strongSwan: radius_config.c File Reference
radius_config.c File Reference
#include "radius_config.h"
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <collections/linked_list.h>
Classes
struct private_radius_config_t
Typedefs
typedef struct
private_radius_config_t private_radius_config_t
Functions
METHOD (radius_config_t, get_socket, radius_socket_t *, private_radius_config_t *this)
METHOD (radius_config_t, put_socket, void, private_radius_config_t *this, radius_socket_t *skt, bool result)
METHOD (radius_config_t, get_nas_identifier, chunk_t, private_radius_config_t *this)
METHOD (radius_config_t, get_preference, int, private_radius_config_t *this)
METHOD (radius_config_t, get_name, char *, private_radius_config_t *this)
METHOD (radius_config_t, get_ref, radius_config_t *, private_radius_config_t *this)
METHOD (radius_config_t, destroy, void, private_radius_config_t *this)
radius_config_t * radius_config_create (char *name, char *address, u_int16_t auth_port, u_int16_t acct_port, char *nas_identifier, char *secret, int sockets, int preference, u_int tries, double timeout, double base)
Typedef Documentation
typedef struct private_radius_config_t private_radius_config_t
Definition at line 44 of file radius_config.c.
Function Documentation
METHOD (radius_config_t , get_socket , radius_socket_t * , private_radius_config_t * this)
Definition at line 107 of file radius_config.c.
References condvar, mutex_t::lock, mutex, SUCCESS, mutex_t::unlock, and condvar_t::wait.
 {
     radius_socket_t *skt;
     this->mutex->lock(this->mutex);
     while (this->sockets->remove_first(this->sockets, (void**)&skt) != SUCCESS)
     {
         this->condvar->wait(this->condvar, this->mutex);
     }
     this->mutex->unlock(this->mutex);
     return skt;
 }
METHOD (radius_config_t , put_socket , void , private_radius_config_t * this, radius_socket_t * skt, bool result)
Definition at line 121 of file radius_config.c.
References condvar, mutex_t::lock, mutex, result, condvar_t::signal, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->sockets->insert_last(this->sockets, skt);
     this->mutex->unlock(this->mutex);
     this->condvar->signal(this->condvar);
     this->reachable = result;
 }
METHOD (radius_config_t , get_nas_identifier , chunk_t , private_radius_config_t * this)
Definition at line 131 of file radius_config.c.
 {
     return this->nas_identifier;
 }
METHOD (radius_config_t , get_preference , int , private_radius_config_t * this)
Definition at line 137 of file radius_config.c.
 {
     int pref;
     if (this->socket_count == 0)
     {   /* don't have sockets, huh? */
         return -1;
     }
     /* calculate preference between 0-100 + boost */
     pref = this->preference;
     pref += this->sockets->get_count(this->sockets) * 100 / this->socket_count;
     if (this->reachable)
     {   /* reachable server get a boost: pref = 110-210 + boost */
         return pref + 110;
     }
     /* Not reachable. Increase preference randomly to let it retry from
      * time to time, especially if other servers have high load. */
     this->retry++;
     if (this->retry % 128 == 0)
     {   /* every 64th request gets 210, same as unloaded reachable */
         return pref + 110;
     }
     if (this->retry % 32 == 0)
     {   /* every 32th request gets 190, wins against average loaded */
         return pref + 90;
     }
     if (this->retry % 8 == 0)
     {   /* every 8th request gets 110, same as server under load */
         return pref + 10;
     }
     /* other get ~100, less than fully loaded */
     return pref;
 }
METHOD (radius_config_t , get_name , char * , private_radius_config_t * this)
Definition at line 172 of file radius_config.c.
References name.
 {
     return this->name;
 }
METHOD (radius_config_t , get_ref , radius_config_t * , private_radius_config_t * this)
Definition at line 178 of file radius_config.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (radius_config_t , destroy , void , private_radius_config_t * this)
Definition at line 186 of file radius_config.c.
References condvar, mutex_t::destroy, condvar_t::destroy, destroy(), free(), mutex, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         this->mutex->destroy(this->mutex);
         this->condvar->destroy(this->condvar);
         this->sockets->destroy_offset(this->sockets,
                                       offsetof(radius_socket_t, destroy));
         free(this);
     }
 }