strongSwan: bio_writer_t Struct Reference
bio_writer_t Struct Reference
bio_writer
#include "bio_writer.h"
Public Attributes
void(* write_uint8)(bio_writer_t *this, u_int8_t value)
void(* write_uint16)(bio_writer_t *this, u_int16_t value)
void(* write_uint24)(bio_writer_t *this, u_int32_t value)
void(* write_uint32)(bio_writer_t *this, u_int32_t value)
void(* write_uint64)(bio_writer_t *this, u_int64_t value)
void(* write_data)(bio_writer_t *this, chunk_t value)
void(* write_data8)(bio_writer_t *this, chunk_t value)
void(* write_data16)(bio_writer_t *this, chunk_t value)
void(* write_data24)(bio_writer_t *this, chunk_t value)
void(* write_data32)(bio_writer_t *this, chunk_t value)
void(* wrap8)(bio_writer_t *this)
void(* wrap16)(bio_writer_t *this)
void(* wrap24)(bio_writer_t *this)
void(* wrap32)(bio_writer_t *this)
chunk_t(* skip)(bio_writer_t *this, size_t len)
chunk_t(* get_buf)(bio_writer_t *this)
chunk_t(* extract_buf)(bio_writer_t *this)
void(* destroy)(bio_writer_t *this)
Detailed Description
Buffered output generator.
Note
Integers are converted to network byte order before writing.
Definition at line 36 of file bio_writer.h.
Member Data Documentation
void(* bio_writer_t::destroy)(bio_writer_t *this)
Destroy a bio_writer_t.
Definition at line 158 of file bio_writer.h.
Referenced by add_unity_split_attribute(), build_application(), build_handshake(), build_public_key(), check_alerts(), do_sasl(), eap_payload_create_nak(), identity_attribute(), ietf_attr_remediation_instr_create_from_string(), imv_attestation_process(), merge_fragments(), METHOD(), negotiate_version(), pb_pdp_referral_msg_create_from_fqdn(), pb_remediation_parameters_msg_create_from_string(), process_sasl(), pt_tls_write(), pts_dh_group_error_create(), pts_dh_nonce_error_create(), pts_hash_alg_error_create(), read_swid_tags(), send_certificate(), send_certificate_request(), send_client_hello(), send_op(), send_sasl_mechs(), send_supported_hash_algorithms(), START_TEST(), and swid_error_create().
chunk_t(* bio_writer_t::extract_buf)(bio_writer_t *this)
Return the encoded data buffer and detach it from the writer (resets the internal buffer).
Returns
chunk to internal buffer (has to be freed)
Definition at line 153 of file bio_writer.h.
Referenced by merge_fragments(), METHOD(), send_op(), and START_TEST().
chunk_t(* bio_writer_t::get_buf)(bio_writer_t *this)
Get the encoded data buffer.
Returns
chunk to internal buffer
Definition at line 145 of file bio_writer.h.
Referenced by add_unity_split_attribute(), assert_writer_after_write(), build_application(), build_handshake(), build_public_key(), check_alerts(), do_sasl(), eap_payload_create_nak(), identity_attribute(), ietf_attr_remediation_instr_create_from_string(), imv_attestation_process(), METHOD(), negotiate_version(), pb_pdp_referral_msg_create_from_fqdn(), pb_remediation_parameters_msg_create_from_string(), process_sasl(), pt_tls_write(), pts_dh_group_error_create(), pts_dh_nonce_error_create(), pts_hash_alg_error_create(), read_swid_tags(), send_certificate(), send_certificate_request(), send_certificate_verify(), send_client_hello(), send_finished(), send_hello_done(), send_key_exchange_dhe(), send_key_exchange_encrypt(), send_sasl_mechs(), send_server_hello(), send_server_key_exchange(), send_supported_hash_algorithms(), START_TEST(), and swid_error_create().
chunk_t(* bio_writer_t::skip)(bio_writer_t *this, size_t len)
Skips len bytes in the buffer, return chunk of skipped data.
The returned chunk is not valid after calling any other writer function (except get_buf()), because a buffer reallocation might move the internal buffer to a different memory location!
Parameters
len number of bytes to skip
Returns
chunk pointing to skipped bytes in the internal buffer
Definition at line 138 of file bio_writer.h.
Referenced by add_unity_split_attribute(), append_ts(), METHOD(), and START_TEST().
void(* bio_writer_t::wrap16)(bio_writer_t *this)
Prepend a 16-bit length header to existing data.
Definition at line 116 of file bio_writer.h.
Referenced by METHOD(), and send_client_hello().
void(* bio_writer_t::wrap24)(bio_writer_t *this)
Prepend a 24-bit length header to existing data.
Definition at line 121 of file bio_writer.h.
void(* bio_writer_t::wrap32)(bio_writer_t *this)
Prepend a 32-bit length header to existing data.
Definition at line 126 of file bio_writer.h.
void(* bio_writer_t::wrap8)(bio_writer_t *this)
Prepend a 8-bit length header to existing data.
Definition at line 111 of file bio_writer.h.
void(* bio_writer_t::write_data)(bio_writer_t *this, chunk_t value)
Append a chunk of data without a length header.
Parameters
value value to append
Definition at line 78 of file bio_writer.h.
Referenced by add_unity_split_attribute(), append_ts(), do_sasl(), imv_attestation_process(), merge_fragments(), METHOD(), pb_pdp_referral_msg_create_from_fqdn(), pt_tls_write(), read_swid_tags(), send_client_hello(), send_finished(), send_key_exchange_dhe(), send_op(), send_server_hello(), send_server_key_exchange(), START_TEST(), and swid_error_create().
void(* bio_writer_t::write_data16)(bio_writer_t *this, chunk_t value)
Append a chunk of data with a 16-bit length header.
Parameters
value value to append
Definition at line 92 of file bio_writer.h.
Referenced by METHOD(), send_certificate_request(), send_client_hello(), send_key_exchange_dhe(), send_key_exchange_encrypt(), and send_server_key_exchange().
void(* bio_writer_t::write_data24)(bio_writer_t *this, chunk_t value)
Append a chunk of data with a 24-bit length header.
Parameters
value value to append
Definition at line 99 of file bio_writer.h.
Referenced by build_handshake(), and send_certificate().
void(* bio_writer_t::write_data32)(bio_writer_t *this, chunk_t value)
Append a chunk of data with a 32-bit length header.
Parameters
value value to append
Definition at line 106 of file bio_writer.h.
Referenced by build_public_key(), ietf_attr_remediation_instr_create_from_string(), METHOD(), pb_remediation_parameters_msg_create_from_string(), and write_ec_identifier().
void(* bio_writer_t::write_data8)(bio_writer_t *this, chunk_t value)
Append a chunk of data with a 8-bit length header.
Parameters
value value to append
Definition at line 85 of file bio_writer.h.
Referenced by do_sasl(), ietf_attr_remediation_instr_create_from_string(), METHOD(), pb_remediation_parameters_msg_create_from_string(), send_certificate_request(), send_client_hello(), send_op(), send_sasl_mechs(), and send_server_hello().
void(* bio_writer_t::write_uint16)(bio_writer_t *this, u_int16_t value)
Append a 16-bit integer to the buffer.
Parameters
value value to append
Definition at line 50 of file bio_writer.h.
Referenced by eap_payload_create_nak(), METHOD(), pb_pdp_referral_msg_create_from_fqdn(), pts_dh_group_error_create(), pts_dh_nonce_error_create(), pts_hash_alg_error_create(), send_client_hello(), send_server_hello(), send_server_key_exchange(), and send_supported_hash_algorithms().
void(* bio_writer_t::write_uint24)(bio_writer_t *this, u_int32_t value)
Append a 24-bit integer to the buffer.
Parameters
value value to append
Definition at line 57 of file bio_writer.h.
Referenced by METHOD(), negotiate_version(), pt_tls_write(), and write_type().
void(* bio_writer_t::write_uint32)(bio_writer_t *this, u_int32_t value)
Append a 32-bit integer to the buffer.
Parameters
value value to append
Definition at line 64 of file bio_writer.h.
Referenced by identity_attribute(), METHOD(), pt_tls_write(), swid_error_create(), and write_type().
void(* bio_writer_t::write_uint64)(bio_writer_t *this, u_int64_t value)
Append a 64-bit integer to the buffer.
Parameters
value value to append
Definition at line 71 of file bio_writer.h.
Referenced by METHOD().
void(* bio_writer_t::write_uint8)(bio_writer_t *this, u_int8_t value)
Append a 8-bit integer to the buffer.
Parameters
value value to append
Definition at line 43 of file bio_writer.h.
Referenced by build_handshake(), check_alerts(), eap_payload_create_nak(), imv_attestation_process(), METHOD(), negotiate_version(), pb_pdp_referral_msg_create_from_fqdn(), process_sasl(), pt_tls_write(), send_certificate_request(), send_client_hello(), send_key_exchange_dhe(), send_op(), send_server_hello(), send_server_key_exchange(), START_TEST(), and write_type().
The documentation for this struct was generated from the following file:
bio_writer.h