strongSwan: uci_plugin.c File Reference
uci_plugin.c File Reference
#include "uci_plugin.h"
#include "uci_config.h"
#include "uci_creds.h"
#include "uci_control.h"
#include <daemon.h>
Classes
struct private_uci_plugin_t
Macros
#define UCI_PACKAGE "strongswan"
Typedefs
typedef struct private_uci_plugin_t private_uci_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_uci_plugin_t *this)
static bool plugin_cb (private_uci_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_uci_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_uci_plugin_t *this)
plugin_t * uci_plugin_create ()
Macro Definition Documentation
#define UCI_PACKAGE "strongswan"
UCI package name to use for lookups
Definition at line 26 of file uci_plugin.c.
Referenced by uci_plugin_create().
Typedef Documentation
typedef struct private_uci_plugin_t private_uci_plugin_t
Definition at line 28 of file uci_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_uci_plugin_t * this)
Definition at line 61 of file uci_plugin.c.
 {
     return "uci";
 }
METHOD (plugin_t , get_features , int , private_uci_plugin_t * this, plugin_feature_t * features[])
Definition at line 87 of file uci_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "uci"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_uci_plugin_t * this)
Definition at line 98 of file uci_plugin.c.
References creds, conf_parser_t::destroy, mem_cred_t::destroy, free(), and parser.
 {
     this->config->destroy(this->config);
     this->creds->destroy(this->creds);
     this->parser->destroy(this->parser);
     this->control->destroy(this->control);
     free(this);
 }
static bool plugin_cb (private_uci_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register backend
Definition at line 70 of file uci_plugin.c.
References backend_manager_t::add_backend, credential_manager_t::add_set, daemon_t::backends, charon, library_t::credmgr, lib, backend_manager_t::remove_backend, credential_manager_t::remove_set, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->backends->add_backend(charon->backends, &this->config->backend);
         lib->credmgr->add_set(lib->credmgr, &this->creds->credential_set);
     }
     else
     {
         charon->backends->remove_backend(charon->backends,
                                          &this->config->backend);
         lib->credmgr->remove_set(lib->credmgr, &this->creds->credential_set);
     }
     return TRUE;
 }
plugin_t* uci_plugin_create ()
Definition at line 111 of file uci_plugin.c.
References creds, INIT, parser, uci_config_create(), uci_control_create(), uci_creds_create(), UCI_PACKAGE, and uci_parser_create().
 {
     private_uci_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .parser = uci_parser_create(UCI_PACKAGE),
         .control = uci_control_create(),
     );
     this->config = uci_config_create(this->parser);
     this->creds = uci_creds_create(this->parser);
     return &this->public.plugin;
 }