strongSwan: nm_creds_t Struct Reference
nm_creds_t Struct Reference
nm_creds
#include "nm_creds.h"
Public Attributes
credential_set_t set
void(* add_certificate)(nm_creds_t *this, certificate_t *cert)
void(* load_ca_dir)(nm_creds_t *this, char *dir)
void(* set_username_password)(nm_creds_t *this, identification_t *id, char *password)
void(* set_key_password)(nm_creds_t *this, char *password)
void(* set_pin)(nm_creds_t *this, chunk_t keyid, char *pin)
void(* set_cert_and_key)(nm_creds_t *this, certificate_t *cert, private_key_t *key)
void(* clear)(nm_creds_t *this)
void(* destroy)(nm_creds_t *this)
Detailed Description
NetworkManager credentials helper.
Definition at line 32 of file nm_creds.h.
Member Data Documentation
void(* nm_creds_t::add_certificate)(nm_creds_t *this, certificate_t *cert)
Add a trusted gateway certificate to serve by this set.
Parameters
cert certificate to serve
Definition at line 44 of file nm_creds.h.
Referenced by connect_().
void(* nm_creds_t::clear)(nm_creds_t *this)
Clear the stored credentials.
Definition at line 89 of file nm_creds.h.
Referenced by connect_().
void(* nm_creds_t::destroy)(nm_creds_t *this)
Destroy a nm_creds instance.
Definition at line 94 of file nm_creds.h.
void(* nm_creds_t::load_ca_dir)(nm_creds_t *this, char *dir)
Load CA certificates recursively from a directory.
Parameters
dir directory to PEM encoded CA certificates
Definition at line 51 of file nm_creds.h.
Referenced by connect_().
credential_set_t nm_creds_t::set
Implements credential_set_t
Definition at line 37 of file nm_creds.h.
void(* nm_creds_t::set_cert_and_key)(nm_creds_t *this, certificate_t *cert, private_key_t *key)
Set the certificate and private key to use for client authentication.
Parameters
cert client certificate
key associated private key
Definition at line 83 of file nm_creds.h.
Referenced by connect_(), and find_smartcard_key().
void(* nm_creds_t::set_key_password)(nm_creds_t *this, char *password)
Set the passphrase to use for private key decryption.
Parameters
password password to use
Definition at line 67 of file nm_creds.h.
Referenced by connect_().
void(* nm_creds_t::set_pin)(nm_creds_t *this, chunk_t keyid, char *pin)
Set the PIN to unlock a smartcard.
Parameters
keyid keyid of the smartcard key
pin PIN
Definition at line 75 of file nm_creds.h.
Referenced by find_smartcard_key().
void(* nm_creds_t::set_username_password)(nm_creds_t *this, identification_t *id, char *password)
Set the username/password for authentication.
Parameters
id ID of the user
password password to use for authentication
Definition at line 59 of file nm_creds.h.
Referenced by connect_().
The documentation for this struct was generated from the following file:
nm_creds.h