strongSwan: forecast_listener
forecast_listener
forecast
Classes
struct forecast_listener_t
Typedefs
typedef struct forecast_listener_t forecast_listener_t
Functions
forecast_listener_t * forecast_listener_create ()
Detailed Description
Typedef Documentation
typedef struct forecast_listener_t forecast_listener_t
Definition at line 26 of file forecast_listener.h.
Function Documentation
forecast_listener_t* forecast_listener_create ()
Create a forecast_listener instance.
See header
Definition at line 658 of file forecast_listener.c.
References settings_t::get_str, INIT, lib, linked_list_create(), library_t::ns, rwlock_create(), RWLOCK_TYPE_DEFAULT, and library_t::settings.
Referenced by forecast_plugin_create().
 {
     private_forecast_listener_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .ike_update = _ike_update,
                 .child_updown = _child_updown,
                 .child_rekey = _child_rekey,
             },
             .create_enumerator = _create_enumerator,
             .set_broadcast = _set_broadcast,
             .destroy = _destroy,
         },
         .entries = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .reinject_configs = lib->settings->get_str(lib->settings,
                                 "%s.plugins.forecast.reinject", "", lib->ns),
     );
     return &this->public;
 }