strongSwan: nm_creds.c File Reference
nm_creds.c File Reference
#include "nm_creds.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <daemon.h>
#include <threading/rwlock.h>
#include <credentials/certificates/x509.h>
Classes
struct private_nm_creds_t
struct cert_data_t
struct shared_enumerator_t
Typedefs
typedef struct private_nm_creds_t private_nm_creds_t
Functions
static enumerator_t * create_usercert_enumerator (private_nm_creds_t *this, certificate_type_t cert, key_type_t key)
static void cert_data_destroy (cert_data_t *data)
static bool cert_filter (cert_data_t *data, certificate_t **in, certificate_t **out)
static enumerator_t * create_trusted_cert_enumerator (private_nm_creds_t *this, key_type_t key, identification_t *id)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_nm_creds_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (credential_set_t, create_private_enumerator, enumerator_t *, private_nm_creds_t *this, key_type_t type, identification_t *id)
METHOD (enumerator_t, shared_enumerate, bool, shared_enumerator_t *this, shared_key_t **key, id_match_t *me, id_match_t *other)
METHOD (enumerator_t, shared_destroy, void, shared_enumerator_t *this)
METHOD (credential_set_t, create_shared_enumerator, enumerator_t *, private_nm_creds_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
METHOD (nm_creds_t, add_certificate, void, private_nm_creds_t *this, certificate_t *cert)
static void load_ca_file (private_nm_creds_t *this, char *file)
METHOD (nm_creds_t, load_ca_dir, void, private_nm_creds_t *this, char *dir)
METHOD (nm_creds_t, set_username_password, void, private_nm_creds_t *this, identification_t *id, char *password)
METHOD (nm_creds_t, set_key_password, void, private_nm_creds_t *this, char *password)
METHOD (nm_creds_t, set_pin, void, private_nm_creds_t *this, chunk_t keyid, char *pin)
METHOD (nm_creds_t, set_cert_and_key, void, private_nm_creds_t *this, certificate_t *cert, private_key_t *key)
METHOD (nm_creds_t, clear, void, private_nm_creds_t *this)
METHOD (nm_creds_t, destroy, void, private_nm_creds_t *this)
nm_creds_t * nm_creds_create ()
Typedef Documentation
typedef struct private_nm_creds_t private_nm_creds_t
Definition at line 26 of file nm_creds.c.
Function Documentation
static void cert_data_destroy (cert_data_t * data) static
Destroy CA certificate enumerator data
Definition at line 126 of file nm_creds.c.
References free(), private_nm_creds_t::lock, cert_data_t::this, and rwlock_t::unlock.
Referenced by create_trusted_cert_enumerator().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static bool cert_filter (cert_data_t * data, certificate_t ** in, certificate_t ** out) static
Filter function for certificates enumerator
Definition at line 135 of file nm_creds.c.
References cert, FALSE, identification_t::get_encoding, certificate_t::get_public_key, identification_t::get_type, certificate_t::has_subject, cert_data_t::id, ID_KEY_ID, in, cert_data_t::key, KEY_ANY, public, and TRUE.
Referenced by create_trusted_cert_enumerator().
 {
     certificate_t *cert = *in;
     public_key_t *public;
     public = cert->get_public_key(cert);
     if (!public)
     {
         return FALSE;
     }
     if (data->key != KEY_ANY && public->get_type(public) != data->key)
     {
         public->destroy(public);
         return FALSE;
     }
     if (data->id && data->id->get_type(data->id) == ID_KEY_ID &&
         public->has_fingerprint(public, data->id->get_encoding(data->id)))
     {
         public->destroy(public);
         *out = cert;
         return TRUE;
     }
     public->destroy(public);
     if (data->id && !cert->has_subject(cert, data->id))
     {
         return FALSE;
     }
     *out = cert;
     return TRUE;
 }
static enumerator_t* create_trusted_cert_enumerator (private_nm_creds_t * this, key_type_t key, identification_t * id) static
Create enumerator for trusted certificates
Definition at line 170 of file nm_creds.c.
References cert_data_destroy(), cert_filter(), data, enumerator_create_filter(), INIT, and lock.
Referenced by METHOD().
 {
     cert_data_t *data;
     INIT(data,
         .this = this,
         .id = id,
         .key = key,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(
                     this->certs->create_enumerator(this->certs),
                     (void*)cert_filter, data, (void*)cert_data_destroy);
 }
static enumerator_t* create_usercert_enumerator (private_nm_creds_t * this, certificate_type_t cert, key_type_t key) static
Enumerator for user certificate
Definition at line 82 of file nm_creds.c.
References CERT_ANY, public_key_t::destroy, enumerator_create_cleaner(), enumerator_create_single(), key, KEY_ANY, lock, public, and spinlock_t::unlock.
Referenced by METHOD().
 {
     public_key_t *public;
     if (cert != CERT_ANY && cert != this->usercert->get_type(this->usercert))
     {
         return NULL;
     }
     if (key != KEY_ANY)
     {
         public = this->usercert->get_public_key(this->usercert);
         if (!public)
         {
             return NULL;
         }
         if (public->get_type(public) != key)
         {
             public->destroy(public);
             return NULL;
         }
         public->destroy(public);
     }
     this->lock->read_lock(this->lock);
     return enumerator_create_cleaner(
                                 enumerator_create_single(this->usercert, NULL),
                                 (void*)this->lock->unlock, this->lock);
 }
static void load_ca_file (private_nm_creds_t * this, char * file) static
Load a certificate file
Definition at line 334 of file nm_creds.c.
References BUILD_END, BUILD_FROM_FILE, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG2, DBG_CFG, certificate_t::get_subject, lib, and X509_SELF_SIGNED.
Referenced by METHOD().
 {
     certificate_t *cert;
     /* We add the CA constraint, as many CAs miss it */
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_FROM_FILE, file, BUILD_END);
     if (!cert)
     {
         DBG1(DBG_CFG, "loading CA certificate '%s' failed", file);
     }
     else
     {
         DBG2(DBG_CFG, "loaded CA certificate '%Y'", cert->get_subject(cert));
         x509_t *x509 = (x509_t*)cert;
         if (!(x509->get_flags(x509) & X509_SELF_SIGNED))
         {
             DBG1(DBG_CFG, "%Y is not self signed", cert->get_subject(cert));
         }
         this->certs->insert_last(this->certs, cert);
     }
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_nm_creds_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 187 of file nm_creds.c.
References CERT_ANY, CERT_X509, create_trusted_cert_enumerator(), create_usercert_enumerator(), and identification_t::equals.
 {
     if (id && this->usercert &&
         id->equals(id, this->usercert->get_subject(this->usercert)))
     {
         return create_usercert_enumerator(this, cert, key);
     }
     if (cert == CERT_X509 || cert == CERT_ANY)
     {
         return create_trusted_cert_enumerator(this, key, id);
     }
     return NULL;
 }
METHOD (credential_set_t , create_private_enumerator , enumerator_t * , private_nm_creds_t * this, key_type_t type, identification_t * id)
Definition at line 203 of file nm_creds.c.
References enumerator_create_cleaner(), enumerator_create_single(), identification_t::get_encoding, identification_t::get_type, ID_ANY, ID_KEY_ID, key, KEY_ANY, lock, and spinlock_t::unlock.
 {
     if (this->key == NULL)
     {
         return NULL;
     }
     if (type != KEY_ANY && type != this->key->get_type(this->key))
     {
         return NULL;
     }
     if (id && id->get_type(id) != ID_ANY)
     {
         if (id->get_type(id) != ID_KEY_ID ||
             !this->key->has_fingerprint(this->key, id->get_encoding(id)))
         {
             return NULL;
         }
     }
     this->lock->read_lock(this->lock);
     return enumerator_create_cleaner(enumerator_create_single(this->key, NULL),
                                      (void*)this->lock->unlock, this->lock);
 }
METHOD (enumerator_t , shared_enumerate , bool , shared_enumerator_t * this, shared_key_t ** key, id_match_t * me, id_match_t * other)
Definition at line 237 of file nm_creds.c.
References FALSE, ID_MATCH_ANY, ID_MATCH_PERFECT, key, and TRUE.
 {
     if (this->done)
     {
         return FALSE;
     }
     *key = this->key;
     if (me)
     {
         *me = ID_MATCH_PERFECT;
     }
     if (other)
     {
         *other = ID_MATCH_ANY;
     }
     this->done = TRUE;
     return TRUE;
 }
METHOD (enumerator_t , shared_destroy , void , shared_enumerator_t * this)
Definition at line 258 of file nm_creds.c.
References free(), key, lock, and spinlock_t::unlock.
 {
     this->key->destroy(this->key);
     this->this->lock->unlock(this->this->lock);
     free(this);
 }
METHOD (credential_set_t , create_shared_enumerator , enumerator_t * , private_nm_creds_t * this, shared_key_type_t type, identification_t * me, identification_t * other)
Definition at line 266 of file nm_creds.c.
References chunk_clone, chunk_create(), chunk_equals(), destroy(), identification_t::equals, identification_t::get_encoding, INIT, shared_enumerator_t::key, key, keyid(), lock, shared_enumerator_t::public, SHARED_EAP, SHARED_IKE, shared_key_create(), SHARED_PIN, SHARED_PRIVATE_KEY_PASS, and spinlock_t::unlock.
 {
     shared_enumerator_t *enumerator;
     chunk_t key;
     this->lock->read_lock(this->lock);
     switch (type)
     {
         case SHARED_EAP:
         case SHARED_IKE:
             if (!this->pass || !this->user)
             {
                 goto no_secret;
             }
             if (me && !me->equals(me, this->user))
             {
                 goto no_secret;
             }
             key = chunk_create(this->pass, strlen(this->pass));
             break;
         case SHARED_PRIVATE_KEY_PASS:
             if (!this->keypass)
             {
                 goto no_secret;
             }
             key = chunk_create(this->keypass, strlen(this->keypass));
             break;
         case SHARED_PIN:
             if (!this->keypass || !me ||
                 !chunk_equals(me->get_encoding(me), this->keyid))
             {
                 goto no_secret;
             }
             key = chunk_create(this->keypass, strlen(this->keypass));
             break;
         default:
             goto no_secret;
     }
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_shared_enumerate,
             .destroy = _shared_destroy,
         },
         .this = this,
     );
     enumerator->key = shared_key_create(type, chunk_clone(key));
     return &enumerator->public;
 no_secret:
     this->lock->unlock(this->lock);
     return NULL;
 }
METHOD (nm_creds_t , add_certificate , void , private_nm_creds_t * this, certificate_t * cert)
Definition at line 323 of file nm_creds.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->certs->insert_last(this->certs, cert);
     this->lock->unlock(this->lock);
 }
METHOD (nm_creds_t , load_ca_dir , void , private_nm_creds_t * this, char * dir)
Definition at line 357 of file nm_creds.c.
References enumerator_create_directory(), load_ca_dir(), load_ca_file(), and rel().
 {
     enumerator_t *enumerator;
     char *rel, *abs;
     struct stat st;
     enumerator = enumerator_create_directory(dir);
     if (enumerator)
     {
         while (enumerator->enumerate(enumerator, &rel, &abs, &st))
         {
             /* skip '.', '..' and hidden files */
             if (rel[0] != '.')
             {
                 if (S_ISDIR(st.st_mode))
                 {
                     load_ca_dir(this, abs);
                 }
                 else if (S_ISREG(st.st_mode))
                 {
                     load_ca_file(this, abs);
                 }
             }
         }
         enumerator->destroy(enumerator);
     }
 }
METHOD (nm_creds_t , set_username_password , void , private_nm_creds_t * this, identification_t * id, char * password)
Definition at line 386 of file nm_creds.c.
References DESTROY_IF, free(), lock, strdupnull(), and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     DESTROY_IF(this->user);
     this->user = id->clone(id);
     free(this->pass);
     this->pass = strdupnull(password);
     this->lock->unlock(this->lock);
 }
METHOD (nm_creds_t , set_key_password , void , private_nm_creds_t * this, char * password)
Definition at line 397 of file nm_creds.c.
References free(), lock, strdupnull(), and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     free(this->keypass);
     this->keypass = strdupnull(password);
     this->lock->unlock(this->lock);
 }
METHOD (nm_creds_t , set_pin , void , private_nm_creds_t * this, chunk_t keyid, char * pin)
Definition at line 406 of file nm_creds.c.
References chunk_clone, free(), lock, chunk_t::ptr, strdupnull(), and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     free(this->keypass);
     free(this->keyid.ptr);
     this->keypass = strdupnull(pin);
     this->keyid = chunk_clone(keyid);
     this->lock->unlock(this->lock);
 }
METHOD (nm_creds_t , set_cert_and_key , void , private_nm_creds_t * this, certificate_t * cert, private_key_t * key)
Definition at line 417 of file nm_creds.c.
References cert, DESTROY_IF, key, lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     DESTROY_IF(this->key);
     DESTROY_IF(this->usercert);
     this->key = key;
     this->usercert = cert;
     this->lock->unlock(this->lock);
 }
METHOD (nm_creds_t , clear , void , private_nm_creds_t * this)
Definition at line 428 of file nm_creds.c.
References cert, chunk_empty, certificate_t::destroy, DESTROY_IF, free(), keyid(), and SUCCESS.
 {
     certificate_t *cert;
     while (this->certs->remove_last(this->certs, (void**)&cert) == SUCCESS)
     {
         cert->destroy(cert);
     }
     DESTROY_IF(this->user);
     free(this->pass);
     free(this->keypass);
     free(this->keyid.ptr);
     DESTROY_IF(this->usercert);
     DESTROY_IF(this->key);
     this->key = NULL;
     this->usercert = NULL;
     this->pass = NULL;
     this->user = NULL;
     this->keypass = NULL;
     this->keyid = chunk_empty;
 }
METHOD (nm_creds_t , destroy , void , private_nm_creds_t * this)
Definition at line 451 of file nm_creds.c.
References spinlock_t::destroy, free(), and lock.
 {
     clear(this);
     this->certs->destroy(this->certs);
     this->lock->destroy(this->lock);
     free(this);
 }