strongSwan: backend_manager_t Struct Reference
backend_manager_t Struct Reference
backend_manager
#include "backend_manager.h"
Public Attributes
ike_cfg_t *(* get_ike_cfg)(backend_manager_t *this, host_t *my_host, host_t *other_host, ike_version_t version)
peer_cfg_t *(* get_peer_cfg_by_name)(backend_manager_t *this, char *name)
enumerator_t *(* create_peer_cfg_enumerator)(backend_manager_t *this, host_t *me, host_t *other, identification_t *my_id, identification_t *other_id, ike_version_t version)
void(* add_backend)(backend_manager_t *this, backend_t *backend)
void(* remove_backend)(backend_manager_t *this, backend_t *backend)
void(* destroy)(backend_manager_t *this)
Detailed Description
A loader and multiplexer to use multiple backends.
Charon allows the use of multiple configuration backends simultaneously. To access all this backends by a single call, this class wraps multiple backends behind a single object.
+---------+      +-----------+         +--------------+     |
|         |      |           |       +--------------+ |     |
| daemon  |----->| backend_- |     +--------------+ |-+  <==|==> IPC
|  core   |      | manager   |---->|   backends   |-+       |
|         |----->|           |     +--------------+         |
|         |      |           |                              |
+---------+      +-----------+                              |
Definition at line 52 of file backend_manager.h.
Member Data Documentation
void(* backend_manager_t::add_backend)(backend_manager_t *this, backend_t *backend)
Register a backend on the manager.
Parameters
backend backend to register
Definition at line 95 of file backend_manager.h.
Referenced by main(), open_database(), plugin_cb(), register_load_tester(), register_vici(), setup_tunnel(), and stroke_socket_create().
enumerator_t*(* backend_manager_t::create_peer_cfg_enumerator)(backend_manager_t *this, host_t *me, host_t *other, identification_t *my_id, identification_t *other_id, ike_version_t version)
Create an enumerator over all matching peer configs.
Pass NULL as parameters to match any. The enumerator enumerates over peer_cfgs, ordered by priority (best match first).
Parameters
me local address
other remote address
my_id IDr in first authentication round
other_id IDi in first authentication round
version IKE version to get a config for
Returns
enumerator over peer_cfg_t
Definition at line 87 of file backend_manager.h.
Referenced by CALLBACK(), find_child_cfg(), load_cfg_candidates(), lookup_shared_key(), METHOD(), request_query_config(), select_compliant_config(), and status().
void(* backend_manager_t::destroy)(backend_manager_t *this)
Destroys a backend_manager_t object.
Definition at line 107 of file backend_manager.h.
ike_cfg_t*(* backend_manager_t::get_ike_cfg)(backend_manager_t *this, host_t *my_host, host_t *other_host, ike_version_t version)
Get an ike_config identified by two hosts.
Parameters
my_host address of own host
other_host address of remote host
version IKE version to get a config for
Returns
matching ike_config, or NULL if none found
Definition at line 62 of file backend_manager.h.
Referenced by METHOD().
peer_cfg_t*(* backend_manager_t::get_peer_cfg_by_name)(backend_manager_t *this, char *name)
Get a peer_config identified by it's name.
Parameters
name name of the peer_config
Returns
matching peer_config, or NULL if none found
Definition at line 72 of file backend_manager.h.
Referenced by build_peer_cfg(), do_load_test(), initiate(), METHOD(), on_accept(), process_ike_update(), and request_control_initiate().
void(* backend_manager_t::remove_backend)(backend_manager_t *this, backend_t *backend)
Unregister a backend.
Parameters
backend backend to unregister
Definition at line 102 of file backend_manager.h.
Referenced by cleanup(), METHOD(), open_database(), plugin_cb(), register_load_tester(), and register_vici().
The documentation for this struct was generated from the following file:
backend_manager.h