strongSwan: tls
tls
libtls
Modules
tls_aead
Classes
struct tls_t
Macros
#define TLS_MAX_FRAGMENT_LEN 16384
Typedefs
typedef enum tls_version_t tls_version_t
typedef enum tls_content_type_t tls_content_type_t
typedef enum tls_handshake_type_t tls_handshake_type_t
typedef enum tls_purpose_t tls_purpose_t
typedef struct tls_t tls_t
Enumerations
enum tls_version_t {
SSL_2_0 = 0x0200, SSL_3_0 = 0x0300, TLS_1_0 = 0x0301, TLS_1_1 = 0x0302,
TLS_1_2 = 0x0303
}
enum tls_content_type_t { TLS_CHANGE_CIPHER_SPEC = 20, TLS_ALERT = 21, TLS_HANDSHAKE = 22, TLS_APPLICATION_DATA = 23 }
enum tls_handshake_type_t {
TLS_HELLO_REQUEST = 0, TLS_CLIENT_HELLO = 1, TLS_SERVER_HELLO = 2, TLS_CERTIFICATE = 11,
TLS_SERVER_KEY_EXCHANGE = 12, TLS_CERTIFICATE_REQUEST = 13, TLS_SERVER_HELLO_DONE = 14, TLS_CERTIFICATE_VERIFY = 15,
TLS_CLIENT_KEY_EXCHANGE = 16, TLS_FINISHED = 20
}
enum tls_purpose_t {
TLS_PURPOSE_EAP_TLS, TLS_PURPOSE_EAP_TTLS, TLS_PURPOSE_EAP_PEAP, TLS_PURPOSE_GENERIC,
TLS_PURPOSE_GENERIC_NULLOK, TLS_PURPOSE_EAP_TNC
}
enum tls_extension_t {
TLS_EXT_SERVER_NAME = 0, TLS_EXT_MAX_FRAGMENT_LENGTH = 1, TLS_EXT_CLIENT_CERTIFICATE_URL = 2, TLS_EXT_TRUSTED_CA_KEYS = 3,
TLS_EXT_TRUNCATED_HMAC = 4, TLS_EXT_STATUS_REQUEST = 5, TLS_EXT_ELLIPTIC_CURVES = 10, TLS_EXT_EC_POINT_FORMATS = 11,
TLS_EXT_SIGNATURE_ALGORITHMS = 13, TLS_EXT_RENEGOTIATION_INFO = 65281
}
enum tls_name_type_t { TLS_NAME_TYPE_HOST_NAME = 0 }
Functions
void libtls_init (void)
tls_t * tls_create (bool is_server, identification_t *server, identification_t *peer, tls_purpose_t purpose, tls_application_t *application, tls_cache_t *cache)
Variables
enum_name_t * tls_version_names
enum_name_t * tls_content_type_names
enum_name_t * tls_handshake_type_names
enum_name_t * tls_extension_names
Detailed Description
Macro Definition Documentation
#define TLS_MAX_FRAGMENT_LEN 16384
Maximum size of a TLS fragment as defined by section 6.2.1. "Fragmentation" of RFC 5246 TLS 1.2
Definition at line 33 of file tls.h.
Referenced by METHOD(), process_application(), process_handshake(), and tnccs_20_create().
Typedef Documentation
typedef enum tls_content_type_t tls_content_type_t
Definition at line 36 of file tls.h.
typedef enum tls_handshake_type_t tls_handshake_type_t
Definition at line 37 of file tls.h.
typedef enum tls_purpose_t tls_purpose_t
Definition at line 38 of file tls.h.
typedef struct tls_t tls_t
Definition at line 39 of file tls.h.
typedef enum tls_version_t tls_version_t
Definition at line 35 of file tls.h.
Enumeration Type Documentation
enum tls_content_type_t
TLS higher level content type
Enumerator
TLS_CHANGE_CIPHER_SPEC
TLS_ALERT
TLS_HANDSHAKE
TLS_APPLICATION_DATA
Definition at line 65 of file tls.h.
{
     TLS_CHANGE_CIPHER_SPEC = 20,
     TLS_ALERT = 21,
     TLS_HANDSHAKE = 22,
     TLS_APPLICATION_DATA = 23,
 };
enum tls_extension_t
TLS Hello extension types.
Enumerator
TLS_EXT_SERVER_NAME
Server name the client wants to talk to
TLS_EXT_MAX_FRAGMENT_LENGTH
request a maximum fragment size
TLS_EXT_CLIENT_CERTIFICATE_URL
indicate client certificate URL support
TLS_EXT_TRUSTED_CA_KEYS
list of CA the client trusts
TLS_EXT_TRUNCATED_HMAC
request MAC truncation to 80-bit
TLS_EXT_STATUS_REQUEST
list of OCSP responders the client trusts
TLS_EXT_ELLIPTIC_CURVES
list of supported elliptic curves
TLS_EXT_EC_POINT_FORMATS
supported point formats
TLS_EXT_SIGNATURE_ALGORITHMS
list supported signature algorithms
TLS_EXT_RENEGOTIATION_INFO
cryptographic binding for RFC 5746 renegotiation indication
Definition at line 119 of file tls.h.
                      {
     TLS_EXT_SERVER_NAME = 0,
     TLS_EXT_MAX_FRAGMENT_LENGTH = 1,
     TLS_EXT_CLIENT_CERTIFICATE_URL = 2,
     TLS_EXT_TRUSTED_CA_KEYS = 3,
     TLS_EXT_TRUNCATED_HMAC = 4,
     TLS_EXT_STATUS_REQUEST = 5,
     TLS_EXT_ELLIPTIC_CURVES = 10,
     TLS_EXT_EC_POINT_FORMATS = 11,
     TLS_EXT_SIGNATURE_ALGORITHMS = 13,
     TLS_EXT_RENEGOTIATION_INFO = 65281,
 };
enum tls_handshake_type_t
TLS handshake subtype
Enumerator
TLS_HELLO_REQUEST
TLS_CLIENT_HELLO
TLS_SERVER_HELLO
TLS_CERTIFICATE
TLS_SERVER_KEY_EXCHANGE
TLS_CERTIFICATE_REQUEST
TLS_SERVER_HELLO_DONE
TLS_CERTIFICATE_VERIFY
TLS_CLIENT_KEY_EXCHANGE
TLS_FINISHED
Definition at line 80 of file tls.h.
{
     TLS_HELLO_REQUEST = 0,
     TLS_CLIENT_HELLO = 1,
     TLS_SERVER_HELLO = 2,
     TLS_CERTIFICATE = 11,
     TLS_SERVER_KEY_EXCHANGE = 12,
     TLS_CERTIFICATE_REQUEST = 13,
     TLS_SERVER_HELLO_DONE = 14,
     TLS_CERTIFICATE_VERIFY = 15,
     TLS_CLIENT_KEY_EXCHANGE = 16,
     TLS_FINISHED = 20,
 };
enum tls_name_type_t
Enumerator
TLS_NAME_TYPE_HOST_NAME
Definition at line 142 of file tls.h.
                      {
     TLS_NAME_TYPE_HOST_NAME = 0,
 };
enum tls_purpose_t
Purpose the TLS stack is initiated for.
Enumerator
TLS_PURPOSE_EAP_TLS
authentication in EAP-TLS
TLS_PURPOSE_EAP_TTLS
outer authentication and protection in EAP-TTLS
TLS_PURPOSE_EAP_PEAP
outer authentication and protection in EAP-PEAP
TLS_PURPOSE_GENERIC
non-EAP TLS
TLS_PURPOSE_GENERIC_NULLOK
non-EAP TLS accepting NULL encryption
TLS_PURPOSE_EAP_TNC
EAP binding for TNC
Definition at line 101 of file tls.h.
                    {
     TLS_PURPOSE_EAP_TLS,
     TLS_PURPOSE_EAP_TTLS,
     TLS_PURPOSE_EAP_PEAP,
     TLS_PURPOSE_GENERIC,
     TLS_PURPOSE_GENERIC_NULLOK,
     TLS_PURPOSE_EAP_TNC
 };
enum tls_version_t
TLS/SSL version numbers
Enumerator
SSL_2_0
SSL_3_0
TLS_1_0
TLS_1_1
TLS_1_2
Definition at line 49 of file tls.h.
                    {
     SSL_2_0 = 0x0200,
     SSL_3_0 = 0x0300,
     TLS_1_0 = 0x0301,
     TLS_1_1 = 0x0302,
     TLS_1_2 = 0x0303,
 };
Function Documentation
void libtls_init (void)
Dummy libtls initialization function needed for integrity test
Described in header.
Definition at line 188 of file tls.c.
 {
     /* empty */
 }
tls_t* tls_create (bool is_server, identification_t * server, identification_t * peer, tls_purpose_t purpose, tls_application_t * application, tls_cache_t * cache)
Create a tls instance.
Parameters
is_server TRUE to act as server, FALSE for client
server server identity
peer peer identity, NULL for no client authentication
purpose purpose this TLS stack instance is used for
application higher layer application or NULL if none
cache session cache to use, or NULL
Returns
TLS stack
See header
Definition at line 444 of file tls.c.
References settings_t::add_fallback, tls_peer_t::handshake, tls_server_t::handshake, INIT, lib, library_t::ns, library_t::settings, TLS_1_2, tls_alert_create(), tls_compression_create(), tls_crypto_create(), tls_fragmentation_create(), tls_peer_create(), tls_protection_create(), TLS_PURPOSE_EAP_PEAP, TLS_PURPOSE_EAP_TLS, TLS_PURPOSE_EAP_TTLS, TLS_PURPOSE_GENERIC, TLS_PURPOSE_GENERIC_NULLOK, and tls_server_create().
Referenced by eap_peap_create(), eap_tls_create(), eap_ttls_create(), and tls_socket_create().
 {
     private_tls_t *this;
     switch (purpose)
     {
         case TLS_PURPOSE_EAP_TLS:
         case TLS_PURPOSE_EAP_TTLS:
         case TLS_PURPOSE_EAP_PEAP:
         case TLS_PURPOSE_GENERIC:
         case TLS_PURPOSE_GENERIC_NULLOK:
             break;
         default:
             return NULL;
     }
     INIT(this,
         .public = {
             .process = _process,
             .build = _build,
             .is_server = _is_server,
             .get_server_id = _get_server_id,
             .get_peer_id = _get_peer_id,
             .get_version = _get_version,
             .set_version = _set_version,
             .get_purpose = _get_purpose,
             .is_complete = _is_complete,
             .get_eap_msk = _get_eap_msk,
             .get_auth = _get_auth,
             .destroy = _destroy,
         },
         .is_server = is_server,
         .version = TLS_1_2,
         .application = application,
         .purpose = purpose,
     );
     lib->settings->add_fallback(lib->settings, "%s.tls", "libtls", lib->ns);
     this->crypto = tls_crypto_create(&this->public, cache);
     this->alert = tls_alert_create();
     if (is_server)
     {
         this->handshake = &tls_server_create(&this->public, this->crypto,
                                         this->alert, server, peer)->handshake;
     }
     else
     {
         this->handshake = &tls_peer_create(&this->public, this->crypto,
                                         this->alert, peer, server)->handshake;
     }
     this->fragmentation = tls_fragmentation_create(this->handshake, this->alert,
                                                    this->application, purpose);
     this->compression = tls_compression_create(this->fragmentation, this->alert);
     this->protection = tls_protection_create(this->compression, this->alert);
     this->crypto->set_protection(this->crypto, this->protection);
     return &this->public;
 }
Variable Documentation
enum_name_t* tls_content_type_names
Enum names for tls_content_type_t
Referenced by METHOD().
enum_name_t* tls_extension_names
Enum names for tls_extension_t
Referenced by process_client_hello().
enum_name_t* tls_handshake_type_names
Enum names for tls_handshake_type_t
Referenced by build_handshake(), METHOD(), and process_handshake().
enum_name_t* tls_version_names
Enum names for tls_version_t
Referenced by process_client_hello(), and process_server_hello().