strongSwan: vici_dispatcher.c File Reference
vici_dispatcher.c File Reference
#include "vici_dispatcher.h"
#include "vici_socket.h"
#include <bio/bio_reader.h>
#include <bio/bio_writer.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <threading/thread.h>
#include <collections/array.h>
#include <collections/hashtable.h>
Classes
struct private_vici_dispatcher_t
struct command_t
struct event_t
struct release_data_t
Typedefs
typedef struct
private_vici_dispatcher_t private_vici_dispatcher_t
Functions
static void send_op (private_vici_dispatcher_t *this, u_int id, vici_operation_t op, char *name, vici_message_t *message)
static void register_event (private_vici_dispatcher_t *this, char *name, u_int id)
static void unregister_event (private_vici_dispatcher_t *this, char *name, u_int id)
CALLBACK (release_command, void, release_data_t *release)
void process_request (private_vici_dispatcher_t *this, char *name, u_int id, chunk_t data)
CALLBACK (inbound, void, private_vici_dispatcher_t *this, u_int id, chunk_t data)
CALLBACK (connect_, void, private_vici_dispatcher_t *this, u_int id)
CALLBACK (disconnect, void, private_vici_dispatcher_t *this, u_int id)
METHOD (vici_dispatcher_t, manage_command, void, private_vici_dispatcher_t *this, char *name, vici_command_cb_t cb, void *user)
METHOD (vici_dispatcher_t, manage_event, void, private_vici_dispatcher_t *this, char *name, bool reg)
METHOD (vici_dispatcher_t, has_event_listeners, bool, private_vici_dispatcher_t *this, char *name)
METHOD (vici_dispatcher_t, raise_event, void, private_vici_dispatcher_t *this, char *name, u_int id, vici_message_t *message)
METHOD (vici_dispatcher_t, destroy, void, private_vici_dispatcher_t *this)
vici_dispatcher_t * vici_dispatcher_create (char *uri)
Typedef Documentation
typedef struct private_vici_dispatcher_t private_vici_dispatcher_t
Definition at line 49 of file vici_dispatcher.c.
Function Documentation
CALLBACK (release_command , void , release_data_t * release)
Release command after execution/cancellation
Definition at line 244 of file vici_dispatcher.c.
References condvar_t::broadcast, release_data_t::cmd, private_vici_dispatcher_t::cond, vici_message_t::destroy, free(), mutex_t::lock, private_vici_dispatcher_t::mutex, release_data_t::request, release_data_t::this, mutex_t::unlock, and command_t::uses.
 {
     release->request->destroy(release->request);
     release->this->mutex->lock(release->this->mutex);
     if (--release->cmd->uses == 0)
     {
         release->this->cond->broadcast(release->this->cond);
     }
     release->this->mutex->unlock(release->this->mutex);
     free(release);
 }
CALLBACK (inbound , void , private_vici_dispatcher_t * this, u_int id, chunk_t data)
Definition at line 306 of file vici_dispatcher.c.
References bio_reader_create(), DBG1, DBG_CFG, bio_reader_t::destroy, FALSE, name, bio_reader_t::peek, process_request(), bio_reader_t::read_data8, bio_reader_t::read_uint8, register_event(), thread_cleanup_pop(), thread_cleanup_push(), type, unregister_event(), VICI_CMD_REQUEST, VICI_CMD_RESPONSE, VICI_EVENT, VICI_EVENT_CONFIRM, VICI_EVENT_REGISTER, VICI_EVENT_UNKNOWN, VICI_EVENT_UNREGISTER, and vici_stringify().
 {
     bio_reader_t *reader;
     chunk_t chunk;
     u_int8_t type;
     char name[257];
     reader = bio_reader_create(data);
     if (reader->read_uint8(reader, &type))
     {
         switch (type)
         {
             case VICI_EVENT_REGISTER:
                 if (reader->read_data8(reader, &chunk) &&
                     vici_stringify(chunk, name, sizeof(name)))
                 {
                     register_event(this, name, id);
                 }
                 else
                 {
                     DBG1(DBG_CFG, "invalid vici register message");
                 }
                 break;
             case VICI_EVENT_UNREGISTER:
                 if (reader->read_data8(reader, &chunk) &&
                     vici_stringify(chunk, name, sizeof(name)))
                 {
                     unregister_event(this, name, id);
                 }
                 else
                 {
                     DBG1(DBG_CFG, "invalid vici unregister message");
                 }
                 break;
             case VICI_CMD_REQUEST:
                 if (reader->read_data8(reader, &chunk) &&
                     vici_stringify(chunk, name, sizeof(name)))
                 {
                     thread_cleanup_push((void*)reader->destroy, reader);
                     process_request(this, name, id, reader->peek(reader));
                     thread_cleanup_pop(FALSE);
                 }
                 else
                 {
                     DBG1(DBG_CFG, "invalid vici request message");
                 }
                 break;
             case VICI_CMD_RESPONSE:
             case VICI_EVENT_CONFIRM:
             case VICI_EVENT_UNKNOWN:
             case VICI_EVENT:
             default:
                 DBG1(DBG_CFG, "unsupported vici operation: %u", type);
                 break;
         }
     }
     else
     {
         DBG1(DBG_CFG, "invalid vici message");
     }
     reader->destroy(reader);
 }
CALLBACK (connect_ , void , private_vici_dispatcher_t * this, u_int id)
Definition at line 370 of file vici_dispatcher.c.
References DBG2, and DBG_CFG.
 {
     DBG2(DBG_CFG, "vici client %u connected", id);
 }
CALLBACK (disconnect , void , private_vici_dispatcher_t * this, u_int id)
Definition at line 376 of file vici_dispatcher.c.
References array_create_enumerator(), array_remove_at(), event_t::clients, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, event, mutex_t::lock, mutex, mutex_t::unlock, and event_t::uses.
 {
     enumerator_t *events, *ids;
     event_t *event;
     u_int *current;
     /* deregister client from all events */
     this->mutex->lock(this->mutex);
     events = this->events->create_enumerator(this->events);
     while (events->enumerate(events, NULL, &event))
     {
         while (event->uses)
         {
             this->cond->wait(this->cond, this->mutex);
         }
         ids = array_create_enumerator(event->clients);
         while (ids->enumerate(ids, &current))
         {
             if (id == *current)
             {
                 array_remove_at(event->clients, ids);
             }
         }
         ids->destroy(ids);
     }
     events->destroy(events);
     this->mutex->unlock(this->mutex);
     DBG2(DBG_CFG, "vici client %u disconnected", id);
 }
METHOD (vici_dispatcher_t , manage_command , void , private_vici_dispatcher_t * this, char * name, vici_command_cb_t cb, void * user)
Definition at line 408 of file vici_dispatcher.c.
References cmd, cmds, free(), INIT, mutex_t::lock, mutex, command_t::name, strdup, mutex_t::unlock, and command_t::uses.
 {
     command_t *cmd;
     this->mutex->lock(this->mutex);
     if (cb)
     {
         INIT(cmd,
             .name = strdup(name),
             .cb = cb,
             .user = user,
         );
         cmd = this->cmds->put(this->cmds, cmd->name, cmd);
     }
     else
     {
         cmd = this->cmds->remove(this->cmds, name);
     }
     if (cmd)
     {
         while (cmd->uses)
         {
             this->cond->wait(this->cond, this->mutex);
         }
         free(cmd->name);
         free(cmd);
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (vici_dispatcher_t , manage_event , void , private_vici_dispatcher_t * this, char * name, bool reg)
Definition at line 440 of file vici_dispatcher.c.
References array_create(), array_destroy(), event_t::clients, event, free(), INIT, mutex_t::lock, mutex, event_t::name, strdup, mutex_t::unlock, and event_t::uses.
 {
     event_t *event;
     this->mutex->lock(this->mutex);
     if (reg)
     {
         INIT(event,
             .name = strdup(name),
             .clients = array_create(sizeof(u_int), 0),
         );
         event = this->events->put(this->events, event->name, event);
     }
     else
     {
         event = this->events->remove(this->events, name);
     }
     if (event)
     {
         while (event->uses)
         {
             this->cond->wait(this->cond, this->mutex);
         }
         array_destroy(event->clients);
         free(event->name);
         free(event);
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (vici_dispatcher_t , has_event_listeners , bool , private_vici_dispatcher_t * this, char * name)
Definition at line 471 of file vici_dispatcher.c.
References FALSE, mutex_t::lock, mutex, TRUE, and mutex_t::unlock.
 {
     bool retval = FALSE;
     this->mutex->lock(this->mutex);
     if (this->events->get(this->events, name))
     {
         /* the entry might be getting destroyed, but returning
          * false positive is not a problem as a later raise_event
          * will check things again. */
         retval = TRUE;
     }
     this->mutex->unlock(this->mutex);
     return retval;
 }
METHOD (vici_dispatcher_t , raise_event , void , private_vici_dispatcher_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 489 of file vici_dispatcher.c.
References array_create_enumerator(), event_t::clients, enumerator_t::destroy, vici_message_t::destroy, enumerator_t::enumerate, event, mutex_t::lock, mutex, send_op(), mutex_t::unlock, event_t::uses, and VICI_EVENT.
 {
     enumerator_t *enumerator;
     event_t *event;
     u_int *current;
     this->mutex->lock(this->mutex);
     event = this->events->get(this->events, name);
     if (event)
     {
         event->uses++;
         this->mutex->unlock(this->mutex);
         enumerator = array_create_enumerator(event->clients);
         while (enumerator->enumerate(enumerator, &current))
         {
             if (id == 0 || id == *current)
             {
                 send_op(this, *current, VICI_EVENT, name, message);
             }
         }
         enumerator->destroy(enumerator);
         this->mutex->lock(this->mutex);
         if (--event->uses == 0)
         {
             this->cond->broadcast(this->cond);
         }
     }
     this->mutex->unlock(this->mutex);
     message->destroy(message);
 }
METHOD (vici_dispatcher_t , destroy , void , private_vici_dispatcher_t * this)
Definition at line 525 of file vici_dispatcher.c.
References cmds, mutex_t::destroy, DESTROY_IF, free(), mutex, and socket.
 {
     DESTROY_IF(this->socket);
     this->mutex->destroy(this->mutex);
     this->cond->destroy(this->cond);
     this->cmds->destroy(this->cmds);
     this->events->destroy(this->events);
     free(this);
 }
void process_request (private_vici_dispatcher_t * this, char * name, u_int id, chunk_t data)
Process a request message
Definition at line 262 of file vici_dispatcher.c.
References command_t::cb, cmd, release_data_t::cmd, cmds, DBG1, DBG2, DBG_CFG, vici_message_t::destroy, FALSE, INIT, mutex_t::lock, mutex, command_t::name, release_data_t::request, response, send_op(), thread_cleanup_pop(), thread_cleanup_push(), TRUE, mutex_t::unlock, command_t::user, command_t::uses, VICI_CMD_RESPONSE, VICI_CMD_UNKNOWN, and vici_message_create_from_data().
Referenced by CALLBACK().
 {
     vici_message_t *response = NULL;
     release_data_t *release;
     command_t *cmd;
     this->mutex->lock(this->mutex);
     cmd = this->cmds->get(this->cmds, name);
     if (cmd)
     {
         cmd->uses++;
     }
     this->mutex->unlock(this->mutex);
     if (cmd)
     {
         INIT(release,
             .this = this,
             .cmd = cmd,
         );
         DBG2(DBG_CFG, "vici client %u requests: %s", id, name);
         thread_cleanup_push(release_command, release);
         release->request = vici_message_create_from_data(data, FALSE);
         response = release->cmd->cb(cmd->user, cmd->name, id, release->request);
         thread_cleanup_pop(TRUE);
         if (response)
         {
             send_op(this, id, VICI_CMD_RESPONSE, NULL, response);
             response->destroy(response);
         }
     }
     else
     {
         DBG1(DBG_CFG, "vici client %u invalid request: %s", id, name);
         send_op(this, id, VICI_CMD_UNKNOWN, NULL, NULL);
     }
 }
static void register_event (private_vici_dispatcher_t * this, char * name, u_int id) static
Register client for event
Definition at line 148 of file vici_dispatcher.c.
References array_insert(), ARRAY_TAIL, event_t::clients, DBG1, DBG2, DBG_CFG, event, mutex_t::lock, mutex, send_op(), TRUE, mutex_t::unlock, event_t::uses, VICI_EVENT_CONFIRM, and VICI_EVENT_UNKNOWN.
Referenced by CALLBACK().
 {
     event_t *event;
     this->mutex->lock(this->mutex);
     while (TRUE)
     {
         event = this->events->get(this->events, name);
         if (!event)
         {
             break;
         }
         if (!event->uses)
         {
             array_insert(event->clients, ARRAY_TAIL, &id);
             break;
         }
         this->cond->wait(this->cond, this->mutex);
     }
     this->mutex->unlock(this->mutex);
     if (event)
     {
         DBG2(DBG_CFG, "vici client %u registered for: %s", id, name);
         send_op(this, id, VICI_EVENT_CONFIRM, NULL, NULL);
     }
     else
     {
         DBG1(DBG_CFG, "vici client %u invalid registration: %s", id, name);
         send_op(this, id, VICI_EVENT_UNKNOWN, NULL, NULL);
     }
 }
static void send_op (private_vici_dispatcher_t * this, u_int id, vici_operation_t op, char * name, vici_message_t * message) static
Send a operation code, optionally with name and message
Definition at line 116 of file vici_dispatcher.c.
References bio_writer_create(), chunk_from_str, bio_writer_t::destroy, bio_writer_t::extract_buf, vici_message_t::get_encoding, chunk_t::len, len, socket, bio_writer_t::write_data, bio_writer_t::write_data8, and bio_writer_t::write_uint8.
Referenced by METHOD(), process_request(), register_event(), and unregister_event().
 {
     bio_writer_t *writer;
     u_int len;
     len = sizeof(u_int8_t);
     if (name)
     {
         len += sizeof(u_int8_t) + strlen(name);
     }
     if (message)
     {
         len += message->get_encoding(message).len;
     }
     writer = bio_writer_create(len);
     writer->write_uint8(writer, op);
     if (name)
     {
         writer->write_data8(writer, chunk_from_str(name));
     }
     if (message)
     {
         writer->write_data(writer, message->get_encoding(message));
     }
     this->socket->send(this->socket, id, writer->extract_buf(writer));
     writer->destroy(writer);
 }
static void unregister_event (private_vici_dispatcher_t * this, char * name, u_int id) static
Unregister client for event
Definition at line 185 of file vici_dispatcher.c.
References array_create_enumerator(), array_remove_at(), event_t::clients, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, event, FALSE, found, mutex_t::lock, mutex, send_op(), TRUE, mutex_t::unlock, event_t::uses, VICI_EVENT_CONFIRM, and VICI_EVENT_UNKNOWN.
Referenced by CALLBACK().
 {
     enumerator_t *enumerator;
     event_t *event;
     u_int *current;
     bool found = FALSE;
     this->mutex->lock(this->mutex);
     while (TRUE)
     {
         event = this->events->get(this->events, name);
         if (!event)
         {
             break;
         }
         if (!event->uses)
         {
             enumerator = array_create_enumerator(event->clients);
             while (enumerator->enumerate(enumerator, &current))
             {
                 if (*current == id)
                 {
                     array_remove_at(event->clients, enumerator);
                     found = TRUE;
                     break;
                 }
             }
             enumerator->destroy(enumerator);
             break;
         }
         this->cond->wait(this->cond, this->mutex);
     }
     this->mutex->unlock(this->mutex);
     DBG2(DBG_CFG, "vici client %u unregistered for: %s", id, name);
     if (found)
     {
         send_op(this, id, VICI_EVENT_CONFIRM, NULL, NULL);
     }
     else
     {
         send_op(this, id, VICI_EVENT_UNKNOWN, NULL, NULL);
     }
 }