strongSwan: vici_message_t Struct Reference
vici_message_t Struct Reference
vici_message
#include "vici_message.h"
Public Attributes
enumerator_t *(* create_enumerator)(vici_message_t *this)
char *(* get_str)(vici_message_t *this, char *def, char *fmt,...)
char *(* vget_str)(vici_message_t *this, char *def, char *fmt, va_list args)
int(* get_int)(vici_message_t *this, int def, char *fmt,...)
int(* vget_int)(vici_message_t *this, int def, char *fmt, va_list args)
bool(* get_bool)(vici_message_t *this, bool def, char *fmt,...)
bool(* vget_bool)(vici_message_t *this, bool def, char *fmt, va_list args)
chunk_t(* get_value)(vici_message_t *this, chunk_t def, char *fmt,...)
chunk_t(* vget_value)(vici_message_t *this, chunk_t def, char *fmt, va_list args)
chunk_t(* get_encoding)(vici_message_t *this)
bool(* parse)(vici_message_t *this, vici_parse_context_t *ctx, vici_section_cb_t section, vici_value_cb_t kv, vici_value_cb_t li, void *user)
bool(* dump)(vici_message_t *this, char *label, bool pretty, FILE *out)
void(* destroy)(vici_message_t *this)
Detailed Description
Vici message representation, encoding/decoding routines.
Definition at line 89 of file vici_message.h.
Member Data Documentation
enumerator_t*(* vici_message_t::create_enumerator)(vici_message_t *this)
Create an enumerator over message contents.
The enumerator takes a fixed list of arguments, but depending on the type may set not all of them. It returns VICI_END as last argument to indicate the message end, and returns FALSE if parsing the message failed.
Returns
enumerator over (vici_type_t, char*, chunk_t)
Definition at line 101 of file vici_message.h.
Referenced by echo_cb(), handle_event(), START_TEST(), and vici_submit().
void(* vici_message_t::destroy)(vici_message_t *this)
Destroy a vici_message_t.
Definition at line 223 of file vici_message.h.
Referenced by CALLBACK(), handle_event(), METHOD(), process_request(), START_TEST(), vici_free_res(), and vici_submit().
bool(* vici_message_t::dump)(vici_message_t *this, char *label, bool pretty, FILE *out)
Dump a message text representation to a FILE stream.
Parameters
label label to print for message
pretty use pretty print with indentation
out FILE stream to dump to
Returns
TRUE if message valid
Definition at line 218 of file vici_message.h.
Referenced by vici_dump().
bool(* vici_message_t::get_bool)(vici_message_t *this, bool def, char *fmt,...)
Get the value of a key/value pair as boolean.
Parameters
def default value if not found
fmt printf style format string for key, with sections
... arguments to fmt string
Returns
value
Definition at line 151 of file vici_message.h.
Referenced by CALLBACK(), and START_TEST().
chunk_t(* vici_message_t::get_encoding)(vici_message_t *this)
Get encoded message.
Returns
message data, points to internal data
Definition at line 189 of file vici_message.h.
Referenced by send_op(), START_TEST(), and vici_submit().
int(* vici_message_t::get_int)(vici_message_t *this, int def, char *fmt,...)
Get the value of a key/value pair as integer.
Parameters
def default value if not found
fmt printf style format string for key, with sections
... arguments to fmt string
Returns
value
Definition at line 131 of file vici_message.h.
Referenced by CALLBACK(), and START_TEST().
char*(* vici_message_t::get_str)(vici_message_t *this, char *def, char *fmt,...)
Get the value of a key/value pair as a string.
Parameters
def default value if not found
fmt printf style format string for key, with sections
... arguments to fmt string
Returns
string
Definition at line 111 of file vici_message.h.
Referenced by CALLBACK(), and START_TEST().
chunk_t(* vici_message_t::get_value)(vici_message_t *this, chunk_t def, char *fmt,...)
Get the raw value of a key/value pair.
Parameters
def default value if not found
fmt printf style format string for key, with sections
... arguments to fmt string
Returns
value
Definition at line 171 of file vici_message.h.
Referenced by CALLBACK(), and START_TEST().
bool(* vici_message_t::parse)(vici_message_t *this, vici_parse_context_t *ctx, vici_section_cb_t section, vici_value_cb_t kv, vici_value_cb_t li, void *user)
Parse a message using callback functions.
Any of the callbacks may be NULL to skip this kind of item. Callbacks are invoked for the current section level only. To descent into sections, call parse() from within a section callback using the provided parse context.
Parameters
ctx parse context, NULL for root level
section callback invoked for each section
kv callback invoked for key/value pairs
li callback invoked for list items
user user data to pass to callbacks
Returns
TRUE if parsed successfully
Definition at line 206 of file vici_message.h.
Referenced by CALLBACK().
bool(* vici_message_t::vget_bool)(vici_message_t *this, bool def, char *fmt, va_list args)
Get the value of a key/value pair as boolean, va_list variant
Parameters
def default value if not found
fmt printf style format string for key, with sections
args arguments to fmt string
Returns
value
Definition at line 161 of file vici_message.h.
int(* vici_message_t::vget_int)(vici_message_t *this, int def, char *fmt, va_list args)
Get the value of a key/value pair as integer, va_list variant
Parameters
def default value if not found
fmt printf style format string for key, with sections
args arguments to fmt string
Returns
value
Definition at line 141 of file vici_message.h.
Referenced by vici_find_int().
char*(* vici_message_t::vget_str)(vici_message_t *this, char *def, char *fmt, va_list args)
Get the value of a key/value pair as a string, va_list variant.
Parameters
def default value if not found
fmt printf style format string for key, with sections
args arguments to fmt string
Returns
string
Definition at line 121 of file vici_message.h.
Referenced by vici_find_str().
chunk_t(* vici_message_t::vget_value)(vici_message_t *this, chunk_t def, char *fmt, va_list args)
Get the raw value of a key/value pair, va_list variant.
Parameters
def default value if not found
fmt printf style format string for key, with sections
args arguments to fmt string
Returns
value
Definition at line 181 of file vici_message.h.
Referenced by vici_find().
The documentation for this struct was generated from the following file:
vici_message.h