strongSwan: pts_meas_algo
pts_meas_algo
pts
Typedefs
typedef enum pts_meas_algorithms_t pts_meas_algorithms_t
Enumerations
enum pts_meas_algorithms_t { PTS_MEAS_ALGO_NONE = 0, PTS_MEAS_ALGO_SHA384 = (1<<13), PTS_MEAS_ALGO_SHA256 = (1<<14), PTS_MEAS_ALGO_SHA1 = (1<<15) }
Functions
bool pts_meas_algo_probe (pts_meas_algorithms_t *algorithms)
bool pts_meas_algo_update (char *hash_alg, pts_meas_algorithms_t *algorithms)
pts_meas_algorithms_t pts_meas_algo_select (pts_meas_algorithms_t supported_algos, pts_meas_algorithms_t offered_algos)
hash_algorithm_t pts_meas_algo_to_hash (pts_meas_algorithms_t algorithm)
size_t pts_meas_algo_hash_size (pts_meas_algorithms_t algorithm)
Variables
enum_name_t * pts_meas_algorithm_names
Detailed Description
Typedef Documentation
typedef enum pts_meas_algorithms_t pts_meas_algorithms_t
Definition at line 28 of file pts_meas_algo.h.
Enumeration Type Documentation
enum pts_meas_algorithms_t
PTS Measurement Algorithms
Enumerator
PTS_MEAS_ALGO_NONE
PTS_MEAS_ALGO_SHA384
PTS_MEAS_ALGO_SHA256
PTS_MEAS_ALGO_SHA1
Definition at line 33 of file pts_meas_algo.h.
{
     PTS_MEAS_ALGO_NONE     =      0,
     PTS_MEAS_ALGO_SHA384   = (1<<13),
     PTS_MEAS_ALGO_SHA256   = (1<<14),
     PTS_MEAS_ALGO_SHA1     = (1<<15)
 };
Function Documentation
size_t pts_meas_algo_hash_size (pts_meas_algorithms_t algorithm)
Return the hash size of a pts_meas_algorithm
Parameters
algorithm PTS measurement algorithm type
Returns
hash size in bytes
Described in header.
Definition at line 161 of file pts_meas_algo.c.
References HASH_SIZE_SHA1, HASH_SIZE_SHA256, HASH_SIZE_SHA384, PTS_MEAS_ALGO_NONE, PTS_MEAS_ALGO_SHA1, PTS_MEAS_ALGO_SHA256, and PTS_MEAS_ALGO_SHA384.
Referenced by METHOD(), and pts_meas_algo_to_pcr_transform().
 {
     switch (algorithm)
     {
         case PTS_MEAS_ALGO_SHA1:
             return HASH_SIZE_SHA1;
         case PTS_MEAS_ALGO_SHA256:
             return HASH_SIZE_SHA256;
         case PTS_MEAS_ALGO_SHA384:
             return HASH_SIZE_SHA384;
         case PTS_MEAS_ALGO_NONE:
         default:
             return 0;
     }
 }
bool pts_meas_algo_probe (pts_meas_algorithms_t * algorithms)
Diffie-Hellman Hash Algorithm Values see section 3.8.5 of PTS Protocol: Binding to TNC IF-M Specification
               1
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ |1|2|3|R|R|R|R|R|R|R|R|R|R|R|R|R| +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ Probe available PTS measurement algorithms
Parameters
algorithms set of available algorithms
Returns
TRUE if mandatory algorithms are available
Described in header.
Definition at line 36 of file pts_meas_algo.c.
References crypto_factory_t::create_hasher_enumerator, library_t::crypto, DBG1, DBG2, DBG_PTS, enumerator_t::destroy, enumerator_t::enumerate, FALSE, hash_algorithm_names, HASH_SHA1, HASH_SHA256, HASH_SHA384, lib, PTS_MEAS_ALGO_SHA1, PTS_MEAS_ALGO_SHA256, PTS_MEAS_ALGO_SHA384, and TRUE.
Referenced by imv_attestation_agent_create(), and TNC_IMC_Initialize().
 {
     enumerator_t *enumerator;
     hash_algorithm_t hash_alg;
     const char *plugin_name;
     char format1[] = "  %s PTS measurement algorithm %N[%s] available";
     char format2[] = "  %s PTS measurement algorithm %N not available";
     *algorithms = 0;
     enumerator = lib->crypto->create_hasher_enumerator(lib->crypto);
     while (enumerator->enumerate(enumerator, &hash_alg, &plugin_name))
     {
         if (hash_alg == HASH_SHA1)
         {
             *algorithms |= PTS_MEAS_ALGO_SHA1;
             DBG2(DBG_PTS, format1, "mandatory", hash_algorithm_names, hash_alg,
                                   plugin_name);
         }
         else if (hash_alg == HASH_SHA256)
         {
             *algorithms |= PTS_MEAS_ALGO_SHA256;
             DBG2(DBG_PTS, format1, "mandatory", hash_algorithm_names, hash_alg,
                                   plugin_name);
         }
         else if (hash_alg == HASH_SHA384)
         {
             *algorithms |= PTS_MEAS_ALGO_SHA384;
             DBG2(DBG_PTS, format1, "optional ", hash_algorithm_names, hash_alg,
                                   plugin_name);
         }
     }
     enumerator->destroy(enumerator);
     if (!(*algorithms & PTS_MEAS_ALGO_SHA384))
     {
         DBG1(DBG_PTS, format2, "optional ", hash_algorithm_names, HASH_SHA384);
     }
     if ((*algorithms & PTS_MEAS_ALGO_SHA1) &&
         (*algorithms & PTS_MEAS_ALGO_SHA256))
     {
         return TRUE;
     }
     if (!(*algorithms & PTS_MEAS_ALGO_SHA1))
     {
         DBG1(DBG_PTS, format2, "mandatory", hash_algorithm_names, HASH_SHA1);
     }
     if (!(*algorithms & PTS_MEAS_ALGO_SHA256))
     {
         DBG1(DBG_PTS, format2, "mandatory", hash_algorithm_names, HASH_SHA256);
     }
     return FALSE;
 }
pts_meas_algorithms_t pts_meas_algo_select (pts_meas_algorithms_t supported_algos, pts_meas_algorithms_t offered_algos)
Select the strongest PTS measurement algorithm among a set of offered PTS measurement algorithms
Parameters
supported_algos set of supported PTS measurement algorithms
offered_algos set of offered PTS measurements algorithms
Returns
selected algorithm
Described in header.
Definition at line 119 of file pts_meas_algo.c.
References PTS_MEAS_ALGO_NONE, PTS_MEAS_ALGO_SHA1, PTS_MEAS_ALGO_SHA256, and PTS_MEAS_ALGO_SHA384.
Referenced by imc_attestation_process(), and imv_attestation_process().
 {
     if ((supported_algos & PTS_MEAS_ALGO_SHA384) &&
         (offered_algos   & PTS_MEAS_ALGO_SHA384))
     {
         return PTS_MEAS_ALGO_SHA384;
     }
     if ((supported_algos & PTS_MEAS_ALGO_SHA256) &&
         (offered_algos   & PTS_MEAS_ALGO_SHA256))
     {
         return PTS_MEAS_ALGO_SHA256;
     }
     if ((supported_algos & PTS_MEAS_ALGO_SHA1) &&
         (offered_algos   & PTS_MEAS_ALGO_SHA1))
     {
         return PTS_MEAS_ALGO_SHA1;
     }
     return PTS_MEAS_ALGO_NONE;
 }
hash_algorithm_t pts_meas_algo_to_hash (pts_meas_algorithms_t algorithm)
Convert pts_meas_algorithms_t to hash_algorithm_t
Parameters
algorithm PTS measurement algorithm type
Returns
libstrongswan hash algorithm type
Described in header.
Definition at line 143 of file pts_meas_algo.c.
References HASH_SHA1, HASH_SHA256, HASH_SHA384, HASH_UNKNOWN, PTS_MEAS_ALGO_SHA1, PTS_MEAS_ALGO_SHA256, and PTS_MEAS_ALGO_SHA384.
Referenced by ima_hash(), METHOD(), and pts_file_meas_create_from_path().
 {
     switch (algorithm)
     {
         case PTS_MEAS_ALGO_SHA1:
             return HASH_SHA1;
         case PTS_MEAS_ALGO_SHA256:
             return HASH_SHA256;
         case PTS_MEAS_ALGO_SHA384:
             return HASH_SHA384;
         default:
             return HASH_UNKNOWN;
     }
 }
bool pts_meas_algo_update (char * hash_alg, pts_meas_algorithms_t * algorithms)
Update supported PTS measurement algorithms according to configuration
sha1 : PTS_MEAS_ALGO_SHA1 sha256: PTS_MEAS_ALGO_SHA1 | PTS_MEAS_ALGO_SHA256 sha384: PTS_MEAS_ALGO_SHA1 | PTS_MEAS_ALGO_SHA256 | PTS_MEAS_ALGO_SHA384
The PTS-IMC is expected to select the strongest supported algorithm
Parameters
hash_alg configured hash algorithm
algorithms returns set of available PTS measurement algorithms
Described in header.
Definition at line 93 of file pts_meas_algo.c.
References DBG1, DBG_PTS, FALSE, PTS_MEAS_ALGO_SHA256, PTS_MEAS_ALGO_SHA384, strcaseeq(), and TRUE.
Referenced by imv_attestation_agent_create().
 {
     if (strcaseeq(hash_alg, "sha384") || strcaseeq(hash_alg, "sha2_384"))
     {
         /* nothing to update, all algorithms are supported */
         return TRUE;
     }
     if (strcaseeq(hash_alg, "sha256") || strcaseeq(hash_alg, "sha2_256"))
     {
         /* remove SHA384algorithm */
         *algorithms &= ~PTS_MEAS_ALGO_SHA384;
         return TRUE;
     }
     if (strcaseeq(hash_alg, "sha1"))
     {
         /* remove SHA384 and SHA256 algorithms */
         *algorithms &= ~(PTS_MEAS_ALGO_SHA384 | PTS_MEAS_ALGO_SHA256);
         return TRUE;
     }
     DBG1(DBG_PTS, "unknown hash algorithm '%s' configured", hash_alg);
     return FALSE;
 }
Variable Documentation
enum_name_t* pts_meas_algorithm_names
enum name for pts_meas_algorithms_t.
Referenced by METHOD().