strongSwan: ha_message_t Struct Reference
ha_message_t Struct Reference
ha_message
#include "ha_message.h"
Public Attributes
ha_message_type_t(* get_type)(ha_message_t *this)
void(* add_attribute)(ha_message_t *this, ha_message_attribute_t attribute,...)
enumerator_t *(* create_attribute_enumerator)(ha_message_t *this)
chunk_t(* get_encoding)(ha_message_t *this)
void(* destroy)(ha_message_t *this)
Detailed Description
Abstracted message passed between nodes in a HA cluster.
Definition at line 177 of file ha_message.h.
Member Data Documentation
void(* ha_message_t::add_attribute)(ha_message_t *this, ha_message_attribute_t attribute,...)
Add an attribute to a message.
Parameters
attribute attribute type to add
... attribute specific data
Definition at line 192 of file ha_message.h.
Referenced by enable_disable(), METHOD(), request_resync(), send_status(), and sync_vips().
enumerator_t*(* ha_message_t::create_attribute_enumerator)(ha_message_t *this)
Create an enumerator over all attributes in a message.
Returns
enumerator over attribute, ha_message_value_t
Definition at line 200 of file ha_message.h.
Referenced by process_child_add(), process_child_delete(), process_ike_add(), process_ike_delete(), process_ike_iv(), process_ike_mid(), process_ike_update(), process_resync(), process_segment(), and process_status().
void(* ha_message_t::destroy)(ha_message_t *this)
Destroy a ha_message_t.
Definition at line 212 of file ha_message.h.
Referenced by dispatch(), enable_disable(), entry_destroy(), METHOD(), process_child_add(), process_child_delete(), process_ike_delete(), process_ike_iv(), process_ike_mid(), process_ike_update(), process_resync(), process_segment(), process_status(), request_resync(), and send_status().
chunk_t(* ha_message_t::get_encoding)(ha_message_t *this)
Get the message in a encoded form.
Returns
chunk pointing to internal data
Definition at line 207 of file ha_message.h.
Referenced by METHOD().
ha_message_type_t(* ha_message_t::get_type)(ha_message_t *this)
Get the type of the message.
Returns
message type
Definition at line 184 of file ha_message.h.
Referenced by dispatch(), and METHOD().
The documentation for this struct was generated from the following file:
ha_message.h