strongSwan: eap_radius
eap_radius
eap_radius
Classes
struct eap_radius_t
Typedefs
typedef struct eap_radius_t eap_radius_t
Functions
eap_radius_t * eap_radius_create (identification_t *server, identification_t *peer)
void eap_radius_process_attributes (radius_message_t *message)
void eap_radius_build_attributes (radius_message_t *message)
Detailed Description
Typedef Documentation
typedef struct eap_radius_t eap_radius_t
Definition at line 24 of file eap_radius.h.
Function Documentation
void eap_radius_build_attributes (radius_message_t * request)
Build additional attributes for an Access-Request.
Adds additional RADIUS attributes to use with Access-Request, such as different NAS specific attributes.
Parameters
message Access-Request message to add attributes to
See header.
Definition at line 154 of file eap_radius.c.
References radius_message_t::add, daemon_t::bus, charon, chunk_from_str, chunk_from_thing, host_t::get_address, settings_t::get_bool, host_t::get_family, ike_sa_t::get_my_host, ike_sa_t::get_name, ike_sa_t::get_other_host, bus_t::get_sa, ike_sa_t::get_unique_id, host, lib, library_t::ns, RAT_CALLED_STATION_ID, RAT_CALLING_STATION_ID, RAT_NAS_IP_ADDRESS, RAT_NAS_IPV6_ADDRESS, RAT_NAS_PORT, RAT_NAS_PORT_ID, RAT_NAS_PORT_TYPE, RAT_SERVICE_TYPE, library_t::settings, snprintf, TRUE, and value.
Referenced by add_radius_request_attrs(), and verify_radius().
 {
     ike_sa_t *ike_sa;
     host_t *host;
     char buf[40], *station_id_fmt;;
     u_int32_t value;
     chunk_t chunk;
     /* virtual NAS-Port-Type */
     value = htonl(5);
     request->add(request, RAT_NAS_PORT_TYPE, chunk_from_thing(value));
     /* framed ServiceType */
     value = htonl(2);
     request->add(request, RAT_SERVICE_TYPE, chunk_from_thing(value));
     ike_sa = charon->bus->get_sa(charon->bus);
     if (ike_sa)
     {
         value = htonl(ike_sa->get_unique_id(ike_sa));
         request->add(request, RAT_NAS_PORT, chunk_from_thing(value));
         request->add(request, RAT_NAS_PORT_ID,
                      chunk_from_str(ike_sa->get_name(ike_sa)));
         host = ike_sa->get_my_host(ike_sa);
         chunk = host->get_address(host);
         switch (host->get_family(host))
         {
             case AF_INET:
                 request->add(request, RAT_NAS_IP_ADDRESS, chunk);
                 break;
             case AF_INET6:
                 request->add(request, RAT_NAS_IPV6_ADDRESS, chunk);
             default:
                 break;
         }
         if (lib->settings->get_bool(lib->settings,
                                     "%s.plugins.eap-radius.station_id_with_port",
                                     TRUE, lib->ns))
         {
             station_id_fmt = "%#H";
         }
         else
         {
             station_id_fmt = "%H";
         }
         snprintf(buf, sizeof(buf), station_id_fmt, host);
         request->add(request, RAT_CALLED_STATION_ID, chunk_from_str(buf));
         host = ike_sa->get_other_host(ike_sa);
         snprintf(buf, sizeof(buf), station_id_fmt, host);
         request->add(request, RAT_CALLING_STATION_ID, chunk_from_str(buf));
     }
 }
eap_radius_t* eap_radius_create (identification_t * server, identification_t * peer)
Create a EAP RADIUS proxy.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_radius_t object
Generic constructor
Definition at line 761 of file eap_radius.c.
References client(), identification_t::clone, EAP_RADIUS, eap_radius_create_client(), FALSE, free(), settings_t::get_bool, settings_t::get_str, INIT, lib, library_t::ns, and library_t::settings.
Referenced by METHOD().
 {
     private_eap_radius_t *this;
     INIT(this,
         .public = {
             .eap_method = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .destroy = _destroy,
             },
         },
         /* initially EAP_RADIUS, but is set to the method selected by RADIUS */
         .type = EAP_RADIUS,
         .eap_start = lib->settings->get_bool(lib->settings,
                                     "%s.plugins.eap-radius.eap_start", FALSE,
                                     lib->ns),
         .id_prefix = lib->settings->get_str(lib->settings,
                                     "%s.plugins.eap-radius.id_prefix", "",
                                     lib->ns),
     );
     this->client = eap_radius_create_client();
     if (!this->client)
     {
         free(this);
         return NULL;
     }
     this->peer = peer->clone(peer);
     this->server = server->clone(server);
     return &this->public;
 }
void eap_radius_process_attributes (radius_message_t * message)
Process additional attributes from an Access-Accept.
Parses and applies additional authorization attributes from an Accept message, such as group membership information or IKE configuration attributes.
Parameters
message Access-Accept message to process
See header.
Definition at line 632 of file eap_radius.c.
References FALSE, settings_t::get_bool, lib, library_t::ns, process_cfg_attributes(), process_class(), process_filter_id(), process_timeout(), and library_t::settings.
Referenced by METHOD(), and verify_radius().
 {
     if (lib->settings->get_bool(lib->settings,
                         "%s.plugins.eap-radius.class_group", FALSE, lib->ns))
     {
         process_class(message);
     }
     if (lib->settings->get_bool(lib->settings,
                         "%s.plugins.eap-radius.filter_id", FALSE, lib->ns))
     {
         process_filter_id(message);
     }
     process_timeout(message);
     process_cfg_attributes(message);
 }