strongSwan: test_bliss_huffman.c File Reference
test_bliss_huffman.c File Reference
#include "test_suite.h"
#include <bliss_huffman_coder.h>
Functions
START_TEST (test_bliss_huffman_encode)
END_TEST START_TEST (test_bliss_huffman_decode)
END_TEST Suite * bliss_huffman_suite_create ()
Variables
static chunk_t data = chunk_from_chars(0x5f, 0x71, 0x9e, 0x4c)
Function Documentation
END_TEST Suite* bliss_huffman_suite_create ()
Definition at line 106 of file test_bliss_huffman.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("bliss_huffman");
     tc = tcase_create("huffman_encode");
     tcase_add_test(tc, test_bliss_huffman_encode);
     suite_add_tcase(s, tc);
     tc = tcase_create("huffman_decode");
     tcase_add_test(tc, test_bliss_huffman_decode);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_bliss_huffman_encode)
Definition at line 22 of file test_bliss_huffman.c.
References BLISS_B_I, bliss_bitpacker_create(), bliss_huffman_code_get_by_id(), bliss_huffman_coder_create(), chunk_equals(), chunk_free(), ck_assert, code, bliss_huffman_coder_t::destroy, bliss_bitpacker_t::destroy, bliss_huffman_coder_t::encode, encoding, and bliss_bitpacker_t::extract_buf.
 {
     bliss_bitpacker_t *packer;
     bliss_huffman_code_t *code;
     bliss_huffman_coder_t *coder;
     chunk_t encoding;
     packer = bliss_bitpacker_create(32);
     ck_assert(packer);
     code = bliss_huffman_code_get_by_id(BLISS_B_I);
     ck_assert(code);
     coder = bliss_huffman_coder_create(code, packer);
     ck_assert(coder);
     ck_assert( coder->encode(coder, 0,  0));    /* 0 */
     ck_assert( coder->encode(coder, 1,  0));    /* 10 */
     ck_assert( coder->encode(coder, 2,  0));    /* 111 */
     ck_assert( coder->encode(coder, 0,  1));    /* 1101 */
     ck_assert( coder->encode(coder, 0, -1));    /* 11000 */
     ck_assert( coder->encode(coder, 1,  1));    /* 110011 */
     ck_assert( coder->encode(coder, 1, -1));    /* 1100100 */
     ck_assert(!coder->encode(coder, 3,  0));    /* 11001010 */
     ck_assert(!coder->encode(coder, 8,  0));    /* - */
     encoding = packer->extract_buf(packer);
     ck_assert(chunk_equals(encoding, data));
     chunk_free(&encoding);
     coder->destroy(coder);
     packer->destroy(packer);
 }
END_TEST START_TEST (test_bliss_huffman_decode)
Definition at line 57 of file test_bliss_huffman.c.
References BLISS_B_I, BLISS_B_II, bliss_bitpacker_create_from_data(), bliss_huffman_code_get_by_id(), bliss_huffman_coder_create(), BLISS_II, ck_assert, code, bliss_huffman_coder_t::decode, bliss_huffman_coder_t::destroy, and bliss_bitpacker_t::destroy.
 {
     bliss_bitpacker_t *packer;
     bliss_huffman_code_t *code;
     bliss_huffman_coder_t *coder;
     int32_t z1;
     int16_t z2;
     packer = bliss_bitpacker_create_from_data(data);
     ck_assert(packer);
     code = bliss_huffman_code_get_by_id(BLISS_II);
     ck_assert(!code);
     code = bliss_huffman_code_get_by_id(BLISS_B_II);
     ck_assert(!code);
     code = bliss_huffman_code_get_by_id(BLISS_B_I);
     ck_assert(code);
     coder = bliss_huffman_coder_create(code, packer);
     ck_assert(coder);
     ck_assert(coder->decode(coder, &z1, &z2));  /* 0 */
     ck_assert(z1 == 0 && z2 == 0);
     ck_assert(coder->decode(coder, &z1, &z2));  /* 10 */
     ck_assert(z1 == 1 && z2 == 0);
     ck_assert(coder->decode(coder, &z1, &z2));  /* 111 */
     ck_assert(z1 == 2 && z2 == 0);
     ck_assert(coder->decode(coder, &z1, &z2));  /* 1101 */
     ck_assert(z1 == 0 && z2 == 1);
     ck_assert(coder->decode(coder, &z1, &z2));  /* 11000 */
     ck_assert(z1 == 0 && z2 == -1);
     ck_assert(coder->decode(coder, &z1, &z2));  /* 110011 */
     ck_assert(z1 == 1 && z2 == 1);
     ck_assert(coder->decode(coder, &z1, &z2));  /* 1100100 */
     ck_assert(z1 == 1 && z2 == -1);
     ck_assert(!coder->decode(coder, &z1, &z2)); /* 11001010 */
     coder->destroy(coder);
     packer->destroy(packer);
 }
Variable Documentation
chunk_t data = chunk_from_chars(0x5f, 0x71, 0x9e, 0x4c) static
Definition at line 20 of file test_bliss_huffman.c.