strongSwan: openssl_rsa_private_key.c File Reference
openssl_rsa_private_key.c File Reference
#include <openssl/opensslconf.h>
#include "openssl_rsa_private_key.h"
#include "openssl_rsa_public_key.h"
#include <utils/debug.h>
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/rsa.h>
#include <openssl/engine.h>
Classes
struct private_openssl_rsa_private_key_t
Macros
#define PUBLIC_EXPONENT 0x10001
Typedefs
typedef struct
private_openssl_rsa_private_key_t private_openssl_rsa_private_key_t
Functions
bool openssl_rsa_fingerprint (RSA *rsa, cred_encoding_type_t type, chunk_t *fp)
static bool build_emsa_pkcs1_signature (private_openssl_rsa_private_key_t *this, int type, chunk_t data, chunk_t *sig)
METHOD (private_key_t, get_type, key_type_t, private_openssl_rsa_private_key_t *this)
METHOD (private_key_t, sign, bool, private_openssl_rsa_private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
METHOD (private_key_t, decrypt, bool, private_openssl_rsa_private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
METHOD (private_key_t, get_keysize, int, private_openssl_rsa_private_key_t *this)
METHOD (private_key_t, get_public_key, public_key_t *, private_openssl_rsa_private_key_t *this)
METHOD (private_key_t, get_fingerprint, bool, private_openssl_rsa_private_key_t *this, cred_encoding_type_t type, chunk_t *fingerprint)
METHOD (private_key_t, get_encoding, bool, private_openssl_rsa_private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (private_key_t, get_ref, private_key_t *, private_openssl_rsa_private_key_t *this)
METHOD (private_key_t, destroy, void, private_openssl_rsa_private_key_t *this)
static
private_openssl_rsa_private_key_t * create_empty ()
openssl_rsa_private_key_t * openssl_rsa_private_key_gen (key_type_t type, va_list args)
openssl_rsa_private_key_t * openssl_rsa_private_key_load (key_type_t type, va_list args)
static bool login (ENGINE *engine, chunk_t keyid)
openssl_rsa_private_key_t * openssl_rsa_private_key_connect (key_type_t type, va_list args)
Macro Definition Documentation
#define PUBLIC_EXPONENT 0x10001
Public exponent to use for key generation.
Definition at line 36 of file openssl_rsa_private_key.c.
Referenced by openssl_rsa_private_key_gen().
Typedef Documentation
typedef struct private_openssl_rsa_private_key_t private_openssl_rsa_private_key_t
Definition at line 38 of file openssl_rsa_private_key.c.
Function Documentation
static bool build_emsa_pkcs1_signature (private_openssl_rsa_private_key_t * this, int type, chunk_t data, chunk_t * sig) static
Build an EMPSA PKCS1 signature described in PKCS#1
Definition at line 71 of file openssl_rsa_private_key.c.
References chunk_alloc, ctx, FALSE, free(), hasher, key, chunk_t::len, len, chunk_t::ptr, rsa, and TRUE.
Referenced by METHOD().
 {
     bool success = FALSE;
     *sig = chunk_alloc(RSA_size(this->rsa));
     if (type == NID_undef)
     {
         if (RSA_private_encrypt(data.len, data.ptr, sig->ptr, this->rsa,
                                 RSA_PKCS1_PADDING) == sig->len)
         {
             success = TRUE;
         }
     }
     else
     {
         EVP_MD_CTX *ctx;
         EVP_PKEY *key;
         const EVP_MD *hasher;
         u_int len;
         hasher = EVP_get_digestbynid(type);
         if (!hasher)
         {
             return FALSE;
         }
         ctx = EVP_MD_CTX_create();
         key = EVP_PKEY_new();
         if (!ctx || !key)
         {
             goto error;
         }
         if (!EVP_PKEY_set1_RSA(key, this->rsa))
         {
             goto error;
         }
         if (!EVP_SignInit_ex(ctx, hasher, NULL))
         {
             goto error;
         }
         if (!EVP_SignUpdate(ctx, data.ptr, data.len))
         {
             goto error;
         }
         if (EVP_SignFinal(ctx, sig->ptr, &len, key))
         {
             success = TRUE;
         }
 error:
         if (key)
         {
             EVP_PKEY_free(key);
         }
         if (ctx)
         {
             EVP_MD_CTX_destroy(ctx);
         }
     }
     if (!success)
     {
         free(sig->ptr);
     }
     return success;
 }
static private_openssl_rsa_private_key_t* create_empty (void) static
Internal generic constructor
Definition at line 296 of file openssl_rsa_private_key.c.
References INIT, private_key_belongs_to(), private_key_equals(), and private_key_has_fingerprint().
Referenced by openssl_rsa_private_key_connect(), openssl_rsa_private_key_gen(), and openssl_rsa_private_key_load().
 {
     private_openssl_rsa_private_key_t *this;
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .sign = _sign,
                 .decrypt = _decrypt,
                 .get_keysize = _get_keysize,
                 .get_public_key = _get_public_key,
                 .equals = private_key_equals,
                 .belongs_to = private_key_belongs_to,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = private_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     return this;
 }
static bool login (ENGINE * engine, chunk_t keyid) static
Login to engine with a PIN specified for a keyid
Definition at line 467 of file openssl_rsa_private_key.c.
References credential_manager_t::create_shared_enumerator, library_t::credmgr, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, shared_key_t::get_key, id, ID_KEY_ID, identification_create_from_encoding(), key, chunk_t::len, lib, chunk_t::ptr, SHARED_PIN, snprintf, and TRUE.
Referenced by METHOD(), and openssl_rsa_private_key_connect().
 {
     enumerator_t *enumerator;
     shared_key_t *shared;
     identification_t *id;
     chunk_t key;
     char pin[64];
     bool found = FALSE, success = FALSE;
     id = identification_create_from_encoding(ID_KEY_ID, keyid);
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                                         SHARED_PIN, id, NULL);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         found = TRUE;
         key = shared->get_key(shared);
         if (snprintf(pin, sizeof(pin),
                      "%.*s", (int)key.len, key.ptr) >= sizeof(pin))
         {
             continue;
         }
         if (ENGINE_ctrl_cmd_string(engine, "PIN", pin, 0))
         {
             success = TRUE;
             break;
         }
         else
         {
             DBG1(DBG_CFG, "setting PIN on engine failed");
         }
     }
     enumerator->destroy(enumerator);
     id->destroy(id);
     if (!found)
     {
         DBG1(DBG_CFG, "no PIN found for %#B", &keyid);
     }
     return success;
 }
METHOD (private_key_t , get_type , key_type_t , private_openssl_rsa_private_key_t * this)
Definition at line 140 of file openssl_rsa_private_key.c.
References KEY_RSA.
 {
     return KEY_RSA;
 }
METHOD (private_key_t , sign , bool , private_openssl_rsa_private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * signature)
Definition at line 146 of file openssl_rsa_private_key.c.
References build_emsa_pkcs1_signature(), DBG1, DBG_LIB, FALSE, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, and signature_scheme_names.
 {
     switch (scheme)
     {
         case SIGN_RSA_EMSA_PKCS1_NULL:
             return build_emsa_pkcs1_signature(this, NID_undef, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA1:
             return build_emsa_pkcs1_signature(this, NID_sha1, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA224:
             return build_emsa_pkcs1_signature(this, NID_sha224, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA256:
             return build_emsa_pkcs1_signature(this, NID_sha256, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA384:
             return build_emsa_pkcs1_signature(this, NID_sha384, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA512:
             return build_emsa_pkcs1_signature(this, NID_sha512, data, signature);
         case SIGN_RSA_EMSA_PKCS1_MD5:
             return build_emsa_pkcs1_signature(this, NID_md5, data, signature);
         default:
             DBG1(DBG_LIB, "signature scheme %N not supported in RSA",
                  signature_scheme_names, scheme);
             return FALSE;
     }
 }
METHOD (private_key_t , decrypt , bool , private_openssl_rsa_private_key_t * this, encryption_scheme_t scheme, chunk_t crypto, chunk_t * plain)
Definition at line 173 of file openssl_rsa_private_key.c.
References chunk_create(), DBG1, DBG_LIB, ENCRYPT_RSA_OAEP_SHA1, ENCRYPT_RSA_PKCS1, encryption_scheme_names, FALSE, free(), chunk_t::len, len, malloc(), padding, chunk_t::ptr, rsa, and TRUE.
 {
     int padding, len;
     char *decrypted;
     switch (scheme)
     {
         case ENCRYPT_RSA_PKCS1:
             padding = RSA_PKCS1_PADDING;
             break;
         case ENCRYPT_RSA_OAEP_SHA1:
             padding = RSA_PKCS1_OAEP_PADDING;
             break;
         default:
             DBG1(DBG_LIB, "encryption scheme %N not supported via openssl",
                  encryption_scheme_names, scheme);
             return FALSE;
     }
     decrypted = malloc(RSA_size(this->rsa));
     len = RSA_private_decrypt(crypto.len, crypto.ptr, decrypted,
                               this->rsa, padding);
     if (len < 0)
     {
         DBG1(DBG_LIB, "RSA decryption failed");
         free(decrypted);
         return FALSE;
     }
     *plain = chunk_create(decrypted, len);
     return TRUE;
 }
METHOD (private_key_t , get_keysize , int , private_openssl_rsa_private_key_t * this)
Definition at line 206 of file openssl_rsa_private_key.c.
References rsa.
 {
     return RSA_size(this->rsa) * 8;
 }
METHOD (private_key_t , get_public_key , public_key_t * , private_openssl_rsa_private_key_t * this)
Definition at line 212 of file openssl_rsa_private_key.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, chunk_alloc, credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, enc, free(), key, KEY_RSA, lib, chunk_t::ptr, and rsa.
 {
     chunk_t enc;
     public_key_t *key;
     u_char *p;
     enc = chunk_alloc(i2d_RSAPublicKey(this->rsa, NULL));
     p = enc.ptr;
     i2d_RSAPublicKey(this->rsa, &p);
     key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                              BUILD_BLOB_ASN1_DER, enc, BUILD_END);
     free(enc.ptr);
     return key;
 }
METHOD (private_key_t , get_fingerprint , bool , private_openssl_rsa_private_key_t * this, cred_encoding_type_t type, chunk_t * fingerprint)
Definition at line 228 of file openssl_rsa_private_key.c.
References openssl_rsa_fingerprint(), and rsa.
 {
     return openssl_rsa_fingerprint(this->rsa, type, fingerprint);
 }
METHOD (private_key_t , get_encoding , bool , private_openssl_rsa_private_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 235 of file openssl_rsa_private_key.c.
References chunk_alloc, chunk_clear(), CRED_PART_END, CRED_PART_RSA_PRIV_ASN1_DER, cred_encoding_t::encode, encoding, library_t::encoding, FALSE, lib, PRIVKEY_ASN1_DER, PRIVKEY_PEM, chunk_t::ptr, rsa, and TRUE.
 {
     u_char *p;
     if (this->engine)
     {
         return FALSE;
     }
     switch (type)
     {
         case PRIVKEY_ASN1_DER:
         case PRIVKEY_PEM:
         {
             bool success = TRUE;
             *encoding = chunk_alloc(i2d_RSAPrivateKey(this->rsa, NULL));
             p = encoding->ptr;
             i2d_RSAPrivateKey(this->rsa, &p);
             if (type == PRIVKEY_PEM)
             {
                 chunk_t asn1_encoding = *encoding;
                 success = lib->encoding->encode(lib->encoding, PRIVKEY_PEM,
                                 NULL, encoding, CRED_PART_RSA_PRIV_ASN1_DER,
                                 asn1_encoding, CRED_PART_END);
                 chunk_clear(&asn1_encoding);
             }
             return success;
         }
         default:
             return FALSE;
     }
 }
METHOD (private_key_t , get_ref , private_key_t * , private_openssl_rsa_private_key_t * this)
Definition at line 272 of file openssl_rsa_private_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (private_key_t , destroy , void , private_openssl_rsa_private_key_t * this)
Definition at line 279 of file openssl_rsa_private_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), lib, ref_put(), and rsa.
 {
     if (ref_put(&this->ref))
     {
         if (this->rsa)
         {
             lib->encoding->clear_cache(lib->encoding, this->rsa);
             RSA_free(this->rsa);
         }
         free(this);
     }
 }
bool openssl_rsa_fingerprint (RSA * rsa, cred_encoding_type_t type, chunk_t * fp)
Calculate fingerprint from a RSA key, also used in rsa private key.
Definition at line 203 of file openssl_rsa_public_key.c.
References hasher_t::allocate_hash, cred_encoding_t::cache, chunk_alloc, chunk_empty, chunk_free(), crypto_factory_t::create_hasher, CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, cred_encoding_t::encode, library_t::encoding, FALSE, free(), cred_encoding_t::get_cache, HASH_SHA1, hasher, key, KEYID_PUBKEY_INFO_SHA1, KEYID_PUBKEY_SHA1, lib, n, openssl_bn2chunk(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     hasher_t *hasher;
     chunk_t key;
     u_char *p;
     if (lib->encoding->get_cache(lib->encoding, type, rsa, fp))
     {
         return TRUE;
     }
     switch (type)
     {
         case KEYID_PUBKEY_SHA1:
             key = chunk_alloc(i2d_RSAPublicKey(rsa, NULL));
             p = key.ptr;
             i2d_RSAPublicKey(rsa, &p);
             break;
         case KEYID_PUBKEY_INFO_SHA1:
             key = chunk_alloc(i2d_RSA_PUBKEY(rsa, NULL));
             p = key.ptr;
             i2d_RSA_PUBKEY(rsa, &p);
             break;
         default:
         {
             chunk_t n = chunk_empty, e = chunk_empty;
             bool success = FALSE;
             if (openssl_bn2chunk(rsa->n, &n) &&
                 openssl_bn2chunk(rsa->e, &e))
             {
                 success = lib->encoding->encode(lib->encoding, type, rsa, fp,
                                     CRED_PART_RSA_MODULUS, n,
                                     CRED_PART_RSA_PUB_EXP, e, CRED_PART_END);
             }
             chunk_free(&n);
             chunk_free(&e);
             return success;
         }
     }
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher || !hasher->allocate_hash(hasher, key, fp))
     {
         DBG1(DBG_LIB, "SHA1 hash algorithm not supported, fingerprinting failed");
         DESTROY_IF(hasher);
         free(key.ptr);
         return FALSE;
     }
     free(key.ptr);
     hasher->destroy(hasher);
     lib->encoding->cache(lib->encoding, type, rsa, *fp);
     return TRUE;
 }