strongSwan: gcrypt_rsa_private_key
gcrypt_rsa_private_key
gcrypt
Classes
struct gcrypt_rsa_private_key_t
Typedefs
typedef struct
gcrypt_rsa_private_key_t gcrypt_rsa_private_key_t
Functions
gcrypt_rsa_private_key_t * gcrypt_rsa_private_key_gen (key_type_t type, va_list args)
gcrypt_rsa_private_key_t * gcrypt_rsa_private_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct gcrypt_rsa_private_key_t gcrypt_rsa_private_key_t
Definition at line 27 of file gcrypt_rsa_private_key.h.
Function Documentation
gcrypt_rsa_private_key_t* gcrypt_rsa_private_key_gen (key_type_t type, va_list args)
Generate a private key using gcrypt.
Accepts the BUILD_KEY_SIZE argument.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
generated key, NULL on failure
See header.
Definition at line 455 of file gcrypt_rsa_private_key.c.
References BUILD_END, BUILD_KEY_SIZE, create_empty(), DBG1, DBG_LIB, free(), key, key_size, and TRUE.
Referenced by METHOD().
 {
     private_gcrypt_rsa_private_key_t *this;
     gcry_sexp_t param;
     gcry_error_t err;
     u_int key_size = 0;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_KEY_SIZE:
                 key_size = va_arg(args, u_int);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!key_size)
     {
         return NULL;
     }
     err = gcry_sexp_build(&param, NULL, "(genkey(rsa(nbits %d)))", key_size);
     if (err)
     {
         DBG1(DBG_LIB, "building S-expression failed: %s", gpg_strerror(err));
         return NULL;
     }
     this = create_empty();
     err = gcry_pk_genkey(&this->key, param);
     gcry_sexp_release(param);
     if (err)
     {
         free(this);
         DBG1(DBG_LIB, "generating RSA key failed: %s", gpg_strerror(err));
         return NULL;
     }
     return &this->public;
 }
gcrypt_rsa_private_key_t* gcrypt_rsa_private_key_load (key_type_t type, va_list args)
Load a gcrypt RSA private keys.
Accepts BUILD_RSA_* components.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 503 of file gcrypt_rsa_private_key.c.
References BUILD_END, BUILD_RSA_COEFF, BUILD_RSA_EXP1, BUILD_RSA_EXP2, BUILD_RSA_MODULUS, BUILD_RSA_PRIME1, BUILD_RSA_PRIME2, BUILD_RSA_PRIV_EXP, BUILD_RSA_PUB_EXP, chunk_empty, create_empty(), DBG1, DBG_LIB, destroy(), free(), key, chunk_t::len, n, chunk_t::ptr, q, and TRUE.
Referenced by METHOD().
 {
     private_gcrypt_rsa_private_key_t *this;
     chunk_t n, e, d, p, q, u;
     gcry_error_t err;
     n = e = d = p = q = u = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_RSA_MODULUS:
                 n = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PUB_EXP:
                 e = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIV_EXP:
                 d = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIME1:
                 /* swap p and q, gcrypt expects p < q */
                 q = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIME2:
                 p = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_EXP1:
             case BUILD_RSA_EXP2:
                 /* not required for gcrypt */
                 va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_COEFF:
                 u = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     this = create_empty();
     err = gcry_sexp_build(&this->key, NULL,
                     "(private-key(rsa(n %b)(e %b)(d %b)(p %b)(q %b)(u %b)))",
                     n.len, n.ptr, e.len, e.ptr, d.len, d.ptr,
                     p.len, p.ptr, q.len, q.ptr, u.len, u.ptr);
     if (err)
     {
         DBG1(DBG_LIB, "loading private key failed: %s", gpg_strerror(err));
         free(this);
         return NULL;
     }
     err = gcry_pk_testkey(this->key);
     if (err)
     {
         DBG1(DBG_LIB, "private key sanity check failed: %s", gpg_strerror(err));
         destroy(this);
         return NULL;
     }
     return &this->public;
 }