strongSwan: curl_fetcher
curl_fetcher
curl
Classes
struct curl_fetcher_t
Typedefs
typedef struct curl_fetcher_t curl_fetcher_t
Functions
curl_fetcher_t * curl_fetcher_create ()
Detailed Description
Typedef Documentation
typedef struct curl_fetcher_t curl_fetcher_t
Definition at line 24 of file curl_fetcher.h.
Function Documentation
curl_fetcher_t* curl_fetcher_create ()
Create a curl_fetcher instance.
Definition at line 239 of file curl_fetcher.c.
References fetcher_default_callback(), free(), and INIT.
Referenced by query_protocols().
 {
     private_curl_fetcher_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .fetch = _fetch,
                 .set_option = _set_option,
                 .destroy = _destroy,
             },
         },
         .curl = curl_easy_init(),
         .cb = fetcher_default_callback,
     );
     if (!this->curl)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }