strongSwan: kernel_libipsec_ipsec.c File Reference
kernel_libipsec_ipsec.c File Reference
#include "kernel_libipsec_ipsec.h"
#include "kernel_libipsec_router.h"
#include <library.h>
#include <ipsec.h>
#include <hydra.h>
#include <networking/tun_device.h>
#include <threading/mutex.h>
#include <utils/debug.h>
Classes
struct private_kernel_libipsec_ipsec_t
struct exclude_route_t
struct route_entry_t
struct policy_entry_t
Typedefs
typedef struct
private_kernel_libipsec_ipsec_t private_kernel_libipsec_ipsec_t
typedef struct exclude_route_t exclude_route_t
typedef struct route_entry_t route_entry_t
typedef struct policy_entry_t policy_entry_t
Functions
static void exclude_route_destroy (exclude_route_t *this)
static bool exclude_route_match (exclude_route_t *current, host_t *dst)
static void route_entry_destroy (route_entry_t *this)
static bool route_entry_equals (route_entry_t *a, route_entry_t *b)
static policy_entry_t * create_policy_entry (traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t dir)
static void policy_entry_destroy (policy_entry_t *this)
static bool policy_entry_equals (policy_entry_t *a, policy_entry_t *b)
static void expire (u_int8_t protocol, u_int32_t spi, host_t *dst, bool hard)
METHOD (kernel_ipsec_t, get_features, kernel_feature_t, private_kernel_libipsec_ipsec_t *this)
METHOD (kernel_ipsec_t, get_spi, status_t, private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
METHOD (kernel_ipsec_t, get_cpi, status_t, private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, u_int16_t *cpi)
METHOD (kernel_ipsec_t, add_sa, status_t, private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t *src_ts, linked_list_t *dst_ts)
METHOD (kernel_ipsec_t, update_sa, status_t, private_kernel_libipsec_ipsec_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
METHOD (kernel_ipsec_t, query_sa, status_t, private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
METHOD (kernel_ipsec_t, del_sa, status_t, private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
METHOD (kernel_ipsec_t, flush_sas, status_t, private_kernel_libipsec_ipsec_t *this)
static void add_exclude_route (private_kernel_libipsec_ipsec_t *this, route_entry_t *route, host_t *src, host_t *dst)
static void remove_exclude_route (private_kernel_libipsec_ipsec_t *this, route_entry_t *route)
static bool install_route (private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_entry_t *policy)
METHOD (kernel_ipsec_t, add_policy, status_t, private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_ipsec_t, query_policy, status_t, private_kernel_libipsec_ipsec_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, mark_t mark, time_t *use_time)
METHOD (kernel_ipsec_t, del_policy, status_t, private_kernel_libipsec_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_ipsec_t, flush_policies, status_t, private_kernel_libipsec_ipsec_t *this)
METHOD (kernel_ipsec_t, bypass_socket, bool, private_kernel_libipsec_ipsec_t *this, int fd, int family)
METHOD (kernel_ipsec_t, enable_udp_decap, bool, private_kernel_libipsec_ipsec_t *this, int fd, int family, u_int16_t port)
METHOD (kernel_ipsec_t, destroy, void, private_kernel_libipsec_ipsec_t *this)
kernel_libipsec_ipsec_t * kernel_libipsec_ipsec_create ()
Typedef Documentation
typedef struct exclude_route_t exclude_route_t
Definition at line 60 of file kernel_libipsec_ipsec.c.
typedef struct policy_entry_t policy_entry_t
Definition at line 147 of file kernel_libipsec_ipsec.c.
typedef struct private_kernel_libipsec_ipsec_t private_kernel_libipsec_ipsec_t
Definition at line 25 of file kernel_libipsec_ipsec.c.
typedef struct route_entry_t route_entry_t
Definition at line 96 of file kernel_libipsec_ipsec.c.
Function Documentation
static void add_exclude_route (private_kernel_libipsec_ipsec_t * this, route_entry_t * route, host_t * src, host_t * dst) static
Add an explicit exclude route to a routing entry
Definition at line 299 of file kernel_libipsec_ipsec.c.
References kernel_interface_t::add_route, host_t::clone, DBG1, DBG2, DBG_KNL, host_t::destroy, route_entry_t::exclude, exclude_route_match(), free(), host_t::get_address, host_t::get_family, kernel_interface_t::get_interface, kernel_interface_t::get_nexthop, hydra, INIT, hydra_t::kernel_interface, exclude_route_t::refs, src, and SUCCESS.
Referenced by install_route().
 {
     exclude_route_t *exclude;
     host_t *gtw;
     if (this->excludes->find_first(this->excludes,
                                   (linked_list_match_t)exclude_route_match,
                                   (void**)&exclude, dst) == SUCCESS)
     {
         route->exclude = exclude;
         exclude->refs++;
     }
     if (!route->exclude)
     {
         DBG2(DBG_KNL, "installing new exclude route for %H src %H", dst, src);
         gtw = hydra->kernel_interface->get_nexthop(hydra->kernel_interface,
                                                    dst, -1, NULL);
         if (gtw)
         {
             char *if_name = NULL;
             if (hydra->kernel_interface->get_interface(
                                     hydra->kernel_interface, src, &if_name) &&
                 hydra->kernel_interface->add_route(hydra->kernel_interface,
                                     dst->get_address(dst),
                                     dst->get_family(dst) == AF_INET ? 32 : 128,
                                     gtw, src, if_name) == SUCCESS)
             {
                 INIT(exclude,
                     .dst = dst->clone(dst),
                     .src = src->clone(src),
                     .gtw = gtw->clone(gtw),
                     .refs = 1,
                 );
                 route->exclude = exclude;
                 this->excludes->insert_last(this->excludes, exclude);
             }
             else
             {
                 DBG1(DBG_KNL, "installing exclude route for %H failed", dst);
             }
             gtw->destroy(gtw);
             free(if_name);
         }
         else
         {
             DBG1(DBG_KNL, "gateway lookup for %H failed", dst);
         }
     }
 }
static policy_entry_t* create_policy_entry (traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t dir) static
Create a policy_entry_t object
Definition at line 173 of file kernel_libipsec_ipsec.c.
References dst, traffic_selector_t::get_protocol, INIT, max, src, and traffic_selector_t::to_subnet.
Referenced by METHOD().
 {
     policy_entry_t *this;
     INIT(this,
         .direction = dir,
     );
     src_ts->to_subnet(src_ts, &this->src.net, &this->src.mask);
     dst_ts->to_subnet(dst_ts, &this->dst.net, &this->dst.mask);
     /* src or dest proto may be "any" (0), use more restrictive one */
     this->src.proto = max(src_ts->get_protocol(src_ts),
                           dst_ts->get_protocol(dst_ts));
     this->src.proto = this->src.proto ? this->src.proto : 0;
     this->dst.proto = this->src.proto;
     return this;
 }
static void exclude_route_destroy (exclude_route_t * this) static
Clean up an exclude route entry
Definition at line 79 of file kernel_libipsec_ipsec.c.
References dst, free(), and src.
Referenced by remove_exclude_route().
 {
     this->dst->destroy(this->dst);
     this->src->destroy(this->src);
     this->gtw->destroy(this->gtw);
     free(this);
 }
static bool exclude_route_match (exclude_route_t * current, host_t * dst) static
Find an exclude route entry by destination address
Definition at line 90 of file kernel_libipsec_ipsec.c.
References exclude_route_t::dst, and host_t::ip_equals.
Referenced by add_exclude_route().
 {
     return dst->ip_equals(dst, current->dst);
 }
static void expire (u_int8_t protocol, u_int32_t spi, host_t * dst, bool hard) static
Expiration callback
Definition at line 225 of file kernel_libipsec_ipsec.c.
References kernel_interface_t::expire, hydra, and hydra_t::kernel_interface.
Referenced by kernel_libipsec_ipsec_create(), METHOD(), and process_expire().
 {
     hydra->kernel_interface->expire(hydra->kernel_interface, protocol,
                                     spi, dst, hard);
 }
static bool install_route (private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_entry_t * policy) static
Install a route for the given policy
this->mutex is released by this function
Definition at line 391 of file kernel_libipsec_ipsec.c.
References add_exclude_route(), kernel_interface_t::add_route, ALREADY_DONE, chunk_clone, DBG1, DBG2, DBG_KNL, kernel_interface_t::del_route, traffic_selector_t::destroy, DESTROY_IF, policy_entry_t::direction, policy_entry_t::dst, route_entry_t::dst_net, FALSE, route_entry_t::gateway, host_t::get_address, kernel_interface_t::get_address_by_ts, kernel_interface_t::get_nexthop, kernel_libipsec_router_t::get_tun_name, traffic_selector_t::get_type, hydra, route_entry_t::if_name, ignore(), traffic_selector_t::includes, INIT, traffic_selector_t::is_contained_in, traffic_selector_t::is_host, hydra_t::kernel_interface, policy_entry_t::mask, mutex, policy_entry_t::net, policy_dir_names, POLICY_OUT, route_entry_t::prefixlen, remove_exclude_route(), policy_entry_t::route, route_entry_destroy(), route_entry_equals(), router, route_entry_t::src_ip, SUCCESS, traffic_selector_create_from_cidr(), TRUE, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and mutex_t::unlock.
Referenced by METHOD().
 {
     route_entry_t *route, *old;
     host_t *src_ip;
     bool is_virtual;
     if (policy->direction != POLICY_OUT)
     {
         this->mutex->unlock(this->mutex);
         return TRUE;
     }
     if (hydra->kernel_interface->get_address_by_ts(hydra->kernel_interface,
                                     src_ts, &src_ip, &is_virtual) != SUCCESS)
     {
         traffic_selector_t *multicast, *broadcast = NULL;
         bool ignore = FALSE;
         this->mutex->unlock(this->mutex);
         switch (src_ts->get_type(src_ts))
         {
             case TS_IPV4_ADDR_RANGE:
                 multicast = traffic_selector_create_from_cidr("224.0.0.0/4",
                                                               0, 0, 0xffff);
                 broadcast = traffic_selector_create_from_cidr("255.255.255.255/32",
                                                               0, 0, 0xffff);
                 break;
             case TS_IPV6_ADDR_RANGE:
                 multicast = traffic_selector_create_from_cidr("ff00::/8",
                                                               0, 0, 0xffff);
                 break;
             default:
                 return FALSE;
         }
         ignore = src_ts->is_contained_in(src_ts, multicast);
         ignore |= broadcast && src_ts->is_contained_in(src_ts, broadcast);
         multicast->destroy(multicast);
         DESTROY_IF(broadcast);
         if (!ignore)
         {
             DBG1(DBG_KNL, "error installing route with policy %R === %R %N",
                  src_ts, dst_ts, policy_dir_names, policy->direction);
         }
         return ignore;
     }
     INIT(route,
         .if_name = router->get_tun_name(router, is_virtual ? src_ip : NULL),
         .src_ip = src_ip,
         .dst_net = chunk_clone(policy->dst.net->get_address(policy->dst.net)),
         .prefixlen = policy->dst.mask,
     );
 #ifndef __linux__
     /* on Linux we cant't install a gateway */
     route->gateway = hydra->kernel_interface->get_nexthop(
                                         hydra->kernel_interface, dst, -1, src);
 #endif
     if (policy->route)
     {
         old = policy->route;
         if (route_entry_equals(old, route))
         {   /* such a route already exists */
             route_entry_destroy(route);
             this->mutex->unlock(this->mutex);
             return TRUE;
         }
         /* uninstall previously installed route */
         if (hydra->kernel_interface->del_route(hydra->kernel_interface,
                                     old->dst_net, old->prefixlen, old->gateway,
                                     old->src_ip, old->if_name) != SUCCESS)
         {
             DBG1(DBG_KNL, "error uninstalling route installed with policy "
                  "%R === %R %N", src_ts, dst_ts, policy_dir_names,
                  policy->direction);
         }
         route_entry_destroy(old);
         policy->route = NULL;
     }
     if (!this->allow_peer_ts && dst_ts->is_host(dst_ts, dst))
     {
         DBG1(DBG_KNL, "can't install route for %R === %R %N, conflicts with "
              "IKE traffic", src_ts, dst_ts, policy_dir_names,
              policy->direction);
         route_entry_destroy(route);
         this->mutex->unlock(this->mutex);
         return FALSE;
     }
     /* if remote traffic selector covers the IKE peer, add an exclude route */
     if (!this->allow_peer_ts && dst_ts->includes(dst_ts, dst))
     {
         /* add exclude route for peer */
         add_exclude_route(this, route, src, dst);
     }
     DBG2(DBG_KNL, "installing route: %R src %H dev %s",
          dst_ts, route->src_ip, route->if_name);
     switch (hydra->kernel_interface->add_route(hydra->kernel_interface,
                             route->dst_net, route->prefixlen, route->gateway,
                             route->src_ip, route->if_name))
     {
         case ALREADY_DONE:
             /* route exists, do not uninstall */
             remove_exclude_route(this, route);
             route_entry_destroy(route);
             this->mutex->unlock(this->mutex);
             return TRUE;
         case SUCCESS:
             /* cache the installed route */
             policy->route = route;
             this->mutex->unlock(this->mutex);
             return TRUE;
         default:
             DBG1(DBG_KNL, "installing route failed: %R src %H dev %s",
                  dst_ts, route->src_ip, route->if_name);
             remove_exclude_route(this, route);
             route_entry_destroy(route);
             this->mutex->unlock(this->mutex);
             return FALSE;
     }
 }
METHOD (kernel_ipsec_t , get_features , kernel_feature_t , private_kernel_libipsec_ipsec_t * this)
Definition at line 231 of file kernel_libipsec_ipsec.c.
References KERNEL_ESP_V3_TFC, and KERNEL_REQUIRE_UDP_ENCAPSULATION.
 {
     return KERNEL_REQUIRE_UDP_ENCAPSULATION | KERNEL_ESP_V3_TFC;
 }
METHOD (kernel_ipsec_t , get_spi , status_t , private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, u_int8_t protocol, u_int32_t * spi)
Definition at line 237 of file kernel_libipsec_ipsec.c.
References ipsec_sa_mgr_t::get_spi, ipsec, and ipsec_t::sas.
 {
     return ipsec->sas->get_spi(ipsec->sas, src, dst, protocol, spi);
 }
METHOD (kernel_ipsec_t , get_cpi , status_t , private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, u_int16_t * cpi)
Definition at line 244 of file kernel_libipsec_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , add_sa , status_t , private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t * lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t * src_ts, linked_list_t * dst_ts)
Definition at line 251 of file kernel_libipsec_ipsec.c.
References ipsec_sa_mgr_t::add_sa, ipsec, and ipsec_t::sas.
 {
     return ipsec->sas->add_sa(ipsec->sas, src, dst, spi, protocol, reqid, mark,
                               tfc, lifetime, enc_alg, enc_key, int_alg, int_key,
                               mode, ipcomp, cpi, initiator, encap, esn,
                               inbound, update);
 }
METHOD (kernel_ipsec_t , update_sa , status_t , private_kernel_libipsec_ipsec_t * this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t * src, host_t * dst, host_t * new_src, host_t * new_dst, bool encap, bool new_encap, mark_t mark)
Definition at line 266 of file kernel_libipsec_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , query_sa , status_t , private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t * bytes, u_int64_t * packets, time_t * time)
Definition at line 274 of file kernel_libipsec_ipsec.c.
References ipsec, ipsec_sa_mgr_t::query_sa, and ipsec_t::sas.
 {
     return ipsec->sas->query_sa(ipsec->sas, src, dst, spi, protocol, mark,
                                 bytes, packets, time);
 }
METHOD (kernel_ipsec_t , del_sa , status_t , private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Definition at line 283 of file kernel_libipsec_ipsec.c.
References ipsec_sa_mgr_t::del_sa, ipsec, and ipsec_t::sas.
 {
     return ipsec->sas->del_sa(ipsec->sas, src, dst, spi, protocol, cpi, mark);
 }
METHOD (kernel_ipsec_t , flush_sas , status_t , private_kernel_libipsec_ipsec_t * this)
Definition at line 290 of file kernel_libipsec_ipsec.c.
References ipsec_sa_mgr_t::flush_sas, ipsec, and ipsec_t::sas.
 {
     return ipsec->sas->flush_sas(ipsec->sas);
 }
METHOD (kernel_ipsec_t , add_policy , status_t , private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 518 of file kernel_libipsec_ipsec.c.
References ipsec_policy_mgr_t::add_policy, create_policy_entry(), FAILED, found, install_route(), ipsec, mutex_t::lock, mutex, ipsec_t::policies, policy_entry_destroy(), policy_entry_equals(), policy_entry_t::refs, status, and SUCCESS.
 {
     policy_entry_t *policy, *found = NULL;
     status_t status;
     status = ipsec->policies->add_policy(ipsec->policies, src, dst, src_ts,
                                 dst_ts, direction, type, sa, mark, priority);
     if (status != SUCCESS)
     {
         return status;
     }
     /* we track policies in order to install routes */
     policy = create_policy_entry(src_ts, dst_ts, direction);
     this->mutex->lock(this->mutex);
     if (this->policies->find_first(this->policies,
                                   (linked_list_match_t)policy_entry_equals,
                                   (void**)&found, policy) == SUCCESS)
     {
         policy_entry_destroy(policy);
         policy = found;
     }
     else
     {   /* use the new one, if we have no such policy */
         this->policies->insert_last(this->policies, policy);
     }
     policy->refs++;
     if (!install_route(this, src, dst, src_ts, dst_ts, policy))
     {
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , query_policy , status_t , private_kernel_libipsec_ipsec_t * this, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, mark_t mark, time_t * use_time)
Definition at line 557 of file kernel_libipsec_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , del_policy , status_t , private_kernel_libipsec_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 565 of file kernel_libipsec_ipsec.c.
References create_policy_entry(), DBG1, DBG_KNL, ipsec_policy_mgr_t::del_policy, kernel_interface_t::del_route, route_entry_t::dst_net, found, route_entry_t::gateway, hydra, route_entry_t::if_name, ipsec, hydra_t::kernel_interface, mutex_t::lock, mutex, ipsec_t::policies, policy_dir_names, policy_entry_destroy(), policy_entry_equals(), route_entry_t::prefixlen, policy_entry_t::refs, remove_exclude_route(), ipsec_sa_cfg_t::reqid, policy_entry_t::route, route_entry_t::src_ip, status, SUCCESS, and mutex_t::unlock.
 {
     policy_entry_t *policy, *found = NULL;
     status_t status;
     status = ipsec->policies->del_policy(ipsec->policies, src_ts, dst_ts,
                                          direction, sa->reqid, mark, priority);
     policy = create_policy_entry(src_ts, dst_ts, direction);
     this->mutex->lock(this->mutex);
     if (this->policies->find_first(this->policies,
                                   (linked_list_match_t)policy_entry_equals,
                                   (void**)&found, policy) != SUCCESS)
     {
         policy_entry_destroy(policy);
         this->mutex->unlock(this->mutex);
         return status;
     }
     policy_entry_destroy(policy);
     policy = found;
     if (--policy->refs > 0)
     {   /* policy is still in use */
         this->mutex->unlock(this->mutex);
         return status;
     }
     if (policy->route)
     {
         route_entry_t *route = policy->route;
         if (hydra->kernel_interface->del_route(hydra->kernel_interface,
                 route->dst_net, route->prefixlen, route->gateway, route->src_ip,
                 route->if_name) != SUCCESS)
         {
             DBG1(DBG_KNL, "error uninstalling route installed with "
                           "policy %R === %R %N", src_ts, dst_ts,
                            policy_dir_names, direction);
         }
         remove_exclude_route(this, route);
     }
     this->policies->remove(this->policies, policy, NULL);
     policy_entry_destroy(policy);
     this->mutex->unlock(this->mutex);
     return status;
 }
METHOD (kernel_ipsec_t , flush_policies , status_t , private_kernel_libipsec_ipsec_t * this)
Definition at line 617 of file kernel_libipsec_ipsec.c.
References kernel_interface_t::del_route, route_entry_t::dst_net, ipsec_policy_mgr_t::flush_policies, route_entry_t::gateway, hydra, route_entry_t::if_name, ipsec, hydra_t::kernel_interface, mutex_t::lock, mutex, ipsec_t::policies, policy_entry_destroy(), route_entry_t::prefixlen, remove_exclude_route(), policy_entry_t::route, route_entry_t::src_ip, status, SUCCESS, and mutex_t::unlock.
 {
     policy_entry_t *pol;
     status_t status;
     status = ipsec->policies->flush_policies(ipsec->policies);
     this->mutex->lock(this->mutex);
     while (this->policies->remove_first(this->policies, (void*)&pol) == SUCCESS)
     {
         if (pol->route)
         {
             route_entry_t *route = pol->route;
             hydra->kernel_interface->del_route(hydra->kernel_interface,
                     route->dst_net, route->prefixlen, route->gateway,
                     route->src_ip, route->if_name);
             remove_exclude_route(this, route);
         }
         policy_entry_destroy(pol);
     }
     this->mutex->unlock(this->mutex);
     return status;
 }
METHOD (kernel_ipsec_t , bypass_socket , bool , private_kernel_libipsec_ipsec_t * this, int fd, int family)
Definition at line 643 of file kernel_libipsec_ipsec.c.
References NOT_SUPPORTED.
 {
     /* we use exclude routes for this */
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , enable_udp_decap , bool , private_kernel_libipsec_ipsec_t * this, int fd, int family, u_int16_t port)
Definition at line 650 of file kernel_libipsec_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , destroy , void , private_kernel_libipsec_ipsec_t * this)
Definition at line 656 of file kernel_libipsec_ipsec.c.
References mutex_t::destroy, ipsec_t::events, free(), ipsec, mutex, policy_entry_destroy(), and ipsec_event_relay_t::unregister_listener.
 {
     ipsec->events->unregister_listener(ipsec->events, &this->ipsec_listener);
     this->policies->destroy_function(this->policies, (void*)policy_entry_destroy);
     this->excludes->destroy(this->excludes);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void policy_entry_destroy (policy_entry_t * this) static
Destroy a policy_entry_t object
Definition at line 196 of file kernel_libipsec_ipsec.c.
References DESTROY_IF, dst, free(), route_entry_destroy(), and src.
Referenced by METHOD().
 {
     if (this->route)
     {
         route_entry_destroy(this->route);
     }
     DESTROY_IF(this->src.net);
     DESTROY_IF(this->dst.net);
     free(this);
 }
static bool policy_entry_equals (policy_entry_t * a, policy_entry_t * b) inline static
Compare two policy_entry_t objects
Definition at line 210 of file kernel_libipsec_ipsec.c.
References policy_entry_t::direction, policy_entry_t::dst, host_t::equals, policy_entry_t::mask, policy_entry_t::net, policy_entry_t::proto, and policy_entry_t::src.
Referenced by METHOD().
 {
     return a->direction == b->direction &&
            a->src.proto == b->src.proto &&
            a->dst.proto == b->dst.proto &&
            a->src.mask == b->src.mask &&
            a->dst.mask == b->dst.mask &&
            a->src.net->equals(a->src.net, b->src.net) &&
            a->dst.net->equals(a->dst.net, b->dst.net);
 }
static void remove_exclude_route (private_kernel_libipsec_ipsec_t * this, route_entry_t * route) static
Remove an exclude route attached to a routing entry
Definition at line 355 of file kernel_libipsec_ipsec.c.
References DBG1, DBG2, DBG_KNL, kernel_interface_t::del_route, exclude_route_t::dst, dst, route_entry_t::exclude, exclude_route_destroy(), free(), host_t::get_address, host_t::get_family, kernel_interface_t::get_interface, exclude_route_t::gtw, hydra, hydra_t::kernel_interface, exclude_route_t::refs, exclude_route_t::src, and SUCCESS.
Referenced by install_route(), and METHOD().
 {
     char *if_name = NULL;
     host_t *dst;
     if (!route->exclude || --route->exclude->refs > 0)
     {
         return;
     }
     this->excludes->remove(this->excludes, route->exclude, NULL);
     dst = route->exclude->dst;
     DBG2(DBG_KNL, "uninstalling exclude route for %H src %H",
          dst, route->exclude->src);
     if (hydra->kernel_interface->get_interface(
                                     hydra->kernel_interface,
                                     route->exclude->src, &if_name) &&
         hydra->kernel_interface->del_route(hydra->kernel_interface,
                                     dst->get_address(dst),
                                     dst->get_family(dst) == AF_INET ? 32 : 128,
                                     route->exclude->gtw, route->exclude->src,
                                     if_name) != SUCCESS)
     {
         DBG1(DBG_KNL, "uninstalling exclude route for %H failed", dst);
     }
     exclude_route_destroy(route->exclude);
     route->exclude = NULL;
     free(if_name);
 }
static void route_entry_destroy (route_entry_t * this) static
Destroy a route_entry_t object
Definition at line 119 of file kernel_libipsec_ipsec.c.
References chunk_free(), DESTROY_IF, and free().
Referenced by install_route(), and policy_entry_destroy().
 {
     free(this->if_name);
     DESTROY_IF(this->src_ip);
     DESTROY_IF(this->gateway);
     chunk_free(&this->dst_net);
     free(this);
 }
static bool route_entry_equals (route_entry_t * a, route_entry_t * b) static
Compare two route_entry_t objects
Definition at line 131 of file kernel_libipsec_ipsec.c.
References chunk_equals(), route_entry_t::dst_net, FALSE, route_entry_t::gateway, route_entry_t::if_name, host_t::ip_equals, route_entry_t::prefixlen, route_entry_t::src_ip, and streq().
Referenced by install_route().
 {
     if ((!a->src_ip && !b->src_ip) || (a->src_ip && b->src_ip &&
           a->src_ip->ip_equals(a->src_ip, b->src_ip)))
     {
         if ((!a->gateway && !b->gateway) || (a->gateway && b->gateway &&
               a->gateway->ip_equals(a->gateway, b->gateway)))
         {
             return a->if_name && b->if_name && streq(a->if_name, b->if_name) &&
                    chunk_equals(a->dst_net, b->dst_net) &&
                    a->prefixlen == b->prefixlen;
         }
     }
     return FALSE;
 }