strongSwan: eap_md5.c File Reference
eap_md5.c File Reference
#include "eap_md5.h"
#include <daemon.h>
#include <library.h>
#include <crypto/hashers/hasher.h>
Classes
struct private_eap_md5_t
struct eap_md5_header_t
Macros
#define CHALLENGE_LEN 16
#define PAYLOAD_LEN (CHALLENGE_LEN + sizeof(eap_md5_header_t))
Typedefs
typedef struct private_eap_md5_t private_eap_md5_t
typedef struct eap_md5_header_t eap_md5_header_t
Functions
struct eap_md5_header_t __attribute__ ((__packed__))
static status_t hash_challenge (private_eap_md5_t *this, chunk_t *response, identification_t *me, identification_t *other)
METHOD (eap_method_t, initiate_peer, status_t, private_eap_md5_t *this, eap_payload_t **out)
METHOD (eap_method_t, initiate_server, status_t, private_eap_md5_t *this, eap_payload_t **out)
METHOD (eap_method_t, process_peer, status_t, private_eap_md5_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, process_server, status_t, private_eap_md5_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_md5_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_md5_t *this, chunk_t *msk)
METHOD (eap_method_t, is_mutual, bool, private_eap_md5_t *this)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_md5_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_md5_t *this, u_int8_t identifier)
METHOD (eap_method_t, destroy, void, private_eap_md5_t *this)
eap_md5_t * eap_md5_create_server (identification_t *server, identification_t *peer)
eap_md5_t * eap_md5_create_peer (identification_t *server, identification_t *peer)
Variables
u_int8_t code
u_int8_t identifier
u_int16_t length
u_int8_t type
u_int8_t value_size
u_int8_t value []
Macro Definition Documentation
#define CHALLENGE_LEN 16
Definition at line 75 of file eap_md5.c.
Referenced by METHOD().
#define PAYLOAD_LEN (CHALLENGE_LEN + sizeof(eap_md5_header_t))
Definition at line 76 of file eap_md5.c.
Referenced by METHOD().
Typedef Documentation
typedef struct eap_md5_header_t eap_md5_header_t
Definition at line 55 of file eap_md5.c.
typedef struct private_eap_md5_t private_eap_md5_t
Definition at line 22 of file eap_md5.c.
Function Documentation
static status_t hash_challenge (private_eap_md5_t * this, chunk_t * response, identification_t * me, identification_t * other) static
Hash the challenge string, create response
Definition at line 81 of file eap_md5.c.
References hasher_t::allocate_hash, challenge, chunk_cata, chunk_from_thing, crypto_factory_t::create_hasher, library_t::credmgr, library_t::crypto, DBG1, DBG_IKE, shared_key_t::destroy, hasher_t::destroy, FAILED, shared_key_t::get_key, credential_manager_t::get_shared, HASH_MD5, hasher, identifier, lib, NOT_FOUND, SHARED_EAP, and SUCCESS.
Referenced by METHOD().
 {
     shared_key_t *shared;
     chunk_t concat;
     hasher_t *hasher;
     shared = lib->credmgr->get_shared(lib->credmgr, SHARED_EAP, me, other);
     if (shared == NULL)
     {
         DBG1(DBG_IKE, "no EAP key found for hosts '%Y' - '%Y'", me, other);
         return NOT_FOUND;
     }
     concat = chunk_cata("ccc", chunk_from_thing(this->identifier),
                         shared->get_key(shared), this->challenge);
     shared->destroy(shared);
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_MD5);
     if (hasher == NULL)
     {
         DBG1(DBG_IKE, "EAP-MD5 failed, MD5 not supported");
         return FAILED;
     }
     if (!hasher->allocate_hash(hasher, concat, response))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     hasher->destroy(hasher);
     return SUCCESS;
 }
METHOD (eap_method_t , initiate_peer , status_t , private_eap_md5_t * this, eap_payload_t ** out)
Definition at line 112 of file eap_md5.c.
References FAILED.
 {
     /* peer never initiates */
     return FAILED;
 }
METHOD (eap_method_t , initiate_server , status_t , private_eap_md5_t * this, eap_payload_t ** out)
Definition at line 119 of file eap_md5.c.
References rng_t::allocate_bytes, challenge, CHALLENGE_LEN, chunk_create(), eap_md5_header_t::code, crypto_factory_t::create_rng, library_t::crypto, rng_t::destroy, DESTROY_IF, EAP_MD5, eap_payload_create_data(), EAP_REQUEST, FAILED, identifier, eap_md5_header_t::identifier, eap_md5_header_t::length, lib, memcpy, NEED_MORE, PAYLOAD_LEN, req(), rng, RNG_WEAK, eap_md5_header_t::type, eap_md5_header_t::value, and eap_md5_header_t::value_size.
 {
     rng_t *rng;
     eap_md5_header_t *req;
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng || !rng->allocate_bytes(rng, CHALLENGE_LEN, &this->challenge))
     {
         DESTROY_IF(rng);
         return FAILED;
     }
     rng->destroy(rng);
     req = alloca(PAYLOAD_LEN);
     req->length = htons(PAYLOAD_LEN);
     req->code = EAP_REQUEST;
     req->identifier = this->identifier;
     req->type = EAP_MD5;
     req->value_size = this->challenge.len;
     memcpy(req->value, this->challenge.ptr, this->challenge.len);
     *out = eap_payload_create_data(chunk_create((void*)req, PAYLOAD_LEN));
     return NEED_MORE;
 }
METHOD (eap_method_t , process_peer , status_t , private_eap_md5_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 145 of file eap_md5.c.
References challenge, chunk_clone, chunk_create(), chunk_free(), eap_md5_header_t::code, data, DBG1, DBG_IKE, EAP_MD5, eap_payload_create_data(), EAP_RESPONSE, FAILED, eap_payload_t::get_data, eap_payload_t::get_identifier, hash_challenge(), identifier, eap_md5_header_t::identifier, chunk_t::len, eap_md5_header_t::length, memcpy, NEED_MORE, PAYLOAD_LEN, chunk_t::ptr, req(), response, server, SUCCESS, eap_md5_header_t::type, eap_md5_header_t::value, and eap_md5_header_t::value_size.
 {
     chunk_t response;
     chunk_t data;
     eap_md5_header_t *req;
     this->identifier = in->get_identifier(in);
     data = in->get_data(in);
     if (data.len < 6 || data.ptr[5] + 6 > data.len)
     {
         DBG1(DBG_IKE, "received invalid EAP-MD5 message");
         return FAILED;
     }
     this->challenge = chunk_clone(chunk_create(data.ptr + 6, data.ptr[5]));
     if (hash_challenge(this, &response, this->peer, this->server) != SUCCESS)
     {
         return FAILED;
     }
     req = alloca(PAYLOAD_LEN);
     req->length = htons(PAYLOAD_LEN);
     req->code = EAP_RESPONSE;
     req->identifier = this->identifier;
     req->type = EAP_MD5;
     req->value_size = response.len;
     memcpy(req->value, response.ptr, response.len);
     chunk_free(&response);
     *out = eap_payload_create_data(chunk_create((void*)req, PAYLOAD_LEN));
     return NEED_MORE;
 }
METHOD (eap_method_t , process_server , status_t , private_eap_md5_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 177 of file eap_md5.c.
References chunk_create(), chunk_free(), data, DBG1, DBG_IKE, expected, FAILED, eap_payload_t::get_data, eap_payload_t::get_identifier, hash_challenge(), identifier, chunk_t::len, memeq_const(), chunk_t::ptr, response, server, and SUCCESS.
 {
     chunk_t response, expected;
     chunk_t data;
     data = in->get_data(in);
     if (this->identifier != in->get_identifier(in) ||
         data.len < 6 || data.ptr[5] + 6 > data.len)
     {
         DBG1(DBG_IKE, "received invalid EAP-MD5 message");
         return FAILED;
     }
     if (hash_challenge(this, &expected, this->server, this->peer) != SUCCESS)
     {
         return FAILED;
     }
     response = chunk_create(data.ptr + 6, data.ptr[5]);
     if (response.len < expected.len ||
         !memeq_const(response.ptr, expected.ptr, expected.len))
     {
         chunk_free(&expected);
         DBG1(DBG_IKE, "EAP-MD5 verification failed");
         return FAILED;
     }
     chunk_free(&expected);
     return SUCCESS;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_md5_t * this, u_int32_t * vendor)
Definition at line 206 of file eap_md5.c.
References EAP_MD5.
 {
     *vendor = 0;
     return EAP_MD5;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_md5_t * this, chunk_t * msk)
Definition at line 213 of file eap_md5.c.
References FAILED.
 {
     return FAILED;
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_md5_t * this)
Definition at line 219 of file eap_md5.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_md5_t * this)
Definition at line 225 of file eap_md5.c.
References identifier.
 {
     return this->identifier;
 }
METHOD (eap_method_t , set_identifier , void , private_eap_md5_t * this, u_int8_t identifier)
Definition at line 231 of file eap_md5.c.
References identifier.
 {
     this->identifier = identifier;
 }
METHOD (eap_method_t , destroy , void , private_eap_md5_t * this)
Definition at line 237 of file eap_md5.c.
References challenge, chunk_free(), free(), and server.
 {
     this->peer->destroy(this->peer);
     this->server->destroy(this->server);
     chunk_free(&this->challenge);
     free(this);
 }
Variable Documentation
u_int8_t code
EAP code (REQUEST/RESPONSE)
Definition at line 41 of file eap_md5.c.
u_int8_t identifier
unique message identifier
Definition at line 43 of file eap_md5.c.
Referenced by eap_md5_create_server(), hash_challenge(), and METHOD().
u_int16_t length
length of whole message
Definition at line 45 of file eap_md5.c.
u_int8_t type
EAP type
Definition at line 47 of file eap_md5.c.
u_int8_t value[]
actual value
Definition at line 51 of file eap_md5.c.
u_int8_t value_size
length of value (challenge)
Value-Size
Definition at line 49 of file eap_md5.c.