strongSwan: ip_packet
ip_packet
libipsec
Classes
struct ip_packet_t
Typedefs
typedef struct ip_packet_t ip_packet_t
Functions
ip_packet_t * ip_packet_create (chunk_t packet)
ip_packet_t * ip_packet_create_from_data (host_t *src, host_t *dst, u_int8_t next_header, chunk_t data)
ip_packet_t * ip_packet_create_udp_from_data (host_t *src, host_t *dst, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct ip_packet_t ip_packet_t
Definition at line 28 of file ip_packet.h.
Function Documentation
ip_packet_t* ip_packet_create (chunk_t packet)
Create an IP packet out of data from the wire (or decapsulated from another packet).
Note
The raw IP packet gets either owned by the new object, or destroyed, if the data is invalid.
Parameters
packet the IP packet (including header), gets owned
Returns
ip_packet_t instance, or NULL if invalid
Described in header.
Definition at line 196 of file ip_packet.c.
References chunk_free(), chunk_from_thing, chunk_skip(), DBG1, DBG_ESP, dst, host_create_from_chunk(), INIT, ip, chunk_t::len, min, parse_transport_header(), chunk_t::ptr, src, untoh16(), and version.
Referenced by ip_packet_create_from_data(), METHOD(), process_plain(), remove_padding(), and START_TEST().
 {
     private_ip_packet_t *this;
     u_int8_t version, next_header;
     u_int16_t sport = 0, dport = 0;
     host_t *src, *dst;
     chunk_t payload;
     if (packet.len < 1)
     {
         DBG1(DBG_ESP, "IP packet too short");
         goto failed;
     }
     version = (packet.ptr[0] & 0xf0) >> 4;
     switch (version)
     {
         case 4:
         {
             struct ip *ip;
             if (packet.len < sizeof(struct ip))
             {
                 DBG1(DBG_ESP, "IPv4 packet too short");
                 goto failed;
             }
             ip = (struct ip*)packet.ptr;
             /* remove any RFC 4303 TFC extra padding */
             packet.len = min(packet.len, untoh16(&ip->ip_len));
             payload = chunk_skip(packet, ip->ip_hl * 4);
             if (!parse_transport_header(payload, ip->ip_p, &sport, &dport))
             {
                 goto failed;
             }
             src = host_create_from_chunk(AF_INET,
                                          chunk_from_thing(ip->ip_src), sport);
             dst = host_create_from_chunk(AF_INET,
                                          chunk_from_thing(ip->ip_dst), dport);
             next_header = ip->ip_p;
             break;
         }
 #ifdef HAVE_NETINET_IP6_H
         case 6:
         {
             struct ip6_hdr *ip;
             if (packet.len < sizeof(*ip))
             {
                 DBG1(DBG_ESP, "IPv6 packet too short");
                 goto failed;
             }
             ip = (struct ip6_hdr*)packet.ptr;
             /* remove any RFC 4303 TFC extra padding */
             packet.len = min(packet.len, 40 + untoh16(&ip->ip6_plen));
             /* we only handle packets without extension headers, just skip the
              * basic IPv6 header */
             payload = chunk_skip(packet, 40);
             if (!parse_transport_header(payload, ip->ip6_nxt, &sport, &dport))
             {
                 goto failed;
             }
             src = host_create_from_chunk(AF_INET6,
                                          chunk_from_thing(ip->ip6_src), sport);
             dst = host_create_from_chunk(AF_INET6,
                                          chunk_from_thing(ip->ip6_dst), dport);
             next_header = ip->ip6_nxt;
             break;
         }
 #endif /* HAVE_NETINET_IP6_H */
         default:
             DBG1(DBG_ESP, "unsupported IP version");
             goto failed;
     }
     INIT(this,
         .public = {
             .get_version = _get_version,
             .get_source = _get_source,
             .get_destination = _get_destination,
             .get_next_header = _get_next_header,
             .get_encoding = _get_encoding,
             .get_payload = _get_payload,
             .clone = _clone_,
             .destroy = _destroy,
         },
         .src = src,
         .dst = dst,
         .packet = packet,
         .payload = payload,
         .version = version,
         .next_header = next_header,
     );
     return &this->public;
 failed:
     chunk_free(&packet);
     return NULL;
 }
ip_packet_t* ip_packet_create_from_data (host_t * src, host_t * dst, u_int8_t next_header, chunk_t data)
Encode an IP packet from the given data.
If src and/or dst have ports set they are applied to UDP/TCP headers found in the packet.
Parameters
src source address and optional port (cloned)
dst destination address and optional port (cloned)
next_header the protocol (IPv4) or next header (IPv6)
data complete data after basic IP header (cloned)
Returns
ip_packet_t instance, or NULL if invalid
Described in header.
Definition at line 409 of file ip_packet.c.
References chunk_cat, chunk_from_thing, chunk_internet_checksum(), chunk_skip(), DBG1, DBG_ESP, family, fix_transport_header(), host_t::get_address, host_t::get_family, ip, ip_packet_create(), chunk_t::len, memcpy, and chunk_t::ptr.
Referenced by ip_packet_create_udp_from_data().
 {
     chunk_t packet;
     int family;
     family = src->get_family(src);
     if (family != dst->get_family(dst))
     {
         DBG1(DBG_ESP, "address family does not match");
         return NULL;
     }
     switch (family)
     {
         case AF_INET:
         {
             struct ip ip = {
                 .ip_v = 4,
                 .ip_hl = 5,
                 .ip_len = htons(20 + data.len),
                 .ip_ttl = 0x80,
                 .ip_p = next_header,
             };
             memcpy(&ip.ip_src, src->get_address(src).ptr, sizeof(ip.ip_src));
             memcpy(&ip.ip_dst, dst->get_address(dst).ptr, sizeof(ip.ip_dst));
             ip.ip_sum = chunk_internet_checksum(chunk_from_thing(ip));
             packet = chunk_cat("cc", chunk_from_thing(ip), data);
             fix_transport_header(src, dst, next_header, chunk_skip(packet, 20));
             return ip_packet_create(packet);
         }
 #ifdef HAVE_NETINET_IP6_H
         case AF_INET6:
         {
             struct ip6_hdr ip = {
                 .ip6_flow = htonl(6),
                 .ip6_plen = htons(data.len),
                 .ip6_nxt = next_header,
                 .ip6_hlim = 0x80,
             };
             memcpy(&ip.ip6_src, src->get_address(src).ptr, sizeof(ip.ip6_src));
             memcpy(&ip.ip6_dst, dst->get_address(dst).ptr, sizeof(ip.ip6_dst));
             packet = chunk_cat("cc", chunk_from_thing(ip), data);
             fix_transport_header(src, dst, next_header, chunk_skip(packet, 40));
             return ip_packet_create(packet);
         }
 #endif /* HAVE_NETINET_IP6_H */
         default:
             DBG1(DBG_ESP, "unsupported address family");
             return NULL;
     }
 }
ip_packet_t* ip_packet_create_udp_from_data (host_t * src, host_t * dst, chunk_t data)
Encode a UDP packet from the given data.
Parameters
src source address and port (cloned)
dst destination address and port (cloned)
data UDP data (cloned)
Returns
ip_packet_t instance, or NULL if invalid
Described in header.
Definition at line 467 of file ip_packet.c.
References chunk_cat, chunk_free(), chunk_from_thing, ip_packet_create_from_data(), udphdr::len, and chunk_t::len.
 {
     struct udphdr udp = {
         .len = htons(8 + data.len),
         .check = 0,
     };
     ip_packet_t *packet;
     data = chunk_cat("cc", chunk_from_thing(udp), data);
     packet = ip_packet_create_from_data(src, dst, IPPROTO_UDP, data);
     chunk_free(&data);
     return packet;
 }