strongSwan: eap_radius_provider.c File Reference
eap_radius_provider.c File Reference
#include "eap_radius_provider.h"
#include <daemon.h>
#include <collections/hashtable.h>
#include <threading/mutex.h>
Classes
struct private_listener_t
struct private_eap_radius_provider_t
struct attr_t
struct entry_t
struct attribute_enumerator_t
Typedefs
typedef struct
private_eap_radius_provider_t private_eap_radius_provider_t
typedef struct private_listener_t private_listener_t
Functions
static void destroy_attr (attr_t *this)
static void destroy_entry (entry_t *this)
static entry_t * get_or_create_entry (hashtable_t *hashtable, uintptr_t id)
static void put_or_destroy_entry (hashtable_t *hashtable, entry_t *entry)
static u_int hash (uintptr_t id)
static bool equals (uintptr_t a, uintptr_t b)
static void add_addr (private_eap_radius_provider_t *this, hashtable_t *hashtable, uintptr_t id, host_t *host)
static host_t * remove_addr (private_eap_radius_provider_t *this, hashtable_t *hashtable, uintptr_t id, host_t *addr)
static void add_attr (private_eap_radius_provider_t *this, hashtable_t *hashtable, uintptr_t id, attr_t *attr)
static attr_t * remove_attr (private_eap_radius_provider_t *this, hashtable_t *hashtable, uintptr_t id)
static void release_unclaimed (private_listener_t *this, ike_sa_t *ike_sa)
METHOD (listener_t, message_hook, bool, private_listener_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (listener_t, ike_updown, bool, private_listener_t *this, ike_sa_t *ike_sa, bool up)
static void migrate_entry (hashtable_t *table, uintptr_t old, uintptr_t new)
METHOD (listener_t, ike_rekey, bool, private_listener_t *this, ike_sa_t *old, ike_sa_t *new)
METHOD (attribute_provider_t, acquire_address, host_t *, private_eap_radius_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
METHOD (attribute_provider_t, release_address, bool, private_eap_radius_provider_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
METHOD (enumerator_t, attribute_enumerate, bool, attribute_enumerator_t *this, configuration_attribute_type_t *type, chunk_t *data)
METHOD (enumerator_t, attribute_destroy, void, attribute_enumerator_t *this)
METHOD (attribute_provider_t, create_attribute_enumerator, enumerator_t *, private_eap_radius_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (eap_radius_provider_t, add_framed_ip, void, private_eap_radius_provider_t *this, u_int32_t id, host_t *ip)
METHOD (eap_radius_provider_t, add_attribute, void, private_eap_radius_provider_t *this, u_int32_t id, configuration_attribute_type_t type, chunk_t data)
METHOD (eap_radius_provider_t, destroy, void, private_eap_radius_provider_t *this)
eap_radius_provider_t * eap_radius_provider_create ()
eap_radius_provider_t * eap_radius_provider_get ()
Variables
static eap_radius_provider_t * singleton = NULL
Typedef Documentation
typedef struct private_eap_radius_provider_t private_eap_radius_provider_t
Definition at line 22 of file eap_radius_provider.c.
typedef struct private_listener_t private_listener_t
Definition at line 23 of file eap_radius_provider.c.
Function Documentation
static void add_addr (private_eap_radius_provider_t * this, hashtable_t * hashtable, uintptr_t id, host_t * host) static
Insert an address entry to a locked claimed/unclaimed hashtable
Definition at line 168 of file eap_radius_provider.c.
References entry_t::addrs, get_or_create_entry(), and linked_list_t::insert_last.
Referenced by METHOD().
 {
     entry_t *entry;
     entry = get_or_create_entry(hashtable, id);
     entry->addrs->insert_last(entry->addrs, host);
 }
static void add_attr (private_eap_radius_provider_t * this, hashtable_t * hashtable, uintptr_t id, attr_t * attr) static
Insert an attribute entry to a locked claimed/unclaimed hashtable
Definition at line 218 of file eap_radius_provider.c.
References entry_t::attrs, get_or_create_entry(), and linked_list_t::insert_last.
Referenced by do_args(), and METHOD().
 {
     entry_t *entry;
     entry = get_or_create_entry(hashtable, id);
     entry->attrs->insert_last(entry->attrs, attr);
 }
static void destroy_attr (attr_t * this) static
Destroy an attr_t
Definition at line 85 of file eap_radius_provider.c.
References data, and free().
Referenced by destroy_entry(), and METHOD().
 {
     free(this->data.ptr);
     free(this);
 }
static void destroy_entry (entry_t * this) static
destroy an entry_t
Definition at line 106 of file eap_radius_provider.c.
References destroy(), destroy_attr(), and free().
Referenced by migrate_entry(), put_or_destroy_entry(), and release_unclaimed().
 {
     this->addrs->destroy_offset(this->addrs, offsetof(host_t, destroy));
     this->attrs->destroy_function(this->attrs, (void*)destroy_attr);
     free(this);
 }
static bool equals (uintptr_t a, uintptr_t b) static
Hashtable equals function
Definition at line 160 of file eap_radius_provider.c.
References b.
Referenced by eap_radius_provider_create().
 {
     return a == b;
 }
static entry_t* get_or_create_entry (hashtable_t * hashtable, uintptr_t id) static
Get or create an entry from a locked hashtable
Definition at line 116 of file eap_radius_provider.c.
References hashtable_t::get, INIT, linked_list_create(), and hashtable_t::put.
Referenced by add_addr(), and add_attr().
 {
     entry_t *entry;
     entry = hashtable->get(hashtable, (void*)id);
     if (!entry)
     {
         INIT(entry,
             .id = id,
             .addrs = linked_list_create(),
             .attrs = linked_list_create(),
         );
         hashtable->put(hashtable, (void*)id, entry);
     }
     return entry;
 }
static u_int hash (uintptr_t id) static
Hashtable hash function
Definition at line 152 of file eap_radius_provider.c.
References id.
Referenced by eap_radius_provider_create().
 {
     return id;
 }
METHOD (listener_t , message_hook , bool , private_listener_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 263 of file eap_radius_provider.c.
References message_t::get_exchange_type, message_t::get_request, ike_sa_t::get_state, ike_sa_t::get_version, IKE_AUTH, IKE_ESTABLISHED, IKEV1, IKEV2, release_unclaimed(), TRANSACTION, and TRUE.
 {
     if (plain && ike_sa->get_state(ike_sa) == IKE_ESTABLISHED &&
         !incoming && !message->get_request(message))
     {
         if ((ike_sa->get_version(ike_sa) == IKEV1 &&
              message->get_exchange_type(message) == TRANSACTION) ||
             (ike_sa->get_version(ike_sa) == IKEV2 &&
              message->get_exchange_type(message) == IKE_AUTH))
         {
             /* if the addresses have not been claimed yet, they won't. Release
              * these resources. */
             release_unclaimed(this, ike_sa);
         }
     }
     return TRUE;
 }
METHOD (listener_t , ike_updown , bool , private_listener_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 283 of file eap_radius_provider.c.
References release_unclaimed(), and TRUE.
 {
     if (!up)
     {
         /* if the message hook does not apply because of a failed exchange
          * or something, make sure we release any resources now */
         release_unclaimed(this, ike_sa);
     }
     return TRUE;
 }
METHOD (listener_t , ike_rekey , bool , private_listener_t * this, ike_sa_t * old, ike_sa_t * new)
Definition at line 314 of file eap_radius_provider.c.
References ike_sa_t::get_unique_id, mutex_t::lock, migrate_entry(), mutex, TRUE, and mutex_t::unlock.
 {
     uintptr_t old_id, new_id;
     old_id = old->get_unique_id(old);
     new_id = new->get_unique_id(new);
     this->mutex->lock(this->mutex);
     migrate_entry(this->unclaimed, old_id, new_id);
     migrate_entry(this->claimed, old_id, new_id);
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
METHOD (attribute_provider_t , acquire_address , host_t * , private_eap_radius_provider_t * this, linked_list_t * pools, ike_sa_t * ike_sa, host_t * requested)
Definition at line 332 of file eap_radius_provider.c.
References add_addr(), addr, host_t::clone, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, ike_sa_t::get_unique_id, listener, name, remove_addr(), sa, and streq().
 {
     enumerator_t *enumerator;
     host_t *addr = NULL;
     uintptr_t sa;
     char *name;
     sa = ike_sa->get_unique_id(ike_sa);
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &name))
     {
         if (streq(name, "radius"))
         {
             this->listener.mutex->lock(this->listener.mutex);
             addr = remove_addr(this, this->listener.unclaimed, sa, requested);
             if (addr)
             {
                 add_addr(this, this->listener.claimed, sa, addr->clone(addr));
             }
             this->listener.mutex->unlock(this->listener.mutex);
             break;
         }
     }
     enumerator->destroy(enumerator);
     return addr;
 }
METHOD (attribute_provider_t , release_address , bool , private_eap_radius_provider_t * this, linked_list_t * pools, host_t * address, ike_sa_t * ike_sa)
Definition at line 363 of file eap_radius_provider.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, host_t::destroy, enumerator_t::enumerate, FALSE, found, ike_sa_t::get_unique_id, listener, name, remove_addr(), sa, streq(), and TRUE.
 {
     enumerator_t *enumerator;
     host_t *found = NULL;
     uintptr_t sa;
     char *name;
     sa = ike_sa->get_unique_id(ike_sa);
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &name))
     {
         if (streq(name, "radius"))
         {
             this->listener.mutex->lock(this->listener.mutex);
             found = remove_addr(this, this->listener.claimed, sa, address);
             this->listener.mutex->unlock(this->listener.mutex);
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (found)
     {
         found->destroy(found);
         return TRUE;
     }
     return FALSE;
 }
METHOD (enumerator_t , attribute_enumerate , bool , attribute_enumerator_t * this, configuration_attribute_type_t * type, chunk_t * data)
Definition at line 408 of file eap_radius_provider.c.
References destroy_attr(), FALSE, list, linked_list_t::remove_first, SUCCESS, and TRUE.
 {
     if (this->current)
     {
         destroy_attr(this->current);
         this->current = NULL;
     }
     if (this->list->remove_first(this->list, (void**)&this->current) == SUCCESS)
     {
         *type = this->current->type;
         *data = this->current->data;
         return TRUE;
     }
     return FALSE;
 }
METHOD (enumerator_t , attribute_destroy , void , attribute_enumerator_t * this)
Definition at line 426 of file eap_radius_provider.c.
References destroy_attr(), linked_list_t::destroy_function, free(), and list.
 {
     if (this->current)
     {
         destroy_attr(this->current);
     }
     this->list->destroy_function(this->list, (void*)destroy_attr);
     free(this);
 }
METHOD (attribute_provider_t , create_attribute_enumerator , enumerator_t * , private_eap_radius_provider_t * this, linked_list_t * pools, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 437 of file eap_radius_provider.c.
References destroy(), ike_sa_t::get_unique_id, INIT, linked_list_t::insert_last, linked_list_create(), list, attribute_enumerator_t::list, listener, attribute_enumerator_t::public, remove_attr(), sa, and TRUE.
 {
     attribute_enumerator_t *enumerator;
     attr_t *attr;
     uintptr_t sa;
     sa = ike_sa->get_unique_id(ike_sa);
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_attribute_enumerate,
             .destroy = _attribute_destroy,
         },
         .list = linked_list_create(),
     );
     /* we forward attributes regardless of pool configurations */
     this->listener.mutex->lock(this->listener.mutex);
     while (TRUE)
     {
         attr = remove_attr(this, this->listener.unclaimed, sa);
         if (!attr)
         {
             break;
         }
         enumerator->list->insert_last(enumerator->list, attr);
     }
     this->listener.mutex->unlock(this->listener.mutex);
     return &enumerator->public;
 }
METHOD (eap_radius_provider_t , add_framed_ip , void , private_eap_radius_provider_t * this, u_int32_t id, host_t * ip)
Definition at line 471 of file eap_radius_provider.c.
References add_addr(), and listener.
 {
     this->listener.mutex->lock(this->listener.mutex);
     add_addr(this, this->listener.unclaimed, id, ip);
     this->listener.mutex->unlock(this->listener.mutex);
 }
METHOD (eap_radius_provider_t , add_attribute , void , private_eap_radius_provider_t * this, u_int32_t id, configuration_attribute_type_t type, chunk_t data)
Definition at line 479 of file eap_radius_provider.c.
References add_attr(), chunk_clone, INIT, and listener.
 {
     attr_t *attr;
     INIT(attr,
         .type = type,
         .data = chunk_clone(data),
     );
     this->listener.mutex->lock(this->listener.mutex);
     add_attr(this, this->listener.unclaimed, id, attr);
     this->listener.mutex->unlock(this->listener.mutex);
 }
METHOD (eap_radius_provider_t , destroy , void , private_eap_radius_provider_t * this)
Definition at line 494 of file eap_radius_provider.c.
References daemon_t::bus, charon, tkm_listener_t::destroy, free(), listener, and bus_t::remove_listener.
 {
     singleton = NULL;
     charon->bus->remove_listener(charon->bus, &this->listener.public);
     this->listener.mutex->destroy(this->listener.mutex);
     this->listener.claimed->destroy(this->listener.claimed);
     this->listener.unclaimed->destroy(this->listener.unclaimed);
     free(this);
 }
static void migrate_entry (hashtable_t * table, uintptr_t old, uintptr_t new) static
Migrate an entry in hashtable from old to new id
Definition at line 298 of file eap_radius_provider.c.
References destroy_entry(), entry_t::id, hashtable_t::put, and hashtable_t::remove.
Referenced by METHOD().
 {
     entry_t *entry;
     entry = table->remove(table, (void*)old);
     if (entry)
     {
         entry->id = new;
         entry = table->put(table, (void*)new, entry);
         if (entry)
         {   /* shouldn't happen */
             destroy_entry(entry);
         }
     }
 }
static void put_or_destroy_entry (hashtable_t * hashtable, entry_t * entry) static
Put an entry to hashtable, or destroy it ife empty
Definition at line 136 of file eap_radius_provider.c.
References entry_t::addrs, entry_t::attrs, destroy_entry(), linked_list_t::get_count, entry_t::id, and hashtable_t::put.
Referenced by remove_addr(), and remove_attr().
 {
     if (entry->addrs->get_count(entry->addrs) > 0 ||
         entry->attrs->get_count(entry->attrs) > 0)
     {
         hashtable->put(hashtable, (void*)entry->id, entry);
     }
     else
     {
         destroy_entry(entry);
     }
 }
static void release_unclaimed (private_listener_t * this, ike_sa_t * ike_sa) static
Clean up unclaimed leases assigned for an IKE_SA
Definition at line 248 of file eap_radius_provider.c.
References destroy_entry(), ike_sa_t::get_unique_id, id, mutex_t::lock, mutex, and mutex_t::unlock.
Referenced by METHOD().
 {
     uintptr_t id;
     entry_t *entry;
     id = ike_sa->get_unique_id(ike_sa);
     this->mutex->lock(this->mutex);
     entry = this->unclaimed->remove(this->unclaimed, (void*)id);
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         destroy_entry(entry);
     }
 }
static host_t* remove_addr (private_eap_radius_provider_t * this, hashtable_t * hashtable, uintptr_t id, host_t * addr) static
Remove the next address from the locked hashtable stored for given id
Definition at line 180 of file eap_radius_provider.c.
References entry_t::addrs, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, host_t::get_family, host_t::ip_equals, put_or_destroy_entry(), linked_list_t::remove, hashtable_t::remove, and linked_list_t::remove_at.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     host_t *found = NULL, *current;
     entry = hashtable->remove(hashtable, (void*)id);
     if (entry)
     {
         enumerator = entry->addrs->create_enumerator(entry->addrs);
         while (enumerator->enumerate(enumerator, &current))
         {
             if (addr->ip_equals(addr, current))
             {   /* prefer an exact match */
                 entry->addrs->remove_at(entry->addrs, enumerator);
                 enumerator->destroy(enumerator);
                 put_or_destroy_entry(hashtable, entry);
                 return current;
             }
             if (!found && addr->get_family(addr) == current->get_family(current))
             {   /* fallback to the first IP with a matching address family */
                 found = current;
             }
         }
         enumerator->destroy(enumerator);
         if (found)
         {
             entry->addrs->remove(entry->addrs, found, NULL);
         }
         put_or_destroy_entry(hashtable, entry);
     }
     return found;
 }
static attr_t* remove_attr (private_eap_radius_provider_t * this, hashtable_t * hashtable, uintptr_t id) static
Remove the next attribute from the locked hashtable stored for given id
Definition at line 230 of file eap_radius_provider.c.
References entry_t::attrs, put_or_destroy_entry(), hashtable_t::remove, and linked_list_t::remove_first.
Referenced by METHOD().
 {
     entry_t *entry;
     attr_t *attr = NULL;
     entry = hashtable->remove(hashtable, (void*)id);
     if (entry)
     {
         entry->attrs->remove_first(entry->attrs, (void**)&attr);
         put_or_destroy_entry(hashtable, entry);
     }
     return attr;
 }
Variable Documentation
eap_radius_provider_t* singleton = NULL static
Singleton instance of provider
Definition at line 70 of file eap_radius_provider.c.
Referenced by eap_radius_provider_create(), and eap_radius_provider_get().