strongSwan: tnccs_manager_t Struct Reference
tnccs_manager_t Struct Reference
tnccs_manager
#include "tnccs_manager.h"
Public Attributes
void(* add_method)(tnccs_manager_t *this, tnccs_type_t type, tnccs_constructor_t constructor)
void(* remove_method)(tnccs_manager_t *this, tnccs_constructor_t constructor)
tnccs_t *(* create_instance)(tnccs_manager_t *this, tnccs_type_t type, bool is_server, identification_t *server_id, identification_t *peer_id, host_t *server_ip, host_t *peer_ip, tnc_ift_type_t transport, tnccs_cb_t cb)
TNC_ConnectionID(* create_connection)(tnccs_manager_t *this, tnccs_type_t type, tnccs_t *tnccs, tnccs_send_message_t send_message, bool *request_handshake_retry, u_int32_t max_msg_len, recommendations_t **recs)
void(* remove_connection)(tnccs_manager_t *this, TNC_ConnectionID id, bool is_server)
TNC_Result(* request_handshake_retry)(tnccs_manager_t *this, bool is_imc, TNC_UInt32 imcv_id, TNC_ConnectionID id, TNC_RetryReason reason)
TNC_Result(* send_message)(tnccs_manager_t *this, TNC_IMCID imc_id, TNC_IMVID imv_id, TNC_ConnectionID id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
TNC_Result(* provide_recommendation)(tnccs_manager_t *this, TNC_IMVID imv_id, TNC_ConnectionID id, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
TNC_Result(* get_attribute)(tnccs_manager_t *this, bool is_imc, TNC_UInt32 imcv_id, TNC_ConnectionID id, TNC_AttributeID attribute_id, TNC_UInt32 buffer_len, TNC_BufferReference buffer, TNC_UInt32 *value_len)
TNC_Result(* set_attribute)(tnccs_manager_t *this, bool is_imc, TNC_UInt32 imcv_id, TNC_ConnectionID id, TNC_AttributeID attribute_id, TNC_UInt32 buffer_len, TNC_BufferReference buffer)
void(* destroy)(tnccs_manager_t *this)
Detailed Description
The TNCCS manager manages all TNCCS implementations and creates instances.
A plugin registers its implemented TNCCS protocol with the manager by providing type and a constructor function. The manager then creates TNCCS protocol instances via the provided constructor.
Definition at line 36 of file tnccs_manager.h.
Member Data Documentation
void(* tnccs_manager_t::add_method)(tnccs_manager_t *this, tnccs_type_t type, tnccs_constructor_t constructor)
Register a TNCCS protocol implementation.
Parameters
type TNCCS protocol type
constructor constructor, returns a TNCCS protocol implementation
Definition at line 44 of file tnccs_manager.h.
Referenced by tnccs_method_register().
TNC_ConnectionID(* tnccs_manager_t::create_connection)(tnccs_manager_t *this, tnccs_type_t type, tnccs_t *tnccs, tnccs_send_message_t send_message, bool *request_handshake_retry, u_int32_t max_msg_len, recommendations_t **recs)
Create a TNCCS connection and assign a unique connection ID as well a callback function for adding a message to a TNCCS batch and create an empty set for collecting IMV recommendations
Parameters
type TNCCS protocol type
tnccs TNCCS connection instance
send_message TNCCS callback function
request_handshake_retry pointer to boolean variable
max_msg_len maximum PA-TNC message size
recs pointer to IMV recommendation set
Returns
assigned connection ID
Definition at line 86 of file tnccs_manager.h.
Referenced by METHOD(), tnccs_20_client_create(), and tnccs_20_server_create().
tnccs_t*(* tnccs_manager_t::create_instance)(tnccs_manager_t *this, tnccs_type_t type, bool is_server, identification_t *server_id, identification_t *peer_id, host_t *server_ip, host_t *peer_ip, tnc_ift_type_t transport, tnccs_cb_t cb)
Create a new TNCCS protocol instance.
Parameters
type type of the TNCCS protocol
is_server TRUE if TNC Server, FALSE if TNC Client
server_id Server identity
peer_id Client identity
server_ip Server IP address
peer_ip Client IP address
transport Underlying TNC IF-T transport protocol used
cb Callback function if TNC Server, NULL if TNC Client
Returns
TNCCS protocol instance, NULL if no constructor found
Definition at line 67 of file tnccs_manager.h.
Referenced by client(), eap_tnc_create(), METHOD(), and pt_tls_receive().
void(* tnccs_manager_t::destroy)(tnccs_manager_t *this)
Destroy a tnccs_manager instance.
Definition at line 197 of file tnccs_manager.h.
Referenced by tnc_manager_register().
TNC_Result(* tnccs_manager_t::get_attribute)(tnccs_manager_t *this, bool is_imc, TNC_UInt32 imcv_id, TNC_ConnectionID id, TNC_AttributeID attribute_id, TNC_UInt32 buffer_len, TNC_BufferReference buffer, TNC_UInt32 *value_len)
Get the value of an attribute associated with a connection or with the TNCS as a whole.
Parameters
is_imc TRUE if IMC, FALSE if IMV
imcv_id ID of the IMC/IMV requesting the attribute
id ID of target connection
attribute_id ID of the requested attribute
buffer_len length of the buffer in bytes
buffer pointer to the buffer
value_len actual length of the returned attribute
Returns
return code
Definition at line 167 of file tnccs_manager.h.
Referenced by TNC_TNCC_GetAttribute(), and TNC_TNCS_GetAttribute().
TNC_Result(* tnccs_manager_t::provide_recommendation)(tnccs_manager_t *this, TNC_IMVID imv_id, TNC_ConnectionID id, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Deliver an IMV Action Recommendation and IMV Evaluation Result to the TNCS
Parameters
imv_id ID of the IMV providing the recommendation
id ID of target connection
rec action recommendation
eval evaluation result
Returns
return code
Definition at line 148 of file tnccs_manager.h.
Referenced by TNC_TNCS_ProvideRecommendation().
void(* tnccs_manager_t::remove_connection)(tnccs_manager_t *this, TNC_ConnectionID id, bool is_server)
Remove a TNCCS connection using its connection ID.
Parameters
id ID of the connection to be removed
is_server TNC Server if TRUE, TNC Client if FALSE
Definition at line 99 of file tnccs_manager.h.
Referenced by METHOD().
void(* tnccs_manager_t::remove_method)(tnccs_manager_t *this, tnccs_constructor_t constructor)
Unregister a TNCCS protocol implementation using it's constructor.
Parameters
constructor constructor function to remove, as added in add_method
Definition at line 52 of file tnccs_manager.h.
Referenced by tnccs_method_register().
TNC_Result(* tnccs_manager_t::request_handshake_retry)(tnccs_manager_t *this, bool is_imc, TNC_UInt32 imcv_id, TNC_ConnectionID id, TNC_RetryReason reason)
Request a handshake retry
Parameters
is_imc TRUE if IMC, FALSE if IMV
imcv_id ID of IMC or IMV requesting the retry
id ID of a specific connection or any connection
reason reason for the handshake retry
Returns
return code
Definition at line 111 of file tnccs_manager.h.
Referenced by TNC_TNCC_RequestHandshakeRetry(), and TNC_TNCS_RequestHandshakeRetry().
TNC_Result(* tnccs_manager_t::send_message)(tnccs_manager_t *this, TNC_IMCID imc_id, TNC_IMVID imv_id, TNC_ConnectionID id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
Add an IMC/IMV message to the batch of a given connection ID.
Parameters
imc_id ID of IMC or TNC_IMCID_ANY
imv_id ID of IMV or TNC_IMVID_ANY
id ID of target connection
msg_flags message flags
msg message to be added
msg_len message length
msg_vid message vendor ID
msg_subtype message subtype
Returns
return code
Definition at line 129 of file tnccs_manager.h.
Referenced by TNC_TNCC_SendMessage(), TNC_TNCC_SendMessageLong(), TNC_TNCS_SendMessage(), and TNC_TNCS_SendMessageLong().
TNC_Result(* tnccs_manager_t::set_attribute)(tnccs_manager_t *this, bool is_imc, TNC_UInt32 imcv_id, TNC_ConnectionID id, TNC_AttributeID attribute_id, TNC_UInt32 buffer_len, TNC_BufferReference buffer)
Set the value of an attribute associated with a connection or with the TNCS as a whole.
Parameters
is_imc TRUE if IMC, FALSE if IMV
imcv_id ID of the IMC/IMV setting the attribute
id ID of target connection
attribute_id ID of the attribute to be set
buffer_len length of the buffer in bytes
buffer pointer to the buffer
Returns
return code
Definition at line 187 of file tnccs_manager.h.
Referenced by TNC_TNCC_SetAttribute(), and TNC_TNCS_SetAttribute().
The documentation for this struct was generated from the following file:
tnccs_manager.h