strongSwan: ipsec_event_relay_t Struct Reference
ipsec_event_relay_t Struct Reference
ipsec_event_relay
#include "ipsec_event_relay.h"
Public Attributes
void(* expire)(ipsec_event_relay_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, bool hard)
void(* register_listener)(ipsec_event_relay_t *this, ipsec_event_listener_t *listener)
void(* unregister_listener)(ipsec_event_relay_t *this, ipsec_event_listener_t *listener)
void(* destroy)(ipsec_event_relay_t *this)
Detailed Description
Event relay manager.
Used to notify upper layers about changes
Definition at line 36 of file ipsec_event_relay.h.
Member Data Documentation
void(* ipsec_event_relay_t::destroy)(ipsec_event_relay_t *this)
Destroy an ipsec_event_relay_t
Definition at line 68 of file ipsec_event_relay.h.
void(* ipsec_event_relay_t::expire)(ipsec_event_relay_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, bool hard)
Raise an expire event.
Parameters
protocol protocol (e.g ESP) of the expired SA
spi SPI of the expired SA
dst destination address of expired SA
hard TRUE for a hard expire, FALSE otherwise
Definition at line 46 of file ipsec_event_relay.h.
Referenced by METHOD().
void(* ipsec_event_relay_t::register_listener)(ipsec_event_relay_t *this, ipsec_event_listener_t *listener)
Register a listener to events raised by this manager
Parameters
listener the listener to register
Definition at line 54 of file ipsec_event_relay.h.
Referenced by kernel_libipsec_ipsec_create().
void(* ipsec_event_relay_t::unregister_listener)(ipsec_event_relay_t *this, ipsec_event_listener_t *listener)
Unregister a listener
Parameters
listener the listener to unregister
Definition at line 62 of file ipsec_event_relay.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ipsec_event_relay.h