strongSwan: mem_cred.c File Reference
mem_cred.c File Reference
#include "mem_cred.h"
#include <threading/rwlock.h>
#include <collections/linked_list.h>
Classes
struct private_mem_cred_t
struct cert_data_t
struct key_data_t
struct shared_entry_t
struct shared_data_t
struct cdp_t
struct cdp_data_t
Typedefs
typedef struct private_mem_cred_t private_mem_cred_t
Functions
static void cert_data_destroy (cert_data_t *data)
static bool certs_filter (cert_data_t *data, certificate_t **in, certificate_t **out)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_mem_cred_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
static bool certificate_equals (certificate_t *item, certificate_t *cert)
static certificate_t * add_cert_internal (private_mem_cred_t *this, bool trusted, certificate_t *cert)
METHOD (mem_cred_t, add_cert, void, private_mem_cred_t *this, bool trusted, certificate_t *cert)
METHOD (mem_cred_t, add_cert_ref, certificate_t *, private_mem_cred_t *this, bool trusted, certificate_t *cert)
METHOD (mem_cred_t, get_cert_ref, certificate_t *, private_mem_cred_t *this, certificate_t *cert)
METHOD (mem_cred_t, add_crl, bool, private_mem_cred_t *this, crl_t *crl)
static void key_data_destroy (key_data_t *data)
static bool key_filter (key_data_t *data, private_key_t **in, private_key_t **out)
METHOD (credential_set_t, create_private_enumerator, enumerator_t *, private_mem_cred_t *this, key_type_t type, identification_t *id)
METHOD (mem_cred_t, add_key, void, private_mem_cred_t *this, private_key_t *key)
static void shared_entry_destroy (shared_entry_t *entry)
static bool shared_entry_equals (shared_entry_t *a, shared_entry_t *b)
static void shared_data_destroy (shared_data_t *data)
static id_match_t has_owner (shared_entry_t *entry, identification_t *owner)
static bool shared_filter (shared_data_t *data, shared_entry_t **in, shared_key_t **out, void **unused1, id_match_t *me, void **unused2, id_match_t *other)
METHOD (credential_set_t, create_shared_enumerator, enumerator_t *, private_mem_cred_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
METHOD (mem_cred_t, add_shared_list, void, private_mem_cred_t *this, shared_key_t *shared, linked_list_t *owners)
METHOD (mem_cred_t, add_shared, void, private_mem_cred_t *this, shared_key_t *shared,...)
static void cdp_destroy (cdp_t *this)
METHOD (mem_cred_t, add_cdp, void, private_mem_cred_t *this, certificate_type_t type, identification_t *id, char *uri)
static void cdp_data_destroy (cdp_data_t *data)
static bool cdp_filter (cdp_data_t *data, cdp_t **cdp, char **uri)
METHOD (credential_set_t, create_cdp_enumerator, enumerator_t *, private_mem_cred_t *this, certificate_type_t type, identification_t *id)
static void reset_certs (private_mem_cred_t *this)
static void copy_certs (linked_list_t *dst, linked_list_t *src, bool clone)
METHOD (mem_cred_t, replace_certs, void, private_mem_cred_t *this, mem_cred_t *other_set, bool clone)
static void reset_secrets (private_mem_cred_t *this)
METHOD (mem_cred_t, replace_secrets, void, private_mem_cred_t *this, mem_cred_t *other_set, bool clone)
METHOD (mem_cred_t, clear_secrets, void, private_mem_cred_t *this)
METHOD (mem_cred_t, clear_, void, private_mem_cred_t *this)
METHOD (mem_cred_t, destroy, void, private_mem_cred_t *this)
mem_cred_t * mem_cred_create ()
Typedef Documentation
typedef struct private_mem_cred_t private_mem_cred_t
Definition at line 23 of file mem_cred.c.
Function Documentation
static certificate_t* add_cert_internal (private_mem_cred_t * this, bool trusted, certificate_t * cert) static
Add a certificate the the cache. Returns a reference to "cert" or a previously cached certificate that equals "cert".
Definition at line 158 of file mem_cred.c.
References cert, certificate_equals(), certificate_t::destroy, certificate_t::get_ref, lock, SUCCESS, and spinlock_t::unlock.
Referenced by METHOD().
 {
     certificate_t *cached;
     this->lock->write_lock(this->lock);
     if (this->untrusted->find_first(this->untrusted,
                                     (linked_list_match_t)certificate_equals,
                                     (void**)&cached, cert) == SUCCESS)
     {
         cert->destroy(cert);
         cert = cached->get_ref(cached);
     }
     else
     {
         if (trusted)
         {
             this->trusted->insert_first(this->trusted, cert->get_ref(cert));
         }
         this->untrusted->insert_first(this->untrusted, cert->get_ref(cert));
     }
     this->lock->unlock(this->lock);
     return cert;
 }
static void cdp_data_destroy (cdp_data_t * data) static
Clean up CDP enumerator data
Definition at line 607 of file mem_cred.c.
References free(), cdp_data_t::lock, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->lock->unlock(data->lock);
     free(data);
 }
static void cdp_destroy (cdp_t * this) static
Destroy a CDP entry
Definition at line 572 of file mem_cred.c.
References free(), and uri.
Referenced by METHOD().
 {
     this->id->destroy(this->id);
     free(this->uri);
     free(this);
 }
static bool cdp_filter (cdp_data_t * data, cdp_t ** cdp, char ** uri) static
CDP enumerator filter
Definition at line 616 of file mem_cred.c.
References CERT_ANY, FALSE, cdp_data_t::id, identification_t::matches, TRUE, and cdp_data_t::type.
Referenced by METHOD().
 {
     if (data->type != CERT_ANY && data->type != (*cdp)->type)
     {
         return FALSE;
     }
     if (data->id && !(*cdp)->id->matches((*cdp)->id, data->id))
     {
         return FALSE;
     }
     *uri = (*cdp)->uri;
     return TRUE;
 }
static void cert_data_destroy (cert_data_t * data) static
destroy cert_data
Definition at line 79 of file mem_cred.c.
References free(), cert_data_t::lock, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->lock->unlock(data->lock);
     free(data);
 }
static bool certificate_equals (certificate_t * item, certificate_t * cert) static
Definition at line 149 of file mem_cred.c.
References certificate_t::equals.
Referenced by add_cert_internal(), and METHOD().
 {
     return item->equals(item, cert);
 }
static bool certs_filter (cert_data_t * data, certificate_t ** in, certificate_t ** out) static
filter function for certs enumerator
Definition at line 88 of file mem_cred.c.
References cert, cert_data_t::cert, CERT_ANY, public_key_t::destroy, FALSE, identification_t::get_encoding, certificate_t::get_public_key, certificate_t::get_type, certificate_t::has_subject, cert_data_t::id, in, cert_data_t::key, KEY_ANY, public, and TRUE.
Referenced by METHOD().
 {
     public_key_t *public;
     certificate_t *cert = *in;
     if (data->cert == CERT_ANY || data->cert == cert->get_type(cert))
     {
         public = cert->get_public_key(cert);
         if (public)
         {
             if (data->key == KEY_ANY || data->key == public->get_type(public))
             {
                 if (data->id && public->has_fingerprint(public,
                                             data->id->get_encoding(data->id)))
                 {
                     public->destroy(public);
                     *out = *in;
                     return TRUE;
                 }
             }
             public->destroy(public);
         }
         else if (data->key != KEY_ANY)
         {
             return FALSE;
         }
         if (data->id == NULL || cert->has_subject(cert, data->id))
         {
             *out = *in;
             return TRUE;
         }
     }
     return FALSE;
 }
static void copy_certs (linked_list_t * dst, linked_list_t * src, bool clone) static
Definition at line 656 of file mem_cred.c.
References cert, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, certificate_t::get_ref, linked_list_t::insert_last, and linked_list_t::remove_at.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     enumerator = src->create_enumerator(src);
     while (enumerator->enumerate(enumerator, &cert))
     {
         if (clone)
         {
             cert = cert->get_ref(cert);
         }
         else
         {
             src->remove_at(src, enumerator);
         }
         dst->insert_last(dst, cert);
     }
     enumerator->destroy(enumerator);
 }
static id_match_t has_owner (shared_entry_t * entry, identification_t * owner) static
Get the best match of an owner in an entry.
Definition at line 431 of file mem_cred.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, ID_MATCH_NONE, match(), identification_t::matches, and shared_entry_t::owners.
Referenced by shared_filter().
 {
     enumerator_t *enumerator;
     id_match_t match, best = ID_MATCH_NONE;
     identification_t *current;
     enumerator = entry->owners->create_enumerator(entry->owners);
     while (enumerator->enumerate(enumerator, &current))
     {
         match  = owner->matches(owner, current);
         if (match > best)
         {
             best = match;
         }
     }
     enumerator->destroy(enumerator);
     return best;
 }
static void key_data_destroy (key_data_t * data) static
Destroy key enumerator data
Definition at line 284 of file mem_cred.c.
References free(), key_data_t::lock, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->lock->unlock(data->lock);
     free(data);
 }
static bool key_filter (key_data_t * data, private_key_t ** in, private_key_t ** out) static
filter function for private key enumerator
Definition at line 293 of file mem_cred.c.
References FALSE, identification_t::get_encoding, private_key_t::get_type, private_key_t::has_fingerprint, key_data_t::id, in, key, KEY_ANY, TRUE, and key_data_t::type.
Referenced by METHOD().
 {
     private_key_t *key;
     key = *in;
     if (data->type == KEY_ANY || data->type == key->get_type(key))
     {
         if (data->id == NULL ||
             key->has_fingerprint(key, data->id->get_encoding(data->id)))
         {
             *out = key;
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_mem_cred_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 123 of file mem_cred.c.
References cert_data_destroy(), certs_filter(), data, enumerator_create_filter(), INIT, and lock.
 {
     cert_data_t *data;
     enumerator_t *enumerator;
     INIT(data,
         .lock = this->lock,
         .cert = cert,
         .key = key,
         .id = id,
     );
     this->lock->read_lock(this->lock);
     if (trusted)
     {
         enumerator = this->trusted->create_enumerator(this->trusted);
     }
     else
     {
         enumerator = this->untrusted->create_enumerator(this->untrusted);
     }
     return enumerator_create_filter(enumerator, (void*)certs_filter, data,
                                     (void*)cert_data_destroy);
 }
METHOD (mem_cred_t , add_cert , void , private_mem_cred_t * this, bool trusted, certificate_t * cert)
Definition at line 182 of file mem_cred.c.
References add_cert_internal(), and certificate_t::destroy.
 {
     certificate_t *cached = add_cert_internal(this, trusted, cert);
     cached->destroy(cached);
 }
METHOD (mem_cred_t , add_cert_ref , certificate_t * , private_mem_cred_t * this, bool trusted, certificate_t * cert)
Definition at line 189 of file mem_cred.c.
References add_cert_internal().
 {
     return add_cert_internal(this, trusted, cert);
 }
METHOD (mem_cred_t , get_cert_ref , certificate_t * , private_mem_cred_t * this, certificate_t * cert)
Definition at line 195 of file mem_cred.c.
References cert, certificate_equals(), certificate_t::destroy, certificate_t::get_ref, lock, SUCCESS, and spinlock_t::unlock.
 {
     certificate_t *cached;
     this->lock->read_lock(this->lock);
     if (this->untrusted->find_first(this->untrusted,
                                     (linked_list_match_t)certificate_equals,
                                     (void**)&cached, cert) == SUCCESS)
     {
         cert->destroy(cert);
         cert = cached->get_ref(cached);
     }
     this->lock->unlock(this->lock);
     return cert;
 }
METHOD (mem_cred_t , add_crl , bool , private_mem_cred_t * this, crl_t * crl)
Definition at line 213 of file mem_cred.c.
References cert, CERT_X509_CRL, crl_t::certificate, chunk_equals(), crl_is_newer(), enumerator_t::destroy, certificate_t::destroy, enumerator_t::enumerate, identification_t::equals, FALSE, found, crl_t::get_authKeyIdentifier, certificate_t::get_issuer, certificate_t::get_type, lock, TRUE, and spinlock_t::unlock.
 {
     certificate_t *current, *cert = &crl->certificate;
     enumerator_t *enumerator;
     bool new = TRUE;
     this->lock->write_lock(this->lock);
     enumerator = this->untrusted->create_enumerator(this->untrusted);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current->get_type(current) == CERT_X509_CRL)
         {
             bool found = FALSE;
             crl_t *crl_c = (crl_t*)current;
             chunk_t authkey = crl->get_authKeyIdentifier(crl);
             chunk_t authkey_c = crl_c->get_authKeyIdentifier(crl_c);
             /* compare authorityKeyIdentifiers if available */
             if (chunk_equals(authkey, authkey_c))
             {
                 found = TRUE;
             }
             else
             {
                 identification_t *issuer = cert->get_issuer(cert);
                 identification_t *issuer_c = current->get_issuer(current);
                 /* otherwise compare issuer distinguished names */
                 if (issuer->equals(issuer, issuer_c))
                 {
                     found = TRUE;
                 }
             }
             if (found)
             {
                 new = crl_is_newer(crl, crl_c);
                 if (new)
                 {
                     this->untrusted->remove_at(this->untrusted, enumerator);
                 }
                 else
                 {
                     cert->destroy(cert);
                 }
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     if (new)
     {
         this->untrusted->insert_first(this->untrusted, cert);
     }
     this->lock->unlock(this->lock);
     return new;
 }
METHOD (credential_set_t , create_private_enumerator , enumerator_t * , private_mem_cred_t * this, key_type_t type, identification_t * id)
Definition at line 310 of file mem_cred.c.
References data, enumerator_create_filter(), INIT, key_data_destroy(), key_filter(), keys, and lock.
 {
     key_data_t *data;
     INIT(data,
         .lock = this->lock,
         .type = type,
         .id = id,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(this->keys->create_enumerator(this->keys),
                             (void*)key_filter, data, (void*)key_data_destroy);
 }
METHOD (mem_cred_t , add_key , void , private_mem_cred_t * this, private_key_t * key)
Definition at line 325 of file mem_cred.c.
References enumerator_t::destroy, private_key_t::destroy, enumerator_t::enumerate, private_key_t::equals, keys, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     private_key_t *current;
     this->lock->write_lock(this->lock);
     enumerator = this->keys->create_enumerator(this->keys);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current->equals(current, key))
         {
             this->keys->remove_at(this->keys, enumerator);
             current->destroy(current);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->keys->insert_first(this->keys, key);
     this->lock->unlock(this->lock);
 }
METHOD (credential_set_t , create_shared_enumerator , enumerator_t * , private_mem_cred_t * this, shared_key_type_t type, identification_t * me, identification_t * other)
Definition at line 490 of file mem_cred.c.
References data, enumerator_create_filter(), INIT, lock, shared_data_t::lock, rwlock_t::read_lock, shared_data_destroy(), and shared_filter().
 {
     shared_data_t *data;
     INIT(data,
         .lock = this->lock,
         .me = me,
         .other = other,
         .type = type,
     );
     data->lock->read_lock(data->lock);
     return enumerator_create_filter(
                         this->shared->create_enumerator(this->shared),
                         (void*)shared_filter, data, (void*)shared_data_destroy);
 }
METHOD (mem_cred_t , add_shared_list , void , private_mem_cred_t * this, shared_key_t * shared, linked_list_t * owners)
Definition at line 508 of file mem_cred.c.
References enumerator_t::destroy, enumerator_t::enumerate, INIT, lock, shared_entry_destroy(), shared_entry_equals(), and spinlock_t::unlock.
 {
     shared_entry_t *current, *new;
     enumerator_t *enumerator;
     INIT(new,
         .shared = shared,
         .owners = owners,
     );
     this->lock->write_lock(this->lock);
     enumerator = this->shared->create_enumerator(this->shared);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (shared_entry_equals(current, new))
         {
             this->shared->remove_at(this->shared, enumerator);
             shared_entry_destroy(current);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->shared->insert_first(this->shared, new);
     this->lock->unlock(this->lock);
 }
METHOD (mem_cred_t , add_shared , void , private_mem_cred_t * this, shared_key_t * shared, ...)
Definition at line 538 of file mem_cred.c.
References id, linked_list_t::insert_first, and linked_list_create().
 {
     identification_t *id;
     linked_list_t *owners = linked_list_create();
     va_list args;
     va_start(args, shared);
     do
     {
         id = va_arg(args, identification_t*);
         if (id)
         {
             owners->insert_first(owners, id);
         }
     }
     while (id);
     va_end(args);
     add_shared_list(this, shared, owners);
 }
METHOD (mem_cred_t , add_cdp , void , private_mem_cred_t * this, certificate_type_t type, identification_t * id, char * uri)
Definition at line 579 of file mem_cred.c.
References identification_t::clone, INIT, lock, strdup, and spinlock_t::unlock.
 {
     cdp_t *cdp;
     INIT(cdp,
         .type = type,
         .id = id->clone(id),
         .uri = strdup(uri),
     );
     this->lock->write_lock(this->lock);
     this->cdps->insert_last(this->cdps, cdp);
     this->lock->unlock(this->lock);
 }
METHOD (credential_set_t , create_cdp_enumerator , enumerator_t * , private_mem_cred_t * this, certificate_type_t type, identification_t * id)
Definition at line 630 of file mem_cred.c.
References cdp_data_destroy(), cdp_filter(), data, enumerator_create_filter(), INIT, and lock.
 {
     cdp_data_t *data;
     INIT(data,
         .type = type,
         .id = id,
         .lock = this->lock,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(this->cdps->create_enumerator(this->cdps),
                             (void*)cdp_filter, data, (void*)cdp_data_destroy);
 }
METHOD (mem_cred_t , replace_certs , void , private_mem_cred_t * this, mem_cred_t * other_set, bool clone)
Definition at line 677 of file mem_cred.c.
References copy_certs(), lock, reset_certs(), private_mem_cred_t::trusted, spinlock_t::unlock, and private_mem_cred_t::untrusted.
 {
     private_mem_cred_t *other = (private_mem_cred_t*)other_set;
     this->lock->write_lock(this->lock);
     reset_certs(this);
     copy_certs(this->untrusted, other->untrusted, clone);
     copy_certs(this->trusted, other->trusted, clone);
     this->lock->unlock(this->lock);
 }
METHOD (mem_cred_t , replace_secrets , void , private_mem_cred_t * this, mem_cred_t * other_set, bool clone)
Definition at line 697 of file mem_cred.c.
References linked_list_t::clone_offset, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, shared_key_t::get_ref, private_key_t::get_ref, INIT, key, private_mem_cred_t::keys, keys, lock, shared_entry_t::owners, linked_list_t::remove_first, reset_secrets(), private_mem_cred_t::shared, shared_entry_t::shared, SUCCESS, and spinlock_t::unlock.
 {
     private_mem_cred_t *other = (private_mem_cred_t*)other_set;
     enumerator_t *enumerator;
     shared_entry_t *entry, *new_entry;
     private_key_t *key;
     this->lock->write_lock(this->lock);
     reset_secrets(this);
     if (clone)
     {
         enumerator = other->keys->create_enumerator(other->keys);
         while (enumerator->enumerate(enumerator, &key))
         {
             this->keys->insert_last(this->keys, key->get_ref(key));
         }
         enumerator->destroy(enumerator);
         enumerator = other->shared->create_enumerator(other->shared);
         while (enumerator->enumerate(enumerator, &entry))
         {
             INIT(new_entry,
                 .shared = entry->shared->get_ref(entry->shared),
                 .owners = entry->owners->clone_offset(entry->owners,
                                             offsetof(identification_t, clone)),
             );
             this->shared->insert_last(this->shared, new_entry);
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         while (other->keys->remove_first(other->keys, (void**)&key) == SUCCESS)
         {
             this->keys->insert_last(this->keys, key);
         }
         while (other->shared->remove_first(other->shared,
                                           (void**)&entry) == SUCCESS)
         {
             this->shared->insert_last(this->shared, entry);
         }
     }
     this->lock->unlock(this->lock);
 }
METHOD (mem_cred_t , clear_secrets , void , private_mem_cred_t * this)
Definition at line 744 of file mem_cred.c.
References lock, reset_secrets(), and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     reset_secrets(this);
     this->lock->unlock(this->lock);
 }
METHOD (mem_cred_t , clear_ , void , private_mem_cred_t * this)
Definition at line 752 of file mem_cred.c.
References cdp_destroy(), linked_list_create(), lock, reset_certs(), reset_secrets(), and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->cdps->destroy_function(this->cdps, (void*)cdp_destroy);
     this->cdps = linked_list_create();
     reset_certs(this);
     reset_secrets(this);
     this->lock->unlock(this->lock);
 }
METHOD (mem_cred_t , destroy , void , private_mem_cred_t * this)
Definition at line 763 of file mem_cred.c.
References spinlock_t::destroy, free(), keys, and lock.
 {
     clear_(this);
     this->trusted->destroy(this->trusted);
     this->untrusted->destroy(this->untrusted);
     this->keys->destroy(this->keys);
     this->shared->destroy(this->shared);
     this->cdps->destroy(this->cdps);
     this->lock->destroy(this->lock);
     free(this);
 }
static void reset_certs (private_mem_cred_t * this) static
Definition at line 646 of file mem_cred.c.
References destroy(), and linked_list_create().
Referenced by METHOD().
 {
     this->trusted->destroy_offset(this->trusted,
                                   offsetof(certificate_t, destroy));
     this->untrusted->destroy_offset(this->untrusted,
                                     offsetof(certificate_t, destroy));
     this->trusted = linked_list_create();
     this->untrusted = linked_list_create();
 }
static void reset_secrets (private_mem_cred_t * this) static
Definition at line 689 of file mem_cred.c.
References destroy(), keys, linked_list_create(), and shared_entry_destroy().
Referenced by METHOD().
 {
     this->keys->destroy_offset(this->keys, offsetof(private_key_t, destroy));
     this->shared->destroy_function(this->shared, (void*)shared_entry_destroy);
     this->keys = linked_list_create();
     this->shared = linked_list_create();
 }
static void shared_data_destroy (shared_data_t * data) static
free shared key enumerator data and unlock list
Definition at line 422 of file mem_cred.c.
References free(), shared_data_t::lock, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->lock->unlock(data->lock);
     free(data);
 }
static void shared_entry_destroy (shared_entry_t * entry) static
Clean up a shared entry
Definition at line 363 of file mem_cred.c.
References shared_key_t::destroy, destroy(), linked_list_t::destroy_offset, free(), shared_entry_t::owners, and shared_entry_t::shared.
Referenced by METHOD(), and reset_secrets().
 {
     entry->owners->destroy_offset(entry->owners,
                                   offsetof(identification_t, destroy));
     entry->shared->destroy(entry->shared);
     free(entry);
 }
static bool shared_entry_equals (shared_entry_t * a, shared_entry_t * b) static
Check if two shared key entries equal
Definition at line 374 of file mem_cred.c.
References chunk_equals(), linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, equals(), identification_t::equals, FALSE, linked_list_t::get_count, shared_key_t::get_key, shared_key_t::get_type, shared_entry_t::owners, shared_entry_t::shared, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *e1, *e2;
     identification_t *id1, *id2;
     bool equals = TRUE;
     if (a->shared->get_type(a->shared) != b->shared->get_type(b->shared))
     {
         return FALSE;
     }
     if (!chunk_equals(a->shared->get_key(a->shared),
                       b->shared->get_key(b->shared)))
     {
         return FALSE;
     }
     if (a->owners->get_count(a->owners) != b->owners->get_count(b->owners))
     {
         return FALSE;
     }
     e1 = a->owners->create_enumerator(a->owners);
     e2 = b->owners->create_enumerator(b->owners);
     while (e1->enumerate(e1, &id1) && e2->enumerate(e2, &id2))
     {
         if (!id1->equals(id1, id2))
         {
             equals = FALSE;
             break;
         }
     }
     e1->destroy(e1);
     e2->destroy(e2);
     return equals;
 }
static bool shared_filter (shared_data_t * data, shared_entry_t ** in, shared_key_t ** out, void ** unused1, id_match_t * me, void ** unused2, id_match_t * other) static
enumerator filter function for shared entries
Definition at line 453 of file mem_cred.c.
References FALSE, shared_key_t::get_type, has_owner(), ID_MATCH_NONE, in, shared_data_t::me, shared_data_t::other, shared_entry_t::shared, SHARED_ANY, TRUE, and shared_data_t::type.
Referenced by METHOD().
 {
     id_match_t my_match = ID_MATCH_NONE, other_match = ID_MATCH_NONE;
     shared_entry_t *entry = *in;
     if (data->type != SHARED_ANY &&
         entry->shared->get_type(entry->shared) != data->type)
     {
         return FALSE;
     }
     if (data->me)
     {
         my_match = has_owner(entry, data->me);
     }
     if (data->other)
     {
         other_match = has_owner(entry, data->other);
     }
     if ((data->me || data->other) && (!my_match && !other_match))
     {
         return FALSE;
     }
     *out = entry->shared;
     if (me)
     {
         *me = my_match;
     }
     if (other)
     {
         *other = other_match;
     }
     return TRUE;
 }