strongSwan: ha_cache
ha_cache
ha
Classes
struct ha_cache_t
Typedefs
typedef struct ha_cache_t ha_cache_t
Functions
ha_cache_t * ha_cache_create (ha_kernel_t *kernel, ha_socket_t *socket, ha_tunnel_t *tunnel, bool resync, u_int count)
Detailed Description
Typedef Documentation
typedef struct ha_cache_t ha_cache_t
Definition at line 24 of file ha_cache.h.
Function Documentation
ha_cache_t* ha_cache_create (ha_kernel_t * kernel, ha_socket_t * socket, ha_tunnel_t * tunnel, bool sync, u_int count)
Create a ha_cache instance.
Parameters
kernel kernel helper
socket socket to send resync messages
tunnel HA tunnel
resync request a resync during startup?
count total number of segments
See header
Definition at line 376 of file ha_cache.c.
References callback_job_create_with_prio(), count, hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), INIT, JOB_PRIO_CRITICAL, lib, mutex_create(), MUTEX_TYPE_DEFAULT, request_resync(), scheduler_t::schedule_job, library_t::scheduler, and socket.
Referenced by initialize_plugin().
 {
     private_ha_cache_t *this;
     INIT(this,
         .public = {
             .cache = _cache,
             .delete = _delete_,
             .resync = _resync,
             .destroy = _destroy,
         },
         .count = count,
         .kernel = kernel,
         .socket = socket,
         .tunnel = tunnel,
         .cache = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 8),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     if (sync)
     {
         /* request a resync as soon as we are up */
         lib->scheduler->schedule_job(lib->scheduler, (job_t*)
             callback_job_create_with_prio((callback_job_cb_t)request_resync,
                                     this, NULL, NULL, JOB_PRIO_CRITICAL), 1);
     }
     return &this->public;
 }