strongSwan: diffie_hellman
diffie_hellman
crypto
Classes
struct diffie_hellman_t
struct diffie_hellman_params_t
Typedefs
typedef enum diffie_hellman_group_t diffie_hellman_group_t
typedef struct diffie_hellman_t diffie_hellman_t
typedef struct
diffie_hellman_params_t diffie_hellman_params_t
Enumerations
enum diffie_hellman_group_t {
MODP_NONE = 0, MODP_768_BIT = 1, MODP_1024_BIT = 2, MODP_1536_BIT = 5,
MODP_2048_BIT = 14, MODP_3072_BIT = 15, MODP_4096_BIT = 16, MODP_6144_BIT = 17,
MODP_8192_BIT = 18, ECP_256_BIT = 19, ECP_384_BIT = 20, ECP_521_BIT = 21,
MODP_1024_160 = 22, MODP_2048_224 = 23, MODP_2048_256 = 24, ECP_192_BIT = 25,
ECP_224_BIT = 26, ECP_224_BP = 27, ECP_256_BP = 28, ECP_384_BP = 29,
ECP_512_BP = 30, MODP_NULL = 1024, NTRU_112_BIT = 1030, NTRU_128_BIT = 1031,
NTRU_192_BIT = 1032, NTRU_256_BIT = 1033, MODP_CUSTOM = 65536
}
Functions
void diffie_hellman_init ()
diffie_hellman_params_t * diffie_hellman_get_params (diffie_hellman_group_t group)
bool diffie_hellman_group_is_ec (diffie_hellman_group_t group)
bool diffie_hellman_verify_value (diffie_hellman_group_t group, chunk_t value)
Variables
enum_name_t * diffie_hellman_group_names
Detailed Description
Typedef Documentation
typedef enum diffie_hellman_group_t diffie_hellman_group_t
Definition at line 26 of file diffie_hellman.h.
typedef struct diffie_hellman_params_t diffie_hellman_params_t
Definition at line 28 of file diffie_hellman.h.
typedef struct diffie_hellman_t diffie_hellman_t
Definition at line 27 of file diffie_hellman.h.
Enumeration Type Documentation
enum diffie_hellman_group_t
Diffie-Hellman group.
The modulus (or group) to use for a Diffie-Hellman calculation. See IKEv2 RFC 3.3.2 and RFC 3526.
ECP groups are defined in RFC 4753 and RFC 5114. ECC Brainpool groups are defined in RFC 6954.
Enumerator
MODP_NONE
MODP_768_BIT
MODP_1024_BIT
MODP_1536_BIT
MODP_2048_BIT
MODP_3072_BIT
MODP_4096_BIT
MODP_6144_BIT
MODP_8192_BIT
ECP_256_BIT
ECP_384_BIT
ECP_521_BIT
MODP_1024_160
MODP_2048_224
MODP_2048_256
ECP_192_BIT
ECP_224_BIT
ECP_224_BP
ECP_256_BP
ECP_384_BP
ECP_512_BP
MODP_NULL
insecure NULL diffie hellman group for testing, in PRIVATE USE
NTRU_112_BIT
MODP group with custom generator/prime Parameters defined by IEEE 1363.1, in PRIVATE USE
NTRU_128_BIT
NTRU_192_BIT
NTRU_256_BIT
MODP_CUSTOM
internally used DH group with additional parameters g and p, outside of PRIVATE USE (i.e. IKEv2 DH group range) so it can't be negotiated
Definition at line 41 of file diffie_hellman.h.
{
     MODP_NONE     =  0,
     MODP_768_BIT  =  1,
     MODP_1024_BIT =  2,
     MODP_1536_BIT =  5,
     MODP_2048_BIT = 14,
     MODP_3072_BIT = 15,
     MODP_4096_BIT = 16,
     MODP_6144_BIT = 17,
     MODP_8192_BIT = 18,
     ECP_256_BIT   = 19,
     ECP_384_BIT   = 20,
     ECP_521_BIT   = 21,
     MODP_1024_160 = 22,
     MODP_2048_224 = 23,
     MODP_2048_256 = 24,
     ECP_192_BIT   = 25,
     ECP_224_BIT   = 26,
     ECP_224_BP    = 27,
     ECP_256_BP    = 28,
     ECP_384_BP    = 29,
     ECP_512_BP    = 30,
     MODP_NULL = 1024,
     NTRU_112_BIT = 1030,
     NTRU_128_BIT = 1031,
     NTRU_192_BIT = 1032,
     NTRU_256_BIT = 1033,
     MODP_CUSTOM = 65536,
 };
Function Documentation
diffie_hellman_params_t* diffie_hellman_get_params (diffie_hellman_group_t group)
Get the parameters associated with the specified diffie hellman group.
Before calling this method, use diffie_hellman_init() to initialize the DH group table. This is usually done by library_init().
Parameters
group DH group
Returns
The parameters or NULL, if the group is not supported
Described in header.
Definition at line 456 of file diffie_hellman.c.
References countof, dh_params, settings_t::get_bool, lib, library_t::ns, library_t::settings, and TRUE.
Referenced by diffie_hellman_verify_value(), gcrypt_dh_create(), gmp_diffie_hellman_create(), METHOD(), pkcs11_dh_create(), send_server_key_exchange(), and set_modulus().
 {
     int i;
     for (i = 0; i < countof(dh_params); i++)
     {
         if (dh_params[i].group == group)
         {
             if (!dh_params[i].public.exp_len)
             {
                 if (!dh_params[i].public.subgroup.len &&
                     lib->settings->get_bool(lib->settings,
                                     "%s.dh_exponent_ansi_x9_42", TRUE, lib->ns))
                 {
                     dh_params[i].public.exp_len = dh_params[i].public.prime.len;
                 }
                 else
                 {
                     dh_params[i].public.exp_len = dh_params[i].opt_exp;
                 }
             }
             return &dh_params[i].public;
         }
     }
     return NULL;
 }
bool diffie_hellman_group_is_ec (diffie_hellman_group_t group)
Check if a given DH group is an ECDH group
Parameters
group group to check
Returns
TRUE if group is an ECP group
See header.
Definition at line 486 of file diffie_hellman.c.
References ECP_192_BIT, ECP_224_BIT, ECP_224_BP, ECP_256_BIT, ECP_256_BP, ECP_384_BIT, ECP_384_BP, ECP_512_BP, ECP_521_BIT, FALSE, and TRUE.
Referenced by filter_key_exchange_config_suites(), process_key_exchange(), process_key_exchange_dhe(), and send_server_key_exchange().
 {
     switch (group)
     {
         case ECP_256_BIT:
         case ECP_384_BIT:
         case ECP_521_BIT:
         case ECP_192_BIT:
         case ECP_224_BIT:
         case ECP_224_BP:
         case ECP_256_BP:
         case ECP_384_BP:
         case ECP_512_BP:
             return TRUE;
         default:
             return FALSE;
     }
 }
void diffie_hellman_init ()
Initialize diffie hellman parameters during startup.
See header.
Definition at line 439 of file diffie_hellman.c.
References countof, dh_params, settings_t::get_bool, lib, library_t::ns, library_t::settings, and TRUE.
Referenced by library_init().
 {
     int i;
     if (lib->settings->get_bool(lib->settings,
                     "%s.dh_exponent_ansi_x9_42", TRUE, lib->ns))
     {
         for (i = 0; i < countof(dh_params); i++)
         {
             dh_params[i].public.exp_len = dh_params[i].public.prime.len;
         }
     }
 }
bool diffie_hellman_verify_value (diffie_hellman_group_t group, chunk_t value)
Check if a diffie hellman public value is valid for given group.
Parameters
group group the value is used in
value public DH value to check
Returns
TRUE if value looks valid for group
See header.
Definition at line 508 of file diffie_hellman.c.
References DBG1, DBG_ENC, diffie_hellman_get_params(), diffie_hellman_group_names, ECP_192_BIT, ECP_224_BIT, ECP_224_BP, ECP_256_BIT, ECP_256_BP, ECP_384_BIT, ECP_384_BP, ECP_512_BP, ECP_521_BIT, FALSE, chunk_t::len, MODP_1024_160, MODP_1024_BIT, MODP_1536_BIT, MODP_2048_224, MODP_2048_256, MODP_2048_BIT, MODP_3072_BIT, MODP_4096_BIT, MODP_6144_BIT, MODP_768_BIT, MODP_8192_BIT, MODP_CUSTOM, MODP_NONE, MODP_NULL, NTRU_112_BIT, NTRU_128_BIT, NTRU_192_BIT, NTRU_256_BIT, params, diffie_hellman_params_t::prime, TRUE, and valid.
Referenced by METHOD().
 {
     diffie_hellman_params_t *params;
     bool valid = FALSE;
     switch (group)
     {
         case MODP_768_BIT:
         case MODP_1024_BIT:
         case MODP_1536_BIT:
         case MODP_2048_BIT:
         case MODP_3072_BIT:
         case MODP_4096_BIT:
         case MODP_6144_BIT:
         case MODP_8192_BIT:
         case MODP_1024_160:
         case MODP_2048_224:
         case MODP_2048_256:
             params = diffie_hellman_get_params(group);
             if (params)
             {
                 valid = value.len == params->prime.len;
             }
             break;
         case ECP_192_BIT:
             valid = value.len == 48;
             break;
         case ECP_224_BIT:
         case ECP_224_BP:
             valid = value.len == 56;
             break;
         case ECP_256_BIT:
         case ECP_256_BP:
             valid = value.len == 64;
             break;
         case ECP_384_BIT:
         case ECP_384_BP:
             valid = value.len == 96;
             break;
         case ECP_512_BP:
             valid = value.len == 128;
             break;
         case ECP_521_BIT:
             valid = value.len == 132;
             break;
         case NTRU_112_BIT:
         case NTRU_128_BIT:
         case NTRU_192_BIT:
         case NTRU_256_BIT:
             /* verification currently not supported, do in plugin */
             valid = FALSE;
             break;
         case MODP_NULL:
         case MODP_CUSTOM:
             valid = TRUE;
             break;
         case MODP_NONE:
             /* fail */
             break;
         /* compile-warn unhandled groups, fail verification */
     }
     if (!valid)
     {
         DBG1(DBG_ENC, "invalid DH public value size (%zu bytes) for %N",
              value.len, diffie_hellman_group_names, group);
     }
     return valid;
 }
Variable Documentation
enum_name_t* diffie_hellman_group_names
enum name for diffie_hellman_group_t.
Referenced by diffie_hellman_verify_value(), list_algs(), list_child(), list_ike(), METHOD(), plugin_feature_get_string(), process_ec_key_exchange(), proposal_printf_hook(), pts_dh_group_probe(), run_test(), select_and_install(), send_server_key_exchange(), START_TEST(), and transform_get_enum_names().