strongSwan: receiver.c File Reference
receiver.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include "receiver.h"
#include <hydra.h>
#include <daemon.h>
#include <network/socket.h>
#include <processing/jobs/job.h>
#include <processing/jobs/process_message_job.h>
#include <processing/jobs/callback_job.h>
#include <crypto/hashers/hasher.h>
#include <threading/mutex.h>
#include <networking/packet.h>
Classes
struct private_receiver_t
Macros
#define COOKIE_LIFETIME 10
#define COOKIE_CALMDOWN_DELAY 10
#define COOKIE_REUSE 10000
#define COOKIE_THRESHOLD_DEFAULT 10
#define BLOCK_THRESHOLD_DEFAULT 5
#define SECRET_LENGTH 16
#define NOTIFY_PAYLOAD_HEADER_LENGTH 8
Typedefs
typedef struct private_receiver_t private_receiver_t
Functions
static void send_notify (message_t *request, int major, exchange_type_t exchange, notify_type_t type, chunk_t data)
static bool cookie_build (private_receiver_t *this, message_t *message, u_int32_t t, chunk_t secret, chunk_t *cookie)
static bool cookie_verify (private_receiver_t *this, message_t *message, chunk_t cookie)
static bool check_cookie (private_receiver_t *this, message_t *message)
static bool cookie_required (private_receiver_t *this, u_int half_open, u_int32_t now)
static bool drop_ike_sa_init (private_receiver_t *this, message_t *message)
static job_requeue_t receive_packets (private_receiver_t *this)
METHOD (receiver_t, add_esp_cb, void, private_receiver_t *this, receiver_esp_cb_t callback, void *data)
METHOD (receiver_t, del_esp_cb, void, private_receiver_t *this, receiver_esp_cb_t callback)
METHOD (receiver_t, destroy, void, private_receiver_t *this)
receiver_t * receiver_create ()
Macro Definition Documentation
#define BLOCK_THRESHOLD_DEFAULT 5
default value for private_receiver_t.block_threshold
Definition at line 42 of file receiver.c.
Referenced by receiver_create().
#define COOKIE_CALMDOWN_DELAY 10
time we wait before disabling cookies
Definition at line 36 of file receiver.c.
Referenced by cookie_required().
#define COOKIE_LIFETIME 10
lifetime of a cookie, in seconds
Definition at line 34 of file receiver.c.
Referenced by cookie_verify().
#define COOKIE_REUSE 10000
how many times to reuse the secret
Definition at line 38 of file receiver.c.
Referenced by drop_ike_sa_init().
#define COOKIE_THRESHOLD_DEFAULT 10
default value for private_receiver_t.cookie_threshold
Definition at line 40 of file receiver.c.
Referenced by receiver_create().
#define NOTIFY_PAYLOAD_HEADER_LENGTH 8
Length of a notify payload header
Definition at line 46 of file receiver.c.
Referenced by check_cookie().
#define SECRET_LENGTH 16
length of the secret to use for cookie calculation
Definition at line 44 of file receiver.c.
Referenced by drop_ike_sa_init(), and receiver_create().
Typedef Documentation
typedef struct private_receiver_t private_receiver_t
Definition at line 48 of file receiver.c.
Function Documentation
static bool check_cookie (private_receiver_t * this, message_t * message) static
Check if a valid cookie found
Definition at line 262 of file receiver.c.
References COOKIE, cookie_verify(), data, DBG2, DBG_NET, FALSE, message_t::get_packet_data, hasher, IKE_HEADER_LENGTH, chunk_t::len, NOTIFY_PAYLOAD_HEADER_LENGTH, PLV2_NOTIFY, chunk_t::ptr, and TRUE.
Referenced by drop_ike_sa_init().
 {
     chunk_t data;
     /* check for a cookie. We don't use our parser here and do it
      * quick and dirty for performance reasons.
      * we assume the cookie is the first payload (which is a MUST), and
      * the cookie's SPI length is zero. */
     data = message->get_packet_data(message);
     if (data.len <
          IKE_HEADER_LENGTH + NOTIFY_PAYLOAD_HEADER_LENGTH +
          sizeof(u_int32_t) + this->hasher->get_hash_size(this->hasher) ||
         *(data.ptr + 16) != PLV2_NOTIFY ||
         *(u_int16_t*)(data.ptr + IKE_HEADER_LENGTH + 6) != htons(COOKIE))
     {
         /* no cookie found */
         return FALSE;
     }
     data.ptr += IKE_HEADER_LENGTH + NOTIFY_PAYLOAD_HEADER_LENGTH;
     data.len = sizeof(u_int32_t) + this->hasher->get_hash_size(this->hasher);
     if (!cookie_verify(this, message, data))
     {
         DBG2(DBG_NET, "found cookie, but content invalid");
         return FALSE;
     }
     return TRUE;
 }
static bool cookie_build (private_receiver_t * this, message_t * message, u_int32_t t, chunk_t secret, chunk_t * cookie) static
build a cookie
Definition at line 195 of file receiver.c.
References chunk_alloca, chunk_cat, chunk_cata, chunk_from_thing, FALSE, host_t::get_address, message_t::get_initiator_spi, message_t::get_source, hash, hasher, ip, chunk_t::ptr, and TRUE.
Referenced by cookie_verify(), and drop_ike_sa_init().
 {
     u_int64_t spi = message->get_initiator_spi(message);
     host_t *ip = message->get_source(message);
     chunk_t input, hash;
     /* COOKIE = t | sha1( IPi | SPIi | t | secret ) */
     input = chunk_cata("cccc", ip->get_address(ip), chunk_from_thing(spi),
                       chunk_from_thing(t), secret);
     hash = chunk_alloca(this->hasher->get_hash_size(this->hasher));
     if (!this->hasher->get_hash(this->hasher, input, hash.ptr))
     {
         return FALSE;
     }
     *cookie = chunk_cat("cc", chunk_from_thing(t), hash);
     return TRUE;
 }
static bool cookie_required (private_receiver_t * this, u_int half_open, u_int32_t now) static
Check if we currently require cookies
Definition at line 293 of file receiver.c.
References COOKIE_CALMDOWN_DELAY, FALSE, and TRUE.
Referenced by drop_ike_sa_init().
 {
     if (this->cookie_threshold && half_open >= this->cookie_threshold)
     {
         this->last_cookie = now;
         return TRUE;
     }
     if (this->last_cookie && now < this->last_cookie + COOKIE_CALMDOWN_DELAY)
     {
         /* We don't disable cookies unless we haven't seen IKE_SA_INITs
          * for COOKIE_CALMDOWN_DELAY seconds. This avoids jittering between
          * cookie on / cookie off states, which is problematic. Consider the
          * following: A legitimiate initiator sends a IKE_SA_INIT while we
          * are under a DoS attack. If we toggle our cookie behavior,
          * multiple retransmits of this IKE_SA_INIT might get answered with
          * and without cookies. The initiator goes on and retries with
          * a cookie, but it can't know if the completing IKE_SA_INIT response
          * is to its IKE_SA_INIT request with or without cookies. This is
          * problematic, as the cookie is part of AUTH payload data.
          */
         this->last_cookie = now;
         return TRUE;
     }
     return FALSE;
 }
static bool cookie_verify (private_receiver_t * this, message_t * message, chunk_t cookie) static
verify a received cookie
Definition at line 217 of file receiver.c.
References chunk_equals_const(), chunk_free(), chunk_from_thing, cookie_build(), COOKIE_LIFETIME, DBG2, DBG_NET, FALSE, hasher, if(), chunk_t::len, chunk_t::ptr, time_monotonic(), and TRUE.
Referenced by check_cookie().
 {
     u_int32_t t, now;
     chunk_t reference;
     chunk_t secret;
     now = time_monotonic(NULL);
     t = *(u_int32_t*)cookie.ptr;
     if (cookie.len != sizeof(u_int32_t) +
             this->hasher->get_hash_size(this->hasher) ||
         t < now - this->secret_offset - COOKIE_LIFETIME)
     {
         DBG2(DBG_NET, "received cookie lifetime expired, rejecting");
         return FALSE;
     }
     /* check if cookie is derived from old_secret */
     if (t + this->secret_offset > this->secret_switch)
     {
         secret = chunk_from_thing(this->secret);
     }
     else
     {
         secret = chunk_from_thing(this->secret_old);
     }
     /* compare own calculation against received */
     if (!cookie_build(this, message, t, secret, &reference))
     {
         return FALSE;
     }
     if (chunk_equals_const(reference, cookie))
     {
         chunk_free(&reference);
         return TRUE;
     }
     chunk_free(&reference);
     return FALSE;
 }
static bool drop_ike_sa_init (private_receiver_t * this, message_t * message) static
Check if we should drop IKE_SA_INIT because of cookie/overload checking
Definition at line 323 of file receiver.c.
References charon, check_cookie(), chunk_free(), chunk_from_thing, COOKIE, cookie_build(), cookie_required(), COOKIE_REUSE, DBG1, DBG2, DBG_NET, FALSE, message_t::get_destination, ike_sa_manager_t::get_half_open_count, processor_t::get_job_load, message_t::get_major_version, message_t::get_source, IKE_SA_INIT, daemon_t::ike_sa_manager, IKEV2_MAJOR_VERSION, JOB_PRIO_MAX, lib, memcpy, memwipe(), library_t::processor, rng, SECRET_LENGTH, send_notify(), time_monotonic(), and TRUE.
Referenced by receive_packets().
 {
     u_int half_open, half_open_r;
     u_int32_t now;
     now = time_monotonic(NULL);
     half_open = charon->ike_sa_manager->get_half_open_count(
                                         charon->ike_sa_manager, NULL, FALSE);
     half_open_r = charon->ike_sa_manager->get_half_open_count(
                                         charon->ike_sa_manager, NULL, TRUE);
     /* check for cookies in IKEv2 */
     if (message->get_major_version(message) == IKEV2_MAJOR_VERSION &&
         cookie_required(this, half_open_r, now) && !check_cookie(this, message))
     {
         chunk_t cookie;
         DBG2(DBG_NET, "received packet from: %#H to %#H",
              message->get_source(message),
              message->get_destination(message));
         if (!cookie_build(this, message, now - this->secret_offset,
                           chunk_from_thing(this->secret), &cookie))
         {
             return TRUE;
         }
         DBG2(DBG_NET, "sending COOKIE notify to %H",
              message->get_source(message));
         send_notify(message, IKEV2_MAJOR_VERSION, IKE_SA_INIT, COOKIE, cookie);
         chunk_free(&cookie);
         if (++this->secret_used > COOKIE_REUSE)
         {
             char secret[SECRET_LENGTH];
             DBG1(DBG_NET, "generating new cookie secret after %d uses",
                  this->secret_used);
             if (this->rng->get_bytes(this->rng, SECRET_LENGTH, secret))
             {
                 memcpy(this->secret_old, this->secret, SECRET_LENGTH);
                 memcpy(this->secret, secret, SECRET_LENGTH);
                 memwipe(secret, SECRET_LENGTH);
                 this->secret_switch = now;
                 this->secret_used = 0;
             }
             else
             {
                 DBG1(DBG_NET, "failed to allocated cookie secret, keeping old");
             }
         }
         return TRUE;
     }
     /* check if peer has too many IKE_SAs half open */
     if (this->block_threshold &&
         charon->ike_sa_manager->get_half_open_count(charon->ike_sa_manager,
                 message->get_source(message), TRUE) >= this->block_threshold)
     {
         DBG1(DBG_NET, "ignoring IKE_SA setup from %H, "
              "peer too aggressive", message->get_source(message));
         return TRUE;
     }
     /* check if global half open IKE_SA limit reached */
     if (this->init_limit_half_open &&
         half_open >= this->init_limit_half_open)
     {
         DBG1(DBG_NET, "ignoring IKE_SA setup from %H, half open IKE_SA "
              "count of %d exceeds limit of %d", message->get_source(message),
              half_open, this->init_limit_half_open);
         return TRUE;
     }
     /* check if job load acceptable */
     if (this->init_limit_job_load)
     {
         u_int jobs = 0, i;
         for (i = 0; i < JOB_PRIO_MAX; i++)
         {
             jobs += lib->processor->get_job_load(lib->processor, i);
         }
         if (jobs > this->init_limit_job_load)
         {
             DBG1(DBG_NET, "ignoring IKE_SA setup from %H, job load of %d "
                  "exceeds limit of %d", message->get_source(message),
                  jobs, this->init_limit_job_load);
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (receiver_t , add_esp_cb , void , private_receiver_t * this, receiver_esp_cb_t callback, void * data)
Definition at line 589 of file receiver.c.
References callback, and data.
 {
     this->esp_cb_mutex->lock(this->esp_cb_mutex);
     this->esp_cb.cb = callback;
     this->esp_cb.data = data;
     this->esp_cb_mutex->unlock(this->esp_cb_mutex);
 }
METHOD (receiver_t , del_esp_cb , void , private_receiver_t * this, receiver_esp_cb_t callback)
Definition at line 598 of file receiver.c.
 {
     this->esp_cb_mutex->lock(this->esp_cb_mutex);
     if (this->esp_cb.cb == callback)
     {
         this->esp_cb.cb = NULL;
         this->esp_cb.data = NULL;
     }
     this->esp_cb_mutex->unlock(this->esp_cb_mutex);
 }
METHOD (receiver_t , destroy , void , private_receiver_t * this)
Definition at line 610 of file receiver.c.
References free(), hasher, and rng.
 {
     this->rng->destroy(this->rng);
     this->hasher->destroy(this->hasher);
     this->esp_cb_mutex->destroy(this->esp_cb_mutex);
     free(this);
 }
static job_requeue_t receive_packets (private_receiver_t * this) static
Job callback to receive packets
Definition at line 417 of file receiver.c.
References AGGRESSIVE, bus_t::alert, ALERT_PARSE_ERROR_HEADER, kernel_interface_t::all_interfaces_usable, daemon_t::bus, charon, chunk_empty, chunk_from_chars, data, DBG1, DBG2, DBG3, DBG_NET, packet_t::destroy, message_t::destroy, drop_ike_sa_init(), dst, FALSE, packet_t::get_data, packet_t::get_destination, message_t::get_exchange_type, message_t::get_ike_sa_id, kernel_interface_t::get_interface, message_t::get_major_version, message_t::get_minor_version, host_t::get_port, message_t::get_request, ike_sa_id_t::get_responder_spi, packet_t::get_source, hydra, id, ID_PROT, IKE_SA_INIT, IKEV1_MAJOR_VERSION, IKEV2_MAJOR_VERSION, IKEV2_UDP_PORT, INFORMATIONAL, INFORMATIONAL_V1, INVALID_MAJOR_VERSION, ike_sa_id_t::is_initiator, JOB_REQUEUE_DIRECT, JOB_REQUEUE_FAIR, JOB_REQUEUE_NONE, hydra_t::kernel_interface, chunk_t::len, lib, memeq(), message_create_from_packet(), NOT_SUPPORTED, message_t::parse_header, process_message_job_create(), library_t::processor, chunk_t::ptr, processor_t::queue_job, socket_manager_t::receive, scheduler_t::schedule_job_ms, library_t::scheduler, send_notify(), packet_t::skip_bytes, daemon_t::socket, src, status, SUCCESS, and TRUE.
Referenced by receiver_create().
 {
     ike_sa_id_t *id;
     packet_t *packet;
     message_t *message;
     host_t *src, *dst;
     status_t status;
     bool supported = TRUE;
     chunk_t data, marker = chunk_from_chars(0x00, 0x00, 0x00, 0x00);
     /* read in a packet */
     status = charon->socket->receive(charon->socket, &packet);
     if (status == NOT_SUPPORTED)
     {
         return JOB_REQUEUE_NONE;
     }
     else if (status != SUCCESS)
     {
         DBG2(DBG_NET, "receiving from socket failed!");
         return JOB_REQUEUE_FAIR;
     }
     data = packet->get_data(packet);
     if (data.len == 1 && data.ptr[0] == 0xFF)
     {   /* silently drop NAT-T keepalives */
         packet->destroy(packet);
         return JOB_REQUEUE_DIRECT;
     }
     else if (data.len < marker.len)
     {   /* drop packets that are too small */
         DBG3(DBG_NET, "received packet is too short (%d bytes)", data.len);
         packet->destroy(packet);
         return JOB_REQUEUE_DIRECT;
     }
     dst = packet->get_destination(packet);
     src = packet->get_source(packet);
     if (!hydra->kernel_interface->all_interfaces_usable(hydra->kernel_interface)
         && !hydra->kernel_interface->get_interface(hydra->kernel_interface,
                                                    dst, NULL))
     {
         DBG3(DBG_NET, "received packet from %#H to %#H on ignored interface",
              src, dst);
         packet->destroy(packet);
         return JOB_REQUEUE_DIRECT;
     }
     /* if neither source nor destination port is 500 we assume an IKE packet
      * with Non-ESP marker or an ESP packet */
     if (dst->get_port(dst) != IKEV2_UDP_PORT &&
         src->get_port(src) != IKEV2_UDP_PORT)
     {
         if (memeq(data.ptr, marker.ptr, marker.len))
         {   /* remove Non-ESP marker */
             packet->skip_bytes(packet, marker.len);
         }
         else
         {   /* this seems to be an ESP packet */
             this->esp_cb_mutex->lock(this->esp_cb_mutex);
             if (this->esp_cb.cb)
             {
                 this->esp_cb.cb(this->esp_cb.data, packet);
             }
             else
             {
                 packet->destroy(packet);
             }
             this->esp_cb_mutex->unlock(this->esp_cb_mutex);
             return JOB_REQUEUE_DIRECT;
         }
     }
     /* parse message header */
     message = message_create_from_packet(packet);
     if (message->parse_header(message) != SUCCESS)
     {
         DBG1(DBG_NET, "received invalid IKE header from %H - ignored",
              packet->get_source(packet));
         charon->bus->alert(charon->bus, ALERT_PARSE_ERROR_HEADER, message);
         message->destroy(message);
         return JOB_REQUEUE_DIRECT;
     }
     /* check IKE major version */
     switch (message->get_major_version(message))
     {
         case IKEV2_MAJOR_VERSION:
 #ifndef USE_IKEV2
             if (message->get_exchange_type(message) == IKE_SA_INIT &&
                 message->get_request(message))
             {
                 send_notify(message, IKEV1_MAJOR_VERSION, INFORMATIONAL_V1,
                             INVALID_MAJOR_VERSION, chunk_empty);
                 supported = FALSE;
             }
 #endif /* USE_IKEV2 */
             break;
         case IKEV1_MAJOR_VERSION:
 #ifndef USE_IKEV1
             if (message->get_exchange_type(message) == ID_PROT ||
                 message->get_exchange_type(message) == AGGRESSIVE)
             {
                 send_notify(message, IKEV2_MAJOR_VERSION, INFORMATIONAL,
                             INVALID_MAJOR_VERSION, chunk_empty);
                 supported = FALSE;
             }
 #endif /* USE_IKEV1 */
             break;
         default:
 #ifdef USE_IKEV2
             send_notify(message, IKEV2_MAJOR_VERSION, INFORMATIONAL,
                         INVALID_MAJOR_VERSION, chunk_empty);
 #elif defined(USE_IKEV1)
             send_notify(message, IKEV1_MAJOR_VERSION, INFORMATIONAL_V1,
                         INVALID_MAJOR_VERSION, chunk_empty);
 #endif /* USE_IKEV1 */
             supported = FALSE;
             break;
     }
     if (!supported)
     {
         DBG1(DBG_NET, "received unsupported IKE version %d.%d from %H, sending "
              "INVALID_MAJOR_VERSION", message->get_major_version(message),
              message->get_minor_version(message), packet->get_source(packet));
         message->destroy(message);
         return JOB_REQUEUE_DIRECT;
     }
     if (message->get_request(message) &&
         message->get_exchange_type(message) == IKE_SA_INIT)
     {
         id = message->get_ike_sa_id(message);
         if (this->initiator_only || !id->is_initiator(id) ||
             drop_ike_sa_init(this, message))
         {
             message->destroy(message);
             return JOB_REQUEUE_DIRECT;
         }
     }
     if (message->get_exchange_type(message) == ID_PROT ||
         message->get_exchange_type(message) == AGGRESSIVE)
     {
         id = message->get_ike_sa_id(message);
         if (id->get_responder_spi(id) == 0 &&
            (this->initiator_only || drop_ike_sa_init(this, message)))
         {
             message->destroy(message);
             return JOB_REQUEUE_DIRECT;
         }
     }
     if (this->receive_delay)
     {
         if (this->receive_delay_type == 0 ||
             this->receive_delay_type == message->get_exchange_type(message))
         {
             if ((message->get_request(message) && this->receive_delay_request) ||
                 (!message->get_request(message) && this->receive_delay_response))
             {
                 DBG1(DBG_NET, "using receive delay: %dms",
                      this->receive_delay);
                 lib->scheduler->schedule_job_ms(lib->scheduler,
                                 (job_t*)process_message_job_create(message),
                                 this->receive_delay);
                 return JOB_REQUEUE_DIRECT;
             }
         }
     }
     lib->processor->queue_job(lib->processor,
                               (job_t*)process_message_job_create(message));
     return JOB_REQUEUE_DIRECT;
 }
static void send_notify (message_t * request, int major, exchange_type_t exchange, notify_type_t type, chunk_t data) static
send a notify back to the sender
Definition at line 162 of file receiver.c.
References message_t::add_notify, charon, host_t::clone, message_t::destroy, dst, FALSE, message_t::generate, message_t::get_destination, message_t::get_ike_sa_id, message_t::get_source, IKEV2_MAJOR_VERSION, message_create(), response, sender_t::send, daemon_t::sender, message_t::set_destination, message_t::set_exchange_type, message_t::set_ike_sa_id, message_t::set_message_id, message_t::set_request, message_t::set_source, src, SUCCESS, and ike_sa_id_t::switch_initiator.
Referenced by drop_ike_sa_init(), and receive_packets().
 {
     ike_sa_id_t *ike_sa_id;
     message_t *response;
     host_t *src, *dst;
     packet_t *packet;
     response = message_create(major, 0);
     response->set_exchange_type(response, exchange);
     response->add_notify(response, FALSE, type, data);
     dst = request->get_source(request);
     src = request->get_destination(request);
     response->set_source(response, src->clone(src));
     response->set_destination(response, dst->clone(dst));
     if (major == IKEV2_MAJOR_VERSION)
     {
         response->set_request(response, FALSE);
     }
     response->set_message_id(response, 0);
     ike_sa_id = request->get_ike_sa_id(request);
     ike_sa_id->switch_initiator(ike_sa_id);
     response->set_ike_sa_id(response, ike_sa_id);
     if (response->generate(response, NULL, &packet) == SUCCESS)
     {
         charon->sender->send(charon->sender, packet);
     }
     response->destroy(response);
 }