strongSwan: ike_auth
ike_auth
tasks
Classes
struct ike_auth_t
Typedefs
typedef struct ike_auth_t ike_auth_t
Functions
ike_auth_t * ike_auth_create (ike_sa_t *ike_sa, bool initiator)
Detailed Description
Typedef Documentation
typedef struct ike_auth_t ike_auth_t
Definition at line 24 of file ike_auth.h.
Function Documentation
ike_auth_t* ike_auth_create (ike_sa_t * ike_sa, bool initiator)
Create a new task of type TASK_IKE_AUTH.
Parameters
ike_sa IKE_SA this task works for
initiator TRUE if task is the initiator of an exchange
Returns
ike_auth task to handle by the task_manager
Definition at line 1175 of file ike_auth.c.
References INIT, initiator, linked_list_create(), and TRUE.
Referenced by METHOD(), and process_request().
 {
     private_ike_auth_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .build = _build_r,
                 .process = _process_r,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .initiator = initiator,
         .candidates = linked_list_create(),
         .do_another_auth = TRUE,
         .expect_another_auth = TRUE,
     );
     if (initiator)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
     }
     return &this->public;
 }