strongSwan: vici_plugin.c File Reference
vici_plugin.c File Reference
#include "vici_plugin.h"
#include "vici_dispatcher.h"
#include "vici_query.h"
#include "vici_control.h"
#include "vici_cred.h"
#include "vici_config.h"
#include "vici_attribute.h"
#include "vici_authority.h"
#include "vici_logger.h"
#include <library.h>
#include <daemon.h>
Classes
struct private_vici_plugin_t
Typedefs
typedef struct
private_vici_plugin_t private_vici_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_vici_plugin_t *this)
static bool register_vici (private_vici_plugin_t *this, plugin_feature_t *feature, bool reg, void *data)
METHOD (plugin_t, get_features, int, private_vici_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_vici_plugin_t *this)
plugin_t * vici_plugin_create ()
Typedef Documentation
typedef struct private_vici_plugin_t private_vici_plugin_t
Definition at line 54 of file vici_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_vici_plugin_t * this)
Definition at line 107 of file vici_plugin.c.
 {
     return "vici";
 }
METHOD (plugin_t , get_features , int , private_vici_plugin_t * this, plugin_feature_t * features[])
Definition at line 170 of file vici_plugin.c.
References countof, PLUGIN_CALLBACK, PLUGIN_PROVIDE, and register_vici().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)register_vici, NULL),
             PLUGIN_PROVIDE(CUSTOM, "vici"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_vici_plugin_t * this)
Definition at line 181 of file vici_plugin.c.
References free().
 {
     free(this);
 }
static bool register_vici (private_vici_plugin_t * this, plugin_feature_t * feature, bool reg, void * data) static
Register vici plugin features
Definition at line 116 of file vici_plugin.c.
References backend_manager_t::add_backend, bus_t::add_listener, bus_t::add_logger, attribute_manager_t::add_provider, credential_manager_t::add_set, daemon_t::attributes, daemon_t::backends, daemon_t::bus, charon, library_t::credmgr, FALSE, settings_t::get_str, lib, library_t::ns, query(), backend_manager_t::remove_backend, bus_t::remove_listener, bus_t::remove_logger, attribute_manager_t::remove_provider, credential_manager_t::remove_set, library_t::settings, TRUE, uri, vici_attribute_create(), vici_authority_create(), vici_config_create(), vici_control_create(), vici_cred_create(), VICI_DEFAULT_URI, vici_dispatcher_create(), vici_logger_create(), and vici_query_create().
Referenced by METHOD().
 {
     if (reg)
     {
         char *uri;
         uri = lib->settings->get_str(lib->settings, "%s.plugins.vici.socket",
                                      VICI_DEFAULT_URI, lib->ns);
         this->dispatcher = vici_dispatcher_create(uri);
         if (this->dispatcher)
         {
             this->query = vici_query_create(this->dispatcher);
             this->control = vici_control_create(this->dispatcher);
             this->cred = vici_cred_create(this->dispatcher);
             this->authority = vici_authority_create(this->dispatcher,
                                                     this->cred);
             lib->credmgr->add_set(lib->credmgr, &this->authority->set);
             this->config = vici_config_create(this->dispatcher, this->authority);
             this->attrs = vici_attribute_create(this->dispatcher);
             this->logger = vici_logger_create(this->dispatcher);
             charon->backends->add_backend(charon->backends,
                                           &this->config->backend);
             charon->attributes->add_provider(charon->attributes,
                                              &this->attrs->provider);
             charon->bus->add_logger(charon->bus, &this->logger->logger);
             charon->bus->add_listener(charon->bus, &this->query->listener);
             return TRUE;
         }
         return FALSE;
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->query->listener);
         charon->bus->remove_logger(charon->bus, &this->logger->logger);
         charon->attributes->remove_provider(charon->attributes,
                                             &this->attrs->provider);
         charon->backends->remove_backend(charon->backends,
                                          &this->config->backend);
         this->logger->destroy(this->logger);
         this->attrs->destroy(this->attrs);
         this->config->destroy(this->config);
         lib->credmgr->remove_set(lib->credmgr, &this->authority->set);
         this->authority->destroy(this->authority);
         this->cred->destroy(this->cred);
         this->control->destroy(this->control);
         this->query->destroy(this->query);
         this->dispatcher->destroy(this->dispatcher);
     }
     return TRUE;
 }
plugin_t* vici_plugin_create ()
Definition at line 190 of file vici_plugin.c.
References destroy(), INIT, and return_false().
 {
     private_vici_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .reload = (void*)return_false,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }