strongSwan: chunk.c File Reference
chunk.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <ctype.h>
#include <time.h>
#include "chunk.h"
Classes
struct mmaped_chunk_t
Functions
chunk_t chunk_create_clone (u_char *ptr, chunk_t chunk)
size_t chunk_length (const char *mode,...)
chunk_t chunk_create_cat (u_char *ptr, const char *mode,...)
void chunk_split (chunk_t chunk, const char *mode,...)
bool chunk_write (chunk_t chunk, char *path, mode_t mask, bool force)
bool chunk_from_fd (int fd, chunk_t *out)
chunk_t * chunk_map (char *path, bool wr)
bool chunk_unmap (chunk_t *public)
chunk_t chunk_to_hex (chunk_t chunk, char *buf, bool uppercase)
static char hex2bin (char hex)
chunk_t chunk_from_hex (chunk_t hex, char *buf)
chunk_t chunk_to_base64 (chunk_t chunk, char *buf)
static int b642bin (char b64)
chunk_t chunk_from_base64 (chunk_t base64, char *buf)
chunk_t chunk_to_base32 (chunk_t chunk, char *buf)
int chunk_compare (chunk_t a, chunk_t b)
bool chunk_increment (chunk_t chunk)
bool chunk_printable (chunk_t chunk, chunk_t *sane, char replace)
static u_int64_t sipget (u_char *in)
static u_int64_t siprotate (u_int64_t v, int shift)
static void sipround (u_int64_t *v0, u_int64_t *v1, u_int64_t *v2, u_int64_t *v3)
static void sipcompress (u_int64_t *v0, u_int64_t *v1, u_int64_t *v2, u_int64_t *v3, u_int64_t m)
static u_int64_t siplast (size_t len, u_char *pos)
static u_int64_t chunk_mac_inc (chunk_t chunk, u_char *key, u_int64_t m)
u_int64_t chunk_mac (chunk_t chunk, u_char *key)
void chunk_hash_seed ()
u_int32_t chunk_hash_inc (chunk_t chunk, u_int32_t hash)
u_int32_t chunk_hash (chunk_t chunk)
u_int32_t chunk_hash_static_inc (chunk_t chunk, u_int32_t hash)
u_int32_t chunk_hash_static (chunk_t chunk)
u_int16_t chunk_internet_checksum_inc (chunk_t data, u_int16_t checksum)
u_int16_t chunk_internet_checksum (chunk_t data)
int chunk_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Variables
chunk_t chunk_empty = { NULL, 0 }
static char hexdig_upper [] = "0123456789ABCDEF"
static char hexdig_lower [] = "0123456789abcdef"
static char b64digits []
static char b32digits [] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
static u_char key [16] = {}
static u_char static_key []
Function Documentation
static int b642bin (char b64) static
convert a base 64 digit to its binary form (inversion of b64digits array)
Definition at line 597 of file chunk.c.
Referenced by chunk_from_base64().
 {
     switch (b64)
     {
         case 'A' ... 'Z':
             return b64 - 'A';
         case 'a' ... 'z':
             return ('Z' - 'A' + 1) + b64 - 'a';
         case '0' ... '9':
             return ('Z' - 'A' + 1) + ('z' - 'a' + 1) + b64 - '0';
         case '+':
         case '-':
             return 62;
         case '/':
         case '_':
             return 63;
         case '=':
             return 0;
         default:
             return -1;
     }
 }
static u_int64_t chunk_mac_inc (chunk_t chunk, u_char * key, u_int64_t m) static
Caculate SipHash-2-4 with an optional first block given as argument.
Definition at line 858 of file chunk.c.
References end, chunk_t::len, len, chunk_t::ptr, sipcompress(), sipget(), siplast(), and sipround().
Referenced by chunk_hash_inc(), chunk_hash_static_inc(), and chunk_mac().
 {
     u_int64_t v0, v1, v2, v3, k0, k1;
     size_t len = chunk.len;
     u_char *pos = chunk.ptr, *end;
     end = chunk.ptr + len - (len % 8);
     k0 = sipget(key);
     k1 = sipget(key + 8);
     v0 = k0 ^ 0x736f6d6570736575ULL;
     v1 = k1 ^ 0x646f72616e646f6dULL;
     v2 = k0 ^ 0x6c7967656e657261ULL;
     v3 = k1 ^ 0x7465646279746573ULL;
     if (m)
     {
         sipcompress(&v0, &v1, &v2, &v3, m);
     }
     /* compression with c = 2 */
     for (; pos != end; pos += 8)
     {
         m = sipget(pos);
         sipcompress(&v0, &v1, &v2, &v3, m);
     }
     sipcompress(&v0, &v1, &v2, &v3, siplast(len, pos));
     /* finalization with d = 4 */
     v2 ^= 0xff;
     sipround(&v0, &v1, &v2, &v3);
     sipround(&v0, &v1, &v2, &v3);
     sipround(&v0, &v1, &v2, &v3);
     sipround(&v0, &v1, &v2, &v3);
     return v0 ^ v1 ^ v2  ^ v3;
 }
static char hex2bin (char hex) static
convert a signle hex character to its binary value
Definition at line 483 of file chunk.c.
Referenced by chunk_from_hex().
 {
     switch (hex)
     {
         case '0' ... '9':
             return hex - '0';
         case 'A' ... 'F':
             return hex - 'A' + 10;
         case 'a' ... 'f':
             return hex - 'a' + 10;
         default:
             return 0;
     }
 }
static void sipcompress (u_int64_t * v0, u_int64_t * v1, u_int64_t * v2, u_int64_t * v3, u_int64_t m) inline static
Definition at line 817 of file chunk.c.
References m, and sipround().
Referenced by chunk_mac_inc().
 {
     *v3 ^= m;
     sipround(v0, v1, v2, v3);
     sipround(v0, v1, v2, v3);
     *v0 ^= m;
 }
static u_int64_t sipget (u_char * in) inline static
Helper functions for chunk_mac()
Definition at line 778 of file chunk.c.
References in.
Referenced by chunk_mac_inc().
 {
     u_int64_t v = 0;
     int i;
     for (i = 0; i < 64; i += 8, ++in)
     {
         v |= ((u_int64_t)*in) << i;
     }
     return v;
 }
static u_int64_t siplast (size_t len, u_char * pos) inline static
Definition at line 826 of file chunk.c.
References b.
Referenced by chunk_mac_inc().
 {
     u_int64_t b;
     int rem = len & 7;
     b = ((u_int64_t)len) << 56;
     switch (rem)
     {
         case 7:
             b |= ((u_int64_t)pos[6]) << 48;
         case 6:
             b |= ((u_int64_t)pos[5]) << 40;
         case 5:
             b |= ((u_int64_t)pos[4]) << 32;
         case 4:
             b |= ((u_int64_t)pos[3]) << 24;
         case 3:
             b |= ((u_int64_t)pos[2]) << 16;
         case 2:
             b |= ((u_int64_t)pos[1]) <<  8;
         case 1:
             b |= ((u_int64_t)pos[0]);
             break;
         case 0:
             break;
     }
     return b;
 }
static u_int64_t siprotate (u_int64_t v, int shift) inline static
Definition at line 790 of file chunk.c.
Referenced by sipround().
 {
         return (v << shift) | (v >> (64 - shift));
 }
static void sipround (u_int64_t * v0, u_int64_t * v1, u_int64_t * v2, u_int64_t * v3) inline static
Definition at line 795 of file chunk.c.
References siprotate().
Referenced by chunk_mac_inc(), and sipcompress().
 {
     *v0 += *v1;
     *v1 = siprotate(*v1, 13);
     *v1 ^= *v0;
     *v0 = siprotate(*v0, 32);
     *v2 += *v3;
     *v3 = siprotate(*v3, 16);
     *v3 ^= *v2;
     *v2 += *v1;
     *v1 = siprotate(*v1, 17);
     *v1 ^= *v2;
     *v2 = siprotate(*v2, 32);
     *v0 += *v3;
     *v3 = siprotate(*v3, 21);
     *v3 ^= *v0;
 }
Variable Documentation
char b32digits[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567" static
base 32 conversion digits
Definition at line 654 of file chunk.c.
Referenced by chunk_to_base32().
char b64digits[] static
Initial value:
=
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
base 64 conversion digits
Definition at line 553 of file chunk.c.
Referenced by chunk_to_base64().
char hexdig_lower[] = "0123456789abcdef" static
Definition at line 450 of file chunk.c.
Referenced by chunk_to_hex().
char hexdig_upper[] = "0123456789ABCDEF" static
hex conversion digits
Definition at line 449 of file chunk.c.
Referenced by chunk_to_hex().
u_char key[16] = {} static
Secret key allocated randomly with chunk_hash_seed().
Definition at line 907 of file chunk.c.
Referenced by chunk_hash(), chunk_hash_inc(), and chunk_hash_seed().
u_char static_key[] static
Initial value:
= {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
                              0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f}
Static key used in case predictable hash values are required.
Definition at line 912 of file chunk.c.
Referenced by chunk_hash_static(), and chunk_hash_static_inc().