strongSwan: ocsp_response_wrapper.c File Reference
ocsp_response_wrapper.c File Reference
#include "ocsp_response_wrapper.h"
Classes
struct private_ocsp_response_wrapper_t
struct wrapper_enumerator_t
Typedefs
typedef struct
private_ocsp_response_wrapper_t private_ocsp_response_wrapper_t
Functions
static bool enumerate (wrapper_enumerator_t *this, certificate_t **cert)
static void enumerator_destroy (wrapper_enumerator_t *this)
METHOD (credential_set_t, create_enumerator, enumerator_t *, private_ocsp_response_wrapper_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (ocsp_response_wrapper_t, destroy, void, private_ocsp_response_wrapper_t *this)
ocsp_response_wrapper_t * ocsp_response_wrapper_create (ocsp_response_t *response)
Typedef Documentation
typedef struct private_ocsp_response_wrapper_t private_ocsp_response_wrapper_t
Definition at line 18 of file ocsp_response_wrapper.c.
Function Documentation
static bool enumerate (wrapper_enumerator_t * this, certificate_t ** cert) static
enumerate function wrapper_enumerator_t
Definition at line 55 of file ocsp_response_wrapper.c.
References CERT_ANY, DESTROY_IF, FALSE, certificate_t::get_public_key, certificate_t::get_type, certificate_t::has_subject, key, KEY_ANY, public, and TRUE.
Referenced by METHOD().
 {
     certificate_t *current;
     public_key_t *public;
     while (this->inner->enumerate(this->inner, &current))
     {
         if (this->cert != CERT_ANY && this->cert != current->get_type(current))
         {   /* CERT type requested, but does not match */
             continue;
         }
         public = current->get_public_key(current);
         if (this->key != KEY_ANY && !public)
         {   /* key type requested, but no public key */
             DESTROY_IF(public);
             continue;
         }
         if (this->key != KEY_ANY && public && this->key != public->get_type(public))
         {   /* key type requested, but public key has another type */
             DESTROY_IF(public);
             continue;
         }
         DESTROY_IF(public);
         if (this->id && !current->has_subject(current, this->id))
         {   /* subject requested, but does not match */
             continue;
         }
         *cert = current;
         return TRUE;
     }
     return FALSE;
 }
static void enumerator_destroy (wrapper_enumerator_t * this) static
destroy function for wrapper_enumerator_t
Definition at line 91 of file ocsp_response_wrapper.c.
References free().
Referenced by METHOD().
 {
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_enumerator , enumerator_t * , private_ocsp_response_wrapper_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 97 of file ocsp_response_wrapper.c.
References wrapper_enumerator_t::cert, cert, enumerator_t::destroy, enumerator_t::enumerate, enumerate(), enumerator_destroy(), id, wrapper_enumerator_t::id, wrapper_enumerator_t::inner, wrapper_enumerator_t::key, key, malloc_thing, wrapper_enumerator_t::public, and response.
 {
     wrapper_enumerator_t *enumerator;
     if (trusted)
     {
         return NULL;
     }
     enumerator = malloc_thing(wrapper_enumerator_t);
     enumerator->cert = cert;
     enumerator->key = key;
     enumerator->id = id;
     enumerator->inner = this->response->create_cert_enumerator(this->response);
     enumerator->public.enumerate = (void*)enumerate;
     enumerator->public.destroy = (void*)enumerator_destroy;
     return &enumerator->public;
 }
METHOD (ocsp_response_wrapper_t , destroy , void , private_ocsp_response_wrapper_t * this)
Definition at line 118 of file ocsp_response_wrapper.c.
References free().
 {
     free(this);
 }