strongSwan: ha_ctl.c File Reference
ha_ctl.c File Reference
#include "ha_ctl.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/select.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_ha_ctl_t
Macros
#define HA_FIFO IPSEC_PIDDIR "/charon.ha"
Typedefs
typedef struct private_ha_ctl_t private_ha_ctl_t
Functions
static bool change_fifo_permissions ()
static bool recreate_fifo ()
static job_requeue_t dispatch_fifo (private_ha_ctl_t *this)
METHOD (ha_ctl_t, destroy, void, private_ha_ctl_t *this)
ha_ctl_t * ha_ctl_create (ha_segments_t *segments, ha_cache_t *cache)
Macro Definition Documentation
#define HA_FIFO IPSEC_PIDDIR "/charon.ha"
Definition at line 29 of file ha_ctl.c.
Referenced by change_fifo_permissions(), dispatch_fifo(), ha_ctl_create(), METHOD(), and recreate_fifo().
Typedef Documentation
typedef struct private_ha_ctl_t private_ha_ctl_t
Definition at line 31 of file ha_ctl.c.
Function Documentation
static bool change_fifo_permissions () static
Change the permissions of the control FIFO, returns TRUE on success
Definition at line 57 of file ha_ctl.c.
References library_t::caps, DBG1, DBG_CFG, FALSE, capabilities_t::get_gid, capabilities_t::get_uid, HA_FIFO, lib, strerror, and TRUE.
Referenced by ha_ctl_create(), and recreate_fifo().
 {
     if (chown(HA_FIFO, lib->caps->get_uid(lib->caps),
               lib->caps->get_gid(lib->caps)) != 0)
     {
         DBG1(DBG_CFG, "changing HA FIFO permissions failed: %s",
              strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
static job_requeue_t dispatch_fifo (private_ha_ctl_t * this) static
FIFO dispatching function
Definition at line 92 of file ha_ctl.c.
References cache(), close, DBG1, DBG_CFG, HA_FIFO, JOB_REQUEUE_DIRECT, JOB_REQUEUE_FAIR, memset, read, recreate_fifo(), segment, sleep, strerror, thread_cancelability(), and TRUE.
Referenced by ha_ctl_create().
 {
     int fifo;
     bool oldstate;
     char buf[8];
     u_int segment;
     struct stat sb;
     oldstate = thread_cancelability(TRUE);
     fifo = open(HA_FIFO, O_RDONLY);
     thread_cancelability(oldstate);
     if (fifo == -1 || fstat(fifo, &sb) != 0 || !S_ISFIFO(sb.st_mode))
     {
         if (fifo == -1 && errno != ENOENT)
         {
             DBG1(DBG_CFG, "opening HA FIFO failed: %s", strerror(errno));
         }
         else
         {
             DBG1(DBG_CFG, "%s is not a FIFO, recreate it", HA_FIFO);
             recreate_fifo();
         }
         if (fifo != -1)
         {
             close(fifo);
         }
         sleep(1);
         return JOB_REQUEUE_FAIR;
     }
     memset(buf, 0, sizeof(buf));
     if (read(fifo, buf, sizeof(buf)-1) > 1)
     {
         segment = atoi(&buf[1]);
         if (segment)
         {
             switch (buf[0])
             {
                 case '+':
                     this->segments->activate(this->segments, segment, TRUE);
                     break;
                 case '-':
                     this->segments->deactivate(this->segments, segment, TRUE);
                     break;
                 case '*':
                     this->cache->resync(this->cache, segment);
                     break;
                 default:
                     break;
             }
         }
     }
     close(fifo);
     return JOB_REQUEUE_DIRECT;
 }
METHOD (ha_ctl_t , destroy , void , private_ha_ctl_t * this)
Definition at line 149 of file ha_ctl.c.
References free(), and HA_FIFO.
 {
     unlink(HA_FIFO);
     free(this);
 }
static bool recreate_fifo () static
Deletes and creates the control FIFO, returns TRUE on success
Definition at line 72 of file ha_ctl.c.
References change_fifo_permissions(), DBG1, DBG_CFG, FALSE, HA_FIFO, strerror, and TRUE.
Referenced by dispatch_fifo(), and ha_ctl_create().
 {
     mode_t old;
     bool success = TRUE;
     unlink(HA_FIFO);
     old = umask(S_IRWXO);
     if (mkfifo(HA_FIFO, S_IRUSR | S_IWUSR) != 0)
     {
         DBG1(DBG_CFG, "creating HA FIFO %s failed: %s", HA_FIFO,
              strerror(errno));
         success = FALSE;
     }
     umask(old);
     return success && change_fifo_permissions();
 }