strongSwan: message.c File Reference
message.c File Reference
#include <stdlib.h>
#include <string.h>
#include "message.h"
#include <library.h>
#include <bio/bio_writer.h>
#include <collections/array.h>
#include <daemon.h>
#include <sa/ikev1/keymat_v1.h>
#include <encoding/generator.h>
#include <encoding/parser.h>
#include <encoding/payloads/encodings.h>
#include <encoding/payloads/payload.h>
#include <encoding/payloads/hash_payload.h>
#include <encoding/payloads/encrypted_payload.h>
#include <encoding/payloads/encrypted_fragment_payload.h>
#include <encoding/payloads/unknown_payload.h>
#include <encoding/payloads/cp_payload.h>
#include <encoding/payloads/fragment_payload.h>
Classes
struct payload_rule_t
struct payload_order_t
struct message_rule_t
struct fragment_data_t
struct private_message_t
struct fragment_t
Macros
#define MAX_NOTIFY_PAYLOADS 20
#define MAX_DELETE_PAYLOADS 20
#define MAX_CERT_PAYLOADS 8
#define MAX_VID_PAYLOADS 20
#define MAX_CERTREQ_PAYLOADS 20
#define MAX_NAT_D_PAYLOADS 10
#define MAX_FRAGMENTS 255
#define REDUCE_FRAG_LEN(fl, amount)
Typedefs
typedef struct private_message_t private_message_t
Functions
static void fragment_destroy (fragment_t *this)
static void reset_defrag (private_message_t *this)
static message_rule_t * get_message_rule (private_message_t *this)
static payload_rule_t * get_payload_rule (private_message_t *this, payload_type_t type)
METHOD (message_t, set_ike_sa_id, void, private_message_t *this, ike_sa_id_t *ike_sa_id)
METHOD (message_t, get_ike_sa_id, ike_sa_id_t *, private_message_t *this)
METHOD (message_t, set_message_id, void, private_message_t *this, u_int32_t message_id)
METHOD (message_t, get_message_id, u_int32_t, private_message_t *this)
METHOD (message_t, get_initiator_spi, u_int64_t, private_message_t *this)
METHOD (message_t, get_responder_spi, u_int64_t, private_message_t *this)
METHOD (message_t, set_major_version, void, private_message_t *this, u_int8_t major_version)
METHOD (message_t, get_major_version, u_int8_t, private_message_t *this)
METHOD (message_t, set_minor_version, void, private_message_t *this, u_int8_t minor_version)
METHOD (message_t, get_minor_version, u_int8_t, private_message_t *this)
METHOD (message_t, set_exchange_type, void, private_message_t *this, exchange_type_t exchange_type)
METHOD (message_t, get_exchange_type, exchange_type_t, private_message_t *this)
METHOD (message_t, get_first_payload_type, payload_type_t, private_message_t *this)
METHOD (message_t, set_request, void, private_message_t *this, bool request)
METHOD (message_t, get_request, bool, private_message_t *this)
METHOD (message_t, set_version_flag, void, private_message_t *this)
METHOD (message_t, get_reserved_header_bit, bool, private_message_t *this, u_int nr)
METHOD (message_t, set_reserved_header_bit, void, private_message_t *this, u_int nr)
METHOD (message_t, is_encoded, bool, private_message_t *this)
METHOD (message_t, is_fragmented, bool, private_message_t *this)
METHOD (message_t, add_payload, void, private_message_t *this, payload_t *payload)
METHOD (message_t, add_notify, void, private_message_t *this, bool flush, notify_type_t type, chunk_t data)
METHOD (message_t, set_source, void, private_message_t *this, host_t *host)
METHOD (message_t, set_destination, void, private_message_t *this, host_t *host)
METHOD (message_t, get_source, host_t *, private_message_t *this)
METHOD (message_t, get_destination, host_t *, private_message_t *this)
METHOD (message_t, create_payload_enumerator, enumerator_t *, private_message_t *this)
METHOD (message_t, remove_payload_at, void, private_message_t *this, enumerator_t *enumerator)
METHOD (message_t, get_payload, payload_t *, private_message_t *this, payload_type_t type)
METHOD (message_t, get_notify, notify_payload_t *, private_message_t *this, notify_type_t type)
static char * get_string (private_message_t *this, char *buf, int len)
METHOD (message_t, disable_sort, void, private_message_t *this)
static void order_payloads (private_message_t *this)
static encrypted_payload_t * wrap_payloads (private_message_t *this)
static ike_header_t * create_header (private_message_t *this)
static status_t generate_message (private_message_t *this, keymat_t *keymat, generator_t **out_generator, encrypted_payload_t **encrypted)
static status_t finalize_message (private_message_t *this, keymat_t *keymat, generator_t *generator, encrypted_payload_t *encrypted)
METHOD (message_t, generate, status_t, private_message_t *this, keymat_t *keymat, packet_t **packet)
static message_t * clone_message (private_message_t *this)
static message_t * create_fragment (private_message_t *this, payload_type_t next, u_int16_t num, u_int16_t count, chunk_t data)
static void clear_fragments (private_message_t *this)
METHOD (message_t, fragment, status_t, private_message_t *this, keymat_t *keymat, size_t frag_len, enumerator_t **fragments)
METHOD (message_t, get_packet, packet_t *, private_message_t *this)
METHOD (message_t, get_packet_data, chunk_t, private_message_t *this)
METHOD (message_t, get_fragments, enumerator_t *, private_message_t *this)
METHOD (message_t, parse_header, status_t, private_message_t *this)
static bool is_connectivity_check (private_message_t *this, payload_t *payload)
static status_t parse_payloads (private_message_t *this)
static status_t decrypt_and_extract (private_message_t *this, keymat_t *keymat, payload_t *previous, encrypted_payload_t *encryption)
static status_t decrypt_fragment (private_message_t *this, keymat_t *keymat, encrypted_fragment_payload_t *fragment)
static bool accept_unencrypted_mm (private_message_t *this, payload_type_t type)
static status_t decrypt_payloads (private_message_t *this, keymat_t *keymat)
static status_t verify (private_message_t *this)
METHOD (message_t, parse_body, status_t, private_message_t *this, keymat_t *keymat)
static status_t add_fragment (private_message_t *this, u_int16_t num, chunk_t data)
static chunk_t merge_fragments (private_message_t *this, message_t *last)
METHOD (message_t, add_fragment_v1, status_t, private_message_t *this, message_t *message)
METHOD (message_t, add_fragment_v2, status_t, private_message_t *this, message_t *message)
METHOD (message_t, destroy, void, private_message_t *this)
message_t * message_create_from_packet (packet_t *packet)
message_t * message_create (int major, int minor)
message_t * message_create_defrag (message_t *fragment)
Variables
static payload_rule_t ike_sa_init_i_rules []
static payload_order_t ike_sa_init_i_order []
static payload_rule_t ike_sa_init_r_rules []
static payload_order_t ike_sa_init_r_order []
static payload_rule_t ike_auth_i_rules []
static payload_order_t ike_auth_i_order []
static payload_rule_t ike_auth_r_rules []
static payload_order_t ike_auth_r_order []
static payload_rule_t informational_i_rules []
static payload_order_t informational_i_order []
static payload_rule_t informational_r_rules []
static payload_order_t informational_r_order []
static payload_rule_t create_child_sa_i_rules []
static payload_order_t create_child_sa_i_order []
static payload_rule_t create_child_sa_r_rules []
static payload_order_t create_child_sa_r_order []
static message_rule_t message_rules []
Macro Definition Documentation
#define MAX_CERT_PAYLOADS 8
Max number of certificate payloads per IKEv2 message
Definition at line 54 of file message.c.
#define MAX_CERTREQ_PAYLOADS 20
Max number of certificate request payloads per IKEv1 message
Definition at line 64 of file message.c.
#define MAX_DELETE_PAYLOADS 20
Max number of delete payloads per IKEv2 message
Definition at line 49 of file message.c.
#define MAX_FRAGMENTS 255
Maximum number of fragments we will handle
Definition at line 948 of file message.c.
Referenced by METHOD().
#define MAX_NAT_D_PAYLOADS 10
Max number of NAT-D payloads per IKEv1 message
Definition at line 69 of file message.c.
#define MAX_NOTIFY_PAYLOADS 20
Max number of notify payloads per IKEv2 message
Definition at line 44 of file message.c.
#define MAX_VID_PAYLOADS 20
Max number of vendor ID payloads per IKEv2 message
Definition at line 59 of file message.c.
#define REDUCE_FRAG_LEN (fl, amount)
Value:
({ \
    fl = max(1, (ssize_t)fl - (amount)); \
})
Reduce the fragment length but ensure it stays > 0
Definition at line 1962 of file message.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_message_t private_message_t
Definition at line 846 of file message.c.
Function Documentation
static bool accept_unencrypted_mm (private_message_t * this, payload_type_t type) static
Do we accept unencrypted ID/HASH payloads in Main Mode, as seen from some SonicWall boxes?
Definition at line 2447 of file message.c.
References FALSE, settings_t::get_bool, ID_PROT, lib, library_t::ns, PLV1_HASH, PLV1_ID, and library_t::settings.
Referenced by decrypt_payloads().
 {
     if (this->exchange_type == ID_PROT)
     {
         if (type == PLV1_ID || type == PLV1_HASH)
         {
             return lib->settings->get_bool(lib->settings,
                                     "%s.accept_unencrypted_mainmode_messages",
                                     FALSE, lib->ns);
         }
     }
     return FALSE;
 }
static status_t add_fragment (private_message_t * this, u_int16_t num, chunk_t data) static
Store the fragment data for the fragment with the given fragment number.
Definition at line 2706 of file message.c.
References array_count(), array_get(), array_insert(), chunk_clone, DBG1, DBG_ENC, FAILED, INIT, chunk_t::len, NEED_MORE, fragment_t::num, reset_defrag(), and SUCCESS.
Referenced by METHOD().
 {
     fragment_t *fragment;
     int i, insert_at = -1;
     for (i = 0; i < array_count(this->fragments); i++)
     {
         array_get(this->fragments, i, &fragment);
         if (fragment->num == num)
         {
             /* ignore a duplicate fragment */
             DBG1(DBG_ENC, "received duplicate fragment #%hu", num);
             return NEED_MORE;
         }
         if (fragment->num > num)
         {
             insert_at = i;
             break;
         }
     }
     this->frag->len += data.len;
     if (this->frag->len > this->frag->max_packet)
     {
         DBG1(DBG_ENC, "fragmented IKE message is too large");
         reset_defrag(this);
         return FAILED;
     }
     INIT(fragment,
         .num = num,
         .data = chunk_clone(data),
     );
     array_insert(this->fragments, insert_at, fragment);
     return SUCCESS;
 }
static void clear_fragments (private_message_t * this) static
Destroy all fragments
Definition at line 1953 of file message.c.
References array_destroy_offset(), and destroy().
Referenced by METHOD().
 {
     array_destroy_offset(this->fragments, offsetof(packet_t, destroy));
     this->fragments = NULL;
 }
static message_t* clone_message (private_message_t * this) static
Creates a (basic) clone of the given message
Definition at line 1872 of file message.c.
References host_t::clone, dst, memcpy, message_create(), reserved, message_t::set_destination, message_t::set_exchange_type, message_t::set_ike_sa_id, message_t::set_message_id, message_t::set_request, message_t::set_source, and src.
Referenced by create_fragment(), and message_create_defrag().
 {
     message_t *message;
     host_t *src, *dst;
     src = this->packet->get_source(this->packet);
     dst = this->packet->get_destination(this->packet);
     message = message_create(this->major_version, this->minor_version);
     message->set_ike_sa_id(message, this->ike_sa_id);
     message->set_message_id(message, this->message_id);
     message->set_request(message, this->is_request);
     message->set_source(message, src->clone(src));
     message->set_destination(message, dst->clone(dst));
     message->set_exchange_type(message, this->exchange_type);
     memcpy(((private_message_t*)message)->reserved, this->reserved,
            sizeof(this->reserved));
     return message;
 }
static message_t* create_fragment (private_message_t * this, payload_type_t next, u_int16_t num, u_int16_t count, chunk_t data) static
Create a single fragment with the given data
Definition at line 1895 of file message.c.
References message_t::add_payload, AGGRESSIVE, daemon_t::bus, charon, clone_message(), enumerator_t::destroy, encrypted_fragment_payload_create_from_data(), enumerator_t::enumerate, fragment_payload_create_from_data(), ike_sa_t::get_peer_cfg, bus_t::get_sa, payload_t::get_type, ID_PROT, IKEV1_MAJOR_VERSION, PLV2_ENCRYPTED, message_t::set_exchange_type, message_t::set_message_id, payload_t::set_next_type, and peer_cfg_t::use_aggressive.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *fragment, *payload;
     message_t *message;
     peer_cfg_t *peer_cfg;
     ike_sa_t *ike_sa;
     message = clone_message(this);
     if (this->major_version == IKEV1_MAJOR_VERSION)
     {
         /* other implementations seem to just use 0 as message ID, so here we go */
         message->set_message_id(message, 0);
         /* always use the initial message type for fragments, even for quick mode
          * or transaction messages. */
         ike_sa = charon->bus->get_sa(charon->bus);
         if (ike_sa && (peer_cfg = ike_sa->get_peer_cfg(ike_sa)) &&
             peer_cfg->use_aggressive(peer_cfg))
         {
             message->set_exchange_type(message, AGGRESSIVE);
         }
         else
         {
             message->set_exchange_type(message, ID_PROT);
         }
         fragment = (payload_t*)fragment_payload_create_from_data(
                                                     num, num == count, data);
     }
     else
     {
         fragment = (payload_t*)encrypted_fragment_payload_create_from_data(
                                                     num, count, data);
         if (num == 1)
         {
             /* only in the first fragment is this set to the type of the first
              * payload in the encrypted payload */
             fragment->set_next_type(fragment, next);
             /* move unencrypted payloads to the first fragment */
             enumerator = this->payloads->create_enumerator(this->payloads);
             while (enumerator->enumerate(enumerator, &payload))
             {
                 if (payload->get_type(payload) != PLV2_ENCRYPTED)
                 {
                     this->payloads->remove_at(this->payloads, enumerator);
                     message->add_payload(message, payload);
                 }
             }
             enumerator->destroy(enumerator);
         }
     }
     message->add_payload(message, (payload_t*)fragment);
     return message;
 }
static ike_header_t* create_header (private_message_t * this) static
Creates the IKE header for this message
Definition at line 1611 of file message.c.
References countof, ike_header_t::get_initiator_spi, ike_header_t::get_responder_spi, ike_header_create_version(), IKEV2_MAJOR_VERSION, payload_get_field(), ike_header_t::payload_interface, reserved, RESERVED_BIT, ike_header_t::set_encryption_flag, ike_header_t::set_exchange_type, ike_header_t::set_initiator_flag, ike_header_t::set_initiator_spi, ike_header_t::set_message_id, ike_header_t::set_responder_spi, ike_header_t::set_response_flag, and ike_header_t::set_version_flag.
Referenced by generate_message().
 {
     ike_header_t *ike_header;
     bool *reserved;
     int i;
     ike_header = ike_header_create_version(this->major_version,
                                            this->minor_version);
     ike_header->set_exchange_type(ike_header, this->exchange_type);
     ike_header->set_message_id(ike_header, this->message_id);
     if (this->major_version == IKEV2_MAJOR_VERSION)
     {
         ike_header->set_response_flag(ike_header, !this->is_request);
         ike_header->set_version_flag(ike_header, this->version_flag);
         ike_header->set_initiator_flag(ike_header,
                         this->ike_sa_id->is_initiator(this->ike_sa_id));
     }
     else
     {
         ike_header->set_encryption_flag(ike_header, this->is_encrypted);
     }
     ike_header->set_initiator_spi(ike_header,
                         this->ike_sa_id->get_initiator_spi(this->ike_sa_id));
     ike_header->set_responder_spi(ike_header,
                         this->ike_sa_id->get_responder_spi(this->ike_sa_id));
     for (i = 0; i < countof(this->reserved); i++)
     {
         reserved = payload_get_field(&ike_header->payload_interface,
                                      RESERVED_BIT, i);
         if (reserved)
         {
             *reserved = this->reserved[i];
         }
     }
     return ike_header;
 }
static status_t decrypt_and_extract (private_message_t * this, keymat_t * keymat, payload_t * previous, encrypted_payload_t * encryption) static
Decrypt an encrypted payload and extract all contained payloads.
Definition at line 2317 of file message.c.
References aead, chunk_create(), chunk_empty, DBG1, DBG2, DBG_ENC, encrypted_payload_t::decrypt, FAILED, keymat_t::get_aead, aead_t::get_block_size, keymat_v1_t::get_iv, encrypted_payload_t::get_length, payload_t::get_type, keymat_t::get_version, IKEV1, INVALID_ARG, chunk_t::len, parser, payload_type_names, chunk_t::ptr, encrypted_payload_t::remove_payload, payload_t::set_next_type, encrypted_payload_t::set_transform, status, SUCCESS, TRUE, type, keymat_v1_t::update_iv, and VERIFY_ERROR.
Referenced by decrypt_payloads().
 {
     payload_t *encrypted;
     payload_type_t type;
     chunk_t chunk;
     aead_t *aead;
     size_t bs;
     status_t status = SUCCESS;
     if (!keymat)
     {
         DBG1(DBG_ENC, "found encrypted payload, but no keymat");
         return INVALID_ARG;
     }
     aead = keymat->get_aead(keymat, TRUE);
     if (!aead)
     {
         DBG1(DBG_ENC, "found encrypted payload, but no transform set");
         return INVALID_ARG;
     }
     if (!this->parser)
     {
         /* reassembled IKEv2 messages are already decrypted, we still call
          * decrypt() to parse the contained payloads */
         status = encryption->decrypt(encryption, chunk_empty);
     }
     else
     {
         bs = aead->get_block_size(aead);
         encryption->set_transform(encryption, aead);
         chunk = this->packet->get_data(this->packet);
         if (chunk.len < encryption->get_length(encryption) ||
             chunk.len < bs)
         {
             DBG1(DBG_ENC, "invalid payload length");
             return VERIFY_ERROR;
         }
         if (keymat->get_version(keymat) == IKEV1)
         {   /* instead of associated data we provide the IV, we also update
              * the IV with the last encrypted block */
             keymat_v1_t *keymat_v1 = (keymat_v1_t*)keymat;
             chunk_t iv;
             if (keymat_v1->get_iv(keymat_v1, this->message_id, &iv))
             {
                 status = encryption->decrypt(encryption, iv);
                 if (status == SUCCESS)
                 {
                     if (!keymat_v1->update_iv(keymat_v1, this->message_id,
                             chunk_create(chunk.ptr + chunk.len - bs, bs)))
                     {
                         status = FAILED;
                     }
                 }
             }
             else
             {
                 status = FAILED;
             }
         }
         else
         {
             chunk.len -= encryption->get_length(encryption);
             status = encryption->decrypt(encryption, chunk);
         }
     }
     if (status != SUCCESS)
     {
         return status;
     }
     while ((encrypted = encryption->remove_payload(encryption)))
     {
         type = encrypted->get_type(encrypted);
         if (previous)
         {
             previous->set_next_type(previous, type);
         }
         else
         {
             this->first_payload = type;
         }
         DBG2(DBG_ENC, "insert decrypted payload of type %N at end of list",
              payload_type_names, type);
         this->payloads->insert_last(this->payloads, encrypted);
         previous = encrypted;
     }
     return SUCCESS;
 }
static status_t decrypt_fragment (private_message_t * this, keymat_t * keymat, encrypted_fragment_payload_t * fragment) static
Decrypt an encrypted fragment payload.
Definition at line 2411 of file message.c.
References aead, DBG1, DBG_ENC, encrypted_payload_t::decrypt, keymat_t::get_aead, aead_t::get_block_size, encrypted_payload_t::get_length, INVALID_ARG, chunk_t::len, encrypted_payload_t::set_transform, TRUE, and VERIFY_ERROR.
Referenced by decrypt_payloads().
 {
     encrypted_payload_t *encrypted = (encrypted_payload_t*)fragment;
     chunk_t chunk;
     aead_t *aead;
     size_t bs;
     if (!keymat)
     {
         DBG1(DBG_ENC, "found encrypted fragment payload, but no keymat");
         return INVALID_ARG;
     }
     aead = keymat->get_aead(keymat, TRUE);
     if (!aead)
     {
         DBG1(DBG_ENC, "found encrypted fragment payload, but no transform set");
         return INVALID_ARG;
     }
     bs = aead->get_block_size(aead);
     encrypted->set_transform(encrypted, aead);
     chunk = this->packet->get_data(this->packet);
     if (chunk.len < encrypted->get_length(encrypted) ||
         chunk.len < bs)
     {
         DBG1(DBG_ENC, "invalid payload length");
         return VERIFY_ERROR;
     }
     chunk.len -= encrypted->get_length(encrypted);
     return encrypted->decrypt(encrypted, chunk);
 }
static status_t decrypt_payloads (private_message_t * this, keymat_t * keymat) static
Decrypt payload from the encrypted payload
Definition at line 2464 of file message.c.
References accept_unencrypted_mm(), AGGRESSIVE, DBG1, DBG2, DBG_ENC, decrypt_and_extract(), decrypt_fragment(), enumerator_t::destroy, encrypted_payload_t::destroy, payload_rule_t::encrypted, enumerator_t::enumerate, FAILED, get_payload_rule(), payload_t::get_type, is_connectivity_check(), payload_type_names, PL_UNKNOWN, PLV1_ENCRYPTED, PLV2_ENCRYPTED, PLV2_FRAGMENT, previous, status, SUCCESS, type, and VERIFY_ERROR.
Referenced by METHOD().
 {
     payload_t *payload, *previous = NULL;
     enumerator_t *enumerator;
     payload_rule_t *rule;
     payload_type_t type;
     status_t status = SUCCESS;
     char *was_encrypted = NULL;
     enumerator = this->payloads->create_enumerator(this->payloads);
     while (enumerator->enumerate(enumerator, &payload))
     {
         type = payload->get_type(payload);
         DBG2(DBG_ENC, "process payload of type %N", payload_type_names, type);
         if (type == PLV2_ENCRYPTED || type == PLV1_ENCRYPTED ||
             type == PLV2_FRAGMENT)
         {
             if (was_encrypted)
             {
                 DBG1(DBG_ENC, "%s can't contain other payloads of type %N",
                      was_encrypted, payload_type_names, type);
                 status = VERIFY_ERROR;
                 break;
             }
         }
         if (type == PLV2_ENCRYPTED || type == PLV1_ENCRYPTED)
         {
             encrypted_payload_t *encryption;
             DBG2(DBG_ENC, "found an encrypted payload");
             encryption = (encrypted_payload_t*)payload;
             this->payloads->remove_at(this->payloads, enumerator);
             if (enumerator->enumerate(enumerator, NULL))
             {
                 DBG1(DBG_ENC, "encrypted payload is not last payload");
                 encryption->destroy(encryption);
                 status = VERIFY_ERROR;
                 break;
             }
             status = decrypt_and_extract(this, keymat, previous, encryption);
             encryption->destroy(encryption);
             if (status != SUCCESS)
             {
                 break;
             }
             was_encrypted = "encrypted payload";
         }
         else if (type == PLV2_FRAGMENT)
         {
             encrypted_fragment_payload_t *fragment;
             DBG2(DBG_ENC, "found an encrypted fragment payload");
             fragment = (encrypted_fragment_payload_t*)payload;
             if (enumerator->enumerate(enumerator, NULL))
             {
                 DBG1(DBG_ENC, "encrypted fragment payload is not last payload");
                 status = VERIFY_ERROR;
                 break;
             }
             status = decrypt_fragment(this, keymat, fragment);
             if (status != SUCCESS)
             {
                 break;
             }
             was_encrypted = "encrypted fragment payload";
         }
         if (type != PL_UNKNOWN && !was_encrypted &&
             !is_connectivity_check(this, payload) &&
             this->exchange_type != AGGRESSIVE)
         {
             rule = get_payload_rule(this, type);
             if ((!rule || rule->encrypted) &&
                 !accept_unencrypted_mm(this, type))
             {
                 DBG1(DBG_ENC, "payload type %N was not encrypted",
                      payload_type_names, type);
                 status = FAILED;
                 break;
             }
         }
         previous = payload;
     }
     enumerator->destroy(enumerator);
     return status;
 }
static status_t finalize_message (private_message_t * this, keymat_t * keymat, generator_t * generator, encrypted_payload_t * encrypted) static
Encrypts and adds the encrypted payload (if any) to the payload list and finalizes the message generation. Destroys the given generator.
Definition at line 1788 of file message.c.
References aead, chunk_clone, chunk_create(), keymat_v1_t::confirm_iv, generator_t::destroy, encrypted_payload_t::destroy, encrypted_payload_t::encrypt, FAILED, FALSE, generator_t::generate_payload, keymat_t::get_aead, aead_t::get_block_size, generator_t::get_chunk, keymat_v1_t::get_iv, encrypted_payload_t::get_length, htoun32(), INFORMATIONAL_V1, INVALID_STATE, chunk_t::len, encrypted_payload_t::payload_interface, chunk_t::ptr, SUCCESS, and keymat_v1_t::update_iv.
Referenced by METHOD().
 {
     keymat_v1_t *keymat_v1 = (keymat_v1_t*)keymat;
     chunk_t chunk;
     u_int32_t *lenpos;
     if (encrypted)
     {
         if (this->is_encrypted)
         {   /* for IKEv1 instead of associated data we provide the IV */
             if (!keymat_v1->get_iv(keymat_v1, this->message_id, &chunk))
             {
                 generator->destroy(generator);
                 encrypted->destroy(encrypted);
                 return FAILED;
             }
         }
         else
         {   /* build associated data (without header of encrypted payload) */
             chunk = generator->get_chunk(generator, &lenpos);
             /* fill in length, including encrypted payload */
             htoun32(lenpos, chunk.len + encrypted->get_length(encrypted));
         }
         this->payloads->insert_last(this->payloads, encrypted);
         if (encrypted->encrypt(encrypted, this->message_id, chunk) != SUCCESS)
         {
             generator->destroy(generator);
             return INVALID_STATE;
         }
         generator->generate_payload(generator, &encrypted->payload_interface);
     }
     chunk = generator->get_chunk(generator, &lenpos);
     htoun32(lenpos, chunk.len);
     this->packet->set_data(this->packet, chunk_clone(chunk));
     if (this->is_encrypted && this->exchange_type != INFORMATIONAL_V1)
     {
         /* update the IV for the next IKEv1 message */
         chunk_t last_block;
         aead_t *aead;
         size_t bs;
         aead = keymat->get_aead(keymat, FALSE);
         bs = aead->get_block_size(aead);
         last_block = chunk_create(chunk.ptr + chunk.len - bs, bs);
         if (!keymat_v1->update_iv(keymat_v1, this->message_id, last_block) ||
             !keymat_v1->confirm_iv(keymat_v1, this->message_id))
         {
             generator->destroy(generator);
             return FAILED;
         }
     }
     generator->destroy(generator);
     return SUCCESS;
 }
static void fragment_destroy (fragment_t * this) static
Definition at line 963 of file message.c.
References chunk_free(), data, and free().
Referenced by reset_defrag().
 {
     chunk_free(&this->data);
     free(this);
 }
static status_t generate_message (private_message_t * this, keymat_t * keymat, generator_t ** out_generator, encrypted_payload_t ** encrypted) static
Generates the message, if needed, wraps the payloads in an encrypted payload.
The generator and the possible enrypted payload are returned. The latter is not yet encrypted (but the transform is set). It is also not added to the payload list (so unless there are unencrypted payloads that list will be empty afterwards).
Definition at line 1657 of file message.c.
References aead, BUF_LEN, chunk_empty, chunk_free(), create_header(), DBG1, DBG2, DBG_ENC, enumerator_t::destroy, ike_header_t::destroy, payload_rule_t::encrypted, enumerator_t::enumerate, EXCHANGE_TYPE_UNDEFINED, FALSE, generator_t::generate_payload, generator_create(), keymat_t::get_aead, keymat_v1_t::get_hash_phase2, get_message_rule(), get_payload_rule(), get_string(), payload_t::get_type, keymat_t::get_version, hash, hash_payload_create(), IKEV1, IKEV2_MAJOR_VERSION, INFORMATIONAL_V1, INVALID_STATE, next, NOT_SUPPORTED, order_payloads(), PL_NONE, PLV1_HASH, hash_payload_t::set_hash, payload_t::set_next_type, str, SUCCESS, TRUE, and wrap_payloads().
Referenced by METHOD().
 {
     keymat_v1_t *keymat_v1 = (keymat_v1_t*)keymat;
     generator_t *generator;
     payload_type_t next_type;
     enumerator_t *enumerator;
     aead_t *aead = NULL;
     chunk_t hash = chunk_empty;
     char str[BUF_LEN];
     ike_header_t *ike_header;
     payload_t *payload, *next;
     bool encrypting = FALSE;
     if (this->exchange_type == EXCHANGE_TYPE_UNDEFINED)
     {
         DBG1(DBG_ENC, "exchange type is not defined");
         return INVALID_STATE;
     }
     if (this->packet->get_source(this->packet) == NULL ||
         this->packet->get_destination(this->packet) == NULL)
     {
         DBG1(DBG_ENC, "source/destination not defined");
         return INVALID_STATE;
     }
     this->rule = get_message_rule(this);
     if (!this->rule)
     {
         DBG1(DBG_ENC, "no message rules specified for this message type");
         return NOT_SUPPORTED;
     }
     if (!this->sort_disabled)
     {
         order_payloads(this);
     }
     if (keymat && keymat->get_version(keymat) == IKEV1)
     {
         /* get a hash for this message, if any is required */
         if (keymat_v1->get_hash_phase2(keymat_v1, &this->public, &hash))
         {   /* insert a HASH payload as first payload */
             hash_payload_t *hash_payload;
             hash_payload = hash_payload_create(PLV1_HASH);
             hash_payload->set_hash(hash_payload, hash);
             this->payloads->insert_first(this->payloads, hash_payload);
             if (this->exchange_type == INFORMATIONAL_V1)
             {
                 this->is_encrypted = encrypting = TRUE;
             }
             chunk_free(&hash);
         }
     }
     if (this->major_version == IKEV2_MAJOR_VERSION)
     {
         encrypting = this->rule->encrypted;
     }
     else if (!encrypting)
     {
         /* If at least one payload requires encryption, encrypt the message.
          * If no key material is available, the flag will be reset below. */
         enumerator = this->payloads->create_enumerator(this->payloads);
         while (enumerator->enumerate(enumerator, (void**)&payload))
         {
             payload_rule_t *rule;
             rule = get_payload_rule(this, payload->get_type(payload));
             if (rule && rule->encrypted)
             {
                 this->is_encrypted = encrypting = TRUE;
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     DBG1(DBG_ENC, "generating %s", get_string(this, str, sizeof(str)));
     if (keymat)
     {
         aead = keymat->get_aead(keymat, FALSE);
     }
     if (aead && encrypting)
     {
         *encrypted = wrap_payloads(this);
         (*encrypted)->set_transform(*encrypted, aead);
     }
     else
     {
         DBG2(DBG_ENC, "not encrypting payloads");
         this->is_encrypted = FALSE;
     }
     /* generate all payloads with proper next type */
     *out_generator = generator = generator_create();
     ike_header = create_header(this);
     payload = (payload_t*)ike_header;
     enumerator = create_payload_enumerator(this);
     while (enumerator->enumerate(enumerator, &next))
     {
         payload->set_next_type(payload, next->get_type(next));
         generator->generate_payload(generator, payload);
         payload = next;
     }
     enumerator->destroy(enumerator);
     next_type = PL_NONE;
     if (this->is_encrypted)
     {   /* for encrypted IKEv1 messages */
         next_type = (*encrypted)->payload_interface.get_next_type(
                                                         (payload_t*)*encrypted);
     }
     else if (*encrypted)
     {   /* use proper IKEv2 encrypted (fragment) payload type */
         next_type = (*encrypted)->payload_interface.get_type(
                                                         (payload_t*)*encrypted);
     }
     payload->set_next_type(payload, next_type);
     generator->generate_payload(generator, payload);
     ike_header->destroy(ike_header);
     return SUCCESS;
 }
static message_rule_t* get_message_rule (private_message_t * this) static
Get the message rule that applies to this message
Definition at line 980 of file message.c.
References countof, and message_rule_t::is_request.
Referenced by generate_message(), and METHOD().
 {
     int i;
     for (i = 0; i < countof(message_rules); i++)
     {
         if ((this->exchange_type == message_rules[i].exchange_type) &&
             (this->is_request == message_rules[i].is_request))
         {
             return &message_rules[i];
         }
     }
     return NULL;
 }
static payload_rule_t* get_payload_rule (private_message_t * this, payload_type_t type) static
Look up a payload rule
Definition at line 998 of file message.c.
Referenced by decrypt_payloads(), generate_message(), and wrap_payloads().
 {
     int i;
     for (i = 0; i < this->rule->rule_count;i++)
     {
         if (this->rule->rules[i].type == type)
         {
             return &this->rule->rules[i];
         }
     }
     return NULL;
 }
static char* get_string (private_message_t * this, char * buf, int len) static
get a string representation of the message
Definition at line 1272 of file message.c.
References attributes, CFG_ACK, CFG_REPLY, CFG_REQUEST, CFG_SET, configuration_attribute_type_short_names, cp, cp_payload_t::create_attribute_enumerator, data, enumerator_t::destroy, eap_code_short_names, eap_type_short_names, enumerator_t::enumerate, exchange_type_names, FALSE, eap_payload_t::get_code, encrypted_fragment_payload_t::get_fragment_number, notify_payload_t::get_notification_data, notify_payload_t::get_notify_type, fragment_payload_t::get_number, encrypted_fragment_payload_t::get_total_fragments, configuration_attribute_t::get_type, unknown_payload_t::get_type, cp_payload_t::get_type, eap_payload_t::get_type, payload_t::get_type, fragment_payload_t::is_last, chunk_t::len, memset, MS_NOTIFY_STATUS, notify(), notify_type_short_names, payload_type_short_names, pfx, PL_UNKNOWN, PLV1_CONFIGURATION, PLV1_FRAGMENT, PLV1_NOTIFY, PLV2_CONFIGURATION, PLV2_EAP, PLV2_FRAGMENT, PLV2_NOTIFY, chunk_t::ptr, snprintf, TRUE, type, and untoh32().
Referenced by generate_message(), and METHOD().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     int written;
     char *pos = buf;
     memset(buf, 0, len);
     len--;
     written = snprintf(pos, len, "%N %s %u [",
                        exchange_type_names, this->exchange_type,
                        this->is_request ? "request" : "response",
                        this->message_id);
     if (written >= len || written < 0)
     {
         return "";
     }
     pos += written;
     len -= written;
     enumerator = create_payload_enumerator(this);
     while (enumerator->enumerate(enumerator, &payload))
     {
         written = snprintf(pos, len, " %N", payload_type_short_names,
                            payload->get_type(payload));
         if (written >= len || written < 0)
         {
             return buf;
         }
         pos += written;
         len -= written;
         if (payload->get_type(payload) == PLV2_NOTIFY ||
             payload->get_type(payload) == PLV1_NOTIFY)
         {
             notify_payload_t *notify;
             notify_type_t type;
             chunk_t data;
             notify = (notify_payload_t*)payload;
             type = notify->get_notify_type(notify);
             data = notify->get_notification_data(notify);
             if (type == MS_NOTIFY_STATUS && data.len == 4)
             {
                 written = snprintf(pos, len, "(%N(%d))", notify_type_short_names,
                                    type, untoh32(data.ptr));
             }
             else
             {
                 written = snprintf(pos, len, "(%N)", notify_type_short_names,
                                    type);
             }
             if (written >= len || written < 0)
             {
                 return buf;
             }
             pos += written;
             len -= written;
         }
         if (payload->get_type(payload) == PLV2_EAP)
         {
             eap_payload_t *eap = (eap_payload_t*)payload;
             u_int32_t vendor;
             eap_type_t type;
             char method[64] = "";
             type = eap->get_type(eap, &vendor);
             if (type)
             {
                 if (vendor)
                 {
                     snprintf(method, sizeof(method), "/%d-%d", type, vendor);
                 }
                 else
                 {
                     snprintf(method, sizeof(method), "/%N",
                              eap_type_short_names, type);
                 }
             }
             written = snprintf(pos, len, "/%N%s", eap_code_short_names,
                                eap->get_code(eap), method);
             if (written >= len || written < 0)
             {
                 return buf;
             }
             pos += written;
             len -= written;
         }
         if (payload->get_type(payload) == PLV2_CONFIGURATION ||
             payload->get_type(payload) == PLV1_CONFIGURATION)
         {
             cp_payload_t *cp = (cp_payload_t*)payload;
             enumerator_t *attributes;
             configuration_attribute_t *attribute;
             bool first = TRUE;
             char *pfx;
             switch (cp->get_type(cp))
             {
                 case CFG_REQUEST:
                     pfx = "RQ(";
                     break;
                 case CFG_REPLY:
                     pfx = "RP(";
                     break;
                 case CFG_SET:
                     pfx = "S(";
                     break;
                 case CFG_ACK:
                     pfx = "A(";
                     break;
                 default:
                     pfx = "(";
                     break;
             }
             attributes = cp->create_attribute_enumerator(cp);
             while (attributes->enumerate(attributes, &attribute))
             {
                 written = snprintf(pos, len, "%s%N", first ? pfx : " ",
                                    configuration_attribute_type_short_names,
                                    attribute->get_type(attribute));
                 if (written >= len || written < 0)
                 {
                     return buf;
                 }
                 pos += written;
                 len -= written;
                 first = FALSE;
             }
             attributes->destroy(attributes);
             if (!first)
             {
                 written = snprintf(pos, len, ")");
                 if (written >= len || written < 0)
                 {
                     return buf;
                 }
                 pos += written;
                 len -= written;
             }
         }
         if (payload->get_type(payload) == PLV1_FRAGMENT)
         {
             fragment_payload_t *frag;
             frag = (fragment_payload_t*)payload;
             if (frag->is_last(frag))
             {
                 written = snprintf(pos, len, "(%u/%u)",
                             frag->get_number(frag), frag->get_number(frag));
             }
             else
             {
                 written = snprintf(pos, len, "(%u)", frag->get_number(frag));
             }
             if (written >= len || written < 0)
             {
                 return buf;
             }
             pos += written;
             len -= written;
         }
         if (payload->get_type(payload) == PLV2_FRAGMENT)
         {
             encrypted_fragment_payload_t *frag;
             frag = (encrypted_fragment_payload_t*)payload;
             written = snprintf(pos, len, "(%u/%u)",
                                frag->get_fragment_number(frag),
                                frag->get_total_fragments(frag));
             if (written >= len || written < 0)
             {
                 return buf;
             }
             pos += written;
             len -= written;
         }
         if (payload->get_type(payload) == PL_UNKNOWN)
         {
             unknown_payload_t *unknown;
             unknown = (unknown_payload_t*)payload;
             written = snprintf(pos, len, "(%d)", unknown->get_type(unknown));
             if (written >= len || written < 0)
             {
                 return buf;
             }
             pos += written;
             len -= written;
         }
     }
     enumerator->destroy(enumerator);
     /* remove last space */
     snprintf(pos, len, " ]");
     return buf;
 }
static bool is_connectivity_check (private_message_t * this, payload_t * payload) static
Check if a payload is for a mediation extension connectivity check
Definition at line 2218 of file message.c.
References FALSE, notify_payload_t::get_notify_type, payload_t::get_type, INFORMATIONAL, ME_CONNECTAUTH, ME_CONNECTID, ME_ENDPOINT, notify(), PLV2_NOTIFY, and TRUE.
Referenced by decrypt_payloads().
 {
 #ifdef ME
     if (this->exchange_type == INFORMATIONAL &&
         payload->get_type(payload) == PLV2_NOTIFY)
     {
         notify_payload_t *notify = (notify_payload_t*)payload;
         switch (notify->get_notify_type(notify))
         {
             case ME_CONNECTID:
             case ME_ENDPOINT:
             case ME_CONNECTAUTH:
                 return TRUE;
             default:
                 break;
         }
     }
 #endif /* !ME */
     return FALSE;
 }
static chunk_t merge_fragments (private_message_t * this, message_t * last) static
Merge the cached fragment data and resets the defragmentation state. Also updates the IP addresses to those of the last received fragment.
Definition at line 2746 of file message.c.
References array_count(), array_get(), bio_writer_create(), host_t::clone, data, fragment_t::data, bio_writer_t::destroy, dst, bio_writer_t::extract_buf, free(), message_t::get_destination, message_t::get_source, reset_defrag(), src, and bio_writer_t::write_data.
Referenced by METHOD().
 {
     fragment_t *fragment;
     bio_writer_t *writer;
     host_t *src, *dst;
     chunk_t data;
     int i;
     writer = bio_writer_create(this->frag->len);
     for (i = 0; i < array_count(this->fragments); i++)
     {
         array_get(this->fragments, i, &fragment);
         writer->write_data(writer, fragment->data);
     }
     data = writer->extract_buf(writer);
     writer->destroy(writer);
     /* set addresses to those of the last fragment we received */
     src = last->get_source(last);
     dst = last->get_destination(last);
     this->packet->set_source(this->packet, src->clone(src));
     this->packet->set_destination(this->packet, dst->clone(dst));
     reset_defrag(this);
     free(this->frag);
     this->frag = NULL;
     return data;
 }
METHOD (message_t , set_ike_sa_id , void , private_message_t * this, ike_sa_id_t * ike_sa_id)
Definition at line 1013 of file message.c.
References ike_sa_id_t::clone, and DESTROY_IF.
 {
     DESTROY_IF(this->ike_sa_id);
     this->ike_sa_id = ike_sa_id->clone(ike_sa_id);
 }
METHOD (message_t , get_ike_sa_id , ike_sa_id_t * , private_message_t * this)
Definition at line 1020 of file message.c.
 {
     return this->ike_sa_id;
 }
METHOD (message_t , set_message_id , void , private_message_t * this, u_int32_t message_id)
Definition at line 1026 of file message.c.
 {
     this->message_id = message_id;
 }
METHOD (message_t , get_message_id , u_int32_t , private_message_t * this)
Definition at line 1032 of file message.c.
 {
     return this->message_id;
 }
METHOD (message_t , get_initiator_spi , u_int64_t , private_message_t * this)
Definition at line 1038 of file message.c.
 {
     return (this->ike_sa_id->get_initiator_spi(this->ike_sa_id));
 }
METHOD (message_t , get_responder_spi , u_int64_t , private_message_t * this)
Definition at line 1044 of file message.c.
 {
     return (this->ike_sa_id->get_responder_spi(this->ike_sa_id));
 }
METHOD (message_t , set_major_version , void , private_message_t * this, u_int8_t major_version)
Definition at line 1050 of file message.c.
 {
     this->major_version = major_version;
 }
METHOD (message_t , get_major_version , u_int8_t , private_message_t * this)
Definition at line 1056 of file message.c.
 {
     return this->major_version;
 }
METHOD (message_t , set_minor_version , void , private_message_t * this, u_int8_t minor_version)
Definition at line 1062 of file message.c.
 {
     this->minor_version = minor_version;
 }
METHOD (message_t , get_minor_version , u_int8_t , private_message_t * this)
Definition at line 1068 of file message.c.
 {
     return this->minor_version;
 }
METHOD (message_t , set_exchange_type , void , private_message_t * this, exchange_type_t exchange_type)
Definition at line 1074 of file message.c.
 {
     this->exchange_type = exchange_type;
 }
METHOD (message_t , get_exchange_type , exchange_type_t , private_message_t * this)
Definition at line 1080 of file message.c.
 {
     return this->exchange_type;
 }
METHOD (message_t , get_first_payload_type , payload_type_t , private_message_t * this)
Definition at line 1086 of file message.c.
 {
     return this->first_payload;
 }
METHOD (message_t , set_request , void , private_message_t * this, bool request)
Definition at line 1092 of file message.c.
References request().
 {
     this->is_request = request;
 }
METHOD (message_t , get_request , bool , private_message_t * this)
Definition at line 1098 of file message.c.
 {
     return this->is_request;
 }
METHOD (message_t , set_version_flag , void , private_message_t * this)
Definition at line 1104 of file message.c.
References TRUE.
 {
     this->version_flag = TRUE;
 }
METHOD (message_t , get_reserved_header_bit , bool , private_message_t * this, u_int nr)
Definition at line 1110 of file message.c.
References countof, FALSE, and reserved.
 {
     if (nr < countof(this->reserved))
     {
         return this->reserved[nr];
     }
     return FALSE;
 }
METHOD (message_t , set_reserved_header_bit , void , private_message_t * this, u_int nr)
Definition at line 1120 of file message.c.
References countof, reserved, and TRUE.
 {
     if (nr < countof(this->reserved))
     {
         this->reserved[nr] = TRUE;
     }
 }
METHOD (message_t , is_encoded , bool , private_message_t * this)
Definition at line 1129 of file message.c.
 {
     return this->packet->get_data(this->packet).ptr != NULL;
 }
METHOD (message_t , is_fragmented , bool , private_message_t * this)
Definition at line 1135 of file message.c.
References array_count().
 {
     return array_count(this->fragments) > 0;
 }
METHOD (message_t , add_payload , void , private_message_t * this, payload_t * payload)
Definition at line 1141 of file message.c.
References DBG2, DBG_ENC, payload_t::get_type, payload_type_names, PL_NONE, and payload_t::set_next_type.
 {
     payload_t *last_payload;
     if (this->payloads->get_count(this->payloads) > 0)
     {
         this->payloads->get_last(this->payloads, (void **)&last_payload);
         last_payload->set_next_type(last_payload, payload->get_type(payload));
     }
     else
     {
         this->first_payload = payload->get_type(payload);
     }
     payload->set_next_type(payload, PL_NONE);
     this->payloads->insert_last(this->payloads, payload);
     DBG2(DBG_ENC ,"added payload of type %N to message",
          payload_type_names, payload->get_type(payload));
 }
METHOD (message_t , add_notify , void , private_message_t * this, bool flush, notify_type_t type, chunk_t data)
Definition at line 1162 of file message.c.
References payload_t::destroy, IKEV2_MAJOR_VERSION, notify(), notify_payload_create(), PLV1_NOTIFY, PLV2_NOTIFY, notify_payload_t::set_notification_data, notify_payload_t::set_notify_type, and SUCCESS.
 {
     notify_payload_t *notify;
     payload_t *payload;
     if (flush)
     {
         while (this->payloads->remove_last(this->payloads,
                                                 (void**)&payload) == SUCCESS)
         {
             payload->destroy(payload);
         }
     }
     if (this->major_version == IKEV2_MAJOR_VERSION)
     {
         notify = notify_payload_create(PLV2_NOTIFY);
     }
     else
     {
         notify = notify_payload_create(PLV1_NOTIFY);
     }
     notify->set_notify_type(notify, type);
     notify->set_notification_data(notify, data);
     add_payload(this, (payload_t*)notify);
 }
METHOD (message_t , set_source , void , private_message_t * this, host_t * host)
Definition at line 1189 of file message.c.
 {
     this->packet->set_source(this->packet, host);
 }
METHOD (message_t , set_destination , void , private_message_t * this, host_t * host)
Definition at line 1195 of file message.c.
 {
     this->packet->set_destination(this->packet, host);
 }
METHOD (message_t , get_source , host_t * , private_message_t * this)
Definition at line 1201 of file message.c.
 {
     return this->packet->get_source(this->packet);
 }
METHOD (message_t , get_destination , host_t * , private_message_t * this)
Definition at line 1207 of file message.c.
 {
     return this->packet->get_destination(this->packet);
 }
METHOD (message_t , create_payload_enumerator , enumerator_t * , private_message_t * this)
Definition at line 1213 of file message.c.
 {
     return this->payloads->create_enumerator(this->payloads);
 }
METHOD (message_t , remove_payload_at , void , private_message_t * this, enumerator_t * enumerator)
Definition at line 1219 of file message.c.
 {
     this->payloads->remove_at(this->payloads, enumerator);
 }
METHOD (message_t , get_payload , payload_t * , private_message_t * this, payload_type_t type)
Definition at line 1225 of file message.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, payload_t::get_type, and type.
 {
     payload_t *current, *found = NULL;
     enumerator_t *enumerator;
     enumerator = create_payload_enumerator(this);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current->get_type(current) == type)
         {
             found = current;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (message_t , get_notify , notify_payload_t * , private_message_t * this, notify_type_t type)
Definition at line 1244 of file message.c.
References enumerator_t::destroy, enumerator_t::enumerate, notify_payload_t::get_notify_type, payload_t::get_type, notify(), PLV1_NOTIFY, PLV2_NOTIFY, and type.
 {
     enumerator_t *enumerator;
     notify_payload_t *notify = NULL;
     payload_t *payload;
     enumerator = create_payload_enumerator(this);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV2_NOTIFY ||
             payload->get_type(payload) == PLV1_NOTIFY)
         {
             notify = (notify_payload_t*)payload;
             if (notify->get_notify_type(notify) == type)
             {
                 break;
             }
             notify = NULL;
         }
     }
     enumerator->destroy(enumerator);
     return notify;
 }
METHOD (message_t , disable_sort , void , private_message_t * this)
Definition at line 1471 of file message.c.
References TRUE.
 {
     this->sort_disabled = TRUE;
 }
METHOD (message_t , generate , status_t , private_message_t * this, keymat_t * keymat, packet_t ** packet)
Definition at line 1844 of file message.c.
References packet_t::clone, DESTROY_IF, finalize_message(), generate_message(), status, and SUCCESS.
 {
     generator_t *generator = NULL;
     encrypted_payload_t *encrypted = NULL;
     status_t status;
     status = generate_message(this, keymat, &generator, &encrypted);
     if (status != SUCCESS)
     {
         DESTROY_IF(generator);
         return status;
     }
     status = finalize_message(this, keymat, generator, encrypted);
     if (status != SUCCESS)
     {
         return status;
     }
     if (packet)
     {
         *packet = this->packet->clone(this->packet);
     }
     return SUCCESS;
 }
METHOD (message_t , fragment , status_t , private_message_t * this, keymat_t * keymat, size_t frag_len, enumerator_t ** fragments)
Definition at line 1966 of file message.c.
References aead, array_create(), array_create_enumerator(), array_insert(), ARRAY_TAIL, chunk_create(), chunk_skip(), clear_fragments(), count, create_fragment(), data, DBG1, DBG_ENC, generator_t::destroy, encrypted_payload_t::destroy, message_t::destroy, DESTROY_IF, dst, enumerator_create_single(), FAILED, FALSE, finalize_message(), message_t::generate, generate_message(), encrypted_payload_t::generate_payloads, generator_create(), generator_create_no_dbg(), keymat_t::get_aead, aead_t::get_block_size, generator_t::get_chunk, packet_t::get_data, packet_t::get_destination, host_t::get_family, aead_t::get_icv_size, aead_t::get_iv_size, encrypted_payload_t::get_length, payload_t::get_next_type, host_t::get_port, packet_t::get_source, IKEV1_MAJOR_VERSION, IKEV2_MAJOR_VERSION, IKEV2_UDP_PORT, chunk_t::len, len, min, next, encrypted_payload_t::payload_interface, PL_NONE, PLV2_ENCRYPTED, chunk_t::ptr, REDUCE_FRAG_LEN, round_down(), src, status, and SUCCESS.
 {
     encrypted_payload_t *encrypted = NULL;
     generator_t *generator = NULL;
     message_t *fragment;
     packet_t *packet;
     payload_type_t next = PL_NONE;
     u_int16_t num, count;
     host_t *src, *dst;
     chunk_t data;
     status_t status;
     u_int32_t *lenpos;
     size_t len;
     src = this->packet->get_source(this->packet);
     dst = this->packet->get_destination(this->packet);
     if (!frag_len)
     {
         frag_len = (src->get_family(src) == AF_INET) ? 576 : 1280;
     }
     /* frag_len is the complete IP datagram length, account for overhead (we
      * assume no IP options/extension headers are used) */
     REDUCE_FRAG_LEN(frag_len, (src->get_family(src) == AF_INET) ? 20 : 40);
     /* 8 (UDP header) */
     REDUCE_FRAG_LEN(frag_len, 8);
     if (dst->get_port(dst) != IKEV2_UDP_PORT &&
         src->get_port(src) != IKEV2_UDP_PORT)
     {   /* reduce length due to non-ESP marker */
         REDUCE_FRAG_LEN(frag_len, 4);
     }
     if (is_encoded(this))
     {
         if (this->major_version == IKEV2_MAJOR_VERSION)
         {
             encrypted = (encrypted_payload_t*)get_payload(this, PLV2_ENCRYPTED);
         }
         data = this->packet->get_data(this->packet);
         len = data.len;
     }
     else
     {
         status = generate_message(this, keymat, &generator, &encrypted);
         if (status != SUCCESS)
         {
             DESTROY_IF(generator);
             return status;
         }
         data = generator->get_chunk(generator, &lenpos);
         len = data.len + (encrypted ? encrypted->get_length(encrypted) : 0);
     }
     /* check if we actually need to fragment the message and if we have an
      * encrypted payload for IKEv2 */
     if (len <= frag_len ||
        (this->major_version == IKEV2_MAJOR_VERSION && !encrypted))
     {
         if (generator)
         {
             status = finalize_message(this, keymat, generator, encrypted);
             if (status != SUCCESS)
             {
                 return status;
             }
         }
         *fragments = enumerator_create_single(this->packet, NULL);
         return SUCCESS;
     }
     /* frag_len denoted the maximum IKE message size so far, later on it will
      * denote the maximum content size of a fragment payload, therefore,
      * account for IKE header */
     REDUCE_FRAG_LEN(frag_len, 28);
     if (this->major_version == IKEV1_MAJOR_VERSION)
     {
         if (generator)
         {
             status = finalize_message(this, keymat, generator, encrypted);
             if (status != SUCCESS)
             {
                 return status;
             }
             data = this->packet->get_data(this->packet);
             generator = NULL;
         }
         /* overhead for the fragmentation payload header */
         REDUCE_FRAG_LEN(frag_len, 8);
     }
     else
     {
         aead_t *aead;
         if (generator)
         {
             generator->destroy(generator);
             generator = generator_create();
         }
         else
         {   /* do not log again if it was generated previously */
             generator = generator_create_no_dbg();
         }
         next = encrypted->payload_interface.get_next_type((payload_t*)encrypted);
         encrypted->generate_payloads(encrypted, generator);
         data = generator->get_chunk(generator, &lenpos);
         if (!is_encoded(this))
         {
             encrypted->destroy(encrypted);
         }
         aead = keymat->get_aead(keymat, FALSE);
         /* overhead for the encrypted fragment payload */
         REDUCE_FRAG_LEN(frag_len, aead->get_iv_size(aead));
         REDUCE_FRAG_LEN(frag_len, aead->get_icv_size(aead));
         /* header */
         REDUCE_FRAG_LEN(frag_len, 8);
         /* padding and padding length */
         frag_len = round_down(frag_len, aead->get_block_size(aead));
         REDUCE_FRAG_LEN(frag_len, 1);
         /* TODO-FRAG: if there are unencrypted payloads, should we account for
          * their length in the first fragment? we still would have to add
          * an encrypted fragment payload (albeit empty), even so we couldn't
          * prevent IP fragmentation in every case */
     }
     count = data.len / frag_len + (data.len % frag_len ? 1 : 0);
     this->fragments = array_create(0, count);
     DBG1(DBG_ENC, "splitting IKE message with length of %zu bytes into "
          "%hu fragments", len, count);
     for (num = 1; num <= count; num++)
     {
         len = min(data.len, frag_len);
         fragment = create_fragment(this, next, num, count,
                                    chunk_create(data.ptr, len));
         status = fragment->generate(fragment, keymat, &packet);
         fragment->destroy(fragment);
         if (status != SUCCESS)
         {
             DBG1(DBG_ENC, "failed to generate IKE fragment");
             clear_fragments(this);
             DESTROY_IF(generator);
             return FAILED;
         }
         array_insert(this->fragments, ARRAY_TAIL, packet);
         data = chunk_skip(data, len);
     }
     *fragments = array_create_enumerator(this->fragments);
     DESTROY_IF(generator);
     return SUCCESS;
 }
METHOD (message_t , get_packet , packet_t * , private_message_t * this)
Definition at line 2118 of file message.c.
 {
     return this->packet->clone(this->packet);
 }
METHOD (message_t , get_packet_data , chunk_t , private_message_t * this)
Definition at line 2124 of file message.c.
 {
     return this->packet->get_data(this->packet);
 }
METHOD (message_t , get_fragments , enumerator_t * , private_message_t * this)
Definition at line 2130 of file message.c.
References array_create_enumerator().
 {
     return array_create_enumerator(this->fragments);
 }
METHOD (message_t , parse_header , status_t , private_message_t * this)
Definition at line 2136 of file message.c.
References countof, DBG1, DBG2, DBG_ENC, ike_header_t::destroy, DESTROY_IF, exchange_type_names, FALSE, ike_header_t::get_encryption_flag, ike_header_t::get_exchange_type, ike_header_t::get_initiator_flag, ike_header_t::get_initiator_spi, ike_header_t::get_maj_version, ike_header_t::get_message_id, ike_header_t::get_min_version, payload_t::get_next_type, ike_header_t::get_responder_spi, ike_header_t::get_response_flag, ike_sa_id_create(), IKEV1_MAJOR_VERSION, IKEV2_MAJOR_VERSION, parser, payload_get_field(), ike_header_t::payload_interface, PL_HEADER, PLV1_FRAGMENT, reserved, RESERVED_BIT, status, SUCCESS, and payload_t::verify.
 {
     ike_header_t *ike_header;
     status_t status;
     bool *reserved;
     int i;
     DBG2(DBG_ENC, "parsing header of message");
     if (!this->parser)
     {   /* reassembled IKEv2 message, header is inherited from fragments */
         return SUCCESS;
     }
     this->parser->reset_context(this->parser);
     status = this->parser->parse_payload(this->parser, PL_HEADER,
                                          (payload_t**)&ike_header);
     if (status != SUCCESS)
     {
         DBG1(DBG_ENC, "header could not be parsed");
         return status;
     }
     status = ike_header->payload_interface.verify(
                                         &ike_header->payload_interface);
     if (status != SUCCESS)
     {
         DBG1(DBG_ENC, "header verification failed");
         ike_header->destroy(ike_header);
         return status;
     }
     DESTROY_IF(this->ike_sa_id);
     this->ike_sa_id = ike_sa_id_create(
                                     ike_header->get_maj_version(ike_header),
                                     ike_header->get_initiator_spi(ike_header),
                                     ike_header->get_responder_spi(ike_header),
                                     ike_header->get_initiator_flag(ike_header));
     this->exchange_type = ike_header->get_exchange_type(ike_header);
     this->message_id = ike_header->get_message_id(ike_header);
     this->major_version = ike_header->get_maj_version(ike_header);
     this->minor_version = ike_header->get_min_version(ike_header);
     if (this->major_version == IKEV2_MAJOR_VERSION)
     {
         this->is_request = !ike_header->get_response_flag(ike_header);
     }
     else
     {
         this->is_encrypted = ike_header->get_encryption_flag(ike_header);
     }
     this->first_payload = ike_header->payload_interface.get_next_type(
                                                 &ike_header->payload_interface);
     if (this->first_payload == PLV1_FRAGMENT && this->is_encrypted)
     {   /* racoon sets the encrypted bit when sending a fragment, but these
          * messages are really not encrypted */
         this->is_encrypted = FALSE;
     }
     for (i = 0; i < countof(this->reserved); i++)
     {
         reserved = payload_get_field(&ike_header->payload_interface,
                                      RESERVED_BIT, i);
         if (reserved)
         {
             this->reserved[i] = *reserved;
         }
     }
     ike_header->destroy(ike_header);
     this->parser->set_major_version(this->parser, this->major_version);
     DBG2(DBG_ENC, "parsed a %N %s header", exchange_type_names,
          this->exchange_type, this->major_version == IKEV1_MAJOR_VERSION ?
          "message" : (this->is_request ? "request" : "response"));
     return SUCCESS;
 }
METHOD (message_t , parse_body , status_t , private_message_t * this, keymat_t * keymat)
Definition at line 2612 of file message.c.
References BUF_LEN, chunk_equals_const(), chunk_free(), keymat_v1_t::confirm_iv, DBG1, DBG2, DBG3, DBG_ENC, decrypt_payloads(), exchange_type_names, FAILED, hash_payload_t::get_hash, keymat_v1_t::get_hash_phase2, get_message_rule(), get_string(), keymat_t::get_version, hash, IKEV1, INFORMATIONAL_V1, NOT_SUPPORTED, parse_payloads(), parser, payload_type_names, PLV1_HASH, status, str, SUCCESS, verify(), and VERIFY_ERROR.
 {
     status_t status = SUCCESS;
     char str[BUF_LEN];
     DBG2(DBG_ENC, "parsing body of message, first payload is %N",
          payload_type_names, this->first_payload);
     this->rule = get_message_rule(this);
     if (!this->rule)
     {
         DBG1(DBG_ENC, "no message rules specified for a %N %s",
              exchange_type_names, this->exchange_type,
              this->is_request ? "request" : "response");
         return NOT_SUPPORTED;
     }
     /* reassembled IKEv2 messages are already parsed (except for the payloads
      * contained in the encrypted payload, which are handled below) */
     if (this->parser)
     {
         status = parse_payloads(this);
         if (status != SUCCESS)
         {   /* error is already logged */
             return status;
         }
     }
     status = decrypt_payloads(this, keymat);
     if (status != SUCCESS)
     {
         DBG1(DBG_ENC, "could not decrypt payloads");
         return status;
     }
     status = verify(this);
     if (status != SUCCESS)
     {
         return status;
     }
     DBG1(DBG_ENC, "parsed %s", get_string(this, str, sizeof(str)));
     if (keymat && keymat->get_version(keymat) == IKEV1)
     {
         keymat_v1_t *keymat_v1 = (keymat_v1_t*)keymat;
         chunk_t hash;
         if (keymat_v1->get_hash_phase2(keymat_v1, &this->public, &hash))
         {
             hash_payload_t *hash_payload;
             chunk_t other_hash;
             if (this->first_payload != PLV1_HASH)
             {
                 if (this->exchange_type == INFORMATIONAL_V1)
                 {
                     DBG1(DBG_ENC, "ignoring unprotected INFORMATIONAL from %H",
                          this->packet->get_source(this->packet));
                 }
                 else
                 {
                     DBG1(DBG_ENC, "expected HASH payload as first payload");
                 }
                 chunk_free(&hash);
                 return VERIFY_ERROR;
             }
             hash_payload = (hash_payload_t*)get_payload(this, PLV1_HASH);
             other_hash = hash_payload->get_hash(hash_payload);
             DBG3(DBG_ENC, "HASH received %B\nHASH expected %B",
                  &other_hash, &hash);
             if (!chunk_equals_const(hash, other_hash))
             {
                 DBG1(DBG_ENC, "received HASH payload does not match");
                 chunk_free(&hash);
                 return FAILED;
             }
             chunk_free(&hash);
         }
         if (this->is_encrypted && this->exchange_type != INFORMATIONAL_V1)
         {   /* message verified, confirm IV */
             if (!keymat_v1->confirm_iv(keymat_v1, this->message_id))
             {
                 return FAILED;
             }
         }
     }
     return SUCCESS;
 }
METHOD (message_t , add_fragment_v1 , status_t , private_message_t * this, message_t * message)
Definition at line 2775 of file message.c.
References add_fragment(), array_count(), array_create(), data, DBG1, DBG_ENC, DBG_IKE, FAILED, fragment_payload_t::get_data, fragment_payload_t::get_id, fragment_payload_t::get_number, message_t::get_payload, INVALID_ARG, INVALID_STATE, fragment_payload_t::is_last, merge_fragments(), NEED_MORE, parser, parser_create(), PLV1_FRAGMENT, reset_defrag(), status, and SUCCESS.
 {
     fragment_payload_t *payload;
     chunk_t data;
     u_int8_t num;
     status_t status;
     if (!this->frag)
     {
         return INVALID_STATE;
     }
     payload = (fragment_payload_t*)message->get_payload(message, PLV1_FRAGMENT);
     if (!payload)
     {
         return INVALID_ARG;
     }
     if (!this->fragments || this->message_id != payload->get_id(payload))
     {
         reset_defrag(this);
         this->message_id = payload->get_id(payload);
         /* we don't know the total number of fragments, assume something */
         this->fragments = array_create(0, 4);
     }
     num = payload->get_number(payload);
     data = payload->get_data(payload);
     if (!this->frag->last && payload->is_last(payload))
     {
         this->frag->last = num;
     }
     status = add_fragment(this, num, data);
     if (status != SUCCESS)
     {
         return status;
     }
     if (array_count(this->fragments) != this->frag->last)
     {
         /* there are some fragments missing */
         DBG1(DBG_ENC, "received fragment #%hhu, waiting for complete IKE "
              "message", num);
         return NEED_MORE;
     }
     DBG1(DBG_ENC, "received fragment #%hhu, reassembling fragmented IKE "
          "message", num);
     data = merge_fragments(this, message);
     this->packet->set_data(this->packet, data);
     this->parser = parser_create(data);
     if (parse_header(this) != SUCCESS)
     {
         DBG1(DBG_IKE, "failed to parse header of reassembled IKE message");
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (message_t , add_fragment_v2 , status_t , private_message_t * this, message_t * message)
Definition at line 2835 of file message.c.
References add_fragment(), array_count(), array_create(), message_t::create_payload_enumerator, data, DBG1, DBG_ENC, DBG_IKE, enumerator_t::destroy, encrypted_payload_create_from_plain(), enumerator_t::enumerate, FAILED, encrypted_fragment_payload_t::get_content, encrypted_fragment_payload_t::get_fragment_number, message_t::get_message_id, payload_t::get_next_type, message_t::get_payload, encrypted_fragment_payload_t::get_total_fragments, payload_t::get_type, INVALID_ARG, INVALID_STATE, MAX_FRAGMENTS, merge_fragments(), NEED_MORE, PLV2_FRAGMENT, message_t::remove_payload_at, reset_defrag(), status, and SUCCESS.
 {
     encrypted_fragment_payload_t *encrypted_fragment;
     encrypted_payload_t *encrypted;
     payload_t *payload;
     enumerator_t *enumerator;
     chunk_t data;
     u_int16_t total, num;
     status_t status;
     if (!this->frag)
     {
         return INVALID_STATE;
     }
     payload = message->get_payload(message, PLV2_FRAGMENT);
     if (!payload || this->message_id != message->get_message_id(message))
     {
         return INVALID_ARG;
     }
     encrypted_fragment = (encrypted_fragment_payload_t*)payload;
     total = encrypted_fragment->get_total_fragments(encrypted_fragment);
     if (total > MAX_FRAGMENTS)
     {
         DBG1(DBG_IKE, "maximum fragment count exceeded");
         reset_defrag(this);
         return FAILED;
     }
     if (!this->fragments || total > this->frag->last)
     {
         reset_defrag(this);
         this->frag->last = total;
         this->fragments = array_create(0, total);
     }
     num = encrypted_fragment->get_fragment_number(encrypted_fragment);
     data = encrypted_fragment->get_content(encrypted_fragment);
     status = add_fragment(this, num, data);
     if (status != SUCCESS)
     {
         return status;
     }
     if (num == 1)
     {
         /* the first fragment denotes the payload type of the first payload in
          * the original encrypted payload, cache that */
         this->first_payload = payload->get_next_type(payload);
         /* move all unencrypted payloads contained in the first fragment */
         enumerator = message->create_payload_enumerator(message);
         while (enumerator->enumerate(enumerator, &payload))
         {
             if (payload->get_type(payload) != PLV2_FRAGMENT)
             {
                 message->remove_payload_at(message, enumerator);
                 this->payloads->insert_last(this->payloads, payload);
             }
         }
         enumerator->destroy(enumerator);
     }
     if (array_count(this->fragments) != total)
     {
         /* there are some fragments missing */
         DBG1(DBG_ENC, "received fragment #%hu of %hu, waiting for complete IKE "
              "message", num, total);
         return NEED_MORE;
     }
     DBG1(DBG_ENC, "received fragment #%hu of %hu, reassembling fragmented IKE "
          "message", num, total);
     data = merge_fragments(this, message);
     encrypted = encrypted_payload_create_from_plain(this->first_payload, data);
     this->payloads->insert_last(this->payloads, encrypted);
     /* update next payload type (could be an unencrypted payload) */
     this->payloads->get_first(this->payloads, (void**)&payload);
     this->first_payload = payload->get_type(payload);
     return SUCCESS;
 }
METHOD (message_t , destroy , void , private_message_t * this)
Definition at line 2915 of file message.c.
References array_destroy_offset(), destroy(), DESTROY_IF, free(), parser, and reset_defrag().
 {
     DESTROY_IF(this->ike_sa_id);
     DESTROY_IF(this->parser);
     this->payloads->destroy_offset(this->payloads, offsetof(payload_t, destroy));
     this->packet->destroy(this->packet);
     if (this->frag)
     {
         reset_defrag(this);
         free(this->frag);
     }
     else
     {
         array_destroy_offset(this->fragments, offsetof(packet_t, destroy));
     }
     free(this);
 }
static void order_payloads (private_message_t * this) static
reorder payloads depending on reordering rules
... and check notify for type.
Definition at line 1480 of file message.c.
References linked_list_t::create_enumerator, DBG1, DBG2, DBG_ENC, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, exchange_type_names, notify_payload_t::get_notify_type, payload_t::get_type, linked_list_t::insert_first, linked_list_create(), list, payload_order_t::notify, notify(), payload_type_names, PLV2_NOTIFY, linked_list_t::remove_at, linked_list_t::remove_last, SUCCESS, and payload_order_t::type.
Referenced by generate_message().
 {
     linked_list_t *list;
     payload_t *payload;
     int i;
     DBG2(DBG_ENC, "order payloads in message");
     /* move to temp list */
     list = linked_list_create();
     while (this->payloads->remove_last(this->payloads,
                                        (void**)&payload) == SUCCESS)
     {
         list->insert_first(list, payload);
     }
     /* for each rule, ... */
     for (i = 0; i < this->rule->order_count; i++)
     {
         enumerator_t *enumerator;
         notify_payload_t *notify;
         payload_order_t order;
         order = this->rule->order[i];
         /* ... find all payload ... */
         enumerator = list->create_enumerator(list);
         while (enumerator->enumerate(enumerator, &payload))
         {
             /* ... with that type ... */
             if (payload->get_type(payload) == order.type)
             {
                 notify = (notify_payload_t*)payload;
                 if (order.type != PLV2_NOTIFY || order.notify == 0 ||
                     order.notify == notify->get_notify_type(notify))
                 {
                     list->remove_at(list, enumerator);
                     add_payload(this, payload);
                 }
             }
         }
         enumerator->destroy(enumerator);
     }
     /* append all payloads without a rule to the end */
     while (list->remove_last(list, (void**)&payload) == SUCCESS)
     {
         /* do not complain about payloads in private use space */
         if (payload->get_type(payload) < 128)
         {
             DBG1(DBG_ENC, "payload %N has no ordering rule in %N %s",
                  payload_type_names, payload->get_type(payload),
                  exchange_type_names, this->rule->exchange_type,
                  this->rule->is_request ? "request" : "response");
         }
         add_payload(this, payload);
     }
     list->destroy(list);
 }
static status_t parse_payloads (private_message_t * this) static
Parses and verifies the unencrypted payloads contained in the message
Definition at line 2243 of file message.c.
References DBG1, DBG2, DBG_ENC, payload_t::destroy, payload_t::get_next_type, payload_t::get_type, PARSE_ERROR, parser, encrypted_payload_t::payload_interface, payload_type_names, PL_NONE, PL_UNKNOWN, PLV1_ENCRYPTED, PLV2_ENCRYPTED, PLV2_FRAGMENT, payload_t::set_next_type, status, SUCCESS, type, payload_t::verify, and VERIFY_ERROR.
Referenced by METHOD().
 {
     payload_type_t type = this->first_payload;
     payload_t *payload;
     status_t status;
     if (this->is_encrypted)
     {   /* wrap the whole encrypted IKEv1 message in a special encrypted
          * payload which is then handled just like a regular payload */
         encrypted_payload_t *encryption;
         status = this->parser->parse_payload(this->parser, PLV1_ENCRYPTED,
                                              (payload_t**)&encryption);
         if (status != SUCCESS)
         {
             DBG1(DBG_ENC, "failed to wrap encrypted IKEv1 message");
             return PARSE_ERROR;
         }
         encryption->payload_interface.set_next_type((payload_t*)encryption,
                                                     this->first_payload);
         this->payloads->insert_last(this->payloads, encryption);
         return SUCCESS;
     }
     while (type != PL_NONE)
     {
         DBG2(DBG_ENC, "starting parsing a %N payload",
              payload_type_names, type);
         status = this->parser->parse_payload(this->parser, type, &payload);
         if (status != SUCCESS)
         {
             DBG1(DBG_ENC, "payload type %N could not be parsed",
                  payload_type_names, type);
             return PARSE_ERROR;
         }
         DBG2(DBG_ENC, "verifying payload of type %N", payload_type_names, type);
         status = payload->verify(payload);
         if (status != SUCCESS)
         {
             DBG1(DBG_ENC, "%N payload verification failed",
                  payload_type_names, type);
             payload->destroy(payload);
             return VERIFY_ERROR;
         }
         if (payload->get_type(payload) == PL_UNKNOWN)
         {
             DBG2(DBG_ENC, "%N payload unknown or not allowed",
                  payload_type_names, type);
         }
         else
         {
             DBG2(DBG_ENC, "%N payload verified, adding to payload list",
                  payload_type_names, type);
         }
         this->payloads->insert_last(this->payloads, payload);
         /* an encrypted (fragment) payload MUST be the last one, so STOP here.
          * decryption is done later */
         if (type == PLV2_ENCRYPTED || type == PLV2_FRAGMENT)
         {
             DBG2(DBG_ENC, "%N payload found, stop parsing",
                  payload_type_names, type);
             break;
         }
         type = payload->get_next_type(payload);
     }
     return SUCCESS;
 }
static void reset_defrag (private_message_t * this) static
Definition at line 969 of file message.c.
References array_destroy_function(), and fragment_destroy().
Referenced by add_fragment(), merge_fragments(), and METHOD().
 {
     array_destroy_function(this->fragments, (void*)fragment_destroy, NULL);
     this->fragments = NULL;
     this->frag->last = 0;
     this->frag->len = 0;
 }
static status_t verify (private_message_t * this) static
Verify a message and all payload according to message/payload rules
Definition at line 2559 of file message.c.
References complete(), DBG1, DBG2, DBG_ENC, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, payload_t::get_type, payload_rule_t::max_occurence, payload_rule_t::min_occurence, payload_type_names, SUCCESS, payload_rule_t::sufficient, TRUE, type, payload_rule_t::type, and VERIFY_ERROR.
Referenced by METHOD().
 {
     bool complete = FALSE;
     int i;
     DBG2(DBG_ENC, "verifying message structure");
     /* check for payloads with wrong count */
     for (i = 0; i < this->rule->rule_count; i++)
     {
         enumerator_t *enumerator;
         payload_t *payload;
         payload_rule_t *rule;
         int found = 0;
         rule = &this->rule->rules[i];
         enumerator = create_payload_enumerator(this);
         while (enumerator->enumerate(enumerator, &payload))
         {
             payload_type_t type;
             type = payload->get_type(payload);
             if (type == rule->type)
             {
                 found++;
                 DBG2(DBG_ENC, "found payload of type %N",
                      payload_type_names, type);
                 if (found > rule->max_occurence)
                 {
                     DBG1(DBG_ENC, "payload of type %N more than %d times (%d) "
                          "occurred in current message", payload_type_names,
                          type, rule->max_occurence, found);
                     enumerator->destroy(enumerator);
                     return VERIFY_ERROR;
                 }
             }
         }
         enumerator->destroy(enumerator);
         if (!complete && found < rule->min_occurence)
         {
             DBG1(DBG_ENC, "payload of type %N not occurred %d times (%d)",
                  payload_type_names, rule->type, rule->min_occurence, found);
             return VERIFY_ERROR;
         }
         if (found && rule->sufficient)
         {
             complete = TRUE;
         }
     }
     return SUCCESS;
 }
static encrypted_payload_t* wrap_payloads (private_message_t * this) static
Wrap payloads in an encrypted payload
Definition at line 1543 of file message.c.
References encrypted_payload_t::add_payload, DBG2, DBG_ENC, linked_list_t::destroy, encrypt(), payload_rule_t::encrypted, encrypted_payload_create(), get_payload_rule(), payload_t::get_type, linked_list_t::insert_last, linked_list_create(), payload_type_names, PLV1_ENCRYPTED, PLV2_ENCRYPTED, PLV2_FRAGMENT, linked_list_t::remove_first, SUCCESS, TRUE, and type.
Referenced by generate_message().
 {
     encrypted_payload_t *encrypted = NULL;
     linked_list_t *payloads;
     payload_t *current;
     /* move all payloads to a temporary list */
     payloads = linked_list_create();
     while (this->payloads->remove_first(this->payloads,
                                         (void**)&current) == SUCCESS)
     {
         if (current->get_type(current) == PLV2_FRAGMENT)
         {   /* treat encrypted fragment payload as encrypted payload */
             encrypted = (encrypted_payload_t*)current;
         }
         else
         {
             payloads->insert_last(payloads, current);
         }
     }
     if (encrypted)
     {   /* simply adopt all the unencrypted payloads */
         this->payloads->destroy(this->payloads);
         this->payloads = payloads;
         return encrypted;
     }
     if (this->is_encrypted)
     {
         encrypted = encrypted_payload_create(PLV1_ENCRYPTED);
     }
     else
     {
         encrypted = encrypted_payload_create(PLV2_ENCRYPTED);
     }
     while (payloads->remove_first(payloads, (void**)&current) == SUCCESS)
     {
         payload_rule_t *rule;
         payload_type_t type;
         bool encrypt = TRUE;
         type = current->get_type(current);
         rule = get_payload_rule(this, type);
         if (rule)
         {
             encrypt = rule->encrypted;
         }
         if (encrypt || this->is_encrypted)
         {   /* encryption is forced for IKEv1 */
             DBG2(DBG_ENC, "insert payload %N into encrypted payload",
                  payload_type_names, type);
             encrypted->add_payload(encrypted, current);
         }
         else
         {
             DBG2(DBG_ENC, "insert payload %N unencrypted",
                  payload_type_names, type);
             add_payload(this, current);
         }
     }
     payloads->destroy(payloads);
     return encrypted;
 }
Variable Documentation
payload_order_t create_child_sa_i_order[] static
Initial value:
= {
    {PLV2_NOTIFY,                   REKEY_SA},
    {PLV2_NOTIFY,                   IPCOMP_SUPPORTED},
    {PLV2_NOTIFY,                   USE_TRANSPORT_MODE},
    {PLV2_NOTIFY,                   ESP_TFC_PADDING_NOT_SUPPORTED},
    {PLV2_NOTIFY,                   NON_FIRST_FRAGMENTS_ALSO},
    {PLV2_SECURITY_ASSOCIATION,     0},
    {PLV2_NONCE,                    0},
    {PLV2_KEY_EXCHANGE,             0},
    {PLV2_TS_INITIATOR,             0},
    {PLV2_TS_RESPONDER,             0},
    {PLV2_NOTIFY,                   0},
    {PLV2_FRAGMENT,                 0},
}
payload order for CREATE_CHILD_SA from initiator.
Definition at line 352 of file message.c.
payload_rule_t create_child_sa_i_rules[] static
Initial value:
= {
    {PLV2_FRAGMENT,                 0,  1,                      TRUE,   TRUE},
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    TRUE,   FALSE},
    {PLV2_SECURITY_ASSOCIATION,     1,  1,                      TRUE,   FALSE},
    {PLV2_NONCE,                    1,  1,                      TRUE,   FALSE},
    {PLV2_KEY_EXCHANGE,             0,  1,                      TRUE,   FALSE},
    {PLV2_TS_INITIATOR,             0,  1,                      TRUE,   FALSE},
    {PLV2_TS_RESPONDER,             0,  1,                      TRUE,   FALSE},
    {PLV2_CONFIGURATION,            0,  1,                      TRUE,   FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       TRUE,   FALSE},
}
Message rule for CREATE_CHILD_SA from initiator.
Definition at line 336 of file message.c.
payload_order_t create_child_sa_r_order[] static
Initial value:
= {
    {PLV2_NOTIFY,                   IPCOMP_SUPPORTED},
    {PLV2_NOTIFY,                   USE_TRANSPORT_MODE},
    {PLV2_NOTIFY,                   ESP_TFC_PADDING_NOT_SUPPORTED},
    {PLV2_NOTIFY,                   NON_FIRST_FRAGMENTS_ALSO},
    {PLV2_SECURITY_ASSOCIATION,     0},
    {PLV2_NONCE,                    0},
    {PLV2_KEY_EXCHANGE,             0},
    {PLV2_TS_INITIATOR,             0},
    {PLV2_TS_RESPONDER,             0},
    {PLV2_NOTIFY,                   ADDITIONAL_TS_POSSIBLE},
    {PLV2_NOTIFY,                   0},
    {PLV2_FRAGMENT,                 0},
}
payload order for CREATE_CHILD_SA from responder.
Definition at line 387 of file message.c.
payload_rule_t create_child_sa_r_rules[] static
Initial value:
= {
    {PLV2_FRAGMENT,                 0,  1,                      TRUE,   TRUE},
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    TRUE,   TRUE},
    {PLV2_SECURITY_ASSOCIATION,     1,  1,                      TRUE,   FALSE},
    {PLV2_NONCE,                    1,  1,                      TRUE,   FALSE},
    {PLV2_KEY_EXCHANGE,             0,  1,                      TRUE,   FALSE},
    {PLV2_TS_INITIATOR,             0,  1,                      TRUE,   FALSE},
    {PLV2_TS_RESPONDER,             0,  1,                      TRUE,   FALSE},
    {PLV2_CONFIGURATION,            0,  1,                      TRUE,   FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       TRUE,   FALSE},
}
Message rule for CREATE_CHILD_SA from responder.
Definition at line 371 of file message.c.
payload_order_t ike_auth_i_order[] static
Initial value:
= {
    {PLV2_ID_INITIATOR,             0},
    {PLV2_CERTIFICATE,              0},
    {PLV2_NOTIFY,                   INITIAL_CONTACT},
    {PLV2_NOTIFY,                   HTTP_CERT_LOOKUP_SUPPORTED},
    {PLV2_CERTREQ,                  0},
    {PLV2_ID_RESPONDER,             0},
    {PLV2_AUTH,                     0},
    {PLV2_EAP,                      0},
    {PLV2_CONFIGURATION,            0},
    {PLV2_NOTIFY,                   IPCOMP_SUPPORTED},
    {PLV2_NOTIFY,                   USE_TRANSPORT_MODE},
    {PLV2_NOTIFY,                   ESP_TFC_PADDING_NOT_SUPPORTED},
    {PLV2_NOTIFY,                   NON_FIRST_FRAGMENTS_ALSO},
    {PLV2_SECURITY_ASSOCIATION,     0},
    {PLV2_TS_INITIATOR,             0},
    {PLV2_TS_RESPONDER,             0},
    {PLV2_NOTIFY,                   MOBIKE_SUPPORTED},
    {PLV2_NOTIFY,                   ADDITIONAL_IP4_ADDRESS},
    {PLV2_NOTIFY,                   ADDITIONAL_IP6_ADDRESS},
    {PLV2_NOTIFY,                   NO_ADDITIONAL_ADDRESSES},
    {PLV2_NOTIFY,                   0},
    {PLV2_VENDOR_ID,                0},
    {PLV2_FRAGMENT,                 0},
}
payload order for IKE_AUTH initiator
Definition at line 207 of file message.c.
payload_rule_t ike_auth_i_rules[] static
Initial value:
= {
    {PLV2_FRAGMENT,                 0,  1,                      TRUE,   TRUE},
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    TRUE,   FALSE},
    {PLV2_EAP,                      0,  1,                      TRUE,   TRUE},
    {PLV2_AUTH,                     0,  1,                      TRUE,   TRUE},
    {PLV2_ID_INITIATOR,             0,  1,                      TRUE,   FALSE},
    {PLV2_CERTIFICATE,              0,  MAX_CERT_PAYLOADS,      TRUE,   FALSE},
    {PLV2_CERTREQ,                  0,  MAX_CERTREQ_PAYLOADS,   TRUE,   FALSE},
    {PLV2_ID_RESPONDER,             0,  1,                      TRUE,   FALSE},
    {PLV2_SECURITY_ASSOCIATION,     0,  1,                      TRUE,   FALSE},
    {PLV2_TS_INITIATOR,             0,  1,                      TRUE,   FALSE},
    {PLV2_TS_RESPONDER,             0,  1,                      TRUE,   FALSE},
    {PLV2_CONFIGURATION,            0,  1,                      TRUE,   FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       TRUE,   FALSE},
}
Message rule for IKE_AUTH from initiator.
Definition at line 181 of file message.c.
payload_order_t ike_auth_r_order[] static
Initial value:
= {
    {PLV2_ID_RESPONDER,             0},
    {PLV2_CERTIFICATE,              0},
    {PLV2_AUTH,                     0},
    {PLV2_EAP,                      0},
    {PLV2_CONFIGURATION,            0},
    {PLV2_NOTIFY,                   IPCOMP_SUPPORTED},
    {PLV2_NOTIFY,                   USE_TRANSPORT_MODE},
    {PLV2_NOTIFY,                   ESP_TFC_PADDING_NOT_SUPPORTED},
    {PLV2_NOTIFY,                   NON_FIRST_FRAGMENTS_ALSO},
    {PLV2_SECURITY_ASSOCIATION,     0},
    {PLV2_TS_INITIATOR,             0},
    {PLV2_TS_RESPONDER,             0},
    {PLV2_NOTIFY,                   AUTH_LIFETIME},
    {PLV2_NOTIFY,                   MOBIKE_SUPPORTED},
    {PLV2_NOTIFY,                   ADDITIONAL_IP4_ADDRESS},
    {PLV2_NOTIFY,                   ADDITIONAL_IP6_ADDRESS},
    {PLV2_NOTIFY,                   NO_ADDITIONAL_ADDRESSES},
    {PLV2_NOTIFY,                   0},
    {PLV2_VENDOR_ID,                0},
    {PLV2_FRAGMENT,                 0},
}
payload order for IKE_AUTH responder
Definition at line 255 of file message.c.
payload_rule_t ike_auth_r_rules[] static
Initial value:
= {
    {PLV2_FRAGMENT,                 0,  1,                      TRUE,   TRUE},
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    TRUE,   TRUE},
    {PLV2_EAP,                      0,  1,                      TRUE,   TRUE},
    {PLV2_AUTH,                     0,  1,                      TRUE,   TRUE},
    {PLV2_CERTIFICATE,              0,  MAX_CERT_PAYLOADS,      TRUE,   FALSE},
    {PLV2_ID_RESPONDER,             0,  1,                      TRUE,   FALSE},
    {PLV2_SECURITY_ASSOCIATION,     0,  1,                      TRUE,   FALSE},
    {PLV2_TS_INITIATOR,             0,  1,                      TRUE,   FALSE},
    {PLV2_TS_RESPONDER,             0,  1,                      TRUE,   FALSE},
    {PLV2_CONFIGURATION,            0,  1,                      TRUE,   FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       TRUE,   FALSE},
}
Message rule for IKE_AUTH from responder.
Definition at line 237 of file message.c.
payload_order_t ike_sa_init_i_order[] static
Initial value:
= {
    {PLV2_NOTIFY,                   COOKIE},
    {PLV2_SECURITY_ASSOCIATION,     0},
    {PLV2_KEY_EXCHANGE,             0},
    {PLV2_NONCE,                    0},
    {PLV2_NOTIFY,                   NAT_DETECTION_SOURCE_IP},
    {PLV2_NOTIFY,                   NAT_DETECTION_DESTINATION_IP},
    {PLV2_NOTIFY,                   0},
    {PLV2_VENDOR_ID,                0},
}
payload order for IKE_SA_INIT initiator
Definition at line 137 of file message.c.
payload_rule_t ike_sa_init_i_rules[] static
Initial value:
= {
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    FALSE,  FALSE},
    {PLV2_SECURITY_ASSOCIATION,     1,  1,                      FALSE,  FALSE},
    {PLV2_KEY_EXCHANGE,             1,  1,                      FALSE,  FALSE},
    {PLV2_NONCE,                    1,  1,                      FALSE,  FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       FALSE,  FALSE},
}
Message rule for IKE_SA_INIT from initiator.
Definition at line 125 of file message.c.
payload_order_t ike_sa_init_r_order[] static
Initial value:
= {
    {PLV2_SECURITY_ASSOCIATION,     0},
    {PLV2_KEY_EXCHANGE,             0},
    {PLV2_NONCE,                    0},
    {PLV2_NOTIFY,                   NAT_DETECTION_SOURCE_IP},
    {PLV2_NOTIFY,                   NAT_DETECTION_DESTINATION_IP},
    {PLV2_NOTIFY,                   HTTP_CERT_LOOKUP_SUPPORTED},
    {PLV2_CERTREQ,                  0},
    {PLV2_NOTIFY,                   0},
    {PLV2_VENDOR_ID,                0},
}
payload order for IKE_SA_INIT responder
Definition at line 165 of file message.c.
payload_rule_t ike_sa_init_r_rules[] static
Initial value:
= {
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    FALSE,  TRUE},
    {PLV2_SECURITY_ASSOCIATION,     1,  1,                      FALSE,  FALSE},
    {PLV2_KEY_EXCHANGE,             1,  1,                      FALSE,  FALSE},
    {PLV2_NONCE,                    1,  1,                      FALSE,  FALSE},
    {PLV2_CERTREQ,                  0,  MAX_CERTREQ_PAYLOADS,   FALSE,  FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       FALSE,  FALSE},
}
Message rule for IKE_SA_INIT from responder.
Definition at line 152 of file message.c.
payload_order_t informational_i_order[] static
Initial value:
= {
    {PLV2_NOTIFY,                   UPDATE_SA_ADDRESSES},
    {PLV2_NOTIFY,                   NAT_DETECTION_SOURCE_IP},
    {PLV2_NOTIFY,                   NAT_DETECTION_DESTINATION_IP},
    {PLV2_NOTIFY,                   COOKIE2},
    {PLV2_NOTIFY,                   0},
    {PLV2_DELETE,                   0},
    {PLV2_CONFIGURATION,            0},
    {PLV2_FRAGMENT,                 0},
}
payload order for INFORMATIONAL initiator
Definition at line 294 of file message.c.
payload_rule_t informational_i_rules[] static
Initial value:
= {
    {PLV2_FRAGMENT,                 0,  1,                      TRUE,   TRUE},
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    TRUE,   FALSE},
    {PLV2_CONFIGURATION,            0,  1,                      TRUE,   FALSE},
    {PLV2_DELETE,                   0,  MAX_DELETE_PAYLOADS,    TRUE,   FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       TRUE,   FALSE},
}
Message rule for INFORMATIONAL from initiator.
Definition at line 282 of file message.c.
payload_order_t informational_r_order[] static
Initial value:
= {
    {PLV2_NOTIFY,                   UPDATE_SA_ADDRESSES},
    {PLV2_NOTIFY,                   NAT_DETECTION_SOURCE_IP},
    {PLV2_NOTIFY,                   NAT_DETECTION_DESTINATION_IP},
    {PLV2_NOTIFY,                   COOKIE2},
    {PLV2_NOTIFY,                   0},
    {PLV2_DELETE,                   0},
    {PLV2_CONFIGURATION,            0},
    {PLV2_FRAGMENT,                 0},
}
payload order for INFORMATIONAL responder
Definition at line 321 of file message.c.
payload_rule_t informational_r_rules[] static
Initial value:
= {
    {PLV2_FRAGMENT,                 0,  1,                      TRUE,   TRUE},
    {PLV2_NOTIFY,                   0,  MAX_NOTIFY_PAYLOADS,    TRUE,   FALSE},
    {PLV2_CONFIGURATION,            0,  1,                      TRUE,   FALSE},
    {PLV2_DELETE,                   0,  MAX_DELETE_PAYLOADS,    TRUE,   FALSE},
    {PLV2_VENDOR_ID,                0,  MAX_VID_PAYLOADS,       TRUE,   FALSE},
}
Message rule for INFORMATIONAL from responder.
Definition at line 309 of file message.c.
message_rule_t message_rules[] static
Message rules, defines allowed payloads.
Definition at line 733 of file message.c.