strongSwan: eap_dynamic
eap_dynamic
eap_dynamic
Classes
struct eap_dynamic_t
Typedefs
typedef struct eap_dynamic_t eap_dynamic_t
Functions
eap_dynamic_t * eap_dynamic_create (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_dynamic_t eap_dynamic_t
Definition at line 24 of file eap_dynamic.h.
Function Documentation
eap_dynamic_t* eap_dynamic_create (identification_t * server, identification_t * peer)
Create a dynamic EAP proxy serving any supported real method which is also supported (or selected) by the client.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_dynamic_t object
Definition at line 357 of file eap_dynamic.c.
References identification_t::clone, FALSE, settings_t::get_bool, settings_t::get_str, get_supported_eap_types(), handle_preferred_eap_types(), INIT, lib, linked_list_create(), library_t::ns, and library_t::settings.
Referenced by METHOD().
 {
     private_eap_dynamic_t *this;
     char *preferred;
     INIT(this,
         .public = {
             .interface = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .destroy = _destroy,
             },
         },
         .peer = peer->clone(peer),
         .server = server->clone(server),
         .types = linked_list_create(),
         .prefer_peer = lib->settings->get_bool(lib->settings,
                         "%s.plugins.eap-dynamic.prefer_peer", FALSE, lib->ns),
     );
     /* get all supported EAP methods */
     get_supported_eap_types(this);
     /* move preferred methods to the front */
     preferred = lib->settings->get_str(lib->settings,
                         "%s.plugins.eap-dynamic.preferred", NULL, lib->ns);
     if (preferred)
     {
         handle_preferred_eap_types(this, preferred);
     }
     return &this->public;
 }