strongSwan: message
message
encoding
Classes
struct message_t
Typedefs
typedef struct message_t message_t
Functions
message_t * message_create_from_packet (packet_t *packet)
message_t * message_create (int major, int minor)
message_t * message_create_defrag (message_t *fragment)
Detailed Description
Typedef Documentation
typedef struct message_t message_t
Definition at line 27 of file message.h.
Function Documentation
message_t* message_create (int major, int minor)
Creates an empty message_t object for a specific major/minor version.
exchange_type is set to NOT_SET
original_initiator is set to TRUE
is_request is set to TRUE
Parameters
major major IKE version of this message
minor minor IKE version of this message
Returns
message_t object
Definition at line 2998 of file message.c.
References message_create_from_packet(), and packet_create().
Referenced by build_response(), clone_message(), METHOD(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), and START_TEST().
 {
     message_t *this = message_create_from_packet(packet_create());
     this->set_major_version(this, major);
     this->set_minor_version(this, minor);
     return this;
 }
message_t* message_create_defrag (message_t * fragment)
Creates a message_t object that is used to reassemble fragmented messages.
Use add_fragment() to add fragments.
Parameters
fragment initial fragment (is not added)
Returns
message_t object, NULL if fragment is not actually one
Definition at line 3011 of file message.c.
References clone_message(), conf_parser_t::destroy, settings_t::get_int, message_t::get_major_version, message_t::get_payload, IKEV1_MAJOR_VERSION, INIT, lib, library_t::ns, PACKET_MAX_DEFAULT, parser, PLV1_FRAGMENT, PLV2_FRAGMENT, and library_t::settings.
Referenced by handle_fragment().
 {
     private_message_t *this;
     if (!fragment->get_payload(fragment, PLV1_FRAGMENT) &&
         !fragment->get_payload(fragment, PLV2_FRAGMENT))
     {
         return NULL;
     }
     this = (private_message_t*)clone_message((private_message_t*)fragment);
     /* we don't need a parser for IKEv2, the one for IKEv1 is created after
      * reassembling the original message */
     this->parser->destroy(this->parser);
     this->parser = NULL;
     if (fragment->get_major_version(fragment) == IKEV1_MAJOR_VERSION)
     {
         /* we store the fragment ID in the message ID field, which should be
          * zero for fragments, but make sure */
         this->message_id = 0;
         this->public.add_fragment = _add_fragment_v1;
     }
     INIT(this->frag,
         .max_packet = lib->settings->get_int(lib->settings,
                                 "%s.max_packet", PACKET_MAX_DEFAULT, lib->ns),
     );
     return &this->public;
 }
message_t* message_create_from_packet (packet_t * packet)
Creates a message_t object from an incoming UDP packet.
The given packet gets owned by the message. The message is uninitialized, call parse_header() to populate header fields.
Parameters
packet packet_t object which is assigned to message
Returns
message_t object
Definition at line 2937 of file message.c.
References EXCHANGE_TYPE_UNDEFINED, packet_t::get_data, INIT, linked_list_create(), parser_create(), PL_NONE, and TRUE.
Referenced by message_create(), METHOD(), queue_message(), and receive_packets().
 {
     private_message_t *this;
     INIT(this,
         .public = {
             .set_major_version = _set_major_version,
             .get_major_version = _get_major_version,
             .set_minor_version = _set_minor_version,
             .get_minor_version = _get_minor_version,
             .set_message_id = _set_message_id,
             .get_message_id = _get_message_id,
             .get_initiator_spi = _get_initiator_spi,
             .get_responder_spi = _get_responder_spi,
             .set_ike_sa_id = _set_ike_sa_id,
             .get_ike_sa_id = _get_ike_sa_id,
             .set_exchange_type = _set_exchange_type,
             .get_exchange_type = _get_exchange_type,
             .get_first_payload_type = _get_first_payload_type,
             .set_request = _set_request,
             .get_request = _get_request,
             .set_version_flag = _set_version_flag,
             .get_reserved_header_bit = _get_reserved_header_bit,
             .set_reserved_header_bit = _set_reserved_header_bit,
             .add_payload = _add_payload,
             .add_notify = _add_notify,
             .disable_sort = _disable_sort,
             .generate = _generate,
             .is_encoded = _is_encoded,
             .is_fragmented = _is_fragmented,
             .fragment = _fragment,
             .add_fragment = _add_fragment_v2,
             .set_source = _set_source,
             .get_source = _get_source,
             .set_destination = _set_destination,
             .get_destination = _get_destination,
             .create_payload_enumerator = _create_payload_enumerator,
             .remove_payload_at = _remove_payload_at,
             .get_payload = _get_payload,
             .get_notify = _get_notify,
             .parse_header = _parse_header,
             .parse_body = _parse_body,
             .get_packet = _get_packet,
             .get_packet_data = _get_packet_data,
             .get_fragments = _get_fragments,
             .destroy = _destroy,
         },
         .exchange_type = EXCHANGE_TYPE_UNDEFINED,
         .is_request = TRUE,
         .first_payload = PL_NONE,
         .packet = packet,
         .payloads = linked_list_create(),
         .parser = parser_create(packet->get_data(packet)),
     );
     return &this->public;
 }