strongSwan: child_create_t Struct Reference
child_create_t Struct Reference
child_create
#include "child_create.h"
Public Attributes
task_t task
void(* use_reqid)(child_create_t *this, u_int32_t reqid)
void(* use_marks)(child_create_t *this, u_int in, u_int out)
chunk_t(* get_lower_nonce)(child_create_t *this)
child_sa_t *(* get_child)(child_create_t *this)
void(* set_config)(child_create_t *this, child_cfg_t *cfg)
Detailed Description
Task of type TASK_CHILD_CREATE, established a new CHILD_SA.
This task may be included in the IKE_AUTH message or in a separate CREATE_CHILD_SA exchange.
Definition at line 37 of file child_create.h.
Member Data Documentation
child_sa_t*(* child_create_t::get_child)(child_create_t *this)
Get the CHILD_SA established/establishing by this task.
Returns
child_sa
Definition at line 74 of file child_create.h.
Referenced by handle_collision(), and METHOD().
chunk_t(* child_create_t::get_lower_nonce)(child_create_t *this)
Get the lower of the two nonces, used for rekey collisions.
Returns
lower nonce
Definition at line 67 of file child_create.h.
Referenced by handle_collision().
void(* child_create_t::set_config)(child_create_t *this, child_cfg_t *cfg)
Enforce a specific CHILD_SA config as responder.
Parameters
cfg configuration to enforce, reference gets owned
Definition at line 81 of file child_create.h.
task_t child_create_t::task
Implements the task_t interface
Definition at line 42 of file child_create.h.
Referenced by METHOD().
void(* child_create_t::use_marks)(child_create_t *this, u_int in, u_int out)
Use specific mark values to override configuration.
Parameters
in inbound mark value
out outbound mark value
Definition at line 60 of file child_create.h.
void(* child_create_t::use_reqid)(child_create_t *this, u_int32_t reqid)
Use a specific reqid for the CHILD_SA.
When this task is used for rekeying, the same reqid is used for the new CHILD_SA.
Parameters
reqid reqid to use
Definition at line 52 of file child_create.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
child_create.h