strongSwan: pacman.c File Reference
pacman.c File Reference
#include <getopt.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <syslog.h>
#include <time.h>
#include <sys/stat.h>
#include "imv_os_state.h"
#include <library.h>
#include <utils/debug.h>
Classes
struct stats_t
Macros
#define _GNU_SOURCE
Typedefs
typedef enum pacman_state_t pacman_state_t
typedef struct stats_t stats_t
Enumerations
enum pacman_state_t { PACMAN_STATE_BEGIN_PACKAGE, PACMAN_STATE_VERSION, PACMAN_STATE_END_PACKAGE }
Functions
static void pacman_dbg (debug_t group, level_t level, char *fmt,...)
static void cleanup (void)
static void usage (void)
static bool update_database (database_t *db, char *package, char *version, bool security, stats_t *stats)
static void process_packages (char *filename, char *product, bool security)
static void do_args (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
static int debug_level = 1
static bool stderr_quiet = TRUE
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file pacman.c.
Typedef Documentation
typedef enum pacman_state_t pacman_state_t
Definition at line 31 of file pacman.c.
typedef struct stats_t stats_t
Definition at line 39 of file pacman.c.
Enumeration Type Documentation
enum pacman_state_t
Enumerator
PACMAN_STATE_BEGIN_PACKAGE
PACMAN_STATE_VERSION
PACMAN_STATE_END_PACKAGE
Definition at line 33 of file pacman.c.
                     {
     PACMAN_STATE_BEGIN_PACKAGE,
     PACMAN_STATE_VERSION,
     PACMAN_STATE_END_PACKAGE
 };
Function Documentation
static void cleanup (void) static
atexit handler to close everything on shutdown
Definition at line 99 of file pacman.c.
References library_deinit().
Referenced by main().
 {
     closelog();
     library_deinit();
 }
static void do_args (int argc, char * argv[]) static
Definition at line 425 of file pacman.c.
References c, FALSE, process_packages(), TRUE, and usage().
Referenced by main().
 {
     char *filename = NULL, *product = NULL;
     bool security = FALSE;
     /* reinit getopt state */
     optind = 0;
     while (TRUE)
     {
         int c;
         struct option long_opts[] = {
             { "help", no_argument, NULL, 'h' },
             { "file", required_argument, NULL, 'f' },
             { "product", required_argument, NULL, 'p' },
             { "security", no_argument, NULL, 's' },
             { 0,0,0,0 }
         };
         c = getopt_long(argc, argv, "", long_opts, NULL);
         switch (c)
         {
             case EOF:
                 break;
             case 'h':
                 usage();
                 exit(EXIT_SUCCESS);
             case 'f':
                 filename = optarg;
                 continue;
             case 'p':
                 product = optarg;
                 continue;
             case 's':
                 security = TRUE;
                 continue;
         }
         break;
     }
     if (filename && product)
     {
         process_packages(filename, product, security);
     }
     else
     {
         usage();
         exit(EXIT_FAILURE);
     }
 }
int main (int argc, char * argv[])
Definition at line 477 of file pacman.c.
References cleanup(), dbg, do_args(), settings_t::get_str, lib, library_init(), plugin_loader_t::load, pacman_dbg(), library_t::plugins, library_t::settings, SS_RC_INITIALIZATION_FAILED, and SS_RC_LIBSTRONGSWAN_INTEGRITY.
 {
     /* enable attest debugging hook */
     dbg = pacman_dbg;
     openlog("pacman", 0, LOG_DEBUG);
     atexit(cleanup);
     /* initialize library */
     if (!library_init(NULL, "pacman"))
     {
         exit(SS_RC_LIBSTRONGSWAN_INTEGRITY);
     }
     if (!lib->plugins->load(lib->plugins,
             lib->settings->get_str(lib->settings, "pacman.load", "sqlite")))
     {
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     do_args(argc, argv);
     exit(EXIT_SUCCESS);
 }
static void pacman_dbg (debug_t group, level_t level, char * fmt, ...) static
pacman dbg function
Definition at line 60 of file pacman.c.
References debug_level, fprintf, next, stderr_quiet, vfprintf, and vsnprintf.
Referenced by main().
 {
     int priority = LOG_INFO;
     char buffer[8192];
     char *current = buffer, *next;
     va_list args;
     if (level <= debug_level)
     {
         if (!stderr_quiet)
         {
             va_start(args, fmt);
             vfprintf(stderr, fmt, args);
             fprintf(stderr, "\n");
             va_end(args);
         }
         /* write in memory buffer first */
         va_start(args, fmt);
         vsnprintf(buffer, sizeof(buffer), fmt, args);
         va_end(args);
         /* do a syslog with every line */
         while (current)
         {
             next = strchr(current, '\n');
             if (next)
             {
                 *(next++) = '\0';
             }
             syslog(priority, "%s\n", current);
             current = next;
         }
     }
 }
static void process_packages (char * filename, char * product, bool security) static
Process a package file and store updates in the database
Definition at line 282 of file pacman.c.
References BUF_LEN, database_factory_t::create, db, library_t::db, DB_INT, DB_TEXT, database_t::destroy, database_t::execute, fprintf, free(), settings_t::get_str, lib, memset, PACMAN_STATE_BEGIN_PACKAGE, PACMAN_STATE_END_PACKAGE, PACMAN_STATE_VERSION, printf, database_t::query, library_t::settings, stats(), strndup(), update_database(), uri, and version.
Referenced by do_args().
 {
     char *uri, line[BUF_LEN], *pos, *package = NULL, *version = NULL;
     pacman_state_t pacman_state;
     enumerator_t *e;
     database_t *db;
     int pid;
     FILE *file;
     stats_t stats;
     bool success;
     /* initialize statistics */
     memset(&stats, 0x00, sizeof(stats_t));
     /* Set release date to current time */
     stats.release = time(NULL);
     /* opening package file */
     printf("loading\"%s\"\n", filename);
     file = fopen(filename, "r");
     if (!file)
     {
         fprintf(stderr, "could not open \"%s\"\n", filename);
         exit(EXIT_FAILURE);
     }
     /* connect package database */
     uri = lib->settings->get_str(lib->settings, "pacman.database", NULL);
     if (!uri)
     {
         fprintf(stderr, "database URI pacman.database not set\n");
         fclose(file);
         exit(EXIT_FAILURE);
     }
     db = lib->db->create(lib->db, uri);
     if (!db)
     {
         fprintf(stderr, "could not connect to database '%s'\n", uri);
         fclose(file);
         exit(EXIT_FAILURE);
     }
     /* check if product is already in database */
     e = db->query(db, "SELECT id FROM products WHERE name = ?",
                   DB_TEXT, product, DB_INT);
     if (e)
     {
         if (e->enumerate(e, &pid))
         {
             stats.product = pid;
         }
         e->destroy(e);
     }
     if (!stats.product)
     {
         if (db->execute(db, &pid, "INSERT INTO products (name) VALUES (?)",
                         DB_TEXT, product) != 1)
         {
             fprintf(stderr, "could not store product '%s' to database\n",
                              product);
             fclose(file);
             db->destroy(db);
             exit(EXIT_FAILURE);
         }
         stats.product = pid;
     }
     pacman_state = PACMAN_STATE_BEGIN_PACKAGE;
     while (fgets(line, sizeof(line), file))
     {
         /* set read pointer to beginning of line */
         pos = line;
         switch (pacman_state)
         {
             case PACMAN_STATE_BEGIN_PACKAGE:
                 pos = strstr(pos, "Package: ");
                 if (!pos)
                 {
                     continue;
                 }
                 pos += 9;
                 package = pos;
                 pos = strchr(pos, '\n');
                 if (pos)
                 {
                     package = strndup(package, pos - package);
                     pacman_state = PACMAN_STATE_VERSION;
                 }
                 break;
             case PACMAN_STATE_VERSION:
                 pos = strstr(pos, "Version: ");
                 if (!pos)
                 {
                     continue;
                 }
                 pos += 9;
                 version = pos;
                 pos = strchr(pos, '\n');
                 if (pos)
                 {
                     version = strndup(version, pos - version);
                     pacman_state = PACMAN_STATE_END_PACKAGE;
                 }
                 break;
             case PACMAN_STATE_END_PACKAGE:
                 if (*pos != '\n')
                 {
                     continue;
                 }
                 success = update_database(db, package, version, security, &stats);
                 free(package);
                 free(version);
                 if (!success)
                 {
                     fclose(file);
                     db->destroy(db);
                     exit(EXIT_FAILURE);
                 }
                 pacman_state = PACMAN_STATE_BEGIN_PACKAGE;
         }
     }
     switch (pacman_state)
     {
         case PACMAN_STATE_END_PACKAGE:
             free(version);
             /* fall-through */
         case PACMAN_STATE_VERSION:
             free(package);
             break;
         default:
             break;
     }
     fclose(file);
     db->destroy(db);
     printf("processed %d packages, %d new packages, %d new versions, "
            "%d updated versions, %d deleted versions\n",
             stats.packages, stats.new_packages, stats.new_versions,
             stats.updated_versions, stats.deleted_versions);
 }
static bool update_database (database_t * db, char * package, char * version, bool security, stats_t * stats) static
Update the package database
Definition at line 120 of file pacman.c.
References DB_INT, DB_TEXT, DB_UINT, stats_t::deleted_versions, enumerator_t::destroy, enumerator_t::enumerate, database_t::execute, FALSE, fprintf, free(), stats_t::new_packages, stats_t::new_versions, stats_t::packages, printf, stats_t::product, database_t::query, stats_t::release, strdup, streq(), TRUE, and stats_t::updated_versions.
Referenced by process_packages().
 {
     char *cur_version, *version_update = NULL, *version_delete = NULL;
     int cur_security, security_update = 0, security_delete = 0;
     int pac_id = 0, vid = 0, vid_update = 0, vid_delete = 0;
     u_int cur_time;
     bool add_version = TRUE;
     enumerator_t *e;
     /* increment package count */
     stats->packages++;
     /* check if package is already in database */
     e = db->query(db, "SELECT id FROM packages WHERE name = ?",
                       DB_TEXT, package, DB_INT);
     if (!e)
     {
         return FALSE;
     }
     if (!e->enumerate(e, &pac_id))
     {
         pac_id = 0;
     }
     e->destroy(e);
     if (!pac_id && security)
     {
         if (db->execute(db, &pac_id, "INSERT INTO packages (name) VALUES (?)",
                         DB_TEXT, package) != 1)
         {
             fprintf(stderr, "could not store package '%s' to database\n",
                              package);
             return FALSE;
         }
         stats->new_packages++;
     }
     /* check for package versions already in database */
     e = db->query(db,
             "SELECT id, release, security, time FROM versions "
             "WHERE package = ? AND product = ?", DB_INT, pac_id,
              DB_INT, stats->product, DB_INT, DB_TEXT, DB_INT, DB_UINT);
     if (!e)
     {
         return FALSE;
     }
     while (e->enumerate(e, &vid, &cur_version, &cur_security, &cur_time))
     {
         if (streq(version, cur_version))
         {
             /* already in data base */
             add_version = FALSE;
             break;
         }
         else if (stats->release >= cur_time)
         {
             if (security)
             {
                 if (cur_security)
                 {
                     vid_update = vid;
                     version_update = strdup(cur_version);
                     security_update = cur_security;
                 }
                 else
                 {
                     vid_delete = vid;
                     version_delete = strdup(cur_version);
                     security_delete = cur_security;
                 }
             }
             else
             {
                 if (!cur_security)
                 {
                     vid_update = vid;
                     version_update = strdup(cur_version);
                     security_update = cur_security;
                 }
             }
         }
         else
         {
             if (security == cur_security)
             {
                 add_version = FALSE;
             }
         }
     }
     e->destroy(e);
     if ((!vid && !security) || (vid && !add_version))
     {
         free(version_update);
         free(version_delete);
         return TRUE;
     }
     if ((!vid && security) || (vid && !vid_update))
     {
         printf("%s (%s) %s\n", package, version, security ? "[s]" : "");
         if (db->execute(db, &vid,
             "INSERT INTO versions "
             "(package, product, release, security, time) "
             "VALUES (?, ?, ?, ?, ?)", DB_INT, pac_id, DB_INT, stats->product,
             DB_TEXT, version, DB_INT, security, DB_INT, stats->release) != 1)
         {
             fprintf(stderr, "could not store version '%s' to database\n",
                              version);
             free(version_update);
             free(version_delete);
             return FALSE;
         }
         stats->new_versions++;
     }
     else
     {
         printf("%s (%s) %s updated by\n",
                package, version_update, security_update ? "[s]" : "");
         printf("%s (%s) %s\n", package, version, security ? "[s]" : "");
         if (db->execute(db, NULL,
             "UPDATE versions SET release = ?, time = ? WHERE id = ?",
             DB_TEXT, version, DB_INT, stats->release, DB_INT, vid_update) <= 0)
         {
             fprintf(stderr, "could not update version '%s' to database\n",
                              version);
             free(version_update);
             free(version_delete);
             return FALSE;
         }
         stats->updated_versions++;
     }
     if (vid_delete)
     {
         printf("%s (%s) %s deleted\n",
                package, version_delete, security_delete ? "[s]" : "");
             if (db->execute(db, NULL,
             "DELETE FROM  versions WHERE id = ?",
             DB_INT, vid_delete) <= 0)
         {
             fprintf(stderr, "could not delete version '%s' from database\n",
                              version_delete);
             free(version_update);
             free(version_delete);
             return FALSE;
         }
         stats->deleted_versions++;
     }
     free(version_update);
     free(version_delete);
     return TRUE;
 }
static void usage (void) static
Definition at line 105 of file pacman.c.
References printf.
Referenced by do_args().
 {
     printf("Parses package information files from Debian/Ubuntu repositories and\n");
     printf("stores the extracted information in the database used by the OS IMV.\n\n");
     printf("ipsec pacman --product <name> --file <filename> [--security]\n\n");
     printf("  --help               print usage information\n");
     printf("  --product <name>     name of the Debian/Ubuntu release, as stored in the DB\n");
     printf("  --file <filename>    package information file to parse\n");
     printf("  --security           set this when parsing a file with security updates\n");
     printf("\n");
 }
Variable Documentation
int debug_level = 1 static
global debug output variables
Definition at line 54 of file pacman.c.
Referenced by pacman_dbg().
bool stderr_quiet = TRUE static
Definition at line 55 of file pacman.c.
Referenced by pacman_dbg().