strongSwan: tls_prf.c File Reference
tls_prf.c File Reference
#include "tls_prf.h"
Classes
struct private_tls_prf12_t
struct private_tls_prf10_t
Typedefs
typedef struct private_tls_prf12_t private_tls_prf12_t
typedef struct private_tls_prf10_t private_tls_prf10_t
Functions
METHOD (tls_prf_t, set_key12, bool, private_tls_prf12_t *this, chunk_t key)
static bool p_hash (prf_t *prf, char *label, chunk_t seed, size_t block_size, size_t bytes, char *out)
METHOD (tls_prf_t, get_bytes12, bool, private_tls_prf12_t *this, char *label, chunk_t seed, size_t bytes, char *out)
METHOD (tls_prf_t, destroy12, void, private_tls_prf12_t *this)
tls_prf_t * tls_prf_create_12 (pseudo_random_function_t prf)
METHOD (tls_prf_t, set_key10, bool, private_tls_prf10_t *this, chunk_t key)
METHOD (tls_prf_t, get_bytes10, bool, private_tls_prf10_t *this, char *label, chunk_t seed, size_t bytes, char *out)
METHOD (tls_prf_t, destroy10, void, private_tls_prf10_t *this)
tls_prf_t * tls_prf_create_10 (pseudo_random_function_t prf)
Typedef Documentation
typedef struct private_tls_prf10_t private_tls_prf10_t
Definition at line 122 of file tls_prf.c.
typedef struct private_tls_prf12_t private_tls_prf12_t
Definition at line 18 of file tls_prf.c.
Function Documentation
METHOD (tls_prf_t , set_key12 , bool , private_tls_prf12_t * this, chunk_t key)
Definition at line 36 of file tls_prf.c.
References prf.
 {
     return this->prf->set_key(this->prf, key);
 }
METHOD (tls_prf_t , get_bytes12 , bool , private_tls_prf12_t * this, char * label, chunk_t seed, size_t bytes, char * out)
Definition at line 83 of file tls_prf.c.
References bytes, out, p_hash(), and prf.
 {
     return p_hash(this->prf, label, seed, this->prf->get_block_size(this->prf),
                   bytes, out);
 }
METHOD (tls_prf_t , destroy12 , void , private_tls_prf12_t * this)
Definition at line 91 of file tls_prf.c.
References free(), and prf.
 {
     this->prf->destroy(this->prf);
     free(this);
 }
METHOD (tls_prf_t , set_key10 , bool , private_tls_prf10_t * this, chunk_t key)
Definition at line 145 of file tls_prf.c.
References chunk_create(), chunk_t::len, len, chunk_t::ptr, and sha1().
 {
     size_t len = key.len / 2 + key.len % 2;
     return this->md5->set_key(this->md5, chunk_create(key.ptr, len)) &&
            this->sha1->set_key(this->sha1, chunk_create(key.ptr + key.len - len,
                                                         len));
 }
METHOD (tls_prf_t , get_bytes10 , bool , private_tls_prf10_t * this, char * label, chunk_t seed, size_t bytes, char * out)
Definition at line 155 of file tls_prf.c.
References bytes, FALSE, memxor(), out, p_hash(), sha1(), and TRUE.
 {
     char buf[bytes];
     if (!p_hash(this->md5, label, seed, this->md5->get_block_size(this->md5),
                 bytes, out) ||
         !p_hash(this->sha1, label, seed, this->sha1->get_block_size(this->sha1),
                 bytes, buf))
     {
         return FALSE;
     }
     memxor(out, buf, bytes);
     return TRUE;
 }
METHOD (tls_prf_t , destroy10 , void , private_tls_prf10_t * this)
Definition at line 172 of file tls_prf.c.
References DESTROY_IF, free(), and sha1().
 {
     DESTROY_IF(this->md5);
     DESTROY_IF(this->sha1);
     free(this);
 }
static bool p_hash (prf_t * prf, char * label, chunk_t seed, size_t block_size, size_t bytes, char * out) static
The P_hash function as in TLS 1.0/1.2
Definition at line 45 of file tls_prf.c.
References a, block_size, chunk_cata, chunk_create(), chunk_from_thing, FALSE, prf_t::get_bytes, memcpy, and TRUE.
Referenced by METHOD().
 {
     char buf[block_size], abuf[block_size];
     chunk_t a;
     /* seed = label + seed */
     seed = chunk_cata("cc", chunk_create(label, strlen(label)), seed);
     /* A(0) = seed */
     a = seed;
     while (TRUE)
     {
         /* A(i) = HMAC_hash(secret, A(i-1)) */
         if (!prf->get_bytes(prf, a, abuf))
         {
             return FALSE;
         }
         a = chunk_from_thing(abuf);
         /* HMAC_hash(secret, A(i) + seed) */
         if (!prf->get_bytes(prf, a, NULL) ||
             !prf->get_bytes(prf, seed, buf))
         {
             return FALSE;
         }
         if (bytes <= block_size)
         {
             memcpy(out, buf, bytes);
             break;
         }
         memcpy(out, buf, block_size);
         out += block_size;
         bytes -= block_size;
     }
     return TRUE;
 }
tls_prf_t* tls_prf_create_10 (pseudo_random_function_t prf)
See header
Definition at line 183 of file tls_prf.c.
References crypto_factory_t::create_prf, library_t::crypto, INIT, lib, PRF_HMAC_MD5, PRF_HMAC_SHA1, and sha1().
Referenced by create_ciphers().
 {
     private_tls_prf10_t *this;
     INIT(this,
         .public = {
             .set_key = _set_key10,
             .get_bytes = _get_bytes10,
             .destroy = _destroy10,
         },
         .md5 = lib->crypto->create_prf(lib->crypto, PRF_HMAC_MD5),
         .sha1 = lib->crypto->create_prf(lib->crypto, PRF_HMAC_SHA1),
     );
     if (!this->md5 || !this->sha1)
     {
         destroy10(this);
         return NULL;
     }
     return &this->public;
 }