strongSwan: id_payload
id_payload
payloads
Classes
struct id_payload_t
Typedefs
typedef struct id_payload_t id_payload_t
Functions
id_payload_t * id_payload_create (payload_type_t type)
id_payload_t * id_payload_create_from_identification (payload_type_t type, identification_t *id)
id_payload_t * id_payload_create_from_ts (traffic_selector_t *ts)
Detailed Description
Typedef Documentation
typedef struct id_payload_t id_payload_t
Definition at line 26 of file id_payload.h.
Function Documentation
id_payload_t* id_payload_create (payload_type_t type)
Creates an empty id_payload_t object.
Parameters
type one of PLV2_ID_INITIATOR, PLV2_ID_RESPONDER, PLV1_ID and PLV1_NAT_OA
Returns
id_payload_t object
Definition at line 353 of file id_payload.c.
References INIT, PL_NONE, and type.
Referenced by id_payload_create_from_identification(), id_payload_create_from_ts(), and payload_create().
 {
     private_id_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_identification = _get_identification,
             .get_encoded = _get_encoded,
             .get_ts = _get_ts,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
         .type = type,
     );
     return &this->public;
 }
id_payload_t* id_payload_create_from_identification (payload_type_t type, identification_t * id)
Creates an id_payload_t from an existing identification_t object.
Parameters
type one of PLV2_ID_INITIATOR, PLV2_ID_RESPONDER, PLV1_ID and PLV1_NAT_OA
id identification_t object
Returns
id_payload_t object
Definition at line 384 of file id_payload.c.
References chunk_clone, identification_t::get_encoding, and id_payload_create().
Referenced by add_nat_oa_payloads(), METHOD(), and process_auth_response().
 {
     private_id_payload_t *this;
     this = (private_id_payload_t*)id_payload_create(type);
     this->id_data = chunk_clone(id->get_encoding(id));
     this->id_type = id->get_type(id);
     this->payload_length += this->id_data.len;
     return &this->public;
 }
id_payload_t* id_payload_create_from_ts (traffic_selector_t * ts)
Create an IKEv1 ID_ADDR_SUBNET/RANGE identity from a traffic selector.
Parameters
ts traffic selector
Returns
PLV1_ID id_paylad_t object.
Definition at line 400 of file id_payload.c.
References chunk_cat, chunk_clone, chunk_create(), host_t::destroy, host_t::get_address, traffic_selector_t::get_from_address, traffic_selector_t::get_from_port, traffic_selector_t::get_protocol, traffic_selector_t::get_to_address, traffic_selector_t::get_type, ID_IPV4_ADDR, ID_IPV4_ADDR_RANGE, ID_IPV4_ADDR_SUBNET, ID_IPV6_ADDR, ID_IPV6_ADDR_RANGE, ID_IPV6_ADDR_SUBNET, id_payload_create(), traffic_selector_t::is_host, len, mask, memset, net, PLV1_ID, port, traffic_selector_t::to_subnet, and TS_IPV4_ADDR_RANGE.
Referenced by add_ts().
 {
     private_id_payload_t *this;
     u_int8_t mask;
     host_t *net;
     this = (private_id_payload_t*)id_payload_create(PLV1_ID);
     if (ts->is_host(ts, NULL))
     {
         if (ts->get_type(ts) == TS_IPV4_ADDR_RANGE)
         {
             this->id_type = ID_IPV4_ADDR;
         }
         else
         {
             this->id_type = ID_IPV6_ADDR;
         }
         this->id_data = chunk_clone(ts->get_from_address(ts));
     }
     else if (ts->to_subnet(ts, &net, &mask))
     {
         u_int8_t netmask[16], len, byte;
         if (ts->get_type(ts) == TS_IPV4_ADDR_RANGE)
         {
             this->id_type = ID_IPV4_ADDR_SUBNET;
             len = 4;
         }
         else
         {
             this->id_type = ID_IPV6_ADDR_SUBNET;
             len = 16;
         }
         memset(netmask, 0, sizeof(netmask));
         for (byte = 0; byte < sizeof(netmask); byte++)
         {
             if (mask < 8)
             {
                 netmask[byte] = 0xFF << (8 - mask);
                 break;
             }
             netmask[byte] = 0xFF;
             mask -= 8;
         }
         this->id_data = chunk_cat("cc", net->get_address(net),
                                   chunk_create(netmask, len));
         net->destroy(net);
     }
     else
     {
         if (ts->get_type(ts) == TS_IPV4_ADDR_RANGE)
         {
             this->id_type = ID_IPV4_ADDR_RANGE;
         }
         else
         {
             this->id_type = ID_IPV6_ADDR_RANGE;
         }
         this->id_data = chunk_cat("cc",
                             ts->get_from_address(ts), ts->get_to_address(ts));
         net->destroy(net);
     }
     this->port = ts->get_from_port(ts);
     this->protocol_id = ts->get_protocol(ts);
     this->payload_length += this->id_data.len;
     return &this->public;
 }