strongSwan: log_ts.c File Reference
log_ts.c File Reference
#include "hook.h"
#include <encoding/payloads/ts_payload.h>
Classes
struct private_log_ts_t
Typedefs
typedef struct private_log_ts_t private_log_ts_t
Functions
METHOD (listener_t, message, bool, private_log_ts_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (hook_t, destroy, void, private_log_ts_t *this)
hook_t * log_ts_hook_create (char *name)
Typedef Documentation
typedef struct private_log_ts_t private_log_ts_t
Definition at line 20 of file log_ts.c.
Function Documentation
hook_t* log_ts_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 90 of file log_ts.c.
References INIT.
 {
     private_log_ts_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .message = _message,
             },
             .destroy = _destroy,
         },
     );
     return &this->hook;
 }
METHOD (listener_t , message , bool , private_log_ts_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 33 of file log_ts.c.
References linked_list_t::create_enumerator, message_t::create_payload_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, from, traffic_selector_t::get_from_address, traffic_selector_t::get_from_port, traffic_selector_t::get_protocol, traffic_selector_t::get_to_address, traffic_selector_t::get_to_port, ts_payload_t::get_traffic_selectors, traffic_selector_t::get_type, payload_t::get_type, host_create_from_chunk(), list, payload_type_short_names, PLV2_TS_INITIATOR, PLV2_TS_RESPONDER, to, TRUE, and ts_type_name.
 {
     if (incoming && plain)
     {
         enumerator_t *enumerator;
         payload_t *payload;
         ts_payload_t *ts;
         enumerator = message->create_payload_enumerator(message);
         while (enumerator->enumerate(enumerator, &payload))
         {
             if (payload->get_type(payload) == PLV2_TS_INITIATOR ||
                 payload->get_type(payload) == PLV2_TS_RESPONDER)
             {
                 ts = (ts_payload_t*)payload;
                 host_t *from, *to;
                 linked_list_t *list;
                 enumerator_t *tsenum;
                 traffic_selector_t *selector;
                 list = ts->get_traffic_selectors(ts);
                 tsenum = list->create_enumerator(list);
                 while (tsenum->enumerate(tsenum, &selector))
                 {
                     from = host_create_from_chunk(AF_UNSPEC,
                                     selector->get_from_address(selector), 0);
                     to = host_create_from_chunk(AF_UNSPEC,
                                     selector->get_to_address(selector), 0);
                     DBG1(DBG_CFG, "received %N: %N %H-%H proto %u port %u-%u",
                          payload_type_short_names, payload->get_type(payload),
                          ts_type_name, selector->get_type(selector),
                          from, to, selector->get_protocol(selector),
                          selector->get_from_port(selector),
                          selector->get_to_port(selector));
                 }
                 tsenum->destroy(tsenum);
                 list->destroy_offset(list, offsetof(traffic_selector_t, destroy));
             }
         }
         enumerator->destroy(enumerator);
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_log_ts_t * this)
Definition at line 81 of file log_ts.c.
References free().
 {
     free(this);
 }