strongSwan: cp_payload_t Struct Reference
cp_payload_t Struct Reference
cp_payload
#include "cp_payload.h"
Public Attributes
payload_t payload_interface
enumerator_t *(* create_attribute_enumerator)(cp_payload_t *this)
void(* add_attribute)(cp_payload_t *this, configuration_attribute_t *attribute)
config_type_t(* get_type)(cp_payload_t *this)
void(* set_identifier)(cp_payload_t *this, u_int16_t identifier)
u_int16_t(* get_identifier)(cp_payload_t *this)
void(* destroy)(cp_payload_t *this)
Detailed Description
Class representing an IKEv2 configuration / IKEv1 attribute payload.
Definition at line 51 of file cp_payload.h.
Member Data Documentation
void(* cp_payload_t::add_attribute)(cp_payload_t *this, configuration_attribute_t *attribute)
Adds a configuration attribute to the configuration payload.
Parameters
attribute attribute to add
Definition at line 70 of file cp_payload.h.
Referenced by add_attribute(), build_ack(), build_reply(), build_request(), build_round(), build_set(), and METHOD().
enumerator_t*(* cp_payload_t::create_attribute_enumerator)(cp_payload_t *this)
Creates an enumerator of stored configuration_attribute_t objects.
Returns
enumerator over configration_attribute_T
Definition at line 63 of file cp_payload.h.
Referenced by get_string(), METHOD(), and process_payloads().
void(* cp_payload_t::destroy)(cp_payload_t *this)
Destroys an cp_payload_t object.
Definition at line 97 of file cp_payload.h.
Referenced by METHOD().
u_int16_t(* cp_payload_t::get_identifier)(cp_payload_t *this)
Get the configuration payload identifier (IKEv1 only).
Returns
identifier
Definition at line 92 of file cp_payload.h.
Referenced by METHOD(), and process_payloads().
config_type_t(* cp_payload_t::get_type)(cp_payload_t *this)
Get the configuration payload type.
Returns
type of configuration payload
Definition at line 78 of file cp_payload.h.
Referenced by get_string(), METHOD(), and process_payloads().
payload_t cp_payload_t::payload_interface
The payload_t interface.
Definition at line 56 of file cp_payload.h.
void(* cp_payload_t::set_identifier)(cp_payload_t *this, u_int16_t identifier)
Set the configuration payload identifier (IKEv1 only).
Parameters
identifier identifier to set
Definition at line 85 of file cp_payload.h.
Referenced by build_ack(), build_reply(), and METHOD().
The documentation for this struct was generated from the following file:
cp_payload.h