strongSwan: sys_logger_t Struct Reference
sys_logger_t Struct Reference
sys_logger
#include "sys_logger.h"
Public Attributes
logger_t logger
void(* set_level)(sys_logger_t *this, debug_t group, level_t level)
void(* set_options)(sys_logger_t *this, bool ike_name)
void(* destroy)(sys_logger_t *this)
Detailed Description
Logger for syslog which implements listener_t.
Definition at line 32 of file sys_logger.h.
Member Data Documentation
void(* sys_logger_t::destroy)(sys_logger_t *this)
Destroys a sys_logger_t object.
Definition at line 57 of file sys_logger.h.
logger_t sys_logger_t::logger
Implements the logger_t interface.
Definition at line 37 of file sys_logger.h.
Referenced by load_sys_logger(), and METHOD().
void(* sys_logger_t::set_level)(sys_logger_t *this, debug_t group, level_t level)
Set the loglevel for a debug group.
Parameters
group debug group to set
level max level to log (0..4)
Definition at line 45 of file sys_logger.h.
Referenced by load_sys_logger(), and METHOD().
void(* sys_logger_t::set_options)(sys_logger_t *this, bool ike_name)
Set options used by this logger.
Parameters
ike_name TRUE to prefix the name of the IKE_SA
Definition at line 52 of file sys_logger.h.
Referenced by load_sys_logger().
The documentation for this struct was generated from the following file:
sys_logger.h