strongSwan: pa_tnc_msg
pa_tnc_msg
pa_tnc
Classes
struct pa_tnc_msg_t
Macros
#define PA_TNC_VERSION 0x01
#define PA_TNC_HEADER_SIZE 8
Typedefs
typedef struct pa_tnc_msg_t pa_tnc_msg_t
Functions
pa_tnc_msg_t * pa_tnc_msg_create (size_t max_msg_len)
pa_tnc_msg_t * pa_tnc_msg_create_from_data (chunk_t data)
Detailed Description
Macro Definition Documentation
#define PA_TNC_HEADER_SIZE 8
Definition at line 27 of file pa_tnc_msg.h.
Referenced by METHOD(), pa_tnc_msg_create(), and TNC_IMC_BeginHandshake().
#define PA_TNC_VERSION 0x01
Definition at line 26 of file pa_tnc_msg.h.
Referenced by METHOD().
Typedef Documentation
typedef struct pa_tnc_msg_t pa_tnc_msg_t
Definition at line 24 of file pa_tnc_msg.h.
Function Documentation
pa_tnc_msg_t* pa_tnc_msg_create (size_t max_msg_len)
Create an empty PA-TNC message
See header
Definition at line 391 of file pa_tnc_msg.c.
References INIT, linked_list_create(), and PA_TNC_HEADER_SIZE.
Referenced by METHOD().
 {
     private_pa_tnc_msg_t *this;
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .get_space = _get_space,
             .add_attribute = _add_attribute,
             .build = _build,
             .process = _process,
             .process_ietf_std_errors = _process_ietf_std_errors,
             .create_attribute_enumerator = _create_attribute_enumerator,
             .create_error_enumerator = _create_error_enumerator,
             .destroy = _destroy,
         },
         .attributes = linked_list_create(),
         .errors = linked_list_create(),
         .msg_len = PA_TNC_HEADER_SIZE,
         .max_msg_len = max_msg_len,
     );
     return &this->public;
 }
pa_tnc_msg_t* pa_tnc_msg_create_from_data (chunk_t data)
Create an unprocessed PA-TNC message from received data
Parameters
data PA-TNC message data
See header
Definition at line 419 of file pa_tnc_msg.c.
References chunk_clone, INIT, linked_list_create(), and TRUE.
Referenced by imc_msg_create_from_long_data(), and imv_msg_create_from_long_data().
 {
     private_pa_tnc_msg_t *this;
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .get_space = _get_space,
             .add_attribute = _add_attribute,
             .build = _build,
             .process = _process,
             .process_ietf_std_errors = _process_ietf_std_errors,
             .create_attribute_enumerator = _create_attribute_enumerator,
             .create_error_enumerator = _create_error_enumerator,
             .destroy = _destroy,
         },
         .encoding = chunk_clone(data),
         .attributes = linked_list_create(),
         .errors = linked_list_create(),
         .from_data = TRUE,
     );
     return &this->public;
 }