strongSwan: imv_os_database.c File Reference
imv_os_database.c File Reference
#include <string.h>
#include "imv_os_database.h"
#include <utils/debug.h>
Classes
struct private_imv_os_database_t
Macros
#define _GNU_SOURCE /* for stdndup() */
Typedefs
typedef struct
private_imv_os_database_t private_imv_os_database_t
Functions
METHOD (imv_os_database_t, check_packages, status_t, private_imv_os_database_t *this, imv_os_state_t *os_state, enumerator_t *package_enumerator)
METHOD (imv_os_database_t, destroy, void, private_imv_os_database_t *this)
imv_os_database_t * imv_os_database_create (imv_database_t *imv_db)
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 16 of file imv_os_database.c.
Typedef Documentation
typedef struct private_imv_os_database_t private_imv_os_database_t
Definition at line 23 of file imv_os_database.c.
Function Documentation
METHOD (imv_os_database_t , check_packages , status_t , private_imv_os_database_t * this, imv_os_state_t * os_state, enumerator_t * package_enumerator)
Definition at line 43 of file imv_os_database.c.
References imv_os_state_t::add_bad_package, count, db, DB_INT, DB_TEXT, DBG1, DBG2, DBG_IMV, enumerator_t::destroy, enum_to_name(), enumerator_t::enumerate, FAILED, FALSE, found, free(), imv_os_info_t::get_info, imv_session_t::get_os_info, imv_state_t::get_session, imv_session_t::get_session_id, imv_os_info_t::get_type, imv_os_state_t::interface, chunk_t::len, match(), name, NOT_FOUND, OS_PACKAGE_STATE_BLACKLIST, OS_PACKAGE_STATE_SECURITY, OS_TYPE_ANDROID, os_type_names, chunk_t::ptr, database_t::query, imv_os_state_t::set_count, status, streq(), strndup(), SUCCESS, TRUE, and version.
 {
     imv_state_t *state;
     imv_session_t *session;
     imv_os_info_t *os_info;
     os_type_t os_type;
     char *product, *package, *release, *cur_release;
     chunk_t name, version;
     int pid, gid, security, blacklist;
     int count = 0, count_ok = 0, count_no_match = 0, count_blacklist = 0;
     enumerator_t *e;
     status_t status = SUCCESS;
     bool found, match;
     state = &os_state->interface;
     session = state->get_session(state);
     session->get_session_id(session, &pid, NULL);
     os_info = session->get_os_info(session);
     os_type = os_info->get_type(os_info);
     product = os_info->get_info(os_info);
     if (os_type == OS_TYPE_ANDROID)
     {
         /*no package dependency on Android version */
         product = enum_to_name(os_type_names, os_type);
         /* Get primary key of product */
         e = this->db->query(this->db,
                     "SELECT id FROM products WHERE name = ?",
                     DB_TEXT, product, DB_INT);
         if (!e)
         {
             return FAILED;
         }
         if (!e->enumerate(e, &pid))
         {
             e->destroy(e);
             return NOT_FOUND;
         }
         e->destroy(e);
     }
     DBG1(DBG_IMV, "processing installed '%s' packages", product);
     while (package_enumerator->enumerate(package_enumerator, &name, &version))
     {
         /* Convert package name chunk to a string */
         package = strndup(name.ptr, name.len);
         count++;
         /* Get primary key of package */
         e = this->db->query(this->db,
                     "SELECT id FROM packages WHERE name = ?",
                     DB_TEXT, package, DB_INT);
         if (!e)
         {
             free(package);
             return FAILED;
         }
         if (!e->enumerate(e, &gid))
         {
             /* package not present in database for any product - skip */
             if (os_type == OS_TYPE_ANDROID)
             {
                 DBG2(DBG_IMV, "package '%s' (%.*s) not found",
                      package, version.len, version.ptr);
             }
             free(package);
             e->destroy(e);
             continue;
         }
         e->destroy(e);
         /* Convert package version chunk to a string */
         release = strndup(version.ptr, version.len);
         /* Enumerate over all acceptable versions */
         e = this->db->query(this->db,
                 "SELECT release, security, blacklist FROM versions "
                 "WHERE product = ? AND package = ?",
                 DB_INT, pid, DB_INT, gid, DB_TEXT, DB_INT, DB_INT);
         if (!e)
         {
             free(package);
             free(release);
             return FAILED;
         }
         found = FALSE;
         match = FALSE;
         while (e->enumerate(e, &cur_release, &security, &blacklist))
         {
             found = TRUE;
             if (streq(release, cur_release) || streq("*", cur_release))
             {
                 match = TRUE;
                 break;
             }
         }
         e->destroy(e);
         if (found)
         {
             if (match)
             {
                 if (blacklist)
                 {
                     DBG2(DBG_IMV, "package '%s' (%s) is blacklisted",
                                    package, release);
                     count_blacklist++;
                     os_state->add_bad_package(os_state, package,
                                               OS_PACKAGE_STATE_BLACKLIST);
                 }
                 else
                 {
                     DBG2(DBG_IMV, "package '%s' (%s)%s is ok", package, release,
                                    security ? " [s]" : "");
                     count_ok++;
                 }
             }
             else
             {
                 DBG1(DBG_IMV, "package '%s' (%s) no match", package, release);
                 count_no_match++;
                 os_state->add_bad_package(os_state, package,
                                           OS_PACKAGE_STATE_SECURITY);
             }
         }
         else
         {
             /* package not present in database for this product - skip */
         }
         free(package);
         free(release);
     }
     os_state->set_count(os_state, count, count_no_match,
                                   count_blacklist, count_ok);
     return status;
 }
METHOD (imv_os_database_t , destroy , void , private_imv_os_database_t * this)
Definition at line 185 of file imv_os_database.c.
References free().
 {
     free(this);
 }