strongSwan: padlock_rng.c File Reference
padlock_rng.c File Reference
#include "padlock_rng.h"
Classes
struct private_padlock_rng_t
Typedefs
typedef struct
private_padlock_rng_t private_padlock_rng_t
typedef enum
padlock_quality_factor_t padlock_quality_factor_t
Enumerations
enum padlock_quality_factor_t { PADLOCK_QF0 = 0x00, PADLOCK_QF1 = 0x01, PADLOCK_QF2 = 0x10, PADLOCK_QF3 = 0x11 }
Functions
static void rng (char *buf, int len, int quality)
METHOD (rng_t, allocate_bytes, bool, private_padlock_rng_t *this, size_t bytes, chunk_t *chunk)
METHOD (rng_t, get_bytes, bool, private_padlock_rng_t *this, size_t bytes, u_int8_t *buffer)
METHOD (rng_t, destroy, void, private_padlock_rng_t *this)
padlock_rng_t * padlock_rng_create (rng_quality_t quality)
Typedef Documentation
typedef enum padlock_quality_factor_t padlock_quality_factor_t
Definition at line 19 of file padlock_rng.c.
typedef struct private_padlock_rng_t private_padlock_rng_t
Definition at line 18 of file padlock_rng.c.
Enumeration Type Documentation
enum padlock_quality_factor_t
Padlock RNG quality factors
Enumerator
PADLOCK_QF0
PADLOCK_QF1
PADLOCK_QF2
PADLOCK_QF3
Definition at line 24 of file padlock_rng.c.
{
     /* Lowest quality: Reads 8 bytes */
     PADLOCK_QF0 = 0x00,
     /* Medium quality: Reads 4 bytes */
     PADLOCK_QF1 = 0x01,
     /* Better quality: Reads 2 bytes */
     PADLOCK_QF2 = 0x10,
     /* Highest quality: Reads 1 byte */
     PADLOCK_QF3 = 0x11,
 };
Function Documentation
METHOD (rng_t , allocate_bytes , bool , private_padlock_rng_t * this, size_t bytes, chunk_t * chunk)
Definition at line 72 of file padlock_rng.c.
References bytes, chunk_t::len, malloc(), chunk_t::ptr, rng(), and TRUE.
 {
     chunk->len = bytes;
     /* padlock requires some additional bytes */
     chunk->ptr = malloc(bytes + 7);
     rng(chunk->ptr, chunk->len, this->quality);
     return TRUE;
 }
METHOD (rng_t , get_bytes , bool , private_padlock_rng_t * this, size_t bytes, u_int8_t * buffer)
Definition at line 83 of file padlock_rng.c.
References chunk_clear(), memcpy, chunk_t::ptr, and TRUE.
 {
     chunk_t chunk;
     /* Padlock needs a larger buffer than "bytes", we need a new buffer */
     allocate_bytes(this, bytes, &chunk);
     memcpy(buffer, chunk.ptr, bytes);
     chunk_clear(&chunk);
     return TRUE;
 }
METHOD (rng_t , destroy , void , private_padlock_rng_t * this)
Definition at line 95 of file padlock_rng.c.
References free().
 {
     free(this);
 }
static void rng (char * buf, int len, int quality) static
Get bytes from Padlock RNG. buf should have space for (len + 7)
Definition at line 54 of file padlock_rng.c.
References status.
Referenced by METHOD().
 {
     while (len > 0)
     {
         int status;
         /* run XSTORE until we have all bytes needed. We do not use REP, as
          * this should not be performance critical and it's easier this way. */
         asm volatile (
             ".byte 0x0F,0xA7,0xC0 \n\t"
             : "=D"(buf), "=a"(status)
             : "d"(quality), "D"(buf));
         /* bits[0..4] of status word contains the number of bytes read */
         len -= status & 0x1F;
     }
 }