strongSwan: forecast_listener.c File Reference
forecast_listener.c File Reference
#include "forecast_listener.h"
#include <errno.h>
#include <libiptc/libiptc.h>
#include <linux/netfilter/xt_MARK.h>
#include <linux/netfilter/xt_esp.h>
#include <daemon.h>
#include <collections/array.h>
#include <collections/hashtable.h>
#include <threading/rwlock.h>
Classes
struct private_forecast_listener_t
struct entry_t
Typedefs
typedef struct
private_forecast_listener_t private_forecast_listener_t
Functions
static void entry_destroy (entry_t *entry)
static bool ts2in (traffic_selector_t *ts, struct in_addr *addr, struct in_addr *mask)
static bool host2in (host_t *host, struct in_addr *addr, struct in_addr *mask)
static bool manage_rule (struct iptc_handle *ipth, const char *chain, bool add, struct ipt_entry *e)
static bool manage_pre_esp_in_udp (struct iptc_handle *ipth, entry_t *entry, bool add)
static bool manage_pre_esp (struct iptc_handle *ipth, entry_t *entry, bool add)
static bool manage_pre (struct iptc_handle *ipth, entry_t *entry, bool add)
static bool manage_out (struct iptc_handle *ipth, entry_t *entry, bool add)
static bool is_reinject_config (private_forecast_listener_t *this, char *name)
static bool add_entry (private_forecast_listener_t *this, struct iptc_handle *ipth, host_t *lhost, host_t *rhost, child_sa_t *child_sa, bool encap)
static bool remove_entry (private_forecast_listener_t *this, struct iptc_handle *ipth, child_sa_t *child_sa)
static struct iptc_handle * init_handle ()
static bool commit_handle (struct iptc_handle *ipth)
static bool handle_sa (child_sa_t *child_sa)
METHOD (listener_t, child_updown, bool, private_forecast_listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool up)
METHOD (listener_t, child_rekey, bool, private_forecast_listener_t *this, ike_sa_t *ike_sa, child_sa_t *old, child_sa_t *new)
METHOD (listener_t, ike_update, bool, private_forecast_listener_t *this, ike_sa_t *ike_sa, bool local, host_t *new)
static bool ts_filter (entry_t *entry, traffic_selector_t **ts, traffic_selector_t **out, void *dummy, u_int32_t *mark, void *dummy2, bool *reinject)
static enumerator_t * create_inner_local (entry_t *entry, rwlock_t *lock)
static enumerator_t * create_inner_remote (entry_t *entry, rwlock_t *lock)
METHOD (forecast_listener_t, create_enumerator, enumerator_t *, private_forecast_listener_t *this, bool local)
METHOD (forecast_listener_t, set_broadcast, void, private_forecast_listener_t *this, host_t *bcast)
METHOD (forecast_listener_t, destroy, void, private_forecast_listener_t *this)
forecast_listener_t * forecast_listener_create ()
Typedef Documentation
typedef struct private_forecast_listener_t private_forecast_listener_t
Definition at line 28 of file forecast_listener.c.
Function Documentation
static bool add_entry (private_forecast_listener_t * this, struct iptc_handle * ipth, host_t * lhost, host_t * rhost, child_sa_t * child_sa, bool encap) static
Add rules and entry for given CHILD_SA
Definition at line 369 of file forecast_listener.c.
References array_create(), array_insert(), ARRAY_TAIL, host_t::clone, traffic_selector_t::clone, child_sa_t::create_ts_enumerator, enumerator_t::destroy, entry_destroy(), enumerator_t::enumerate, FALSE, child_sa_t::get_mark, child_sa_t::get_name, child_sa_t::get_spi, INIT, is_reinject_config(), lock, entry_t::lts, manage_out(), manage_pre(), entry_t::rts, TRUE, spinlock_t::unlock, and mark_t::value.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     entry_t *entry;
     INIT(entry,
         .lts = array_create(0, 0),
         .rts = array_create(0, 0),
         .lhost = lhost->clone(lhost),
         .rhost = rhost->clone(rhost),
         .spi = child_sa->get_spi(child_sa, TRUE),
         .encap = encap,
         .mark = child_sa->get_mark(child_sa, TRUE).value,
         .reinject = is_reinject_config(this, child_sa->get_name(child_sa)),
         .broadcast = this->broadcast,
     );
     enumerator = child_sa->create_ts_enumerator(child_sa, TRUE);
     while (enumerator->enumerate(enumerator, &ts))
     {
         array_insert(entry->lts, ARRAY_TAIL, ts->clone(ts));
     }
     enumerator->destroy(enumerator);
     enumerator = child_sa->create_ts_enumerator(child_sa, FALSE);
     while (enumerator->enumerate(enumerator, &ts))
     {
         array_insert(entry->rts, ARRAY_TAIL, ts->clone(ts));
     }
     enumerator->destroy(enumerator);
     if (manage_pre(ipth, entry, TRUE) &&
         manage_out(ipth, entry, TRUE))
     {
         this->lock->write_lock(this->lock);
         this->entries->insert_last(this->entries, entry);
         this->lock->unlock(this->lock);
         return TRUE;
     }
     entry_destroy(entry);
     return FALSE;
 }
static bool commit_handle (struct iptc_handle * ipth) static
Commit iptables rules, log error
Definition at line 466 of file forecast_listener.c.
References DBG1, DBG_CFG, FALSE, and TRUE.
Referenced by METHOD().
 {
     if (iptc_commit(ipth))
     {
         return TRUE;
     }
     DBG1(DBG_CFG, "forecast iptables commit failed: %s", iptc_strerror(errno));
     return FALSE;
 }
static enumerator_t* create_inner_local (entry_t * entry, rwlock_t * lock) static
Create inner enumerator over local traffic selectors
Definition at line 610 of file forecast_listener.c.
References array_create_enumerator(), enumerator_create_filter(), entry_t::lts, and ts_filter().
Referenced by METHOD().
 {
     return enumerator_create_filter(array_create_enumerator(entry->lts),
                                     (void*)ts_filter, entry, NULL);
 }
static enumerator_t* create_inner_remote (entry_t * entry, rwlock_t * lock) static
Create inner enumerator over remote traffic selectors
Definition at line 619 of file forecast_listener.c.
References array_create_enumerator(), enumerator_create_filter(), entry_t::rts, and ts_filter().
Referenced by METHOD().
 {
     return enumerator_create_filter(array_create_enumerator(entry->rts),
                                     (void*)ts_filter, entry, NULL);
 }
static void entry_destroy (entry_t * entry) static
Destroy an entry
Definition at line 88 of file forecast_listener.c.
References array_destroy_offset(), host_t::destroy, destroy(), free(), entry_t::lhost, entry_t::lts, entry_t::rhost, and entry_t::rts.
Referenced by add_entry(), and remove_entry().
 {
     if (entry)
     {
         entry->lhost->destroy(entry->lhost);
         entry->rhost->destroy(entry->rhost);
         array_destroy_offset(entry->lts, offsetof(traffic_selector_t, destroy));
         array_destroy_offset(entry->rts, offsetof(traffic_selector_t, destroy));
         free(entry);
     }
 }
static bool handle_sa (child_sa_t * child_sa) static
Check if we should handle the given CHILD_SA
Definition at line 479 of file forecast_listener.c.
References FALSE, child_sa_t::get_mark, TRUE, and mark_t::value.
Referenced by METHOD().
 {
     return child_sa->get_mark(child_sa, TRUE).value &&
            child_sa->get_mark(child_sa, FALSE).value;
 }
static bool host2in (host_t * host, struct in_addr * addr, struct in_addr * mask) static
Convert an (IPv4) host to an address with mask
Definition at line 123 of file forecast_listener.c.
References FALSE, host_t::get_address, host_t::get_family, memcpy, chunk_t::ptr, and TRUE.
Referenced by manage_pre_esp(), and manage_pre_esp_in_udp().
 {
     if (host->get_family(host) == AF_INET)
     {
         memcpy(&addr->s_addr, host->get_address(host).ptr, 4);
         mask->s_addr = ~0;
         return TRUE;
     }
     return FALSE;
 }
static struct iptc_handle* init_handle () static
Initialize iptables handle, log error
Definition at line 450 of file forecast_listener.c.
References DBG1, and DBG_CFG.
Referenced by METHOD().
 {
     struct iptc_handle *ipth;
     ipth = iptc_init("mangle");
     if (ipth)
     {
         return ipth;
     }
     DBG1(DBG_CFG, "initializing iptables failed: %s", iptc_strerror(errno));
     return NULL;
 }
static bool is_reinject_config (private_forecast_listener_t * this, char * name) static
Check if config is whitelisted to reinject traffic
Definition at line 346 of file forecast_listener.c.
References enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), FALSE, streq(), and TRUE.
Referenced by add_entry().
 {
     enumerator_t *enumerator;
     bool reinject = FALSE;
     char *token;
     enumerator = enumerator_create_token(this->reinject_configs, ",", " ");
     while (enumerator->enumerate(enumerator, &token))
     {
         if (streq(token, name))
         {
             reinject = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return reinject;
 }
static bool manage_out (struct iptc_handle * ipth, entry_t * entry, bool add) static
Add rule handling outbound traffic to use correct mark
Definition at line 292 of file forecast_listener.c.
References array_create_enumerator(), entry_t::broadcast, enumerator_t::destroy, enumerator_t::enumerate, FALSE, manage_rule(), entry_t::mark, memeq(), entry_t::rts, TRUE, and ts2in().
Referenced by add_entry(), and remove_entry().
 {
     struct {
         struct ipt_entry e;
         struct ipt_entry_target t;
         struct xt_mark_tginfo2 m;
     } ipt = {
         .e  = {
             .target_offset = XT_ALIGN(sizeof(ipt.e)),
             .next_offset = sizeof(ipt),
         },
         .t = {
             .u.user.target_size = XT_ALIGN(sizeof(ipt.t) + sizeof(ipt.m)),
             .u.user.name = "MARK",
             .u.user.revision = 2,
         },
         .m = {
             .mark = entry->mark,
             .mask = ~0,
         },
     };
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     enumerator = array_create_enumerator(entry->rts);
     while (enumerator->enumerate(enumerator, &ts))
     {
         if (!ts2in(ts, &ipt.e.ip.dst, &ipt.e.ip.dmsk))
         {
             continue;
         }
         if (ipt.e.ip.dst.s_addr == 0xffffffff ||
             ipt.e.ip.dst.s_addr == entry->broadcast ||
             memeq(&ipt.e.ip.dst.s_addr, "\xe0", 1))
         {
             /* skip broadcast/multicast selectors, they are shared and the mark
              * is set by the socket we use for reinjection */
             continue;
         }
         if (!manage_rule(ipth, "PREROUTING", add, &ipt.e) ||
             !manage_rule(ipth, "OUTPUT", add, &ipt.e))
         {
             enumerator->destroy(enumerator);
             return FALSE;
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 }
static bool manage_pre (struct iptc_handle * ipth, entry_t * entry, bool add) static
Add rule marking ESP packets to match the correct policy
Definition at line 280 of file forecast_listener.c.
References entry_t::encap, manage_pre_esp(), and manage_pre_esp_in_udp().
Referenced by add_entry(), and remove_entry().
 {
     if (entry->encap)
     {
         return manage_pre_esp_in_udp(ipth, entry, add);
     }
     return manage_pre_esp(ipth, entry, add);
 }
static bool manage_pre_esp (struct iptc_handle * ipth, entry_t * entry, bool add) static
Add rule marking non-encapsulated ESP packets to match the correct policy
Definition at line 226 of file forecast_listener.c.
References FALSE, host2in(), ip, entry_t::lhost, manage_rule(), entry_t::mark, entry_t::rhost, and entry_t::spi.
Referenced by manage_pre().
 {
     struct {
         struct ipt_entry e;
         struct ipt_entry_match m;
         struct xt_esp esp;
         struct ipt_entry_target t;
         struct xt_mark_tginfo2 tm;
     } ipt = {
         .e  = {
             .target_offset = XT_ALIGN(sizeof(ipt.e) + sizeof(ipt.m) +
                                       sizeof(ipt.esp)),
             .next_offset = sizeof(ipt),
             .ip = {
                 .proto = IPPROTO_ESP,
             },
         },
         .m = {
             .u = {
                 .user = {
                     .match_size = XT_ALIGN(sizeof(ipt.m) + sizeof(ipt.esp)),
                     .name = "esp",
                 },
             },
         },
         .esp = {
             .spis = { htonl(entry->spi), htonl(entry->spi) },
         },
         .t = {
             .u = {
                 .user = {
                     .target_size = XT_ALIGN(sizeof(ipt.t) + sizeof(ipt.tm)),
                     .name = "MARK",
                     .revision = 2,
                 },
             },
         },
         .tm = {
             .mark = entry->mark,
             .mask = ~0,
         },
     };
     if (!host2in(entry->lhost, &ipt.e.ip.dst, &ipt.e.ip.dmsk) ||
         !host2in(entry->rhost, &ipt.e.ip.src, &ipt.e.ip.smsk))
     {
         return FALSE;
     }
     return manage_rule(ipth, "PREROUTING", add, &ipt.e);
 }
static bool manage_pre_esp_in_udp (struct iptc_handle * ipth, entry_t * entry, bool add) static
Add rule marking UDP-encapsulated ESP packets to match the correct policy
Definition at line 164 of file forecast_listener.c.
References FALSE, host_t::get_port, host2in(), ip, entry_t::lhost, manage_rule(), entry_t::mark, and entry_t::rhost.
Referenced by manage_pre().
 {
     struct {
         struct ipt_entry e;
         struct ipt_entry_match m;
         struct xt_udp udp;
         struct ipt_entry_target t;
         struct xt_mark_tginfo2 tm;
     } ipt = {
         .e  = {
             .target_offset = XT_ALIGN(sizeof(ipt.e) + sizeof(ipt.m) +
                                       sizeof(ipt.udp)),
             .next_offset = sizeof(ipt),
             .ip = {
                 .proto = IPPROTO_UDP,
             },
         },
         .m = {
             .u = {
                 .user = {
                     .match_size = XT_ALIGN(sizeof(ipt.m) + sizeof(ipt.udp)),
                     .name = "udp",
                 },
             },
         },
         .udp = {
             .spts = {
                 entry->rhost->get_port(entry->rhost),
                 entry->rhost->get_port(entry->lhost)
             },
             .dpts = {
                 entry->lhost->get_port(entry->lhost),
                 entry->lhost->get_port(entry->lhost)
             },
         },
         .t = {
             .u = {
                 .user = {
                     .target_size = XT_ALIGN(sizeof(ipt.t) + sizeof(ipt.tm)),
                     .name = "MARK",
                     .revision = 2,
                 },
             },
         },
         .tm = {
             .mark = entry->mark,
             .mask = ~0,
         },
     };
     if (!host2in(entry->lhost, &ipt.e.ip.dst, &ipt.e.ip.dmsk) ||
         !host2in(entry->rhost, &ipt.e.ip.src, &ipt.e.ip.smsk))
     {
         return FALSE;
     }
     return manage_rule(ipth, "PREROUTING", add, &ipt.e);
 }
static bool manage_rule (struct iptc_handle * ipth, const char * chain, bool add, struct ipt_entry * e) static
Add or remove a rule to/from the specified chain
Definition at line 137 of file forecast_listener.c.
References DBG1, DBG_CFG, FALSE, and TRUE.
Referenced by manage_out(), manage_pre_esp(), and manage_pre_esp_in_udp().
 {
     if (add)
     {
         if (!iptc_insert_entry(chain, e, 0, ipth))
         {
             DBG1(DBG_CFG, "appending %s rule failed: %s",
                  chain, iptc_strerror(errno));
             return FALSE;
         }
     }
     else
     {
         if (!iptc_delete_entry(chain, e, "", ipth))
         {
             DBG1(DBG_CFG, "deleting %s rule failed: %s",
                  chain, iptc_strerror(errno));
             return FALSE;
         }
     }
     return TRUE;
 }
METHOD (listener_t , child_updown , bool , private_forecast_listener_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, bool up)
Definition at line 485 of file forecast_listener.c.
References add_entry(), commit_handle(), ike_sa_t::get_my_host, ike_sa_t::get_other_host, handle_sa(), child_sa_t::has_encap, init_handle(), remove_entry(), and TRUE.
 {
     struct iptc_handle *ipth;
     host_t *lhost, *rhost;
     bool encap;
     lhost = ike_sa->get_my_host(ike_sa);
     rhost = ike_sa->get_other_host(ike_sa);
     encap = child_sa->has_encap(child_sa);
     if (handle_sa(child_sa))
     {
         ipth = init_handle();
         if (ipth)
         {
             if (up)
             {
                 if (add_entry(this, ipth, lhost, rhost, child_sa, encap))
                 {
                     commit_handle(ipth);
                 }
             }
             else
             {
                 if (remove_entry(this, ipth, child_sa))
                 {
                     commit_handle(ipth);
                 }
             }
             iptc_free(ipth);
         }
     }
     return TRUE;
 }
METHOD (listener_t , child_rekey , bool , private_forecast_listener_t * this, ike_sa_t * ike_sa, child_sa_t * old, child_sa_t * new)
Definition at line 522 of file forecast_listener.c.
References add_entry(), commit_handle(), ike_sa_t::get_my_host, ike_sa_t::get_other_host, handle_sa(), init_handle(), remove_entry(), and TRUE.
 {
     struct iptc_handle *ipth;;
     host_t *lhost, *rhost;
     lhost = ike_sa->get_my_host(ike_sa);
     rhost = ike_sa->get_other_host(ike_sa);
     if (handle_sa(old))
     {
         ipth = init_handle();
         if (ipth)
         {
             if (remove_entry(this, ipth, old) &&
                 add_entry(this, ipth, lhost, rhost, new, new->has_encap(new)))
             {
                 commit_handle(ipth);
             }
             iptc_free(ipth);
         }
     }
     return TRUE;
 }
METHOD (listener_t , ike_update , bool , private_forecast_listener_t * this, ike_sa_t * ike_sa, bool local, host_t * new)
Definition at line 548 of file forecast_listener.c.
References add_entry(), commit_handle(), COND_NAT_ANY, ike_sa_t::create_child_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, ike_sa_t::get_my_host, ike_sa_t::get_other_host, handle_sa(), ike_sa_t::has_condition, init_handle(), remove_entry(), and TRUE.
 {
     struct iptc_handle *ipth;
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     host_t *lhost, *rhost;
     bool encap;
     if (local)
     {
         lhost = new;
         rhost = ike_sa->get_other_host(ike_sa);
     }
     else
     {
         lhost = ike_sa->get_my_host(ike_sa);
         rhost = new;
     }
     /* during ike_update(), has_encap() on the CHILD_SA has not yet been
      * updated, but shows the old state. */
     encap = ike_sa->has_condition(ike_sa, COND_NAT_ANY);
     enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         if (handle_sa(child_sa))
         {
             ipth = init_handle();
             if (ipth)
             {
                 if (remove_entry(this, ipth, child_sa) &&
                     add_entry(this, ipth, lhost, rhost, child_sa, encap))
                 {
                     commit_handle(ipth);
                 }
                 iptc_free(ipth);
             }
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 }
METHOD (forecast_listener_t , create_enumerator , enumerator_t * , private_forecast_listener_t * this, bool local)
Definition at line 625 of file forecast_listener.c.
References create_inner_local(), create_inner_remote(), enumerator_create_nested(), lock, and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(
                     this->entries->create_enumerator(this->entries),
                     (void*)(local ? create_inner_local : create_inner_remote),
                     this->lock, (void*)this->lock->unlock);
 }
METHOD (forecast_listener_t , set_broadcast , void , private_forecast_listener_t * this, host_t * bcast)
Definition at line 635 of file forecast_listener.c.
References host_t::get_family, host_t::get_sockaddr, and in.
 {
     if (bcast->get_family(bcast) == AF_INET)
     {
         struct sockaddr_in *in;
         in = (struct sockaddr_in*)bcast->get_sockaddr(bcast);
         this->broadcast = in->sin_addr.s_addr;
     }
 }
METHOD (forecast_listener_t , destroy , void , private_forecast_listener_t * this)
Definition at line 647 of file forecast_listener.c.
References spinlock_t::destroy, free(), and lock.
 {
     this->entries->destroy(this->entries);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool remove_entry (private_forecast_listener_t * this, struct iptc_handle * ipth, child_sa_t * child_sa) static
Remove an entry and rules for a given mark
Definition at line 418 of file forecast_listener.c.
References enumerator_t::destroy, entry_destroy(), enumerator_t::enumerate, FALSE, child_sa_t::get_mark, lock, manage_out(), manage_pre(), entry_t::mark, TRUE, spinlock_t::unlock, and mark_t::value.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool done = FALSE;
     this->lock->write_lock(this->lock);
     enumerator = this->entries->create_enumerator(this->entries);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->mark == child_sa->get_mark(child_sa, TRUE).value)
         {
             this->entries->remove_at(this->entries, enumerator);
             if (manage_pre(ipth, entry, FALSE) &&
                 manage_out(ipth, entry, FALSE))
             {
                 done = TRUE;
             }
             entry_destroy(entry);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return done;
 }
static bool ts2in (traffic_selector_t * ts, struct in_addr * addr, struct in_addr * mask) static
Convert an (IPv4) traffic selector to an address and mask
Definition at line 103 of file forecast_listener.c.
References bits, host_t::destroy, FALSE, host_t::get_address, traffic_selector_t::get_type, memcpy, net, chunk_t::ptr, traffic_selector_t::to_subnet, TRUE, and TS_IPV4_ADDR_RANGE.
Referenced by manage_out().
 {
     u_int8_t bits;
     host_t *net;
     if (ts->get_type(ts) == TS_IPV4_ADDR_RANGE &&
         ts->to_subnet(ts, &net, &bits))
     {
         memcpy(&addr->s_addr, net->get_address(net).ptr, 4);
         net->destroy(net);
         mask->s_addr = htonl(0xffffffffU << (32 - bits));
         return TRUE;
     }
     return FALSE;
 }
static bool ts_filter (entry_t * entry, traffic_selector_t ** ts, traffic_selector_t ** out, void * dummy, u_int32_t * mark, void * dummy2, bool * reinject) static
Filter to map entries to ts/mark
Definition at line 597 of file forecast_listener.c.
References entry_t::mark, entry_t::reinject, and TRUE.
Referenced by create_inner_local(), and create_inner_remote().
 {
     *out = *ts;
     *mark = entry->mark;
     *reinject = entry->reinject;
     return TRUE;
 }