strongSwan: tkm_kernel_sad.c File Reference
tkm_kernel_sad.c File Reference
#include <collections/linked_list.h>
#include <threading/mutex.h>
#include <utils/debug.h>
#include "tkm_kernel_sad.h"
Classes
struct private_tkm_kernel_sad_t
struct sad_entry_t
Typedefs
typedef struct
private_tkm_kernel_sad_t private_tkm_kernel_sad_t
typedef struct sad_entry_t sad_entry_t
Functions
static void sad_entry_destroy (sad_entry_t *entry)
static bool sad_entry_match (sad_entry_t *const entry, const host_t *const src, const host_t *const dst, const u_int32_t *const spi, const u_int8_t *const proto)
static bool sad_entry_match_dst (sad_entry_t *const entry, const u_int32_t *const reqid, const u_int32_t *const spi, const u_int8_t *const proto)
static bool sad_entry_match_esa_id (sad_entry_t *const entry, const esa_id_type *const esa_id)
static bool sad_entry_match_other_esa (sad_entry_t *const entry, const esa_id_type *const esa_id, const u_int32_t *const reqid)
static bool sad_entry_equal (sad_entry_t *const left, sad_entry_t *const right)
METHOD (tkm_kernel_sad_t, insert, bool, private_tkm_kernel_sad_t *const this, const esa_id_type esa_id, const u_int32_t reqid, const host_t *const src, const host_t *const dst, const u_int32_t spi_loc, const u_int32_t spi_rem, const u_int8_t proto)
METHOD (tkm_kernel_sad_t, get_esa_id, esa_id_type, private_tkm_kernel_sad_t *const this, const host_t *const src, const host_t *const dst, const u_int32_t spi, const u_int8_t proto)
METHOD (tkm_kernel_sad_t, get_other_esa_id, esa_id_type, private_tkm_kernel_sad_t *const this, const esa_id_type esa_id)
METHOD (tkm_kernel_sad_t, get_dst_host, host_t *, private_tkm_kernel_sad_t *const this, const u_int32_t reqid, const u_int32_t spi, const u_int8_t proto)
METHOD (tkm_kernel_sad_t, _remove, bool, private_tkm_kernel_sad_t *const this, const esa_id_type esa_id)
METHOD (tkm_kernel_sad_t, destroy, void, private_tkm_kernel_sad_t *this)
tkm_kernel_sad_t * tkm_kernel_sad_create ()
Typedef Documentation
typedef struct private_tkm_kernel_sad_t private_tkm_kernel_sad_t
Definition at line 23 of file tkm_kernel_sad.c.
typedef struct sad_entry_t sad_entry_t
Definition at line 47 of file tkm_kernel_sad.c.
Function Documentation
METHOD (tkm_kernel_sad_t , insert , bool , private_tkm_kernel_sad_t *const this, const esa_id_type esa_id, const u_int32_t reqid, const host_t *const src, const host_t *const dst, const u_int32_t spi_loc, const u_int32_t spi_rem, const u_int8_t proto)
Definition at line 173 of file tkm_kernel_sad.c.
References host_t::clone, data, DBG1, DBG3, DBG_KNL, sad_entry_t::dst, free(), INIT, mutex_t::lock, mutex, NOT_FOUND, result, sad_entry_equal(), sad_entry_t::src, and mutex_t::unlock.
 {
     status_t result;
     sad_entry_t *new_entry;
     INIT(new_entry,
          .esa_id = esa_id,
          .reqid = reqid,
          .src = (host_t *)src,
          .dst = (host_t *)dst,
          .spi_loc = spi_loc,
          .spi_rem = spi_rem,
          .proto = proto,
     );
     this->mutex->lock(this->mutex);
     result = this->data->find_first(this->data,
                                     (linked_list_match_t)sad_entry_equal, NULL,
                                     new_entry);
     if (result == NOT_FOUND)
     {
         DBG3(DBG_KNL, "inserting SAD entry (esa: %llu, reqid: %u, src: %H, "
              "dst: %H, spi_loc: %x, spi_rem: %x,proto: %u)", esa_id, reqid, src,
              dst, ntohl(spi_loc), ntohl(spi_rem), proto);
         new_entry->src = src->clone((host_t *)src);
         new_entry->dst = dst->clone((host_t *)dst);
         this->data->insert_last(this->data, new_entry);
     }
     else
     {
         DBG1(DBG_KNL, "SAD entry with esa id %llu already exists!", esa_id);
         free(new_entry);
     }
     this->mutex->unlock(this->mutex);
     return result == NOT_FOUND;
 }
METHOD (tkm_kernel_sad_t , get_esa_id , esa_id_type , private_tkm_kernel_sad_t *const this, const host_t *const src, const host_t *const dst, const u_int32_t spi, const u_int8_t proto)
Definition at line 213 of file tkm_kernel_sad.c.
References data, DBG3, DBG_KNL, sad_entry_t::esa_id, id, mutex_t::lock, mutex, res, sad_entry_match(), SUCCESS, and mutex_t::unlock.
 {
     esa_id_type id = 0;
     sad_entry_t *entry = NULL;
     this->mutex->lock(this->mutex);
     const status_t res = this->data->find_first(this->data,
                                                 (linked_list_match_t)sad_entry_match,
                                                 (void**)&entry, src, dst, &spi,
                                                 &proto);
     if (res == SUCCESS && entry)
     {
         id = entry->esa_id;
         DBG3(DBG_KNL, "returning ESA id %llu of SAD entry (src: %H, dst: %H, "
              "spi: %x, proto: %u)", id, src, dst, ntohl(spi), proto);
     }
     else
     {
         DBG3(DBG_KNL, "no SAD entry found for src %H, dst %H, spi %x, proto %u",
              src, dst, ntohl(spi), proto);
     }
     this->mutex->unlock(this->mutex);
     return id;
 }
METHOD (tkm_kernel_sad_t , get_other_esa_id , esa_id_type , private_tkm_kernel_sad_t *const this, const esa_id_type esa_id)
Definition at line 240 of file tkm_kernel_sad.c.
References data, DBG3, DBG_KNL, sad_entry_t::esa_id, id, mutex_t::lock, mutex, sad_entry_t::reqid, res, sad_entry_match_esa_id(), sad_entry_match_other_esa(), SUCCESS, and mutex_t::unlock.
 {
     esa_id_type id = 0;
     sad_entry_t *entry = NULL;
     u_int32_t reqid;
     status_t res;
     this->mutex->lock(this->mutex);
     res = this->data->find_first(this->data,
                                  (linked_list_match_t)sad_entry_match_esa_id,
                                  (void**)&entry, &esa_id);
     if (res == SUCCESS && entry)
     {
         reqid = entry->reqid;
     }
     else
     {
         DBG3(DBG_KNL, "no SAD entry found for ESA id %llu", esa_id);
         this->mutex->unlock(this->mutex);
         return id;
     }
     res = this->data->find_first(this->data,
                                  (linked_list_match_t)sad_entry_match_other_esa,
                                  (void**)&entry, &esa_id, &reqid);
     if (res == SUCCESS && entry)
     {
         id = entry->esa_id;
         DBG3(DBG_KNL, "returning ESA id %llu of other SAD entry with reqid %u",
              id, reqid);
     }
     this->mutex->unlock(this->mutex);
     return id;
 }
METHOD (tkm_kernel_sad_t , get_dst_host , host_t * , private_tkm_kernel_sad_t *const this, const u_int32_t reqid, const u_int32_t spi, const u_int8_t proto)
Definition at line 276 of file tkm_kernel_sad.c.
References data, DBG3, DBG_KNL, sad_entry_t::dst, dst, mutex_t::lock, mutex, res, sad_entry_match_dst(), SUCCESS, and mutex_t::unlock.
 {
     host_t *dst = NULL;
     sad_entry_t *entry = NULL;
     this->mutex->lock(this->mutex);
     const status_t res = this->data->find_first(this->data,
                                                 (linked_list_match_t)sad_entry_match_dst,
                                                 (void**)&entry, &reqid, &spi, &proto);
     if (res == SUCCESS && entry)
     {
         dst = entry->dst;
         DBG3(DBG_KNL, "returning destination host %H of SAD entry (reqid: %u,"
              " spi: %x, proto: %u)", dst, reqid, ntohl(spi), proto);
     }
     else
     {
         DBG3(DBG_KNL, "no SAD entry found for reqid %u, spi %x, proto: %u",
              reqid, ntohl(spi), proto);
     }
     this->mutex->unlock(this->mutex);
     return dst;
 }
METHOD (tkm_kernel_sad_t , _remove , bool , private_tkm_kernel_sad_t *const this, const esa_id_type esa_id)
Definition at line 302 of file tkm_kernel_sad.c.
References data, DBG1, DBG3, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, sad_entry_t::esa_id, FALSE, mutex_t::lock, mutex, sad_entry_destroy(), TRUE, and mutex_t::unlock.
 {
     sad_entry_t *current;
     bool removed = FALSE;
     enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     enumerator = this->data->create_enumerator(this->data);
     while (enumerator->enumerate(enumerator, (void **)&current))
     {
         if (current->esa_id == esa_id)
         {
             this->data->remove_at(this->data, enumerator);
             sad_entry_destroy(current);
             removed = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (removed)
     {
         DBG3(DBG_KNL, "removed SAD entry (esa: %llu)", esa_id);
     }
     else
     {
         DBG1(DBG_KNL, "no SAD entry with ESA id %llu found!", esa_id);
     }
     this->mutex->unlock(this->mutex);
     return removed;
 }
METHOD (tkm_kernel_sad_t , destroy , void , private_tkm_kernel_sad_t * this)
Definition at line 337 of file tkm_kernel_sad.c.
References data, mutex_t::destroy, free(), mutex, and sad_entry_destroy().
 {
     this->mutex->destroy(this->mutex);
     this->data->destroy_function(this->data, (void*)sad_entry_destroy);
     free(this);
 }
static void sad_entry_destroy (sad_entry_t * entry) static
Destroy an sad_entry_t object.
Definition at line 94 of file tkm_kernel_sad.c.
References DESTROY_IF, sad_entry_t::dst, free(), and sad_entry_t::src.
Referenced by METHOD().
 {
     if (entry)
     {
         DESTROY_IF(entry->src);
         DESTROY_IF(entry->dst);
         free(entry);
     }
 }
static bool sad_entry_equal (sad_entry_t *const left, sad_entry_t *const right) static
Compare two SAD entries for equality.
Definition at line 157 of file tkm_kernel_sad.c.
References sad_entry_t::dst, sad_entry_t::esa_id, FALSE, host_t::ip_equals, sad_entry_t::proto, sad_entry_t::reqid, sad_entry_t::spi_loc, sad_entry_t::spi_rem, and sad_entry_t::src.
Referenced by METHOD().
 {
     if (left->src == NULL || left->dst == NULL || right->src == NULL ||
         right->dst == NULL)
     {
         return FALSE;
     }
     return left->esa_id == right->esa_id &&
            left->reqid == right->reqid &&
            left->src->ip_equals(left->src, right->src) &&
            left->dst->ip_equals(left->dst, right->dst) &&
            left->spi_loc == right->spi_loc &&
            left->spi_rem == right->spi_rem &&
            left->proto == right->proto;
 }
static bool sad_entry_match (sad_entry_t *const entry, const host_t *const src, const host_t *const dst, const u_int32_t *const spi, const u_int8_t *const proto) static
Find a list entry with given src, dst, (remote) spi and proto values.
Definition at line 107 of file tkm_kernel_sad.c.
References sad_entry_t::dst, FALSE, host_t::ip_equals, sad_entry_t::proto, proto, sad_entry_t::spi_rem, and sad_entry_t::src.
Referenced by METHOD().
 {
     if (entry->src == NULL || entry->dst == NULL)
     {
         return FALSE;
     }
     return src->ip_equals(entry->src, (host_t *)src) &&
            dst->ip_equals(entry->dst, (host_t *)dst) &&
            entry->spi_rem == *spi && entry->proto == *proto;
 }
static bool sad_entry_match_dst (sad_entry_t *const entry, const u_int32_t *const reqid, const u_int32_t *const spi, const u_int8_t *const proto) static
Find a list entry with given reqid, spi and proto values.
Definition at line 124 of file tkm_kernel_sad.c.
References sad_entry_t::proto, proto, sad_entry_t::reqid, and sad_entry_t::spi_rem.
Referenced by METHOD().
 {
     return entry->reqid   == *reqid &&
            entry->spi_rem == *spi   &&
            entry->proto   == *proto;
 }
static bool sad_entry_match_esa_id (sad_entry_t *const entry, const esa_id_type *const esa_id) static
Find a list entry with given esa id.
Definition at line 137 of file tkm_kernel_sad.c.
References sad_entry_t::esa_id.
Referenced by METHOD().
 {
     return entry->esa_id == *esa_id;
 }
static bool sad_entry_match_other_esa (sad_entry_t *const entry, const esa_id_type *const esa_id, const u_int32_t *const reqid) static
Find a list entry with given reqid and different esa id.
Definition at line 146 of file tkm_kernel_sad.c.
References sad_entry_t::esa_id, and sad_entry_t::reqid.
Referenced by METHOD().
 {
     return entry->reqid  == *reqid &&
            entry->esa_id != *esa_id;
 }