strongSwan: tls_aead
tls_aead
tls
Classes
struct tls_aead_t
Typedefs
typedef struct tls_aead_t tls_aead_t
Functions
tls_aead_t * tls_aead_create_explicit (integrity_algorithm_t mac, encryption_algorithm_t encr, size_t encr_size)
tls_aead_t * tls_aead_create_implicit (integrity_algorithm_t mac, encryption_algorithm_t encr, size_t encr_size)
tls_aead_t * tls_aead_create_null (integrity_algorithm_t mac)
tls_aead_t * tls_aead_create_aead (encryption_algorithm_t encr, size_t encr_size)
Detailed Description
Typedef Documentation
typedef struct tls_aead_t tls_aead_t
Definition at line 24 of file tls_aead.h.
Function Documentation
tls_aead_t* tls_aead_create_aead (encryption_algorithm_t encr, size_t encr_size)
Create a tls_aead instance using real a AEAD cipher.
Parameters
encr AEAD encryption algorithm
encr_size encryption key size, in bytes
Returns
TLS AEAD transform
See header
Definition at line 169 of file tls_aead.c.
References aead, crypto_factory_t::create_aead, library_t::crypto, destroy(), ENCR_AES_CCM_ICV12, ENCR_AES_CCM_ICV16, ENCR_AES_CCM_ICV8, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, ENCR_CAMELLIA_CCM_ICV12, ENCR_CAMELLIA_CCM_ICV16, ENCR_CAMELLIA_CCM_ICV8, free(), aead_t::get_block_size, INIT, lib, and salt.
Referenced by create_aead().
 {
     private_tls_aead_t *this;
     size_t salt;
     switch (encr)
     {
         case ENCR_AES_GCM_ICV8:
         case ENCR_AES_GCM_ICV12:
         case ENCR_AES_GCM_ICV16:
         case ENCR_AES_CCM_ICV8:
         case ENCR_AES_CCM_ICV12:
         case ENCR_AES_CCM_ICV16:
         case ENCR_CAMELLIA_CCM_ICV8:
         case ENCR_CAMELLIA_CCM_ICV12:
         case ENCR_CAMELLIA_CCM_ICV16:
             salt = 4;
             break;
         default:
             return NULL;
     }
     INIT(this,
         .public = {
             .encrypt = _encrypt,
             .decrypt = _decrypt,
             .get_mac_key_size = _get_mac_key_size,
             .get_encr_key_size = _get_encr_key_size,
             .get_iv_size = _get_iv_size,
             .set_keys = _set_keys,
             .destroy = _destroy,
         },
         .aead = lib->crypto->create_aead(lib->crypto, encr, encr_size, salt),
         .salt = salt,
     );
     if (!this->aead)
     {
         free(this);
         return NULL;
     }
     if (this->aead->get_block_size(this->aead) != 1)
     {   /* TLS does not define any padding scheme for AEAD */
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
tls_aead_t* tls_aead_create_explicit (integrity_algorithm_t mac, encryption_algorithm_t encr, size_t encr_size)
Create a tls_aead instance using traditional transforms, explicit IV.
An explicit IV means that the IV is prepended to each TLS record. This is the mechanism used in TLS 1.1 and newer.
Parameters
mac integrity protection algorithm
encr encryption algorithm
encr_size encryption key size, in bytes
Returns
TLS AEAD transform
See header
Definition at line 202 of file tls_aead_expl.c.
References crypto_factory_t::create_crypter, crypto_factory_t::create_signer, crypter, library_t::crypto, destroy(), INIT, iv_gen_rand_create(), lib, and signer.
Referenced by create_traditional().
 {
     private_tls_aead_t *this;
     INIT(this,
         .public = {
             .encrypt = _encrypt,
             .decrypt = _decrypt,
             .get_mac_key_size = _get_mac_key_size,
             .get_encr_key_size = _get_encr_key_size,
             .get_iv_size = _get_iv_size,
             .set_keys = _set_keys,
             .destroy = _destroy,
         },
         .crypter = lib->crypto->create_crypter(lib->crypto, encr, encr_size),
         .signer = lib->crypto->create_signer(lib->crypto, mac),
         .iv_gen = iv_gen_rand_create(),
     );
     if (!this->crypter || !this->signer)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
tls_aead_t* tls_aead_create_implicit (integrity_algorithm_t mac, encryption_algorithm_t encr, size_t encr_size)
Create a tls_aead instance using traditional transforms, implicit IV.
An implicit IV uses a first IV derived from the TLS keymat, which then gets replaced by the last encrypted records tail. This is the mechanism used for TLS 1.0 and older.
Parameters
mac integrity protection algorithm
encr encryption algorithm
encr_size encryption key size, in bytes
Returns
TLS AEAD transform
See header
Definition at line 194 of file tls_aead_impl.c.
References chunk_alloc, crypto_factory_t::create_crypter, crypto_factory_t::create_signer, crypter, library_t::crypto, destroy(), INIT, lib, and signer.
Referenced by create_traditional().
 {
     private_tls_aead_t *this;
     INIT(this,
         .public = {
             .encrypt = _encrypt,
             .decrypt = _decrypt,
             .get_mac_key_size = _get_mac_key_size,
             .get_encr_key_size = _get_encr_key_size,
             .get_iv_size = _get_iv_size,
             .set_keys = _set_keys,
             .destroy = _destroy,
         },
         .crypter = lib->crypto->create_crypter(lib->crypto, encr, encr_size),
         .signer = lib->crypto->create_signer(lib->crypto, mac),
     );
     if (!this->crypter || !this->signer)
     {
         destroy(this);
         return NULL;
     }
     this->iv = chunk_alloc(this->crypter->get_iv_size(this->crypter));
     return &this->public;
 }
tls_aead_t* tls_aead_create_null (integrity_algorithm_t alg)
Create a tls_aead instance using NULL encryption.
As no IV is involved with null encryption, this AEAD works with any version of TLS.
Parameters
mac integrity protection algorithm
Returns
TLS AEAD transform
See header
Definition at line 135 of file tls_aead_null.c.
References crypto_factory_t::create_signer, library_t::crypto, free(), INIT, lib, and signer.
Referenced by create_null().
 {
     private_tls_aead_t *this;
     INIT(this,
         .public = {
             .encrypt = _encrypt,
             .decrypt = _decrypt,
             .get_mac_key_size = _get_mac_key_size,
             .get_encr_key_size = _get_encr_key_size,
             .get_iv_size = _get_iv_size,
             .set_keys = _set_keys,
             .destroy = _destroy,
         },
         .signer = lib->crypto->create_signer(lib->crypto, alg),
     );
     if (!this->signer)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }