strongSwan: vici_query
vici_query
vici
Classes
struct vici_query_t
Typedefs
typedef struct vici_query_t vici_query_t
Functions
vici_query_t * vici_query_create (vici_dispatcher_t *dispatcher)
Detailed Description
Typedef Documentation
typedef struct vici_query_t vici_query_t
Definition at line 49 of file vici_query.h.
Function Documentation
vici_query_t* vici_query_create (vici_dispatcher_t * dispatcher)
Create a vici_query instance.
Parameters
dispatcher dispatcher to receive requests from
Returns
query handler
See header
Definition at line 1236 of file vici_query.c.
References INIT, manage_commands(), time_monotonic(), and TRUE.
Referenced by register_vici().
 {
     private_vici_query_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .ike_updown = _ike_updown,
                 .ike_rekey = _ike_rekey,
                 .child_updown = _child_updown,
                 .child_rekey = _child_rekey,
             },
             .destroy = _destroy,
         },
         .dispatcher = dispatcher,
         .uptime = time_monotonic(NULL),
     );
     manage_commands(this, TRUE);
     return &this->public;
 }