strongSwan: endpoint_notify.c File Reference
endpoint_notify.c File Reference
#include "endpoint_notify.h"
#include <math.h>
#include <daemon.h>
Classes
struct private_endpoint_notify_t
Typedefs
typedef struct
private_endpoint_notify_t private_endpoint_notify_t
Functions
ENUM (me_endpoint_type_names, HOST, RELAYED,"HOST","PEER_REFLEXIVE","SERVER_REFLEXIVE","RELAYED")
static private_endpoint_notify_t * endpoint_notify_create ()
static status_t parse_uint8 (u_int8_t **cur, u_int8_t *top, u_int8_t *val)
static status_t parse_uint16 (u_int8_t **cur, u_int8_t *top, u_int16_t *val)
static status_t parse_uint32 (u_int8_t **cur, u_int8_t *top, u_int32_t *val)
static status_t parse_notification_data (private_endpoint_notify_t *this, chunk_t data)
static chunk_t build_notification_data (private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, build_notify, notify_payload_t *, private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, get_priority, u_int32_t, private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, set_priority, void, private_endpoint_notify_t *this, u_int32_t priority)
METHOD (endpoint_notify_t, get_type, me_endpoint_type_t, private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, get_family, me_endpoint_family_t, private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, get_host, host_t *, private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, get_base, host_t *, private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, clone_, endpoint_notify_t *, private_endpoint_notify_t *this)
METHOD (endpoint_notify_t, destroy, void, private_endpoint_notify_t *this)
endpoint_notify_t * endpoint_notify_create_from_host (me_endpoint_type_t type, host_t *host, host_t *base)
endpoint_notify_t * endpoint_notify_create_from_payload (notify_payload_t *notify)
Typedef Documentation
typedef struct private_endpoint_notify_t private_endpoint_notify_t
Definition at line 22 of file endpoint_notify.c.
Function Documentation
static chunk_t build_notification_data (private_endpoint_notify_t * this) static
Generates the notification data of a ME_ENDPOINT notify
Definition at line 190 of file endpoint_notify.c.
References chunk_cat, chunk_empty, chunk_from_thing, data, DBG3, DBG_IKE, family, port, and type.
Referenced by METHOD().
 {
     chunk_t prio_chunk, family_chunk, type_chunk, port_chunk, addr_chunk;
     chunk_t data;
     u_int32_t prio;
     u_int16_t port;
     u_int8_t family, type;
     prio = htonl(this->priority);
     prio_chunk = chunk_from_thing(prio);
     family = this->family;
     family_chunk = chunk_from_thing(family);
     type = this->type;
     type_chunk = chunk_from_thing(type);
     if (this->endpoint)
     {
         port = htons(this->endpoint->get_port(this->endpoint));
         addr_chunk = this->endpoint->get_address(this->endpoint);
     }
     else
     {
         port = 0;
         addr_chunk = chunk_empty;
     }
     port_chunk = chunk_from_thing(port);
     /* data = prio | family | type | port | addr */
     data = chunk_cat("ccccc", prio_chunk, family_chunk, type_chunk,
                      port_chunk, addr_chunk);
     DBG3(DBG_IKE, "me_endpoint_data %B", &data);
     return data;
 }
static private_endpoint_notify_t * endpoint_notify_create () static
Forward declaration
Creates an empty endpoint notify
Definition at line 310 of file endpoint_notify.c.
References INIT, NO_FAMILY, and NO_TYPE.
Referenced by endpoint_notify_create_from_host(), endpoint_notify_create_from_payload(), and METHOD().
 {
     private_endpoint_notify_t *this;
     INIT(this,
         .public = {
             .get_priority = _get_priority,
             .set_priority = _set_priority,
             .get_type = _get_type,
             .get_family = _get_family,
             .get_host = _get_host,
             .get_base = _get_base,
             .build_notify = _build_notify,
             .clone = _clone_,
             .destroy = _destroy,
         },
         .family = NO_FAMILY,
         .type = NO_TYPE,
     );
     return this;
 }
ENUM (me_endpoint_type_names , HOST , RELAYED , "HOST" , "PEER_REFLEXIVE" , "SERVER_REFLEXIVE" , "RELAYED")
METHOD (endpoint_notify_t , build_notify , notify_payload_t * , private_endpoint_notify_t * this)
Definition at line 224 of file endpoint_notify.c.
References build_notification_data(), chunk_free(), data, ME_ENDPOINT, notify(), notify_payload_create(), PLV2_NOTIFY, notify_payload_t::set_notification_data, and notify_payload_t::set_notify_type.
 {
     chunk_t data;
     notify_payload_t *notify;
     notify = notify_payload_create(PLV2_NOTIFY);
     notify->set_notify_type(notify, ME_ENDPOINT);
     data = build_notification_data(this);
     notify->set_notification_data(notify, data);
     chunk_free(&data);
     return notify;
 }
METHOD (endpoint_notify_t , get_priority , u_int32_t , private_endpoint_notify_t * this)
Definition at line 240 of file endpoint_notify.c.
 {
     return this->priority;
 }
METHOD (endpoint_notify_t , set_priority , void , private_endpoint_notify_t * this, u_int32_t priority)
Definition at line 246 of file endpoint_notify.c.
 {
     this->priority = priority;
 }
METHOD (endpoint_notify_t , get_type , me_endpoint_type_t , private_endpoint_notify_t * this)
Definition at line 252 of file endpoint_notify.c.
References type.
 {
     return this->type;
 }
METHOD (endpoint_notify_t , get_family , me_endpoint_family_t , private_endpoint_notify_t * this)
Definition at line 258 of file endpoint_notify.c.
References family.
 {
     return this->family;
 }
METHOD (endpoint_notify_t , get_host , host_t * , private_endpoint_notify_t * this)
Definition at line 264 of file endpoint_notify.c.
 {
     return this->endpoint;
 }
METHOD (endpoint_notify_t , get_base , host_t * , private_endpoint_notify_t * this)
Definition at line 270 of file endpoint_notify.c.
References base.
 {
     return (!this->base) ? this->endpoint : this->base;
 }
METHOD (endpoint_notify_t , clone_ , endpoint_notify_t * , private_endpoint_notify_t * this)
Definition at line 276 of file endpoint_notify.c.
References private_endpoint_notify_t::base, base, host_t::clone, private_endpoint_notify_t::endpoint, endpoint_notify_create(), private_endpoint_notify_t::family, family, private_endpoint_notify_t::priority, private_endpoint_notify_t::public, private_endpoint_notify_t::type, and type.
 {
     private_endpoint_notify_t *clone;
     clone = endpoint_notify_create();
     clone->priority = this->priority;
     clone->type = this->type;
     clone->family = this->family;
     if (this->endpoint)
     {
         clone->endpoint = this->endpoint->clone(this->endpoint);
     }
     if (this->base)
     {
         clone->base = this->base->clone(this->base);
     }
     return &clone->public;
 }
METHOD (endpoint_notify_t , destroy , void , private_endpoint_notify_t * this)
Definition at line 299 of file endpoint_notify.c.
References base, DESTROY_IF, and free().
 {
     DESTROY_IF(this->endpoint);
     DESTROY_IF(this->base);
     free(this);
 }
static status_t parse_notification_data (private_endpoint_notify_t * this, chunk_t data) static
Parses the notification data of a ME_ENDPOINT notify
Definition at line 122 of file endpoint_notify.c.
References addr, DBG1, DBG3, DBG_IKE, FAILED, family, host_create_from_chunk(), IPv4, IPv6, chunk_t::len, MAX_FAMILY, MAX_TYPE, NO_FAMILY, NO_TYPE, parse_uint16(), parse_uint32(), parse_uint8(), port, chunk_t::ptr, SUCCESS, and type.
Referenced by endpoint_notify_create_from_payload().
 {
     u_int8_t family, type, addr_family;
     u_int16_t port;
     chunk_t addr;
     u_int8_t *cur = data.ptr;
     u_int8_t *top = data.ptr + data.len;
     DBG3(DBG_IKE, "me_endpoint_data %B", &data);
     if (parse_uint32(&cur, top, &this->priority) != SUCCESS)
     {
         DBG1(DBG_IKE, "failed to parse ME_ENDPOINT: invalid priority");
         return FAILED;
     }
     if (parse_uint8(&cur, top, &family) != SUCCESS || family >= MAX_FAMILY)
     {
         DBG1(DBG_IKE, "failed to parse ME_ENDPOINT: invalid family");
         return FAILED;
     }
     this->family = (me_endpoint_family_t)family;
     if (parse_uint8(&cur, top, &type) != SUCCESS ||
         type == NO_TYPE || type >= MAX_TYPE)
     {
         DBG1(DBG_IKE, "failed to parse ME_ENDPOINT: invalid type");
         return FAILED;
     }
     this->type = (me_endpoint_type_t)type;
     addr_family = AF_INET;
     addr.len = 4;
     switch(this->family)
     {
         case IPv6:
             addr_family = AF_INET6;
             addr.len = 16;
             /* fall-through */
         case IPv4:
             if (parse_uint16(&cur, top, &port) != SUCCESS)
             {
                 DBG1(DBG_IKE, "failed to parse ME_ENDPOINT: invalid port");
                 return FAILED;
             }
             if (cur + addr.len > top)
             {
                 DBG1(DBG_IKE, "failed to parse ME_ENDPOINT: invalid IP address");
                 return FAILED;
             }
             addr.ptr = cur;
             this->endpoint = host_create_from_chunk(addr_family, addr, port);
             break;
         case NO_FAMILY:
         default:
             this->endpoint = NULL;
             break;
     }
     return SUCCESS;
 }
static status_t parse_uint16 (u_int8_t ** cur, u_int8_t * top, u_int16_t * val) static
Definition at line 97 of file endpoint_notify.c.
References FAILED, and SUCCESS.
Referenced by parse_notification_data().
 {
     if (*cur + sizeof(u_int16_t) > top)
     {
         return FAILED;
     }
     *val =  ntohs(*(u_int16_t*)*cur);
     *cur += sizeof(u_int16_t);
     return SUCCESS;
 }
static status_t parse_uint32 (u_int8_t ** cur, u_int8_t * top, u_int32_t * val) static
Definition at line 108 of file endpoint_notify.c.
References FAILED, and SUCCESS.
Referenced by parse_notification_data().
 {
     if (*cur + sizeof(u_int32_t) > top)
     {
         return FAILED;
     }
     *val =  ntohl(*(u_int32_t*)*cur);
     *cur += sizeof(u_int32_t);
     return SUCCESS;
 }
static status_t parse_uint8 (u_int8_t ** cur, u_int8_t * top, u_int8_t * val) static
Helper functions to parse integer values
Definition at line 86 of file endpoint_notify.c.
References FAILED, and SUCCESS.
Referenced by parse_notification_data().
 {
     if (*cur + sizeof(u_int8_t) > top)
     {
         return FAILED;
     }
     *val =  *(u_int8_t*)*cur;
     *cur += sizeof(u_int8_t);
     return SUCCESS;
 }