strongSwan: pb_error_msg.c File Reference
pb_error_msg.c File Reference
#include "pb_error_msg.h"
#include <tnc/tnccs/tnccs.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_pb_error_msg_t
Macros
#define ERROR_FLAG_NONE 0x00
#define ERROR_FLAG_FATAL (1<<7)
#define ERROR_RESERVED 0x0000
#define ERROR_HEADER_SIZE 8
Typedefs
typedef struct
private_pb_error_msg_t private_pb_error_msg_t
Functions
ENUM (pb_tnc_error_code_names, PB_ERROR_UNEXPECTED_BATCH_TYPE, PB_ERROR_VERSION_NOT_SUPPORTED,"Unexpected Batch Type","Invalid Parameter","Local Error","Unsupported Mandatory Message","Version Not Supported")
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_error_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_error_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_error_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_error_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, get_ref, pb_tnc_msg_t *, private_pb_error_msg_t *this)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_error_msg_t *this)
METHOD (pb_error_msg_t, get_fatal_flag, bool, private_pb_error_msg_t *this)
METHOD (pb_error_msg_t, get_vendor_id, u_int32_t, private_pb_error_msg_t *this)
METHOD (pb_error_msg_t, get_error_code, u_int16_t, private_pb_error_msg_t *this)
METHOD (pb_error_msg_t, get_offset, u_int32_t, private_pb_error_msg_t *this)
METHOD (pb_error_msg_t, get_bad_version, u_int8_t, private_pb_error_msg_t *this)
METHOD (pb_error_msg_t, set_bad_version, void, private_pb_error_msg_t *this, u_int8_t version)
pb_tnc_msg_t * pb_error_msg_create (bool fatal, u_int32_t vendor_id, pb_tnc_error_code_t error_code)
pb_tnc_msg_t * pb_error_msg_create_with_offset (bool fatal, u_int32_t vendor_id, pb_tnc_error_code_t error_code, u_int32_t error_offset)
pb_tnc_msg_t * pb_error_msg_create_from_data (chunk_t data)
Macro Definition Documentation
#define ERROR_FLAG_FATAL (1<<7)
Definition at line 51 of file pb_error_msg.c.
Referenced by METHOD().
#define ERROR_FLAG_NONE 0x00
PB-Error message (see section 4.9 of RFC 5793)
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | Error Code Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Error Code | Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Error Parameters (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 50 of file pb_error_msg.c.
Referenced by METHOD().
#define ERROR_HEADER_SIZE 8
Definition at line 53 of file pb_error_msg.c.
Referenced by METHOD().
#define ERROR_RESERVED 0x0000
Definition at line 52 of file pb_error_msg.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pb_error_msg_t private_pb_error_msg_t
Definition at line 34 of file pb_error_msg.c.
Function Documentation
ENUM (pb_tnc_error_code_names , PB_ERROR_UNEXPECTED_BATCH_TYPE , PB_ERROR_VERSION_NOT_SUPPORTED , "Unexpected Batch Type" , "Invalid Parameter" , "Local Error" , "Unsupported Mandatory Message" , "Version Not Supported")
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_error_msg_t * this)
Definition at line 106 of file pb_error_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_error_msg_t * this)
Definition at line 112 of file pb_error_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_error_msg_t * this)
Definition at line 118 of file pb_error_msg.c.
References bio_writer_create(), chunk_clone, bio_writer_t::destroy, encoding, error_code, ERROR_FLAG_FATAL, ERROR_FLAG_NONE, ERROR_HEADER_SIZE, ERROR_RESERVED, bio_writer_t::get_buf, PB_ERROR_VERSION_NOT_SUPPORTED, PB_TNC_VERSION, bio_writer_t::write_uint16, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     /* build message header */
     writer = bio_writer_create(ERROR_HEADER_SIZE);
     writer->write_uint8 (writer, this->fatal ?
                          ERROR_FLAG_FATAL : ERROR_FLAG_NONE);
     writer->write_uint24(writer, this->vendor_id);
     writer->write_uint16(writer, this->error_code);
     writer->write_uint16(writer, ERROR_RESERVED);
     /* build message body */
     if (this->error_code == PB_ERROR_VERSION_NOT_SUPPORTED)
     {
         /* Bad version */
         writer->write_uint8(writer, this->bad_version);
         writer->write_uint8(writer, PB_TNC_VERSION); /* Max version */
         writer->write_uint8(writer, PB_TNC_VERSION); /* Min version */
         writer->write_uint8(writer, 0x00);           /* Reserved */
     }
     else
     {
         /* Error Offset */
         writer->write_uint32(writer, this->error_offset);
     }
     this->encoding = writer->get_buf(writer);
     this->encoding = chunk_clone(this->encoding);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_error_msg_t * this, u_int32_t * offset)
Definition at line 155 of file pb_error_msg.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, encoding, error_code, ERROR_FLAG_FATAL, ERROR_FLAG_NONE, ERROR_HEADER_SIZE, FAILED, flags, PB_ERROR_VERSION_NOT_SUPPORTED, PB_MSG_ERROR, pb_tnc_msg_type_names, PEN_IETF, bio_reader_t::read_uint16, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, and SUCCESS.
 {
     u_int8_t flags, max_version, min_version;
     u_int16_t reserved;
     bio_reader_t *reader;
     if (this->encoding.len < ERROR_HEADER_SIZE)
     {
         DBG1(DBG_TNC,"%N message is shorter than header size of %u bytes",
              pb_tnc_msg_type_names, PB_MSG_ERROR, ERROR_HEADER_SIZE);
         *offset = 0;
         return FAILED;
     }
     /* process message header */
     reader = bio_reader_create(this->encoding);
     reader->read_uint8 (reader, &flags);
     reader->read_uint24(reader, &this->vendor_id);
     reader->read_uint16(reader, &this->error_code);
     reader->read_uint16(reader, &reserved);
     this->fatal = (flags & ERROR_FLAG_FATAL) != ERROR_FLAG_NONE;
     if (this->vendor_id == PEN_IETF && reader->remaining(reader) == 4)
     {
         if (this->error_code == PB_ERROR_VERSION_NOT_SUPPORTED)
         {
             reader->read_uint8(reader, &this->bad_version);
             reader->read_uint8(reader, &max_version);
             reader->read_uint8(reader, &min_version);
         }
         else
         {
             reader->read_uint32(reader, &this->error_offset);
         }
     }
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , get_ref , pb_tnc_msg_t * , private_pb_error_msg_t * this)
Definition at line 196 of file pb_error_msg.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pb_interface;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_error_msg_t * this)
Definition at line 203 of file pb_error_msg.c.
References encoding, free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         free(this->encoding.ptr);
         free(this);
     }
 }
METHOD (pb_error_msg_t , get_fatal_flag , bool , private_pb_error_msg_t * this)
Definition at line 213 of file pb_error_msg.c.
 {
     return this->fatal;
 }
METHOD (pb_error_msg_t , get_vendor_id , u_int32_t , private_pb_error_msg_t * this)
Definition at line 219 of file pb_error_msg.c.
 {
     return this->vendor_id;
 }
METHOD (pb_error_msg_t , get_error_code , u_int16_t , private_pb_error_msg_t * this)
Definition at line 225 of file pb_error_msg.c.
References error_code.
 {
     return this->error_code;
 }
METHOD (pb_error_msg_t , get_offset , u_int32_t , private_pb_error_msg_t * this)
Definition at line 231 of file pb_error_msg.c.
 {
     return this->error_offset;
 }
METHOD (pb_error_msg_t , get_bad_version , u_int8_t , private_pb_error_msg_t * this)
Definition at line 237 of file pb_error_msg.c.
 {
     return this->bad_version;
 }
METHOD (pb_error_msg_t , set_bad_version , void , private_pb_error_msg_t * this, u_int8_t version)
Definition at line 243 of file pb_error_msg.c.
References version.
 {
     this->bad_version = version;
 }