strongSwan: tnccs_batch_t Struct Reference
tnccs_batch_t Struct Reference
tnccs_batch
#include "tnccs_batch.h"
Public Attributes
chunk_t(* get_encoding)(tnccs_batch_t *this)
void(* add_msg)(tnccs_batch_t *this, tnccs_msg_t *msg)
void(* build)(tnccs_batch_t *this)
status_t(* process)(tnccs_batch_t *this)
enumerator_t *(* create_msg_enumerator)(tnccs_batch_t *this)
enumerator_t *(* create_error_enumerator)(tnccs_batch_t *this)
void(* destroy)(tnccs_batch_t *this)
Detailed Description
Interface for a TNCCS 1.x Batch.
Definition at line 34 of file tnccs_batch.h.
Member Data Documentation
void(* tnccs_batch_t::add_msg)(tnccs_batch_t *this, tnccs_msg_t *msg)
Add TNCCS message
Parameters
msg TNCCS message to be addedd
Definition at line 48 of file tnccs_batch.h.
Referenced by METHOD().
void(* tnccs_batch_t::build)(tnccs_batch_t *this)
Build the TNCCS 1.x Batch
Definition at line 53 of file tnccs_batch.h.
enumerator_t*(* tnccs_batch_t::create_error_enumerator)(tnccs_batch_t *this)
Enumerates over all parsing errors
Returns
return error enumerator
Definition at line 74 of file tnccs_batch.h.
Referenced by METHOD().
enumerator_t*(* tnccs_batch_t::create_msg_enumerator)(tnccs_batch_t *this)
Enumerates over all TNCCS Messages
Returns
return message enumerator
Definition at line 67 of file tnccs_batch.h.
Referenced by METHOD().
void(* tnccs_batch_t::destroy)(tnccs_batch_t *this)
Destroys a tnccs_batch_t object.
Definition at line 79 of file tnccs_batch.h.
Referenced by METHOD().
chunk_t(* tnccs_batch_t::get_encoding)(tnccs_batch_t *this)
Get the encoding of the TNCCS 1.x Batch
Returns
encoded TNCCS 1.x batch
Definition at line 41 of file tnccs_batch.h.
status_t(* tnccs_batch_t::process)(tnccs_batch_t *this)
Process the TNCCS 1.x Batch
Returns
return processing status
Definition at line 60 of file tnccs_batch.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
tnccs_batch.h