strongSwan: unity_narrow
unity_narrow
unity
Classes
struct unity_narrow_t
Typedefs
typedef struct unity_narrow_t unity_narrow_t
Functions
unity_narrow_t * unity_narrow_create (unity_handler_t *handler)
Detailed Description
Typedef Documentation
typedef struct unity_narrow_t unity_narrow_t
Definition at line 28 of file unity_narrow.h.
Function Documentation
unity_narrow_t* unity_narrow_create (unity_handler_t * handler)
Create a unity_narrow instance.
See header
Definition at line 295 of file unity_narrow.c.
References hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), and INIT.
Referenced by unity_plugin_create().
 {
     private_unity_narrow_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .narrow = _narrow,
                 .message = _message,
                 .ike_updown = _ike_updown,
             },
             .destroy = _destroy,
         },
         .handler = handler,
         .wildcard_ts = hashtable_create(hashtable_hash_ptr,
                                         hashtable_equals_ptr, 4),
     );
     return &this->public;
 }