strongSwan: socket_manager_t Struct Reference
socket_manager_t Struct Reference
socket_manager
#include "socket_manager.h"
Public Attributes
status_t(* receive)(socket_manager_t *this, packet_t **packet)
status_t(* send)(socket_manager_t *this, packet_t *packet)
u_int16_t(* get_port)(socket_manager_t *this, bool nat_t)
socket_family_t(* supported_families)(socket_manager_t *this)
void(* add_socket)(socket_manager_t *this, socket_constructor_t create)
void(* remove_socket)(socket_manager_t *this, socket_constructor_t create)
void(* destroy)(socket_manager_t *this)
Detailed Description
Handle pluggable socket implementations and send/receive packets through it.
Definition at line 33 of file socket_manager.h.
Member Data Documentation
void(* socket_manager_t::add_socket)(socket_manager_t *this, socket_constructor_t create)
Register a socket constructor.
Parameters
create constructor for the socket
Definition at line 75 of file socket_manager.h.
Referenced by socket_register().
void(* socket_manager_t::destroy)(socket_manager_t *this)
Destroy a socket_manager_t.
Definition at line 87 of file socket_manager.h.
u_int16_t(* socket_manager_t::get_port)(socket_manager_t *this, bool nat_t)
Get the port the registered socket is listening on.
Parameters
nat_t TRUE to get the port used to float in case of NAT-T
Returns
the port, or 0, if no socket is registered
Definition at line 61 of file socket_manager.h.
Referenced by apply_port(), build_ike_cfg(), CALLBACK(), connect_(), create_peer_cfg(), generate_config(), ike_sa_create(), initiate_connection(), medcli_config_create(), medsrv_config_create(), METHOD(), resolve_hosts(), and setup_tunnel().
status_t(* socket_manager_t::receive)(socket_manager_t *this, packet_t **packet)
Receive a packet using the registered socket.
Parameters
packet allocated packet that has been received
Returns
SUCCESS when packet successfully received
FAILED when unable to receive
Definition at line 43 of file socket_manager.h.
Referenced by receive_packets().
void(* socket_manager_t::remove_socket)(socket_manager_t *this, socket_constructor_t create)
Unregister a registered socket constructor.
Parameters
create constructor for the socket
Definition at line 82 of file socket_manager.h.
Referenced by socket_register().
status_t(* socket_manager_t::send)(socket_manager_t *this, packet_t *packet)
Send a packet using the registered socket.
Parameters
packet packet to send out
Returns
SUCCESS when packet successfully sent
FAILED when unable to send
Definition at line 53 of file socket_manager.h.
Referenced by send_packets().
socket_family_t(* socket_manager_t::supported_families)(socket_manager_t *this)
Get the address families the registered socket is listening on.
Returns
address families
Definition at line 68 of file socket_manager.h.
Referenced by is_any_path_valid(), METHOD(), and resolve_hosts().
The documentation for this struct was generated from the following file:
socket_manager.h