strongSwan: eap_payload
eap_payload
payloads
Classes
struct eap_payload_t
Typedefs
typedef struct eap_payload_t eap_payload_t
Functions
eap_payload_t * eap_payload_create (void)
eap_payload_t * eap_payload_create_data (chunk_t data)
eap_payload_t * eap_payload_create_data_own (chunk_t data)
eap_payload_t * eap_payload_create_code (eap_code_t code, u_int8_t identifier)
eap_payload_t * eap_payload_create_nak (u_int8_t identifier, eap_type_t type, u_int32_t vendor, bool expanded)
Detailed Description
Typedef Documentation
typedef struct eap_payload_t eap_payload_t
Definition at line 26 of file eap_payload.h.
Function Documentation
eap_payload_t* eap_payload_create (void)
Creates an empty eap_payload_t object.
Returns
eap_payload_t object
Definition at line 319 of file eap_payload.c.
References INIT, and PL_NONE.
Referenced by eap_payload_create_data(), eap_payload_create_data_own(), and payload_create().
 {
     private_eap_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_payload_type,
                 .destroy = _destroy,
             },
             .get_data = _get_data,
             .set_data = _set_data,
             .get_code = _get_code,
             .get_identifier = _get_identifier,
             .get_type = _get_type,
             .get_types = _get_types,
             .is_expanded = _is_expanded,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
     );
     return &this->public;
 }
eap_payload_t* eap_payload_create_code (eap_code_t code, u_int8_t identifier)
Creates an eap_payload_t object with a code.
Could should be either EAP_SUCCESS/EAP_FAILURE, use constructor above otherwise.
Parameters
code EAP status code
identifier EAP identifier to use in payload
Returns
eap_payload_t object
Definition at line 376 of file eap_payload.c.
References chunk_from_chars, data, eap_payload_create_data(), htoun16(), chunk_t::len, and chunk_t::ptr.
Referenced by METHOD(), process_eap(), server_initiate_eap(), and server_process_eap().
 {
     chunk_t data;
     data = chunk_from_chars(code, identifier, 0, 0);
     htoun16(data.ptr + 2, data.len);
     return eap_payload_create_data(data);
 }
eap_payload_t* eap_payload_create_data (chunk_t data)
Creates an eap_payload_t object with data.
Parameters
data data, gets cloned
Returns
eap_payload_t object
Definition at line 353 of file eap_payload.c.
References eap_payload_create(), and set_data().
Referenced by eap_payload_create_code(), eap_payload_create_nak(), METHOD(), process_eap(), process_peer_challenge(), process_peer_success(), process_server_response(), process_server_retry(), and radius2ike().
 {
     eap_payload_t *this = eap_payload_create();
     this->set_data(this, data);
     return this;
 }
eap_payload_t* eap_payload_create_data_own (chunk_t data)
Creates an eap_payload_t object with data, owning the data.
Parameters
data data on heap, gets owned and freed
Returns
eap_payload_t object
Definition at line 364 of file eap_payload.c.
References eap_payload_create(), free(), chunk_t::ptr, and set_data().
Referenced by generate_payload().
 {
     eap_payload_t *this = eap_payload_create();
     this->set_data(this, data);
     free(data.ptr);
     return this;
 }
eap_payload_t* eap_payload_create_nak (u_int8_t identifier, eap_type_t type, u_int32_t vendor, bool expanded)
Creates an eap_payload_t EAP_RESPONSE containing an EAP_NAK.
Parameters
identifier EAP identifier to use in payload
type preferred auth type, 0 to send all supported types
vendor vendor identifier for auth type, 0 for default
expanded TRUE to send an expanded Nak
Returns
eap_payload_t object
Definition at line 406 of file eap_payload.c.
References bio_writer_create(), charon, eap_manager_t::create_enumerator, data, enumerator_t::destroy, bio_writer_t::destroy, daemon_t::eap, EAP_EXPANDED, EAP_NAK, eap_packet_t, eap_payload_create_data(), EAP_PEER, EAP_RESPONSE, enumerator_t::enumerate, FALSE, bio_writer_t::get_buf, htoun16(), chunk_t::len, length, chunk_t::ptr, TRUE, write_type(), bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
Referenced by client_process_eap(), and METHOD().
 {
     enumerator_t *enumerator;
     eap_type_t reg_type;
     u_int32_t reg_vendor;
     bio_writer_t *writer;
     chunk_t data;
     bool added_any = FALSE, found_vendor = FALSE;
     eap_payload_t *payload;
     writer = bio_writer_create(12);
     writer->write_uint8(writer, EAP_RESPONSE);
     writer->write_uint8(writer, identifier);
     /* write zero length, we update it once we know the length */
     writer->write_uint16(writer, 0);
     write_type(writer, EAP_NAK, 0, expanded);
     enumerator = charon->eap->create_enumerator(charon->eap, EAP_PEER);
     while (enumerator->enumerate(enumerator, &reg_type, &reg_vendor))
     {
         if ((type && type != reg_type) ||
             (type && vendor && vendor != reg_vendor))
         {   /* the preferred type is only sent if we actually find it */
             continue;
         }
         if (!reg_vendor || expanded)
         {
             write_type(writer, reg_type, reg_vendor, expanded);
             added_any = TRUE;
         }
         else if (reg_vendor)
         {   /* found vendor specifc method, but this is not an expanded Nak */
             found_vendor = TRUE;
         }
     }
     enumerator->destroy(enumerator);
     if (found_vendor)
     {   /* request an expanded authentication type */
         write_type(writer, EAP_EXPANDED, 0, expanded);
         added_any = TRUE;
     }
     if (!added_any)
     {   /* no methods added */
         write_type(writer, 0, 0, expanded);
     }
     /* set length */
     data = writer->get_buf(writer);
     htoun16(data.ptr + offsetof(eap_packet_t, length), data.len);
     payload = eap_payload_create_data(data);
     writer->destroy(writer);
     return payload;
 }