strongSwan: identification_t Struct Reference
identification_t Struct Reference
identification
#include "identification.h"
Public Attributes
chunk_t(* get_encoding)(identification_t *this)
id_type_t(* get_type)(identification_t *this)
u_int(* hash)(identification_t *this, u_int inc)
bool(* equals)(identification_t *this, identification_t *other)
id_match_t(* matches)(identification_t *this, identification_t *other)
bool(* contains_wildcards)(identification_t *this)
enumerator_t *(* create_part_enumerator)(identification_t *this)
identification_t *(* clone)(identification_t *this)
void(* destroy)(identification_t *this)
Detailed Description
Generic identification, such as used in ID payload.
Todo:
Support for ID_DER_ASN1_GN is minimal right now. Comparison between them and ID_IPV4_ADDR/RFC822_ADDR would be nice.
Definition at line 197 of file identification.h.
Member Data Documentation
identification_t*(* identification_t::clone)(identification_t *this)
Clone a identification_t instance.
Returns
clone of this
Definition at line 280 of file identification.h.
Referenced by add_auth_cfg(), add_cdps(), add_exclude(), add_include(), build_auth_cfg(), CALLBACK(), check_constraints(), check_list_create(), connect_(), dhcp_transaction_create(), eap_aka_peer_create(), eap_aka_server_create(), eap_dynamic_create(), eap_gtc_create_generic(), eap_identity_create_peer(), eap_identity_create_server(), eap_md5_create_peer(), eap_md5_create_server(), eap_mschapv2_create_generic(), eap_peap_peer_create(), eap_peap_server_create(), eap_radius_create(), eap_radius_xauth_create_server(), eap_sim_peer_create(), eap_sim_server_create(), eap_ttls_peer_create(), eap_ttls_server_create(), entry_create(), find_client_id(), find_smartcard_key(), generate(), generate_auth_cfg(), initiated_create(), issue(), list(), main(), mediation_callback_job_create(), mediation_job_create(), merge(), METHOD(), peer_create(), process_certificate(), process_identity(), process_ike_update(), process_start(), pubkey_cert_create(), put(), put_connected_peers(), register_peer(), replace_eap_identity(), sasl_plain_create(), schedule_interim(), START_TEST(), tls_peer_create(), tls_server_create(), tnccs_11_create(), tnccs_20_create(), tnccs_dynamic_create(), x509_cert_gen(), x509_crl_gen(), x509_ocsp_request_gen(), x509_pkcs10_gen(), xauth_eap_create_server(), xauth_generic_create_peer(), xauth_generic_create_server(), and xauth_pam_create_server().
bool(* identification_t::contains_wildcards)(identification_t *this)
Check if an ID is a wildcard ID.
If the ID represents multiple IDs (with wildcards, or as the type ID_ANY), TRUE is returned. If it is unique, FALSE is returned.
Returns
TRUE if ID contains wildcards
Definition at line 260 of file identification.h.
Referenced by add_initial_contact(), and METHOD().
enumerator_t*(* identification_t::create_part_enumerator)(identification_t *this)
Create an enumerator over subparts of an identity.
Some identities are built from several parts, e.g. an E-Mail consists of a username and a domain part, or a DistinguishedName contains several RDNs. For identity without subtypes (support), an empty enumerator is returned.
Returns
an enumerator over (id_part_t type, chunk_t data)
Definition at line 273 of file identification.h.
Referenced by dn_matches().
void(* identification_t::destroy)(identification_t *this)
Destroys a identification_t object.
Definition at line 285 of file identification.h.
Referenced by add_attribute_certs(), add_local_certs(), build_auth_cfg(), build_peer_cfg(), client(), destroy_entry_value(), entry_destroy(), get_matching_ike_sas(), get_private_by_cert(), has_privkey(), id_equals(), id_hash_equals(), id_matches(), id_matches_rev(), leases(), list(), load_shared(), main(), METHOD(), parse_directoryName(), process_eap(), process_identity(), process_reauthentication(), process_server_response(), process_start(), reauthenticate(), run_echo_client(), serve_echo(), START_TEST(), status_attr(), and unregister_peer().
bool(* identification_t::equals)(identification_t *this, identification_t *other)
Check if two identification_t objects are equal.
Parameters
other other identification_t object
Returns
TRUE if the IDs are equal
Definition at line 230 of file identification.h.
Referenced by add_attribute_certs(), connected_peers_match(), entry_equals(), equals(), find_private(), get_peer_by_id(), id_equals(), list_ike(), log_ike_sa(), match_initiated_by_ids(), METHOD(), process_server_response(), register_peer(), remove_include(), shared_entry_equals(), START_TEST(), and unregister_peer().
chunk_t(* identification_t::get_encoding)(identification_t *this)
Get the encoding of this id, to send over the network.
Result points to internal data, do not free.
Returns
a chunk containing the encoded bytes
Definition at line 207 of file identification.h.
Referenced by build_authorityKeyIdentifier(), build_generalName(), build_holder(), build_issuerAndSerialNumber(), build_requestList(), build_v2_form(), cert_filter(), certreq_payload_create_dn(), certs_filter(), challenge(), create_inner_cdp(), create_inner_cdp_hashandurl(), dn(), email_matches(), fqdn_matches(), generate(), hash(), hash_id_host(), id_hash(), id_payload_create_from_identification(), key_filter(), main(), METHOD(), pin_cb(), prepare_dhcp(), process_server_response(), process_start(), put_connected_peers(), reauthenticate(), remove_connected_peers(), send_certificate_request(), send_response(), and START_TEST().
id_type_t(* identification_t::get_type)(identification_t *this)
Get the type of this identification.
Returns
id_type_t
Definition at line 214 of file identification.h.
Referenced by build_auth_cfg(), build_generalName(), cert_filter(), client_process_eap(), create_identity(), create_lease_query(), get_identity(), get_peer_match(), get_type_pfx(), issue(), load_shared(), main(), METHOD(), name_constraint_inherited(), name_constraint_matches(), prepare_dhcp(), req(), self(), server_initiate_eap(), START_TEST(), stroke_list_pubkeys(), and write_id().
u_int(* identification_t::hash)(identification_t *this, u_int inc)
Create a hash value for this identification_t object.
Parameters
inc optional value for incremental hashing
Returns
hash value
Definition at line 222 of file identification.h.
Referenced by hash(), id_hash_equals(), and START_TEST().
id_match_t(* identification_t::matches)(identification_t *this, identification_t *other)
Check if an ID matches a wildcard ID.
An identification_t may contain wildcards, such as *.strongswan.org. This call checks if a given ID (e.g. tester.strongswan.org) belongs to a such wildcard ID. Returns > 0 if
IDs are identical
other is of type ID_ANY
other contains a wildcard and matches this
The larger the return value is, the better is the match. Zero means no match at all, 1 means a bad match, and 2 a slightly better match.
Parameters
other the ID containing one or more wildcards
Returns
match value as described above
Definition at line 249 of file identification.h.
Referenced by add_matching_ike_sas(), cdp_filter(), check_certificate(), create_inner_cdp_hashandurl(), get_peer_match(), has_owner(), id_matches(), id_matches_rev(), list(), and METHOD().
The documentation for this struct was generated from the following file:
identification.h