strongSwan: radius_message_t Struct Reference
radius_message_t Struct Reference
radius_message
#include "radius_message.h"
Public Attributes
enumerator_t *(* create_enumerator)(radius_message_t *this)
enumerator_t *(* create_vendor_enumerator)(radius_message_t *this)
void(* add)(radius_message_t *this, radius_attribute_type_t type, chunk_t data)
radius_message_code_t(* get_code)(radius_message_t *this)
u_int8_t(* get_identifier)(radius_message_t *this)
void(* set_identifier)(radius_message_t *this, u_int8_t identifier)
u_int8_t *(* get_authenticator)(radius_message_t *this)
chunk_t(* get_encoding)(radius_message_t *this)
bool(* sign)(radius_message_t *this, u_int8_t *req_auth, chunk_t secret, hasher_t *hasher, signer_t *signer, rng_t *rng, bool msg_auth)
bool(* verify)(radius_message_t *this, u_int8_t *req_auth, chunk_t secret, hasher_t *hasher, signer_t *signer)
bool(* crypt)(radius_message_t *this, chunk_t salt, chunk_t in, chunk_t out, chunk_t secret, hasher_t *hasher)
void(* destroy)(radius_message_t *this)
Detailed Description
A RADIUS message, contains attributes.
Definition at line 204 of file radius_message.h.
Member Data Documentation
void(* radius_message_t::add)(radius_message_t *this, radius_attribute_type_t type, chunk_t data)
Add a RADIUS attribute to the message.
Parameters
type type of attribute to add
attribute data, gets cloned
Definition at line 229 of file radius_message.h.
Referenced by add_eap_identity(), add_ike_sa_parameters(), add_radius_request_attrs(), eap_radius_build_attributes(), METHOD(), queue2radius(), send_interim(), send_response(), send_start(), send_stop(), and verify_radius().
enumerator_t*(* radius_message_t::create_enumerator)(radius_message_t *this)
Create an enumerator over contained RADIUS attributes.
Returns
enumerator over (int type, chunk_t data)
Definition at line 211 of file radius_message.h.
Referenced by get_matching_ike_sas(), METHOD(), process_cfg_attributes(), process_class(), process_coa(), process_eap(), process_filter_id(), process_timeout(), radius2ike(), radius2queue(), and save_state().
enumerator_t*(* radius_message_t::create_vendor_enumerator)(radius_message_t *this)
Create an enumerator over contained RADIUS Vendor-ID attributes.
This enumerator parses only vendor specific attributes in the format recommended in RFC2865.
Returns
enumerator over (int vendor, int type, chunk_t data)
Definition at line 221 of file radius_message.h.
Referenced by process_cfg_attributes().
bool(* radius_message_t::crypt)(radius_message_t *this, chunk_t salt, chunk_t in, chunk_t out, chunk_t secret, hasher_t *hasher)
Perform RADIUS attribute en-/decryption.
Performs en-/decryption by XOring the hash-extended secret into data, as specified in RFC 2865 5.2 and used by RFC 2548.
Parameters
salt salt to append to message authenticator, if any
in data to en-/decrypt, multiple of HASH_SIZE_MD5
out en-/decrypted data, length equal to in
secret RADIUS secret
hasher MD5 hasher
Returns
TRUE if en-/decryption successful
Definition at line 305 of file radius_message.h.
Referenced by decrypt_mppe_key().
void(* radius_message_t::destroy)(radius_message_t *this)
Destroy the message.
Definition at line 311 of file radius_message.h.
Referenced by entry_destroy(), METHOD(), radius_receive(), receive(), receive_response(), save_retransmit(), send_interim(), send_message(), send_response(), send_start(), send_stop(), and verify_radius().
u_int8_t*(* radius_message_t::get_authenticator)(radius_message_t *this)
Get the 16 byte authenticator.
Returns
pointer to the Authenticator field
Definition at line 258 of file radius_message.h.
Referenced by encrypt_mppe_key(), METHOD(), and send_response().
radius_message_code_t(* radius_message_t::get_code)(radius_message_t *this)
Get the message type (code).
Returns
message code
Definition at line 237 of file radius_message.h.
Referenced by get_matching_ike_sas(), METHOD(), radius_receive(), receive(), send_message(), send_retransmit(), and verify_radius().
chunk_t(* radius_message_t::get_encoding)(radius_message_t *this)
Get the RADIUS message in its encoded form.
Returns
chunk pointing to internal RADIUS message.
Definition at line 265 of file radius_message.h.
Referenced by METHOD(), and send_message().
u_int8_t(* radius_message_t::get_identifier)(radius_message_t *this)
Get the message identifier.
Returns
message identifier
Definition at line 244 of file radius_message.h.
Referenced by METHOD(), radius_receive(), receive_response(), send_response(), and send_retransmit().
void(* radius_message_t::set_identifier)(radius_message_t *this, u_int8_t identifier)
Set the message identifier.
Parameters
identifier message identifier
Definition at line 251 of file radius_message.h.
Referenced by METHOD(), and send_response().
bool(* radius_message_t::sign)(radius_message_t *this, u_int8_t *req_auth, chunk_t secret, hasher_t *hasher, signer_t *signer, rng_t *rng, bool msg_auth)
Calculate and add the Message-Authenticator attribute to the message.
Parameters
req_auth 16 byte Authenticator of request, or NULL
secret shared RADIUS secret
signer HMAC-MD5 signer with secret set
hasher MD5 hasher
rng RNG to create Request-Authenticator, NULL to omit
msg_auth calculate and add Message-Authenticator
Returns
TRUE if signed successfully
Definition at line 278 of file radius_message.h.
Referenced by METHOD(), and send_response().
bool(* radius_message_t::verify)(radius_message_t *this, u_int8_t *req_auth, chunk_t secret, hasher_t *hasher, signer_t *signer)
Verify the integrity of a received RADIUS message.
Parameters
req_auth 16 byte Authenticator of request, or NULL
secret shared RADIUS secret
signer HMAC-MD5 signer with secret set
hasher MD5 hasher
Definition at line 289 of file radius_message.h.
Referenced by METHOD(), radius_receive(), and receive().
The documentation for this struct was generated from the following file:
radius_message.h