strongSwan: ietf_attr_port_filter.c File Reference
ietf_attr_port_filter.c File Reference
#include "ietf_attr_port_filter.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct port_entry_t
struct private_ietf_attr_port_filter_t
Macros
#define PORT_FILTER_ENTRY_SIZE 4
Typedefs
typedef struct
private_ietf_attr_port_filter_t private_ietf_attr_port_filter_t
typedef struct port_entry_t port_entry_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_port_filter_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_port_filter_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_port_filter_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_port_filter_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_port_filter_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_port_filter_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_port_filter_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_port_filter_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_port_filter_t *this)
METHOD (ietf_attr_port_filter_t, add_port, void, private_ietf_attr_port_filter_t *this, bool blocked, u_int8_t protocol, u_int16_t port)
static bool port_filter (void *null, port_entry_t **entry, bool *blocked, void *i2, u_int8_t *protocol, void *i3, u_int16_t *port)
METHOD (ietf_attr_port_filter_t, create_port_enumerator, enumerator_t *, private_ietf_attr_port_filter_t *this)
pa_tnc_attr_t * ietf_attr_port_filter_create (pen_type_t type)
pa_tnc_attr_t * ietf_attr_port_filter_create_from_data (size_t length, chunk_t data, pen_type_t type)
Macro Definition Documentation
#define PORT_FILTER_ENTRY_SIZE 4
PA-TNC Port Filter Type (see section 4.2.6 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved |B| Protocol | Port Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved |B| Protocol | Port Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 49 of file ietf_attr_port_filter.c.
Referenced by METHOD().
Typedef Documentation
typedef struct port_entry_t port_entry_t
Definition at line 26 of file ietf_attr_port_filter.c.
typedef struct private_ietf_attr_port_filter_t private_ietf_attr_port_filter_t
Definition at line 25 of file ietf_attr_port_filter.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_port_filter_t * this)
Definition at line 92 of file ietf_attr_port_filter.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_port_filter_t * this)
Definition at line 98 of file ietf_attr_port_filter.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_port_filter_t * this)
Definition at line 104 of file ietf_attr_port_filter.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_port_filter_t * this, bool noskip)
Definition at line 110 of file ietf_attr_port_filter.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_port_filter_t * this)
Definition at line 116 of file ietf_attr_port_filter.c.
References bio_writer_create(), port_entry_t::blocked, bio_writer_t::destroy, bio_writer_t::extract_buf, length, port_entry_t::port, PORT_FILTER_ENTRY_SIZE, port_entry_t::protocol, value, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     port_entry_t *entry;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(this->ports->get_count(this->ports) *
                                PORT_FILTER_ENTRY_SIZE);
     enumerator = this->ports->create_enumerator(this->ports);
     while (enumerator->enumerate(enumerator, &entry))
     {
         writer->write_uint8 (writer, entry->blocked ? 0x01 : 0x00);
         writer->write_uint8 (writer, entry->protocol);
         writer->write_uint16(writer, entry->port);
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_port_filter_t * this, u_int32_t * offset)
Definition at line 144 of file ietf_attr_port_filter.c.
References bio_reader_create(), port_entry_t::blocked, DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, malloc_thing, NEED_MORE, port_entry_t::port, PORT_FILTER_ENTRY_SIZE, port_entry_t::protocol, bio_reader_t::read_uint16, bio_reader_t::read_uint8, bio_reader_t::remaining, SUCCESS, and value.
 {
     bio_reader_t *reader;
     port_entry_t *entry;
     u_int8_t blocked;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len % PORT_FILTER_ENTRY_SIZE)
     {
         DBG1(DBG_TNC, "ietf port filter attribute value is not a multiple of %d",
              PORT_FILTER_ENTRY_SIZE);
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     while (reader->remaining(reader))
     {
         entry = malloc_thing(port_entry_t);
         reader->read_uint8 (reader, &blocked);
         entry->blocked = blocked & 0x01;
         reader->read_uint8 (reader, &entry->protocol);
         reader->read_uint16(reader, &entry->port);
         this->ports->insert_last(this->ports, entry);
     }
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_port_filter_t * this, chunk_t segment)
Definition at line 179 of file ietf_attr_port_filter.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_port_filter_t * this)
Definition at line 185 of file ietf_attr_port_filter.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_port_filter_t * this)
Definition at line 192 of file ietf_attr_port_filter.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         this->ports->destroy_function(this->ports, free);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_port_filter_t , add_port , void , private_ietf_attr_port_filter_t * this, bool blocked, u_int8_t protocol, u_int16_t port)
Definition at line 203 of file ietf_attr_port_filter.c.
References port_entry_t::blocked, malloc_thing, port_entry_t::port, port, port_entry_t::protocol, and protocol.
 {
     port_entry_t *entry;
     entry = malloc_thing(port_entry_t);
     entry->blocked = blocked;
     entry->protocol = protocol;
     entry->port = port;
     this->ports->insert_last(this->ports, entry);
 }
METHOD (ietf_attr_port_filter_t , create_port_enumerator , enumerator_t * , private_ietf_attr_port_filter_t * this)
Definition at line 229 of file ietf_attr_port_filter.c.
References enumerator_create_filter(), and port_filter().
 {
     return enumerator_create_filter(this->ports->create_enumerator(this->ports),
                     (void*)port_filter, NULL, NULL);
 }
static bool port_filter (void * null, port_entry_t ** entry, bool * blocked, void * i2, u_int8_t * protocol, void * i3, u_int16_t * port) static
Enumerate port filter entries
Definition at line 219 of file ietf_attr_port_filter.c.
References TRUE.
Referenced by METHOD().
 {
     *blocked = (*entry)->blocked;
     *protocol = (*entry)->protocol;
     *port = (*entry)->port;
     return TRUE;
 }