strongSwan: ntru_poly.c File Reference
ntru_poly.c File Reference
#include "ntru_poly.h"
#include <crypto/mgf1/mgf1_bitspender.h>
#include <utils/debug.h>
#include <utils/test.h>
Classes
struct indices_len_t
struct private_ntru_poly_t
Typedefs
typedef struct private_ntru_poly_t private_ntru_poly_t
typedef struct indices_len_t indices_len_t
Functions
METHOD (ntru_poly_t, get_size, size_t, private_ntru_poly_t *this)
METHOD (ntru_poly_t, get_indices, uint16_t *, private_ntru_poly_t *this)
static void ring_mult_i (uint16_t *a, indices_len_t len, uint16_t *indices, uint16_t N, uint16_t mod_q_mask, uint16_t *t, uint16_t *c)
METHOD (ntru_poly_t, get_array, void, private_ntru_poly_t *this, uint16_t *array)
METHOD (ntru_poly_t, ring_mult, void, private_ntru_poly_t *this, uint16_t *a, uint16_t *c)
METHOD (ntru_poly_t, destroy, void, private_ntru_poly_t *this)
static private_ntru_poly_t * ntru_poly_create (uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form)
ntru_poly_t * ntru_poly_create_from_seed (hash_algorithm_t alg, chunk_t seed, uint8_t c_bits, uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form)
ntru_poly_t * ntru_poly_create_from_data (uint16_t *data, uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form)
EXPORT_FUNCTION_FOR_TESTS (ntru, ntru_poly_create_from_seed)
EXPORT_FUNCTION_FOR_TESTS (ntru, ntru_poly_create_from_data)
Typedef Documentation
typedef struct indices_len_t indices_len_t
Definition at line 25 of file ntru_poly.c.
typedef struct private_ntru_poly_t private_ntru_poly_t
Definition at line 24 of file ntru_poly.c.
Function Documentation
EXPORT_FUNCTION_FOR_TESTS (ntru , ntru_poly_create_from_seed)
EXPORT_FUNCTION_FOR_TESTS (ntru , ntru_poly_create_from_data)
METHOD (ntru_poly_t , get_size , size_t , private_ntru_poly_t * this)
Definition at line 77 of file ntru_poly.c.
 {
     return this->num_indices;
 }
METHOD (ntru_poly_t , get_indices , uint16_t * , private_ntru_poly_t * this)
Definition at line 83 of file ntru_poly.c.
 {
     return this->indices;
 }
METHOD (ntru_poly_t , get_array , void , private_ntru_poly_t * this, uint16_t * array)
Definition at line 147 of file ntru_poly.c.
References free(), len, indices_len_t::m, malloc(), memset, N, indices_len_t::p, q, and ring_mult_i().
 {
     uint16_t *t, *bi;
     uint16_t mod_q_mask = this->q - 1;
     indices_len_t len;
     int i;
     /* form polynomial F or F1 */
     memset(array, 0x00, this->N * sizeof(uint16_t));
     bi = this->indices;
     len = this->indices_len[0];
     for (i = 0; i < len.p + len.m; i++)
     {
         array[bi[i]] = (i < len.p) ? 1 : mod_q_mask;
     }
     if (this->num_polynomials == 3)
     {
         /* allocate temporary array t */
         t = malloc(this->N * sizeof(uint16_t));
         /* form F1 * F2 */
         bi += len.p + len.m;
         len = this->indices_len[1];
         ring_mult_i(array, len, bi, this->N, mod_q_mask, t, array);
         /* form (F1 * F2) + F3 */
         bi += len.p + len.m;
         len = this->indices_len[2];
         for (i = 0; i < len.p + len.m; i++)
         {
             if (i < len.p)
             {
                 array[bi[i]] += 1;
             }
             else
             {
                 array[bi[i]] -= 1;
             }
             array[bi[i]] &= mod_q_mask;
         }
         free(t);
     }
 }
METHOD (ntru_poly_t , ring_mult , void , private_ntru_poly_t * this, uint16_t * a, uint16_t * c)
Definition at line 193 of file ntru_poly.c.
References free(), malloc(), N, q, and ring_mult_i().
 {
     uint16_t *t1, *t2;
     uint16_t *bi = this->indices;
     uint16_t mod_q_mask = this->q - 1;
     int i;
     /* allocate temporary array t1 */
     t1 = malloc(this->N * sizeof(uint16_t));
     if (this->num_polynomials == 1)
     {
         ring_mult_i(a, this->indices_len[0], bi, this->N, mod_q_mask, t1, c);
     }
     else
     {
         /* allocate temporary array t2 */
         t2 = malloc(this->N * sizeof(uint16_t));
         /* t1 = a * b1 */
         ring_mult_i(a, this->indices_len[0], bi, this->N, mod_q_mask, t1, t1);
         /* t1 = (a * b1) * b2 */
         bi += this->indices_len[0].p + this->indices_len[0].m;
         ring_mult_i(t1, this->indices_len[1], bi, this->N, mod_q_mask, t2, t1);
         /* t2 = a * b3 */
         bi += this->indices_len[1].p + this->indices_len[1].m;
         ring_mult_i(a, this->indices_len[2], bi, this->N, mod_q_mask, t2, t2);
         /* c = (a * b1 * b2) + (a * b3) */
         for (i = 0; i < this->N; i++)
         {
             c[i] = (t1[i] + t2[i]) & mod_q_mask;
         }
         free(t2);
     }
     free(t1);
 }
METHOD (ntru_poly_t , destroy , void , private_ntru_poly_t * this)
Definition at line 234 of file ntru_poly.c.
References free(), get_size(), and memwipe().
 {
     memwipe(this->indices, sizeof(uint16_t) * get_size(this));
     free(this->indices);
     free(this);
 }
static private_ntru_poly_t* ntru_poly_create (uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form) static
Creates an empty ntru_poly_t object with space allocated for indices
Definition at line 245 of file ntru_poly.c.
References indices_len_m, indices_len_p, INIT, malloc(), N, n, and q.
Referenced by ntru_poly_create_from_data(), and ntru_poly_create_from_seed().
 {
     private_ntru_poly_t *this;
     int n;
     INIT(this,
         .public = {
             .get_size = _get_size,
             .get_indices = _get_indices,
             .get_array = _get_array,
             .ring_mult = _ring_mult,
             .destroy = _destroy,
         },
         .N = N,
         .q = q,
     );
     if (is_product_form)
     {
         this->num_polynomials = 3;
         for (n = 0; n < 3; n++)
         {
             this->indices_len[n].p = 0xff & indices_len_p;
             this->indices_len[n].m = 0xff & indices_len_m;
             this->num_indices += this->indices_len[n].p +
                                  this->indices_len[n].m;
             indices_len_p >>= 8;
             indices_len_m >>= 8;
         }
     }
     else
     {
         this->num_polynomials = 1;
         this->indices_len[0].p = indices_len_p;
         this->indices_len[0].m = indices_len_m;
         this->num_indices = indices_len_p + indices_len_m;
     }
     this->indices = malloc(sizeof(uint16_t) * this->num_indices);
     return this;
 }
static void ring_mult_i (uint16_t * a, indices_len_t len, uint16_t * indices, uint16_t N, uint16_t mod_q_mask, uint16_t * t, uint16_t * c) static
Multiplication of polynomial a with a sparse polynomial b given by the indices of its +1 and -1 coefficients results in polynomial c. This is a convolution operation
Definition at line 94 of file ntru_poly.c.
References indices_len_t::m, N, and indices_len_t::p.
Referenced by METHOD().
 {
     int i, j, k;
     /* initialize temporary array t */
     for (k = 0; k < N; k++)
     {
         t[k] = 0;
     }
     /* t[(i+k)%N] = sum i=0 through N-1 of a[i], for b[k] = -1 */
     for (j = len.p; j < len.p + len.m; j++)
     {
         k = indices[j];
         for (i = 0; k < N; ++i, ++k)
         {
             t[k] += a[i];
         }
         for (k = 0; i < N; ++i, ++k)
         {
             t[k] += a[i];
         }
     }
     /* t[(i+k)%N] = -(sum i=0 through N-1 of a[i] for b[k] = -1) */
     for (k = 0; k < N; k++)
     {
         t[k] = -t[k];
     }
     /* t[(i+k)%N] += sum i=0 through N-1 of a[i] for b[k] = +1 */
     for (j = 0; j < len.p; j++)
     {
         k = indices[j];
         for (i = 0; k < N; ++i, ++k)
         {
             t[k] += a[i];
         }
         for (k = 0; i < N; ++i, ++k)
         {
             t[k] += a[i];
         }
     }
     /* c = (a * b) mod q */
     for (k = 0; k < N; k++)
     {
         c[k] = t[k] & mod_q_mask;
     }
 }