strongSwan: x509_t Struct Reference
x509_t Struct Reference
x509
#include "x509.h"
Public Attributes
certificate_t interface
x509_flag_t(* get_flags)(x509_t *this)
chunk_t(* get_serial)(x509_t *this)
chunk_t(* get_subjectKeyIdentifier)(x509_t *this)
chunk_t(* get_authKeyIdentifier)(x509_t *this)
u_int(* get_constraint)(x509_t *this, x509_constraint_t type)
enumerator_t *(* create_subjectAltName_enumerator)(x509_t *this)
enumerator_t *(* create_crl_uri_enumerator)(x509_t *this)
enumerator_t *(* create_ocsp_uri_enumerator)(x509_t *this)
enumerator_t *(* create_ipAddrBlock_enumerator)(x509_t *this)
enumerator_t *(* create_name_constraint_enumerator)(x509_t *this, bool perm)
enumerator_t *(* create_cert_policy_enumerator)(x509_t *this)
enumerator_t *(* create_policy_mapping_enumerator)(x509_t *this)
Detailed Description
X.509 certificate interface.
This interface adds additional methods to the certificate_t type to allow further operations on these certificates.
Definition at line 117 of file x509.h.
Member Data Documentation
enumerator_t*(* x509_t::create_cert_policy_enumerator)(x509_t *this)
Create an enumerator over certificate policies.
Returns
enumerator over x509_cert_policy_t
Definition at line 201 of file x509.h.
Referenced by check_policy(), check_policy_constraints(), has_no_any_policy(), has_policy(), is_policy_valid(), and print_x509().
enumerator_t*(* x509_t::create_crl_uri_enumerator)(x509_t *this)
Create an enumerator over all CRL URIs and CRL Issuers.
Returns
enumerator over x509_cdp_t
Definition at line 172 of file x509.h.
Referenced by check_crl(), check_delta_crl(), and print_x509().
enumerator_t*(* x509_t::create_ipAddrBlock_enumerator)(x509_t *this)
Create an enumerator over all ipAddrBlocks.
Returns
enumerator over ipAddrBlocks as traffic_selector_t*
Definition at line 186 of file x509.h.
Referenced by check_addrblock(), check_constraints(), print_x509(), and stroke_list_certs().
enumerator_t*(* x509_t::create_name_constraint_enumerator)(x509_t *this, bool perm)
Create an enumerator over name constraints.
Parameters
perm TRUE for permitted, FALSE for excluded subtrees
Returns
enumerator over subtrees as identification_t
Definition at line 194 of file x509.h.
Referenced by check_name_constraints(), name_constraint_inherited(), and print_x509().
enumerator_t*(* x509_t::create_ocsp_uri_enumerator)(x509_t *this)
Create an enumerator over all OCSP URIs.
Returns
enumerator over URIs as char*
Definition at line 179 of file x509.h.
Referenced by check_ocsp(), and print_x509().
enumerator_t*(* x509_t::create_policy_mapping_enumerator)(x509_t *this)
Create an enumerator over policy mappings.
Returns
enumerator over x509_policy_mapping
Definition at line 208 of file x509.h.
Referenced by check_policy(), has_no_policy_mapping(), has_policy(), is_policy_valid(), and print_x509().
enumerator_t*(* x509_t::create_subjectAltName_enumerator)(x509_t *this)
Create an enumerator over all subjectAltNames.
Returns
enumerator over subjectAltNames as identification_t*
Definition at line 165 of file x509.h.
Referenced by check_certificate(), find_smartcard_key(), METHOD(), name_constraint_matches(), print_x509(), and stroke_list_certs().
chunk_t(* x509_t::get_authKeyIdentifier)(x509_t *this)
Get the the authorityKeyIdentifier.
Returns
authKeyIdentifier as chunk_t, internal data
Definition at line 150 of file x509.h.
Referenced by print_x509(), and stroke_list_certs().
u_int(* x509_t::get_constraint)(x509_t *this, x509_constraint_t type)
Get a numerical X.509 constraint.
Parameters
type type of constraint to get
Returns
constraint, X509_NO_CONSTRAINT if none found
Definition at line 158 of file x509.h.
Referenced by check_pathlen(), check_policy_constraints(), print_x509(), and stroke_list_certs().
x509_flag_t(* x509_t::get_flags)(x509_t *this)
Get the flags set for this certificate.
Returns
set of flags
Definition at line 129 of file x509.h.
Referenced by add_certreq(), add_local_certs(), CALLBACK(), check_addrblock(), check_constraints(), connect_(), find_smartcard_key(), issue(), load_ca_cert(), load_cacerts(), load_pkcs12(), main(), METHOD(), name_constraint_inherited(), print_x509(), process_pkcs7(), send_certificate_request(), show(), sign_crl(), stroke_list_certs(), and verify_ocsp().
chunk_t(* x509_t::get_serial)(x509_t *this)
Get the certificate serial number.
Returns
chunk pointing to internal serial number
Definition at line 136 of file x509.h.
Referenced by add_attribute_certs(), build_authorityKeyIdentifier(), build_holder(), build_issuerAndSerialNumber(), build_requestList(), get_better_crl(), METHOD(), print_x509(), read_serial(), and stroke_list_certs().
chunk_t(* x509_t::get_subjectKeyIdentifier)(x509_t *this)
Get the the subjectKeyIdentifier.
Returns
subjectKeyIdentifier as chunk_t, internal data
Definition at line 143 of file x509.h.
Referenced by check_crl(), check_delta_crl(), find_smartcard_key(), generate(), load_cdps(), METHOD(), and print_x509().
certificate_t x509_t::interface
Implements certificate_t.
Definition at line 122 of file x509.h.
Referenced by check_ocsp(), get_better_ocsp(), METHOD(), and read_serial().
The documentation for this struct was generated from the following file:
x509.h