strongSwan: sender.c File Reference
sender.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include "sender.h"
#include <daemon.h>
#include <network/socket.h>
#include <processing/jobs/callback_job.h>
#include <threading/thread.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
Classes
struct private_sender_t
Typedefs
typedef struct private_sender_t private_sender_t
Functions
METHOD (sender_t, send_no_marker, void, private_sender_t *this, packet_t *packet)
METHOD (sender_t, send_, void, private_sender_t *this, packet_t *packet)
static job_requeue_t send_packets (private_sender_t *this)
METHOD (sender_t, flush, void, private_sender_t *this)
METHOD (sender_t, destroy, void, private_sender_t *this)
sender_t * sender_create ()
Typedef Documentation
typedef struct private_sender_t private_sender_t
Definition at line 31 of file sender.c.
Function Documentation
METHOD (sender_t , send_no_marker , void , private_sender_t * this, packet_t * packet)
Definition at line 83 of file sender.c.
References linked_list_t::insert_last, list, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->list->insert_last(this->list, packet);
     this->got->signal(this->got);
     this->mutex->unlock(this->mutex);
 }
METHOD (sender_t , send_ , void , private_sender_t * this, packet_t * packet)
Definition at line 92 of file sender.c.
References chunk_cat, chunk_from_chars, packet_t::clone, data, DBG1, DBG_NET, message_t::destroy, dst, packet_t::get_data, packet_t::get_destination, message_t::get_exchange_type, host_t::get_port, message_t::get_request, packet_t::get_source, IKEV2_UDP_PORT, chunk_t::len, message_create_from_packet(), message_t::parse_header, packet_t::set_data, src, SUCCESS, and usleep().
 {
     host_t *src, *dst;
     src = packet->get_source(packet);
     dst = packet->get_destination(packet);
     DBG1(DBG_NET, "sending packet: from %#H to %#H (%zu bytes)", src, dst,
          packet->get_data(packet).len);
     if (this->send_delay)
     {
         message_t *message;
         message = message_create_from_packet(packet->clone(packet));
         if (message->parse_header(message) == SUCCESS)
         {
             if (this->send_delay_type == 0 ||
                 this->send_delay_type == message->get_exchange_type(message))
             {
                 if ((message->get_request(message) && this->send_delay_request) ||
                     (!message->get_request(message) && this->send_delay_response))
                 {
                     DBG1(DBG_NET, "using send delay: %dms", this->send_delay);
                     usleep(this->send_delay * 1000);
                 }
             }
         }
         message->destroy(message);
     }
     /* if neither source nor destination port is 500 we add a Non-ESP marker */
     if (dst->get_port(dst) != IKEV2_UDP_PORT &&
         src->get_port(src) != IKEV2_UDP_PORT)
     {
         chunk_t data, marker = chunk_from_chars(0x00, 0x00, 0x00, 0x00);
         data = chunk_cat("cc", marker, packet->get_data(packet));
         packet->set_data(packet, data);
     }
     send_no_marker(this, packet);
 }
METHOD (sender_t , flush , void , private_sender_t * this)
Definition at line 166 of file sender.c.
References linked_list_t::get_count, list, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     /* send all packets in the queue */
     this->mutex->lock(this->mutex);
     while (this->list->get_count(this->list))
     {
         this->sent->wait(this->sent, this->mutex);
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (sender_t , destroy , void , private_sender_t * this)
Definition at line 178 of file sender.c.
References mutex_t::destroy, destroy(), linked_list_t::destroy_offset, free(), list, and mutex.
 {
     this->list->destroy_offset(this->list, offsetof(packet_t, destroy));
     this->got->destroy(this->got);
     this->sent->destroy(this->sent);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static job_requeue_t send_packets (private_sender_t * this) static
Job callback function to send packets
Definition at line 140 of file sender.c.
References charon, packet_t::destroy, FALSE, linked_list_t::get_count, JOB_REQUEUE_DIRECT, list, mutex_t::lock, mutex, linked_list_t::remove_first, socket_manager_t::send, daemon_t::socket, thread_cancelability(), thread_cleanup_pop(), thread_cleanup_push(), TRUE, and mutex_t::unlock.
Referenced by sender_create().
 {
     packet_t *packet;
     bool oldstate;
     this->mutex->lock(this->mutex);
     while (this->list->get_count(this->list) == 0)
     {
         /* add cleanup handler, wait for packet, remove cleanup handler */
         thread_cleanup_push((thread_cleanup_t)this->mutex->unlock, this->mutex);
         oldstate = thread_cancelability(TRUE);
         this->got->wait(this->got, this->mutex);
         thread_cancelability(oldstate);
         thread_cleanup_pop(FALSE);
     }
     this->list->remove_first(this->list, (void**)&packet);
     this->sent->signal(this->sent);
     this->mutex->unlock(this->mutex);
     charon->socket->send(charon->socket, packet);
     packet->destroy(packet);
     return JOB_REQUEUE_DIRECT;
 }