strongSwan: cowfs.h File Reference
cowfs.h File Reference
#include <library.h>
Classes
struct cowfs_t
Typedefs
typedef struct cowfs_t cowfs_t
Functions
cowfs_t * cowfs_create (char *master, char *host, char *mount)
Typedef Documentation
typedef struct cowfs_t cowfs_t
Definition at line 22 of file cowfs.h.
Function Documentation
cowfs_t* cowfs_create (char * master, char * host, char * mount)
Mount a cowfs FUSE filesystem.
Parameters
master read only master file system directory
host copy on write host directory
mount mountpoint where union is mounted
Returns
instance, or NULL if FUSE initialization failed
creates a new cowfs fuse instance
Definition at line 903 of file cowfs.c.
References close, cowfs_operations, DBG1, DBG_LIB, spinlock_t::destroy, free(), INIT, linked_list_create(), lock, rwlock_create(), RWLOCK_TYPE_DEFAULT, strdup, and thread_create.
Referenced by mount_unionfs().
 {
     struct fuse_args args = {0, NULL, 0};
     private_cowfs_t *this;
     INIT(this,
         .public = {
             .add_overlay = _add_overlay,
             .del_overlay = _del_overlay,
             .pop_overlay = _pop_overlay,
             .destroy = _destroy,
         }
     );
     this->master_fd = open(master, O_RDONLY | O_DIRECTORY);
     if (this->master_fd < 0)
     {
         DBG1(DBG_LIB, "failed to open master filesystem '%s'", master);
         free(this);
         return NULL;
     }
     this->host_fd = open(host, O_RDONLY | O_DIRECTORY);
     if (this->host_fd < 0)
     {
         DBG1(DBG_LIB, "failed to open host filesystem '%s'", host);
         close(this->master_fd);
         free(this);
         return NULL;
     }
     this->chan = fuse_mount(mount, &args);
     if (this->chan == NULL)
     {
         DBG1(DBG_LIB, "mounting cowfs FUSE on '%s' failed", mount);
         close(this->master_fd);
         close(this->host_fd);
         free(this);
         return NULL;
     }
     this->fuse = fuse_new(this->chan, &args, &cowfs_operations,
                           sizeof(cowfs_operations), this);
     if (this->fuse == NULL)
     {
         DBG1(DBG_LIB, "creating cowfs FUSE handle failed");
         close(this->master_fd);
         close(this->host_fd);
         fuse_unmount(mount, this->chan);
         free(this);
         return NULL;
     }
     this->mount = strdup(mount);
     this->master = strdup(master);
     this->host = strdup(host);
     this->overlays = linked_list_create();
     this->lock = rwlock_create(RWLOCK_TYPE_DEFAULT);
     this->thread = thread_create((thread_main_t)fuse_loop, this->fuse);
     if (!this->thread)
     {
         DBG1(DBG_LIB, "creating thread to handle FUSE failed");
         fuse_unmount(mount, this->chan);
         this->lock->destroy(this->lock);
         this->overlays->destroy(this->overlays);
         free(this->mount);
         free(this->master);
         free(this->host);
         close(this->master_fd);
         close(this->host_fd);
         free(this);
         return NULL;
     }
     return &this->public;
 }