strongSwan: tkm_listener.c File Reference
tkm_listener.c File Reference
#include <stdarg.h>
#include <daemon.h>
#include <encoding/payloads/auth_payload.h>
#include <utils/chunk.h>
#include <tkm/types.h>
#include <tkm/constants.h>
#include <tkm/client.h>
#include "tkm.h"
#include "tkm_listener.h"
#include "tkm_keymat.h"
#include "tkm_utils.h"
Classes
struct private_tkm_listener_t
Typedefs
typedef struct
private_tkm_listener_t private_tkm_listener_t
Functions
static ri_id_type get_remote_identity_id (peer_cfg_t *peer)
static bool build_cert_chain (const ike_sa_t *const ike_sa, cc_id_type cc_id)
METHOD (listener_t, alert, bool, private_tkm_listener_t *this, ike_sa_t *ike_sa, alert_t alert, va_list args)
METHOD (listener_t, authorize, bool, private_tkm_listener_t *this, ike_sa_t *ike_sa, bool final, bool *success)
METHOD (listener_t, message, bool, private_tkm_listener_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (tkm_listener_t, destroy, void, private_tkm_listener_t *this)
tkm_listener_t * tkm_listener_create ()
Typedef Documentation
typedef struct private_tkm_listener_t private_tkm_listener_t
Definition at line 31 of file tkm_listener.c.
Function Documentation
static bool build_cert_chain (const ike_sa_t *const ike_sa, cc_id_type cc_id) static
Build a TKM certificate chain context with given cc id.
Parameters
ike_sa IKE SA containing auth config to build certificate chain from
cc_id Certificate chain ID
Returns
TRUE if certificate chain was built successfully, FALSE otherwise
Definition at line 81 of file tkm_listener.c.
References AUTH_RULE_CA_CERT, AUTH_RULE_IM_CERT, AUTH_RULE_SUBJECT_CERT, cert, CERT_ASN1_DER, chunk_free(), chunk_to_sequence(), ike_sa_t::create_auth_cfg_enumerator, auth_cfg_t::create_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, auth_cfg_t::get, certificate_t::get_encoding, ike_sa_t::get_name, ike_sa_t::get_peer_cfg, get_remote_identity_id(), and TRUE.
Referenced by METHOD().
 {
     auth_cfg_t *auth;
     certificate_t *cert;
     enumerator_t *rounds;
     DBG1(DBG_IKE, "building certificate chain context %llu for IKE SA %s",
          cc_id, ike_sa->get_name((ike_sa_t *)ike_sa));
     rounds = ike_sa->create_auth_cfg_enumerator((ike_sa_t *)ike_sa, FALSE);
     while (rounds->enumerate(rounds, &auth))
     {
         cert = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
         if (cert)
         {
             chunk_t enc_user_cert;
             ri_id_type ri_id;
             certificate_type user_cert;
             auth_rule_t rule;
             enumerator_t *enumerator;
             /* set user certificate */
             if (!cert->get_encoding(cert, CERT_ASN1_DER, &enc_user_cert))
             {
                 DBG1(DBG_IKE, "unable to extract encoded user certificate");
                 rounds->destroy(rounds);
                 return FALSE;
             }
             ri_id = get_remote_identity_id(ike_sa->get_peer_cfg((ike_sa_t *)ike_sa));
             chunk_to_sequence(&enc_user_cert, &user_cert, sizeof(certificate_type));
             chunk_free(&enc_user_cert);
             if (ike_cc_set_user_certificate(cc_id, ri_id, 1, user_cert) != TKM_OK)
             {
                 DBG1(DBG_IKE, "error setting user certificate of cert chain"
                      " (cc_id: %llu)", cc_id);
                 rounds->destroy(rounds);
                 return FALSE;
             }
             /* process intermediate CA certificates */
             enumerator = auth->create_enumerator(auth);
             while (enumerator->enumerate(enumerator, &rule, &cert))
             {
                 if (rule == AUTH_RULE_IM_CERT)
                 {
                     chunk_t enc_im_cert;
                     certificate_type im_cert;
                     if (!cert->get_encoding(cert, CERT_ASN1_DER, &enc_im_cert))
                     {
                         DBG1(DBG_IKE, "unable to extract encoded intermediate CA"
                              " certificate");
                         rounds->destroy(rounds);
                         enumerator->destroy(enumerator);
                         return FALSE;
                     }
                     chunk_to_sequence(&enc_im_cert, &im_cert,
                                       sizeof(certificate_type));
                     chunk_free(&enc_im_cert);
                     if (ike_cc_add_certificate(cc_id, 1, im_cert) != TKM_OK)
                     {
                         DBG1(DBG_IKE, "error adding intermediate certificate to"
                              " cert chain (cc_id: %llu)", cc_id);
                         rounds->destroy(rounds);
                         enumerator->destroy(enumerator);
                         return FALSE;
                     }
                 }
             }
             enumerator->destroy(enumerator);
             /* finally add CA certificate */
             cert = auth->get(auth, AUTH_RULE_CA_CERT);
             if (cert)
             {
                 const ca_id_type ca_id = 1;
                 certificate_type ca_cert;
                 chunk_t enc_ca_cert;
                 if (!cert->get_encoding(cert, CERT_ASN1_DER, &enc_ca_cert))
                 {
                     DBG1(DBG_IKE, "unable to extract encoded CA certificate");
                     rounds->destroy(rounds);
                     return FALSE;
                 }
                 chunk_to_sequence(&enc_ca_cert, &ca_cert,
                                   sizeof(certificate_type));
                 chunk_free(&enc_ca_cert);
                 if (ike_cc_add_certificate(cc_id, 1, ca_cert) != TKM_OK)
                 {
                     DBG1(DBG_IKE, "error adding CA certificate to cert chain "
                          "(cc_id: %llu)", cc_id);
                     rounds->destroy(rounds);
                     return FALSE;
                 }
                 if (ike_cc_check_ca(cc_id, ca_id) != TKM_OK)
                 {
                     DBG1(DBG_IKE, "certificate chain (cc_id: %llu) not based on"
                          " trusted CA (ca_id: %llu)", cc_id, ca_id);
                     rounds->destroy(rounds);
                     return FALSE;
                 }
                 rounds->destroy(rounds);
                 return TRUE;
             }
             else
             {
                 DBG1(DBG_IKE, "no CA certificate");
             }
         }
         else
         {
             DBG1(DBG_IKE, "no subject certificate for remote peer");
         }
     }
     rounds->destroy(rounds);
     return FALSE;
 }
static ri_id_type get_remote_identity_id (peer_cfg_t * peer) static
Return id of remote identity.
TODO: Replace this with the lookup for the remote identitiy id.
Currently the reqid of the first child SA in peer config of IKE SA is returned. Might choose wrong reqid if IKE SA has multiple child configs with different reqids.
Parameters
peer_cfg Remote peer config
Returns
remote identity id if found, 0 otherwise
Definition at line 57 of file tkm_listener.c.
References peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, and child_cfg_t::get_reqid.
Referenced by build_cert_chain().
 {
     ri_id_type remote_id = 0;
     child_cfg_t *child;
     enumerator_t* children;
     children = peer->create_child_cfg_enumerator(peer);
     /* pick the reqid of the first child, no need to enumerate all children. */
     children->enumerate(children, &child);
     remote_id = child->get_reqid(child);
     children->destroy(children);
     return remote_id;
 }
METHOD (listener_t , alert , bool , private_tkm_listener_t * this, ike_sa_t * ike_sa, alert_t alert, va_list args)
Definition at line 206 of file tkm_listener.c.
References ALERT_KEEP_ON_CHILD_SA_FAILURE, DBG1, DBG_IKE, tkm_keymat_t::get_isa_id, ike_sa_t::get_keymat, and TRUE.
 {
     if (alert == ALERT_KEEP_ON_CHILD_SA_FAILURE)
     {
         tkm_keymat_t *keymat;
         isa_id_type isa_id;
         int is_first;
         is_first = va_arg(args, int);
         if (!is_first)
         {
             return TRUE;
         }
         keymat = (tkm_keymat_t*)ike_sa->get_keymat(ike_sa);
         isa_id = keymat->get_isa_id(keymat);
         DBG1(DBG_IKE, "TKM alert listener called for ISA context %llu", isa_id);
         if (ike_isa_skip_create_first(isa_id) != TKM_OK)
         {
             DBG1(DBG_IKE, "Skip of first child SA creation failed for ISA "
                  "context %llu", isa_id);
         }
     }
     return TRUE;
 }
METHOD (listener_t , authorize , bool , private_tkm_listener_t * this, ike_sa_t * ike_sa, bool final, bool * success)
Definition at line 236 of file tkm_listener.c.
References tkm_id_manager_t::acquire_id, build_cert_chain(), chunk_to_sequence(), DBG1, DBG_IKE, FALSE, tkm_keymat_t::get_auth_payload, tkm_keymat_t::get_isa_id, ike_sa_t::get_keymat, tkm_keymat_t::get_peer_init_msg, tkm_t::idmgr, chunk_t::ptr, tkm_id_manager_t::release_id, tkm, TKM_CTX_CC, and TRUE.
 {
     tkm_keymat_t *keymat;
     isa_id_type isa_id;
     cc_id_type cc_id;
     chunk_t *auth, *other_init_msg;
     signature_type signature;
     init_message_type init_msg;
     if (!final)
     {
         return TRUE;
     }
     *success = FALSE;
     keymat = (tkm_keymat_t*)ike_sa->get_keymat(ike_sa);
     isa_id = keymat->get_isa_id(keymat);
     DBG1(DBG_IKE, "TKM authorize listener called for ISA context %llu", isa_id);
     cc_id = tkm->idmgr->acquire_id(tkm->idmgr, TKM_CTX_CC);
     if (!cc_id)
     {
         DBG1(DBG_IKE, "unable to acquire CC context id");
         return TRUE;
     }
     if (!build_cert_chain(ike_sa, cc_id))
     {
         DBG1(DBG_IKE, "unable to build certificate chain");
         goto cc_reset;
     }
     auth = keymat->get_auth_payload(keymat);
     if (!auth->ptr)
     {
         DBG1(DBG_IKE, "no AUTHENTICATION data available");
         goto cc_reset;
     }
     other_init_msg = keymat->get_peer_init_msg(keymat);
     if (!other_init_msg->ptr)
     {
         DBG1(DBG_IKE, "no peer init message available");
         goto cc_reset;
     }
     chunk_to_sequence(auth, &signature, sizeof(signature_type));
     chunk_to_sequence(other_init_msg, &init_msg, sizeof(init_message_type));
     if (ike_isa_auth(isa_id, cc_id, init_msg, signature) != TKM_OK)
     {
         DBG1(DBG_IKE, "TKM based authentication failed"
              " for ISA context %llu", isa_id);
         goto cc_reset;
     }
     else
     {
         DBG1(DBG_IKE, "TKM based authentication successful"
              " for ISA context %llu", isa_id);
         *success = TRUE;
     }
 cc_reset:
     if (ike_cc_reset(cc_id) != TKM_OK)
     {
         DBG1(DBG_IKE, "unable to reset CC context %llu", cc_id);
     }
     tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_CC, cc_id);
     return TRUE; /* stay registered */
 }
METHOD (listener_t , message , bool , private_tkm_listener_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 309 of file tkm_listener.c.
References DBG1, DBG_IKE, auth_payload_t::get_data, message_t::get_exchange_type, tkm_keymat_t::get_isa_id, ike_sa_t::get_keymat, message_t::get_payload, IKE_AUTH, PLV2_AUTH, tkm_keymat_t::set_auth_payload, and TRUE.
 {
     tkm_keymat_t *keymat;
     isa_id_type isa_id;
     auth_payload_t *auth_payload;
     if (!incoming || !plain || message->get_exchange_type(message) != IKE_AUTH)
     {
         return TRUE;
     }
     keymat = (tkm_keymat_t*)ike_sa->get_keymat(ike_sa);
     isa_id = keymat->get_isa_id(keymat);
     DBG1(DBG_IKE, "saving AUTHENTICATION payload for authorize hook"
          " (ISA context %llu)", isa_id);
     auth_payload = (auth_payload_t*)message->get_payload(message,
                                                          PLV2_AUTH);
     if (auth_payload)
     {
         chunk_t auth_data;
         auth_data = auth_payload->get_data(auth_payload);
         keymat->set_auth_payload(keymat, &auth_data);
     }
     else
     {
         DBG1(DBG_IKE, "unable to extract AUTHENTICATION payload, authorize will"
              " fail");
     }
     return TRUE;
 }
METHOD (tkm_listener_t , destroy , void , private_tkm_listener_t * this)
Definition at line 345 of file tkm_listener.c.
References free().
 {
     free(this);
 }