strongSwan: main.c File Reference
medsrv/main.c File Reference
#include <stdio.h>
#include <fast_dispatcher.h>
#include <utils/debug.h>
#include <database/database.h>
#include "filter/auth_filter.h"
#include "controller/user_controller.h"
#include "controller/peer_controller.h"
Functions
int main (int arc, char *argv[])
Function Documentation
int main (int arc, char * argv[])
Definition at line 27 of file medsrv/main.c.
References fast_dispatcher_t::add_controller, fast_dispatcher_t::add_filter, auth_filter_create(), database_factory_t::create, db, library_t::db, fast_dispatcher_t::destroy, database_t::destroy, FALSE, fast_dispatcher_create(), fprintf, settings_t::get_bool, settings_t::get_int, settings_t::get_str, settings_t::get_time, lib, library_deinit(), library_init(), plugin_loader_t::load, peer_controller_create(), PLUGINS, library_t::plugins, fast_dispatcher_t::run, library_t::settings, socket, threads, uri, user_controller_create(), user_create(), and fast_dispatcher_t::waitsignal.
 {
     fast_dispatcher_t *dispatcher;
     database_t *db;
     char *socket;
     bool debug;
     char *uri;
     int timeout, threads;
     library_init(NULL, "medsrv");
     if (!lib->plugins->load(lib->plugins,
             lib->settings->get_str(lib->settings, "medsrv.load", PLUGINS)))
     {
         return 1;
     }
     socket = lib->settings->get_str(lib->settings, "medsrv.socket", NULL);
     debug = lib->settings->get_bool(lib->settings, "medsrv.debug", FALSE);
     timeout = lib->settings->get_time(lib->settings, "medsrv.timeout", 900);
     threads = lib->settings->get_int(lib->settings, "medsrv.threads", 5);
     uri = lib->settings->get_str(lib->settings, "medsrv.database", NULL);
     if (uri == NULL)
     {
         fprintf(stderr, "database URI medsrv.database not defined.\n");
         return 1;
     }
     db = lib->db->create(lib->db, uri);
     if (db == NULL)
     {
         fprintf(stderr, "opening database failed.\n");
         return 1;
     }
     dispatcher = fast_dispatcher_create(socket, debug, timeout,
                     (fast_context_constructor_t)user_create, db);
     dispatcher->add_filter(dispatcher,
                     (fast_filter_constructor_t)auth_filter_create, db);
     dispatcher->add_controller(dispatcher,
                     (fast_controller_constructor_t)user_controller_create, db);
     dispatcher->add_controller(dispatcher,
                     (fast_controller_constructor_t)peer_controller_create, db);
     dispatcher->run(dispatcher, threads);
     dispatcher->waitsignal(dispatcher);
     dispatcher->destroy(dispatcher);
     db->destroy(db);
     library_deinit();
     return 0;
 }