strongSwan: imv_attestation_state_t Struct Reference
imv_attestation_state_t Struct Reference
imv_attestation_state
#include "imv_attestation_state.h"
Public Attributes
imv_state_t interface
imv_attestation_handshake_state_t(* get_handshake_state)(imv_attestation_state_t *this)
void(* set_handshake_state)(imv_attestation_state_t *this, imv_attestation_handshake_state_t new_state)
pts_t *(* get_pts)(imv_attestation_state_t *this)
pts_component_t *(* create_component)(imv_attestation_state_t *this, pts_comp_func_name_t *name, uint32_t depth, pts_database_t *pts_db)
enumerator_t *(* create_component_enumerator)(imv_attestation_state_t *this)
pts_component_t *(* get_component)(imv_attestation_state_t *this, pts_comp_func_name_t *name)
void(* finalize_components)(imv_attestation_state_t *this, bio_writer_t *result)
uint32_t(* get_measurement_error)(imv_attestation_state_t *this)
void(* set_measurement_error)(imv_attestation_state_t *this, uint32_t error)
void(* add_file_meas_reasons)(imv_attestation_state_t *this, imv_reason_string_t *reason_string)
void(* add_comp_evid_reasons)(imv_attestation_state_t *this, imv_reason_string_t *reason_string)
Detailed Description
Internal state of an imv_attestation_t connection instance
Definition at line 85 of file imv_attestation_state.h.
Member Data Documentation
void(* imv_attestation_state_t::add_comp_evid_reasons)(imv_attestation_state_t *this, imv_reason_string_t *reason_string)
Returns a concatenation of Component Evidence reason strings
Parameters
reason_string Concatenated reason strings
Definition at line 181 of file imv_attestation_state.h.
Referenced by imv_attestation_process(), and METHOD().
void(* imv_attestation_state_t::add_file_meas_reasons)(imv_attestation_state_t *this, imv_reason_string_t *reason_string)
Returns a concatenation of File Measurement reason strings
Parameters
reason_string Concatenated reason strings
Definition at line 173 of file imv_attestation_state.h.
pts_component_t*(* imv_attestation_state_t::create_component)(imv_attestation_state_t *this, pts_comp_func_name_t *name, uint32_t depth, pts_database_t *pts_db)
Create and add an entry to the list of Functional Components
Parameters
name Component Functional Name
depth Sub-component Depth
pts_db PTS measurement database
Returns
created functional component instance or NULL
Definition at line 123 of file imv_attestation_state.h.
Referenced by METHOD().
enumerator_t*(* imv_attestation_state_t::create_component_enumerator)(imv_attestation_state_t *this)
Enumerate over all Functional Components
Returns
Functional Component enumerator
Definition at line 133 of file imv_attestation_state.h.
Referenced by imv_attestation_build().
void(* imv_attestation_state_t::finalize_components)(imv_attestation_state_t *this, bio_writer_t *result)
Tell the Functional Components to finalize any measurement registrations and to check if all expected measurements were received
Parameters
result Writer appending component measurement results
Definition at line 150 of file imv_attestation_state.h.
Referenced by imv_attestation_process(), and METHOD().
pts_component_t*(* imv_attestation_state_t::get_component)(imv_attestation_state_t *this, pts_comp_func_name_t *name)
Get a Functional Component with a given name
Parameters
name Name of the requested Functional Component
Returns
Functional Component if found, NULL otherwise
Definition at line 141 of file imv_attestation_state.h.
Referenced by imv_attestation_process().
imv_attestation_handshake_state_t(* imv_attestation_state_t::get_handshake_state)(imv_attestation_state_t *this)
Get state of the handshake
Returns
the handshake state of IMV
Definition at line 97 of file imv_attestation_state.h.
Referenced by imv_attestation_build(), and METHOD().
uint32_t(* imv_attestation_state_t::get_measurement_error)(imv_attestation_state_t *this)
Indicates the types of measurement errors that occurred
Returns
Measurement error flags
Definition at line 158 of file imv_attestation_state.h.
Referenced by imv_attestation_process().
pts_t*(* imv_attestation_state_t::get_pts)(imv_attestation_state_t *this)
Get the PTS object
Returns
PTS object
Definition at line 113 of file imv_attestation_state.h.
Referenced by imv_attestation_build(), imv_attestation_process(), and METHOD().
imv_state_t imv_attestation_state_t::interface
imv_state_t interface
Definition at line 90 of file imv_attestation_state.h.
void(* imv_attestation_state_t::set_handshake_state)(imv_attestation_state_t *this, imv_attestation_handshake_state_t new_state)
Set state of the handshake
Parameters
new_state the handshake state of IMV
Definition at line 105 of file imv_attestation_state.h.
Referenced by imv_attestation_build(), imv_attestation_process(), and METHOD().
void(* imv_attestation_state_t::set_measurement_error)(imv_attestation_state_t *this, uint32_t error)
Call if a measurement error is encountered
Parameters
error Measurement error type
Definition at line 165 of file imv_attestation_state.h.
Referenced by imv_attestation_build(), imv_attestation_process(), and METHOD().
The documentation for this struct was generated from the following file:
imv_attestation_state.h