strongSwan: af_alg_ops
af_alg_ops
af_alg
Classes
struct af_alg_ops_t
Macros
#define AF_ALG 38
#define SOL_ALG 279
Typedefs
typedef struct af_alg_ops_t af_alg_ops_t
Functions
af_alg_ops_t * af_alg_ops_create (char *type, char *alg)
Detailed Description
Macro Definition Documentation
#define AF_ALG 38
Definition at line 29 of file af_alg_ops.h.
Referenced by af_alg_ops_create().
#define SOL_ALG 279
Definition at line 33 of file af_alg_ops.h.
Referenced by METHOD().
Typedef Documentation
typedef struct af_alg_ops_t af_alg_ops_t
Definition at line 36 of file af_alg_ops.h.
Function Documentation
af_alg_ops_t* af_alg_ops_create (char * type, char * alg)
Create a af_alg_ops instance.
Parameters
type algorithm type (hash, skcipher)
alg algorithm name
Returns
TRUE if AF_ALG socket bound successfully
See header
Definition at line 213 of file af_alg_ops.c.
References AF_ALG, bind, DBG1, DBG_LIB, destroy(), free(), INIT, sockaddr_alg::salg_family, sockaddr_alg::salg_name, sockaddr_alg::salg_type, socket, and strerror.
Referenced by af_alg_crypter_create(), af_alg_crypter_probe(), af_alg_hasher_create(), af_alg_hasher_probe(), af_alg_prf_create(), af_alg_prf_probe(), af_alg_signer_create(), and af_alg_signer_probe().
 {
     private_af_alg_ops_t *this;
     struct sockaddr_alg sa = {
         .salg_family = AF_ALG,
     };
     strncpy(sa.salg_type, type, sizeof(sa.salg_type));
     strncpy(sa.salg_name, alg, sizeof(sa.salg_name));
     INIT(this,
         .public = {
             .hash = _hash,
             .reset = _reset,
             .crypt = _crypt,
             .set_key = _set_key,
             .destroy = _destroy,
         },
         .tfm = socket(AF_ALG, SOCK_SEQPACKET, 0),
         .op = -1,
     );
     if (this->tfm == -1)
     {
         DBG1(DBG_LIB, "opening AF_ALG socket failed: %s", strerror(errno));
         free(this);
         return NULL;
     }
     if (bind(this->tfm, (struct sockaddr*)&sa, sizeof(sa)) == -1)
     {
         if (errno != ENOENT)
         {   /* fail silently if algorithm not supported */
             DBG1(DBG_LIB, "binding AF_ALG socket for '%s' failed: %s",
                  sa.salg_name, strerror(errno));
         }
         destroy(this);
         return NULL;
     }
     return &this->public;
 }