strongSwan: iface_t Struct Reference
iface_t Struct Reference
#include "iface.h"
Public Attributes
char *(* get_guestif)(iface_t *this)
char *(* get_hostif)(iface_t *this)
bool(* add_address)(iface_t *this, host_t *addr, int bits)
enumerator_t *(* create_address_enumerator)(iface_t *this)
bool(* delete_address)(iface_t *this, host_t *addr, int bits)
void(* set_bridge)(iface_t *this, bridge_t *bridge)
bridge_t *(* get_bridge)(iface_t *this)
guest_t *(* get_guest)(iface_t *this)
void(* destroy)(iface_t *this)
DWORD ifindex
char * ifname
char * ifdesc
DWORD iftype
IF_OPER_STATUS status
linked_list_t * addrs
Detailed Description
Interface in a guest, connected to a tap device on the host.
Interface entry
Definition at line 34 of file iface.h.
Member Data Documentation
bool(* iface_t::add_address)(iface_t *this, host_t *addr, int bits)
Add an address to the interface.
Parameters
addr address to add to the interface
bits network prefix length in bits
Returns
TRUE if address added
Definition at line 57 of file iface.h.
Referenced by iface_add_addr(), and iface_del_addr().
linked_list_t* iface_t::addrs
list of known addresses, as host_t
Definition at line 94 of file kernel_iph_net.c.
Referenced by address2entry(), METHOD(), and update_addrs().
enumerator_t*(* iface_t::create_address_enumerator)(iface_t *this)
Create an enumerator over all installed addresses.
Returns
enumerator over host_t*
Definition at line 64 of file iface.h.
Referenced by iface_each_addr().
bool(* iface_t::delete_address)(iface_t *this, host_t *addr, int bits)
Remove an address from an interface.
Note
The network prefix length has to be the same as used in add_address
Parameters
addr address to remove
bits network prefix length in bits
Returns
TRUE if address removed
Definition at line 75 of file iface.h.
Referenced by iface_add_addr(), and iface_del_addr().
void(* iface_t::destroy)(iface_t *this)
Destroy an interface
Definition at line 101 of file iface.h.
Referenced by METHOD().
bridge_t*(* iface_t::get_bridge)(iface_t *this)
Get the bridge this iface is connected, or NULL.
Returns
connected bridge, or NULL
Definition at line 89 of file iface.h.
Referenced by iface_disconnect().
guest_t*(* iface_t::get_guest)(iface_t *this)
Get the guest this iface belongs to.
Returns
guest of this iface
Definition at line 96 of file iface.h.
Referenced by iface_delete().
char*(* iface_t::get_guestif)(iface_t *this)
Get the interface name in the guest (e.g. eth0).
Returns
guest interface name
Definition at line 41 of file iface.h.
Referenced by guest_find_iface(), and METHOD().
char*(* iface_t::get_hostif)(iface_t *this)
Get the interface name at the host (e.g. tap0).
Returns
host interface (tap device) name
Definition at line 48 of file iface.h.
Referenced by iface_to_s(), and METHOD().
char* iface_t::ifdesc
interface description
Definition at line 88 of file kernel_iph_net.c.
Referenced by add_interface(), remove_interface(), update_addrs(), and update_interface().
DWORD iface_t::ifindex
interface index
Definition at line 84 of file kernel_iph_net.c.
Referenced by add_interface(), manage_route(), remove_interface(), update_addrs(), and update_interface().
char* iface_t::ifname
interface name
Definition at line 86 of file kernel_iph_net.c.
Referenced by add_interface(), manage_route(), and METHOD().
DWORD iface_t::iftype
type of interface
Definition at line 90 of file kernel_iph_net.c.
Referenced by METHOD().
void(* iface_t::set_bridge)(iface_t *this, bridge_t *bridge)
Set the bridge this interface is attached to.
Parameters
bridge assigned bridge, or NULL for none
Definition at line 82 of file iface.h.
Referenced by METHOD().
IF_OPER_STATUS iface_t::status
interface status
Definition at line 92 of file kernel_iph_net.c.
Referenced by METHOD(), and update_interface().
The documentation for this struct was generated from the following files:
iface.h
kernel_iph_net.c