strongSwan: ike_mobike_t Struct Reference
ike_mobike_t Struct Reference
ike_mobike
#include "ike_mobike.h"
Public Attributes
task_t task
void(* addresses)(ike_mobike_t *this)
void(* roam)(ike_mobike_t *this, bool address)
void(* dpd)(ike_mobike_t *this)
bool(* transmit)(ike_mobike_t *this, packet_t *packet)
bool(* is_probing)(ike_mobike_t *this)
void(* enable_probing)(ike_mobike_t *this)
Detailed Description
Task of type ike_mobike, detects and handles MOBIKE extension.
The MOBIKE extension is defined in RFC4555. It allows to update IKE and IPsec tunnel addresses. This tasks handles the MOBIKE_SUPPORTED notify exchange to detect MOBIKE support, allows the exchange of ADDITIONAL_*_ADDRESS to exchange additional endpoints and handles the UPDATE_SA_ADDRESS notify to finally update endpoints.
Definition at line 41 of file ike_mobike.h.
Member Data Documentation
void(* ike_mobike_t::addresses)(ike_mobike_t *this)
Use the task to update the list of additional addresses.
Definition at line 51 of file ike_mobike.h.
Referenced by METHOD().
void(* ike_mobike_t::dpd)(ike_mobike_t *this)
Use the task for a DPD check which detects changes in NAT mappings.
Definition at line 63 of file ike_mobike.h.
Referenced by METHOD().
void(* ike_mobike_t::enable_probing)(ike_mobike_t *this)
Enable probing for routability.
Definition at line 87 of file ike_mobike.h.
Referenced by METHOD().
bool(* ike_mobike_t::is_probing)(ike_mobike_t *this)
Check if this task is probing for routability.
Returns
TRUE if task is probing
Definition at line 82 of file ike_mobike.h.
Referenced by METHOD().
void(* ike_mobike_t::roam)(ike_mobike_t *this, bool address)
Use the task to roam to other addresses.
Parameters
address TRUE to include address list update
Definition at line 58 of file ike_mobike.h.
Referenced by METHOD().
task_t ike_mobike_t::task
Implements the task_t interface
Definition at line 46 of file ike_mobike.h.
Referenced by METHOD().
bool(* ike_mobike_t::transmit)(ike_mobike_t *this, packet_t *packet)
Transmision hook, called by task manager.
The task manager calls this hook whenever it transmits a packet. It allows the mobike task to send the packet on multiple paths to do path probing.
Parameters
packet the packet to transmit
Returns
TRUE if transmitted, FALSE if no path found
Definition at line 75 of file ike_mobike.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ike_mobike.h