strongSwan: host_t Struct Reference
host_t Struct Reference
host
#include "host.h"
Public Attributes
host_t *(* clone)(host_t *this)
sockaddr_t *(* get_sockaddr)(host_t *this)
socklen_t *(* get_sockaddr_len)(host_t *this)
int(* get_family)(host_t *this)
bool(* is_anyaddr)(host_t *this)
chunk_t(* get_address)(host_t *this)
u_int16_t(* get_port)(host_t *this)
void(* set_port)(host_t *this, u_int16_t port)
bool(* ip_equals)(host_t *this, host_t *other)
bool(* equals)(host_t *this, host_t *other)
void(* destroy)(host_t *this)
Detailed Description
Representates a Host
Host object, identifies a address:port pair and defines some useful functions on it.
Definition at line 43 of file host.h.
Member Data Documentation
host_t*(* host_t::clone)(host_t *this)
Build a clone of this host object.
Returns
cloned host
Definition at line 50 of file host.h.
Referenced by add_entry(), add_exclude_async(), add_exclude_route(), add_trap(), allocate_addr(), build_response(), child_sa_create(), clone_message(), delete_child_sa_job_create(), endpoint_notify_create_from_host(), gather_and_add_endpoints(), get_interface_address(), get_proxy_addr(), get_route(), get_ts(), handle_offer(), iface_each_addr(), install_ipip_ale(), install_route(), ipsec_policy_create(), ipsec_sa_create(), mem_pool_create(), mem_pool_create_range(), merge_fragments(), METHOD(), process_addr(), process_ike_add(), process_ike_update(), process_outbound(), process_payloads(), process_request(), radius_receive(), rekey_child(), rekey_child_sa_job_create(), resolve_hosts(), save_retransmit(), schedule_expire(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), send_packets(), sender(), START_TEST(), tnccs_11_create(), tnccs_20_create(), tnccs_dynamic_create(), trigger_mbb_reauth(), and update_sa_job_create().
void(* host_t::destroy)(host_t *this)
Destroy this host object.
Definition at line 130 of file host.h.
Referenced by add_address(), add_addresses(), add_exclude_route(), add_legacy_entry(), add_policy_internal(), add_rt_mask(), add_unity_split_attribute(), allocate_addr(), append_ts(), assert_acquire(), assert_host(), bliss_public_key_load(), build_natd_payload(), build_peer_cfg(), build_set(), calculate_priority(), CALLBACK(), cancellation_accept(), check_connection(), child_entry_destroy(), client(), create_pool_range(), del_attr(), entry_destroy(), expire_data_destroy(), gather_and_add_endpoints(), generate_config(), get_route(), handle_ack(), handle_offer(), id_payload_create_from_ts(), iface_add_addr(), iface_del_addr(), iface_each_addr(), ike_cfg_get_family(), install_shunt_policy(), invoke_once(), is_any_path_valid(), is_current_path_valid(), is_local(), issue(), load_addrs(), load_entries(), load_pools(), main(), make_range(), manage_dns(), manage_route(), match(), METHOD(), open_socket(), parse_attributes(), pool_destroy(), prepare_dhcp(), print_host(), process_addr(), process_expire(), process_mapping(), process_route(), pt_tls_receive(), query(), radius_receive(), receive(), receive_arp(), receive_casts(), rekey_child(), resize(), resolve_hosts(), run_echo_client(), setup_interface(), start_echo_server(), START_TEST(), status(), status_attr(), stream_parse_uri_tcp(), test_create_any(), test_create_from_dns(), test_create_from_string_and_family_addr(), test_create_from_string_and_family_any(), test_create_netmask(), traffic_selector_create_from_subnet(), ts2condition(), ts2in(), ts2subnet(), uninstall_shunt_policy(), update_addrs(), use_ts(), verify_address(), and verify_range().
bool(* host_t::equals)(host_t *this, host_t *other)
Compare two hosts, with port.
Parameters
other the other to compare
Returns
TRUE if addresses and ports are equal.
Definition at line 125 of file host.h.
Referenced by enforce_replace(), match_endpoint_by_host(), match_pair_by_hosts(), METHOD(), policy_entry_equals(), process_response(), prune_pairs(), radius_receive(), save_retransmit(), send_retransmit(), and START_TEST().
chunk_t(* host_t::get_address)(host_t *this)
Get the address of this host as chunk_t
Returned chunk points to internal data.
Returns
address blob
Definition at line 95 of file host.h.
Referenced by add(), add_address(), add_addresses(), add_exclude_route(), add_ike_sa_parameters(), add_legacy_entry(), add_unity_split_attribute(), append_ts(), attr_filter(), build_address_list(), build_vip(), CALLBACK(), common_prefix(), cookie_build(), create_ip_address(), eap_radius_build_attributes(), generate_natd_hash(), get_init_hash(), get_route(), get_scope(), hash(), hash_addr(), hash_id_host(), hash_in(), hash_out(), hash_route(), hash_sa(), have_vips_from_pool(), host2address6(), host2in(), host2int(), host2offset(), host2xfrm(), hosts2traffic(), id_payload_create_from_ts(), install_route(), ip_packet_create_from_data(), ipsec_sa_hash(), load_entries(), make_range(), manage_ipaddr(), manage_srcroute(), mem_pool_create_range(), METHOD(), network_id_diff(), offset2host(), parse_attributes(), prepare_dhcp(), pseudo_header_checksum(), put_half_open(), remove_exclude_route(), remove_half_open(), request(), resize(), signal_ipv4_config(), test_create_netmask(), traffic_selector_create_from_subnet(), ts2in(), ts2subnet(), tun_entry_hash(), uninstall_route(), verify_address(), and verify_any().
int(* host_t::get_family)(host_t *this)
Gets the family of the address
Returns
family
Definition at line 79 of file host.h.
Referenced by add_address(), add_exclude_route(), add_ike_sa_parameters(), add_initial_contact(), add_legacy_entry(), add_policy_internal(), add_unity_split_attribute(), assign_migrated_vip(), attr_filter(), build_ack(), build_address_list(), build_vip(), CALLBACK(), check_connection(), client(), create_ip_address(), eap_radius_build_attributes(), endpoint_notify_create_from_host(), filter_addresses(), get_interface_address(), get_replay_state(), get_route(), get_spi_internal(), get_ts(), has_host_family(), host2in(), host2int(), host2offset(), host_create_from_subnet(), hosts2traffic(), ike_cfg_get_family(), install_ipip_ale(), invoke_once(), ip_packet_create_from_data(), is_address_better(), load_entries(), load_pools(), make_range(), manage_ipaddr(), manage_route(), manage_srcroute(), match(), mem_pool_create(), mem_pool_create_range(), METHOD(), offset2host(), parse_attributes(), pseudo_header_checksum(), pt_tls_receive(), push_dns_env(), push_vip_env(), put_connected_peers(), remove_addr(), remove_connected_peers(), remove_exclude_route(), send_message(), traffic_selector_create_from_subnet(), ts2condition(), verify_address(), verify_any(), and write_address().
u_int16_t(* host_t::get_port)(host_t *this)
Get the port of this host
Returns
port number
Definition at line 102 of file host.h.
Referenced by apply_port(), calculate_priority(), create_policy_entry(), fix_transport_header(), gather_and_add_endpoints(), generate_natd_hash(), get_init_hash(), get_priority(), hash_addr(), invoke_once(), manage_pre_esp_in_udp(), METHOD(), receive_packets(), request_query_ikesa(), resolve_hosts(), sadb_address2ts(), START_TEST(), verify_address(), and verify_any().
sockaddr_t*(* host_t::get_sockaddr)(host_t *this)
Get a pointer to the internal sockaddr struct.
This is used for sending and receiving via sockets.
Returns
pointer to the internal sockaddr structure
Definition at line 59 of file host.h.
Referenced by add_nat_oa_payloads(), add_rt_addr(), cancellation_accept(), check_connection(), filter_addresses(), hostcpy(), lookup_shared_key(), manage_route(), METHOD(), open_socket(), run_client(), run_echo_client(), send_dhcp(), send_message(), send_msg_v4(), send_msg_v6(), serve(), start_echo_server(), START_TEST(), and stream_parse_uri_tcp().
socklen_t*(* host_t::get_sockaddr_len)(host_t *this)
Get the length of the sockaddr struct.
Depending on the family, the length of the sockaddr struct is different. Use this function to get the length of the sockaddr struct returned by get_sock_addr.
This is used for sending and receiving via sockets.
Returns
length of the sockaddr struct
Definition at line 72 of file host.h.
Referenced by add_rt_addr(), cancellation_accept(), check_connection(), hostcpy(), manage_route(), METHOD(), open_socket(), run_client(), run_echo_client(), send_dhcp(), send_message(), serve(), start_echo_server(), START_TEST(), and stream_parse_uri_tcp().
bool(* host_t::ip_equals)(host_t *this, host_t *other)
Compare the ips of two hosts hosts.
Parameters
other the other to compare
Returns
TRUE if addresses are equal.
Definition at line 117 of file host.h.
Referenced by acquire_by_dst(), add_exclude_route(), addr_map_entry_equals(), addr_map_entry_match(), addr_map_entry_match_up(), addr_map_entry_match_up_and_usable(), addr_map_entry_match_virtual(), address2entry(), apply_port(), assert_host(), build_address_list(), equals(), equals_in(), equals_out(), equals_route(), equals_sa(), exclude_route_match(), get_interface_address(), get_route(), ipsec_sa_equals(), is_current_path_valid(), match(), merge_pool(), METHOD(), pool_leases(), process_addr(), remove_addr(), route_entry_equals(), sad_entry_equal(), sad_entry_match(), START_TEST(), tun_entry_equals(), and update_addrs().
bool(* host_t::is_anyaddr)(host_t *this)
Checks if the ip address of host is set to default route.
Returns
TRUE if host is 0.0.0.0 or 0::0, FALSE otherwise
Definition at line 86 of file host.h.
Referenced by add_policy_internal(), assign_migrated_vip(), attr_filter(), build_vip(), install_route(), install_vips(), is_local(), match(), METHOD(), process_addr(), resize(), resolve_hosts(), send_notify(), send_notify_response(), status(), verify_address(), verify_any(), and write_address().
void(* host_t::set_port)(host_t *this, u_int16_t port)
Set the port of this host
Parameters
port port number
Definition at line 109 of file host.h.
Referenced by apply_port(), create_policy_entry(), gather_and_add_endpoints(), METHOD(), resolve(), resolve_hosts(), and START_TEST().
The documentation for this struct was generated from the following file:
host.h