strongSwan: test_enumerator.c File Reference
test_enumerator.c File Reference
#include "test_suite.h"
#include <collections/enumerator.h>
#include <collections/linked_list.h>
Functions
START_TEST (test_token)
START_SETUP (setup_destroy_data)
END_SETUP START_TEARDOWN (teardown_destroy_data)
static END_TEARDOWN void destroy_data (void *data)
static bool filter (int *data, int **v, int *vo, int **w, int *wo, int **x, int *xo, int **y, int *yo, int **z, int *zo)
static bool filter_odd (void *data, int **item, int *out)
START_TEST (test_filtered)
END_TEST START_TEST (test_filtered_filter)
static END_TEST enumerator_t * create_inner (linked_list_t *outer, void *data)
static enumerator_t * create_inner_null (void *outer, void *data)
START_TEST (test_nested)
END_TEST START_TEST (test_nested_reset)
END_TEST START_TEST (test_nested_empty)
END_TEST START_TEST (test_nested_null)
END_TEST START_TEST (test_cleaner)
static END_TEST void single_cleanup (void *data)
static void do_test_single (enumerator_t *enumerator)
START_TEST (test_single)
END_TEST START_TEST (test_single_cleanup)
END_TEST Suite * enumerator_suite_create ()
Variables
static const char * token_results1 [] = { "abc", "cde", "efg" }
static const char * token_results2 [] = { "a", "b", "c" }
struct {
char * string
char * sep
char * trim
const char ** results
} token_tests []
static END_TEST int destroy_data_called
Function Documentation
static END_TEST enumerator_t* create_inner (linked_list_t * outer, void * data) static
Definition at line 186 of file test_enumerator.c.
References linked_list_t::create_enumerator, and fail_if.
Referenced by enumerate_nested(), and START_TEST().
 {
     fail_if(data != (void*)101, "data does not match '101' in nested constr.");
     return outer->create_enumerator(outer);
 }
static enumerator_t* create_inner_null (void * outer, void * data) static
Definition at line 192 of file test_enumerator.c.
References ck_assert, and fail_if.
Referenced by START_TEST().
 {
     ck_assert(outer == (void*)1);
     fail_if(data != (void*)101, "data does not match '101' in nested constr.");
     return NULL;
 }
static END_TEARDOWN void destroy_data (void * data) static
Definition at line 97 of file test_enumerator.c.
References destroy_data_called, and fail_if.
Referenced by destroy_nested(), enumerator_create_nested(), and START_TEST().
 {
     fail_if(data != (void*)101, "data does not match '101' in destructor");
     destroy_data_called++;
 }
static void do_test_single (enumerator_t * enumerator) static
Definition at line 345 of file test_enumerator.c.
References ck_assert, ck_assert_int_eq, enumerator_t::destroy, and enumerator_t::enumerate.
Referenced by START_TEST().
 {
     intptr_t x;
     ck_assert(enumerator->enumerate(enumerator, &x));
     ck_assert_int_eq(x, 1);
     ck_assert(!enumerator->enumerate(enumerator, &x));
     enumerator->destroy(enumerator);
 }
END_TEST Suite* enumerator_suite_create ()
Definition at line 373 of file test_enumerator.c.
References countof, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_checked_fixture, tcase_add_loop_test, tcase_add_test, tcase_create, and token_tests.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("enumerator");
     tc = tcase_create("tokens");
     tcase_add_loop_test(tc, test_token, 0, countof(token_tests));
     suite_add_tcase(s, tc);
     tc = tcase_create("filtered");
     tcase_add_checked_fixture(tc, setup_destroy_data, teardown_destroy_data);
     tcase_add_test(tc, test_filtered);
     tcase_add_test(tc, test_filtered_filter);
     suite_add_tcase(s, tc);
     tc = tcase_create("nested");
     tcase_add_checked_fixture(tc, setup_destroy_data, teardown_destroy_data);
     tcase_add_test(tc, test_nested);
     tcase_add_test(tc, test_nested_reset);
     tcase_add_test(tc, test_nested_empty);
     tcase_add_test(tc, test_nested_null);
     suite_add_tcase(s, tc);
     tc = tcase_create("cleaner");
     tcase_add_checked_fixture(tc, setup_destroy_data, teardown_destroy_data);
     tcase_add_test(tc, test_cleaner);
     suite_add_tcase(s, tc);
     tc = tcase_create("single");
     tcase_add_test(tc, test_single);
     tcase_add_test(tc, test_single_cleanup);
     suite_add_tcase(s, tc);
     return s;
 }
static bool filter (int * data, int ** v, int * vo, int ** w, int * wo, int ** x, int * xo, int ** y, int * yo, int ** z, int * zo) static
Definition at line 107 of file test_enumerator.c.
References fail_if, TRUE, and val.
Referenced by START_TEST().
 {
     int val = **v;
     *vo = val++;
     *wo = val++;
     *xo = val++;
     *yo = val++;
     *zo = val++;
     fail_if(data != (void*)101, "data does not match '101' in filter function");
     return TRUE;
 }
static bool filter_odd (void * data, int ** item, int * out) static
Definition at line 121 of file test_enumerator.c.
References fail_if.
Referenced by START_TEST().
 {
     fail_if(data != (void*)101, "data does not match '101' in filter function");
     *out = **item;
     return **item % 2 == 0;
 }
static END_TEST void single_cleanup (void * data) static
Definition at line 340 of file test_enumerator.c.
References ck_assert_int_eq.
Referenced by START_TEST().
 {
     ck_assert_int_eq((intptr_t)data, 1);
 }
START_SETUP (setup_destroy_data)
Definition at line 85 of file test_enumerator.c.
References destroy_data_called.
 {
     destroy_data_called = 0;
 }
END_SETUP START_TEARDOWN (teardown_destroy_data)
Definition at line 91 of file test_enumerator.c.
References ck_assert_int_eq, and destroy_data_called.
 {
     ck_assert_int_eq(destroy_data_called, 1);
 }
START_TEST (test_token)
Definition at line 49 of file test_enumerator.c.
References ck_assert_str_eq, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), fail, fail_if, results, sep, token_tests, and trim.
 {
     enumerator_t *enumerator;
     const char **results;
     char *token;
     int tok = 0;
     enumerator = enumerator_create_token(token_tests[_i].string,
                                     token_tests[_i].sep, token_tests[_i].trim);
     results = token_tests[_i].results;
     while (enumerator->enumerate(enumerator, &token))
     {
         switch (tok)
         {
             case 0:
             case 1:
             case 2:
                 ck_assert_str_eq(token, results[tok]);
                 break;
             default:
                 fail("unexpected token '%s'", token);
         }
         tok++;
     }
     fail_if(tok != 3, "not enough tokens (%d) extracted from '%s'",
             tok, token_tests[_i].string);
     enumerator->destroy(enumerator);
 }
START_TEST (test_filtered)
Definition at line 128 of file test_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, data, enumerator_t::destroy, linked_list_t::destroy, destroy_data(), enumerator_t::enumerate, enumerator_create_filter(), filter(), linked_list_create_with_items(), list, and w.
 {
     int data[5] = {1,2,3,4,5}, round, v, w, x, y, z;
     linked_list_t *list;
     enumerator_t *enumerator;
     list = linked_list_create_with_items(&data[0], &data[1], &data[2], &data[3],
                                          &data[4], NULL);
     round = 1;
     enumerator = enumerator_create_filter(list->create_enumerator(list),
                                     (void*)filter, (void*)101, destroy_data);
     while (enumerator->enumerate(enumerator, &v, &w, &x, &y, &z))
     {
         ck_assert_int_eq(v, round);
         ck_assert_int_eq(w, round + 1);
         ck_assert_int_eq(x, round + 2);
         ck_assert_int_eq(y, round + 3);
         ck_assert_int_eq(z, round + 4);
         round++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(round, 6);
     list->destroy(list);
 }
END_TEST START_TEST (test_filtered_filter)
Definition at line 156 of file test_enumerator.c.
References ck_assert, ck_assert_int_eq, count, linked_list_t::create_enumerator, data, enumerator_t::destroy, linked_list_t::destroy, destroy_data_called, enumerator_t::enumerate, enumerator_create_filter(), filter_odd(), linked_list_create_with_items(), and list.
 {
     int data[5] = {1,2,3,4,5}, count, x;
     linked_list_t *list;
     enumerator_t *enumerator;
     list = linked_list_create_with_items(&data[0], &data[1], &data[2], &data[3],
                                          &data[4], NULL);
     count = 0;
     /* should also work without destructor, so set this manually */
     destroy_data_called = 1;
     enumerator = enumerator_create_filter(list->create_enumerator(list),
                                          (void*)filter_odd, (void*)101, NULL);
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert(x % 2 == 0);
         count++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(count, 2);
     list->destroy(list);
 }
START_TEST (test_nested)
Definition at line 199 of file test_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, create_inner(), enumerator_t::destroy, linked_list_t::destroy, destroy_data(), enumerator_t::enumerate, enumerator_create_nested(), linked_list_create(), linked_list_create_with_items(), and list.
 {
     linked_list_t *list, *l1, *l2, *l3;
     enumerator_t *enumerator;
     intptr_t x;
     int round;
     l1 = linked_list_create_with_items((void*)1, (void*)2, NULL);
     l2 = linked_list_create();
     l3 = linked_list_create_with_items((void*)3, (void*)4, (void*)5, NULL);
     list = linked_list_create_with_items(l1, l2, l3, NULL);
     round = 1;
     enumerator = enumerator_create_nested(list->create_enumerator(list),
                                 (void*)create_inner, (void*)101, destroy_data);
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         round++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(round, 6);
     list->destroy(list);
     l1->destroy(l1);
     l2->destroy(l2);
     l3->destroy(l3);
 }
END_TEST START_TEST (test_nested_reset)
Definition at line 229 of file test_enumerator.c.
References ck_assert, ck_assert_int_eq, count, linked_list_t::create_enumerator, create_inner(), enumerator_t::destroy, linked_list_t::destroy, destroy_data(), enumerator_t::enumerate, enumerator_create_nested(), linked_list_create(), linked_list_create_with_items(), list, and linked_list_t::reset_enumerator.
 {
     linked_list_t *list, *l1, *l2, *l3;
     enumerator_t *outer, *enumerator;
     intptr_t x;
     int count = 0;
     l1 = linked_list_create_with_items((void*)1, (void*)2, NULL);
     l2 = linked_list_create();
     l3 = linked_list_create_with_items((void*)3, (void*)4, (void*)5, NULL);
     list = linked_list_create_with_items(l1, l2, l3, NULL);
     outer = list->create_enumerator(list);
     enumerator = enumerator_create_nested(outer, (void*)create_inner,
                                          (void*)101, destroy_data);
     while (enumerator->enumerate(enumerator, &x))
     {
         count++;
     }
     ck_assert_int_eq(count, 5);
     list->reset_enumerator(list, outer);
     ck_assert(enumerator->enumerate(enumerator, &x));
     ck_assert_int_eq(x, 1);
     enumerator->destroy(enumerator);
     list->destroy(list);
     l1->destroy(l1);
     l2->destroy(l2);
     l3->destroy(l3);
 }
END_TEST START_TEST (test_nested_empty)
Definition at line 262 of file test_enumerator.c.
References ck_assert_int_eq, count, linked_list_t::create_enumerator, create_inner(), enumerator_t::destroy, linked_list_t::destroy, destroy_data(), enumerator_t::enumerate, enumerator_create_nested(), linked_list_create(), and list.
 {
     linked_list_t *list;
     enumerator_t *enumerator;
     intptr_t x;
     int count;
     list = linked_list_create();
     count = 0;
     enumerator = enumerator_create_nested(list->create_enumerator(list),
                                 (void*)create_inner, (void*)101, destroy_data);
     while (enumerator->enumerate(enumerator, &x))
     {
         count++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(count, 0);
     list->destroy(list);
 }
END_TEST START_TEST (test_nested_null)
Definition at line 284 of file test_enumerator.c.
References ck_assert_int_eq, count, linked_list_t::create_enumerator, create_inner_null(), enumerator_t::destroy, linked_list_t::destroy, destroy_data_called, enumerator_t::enumerate, enumerator_create_nested(), linked_list_create_with_items(), and list.
 {
     linked_list_t *list;
     enumerator_t *enumerator;
     intptr_t x;
     int count;
     list = linked_list_create_with_items((void*)1, NULL);
     count = 0;
     /* should also work without destructor, so set this manually */
     destroy_data_called = 1;
     enumerator = enumerator_create_nested(list->create_enumerator(list),
                                     (void*)create_inner_null, (void*)101, NULL);
     while (enumerator->enumerate(enumerator, &x))
     {
         count++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(count, 0);
     list->destroy(list);
 }
END_TEST START_TEST (test_cleaner)
Definition at line 313 of file test_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, linked_list_t::destroy, destroy_data(), enumerator_t::enumerate, enumerator_create_cleaner(), linked_list_create_with_items(), and list.
 {
     enumerator_t *enumerator;
     linked_list_t *list;
     intptr_t x;
     int round;
     list = linked_list_create_with_items((void*)1, (void*)2, NULL);
     round = 1;
     enumerator = enumerator_create_cleaner(list->create_enumerator(list),
                                            destroy_data, (void*)101);
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         round++;
     }
     ck_assert_int_eq(round, 3);
     enumerator->destroy(enumerator);
     list->destroy(list);
 }
START_TEST (test_single)
Definition at line 355 of file test_enumerator.c.
References do_test_single(), and enumerator_create_single().
 {
     enumerator_t *enumerator;
     enumerator = enumerator_create_single((void*)1, NULL);
     do_test_single(enumerator);
 }
END_TEST START_TEST (test_single_cleanup)
Definition at line 364 of file test_enumerator.c.
References do_test_single(), enumerator_create_single(), and single_cleanup().
 {
     enumerator_t *enumerator;
     enumerator = enumerator_create_single((void*)1, single_cleanup);
     do_test_single(enumerator);
 }
Variable Documentation
END_TEST int destroy_data_called static
Definition at line 83 of file test_enumerator.c.
Referenced by destroy_data(), START_SETUP(), START_TEARDOWN(), and START_TEST().
const char** results
Definition at line 33 of file test_enumerator.c.
Referenced by METHOD(), and START_TEST().
char* sep
Definition at line 31 of file test_enumerator.c.
Referenced by add_hash(), atodn(), CALLBACK(), enumerate_token_enum(), enumerator_create_token(), host_create_from_range(), kw_end(), METHOD(), parse_protoport(), START_TEST(), and traffic_selector_printf_hook().
char* string
Definition at line 30 of file test_enumerator.c.
Referenced by add_attrs_natural_lang(), add_machine_type_model(), add_time_source(), add_vendor_name(), handle_ietf_message(), host_create_from_subnet(), imv_lang_string_select_string(), METHOD(), parse_specifier(), pop_string(), and START_TEST().
const char* token_results1[] = { "abc", "cde", "efg" } static
Definition at line 26 of file test_enumerator.c.
const char* token_results2[] = { "a", "b", "c" } static
Definition at line 27 of file test_enumerator.c.
struct { ... } token_tests[]
Initial value:
= {
    {"abc, cde, efg", ",", " ", token_results1},
    {" abc 1:2 cde;3  4efg5.  ", ":;.,", " 12345", token_results1},
    {"abc.cde,efg", ",.", "", token_results1},
    {"  abc   cde  efg  ", " ", " ", token_results1},
    {"a'abc' c 'cde' cefg", " ", " abcd", token_results1},
    {"'abc' abc 'cde'd 'efg'", " ", " abcd", token_results1},
    {"a, b, c", ",", " ", token_results2},
    {"a,b,c", ",", " ", token_results2},
    {" a 1:2 b;3  4c5.  ", ":;.,", " 12345", token_results2},
    {"a.b,c", ",.", "", token_results2},
    {"  a   b  c  ", " ", " ", token_results2},
}
Referenced by enumerator_suite_create(), and START_TEST().
char* trim
Definition at line 32 of file test_enumerator.c.
Referenced by enumerate_token_enum(), enumerator_create_token(), and START_TEST().