strongSwan: gmp_rsa_private_key.c File Reference
gmp_rsa_private_key.c File Reference
#include <gmp.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include "gmp_rsa_private_key.h"
#include "gmp_rsa_public_key.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
Classes
struct private_gmp_rsa_private_key_t
Macros
#define PUBLIC_EXPONENT 0x10001
Typedefs
typedef struct
private_gmp_rsa_private_key_t private_gmp_rsa_private_key_t
Functions
chunk_t gmp_mpz_to_chunk (const mpz_t value)
static void mpz_clear_sensitive (mpz_t z)
static status_t compute_prime (size_t prime_size, bool safe, mpz_t *p, mpz_t *q)
static chunk_t rsadp (private_gmp_rsa_private_key_t *this, chunk_t data)
static chunk_t rsasp1 (private_gmp_rsa_private_key_t *this, chunk_t data)
static bool build_emsa_pkcs1_signature (private_gmp_rsa_private_key_t *this, hash_algorithm_t hash_algorithm, chunk_t data, chunk_t *signature)
METHOD (private_key_t, get_type, key_type_t, private_gmp_rsa_private_key_t *this)
METHOD (private_key_t, sign, bool, private_gmp_rsa_private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
METHOD (private_key_t, decrypt, bool, private_gmp_rsa_private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
METHOD (private_key_t, get_keysize, int, private_gmp_rsa_private_key_t *this)
METHOD (private_key_t, get_public_key, public_key_t *, private_gmp_rsa_private_key_t *this)
METHOD (private_key_t, get_encoding, bool, private_gmp_rsa_private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (private_key_t, get_fingerprint, bool, private_gmp_rsa_private_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (private_key_t, get_ref, private_key_t *, private_gmp_rsa_private_key_t *this)
METHOD (private_key_t, destroy, void, private_gmp_rsa_private_key_t *this)
static status_t check (private_gmp_rsa_private_key_t *this)
static
private_gmp_rsa_private_key_t * gmp_rsa_private_key_create_empty (void)
gmp_rsa_private_key_t * gmp_rsa_private_key_gen (key_type_t type, va_list args)
gmp_rsa_private_key_t * gmp_rsa_private_key_load (key_type_t type, va_list args)
Macro Definition Documentation
#define PUBLIC_EXPONENT 0x10001
Public exponent to use for key generation.
Definition at line 39 of file gmp_rsa_private_key.c.
Referenced by gmp_rsa_private_key_gen().
Typedef Documentation
typedef struct private_gmp_rsa_private_key_t private_gmp_rsa_private_key_t
Definition at line 41 of file gmp_rsa_private_key.c.
Function Documentation
static bool build_emsa_pkcs1_signature (private_gmp_rsa_private_key_t * this, hash_algorithm_t hash_algorithm, chunk_t data, chunk_t * signature) static
Build a signature using the PKCS#1 EMSA scheme
Definition at line 267 of file gmp_rsa_private_key.c.
References hasher_t::allocate_hash, asn1_algorithmIdentifier(), ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_simple_object(), asn1_wrap(), chunk_empty, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, free(), hash, HASH_UNKNOWN, hasher, hasher_algorithm_to_oid(), chunk_t::len, lib, malloc(), memcpy, memset, n, OID_UNKNOWN, chunk_t::ptr, rsasp1(), and TRUE.
Referenced by METHOD().
 {
     chunk_t digestInfo = chunk_empty;
     chunk_t em;
     if (hash_algorithm != HASH_UNKNOWN)
     {
         hasher_t *hasher;
         chunk_t hash;
         int hash_oid = hasher_algorithm_to_oid(hash_algorithm);
         if (hash_oid == OID_UNKNOWN)
         {
             return FALSE;
         }
         hasher = lib->crypto->create_hasher(lib->crypto, hash_algorithm);
         if (!hasher || !hasher->allocate_hash(hasher, data, &hash))
         {
             DESTROY_IF(hasher);
             return FALSE;
         }
         hasher->destroy(hasher);
         /* build DER-encoded digestInfo */
         digestInfo = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_algorithmIdentifier(hash_oid),
                         asn1_simple_object(ASN1_OCTET_STRING, hash)
                       );
         chunk_free(&hash);
         data = digestInfo;
     }
     if (data.len > this->k - 3)
     {
         free(digestInfo.ptr);
         DBG1(DBG_LIB, "unable to sign %d bytes using a %dbit key", data.len,
              mpz_sizeinbase(this->n, 2));
         return FALSE;
     }
     /* build chunk to rsa-decrypt:
      * EM = 0x00 || 0x01 || PS || 0x00 || T.
      * PS = 0xFF padding, with length to fill em
      * T = encoded_hash
      */
     em.len = this->k;
     em.ptr = malloc(em.len);
     /* fill em with padding */
     memset(em.ptr, 0xFF, em.len);
     /* set magic bytes */
     *(em.ptr) = 0x00;
     *(em.ptr+1) = 0x01;
     *(em.ptr + em.len - data.len - 1) = 0x00;
     /* set DER-encoded hash */
     memcpy(em.ptr + em.len - data.len, data.ptr, data.len);
     /* build signature */
     *signature = rsasp1(this, em);
     free(digestInfo.ptr);
     free(em.ptr);
     return TRUE;
 }
static status_t check (private_gmp_rsa_private_key_t * this) static
Check the loaded key if it is valid and usable
Definition at line 528 of file gmp_rsa_private_key.c.
References BITS_PER_BYTE, DBG1, DBG_LIB, FAILED, m, mpz_clear_sensitive(), n, q, status, and SUCCESS.
Referenced by gmp_rsa_private_key_load().
 {
     mpz_t u, p1, q1;
     status_t status = SUCCESS;
     /* PKCS#1 1.5 section 6 requires modulus to have at least 12 octets.
      * We actually require more (for security).
      */
     if (this->k < 512 / BITS_PER_BYTE)
     {
         DBG1(DBG_LIB, "key shorter than 512 bits");
         return FAILED;
     }
     /* we picked a max modulus size to simplify buffer allocation */
     if (this->k > 8192 / BITS_PER_BYTE)
     {
         DBG1(DBG_LIB, "key larger than 8192 bits");
         return FAILED;
     }
     mpz_init(u);
     mpz_init(p1);
     mpz_init(q1);
     /* precompute p1 = p-1 and q1 = q-1 */
     mpz_sub_ui(p1, this->p, 1);
     mpz_sub_ui(q1, this->q, 1);
     /* check that n == p * q */
     mpz_mul(u, this->p, this->q);
     if (mpz_cmp(u, this->n) != 0)
     {
         status = FAILED;
     }
     /* check that e divides neither p-1 nor q-1 */
     mpz_mod(u, p1, this->e);
     if (mpz_cmp_ui(u, 0) == 0)
     {
         status = FAILED;
     }
     mpz_mod(u, q1, this->e);
     if (mpz_cmp_ui(u, 0) == 0)
     {
         status = FAILED;
     }
     /* check that d is e^-1 (mod lcm(p-1, q-1)) */
     /* see PKCS#1v2, aka RFC 2437, for the "lcm" */
     mpz_lcm(this->m, p1, q1);
     mpz_mul(u, *this->d, this->e);
     mpz_mod(u, u, this->m);
     if (mpz_cmp_ui(u, 1) != 0)
     {
         status = FAILED;
     }
     /* check that exp1 is d mod (p-1) */
     mpz_mod(u, *this->d, p1);
     if (mpz_cmp(u, this->exp1) != 0)
     {
         status = FAILED;
     }
     /* check that exp2 is d mod (q-1) */
     mpz_mod(u, *this->d, q1);
     if (mpz_cmp(u, this->exp2) != 0)
     {
         status = FAILED;
     }
     /* check that coeff is (q^-1) mod p */
     mpz_mul(u, this->coeff, this->q);
     mpz_mod(u, u, this->p);
     if (mpz_cmp_ui(u, 1) != 0)
     {
         status = FAILED;
     }
     mpz_clear_sensitive(u);
     mpz_clear_sensitive(p1);
     mpz_clear_sensitive(q1);
     if (status != SUCCESS)
     {
         DBG1(DBG_LIB, "key integrity tests failed");
     }
     return status;
 }
static status_t compute_prime (size_t prime_size, bool safe, mpz_t * p, mpz_t * q) static
Create a mpz prime of at least prime_size
Definition at line 156 of file gmp_rsa_private_key.c.
References rng_t::allocate_bytes, chunk_clear(), count, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG2, DBG_LIB, rng_t::destroy, FAILED, chunk_t::len, lib, chunk_t::ptr, rng, rng_quality_names, RNG_TRUE, and SUCCESS.
Referenced by gmp_rsa_private_key_gen().
 {
     rng_t *rng;
     chunk_t random_bytes;
     int count = 0;
     rng = lib->crypto->create_rng(lib->crypto, RNG_TRUE);
     if (!rng)
     {
         DBG1(DBG_LIB, "no RNG of quality %N found", rng_quality_names,
              RNG_TRUE);
         return FAILED;
     }
     mpz_init(*p);
     mpz_init(*q);
     do
     {
         if (!rng->allocate_bytes(rng, prime_size, &random_bytes))
         {
             DBG1(DBG_LIB, "failed to allocate random prime");
             mpz_clear(*p);
             mpz_clear(*q);
             rng->destroy(rng);
             return FAILED;
         }
         /* make sure the two most significant bits are set */
         if (safe)
         {
             random_bytes.ptr[0] &= 0x7F;
             random_bytes.ptr[0] |= 0x60;
             mpz_import(*q, random_bytes.len, 1, 1, 1, 0, random_bytes.ptr);
             do
             {
                 count++;
                 mpz_nextprime (*q, *q);
                 mpz_mul_ui(*p, *q, 2);
                 mpz_add_ui(*p, *p, 1);
             }
             while (mpz_probab_prime_p(*p, 10) == 0);
             DBG2(DBG_LIB, "safe prime found after %d iterations", count);
         }
         else
         {
             random_bytes.ptr[0] |= 0xC0;
             mpz_import(*p, random_bytes.len, 1, 1, 1, 0, random_bytes.ptr);
             mpz_nextprime (*p, *p);
         }
         chunk_clear(&random_bytes);
     }
     /* check if the prime isn't too large */
     while (((mpz_sizeinbase(*p, 2) + 7) / 8) > prime_size);
     rng->destroy(rng);
     /* additionally return p-1 */
     mpz_sub_ui(*q, *p, 1);
     return SUCCESS;
 }
chunk_t gmp_mpz_to_chunk (const mpz_t value)
Convert a MP integer into a chunk_t
Definition at line 126 of file gmp_rsa_private_key.c.
References BITS_PER_BYTE, chunk_t::len, n, and chunk_t::ptr.
Referenced by METHOD().
 {
     chunk_t n;
     n.len = 1 + mpz_sizeinbase(value, 2) / BITS_PER_BYTE;
     n.ptr = mpz_export(NULL, NULL, 1, n.len, 1, 0, value);
     if (n.ptr == NULL)
     {   /* if we have zero in "value", gmp returns NULL */
         n.len = 0;
     }
     return n;
 }
static private_gmp_rsa_private_key_t* gmp_rsa_private_key_create_empty (void) static
Internal generic constructor
Definition at line 623 of file gmp_rsa_private_key.c.
References INIT, private_key_belongs_to(), private_key_equals(), and private_key_has_fingerprint().
Referenced by gmp_rsa_private_key_gen(), and gmp_rsa_private_key_load().
 {
     private_gmp_rsa_private_key_t *this;
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .sign = _sign,
                 .decrypt = _decrypt,
                 .get_keysize = _get_keysize,
                 .get_public_key = _get_public_key,
                 .equals = private_key_equals,
                 .belongs_to = private_key_belongs_to,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = private_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .threshold = 1,
         .ref = 1,
     );
     return this;
 }
METHOD (private_key_t , get_type , key_type_t , private_gmp_rsa_private_key_t * this)
Definition at line 336 of file gmp_rsa_private_key.c.
References KEY_RSA.
 {
     return KEY_RSA;
 }
METHOD (private_key_t , sign , bool , private_gmp_rsa_private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * signature)
Definition at line 342 of file gmp_rsa_private_key.c.
References build_emsa_pkcs1_signature(), DBG1, DBG_LIB, FALSE, HASH_MD5, HASH_SHA1, HASH_SHA224, HASH_SHA256, HASH_SHA384, HASH_SHA512, HASH_UNKNOWN, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, and signature_scheme_names.
 {
     switch (scheme)
     {
         case SIGN_RSA_EMSA_PKCS1_NULL:
             return build_emsa_pkcs1_signature(this, HASH_UNKNOWN, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA1:
             return build_emsa_pkcs1_signature(this, HASH_SHA1, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA224:
             return build_emsa_pkcs1_signature(this, HASH_SHA224, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA256:
             return build_emsa_pkcs1_signature(this, HASH_SHA256, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA384:
             return build_emsa_pkcs1_signature(this, HASH_SHA384, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA512:
             return build_emsa_pkcs1_signature(this, HASH_SHA512, data, signature);
         case SIGN_RSA_EMSA_PKCS1_MD5:
             return build_emsa_pkcs1_signature(this, HASH_MD5, data, signature);
         default:
             DBG1(DBG_LIB, "signature scheme %N not supported in RSA",
                  signature_scheme_names, scheme);
             return FALSE;
     }
 }
METHOD (private_key_t , decrypt , bool , private_gmp_rsa_private_key_t * this, encryption_scheme_t scheme, chunk_t crypto, chunk_t * plain)
Definition at line 369 of file gmp_rsa_private_key.c.
References chunk_clear(), chunk_clone, DBG1, DBG_LIB, ENCRYPT_RSA_PKCS1, encryption_scheme_names, end, FALSE, chunk_t::len, chunk_t::ptr, rsadp(), and TRUE.
 {
     chunk_t em, stripped;
     bool success = FALSE;
     if (scheme != ENCRYPT_RSA_PKCS1)
     {
         DBG1(DBG_LIB, "encryption scheme %N not supported",
              encryption_scheme_names, scheme);
         return FALSE;
     }
     /* rsa decryption using PKCS#1 RSADP */
     stripped = em = rsadp(this, crypto);
     /* PKCS#1 v1.5 8.1 encryption-block formatting (EB = 00 || 02 || PS || 00 || D) */
     /* check for hex pattern 00 02 in decrypted message */
     if ((*stripped.ptr++ != 0x00) || (*(stripped.ptr++) != 0x02))
     {
         DBG1(DBG_LIB, "incorrect padding - probably wrong rsa key");
         goto end;
     }
     stripped.len -= 2;
     /* the plaintext data starts after first 0x00 byte */
     while (stripped.len-- > 0 && *stripped.ptr++ != 0x00)
     if (stripped.len == 0)
     {
         DBG1(DBG_LIB, "no plaintext data");
         goto end;
     }
     *plain = chunk_clone(stripped);
     success = TRUE;
 end:
     chunk_clear(&em);
     return success;
 }
METHOD (private_key_t , get_keysize , int , private_gmp_rsa_private_key_t * this)
Definition at line 412 of file gmp_rsa_private_key.c.
References n.
 {
     return mpz_sizeinbase(this->n, 2);
 }
METHOD (private_key_t , get_public_key , public_key_t * , private_gmp_rsa_private_key_t * this)
Definition at line 418 of file gmp_rsa_private_key.c.
References BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_free(), credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, gmp_mpz_to_chunk(), KEY_RSA, lib, and n.
 {
     chunk_t n, e;
     public_key_t *public;
     n = gmp_mpz_to_chunk(this->n);
     e = gmp_mpz_to_chunk(this->e);
     public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                         BUILD_RSA_MODULUS, n, BUILD_RSA_PUB_EXP, e, BUILD_END);
     chunk_free(&n);
     chunk_free(&e);
     return public;
 }
METHOD (private_key_t , get_encoding , bool , private_gmp_rsa_private_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 435 of file gmp_rsa_private_key.c.
References chunk_clear(), chunk_free(), CRED_PART_END, CRED_PART_RSA_COEFF, CRED_PART_RSA_EXP1, CRED_PART_RSA_EXP2, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PRIME1, CRED_PART_RSA_PRIME2, CRED_PART_RSA_PRIV_EXP, CRED_PART_RSA_PUB_EXP, cred_encoding_t::encode, library_t::encoding, gmp_mpz_to_chunk(), lib, n, and q.
 {
     chunk_t n, e, d, p, q, exp1, exp2, coeff;
     bool success;
     n = gmp_mpz_to_chunk(this->n);
     e = gmp_mpz_to_chunk(this->e);
     d = gmp_mpz_to_chunk(*this->d);
     p = gmp_mpz_to_chunk(this->p);
     q = gmp_mpz_to_chunk(this->q);
     exp1 = gmp_mpz_to_chunk(this->exp1);
     exp2 = gmp_mpz_to_chunk(this->exp2);
     coeff = gmp_mpz_to_chunk(this->coeff);
     success = lib->encoding->encode(lib->encoding,
                             type, NULL, encoding, CRED_PART_RSA_MODULUS, n,
                             CRED_PART_RSA_PUB_EXP, e, CRED_PART_RSA_PRIV_EXP, d,
                             CRED_PART_RSA_PRIME1, p, CRED_PART_RSA_PRIME2, q,
                             CRED_PART_RSA_EXP1, exp1, CRED_PART_RSA_EXP2, exp2,
                             CRED_PART_RSA_COEFF, coeff, CRED_PART_END);
     chunk_free(&n);
     chunk_free(&e);
     chunk_clear(&d);
     chunk_clear(&p);
     chunk_clear(&q);
     chunk_clear(&exp1);
     chunk_clear(&exp2);
     chunk_clear(&coeff);
     return success;
 }
METHOD (private_key_t , get_fingerprint , bool , private_gmp_rsa_private_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 469 of file gmp_rsa_private_key.c.
References chunk_free(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, cred_encoding_t::encode, library_t::encoding, cred_encoding_t::get_cache, gmp_mpz_to_chunk(), lib, n, and TRUE.
 {
     chunk_t n, e;
     bool success;
     if (lib->encoding->get_cache(lib->encoding, type, this, fp))
     {
         return TRUE;
     }
     n = gmp_mpz_to_chunk(this->n);
     e = gmp_mpz_to_chunk(this->e);
     success = lib->encoding->encode(lib->encoding, type, this, fp,
             CRED_PART_RSA_MODULUS, n, CRED_PART_RSA_PUB_EXP, e, CRED_PART_END);
     chunk_free(&n);
     chunk_free(&e);
     return success;
 }
METHOD (private_key_t , get_ref , private_key_t * , private_gmp_rsa_private_key_t * this)
Definition at line 490 of file gmp_rsa_private_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (private_key_t , destroy , void , private_gmp_rsa_private_key_t * this)
Definition at line 497 of file gmp_rsa_private_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), lib, m, mpz_clear_sensitive(), n, q, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         int i;
         mpz_clear(this->n);
         mpz_clear(this->e);
         mpz_clear(this->v);
         mpz_clear_sensitive(this->p);
         mpz_clear_sensitive(this->q);
         mpz_clear_sensitive(this->m);
         mpz_clear_sensitive(this->exp1);
         mpz_clear_sensitive(this->exp2);
         mpz_clear_sensitive(this->coeff);
         for (i = 0; i < this->threshold; i++)
         {
             mpz_clear_sensitive(*this->d + i);
         }
         free(this->d);
         lib->encoding->clear_cache(lib->encoding, this);
         free(this);
     }
 }
static void mpz_clear_sensitive (mpz_t z) static
Auxiliary function overwriting private key material with zero bytes
Definition at line 142 of file gmp_rsa_private_key.c.
References BITS_PER_BYTE, len, and memset.
Referenced by check(), gmp_rsa_private_key_gen(), METHOD(), and rsadp().
 {
     size_t len = mpz_size(z) * GMP_LIMB_BITS / BITS_PER_BYTE;
     u_int8_t *zeros = alloca(len);
     memset(zeros, 0, len);
     /* overwrite mpz_t with zero bytes before clearing it */
     mpz_import(z, len, 1, 1, 1, 0, zeros);
     mpz_clear(z);
 }
static chunk_t rsadp (private_gmp_rsa_private_key_t * this, chunk_t data) static
PKCS#1 RSADP function
Definition at line 223 of file gmp_rsa_private_key.c.
References chunk_t::len, mpz_clear_sensitive(), chunk_t::ptr, and q.
Referenced by METHOD(), and rsasp1().
 {
     mpz_t t1, t2;
     chunk_t decrypted;
     mpz_init(t1);
     mpz_init(t2);
     mpz_import(t1, data.len, 1, 1, 1, 0, data.ptr);
     mpz_powm(t2, t1, this->exp1, this->p);  /* m1 = c^dP mod p */
     mpz_powm(t1, t1, this->exp2, this->q);  /* m2 = c^dQ mod Q */
     mpz_sub(t2, t2, t1);                    /* h = qInv (m1 - m2) mod p */
     mpz_mod(t2, t2, this->p);
     mpz_mul(t2, t2, this->coeff);
     mpz_mod(t2, t2, this->p);
     mpz_mul(t2, t2, this->q);               /* m = m2 + h q */
     mpz_add(t1, t1, t2);
     decrypted.len = this->k;
     decrypted.ptr = mpz_export(NULL, NULL, 1, decrypted.len, 1, 0, t1);
     if (decrypted.ptr == NULL)
     {
         decrypted.len = 0;
     }
     mpz_clear_sensitive(t1);
     mpz_clear_sensitive(t2);
     return decrypted;
 }
static chunk_t rsasp1 (private_gmp_rsa_private_key_t * this, chunk_t data) static
PKCS#1 RSASP1 function
Definition at line 259 of file gmp_rsa_private_key.c.
References rsadp().
Referenced by build_emsa_pkcs1_signature().
 {
     return rsadp(this, data);
 }