strongSwan: eap_method_t Struct Reference
eap_method_t Struct Reference
eap_method
#include "eap_method.h"
Public Attributes
status_t(* initiate)(eap_method_t *this, eap_payload_t **out)
status_t(* process)(eap_method_t *this, eap_payload_t *in, eap_payload_t **out)
eap_type_t(* get_type)(eap_method_t *this, u_int32_t *vendor)
bool(* is_mutual)(eap_method_t *this)
status_t(* get_msk)(eap_method_t *this, chunk_t *msk)
u_int8_t(* get_identifier)(eap_method_t *this)
void(* set_identifier)(eap_method_t *this, u_int8_t identifier)
auth_cfg_t *(* get_auth)(eap_method_t *this)
void(* destroy)(eap_method_t *this)
Detailed Description
Interface of an EAP method for server and client side.
An EAP method initiates an EAP exchange and processes requests and responses. An EAP method may need multiple exchanges before succeeding, and the eap_authentication may use multiple EAP methods to authenticate a peer. To accomplish these requirements, all EAP methods have their own implementation while the eap_authenticatior uses one or more of these EAP methods. Sending of EAP(SUCCESS/FAILURE) message is not the job of the method, the eap_authenticator does this. An EAP method may establish a MSK, this is used the complete the authentication. Even if a mutual EAP method is used, the traditional AUTH payloads are required. Only these include the nonces and messages from ike_sa_init and therefore prevent man in the middle attacks. The EAP method must use an initial EAP identifier value != 0, as a preceding EAP-Identity exchange always uses identifier 0.
Definition at line 62 of file eap_method.h.
Member Data Documentation
void(* eap_method_t::destroy)(eap_method_t *this)
Destroys a eap_method_t object.
Definition at line 154 of file eap_method.h.
Referenced by METHOD(), and verify_eap().
auth_cfg_t*(* eap_method_t::get_auth)(eap_method_t *this)
Get authentication details performed by this EAP method.
After EAP completion, the auth data contains additional information of the authentication process, used certificates etc. This method is optional to implement, but if it is, it must return a valid auth_cfg.
Returns
auth method, internal data
Definition at line 149 of file eap_method.h.
u_int8_t(* eap_method_t::get_identifier)(eap_method_t *this)
Get the current EAP identifier.
Returns
current EAP identifier
Definition at line 129 of file eap_method.h.
status_t(* eap_method_t::get_msk)(eap_method_t *this, chunk_t *msk)
Get the MSK established by this EAP method.
Not all EAP methods establish a shared secret. For implementations of the EAP-Identity method, get_msk() returns the received identity.
Parameters
msk chunk receiving internal stored MSK
Returns
SUCCESS, or
FAILED, if MSK not established (yet)
Definition at line 122 of file eap_method.h.
Referenced by process_eap().
eap_type_t(* eap_method_t::get_type)(eap_method_t *this, u_int32_t *vendor)
Get the EAP type implemented in this method.
Parameters
vendor pointer receiving vendor identifier for type, 0 for none
Returns
type of the EAP method
Definition at line 99 of file eap_method.h.
status_t(* eap_method_t::initiate)(eap_method_t *this, eap_payload_t **out)
Initiate the EAP exchange.
initiate() is only useable for server implementations, as clients only reply to server requests. A eap_payload is created in "out" if result is NEED_MORE.
Parameters
out eap_payload to send to the client
Returns
NEED_MORE, if an other exchange is required
FAILED, if unable to create eap request payload
Definition at line 76 of file eap_method.h.
Referenced by process_eap(), and verify_eap().
bool(* eap_method_t::is_mutual)(eap_method_t *this)
Check if this EAP method authenticates the server.
Some EAP methods provide mutual authentication and allow authentication using only EAP, if the peer supports it.
Returns
TRUE if methods provides mutual authentication
Definition at line 109 of file eap_method.h.
status_t(* eap_method_t::process)(eap_method_t *this, eap_payload_t *in, eap_payload_t **out)
Process a received EAP message.
A eap_payload is created in "out" if result is NEED_MORE.
Parameters
in eap_payload response received
out created eap_payload to send
Returns
NEED_MORE, if an other exchange is required
FAILED, if EAP method failed
SUCCESS, if EAP method succeeded
Definition at line 90 of file eap_method.h.
Referenced by process_eap(), and verify_eap().
void(* eap_method_t::set_identifier)(eap_method_t *this, u_int8_t identifier)
Set the EAP identifier to a deterministic value, overwriting the randomly initialized default value.
Parameters
identifier current EAP identifier
Definition at line 137 of file eap_method.h.
The documentation for this struct was generated from the following file:
eap_method.h