strongSwan: ita_attr_get_settings.c File Reference
ita_attr_get_settings.c File Reference
#include <string.h>
#include "ita_attr.h"
#include "ita_attr_get_settings.h"
#include <bio/bio_reader.h>
#include <bio/bio_writer.h>
#include <collections/linked_list.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_ita_attr_get_settings_t
Macros
#define _GNU_SOURCE /* for stdndup() */
#define ITA_GET_SETTINGS_MIN_SIZE 4
Typedefs
typedef struct
private_ita_attr_get_settings_t private_ita_attr_get_settings_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ita_attr_get_settings_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ita_attr_get_settings_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ita_attr_get_settings_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ita_attr_get_settings_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ita_attr_get_settings_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ita_attr_get_settings_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ita_attr_get_settings_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ita_attr_get_settings_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ita_attr_get_settings_t *this)
METHOD (ita_attr_get_settings_t, add, void, private_ita_attr_get_settings_t *this, char *name)
METHOD (ita_attr_get_settings_t, create_enumerator, enumerator_t *, private_ita_attr_get_settings_t *this)
pa_tnc_attr_t * ita_attr_get_settings_create (char *name)
pa_tnc_attr_t * ita_attr_get_settings_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 16 of file ita_attr_get_settings.c.
#define ITA_GET_SETTINGS_MIN_SIZE 4
ITA Get Settings
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Settings Count | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Name Length | Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Name Length | Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ...........................
Definition at line 49 of file ita_attr_get_settings.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ita_attr_get_settings_t private_ita_attr_get_settings_t
Definition at line 28 of file ita_attr_get_settings.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ita_attr_get_settings_t * this)
Definition at line 92 of file ita_attr_get_settings.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ita_attr_get_settings_t * this)
Definition at line 98 of file ita_attr_get_settings.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ita_attr_get_settings_t * this)
Definition at line 104 of file ita_attr_get_settings.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ita_attr_get_settings_t * this, bool noskip)
Definition at line 110 of file ita_attr_get_settings.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ita_attr_get_settings_t * this)
Definition at line 116 of file ita_attr_get_settings.c.
References bio_writer_create(), chunk_create(), linked_list_t::create_enumerator, enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::extract_buf, linked_list_t::get_count, ITA_GET_SETTINGS_MIN_SIZE, length, list, name, value, bio_writer_t::write_data16, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     char *name;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(ITA_GET_SETTINGS_MIN_SIZE);
     writer->write_uint32(writer, this->list->get_count(this->list));
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &name))
     {
         writer->write_data16(writer, chunk_create(name, strlen(name)));
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ita_attr_get_settings_t * this, u_int32_t * offset)
Definition at line 142 of file ita_attr_get_settings.c.
References bio_reader_create(), count, DBG1, DBG_TNC, bio_reader_t::destroy, end, FAILED, linked_list_t::insert_last, ITA_GET_SETTINGS_MIN_SIZE, chunk_t::len, list, name, NEED_MORE, chunk_t::ptr, bio_reader_t::read_data16, bio_reader_t::read_uint32, status, strndup(), SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int32_t count;
     chunk_t name;
     status_t status = FAILED;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < ITA_GET_SETTINGS_MIN_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for ITA Get Settings attribute");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint32(reader, &count);
     *offset = ITA_GET_SETTINGS_MIN_SIZE;
     while (count--)
     {
         if (!reader->read_data16(reader, &name))
         {
             DBG1(DBG_TNC, "insufficient data for setting name");
             goto end;
         }
         *offset += 2 + name.len;
         this->list->insert_last(this->list, strndup(name.ptr, name.len));
     }
     status = SUCCESS;
 end:
     reader->destroy(reader);
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ita_attr_get_settings_t * this, chunk_t segment)
Definition at line 185 of file ita_attr_get_settings.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ita_attr_get_settings_t * this)
Definition at line 191 of file ita_attr_get_settings.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ita_attr_get_settings_t * this)
Definition at line 198 of file ita_attr_get_settings.c.
References linked_list_t::destroy_function, free(), list, ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         this->list->destroy_function(this->list, free);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ita_attr_get_settings_t , add , void , private_ita_attr_get_settings_t * this, char * name)
Definition at line 209 of file ita_attr_get_settings.c.
References linked_list_t::insert_last, list, and strdup.
 {
     this->list->insert_last(this->list, strdup(name));
 }
METHOD (ita_attr_get_settings_t , create_enumerator , enumerator_t * , private_ita_attr_get_settings_t * this)
Definition at line 215 of file ita_attr_get_settings.c.
References linked_list_t::create_enumerator, and list.
 {
     return this->list->create_enumerator(this->list);
 }