strongSwan: ha_plugin.c File Reference
ha_plugin.c File Reference
#include "ha_plugin.h"
#include "ha_ike.h"
#include "ha_child.h"
#include "ha_socket.h"
#include "ha_tunnel.h"
#include "ha_dispatcher.h"
#include "ha_segments.h"
#include "ha_ctl.h"
#include "ha_cache.h"
#include "ha_attribute.h"
#include <daemon.h>
#include <config/child_cfg.h>
Classes
struct private_ha_plugin_t
Typedefs
typedef struct private_ha_plugin_t private_ha_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_ha_plugin_t *this)
static bool initialize_plugin (private_ha_plugin_t *this)
static bool plugin_cb (private_ha_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_ha_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_ha_plugin_t *this)
plugin_t * ha_plugin_create ()
Typedef Documentation
typedef struct private_ha_plugin_t private_ha_plugin_t
Definition at line 30 of file ha_plugin.c.
Function Documentation
plugin_t* ha_plugin_create ()
Plugin constructor
Definition at line 215 of file ha_plugin.c.
References CAP_CHOWN, library_t::caps, DBG1, DBG_CFG, INIT, capabilities_t::keep, and lib.
 {
     private_ha_plugin_t *this;
     if (!lib->caps->keep(lib->caps, CAP_CHOWN))
     {   /* required to chown(2) control socket, ha_kernel also needs it at
          * runtime */
         DBG1(DBG_CFG, "ha plugin requires CAP_CHOWN capability");
         return NULL;
     }
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
static bool initialize_plugin (private_ha_plugin_t * this) static
Initialize plugin
Definition at line 102 of file ha_plugin.c.
References cache(), count, DBG1, DBG_CFG, FALSE, settings_t::get_bool, settings_t::get_int, settings_t::get_str, ha_attribute_create(), ha_cache_create(), ha_child_create(), ha_ctl_create(), ha_dispatcher_create(), ha_ike_create(), ha_kernel_create(), ha_segments_create(), ha_socket_create(), ha_tunnel_create(), lib, min, library_t::ns, SEGMENTS_MAX, library_t::settings, socket, and TRUE.
Referenced by plugin_cb().
 {
     char *local, *remote, *secret;
     u_int count;
     bool fifo, monitor, resync;
     local = lib->settings->get_str(lib->settings,
                                 "%s.plugins.ha.local", NULL, lib->ns);
     remote = lib->settings->get_str(lib->settings,
                                 "%s.plugins.ha.remote", NULL, lib->ns);
     secret = lib->settings->get_str(lib->settings,
                                 "%s.plugins.ha.secret", NULL, lib->ns);
     fifo = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.ha.fifo_interface", TRUE, lib->ns);
     monitor = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.ha.monitor", TRUE, lib->ns);
     resync = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.ha.resync", TRUE, lib->ns);
     count = min(SEGMENTS_MAX, lib->settings->get_int(lib->settings,
                                 "%s.plugins.ha.segment_count", 1, lib->ns));
     if (!local || !remote)
     {
         DBG1(DBG_CFG, "HA config misses local/remote address");
         return FALSE;
     }
     if (secret)
     {
         this->tunnel = ha_tunnel_create(local, remote, secret);
     }
     this->socket = ha_socket_create(local, remote);
     if (!this->socket)
     {
         return FALSE;
     }
     this->kernel = ha_kernel_create(count);
     this->segments = ha_segments_create(this->socket, this->kernel, this->tunnel,
                             count, strcmp(local, remote) > 0, monitor);
     this->cache = ha_cache_create(this->kernel, this->socket, this->tunnel,
                                   resync, count);
     if (fifo)
     {
         this->ctl = ha_ctl_create(this->segments, this->cache);
     }
     this->attr = ha_attribute_create(this->kernel, this->segments);
     this->dispatcher = ha_dispatcher_create(this->socket, this->segments,
                                         this->cache, this->kernel, this->attr);
     this->ike = ha_ike_create(this->socket, this->tunnel, this->cache);
     this->child = ha_child_create(this->socket, this->tunnel, this->segments,
                                   this->kernel);
     return TRUE;
 }
METHOD (plugin_t , get_name , char * , private_ha_plugin_t * this)
Definition at line 93 of file ha_plugin.c.
 {
     return "ha";
 }
METHOD (plugin_t , get_features , int , private_ha_plugin_t * this, plugin_feature_t * features[])
Definition at line 184 of file ha_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_PROVIDE, and PLUGIN_SDEPEND.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "ha"),
                 PLUGIN_SDEPEND(CUSTOM, "kernel-ipsec"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_ha_plugin_t * this)
Definition at line 196 of file ha_plugin.c.
References cache(), DESTROY_IF, free(), and socket.
 {
     DESTROY_IF(this->ctl);
     DESTROY_IF(this->ike);
     DESTROY_IF(this->child);
     DESTROY_IF(this->dispatcher);
     DESTROY_IF(this->attr);
     DESTROY_IF(this->cache);
     DESTROY_IF(this->segments);
     DESTROY_IF(this->kernel);
     DESTROY_IF(this->socket);
     DESTROY_IF(this->tunnel);
     free(this);
 }
static bool plugin_cb (private_ha_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Initialize plugin and register listener
Definition at line 158 of file ha_plugin.c.
References bus_t::add_listener, attribute_manager_t::add_provider, daemon_t::attributes, daemon_t::bus, charon, FALSE, initialize_plugin(), bus_t::remove_listener, attribute_manager_t::remove_provider, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         if (!initialize_plugin(this))
         {
             return FALSE;
         }
         charon->bus->add_listener(charon->bus, &this->segments->listener);
         charon->bus->add_listener(charon->bus, &this->ike->listener);
         charon->bus->add_listener(charon->bus, &this->child->listener);
         charon->attributes->add_provider(charon->attributes,
                                          &this->attr->provider);
     }
     else
     {
         charon->attributes->remove_provider(charon->attributes,
                                             &this->attr->provider);
         charon->bus->remove_listener(charon->bus, &this->segments->listener);
         charon->bus->remove_listener(charon->bus, &this->ike->listener);
         charon->bus->remove_listener(charon->bus, &this->child->listener);
     }
     return TRUE;
 }