strongSwan: aesni_ctr
aesni_ctr
aesni
Classes
struct aesni_ctr_t
Typedefs
typedef struct aesni_ctr_t aesni_ctr_t
Functions
aesni_ctr_t * aesni_ctr_create (encryption_algorithm_t algo, size_t key_size)
Variables
struct aesni_ctr_t __attribute__
Detailed Description
Typedef Documentation
typedef struct aesni_ctr_t aesni_ctr_t
Definition at line 26 of file aesni_ctr.h.
Function Documentation
aesni_ctr_t* aesni_ctr_create (encryption_algorithm_t algo, size_t key_size)
Create a aesni_ctr instance.
Parameters
algo encryption algorithm, AES_ENCR_CTR
key_size AES key size, in bytes
Returns
AES-CTR crypter, NULL if not supported
See header
Definition at line 593 of file aesni_ctr.c.
References private_aesni_ctr_t::crypt, ENCR_AES_CTR, encrypt_ctr128(), encrypt_ctr192(), encrypt_ctr256(), INIT_ALIGN, and private_aesni_ctr_t::key_size.
Referenced by METHOD().
 {
     private_aesni_ctr_t *this;
     if (algo != ENCR_AES_CTR)
     {
         return NULL;
     }
     switch (key_size)
     {
         case 0:
             key_size = 16;
             break;
         case 16:
         case 24:
         case 32:
             break;
         default:
             return NULL;
     }
     INIT_ALIGN(this, sizeof(__m128i),
         .public = {
             .crypter = {
                 .encrypt = _crypt,
                 .decrypt = _crypt,
                 .get_block_size = _get_block_size,
                 .get_iv_size = _get_iv_size,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .key_size = key_size,
     );
     switch (key_size)
     {
         case 16:
             this->crypt = encrypt_ctr128;
             break;
         case 24:
             this->crypt = encrypt_ctr192;
             break;
         case 32:
             this->crypt = encrypt_ctr256;
             break;
     }
     return &this->public;
 }
Variable Documentation
struct aesni_ctr_t __attribute__