strongSwan: iface.h File Reference
iface.h File Reference
#include <library.h>
#include <collections/enumerator.h>
#include <networking/host.h>
#include "mconsole.h"
#include "bridge.h"
#include "guest.h"
Classes
struct iface_t
Macros
#define TAP_DEVICE "/dev/net/tun"
Typedefs
typedef struct iface_t iface_t
Functions
iface_t * iface_create (char *name, guest_t *guest, mconsole_t *mconsole)
Macro Definition Documentation
#define TAP_DEVICE "/dev/net/tun"
Definition at line 23 of file iface.h.
Referenced by create_tap(), and destroy_tap().
Typedef Documentation
typedef struct iface_t iface_t
Definition at line 25 of file iface.h.
Function Documentation
iface_t* iface_create (char * name, guest_t * guest, mconsole_t * mconsole)
Create a new interface for a guest
Parameters
name name of the interface in the guest
guest guest this iface is connecting
mconsole mconsole of guest
Returns
interface descriptor, or NULL if failed
create the iface instance
Definition at line 256 of file iface.c.
References mconsole_t::add_iface, create_tap(), DBG1, DBG_LIB, destroy_tap(), free(), iface_control(), INIT, strdup, and TRUE.
Referenced by METHOD().
 {
     private_iface_t *this;
     INIT(this,
         .public = {
             .get_hostif = _get_hostif,
             .get_guestif = _get_guestif,
             .add_address = _add_address,
             .create_address_enumerator = _create_address_enumerator,
             .delete_address = _delete_address,
             .set_bridge = _set_bridge,
             .get_bridge = _get_bridge,
             .get_guest = _get_guest,
             .destroy = _destroy,
         },
         .mconsole = mconsole,
         .guestif = strdup(name),
         .guest = guest,
     );
     this->hostif = create_tap(this);
     if (this->hostif == NULL)
     {
         destroy_tap(this);
         free(this->guestif);
         free(this);
         return NULL;
     }
     if (!this->mconsole->add_iface(this->mconsole, this->guestif, this->hostif))
     {
         DBG1(DBG_LIB, "creating interface '%s' in guest failed", this->guestif);
         destroy_tap(this);
         free(this->guestif);
         free(this->hostif);
         free(this);
         return NULL;
     }
     if (!iface_control(this->hostif, TRUE))
     {
         DBG1(DBG_LIB, "bringing iface '%s' up failed: %m", this->hostif);
     }
     return &this->public;
 }