strongSwan: dumm.c File Reference
dumm.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdio.h>
#include <dirent.h>
#include <errno.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
#include "dumm.h"
Classes
struct private_dumm_t
struct template_enumerator_t
Macros
#define _GNU_SOURCE
#define PERME (S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH)
#define GUEST_DIR "guests"
#define TEMPLATE_DIR "templates"
Typedefs
typedef struct private_dumm_t private_dumm_t
Functions
METHOD (dumm_t, create_guest, guest_t *, private_dumm_t *this, char *name, char *kernel, char *master, char *args)
METHOD (dumm_t, create_guest_enumerator, enumerator_t *, private_dumm_t *this)
METHOD (dumm_t, delete_guest, void, private_dumm_t *this, guest_t *guest)
METHOD (dumm_t, create_bridge, bridge_t *, private_dumm_t *this, char *name)
METHOD (dumm_t, create_bridge_enumerator, enumerator_t *, private_dumm_t *this)
METHOD (dumm_t, delete_bridge, void, private_dumm_t *this, bridge_t *bridge)
METHOD (dumm_t, add_overlay, bool, private_dumm_t *this, char *dir)
METHOD (dumm_t, del_overlay, bool, private_dumm_t *this, char *dir)
METHOD (dumm_t, pop_overlay, bool, private_dumm_t *this)
static void clear_template (private_dumm_t *this)
METHOD (dumm_t, load_template, bool, private_dumm_t *this, char *name)
METHOD (enumerator_t, template_enumerate, bool, template_enumerator_t *this, char **template)
METHOD (enumerator_t, template_enumerator_destroy, void, template_enumerator_t *this)
METHOD (dumm_t, create_template_enumerator, enumerator_t *, private_dumm_t *this)
METHOD (dumm_t, destroy, void, private_dumm_t *this)
static void load_guests (private_dumm_t *this)
dumm_t * dumm_create (char *dir)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file dumm.c.
#define GUEST_DIR "guests"
Definition at line 32 of file dumm.c.
Referenced by dumm_create().
#define PERME (S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH)
Definition at line 31 of file dumm.c.
Referenced by dumm_create(), and METHOD().
#define TEMPLATE_DIR "templates"
Definition at line 33 of file dumm.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_dumm_t private_dumm_t
Definition at line 35 of file dumm.c.
Function Documentation
static void clear_template (private_dumm_t * this) static
disable the currently enabled template
Definition at line 214 of file dumm.c.
References free().
Referenced by METHOD().
 {
     if (this->template)
     {
         del_overlay(this, this->template);
         free(this->template);
         this->template = NULL;
     }
 }
dumm_t* dumm_create (char * dir)
create a dumm instance
Definition at line 376 of file dumm.c.
References asprintf(), DBG1, DBG_LIB, destroy(), free(), GUEST_DIR, INIT, linked_list_create(), load_guests(), PERME, and strdup.
Referenced by Init_dumm(), and main().
 {
     char cwd[PATH_MAX];
     private_dumm_t *this;
     INIT(this,
         .public = {
             .create_guest = _create_guest,
             .create_guest_enumerator = _create_guest_enumerator,
             .delete_guest = _delete_guest,
             .create_bridge = _create_bridge,
             .create_bridge_enumerator = _create_bridge_enumerator,
             .delete_bridge = _delete_bridge,
             .add_overlay = _add_overlay,
             .del_overlay = _del_overlay,
             .pop_overlay = _pop_overlay,
             .load_template = _load_template,
             .create_template_enumerator = _create_template_enumerator,
             .destroy = _destroy,
         },
     );
     if (dir && *dir == '/')
     {
         this->dir = strdup(dir);
     }
     else
     {
         if (getcwd(cwd, sizeof(cwd)) == NULL)
         {
             free(this);
             return NULL;
         }
         if (dir)
         {
             if (asprintf(&this->dir, "%s/%s", cwd, dir) < 0)
             {
                 this->dir = NULL;
             }
         }
         else
         {
             this->dir = strdup(cwd);
         }
     }
     if (asprintf(&this->guest_dir, "%s/%s", this->dir, GUEST_DIR) < 0)
     {
         this->guest_dir = NULL;
     }
     this->guests = linked_list_create();
     this->bridges = linked_list_create();
     if (this->dir == NULL || this->guest_dir == NULL ||
         (mkdir(this->guest_dir, PERME) < 0 && errno != EEXIST))
     {
         DBG1(DBG_LIB, "creating guest directory '%s' failed: %m",
              this->guest_dir);
         destroy(this);
         return NULL;
     }
     load_guests(this);
     return &this->public;
 }
static void load_guests (private_dumm_t * this) static
load all guests in our working dir
Definition at line 341 of file dumm.c.
References DBG1, DBG_LIB, dir, and guest_load().
Referenced by dumm_create().
 {
     DIR *dir;
     struct dirent *ent;
     guest_t *guest;
     dir = opendir(this->guest_dir);
     if (dir == NULL)
     {
         return;
     }
     while ((ent = readdir(dir)))
     {
         if (*ent->d_name == '.')
         {   /* skip ".", ".." and hidden files (such as ".svn") */
             continue;
         }
         guest = guest_load(this->guest_dir, ent->d_name);
         if (guest)
         {
             this->guests->insert_last(this->guests, guest);
         }
         else
         {
             DBG1(DBG_LIB, "loading guest in directory '%s' failed, skipped",
                  ent->d_name);
         }
     }
     closedir(dir);
 }
METHOD (dumm_t , create_guest , guest_t * , private_dumm_t * this, char * name, char * kernel, char * master, char * args)
Definition at line 52 of file dumm.c.
References guest_create().
 {
     guest_t *guest;
     guest = guest_create(this->guest_dir, name, kernel, master, args);
     if (guest)
     {
         this->guests->insert_last(this->guests, guest);
     }
     return guest;
 }
METHOD (dumm_t , create_guest_enumerator , enumerator_t * , private_dumm_t * this)
Definition at line 65 of file dumm.c.
 {
     return this->guests->create_enumerator(this->guests);
 }
METHOD (dumm_t , delete_guest , void , private_dumm_t * this, guest_t * guest)
Definition at line 71 of file dumm.c.
References guest_t::destroy, guest_t::get_name, ignore_result, len, and snprintf.
 {
     if (this->guests->remove(this->guests, guest, NULL))
     {
         char buf[512];
         int len;
         len = snprintf(buf, sizeof(buf), "rm -Rf %s/%s",
                        this->guest_dir, guest->get_name(guest));
         guest->destroy(guest);
         if (len > 8 && len < 512)
         {
             ignore_result(system(buf));
         }
     }
 }
METHOD (dumm_t , create_bridge , bridge_t * , private_dumm_t * this, char * name)
Definition at line 89 of file dumm.c.
References bridge_create().
 {
     bridge_t *bridge;
     bridge = bridge_create(name);
     if (bridge)
     {
         this->bridges->insert_last(this->bridges, bridge);
     }
     return bridge;
 }
METHOD (dumm_t , create_bridge_enumerator , enumerator_t * , private_dumm_t * this)
Definition at line 102 of file dumm.c.
 {
     return this->bridges->create_enumerator(this->bridges);
 }
METHOD (dumm_t , delete_bridge , void , private_dumm_t * this, bridge_t * bridge)
Definition at line 108 of file dumm.c.
References bridge_t::destroy.
 {
     if (this->bridges->remove(this->bridges, bridge, NULL))
     {
         bridge->destroy(bridge);
     }
 }
METHOD (dumm_t , add_overlay , bool , private_dumm_t * this, char * dir)
Definition at line 117 of file dumm.c.
References guest_t::add_overlay, DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, FALSE, guest_t::get_name, len, mkdir_p(), PERME, snprintf, and TRUE.
 {
     enumerator_t *enumerator;
     guest_t *guest;
     if (dir == NULL)
     {
         return TRUE;
     }
     if (strlen(dir) > PATH_MAX)
     {
         DBG1(DBG_LIB, "overlay directory string '%s' is too long", dir);
         return FALSE;
     }
     if (access(dir, F_OK) != 0)
     {
         if (!mkdir_p(dir, PERME))
         {
             DBG1(DBG_LIB, "creating overlay directory '%s' failed: %m", dir);
             return FALSE;
         }
     }
     enumerator = this->guests->create_enumerator(this->guests);
     while (enumerator->enumerate(enumerator, (void**)&guest))
     {
         char guest_dir[PATH_MAX];
         int len = snprintf(guest_dir, sizeof(guest_dir), "%s/%s", dir,
                            guest->get_name(guest));
         if (len < 0 || len >= sizeof(guest_dir))
         {
             goto error;
         }
         if (access(guest_dir, F_OK) != 0)
         {
             if (!mkdir_p(guest_dir, PERME))
             {
                 DBG1(DBG_LIB, "creating overlay directory for guest '%s' failed: %m",
                      guest->get_name(guest));
                 goto error;
             }
         }
         if (!guest->add_overlay(guest, guest_dir))
         {
             goto error;
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 error:
     enumerator->destroy(enumerator);
     this->public.del_overlay(&this->public, dir);
     return FALSE;
 }
METHOD (dumm_t , del_overlay , bool , private_dumm_t * this, char * dir)
Definition at line 172 of file dumm.c.
References guest_t::del_overlay, enumerator_t::destroy, enumerator_t::enumerate, FALSE, guest_t::get_name, len, and snprintf.
 {
     bool ret = FALSE;
     enumerator_t *enumerator;
     guest_t *guest;
     enumerator = this->guests->create_enumerator(this->guests);
     while (enumerator->enumerate(enumerator, (void**)&guest))
     {
         char guest_dir[PATH_MAX];
         int len = snprintf(guest_dir, sizeof(guest_dir), "%s/%s", dir,
                            guest->get_name(guest));
         if (len < 0 || len >= sizeof(guest_dir))
         {
             continue;
         }
         ret = guest->del_overlay(guest, guest_dir) || ret;
     }
     enumerator->destroy(enumerator);
     return ret;
 }
METHOD (dumm_t , pop_overlay , bool , private_dumm_t * this)
Definition at line 195 of file dumm.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, and guest_t::pop_overlay.
 {
     bool ret = FALSE;
     enumerator_t *enumerator;
     guest_t *guest;
     enumerator = this->guests->create_enumerator(this->guests);
     while (enumerator->enumerate(enumerator, (void**)&guest))
     {
         ret = guest->pop_overlay(guest) || ret;
     }
     enumerator->destroy(enumerator);
     return ret;
 }
METHOD (dumm_t , load_template , bool , private_dumm_t * this, char * name)
Definition at line 224 of file dumm.c.
References asprintf(), clear_template(), DBG1, DBG_LIB, FALSE, mkdir_p(), PERME, TEMPLATE_DIR, and TRUE.
 {
     clear_template(this);
     if (name == NULL)
     {
         return TRUE;
     }
     if (strlen(name) > PATH_MAX)
     {
         DBG1(DBG_LIB, "template name '%s' is too long", name);
         return FALSE;
     }
     if (strchr(name, '/') != NULL)
     {
         DBG1(DBG_LIB, "template name '%s' must not contain '/' characters", name);
         return FALSE;
     }
     if (asprintf(&this->template, "%s/%s", TEMPLATE_DIR, name) < 0)
     {
         this->template = NULL;
         return FALSE;
     }
     if (access(this->template, F_OK) != 0)
     {
         if (!mkdir_p(this->template, PERME))
         {
             DBG1(DBG_LIB, "creating template directory '%s' failed: %m",
                  this->template);
             return FALSE;
         }
     }
     return add_overlay(this, this->template);
 }
METHOD (enumerator_t , template_enumerate , bool , template_enumerator_t * this, char ** template)
Definition at line 269 of file dumm.c.
References FALSE, rel(), and TRUE.
 {
     struct stat st;
     char *rel;
     while (this->inner->enumerate(this->inner, &rel, NULL, &st))
     {
         if (S_ISDIR(st.st_mode) && *rel != '.')
         {
             *template = rel;
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (enumerator_t , template_enumerator_destroy , void , template_enumerator_t * this)
Definition at line 286 of file dumm.c.
References free().
 {
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (dumm_t , create_template_enumerator , enumerator_t * , private_dumm_t * this)
Definition at line 293 of file dumm.c.
References destroy(), enumerator_create_directory(), enumerator_create_empty(), free(), INIT, template_enumerator_t::inner, template_enumerator_t::public, and TEMPLATE_DIR.
 {
     template_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_template_enumerate,
             .destroy = (void*)_template_enumerator_destroy,
         },
         .inner = enumerator_create_directory(TEMPLATE_DIR),
     );
     if (!enumerator->inner)
     {
         free(enumerator);
         return enumerator_create_empty();
     }
     return &enumerator->public;
 }
METHOD (dumm_t , destroy , void , private_dumm_t * this)
Definition at line 312 of file dumm.c.
References enumerator_t::destroy, guest_t::destroy, destroy(), dir, enumerator_t::enumerate, free(), guest_t::stop, and SUCCESS.
 {
     enumerator_t *enumerator;
     guest_t *guest;
     this->bridges->destroy_offset(this->bridges, offsetof(bridge_t, destroy));
     enumerator = this->guests->create_enumerator(this->guests);
     while (enumerator->enumerate(enumerator, (void**)&guest))
     {
         guest->stop(guest, NULL);
     }
     enumerator->destroy(enumerator);
     while (this->guests->remove_last(this->guests, (void**)&guest) == SUCCESS)
     {
         guest->destroy(guest);
     }
     this->guests->destroy(this->guests);
     free(this->guest_dir);
     free(this->template);
     free(this->dir);
     free(this);
 }