strongSwan: swid_tag_id.c File Reference
swid_tag_id.c File Reference
#include "swid_tag_id.h"
Classes
struct private_swid_tag_id_t
Typedefs
typedef struct
private_swid_tag_id_t private_swid_tag_id_t
Functions
METHOD (swid_tag_id_t, get_tag_creator, chunk_t, private_swid_tag_id_t *this)
METHOD (swid_tag_id_t, get_unique_sw_id, chunk_t, private_swid_tag_id_t *this, chunk_t *instance_id)
METHOD (swid_tag_id_t, get_ref, swid_tag_id_t *, private_swid_tag_id_t *this)
METHOD (swid_tag_id_t, destroy, void, private_swid_tag_id_t *this)
swid_tag_id_t * swid_tag_id_create (chunk_t tag_creator, chunk_t unique_sw_id, chunk_t instance_id)
Typedef Documentation
typedef struct private_swid_tag_id_t private_swid_tag_id_t
Definition at line 18 of file swid_tag_id.c.
Function Documentation
METHOD (swid_tag_id_t , get_tag_creator , chunk_t , private_swid_tag_id_t * this)
Definition at line 52 of file swid_tag_id.c.
 {
     return this->tag_creator;
 }
METHOD (swid_tag_id_t , get_unique_sw_id , chunk_t , private_swid_tag_id_t * this, chunk_t * instance_id)
Definition at line 58 of file swid_tag_id.c.
 {
     if (instance_id)
     {
         *instance_id = this->instance_id;
     }
     return this->unique_sw_id;
 }
METHOD (swid_tag_id_t , get_ref , swid_tag_id_t * , private_swid_tag_id_t * this)
Definition at line 68 of file swid_tag_id.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (swid_tag_id_t , destroy , void , private_swid_tag_id_t * this)
Definition at line 75 of file swid_tag_id.c.
References free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         free(this->tag_creator.ptr);
         free(this->unique_sw_id.ptr);
         free(this->instance_id.ptr);
         free(this);
     }
 }