strongSwan: test_runner.c File Reference
test_runner.c File Reference
#include "test_runner.h"
#include <library.h>
#include <threading/thread.h>
#include <plugins/plugin_feature.h>
#include <collections/array.h>
#include <utils/test.h>
#include <stdlib.h>
#include <dirent.h>
#include <unistd.h>
#include <limits.h>
Classes
struct failure_t
struct report_data_t
Macros
#define TTY(color) tty_escape_get(2, TTY_FG_##color)
Functions
static void destroy_suite (test_suite_t *suite)
static void apply_filter (array_t *loaded, char *filter, bool exclude)
static void filter_suites (array_t *loaded)
static array_t * load_suites (test_configuration_t configs[], test_runner_init_t init, char *cfg)
static void unload_suites (array_t *suites)
static bool run_test (test_function_t *tfun, int i)
static bool call_fixture (test_case_t *tcase, bool up)
static bool pre_test (test_runner_init_t init, char *cfg)
static void report_leaks (report_data_t *data, int count, size_t bytes, backtrace_t *bt, bool detailed)
static void sum_leaks (report_data_t *data, int count, size_t bytes, int whitelisted)
static bool post_test (test_runner_init_t init, bool check_leaks, array_t *failures, char *name, int i, int *leaks)
static void collect_failure_info (array_t *failures, char *name, int i)
static void print_failures (array_t *failures)
static bool run_case (test_case_t *tcase, test_runner_init_t init, char *cfg)
static bool run_suite (test_suite_t *suite, test_runner_init_t init, char *cfg)
int test_runner_run (const char *name, test_configuration_t configs[], test_runner_init_t init)
Variables
bool test_runner_available = TRUE
Macro Definition Documentation
#define TTY (color) tty_escape_get(2, TTY_FG_##color)
Get a tty color escape character for stderr
Definition at line 35 of file test_runner.c.
Referenced by print_failures(), run_case(), run_suite(), and test_runner_run().
Function Documentation
static void apply_filter (array_t * loaded, char * filter, bool exclude) static
Filter loaded test suites, either remove suites listed (exclude=TRUE), or all that are not listed (exclude=FALSE).
Definition at line 64 of file test_runner.c.
References array_create_enumerator(), array_remove_at(), enumerator_t::destroy, hashtable_t::destroy, destroy_suite(), enumerator_t::enumerate, enumerator_create_token(), hashtable_t::get, hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), name, test_suite_t::name, and hashtable_t::put.
Referenced by filter_suites().
 {
     enumerator_t *enumerator, *names;
     hashtable_t *listed;
     test_suite_t *suite;
     char *name;
     listed = hashtable_create(hashtable_hash_str, hashtable_equals_str, 8);
     names = enumerator_create_token(filter, ",", " ");
     while (names->enumerate(names, &name))
     {
         listed->put(listed, name, name);
     }
     enumerator = array_create_enumerator(loaded);
     while (enumerator->enumerate(enumerator, &suite))
     {
         if ((exclude && listed->get(listed, suite->name)) ||
             (!exclude && !listed->get(listed, suite->name)))
         {
             array_remove_at(loaded, enumerator);
             destroy_suite(suite);
         }
     }
     enumerator->destroy(enumerator);
     listed->destroy(listed);
     names->destroy(names);
 }
static bool call_fixture (test_case_t * tcase, bool up) static
Invoke fixture setup/teardown
Definition at line 195 of file test_runner.c.
References array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, test_case_t::fixtures, test_fixture_t::setup, test_fixture_t::teardown, test_restore_point, thread_cleanup_popall(), and TRUE.
Referenced by run_case().
 {
     enumerator_t *enumerator;
     test_fixture_t *fixture;
     bool failure = FALSE;
     enumerator = array_create_enumerator(tcase->fixtures);
     while (enumerator->enumerate(enumerator, &fixture))
     {
         if (test_restore_point())
         {
             if (up)
             {
                 if (fixture->setup)
                 {
                     fixture->setup();
                 }
             }
             else
             {
                 if (fixture->teardown)
                 {
                     fixture->teardown();
                 }
             }
         }
         else
         {
             thread_cleanup_popall();
             failure = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return !failure;
 }
static void collect_failure_info (array_t * failures, char * name, int i) static
Collect failure information, add failure_t to array
Definition at line 352 of file test_runner.c.
References array_insert(), failure_t::file, failure_t::line, failure_t::msg, name, failure_t::name, test_failure_backtrace(), and test_failure_get().
Referenced by run_case().
 {
     failure_t failure = {
         .name = name,
         .i = i,
         .bt = test_failure_backtrace(),
     };
     failure.line = test_failure_get(failure.msg, sizeof(failure.msg),
                                     &failure.file);
     array_insert(failures, -1, &failure);
 }
static void destroy_suite (test_suite_t * suite) static
Destroy a single test suite and associated data
Definition at line 48 of file test_runner.c.
References array_destroy(), array_remove(), test_case_t::fixtures, free(), test_case_t::functions, and test_suite_t::tcases.
Referenced by apply_filter(), and unload_suites().
 {
     test_case_t *tcase;
     while (array_remove(suite->tcases, 0, &tcase))
     {
         array_destroy(tcase->functions);
         array_destroy(tcase->fixtures);
     }
     free(suite);
 }
static void filter_suites (array_t * loaded) static
Removes and destroys test suites that are not selected or explicitly excluded.
Definition at line 96 of file test_runner.c.
References apply_filter(), FALSE, filter(), and TRUE.
Referenced by load_suites().
 {
     char *filter;
     filter = getenv("TESTS_SUITES");
     if (filter)
     {
         apply_filter(loaded, filter, FALSE);
     }
     filter = getenv("TESTS_SUITES_EXCLUDE");
     if (filter)
     {
         apply_filter(loaded, filter, TRUE);
     }
 }
static array_t* load_suites (test_configuration_t configs[], test_runner_init_t init, char * cfg) static
Load all available test suites, or optionally only selected ones.
Definition at line 115 of file test_runner.c.
References array_create(), array_insert(), FALSE, test_configuration_t::feature, filter_suites(), plugin_loader_t::has_feature, init(), library_t::leak_detective, LEVEL_CTRL, lib, library_deinit(), library_init(), library_t::plugins, leak_detective_t::set_state, plugin_loader_t::status, test_configuration_t::suite, test_setup_handler(), and TRUE.
Referenced by test_runner_run().
 {
     array_t *suites;
     bool old = FALSE;
     int i;
     library_init(cfg, "test-runner");
     test_setup_handler();
     if (init && !init(TRUE))
     {
         library_deinit();
         return NULL;
     }
     lib->plugins->status(lib->plugins, LEVEL_CTRL);
     if (lib->leak_detective)
     {
         old = lib->leak_detective->set_state(lib->leak_detective, FALSE);
     }
     suites = array_create(0, 0);
     for (i = 0; configs[i].suite; i++)
     {
         if (configs[i].feature.type == 0 ||
             lib->plugins->has_feature(lib->plugins, configs[i].feature))
         {
             array_insert(suites, -1, configs[i].suite());
         }
     }
     filter_suites(suites);
     if (lib->leak_detective)
     {
         lib->leak_detective->set_state(lib->leak_detective, old);
     }
     if (init)
     {
         init(FALSE);
     }
     library_deinit();
     return suites;
 }
static bool post_test (test_runner_init_t init, bool check_leaks, array_t * failures, char * name, int i, int * leaks) static
Do library cleanup and optionally check for memory leaks
Definition at line 315 of file test_runner.c.
References data, FALSE, init(), library_t::leak_detective, report_data_t::leaks, lib, library_deinit(), name, report_leaks(), leak_detective_t::set_report_cb, sum_leaks(), test_restore_point, thread_cleanup_popall(), and TRUE.
Referenced by run_case().
 {
     report_data_t data = {
         .failures = failures,
         .name = name,
         .i = i,
     };
     if (init)
     {
         if (test_restore_point())
         {
             init(FALSE);
         }
         else
         {
             thread_cleanup_popall();
             library_deinit();
             return FALSE;
         }
     }
     if (check_leaks && lib->leak_detective)
     {
         lib->leak_detective->set_report_cb(lib->leak_detective,
                                 (leak_detective_report_cb_t)report_leaks,
                                 (leak_detective_summary_cb_t)sum_leaks, &data);
     }
     library_deinit();
     *leaks = data.leaks;
     return TRUE;
 }
static bool pre_test (test_runner_init_t init, char * cfg) static
Test initialization, initializes libstrongswan for the next run
Definition at line 236 of file test_runner.c.
References FALSE, settings_t::get_str, init(), library_t::leak_detective, lib, library_deinit(), library_init(), settings_t::set_default_str, leak_detective_t::set_report_cb, library_t::settings, and TRUE.
Referenced by run_case().
 {
     library_init(cfg, "test-runner");
     /* use non-blocking RNG to generate keys fast */
     lib->settings->set_default_str(lib->settings,
             "libstrongswan.plugins.random.random",
             lib->settings->get_str(lib->settings,
                 "libstrongswan.plugins.random.urandom", "/dev/urandom"));
     /* same for the gcrypt plugin */
     lib->settings->set_default_str(lib->settings,
             "libstrongswan.plugins.gcrypt.quick_random", "yes");
     if (lib->leak_detective)
     {
         /* disable leak reports during testing */
         lib->leak_detective->set_report_cb(lib->leak_detective,
                                            NULL, NULL, NULL);
     }
     if (init && !init(TRUE))
     {
         library_deinit();
         return FALSE;
     }
     return TRUE;
 }
static void print_failures (array_t * failures) static
Print array of collected failure_t to stderr
Definition at line 369 of file test_runner.c.
References array_remove(), backtrace_deinit(), backtrace_init(), failure_t::bt, backtrace_t::destroy, failure_t::file, fprintf, failure_t::i, failure_t::line, backtrace_t::log, failure_t::msg, failure_t::name, threads_deinit(), threads_init(), TRUE, and TTY.
Referenced by run_case().
 {
     failure_t failure;
     threads_init();
     backtrace_init();
     while (array_remove(failures, 0, &failure))
     {
         fprintf(stderr, "      %sFailure in '%s': %s (",
                 TTY(RED), failure.name, failure.msg);
         if (failure.line)
         {
             fprintf(stderr, "%s:%d, ", failure.file, failure.line);
         }
         fprintf(stderr, "i = %d)%s\n", failure.i, TTY(DEF));
         if (failure.bt)
         {
             failure.bt->log(failure.bt, stderr, TRUE);
             failure.bt->destroy(failure.bt);
         }
     }
     backtrace_deinit();
     threads_deinit();
 }
static void report_leaks (report_data_t * data, int count, size_t bytes, backtrace_t * bt, bool detailed) static
Leak report callback, build failures from leaks
Definition at line 288 of file test_runner.c.
References array_insert(), backtrace_t::clone, report_data_t::failures, report_data_t::i, failure_t::msg, failure_t::name, report_data_t::name, and snprintf.
Referenced by library_init(), and post_test().
 {
     failure_t failure = {
         .name = data->name,
         .i = data->i,
         .bt = bt->clone(bt),
     };
     snprintf(failure.msg, sizeof(failure.msg),
              "Leak detected: %d allocations using %zu bytes", count, bytes);
     array_insert(data->failures, -1, &failure);
 }
static bool run_case (test_case_t * tcase, test_runner_init_t init, char * cfg) static
Run a single test case with fixtures
Definition at line 399 of file test_runner.c.
References array_count(), array_create(), array_create_enumerator(), array_destroy(), call_fixture(), collect_failure_info(), enumerator_t::destroy, end, test_function_t::end, enumerator_t::enumerate, FALSE, fprintf, test_case_t::functions, test_case_t::name, test_function_t::name, ok, post_test(), pre_test(), print_failures(), run_test(), test_function_t::start, test_setup_timeout(), test_case_t::timeout, TRUE, and TTY.
Referenced by run_suite().
 {
     enumerator_t *enumerator;
     test_function_t *tfun;
     int passed = 0;
     array_t *failures;
     failures = array_create(sizeof(failure_t), 0);
     fprintf(stderr, "    Running case '%s': ", tcase->name);
     fflush(stderr);
     enumerator = array_create_enumerator(tcase->functions);
     while (enumerator->enumerate(enumerator, &tfun))
     {
         int i, rounds = 0;
         for (i = tfun->start; i < tfun->end; i++)
         {
             if (pre_test(init, cfg))
             {
                 bool ok = FALSE;
                 int leaks = 0;
                 test_setup_timeout(tcase->timeout);
                 if (call_fixture(tcase, TRUE))
                 {
                     if (run_test(tfun, i))
                     {
                         if (call_fixture(tcase, FALSE))
{
                             ok = TRUE;
                         }
                     }
                     else
                     {
                         call_fixture(tcase, FALSE);
                     }
                 }
                 if (!post_test(init, ok, failures, tfun->name, i, &leaks))
                 {
                     ok = FALSE;
                 }
                 test_setup_timeout(0);
                 if (ok)
                 {
                     if (!leaks)
                     {
                         rounds++;
                         fprintf(stderr, "%s+%s", TTY(GREEN), TTY(DEF));
                     }
                 }
                 else
                 {
                     collect_failure_info(failures, tfun->name, i);
                 }
                 if (!ok || leaks)
                 {
                     fprintf(stderr, "%s-%s", TTY(RED), TTY(DEF));
                 }
             }
             else
             {
                 fprintf(stderr, "!");
             }
         }
         fflush(stderr);
         if (rounds == tfun->end - tfun->start)
         {
             passed++;
         }
     }
     enumerator->destroy(enumerator);
     fprintf(stderr, "\n");
     print_failures(failures);
     array_destroy(failures);
     return passed == array_count(tcase->functions);
 }
static bool run_suite (test_suite_t * suite, test_runner_init_t init, char * cfg) static
Run a single test suite
Definition at line 487 of file test_runner.c.
References array_count(), array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, fprintf, test_suite_t::name, run_case(), test_suite_t::tcases, TRUE, and TTY.
Referenced by test_runner_run().
 {
     enumerator_t *enumerator;
     test_case_t *tcase;
     int passed = 0;
     fprintf(stderr, "  Running suite '%s':\n", suite->name);
     enumerator = array_create_enumerator(suite->tcases);
     while (enumerator->enumerate(enumerator, &tcase))
     {
         if (run_case(tcase, init, cfg))
         {
             passed++;
         }
     }
     enumerator->destroy(enumerator);
     if (passed == array_count(suite->tcases))
     {
         fprintf(stderr, "  %sPassed all %u '%s' test cases%s\n",
                 TTY(GREEN), array_count(suite->tcases), suite->name, TTY(DEF));
         return TRUE;
     }
     fprintf(stderr, "  %sPassed %u/%u '%s' test cases%s\n",
             TTY(RED), passed, array_count(suite->tcases), suite->name, TTY(DEF));
     return FALSE;
 }
static bool run_test (test_function_t * tfun, int i) static
Run a single test function, return FALSE on failure
Definition at line 181 of file test_runner.c.
References test_function_t::cb, FALSE, test_restore_point, thread_cleanup_popall(), and TRUE.
Referenced by run_case().
 {
     if (test_restore_point())
     {
         tfun->cb(i);
         return TRUE;
     }
     thread_cleanup_popall();
     return FALSE;
 }
static void sum_leaks (report_data_t * data, int count, size_t bytes, int whitelisted) static
Leak summary callback, check if any leaks found
Definition at line 306 of file test_runner.c.
References count, and report_data_t::leaks.
Referenced by library_init(), and post_test().
 {
     data->leaks = count;
 }
static void unload_suites (array_t * suites) static
Unload and destroy test suites and associated data
Definition at line 167 of file test_runner.c.
References array_destroy(), array_remove(), and destroy_suite().
Referenced by test_runner_run().
 {
     test_suite_t *suite;
     while (array_remove(suites, 0, &suite))
     {
         destroy_suite(suite);
     }
     array_destroy(suites);
 }
Variable Documentation
bool test_runner_available = TRUE
A global symbol indicating libtest linkage
Definition at line 43 of file test_runner.c.
Referenced by has_libtest_linkage().