strongSwan: pts_file_meas.c File Reference
pts_file_meas.c File Reference
#include "pts_file_meas.h"
#include <collections/linked_list.h>
#include <utils/debug.h>
#include <sys/stat.h>
#include <libgen.h>
#include <errno.h>
Classes
struct private_pts_file_meas_t
struct entry_t
Typedefs
typedef struct
private_pts_file_meas_t private_pts_file_meas_t
typedef struct entry_t entry_t
Functions
static void free_entry (entry_t *entry)
METHOD (pts_file_meas_t, get_request_id, u_int16_t, private_pts_file_meas_t *this)
METHOD (pts_file_meas_t, get_file_count, int, private_pts_file_meas_t *this)
METHOD (pts_file_meas_t, add, void, private_pts_file_meas_t *this, char *filename, chunk_t measurement)
static bool entry_filter (void *null, entry_t **entry, char **filename, void *i2, chunk_t *measurement)
METHOD (pts_file_meas_t, create_enumerator, enumerator_t *, private_pts_file_meas_t *this)
METHOD (pts_file_meas_t, check, bool, private_pts_file_meas_t *this, pts_database_t *pts_db, int pid, pts_meas_algorithms_t algo)
METHOD (pts_file_meas_t, verify, bool, private_pts_file_meas_t *this, enumerator_t *e_hash, bool is_dir)
METHOD (pts_file_meas_t, destroy, void, private_pts_file_meas_t *this)
pts_file_meas_t * pts_file_meas_create (u_int16_t request_id)
static bool hash_file (hasher_t *hasher, char *pathname, u_char *hash)
pts_file_meas_t * pts_file_meas_create_from_path (u_int16_t request_id, char *pathname, bool is_dir, bool use_rel_name, pts_meas_algorithms_t alg)
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 50 of file pts_file_meas.c.
typedef struct private_pts_file_meas_t private_pts_file_meas_t
Definition at line 26 of file pts_file_meas.c.
Function Documentation
static bool entry_filter (void * null, entry_t ** entry, char ** filename, void * i2, chunk_t * measurement) static
Enumerate file measurement entries
Definition at line 100 of file pts_file_meas.c.
References TRUE.
Referenced by METHOD().
 {
     *filename = (*entry)->filename;
     *measurement = (*entry)->measurement;
     return TRUE;
 }
static void free_entry (entry_t * entry) static
Free an entry_t object
Definition at line 63 of file pts_file_meas.c.
References entry_t::filename, free(), entry_t::measurement, and chunk_t::ptr.
Referenced by METHOD().
 {
     if (entry)
     {
         free(entry->filename);
         free(entry->measurement.ptr);
         free(entry);
     }
 }
static bool hash_file (hasher_t * hasher, char * pathname, u_char * hash) static
Hash a file with a given absolute pathname
Definition at line 293 of file pts_file_meas.c.
References chunk_create(), chunk_empty, DBG1, DBG_PTS, FALSE, hasher_t::get_hash, strerror, and TRUE.
Referenced by pts_file_meas_create_from_path().
 {
     u_char buffer[4096];
     size_t bytes_read;
     bool success = TRUE;
     FILE *file;
     file = fopen(pathname, "rb");
     if (!file)
     {
         DBG1(DBG_PTS,"  file '%s' can not be opened, %s", pathname,
              strerror(errno));
         return FALSE;
     }
     while (TRUE)
     {
         bytes_read = fread(buffer, 1, sizeof(buffer), file);
         if (bytes_read > 0)
         {
             if (!hasher->get_hash(hasher, chunk_create(buffer, bytes_read), NULL))
             {
                 DBG1(DBG_PTS, "  hasher increment error");
                 success = FALSE;
                 break;
             }
         }
         else
         {
             if (!hasher->get_hash(hasher, chunk_empty, hash))
             {
                 DBG1(DBG_PTS, "  hasher finalize error");
                 success = FALSE;
             }
             break;
         }
     }
     fclose(file);
     return success;
 }
METHOD (pts_file_meas_t , get_request_id , u_int16_t , private_pts_file_meas_t * this)
Definition at line 73 of file pts_file_meas.c.
 {
     return this->request_id;
 }
METHOD (pts_file_meas_t , get_file_count , int , private_pts_file_meas_t * this)
Definition at line 79 of file pts_file_meas.c.
References linked_list_t::get_count, and list.
 {
     return this->list->get_count(this->list);
 }
METHOD (pts_file_meas_t , add , void , private_pts_file_meas_t * this, char * filename, chunk_t measurement)
Definition at line 85 of file pts_file_meas.c.
References chunk_clone, entry_t::filename, linked_list_t::insert_last, list, malloc_thing, entry_t::measurement, and strdup.
 {
     entry_t *entry;
     entry = malloc_thing(entry_t);
     entry->filename = strdup(filename);
     entry->measurement = chunk_clone(measurement);
     this->list->insert_last(this->list, entry);
 }
METHOD (pts_file_meas_t , create_enumerator , enumerator_t * , private_pts_file_meas_t * this)
Definition at line 108 of file pts_file_meas.c.
References linked_list_t::create_enumerator, entry_filter(), enumerator_create_filter(), and list.
 {
     return enumerator_create_filter(this->list->create_enumerator(this->list),
                                    (void*)entry_filter, NULL, NULL);
 }
METHOD (pts_file_meas_t , check , bool , private_pts_file_meas_t * this, pts_database_t * pts_db, int pid, pts_meas_algorithms_t algo)
Definition at line 115 of file pts_file_meas.c.
References chunk_equals_const(), linked_list_t::create_enumerator, pts_database_t::create_file_meas_enumerator, DBG1, DBG2, DBG3, DBG_PTS, enumerator_t::destroy, enumerator_t::enumerate, FAILED, entry_t::filename, linked_list_t::get_count, hash, list, entry_t::measurement, NOT_FOUND, status, SUCCESS, TRUE, and VERIFY_ERROR.
 {
     enumerator_t *enumerator, *e;
     entry_t *entry;
     chunk_t hash;
     int count_ok = 0, count_not_found = 0, count_differ = 0;
     status_t status;
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         status = NOT_FOUND;
         e = pts_db->create_file_meas_enumerator(pts_db, pid, algo,
                                                 entry->filename);
         if (e)
         {
             while (e->enumerate(e, &hash))
             {
                 if (chunk_equals_const(entry->measurement, hash))
                 {
                     status = SUCCESS;
                     break;
                 }
                 else
                 {
                     status = VERIFY_ERROR;
                 }
             }
             e->destroy(e);
         }
         else
         {
             status = FAILED;
         }
         switch (status)
         {
             case SUCCESS:
                 DBG3(DBG_PTS, "  %#B for '%s' is ok", &entry->measurement,
                                                        entry->filename);
                 count_ok++;
                 break;
             case NOT_FOUND:
                 DBG2(DBG_PTS, "  %#B for '%s' not found", &entry->measurement,
                                                            entry->filename);
                 count_not_found++;
                 break;
             case VERIFY_ERROR:
                 DBG1(DBG_PTS, "  %#B for '%s' differs", &entry->measurement,
                                                          entry->filename);
                 count_differ++;
                 break;
             case FAILED:
             default:
                 DBG1(DBG_PTS, "  %#B for '%s' failed", &entry->measurement,
                                                         entry->filename);
         }
     }
     enumerator->destroy(enumerator);
     DBG1(DBG_PTS, "%d measurements, %d ok, %d not found, %d differ",
          this->list->get_count(this->list),
          count_ok, count_not_found, count_differ);
     return TRUE;
 }
METHOD (pts_file_meas_t , verify , bool , private_pts_file_meas_t * this, enumerator_t * e_hash, bool is_dir)
check if we find an entry for this filename in the PTS measurement list
Definition at line 184 of file pts_file_meas.c.
References chunk_equals_const(), linked_list_t::create_enumerator, DBG1, DBG2, DBG_PTS, enumerator_t::destroy, enumerator_t::enumerate, FALSE, entry_t::filename, found, list, match(), entry_t::measurement, streq(), and TRUE.
 {
     int fid, fid_last = 0;
     char *filename;
     chunk_t measurement;
     entry_t *entry;
     enumerator_t *enumerator = NULL;
     bool found = FALSE, match = FALSE, success = TRUE;
     while (e_hash->enumerate(e_hash, &fid, &filename, &measurement))
     {
         if (fid != fid_last)
         {
             if (found && !match)
             {
                 /* no matching hash value found for last filename */
                 success = FALSE;
                 DBG1(DBG_PTS, "  %#B for '%s' is incorrect",
                      &entry->measurement, entry->filename);
                 enumerator->destroy(enumerator);
             }
             /* get a new filename from the database */
             found = FALSE;
             match = FALSE;
             fid_last = fid;
             enumerator = this->list->create_enumerator(this->list);
             while (enumerator->enumerate(enumerator, &entry))
             {
                 if (!is_dir || streq(filename, entry->filename))
                 {
                     found = TRUE;
                     break;
                 }
             }
             /* no PTS measurement returned for this filename */
             if (!found)
             {
                 success = FALSE;
                 DBG1(DBG_PTS, "  no measurement found for '%s'", filename);
                 enumerator->destroy(enumerator);
             }
         }
         if (found && !match)
         {
             if (chunk_equals_const(measurement, entry->measurement))
             {
                 match = TRUE;
                 DBG2(DBG_PTS, "  %#B for '%s' is ok",
                      &entry->measurement, entry->filename);
                 enumerator->destroy(enumerator);
             }
         }
     }
     if (found && !match)
     {
         /* no matching hash value found for the very last filename */
         success = FALSE;
         DBG1(DBG_PTS, "  %#B for '%s' is incorrect",
              &entry->measurement, entry->filename);
             enumerator->destroy(enumerator);
     }
     return success;
 }
METHOD (pts_file_meas_t , destroy , void , private_pts_file_meas_t * this)
Definition at line 259 of file pts_file_meas.c.
References linked_list_t::destroy_function, free(), free_entry(), and list.
 {
     this->list->destroy_function(this->list, (void *)free_entry);
     free(this);
 }