strongSwan: kernel_interface_t Struct Reference
kernel_interface_t Struct Reference
kernel_interface
#include "kernel_interface.h"
Public Attributes
kernel_feature_t(* get_features)(kernel_interface_t *this)
status_t(* get_spi)(kernel_interface_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
status_t(* get_cpi)(kernel_interface_t *this, host_t *src, host_t *dst, u_int16_t *cpi)
status_t(* alloc_reqid)(kernel_interface_t *this, linked_list_t *local_ts, linked_list_t *remote_ts, mark_t mark_in, mark_t mark_out, u_int32_t *reqid)
status_t(* release_reqid)(kernel_interface_t *this, u_int32_t reqid, mark_t mark_in, mark_t mark_out)
status_t(* add_sa)(kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t *src_ts, linked_list_t *dst_ts)
status_t(* update_sa)(kernel_interface_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
status_t(* query_sa)(kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
status_t(* del_sa)(kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
status_t(* flush_sas)(kernel_interface_t *this)
status_t(* add_policy)(kernel_interface_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
status_t(* query_policy)(kernel_interface_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, mark_t mark, time_t *use_time)
status_t(* del_policy)(kernel_interface_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
status_t(* flush_policies)(kernel_interface_t *this)
host_t *(* get_source_addr)(kernel_interface_t *this, host_t *dest, host_t *src)
host_t *(* get_nexthop)(kernel_interface_t *this, host_t *dest, int prefix, host_t *src)
bool(* get_interface)(kernel_interface_t *this, host_t *host, char **name)
enumerator_t *(* create_address_enumerator)(kernel_interface_t *this, kernel_address_type_t which)
status_t(* add_ip)(kernel_interface_t *this, host_t *virtual_ip, int prefix, char *iface)
status_t(* del_ip)(kernel_interface_t *this, host_t *virtual_ip, int prefix, bool wait)
status_t(* add_route)(kernel_interface_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
status_t(* del_route)(kernel_interface_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
bool(* bypass_socket)(kernel_interface_t *this, int fd, int family)
bool(* enable_udp_decap)(kernel_interface_t *this, int fd, int family, u_int16_t port)
bool(* is_interface_usable)(kernel_interface_t *this, const char *iface)
bool(* all_interfaces_usable)(kernel_interface_t *this)
status_t(* get_address_by_ts)(kernel_interface_t *this, traffic_selector_t *ts, host_t **ip, bool *vip)
bool(* add_ipsec_interface)(kernel_interface_t *this, kernel_ipsec_constructor_t create)
bool(* remove_ipsec_interface)(kernel_interface_t *this, kernel_ipsec_constructor_t create)
bool(* add_net_interface)(kernel_interface_t *this, kernel_net_constructor_t create)
bool(* remove_net_interface)(kernel_interface_t *this, kernel_net_constructor_t create)
void(* add_listener)(kernel_interface_t *this, kernel_listener_t *listener)
void(* remove_listener)(kernel_interface_t *this, kernel_listener_t *listener)
void(* acquire)(kernel_interface_t *this, u_int32_t reqid, traffic_selector_t *src_ts, traffic_selector_t *dst_ts)
void(* expire)(kernel_interface_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, bool hard)
void(* mapping)(kernel_interface_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, host_t *remote)
void(* migrate)(kernel_interface_t *this, u_int32_t reqid, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, host_t *local, host_t *remote)
void(* roam)(kernel_interface_t *this, bool address)
void(* tun)(kernel_interface_t *this, tun_device_t *tun, bool created)
void(* register_algorithm)(kernel_interface_t *this, u_int16_t alg_id, transform_type_t type, u_int16_t kernel_id, char *kernel_name)
bool(* lookup_algorithm)(kernel_interface_t *this, u_int16_t alg_id, transform_type_t type, u_int16_t *kernel_id, char **kernel_name)
void(* destroy)(kernel_interface_t *this)
Detailed Description
Manager and wrapper for different kernel interfaces.
The kernel interface handles the communication with the kernel for SA and policy management and interface and IP address management.
Definition at line 92 of file kernel_interface.h.
Member Data Documentation
void(* kernel_interface_t::acquire)(kernel_interface_t *this, u_int32_t reqid, traffic_selector_t *src_ts, traffic_selector_t *dst_ts)
Raise an acquire event.
Parameters
reqid reqid of the policy to acquire
src_ts source traffic selector
dst_ts destination traffic selector
Definition at line 564 of file kernel_interface.h.
Referenced by acquire(), charon_esa_acquire(), and process_acquire().
status_t(* kernel_interface_t::add_ip)(kernel_interface_t *this, host_t *virtual_ip, int prefix, char *iface)
Add a virtual IP to an interface.
Virtual IPs are attached to an interface. If an IP is added multiple times, the IP is refcounted and not removed until del_ip() was called as many times as add_ip().
Parameters
virtual_ip virtual ip address to assign
prefix prefix length to install IP with, -1 for auto
iface interface to install virtual IP on
Returns
SUCCESS if operation completed
Definition at line 401 of file kernel_interface.h.
Referenced by allocate_addr(), METHOD(), and reinstall_vip().
bool(* kernel_interface_t::add_ipsec_interface)(kernel_interface_t *this, kernel_ipsec_constructor_t create)
Register an ipsec kernel interface constructor on the manager.
Parameters
create constructor to register
Returns
TRUE if the ipsec kernel interface was registered successfully, FALSE if an interface was already registered or the registration failed
Definition at line 507 of file kernel_interface.h.
Referenced by kernel_ipsec_register(), and load_tester_plugin_create().
void(* kernel_interface_t::add_listener)(kernel_interface_t *this, kernel_listener_t *listener)
Add a listener to the kernel interface.
Parameters
listener listener to add
Definition at line 546 of file kernel_interface.h.
Referenced by forecast_forwarder_create(), kernel_handler_create(), and kernel_libipsec_router_create().
bool(* kernel_interface_t::add_net_interface)(kernel_interface_t *this, kernel_net_constructor_t create)
Register a network kernel interface constructor on the manager.
Parameters
create constructor to register
Returns
TRUE if the kernel net interface was registered successfully, FALSE if an interface was already registered or the registration failed
Definition at line 528 of file kernel_interface.h.
Referenced by kernel_net_register().
status_t(* kernel_interface_t::add_policy)(kernel_interface_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
Add a policy to the SPD.
Parameters
src source address of SA
dst dest address of SA
src_ts traffic selector to match traffic source
dst_ts traffic selector to match traffic dest
direction direction of traffic, POLICY_(IN|OUT|FWD)
type type of policy, POLICY_(IPSEC|PASS|DROP)
sa details about the SA(s) tied to this policy
mark mark for this policy
priority priority of this policy
Returns
SUCCESS if operation completed
Definition at line 279 of file kernel_interface.h.
Referenced by install_policies_internal(), and install_shunt_policy().
status_t(* kernel_interface_t::add_route)(kernel_interface_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
Add a route.
Parameters
dst_net destination net
prefixlen destination net prefix length
gateway gateway for this route
src_ip source ip of the route
if_name name of the interface the route is bound to
Returns
SUCCESS if operation completed ALREADY_DONE if the route already exists
Definition at line 428 of file kernel_interface.h.
Referenced by add_exclude_route(), add_policy_internal(), and install_route().
status_t(* kernel_interface_t::add_sa)(kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t *src_ts, linked_list_t *dst_ts)
Add an SA to the SAD.
This function does install a single SA for a single protocol in one direction.
Parameters
src source address for this SA
dst destination address for this SA
spi SPI allocated by us or remote peer
protocol protocol for this SA (ESP/AH)
reqid reqid for this SA
mark optional mark for this SA
tfc Traffic Flow Confidentiality padding for this SA
lifetime lifetime_cfg_t for this SA
enc_alg Algorithm to use for encryption (ESP only)
enc_key key to use for encryption
int_alg Algorithm to use for integrity protection
int_key key to use for integrity protection
mode mode of the SA (tunnel, transport)
ipcomp IPComp transform to use
cpi CPI for IPComp
replay_window anti-replay window size
initiator TRUE if initiator of the exchange creating this SA
encap enable UDP encapsulation for NAT traversal
esn TRUE to use Extended Sequence Numbers
inbound TRUE if this is an inbound SA
update TRUE if an SPI has already been allocated for SA
src_ts list of source traffic selectors
dst_ts list of destination traffic selectors
Returns
SUCCESS if operation completed
Definition at line 188 of file kernel_interface.h.
Referenced by METHOD().
bool(* kernel_interface_t::all_interfaces_usable)(kernel_interface_t *this)
Check if interfaces are excluded by config.
Returns
TRUE if no interfaces are exclued by config
Definition at line 485 of file kernel_interface.h.
Referenced by receive_packets().
status_t(* kernel_interface_t::alloc_reqid)(kernel_interface_t *this, linked_list_t *local_ts, linked_list_t *remote_ts, mark_t mark_in, mark_t mark_out, u_int32_t *reqid)
Allocate or confirm a reqid to use for a given SA pair.
Each returned reqid by a successful call to alloc_reqid() must be released using release_reqid().
The reqid parameter is an in/out parameter. If it points to non-zero, the reqid is confirmed and registered for use. If it points to zero, a reqid is allocated for the given selectors, and returned to reqid.
Parameters
local_ts traffic selectors of local side for SA
remote_ts traffic selectors of remote side for SA
mark_in inbound mark on SA
mark_out outbound mark on SA
reqid allocated reqid
Returns
SUCCESS if reqid allocated
Definition at line 141 of file kernel_interface.h.
Referenced by METHOD().
bool(* kernel_interface_t::bypass_socket)(kernel_interface_t *this, int fd, int family)
Set up a bypass policy for a given socket.
Parameters
fd socket file descriptor to setup policy for
family protocol family of the socket
Returns
TRUE if policy set up successfully
Definition at line 453 of file kernel_interface.h.
Referenced by open_socket().
enumerator_t*(* kernel_interface_t::create_address_enumerator)(kernel_interface_t *this, kernel_address_type_t which)
Creates an enumerator over all local addresses.
This function blocks an internal cached address list until the enumerator gets destroyed. The hosts are read-only, do not modify of free.
Parameters
which a combination of address types to enumerate
Returns
enumerator over host_t's
Definition at line 386 of file kernel_interface.h.
Referenced by build_address_list(), gather_and_add_endpoints(), METHOD(), and publish_device_ip_addresses().
status_t(* kernel_interface_t::del_ip)(kernel_interface_t *this, host_t *virtual_ip, int prefix, bool wait)
Remove a virtual IP from an interface.
The kernel interface uses refcounting, see add_ip().
Parameters
virtual_ip virtual ip address to remove
prefix prefix length of the IP to uninstall, -1 for auto
wait TRUE to wait untily IP is gone
Returns
SUCCESS if operation completed
Definition at line 414 of file kernel_interface.h.
Referenced by cleanup_leases(), METHOD(), and reinstall_vip().
status_t(* kernel_interface_t::del_policy)(kernel_interface_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
Remove a policy from the SPD.
Parameters
src source address of SA
dst dest address of SA
src_ts traffic selector to match traffic source
dst_ts traffic selector to match traffic dest
direction direction of traffic, POLICY_(IN|OUT|FWD)
type type of policy, POLICY_(IPSEC|PASS|DROP)
sa details about the SA(s) tied to this policy
mark mark for this policy
priority priority of the policy
Returns
SUCCESS if operation completed
Definition at line 320 of file kernel_interface.h.
Referenced by del_policies_internal(), and uninstall_shunt_policy().
status_t(* kernel_interface_t::del_route)(kernel_interface_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
Delete a route.
Parameters
dst_net destination net
prefixlen destination net prefix length
gateway gateway for this route
src_ip source ip of the route
if_name name of the interface the route is bound to
Returns
SUCCESS if operation completed
Definition at line 442 of file kernel_interface.h.
Referenced by add_policy_internal(), install_route(), METHOD(), remove_exclude_route(), and uninstall_route().
status_t(* kernel_interface_t::del_sa)(kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Delete a previously installed SA from the SAD.
Parameters
src source address for this SA
dst destination address for this SA
spi SPI allocated by us or remote peer
protocol protocol for this SA (ESP/AH)
cpi CPI for IPComp or 0
mark optional mark for this SA
Returns
SUCCESS if operation completed
Definition at line 254 of file kernel_interface.h.
Referenced by METHOD().
void(* kernel_interface_t::destroy)(kernel_interface_t *this)
Destroys a kernel_interface_t object.
Definition at line 647 of file kernel_interface.h.
Referenced by libhydra_deinit().
bool(* kernel_interface_t::enable_udp_decap)(kernel_interface_t *this, int fd, int family, u_int16_t port)
Enable decapsulation of ESP-in-UDP packets for the given port/socket.
Parameters
fd socket file descriptor
family protocol family of the socket
port the UDP port
Returns
TRUE if UDP decapsulation was enabled successfully
Definition at line 463 of file kernel_interface.h.
Referenced by open_socket().
void(* kernel_interface_t::expire)(kernel_interface_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, bool hard)
Raise an expire event.
Parameters
protocol protocol of the expired SA
spi spi of the expired SA
dst destination address of expired SA
hard TRUE if it is a hard expire, FALSE otherwise
Definition at line 575 of file kernel_interface.h.
Referenced by charon_esa_expire(), expire(), expire_job(), and process_expire().
status_t(* kernel_interface_t::flush_policies)(kernel_interface_t *this)
Flush all policies from the SPD.
Returns
SUCCESS if operation completed
Definition at line 333 of file kernel_interface.h.
status_t(* kernel_interface_t::flush_sas)(kernel_interface_t *this)
Flush all SAs from the SAD.
Returns
SUCCESS if operation completed
Definition at line 263 of file kernel_interface.h.
status_t(* kernel_interface_t::get_address_by_ts)(kernel_interface_t *this, traffic_selector_t *ts, host_t **ip, bool *vip)
Tries to find an IP address of a local interface that is included in the supplied traffic selector.
Parameters
ts traffic selector
ip returned IP address (has to be destroyed)
vip set to TRUE if returned address is a virtual IP
Returns
SUCCESS if address found
Definition at line 496 of file kernel_interface.h.
Referenced by add_policy_internal(), install_route(), and manage_route().
status_t(* kernel_interface_t::get_cpi)(kernel_interface_t *this, host_t *src, host_t *dst, u_int16_t *cpi)
Get a Compression Parameter Index (CPI) from the kernel.
Parameters
src source address of SA
dst destination address of SA
cpi allocated cpi
Returns
SUCCESS if operation completed
Definition at line 121 of file kernel_interface.h.
Referenced by METHOD().
kernel_feature_t(* kernel_interface_t::get_features)(kernel_interface_t *this)
Get the feature set supported by the net and ipsec kernel backends.
Returns
ORed feature-set of backends
Definition at line 99 of file kernel_interface.h.
Referenced by build_payloads(), force_encap(), install_route(), and require_policy_update().
bool(* kernel_interface_t::get_interface)(kernel_interface_t *this, host_t *host, char **name)
Get the interface name of a local address. Interfaces that are down or ignored by config are not considered.
Parameters
host address to get interface name from
name allocated interface name (optional)
Returns
TRUE if interface found and usable
Definition at line 374 of file kernel_interface.h.
Referenced by add_exclude_route(), add_policy_internal(), install_route(), invoke_once(), is_local(), METHOD(), receive_packets(), reinstall_vip(), remove_exclude_route(), and uninstall_route().
host_t*(* kernel_interface_t::get_nexthop)(kernel_interface_t *this, host_t *dest, int prefix, host_t *src)
Get the next hop for a destination.
Does a route lookup to get the next hop used to reach dest. The returned host is allocated and must be destroyed. An optional src address can be used to check if a route is available for the given source to dest.
Parameters
dest target destination address
prefix prefix length if dest is a subnet, -1 for auto
src source address to check, or NULL
Returns
next hop address, NULL if unreachable
Definition at line 363 of file kernel_interface.h.
Referenced by add_exclude_route(), add_policy_internal(), install_route(), and manage_route().
host_t*(* kernel_interface_t::get_source_addr)(kernel_interface_t *this, host_t *dest, host_t *src)
Get our outgoing source address for a destination.
Does a route lookup to get the source address used to reach dest. The returned host is allocated and must be destroyed. An optional src address can be used to check if a route is available for the given source to dest.
Parameters
dest target destination address
src source address to check, or NULL
Returns
outgoing source address, NULL if unreachable
Definition at line 347 of file kernel_interface.h.
Referenced by is_any_path_valid(), is_current_path_valid(), METHOD(), prepare_dhcp(), and resolve_hosts().
status_t(* kernel_interface_t::get_spi)(kernel_interface_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
Get a SPI from the kernel.
Parameters
src source address of SA
dst destination address of SA
protocol protocol for SA (ESP/AH)
spi allocated spi
Returns
SUCCESS if operation completed
Definition at line 110 of file kernel_interface.h.
Referenced by METHOD().
bool(* kernel_interface_t::is_interface_usable)(kernel_interface_t *this, const char *iface)
manager methods Verifies that the given interface is usable and not excluded by configuration.
Parameters
iface interface name
Returns
TRUE if usable
Definition at line 478 of file kernel_interface.h.
Referenced by init_address_list(), and process_link().
bool(* kernel_interface_t::lookup_algorithm)(kernel_interface_t *this, u_int16_t alg_id, transform_type_t type, u_int16_t *kernel_id, char **kernel_name)
Return the kernel-specific id and/or name for an algorithms depending on the arguments specified.
Parameters
alg_id the IKE id of the algorithm
type the transform type of the algorithm
kernel_id the kernel id of the algorithm (optional)
kernel_name the kernel name of the algorithm (optional)
Returns
TRUE if algorithm was found
Definition at line 640 of file kernel_interface.h.
Referenced by lookup_algorithm().
void(* kernel_interface_t::mapping)(kernel_interface_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, host_t *remote)
Raise a mapping event.
Parameters
protocol protocol of affected SA
spi spi of the SA
dst original destination address of SA
remote new remote host
Definition at line 586 of file kernel_interface.h.
Referenced by process_mapping().
void(* kernel_interface_t::migrate)(kernel_interface_t *this, u_int32_t reqid, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, host_t *local, host_t *remote)
Raise a migrate event.
Parameters
reqid reqid of the policy
src_ts source traffic selector
dst_ts destination traffic selector
direction direction of the policy (in|out)
local local host address to be used in the IKE_SA
remote remote host address to be used in the IKE_SA
Definition at line 599 of file kernel_interface.h.
Referenced by process_migrate().
status_t(* kernel_interface_t::query_policy)(kernel_interface_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, mark_t mark, time_t *use_time)
Query the use time of a policy.
The use time of a policy is the time the policy was used for the last time.
Parameters
src_ts traffic selector to match traffic source
dst_ts traffic selector to match traffic dest
direction direction of traffic, POLICY_(IN|OUT|FWD)
mark optional mark
[out] use_time the (monotonic) time of this SA's last use
Returns
SUCCESS if operation completed
Definition at line 300 of file kernel_interface.h.
Referenced by update_usetime().
status_t(* kernel_interface_t::query_sa)(kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
Query the number of bytes processed by an SA from the SAD.
Parameters
src source address for this SA
dst destination address for this SA
spi SPI allocated by us or remote peer
protocol protocol for this SA (ESP/AH)
mark optional mark for this SA
[out] bytes the number of bytes processed by SA
[out] packets number of packets processed by SA
[out] time last (monotonic) time of SA use
Returns
SUCCESS if operation completed
Definition at line 239 of file kernel_interface.h.
Referenced by update_usebytes().
void(* kernel_interface_t::register_algorithm)(kernel_interface_t *this, u_int16_t alg_id, transform_type_t type, u_int16_t kernel_id, char *kernel_name)
Register a new algorithm with the kernel interface.
Parameters
alg_id the IKE id of the algorithm
type the transform type of the algorithm
kernel_id the kernel id of the algorithm
kernel_name the kernel name of the algorithm
Definition at line 626 of file kernel_interface.h.
status_t(* kernel_interface_t::release_reqid)(kernel_interface_t *this, u_int32_t reqid, mark_t mark_in, mark_t mark_out)
Release a previously allocated reqid.
Parameters
reqid reqid to release
mark_in inbound mark on SA
mark_out outbound mark on SA
Returns
SUCCESS if reqid released
Definition at line 154 of file kernel_interface.h.
Referenced by METHOD().
bool(* kernel_interface_t::remove_ipsec_interface)(kernel_interface_t *this, kernel_ipsec_constructor_t create)
Unregister an ipsec kernel interface constructor.
Parameters
create constructor to unregister
Returns
TRUE if the ipsec kernel interface was unregistered successfully, FALSE otherwise
Definition at line 517 of file kernel_interface.h.
Referenced by kernel_ipsec_register(), and METHOD().
void(* kernel_interface_t::remove_listener)(kernel_interface_t *this, kernel_listener_t *listener)
Remove a listener from the kernel interface.
Parameters
listener listener to remove
Definition at line 554 of file kernel_interface.h.
Referenced by METHOD().
bool(* kernel_interface_t::remove_net_interface)(kernel_interface_t *this, kernel_net_constructor_t create)
Unregister a network kernel interface constructor.
Parameters
create constructor to unregister
Returns
TRUE if the kernel net interface was unregistered successfully, FALSE otherwise
Definition at line 538 of file kernel_interface.h.
Referenced by kernel_net_register().
void(* kernel_interface_t::roam)(kernel_interface_t *this, bool address)
Raise a roam event.
Parameters
address TRUE if address list, FALSE if routing changed
Definition at line 608 of file kernel_interface.h.
Referenced by roam_event().
void(* kernel_interface_t::tun)(kernel_interface_t *this, tun_device_t *tun, bool created)
Raise a tun event.
Parameters
tun TUN device
created TRUE if created, FALSE if going to be destroyed
Definition at line 616 of file kernel_interface.h.
Referenced by METHOD().
status_t(* kernel_interface_t::update_sa)(kernel_interface_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
Update the hosts on an installed SA.
We cannot directly update the destination address as the kernel requires the spi, the protocol AND the destination address (and family) to identify SAs. Therefore if the destination address changed we create a new SA and delete the old one.
Parameters
spi SPI of the SA
protocol protocol for this SA (ESP/AH)
cpi CPI for IPComp, 0 if no IPComp is used
src current source address
dst current destination address
new_src new source address
new_dst new destination address
encap current use of UDP encapsulation
new_encap new use of UDP encapsulation
mark optional mark for this SA
Returns
SUCCESS if operation completed, NOT_SUPPORTED if the kernel interface can't update the SA
Definition at line 220 of file kernel_interface.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
kernel_interface.h