strongSwan: pgp_plugin.c File Reference
pgp_plugin.c File Reference
#include "pgp_plugin.h"
#include <library.h>
#include "pgp_builder.h"
#include "pgp_encoder.h"
#include "pgp_cert.h"
Classes
struct private_pgp_plugin_t
Typedefs
typedef struct private_pgp_plugin_t private_pgp_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_pgp_plugin_t *this)
METHOD (plugin_t, get_features, int, private_pgp_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_pgp_plugin_t *this)
plugin_t * pgp_plugin_create ()
Typedef Documentation
typedef struct private_pgp_plugin_t private_pgp_plugin_t
Definition at line 23 of file pgp_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_pgp_plugin_t * this)
Definition at line 36 of file pgp_plugin.c.
 {
     return "pgp";
 }
METHOD (plugin_t , get_features , int , private_pgp_plugin_t * this, plugin_feature_t * features[])
Definition at line 42 of file pgp_plugin.c.
References CERT_GPG, countof, FALSE, KEY_ANY, KEY_RSA, pgp_cert_load(), pgp_private_key_load(), pgp_public_key_load(), PLUGIN_PROVIDE, and PLUGIN_REGISTER.
 {
     static plugin_feature_t f[] = {
         PLUGIN_REGISTER(PRIVKEY, pgp_private_key_load, FALSE),
             PLUGIN_PROVIDE(PRIVKEY, KEY_ANY),
         PLUGIN_REGISTER(PRIVKEY, pgp_private_key_load, FALSE),
             PLUGIN_PROVIDE(PRIVKEY, KEY_RSA),
         PLUGIN_REGISTER(PUBKEY, pgp_public_key_load, FALSE),
             PLUGIN_PROVIDE(PUBKEY, KEY_ANY),
         PLUGIN_REGISTER(PUBKEY, pgp_public_key_load, FALSE),
             PLUGIN_PROVIDE(PUBKEY, KEY_RSA),
         PLUGIN_REGISTER(CERT_DECODE, pgp_cert_load, FALSE),
             PLUGIN_PROVIDE(CERT_DECODE, CERT_GPG),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_pgp_plugin_t * this)
Definition at line 63 of file pgp_plugin.c.
References library_t::encoding, free(), lib, pgp_encoder_encode(), and cred_encoding_t::remove_encoder.
 {
     lib->encoding->remove_encoder(lib->encoding, pgp_encoder_encode);
     free(this);
 }
plugin_t* pgp_plugin_create ()
Definition at line 74 of file pgp_plugin.c.
References cred_encoding_t::add_encoder, library_t::encoding, INIT, lib, and pgp_encoder_encode().
 {
     private_pgp_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     lib->encoding->add_encoder(lib->encoding, pgp_encoder_encode);
     return &this->public.plugin;
 }