strongSwan: dnscert_plugin.c File Reference
dnscert_plugin.c File Reference
#include "dnscert_plugin.h"
#include <daemon.h>
#include "dnscert_cred.h"
Classes
struct private_dnscert_plugin_t
Typedefs
typedef struct
private_dnscert_plugin_t private_dnscert_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_dnscert_plugin_t *this)
METHOD (plugin_t, reload, bool, private_dnscert_plugin_t *this)
static bool plugin_cb (private_dnscert_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_dnscert_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_dnscert_plugin_t *this)
plugin_t * dnscert_plugin_create ()
Typedef Documentation
typedef struct private_dnscert_plugin_t private_dnscert_plugin_t
Definition at line 43 of file dnscert_plugin.c.
Function Documentation
plugin_t* dnscert_plugin_create ()
Definition at line 150 of file dnscert_plugin.c.
References INIT.
 {
     private_dnscert_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .reload = _reload,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_dnscert_plugin_t * this)
Definition at line 67 of file dnscert_plugin.c.
 {
     return "dnscert";
 }
METHOD (plugin_t , reload , bool , private_dnscert_plugin_t * this)
Definition at line 73 of file dnscert_plugin.c.
References credential_manager_t::add_set, library_t::credmgr, DBG1, DBG_CFG, enabled, FALSE, settings_t::get_bool, lib, library_t::ns, credential_manager_t::remove_set, library_t::settings, and TRUE.
 {
     bool enabled = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.dnscert.enable", FALSE, lib->ns);
     if (enabled != this->enabled)
     {
         if (enabled)
         {
             lib->credmgr->add_set(lib->credmgr, &this->cred->set);
         }
         else
         {
             lib->credmgr->remove_set(lib->credmgr, &this->cred->set);
         }
         this->enabled = enabled;
     }
     DBG1(DBG_CFG, "dnscert plugin is %sabled", this->enabled ? "en" : "dis");
     return TRUE;
 }
METHOD (plugin_t , get_features , int , private_dnscert_plugin_t * this, plugin_feature_t * features[])
Definition at line 126 of file dnscert_plugin.c.
References CERT_ANY, CERT_GPG, CERT_X509, countof, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_DEPENDS, PLUGIN_PROVIDE, and PLUGIN_SDEPEND.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "dnscert"),
                 PLUGIN_DEPENDS(RESOLVER),
                 PLUGIN_DEPENDS(CERT_DECODE, CERT_ANY),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_GPG),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_dnscert_plugin_t * this)
Definition at line 141 of file dnscert_plugin.c.
References free().
 {
     free(this);
 }
static bool plugin_cb (private_dnscert_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Create resolver and register credential set
Definition at line 98 of file dnscert_plugin.c.
References resolver_manager_t::create, library_t::credmgr, DBG1, DBG_CFG, dnscert_cred_create(), enabled, FALSE, lib, credential_manager_t::remove_set, res, library_t::resolver, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         resolver_t *res;
         res = lib->resolver->create(lib->resolver);
         if (!res)
         {
             DBG1(DBG_CFG, "failed to create a DNS resolver instance");
             return FALSE;
         }
         this->cred = dnscert_cred_create(res);
         reload(this);
     }
     else
     {
         if (this->enabled)
         {
             lib->credmgr->remove_set(lib->credmgr, &this->cred->set);
         }
         this->cred->destroy(this->cred);
     }
     return TRUE;
 }