strongSwan: ocsp_response_wrapper
ocsp_response_wrapper
sets
Classes
struct ocsp_response_wrapper_t
Typedefs
typedef struct
ocsp_response_wrapper_t ocsp_response_wrapper_t
Functions
ocsp_response_wrapper_t * ocsp_response_wrapper_create (ocsp_response_t *response)
Detailed Description
Typedef Documentation
typedef struct ocsp_response_wrapper_t ocsp_response_wrapper_t
Definition at line 27 of file ocsp_response_wrapper.h.
Function Documentation
ocsp_response_wrapper_t* ocsp_response_wrapper_create (ocsp_response_t * response)
Create a ocsp_response_wrapper instance.
Parameters
response the wrapped OCSP response
Returns
wrapper around response
Definition at line 127 of file ocsp_response_wrapper.c.
References INIT, nop(), response, and return_null().
Referenced by verify_ocsp().
 {
     private_ocsp_response_wrapper_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_cert_enumerator = _create_enumerator,
                 .create_private_enumerator = (void*)return_null,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .destroy = _destroy,
         },
         .response = response,
     );
     return &this->public;
 }