strongSwan: attribute_manager.c File Reference
attribute_manager.c File Reference
#include "attribute_manager.h"
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_attribute_manager_t
struct enum_data_t
struct initiator_enumerator_t
Typedefs
typedef struct
private_attribute_manager_t private_attribute_manager_t
Functions
METHOD (attribute_manager_t, acquire_address, host_t *, private_attribute_manager_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
METHOD (attribute_manager_t, release_address, bool, private_attribute_manager_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
static enumerator_t * responder_enum_create (attribute_provider_t *provider, enum_data_t *data)
METHOD (attribute_manager_t, create_responder_enumerator, enumerator_t *, private_attribute_manager_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (attribute_manager_t, add_provider, void, private_attribute_manager_t *this, attribute_provider_t *provider)
METHOD (attribute_manager_t, remove_provider, void, private_attribute_manager_t *this, attribute_provider_t *provider)
METHOD (attribute_manager_t, handle, attribute_handler_t *, private_attribute_manager_t *this, ike_sa_t *ike_sa, attribute_handler_t *handler, configuration_attribute_type_t type, chunk_t data)
METHOD (attribute_manager_t, release, void, private_attribute_manager_t *this, attribute_handler_t *handler, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
static bool initiator_enumerate (initiator_enumerator_t *this, attribute_handler_t **handler, configuration_attribute_type_t *type, chunk_t *value)
static void initiator_destroy (initiator_enumerator_t *this)
METHOD (attribute_manager_t, create_initiator_enumerator, enumerator_t *, private_attribute_manager_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (attribute_manager_t, add_handler, void, private_attribute_manager_t *this, attribute_handler_t *handler)
METHOD (attribute_manager_t, remove_handler, void, private_attribute_manager_t *this, attribute_handler_t *handler)
METHOD (attribute_manager_t, destroy, void, private_attribute_manager_t *this)
attribute_manager_t * attribute_manager_create ()
Typedef Documentation
typedef struct private_attribute_manager_t private_attribute_manager_t
Definition at line 22 of file attribute_manager.c.
Function Documentation
static void initiator_destroy (initiator_enumerator_t * this) static
Cleanup function of initiator attribute enumerator
Definition at line 267 of file attribute_manager.c.
References DESTROY_IF, free(), lock, and spinlock_t::unlock.
Referenced by METHOD().
 {
     this->this->lock->unlock(this->this->lock);
     this->outer->destroy(this->outer);
     DESTROY_IF(this->inner);
     free(this);
 }
static bool initiator_enumerate (initiator_enumerator_t * this, attribute_handler_t ** handler, configuration_attribute_type_t * type, chunk_t * value) static
Enumerator implementation for initiator attributes
Definition at line 243 of file attribute_manager.c.
References attribute_handler_t::create_attribute_enumerator, DESTROY_IF, FALSE, and TRUE.
Referenced by METHOD().
 {
     /* enumerate inner attributes using outer handler enumerator */
     while (!this->inner || !this->inner->enumerate(this->inner, type, value))
     {
         if (!this->outer->enumerate(this->outer, &this->handler))
         {
             return FALSE;
         }
         DESTROY_IF(this->inner);
         this->inner = this->handler->create_attribute_enumerator(this->handler,
                                                     this->ike_sa, this->vips);
     }
     /* inject the handler as additional attribute */
     *handler = this->handler;
     return TRUE;
 }
METHOD (attribute_manager_t , acquire_address , host_t * , private_attribute_manager_t * this, linked_list_t * pools, ike_sa_t * ike_sa, host_t * requested)
Definition at line 62 of file attribute_manager.c.
References attribute_provider_t::acquire_address, enumerator_t::destroy, enumerator_t::enumerate, host, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     attribute_provider_t *current;
     host_t *host = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &current))
     {
         host = current->acquire_address(current, pools, ike_sa, requested);
         if (host)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return host;
 }
METHOD (attribute_manager_t , release_address , bool , private_attribute_manager_t * this, linked_list_t * pools, host_t * address, ike_sa_t * ike_sa)
Definition at line 86 of file attribute_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, lock, attribute_provider_t::release_address, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     attribute_provider_t *current;
     bool found = FALSE;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current->release_address(current, pools, address, ike_sa))
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (attribute_manager_t , create_responder_enumerator , enumerator_t * , private_attribute_manager_t * this, linked_list_t * pools, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 120 of file attribute_manager.c.
References data, enumerator_create_cleaner(), enumerator_create_nested(), free(), INIT, lock, responder_enum_create(), and spinlock_t::unlock.
 {
     enum_data_t *data;
     INIT(data,
         .pools = pools,
         .ike_sa = ike_sa,
         .vips = vips,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_cleaner(
                 enumerator_create_nested(
                     this->providers->create_enumerator(this->providers),
                     (void*)responder_enum_create, data, free),
                 (void*)this->lock->unlock, this->lock);
 }
METHOD (attribute_manager_t , add_provider , void , private_attribute_manager_t * this, attribute_provider_t * provider)
Definition at line 139 of file attribute_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->providers->insert_last(this->providers, provider);
     this->lock->unlock(this->lock);
 }
METHOD (attribute_manager_t , remove_provider , void , private_attribute_manager_t * this, attribute_provider_t * provider)
Definition at line 147 of file attribute_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->providers->remove(this->providers, provider, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (attribute_manager_t , handle , attribute_handler_t * , private_attribute_manager_t * this, ike_sa_t * ike_sa, attribute_handler_t * handler, configuration_attribute_type_t type, chunk_t data)
Definition at line 155 of file attribute_manager.c.
References configuration_attribute_type_names, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, attribute_handler_t::handle, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     attribute_handler_t *current, *handled = NULL;
     this->lock->read_lock(this->lock);
     /* try to find the passed handler */
     enumerator = this->handlers->create_enumerator(this->handlers);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current == handler && current->handle(current, ike_sa, type, data))
         {
             handled = current;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!handled)
     {   /* handler requesting this attribute not found, try any other */
         enumerator = this->handlers->create_enumerator(this->handlers);
         while (enumerator->enumerate(enumerator, &current))
         {
             if (current->handle(current, ike_sa, type, data))
             {
                 handled = current;
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     this->lock->unlock(this->lock);
     if (!handled)
     {
         DBG1(DBG_CFG, "handling %N attribute failed",
              configuration_attribute_type_names, type);
     }
     return handled;
 }
METHOD (attribute_manager_t , release , void , private_attribute_manager_t * this, attribute_handler_t * handler, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 199 of file attribute_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, lock, attribute_handler_t::release, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     attribute_handler_t *current;
     this->lock->read_lock(this->lock);
     enumerator = this->handlers->create_enumerator(this->handlers);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current == handler)
         {
             current->release(current, ike_sa, type, data);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (attribute_manager_t , create_initiator_enumerator , enumerator_t * , private_attribute_manager_t * this, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 275 of file attribute_manager.c.
References linked_list_t::create_enumerator, destroy(), INIT, initiator_destroy(), initiator_enumerate(), lock, and initiator_enumerator_t::public.
 {
     initiator_enumerator_t *enumerator;
     this->lock->read_lock(this->lock);
     INIT(enumerator,
         .public = {
             .enumerate = (void*)initiator_enumerate,
             .destroy = (void*)initiator_destroy,
         },
         .this = this,
         .ike_sa = ike_sa,
         .vips = vips,
         .outer = this->handlers->create_enumerator(this->handlers),
     );
     return &enumerator->public;
 }
METHOD (attribute_manager_t , add_handler , void , private_attribute_manager_t * this, attribute_handler_t * handler)
Definition at line 295 of file attribute_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->handlers->insert_last(this->handlers, handler);
     this->lock->unlock(this->lock);
 }
METHOD (attribute_manager_t , remove_handler , void , private_attribute_manager_t * this, attribute_handler_t * handler)
Definition at line 303 of file attribute_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->handlers->remove(this->handlers, handler, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (attribute_manager_t , destroy , void , private_attribute_manager_t * this)
Definition at line 311 of file attribute_manager.c.
References spinlock_t::destroy, free(), and lock.
 {
     this->providers->destroy(this->providers);
     this->handlers->destroy(this->handlers);
     this->lock->destroy(this->lock);
     free(this);
 }
static enumerator_t* responder_enum_create (attribute_provider_t * provider, enum_data_t * data) static
inner enumerator constructor for responder attributes
Definition at line 113 of file attribute_manager.c.
References attribute_provider_t::create_attribute_enumerator, enum_data_t::ike_sa, enum_data_t::pools, and enum_data_t::vips.
Referenced by METHOD().
 {
     return provider->create_attribute_enumerator(provider, data->pools,
                                                  data->ike_sa, data->vips);
 }