strongSwan: ha_socket.c File Reference
ha_socket.c File Reference
#include "ha_socket.h"
#include "ha_plugin.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <errno.h>
#include <unistd.h>
#include <daemon.h>
#include <networking/host.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_ha_socket_t
struct job_data_t
Typedefs
typedef struct private_ha_socket_t private_ha_socket_t
Functions
static void job_data_destroy (job_data_t *this)
static job_requeue_t send_message (job_data_t *data)
METHOD (ha_socket_t, push, void, private_ha_socket_t *this, ha_message_t *message)
METHOD (ha_socket_t, pull, ha_message_t *, private_ha_socket_t *this)
static bool open_socket (private_ha_socket_t *this)
METHOD (ha_socket_t, destroy, void, private_ha_socket_t *this)
ha_socket_t * ha_socket_create (char *local, char *remote)
Typedef Documentation
typedef struct private_ha_socket_t private_ha_socket_t
Definition at line 29 of file ha_socket.c.
Function Documentation
static void job_data_destroy (job_data_t * this) static
Cleanup job data
Definition at line 68 of file ha_socket.c.
References free().
Referenced by METHOD().
 {
     free(this->chunk.ptr);
     free(this);
 }
METHOD (ha_socket_t , push , void , private_ha_socket_t * this, ha_message_t * message)
Definition at line 86 of file ha_socket.c.
References callback_job_create_with_prio(), chunk_clone, data, DBG1, DBG_CFG, ha_message_t::get_encoding, INIT, job_data_destroy(), JOB_PRIO_HIGH, chunk_t::len, lib, MSG_DONTWAIT, library_t::processor, chunk_t::ptr, processor_t::queue_job, send, send_message(), and strerror.
 {
     chunk_t chunk;
     /* Try to send synchronously, but non-blocking. */
     chunk = message->get_encoding(message);
     if (send(this->fd, chunk.ptr, chunk.len, MSG_DONTWAIT) < chunk.len)
     {
         if (errno == EAGAIN)
         {
             callback_job_t *job;
             job_data_t *data;
             /* Fallback to asynchronous transmission. This is required, as sendto()
              * is a blocking call if it acquires a policy. We could end up in a
              * deadlock, as we own an IKE_SA. */
             INIT(data,
                 .chunk = chunk_clone(chunk),
                 .fd = this->fd,
             );
             job = callback_job_create_with_prio((callback_job_cb_t)send_message,
                             data, (void*)job_data_destroy, NULL, JOB_PRIO_HIGH);
             lib->processor->queue_job(lib->processor, (job_t*)job);
             return;
         }
         DBG1(DBG_CFG, "pushing HA message failed: %s", strerror(errno));
     }
 }
METHOD (ha_socket_t , pull , ha_message_t * , private_ha_socket_t * this)
Definition at line 117 of file ha_socket.c.
References chunk_create(), DBG1, DBG_CFG, ECONNREFUSED, ha_message_parse(), len, recv, sleep, strerror, thread_cancelability(), and TRUE.
 {
     while (TRUE)
     {
         ha_message_t *message;
         char buf[1024];
         bool oldstate;
         ssize_t len;
         oldstate = thread_cancelability(TRUE);
         len = recv(this->fd, buf, sizeof(buf), 0);
         thread_cancelability(oldstate);
         if (len <= 0)
         {
             switch (errno)
             {
                 case ECONNREFUSED:
                 case EINTR:
                     continue;
                 default:
                     DBG1(DBG_CFG, "pulling HA message failed: %s",
                          strerror(errno));
                     sleep(1);
                     continue;
             }
         }
         message = ha_message_parse(chunk_create(buf, len));
         if (message)
         {
             return message;
         }
     }
 }
METHOD (ha_socket_t , destroy , void , private_ha_socket_t * this)
Definition at line 184 of file ha_socket.c.
References close, DESTROY_IF, and free().
 {
     if (this->fd != -1)
     {
         close(this->fd);
     }
     DESTROY_IF(this->local);
     DESTROY_IF(this->remote);
     free(this);
 }
static bool open_socket (private_ha_socket_t * this) static
Open and connect the HA socket
Definition at line 155 of file ha_socket.c.
References bind, close, connect, DBG1, DBG_CFG, FALSE, socket, strerror, and TRUE.
Referenced by ha_socket_create().
 {
     this->fd = socket(this->local->get_family(this->local), SOCK_DGRAM, 0);
     if (this->fd == -1)
     {
         DBG1(DBG_CFG, "opening HA socket failed: %s", strerror(errno));
         return FALSE;
     }
     if (bind(this->fd, this->local->get_sockaddr(this->local),
              *this->local->get_sockaddr_len(this->local)) == -1)
     {
         DBG1(DBG_CFG, "binding HA socket failed: %s", strerror(errno));
         close(this->fd);
         this->fd = -1;
         return FALSE;
     }
     if (connect(this->fd, this->remote->get_sockaddr(this->remote),
                 *this->remote->get_sockaddr_len(this->remote)) == -1)
     {
         DBG1(DBG_CFG, "connecting HA socket failed: %s", strerror(errno));
         close(this->fd);
         this->fd = -1;
         return FALSE;
     }
     return TRUE;
 }
static job_requeue_t send_message (job_data_t * data) static
Callback to asynchronously send messages
Definition at line 77 of file ha_socket.c.
References job_data_t::chunk, DBG1, DBG_CFG, job_data_t::fd, JOB_REQUEUE_NONE, chunk_t::len, chunk_t::ptr, send, and strerror.
Referenced by METHOD().
 {
     if (send(data->fd, data->chunk.ptr, data->chunk.len, 0) < data->chunk.len)
     {
         DBG1(DBG_CFG, "pushing HA message failed: %s", strerror(errno));
     }
     return JOB_REQUEUE_NONE;
 }