strongSwan: sql_cred.c File Reference
sql_cred.c File Reference
#include <string.h>
#include "sql_cred.h"
#include <daemon.h>
Classes
struct private_sql_cred_t
struct private_enumerator_t
struct cert_enumerator_t
struct shared_enumerator_t
struct cdp_enumerator_t
Typedefs
typedef struct private_sql_cred_t private_sql_cred_t
Enumerations
enum cdp_type_t { CDP_TYPE_ANY = 0, CDP_TYPE_CRL, CDP_TYPE_OCSP }
Functions
METHOD (enumerator_t, private_enumerator_enumerate, bool, private_enumerator_t *this, private_key_t **key)
METHOD (enumerator_t, private_enumerator_destroy, void, private_enumerator_t *this)
METHOD (credential_set_t, create_private_enumerator, enumerator_t *, private_sql_cred_t *this, key_type_t type, identification_t *id)
METHOD (enumerator_t, cert_enumerator_enumerate, bool, cert_enumerator_t *this, certificate_t **cert)
METHOD (enumerator_t, cert_enumerator_destroy, void, cert_enumerator_t *this)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_sql_cred_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (enumerator_t, shared_enumerator_enumerate, bool, shared_enumerator_t *this, shared_key_t **shared, id_match_t *me, id_match_t *other)
METHOD (enumerator_t, shared_enumerator_destroy, void, shared_enumerator_t *this)
METHOD (credential_set_t, create_shared_enumerator, enumerator_t *, private_sql_cred_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
METHOD (enumerator_t, cdp_enumerator_enumerate, bool, cdp_enumerator_t *this, char **uri)
METHOD (enumerator_t, cdp_enumerator_destroy, void, cdp_enumerator_t *this)
METHOD (credential_set_t, create_cdp_enumerator, enumerator_t *, private_sql_cred_t *this, certificate_type_t type, identification_t *id)
METHOD (credential_set_t, cache_cert, void, private_sql_cred_t *this, certificate_t *cert)
METHOD (sql_cred_t, destroy, void, private_sql_cred_t *this)
sql_cred_t * sql_cred_create (database_t *db)
Typedef Documentation
typedef struct private_sql_cred_t private_sql_cred_t
Definition at line 23 of file sql_cred.c.
Enumeration Type Documentation
enum cdp_type_t
types of CDPs
Enumerator
CDP_TYPE_ANY
any available CDP
CDP_TYPE_CRL
CRL
CDP_TYPE_OCSP
OCSP Responder
Definition at line 333 of file sql_cred.c.
              {
     CDP_TYPE_ANY = 0,
     CDP_TYPE_CRL,
     CDP_TYPE_OCSP,
 } cdp_type_t;
Function Documentation
METHOD (enumerator_t , private_enumerator_enumerate , bool , private_enumerator_t * this, private_key_t ** key)
Definition at line 54 of file sql_cred.c.
References blob, BUILD_BLOB_PEM, BUILD_END, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, DESTROY_IF, FALSE, lib, TRUE, and type.
 {
     chunk_t blob;
     int type;
     DESTROY_IF(this->current);
     while (this->inner->enumerate(this->inner, &type, &blob))
     {
         this->current = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, type,
                                            BUILD_BLOB_PEM, blob,
                                            BUILD_END);
         if (this->current)
         {
             *key = this->current;
             return TRUE;
         }
     }
     this->current = NULL;
     return FALSE;
 }
METHOD (enumerator_t , private_enumerator_destroy , void , private_enumerator_t * this)
Definition at line 76 of file sql_cred.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_private_enumerator , enumerator_t * , private_sql_cred_t * this, key_type_t type, identification_t * id)
Definition at line 84 of file sql_cred.c.
References db, DB_BLOB, DB_INT, destroy(), free(), identification_t::get_type, ID_ANY, INIT, private_enumerator_t::inner, KEY_ANY, private_enumerator_t::public, database_t::query, and type.
 {
     private_enumerator_t *e;
     INIT(e,
         .public = {
             .enumerate = (void*)_private_enumerator_enumerate,
             .destroy = _private_enumerator_destroy,
         },
     );
     if (id && id->get_type(id) != ID_ANY)
     {
         e->inner = this->db->query(this->db,
                 "SELECT p.type, p.data FROM private_keys AS p "
                 "JOIN private_key_identity AS pi ON p.id = pi.private_key "
                 "JOIN identities AS i ON pi.identity = i.id "
                 "WHERE i.type = ? AND i.data = ? AND (? OR p.type = ?)",
                 DB_INT, id->get_type(id), DB_BLOB, id->get_encoding(id),
                 DB_INT, type == KEY_ANY, DB_INT, type,
                 DB_INT, DB_BLOB);
     }
     else
     {
         e->inner = this->db->query(this->db,
                 "SELECT type, data FROM private_keys WHERE (? OR type = ?)",
                 DB_INT, type == KEY_ANY, DB_INT, type,
                 DB_INT, DB_BLOB);
     }
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (enumerator_t , cert_enumerator_enumerate , bool , cert_enumerator_t * this, certificate_t ** cert)
Definition at line 134 of file sql_cred.c.
References blob, BUILD_BLOB_PEM, BUILD_END, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DESTROY_IF, FALSE, lib, TRUE, and type.
 {
     chunk_t blob;
     int type;
     DESTROY_IF(this->current);
     while (this->inner->enumerate(this->inner, &type, &blob))
     {
         this->current = lib->creds->create(lib->creds, CRED_CERTIFICATE, type,
                                            BUILD_BLOB_PEM, blob,
                                            BUILD_END);
         if (this->current)
         {
             *cert = this->current;
             return TRUE;
         }
     }
     this->current = NULL;
     return FALSE;
 }
METHOD (enumerator_t , cert_enumerator_destroy , void , cert_enumerator_t * this)
Definition at line 156 of file sql_cred.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_sql_cred_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 164 of file sql_cred.c.
References cert, CERT_ANY, db, DB_BLOB, DB_INT, destroy(), free(), identification_t::get_type, ID_ANY, INIT, cert_enumerator_t::inner, key, KEY_ANY, cert_enumerator_t::public, and database_t::query.
 {
     cert_enumerator_t *e;
     INIT(e,
         .public = {
             .enumerate = (void*)_cert_enumerator_enumerate,
             .destroy = _cert_enumerator_destroy,
         },
     );
     if (id && id->get_type(id) != ID_ANY)
     {
         e->inner = this->db->query(this->db,
                 "SELECT c.type, c.data FROM certificates AS c "
                 "JOIN certificate_identity AS ci ON c.id = ci.certificate "
                 "JOIN identities AS i ON ci.identity = i.id "
                 "WHERE i.type = ? AND i.data = ? AND "
                 "(? OR c.type = ?) AND (? OR c.keytype = ?)",
                 DB_INT, id->get_type(id), DB_BLOB, id->get_encoding(id),
                 DB_INT, cert == CERT_ANY, DB_INT, cert,
                 DB_INT, key == KEY_ANY, DB_INT, key,
                 DB_INT, DB_BLOB);
     }
     else
     {
         e->inner = this->db->query(this->db,
                 "SELECT type, data FROM certificates WHERE "
                 "(? OR type = ?) AND (? OR keytype = ?)",
                 DB_INT, cert == CERT_ANY, DB_INT, cert,
                 DB_INT, key == KEY_ANY, DB_INT, key,
                 DB_INT, DB_BLOB);
     }
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (enumerator_t , shared_enumerator_enumerate , bool , shared_enumerator_t * this, shared_key_t ** shared, id_match_t * me, id_match_t * other)
Definition at line 223 of file sql_cred.c.
References blob, chunk_clone, DESTROY_IF, FALSE, ID_MATCH_ANY, ID_MATCH_PERFECT, shared_key_create(), TRUE, and type.
 {
     chunk_t blob;
     int type;
     DESTROY_IF(this->current);
     while (this->inner->enumerate(this->inner, &type, &blob))
     {
         this->current = shared_key_create(type, chunk_clone(blob));
         if (this->current)
         {
             *shared = this->current;
             if (me)
             {
                 *me = this->me ? ID_MATCH_PERFECT : ID_MATCH_ANY;
             }
             if (other)
             {
                 *other = this->other ? ID_MATCH_PERFECT : ID_MATCH_ANY;
             }
             return TRUE;
         }
     }
     this->current = NULL;
     return FALSE;
 }
METHOD (enumerator_t , shared_enumerator_destroy , void , shared_enumerator_t * this)
Definition at line 252 of file sql_cred.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_shared_enumerator , enumerator_t * , private_sql_cred_t * this, shared_key_type_t type, identification_t * me, identification_t * other)
Definition at line 260 of file sql_cred.c.
References db, DB_BLOB, DB_INT, destroy(), free(), identification_t::get_encoding, identification_t::get_type, INIT, shared_enumerator_t::inner, shared_enumerator_t::public, database_t::query, SHARED_ANY, and type.
 {
     shared_enumerator_t *e;
     INIT(e,
         .public = {
             .enumerate = (void*)_shared_enumerator_enumerate,
             .destroy = _shared_enumerator_destroy,
         },
         .me = me,
         .other = other,
     );
     if (!me && !other)
     {
         e->inner = this->db->query(this->db,
                 "SELECT type, data FROM shared_secrets WHERE  (? OR type = ?)",
                 DB_INT, type == SHARED_ANY, DB_INT, type,
                 DB_INT, DB_BLOB);
     }
     else if (me && other)
     {
         e->inner = this->db->query(this->db,
                 "SELECT s.type, s.data FROM shared_secrets AS s "
                 "JOIN shared_secret_identity AS sm ON s.id = sm.shared_secret "
                 "JOIN identities AS m ON sm.identity = m.id "
                 "JOIN shared_secret_identity AS so ON s.id = so.shared_secret "
                 "JOIN identities AS o ON so.identity = o.id "
                 "WHERE m.type = ? AND m.data = ? AND o.type = ? AND o.data = ? "
                 "AND (? OR s.type = ?)",
                 DB_INT, me->get_type(me), DB_BLOB, me->get_encoding(me),
                 DB_INT, other->get_type(other), DB_BLOB, other->get_encoding(other),
                 DB_INT, type == SHARED_ANY, DB_INT, type,
                 DB_INT, DB_BLOB);
     }
     else
     {
         identification_t *id = me ? me : other;
         e->inner = this->db->query(this->db,
                 "SELECT s.type, s.data FROM shared_secrets AS s "
                 "JOIN shared_secret_identity AS si ON s.id = si.shared_secret "
                 "JOIN identities AS i ON si.identity = i.id "
                 "WHERE i.type = ? AND i.data = ? AND (? OR s.type = ?)",
                 DB_INT, id->get_type(id), DB_BLOB, id->get_encoding(id),
                 DB_INT, type == SHARED_ANY, DB_INT, type,
                 DB_INT, DB_BLOB);
     }
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (enumerator_t , cdp_enumerator_enumerate , bool , cdp_enumerator_t * this, char ** uri)
Definition at line 342 of file sql_cred.c.
References FALSE, free(), strdup, and TRUE.
 {
     char *text;
     free(this->current);
     while (this->inner->enumerate(this->inner, &text))
     {
         *uri = this->current = strdup(text);
         return TRUE;
     }
     this->current = NULL;
     return FALSE;
 }
METHOD (enumerator_t , cdp_enumerator_destroy , void , cdp_enumerator_t * this)
Definition at line 357 of file sql_cred.c.
References free().
 {
     free(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_cdp_enumerator , enumerator_t * , private_sql_cred_t * this, certificate_type_t type, identification_t * id)
Definition at line 365 of file sql_cred.c.
References CDP_TYPE_ANY, CDP_TYPE_CRL, CDP_TYPE_OCSP, CERT_ANY, CERT_X509_CRL, CERT_X509_OCSP_RESPONSE, db, DB_BLOB, DB_INT, DB_TEXT, destroy(), free(), identification_t::get_type, ID_ANY, INIT, cdp_enumerator_t::inner, cdp_enumerator_t::public, and database_t::query.
 {
     cdp_enumerator_t *e;
     cdp_type_t cdp_type;
     switch (type)
     {   /* we serve CRLs and OCSP responders */
         case CERT_X509_CRL:
             cdp_type = CDP_TYPE_CRL;
             break;
         case CERT_X509_OCSP_RESPONSE:
             cdp_type = CDP_TYPE_OCSP;
             break;
         case CERT_ANY:
             cdp_type = CDP_TYPE_ANY;
             break;
         default:
             return NULL;
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_cdp_enumerator_enumerate,
             .destroy = _cdp_enumerator_destroy,
         },
     );
     if (id && id->get_type(id) != ID_ANY)
     {
         e->inner = this->db->query(this->db,
                 "SELECT dp.uri FROM certificate_distribution_points AS dp "
                 "JOIN certificate_authorities AS ca ON ca.id = dp.ca "
                 "JOIN certificates AS c ON c.id = ca.certificate "
                 "JOIN certificate_identity AS ci ON c.id = ci.certificate "
                 "JOIN identities AS i ON ci.identity = i.id "
                 "WHERE i.type = ? AND i.data = ? AND (? OR dp.type = ?)",
                 DB_INT, id->get_type(id), DB_BLOB, id->get_encoding(id),
                 DB_INT, cdp_type == CDP_TYPE_ANY, DB_INT, cdp_type,
                 DB_TEXT);
     }
     else
     {
         e->inner = this->db->query(this->db,
                 "SELECT dp.uri FROM certificate_distribution_points AS dp "
                 "WHERE (? OR dp.type = ?)",
                 DB_INT, cdp_type == CDP_TYPE_ANY, DB_INT, cdp_type,
                 DB_TEXT);
     }
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (credential_set_t , cache_cert , void , private_sql_cred_t * this, certificate_t * cert)
Definition at line 420 of file sql_cred.c.
 {
     /* TODO: implement CRL caching to database */
 }
METHOD (sql_cred_t , destroy , void , private_sql_cred_t * this)
Definition at line 426 of file sql_cred.c.
References free().
 {
     free(this);
 }