strongSwan: auth_payload
auth_payload
payloads
Classes
struct auth_payload_t
Typedefs
typedef struct auth_payload_t auth_payload_t
Functions
auth_payload_t * auth_payload_create (void)
Detailed Description
Typedef Documentation
typedef struct auth_payload_t auth_payload_t
Definition at line 25 of file auth_payload.h.
Function Documentation
auth_payload_t* auth_payload_create (void)
Creates an empty auth_payload_t object.
Returns
auth_payload_t object
Definition at line 195 of file auth_payload.c.
References INIT, and PL_NONE.
Referenced by build_auth(), METHOD(), payload_create(), and rebuild_auth().
 {
     private_auth_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .set_auth_method = _set_auth_method,
             .get_auth_method = _get_auth_method,
             .set_data = _set_data,
             .get_data = _get_data,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
     );
     return &this->public;
 }