strongSwan: pkcs5
pkcs5
crypto
Classes
struct pkcs5_t
Typedefs
typedef struct pkcs5_t pkcs5_t
Functions
pkcs5_t * pkcs5_from_algorithmIdentifier (chunk_t blob, int level0)
Detailed Description
Typedef Documentation
typedef struct pkcs5_t pkcs5_t
Definition at line 24 of file pkcs5.h.
Function Documentation
pkcs5_t* pkcs5_from_algorithmIdentifier (chunk_t blob, int level0)
Create a PKCS#5 helper object from an ASN.1 encoded AlgorithmIdentifier object.
Parameters
blob ASN.1 encoded AlgorithmIdentifier
level0 ASN.1 parser level
Returns
pkcs5_t object, NULL on failure
Definition at line 600 of file pkcs5.c.
References asn1_parse_algorithmIdentifier(), data, destroy(), ENCR_3DES, ENCR_DES, ENCR_RC2_CBC, HASH_MD5, HASH_SHA1, INIT, OID_PBE_MD5_DES_CBC, OID_PBE_SHA1_3DES_CBC, OID_PBE_SHA1_DES_CBC, OID_PBE_SHA1_RC2_CBC_128, OID_PBE_SHA1_RC2_CBC_40, OID_PBES2, params, parse_pbes1_params(), parse_pbes2_params(), and scheme.
Referenced by parse(), and parse_encrypted_private_key().
 {
     private_pkcs5_t *this;
     chunk_t params;
     int oid;
     INIT(this,
         .public = {
             .decrypt = _decrypt,
             .destroy = _destroy,
         },
         .scheme = PKCS5_SCHEME_PBES1,
         .keylen = 8,
     );
     oid = asn1_parse_algorithmIdentifier(blob, level0, &params);
     switch (oid)
     {
         case OID_PBE_MD5_DES_CBC:
             this->encr = ENCR_DES;
             this->data.pbes1.hash = HASH_MD5;
             break;
         case OID_PBE_SHA1_DES_CBC:
             this->encr = ENCR_DES;
             this->data.pbes1.hash = HASH_SHA1;
             break;
         case OID_PBE_SHA1_3DES_CBC:
             this->scheme = PKCS5_SCHEME_PKCS12;
             this->keylen = 24;
             this->encr = ENCR_3DES;
             this->data.pbes1.hash = HASH_SHA1;
             break;
         case OID_PBE_SHA1_RC2_CBC_40:
         case OID_PBE_SHA1_RC2_CBC_128:
             this->scheme = PKCS5_SCHEME_PKCS12;
             this->keylen = (oid == OID_PBE_SHA1_RC2_CBC_40) ? 5 : 16;
             this->encr = ENCR_RC2_CBC;
             this->data.pbes1.hash = HASH_SHA1;
             break;
         case OID_PBES2:
             this->scheme = PKCS5_SCHEME_PBES2;
             break;
         default:
             /* encryption scheme not supported */
             goto failure;
     }
     switch (this->scheme)
     {
         case PKCS5_SCHEME_PBES1:
         case PKCS5_SCHEME_PKCS12:
             if (!parse_pbes1_params(this, params, level0))
             {
                 goto failure;
             }
             break;
         case PKCS5_SCHEME_PBES2:
             if (!parse_pbes2_params(this, params, level0))
             {
                 goto failure;
             }
             break;
     }
     return &this->public;
 failure:
     destroy(this);
     return NULL;
 }