strongSwan: eap_simaka_pseudonym_card
eap_simaka_pseudonym_card
eap_simaka_pseudonym
Classes
struct eap_simaka_pseudonym_card_t
Typedefs
typedef struct
eap_simaka_pseudonym_card_t eap_simaka_pseudonym_card_t
Functions
eap_simaka_pseudonym_card_t * eap_simaka_pseudonym_card_create ()
Detailed Description
Typedef Documentation
typedef struct eap_simaka_pseudonym_card_t eap_simaka_pseudonym_card_t
Definition at line 26 of file eap_simaka_pseudonym_card.h.
Function Documentation
eap_simaka_pseudonym_card_t* eap_simaka_pseudonym_card_create ()
Create a eap_simaka_pseudonym_card instance.
See header
Definition at line 127 of file eap_simaka_pseudonym_card.c.
References equals(), hash(), hashtable_create(), INIT, nop(), return_false(), and return_null().
Referenced by get_card().
 {
     private_eap_simaka_pseudonym_card_t *this;
     INIT(this,
         .public = {
             .card = {
                 .get_triplet = (void*)return_false,
                 .get_quintuplet = _get_quintuplet,
                 .resync = (void*)return_false,
                 .get_pseudonym = _get_pseudonym,
                 .set_pseudonym = _set_pseudonym,
                 .get_reauth = (void*)return_null,
                 .set_reauth = (void*)nop,
             },
             .destroy = _destroy,
         },
         .pseudonym = hashtable_create((void*)hash, (void*)equals, 0),
         .permanent = hashtable_create((void*)hash, (void*)equals, 0),
     );
     return &this->public;
 }