strongSwan: farp_spoofer.c File Reference
farp_spoofer.c File Reference
#include "farp_spoofer.h"
#include <errno.h>
#include <unistd.h>
#include <sys/socket.h>
#include <linux/if_arp.h>
#include <linux/if_ether.h>
#include <linux/filter.h>
#include <sys/ioctl.h>
#include <daemon.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_farp_spoofer_t
Typedefs
typedef struct
private_farp_spoofer_t private_farp_spoofer_t
Functions
struct __attribute__ ((packed))
static void send_arp (private_farp_spoofer_t *this, arp_t *arp, struct sockaddr_ll *addr)
static bool receive_arp (private_farp_spoofer_t *this)
METHOD (farp_spoofer_t, destroy, void, private_farp_spoofer_t *this)
farp_spoofer_t * farp_spoofer_create (farp_listener_t *listener)
Variables
arp_t
Typedef Documentation
typedef struct private_farp_spoofer_t private_farp_spoofer_t
Definition at line 30 of file farp_spoofer.c.
Function Documentation
METHOD (farp_spoofer_t , destroy , void , private_farp_spoofer_t * this)
Definition at line 126 of file farp_spoofer.c.
References close, free(), lib, watcher_t::remove, and library_t::watcher.
 {
     lib->watcher->remove(lib->watcher, this->skt);
     close(this->skt);
     free(this);
 }
static bool receive_arp (private_farp_spoofer_t * this) static
ARP request receiving
Definition at line 99 of file farp_spoofer.c.
References addr, arp_t, chunk_create(), host_t::destroy, host_create_from_chunk(), len, listener, MSG_DONTWAIT, recvfrom, send_arp(), and TRUE.
Referenced by farp_spoofer_create().
 {
     struct sockaddr_ll addr;
     socklen_t addr_len = sizeof(addr);
     arp_t arp;
     ssize_t len;
     host_t *local, *remote;
     len = recvfrom(this->skt, &arp, sizeof(arp), MSG_DONTWAIT,
                    (struct sockaddr*)&addr, &addr_len);
     if (len == sizeof(arp))
     {
         local = host_create_from_chunk(AF_INET,
                                     chunk_create((char*)&arp.sender_ip, 4), 0);
         remote = host_create_from_chunk(AF_INET,
                                     chunk_create((char*)&arp.target_ip, 4), 0);
         if (this->listener->has_tunnel(this->listener, local, remote))
         {
             send_arp(this, &arp, &addr);
         }
         local->destroy(local);
         remote->destroy(remote);
     }
     return TRUE;
 }
static void send_arp (private_farp_spoofer_t * this, arp_t * arp, struct sockaddr_ll * addr) static
Send faked ARP response
Definition at line 71 of file farp_spoofer.c.
References memcpy, and sendto.
Referenced by receive_arp().
 {
     struct ifreq req;
     char tmp[4];
     req.ifr_ifindex = addr->sll_ifindex;
     if (ioctl(this->skt, SIOCGIFNAME, &req) == 0 &&
         ioctl(this->skt, SIOCGIFHWADDR, &req) == 0 &&
         req.ifr_hwaddr.sa_family == ARPHRD_ETHER)
     {
         memcpy(arp->target_mac, arp->sender_mac, 6);
         memcpy(arp->sender_mac, req.ifr_hwaddr.sa_data, 6);
         memcpy(tmp, arp->sender_ip, 4);
         memcpy(arp->sender_ip, arp->target_ip, 4);
         memcpy(arp->target_ip, tmp, 4);
         arp->opcode = htons(ARPOP_REPLY);
         sendto(this->skt, arp, sizeof(*arp), 0,
                (struct sockaddr*)addr, sizeof(*addr));
     }
 }
Variable Documentation
arp_t
Definition at line 66 of file farp_spoofer.c.
Referenced by farp_spoofer_create(), and receive_arp().