strongSwan: charon-tkm.c File Reference
charon-tkm.c File Reference
#include <stdio.h>
#include <syslog.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <libgen.h>
#include <errno.h>
#include <hydra.h>
#include <daemon.h>
#include <library.h>
#include <utils/backtrace.h>
#include <threading/thread.h>
#include <sa/keymat.h>
#include <credentials/credential_manager.h>
#include "tkm.h"
#include "tkm_nonceg.h"
#include "tkm_diffie_hellman.h"
#include "tkm_keymat.h"
#include "tkm_listener.h"
#include "tkm_kernel_ipsec.h"
#include "tkm_public_key.h"
#include "tkm_cred.h"
#include "tkm_encoder.h"
#include "tkm_spi_generator.h"
Macros
#define _GNU_SOURCE
Functions
static void dbg_syslog (debug_t group, level_t level, char *fmt,...)
static void run ()
static void segv_handler (int signal)
static bool lookup_uid_gid ()
static bool check_pidfile ()
static void unlink_pidfile ()
int main (int argc, char *argv[])
Variables
static tkm_listener_t * listener
static char * pidfile_name = NULL
static FILE * pidfile = NULL
void(* dbg)(debug_t group, level_t level, char *fmt,...)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 18 of file charon-tkm.c.
Function Documentation
static bool check_pidfile () static
Check/create PID file, return TRUE if already running
Definition at line 171 of file charon-tkm.c.
References library_t::caps, DBG1, DBG_DMN, FALSE, fprintf, capabilities_t::get_gid, capabilities_t::get_uid, ignore_result, lib, memset, pidfile, pidfile_name, and TRUE.
Referenced by main().
 {
     struct stat stb;
     if (stat(pidfile_name, &stb) == 0)
     {
         pidfile = fopen(pidfile_name, "r");
         if (pidfile)
         {
             char buf[64];
             pid_t pid = 0;
             memset(buf, 0, sizeof(buf));
             if (fread(buf, 1, sizeof(buf), pidfile))
             {
                 buf[sizeof(buf) - 1] = '\0';
                 pid = atoi(buf);
             }
             fclose(pidfile);
             if (pid && kill(pid, 0) == 0)
             {   /* such a process is running */
                 return TRUE;
             }
         }
         DBG1(DBG_DMN, "removing pidfile '%s', process not running", pidfile_name);
         unlink(pidfile_name);
     }
     /* create new pidfile */
     pidfile = fopen(pidfile_name, "w");
     if (pidfile)
     {
         ignore_result(fchown(fileno(pidfile),
                              lib->caps->get_uid(lib->caps),
                              lib->caps->get_gid(lib->caps)));
         fprintf(pidfile, "%d\n", getpid());
         fflush(pidfile);
     }
     return FALSE;
 }
static void dbg_syslog (debug_t group, level_t level, char * fmt, ...) static
Simple logging hook for library logs, using syslog output
Definition at line 71 of file charon-tkm.c.
References debug_names, enum_name_t::names, and vsnprintf.
Referenced by main().
 {
     if (level <= 1)
     {
         char buffer[8192];
         va_list args;
         va_start(args, fmt);
         /* write in memory buffer first */
         vsnprintf(buffer, sizeof(buffer), fmt, args);
         syslog(LOG_DAEMON|LOG_INFO, "00[%s] %s", debug_names->names[group],
                 buffer);
         va_end(args);
     }
 }
static bool lookup_uid_gid () static
Lookup UID and GID
Definition at line 151 of file charon-tkm.c.
References library_t::caps, FALSE, IPSEC_GROUP, IPSEC_USER, lib, capabilities_t::resolve_gid, capabilities_t::resolve_uid, and TRUE.
Referenced by main().
 {
 #ifdef IPSEC_USER
     if (!lib->caps->resolve_uid(lib->caps, IPSEC_USER))
     {
         return FALSE;
     }
 #endif
 #ifdef IPSEC_GROUP
     if (!lib->caps->resolve_gid(lib->caps, IPSEC_GROUP))
     {
         return FALSE;
     }
 #endif
     return TRUE;
 }
int main (int argc, char * argv[])
Main function, starts TKM backend.
Definition at line 231 of file charon-tkm.c.
References cred_encoding_t::add_encoder, bus_t::add_listener, credential_manager_t::add_set, plugin_loader_t::add_static_features, asprintf(), daemon_t::bus, library_t::caps, charon, check_pidfile(), countof, library_t::credmgr, creds, dbg, DBG1, DBG_DMN, dbg_syslog(), tkm_listener_t::destroy, tkm_cred_t::destroy, destroy_dh_mapping(), capabilities_t::drop, library_t::encoding, FALSE, features, settings_t::get_int, IKEV2, daemon_t::initialize, kernel_ipsec_register(), KEY_RSA, keymat_register_constructor(), LEVEL_CTRL, lib, libcharon_deinit(), libcharon_init(), libhydra_deinit(), libhydra_init(), library_deinit(), library_init(), tkm_listener_t::listener, daemon_t::load_loggers, lookup_uid_gid(), pidfile_name, PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, PLUGIN_REGISTER, PLUGINS, library_t::plugins, register_dh_mapping(), cred_encoding_t::remove_encoder, bus_t::remove_listener, run(), segv_handler(), settings_t::set_bool, settings_t::set_int, library_t::settings, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA256, SS_RC_INITIALIZATION_FAILED, daemon_t::start, status, plugin_loader_t::status, tkm_cred_create(), tkm_deinit(), tkm_encoder_encode(), tkm_init(), tkm_kernel_ipsec_create(), tkm_keymat_create(), tkm_listener_create(), tkm_nonceg_create(), tkm_public_key_load(), tkm_spi_generator_register(), TRUE, and unlink_pidfile().
 {
     char *dmn_name;
     if (argc > 0 && strlen(argv[0]) > 0)
     {
         dmn_name = basename(argv[0]);
     }
     else
     {
         dmn_name = "charon-tkm";
     }
     /* TKM credential set */
     tkm_cred_t *creds;
     struct sigaction action;
     int status = SS_RC_INITIALIZATION_FAILED;
     /* logging for library during initialization, as we have no bus yet */
     dbg = dbg_syslog;
     /* initialize library */
     if (!library_init(NULL, dmn_name))
     {
         library_deinit();
         exit(status);
     }
     if (!libhydra_init())
     {
         dbg_syslog(DBG_DMN, 1, "initialization failed - aborting %s", dmn_name);
         libhydra_deinit();
         library_deinit();
         exit(status);
     }
     if (!libcharon_init())
     {
         dbg_syslog(DBG_DMN, 1, "initialization failed - aborting %s", dmn_name);
         goto deinit;
     }
     if (!lookup_uid_gid())
     {
         dbg_syslog(DBG_DMN, 1, "invalid uid/gid - aborting %s", dmn_name);
         goto deinit;
     }
     /* the authorize hook currently does not support RFC 7427 signature auth */
     lib->settings->set_bool(lib->settings, "%s.signature_authentication", FALSE,
                             dmn_name);
     /* make sure we log to the DAEMON facility by default */
     lib->settings->set_int(lib->settings, "%s.syslog.daemon.default",
             lib->settings->get_int(lib->settings, "%s.syslog.daemon.default", 1,
                                    dmn_name), dmn_name);
     charon->load_loggers(charon, NULL, FALSE);
     DBG1(DBG_DMN, "Starting charon with TKM backend (strongSwan "VERSION")");
     /* register TKM specific plugins */
     static plugin_feature_t features[] = {
         PLUGIN_REGISTER(NONCE_GEN, tkm_nonceg_create),
             PLUGIN_PROVIDE(NONCE_GEN),
         PLUGIN_REGISTER(PUBKEY, tkm_public_key_load, TRUE),
             PLUGIN_PROVIDE(PUBKEY, KEY_RSA),
             PLUGIN_PROVIDE(PUBKEY_VERIFY, SIGN_RSA_EMSA_PKCS1_SHA1),
             PLUGIN_PROVIDE(PUBKEY_VERIFY, SIGN_RSA_EMSA_PKCS1_SHA256),
         PLUGIN_CALLBACK(kernel_ipsec_register, tkm_kernel_ipsec_create),
             PLUGIN_PROVIDE(CUSTOM, "kernel-ipsec"),
         PLUGIN_CALLBACK(tkm_spi_generator_register, NULL),
             PLUGIN_PROVIDE(CUSTOM, "tkm-spi-generator"),
                 PLUGIN_DEPENDS(CUSTOM, "libcharon-sa-managers"),
     };
     lib->plugins->add_static_features(lib->plugins, "tkm-backend", features,
             countof(features), TRUE, NULL, NULL);
     if (!register_dh_mapping())
     {
         DBG1(DBG_DMN, "no DH group mapping defined - aborting %s", dmn_name);
         goto deinit;
     }
     /* register TKM keymat variant */
     keymat_register_constructor(IKEV2, (keymat_constructor_t)tkm_keymat_create);
     /* initialize daemon */
     if (!charon->initialize(charon, PLUGINS))
     {
         DBG1(DBG_DMN, "initialization failed - aborting %s", dmn_name);
         goto deinit;
     }
     lib->plugins->status(lib->plugins, LEVEL_CTRL);
     /* set global pidfile name depending on daemon name */
     if (asprintf(&pidfile_name, IPSEC_PIDDIR"/%s.pid", dmn_name) < 0)
     {
         DBG1(DBG_DMN, "unable to set pidfile name - aborting %s", dmn_name);
         goto deinit;
     };
     if (check_pidfile())
     {
         DBG1(DBG_DMN, "%s already running (\"%s\" exists)", dmn_name,
              pidfile_name);
         goto deinit;
     }
     if (!lib->caps->drop(lib->caps))
     {
         DBG1(DBG_DMN, "capability dropping failed - aborting %s", dmn_name);
         goto deinit;
     }
     /* initialize TKM client */
     if (!tkm_init())
     {
         DBG1(DBG_DMN, "init of TKM client failed - aborting %s", dmn_name);
         goto deinit;
     }
     /* register TKM authorization hook */
     listener = tkm_listener_create();
     charon->bus->add_listener(charon->bus, &listener->listener);
     /* register TKM credential set */
     creds = tkm_cred_create();
     lib->credmgr->add_set(lib->credmgr, (credential_set_t*)creds);
     /* register TKM credential encoder */
     lib->encoding->add_encoder(lib->encoding, tkm_encoder_encode);
     /* add handler for SEGV and ILL,
      * INT and TERM are handled by sigwaitinfo() in run() */
     action.sa_handler = segv_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaddset(&action.sa_mask, SIGINT);
     sigaddset(&action.sa_mask, SIGTERM);
     sigaction(SIGSEGV, &action, NULL);
     sigaction(SIGILL, &action, NULL);
     sigaction(SIGBUS, &action, NULL);
     action.sa_handler = SIG_IGN;
     sigaction(SIGPIPE, &action, NULL);
     pthread_sigmask(SIG_SETMASK, &action.sa_mask, NULL);
     /* start daemon (i.e. the threads in the thread-pool) */
     charon->start(charon);
     /* main thread goes to run loop */
     run();
     unlink_pidfile();
     status = 0;
     charon->bus->remove_listener(charon->bus, &listener->listener);
     listener->destroy(listener);
     creds->destroy(creds);
     lib->encoding->remove_encoder(lib->encoding, tkm_encoder_encode);
 deinit:
     destroy_dh_mapping();
     libcharon_deinit();
     libhydra_deinit();
     library_deinit();
     tkm_deinit();
     return status;
 }
static void run () static
Run the daemon and handle unix signals
Definition at line 90 of file charon-tkm.c.
References bus_t::alert, ALERT_SHUTDOWN_SIGNAL, daemon_t::bus, charon, DBG1, DBG_DMN, sig, sigwaitinfo(), strerror, and TRUE.
Referenced by main().
 {
     sigset_t set;
     /* handle SIGINT and SIGTERM in this handler */
     sigemptyset(&set);
     sigaddset(&set, SIGINT);
     sigaddset(&set, SIGTERM);
     sigprocmask(SIG_BLOCK, &set, NULL);
     while (TRUE)
     {
         int sig;
         sig = sigwaitinfo(&set, NULL);
         if (sig == -1)
         {
             if (errno == EINTR)
             {   /* ignore signals we didn't wait for */
                 continue;
             }
             DBG1(DBG_DMN, "waiting for signal failed: %s", strerror(errno));
             return;
         }
         switch (sig)
         {
             case SIGINT:
             {
                 DBG1(DBG_DMN, "signal of type SIGINT received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return;
             }
             case SIGTERM:
             {
                 DBG1(DBG_DMN, "signal of type SIGTERM received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return;
             }
         }
     }
 }
static void segv_handler (int signal) static
Handle SIGSEGV/SIGILL signals raised by threads
Definition at line 135 of file charon-tkm.c.
References backtrace, backtrace_create(), DBG1, DBG_DMN, backtrace_t::destroy, backtrace_t::log, thread_current_id(), and TRUE.
Referenced by main().
 {
     backtrace_t *backtrace;
     DBG1(DBG_DMN, "thread %u received %d", thread_current_id(), signal);
     backtrace = backtrace_create(2);
     backtrace->log(backtrace, stderr, TRUE);
     backtrace->destroy(backtrace);
     DBG1(DBG_DMN, "killing ourself, received critical signal");
     abort();
 }
static void unlink_pidfile () static
Delete/truncate the PID file
Definition at line 215 of file charon-tkm.c.
References ignore_result, pidfile, and pidfile_name.
Referenced by main().
 {
     /* because unlinking the PID file may fail, we truncate it to ensure the
      * daemon can be properly restarted.  one probable cause for this is the
      * combination of not running as root and the effective user lacking
      * permissions on the parent dir(s) of the PID file */
     if (pidfile)
     {
         ignore_result(ftruncate(fileno(pidfile), 0));
         fclose(pidfile);
     }
     unlink(pidfile_name);
 }
Variable Documentation
void(* dbg)(debug_t group, level_t level, char *fmt,...)
Hook in library for debugging messages
The registered debug hook.
Definition at line 111 of file debug.c.
Referenced by main().
tkm_listener_t* listener static
TKM bus listener for IKE authorize events.
Definition at line 51 of file charon-tkm.c.
Referenced by certexpire_plugin_create(), disconnect_async(), do_load_test(), duplicheck_plugin_create(), error_notify_plugin_create(), farp_plugin_create(), farp_spoofer_create(), forecast_forwarder_create(), forecast_plugin_create(), list(), lookip_plugin_create(), lookip_socket_create(), METHOD(), on_accept(), open_database(), plugin_cb(), query(), receive_arp(), register_forecast(), register_load_tester(), register_tnc_ifmap(), subscribe(), wait_for_listener(), whitelist_control_create(), and whitelist_plugin_create().
FILE* pidfile = NULL static
Global reference to PID file (required to truncate, if undeletable)
Definition at line 61 of file charon-tkm.c.
Referenced by check_pidfile(), and unlink_pidfile().
char* pidfile_name = NULL static
PID file, in which charon-tkm stores its process id
Definition at line 56 of file charon-tkm.c.
Referenced by check_pidfile(), main(), and unlink_pidfile().