strongSwan: eap_radius_accounting
eap_radius_accounting
eap_radius
Classes
struct eap_radius_accounting_t
Typedefs
typedef struct
eap_radius_accounting_t eap_radius_accounting_t
Functions
eap_radius_accounting_t * eap_radius_accounting_create ()
void eap_radius_accounting_start_interim (ike_sa_t *ike_sa, u_int32_t interval)
Detailed Description
Typedef Documentation
typedef struct eap_radius_accounting_t eap_radius_accounting_t
Definition at line 26 of file eap_radius_accounting.h.
Function Documentation
eap_radius_accounting_t* eap_radius_accounting_create ()
Create a eap_radius_accounting instance.
See header
Definition at line 1004 of file eap_radius_accounting.c.
References bus_t::add_listener, daemon_t::bus, charon, equals(), FALSE, settings_t::get_bool, hash(), hashtable_create(), INIT, lib, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, library_t::settings, and TRUE.
Referenced by plugin_cb().
 {
     private_eap_radius_accounting_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .alert = _alert,
                 .ike_updown = _ike_updown,
                 .ike_rekey = _ike_rekey,
                 .message = _message_hook,
                 .assign_vips = _assign_vips,
                 .child_updown = _child_updown,
                 .child_rekey = _child_rekey,
                 .children_migrate = _children_migrate,
             },
             .destroy = _destroy,
         },
         /* use system time as Session ID prefix */
         .prefix = (u_int32_t)time(NULL),
         .sessions = hashtable_create((hashtable_hash_t)hash,
                                      (hashtable_equals_t)equals, 32),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     if (lib->settings->get_bool(lib->settings,
                 "%s.plugins.eap-radius.station_id_with_port", TRUE, lib->ns))
     {
         this->station_id_fmt = "%#H";
     }
     else
     {
         this->station_id_fmt = "%H";
     }
     if (lib->settings->get_bool(lib->settings,
                             "%s.plugins.eap-radius.accounting", FALSE, lib->ns))
     {
         singleton = this;
         charon->bus->add_listener(charon->bus, &this->public.listener);
     }
     this->acct_req_vip = lib->settings->get_bool(lib->settings,
                             "%s.plugins.eap-radius.accounting_requires_vip",
                             FALSE, lib->ns);
     return &this->public;
 }
void eap_radius_accounting_start_interim (ike_sa_t * ike_sa, u_int32_t interval)
Schedule Accounting interim updates for the given IKE_SA.
Parameters
ike_sa IKE_SA to send updates for
interval interval for interim updates
See header
Definition at line 1053 of file eap_radius_accounting.c.
References DBG1, DBG_CFG, ike_sa_t::get_id, get_or_create_entry(), ike_sa_t::get_unique_id, entry_t::interim, entry_t::interval, mutex_t::lock, private_eap_radius_accounting_t::mutex, and mutex_t::unlock.
Referenced by process_timeout().
 {
     if (singleton)
     {
         entry_t *entry;
         DBG1(DBG_CFG, "scheduling RADIUS Interim-Updates every %us", interval);
         singleton->mutex->lock(singleton->mutex);
         entry = get_or_create_entry(singleton, ike_sa->get_id(ike_sa),
                                     ike_sa->get_unique_id(ike_sa));
         entry->interim.interval = interval;
         singleton->mutex->unlock(singleton->mutex);
     }
 }