strongSwan: kernel_pfroute_net.c File Reference
kernel_pfroute_net.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <net/if.h>
#include <net/if_dl.h>
#include <ifaddrs.h>
#include <net/route.h>
#include <unistd.h>
#include <errno.h>
#include "kernel_pfroute_net.h"
#include <hydra.h>
#include <utils/debug.h>
#include <networking/host.h>
#include <networking/tun_device.h>
#include <threading/thread.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <threading/rwlock.h>
#include <threading/spinlock.h>
#include <collections/hashtable.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
Classes
struct addr_entry_t
struct iface_entry_t
struct addr_map_entry_t
struct route_entry_t
struct net_change_t
struct private_kernel_pfroute_net_t
struct rt_enumerator_t
struct address_enumerator_t
Macros
#define SA_ALIGN sizeof(long)
#define SA_LEN(len) ((len) > 0 ? (((len)+SA_ALIGN-1) & ~(SA_ALIGN-1)) : SA_ALIGN)
#define ROAM_DELAY 100
#define ROUTE_DELAY 100
Typedefs
typedef struct addr_entry_t addr_entry_t
typedef struct iface_entry_t iface_entry_t
typedef struct addr_map_entry_t addr_map_entry_t
typedef struct route_entry_t route_entry_t
typedef struct net_change_t net_change_t
typedef struct
private_kernel_pfroute_net_t private_kernel_pfroute_net_t
Functions
static void addr_entry_destroy (addr_entry_t *this)
static void iface_entry_destroy (iface_entry_t *this)
static bool iface_entry_up (iface_entry_t *iface)
static bool iface_entry_up_and_usable (iface_entry_t *iface)
static u_int addr_map_entry_hash (addr_map_entry_t *this)
static bool addr_map_entry_equals (addr_map_entry_t *a, addr_map_entry_t *b)
static bool addr_map_entry_match_up_and_usable (addr_map_entry_t *a, addr_map_entry_t *b)
static bool addr_map_entry_match_virtual (addr_map_entry_t *a, addr_map_entry_t *b)
static bool addr_map_entry_match_up (addr_map_entry_t *a, addr_map_entry_t *b)
static route_entry_t * route_entry_clone (route_entry_t *this)
static void route_entry_destroy (route_entry_t *this)
static u_int route_entry_hash (route_entry_t *this)
static bool route_entry_equals (route_entry_t *a, route_entry_t *b)
static void net_change_destroy (net_change_t *this)
static u_int net_change_hash (net_change_t *this)
static bool net_change_equals (net_change_t *a, net_change_t *b)
static status_t manage_route (private_kernel_pfroute_net_t *this, int op, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, char *if_name)
static void net_changes_clear (private_kernel_pfroute_net_t *this)
static job_requeue_t reinstall_routes (private_kernel_pfroute_net_t *this)
static void queue_route_reinstall (private_kernel_pfroute_net_t *this, char *if_name)
static void addr_map_entry_add (private_kernel_pfroute_net_t *this, addr_entry_t *addr, iface_entry_t *iface)
static void addr_map_entry_remove (addr_entry_t *addr, iface_entry_t *iface, private_kernel_pfroute_net_t *this)
static job_requeue_t roam_event (private_kernel_pfroute_net_t *this)
static void fire_roam_event (private_kernel_pfroute_net_t *this, bool address)
METHOD (enumerator_t, rt_enumerate, bool, rt_enumerator_t *this, int *xtype, struct sockaddr **addr)
static enumerator_t * create_rt_enumerator (int types, int remaining, struct sockaddr *addr)
static enumerator_t * create_rtmsg_enumerator (struct rt_msghdr *hdr)
static enumerator_t * create_ifamsg_enumerator (struct ifa_msghdr *hdr)
static void process_addr (private_kernel_pfroute_net_t *this, struct ifa_msghdr *ifa)
static void repopulate_iface (private_kernel_pfroute_net_t *this, iface_entry_t *iface)
static void process_link (private_kernel_pfroute_net_t *this, struct if_msghdr *msg)
static void process_route (private_kernel_pfroute_net_t *this, struct rt_msghdr *msg)
static bool receive_events (private_kernel_pfroute_net_t *this, int fd, watcher_event_t event)
static void address_enumerator_destroy (address_enumerator_t *data)
static bool filter_addresses (address_enumerator_t *data, addr_entry_t **in, host_t **out)
static enumerator_t * create_iface_enumerator (iface_entry_t *iface, address_enumerator_t *data)
static bool filter_interfaces (address_enumerator_t *data, iface_entry_t **in, iface_entry_t **out)
METHOD (kernel_net_t, create_address_enumerator, enumerator_t *, private_kernel_pfroute_net_t *this, kernel_address_type_t which)
METHOD (kernel_net_t, get_features, kernel_feature_t, private_kernel_pfroute_net_t *this)
METHOD (kernel_net_t, get_interface_name, bool, private_kernel_pfroute_net_t *this, host_t *ip, char **name)
METHOD (kernel_net_t, add_ip, status_t, private_kernel_pfroute_net_t *this, host_t *vip, int prefix, char *ifname)
METHOD (kernel_net_t, del_ip, status_t, private_kernel_pfroute_net_t *this, host_t *vip, int prefix, bool wait)
static void add_rt_addr (struct rt_msghdr *hdr, int type, host_t *addr)
static void add_rt_mask (struct rt_msghdr *hdr, int type, int family, int prefix)
static void add_rt_ifname (struct rt_msghdr *hdr, int type, char *name)
METHOD (kernel_net_t, add_route, status_t, private_kernel_pfroute_net_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
METHOD (kernel_net_t, del_route, status_t, private_kernel_pfroute_net_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
static host_t * get_route (private_kernel_pfroute_net_t *this, bool nexthop, host_t *dest, host_t *src)
METHOD (kernel_net_t, get_source_addr, host_t *, private_kernel_pfroute_net_t *this, host_t *dest, host_t *src)
METHOD (kernel_net_t, get_nexthop, host_t *, private_kernel_pfroute_net_t *this, host_t *dest, int prefix, host_t *src)
static status_t init_address_list (private_kernel_pfroute_net_t *this)
METHOD (kernel_net_t, destroy, void, private_kernel_pfroute_net_t *this)
kernel_pfroute_net_t * kernel_pfroute_net_create ()
Macro Definition Documentation
#define ROAM_DELAY 100
delay before firing roam events (ms)
Definition at line 55 of file kernel_pfroute_net.c.
Referenced by fire_roam_event().
#define ROUTE_DELAY 100
delay before reinstalling routes (ms)
Definition at line 58 of file kernel_pfroute_net.c.
Referenced by queue_route_reinstall().
#define SA_ALIGN sizeof(long)
properly align sockaddrs
Definition at line 50 of file kernel_pfroute_net.c.
#define SA_LEN (len) ((len) > 0 ? (((len)+SA_ALIGN-1) & ~(SA_ALIGN-1)) : SA_ALIGN)
Definition at line 52 of file kernel_pfroute_net.c.
Referenced by add_rt_addr(), add_rt_ifname(), and METHOD().
Typedef Documentation
typedef struct addr_entry_t addr_entry_t
Definition at line 60 of file kernel_pfroute_net.c.
typedef struct addr_map_entry_t addr_map_entry_t
Definition at line 131 of file kernel_pfroute_net.c.
typedef struct iface_entry_t iface_entry_t
Definition at line 83 of file kernel_pfroute_net.c.
typedef struct net_change_t net_change_t
Definition at line 265 of file kernel_pfroute_net.c.
typedef struct private_kernel_pfroute_net_t private_kernel_pfroute_net_t
Definition at line 300 of file kernel_pfroute_net.c.
typedef struct route_entry_t route_entry_t
Definition at line 196 of file kernel_pfroute_net.c.
Function Documentation
static void add_rt_addr (struct rt_msghdr * hdr, int type, host_t * addr) static
Append a sockaddr_in/in6 of given type to routing message
Definition at line 1333 of file kernel_pfroute_net.c.
References host_t::get_sockaddr, host_t::get_sockaddr_len, len, memcpy, SA_LEN, and type.
Referenced by add_rt_mask(), get_route(), and manage_route().
 {
     if (addr)
     {
         int len;
         len = *addr->get_sockaddr_len(addr);
         memcpy((char*)hdr + hdr->rtm_msglen, addr->get_sockaddr(addr), len);
         hdr->rtm_msglen += SA_LEN(len);
         hdr->rtm_addrs |= type;
     }
 }
static void add_rt_ifname (struct rt_msghdr * hdr, int type, char * name) static
Append an interface name sockaddr_dl to routing message
Definition at line 1364 of file kernel_pfroute_net.c.
References memcpy, SA_LEN, and type.
Referenced by get_route(), and manage_route().
 {
     struct sockaddr_dl sdl = {
         .sdl_len = sizeof(struct sockaddr_dl),
         .sdl_family = AF_LINK,
         .sdl_nlen = strlen(name),
     };
     if (strlen(name) <= sizeof(sdl.sdl_data))
     {
         memcpy(sdl.sdl_data, name, sdl.sdl_nlen);
         memcpy((char*)hdr + hdr->rtm_msglen, &sdl, sdl.sdl_len);
         hdr->rtm_msglen += SA_LEN(sdl.sdl_len);
         hdr->rtm_addrs |= type;
     }
 }
static void add_rt_mask (struct rt_msghdr * hdr, int type, int family, int prefix) static
Append a subnet mask sockaddr using the given prefix to routing message
Definition at line 1349 of file kernel_pfroute_net.c.
References add_rt_addr(), host_t::destroy, host_create_netmask(), and mask.
Referenced by manage_route().
 {
     host_t *mask;
     mask = host_create_netmask(family, prefix);
     if (mask)
     {
         add_rt_addr(hdr, type, mask);
         mask->destroy(mask);
     }
 }
static void addr_entry_destroy (addr_entry_t * this) static
destroy a addr_entry_t object
Definition at line 77 of file kernel_pfroute_net.c.
References free(), and ip.
Referenced by iface_entry_destroy(), process_addr(), and repopulate_iface().
 {
     this->ip->destroy(this->ip);
     free(this);
 }
static void addr_map_entry_add (private_kernel_pfroute_net_t * this, addr_entry_t * addr, iface_entry_t * iface) static
Add an address map entry
Definition at line 516 of file kernel_pfroute_net.c.
References free(), INIT, ip, and addr_entry_t::ip.
Referenced by init_address_list(), process_addr(), and repopulate_iface().
 {
     addr_map_entry_t *entry;
     INIT(entry,
         .ip = addr->ip,
         .addr = addr,
         .iface = iface,
     );
     entry = this->addrs->put(this->addrs, entry, entry);
     free(entry);
 }
static bool addr_map_entry_equals (addr_map_entry_t * a, addr_map_entry_t * b) static
Compare two addr_map_entry_t objects, two entries are equal if they are installed on the same interface
Definition at line 160 of file kernel_pfroute_net.c.
References addr_map_entry_t::iface, iface_entry_t::ifindex, addr_map_entry_t::ip, and host_t::ip_equals.
Referenced by kernel_pfroute_net_create().
 {
     return a->iface->ifindex == b->iface->ifindex &&
            a->ip->ip_equals(a->ip, b->ip);
 }
static u_int addr_map_entry_hash (addr_map_entry_t * this) static
Hash a addr_map_entry_t object, all entries with the same IP address are stored in the same bucket
Definition at line 151 of file kernel_pfroute_net.c.
References chunk_hash(), and ip.
Referenced by kernel_pfroute_net_create().
 {
     return chunk_hash(this->ip->get_address(this->ip));
 }
static bool addr_map_entry_match_up (addr_map_entry_t * a, addr_map_entry_t * b) static
Used with get_match this finds an address entry if it is installed on any active local interface
Definition at line 190 of file kernel_pfroute_net.c.
References addr_map_entry_t::addr, addr_map_entry_t::iface, iface_entry_up(), addr_map_entry_t::ip, host_t::ip_equals, and addr_entry_t::virtual.
Referenced by METHOD().
 {
     return !b->addr->virtual && iface_entry_up(b->iface) &&
             a->ip->ip_equals(a->ip, b->ip);
 }
static bool addr_map_entry_match_up_and_usable (addr_map_entry_t * a, addr_map_entry_t * b) static
Used with get_match this finds an address entry if it is installed on an up and usable interface
Definition at line 170 of file kernel_pfroute_net.c.
References addr_map_entry_t::addr, addr_map_entry_t::iface, iface_entry_up_and_usable(), addr_map_entry_t::ip, host_t::ip_equals, and addr_entry_t::virtual.
Referenced by get_route(), and METHOD().
 {
     return !b->addr->virtual && iface_entry_up_and_usable(b->iface) &&
             a->ip->ip_equals(a->ip, b->ip);
 }
static bool addr_map_entry_match_virtual (addr_map_entry_t * a, addr_map_entry_t * b) static
Used with get_match this finds an address entry if it is installed as virtual IP address
Definition at line 181 of file kernel_pfroute_net.c.
References addr_map_entry_t::addr, addr_map_entry_t::ip, host_t::ip_equals, and addr_entry_t::virtual.
Referenced by METHOD().
 {
     return b->addr->virtual && a->ip->ip_equals(a->ip, b->ip);
 }
static void addr_map_entry_remove (addr_entry_t * addr, iface_entry_t * iface, private_kernel_pfroute_net_t * this) static
Remove an address map entry (the argument order is a bit strange because it is also used with linked_list_t.invoke_function)
Definition at line 534 of file kernel_pfroute_net.c.
References addr, free(), addr_entry_t::ip, and lookup.
Referenced by process_addr(), and repopulate_iface().
 {
     addr_map_entry_t *entry, lookup = {
         .ip = addr->ip,
         .addr = addr,
         .iface = iface,
     };
     entry = this->addrs->remove(this->addrs, &lookup);
     free(entry);
 }
static void address_enumerator_destroy (address_enumerator_t * data) static
cleanup function for address enumerator
Definition at line 1055 of file kernel_pfroute_net.c.
References free(), private_kernel_netlink_net_t::lock, address_enumerator_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static enumerator_t* create_iface_enumerator (iface_entry_t * iface, address_enumerator_t * data) static
enumerator constructor for interfaces
Definition at line 1092 of file kernel_pfroute_net.c.
References iface_entry_t::addrs, linked_list_t::create_enumerator, enumerator_create_filter(), and filter_addresses().
Referenced by METHOD().
 {
     return enumerator_create_filter(iface->addrs->create_enumerator(iface->addrs),
                                     (void*)filter_addresses, data, NULL);
 }
static enumerator_t* create_ifamsg_enumerator (struct ifa_msghdr * hdr) static
Create a safe enumerator over sockaddrs in ifa_msghdr
Definition at line 661 of file kernel_pfroute_net.c.
References create_rt_enumerator().
Referenced by process_addr().
 {
     return create_rt_enumerator(hdr->ifam_addrs, hdr->ifam_msglen - sizeof(*hdr),
                                 (struct sockaddr *)(hdr + 1));
 }
static enumerator_t* create_rt_enumerator (int types, int remaining, struct sockaddr * addr) static
Create an enumerator over sockaddrs in rt/if messages
Definition at line 632 of file kernel_pfroute_net.c.
References addr, destroy(), free(), and INIT.
Referenced by create_ifamsg_enumerator(), and create_rtmsg_enumerator().
 {
     rt_enumerator_t *this;
     INIT(this,
         .public = {
             .enumerate = (void*)_rt_enumerate,
             .destroy = (void*)free,
         },
         .types = types,
         .remaining = remaining,
         .addr = addr,
     );
     return &this->public;
 }
static enumerator_t* create_rtmsg_enumerator (struct rt_msghdr * hdr) static
Create a safe enumerator over sockaddrs in rt_msghdr
Definition at line 652 of file kernel_pfroute_net.c.
References create_rt_enumerator().
Referenced by get_route().
 {
     return create_rt_enumerator(hdr->rtm_addrs, hdr->rtm_msglen - sizeof(*hdr),
                                 (struct sockaddr *)(hdr + 1));
 }
static bool filter_addresses (address_enumerator_t * data, addr_entry_t ** in, host_t ** out) static
filter for addresses
Definition at line 1064 of file kernel_pfroute_net.c.
References ADDR_TYPE_REGULAR, ADDR_TYPE_VIRTUAL, FALSE, host_t::get_family, host_t::get_sockaddr, ip, TRUE, and address_enumerator_t::which.
Referenced by create_iface_enumerator().
 {
     host_t *ip;
     if (!(data->which & ADDR_TYPE_VIRTUAL) && (*in)->virtual)
     {   /* skip virtual interfaces added by us */
         return FALSE;
     }
     if (!(data->which & ADDR_TYPE_REGULAR) && !(*in)->virtual)
     {   /* address is regular, but not requested */
         return FALSE;
     }
     ip = (*in)->ip;
     if (ip->get_family(ip) == AF_INET6)
     {
         struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)ip->get_sockaddr(ip);
         if (IN6_IS_ADDR_LINKLOCAL(&sin6->sin6_addr))
         {   /* skip addresses with a unusable scope */
             return FALSE;
         }
     }
     *out = ip;
     return TRUE;
 }
static bool filter_interfaces (address_enumerator_t * data, iface_entry_t ** in, iface_entry_t ** out) static
filter for interfaces
Definition at line 1102 of file kernel_pfroute_net.c.
References ADDR_TYPE_DOWN, ADDR_TYPE_IGNORED, ADDR_TYPE_LOOPBACK, FALSE, in, TRUE, and address_enumerator_t::which.
Referenced by METHOD().
 {
     if (!(data->which & ADDR_TYPE_IGNORED) && !(*in)->usable)
     {   /* skip interfaces excluded by config */
         return FALSE;
     }
     if (!(data->which & ADDR_TYPE_LOOPBACK) && ((*in)->flags & IFF_LOOPBACK))
     {   /* ignore loopback devices */
         return FALSE;
     }
     if (!(data->which & ADDR_TYPE_DOWN) && !((*in)->flags & IFF_UP))
     {   /* skip interfaces not up */
         return FALSE;
     }
     *out = *in;
     return TRUE;
 }
static void fire_roam_event (private_kernel_pfroute_net_t * this, bool address) static
fire a roaming event. we delay it for a bit and fire only one event for multiple calls. otherwise we would create too many events.
Definition at line 566 of file kernel_pfroute_net.c.
References callback_job_create(), lib, ROAM_DELAY, roam_event(), scheduler_t::schedule_job_ms, library_t::scheduler, time_monotonic(), and timeval_add_ms().
Referenced by process_addr(), and process_link().
 {
     timeval_t now;
     job_t *job;
     time_monotonic(&now);
     this->roam_lock->lock(this->roam_lock);
     this->roam_address |= address;
     if (!timercmp(&now, &this->next_roam, >))
     {
         this->roam_lock->unlock(this->roam_lock);
         return;
     }
     timeval_add_ms(&now, ROAM_DELAY);
     this->next_roam = now;
     this->roam_lock->unlock(this->roam_lock);
     job = (job_t*)callback_job_create((callback_job_cb_t)roam_event,
                                       this, NULL, NULL);
     lib->scheduler->schedule_job_ms(lib->scheduler, job, ROAM_DELAY);
 }
static host_t* get_route (private_kernel_pfroute_net_t * this, bool nexthop, host_t * dest, host_t * src) static
Do a route lookup for dest and return either the nexthop or the source address.
Definition at line 1536 of file kernel_pfroute_net.c.
References add_rt_addr(), add_rt_ifname(), addr, addr_map_entry_match_up_and_usable(), host_t::clone, condvar, create_rtmsg_enumerator(), DBG1, DBG2, DBG_KNL, enumerator_t::destroy, host_t::destroy, DESTROY_IF, enumerator_t::enumerate, FALSE, free(), host, host_create_from_sockaddr(), mutex_t::lock, lock, lookup, memset, mutex, ref_get(), RTA_DST, RTAX_MAX, send, seq, condvar_t::signal, socket, strerror, condvar_t::timed_wait, TRUE, type, spinlock_t::unlock, mutex_t::unlock, and condvar_t::wait.
Referenced by METHOD().
 {
     struct {
         struct rt_msghdr hdr;
         char buf[sizeof(struct sockaddr_storage) * RTAX_MAX];
     } msg = {
         .hdr = {
             .rtm_version = RTM_VERSION,
             .rtm_type = RTM_GET,
             .rtm_pid = this->pid,
             .rtm_seq = ref_get(&this->seq),
         },
     };
     host_t *host = NULL;
     enumerator_t *enumerator;
     struct sockaddr *addr;
     bool failed = FALSE;
     int type;
 retry:
     msg.hdr.rtm_msglen = sizeof(struct rt_msghdr);
     for (type = 0; type < RTAX_MAX; type++)
     {
         switch (type)
         {
             case RTAX_DST:
                 add_rt_addr(&msg.hdr, RTA_DST, dest);
                 break;
             case RTAX_IFA:
                 add_rt_addr(&msg.hdr, RTA_IFA, src);
                 break;
             case RTAX_IFP:
                 if (!nexthop)
                 {   /* add an empty IFP to ensure we get a source address */
                     add_rt_ifname(&msg.hdr, RTA_IFP, "");
                 }
                 break;
             default:
                 break;
         }
     }
     this->mutex->lock(this->mutex);
     while (this->waiting_seq)
     {
         this->condvar->wait(this->condvar, this->mutex);
     }
     this->waiting_seq = msg.hdr.rtm_seq;
     if (send(this->socket, &msg, msg.hdr.rtm_msglen, 0) == msg.hdr.rtm_msglen)
     {
         while (TRUE)
         {
             if (this->condvar->timed_wait(this->condvar, this->mutex, 1000))
             {   /* timed out? */
                 break;
             }
             if (!this->reply)
             {
                 continue;
             }
             enumerator = create_rtmsg_enumerator(this->reply);
             while (enumerator->enumerate(enumerator, &type, &addr))
             {
                 if (nexthop)
                 {
                     if (type == RTAX_DST && this->reply->rtm_flags & RTF_HOST)
                     {   /* probably a cloned/cached direct route, only use that
                          * as fallback if no gateway is found */
                         host = host ?: host_create_from_sockaddr(addr);
                     }
                     if (type == RTAX_GATEWAY)
                     {   /* could actually be a MAC address */
                         host_t *gtw = host_create_from_sockaddr(addr);
                         if (gtw)
{
                             DESTROY_IF(host);
                             host = gtw;
                         }
                     }
                 }
                 else
                 {
                     if (type == RTAX_IFA)
                     {
                         host = host_create_from_sockaddr(addr);
                     }
                 }
             }
             enumerator->destroy(enumerator);
             break;
         }
     }
     else
     {
         failed = TRUE;
     }
     free(this->reply);
     this->reply = NULL;
     /* signal completion of query to a waiting thread */
     this->waiting_seq = 0;
     this->condvar->signal(this->condvar);
     this->mutex->unlock(this->mutex);
     if (failed)
     {
         if (src)
         {   /* the given source address might be gone, try again without */
             src = NULL;
             msg.hdr.rtm_seq = ref_get(&this->seq);
             msg.hdr.rtm_addrs = 0;
             memset(msg.buf, 0, sizeof(msg.buf));
             goto retry;
         }
         DBG1(DBG_KNL, "PF_ROUTE lookup failed: %s", strerror(errno));
     }
     if (nexthop)
     {
         host = host ?: dest->clone(dest);
     }
     else
     {   /* make sure the source address is not virtual and usable */
         addr_entry_t *entry, lookup = {
             .ip = host,
         };
         if (!host)
         {
             return NULL;
         }
         this->lock->read_lock(this->lock);
         entry = this->addrs->get_match(this->addrs, &lookup,
                                     (void*)addr_map_entry_match_up_and_usable);
         this->lock->unlock(this->lock);
         if (!entry)
         {
             host->destroy(host);
             return NULL;
         }
     }
     DBG2(DBG_KNL, "using %H as %s to reach %H", host,
          nexthop ? "nexthop" : "address", dest);
     return host;
 }
static void iface_entry_destroy (iface_entry_t * this) static
destroy an interface entry
Definition at line 109 of file kernel_pfroute_net.c.
References addr_entry_destroy(), and free().
Referenced by METHOD().
 {
     this->addrs->destroy_function(this->addrs, (void*)addr_entry_destroy);
     free(this);
 }
static bool iface_entry_up (iface_entry_t * iface) inline static
check if an interface is up
Definition at line 118 of file kernel_pfroute_net.c.
References iface_entry_t::flags.
Referenced by addr_map_entry_match_up(), and iface_entry_up_and_usable().
 {
     return (iface->flags & IFF_UP) == IFF_UP;
 }
static bool iface_entry_up_and_usable (iface_entry_t * iface) inline static
check if an interface is up and usable
Definition at line 126 of file kernel_pfroute_net.c.
References iface_entry_up(), and iface_entry_t::usable.
Referenced by addr_map_entry_match_up_and_usable(), and process_addr().
 {
     return iface->usable && iface_entry_up(iface);
 }
static status_t init_address_list (private_kernel_pfroute_net_t * this) static
Initialize a list of local addresses.
Definition at line 1696 of file kernel_pfroute_net.c.
References addr, addr_map_entry_add(), iface_entry_t::addrs, linked_list_t::create_enumerator, DBG1, DBG2, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, FAILED, iface_entry_t::flags, host_create_from_sockaddr(), hydra, iface_entry_t::ifname, INIT, linked_list_t::insert_last, ip, addr_entry_t::ip, kernel_interface_t::is_interface_usable, hydra_t::kernel_interface, linked_list_create(), memcpy, streq(), SUCCESS, and iface_entry_t::usable.
Referenced by kernel_pfroute_net_create().
 {
     struct ifaddrs *ifap, *ifa;
     iface_entry_t *iface, *current;
     addr_entry_t *addr;
     enumerator_t *ifaces, *addrs;
     DBG2(DBG_KNL, "known interfaces and IP addresses:");
     if (getifaddrs(&ifap) < 0)
     {
         DBG1(DBG_KNL, "  failed to get interfaces!");
         return FAILED;
     }
     for (ifa = ifap; ifa != NULL; ifa = ifa->ifa_next)
     {
         if (ifa->ifa_addr == NULL)
         {
             continue;
         }
         switch(ifa->ifa_addr->sa_family)
         {
             case AF_LINK:
             case AF_INET:
             case AF_INET6:
             {
                 iface = NULL;
                 ifaces = this->ifaces->create_enumerator(this->ifaces);
                 while (ifaces->enumerate(ifaces, &current))
                 {
                     if (streq(current->ifname, ifa->ifa_name))
                     {
                         iface = current;
                         break;
                     }
                 }
                 ifaces->destroy(ifaces);
                 if (!iface)
                 {
                     INIT(iface,
                         .ifindex = if_nametoindex(ifa->ifa_name),
                         .flags = ifa->ifa_flags,
                         .addrs = linked_list_create(),
                         .usable = hydra->kernel_interface->is_interface_usable(
                                         hydra->kernel_interface, ifa->ifa_name),
                     );
                     memcpy(iface->ifname, ifa->ifa_name, IFNAMSIZ);
                     this->ifaces->insert_last(this->ifaces, iface);
                 }
                 if (ifa->ifa_addr->sa_family != AF_LINK)
                 {
                     INIT(addr,
                         .ip = host_create_from_sockaddr(ifa->ifa_addr),
                     );
                     iface->addrs->insert_last(iface->addrs, addr);
                     addr_map_entry_add(this, addr, iface);
                 }
             }
         }
     }
     freeifaddrs(ifap);
     ifaces = this->ifaces->create_enumerator(this->ifaces);
     while (ifaces->enumerate(ifaces, &iface))
     {
         if (iface->usable && iface->flags & IFF_UP)
         {
             DBG2(DBG_KNL, "  %s", iface->ifname);
             addrs = iface->addrs->create_enumerator(iface->addrs);
             while (addrs->enumerate(addrs, (void**)&addr))
             {
                 DBG2(DBG_KNL, "    %H", addr->ip);
             }
             addrs->destroy(addrs);
         }
     }
     ifaces->destroy(ifaces);
     return SUCCESS;
 }
static status_t manage_route (private_kernel_pfroute_net_t * this, int op, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, char * if_name) static
Forward declaration
Add or remove a route
Definition at line 1384 of file kernel_pfroute_net.c.
References add_rt_addr(), add_rt_ifname(), add_rt_mask(), ALREADY_DONE, chunk_clonea, DBG1, DBG_KNL, host_t::destroy, dst, FAILED, host_t::get_family, host_create_from_chunk(), chunk_t::len, chunk_t::ptr, ref_get(), RTA_DST, RTA_GATEWAY, RTAX_MAX, send, seq, socket, status, strerror, SUCCESS, and type.
Referenced by METHOD(), and reinstall_routes().
 {
     struct {
         struct rt_msghdr hdr;
         char buf[sizeof(struct sockaddr_storage) * RTAX_MAX];
     } msg = {
         .hdr = {
             .rtm_version = RTM_VERSION,
             .rtm_type = op,
             .rtm_flags = RTF_UP | RTF_STATIC,
             .rtm_pid = this->pid,
             .rtm_seq = ref_get(&this->seq),
         },
     };
     host_t *dst;
     int type;
     if (prefixlen == 0 && dst_net.len)
     {
         status_t status;
         chunk_t half;
         half = chunk_clonea(dst_net);
         half.ptr[0] |= 0x80;
         prefixlen = 1;
         status = manage_route(this, op, half, prefixlen, gateway, if_name);
         if (status != SUCCESS)
         {
             return status;
         }
     }
     dst = host_create_from_chunk(AF_UNSPEC, dst_net, 0);
     if (!dst)
     {
         return FAILED;
     }
     if ((dst->get_family(dst) == AF_INET && prefixlen == 32) ||
         (dst->get_family(dst) == AF_INET6 && prefixlen == 128))
     {
         msg.hdr.rtm_flags |= RTF_HOST | RTF_GATEWAY;
     }
     msg.hdr.rtm_msglen = sizeof(struct rt_msghdr);
     for (type = 0; type < RTAX_MAX; type++)
     {
         switch (type)
         {
             case RTAX_DST:
                 add_rt_addr(&msg.hdr, RTA_DST, dst);
                 break;
             case RTAX_NETMASK:
                 if (!(msg.hdr.rtm_flags & RTF_HOST))
                 {
                     add_rt_mask(&msg.hdr, RTA_NETMASK,
                                 dst->get_family(dst), prefixlen);
                 }
                 break;
             case RTAX_IFP:
                 if (if_name)
                 {
                     add_rt_ifname(&msg.hdr, RTA_IFP, if_name);
                 }
                 break;
             case RTAX_GATEWAY:
                 if (gateway)
                 {
                     add_rt_addr(&msg.hdr, RTA_GATEWAY, gateway);
                 }
                 break;
             default:
                 break;
         }
     }
     dst->destroy(dst);
     if (send(this->socket, &msg, msg.hdr.rtm_msglen, 0) != msg.hdr.rtm_msglen)
     {
         if (errno == EEXIST)
         {
             return ALREADY_DONE;
         }
         DBG1(DBG_KNL, "%s PF_ROUTE route failed: %s",
              op == RTM_ADD ? "adding" : "deleting", strerror(errno));
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (enumerator_t , rt_enumerate , bool , rt_enumerator_t * this, int * xtype, struct sockaddr ** addr)
Definition at line 602 of file kernel_pfroute_net.c.
References addr, FALSE, RTAX_MAX, SA_LEN, TRUE, and type.
 {
     int i, type;
     if (this->remaining < sizeof(this->addr->sa_len) ||
         this->remaining < this->addr->sa_len)
     {
         return FALSE;
     }
     for (i = 0; i < RTAX_MAX; i++)
     {
         type = (1 << i);
         if (this->types & type)
         {
             this->types &= ~type;
             *addr = this->addr;
             *xtype = i;
             this->remaining -= SA_LEN(this->addr->sa_len);
             this->addr = (struct sockaddr*)((char*)this->addr +
                                             SA_LEN(this->addr->sa_len));
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (kernel_net_t , create_address_enumerator , enumerator_t * , private_kernel_pfroute_net_t * this, kernel_address_type_t which)
Definition at line 1121 of file kernel_pfroute_net.c.
References address_enumerator_destroy(), create_iface_enumerator(), data, enumerator_create_filter(), enumerator_create_nested(), filter_interfaces(), INIT, and lock.
 {
     address_enumerator_t *data;
     INIT(data,
         .this = this,
         .which = which,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(
                 enumerator_create_filter(
                     this->ifaces->create_enumerator(this->ifaces),
                     (void*)filter_interfaces, data, NULL),
                 (void*)create_iface_enumerator, data,
                 (void*)address_enumerator_destroy);
 }
METHOD (kernel_net_t , get_features , kernel_feature_t , private_kernel_pfroute_net_t * this)
Definition at line 1140 of file kernel_pfroute_net.c.
References KERNEL_REQUIRE_EXCLUDE_ROUTE.
 {
     return KERNEL_REQUIRE_EXCLUDE_ROUTE;
 }
METHOD (kernel_net_t , get_interface_name , bool , private_kernel_pfroute_net_t * this, host_t * ip, char ** name)
Definition at line 1146 of file kernel_pfroute_net.c.
References addr_map_entry_match_up(), addr_map_entry_match_up_and_usable(), addr_map_entry_match_virtual(), DBG2, DBG_KNL, FALSE, addr_map_entry_t::iface, iface_entry_t::ifname, ip, host_t::is_anyaddr, lock, lookup, strdup, TRUE, and spinlock_t::unlock.
 {
     addr_map_entry_t *entry, lookup = {
         .ip = ip,
     };
     if (ip->is_anyaddr(ip))
     {
         return FALSE;
     }
     this->lock->read_lock(this->lock);
     /* first try to find it on an up and usable interface */
     entry = this->addrs->get_match(this->addrs, &lookup,
                                   (void*)addr_map_entry_match_up_and_usable);
     if (entry)
     {
         if (name)
         {
             *name = strdup(entry->iface->ifname);
             DBG2(DBG_KNL, "%H is on interface %s", ip, *name);
         }
         this->lock->unlock(this->lock);
         return TRUE;
     }
     /* check if it is a virtual IP */
     entry = this->addrs->get_match(this->addrs, &lookup,
                                   (void*)addr_map_entry_match_virtual);
     if (entry)
     {
         if (name)
         {
             *name = strdup(entry->iface->ifname);
             DBG2(DBG_KNL, "virtual IP %H is on interface %s", ip, *name);
         }
         this->lock->unlock(this->lock);
         return TRUE;
     }
     /* maybe it is installed on an ignored interface */
     entry = this->addrs->get_match(this->addrs, &lookup,
                                   (void*)addr_map_entry_match_up);
     if (!entry)
     {   /* the address does not exist, is on a down interface */
         DBG2(DBG_KNL, "%H is not a local address or the interface is down", ip);
     }
     this->lock->unlock(this->lock);
     return FALSE;
 }
METHOD (kernel_net_t , add_ip , status_t , private_kernel_pfroute_net_t * this, host_t * vip, int prefix, char * ifname)
Definition at line 1195 of file kernel_pfroute_net.c.
References addr, iface_entry_t::addrs, condvar, linked_list_t::create_enumerator, DBG1, DBG_KNL, enumerator_t::destroy, tun_device_t::destroy, enumerator_t::enumerate, FAILED, FALSE, host_t::get_address, tun_device_t::get_name, hydra, iface_entry_t::ifname, addr_entry_t::ip, host_t::ip_equals, hydra_t::kernel_interface, chunk_t::len, mutex_t::lock, lock, mutex, queue_route_reinstall(), tun_device_t::set_address, strdup, streq(), SUCCESS, condvar_t::timed_wait, TRUE, kernel_interface_t::tun, tun_device_create(), spinlock_t::unlock, mutex_t::unlock, tun_device_t::up, and addr_entry_t::virtual.
 {
     enumerator_t *ifaces, *addrs;
     iface_entry_t *iface;
     addr_entry_t *addr;
     tun_device_t *tun;
     bool timeout = FALSE;
     if (!this->install_virtual_ip)
     {   /* disabled by config */
         return SUCCESS;
     }
     tun = tun_device_create(NULL);
     if (!tun)
     {
         return FAILED;
     }
     if (prefix == -1)
     {
         prefix = vip->get_address(vip).len * 8;
     }
     if (!tun->up(tun) || !tun->set_address(tun, vip, prefix))
     {
         tun->destroy(tun);
         return FAILED;
     }
     /* wait until address appears */
     this->mutex->lock(this->mutex);
     while (!timeout && !get_interface_name(this, vip, NULL))
     {
         timeout = this->condvar->timed_wait(this->condvar, this->mutex,
                                             this->vip_wait);
     }
     this->mutex->unlock(this->mutex);
     if (timeout)
     {
         DBG1(DBG_KNL, "virtual IP %H did not appear on %s",
              vip, tun->get_name(tun));
         tun->destroy(tun);
         return FAILED;
     }
     this->lock->write_lock(this->lock);
     this->tuns->insert_last(this->tuns, tun);
     ifaces = this->ifaces->create_enumerator(this->ifaces);
     while (ifaces->enumerate(ifaces, &iface))
     {
         if (streq(iface->ifname, tun->get_name(tun)))
         {
             addrs = iface->addrs->create_enumerator(iface->addrs);
             while (addrs->enumerate(addrs, &addr))
             {
                 if (addr->ip->ip_equals(addr->ip, vip))
                 {
                     addr->virtual = TRUE;
                 }
             }
             addrs->destroy(addrs);
             /* during IKEv1 reauthentication, children get moved from
              * old the new SA before the virtual IP is available. This
              * kills the route for our virtual IP, reinstall. */
             queue_route_reinstall(this, strdup(iface->ifname));
             break;
         }
     }
     ifaces->destroy(ifaces);
     /* lets do this while holding the lock, thus preventing another thread
      * from deleting the TUN device concurrently, hopefully listeners are quick
      * and cause no deadlocks */
     hydra->kernel_interface->tun(hydra->kernel_interface, tun, TRUE);
     this->lock->unlock(this->lock);
     return SUCCESS;
 }
METHOD (kernel_net_t , del_ip , status_t , private_kernel_pfroute_net_t * this, host_t * vip, int prefix, bool wait)
Definition at line 1275 of file kernel_pfroute_net.c.
References addr, condvar, DBG1, DBG_KNL, enumerator_t::destroy, tun_device_t::destroy, enumerator_t::enumerate, FAILED, FALSE, found, tun_device_t::get_address, hydra, host_t::ip_equals, hydra_t::kernel_interface, mutex_t::lock, lock, mutex, NOT_FOUND, SUCCESS, condvar_t::timed_wait, TRUE, kernel_interface_t::tun, spinlock_t::unlock, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     tun_device_t *tun;
     host_t *addr;
     bool timeout = FALSE, found = FALSE;
     if (!this->install_virtual_ip)
     {   /* disabled by config */
         return SUCCESS;
     }
     this->lock->write_lock(this->lock);
     enumerator = this->tuns->create_enumerator(this->tuns);
     while (enumerator->enumerate(enumerator, &tun))
     {
         addr = tun->get_address(tun, NULL);
         if (addr && addr->ip_equals(addr, vip))
         {
             this->tuns->remove_at(this->tuns, enumerator);
             hydra->kernel_interface->tun(hydra->kernel_interface, tun,
                                          FALSE);
             tun->destroy(tun);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!found)
     {
         return NOT_FOUND;
     }
     /* wait until address disappears */
     if (wait)
     {
         this->mutex->lock(this->mutex);
         while (!timeout && get_interface_name(this, vip, NULL))
         {
             timeout = this->condvar->timed_wait(this->condvar, this->mutex,
                                                 this->vip_wait);
         }
         this->mutex->unlock(this->mutex);
         if (timeout)
         {
             DBG1(DBG_KNL, "virtual IP %H did not disappear from tun", vip);
             return FAILED;
         }
     }
     return SUCCESS;
 }
METHOD (kernel_net_t , add_route , status_t , private_kernel_pfroute_net_t * this, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, host_t * src_ip, char * if_name)
Definition at line 1476 of file kernel_pfroute_net.c.
References ALREADY_DONE, found, manage_route(), route_entry_clone(), status, and SUCCESS.
 {
     status_t status;
     route_entry_t *found, route = {
         .dst_net = dst_net,
         .prefixlen = prefixlen,
         .gateway = gateway,
         .if_name = if_name,
     };
     this->routes_lock->lock(this->routes_lock);
     found = this->routes->get(this->routes, &route);
     if (found)
     {
         this->routes_lock->unlock(this->routes_lock);
         return ALREADY_DONE;
     }
     status = manage_route(this, RTM_ADD, dst_net, prefixlen, gateway, if_name);
     if (status == SUCCESS)
     {
         found = route_entry_clone(&route);
         this->routes->put(this->routes, found, found);
     }
     this->routes_lock->unlock(this->routes_lock);
     return status;
 }
METHOD (kernel_net_t , del_route , status_t , private_kernel_pfroute_net_t * this, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, host_t * src_ip, char * if_name)
Definition at line 1505 of file kernel_pfroute_net.c.
References found, manage_route(), NOT_FOUND, route_entry_destroy(), and status.
 {
     status_t status;
     route_entry_t *found, route = {
         .dst_net = dst_net,
         .prefixlen = prefixlen,
         .gateway = gateway,
         .if_name = if_name,
     };
     this->routes_lock->lock(this->routes_lock);
     found = this->routes->get(this->routes, &route);
     if (!found)
     {
         this->routes_lock->unlock(this->routes_lock);
         return NOT_FOUND;
     }
     this->routes->remove(this->routes, found);
     route_entry_destroy(found);
     status = manage_route(this, RTM_DELETE, dst_net, prefixlen, gateway,
                           if_name);
     this->routes_lock->unlock(this->routes_lock);
     return status;
 }
METHOD (kernel_net_t , get_source_addr , host_t * , private_kernel_pfroute_net_t * this, host_t * dest, host_t * src)
Definition at line 1681 of file kernel_pfroute_net.c.
References FALSE, and get_route().
 {
     return get_route(this, FALSE, dest, src);
 }
METHOD (kernel_net_t , get_nexthop , host_t * , private_kernel_pfroute_net_t * this, host_t * dest, int prefix, host_t * src)
Definition at line 1687 of file kernel_pfroute_net.c.
References get_route(), and TRUE.
 {
     return get_route(this, TRUE, dest, src);
 }
METHOD (kernel_net_t , destroy , void , private_kernel_pfroute_net_t * this)
Definition at line 1780 of file kernel_pfroute_net.c.
References addr, close, condvar, spinlock_t::destroy, enumerator_t::destroy, mutex_t::destroy, condvar_t::destroy, route_entry_t::dst_net, enumerator_t::enumerate, free(), route_entry_t::gateway, route_entry_t::if_name, iface_entry_destroy(), lib, lock, manage_route(), mutex, net_changes_clear(), route_entry_t::prefixlen, watcher_t::remove, route_entry_destroy(), socket, and library_t::watcher.
 {
     enumerator_t *enumerator;
     route_entry_t *route;
     addr_entry_t *addr;
     enumerator = this->routes->create_enumerator(this->routes);
     while (enumerator->enumerate(enumerator, NULL, (void**)&route))
     {
         manage_route(this, RTM_DELETE, route->dst_net, route->prefixlen,
                      route->gateway, route->if_name);
         route_entry_destroy(route);
     }
     enumerator->destroy(enumerator);
     this->routes->destroy(this->routes);
     this->routes_lock->destroy(this->routes_lock);
     if (this->socket != -1)
     {
         lib->watcher->remove(lib->watcher, this->socket);
         close(this->socket);
     }
     net_changes_clear(this);
     this->net_changes->destroy(this->net_changes);
     this->net_changes_lock->destroy(this->net_changes_lock);
     enumerator = this->addrs->create_enumerator(this->addrs);
     while (enumerator->enumerate(enumerator, NULL, (void**)&addr))
     {
         free(addr);
     }
     enumerator->destroy(enumerator);
     this->addrs->destroy(this->addrs);
     this->ifaces->destroy_function(this->ifaces, (void*)iface_entry_destroy);
     this->tuns->destroy(this->tuns);
     this->lock->destroy(this->lock);
     this->mutex->destroy(this->mutex);
     this->condvar->destroy(this->condvar);
     this->roam_lock->destroy(this->roam_lock);
     free(this->reply);
     free(this);
 }
static void net_change_destroy (net_change_t * this) static
Destroy a net_change_t object
Definition at line 278 of file kernel_pfroute_net.c.
References free().
Referenced by net_changes_clear(), and queue_route_reinstall().
 {
     free(this->if_name);
     free(this);
 }
static bool net_change_equals (net_change_t * a, net_change_t * b) static
Compare two net_change_t objects
Definition at line 295 of file kernel_pfroute_net.c.
References net_change_t::if_name, and streq().
Referenced by kernel_pfroute_net_create().
 {
     return streq(a->if_name, b->if_name);
 }
static u_int net_change_hash (net_change_t * this) static
Hash a net_change_t object
Definition at line 287 of file kernel_pfroute_net.c.
References chunk_create(), and chunk_hash().
Referenced by kernel_pfroute_net_create().
 {
     return chunk_hash(chunk_create(this->if_name, strlen(this->if_name)));
 }
static void net_changes_clear (private_kernel_pfroute_net_t * this) static
Clear the queued network changes.
Definition at line 429 of file kernel_pfroute_net.c.
References enumerator_t::destroy, enumerator_t::enumerate, and net_change_destroy().
Referenced by METHOD(), and reinstall_routes().
 {
     enumerator_t *enumerator;
     net_change_t *change;
     enumerator = this->net_changes->create_enumerator(this->net_changes);
     while (enumerator->enumerate(enumerator, NULL, (void**)&change))
     {
         this->net_changes->remove_at(this->net_changes, enumerator);
         net_change_destroy(change);
     }
     enumerator->destroy(enumerator);
 }
static void process_addr (private_kernel_pfroute_net_t * this, struct ifa_msghdr * ifa) static
Process an RTM_*ADDR message from the kernel
Definition at line 670 of file kernel_pfroute_net.c.
References addr, addr_entry_destroy(), addr_map_entry_add(), addr_map_entry_remove(), iface_entry_t::addrs, host_t::clone, linked_list_t::create_enumerator, create_ifamsg_enumerator(), DBG1, DBG_KNL, enumerator_t::destroy, host_t::destroy, DESTROY_IF, enumerator_t::enumerate, FALSE, fire_roam_event(), found, free(), host, host_create_from_sockaddr(), iface_entry_up_and_usable(), iface_entry_t::ifindex, iface_entry_t::ifname, INIT, linked_list_t::insert_last, ip, addr_entry_t::ip, host_t::ip_equals, host_t::is_anyaddr, lock, queue_route_reinstall(), linked_list_t::remove_at, RTM_DELADDR, RTM_NEWADDR, strdup, TRUE, type, spinlock_t::unlock, iface_entry_t::usable, and addr_entry_t::virtual.
Referenced by receive_events().
 {
     struct sockaddr *sockaddr;
     host_t *host = NULL;
     enumerator_t *ifaces, *addrs;
     iface_entry_t *iface;
     addr_entry_t *addr;
     bool found = FALSE, changed = FALSE, roam = FALSE;
     enumerator_t *enumerator;
     char *ifname = NULL;
     int type;
     enumerator = create_ifamsg_enumerator(ifa);
     while (enumerator->enumerate(enumerator, &type, &sockaddr))
     {
         if (type == RTAX_IFA)
         {
             host = host_create_from_sockaddr(sockaddr);
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!host || host->is_anyaddr(host))
     {
         DESTROY_IF(host);
         return;
     }
     this->lock->write_lock(this->lock);
     ifaces = this->ifaces->create_enumerator(this->ifaces);
     while (ifaces->enumerate(ifaces, &iface))
     {
         if (iface->ifindex == ifa->ifam_index)
         {
             addrs = iface->addrs->create_enumerator(iface->addrs);
             while (addrs->enumerate(addrs, &addr))
             {
                 if (host->ip_equals(host, addr->ip))
                 {
                     found = TRUE;
                     if (ifa->ifam_type == RTM_DELADDR)
                     {
                         iface->addrs->remove_at(iface->addrs, addrs);
                         if (!addr->virtual && iface->usable)
{
                             changed = TRUE;
                             DBG1(DBG_KNL, "%H disappeared from %s",
                                  host, iface->ifname);
                         }
                         addr_map_entry_remove(addr, iface, this);
                         addr_entry_destroy(addr);
                     }
                 }
             }
             addrs->destroy(addrs);
             if (!found && ifa->ifam_type == RTM_NEWADDR)
             {
                 INIT(addr,
                     .ip = host->clone(host),
                 );
                 changed = TRUE;
                 ifname = strdup(iface->ifname);
                 iface->addrs->insert_last(iface->addrs, addr);
                 addr_map_entry_add(this, addr, iface);
                 if (iface->usable)
                 {
                     DBG1(DBG_KNL, "%H appeared on %s", host, iface->ifname);
                 }
             }
             if (changed && iface_entry_up_and_usable(iface))
             {
                 roam = TRUE;
             }
             break;
         }
     }
     ifaces->destroy(ifaces);
     this->lock->unlock(this->lock);
     host->destroy(host);
     if (roam && ifname)
     {
         queue_route_reinstall(this, ifname);
     }
     else
     {
         free(ifname);
     }
     if (roam)
     {
         fire_roam_event(this, TRUE);
     }
 }
static void process_link (private_kernel_pfroute_net_t * this, struct if_msghdr * msg) static
Process an RTM_IFINFO message from the kernel
Definition at line 812 of file kernel_pfroute_net.c.
References DBG1, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, FALSE, fire_roam_event(), iface_entry_t::flags, found, free(), hydra, iface_entry_t::ifindex, iface_entry_t::ifname, INIT, kernel_interface_t::is_interface_usable, hydra_t::kernel_interface, linked_list_create(), lock, queue_route_reinstall(), repopulate_iface(), strdup, TRUE, spinlock_t::unlock, iface_entry_t::usable, and usleep().
Referenced by receive_events().
 {
     enumerator_t *enumerator;
     iface_entry_t *iface;
     bool roam = FALSE, found = FALSE, update_routes = FALSE;
     this->lock->write_lock(this->lock);
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, &iface))
     {
         if (iface->ifindex == msg->ifm_index)
         {
             if (iface->usable)
             {
                 if (!(iface->flags & IFF_UP) && (msg->ifm_flags & IFF_UP))
                 {
                     roam = update_routes = TRUE;
                     DBG1(DBG_KNL, "interface %s activated", iface->ifname);
                 }
                 else if ((iface->flags & IFF_UP) && !(msg->ifm_flags & IFF_UP))
                 {
                     roam = TRUE;
                     DBG1(DBG_KNL, "interface %s deactivated", iface->ifname);
                 }
             }
 #ifdef __APPLE__
             /* There seems to be a race condition on 10.10, where we get
              * the RTM_IFINFO, but getifaddrs() does not return the virtual
              * IP installed on a tun device, but we also don't get a
              * RTM_NEWADDR. We therefore could miss the new address, letting
              * virtual IP installation fail. Delaying getifaddrs() helps,
              * but is obviously not a clean fix. */
             usleep(50000);
 #endif
             iface->flags = msg->ifm_flags;
             repopulate_iface(this, iface);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         INIT(iface,
             .ifindex = msg->ifm_index,
             .flags = msg->ifm_flags,
             .addrs = linked_list_create(),
         );
         if (if_indextoname(iface->ifindex, iface->ifname))
         {
             DBG1(DBG_KNL, "interface %s appeared", iface->ifname);
             iface->usable = hydra->kernel_interface->is_interface_usable(
                                         hydra->kernel_interface, iface->ifname);
             repopulate_iface(this, iface);
             this->ifaces->insert_last(this->ifaces, iface);
             if (iface->usable)
             {
                 roam = update_routes = TRUE;
             }
         }
         else
         {
             free(iface);
         }
     }
     this->lock->unlock(this->lock);
     if (update_routes)
     {
         queue_route_reinstall(this, strdup(iface->ifname));
     }
     if (roam)
     {
         fire_roam_event(this, TRUE);
     }
 }
static void process_route (private_kernel_pfroute_net_t * this, struct rt_msghdr * msg) static
Process an RTM_*ROUTE message from the kernel
Definition at line 930 of file kernel_pfroute_net.c.
Referenced by receive_events().
 {
 }
static void queue_route_reinstall (private_kernel_pfroute_net_t * this, char * if_name) static
Queue route reinstallation caused by network changes for a given interface.
The route reinstallation is delayed for a while and only done once for several calls during this delay, in order to avoid doing it too often. The interface name is freed.
Definition at line 483 of file kernel_pfroute_net.c.
References callback_job_create(), found, INIT, lib, net_change_destroy(), reinstall_routes(), ROUTE_DELAY, scheduler_t::schedule_job_ms, library_t::scheduler, time_monotonic(), timeval_add_ms(), and update().
Referenced by METHOD(), process_addr(), and process_link().
 {
     net_change_t *update, *found;
     timeval_t now;
     job_t *job;
     INIT(update,
         .if_name = if_name
     );
     this->net_changes_lock->lock(this->net_changes_lock);
     found = this->net_changes->put(this->net_changes, update, update);
     if (found)
     {
         net_change_destroy(found);
     }
     time_monotonic(&now);
     if (timercmp(&now, &this->last_route_reinstall, >))
     {
         timeval_add_ms(&now, ROUTE_DELAY);
         this->last_route_reinstall = now;
         job = (job_t*)callback_job_create((callback_job_cb_t)reinstall_routes,
                                           this, NULL, NULL);
         lib->scheduler->schedule_job_ms(lib->scheduler, job, ROUTE_DELAY);
     }
     this->net_changes_lock->unlock(this->net_changes_lock);
 }
static bool receive_events (private_kernel_pfroute_net_t * this, int fd, watcher_event_t event) static
Receives PF_ROUTE messages from kernel
Definition at line 939 of file kernel_pfroute_net.c.
References condvar_t::broadcast, condvar, DBG1, DBG_KNL, len, mutex_t::lock, memcpy, msg, MSG_DONTWAIT, mutex, process_addr(), process_link(), process_route(), recv, RTAX_MAX, RTM_DELADDR, RTM_NEWADDR, sleep, socket, TRUE, and mutex_t::unlock.
Referenced by kernel_pfroute_net_create().
 {
     struct {
         union {
             struct rt_msghdr rtm;
             struct if_msghdr ifm;
             struct ifa_msghdr ifam;
 #ifdef HAVE_RTM_IFANNOUNCE
             struct if_announcemsghdr ifanm;
 #endif
         };
         char buf[sizeof(struct sockaddr_storage) * RTAX_MAX];
     } msg;
     int len, hdrlen;
     len = recv(this->socket, &msg, sizeof(msg), MSG_DONTWAIT);
     if (len < 0)
     {
         switch (errno)
         {
             case EINTR:
             case EAGAIN:
                 return TRUE;
             default:
                 DBG1(DBG_KNL, "unable to receive from PF_ROUTE event socket");
                 sleep(1);
                 return TRUE;
         }
     }
     if (len < offsetof(struct rt_msghdr, rtm_flags) || len < msg.rtm.rtm_msglen)
     {
         DBG1(DBG_KNL, "received invalid PF_ROUTE message");
         return TRUE;
     }
     if (msg.rtm.rtm_version != RTM_VERSION)
     {
         DBG1(DBG_KNL, "received PF_ROUTE message with unsupported version: %d",
              msg.rtm.rtm_version);
         return TRUE;
     }
     switch (msg.rtm.rtm_type)
     {
         case RTM_NEWADDR:
         case RTM_DELADDR:
             hdrlen = sizeof(msg.ifam);
             break;
         case RTM_IFINFO:
             hdrlen = sizeof(msg.ifm);
             break;
 #ifdef HAVE_RTM_IFANNOUNCE
         case RTM_IFANNOUNCE:
             hdrlen = sizeof(msg.ifanm);
             break;
 #endif /* HAVE_RTM_IFANNOUNCE */
         case RTM_ADD:
         case RTM_DELETE:
         case RTM_GET:
             hdrlen = sizeof(msg.rtm);
             break;
         default:
             return TRUE;
     }
     if (msg.rtm.rtm_msglen < hdrlen)
     {
         DBG1(DBG_KNL, "ignoring short PF_ROUTE message");
         return TRUE;
     }
     switch (msg.rtm.rtm_type)
     {
         case RTM_NEWADDR:
         case RTM_DELADDR:
             process_addr(this, &msg.ifam);
             break;
         case RTM_IFINFO:
             process_link(this, &msg.ifm);
             break;
 #ifdef HAVE_RTM_IFANNOUNCE
         case RTM_IFANNOUNCE:
             process_announce(this, &msg.ifanm);
             break;
 #endif /* HAVE_RTM_IFANNOUNCE */
         case RTM_ADD:
         case RTM_DELETE:
             process_route(this, &msg.rtm);
             break;
         default:
             break;
     }
     this->mutex->lock(this->mutex);
     if (msg.rtm.rtm_pid == this->pid && msg.rtm.rtm_seq == this->waiting_seq)
     {
         /* seems like the message someone is waiting for, deliver */
         this->reply = realloc(this->reply, msg.rtm.rtm_msglen);
         memcpy(this->reply, &msg, msg.rtm.rtm_msglen);
     }
     /* signal on any event, add_ip()/del_ip() might wait for it */
     this->condvar->broadcast(this->condvar);
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
static job_requeue_t reinstall_routes (private_kernel_pfroute_net_t * this) static
Act upon queued network changes.
Definition at line 446 of file kernel_pfroute_net.c.
References enumerator_t::destroy, route_entry_t::dst_net, enumerator_t::enumerate, route_entry_t::gateway, route_entry_t::if_name, JOB_REQUEUE_NONE, lookup, manage_route(), net_changes_clear(), and route_entry_t::prefixlen.
Referenced by queue_route_reinstall().
 {
     enumerator_t *enumerator;
     route_entry_t *route;
     this->net_changes_lock->lock(this->net_changes_lock);
     this->routes_lock->lock(this->routes_lock);
     enumerator = this->routes->create_enumerator(this->routes);
     while (enumerator->enumerate(enumerator, NULL, (void**)&route))
     {
         net_change_t *change, lookup = {
             .if_name = route->if_name,
         };
         /* check if a change for the outgoing interface is queued */
         change = this->net_changes->get(this->net_changes, &lookup);
         if (change)
         {
             manage_route(this, RTM_ADD, route->dst_net, route->prefixlen,
                          route->gateway, route->if_name);
         }
     }
     enumerator->destroy(enumerator);
     this->routes_lock->unlock(this->routes_lock);
     net_changes_clear(this);
     this->net_changes_lock->unlock(this->net_changes_lock);
     return JOB_REQUEUE_NONE;
 }
static void repopulate_iface (private_kernel_pfroute_net_t * this, iface_entry_t * iface) static
Re-initialize address list of an interface if it changes state
Definition at line 772 of file kernel_pfroute_net.c.
References addr, addr_entry_destroy(), addr_map_entry_add(), addr_map_entry_remove(), iface_entry_t::addrs, host_create_from_sockaddr(), iface_entry_t::ifname, INIT, linked_list_t::insert_last, ip, linked_list_t::remove_last, streq(), and SUCCESS.
Referenced by process_link().
 {
     struct ifaddrs *ifap, *ifa;
     addr_entry_t *addr;
     while (iface->addrs->remove_last(iface->addrs, (void**)&addr) == SUCCESS)
     {
         addr_map_entry_remove(addr, iface, this);
         addr_entry_destroy(addr);
     }
     if (getifaddrs(&ifap) == 0)
     {
         for (ifa = ifap; ifa != NULL; ifa = ifa->ifa_next)
         {
             if (ifa->ifa_addr && streq(ifa->ifa_name, iface->ifname))
             {
                 switch (ifa->ifa_addr->sa_family)
                 {
                     case AF_INET:
                     case AF_INET6:
                         INIT(addr,
                             .ip = host_create_from_sockaddr(ifa->ifa_addr),
                         );
                         iface->addrs->insert_last(iface->addrs, addr);
                         addr_map_entry_add(this, addr, iface);
                         break;
                     default:
                         break;
                 }
             }
         }
         freeifaddrs(ifap);
     }
 }
static job_requeue_t roam_event (private_kernel_pfroute_net_t * this) static
callback function that raises the delayed roam event
Definition at line 550 of file kernel_pfroute_net.c.
References FALSE, hydra, JOB_REQUEUE_NONE, hydra_t::kernel_interface, and kernel_interface_t::roam.
Referenced by fire_roam_event().
 {
     bool address;
     this->roam_lock->lock(this->roam_lock);
     address = this->roam_address;
     this->roam_address = FALSE;
     this->roam_lock->unlock(this->roam_lock);
     hydra->kernel_interface->roam(hydra->kernel_interface, address);
     return JOB_REQUEUE_NONE;
 }
static route_entry_t* route_entry_clone (route_entry_t * this) static
Clone a route_entry_t object.
Definition at line 218 of file kernel_pfroute_net.c.
References chunk_clone, INIT, and strdup.
Referenced by METHOD().
 {
     route_entry_t *route;
     INIT(route,
         .if_name = strdup(this->if_name),
         .gateway = this->gateway ? this->gateway->clone(this->gateway) : NULL,
         .dst_net = chunk_clone(this->dst_net),
         .prefixlen = this->prefixlen,
     );
     return route;
 }
static void route_entry_destroy (route_entry_t * this) static
Destroy a route_entry_t object
Definition at line 234 of file kernel_pfroute_net.c.
References chunk_free(), DESTROY_IF, and free().
Referenced by METHOD().
 {
     free(this->if_name);
     DESTROY_IF(this->gateway);
     chunk_free(&this->dst_net);
     free(this);
 }
static bool route_entry_equals (route_entry_t * a, route_entry_t * b) static
Compare two route_entry_t objects
Definition at line 254 of file kernel_pfroute_net.c.
References chunk_equals(), route_entry_t::dst_net, FALSE, route_entry_t::gateway, route_entry_t::if_name, host_t::ip_equals, route_entry_t::prefixlen, and streq().
Referenced by kernel_pfroute_net_create().
 {
     if (a->if_name && b->if_name && streq(a->if_name, b->if_name) &&
         chunk_equals(a->dst_net, b->dst_net) && a->prefixlen == b->prefixlen)
     {
         return (!a->gateway && !b->gateway) || (a->gateway && b->gateway &&
                     a->gateway->ip_equals(a->gateway, b->gateway));
     }
     return FALSE;
 }
static u_int route_entry_hash (route_entry_t * this) static
Hash a route_entry_t object
Definition at line 245 of file kernel_pfroute_net.c.
References chunk_from_thing, chunk_hash(), and chunk_hash_inc().
Referenced by kernel_pfroute_net_create().
 {
     return chunk_hash_inc(chunk_from_thing(this->prefixlen),
                           chunk_hash(this->dst_net));
 }