strongSwan: radius_client.c File Reference
radius_client.c File Reference
#include "radius_client.h"
#include "radius_config.h"
#include <unistd.h>
#include <errno.h>
#include <utils/debug.h>
#include <networking/host.h>
#include <collections/linked_list.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
Classes
struct private_radius_client_t
Typedefs
typedef struct
private_radius_client_t private_radius_client_t
Functions
static void save_state (private_radius_client_t *this, radius_message_t *msg)
METHOD (radius_client_t, request, radius_message_t *, private_radius_client_t *this, radius_message_t *req)
METHOD (radius_client_t, get_msk, chunk_t, private_radius_client_t *this)
METHOD (radius_client_t, destroy, void, private_radius_client_t *this)
radius_client_t * radius_client_create (radius_config_t *config)
Typedef Documentation
typedef struct private_radius_client_t private_radius_client_t
Definition at line 28 of file radius_client.c.
Function Documentation
METHOD (radius_client_t , request , radius_message_t * , private_radius_client_t * this, radius_message_t * req)
Definition at line 81 of file radius_client.c.
References radius_message_t::add, chunk_clear(), data, DBG1, DBG3, DBG_CFG, radius_socket_t::decrypt_msk, FALSE, radius_message_t::get_code, radius_message_code_names, RAT_NAS_IDENTIFIER, RAT_STATE, radius_socket_t::request, res, RMC_ACCESS_ACCEPT, save_state(), socket, and TRUE.
 {
     radius_socket_t *socket;
     radius_message_t *res;
     chunk_t data;
     /* add our NAS-Identifier */
     req->add(req, RAT_NAS_IDENTIFIER,
              this->config->get_nas_identifier(this->config));
     /* add State attribute, if server sent one */
     if (this->state.ptr)
     {
         req->add(req, RAT_STATE, this->state);
     }
     socket = this->config->get_socket(this->config);
     DBG1(DBG_CFG, "sending RADIUS %N to server '%s'", radius_message_code_names,
          req->get_code(req), this->config->get_name(this->config));
     res = socket->request(socket, req);
     if (res)
     {
         DBG1(DBG_CFG, "received RADIUS %N from server '%s'",
              radius_message_code_names, res->get_code(res),
              this->config->get_name(this->config));
         data = res->get_encoding(res);
         DBG3(DBG_CFG, "%B", &data);
         save_state(this, res);
         if (res->get_code(res) == RMC_ACCESS_ACCEPT)
         {
             chunk_clear(&this->msk);
             this->msk = socket->decrypt_msk(socket, req, res);
         }
         this->config->put_socket(this->config, socket, TRUE);
         return res;
     }
     this->config->put_socket(this->config, socket, FALSE);
     return NULL;
 }
METHOD (radius_client_t , get_msk , chunk_t , private_radius_client_t * this)
Definition at line 122 of file radius_client.c.
 {
     return this->msk;
 }
METHOD (radius_client_t , destroy , void , private_radius_client_t * this)
Definition at line 128 of file radius_client.c.
References chunk_clear(), and free().
 {
     this->config->destroy(this->config);
     chunk_clear(&this->msk);
     free(this->state.ptr);
     free(this);
 }
static void save_state (private_radius_client_t * this, radius_message_t * msg) static
Save the state attribute to include in further request
Definition at line 59 of file radius_client.c.
References chunk_clone, chunk_free(), radius_message_t::create_enumerator, data, enumerator_t::destroy, enumerator_t::enumerate, free(), RAT_STATE, and type.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     int type;
     chunk_t data;
     enumerator = msg->create_enumerator(msg);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (type == RAT_STATE)
         {
             free(this->state.ptr);
             this->state = chunk_clone(data);
             enumerator->destroy(enumerator);
             return;
         }
     }
     enumerator->destroy(enumerator);
     /* no state attribute found, remove state */
     chunk_free(&this->state);
 }