strongSwan: eap_simaka_reauth_provider.c File Reference
eap_simaka_reauth_provider.c File Reference
#include "eap_simaka_reauth_provider.h"
#include <daemon.h>
#include <collections/hashtable.h>
Classes
struct private_eap_simaka_reauth_provider_t
struct reauth_data_t
Typedefs
typedef struct
private_eap_simaka_reauth_provider_t private_eap_simaka_reauth_provider_t
Functions
static u_int hash (identification_t *key)
static bool equals (identification_t *key1, identification_t *key2)
static identification_t * gen_identity (private_eap_simaka_reauth_provider_t *this)
METHOD (simaka_provider_t, is_reauth, identification_t *, private_eap_simaka_reauth_provider_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
METHOD (simaka_provider_t, gen_reauth, identification_t *, private_eap_simaka_reauth_provider_t *this, identification_t *id, char mk[HASH_SIZE_SHA1])
METHOD (eap_simaka_reauth_provider_t, destroy, void, private_eap_simaka_reauth_provider_t *this)
eap_simaka_reauth_provider_t * eap_simaka_reauth_provider_create ()
Typedef Documentation
typedef struct private_eap_simaka_reauth_provider_t private_eap_simaka_reauth_provider_t
Definition at line 21 of file eap_simaka_reauth_provider.c.
Function Documentation
static bool equals (identification_t * key1, identification_t * key2) static
hashtable equals function
Definition at line 72 of file eap_simaka_reauth_provider.c.
References identification_t::equals.
Referenced by eap_simaka_reauth_provider_create().
 {
     return key1->equals(key1, key2);
 }
static identification_t* gen_identity (private_eap_simaka_reauth_provider_t * this) static
Generate a random identity
Definition at line 80 of file eap_simaka_reauth_provider.c.
References chunk_create(), chunk_to_hex(), FALSE, identification_create_from_string(), and rng.
Referenced by METHOD().
 {
     char buf[8], hex[sizeof(buf) * 2 + 1];
     if (!this->rng->get_bytes(this->rng, sizeof(buf), buf))
     {
         return NULL;
     }
     chunk_to_hex(chunk_create(buf, sizeof(buf)), hex, FALSE);
     return identification_create_from_string(hex);
 }
static u_int hash (identification_t * key) static
hashtable hash function
Definition at line 64 of file eap_simaka_reauth_provider.c.
References chunk_hash(), and identification_t::get_encoding.
Referenced by eap_simaka_reauth_provider_create().
 {
     return chunk_hash(key->get_encoding(key));
 }
METHOD (simaka_provider_t , is_reauth , identification_t * , private_eap_simaka_reauth_provider_t * this, identification_t * id, char mk[HASH_SIZE_SHA1], u_int16_t * counter)
Definition at line 93 of file eap_simaka_reauth_provider.c.
References identification_t::clone, reauth_data_t::counter, data, memcpy, reauth_data_t::mk, and reauth().
 {
     identification_t *permanent;
     reauth_data_t *data;
     /* look up permanent identity */
     permanent = this->permanent->get(this->permanent, id);
     if (!permanent)
     {
         return NULL;
     }
     /* look up reauthentication data */
     data = this->reauth->get(this->reauth, permanent);
     if (!data)
     {
         return NULL;
     }
     *counter = ++data->counter;
     memcpy(mk, data->mk, HASH_SIZE_SHA1);
     return permanent->clone(permanent);
 }
METHOD (simaka_provider_t , gen_reauth , identification_t * , private_eap_simaka_reauth_provider_t * this, identification_t * id, char mk[HASH_SIZE_SHA1])
Definition at line 117 of file eap_simaka_reauth_provider.c.
References identification_t::clone, data, DBG1, DBG_CFG, identification_t::destroy, gen_identity(), reauth_data_t::id, INIT, memcpy, reauth_data_t::mk, and reauth().
 {
     reauth_data_t *data;
     identification_t *permanent, *new_id;
     new_id = gen_identity(this);
     if (!new_id)
     {
         DBG1(DBG_CFG, "failed to generate identity");
         return NULL;
     }
     data = this->reauth->get(this->reauth, id);
     if (data)
     {   /* update existing entry */
         permanent = this->permanent->remove(this->permanent, data->id);
         if (permanent)
         {
             data->id->destroy(data->id);
             data->id = new_id;
             this->permanent->put(this->permanent, data->id, permanent);
         }
         else
         {
             new_id->destroy(new_id);
         }
     }
     else
     {   /* generate new entry */
         INIT(data,
             .id = new_id,
         );
         id = id->clone(id);
         this->reauth->put(this->reauth, id, data);
         this->permanent->put(this->permanent, data->id, id);
     }
     memcpy(data->mk, mk, HASH_SIZE_SHA1);
     return data->id->clone(data->id);
 }
METHOD (eap_simaka_reauth_provider_t , destroy , void , private_eap_simaka_reauth_provider_t * this)
Definition at line 160 of file eap_simaka_reauth_provider.c.
References data, enumerator_t::destroy, identification_t::destroy, enumerator_t::enumerate, free(), reauth_data_t::id, id, key, reauth(), and rng.
 {
     enumerator_t *enumerator;
     identification_t *id;
     reauth_data_t *data;
     void *key;
     enumerator = this->permanent->create_enumerator(this->permanent);
     while (enumerator->enumerate(enumerator, &key, &id))
     {
         id->destroy(id);
     }
     enumerator->destroy(enumerator);
     enumerator = this->reauth->create_enumerator(this->reauth);
     while (enumerator->enumerate(enumerator, &key, &data))
     {
         data->id->destroy(data->id);
         free(data);
     }
     enumerator->destroy(enumerator);
     this->permanent->destroy(this->permanent);
     this->reauth->destroy(this->reauth);
     this->rng->destroy(this->rng);
     free(this);
 }