strongSwan: rekey_ike_sa_job.c File Reference
rekey_ike_sa_job.c File Reference
#include "rekey_ike_sa_job.h"
#include <daemon.h>
Classes
struct private_rekey_ike_sa_job_t
Typedefs
typedef struct
private_rekey_ike_sa_job_t private_rekey_ike_sa_job_t
Functions
METHOD (job_t, destroy, void, private_rekey_ike_sa_job_t *this)
static u_int32_t get_retry_delay (ike_sa_t *ike_sa)
METHOD (job_t, execute, job_requeue_t, private_rekey_ike_sa_job_t *this)
METHOD (job_t, get_priority, job_priority_t, private_rekey_ike_sa_job_t *this)
rekey_ike_sa_job_t * rekey_ike_sa_job_create (ike_sa_id_t *ike_sa_id, bool reauth)
Typedef Documentation
typedef struct private_rekey_ike_sa_job_t private_rekey_ike_sa_job_t
Definition at line 20 of file rekey_ike_sa_job.c.
Function Documentation
static u_int32_t get_retry_delay (ike_sa_t * ike_sa) static
Check if we should delay a reauth, and by how many seconds
Definition at line 52 of file rekey_ike_sa_job.c.
References CHILD_INSTALLED, CHILD_REKEYED, child_sa_state_names, ike_sa_t::create_child_sa_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, child_sa_t::get_state, ike_sa_t::get_state, IKE_ESTABLISHED, ike_sa_state_names, random, RETRY_INTERVAL, and RETRY_JITTER.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     u_int32_t retry = 0;
     /* avoid reauth collisions for certain IKE_SA/CHILD_SA states */
     if (ike_sa->get_state(ike_sa) != IKE_ESTABLISHED)
     {
         retry = RETRY_INTERVAL - (random() % RETRY_JITTER);
         DBG1(DBG_IKE, "unable to reauthenticate in %N state, delaying for %us",
              ike_sa_state_names, ike_sa->get_state(ike_sa), retry);
     }
     else
     {
         enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
         while (enumerator->enumerate(enumerator, &child_sa))
         {
             if (child_sa->get_state(child_sa) != CHILD_INSTALLED &&
                 child_sa->get_state(child_sa) != CHILD_REKEYED)
             {
                 retry = RETRY_INTERVAL - (random() % RETRY_JITTER);
                 DBG1(DBG_IKE, "unable to reauthenticate in CHILD_SA %N state, "
                      "delaying for %us", child_sa_state_names,
                      child_sa->get_state(child_sa), retry);
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     return retry;
 }
METHOD (job_t , destroy , void , private_rekey_ike_sa_job_t * this)
Definition at line 42 of file rekey_ike_sa_job.c.
References free().
 {
     this->ike_sa_id->destroy(this->ike_sa_id);
     free(this);
 }
METHOD (job_t , execute , job_requeue_t , private_rekey_ike_sa_job_t * this)
Definition at line 85 of file rekey_ike_sa_job.c.
References charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout, DBG2, DBG_JOB, DESTROY_ME, get_retry_delay(), daemon_t::ike_sa_manager, JOB_REQUEUE_NONE, JOB_RESCHEDULE, reauth(), ike_sa_t::reauth, ike_sa_t::rekey, status, and SUCCESS.
 {
     ike_sa_t *ike_sa;
     status_t status = SUCCESS;
     u_int32_t retry = 0;
     ike_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager,
                                               this->ike_sa_id);
     if (ike_sa == NULL)
     {
         DBG2(DBG_JOB, "IKE_SA to rekey not found");
     }
     else
     {
         if (this->reauth)
         {
             retry = get_retry_delay(ike_sa);
             if (!retry)
             {
                 status = ike_sa->reauth(ike_sa);
             }
         }
         else
         {
             status = ike_sa->rekey(ike_sa);
         }
         if (status == DESTROY_ME)
         {
             charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                         ike_sa);
         }
         else
         {
             charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
         }
     }
     if (retry)
     {
         return JOB_RESCHEDULE(retry);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (job_t , get_priority , job_priority_t , private_rekey_ike_sa_job_t * this)
Definition at line 130 of file rekey_ike_sa_job.c.
References JOB_PRIO_MEDIUM.
 {
     return JOB_PRIO_MEDIUM;
 }