strongSwan: auth_cfg_wrapper.c File Reference
auth_cfg_wrapper.c File Reference
#include <library.h>
#include <utils/debug.h>
#include "auth_cfg_wrapper.h"
Classes
struct private_auth_cfg_wrapper_t
struct wrapper_enumerator_t
Typedefs
typedef struct
private_auth_cfg_wrapper_t private_auth_cfg_wrapper_t
Functions
static bool fetch_cert (wrapper_enumerator_t *enumerator, auth_rule_t *rule, void **value)
static bool enumerate (wrapper_enumerator_t *this, certificate_t **cert)
static void wrapper_enumerator_destroy (wrapper_enumerator_t *this)
METHOD (credential_set_t, create_enumerator, enumerator_t *, private_auth_cfg_wrapper_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (auth_cfg_wrapper_t, destroy, void, private_auth_cfg_wrapper_t *this)
auth_cfg_wrapper_t * auth_cfg_wrapper_create (auth_cfg_t *auth)
Typedef Documentation
typedef struct private_auth_cfg_wrapper_t private_auth_cfg_wrapper_t
Definition at line 22 of file auth_cfg_wrapper.c.
Function Documentation
static bool enumerate (wrapper_enumerator_t * this, certificate_t ** cert) static
enumerate function for wrapper_enumerator_t
Definition at line 118 of file auth_cfg_wrapper.c.
References AUTH_HELPER_AC_CERT, AUTH_HELPER_IM_CERT, AUTH_HELPER_IM_HASH_URL, AUTH_HELPER_REVOCATION_CERT, AUTH_HELPER_SUBJECT_CERT, AUTH_HELPER_SUBJECT_HASH_URL, CERT_ANY, DESTROY_IF, FALSE, fetch_cert(), certificate_t::get_public_key, certificate_t::get_type, certificate_t::has_subject, key, KEY_ANY, public, and TRUE.
Referenced by METHOD().
 {
     auth_rule_t rule;
     certificate_t *current;
     public_key_t *public;
     while (this->inner->enumerate(this->inner, &rule, &current))
     {
         if (rule == AUTH_HELPER_IM_HASH_URL ||
             rule == AUTH_HELPER_SUBJECT_HASH_URL)
         {   /* on-demand fetching of hash and url certificates */
             if (!fetch_cert(this, &rule, (void**)&current))
             {
                 continue;
             }
         }
         else if (rule != AUTH_HELPER_SUBJECT_CERT &&
                  rule != AUTH_HELPER_IM_CERT &&
                  rule != AUTH_HELPER_REVOCATION_CERT &&
                  rule != AUTH_HELPER_AC_CERT)
         {   /* handle only HELPER certificates */
             continue;
         }
         if (this->cert != CERT_ANY && this->cert != current->get_type(current))
         {   /* CERT type requested, but does not match */
             continue;
         }
         public = current->get_public_key(current);
         if (this->key != KEY_ANY && !public)
         {   /* key type requested, but no public key */
             DESTROY_IF(public);
             continue;
         }
         if (this->key != KEY_ANY && public && this->key != public->get_type(public))
         {   /* key type requested, but public key has another type */
             DESTROY_IF(public);
             continue;
         }
         DESTROY_IF(public);
         if (this->id && !current->has_subject(current, this->id))
         {   /* subject requested, but does not match */
             continue;
         }
         *cert = current;
         return TRUE;
     }
     return FALSE;
 }
static bool fetch_cert (wrapper_enumerator_t * enumerator, auth_rule_t * rule, void ** value) static
Tries to fetch a certificate that was supplied as "Hash and URL" (replaces rule type and value in place).
Definition at line 62 of file auth_cfg_wrapper.c.
References wrapper_enumerator_t::auth, AUTH_HELPER_IM_CERT, AUTH_HELPER_IM_HASH_URL, AUTH_HELPER_SUBJECT_CERT, BUILD_BLOB_ASN1_DER, BUILD_END, credential_manager_t::cache_cert, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::credmgr, library_t::creds, data, DBG1, DBG_CFG, FALSE, fetcher_manager_t::fetch, FETCH_END, library_t::fetcher, free(), certificate_t::get_ref, certificate_t::get_subject, wrapper_enumerator_t::inner, lib, chunk_t::ptr, auth_cfg_t::replace, SUCCESS, and TRUE.
Referenced by enumerate().
 {
     char *url = (char*)*value;
     if (!url)
     {
         /* fetching the certificate previously failed */
         return FALSE;
     }
     chunk_t data;
     certificate_t *cert;
     DBG1(DBG_CFG, "  fetching certificate from '%s' ...", url);
     if (lib->fetcher->fetch(lib->fetcher, url, &data, FETCH_END) != SUCCESS)
     {
         DBG1(DBG_CFG, "  fetching certificate failed");
         /* we set the item to NULL, so we can skip it */
         enumerator->auth->replace(enumerator->auth, enumerator->inner,
                                   *rule, NULL);
         return FALSE;
     }
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_BLOB_ASN1_DER, data, BUILD_END);
     free(data.ptr);
     if (!cert)
     {
         DBG1(DBG_CFG, "  parsing fetched certificate failed");
         /* we set the item to NULL, so we can skip it */
         enumerator->auth->replace(enumerator->auth, enumerator->inner,
                                   *rule, NULL);
         return FALSE;
     }
     DBG1(DBG_CFG, "  fetched certificate \"%Y\"", cert->get_subject(cert));
     lib->credmgr->cache_cert(lib->credmgr, cert);
     if (*rule == AUTH_HELPER_IM_HASH_URL)
     {
         *rule = AUTH_HELPER_IM_CERT;
     }
     else
     {
         *rule = AUTH_HELPER_SUBJECT_CERT;
     }
     *value = cert;
     enumerator->auth->replace(enumerator->auth, enumerator->inner,
                               *rule, cert->get_ref(cert));
     return TRUE;
 }
METHOD (credential_set_t , create_enumerator , enumerator_t * , private_auth_cfg_wrapper_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 176 of file auth_cfg_wrapper.c.
References wrapper_enumerator_t::auth, wrapper_enumerator_t::cert, cert, enumerator_t::destroy, enumerator_t::enumerate, enumerate(), id, wrapper_enumerator_t::id, wrapper_enumerator_t::inner, wrapper_enumerator_t::key, key, malloc_thing, wrapper_enumerator_t::public, and wrapper_enumerator_destroy().
 {
     wrapper_enumerator_t *enumerator;
     if (trusted)
     {
         return NULL;
     }
     enumerator = malloc_thing(wrapper_enumerator_t);
     enumerator->auth = this->auth;
     enumerator->cert = cert;
     enumerator->key = key;
     enumerator->id = id;
     enumerator->inner = this->auth->create_enumerator(this->auth);
     enumerator->public.enumerate = (void*)enumerate;
     enumerator->public.destroy = (void*)wrapper_enumerator_destroy;
     return &enumerator->public;
 }
METHOD (auth_cfg_wrapper_t , destroy , void , private_auth_cfg_wrapper_t * this)
Definition at line 197 of file auth_cfg_wrapper.c.
References free().
 {
     free(this);
 }
static void wrapper_enumerator_destroy (wrapper_enumerator_t * this) static
destroy function for wrapper_enumerator_t
Definition at line 170 of file auth_cfg_wrapper.c.
References free().
Referenced by METHOD().
 {
     this->inner->destroy(this->inner);
     free(this);
 }