strongSwan: eap_sim_peer
eap_sim_peer
eap_sim
Classes
struct eap_sim_peer_t
Typedefs
typedef struct eap_sim_peer_t eap_sim_peer_t
Functions
eap_sim_peer_t * eap_sim_peer_create (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_sim_peer_t eap_sim_peer_t
Definition at line 26 of file eap_sim_peer.h.
Function Documentation
eap_sim_peer_t* eap_sim_peer_create (identification_t * server, identification_t * peer)
Creates the EAP method EAP-SIM acting as peer.
Parameters
server ID of the EAP server
peer ID of the EAP peer
Returns
eap_sim_t object
Definition at line 704 of file eap_sim_peer.c.
References identification_t::clone, EAP_SIM, free(), library_t::get, INIT, lib, MAX_TRIES, and simaka_crypto_create().
Referenced by METHOD().
 {
     private_eap_sim_peer_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .destroy = _destroy,
             },
         },
         .crypto = simaka_crypto_create(EAP_SIM),
         .mgr = lib->get(lib, "sim-manager"),
     );
     if (!this->crypto)
     {
         free(this);
         return NULL;
     }
     this->permanent = peer->clone(peer);
     this->tries = MAX_TRIES;
     return &this->public;
 }