strongSwan: dn.c File Reference
dn.c File Reference
#include "pki.h"
#include <credentials/certificates/certificate.h>
#include <errno.h>
Functions
static int dn ()
static void __attribute__ ((constructor))
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 134 of file dn.c.
References command_register(), and dn().
 {
     command_register((command_t)
         { dn, 'd', "dn",
         "extract the subject DN of an X.509 certificate",
         {"[--in file] [--format config|hex|base64|bin]"},
         {
             {"help",        'h', 0, "show usage information"},
             {"in",          'i', 1, "input file, default: stdin"},
             {"format",      'f', 1, "output format, default: config"},
         }
     });
 }
static int dn () static
Extract subject DN
Definition at line 25 of file dn.c.
References BUILD_BLOB, BUILD_END, BUILD_FROM_FILE, cert, CERT_ASN1_DER, CERT_X509, chunk_free(), chunk_from_fd(), chunk_to_base64(), chunk_to_hex(), command_getopt(), command_usage(), credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, certificate_t::destroy, FALSE, fprintf, free(), identification_t::get_encoding, certificate_t::get_subject, id, chunk_t::len, lib, printf, chunk_t::ptr, set_file_mode(), streq(), strerror, and TRUE.
Referenced by __attribute__(), issue(), METHOD(), req(), and self().
 {
     identification_t *id;
     certificate_t *cert;
     chunk_t chunk;
     enum {
         FORMAT_CONFIG,
         FORMAT_HEX,
         FORMAT_BASE64,
         FORMAT_BINARY,
     } format = FORMAT_CONFIG;
     char *arg, *file = NULL, *fmt;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 'f':
                 if (streq(arg, "hex"))
                 {
                     format = FORMAT_HEX;
                 }
                 else if (streq(arg, "base64"))
                 {
                     format = FORMAT_BASE64;
                 }
                 else if (streq(arg, "bin"))
                 {
                     format = FORMAT_BINARY;
                 }
                 else if (!streq(arg, "config"))
                 {
                     return command_usage( "invalid output format");
                 }
                 continue;
             case 'i':
                 file = arg;
                 continue;
             case EOF:
                 break;
             default:
                 return command_usage("invalid --print option");
         }
         break;
     }
     if (file)
     {
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_FROM_FILE, file, BUILD_END);
     }
     else
     {
         chunk_t chunk;
         set_file_mode(stdin, CERT_ASN1_DER);
         if (!chunk_from_fd(0, &chunk))
         {
             fprintf(stderr, "reading input failed: %s\n", strerror(errno));
             return 1;
         }
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_BLOB, chunk, BUILD_END);
         free(chunk.ptr);
     }
     if (!cert)
     {
         fprintf(stderr, "parsing input failed\n");
         return 1;
     }
     id = cert->get_subject(cert);
     if (!id)
     {
         fprintf(stderr, "failed to get certificate's subject DN\n");
         cert->destroy(cert);
         return 1;
     }
     fmt = "%.*s\n";
     switch (format)
     {
         case FORMAT_CONFIG:
             fmt = "\"asn1dn:#%.*s\"\n";
             /* fall-through */
         case FORMAT_HEX:
             chunk = chunk_to_hex(id->get_encoding(id), NULL, FALSE);
             printf(fmt, (int)chunk.len, chunk.ptr);
             chunk_free(&chunk);
             break;
         case FORMAT_BASE64:
             chunk = chunk_to_base64(id->get_encoding(id), NULL);
             printf(fmt, (int)chunk.len, chunk.ptr);
             chunk_free(&chunk);
             break;
         case FORMAT_BINARY:
             chunk = id->get_encoding(id);
             if (fwrite(chunk.ptr, chunk.len, 1, stdout) != 1)
             {
                 fprintf(stderr, "writing subject DN failed\n");
             }
             break;
     }
     cert->destroy(cert);
     return 0;
 }