strongSwan: pkcs8_builder.c File Reference
pkcs8_builder.c File Reference
#include "pkcs8_builder.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <crypto/pkcs5.h>
#include <credentials/keys/private_key.h>
Macros
#define PKINFO_PRIVATE_KEY_ALGORITHM 2
#define PKINFO_PRIVATE_KEY 3
#define EPKINFO_ENCRYPTION_ALGORITHM 1
#define EPKINFO_ENCRYPTED_DATA 2
Functions
static private_key_t * parse_private_key (chunk_t blob)
static private_key_t * decrypt_private_key (pkcs5_t *pkcs5, chunk_t blob)
static private_key_t * parse_encrypted_private_key (chunk_t blob)
private_key_t * pkcs8_private_key_load (key_type_t type, va_list args)
Variables
static const asn1Object_t pkinfoObjects []
static const asn1Object_t encryptedPKIObjects []
Macro Definition Documentation
#define EPKINFO_ENCRYPTED_DATA 2
Definition at line 147 of file pkcs8_builder.c.
Referenced by parse_encrypted_private_key().
#define EPKINFO_ENCRYPTION_ALGORITHM 1
Definition at line 146 of file pkcs8_builder.c.
Referenced by parse_encrypted_private_key().
#define PKINFO_PRIVATE_KEY 3
Definition at line 38 of file pkcs8_builder.c.
Referenced by parse_private_key().
#define PKINFO_PRIVATE_KEY_ALGORITHM 2
Definition at line 37 of file pkcs8_builder.c.
Referenced by parse_private_key().
Function Documentation
static private_key_t* decrypt_private_key (pkcs5_t * pkcs5, chunk_t blob) static
Try to decrypt the given blob with multiple passwords using the given pkcs5 object.
Definition at line 108 of file pkcs8_builder.c.
References blob, chunk_clear(), chunk_free(), credential_manager_t::create_shared_enumerator, library_t::credmgr, pkcs5_t::decrypt, enumerator_t::destroy, enumerator_t::enumerate, shared_key_t::get_key, lib, parse_private_key(), private_key, and SHARED_PRIVATE_KEY_PASS.
Referenced by parse_encrypted_private_key().
 {
     enumerator_t *enumerator;
     shared_key_t *shared;
     private_key_t *private_key = NULL;
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                         SHARED_PRIVATE_KEY_PASS, NULL, NULL);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         chunk_t decrypted;
         if (!pkcs5->decrypt(pkcs5, shared->get_key(shared), blob, &decrypted))
         {
             continue;
         }
         private_key = parse_private_key(decrypted);
         if (private_key)
         {
             chunk_clear(&decrypted);
             break;
         }
         chunk_free(&decrypted);
     }
     enumerator->destroy(enumerator);
     return private_key;
 }
static private_key_t* parse_encrypted_private_key (chunk_t blob) static
Load an encrypted private key from an ASN.1 encoded blob Schemes per PKCS#5 (RFC 2898)
Definition at line 153 of file pkcs8_builder.c.
References asn1_parser_create(), decrypt_private_key(), asn1_parser_t::destroy, DESTROY_IF, end, EPKINFO_ENCRYPTED_DATA, EPKINFO_ENCRYPTION_ALGORITHM, asn1_parser_t::get_level, asn1_parser_t::iterate, key, parser, and pkcs5_from_algorithmIdentifier().
Referenced by pkcs8_private_key_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     private_key_t *key = NULL;
     pkcs5_t *pkcs5 = NULL;
     parser = asn1_parser_create(encryptedPKIObjects, blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case EPKINFO_ENCRYPTION_ALGORITHM:
             {
                 pkcs5 = pkcs5_from_algorithmIdentifier(object,
                                                 parser->get_level(parser) + 1);
                 if (!pkcs5)
                 {
                     goto end;
                 }
                 break;
             }
             case EPKINFO_ENCRYPTED_DATA:
             {
                 key = decrypt_private_key(pkcs5, object);
                 break;
             }
         }
     }
 end:
     DESTROY_IF(pkcs5);
     parser->destroy(parser);
     return key;
 }
static private_key_t* parse_private_key (chunk_t blob) static
Load a generic private key from an ASN.1 encoded blob
Definition at line 43 of file pkcs8_builder.c.
References asn1_parse_algorithmIdentifier(), asn1_parser_create(), BUILD_BLOB_ALGID_PARAMS, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, DBG2, DBG_ASN, asn1_parser_t::destroy, end, FALSE, asn1_parser_t::get_level, asn1_parser_t::iterate, key, KEY_ANY, KEY_ECDSA, KEY_RSA, lib, OID_EC_PUBLICKEY, OID_RSA_ENCRYPTION, params, parser, PKINFO_PRIVATE_KEY, PKINFO_PRIVATE_KEY_ALGORITHM, chunk_t::ptr, asn1_parser_t::set_flags, TRUE, and type.
Referenced by decrypt_private_key(), and pkcs8_private_key_load().
 {
     asn1_parser_t *parser;
     chunk_t object, params = chunk_empty;
     int objectID;
     private_key_t *key = NULL;
     key_type_t type = KEY_ANY;
     parser = asn1_parser_create(pkinfoObjects, blob);
     parser->set_flags(parser, FALSE, TRUE);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case PKINFO_PRIVATE_KEY_ALGORITHM:
             {
                 int oid = asn1_parse_algorithmIdentifier(object,
                                     parser->get_level(parser) + 1, &params);
                 switch (oid)
                 {
                     case OID_RSA_ENCRYPTION:
                         type = KEY_RSA;
                         break;
                     case OID_EC_PUBLICKEY:
                         type = KEY_ECDSA;
                         break;
                     default:
                         /* key type not supported */
                         goto end;
                 }
                 break;
             }
             case PKINFO_PRIVATE_KEY:
             {
                 DBG2(DBG_ASN, "-- > --");
                 if (params.ptr)
                 {
                     key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY,
                                              type, BUILD_BLOB_ALGID_PARAMS,
                                              params, BUILD_BLOB_ASN1_DER,
                                              object, BUILD_END);
                 }
                 else
                 {
                     key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY,
                                              type, BUILD_BLOB_ASN1_DER, object,
                                              BUILD_END);
                 }
                 DBG2(DBG_ASN, "-- < --");
                 break;
             }
         }
     }
 end:
     parser->destroy(parser);
     return key;
 }
Variable Documentation
const asn1Object_t encryptedPKIObjects[] static
Initial value:
= {
    { 0, "encryptedPrivateKeyInfo", ASN1_SEQUENCE,      ASN1_NONE   },
    { 1,   "encryptionAlgorithm",   ASN1_EOC,           ASN1_RAW    },
    { 1,   "encryptedData",         ASN1_OCTET_STRING,  ASN1_BODY   },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT   }
}
ASN.1 definition of an encryptedPrivateKeyInfo structure
Definition at line 140 of file pkcs8_builder.c.
const asn1Object_t pkinfoObjects[] static
Initial value:
= {
    { 0, "privateKeyInfo",          ASN1_SEQUENCE,      ASN1_NONE   },
    { 1,   "version",               ASN1_INTEGER,       ASN1_BODY   },
    { 1,   "privateKeyAlgorithm",   ASN1_EOC,           ASN1_RAW    },
    { 1,   "privateKey",            ASN1_OCTET_STRING,  ASN1_BODY   },
    { 1,   "attributes",            ASN1_CONTEXT_C_0,   ASN1_OPT    },
    { 1,   "end opt",               ASN1_EOC,           ASN1_END    },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT   }
}
ASN.1 definition of a privateKeyInfo structure
Definition at line 28 of file pkcs8_builder.c.