strongSwan: pts_database_t Struct Reference
pts_database_t Struct Reference
pts_database
#include "pts_database.h"
Public Attributes
char *(* get_pathname)(pts_database_t *this, bool is_dir, int id)
enumerator_t *(* create_file_hash_enumerator)(pts_database_t *this, int pid, pts_meas_algorithms_t algo, bool is_dir, int id)
status_t(* add_file_measurement)(pts_database_t *this, int pid, pts_meas_algorithms_t algo, chunk_t measurement, char *filename, bool is_dir, int id)
enumerator_t *(* create_file_meas_enumerator)(pts_database_t *this, int pid, pts_meas_algorithms_t algo, char *filename)
status_t(* check_comp_measurement)(pts_database_t *this, chunk_t measurement, int cid, int aik_id, int seq_no, int pcr, pts_meas_algorithms_t algo)
status_t(* insert_comp_measurement)(pts_database_t *this, chunk_t measurement, int cid, int aik_id, int seq_no, int pcr, pts_meas_algorithms_t algo)
int(* delete_comp_measurements)(pts_database_t *this, int cid, int aik_id)
status_t(* get_comp_measurement_count)(pts_database_t *this, pts_comp_func_name_t *comp_name, int aik_id, pts_meas_algorithms_t algo, int *cid, int *count)
void(* destroy)(pts_database_t *this)
Detailed Description
Class implementing the PTS File Measurement database
Definition at line 36 of file pts_database.h.
Member Data Documentation
status_t(* pts_database_t::add_file_measurement)(pts_database_t *this, int pid, pts_meas_algorithms_t algo, chunk_t measurement, char *filename, bool is_dir, int id)
Add PTS file measurement reference value
Parameters
pid Primary key of software product in database
algo File measurement hash algorithm used
measurement File measurement hash
filename Optional name of the file to be checked
is_dir TRUE if part of directory measurement
id Primary key into direcories/files table
Returns
Status
Definition at line 71 of file pts_database.h.
Referenced by imv_attestation_process().
status_t(* pts_database_t::check_comp_measurement)(pts_database_t *this, chunk_t measurement, int cid, int aik_id, int seq_no, int pcr, pts_meas_algorithms_t algo)
Check a functional component measurement against value stored in database
Parameters
measurement measurement hash
cid Primary key of Component Functional Name entry
aik_id Primary key of AIK entry in database
seq_no Measurement sequence number
prc Number of the PCR the measurement was extended into
algo Hash algorithm used for measurement
Returns
SUCCESS if check was successful
Definition at line 99 of file pts_database.h.
enumerator_t*(* pts_database_t::create_file_hash_enumerator)(pts_database_t *this, int pid, pts_meas_algorithms_t algo, bool is_dir, int id)
Get stored measurement hash for single file or directory entries
Parameters
pid Primary key of software product in database
algo Hash algorithm used for measurement
is_dir TRUE if directory was measured
id Primary key of measured file/directory
Returns
Enumerator over all matching measurement hashes
Definition at line 56 of file pts_database.h.
Referenced by imv_attestation_process().
enumerator_t*(* pts_database_t::create_file_meas_enumerator)(pts_database_t *this, int pid, pts_meas_algorithms_t algo, char *filename)
Get PTS measurement[s] for a given filename stored in database
Parameters
pid Primary key of software product in database
algo File measurement hash algorithm used
filename Name of the file to be checked
Returns
Enumerator over all matching measurement hashes
Definition at line 84 of file pts_database.h.
Referenced by METHOD().
int(* pts_database_t::delete_comp_measurements)(pts_database_t *this, int cid, int aik_id)
Delete functional component measurements from the database
Parameters
cid Primary key of Component Functional Name entry
aik_id Primary key of AIK entry in database
Returns
number of deleted measurement entries
Definition at line 125 of file pts_database.h.
void(* pts_database_t::destroy)(pts_database_t *this)
Destroys a pts_database_t object.
Definition at line 144 of file pts_database.h.
status_t(* pts_database_t::get_comp_measurement_count)(pts_database_t *this, pts_comp_func_name_t *comp_name, int aik_id, pts_meas_algorithms_t algo, int *cid, int *count)
Get the number of measurements for a functional component and AIK
Parameters
comp_name Component Functional Name
aik_id Primary key of AIK entry in database
algo Hash algorithm used for measurement
cid Primary key of Component Functional Name entry
count measurement count
Returns
SUCCESS if COUNT was successful
Definition at line 137 of file pts_database.h.
char*(* pts_database_t::get_pathname)(pts_database_t *this, bool is_dir, int id)
Get absolute pathname for file or directory measurement
Parameters
is_dir TRUE if dir, FALSE if file
id Primary key into directories or files table
Returns
Absolute pathname as a text string
Definition at line 45 of file pts_database.h.
status_t(* pts_database_t::insert_comp_measurement)(pts_database_t *this, chunk_t measurement, int cid, int aik_id, int seq_no, int pcr, pts_meas_algorithms_t algo)
Insert a functional component measurement into the database
Parameters
measurement Measurement hash
cid Primary key of Component Functional Name entry
aik_id Primary key of AIK entry in database
seq_no Measurement sequence number
prc Number of the PCR the measurement was extended into
algo Hash algorithm used for measurement
Returns
SUCCESS if INSERT was successful
Definition at line 114 of file pts_database.h.
The documentation for this struct was generated from the following file:
pts_database.h