strongSwan: x509_pkcs10
x509_pkcs10
x509
Classes
struct x509_pkcs10_t
Typedefs
typedef struct x509_pkcs10_t x509_pkcs10_t
Functions
x509_pkcs10_t * x509_pkcs10_load (certificate_type_t type, va_list args)
x509_pkcs10_t * x509_pkcs10_gen (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct x509_pkcs10_t x509_pkcs10_t
Definition at line 26 of file x509_pkcs10.h.
Function Documentation
x509_pkcs10_t* x509_pkcs10_gen (certificate_type_t type, va_list args)
Generate a PKCS#10 certificate request.
To issue a self-signed certificate request, the function takes: BUILD_SUBJECT, BUILD_SUBJECT_ALTNAMES, BUILD_SIGNING_KEY, BUILD_DIGEST_ALG.
Parameters
type certificate type, CERT_PKCS10_REQUEST only
args builder_part_t argument list
Returns
PKCS#10 certificate request, NULL on failure
See header.
Definition at line 634 of file x509_pkcs10.c.
References BUILD_CHALLENGE_PWD, BUILD_DIGEST_ALG, BUILD_END, BUILD_SIGNING_KEY, BUILD_SUBJECT, BUILD_SUBJECT_ALTNAMES, cert, private_x509_pkcs10_t::challengePassword, chunk_clone, identification_t::clone, create_empty(), linked_list_t::create_enumerator, enumerator_t::destroy, destroy(), enumerator_t::enumerate, generate(), HASH_SHA1, id, linked_list_t::insert_last, list, private_x509_pkcs10_t::public, private_x509_pkcs10_t::subject, private_x509_pkcs10_t::subjectAltNames, and TRUE.
Referenced by METHOD().
 {
     private_x509_pkcs10_t *cert;
     private_key_t *sign_key = NULL;
     hash_algorithm_t digest_alg = HASH_SHA1;
     cert = create_empty();
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_SIGNING_KEY:
                 sign_key = va_arg(args, private_key_t*);
                 continue;
             case BUILD_SUBJECT:
                 cert->subject = va_arg(args, identification_t*);
                 cert->subject = cert->subject->clone(cert->subject);
                 continue;
             case BUILD_SUBJECT_ALTNAMES:
             {
                 enumerator_t *enumerator;
                 identification_t *id;
                 linked_list_t *list;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &id))
                 {
                     cert->subjectAltNames->insert_last(cert->subjectAltNames,
                                                        id->clone(id));
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_CHALLENGE_PWD:
                 cert->challengePassword = chunk_clone(va_arg(args, chunk_t));
                 continue;
             case BUILD_DIGEST_ALG:
                 digest_alg = va_arg(args, int);
                 continue;
             case BUILD_END:
                 break;
             default:
                 destroy(cert);
                 return NULL;
         }
         break;
     }
     if (sign_key && generate(cert, sign_key, digest_alg))
     {
         return &cert->public;
     }
     destroy(cert);
     return NULL;
 }
x509_pkcs10_t* x509_pkcs10_load (certificate_type_t type, va_list args)
Load a PKCS#10 certificate.
This function takes a BUILD_BLOB_ASN1_DER.
Parameters
type certificate type, CERT_PKCS10_REQUEST only
args builder_part_t argument list
Returns
PKCS#10 certificate request, NULL on failure
See header.
Definition at line 597 of file x509_pkcs10.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, cert, chunk_clone, chunk_empty, create_empty(), destroy(), private_x509_pkcs10_t::encoding, parse_certificate_request(), private_x509_pkcs10_t::parsed, chunk_t::ptr, private_x509_pkcs10_t::public, and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.ptr)
     {
         private_x509_pkcs10_t *cert = create_empty();
         cert->encoding = chunk_clone(blob);
         cert->parsed = TRUE;
         if (parse_certificate_request(cert))
         {
             return &cert->public;
         }
         destroy(cert);
     }
     return NULL;
 }