strongSwan: seg_contract_t Struct Reference
seg_contract_t Struct Reference
seg_contract
#include "seg_contract.h"
Public Attributes
pen_type_t(* get_msg_type)(seg_contract_t *this)
void(* set_max_size)(seg_contract_t *this, uint32_t max_attr_size, uint32_t max_seg_size)
void(* get_max_size)(seg_contract_t *this, uint32_t *max_attr_size, uint32_t *max_seg_size)
bool(* check_size)(seg_contract_t *this, pa_tnc_attr_t *attr, bool *oversize)
pa_tnc_attr_t *(* first_segment)(seg_contract_t *this, pa_tnc_attr_t *attr, size_t max_attr_len)
pa_tnc_attr_t *(* next_segment)(seg_contract_t *this, uint32_t base_attr_id)
pa_tnc_attr_t *(* add_segment)(seg_contract_t *this, pa_tnc_attr_t *attr, pa_tnc_attr_t **error, bool *more)
bool(* is_issuer)(seg_contract_t *this)
bool(* is_null)(seg_contract_t *this)
void(* set_responder)(seg_contract_t *this, TNC_UInt32 responder)
TNC_UInt32(* get_responder)(seg_contract_t *this)
TNC_UInt32(* get_issuer)(seg_contract_t *this)
seg_contract_t *(* clone)(seg_contract_t *this)
void(* get_info_string)(seg_contract_t *this, char *buf, size_t len, bool request)
void(* destroy)(seg_contract_t *this)
Detailed Description
Interface for a PA-TNC attribute segmentation contract
Definition at line 40 of file seg_contract.h.
Member Data Documentation
pa_tnc_attr_t*(* seg_contract_t::add_segment)(seg_contract_t *this, pa_tnc_attr_t *attr, pa_tnc_attr_t **error, bool *more)
Add an attribute segments until the PA-TNC attribute is reconstructed
Parameters
attr Segment envelope attribute
error Error attribute if an error occurred or NULL
more Need more segments
Returns
Completed PA-TNC attribute or NULL
Definition at line 103 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
bool(* seg_contract_t::check_size)(seg_contract_t *this, pa_tnc_attr_t *attr, bool *oversize)
Check if a PA-TNC attribute must be segmented or is oversized
Parameters
attr PA-TNC attribute to be checked
oversize PA-TNC attribute is larger than maximum size
Returns
TRUE if PA-TNC attribute must be segmented
Definition at line 74 of file seg_contract.h.
Referenced by METHOD().
seg_contract_t*(* seg_contract_t::clone)(seg_contract_t *this)
Clone a contract
Returns
Cloned contract
Definition at line 148 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
void(* seg_contract_t::destroy)(seg_contract_t *this)
Destroys a seg_contract_t object.
Definition at line 163 of file seg_contract.h.
Referenced by START_TEST().
pa_tnc_attr_t*(* seg_contract_t::first_segment)(seg_contract_t *this, pa_tnc_attr_t *attr, size_t max_attr_len)
Generate first segment of a PA-TNC attribute according to the contract
Parameters
attr PA-TNC attribute to be segmented
max_attr_len Maximum size of first segment envelope attribute
Returns
First segment envelope attribute
Definition at line 84 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
void(* seg_contract_t::get_info_string)(seg_contract_t *this, char *buf, size_t len, bool request)
Get an info string about the contract
Parameters
buf String buffer of at least size len
len Size of string buffer
request TRUE if contract request, FALSE if response
Definition at line 157 of file seg_contract.h.
Referenced by METHOD(), START_TEST(), and TNC_IMC_BeginHandshake().
TNC_UInt32(* seg_contract_t::get_issuer)(seg_contract_t *this)
Get the issuer ID
Returns
IMC or IMV ID of issuer
Definition at line 141 of file seg_contract.h.
Referenced by METHOD().
void(* seg_contract_t::get_max_size)(seg_contract_t *this, uint32_t *max_attr_size, uint32_t *max_seg_size)
Get maximum PA-TNC attribute and segment size in octets
Parameters
max_attr_size Maximum PA-TNC attribute size in octets
max_seg_size Maximum PA-TNC attribute segment size in octets
Definition at line 64 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
pen_type_t(* seg_contract_t::get_msg_type)(seg_contract_t *this)
Get the PA-TNC message type.
Returns
PA-TNC Message type
Definition at line 47 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
TNC_UInt32(* seg_contract_t::get_responder)(seg_contract_t *this)
Get the responder ID
Returns
IMC or IMV ID of responder
Definition at line 134 of file seg_contract.h.
Referenced by METHOD().
bool(* seg_contract_t::is_issuer)(seg_contract_t *this)
Get contract role
Returns
TRUE: contracting party (issuer), FALSE: contracted party
Definition at line 113 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
bool(* seg_contract_t::is_null)(seg_contract_t *this)
Is this a null contract ?
Returns
TRUE if null contract
Definition at line 120 of file seg_contract.h.
Referenced by START_TEST().
pa_tnc_attr_t*(* seg_contract_t::next_segment)(seg_contract_t *this, uint32_t base_attr_id)
Generate next segment of a PA-TNC attribute according to the contract
Parameters
base_attr_id Base Attribute ID
Returns
Next segment envelope attribute
Definition at line 93 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
void(* seg_contract_t::set_max_size)(seg_contract_t *this, uint32_t max_attr_size, uint32_t max_seg_size)
Set maximum PA-TNC attribute and segment size in octets
Parameters
max_attr_size Maximum PA-TNC attribute size in octets
max_seg_size Maximum PA-TNC attribute segment size in octets
Definition at line 55 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
void(* seg_contract_t::set_responder)(seg_contract_t *this, TNC_UInt32 responder)
Set the responder ID
Parameters
responder IMC or IMV ID of responder
Definition at line 127 of file seg_contract.h.
Referenced by METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
seg_contract.h