strongSwan: tcg_pts_attr_req_file_meas.c File Reference
tcg_pts_attr_req_file_meas.c File Reference
#include <string.h>
#include "tcg_pts_attr_req_file_meas.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_req_file_meas_t
Macros
#define _GNU_SOURCE /* for stdndup() */
#define PTS_REQ_FILE_MEAS_SIZE 8
#define PTS_REQ_FILE_MEAS_RESERVED 0x00
#define PTS_REQ_FILE_MEAS_NO_FLAGS 0x00
#define DIRECTORY_CONTENTS_FLAG (1<<7)
Typedefs
typedef struct
private_tcg_pts_attr_req_file_meas_t private_tcg_pts_attr_req_file_meas_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_req_file_meas_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_req_file_meas_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_req_file_meas_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (tcg_pts_attr_req_file_meas_t, get_directory_flag, bool, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (tcg_pts_attr_req_file_meas_t, get_request_id, u_int16_t, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (tcg_pts_attr_req_file_meas_t, get_delimiter, u_int32_t, private_tcg_pts_attr_req_file_meas_t *this)
METHOD (tcg_pts_attr_req_file_meas_t, get_pathname, char *, private_tcg_pts_attr_req_file_meas_t *this)
pa_tnc_attr_t * tcg_pts_attr_req_file_meas_create (bool directory_flag, u_int16_t request_id, u_int32_t delimiter, char *pathname)
pa_tnc_attr_t * tcg_pts_attr_req_file_meas_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 17 of file tcg_pts_attr_req_file_meas.c.
#define DIRECTORY_CONTENTS_FLAG (1<<7)
Definition at line 48 of file tcg_pts_attr_req_file_meas.c.
Referenced by METHOD().
#define PTS_REQ_FILE_MEAS_NO_FLAGS 0x00
Definition at line 46 of file tcg_pts_attr_req_file_meas.c.
Referenced by METHOD().
#define PTS_REQ_FILE_MEAS_RESERVED 0x00
Definition at line 45 of file tcg_pts_attr_req_file_meas.c.
Referenced by METHOD().
#define PTS_REQ_FILE_MEAS_SIZE 8
Request File Measurement see section 3.19.1 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | Reserved | Request ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Delimiter | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Fully Qualified File Pathname (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 44 of file tcg_pts_attr_req_file_meas.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_req_file_meas_t private_tcg_pts_attr_req_file_meas_t
Definition at line 27 of file tcg_pts_attr_req_file_meas.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 106 of file tcg_pts_attr_req_file_meas.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 112 of file tcg_pts_attr_req_file_meas.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 118 of file tcg_pts_attr_req_file_meas.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_req_file_meas_t * this, bool noskip)
Definition at line 124 of file tcg_pts_attr_req_file_meas.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 130 of file tcg_pts_attr_req_file_meas.c.
References bio_writer_create(), chunk_create(), bio_writer_t::destroy, DIRECTORY_CONTENTS_FLAG, bio_writer_t::extract_buf, flags, length, PTS_REQ_FILE_MEAS_NO_FLAGS, PTS_REQ_FILE_MEAS_RESERVED, PTS_REQ_FILE_MEAS_SIZE, value, bio_writer_t::write_data, bio_writer_t::write_uint16, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     u_int8_t flags = PTS_REQ_FILE_MEAS_NO_FLAGS;
     chunk_t pathname;
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     if (this->directory_flag)
     {
         flags |= DIRECTORY_CONTENTS_FLAG;
     }
     pathname = chunk_create(this->pathname, strlen(this->pathname));
     writer = bio_writer_create(PTS_REQ_FILE_MEAS_SIZE);
     writer->write_uint8 (writer, flags);
     writer->write_uint8 (writer, PTS_REQ_FILE_MEAS_RESERVED);
     writer->write_uint16(writer, this->request_id);
     writer->write_uint32(writer, this->delimiter);
     writer->write_data  (writer, pathname);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_req_file_meas_t * this, u_int32_t * offset)
Definition at line 158 of file tcg_pts_attr_req_file_meas.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, DIRECTORY_CONTENTS_FLAG, FAILED, flags, chunk_t::len, NEED_MORE, chunk_t::ptr, PTS_REQ_FILE_MEAS_NO_FLAGS, PTS_REQ_FILE_MEAS_SIZE, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, strndup(), SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int8_t flags;
     u_int8_t reserved;
     chunk_t pathname;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_REQ_FILE_MEAS_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for Request File Measurement");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &flags);
     reader->read_uint8 (reader, &reserved);
     reader->read_uint16(reader, &this->request_id);
     reader->read_uint32(reader, &this->delimiter);
     reader->read_data  (reader, reader->remaining(reader), &pathname);
     this->directory_flag = (flags & DIRECTORY_CONTENTS_FLAG) !=
                             PTS_REQ_FILE_MEAS_NO_FLAGS;
     this->pathname = strndup(pathname.ptr, pathname.len);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_req_file_meas_t * this, chunk_t segment)
Definition at line 193 of file tcg_pts_attr_req_file_meas.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 199 of file tcg_pts_attr_req_file_meas.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 206 of file tcg_pts_attr_req_file_meas.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->pathname);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_req_file_meas_t , get_directory_flag , bool , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 217 of file tcg_pts_attr_req_file_meas.c.
 {
     return this->directory_flag;
 }
METHOD (tcg_pts_attr_req_file_meas_t , get_request_id , u_int16_t , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 223 of file tcg_pts_attr_req_file_meas.c.
 {
     return this->request_id;
 }
METHOD (tcg_pts_attr_req_file_meas_t , get_delimiter , u_int32_t , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 229 of file tcg_pts_attr_req_file_meas.c.
 {
     return this->delimiter;
 }
METHOD (tcg_pts_attr_req_file_meas_t , get_pathname , char * , private_tcg_pts_attr_req_file_meas_t * this)
Definition at line 235 of file tcg_pts_attr_req_file_meas.c.
 {
     return this->pathname;
 }