strongSwan: isakmp_dpd.c File Reference
isakmp_dpd.c File Reference
#include "isakmp_dpd.h"
#include <daemon.h>
#include <encoding/payloads/notify_payload.h>
Classes
struct private_isakmp_dpd_t
Typedefs
typedef struct private_isakmp_dpd_t private_isakmp_dpd_t
Functions
METHOD (task_t, build, status_t, private_isakmp_dpd_t *this, message_t *message)
METHOD (task_t, process, status_t, private_isakmp_dpd_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_isakmp_dpd_t *this)
METHOD (task_t, migrate, void, private_isakmp_dpd_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_isakmp_dpd_t *this)
isakmp_dpd_t * isakmp_dpd_create (ike_sa_t *ike_sa, notify_type_t type, u_int32_t seqnr)
Typedef Documentation
typedef struct private_isakmp_dpd_t private_isakmp_dpd_t
Definition at line 21 of file isakmp_dpd.c.
Function Documentation
METHOD (task_t , build , status_t , private_isakmp_dpd_t * this, message_t * message)
Definition at line 49 of file isakmp_dpd.c.
References message_t::add_payload, chunk_cata, chunk_from_thing, ike_sa_id_t::get_initiator_spi, ike_sa_id_t::get_responder_spi, notify(), notify_payload_create_from_protocol_and_type(), PLV1_NOTIFY, PROTO_IKE, notify_payload_t::set_notification_data, notify_payload_t::set_spi_data, SUCCESS, and type.
 {
     notify_payload_t *notify;
     ike_sa_id_t *ike_sa_id;
     u_int64_t spi_i, spi_r;
     u_int32_t seqnr;
     chunk_t spi;
     notify = notify_payload_create_from_protocol_and_type(PLV1_NOTIFY,
                                                           PROTO_IKE, this->type);
     seqnr = htonl(this->seqnr);
     ike_sa_id = this->ike_sa->get_id(this->ike_sa);
     spi_i = ike_sa_id->get_initiator_spi(ike_sa_id);
     spi_r = ike_sa_id->get_responder_spi(ike_sa_id);
     spi = chunk_cata("cc", chunk_from_thing(spi_i), chunk_from_thing(spi_r));
     notify->set_spi_data(notify, spi);
     notify->set_notification_data(notify, chunk_from_thing(seqnr));
     message->add_payload(message, (payload_t*)notify);
     return SUCCESS;
 }
METHOD (task_t , process , status_t , private_isakmp_dpd_t * this, message_t * message)
Definition at line 74 of file isakmp_dpd.c.
References FAILED.
 {
     /* done in task manager */
     return FAILED;
 }
METHOD (task_t , get_type , task_type_t , private_isakmp_dpd_t * this)
Definition at line 81 of file isakmp_dpd.c.
References TASK_ISAKMP_DPD.
 {
     return TASK_ISAKMP_DPD;
 }
METHOD (task_t , migrate , void , private_isakmp_dpd_t * this, ike_sa_t * ike_sa)
Definition at line 87 of file isakmp_dpd.c.
 {
     this->ike_sa = ike_sa;
 }
METHOD (task_t , destroy , void , private_isakmp_dpd_t * this)
Definition at line 93 of file isakmp_dpd.c.
References free().
 {
     free(this);
 }