strongSwan: crypto_factory.c File Reference
crypto_factory.c File Reference
#include "crypto_factory.h"
#include <utils/debug.h>
#include <threading/rwlock.h>
#include <collections/linked_list.h>
#include <crypto/crypto_tester.h>
#include <utils/test.h>
Classes
struct entry_t
struct private_crypto_factory_t
struct verify_enumerator_t
Typedefs
typedef struct entry_t entry_t
typedef struct
private_crypto_factory_t private_crypto_factory_t
Functions
METHOD (crypto_factory_t, create_crypter, crypter_t *, private_crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size)
METHOD (crypto_factory_t, create_aead, aead_t *, private_crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, size_t salt_size)
METHOD (crypto_factory_t, create_signer, signer_t *, private_crypto_factory_t *this, integrity_algorithm_t algo)
METHOD (crypto_factory_t, create_hasher, hasher_t *, private_crypto_factory_t *this, hash_algorithm_t algo)
METHOD (crypto_factory_t, create_prf, prf_t *, private_crypto_factory_t *this, pseudo_random_function_t algo)
METHOD (crypto_factory_t, create_rng, rng_t *, private_crypto_factory_t *this, rng_quality_t quality)
METHOD (crypto_factory_t, create_nonce_gen, nonce_gen_t *, private_crypto_factory_t *this)
METHOD (crypto_factory_t, create_dh, diffie_hellman_t *, private_crypto_factory_t *this, diffie_hellman_group_t group,...)
static void add_entry (private_crypto_factory_t *this, linked_list_t *list, int algo, const char *plugin_name, u_int speed, void *create)
METHOD (crypto_factory_t, add_crypter, bool, private_crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, const char *plugin_name, crypter_constructor_t create)
METHOD (crypto_factory_t, remove_crypter, void, private_crypto_factory_t *this, crypter_constructor_t create)
METHOD (crypto_factory_t, add_aead, bool, private_crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, const char *plugin_name, aead_constructor_t create)
METHOD (crypto_factory_t, remove_aead, void, private_crypto_factory_t *this, aead_constructor_t create)
METHOD (crypto_factory_t, add_signer, bool, private_crypto_factory_t *this, integrity_algorithm_t algo, const char *plugin_name, signer_constructor_t create)
METHOD (crypto_factory_t, remove_signer, void, private_crypto_factory_t *this, signer_constructor_t create)
METHOD (crypto_factory_t, add_hasher, bool, private_crypto_factory_t *this, hash_algorithm_t algo, const char *plugin_name, hasher_constructor_t create)
METHOD (crypto_factory_t, remove_hasher, void, private_crypto_factory_t *this, hasher_constructor_t create)
METHOD (crypto_factory_t, add_prf, bool, private_crypto_factory_t *this, pseudo_random_function_t algo, const char *plugin_name, prf_constructor_t create)
METHOD (crypto_factory_t, remove_prf, void, private_crypto_factory_t *this, prf_constructor_t create)
METHOD (crypto_factory_t, add_rng, bool, private_crypto_factory_t *this, rng_quality_t quality, const char *plugin_name, rng_constructor_t create)
METHOD (crypto_factory_t, remove_rng, void, private_crypto_factory_t *this, rng_constructor_t create)
METHOD (crypto_factory_t, add_nonce_gen, bool, private_crypto_factory_t *this, const char *plugin_name, nonce_gen_constructor_t create)
METHOD (crypto_factory_t, remove_nonce_gen, void, private_crypto_factory_t *this, nonce_gen_constructor_t create)
METHOD (crypto_factory_t, add_dh, bool, private_crypto_factory_t *this, diffie_hellman_group_t group, const char *plugin_name, dh_constructor_t create)
METHOD (crypto_factory_t, remove_dh, void, private_crypto_factory_t *this, dh_constructor_t create)
static bool entry_match (entry_t *a, entry_t *b)
static bool unique_check (linked_list_t *list, entry_t **in, entry_t **out)
static enumerator_t * create_enumerator (private_crypto_factory_t *this, linked_list_t *list, void *filter)
static bool crypter_filter (void *n, entry_t **entry, encryption_algorithm_t *algo, void *i2, const char **plugin_name)
METHOD (crypto_factory_t, create_crypter_enumerator, enumerator_t *, private_crypto_factory_t *this)
METHOD (crypto_factory_t, create_aead_enumerator, enumerator_t *, private_crypto_factory_t *this)
static bool signer_filter (void *n, entry_t **entry, integrity_algorithm_t *algo, void *i2, const char **plugin_name)
METHOD (crypto_factory_t, create_signer_enumerator, enumerator_t *, private_crypto_factory_t *this)
static bool hasher_filter (void *n, entry_t **entry, hash_algorithm_t *algo, void *i2, const char **plugin_name)
METHOD (crypto_factory_t, create_hasher_enumerator, enumerator_t *, private_crypto_factory_t *this)
static bool prf_filter (void *n, entry_t **entry, pseudo_random_function_t *algo, void *i2, const char **plugin_name)
METHOD (crypto_factory_t, create_prf_enumerator, enumerator_t *, private_crypto_factory_t *this)
static bool dh_filter (void *n, entry_t **entry, diffie_hellman_group_t *group, void *i2, const char **plugin_name)
METHOD (crypto_factory_t, create_dh_enumerator, enumerator_t *, private_crypto_factory_t *this)
static bool rng_filter (void *n, entry_t **entry, rng_quality_t *quality, void *i2, const char **plugin_name)
METHOD (crypto_factory_t, create_rng_enumerator, enumerator_t *, private_crypto_factory_t *this)
static bool nonce_gen_filter (void *n, entry_t **entry, const char **plugin_name)
METHOD (crypto_factory_t, create_nonce_gen_enumerator, enumerator_t *, private_crypto_factory_t *this)
METHOD (crypto_factory_t, add_test_vector, void, private_crypto_factory_t *this, transform_type_t type, void *vector)
METHOD (enumerator_t, verify_enumerate, bool, verify_enumerator_t *this, u_int *alg, const char **plugin, bool *valid)
METHOD (enumerator_t, verify_destroy, void, verify_enumerator_t *this)
METHOD (crypto_factory_t, create_verify_enumerator, enumerator_t *, private_crypto_factory_t *this, transform_type_t type)
METHOD (crypto_factory_t, destroy, void, private_crypto_factory_t *this)
crypto_factory_t * crypto_factory_create ()
Variables
const char * default_plugin_name = "default"
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 27 of file crypto_factory.c.
typedef struct private_crypto_factory_t private_crypto_factory_t
Definition at line 61 of file crypto_factory.c.
Function Documentation
static void add_entry (private_crypto_factory_t * this, linked_list_t * list, int algo, const char * plugin_name, u_int speed, void * create) static
Insert an algorithm entry to a list
Entries maintain the order in which algorithms were added, unless they were benchmarked and speed is provided, which then is used to order entries of the same algorithm. An exception are RNG entries, which are sorted by algorithm identifier.
Definition at line 406 of file crypto_factory.c.
References entry_t::algo, create, entry_t::create, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, INIT, linked_list_t::insert_before, lock, entry_t::speed, TRUE, and spinlock_t::unlock.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry, *current;
     bool sort = (list == this->rngs), found = FALSE;
     INIT(entry,
         .algo = algo,
         .plugin_name = plugin_name,
         .speed = speed,
     );
     entry->create = create;
     this->lock->write_lock(this->lock);
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (sort && current->algo > algo)
         {
             break;
         }
         else if (current->algo == algo)
         {
             if (speed > current->speed)
             {
                 break;
             }
             found = TRUE;
         }
         else if (found)
         {
             break;
         }
     }
     list->insert_before(list, enumerator, entry);
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
static enumerator_t* create_enumerator (private_crypto_factory_t * this, linked_list_t * list, void * filter) static
create an enumerator over entry->algo in list with locking and unique check
Definition at line 759 of file crypto_factory.c.
References linked_list_t::create_enumerator, linked_list_t::destroy, enumerator_create_filter(), filter(), linked_list_create(), lock, unique_check(), and spinlock_t::unlock.
Referenced by algo_list_equals(), auth_cfg_create(), check_proposal(), filter_suite(), find_value(), generate(), hashtable_create(), merge(), METHOD(), print_alg(), and select_algo().
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(
                 enumerator_create_filter(
                     list->create_enumerator(list), (void*)unique_check,
                     linked_list_create(), (void*)list->destroy),
                 filter, this->lock, (void*)this->lock->unlock);
 }
static bool crypter_filter (void * n, entry_t ** entry, encryption_algorithm_t * algo, void * i2, const char ** plugin_name) static
Filter function to enumerate algorithm, not entry
Definition at line 773 of file crypto_factory.c.
References TRUE.
Referenced by METHOD().
 {
     *algo = (*entry)->algo;
     *plugin_name = (*entry)->plugin_name;
     return TRUE;
 }
static bool dh_filter (void * n, entry_t ** entry, diffie_hellman_group_t * group, void * i2, const char ** plugin_name) static
Filter function to enumerate group, not entry
Definition at line 847 of file crypto_factory.c.
References TRUE.
Referenced by METHOD().
 {
     *group = (*entry)->algo;
     *plugin_name = (*entry)->plugin_name;
     return TRUE;
 }
static bool entry_match (entry_t * a, entry_t * b) static
match algorithms of an entry?
Definition at line 737 of file crypto_factory.c.
References entry_t::algo.
Referenced by unique_check().
 {
     return a->algo == b->algo;
 }
static bool hasher_filter (void * n, entry_t ** entry, hash_algorithm_t * algo, void * i2, const char ** plugin_name) static
Filter function to enumerate algorithm, not entry
Definition at line 813 of file crypto_factory.c.
References TRUE.
Referenced by METHOD().
 {
     *algo = (*entry)->algo;
     *plugin_name = (*entry)->plugin_name;
     return TRUE;
 }
METHOD (crypto_factory_t , create_crypter , crypter_t * , private_crypto_factory_t * this, encryption_algorithm_t algo, size_t key_size)
Definition at line 144 of file crypto_factory.c.
References entry_t::algo, entry_t::create_crypter, crypter, default_plugin_name, enumerator_t::destroy, enumerator_t::enumerate, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     crypter_t *crypter = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->crypters->create_enumerator(this->crypters);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->algo == algo)
         {
             if (this->test_on_create &&
                 !this->tester->test_crypter(this->tester, algo, key_size,
                                             entry->create_crypter, NULL,
                                             default_plugin_name))
             {
                 continue;
             }
             crypter = entry->create_crypter(algo, key_size);
             if (crypter)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return crypter;
 }
METHOD (crypto_factory_t , create_aead , aead_t * , private_crypto_factory_t * this, encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Definition at line 177 of file crypto_factory.c.
References aead, entry_t::algo, entry_t::create_aead, default_plugin_name, enumerator_t::destroy, enumerator_t::enumerate, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     aead_t *aead = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->aeads->create_enumerator(this->aeads);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->algo == algo)
         {
             if (this->test_on_create &&
                 !this->tester->test_aead(this->tester, algo, key_size,
                                          salt_size, entry->create_aead, NULL,
                                          default_plugin_name))
             {
                 continue;
             }
             aead = entry->create_aead(algo, key_size, salt_size);
             if (aead)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return aead;
 }
METHOD (crypto_factory_t , create_signer , signer_t * , private_crypto_factory_t * this, integrity_algorithm_t algo)
Definition at line 210 of file crypto_factory.c.
References entry_t::algo, entry_t::create_signer, default_plugin_name, enumerator_t::destroy, enumerator_t::enumerate, lock, signer, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     signer_t *signer = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->signers->create_enumerator(this->signers);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->algo == algo)
         {
             if (this->test_on_create &&
                 !this->tester->test_signer(this->tester, algo,
                                            entry->create_signer, NULL,
                                            default_plugin_name))
             {
                 continue;
             }
             signer = entry->create_signer(algo);
             if (signer)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return signer;
 }
METHOD (crypto_factory_t , create_hasher , hasher_t * , private_crypto_factory_t * this, hash_algorithm_t algo)
Definition at line 242 of file crypto_factory.c.
References entry_t::algo, entry_t::create_hasher, default_plugin_name, enumerator_t::destroy, enumerator_t::enumerate, hasher, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     hasher_t *hasher = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->hashers->create_enumerator(this->hashers);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->algo == algo)
         {
             if (this->test_on_create &&
                 !this->tester->test_hasher(this->tester, algo,
                                            entry->create_hasher, NULL,
                                            default_plugin_name))
             {
                 continue;
             }
             hasher = entry->create_hasher(entry->algo);
             if (hasher)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return hasher;
 }
METHOD (crypto_factory_t , create_prf , prf_t * , private_crypto_factory_t * this, pseudo_random_function_t algo)
Definition at line 274 of file crypto_factory.c.
References entry_t::algo, entry_t::create_prf, default_plugin_name, enumerator_t::destroy, enumerator_t::enumerate, lock, prf, prfs, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     prf_t *prf = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->prfs->create_enumerator(this->prfs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->algo == algo)
         {
             if (this->test_on_create &&
                 !this->tester->test_prf(this->tester, algo,
                                         entry->create_prf, NULL,
                                         default_plugin_name))
             {
                 continue;
             }
             prf = entry->create_prf(algo);
             if (prf)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return prf;
 }
METHOD (crypto_factory_t , create_rng , rng_t * , private_crypto_factory_t * this, rng_quality_t quality)
Definition at line 306 of file crypto_factory.c.
References entry_t::algo, entry_t::create_rng, default_plugin_name, enumerator_t::destroy, enumerator_t::enumerate, lock, rng, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     rng_t *rng = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->rngs->create_enumerator(this->rngs);
     while (enumerator->enumerate(enumerator, &entry))
     {   /* find the best matching quality, but at least as good as requested */
         if (entry->algo >= quality)
         {
             if (this->test_on_create &&
                 !this->tester->test_rng(this->tester, quality,
                                         entry->create_rng, NULL,
                                         default_plugin_name))
             {
                 continue;
             }
             rng = entry->create_rng(quality);
             if (rng)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return rng;
 }
METHOD (crypto_factory_t , create_nonce_gen , nonce_gen_t * , private_crypto_factory_t * this)
Definition at line 338 of file crypto_factory.c.
References entry_t::create_nonce_gen, enumerator_t::destroy, enumerator_t::enumerate, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     nonce_gen_t *nonce_gen = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->nonce_gens->create_enumerator(this->nonce_gens);
     while (enumerator->enumerate(enumerator, &entry))
     {
         nonce_gen = entry->create_nonce_gen();
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return nonce_gen;
 }
METHOD (crypto_factory_t , create_dh , diffie_hellman_t * , private_crypto_factory_t * this, diffie_hellman_group_t group, ...)
Definition at line 357 of file crypto_factory.c.
References entry_t::algo, chunk_empty, entry_t::create_dh, default_plugin_name, enumerator_t::destroy, enumerator_t::enumerate, g, lock, MODP_CUSTOM, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     va_list args;
     chunk_t g = chunk_empty, p = chunk_empty;
     diffie_hellman_t *diffie_hellman = NULL;
     if (group == MODP_CUSTOM)
     {
         va_start(args, group);
         g = va_arg(args, chunk_t);
         p = va_arg(args, chunk_t);
         va_end(args);
     }
     this->lock->read_lock(this->lock);
     enumerator = this->dhs->create_enumerator(this->dhs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->algo == group)
         {
             if (this->test_on_create && group != MODP_CUSTOM &&
                 !this->tester->test_dh(this->tester, group,
                                 entry->create_dh, NULL, default_plugin_name))
             {
                 continue;
             }
             diffie_hellman = entry->create_dh(group, g, p);
             if (diffie_hellman)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return diffie_hellman;
 }
METHOD (crypto_factory_t , add_crypter , bool , private_crypto_factory_t * this, encryption_algorithm_t algo, size_t key_size, const char * plugin_name, crypter_constructor_t create)
Definition at line 447 of file crypto_factory.c.
References add_entry(), FALSE, and TRUE.
 {
     u_int speed = 0;
     if (!this->test_on_add ||
         this->tester->test_crypter(this->tester, algo, key_size, create,
                                    this->bench ? &speed : NULL, plugin_name))
     {
         add_entry(this, this->crypters, algo, plugin_name, speed, create);
         return TRUE;
     }
     this->test_failures++;
     return FALSE;
 }
METHOD (crypto_factory_t , remove_crypter , void , private_crypto_factory_t * this, crypter_constructor_t create)
Definition at line 464 of file crypto_factory.c.
References entry_t::create_crypter, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->crypters->create_enumerator(this->crypters);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_crypter == create)
         {
             this->crypters->remove_at(this->crypters, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , add_aead , bool , private_crypto_factory_t * this, encryption_algorithm_t algo, size_t key_size, const char * plugin_name, aead_constructor_t create)
Definition at line 484 of file crypto_factory.c.
References add_entry(), FALSE, and TRUE.
 {
     u_int speed = 0;
     if (!this->test_on_add ||
         this->tester->test_aead(this->tester, algo, key_size, 0, create,
                                 this->bench ? &speed : NULL, plugin_name))
     {
         add_entry(this, this->aeads, algo, plugin_name, speed, create);
         return TRUE;
     }
     this->test_failures++;
     return FALSE;
 }
METHOD (crypto_factory_t , remove_aead , void , private_crypto_factory_t * this, aead_constructor_t create)
Definition at line 501 of file crypto_factory.c.
References entry_t::create_aead, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->aeads->create_enumerator(this->aeads);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_aead == create)
         {
             this->aeads->remove_at(this->aeads, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , add_signer , bool , private_crypto_factory_t * this, integrity_algorithm_t algo, const char * plugin_name, signer_constructor_t create)
Definition at line 521 of file crypto_factory.c.
References add_entry(), FALSE, and TRUE.
 {
     u_int speed = 0;
     if (!this->test_on_add ||
         this->tester->test_signer(this->tester, algo, create,
                                   this->bench ? &speed : NULL, plugin_name))
     {
         add_entry(this, this->signers, algo, plugin_name, speed, create);
         return TRUE;
     }
     this->test_failures++;
     return FALSE;
 }
METHOD (crypto_factory_t , remove_signer , void , private_crypto_factory_t * this, signer_constructor_t create)
Definition at line 538 of file crypto_factory.c.
References entry_t::create_signer, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->signers->create_enumerator(this->signers);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_signer == create)
         {
             this->signers->remove_at(this->signers, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , add_hasher , bool , private_crypto_factory_t * this, hash_algorithm_t algo, const char * plugin_name, hasher_constructor_t create)
Definition at line 558 of file crypto_factory.c.
References add_entry(), FALSE, and TRUE.
 {
     u_int speed = 0;
     if (!this->test_on_add ||
         this->tester->test_hasher(this->tester, algo, create,
                                   this->bench ? &speed : NULL, plugin_name))
     {
         add_entry(this, this->hashers, algo, plugin_name, speed, create);
         return TRUE;
     }
     this->test_failures++;
     return FALSE;
 }
METHOD (crypto_factory_t , remove_hasher , void , private_crypto_factory_t * this, hasher_constructor_t create)
Definition at line 575 of file crypto_factory.c.
References entry_t::create_hasher, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->hashers->create_enumerator(this->hashers);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_hasher == create)
         {
             this->hashers->remove_at(this->hashers, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , add_prf , bool , private_crypto_factory_t * this, pseudo_random_function_t algo, const char * plugin_name, prf_constructor_t create)
Definition at line 595 of file crypto_factory.c.
References add_entry(), FALSE, prfs, and TRUE.
 {
     u_int speed = 0;
     if (!this->test_on_add ||
         this->tester->test_prf(this->tester, algo, create,
                                this->bench ? &speed : NULL, plugin_name))
     {
         add_entry(this, this->prfs, algo, plugin_name, speed, create);
         return TRUE;
     }
     this->test_failures++;
     return FALSE;
 }
METHOD (crypto_factory_t , remove_prf , void , private_crypto_factory_t * this, prf_constructor_t create)
Definition at line 612 of file crypto_factory.c.
References entry_t::create_prf, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, prfs, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->prfs->create_enumerator(this->prfs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_prf == create)
         {
             this->prfs->remove_at(this->prfs, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , add_rng , bool , private_crypto_factory_t * this, rng_quality_t quality, const char * plugin_name, rng_constructor_t create)
Definition at line 632 of file crypto_factory.c.
References add_entry(), FALSE, and TRUE.
 {
     u_int speed = 0;
     if (!this->test_on_add ||
         this->tester->test_rng(this->tester, quality, create,
                                this->bench ? &speed : NULL, plugin_name))
     {
         add_entry(this, this->rngs, quality, plugin_name, speed, create);
         return TRUE;
     }
     this->test_failures++;
     return FALSE;
 }
METHOD (crypto_factory_t , remove_rng , void , private_crypto_factory_t * this, rng_constructor_t create)
Definition at line 649 of file crypto_factory.c.
References entry_t::create_rng, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->rngs->create_enumerator(this->rngs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_rng == create)
         {
             this->rngs->remove_at(this->rngs, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , add_nonce_gen , bool , private_crypto_factory_t * this, const char * plugin_name, nonce_gen_constructor_t create)
Definition at line 669 of file crypto_factory.c.
References add_entry(), and TRUE.
 {
     add_entry(this, this->nonce_gens, 0, plugin_name, 0, create);
     return TRUE;
 }
METHOD (crypto_factory_t , remove_nonce_gen , void , private_crypto_factory_t * this, nonce_gen_constructor_t create)
Definition at line 677 of file crypto_factory.c.
References entry_t::create_nonce_gen, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->nonce_gens->create_enumerator(this->nonce_gens);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_nonce_gen == create)
         {
             this->nonce_gens->remove_at(this->nonce_gens, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , add_dh , bool , private_crypto_factory_t * this, diffie_hellman_group_t group, const char * plugin_name, dh_constructor_t create)
Definition at line 697 of file crypto_factory.c.
References add_entry(), FALSE, and TRUE.
 {
     u_int speed = 0;
     if (!this->test_on_add ||
         this->tester->test_dh(this->tester, group, create,
                               this->bench ? &speed : NULL, plugin_name))
     {
         add_entry(this, this->dhs, group, plugin_name, 0, create);
         return TRUE;
     }
     this->test_failures++;
     return FALSE;
 }
METHOD (crypto_factory_t , remove_dh , void , private_crypto_factory_t * this, dh_constructor_t create)
Definition at line 714 of file crypto_factory.c.
References entry_t::create_dh, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->dhs->create_enumerator(this->dhs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create_dh == create)
         {
             this->dhs->remove_at(this->dhs, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (crypto_factory_t , create_crypter_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 781 of file crypto_factory.c.
References create_enumerator(), and crypter_filter().
 {
     return create_enumerator(this, this->crypters, crypter_filter);
 }
METHOD (crypto_factory_t , create_aead_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 787 of file crypto_factory.c.
References create_enumerator(), and crypter_filter().
 {
     return create_enumerator(this, this->aeads, crypter_filter);
 }
METHOD (crypto_factory_t , create_signer_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 804 of file crypto_factory.c.
References create_enumerator(), and signer_filter().
 {
     return create_enumerator(this, this->signers, signer_filter);
 }
METHOD (crypto_factory_t , create_hasher_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 821 of file crypto_factory.c.
References create_enumerator(), and hasher_filter().
 {
     return create_enumerator(this, this->hashers, hasher_filter);
 }
METHOD (crypto_factory_t , create_prf_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 838 of file crypto_factory.c.
References create_enumerator(), prf_filter(), and prfs.
 {
     return create_enumerator(this, this->prfs, prf_filter);
 }
METHOD (crypto_factory_t , create_dh_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 855 of file crypto_factory.c.
References create_enumerator(), and dh_filter().
 {
     return create_enumerator(this, this->dhs, dh_filter);
 }
METHOD (crypto_factory_t , create_rng_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 872 of file crypto_factory.c.
References create_enumerator(), and rng_filter().
 {
     return create_enumerator(this, this->rngs, rng_filter);
 }
METHOD (crypto_factory_t , create_nonce_gen_enumerator , enumerator_t * , private_crypto_factory_t * this)
Definition at line 887 of file crypto_factory.c.
References create_enumerator(), and nonce_gen_filter().
 {
     return create_enumerator(this, this->nonce_gens, nonce_gen_filter);
 }
METHOD (crypto_factory_t , add_test_vector , void , private_crypto_factory_t * this, transform_type_t type, void * vector)
Definition at line 893 of file crypto_factory.c.
References AEAD_ALGORITHM, DBG1, DBG_LIB, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, HASH_ALGORITHM, INTEGRITY_ALGORITHM, PSEUDO_RANDOM_FUNCTION, RANDOM_NUMBER_GENERATOR, and transform_type_names.
 {
     switch (type)
     {
         case ENCRYPTION_ALGORITHM:
             return this->tester->add_crypter_vector(this->tester, vector);
         case AEAD_ALGORITHM:
             return this->tester->add_aead_vector(this->tester, vector);
         case INTEGRITY_ALGORITHM:
             return this->tester->add_signer_vector(this->tester, vector);
         case HASH_ALGORITHM:
             return this->tester->add_hasher_vector(this->tester, vector);
         case PSEUDO_RANDOM_FUNCTION:
             return this->tester->add_prf_vector(this->tester, vector);
         case RANDOM_NUMBER_GENERATOR:
             return this->tester->add_rng_vector(this->tester, vector);
         case DIFFIE_HELLMAN_GROUP:
             return this->tester->add_dh_vector(this->tester, vector);
         default:
             DBG1(DBG_LIB, "%N test vectors not supported, ignored",
                  transform_type_names, type);
     }
 }
METHOD (enumerator_t , verify_enumerate , bool , verify_enumerator_t * this, u_int * alg, const char ** plugin, bool * valid)
Definition at line 929 of file crypto_factory.c.
References AEAD_ALGORITHM, entry_t::algo, entry_t::create_aead, entry_t::create_crypter, entry_t::create_dh, entry_t::create_hasher, entry_t::create_prf, entry_t::create_rng, entry_t::create_signer, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, FALSE, HASH_ALGORITHM, INTEGRITY_ALGORITHM, entry_t::plugin_name, PSEUDO_RANDOM_FUNCTION, RANDOM_NUMBER_GENERATOR, TRUE, and type.
 {
     entry_t *entry;
     if (!this->inner->enumerate(this->inner, &entry))
     {
         return FALSE;
     }
     switch (this->type)
     {
         case ENCRYPTION_ALGORITHM:
             *valid = this->tester->test_crypter(this->tester, entry->algo, 0,
                             entry->create_crypter, NULL, entry->plugin_name);
             break;
         case AEAD_ALGORITHM:
             *valid = this->tester->test_aead(this->tester, entry->algo, 0, 0,
                             entry->create_aead, NULL, entry->plugin_name);
             break;
         case INTEGRITY_ALGORITHM:
             *valid = this->tester->test_signer(this->tester, entry->algo,
                             entry->create_signer, NULL, entry->plugin_name);
             break;
         case HASH_ALGORITHM:
             *valid = this->tester->test_hasher(this->tester, entry->algo,
                             entry->create_hasher, NULL, entry->plugin_name);
             break;
         case PSEUDO_RANDOM_FUNCTION:
             *valid = this->tester->test_prf(this->tester, entry->algo,
                             entry->create_prf, NULL, entry->plugin_name);
             break;
         case RANDOM_NUMBER_GENERATOR:
             *valid = this->tester->test_rng(this->tester, entry->algo,
                             entry->create_rng, NULL, entry->plugin_name);
             break;
         case DIFFIE_HELLMAN_GROUP:
             *valid = this->tester->test_dh(this->tester, entry->algo,
                             entry->create_dh, NULL, entry->plugin_name);
             break;
         default:
             return FALSE;
     }
     *plugin = entry->plugin_name;
     *alg = entry->algo;
     return TRUE;
 }
METHOD (enumerator_t , verify_destroy , void , verify_enumerator_t * this)
Definition at line 976 of file crypto_factory.c.
References free(), lock, and spinlock_t::unlock.
 {
     this->inner->destroy(this->inner);
     this->lock->unlock(this->lock);
     free(this);
 }
METHOD (crypto_factory_t , create_verify_enumerator , enumerator_t * , private_crypto_factory_t * this, transform_type_t type)
Definition at line 984 of file crypto_factory.c.
References AEAD_ALGORITHM, destroy(), DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, enumerator_create_empty(), HASH_ALGORITHM, INIT, INTEGRITY_ALGORITHM, lock, prfs, PSEUDO_RANDOM_FUNCTION, verify_enumerator_t::public, RANDOM_NUMBER_GENERATOR, and spinlock_t::unlock.
 {
     verify_enumerator_t *enumerator;
     enumerator_t *inner;
     this->lock->read_lock(this->lock);
     switch (type)
     {
         case ENCRYPTION_ALGORITHM:
             inner = this->crypters->create_enumerator(this->crypters);
             break;
         case AEAD_ALGORITHM:
             inner = this->aeads->create_enumerator(this->aeads);
             break;
         case INTEGRITY_ALGORITHM:
             inner = this->signers->create_enumerator(this->signers);
             break;
         case HASH_ALGORITHM:
             inner = this->hashers->create_enumerator(this->hashers);
             break;
         case PSEUDO_RANDOM_FUNCTION:
             inner = this->prfs->create_enumerator(this->prfs);
             break;
         case RANDOM_NUMBER_GENERATOR:
             inner = this->rngs->create_enumerator(this->rngs);
             break;
         case DIFFIE_HELLMAN_GROUP:
             inner = this->dhs->create_enumerator(this->dhs);
             break;
         default:
             this->lock->unlock(this->lock);
             return enumerator_create_empty();
     }
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_verify_enumerate,
             .destroy = _verify_destroy,
         },
         .inner = inner,
         .type = type,
         .tester = this->tester,
         .lock = this->lock,
     );
     return &enumerator->public;
 }
METHOD (crypto_factory_t , destroy , void , private_crypto_factory_t * this)
Definition at line 1031 of file crypto_factory.c.
References spinlock_t::destroy, free(), lock, and prfs.
 {
     this->crypters->destroy(this->crypters);
     this->aeads->destroy(this->aeads);
     this->signers->destroy(this->signers);
     this->hashers->destroy(this->hashers);
     this->prfs->destroy(this->prfs);
     this->rngs->destroy(this->rngs);
     this->nonce_gens->destroy(this->nonce_gens);
     this->dhs->destroy(this->dhs);
     this->tester->destroy(this->tester);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool nonce_gen_filter (void * n, entry_t ** entry, const char ** plugin_name) static
Filter function to enumerate plugin name, not entry
Definition at line 881 of file crypto_factory.c.
References TRUE.
Referenced by METHOD().
 {
     *plugin_name = (*entry)->plugin_name;
     return TRUE;
 }
static bool prf_filter (void * n, entry_t ** entry, pseudo_random_function_t * algo, void * i2, const char ** plugin_name) static
Filter function to enumerate algorithm, not entry
Definition at line 830 of file crypto_factory.c.
References TRUE.
Referenced by METHOD().
 {
     *algo = (*entry)->algo;
     *plugin_name = (*entry)->plugin_name;
     return TRUE;
 }
static bool rng_filter (void * n, entry_t ** entry, rng_quality_t * quality, void * i2, const char ** plugin_name) static
Filter function to enumerate strength, not entry
Definition at line 864 of file crypto_factory.c.
References TRUE.
Referenced by METHOD().
 {
     *quality = (*entry)->algo;
     *plugin_name = (*entry)->plugin_name;
     return TRUE;
 }
static bool signer_filter (void * n, entry_t ** entry, integrity_algorithm_t * algo, void * i2, const char ** plugin_name) static
Filter function to enumerate algorithm, not entry
Definition at line 796 of file crypto_factory.c.
References TRUE.
Referenced by METHOD().
 {
     *algo = (*entry)->algo;
     *plugin_name = (*entry)->plugin_name;
     return TRUE;
 }
static bool unique_check (linked_list_t * list, entry_t ** in, entry_t ** out) static
check for uniqueness of an entry
Definition at line 745 of file crypto_factory.c.
References entry_match(), FALSE, linked_list_t::find_first, in, linked_list_t::insert_last, SUCCESS, and TRUE.
Referenced by create_enumerator().
 {
     if (list->find_first(list, (void*)entry_match, NULL, *in) == SUCCESS)
     {
         return FALSE;
     }
     *out = *in;
     list->insert_last(list, *in);
     return TRUE;
 }
Variable Documentation
const char* default_plugin_name = "default"
Definition at line 25 of file crypto_factory.c.
Referenced by METHOD().