strongSwan: gcrypt_dh
gcrypt_dh
gcrypt
Classes
struct gcrypt_dh_t
Typedefs
typedef struct gcrypt_dh_t gcrypt_dh_t
Functions
gcrypt_dh_t * gcrypt_dh_create (diffie_hellman_group_t group)
gcrypt_dh_t * gcrypt_dh_create_custom (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Detailed Description
Typedef Documentation
typedef struct gcrypt_dh_t gcrypt_dh_t
Definition at line 24 of file gcrypt_dh.h.
Function Documentation
gcrypt_dh_t* gcrypt_dh_create (diffie_hellman_group_t group)
Creates a new gcrypt_dh_t object.
Parameters
group Diffie Hellman group number to use
Returns
gcrypt_dh_t object, NULL if not supported
Definition at line 275 of file gcrypt_dh.c.
References create_generic(), diffie_hellman_get_params(), diffie_hellman_params_t::exp_len, diffie_hellman_params_t::generator, params, and diffie_hellman_params_t::prime.
Referenced by METHOD().
 {
     diffie_hellman_params_t *params;
     params = diffie_hellman_get_params(group);
     if (!params)
     {
         return NULL;
     }
     return create_generic(group, params->exp_len,
                           params->generator, params->prime);
 }
gcrypt_dh_t* gcrypt_dh_create_custom (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Creates a new gcrypt_dh_t object for MODP_CUSTOM.
Parameters
group MODP_CUSTOM
g generator
p prime
Returns
gcrypt_dh_t object, NULL if not supported
Definition at line 292 of file gcrypt_dh.c.
References create_generic(), chunk_t::len, and MODP_CUSTOM.
Referenced by METHOD().
 {
     if (group == MODP_CUSTOM)
     {
         return create_generic(group, p.len, g, p);
     }
     return NULL;
 }