strongSwan: tkm_encoder.c File Reference
tkm_encoder.c File Reference
#include <utils/debug.h>
#include <asn1/asn1.h>
#include <asn1/oid.h>
#include "tkm_encoder.h"
Functions
static bool hash_pubkey (chunk_t pubkey, chunk_t *hash)
static bool build_pub_info (chunk_t *encoding, va_list args)
static bool build_info_sha1 (chunk_t *encoding, va_list args)
static bool build_sha1 (chunk_t *encoding, va_list args)
bool tkm_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Function Documentation
static bool build_info_sha1 (chunk_t * encoding, va_list args) static
Build the fingerprint of the subjectPublicKeyInfo object.
Definition at line 65 of file tkm_encoder.c.
References build_pub_info(), FALSE, and hash_pubkey().
Referenced by tkm_encoder_encode().
 {
     chunk_t pubkey;
     if (build_pub_info(&pubkey, args))
     {
         return hash_pubkey(pubkey, encoding);
     }
     return FALSE;
 }
static bool build_pub_info (chunk_t * encoding, va_list args) static
Encode the public key blob into subjectPublicKeyInfo.
Definition at line 47 of file tkm_encoder.c.
References asn1_algorithmIdentifier(), asn1_bitstring(), ASN1_SEQUENCE, asn1_wrap(), blob, cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_PUB_ASN1_DER, FALSE, OID_RSA_ENCRYPTION, and TRUE.
Referenced by build_info_sha1().
 {
     chunk_t blob;
     if (cred_encoding_args(args, CRED_PART_RSA_PUB_ASN1_DER, &blob,
                            CRED_PART_END))
     {
         *encoding = asn1_wrap(ASN1_SEQUENCE, "mm",
                               asn1_algorithmIdentifier(OID_RSA_ENCRYPTION),
                               asn1_bitstring("c", blob));
         return TRUE;
     }
     return FALSE;
 }
static bool build_sha1 (chunk_t * encoding, va_list args) static
Build the fingerprint of the subjectPublicKey object.
Definition at line 79 of file tkm_encoder.c.
References blob, chunk_clone, cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_PUB_ASN1_DER, FALSE, and hash_pubkey().
Referenced by tkm_encoder_encode().
 {
     chunk_t blob;
     if (cred_encoding_args(args, CRED_PART_RSA_PUB_ASN1_DER, &blob,
                            CRED_PART_END))
     {
         return hash_pubkey(chunk_clone(blob), encoding);
     }
     return FALSE;
 }
static bool hash_pubkey (chunk_t pubkey, chunk_t * hash) static
Build the SHA1 hash of pubkey(info) ASN.1 data.
Definition at line 26 of file tkm_encoder.c.
References hasher_t::allocate_hash, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, HASH_SHA1, hasher, lib, and TRUE.
Referenced by build_info_sha1(), and build_sha1().
 {
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher || !hasher->allocate_hash(hasher, pubkey, hash))
     {
         DBG1(DBG_LIB, "SHA1 hash algorithm not supported, "
              "fingerprinting failed");
         DESTROY_IF(hasher);
         chunk_free(&pubkey);
         return FALSE;
     }
     hasher->destroy(hasher);
     chunk_free(&pubkey);
     return TRUE;
 }