strongSwan: ipsec_sa_mgr
ipsec_sa_mgr
libipsec
Classes
struct ipsec_sa_mgr_t
Typedefs
typedef struct ipsec_sa_mgr_t ipsec_sa_mgr_t
Functions
ipsec_sa_mgr_t * ipsec_sa_mgr_create ()
Detailed Description
Typedef Documentation
typedef struct ipsec_sa_mgr_t ipsec_sa_mgr_t
Definition at line 33 of file ipsec_sa_mgr.h.
Function Documentation
ipsec_sa_mgr_t* ipsec_sa_mgr_create ()
Create an ipsec_sa_mgr instance
Returns
IPsec SA manager instance
Described in header.
Definition at line 665 of file ipsec_sa_mgr.c.
References hashtable_create(), INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, spi_equals(), and spi_hash().
Referenced by libipsec_init().
 {
     private_ipsec_sa_mgr_t *this;
     INIT(this,
         .public = {
             .get_spi = _get_spi,
             .add_sa = _add_sa,
             .update_sa = _update_sa,
             .query_sa = _query_sa,
             .del_sa = _del_sa,
             .checkout_by_spi = _checkout_by_spi,
             .checkout_by_reqid = _checkout_by_reqid,
             .checkin = _checkin,
             .flush_sas = _flush_sas,
             .destroy = _destroy,
         },
         .sas = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .allocated_spis = hashtable_create((hashtable_hash_t)spi_hash,
                                            (hashtable_equals_t)spi_equals, 16),
     );
     return &this->public;
 }