strongSwan: padlock_sha1_hasher.c File Reference
padlock_sha1_hasher.c File Reference
#include <string.h>
#include <arpa/inet.h>
#include <byteswap.h>
#include "padlock_sha1_hasher.h"
Classes
struct private_padlock_sha1_hasher_t
Macros
#define PADLOCK_ALIGN __attribute__ ((__aligned__(16)))
Typedefs
typedef struct
private_padlock_sha1_hasher_t private_padlock_sha1_hasher_t
Functions
static void padlock_sha1 (int len, u_char *in, u_char *out)
static void sha1 (chunk_t data, u_int32_t *digest)
static void append_data (private_padlock_sha1_hasher_t *this, chunk_t data)
METHOD (hasher_t, reset, bool, private_padlock_sha1_hasher_t *this)
METHOD (hasher_t, get_hash, bool, private_padlock_sha1_hasher_t *this, chunk_t chunk, u_int8_t *hash)
METHOD (hasher_t, allocate_hash, bool, private_padlock_sha1_hasher_t *this, chunk_t chunk, chunk_t *hash)
METHOD (hasher_t, get_hash_size, size_t, private_padlock_sha1_hasher_t *this)
METHOD (hasher_t, destroy, void, private_padlock_sha1_hasher_t *this)
padlock_sha1_hasher_t * padlock_sha1_hasher_create (hash_algorithm_t algo)
Macro Definition Documentation
#define PADLOCK_ALIGN __attribute__ ((__aligned__(16)))
Definition at line 23 of file padlock_sha1_hasher.c.
Referenced by sha1().
Typedef Documentation
typedef struct private_padlock_sha1_hasher_t private_padlock_sha1_hasher_t
Definition at line 25 of file padlock_sha1_hasher.c.
Function Documentation
static void append_data (private_padlock_sha1_hasher_t * this, chunk_t data) static
append data to the to-be-hashed buffer
Definition at line 79 of file padlock_sha1_hasher.c.
References chunk_t::len, memcpy, and chunk_t::ptr.
Referenced by METHOD().
 {
     this->data.ptr = realloc(this->data.ptr, this->data.len + data.len);
     memcpy(this->data.ptr + this->data.len, data.ptr, data.len);
     this->data.len += data.len;
 }
METHOD (hasher_t , reset , bool , private_padlock_sha1_hasher_t * this)
Definition at line 86 of file padlock_sha1_hasher.c.
References chunk_free(), data, and TRUE.
 {
     chunk_free(&this->data);
     return TRUE;
 }
METHOD (hasher_t , get_hash , bool , private_padlock_sha1_hasher_t * this, chunk_t chunk, u_int8_t * hash)
Definition at line 93 of file padlock_sha1_hasher.c.
References append_data(), data, sha1(), and TRUE.
 {
     if (hash)
     {
         if (this->data.len)
         {
             append_data(this, chunk);
             sha1(this->data, (u_int32_t*)hash);
         }
         else
         {   /* hash directly if no previous data found */
             sha1(chunk, (u_int32_t*)hash);
         }
         reset(this);
     }
     else
     {
         append_data(this, chunk);
     }
     return TRUE;
 }
METHOD (hasher_t , allocate_hash , bool , private_padlock_sha1_hasher_t * this, chunk_t chunk, chunk_t * hash)
Definition at line 116 of file padlock_sha1_hasher.c.
References chunk_alloc, HASH_SIZE_SHA1, and chunk_t::ptr.
 {
     if (hash)
     {
         *hash = chunk_alloc(HASH_SIZE_SHA1);
         return get_hash(this, chunk, hash->ptr);
     }
     return get_hash(this, chunk, NULL);
 }
METHOD (hasher_t , get_hash_size , size_t , private_padlock_sha1_hasher_t * this)
Definition at line 127 of file padlock_sha1_hasher.c.
References HASH_SIZE_SHA1.
 {
     return HASH_SIZE_SHA1;
 }
METHOD (hasher_t , destroy , void , private_padlock_sha1_hasher_t * this)
Definition at line 133 of file padlock_sha1_hasher.c.
References data, and free().
 {
     free(this->data.ptr);
     free(this);
 }
static void padlock_sha1 (int len, u_char * in, u_char * out) static
Invoke the actual padlock sha1() operation
Definition at line 45 of file padlock_sha1_hasher.c.
References in, and len.
Referenced by sha1().
 {
     /* rep xsha1 */
     asm volatile (
         ".byte 0xf3, 0x0f, 0xa6, 0xc8"
         : "+S"(in), "+D"(out)
         : "c"(len), "a"(0));
 }
static void sha1 (chunk_t data, u_int32_t * digest) static
sha1() a buffer of data into digest
Definition at line 57 of file padlock_sha1_hasher.c.
References hash, chunk_t::len, PADLOCK_ALIGN, padlock_sha1(), and chunk_t::ptr.
Referenced by hash_data(), METHOD(), and tls_prf_create_10().
 {
     u_int32_t hash[128] PADLOCK_ALIGN;
     hash[0] = 0x67452301;
     hash[1] = 0xefcdab89;
     hash[2] = 0x98badcfe;
     hash[3] = 0x10325476;
     hash[4] = 0xc3d2e1f0;
     padlock_sha1(data.len, data.ptr, (u_char*)hash);
     digest[0] = bswap_32(hash[0]);
     digest[1] = bswap_32(hash[1]);
     digest[2] = bswap_32(hash[2]);
     digest[3] = bswap_32(hash[3]);
     digest[4] = bswap_32(hash[4]);
 }