strongSwan: kernel_netlink_net.c File Reference
kernel_netlink_net.c File Reference
#include <sys/socket.h>
#include <sys/utsname.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <unistd.h>
#include <errno.h>
#include <net/if.h>
#include "kernel_netlink_net.h"
#include "kernel_netlink_shared.h"
#include <hydra.h>
#include <utils/debug.h>
#include <threading/mutex.h>
#include <threading/rwlock.h>
#include <threading/rwlock_condvar.h>
#include <threading/spinlock.h>
#include <collections/hashtable.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
Classes
struct addr_entry_t
struct iface_entry_t
struct addr_map_entry_t
struct route_entry_t
struct net_change_t
struct private_kernel_netlink_net_t
struct address_enumerator_t
struct rt_entry_t
Macros
#define ROAM_DELAY 100
#define ROUTE_DELAY 100
#define MAX_ROUTE_RECURSION 2
#define ROUTING_TABLE 0
#define ROUTING_TABLE_PRIO 0
Typedefs
typedef struct addr_entry_t addr_entry_t
typedef struct iface_entry_t iface_entry_t
typedef struct addr_map_entry_t addr_map_entry_t
typedef struct route_entry_t route_entry_t
typedef struct net_change_t net_change_t
typedef struct
private_kernel_netlink_net_t private_kernel_netlink_net_t
Functions
ENUM (rt_msg_names, RTM_NEWLINK, RTM_GETRULE,"RTM_NEWLINK","RTM_DELLINK","RTM_GETLINK","RTM_SETLINK","RTM_NEWADDR","RTM_DELADDR","RTM_GETADDR","31","RTM_NEWROUTE","RTM_DELROUTE","RTM_GETROUTE","35","RTM_NEWNEIGH","RTM_DELNEIGH","RTM_GETNEIGH","RTM_NEWRULE","RTM_DELRULE","RTM_GETRULE",)
static void addr_entry_destroy (addr_entry_t *this)
static void iface_entry_destroy (iface_entry_t *this)
static bool iface_entry_by_index (iface_entry_t *this, int *ifindex)
static bool iface_entry_by_name (iface_entry_t *this, char *ifname)
static bool iface_entry_up (iface_entry_t *iface)
static bool iface_entry_up_and_usable (iface_entry_t *iface)
static u_int addr_map_entry_hash (addr_map_entry_t *this)
static bool addr_map_entry_equals (addr_map_entry_t *a, addr_map_entry_t *b)
static bool addr_map_entry_match_up_and_usable (addr_map_entry_t *a, addr_map_entry_t *b)
static bool addr_map_entry_match_up (addr_map_entry_t *a, addr_map_entry_t *b)
static bool addr_map_entry_match (addr_map_entry_t *a, addr_map_entry_t *b)
static route_entry_t * route_entry_clone (route_entry_t *this)
static void route_entry_destroy (route_entry_t *this)
static u_int route_entry_hash (route_entry_t *this)
static bool route_entry_equals (route_entry_t *a, route_entry_t *b)
static void net_change_destroy (net_change_t *this)
static u_int net_change_hash (net_change_t *this)
static bool net_change_equals (net_change_t *a, net_change_t *b)
static status_t manage_srcroute (private_kernel_netlink_net_t *this, int nlmsg_type, int flags, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
static void net_changes_clear (private_kernel_netlink_net_t *this)
static job_requeue_t reinstall_routes (private_kernel_netlink_net_t *this)
static void queue_route_reinstall (private_kernel_netlink_net_t *this, char *if_name)
static bool is_vip_installed_or_gone (private_kernel_netlink_net_t *this, host_t *ip, addr_map_entry_t **entry)
static bool is_known_vip (private_kernel_netlink_net_t *this, host_t *ip)
static void addr_map_entry_add (hashtable_t *map, addr_entry_t *addr, iface_entry_t *iface)
static void addr_map_entry_remove (hashtable_t *map, addr_entry_t *addr, iface_entry_t *iface)
static u_char get_scope (host_t *ip)
static u_char common_prefix (host_t *a, host_t *b)
static bool is_address_better (private_kernel_netlink_net_t *this, addr_entry_t *a, addr_entry_t *b, host_t *d)
static host_t * get_interface_address (private_kernel_netlink_net_t *this, int ifindex, int family, host_t *dest, host_t *candidate)
static job_requeue_t roam_event (private_kernel_netlink_net_t *this)
static void fire_roam_event (private_kernel_netlink_net_t *this, bool address)
static bool is_interface_up_and_usable (private_kernel_netlink_net_t *this, int index)
static void addr_entry_unregister (addr_entry_t *addr, iface_entry_t *iface, private_kernel_netlink_net_t *this)
static void process_link (private_kernel_netlink_net_t *this, struct nlmsghdr *hdr, bool event)
static void process_addr (private_kernel_netlink_net_t *this, struct nlmsghdr *hdr, bool event)
static void process_route (private_kernel_netlink_net_t *this, struct nlmsghdr *hdr)
static bool receive_events (private_kernel_netlink_net_t *this, int fd, watcher_event_t event)
static void address_enumerator_destroy (address_enumerator_t *data)
static bool filter_addresses (address_enumerator_t *data, addr_entry_t **in, host_t **out)
static enumerator_t * create_iface_enumerator (iface_entry_t *iface, address_enumerator_t *data)
static bool filter_interfaces (address_enumerator_t *data, iface_entry_t **in, iface_entry_t **out)
METHOD (kernel_net_t, create_address_enumerator, enumerator_t *, private_kernel_netlink_net_t *this, kernel_address_type_t which)
METHOD (kernel_net_t, get_interface_name, bool, private_kernel_netlink_net_t *this, host_t *ip, char **name)
static int get_interface_index (private_kernel_netlink_net_t *this, char *name)
static bool addr_in_subnet (chunk_t addr, int prefix, chunk_t net, int net_len)
static void rt_entry_destroy (rt_entry_t *this)
static bool route_usable (struct nlmsghdr *hdr)
static rt_entry_t * parse_route (struct nlmsghdr *hdr, rt_entry_t *route)
static host_t * get_route (private_kernel_netlink_net_t *this, host_t *dest, int prefix, bool nexthop, host_t *candidate, u_int recursion)
METHOD (kernel_net_t, get_source_addr, host_t *, private_kernel_netlink_net_t *this, host_t *dest, host_t *src)
METHOD (kernel_net_t, get_nexthop, host_t *, private_kernel_netlink_net_t *this, host_t *dest, int prefix, host_t *src)
static status_t manage_ipaddr (private_kernel_netlink_net_t *this, int nlmsg_type, int flags, int if_index, host_t *ip, int prefix)
METHOD (kernel_net_t, add_ip, status_t, private_kernel_netlink_net_t *this, host_t *virtual_ip, int prefix, char *iface_name)
METHOD (kernel_net_t, del_ip, status_t, private_kernel_netlink_net_t *this, host_t *virtual_ip, int prefix, bool wait)
METHOD (kernel_net_t, add_route, status_t, private_kernel_netlink_net_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
METHOD (kernel_net_t, del_route, status_t, private_kernel_netlink_net_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
static status_t init_address_list (private_kernel_netlink_net_t *this)
static status_t manage_rule (private_kernel_netlink_net_t *this, int nlmsg_type, int family, u_int32_t table, u_int32_t prio)
static void check_kernel_features (private_kernel_netlink_net_t *this)
static void addr_map_destroy (hashtable_t *map)
METHOD (kernel_net_t, destroy, void, private_kernel_netlink_net_t *this)
kernel_netlink_net_t * kernel_netlink_net_create ()
Macro Definition Documentation
#define MAX_ROUTE_RECURSION 2
maximum recursion when searching for addresses in get_route()
Definition at line 71 of file kernel_netlink_net.c.
Referenced by get_route().
#define ROAM_DELAY 100
delay before firing roam events (ms)
Definition at line 65 of file kernel_netlink_net.c.
Referenced by fire_roam_event().
#define ROUTE_DELAY 100
delay before reinstalling routes (ms)
Definition at line 68 of file kernel_netlink_net.c.
Referenced by queue_route_reinstall().
#define ROUTING_TABLE 0
Definition at line 74 of file kernel_netlink_net.c.
Referenced by kernel_netlink_net_create().
#define ROUTING_TABLE_PRIO 0
Definition at line 78 of file kernel_netlink_net.c.
Referenced by kernel_netlink_net_create().
Typedef Documentation
typedef struct addr_entry_t addr_entry_t
Definition at line 102 of file kernel_netlink_net.c.
typedef struct addr_map_entry_t addr_map_entry_t
Definition at line 198 of file kernel_netlink_net.c.
typedef struct iface_entry_t iface_entry_t
Definition at line 134 of file kernel_netlink_net.c.
typedef struct net_change_t net_change_t
Definition at line 337 of file kernel_netlink_net.c.
typedef struct private_kernel_netlink_net_t private_kernel_netlink_net_t
Definition at line 372 of file kernel_netlink_net.c.
typedef struct route_entry_t route_entry_t
Definition at line 262 of file kernel_netlink_net.c.
Function Documentation
static void addr_entry_destroy (addr_entry_t * this) static
destroy a addr_entry_t object
Definition at line 128 of file kernel_netlink_net.c.
References free(), and ip.
Referenced by iface_entry_destroy(), and process_addr().
 {
     this->ip->destroy(this->ip);
     free(this);
 }
static void addr_entry_unregister (addr_entry_t * addr, iface_entry_t * iface, private_kernel_netlink_net_t * this) static
unregister the current addr_entry_t from the hashtable it is stored in
this->lock must be locked when calling this function
Definition at line 954 of file kernel_netlink_net.c.
References addr_map_entry_remove(), condvar_t::broadcast, condvar, and addr_entry_t::refcount.
Referenced by process_link().
 {
     if (addr->refcount)
     {
         addr_map_entry_remove(this->vips, addr, iface);
         this->condvar->broadcast(this->condvar);
         return;
     }
     addr_map_entry_remove(this->addrs, addr, iface);
 }
static bool addr_in_subnet (chunk_t addr, int prefix, chunk_t net, int net_len) static
check if an address or net (addr with prefix net bits) is in subnet (net with net_len net bits)
Definition at line 1507 of file kernel_netlink_net.c.
References FALSE, chunk_t::len, mask, chunk_t::ptr, and TRUE.
Referenced by get_route().
 {
     static const u_char mask[] = { 0x00, 0x80, 0xc0, 0xe0, 0xf0, 0xf8, 0xfc, 0xfe };
     int byte = 0;
     if (net_len == 0)
     {   /* any address matches a /0 network */
         return TRUE;
     }
     if (addr.len != net.len || net_len > 8 * net.len || prefix < net_len)
     {
         return FALSE;
     }
     /* scan through all bytes in network order */
     while (net_len > 0)
     {
         if (net_len < 8)
         {
             return (mask[net_len] & addr.ptr[byte]) == (mask[net_len] & net.ptr[byte]);
         }
         else
         {
             if (addr.ptr[byte] != net.ptr[byte])
             {
                 return FALSE;
             }
             byte++;
             net_len -= 8;
         }
     }
     return TRUE;
 }
static void addr_map_destroy (hashtable_t * map) static
Destroy an address to iface map
Definition at line 2482 of file kernel_netlink_net.c.
References addr, hashtable_t::create_enumerator, enumerator_t::destroy, hashtable_t::destroy, enumerator_t::enumerate, and free().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     addr_map_entry_t *addr;
     enumerator = map->create_enumerator(map);
     while (enumerator->enumerate(enumerator, NULL, (void**)&addr))
     {
         free(addr);
     }
     enumerator->destroy(enumerator);
     map->destroy(map);
 }
static void addr_map_entry_add (hashtable_t * map, addr_entry_t * addr, iface_entry_t * iface) static
Add an address map entry
Definition at line 674 of file kernel_netlink_net.c.
References free(), INIT, ip, addr_entry_t::ip, and hashtable_t::put.
Referenced by METHOD(), and process_addr().
 {
     addr_map_entry_t *entry;
     INIT(entry,
         .ip = addr->ip,
         .addr = addr,
         .iface = iface,
     );
     entry = map->put(map, entry, entry);
     free(entry);
 }
static bool addr_map_entry_equals (addr_map_entry_t * a, addr_map_entry_t * b) static
Compare two addr_map_entry_t objects, two entries are equal if they are installed on the same interface
Definition at line 227 of file kernel_netlink_net.c.
References addr_map_entry_t::iface, iface_entry_t::ifindex, addr_map_entry_t::ip, and host_t::ip_equals.
Referenced by kernel_netlink_net_create().
 {
     return a->iface->ifindex == b->iface->ifindex &&
            a->ip->ip_equals(a->ip, b->ip);
 }
static u_int addr_map_entry_hash (addr_map_entry_t * this) static
Hash a addr_map_entry_t object, all entries with the same IP address are stored in the same bucket
Definition at line 218 of file kernel_netlink_net.c.
References chunk_hash(), and ip.
Referenced by kernel_netlink_net_create().
 {
     return chunk_hash(this->ip->get_address(this->ip));
 }
static bool addr_map_entry_match (addr_map_entry_t * a, addr_map_entry_t * b) static
Used with get_match this finds an address entry if it is installed on any local interface
Definition at line 257 of file kernel_netlink_net.c.
References addr_map_entry_t::ip, and host_t::ip_equals.
Referenced by is_known_vip(), is_vip_installed_or_gone(), and METHOD().
 {
     return a->ip->ip_equals(a->ip, b->ip);
 }
static bool addr_map_entry_match_up (addr_map_entry_t * a, addr_map_entry_t * b) static
Used with get_match this finds an address entry if it is installed on any active local interface
Definition at line 248 of file kernel_netlink_net.c.
References addr_map_entry_t::iface, iface_entry_up(), addr_map_entry_t::ip, and host_t::ip_equals.
Referenced by METHOD().
 {
     return iface_entry_up(b->iface) && a->ip->ip_equals(a->ip, b->ip);
 }
static bool addr_map_entry_match_up_and_usable (addr_map_entry_t * a, addr_map_entry_t * b) static
Used with get_match this finds an address entry if it is installed on an up and usable interface
Definition at line 237 of file kernel_netlink_net.c.
References addr_map_entry_t::iface, iface_entry_up_and_usable(), addr_map_entry_t::ip, and host_t::ip_equals.
Referenced by METHOD().
 {
     return iface_entry_up_and_usable(b->iface) &&
            a->ip->ip_equals(a->ip, b->ip);
 }
static void addr_map_entry_remove (hashtable_t * map, addr_entry_t * addr, iface_entry_t * iface) static
Remove an address map entry
Definition at line 691 of file kernel_netlink_net.c.
References addr, free(), addr_entry_t::ip, lookup, and hashtable_t::remove.
Referenced by addr_entry_unregister(), and process_addr().
 {
     addr_map_entry_t *entry, lookup = {
         .ip = addr->ip,
         .addr = addr,
         .iface = iface,
     };
     entry = map->remove(map, &lookup);
     free(entry);
 }
static void address_enumerator_destroy (address_enumerator_t * data) static
cleanup function for address enumerator
Definition at line 1349 of file kernel_netlink_net.c.
References free(), private_kernel_netlink_net_t::lock, address_enumerator_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static void check_kernel_features (private_kernel_netlink_net_t * this) static
check for kernel features (currently only via version number)
Definition at line 2447 of file kernel_netlink_net.c.
References a, b, c, DBG2, DBG_KNL, and TRUE.
Referenced by kernel_netlink_net_create().
 {
     struct utsname utsname;
     int a, b, c;
     if (uname(&utsname) == 0)
     {
         switch(sscanf(utsname.release, "%d.%d.%d", &a, &b, &c))
         {
             case 3:
                 if (a == 2)
                 {
                     if (b == 6 && c >= 36)
                     {
                         this->rta_mark = TRUE;
                     }
                     DBG2(DBG_KNL, "detected Linux %d.%d.%d, no support for "
                          "RTA_PREFSRC for IPv6 routes", a, b, c);
                     break;
                 }
                 /* fall-through */
             case 2:
                 /* only 3.x+ uses two part version numbers */
                 this->rta_prefsrc_for_ipv6 = TRUE;
                 this->rta_mark = TRUE;
                 break;
             default:
                 break;
         }
     }
 }
static u_char common_prefix (host_t * a, host_t * b) static
Returns the length of the common prefix in bits up to the length of a's prefix, defined by RFC 6724 as the portion of the address not including the interface ID, which is 64-bit for most unicast addresses (see RFC 4291).
Definition at line 754 of file kernel_netlink_net.c.
References bits, host_t::get_address, match(), and chunk_t::ptr.
Referenced by is_address_better().
 {
     chunk_t aa, ba;
     u_char byte, bits = 0, match;
     aa = a->get_address(a);
     ba = b->get_address(b);
     for (byte = 0; byte < 8; byte++)
     {
         if (aa.ptr[byte] != ba.ptr[byte])
         {
             match = aa.ptr[byte] ^ ba.ptr[byte];
             for (bits = 8; match; match >>= 1)
             {
                 bits--;
             }
             break;
         }
     }
     return byte * 8 + bits;
 }
static enumerator_t* create_iface_enumerator (iface_entry_t * iface, address_enumerator_t * data) static
enumerator constructor for interfaces
Definition at line 1380 of file kernel_netlink_net.c.
References iface_entry_t::addrs, linked_list_t::create_enumerator, enumerator_create_filter(), and filter_addresses().
Referenced by METHOD().
 {
     return enumerator_create_filter(
                 iface->addrs->create_enumerator(iface->addrs),
                 (void*)filter_addresses, data, NULL);
 }
ENUM (rt_msg_names , RTM_NEWLINK , RTM_GETRULE , "RTM_NEWLINK" , "RTM_DELLINK" , "RTM_GETLINK" , "RTM_SETLINK" , "RTM_NEWADDR" , "RTM_DELADDR" , "RTM_GETADDR" , "31" , "RTM_NEWROUTE" , "RTM_DELROUTE" , "RTM_GETROUTE" , "35" , "RTM_NEWNEIGH" , "RTM_DELNEIGH" , "RTM_GETNEIGH" , "RTM_NEWRULE" , "RTM_DELRULE" , "RTM_GETRULE")
static bool filter_addresses (address_enumerator_t * data, addr_entry_t ** in, host_t ** out) static
filter for addresses
Definition at line 1358 of file kernel_netlink_net.c.
References ADDR_TYPE_REGULAR, ADDR_TYPE_VIRTUAL, FALSE, RT_SCOPE_LINK, TRUE, and address_enumerator_t::which.
Referenced by create_iface_enumerator().
 {
     if (!(data->which & ADDR_TYPE_VIRTUAL) && (*in)->refcount)
     {   /* skip virtual interfaces added by us */
         return FALSE;
     }
     if (!(data->which & ADDR_TYPE_REGULAR) && !(*in)->refcount)
     {   /* address is regular, but not requested */
         return FALSE;
     }
     if ((*in)->scope >= RT_SCOPE_LINK)
     {   /* skip addresses with a unusable scope */
         return FALSE;
     }
     *out = (*in)->ip;
     return TRUE;
 }
static bool filter_interfaces (address_enumerator_t * data, iface_entry_t ** in, iface_entry_t ** out) static
filter for interfaces
Definition at line 1391 of file kernel_netlink_net.c.
References ADDR_TYPE_DOWN, ADDR_TYPE_IGNORED, ADDR_TYPE_LOOPBACK, FALSE, in, TRUE, and address_enumerator_t::which.
Referenced by METHOD().
 {
     if (!(data->which & ADDR_TYPE_IGNORED) && !(*in)->usable)
     {   /* skip interfaces excluded by config */
         return FALSE;
     }
     if (!(data->which & ADDR_TYPE_LOOPBACK) && ((*in)->flags & IFF_LOOPBACK))
     {   /* ignore loopback devices */
         return FALSE;
     }
     if (!(data->which & ADDR_TYPE_DOWN) && !((*in)->flags & IFF_UP))
     {   /* skip interfaces not up */
         return FALSE;
     }
     *out = *in;
     return TRUE;
 }
static void fire_roam_event (private_kernel_netlink_net_t * this, bool address) static
fire a roaming event. we delay it for a bit and fire only one event for multiple calls. otherwise we would create too many events.
Definition at line 904 of file kernel_netlink_net.c.
References callback_job_create(), lib, ROAM_DELAY, roam_event(), scheduler_t::schedule_job_ms, library_t::scheduler, time_monotonic(), and timeval_add_ms().
Referenced by process_addr(), process_link(), and process_route().
 {
     timeval_t now;
     job_t *job;
     if (!this->roam_events)
     {
         return;
     }
     time_monotonic(&now);
     this->roam_lock->lock(this->roam_lock);
     this->roam_address |= address;
     if (!timercmp(&now, &this->next_roam, >))
     {
         this->roam_lock->unlock(this->roam_lock);
         return;
     }
     timeval_add_ms(&now, ROAM_DELAY);
     this->next_roam = now;
     this->roam_lock->unlock(this->roam_lock);
     job = (job_t*)callback_job_create((callback_job_cb_t)roam_event,
                                       this, NULL, NULL);
     lib->scheduler->schedule_job_ms(lib->scheduler, job, ROAM_DELAY);
 }
static host_t* get_interface_address (private_kernel_netlink_net_t * this, int ifindex, int family, host_t * dest, host_t * candidate) static
Get a non-virtual IP address on the given interface.
If a candidate address is given, we first search for that address and if not found return the address as above. Returned host is a clone, has to be freed by caller.
this->lock must be held when calling this function.
Definition at line 848 of file kernel_netlink_net.c.
References addr, iface_entry_t::addrs, host_t::clone, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, family, host_t::get_family, iface_entry_by_index(), addr_entry_t::ip, host_t::ip_equals, is_address_better(), addr_entry_t::refcount, SUCCESS, and iface_entry_t::usable.
Referenced by get_route(), and process_route().
 {
     iface_entry_t *iface;
     enumerator_t *addrs;
     addr_entry_t *addr, *best = NULL;
     if (this->ifaces->find_first(this->ifaces, (void*)iface_entry_by_index,
                                  (void**)&iface, &ifindex) == SUCCESS)
     {
         if (iface->usable)
         {   /* only use interfaces not excluded by config */
             addrs = iface->addrs->create_enumerator(iface->addrs);
             while (addrs->enumerate(addrs, &addr))
             {
                 if (addr->refcount ||
                     addr->ip->get_family(addr->ip) != family)
                 {   /* ignore virtual IP addresses and ensure family matches */
                     continue;
                 }
                 if (candidate && candidate->ip_equals(candidate, addr->ip))
                 {   /* stop if we find the candidate */
                     best = addr;
                     break;
                 }
                 else if (!best || is_address_better(this, best, addr, dest))
                 {
                     best = addr;
                 }
             }
             addrs->destroy(addrs);
         }
     }
     return best ? best->ip->clone(best->ip) : NULL;
 }
static int get_interface_index (private_kernel_netlink_net_t * this, char * name) static
get the index of an interface by name
Definition at line 1481 of file kernel_netlink_net.c.
References DBG1, DBG2, DBG_KNL, iface_entry_by_name(), iface_entry_t::ifindex, lock, SUCCESS, and spinlock_t::unlock.
Referenced by manage_srcroute().
 {
     iface_entry_t *iface;
     int ifindex = 0;
     DBG2(DBG_KNL, "getting iface index for %s", name);
     this->lock->read_lock(this->lock);
     if (this->ifaces->find_first(this->ifaces, (void*)iface_entry_by_name,
                                 (void**)&iface, name) == SUCCESS)
     {
         ifindex = iface->ifindex;
     }
     this->lock->unlock(this->lock);
     if (ifindex == 0)
     {
         DBG1(DBG_KNL, "unable to get interface index for %s", name);
     }
     return ifindex;
 }
static host_t* get_route (private_kernel_netlink_net_t * this, host_t * dest, int prefix, bool nexthop, host_t * candidate, u_int recursion) static
Get a route: If "nexthop", the nexthop is returned. source addr otherwise.
Definition at line 1659 of file kernel_netlink_net.c.
References addr, addr_in_subnet(), chunk_from_thing, host_t::clone, linked_list_t::create_enumerator, DBG2, DBG_KNL, enumerator_t::destroy, host_t::destroy, linked_list_t::destroy_function, DESTROY_IF, rt_entry_t::dst, rt_entry_t::dst_len, enumerator_t::enumerate, FALSE, family, free(), host_t::get_address, host_t::get_family, linked_list_t::get_first, get_interface_address(), rt_entry_t::gtw, netlink_buf_t::hdr, host_create_from_chunk(), if(), linked_list_t::insert_before, host_t::ip_equals, is_interface_up_and_usable(), is_known_vip(), chunk_t::len, len, linked_list_create(), lock, MAX_ROUTE_RECURSION, memset, min, msg, netlink_add_attribute(), NLM_F_DUMP, NLM_F_REQUEST, NLMSG_DATA, NLMSG_DONE, nlmsghdr::nlmsg_flags, nlmsghdr::nlmsg_len, NLMSG_LENGTH, NLMSG_NEXT, NLMSG_OK, nlmsghdr::nlmsg_type, rt_entry_t::oif, out, parse_route(), rt_entry_t::priority, chunk_t::ptr, request(), route_usable(), rt_entry_destroy(), RTA_DST, RTA_MARK, RTA_PREFSRC, rtmsg::rtm_family, RTM_GETROUTE, RTM_NEWROUTE, socket, src, rt_entry_t::src, rt_entry_t::src_host, SUCCESS, rt_entry_t::table, and spinlock_t::unlock.
Referenced by METHOD().
 {
     netlink_buf_t request;
     struct nlmsghdr *hdr, *out, *current;
     struct rtmsg *msg;
     chunk_t chunk;
     size_t len;
     linked_list_t *routes;
     rt_entry_t *route = NULL, *best = NULL;
     enumerator_t *enumerator;
     host_t *addr = NULL;
     bool match_net;
     int family;
     if (recursion > MAX_ROUTE_RECURSION)
     {
         return NULL;
     }
     chunk = dest->get_address(dest);
     len = chunk.len * 8;
     prefix = prefix < 0 ? len : min(prefix, len);
     match_net = prefix != len;
     memset(&request, 0, sizeof(request));
     family = dest->get_family(dest);
     hdr = &request.hdr;
     hdr->nlmsg_flags = NLM_F_REQUEST;
     hdr->nlmsg_type = RTM_GETROUTE;
     hdr->nlmsg_len = NLMSG_LENGTH(sizeof(struct rtmsg));
     msg = NLMSG_DATA(hdr);
     msg->rtm_family = family;
     if (!match_net && this->rta_mark && this->routing_mark.value)
     {
         /* if our routing rule excludes packets with a certain mark we can
          * get the preferred route without having to dump all routes */
         chunk = chunk_from_thing(this->routing_mark.value);
         netlink_add_attribute(hdr, RTA_MARK, chunk, sizeof(request));
     }
     else if (family == AF_INET || this->rta_prefsrc_for_ipv6 ||
              this->routing_table || match_net)
     {   /* kernels prior to 3.0 do not support RTA_PREFSRC for IPv6 routes.
          * as we want to ignore routes with virtual IPs we cannot use DUMP
          * if these routes are not installed in a separate table */
         hdr->nlmsg_flags |= NLM_F_DUMP;
     }
     if (candidate)
     {
         chunk = candidate->get_address(candidate);
         netlink_add_attribute(hdr, RTA_PREFSRC, chunk, sizeof(request));
     }
     if (!match_net)
     {
         chunk = dest->get_address(dest);
         netlink_add_attribute(hdr, RTA_DST, chunk, sizeof(request));
     }
     if (this->socket->send(this->socket, hdr, &out, &len) != SUCCESS)
     {
         DBG2(DBG_KNL, "getting %s to reach %H/%d failed",
              nexthop ? "nexthop" : "address", dest, prefix);
         return NULL;
     }
     routes = linked_list_create();
     this->lock->read_lock(this->lock);
     for (current = out; NLMSG_OK(current, len);
          current = NLMSG_NEXT(current, len))
     {
         switch (current->nlmsg_type)
         {
             case NLMSG_DONE:
                 break;
             case RTM_NEWROUTE:
             {
                 rt_entry_t *other;
                 uintptr_t table;
                 if (!route_usable(current))
                 {
                     continue;
                 }
                 route = parse_route(current, route);
                 table = (uintptr_t)route->table;
                 if (this->rt_exclude->find_first(this->rt_exclude, NULL,
                                                  (void**)&table) == SUCCESS)
                 {   /* route is from an excluded routing table */
                     continue;
                 }
                 if (this->routing_table != 0 &&
                     route->table == this->routing_table)
                 {   /* route is from our own ipsec routing table */
                     continue;
                 }
                 if (route->oif && !is_interface_up_and_usable(this, route->oif))
                 {   /* interface is down */
                     continue;
                 }
                 if (!addr_in_subnet(chunk, prefix, route->dst, route->dst_len))
                 {   /* route destination does not contain dest */
                     continue;
                 }
                 if (route->src.ptr)
                 {   /* verify source address, if any */
                     host_t *src = host_create_from_chunk(msg->rtm_family,
                                                          route->src, 0);
                     if (src && is_known_vip(this, src))
                     {   /* ignore routes installed by us */
                         src->destroy(src);
                         continue;
                     }
                     route->src_host = src;
                 }
                 /* insert route, sorted by priority and network prefix */
                 enumerator = routes->create_enumerator(routes);
                 while (enumerator->enumerate(enumerator, &other))
                 {
                     if (route->priority < other->priority)
                     {
                         break;
                     }
                     if (route->priority == other->priority &&
                         route->dst_len > other->dst_len)
                     {
                         break;
                     }
                 }
                 routes->insert_before(routes, enumerator, route);
                 enumerator->destroy(enumerator);
                 route = NULL;
                 continue;
             }
             default:
                 continue;
         }
         break;
     }
     if (route)
     {
         rt_entry_destroy(route);
     }
     /* now we have a list of routes matching dest, sorted by net prefix.
      * we will look for source addresses for these routes and select the one
      * with the preferred source address, if possible */
     enumerator = routes->create_enumerator(routes);
     while (enumerator->enumerate(enumerator, &route))
     {
         if (route->src_host)
         {   /* got a source address with the route, if no preferred source
              * is given or it matches we are done, as this is the best route */
             if (!candidate || candidate->ip_equals(candidate, route->src_host))
             {
                 best = route;
                 break;
             }
             else if (route->oif)
             {   /* no match yet, maybe it is assigned to the same interface */
                 host_t *src = get_interface_address(this, route->oif,
                                             msg->rtm_family, dest, candidate);
                 if (src && src->ip_equals(src, candidate))
                 {
                     route->src_host->destroy(route->src_host);
                     route->src_host = src;
                     best = route;
                     break;
                 }
                 DESTROY_IF(src);
             }
             /* no luck yet with the source address. if this is the best (first)
              * route we store it as fallback in case we don't find a route with
              * the preferred source */
             best = best ?: route;
             continue;
         }
         if (route->oif)
         {   /* no src, but an interface - get address from it */
             route->src_host = get_interface_address(this, route->oif,
                                             msg->rtm_family, dest, candidate);
             if (route->src_host)
             {   /* we handle this address the same as the one above */
                 if (!candidate ||
                      candidate->ip_equals(candidate, route->src_host))
                 {
                     best = route;
                     break;
                 }
                 best = best ?: route;
                 continue;
             }
         }
         if (route->gtw.ptr)
         {   /* no src, no iface, but a gateway - lookup src to reach gtw */
             host_t *gtw;
             gtw = host_create_from_chunk(msg->rtm_family, route->gtw, 0);
             if (gtw && !gtw->ip_equals(gtw, dest))
             {
                 route->src_host = get_route(this, gtw, -1, FALSE, candidate,
                                             recursion + 1);
             }
             DESTROY_IF(gtw);
             if (route->src_host)
             {   /* more of the same */
                 if (!candidate ||
                      candidate->ip_equals(candidate, route->src_host))
                 {
                     best = route;
                     break;
                 }
                 best = best ?: route;
             }
         }
     }
     enumerator->destroy(enumerator);
     if (nexthop)
     {   /* nexthop lookup, return gateway if any */
         if (best || routes->get_first(routes, (void**)&best) == SUCCESS)
         {
             addr = host_create_from_chunk(msg->rtm_family, best->gtw, 0);
         }
         if (!addr && !match_net)
         {   /* fallback to destination address */
             addr = dest->clone(dest);
         }
     }
     else
     {
         if (best)
         {
             addr = best->src_host->clone(best->src_host);
         }
     }
     this->lock->unlock(this->lock);
     routes->destroy_function(routes, (void*)rt_entry_destroy);
     free(out);
     if (addr)
     {
         DBG2(DBG_KNL, "using %H as %s to reach %H/%d", addr,
              nexthop ? "nexthop" : "address", dest, prefix);
     }
     else if (!recursion)
     {
         DBG2(DBG_KNL, "no %s found to reach %H/%d",
              nexthop ? "nexthop" : "address", dest, prefix);
     }
     return addr;
 }
static u_char get_scope (host_t * ip) static
Determine the type or scope of the given unicast IP address. This is not the same thing returned in rtm_scope/ifa_scope.
We use return values as defined in RFC 6724 (referring to RFC 4291).
Definition at line 710 of file kernel_netlink_net.c.
References addr, host_t::get_address, chunk_t::len, and chunk_t::ptr.
Referenced by is_address_better().
 {
     chunk_t addr;
     addr = ip->get_address(ip);
     switch (addr.len)
     {
         case 4:
             /* we use the mapping defined in RFC 6724, 3.2 */
             if (addr.ptr[0] == 127)
             {   /* link-local, same as the IPv6 loopback address */
                 return 2;
             }
             if (addr.ptr[0] == 169 && addr.ptr[1] == 254)
             {   /* link-local */
                 return 2;
             }
             break;
         case 16:
             if (IN6_IS_ADDR_LOOPBACK((struct in6_addr*)addr.ptr))
             {   /* link-local, according to RFC 4291, 2.5.3 */
                 return 2;
             }
             if (IN6_IS_ADDR_LINKLOCAL((struct in6_addr*)addr.ptr))
             {
                 return 2;
             }
             if (IN6_IS_ADDR_SITELOCAL((struct in6_addr*)addr.ptr))
             {   /* deprecated, according to RFC 4291, 2.5.7 */
                 return 5;
             }
             break;
         default:
             break;
     }
     /* global */
     return 14;
 }
static bool iface_entry_by_index (iface_entry_t * this, int * ifindex) static
find an interface entry by index
Definition at line 169 of file kernel_netlink_net.c.
Referenced by get_interface_address(), is_interface_up_and_usable(), process_addr(), and process_link().
 {
     return this->ifindex == *ifindex;
 }
static bool iface_entry_by_name (iface_entry_t * this, char * ifname) static
find an interface entry by name
Definition at line 177 of file kernel_netlink_net.c.
References streq().
Referenced by get_interface_index(), and METHOD().
 {
     return streq(this->ifname, ifname);
 }
static void iface_entry_destroy (iface_entry_t * this) static
destroy an interface entry
Definition at line 160 of file kernel_netlink_net.c.
References addr_entry_destroy(), and free().
Referenced by METHOD(), and process_link().
 {
     this->addrs->destroy_function(this->addrs, (void*)addr_entry_destroy);
     free(this);
 }
static bool iface_entry_up (iface_entry_t * iface) inline static
check if an interface is up
Definition at line 185 of file kernel_netlink_net.c.
References iface_entry_t::flags.
Referenced by addr_map_entry_match_up(), and iface_entry_up_and_usable().
 {
     return (iface->flags & IFF_UP) == IFF_UP;
 }
static bool iface_entry_up_and_usable (iface_entry_t * iface) inline static
check if an interface is up and usable
Definition at line 193 of file kernel_netlink_net.c.
References iface_entry_up(), and iface_entry_t::usable.
Referenced by addr_map_entry_match_up_and_usable(), init_address_list(), and is_interface_up_and_usable().
 {
     return iface->usable && iface_entry_up(iface);
 }
static status_t init_address_list (private_kernel_netlink_net_t * this) static
Initialize a list of local addresses.
Definition at line 2294 of file kernel_netlink_net.c.
References addr, iface_entry_t::addrs, linked_list_t::create_enumerator, DBG2, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, FAILED, FALSE, free(), netlink_buf_t::hdr, iface_entry_up_and_usable(), iface_entry_t::ifname, in, addr_entry_t::ip, len, lock, memset, msg, NLM_F_MATCH, NLM_F_REQUEST, NLM_F_ROOT, NLMSG_DATA, NLMSG_DONE, nlmsghdr::nlmsg_flags, nlmsghdr::nlmsg_len, NLMSG_LENGTH, NLMSG_NEXT, NLMSG_OK, nlmsghdr::nlmsg_type, out, process_addr(), process_link(), request(), rtgenmsg::rtgen_family, RTM_GETADDR, RTM_GETLINK, RTM_NEWADDR, RTM_NEWLINK, socket, SUCCESS, and spinlock_t::unlock.
Referenced by kernel_netlink_net_create().
 {
     netlink_buf_t request;
     struct nlmsghdr *out, *current, *in;
     struct rtgenmsg *msg;
     size_t len;
     enumerator_t *ifaces, *addrs;
     iface_entry_t *iface;
     addr_entry_t *addr;
     DBG2(DBG_KNL, "known interfaces and IP addresses:");
     memset(&request, 0, sizeof(request));
     in = &request.hdr;
     in->nlmsg_len = NLMSG_LENGTH(sizeof(struct rtgenmsg));
     in->nlmsg_flags = NLM_F_REQUEST | NLM_F_MATCH | NLM_F_ROOT;
     msg = NLMSG_DATA(in);
     msg->rtgen_family = AF_UNSPEC;
     /* get all links */
     in->nlmsg_type = RTM_GETLINK;
     if (this->socket->send(this->socket, in, &out, &len) != SUCCESS)
     {
         return FAILED;
     }
     current = out;
     while (NLMSG_OK(current, len))
     {
         switch (current->nlmsg_type)
         {
             case NLMSG_DONE:
                 break;
             case RTM_NEWLINK:
                 process_link(this, current, FALSE);
                 /* fall through */
             default:
                 current = NLMSG_NEXT(current, len);
                 continue;
         }
         break;
     }
     free(out);
     /* get all interface addresses */
     in->nlmsg_type = RTM_GETADDR;
     if (this->socket->send(this->socket, in, &out, &len) != SUCCESS)
     {
         return FAILED;
     }
     current = out;
     while (NLMSG_OK(current, len))
     {
         switch (current->nlmsg_type)
         {
             case NLMSG_DONE:
                 break;
             case RTM_NEWADDR:
                 process_addr(this, current, FALSE);
                 /* fall through */
             default:
                 current = NLMSG_NEXT(current, len);
                 continue;
         }
         break;
     }
     free(out);
     this->lock->read_lock(this->lock);
     ifaces = this->ifaces->create_enumerator(this->ifaces);
     while (ifaces->enumerate(ifaces, &iface))
     {
         if (iface_entry_up_and_usable(iface))
         {
             DBG2(DBG_KNL, "  %s", iface->ifname);
             addrs = iface->addrs->create_enumerator(iface->addrs);
             while (addrs->enumerate(addrs, (void**)&addr))
             {
                 DBG2(DBG_KNL, "    %H", addr->ip);
             }
             addrs->destroy(addrs);
         }
     }
     ifaces->destroy(ifaces);
     this->lock->unlock(this->lock);
     return SUCCESS;
 }
static bool is_address_better (private_kernel_netlink_net_t * this, addr_entry_t * a, addr_entry_t * b, host_t * d) static
Compare two IP addresses and return TRUE if the second address is the better choice of the two to reach the destination. For IPv6 we approximately follow RFC 6724.
Definition at line 781 of file kernel_netlink_net.c.
References common_prefix(), FALSE, addr_entry_t::flags, host_t::get_family, get_scope(), addr_entry_t::ip, and sa.
Referenced by get_interface_address().
 {
     u_char sa, sb, sd, pa, pb;
     /* rule 2: prefer appropriate scope */
     if (d)
     {
         sa = get_scope(a->ip);
         sb = get_scope(b->ip);
         sd = get_scope(d);
         if (sa < sb)
         {
             return sa < sd;
         }
         else if (sb < sa)
         {
             return sb >= sd;
         }
     }
     if (a->ip->get_family(a->ip) == AF_INET)
     {   /* stop here for IPv4, default to addresses found earlier */
         return FALSE;
     }
     /* rule 3: avoid deprecated addresses (RFC 4862) */
     if ((a->flags & IFA_F_DEPRECATED) != (b->flags & IFA_F_DEPRECATED))
     {
         return a->flags & IFA_F_DEPRECATED;
     }
     /* rule 4 is not applicable as we don't know if an address is a home or
      * care-of addresses.
      * rule 5 does not apply as we only compare addresses from one interface
      * rule 6 requires a policy table (optionally configurable) to match
      * configurable labels
      */
     /* rule 7: prefer temporary addresses (WE REVERSE THIS BY DEFAULT!) */
     if ((a->flags & IFA_F_TEMPORARY) != (b->flags & IFA_F_TEMPORARY))
     {
         if (this->prefer_temporary_addrs)
         {
             return b->flags & IFA_F_TEMPORARY;
         }
         return a->flags & IFA_F_TEMPORARY;
     }
     /* rule 8: use longest matching prefix */
     if (d)
     {
         pa = common_prefix(a->ip, d);
         pb = common_prefix(b->ip, d);
         if (pa != pb)
         {
             return pb > pa;
         }
     }
     /* default to addresses found earlier */
     return FALSE;
 }
static bool is_interface_up_and_usable (private_kernel_netlink_net_t * this, int index) static
check if an interface with a given index is up and usable
this->lock must be locked when calling this function
Definition at line 936 of file kernel_netlink_net.c.
References FALSE, iface_entry_by_index(), iface_entry_up_and_usable(), and SUCCESS.
Referenced by get_route(), and process_route().
 {
     iface_entry_t *iface;
     if (this->ifaces->find_first(this->ifaces, (void*)iface_entry_by_index,
                                  (void**)&iface, &index) == SUCCESS)
     {
         return iface_entry_up_and_usable(iface);
     }
     return FALSE;
 }
static bool is_known_vip (private_kernel_netlink_net_t * this, host_t * ip) static
check if the given IP is known as virtual IP
this->lock must be held when calling this function
Definition at line 661 of file kernel_netlink_net.c.
References addr_map_entry_match(), ip, and lookup.
Referenced by get_route(), METHOD(), and process_route().
 {
     addr_map_entry_t lookup = {
         .ip = ip,
     };
     return this->vips->get_match(this->vips, &lookup,
                                 (void*)addr_map_entry_match) != NULL;
 }
static bool is_vip_installed_or_gone (private_kernel_netlink_net_t * this, host_t * ip, addr_map_entry_t ** entry) static
check if the given IP is known as virtual IP and currently installed
this function will also return TRUE if the virtual IP entry disappeared. in that case the returned entry will be NULL.
this->lock must be held when calling this function
Definition at line 640 of file kernel_netlink_net.c.
References addr_map_entry_match(), ip, lookup, and TRUE.
Referenced by METHOD().
 {
     addr_map_entry_t lookup = {
         .ip = ip,
     };
     *entry = this->vips->get_match(this->vips, &lookup,
                                   (void*)addr_map_entry_match);
     if (*entry == NULL)
     {   /* the virtual IP disappeared */
         return TRUE;
     }
     return (*entry)->addr->installed;
 }
static status_t manage_ipaddr (private_kernel_netlink_net_t * this, int nlmsg_type, int flags, int if_index, host_t * ip, int prefix) static
Manages the creation and deletion of ip addresses on an interface. By setting the appropriate nlmsg_type, the ip will be set or unset.
Definition at line 1930 of file kernel_netlink_net.c.
References chunk_from_thing, flags, host_t::get_address, host_t::get_family, netlink_buf_t::hdr, chunk_t::len, memset, msg, netlink_add_attribute(), NLM_F_ACK, NLM_F_REQUEST, NLMSG_DATA, nlmsghdr::nlmsg_flags, nlmsghdr::nlmsg_len, NLMSG_LENGTH, nlmsghdr::nlmsg_type, prefix, request(), RT_SCOPE_UNIVERSE, and socket.
Referenced by METHOD().
 {
     netlink_buf_t request;
     struct nlmsghdr *hdr;
     struct ifaddrmsg *msg;
     chunk_t chunk;
     memset(&request, 0, sizeof(request));
     chunk = ip->get_address(ip);
     hdr = &request.hdr;
     hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
     hdr->nlmsg_type = nlmsg_type;
     hdr->nlmsg_len = NLMSG_LENGTH(sizeof(struct ifaddrmsg));
     msg = NLMSG_DATA(hdr);
     msg->ifa_family = ip->get_family(ip);
     msg->ifa_flags = 0;
     msg->ifa_prefixlen = prefix < 0 ? chunk.len * 8 : prefix;
     msg->ifa_scope = RT_SCOPE_UNIVERSE;
     msg->ifa_index = if_index;
     netlink_add_attribute(hdr, IFA_LOCAL, chunk, sizeof(request));
     if (ip->get_family(ip) == AF_INET6 && this->rta_prefsrc_for_ipv6)
     {   /* if source routes are possible we let the virtual IP get deprecated
          * immediately (but mark it as valid forever) so it gets only used if
          * forced by our route, and not by the default IPv6 address selection */
         struct ifa_cacheinfo cache = {
             .ifa_valid = 0xFFFFFFFF,
             .ifa_prefered = 0,
         };
         netlink_add_attribute(hdr, IFA_CACHEINFO, chunk_from_thing(cache),
                               sizeof(request));
     }
     return this->socket->send_ack(this->socket, hdr);
 }
static status_t manage_rule (private_kernel_netlink_net_t * this, int nlmsg_type, int family, u_int32_t table, u_int32_t prio) static
create or delete a rule to use our routing table
Definition at line 2385 of file kernel_netlink_net.c.
References chunk_from_thing, DBG1, DBG_KNL, family, settings_t::get_str, netlink_buf_t::hdr, lib, mark_from_string(), mark_t::mask, memset, msg, netlink_add_attribute(), NLM_F_ACK, NLM_F_CREATE, NLM_F_EXCL, NLM_F_REQUEST, NLMSG_DATA, nlmsghdr::nlmsg_flags, nlmsghdr::nlmsg_len, NLMSG_LENGTH, nlmsghdr::nlmsg_type, library_t::ns, request(), RT_SCOPE_UNIVERSE, RTA_PRIORITY, rtmsg::rtm_family, rtmsg::rtm_flags, RTM_NEWRULE, rtmsg::rtm_protocol, rtmsg::rtm_scope, rtmsg::rtm_table, rtmsg::rtm_type, RTN_UNICAST, RTPROT_BOOT, library_t::settings, socket, and mark_t::value.
Referenced by kernel_netlink_net_create(), and METHOD().
 {
     netlink_buf_t request;
     struct nlmsghdr *hdr;
     struct rtmsg *msg;
     chunk_t chunk;
     char *fwmark;
     memset(&request, 0, sizeof(request));
     hdr = &request.hdr;
     hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK;
     hdr->nlmsg_type = nlmsg_type;
     if (nlmsg_type == RTM_NEWRULE)
     {
         hdr->nlmsg_flags |= NLM_F_CREATE | NLM_F_EXCL;
     }
     hdr->nlmsg_len = NLMSG_LENGTH(sizeof(struct rtmsg));
     msg = NLMSG_DATA(hdr);
     msg->rtm_table = table;
     msg->rtm_family = family;
     msg->rtm_protocol = RTPROT_BOOT;
     msg->rtm_scope = RT_SCOPE_UNIVERSE;
     msg->rtm_type = RTN_UNICAST;
     chunk = chunk_from_thing(prio);
     netlink_add_attribute(hdr, RTA_PRIORITY, chunk, sizeof(request));
     fwmark = lib->settings->get_str(lib->settings,
                             "%s.plugins.kernel-netlink.fwmark", NULL, lib->ns);
     if (fwmark)
     {
 #ifdef HAVE_LINUX_FIB_RULES_H
         mark_t mark;
         if (fwmark[0] == '!')
         {
             msg->rtm_flags |= FIB_RULE_INVERT;
             fwmark++;
         }
         if (mark_from_string(fwmark, &mark))
         {
             chunk = chunk_from_thing(mark.value);
             netlink_add_attribute(hdr, FRA_FWMARK, chunk, sizeof(request));
             chunk = chunk_from_thing(mark.mask);
             netlink_add_attribute(hdr, FRA_FWMASK, chunk, sizeof(request));
             if (msg->rtm_flags & FIB_RULE_INVERT)
             {
                 this->routing_mark = mark;
             }
         }
 #else
         DBG1(DBG_KNL, "setting firewall mark on routing rule is not supported");
 #endif
     }
     return this->socket->send_ack(this->socket, hdr);
 }
static status_t manage_srcroute (private_kernel_netlink_net_t * this, int nlmsg_type, int flags, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, host_t * src_ip, char * if_name) static
Forward declaration
Manages source routes in the routing table. By setting the appropriate nlmsg_type, the route gets added or removed.
Definition at line 2144 of file kernel_netlink_net.c.
References chunk_alloca, flags, host_t::get_address, host_t::get_family, get_interface_index(), netlink_buf_t::hdr, if(), chunk_t::len, memcpy, memset, msg, netlink_add_attribute(), NLM_F_ACK, NLM_F_REQUEST, NLMSG_DATA, nlmsghdr::nlmsg_flags, nlmsghdr::nlmsg_len, NLMSG_LENGTH, nlmsghdr::nlmsg_type, chunk_t::ptr, request(), RT_SCOPE_UNIVERSE, RTA_ALIGN, RTA_DATA, RTA_DST, RTA_GATEWAY, rtattr::rta_len, RTA_LENGTH, RTA_METRICS, RTA_OIF, RTA_PREFSRC, rtattr::rta_type, RTAX_ADVMSS, RTAX_MTU, rtmsg::rtm_dst_len, rtmsg::rtm_family, rtmsg::rtm_protocol, rtmsg::rtm_scope, rtmsg::rtm_table, rtmsg::rtm_type, RTN_UNICAST, RTPROT_STATIC, socket, and status.
Referenced by METHOD(), and reinstall_routes().
 {
     netlink_buf_t request;
     struct nlmsghdr *hdr;
     struct rtmsg *msg;
     struct rtattr *rta;
     int ifindex;
     chunk_t chunk;
     /* if route is 0.0.0.0/0, we can't install it, as it would
      * overwrite the default route. Instead, we add two routes:
      * 0.0.0.0/1 and 128.0.0.0/1 */
     if (this->routing_table == 0 && prefixlen == 0)
     {
         chunk_t half_net;
         u_int8_t half_prefixlen;
         status_t status;
         half_net = chunk_alloca(dst_net.len);
         memset(half_net.ptr, 0, half_net.len);
         half_prefixlen = 1;
         status = manage_srcroute(this, nlmsg_type, flags, half_net, half_prefixlen,
                     gateway, src_ip, if_name);
         half_net.ptr[0] |= 0x80;
         status = manage_srcroute(this, nlmsg_type, flags, half_net, half_prefixlen,
                     gateway, src_ip, if_name);
         return status;
     }
     memset(&request, 0, sizeof(request));
     hdr = &request.hdr;
     hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
     hdr->nlmsg_type = nlmsg_type;
     hdr->nlmsg_len = NLMSG_LENGTH(sizeof(struct rtmsg));
     msg = NLMSG_DATA(hdr);
     msg->rtm_family = src_ip->get_family(src_ip);
     msg->rtm_dst_len = prefixlen;
     msg->rtm_table = this->routing_table;
     msg->rtm_protocol = RTPROT_STATIC;
     msg->rtm_type = RTN_UNICAST;
     msg->rtm_scope = RT_SCOPE_UNIVERSE;
     netlink_add_attribute(hdr, RTA_DST, dst_net, sizeof(request));
     chunk = src_ip->get_address(src_ip);
     netlink_add_attribute(hdr, RTA_PREFSRC, chunk, sizeof(request));
     if (gateway && gateway->get_family(gateway) == src_ip->get_family(src_ip))
     {
         chunk = gateway->get_address(gateway);
         netlink_add_attribute(hdr, RTA_GATEWAY, chunk, sizeof(request));
     }
     ifindex = get_interface_index(this, if_name);
     chunk.ptr = (char*)&ifindex;
     chunk.len = sizeof(ifindex);
     netlink_add_attribute(hdr, RTA_OIF, chunk, sizeof(request));
     if (this->mtu || this->mss)
     {
         chunk = chunk_alloca(RTA_LENGTH((sizeof(struct rtattr) +
                                          sizeof(u_int32_t)) * 2));
         chunk.len = 0;
         rta = (struct rtattr*)chunk.ptr;
         if (this->mtu)
         {
             rta->rta_type = RTAX_MTU;
             rta->rta_len = RTA_LENGTH(sizeof(u_int32_t));
             memcpy(RTA_DATA(rta), &this->mtu, sizeof(u_int32_t));
             chunk.len = rta->rta_len;
         }
         if (this->mss)
         {
             rta = (struct rtattr*)(chunk.ptr + RTA_ALIGN(chunk.len));
             rta->rta_type = RTAX_ADVMSS;
             rta->rta_len = RTA_LENGTH(sizeof(u_int32_t));
             memcpy(RTA_DATA(rta), &this->mss, sizeof(u_int32_t));
             chunk.len = RTA_ALIGN(chunk.len) + rta->rta_len;
         }
         netlink_add_attribute(hdr, RTA_METRICS, chunk, sizeof(request));
     }
     return this->socket->send_ack(this->socket, hdr);
 }
METHOD (kernel_net_t , create_address_enumerator , enumerator_t * , private_kernel_netlink_net_t * this, kernel_address_type_t which)
Definition at line 1410 of file kernel_netlink_net.c.
References address_enumerator_destroy(), create_iface_enumerator(), data, enumerator_create_filter(), enumerator_create_nested(), filter_interfaces(), INIT, and lock.
 {
     address_enumerator_t *data;
     INIT(data,
         .this = this,
         .which = which,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(
                 enumerator_create_filter(
                     this->ifaces->create_enumerator(this->ifaces),
                     (void*)filter_interfaces, data, NULL),
                 (void*)create_iface_enumerator, data,
                 (void*)address_enumerator_destroy);
 }
METHOD (kernel_net_t , get_interface_name , bool , private_kernel_netlink_net_t * this, host_t * ip, char ** name)
Definition at line 1429 of file kernel_netlink_net.c.
References addr_map_entry_match_up(), addr_map_entry_match_up_and_usable(), DBG2, DBG_KNL, FALSE, addr_map_entry_t::iface, iface_entry_t::ifname, ip, host_t::is_anyaddr, lock, lookup, strdup, TRUE, and spinlock_t::unlock.
 {
     addr_map_entry_t *entry, lookup = {
         .ip = ip,
     };
     if (ip->is_anyaddr(ip))
     {
         return FALSE;
     }
     this->lock->read_lock(this->lock);
     /* first try to find it on an up and usable interface */
     entry = this->addrs->get_match(this->addrs, &lookup,
                                   (void*)addr_map_entry_match_up_and_usable);
     if (entry)
     {
         if (name)
         {
             *name = strdup(entry->iface->ifname);
             DBG2(DBG_KNL, "%H is on interface %s", ip, *name);
         }
         this->lock->unlock(this->lock);
         return TRUE;
     }
     /* in a second step, consider virtual IPs installed by us */
     entry = this->vips->get_match(this->vips, &lookup,
                                   (void*)addr_map_entry_match_up_and_usable);
     if (entry)
     {
         if (name)
         {
             *name = strdup(entry->iface->ifname);
             DBG2(DBG_KNL, "virtual IP %H is on interface %s", ip, *name);
         }
         this->lock->unlock(this->lock);
         return TRUE;
     }
     /* maybe it is installed on an ignored interface */
     entry = this->addrs->get_match(this->addrs, &lookup,
                                   (void*)addr_map_entry_match_up);
     if (!entry)
     {
         DBG2(DBG_KNL, "%H is not a local address or the interface is down", ip);
     }
     this->lock->unlock(this->lock);
     return FALSE;
 }
METHOD (kernel_net_t , get_source_addr , host_t * , private_kernel_netlink_net_t * this, host_t * dest, host_t * src)
Definition at line 1914 of file kernel_netlink_net.c.
References FALSE, and get_route().
 {
     return get_route(this, dest, -1, FALSE, src, 0);
 }
METHOD (kernel_net_t , get_nexthop , host_t * , private_kernel_netlink_net_t * this, host_t * dest, int prefix, host_t * src)
Definition at line 1920 of file kernel_netlink_net.c.
References get_route(), and TRUE.
 {
     return get_route(this, dest, prefix, TRUE, src, 0);
 }
METHOD (kernel_net_t , add_ip , status_t , private_kernel_netlink_net_t * this, host_t * virtual_ip, int prefix, char * iface_name)
Definition at line 1970 of file kernel_netlink_net.c.
References addr_map_entry_t::addr, addr, addr_map_entry_add(), addr_map_entry_match(), iface_entry_t::addrs, host_t::clone, condvar, DBG1, DBG2, DBG_KNL, FAILED, addr_map_entry_t::iface, iface_entry_by_name(), iface_entry_t::ifindex, iface_entry_t::ifname, INIT, linked_list_t::insert_last, ip, is_vip_installed_or_gone(), lock, lookup, manage_ipaddr(), NLM_F_CREATE, NLM_F_EXCL, queue_route_reinstall(), addr_entry_t::refcount, RT_SCOPE_UNIVERSE, RTM_NEWADDR, strdup, SUCCESS, spinlock_t::unlock, and condvar_t::wait.
 {
     addr_map_entry_t *entry, lookup = {
         .ip = virtual_ip,
     };
     iface_entry_t *iface = NULL;
     if (!this->install_virtual_ip)
     {   /* disabled by config */
         return SUCCESS;
     }
     this->lock->write_lock(this->lock);
     /* the virtual IP might actually be installed as regular IP, in which case
      * we don't track it as virtual IP */
     entry = this->addrs->get_match(this->addrs, &lookup,
                                   (void*)addr_map_entry_match);
     if (!entry)
     {   /* otherwise it might already be installed as virtual IP */
         entry = this->vips->get_match(this->vips, &lookup,
                                      (void*)addr_map_entry_match);
         if (entry)
         {   /* the vip we found can be in one of three states: 1) installed and
              * ready, 2) just added by another thread, but not yet confirmed to
              * be installed by the kernel, 3) just deleted, but not yet gone.
              * Then while we wait below, several things could happen (as we
              * release the lock).  For instance, the interface could disappear,
              * or the IP is finally deleted, and it reappears on a different
              * interface. All these cases are handled by the call below. */
             while (!is_vip_installed_or_gone(this, virtual_ip, &entry))
             {
                 this->condvar->wait(this->condvar, this->lock);
             }
             if (entry)
             {
                 entry->addr->refcount++;
             }
         }
     }
     if (entry)
     {
         DBG2(DBG_KNL, "virtual IP %H is already installed on %s", virtual_ip,
              entry->iface->ifname);
         this->lock->unlock(this->lock);
         return SUCCESS;
     }
     /* try to find the target interface, either by config or via src ip */
     if (!this->install_virtual_ip_on ||
          this->ifaces->find_first(this->ifaces, (void*)iface_entry_by_name,
                         (void**)&iface, this->install_virtual_ip_on) != SUCCESS)
     {
         if (this->ifaces->find_first(this->ifaces, (void*)iface_entry_by_name,
                                      (void**)&iface, iface_name) != SUCCESS)
         {   /* if we don't find the requested interface we just use the first */
             this->ifaces->get_first(this->ifaces, (void**)&iface);
         }
     }
     if (iface)
     {
         addr_entry_t *addr;
         char *ifname;
         int ifi;
         INIT(addr,
             .ip = virtual_ip->clone(virtual_ip),
             .refcount = 1,
             .scope = RT_SCOPE_UNIVERSE,
         );
         iface->addrs->insert_last(iface->addrs, addr);
         addr_map_entry_add(this->vips, addr, iface);
         ifi = iface->ifindex;
         this->lock->unlock(this->lock);
         if (manage_ipaddr(this, RTM_NEWADDR, NLM_F_CREATE | NLM_F_EXCL,
                           ifi, virtual_ip, prefix) == SUCCESS)
         {
             this->lock->write_lock(this->lock);
             while (!is_vip_installed_or_gone(this, virtual_ip, &entry))
             {   /* wait until address appears */
                 this->condvar->wait(this->condvar, this->lock);
             }
             if (entry)
             {   /* we fail if the interface got deleted in the meantime */
                 ifname = strdup(entry->iface->ifname);
                 this->lock->unlock(this->lock);
                 DBG2(DBG_KNL, "virtual IP %H installed on %s",
                      virtual_ip, ifname);
                 /* during IKEv1 reauthentication, children get moved from
                  * old the new SA before the virtual IP is available. This
                  * kills the route for our virtual IP, reinstall. */
                 queue_route_reinstall(this, ifname);
                 return SUCCESS;
             }
             this->lock->unlock(this->lock);
         }
         DBG1(DBG_KNL, "adding virtual IP %H failed", virtual_ip);
         return FAILED;
     }
     this->lock->unlock(this->lock);
     DBG1(DBG_KNL, "no interface available, unable to install virtual IP %H",
          virtual_ip);
     return FAILED;
 }
METHOD (kernel_net_t , del_ip , status_t , private_kernel_netlink_net_t * this, host_t * virtual_ip, int prefix, bool wait)
Definition at line 2075 of file kernel_netlink_net.c.
References addr_map_entry_t::addr, addr_map_entry_match(), condvar, DBG2, DBG_KNL, FAILED, FALSE, addr_map_entry_t::iface, iface_entry_t::ifindex, iface_entry_t::ifname, addr_entry_t::installed, is_known_vip(), lock, lookup, manage_ipaddr(), addr_entry_t::refcount, RTM_DELADDR, status, SUCCESS, spinlock_t::unlock, and condvar_t::wait.
 {
     addr_map_entry_t *entry, lookup = {
         .ip = virtual_ip,
     };
     if (!this->install_virtual_ip)
     {   /* disabled by config */
         return SUCCESS;
     }
     DBG2(DBG_KNL, "deleting virtual IP %H", virtual_ip);
     this->lock->write_lock(this->lock);
     entry = this->vips->get_match(this->vips, &lookup,
                                  (void*)addr_map_entry_match);
     if (!entry)
     {   /* we didn't install this IP as virtual IP */
         entry = this->addrs->get_match(this->addrs, &lookup,
                                       (void*)addr_map_entry_match);
         if (entry)
         {
             DBG2(DBG_KNL, "not deleting existing IP %H on %s", virtual_ip,
                  entry->iface->ifname);
             this->lock->unlock(this->lock);
             return SUCCESS;
         }
         DBG2(DBG_KNL, "virtual IP %H not cached, unable to delete", virtual_ip);
         this->lock->unlock(this->lock);
         return FAILED;
     }
     if (entry->addr->refcount == 1)
     {
         status_t status;
         int ifi;
         /* we set this flag so that threads calling add_ip will block and wait
          * until the entry is gone, also so we can wait below */
         entry->addr->installed = FALSE;
         ifi = entry->iface->ifindex;
         this->lock->unlock(this->lock);
         status = manage_ipaddr(this, RTM_DELADDR, 0, ifi, virtual_ip, prefix);
         if (status == SUCCESS && wait)
         {   /* wait until the address is really gone */
             this->lock->write_lock(this->lock);
             while (is_known_vip(this, virtual_ip))
             {
                 this->condvar->wait(this->condvar, this->lock);
             }
             this->lock->unlock(this->lock);
         }
         return status;
     }
     else
     {
         entry->addr->refcount--;
     }
     DBG2(DBG_KNL, "virtual IP %H used by other SAs, not deleting",
          virtual_ip);
     this->lock->unlock(this->lock);
     return SUCCESS;
 }
METHOD (kernel_net_t , add_route , status_t , private_kernel_netlink_net_t * this, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, host_t * src_ip, char * if_name)
Definition at line 2232 of file kernel_netlink_net.c.
References ALREADY_DONE, found, manage_srcroute(), NLM_F_CREATE, NLM_F_EXCL, route_entry_clone(), RTM_NEWROUTE, status, and SUCCESS.
 {
     status_t status;
     route_entry_t *found, route = {
         .dst_net = dst_net,
         .prefixlen = prefixlen,
         .gateway = gateway,
         .src_ip = src_ip,
         .if_name = if_name,
     };
     this->routes_lock->lock(this->routes_lock);
     found = this->routes->get(this->routes, &route);
     if (found)
     {
         this->routes_lock->unlock(this->routes_lock);
         return ALREADY_DONE;
     }
     status = manage_srcroute(this, RTM_NEWROUTE, NLM_F_CREATE | NLM_F_EXCL,
                              dst_net, prefixlen, gateway, src_ip, if_name);
     if (status == SUCCESS)
     {
         found = route_entry_clone(&route);
         this->routes->put(this->routes, found, found);
     }
     this->routes_lock->unlock(this->routes_lock);
     return status;
 }
METHOD (kernel_net_t , del_route , status_t , private_kernel_netlink_net_t * this, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, host_t * src_ip, char * if_name)
Definition at line 2263 of file kernel_netlink_net.c.
References found, manage_srcroute(), NOT_FOUND, route_entry_destroy(), RTM_DELROUTE, and status.
 {
     status_t status;
     route_entry_t *found, route = {
         .dst_net = dst_net,
         .prefixlen = prefixlen,
         .gateway = gateway,
         .src_ip = src_ip,
         .if_name = if_name,
     };
     this->routes_lock->lock(this->routes_lock);
     found = this->routes->get(this->routes, &route);
     if (!found)
     {
         this->routes_lock->unlock(this->routes_lock);
         return NOT_FOUND;
     }
     this->routes->remove(this->routes, found);
     route_entry_destroy(found);
     status = manage_srcroute(this, RTM_DELROUTE, 0, dst_net, prefixlen,
                              gateway, src_ip, if_name);
     this->routes_lock->unlock(this->routes_lock);
     return status;
 }
METHOD (kernel_net_t , destroy , void , private_kernel_netlink_net_t * this)
Definition at line 2496 of file kernel_netlink_net.c.
References addr_map_destroy(), close, condvar, spinlock_t::destroy, enumerator_t::destroy, condvar_t::destroy, DESTROY_IF, route_entry_t::dst_net, enumerator_t::enumerate, free(), route_entry_t::gateway, route_entry_t::if_name, iface_entry_destroy(), lib, lock, manage_rule(), manage_srcroute(), net_changes_clear(), route_entry_t::prefixlen, watcher_t::remove, route_entry_destroy(), RTM_DELROUTE, RTM_DELRULE, socket, route_entry_t::src_ip, and library_t::watcher.
 {
     enumerator_t *enumerator;
     route_entry_t *route;
     if (this->routing_table)
     {
         manage_rule(this, RTM_DELRULE, AF_INET, this->routing_table,
                     this->routing_table_prio);
         manage_rule(this, RTM_DELRULE, AF_INET6, this->routing_table,
                     this->routing_table_prio);
     }
     if (this->socket_events > 0)
     {
         lib->watcher->remove(lib->watcher, this->socket_events);
         close(this->socket_events);
     }
     enumerator = this->routes->create_enumerator(this->routes);
     while (enumerator->enumerate(enumerator, NULL, (void**)&route))
     {
         manage_srcroute(this, RTM_DELROUTE, 0, route->dst_net, route->prefixlen,
                         route->gateway, route->src_ip, route->if_name);
         route_entry_destroy(route);
     }
     enumerator->destroy(enumerator);
     this->routes->destroy(this->routes);
     this->routes_lock->destroy(this->routes_lock);
     DESTROY_IF(this->socket);
     net_changes_clear(this);
     this->net_changes->destroy(this->net_changes);
     this->net_changes_lock->destroy(this->net_changes_lock);
     addr_map_destroy(this->addrs);
     addr_map_destroy(this->vips);
     this->ifaces->destroy_function(this->ifaces, (void*)iface_entry_destroy);
     this->rt_exclude->destroy(this->rt_exclude);
     this->roam_lock->destroy(this->roam_lock);
     this->condvar->destroy(this->condvar);
     this->lock->destroy(this->lock);
     free(this);
 }
static void net_change_destroy (net_change_t * this) static
Destroy a net_change_t object
Definition at line 350 of file kernel_netlink_net.c.
References free().
Referenced by net_changes_clear(), and queue_route_reinstall().
 {
     free(this->if_name);
     free(this);
 }
static bool net_change_equals (net_change_t * a, net_change_t * b) static
Compare two net_change_t objects
Definition at line 367 of file kernel_netlink_net.c.
References net_change_t::if_name, and streq().
Referenced by kernel_netlink_net_create().
 {
     return streq(a->if_name, b->if_name);
 }
static u_int net_change_hash (net_change_t * this) static
Hash a net_change_t object
Definition at line 359 of file kernel_netlink_net.c.
References chunk_create(), and chunk_hash().
Referenced by kernel_netlink_net_create().
 {
     return chunk_hash(chunk_create(this->if_name, strlen(this->if_name)));
 }
static void net_changes_clear (private_kernel_netlink_net_t * this) static
Clear the queued network changes.
Definition at line 535 of file kernel_netlink_net.c.
References enumerator_t::destroy, enumerator_t::enumerate, and net_change_destroy().
Referenced by METHOD(), and reinstall_routes().
 {
     enumerator_t *enumerator;
     net_change_t *change;
     enumerator = this->net_changes->create_enumerator(this->net_changes);
     while (enumerator->enumerate(enumerator, NULL, (void**)&change))
     {
         this->net_changes->remove_at(this->net_changes, enumerator);
         net_change_destroy(change);
     }
     enumerator->destroy(enumerator);
 }
static rt_entry_t* parse_route (struct nlmsghdr * hdr, rt_entry_t * route) static
Parse route received with RTM_NEWROUTE. The given rt_entry_t object will be reused if not NULL.
Returned chunks point to internal data of the Netlink message.
Definition at line 1589 of file kernel_netlink_net.c.
References chunk_create(), chunk_empty, rt_entry_t::dst, rt_entry_t::dst_len, rt_entry_t::gtw, INIT, msg, NLMSG_DATA, rt_entry_t::oif, rt_entry_t::priority, RTA_DATA, RTA_DST, RTA_GATEWAY, RTA_NEXT, RTA_OIF, RTA_OK, RTA_PAYLOAD, RTA_PREFSRC, RTA_PRIORITY, RTA_TABLE, rtattr::rta_type, rtmsg::rtm_dst_len, RTM_PAYLOAD, RTM_RTA, rtmsg::rtm_table, rt_entry_t::src, and rt_entry_t::table.
Referenced by get_route().
 {
     struct rtattr *rta;
     struct rtmsg *msg;
     size_t rtasize;
     msg = NLMSG_DATA(hdr);
     rta = RTM_RTA(msg);
     rtasize = RTM_PAYLOAD(hdr);
     if (route)
     {
         route->gtw = chunk_empty;
         route->src = chunk_empty;
         route->dst = chunk_empty;
         route->dst_len = msg->rtm_dst_len;
         route->table = msg->rtm_table;
         route->oif = 0;
         route->priority = 0;
     }
     else
     {
         INIT(route,
             .dst_len = msg->rtm_dst_len,
             .table = msg->rtm_table,
         );
     }
     while (RTA_OK(rta, rtasize))
     {
         switch (rta->rta_type)
         {
             case RTA_PREFSRC:
                 route->src = chunk_create(RTA_DATA(rta), RTA_PAYLOAD(rta));
                 break;
             case RTA_GATEWAY:
                 route->gtw = chunk_create(RTA_DATA(rta), RTA_PAYLOAD(rta));
                 break;
             case RTA_DST:
                 route->dst = chunk_create(RTA_DATA(rta), RTA_PAYLOAD(rta));
                 break;
             case RTA_OIF:
                 if (RTA_PAYLOAD(rta) == sizeof(route->oif))
                 {
                     route->oif = *(u_int32_t*)RTA_DATA(rta);
                 }
                 break;
             case RTA_PRIORITY:
                 if (RTA_PAYLOAD(rta) == sizeof(route->priority))
                 {
                     route->priority = *(u_int32_t*)RTA_DATA(rta);
                 }
                 break;
 #ifdef HAVE_RTA_TABLE
             case RTA_TABLE:
                 if (RTA_PAYLOAD(rta) == sizeof(route->table))
                 {
                     route->table = *(u_int32_t*)RTA_DATA(rta);
                 }
                 break;
 #endif /* HAVE_RTA_TABLE*/
         }
         rta = RTA_NEXT(rta, rtasize);
     }
     return route;
 }
static void process_addr (private_kernel_netlink_net_t * this, struct nlmsghdr * hdr, bool event) static
process RTM_NEWADDR/RTM_DELADDR from kernel
Definition at line 1071 of file kernel_netlink_net.c.
References addr_map_entry_t::addr, addr, addr_entry_destroy(), addr_map_entry_add(), addr_map_entry_remove(), iface_entry_t::addrs, condvar_t::broadcast, chunk_empty, host_t::clone, condvar, DBG1, DBG_KNL, host_t::destroy, FALSE, fire_roam_event(), iface_entry_t::flags, found, free(), host, host_create_from_chunk(), iface_entry_by_index(), iface_entry_t::ifname, INIT, linked_list_t::insert_last, addr_entry_t::installed, ip, chunk_t::len, lock, lookup, msg, NLMSG_DATA, nlmsghdr::nlmsg_type, chunk_t::ptr, queue_route_reinstall(), linked_list_t::remove, RTA_DATA, RTA_NEXT, RTA_OK, RTA_PAYLOAD, rtattr::rta_type, RTM_DELADDR, RTM_NEWADDR, strdup, SUCCESS, TRUE, spinlock_t::unlock, update(), and iface_entry_t::usable.
Referenced by init_address_list(), and receive_events().
 {
     struct ifaddrmsg* msg = NLMSG_DATA(hdr);
     struct rtattr *rta = IFA_RTA(msg);
     size_t rtasize = IFA_PAYLOAD (hdr);
     host_t *host = NULL;
     iface_entry_t *iface;
     chunk_t local = chunk_empty, address = chunk_empty;
     char *route_ifname = NULL;
     bool update = FALSE, found = FALSE, changed = FALSE;
     while (RTA_OK(rta, rtasize))
     {
         switch (rta->rta_type)
         {
             case IFA_LOCAL:
                 local.ptr = RTA_DATA(rta);
                 local.len = RTA_PAYLOAD(rta);
                 break;
             case IFA_ADDRESS:
                 address.ptr = RTA_DATA(rta);
                 address.len = RTA_PAYLOAD(rta);
                 break;
         }
         rta = RTA_NEXT(rta, rtasize);
     }
     /* For PPP interfaces, we need the IFA_LOCAL address,
      * IFA_ADDRESS is the peers address. But IFA_LOCAL is
      * not included in all cases (IPv6?), so fallback to IFA_ADDRESS. */
     if (local.ptr)
     {
         host = host_create_from_chunk(msg->ifa_family, local, 0);
     }
     else if (address.ptr)
     {
         host = host_create_from_chunk(msg->ifa_family, address, 0);
     }
     if (host == NULL)
     {   /* bad family? */
         return;
     }
     this->lock->write_lock(this->lock);
     if (this->ifaces->find_first(this->ifaces, (void*)iface_entry_by_index,
                                  (void**)&iface, &msg->ifa_index) == SUCCESS)
     {
         addr_map_entry_t *entry, lookup = {
             .ip = host,
             .iface = iface,
         };
         addr_entry_t *addr;
         entry = this->vips->get(this->vips, &lookup);
         if (entry)
         {
             if (hdr->nlmsg_type == RTM_NEWADDR)
             {   /* mark as installed and signal waiting threads */
                 entry->addr->installed = TRUE;
             }
             else
             {   /* the address was already marked as uninstalled */
                 addr = entry->addr;
                 iface->addrs->remove(iface->addrs, addr, NULL);
                 addr_map_entry_remove(this->vips, addr, iface);
                 addr_entry_destroy(addr);
             }
             /* no roam events etc. for virtual IPs */
             this->condvar->broadcast(this->condvar);
             this->lock->unlock(this->lock);
             host->destroy(host);
             return;
         }
         entry = this->addrs->get(this->addrs, &lookup);
         if (entry)
         {
             if (hdr->nlmsg_type == RTM_DELADDR)
             {
                 found = TRUE;
                 addr = entry->addr;
                 iface->addrs->remove(iface->addrs, addr, NULL);
                 if (iface->usable)
                 {
                     changed = TRUE;
                     DBG1(DBG_KNL, "%H disappeared from %s", host,
                          iface->ifname);
                 }
                 addr_map_entry_remove(this->addrs, addr, iface);
                 addr_entry_destroy(addr);
             }
         }
         else
         {
             if (hdr->nlmsg_type == RTM_NEWADDR)
             {
                 found = TRUE;
                 changed = TRUE;
                 route_ifname = strdup(iface->ifname);
                 INIT(addr,
                     .ip = host->clone(host),
                     .flags = msg->ifa_flags,
                     .scope = msg->ifa_scope,
                 );
                 iface->addrs->insert_last(iface->addrs, addr);
                 addr_map_entry_add(this->addrs, addr, iface);
                 if (event && iface->usable)
                 {
                     DBG1(DBG_KNL, "%H appeared on %s", host, iface->ifname);
                 }
             }
         }
         if (found && (iface->flags & IFF_UP))
         {
             update = TRUE;
         }
         if (!iface->usable)
         {   /* ignore events for interfaces excluded by config */
             update = changed = FALSE;
         }
     }
     this->lock->unlock(this->lock);
     if (update && event && route_ifname)
     {
         queue_route_reinstall(this, route_ifname);
     }
     else
     {
         free(route_ifname);
     }
     host->destroy(host);
     /* send an update to all IKE_SAs */
     if (update && event && changed)
     {
         fire_roam_event(this, TRUE);
     }
 }
static void process_link (private_kernel_netlink_net_t * this, struct nlmsghdr * hdr, bool event) static
process RTM_NEWLINK/RTM_DELLINK from kernel
Definition at line 969 of file kernel_netlink_net.c.
References addr_entry_unregister(), iface_entry_t::addrs, DBG1, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, FALSE, fire_roam_event(), iface_entry_t::flags, hydra, iface_entry_by_index(), iface_entry_destroy(), ifinfomsg::ifi_flags, ifinfomsg::ifi_index, iface_entry_t::ifindex, iface_entry_t::ifname, INIT, linked_list_t::invoke_function, kernel_interface_t::is_interface_usable, hydra_t::kernel_interface, linked_list_create(), lock, msg, name, NLMSG_DATA, nlmsghdr::nlmsg_type, queue_route_reinstall(), RTA_DATA, RTA_NEXT, RTA_OK, rtattr::rta_type, RTM_DELLINK, RTM_NEWLINK, strdup, SUCCESS, TRUE, spinlock_t::unlock, update(), and iface_entry_t::usable.
Referenced by init_address_list(), and receive_events().
 {
     struct ifinfomsg* msg = NLMSG_DATA(hdr);
     struct rtattr *rta = IFLA_RTA(msg);
     size_t rtasize = IFLA_PAYLOAD (hdr);
     enumerator_t *enumerator;
     iface_entry_t *current, *entry = NULL;
     char *name = NULL;
     bool update = FALSE, update_routes = FALSE;
     while (RTA_OK(rta, rtasize))
     {
         switch (rta->rta_type)
         {
             case IFLA_IFNAME:
                 name = RTA_DATA(rta);
                 break;
         }
         rta = RTA_NEXT(rta, rtasize);
     }
     if (!name)
     {
         name = "(unknown)";
     }
     this->lock->write_lock(this->lock);
     switch (hdr->nlmsg_type)
     {
         case RTM_NEWLINK:
         {
             if (this->ifaces->find_first(this->ifaces,
                                     (void*)iface_entry_by_index, (void**)&entry,
                                     &msg->ifi_index) != SUCCESS)
             {
                 INIT(entry,
                     .ifindex = msg->ifi_index,
                     .addrs = linked_list_create(),
                     .usable = hydra->kernel_interface->is_interface_usable(
                                                 hydra->kernel_interface, name),
                 );
                 this->ifaces->insert_last(this->ifaces, entry);
             }
             strncpy(entry->ifname, name, IFNAMSIZ);
             entry->ifname[IFNAMSIZ-1] = '\0';
             if (event && entry->usable)
             {
                 if (!(entry->flags & IFF_UP) && (msg->ifi_flags & IFF_UP))
                 {
                     update = update_routes = TRUE;
                     DBG1(DBG_KNL, "interface %s activated", name);
                 }
                 if ((entry->flags & IFF_UP) && !(msg->ifi_flags & IFF_UP))
                 {
                     update = TRUE;
                     DBG1(DBG_KNL, "interface %s deactivated", name);
                 }
             }
             entry->flags = msg->ifi_flags;
             break;
         }
         case RTM_DELLINK:
         {
             enumerator = this->ifaces->create_enumerator(this->ifaces);
             while (enumerator->enumerate(enumerator, &current))
             {
                 if (current->ifindex == msg->ifi_index)
                 {
                     if (event && current->usable)
                     {
                         update = TRUE;
                         DBG1(DBG_KNL, "interface %s deleted", current->ifname);
                     }
                     /* TODO: move virtual IPs installed on this interface to
                      * another interface? */
                     this->ifaces->remove_at(this->ifaces, enumerator);
                     current->addrs->invoke_function(current->addrs,
                                 (void*)addr_entry_unregister, current, this);
                     iface_entry_destroy(current);
                     break;
                 }
             }
             enumerator->destroy(enumerator);
             break;
         }
     }
     this->lock->unlock(this->lock);
     if (update_routes && event)
     {
         queue_route_reinstall(this, strdup(name));
     }
     if (update && event)
     {
         fire_roam_event(this, TRUE);
     }
 }
static void process_route (private_kernel_netlink_net_t * this, struct nlmsghdr * hdr) static
process RTM_NEWROUTE and RTM_DELROUTE from kernel
Definition at line 1215 of file kernel_netlink_net.c.
References chunk_create(), host_t::destroy, DESTROY_IF, FALSE, fire_roam_event(), get_interface_address(), host, host_create_from_chunk(), is_interface_up_and_usable(), is_known_vip(), lock, msg, NLMSG_DATA, RT_TABLE_LOCAL, RTA_DATA, RTA_NEXT, RTA_OIF, RTA_OK, RTA_PAYLOAD, RTA_PREFSRC, rtattr::rta_type, RTM_F_CLONED, rtmsg::rtm_family, rtmsg::rtm_flags, RTM_PAYLOAD, RTM_RTA, rtmsg::rtm_table, and spinlock_t::unlock.
Referenced by receive_events().
 {
     struct rtmsg* msg = NLMSG_DATA(hdr);
     struct rtattr *rta = RTM_RTA(msg);
     size_t rtasize = RTM_PAYLOAD(hdr);
     u_int32_t rta_oif = 0;
     host_t *host = NULL;
     /* ignore routes added by us or in the local routing table (local addrs) */
     if (msg->rtm_table && (msg->rtm_table == this->routing_table ||
                            msg->rtm_table == RT_TABLE_LOCAL))
     {
         return;
     }
     else if (msg->rtm_flags & RTM_F_CLONED)
     {   /* ignore cached routes, seem to be created a lot for IPv6 */
         return;
     }
     while (RTA_OK(rta, rtasize))
     {
         switch (rta->rta_type)
         {
             case RTA_PREFSRC:
                 DESTROY_IF(host);
                 host = host_create_from_chunk(msg->rtm_family,
                             chunk_create(RTA_DATA(rta), RTA_PAYLOAD(rta)), 0);
                 break;
             case RTA_OIF:
                 if (RTA_PAYLOAD(rta) == sizeof(rta_oif))
                 {
                     rta_oif = *(u_int32_t*)RTA_DATA(rta);
                 }
                 break;
         }
         rta = RTA_NEXT(rta, rtasize);
     }
     this->lock->read_lock(this->lock);
     if (rta_oif && !is_interface_up_and_usable(this, rta_oif))
     {   /* ignore route changes for interfaces that are ignored or down */
         this->lock->unlock(this->lock);
         DESTROY_IF(host);
         return;
     }
     if (!host && rta_oif)
     {
         host = get_interface_address(this, rta_oif, msg->rtm_family,
                                      NULL, NULL);
     }
     if (!host || is_known_vip(this, host))
     {   /* ignore routes added for virtual IPs */
         this->lock->unlock(this->lock);
         DESTROY_IF(host);
         return;
     }
     this->lock->unlock(this->lock);
     fire_roam_event(this, FALSE);
     host->destroy(host);
 }
static void queue_route_reinstall (private_kernel_netlink_net_t * this, char * if_name) static
Queue route reinstallation caused by network changes for a given interface.
The route reinstallation is delayed for a while and only done once for several calls during this delay, in order to avoid doing it too often. The interface name is freed.
Definition at line 602 of file kernel_netlink_net.c.
References callback_job_create(), found, INIT, lib, net_change_destroy(), reinstall_routes(), ROUTE_DELAY, scheduler_t::schedule_job_ms, library_t::scheduler, time_monotonic(), timeval_add_ms(), and update().
Referenced by METHOD(), process_addr(), and process_link().
 {
     net_change_t *update, *found;
     timeval_t now;
     job_t *job;
     INIT(update,
         .if_name = if_name
     );
     this->net_changes_lock->lock(this->net_changes_lock);
     found = this->net_changes->put(this->net_changes, update, update);
     if (found)
     {
         net_change_destroy(found);
     }
     time_monotonic(&now);
     if (timercmp(&now, &this->last_route_reinstall, >))
     {
         timeval_add_ms(&now, ROUTE_DELAY);
         this->last_route_reinstall = now;
         job = (job_t*)callback_job_create((callback_job_cb_t)reinstall_routes,
                                           this, NULL, NULL);
         lib->scheduler->schedule_job_ms(lib->scheduler, job, ROUTE_DELAY);
     }
     this->net_changes_lock->unlock(this->net_changes_lock);
 }
static bool receive_events (private_kernel_netlink_net_t * this, int fd, watcher_event_t event) static
Receives events from kernel
Definition at line 1278 of file kernel_netlink_net.c.
References addr, DBG1, DBG_KNL, len, MSG_DONTWAIT, sockaddr_nl::nl_pid, NLMSG_NEXT, NLMSG_OK, nlmsghdr::nlmsg_type, process_addr(), process_link(), process_route(), recvfrom, response, RTM_DELADDR, RTM_DELLINK, RTM_DELROUTE, RTM_NEWADDR, RTM_NEWLINK, RTM_NEWROUTE, sleep, and TRUE.
Referenced by kernel_netlink_net_create().
 {
     char response[1536];
     struct nlmsghdr *hdr = (struct nlmsghdr*)response;
     struct sockaddr_nl addr;
     socklen_t addr_len = sizeof(addr);
     int len;
     len = recvfrom(this->socket_events, response, sizeof(response),
                    MSG_DONTWAIT, (struct sockaddr*)&addr, &addr_len);
     if (len < 0)
     {
         switch (errno)
         {
             case EINTR:
                 /* interrupted, try again */
                 return TRUE;
             case EAGAIN:
                 /* no data ready, select again */
                 return TRUE;
             default:
                 DBG1(DBG_KNL, "unable to receive from rt event socket");
                 sleep(1);
                 return TRUE;
         }
     }
     if (addr.nl_pid != 0)
     {   /* not from kernel. not interested, try another one */
         return TRUE;
     }
     while (NLMSG_OK(hdr, len))
     {
         /* looks good so far, dispatch netlink message */
         switch (hdr->nlmsg_type)
         {
             case RTM_NEWADDR:
             case RTM_DELADDR:
                 process_addr(this, hdr, TRUE);
                 break;
             case RTM_NEWLINK:
             case RTM_DELLINK:
                 process_link(this, hdr, TRUE);
                 break;
             case RTM_NEWROUTE:
             case RTM_DELROUTE:
                 if (this->process_route)
                 {
                     process_route(this, hdr);
                 }
                 break;
             default:
                 break;
         }
         hdr = NLMSG_NEXT(hdr, len);
     }
     return TRUE;
 }
static job_requeue_t reinstall_routes (private_kernel_netlink_net_t * this) static
Act upon queued network changes.
Definition at line 552 of file kernel_netlink_net.c.
References enumerator_t::destroy, route_entry_t::dst_net, enumerator_t::enumerate, free(), route_entry_t::gateway, route_entry_t::if_name, net_change_t::if_name, JOB_REQUEUE_NONE, lookup, manage_srcroute(), net_changes_clear(), NLM_F_CREATE, NLM_F_EXCL, route_entry_t::prefixlen, RTM_NEWROUTE, route_entry_t::src_ip, and streq().
Referenced by queue_route_reinstall().
 {
     enumerator_t *enumerator;
     route_entry_t *route;
     this->net_changes_lock->lock(this->net_changes_lock);
     this->routes_lock->lock(this->routes_lock);
     enumerator = this->routes->create_enumerator(this->routes);
     while (enumerator->enumerate(enumerator, NULL, (void**)&route))
     {
         net_change_t *change, lookup = {
             .if_name = route->if_name,
         };
         /* check if a change for the outgoing interface is queued */
         change = this->net_changes->get(this->net_changes, &lookup);
         if (!change)
         {   /* in case src_ip is not on the outgoing interface */
             if (this->public.interface.get_interface(&this->public.interface,
                                                 route->src_ip, &lookup.if_name))
             {
                 if (!streq(lookup.if_name, route->if_name))
                 {
                     change = this->net_changes->get(this->net_changes, &lookup);
                 }
                 free(lookup.if_name);
             }
         }
         if (change)
         {
             manage_srcroute(this, RTM_NEWROUTE, NLM_F_CREATE | NLM_F_EXCL,
                             route->dst_net, route->prefixlen, route->gateway,
                             route->src_ip, route->if_name);
         }
     }
     enumerator->destroy(enumerator);
     this->routes_lock->unlock(this->routes_lock);
     net_changes_clear(this);
     this->net_changes_lock->unlock(this->net_changes_lock);
     return JOB_REQUEUE_NONE;
 }
static job_requeue_t roam_event (private_kernel_netlink_net_t * this) static
callback function that raises the delayed roam event
Definition at line 888 of file kernel_netlink_net.c.
References FALSE, hydra, JOB_REQUEUE_NONE, hydra_t::kernel_interface, and kernel_interface_t::roam.
Referenced by fire_roam_event().
 {
     bool address;
     this->roam_lock->lock(this->roam_lock);
     address = this->roam_address;
     this->roam_address = FALSE;
     this->roam_lock->unlock(this->roam_lock);
     hydra->kernel_interface->roam(hydra->kernel_interface, address);
     return JOB_REQUEUE_NONE;
 }
static route_entry_t* route_entry_clone (route_entry_t * this) static
Clone a route_entry_t object.
Definition at line 287 of file kernel_netlink_net.c.
References chunk_clone, INIT, and strdup.
Referenced by METHOD().
 {
     route_entry_t *route;
     INIT(route,
         .if_name = strdup(this->if_name),
         .src_ip = this->src_ip->clone(this->src_ip),
         .gateway = this->gateway ? this->gateway->clone(this->gateway) : NULL,
         .dst_net = chunk_clone(this->dst_net),
         .prefixlen = this->prefixlen,
     );
     return route;
 }
static void route_entry_destroy (route_entry_t * this) static
Destroy a route_entry_t object
Definition at line 304 of file kernel_netlink_net.c.
References chunk_free(), DESTROY_IF, and free().
Referenced by METHOD().
 {
     free(this->if_name);
     DESTROY_IF(this->src_ip);
     DESTROY_IF(this->gateway);
     chunk_free(&this->dst_net);
     free(this);
 }
static bool route_entry_equals (route_entry_t * a, route_entry_t * b) static
Compare two route_entry_t objects
Definition at line 325 of file kernel_netlink_net.c.
References chunk_equals(), route_entry_t::dst_net, FALSE, route_entry_t::gateway, route_entry_t::if_name, host_t::ip_equals, route_entry_t::prefixlen, route_entry_t::src_ip, and streq().
Referenced by kernel_netlink_net_create().
 {
     if (a->if_name && b->if_name && streq(a->if_name, b->if_name) &&
         a->src_ip->ip_equals(a->src_ip, b->src_ip) &&
         chunk_equals(a->dst_net, b->dst_net) && a->prefixlen == b->prefixlen)
     {
         return (!a->gateway && !b->gateway) || (a->gateway && b->gateway &&
                     a->gateway->ip_equals(a->gateway, b->gateway));
     }
     return FALSE;
 }
static u_int route_entry_hash (route_entry_t * this) static
Hash a route_entry_t object
Definition at line 316 of file kernel_netlink_net.c.
References chunk_from_thing, chunk_hash(), and chunk_hash_inc().
Referenced by kernel_netlink_net_create().
 {
     return chunk_hash_inc(chunk_from_thing(this->prefixlen),
                           chunk_hash(this->dst_net));
 }
static bool route_usable (struct nlmsghdr * hdr) static
Check if the route received with RTM_NEWROUTE is usable based on its type.
Definition at line 1566 of file kernel_netlink_net.c.
References FALSE, msg, NLMSG_DATA, rtmsg::rtm_type, RTN_BLACKHOLE, RTN_PROHIBIT, RTN_THROW, RTN_UNREACHABLE, and TRUE.
Referenced by get_route().
 {
     struct rtmsg *msg;
     msg = NLMSG_DATA(hdr);
     switch (msg->rtm_type)
     {
         case RTN_BLACKHOLE:
         case RTN_UNREACHABLE:
         case RTN_PROHIBIT:
         case RTN_THROW:
             return FALSE;
         default:
             return TRUE;
     }
 }
static void rt_entry_destroy (rt_entry_t * this) static
Free a route entry
Definition at line 1557 of file kernel_netlink_net.c.
References DESTROY_IF, and free().
Referenced by get_route().
 {
     DESTROY_IF(this->src_host);
     free(this);
 }