strongSwan: led_listener.c File Reference
led_listener.c File Reference
#include "led_listener.h"
#include <errno.h>
#include <daemon.h>
#include <threading/mutex.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_led_listener_t
Typedefs
typedef struct
private_led_listener_t private_led_listener_t
Functions
static FILE * open_led (char *name, int *max_brightness)
static void set_led (FILE *led, int brightness)
static job_requeue_t reset_activity_led (private_led_listener_t *this)
static void blink_activity (private_led_listener_t *this)
METHOD (listener_t, ike_state_change, bool, private_led_listener_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
METHOD (listener_t, message_hook, bool, private_led_listener_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (led_listener_t, destroy, void, private_led_listener_t *this)
led_listener_t * led_listener_create ()
Variables
static bool plugin_gone = FALSE
Typedef Documentation
typedef struct private_led_listener_t private_led_listener_t
Definition at line 24 of file led_listener.c.
Function Documentation
static void blink_activity (private_led_listener_t * this) static
Blink the activity LED
Definition at line 146 of file led_listener.c.
References callback_job_create_with_prio(), count, JOB_PRIO_CRITICAL, lib, mutex_t::lock, mutex, reset_activity_led(), scheduler_t::schedule_job_ms, library_t::scheduler, set_led(), and mutex_t::unlock.
Referenced by METHOD().
 {
     if (this->activity)
     {
         this->mutex->lock(this->mutex);
         if (this->count)
         {
             set_led(this->activity, 0);
         }
         else
         {
             set_led(this->activity, this->activity_max);
         }
         lib->scheduler->schedule_job_ms(lib->scheduler, (job_t*)
             callback_job_create_with_prio((callback_job_cb_t)reset_activity_led,
                         this, NULL, NULL, JOB_PRIO_CRITICAL), this->blink_time);
         this->mutex->unlock(this->mutex);
     }
 }
METHOD (listener_t , ike_state_change , bool , private_led_listener_t * this, ike_sa_t * ike_sa, ike_sa_state_t state)
Definition at line 166 of file led_listener.c.
References count, ike_sa_t::get_state, IKE_ESTABLISHED, mutex_t::lock, mutex, set_led(), TRUE, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     if (state == IKE_ESTABLISHED && ike_sa->get_state(ike_sa) != IKE_ESTABLISHED)
     {
         this->count++;
         if (this->count == 1)
         {
             set_led(this->activity, this->activity_max);
         }
     }
     if (ike_sa->get_state(ike_sa) == IKE_ESTABLISHED && state != IKE_ESTABLISHED)
     {
         this->count--;
         if (this->count == 0)
         {
             set_led(this->activity, 0);
         }
     }
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
METHOD (listener_t , message_hook , bool , private_led_listener_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 190 of file led_listener.c.
References blink_activity(), message_t::get_request, and TRUE.
 {
     if (plain && (incoming || message->get_request(message)))
     {
         blink_activity(this);
     }
     return TRUE;
 }
METHOD (led_listener_t , destroy , void , private_led_listener_t * this)
Definition at line 201 of file led_listener.c.
References mutex_t::destroy, free(), mutex_t::lock, mutex, plugin_gone, set_led(), TRUE, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     set_led(this->activity, 0);
     plugin_gone = TRUE;
     this->mutex->unlock(this->mutex);
     if (this->activity)
     {
         fclose(this->activity);
     }
     this->mutex->destroy(this->mutex);
     free(this);
 }
static FILE* open_led (char * name, int * max_brightness) static
Open a LED brightness control file, get max brightness
Definition at line 65 of file led_listener.c.
References DBG1, DBG_CFG, path, snprintf, and strerror.
Referenced by led_listener_create().
 {
     char path[PATH_MAX];
     FILE *f;
     if (!name)
     {
         return NULL;
     }
     *max_brightness = 1;
     snprintf(path, sizeof(path), "/sys/class/leds/%s/max_brightness", name);
     f = fopen(path, "r");
     if (f)
     {
         if (fscanf(f, "%d\n", max_brightness) != 1)
         {
             DBG1(DBG_CFG, "reading max brightness for '%s' failed: %s, using 1",
                  name, strerror(errno));
         }
         fclose(f);
     }
     else
     {
         DBG1(DBG_CFG, "reading max_brightness for '%s' failed: %s, using 1",
              name, strerror(errno));
     }
     snprintf(path, sizeof(path), "/sys/class/leds/%s/brightness", name);
     f = fopen(path, "w");
     if (!f)
     {
         DBG1(DBG_CFG, "opening LED file '%s' failed: %s", path, strerror(errno));
     }
     return f;
 }
static job_requeue_t reset_activity_led (private_led_listener_t * this) static
Reset activity LED after timeout
Definition at line 125 of file led_listener.c.
References count, JOB_REQUEUE_NONE, mutex_t::lock, mutex, plugin_gone, set_led(), and mutex_t::unlock.
Referenced by blink_activity().
 {
     if (!plugin_gone)
     {   /* TODO: fix race */
         this->mutex->lock(this->mutex);
         if (this->count)
         {
             set_led(this->activity, this->activity_max);
         }
         else
         {
             set_led(this->activity, 0);
         }
         this->mutex->unlock(this->mutex);
     }
     return JOB_REQUEUE_NONE;
 }
static void set_led (FILE * led, int brightness) static
Set a LED to a given brightness
Definition at line 105 of file led_listener.c.
References DBG1, DBG_CFG, fprintf, and strerror.
Referenced by blink_activity(), led_listener_create(), METHOD(), and reset_activity_led().
 {
     if (led)
     {
         if (fprintf(led, "%d\n", brightness) <= 0 ||
             fflush(led) != 0)
         {
             DBG1(DBG_CFG, "setting LED brightness failed: %s", strerror(errno));
         }
     }
 }
Variable Documentation
bool plugin_gone = FALSE static
Plugin unloaded?
Definition at line 120 of file led_listener.c.
Referenced by METHOD(), and reset_activity_led().