strongSwan: mutex_t Struct Reference
mutex_t Struct Reference
mutex
#include "mutex.h"
Public Attributes
void(* lock)(mutex_t *this)
void(* unlock)(mutex_t *this)
void(* destroy)(mutex_t *this)
Detailed Description
Mutex wrapper implements simple, portable and advanced mutex functions.
Definition at line 41 of file mutex.h.
Member Data Documentation
void(* mutex_t::destroy)(mutex_t *this)
Destroy a mutex instance.
Definition at line 56 of file mutex.h.
Referenced by barrier_destroy(), cancellation_cond(), destroy(), destroy_function(), destroy_service(), DestroyMutex(), METHOD(), on_accept(), pkcs11_hasher_create(), START_TEST(), thread_destroy(), threading_cleanup(), threads_deinit(), and vici_disconnect().
void(* mutex_t::lock)(mutex_t *this)
Acquire the lock to the mutex.
Definition at line 46 of file mutex.h.
Referenced by accept_async(), acquire(), activate_all(), add_include(), add_interface(), add_policy_internal(), add_trap(), allocate_addr(), autobalance(), barrier_wait(), blink_activity(), CALLBACK(), cancellation_cond(), check_and_put_init_hash(), complete(), condvar_cancel_run(), condvar_recursive_run(), condvar_run(), condvar_run_broad(), conn_get(), conn_release(), destroy_async_data(), disconnect_async(), dispatch(), do_load_test(), eap_radius_accounting_start_interim(), enable_disable_all(), expire_job(), export_csv(), file_logger_create(), find_entry(), get_route(), handle_ack(), handle_event(), handle_ita_message(), handle_offer(), init_supplementary_groups(), initiate_cb(), initiator_finish(), install_route(), lock_function(), lock_single_segment(), locking_function(), LockMutex(), lookup_queue(), manage_route(), METHOD(), mutex_run(), notify_end(), on_accept(), process_acquire(), process_job(), process_jobs(), process_request(), put_entry(), raise_events(), receive_events(), register_event(), register_load_tester(), release_unclaimed(), remove_entry(), remove_include(), remove_init_hash(), remove_interface(), remove_queue(), remove_trap(), reset_activity_led(), resolve_hosts(), restart(), retransmit(), roam_event(), sa_expired(), schedule(), send_interim(), send_once(), send_packets(), send_start(), send_status(), send_stop(), sender(), START_TEST(), subscribe(), subscribed(), sys_logger_create(), thread_cleanup(), thread_create(), thread_current(), threads_deinit(), token_event_cb(), trap_manager_create(), uninstall_route(), unregister_event(), update_interface(), update_usage(), vici_register(), vici_submit(), wait_result(), watch(), and watchdog().
void(* mutex_t::unlock)(mutex_t *this)
Release the lock on the mutex.
Definition at line 51 of file mutex.h.
Referenced by accept_async(), acquire(), activate_all(), add_include(), add_interface(), add_policy_internal(), add_trap(), allocate_addr(), autobalance(), barrier_wait(), blink_activity(), CALLBACK(), check_and_put_init_hash(), complete(), condvar_cancel_run(), condvar_recursive_run(), condvar_run(), condvar_run_broad(), conn_get(), conn_release(), destroy_async_data(), destroy_filter(), disconnect_async(), dispatch(), do_load_test(), eap_radius_accounting_start_interim(), enable_disable_all(), enumerator_destroy(), expire_job(), export_csv(), find_entry(), get_route(), handle_ack(), handle_event(), handle_ita_message(), handle_offer(), init_supplementary_groups(), initiate_cb(), initiator_finish(), install_route(), lock_function(), locking_function(), lookup_queue(), manage_route(), METHOD(), mutex_run(), notify_end(), on_accept(), process_acquire(), process_job(), process_jobs(), process_request(), put_entry(), queue(), raise_events(), receive_events(), register_event(), register_load_tester(), release_unclaimed(), remove_entry(), remove_include(), remove_init_hash(), remove_interface(), remove_queue(), remove_trap(), reset_activity_led(), resolve_hosts(), restart(), retransmit(), roam_event(), sa_expired(), schedule(), send_interim(), send_once(), send_packets(), send_start(), send_status(), send_stop(), sender(), START_TEST(), subscribe(), subscribed(), thread_create(), thread_current(), thread_destroy(), token_event_cb(), uninstall_route(), unlock_single_segment(), UnlockMutex(), unregister_event(), update_interface(), update_usage(), vici_register(), vici_submit(), wait_result(), watch(), and watchdog().
The documentation for this struct was generated from the following file:
mutex.h