strongSwan: windows.c File Reference
windows.c File Reference
#include <utils/utils.h>
#include <errno.h>
Macros
#define _WIN32_WINNT 0x0600
Functions
void windows_init ()
void windows_deinit ()
int usleep (useconds_t usec)
char * strndup (const char *s, size_t n)
void * dlopen (const char *filename, int flag)
static void * dlsym_default (const char *name)
static void * dlsym_next (const char *name)
void * dlsym (void *handle, const char *symbol)
char * dlerror (void)
int dlclose (void *handle)
int socketpair (int domain, int type, int protocol, int sv[2])
char * getpass (const char *prompt)
int strerror_s_extended (char *buf, size_t buflen, int errnum)
static int wserr (int retval)
static bool check_dontwait (int *flags)
int windows_shutdown (int sockfd, int how)
int windows_accept (int sockfd, struct sockaddr *addr, socklen_t *addrlen)
int windows_bind (int sockfd, const struct sockaddr *addr, socklen_t addrlen)
int windows_connect (int sockfd, const struct sockaddr *addr, socklen_t addrlen)
int windows_getsockname (int sockfd, struct sockaddr *addr, socklen_t *addrlen)
int windows_getsockopt (int sockfd, int level, int optname, void *optval, socklen_t *optlen)
int windows_setsockopt (int sockfd, int level, int optname, const void *optval, socklen_t optlen)
int windows_socket (int domain, int type, int protocol)
int windows_select (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
int windows_close (int fd)
ssize_t windows_recv (int sockfd, void *buf, size_t len, int flags)
ssize_t windows_recvfrom (int sockfd, void *buf, size_t len, int flags, struct sockaddr *src_addr, socklen_t *addrlen)
ssize_t windows_send (int sockfd, const void *buf, size_t len, int flags)
ssize_t windows_sendto (int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *dest_addr, socklen_t addrlen)
ssize_t windows_read (int fd, void *buf, size_t count)
ssize_t windows_write (int fd, void *buf, size_t count)
int poll (struct pollfd *fds, int nfds, int timeout)
Macro Definition Documentation
#define _WIN32_WINNT 0x0600
Definition at line 17 of file windows.c.
Function Documentation
static bool check_dontwait (int * flags) static
Check and clear the dontwait flag
Definition at line 450 of file windows.c.
References FALSE, MSG_DONTWAIT, and TRUE.
Referenced by windows_recv(), windows_recvfrom(), windows_send(), and windows_sendto().
 {
     if (*flags & MSG_DONTWAIT)
     {
         *flags &= ~MSG_DONTWAIT;
         return TRUE;
     }
     return FALSE;
 }
static void* dlsym_default (const char * name) static
Load a symbol from known default libs (monolithic build)
Definition at line 81 of file windows.c.
References countof, and handle.
Referenced by dlsym().
 {
     const char *dlls[] = {
         "libstrongswan-0.dll",
         "libhydra-0.dll",
         "libcharon-0.dll",
         "libtnccs-0.dll",
         NULL /* .exe */
     };
     HANDLE handle;
     void *sym = NULL;
     int i;
     for (i = 0; i < countof(dlls); i++)
     {
         handle = GetModuleHandle(dlls[i]);
         if (handle)
         {
             sym = GetProcAddress(handle, name);
             if (sym)
             {
                 break;
             }
         }
     }
     return sym;
 }
static void* dlsym_next (const char * name) static
Emulate RTLD_NEXT for some known symbols
Definition at line 112 of file windows.c.
References countof, handle, and streq().
Referenced by dlsym().
 {
     struct {
         const char *dll;
         const char *syms[4];
     } dlls[] = {
         /* for leak detective */
         { "msvcrt",
             { "malloc", "calloc", "realloc", "free" }
         },
     };
     HANDLE handle = NULL;
     int i, j;
     for (i = 0; i < countof(dlls); i++)
     {
         for (j = 0; j < countof(dlls[0].syms); j++)
         {
             if (dlls[i].syms[j] && streq(dlls[i].syms[j], name))
             {
                 handle = GetModuleHandle(dlls[i].dll);
                 break;
             }
         }
     }
     if (handle)
     {
         return GetProcAddress(handle, name);
     }
     return handle;
 }
static int wserr (int retval) static
Set errno for a function setting WSA error on failure
Definition at line 380 of file windows.c.
References countof, DWORD, EADDRINUSE, EADDRNOTAVAIL, EAFNOSUPPORT, EALREADY, ECONNABORTED, ECONNREFUSED, ECONNRESET, EDESTADDRREQ, EHOSTUNREACH, EINPROGRESS, EISCONN, ELOOP, EMSGSIZE, ENETDOWN, ENETRESET, ENETUNREACH, ENOBUFS, ENOPROTOOPT, ENOTCONN, ENOTSOCK, ENOTSUP, EOPNOTSUPP, EPROTONOSUPPORT, EPROTOTYPE, ETIMEDOUT, and EWOULDBLOCK.
Referenced by poll(), windows_accept(), windows_bind(), windows_close(), windows_connect(), windows_getsockname(), windows_getsockopt(), windows_read(), windows_recv(), windows_recvfrom(), windows_select(), windows_send(), windows_sendto(), windows_setsockopt(), windows_shutdown(), windows_socket(), and windows_write().
 {
     if (retval < 0)
     {
         static const struct {
             DWORD wsa;
             int err;
         } map[] = {
             { WSANOTINITIALISED,            EBADF                       },
             { WSAENETDOWN,                  ENETDOWN                    },
             { WSAENETRESET,                 ENETRESET                   },
             { WSAECONNABORTED,              ECONNABORTED                },
             { WSAESHUTDOWN,                 ECONNABORTED                },
             { WSAEACCES,                    EACCES                      },
             { WSAEINTR,                     EINTR                       },
             { WSAEINPROGRESS,               EINPROGRESS                 },
             { WSAEFAULT,                    EFAULT                      },
             { WSAENOBUFS,                   ENOBUFS                     },
             { WSAENOTSOCK,                  ENOTSOCK                    },
             { WSAEOPNOTSUPP,                EOPNOTSUPP                  },
             { WSAEWOULDBLOCK,               EWOULDBLOCK                 },
             { WSAEMSGSIZE,                  EMSGSIZE                    },
             { WSAEINVAL,                    EINVAL                      },
             { WSAENOTCONN,                  ENOTCONN                    },
             { WSAEHOSTUNREACH,              EHOSTUNREACH                },
             { WSAENETUNREACH,               ENETUNREACH                 },
             { WSAECONNABORTED,              ECONNABORTED                },
             { WSAECONNRESET,                ECONNRESET                  },
             { WSAETIMEDOUT,                 ETIMEDOUT                   },
             { WSAEMFILE,                    EMFILE                      },
             { WSAEALREADY,                  EALREADY                    },
             { WSAEDESTADDRREQ,              EDESTADDRREQ                },
             { WSAEISCONN,                   EISCONN                     },
             { WSAEOPNOTSUPP,                EOPNOTSUPP                  },
             { WSAEPROTOTYPE,                EPROTOTYPE                  },
             { WSAENOPROTOOPT,               ENOPROTOOPT                 },
             { WSAEPROTONOSUPPORT,           EPROTONOSUPPORT             },
             { WSAEPFNOSUPPORT,              EPROTONOSUPPORT             },
             { WSAEAFNOSUPPORT,              EAFNOSUPPORT                },
             { WSAEADDRNOTAVAIL,             EADDRNOTAVAIL               },
             { WSAEADDRINUSE,                EADDRINUSE                  },
             { WSAETIMEDOUT,                 ETIMEDOUT                   },
             { WSAECONNREFUSED,              ECONNREFUSED                },
             { WSAELOOP,                     ELOOP                       },
             { WSAENAMETOOLONG,              ENAMETOOLONG                },
             { WSAENOTEMPTY,                 ENOTEMPTY                   },
             { WSAEPROTOTYPE,                EPROTOTYPE                  },
             { WSAVERNOTSUPPORTED,           ENOTSUP                     },
         };
         DWORD wsa, i;
         wsa = WSAGetLastError();
         for (i = 0; i < countof(map); i++)
         {
             if (map[i].wsa == wsa)
             {
                 errno = map[i].err;
                 return retval;
             }
         }
         errno = ENOENT;
         return retval;
     }
     errno = 0;
     return retval;
 }