strongSwan: pkcs7_encrypted_data
pkcs7_encrypted_data
pkcs7
Functions
pkcs7_t * pkcs7_encrypted_data_load (chunk_t encoding, chunk_t content)
Detailed Description
Function Documentation
pkcs7_t* pkcs7_encrypted_data_load (chunk_t encoding, chunk_t content)
Parse a PKCS#7 encrypted-data container.
Parameters
encoding full contentInfo encoding
content DER encoded content from contentInfo
Returns
CONTAINER_PKCS7_ENCRYPTED_DATA container, NULL on failure
See header.
Definition at line 204 of file pkcs7_encrypted_data.c.
References chunk_clone, create_empty(), destroy(), and parse().
Referenced by parse_contentInfo().
 {
     private_pkcs7_encrypted_data_t *this = create_empty();
     this->encoding = chunk_clone(encoding);
     if (!parse(this, content))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }