strongSwan: keyid.c File Reference
keyid.c File Reference
#include <errno.h>
#include "pki.h"
#include <credentials/certificates/certificate.h>
#include <credentials/certificates/x509.h>
Functions
static int keyid ()
static void __attribute__ ((constructor))
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 167 of file keyid.c.
References command_register(), and keyid().
 {
     command_register((command_t)
         { keyid, 'k', "keyid",
         "calculate key identifiers of a key/certificate",
         {"[--in file] [--type rsa-priv|ecdsa-priv|bliss-priv|pub|pkcs10|x509]"},
         {
             {"help",    'h', 0, "show usage information"},
             {"in",      'i', 1, "input file, default: stdin"},
             {"type",    't', 1, "type of key, default: rsa-priv"},
         }
     });
 }
static int keyid () static
Calculate the keyid of a key/certificate
Definition at line 26 of file keyid.c.
References BUILD_BLOB, BUILD_END, BUILD_FROM_FILE, cert, CERT_ASN1_DER, CERT_PKCS10_REQUEST, CERT_X509, chunk_from_fd(), command_getopt(), command_usage(), credential_factory_t::create, CRED_CERTIFICATE, CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, library_t::creds, certificate_t::destroy, fprintf, free(), certificate_t::get_public_key, id, KEY_ANY, KEY_BLISS, KEY_ECDSA, KEY_RSA, KEYID_PUBKEY_INFO_SHA1, KEYID_PUBKEY_SHA1, lib, printf, private, chunk_t::ptr, public, set_file_mode(), streq(), strerror, subtype, TRUE, and type.
Referenced by __attribute__(), acert(), add(), add_certreq(), add_device_id(), add_local_certs(), check_ocsp(), edit(), find_client_id(), find_smartcard_key(), generate(), get_private_by_cert(), has_privkey(), imv_attestation_process(), issue(), list(), list_public_key(), load_ca_cert(), load_pin(), METHOD(), openssl_rsa_private_key_connect(), parse_authKeyIdentifier_ext(), pkcs11_creds_load(), process_certreq(), pub(), self(), and sign_crl().
 {
     credential_type_t type = CRED_PRIVATE_KEY;
     int subtype = KEY_RSA;
     certificate_t *cert;
     private_key_t *private;
     public_key_t *public;
     char *file = NULL;
     void *cred;
     chunk_t id;
     char *arg;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 't':
                 if (streq(arg, "rsa-priv"))
                 {
                     type = CRED_PRIVATE_KEY;
                     subtype = KEY_RSA;
                 }
                 else if (streq(arg, "ecdsa-priv"))
                 {
                     type = CRED_PRIVATE_KEY;
                     subtype = KEY_ECDSA;
                 }
                 else if (streq(arg, "bliss-priv"))
                 {
                     type = CRED_PRIVATE_KEY;
                     subtype = KEY_BLISS;
                 }
                 else if (streq(arg, "pub"))
                 {
                     type = CRED_PUBLIC_KEY;
                     subtype = KEY_ANY;
                 }
                 else if (streq(arg, "pkcs10"))
                 {
                     type = CRED_CERTIFICATE;
                     subtype = CERT_PKCS10_REQUEST;
                 }
                 else if (streq(arg, "x509"))
                 {
                     type = CRED_CERTIFICATE;
                     subtype = CERT_X509;
                 }
                 else
                 {
                     return command_usage( "invalid input type");
                 }
                 continue;
             case 'i':
                 file = arg;
                 continue;
             case EOF:
                 break;
             default:
                 return command_usage("invalid --keyid option");
         }
         break;
     }
     if (file)
     {
         cred = lib->creds->create(lib->creds, type, subtype,
                                   BUILD_FROM_FILE, file, BUILD_END);
     }
     else
     {
         chunk_t chunk;
         set_file_mode(stdin, CERT_ASN1_DER);
         if (!chunk_from_fd(0, &chunk))
         {
             fprintf(stderr, "reading input failed: %s\n", strerror(errno));
             return 1;
         }
         cred = lib->creds->create(lib->creds, type, subtype,
                                   BUILD_BLOB, chunk, BUILD_END);
         free(chunk.ptr);
     }
     if (!cred)
     {
         fprintf(stderr, "parsing input failed\n");
         return 1;
     }
     if (type == CRED_PRIVATE_KEY)
     {
         private = cred;
         if (private->get_fingerprint(private, KEYID_PUBKEY_SHA1, &id))
         {
             printf("subjectKeyIdentifier:      %#B\n", &id);
         }
         if (private->get_fingerprint(private, KEYID_PUBKEY_INFO_SHA1, &id))
         {
             printf("subjectPublicKeyInfo hash: %#B\n", &id);
         }
         private->destroy(private);
     }
     else if (type == CRED_PUBLIC_KEY)
     {
         public = cred;
         if (public->get_fingerprint(public, KEYID_PUBKEY_SHA1, &id))
         {
             printf("subjectKeyIdentifier:      %#B\n", &id);
         }
         if (public->get_fingerprint(public, KEYID_PUBKEY_INFO_SHA1, &id))
         {
             printf("subjectPublicKeyInfo hash: %#B\n", &id);
         }
         public->destroy(public);
     }
     else
     {
         cert = cred;
         public = cert->get_public_key(cert);
         if (!public)
         {
             fprintf(stderr, "extracting public key from certificate failed");
             return 1;
         }
         if (public->get_fingerprint(public, KEYID_PUBKEY_SHA1, &id))
         {
             printf("subjectKeyIdentifier:      %#B\n", &id);
         }
         if (public->get_fingerprint(public, KEYID_PUBKEY_INFO_SHA1, &id))
         {
             printf("subjectPublicKeyInfo hash: %#B\n", &id);
         }
         public->destroy(public);
         cert->destroy(cert);
     }
     return 0;
 }