strongSwan: stream_service.c File Reference
stream_service.c File Reference
#include <library.h>
#include <threading/thread.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <processing/jobs/callback_job.h>
#include "stream_service.h"
#include <errno.h>
#include <unistd.h>
#include <sys/stat.h>
Classes
struct private_stream_service_t
struct async_data_t
Typedefs
typedef struct
private_stream_service_t private_stream_service_t
Functions
static void destroy_service (private_stream_service_t *this)
static bool watch (private_stream_service_t *this, int fd, watcher_event_t event)
static void destroy_async_data (async_data_t *data)
CALLBACK (reduce_running, void, async_data_t *data)
static job_requeue_t accept_async (async_data_t *data)
METHOD (stream_service_t, on_accept, void, private_stream_service_t *this, stream_service_cb_t cb, void *data, job_priority_t prio, u_int cncrncy)
METHOD (stream_service_t, destroy, void, private_stream_service_t *this)
stream_service_t * stream_service_create_from_fd (int fd)
Typedef Documentation
typedef struct private_stream_service_t private_stream_service_t
Definition at line 28 of file stream_service.c.
Function Documentation
static job_requeue_t accept_async (async_data_t * data) static
Async processing of accepted connection
Definition at line 168 of file stream_service.c.
References async_data_t::cb, async_data_t::data, stream_t::destroy, async_data_t::fd, JOB_REQUEUE_NONE, mutex_t::lock, mutex, stream_create_from_fd(), async_data_t::this, thread_cleanup_pop(), thread_cleanup_push(), TRUE, and mutex_t::unlock.
Referenced by watch().
 {
     private_stream_service_t *this = data->this;
     stream_t *stream;
     this->mutex->lock(this->mutex);
     if (this->terminated)
     {
         this->mutex->unlock(this->mutex);
         return JOB_REQUEUE_NONE;
     }
     this->running++;
     this->mutex->unlock(this->mutex);
     stream = stream_create_from_fd(data->fd);
     if (stream)
     {
         /* FD is now owned by stream, don't close it during cleanup */
         data->fd = -1;
         thread_cleanup_push(reduce_running, data);
         thread_cleanup_push((void*)stream->destroy, stream);
         thread_cleanup_pop(!data->cb(data->data, stream));
         thread_cleanup_pop(TRUE);
     }
     return JOB_REQUEUE_NONE;
 }
CALLBACK (reduce_running , void , async_data_t * data)
Reduce running counter
Definition at line 154 of file stream_service.c.
References condvar, mutex_t::lock, mutex, condvar_t::signal, async_data_t::this, and mutex_t::unlock.
 {
     private_stream_service_t *this = data->this;
     this->mutex->lock(this->mutex);
     this->running--;
     this->condvar->signal(this->condvar);
     this->mutex->unlock(this->mutex);
 }
static void destroy_async_data (async_data_t * data) static
Clean up accept data
Definition at line 129 of file stream_service.c.
References active, watcher_t::add, close, condvar, destroy_service(), async_data_t::fd, free(), lib, mutex_t::lock, mutex, condvar_t::signal, async_data_t::this, mutex_t::unlock, watch(), library_t::watcher, and WATCHER_READ.
Referenced by watch().
 {
     private_stream_service_t *this = data->this;
     this->mutex->lock(this->mutex);
     if (this->active-- == this->cncrncy && !this->terminated)
     {
         /* leaving concurrency limit, restart accept()ing. */
         lib->watcher->add(lib->watcher, this->fd,
                           WATCHER_READ, (watcher_cb_t)watch, this);
     }
     this->condvar->signal(this->condvar);
     this->mutex->unlock(this->mutex);
     destroy_service(this);
     if (data->fd != -1)
     {
         close(data->fd);
     }
     free(data);
 }
static void destroy_service (private_stream_service_t * this) static
Definition at line 96 of file stream_service.c.
References close, condvar, mutex_t::destroy, condvar_t::destroy, free(), mutex, and ref_put().
Referenced by destroy_async_data(), and METHOD().
 {
     if (ref_put(&this->ref))
     {
         close(this->fd);
         this->mutex->destroy(this->mutex);
         this->condvar->destroy(this->condvar);
         free(this);
     }
 }
METHOD (stream_service_t , on_accept , void , private_stream_service_t * this, stream_service_cb_t cb, void * data, job_priority_t prio, u_int cncrncy)
Definition at line 233 of file stream_service.c.
References active, watcher_t::add, cb(), condvar, data, JOB_PRIO_MAX, lib, mutex_t::lock, mutex, watcher_t::remove, mutex_t::unlock, condvar_t::wait, watch(), library_t::watcher, and WATCHER_READ.
 {
     this->mutex->lock(this->mutex);
     if (this->terminated)
     {
         this->mutex->unlock(this->mutex);
         return;
     }
     /* wait for all callbacks to return */
     while (this->active)
     {
         this->condvar->wait(this->condvar, this->mutex);
     }
     if (this->cb)
     {
         lib->watcher->remove(lib->watcher, this->fd);
     }
     this->cb = cb;
     this->data = data;
     if (prio <= JOB_PRIO_MAX)
     {
         this->prio = prio;
     }
     this->cncrncy = cncrncy;
     if (this->cb)
     {
         lib->watcher->add(lib->watcher, this->fd,
                           WATCHER_READ, (watcher_cb_t)watch, this);
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (stream_service_t , destroy , void , private_stream_service_t * this)
Definition at line 273 of file stream_service.c.
References condvar, destroy_service(), lib, mutex_t::lock, mutex, watcher_t::remove, TRUE, mutex_t::unlock, condvar_t::wait, and library_t::watcher.
 {
     this->mutex->lock(this->mutex);
     lib->watcher->remove(lib->watcher, this->fd);
     this->terminated = TRUE;
     while (this->running)
     {
         this->condvar->wait(this->condvar, this->mutex);
     }
     this->mutex->unlock(this->mutex);
     destroy_service(this);
 }
static bool watch (private_stream_service_t * this, int fd, watcher_event_t event) static
Forward declaration
Watcher callback function
Definition at line 198 of file stream_service.c.
References accept, accept_async(), active, callback_job_create_with_prio(), cb(), data, destroy_async_data(), FALSE, async_data_t::fd, free(), INIT, lib, mutex_t::lock, mutex, library_t::processor, processor_t::queue_job, ref_get(), return_false(), TRUE, and mutex_t::unlock.
Referenced by destroy_async_data(), and METHOD().
 {
     async_data_t *data;
     bool keep = TRUE;
     INIT(data,
         .cb = this->cb,
         .data = this->data,
         .fd = accept(fd, NULL, NULL),
         .this = this,
     );
     if (data->fd != -1 && !this->terminated)
     {
         this->mutex->lock(this->mutex);
         if (++this->active == this->cncrncy)
         {
             /* concurrency limit reached, stop accept()ing new connections */
             keep = FALSE;
         }
         this->mutex->unlock(this->mutex);
         ref_get(&this->ref);
         lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create_with_prio((void*)accept_async, data,
                 (void*)destroy_async_data, (callback_job_cancel_t)return_false,
                 this->prio));
     }
     else
     {
         free(data);
     }
     return keep;
 }