strongSwan: guest.h File Reference
guest.h File Reference
#include <library.h>
#include <collections/enumerator.h>
#include "iface.h"
Classes
struct guest_t
Typedefs
typedef enum guest_state_t guest_state_t
typedef struct guest_t guest_t
typedef pid_t(* invoke_function_t)(void *data, guest_t *guest, char *args[], int argc)
typedef void(* idle_function_t)(void)
Enumerations
enum guest_state_t {
GUEST_STOPPED, GUEST_STARTING, GUEST_RUNNING, GUEST_PAUSED,
GUEST_STOPPING
}
Functions
guest_t * guest_create (char *parent, char *name, char *kernel, char *master, char *args)
guest_t * guest_load (char *parent, char *name)
Variables
enum_name_t * guest_state_names
Typedef Documentation
typedef enum guest_state_t guest_state_t
Definition at line 23 of file guest.h.
typedef struct guest_t guest_t
Definition at line 24 of file guest.h.
typedef void(* idle_function_t)(void)
Idle function to pass to start().
Definition at line 68 of file guest.h.
typedef pid_t(* invoke_function_t)(void *data, guest_t *guest, char *args[], int argc)
Invoke function which lauches the UML guest.
Consoles are all set to NULL, you may change them by adding additional UML options to args before invocation.
Parameters
data callback data
guest guest to start
args args to use for guest invocation, args[0] is kernel
argc number of elements in args
idle
Returns
PID of child, 0 if failed
Definition at line 62 of file guest.h.
Enumeration Type Documentation
enum guest_state_t
State of a guest (started, stopped, ...)
Enumerator
GUEST_STOPPED
guest kernel not running at all
GUEST_STARTING
kernel started, but not yet available
GUEST_RUNNING
guest is up and running
GUEST_PAUSED
guest has been paused
GUEST_STOPPING
guest is stopping (shutting down)
Definition at line 31 of file guest.h.
                    {
     GUEST_STOPPED,
     GUEST_STARTING,
     GUEST_RUNNING,
     GUEST_PAUSED,
     GUEST_STOPPING,
 };
Function Documentation
guest_t* guest_create (char * parent, char * name, char * kernel, char * master, char * args)
Create a new, unstarted guest.
Parameters
parent parent directory to create the guest in
name name of the guest to create
kernel kernel this guest uses
master read-only master filesystem for guest
args additional args to pass to kernel
mem amount of memory to give the guest
create the guest instance, including required dirs and mounts
Definition at line 618 of file guest.c.
References DBG1, DBG_LIB, destroy(), DIFF_DIR, dir, guest_create_generic(), KERNEL_FILE, make_symlink(), MASTER_DIR, mount_unionfs(), PERME, saveargs(), TRUE, and UNION_DIR.
Referenced by METHOD().
 {
     private_guest_t *this = guest_create_generic(parent, name, TRUE);
     if (this == NULL)
     {
         return NULL;
     }
     if (!make_symlink(this, master, MASTER_DIR) ||
         !make_symlink(this, kernel, KERNEL_FILE))
     {
         DBG1(DBG_LIB, "creating master/kernel symlink failed: %m");
         destroy(this);
         return NULL;
     }
     if (mkdirat(this->dir, UNION_DIR, PERME) != 0 ||
         mkdirat(this->dir, DIFF_DIR, PERME) != 0)
     {
         DBG1(DBG_LIB, "unable to create directories for '%s': %m", name);
         destroy(this);
         return NULL;
     }
     this->args = args;
     if (args && !saveargs(this, args))
     {
         destroy(this);
         return NULL;
     }
     if (!mount_unionfs(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
guest_t* guest_load (char * parent, char * name)
Load a guest created with guest_create().
Parameters
parent parent directory to look for a guest
name name of the guest directory
load an already created guest
Definition at line 663 of file guest.c.
References destroy(), FALSE, guest_create_generic(), loadargs(), and mount_unionfs().
Referenced by load_guests().
 {
     private_guest_t *this = guest_create_generic(parent, name, FALSE);
     if (this == NULL)
     {
         return NULL;
     }
     this->args = loadargs(this);
     if (!mount_unionfs(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
Variable Documentation
enum_name_t* guest_state_names
string mappings for guest_state_t
Referenced by METHOD().