strongSwan: whitelist_plugin.c File Reference
whitelist_plugin.c File Reference
#include "whitelist_plugin.h"
#include "whitelist_listener.h"
#include "whitelist_control.h"
#include <daemon.h>
Classes
struct private_whitelist_plugin_t
Typedefs
typedef struct
private_whitelist_plugin_t private_whitelist_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_whitelist_plugin_t *this)
static bool plugin_cb (private_whitelist_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_whitelist_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_whitelist_plugin_t *this)
plugin_t * whitelist_plugin_create ()
Variables
struct private_whitelist_plugin_t __attribute__
Typedef Documentation
typedef struct private_whitelist_plugin_t private_whitelist_plugin_t
Definition at line 23 of file whitelist_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_whitelist_plugin_t * this)
Definition at line 46 of file whitelist_plugin.c.
 {
     return "whitelist";
 }
METHOD (plugin_t , get_features , int , private_whitelist_plugin_t * this, plugin_feature_t * features[])
Definition at line 69 of file whitelist_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "whitelist"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_whitelist_plugin_t * this)
Definition at line 80 of file whitelist_plugin.c.
References tkm_listener_t::destroy, DESTROY_IF, free(), and listener.
 {
     this->listener->destroy(this->listener);
     DESTROY_IF(this->control);
     free(this);
 }
static bool plugin_cb (private_whitelist_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 55 of file whitelist_plugin.c.
References bus_t::add_listener, daemon_t::bus, charon, bus_t::remove_listener, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
     }
     return TRUE;
 }
plugin_t* whitelist_plugin_create ()
Plugin constructor
Definition at line 91 of file whitelist_plugin.c.
References destroy(), INIT, listener, whitelist_control_create(), and whitelist_listener_create().
 {
     private_whitelist_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .listener = whitelist_listener_create(),
     );
     this->control = whitelist_control_create(this->listener);
     if (!this->control)
     {
         destroy(this);
         return NULL;
     }
     return &this->public.plugin;
 }
Variable Documentation
struct private_whitelist_plugin_t __attribute__