strongSwan: gcrypt_rsa_private_key.c File Reference
gcrypt_rsa_private_key.c File Reference
#include <gcrypt.h>
#include "gcrypt_rsa_private_key.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
Classes
struct private_gcrypt_rsa_private_key_t
Typedefs
typedef struct
private_gcrypt_rsa_private_key_t private_gcrypt_rsa_private_key_t
Functions
chunk_t gcrypt_rsa_find_token (gcry_sexp_t sexp, char *name, gcry_sexp_t key)
static bool sign_raw (private_gcrypt_rsa_private_key_t *this, chunk_t data, chunk_t *signature)
static bool sign_pkcs1 (private_gcrypt_rsa_private_key_t *this, hash_algorithm_t hash_algorithm, char *hash_name, chunk_t data, chunk_t *signature)
METHOD (private_key_t, get_type, key_type_t, private_gcrypt_rsa_private_key_t *this)
METHOD (private_key_t, sign, bool, private_gcrypt_rsa_private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *sig)
METHOD (private_key_t, decrypt, bool, private_gcrypt_rsa_private_key_t *this, encryption_scheme_t scheme, chunk_t encrypted, chunk_t *plain)
METHOD (private_key_t, get_keysize, int, private_gcrypt_rsa_private_key_t *this)
METHOD (private_key_t, get_public_key, public_key_t *, private_gcrypt_rsa_private_key_t *this)
METHOD (private_key_t, get_encoding, bool, private_gcrypt_rsa_private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (private_key_t, get_fingerprint, bool, private_gcrypt_rsa_private_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (private_key_t, get_ref, private_key_t *, private_gcrypt_rsa_private_key_t *this)
METHOD (private_key_t, destroy, void, private_gcrypt_rsa_private_key_t *this)
static
private_gcrypt_rsa_private_key_t * create_empty ()
gcrypt_rsa_private_key_t * gcrypt_rsa_private_key_gen (key_type_t type, va_list args)
gcrypt_rsa_private_key_t * gcrypt_rsa_private_key_load (key_type_t type, va_list args)
Typedef Documentation
typedef struct private_gcrypt_rsa_private_key_t private_gcrypt_rsa_private_key_t
Definition at line 25 of file gcrypt_rsa_private_key.c.
Function Documentation
static private_gcrypt_rsa_private_key_t* create_empty (void) static
Internal generic constructor
Definition at line 425 of file gcrypt_rsa_private_key.c.
References INIT, private_key_belongs_to(), private_key_equals(), and private_key_has_fingerprint().
Referenced by gcrypt_rsa_private_key_gen(), and gcrypt_rsa_private_key_load().
 {
     private_gcrypt_rsa_private_key_t *this;
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .sign = _sign,
                 .decrypt = _decrypt,
                 .get_keysize = _get_keysize,
                 .get_public_key = _get_public_key,
                 .equals = private_key_equals,
                 .belongs_to = private_key_belongs_to,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = private_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     return this;
 }
chunk_t gcrypt_rsa_find_token (gcry_sexp_t sexp, char * name, gcry_sexp_t key)
find a token in a S-expression. If a key is given, its length is used to pad the output to a given length.
Definition at line 52 of file gcrypt_rsa_private_key.c.
References chunk_alloc, chunk_clone, chunk_empty, chunk_skip(), data, chunk_t::len, len, memcpy, memset, and chunk_t::ptr.
Referenced by METHOD(), sign_pkcs1(), and sign_raw().
 {
     gcry_sexp_t token;
     chunk_t data = chunk_empty, tmp;
     size_t len = 0;
     token = gcry_sexp_find_token(sexp, name, 1);
     if (token)
     {
         data.ptr = (char*)gcry_sexp_nth_data(token, 1, &data.len);
         if (!data.ptr)
         {
             data.len = 0;
         }
         else
         {
             if (key)
             {
                 /* gcrypt might return more bytes than necessary. Truncate
                  * to key length if key given, or prepend zeros if needed  */
                 len = gcry_pk_get_nbits(key);
                 len = len / 8 + (len % 8 ? 1 : 0);
                 if (len > data.len)
                 {
                     tmp = chunk_alloc(len);
                     len -= data.len;
                     memset(tmp.ptr, 0, tmp.len - len);
                     memcpy(tmp.ptr + len, data.ptr, data.len);
                     data = tmp;
                 }
                 else if (len < data.len)
                 {
                     data = chunk_clone(chunk_skip(data, data.len - len));
                 }
                 else
                 {
                     data = chunk_clone(data);
                 }
             }
             else
             {
                 data = chunk_clone(data);
             }
         }
         gcry_sexp_release(token);
     }
     return data;
 }
METHOD (private_key_t , get_type , key_type_t , private_gcrypt_rsa_private_key_t * this)
Definition at line 195 of file gcrypt_rsa_private_key.c.
References KEY_RSA.
 {
     return KEY_RSA;
 }
METHOD (private_key_t , sign , bool , private_gcrypt_rsa_private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * sig)
Definition at line 201 of file gcrypt_rsa_private_key.c.
References DBG1, DBG_LIB, FALSE, HASH_MD5, HASH_SHA1, HASH_SHA224, HASH_SHA256, HASH_SHA384, HASH_SHA512, sign_pkcs1(), sign_raw(), SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, and signature_scheme_names.
 {
     switch (scheme)
     {
         case SIGN_RSA_EMSA_PKCS1_NULL:
             return sign_raw(this, data, sig);
         case SIGN_RSA_EMSA_PKCS1_SHA1:
             return sign_pkcs1(this, HASH_SHA1, "sha1", data, sig);
         case SIGN_RSA_EMSA_PKCS1_SHA224:
             return sign_pkcs1(this, HASH_SHA224, "sha224", data, sig);
         case SIGN_RSA_EMSA_PKCS1_SHA256:
             return sign_pkcs1(this, HASH_SHA256, "sha256", data, sig);
         case SIGN_RSA_EMSA_PKCS1_SHA384:
             return sign_pkcs1(this, HASH_SHA384, "sha384", data, sig);
         case SIGN_RSA_EMSA_PKCS1_SHA512:
             return sign_pkcs1(this, HASH_SHA512, "sha512", data, sig);
         case SIGN_RSA_EMSA_PKCS1_MD5:
             return sign_pkcs1(this, HASH_MD5, "md5", data, sig);
         default:
             DBG1(DBG_LIB, "signature scheme %N not supported in RSA",
                  signature_scheme_names, scheme);
             return FALSE;
     }
 }
METHOD (private_key_t , decrypt , bool , private_gcrypt_rsa_private_key_t * this, encryption_scheme_t scheme, chunk_t encrypted, chunk_t * plain)
Definition at line 228 of file gcrypt_rsa_private_key.c.
References chunk_clone, chunk_create(), DBG1, DBG_LIB, ENCRYPT_RSA_PKCS1, encryption_scheme_names, FALSE, in, key, chunk_t::len, out, chunk_t::ptr, and TRUE.
 {
     gcry_error_t err;
     gcry_sexp_t in, out;
     chunk_t padded;
     u_char *pos = NULL;;
     if (scheme != ENCRYPT_RSA_PKCS1)
     {
         DBG1(DBG_LIB, "encryption scheme %N not supported",
              encryption_scheme_names, scheme);
         return FALSE;
     }
     err = gcry_sexp_build(&in, NULL, "(enc-val(flags)(rsa(a %b)))",
                           encrypted.len, encrypted.ptr);
     if (err)
     {
         DBG1(DBG_LIB, "building decryption S-expression failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     err = gcry_pk_decrypt(&out, in, this->key);
     gcry_sexp_release(in);
     if (err)
     {
         DBG1(DBG_LIB, "decrypting pkcs1 data failed: %s", gpg_strerror(err));
         return FALSE;
     }
     padded.ptr = (u_char*)gcry_sexp_nth_data(out, 1, &padded.len);
     /* result is padded, but gcrypt strips leading zero:
      *  00 | 02 | RANDOM | 00 | DATA */
     if (padded.ptr && padded.len > 2 && padded.ptr[0] == 0x02)
     {
         pos = memchr(padded.ptr, 0x00, padded.len - 1);
         if (pos)
         {
             pos++;
             *plain = chunk_clone(chunk_create(
                                         pos, padded.len - (pos - padded.ptr)));
         }
     }
     gcry_sexp_release(out);
     if (!pos)
     {
         DBG1(DBG_LIB, "decrypted data has invalid pkcs1 padding");
         return FALSE;
     }
     return TRUE;
 }
METHOD (private_key_t , get_keysize , int , private_gcrypt_rsa_private_key_t * this)
Definition at line 280 of file gcrypt_rsa_private_key.c.
References key.
 {
     return gcry_pk_get_nbits(this->key);
 }
METHOD (private_key_t , get_public_key , public_key_t * , private_gcrypt_rsa_private_key_t * this)
Definition at line 286 of file gcrypt_rsa_private_key.c.
References BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_free(), credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, gcrypt_rsa_find_token(), key, KEY_RSA, lib, and n.
 {
     chunk_t n, e;
     public_key_t *public;
     n = gcrypt_rsa_find_token(this->key, "n", NULL);
     e = gcrypt_rsa_find_token(this->key, "e", NULL);
     public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                         BUILD_RSA_MODULUS, n, BUILD_RSA_PUB_EXP, e, BUILD_END);
     chunk_free(&n);
     chunk_free(&e);
     return public;
 }
METHOD (private_key_t , get_encoding , bool , private_gcrypt_rsa_private_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 303 of file gcrypt_rsa_private_key.c.
References chunk_clear(), chunk_empty, chunk_free(), cp, CRED_PART_END, CRED_PART_RSA_COEFF, CRED_PART_RSA_EXP1, CRED_PART_RSA_EXP2, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PRIME1, CRED_PART_RSA_PRIME2, CRED_PART_RSA_PRIV_EXP, CRED_PART_RSA_PUB_EXP, DBG1, DBG_LIB, cred_encoding_t::encode, library_t::encoding, FALSE, gcrypt_rsa_find_token(), key, chunk_t::len, lib, chunk_t::ptr, and q.
 {
     chunk_t cn, ce, cp, cq, cd, cu, cexp1 = chunk_empty, cexp2 = chunk_empty;
     gcry_mpi_t p = NULL, q = NULL, d = NULL, exp1, exp2;
     gcry_error_t err;
     bool success;
     /* p and q are swapped, gcrypt expects p < q */
     cp = gcrypt_rsa_find_token(this->key, "q", NULL);
     cq = gcrypt_rsa_find_token(this->key, "p", NULL);
     cd = gcrypt_rsa_find_token(this->key, "d", NULL);
     err = gcry_mpi_scan(&p, GCRYMPI_FMT_USG, cp.ptr, cp.len, NULL)
         | gcry_mpi_scan(&q, GCRYMPI_FMT_USG, cq.ptr, cq.len, NULL)
         | gcry_mpi_scan(&d, GCRYMPI_FMT_USG, cd.ptr, cd.len, NULL);
     if (err)
     {
         gcry_mpi_release(p);
         gcry_mpi_release(q);
         gcry_mpi_release(d);
         chunk_clear(&cp);
         chunk_clear(&cq);
         chunk_clear(&cd);
         DBG1(DBG_LIB, "scanning mpi for export failed: %s", gpg_strerror(err));
         return FALSE;
     }
     gcry_mpi_sub_ui(p, p, 1);
     exp1 = gcry_mpi_new(gcry_pk_get_nbits(this->key));
     gcry_mpi_mod(exp1, d, p);
     gcry_mpi_release(p);
     gcry_mpi_sub_ui(q, q, 1);
     exp2 = gcry_mpi_new(gcry_pk_get_nbits(this->key));
     gcry_mpi_mod(exp2, d, q);
     gcry_mpi_release(q);
     err = gcry_mpi_aprint(GCRYMPI_FMT_USG, &cexp1.ptr, &cexp1.len, exp1)
         | gcry_mpi_aprint(GCRYMPI_FMT_USG, &cexp2.ptr, &cexp2.len, exp2);
     gcry_mpi_release(d);
     gcry_mpi_release(exp1);
     gcry_mpi_release(exp2);
     if (err)
     {
         DBG1(DBG_LIB, "printing mpi for export failed: %s", gpg_strerror(err));
         chunk_clear(&cp);
         chunk_clear(&cq);
         chunk_clear(&cd);
         chunk_clear(&cexp1);
         chunk_clear(&cexp2);
         return FALSE;
     }
     cn = gcrypt_rsa_find_token(this->key, "n", NULL);
     ce = gcrypt_rsa_find_token(this->key, "e", NULL);
     cu = gcrypt_rsa_find_token(this->key, "u", NULL);
     success = lib->encoding->encode(lib->encoding, type, NULL, encoding,
                         CRED_PART_RSA_MODULUS, cn,
                         CRED_PART_RSA_PUB_EXP, ce, CRED_PART_RSA_PRIV_EXP, cd,
                         CRED_PART_RSA_PRIME1, cp, CRED_PART_RSA_PRIME2, cq,
                         CRED_PART_RSA_EXP1, cexp1, CRED_PART_RSA_EXP2, cexp2,
                         CRED_PART_RSA_COEFF, cu, CRED_PART_END);
     chunk_free(&cn);
     chunk_free(&ce);
     chunk_clear(&cd);
     chunk_clear(&cp);
     chunk_clear(&cq);
     chunk_clear(&cexp1);
     chunk_clear(&cexp2);
     chunk_clear(&cu);
     return success;
 }
METHOD (private_key_t , get_fingerprint , bool , private_gcrypt_rsa_private_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 382 of file gcrypt_rsa_private_key.c.
References chunk_free(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, cred_encoding_t::encode, library_t::encoding, gcrypt_rsa_find_token(), cred_encoding_t::get_cache, key, lib, n, and TRUE.
 {
     chunk_t n, e;
     bool success;
     if (lib->encoding->get_cache(lib->encoding, type, this, fp))
     {
         return TRUE;
     }
     n = gcrypt_rsa_find_token(this->key, "n", NULL);
     e = gcrypt_rsa_find_token(this->key, "e", NULL);
     success = lib->encoding->encode(lib->encoding,
                                 type, this, fp, CRED_PART_RSA_MODULUS, n,
                                 CRED_PART_RSA_PUB_EXP, e, CRED_PART_END);
     chunk_free(&n);
     chunk_free(&e);
     return success;
 }
METHOD (private_key_t , get_ref , private_key_t * , private_gcrypt_rsa_private_key_t * this)
Definition at line 404 of file gcrypt_rsa_private_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (private_key_t , destroy , void , private_gcrypt_rsa_private_key_t * this)
Definition at line 411 of file gcrypt_rsa_private_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), key, lib, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         gcry_sexp_release(this->key);
         lib->encoding->clear_cache(lib->encoding, this);
         free(this);
     }
 }
static bool sign_pkcs1 (private_gcrypt_rsa_private_key_t * this, hash_algorithm_t hash_algorithm, char * hash_name, chunk_t data, chunk_t * signature) static
Sign a chunk of data using hashing and PKCS#1 encoding
Definition at line 152 of file gcrypt_rsa_private_key.c.
References hasher_t::allocate_hash, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, gcrypt_rsa_find_token(), hash, hasher, hasher_algorithm_to_oid(), in, key, chunk_t::len, lib, OID_UNKNOWN, out, and chunk_t::ptr.
Referenced by METHOD().
 {
     hasher_t *hasher;
     chunk_t hash;
     gcry_error_t err;
     gcry_sexp_t in, out;
     int hash_oid;
     hash_oid = hasher_algorithm_to_oid(hash_algorithm);
     if (hash_oid == OID_UNKNOWN)
     {
         return FALSE;
     }
     hasher = lib->crypto->create_hasher(lib->crypto, hash_algorithm);
     if (!hasher || !hasher->allocate_hash(hasher, data, &hash))
     {
         DESTROY_IF(hasher);
         return FALSE;
     }
     hasher->destroy(hasher);
     err = gcry_sexp_build(&in, NULL, "(data(flags pkcs1)(hash %s %b))",
                           hash_name, hash.len, hash.ptr);
     chunk_free(&hash);
     if (err)
     {
         DBG1(DBG_LIB, "building signature S-expression failed: %s", gpg_strerror(err));
         return FALSE;
     }
     err = gcry_pk_sign(&out, in, this->key);
     gcry_sexp_release(in);
     if (err)
     {
         DBG1(DBG_LIB, "creating pkcs1 signature failed: %s", gpg_strerror(err));
         return FALSE;
     }
     *signature = gcrypt_rsa_find_token(out, "s", this->key);
     gcry_sexp_release(out);
     return !!signature->len;
 }
static bool sign_raw (private_gcrypt_rsa_private_key_t * this, chunk_t data, chunk_t * signature) static
Sign a chunk of data with direct PKCS#1 encoding, no hash OID
Definition at line 104 of file gcrypt_rsa_private_key.c.
References chunk_alloc, chunk_free(), DBG1, DBG_LIB, FALSE, gcrypt_rsa_find_token(), in, key, chunk_t::len, memcpy, memset, out, and chunk_t::ptr.
Referenced by METHOD().
 {
     gcry_sexp_t in, out;
     gcry_error_t err;
     chunk_t em;
     size_t k;
     /* EM = 0x00 || 0x01 || PS || 0x00 || T
      * PS = 0xFF padding, with length to fill em
      * T  = data
      */
     k = gcry_pk_get_nbits(this->key) / 8;
     if (data.len > k - 3)
     {
         return FALSE;
     }
     em = chunk_alloc(k);
     memset(em.ptr, 0xFF, em.len);
     em.ptr[0] = 0x00;
     em.ptr[1] = 0x01;
     em.ptr[em.len - data.len - 1] = 0x00;
     memcpy(em.ptr + em.len - data.len, data.ptr, data.len);
     err = gcry_sexp_build(&in, NULL, "(data(flags raw)(value %b))",
                           em.len, em.ptr);
     chunk_free(&em);
     if (err)
     {
         DBG1(DBG_LIB, "building signature S-expression failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     err = gcry_pk_sign(&out, in, this->key);
     gcry_sexp_release(in);
     if (err)
     {
         DBG1(DBG_LIB, "creating pkcs1 signature failed: %s", gpg_strerror(err));
         return FALSE;
     }
     *signature = gcrypt_rsa_find_token(out, "s", this->key);
     gcry_sexp_release(out);
     return !!signature->len;
 }