strongSwan: packet.c File Reference
packet.c File Reference
#include "packet.h"
Classes
struct private_packet_t
Typedefs
typedef struct private_packet_t private_packet_t
Functions
METHOD (packet_t, set_source, void, private_packet_t *this, host_t *source)
METHOD (packet_t, set_destination, void, private_packet_t *this, host_t *destination)
METHOD (packet_t, get_source, host_t *, private_packet_t *this)
METHOD (packet_t, get_destination, host_t *, private_packet_t *this)
METHOD (packet_t, get_data, chunk_t, private_packet_t *this)
METHOD (packet_t, set_data, void, private_packet_t *this, chunk_t data)
METHOD (packet_t, get_dscp, u_int8_t, private_packet_t *this)
METHOD (packet_t, set_dscp, void, private_packet_t *this, u_int8_t value)
METHOD (packet_t, skip_bytes, void, private_packet_t *this, size_t bytes)
METHOD (packet_t, destroy, void, private_packet_t *this)
METHOD (packet_t, clone_, packet_t *, private_packet_t *this)
packet_t * packet_create_from_data (host_t *src, host_t *dst, chunk_t data)
packet_t * packet_create ()
Typedef Documentation
typedef struct private_packet_t private_packet_t
Definition at line 20 of file packet.c.
Function Documentation
METHOD (packet_t , set_source , void , private_packet_t * this, host_t * source)
Definition at line 58 of file packet.c.
References DESTROY_IF, and source.
 {
     DESTROY_IF(this->source);
     this->source = source;
 }
METHOD (packet_t , set_destination , void , private_packet_t * this, host_t * destination)
Definition at line 65 of file packet.c.
References DESTROY_IF.
 {
     DESTROY_IF(this->destination);
     this->destination = destination;
 }
METHOD (packet_t , get_source , host_t * , private_packet_t * this)
Definition at line 72 of file packet.c.
References source.
 {
     return this->source;
 }
METHOD (packet_t , get_destination , host_t * , private_packet_t * this)
Definition at line 78 of file packet.c.
 {
     return this->destination;
 }
METHOD (packet_t , get_data , chunk_t , private_packet_t * this)
Definition at line 84 of file packet.c.
 {
     return this->adjusted_data;
 }
METHOD (packet_t , set_data , void , private_packet_t * this, chunk_t data)
Definition at line 90 of file packet.c.
References data, free(), and chunk_t::ptr.
 {
     free(this->data.ptr);
     this->adjusted_data = this->data = data;
 }
METHOD (packet_t , get_dscp , u_int8_t , private_packet_t * this)
Definition at line 97 of file packet.c.
 {
     return this->dscp;
 }
METHOD (packet_t , set_dscp , void , private_packet_t * this, u_int8_t value)
Definition at line 102 of file packet.c.
References value.
 {
     this->dscp = value;
 }
METHOD (packet_t , skip_bytes , void , private_packet_t * this, size_t bytes)
Definition at line 108 of file packet.c.
References chunk_skip().
 {
     this->adjusted_data = chunk_skip(this->adjusted_data, bytes);
 }
METHOD (packet_t , destroy , void , private_packet_t * this)
Definition at line 114 of file packet.c.
References data, DESTROY_IF, free(), and source.
 {
     DESTROY_IF(this->source);
     DESTROY_IF(this->destination);
     free(this->data.ptr);
     free(this);
 }
METHOD (packet_t , clone_ , packet_t * , private_packet_t * this)
Definition at line 123 of file packet.c.
References chunk_clone, packet_t::clone, data, packet_create(), packet_t::set_data, packet_t::set_destination, packet_t::set_dscp, packet_t::set_source, and source.
 {
     packet_t *other;
     other = packet_create();
     if (this->destination)
     {
         other->set_destination(other,
                                this->destination->clone(this->destination));
     }
     if (this->source)
     {
         other->set_source(other, this->source->clone(this->source));
     }
     if (this->data.ptr)
     {
         other->set_data(other, chunk_clone(this->adjusted_data));
     }
     other->set_dscp(other, this->dscp);
     return other;
 }