strongSwan: tests.c File Reference
libstrongswan/tests/tests.c File Reference
#include <test_runner.h>
#include "tests.h"
Macros
#define TEST_SUITE(x) test_suite_t* x();
#define TEST_SUITE_DEPEND(x,...) TEST_SUITE(x)
#define TEST_SUITE(x) { .suite = x, },
#define TEST_SUITE_DEPEND(x, type,...) { .suite = x, .feature = PLUGIN_DEPENDS(type, __VA_ARGS__) },
Functions
static bool test_runner_init (bool init)
int main (int argc, char *argv[])
Variables
static test_configuration_t tests []
Macro Definition Documentation
#define TEST_SUITE (x) test_suite_t* x();
Definition at line 19 of file libstrongswan/tests/tests.c.
#define TEST_SUITE (x) { .suite = x, },
Definition at line 19 of file libstrongswan/tests/tests.c.
#define TEST_SUITE_DEPEND (x, ...) TEST_SUITE(x)
Definition at line 20 of file libstrongswan/tests/tests.c.
#define TEST_SUITE_DEPEND (x, type, ...) { .suite = x, .feature = PLUGIN_DEPENDS(type, __VA_ARGS__) },
Definition at line 20 of file libstrongswan/tests/tests.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 60 of file libstrongswan/tests/tests.c.
References test_runner_init(), and test_runner_run().
 {
     return test_runner_run("libstrongswan", tests, test_runner_init);
 }
static bool test_runner_init (bool init) static
Definition at line 34 of file libstrongswan/tests/tests.c.
References processor_t::cancel, FALSE, settings_t::get_str, lib, plugin_loader_t::load, plugin_loader_add_plugindirs(), PLUGINS, library_t::plugins, library_t::processor, processor_t::set_threads, library_t::settings, TRUE, and plugin_loader_t::unload.
Referenced by main().
 {
     if (init)
     {
         char *plugins, *plugindir;
         plugins = getenv("TESTS_PLUGINS") ?:
                     lib->settings->get_str(lib->settings,
                                         "tests.load", PLUGINS);
         plugindir = lib->settings->get_str(lib->settings,
                                         "tests.plugindir", PLUGINDIR);
         plugin_loader_add_plugindirs(plugindir, plugins);
         if (!lib->plugins->load(lib->plugins, plugins))
         {
             return FALSE;
         }
     }
     else
     {
         lib->processor->set_threads(lib->processor, 0);
         lib->processor->cancel(lib->processor);
         lib->plugins->unload(lib->plugins);
     }
     return TRUE;
 }
Variable Documentation
test_configuration_t tests[] static
Definition at line 25 of file libstrongswan/tests/tests.c.