strongSwan: ha_attribute.c File Reference
ha_attribute.c File Reference
#include "ha_attribute.h"
#include <collections/linked_list.h>
#include <threading/mutex.h>
Classes
struct private_ha_attribute_t
struct pool_t
Typedefs
typedef struct
private_ha_attribute_t private_ha_attribute_t
Functions
static void pool_destroy (pool_t *pool)
static host_t * offset2host (pool_t *pool, int offset)
static int host2offset (pool_t *pool, host_t *addr)
static pool_t * get_pool (private_ha_attribute_t *this, char *name)
static bool responsible_for (private_ha_attribute_t *this, int bit)
METHOD (attribute_provider_t, acquire_address, host_t *, private_ha_attribute_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
METHOD (attribute_provider_t, release_address, bool, private_ha_attribute_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
METHOD (ha_attribute_t, reserve, void, private_ha_attribute_t *this, char *name, host_t *address)
METHOD (ha_attribute_t, destroy, void, private_ha_attribute_t *this)
static void load_pools (private_ha_attribute_t *this)
ha_attribute_t * ha_attribute_create (ha_kernel_t *kernel, ha_segments_t *segments)
Typedef Documentation
typedef struct private_ha_attribute_t private_ha_attribute_t
Definition at line 21 of file ha_attribute.c.
Function Documentation
static pool_t* get_pool (private_ha_attribute_t * this, char * name) static
Find a pool by its name
Definition at line 144 of file ha_attribute.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, pool_t::name, and streq().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     pool_t *pool, *found = NULL;
     enumerator = this->pools->create_enumerator(this->pools);
     while (enumerator->enumerate(enumerator, &pool))
     {
         if (streq(name, pool->name))
         {
             found = pool;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static int host2offset (pool_t * pool, host_t * addr) static
convert a host to a pool offset
Definition at line 111 of file ha_attribute.c.
References pool_t::base, base, chunk_skip(), host_t::get_address, host_t::get_family, host, memeq(), chunk_t::ptr, and pool_t::size.
Referenced by METHOD().
 {
     chunk_t host, base;
     u_int32_t hosti, basei;
     if (addr->get_family(addr) != pool->base->get_family(pool->base))
     {
         return -1;
     }
     host = addr->get_address(addr);
     base = pool->base->get_address(pool->base);
     if (addr->get_family(addr) == AF_INET6)
     {
         /* only look at last /32 block */
         if (!memeq(host.ptr, base.ptr, 12))
         {
             return -1;
         }
         host = chunk_skip(host, 12);
         base = chunk_skip(base, 12);
     }
     hosti = ntohl(*(u_int32_t*)(host.ptr));
     basei = ntohl(*(u_int32_t*)(base.ptr));
     if (hosti > basei + pool->size)
     {
         return -1;
     }
     return hosti - basei;
 }
static void load_pools (private_ha_attribute_t * this) static
Load the configured pools.
Definition at line 303 of file ha_attribute.c.
References pool_t::base, base, bits, settings_t::create_key_value_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, host_t::destroy, DESTROY_IF, enumerator_t::enumerate, free(), host_t::get_family, host_create_from_string(), INIT, lib, pool_t::mask, mask, name, pool_t::name, net, library_t::ns, library_t::settings, size, pool_t::size, and strdup.
Referenced by ha_attribute_create().
 {
     enumerator_t *enumerator;
     char *name, *net, *bits;
     host_t *base;
     int mask, maxbits;
     pool_t *pool;
     enumerator = lib->settings->create_key_value_enumerator(lib->settings,
                                                 "%s.plugins.ha.pools", lib->ns);
     while (enumerator->enumerate(enumerator, &name, &net))
     {
         net = strdup(net);
         bits = strchr(net, '/');
         if (!bits)
         {
             DBG1(DBG_CFG, "invalid HA pool '%s' subnet, skipped", name);
             free(net);
             continue;
         }
         *bits++ = '\0';
         base = host_create_from_string(net, 0);
         mask = atoi(bits);
         free(net);
         if (!base || !mask)
         {
             DESTROY_IF(base);
             DBG1(DBG_CFG, "invalid HA pool '%s', skipped", name);
             continue;
         }
         maxbits = base->get_family(base) == AF_INET ? 32 : 128;
         mask = maxbits - mask;
         if (mask > 24)
         {
             mask = 24;
             DBG1(DBG_CFG, "size of HA pool '%s' limited to /%d",
                  name, maxbits - mask);
         }
         if (mask < 3)
         {
             DBG1(DBG_CFG, "HA pool '%s' too small, skipped", name);
             base->destroy(base);
             continue;
         }
         INIT(pool,
             .name = strdup(name),
             .base = base,
             .size = (1 << mask),
         );
         pool->mask = calloc(pool->size / 8, 1);
         /* do not use first/last address of pool */
         pool->mask[0] |= 0x01;
         pool->mask[pool->size / 8 - 1] |= 0x80;
         DBG1(DBG_CFG, "loaded HA pool '%s' %H/%d (%d addresses)",
              pool->name, pool->base, maxbits - mask, pool->size - 2);
         this->pools->insert_last(this->pools, pool);
     }
     enumerator->destroy(enumerator);
 }
METHOD (attribute_provider_t , acquire_address , host_t * , private_ha_attribute_t * this, linked_list_t * pools, ike_sa_t * ike_sa, host_t * requested)
Definition at line 172 of file ha_attribute.c.
References pool_t::base, linked_list_t::create_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, host_t::get_family, get_pool(), mutex_t::lock, pool_t::mask, mutex, name, offset, offset2host(), responsible_for(), pool_t::size, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     pool_t *pool = NULL;
     int offset = -1, byte, bit;
     host_t *address;
     char *name;
     enumerator = pools->create_enumerator(pools);
     this->mutex->lock(this->mutex);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = get_pool(this, name);
         if (!pool)
         {
             continue;
         }
         if (pool->base->get_family(pool->base) !=
             requested->get_family(requested))
         {
             continue;
         }
         for (byte = 0; byte < pool->size / 8; byte++)
         {
             if (pool->mask[byte] != 0xFF)
             {
                 for (bit = 0; bit < 8; bit++)
                 {
                     if (!(pool->mask[byte] & 1 << bit) &&
                         responsible_for(this, bit))
                     {
                         offset = byte * 8 + bit;
                         pool->mask[byte] |= 1 << bit;
                         break;
                     }
                 }
             }
             if (offset != -1)
             {
                 break;
             }
         }
         if (offset == -1)
         {
             DBG1(DBG_CFG, "no address left in HA pool '%s' belonging to"
                  "a responsible segment", name);
         }
     }
     this->mutex->unlock(this->mutex);
     enumerator->destroy(enumerator);
     if (offset != -1)
     {
         address = offset2host(pool, offset);
         DBG1(DBG_CFG, "acquired address %H from HA pool '%s'", address, name);
         return address;
     }
     return NULL;
 }
METHOD (attribute_provider_t , release_address , bool , private_ha_attribute_t * this, linked_list_t * pools, host_t * address, ike_sa_t * ike_sa)
Definition at line 234 of file ha_attribute.c.
References pool_t::base, linked_list_t::create_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, host_t::get_family, get_pool(), host2offset(), mutex_t::lock, pool_t::mask, mutex, name, offset, size, TRUE, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     pool_t *pool;
     int offset;
     char *name;
     bool found = FALSE;
     enumerator = pools->create_enumerator(pools);
     this->mutex->lock(this->mutex);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = get_pool(this, name);
         if (!pool)
         {
             continue;
         }
         if (pool->base->get_family(pool->base) != address->get_family(address))
         {
             continue;
         }
         offset = host2offset(pool, address);
         if (offset > 0 && offset < pool->size)
         {
             pool->mask[offset / 8] &= ~(1 << (offset % 8));
             DBG1(DBG_CFG, "released address %H to HA pool '%s'", address, name);
             found = TRUE;
             break;
         }
     }
     this->mutex->unlock(this->mutex);
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (ha_attribute_t , reserve , void , private_ha_attribute_t * this, char * name, host_t * address)
Definition at line 272 of file ha_attribute.c.
References DBG1, DBG_CFG, get_pool(), host2offset(), mutex_t::lock, pool_t::mask, mutex, offset, size, and mutex_t::unlock.
 {
     pool_t *pool;
     int offset;
     this->mutex->lock(this->mutex);
     pool = get_pool(this, name);
     if (pool)
     {
         offset = host2offset(pool, address);
         if (offset > 0 && offset < pool->size)
         {
             pool->mask[offset / 8] |= 1 << (offset % 8);
             DBG1(DBG_CFG, "reserved address %H in HA pool '%s'", address, name);
         }
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (ha_attribute_t , destroy , void , private_ha_attribute_t * this)
Definition at line 292 of file ha_attribute.c.
References mutex_t::destroy, free(), mutex, and pool_destroy().
 {
     this->pools->destroy_function(this->pools, (void*)pool_destroy);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static host_t* offset2host (pool_t * pool, int offset) static
convert a pool offset to an address
Definition at line 82 of file ha_attribute.c.
References addr, pool_t::base, chunk_clone, free(), host_t::get_address, host_t::get_family, host, host_create_from_chunk(), chunk_t::ptr, and pool_t::size.
Referenced by METHOD().
 {
     chunk_t addr;
     host_t *host;
     u_int32_t *pos;
     if (offset > pool->size)
     {
         return NULL;
     }
     addr = chunk_clone(pool->base->get_address(pool->base));
     if (pool->base->get_family(pool->base) == AF_INET6)
     {
         pos = (u_int32_t*)(addr.ptr + 12);
     }
     else
     {
         pos = (u_int32_t*)addr.ptr;
     }
     *pos = htonl(offset + ntohl(*pos));
     host = host_create_from_chunk(pool->base->get_family(pool->base), addr, 0);
     free(addr.ptr);
     return host;
 }
static void pool_destroy (pool_t * pool) static
Clean up a pool entry
Definition at line 71 of file ha_attribute.c.
References pool_t::base, host_t::destroy, free(), pool_t::mask, and pool_t::name.
Referenced by METHOD().
 {
     pool->base->destroy(pool->base);
     free(pool->name);
     free(pool->mask);
     free(pool);
 }
static bool responsible_for (private_ha_attribute_t * this, int bit) static
Check if we are responsible for a bit in our bitmask
Definition at line 164 of file ha_attribute.c.
References segment.
Referenced by METHOD().
 {
     u_int segment;
     segment = this->kernel->get_segment_int(this->kernel, bit);
     return this->segments->is_active(this->segments, segment);
 }