strongSwan: openssl_crypter
openssl_crypter
openssl
Classes
struct openssl_crypter_t
Typedefs
typedef struct openssl_crypter_t openssl_crypter_t
Functions
openssl_crypter_t * openssl_crypter_create (encryption_algorithm_t algo, size_t key_size)
Detailed Description
Typedef Documentation
typedef struct openssl_crypter_t openssl_crypter_t
Definition at line 24 of file openssl_crypter.h.
Function Documentation
openssl_crypter_t* openssl_crypter_create (encryption_algorithm_t algo, size_t key_size)
Constructor to create openssl_crypter_t.
Parameters
algo algorithm to implement
key_size key size in bytes
Returns
openssl_crypter_t, NULL if not supported
Definition at line 164 of file openssl_crypter.c.
References chunk_alloc, ENCR_AES_CBC, ENCR_CAMELLIA_CBC, ENCR_DES_ECB, ENCR_NULL, free(), INIT, key, lookup_algorithm(), and name.
Referenced by METHOD().
 {
     private_openssl_crypter_t *this;
     INIT(this,
         .public = {
             .crypter = {
                 .encrypt = _encrypt,
                 .decrypt = _decrypt,
                 .get_block_size = _get_block_size,
                 .get_iv_size = _get_iv_size,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
     );
     switch (algo)
     {
         case ENCR_NULL:
             this->cipher = EVP_enc_null();
             key_size = 0;
             break;
         case ENCR_AES_CBC:
             switch (key_size)
             {
                 case 0:
                     key_size = 16;
                     /* FALL */
                 case 16:        /* AES 128 */
                     this->cipher = EVP_get_cipherbyname("aes128");
                     break;
                 case 24:        /* AES-192 */
                     this->cipher = EVP_get_cipherbyname("aes192");
                     break;
                 case 32:        /* AES-256 */
                     this->cipher = EVP_get_cipherbyname("aes256");
                     break;
                 default:
                     free(this);
                     return NULL;
             }
             break;
         case ENCR_CAMELLIA_CBC:
             switch (key_size)
             {
                 case 0:
                     key_size = 16;
                     /* FALL */
                 case 16:        /* CAMELLIA 128 */
                     this->cipher = EVP_get_cipherbyname("camellia128");
                     break;
                 case 24:        /* CAMELLIA 192 */
                     this->cipher = EVP_get_cipherbyname("camellia192");
                     break;
                 case 32:        /* CAMELLIA 256 */
                     this->cipher = EVP_get_cipherbyname("camellia256");
                     break;
                 default:
                     free(this);
                     return NULL;
             }
             break;
 #ifndef OPENSSL_NO_DES
         case ENCR_DES_ECB:
             key_size = 8;
             this->cipher = EVP_des_ecb();
             break;
 #endif
         default:
         {
             char* name;
             name = lookup_algorithm(algo, &key_size);
             if (!name)
             {
                 /* algo unavailable or key_size invalid */
                 free(this);
                 return NULL;
             }
             this->cipher = EVP_get_cipherbyname(name);
             break;
         }
     }
     if (!this->cipher)
     {
         /* OpenSSL does not support the requested algo */
         free(this);
         return NULL;
     }
     this->key = chunk_alloc(key_size);
     return &this->public;
 }