strongSwan: tcg_attr
tcg_attr
libimcv
Modules
tcg_pts_attr_aik
tcg_pts_attr_dh_nonce_finish
tcg_pts_attr_dh_nonce_params_req
tcg_pts_attr_dh_nonce_params_resp
tcg_pts_attr_file_meas
tcg_pts_attr_gen_attest_evid
tcg_pts_attr_get_aik
tcg_pts_attr_get_tpm_version_info
tcg_pts_attr_meas_algo
tcg_pts_attr_proto_caps
tcg_pts_attr_req_file_meas
tcg_pts_attr_req_file_meta
tcg_pts_attr_req_func_comp_evid
tcg_pts_attr_simple_comp_evid
tcg_pts_attr_simple_evid_final
tcg_pts_attr_tpm_version_info
tcg_pts_attr_unix_file_meta
tcg_seg_attr_max_size
tcg_seg_attr_next_seg
tcg_seg_attr_seg_env
tcg_swid_attr_req
tcg_swid_attr_tag_id_inv
tcg_swid_attr_tag_inv
Typedefs
typedef enum tcg_attr_t tcg_attr_t
Enumerations
enum tcg_attr_t {
TCG_SCAP_REFERENCES = 0x00000001, TCG_SCAP_CAPS_AND_INVENTORY = 0x00000002, TCG_SCAP_CONTENT = 0x00000003, TCG_SCAP_ASSESSMENT = 0x00000004,
TCG_SCAP_RESULTS = 0x00000005, TCG_SCAP_SUMMARY_RESULTS = 0x00000006, TCG_SWID_REQUEST = 0x00000011, TCG_SWID_TAG_ID_INVENTORY = 0x00000012,
TCG_SWID_TAG_ID_EVENTS = 0x00000013, TCG_SWID_TAG_INVENTORY = 0x00000014, TCG_SWID_TAG_EVENTS = 0x00000015, TCG_SWID_SUBSCRIPTION_STATUS_REQ = 0x00000016,
TCG_SWID_SUBSCRIPTION_STATUS_RESP = 0x00000017, TCG_SEG_MAX_ATTR_SIZE_REQ = 0x00000021, TCG_SEG_MAX_ATTR_SIZE_RESP = 0x00000022, TCG_SEG_ATTR_SEG_ENV = 0x00000023,
TCG_SEG_NEXT_SEG_REQ = 0x00000024, TCG_SEG_CANCEL_SEG_EXCH = 0x00000025, TCG_PTS_REQ_PROTO_CAPS = 0x01000000, TCG_PTS_PROTO_CAPS = 0x02000000,
TCG_PTS_DH_NONCE_PARAMS_REQ = 0x03000000, TCG_PTS_DH_NONCE_PARAMS_RESP = 0x04000000, TCG_PTS_DH_NONCE_FINISH = 0x05000000, TCG_PTS_MEAS_ALGO = 0x06000000,
TCG_PTS_MEAS_ALGO_SELECTION = 0x07000000, TCG_PTS_GET_TPM_VERSION_INFO = 0x08000000, TCG_PTS_TPM_VERSION_INFO = 0x09000000, TCG_PTS_REQ_TEMPL_REF_MANI_SET_META = 0x0A000000,
TCG_PTS_TEMPL_REF_MANI_SET_META = 0x0B000000, TCG_PTS_UPDATE_TEMPL_REF_MANI = 0x0C000000, TCG_PTS_GET_AIK = 0x0D000000, TCG_PTS_AIK = 0x0E000000,
TCG_PTS_REQ_FUNC_COMP_EVID = 0x00100000, TCG_PTS_GEN_ATTEST_EVID = 0x00200000, TCG_PTS_SIMPLE_COMP_EVID = 0x00300000, TCG_PTS_SIMPLE_EVID_FINAL = 0x00400000,
TCG_PTS_VERIFICATION_RESULT = 0x00500000, TCG_PTS_INTEG_REPORT = 0x00600000, TCG_PTS_REQ_FILE_META = 0x00700000, TCG_PTS_WIN_FILE_META = 0x00800000,
TCG_PTS_UNIX_FILE_META = 0x00900000, TCG_PTS_REQ_REGISTRY_VALUE = 0x00A00000, TCG_PTS_REGISTRY_VALUE = 0x00B00000, TCG_PTS_REQ_FILE_MEAS = 0x00C00000,
TCG_PTS_FILE_MEAS = 0x00D00000, TCG_PTS_REQ_INTEG_MEAS_LOG = 0x00E00000, TCG_PTS_INTEG_MEAS_LOG = 0x00F00000
}
Functions
pa_tnc_attr_t * tcg_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Variables
enum_name_t * tcg_attr_names
Detailed Description
Typedef Documentation
typedef enum tcg_attr_t tcg_attr_t
Definition at line 27 of file tcg_attr.h.
Enumeration Type Documentation
enum tcg_attr_t
TCG PTS IF-M Attributes (section 4 of PTS PROTO: Binding to TNC IF-M)
Enumerator
TCG_SCAP_REFERENCES
TCG_SCAP_CAPS_AND_INVENTORY
TCG_SCAP_CONTENT
TCG_SCAP_ASSESSMENT
TCG_SCAP_RESULTS
TCG_SCAP_SUMMARY_RESULTS
TCG_SWID_REQUEST
TCG_SWID_TAG_ID_INVENTORY
TCG_SWID_TAG_ID_EVENTS
TCG_SWID_TAG_INVENTORY
TCG_SWID_TAG_EVENTS
TCG_SWID_SUBSCRIPTION_STATUS_REQ
TCG_SWID_SUBSCRIPTION_STATUS_RESP
TCG_SEG_MAX_ATTR_SIZE_REQ
TCG_SEG_MAX_ATTR_SIZE_RESP
TCG_SEG_ATTR_SEG_ENV
TCG_SEG_NEXT_SEG_REQ
TCG_SEG_CANCEL_SEG_EXCH
TCG_PTS_REQ_PROTO_CAPS
TCG_PTS_PROTO_CAPS
TCG_PTS_DH_NONCE_PARAMS_REQ
TCG_PTS_DH_NONCE_PARAMS_RESP
TCG_PTS_DH_NONCE_FINISH
TCG_PTS_MEAS_ALGO
TCG_PTS_MEAS_ALGO_SELECTION
TCG_PTS_GET_TPM_VERSION_INFO
TCG_PTS_TPM_VERSION_INFO
TCG_PTS_REQ_TEMPL_REF_MANI_SET_META
TCG_PTS_TEMPL_REF_MANI_SET_META
TCG_PTS_UPDATE_TEMPL_REF_MANI
TCG_PTS_GET_AIK
TCG_PTS_AIK
TCG_PTS_REQ_FUNC_COMP_EVID
TCG_PTS_GEN_ATTEST_EVID
TCG_PTS_SIMPLE_COMP_EVID
TCG_PTS_SIMPLE_EVID_FINAL
TCG_PTS_VERIFICATION_RESULT
TCG_PTS_INTEG_REPORT
TCG_PTS_REQ_FILE_META
TCG_PTS_WIN_FILE_META
TCG_PTS_UNIX_FILE_META
TCG_PTS_REQ_REGISTRY_VALUE
TCG_PTS_REGISTRY_VALUE
TCG_PTS_REQ_FILE_MEAS
TCG_PTS_FILE_MEAS
TCG_PTS_REQ_INTEG_MEAS_LOG
TCG_PTS_INTEG_MEAS_LOG
Definition at line 32 of file tcg_attr.h.
                 {
     /* SCAP Attributes */
     TCG_SCAP_REFERENCES =                 0x00000001,
     TCG_SCAP_CAPS_AND_INVENTORY =         0x00000002,
     TCG_SCAP_CONTENT =                    0x00000003,
     TCG_SCAP_ASSESSMENT =                 0x00000004,
     TCG_SCAP_RESULTS =                    0x00000005,
     TCG_SCAP_SUMMARY_RESULTS =            0x00000006,
     /* SWID Attributes */
     TCG_SWID_REQUEST =                    0x00000011,
     TCG_SWID_TAG_ID_INVENTORY =           0x00000012,
     TCG_SWID_TAG_ID_EVENTS =              0x00000013,
     TCG_SWID_TAG_INVENTORY =              0x00000014,
     TCG_SWID_TAG_EVENTS =                 0x00000015,
     TCG_SWID_SUBSCRIPTION_STATUS_REQ =    0x00000016,
     TCG_SWID_SUBSCRIPTION_STATUS_RESP =   0x00000017,
     /* IF-M Attribute Segmentation */
     TCG_SEG_MAX_ATTR_SIZE_REQ =           0x00000021,
     TCG_SEG_MAX_ATTR_SIZE_RESP =          0x00000022,
     TCG_SEG_ATTR_SEG_ENV =                0x00000023,
     TCG_SEG_NEXT_SEG_REQ =                0x00000024,
     TCG_SEG_CANCEL_SEG_EXCH =             0x00000025,
     /* PTS Protocol Negotiations */
     TCG_PTS_REQ_PROTO_CAPS =              0x01000000,
     TCG_PTS_PROTO_CAPS =                  0x02000000,
     TCG_PTS_DH_NONCE_PARAMS_REQ =         0x03000000,
     TCG_PTS_DH_NONCE_PARAMS_RESP =        0x04000000,
     TCG_PTS_DH_NONCE_FINISH =             0x05000000,
     TCG_PTS_MEAS_ALGO =                   0x06000000,
     TCG_PTS_MEAS_ALGO_SELECTION =         0x07000000,
     TCG_PTS_GET_TPM_VERSION_INFO =        0x08000000,
     TCG_PTS_TPM_VERSION_INFO =            0x09000000,
     TCG_PTS_REQ_TEMPL_REF_MANI_SET_META = 0x0A000000,
     TCG_PTS_TEMPL_REF_MANI_SET_META =     0x0B000000,
     TCG_PTS_UPDATE_TEMPL_REF_MANI =       0x0C000000,
     TCG_PTS_GET_AIK =                     0x0D000000,
     TCG_PTS_AIK =                         0x0E000000,
     /* PTS-based Attestation Evidence */
     TCG_PTS_REQ_FUNC_COMP_EVID =          0x00100000,
     TCG_PTS_GEN_ATTEST_EVID =             0x00200000,
     TCG_PTS_SIMPLE_COMP_EVID =            0x00300000,
     TCG_PTS_SIMPLE_EVID_FINAL =           0x00400000,
     TCG_PTS_VERIFICATION_RESULT =         0x00500000,
     TCG_PTS_INTEG_REPORT =                0x00600000,
     TCG_PTS_REQ_FILE_META =               0x00700000,
     TCG_PTS_WIN_FILE_META =               0x00800000,
     TCG_PTS_UNIX_FILE_META =              0x00900000,
     TCG_PTS_REQ_REGISTRY_VALUE =          0x00A00000,
     TCG_PTS_REGISTRY_VALUE =              0x00B00000,
     TCG_PTS_REQ_FILE_MEAS =               0x00C00000,
     TCG_PTS_FILE_MEAS =                   0x00D00000,
     TCG_PTS_REQ_INTEG_MEAS_LOG =          0x00E00000,
     TCG_PTS_INTEG_MEAS_LOG =              0x00F00000,
 };
Function Documentation
pa_tnc_attr_t* tcg_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Create a TCG PA-TNC attribute from data
Parameters
type attribute type
length attribute length
value attribute value or segment
See header
Definition at line 188 of file tcg_attr.c.
References FALSE, TCG_PTS_AIK, tcg_pts_attr_aik_create_from_data(), tcg_pts_attr_dh_nonce_finish_create_from_data(), tcg_pts_attr_dh_nonce_params_req_create_from_data(), tcg_pts_attr_dh_nonce_params_resp_create_from_data(), tcg_pts_attr_file_meas_create_from_data(), tcg_pts_attr_gen_attest_evid_create_from_data(), tcg_pts_attr_get_aik_create_from_data(), tcg_pts_attr_get_tpm_version_info_create_from_data(), tcg_pts_attr_meas_algo_create_from_data(), tcg_pts_attr_proto_caps_create_from_data(), tcg_pts_attr_req_file_meas_create_from_data(), tcg_pts_attr_req_file_meta_create_from_data(), tcg_pts_attr_req_func_comp_evid_create_from_data(), tcg_pts_attr_simple_comp_evid_create_from_data(), tcg_pts_attr_simple_evid_final_create_from_data(), tcg_pts_attr_tpm_version_info_create_from_data(), tcg_pts_attr_unix_file_meta_create_from_data(), TCG_PTS_DH_NONCE_FINISH, TCG_PTS_DH_NONCE_PARAMS_REQ, TCG_PTS_DH_NONCE_PARAMS_RESP, TCG_PTS_FILE_MEAS, TCG_PTS_GEN_ATTEST_EVID, TCG_PTS_GET_AIK, TCG_PTS_GET_TPM_VERSION_INFO, TCG_PTS_INTEG_MEAS_LOG, TCG_PTS_INTEG_REPORT, TCG_PTS_MEAS_ALGO, TCG_PTS_MEAS_ALGO_SELECTION, TCG_PTS_PROTO_CAPS, TCG_PTS_REGISTRY_VALUE, TCG_PTS_REQ_FILE_MEAS, TCG_PTS_REQ_FILE_META, TCG_PTS_REQ_FUNC_COMP_EVID, TCG_PTS_REQ_INTEG_MEAS_LOG, TCG_PTS_REQ_PROTO_CAPS, TCG_PTS_REQ_REGISTRY_VALUE, TCG_PTS_REQ_TEMPL_REF_MANI_SET_META, TCG_PTS_SIMPLE_COMP_EVID, TCG_PTS_SIMPLE_EVID_FINAL, TCG_PTS_TEMPL_REF_MANI_SET_META, TCG_PTS_TPM_VERSION_INFO, TCG_PTS_UNIX_FILE_META, TCG_PTS_UPDATE_TEMPL_REF_MANI, TCG_PTS_VERIFICATION_RESULT, TCG_PTS_WIN_FILE_META, tcg_seg_attr_max_size_create_from_data(), tcg_seg_attr_next_seg_create_from_data(), TCG_SEG_ATTR_SEG_ENV, tcg_seg_attr_seg_env_create_from_data(), TCG_SEG_MAX_ATTR_SIZE_REQ, TCG_SEG_MAX_ATTR_SIZE_RESP, TCG_SEG_NEXT_SEG_REQ, tcg_swid_attr_req_create_from_data(), tcg_swid_attr_tag_id_inv_create_from_data(), tcg_swid_attr_tag_inv_create_from_data(), TCG_SWID_REQUEST, TCG_SWID_SUBSCRIPTION_STATUS_REQ, TCG_SWID_SUBSCRIPTION_STATUS_RESP, TCG_SWID_TAG_EVENTS, TCG_SWID_TAG_ID_EVENTS, TCG_SWID_TAG_ID_INVENTORY, TCG_SWID_TAG_INVENTORY, and TRUE.
Referenced by libimcv_init().
 {
     switch (type)
     {
         case TCG_SWID_REQUEST:
             return tcg_swid_attr_req_create_from_data(length, value);
         case TCG_SWID_TAG_ID_INVENTORY:
             return tcg_swid_attr_tag_id_inv_create_from_data(length, value);
         case TCG_SWID_TAG_INVENTORY:
             return tcg_swid_attr_tag_inv_create_from_data(length, value);
         case TCG_SEG_MAX_ATTR_SIZE_REQ:
             return tcg_seg_attr_max_size_create_from_data(length, value, TRUE);
         case TCG_SEG_MAX_ATTR_SIZE_RESP:
             return tcg_seg_attr_max_size_create_from_data(length, value, FALSE);
         case TCG_SEG_ATTR_SEG_ENV:
             return tcg_seg_attr_seg_env_create_from_data(length, value);
         case TCG_SEG_NEXT_SEG_REQ:
             return tcg_seg_attr_next_seg_create_from_data(length, value);
         case TCG_PTS_REQ_PROTO_CAPS:
             return tcg_pts_attr_proto_caps_create_from_data(length, value,
                                                             TRUE);
         case TCG_PTS_PROTO_CAPS:
             return tcg_pts_attr_proto_caps_create_from_data(length, value,
                                                             FALSE);
         case TCG_PTS_DH_NONCE_PARAMS_REQ:
             return tcg_pts_attr_dh_nonce_params_req_create_from_data(length,
                                                                      value);
         case TCG_PTS_DH_NONCE_PARAMS_RESP:
             return tcg_pts_attr_dh_nonce_params_resp_create_from_data(length,
                                                                       value);
         case TCG_PTS_DH_NONCE_FINISH:
             return tcg_pts_attr_dh_nonce_finish_create_from_data(length, value);
         case TCG_PTS_MEAS_ALGO:
             return tcg_pts_attr_meas_algo_create_from_data(length, value,
                                                            FALSE);
         case TCG_PTS_MEAS_ALGO_SELECTION:
             return tcg_pts_attr_meas_algo_create_from_data(length, value,
                                                            TRUE);
         case TCG_PTS_GET_TPM_VERSION_INFO:
             return tcg_pts_attr_get_tpm_version_info_create_from_data(length,
                                                                       value);
         case TCG_PTS_TPM_VERSION_INFO:
             return tcg_pts_attr_tpm_version_info_create_from_data(length,
                                                                   value);
         case TCG_PTS_GET_AIK:
             return tcg_pts_attr_get_aik_create_from_data(length, value);
         case TCG_PTS_AIK:
             return tcg_pts_attr_aik_create_from_data(length, value);
         case TCG_PTS_REQ_FUNC_COMP_EVID:
             return tcg_pts_attr_req_func_comp_evid_create_from_data(length,
                                                                     value);
         case TCG_PTS_GEN_ATTEST_EVID:
             return tcg_pts_attr_gen_attest_evid_create_from_data(length, value);
         case TCG_PTS_SIMPLE_COMP_EVID:
             return tcg_pts_attr_simple_comp_evid_create_from_data(length,
                                                                   value);
         case TCG_PTS_SIMPLE_EVID_FINAL:
             return tcg_pts_attr_simple_evid_final_create_from_data(length,
                                                                    value);
         case TCG_PTS_REQ_FILE_MEAS:
             return tcg_pts_attr_req_file_meas_create_from_data(length, value);
         case TCG_PTS_FILE_MEAS:
             return tcg_pts_attr_file_meas_create_from_data(length, value);
         case TCG_PTS_REQ_FILE_META:
             return tcg_pts_attr_req_file_meta_create_from_data(length, value);
         case TCG_PTS_UNIX_FILE_META:
             return tcg_pts_attr_unix_file_meta_create_from_data(length, value);
         /* unsupported TCG/SWID attributes */
         case TCG_SWID_TAG_ID_EVENTS:
         case TCG_SWID_TAG_EVENTS:
         case TCG_SWID_SUBSCRIPTION_STATUS_REQ:
         case TCG_SWID_SUBSCRIPTION_STATUS_RESP:
         /* unsupported TCG/PTS attributes */
         case TCG_PTS_REQ_TEMPL_REF_MANI_SET_META:
         case TCG_PTS_TEMPL_REF_MANI_SET_META:
         case TCG_PTS_UPDATE_TEMPL_REF_MANI:
         case TCG_PTS_VERIFICATION_RESULT:
         case TCG_PTS_INTEG_REPORT:
         case TCG_PTS_WIN_FILE_META:
         case TCG_PTS_REQ_REGISTRY_VALUE:
         case TCG_PTS_REGISTRY_VALUE:
         case TCG_PTS_REQ_INTEG_MEAS_LOG:
         case TCG_PTS_INTEG_MEAS_LOG:
         default:
             return NULL;
     }
 }
Variable Documentation
enum_name_t* tcg_attr_names
enum name for tcg_attr_t.
Referenced by imc_attestation_process(), imv_attestation_process(), libimcv_init(), and METHOD().