strongSwan: child_create
child_create
tasks
Classes
struct child_create_t
Typedefs
typedef struct child_create_t child_create_t
Functions
child_create_t * child_create_create (ike_sa_t *ike_sa, child_cfg_t *config, bool rekey, traffic_selector_t *tsi, traffic_selector_t *tsr)
Detailed Description
Typedef Documentation
typedef struct child_create_t child_create_t
Definition at line 24 of file child_create.h.
Function Documentation
child_create_t* child_create_create (ike_sa_t * ike_sa, child_cfg_t * config, bool rekey, traffic_selector_t * tsi, traffic_selector_t * tsr)
Create a new child_create task.
Parameters
ike_sa IKE_SA this task works for
config child_cfg if task initiator, NULL if responder
rekey whether we do a rekey or not
tsi source of triggering packet, or NULL
tsr destination of triggering packet, or NULL
Returns
child_create task to handle by the task_manager
Definition at line 1650 of file child_create.c.
References traffic_selector_t::clone, FALSE, ike_sa_t::get_keymat, INIT, initiator, IPCOMP_NONE, MODE_TUNNEL, MODP_NONE, and TRUE.
Referenced by child_rekey_create(), METHOD(), process_request(), and trigger_mbb_reauth().
 {
     private_child_create_t *this;
     INIT(this,
         .public = {
             .get_child = _get_child,
             .set_config = _set_config,
             .get_lower_nonce = _get_lower_nonce,
             .use_reqid = _use_reqid,
             .use_marks = _use_marks,
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .config = config,
         .packet_tsi = tsi ? tsi->clone(tsi) : NULL,
         .packet_tsr = tsr ? tsr->clone(tsr) : NULL,
         .dh_group = MODP_NONE,
         .keymat = (keymat_v2_t*)ike_sa->get_keymat(ike_sa),
         .mode = MODE_TUNNEL,
         .tfcv3 = TRUE,
         .ipcomp = IPCOMP_NONE,
         .ipcomp_received = IPCOMP_NONE,
         .rekey = rekey,
         .retry = FALSE,
     );
     if (config)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
         this->initiator = TRUE;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
         this->initiator = FALSE;
     }
     return &this->public;
 }