strongSwan: updown_plugin.c File Reference
updown_plugin.c File Reference
#include "updown_plugin.h"
#include "updown_listener.h"
#include "updown_handler.h"
#include <daemon.h>
Classes
struct private_updown_plugin_t
Typedefs
typedef struct
private_updown_plugin_t private_updown_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_updown_plugin_t *this)
static bool plugin_cb (private_updown_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_updown_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_updown_plugin_t *this)
plugin_t * updown_plugin_create ()
Typedef Documentation
typedef struct private_updown_plugin_t private_updown_plugin_t
Definition at line 22 of file updown_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_updown_plugin_t * this)
Definition at line 45 of file updown_plugin.c.
 {
     return "updown";
 }
METHOD (plugin_t , get_features , int , private_updown_plugin_t * this, plugin_feature_t * features[])
Definition at line 83 of file updown_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "updown"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_updown_plugin_t * this)
Definition at line 94 of file updown_plugin.c.
References free().
 {
     free(this);
 }
static bool plugin_cb (private_updown_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 54 of file updown_plugin.c.
References attribute_manager_t::add_handler, bus_t::add_listener, daemon_t::attributes, daemon_t::bus, charon, tkm_listener_t::destroy, FALSE, settings_t::get_bool, lib, listener, library_t::ns, attribute_manager_t::remove_handler, bus_t::remove_listener, library_t::settings, TRUE, updown_handler_create(), and updown_listener_create().
Referenced by METHOD().
 {
     if (reg)
     {
         if (lib->settings->get_bool(lib->settings,
                             "%s.plugins.updown.dns_handler", FALSE, lib->ns))
         {
             this->handler = updown_handler_create();
             charon->attributes->add_handler(charon->attributes,
                                             &this->handler->handler);
         }
         this->listener = updown_listener_create(this->handler);
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
         this->listener->destroy(this->listener);
         if (this->handler)
         {
             this->handler->destroy(this->handler);
             charon->attributes->remove_handler(charon->attributes,
                                                &this->handler->handler);
         }
     }
     return TRUE;
 }
plugin_t* updown_plugin_create ()
Definition at line 103 of file updown_plugin.c.
References INIT.
 {
     private_updown_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }