strongSwan: ntru_drbg
ntru_drbg
ntru
Classes
struct ntru_drbg_t
Typedefs
typedef struct ntru_drbg_t ntru_drbg_t
Functions
ntru_drbg_t * ntru_drbg_create (u_int32_t strength, chunk_t pers_str, rng_t *entropy)
Detailed Description
Typedef Documentation
typedef struct ntru_drbg_t ntru_drbg_t
Definition at line 24 of file ntru_drbg.h.
Function Documentation
ntru_drbg_t* ntru_drbg_create (u_int32_t strength, chunk_t pers_str, rng_t * entropy)
Create and instantiate a new DRBG objet.
Parameters
strength security strength in bits
pers_str personalization string
entropy entropy source to use
Definition at line 209 of file ntru_drbg.c.
References AUTH_HMAC_SHA2_256_256, BITS_PER_BYTE, chunk_alloc, chunk_clear(), chunk_free(), crypto_factory_t::create_signer, library_t::crypto, DBG1, DBG2, DBG4, DBG_LIB, destroy(), signer_t::get_block_size, rng_t::get_bytes, settings_t::get_int, signer_t::get_key_size, INIT, key, chunk_t::len, lib, MAX_DRBG_REQUESTS, MAX_STRENGTH_BITS, memcpy, memset, library_t::ns, chunk_t::ptr, library_t::settings, update(), and value.
Referenced by ntru_ke_create(), and START_TEST().
 {
     private_ntru_drbg_t *this;
     chunk_t seed;
     signer_t *hmac;
     size_t entropy_len;
     u_int32_t max_requests;
     if (strength > MAX_STRENGTH_BITS)
     {
         return NULL;
     }
     if (strength <= 112)
     {
         strength = 112;
     }
     else if (strength <= 128)
     {
         strength = 128;
     }
     else if (strength <= 192)
     {
         strength = 192;
     }
     else
     {
         strength = 256;
     }
     hmac = lib->crypto->create_signer(lib->crypto, AUTH_HMAC_SHA2_256_256);
     if (!hmac)
     {
         DBG1(DBG_LIB, "could not instantiate HMAC-SHA256");
         return NULL;
     }
     max_requests = lib->settings->get_int(lib->settings,
                                           "%s.plugins.ntru.max_drbg_requests",
                                           MAX_DRBG_REQUESTS, lib->ns);
     INIT(this,
         .public = {
             .get_strength = _get_strength,
             .reseed = _reseed,
             .generate = _generate,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .strength = strength,
         .entropy = entropy,
         .hmac = hmac,
         .key = chunk_alloc(hmac->get_key_size(hmac)),
         .value = chunk_alloc(hmac->get_block_size(hmac)),
         .max_requests = max_requests,
         .reseed_counter = 1,
         .ref = 1,
     );
     memset(this->key.ptr, 0x00, this->key.len);
     memset(this->value.ptr, 0x01, this->value.len);
     entropy_len = (strength + strength/2) / BITS_PER_BYTE;
     seed = chunk_alloc(entropy_len + pers_str.len);
     DBG2(DBG_LIB, "DRBG requests %u bytes of entropy", entropy_len);
     if (!this->entropy->get_bytes(this->entropy, entropy_len, seed.ptr))
     {
         chunk_free(&seed);
         destroy(this);
         return NULL;
     }
     memcpy(seed.ptr + entropy_len, pers_str.ptr, pers_str.len);
     DBG4(DBG_LIB, "seed: %B", &seed);
     if (!update(this, seed))
     {
         chunk_free(&seed);
         destroy(this);
         return NULL;
     }
     chunk_clear(&seed);
     return &this->public;
 }