strongSwan: ike_sa_manager_t Struct Reference
ike_sa_manager_t Struct Reference
ike_sa_manager
#include "ike_sa_manager.h"
Public Attributes
ike_sa_t *(* checkout)(ike_sa_manager_t *this, ike_sa_id_t *sa_id)
ike_sa_t *(* checkout_new)(ike_sa_manager_t *this, ike_version_t version, bool initiator)
ike_sa_t *(* checkout_by_message)(ike_sa_manager_t *this, message_t *message)
ike_sa_t *(* checkout_by_config)(ike_sa_manager_t *this, peer_cfg_t *peer_cfg)
bool(* check_uniqueness)(ike_sa_manager_t *this, ike_sa_t *ike_sa, bool force_replace)
bool(* has_contact)(ike_sa_manager_t *this, identification_t *me, identification_t *other, int family)
ike_sa_t *(* checkout_by_id)(ike_sa_manager_t *this, u_int32_t id)
ike_sa_t *(* checkout_by_name)(ike_sa_manager_t *this, char *name, bool child)
enumerator_t *(* create_enumerator)(ike_sa_manager_t *this, bool wait)
enumerator_t *(* create_id_enumerator)(ike_sa_manager_t *this, identification_t *me, identification_t *other, int family)
void(* checkin)(ike_sa_manager_t *this, ike_sa_t *ike_sa)
void(* checkin_and_destroy)(ike_sa_manager_t *this, ike_sa_t *ike_sa)
u_int(* get_count)(ike_sa_manager_t *this)
u_int(* get_half_open_count)(ike_sa_manager_t *this, host_t *ip, bool responder_only)
void(* set_spi_cb)(ike_sa_manager_t *this, spi_cb_t callback, void *data)
void(* flush)(ike_sa_manager_t *this)
void(* destroy)(ike_sa_manager_t *this)
Detailed Description
Manages and synchronizes access to all IKE_SAs.
To synchronize access to thread-unsave IKE_SAs, they are checked out for use and checked in afterwards. A checked out SA is exclusively accessible by the owning thread.
Definition at line 50 of file ike_sa_manager.h.
Member Data Documentation
bool(* ike_sa_manager_t::check_uniqueness)(ike_sa_manager_t *this, ike_sa_t *ike_sa, bool force_replace)
Check for duplicates of the given IKE_SA.
Measures are taken according to the uniqueness policy of the IKE_SA. The return value indicates whether duplicates have been found and if further measures should be taken (e.g. cancelling an IKE_AUTH exchange). check_uniqueness() must be called before the IKE_SA is complete, deadlocks occur otherwise.
Parameters
ike_sa ike_sa to check
force_replace replace existing SAs, regardless of unique policy
Returns
TRUE, if the given IKE_SA has duplicates and should be deleted
Definition at line 125 of file ike_sa_manager.h.
Referenced by allowed(), and METHOD().
void(* ike_sa_manager_t::checkin)(ike_sa_manager_t *this, ike_sa_t *ike_sa)
Checkin the SA after usage.
If the IKE_SA is not registered in the manager, a new entry is created.
Parameters
ike_sa_id the SA identifier, will be updated
ike_sa checked out SA
Definition at line 200 of file ike_sa_manager.h.
Referenced by add_exclude_async(), apply_lifetime(), checkout_ikesa(), connect_(), disconnect(), establish_new(), initiate_connection(), initiate_mediated(), METHOD(), process_child_add(), process_child_delete(), process_ike_add(), process_ike_iv(), process_ike_mid(), process_ike_update(), rekey_segment(), send_interim(), and trigger_mbb_reauth().
void(* ike_sa_manager_t::checkin_and_destroy)(ike_sa_manager_t *this, ike_sa_t *ike_sa)
Destroy a checked out SA.
The IKE SA is destroyed without notification of the remote peer. Use this only if the other peer doesn't respond or behaves not as predicted. Checking in and destruction is an atomic operation (for the IKE_SA), so this can be called if the SA is in a "unclean" state, without the risk that another thread can get the SA.
Parameters
ike_sa SA to delete
Definition at line 214 of file ike_sa_manager.h.
Referenced by apply_lifetime(), connect_(), initiate_connection(), initiate_mediated(), METHOD(), process_ike_add(), process_ike_delete(), process_ike_update(), rekey_segment(), and trigger_mbb_reauth().
ike_sa_t*(* ike_sa_manager_t::checkout)(ike_sa_manager_t *this, ike_sa_id_t *sa_id)
Checkout an existing IKE_SA.
Parameters
ike_sa_id the SA identifier, will be updated
Returns
checked out IKE_SA if found
NULL, if specified IKE_SA is not found.
Definition at line 60 of file ike_sa_manager.h.
Referenced by add_exclude_async(), apply_lifetime(), checkout_ikesa(), initiate_mediated(), METHOD(), process_child_add(), process_child_delete(), process_ike_add(), process_ike_delete(), process_ike_iv(), process_ike_mid(), process_ike_update(), rekey_segment(), and send_interim().
ike_sa_t*(* ike_sa_manager_t::checkout_by_config)(ike_sa_manager_t *this, peer_cfg_t *peer_cfg)
Checkout an IKE_SA for initiation by a peer_config.
To initiate, a CHILD_SA may be established within an existing IKE_SA. This call checks for an existing IKE_SA by comparing the configuration. If the CHILD_SA can be created in an existing IKE_SA, the matching SA is returned. If no IKE_SA is found, a new one is created. This is also the case when the found IKE_SA is in the DELETING state.
Parameters
peer_cfg configuration used to find an existing IKE_SA
Returns
checked out/created IKE_SA
Definition at line 108 of file ike_sa_manager.h.
Referenced by connect_(), initiate_connection(), and METHOD().
ike_sa_t*(* ike_sa_manager_t::checkout_by_id)(ike_sa_manager_t *this, u_int32_t id)
Check out an IKE_SA a unique ID.
Every IKE_SA is uniquely identified by a numerical ID. This checkout function uses the unique ID of the IKE_SA to check it out.
Parameters
id unique ID of the object
Returns
checked out IKE_SA, if found
NULL, if not found
Definition at line 150 of file ike_sa_manager.h.
Referenced by METHOD().
ike_sa_t*(* ike_sa_manager_t::checkout_by_message)(ike_sa_manager_t *this, message_t *message)
Checkout an IKE_SA by a message.
In some situations, it is necessary that the manager knows the message to use for the checkout. This has the following reasons:
If the targeted IKE_SA is already processing a message, we do not check it out if the message ID is the same.
If it is an IKE_SA_INIT request, we have to check if it is a retransmission. If so, we have to drop the message, we would create another unneeded IKE_SA for each retransmitted packet.
A call to checkout_by_message() returns a (maybe new created) IKE_SA. If processing the message does not make sense (for the reasons above), NULL is returned.
Parameters
ike_sa_id the SA identifier, will be updated
Returns
checked out/created IKE_SA
NULL to not process message further
Definition at line 93 of file ike_sa_manager.h.
Referenced by METHOD().
ike_sa_t*(* ike_sa_manager_t::checkout_by_name)(ike_sa_manager_t *this, char *name, bool child)
Check out an IKE_SA by the policy/connection name.
Check out the IKE_SA by the configuration name, either from the IKE- or one of its CHILD_SAs.
Parameters
name name of the connection/policy
child TRUE to use policy name, FALSE to use conn name
Returns
checked out IKE_SA, if found
NULL, if not found
Definition at line 164 of file ike_sa_manager.h.
Referenced by disconnect().
ike_sa_t*(* ike_sa_manager_t::checkout_new)(ike_sa_manager_t *this, ike_version_t version, bool initiator)
Create and check out a new IKE_SA.
Parameters
version IKE version of this SA
initiator TRUE for initiator, FALSE otherwise
Returns
created and checked out IKE_SA
Definition at line 69 of file ike_sa_manager.h.
Referenced by METHOD(), and trigger_mbb_reauth().
enumerator_t*(* ike_sa_manager_t::create_enumerator)(ike_sa_manager_t *this, bool wait)
Create an enumerator over all stored IKE_SAs.
While enumerating an IKE_SA, it is temporarily checked out and automatically checked in after the current enumeration step.
Parameters
wait TRUE to wait for checked out SAs, FALSE to skip
Returns
enumerator over all IKE_SAs.
Definition at line 176 of file ike_sa_manager.h.
Referenced by add_matching_ike_sas(), check_systime(), delete_all_async(), enable_disable(), METHOD(), rekey_segment(), and stroke_export().
enumerator_t*(* ike_sa_manager_t::create_id_enumerator)(ike_sa_manager_t *this, identification_t *me, identification_t *other, int family)
Create an enumerator over ike_sa_id_t*, matching peer identities.
The remote peer is identified by its XAuth or EAP identity, if available.
Parameters
me local peer identity to match
other remote peer identity to match
family address family to match, 0 for any
Returns
enumerator over ike_sa_id_t*
Definition at line 188 of file ike_sa_manager.h.
Referenced by METHOD().
void(* ike_sa_manager_t::destroy)(ike_sa_manager_t *this)
Destroys the manager with all associated SAs.
A call to flush() is required before calling destroy.
Definition at line 262 of file ike_sa_manager.h.
void(* ike_sa_manager_t::flush)(ike_sa_manager_t *this)
Delete all existing IKE_SAs and destroy them immediately.
Threads will be driven out, so all SAs can be deleted cleanly. To a flush(), an immediate call to destroy() is mandatory; no other method may be used.
Definition at line 255 of file ike_sa_manager.h.
u_int(* ike_sa_manager_t::get_count)(ike_sa_manager_t *this)
Get the number of IKE_SAs currently registered.
Returns
number of registered IKE_SAs
Definition at line 221 of file ike_sa_manager.h.
Referenced by CALLBACK(), do_load_test(), and METHOD().
u_int(* ike_sa_manager_t::get_half_open_count)(ike_sa_manager_t *this, host_t *ip, bool responder_only)
Get the number of IKE_SAs which are in the connecting state.
To prevent the server from resource exhaustion, cookies and other mechanisms are used. The number of half open IKE_SAs is a good indicator to see if a peer is flooding the server. If a host is supplied, only the number of half open IKE_SAs with this IP are counted.
Parameters
ip NULL for all, IP for half open IKE_SAs with IP
responder_only TRUE to return only the number of responding SAs
Returns
number of half open IKE_SAs
Definition at line 236 of file ike_sa_manager.h.
Referenced by CALLBACK(), drop_ike_sa_init(), and METHOD().
bool(* ike_sa_manager_t::has_contact)(ike_sa_manager_t *this, identification_t *me, identification_t *other, int family)
Check if we already have a connected IKE_SA between two identities.
Parameters
me own identity
other remote identity
family address family to include in uniqueness check
Returns
TRUE if we have a connected IKE_SA
Definition at line 136 of file ike_sa_manager.h.
Referenced by add_initial_contact(), and METHOD().
void(* ike_sa_manager_t::set_spi_cb)(ike_sa_manager_t *this, spi_cb_t callback, void *data)
Set the callback to generate IKE SPIs
Parameters
callback callback to register
data data provided to callback
Definition at line 245 of file ike_sa_manager.h.
Referenced by tkm_spi_generator_register().
The documentation for this struct was generated from the following file:
ike_sa_manager.h