strongSwan: config_controller.c File Reference
config_controller.c File Reference
#include "config_controller.h"
#include "../manager.h"
#include "../gateway.h"
#include <xml.h>
#include <library.h>
Classes
struct private_config_controller_t
Typedefs
typedef struct
private_config_controller_t private_config_controller_t
Functions
static void process_peerconfig (private_config_controller_t *this, enumerator_t *e, fast_request_t *r)
static void list (private_config_controller_t *this, fast_request_t *r)
METHOD (fast_controller_t, get_name, char *, private_config_controller_t *this)
METHOD (fast_controller_t, handle, void, private_config_controller_t *this, fast_request_t *request, char *action, char *p2, char *p3, char *p4, char *p5)
METHOD (fast_controller_t, destroy, void, private_config_controller_t *this)
fast_controller_t * config_controller_create (fast_context_t *context, void *param)
Typedef Documentation
typedef struct private_config_controller_t private_config_controller_t
Definition at line 25 of file config_controller.c.
Function Documentation
static void list (private_config_controller_t * this, fast_request_t * r) static
Definition at line 118 of file config_controller.c.
References xml_t::children, enumerator_t::destroy, enumerator_t::enumerate, name, process_peerconfig(), gateway_t::query_configlist, fast_request_t::render, fast_request_t::set, streq(), and value.
Referenced by METHOD().
 {
     gateway_t *gateway;
     xml_t *xml;
     enumerator_t *e1, *e2;
     char *name, *value;
     gateway = this->manager->select_gateway(this->manager, 0);
     e1 = gateway->query_configlist(gateway);
     if (e1 == NULL)
     {
         r->set(r, "title", "Error");
         r->set(r, "error", "querying the gateway failed");
         r->render(r, "templates/error.cs");
     }
     else
     {
         r->set(r, "title", "Configuration overview");
         while (e1->enumerate(e1, &xml, &name, &value))
         {
             if (streq(name, "peerconfig"))
             {
                 e2 = xml->children(xml);
                 process_peerconfig(this, e2, r);
                 e2->destroy(e2);
             }
         }
         e1->destroy(e1);
         r->render(r, "templates/config/list.cs");
     }
 }
METHOD (fast_controller_t , get_name , char * , private_config_controller_t * this)
Definition at line 152 of file config_controller.c.
 {
     return "config";
 }
METHOD (fast_controller_t , handle , void , private_config_controller_t * this, fast_request_t * request, char * action, char * p2, char * p3, char * p4, char * p5)
Definition at line 158 of file config_controller.c.
References list(), fast_request_t::redirect, and streq().
 {
     if (!this->manager->logged_in(this->manager))
     {
         return request->redirect(request, "auth/login");
     }
     if (this->manager->select_gateway(this->manager, 0) == NULL)
     {
         return request->redirect(request, "gateway/list");
     }
     if (action)
     {
         if (streq(action, "list"))
         {
             return list(this, request);
         }
     }
     return request->redirect(request, "config/list");
 }
METHOD (fast_controller_t , destroy , void , private_config_controller_t * this)
Definition at line 180 of file config_controller.c.
References free().
 {
     free(this);
 }
static void process_peerconfig (private_config_controller_t * this, enumerator_t * e, fast_request_t * r) static
read XML of a peerconfig element and fill template
Definition at line 46 of file config_controller.c.
References xml_t::children, enumerator_t::destroy, enumerator_t::enumerate, name, section, fast_request_t::setf, streq(), and value.
Referenced by list().
 {
     xml_t *xml;
     enumerator_t *e1, *e2, *e3;
     char *name, *value, *config = "", *child = "", *section = "";
     while (e->enumerate(e, &xml, &name, &value))
     {
         if (streq(name, "name"))
         {
             config = value;
         }
         else if (streq(name, "ikeconfig"))
         {
             e1 = xml->children(xml);
             while (e1->enumerate(e1, &xml, &name, &value))
             {
                 if (streq(name, "local") || streq(name, "remote"))
                 {
                     if (streq(value, "0.0.0.0") || streq(value, "::"))
                     {
                         value = "%any";
                     }
                     r->setf(r, "peercfgs.%s.ikecfg.%s=%s", config, name, value);
                 }
             }
             e1->destroy(e1);
         }
         else if (streq(name, "childconfiglist"))
         {
             e1 = xml->children(xml);
             while (e1->enumerate(e1, &xml, &name, &value))
             {
                 if (streq(name, "childconfig"))
                 {
                     int num = 0;
                     e2 = xml->children(xml);
                     while (e2->enumerate(e2, &xml, &name, &value))
                     {
                         if (streq(name, "name"))
{
                             child = value;
                         }
                         else if (streq(name, "local") || streq(name, "remote"))
{
                             section = name;
                             e3 = xml->children(xml);
                             while (e3->enumerate(e3, &xml, &name, &value))
{
                                 if (streq(name, "network"))
{
                                     r->setf(r, "peercfgs.%s.childcfgs.%s.%s.networks.%d=%s",
                                             config, child, section, ++num, value);
                                 }
                             }
                             e3->destroy(e3);
                         }
                     }
                     e2->destroy(e2);
                 }
             }
             e1->destroy(e1);
         }
         else
         {
             r->setf(r, "peercfgs.%s.%s=%s", config, name, value);
         }
     }
 }