strongSwan: kernel_libipsec_ipsec
kernel_libipsec_ipsec
kernel_libipsec
Classes
struct kernel_libipsec_ipsec_t
Typedefs
typedef struct
kernel_libipsec_ipsec_t kernel_libipsec_ipsec_t
Functions
kernel_libipsec_ipsec_t * kernel_libipsec_ipsec_create ()
Detailed Description
Typedef Documentation
typedef struct kernel_libipsec_ipsec_t kernel_libipsec_ipsec_t
Definition at line 27 of file kernel_libipsec_ipsec.h.
Function Documentation
kernel_libipsec_ipsec_t* kernel_libipsec_ipsec_create ()
Create a libipsec ipsec interface instance.
Returns
kernel_libipsec_ipsec_t instance
Definition at line 669 of file kernel_libipsec_ipsec.c.
References ipsec_t::events, expire(), FALSE, settings_t::get_bool, INIT, ipsec, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, ipsec_event_relay_t::register_listener, and library_t::settings.
Referenced by METHOD().
 {
     private_kernel_libipsec_ipsec_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_features = _get_features,
                 .get_spi = _get_spi,
                 .get_cpi = _get_cpi,
                 .add_sa  = _add_sa,
                 .update_sa = _update_sa,
                 .query_sa = _query_sa,
                 .del_sa = _del_sa,
                 .flush_sas = _flush_sas,
                 .add_policy = _add_policy,
                 .query_policy = _query_policy,
                 .del_policy = _del_policy,
                 .flush_policies = _flush_policies,
                 .bypass_socket = _bypass_socket,
                 .enable_udp_decap = _enable_udp_decap,
                 .destroy = _destroy,
             },
         },
         .ipsec_listener = {
             .expire = expire,
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .policies = linked_list_create(),
         .excludes = linked_list_create(),
         .allow_peer_ts = lib->settings->get_bool(lib->settings,
                     "%s.plugins.kernel-libipsec.allow_peer_ts", FALSE, lib->ns),
     );
     ipsec->events->register_listener(ipsec->events, &this->ipsec_listener);
     return &this->public;
 };