strongSwan: eap_sim_file_card
eap_sim_file_card
eap_sim_file
Classes
struct eap_sim_file_card_t
Typedefs
typedef struct eap_sim_file_card_t eap_sim_file_card_t
Functions
eap_sim_file_card_t * eap_sim_file_card_create (eap_sim_file_triplets_t *triplets)
Detailed Description
Typedef Documentation
typedef struct eap_sim_file_card_t eap_sim_file_card_t
Definition at line 28 of file eap_sim_file_card.h.
Function Documentation
eap_sim_file_card_t* eap_sim_file_card_create (eap_sim_file_triplets_t * triplets)
Create a eap_sim_file_card instance.
Parameters
triplets source of triplets
See header
Definition at line 86 of file eap_sim_file_card.c.
References destroy(), INIT, nop(), return_false(), and return_null().
Referenced by load_triplets().
 {
     private_eap_sim_file_card_t *this;
     INIT(this,
         .public = {
             .card = {
                 .get_triplet = _get_triplet,
                 .get_quintuplet = _get_quintuplet,
                 .resync = (void*)return_false,
                 .get_pseudonym = (void*)return_null,
                 .set_pseudonym = (void*)nop,
                 .get_reauth = (void*)return_null,
                 .set_reauth = (void*)nop,
             },
             .destroy = _destroy,
         },
         .triplets = triplets,
     );
     return &this->public;
 }