strongSwan: hashtable.c File Reference
hashtable.c File Reference
#include "hashtable.h"
#include <utils/chunk.h>
Classes
struct pair_t
struct private_hashtable_t
struct private_enumerator_t
Macros
#define MAX_CAPACITY (1 << 30)
Typedefs
typedef struct pair_t pair_t
typedef struct private_hashtable_t private_hashtable_t
typedef struct private_enumerator_t private_enumerator_t
Functions
static pair_t * pair_create (const void *key, void *value, u_int hash)
u_int hashtable_hash_ptr (const void *key)
u_int hashtable_hash_str (const void *key)
bool hashtable_equals_ptr (const void *key, const void *other_key)
bool hashtable_equals_str (const void *key, const void *other_key)
static u_int get_nearest_powerof2 (u_int n)
static void init_hashtable (private_hashtable_t *this, u_int capacity)
static void rehash (private_hashtable_t *this)
METHOD (hashtable_t, put, void *, private_hashtable_t *this, const void *key, void *value)
static void * get_internal (private_hashtable_t *this, const void *key, hashtable_equals_t equals)
METHOD (hashtable_t, get, void *, private_hashtable_t *this, const void *key)
METHOD (hashtable_t, get_match, void *, private_hashtable_t *this, const void *key, hashtable_equals_t match)
METHOD (hashtable_t, remove_, void *, private_hashtable_t *this, const void *key)
METHOD (hashtable_t, remove_at, void, private_hashtable_t *this, private_enumerator_t *enumerator)
METHOD (hashtable_t, get_count, u_int, private_hashtable_t *this)
METHOD (enumerator_t, enumerate, bool, private_enumerator_t *this, const void **key, void **value)
METHOD (hashtable_t, create_enumerator, enumerator_t *, private_hashtable_t *this)
static void destroy_internal (private_hashtable_t *this, void(*fn)(void *, const void *))
METHOD (hashtable_t, destroy, void, private_hashtable_t *this)
METHOD (hashtable_t, destroy_function, void, private_hashtable_t *this, void(*fn)(void *, const void *))
hashtable_t * hashtable_create (hashtable_hash_t hash, hashtable_equals_t equals, u_int capacity)
Macro Definition Documentation
#define MAX_CAPACITY (1 << 30)
The maximum capacity of the hash table (MUST be a power of 2)
Definition at line 22 of file hashtable.c.
Referenced by init_hashtable(), and rehash().
Typedef Documentation
typedef struct pair_t pair_t
Definition at line 24 of file hashtable.c.
typedef struct private_enumerator_t private_enumerator_t
Definition at line 115 of file hashtable.c.
typedef struct private_hashtable_t private_hashtable_t
Definition at line 67 of file hashtable.c.
Function Documentation
static void destroy_internal (private_hashtable_t * this, void(*)(void *, const void *) fn) static
Definition at line 430 of file hashtable.c.
References fn, free(), pair_t::key, pair_t::next, next, and pair_t::value.
Referenced by METHOD().
 {
     pair_t *pair, *next;
     u_int row;
     for (row = 0; row < this->capacity; row++)
     {
         pair = this->table[row];
         while (pair)
         {
             if (fn)
             {
                 fn(pair->value, pair->key);
             }
             next = pair->next;
             free(pair);
             pair = next;
         }
     }
     free(this->table);
     free(this);
 }
static void* get_internal (private_hashtable_t * this, const void * key, hashtable_equals_t equals) static
Definition at line 287 of file hashtable.c.
References count, equals(), hash, pair_t::key, mask, pair_t::next, pair_t::value, and value.
Referenced by METHOD().
 {
     void *value = NULL;
     pair_t *pair;
     if (!this->count)
     {   /* no need to calculate the hash */
         return NULL;
     }
     pair = this->table[this->hash(key) & this->mask];
     while (pair)
     {
         if (equals(key, pair->key))
         {
             value = pair->value;
             break;
         }
         pair = pair->next;
     }
     return value;
 }
static u_int get_nearest_powerof2 (u_int n) static
This function returns the next-highest power of two for the given number. The algorithm works by setting all bits on the right-hand side of the most significant 1 to 1 and then increments the whole number so it rolls over to the nearest power of two. Note: returns 0 for n == 0
Definition at line 191 of file hashtable.c.
References n.
Referenced by init_hashtable().
 {
     u_int i;
     --n;
     for (i = 1; i < sizeof(u_int) * 8; i <<= 1)
     {
         n |= n >> i;
     }
     return ++n;
 }
static void init_hashtable (private_hashtable_t * this, u_int capacity) static
Init hash table parameters
Definition at line 206 of file hashtable.c.
References get_nearest_powerof2(), mask, max, MAX_CAPACITY, and min.
Referenced by hashtable_create(), and rehash().
 {
     capacity = max(1, min(capacity, MAX_CAPACITY));
     this->capacity = get_nearest_powerof2(capacity);
     this->mask = this->capacity - 1;
     this->load_factor = 0.75;
     this->table = calloc(this->capacity, sizeof(pair_t*));
 }
METHOD (hashtable_t , put , void * , private_hashtable_t * this, const void * key, void * value)
Definition at line 252 of file hashtable.c.
References count, equals(), hash, pair_t::key, key, mask, pair_t::next, pair_create(), rehash(), pair_t::value, and value.
 {
     void *old_value = NULL;
     pair_t *pair;
     u_int hash, row;
     hash = this->hash(key);
     row = hash & this->mask;
     pair = this->table[row];
     while (pair)
     {   /* search existing bucket for key */
         if (this->equals(key, pair->key))
         {
             old_value = pair->value;
             pair->value = value;
             pair->key = key;
             break;
         }
         pair = pair->next;
     }
     if (!pair)
     {   /* insert at the front of bucket */
         pair = pair_create(key, value, hash);
         pair->next = this->table[row];
         this->table[row] = pair;
         this->count++;
     }
     if (this->count >= this->capacity * this->load_factor)
     {
         rehash(this);
     }
     return old_value;
 }
METHOD (hashtable_t , get , void * , private_hashtable_t * this, const void * key)
Definition at line 311 of file hashtable.c.
References equals(), and get_internal().
 {
     return get_internal(this, key, this->equals);
 }
METHOD (hashtable_t , get_match , void * , private_hashtable_t * this, const void * key, hashtable_equals_t match)
Definition at line 317 of file hashtable.c.
References get_internal().
 {
     return get_internal(this, key, match);
 }
METHOD (hashtable_t , remove_ , void * , private_hashtable_t * this, const void * key)
Definition at line 323 of file hashtable.c.
References count, equals(), free(), hash, pair_t::key, mask, pair_t::next, pair_t::value, and value.
 {
     void *value = NULL;
     pair_t *pair, *prev = NULL;
     u_int row;
     row = this->hash(key) & this->mask;
     pair = this->table[row];
     while (pair)
     {
         if (this->equals(key, pair->key))
         {
             if (prev)
             {
                 prev->next = pair->next;
             }
             else
             {
                 this->table[row] = pair->next;
             }
             value = pair->value;
             this->count--;
             free(pair);
             break;
         }
         prev = pair;
         pair = pair->next;
     }
     return value;
 }
METHOD (hashtable_t , remove_at , void , private_hashtable_t * this, private_enumerator_t * enumerator)
Definition at line 355 of file hashtable.c.
References count, private_enumerator_t::current, free(), pair_t::next, table_item_t::next, private_enumerator_t::prev, private_enumerator_t::row, and private_enumerator_t::table.
 {
     if (enumerator->table == this && enumerator->current)
     {
         pair_t *current = enumerator->current;
         if (enumerator->prev)
         {
             enumerator->prev->next = current->next;
         }
         else
         {
             this->table[enumerator->row] = current->next;
         }
         enumerator->current = enumerator->prev;
         free(current);
         this->count--;
     }
 }
METHOD (hashtable_t , get_count , u_int , private_hashtable_t * this)
Definition at line 375 of file hashtable.c.
References count.
 {
     return this->count;
 }
METHOD (enumerator_t , enumerate , bool , private_enumerator_t * this, const void ** key, void ** value)
Definition at line 381 of file hashtable.c.
References count, FALSE, and TRUE.
 {
     while (this->count && this->row < this->table->capacity)
     {
         this->prev = this->current;
         if (this->current)
         {
             this->current = this->current->next;
         }
         else
         {
             this->current = this->table->table[this->row];
         }
         if (this->current)
         {
             if (key)
             {
                 *key = this->current->key;
             }
             if (value)
             {
                 *value = this->current->value;
             }
             this->count--;
             return TRUE;
         }
         this->row++;
     }
     return FALSE;
 }
METHOD (hashtable_t , create_enumerator , enumerator_t * , private_hashtable_t * this)
Definition at line 413 of file hashtable.c.
References count, destroy(), private_enumerator_t::enumerator, free(), and INIT.
 {
     private_enumerator_t *enumerator;
     INIT(enumerator,
         .enumerator = {
             .enumerate = (void*)_enumerate,
             .destroy = (void*)free,
         },
         .table = this,
         .count = this->count,
     );
     return &enumerator->enumerator;
 }
METHOD (hashtable_t , destroy , void , private_hashtable_t * this)
Definition at line 454 of file hashtable.c.
References destroy_internal().
 {
     destroy_internal(this, NULL);
 }
METHOD (hashtable_t , destroy_function , void , private_hashtable_t * this, void(*)(void *, const void *) fn)
Definition at line 460 of file hashtable.c.
References destroy_internal(), and fn.
 {
     destroy_internal(this, fn);
 }
static pair_t* pair_create (const void * key, void * value, u_int hash) inline static
Creates an empty pair object.
Definition at line 54 of file hashtable.c.
References INIT.
Referenced by METHOD().
 {
     pair_t *this;
     INIT(this,
         .key = key,
         .value = value,
         .hash = hash,
     );
     return this;
 }
static void rehash (private_hashtable_t * this) static
Double the size of the hash table and rehash all the elements.
Definition at line 219 of file hashtable.c.
References free(), pair_t::hash, init_hashtable(), mask, MAX_CAPACITY, pair_t::next, and next.
Referenced by METHOD().
 {
     pair_t **old_table;
     u_int row, old_capacity;
     if (this->capacity >= MAX_CAPACITY)
     {
         return;
     }
     old_capacity = this->capacity;
     old_table = this->table;
     init_hashtable(this, old_capacity << 1);
     for (row = 0; row < old_capacity; row++)
     {
         pair_t *pair, *next;
         u_int new_row;
         pair = old_table[row];
         while (pair)
         {   /* insert pair at the front of new bucket*/
             next = pair->next;
             new_row = pair->hash & this->mask;
             pair->next = this->table[new_row];
             this->table[new_row] = pair;
             pair = next;
         }
     }
     free(old_table);
 }