strongSwan: openssl_util
openssl_util
openssl
Macros
#define EC_FIELD_ELEMENT_LEN(group) ((EC_GROUP_get_degree(group) + 7) / 8)
#define openssl_i2chunk(type, obj)
Functions
bool openssl_hash_chunk (int hash_type, chunk_t data, chunk_t *hash)
bool openssl_bn_cat (int len, BIGNUM *a, BIGNUM *b, chunk_t *chunk)
bool openssl_bn_split (chunk_t chunk, BIGNUM *a, BIGNUM *b)
bool openssl_bn2chunk (BIGNUM *bn, chunk_t *chunk)
chunk_t openssl_asn1_obj2chunk (ASN1_OBJECT *asn1)
chunk_t openssl_asn1_str2chunk (ASN1_STRING *asn1)
identification_t * openssl_x509_name2id (X509_NAME *name)
int openssl_asn1_known_oid (ASN1_OBJECT *obj)
time_t openssl_asn1_to_time (ASN1_TIME *time)
Detailed Description
Macro Definition Documentation
#define EC_FIELD_ELEMENT_LEN (group) ((EC_GROUP_get_degree(group) + 7) / 8)
Returns the length in bytes of a field element
Definition at line 37 of file openssl_util.h.
Referenced by build_signature(), and ecp2chunk().
#define openssl_i2chunk (type, obj)
Value:
({ \
                    unsigned char *ptr = NULL; \
                    int len = i2d_##type(obj, &ptr); \
                    len < 0 ? chunk_empty : chunk_create(ptr, len);})
Allocate a chunk using the i2d function of a given object
Parameters
type type of the object
obj object to convert to DER
Returns
allocated chunk of the object, or chunk_empty
Definition at line 92 of file openssl_util.h.
Referenced by add_cert(), add_key(), METHOD(), openssl_x509_name2id(), and parse_certificate().
Function Documentation
int openssl_asn1_known_oid (ASN1_OBJECT * obj)
Check if an ASN1 oid is a an OID known by libstrongswan.
Parameters
obj openssl ASN1 object
Returns
OID, as defined in <asn1/oid.h>
Described in header.
Definition at line 200 of file openssl_util.c.
References asn1_known_oid(), and openssl_asn1_obj2chunk().
Referenced by parse_authorityInfoAccess_ext(), parse_certificate(), and parse_crl().
 {
     return asn1_known_oid(openssl_asn1_obj2chunk(obj));
 }
chunk_t openssl_asn1_obj2chunk (ASN1_OBJECT * asn1)
Convert an OpenSSL ASN1_OBJECT to a chunk.
Parameters
asn1 asn1 object to convert
Returns
chunk, pointing into asn1 object
Described in header.
Definition at line 148 of file openssl_util.c.
References chunk_create(), and chunk_empty.
Referenced by openssl_asn1_known_oid(), parse_certificate(), and parse_crl().
 {
     if (asn1)
     {
         return chunk_create((u_char*)asn1->data, asn1->length);
     }
     return chunk_empty;
 }
chunk_t openssl_asn1_str2chunk (ASN1_STRING * asn1)
Convert an OpenSSL ASN1_STRING to a chunk.
Parameters
asn1 asn1 string to convert
Returns
chunk, pointing into asn1 string
Described in header.
Definition at line 160 of file openssl_util.c.
References chunk_create(), and chunk_empty.
Referenced by general_name2id(), METHOD(), openssl_asn1_to_time(), parse_authKeyIdentifier_ext(), parse_certificate(), parse_crlNumber_ext(), and parse_subjectKeyIdentifier_ext().
 {
     if (asn1)
     {
         return chunk_create(ASN1_STRING_data(asn1), ASN1_STRING_length(asn1));
     }
     return chunk_empty;
 }
time_t openssl_asn1_to_time (ASN1_TIME * time)
Convert an OpenSSL ASN1_TIME to a time_t.
Parameters
time openssl ASN1_TIME
Returns
time_t, 0 on error
Described in header.
Definition at line 208 of file openssl_util.c.
References asn1_to_time(), DBG1, DBG_LIB, and openssl_asn1_str2chunk().
Referenced by METHOD(), parse_certificate(), and parse_crl().
 {
     chunk_t chunk;
     if (time)
     {
         chunk = openssl_asn1_str2chunk(time);
         switch (time->type)
         {
             case V_ASN1_UTCTIME:
             case V_ASN1_GENERALIZEDTIME:
                 return asn1_to_time(&chunk, time->type);
             default:
                 break;
         }
     }
     DBG1(DBG_LIB, "invalid ASN1 time");
     return 0;
 }
bool openssl_bn2chunk (BIGNUM * bn, chunk_t * chunk)
Exports the given bignum (assumed to be a positive number) to a chunk in two's complement format (i.e. a zero byte is added if the MSB is set).
Parameters
bn the BIGNUM to export
chunk the chunk (data gets allocated)
Returns
TRUE on success, FALSE otherwise
Described in header.
Definition at line 130 of file openssl_util.c.
References chunk_alloc, chunk_cat, chunk_free(), chunk_from_chars, FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by METHOD(), and openssl_rsa_fingerprint().
 {
     *chunk = chunk_alloc(BN_num_bytes(bn));
     if (BN_bn2bin(bn, chunk->ptr) == chunk->len)
     {
         if (chunk->len && chunk->ptr[0] & 0x80)
         {   /* if MSB is set, prepend a zero to make it non-negative */
             *chunk = chunk_cat("cm", chunk_from_chars(0x00), *chunk);
         }
         return TRUE;
     }
     chunk_free(chunk);
     return FALSE;
 }
bool openssl_bn_cat (int len, BIGNUM * a, BIGNUM * b, chunk_t * chunk)
Concatenates two bignums into a chunk, thereby enfocing the length of a single BIGNUM, if necessary, by pre-pending it with zeros.
Note: this function allocates memory for the chunk
Parameters
len the length of a single BIGNUM
a first BIGNUM
b second BIGNUM
chunk resulting chunk
Returns
TRUE on success, FALSE otherwise
Described in header.
Definition at line 73 of file openssl_util.c.
References chunk_free(), FALSE, chunk_t::len, malloc(), memset, offset, chunk_t::ptr, and TRUE.
Referenced by build_signature(), and ecp2chunk().
 {
     int offset;
     chunk->len = len + (b ? len : 0);
     chunk->ptr = malloc(chunk->len);
     memset(chunk->ptr, 0, chunk->len);
     /* convert a */
     offset = len - BN_num_bytes(a);
     if (!BN_bn2bin(a, chunk->ptr + offset))
     {
         goto error;
     }
     /* optionally convert and concatenate b */
     if (b)
     {
         offset = len - BN_num_bytes(b);
         if (!BN_bn2bin(b, chunk->ptr + len + offset))
         {
             goto error;
         }
     }
     return TRUE;
 error:
     chunk_free(chunk);
     return FALSE;
 }
bool openssl_bn_split (chunk_t chunk, BIGNUM * a, BIGNUM * b)
Splits a chunk into two bignums of equal binary length.
Parameters
chunk a chunk that contains the two BIGNUMs
a first BIGNUM
b second BIGNUM
Returns
TRUE on success, FALSE otherwise
Described in header.
Definition at line 107 of file openssl_util.c.
References FALSE, chunk_t::len, len, chunk_t::ptr, and TRUE.
Referenced by chunk2ecp(), and verify_signature().
 {
     int len;
     if ((chunk.len % 2) != 0)
     {
         return FALSE;
     }
     len = chunk.len / 2;
     if (!BN_bin2bn(chunk.ptr, len, a) ||
         !BN_bin2bn(chunk.ptr + len, len, b))
     {
         return FALSE;
     }
     return TRUE;
 }
bool openssl_hash_chunk (int hash_type, chunk_t data, chunk_t * hash)
Creates a hash of a given type of a chunk of data.
Note: this function allocates memory for the hash
Parameters
hash_type NID of the hash
data the chunk of data to hash
hash chunk that contains the hash
Returns
TRUE on success, FALSE otherwise
Described in header.
Definition at line 28 of file openssl_util.c.
References chunk_alloc, chunk_free(), ctx, FALSE, hasher, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by build_curve_signature(), build_der_signature(), verify_curve_signature(), and verify_der_signature().
 {
     EVP_MD_CTX *ctx;
     bool ret = FALSE;
     const EVP_MD *hasher = EVP_get_digestbynid(hash_type);
     if (!hasher)
     {
         return FALSE;
     }
     ctx = EVP_MD_CTX_create();
     if (!ctx)
     {
         goto error;
     }
     if (!EVP_DigestInit_ex(ctx, hasher, NULL))
     {
         goto error;
     }
     if (!EVP_DigestUpdate(ctx, data.ptr, data.len))
     {
         goto error;
     }
     *hash = chunk_alloc(hasher->md_size);
     if (!EVP_DigestFinal_ex(ctx, hash->ptr, NULL))
     {
         chunk_free(hash);
         goto error;
     }
     ret = TRUE;
 error:
     if (ctx)
     {
         EVP_MD_CTX_destroy(ctx);
     }
     return ret;
 }
identification_t* openssl_x509_name2id (X509_NAME * name)
Convert an openssl X509_NAME to a identification_t of type ID_DER_ASN1_DN.
Parameters
name name to convert
Returns
identification_t, NULL on error
Convert a X509 name to a ID_DER_ASN1_DN identification_t
Definition at line 172 of file openssl_util.c.
References free(), id, ID_DER_ASN1_DN, identification_create_from_encoding(), chunk_t::len, openssl_i2chunk, and chunk_t::ptr.
Referenced by general_name2id(), parse_certificate(), and parse_crl().
 {
     if (name)
     {
         identification_t *id;
         chunk_t chunk;
         chunk = openssl_i2chunk(X509_NAME, name);
         if (chunk.len)
         {
             id = identification_create_from_encoding(ID_DER_ASN1_DN, chunk);
             free(chunk.ptr);
             return id;
         }
     }
     return NULL;
 }