strongSwan: tcg_pts_attr_proto_caps.c File Reference
tcg_pts_attr_proto_caps.c File Reference
#include "tcg_pts_attr_proto_caps.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_proto_caps_t
Macros
#define PTS_PROTO_CAPS_SIZE 4
#define PTS_PROTO_CAPS_RESERVED 0x0000
Typedefs
typedef struct
private_tcg_pts_attr_proto_caps_t private_tcg_pts_attr_proto_caps_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_proto_caps_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_proto_caps_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_proto_caps_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_proto_caps_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_proto_caps_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_proto_caps_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_proto_caps_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_proto_caps_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_proto_caps_t *this)
METHOD (tcg_pts_attr_proto_caps_t, get_flags, pts_proto_caps_flag_t, private_tcg_pts_attr_proto_caps_t *this)
pa_tnc_attr_t * tcg_pts_attr_proto_caps_create (pts_proto_caps_flag_t flags, bool request)
pa_tnc_attr_t * tcg_pts_attr_proto_caps_create_from_data (size_t length, chunk_t data, bool request)
Macro Definition Documentation
#define PTS_PROTO_CAPS_RESERVED 0x0000
Definition at line 39 of file tcg_pts_attr_proto_caps.c.
Referenced by METHOD().
#define PTS_PROTO_CAPS_SIZE 4
PTS Protocol Capabilities see section 3.7 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved |C|V|D|T|X| +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 38 of file tcg_pts_attr_proto_caps.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_proto_caps_t private_tcg_pts_attr_proto_caps_t
Definition at line 24 of file tcg_pts_attr_proto_caps.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_proto_caps_t * this)
Definition at line 83 of file tcg_pts_attr_proto_caps.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_proto_caps_t * this)
Definition at line 89 of file tcg_pts_attr_proto_caps.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_proto_caps_t * this)
Definition at line 95 of file tcg_pts_attr_proto_caps.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_proto_caps_t * this, bool noskip)
Definition at line 101 of file tcg_pts_attr_proto_caps.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_proto_caps_t * this)
Definition at line 107 of file tcg_pts_attr_proto_caps.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, flags, length, PTS_PROTO_CAPS_RESERVED, PTS_PROTO_CAPS_SIZE, value, and bio_writer_t::write_uint16.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PTS_PROTO_CAPS_SIZE);
     writer->write_uint16(writer, PTS_PROTO_CAPS_RESERVED);
     writer->write_uint16(writer, this->flags);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_proto_caps_t * this, u_int32_t * offset)
Definition at line 125 of file tcg_pts_attr_proto_caps.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, flags, NEED_MORE, PTS_PROTO_CAPS_SIZE, bio_reader_t::read_uint16, reserved, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int16_t reserved, flags;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_PROTO_CAPS_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for PTS Protocol Capabilities");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint16(reader, &reserved);
     reader->read_uint16(reader, &flags);
     this->flags = flags;
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_proto_caps_t * this, chunk_t segment)
Definition at line 151 of file tcg_pts_attr_proto_caps.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_proto_caps_t * this)
Definition at line 157 of file tcg_pts_attr_proto_caps.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_proto_caps_t * this)
Definition at line 164 of file tcg_pts_attr_proto_caps.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_proto_caps_t , get_flags , pts_proto_caps_flag_t , private_tcg_pts_attr_proto_caps_t * this)
Definition at line 174 of file tcg_pts_attr_proto_caps.c.
References flags.
 {
     return this->flags;
 }