strongSwan: imc_msg
imc_msg
imc
Classes
struct imc_msg_t
Typedefs
typedef struct imc_msg_t imc_msg_t
Functions
imc_msg_t * imc_msg_create (imc_agent_t *agent, imc_state_t *state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, pen_type_t msg_type)
imc_msg_t * imc_msg_create_as_reply (imc_msg_t *msg)
imc_msg_t * imc_msg_create_from_data (imc_agent_t *agent, imc_state_t *state, TNC_ConnectionID connection_id, TNC_MessageType msg_type, chunk_t msg)
imc_msg_t * imc_msg_create_from_long_data (imc_agent_t *agent, imc_state_t *state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, chunk_t msg)
Detailed Description
Typedef Documentation
typedef struct imc_msg_t imc_msg_t
Definition at line 26 of file imc_msg.h.
Function Documentation
imc_msg_t* imc_msg_create (imc_agent_t * agent, imc_state_t * state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, pen_type_t msg_type)
Create a wrapper for an outbound message
Parameters
agent IMC agent responsible for the message
state IMC state for the given connection ID
connection_id connection ID
src_id source IMC ID
dst_id destination IMV ID
msg_type PA-TNC message type
See header
Definition at line 597 of file imc_msg.c.
References INIT, and linked_list_create().
Referenced by imc_msg_create_as_reply(), imc_msg_create_from_long_data(), and TNC_IMC_BeginHandshake().
 {
     private_imc_msg_t *this;
     INIT(this,
         .public = {
             .get_src_id = _get_src_id,
             .get_dst_id = _get_dst_id,
             .get_msg_type = _get_msg_type,
             .send = _send_,
             .receive = _receive,
             .add_attribute = _add_attribute,
             .create_attribute_enumerator = _create_attribute_enumerator,
             .get_encoding = _get_encoding,
             .destroy = _destroy,
         },
         .connection_id = connection_id,
         .src_id = src_id,
         .dst_id = dst_id,
         .msg_type = msg_type,
         .attr_list = linked_list_create(),
         .agent = agent,
         .state = state,
     );
     return &this->public;
 }
imc_msg_t* imc_msg_create_as_reply (imc_msg_t * msg)
Create a wrapper for an outbound message based on a received message
Parameters
msg received message the reply is based on
See header
Definition at line 631 of file imc_msg.c.
References private_imc_msg_t::agent, private_imc_msg_t::connection_id, private_imc_msg_t::dst_id, imc_agent_t::get_id, imc_msg_create(), in, private_imc_msg_t::msg_type, private_imc_msg_t::src_id, private_imc_msg_t::state, and TNC_IMCID_ANY.
Referenced by receive_message().
 {
     private_imc_msg_t *in;
     TNC_UInt32 src_id;
     in = (private_imc_msg_t*)msg;
     src_id = (in->dst_id != TNC_IMCID_ANY) ?
               in->dst_id : in->agent->get_id(in->agent);
     return imc_msg_create(in->agent, in->state, in->connection_id, src_id,
                           in->src_id, in->msg_type);
 }
imc_msg_t* imc_msg_create_from_data (imc_agent_t * agent, imc_state_t * state, TNC_ConnectionID connection_id, TNC_MessageType msg_type, chunk_t msg)
Create a wrapper around message data received via the legacy IF-IMC interface
Parameters
agent IMC agent responsible for the message
state IMC state for the given connection ID
connection_id connection ID
msg_type PA-TNC message type
msg received PA-TNC message blob
See header
Definition at line 647 of file imc_msg.c.
References imc_agent_t::get_id, imc_msg_create_from_long_data(), msg, TNC_IMVID_ANY, and TNC_SUBTYPE_ANY.
Referenced by TNC_IMC_ReceiveMessage().
 {
     TNC_VendorID msg_vid;
     TNC_MessageSubtype msg_subtype;
     msg_vid = msg_type >> 8;
     msg_subtype = msg_type & TNC_SUBTYPE_ANY;
     return imc_msg_create_from_long_data(agent, state, connection_id,
                                 TNC_IMVID_ANY, agent->get_id(agent),
                                 msg_vid, msg_subtype, msg);
 }
imc_msg_t* imc_msg_create_from_long_data (imc_agent_t * agent, imc_state_t * state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, chunk_t msg)
Create a wrapper around message data received via the long IF-IMC interface
Parameters
agent IMC agent responsible for the message
state IMC state for the given connection ID
connection_id connection ID
src_id source IMV ID
dst_id destination IMC ID
msg_vid PA-TNC message vendor ID
msg_subtype PA-TNC subtype
msg received PA-TNC message blob
See header
Definition at line 666 of file imc_msg.c.
References imc_msg_create(), pa_tnc_msg_create_from_data(), and pen_type_create().
Referenced by imc_msg_create_from_data(), and TNC_IMC_ReceiveMessageLong().
 {
     private_imc_msg_t *this;
     this = (private_imc_msg_t*)imc_msg_create(agent, state,
                                         connection_id, src_id, dst_id,
                                         pen_type_create(msg_vid, msg_subtype));
     this->pa_msg = pa_tnc_msg_create_from_data(msg);
     return &this->public;
 }