strongSwan: fips_prf
fips_prf
fips_prf
Classes
struct fips_prf_t
Typedefs
typedef struct fips_prf_t fips_prf_t
Functions
fips_prf_t * fips_prf_create (pseudo_random_function_t algo)
Detailed Description
Typedef Documentation
typedef struct fips_prf_t fips_prf_t
Definition at line 24 of file fips_prf.h.
Function Documentation
fips_prf_t* fips_prf_create (pseudo_random_function_t algo)
Creates a new fips_prf_t object.
FIPS 186-2 defines G() functions used in the PRF function. It can be implemented either based on SHA1 or DES. The G() function is selected using the algo parameter.
Parameters
algo specific FIPS PRF implementation, specifies G() function
Returns
fips_prf_t object, NULL if not supported.
Definition at line 216 of file fips_prf/fips_prf.c.
References b, crypto_factory_t::create_prf, library_t::crypto, free(), g, g_sha1(), INIT, key, lib, malloc(), PRF_FIPS_DES, PRF_FIPS_SHA1_160, and PRF_KEYED_SHA1.
Referenced by METHOD().
 {
     private_fips_prf_t *this;
     INIT(this,
         .public = {
             .prf_interface = {
                 .get_bytes = _get_bytes,
                 .allocate_bytes = _allocate_bytes,
                 .get_block_size = _get_block_size,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
     );
     switch (algo)
     {
         case PRF_FIPS_SHA1_160:
         {
             this->g = g_sha1;
             this->b = 20;
             this->keyed_prf = lib->crypto->create_prf(lib->crypto, PRF_KEYED_SHA1);
             if (this->keyed_prf == NULL)
             {
                 free(this);
                 return NULL;
             }
             break;
         }
         case PRF_FIPS_DES:
             /* not implemented yet */
         default:
             free(this);
             return NULL;
     }
     this->key = malloc(this->b);
     return &this->public;
 }