strongSwan: parser
parser
encoding
Classes
struct parser_t
Typedefs
typedef struct parser_t parser_t
Functions
parser_t * parser_create (chunk_t data)
Detailed Description
Typedef Documentation
typedef struct parser_t parser_t
Definition at line 25 of file libcharon/encoding/parser.h.
Function Documentation
parser_t* parser_create (chunk_t data)
Constructor to create a parser_t object.
Parameters
data chunk of data to parse with this parser_t object
Returns
parser_t object
Definition at line 659 of file libcharon/encoding/parser.c.
References INIT, chunk_t::len, and chunk_t::ptr.
Referenced by message_create_from_packet(), METHOD(), and parse().
 {
     private_parser_t *this;
     INIT(this,
         .public = {
             .parse_payload = _parse_payload,
             .reset_context = _reset_context,
             .set_major_version = _set_major_version,
             .get_remaining_byte_count = _get_remaining_byte_count,
             .destroy = _destroy,
         },
         .input = data.ptr,
         .byte_pos = data.ptr,
         .input_roof = data.ptr + data.len,
     );
     return &this->public;
 }