strongSwan: cred_encoding
cred_encoding
credentials
Classes
struct cred_encoding_t
Typedefs
typedef struct cred_encoding_t cred_encoding_t
typedef enum cred_encoding_type_t cred_encoding_type_t
typedef enum cred_encoding_part_t cred_encoding_part_t
typedef bool(* cred_encoder_t)(cred_encoding_type_t type, chunk_t *encoding, va_list args)
Enumerations
enum cred_encoding_type_t {
KEYID_PUBKEY_INFO_SHA1 = 0, KEYID_PUBKEY_SHA1, KEYID_PGPV3, KEYID_PGPV4,
KEYID_MAX, PUBKEY_ASN1_DER, PRIVKEY_ASN1_DER, PUBKEY_SPKI_ASN1_DER,
PUBKEY_PEM, PRIVKEY_PEM, PUBKEY_PGP, PRIVKEY_PGP,
PUBKEY_DNSKEY, PUBKEY_SSHKEY, PUBKEY_RSA_MODULUS, CERT_ASN1_DER,
CERT_PEM, CERT_PGP_PKT, CRED_ENCODING_MAX
}
enum cred_encoding_part_t {
CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, CRED_PART_RSA_PRIV_EXP, CRED_PART_RSA_PRIME1,
CRED_PART_RSA_PRIME2, CRED_PART_RSA_EXP1, CRED_PART_RSA_EXP2, CRED_PART_RSA_COEFF,
CRED_PART_RSA_PUB_ASN1_DER, CRED_PART_RSA_PRIV_ASN1_DER, CRED_PART_ECDSA_PUB_ASN1_DER, CRED_PART_ECDSA_PRIV_ASN1_DER,
CRED_PART_X509_ASN1_DER, CRED_PART_X509_CRL_ASN1_DER, CRED_PART_X509_OCSP_REQ_ASN1_DER, CRED_PART_X509_OCSP_RES_ASN1_DER,
CRED_PART_X509_AC_ASN1_DER, CRED_PART_PKCS10_ASN1_DER, CRED_PART_PGP_CERT, CRED_PART_BLISS_PUB_ASN1_DER,
CRED_PART_BLISS_PRIV_ASN1_DER, CRED_PART_END
}
Functions
bool cred_encoding_args (va_list args,...)
cred_encoding_t * cred_encoding_create ()
Detailed Description
Typedef Documentation
typedef bool(* cred_encoder_t)(cred_encoding_type_t type, chunk_t *encoding, va_list args)
Credential encoder function implementing encoding/fingerprinting.
The variable argument list takes cred_encoding_part_t, followed by part specific arguments, terminated by KEY_PART_END.
Parameters
type format to encode the credential to
args list of (cred_encoding_part_t, data)
encoding encoding result, allocated
Returns
TRUE if encoding successful
Definition at line 41 of file cred_encoding.h.
typedef enum cred_encoding_part_t cred_encoding_part_t
Definition at line 26 of file cred_encoding.h.
typedef struct cred_encoding_t cred_encoding_t
Definition at line 24 of file cred_encoding.h.
typedef enum cred_encoding_type_t cred_encoding_type_t
Definition at line 25 of file cred_encoding.h.
Enumeration Type Documentation
enum cred_encoding_part_t
Parts of a credential to encode.
Enumerator
CRED_PART_RSA_MODULUS
modulus of a RSA key, n
CRED_PART_RSA_PUB_EXP
public exponent of a RSA key, e
CRED_PART_RSA_PRIV_EXP
private exponent of a RSA key, d
CRED_PART_RSA_PRIME1
prime1 a RSA key, p
CRED_PART_RSA_PRIME2
prime2 a RSA key, q
CRED_PART_RSA_EXP1
exponent1 a RSA key, exp1
CRED_PART_RSA_EXP2
exponent1 a RSA key, exp2
CRED_PART_RSA_COEFF
coefficient of RSA key, coeff
CRED_PART_RSA_PUB_ASN1_DER
a DER encoded RSA public key
CRED_PART_RSA_PRIV_ASN1_DER
a DER encoded RSA private key
CRED_PART_ECDSA_PUB_ASN1_DER
a DER encoded ECDSA public key
CRED_PART_ECDSA_PRIV_ASN1_DER
a DER encoded ECDSA private key
CRED_PART_X509_ASN1_DER
a DER encoded X509 certificate
CRED_PART_X509_CRL_ASN1_DER
a DER encoded X509 CRL
CRED_PART_X509_OCSP_REQ_ASN1_DER
a DER encoded X509 OCSP request
CRED_PART_X509_OCSP_RES_ASN1_DER
a DER encoded X509 OCSP response
CRED_PART_X509_AC_ASN1_DER
a DER encoded X509 attribute certificate
CRED_PART_PKCS10_ASN1_DER
a DER encoded PKCS10 certificate request
CRED_PART_PGP_CERT
a PGP encoded certificate
CRED_PART_BLISS_PUB_ASN1_DER
a DER encoded BLISS public key
CRED_PART_BLISS_PRIV_ASN1_DER
a DER encoded BLISS private key
CRED_PART_END
Definition at line 108 of file cred_encoding.h.
{
     CRED_PART_RSA_MODULUS,
     CRED_PART_RSA_PUB_EXP,
     CRED_PART_RSA_PRIV_EXP,
     CRED_PART_RSA_PRIME1,
     CRED_PART_RSA_PRIME2,
     CRED_PART_RSA_EXP1,
     CRED_PART_RSA_EXP2,
     CRED_PART_RSA_COEFF,
     CRED_PART_RSA_PUB_ASN1_DER,
     CRED_PART_RSA_PRIV_ASN1_DER,
     CRED_PART_ECDSA_PUB_ASN1_DER,
     CRED_PART_ECDSA_PRIV_ASN1_DER,
     CRED_PART_X509_ASN1_DER,
     CRED_PART_X509_CRL_ASN1_DER,
     CRED_PART_X509_OCSP_REQ_ASN1_DER,
     CRED_PART_X509_OCSP_RES_ASN1_DER,
     CRED_PART_X509_AC_ASN1_DER,
     CRED_PART_PKCS10_ASN1_DER,
     CRED_PART_PGP_CERT,
     CRED_PART_BLISS_PUB_ASN1_DER,
     CRED_PART_BLISS_PRIV_ASN1_DER,
     CRED_PART_END,
 };
enum cred_encoding_type_t
Encoding type of a fingerprint/credential.
Fingerprints have the KEYID_*, public keys the PUBKEY_* and private keys the PRIVKEY_* prefix.
Enumerator
KEYID_PUBKEY_INFO_SHA1
SHA1 fingerprint over subjectPublicKeyInfo
KEYID_PUBKEY_SHA1
SHA1 fingerprint over subjectPublicKey
KEYID_PGPV3
PGPv3 fingerprint
KEYID_PGPV4
PGPv4 fingerprint
KEYID_MAX
PUBKEY_ASN1_DER
PKCS#1 and similar ASN.1 key encoding
PRIVKEY_ASN1_DER
PUBKEY_SPKI_ASN1_DER
subjectPublicKeyInfo encoding
PUBKEY_PEM
PEM encoded PKCS#1 key
PRIVKEY_PEM
PUBKEY_PGP
PGP key encoding
PRIVKEY_PGP
PUBKEY_DNSKEY
DNSKEY encoding
PUBKEY_SSHKEY
SSHKEY encoding (Base64)
PUBKEY_RSA_MODULUS
RSA modulus only
CERT_ASN1_DER
ASN.1 DER encoded certificate
CERT_PEM
PEM encoded certificate
CERT_PGP_PKT
PGP Packet encoded certificate
CRED_ENCODING_MAX
Definition at line 65 of file cred_encoding.h.
{
     KEYID_PUBKEY_INFO_SHA1 = 0,
     KEYID_PUBKEY_SHA1,
     KEYID_PGPV3,
     KEYID_PGPV4,
     KEYID_MAX,
     PUBKEY_ASN1_DER,
     PRIVKEY_ASN1_DER,
     PUBKEY_SPKI_ASN1_DER,
     PUBKEY_PEM,
     PRIVKEY_PEM,
     PUBKEY_PGP,
     PRIVKEY_PGP,
     PUBKEY_DNSKEY,
     PUBKEY_SSHKEY,
     PUBKEY_RSA_MODULUS,
     CERT_ASN1_DER,
     CERT_PEM,
     CERT_PGP_PKT,
     CRED_ENCODING_MAX,
 };
Function Documentation
bool cred_encoding_args (va_list args, ...)
Helper function for cred_encoder_t implementations to parse argument list.
Credential encoder functions get a variable argument list to parse. To simplify the job, this function reads the arguments and returns chunks for each part. The argument list of this function takes a cred_encoding_part_t, followed by a data pointer receiving the value, terminated by CRED_PART_END.
Parameters
args argument list passed to credential encoder function
... list of (cred_encoding_part_t, data*)
Returns
TRUE if all parts found, FALSE otherwise
See header.
Definition at line 55 of file cred_encoding.c.
References copy(), CRED_PART_END, data, FALSE, out, and TRUE.
Referenced by build_priv(), build_pub(), build_pub_info(), build_pub_modulus(), build_public_key(), build_sha1(), build_v3_fingerprint(), and pem_encoder_encode().
 {
     va_list parts, copy;
     bool failed = FALSE;
     va_start(parts, args);
     while (!failed)
     {
         cred_encoding_part_t current, target;
         chunk_t *out, data;
         /* get the part we are looking for */
         target = va_arg(parts, cred_encoding_part_t);
         if (target == CRED_PART_END)
         {
             break;
         }
         out = va_arg(parts, chunk_t*);
         va_copy(copy, args);
         while (!failed)
         {
             current = va_arg(copy, cred_encoding_part_t);
             if (current == CRED_PART_END)
             {
                 failed = TRUE;
                 break;
             }
             data = va_arg(copy, chunk_t);
             if (current == target)
             {
                 *out = data;
                 break;
             }
         }
         va_end(copy);
     }
     va_end(parts);
     return !failed;
 }
cred_encoding_t* cred_encoding_create ()
Create a cred_encoding instance.
See header
Definition at line 255 of file cred_encoding.c.
References bool, cache(), CRED_ENCODING_MAX, destroy(), encode(), encoding, hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), INIT, linked_list_create(), rwlock_create(), RWLOCK_TYPE_DEFAULT, and type.
Referenced by library_init().
 {
     private_cred_encoding_t *this;
     cred_encoding_type_t type;
     INIT(this,
         .public = {
             .encode = (bool(*)(cred_encoding_t*, cred_encoding_type_t type, void *cache, chunk_t *encoding, ...))encode,
             .get_cache = _get_cache,
             .cache = _cache,
             .clear_cache = _clear_cache,
             .add_encoder = _add_encoder,
             .remove_encoder = _remove_encoder,
             .destroy = _destroy,
         },
         .encoders = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     for (type = 0; type < CRED_ENCODING_MAX; type++)
     {
         this->cache[type] = hashtable_create(hashtable_hash_ptr,
                                              hashtable_equals_ptr, 8);
     }
     return &this->public;
 }