strongSwan: uci_control.c File Reference
uci_control.c File Reference
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include "uci_control.h"
#include <daemon.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_uci_control_t
Macros
#define _GNU_SOURCE
#define FIFO_FILE "/var/run/charon.fifo"
Typedefs
typedef struct
private_uci_control_t private_uci_control_t
Functions
static void write_fifo (private_uci_control_t *this, char *format,...)
static void status (private_uci_control_t *this, char *name)
static void initiate (private_uci_control_t *this, char *name)
static void terminate (private_uci_control_t *this, char *name)
static void process (private_uci_control_t *this, char *message)
static job_requeue_t receive (private_uci_control_t *this)
METHOD (uci_control_t, destroy, void, private_uci_control_t *this)
uci_control_t * uci_control_create ()
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file uci_control.c.
#define FIFO_FILE "/var/run/charon.fifo"
Definition at line 31 of file uci_control.c.
Referenced by METHOD(), receive(), uci_control_create(), and write_fifo().
Typedef Documentation
typedef struct private_uci_control_t private_uci_control_t
Definition at line 34 of file uci_control.c.
Function Documentation
static void initiate (private_uci_control_t * this, char * name) static
Initiate an IKE_SA
Definition at line 137 of file uci_control.c.
References daemon_t::backends, charon, daemon_t::controller, controller_cb_empty(), peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, backend_manager_t::get_peer_cfg_by_name, child_cfg_t::get_ref, controller_t::initiate, SUCCESS, and write_fifo().
Referenced by process().
 {
     peer_cfg_t *peer_cfg;
     child_cfg_t *child_cfg;
     enumerator_t *enumerator;
     peer_cfg = charon->backends->get_peer_cfg_by_name(charon->backends, name);
     if (peer_cfg)
     {
         enumerator = peer_cfg->create_child_cfg_enumerator(peer_cfg);
         if (enumerator->enumerate(enumerator, &child_cfg) &&
             charon->controller->initiate(charon->controller, peer_cfg,
                                 child_cfg->get_ref(child_cfg),
                                 controller_cb_empty, NULL, 0, FALSE) == SUCCESS)
         {
             write_fifo(this, "connection '%s' established\n", name);
         }
         else
         {
             write_fifo(this, "establishing connection '%s' failed\n", name);
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         write_fifo(this, "no connection named '%s' found\n", name);
     }
 }
METHOD (uci_control_t , destroy , void , private_uci_control_t * this)
Definition at line 267 of file uci_control.c.
References FIFO_FILE, and free().
 {
     unlink(FIFO_FILE);
     free(this);
 }
static void process (private_uci_control_t * this, char * message) static
dispatch control request
Definition at line 196 of file uci_control.c.
References enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), initiate(), status(), streq(), terminate(), and write_fifo().
Referenced by receive().
 {
     enumerator_t* enumerator;
     enumerator = enumerator_create_token(message, " \n", "");
     if (enumerator->enumerate(enumerator, &message))
     {
         if (streq(message, "status"))
         {
             if (enumerator->enumerate(enumerator, &message))
             {
                 status(this, message);
             }
             else
             {
                 status(this, NULL);
             }
         }
         else if (streq(message, "up") &&
                  enumerator->enumerate(enumerator, &message))
         {
             initiate(this, message);
         }
         else if (streq(message, "down") &&
                  enumerator->enumerate(enumerator, &message))
         {
             terminate(this, message);
         }
         else
         {
             write_fifo(this, "usage: status [<name>] | up <name> | down <name>\n"
                        "  status format: name peer-id peer-addr tunnel(s)\n");
         }
     }
     enumerator->destroy(enumerator);
 }
static job_requeue_t receive (private_uci_control_t * this) static
read from fifo
Definition at line 236 of file uci_control.c.
References DBG1, DBG_DMN, FIFO_FILE, in, JOB_REQUEUE_FAIR, len, memset, process(), strerror, thread_cancelability(), and TRUE.
Referenced by uci_control_create().
 {
     char message[128];
     int len;
     bool oldstate;
     FILE *in;
     memset(message, 0, sizeof(message));
     oldstate = thread_cancelability(TRUE);
     in = fopen(FIFO_FILE, "r");
     thread_cancelability(oldstate);
     if (in)
     {
         len = fread(message, 1, sizeof(message) - 1, in);
         fclose(in);
         if (len > 0)
         {
             process(this, message);
         }
         else
         {
             DBG1(DBG_DMN, "reading from UCI fifo failed: %s", strerror(errno));
         }
     }
     else
     {
         DBG1(DBG_DMN, "opening UCI fifo failed: %s", strerror(errno));
     }
     return JOB_REQUEUE_FAIR;
 }
static void status (private_uci_control_t * this, char * name) static
print IKE_SA status information
Definition at line 72 of file uci_control.c.
References daemon_t::backends, charon, daemon_t::controller, ike_sa_t::create_child_sa_enumerator, controller_t::create_ike_sa_enumerator, backend_manager_t::create_peer_cfg_enumerator, child_sa_t::create_ts_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, FALSE, fprintf, peer_cfg_t::get_name, ike_sa_t::get_name, ike_sa_t::get_other_host, ike_sa_t::get_other_id, IKE_ANY, linked_list_create_from_enumerator(), list, out, streq(), TRUE, and write_fifo().
Referenced by process().
 {
     enumerator_t *configs, *sas, *children;
     linked_list_t *list;
     ike_sa_t *ike_sa;
     child_sa_t *child_sa;
     peer_cfg_t *peer_cfg;
     char buf[2048];
     FILE *out = NULL;
     configs = charon->backends->create_peer_cfg_enumerator(charon->backends,
                                             NULL, NULL, NULL, NULL, IKE_ANY);
     while (configs->enumerate(configs, &peer_cfg))
     {
         if (name && !streq(name, peer_cfg->get_name(peer_cfg)))
         {
             continue;
         }
         sas = charon->controller->create_ike_sa_enumerator(
                                                     charon->controller, TRUE);
         while (sas->enumerate(sas, &ike_sa))
         {
             if (!streq(ike_sa->get_name(ike_sa), peer_cfg->get_name(peer_cfg)))
             {
                 continue;
             }
             if (!out)
             {
                 out = fmemopen(buf, sizeof(buf), "w");
                 if (!out)
                 {
                     continue;
                 }
             }
             fprintf(out, "%-8s %-20D %-16H ", ike_sa->get_name(ike_sa),
                 ike_sa->get_other_id(ike_sa), ike_sa->get_other_host(ike_sa));
             children = ike_sa->create_child_sa_enumerator(ike_sa);
             while (children->enumerate(children, (void**)&child_sa))
             {
                 list = linked_list_create_from_enumerator(
                             child_sa->create_ts_enumerator(child_sa, FALSE));
                 fprintf(out, "%#R", list);
                 list->destroy(list);
             }
             children->destroy(children);
             fprintf(out, "\n");
         }
         sas->destroy(sas);
     }
     configs->destroy(configs);
     if (out)
     {
         fclose(out);
         write_fifo(this, "%s", buf);
     }
     else
     {
         write_fifo(this, "");
     }
 }
static void terminate (private_uci_control_t * this, char * name) static
terminate an IKE_SA
Definition at line 169 of file uci_control.c.
References charon, daemon_t::controller, controller_cb_empty(), controller_t::create_ike_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, ike_sa_t::get_name, ike_sa_t::get_unique_id, id, streq(), controller_t::terminate_ike, TRUE, and write_fifo().
Referenced by process().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     u_int id;
     enumerator = charon->controller->create_ike_sa_enumerator(
                                                     charon->controller, TRUE);
     while (enumerator->enumerate(enumerator, &ike_sa))
     {
         if (streq(name, ike_sa->get_name(ike_sa)))
         {
             id = ike_sa->get_unique_id(ike_sa);
             enumerator->destroy(enumerator);
             charon->controller->terminate_ike(charon->controller, id,
                                               controller_cb_empty, NULL, 0);
             write_fifo(this, "connection '%s' terminated\n", name);
             return;
         }
     }
     enumerator->destroy(enumerator);
     write_fifo(this, "no active connection named '%s'\n", name);
 }
static void write_fifo (private_uci_control_t * this, char * format, ...) static
write answer to fifo
Definition at line 50 of file uci_control.c.
References DBG1, DBG_CFG, FIFO_FILE, out, strerror, and vfprintf.
Referenced by initiate(), process(), status(), and terminate().
 {
     va_list args;
     FILE *out;
     out = fopen(FIFO_FILE, "w");
     if (out)
     {
         va_start(args, format);
         vfprintf(out, format, args);
         va_end(args);
         fclose(out);
     }
     else
     {
         DBG1(DBG_CFG, "writing to UCI fifo failed: %s", strerror(errno));
     }
 }