strongSwan: eap_radius_provider
eap_radius_provider
eap_radius
Classes
struct eap_radius_provider_t
Typedefs
typedef struct
eap_radius_provider_t eap_radius_provider_t
Functions
eap_radius_provider_t * eap_radius_provider_create ()
eap_radius_provider_t * eap_radius_provider_get ()
Detailed Description
Typedef Documentation
typedef struct eap_radius_provider_t eap_radius_provider_t
Definition at line 27 of file eap_radius_provider.h.
Function Documentation
eap_radius_provider_t* eap_radius_provider_create ()
Create a eap_radius_provider instance.
See header
Definition at line 508 of file eap_radius_provider.c.
References bus_t::add_listener, daemon_t::bus, charon, equals(), hash(), hashtable_create(), INIT, mutex_create(), MUTEX_TYPE_DEFAULT, and singleton.
Referenced by plugin_cb().
 {
     if (!singleton)
     {
         private_eap_radius_provider_t *this;
         INIT(this,
             .public = {
                 .provider = {
                     .acquire_address = _acquire_address,
                     .release_address = _release_address,
                     .create_attribute_enumerator = _create_attribute_enumerator,
                 },
                 .add_framed_ip = _add_framed_ip,
                 .add_attribute = _add_attribute,
                 .destroy = _destroy,
             },
             .listener = {
                 .public = {
                     .ike_updown = _ike_updown,
                     .ike_rekey = _ike_rekey,
                     .message = _message_hook,
                 },
                 .claimed = hashtable_create((hashtable_hash_t)hash,
                                         (hashtable_equals_t)equals, 32),
                 .unclaimed = hashtable_create((hashtable_hash_t)hash,
                                         (hashtable_equals_t)equals, 32),
                 .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
             },
         );
         charon->bus->add_listener(charon->bus, &this->listener.public);
         singleton = &this->public;
     }
     return singleton;
 }
eap_radius_provider_t* eap_radius_provider_get ()
Get singleton instance previously created with eap_radius_provider_create().
See header
Definition at line 549 of file eap_radius_provider.c.
References singleton.
Referenced by process_cfg_attributes().
 {
     return singleton;
 }