strongSwan: tnccs_dynamic.c File Reference
tnccs_dynamic.c File Reference
#include "tnccs_dynamic.h"
#include <tnc/tnc.h>
#include <utils/debug.h>
Classes
struct private_tnccs_dynamic_t
Typedefs
typedef struct
private_tnccs_dynamic_t private_tnccs_dynamic_t
Functions
tnccs_type_t determine_tnccs_protocol (char version)
METHOD (tls_t, process, status_t, private_tnccs_dynamic_t *this, void *buf, size_t buflen)
METHOD (tls_t, build, status_t, private_tnccs_dynamic_t *this, void *buf, size_t *buflen, size_t *msglen)
METHOD (tls_t, is_server, bool, private_tnccs_dynamic_t *this)
METHOD (tls_t, get_server_id, identification_t *, private_tnccs_dynamic_t *this)
METHOD (tls_t, set_peer_id, void, private_tnccs_dynamic_t *this, identification_t *id)
METHOD (tls_t, get_peer_id, identification_t *, private_tnccs_dynamic_t *this)
METHOD (tls_t, get_purpose, tls_purpose_t, private_tnccs_dynamic_t *this)
METHOD (tls_t, is_complete, bool, private_tnccs_dynamic_t *this)
METHOD (tls_t, get_eap_msk, chunk_t, private_tnccs_dynamic_t *this)
METHOD (tls_t, destroy, void, private_tnccs_dynamic_t *this)
METHOD (tnccs_t, get_server_ip, host_t *, private_tnccs_dynamic_t *this)
METHOD (tnccs_t, get_peer_ip, host_t *, private_tnccs_dynamic_t *this)
METHOD (tnccs_t, get_transport, tnc_ift_type_t, private_tnccs_dynamic_t *this)
METHOD (tnccs_t, set_transport, void, private_tnccs_dynamic_t *this, tnc_ift_type_t transport)
METHOD (tnccs_t, get_auth_type, u_int32_t, private_tnccs_dynamic_t *this)
METHOD (tnccs_t, set_auth_type, void, private_tnccs_dynamic_t *this, u_int32_t auth_type)
METHOD (tnccs_t, get_pdp_server, chunk_t, private_tnccs_dynamic_t *this, u_int16_t *port)
METHOD (tnccs_t, get_ref, tnccs_t *, private_tnccs_dynamic_t *this)
tnccs_t * tnccs_dynamic_create (bool is_server, identification_t *server_id, identification_t *peer_id, host_t *server_ip, host_t *peer_ip, tnc_ift_type_t transport, tnccs_cb_t cb)
Typedef Documentation
typedef struct private_tnccs_dynamic_t private_tnccs_dynamic_t
Definition at line 22 of file tnccs_dynamic.c.
Function Documentation
tnccs_type_t determine_tnccs_protocol (char version)
Determine the version of the IF-TNCCS protocol used by analyzing the first byte of the TNCCS batch received from a TNC Client according to the rules defined by section 3.5 "Interoperability with older IF-TNCCS versions" of the TCG TNC IF-TNCCS TLV Bindings Version 2.0 standard.
Definition at line 87 of file tnccs_dynamic.c.
References TNCCS_1_1, TNCCS_2_0, TNCCS_SOH, and TNCCS_UNKNOWN.
Referenced by METHOD().
 {
     switch (version)
     {
         case '\t':
         case '\n':
         case '\r':
         case ' ':
         case '<':
             return TNCCS_1_1;
         case 0x00:
             return TNCCS_SOH;
         case 0x02:
             return TNCCS_2_0;
         default:
             return TNCCS_UNKNOWN;
     }
 }
METHOD (tls_t , process , status_t , private_tnccs_dynamic_t * this, void * buf, size_t buflen)
Definition at line 106 of file tnccs_dynamic.c.
References tnccs_manager_t::create_instance, DBG1, DBG_TNC, determine_tnccs_protocol(), FAILED, tnccs_t::set_auth_type, tnccs_t::tls, tls, tnc, tnc_t::tnccs, tnccs_type_names, TRUE, and type.
 {
     tnccs_type_t type;
     tnccs_t *tnccs;
     if (!this->tls)
     {
         if (buflen == 0)
         {
             return FAILED;
         }
         type = determine_tnccs_protocol(*(char*)buf);
         DBG1(DBG_TNC, "%N protocol detected dynamically",
                        tnccs_type_names, type);
         tnccs = tnc->tnccs->create_instance(tnc->tnccs, type, TRUE,
                             this->server_id, this->peer_id, this->server_ip,
                             this->peer_ip, this->transport, this->callback);
         if (!tnccs)
         {
             DBG1(DBG_TNC, "N% protocol not supported", tnccs_type_names, type);
             return FAILED;
         }
         tnccs->set_auth_type(tnccs, this->auth_type);
         this->tls = &tnccs->tls;
     }
     return this->tls->process(this->tls, buf, buflen);
 }
METHOD (tls_t , build , status_t , private_tnccs_dynamic_t * this, void * buf, size_t * buflen, size_t * msglen)
Definition at line 135 of file tnccs_dynamic.c.
References tls.
 {
     return this->tls->build(this->tls, buf, buflen, msglen);
 }
METHOD (tls_t , is_server , bool , private_tnccs_dynamic_t * this)
Definition at line 141 of file tnccs_dynamic.c.
References TRUE.
 {
     return TRUE;
 }
METHOD (tls_t , get_server_id , identification_t * , private_tnccs_dynamic_t * this)
Definition at line 147 of file tnccs_dynamic.c.
 {
     return this->server_id;
 }
METHOD (tls_t , set_peer_id , void , private_tnccs_dynamic_t * this, identification_t * id)
Definition at line 153 of file tnccs_dynamic.c.
References DESTROY_IF, and tls.
 {
     DESTROY_IF(this->peer_id);
     this->peer_id = id->clone(id);
     if (this->tls)
     {
         this->tls->set_peer_id(this->tls, id);
     }
 }
METHOD (tls_t , get_peer_id , identification_t * , private_tnccs_dynamic_t * this)
Definition at line 164 of file tnccs_dynamic.c.
 {
     return this->peer_id;
 }
METHOD (tls_t , get_purpose , tls_purpose_t , private_tnccs_dynamic_t * this)
Definition at line 170 of file tnccs_dynamic.c.
References TLS_PURPOSE_EAP_TNC.
 {
     return TLS_PURPOSE_EAP_TNC;
 }
METHOD (tls_t , is_complete , bool , private_tnccs_dynamic_t * this)
Definition at line 176 of file tnccs_dynamic.c.
References FALSE, and tls.
 {
     return this->tls ? this->tls->is_complete(this->tls) : FALSE;
 }
METHOD (tls_t , get_eap_msk , chunk_t , private_tnccs_dynamic_t * this)
Definition at line 182 of file tnccs_dynamic.c.
References chunk_empty.
 {
     return chunk_empty;
 }
METHOD (tls_t , destroy , void , private_tnccs_dynamic_t * this)
Definition at line 188 of file tnccs_dynamic.c.
References DESTROY_IF, free(), ref_put(), and tls.
 {
     if (ref_put(&this->ref))
     {
         DESTROY_IF(this->tls);
         this->server_id->destroy(this->server_id);
         this->peer_id->destroy(this->peer_id);
         this->server_ip->destroy(this->server_ip);
         this->peer_ip->destroy(this->peer_ip);
         free(this);
     }
 }
METHOD (tnccs_t , get_server_ip , host_t * , private_tnccs_dynamic_t * this)
Definition at line 202 of file tnccs_dynamic.c.
 {
     return this->server_ip;
 }
METHOD (tnccs_t , get_peer_ip , host_t * , private_tnccs_dynamic_t * this)
Definition at line 208 of file tnccs_dynamic.c.
 {
     return this->peer_ip;
 }
METHOD (tnccs_t , get_transport , tnc_ift_type_t , private_tnccs_dynamic_t * this)
Definition at line 214 of file tnccs_dynamic.c.
 {
     return this->transport;
 }
METHOD (tnccs_t , set_transport , void , private_tnccs_dynamic_t * this, tnc_ift_type_t transport)
Definition at line 220 of file tnccs_dynamic.c.
 {
     this->transport = transport;
 }
METHOD (tnccs_t , get_auth_type , u_int32_t , private_tnccs_dynamic_t * this)
Definition at line 226 of file tnccs_dynamic.c.
 {
     return this->auth_type;
 }
METHOD (tnccs_t , set_auth_type , void , private_tnccs_dynamic_t * this, u_int32_t auth_type)
Definition at line 232 of file tnccs_dynamic.c.
 {
     this->auth_type = auth_type;
 }
METHOD (tnccs_t , get_pdp_server , chunk_t , private_tnccs_dynamic_t * this, u_int16_t * port)
Definition at line 238 of file tnccs_dynamic.c.
References tnccs_t::get_pdp_server, and tls.
 {
     tnccs_t *tnccs = (tnccs_t*)this->tls;
     return tnccs->get_pdp_server(tnccs, port);
 }
METHOD (tnccs_t , get_ref , tnccs_t * , private_tnccs_dynamic_t * this)
Definition at line 246 of file tnccs_dynamic.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }