strongSwan: test_vectors.c File Reference
test_vectors.c File Reference
#include "test_suite.h"
#include <utils/test.h>
#include <threading/thread.h>
#include <crypto/transform.h>
Functions
START_TEST (test_vectors)
END_TEST Suite * vectors_suite_create ()
Variables
static transform_type_t tfs []
Function Documentation
START_TEST (test_vectors)
Definition at line 35 of file test_vectors.c.
References alg, ck_assert_msg, crypto_factory_t::create_verify_enumerator, library_t::crypto, enumerator_t::destroy, enumerator_t::enumerate, lib, plugin, tfs, thread_cleanup_pop(), thread_cleanup_push(), transform_get_enum_names(), and TRUE.
 {
     enumerator_t *enumerator;
     char *plugin;
     bool success;
     u_int alg;
     enumerator = lib->crypto->create_verify_enumerator(lib->crypto, tfs[_i]);
     thread_cleanup_push((void*)enumerator->destroy, enumerator);
     while (enumerator->enumerate(enumerator, &alg, &plugin, &success))
     {
         ck_assert_msg(success, "test vector for %N from '%s' plugin failed",
                       transform_get_enum_names(tfs[_i]), alg, plugin);
     }
     thread_cleanup_pop(TRUE);
 }
END_TEST Suite* vectors_suite_create ()
Definition at line 54 of file test_vectors.c.
References countof, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, tcase_create, tcase_set_timeout, and tfs.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("vectors");
     tc = tcase_create("transforms");
     tcase_add_loop_test(tc, test_vectors, 0, countof(tfs));
     tcase_set_timeout(tc, 20);
     suite_add_tcase(s, tc);
     return s;
 }
Variable Documentation
transform_type_t tfs[] static
Initial value:
= {
    ENCRYPTION_ALGORITHM,
    AEAD_ALGORITHM,
    INTEGRITY_ALGORITHM,
    HASH_ALGORITHM,
    PSEUDO_RANDOM_FUNCTION,
    RANDOM_NUMBER_GENERATOR,
    DIFFIE_HELLMAN_GROUP,
}
Definition at line 25 of file test_vectors.c.
Referenced by START_TEST(), and vectors_suite_create().