strongSwan: mem_pool_t Struct Reference
mem_pool_t Struct Reference
mem_pool
#include "mem_pool.h"
Public Attributes
const char *(* get_name)(mem_pool_t *this)
host_t *(* get_base)(mem_pool_t *this)
u_int(* get_size)(mem_pool_t *this)
u_int(* get_online)(mem_pool_t *this)
u_int(* get_offline)(mem_pool_t *this)
host_t *(* acquire_address)(mem_pool_t *this, identification_t *id, host_t *requested, mem_pool_op_t operation, host_t *peer)
bool(* release_address)(mem_pool_t *this, host_t *address, identification_t *id)
enumerator_t *(* create_lease_enumerator)(mem_pool_t *this)
void(* destroy)(mem_pool_t *this)
Detailed Description
An in-memory IP address pool.
Definition at line 45 of file mem_pool.h.
Member Data Documentation
host_t*(* mem_pool_t::acquire_address)(mem_pool_t *this, identification_t *id, host_t *requested, mem_pool_op_t operation, host_t *peer)
Acquire an address for the given id from this pool.
This call is usually invoked several times: The first time to find an existing lease (MEM_POOL_EXISTING), if none found a second time to acquire a new lease (MEM_POOL_NEW), and if the pool is full once again to assign an existing offline lease (MEM_POOL_REASSIGN).
If the same identity requests a virtual IP that is already assigned to it, the peer address and port is used to check if it is the same client instance that is connecting. If this is true, the request is considered a request for a reauthentication attempt, and the same virtual IP gets assigned to the peer.
Parameters
id the id to acquire an address for
requested acquire this address, if possible
operation acquire operation to perform, see above
peer optional remote IKE address and port
Returns
the acquired address
Definition at line 102 of file mem_pool.h.
Referenced by allocate_addr(), assert_acquire(), and find_addr().
enumerator_t*(* mem_pool_t::create_lease_enumerator)(mem_pool_t *this)
Create an enumerator over the leases of this pool.
Enumerator enumerates over identification_t *id, host_t *address, bool online
Returns
enumerator
Definition at line 124 of file mem_pool.h.
Referenced by CALLBACK(), cleanup_leases(), and METHOD().
void(* mem_pool_t::destroy)(mem_pool_t *this)
Destroy a mem_pool_t instance.
Definition at line 129 of file mem_pool.h.
Referenced by METHOD(), and START_TEST().
host_t*(* mem_pool_t::get_base)(mem_pool_t *this)
Get the base (first) address of this pool.
Returns
base address, internal host
Definition at line 59 of file mem_pool.h.
Referenced by CALLBACK(), have_vips_from_pool(), merge_pool(), and METHOD().
const char*(* mem_pool_t::get_name)(mem_pool_t *this)
Get the name of this pool.
Returns
the name of this pool
Definition at line 52 of file mem_pool.h.
Referenced by allocate_addr(), CALLBACK(), find_pool(), merge_pool(), METHOD(), and pool_filter().
u_int(* mem_pool_t::get_offline)(mem_pool_t *this)
Get the number of offline leases.
Returns
the number of online leases
Definition at line 80 of file mem_pool.h.
Referenced by CALLBACK(), and pool_filter().
u_int(* mem_pool_t::get_online)(mem_pool_t *this)
Get the number of online leases.
Returns
the number of offline leases
Definition at line 73 of file mem_pool.h.
Referenced by assert_acquires_new(), CALLBACK(), merge_pool(), pool_filter(), and START_TEST().
u_int(* mem_pool_t::get_size)(mem_pool_t *this)
Get the size (i.e. number of addresses) of this pool.
Returns
the size of this pool
Definition at line 66 of file mem_pool.h.
Referenced by assert_acquires_new(), CALLBACK(), have_vips_from_pool(), merge_pool(), METHOD(), pool_filter(), and START_TEST().
bool(* mem_pool_t::release_address)(mem_pool_t *this, host_t *address, identification_t *id)
Release a previously acquired address.
Parameters
address the address to release
id the id the address was assigned to
Returns
TRUE, if the lease was found
Definition at line 113 of file mem_pool.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
mem_pool.h