strongSwan: eap_radius_accounting.c File Reference
eap_radius_accounting.c File Reference
#include "eap_radius_accounting.h"
#include "eap_radius_plugin.h"
#include <time.h>
#include <radius_message.h>
#include <radius_client.h>
#include <daemon.h>
#include <collections/array.h>
#include <collections/hashtable.h>
#include <threading/mutex.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_eap_radius_accounting_t
struct usage_t
struct sa_entry_t
struct entry_t
struct interim_data_t
Typedefs
typedef struct
private_eap_radius_accounting_t private_eap_radius_accounting_t
Enumerations
enum radius_acct_terminate_cause_t {
ACCT_CAUSE_USER_REQUEST = 1, ACCT_CAUSE_LOST_CARRIER = 2, ACCT_CAUSE_LOST_SERVICE = 3, ACCT_CAUSE_IDLE_TIMEOUT = 4,
ACCT_CAUSE_SESSION_TIMEOUT = 5, ACCT_CAUSE_ADMIN_RESET = 6, ACCT_CAUSE_ADMIN_REBOOT = 7, ACCT_CAUSE_PORT_ERROR = 8,
ACCT_CAUSE_NAS_ERROR = 9, ACCT_CAUSE_NAS_REQUEST = 10, ACCT_CAUSE_NAS_REBOOT = 11, ACCT_CAUSE_PORT_UNNEEDED = 12,
ACCT_CAUSE_PORT_PREEMPTED = 13, ACCT_CAUSE_PORT_SUSPENDED = 14, ACCT_CAUSE_SERVICE_UNAVAILABLE = 15, ACCT_CAUSE_CALLBACK = 16,
ACCT_CAUSE_USER_ERROR = 17, ACCT_CAUSE_HOST_REQUEST = 18
}
enum radius_acct_status_t {
ACCT_STATUS_START = 1, ACCT_STATUS_STOP = 2, ACCT_STATUS_INTERIM_UPDATE = 3, ACCT_STATUS_ACCOUNTING_ON = 7,
ACCT_STATUS_ACCOUNTING_OFF = 8
}
Functions
static void add_usage (usage_t *a, usage_t b)
static void sub_usage (usage_t *a, usage_t b)
static sa_entry_t * clone_sa (sa_entry_t *sa)
static void destroy_entry (entry_t *this)
static u_int hash (ike_sa_id_t *key)
static bool equals (ike_sa_id_t *a, ike_sa_id_t *b)
static int sa_sort (const void *a, const void *b, void *user)
static int sa_find (const void *a, const void *b)
static void update_sa (entry_t *entry, u_int32_t id, usage_t usage)
static void update_usage (private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa)
static array_t * collect_stats (ike_sa_t *ike_sa, usage_t *total)
static void cleanup_sas (private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, entry_t *entry)
static bool send_message (private_eap_radius_accounting_t *this, radius_message_t *request)
static void add_ike_sa_parameters (private_eap_radius_accounting_t *this, radius_message_t *message, ike_sa_t *ike_sa)
static entry_t * get_or_create_entry (private_eap_radius_accounting_t *this, ike_sa_id_t *id, u_int32_t unique)
static void schedule_interim (private_eap_radius_accounting_t *this, entry_t *entry)
void destroy_interim_data (interim_data_t *this)
static job_requeue_t send_interim (interim_data_t *data)
static bool has_vip (ike_sa_t *ike_sa)
static void send_start (private_eap_radius_accounting_t *this, ike_sa_t *ike_sa)
static void send_stop (private_eap_radius_accounting_t *this, ike_sa_t *ike_sa)
METHOD (listener_t, alert, bool, private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, alert_t alert, va_list args)
METHOD (listener_t, ike_updown, bool, private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, bool up)
METHOD (listener_t, message_hook, bool, private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (listener_t, assign_vips, bool, private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, bool assign)
METHOD (listener_t, ike_rekey, bool, private_eap_radius_accounting_t *this, ike_sa_t *old, ike_sa_t *new)
METHOD (listener_t, child_rekey, bool, private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, child_sa_t *old, child_sa_t *new)
METHOD (listener_t, children_migrate, bool, private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, ike_sa_id_t *new, u_int32_t unique)
METHOD (listener_t, child_updown, bool, private_eap_radius_accounting_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool up)
METHOD (eap_radius_accounting_t, destroy, void, private_eap_radius_accounting_t *this)
eap_radius_accounting_t * eap_radius_accounting_create ()
void eap_radius_accounting_start_interim (ike_sa_t *ike_sa, u_int32_t interval)
Variables
static
private_eap_radius_accounting_t * singleton = NULL
Typedef Documentation
typedef struct private_eap_radius_accounting_t private_eap_radius_accounting_t
Definition at line 32 of file eap_radius_accounting.c.
Enumeration Type Documentation
enum radius_acct_status_t
Accounting message status types
Enumerator
ACCT_STATUS_START
ACCT_STATUS_STOP
ACCT_STATUS_INTERIM_UPDATE
ACCT_STATUS_ACCOUNTING_ON
ACCT_STATUS_ACCOUNTING_OFF
Definition at line 196 of file eap_radius_accounting.c.
              {
     ACCT_STATUS_START = 1,
     ACCT_STATUS_STOP = 2,
     ACCT_STATUS_INTERIM_UPDATE = 3,
     ACCT_STATUS_ACCOUNTING_ON = 7,
     ACCT_STATUS_ACCOUNTING_OFF = 8,
 } radius_acct_status_t;
enum radius_acct_terminate_cause_t
Acct-Terminate-Cause
Enumerator
ACCT_CAUSE_USER_REQUEST
ACCT_CAUSE_LOST_CARRIER
ACCT_CAUSE_LOST_SERVICE
ACCT_CAUSE_IDLE_TIMEOUT
ACCT_CAUSE_SESSION_TIMEOUT
ACCT_CAUSE_ADMIN_RESET
ACCT_CAUSE_ADMIN_REBOOT
ACCT_CAUSE_PORT_ERROR
ACCT_CAUSE_NAS_ERROR
ACCT_CAUSE_NAS_REQUEST
ACCT_CAUSE_NAS_REBOOT
ACCT_CAUSE_PORT_UNNEEDED
ACCT_CAUSE_PORT_PREEMPTED
ACCT_CAUSE_PORT_SUSPENDED
ACCT_CAUSE_SERVICE_UNAVAILABLE
ACCT_CAUSE_CALLBACK
ACCT_CAUSE_USER_ERROR
ACCT_CAUSE_HOST_REQUEST
Definition at line 78 of file eap_radius_accounting.c.
              {
     ACCT_CAUSE_USER_REQUEST = 1,
     ACCT_CAUSE_LOST_CARRIER = 2,
     ACCT_CAUSE_LOST_SERVICE = 3,
     ACCT_CAUSE_IDLE_TIMEOUT = 4,
     ACCT_CAUSE_SESSION_TIMEOUT = 5,
     ACCT_CAUSE_ADMIN_RESET = 6,
     ACCT_CAUSE_ADMIN_REBOOT = 7,
     ACCT_CAUSE_PORT_ERROR = 8,
     ACCT_CAUSE_NAS_ERROR = 9,
     ACCT_CAUSE_NAS_REQUEST = 10,
     ACCT_CAUSE_NAS_REBOOT = 11,
     ACCT_CAUSE_PORT_UNNEEDED = 12,
     ACCT_CAUSE_PORT_PREEMPTED = 13,
     ACCT_CAUSE_PORT_SUSPENDED = 14,
     ACCT_CAUSE_SERVICE_UNAVAILABLE = 15,
     ACCT_CAUSE_CALLBACK = 16,
     ACCT_CAUSE_USER_ERROR = 17,
     ACCT_CAUSE_HOST_REQUEST = 18,
 } radius_acct_terminate_cause_t;
Function Documentation
static void add_ike_sa_parameters (private_eap_radius_accounting_t * this, radius_message_t * message, ike_sa_t * ike_sa) static
Add common IKE_SA parameters to RADIUS account message
Definition at line 398 of file eap_radius_accounting.c.
References radius_message_t::add, chunk_from_str, chunk_from_thing, ike_sa_t::create_virtual_ip_enumerator, data, enumerator_t::destroy, enumerator_t::enumerate, FALSE, host_t::get_address, host_t::get_family, ike_sa_t::get_my_host, ike_sa_t::get_name, ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, ike_sa_t::get_unique_id, host, MAX_RADIUS_ATTRIBUTE_SIZE, RAT_CALLED_STATION_ID, RAT_CALLING_STATION_ID, RAT_FRAMED_IP_ADDRESS, RAT_FRAMED_IPV6_ADDRESS, RAT_NAS_IP_ADDRESS, RAT_NAS_IPV6_ADDRESS, RAT_NAS_PORT, RAT_NAS_PORT_ID, RAT_NAS_PORT_TYPE, RAT_SERVICE_TYPE, RAT_USER_NAME, snprintf, value, and vip.
Referenced by send_interim(), send_start(), and send_stop().
 {
     enumerator_t *enumerator;
     host_t *vip, *host;
     char buf[MAX_RADIUS_ATTRIBUTE_SIZE + 1];
     chunk_t data;
     u_int32_t value;
     /* virtual NAS-Port-Type */
     value = htonl(5);
     message->add(message, RAT_NAS_PORT_TYPE, chunk_from_thing(value));
     /* framed ServiceType */
     value = htonl(2);
     message->add(message, RAT_SERVICE_TYPE, chunk_from_thing(value));
     value = htonl(ike_sa->get_unique_id(ike_sa));
     message->add(message, RAT_NAS_PORT, chunk_from_thing(value));
     message->add(message, RAT_NAS_PORT_ID,
                  chunk_from_str(ike_sa->get_name(ike_sa)));
     host = ike_sa->get_my_host(ike_sa);
     data = host->get_address(host);
     switch (host->get_family(host))
     {
         case AF_INET:
             message->add(message, RAT_NAS_IP_ADDRESS, data);
             break;
         case AF_INET6:
             message->add(message, RAT_NAS_IPV6_ADDRESS, data);
         default:
             break;
     }
     snprintf(buf, sizeof(buf), this->station_id_fmt, host);
     message->add(message, RAT_CALLED_STATION_ID, chunk_from_str(buf));
     host = ike_sa->get_other_host(ike_sa);
     snprintf(buf, sizeof(buf), this->station_id_fmt, host);
     message->add(message, RAT_CALLING_STATION_ID, chunk_from_str(buf));
     snprintf(buf, sizeof(buf), "%Y", ike_sa->get_other_eap_id(ike_sa));
     message->add(message, RAT_USER_NAME, chunk_from_str(buf));
     enumerator = ike_sa->create_virtual_ip_enumerator(ike_sa, FALSE);
     while (enumerator->enumerate(enumerator, &vip))
     {
         switch (vip->get_family(vip))
         {
             case AF_INET:
                 message->add(message, RAT_FRAMED_IP_ADDRESS,
                              vip->get_address(vip));
                 break;
             case AF_INET6:
                 message->add(message, RAT_FRAMED_IPV6_ADDRESS,
                              vip->get_address(vip));
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
 }
static void add_usage (usage_t * a, usage_t b) inline static
Add usage stats (modifies a)
Definition at line 112 of file eap_radius_accounting.c.
References usage_t::bytes, usage_t::packets, usage_t::received, and usage_t::sent.
Referenced by cleanup_sas(), collect_stats(), send_interim(), and send_stop().
 {
     a->bytes.sent += b.bytes.sent;
     a->bytes.received += b.bytes.received;
     a->packets.sent += b.packets.sent;
     a->packets.received += b.packets.received;
 }
static void cleanup_sas (private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, entry_t * entry) static
Cleanup cached SAs
Definition at line 323 of file eap_radius_accounting.c.
References add_usage(), array_bsearch(), array_create(), array_create_enumerator(), array_destroy_function(), array_insert(), array_remove_at(), array_sort(), ARRAY_TAIL, entry_t::cached, ike_sa_t::create_child_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, free(), child_sa_t::get_unique_id, INIT, entry_t::migrated, sa, sa_find(), sa_sort(), sub_usage(), sa_entry_t::usage, and entry_t::usage.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     sa_entry_t *sa, *found;
     array_t *sas;
     sas = array_create(0, 0);
     enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         INIT(sa,
             .id = child_sa->get_unique_id(child_sa),
         );
         array_insert(sas, ARRAY_TAIL, sa);
         array_sort(sas, sa_sort, NULL);
     }
     enumerator->destroy(enumerator);
     enumerator = array_create_enumerator(entry->cached);
     while (enumerator->enumerate(enumerator, &sa))
     {
         if (array_bsearch(sas, sa, sa_find, &found) == -1)
         {
             /* SA is gone, add its latest stats to the total for this IKE_SA
              * and remove the cache entry */
             add_usage(&entry->usage, sa->usage);
             array_remove_at(entry->cached, enumerator);
             free(sa);
         }
     }
     enumerator->destroy(enumerator);
     enumerator = array_create_enumerator(entry->migrated);
     while (enumerator->enumerate(enumerator, &sa))
     {
         if (array_bsearch(sas, sa, sa_find, &found) == -1)
         {
             /* SA is gone, subtract stats from the total for this IKE_SA */
             sub_usage(&entry->usage, sa->usage);
             array_remove_at(entry->migrated, enumerator);
             free(sa);
         }
     }
     enumerator->destroy(enumerator);
     array_destroy_function(sas, (void*)free, NULL);
 }
static sa_entry_t* clone_sa (sa_entry_t * sa) static
Clone an sa_entry_t
Definition at line 144 of file eap_radius_accounting.c.
References sa_entry_t::id, INIT, and sa_entry_t::usage.
Referenced by METHOD().
 {
     sa_entry_t *this;
     INIT(this,
         .id = sa->id,
         .usage = sa->usage,
     );
     return this;
 }
static array_t* collect_stats (ike_sa_t * ike_sa, usage_t * total) static
Collect usage stats for all CHILD_SAs of the given IKE_SA, optionally returns the total number of bytes and packets
Definition at line 283 of file eap_radius_accounting.c.
References add_usage(), array_create(), array_insert(), array_sort(), ARRAY_TAIL, usage_t::bytes, ike_sa_t::create_child_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, child_sa_t::get_unique_id, child_sa_t::get_usestats, INIT, usage_t::packets, usage_t::received, sa, sa_sort(), usage_t::sent, stats(), TRUE, usage, and sa_entry_t::usage.
Referenced by METHOD(), and send_interim().
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     array_t *stats;
     sa_entry_t *sa;
     usage_t usage;
     if (total)
     {
         *total = (usage_t){};
     }
     stats = array_create(0, 0);
     enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         INIT(sa,
             .id = child_sa->get_unique_id(child_sa),
         );
         array_insert(stats, ARRAY_TAIL, sa);
         array_sort(stats, sa_sort, NULL);
         child_sa->get_usestats(child_sa, TRUE, NULL, &usage.bytes.received,
                                &usage.packets.received);
         child_sa->get_usestats(child_sa, FALSE, NULL, &usage.bytes.sent,
                                &usage.packets.sent);
         sa->usage = usage;
         if (total)
         {
             add_usage(total, usage);
         }
     }
     enumerator->destroy(enumerator);
     return stats;
 }
static void destroy_entry (entry_t * this) static
Destroy an entry_t
Definition at line 185 of file eap_radius_accounting.c.
References array_destroy_function(), and free().
Referenced by CALLBACK(), METHOD(), and send_stop().
 {
     array_destroy_function(this->cached, (void*)free, NULL);
     array_destroy_function(this->migrated, (void*)free, NULL);
     this->id->destroy(this->id);
     free(this);
 }
void destroy_interim_data (interim_data_t * this)
Clean up interim data
Definition at line 506 of file eap_radius_accounting.c.
References free().
Referenced by schedule_interim().
 {
     this->id->destroy(this->id);
     free(this);
 }
static bool equals (ike_sa_id_t * a, ike_sa_id_t * b) static
Hashtable equals function
Definition at line 215 of file eap_radius_accounting.c.
References ike_sa_id_t::equals.
Referenced by eap_radius_accounting_create().
 {
     return a->equals(a, b);
 }
static entry_t* get_or_create_entry (private_eap_radius_accounting_t * this, ike_sa_id_t * id, u_int32_t unique) static
Get an existing or create a new entry from the locked session table
Definition at line 463 of file eap_radius_accounting.c.
References ACCT_CAUSE_USER_REQUEST, ike_sa_id_t::clone, entry_t::id, INIT, entry_t::sid, snprintf, and time_monotonic().
Referenced by eap_radius_accounting_start_interim(), METHOD(), and send_start().
 {
     entry_t *entry;
     time_t now;
     entry = this->sessions->get(this->sessions, id);
     if (!entry)
     {
         now = time_monotonic(NULL);
         INIT(entry,
             .id = id->clone(id),
             .created = now,
             .interim = {
                 .last = now,
             },
             /* default terminate cause, if none other catched */
             .cause = ACCT_CAUSE_USER_REQUEST,
         );
         snprintf(entry->sid, sizeof(entry->sid), "%u-%u", this->prefix, unique);
         this->sessions->put(this->sessions, entry->id, entry);
     }
     return entry;
 }
static bool has_vip (ike_sa_t * ike_sa) static
Check if an IKE_SA has assigned a virtual IP (to peer)
Definition at line 664 of file eap_radius_accounting.c.
References ike_sa_t::create_virtual_ip_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, and host.
Referenced by send_start().
 {
     enumerator_t *enumerator;
     host_t *host;
     bool found;
     enumerator = ike_sa->create_virtual_ip_enumerator(ike_sa, FALSE);
     found = enumerator->enumerate(enumerator, &host);
     enumerator->destroy(enumerator);
     return found;
 }
static u_int hash (ike_sa_id_t * key) static
Hashtable hash function
Definition at line 207 of file eap_radius_accounting.c.
References ike_sa_id_t::get_responder_spi.
Referenced by eap_radius_accounting_create().
 {
     return key->get_responder_spi(key);
 }
METHOD (listener_t , alert , bool , private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, alert_t alert, va_list args)
Definition at line 809 of file eap_radius_accounting.c.
References ACCT_CAUSE_LOST_SERVICE, ACCT_CAUSE_SESSION_TIMEOUT, ALERT_IKE_SA_EXPIRED, ALERT_RETRANSMIT_SEND_TIMEOUT, entry_t::cause, ike_sa_t::get_id, mutex_t::lock, mutex, TRUE, and mutex_t::unlock.
 {
     radius_acct_terminate_cause_t cause;
     entry_t *entry;
     switch (alert)
     {
         case ALERT_IKE_SA_EXPIRED:
             cause = ACCT_CAUSE_SESSION_TIMEOUT;
             break;
         case ALERT_RETRANSMIT_SEND_TIMEOUT:
             cause = ACCT_CAUSE_LOST_SERVICE;
             break;
         default:
             return TRUE;
     }
     this->mutex->lock(this->mutex);
     entry = this->sessions->get(this->sessions, ike_sa->get_id(ike_sa));
     if (entry)
     {
         entry->cause = cause;
     }
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
METHOD (listener_t , ike_updown , bool , private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 837 of file eap_radius_accounting.c.
References ike_sa_t::create_child_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, send_stop(), TRUE, and update_usage().
 {
     if (!up)
     {
         enumerator_t *enumerator;
         child_sa_t *child_sa;
         /* update usage for all children just before sending stop */
         enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
         while (enumerator->enumerate(enumerator, &child_sa))
         {
             update_usage(this, ike_sa, child_sa);
         }
         enumerator->destroy(enumerator);
         send_stop(this, ike_sa);
     }
     return TRUE;
 }
METHOD (listener_t , message_hook , bool , private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 858 of file eap_radius_accounting.c.
References message_t::get_exchange_type, message_t::get_request, ike_sa_t::get_state, ike_sa_t::get_version, IKE_AUTH, IKE_ESTABLISHED, IKEV2, send_start(), and TRUE.
 {
     /* start accounting here, virtual IP now is set */
     if (plain && ike_sa->get_state(ike_sa) == IKE_ESTABLISHED &&
         !incoming && !message->get_request(message))
     {
         if (ike_sa->get_version(ike_sa) == IKEV2 &&
             message->get_exchange_type(message) == IKE_AUTH)
         {
             send_start(this, ike_sa);
         }
     }
     return TRUE;
 }
METHOD (listener_t , assign_vips , bool , private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, bool assign)
Definition at line 875 of file eap_radius_accounting.c.
References ike_sa_t::get_version, IKEV1, send_start(), and TRUE.
 {
     /* start accounting as soon as the virtual IP is set */
     if (assign && ike_sa->get_version(ike_sa) == IKEV1)
     {
         send_start(this, ike_sa);
     }
     return TRUE;
 }
METHOD (listener_t , ike_rekey , bool , private_eap_radius_accounting_t * this, ike_sa_t * old, ike_sa_t * new)
Definition at line 886 of file eap_radius_accounting.c.
References cleanup_sas(), identification_t::clone, identification_t::destroy, destroy_entry(), ike_sa_t::get_id, entry_t::id, mutex_t::lock, mutex, schedule_interim(), TRUE, and mutex_t::unlock.
 {
     entry_t *entry;
     this->mutex->lock(this->mutex);
     entry = this->sessions->remove(this->sessions, old->get_id(old));
     if (entry)
     {
         /* update IKE_SA identifier */
         entry->id->destroy(entry->id);
         entry->id = new->get_id(new);
         entry->id = entry->id->clone(entry->id);
         /* fire new interim update job, old gets invalid */
         schedule_interim(this, entry);
         cleanup_sas(this, new, entry);
         entry = this->sessions->put(this->sessions, entry->id, entry);
         if (entry)
         {
             destroy_entry(entry);
         }
     }
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
METHOD (listener_t , child_rekey , bool , private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, child_sa_t * old, child_sa_t * new)
Definition at line 915 of file eap_radius_accounting.c.
References cleanup_sas(), ike_sa_t::get_id, mutex_t::lock, mutex, TRUE, mutex_t::unlock, and update_usage().
 {
     entry_t *entry;
     update_usage(this, ike_sa, old);
     this->mutex->lock(this->mutex);
     entry = this->sessions->get(this->sessions, ike_sa->get_id(ike_sa));
     if (entry)
     {
         cleanup_sas(this, ike_sa, entry);
     }
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
METHOD (listener_t , children_migrate , bool , private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, ike_sa_id_t * new, u_int32_t unique)
Definition at line 932 of file eap_radius_accounting.c.
References array_bsearch(), array_create_enumerator(), array_destroy_function(), array_insert_create(), array_sort(), ARRAY_TAIL, usage_t::bytes, entry_t::cached, clone_sa(), collect_stats(), enumerator_t::destroy, enumerator_t::enumerate, free(), ike_sa_t::get_id, get_or_create_entry(), sa_entry_t::id, mutex_t::lock, entry_t::migrated, mutex, usage_t::packets, usage_t::received, sa, sa_find(), sa_sort(), usage_t::sent, stats(), TRUE, mutex_t::unlock, update_sa(), and sa_entry_t::usage.
 {
     enumerator_t *enumerator;
     sa_entry_t *sa, *sa_new, *cached;
     entry_t *entry_old, *entry_new;
     array_t *stats;
     if (!new)
     {
         return TRUE;
     }
     stats = collect_stats(ike_sa, NULL);
     this->mutex->lock(this->mutex);
     entry_old = this->sessions->get(this->sessions, ike_sa->get_id(ike_sa));
     if (entry_old)
     {
         entry_new = get_or_create_entry(this, new, unique);
         enumerator = array_create_enumerator(stats);
         while (enumerator->enumerate(enumerator, &sa))
         {
             /* if the SA was already rekeyed/cached we cache it too on the new
              * SA to track it properly until it's finally gone */
             if (array_bsearch(entry_old->cached, sa, sa_find, &cached) != -1)
             {
                 sa_new = clone_sa(sa);
                 array_insert_create(&entry_new->cached, ARRAY_TAIL, sa_new);
                 array_sort(entry_new->cached, sa_sort, NULL);
             }
             /* if the SA was used, we store it to compensate on the new SA */
             if (sa->usage.bytes.sent || sa->usage.bytes.received ||
                 sa->usage.packets.sent || sa->usage.packets.received)
             {
                 sa_new = clone_sa(sa);
                 array_insert_create(&entry_new->migrated, ARRAY_TAIL, sa_new);
                 array_sort(entry_new->migrated, sa_sort, NULL);
                 /* store/update latest stats on old SA to report in Stop */
                 update_sa(entry_old, sa->id, sa->usage);
             }
         }
         enumerator->destroy(enumerator);
     }
     this->mutex->unlock(this->mutex);
     array_destroy_function(stats, (void*)free, NULL);
     return TRUE;
 }
METHOD (listener_t , child_updown , bool , private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, bool up)
Definition at line 980 of file eap_radius_accounting.c.
References ike_sa_t::get_state, IKE_ESTABLISHED, TRUE, and update_usage().
 {
     if (!up && ike_sa->get_state(ike_sa) == IKE_ESTABLISHED)
     {
         update_usage(this, ike_sa, child_sa);
     }
     return TRUE;
 }
METHOD (eap_radius_accounting_t , destroy , void , private_eap_radius_accounting_t * this)
Definition at line 991 of file eap_radius_accounting.c.
References daemon_t::bus, charon, mutex_t::destroy, free(), mutex, and bus_t::remove_listener.
 {
     charon->bus->remove_listener(charon->bus, &this->public.listener);
     singleton = NULL;
     this->mutex->destroy(this->mutex);
     this->sessions->destroy(this->sessions);
     free(this);
 }
static int sa_find (const void * a, const void * b) static
Find a cached SA
Definition at line 232 of file eap_radius_accounting.c.
References sa_sort().
Referenced by cleanup_sas(), METHOD(), send_interim(), and update_sa().
 {
     return sa_sort(a, b, NULL);
 }
static int sa_sort (const void * a, const void * b, void * user) static
Sort cached SAs
Definition at line 223 of file eap_radius_accounting.c.
References a, b, and sa_entry_t::id.
Referenced by cleanup_sas(), collect_stats(), METHOD(), sa_find(), and update_sa().
 {
     const sa_entry_t *ra = a, *rb = b;
     return ra->id - rb->id;
 }
static void schedule_interim (private_eap_radius_accounting_t * this, entry_t * entry) static
Schedule interim update for given entry
Definition at line 639 of file eap_radius_accounting.c.
References callback_job_create_with_prio(), identification_t::clone, data, destroy_interim_data(), entry_t::id, INIT, entry_t::interim, entry_t::interval, JOB_PRIO_CRITICAL, entry_t::last, lib, return_false(), scheduler_t::schedule_job_tv, library_t::scheduler, and send_interim().
Referenced by METHOD(), send_interim(), and send_start().
 {
     if (entry->interim.interval)
     {
         interim_data_t *data;
         timeval_t tv = {
             .tv_sec = entry->interim.last + entry->interim.interval,
         };
         INIT(data,
             .this = this,
             .id = entry->id->clone(entry->id),
         );
         lib->scheduler->schedule_job_tv(lib->scheduler,
             (job_t*)callback_job_create_with_prio(
                 (callback_job_cb_t)send_interim,
                 data, (void*)destroy_interim_data,
                 (callback_job_cancel_t)return_false, JOB_PRIO_CRITICAL), tv);
     }
 }
static job_requeue_t send_interim (interim_data_t * data) static
Send an interim update for entry of given IKE_SA identifier
Definition at line 515 of file eap_radius_accounting.c.
References ACCT_STATUS_INTERIM_UPDATE, radius_message_t::add, add_ike_sa_parameters(), add_usage(), array_bsearch(), array_create_enumerator(), array_destroy_function(), array_remove_at(), usage_t::bytes, entry_t::cached, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkout, chunk_create(), chunk_from_thing, collect_stats(), entry_t::created, enumerator_t::destroy, radius_message_t::destroy, eap_radius_handle_timeout(), enumerator_t::enumerate, found, free(), settings_t::get_bool, interim_data_t::id, daemon_t::ike_sa_manager, entry_t::interim, JOB_REQUEUE_NONE, entry_t::last, lib, mutex_t::lock, entry_t::migrated, mutex, library_t::ns, usage_t::packets, radius_message_create(), RAT_ACCT_INPUT_GIGAWORDS, RAT_ACCT_INPUT_OCTETS, RAT_ACCT_INPUT_PACKETS, RAT_ACCT_OUTPUT_GIGAWORDS, RAT_ACCT_OUTPUT_OCTETS, RAT_ACCT_OUTPUT_PACKETS, RAT_ACCT_SESSION_ID, RAT_ACCT_SESSION_TIME, RAT_ACCT_STATUS_TYPE, usage_t::received, RMC_ACCOUNTING_REQUEST, sa, sa_find(), schedule_interim(), send_message(), usage_t::sent, library_t::settings, entry_t::sid, stats(), sub_usage(), interim_data_t::this, time_monotonic(), TRUE, mutex_t::unlock, usage, sa_entry_t::usage, entry_t::usage, and value.
Referenced by schedule_interim().
 {
     private_eap_radius_accounting_t *this = data->this;
     usage_t usage;
     radius_message_t *message = NULL;
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     u_int32_t value;
     array_t *stats;
     sa_entry_t *sa, *found;
     ike_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager, data->id);
     if (!ike_sa)
     {
         return JOB_REQUEUE_NONE;
     }
     stats = collect_stats(ike_sa, &usage);
     charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
     /* avoid any races by returning IKE_SA before acquiring lock */
     this->mutex->lock(this->mutex);
     entry = this->sessions->get(this->sessions, data->id);
     if (entry)
     {
         entry->interim.last = time_monotonic(NULL);
         enumerator = array_create_enumerator(entry->cached);
         while (enumerator->enumerate(enumerator, &sa))
         {
             if (array_bsearch(stats, sa, sa_find, &found) != -1)
             {
                 /* SA is still around, update stats (e.g. for IKEv1 where
                  * SA might get used even after rekeying) */
                 sa->usage = found->usage;
             }
             else
             {
                 /* SA is gone, add its last stats to the total for this IKE_SA
                  * and remove the cache entry */
                 add_usage(&entry->usage, sa->usage);
                 array_remove_at(entry->cached, enumerator);
                 free(sa);
             }
         }
         enumerator->destroy(enumerator);
         enumerator = array_create_enumerator(entry->migrated);
         while (enumerator->enumerate(enumerator, &sa))
         {
             if (array_bsearch(stats, sa, sa_find, &found) != -1)
             {
                 /* SA is still around, but we have to compensate */
                 sub_usage(&usage, sa->usage);
             }
             else
             {
                 /* SA is gone, subtract stats from the total for this IKE_SA */
                 sub_usage(&entry->usage, sa->usage);
                 array_remove_at(entry->migrated, enumerator);
                 free(sa);
             }
         }
         enumerator->destroy(enumerator);
         add_usage(&usage, entry->usage);
         message = radius_message_create(RMC_ACCOUNTING_REQUEST);
         value = htonl(ACCT_STATUS_INTERIM_UPDATE);
         message->add(message, RAT_ACCT_STATUS_TYPE, chunk_from_thing(value));
         message->add(message, RAT_ACCT_SESSION_ID,
                      chunk_create(entry->sid, strlen(entry->sid)));
         add_ike_sa_parameters(this, message, ike_sa);
         value = htonl(usage.bytes.sent);
         message->add(message, RAT_ACCT_OUTPUT_OCTETS, chunk_from_thing(value));
         value = htonl(usage.bytes.sent >> 32);
         if (value)
         {
             message->add(message, RAT_ACCT_OUTPUT_GIGAWORDS,
                          chunk_from_thing(value));
         }
         value = htonl(usage.packets.sent);
         message->add(message, RAT_ACCT_OUTPUT_PACKETS, chunk_from_thing(value));
         value = htonl(usage.bytes.received);
         message->add(message, RAT_ACCT_INPUT_OCTETS, chunk_from_thing(value));
         value = htonl(usage.bytes.received >> 32);
         if (value)
         {
             message->add(message, RAT_ACCT_INPUT_GIGAWORDS,
                          chunk_from_thing(value));
         }
         value = htonl(usage.packets.received);
         message->add(message, RAT_ACCT_INPUT_PACKETS, chunk_from_thing(value));
         value = htonl(entry->interim.last - entry->created);
         message->add(message, RAT_ACCT_SESSION_TIME, chunk_from_thing(value));
         schedule_interim(this, entry);
     }
     this->mutex->unlock(this->mutex);
     array_destroy_function(stats, (void*)free, NULL);
     if (message)
     {
         if (!send_message(this, message))
         {
             if (lib->settings->get_bool(lib->settings,
                             "%s.plugins.eap-radius.accounting_close_on_timeout",
                             TRUE, lib->ns))
             {
                 eap_radius_handle_timeout(data->id);
             }
         }
         message->destroy(message);
     }
     return JOB_REQUEUE_NONE;
 }
static bool send_message (private_eap_radius_accounting_t * this, radius_message_t * request) static
Send a RADIUS message, wait for response
Definition at line 374 of file eap_radius_accounting.c.
References client(), radius_client_t::destroy, radius_message_t::destroy, eap_radius_create_client(), FALSE, radius_message_t::get_code, radius_client_t::request, response, and RMC_ACCOUNTING_RESPONSE.
Referenced by METHOD(), send_interim(), send_start(), and send_stop().
 {
     radius_message_t *response;
     radius_client_t *client;
     bool ack = FALSE;
     client = eap_radius_create_client();
     if (client)
     {
         response = client->request(client, request);
         if (response)
         {
             ack = response->get_code(response) == RMC_ACCOUNTING_RESPONSE;
             response->destroy(response);
         }
         client->destroy(client);
     }
     return ack;
 }
static void send_start (private_eap_radius_accounting_t * this, ike_sa_t * ike_sa) static
Send an accounting start message
Definition at line 680 of file eap_radius_accounting.c.
References ACCT_STATUS_START, radius_message_t::add, add_ike_sa_parameters(), chunk_create(), chunk_from_thing, DBG1, DBG_CFG, radius_message_t::destroy, eap_radius_handle_timeout(), ike_sa_t::get_id, get_or_create_entry(), settings_t::get_time, ike_sa_t::get_unique_id, has_vip(), entry_t::interim, entry_t::interval, lib, mutex_t::lock, mutex, library_t::ns, radius_message_create(), RAT_ACCT_SESSION_ID, RAT_ACCT_STATUS_TYPE, RMC_ACCOUNTING_REQUEST, schedule_interim(), send_message(), library_t::settings, entry_t::sid, entry_t::start_sent, TRUE, mutex_t::unlock, and value.
Referenced by METHOD().
 {
     radius_message_t *message;
     entry_t *entry;
     u_int32_t value;
     if (this->acct_req_vip && !has_vip(ike_sa))
     {
         return;
     }
     this->mutex->lock(this->mutex);
     entry = get_or_create_entry(this, ike_sa->get_id(ike_sa),
                                 ike_sa->get_unique_id(ike_sa));
     if (entry->start_sent)
     {
         this->mutex->unlock(this->mutex);
         return;
     }
     entry->start_sent = TRUE;
     message = radius_message_create(RMC_ACCOUNTING_REQUEST);
     value = htonl(ACCT_STATUS_START);
     message->add(message, RAT_ACCT_STATUS_TYPE, chunk_from_thing(value));
     message->add(message, RAT_ACCT_SESSION_ID,
                  chunk_create(entry->sid, strlen(entry->sid)));
     if (!entry->interim.interval)
     {
         entry->interim.interval = lib->settings->get_time(lib->settings,
                     "%s.plugins.eap-radius.accounting_interval", 0, lib->ns);
         if (entry->interim.interval)
         {
             DBG1(DBG_CFG, "scheduling RADIUS Interim-Updates every %us",
                  entry->interim.interval);
         }
     }
     schedule_interim(this, entry);
     this->mutex->unlock(this->mutex);
     add_ike_sa_parameters(this, message, ike_sa);
     if (!send_message(this, message))
     {
         eap_radius_handle_timeout(ike_sa->get_id(ike_sa));
     }
     message->destroy(message);
 }
static void send_stop (private_eap_radius_accounting_t * this, ike_sa_t * ike_sa) static
Send an account stop message
Definition at line 732 of file eap_radius_accounting.c.
References ACCT_STATUS_STOP, radius_message_t::add, add_ike_sa_parameters(), add_usage(), array_create_enumerator(), usage_t::bytes, entry_t::cached, entry_t::cause, chunk_create(), chunk_from_thing, entry_t::created, enumerator_t::destroy, radius_message_t::destroy, destroy_entry(), eap_radius_handle_timeout(), enumerator_t::enumerate, ike_sa_t::get_id, mutex_t::lock, entry_t::migrated, mutex, usage_t::packets, radius_message_create(), RAT_ACCT_INPUT_GIGAWORDS, RAT_ACCT_INPUT_OCTETS, RAT_ACCT_INPUT_PACKETS, RAT_ACCT_OUTPUT_GIGAWORDS, RAT_ACCT_OUTPUT_OCTETS, RAT_ACCT_OUTPUT_PACKETS, RAT_ACCT_SESSION_ID, RAT_ACCT_SESSION_TIME, RAT_ACCT_STATUS_TYPE, RAT_ACCT_TERMINATE_CAUSE, usage_t::received, RMC_ACCOUNTING_REQUEST, sa, send_message(), usage_t::sent, entry_t::sid, entry_t::start_sent, sub_usage(), time_monotonic(), mutex_t::unlock, sa_entry_t::usage, entry_t::usage, and value.
Referenced by METHOD().
 {
     radius_message_t *message;
     enumerator_t *enumerator;
     entry_t *entry;
     sa_entry_t *sa;
     u_int32_t value;
     this->mutex->lock(this->mutex);
     entry = this->sessions->remove(this->sessions, ike_sa->get_id(ike_sa));
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         if (!entry->start_sent)
         {   /* we tried to authenticate this peer, but never sent a start */
             destroy_entry(entry);
             return;
         }
         enumerator = array_create_enumerator(entry->cached);
         while (enumerator->enumerate(enumerator, &sa))
         {
             add_usage(&entry->usage, sa->usage);
         }
         enumerator->destroy(enumerator);
         enumerator = array_create_enumerator(entry->migrated);
         while (enumerator->enumerate(enumerator, &sa))
         {
             sub_usage(&entry->usage, sa->usage);
         }
         enumerator->destroy(enumerator);
         message = radius_message_create(RMC_ACCOUNTING_REQUEST);
         value = htonl(ACCT_STATUS_STOP);
         message->add(message, RAT_ACCT_STATUS_TYPE, chunk_from_thing(value));
         message->add(message, RAT_ACCT_SESSION_ID,
                      chunk_create(entry->sid, strlen(entry->sid)));
         add_ike_sa_parameters(this, message, ike_sa);
         value = htonl(entry->usage.bytes.sent);
         message->add(message, RAT_ACCT_OUTPUT_OCTETS, chunk_from_thing(value));
         value = htonl(entry->usage.bytes.sent >> 32);
         if (value)
         {
             message->add(message, RAT_ACCT_OUTPUT_GIGAWORDS,
                          chunk_from_thing(value));
         }
         value = htonl(entry->usage.packets.sent);
         message->add(message, RAT_ACCT_OUTPUT_PACKETS, chunk_from_thing(value));
         value = htonl(entry->usage.bytes.received);
         message->add(message, RAT_ACCT_INPUT_OCTETS, chunk_from_thing(value));
         value = htonl(entry->usage.bytes.received >> 32);
         if (value)
         {
             message->add(message, RAT_ACCT_INPUT_GIGAWORDS,
                          chunk_from_thing(value));
         }
         value = htonl(entry->usage.packets.received);
         message->add(message, RAT_ACCT_INPUT_PACKETS, chunk_from_thing(value));
         value = htonl(time_monotonic(NULL) - entry->created);
         message->add(message, RAT_ACCT_SESSION_TIME, chunk_from_thing(value));
         value = htonl(entry->cause);
         message->add(message, RAT_ACCT_TERMINATE_CAUSE, chunk_from_thing(value));
         if (!send_message(this, message))
         {
             eap_radius_handle_timeout(NULL);
         }
         message->destroy(message);
         destroy_entry(entry);
     }
 }
static void sub_usage (usage_t * a, usage_t b) inline static
Subtract usage stats (modifies a)
Definition at line 123 of file eap_radius_accounting.c.
References usage_t::bytes, usage_t::packets, usage_t::received, and usage_t::sent.
Referenced by cleanup_sas(), send_interim(), and send_stop().
 {
     a->bytes.sent -= b.bytes.sent;
     a->bytes.received -= b.bytes.received;
     a->packets.sent -= b.packets.sent;
     a->packets.received -= b.packets.received;
 }
static void update_sa (entry_t * entry, u_int32_t id, usage_t usage) static
Update or create usage counters of a cached SA
Definition at line 240 of file eap_radius_accounting.c.
References array_bsearch(), array_insert_create(), array_sort(), ARRAY_TAIL, entry_t::cached, id, sa_entry_t::id, INIT, lookup, sa, sa_find(), sa_sort(), usage, and sa_entry_t::usage.
Referenced by METHOD(), and update_usage().
 {
     sa_entry_t *sa, lookup;
     lookup.id = id;
     if (array_bsearch(entry->cached, &lookup, sa_find, &sa) == -1)
     {
         INIT(sa,
             .id = id,
         );
         array_insert_create(&entry->cached, ARRAY_TAIL, sa);
         array_sort(entry->cached, sa_sort, NULL);
     }
     sa->usage = usage;
 }
static void update_usage (private_eap_radius_accounting_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa) static
Update usage counter when a CHILD_SA rekeys/goes down
Definition at line 259 of file eap_radius_accounting.c.
References usage_t::bytes, FALSE, ike_sa_t::get_id, child_sa_t::get_unique_id, child_sa_t::get_usestats, mutex_t::lock, mutex, usage_t::packets, usage_t::received, usage_t::sent, TRUE, mutex_t::unlock, update_sa(), and usage.
Referenced by METHOD().
 {
     usage_t usage;
     entry_t *entry;
     child_sa->get_usestats(child_sa, TRUE, NULL, &usage.bytes.received,
                            &usage.packets.received);
     child_sa->get_usestats(child_sa, FALSE, NULL, &usage.bytes.sent,
                            &usage.packets.sent);
     this->mutex->lock(this->mutex);
     entry = this->sessions->get(this->sessions, ike_sa->get_id(ike_sa));
     if (entry)
     {
         update_sa(entry, child_sa->get_unique_id(child_sa), usage);
     }
     this->mutex->unlock(this->mutex);
 }
Variable Documentation
private_eap_radius_accounting_t* singleton = NULL static
Singleton instance of accounting
Definition at line 73 of file eap_radius_accounting.c.