strongSwan: ike_sa.c File Reference
ike_sa.c File Reference
#include <string.h>
#include <sys/stat.h>
#include <errno.h>
#include <time.h>
#include "ike_sa.h"
#include <library.h>
#include <hydra.h>
#include <daemon.h>
#include <collections/array.h>
#include <utils/lexparser.h>
#include <processing/jobs/retransmit_job.h>
#include <processing/jobs/delete_ike_sa_job.h>
#include <processing/jobs/send_dpd_job.h>
#include <processing/jobs/send_keepalive_job.h>
#include <processing/jobs/rekey_ike_sa_job.h>
#include <processing/jobs/retry_initiate_job.h>
#include <sa/ikev2/tasks/ike_auth_lifetime.h>
Classes
struct private_ike_sa_t
struct attribute_entry_t
struct child_enumerator_t
Typedefs
typedef struct private_ike_sa_t private_ike_sa_t
typedef struct attribute_entry_t attribute_entry_t
Functions
ENUM (ike_sa_state_names, IKE_CREATED, IKE_DESTROYING,"CREATED","CONNECTING","ESTABLISHED","PASSIVE","REKEYING","DELETING","DESTROYING",)
static time_t get_use_time (private_ike_sa_t *this, bool inbound)
METHOD (ike_sa_t, get_unique_id, u_int32_t, private_ike_sa_t *this)
METHOD (ike_sa_t, get_name, char *, private_ike_sa_t *this)
METHOD (ike_sa_t, get_statistic, u_int32_t, private_ike_sa_t *this, statistic_t kind)
METHOD (ike_sa_t, set_statistic, void, private_ike_sa_t *this, statistic_t kind, u_int32_t value)
METHOD (ike_sa_t, get_my_host, host_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, set_my_host, void, private_ike_sa_t *this, host_t *me)
METHOD (ike_sa_t, get_other_host, host_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, set_other_host, void, private_ike_sa_t *this, host_t *other)
METHOD (ike_sa_t, get_peer_cfg, peer_cfg_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, set_peer_cfg, void, private_ike_sa_t *this, peer_cfg_t *peer_cfg)
METHOD (ike_sa_t, get_auth_cfg, auth_cfg_t *, private_ike_sa_t *this, bool local)
METHOD (ike_sa_t, add_auth_cfg, void, private_ike_sa_t *this, bool local, auth_cfg_t *cfg)
METHOD (ike_sa_t, create_auth_cfg_enumerator, enumerator_t *, private_ike_sa_t *this, bool local)
static void flush_auth_cfgs (private_ike_sa_t *this)
METHOD (ike_sa_t, get_proposal, proposal_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, set_proposal, void, private_ike_sa_t *this, proposal_t *proposal)
METHOD (ike_sa_t, set_message_id, void, private_ike_sa_t *this, bool initiate, u_int32_t mid)
METHOD (ike_sa_t, send_keepalive, void, private_ike_sa_t *this)
METHOD (ike_sa_t, get_ike_cfg, ike_cfg_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, set_ike_cfg, void, private_ike_sa_t *this, ike_cfg_t *ike_cfg)
METHOD (ike_sa_t, enable_extension, void, private_ike_sa_t *this, ike_extension_t extension)
METHOD (ike_sa_t, supports_extension, bool, private_ike_sa_t *this, ike_extension_t extension)
METHOD (ike_sa_t, has_condition, bool, private_ike_sa_t *this, ike_condition_t condition)
METHOD (ike_sa_t, set_condition, void, private_ike_sa_t *this, ike_condition_t condition, bool enable)
METHOD (ike_sa_t, send_dpd, status_t, private_ike_sa_t *this)
METHOD (ike_sa_t, get_state, ike_sa_state_t, private_ike_sa_t *this)
METHOD (ike_sa_t, set_state, void, private_ike_sa_t *this, ike_sa_state_t state)
METHOD (ike_sa_t, reset, void, private_ike_sa_t *this)
METHOD (ike_sa_t, get_keymat, keymat_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, add_virtual_ip, void, private_ike_sa_t *this, bool local, host_t *ip)
METHOD (ike_sa_t, clear_virtual_ips, void, private_ike_sa_t *this, bool local)
METHOD (ike_sa_t, create_virtual_ip_enumerator, enumerator_t *, private_ike_sa_t *this, bool local)
METHOD (ike_sa_t, add_peer_address, void, private_ike_sa_t *this, host_t *host)
METHOD (ike_sa_t, create_peer_address_enumerator, enumerator_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, clear_peer_addresses, void, private_ike_sa_t *this)
METHOD (ike_sa_t, has_mapping_changed, bool, private_ike_sa_t *this, chunk_t hash)
METHOD (ike_sa_t, set_pending_updates, void, private_ike_sa_t *this, u_int32_t updates)
METHOD (ike_sa_t, get_pending_updates, u_int32_t, private_ike_sa_t *this)
METHOD (ike_sa_t, float_ports, void, private_ike_sa_t *this)
METHOD (ike_sa_t, update_hosts, void, private_ike_sa_t *this, host_t *me, host_t *other, bool force)
static void set_dscp (private_ike_sa_t *this, packet_t *packet)
METHOD (ike_sa_t, generate_message, status_t, private_ike_sa_t *this, message_t *message, packet_t **packet)
static bool filter_fragments (private_ike_sa_t *this, packet_t **fragment, packet_t **packet)
METHOD (ike_sa_t, generate_message_fragmented, status_t, private_ike_sa_t *this, message_t *message, enumerator_t **packets)
METHOD (ike_sa_t, set_kmaddress, void, private_ike_sa_t *this, host_t *local, host_t *remote)
static void resolve_hosts (private_ike_sa_t *this)
METHOD (ike_sa_t, initiate, status_t, private_ike_sa_t *this, child_cfg_t *child_cfg, u_int32_t reqid, traffic_selector_t *tsi, traffic_selector_t *tsr)
METHOD (ike_sa_t, retry_initiate, status_t, private_ike_sa_t *this)
METHOD (ike_sa_t, process_message, status_t, private_ike_sa_t *this, message_t *message)
METHOD (ike_sa_t, get_id, ike_sa_id_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, get_version, ike_version_t, private_ike_sa_t *this)
METHOD (ike_sa_t, get_my_id, identification_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, set_my_id, void, private_ike_sa_t *this, identification_t *me)
METHOD (ike_sa_t, get_other_id, identification_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, get_other_eap_id, identification_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, set_other_id, void, private_ike_sa_t *this, identification_t *other)
METHOD (ike_sa_t, add_child_sa, void, private_ike_sa_t *this, child_sa_t *child_sa)
METHOD (ike_sa_t, get_child_sa, child_sa_t *, private_ike_sa_t *this, protocol_id_t protocol, u_int32_t spi, bool inbound)
METHOD (ike_sa_t, get_child_count, int, private_ike_sa_t *this)
METHOD (enumerator_t, child_enumerate, bool, child_enumerator_t *this, child_sa_t **child_sa)
METHOD (enumerator_t, child_enumerator_destroy, void, child_enumerator_t *this)
METHOD (ike_sa_t, create_child_sa_enumerator, enumerator_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, remove_child_sa, void, private_ike_sa_t *this, enumerator_t *enumerator)
METHOD (ike_sa_t, rekey_child_sa, status_t, private_ike_sa_t *this, protocol_id_t protocol, u_int32_t spi)
METHOD (ike_sa_t, delete_child_sa, status_t, private_ike_sa_t *this, protocol_id_t protocol, u_int32_t spi, bool expired)
METHOD (ike_sa_t, destroy_child_sa, status_t, private_ike_sa_t *this, protocol_id_t protocol, u_int32_t spi)
METHOD (ike_sa_t, delete_, status_t, private_ike_sa_t *this)
METHOD (ike_sa_t, rekey, status_t, private_ike_sa_t *this)
METHOD (ike_sa_t, reauth, status_t, private_ike_sa_t *this)
static bool is_child_queued (private_ike_sa_t *this, task_queue_t queue)
METHOD (ike_sa_t, reestablish, status_t, private_ike_sa_t *this)
METHOD (ike_sa_t, retransmit, status_t, private_ike_sa_t *this, u_int32_t message_id)
METHOD (ike_sa_t, set_auth_lifetime, status_t, private_ike_sa_t *this, u_int32_t lifetime)
static bool is_current_path_valid (private_ike_sa_t *this)
static bool is_any_path_valid (private_ike_sa_t *this)
METHOD (ike_sa_t, roam, status_t, private_ike_sa_t *this, bool address)
METHOD (ike_sa_t, add_configuration_attribute, void, private_ike_sa_t *this, attribute_handler_t *handler, configuration_attribute_type_t type, chunk_t data)
static bool filter_attribute (void *null, attribute_entry_t **in, configuration_attribute_type_t *type, void *in2, chunk_t *data, void *in3, bool *handled)
METHOD (ike_sa_t, create_attribute_enumerator, enumerator_t *, private_ike_sa_t *this)
METHOD (ike_sa_t, create_task_enumerator, enumerator_t *, private_ike_sa_t *this, task_queue_t queue)
METHOD (ike_sa_t, flush_queue, void, private_ike_sa_t *this, task_queue_t queue)
METHOD (ike_sa_t, queue_task, void, private_ike_sa_t *this, task_t *task)
METHOD (ike_sa_t, inherit_pre, void, private_ike_sa_t *this, ike_sa_t *other_public)
METHOD (ike_sa_t, inherit_post, void, private_ike_sa_t *this, ike_sa_t *other_public)
METHOD (ike_sa_t, destroy, void, private_ike_sa_t *this)
ike_sa_t * ike_sa_create (ike_sa_id_t *ike_sa_id, bool initiator, ike_version_t version)
Typedef Documentation
typedef struct attribute_entry_t attribute_entry_t
Definition at line 77 of file ike_sa.c.
typedef struct private_ike_sa_t private_ike_sa_t
Definition at line 76 of file ike_sa.c.
Function Documentation
ENUM (ike_sa_state_names , IKE_CREATED , IKE_DESTROYING , "CREATED" , "CONNECTING" , "ESTABLISHED" , "PASSIVE" , "REKEYING" , "DELETING" , "DESTROYING")
static bool filter_attribute (void * null, attribute_entry_t ** in, configuration_attribute_type_t * type, void * in2, chunk_t * data, void * in3, bool * handled) static
Enumerator filter for attributes
Definition at line 2214 of file ike_sa.c.
References TRUE.
Referenced by METHOD().
 {
     *type = (*in)->type;
     *data = (*in)->data;
     *handled = (*in)->handler != NULL;
     return TRUE;
 }
static bool filter_fragments (private_ike_sa_t * this, packet_t ** fragment, packet_t ** packet) static
Definition at line 1043 of file ike_sa.c.
References packet_t::clone, set_dscp(), and TRUE.
Referenced by METHOD().
 {
     *packet = (*fragment)->clone(*fragment);
     set_dscp(this, *packet);
     return TRUE;
 }
static void flush_auth_cfgs (private_ike_sa_t * this) static
Flush the stored authentication round information
Definition at line 441 of file ike_sa.c.
References array_remove(), ARRAY_TAIL, auth_cfg_t::destroy, FALSE, and auth_cfg_t::purge.
Referenced by METHOD().
 {
     auth_cfg_t *cfg;
     this->my_auth->purge(this->my_auth, FALSE);
     this->other_auth->purge(this->other_auth, FALSE);
     while (array_remove(this->my_auths, ARRAY_TAIL, &cfg))
     {
         cfg->destroy(cfg);
     }
     while (array_remove(this->other_auths, ARRAY_TAIL, &cfg))
     {
         cfg->destroy(cfg);
     }
 }
static time_t get_use_time (private_ike_sa_t * this, bool inbound) static
get the time of the latest traffic processed by the kernel
Definition at line 298 of file ike_sa.c.
References array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, child_sa_t::get_usestats, max, STAT_INBOUND, STAT_OUTBOUND, and stats().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     time_t use_time, current;
     if (inbound)
     {
         use_time = this->stats[STAT_INBOUND];
     }
     else
     {
         use_time = this->stats[STAT_OUTBOUND];
     }
     enumerator = array_create_enumerator(this->child_sas);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         child_sa->get_usestats(child_sa, inbound, &current, NULL, NULL);
         use_time = max(use_time, current);
     }
     enumerator->destroy(enumerator);
     return use_time;
 }
static bool is_any_path_valid (private_ike_sa_t * this) static
Check if we have any path avialable for this IKE SA.
Definition at line 2086 of file ike_sa.c.
References addr, charon, DBG1, DBG_IKE, enumerator_t::destroy, host_t::destroy, enumerator_t::enumerate, FALSE, family, kernel_interface_t::get_source_addr, hydra, hydra_t::kernel_interface, daemon_t::socket, SOCKET_FAMILY_BOTH, SOCKET_FAMILY_IPV4, SOCKET_FAMILY_IPV6, SOCKET_FAMILY_NONE, src, socket_manager_t::supported_families, TRUE, and valid.
Referenced by METHOD().
 {
     bool valid = FALSE;
     enumerator_t *enumerator;
     host_t *src = NULL, *addr;
     int family = AF_UNSPEC;
     switch (charon->socket->supported_families(charon->socket))
     {
         case SOCKET_FAMILY_IPV4:
             family = AF_INET;
             break;
         case SOCKET_FAMILY_IPV6:
             family = AF_INET6;
             break;
         case SOCKET_FAMILY_BOTH:
         case SOCKET_FAMILY_NONE:
             break;
     }
     DBG1(DBG_IKE, "old path is not available anymore, try to find another");
     enumerator = create_peer_address_enumerator(this);
     while (enumerator->enumerate(enumerator, &addr))
     {
         if (family != AF_UNSPEC && addr->get_family(addr) != family)
         {
             continue;
         }
         DBG1(DBG_IKE, "looking for a route to %H ...", addr);
         src = hydra->kernel_interface->get_source_addr(
                                         hydra->kernel_interface, addr, NULL);
         if (src)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (src)
     {
         valid = TRUE;
         src->destroy(src);
     }
     return valid;
 }
static bool is_child_queued (private_ike_sa_t * this, task_queue_t queue) static
Check if tasks to create CHILD_SAs are queued in the given queue
Definition at line 1717 of file ike_sa.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, task_t::get_type, TASK_CHILD_CREATE, TASK_QUICK_MODE, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     task_t *task;
     bool found = FALSE;
     enumerator = this->task_manager->create_task_enumerator(this->task_manager,
                                                             queue);
     while (enumerator->enumerate(enumerator, &task))
     {
         if (task->get_type(task) == TASK_CHILD_CREATE ||
             task->get_type(task) == TASK_QUICK_MODE)
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static bool is_current_path_valid (private_ike_sa_t * this) static
Check if the current combination of source and destination address is still valid.
Definition at line 2066 of file ike_sa.c.
References host_t::destroy, FALSE, kernel_interface_t::get_source_addr, hydra, host_t::ip_equals, hydra_t::kernel_interface, src, TRUE, and valid.
Referenced by METHOD().
 {
     bool valid = FALSE;
     host_t *src;
     src = hydra->kernel_interface->get_source_addr(hydra->kernel_interface,
                                             this->other_host, this->my_host);
     if (src)
     {
         if (src->ip_equals(src, this->my_host))
         {
             valid = TRUE;
         }
         src->destroy(src);
     }
     return valid;
 }
METHOD (ike_sa_t , get_unique_id , u_int32_t , private_ike_sa_t * this)
Definition at line 324 of file ike_sa.c.
References unique_id.
 {
     return this->unique_id;
 }
METHOD (ike_sa_t , get_name , char * , private_ike_sa_t * this)
Definition at line 330 of file ike_sa.c.
 {
     if (this->peer_cfg)
     {
         return this->peer_cfg->get_name(this->peer_cfg);
     }
     return "(unnamed)";
 }
METHOD (ike_sa_t , get_statistic , u_int32_t , private_ike_sa_t * this, statistic_t kind)
Definition at line 340 of file ike_sa.c.
References STAT_MAX, and stats().
 {
     if (kind < STAT_MAX)
     {
         return this->stats[kind];
     }
     return 0;
 }
METHOD (ike_sa_t , set_statistic , void , private_ike_sa_t * this, statistic_t kind, u_int32_t value)
Definition at line 350 of file ike_sa.c.
References STAT_MAX, stats(), and value.
 {
     if (kind < STAT_MAX)
     {
         this->stats[kind] = value;
     }
 }
METHOD (ike_sa_t , get_my_host , host_t * , private_ike_sa_t * this)
Definition at line 359 of file ike_sa.c.
 {
     return this->my_host;
 }
METHOD (ike_sa_t , set_my_host , void , private_ike_sa_t * this, host_t * me)
Definition at line 365 of file ike_sa.c.
References DESTROY_IF, and me.
 {
     DESTROY_IF(this->my_host);
     this->my_host = me;
 }
METHOD (ike_sa_t , get_other_host , host_t * , private_ike_sa_t * this)
Definition at line 372 of file ike_sa.c.
 {
     return this->other_host;
 }
METHOD (ike_sa_t , set_other_host , void , private_ike_sa_t * this, host_t * other)
Definition at line 378 of file ike_sa.c.
References DESTROY_IF.
 {
     DESTROY_IF(this->other_host);
     this->other_host = other;
 }
METHOD (ike_sa_t , get_peer_cfg , peer_cfg_t * , private_ike_sa_t * this)
Definition at line 385 of file ike_sa.c.
 {
     return this->peer_cfg;
 }
METHOD (ike_sa_t , set_peer_cfg , void , private_ike_sa_t * this, peer_cfg_t * peer_cfg)
Definition at line 391 of file ike_sa.c.
References DESTROY_IF, peer_cfg_t::get_ike_cfg, ike_cfg_t::get_ref, and peer_cfg_t::get_ref.
 {
     peer_cfg->get_ref(peer_cfg);
     DESTROY_IF(this->peer_cfg);
     this->peer_cfg = peer_cfg;
     if (this->ike_cfg == NULL)
     {
         this->ike_cfg = peer_cfg->get_ike_cfg(peer_cfg);
         this->ike_cfg->get_ref(this->ike_cfg);
     }
 }
METHOD (ike_sa_t , get_auth_cfg , auth_cfg_t * , private_ike_sa_t * this, bool local)
Definition at line 405 of file ike_sa.c.
 {
     if (local)
     {
         return this->my_auth;
     }
     return this->other_auth;
 }
METHOD (ike_sa_t , add_auth_cfg , void , private_ike_sa_t * this, bool local, auth_cfg_t * cfg)
Definition at line 415 of file ike_sa.c.
References array_insert(), and ARRAY_TAIL.
 {
     if (local)
     {
         array_insert(this->my_auths, ARRAY_TAIL, cfg);
     }
     else
     {
         array_insert(this->other_auths, ARRAY_TAIL, cfg);
     }
 }
METHOD (ike_sa_t , create_auth_cfg_enumerator , enumerator_t * , private_ike_sa_t * this, bool local)
Definition at line 428 of file ike_sa.c.
References array_create_enumerator().
 {
     if (local)
     {
         return array_create_enumerator(this->my_auths);
     }
     return array_create_enumerator(this->other_auths);
 }
METHOD (ike_sa_t , get_proposal , proposal_t * , private_ike_sa_t * this)
Definition at line 458 of file ike_sa.c.
References proposal.
 {
     return this->proposal;
 }
METHOD (ike_sa_t , set_proposal , void , private_ike_sa_t * this, proposal_t * proposal)
Definition at line 464 of file ike_sa.c.
References proposal_t::clone, and DESTROY_IF.
 {
     DESTROY_IF(this->proposal);
     this->proposal = proposal->clone(proposal);
 }
METHOD (ike_sa_t , set_message_id , void , private_ike_sa_t * this, bool initiate, u_int32_t mid)
Definition at line 471 of file ike_sa.c.
 {
     if (initiate)
     {
         this->task_manager->reset(this->task_manager, mid, UINT_MAX);
     }
     else
     {
         this->task_manager->reset(this->task_manager, UINT_MAX, mid);
     }
 }
METHOD (ike_sa_t , send_keepalive , void , private_ike_sa_t * this)
Definition at line 484 of file ike_sa.c.
References charon, packet_t::clone, COND_NAT_HERE, data, DBG1, DBG_IKE, FALSE, get_use_time(), IKE_PASSIVE, chunk_t::len, lib, malloc(), packet_create(), chunk_t::ptr, scheduler_t::schedule_job, library_t::scheduler, send_keepalive_job_create(), sender_t::send_no_marker, daemon_t::sender, packet_t::set_data, packet_t::set_destination, packet_t::set_source, and time_monotonic().
 {
     send_keepalive_job_t *job;
     time_t last_out, now, diff;
     if (!(this->conditions & COND_NAT_HERE) || this->keepalive_interval == 0 ||
         this->state == IKE_PASSIVE)
     {   /* disable keep alives if we are not NATed anymore, or we are passive */
         return;
     }
     last_out = get_use_time(this, FALSE);
     now = time_monotonic(NULL);
     diff = now - last_out;
     if (diff >= this->keepalive_interval)
     {
         packet_t *packet;
         chunk_t data;
         packet = packet_create();
         packet->set_source(packet, this->my_host->clone(this->my_host));
         packet->set_destination(packet, this->other_host->clone(this->other_host));
         data.ptr = malloc(1);
         data.ptr[0] = 0xFF;
         data.len = 1;
         packet->set_data(packet, data);
         DBG1(DBG_IKE, "sending keep alive to %#H", this->other_host);
         charon->sender->send_no_marker(charon->sender, packet);
         diff = 0;
     }
     job = send_keepalive_job_create(this->ike_sa_id);
     lib->scheduler->schedule_job(lib->scheduler, (job_t*)job,
                                  this->keepalive_interval - diff);
 }
METHOD (ike_sa_t , get_ike_cfg , ike_cfg_t * , private_ike_sa_t * this)
Definition at line 522 of file ike_sa.c.
 {
     return this->ike_cfg;
 }
METHOD (ike_sa_t , set_ike_cfg , void , private_ike_sa_t * this, ike_cfg_t * ike_cfg)
Definition at line 528 of file ike_sa.c.
References ike_cfg_t::get_ref.
 {
     ike_cfg->get_ref(ike_cfg);
     this->ike_cfg = ike_cfg;
 }
METHOD (ike_sa_t , enable_extension , void , private_ike_sa_t * this, ike_extension_t extension)
Definition at line 535 of file ike_sa.c.
References extension.
 {
     this->extensions |= extension;
 }
METHOD (ike_sa_t , supports_extension , bool , private_ike_sa_t * this, ike_extension_t extension)
Definition at line 541 of file ike_sa.c.
References FALSE.
 {
     return (this->extensions & extension) != FALSE;
 }
METHOD (ike_sa_t , has_condition , bool , private_ike_sa_t * this, ike_condition_t condition)
Definition at line 547 of file ike_sa.c.
References FALSE.
 {
     return (this->conditions & condition) != FALSE;
 }
METHOD (ike_sa_t , set_condition , void , private_ike_sa_t * this, ike_condition_t condition, bool enable)
Definition at line 553 of file ike_sa.c.
References COND_NAT_ANY, COND_NAT_FAKE, COND_NAT_HERE, COND_NAT_THERE, DBG1, DBG_IKE, and set_condition().
 {
     if (has_condition(this, condition) != enable)
     {
         if (enable)
         {
             this->conditions |= condition;
             switch (condition)
             {
                 case COND_NAT_HERE:
                     DBG1(DBG_IKE, "local host is behind NAT, sending keep alives");
                     this->conditions |= COND_NAT_ANY;
                     send_keepalive(this);
                     break;
                 case COND_NAT_THERE:
                     DBG1(DBG_IKE, "remote host is behind NAT");
                     this->conditions |= COND_NAT_ANY;
                     break;
                 case COND_NAT_FAKE:
                     DBG1(DBG_IKE, "faking NAT situation to enforce UDP encapsulation");
                     this->conditions |= COND_NAT_ANY;
                     break;
                 default:
                     break;
             }
         }
         else
         {
             this->conditions &= ~condition;
             switch (condition)
             {
                 case COND_NAT_HERE:
                 case COND_NAT_FAKE:
                 case COND_NAT_THERE:
                     set_condition(this, COND_NAT_ANY,
                                   has_condition(this, COND_NAT_HERE) ||
                                   has_condition(this, COND_NAT_THERE) ||
                                   has_condition(this, COND_NAT_FAKE));
                     break;
                 default:
                     break;
             }
         }
     }
 }
METHOD (ike_sa_t , send_dpd , status_t , private_ike_sa_t * this)
Definition at line 600 of file ike_sa.c.
References DBG1, DBG_IKE, FALSE, get_use_time(), IKE_PASSIVE, INVALID_STATE, lib, scheduler_t::schedule_job, library_t::scheduler, send_dpd_job_create(), SUCCESS, time_monotonic(), and TRUE.
 {
     job_t *job;
     time_t diff, delay;
     bool task_queued = FALSE;
     if (this->state == IKE_PASSIVE)
     {
         return INVALID_STATE;
     }
     delay = this->peer_cfg->get_dpd(this->peer_cfg);
     if (this->task_manager->busy(this->task_manager))
     {
         /* an exchange is in the air, no need to start a DPD check */
         diff = 0;
     }
     else
     {
         /* check if there was any inbound traffic */
         time_t last_in, now;
         last_in = get_use_time(this, TRUE);
         now = time_monotonic(NULL);
         diff = now - last_in;
         if (!delay || diff >= delay)
         {
             /* too long ago, initiate dead peer detection */
             DBG1(DBG_IKE, "sending DPD request");
             this->task_manager->queue_dpd(this->task_manager);
             task_queued = TRUE;
             diff = 0;
         }
     }
     /* recheck in "interval" seconds */
     if (delay)
     {
         job = (job_t*)send_dpd_job_create(this->ike_sa_id);
         lib->scheduler->schedule_job(lib->scheduler, job, delay - diff);
     }
     if (task_queued)
     {
         return this->task_manager->initiate(this->task_manager);
     }
     return SUCCESS;
 }
METHOD (ike_sa_t , get_state , ike_sa_state_t , private_ike_sa_t * this)
Definition at line 646 of file ike_sa.c.
 {
     return this->state;
 }
METHOD (ike_sa_t , set_state , void , private_ike_sa_t * this, ike_sa_state_t state)
Definition at line 652 of file ike_sa.c.
References daemon_t::bus, charon, DBG1, DBG2, DBG_IKE, delete_ike_sa_job_create(), EXT_DPD, FALSE, get_name(), IKE_CONNECTING, IKE_ESTABLISHED, IKE_PASSIVE, ike_sa_state_names, bus_t::ike_state_change, lib, min, rekey_ike_sa_job_create(), scheduler_t::schedule_job, library_t::scheduler, STAT_DELETE, STAT_ESTABLISHED, STAT_INBOUND, STAT_REAUTH, STAT_REKEY, stats(), time_monotonic(), TRUE, and unique_id.
 {
     bool trigger_dpd = FALSE, keepalives = FALSE;
     DBG2(DBG_IKE, "IKE_SA %s[%d] state change: %N => %N",
          get_name(this), this->unique_id,
          ike_sa_state_names, this->state,
          ike_sa_state_names, state);
     switch (state)
     {
         case IKE_ESTABLISHED:
         {
             if (this->state == IKE_CONNECTING ||
                 this->state == IKE_PASSIVE)
             {
                 job_t *job;
                 u_int32_t t;
                 /* calculate rekey, reauth and lifetime */
                 this->stats[STAT_ESTABLISHED] = time_monotonic(NULL);
                 /* schedule rekeying if we have a time which is smaller than
                  * an already scheduled rekeying */
                 t = this->peer_cfg->get_rekey_time(this->peer_cfg, TRUE);
                 if (t && (this->stats[STAT_REKEY] == 0 ||
                     (this->stats[STAT_REKEY] > t + this->stats[STAT_ESTABLISHED])))
                 {
                     this->stats[STAT_REKEY] = t + this->stats[STAT_ESTABLISHED];
                     job = (job_t*)rekey_ike_sa_job_create(this->ike_sa_id, FALSE);
                     lib->scheduler->schedule_job(lib->scheduler, job, t);
                     DBG1(DBG_IKE, "scheduling rekeying in %ds", t);
                 }
                 t = this->peer_cfg->get_reauth_time(this->peer_cfg, TRUE);
                 if (t && (this->stats[STAT_REAUTH] == 0 ||
                     (this->stats[STAT_REAUTH] > t + this->stats[STAT_ESTABLISHED])))
                 {
                     this->stats[STAT_REAUTH] = t + this->stats[STAT_ESTABLISHED];
                     job = (job_t*)rekey_ike_sa_job_create(this->ike_sa_id, TRUE);
                     lib->scheduler->schedule_job(lib->scheduler, job, t);
                     DBG1(DBG_IKE, "scheduling reauthentication in %ds", t);
                 }
                 t = this->peer_cfg->get_over_time(this->peer_cfg);
                 if (this->stats[STAT_REKEY] || this->stats[STAT_REAUTH])
                 {
                     if (this->stats[STAT_REAUTH] == 0)
                     {
                         this->stats[STAT_DELETE] = this->stats[STAT_REKEY];
                     }
                     else if (this->stats[STAT_REKEY] == 0)
                     {
                         this->stats[STAT_DELETE] = this->stats[STAT_REAUTH];
                     }
                     else
                     {
                         this->stats[STAT_DELETE] = min(this->stats[STAT_REKEY],
                                                        this->stats[STAT_REAUTH]);
                     }
                     this->stats[STAT_DELETE] += t;
                     t = this->stats[STAT_DELETE] - this->stats[STAT_ESTABLISHED];
                     job = (job_t*)delete_ike_sa_job_create(this->ike_sa_id, TRUE);
                     lib->scheduler->schedule_job(lib->scheduler, job, t);
                     DBG1(DBG_IKE, "maximum IKE_SA lifetime %ds", t);
                 }
                 trigger_dpd = this->peer_cfg->get_dpd(this->peer_cfg);
                 if (trigger_dpd)
                 {
                     /* Some peers delay the DELETE after rekeying an IKE_SA.
                      * If this delay is longer than our DPD delay, we would
                      * send a DPD request here. The IKE_SA is not ready to do
                      * so yet, so prevent that. */
                     this->stats[STAT_INBOUND] = this->stats[STAT_ESTABLISHED];
                 }
                 if (this->state == IKE_PASSIVE)
                 {
                     keepalives = TRUE;
                 }
             }
             break;
         }
         default:
             break;
     }
     charon->bus->ike_state_change(charon->bus, &this->public, state);
     this->state = state;
     if (trigger_dpd)
     {
         if (supports_extension(this, EXT_DPD))
         {
             send_dpd(this);
         }
         else
         {
             DBG1(DBG_IKE, "DPD not supported by peer, disabled");
         }
     }
     if (keepalives)
     {
         send_keepalive(this);
     }
 }
METHOD (ike_sa_t , reset , void , private_ike_sa_t * this)
Definition at line 756 of file ike_sa.c.
References flush_auth_cfgs(), IKE_CREATED, keymat_create(), set_state(), and version.
 {
     /*  the responder ID is reset, as peer may choose another one */
     if (this->ike_sa_id->is_initiator(this->ike_sa_id))
     {
         this->ike_sa_id->set_responder_spi(this->ike_sa_id, 0);
     }
     set_state(this, IKE_CREATED);
     flush_auth_cfgs(this);
     this->keymat->destroy(this->keymat);
     this->keymat = keymat_create(this->version,
                             this->ike_sa_id->is_initiator(this->ike_sa_id));
     this->task_manager->reset(this->task_manager, 0, 0);
 }
METHOD (ike_sa_t , get_keymat , keymat_t * , private_ike_sa_t * this)
Definition at line 776 of file ike_sa.c.
 {
     return this->keymat;
 }
METHOD (ike_sa_t , add_virtual_ip , void , private_ike_sa_t * this, bool local, host_t * ip)
Definition at line 782 of file ike_sa.c.
References kernel_interface_t::add_ip, array_insert_create(), ARRAY_TAIL, host_t::clone, DBG1, DBG_IKE, free(), kernel_interface_t::get_interface, hydra, hydra_t::kernel_interface, and SUCCESS.
 {
     if (local)
     {
         char *iface;
         if (hydra->kernel_interface->get_interface(hydra->kernel_interface,
                                                    this->my_host, &iface))
         {
             DBG1(DBG_IKE, "installing new virtual IP %H", ip);
             if (hydra->kernel_interface->add_ip(hydra->kernel_interface,
                                                 ip, -1, iface) == SUCCESS)
             {
                 array_insert_create(&this->my_vips, ARRAY_TAIL, ip->clone(ip));
             }
             else
             {
                 DBG1(DBG_IKE, "installing virtual IP %H failed", ip);
             }
             free(iface);
         }
         else
         {
             DBG1(DBG_IKE, "looking up interface for virtual IP %H failed", ip);
         }
     }
     else
     {
         array_insert_create(&this->other_vips, ARRAY_TAIL, ip->clone(ip));
     }
 }
METHOD (ike_sa_t , clear_virtual_ips , void , private_ike_sa_t * this, bool local)
Definition at line 816 of file ike_sa.c.
References array_count(), ARRAY_HEAD, array_remove(), bus_t::assign_vips, daemon_t::bus, charon, kernel_interface_t::del_ip, host_t::destroy, FALSE, hydra, hydra_t::kernel_interface, TRUE, and vip.
 {
     array_t *vips;
     host_t *vip;
     vips = local ? this->my_vips : this->other_vips;
     if (!local && array_count(vips))
     {
         charon->bus->assign_vips(charon->bus, &this->public, FALSE);
     }
     while (array_remove(vips, ARRAY_HEAD, &vip))
     {
         if (local)
         {
             hydra->kernel_interface->del_ip(hydra->kernel_interface,
                                             vip, -1, TRUE);
         }
         vip->destroy(vip);
     }
 }
METHOD (ike_sa_t , create_virtual_ip_enumerator , enumerator_t * , private_ike_sa_t * this, bool local)
Definition at line 838 of file ike_sa.c.
References array_create_enumerator().
 {
     if (local)
     {
         return array_create_enumerator(this->my_vips);
     }
     return array_create_enumerator(this->other_vips);
 }
METHOD (ike_sa_t , add_peer_address , void , private_ike_sa_t * this, host_t * host)
Definition at line 848 of file ike_sa.c.
References array_insert_create(), and ARRAY_TAIL.
 {
     array_insert_create(&this->peer_addresses, ARRAY_TAIL, host);
 }
METHOD (ike_sa_t , create_peer_address_enumerator , enumerator_t * , private_ike_sa_t * this)
Definition at line 854 of file ike_sa.c.
References array_create_enumerator(), and enumerator_create_single().
 {
     if (this->peer_addresses)
     {
         return array_create_enumerator(this->peer_addresses);
     }
     /* in case we don't have MOBIKE */
     return enumerator_create_single(this->other_host, NULL);
 }
METHOD (ike_sa_t , clear_peer_addresses , void , private_ike_sa_t * this)
Definition at line 865 of file ike_sa.c.
References array_destroy_offset(), and destroy().
 {
     array_destroy_offset(this->peer_addresses, offsetof(host_t, destroy));
     this->peer_addresses = NULL;
 }
METHOD (ike_sa_t , has_mapping_changed , bool , private_ike_sa_t * this, chunk_t hash)
Definition at line 872 of file ike_sa.c.
References chunk_clone, chunk_equals(), FALSE, free(), and TRUE.
 {
     if (this->nat_detection_dest.ptr == NULL)
     {
         this->nat_detection_dest = chunk_clone(hash);
         return FALSE;
     }
     if (chunk_equals(hash, this->nat_detection_dest))
     {
         return FALSE;
     }
     free(this->nat_detection_dest.ptr);
     this->nat_detection_dest = chunk_clone(hash);
     return TRUE;
 }
METHOD (ike_sa_t , set_pending_updates , void , private_ike_sa_t * this, u_int32_t updates)
Definition at line 889 of file ike_sa.c.
 {
     this->pending_updates = updates;
 }
METHOD (ike_sa_t , get_pending_updates , u_int32_t , private_ike_sa_t * this)
Definition at line 895 of file ike_sa.c.
 {
     return this->pending_updates;
 }
METHOD (ike_sa_t , float_ports , void , private_ike_sa_t * this)
Definition at line 901 of file ike_sa.c.
References charon, FALSE, socket_manager_t::get_port, IKEV2_NATT_PORT, IKEV2_UDP_PORT, daemon_t::socket, and TRUE.
 {
     /* do not switch if we have a custom port from MOBIKE/NAT */
     if (this->my_host->get_port(this->my_host) ==
             charon->socket->get_port(charon->socket, FALSE))
     {
         this->my_host->set_port(this->my_host,
                                 charon->socket->get_port(charon->socket, TRUE));
     }
     if (this->other_host->get_port(this->other_host) == IKEV2_UDP_PORT)
     {
         this->other_host->set_port(this->other_host, IKEV2_NATT_PORT);
     }
 }
METHOD (ike_sa_t , update_hosts , void , private_ike_sa_t * this, host_t * me, host_t * other, bool force)
Definition at line 917 of file ike_sa.c.
References child_sa_manager_t::add, array_create_enumerator(), daemon_t::bus, charon, daemon_t::child_sa_manager, host_t::clone, COND_NAT_ANY, COND_NAT_HERE, COND_NAT_THERE, COND_ORIGINAL_INITIATOR, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, host_t::equals, FALSE, child_sa_t::get_protocol, child_sa_t::get_spi, bus_t::ike_update, linked_list_create_from_enumerator(), NOT_SUPPORTED, child_sa_manager_t::remove, TRUE, update(), and child_sa_t::update.
 {
     bool update = FALSE;
     if (me == NULL)
     {
         me = this->my_host;
     }
     if (other == NULL)
     {
         other = this->other_host;
     }
     /* apply hosts on first received message */
     if (this->my_host->is_anyaddr(this->my_host) ||
         this->other_host->is_anyaddr(this->other_host))
     {
         set_my_host(this, me->clone(me));
         set_other_host(this, other->clone(other));
         update = TRUE;
     }
     else
     {
         /* update our address in any case */
         if (force && !me->equals(me, this->my_host))
         {
             charon->bus->ike_update(charon->bus, &this->public, TRUE, me);
             set_my_host(this, me->clone(me));
             update = TRUE;
         }
         if (!other->equals(other, this->other_host) &&
             (force || has_condition(this, COND_NAT_THERE)))
         {
             /* only update other's address if we are behind a static NAT,
              * which we assume is the case if we are not initiator */
             if (force ||
                 (!has_condition(this, COND_NAT_HERE) ||
                  !has_condition(this, COND_ORIGINAL_INITIATOR)))
             {
                 charon->bus->ike_update(charon->bus, &this->public, FALSE, other);
                 set_other_host(this, other->clone(other));
                 update = TRUE;
             }
         }
     }
     /* update all associated CHILD_SAs, if required */
     if (update)
     {
         enumerator_t *enumerator;
         child_sa_t *child_sa;
         linked_list_t *vips;
         vips = linked_list_create_from_enumerator(
                                     array_create_enumerator(this->my_vips));
         enumerator = array_create_enumerator(this->child_sas);
         while (enumerator->enumerate(enumerator, &child_sa))
         {
             charon->child_sa_manager->remove(charon->child_sa_manager, child_sa);
             charon->child_sa_manager->add(charon->child_sa_manager,
                                           child_sa, &this->public);
             if (child_sa->update(child_sa, this->my_host, this->other_host,
                     vips, has_condition(this, COND_NAT_ANY)) == NOT_SUPPORTED)
             {
                 this->public.rekey_child_sa(&this->public,
                         child_sa->get_protocol(child_sa),
                         child_sa->get_spi(child_sa, TRUE));
             }
         }
         enumerator->destroy(enumerator);
         vips->destroy(vips);
     }
 }
METHOD (ike_sa_t , generate_message , status_t , private_ike_sa_t * this, message_t * message, packet_t ** packet)
Definition at line 1020 of file ike_sa.c.
References daemon_t::bus, charon, FALSE, message_t::generate, message_t::get_packet, message_t::is_encoded, bus_t::message, set_dscp(), message_t::set_ike_sa_id, STAT_OUTBOUND, stats(), status, SUCCESS, time_monotonic(), and TRUE.
 {
     status_t status;
     if (message->is_encoded(message))
     {   /* already encoded in task, but set DSCP value */
         *packet = message->get_packet(message);
         set_dscp(this, *packet);
         return SUCCESS;
     }
     this->stats[STAT_OUTBOUND] = time_monotonic(NULL);
     message->set_ike_sa_id(message, this->ike_sa_id);
     charon->bus->message(charon->bus, message, FALSE, TRUE);
     status = message->generate(message, this->keymat, packet);
     if (status == SUCCESS)
     {
         set_dscp(this, *packet);
         charon->bus->message(charon->bus, message, FALSE, FALSE);
     }
     return status;
 }
METHOD (ike_sa_t , generate_message_fragmented , status_t , private_ike_sa_t * this, message_t * message, enumerator_t ** packets)
Definition at line 1051 of file ike_sa.c.
References daemon_t::bus, charon, enumerator_create_filter(), enumerator_create_single(), EXT_IKE_FRAGMENTATION, EXT_MS_WINDOWS, FALSE, filter_fragments(), message_t::fragment, FRAGMENTATION_FORCE, FRAGMENTATION_YES, generate_message(), message_t::get_payload, IKEV1, bus_t::message, PLV1_CERTIFICATE, message_t::set_ike_sa_id, STAT_OUTBOUND, stats(), status, SUCCESS, time_monotonic(), TRUE, and version.
 {
     enumerator_t *fragments;
     packet_t *packet;
     status_t status;
     bool use_frags = FALSE;
     if (this->ike_cfg)
     {
         switch (this->ike_cfg->fragmentation(this->ike_cfg))
         {
             case FRAGMENTATION_FORCE:
                 use_frags = TRUE;
                 break;
             case FRAGMENTATION_YES:
                 use_frags = supports_extension(this, EXT_IKE_FRAGMENTATION);
                 if (use_frags && this->version == IKEV1 &&
                     supports_extension(this, EXT_MS_WINDOWS))
                 {
                     /* It seems Windows 7 and 8 peers only accept proprietary
                      * fragmented messages if they expect certificates. */
                     use_frags = message->get_payload(message,
                                                      PLV1_CERTIFICATE) != NULL;
                 }
                 break;
             default:
                 break;
         }
     }
     if (!use_frags)
     {
         status = generate_message(this, message, &packet);
         if (status != SUCCESS)
         {
             return status;
         }
         *packets = enumerator_create_single(packet, NULL);
         return SUCCESS;
     }
     this->stats[STAT_OUTBOUND] = time_monotonic(NULL);
     message->set_ike_sa_id(message, this->ike_sa_id);
     charon->bus->message(charon->bus, message, FALSE, TRUE);
     status = message->fragment(message, this->keymat, this->fragment_size,
                                &fragments);
     if (status == SUCCESS)
     {
         charon->bus->message(charon->bus, message, FALSE, FALSE);
         *packets = enumerator_create_filter(fragments, (void*)filter_fragments,
                                             this, NULL);
     }
     return status;
 }
METHOD (ike_sa_t , set_kmaddress , void , private_ike_sa_t * this, host_t * local, host_t * remote)
Definition at line 1106 of file ike_sa.c.
References host_t::clone, and DESTROY_IF.
 {
     DESTROY_IF(this->local_host);
     DESTROY_IF(this->remote_host);
     this->local_host = local->clone(local);
     this->remote_host = remote->clone(remote);
 }
METHOD (ike_sa_t , initiate , status_t , private_ike_sa_t * this, child_cfg_t * child_cfg, u_int32_t reqid, traffic_selector_t * tsi, traffic_selector_t * tsr)
Definition at line 1286 of file ike_sa.c.
References addr, bus_t::alert, ALERT_PEER_ADDR_FAILED, daemon_t::bus, charon, COND_ORIGINAL_INITIATOR, DBG1, DBG_IKE, DESTROY_IF, DESTROY_ME, FALSE, IKE_CREATED, IKE_ESTABLISHED, initiate_mediation_job_create(), lib, library_t::processor, processor_t::queue_job, resolve_hosts(), retry_initiate_job_create(), scheduler_t::schedule_job, library_t::scheduler, set_condition(), set_state(), SUCCESS, and TRUE.
 {
     bool defer_initiate = FALSE;
     if (this->state == IKE_CREATED)
     {
         if (this->my_host->is_anyaddr(this->my_host) ||
             this->other_host->is_anyaddr(this->other_host))
         {
             resolve_hosts(this);
         }
         if (this->other_host->is_anyaddr(this->other_host)
 #ifdef ME
             && !this->peer_cfg->get_mediated_by(this->peer_cfg)
 #endif /* ME */
             )
         {
             char *addr;
             addr = this->ike_cfg->get_other_addr(this->ike_cfg);
             if (!this->retry_initiate_interval)
             {
                 DBG1(DBG_IKE, "unable to resolve %s, initiate aborted",
                      addr);
                 DESTROY_IF(child_cfg);
                 charon->bus->alert(charon->bus, ALERT_PEER_ADDR_FAILED);
                 return DESTROY_ME;
             }
             DBG1(DBG_IKE, "unable to resolve %s, retrying in %ds",
                  addr, this->retry_initiate_interval);
             defer_initiate = TRUE;
         }
         set_condition(this, COND_ORIGINAL_INITIATOR, TRUE);
         this->task_manager->queue_ike(this->task_manager);
     }
 #ifdef ME
     if (this->peer_cfg->is_mediation(this->peer_cfg))
     {
         if (this->state == IKE_ESTABLISHED)
         {
             /* mediation connection is already established, retrigger state
              * change to notify bus listeners */
             DBG1(DBG_IKE, "mediation connection is already up");
             set_state(this, IKE_ESTABLISHED);
         }
         DESTROY_IF(child_cfg);
     }
     else
 #endif /* ME */
     if (child_cfg)
     {
         /* normal IKE_SA with CHILD_SA */
         this->task_manager->queue_child(this->task_manager, child_cfg, reqid,
                                         tsi, tsr);
 #ifdef ME
         if (this->peer_cfg->get_mediated_by(this->peer_cfg))
         {
             /* mediated connection, initiate mediation process */
             job_t *job = (job_t*)initiate_mediation_job_create(this->ike_sa_id);
             lib->processor->queue_job(lib->processor, job);
             return SUCCESS;
         }
 #endif /* ME */
     }
     if (defer_initiate)
     {
         if (!this->retry_initiate_queued)
         {
             job_t *job = (job_t*)retry_initiate_job_create(this->ike_sa_id);
             lib->scheduler->schedule_job(lib->scheduler, (job_t*)job,
                                          this->retry_initiate_interval);
             this->retry_initiate_queued = TRUE;
         }
         return SUCCESS;
     }
     this->retry_initiate_queued = FALSE;
     return this->task_manager->initiate(this->task_manager);
 }
METHOD (ike_sa_t , retry_initiate , status_t , private_ike_sa_t * this)
Definition at line 1371 of file ike_sa.c.
References FALSE, initiate(), and SUCCESS.
 {
     if (this->retry_initiate_queued)
     {
         this->retry_initiate_queued = FALSE;
         return initiate(this, NULL, 0, NULL, NULL);
     }
     return SUCCESS;
 }
METHOD (ike_sa_t , process_message , status_t , private_ike_sa_t * this, message_t * message)
Definition at line 1382 of file ike_sa.c.
References DBG1, DBG_IKE, exchange_type_names, FAILED, FALSE, flush_auth_cfgs(), message_t::get_exchange_type, message_t::get_major_version, IKE_ESTABLISHED, IKE_PASSIVE, ike_version_names, status, and version.
 {
     status_t status;
     if (this->state == IKE_PASSIVE)
     {   /* do not handle messages in passive state */
         return FAILED;
     }
     if (message->get_major_version(message) != this->version)
     {
         DBG1(DBG_IKE, "ignoring %N IKEv%u exchange on %N SA",
              exchange_type_names, message->get_exchange_type(message),
              message->get_major_version(message),
              ike_version_names, this->version);
         /* TODO-IKEv1: fall back to IKEv1 if we receive an IKEv1
          * INVALID_MAJOR_VERSION on an IKEv2 SA. */
         return FAILED;
     }
     status = this->task_manager->process_message(this->task_manager, message);
     if (this->flush_auth_cfg && this->state == IKE_ESTABLISHED)
     {
         /* authentication completed */
         this->flush_auth_cfg = FALSE;
         flush_auth_cfgs(this);
     }
     return status;
 }
METHOD (ike_sa_t , get_id , ike_sa_id_t * , private_ike_sa_t * this)
Definition at line 1411 of file ike_sa.c.
 {
     return this->ike_sa_id;
 }
METHOD (ike_sa_t , get_version , ike_version_t , private_ike_sa_t * this)
Definition at line 1417 of file ike_sa.c.
References version.
 {
     return this->version;
 }
METHOD (ike_sa_t , get_my_id , identification_t * , private_ike_sa_t * this)
Definition at line 1423 of file ike_sa.c.
 {
     return this->my_id;
 }
METHOD (ike_sa_t , set_my_id , void , private_ike_sa_t * this, identification_t * me)
Definition at line 1429 of file ike_sa.c.
References DESTROY_IF, and me.
 {
     DESTROY_IF(this->my_id);
     this->my_id = me;
 }
METHOD (ike_sa_t , get_other_id , identification_t * , private_ike_sa_t * this)
Definition at line 1436 of file ike_sa.c.
 {
     return this->other_id;
 }
METHOD (ike_sa_t , get_other_eap_id , identification_t * , private_ike_sa_t * this)
Definition at line 1442 of file ike_sa.c.
References array_create_enumerator(), AUTH_RULE_EAP_IDENTITY, AUTH_RULE_IDENTITY, AUTH_RULE_XAUTH_IDENTITY, enumerator_t::destroy, enumerator_t::enumerate, auth_cfg_t::get, id, and ID_ANY.
 {
     identification_t *id = NULL, *current;
     enumerator_t *enumerator;
     auth_cfg_t *cfg;
     enumerator = array_create_enumerator(this->other_auths);
     while (enumerator->enumerate(enumerator, &cfg))
     {
         /* prefer EAP-Identity of last round */
         current = cfg->get(cfg, AUTH_RULE_EAP_IDENTITY);
         if (!current || current->get_type(current) == ID_ANY)
         {
             current = cfg->get(cfg, AUTH_RULE_XAUTH_IDENTITY);
         }
         if (!current || current->get_type(current) == ID_ANY)
         {
             current = cfg->get(cfg, AUTH_RULE_IDENTITY);
         }
         if (current && current->get_type(current) != ID_ANY)
         {
             id = current;
             continue;
         }
     }
     enumerator->destroy(enumerator);
     if (id)
     {
         return id;
     }
     return this->other_id;
 }
METHOD (ike_sa_t , set_other_id , void , private_ike_sa_t * this, identification_t * other)
Definition at line 1476 of file ike_sa.c.
References DESTROY_IF.
 {
     DESTROY_IF(this->other_id);
     this->other_id = other;
 }
METHOD (ike_sa_t , add_child_sa , void , private_ike_sa_t * this, child_sa_t * child_sa)
Definition at line 1483 of file ike_sa.c.
References child_sa_manager_t::add, array_insert_create(), ARRAY_TAIL, charon, and daemon_t::child_sa_manager.
 {
     array_insert_create(&this->child_sas, ARRAY_TAIL, child_sa);
     charon->child_sa_manager->add(charon->child_sa_manager,
                                   child_sa, &this->public);
 }
METHOD (ike_sa_t , get_child_sa , child_sa_t * , private_ike_sa_t * this, protocol_id_t protocol, u_int32_t spi, bool inbound)
Definition at line 1491 of file ike_sa.c.
References array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, found, child_sa_t::get_protocol, child_sa_t::get_spi, and protocol.
 {
     enumerator_t *enumerator;
     child_sa_t *current, *found = NULL;
     enumerator = array_create_enumerator(this->child_sas);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current->get_spi(current, inbound) == spi &&
             current->get_protocol(current) == protocol)
         {
             found = current;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (ike_sa_t , get_child_count , int , private_ike_sa_t * this)
Definition at line 1510 of file ike_sa.c.
References array_count().
 {
     return array_count(this->child_sas);
 }
METHOD (enumerator_t , child_enumerate , bool , child_enumerator_t * this, child_sa_t ** child_sa)
Definition at line 1528 of file ike_sa.c.
References FALSE, and TRUE.
 {
     if (this->inner->enumerate(this->inner, &this->current))
     {
         *child_sa = this->current;
         return TRUE;
     }
     return FALSE;
 }
METHOD (enumerator_t , child_enumerator_destroy , void , child_enumerator_t * this)
Definition at line 1539 of file ike_sa.c.
References free().
 {
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (ike_sa_t , create_child_sa_enumerator , enumerator_t * , private_ike_sa_t * this)
Definition at line 1546 of file ike_sa.c.
References array_create_enumerator(), destroy(), INIT, and child_enumerator_t::public.
 {
     child_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_child_enumerate,
             .destroy = _child_enumerator_destroy,
         },
         .inner = array_create_enumerator(this->child_sas),
     );
     return &enumerator->public;
 }
METHOD (ike_sa_t , remove_child_sa , void , private_ike_sa_t * this, enumerator_t * enumerator)
Definition at line 1561 of file ike_sa.c.
References array_remove_at(), charon, daemon_t::child_sa_manager, child_enumerator_t::current, child_enumerator_t::inner, and child_sa_manager_t::remove.
 {
     child_enumerator_t *ce = (child_enumerator_t*)enumerator;
     charon->child_sa_manager->remove(charon->child_sa_manager, ce->current);
     array_remove_at(this->child_sas, ce->inner);
 }
METHOD (ike_sa_t , rekey_child_sa , status_t , private_ike_sa_t * this, protocol_id_t protocol, u_int32_t spi)
Definition at line 1570 of file ike_sa.c.
References IKE_PASSIVE, and INVALID_STATE.
 {
     if (this->state == IKE_PASSIVE)
     {
         return INVALID_STATE;
     }
     this->task_manager->queue_child_rekey(this->task_manager, protocol, spi);
     return this->task_manager->initiate(this->task_manager);
 }
METHOD (ike_sa_t , delete_child_sa , status_t , private_ike_sa_t * this, protocol_id_t protocol, u_int32_t spi, bool expired)
Definition at line 1581 of file ike_sa.c.
References IKE_PASSIVE, and INVALID_STATE.
 {
     if (this->state == IKE_PASSIVE)
     {
         return INVALID_STATE;
     }
     this->task_manager->queue_child_delete(this->task_manager,
                                            protocol, spi, expired);
     return this->task_manager->initiate(this->task_manager);
 }
METHOD (ike_sa_t , destroy_child_sa , status_t , private_ike_sa_t * this, protocol_id_t protocol, u_int32_t spi)
Definition at line 1593 of file ike_sa.c.
References enumerator_t::destroy, child_sa_t::destroy, enumerator_t::enumerate, child_sa_t::get_protocol, child_sa_t::get_spi, NOT_FOUND, status, SUCCESS, and TRUE.
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     status_t status = NOT_FOUND;
     enumerator = create_child_sa_enumerator(this);
     while (enumerator->enumerate(enumerator, (void**)&child_sa))
     {
         if (child_sa->get_protocol(child_sa) == protocol &&
             child_sa->get_spi(child_sa, TRUE) == spi)
         {
             remove_child_sa(this, enumerator);
             child_sa->destroy(child_sa);
             status = SUCCESS;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return status;
 }
METHOD (ike_sa_t , delete_ , status_t , private_ike_sa_t * this)
Definition at line 1616 of file ike_sa.c.
References bus_t::alert, ALERT_IKE_SA_EXPIRED, daemon_t::bus, charon, DBG1, DBG_IKE, DESTROY_ME, FALSE, IKE_CREATED, IKE_ESTABLISHED, IKE_PASSIVE, IKE_REKEYING, ike_sa_state_names, bus_t::ike_updown, IKEV1, STAT_DELETE, stats(), time_monotonic(), and version.
 {
     switch (this->state)
     {
         case IKE_REKEYING:
             if (this->version == IKEV1)
             {   /* SA has been reauthenticated, delete */
                 charon->bus->ike_updown(charon->bus, &this->public, FALSE);
                 break;
             }
             /* FALL */
         case IKE_ESTABLISHED:
             if (time_monotonic(NULL) >= this->stats[STAT_DELETE])
             {   /* IKE_SA hard lifetime hit */
                 charon->bus->alert(charon->bus, ALERT_IKE_SA_EXPIRED);
             }
             this->task_manager->queue_ike_delete(this->task_manager);
             return this->task_manager->initiate(this->task_manager);
         case IKE_CREATED:
             DBG1(DBG_IKE, "deleting unestablished IKE_SA");
             break;
         case IKE_PASSIVE:
             break;
         default:
             DBG1(DBG_IKE, "destroying IKE_SA in state %N "
                 "without notification", ike_sa_state_names, this->state);
             charon->bus->ike_updown(charon->bus, &this->public, FALSE);
             break;
     }
     return DESTROY_ME;
 }
METHOD (ike_sa_t , rekey , status_t , private_ike_sa_t * this)
Definition at line 1649 of file ike_sa.c.
References IKE_PASSIVE, and INVALID_STATE.
 {
     if (this->state == IKE_PASSIVE)
     {
         return INVALID_STATE;
     }
     this->task_manager->queue_ike_rekey(this->task_manager);
     return this->task_manager->initiate(this->task_manager);
 }
METHOD (ike_sa_t , reauth , status_t , private_ike_sa_t * this)
Definition at line 1660 of file ike_sa.c.
References array_count(), COND_EAP_AUTHENTICATED, COND_ORIGINAL_INITIATOR, COND_REAUTHENTICATING, COND_XAUTH_AUTHENTICATED, DBG0, DBG1, DBG_IKE, del(), FAILED, get_name(), IKE_CONNECTING, IKE_PASSIVE, INVALID_STATE, set_condition(), STAT_DELETE, stats(), time_monotonic(), TRUE, and unique_id.
 {
     if (this->state == IKE_PASSIVE)
     {
         return INVALID_STATE;
     }
     if (this->state == IKE_CONNECTING)
     {
         DBG0(DBG_IKE, "reinitiating IKE_SA %s[%d]",
              get_name(this), this->unique_id);
         reset(this);
         this->task_manager->queue_ike(this->task_manager);
         return this->task_manager->initiate(this->task_manager);
     }
     /* we can't reauthenticate as responder when we use EAP or virtual IPs.
      * If the peer does not support RFC4478, there is no way to keep the
      * IKE_SA up. */
     if (!has_condition(this, COND_ORIGINAL_INITIATOR))
     {
         DBG1(DBG_IKE, "initiator did not reauthenticate as requested");
         if (array_count(this->other_vips) != 0 ||
             has_condition(this, COND_XAUTH_AUTHENTICATED) ||
             has_condition(this, COND_EAP_AUTHENTICATED)
 #ifdef ME
             /* as mediation server we too cannot reauth the IKE_SA */
             || this->is_mediation_server
 #endif /* ME */
             )
         {
             time_t del, now;
             del = this->stats[STAT_DELETE];
             now = time_monotonic(NULL);
             DBG1(DBG_IKE, "IKE_SA %s[%d] will timeout in %V",
                  get_name(this), this->unique_id, &now, &del);
             return FAILED;
         }
         else
         {
             DBG0(DBG_IKE, "reauthenticating IKE_SA %s[%d] actively",
                  get_name(this), this->unique_id);
         }
     }
     else
     {
         DBG0(DBG_IKE, "reauthenticating IKE_SA %s[%d]",
              get_name(this), this->unique_id);
     }
     set_condition(this, COND_REAUTHENTICATING, TRUE);
     this->task_manager->queue_ike_reauth(this->task_manager);
     return this->task_manager->initiate(this->task_manager);
 }
METHOD (ike_sa_t , reestablish , status_t , private_ike_sa_t * this)
Definition at line 1738 of file ike_sa.c.
References ACTION_NONE, ACTION_RESTART, ACTION_ROUTE, task_manager_t::adopt_child_tasks, array_count(), array_create_enumerator(), daemon_t::bus, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout_new, CHILD_ROUTED, host_t::clone, COND_EAP_AUTHENTICATED, COND_ORIGINAL_INITIATOR, COND_REAUTHENTICATING, DBG1, DBG_IKE, enumerator_t::destroy, DESTROY_ME, enumerator_t::enumerate, FAILED, FALSE, child_sa_t::get_close_action, child_sa_t::get_config, child_sa_t::get_dpd_action, child_cfg_t::get_name, child_cfg_t::get_ref, child_sa_t::get_reqid, child_sa_t::get_state, host, IKE_CREATED, IKE_DELETING, bus_t::ike_reestablish_post, bus_t::ike_reestablish_pre, daemon_t::ike_sa_manager, trap_manager_t::install, is_child_queued(), resolve_hosts(), restart(), bus_t::set_sa, status, SUCCESS, TASK_QUEUE_ACTIVE, TASK_QUEUE_QUEUED, daemon_t::traps, and TRUE.
 {
     ike_sa_t *new;
     host_t *host;
     action_t action;
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     child_cfg_t *child_cfg;
     bool restart = FALSE;
     status_t status = FAILED;
     if (has_condition(this, COND_REAUTHENTICATING))
     {   /* only reauthenticate if we have children */
         if (array_count(this->child_sas) == 0
 #ifdef ME
             /* allow reauth of mediation connections without CHILD_SAs */
             && !this->peer_cfg->is_mediation(this->peer_cfg)
 #endif /* ME */
             )
         {
             DBG1(DBG_IKE, "unable to reauthenticate IKE_SA, no CHILD_SA "
                  "to recreate");
         }
         else
         {
             restart = TRUE;
         }
     }
     else
     {   /* check if we have children to keep up at all */
         enumerator = array_create_enumerator(this->child_sas);
         while (enumerator->enumerate(enumerator, (void**)&child_sa))
         {
             if (this->state == IKE_DELETING)
             {
                 action = child_sa->get_close_action(child_sa);
             }
             else
             {
                 action = child_sa->get_dpd_action(child_sa);
             }
             switch (action)
             {
                 case ACTION_RESTART:
                     restart = TRUE;
                     break;
                 case ACTION_ROUTE:
                     charon->traps->install(charon->traps, this->peer_cfg,
                                            child_sa->get_config(child_sa),
                                            child_sa->get_reqid(child_sa));
                     break;
                 default:
                     break;
             }
         }
         enumerator->destroy(enumerator);
         /* check if we have tasks that recreate children */
         if (!restart)
         {
             restart = is_child_queued(this, TASK_QUEUE_ACTIVE) ||
                       is_child_queued(this, TASK_QUEUE_QUEUED);
         }
 #ifdef ME
         /* mediation connections have no children, keep them up anyway */
         if (this->peer_cfg->is_mediation(this->peer_cfg))
         {
             restart = TRUE;
         }
 #endif /* ME */
     }
     if (!restart)
     {
         return FAILED;
     }
     /* check if we are able to reestablish this IKE_SA */
     if (!has_condition(this, COND_ORIGINAL_INITIATOR) &&
         (array_count(this->other_vips) != 0 ||
          has_condition(this, COND_EAP_AUTHENTICATED)
 #ifdef ME
          || this->is_mediation_server
 #endif /* ME */
         ))
     {
         DBG1(DBG_IKE, "unable to reestablish IKE_SA due to asymmetric setup");
         return FAILED;
     }
     new = charon->ike_sa_manager->checkout_new(charon->ike_sa_manager,
                                                this->version, TRUE);
     if (!new)
     {
         return FAILED;
     }
     new->set_peer_cfg(new, this->peer_cfg);
     host = this->other_host;
     new->set_other_host(new, host->clone(host));
     host = this->my_host;
     new->set_my_host(new, host->clone(host));
     charon->bus->ike_reestablish_pre(charon->bus, &this->public, new);
     /* resolve hosts but use the old addresses above as fallback */
     resolve_hosts((private_ike_sa_t*)new);
     /* if we already have a virtual IP, we reuse it */
     enumerator = array_create_enumerator(this->my_vips);
     while (enumerator->enumerate(enumerator, &host))
     {
         new->add_virtual_ip(new, TRUE, host);
     }
     enumerator->destroy(enumerator);
 #ifdef ME
     if (this->peer_cfg->is_mediation(this->peer_cfg))
     {
         status = new->initiate(new, NULL, 0, NULL, NULL);
     }
     else
 #endif /* ME */
     {
         /* handle existing CHILD_SAs */
         enumerator = create_child_sa_enumerator(this);
         while (enumerator->enumerate(enumerator, (void**)&child_sa))
         {
             if (has_condition(this, COND_REAUTHENTICATING))
             {
                 switch (child_sa->get_state(child_sa))
                 {
                     case CHILD_ROUTED:
                     {   /* move routed child directly */
                         remove_child_sa(this, enumerator);
                         new->add_child_sa(new, child_sa);
                         action = ACTION_NONE;
                         break;
                     }
                     default:
                     {   /* initiate/queue all other CHILD_SAs */
                         action = ACTION_RESTART;
                         break;
                     }
                 }
             }
             else
             {   /* only restart CHILD_SAs that are configured accordingly */
                 if (this->state == IKE_DELETING)
                 {
                     action = child_sa->get_close_action(child_sa);
                 }
                 else
                 {
                     action = child_sa->get_dpd_action(child_sa);
                 }
             }
             switch (action)
             {
                 case ACTION_RESTART:
                     child_cfg = child_sa->get_config(child_sa);
                     DBG1(DBG_IKE, "restarting CHILD_SA %s",
                          child_cfg->get_name(child_cfg));
                     child_cfg->get_ref(child_cfg);
                     status = new->initiate(new, child_cfg,
                                     child_sa->get_reqid(child_sa), NULL, NULL);
                     break;
                 default:
                     continue;
             }
             if (status == DESTROY_ME)
             {
                 break;
             }
         }
         enumerator->destroy(enumerator);
         /* adopt any active or queued CHILD-creating tasks */
         if (status != DESTROY_ME)
         {
             task_manager_t *other_tasks = ((private_ike_sa_t*)new)->task_manager;
             other_tasks->adopt_child_tasks(other_tasks, this->task_manager);
             if (new->get_state(new) == IKE_CREATED)
             {
                 status = new->initiate(new, NULL, 0, NULL, NULL);
             }
         }
     }
     if (status == DESTROY_ME)
     {
         charon->bus->ike_reestablish_post(charon->bus, &this->public, new,
                                           FALSE);
         charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager, new);
         status = FAILED;
     }
     else
     {
         charon->bus->ike_reestablish_post(charon->bus, &this->public, new,
                                           TRUE);
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, new);
         status = SUCCESS;
     }
     charon->bus->set_sa(charon->bus, &this->public);
     return status;
 }
METHOD (ike_sa_t , retransmit , status_t , private_ike_sa_t * this, u_int32_t message_id)
Definition at line 1939 of file ike_sa.c.
References bus_t::alert, ALERT_PEER_INIT_UNREACHABLE, daemon_t::bus, charon, COND_REAUTHENTICATING, DBG1, DBG_IKE, DESTROY_ME, FALSE, IKE_CONNECTING, IKE_DELETING, IKE_PASSIVE, IKE_REKEYING, bus_t::ike_updown, INVALID_STATE, resolve_hosts(), STAT_OUTBOUND, stats(), SUCCESS, and time_monotonic().
 {
     if (this->state == IKE_PASSIVE)
     {
         return INVALID_STATE;
     }
     this->stats[STAT_OUTBOUND] = time_monotonic(NULL);
     if (this->task_manager->retransmit(this->task_manager, message_id) != SUCCESS)
     {
         /* send a proper signal to brief interested bus listeners */
         switch (this->state)
         {
             case IKE_CONNECTING:
             {
                 /* retry IKE_SA_INIT/Main Mode if we have multiple keyingtries */
                 u_int32_t tries = this->peer_cfg->get_keyingtries(this->peer_cfg);
                 charon->bus->alert(charon->bus, ALERT_PEER_INIT_UNREACHABLE,
                                    this->keyingtry);
                 this->keyingtry++;
                 if (tries == 0 || tries > this->keyingtry)
                 {
                     DBG1(DBG_IKE, "peer not responding, trying again (%d/%d)",
                          this->keyingtry + 1, tries);
                     reset(this);
                     resolve_hosts(this);
                     this->task_manager->queue_ike(this->task_manager);
                     return this->task_manager->initiate(this->task_manager);
                 }
                 DBG1(DBG_IKE, "establishing IKE_SA failed, peer not responding");
                 break;
             }
             case IKE_DELETING:
                 DBG1(DBG_IKE, "proper IKE_SA delete failed, peer not responding");
                 if (has_condition(this, COND_REAUTHENTICATING))
                 {
                     DBG1(DBG_IKE, "delete during reauthentication failed, "
                          "trying to reestablish IKE_SA anyway");
                     reestablish(this);
                 }
                 break;
             case IKE_REKEYING:
                 DBG1(DBG_IKE, "rekeying IKE_SA failed, peer not responding");
                 /* FALL */
             default:
                 reestablish(this);
                 break;
         }
         if (this->state != IKE_CONNECTING)
         {
             charon->bus->ike_updown(charon->bus, &this->public, FALSE);
         }
         return DESTROY_ME;
     }
     return SUCCESS;
 }
METHOD (ike_sa_t , set_auth_lifetime , status_t , private_ike_sa_t * this, u_int32_t lifetime)
Definition at line 1996 of file ike_sa.c.
References array_count(), COND_EAP_AUTHENTICATED, COND_ORIGINAL_INITIATOR, DBG1, DBG_IKE, FALSE, ike_auth_lifetime_create(), IKE_ESTABLISHED, IKEV2, lib, max, library_t::processor, processor_t::queue_job, rekey_ike_sa_job_create(), scheduler_t::schedule_job, library_t::scheduler, STAT_DELETE, STAT_REAUTH, stats(), SUCCESS, ike_auth_lifetime_t::task, time_monotonic(), TRUE, and version.
 {
     u_int32_t diff, hard, soft, now;
     bool send_update;
     diff = this->peer_cfg->get_over_time(this->peer_cfg);
     now = time_monotonic(NULL);
     hard = now + lifetime;
     soft = hard - diff;
     /* check if we have to send an AUTH_LIFETIME to enforce the new lifetime.
      * We send the notify in IKE_AUTH if not yet ESTABLISHED. */
     send_update = this->state == IKE_ESTABLISHED && this->version == IKEV2 &&
                   !has_condition(this, COND_ORIGINAL_INITIATOR) &&
                   (array_count(this->other_vips) != 0 ||
                   has_condition(this, COND_EAP_AUTHENTICATED));
     if (lifetime < diff)
     {
         this->stats[STAT_REAUTH] = now;
         if (!send_update)
         {
             DBG1(DBG_IKE, "received AUTH_LIFETIME of %ds, "
                  "starting reauthentication", lifetime);
             lib->processor->queue_job(lib->processor,
                     (job_t*)rekey_ike_sa_job_create(this->ike_sa_id, TRUE));
         }
     }
     else if (this->stats[STAT_REAUTH] == 0 ||
              this->stats[STAT_REAUTH] > soft)
     {
         this->stats[STAT_REAUTH] = soft;
         if (!send_update)
         {
             DBG1(DBG_IKE, "received AUTH_LIFETIME of %ds, scheduling "
                  "reauthentication in %ds", lifetime, lifetime - diff);
             lib->scheduler->schedule_job(lib->scheduler,
                         (job_t*)rekey_ike_sa_job_create(this->ike_sa_id, TRUE),
                         lifetime - diff);
         }
     }
     else
     {
         DBG1(DBG_IKE, "received AUTH_LIFETIME of %ds, "
              "reauthentication already scheduled in %ds", lifetime,
              this->stats[STAT_REAUTH] - time_monotonic(NULL));
         send_update = FALSE;
     }
     /* give at least some seconds to reauthenticate */
     this->stats[STAT_DELETE] = max(hard, now + 10);
 #ifdef USE_IKEV2
     if (send_update)
     {
         ike_auth_lifetime_t *task;
         task = ike_auth_lifetime_create(&this->public, TRUE);
         this->task_manager->queue_task(this->task_manager, &task->task);
         return this->task_manager->initiate(this->task_manager);
     }
 #endif
     return SUCCESS;
 }
METHOD (ike_sa_t , roam , status_t , private_ike_sa_t * this, bool address)
Definition at line 2131 of file ike_sa.c.
References COND_ORIGINAL_INITIATOR, COND_STALE, DBG1, DBG2, DBG_IKE, EXT_MOBIKE, FALSE, IKE_CREATED, IKE_DELETING, IKE_DESTROYING, IKE_PASSIVE, is_any_path_valid(), is_current_path_valid(), reauth(), resolve_hosts(), set_condition(), SUCCESS, and TRUE.
 {
     switch (this->state)
     {
         case IKE_CREATED:
         case IKE_DELETING:
         case IKE_DESTROYING:
         case IKE_PASSIVE:
             return SUCCESS;
         default:
             break;
     }
     /* keep existing path if possible */
     if (is_current_path_valid(this))
     {
         DBG2(DBG_IKE, "keeping connection path %H - %H",
              this->my_host, this->other_host);
         set_condition(this, COND_STALE, FALSE);
         if (supports_extension(this, EXT_MOBIKE) && address)
         {   /* if any addresses changed, send an updated list */
             DBG1(DBG_IKE, "sending address list update using MOBIKE");
             this->task_manager->queue_mobike(this->task_manager, FALSE, TRUE);
             return this->task_manager->initiate(this->task_manager);
         }
         return SUCCESS;
     }
     if (!is_any_path_valid(this))
     {
         DBG1(DBG_IKE, "no route found to reach %H, MOBIKE update deferred",
              this->other_host);
         set_condition(this, COND_STALE, TRUE);
         return SUCCESS;
     }
     set_condition(this, COND_STALE, FALSE);
     /* update addresses with mobike, if supported ... */
     if (supports_extension(this, EXT_MOBIKE))
     {
         if (!has_condition(this, COND_ORIGINAL_INITIATOR))
         {   /* responder updates the peer about changed address config */
             DBG1(DBG_IKE, "sending address list update using MOBIKE, "
                  "implicitly requesting an address change");
             address = TRUE;
         }
         else
         {
             DBG1(DBG_IKE, "requesting address change using MOBIKE");
         }
         this->task_manager->queue_mobike(this->task_manager, TRUE, address);
         return this->task_manager->initiate(this->task_manager);
     }
     /* ... reauth if not */
     if (!has_condition(this, COND_ORIGINAL_INITIATOR))
     {   /* responder does not reauthenticate */
         set_condition(this, COND_STALE, TRUE);
         return SUCCESS;
     }
     DBG1(DBG_IKE, "reauthenticating IKE_SA due to address change");
     /* since our previous path is not valid anymore, try and find a new one */
     resolve_hosts(this);
     return reauth(this);
 }
METHOD (ike_sa_t , add_configuration_attribute , void , private_ike_sa_t * this, attribute_handler_t * handler, configuration_attribute_type_t type, chunk_t data)
Definition at line 2199 of file ike_sa.c.
References array_insert(), ARRAY_TAIL, attributes, chunk_clone, attribute_entry_t::handler, and type.
 {
     attribute_entry_t entry = {
         .handler = handler,
         .type = type,
         .data = chunk_clone(data),
     };
     array_insert(this->attributes, ARRAY_TAIL, &entry);
 }
METHOD (ike_sa_t , create_attribute_enumerator , enumerator_t * , private_ike_sa_t * this)
Definition at line 2224 of file ike_sa.c.
References array_create_enumerator(), attributes, enumerator_create_filter(), and filter_attribute().
 {
     return enumerator_create_filter(array_create_enumerator(this->attributes),
                                     (void*)filter_attribute, NULL, NULL);
 }
METHOD (ike_sa_t , create_task_enumerator , enumerator_t * , private_ike_sa_t * this, task_queue_t queue)
Definition at line 2231 of file ike_sa.c.
 {
     return this->task_manager->create_task_enumerator(this->task_manager, queue);
 }
METHOD (ike_sa_t , flush_queue , void , private_ike_sa_t * this, task_queue_t queue)
Definition at line 2237 of file ike_sa.c.
 {
     this->task_manager->flush_queue(this->task_manager, queue);
 }
METHOD (ike_sa_t , queue_task , void , private_ike_sa_t * this, task_t * task)
Definition at line 2243 of file ike_sa.c.
 {
     this->task_manager->queue_task(this->task_manager, task);
 }
METHOD (ike_sa_t , inherit_pre , void , private_ike_sa_t * this, ike_sa_t * other_public)
Definition at line 2249 of file ike_sa.c.
References host_t::clone, COND_REAUTHENTICATING, COND_STALE, private_ike_sa_t::conditions, private_ike_sa_t::extensions, private_ike_sa_t::my_host, private_ike_sa_t::other_host, and private_ike_sa_t::peer_cfg.
 {
     private_ike_sa_t *other = (private_ike_sa_t*)other_public;
     /* apply config and hosts */
     set_peer_cfg(this, other->peer_cfg);
     set_my_host(this, other->my_host->clone(other->my_host));
     set_other_host(this, other->other_host->clone(other->other_host));
     /* apply extensions and conditions with a few exceptions */
     this->extensions = other->extensions;
     this->conditions = other->conditions;
     this->conditions &= ~COND_STALE;
     this->conditions &= ~COND_REAUTHENTICATING;
 }
METHOD (ike_sa_t , inherit_post , void , private_ike_sa_t * this, ike_sa_t * other_public)
Definition at line 2266 of file ike_sa.c.
References array_create_enumerator(), ARRAY_HEAD, array_insert(), array_insert_create(), array_remove(), ARRAY_TAIL, attributes, private_ike_sa_t::attributes, charon, daemon_t::child_sa_manager, private_ike_sa_t::child_sas, host_t::clone, auth_cfg_t::clone, identification_t::clone, COND_NAT_HERE, private_ike_sa_t::conditions, DBG1, DBG_IKE, delete_ike_sa_job_create(), enumerator_t::destroy, enumerator_t::enumerate, lib, private_ike_sa_t::my_auths, private_ike_sa_t::my_host, private_ike_sa_t::my_id, private_ike_sa_t::my_vips, private_ike_sa_t::other_auths, private_ike_sa_t::other_host, private_ike_sa_t::other_id, private_ike_sa_t::other_vips, private_ike_sa_t::peer_addresses, reauth(), rekey_ike_sa_job_create(), child_sa_manager_t::remove, scheduler_t::schedule_job, library_t::scheduler, STAT_DELETE, STAT_REAUTH, stats(), private_ike_sa_t::stats, private_ike_sa_t::task_manager, time_monotonic(), TRUE, and vip.
 {
     private_ike_sa_t *other = (private_ike_sa_t*)other_public;
     child_sa_t *child_sa;
     enumerator_t *enumerator;
     attribute_entry_t entry;
     auth_cfg_t *cfg;
     host_t *vip;
     /* apply hosts and ids */
     this->my_host->destroy(this->my_host);
     this->other_host->destroy(this->other_host);
     this->my_id->destroy(this->my_id);
     this->other_id->destroy(this->other_id);
     this->my_host = other->my_host->clone(other->my_host);
     this->other_host = other->other_host->clone(other->other_host);
     this->my_id = other->my_id->clone(other->my_id);
     this->other_id = other->other_id->clone(other->other_id);
     /* apply assigned virtual IPs... */
     while (array_remove(other->my_vips, ARRAY_HEAD, &vip))
     {
         array_insert_create(&this->my_vips, ARRAY_TAIL, vip);
     }
     while (array_remove(other->other_vips, ARRAY_HEAD, &vip))
     {
         array_insert_create(&this->other_vips, ARRAY_TAIL, vip);
     }
     /* MOBIKE additional addresses */
     while (array_remove(other->peer_addresses, ARRAY_HEAD, &vip))
     {
         array_insert_create(&this->peer_addresses, ARRAY_TAIL, vip);
     }
     /* authentication information */
     enumerator = array_create_enumerator(other->my_auths);
     while (enumerator->enumerate(enumerator, &cfg))
     {
         array_insert(this->my_auths, ARRAY_TAIL, cfg->clone(cfg));
     }
     enumerator->destroy(enumerator);
     enumerator = array_create_enumerator(other->other_auths);
     while (enumerator->enumerate(enumerator, &cfg))
     {
         array_insert(this->other_auths, ARRAY_TAIL, cfg->clone(cfg));
     }
     enumerator->destroy(enumerator);
     /* ... and configuration attributes */
     while (array_remove(other->attributes, ARRAY_HEAD, &entry))
     {
         array_insert(this->attributes, ARRAY_TAIL, &entry);
     }
     /* inherit all conditions */
     this->conditions = other->conditions;
     if (this->conditions & COND_NAT_HERE)
     {
         send_keepalive(this);
     }
 #ifdef ME
     if (other->is_mediation_server)
     {
         act_as_mediation_server(this);
     }
     else if (other->server_reflexive_host)
     {
         this->server_reflexive_host = other->server_reflexive_host->clone(
                 other->server_reflexive_host);
     }
 #endif /* ME */
     /* adopt all children */
     while (array_remove(other->child_sas, ARRAY_HEAD, &child_sa))
     {
         charon->child_sa_manager->remove(charon->child_sa_manager, child_sa);
         add_child_sa(this, child_sa);
     }
     /* move pending tasks to the new IKE_SA */
     this->task_manager->adopt_tasks(this->task_manager, other->task_manager);
     /* reauthentication timeout survives a rekeying */
     if (other->stats[STAT_REAUTH])
     {
         time_t reauth, delete, now = time_monotonic(NULL);
         this->stats[STAT_REAUTH] = other->stats[STAT_REAUTH];
         reauth = this->stats[STAT_REAUTH] - now;
         delete = reauth + this->peer_cfg->get_over_time(this->peer_cfg);
         this->stats[STAT_DELETE] = this->stats[STAT_REAUTH] + delete;
         DBG1(DBG_IKE, "rescheduling reauthentication in %ds after rekeying, "
              "lifetime reduced to %ds", reauth, delete);
         lib->scheduler->schedule_job(lib->scheduler,
                 (job_t*)rekey_ike_sa_job_create(this->ike_sa_id, TRUE), reauth);
         lib->scheduler->schedule_job(lib->scheduler,
                 (job_t*)delete_ike_sa_job_create(this->ike_sa_id, TRUE), delete);
     }
 }
METHOD (ike_sa_t , destroy , void , private_ike_sa_t * this)
Definition at line 2369 of file ike_sa.c.
References array_count(), array_destroy(), array_destroy_offset(), array_remove(), ARRAY_TAIL, bus_t::assign_vips, attributes, daemon_t::attributes, daemon_t::bus, charon, daemon_t::child_sa_manager, chunk_free(), attribute_entry_t::data, kernel_interface_t::del_ip, host_t::destroy, linked_list_t::destroy, child_sa_t::destroy, destroy(), DESTROY_IF, FALSE, free(), bus_t::handle_vips, attribute_entry_t::handler, hydra, IKE_DESTROYING, hydra_t::kernel_interface, linked_list_create_from_enumerator(), proposal, chunk_t::ptr, attribute_manager_t::release, attribute_manager_t::release_address, child_sa_manager_t::remove, bus_t::set_sa, set_state(), TRUE, attribute_entry_t::type, and vip.
 {
     attribute_entry_t entry;
     child_sa_t *child_sa;
     host_t *vip;
     charon->bus->set_sa(charon->bus, &this->public);
     set_state(this, IKE_DESTROYING);
     if (this->task_manager)
     {
         this->task_manager->flush(this->task_manager);
     }
     /* remove attributes first, as we pass the IKE_SA to the handler */
     charon->bus->handle_vips(charon->bus, &this->public, FALSE);
     while (array_remove(this->attributes, ARRAY_TAIL, &entry))
     {
         if (entry.handler)
         {
             charon->attributes->release(charon->attributes, entry.handler,
                                         &this->public, entry.type, entry.data);
         }
         free(entry.data.ptr);
     }
     /* uninstall CHILD_SAs before virtual IPs, otherwise we might kill
      * routes that the CHILD_SA tries to uninstall. */
     while (array_remove(this->child_sas, ARRAY_TAIL, &child_sa))
     {
         charon->child_sa_manager->remove(charon->child_sa_manager, child_sa);
         child_sa->destroy(child_sa);
     }
     while (array_remove(this->my_vips, ARRAY_TAIL, &vip))
     {
         hydra->kernel_interface->del_ip(hydra->kernel_interface, vip, -1, TRUE);
         vip->destroy(vip);
     }
     if (array_count(this->other_vips))
     {
         charon->bus->assign_vips(charon->bus, &this->public, FALSE);
     }
     while (array_remove(this->other_vips, ARRAY_TAIL, &vip))
     {
         if (this->peer_cfg)
         {
             linked_list_t *pools;
             pools = linked_list_create_from_enumerator(
                         this->peer_cfg->create_pool_enumerator(this->peer_cfg));
             charon->attributes->release_address(charon->attributes,
                                                 pools, vip, &this->public);
             pools->destroy(pools);
         }
         vip->destroy(vip);
     }
     /* unset SA after here to avoid usage by the listeners */
     charon->bus->set_sa(charon->bus, NULL);
     array_destroy(this->child_sas);
     DESTROY_IF(this->task_manager);
     DESTROY_IF(this->keymat);
     array_destroy(this->attributes);
     array_destroy(this->my_vips);
     array_destroy(this->other_vips);
     array_destroy_offset(this->peer_addresses, offsetof(host_t, destroy));
 #ifdef ME
     if (this->is_mediation_server)
     {
         charon->mediation_manager->remove(charon->mediation_manager,
                                           this->ike_sa_id);
     }
     DESTROY_IF(this->server_reflexive_host);
     chunk_free(&this->connect_id);
 #endif /* ME */
     free(this->nat_detection_dest.ptr);
     DESTROY_IF(this->my_host);
     DESTROY_IF(this->other_host);
     DESTROY_IF(this->my_id);
     DESTROY_IF(this->other_id);
     DESTROY_IF(this->local_host);
     DESTROY_IF(this->remote_host);
     DESTROY_IF(this->ike_cfg);
     DESTROY_IF(this->peer_cfg);
     DESTROY_IF(this->proposal);
     this->my_auth->destroy(this->my_auth);
     this->other_auth->destroy(this->other_auth);
     array_destroy_offset(this->my_auths, offsetof(auth_cfg_t, destroy));
     array_destroy_offset(this->other_auths, offsetof(auth_cfg_t, destroy));
     this->ike_sa_id->destroy(this->ike_sa_id);
     free(this);
 }
static void resolve_hosts (private_ike_sa_t * this) static
Resolve DNS host in configuration
Definition at line 1194 of file ike_sa.c.
References charon, host_t::clone, host_t::destroy, FALSE, family, socket_manager_t::get_port, host_t::get_port, kernel_interface_t::get_source_addr, host, hydra, ike_cfg_get_family(), IKEV2_UDP_PORT, host_t::is_anyaddr, hydra_t::kernel_interface, host_t::set_port, daemon_t::socket, SOCKET_FAMILY_BOTH, SOCKET_FAMILY_IPV4, SOCKET_FAMILY_IPV6, SOCKET_FAMILY_NONE, socket_manager_t::supported_families, and TRUE.
Referenced by METHOD().
 {
     host_t *host;
     int family = AF_UNSPEC;
     switch (charon->socket->supported_families(charon->socket))
     {
         case SOCKET_FAMILY_IPV4:
             family = AF_INET;
             break;
         case SOCKET_FAMILY_IPV6:
             family = AF_INET6;
             break;
         case SOCKET_FAMILY_BOTH:
         case SOCKET_FAMILY_NONE:
             break;
     }
     /* if an IP address is set locally, use the same family to resolve remote */
     if (family == AF_UNSPEC && !this->remote_host)
     {
         if (this->local_host)
         {
             family = this->local_host->get_family(this->local_host);
         }
         else
         {
             family = ike_cfg_get_family(this->ike_cfg, TRUE);
         }
     }
     if (this->remote_host)
     {
         host = this->remote_host->clone(this->remote_host);
         host->set_port(host, IKEV2_UDP_PORT);
     }
     else
     {
         host = this->ike_cfg->resolve_other(this->ike_cfg, family);
     }
     if (host)
     {
         if (!host->is_anyaddr(host) ||
             this->other_host->is_anyaddr(this->other_host))
         {   /* don't set to %any if we currently have an address, but the
              * address family might have changed */
             set_other_host(this, host);
         }
         else
         {   /* reuse the original port as some implementations might not like
              * initial IKE messages on other ports */
             this->other_host->set_port(this->other_host, host->get_port(host));
             host->destroy(host);
         }
     }
     if (this->local_host)
     {
         host = this->local_host->clone(this->local_host);
         host->set_port(host, charon->socket->get_port(charon->socket, FALSE));
     }
     else
     {
         /* use same address family as for other */
         if (!this->other_host->is_anyaddr(this->other_host))
         {
             family = this->other_host->get_family(this->other_host);
         }
         host = this->ike_cfg->resolve_me(this->ike_cfg, family);
         if (host && host->is_anyaddr(host) &&
             !this->other_host->is_anyaddr(this->other_host))
         {
             host->destroy(host);
             host = hydra->kernel_interface->get_source_addr(
                             hydra->kernel_interface, this->other_host, NULL);
             if (host)
             {
                 host->set_port(host, this->ike_cfg->get_my_port(this->ike_cfg));
             }
             else
             {   /* fallback to address family specific %any(6), if configured */
                 host = this->ike_cfg->resolve_me(this->ike_cfg, family);
             }
         }
     }
     if (host)
     {
         set_my_host(this, host);
     }
 }
static void set_dscp (private_ike_sa_t * this, packet_t * packet) static
Set configured DSCP value on packet
Definition at line 1000 of file ike_sa.c.
References ike_cfg_t::get_dscp, and packet_t::set_dscp.
Referenced by filter_fragments(), and METHOD().
 {
     ike_cfg_t *ike_cfg;
     /* prefer IKE config on peer_cfg, as its selection is more accurate
      * then the initial IKE config */
     if (this->peer_cfg)
     {
         ike_cfg = this->peer_cfg->get_ike_cfg(this->peer_cfg);
     }
     else
     {
         ike_cfg = this->ike_cfg;
     }
     if (ike_cfg)
     {
         packet->set_dscp(packet, ike_cfg->get_dscp(ike_cfg));
     }
 }