strongSwan: ike_auth_lifetime.c File Reference
ike_auth_lifetime.c File Reference
#include "ike_auth_lifetime.h"
#include <time.h>
#include <daemon.h>
#include <encoding/payloads/notify_payload.h>
Classes
struct private_ike_auth_lifetime_t
Typedefs
typedef struct
private_ike_auth_lifetime_t private_ike_auth_lifetime_t
Functions
static void add_auth_lifetime (private_ike_auth_lifetime_t *this, message_t *message)
static void process_payloads (private_ike_auth_lifetime_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_ike_auth_lifetime_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_ike_auth_lifetime_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_ike_auth_lifetime_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_ike_auth_lifetime_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_ike_auth_lifetime_t *this)
METHOD (task_t, migrate, void, private_ike_auth_lifetime_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_ike_auth_lifetime_t *this)
ike_auth_lifetime_t * ike_auth_lifetime_create (ike_sa_t *ike_sa, bool initiator)
Typedef Documentation
typedef struct private_ike_auth_lifetime_t private_ike_auth_lifetime_t
Definition at line 24 of file ike_auth_lifetime.c.
Function Documentation
static void add_auth_lifetime (private_ike_auth_lifetime_t * this, message_t * message) static
add the AUTH_LIFETIME notify to the message
Definition at line 45 of file ike_auth_lifetime.c.
References message_t::add_notify, AUTH_LIFETIME, chunk_from_thing, FALSE, chunk_t::ptr, STAT_REAUTH, and time_monotonic().
Referenced by METHOD().
 {
     chunk_t chunk;
     u_int32_t lifetime;
     lifetime = this->ike_sa->get_statistic(this->ike_sa, STAT_REAUTH);
     if (lifetime)
     {
         lifetime -= time_monotonic(NULL);
         chunk = chunk_from_thing(lifetime);
         *(u_int32_t*)chunk.ptr = htonl(lifetime);
         message->add_notify(message, FALSE, AUTH_LIFETIME, chunk);
     }
 }
METHOD (task_t , build_i , status_t , private_ike_auth_lifetime_t * this, message_t * message)
Definition at line 78 of file ike_auth_lifetime.c.
References add_auth_lifetime(), message_t::get_exchange_type, INFORMATIONAL, NEED_MORE, and SUCCESS.
 {
     if (message->get_exchange_type(message) == INFORMATIONAL)
     {
         add_auth_lifetime(this, message);
         return SUCCESS;
     }
     return NEED_MORE;
 }
METHOD (task_t , process_r , status_t , private_ike_auth_lifetime_t * this, message_t * message)
Definition at line 89 of file ike_auth_lifetime.c.
References message_t::get_exchange_type, INFORMATIONAL, NEED_MORE, process_payloads(), and SUCCESS.
 {
     if (message->get_exchange_type(message) == INFORMATIONAL)
     {
         process_payloads(this, message);
         return SUCCESS;
     }
     return NEED_MORE;
 }
METHOD (task_t , build_r , status_t , private_ike_auth_lifetime_t * this, message_t * message)
Definition at line 100 of file ike_auth_lifetime.c.
References add_auth_lifetime(), message_t::get_exchange_type, IKE_AUTH, IKE_ESTABLISHED, NEED_MORE, and SUCCESS.
 {
     if (message->get_exchange_type(message) == IKE_AUTH &&
         this->ike_sa->get_state(this->ike_sa) == IKE_ESTABLISHED)
     {
         add_auth_lifetime(this, message);
         return SUCCESS;
     }
     return NEED_MORE;
 }
METHOD (task_t , process_i , status_t , private_ike_auth_lifetime_t * this, message_t * message)
Definition at line 112 of file ike_auth_lifetime.c.
References message_t::get_exchange_type, IKE_AUTH, IKE_ESTABLISHED, NEED_MORE, process_payloads(), and SUCCESS.
 {
     if (message->get_exchange_type(message) == IKE_AUTH &&
         this->ike_sa->get_state(this->ike_sa) == IKE_ESTABLISHED)
     {
         process_payloads(this, message);
         return SUCCESS;
     }
     return NEED_MORE;
 }
METHOD (task_t , get_type , task_type_t , private_ike_auth_lifetime_t * this)
Definition at line 124 of file ike_auth_lifetime.c.
References TASK_IKE_AUTH_LIFETIME.
 {
     return TASK_IKE_AUTH_LIFETIME;
 }
METHOD (task_t , migrate , void , private_ike_auth_lifetime_t * this, ike_sa_t * ike_sa)
Definition at line 130 of file ike_auth_lifetime.c.
 {
     this->ike_sa = ike_sa;
 }
METHOD (task_t , destroy , void , private_ike_auth_lifetime_t * this)
Definition at line 136 of file ike_auth_lifetime.c.
References free().
 {
     free(this);
 }
static void process_payloads (private_ike_auth_lifetime_t * this, message_t * message) static
read notifys from message and evaluate them
Definition at line 63 of file ike_auth_lifetime.c.
References AUTH_LIFETIME, data, notify_payload_t::get_notification_data, message_t::get_notify, notify(), and chunk_t::ptr.
Referenced by METHOD().
 {
     notify_payload_t *notify;
     chunk_t data;
     u_int32_t lifetime;
     notify = message->get_notify(message, AUTH_LIFETIME);
     if (notify)
     {
         data = notify->get_notification_data(notify);
         lifetime = ntohl(*(u_int32_t*)data.ptr);
         this->ike_sa->set_auth_lifetime(this->ike_sa, lifetime);
     }
 }