strongSwan: imv_scanner_state_t Struct Reference
imv_scanner_state_t Struct Reference
imv_scanner_state
#include "imv_scanner_state.h"
Public Attributes
imv_state_t interface
void(* set_handshake_state)(imv_scanner_state_t *this, imv_scanner_handshake_state_t new_state)
imv_scanner_handshake_state_t(* get_handshake_state)(imv_scanner_state_t *this)
void(* set_port_filter_attr)(imv_scanner_state_t *this, ietf_attr_port_filter_t *attr)
ietf_attr_port_filter_t *(* get_port_filter_attr)(imv_scanner_state_t *this)
void(* add_violating_port)(imv_scanner_state_t *this, char *port)
Detailed Description
Internal state of an imv_scanner_t connection instance
Definition at line 48 of file imv_scanner_state.h.
Member Data Documentation
void(* imv_scanner_state_t::add_violating_port)(imv_scanner_state_t *this, char *port)
add a violating TCP or UDP port
Definition at line 88 of file imv_scanner_state.h.
Referenced by METHOD().
imv_scanner_handshake_state_t(* imv_scanner_state_t::get_handshake_state)(imv_scanner_state_t *this)
Get state of the handshake
Returns
the handshake state of IMV
Definition at line 68 of file imv_scanner_state.h.
Referenced by METHOD().
ietf_attr_port_filter_t*(* imv_scanner_state_t::get_port_filter_attr)(imv_scanner_state_t *this)
Get the stored IETF Port Filter attribute
Returns
IETF Port Filter attribute
Definition at line 83 of file imv_scanner_state.h.
Referenced by METHOD().
imv_state_t imv_scanner_state_t::interface
imv_state_t interface
Definition at line 53 of file imv_scanner_state.h.
void(* imv_scanner_state_t::set_handshake_state)(imv_scanner_state_t *this, imv_scanner_handshake_state_t new_state)
Set state of the handshake
Parameters
new_state the handshake state of IMV
Definition at line 60 of file imv_scanner_state.h.
Referenced by METHOD().
void(* imv_scanner_state_t::set_port_filter_attr)(imv_scanner_state_t *this, ietf_attr_port_filter_t *attr)
Store an IETF Port Filter attribute for later evaluation
Parameters
attr IETF Port Filter attribute
Definition at line 75 of file imv_scanner_state.h.
Referenced by receive_msg().
The documentation for this struct was generated from the following file:
imv_scanner_state.h