strongSwan: tcg_pts_attr_dh_nonce_params_resp.c File Reference
tcg_pts_attr_dh_nonce_params_resp.c File Reference
#include "tcg_pts_attr_dh_nonce_params_resp.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_dh_nonce_params_resp_t
Macros
#define PTS_DH_NONCE_PARAMS_RESP_SIZE 16
#define PTS_DH_NONCE_PARAMS_RESP_RESERVED 0x0000
Typedefs
typedef struct
private_tcg_pts_attr_dh_nonce_params_resp_t private_tcg_pts_attr_dh_nonce_params_resp_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_dh_nonce_params_resp_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_dh_nonce_params_resp_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_dh_nonce_params_resp_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (tcg_pts_attr_dh_nonce_params_resp_t, get_dh_group, pts_dh_group_t, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (tcg_pts_attr_dh_nonce_params_resp_t, get_hash_algo_set, pts_meas_algorithms_t, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (tcg_pts_attr_dh_nonce_params_resp_t, get_responder_nonce, chunk_t, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
METHOD (tcg_pts_attr_dh_nonce_params_resp_t, get_responder_value, chunk_t, private_tcg_pts_attr_dh_nonce_params_resp_t *this)
pa_tnc_attr_t * tcg_pts_attr_dh_nonce_params_resp_create (pts_dh_group_t dh_group, pts_meas_algorithms_t hash_algo_set, chunk_t responder_nonce, chunk_t responder_value)
pa_tnc_attr_t * tcg_pts_attr_dh_nonce_params_resp_create_from_data (size_t length, chunk_t value)
Macro Definition Documentation
#define PTS_DH_NONCE_PARAMS_RESP_RESERVED 0x0000
Definition at line 46 of file tcg_pts_attr_dh_nonce_params_resp.c.
Referenced by METHOD().
#define PTS_DH_NONCE_PARAMS_RESP_SIZE 16
PTS DH Nonce Parameters Response see section 3.8.2 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Nonce Len | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Selected D-H Group | Hash Algorithm Set | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | D-H Responder Nonce ... | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | D-H Responder Public Value ... | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 45 of file tcg_pts_attr_dh_nonce_params_resp.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_dh_nonce_params_resp_t private_tcg_pts_attr_dh_nonce_params_resp_t
Definition at line 24 of file tcg_pts_attr_dh_nonce_params_resp.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 104 of file tcg_pts_attr_dh_nonce_params_resp.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 110 of file tcg_pts_attr_dh_nonce_params_resp.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 116 of file tcg_pts_attr_dh_nonce_params_resp.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_dh_nonce_params_resp_t * this, bool noskip)
Definition at line 122 of file tcg_pts_attr_dh_nonce_params_resp.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 128 of file tcg_pts_attr_dh_nonce_params_resp.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, PTS_DH_NONCE_PARAMS_RESP_RESERVED, PTS_DH_NONCE_PARAMS_RESP_SIZE, value, bio_writer_t::write_data, bio_writer_t::write_uint16, bio_writer_t::write_uint24, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PTS_DH_NONCE_PARAMS_RESP_SIZE);
     writer->write_uint24(writer, PTS_DH_NONCE_PARAMS_RESP_RESERVED);
     writer->write_uint8 (writer, this->responder_nonce.len);
     writer->write_uint16(writer, this->dh_group);
     writer->write_uint16(writer, this->hash_algo_set);
     writer->write_data  (writer, this->responder_nonce);
     writer->write_data  (writer, this->responder_value);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_dh_nonce_params_resp_t * this, u_int32_t * offset)
Definition at line 150 of file tcg_pts_attr_dh_nonce_params_resp.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, PTS_DH_NONCE_PARAMS_RESP_SIZE, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint24, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int32_t reserved;
     u_int8_t nonce_len;
     u_int16_t dh_group, hash_algo_set;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_DH_NONCE_PARAMS_RESP_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for PTS DH Nonce Parameters Response");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint24(reader, &reserved);
     reader->read_uint8 (reader, &nonce_len);
     reader->read_uint16(reader, &dh_group);
     reader->read_uint16(reader, &hash_algo_set);
     reader->read_data(reader, nonce_len, &this->responder_nonce);
     reader->read_data(reader, reader->remaining(reader), &this->responder_value);
     this->dh_group = dh_group;
     this->hash_algo_set = hash_algo_set;
     this->responder_nonce = chunk_clone(this->responder_nonce);
     this->responder_value = chunk_clone(this->responder_value);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_dh_nonce_params_resp_t * this, chunk_t segment)
Definition at line 185 of file tcg_pts_attr_dh_nonce_params_resp.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 191 of file tcg_pts_attr_dh_nonce_params_resp.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 198 of file tcg_pts_attr_dh_nonce_params_resp.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this->responder_nonce.ptr);
         free(this->responder_value.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_dh_nonce_params_resp_t , get_dh_group , pts_dh_group_t , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 210 of file tcg_pts_attr_dh_nonce_params_resp.c.
 {
     return this->dh_group;
 }
METHOD (tcg_pts_attr_dh_nonce_params_resp_t , get_hash_algo_set , pts_meas_algorithms_t , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 216 of file tcg_pts_attr_dh_nonce_params_resp.c.
 {
     return this->hash_algo_set;
 }
METHOD (tcg_pts_attr_dh_nonce_params_resp_t , get_responder_nonce , chunk_t , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 222 of file tcg_pts_attr_dh_nonce_params_resp.c.
 {
     return this->responder_nonce;
 }
METHOD (tcg_pts_attr_dh_nonce_params_resp_t , get_responder_value , chunk_t , private_tcg_pts_attr_dh_nonce_params_resp_t * this)
Definition at line 228 of file tcg_pts_attr_dh_nonce_params_resp.c.
 {
     return this->responder_value;
 }