strongSwan: shunt_manager.c File Reference
shunt_manager.c File Reference
#include "shunt_manager.h"
#include <hydra.h>
#include <daemon.h>
#include <threading/rwlock.h>
#include <threading/rwlock_condvar.h>
#include <collections/linked_list.h>
Classes
struct private_shunt_manager_t
Macros
#define INSTALL_DISABLED ((u_int)~0)
Typedefs
typedef struct
private_shunt_manager_t private_shunt_manager_t
Functions
static bool install_shunt_policy (child_cfg_t *child)
METHOD (shunt_manager_t, install, bool, private_shunt_manager_t *this, child_cfg_t *child)
static void uninstall_shunt_policy (child_cfg_t *child)
METHOD (shunt_manager_t, uninstall, bool, private_shunt_manager_t *this, char *name)
METHOD (shunt_manager_t, create_enumerator, enumerator_t *, private_shunt_manager_t *this)
METHOD (shunt_manager_t, flush, void, private_shunt_manager_t *this)
METHOD (shunt_manager_t, destroy, void, private_shunt_manager_t *this)
shunt_manager_t * shunt_manager_create ()
Macro Definition Documentation
#define INSTALL_DISABLED ((u_int)~0)
Definition at line 25 of file shunt_manager.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_shunt_manager_t private_shunt_manager_t
Definition at line 27 of file shunt_manager.c.
Function Documentation
static bool install_shunt_policy (child_cfg_t * child) static
Install in and out shunt policies in the kernel
Definition at line 63 of file shunt_manager.c.
References kernel_interface_t::add_policy, linked_list_t::create_enumerator, enumerator_t::destroy, host_t::destroy, linked_list_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, FALSE, child_cfg_t::get_mark, child_cfg_t::get_mode, traffic_selector_t::get_protocol, child_cfg_t::get_traffic_selectors, traffic_selector_t::get_type, host_create_any(), hydra, hydra_t::kernel_interface, linked_list_create_with_items(), MODE_DROP, MODE_PASS, MODE_TRANSPORT, POLICY_DROP, POLICY_FWD, POLICY_IN, POLICY_OUT, POLICY_PASS, POLICY_PRIORITY_FALLBACK, POLICY_PRIORITY_PASS, sa, status, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *e_my_ts, *e_other_ts;
     linked_list_t *my_ts_list, *other_ts_list, *hosts;
     traffic_selector_t *my_ts, *other_ts;
     host_t *host_any, *host_any6;
     policy_type_t policy_type;
     policy_priority_t policy_prio;
     status_t status = SUCCESS;
     ipsec_sa_cfg_t sa = { .mode = MODE_TRANSPORT };
     switch (child->get_mode(child))
     {
         case MODE_PASS:
             policy_type = POLICY_PASS;
             policy_prio = POLICY_PRIORITY_PASS;
             break;
         case MODE_DROP:
             policy_type = POLICY_DROP;
             policy_prio = POLICY_PRIORITY_FALLBACK;
             break;
         default:
             return FALSE;
     }
     host_any = host_create_any(AF_INET);
     host_any6 = host_create_any(AF_INET6);
     hosts = linked_list_create_with_items(host_any, host_any6, NULL);
     my_ts_list =    child->get_traffic_selectors(child, TRUE,  NULL, hosts);
     other_ts_list = child->get_traffic_selectors(child, FALSE, NULL, hosts);
     hosts->destroy(hosts);
     /* enumerate pairs of traffic selectors */
     e_my_ts = my_ts_list->create_enumerator(my_ts_list);
     while (e_my_ts->enumerate(e_my_ts, &my_ts))
     {
         e_other_ts = other_ts_list->create_enumerator(other_ts_list);
         while (e_other_ts->enumerate(e_other_ts, &other_ts))
         {
             if (my_ts->get_type(my_ts) != other_ts->get_type(other_ts))
             {
                 continue;
             }
             if (my_ts->get_protocol(my_ts) &&
                 other_ts->get_protocol(other_ts) &&
                 my_ts->get_protocol(my_ts) != other_ts->get_protocol(other_ts))
             {
                 continue;
             }
             /* install out policy */
             status |= hydra->kernel_interface->add_policy(
                                 hydra->kernel_interface, host_any, host_any,
                                 my_ts, other_ts, POLICY_OUT, policy_type,
                                 &sa, child->get_mark(child, FALSE),
                                 policy_prio);
             /* install in policy */
             status |= hydra->kernel_interface->add_policy(
                                 hydra->kernel_interface, host_any, host_any,
                                 other_ts, my_ts, POLICY_IN, policy_type,
                                 &sa, child->get_mark(child, TRUE),
                                 policy_prio);
             /* install forward policy */
             status |= hydra->kernel_interface->add_policy(
                                 hydra->kernel_interface, host_any, host_any,
                                 other_ts, my_ts, POLICY_FWD, policy_type,
                                 &sa, child->get_mark(child, TRUE),
                                 policy_prio);
         }
         e_other_ts->destroy(e_other_ts);
     }
     e_my_ts->destroy(e_my_ts);
     my_ts_list->destroy_offset(my_ts_list,
                                offsetof(traffic_selector_t, destroy));
     other_ts_list->destroy_offset(other_ts_list,
                                offsetof(traffic_selector_t, destroy));
     host_any6->destroy(host_any6);
     host_any->destroy(host_any);
     return status == SUCCESS;
 }
METHOD (shunt_manager_t , install , bool , private_shunt_manager_t * this, child_cfg_t * child)
Definition at line 148 of file shunt_manager.c.
References condvar, DBG1, DBG_CFG, enumerator_t::destroy, child_cfg_t::destroy, enumerator_t::enumerate, FALSE, found, child_cfg_t::get_mode, child_cfg_t::get_name, child_cfg_t::get_ref, INSTALL_DISABLED, install_shunt_policy(), ipsec_mode_names, lock, condvar_t::signal, streq(), TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     child_cfg_t *child_cfg;
     bool found = FALSE, success;
     /* check if not already installed */
     this->lock->write_lock(this->lock);
     if (this->installing == INSTALL_DISABLED)
     {   /* flush() has been called */
         this->lock->unlock(this->lock);
         return FALSE;
     }
     enumerator = this->shunts->create_enumerator(this->shunts);
     while (enumerator->enumerate(enumerator, &child_cfg))
     {
         if (streq(child_cfg->get_name(child_cfg), child->get_name(child)))
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (found)
     {
         DBG1(DBG_CFG, "shunt %N policy '%s' already installed",
              ipsec_mode_names, child->get_mode(child), child->get_name(child));
         this->lock->unlock(this->lock);
         return TRUE;
     }
     this->shunts->insert_last(this->shunts, child->get_ref(child));
     this->installing++;
     this->lock->unlock(this->lock);
     success = install_shunt_policy(child);
     this->lock->write_lock(this->lock);
     if (!success)
     {
         this->shunts->remove(this->shunts, child, NULL);
         child->destroy(child);
     }
     this->installing--;
     this->condvar->signal(this->condvar);
     this->lock->unlock(this->lock);
     return success;
 }
METHOD (shunt_manager_t , uninstall , bool , private_shunt_manager_t * this, char * name)
Definition at line 289 of file shunt_manager.c.
References enumerator_t::destroy, child_cfg_t::destroy, enumerator_t::enumerate, FALSE, found, child_cfg_t::get_name, lock, streq(), TRUE, uninstall_shunt_policy(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     child_cfg_t *child, *found = NULL;
     this->lock->write_lock(this->lock);
     enumerator = this->shunts->create_enumerator(this->shunts);
     while (enumerator->enumerate(enumerator, &child))
     {
         if (streq(name, child->get_name(child)))
         {
             this->shunts->remove_at(this->shunts, enumerator);
             found = child;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!found)
     {
         return FALSE;
     }
     uninstall_shunt_policy(child);
     child->destroy(child);
     return TRUE;
 }
METHOD (shunt_manager_t , create_enumerator , enumerator_t * , private_shunt_manager_t * this)
Definition at line 318 of file shunt_manager.c.
References enumerator_create_cleaner(), lock, and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_cleaner(
                             this->shunts->create_enumerator(this->shunts),
                             (void*)this->lock->unlock, this->lock);
 }
METHOD (shunt_manager_t , flush , void , private_shunt_manager_t * this)
Definition at line 327 of file shunt_manager.c.
References condvar, child_cfg_t::destroy, INSTALL_DISABLED, lock, SUCCESS, uninstall_shunt_policy(), spinlock_t::unlock, and condvar_t::wait.
 {
     child_cfg_t *child;
     this->lock->write_lock(this->lock);
     while (this->installing)
     {
         this->condvar->wait(this->condvar, this->lock);
     }
     while (this->shunts->remove_last(this->shunts, (void**)&child) == SUCCESS)
     {
         uninstall_shunt_policy(child);
         child->destroy(child);
     }
     this->installing = INSTALL_DISABLED;
     this->lock->unlock(this->lock);
 }
METHOD (shunt_manager_t , destroy , void , private_shunt_manager_t * this)
Definition at line 346 of file shunt_manager.c.
References condvar, spinlock_t::destroy, condvar_t::destroy, destroy(), free(), and lock.
 {
     this->shunts->destroy_offset(this->shunts, offsetof(child_cfg_t, destroy));
     this->lock->destroy(this->lock);
     this->condvar->destroy(this->condvar);
     free(this);
 }
static void uninstall_shunt_policy (child_cfg_t * child) static
Uninstall in and out shunt policies in the kernel
Definition at line 200 of file shunt_manager.c.
References linked_list_t::create_enumerator, DBG1, DBG_CFG, kernel_interface_t::del_policy, enumerator_t::destroy, host_t::destroy, linked_list_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, FALSE, child_cfg_t::get_mark, child_cfg_t::get_mode, child_cfg_t::get_name, traffic_selector_t::get_protocol, child_cfg_t::get_traffic_selectors, traffic_selector_t::get_type, host_create_any(), hydra, ipsec_mode_names, hydra_t::kernel_interface, linked_list_create_with_items(), MODE_DROP, MODE_PASS, MODE_TRANSPORT, POLICY_DROP, POLICY_FWD, POLICY_IN, POLICY_OUT, POLICY_PASS, POLICY_PRIORITY_FALLBACK, POLICY_PRIORITY_PASS, sa, status, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *e_my_ts, *e_other_ts;
     linked_list_t *my_ts_list, *other_ts_list, *hosts;
     traffic_selector_t *my_ts, *other_ts;
     host_t *host_any, *host_any6;
     policy_type_t policy_type;
     policy_priority_t policy_prio;
     status_t status = SUCCESS;
     ipsec_sa_cfg_t sa = { .mode = MODE_TRANSPORT };
     switch (child->get_mode(child))
     {
         case MODE_PASS:
             policy_type = POLICY_PASS;
             policy_prio = POLICY_PRIORITY_PASS;
             break;
         case MODE_DROP:
             policy_type = POLICY_DROP;
             policy_prio = POLICY_PRIORITY_FALLBACK;
             break;
         default:
             return;
     }
     host_any = host_create_any(AF_INET);
     host_any6 = host_create_any(AF_INET6);
     hosts = linked_list_create_with_items(host_any, host_any6, NULL);
     my_ts_list =    child->get_traffic_selectors(child, TRUE,  NULL, hosts);
     other_ts_list = child->get_traffic_selectors(child, FALSE, NULL, hosts);
     hosts->destroy(hosts);
     /* enumerate pairs of traffic selectors */
     e_my_ts = my_ts_list->create_enumerator(my_ts_list);
     while (e_my_ts->enumerate(e_my_ts, &my_ts))
     {
         e_other_ts = other_ts_list->create_enumerator(other_ts_list);
         while (e_other_ts->enumerate(e_other_ts, &other_ts))
         {
             if (my_ts->get_type(my_ts) != other_ts->get_type(other_ts))
             {
                 continue;
             }
             if (my_ts->get_protocol(my_ts) &&
                 other_ts->get_protocol(other_ts) &&
                 my_ts->get_protocol(my_ts) != other_ts->get_protocol(other_ts))
             {
                 continue;
             }
             /* uninstall out policy */
             status |= hydra->kernel_interface->del_policy(
                             hydra->kernel_interface, host_any, host_any,
                             my_ts, other_ts, POLICY_OUT, policy_type,
                             &sa, child->get_mark(child, FALSE),
                             policy_prio);
             /* uninstall in policy */
             status |= hydra->kernel_interface->del_policy(
                             hydra->kernel_interface, host_any, host_any,
                             other_ts, my_ts, POLICY_IN, policy_type,
                             &sa, child->get_mark(child, TRUE),
                             policy_prio);
             /* uninstall forward policy */
             status |= hydra->kernel_interface->del_policy(
                             hydra->kernel_interface, host_any, host_any,
                             other_ts, my_ts, POLICY_FWD, policy_type,
                             &sa, child->get_mark(child, TRUE),
                             policy_prio);
         }
         e_other_ts->destroy(e_other_ts);
     }
     e_my_ts->destroy(e_my_ts);
     my_ts_list->destroy_offset(my_ts_list,
                                offsetof(traffic_selector_t, destroy));
     other_ts_list->destroy_offset(other_ts_list,
                                offsetof(traffic_selector_t, destroy));
     host_any6->destroy(host_any6);
     host_any->destroy(host_any);
     if (status != SUCCESS)
     {
         DBG1(DBG_CFG, "uninstalling shunt %N 'policy %s' failed",
              ipsec_mode_names, child->get_mode(child), child->get_name(child));
     }
 }