strongSwan: settings_types
settings_types
settings
Classes
struct kv_t
struct section_t
Typedefs
typedef struct kv_t kv_t
typedef struct section_t section_t
Functions
kv_t * settings_kv_create (char *key, char *value)
void settings_kv_destroy (kv_t *this, array_t *contents)
void settings_kv_set (kv_t *kv, char *value, array_t *contents)
void settings_kv_add (section_t *section, kv_t *kv, array_t *contents)
section_t * settings_section_create (char *name)
void settings_section_destroy (section_t *this, array_t *contents)
void settings_section_add (section_t *parent, section_t *section, array_t *contents)
void settings_section_extend (section_t *base, section_t *extension, array_t *contents, bool purge)
int settings_section_find (const void *a, const void *b)
int settings_section_sort (const void *a, const void *b, void *user)
int settings_kv_find (const void *a, const void *b)
int settings_kv_sort (const void *a, const void *b, void *user)
Detailed Description
Internal data types and functions shared between the parser and t.
Typedef Documentation
typedef struct kv_t kv_t
Definition at line 26 of file settings_types.h.
typedef struct section_t section_t
Definition at line 27 of file settings_types.h.
Function Documentation
void settings_kv_add (section_t * section, kv_t * kv, array_t * contents)
Add the given key/value pair to the given section.
Parameters
section section to add pair to
kv key/value pair to add (gets adopted)
contents optional array to store replaced values in
Definition at line 114 of file settings_types.c.
References array_bsearch(), array_insert_create(), array_sort(), ARRAY_TAIL, found, kv_t::key, section_t::kv, section_t::kv_order, settings_kv_destroy(), settings_kv_find(), settings_kv_set(), settings_kv_sort(), and kv_t::value.
Referenced by add_setting(), find_value_buffered(), and settings_section_extend().
 {
     kv_t *found;
     if (array_bsearch(section->kv, kv->key, settings_kv_find, &found) == -1)
     {
         array_insert_create(&section->kv, ARRAY_TAIL, kv);
         array_sort(section->kv, settings_kv_sort, NULL);
         array_insert_create(&section->kv_order, ARRAY_TAIL, kv);
     }
     else
     {
         settings_kv_set(found, kv->value, contents);
         kv->value = NULL;
         settings_kv_destroy(kv, NULL);
     }
 }
kv_t* settings_kv_create (char * key, char * value)
Create a key/value pair.
Parameters
key key (gets adopted)
value value (gets adopted)
Returns
allocated key/value pair
Definition at line 21 of file settings_types.c.
References INIT.
Referenced by find_value_buffered(), and yyparse().
 {
     kv_t *this;
     INIT(this,
         .key = key,
         .value = value,
     );
     return this;
 }
void settings_kv_destroy (kv_t * this, array_t * contents)
Destroy a key/value pair.
Parameters
this key/value pair to destroy
contents optional array to store the value in
Definition at line 35 of file settings_types.c.
References array_insert(), ARRAY_TAIL, free(), key, and value.
Referenced by kv_destroy(), settings_kv_add(), settings_section_extend(), and yydestruct().
 {
     free(this->key);
     if (contents && this->value)
     {
         array_insert(contents, ARRAY_TAIL, this->value);
     }
     else
     {
         free(this->value);
     }
     free(this);
 }
int settings_kv_find (const void * a, const void * b)
Callback to find a key/value pair by key
Definition at line 307 of file settings_types.c.
References a, b, kv_t::key, and key.
Referenced by find_value_buffered(), settings_kv_add(), and settings_section_extend().
 {
     const char *key = a;
     const kv_t *item = b;
     return strcmp(key, item->key);
 }
void settings_kv_set (kv_t * kv, char * value, array_t * contents)
Set the value of the given key/value pair.
Parameters
kv key/value pair
value new value (gets adopted), may be NULL
contents optional array to store replaced values in
Definition at line 89 of file settings_types.c.
References array_insert(), ARRAY_TAIL, free(), streq(), kv_t::value, and value.
Referenced by set_value(), and settings_kv_add().
 {
     if (value && kv->value && streq(value, kv->value))
     {   /* no update required */
         free(value);
         return;
     }
     /* if the new value was shorter we could overwrite the existing one but that
      * could lead to reads of partially updated values from other threads that
      * have a pointer to the existing value, so we replace it anyway */
     if (kv->value && contents)
     {
         array_insert(contents, ARRAY_TAIL, kv->value);
     }
     else
     {
         free(kv->value);
     }
     kv->value = value;
 }
int settings_kv_sort (const void * a, const void * b, void * user)
Callback to sort kv pairs by key
Definition at line 317 of file settings_types.c.
References a, b, and kv_t::key.
Referenced by settings_kv_add(), and settings_section_extend().
 {
     const kv_t *kva = a, *kvb = b;
     return strcmp(kva->key, kvb->key);
 }
void settings_section_add (section_t * parent, section_t * section, array_t * contents)
Add the given section to the given parent section.
Parameters
parent section to add section to
section section to add (gets adopted)
contents optional array to store replaced values in
Definition at line 158 of file settings_types.c.
References add_section(), and FALSE.
Referenced by add_section(), find_section_buffered(), and find_value_buffered().
 {
     add_section(parent, section, contents, FALSE);
 }
section_t* settings_section_create (char * name)
Create a section with the given name.
Parameters
name name (gets adopted)
Returns
allocated section
Definition at line 52 of file settings_types.c.
References INIT.
Referenced by find_section_buffered(), find_value_buffered(), load_internal(), main(), push_section(), and settings_create_base().
 {
     section_t *this;
     INIT(this,
         .name = name,
     );
     return this;
 }
void settings_section_destroy (section_t * this, array_t * contents)
Destroy a section.
Parameters
this section to destroy
contents optional array to store values of removed key/value pairs
Definition at line 75 of file settings_types.c.
References array_destroy(), array_destroy_function(), free(), kv_destroy(), name, and section_destroy().
Referenced by add_section(), load_internal(), main(), METHOD(), section_destroy(), section_purge(), settings_section_extend(), and yydestruct().
 {
     array_destroy_function(this->sections, (void*)section_destroy, contents);
     array_destroy(this->sections_order);
     array_destroy_function(this->kv, (void*)kv_destroy, contents);
     array_destroy(this->kv_order);
     array_destroy(this->fallbacks);
     free(this->name);
     free(this);
 }
void settings_section_extend (section_t * base, section_t * extension, array_t * contents, bool purge)
Extend the first section with the values and sub-sections of the second section, from where they are consequently removed.
Parameters
base base section to extend
extension section whose data is extracted
contents optional array to store replaced values in
purge TRUE to remove settings and sections not found in the extension (unless (sub-)sections have/are fallbacks)
Definition at line 196 of file settings_types.c.
References add_section(), array_bsearch(), array_create_enumerator(), array_destroy(), array_insert(), array_insert_create(), array_remove(), array_remove_at(), array_sort(), ARRAY_TAIL, enumerator_t::destroy, enumerator_t::enumerate, kv_t::key, section_t::kv, section_t::kv_order, section_t::name, section, section_purge(), section_t::sections, section_t::sections_order, settings_kv_add(), settings_kv_destroy(), settings_kv_find(), settings_kv_sort(), settings_section_destroy(), settings_section_find(), and settings_section_sort().
Referenced by add_section(), and load_internal().
 {
     enumerator_t *enumerator;
     section_t *section;
     kv_t *kv;
     array_t *sections = NULL, *kvs = NULL;
     int idx;
     if (purge)
     {   /* remove sections and settings in base not found in extension, the
          * others are removed too (from the _order list) so they can be inserted
          * in the order found in extension */
         enumerator = array_create_enumerator(base->sections_order);
         while (enumerator->enumerate(enumerator, (void**)&section))
         {
             if (array_bsearch(extension->sections, section->name,
                               settings_section_find, NULL) == -1)
             {
                 idx = array_bsearch(base->sections, section->name,
                                     settings_section_find, NULL);
                 if (section_purge(section, contents))
                 {   /* only remove them if we can purge them */
                     array_remove(base->sections, idx, NULL);
                     array_remove_at(base->sections_order, enumerator);
                     settings_section_destroy(section, contents);
                 }
             }
             else
             {
                 array_remove_at(base->sections_order, enumerator);
                 array_insert_create(&sections, ARRAY_TAIL, section);
                 array_sort(sections, settings_section_sort, NULL);
             }
         }
         enumerator->destroy(enumerator);
         while (array_remove(base->kv_order, 0, &kv))
         {
             if (array_bsearch(extension->kv, kv->key, settings_kv_find,
                               NULL) == -1)
             {
                 idx = array_bsearch(base->kv, kv->key, settings_kv_find, NULL);
                 array_remove(base->kv, idx, NULL);
                 settings_kv_destroy(kv, contents);
             }
             else
             {
                 array_insert_create(&kvs, ARRAY_TAIL, kv);
                 array_sort(kvs, settings_kv_sort, NULL);
             }
         }
     }
     while (array_remove(extension->sections_order, 0, &section))
     {
         idx = array_bsearch(sections, section->name,
                             settings_section_find, NULL);
         if (idx != -1)
         {
             section_t *existing;
             array_remove(sections, idx, &existing);
             array_insert(base->sections_order, ARRAY_TAIL, existing);
         }
         idx = array_bsearch(extension->sections, section->name,
                             settings_section_find, NULL);
         array_remove(extension->sections, idx, NULL);
         add_section(base, section, contents, purge);
     }
     while (array_remove(extension->kv_order, 0, &kv))
     {
         idx = array_bsearch(kvs, kv->key, settings_kv_find, NULL);
         if (idx != -1)
         {
             kv_t *existing;
             array_remove(kvs, idx, &existing);
             array_insert(base->kv_order, ARRAY_TAIL, existing);
         }
         idx = array_bsearch(extension->kv, kv->key, settings_kv_find, NULL);
         array_remove(extension->kv, idx, NULL);
         settings_kv_add(base, kv, contents);
     }
     array_destroy(sections);
     array_destroy(kvs);
 }
int settings_section_find (const void * a, const void * b)
Callback to find a section by name
Definition at line 288 of file settings_types.c.
References a, b, key, and section_t::name.
Referenced by add_section(), find_section_buffered(), find_sections_buffered(), find_value_buffered(), section_purge(), and settings_section_extend().
 {
     const char *key = a;
     const section_t *item = b;
     return strcmp(key, item->name);
 }
int settings_section_sort (const void * a, const void * b, void * user)
Callback to sort sections by name
Definition at line 298 of file settings_types.c.
References a, b, section_t::name, and sa.
Referenced by add_section(), and settings_section_extend().
 {
     const section_t *sa = a, *sb = b;
     return strcmp(sa->name, sb->name);
 }