strongSwan: dictionary_t Struct Reference
dictionary_t Struct Reference
dictionary
#include "dictionary.h"
Public Attributes
enumerator_t *(* create_enumerator)(dictionary_t *this)
void *(* get)(dictionary_t *this, const void *key)
void(* destroy)(dictionary_t *this)
Detailed Description
Interface for read-only dictionaries.
Definition at line 31 of file dictionary.h.
Member Data Documentation
enumerator_t*(* dictionary_t::create_enumerator)(dictionary_t *this)
Create an enumerator over the key/value pairs in the dictionary.
Returns
enumerator over (const void *key, void *value)
Definition at line 38 of file dictionary.h.
Referenced by load_ca(), load_conn(), and load_setup().
void(* dictionary_t::destroy)(dictionary_t *this)
Destroys a dictionary object.
Definition at line 52 of file dictionary.h.
Referenced by load_ca(), load_conn(), load_setup(), and START_TEST().
void*(* dictionary_t::get)(dictionary_t *this, const void *key)
Returns the value with the given key, if the dictionary contains such an entry, otherwise NULL is returned.
Parameters
key the key of the requested value
Returns
the value, NULL if not found
Definition at line 47 of file dictionary.h.
Referenced by START_TEST().
The documentation for this struct was generated from the following file:
dictionary.h