strongSwan: rr_t Struct Reference
rr_t Struct Reference
rr
#include "rr.h"
Public Attributes
char *(* get_name)(rr_t *this)
rr_type_t(* get_type)(rr_t *this)
rr_class_t(* get_class)(rr_t *this)
uint32_t(* get_ttl)(rr_t *this)
chunk_t(* get_rdata)(rr_t *this)
void(* destroy)(rr_t *this)
Detailed Description
A DNS Resource Record.
Represents a Resource Record of the Domain Name System as defined in RFC 1035.
Definition at line 222 of file rr.h.
Member Data Documentation
void(* rr_t::destroy)(rr_t *this)
Destroy the Resource Record.
Definition at line 265 of file rr.h.
rr_class_t(* rr_t::get_class)(rr_t *this)
Get the class of this RR.
Returns
RR class
Definition at line 243 of file rr.h.
char*(* rr_t::get_name)(rr_t *this)
Get the NAME of the owner of this RR.
Returns
owner name as string
Definition at line 229 of file rr.h.
Referenced by main().
chunk_t(* rr_t::get_rdata)(rr_t *this)
Get the content of the RDATA field as chunk.
The data pointed by the chunk is still owned by the RR. Clone it if needed.
Returns
RDATA field as chunk
Definition at line 260 of file rr.h.
Referenced by dnscert_create_frm_rr(), ipseckey_create_frm_rr(), main(), and METHOD().
uint32_t(* rr_t::get_ttl)(rr_t *this)
Get the Time to Live (TTL) of this RR.
Returns
Time to Live
Definition at line 250 of file rr.h.
rr_type_t(* rr_t::get_type)(rr_t *this)
Get the type of this RR.
Returns
RR type
Definition at line 236 of file rr.h.
Referenced by dnscert_create_frm_rr(), and ipseckey_create_frm_rr().
The documentation for this struct was generated from the following file:
rr.h