strongSwan: vici_authority
vici_authority
vici
Classes
struct vici_authority_t
Typedefs
typedef struct vici_authority_t vici_authority_t
Functions
vici_authority_t * vici_authority_create (vici_dispatcher_t *dispatcher, vici_cred_t *cred)
Detailed Description
Typedef Documentation
typedef struct vici_authority_t vici_authority_t
Definition at line 27 of file vici_authority.h.
Function Documentation
vici_authority_t* vici_authority_create (vici_dispatcher_t * dispatcher, vici_cred_t * cred)
Create a vici_authority instance.
Parameters
dispatcher dispatcher to receive requests from
cred in-memory credential backend managed by VICI
Returns
authority backend
See header
Definition at line 724 of file vici_authority.c.
References INIT, linked_list_create(), manage_commands(), nop(), return_null(), rwlock_create(), RWLOCK_TYPE_DEFAULT, and TRUE.
Referenced by register_vici().
 {
     private_vici_authority_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_private_enumerator = (void*)return_null,
                 .create_cert_enumerator = (void*)return_null,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = _create_cdp_enumerator,
                 .cache_cert = (void*)nop,
             },
             .check_for_hash_and_url = _check_for_hash_and_url,
             .destroy = _destroy,
         },
         .dispatcher = dispatcher,
         .cred = cred,
         .authorities = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     manage_commands(this, TRUE);
     return &this->public;
 }