strongSwan: tnc_imc_manager.c File Reference
tnc_imc_manager.c File Reference
#include "tnc_imc_manager.h"
#include "tnc_imc.h"
#include <tncifimc.h>
#include <utils/debug.h>
#include <threading/rwlock.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
Classes
struct private_tnc_imc_manager_t
Typedefs
typedef struct
private_tnc_imc_manager_t private_tnc_imc_manager_t
Functions
METHOD (imc_manager_t, add, bool, private_tnc_imc_manager_t *this, imc_t *imc)
METHOD (imc_manager_t, remove_, imc_t *, private_tnc_imc_manager_t *this, TNC_IMCID id)
METHOD (imc_manager_t, load, bool, private_tnc_imc_manager_t *this, char *name, char *path)
METHOD (imc_manager_t, load_from_functions, bool, private_tnc_imc_manager_t *this, char *name, TNC_IMC_InitializePointer initialize, TNC_IMC_NotifyConnectionChangePointer notify_connection_change, TNC_IMC_BeginHandshakePointer begin_handshake, TNC_IMC_ReceiveMessagePointer receive_message, TNC_IMC_ReceiveMessageLongPointer receive_message_long, TNC_IMC_BatchEndingPointer batch_ending, TNC_IMC_TerminatePointer terminate, TNC_IMC_ProvideBindFunctionPointer provide_bind_function)
METHOD (imc_manager_t, is_registered, bool, private_tnc_imc_manager_t *this, TNC_IMCID id)
METHOD (imc_manager_t, reserve_id, bool, private_tnc_imc_manager_t *this, TNC_IMCID id, TNC_UInt32 *new_id)
METHOD (imc_manager_t, get_preferred_language, char *, private_tnc_imc_manager_t *this)
METHOD (imc_manager_t, notify_connection_change, void, private_tnc_imc_manager_t *this, TNC_ConnectionID id, TNC_ConnectionState state)
METHOD (imc_manager_t, begin_handshake, void, private_tnc_imc_manager_t *this, TNC_ConnectionID id)
METHOD (imc_manager_t, set_message_types, TNC_Result, private_tnc_imc_manager_t *this, TNC_IMCID id, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
METHOD (imc_manager_t, set_message_types_long, TNC_Result, private_tnc_imc_manager_t *this, TNC_IMCID id, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
METHOD (imc_manager_t, receive_message, void, private_tnc_imc_manager_t *this, TNC_ConnectionID connection_id, bool excl, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
METHOD (imc_manager_t, batch_ending, void, private_tnc_imc_manager_t *this, TNC_ConnectionID id)
METHOD (imc_manager_t, destroy, void, private_tnc_imc_manager_t *this)
imc_manager_t * tnc_imc_manager_create (void)
Typedef Documentation
typedef struct private_tnc_imc_manager_t private_tnc_imc_manager_t
Definition at line 27 of file tnc_imc_manager.c.
Function Documentation
METHOD (imc_manager_t , add , bool , private_tnc_imc_manager_t * this, imc_t * imc)
Definition at line 60 of file tnc_imc_manager.c.
References DBG1, DBG_TNC, FALSE, imc_t::get_id, imc_t::get_name, id_mutex, imc_t::initialize, mutex_t::lock, lock, imc_t::provide_bind_function, imc_t::set_id, imc_t::terminate, TNC_IFIMC_VERSION_1, TNC_RESULT_SUCCESS, TNC_TNCC_BindFunction(), TRUE, spinlock_t::unlock, mutex_t::unlock, and version.
 {
     TNC_Version version;
     TNC_IMCID imc_id;
     this->id_mutex->lock(this->id_mutex);
     imc_id = this->next_imc_id++;
     this->id_mutex->unlock(this->id_mutex);
     imc->set_id(imc, imc_id);
     if (imc->initialize(imc_id, TNC_IFIMC_VERSION_1,
                         TNC_IFIMC_VERSION_1, &version) != TNC_RESULT_SUCCESS)
     {
         DBG1(DBG_TNC, "IMC \"%s\" failed to initialize", imc->get_name(imc));
         return FALSE;
     }
     this->lock->write_lock(this->lock);
     this->imcs->insert_last(this->imcs, imc);
     this->lock->unlock(this->lock);
     if (imc->provide_bind_function(imc->get_id(imc),
                                    TNC_TNCC_BindFunction) != TNC_RESULT_SUCCESS)
     {
         if (imc->terminate)
         {
             imc->terminate(imc->get_id(imc));
         }
         DBG1(DBG_TNC, "IMC \"%s\" failed to obtain bind function",
              imc->get_name(imc));
         this->lock->write_lock(this->lock);
         this->imcs->remove_last(this->imcs, (void**)&imc);
         this->lock->unlock(this->lock);
         return FALSE;
     }
     return TRUE;
 }
METHOD (imc_manager_t , remove_ , imc_t * , private_tnc_imc_manager_t * this, TNC_IMCID id)
Definition at line 98 of file tnc_imc_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, imc_t::get_id, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc, *removed_imc = NULL;
     this->lock->write_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (id == imc->get_id(imc))
         {
             this->imcs->remove_at(this->imcs, enumerator);
             removed_imc = imc;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return removed_imc;
 }
METHOD (imc_manager_t , load , bool , private_tnc_imc_manager_t * this, char * name, char * path)
Definition at line 121 of file tnc_imc_manager.c.
References add(), DBG1, DBG_TNC, imc_t::destroy, FALSE, imc_t::get_id, name, path, tnc_imc_create(), and TRUE.
 {
     imc_t *imc;
     imc = tnc_imc_create(name, path);
     if (!imc)
     {
         return FALSE;
     }
     if (!add(this, imc))
     {
         imc->destroy(imc);
         return FALSE;
     }
     DBG1(DBG_TNC, "IMC %u \"%s\" loaded from '%s'", imc->get_id(imc), name, path);
     return TRUE;
 }
METHOD (imc_manager_t , load_from_functions , bool , private_tnc_imc_manager_t * this, char * name, TNC_IMC_InitializePointer initialize, TNC_IMC_NotifyConnectionChangePointer notify_connection_change, TNC_IMC_BeginHandshakePointer begin_handshake, TNC_IMC_ReceiveMessagePointer receive_message, TNC_IMC_ReceiveMessageLongPointer receive_message_long, TNC_IMC_BatchEndingPointer batch_ending, TNC_IMC_TerminatePointer terminate, TNC_IMC_ProvideBindFunctionPointer provide_bind_function)
Definition at line 140 of file tnc_imc_manager.c.
References add(), DBG1, DBG_TNC, imc_t::destroy, FALSE, imc_t::get_id, name, tnc_imc_create_from_functions(), and TRUE.
 {
     imc_t *imc;
     imc = tnc_imc_create_from_functions(name,
                                         initialize, notify_connection_change,
                                         begin_handshake, receive_message,
                                         receive_message_long, batch_ending,
                                         terminate, provide_bind_function);
     if (!imc)
     {
         return FALSE;
     }
     if (!add(this, imc))
     {
         imc->destroy(imc);
         return FALSE;
     }
     DBG1(DBG_TNC, "IMC %u \"%s\" loaded", imc->get_id(imc), name);
     return TRUE;
 }
METHOD (imc_manager_t , is_registered , bool , private_tnc_imc_manager_t * this, TNC_IMCID id)
Definition at line 171 of file tnc_imc_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, imc_t::has_id, lock, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc;
     bool found = FALSE;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (imc->has_id(imc, id))
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (imc_manager_t , reserve_id , bool , private_tnc_imc_manager_t * this, TNC_IMCID id, TNC_UInt32 * new_id)
Definition at line 194 of file tnc_imc_manager.c.
References imc_t::add_id, DBG2, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, imc_t::get_id, id_mutex, mutex_t::lock, lock, TRUE, spinlock_t::unlock, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc;
     bool found = FALSE;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (id == imc->get_id(imc))
         {
             found = TRUE;
             this->id_mutex->lock(this->id_mutex);
             *new_id = this->next_imc_id++;
             this->id_mutex->unlock(this->id_mutex);
             imc->add_id(imc, *new_id);
             DBG2(DBG_TNC, "additional ID %u reserved for IMC with primary ID %u",
                           *new_id, id);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (imc_manager_t , get_preferred_language , char * , private_tnc_imc_manager_t * this)
Definition at line 223 of file tnc_imc_manager.c.
References settings_t::get_str, lib, library_t::ns, and library_t::settings.
 {
     return lib->settings->get_str(lib->settings,
                 "%s.plugins.tnc-imc.preferred_language", "en", lib->ns);
 }
METHOD (imc_manager_t , notify_connection_change , void , private_tnc_imc_manager_t * this, TNC_ConnectionID id, TNC_ConnectionState state)
Definition at line 230 of file tnc_imc_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, imc_t::get_id, id, lock, imc_t::notify_connection_change, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (imc->notify_connection_change)
         {
             imc->notify_connection_change(imc->get_id(imc), id, state);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (imc_manager_t , begin_handshake , void , private_tnc_imc_manager_t * this, TNC_ConnectionID id)
Definition at line 250 of file tnc_imc_manager.c.
References imc_t::begin_handshake, enumerator_t::destroy, enumerator_t::enumerate, imc_t::get_id, id, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         imc->begin_handshake(imc->get_id(imc), id);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (imc_manager_t , set_message_types , TNC_Result , private_tnc_imc_manager_t * this, TNC_IMCID id, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
Definition at line 266 of file tnc_imc_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, imc_t::get_id, lock, result, imc_t::set_message_types, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc;
     TNC_Result result = TNC_RESULT_FATAL;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (id == imc->get_id(imc))
         {
             imc->set_message_types(imc, supported_types, type_count);
             result = TNC_RESULT_SUCCESS;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return result;
 }
METHOD (imc_manager_t , set_message_types_long , TNC_Result , private_tnc_imc_manager_t * this, TNC_IMCID id, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
Definition at line 291 of file tnc_imc_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, imc_t::get_id, lock, result, imc_t::set_message_types_long, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc;
     TNC_Result result = TNC_RESULT_FATAL;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (id == imc->get_id(imc))
         {
             imc->set_message_types_long(imc, supported_vids, supported_subtypes,
                                         type_count);
             result = TNC_RESULT_SUCCESS;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return result;
 }
METHOD (imc_manager_t , receive_message , void , private_tnc_imc_manager_t * this, TNC_ConnectionID connection_id, bool excl, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
Definition at line 318 of file tnc_imc_manager.c.
References DBG2, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, FALSE, imc_t::get_id, imc_t::has_id, lock, msg, imc_t::receive_message, imc_t::receive_message_long, TNC_MESSAGE_FLAGS_EXCLUSIVE, TNC_SUBTYPE_ANY, TNC_VENDORID_ANY, TRUE, imc_t::type_supported, and spinlock_t::unlock.
 {
     bool type_supported = FALSE;
     TNC_MessageType msg_type;
     TNC_UInt32 msg_flags;
     enumerator_t *enumerator;
     imc_t *imc;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (imc->type_supported(imc, msg_vid, msg_subtype) &&
             (!excl || (excl && imc->has_id(imc, dst_imc_id))))
         {
             if (imc->receive_message_long && src_imv_id)
             {
                 type_supported = TRUE;
                 msg_flags = excl ? TNC_MESSAGE_FLAGS_EXCLUSIVE : 0;
                 imc->receive_message_long(imc->get_id(imc), connection_id,
                                 msg_flags, msg, msg_len, msg_vid, msg_subtype,
                                 src_imv_id, dst_imc_id);
             }
             else if (imc->receive_message && msg_vid <= TNC_VENDORID_ANY &&
                      msg_subtype <= TNC_SUBTYPE_ANY)
             {
                 type_supported = TRUE;
                 msg_type = (msg_vid << 8) | msg_subtype;
                 imc->receive_message(imc->get_id(imc), connection_id,
                                      msg, msg_len, msg_type);
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!type_supported)
     {
         DBG2(DBG_TNC, "message type 0x%06x/0x%08x not supported by any IMC",
              msg_vid, msg_subtype);
     }
 }
METHOD (imc_manager_t , batch_ending , void , private_tnc_imc_manager_t * this, TNC_ConnectionID id)
Definition at line 370 of file tnc_imc_manager.c.
References imc_t::batch_ending, enumerator_t::destroy, enumerator_t::enumerate, imc_t::get_id, id, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     imc_t *imc;
     this->lock->read_lock(this->lock);
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc))
     {
         if (imc->batch_ending)
         {
             imc->batch_ending(imc->get_id(imc), id);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (imc_manager_t , destroy , void , private_tnc_imc_manager_t * this)
Definition at line 389 of file tnc_imc_manager.c.
References DBG1, DBG_TNC, spinlock_t::destroy, mutex_t::destroy, imc_t::destroy, free(), imc_t::get_id, imc_t::get_name, id_mutex, lock, SUCCESS, imc_t::terminate, and TNC_RESULT_SUCCESS.
 {
     imc_t *imc;
     while (this->imcs->remove_last(this->imcs, (void**)&imc) == SUCCESS)
     {
         if (imc->terminate &&
             imc->terminate(imc->get_id(imc)) != TNC_RESULT_SUCCESS)
         {
             DBG1(DBG_TNC, "IMC \"%s\" not terminated successfully",
                            imc->get_name(imc));
         }
         imc->destroy(imc);
     }
     this->imcs->destroy(this->imcs);
     this->lock->destroy(this->lock);
     this->id_mutex->destroy(this->id_mutex);
     free(this);
 }