strongSwan: rng
rng
crypto
Classes
struct rng_t
Typedefs
typedef enum rng_quality_t rng_quality_t
typedef struct rng_t rng_t
Enumerations
enum rng_quality_t { RNG_WEAK, RNG_STRONG, RNG_TRUE }
Functions
bool rng_get_bytes_not_zero (rng_t *rng, size_t len, u_int8_t *buffer, bool all) __attribute__((warn_unused_result))
bool rng_allocate_bytes_not_zero (rng_t *rng, size_t len, chunk_t *chunk, bool all) __attribute__((warn_unused_result))
Variables
enum_name_t * rng_quality_names
Detailed Description
Typedef Documentation
typedef enum rng_quality_t rng_quality_t
Definition at line 25 of file rng.h.
typedef struct rng_t rng_t
Definition at line 26 of file rng.h.
Enumeration Type Documentation
enum rng_quality_t
Quality of generated random bytes.
Enumerator
RNG_WEAK
weak randomness, usable for nonces, IVs
RNG_STRONG
stronger randomness, usable for session keys
RNG_TRUE
true random key material
Definition at line 33 of file rng.h.
                    {
     RNG_WEAK,
     RNG_STRONG,
     RNG_TRUE,
 };
Function Documentation
bool rng_allocate_bytes_not_zero (rng_t * rng, size_t len, chunk_t * chunk, bool all)
Wrapper around rng_t.allocate_bytes() ensuring that either all bytes or at least the first byte is not zero.
Parameters
rng rng_t object
len number of bytes to get
chunk chunk that stores the generated bytes (allocated)
all TRUE if all bytes have to be non-zero, FALSE for first
Returns
TRUE if bytes successfully written
Definition at line 53 of file crypto/rngs/rng.c.
References chunk_alloc, chunk_clear(), FALSE, chunk_t::ptr, rng_get_bytes_not_zero(), and TRUE.
Referenced by acert(), issue(), and self().
 {
     *chunk = chunk_alloc(len);
     if (!rng_get_bytes_not_zero(rng, len, chunk->ptr, all))
     {
         chunk_clear(chunk);
         return FALSE;
     }
     return TRUE;
 }
bool rng_get_bytes_not_zero (rng_t * rng, size_t len, u_int8_t * buffer, bool all)
Wrapper around rng_t.get_bytes() ensuring that either all bytes or at least the first byte is not zero.
Parameters
rng rng_t object
len number of bytes to get
buffer pointer where the generated bytes will be written
all TRUE if all bytes have to be non-zero, FALSE for first
Returns
TRUE if bytes successfully written
Definition at line 28 of file crypto/rngs/rng.c.
References check, FALSE, rng_t::get_bytes, min, and TRUE.
Referenced by METHOD(), and rng_allocate_bytes_not_zero().
 {
     u_int8_t *pos = buffer, *check = buffer + (all ? len : min(1, len));
     if (!rng->get_bytes(rng, len, pos))
     {
         return FALSE;
     }
     for (; pos < check; pos++)
     {
         while (*pos == 0)
         {
             if (!rng->get_bytes(rng, 1, pos))
             {
                 return FALSE;
             }
         }
     }
     return TRUE;
 }
Variable Documentation
enum_name_t* rng_quality_names
enum name for rng_quality_t.
Referenced by compute_prime(), create_generic(), list_algs(), METHOD(), nonce_nonceg_create(), plugin_feature_get_string(), and transform_get_enum_names().