strongSwan: crl_t Struct Reference
crl_t Struct Reference
crl
#include "crl.h"
Public Attributes
certificate_t certificate
chunk_t(* get_serial)(crl_t *this)
chunk_t(* get_authKeyIdentifier)(crl_t *this)
bool(* is_delta_crl)(crl_t *this, chunk_t *base_crl)
enumerator_t *(* create_delta_crl_uri_enumerator)(crl_t *this)
enumerator_t *(* create_enumerator)(crl_t *this)
Detailed Description
X509 certificate revocation list (CRL) interface definition.
Definition at line 65 of file crl.h.
Member Data Documentation
certificate_t crl_t::certificate
Implements (parts of) the certificate_t interface
Definition at line 70 of file crl.h.
Referenced by crl_is_newer(), and METHOD().
enumerator_t*(* crl_t::create_delta_crl_uri_enumerator)(crl_t *this)
Create an enumerator over Freshest CRL distribution points and issuers.
Returns
enumerator over x509_cdp_t
Definition at line 99 of file crl.h.
Referenced by check_delta_crl(), and print_crl().
enumerator_t*(* crl_t::create_enumerator)(crl_t *this)
Create an enumerator over all revoked certificates.
The enumerator takes 3 pointer arguments: chunk_t serial, time_t revocation_date, crl_reason_t reason
Returns
enumerator over revoked certificates.
Definition at line 109 of file crl.h.
Referenced by get_better_crl(), print_crl(), sign_crl(), and stroke_list_crls().
chunk_t(* crl_t::get_authKeyIdentifier)(crl_t *this)
Get the the authorityKeyIdentifier.
Returns
authKeyIdentifier chunk, point to internal data
Definition at line 84 of file crl.h.
Referenced by METHOD(), print_crl(), and stroke_list_crls().
chunk_t(* crl_t::get_serial)(crl_t *this)
Get the CRL serial number.
Returns
chunk pointing to internal crlNumber
Definition at line 77 of file crl.h.
Referenced by crl_is_newer(), get_better_crl(), print_crl(), sign_crl(), and stroke_list_crls().
bool(* crl_t::is_delta_crl)(crl_t *this, chunk_t *base_crl)
Is this CRL a delta CRL?
Parameters
base_crl gets to baseCrlNumber, if this is a delta CRL
Returns
TRUE if delta CRL
Definition at line 92 of file crl.h.
Referenced by get_better_crl(), print_crl(), and stroke_list_crls().
The documentation for this struct was generated from the following file:
crl.h