strongSwan: dhcp_socket
dhcp_socket
dhcp
Classes
struct dhcp_socket_t
Typedefs
typedef struct dhcp_socket_t dhcp_socket_t
Functions
dhcp_socket_t * dhcp_socket_create ()
Detailed Description
Typedef Documentation
typedef struct dhcp_socket_t dhcp_socket_t
Definition at line 24 of file dhcp_socket.h.
Function Documentation
dhcp_socket_t* dhcp_socket_create ()
Create a dhcp_socket instance.
See header
Definition at line 670 of file dhcp_socket.c.
References watcher_t::add, bind, bind_to_device(), BOOTREPLY, condvar_create(), CONDVAR_TYPE_DEFAULT, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_CFG, DBG_NET, dest, destroy(), DHCP_CLIENT_PORT, DHCP_SERVER_PORT, dhcp_t, dst, FALSE, settings_t::get_bool, settings_t::get_str, host_create_from_string(), INIT, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, opcode, protocol, receive(), receive_dhcp(), rng, RNG_WEAK, send, setsockopt, library_t::settings, socket, source, strerror, library_t::watcher, and WATCHER_READ.
Referenced by plugin_cb().
 {
     private_dhcp_socket_t *this;
     struct sockaddr_in src = {
         .sin_family = AF_INET,
         .sin_port = htons(DHCP_CLIENT_PORT),
         .sin_addr = {
             .s_addr = INADDR_ANY,
         },
     };
     char *iface;
     int on = 1;
     struct sock_filter dhcp_filter_code[] = {
         BPF_STMT(BPF_LD+BPF_B+BPF_ABS,
                  offsetof(struct iphdr, protocol)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, IPPROTO_UDP, 0, 16),
         BPF_STMT(BPF_LD+BPF_H+BPF_ABS, sizeof(struct iphdr) +
                  offsetof(struct udphdr, source)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, DHCP_SERVER_PORT, 0, 14),
         BPF_STMT(BPF_LD+BPF_H+BPF_ABS, sizeof(struct iphdr) +
                  offsetof(struct udphdr, dest)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, DHCP_CLIENT_PORT, 0, 2),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, DHCP_SERVER_PORT, 0, 1),
         BPF_JUMP(BPF_JMP+BPF_JA, 0, 0, 10),
         BPF_STMT(BPF_LD+BPF_B+BPF_ABS, sizeof(struct iphdr) +
                  sizeof(struct udphdr) + offsetof(dhcp_t, opcode)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, BOOTREPLY, 0, 8),
         BPF_STMT(BPF_LD+BPF_B+BPF_ABS, sizeof(struct iphdr) +
                  sizeof(struct udphdr) + offsetof(dhcp_t, hw_type)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, ARPHRD_ETHER, 0, 6),
         BPF_STMT(BPF_LD+BPF_B+BPF_ABS, sizeof(struct iphdr) +
                  sizeof(struct udphdr) + offsetof(dhcp_t, hw_addr_len)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, 6, 0, 4),
         BPF_STMT(BPF_LD+BPF_W+BPF_ABS, sizeof(struct iphdr) +
                  sizeof(struct udphdr) + offsetof(dhcp_t, magic_cookie)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, 0x63825363, 0, 2),
         BPF_STMT(BPF_LD+BPF_W+BPF_LEN, 0),
         BPF_STMT(BPF_RET+BPF_A, 0),
         BPF_STMT(BPF_RET+BPF_K, 0),
     };
     struct sock_fprog dhcp_filter = {
         sizeof(dhcp_filter_code) / sizeof(struct sock_filter),
         dhcp_filter_code,
     };
     INIT(this,
         .public = {
             .enroll = _enroll,
             .release = _release,
             .destroy = _destroy,
         },
         .rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .discover = linked_list_create(),
         .request = linked_list_create(),
         .completed = linked_list_create(),
     );
     if (!this->rng)
     {
         DBG1(DBG_CFG, "unable to create RNG");
         destroy(this);
         return NULL;
     }
     this->identity_lease = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.dhcp.identity_lease", FALSE,
                                 lib->ns);
     this->force_dst = lib->settings->get_str(lib->settings,
                                 "%s.plugins.dhcp.force_server_address", FALSE,
                                 lib->ns);
     this->dst = host_create_from_string(lib->settings->get_str(lib->settings,
                                 "%s.plugins.dhcp.server", "255.255.255.255",
                                 lib->ns), DHCP_SERVER_PORT);
     iface = lib->settings->get_str(lib->settings, "%s.plugins.dhcp.interface",
                                    NULL, lib->ns);
     if (!this->dst)
     {
         DBG1(DBG_CFG, "configured DHCP server address invalid");
         destroy(this);
         return NULL;
     }
     this->send = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
     if (this->send == -1)
     {
         DBG1(DBG_CFG, "unable to create DHCP send socket: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     if (setsockopt(this->send, SOL_SOCKET, SO_REUSEADDR, &on, sizeof(on)) == -1)
     {
         DBG1(DBG_CFG, "unable to reuse DHCP socket address: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     if (setsockopt(this->send, SOL_SOCKET, SO_BROADCAST, &on, sizeof(on)) == -1)
     {
         DBG1(DBG_CFG, "unable to broadcast on DHCP socket: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     if (bind(this->send, (struct sockaddr*)&src, sizeof(src)) == -1)
     {
         DBG1(DBG_CFG, "unable to bind DHCP send socket: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     this->receive = socket(AF_PACKET, SOCK_DGRAM, htons(ETH_P_IP));
     if (this->receive == -1)
     {
         DBG1(DBG_NET, "opening DHCP receive socket failed: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     if (setsockopt(this->receive, SOL_SOCKET, SO_ATTACH_FILTER,
                    &dhcp_filter, sizeof(dhcp_filter)) < 0)
     {
         DBG1(DBG_CFG, "installing DHCP socket filter failed: %s",
              strerror(errno));
         destroy(this);
         return NULL;
     }
     if (iface)
     {
         if (!bind_to_device(this->send, iface) ||
             !bind_to_device(this->receive, iface))
         {
             destroy(this);
             return NULL;
         }
     }
     lib->watcher->add(lib->watcher, this->receive, WATCHER_READ,
                       (watcher_cb_t)receive_dhcp, this);
     return &this->public;
 }