strongSwan: signer_t Struct Reference
signer_t Struct Reference
signer
#include "signer.h"
Public Attributes
bool(* get_signature)(signer_t *this, chunk_t data, u_int8_t *buffer) __attribute__((warn_unused_result))
bool(* allocate_signature)(signer_t *this, chunk_t data, chunk_t *chunk) __attribute__((warn_unused_result))
bool(* verify_signature)(signer_t *this, chunk_t data, chunk_t signature)
size_t(* get_block_size)(signer_t *this)
size_t(* get_key_size)(signer_t *this)
bool(* set_key)(signer_t *this, chunk_t key) __attribute__((warn_unused_result))
void(* destroy)(signer_t *this)
Detailed Description
Generic interface for a symmetric signature algorithm.
Definition at line 87 of file signer.h.
Member Data Documentation
bool(* signer_t::allocate_signature)(signer_t *this, chunk_t data, chunk_t *chunk) __attribute__((warn_unused_result))
Generate a signature and allocate space for it.
If chunk is NULL, data is processed and prepended to a next call until chunk is a valid chunk pointer.
Parameters
data a chunk containing the data to sign
chunk chunk which will hold the allocated signature
Returns
TRUE if signature allocated successfully
Definition at line 111 of file signer.h.
Referenced by METHOD().
void(* signer_t::destroy)(signer_t *this)
Destroys a signer_t object.
Definition at line 153 of file signer.h.
Referenced by aead_create_from_keys(), attack_signers(), bench_signer(), burn_signer(), METHOD(), and verify_mac().
size_t(* signer_t::get_block_size)(signer_t *this)
Get the block size of this signature algorithm.
Returns
block size in bytes
Definition at line 132 of file signer.h.
Referenced by attack_signers(), bench_signer(), burn_signer(), METHOD(), ntru_drbg_create(), and verify_mac().
size_t(* signer_t::get_key_size)(signer_t *this)
Get the key size of the signature algorithm.
Returns
key size in bytes
Definition at line 139 of file signer.h.
Referenced by attack_signers(), bench_signer(), burn_signer(), derive_ike_traditional(), METHOD(), ntru_drbg_create(), and verify_mac().
bool(* signer_t::get_signature)(signer_t *this, chunk_t data, u_int8_t *buffer) __attribute__((warn_unused_result))
Generate a signature.
If buffer is NULL, data is processed and prepended to a next call until buffer is a valid pointer.
Parameters
data a chunk containing the data to sign
buffer pointer where the signature will be written
Returns
TRUE if signature created successfully
Definition at line 98 of file signer.h.
Referenced by attack_signers(), bench_signer(), burn_signer(), METHOD(), and verify_mac().
bool(* signer_t::set_key)(signer_t *this, chunk_t key) __attribute__((warn_unused_result))
Set the key for this object.
Parameters
key key to set
Returns
TRUE if key set
Definition at line 147 of file signer.h.
Referenced by aead_create_from_keys(), attack_signers(), bench_signer(), burn_signer(), create_traditional(), derive_ike_traditional(), METHOD(), and verify_mac().
bool(* signer_t::verify_signature)(signer_t *this, chunk_t data, chunk_t signature)
Verify a signature.
To verify a signature of multiple chunks of data, pass the data to get_signature() with a NULL buffer. verify_signature() acts as a final call and includes all data fed to get_signature().
Parameters
data a chunk containing the data to verify
signature a chunk containing the signature
Returns
TRUE, if signature is valid, FALSE otherwise
Definition at line 125 of file signer.h.
Referenced by bench_signer(), burn_signer(), CALLBACK(), and METHOD().
The documentation for this struct was generated from the following file:
signer.h