strongSwan: eap_radius_dae
eap_radius_dae
eap_radius
Classes
struct eap_radius_dae_t
Typedefs
typedef struct eap_radius_dae_t eap_radius_dae_t
Functions
eap_radius_dae_t * eap_radius_dae_create (eap_radius_accounting_t *accounting)
Detailed Description
Typedef Documentation
typedef struct eap_radius_dae_t eap_radius_dae_t
Definition at line 26 of file eap_radius_dae.h.
Function Documentation
eap_radius_dae_t* eap_radius_dae_create (eap_radius_accounting_t * accounting)
Create a eap_radius_dae instance.
See header
Definition at line 494 of file eap_radius_dae.c.
References watcher_t::add, AUTH_HMAC_MD5_128, crypto_factory_t::create_hasher, crypto_factory_t::create_signer, library_t::crypto, DBG1, DBG_CFG, destroy(), settings_t::get_str, HASH_MD5, hasher, INIT, lib, linked_list_create(), library_t::ns, open_socket(), receive(), library_t::settings, signer, library_t::watcher, and WATCHER_READ.
Referenced by plugin_cb().
 {
     private_eap_radius_dae_t *this;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
         .accounting = accounting,
         .fd = -1,
         .secret = {
             .ptr = lib->settings->get_str(lib->settings,
                                     "%s.plugins.eap-radius.dae.secret", NULL,
                                     lib->ns),
         },
         .hasher = lib->crypto->create_hasher(lib->crypto, HASH_MD5),
         .signer = lib->crypto->create_signer(lib->crypto, AUTH_HMAC_MD5_128),
         .responses = linked_list_create(),
     );
     if (!this->hasher || !this->signer)
     {
         destroy(this);
         return NULL;
     }
     if (!this->secret.ptr)
     {
         DBG1(DBG_CFG, "missing RADIUS DAE secret, disabled");
         destroy(this);
         return NULL;
     }
     this->secret.len = strlen(this->secret.ptr);
     if (!this->signer->set_key(this->signer, this->secret) ||
         !open_socket(this))
     {
         destroy(this);
         return NULL;
     }
     lib->watcher->add(lib->watcher, this->fd, WATCHER_READ,
                       (watcher_cb_t)receive, this);
     return &this->public;
 }