strongSwan: bridge_t Struct Reference
bridge_t Struct Reference
#include "bridge.h"
Public Attributes
char *(* get_name)(bridge_t *this)
bool(* connect_iface)(bridge_t *this, iface_t *iface)
bool(* disconnect_iface)(bridge_t *this, iface_t *iface)
enumerator_t *(* create_iface_enumerator)(bridge_t *this)
void(* destroy)(bridge_t *this)
Detailed Description
Interface in a guest, connected to a tap device on the host.
Definition at line 29 of file bridge.h.
Member Data Documentation
bool(* bridge_t::connect_iface)(bridge_t *this, iface_t *iface)
Add an interface to a bridge.
Parameters
iface interface to add
Returns
TRUE if interface added
Definition at line 44 of file bridge.h.
Referenced by connect_guest(), and iface_connect().
enumerator_t*(* bridge_t::create_iface_enumerator)(bridge_t *this)
Create an enumerator over all interfaces.
Returns
enumerator over iface_t's
Definition at line 59 of file bridge.h.
Referenced by bridge_each_iface().
void(* bridge_t::destroy)(bridge_t *this)
Destroy a bridge
Definition at line 64 of file bridge.h.
Referenced by METHOD().
bool(* bridge_t::disconnect_iface)(bridge_t *this, iface_t *iface)
Remove an interface from a bridge.
Parameters
iface interface to remove
Returns
TRUE if interface removed
Definition at line 52 of file bridge.h.
Referenced by iface_disconnect().
char*(* bridge_t::get_name)(bridge_t *this)
Get the name of the bridge.
Returns
name of the bridge
Definition at line 36 of file bridge.h.
Referenced by bridge_find(), bridge_to_s(), and connect_guest().
The documentation for this struct was generated from the following file:
bridge.h