strongSwan: mconsole.h File Reference
mconsole.h File Reference
#include <library.h>
Classes
struct mconsole_t
Typedefs
typedef struct mconsole_t mconsole_t
Functions
mconsole_t * mconsole_create (char *notify, void(*idle)(void))
Typedef Documentation
typedef struct mconsole_t mconsole_t
Definition at line 21 of file mconsole.h.
Function Documentation
mconsole_t* mconsole_create (char * notify, void(*)(void) idle)
Create a new mconsole connection to a guest.
Waits for a notification from the guest through the notify socket and tries to connect to the mconsole socket supplied in the received notification.
Parameters
notify unix notify socket path
idle idle function to call while waiting for responses
Returns
mconsole instance, or NULL if failed
create the mconsole instance
Definition at line 320 of file mconsole.c.
References close, free(), idle(), INIT, setup_console(), wait_bootup(), and wait_for_notify().
Referenced by METHOD().
 {
     private_mconsole_t *this;
     INIT(this,
         .public = {
             .add_iface = _add_iface,
             .del_iface = _del_iface,
             .exec = _exec,
             .destroy = _destroy,
         },
         .idle = idle,
     );
     if (!wait_for_notify(this, notify))
     {
         free(this);
         return NULL;
     }
     if (!setup_console(this))
     {
         close(this->notify);
         unlink(notify);
         free(this);
         return NULL;
     }
     unlink(notify);
     wait_bootup(this);
     return &this->public;
 }