strongSwan: rwlock.c File Reference
windows/rwlock.c File Reference
#include "thread.h"
#include <utils/debug.h>
#include <threading/rwlock.h>
#include <threading/rwlock_condvar.h>
#include <threading/thread_value.h>
Classes
struct private_rwlock_t
struct private_rwlock_condvar_t
Typedefs
typedef struct private_rwlock_t private_rwlock_t
typedef struct
private_rwlock_condvar_t private_rwlock_condvar_t
Functions
METHOD (rwlock_t, read_lock, void, private_rwlock_t *this)
METHOD (rwlock_t, write_lock, void, private_rwlock_t *this)
METHOD (rwlock_t, try_write_lock, bool, private_rwlock_t *this)
METHOD (rwlock_t, unlock, void, private_rwlock_t *this)
METHOD (rwlock_t, destroy, void, private_rwlock_t *this)
rwlock_t * rwlock_create (rwlock_type_t type)
METHOD (rwlock_condvar_t, timed_wait, bool, private_rwlock_condvar_t *this, rwlock_t *pubrwlock, u_int timeout)
METHOD (rwlock_condvar_t, wait_, void, private_rwlock_condvar_t *this, rwlock_t *lock)
METHOD (rwlock_condvar_t, timed_wait_abs, bool, private_rwlock_condvar_t *this, rwlock_t *lock, timeval_t tv)
METHOD (rwlock_condvar_t, signal_, void, private_rwlock_condvar_t *this)
METHOD (rwlock_condvar_t, broadcast, void, private_rwlock_condvar_t *this)
METHOD (rwlock_condvar_t, condvar_destroy, void, private_rwlock_condvar_t *this)
rwlock_condvar_t * rwlock_condvar_create ()
Typedef Documentation
typedef struct private_rwlock_condvar_t private_rwlock_condvar_t
Definition at line 24 of file windows/rwlock.c.
typedef struct private_rwlock_t private_rwlock_t
Definition at line 23 of file windows/rwlock.c.
Function Documentation
METHOD (rwlock_t , read_lock , void , private_rwlock_t * this)
Definition at line 63 of file windows/rwlock.c.
References count.
 {
     uintptr_t count;
     /* Recursive read locks are not supported. Use a thread specific
      * recursiveness counter. */
     count = (uintptr_t)this->shared->get(this->shared);
     if (count == 0)
     {
         AcquireSRWLockShared(&this->srw);
     }
     this->shared->set(this->shared, (void*)(count + 1));
 }
METHOD (rwlock_t , write_lock , void , private_rwlock_t * this)
Definition at line 79 of file windows/rwlock.c.
 {
     AcquireSRWLockExclusive(&this->srw);
 }
METHOD (rwlock_t , try_write_lock , bool , private_rwlock_t * this)
Definition at line 85 of file windows/rwlock.c.
 {
     return TryAcquireSRWLockExclusive(&this->srw);
 }
METHOD (rwlock_t , unlock , void , private_rwlock_t * this)
Definition at line 91 of file windows/rwlock.c.
References count.
 {
     uintptr_t count;
     count = (uintptr_t)this->shared->get(this->shared);
     switch (count)
     {
         case 0:
             ReleaseSRWLockExclusive(&this->srw);
             break;
         case 1:
             ReleaseSRWLockShared(&this->srw);
             /* fall */
         default:
             this->shared->set(this->shared, (void*)(count - 1));
             break;
     }
 }
METHOD (rwlock_t , destroy , void , private_rwlock_t * this)
Definition at line 111 of file windows/rwlock.c.
References free().
 {
     this->shared->destroy(this->shared);
     free(this);
 }
METHOD (rwlock_condvar_t , timed_wait , bool , private_rwlock_condvar_t * this, rwlock_t * pubrwlock, u_int timeout)
Definition at line 141 of file windows/rwlock.c.
References rwlock, private_rwlock_t::srw, and thread_set_active_condvar().
 {
     private_rwlock_t *rwlock = (private_rwlock_t*)pubrwlock;
     bool ret;
     thread_set_active_condvar(&this->cv);
     ret = SleepConditionVariableSRW(&this->cv, &rwlock->srw, timeout, 0);
     thread_set_active_condvar(NULL);
     return ret == 0;
 }
METHOD (rwlock_condvar_t , wait_ , void , private_rwlock_condvar_t * this, rwlock_t * lock)
Definition at line 156 of file windows/rwlock.c.
 {
     timed_wait(this, lock, INFINITE);
 }
METHOD (rwlock_condvar_t , timed_wait_abs , bool , private_rwlock_condvar_t * this, rwlock_t * lock, timeval_t tv)
Definition at line 162 of file windows/rwlock.c.
References DWORD, time_monotonic(), timersub(), and TRUE.
 {
     DWORD timeout;
     timeval_t now, diff;
     time_monotonic(&now);
     if (timercmp(&now, &tv, >))
     {
         return TRUE;
     }
     timersub(&tv, &now, &diff);
     timeout = diff.tv_sec * 1000 + diff.tv_usec / 1000;
     return timed_wait(this, lock, timeout);
 }
METHOD (rwlock_condvar_t , signal_ , void , private_rwlock_condvar_t * this)
Definition at line 179 of file windows/rwlock.c.
 {
     WakeConditionVariable(&this->cv);
 }
METHOD (rwlock_condvar_t , broadcast , void , private_rwlock_condvar_t * this)
Definition at line 185 of file windows/rwlock.c.
 {
     WakeAllConditionVariable(&this->cv);
 }
METHOD (rwlock_condvar_t , condvar_destroy , void , private_rwlock_condvar_t * this)
Definition at line 191 of file windows/rwlock.c.
References free().
 {
     free(this);
 }