strongSwan: aead.c File Reference
aead.c File Reference
#include "aead.h"
#include <utils/debug.h>
#include <crypto/iv/iv_gen_rand.h>
Classes
struct private_aead_t
Typedefs
typedef struct private_aead_t private_aead_t
Functions
METHOD (aead_t, encrypt, bool, private_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encrypted)
METHOD (aead_t, decrypt, bool, private_aead_t *this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t *plain)
METHOD (aead_t, get_block_size, size_t, private_aead_t *this)
METHOD (aead_t, get_icv_size, size_t, private_aead_t *this)
METHOD (aead_t, get_iv_size, size_t, private_aead_t *this)
METHOD (aead_t, get_iv_gen, iv_gen_t *, private_aead_t *this)
METHOD (aead_t, get_key_size, size_t, private_aead_t *this)
METHOD (aead_t, set_key, bool, private_aead_t *this, chunk_t key)
METHOD (aead_t, destroy, void, private_aead_t *this)
aead_t * aead_create (crypter_t *crypter, signer_t *signer, iv_gen_t *iv_gen)
Typedef Documentation
typedef struct private_aead_t private_aead_t
Definition at line 24 of file aead.c.
Function Documentation
METHOD (aead_t , encrypt , bool , private_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t * encrypted)
Definition at line 52 of file aead.c.
References chunk_cat, crypter, FALSE, free(), chunk_t::len, chunk_t::ptr, sig, signer, and TRUE.
 {
     chunk_t encr, sig;
     if (!this->signer->get_signature(this->signer, assoc, NULL) ||
         !this->signer->get_signature(this->signer, iv, NULL))
     {
         return FALSE;
     }
     if (encrypted)
     {
         if (!this->crypter->encrypt(this->crypter, plain, iv, &encr))
         {
             return FALSE;
         }
         if (!this->signer->allocate_signature(this->signer, encr, &sig))
         {
             free(encr.ptr);
             return FALSE;
         }
         *encrypted = chunk_cat("cmm", iv, encr, sig);
     }
     else
     {
         if (!this->crypter->encrypt(this->crypter, plain, iv, NULL) ||
             !this->signer->get_signature(this->signer,
                                          plain, plain.ptr + plain.len))
         {
             return FALSE;
         }
     }
     return TRUE;
 }
METHOD (aead_t , decrypt , bool , private_aead_t * this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t * plain)
Definition at line 89 of file aead.c.
References chunk_split(), crypter, DBG1, DBG_LIB, FALSE, chunk_t::len, sig, and signer.
 {
     chunk_t sig;
     size_t bs;
     bs = this->crypter->get_block_size(this->crypter);
     sig.len = this->signer->get_block_size(this->signer);
     if (sig.len > encrypted.len || (encrypted.len - sig.len) % bs)
     {
         DBG1(DBG_LIB, "invalid encrypted data length %d with block size %d",
             encrypted.len - sig.len, bs);
         return FALSE;
     }
     chunk_split(encrypted, "mm", encrypted.len - sig.len,
                 &encrypted, sig.len, &sig);
     if (!this->signer->get_signature(this->signer, assoc, NULL) ||
         !this->signer->get_signature(this->signer, iv, NULL))
     {
         return FALSE;
     }
     if (!this->signer->verify_signature(this->signer, encrypted, sig))
     {
         DBG1(DBG_LIB, "MAC verification failed");
         return FALSE;
     }
     return this->crypter->decrypt(this->crypter, encrypted, iv, plain);
 }
METHOD (aead_t , get_block_size , size_t , private_aead_t * this)
Definition at line 120 of file aead.c.
References crypter.
 {
     return this->crypter->get_block_size(this->crypter);
 }
METHOD (aead_t , get_icv_size , size_t , private_aead_t * this)
Definition at line 126 of file aead.c.
References signer.
 {
     return this->signer->get_block_size(this->signer);
 }
METHOD (aead_t , get_iv_size , size_t , private_aead_t * this)
Definition at line 132 of file aead.c.
References crypter.
 {
     return this->crypter->get_iv_size(this->crypter);
 }
METHOD (aead_t , get_iv_gen , iv_gen_t * , private_aead_t * this)
Definition at line 138 of file aead.c.
 {
     return this->iv_gen;
 }
METHOD (aead_t , get_key_size , size_t , private_aead_t * this)
Definition at line 144 of file aead.c.
References crypter, and signer.
 {
     return this->crypter->get_key_size(this->crypter) +
             this->signer->get_key_size(this->signer);
 }
METHOD (aead_t , set_key , bool , private_aead_t * this, chunk_t key)
Definition at line 151 of file aead.c.
References chunk_split(), crypter, enc, sig, and signer.
 {
     chunk_t sig, enc;
     chunk_split(key, "mm", this->signer->get_key_size(this->signer), &sig,
                 this->crypter->get_key_size(this->crypter), &enc);
     return this->signer->set_key(this->signer, sig) &&
            this->crypter->set_key(this->crypter, enc);
 }
METHOD (aead_t , destroy , void , private_aead_t * this)
Definition at line 163 of file aead.c.
References crypter, free(), and signer.
 {
     this->iv_gen->destroy(this->iv_gen);
     this->crypter->destroy(this->crypter);
     this->signer->destroy(this->signer);
     free(this);
 }