strongSwan: pts_comp_evidence_t Struct Reference
pts_comp_evidence_t Struct Reference
pts_comp_evidence
#include "pts_comp_evidence.h"
Public Attributes
pts_comp_func_name_t *(* get_comp_func_name)(pts_comp_evidence_t *this, u_int32_t *depth)
u_int32_t(* get_extended_pcr)(pts_comp_evidence_t *this)
chunk_t(* get_measurement)(pts_comp_evidence_t *this, u_int32_t *extended_pcr, pts_meas_algorithms_t *algo, pts_pcr_transform_t *transform, time_t *measurement_time)
bool(* get_pcr_info)(pts_comp_evidence_t *this, chunk_t *pcr_before, chunk_t *pcr_after)
void(* set_pcr_info)(pts_comp_evidence_t *this, chunk_t pcr_before, chunk_t pcr_after)
pts_comp_evid_validation_t(* get_validation)(pts_comp_evidence_t *this, char **uri)
void(* set_validation)(pts_comp_evidence_t *this, pts_comp_evid_validation_t validation, char *uri)
void(* destroy)(pts_comp_evidence_t *this)
Detailed Description
PTS Functional Component Interface
Definition at line 64 of file pts_comp_evidence.h.
Member Data Documentation
void(* pts_comp_evidence_t::destroy)(pts_comp_evidence_t *this)
Destroys a pts_comp_evidence_t object.
Definition at line 137 of file pts_comp_evidence.h.
pts_comp_func_name_t*(* pts_comp_evidence_t::get_comp_func_name)(pts_comp_evidence_t *this, u_int32_t *depth)
Gets the Component Functional Name and Sub-Component Depth
Parameters
depth Sub-Component Depth
Returns
Component Functional Name
Definition at line 72 of file pts_comp_evidence.h.
Referenced by imv_attestation_process().
u_int32_t(* pts_comp_evidence_t::get_extended_pcr)(pts_comp_evidence_t *this)
Gets the PCR the measurement was extended into
Returns
PCR the measurement was extended into
Definition at line 80 of file pts_comp_evidence.h.
chunk_t(* pts_comp_evidence_t::get_measurement)(pts_comp_evidence_t *this, u_int32_t *extended_pcr, pts_meas_algorithms_t *algo, pts_pcr_transform_t *transform, time_t *measurement_time)
Gets the measurement and the algorithms used
Parameters
extended_pcr PCR the measurement was extended into
algo Measurement hash algorithm
transform Transformation used for PCR extension
measurement_time Time the measurement was taken
Returns
Measurement hash value
Definition at line 91 of file pts_comp_evidence.h.
Referenced by METHOD().
bool(* pts_comp_evidence_t::get_pcr_info)(pts_comp_evidence_t *this, chunk_t *pcr_before, chunk_t *pcr_after)
Gets the PCR information if available
Parameters
pcr_before PCR value before extension
pcr_after PCR value after extension
Returns
TRUE if PCR information is available
Definition at line 104 of file pts_comp_evidence.h.
Referenced by METHOD().
pts_comp_evid_validation_t(* pts_comp_evidence_t::get_validation)(pts_comp_evidence_t *this, char **uri)
Gets Validation Result if available
Parameters
uri Verification Policy URI
Returns
validation Validation Result
Definition at line 122 of file pts_comp_evidence.h.
Referenced by METHOD(), and parse_validation_uri().
void(* pts_comp_evidence_t::set_pcr_info)(pts_comp_evidence_t *this, chunk_t pcr_before, chunk_t pcr_after)
Sets PCR information if available
Parameters
pcr_before PCR value before extension
pcr_after PCR value after extension
Definition at line 113 of file pts_comp_evidence.h.
Referenced by extend_pcr(), and METHOD().
void(* pts_comp_evidence_t::set_validation)(pts_comp_evidence_t *this, pts_comp_evid_validation_t validation, char *uri)
Sets Validation Result if available
Parameters
validation Validation Result
uri Verification Policy URI
Definition at line 131 of file pts_comp_evidence.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
pts_comp_evidence.h