strongSwan: ipsec_policy_mgr_t Struct Reference
ipsec_policy_mgr_t Struct Reference
ipsec_policy_mgr
#include "ipsec_policy_mgr.h"
Public Attributes
status_t(* add_policy)(ipsec_policy_mgr_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
status_t(* del_policy)(ipsec_policy_mgr_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t priority)
status_t(* flush_policies)(ipsec_policy_mgr_t *this)
ipsec_policy_t *(* find_by_packet)(ipsec_policy_mgr_t *this, ip_packet_t *packet, bool inbound, u_int32_t reqid)
void(* destroy)(ipsec_policy_mgr_t *this)
Detailed Description
IPsec policy manager
The first methods are modeled after those in kernel_ipsec_t.
Note
Only policies of type POLICY_IPSEC are currently used, also policies with direction POLICY_FWD are ignored. Any packets that do not match an installed policy will be dropped.
Definition at line 46 of file ipsec_policy_mgr.h.
Member Data Documentation
status_t(* ipsec_policy_mgr_t::add_policy)(ipsec_policy_mgr_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
Add a policy
A policy is always associated to an SA. Traffic which matches a policy is handled by the SA with the same reqid.
Parameters
src source address of SA
dst dest address of SA
src_ts traffic selector to match traffic source
dst_ts traffic selector to match traffic dest
direction direction of traffic, POLICY_(IN|OUT|FWD)
type type of policy, POLICY_(IPSEC|PASS|DROP)
sa details about the SA(s) tied to this policy
mark mark for this policy
priority priority of this policy
Returns
SUCCESS if operation completed
Definition at line 65 of file ipsec_policy_mgr.h.
Referenced by METHOD().
status_t(* ipsec_policy_mgr_t::del_policy)(ipsec_policy_mgr_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t priority)
Remove a policy
Parameters
src_ts traffic selector to match traffic source
dst_ts traffic selector to match traffic dest
direction direction of traffic, POLICY_(IN|OUT|FWD)
reqid unique ID of the associated SA
mark optional mark
priority priority of the policy
Returns
SUCCESS if operation completed
Definition at line 82 of file ipsec_policy_mgr.h.
Referenced by METHOD().
void(* ipsec_policy_mgr_t::destroy)(ipsec_policy_mgr_t *this)
Destroy an ipsec_policy_mgr_t
Definition at line 110 of file ipsec_policy_mgr.h.
ipsec_policy_t*(* ipsec_policy_mgr_t::find_by_packet)(ipsec_policy_mgr_t *this, ip_packet_t *packet, bool inbound, u_int32_t reqid)
Find the policy that matches the given IP packet best
Parameters
packet IP packet to match
inbound TRUE for an inbound packet
reqid require a policy with a specific reqid, 0 for any
Returns
reference to the policy, or NULL if none found
Definition at line 103 of file ipsec_policy_mgr.h.
Referenced by process_inbound(), and process_outbound().
status_t(* ipsec_policy_mgr_t::flush_policies)(ipsec_policy_mgr_t *this)
Flush all policies
Returns
SUCCESS if operation completed
Definition at line 93 of file ipsec_policy_mgr.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ipsec_policy_mgr.h