strongSwan: attest_db_t Struct Reference
attest_db_t Struct Reference
attest_db
#include "attest_db.h"
Public Attributes
bool(* set_component)(attest_db_t *this, char *comp, bool create)
bool(* set_cid)(attest_db_t *this, int fid)
bool(* set_directory)(attest_db_t *this, char *dir, bool create)
bool(* set_did)(attest_db_t *this, int did)
bool(* set_file)(attest_db_t *this, char *file, bool create)
bool(* set_fid)(attest_db_t *this, int fid)
bool(* set_meas_directory)(attest_db_t *this, char *dir)
bool(* set_key)(attest_db_t *this, chunk_t key, bool create)
bool(* set_kid)(attest_db_t *this, int kid)
bool(* set_package)(attest_db_t *this, char *package, bool create)
bool(* set_gid)(attest_db_t *this, int gid)
bool(* set_product)(attest_db_t *this, char *product, bool create)
bool(* set_pid)(attest_db_t *this, int pid)
bool(* set_version)(attest_db_t *this, char *version)
void(* set_algo)(attest_db_t *this, pts_meas_algorithms_t algo)
void(* set_ima)(attest_db_t *this)
void(* set_relative)(attest_db_t *this)
void(* set_package_state)(attest_db_t *this, os_package_state_t package_state)
void(* set_sequence)(attest_db_t *this, int seq_no)
void(* set_owner)(attest_db_t *this, char *owner)
void(* set_utc)(attest_db_t *this)
void(* list_packages)(attest_db_t *this)
void(* list_products)(attest_db_t *this)
void(* list_directories)(attest_db_t *this)
void(* list_files)(attest_db_t *this)
void(* list_components)(attest_db_t *this)
void(* list_devices)(attest_db_t *this)
void(* list_keys)(attest_db_t *this)
void(* list_hashes)(attest_db_t *this)
void(* list_measurements)(attest_db_t *this)
void(* list_sessions)(attest_db_t *this)
bool(* add)(attest_db_t *this)
bool(* delete)(attest_db_t *this)
void(* destroy)(attest_db_t *this)
Detailed Description
Attestation database object
Definition at line 33 of file attest_db.h.
Member Data Documentation
bool(* attest_db_t::add)(attest_db_t *this)
Add an entry to the database
Definition at line 246 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::delete)(attest_db_t *this)
Delete an entry from the database
Definition at line 251 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::destroy)(attest_db_t *this)
Destroy attest_db_t object
Definition at line 256 of file attest_db.h.
Referenced by cleanup().
void(* attest_db_t::list_components)(attest_db_t *this)
List all components stored in the database
Definition at line 216 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_devices)(attest_db_t *this)
List all devices stored in the database
Definition at line 221 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_directories)(attest_db_t *this)
List all directories stored in the database
Definition at line 206 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_files)(attest_db_t *this)
List selected files stored in the database
Definition at line 211 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_hashes)(attest_db_t *this)
List selected measurement hashes stored in the database
Definition at line 231 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_keys)(attest_db_t *this)
List all AIKs stored in the database
Definition at line 226 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_measurements)(attest_db_t *this)
List selected component measurement stored in the database
Definition at line 236 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_packages)(attest_db_t *this)
List all packages stored in the database
Definition at line 196 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_products)(attest_db_t *this)
List all products stored in the database
Definition at line 201 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::list_sessions)(attest_db_t *this)
List sessions stored in the database
Definition at line 241 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::set_algo)(attest_db_t *this, pts_meas_algorithms_t algo)
Set measurement hash algorithm
Parameters
algo hash algorithm
Definition at line 158 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_cid)(attest_db_t *this, int fid)
Set primary key of the functional component to be queried
Parameters
fid primary key of functional component
Returns
TRUE if successful
Definition at line 50 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_component)(attest_db_t *this, char *comp, bool create)
Set functional component to be queried
Parameters
comp functional component
create if TRUE create database entry if it doesn't exist
Returns
TRUE if successful
Definition at line 42 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_did)(attest_db_t *this, int did)
Set primary key of the directory to be queried
Parameters
did primary key of directory
Returns
TRUE if successful
Definition at line 67 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_directory)(attest_db_t *this, char *dir, bool create)
Set directory to be queried
Parameters
dir directory
create if TRUE create database entry if it doesn't exist
Returns
TRUE if successful
Definition at line 59 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_fid)(attest_db_t *this, int fid)
Set primary key of the measurement file to be queried
Parameters
fid primary key of measurement file
Returns
TRUE if successful
Definition at line 84 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_file)(attest_db_t *this, char *file, bool create)
Set measurement file to be queried
Parameters
file measurement file
create if TRUE create database entry if it doesn't exist
Returns
TRUE if successful
Definition at line 76 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_gid)(attest_db_t *this, int gid)
Set primary key of the software package to be queried
Parameters
gid primary key of software package
Returns
TRUE if successful
Definition at line 126 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::set_ima)(attest_db_t *this)
Set that the IMA-specific SHA-1 template hash be computed
Definition at line 163 of file attest_db.h.
bool(* attest_db_t::set_key)(attest_db_t *this, chunk_t key, bool create)
Set functional component to be queried
Parameters
key AIK
create if TRUE create database entry if it doesn't exist
Returns
TRUE if successful
Definition at line 101 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_kid)(attest_db_t *this, int kid)
Set primary key of the AIK to be queried
Parameters
kid primary key of AIK
Returns
TRUE if successful
Definition at line 109 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_meas_directory)(attest_db_t *this, char *dir)
Set path to directory where file[s] are to be measured
Parameters
meas_dir measurement directory
Returns
TRUE if successful
Definition at line 92 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::set_owner)(attest_db_t *this, char *owner)
Set owner [user/host] of an AIK
Parameters
owner user/host name
Returns
TRUE if successful
Definition at line 186 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_package)(attest_db_t *this, char *package, bool create)
Set software package to be queried
Parameters
product software package
create if TRUE create database entry if it doesn't exist
Returns
TRUE if successful
Definition at line 118 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::set_package_state)(attest_db_t *this, os_package_state_t package_state)
Set the package security or blacklist state
Definition at line 173 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_pid)(attest_db_t *this, int pid)
Set primary key of the software product to be queried
Parameters
pid primary key of software product
Returns
TRUE if successful
Definition at line 143 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_product)(attest_db_t *this, char *product, bool create)
Set software product to be queried
Parameters
product software product
create if TRUE create database entry if it doesn't exist
Returns
TRUE if successful
Definition at line 135 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::set_relative)(attest_db_t *this)
Set that relative filenames are to be used
Definition at line 168 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::set_sequence)(attest_db_t *this, int seq_no)
Set the sequence number
Definition at line 178 of file attest_db.h.
Referenced by do_args().
void(* attest_db_t::set_utc)(attest_db_t *this)
Display all dates in UTC
Definition at line 191 of file attest_db.h.
Referenced by do_args().
bool(* attest_db_t::set_version)(attest_db_t *this, char *version)
Set software package version to be queried
Parameters
version software package version
Returns
TRUE if successful
Definition at line 151 of file attest_db.h.
Referenced by do_args().
The documentation for this struct was generated from the following file:
attest_db.h