strongSwan: libvici.c File Reference
libvici.c File Reference
#include "libvici.h"
#include "vici_builder.h"
#include "vici_dispatcher.h"
#include "vici_socket.h"
#include <library.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <collections/hashtable.h>
#include <errno.h>
Classes
struct event_t
struct vici_conn_t
struct vici_req_t
struct vici_res_t
Enumerations
enum wait_state_t { WAIT_IDLE = 0, WAIT_SUCCESS, WAIT_FAILURE, WAIT_READ_ERROR }
Functions
static bool wait_result (vici_conn_t *conn, wait_state_t wait)
static bool read_error (vici_conn_t *conn, int err)
static bool handle_response (vici_conn_t *conn, u_int32_t len)
static bool handle_event (vici_conn_t *conn, u_int32_t len)
CALLBACK (on_read, bool, vici_conn_t *conn, stream_t *stream)
vici_conn_t * vici_connect (char *uri)
void vici_disconnect (vici_conn_t *conn)
vici_req_t * vici_begin (char *name)
void vici_begin_section (vici_req_t *req, char *name)
void vici_end_section (vici_req_t *req)
void vici_add_key_value (vici_req_t *req, char *key, void *buf, int len)
void vici_add_key_valuef (vici_req_t *req, char *key, char *fmt,...)
void vici_begin_list (vici_req_t *req, char *name)
void vici_add_list_item (vici_req_t *req, void *buf, int len)
void vici_add_list_itemf (vici_req_t *req, char *fmt,...)
void vici_end_list (vici_req_t *req)
vici_res_t * vici_submit (vici_req_t *req, vici_conn_t *conn)
void vici_free_req (vici_req_t *req)
int vici_dump (vici_res_t *res, char *label, int pretty, FILE *out)
vici_parse_t vici_parse (vici_res_t *res)
char * vici_parse_name (vici_res_t *res)
int vici_parse_name_eq (vici_res_t *res, char *name)
void * vici_parse_value (vici_res_t *res, int *len)
char * vici_parse_value_str (vici_res_t *res)
int vici_parse_cb (vici_res_t *res, vici_parse_section_cb_t section, vici_parse_value_cb_t kv, vici_parse_value_cb_t li, void *user)
void * vici_find (vici_res_t *res, int *len, char *fmt,...)
char * vici_find_str (vici_res_t *res, char *def, char *fmt,...)
int vici_find_int (vici_res_t *res, int def, char *fmt,...)
void vici_free_res (vici_res_t *res)
int vici_register (vici_conn_t *conn, char *name, vici_event_cb_t cb, void *user)
void vici_init ()
void vici_deinit ()
Enumeration Type Documentation
enum wait_state_t
Wait state signaled by asynchronous on_read callback
Enumerator
WAIT_IDLE
WAIT_SUCCESS
WAIT_FAILURE
WAIT_READ_ERROR
Definition at line 43 of file libvici.c.
              {
     WAIT_IDLE = 0,
     WAIT_SUCCESS,
     WAIT_FAILURE,
     WAIT_READ_ERROR,
 } wait_state_t;
Function Documentation
CALLBACK (on_read , bool , vici_conn_t * conn, stream_t * stream)
Definition at line 198 of file libvici.c.
References EBADMSG, EWOULDBLOCK, FALSE, handle_event(), handle_response(), len, stream_t::read, stream_t::read_all, read_error(), TRUE, VICI_CMD_REQUEST, VICI_CMD_RESPONSE, VICI_CMD_UNKNOWN, VICI_EVENT, VICI_EVENT_CONFIRM, VICI_EVENT_REGISTER, VICI_EVENT_UNKNOWN, VICI_EVENT_UNREGISTER, VICI_MESSAGE_SIZE_MAX, WAIT_FAILURE, wait_result(), and WAIT_SUCCESS.
 {
     u_int32_t len;
     u_int8_t op;
     ssize_t hlen;
     hlen = stream->read(stream, &len, sizeof(len), FALSE);
     if (hlen <= 0)
     {
         if (errno == EWOULDBLOCK)
         {
             return TRUE;
         }
         return read_error(conn, errno);
     }
     if (hlen < sizeof(len))
     {
         if (!stream->read_all(stream, ((void*)&len) + hlen, sizeof(len) - hlen))
         {
             return read_error(conn, errno);
         }
     }
     len = ntohl(len);
     if (len > VICI_MESSAGE_SIZE_MAX)
     {
         return read_error(conn, EBADMSG);
     }
     if (len-- < sizeof(op))
     {
         return read_error(conn, EBADMSG);
     }
     if (!stream->read_all(stream, &op, sizeof(op)))
     {
         return read_error(conn, errno);
     }
     switch (op)
     {
         case VICI_EVENT:
             return handle_event(conn, len);
         case VICI_CMD_RESPONSE:
             return handle_response(conn, len);
         case VICI_EVENT_CONFIRM:
             return wait_result(conn, WAIT_SUCCESS);
         case VICI_CMD_UNKNOWN:
         case VICI_EVENT_UNKNOWN:
             return wait_result(conn, WAIT_FAILURE);
         case VICI_CMD_REQUEST:
         case VICI_EVENT_REGISTER:
         case VICI_EVENT_UNREGISTER:
         default:
             return read_error(conn, EBADMSG);
     }
 }
static bool handle_event (vici_conn_t * conn, u_int32_t len) static
Dispatch received event message
Definition at line 143 of file libvici.c.
References chunk_create(), vici_message_t::create_enumerator, enumerator_t::destroy, vici_message_t::destroy, linked_list_t::destroy_function, EBADMSG, vici_res_t::enumerator, event, vici_conn_t::events, free(), hashtable_t::get, linked_list_create(), mutex_t::lock, malloc(), vici_conn_t::mutex, name, stream_t::read_all, read_error(), res, vici_conn_t::stream, vici_res_t::strings, TRUE, mutex_t::unlock, event_t::user, and vici_message_create_from_data().
Referenced by CALLBACK().
 {
     vici_message_t *message;
     event_t *event;
     u_int8_t namelen;
     char name[257], *buf;
     if (len < sizeof(namelen))
     {
         return read_error(conn, EBADMSG);
     }
     if (!conn->stream->read_all(conn->stream, &namelen, sizeof(namelen)))
     {
         return read_error(conn, errno);
     }
     if (namelen > len - sizeof(namelen))
     {
         return read_error(conn, EBADMSG);
     }
     if (!conn->stream->read_all(conn->stream, name, namelen))
     {
         return read_error(conn, errno);
     }
     name[namelen] = '\0';
     len -= sizeof(namelen) + namelen;
     buf = malloc(len);
     if (!conn->stream->read_all(conn->stream, buf, len))
     {
         free(buf);
         return read_error(conn, errno);
     }
     message = vici_message_create_from_data(chunk_create(buf, len), TRUE);
     conn->mutex->lock(conn->mutex);
     event = conn->events->get(conn->events, name);
     if (event)
     {
         vici_res_t res = {
             .message = message,
             .enumerator = message->create_enumerator(message),
             .strings = linked_list_create(),
         };
         event->cb(event->user, name, &res);
         res.enumerator->destroy(res.enumerator);
         res.strings->destroy_function(res.strings, free);
     }
     conn->mutex->unlock(conn->mutex);
     message->destroy(message);
     return TRUE;
 }
static bool handle_response (vici_conn_t * conn, u_int32_t len) static
Handle a command response message
Definition at line 126 of file libvici.c.
References chunk_alloc, free(), chunk_t::len, chunk_t::ptr, vici_conn_t::queue, stream_t::read_all, read_error(), vici_conn_t::stream, wait_result(), and WAIT_SUCCESS.
Referenced by CALLBACK().
 {
     chunk_t buf;
     buf = chunk_alloc(len);
     if (!conn->stream->read_all(conn->stream, buf.ptr, buf.len))
     {
         free(buf.ptr);
         return read_error(conn, errno);
     }
     conn->queue = buf;
     return wait_result(conn, WAIT_SUCCESS);
 }
static bool read_error (vici_conn_t * conn, int err) static
Signal wait error result for waiting user thread
Definition at line 117 of file libvici.c.
References vici_conn_t::error, WAIT_READ_ERROR, and wait_result().
Referenced by CALLBACK(), handle_event(), and handle_response().
 {
     conn->error = err;
     return wait_result(conn, WAIT_READ_ERROR);
 }
static bool wait_result (vici_conn_t * conn, wait_state_t wait) static
Signal wait result for waiting user thread
Definition at line 105 of file libvici.c.
References vici_conn_t::cond, FALSE, mutex_t::lock, vici_conn_t::mutex, condvar_t::signal, mutex_t::unlock, and vici_conn_t::wait.
Referenced by CALLBACK(), handle_response(), and read_error().
 {
     conn->mutex->lock(conn->mutex);
     conn->wait = wait;
     conn->mutex->unlock(conn->mutex);
     conn->cond->signal(conn->cond);
     return FALSE;
 }