strongSwan: notify_payload_t Struct Reference
notify_payload_t Struct Reference
notify_payload
#include "notify_payload.h"
Public Attributes
payload_t payload_interface
u_int8_t(* get_protocol_id)(notify_payload_t *this)
void(* set_protocol_id)(notify_payload_t *this, u_int8_t protocol_id)
notify_type_t(* get_notify_type)(notify_payload_t *this)
void(* set_notify_type)(notify_payload_t *this, notify_type_t type)
u_int32_t(* get_spi)(notify_payload_t *this)
void(* set_spi)(notify_payload_t *this, u_int32_t spi)
chunk_t(* get_spi_data)(notify_payload_t *this)
void(* set_spi_data)(notify_payload_t *this, chunk_t spi)
chunk_t(* get_notification_data)(notify_payload_t *this)
void(* set_notification_data)(notify_payload_t *this, chunk_t notification_data)
void(* destroy)(notify_payload_t *this)
Detailed Description
Class representing an IKEv2-Notify Payload.
The Notify Payload format is described in Draft section 3.10.
Definition at line 192 of file notify_payload.h.
Member Data Documentation
void(* notify_payload_t::destroy)(notify_payload_t *this)
Destroys an notify_payload_t object.
Definition at line 284 of file notify_payload.h.
chunk_t(* notify_payload_t::get_notification_data)(notify_payload_t *this)
Returns the currently set notification data of payload.
Returned data are not copied.
Returns
chunk_t pointing to the value
Definition at line 269 of file notify_payload.h.
Referenced by endpoint_notify_create_from_payload(), get_string(), handle_notify(), handle_supported_hash_algorithms(), ike2queue(), METHOD(), print_radius_attributes(), process_dpd(), process_payloads(), and send_check().
notify_type_t(* notify_payload_t::get_notify_type)(notify_payload_t *this)
Gets the notify message type of this payload.
Returns
notify message type of this payload
Definition at line 217 of file notify_payload.h.
Referenced by endpoint_notify_create_from_payload(), get_string(), handle_notify(), has_notify_errors(), ike2queue(), is_connectivity_check(), METHOD(), order_payloads(), print_radius_attributes(), process_auth_response(), process_notify(), process_payloads(), and process_request().
u_int8_t(* notify_payload_t::get_protocol_id)(notify_payload_t *this)
Gets the protocol id of this payload.
Returns
protocol id of this payload
Definition at line 203 of file notify_payload.h.
Referenced by find_child(), and process_request().
u_int32_t(* notify_payload_t::get_spi)(notify_payload_t *this)
Returns the currently set spi of this payload.
This is only valid for notifys with protocol AH|ESP
Returns
SPI value
Definition at line 233 of file notify_payload.h.
Referenced by find_child().
chunk_t(* notify_payload_t::get_spi_data)(notify_payload_t *this)
Returns the currently set spi of this payload.
This is only valid for notifys with protocol ISAKMP
Returns
SPI value
Definition at line 251 of file notify_payload.h.
payload_t notify_payload_t::payload_interface
The payload_t interface.
Definition at line 196 of file notify_payload.h.
Referenced by METHOD().
void(* notify_payload_t::set_notification_data)(notify_payload_t *this, chunk_t notification_data)
Sets the notification data of this payload.
Warning
Value is getting copied.
Parameters
notification_data chunk_t pointing to the value to set
Definition at line 278 of file notify_payload.h.
Referenced by build_natd_payload(), and METHOD().
void(* notify_payload_t::set_notify_type)(notify_payload_t *this, notify_type_t type)
Sets notify message type of this payload.
Parameters
type notify message type to set
Definition at line 224 of file notify_payload.h.
Referenced by build_natd_payload(), and METHOD().
void(* notify_payload_t::set_protocol_id)(notify_payload_t *this, u_int8_t protocol_id)
Sets the protocol id of this payload.
Parameters
protocol_id protocol id to set
Definition at line 210 of file notify_payload.h.
void(* notify_payload_t::set_spi)(notify_payload_t *this, u_int32_t spi)
Sets the spi of this payload.
This is only valid for notifys with protocol AH|ESP
Parameters
spi SPI value
Definition at line 242 of file notify_payload.h.
Referenced by METHOD(), and send_notify().
void(* notify_payload_t::set_spi_data)(notify_payload_t *this, chunk_t spi)
Sets the spi of this payload.
This is only valid for notifys with protocol ISAKMP
Parameters
spi SPI value
Definition at line 260 of file notify_payload.h.
Referenced by add_initial_contact(), METHOD(), and send_notify().
The documentation for this struct was generated from the following file:
notify_payload.h