strongSwan: tnc_imc_manager
tnc_imc_manager
tnc_imc
Functions
imc_manager_t * tnc_imc_manager_create ()
Detailed Description
Function Documentation
imc_manager_t* tnc_imc_manager_create (void)
Create an IMC manager instance.
Described in header.
Definition at line 413 of file tnc_imc_manager.c.
References INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by METHOD().
 {
     private_tnc_imc_manager_t *this;
     INIT(this,
         .public = {
             .add = _add,
             .remove = _remove_, /* avoid name conflict with stdio.h */
             .load = _load,
             .load_from_functions = _load_from_functions,
             .is_registered = _is_registered,
             .reserve_id = _reserve_id,
             .get_preferred_language = _get_preferred_language,
             .notify_connection_change = _notify_connection_change,
             .begin_handshake = _begin_handshake,
             .set_message_types = _set_message_types,
             .set_message_types_long = _set_message_types_long,
             .receive_message = _receive_message,
             .batch_ending = _batch_ending,
             .destroy = _destroy,
         },
         .imcs = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .id_mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .next_imc_id = 1,
     );
     return &this->public;
 }