strongSwan: tkm_chunk_map.c File Reference
tkm_chunk_map.c File Reference
#include <collections/hashtable.h>
#include <threading/rwlock.h>
#include <utils/chunk.h>
#include <utils/debug.h>
#include "tkm_chunk_map.h"
Classes
struct private_tkm_chunk_map_t
struct entry_t
Typedefs
typedef struct
private_tkm_chunk_map_t private_tkm_chunk_map_t
Functions
static void entry_destroy (entry_t *this)
METHOD (tkm_chunk_map_t, insert, void, private_tkm_chunk_map_t *const this, const chunk_t *const data, const uint64_t id)
METHOD (tkm_chunk_map_t, get_id, uint64_t, private_tkm_chunk_map_t *const this, chunk_t *data)
METHOD (tkm_chunk_map_t, remove_, bool, private_tkm_chunk_map_t *const this, chunk_t *data)
METHOD (tkm_chunk_map_t, destroy, void, private_tkm_chunk_map_t *this)
static u_int hash (chunk_t *key)
tkm_chunk_map_t * tkm_chunk_map_create ()
Typedef Documentation
typedef struct private_tkm_chunk_map_t private_tkm_chunk_map_t
Definition at line 24 of file tkm_chunk_map.c.
Function Documentation
static void entry_destroy (entry_t * this) static
Destroy a hashtable entry
Definition at line 61 of file tkm_chunk_map.c.
References chunk_free(), free(), and key.
Referenced by METHOD().
 {
     chunk_free(&this->key);
     free(this);
 }
static u_int hash (chunk_t * key) static
Hashtable hash function.
Definition at line 146 of file tkm_chunk_map.c.
References chunk_hash().
Referenced by tkm_chunk_map_create().
 {
     return chunk_hash(*key);
 }
METHOD (tkm_chunk_map_t , insert , void , private_tkm_chunk_map_t *const this, const chunk_t *const data, const uint64_t id)
Definition at line 67 of file tkm_chunk_map.c.
References chunk_clone, entry_destroy(), INIT, entry_t::key, key, lock, spinlock_t::unlock, and value.
 {
     entry_t *entry;
     INIT(entry,
         .key = chunk_clone(*data),
         .value = id
     );
     this->lock->write_lock(this->lock);
     entry = this->mappings->put(this->mappings, (void*)&entry->key, entry);
     this->lock->unlock(this->lock);
     if (entry)
     {
         entry_destroy(entry);
     }
 }
METHOD (tkm_chunk_map_t , get_id , uint64_t , private_tkm_chunk_map_t *const this, chunk_t * data)
Definition at line 87 of file tkm_chunk_map.c.
References lock, spinlock_t::unlock, and entry_t::value.
 {
     entry_t *entry;
     this->lock->read_lock(this->lock);
     entry = this->mappings->get(this->mappings, data);
     this->lock->unlock(this->lock);
     if (!entry)
     {
         return 0;
     }
     return entry->value;
 }
METHOD (tkm_chunk_map_t , remove_ , bool , private_tkm_chunk_map_t *const this, chunk_t * data)
Definition at line 103 of file tkm_chunk_map.c.
References entry_destroy(), FALSE, lock, TRUE, and spinlock_t::unlock.
 {
     entry_t *entry;
     this->lock->write_lock(this->lock);
     entry = this->mappings->remove(this->mappings, data);
     this->lock->unlock(this->lock);
     if (entry)
     {
         entry_destroy(entry);
         return TRUE;
     }
     else
     {
         return FALSE;
     }
 }
METHOD (tkm_chunk_map_t , destroy , void , private_tkm_chunk_map_t * this)
Definition at line 123 of file tkm_chunk_map.c.
References spinlock_t::destroy, enumerator_t::destroy, entry_destroy(), enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     entry_t *entry;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->mappings->create_enumerator(this->mappings);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         entry_destroy(entry);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     this->mappings->destroy(this->mappings);
     this->lock->destroy(this->lock);
     free(this);
 }