strongSwan: pkcs11_rng.c File Reference
pkcs11_rng.c File Reference
#include "pkcs11_rng.h"
#include <utils/debug.h>
#include "pkcs11_manager.h"
Classes
struct private_pkcs11_rng_t
Typedefs
typedef struct private_pkcs11_rng_t private_pkcs11_rng_t
Functions
METHOD (rng_t, get_bytes, bool, private_pkcs11_rng_t *this, size_t bytes, u_int8_t *buffer)
METHOD (rng_t, allocate_bytes, bool, private_pkcs11_rng_t *this, size_t bytes, chunk_t *chunk)
METHOD (rng_t, destroy, void, private_pkcs11_rng_t *this)
static pkcs11_library_t * find_token (CK_SESSION_HANDLE *session)
pkcs11_rng_t * pkcs11_rng_create (rng_quality_t quality)
Typedef Documentation
typedef struct private_pkcs11_rng_t private_pkcs11_rng_t
Definition at line 22 of file pkcs11_rng.c.
Function Documentation
static pkcs11_library_t* find_token (CK_SESSION_HANDLE * session) static
Find a token with its own RNG
Definition at line 81 of file pkcs11_rng.c.
References ck_function_list::C_GetTokenInfo, ck_function_list::C_OpenSession, CKF_RNG, CKF_SERIAL_SESSION, CKR_OK, pkcs11_manager_t::create_token_enumerator, enumerator_t::destroy, enumerator_t::enumerate, pkcs11_library_t::f, ck_token_info::flags, found, library_t::get, and lib.
Referenced by pkcs11_rng_create().
 {
     enumerator_t *tokens;
     pkcs11_manager_t *manager;
     pkcs11_library_t *current, *found = NULL;
     CK_SLOT_ID slot;
     manager = lib->get(lib, "pkcs11-manager");
     if (!manager)
     {
         return NULL;
     }
     tokens = manager->create_token_enumerator(manager);
     while (tokens->enumerate(tokens, &current, &slot))
     {
         CK_TOKEN_INFO info;
         CK_RV rv;
         rv = current->f->C_GetTokenInfo(slot, &info);
         if (rv != CKR_OK)
         {
             continue;
         }
         if (info.flags & CKF_RNG)
         {
             if (current->f->C_OpenSession(slot, CKF_SERIAL_SESSION,
                                           NULL, NULL, session) == CKR_OK)
             {
                 found = current;
                 break;
             }
         }
     }
     tokens->destroy(tokens);
     return found;
 }
METHOD (rng_t , get_bytes , bool , private_pkcs11_rng_t * this, size_t bytes, u_int8_t * buffer)
Definition at line 46 of file pkcs11_rng.c.
References ck_rv_names, CKR_OK, DBG1, DBG_CFG, FALSE, lib, and TRUE.
 {
     CK_RV rv;
     rv = this->lib->f->C_GenerateRandom(this->session, buffer, bytes);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_GenerateRandom() failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     return TRUE;
 }
METHOD (rng_t , allocate_bytes , bool , private_pkcs11_rng_t * this, size_t bytes, chunk_t * chunk)
Definition at line 59 of file pkcs11_rng.c.
References chunk_alloc, chunk_clear(), FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
 {
     *chunk = chunk_alloc(bytes);
     if (!get_bytes(this, chunk->len, chunk->ptr))
     {
         chunk_clear(chunk);
         return FALSE;
     }
     return TRUE;
 }
METHOD (rng_t , destroy , void , private_pkcs11_rng_t * this)
Definition at line 71 of file pkcs11_rng.c.
References free(), and lib.
 {
     this->lib->f->C_CloseSession(this->session);
     free(this);
 }