strongSwan: pts_file_meas_t Struct Reference
pts_file_meas_t Struct Reference
pts_file_meas
#include "pts_file_meas.h"
Public Attributes
u_int16_t(* get_request_id)(pts_file_meas_t *this)
int(* get_file_count)(pts_file_meas_t *this)
void(* add)(pts_file_meas_t *this, char *filename, chunk_t measurement)
enumerator_t *(* create_enumerator)(pts_file_meas_t *this)
bool(* check)(pts_file_meas_t *this, pts_database_t *db, int pid, pts_meas_algorithms_t algo)
bool(* verify)(pts_file_meas_t *this, enumerator_t *e_hash, bool is_dir)
void(* destroy)(pts_file_meas_t *this)
Detailed Description
Class storing PTS File Measurements
Definition at line 34 of file pts_file_meas.h.
Member Data Documentation
void(* pts_file_meas_t::add)(pts_file_meas_t *this, char *filename, chunk_t measurement)
Add a PTS File Measurement
Parameters
filename Name of measured file or directory
measurement PTS Measurement hash
Definition at line 56 of file pts_file_meas.h.
bool(* pts_file_meas_t::check)(pts_file_meas_t *this, pts_database_t *db, int pid, pts_meas_algorithms_t algo)
Check PTS File Measurements against reference value in the database
Parameters
db PTS Measurement database
pid Primary key of software product in database
algo PTS Measurement algorithm used
Returns
TRUE if all measurements agreed
Definition at line 73 of file pts_file_meas.h.
Referenced by imv_attestation_process().
enumerator_t*(* pts_file_meas_t::create_enumerator)(pts_file_meas_t *this)
Create a PTS File Measurement enumerator
Returns
Enumerator returning filename and measurement
Definition at line 63 of file pts_file_meas.h.
Referenced by add_hash(), and imv_attestation_process().
void(* pts_file_meas_t::destroy)(pts_file_meas_t *this)
Destroys a pts_file_meas_t object.
Definition at line 88 of file pts_file_meas.h.
Referenced by add_hash().
int(* pts_file_meas_t::get_file_count)(pts_file_meas_t *this)
Get the number of measured files
Returns
Number of measured files
Definition at line 48 of file pts_file_meas.h.
Referenced by add_hash(), imv_attestation_process(), and tcg_pts_attr_file_meas_create().
u_int16_t(* pts_file_meas_t::get_request_id)(pts_file_meas_t *this)
Get the ID of the PTS File Measurement Request
Returns
ID of PTS File Measurement Request
Definition at line 41 of file pts_file_meas.h.
Referenced by imv_attestation_process(), and tcg_pts_attr_file_meas_create().
bool(* pts_file_meas_t::verify)(pts_file_meas_t *this, enumerator_t *e_hash, bool is_dir)
Verify stored hashes against PTS File Measurements
Parameters
e_hash Hash enumerator
is_dir TRUE for directory contents hashes
Returns
TRUE if all hashes match a measurement
Definition at line 83 of file pts_file_meas.h.
Referenced by imv_attestation_process().
The documentation for this struct was generated from the following file:
pts_file_meas.h