strongSwan: imv_session
imv_session
imv
Classes
struct imv_session_t
Typedefs
typedef struct imv_session_t imv_session_t
Functions
imv_session_t * imv_session_create (TNC_ConnectionID id, time_t created, linked_list_t *ar_identities)
Detailed Description
Typedef Documentation
typedef struct imv_session_t imv_session_t
Definition at line 33 of file imv_session.h.
Function Documentation
imv_session_t* imv_session_create (TNC_ConnectionID conn_id, time_t created, linked_list_t * ar_identities)
Create an imv_session_t instance
Parameters
id Associated Connection ID
created Session creation time
ar_identities List of Access Requestor identities
See header
Definition at line 262 of file imv_session.c.
References imv_os_info_create(), INIT, and linked_list_create().
Referenced by METHOD().
 {
     private_imv_session_t *this;
     INIT(this,
         .public = {
             .set_session_id = _set_session_id,
             .get_session_id = _get_session_id,
             .get_connection_id = _get_connection_id,
             .get_creation_time = _get_creation_time,
             .create_ar_identities_enumerator = _create_ar_identities_enumerator,
             .get_os_info = _get_os_info,
             .set_device_id = _set_device_id,
             .get_device_id = _get_device_id,
             .set_device_trust = _set_device_trust,
             .get_device_trust = _get_device_trust,
             .set_policy_started = _set_policy_started,
             .get_policy_started = _get_policy_started,
             .insert_workitem = _insert_workitem,
             .remove_workitem = _remove_workitem,
             .create_workitem_enumerator = _create_workitem_enumerator,
             .get_workitem_count = _get_workitem_count,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .conn_id = conn_id,
         .created = created,
         .ar_identities = ar_identities,
         .os_info = imv_os_info_create(),
         .workitems = linked_list_create(),
         .ref = 1,
     );
     return &this->public;
 }