strongSwan: ac_t Struct Reference
ac_t Struct Reference
ac
#include "ac.h"
Public Attributes
certificate_t certificate
chunk_t(* get_serial)(ac_t *this)
chunk_t(* get_holderSerial)(ac_t *this)
identification_t *(* get_holderIssuer)(ac_t *this)
chunk_t(* get_authKeyIdentifier)(ac_t *this)
enumerator_t *(* create_group_enumerator)(ac_t *this)
Detailed Description
X.509 attribute certificate interface.
This interface adds additional methods to the certificate_t type to allow further operations on these certificates.
Definition at line 46 of file ac.h.
Member Data Documentation
certificate_t ac_t::certificate
Implements the certificate_t interface
Definition at line 51 of file ac.h.
Referenced by add_attribute_certs(), and METHOD().
enumerator_t*(* ac_t::create_group_enumerator)(ac_t *this)
Create an enumerator of contained Group memberships.
Returns
enumerator over (ac_group_type_t, chunk_t)
Definition at line 86 of file ac.h.
Referenced by apply(), print_ac(), and stroke_list_acerts().
chunk_t(* ac_t::get_authKeyIdentifier)(ac_t *this)
Get the authorityKeyIdentifier.
Returns
authKeyIdentifier as chunk_t, to internal data
Definition at line 79 of file ac.h.
Referenced by print_ac(), and stroke_list_acerts().
identification_t*(* ac_t::get_holderIssuer)(ac_t *this)
Get the issuer of the holder certificate.
Returns
holderIssuer as identification_t*
Definition at line 72 of file ac.h.
Referenced by add_attribute_certs(), METHOD(), print_ac(), and stroke_list_acerts().
chunk_t(* ac_t::get_holderSerial)(ac_t *this)
Get the serial number of the holder certificate.
Returns
chunk pointing to serialNumber
Definition at line 65 of file ac.h.
Referenced by print_ac(), and stroke_list_acerts().
chunk_t(* ac_t::get_serial)(ac_t *this)
Get the attribute certificate's serial number.
Returns
chunk pointing to serialNumber
Definition at line 58 of file ac.h.
Referenced by print_ac(), and stroke_list_acerts().
The documentation for this struct was generated from the following file:
ac.h