strongSwan: enumerator_t Struct Reference
enumerator_t Struct Reference
enumerator
#include "enumerator.h"
Public Attributes
bool(* enumerate)(enumerator_t *this,...)
void(* destroy)(enumerator_t *this)
Detailed Description
Enumerator interface, allows enumeration over collections.
Definition at line 32 of file enumerator.h.
Member Data Documentation
void(* enumerator_t::destroy)(enumerator_t *this)
Destroy a enumerator instance.
Definition at line 48 of file enumerator.h.
Referenced by accept_push(), activate_all(), activate_task(), add_cdps(), add_certreqs(), add_child_cfgs(), add_endpoints_to_message(), add_entry(), add_esp_proposals(), add_exclude_async(), add_exclude_route(), add_file_list_key(), add_groups_from_list(), add_hash(), add_ike_proposals(), add_ike_sa_parameters(), add_im_certs(), add_installed_packages(), add_interface(), add_key_values(), add_list_key(), add_local_certs(), add_matching_ike_sas(), add_quadruple(), add_sections(), add_swid_inventory(), add_to_proposal_v1(), add_to_proposal_v1_ike(), add_to_proposal_v2(), add_traffic_selectors(), add_ts(), add_unity_split_attribute(), add_workitems(), addr_map_destroy(), address2entry(), adopt_children_and_vips(), algo_list_equals(), allocate_addr(), allocate_spi(), apply(), apply_filter(), array_from_ts_list(), array_insert_enumerator(), asn1_oid_from_string(), assign_migrated_vip(), auth_cfg_equal(), auth_cfg_equals(), auth_contains_cacert(), bridge_each(), bridge_each_iface(), bridge_find(), build_ack(), build_address_list(), build_attributes(), build_auth_cfg(), build_auth_cfgs(), build_cert_chain(), build_cert_payload(), build_certreqs(), build_certs(), build_encoding(), build_fds(), build_pairs(), build_payloads(), build_peer_cfg(), build_plugin_checksums(), build_reply(), build_request(), build_requestList(), build_response(), build_set(), cache_queue(), calculate_wire_size(), call_fixture(), CALLBACK(), cancel_quick_mode(), check_addrblock(), check_and_build_recommendation(), check_certificate(), check_constraints(), check_crl(), check_delta_crl(), check_for_rekeyed_child(), check_lease(), check_lifetime(), check_name_constraints(), check_ocsp(), check_oid(), check_policy(), check_policy_constraints(), check_proposal(), check_queued_tasks(), check_systime(), check_timeouts(), check_trust(), checkout_ikesa(), child_exited(), cleanup_leases(), cleanup_policies(), cleanup_sas(), cleanup_sessions(), clear_start_action(), clear_start_actions(), close_child(), close_ike(), collect_stats(), collect_tags(), compare_dn(), complete(), compute_length(), confread_load(), conn_get(), connect_guest(), copy_certs(), copy_proposal_algs(), cowfs_readdir(), create_fragment(), create_inner_cdp(), create_key(), create_pool(), create_session(), create_unique_cert_list(), curve_to_ec_group(), decrypt(), decrypt_and_unpack(), decrypt_payloads(), decrypt_private_key(), decrypt_with_config(), del(), del_attr(), delete_all_async(), delete_connection(), destroy_and_reestablish(), destroy_dh_mapping(), disable_all(), disconnect(), disconnect_async(), dn_matches(), dntoa(), do_another_auth(), do_load_test(), do_netstat(), do_remove_at(), do_test_single(), docleanup(), eap_payload_create_nak(), eap_radius_create_client(), eap_vendor_type_from_string(), ec_group_to_curve(), edit(), enable_disable(), encode(), enumerator_create_nested(), enumerator_create_token(), enumerator_destroy(), export(), export_csv(), filter_cipher_config_suites(), filter_key_exchange_config_suites(), filter_mac_config_suites(), filter_specific_config_suites(), filter_suite(), find_addr(), find_child_cfg(), find_client_id(), find_connection(), find_crl(), find_entry(), find_key(), find_key_by_keyid(), find_lib(), find_lib_by_keyid(), find_pool(), find_private(), find_pubkey_in_certs(), find_public_key(), find_reqid(), find_smartcard_key(), find_supported_curve(), find_token(), find_value(), flush_allocated_spis(), flush_entries(), free_hashtable(), gather_and_add_endpoints(), generate(), generate_auth_cfg(), generate_message(), generate_tags(), get_active(), get_any_socket(), get_attr(), get_attr_pool(), get_auth_cfg(), get_auth_class(), get_better_crl(), get_child_from_peer(), get_default_digest(), get_dynamic_hosts(), get_existing(), get_first_ts(), get_identity(), get_ike_cfg_by_id(), get_interface_address(), get_issuer_cert(), get_lease(), get_life_duration(), get_matching_ike_sas(), get_message_data(), get_next_test_vector(), get_page(), get_peer_by_id(), get_peer_cfg_by_id(), get_peer_match(), get_pool(), get_private_by_keyid(), get_proposals(), get_proxy_addr(), get_rd(), get_reassigned(), get_remote_identity_id(), get_retry_delay(), get_route(), get_string(), get_supported_eap_types(), get_transport_nat_ts(), get_triggered_pair(), get_ts(), get_ts_match(), get_use_time(), guest_each_iface(), guest_find_iface(), guest_hash_create(), ha_attribute_create(), handle_ack(), handle_attribute(), handle_certs(), handle_collisions(), handle_event(), handle_events(), handle_offer(), handle_plain(), handle_preferred_eap_types(), handle_result(), handler_to_val(), has_host_family(), has_invalid_certs(), has_no_any_policy(), has_no_policy_mapping(), has_notify_errors(), has_owner(), has_policy(), has_policy_chain(), has_queued(), has_split_includes(), has_vip(), hash(), hash_ts_array(), have_aggressive_mode_task(), have_equal_ts(), have_pool(), have_quick_mode_task(), identity_attribute(), iface_each_addr(), ike2queue(), ike_cfg_get_family(), imv_attestation_build(), imv_attestation_process(), init_address_list(), initiate(), initiate_config(), initiate_mediated(), insert_file_hash(), insert_pair_by_priority(), install_sas(), install_shunt_policy(), install_sps(), install_vips(), is_any_path_valid(), is_attribute_selected(), is_child_queued(), is_compliant(), is_local(), is_policy_valid(), is_redundant(), is_reinject_config(), issue(), iterate_enforcements(), join_groups(), kernel_interface_create(), kernel_netlink_net_create(), leases(), linked_list_create_from_enumerator(), list(), list_algs(), list_child(), list_plugins(), list_task_queue(), list_uris(), list_vips(), liveness(), load_actions(), load_addrs(), load_authorities_cfg(), load_ca(), load_ca_certs(), load_cacerts(), load_cdps(), load_cert(), load_certdir(), load_certs(), load_cfg_candidates(), load_child_config(), load_configs(), load_conn(), load_conns_cfg(), load_containers(), load_creds_cfg(), load_entries(), load_features(), load_from_stream(), load_hooks(), load_ike_config(), load_keys(), load_loggers(), load_method(), load_peer_config(), load_pkcs12(), load_pools(), load_pools_cfg(), load_proposals(), load_registered(), load_secret(), load_session(), load_setup(), loaded_plugins_list(), log_auth(), log_auth_cfgs(), log_authority_data(), log_children(), log_ike_sa(), log_peer_data(), log_task_q(), login(), lookup_iv(), lookup_quick_mode(), lookup_shared_key(), main(), manage_out(), manage_policies(), manage_route(), manage_routes(), match(), merge(), merge_config(), METHOD(), migrate_child_tasks(), mode_config_expected(), modular_pluginlist(), name_constraint_inherited(), name_constraint_matches(), narrow_initiator(), net_changes_clear(), notify_end(), on_accept(), order_payloads(), parse_addresses(), parse_directoryName(), parse_message(), parse_PFX(), parse_pubkey_constraints(), parse_ranges(), parse_rounds(), parse_selector(), parse_token(), pem_to_bin(), pkcs11_creds_load(), plugin_loaded(), plugin_loader_add_plugindirs(), policy_start(), policy_stop(), pool_leases(), prefer_cert(), prepare_sa_cfg(), print_ac(), print_alg(), print_all(), print_checklist(), print_crl(), print_mechs(), print_radius_attributes(), print_traces(), print_x509(), process(), process_addr(), process_auth_response(), process_cert_verify(), process_certreq(), process_certreqs(), process_certs(), process_cfg_attributes(), process_challenge(), process_child_add(), process_child_delete(), process_childsa(), process_class(), process_client_error(), process_coa(), process_eap(), process_filter_id(), process_identity(), process_ike_add(), process_ike_delete(), process_ike_iv(), process_ike_mid(), process_ike_update(), process_ikesa(), process_link(), process_notification(), process_payloads(), process_peer_failure(), process_peer_success(), process_peerconfig(), process_pkcs7(), process_reauthentication(), process_request(), process_response(), process_resync(), process_segment(), process_start(), process_status(), process_synchronize(), process_timeout(), proposal_add_supported_ike(), proposal_create_from_string(), proposal_printf_hook(), proposal_substructure_create_from_proposals_v1(), prune_pairs(), pts_dh_group_probe(), pts_meas_algo_probe(), publish_device_ip_addresses(), purge_plugins(), push_dns_env(), push_vip_env(), quit(), radius2ike(), radius2queue(), radius_receive(), raise_policy(), raise_policy_cfg(), read_result(), read_triplets(), reauth(), rebuild_auth(), receive_casts(), receive_message(), receive_msg(), register_dh_mapping(), register_logger(), register_peer(), reinstall_routes(), rekey_child(), rekey_children(), rekey_ike(), rekey_segment(), reload_by_name(), reload_metadata(), remove_addr(), remove_checklist(), remove_connected_peers(), remove_entry(), remove_exclude_route(), remove_from_list(), remove_include(), remove_initiated(), remove_interface(), remove_specific(), remove_trap(), replace_children(), request_control_initiate(), request_control_terminate(), request_query_config(), request_query_ikesa(), resize(), resolve(), resolve_also(), resolve_also_single(), run_case(), run_filter(), run_scripts(), run_start_actions(), run_suite(), sa_payload_create_from_proposals_v2(), save_retransmit(), save_state(), scan_fds(), scep_parse_response(), schedule_autoinit(), select_algo(), select_compliant_config(), select_signature_schemes(), send_certificate(), send_certificate_request(), send_certreq(), send_client_hello(), send_interim(), send_packets(), send_retransmit(), send_sasl_mechs(), send_stop(), send_supported_hash_algorithms(), set_bit(), set_byte(), set_from_proposal_v1(), set_from_proposal_v1_ike(), set_from_proposal_v2(), settings_section_extend(), shared_entry_equals(), show(), sigchld_handler(), sign_crl(), sign_signature_auth(), signal_ipv4_config(), start_all_guests(), start_cron(), START_TEST(), status(), status_attr(), stroke_export(), stroke_list_acerts(), stroke_list_certs(), stroke_list_crls(), stroke_list_ocsp(), stroke_list_pgp(), stroke_list_pubkeys(), subscribe(), subscribed(), sync_vips(), template_each(), terminate(), test_runner_run(), TNC_IMC_BeginHandshake(), TNC_IMC_NotifyConnectionChange(), token_event_cb(), traffic_selector_printf_hook(), trigger_mbb_reauth(), ts_array_equals(), ts_list_is_host(), ts_payload_create_from_traffic_selectors(), uncache_iface(), uninstall_shunt_policy(), unload_features(), unregister_event(), unregister_features(), unregister_logger(), unregister_peer(), update_addrs(), update_cfg_candidates(), update_checklist_state(), update_children(), update_database(), update_interface(), update_usetime(), updown_handler_create(), use_certs(), verify(), verify_crl(), verify_key_values(), verify_ocsp(), verify_sections(), vici_disconnect(), vici_free_res(), vici_message_create_from_enumerator(), watch(), write_networks(), x509_build_crlDistributionPoints(), x509_build_subjectAltNames(), x509_cert_gen(), x509_crl_gen(), and x509_pkcs10_gen().
bool(* enumerator_t::enumerate)(enumerator_t *this,...)
Enumerate collection.
The enumerate function takes a variable argument list containing pointers where the enumerated values get written.
Parameters
... variable list of enumerated items, implementation dependent
Returns
TRUE if pointers returned
Definition at line 43 of file enumerator.h.
Referenced by accept_push(), activate_all(), activate_task(), add_cdps(), add_certreqs(), add_endpoints_to_message(), add_entry(), add_esp_proposals(), add_exclude_async(), add_exclude_route(), add_file_list_key(), add_groups_from_list(), add_hash(), add_ike_proposals(), add_ike_sa_parameters(), add_im_certs(), add_installed_packages(), add_interface(), add_key_values(), add_list_key(), add_local_certs(), add_matching_ike_sas(), add_quadruple(), add_sections(), add_settings(), add_swid_inventory(), add_to_proposal_v1(), add_to_proposal_v1_ike(), add_to_proposal_v2(), add_ts(), add_unity_split_attribute(), add_workitems(), addr_map_destroy(), address2entry(), adopt_children_and_vips(), algo_list_equals(), allocate_addr(), allocate_spi(), apply(), apply_filter(), array_from_ts_list(), array_insert_enumerator(), asn1_oid_from_string(), assign_migrated_vip(), auth_cfg_equal(), auth_cfg_equals(), auth_contains_cacert(), bridge_each(), bridge_each_iface(), bridge_find(), build_ack(), build_address_list(), build_attributes(), build_auth_cfg(), build_auth_cfgs(), build_cert_chain(), build_cert_payload(), build_certreqs(), build_certs(), build_child_cfg(), build_encoding(), build_fds(), build_ike_cfg(), build_pairs(), build_payloads(), build_peer_cfg(), build_plugin_checksums(), build_reply(), build_request(), build_requestList(), build_response(), build_set(), build_traffic_selector(), cache_queue(), calculate_wire_size(), call_fixture(), CALLBACK(), cancel_quick_mode(), check_addrblock(), check_and_build_recommendation(), check_certificate(), check_constraints(), check_crl(), check_delta_crl(), check_for_rekeyed_child(), check_lease(), check_lifetime(), check_name_constraints(), check_ocsp(), check_oid(), check_policy(), check_policy_constraints(), check_proposal(), check_queued_tasks(), check_systime(), check_timeouts(), check_trust(), checkout_ikesa(), child_exited(), cleanup_leases(), cleanup_policies(), cleanup_sas(), cleanup_sessions(), clear_start_action(), clear_start_actions(), close_child(), close_ike(), collect_stats(), collect_tags(), compare_dn(), compare_vici(), complete(), compute_length(), confread_load(), conn_get(), connect_guest(), copy_certs(), copy_proposal_algs(), cowfs_readdir(), create_fragment(), create_key(), create_pool(), create_session(), create_unique_cert_list(), curve_to_ec_group(), decrypt(), decrypt_and_unpack(), decrypt_payloads(), decrypt_private_key(), decrypt_with_config(), del(), del_attr(), delete_all_async(), delete_connection(), destroy_and_reestablish(), destroy_dh_mapping(), disable_all(), disconnect(), disconnect_async(), dn_matches(), dntoa(), do_another_auth(), do_load_test(), do_netstat(), do_remove_at(), do_test_single(), docleanup(), eap_payload_create_nak(), eap_radius_create_client(), eap_vendor_type_from_string(), ec_group_to_curve(), edit(), enable_disable(), encode(), encode_ecdsa(), encode_rsa(), enumerator_create_nested(), enumerator_create_token(), enumerator_enumerate(), export(), export_csv(), filter_cipher_config_suites(), filter_key_exchange_config_suites(), filter_mac_config_suites(), filter_specific_config_suites(), filter_suite(), find_addr(), find_child_cfg(), find_client_id(), find_connection(), find_crl(), find_entry(), find_key(), find_key_by_keyid(), find_lib(), find_lib_by_keyid(), find_pool(), find_private(), find_pubkey_in_certs(), find_public_key(), find_reqid(), find_smartcard_key(), find_supported_curve(), find_token(), find_value(), flush_allocated_spis(), flush_entries(), free_hashtable(), gather_and_add_endpoints(), generate(), generate_auth_cfg(), generate_message(), generate_tags(), get_active(), get_any_socket(), get_attr(), get_attr_pool(), get_auth_cfg(), get_auth_class(), get_better_crl(), get_child_from_peer(), get_default_digest(), get_dynamic_hosts(), get_existing(), get_first_ts(), get_identity(), get_interface_address(), get_issuer_cert(), get_lease(), get_life_duration(), get_matching_ike_sas(), get_message_data(), get_next_test_vector(), get_page(), get_peer_by_id(), get_peer_match(), get_pool(), get_private_by_keyid(), get_proposals(), get_proxy_addr(), get_rd(), get_reassigned(), get_remote_identity_id(), get_retry_delay(), get_route(), get_string(), get_supported_eap_types(), get_transport_nat_ts(), get_triggered_pair(), get_ts(), get_ts_match(), get_use_time(), guest_each_iface(), guest_find_iface(), guest_hash_create(), handle_ack(), handle_attribute(), handle_certs(), handle_collisions(), handle_events(), handle_offer(), handle_plain(), handle_preferred_eap_types(), handle_result(), handler_to_val(), has_host_family(), has_invalid_certs(), has_no_any_policy(), has_no_policy_mapping(), has_notify_errors(), has_owner(), has_policy(), has_policy_chain(), has_queued(), has_split_includes(), has_vip(), hash(), hash_ts_array(), have_aggressive_mode_task(), have_equal_ts(), have_pool(), have_quick_mode_task(), identity_attribute(), iface_each_addr(), ike2queue(), ike_cfg_get_family(), imv_attestation_build(), imv_attestation_process(), imv_lang_string_select_lang(), init_address_list(), initiate(), initiate_config(), initiate_mediated(), insert_file_hash(), insert_pair_by_priority(), install_sas(), install_shunt_policy(), install_sps(), install_vips(), is_any_path_valid(), is_attribute_selected(), is_child_queued(), is_compliant(), is_local(), is_policy_valid(), is_redundant(), is_reinject_config(), issue(), iterate_enforcements(), join_groups(), kernel_interface_create(), kernel_netlink_net_create(), leases(), linked_list_create_from_enumerator(), list(), list_algs(), list_child(), list_plugins(), list_task_queue(), list_uris(), list_vips(), liveness(), load_actions(), load_addrs(), load_authorities_cfg(), load_ca(), load_ca_certs(), load_cacerts(), load_cdps(), load_cert(), load_certdir(), load_certs(), load_cfg_candidates(), load_child_config(), load_configs(), load_conn(), load_conns_cfg(), load_containers(), load_creds_cfg(), load_entries(), load_features(), load_from_stream(), load_hooks(), load_ike_config(), load_keys(), load_loggers(), load_method(), load_peer_config(), load_pkcs12(), load_pools(), load_pools_cfg(), load_proposals(), load_registered(), load_secret(), load_session(), load_setup(), loaded_plugins_list(), log_auth(), log_auth_cfgs(), log_authority_data(), log_children(), log_ike_sa(), log_peer_data(), log_task_q(), login(), lookup_iv(), lookup_quick_mode(), lookup_shared_key(), main(), manage_out(), manage_policies(), manage_route(), manage_routes(), match(), merge(), merge_config(), METHOD(), migrate_child_tasks(), mode_config_expected(), modular_pluginlist(), name_constraint_inherited(), name_constraint_matches(), narrow_initiator(), net_changes_clear(), notify_end(), on_accept(), order_payloads(), parse_addresses(), parse_directoryName(), parse_message(), parse_PFX(), parse_pubkey_constraints(), parse_ranges(), parse_rounds(), parse_selector(), parse_token(), pem_to_bin(), pkcs11_creds_load(), plugin_loaded(), plugin_loader_add_plugindirs(), policy_start(), policy_stop(), pool_leases(), prefer_cert(), prepare_sa_cfg(), print_ac(), print_alg(), print_all(), print_checklist(), print_crl(), print_mechs(), print_radius_attributes(), print_traces(), print_x509(), process(), process_addr(), process_auth_response(), process_cert_verify(), process_certreq(), process_certreqs(), process_certs(), process_cfg_attributes(), process_challenge(), process_child_add(), process_child_delete(), process_childsa(), process_class(), process_client_error(), process_coa(), process_eap(), process_filter_id(), process_identity(), process_ike_add(), process_ike_delete(), process_ike_iv(), process_ike_mid(), process_ike_update(), process_ikesa(), process_link(), process_notification(), process_payloads(), process_peer_failure(), process_peer_success(), process_peerconfig(), process_pkcs7(), process_reauthentication(), process_request(), process_response(), process_resync(), process_segment(), process_start(), process_status(), process_synchronize(), process_timeout(), proposal_add_supported_ike(), proposal_create_from_string(), proposal_printf_hook(), proposal_substructure_create_from_proposals_v1(), prune_pairs(), pts_dh_group_probe(), pts_meas_algo_probe(), publish_device_ip_addresses(), purge_plugins(), push_dns_env(), push_vip_env(), quit(), radius2ike(), radius2queue(), radius_receive(), raise_policy(), raise_policy_cfg(), read_result(), read_revoked(), read_triplets(), reauth(), rebuild_auth(), receive_casts(), receive_message(), receive_msg(), register_dh_mapping(), register_logger(), register_peer(), reinstall_routes(), rekey_child(), rekey_children(), rekey_ike(), rekey_segment(), reload_by_name(), reload_metadata(), remove_addr(), remove_checklist(), remove_connected_peers(), remove_entry(), remove_exclude_route(), remove_from_list(), remove_include(), remove_initiated(), remove_interface(), remove_specific(), remove_trap(), replace_children(), request_control_initiate(), request_control_terminate(), request_query_config(), request_query_ikesa(), resize(), resolve(), resolve_also(), resolve_also_single(), run_case(), run_filter(), run_scripts(), run_start_actions(), run_suite(), sa_payload_create_from_proposals_v2(), save_retransmit(), save_state(), scan_fds(), scep_parse_response(), schedule_autoinit(), select_algo(), select_compliant_config(), select_signature_schemes(), send_certificate(), send_certificate_request(), send_certreq(), send_client_hello(), send_interim(), send_packets(), send_retransmit(), send_sasl_mechs(), send_stop(), send_supported_hash_algorithms(), set_bit(), set_byte(), set_from_proposal_v1(), set_from_proposal_v1_ike(), set_from_proposal_v2(), settings_section_extend(), shared_entry_equals(), show(), sigchld_handler(), sign_signature_auth(), signal_ipv4_config(), start_all_guests(), start_cron(), START_TEST(), status(), status_attr(), stroke_export(), stroke_list_acerts(), stroke_list_certs(), stroke_list_crls(), stroke_list_ocsp(), stroke_list_pgp(), stroke_list_pubkeys(), subscribe(), subscribed(), sync_vips(), template_each(), terminate(), test_runner_run(), TNC_IMC_BeginHandshake(), TNC_IMC_NotifyConnectionChange(), token_event_cb(), traffic_selector_printf_hook(), trigger_mbb_reauth(), ts_array_equals(), ts_list_is_host(), ts_payload_create_from_traffic_selectors(), uncache_iface(), uninstall_shunt_policy(), unload_features(), unregister_event(), unregister_features(), unregister_logger(), unregister_peer(), update_addrs(), update_cfg_candidates(), update_checklist_state(), update_children(), update_database(), update_interface(), update_usetime(), use_certs(), verify(), verify_crl(), verify_key_values(), verify_ocsp(), verify_sections(), vici_disconnect(), vici_message_create_from_enumerator(), vici_parse(), watch(), write_networks(), x509_build_crlDistributionPoints(), x509_build_subjectAltNames(), x509_cert_gen(), x509_crl_gen(), and x509_pkcs10_gen().
The documentation for this struct was generated from the following file:
enumerator.h