strongSwan: payload
payload
payloads
Classes
struct payload_t
Macros
#define IKEV1_DOI_IPSEC 1
Typedefs
typedef enum payload_type_t payload_type_t
typedef struct payload_t payload_t
Enumerations
enum payload_type_t {
PL_NONE = 0, PLV1_SECURITY_ASSOCIATION = 1, PLV1_PROPOSAL = 2, PLV1_TRANSFORM = 3,
PLV1_KEY_EXCHANGE = 4, PLV1_ID = 5, PLV1_CERTIFICATE = 6, PLV1_CERTREQ = 7,
PLV1_HASH = 8, PLV1_SIGNATURE = 9, PLV1_NONCE = 10, PLV1_NOTIFY = 11,
PLV1_DELETE = 12, PLV1_VENDOR_ID = 13, PLV1_CONFIGURATION = 14, PLV1_NAT_D = 20,
PLV1_NAT_OA = 21, PLV2_SECURITY_ASSOCIATION = 33, PLV2_KEY_EXCHANGE = 34, PLV2_ID_INITIATOR = 35,
PLV2_ID_RESPONDER = 36, PLV2_CERTIFICATE = 37, PLV2_CERTREQ = 38, PLV2_AUTH = 39,
PLV2_NONCE = 40, PLV2_NOTIFY = 41, PLV2_DELETE = 42, PLV2_VENDOR_ID = 43,
PLV2_TS_INITIATOR = 44, PLV2_TS_RESPONDER = 45, PLV2_ENCRYPTED = 46, PLV2_CONFIGURATION = 47,
PLV2_EAP = 48, PLV2_GSPM = 49, PLV2_IDG = 50, PLV2_GSA = 51,
PLV2_KD = 52, PLV2_FRAGMENT = 53, PLV1_NAT_D_DRAFT_00_03 = 130, PLV1_NAT_OA_DRAFT_00_03 = 131,
PLV1_FRAGMENT = 132, PL_HEADER = 256, PL_UNKNOWN, PLV2_PROPOSAL_SUBSTRUCTURE,
PLV1_PROPOSAL_SUBSTRUCTURE, PLV2_TRANSFORM_SUBSTRUCTURE, PLV1_TRANSFORM_SUBSTRUCTURE, PLV2_TRANSFORM_ATTRIBUTE,
PLV1_TRANSFORM_ATTRIBUTE, PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE, PLV2_CONFIGURATION_ATTRIBUTE, PLV1_CONFIGURATION_ATTRIBUTE,
PLV1_ENCRYPTED
}
Functions
payload_t * payload_create (payload_type_t type)
bool payload_is_known (payload_type_t type, u_int8_t maj_ver)
void * payload_get_field (payload_t *payload, encoding_type_t type, u_int skip)
Variables
enum_name_t * payload_type_names
enum_name_t * payload_type_short_names
Detailed Description
Macro Definition Documentation
#define IKEV1_DOI_IPSEC 1
Domain of interpretation used by IPsec/IKEv1
Definition at line 35 of file payload.h.
Referenced by delete_payload_create(), notify_payload_create(), and sa_payload_create().
Typedef Documentation
typedef struct payload_t payload_t
Definition at line 27 of file payload.h.
typedef enum payload_type_t payload_type_t
Definition at line 26 of file payload.h.
Enumeration Type Documentation
enum payload_type_t
Payload-Types of an IKE message.
Header and substructures are also defined as payload types with values from PRIVATE USE space.
Enumerator
PL_NONE
End of payload list in next_payload
PLV1_SECURITY_ASSOCIATION
The security association (SA) payload containing proposals.
PLV1_PROPOSAL
The proposal payload, containing transforms.
PLV1_TRANSFORM
The transform payload.
PLV1_KEY_EXCHANGE
The key exchange (KE) payload containing diffie-hellman values.
PLV1_ID
ID payload.
PLV1_CERTIFICATE
Certificate payload with certificates (CERT).
PLV1_CERTREQ
Certificate request payload.
PLV1_HASH
Hash payload.
PLV1_SIGNATURE
Signature payload
PLV1_NONCE
Nonce payload.
PLV1_NOTIFY
Notification payload.
PLV1_DELETE
Delete payload.
PLV1_VENDOR_ID
Vendor id payload.
PLV1_CONFIGURATION
Attribute payload (ISAKMP Mode Config, aka configuration payload.
PLV1_NAT_D
NAT discovery payload (NAT-D).
PLV1_NAT_OA
NAT original address payload (NAT-OA).
PLV2_SECURITY_ASSOCIATION
The security association (SA) payload containing proposals.
PLV2_KEY_EXCHANGE
The key exchange (KE) payload containing diffie-hellman values.
PLV2_ID_INITIATOR
Identification for the original initiator (IDi).
PLV2_ID_RESPONDER
Identification for the original responder (IDr).
PLV2_CERTIFICATE
Certificate payload with certificates (CERT).
PLV2_CERTREQ
Certificate request payload (CERTREQ).
PLV2_AUTH
Authentication payload contains auth data (AUTH).
PLV2_NONCE
Nonces, for initiator and responder (Ni, Nr, N)
PLV2_NOTIFY
Notify paylaod (N).
PLV2_DELETE
Delete payload (D)
PLV2_VENDOR_ID
Vendor id paylpoad (V).
PLV2_TS_INITIATOR
Traffic selector for the original initiator (TSi).
PLV2_TS_RESPONDER
Traffic selector for the original responser (TSr).
PLV2_ENCRYPTED
Encrypted payload, contains other payloads (E).
PLV2_CONFIGURATION
Configuration payload (CP).
PLV2_EAP
Extensible authentication payload (EAP).
PLV2_GSPM
Generic Secure Password Method (GSPM).
PLV2_IDG
Group Identification (draft-yeung-g-ikev2)
PLV2_GSA
Group Security Association (draft-yeung-g-ikev2)
PLV2_KD
Key Download (draft-yeung-g-ikev2)
PLV2_FRAGMENT
Encrypted fragment payload (SKF), RFC 7383
PLV1_NAT_D_DRAFT_00_03
NAT discovery payload (NAT-D) (drafts).
PLV1_NAT_OA_DRAFT_00_03
NAT original address payload (NAT-OA) (drafts).
PLV1_FRAGMENT
IKEv1 fragment (proprietary IKEv1 extension)
PL_HEADER
Header has a value of PRIVATE USE space.
This type and all the following are never sent over wire and are used internally only.
PL_UNKNOWN
Used to handle unknown or invalid payload types.
PLV2_PROPOSAL_SUBSTRUCTURE
PLV2_PROPOSAL_SUBSTRUCTURE, IKEv2 proposals in a SA payload.
PLV1_PROPOSAL_SUBSTRUCTURE
PLV1_PROPOSAL_SUBSTRUCTURE, IKEv1 proposals in a SA payload.
PLV2_TRANSFORM_SUBSTRUCTURE
PLV2_TRANSFORM_SUBSTRUCTURE, IKEv2 transforms in a proposal substructure.
PLV1_TRANSFORM_SUBSTRUCTURE
PLV1_TRANSFORM_SUBSTRUCTURE, IKEv1 transforms in a proposal substructure.
PLV2_TRANSFORM_ATTRIBUTE
PLV2_TRANSFORM_ATTRIBUTE, IKEv2 attribute in a transform.
PLV1_TRANSFORM_ATTRIBUTE
PLV1_TRANSFORM_ATTRIBUTE, IKEv1 attribute in a transform.
PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE
PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE, traffic selector in a TS payload.
PLV2_CONFIGURATION_ATTRIBUTE
PLV2_CONFIGURATION_ATTRIBUTE, IKEv2 attribute in a configuration payload.
PLV1_CONFIGURATION_ATTRIBUTE
PLV1_CONFIGURATION_ATTRIBUTE, IKEv1 attribute in a configuration payload.
PLV1_ENCRYPTED
This is not really a payload, but rather the complete IKEv1 message.
Definition at line 43 of file payload.h.
                     {
     PL_NONE = 0,
     PLV1_SECURITY_ASSOCIATION = 1,
     PLV1_PROPOSAL = 2,
     PLV1_TRANSFORM = 3,
     PLV1_KEY_EXCHANGE = 4,
     PLV1_ID = 5,
     PLV1_CERTIFICATE = 6,
     PLV1_CERTREQ = 7,
     PLV1_HASH = 8,
     PLV1_SIGNATURE = 9,
     PLV1_NONCE = 10,
     PLV1_NOTIFY = 11,
     PLV1_DELETE = 12,
     PLV1_VENDOR_ID = 13,
     PLV1_CONFIGURATION = 14,
     PLV1_NAT_D = 20,
     PLV1_NAT_OA = 21,
     PLV2_SECURITY_ASSOCIATION = 33,
     PLV2_KEY_EXCHANGE = 34,
     PLV2_ID_INITIATOR = 35,
     PLV2_ID_RESPONDER = 36,
     PLV2_CERTIFICATE = 37,
     PLV2_CERTREQ = 38,
     PLV2_AUTH = 39,
     PLV2_NONCE = 40,
     PLV2_NOTIFY = 41,
     PLV2_DELETE = 42,
     PLV2_VENDOR_ID = 43,
     PLV2_TS_INITIATOR = 44,
     PLV2_TS_RESPONDER = 45,
     PLV2_ENCRYPTED = 46,
     PLV2_CONFIGURATION = 47,
     PLV2_EAP = 48,
     PLV2_GSPM = 49,
     PLV2_IDG = 50,
     PLV2_GSA = 51,
     PLV2_KD = 52,
     PLV2_FRAGMENT = 53,
 #ifdef ME
     PLV2_ID_PEER = 128,
 #endif /* ME */
     PLV1_NAT_D_DRAFT_00_03 = 130,
     PLV1_NAT_OA_DRAFT_00_03 = 131,
     PLV1_FRAGMENT = 132,
     PL_HEADER = 256,
     PL_UNKNOWN,
     PLV2_PROPOSAL_SUBSTRUCTURE,
     PLV1_PROPOSAL_SUBSTRUCTURE,
     PLV2_TRANSFORM_SUBSTRUCTURE,
     PLV1_TRANSFORM_SUBSTRUCTURE,
     PLV2_TRANSFORM_ATTRIBUTE,
     PLV1_TRANSFORM_ATTRIBUTE,
     PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE,
     PLV2_CONFIGURATION_ATTRIBUTE,
     PLV1_CONFIGURATION_ATTRIBUTE,
     PLV1_ENCRYPTED,
 };
Function Documentation
payload_t* payload_create (payload_type_t type)
Create an empty payload.
Useful for the parser, who wants a generic constructor for all payloads. It supports all payload_t methods. If a payload type is not known, an unknwon_paylod is created with the chunk of data in it.
Parameters
type type of the payload to create
Returns
payload_t object
Definition at line 187 of file payload.c.
References auth_payload_create(), cert_payload_create(), certreq_payload_create(), configuration_attribute_create(), cp_payload_create(), delete_payload_create(), eap_payload_create(), encrypted_fragment_payload_create(), encrypted_payload_create(), FALSE, fragment_payload_create(), hash_payload_create(), id_payload_create(), ike_header_create(), ke_payload_create(), nonce_payload_create(), notify_payload_create(), PL_HEADER, PLV1_CERTIFICATE, PLV1_CERTREQ, PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, PLV1_DELETE, PLV1_ENCRYPTED, PLV1_FRAGMENT, PLV1_HASH, PLV1_ID, PLV1_KEY_EXCHANGE, PLV1_NAT_D, PLV1_NAT_D_DRAFT_00_03, PLV1_NAT_OA, PLV1_NAT_OA_DRAFT_00_03, PLV1_NONCE, PLV1_NOTIFY, PLV1_PROPOSAL_SUBSTRUCTURE, PLV1_SECURITY_ASSOCIATION, PLV1_SIGNATURE, PLV1_TRANSFORM_ATTRIBUTE, PLV1_TRANSFORM_SUBSTRUCTURE, PLV1_VENDOR_ID, PLV2_AUTH, PLV2_CERTIFICATE, PLV2_CERTREQ, PLV2_CONFIGURATION, PLV2_CONFIGURATION_ATTRIBUTE, PLV2_DELETE, PLV2_EAP, PLV2_ENCRYPTED, PLV2_FRAGMENT, PLV2_ID_INITIATOR, PLV2_ID_RESPONDER, PLV2_KEY_EXCHANGE, PLV2_NONCE, PLV2_NOTIFY, PLV2_PROPOSAL_SUBSTRUCTURE, PLV2_SECURITY_ASSOCIATION, PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE, PLV2_TRANSFORM_ATTRIBUTE, PLV2_TRANSFORM_SUBSTRUCTURE, PLV2_TS_INITIATOR, PLV2_TS_RESPONDER, PLV2_VENDOR_ID, proposal_substructure_create(), sa_payload_create(), traffic_selector_substructure_create(), transform_attribute_create(), transform_substructure_create(), TRUE, ts_payload_create(), unknown_payload_create(), and vendor_id_payload_create().
Referenced by METHOD().
 {
     switch (type)
     {
         case PL_HEADER:
             return (payload_t*)ike_header_create();
         case PLV2_SECURITY_ASSOCIATION:
         case PLV1_SECURITY_ASSOCIATION:
             return (payload_t*)sa_payload_create(type);
         case PLV2_PROPOSAL_SUBSTRUCTURE:
         case PLV1_PROPOSAL_SUBSTRUCTURE:
             return (payload_t*)proposal_substructure_create(type);
         case PLV2_TRANSFORM_SUBSTRUCTURE:
         case PLV1_TRANSFORM_SUBSTRUCTURE:
             return (payload_t*)transform_substructure_create(type);
         case PLV2_TRANSFORM_ATTRIBUTE:
         case PLV1_TRANSFORM_ATTRIBUTE:
             return (payload_t*)transform_attribute_create(type);
         case PLV2_NONCE:
         case PLV1_NONCE:
             return (payload_t*)nonce_payload_create(type);
         case PLV2_ID_INITIATOR:
         case PLV2_ID_RESPONDER:
         case PLV1_ID:
         case PLV1_NAT_OA:
         case PLV1_NAT_OA_DRAFT_00_03:
 #ifdef ME
         case PLV2_ID_PEER:
 #endif /* ME */
             return (payload_t*)id_payload_create(type);
         case PLV2_AUTH:
             return (payload_t*)auth_payload_create();
         case PLV2_CERTIFICATE:
         case PLV1_CERTIFICATE:
             return (payload_t*)cert_payload_create(type);
         case PLV2_CERTREQ:
         case PLV1_CERTREQ:
             return (payload_t*)certreq_payload_create(type);
         case PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE:
             return (payload_t*)traffic_selector_substructure_create();
         case PLV2_TS_INITIATOR:
             return (payload_t*)ts_payload_create(TRUE);
         case PLV2_TS_RESPONDER:
             return (payload_t*)ts_payload_create(FALSE);
         case PLV2_KEY_EXCHANGE:
         case PLV1_KEY_EXCHANGE:
             return (payload_t*)ke_payload_create(type);
         case PLV2_NOTIFY:
         case PLV1_NOTIFY:
             return (payload_t*)notify_payload_create(type);
         case PLV2_DELETE:
         case PLV1_DELETE:
             return (payload_t*)delete_payload_create(type, 0);
         case PLV2_VENDOR_ID:
         case PLV1_VENDOR_ID:
             return (payload_t*)vendor_id_payload_create(type);
         case PLV1_HASH:
         case PLV1_SIGNATURE:
         case PLV1_NAT_D:
         case PLV1_NAT_D_DRAFT_00_03:
             return (payload_t*)hash_payload_create(type);
         case PLV2_CONFIGURATION:
         case PLV1_CONFIGURATION:
             return (payload_t*)cp_payload_create(type);
         case PLV2_CONFIGURATION_ATTRIBUTE:
         case PLV1_CONFIGURATION_ATTRIBUTE:
             return (payload_t*)configuration_attribute_create(type);
         case PLV2_EAP:
             return (payload_t*)eap_payload_create();
         case PLV2_ENCRYPTED:
         case PLV1_ENCRYPTED:
             return (payload_t*)encrypted_payload_create(type);
         case PLV1_FRAGMENT:
             return (payload_t*)fragment_payload_create();
         case PLV2_FRAGMENT:
             return (payload_t*)encrypted_fragment_payload_create();
         default:
             return (payload_t*)unknown_payload_create(type);
     }
 }
void* payload_get_field (payload_t * payload, encoding_type_t type, u_int skip)
Get the value field in a payload using encoding rules.
Parameters
payload payload to look up a field
type encoding rule type to look up
skip number rules of type to skip, 0 to get first
Returns
type specific value pointer, NULL if not found
See header.
Definition at line 323 of file payload.c.
References count, payload_t::get_encoding_rules, and encoding_rule_t::offset.
Referenced by create_header(), get_reserved_id_bytes(), METHOD(), set_bit(), and set_byte().
 {
     encoding_rule_t *rule;
     int i, count;
     count = payload->get_encoding_rules(payload, &rule);
     for (i = 0; i < count; i++)
     {
         if (rule[i].type == type && skip-- == 0)
         {
             return ((char*)payload) + rule[i].offset;
         }
     }
     return NULL;
 }
bool payload_is_known (payload_type_t type, u_int8_t maj_ver)
Check if a specific payload is implemented, or handled as unknown payload.
Parameters
type type of the payload to check
maj_ver major IKE version (use 0 to skip version check)
Returns
FALSE if payload type handled as unknown payload
See header.
Definition at line 271 of file payload.c.
References FALSE, IKEV1_MAJOR_VERSION, IKEV2_MAJOR_VERSION, PL_HEADER, PLV1_CONFIGURATION, PLV1_FRAGMENT, PLV1_NAT_D, PLV1_NAT_D_DRAFT_00_03, PLV1_NAT_OA, PLV1_SECURITY_ASSOCIATION, PLV2_EAP, PLV2_FRAGMENT, PLV2_SECURITY_ASSOCIATION, and TRUE.
Referenced by METHOD().
 {
     if (type >= PL_HEADER)
     {
         return TRUE;
     }
     switch (maj_ver)
     {
         case 0:
         case IKEV1_MAJOR_VERSION:
             if (type >= PLV1_SECURITY_ASSOCIATION && type <= PLV1_CONFIGURATION)
             {
                 return TRUE;
             }
             if (type >= PLV1_NAT_D && type <= PLV1_NAT_OA)
             {
                 return TRUE;
             }
             if (type >= PLV1_NAT_D_DRAFT_00_03 && type <= PLV1_FRAGMENT)
             {
                 return TRUE;
             }
             if (maj_ver)
             {
                 break;
             }
             /* fall-through */
         case IKEV2_MAJOR_VERSION:
             if (type >= PLV2_SECURITY_ASSOCIATION && type <= PLV2_EAP)
             {
                 return TRUE;
             }
             if (type == PLV2_FRAGMENT)
             {
                 return TRUE;
             }
 #ifdef ME
             if (type == PLV2_ID_PEER)
             {
                 return TRUE;
             }
 #endif
             break;
         default:
             break;
     }
     return FALSE;
 }
Variable Documentation
enum_name_t* payload_type_names
enum names for payload_type_t.
Referenced by decrypt_and_extract(), decrypt_payloads(), METHOD(), order_payloads(), parse(), parse_list(), parse_message(), parse_payloads(), process_payloads(), verify(), and wrap_payloads().
enum_name_t* payload_type_short_names
enum names for payload_type_t in a short form.
Referenced by get_string(), METHOD(), set_bit(), and set_byte().