strongSwan: imv_swid_state.c File Reference
imv_swid_state.c File Reference
#include "imv_swid_state.h"
#include <imv/imv_lang_string.h>
#include <imv/imv_reason_string.h>
#include <imv/imv_remediation_string.h>
#include <swid/swid_tag_id.h>
#include <tncif_policy.h>
#include <utils/lexparser.h>
#include <utils/debug.h>
Classes
struct private_imv_swid_state_t
Typedefs
typedef struct
private_imv_swid_state_t private_imv_swid_state_t
Functions
METHOD (imv_state_t, get_connection_id, TNC_ConnectionID, private_imv_swid_state_t *this)
METHOD (imv_state_t, has_long, bool, private_imv_swid_state_t *this)
METHOD (imv_state_t, has_excl, bool, private_imv_swid_state_t *this)
METHOD (imv_state_t, set_flags, void, private_imv_swid_state_t *this, bool has_long, bool has_excl)
METHOD (imv_state_t, set_max_msg_len, void, private_imv_swid_state_t *this, uint32_t max_msg_len)
METHOD (imv_state_t, get_max_msg_len, uint32_t, private_imv_swid_state_t *this)
METHOD (imv_state_t, set_action_flags, void, private_imv_swid_state_t *this, uint32_t flags)
METHOD (imv_state_t, get_action_flags, uint32_t, private_imv_swid_state_t *this)
METHOD (imv_state_t, set_session, void, private_imv_swid_state_t *this, imv_session_t *session)
METHOD (imv_state_t, get_session, imv_session_t *, private_imv_swid_state_t *this)
METHOD (imv_state_t, get_contracts, seg_contract_manager_t *, private_imv_swid_state_t *this)
METHOD (imv_state_t, change_state, void, private_imv_swid_state_t *this, TNC_ConnectionState new_state)
METHOD (imv_state_t, get_recommendation, void, private_imv_swid_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
METHOD (imv_state_t, set_recommendation, void, private_imv_swid_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, update_recommendation, void, private_imv_swid_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, get_reason_string, bool, private_imv_swid_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
METHOD (imv_state_t, get_remediation_instructions, bool, private_imv_swid_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
METHOD (imv_state_t, destroy, void, private_imv_swid_state_t *this)
METHOD (imv_swid_state_t, set_handshake_state, void, private_imv_swid_state_t *this, imv_swid_handshake_state_t new_state)
METHOD (imv_swid_state_t, get_handshake_state, imv_swid_handshake_state_t, private_imv_swid_state_t *this)
METHOD (imv_swid_state_t, set_request_id, void, private_imv_swid_state_t *this, uint32_t request_id)
METHOD (imv_swid_state_t, get_request_id, uint32_t, private_imv_swid_state_t *this)
METHOD (imv_swid_state_t, set_swid_inventory, void, private_imv_swid_state_t *this, swid_inventory_t *inventory)
METHOD (imv_swid_state_t, get_swid_inventory, json_object *, private_imv_swid_state_t *this)
METHOD (imv_swid_state_t, set_missing, void, private_imv_swid_state_t *this, uint32_t count)
METHOD (imv_swid_state_t, get_missing, uint32_t, private_imv_swid_state_t *this)
METHOD (imv_swid_state_t, set_count, void, private_imv_swid_state_t *this, int tag_id_count, int tag_count)
METHOD (imv_swid_state_t, get_count, void, private_imv_swid_state_t *this, int *tag_id_count, int *tag_count)
imv_state_t * imv_swid_state_create (TNC_ConnectionID connection_id)
Typedef Documentation
typedef struct private_imv_swid_state_t private_imv_swid_state_t
Definition at line 28 of file imv_swid_state.c.
Function Documentation
METHOD (imv_state_t , get_connection_id , TNC_ConnectionID , private_imv_swid_state_t * this)
Definition at line 137 of file imv_swid_state.c.
 {
     return this->connection_id;
 }
METHOD (imv_state_t , has_long , bool , private_imv_swid_state_t * this)
Definition at line 143 of file imv_swid_state.c.
 {
     return this->has_long;
 }
METHOD (imv_state_t , has_excl , bool , private_imv_swid_state_t * this)
Definition at line 149 of file imv_swid_state.c.
 {
     return this->has_excl;
 }
METHOD (imv_state_t , set_flags , void , private_imv_swid_state_t * this, bool has_long, bool has_excl)
Definition at line 155 of file imv_swid_state.c.
 {
     this->has_long = has_long;
     this->has_excl = has_excl;
 }
METHOD (imv_state_t , set_max_msg_len , void , private_imv_swid_state_t * this, uint32_t max_msg_len)
Definition at line 162 of file imv_swid_state.c.
 {
     this->max_msg_len = max_msg_len;
 }
METHOD (imv_state_t , get_max_msg_len , uint32_t , private_imv_swid_state_t * this)
Definition at line 168 of file imv_swid_state.c.
 {
     return this->max_msg_len;
 }
METHOD (imv_state_t , set_action_flags , void , private_imv_swid_state_t * this, uint32_t flags)
Definition at line 174 of file imv_swid_state.c.
References flags.
 {
     this->action_flags |= flags;
 }
METHOD (imv_state_t , get_action_flags , uint32_t , private_imv_swid_state_t * this)
Definition at line 180 of file imv_swid_state.c.
 {
     return this->action_flags;
 }
METHOD (imv_state_t , set_session , void , private_imv_swid_state_t * this, imv_session_t * session)
Definition at line 186 of file imv_swid_state.c.
 {
     this->session = session;
 }
METHOD (imv_state_t , get_session , imv_session_t * , private_imv_swid_state_t * this)
Definition at line 192 of file imv_swid_state.c.
 {
     return this->session;
 }
METHOD (imv_state_t , get_contracts , seg_contract_manager_t * , private_imv_swid_state_t * this)
Definition at line 198 of file imv_swid_state.c.
 {
     return this->contracts;
 }
METHOD (imv_state_t , change_state , void , private_imv_swid_state_t * this, TNC_ConnectionState new_state)
Definition at line 204 of file imv_swid_state.c.
 {
     this->state = new_state;
 }
METHOD (imv_state_t , get_recommendation , void , private_imv_swid_state_t * this, TNC_IMV_Action_Recommendation * rec, TNC_IMV_Evaluation_Result * eval)
Definition at line 210 of file imv_swid_state.c.
 {
     *rec = this->rec;
     *eval = this->eval;
 }
METHOD (imv_state_t , set_recommendation , void , private_imv_swid_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 218 of file imv_swid_state.c.
 {
     this->rec = rec;
     this->eval = eval;
 }
METHOD (imv_state_t , update_recommendation , void , private_imv_swid_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 226 of file imv_swid_state.c.
References tncif_policy_update_evaluation(), and tncif_policy_update_recommendation().
 {
     this->rec  = tncif_policy_update_recommendation(this->rec, rec);
     this->eval = tncif_policy_update_evaluation(this->eval, eval);
 }
METHOD (imv_state_t , get_reason_string , bool , private_imv_swid_state_t * this, enumerator_t * language_enumerator, chunk_t * reason_string, char ** reason_language)
Definition at line 234 of file imv_swid_state.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (imv_state_t , get_remediation_instructions , bool , private_imv_swid_state_t * this, enumerator_t * language_enumerator, chunk_t * string, char ** lang_code, char ** uri)
Definition at line 241 of file imv_swid_state.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (imv_state_t , destroy , void , private_imv_swid_state_t * this)
Definition at line 248 of file imv_swid_state.c.
References DESTROY_IF, and free().
 {
     json_object_put(this->jobj);
     DESTROY_IF(this->session);
     DESTROY_IF(this->reason_string);
     DESTROY_IF(this->remediation_string);
     this->contracts->destroy(this->contracts);
     free(this);
 }
METHOD (imv_swid_state_t , set_handshake_state , void , private_imv_swid_state_t * this, imv_swid_handshake_state_t new_state)
Definition at line 259 of file imv_swid_state.c.
 {
     this->handshake_state = new_state;
 }
METHOD (imv_swid_state_t , get_handshake_state , imv_swid_handshake_state_t , private_imv_swid_state_t * this)
Definition at line 265 of file imv_swid_state.c.
 {
     return this->handshake_state;
 }
METHOD (imv_swid_state_t , set_request_id , void , private_imv_swid_state_t * this, uint32_t request_id)
Definition at line 271 of file imv_swid_state.c.
 {
     this->request_id = request_id;
 }
METHOD (imv_swid_state_t , get_request_id , uint32_t , private_imv_swid_state_t * this)
Definition at line 277 of file imv_swid_state.c.
 {
     return this->request_id;
 }
METHOD (imv_swid_state_t , set_swid_inventory , void , private_imv_swid_state_t * this, swid_inventory_t * inventory)
Definition at line 283 of file imv_swid_state.c.
References swid_inventory_t::create_enumerator, DBG3, DBG_IMV, enumerator_t::destroy, enumerator_t::enumerate, swid_tag_id_t::get_tag_creator, swid_tag_id_t::get_unique_sw_id, chunk_t::len, chunk_t::ptr, and snprintf.
 {
     chunk_t tag_creator, unique_sw_id;
     char software_id[256];
     json_object *jstring;
     swid_tag_id_t *tag_id;
     enumerator_t *enumerator;
     enumerator = inventory->create_enumerator(inventory);
     while (enumerator->enumerate(enumerator, &tag_id))
     {
         /* Construct software ID from tag creator and unique software ID */
         tag_creator = tag_id->get_tag_creator(tag_id);
         unique_sw_id = tag_id->get_unique_sw_id(tag_id, NULL);
         snprintf(software_id, 256, "%.*s_%.*s",
                  tag_creator.len, tag_creator.ptr,
                  unique_sw_id.len, unique_sw_id.ptr);
         DBG3(DBG_IMV, "  %s", software_id);
         /* Add software ID to JSON array */
         jstring = json_object_new_string(software_id);
         json_object_array_add(this->jarray, jstring);
     }
     enumerator->destroy(enumerator);
 }
METHOD (imv_swid_state_t , get_swid_inventory , json_object * , private_imv_swid_state_t * this)
Definition at line 310 of file imv_swid_state.c.
 {
     return this->jobj;
 }
METHOD (imv_swid_state_t , set_missing , void , private_imv_swid_state_t * this, uint32_t count)
Definition at line 316 of file imv_swid_state.c.
References count.
 {
     this->missing = count;
 }
METHOD (imv_swid_state_t , get_missing , uint32_t , private_imv_swid_state_t * this)
Definition at line 322 of file imv_swid_state.c.
 {
     return this->missing;
 }
METHOD (imv_swid_state_t , set_count , void , private_imv_swid_state_t * this, int tag_id_count, int tag_count)
Definition at line 328 of file imv_swid_state.c.
 {
     this->tag_id_count += tag_id_count;
     this->tag_count += tag_count;
 }
METHOD (imv_swid_state_t , get_count , void , private_imv_swid_state_t * this, int * tag_id_count, int * tag_count)
Definition at line 335 of file imv_swid_state.c.
 {
     if (tag_id_count)
     {
         *tag_id_count = this->tag_id_count;
     }
     if (tag_count)
     {
         *tag_count = this->tag_count;
     }
 }