strongSwan: imv_hcd_state.c File Reference
imv_hcd_state.c File Reference
#include "imv_hcd_state.h"
#include "imv/imv_lang_string.h"
#include "imv/imv_reason_string.h"
#include <tncif_policy.h>
#include <utils/debug.h>
Classes
struct subtype_action_flags_t
struct private_imv_hcd_state_t
Typedefs
typedef struct
private_imv_hcd_state_t private_imv_hcd_state_t
typedef struct
subtype_action_flags_t subtype_action_flags_t
Functions
METHOD (imv_state_t, get_connection_id, TNC_ConnectionID, private_imv_hcd_state_t *this)
METHOD (imv_state_t, has_long, bool, private_imv_hcd_state_t *this)
METHOD (imv_state_t, has_excl, bool, private_imv_hcd_state_t *this)
METHOD (imv_state_t, set_flags, void, private_imv_hcd_state_t *this, bool has_long, bool has_excl)
METHOD (imv_state_t, set_max_msg_len, void, private_imv_hcd_state_t *this, uint32_t max_msg_len)
METHOD (imv_state_t, get_max_msg_len, uint32_t, private_imv_hcd_state_t *this)
METHOD (imv_state_t, set_action_flags, void, private_imv_hcd_state_t *this, uint32_t flags)
METHOD (imv_state_t, get_action_flags, uint32_t, private_imv_hcd_state_t *this)
METHOD (imv_state_t, set_session, void, private_imv_hcd_state_t *this, imv_session_t *session)
METHOD (imv_state_t, get_session, imv_session_t *, private_imv_hcd_state_t *this)
METHOD (imv_state_t, get_contracts, seg_contract_manager_t *, private_imv_hcd_state_t *this)
METHOD (imv_state_t, get_recommendation, void, private_imv_hcd_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
METHOD (imv_state_t, set_recommendation, void, private_imv_hcd_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, update_recommendation, void, private_imv_hcd_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, change_state, void, private_imv_hcd_state_t *this, TNC_ConnectionState new_state)
METHOD (imv_state_t, get_reason_string, bool, private_imv_hcd_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
METHOD (imv_state_t, get_remediation_instructions, bool, private_imv_hcd_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
METHOD (imv_state_t, destroy, void, private_imv_hcd_state_t *this)
METHOD (imv_hcd_state_t, set_handshake_state, void, private_imv_hcd_state_t *this, imv_hcd_handshake_state_t new_state)
METHOD (imv_hcd_state_t, get_handshake_state, imv_hcd_handshake_state_t, private_imv_hcd_state_t *this)
METHOD (imv_hcd_state_t, set_subtype, void, private_imv_hcd_state_t *this, pa_subtype_pwg_t subtype)
METHOD (imv_hcd_state_t, set_user_app_disabled, void, private_imv_hcd_state_t *this)
imv_state_t * imv_hcd_state_create (TNC_ConnectionID connection_id)
Variables
static char * languages [] = { "en", "de", "fr", "pl" }
static imv_lang_string_t reasons []
Typedef Documentation
typedef struct private_imv_hcd_state_t private_imv_hcd_state_t
Definition at line 24 of file imv_hcd_state.c.
typedef struct subtype_action_flags_t subtype_action_flags_t
Definition at line 25 of file imv_hcd_state.c.
Function Documentation
METHOD (imv_state_t , get_connection_id , TNC_ConnectionID , private_imv_hcd_state_t * this)
Definition at line 125 of file imv_hcd_state.c.
 {
     return this->connection_id;
 }
METHOD (imv_state_t , has_long , bool , private_imv_hcd_state_t * this)
Definition at line 131 of file imv_hcd_state.c.
 {
     return this->has_long;
 }
METHOD (imv_state_t , has_excl , bool , private_imv_hcd_state_t * this)
Definition at line 137 of file imv_hcd_state.c.
 {
     return this->has_excl;
 }
METHOD (imv_state_t , set_flags , void , private_imv_hcd_state_t * this, bool has_long, bool has_excl)
Definition at line 143 of file imv_hcd_state.c.
 {
     this->has_long = has_long;
     this->has_excl = has_excl;
 }
METHOD (imv_state_t , set_max_msg_len , void , private_imv_hcd_state_t * this, uint32_t max_msg_len)
Definition at line 150 of file imv_hcd_state.c.
 {
     this->max_msg_len = max_msg_len;
 }
METHOD (imv_state_t , get_max_msg_len , uint32_t , private_imv_hcd_state_t * this)
Definition at line 156 of file imv_hcd_state.c.
 {
     return this->max_msg_len;
 }
METHOD (imv_state_t , set_action_flags , void , private_imv_hcd_state_t * this, uint32_t flags)
Definition at line 162 of file imv_hcd_state.c.
References flags.
 {
     *this->action_flags |= flags;
 }
METHOD (imv_state_t , get_action_flags , uint32_t , private_imv_hcd_state_t * this)
Definition at line 168 of file imv_hcd_state.c.
 {
     return *this->action_flags;
 }
METHOD (imv_state_t , set_session , void , private_imv_hcd_state_t * this, imv_session_t * session)
Definition at line 174 of file imv_hcd_state.c.
 {
     this->session = session;
 }
METHOD (imv_state_t , get_session , imv_session_t * , private_imv_hcd_state_t * this)
Definition at line 180 of file imv_hcd_state.c.
 {
     return this->session;
 }
METHOD (imv_state_t , get_contracts , seg_contract_manager_t * , private_imv_hcd_state_t * this)
Definition at line 186 of file imv_hcd_state.c.
 {
     return this->contracts;
 }
METHOD (imv_state_t , get_recommendation , void , private_imv_hcd_state_t * this, TNC_IMV_Action_Recommendation * rec, TNC_IMV_Evaluation_Result * eval)
Definition at line 192 of file imv_hcd_state.c.
 {
     *rec = this->rec;
     *eval = this->eval;
 }
METHOD (imv_state_t , set_recommendation , void , private_imv_hcd_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 200 of file imv_hcd_state.c.
 {
     this->rec = rec;
     this->eval = eval;
 }
METHOD (imv_state_t , update_recommendation , void , private_imv_hcd_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 208 of file imv_hcd_state.c.
References tncif_policy_update_evaluation(), and tncif_policy_update_recommendation().
 {
     this->rec  = tncif_policy_update_recommendation(this->rec, rec);
     this->eval = tncif_policy_update_evaluation(this->eval, eval);
 }
METHOD (imv_state_t , change_state , void , private_imv_hcd_state_t * this, TNC_ConnectionState new_state)
Definition at line 216 of file imv_hcd_state.c.
 {
     this->state = new_state;
 }
METHOD (imv_state_t , get_reason_string , bool , private_imv_hcd_state_t * this, enumerator_t * language_enumerator, chunk_t * reason_string, char ** reason_language)
Definition at line 222 of file imv_hcd_state.c.
References countof, DESTROY_IF, FALSE, imv_lang_string_select_lang(), imv_reason_string_create(), languages, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TRUE.
 {
     if (this->rec == TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION)
     {
         return FALSE;
     }
     *reason_language = imv_lang_string_select_lang(language_enumerator,
                                               languages, countof(languages));
     /* Instantiate a TNC Reason String object */
     DESTROY_IF(this->reason_string);
     this->reason_string = imv_reason_string_create(*reason_language, "\n");
     this->reason_string->add_reason(this->reason_string, reasons);
     *reason_string = this->reason_string->get_encoding(this->reason_string);
     return TRUE;
 }
METHOD (imv_state_t , get_remediation_instructions , bool , private_imv_hcd_state_t * this, enumerator_t * language_enumerator, chunk_t * string, char ** lang_code, char ** uri)
Definition at line 242 of file imv_hcd_state.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (imv_state_t , destroy , void , private_imv_hcd_state_t * this)
Definition at line 249 of file imv_hcd_state.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->session);
     DESTROY_IF(this->reason_string);
     this->contracts->destroy(this->contracts);
     free(this);
 }
METHOD (imv_hcd_state_t , set_handshake_state , void , private_imv_hcd_state_t * this, imv_hcd_handshake_state_t new_state)
Definition at line 258 of file imv_hcd_state.c.
 {
     this->handshake_state = new_state;
 }
METHOD (imv_hcd_state_t , get_handshake_state , imv_hcd_handshake_state_t , private_imv_hcd_state_t * this)
Definition at line 264 of file imv_hcd_state.c.
 {
     return this->handshake_state;
 }
METHOD (imv_hcd_state_t , set_subtype , void , private_imv_hcd_state_t * this, pa_subtype_pwg_t subtype)
Definition at line 270 of file imv_hcd_state.c.
References countof.
 {
     int i;
     for (i = 0; i < countof(this->subtype_action_flags); i++)
     {
         if (subtype == this->subtype_action_flags[i].subtype)
         {
             this->action_flags = &this->subtype_action_flags[i].action_flags;
             break;
         }
     }
 }
METHOD (imv_hcd_state_t , set_user_app_disabled , void , private_imv_hcd_state_t * this)
Definition at line 285 of file imv_hcd_state.c.
References countof, and IMV_HCD_ATTR_USER_APP_NAME.
 {
     int i;
     for (i = 0; i < countof(this->subtype_action_flags); i++)
     {
         this->subtype_action_flags[i].action_flags |= IMV_HCD_ATTR_USER_APP_NAME;
     }
 }
Variable Documentation
char* languages[] = { "en", "de", "fr", "pl" } static
Supported languages
Definition at line 112 of file imv_hcd_state.c.
Referenced by METHOD().
imv_lang_string_t reasons[] static
Initial value:
= {
    { "en", "Mandatory HCD attributes are missing" },
    { "de", "Obligatorische HCD Attribute fehlen" },
    { "fr", "Il manque des attributes HCD obligatoires" },
    { "pl", "Brakuje atrybutw obowizkowych" },
    { NULL, NULL }
}
Reason strings for "Port Filter"
Definition at line 117 of file imv_hcd_state.c.
Referenced by METHOD().