strongSwan: proposal_keywords_t Struct Reference
proposal_keywords_t Struct Reference
proposal_keywords
#include "proposal_keywords.h"
Public Attributes
const proposal_token_t *(* get_token)(proposal_keywords_t *this, const char *str)
void(* register_token)(proposal_keywords_t *this, const char *name, transform_type_t type, u_int16_t algorithm, u_int16_t keysize)
void(* register_algname_parser)(proposal_keywords_t *this, proposal_algname_parser_t parser)
void(* destroy)(proposal_keywords_t *this)
Detailed Description
Class to manage proposal keywords
Definition at line 83 of file proposal_keywords.h.
Member Data Documentation
void(* proposal_keywords_t::destroy)(proposal_keywords_t *this)
Destroy a proposal_keywords_t instance.
Definition at line 120 of file proposal_keywords.h.
const proposal_token_t*(* proposal_keywords_t::get_token)(proposal_keywords_t *this, const char *str)
Returns the proposal token for the specified string if a token exists.
Parameters
str the string containing the name of the token
Returns
proposal_token if found, NULL otherwise
Definition at line 91 of file proposal_keywords.h.
Referenced by add_string_algo(), attack_transform(), load_proposals(), and main().
void(* proposal_keywords_t::register_algname_parser)(proposal_keywords_t *this, proposal_algname_parser_t parser)
Register an algorithm name parser.
It is meant to parse an algorithm name into a proposal token in a generic, user defined way.
Parameters
parser a pointer to the parser function
Definition at line 114 of file proposal_keywords.h.
void(* proposal_keywords_t::register_token)(proposal_keywords_t *this, const char *name, transform_type_t type, u_int16_t algorithm, u_int16_t keysize)
Register a new proposal token for an algorithm.
Parameters
name the string containing the name of the token
type the transform_type_t for the token
algorithm the IKE id of the algorithm
keysize the key size associated with the specific algorithm
Definition at line 102 of file proposal_keywords.h.
The documentation for this struct was generated from the following file:
proposal_keywords.h