strongSwan: led_listener
led_listener
led
Classes
struct led_listener_t
Typedefs
typedef struct led_listener_t led_listener_t
Functions
led_listener_t * led_listener_create ()
Detailed Description
Typedef Documentation
typedef struct led_listener_t led_listener_t
Definition at line 26 of file led_listener.h.
Function Documentation
led_listener_t* led_listener_create ()
Create a led_listener instance.
See header
Definition at line 219 of file led_listener.c.
References settings_t::get_int, settings_t::get_str, INIT, lib, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, open_led(), set_led(), and library_t::settings.
Referenced by led_plugin_create().
 {
     private_led_listener_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .ike_state_change = _ike_state_change,
                 .message = _message_hook,
             },
             .destroy = _destroy,
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .blink_time = lib->settings->get_int(lib->settings,
                                 "%s.plugins.led.blink_time", 50, lib->ns),
     );
     this->activity = open_led(lib->settings->get_str(lib->settings,
                                 "%s.plugins.led.activity_led", NULL, lib->ns),
                                 &this->activity_max);
     set_led(this->activity, 0);
     return &this->public;
 }