strongSwan: test_linked_list_enumerator.c File Reference
test_linked_list_enumerator.c File Reference
#include "test_suite.h"
#include <collections/linked_list.h>
Functions
START_SETUP (setup_list)
END_SETUP START_TEARDOWN (teardown_list)
END_TEARDOWN START_TEST (test_enumerate)
END_TEST START_TEST (test_enumerate_null)
END_TEST START_TEST (test_reset_enumerator)
END_TEST START_TEST (test_insert_before)
END_TEST START_TEST (test_insert_before_ends)
END_TEST START_TEST (test_insert_before_empty)
END_TEST START_TEST (test_remove_at)
END_TEST START_TEST (test_remove_at_ends)
END_TEST START_TEST (test_insert_before_remove_at)
END_TEST START_TEST (test_create_from_enumerator)
END_TEST Suite * linked_list_enumerator_suite_create ()
Variables
static linked_list_t * list
Function Documentation
END_TEST Suite* linked_list_enumerator_suite_create ()
Definition at line 327 of file test_linked_list_enumerator.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_checked_fixture, tcase_add_loop_test, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("linked list and enumerators");
     tc = tcase_create("enumerate");
     tcase_add_checked_fixture(tc, setup_list, teardown_list);
     tcase_add_test(tc, test_enumerate);
     tcase_add_test(tc, test_enumerate_null);
     tcase_add_test(tc, test_reset_enumerator);
     suite_add_tcase(s, tc);
     tc = tcase_create("insert_before()");
     tcase_add_checked_fixture(tc, setup_list, teardown_list);
     tcase_add_loop_test(tc, test_insert_before, 1, 5);
     tcase_add_test(tc, test_insert_before_ends);
     tcase_add_test(tc, test_insert_before_empty);
     suite_add_tcase(s, tc);
     tc = tcase_create("modify");
     tcase_add_checked_fixture(tc, setup_list, teardown_list);
     tcase_add_test(tc, test_remove_at);
     tcase_add_test(tc, test_remove_at_ends);
     tcase_add_test(tc, test_insert_before_remove_at);
     suite_add_tcase(s, tc);
     tc = tcase_create("create_from_enumerator");
     tcase_add_checked_fixture(tc, setup_list, teardown_list);
     tcase_add_test(tc, test_create_from_enumerator);
     suite_add_tcase(s, tc);
     return s;
 }
START_SETUP (setup_list)
Definition at line 26 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, linked_list_t::get_count, and linked_list_create_with_items().
 {
     list = linked_list_create_with_items((void*)1, (void*)2, (void*)3, (void*)4,
                                      (void*)5, NULL);
     ck_assert_int_eq(list->get_count(list), 5);
 }
END_SETUP START_TEARDOWN (teardown_list)
Definition at line 34 of file test_linked_list_enumerator.c.
References linked_list_t::destroy.
 {
     list->destroy(list);
 }
END_TEARDOWN START_TEST (test_enumerate)
Definition at line 44 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, and enumerator_t::enumerate.
 {
     enumerator_t *enumerator;
     intptr_t x;
     int round;
     round = 1;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         round++;
     }
     ck_assert_int_eq(round, 6);
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_enumerate_null)
Definition at line 62 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, and enumerator_t::enumerate.
 {
     enumerator_t *enumerator;
     int round;
     round = 1;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, NULL))
     {
         round++;
     }
     ck_assert_int_eq(round, 6);
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_reset_enumerator)
Definition at line 78 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, and linked_list_t::reset_enumerator.
 {
     enumerator_t *enumerator;
     intptr_t x;
     int round;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &x))
     {
     }
     list->reset_enumerator(list, enumerator);
     round = 1;
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         round++;
     }
     ck_assert_int_eq(round, 6);
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_insert_before)
Definition at line 104 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, linked_list_t::insert_before, and linked_list_t::reset_enumerator.
 {
     enumerator_t *enumerator;
     intptr_t x;
     int round;
     round = 1;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         round++;
         if (x == _i)
         {
             list->insert_before(list, enumerator, (void*)6);
         }
     }
     ck_assert_int_eq(list->get_count(list), 6);
     list->reset_enumerator(list, enumerator);
     round = 1;
     while (enumerator->enumerate(enumerator, &x))
     {
         if (round == _i && x != _i)
         {
             ck_assert_int_eq(6, x);
         }
         else
         {
             ck_assert_int_eq(round, x);
             round++;
         }
     }
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_insert_before_ends)
Definition at line 140 of file test_linked_list_enumerator.c.
References ck_assert, ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, linked_list_t::get_first, linked_list_t::get_last, linked_list_t::insert_before, and SUCCESS.
 {
     enumerator_t *enumerator;
     intptr_t x;
     int round;
     enumerator = list->create_enumerator(list);
     list->insert_before(list, enumerator, (void*)0);
     ck_assert_int_eq(list->get_count(list), 6);
     ck_assert(list->get_first(list, (void*)&x) == SUCCESS);
     ck_assert_int_eq(x, 0);
     round = 0;
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         round++;
     }
     list->insert_before(list, enumerator, (void*)6);
     ck_assert_int_eq(list->get_count(list), 7);
     ck_assert(list->get_last(list, (void*)&x) == SUCCESS);
     ck_assert_int_eq(x, 6);
     ck_assert(!enumerator->enumerate(enumerator, &x));
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_insert_before_empty)
Definition at line 166 of file test_linked_list_enumerator.c.
References ck_assert, ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, linked_list_t::get_first, linked_list_t::get_last, linked_list_t::insert_before, linked_list_create(), and SUCCESS.
 {
     enumerator_t *enumerator;
     intptr_t x;
     list->destroy(list);
     list = linked_list_create();
     enumerator = list->create_enumerator(list);
     list->insert_before(list, enumerator, (void*)1);
     ck_assert_int_eq(list->get_count(list), 1);
     ck_assert(list->get_first(list, (void*)&x) == SUCCESS);
     ck_assert_int_eq(x, 1);
     ck_assert(list->get_last(list, (void*)&x) == SUCCESS);
     ck_assert_int_eq(x, 1);
     ck_assert(enumerator->enumerate(enumerator, &x));
     ck_assert_int_eq(x, 1);
     ck_assert(!enumerator->enumerate(enumerator, NULL));
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_remove_at)
Definition at line 191 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, linked_list_t::remove_at, and linked_list_t::reset_enumerator.
 {
     enumerator_t *enumerator;
     intptr_t x;
     int round;
     round = 1;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         if (round == 2)
         {
             list->remove_at(list, enumerator);
         }
         round++;
     }
     ck_assert_int_eq(list->get_count(list), 4);
     list->reset_enumerator(list, enumerator);
     round = 1;
     while (enumerator->enumerate(enumerator, &x))
     {
         if (round == 2)
         {   /* skip removed item */
             round++;
         }
         ck_assert_int_eq(round, x);
         round++;
     }
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_remove_at_ends)
Definition at line 224 of file test_linked_list_enumerator.c.
References ck_assert, ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, linked_list_t::get_first, linked_list_t::get_last, linked_list_t::remove_at, and SUCCESS.
 {
     enumerator_t *enumerator;
     intptr_t x;
     enumerator = list->create_enumerator(list);
     list->remove_at(list, enumerator);
     ck_assert_int_eq(list->get_count(list), 5);
     ck_assert(list->get_first(list, (void*)&x) == SUCCESS);
     ck_assert_int_eq(x, 1);
     while (enumerator->enumerate(enumerator, &x))
     {
     }
     list->remove_at(list, enumerator);
     ck_assert_int_eq(list->get_count(list), 5);
     ck_assert(list->get_last(list, (void*)&x) == SUCCESS);
     ck_assert_int_eq(x, 5);
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_insert_before_remove_at)
Definition at line 245 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, linked_list_t::insert_before, linked_list_t::remove_at, and linked_list_t::reset_enumerator.
 {
     enumerator_t *enumerator;
     intptr_t x;
     int round;
     round = 1;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &x))
     {
         ck_assert_int_eq(round, x);
         if (round == 2)
         {   /* this replaces the current item, as insert_before does not change
              * the enumerator position */
             list->insert_before(list, enumerator, (void*)42);
             list->remove_at(list, enumerator);
         }
         else if (round == 4)
         {   /* this does not replace the item, as remove_at moves the enumerator
              * position to the previous item */
             list->remove_at(list, enumerator);
             list->insert_before(list, enumerator, (void*)21);
         }
         round++;
     }
     ck_assert_int_eq(list->get_count(list), 5);
     list->reset_enumerator(list, enumerator);
     round = 1;
     while (enumerator->enumerate(enumerator, &x))
     {
         if (round == 2)
         {   /* check replaced item */
             ck_assert_int_eq(42, x);
         }
         else if (round == 3)
         {   /* check misplaced item */
             ck_assert_int_eq(21, x);
         }
         else if (round == 4)
         {   /* check misplaced item */
             ck_assert_int_eq(3, x);
         }
         else
         {
             ck_assert_int_eq(round, x);
         }
         round++;
     }
     enumerator->destroy(enumerator);
 }
END_TEST START_TEST (test_create_from_enumerator)
Definition at line 301 of file test_linked_list_enumerator.c.
References ck_assert_int_eq, count, linked_list_t::create_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, and linked_list_create_from_enumerator().
 {
     enumerator_t *enumerator, *enumerator_other;
     linked_list_t *other;
     intptr_t x, y;
     int count = 0;
     enumerator = list->create_enumerator(list);
     other = linked_list_create_from_enumerator(enumerator);
     ck_assert_int_eq(other->get_count(list), 5);
     enumerator = list->create_enumerator(list);
     enumerator_other = other->create_enumerator(other);
     while (enumerator->enumerate(enumerator, &x) &&
            enumerator_other->enumerate(enumerator_other, &y))
     {
         ck_assert_int_eq(x, y);
         count++;
     }
     ck_assert_int_eq(count, 5);
     enumerator_other->destroy(enumerator_other);
     enumerator->destroy(enumerator);
     other->destroy(other);
 }
Variable Documentation
linked_list_t* list static
Definition at line 24 of file test_linked_list_enumerator.c.