strongSwan: vici_control.c File Reference
vici_control.c File Reference
#include "vici_control.h"
#include "vici_builder.h"
#include <inttypes.h>
#include <daemon.h>
#include <collections/array.h>
Classes
struct private_vici_control_t
struct log_info_t
Typedefs
typedef struct
private_vici_control_t private_vici_control_t
Functions
static bool log_vici (log_info_t *info, debug_t group, level_t level, ike_sa_t *ike_sa, char *text)
static vici_message_t * send_reply (private_vici_control_t *this, char *fmt,...)
static child_cfg_t * get_child_from_peer (peer_cfg_t *peer_cfg, char *name)
static child_cfg_t * find_child_cfg (char *name, peer_cfg_t **out)
CALLBACK (initiate, vici_message_t *, private_vici_control_t *this, char *name, u_int id, vici_message_t *request)
CALLBACK (terminate, vici_message_t *, private_vici_control_t *this, char *name, u_int id, vici_message_t *request)
static u_int32_t find_reqid (child_cfg_t *cfg)
CALLBACK (install, vici_message_t *, private_vici_control_t *this, char *name, u_int id, vici_message_t *request)
CALLBACK (uninstall, vici_message_t *, private_vici_control_t *this, char *name, u_int id, vici_message_t *request)
CALLBACK (reload_settings, vici_message_t *, private_vici_control_t *this, char *name, u_int id, vici_message_t *request)
static void manage_command (private_vici_control_t *this, char *name, vici_command_cb_t cb, bool reg)
static void manage_commands (private_vici_control_t *this, bool reg)
METHOD (vici_control_t, destroy, void, private_vici_control_t *this)
vici_control_t * vici_control_create (vici_dispatcher_t *dispatcher)
Typedef Documentation
typedef struct private_vici_control_t private_vici_control_t
Definition at line 24 of file vici_control.c.
Function Documentation
CALLBACK (initiate , vici_message_t * , private_vici_control_t * this, char * name, u_int id, vici_message_t * request)
Definition at line 159 of file vici_control.c.
References charon, daemon_t::controller, DBG1, DBG_CFG, log_info_t::dispatcher, FAILED, FALSE, find_child_cfg(), vici_message_t::get_bool, vici_message_t::get_int, vici_message_t::get_str, id, controller_t::initiate, INVALID_STATE, log_info_t::level, limits, log_vici(), OUT_OF_RES, send_reply(), and SUCCESS.
 {
     child_cfg_t *child_cfg = NULL;
     peer_cfg_t *peer_cfg;
     char *child;
     u_int timeout;
     bool limits;
     log_info_t log = {
         .dispatcher = this->dispatcher,
         .id = id,
     };
     child = request->get_str(request, NULL, "child");
     timeout = request->get_int(request, 0, "timeout");
     limits = request->get_bool(request, FALSE, "init-limits");
     log.level = request->get_int(request, 1, "loglevel");
     if (!child)
     {
         return send_reply(this, "missing configuration name");
     }
     DBG1(DBG_CFG, "vici initiate '%s'", child);
     child_cfg = find_child_cfg(child, &peer_cfg);
     if (!child_cfg)
     {
         return send_reply(this, "CHILD_SA config '%s' not found", child);
     }
     switch (charon->controller->initiate(charon->controller, peer_cfg,
                 child_cfg, (controller_cb_t)log_vici, &log, timeout, limits))
     {
         case SUCCESS:
             return send_reply(this, NULL);
         case OUT_OF_RES:
             return send_reply(this, "CHILD_SA '%s' not established after %dms",
                               child, timeout);
         case INVALID_STATE:
             return send_reply(this, "establishing CHILD_SA '%s' not possible "
                               "at the moment due to limits", child);
         case FAILED:
         default:
             return send_reply(this, "establishing CHILD_SA '%s' failed", child);
     }
 }
CALLBACK (terminate , vici_message_t * , private_vici_control_t * this, char * name, u_int id, vici_message_t * request)
Definition at line 206 of file vici_control.c.
References vici_builder_t::add_kv, array_count(), array_create(), array_create_enumerator(), array_destroy(), array_insert(), ARRAY_TAIL, charon, daemon_t::controller, ike_sa_t::create_child_sa_enumerator, controller_t::create_ike_sa_enumerator, DBG1, DBG_CFG, del(), enumerator_t::destroy, log_info_t::dispatcher, enumerator_t::enumerate, vici_builder_t::finalize, vici_message_t::get_int, child_sa_t::get_name, ike_sa_t::get_name, vici_message_t::get_str, child_sa_t::get_unique_id, ike_sa_t::get_unique_id, id, log_info_t::level, log_vici(), send_reply(), streq(), SUCCESS, controller_t::terminate_child, controller_t::terminate_ike, TRUE, and vici_builder_create().
 {
     enumerator_t *enumerator, *isas, *csas;
     char *child, *ike, *errmsg = NULL;
     u_int timeout, child_id, ike_id, current, *del, done = 0;
     ike_sa_t *ike_sa;
     child_sa_t *child_sa;
     array_t *ids;
     vici_builder_t *builder;
     log_info_t log = {
         .dispatcher = this->dispatcher,
         .id = id,
     };
     child = request->get_str(request, NULL, "child");
     ike = request->get_str(request, NULL, "ike");
     child_id = request->get_int(request, 0, "child-id");
     ike_id = request->get_int(request, 0, "ike-id");
     timeout = request->get_int(request, 0, "timeout");
     log.level = request->get_int(request, 1, "loglevel");
     if (!child && !ike && !ike_id && !child_id)
     {
         return send_reply(this, "missing terminate selector");
     }
     if (ike_id)
     {
         DBG1(DBG_CFG, "vici terminate IKE_SA #%d", ike_id);
     }
     if (child_id)
     {
         DBG1(DBG_CFG, "vici terminate CHILD_SA #%d", child_id);
     }
     if (ike)
     {
         DBG1(DBG_CFG, "vici terminate IKE_SA '%s'", ike);
     }
     if (child)
     {
         DBG1(DBG_CFG, "vici terminate CHILD_SA '%s'", child);
     }
     ids = array_create(sizeof(u_int), 0);
     isas = charon->controller->create_ike_sa_enumerator(charon->controller, TRUE);
     while (isas->enumerate(isas, &ike_sa))
     {
         if (child || child_id)
         {
             if (ike && !streq(ike, ike_sa->get_name(ike_sa)))
             {
                 continue;
             }
             if (ike_id && ike_id != ike_sa->get_unique_id(ike_sa))
             {
                 continue;
             }
             csas = ike_sa->create_child_sa_enumerator(ike_sa);
             while (csas->enumerate(csas, &child_sa))
             {
                 if (child && !streq(child, child_sa->get_name(child_sa)))
                 {
                     continue;
                 }
                 if (child_id && child_sa->get_unique_id(child_sa) != child_id)
                 {
                     continue;
                 }
                 current = child_sa->get_unique_id(child_sa);
                 array_insert(ids, ARRAY_TAIL, &current);
             }
             csas->destroy(csas);
         }
         else if (ike && streq(ike, ike_sa->get_name(ike_sa)))
         {
             current = ike_sa->get_unique_id(ike_sa);
             array_insert(ids, ARRAY_TAIL, &current);
         }
         else if (ike_id && ike_id == ike_sa->get_unique_id(ike_sa))
         {
             array_insert(ids, ARRAY_TAIL, &ike_id);
         }
     }
     isas->destroy(isas);
     enumerator = array_create_enumerator(ids);
     while (enumerator->enumerate(enumerator, &del))
     {
         if (child || child_id)
         {
             if (charon->controller->terminate_child(charon->controller, *del,
                         (controller_cb_t)log_vici, &log, timeout) == SUCCESS)
             {
                 done++;
             }
         }
         else
         {
             if (charon->controller->terminate_ike(charon->controller, *del,
                         (controller_cb_t)log_vici, &log, timeout) == SUCCESS)
             {
                 done++;
             }
         }
     }
     enumerator->destroy(enumerator);
     builder = vici_builder_create();
     if (array_count(ids) == 0)
     {
         errmsg = "no matching SAs to terminate found";
     }
     else if (done < array_count(ids))
     {
         if (array_count(ids) == 1)
         {
             errmsg = "terminating SA failed";
         }
         else
         {
             errmsg = "not all matching SAs could be terminated";
         }
     }
     builder->add_kv(builder, "success", errmsg ? "no" : "yes");
     builder->add_kv(builder, "matches", "%u", array_count(ids));
     builder->add_kv(builder, "terminated", "%u", done);
     if (errmsg)
     {
         builder->add_kv(builder, "errmsg", "%s", errmsg);
     }
     array_destroy(ids);
     return builder->finalize(builder);
 }
CALLBACK (install , vici_message_t * , private_vici_control_t * this, char * name, u_int id, vici_message_t * request)
Definition at line 377 of file vici_control.c.
References charon, DBG1, DBG_CFG, child_cfg_t::destroy, peer_cfg_t::destroy, find_child_cfg(), find_reqid(), child_cfg_t::get_mode, vici_message_t::get_str, shunt_manager_t::install, trap_manager_t::install, MODE_DROP, MODE_PASS, ok, send_reply(), daemon_t::shunts, and daemon_t::traps.
 {
     child_cfg_t *child_cfg = NULL;
     peer_cfg_t *peer_cfg;
     char *child;
     bool ok;
     child = request->get_str(request, NULL, "child");
     if (!child)
     {
         return send_reply(this, "missing configuration name");
     }
     DBG1(DBG_CFG, "vici install '%s'", child);
     child_cfg = find_child_cfg(child, &peer_cfg);
     if (!child_cfg)
     {
         return send_reply(this, "configuration name not found");
     }
     switch (child_cfg->get_mode(child_cfg))
     {
         case MODE_PASS:
         case MODE_DROP:
             ok = charon->shunts->install(charon->shunts, child_cfg);
             break;
         default:
             ok = charon->traps->install(charon->traps, peer_cfg, child_cfg,
                                         find_reqid(child_cfg));
             break;
     }
     peer_cfg->destroy(peer_cfg);
     child_cfg->destroy(child_cfg);
     return send_reply(this, ok ? NULL : "installing policy '%s' failed", child);
 }
CALLBACK (uninstall , vici_message_t * , private_vici_control_t * this, char * name, u_int id, vici_message_t * request)
Definition at line 415 of file vici_control.c.
References charon, trap_manager_t::create_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, child_sa_t::get_name, child_sa_t::get_reqid, vici_message_t::get_str, send_reply(), daemon_t::shunts, streq(), daemon_t::traps, shunt_manager_t::uninstall, and trap_manager_t::uninstall.
 {
     child_sa_t *child_sa;
     enumerator_t *enumerator;
     u_int32_t reqid = 0;
     char *child;
     child = request->get_str(request, NULL, "child");
     if (!child)
     {
         return send_reply(this, "missing configuration name");
     }
     DBG1(DBG_CFG, "vici uninstall '%s'", child);
     if (charon->shunts->uninstall(charon->shunts, child))
     {
         return send_reply(this, NULL);
     }
     enumerator = charon->traps->create_enumerator(charon->traps);
     while (enumerator->enumerate(enumerator, NULL, &child_sa))
     {
         if (streq(child, child_sa->get_name(child_sa)))
         {
             reqid = child_sa->get_reqid(child_sa);
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (reqid)
     {
         if (charon->traps->uninstall(charon->traps, reqid))
         {
             return send_reply(this, NULL);
         }
         return send_reply(this, "uninstalling policy '%s' failed", child);
     }
     return send_reply(this, "policy '%s' not found", child);
 }
CALLBACK (reload_settings , vici_message_t * , private_vici_control_t * this, char * name, u_int id, vici_message_t * request)
Definition at line 458 of file vici_control.c.
References library_t::conf, FALSE, lib, settings_t::load_files, library_t::plugins, plugin_loader_t::reload, send_reply(), and library_t::settings.
 {
     if (lib->settings->load_files(lib->settings, lib->conf, FALSE))
     {
         lib->plugins->reload(lib->plugins, NULL);
         return send_reply(this, NULL);
     }
     return send_reply(this, "reloading '%s' failed", lib->conf);
 }
static child_cfg_t* find_child_cfg (char * name, peer_cfg_t ** out) static
Find a peer/child config from a child config name
Definition at line 137 of file vici_control.c.
References daemon_t::backends, charon, backend_manager_t::create_peer_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, get_child_from_peer(), peer_cfg_t::get_ref, and IKE_ANY.
Referenced by CALLBACK().
 {
     enumerator_t *enumerator;
     peer_cfg_t *peer_cfg;
     child_cfg_t *child_cfg = NULL;
     enumerator = charon->backends->create_peer_cfg_enumerator(
                             charon->backends, NULL, NULL, NULL, NULL, IKE_ANY);
     while (enumerator->enumerate(enumerator, &peer_cfg))
     {
         child_cfg = get_child_from_peer(peer_cfg, name);
         if (child_cfg)
         {
             *out = peer_cfg->get_ref(peer_cfg);
             break;
         }
     }
     enumerator->destroy(enumerator);
     return child_cfg;
 }
static u_int32_t find_reqid (child_cfg_t * cfg) static
Find reqid of an existing CHILD_SA
Definition at line 345 of file vici_control.c.
References charon, daemon_t::controller, ike_sa_t::create_child_sa_enumerator, controller_t::create_ike_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, trap_manager_t::find_reqid, child_cfg_t::get_name, child_sa_t::get_name, child_sa_t::get_reqid, streq(), daemon_t::traps, and TRUE.
Referenced by CALLBACK().
 {
     enumerator_t *enumerator, *children;
     child_sa_t *child_sa;
     ike_sa_t *ike_sa;
     u_int32_t reqid;
     reqid = charon->traps->find_reqid(charon->traps, cfg);
     if (reqid)
     {   /* already trapped */
         return reqid;
     }
     enumerator = charon->controller->create_ike_sa_enumerator(
                                                     charon->controller, TRUE);
     while (!reqid && enumerator->enumerate(enumerator, &ike_sa))
     {
         children = ike_sa->create_child_sa_enumerator(ike_sa);
         while (children->enumerate(children, &child_sa))
         {
             if (streq(cfg->get_name(cfg), child_sa->get_name(child_sa)))
             {
                 reqid = child_sa->get_reqid(child_sa);
                 break;
             }
         }
         children->destroy(children);
     }
     enumerator->destroy(enumerator);
     return reqid;
 }
static child_cfg_t* get_child_from_peer (peer_cfg_t * peer_cfg, char * name) static
Get the child_cfg having name from peer_cfg
Definition at line 115 of file vici_control.c.
References peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, child_cfg_t::get_name, child_cfg_t::get_ref, name, and streq().
Referenced by find_child_cfg().
 {
     child_cfg_t *current, *found = NULL;
     enumerator_t *enumerator;
     enumerator = peer_cfg->create_child_cfg_enumerator(peer_cfg);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (streq(current->get_name(current), name))
         {
             found = current;
             found->get_ref(found);
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static bool log_vici (log_info_t * info, debug_t group, level_t level, ike_sa_t * ike_sa, char * text) static
Log using vici event messages
Definition at line 59 of file vici_control.c.
References vici_builder_t::add_kv, debug_names, log_info_t::dispatcher, vici_builder_t::finalize, ike_sa_t::get_name, ike_sa_t::get_unique_id, log_info_t::id, vici_dispatcher_t::raise_event, log_info_t::recursive, TRUE, and vici_builder_create().
Referenced by CALLBACK().
 {
     if (level <= info->level)
     {
         if (info->recursive++ == 0)
         {
             vici_message_t *message;
             vici_builder_t *builder;
             builder = vici_builder_create();
             builder->add_kv(builder, "group", "%N", debug_names, group);
             builder->add_kv(builder, "level", "%d", level);
             if (ike_sa)
             {
                 builder->add_kv(builder, "ikesa-name", "%s",
                                 ike_sa->get_name(ike_sa));
                 builder->add_kv(builder, "ikesa-uniqueid", "%u",
                                 ike_sa->get_unique_id(ike_sa));
             }
             builder->add_kv(builder, "msg", "%s", text);
             message = builder->finalize(builder);
             if (message)
             {
                 info->dispatcher->raise_event(info->dispatcher, "control-log",
                                               info->id, message);
             }
         }
         info->recursive--;
     }
     return TRUE;
 }
static void manage_command (private_vici_control_t * this, char * name, vici_command_cb_t cb, bool reg) static
Definition at line 469 of file vici_control.c.
Referenced by manage_commands().
 {
     this->dispatcher->manage_command(this->dispatcher, name,
                                      reg ? cb : NULL, this);
 }
static void manage_commands (private_vici_control_t * this, bool reg) static
(Un-)register dispatcher functions
Definition at line 479 of file vici_control.c.
References initiate(), install(), manage_command(), reload_settings(), terminate(), and uninstall().
Referenced by METHOD(), and vici_control_create().
 {
     manage_command(this, "initiate", initiate, reg);
     manage_command(this, "terminate", terminate, reg);
     manage_command(this, "install", install, reg);
     manage_command(this, "uninstall", uninstall, reg);
     manage_command(this, "reload-settings", reload_settings, reg);
     this->dispatcher->manage_event(this->dispatcher, "control-log", reg);
 }
METHOD (vici_control_t , destroy , void , private_vici_control_t * this)
Definition at line 489 of file vici_control.c.
References FALSE, free(), and manage_commands().
 {
     manage_commands(this, FALSE);
     free(this);
 }
static vici_message_t* send_reply (private_vici_control_t * this, char * fmt, ...) static
Send a (error) reply message
Definition at line 96 of file vici_control.c.
References vici_builder_t::add_kv, vici_builder_t::finalize, vici_builder_t::vadd_kv, and vici_builder_create().
Referenced by CALLBACK().
 {
     vici_builder_t *builder;
     va_list args;
     builder = vici_builder_create();
     builder->add_kv(builder, "success", fmt ? "no" : "yes");
     if (fmt)
     {
         va_start(args, fmt);
         builder->vadd_kv(builder, "errmsg", fmt, args);
         va_end(args);
     }
     return builder->finalize(builder);
 }