strongSwan: eap_simaka_sql_card
eap_simaka_sql_card
eap_simaka_sql
Classes
struct eap_simaka_sql_card_t
Typedefs
typedef struct
eap_simaka_sql_card_t eap_simaka_sql_card_t
Functions
eap_simaka_sql_card_t * eap_simaka_sql_card_create (database_t *db, bool remove_used)
Detailed Description
Typedef Documentation
typedef struct eap_simaka_sql_card_t eap_simaka_sql_card_t
Definition at line 27 of file eap_simaka_sql_card.h.
Function Documentation
eap_simaka_sql_card_t* eap_simaka_sql_card_create (database_t * db, bool remove_used)
Create a eap_simaka_sql_card instance.
Parameters
db triplet/quintuplet database
remove_used TRUE to remove used triplets/quintuplets from db
See header
Definition at line 154 of file eap_simaka_sql_card.c.
References destroy(), INIT, nop(), return_false(), and return_null().
Referenced by load_db().
 {
     private_eap_simaka_sql_card_t *this;
     INIT(this,
         .public = {
             .card = {
                 .get_triplet = _get_triplet,
                 .get_quintuplet = _get_quintuplet,
                 .resync = (void*)return_false,
                 .get_pseudonym = (void*)return_null,
                 .set_pseudonym = (void*)nop,
                 .get_reauth = (void*)return_null,
                 .set_reauth = (void*)nop,
             },
             .destroy = _destroy,
         },
         .db = db,
         .remove_used = remove_used,
     );
     return &this->public;
 }