strongSwan: tnc_pdp.c File Reference
tnc_pdp.c File Reference
#include "tnc_pdp.h"
#include "tnc_pdp_connections.h"
#include <errno.h>
#include <unistd.h>
#include <time.h>
#include <radius_message.h>
#include <radius_mppe.h>
#include <pt_tls_server.h>
#include <tnc/tnc.h>
#include <tncifimv.h>
#include <tncif_names.h>
#include <daemon.h>
#include <utils/debug.h>
#include <pen/pen.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
#include <sa/eap/eap_method.h>
Classes
struct private_tnc_pdp_t
struct client_entry_t
Macros
#define RADIUS_PORT 1812
#define MAX_PACKET 4096
#define RADIUS_RETRANSMIT_TIMEOUT 30 /* seconds */
Typedefs
typedef struct private_tnc_pdp_t private_tnc_pdp_t
typedef struct client_entry_t client_entry_t
Functions
static void free_client_entry (client_entry_t *this)
static int open_udp_socket (int family, u_int16_t port)
static int open_tcp_socket (int family, u_int16_t port)
static void send_message (private_tnc_pdp_t *this, radius_message_t *message, host_t *client)
static chunk_t encrypt_mppe_key (private_tnc_pdp_t *this, u_int8_t type, chunk_t key, u_int16_t *salt, radius_message_t *request)
static void send_response (private_tnc_pdp_t *this, radius_message_t *request, radius_message_code_t code, eap_payload_t *eap, identification_t *group, chunk_t msk, host_t *client)
static void process_eap (private_tnc_pdp_t *this, radius_message_t *request, host_t *source)
static bool get_recommendation (TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
static bool pt_tls_receive_more (pt_tls_server_t *this, int fd, watcher_event_t event)
static bool pt_tls_receive (private_tnc_pdp_t *this, int fd, watcher_event_t event)
static bool radius_receive (private_tnc_pdp_t *this, int fd, watcher_event_t event)
METHOD (tnc_pdp_t, destroy, void, private_tnc_pdp_t *this)
tnc_pdp_t * tnc_pdp_create (void)
Macro Definition Documentation
#define MAX_PACKET 4096
Maximum size of a RADIUS IP packet
Definition at line 50 of file tnc_pdp.c.
Referenced by radius_receive().
#define RADIUS_PORT 1812
Default RADIUS port, when not configured
Definition at line 45 of file tnc_pdp.c.
Referenced by tnc_pdp_create().
#define RADIUS_RETRANSMIT_TIMEOUT 30 /* seconds */
Definition at line 52 of file tnc_pdp.c.
Referenced by radius_receive().
Typedef Documentation
typedef struct client_entry_t client_entry_t
Definition at line 41 of file tnc_pdp.c.
typedef struct private_tnc_pdp_t private_tnc_pdp_t
Definition at line 40 of file tnc_pdp.c.
Function Documentation
static chunk_t encrypt_mppe_key (private_tnc_pdp_t * this, u_int8_t type, chunk_t key, u_int16_t * salt, radius_message_t * request) static
Encrypt a MS-MPPE-Send/Recv-Key
From RFC2548 (encryption): b(1) = MD5(S + R + A) c(1) = p(1) xor b(1) C = c(1) b(2) = MD5(S + c(1)) c(2) = p(2) xor b(2) C = C + c(2) . . . b(i) = MD5(S + c(i-1)) c(i) = p(i) xor b(i) C = C + c(i)
generate a 16 bit unique random salt value for the MPPE stream cipher the MSB of the salt MUST be set to 1
Definition at line 342 of file tnc_pdp.c.
References a, b, c, chunk_alloc, chunk_cata, chunk_create(), chunk_empty, data, free(), radius_message_t::get_authenticator, HASH_SIZE_MD5, hasher, mppe_key_t::id, mppe_key_t::key, chunk_t::len, mppe_key_t::length, memcpy, memset, memxor(), PEN_MICROSOFT, chunk_t::ptr, r, mppe_key_t::salt, mppe_key_t::type, and type.
Referenced by send_response().
 {
     chunk_t a, r, seed, data;
     u_char b[HASH_SIZE_MD5], *c;
     mppe_key_t *mppe_key;
     data = chunk_alloc(sizeof(mppe_key_t) +
                        HASH_SIZE_MD5 * (1 + key.len / HASH_SIZE_MD5));
     memset(data.ptr, 0x00, data.len);
     mppe_key = (mppe_key_t*)data.ptr;
     mppe_key->id = htonl(PEN_MICROSOFT);
     mppe_key->type = type;
     mppe_key->length = data.len - sizeof(mppe_key->id);
     mppe_key->key[0] = key.len;
     memcpy(&mppe_key->key[1], key.ptr, key.len);
     a = chunk_create((u_char*)&(mppe_key->salt), sizeof(mppe_key->salt));
     do
     {
         if (!this->ng->get_nonce(this->ng, a.len, a.ptr))
         {
             free(data.ptr);
             return chunk_empty;
         }
         *a.ptr |= 0x80;
     }
     while (mppe_key->salt == *salt);
     /* update the salt value */
     *salt = mppe_key->salt;
     r = chunk_create(request->get_authenticator(request), HASH_SIZE_MD5);
     seed = chunk_cata("cc", r, a);
     c = mppe_key->key;
     while (c < data.ptr + data.len)
     {
         /* b(i) = MD5(S + c(i-1)) */
         if (!this->hasher->get_hash(this->hasher, this->secret, NULL) ||
             !this->hasher->get_hash(this->hasher, seed, b))
         {
             free(data.ptr);
             return chunk_empty;
         }
         /* c(i) = b(i) xor p(1) */
         memxor(c, b, HASH_SIZE_MD5);
         /* prepare next round */
         seed = chunk_create(c, HASH_SIZE_MD5);
         c += HASH_SIZE_MD5;
     }
     return data;
 }
static void free_client_entry (client_entry_t * this) static
Definition at line 152 of file tnc_pdp.c.
References free(), and host.
Referenced by METHOD(), and radius_receive().
 {
     this->host->destroy(this->host);
     free(this);
 }
static bool get_recommendation (TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval) static
Callback function to get recommendation from TNCCS connection
Definition at line 611 of file tnc_pdp.c.
References DBG1, DBG_TNC, TNC_IMV_Action_Recommendation_names, TNC_IMV_Evaluation_Result_names, and TRUE.
Referenced by pt_tls_receive().
 {
     DBG1(DBG_TNC, "final recommendation is '%N' and evaluation is '%N'",
          TNC_IMV_Action_Recommendation_names, rec,
          TNC_IMV_Evaluation_Result_names, eval);
     return TRUE;
 }
METHOD (tnc_pdp_t , destroy , void , private_tnc_pdp_t * this)
Definition at line 806 of file tnc_pdp.c.
References close, DESTROY_IF, free(), free_client_entry(), hasher, lib, watcher_t::remove, server, signer, and library_t::watcher.
 {
     if (this->pt_tls_ipv4)
     {
         lib->watcher->remove(lib->watcher, this->pt_tls_ipv4);
         close(this->pt_tls_ipv4);
     }
     if (this->pt_tls_ipv6)
     {
         lib->watcher->remove(lib->watcher, this->pt_tls_ipv6);
         close(this->pt_tls_ipv6);
     }
     if (this->radius_ipv4)
     {
         lib->watcher->remove(lib->watcher, this->radius_ipv4);
         close(this->radius_ipv4);
     }
     if (this->radius_ipv6)
     {
         lib->watcher->remove(lib->watcher, this->radius_ipv6);
         close(this->radius_ipv6);
     }
     if (this->clients)
     {
         this->clients->destroy_function(this->clients, (void*)free_client_entry);
     }
     DESTROY_IF(this->server);
     DESTROY_IF(this->signer);
     DESTROY_IF(this->hasher);
     DESTROY_IF(this->ng);
     DESTROY_IF(this->connections);
     free(this);
 }
static int open_tcp_socket (int family, u_int16_t port) static
Open IPv4 or IPv6 TCP socket
Definition at line 236 of file tnc_pdp.c.
References bind, close, DBG1, DBG_CFG, DBG_TNC, family, htoun16(), htoun32(), in6addr_any, IPPROTO_IPV6, IPV6_V6ONLY, memcpy, memset, setsockopt, socket, strerror, and TRUE.
Referenced by tnc_pdp_create().
 {
     int on = TRUE;
     struct sockaddr_storage addr;
     socklen_t addrlen;
     int skt;
     memset(&addr, 0, sizeof(addr));
     addr.ss_family = family;
     /* precalculate constants depending on address family */
     switch (family)
     {
         case AF_INET:
         {
             struct sockaddr_in *sin = (struct sockaddr_in *)&addr;
             htoun32(&sin->sin_addr.s_addr, INADDR_ANY);
             htoun16(&sin->sin_port, port);
             addrlen = sizeof(struct sockaddr_in);
             break;
         }
         case AF_INET6:
         {
             struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)&addr;
             memcpy(&sin6->sin6_addr, &in6addr_any, sizeof(in6addr_any));
             htoun16(&sin6->sin6_port, port);
             addrlen = sizeof(struct sockaddr_in6);
             break;
         }
         default:
             return 0;
     }
     /* open the socket */
     skt = socket(family, SOCK_STREAM, IPPROTO_TCP);
     if (skt < 0)
     {
         DBG1(DBG_CFG, "opening TCP socket failed: %s", strerror(errno));
         return 0;
     }
     if (setsockopt(skt, SOL_SOCKET, SO_REUSEADDR, (void*)&on, sizeof(on)) < 0)
     {
         DBG1(DBG_CFG, "unable to set SO_REUSEADDR on socket: %s",
                        strerror(errno));
         close(skt);
         return 0;
     }
     if (family == AF_INET6)
     {
     if (setsockopt(skt, IPPROTO_IPV6, IPV6_V6ONLY,
                             (void *)&on, sizeof(on)) < 0)
         {
             DBG1(DBG_CFG, "unable to set IPV6_V6ONLY on socket: %s",
                            strerror(errno));
             close(skt);
             return 0;
         }
     }
     /* bind the socket */
     if (bind(skt, (struct sockaddr *)&addr, addrlen) < 0)
     {
         DBG1(DBG_CFG, "unable to bind TCP socket: %s", strerror(errno));
         close(skt);
         return 0;
     }
     /* start listening on socket */
     if (listen(skt, 5) == -1)
     {
         DBG1(DBG_TNC, "listen on TCP socket failed: %s", strerror(errno));
         close(skt);
         return 0;
     }
     return skt;
 }
static int open_udp_socket (int family, u_int16_t port) static
Open IPv4 or IPv6 UDP socket
Definition at line 161 of file tnc_pdp.c.
References bind, close, DBG1, DBG_CFG, family, htoun16(), htoun32(), in6addr_any, IPPROTO_IPV6, IPV6_V6ONLY, memcpy, memset, setsockopt, socket, strerror, and TRUE.
Referenced by tnc_pdp_create().
 {
     int on = TRUE;
     struct sockaddr_storage addr;
     socklen_t addrlen;
     int skt;
     memset(&addr, 0, sizeof(addr));
     addr.ss_family = family;
     /* precalculate constants depending on address family */
     switch (family)
     {
         case AF_INET:
         {
             struct sockaddr_in *sin = (struct sockaddr_in *)&addr;
             htoun32(&sin->sin_addr.s_addr, INADDR_ANY);
             htoun16(&sin->sin_port, port);
             addrlen = sizeof(struct sockaddr_in);
             break;
         }
         case AF_INET6:
         {
             struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)&addr;
             memcpy(&sin6->sin6_addr, &in6addr_any, sizeof(in6addr_any));
             htoun16(&sin6->sin6_port, port);
             addrlen = sizeof(struct sockaddr_in6);
             break;
         }
         default:
             return 0;
     }
     /* open the socket */
     skt = socket(family, SOCK_DGRAM, IPPROTO_UDP);
     if (skt < 0)
     {
         DBG1(DBG_CFG, "opening UDP socket failed: %s", strerror(errno));
         return 0;
     }
     if (setsockopt(skt, SOL_SOCKET, SO_REUSEADDR, (void*)&on, sizeof(on)) < 0)
     {
         DBG1(DBG_CFG, "unable to set SO_REUSEADDR on socket: %s",
                        strerror(errno));
         close(skt);
         return 0;
     }
     if (family == AF_INET6)
     {
         if (setsockopt(skt, IPPROTO_IPV6, IPV6_V6ONLY,
                             (void *)&on, sizeof(on)) < 0)
         {
             DBG1(DBG_CFG, "unable to set IPV6_V6ONLY on socket: %s",
                            strerror(errno));
             close(skt);
             return 0;
         }
     }
     /* bind the socket */
     if (bind(skt, (struct sockaddr *)&addr, addrlen) < 0)
     {
         DBG1(DBG_CFG, "unable to bind UDP socket: %s", strerror(errno));
         close(skt);
         return 0;
     }
     return skt;
 }
static void process_eap (private_tnc_pdp_t * this, radius_message_t * request, host_t * source) static
Process EAP message
Definition at line 473 of file tnc_pdp.c.
References AUTH_RULE_GROUP, daemon_t::bus, charon, chunk_cat, chunk_create(), chunk_empty, code, auth_cfg_t::create_enumerator, radius_message_t::create_enumerator, eap_manager_t::create_instance, data, DBG3, DBG_CFG, enumerator_t::destroy, eap_payload_t::destroy, identification_t::destroy, DESTROY_IF, daemon_t::eap, EAP_FAILURE, EAP_IDENTITY, eap_payload_create_code(), eap_payload_create_data(), EAP_SERVER, EAP_SUCCESS, eap_type_names, end, enumerator_t::enumerate, FAILED, FALSE, free(), ike_sa_t::get_auth_cfg, eap_payload_t::get_identifier, eap_method_t::get_msk, eap_payload_t::get_type, group, identification_create_from_data(), in, eap_method_t::initiate, chunk_t::len, NEED_MORE, out, eap_method_t::process, chunk_t::ptr, RAT_EAP_MESSAGE, RAT_NAS_IDENTIFIER, RAT_USER_NAME, RMC_ACCESS_ACCEPT, RMC_ACCESS_CHALLENGE, RMC_ACCESS_REJECT, send_response(), bus_t::set_sa, SUCCESS, and type.
Referenced by radius_receive().
 {
     enumerator_t *enumerator;
     eap_payload_t *in, *out = NULL;
     eap_method_t *method;
     eap_type_t eap_type;
     u_int32_t eap_vendor;
     chunk_t data, message = chunk_empty, msk = chunk_empty;
     chunk_t user_name = chunk_empty, nas_id = chunk_empty;
     identification_t *group = NULL;
     radius_message_code_t code = RMC_ACCESS_CHALLENGE;
     int type;
     enumerator = request->create_enumerator(request);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         switch (type)
         {
             case RAT_USER_NAME:
                 user_name = data;
                 break;
             case RAT_NAS_IDENTIFIER:
                 nas_id = data;
                 break;
             case RAT_EAP_MESSAGE:
                 if (data.len)
                 {
                     message = chunk_cat("mc", message, data);
                 }
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (message.len)
     {
         in = eap_payload_create_data(message);
         /* apply EAP method selected by RADIUS server */
         eap_type = in->get_type(in, &eap_vendor);
         DBG3(DBG_CFG, "%N payload %B", eap_type_names, eap_type, &message);
         if (eap_type == EAP_IDENTITY)
         {
             identification_t *peer;
             chunk_t eap_identity;
             if (message.len < 5)
             {
                 goto end;
             }
             eap_identity = chunk_create(message.ptr + 5, message.len - 5);
             peer = identification_create_from_data(eap_identity);
             method = charon->eap->create_instance(charon->eap, this->type,
                                         0, EAP_SERVER, this->server, peer);
             if (!method)
             {
                 peer->destroy(peer);
                 goto end;
             }
             this->connections->add(this->connections, nas_id, user_name, peer,
                                    method);
             if (method->initiate(method, &out) == NEED_MORE)
             {
                 send_response(this, request, code, out, group, msk, source);
             }
         }
         else
         {
             ike_sa_t *ike_sa;
             auth_cfg_t *auth;
             auth_rule_t type;
             identification_t *data;
             enumerator_t *e;
             method = this->connections->get_state(this->connections, nas_id,
                                                   user_name, &ike_sa);
             if (!method)
             {
                 goto end;
             }
             charon->bus->set_sa(charon->bus, ike_sa);
             switch (method->process(method, in, &out))
             {
                 case NEED_MORE:
                     code = RMC_ACCESS_CHALLENGE;
                     break;
                 case SUCCESS:
                     code = RMC_ACCESS_ACCEPT;
                     method->get_msk(method, &msk);
                     auth = ike_sa->get_auth_cfg(ike_sa, FALSE);
                     e = auth->create_enumerator(auth);
                     while (e->enumerate(e, &type, &data))
                     {
                         /* look for group memberships */
                         if (type == AUTH_RULE_GROUP)
{
                             group = data;
                         }
                     }
                     e->destroy(e);
                     DESTROY_IF(out);
                     out = eap_payload_create_code(EAP_SUCCESS,
                                                   in->get_identifier(in));
                     break;
                 case FAILED:
                 default:
                     code = RMC_ACCESS_REJECT;
                     DESTROY_IF(out);
                     out = eap_payload_create_code(EAP_FAILURE,
                                                   in->get_identifier(in));
             }
             charon->bus->set_sa(charon->bus, NULL);
             send_response(this, request, code, out, group, msk, source);
             this->connections->unlock(this->connections);
         }
         if (code == RMC_ACCESS_ACCEPT || code == RMC_ACCESS_REJECT)
         {
             this->connections->remove(this->connections, nas_id, user_name);
         }
         out->destroy(out);
 end:
         free(message.ptr);
         in->destroy(in);
     }
 }
static bool pt_tls_receive (private_tnc_pdp_t * this, int fd, watcher_event_t event) static
Accept TCP connection received on the PT-TLS listening socket
Definition at line 644 of file tnc_pdp.c.
References accept, watcher_t::add, addr, chunk_empty, close, tnccs_manager_t::create_instance, DBG1, DBG_TNC, host_t::destroy, FALSE, host_t::get_family, get_recommendation(), host_create_any(), host_create_from_sockaddr(), ID_ANY, identification_create_from_encoding(), lib, PT_TLS_AUTH_TLS_OR_SASL, pt_tls_receive_more(), pt_tls_server_create(), server, strerror, tnc, TNC_IFT_TLS_2_0, tnc_t::tnccs, TNCCS_2_0, TRUE, library_t::watcher, and WATCHER_READ.
Referenced by tnc_pdp_create().
 {
     int pt_tls_fd;
     struct sockaddr_storage addr;
     socklen_t addrlen = sizeof(addr);
     identification_t *client_id;
     host_t *server_ip, *client_ip;
     pt_tls_server_t *pt_tls;
     tnccs_t *tnccs;
     pt_tls_auth_t auth = PT_TLS_AUTH_TLS_OR_SASL;
     pt_tls_fd = accept(fd, (sockaddr_t*)&addr, &addrlen);
     if (pt_tls_fd == -1)
     {
         DBG1(DBG_TNC, "accepting PT-TLS stream failed: %s", strerror(errno));
         return FALSE;
     }
     client_ip = host_create_from_sockaddr((sockaddr_t*)&addr);
     DBG1(DBG_TNC, "accepting PT-TLS stream from %H", client_ip);
     /* Currently we do not determine the IP address of the server interface */
     server_ip = host_create_any(client_ip->get_family(client_ip));
     /* At this moment the client identity is not known yet */
     client_id = identification_create_from_encoding(ID_ANY, chunk_empty),
     tnccs = tnc->tnccs->create_instance(tnc->tnccs, TNCCS_2_0, TRUE,
                                         this->server, client_id, server_ip,
                                         client_ip, TNC_IFT_TLS_2_0,
                                         (tnccs_cb_t)get_recommendation);
     client_id->destroy(client_id);
     server_ip->destroy(server_ip);
     client_ip->destroy(client_ip);
     if (!tnccs)
     {
         DBG1(DBG_TNC, "could not create TNCCS 2.0 connection instance");
         close(pt_tls_fd);
         return FALSE;
     }
     pt_tls = pt_tls_server_create(this->server, pt_tls_fd, auth, tnccs);
     if (!pt_tls)
     {
         DBG1(DBG_TNC, "could not create PT-TLS connection instance");
         close(pt_tls_fd);
         return FALSE;
     }
     lib->watcher->add(lib->watcher, pt_tls_fd, WATCHER_READ,
                              (watcher_cb_t)pt_tls_receive_more, pt_tls);
     return TRUE;
 }
static bool pt_tls_receive_more (pt_tls_server_t * this, int fd, watcher_event_t event) static
Get more data on a PT-TLS connection
Definition at line 624 of file tnc_pdp.c.
References close, DBG1, DBG_TNC, destroy(), FAILED, FALSE, handle, NEED_MORE, SUCCESS, and TRUE.
Referenced by pt_tls_receive().
 {
     switch (this->handle(this))
     {
         case NEED_MORE:
             return TRUE;
         case FAILED:
         case SUCCESS:
         default:
             DBG1(DBG_TNC, "PT-TLS connection terminates");
             this->destroy(this);
             close(fd);
             return FALSE;
     }
 }
static bool radius_receive (private_tnc_pdp_t * this, int fd, watcher_event_t event) static
Process packets received on the RADIUS socket
Definition at line 702 of file tnc_pdp.c.
References chunk_create(), client(), host_t::clone, DBG1, DBG2, DBG3, DBG_CFG, enumerator_t::destroy, host_t::destroy, radius_message_t::destroy, enumerator_t::enumerate, host_t::equals, FALSE, found, free_client_entry(), radius_message_t::get_code, radius_message_t::get_identifier, client_entry_t::host, host_create_from_sockaddr(), id, client_entry_t::last_id, client_entry_t::last_time, malloc_thing, MAX_PACKET, process_eap(), radius_message_code_names, radius_message_parse(), RADIUS_RETRANSMIT_TIMEOUT, request(), source, src, strerror, TRUE, and radius_message_t::verify.
Referenced by tnc_pdp_create().
 {
     radius_message_t *request;
     char buffer[MAX_PACKET];
     client_entry_t *client;
     bool retransmission = FALSE, found = FALSE, stale;
     enumerator_t *enumerator;
     int bytes_read = 0;
     host_t *source;
     uint8_t id;
     time_t now;
     union {
         struct sockaddr_in in4;
         struct sockaddr_in6 in6;
     } src;
     struct iovec iov = {
         .iov_base = buffer,
         .iov_len = MAX_PACKET,
     };
     struct msghdr msg = {
         .msg_name = &src,
         .msg_namelen = sizeof(src),
         .msg_iov = &iov,
         .msg_iovlen = 1,
     };
     /* read received packet */
     bytes_read = recvmsg(fd, &msg, 0);
     if (bytes_read < 0)
     {
         DBG1(DBG_CFG, "error reading RADIUS socket: %s", strerror(errno));
         return FALSE;
     }
     if (msg.msg_flags & MSG_TRUNC)
     {
         DBG1(DBG_CFG, "receive buffer too small, RADIUS packet discarded");
         return FALSE;
     }
     source = host_create_from_sockaddr((sockaddr_t*)&src);
     DBG2(DBG_CFG, "received RADIUS packet from %#H", source);
     DBG3(DBG_CFG, "%b", buffer, bytes_read);
     request = radius_message_parse(chunk_create(buffer, bytes_read));
     if (request)
     {
         DBG1(DBG_CFG, "received RADIUS %N from client '%H'",
         radius_message_code_names, request->get_code(request), source);
         if (request->verify(request, NULL, this->secret, this->hasher,
                                            this->signer))
         {
             id = request->get_identifier(request);
             now = time(NULL);
             enumerator = this->clients->create_enumerator(this->clients);
             while (enumerator->enumerate(enumerator, &client))
             {
                 stale = client->last_time < now - RADIUS_RETRANSMIT_TIMEOUT;
                 if (source->equals(source, client->host))
                 {
                     retransmission = !stale && client->last_id == id;
                     client->last_id = id;
                     client->last_time = now;
                     found = TRUE;
                 }
                 else if (stale)
                 {
                     this->clients->remove_at(this->clients, enumerator);
                     free_client_entry(client);
                 }
             }
             enumerator->destroy(enumerator);
             if (!found)
             {
                 client = malloc_thing(client_entry_t);
                 client->host = source->clone(source);
                 client->last_id = id;
                 client->last_time = now;
                 this->clients->insert_last(this->clients, client);
             }
             if (retransmission)
             {
                 DBG1(DBG_CFG, "ignoring RADIUS Access-Request 0x%02x, "
                               "already processing", id);
             }
             else
             {
                 process_eap(this, request, source);
             }
         }
         request->destroy(request);
     }
     else
     {
         DBG1(DBG_CFG, "received invalid RADIUS message, ignored");
     }
     source->destroy(source);
     return TRUE;
 }
static void send_message (private_tnc_pdp_t * this, radius_message_t * message, host_t * client) static
Send a RADIUS message to client
Definition at line 319 of file tnc_pdp.c.
References data, DBG1, DBG2, DBG3, DBG_CFG, radius_message_t::get_encoding, host_t::get_family, host_t::get_sockaddr, host_t::get_sockaddr_len, chunk_t::len, chunk_t::ptr, sendto, and strerror.
Referenced by send_response().
 {
     int fd;
     chunk_t data;
     fd = (client->get_family(client) == AF_INET) ?
             this->radius_ipv4 : this->radius_ipv6;
     data = message->get_encoding(message);
     DBG2(DBG_CFG, "sending RADIUS packet to %#H", client);
     DBG3(DBG_CFG, "%B", &data);
     if (sendto(fd, data.ptr, data.len, 0, client->get_sockaddr(client),
                *client->get_sockaddr_len(client)) != data.len)
     {
         DBG1(DBG_CFG, "sending RADIUS message failed: %s", strerror(errno));
     }
 }
static void send_response (private_tnc_pdp_t * this, radius_message_t * request, radius_message_code_t code, eap_payload_t * eap, identification_t * group, chunk_t msk, host_t * client) static
Send a RADIUS response for a request
Definition at line 417 of file tnc_pdp.c.
References radius_message_t::add, chunk_create(), chunk_free(), chunk_skip(), data, DBG1, DBG3, DBG_CFG, radius_message_t::destroy, eap_type_names, encrypt_mppe_key(), radius_message_t::get_authenticator, eap_payload_t::get_data, identification_t::get_encoding, radius_message_t::get_identifier, hasher, htoun32(), chunk_t::len, MAX_RADIUS_ATTRIBUTE_SIZE, MS_MPPE_RECV_KEY, MS_MPPE_SEND_KEY, chunk_t::ptr, radius_message_code_names, radius_message_create(), RADIUS_TUNNEL_TYPE_ESP, RAT_EAP_MESSAGE, RAT_FILTER_ID, RAT_TUNNEL_TYPE, RAT_VENDOR_SPECIFIC, recv, response, salt, send, send_message(), radius_message_t::set_identifier, radius_message_t::sign, signer, TRUE, and type.
Referenced by process_eap().
 {
     radius_message_t *response;
     chunk_t data, recv, send;
     u_int32_t tunnel_type;
     u_int16_t salt = 0;
     response = radius_message_create(code);
     data = eap->get_data(eap);
     DBG3(DBG_CFG, "%N payload %B", eap_type_names, this->type, &data);
     /* fragment data suitable for RADIUS */
     while (data.len > MAX_RADIUS_ATTRIBUTE_SIZE)
     {
         response->add(response, RAT_EAP_MESSAGE,
                       chunk_create(data.ptr, MAX_RADIUS_ATTRIBUTE_SIZE));
         data = chunk_skip(data, MAX_RADIUS_ATTRIBUTE_SIZE);
     }
     response->add(response, RAT_EAP_MESSAGE, data);
     if (group)
     {
         tunnel_type = RADIUS_TUNNEL_TYPE_ESP;
         htoun32(data.ptr, tunnel_type);
         data.len = sizeof(tunnel_type);
         response->add(response, RAT_TUNNEL_TYPE, data);
         response->add(response, RAT_FILTER_ID, group->get_encoding(group));
     }
     if (msk.len)
     {
         recv = chunk_create(msk.ptr, msk.len / 2);
         data = encrypt_mppe_key(this, MS_MPPE_RECV_KEY, recv, &salt, request);
         response->add(response, RAT_VENDOR_SPECIFIC, data);
         chunk_free(&data);
         send = chunk_create(msk.ptr + recv.len, msk.len - recv.len);
         data = encrypt_mppe_key(this, MS_MPPE_SEND_KEY, send, &salt, request);
         response->add(response, RAT_VENDOR_SPECIFIC, data);
         chunk_free(&data);
     }
     response->set_identifier(response, request->get_identifier(request));
     if (response->sign(response, request->get_authenticator(request),
                        this->secret, this->hasher, this->signer, NULL, TRUE))
     {
         DBG1(DBG_CFG, "sending RADIUS %N to client '%H'",
              radius_message_code_names, code, client);
         send_message(this, response, client);
     }
     response->destroy(response);
 }