strongSwan: child_sa_manager.c File Reference
child_sa_manager.c File Reference
#include "child_sa_manager.h"
#include <daemon.h>
#include <threading/mutex.h>
#include <collections/hashtable.h>
Classes
struct private_child_sa_manager_t
struct child_entry_t
Typedefs
typedef struct
private_child_sa_manager_t private_child_sa_manager_t
Functions
static void child_entry_destroy (child_entry_t *entry)
static u_int hash_in (child_entry_t *entry)
static bool equals_in (child_entry_t *a, child_entry_t *b)
static u_int hash_out (child_entry_t *entry)
static bool equals_out (child_entry_t *a, child_entry_t *b)
static u_int hash_id (child_entry_t *entry)
static bool equals_id (child_entry_t *a, child_entry_t *b)
METHOD (child_sa_manager_t, add, void, private_child_sa_manager_t *this, child_sa_t *child_sa, ike_sa_t *ike_sa)
METHOD (child_sa_manager_t, remove_, void, private_child_sa_manager_t *this, child_sa_t *child_sa)
static ike_sa_t * checkout_ikesa (private_child_sa_manager_t *this, ike_sa_id_t *id, u_int32_t unique_id, child_sa_t **child_sa)
METHOD (child_sa_manager_t, checkout_by_id, ike_sa_t *, private_child_sa_manager_t *this, u_int32_t unique_id, child_sa_t **child_sa)
METHOD (child_sa_manager_t, checkout, ike_sa_t *, private_child_sa_manager_t *this, protocol_id_t protocol, u_int32_t spi, host_t *dst, child_sa_t **child_sa)
METHOD (child_sa_manager_t, destroy, void, private_child_sa_manager_t *this)
child_sa_manager_t * child_sa_manager_create ()
Typedef Documentation
typedef struct private_child_sa_manager_t private_child_sa_manager_t
Definition at line 22 of file child_sa_manager.c.
Function Documentation
static ike_sa_t* checkout_ikesa (private_child_sa_manager_t * this, ike_sa_id_t * id, u_int32_t unique_id, child_sa_t ** child_sa) static
Check out an IKE_SA for a given CHILD_SA
Definition at line 204 of file child_sa_manager.c.
References charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkout, ike_sa_t::create_child_sa_enumerator, enumerator_t::destroy, ike_sa_t::destroy, enumerator_t::enumerate, FALSE, found, child_sa_t::get_unique_id, daemon_t::ike_sa_manager, and unique_id.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     child_sa_t *current;
     ike_sa_t *ike_sa;
     bool found = FALSE;
     ike_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager, id);
     id->destroy(id);
     if (ike_sa)
     {
         enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
         while (enumerator->enumerate(enumerator, &current))
         {
             found = current->get_unique_id(current) == unique_id;
             if (found)
             {
                 if (child_sa)
                 {
                     *child_sa = current;
                 }
                 break;
             }
         }
         enumerator->destroy(enumerator);
         if (found)
         {
             return ike_sa;
         }
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
     }
     return NULL;
 }
static void child_entry_destroy (child_entry_t * entry) static
Destroy a CHILD_SA entry
Definition at line 78 of file child_sa_manager.c.
References ike_sa_id_t::destroy, host_t::destroy, free(), child_entry_t::host_in, child_entry_t::host_out, and child_entry_t::ike_id.
Referenced by METHOD().
 {
     entry->ike_id->destroy(entry->ike_id);
     entry->host_in->destroy(entry->host_in);
     entry->host_out->destroy(entry->host_out);
     free(entry);
 }
static bool equals_id (child_entry_t * a, child_entry_t * b) static
Hashtable equals function for SAs by unique ID
Definition at line 137 of file child_sa_manager.c.
References child_entry_t::unique_id.
Referenced by child_sa_manager_create().
 {
     return a->unique_id == b->unique_id;
 }
static bool equals_in (child_entry_t * a, child_entry_t * b) static
Hashtable equals function for inbound SAs
Definition at line 99 of file child_sa_manager.c.
References child_entry_t::host_in, host_t::ip_equals, child_entry_t::proto, and child_entry_t::spi_in.
Referenced by child_sa_manager_create().
 {
     return a->spi_in == b->spi_in &&
            a->proto == b->proto &&
            a->host_in->ip_equals(a->host_in, b->host_in);
 }
static bool equals_out (child_entry_t * a, child_entry_t * b) static
Hashtable equals function for outbound SAs
Definition at line 119 of file child_sa_manager.c.
References child_entry_t::host_out, host_t::ip_equals, child_entry_t::proto, and child_entry_t::spi_out.
Referenced by child_sa_manager_create().
 {
     return a->spi_out == b->spi_out &&
            a->proto == b->proto &&
            a->host_out->ip_equals(a->host_out, b->host_out);
 }
static u_int hash_id (child_entry_t * entry) static
Hashtable hash function for SAs by unique ID
Definition at line 129 of file child_sa_manager.c.
References chunk_from_thing, chunk_hash(), and child_entry_t::unique_id.
Referenced by child_sa_manager_create(), and METHOD().
 {
     return chunk_hash(chunk_from_thing(entry->unique_id));
 }
static u_int hash_in (child_entry_t * entry) static
Hashtable hash function for inbound SAs
Definition at line 89 of file child_sa_manager.c.
References chunk_from_thing, chunk_hash(), chunk_hash_inc(), host_t::get_address, child_entry_t::host_in, child_entry_t::proto, and child_entry_t::spi_in.
Referenced by child_sa_manager_create().
 {
     return chunk_hash_inc(chunk_from_thing(entry->spi_in),
             chunk_hash_inc(entry->host_in->get_address(entry->host_in),
              chunk_hash(chunk_from_thing(entry->proto))));
 }
static u_int hash_out (child_entry_t * entry) static
Hashtable hash function for outbound SAs
Definition at line 109 of file child_sa_manager.c.
References chunk_from_thing, chunk_hash(), chunk_hash_inc(), host_t::get_address, child_entry_t::host_out, child_entry_t::proto, and child_entry_t::spi_out.
Referenced by child_sa_manager_create().
 {
     return chunk_hash_inc(chunk_from_thing(entry->spi_out),
             chunk_hash_inc(entry->host_out->get_address(entry->host_out),
              chunk_hash(chunk_from_thing(entry->proto))));
 }
METHOD (child_sa_manager_t , add , void , private_child_sa_manager_t * this, child_sa_t * child_sa, ike_sa_t * ike_sa)
Definition at line 142 of file child_sa_manager.c.
References child_entry_destroy(), host_t::clone, ike_sa_id_t::clone, FALSE, ike_sa_t::get_id, ike_sa_t::get_my_host, ike_sa_t::get_other_host, child_sa_t::get_protocol, child_sa_t::get_spi, child_sa_t::get_unique_id, id, in, INIT, mutex_t::lock, mutex, out, TRUE, and mutex_t::unlock.
 {
     child_entry_t *entry;
     host_t *in, *out;
     ike_sa_id_t *id;
     id = ike_sa->get_id(ike_sa);
     in = ike_sa->get_my_host(ike_sa);
     out = ike_sa->get_other_host(ike_sa);
     INIT(entry,
         .ike_id = id->clone(id),
         .unique_id = child_sa->get_unique_id(child_sa),
         .proto = child_sa->get_protocol(child_sa),
         .spi_in = child_sa->get_spi(child_sa, TRUE),
         .spi_out = child_sa->get_spi(child_sa, FALSE),
         .host_in = in->clone(in),
         .host_out = out->clone(out),
     );
     this->mutex->lock(this->mutex);
     if (!this->in->get(this->in, entry) &&
         !this->out->get(this->out, entry))
     {
         this->in->put(this->in, entry, entry);
         this->out->put(this->out, entry, entry);
         entry = this->ids->put(this->ids, entry, entry);
     }
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         child_entry_destroy(entry);
     }
 }
METHOD (child_sa_manager_t , remove_ , void , private_child_sa_manager_t * this, child_sa_t * child_sa)
Definition at line 179 of file child_sa_manager.c.
References child_entry_destroy(), child_sa_t::get_unique_id, in, key, mutex_t::lock, mutex, out, and mutex_t::unlock.
 {
     child_entry_t *entry, key = {
         .unique_id = child_sa->get_unique_id(child_sa),
     };
     this->mutex->lock(this->mutex);
     entry = this->ids->remove(this->ids, &key);
     if (entry)
     {
         this->in->remove(this->in, entry);
         this->out->remove(this->out, entry);
     }
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         child_entry_destroy(entry);
     }
 }
METHOD (child_sa_manager_t , checkout_by_id , ike_sa_t * , private_child_sa_manager_t * this, u_int32_t unique_id, child_sa_t ** child_sa)
Definition at line 240 of file child_sa_manager.c.
References checkout_ikesa(), ike_sa_id_t::clone, id, child_entry_t::ike_id, key, mutex_t::lock, mutex, unique_id, and mutex_t::unlock.
 {
     ike_sa_id_t *id;
     child_entry_t *entry, key = {
         .unique_id = unique_id,
     };
     this->mutex->lock(this->mutex);
     entry = this->ids->get(this->ids, &key);
     if (entry)
     {
         id = entry->ike_id->clone(entry->ike_id);
     }
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         return checkout_ikesa(this, id, unique_id, child_sa);
     }
     return NULL;
 }
METHOD (child_sa_manager_t , checkout , ike_sa_t * , private_child_sa_manager_t * this, protocol_id_t protocol, u_int32_t spi, host_t * dst, child_sa_t ** child_sa)
Definition at line 264 of file child_sa_manager.c.
References checkout_ikesa(), ike_sa_id_t::clone, dst, id, child_entry_t::ike_id, in, key, mutex_t::lock, mutex, out, protocol, child_entry_t::unique_id, unique_id, and mutex_t::unlock.
 {
     ike_sa_id_t *id;
     u_int32_t unique_id;
     child_entry_t *entry, key = {
         .spi_in = spi,
         .spi_out = spi,
         .host_in = dst,
         .host_out = dst,
         .proto = protocol,
     };
     this->mutex->lock(this->mutex);
     entry = this->in->get(this->in, &key);
     if (!entry)
     {
         entry = this->out->get(this->out, &key);
     }
     if (entry)
     {
         unique_id = entry->unique_id;
         id = entry->ike_id->clone(entry->ike_id);
     }
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         return checkout_ikesa(this, id, unique_id, child_sa);
     }
     return NULL;
 }
METHOD (child_sa_manager_t , destroy , void , private_child_sa_manager_t * this)
Definition at line 298 of file child_sa_manager.c.
References mutex_t::destroy, free(), in, mutex, and out.
 {
     this->in->destroy(this->in);
     this->out->destroy(this->out);
     this->ids->destroy(this->ids);
     this->mutex->destroy(this->mutex);
     free(this);
 }