strongSwan: task_manager_v1.c File Reference
task_manager_v1.c File Reference
#include "task_manager_v1.h"
#include <math.h>
#include <daemon.h>
#include <sa/ikev1/tasks/main_mode.h>
#include <sa/ikev1/tasks/aggressive_mode.h>
#include <sa/ikev1/tasks/quick_mode.h>
#include <sa/ikev1/tasks/quick_delete.h>
#include <sa/ikev1/tasks/xauth.h>
#include <sa/ikev1/tasks/mode_config.h>
#include <sa/ikev1/tasks/informational.h>
#include <sa/ikev1/tasks/isakmp_natd.h>
#include <sa/ikev1/tasks/isakmp_vendor.h>
#include <sa/ikev1/tasks/isakmp_cert_pre.h>
#include <sa/ikev1/tasks/isakmp_cert_post.h>
#include <sa/ikev1/tasks/isakmp_delete.h>
#include <sa/ikev1/tasks/isakmp_dpd.h>
#include <processing/jobs/retransmit_job.h>
#include <processing/jobs/delete_ike_sa_job.h>
#include <processing/jobs/dpd_timeout_job.h>
#include <processing/jobs/process_message_job.h>
#include <collections/array.h>
Classes
struct exchange_t
struct private_task_manager_t
Macros
#define MAX_OLD_HASHES 2
#define RESPONDING_SEQ INT_MAX
Typedefs
typedef struct exchange_t exchange_t
typedef struct
private_task_manager_t private_task_manager_t
Functions
static void clear_packets (array_t *array)
METHOD (task_manager_t, flush_queue, void, private_task_manager_t *this, task_queue_t queue)
METHOD (task_manager_t, flush, void, private_task_manager_t *this)
static bool activate_task (private_task_manager_t *this, task_type_t type)
static void send_packets (private_task_manager_t *this, array_t *packets)
static bool generate_message (private_task_manager_t *this, message_t *message, array_t **packets)
static status_t retransmit_packet (private_task_manager_t *this, u_int32_t seqnr, u_int mid, u_int retransmitted, array_t *packets)
METHOD (task_manager_t, retransmit, status_t, private_task_manager_t *this, u_int32_t seqnr)
static bool mode_config_expected (private_task_manager_t *this)
METHOD (task_manager_t, initiate, status_t, private_task_manager_t *this)
static status_t build_response (private_task_manager_t *this, message_t *request)
static void send_notify (private_task_manager_t *this, message_t *request, notify_type_t type)
static bool process_dpd (private_task_manager_t *this, message_t *message)
static bool have_quick_mode_task (private_task_manager_t *this, u_int32_t mid)
static bool have_aggressive_mode_task (private_task_manager_t *this)
static status_t process_request (private_task_manager_t *this, message_t *message)
static status_t process_response (private_task_manager_t *this, message_t *message)
static status_t handle_fragment (private_task_manager_t *this, message_t *msg)
static status_t parse_message (private_task_manager_t *this, message_t *msg)
static status_t queue_message (private_task_manager_t *this, message_t *msg)
METHOD (task_manager_t, process_message, status_t, private_task_manager_t *this, message_t *msg)
static bool has_queued (private_task_manager_t *this, task_type_t type)
METHOD (task_manager_t, queue_task, void, private_task_manager_t *this, task_t *task)
METHOD (task_manager_t, queue_ike, void, private_task_manager_t *this)
METHOD (task_manager_t, queue_ike_reauth, void, private_task_manager_t *this)
METHOD (task_manager_t, queue_ike_rekey, void, private_task_manager_t *this)
METHOD (task_manager_t, queue_ike_delete, void, private_task_manager_t *this)
METHOD (task_manager_t, queue_mobike, void, private_task_manager_t *this, bool roam, bool address)
METHOD (task_manager_t, queue_child, void, private_task_manager_t *this, child_cfg_t *cfg, u_int32_t reqid, traffic_selector_t *tsi, traffic_selector_t *tsr)
static bool have_equal_ts (child_sa_t *child1, child_sa_t *child2, bool local)
static bool is_redundant (private_task_manager_t *this, child_sa_t *child_sa)
static traffic_selector_t * get_first_ts (child_sa_t *child_sa, bool local)
METHOD (task_manager_t, queue_child_rekey, void, private_task_manager_t *this, protocol_id_t protocol, u_int32_t spi)
METHOD (task_manager_t, queue_child_delete, void, private_task_manager_t *this, protocol_id_t protocol, u_int32_t spi, bool expired)
METHOD (task_manager_t, queue_dpd, void, private_task_manager_t *this)
METHOD (task_manager_t, adopt_tasks, void, private_task_manager_t *this, task_manager_t *other_public)
static void migrate_child_tasks (private_task_manager_t *this, linked_list_t *src, linked_list_t *dst)
METHOD (task_manager_t, adopt_child_tasks, void, private_task_manager_t *this, task_manager_t *other_public)
METHOD (task_manager_t, busy, bool, private_task_manager_t *this)
METHOD (task_manager_t, incr_mid, void, private_task_manager_t *this, bool initiate)
METHOD (task_manager_t, reset, void, private_task_manager_t *this, u_int32_t initiate, u_int32_t respond)
METHOD (task_manager_t, create_task_enumerator, enumerator_t *, private_task_manager_t *this, task_queue_t queue)
METHOD (task_manager_t, destroy, void, private_task_manager_t *this)
task_manager_v1_t * task_manager_v1_create (ike_sa_t *ike_sa)
Macro Definition Documentation
#define MAX_OLD_HASHES 2
Number of old messages hashes we keep for retransmission.
In Main Mode, we must ignore messages from a previous message pair if we already continued to the next. Otherwise a late retransmission could be considered as a reply to the newer request.
Definition at line 50 of file task_manager_v1.c.
Referenced by METHOD().
#define RESPONDING_SEQ INT_MAX
First sequence number of responding packets.
To distinguish retransmission jobs for initiating and responding packets, we split up the sequence counter and use the upper half for responding.
Definition at line 58 of file task_manager_v1.c.
Referenced by METHOD(), retransmit_packet(), and task_manager_v1_create().
Typedef Documentation
typedef struct exchange_t exchange_t
Definition at line 60 of file task_manager_v1.c.
typedef struct private_task_manager_t private_task_manager_t
Definition at line 78 of file task_manager_v1.c.
Function Documentation
static bool activate_task (private_task_manager_t * this, task_type_t type) static
move a task of a specific type from the queue to the active list
Definition at line 281 of file task_manager_v1.c.
References DBG2, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, task_t::get_type, task_type_names, TRUE, and type.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     task_t *task;
     bool found = FALSE;
     enumerator = this->queued_tasks->create_enumerator(this->queued_tasks);
     while (enumerator->enumerate(enumerator, (void**)&task))
     {
         if (task->get_type(task) == type)
         {
             DBG2(DBG_IKE, "  activating %N task", task_type_names, type);
             this->queued_tasks->remove_at(this->queued_tasks, enumerator);
             this->active_tasks->insert_last(this->active_tasks, task);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static status_t build_response (private_task_manager_t * this, message_t * request) static
build a response depending on the "passive" task list
Definition at line 710 of file task_manager_v1.c.
References ALREADY_DONE, task_t::build, daemon_t::bus, charon, clear_packets(), host_t::clone, enumerator_t::destroy, task_t::destroy, message_t::destroy, DESTROY_ME, enumerator_t::enumerate, FAILED, FALSE, generate_message(), message_t::get_destination, message_t::get_exchange_type, message_t::get_message_id, message_t::get_source, task_t::get_type, bus_t::ike_updown, IKEV1_MAJOR_VERSION, IKEV1_MINOR_VERSION, initiate(), INVALID_ARG, me, message_create(), NEED_MORE, retransmit(), send_packets(), message_t::set_destination, message_t::set_exchange_type, message_t::set_message_id, message_t::set_request, message_t::set_source, SUCCESS, TASK_AGGRESSIVE_MODE, TASK_QUICK_MODE, and TRUE.
Referenced by process_request().
 {
     enumerator_t *enumerator;
     task_t *task;
     message_t *message;
     host_t *me, *other;
     bool delete = FALSE, cancelled = FALSE, expect_request = FALSE;
     me = request->get_destination(request);
     other = request->get_source(request);
     message = message_create(IKEV1_MAJOR_VERSION, IKEV1_MINOR_VERSION);
     message->set_exchange_type(message, request->get_exchange_type(request));
     /* send response along the path the request came in */
     message->set_source(message, me->clone(me));
     message->set_destination(message, other->clone(other));
     message->set_message_id(message, request->get_message_id(request));
     message->set_request(message, FALSE);
     this->responding.mid = request->get_message_id(request);
     this->responding.retransmitted = 0;
     this->responding.seqnr++;
     enumerator = this->passive_tasks->create_enumerator(this->passive_tasks);
     while (enumerator->enumerate(enumerator, (void*)&task))
     {
         switch (task->build(task, message))
         {
             case SUCCESS:
                 /* task completed, remove it */
                 this->passive_tasks->remove_at(this->passive_tasks, enumerator);
                 task->destroy(task);
                 continue;
             case NEED_MORE:
                 /* processed, but task needs another exchange */
                 if (task->get_type(task) == TASK_QUICK_MODE ||
                     task->get_type(task) == TASK_AGGRESSIVE_MODE)
                 {   /* we rely on initiator retransmission, except for
                      * three-message exchanges */
                     expect_request = TRUE;
                 }
                 continue;
             case ALREADY_DONE:
                 cancelled = TRUE;
                 break;
             case INVALID_ARG:
                 if (task->get_type(task) == TASK_QUICK_MODE)
                 {   /* not responsible for this exchange */
                     continue;
                 }
                 /* FALL */
             case FAILED:
             default:
                 charon->bus->ike_updown(charon->bus, this->ike_sa, FALSE);
                 /* FALL */
             case DESTROY_ME:
                 /* destroy IKE_SA, but SEND response first */
                 delete = TRUE;
                 break;
         }
         break;
     }
     enumerator->destroy(enumerator);
     clear_packets(this->responding.packets);
     if (cancelled)
     {
         message->destroy(message);
         return initiate(this);
     }
     if (!generate_message(this, message, &this->responding.packets))
     {
         message->destroy(message);
         charon->bus->ike_updown(charon->bus, this->ike_sa, FALSE);
         return DESTROY_ME;
     }
     message->destroy(message);
     if (expect_request && !delete)
     {
         return retransmit(this, this->responding.seqnr);
     }
     send_packets(this, this->responding.packets);
     if (delete)
     {
         return DESTROY_ME;
     }
     return SUCCESS;
 }
static void clear_packets (array_t * array) static
Reset retransmission packet list
Definition at line 226 of file task_manager_v1.c.
References array_remove(), ARRAY_TAIL, and packet_t::destroy.
Referenced by build_response(), METHOD(), process_request(), process_response(), and send_notify().
 {
     packet_t *packet;
     while (array_remove(array, ARRAY_TAIL, &packet))
     {
         packet->destroy(packet);
     }
 }
static bool generate_message (private_task_manager_t * this, message_t * message, array_t ** packets) static
Generates the given message and stores packet(s) in the given array
Definition at line 322 of file task_manager_v1.c.
References array_insert_create(), ARRAY_TAIL, enumerator_t::destroy, enumerator_t::enumerate, FALSE, SUCCESS, and TRUE.
Referenced by build_response(), METHOD(), and send_notify().
 {
     enumerator_t *fragments;
     packet_t *fragment;
     if (this->ike_sa->generate_message_fragmented(this->ike_sa, message,
                                                   &fragments) != SUCCESS)
     {
         return FALSE;
     }
     while (fragments->enumerate(fragments, &fragment))
     {
         array_insert_create(packets, ARRAY_TAIL, fragment);
     }
     fragments->destroy(fragments);
     return TRUE;
 }
static traffic_selector_t* get_first_ts (child_sa_t * child_sa, bool local) static
Get the first traffic selector of a CHILD_SA, local or remote
Definition at line 1729 of file task_manager_v1.c.
References child_sa_t::create_ts_enumerator, enumerator_t::destroy, and enumerator_t::enumerate.
Referenced by METHOD().
 {
     traffic_selector_t *ts = NULL;
     enumerator_t *enumerator;
     enumerator = child_sa->create_ts_enumerator(child_sa, local);
     enumerator->enumerate(enumerator, &ts);
     enumerator->destroy(enumerator);
     return ts;
 }
static status_t handle_fragment (private_task_manager_t * this, message_t * msg) static
Definition at line 1203 of file task_manager_v1.c.
References FAILED, lib, message_create_defrag(), NEED_MORE, process_message_job_create(), library_t::processor, processor_t::queue_job, status, and SUCCESS.
Referenced by parse_message().
 {
     status_t status;
     if (!this->defrag)
     {
         this->defrag = message_create_defrag(msg);
         if (!this->defrag)
         {
             return FAILED;
         }
     }
     status = this->defrag->add_fragment(this->defrag, msg);
     if (status == SUCCESS)
     {
         lib->processor->queue_job(lib->processor,
                             (job_t*)process_message_job_create(this->defrag));
         this->defrag = NULL;
         /* do not process the last fragment */
         status = NEED_MORE;
     }
     return status;
 }
static bool has_queued (private_task_manager_t * this, task_type_t type) static
Check if a given task has been queued already
Definition at line 1483 of file task_manager_v1.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, task_t::get_type, TRUE, and type.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     bool found = FALSE;
     task_t *task;
     enumerator = this->queued_tasks->create_enumerator(this->queued_tasks);
     while (enumerator->enumerate(enumerator, &task))
     {
         if (task->get_type(task) == type)
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static bool have_aggressive_mode_task (private_task_manager_t * this) static
Check if we still have an aggressive mode task queued
Definition at line 940 of file task_manager_v1.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, task_t::get_type, TASK_AGGRESSIVE_MODE, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     task_t *task;
     bool found = FALSE;
     enumerator = this->passive_tasks->create_enumerator(this->passive_tasks);
     while (enumerator->enumerate(enumerator, &task))
     {
         if (task->get_type(task) == TASK_AGGRESSIVE_MODE)
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static bool have_equal_ts (child_sa_t * child1, child_sa_t * child2, bool local) static
Check if two CHILD_SAs have the same traffic selector
Definition at line 1677 of file task_manager_v1.c.
References child_sa_t::create_ts_enumerator, enumerator_t::destroy, enumerator_t::enumerate, traffic_selector_t::equals, and FALSE.
Referenced by is_redundant().
 {
     enumerator_t *e1, *e2;
     traffic_selector_t *ts1, *ts2;
     bool equal = FALSE;
     e1 = child1->create_ts_enumerator(child1, local);
     e2 = child2->create_ts_enumerator(child2, local);
     if (e1->enumerate(e1, &ts1) && e2->enumerate(e2, &ts2))
     {
         equal = ts1->equals(ts1, ts2);
     }
     e2->destroy(e2);
     e1->destroy(e1);
     return equal;
 }
static bool have_quick_mode_task (private_task_manager_t * this, u_int32_t mid) static
Check if we already have a quick mode task queued for the exchange with the given message ID
Definition at line 913 of file task_manager_v1.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, quick_mode_t::get_mid, task_t::get_type, TASK_QUICK_MODE, and TRUE.
Referenced by process_request().
 {
     enumerator_t *enumerator;
     quick_mode_t *qm;
     task_t *task;
     bool found = FALSE;
     enumerator = this->passive_tasks->create_enumerator(this->passive_tasks);
     while (enumerator->enumerate(enumerator, &task))
     {
         if (task->get_type(task) == TASK_QUICK_MODE)
         {
             qm = (quick_mode_t*)task;
             if (qm->get_mid(qm) == mid)
             {
                 found = TRUE;
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static bool is_redundant (private_task_manager_t * this, child_sa_t * child_sa) static
Check if a CHILD_SA is redundant and we should delete instead of rekey
Definition at line 1698 of file task_manager_v1.c.
References CHILD_INSTALLED, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, child_sa_t::get_lifetime, child_sa_t::get_name, child_sa_t::get_state, child_sa_t::get_unique_id, have_equal_ts(), streq(), and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     child_sa_t *current;
     bool redundant = FALSE;
     enumerator = this->ike_sa->create_child_sa_enumerator(this->ike_sa);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current->get_state(current) == CHILD_INSTALLED &&
             streq(current->get_name(current), child_sa->get_name(child_sa)) &&
             have_equal_ts(current, child_sa, TRUE) &&
             have_equal_ts(current, child_sa, FALSE) &&
             current->get_lifetime(current, FALSE) >
                 child_sa->get_lifetime(child_sa, FALSE))
         {
             DBG1(DBG_IKE, "deleting redundant CHILD_SA %s{%d}",
                  child_sa->get_name(child_sa),
                  child_sa->get_unique_id(child_sa));
             redundant = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return redundant;
 }
METHOD (task_manager_t , flush_queue , void , private_task_manager_t * this, task_queue_t queue)
Definition at line 236 of file task_manager_v1.c.
References clear_packets(), task_t::destroy, EXCHANGE_TYPE_UNDEFINED, list, linked_list_t::remove_last, SUCCESS, TASK_QUEUE_ACTIVE, TASK_QUEUE_PASSIVE, and TASK_QUEUE_QUEUED.
 {
     linked_list_t *list;
     task_t *task;
     if (this->queued)
     {
         this->queued->destroy(this->queued);
         this->queued = NULL;
     }
     switch (queue)
     {
         case TASK_QUEUE_ACTIVE:
             list = this->active_tasks;
             /* cancel pending retransmits */
             this->initiating.type = EXCHANGE_TYPE_UNDEFINED;
             clear_packets(this->initiating.packets);
             break;
         case TASK_QUEUE_PASSIVE:
             list = this->passive_tasks;
             break;
         case TASK_QUEUE_QUEUED:
             list = this->queued_tasks;
             break;
         default:
             return;
     }
     while (list->remove_last(list, (void**)&task) == SUCCESS)
     {
         task->destroy(task);
     }
 }
METHOD (task_manager_t , flush , void , private_task_manager_t * this)
Definition at line 270 of file task_manager_v1.c.
References TASK_QUEUE_ACTIVE, TASK_QUEUE_PASSIVE, and TASK_QUEUE_QUEUED.
 {
     flush_queue(this, TASK_QUEUE_QUEUED);
     flush_queue(this, TASK_QUEUE_PASSIVE);
     flush_queue(this, TASK_QUEUE_ACTIVE);
 }
METHOD (task_manager_t , retransmit , status_t , private_task_manager_t * this, u_int32_t seqnr)
Definition at line 372 of file task_manager_v1.c.
References array_count(), NEED_MORE, retransmit_packet(), status, and SUCCESS.
 {
     status_t status = SUCCESS;
     if (seqnr == this->initiating.seqnr &&
         array_count(this->initiating.packets))
     {
         status = retransmit_packet(this, seqnr, this->initiating.mid,
                     this->initiating.retransmitted, this->initiating.packets);
         if (status == NEED_MORE)
         {
             this->initiating.retransmitted++;
             status = SUCCESS;
         }
     }
     if (seqnr == this->responding.seqnr &&
         array_count(this->responding.packets))
     {
         status = retransmit_packet(this, seqnr, this->responding.mid,
                     this->responding.retransmitted, this->responding.packets);
         if (status == NEED_MORE)
         {
             this->responding.retransmitted++;
             status = SUCCESS;
         }
     }
     return status;
 }
METHOD (task_manager_t , initiate , status_t , private_task_manager_t * this)
Definition at line 452 of file task_manager_v1.c.
References activate_task(), AGGRESSIVE, ALREADY_DONE, task_t::build, daemon_t::bus, charon, clear_packets(), host_t::clone, DBG1, DBG2, DBG_IKE, enumerator_t::destroy, task_t::destroy, message_t::destroy, DESTROY_ME, enumerator_t::enumerate, exchange(), exchange_type_names, EXCHANGE_TYPE_UNDEFINED, FAILED, FALSE, generate_message(), task_t::get_type, ID_PROT, IKE_CONNECTING, IKE_CREATED, IKE_DELETING, IKE_ESTABLISHED, bus_t::ike_updown, IKEV1_MAJOR_VERSION, IKEV1_MINOR_VERSION, INFORMATIONAL_V1, initiate(), me, message_create(), mode_config_expected(), NEED_MORE, QUICK_MODE, retransmit(), rng, send_packets(), message_t::set_destination, message_t::set_exchange_type, message_t::set_message_id, message_t::set_source, SUCCESS, TASK_AGGRESSIVE_MODE, TASK_INFORMATIONAL, TASK_ISAKMP_CERT_POST, TASK_ISAKMP_CERT_PRE, TASK_ISAKMP_DELETE, TASK_ISAKMP_DPD, TASK_ISAKMP_NATD, TASK_ISAKMP_VENDOR, TASK_MAIN_MODE, TASK_MODE_CONFIG, TASK_QUICK_DELETE, TASK_QUICK_MODE, task_type_names, TASK_XAUTH, TRANSACTION, and TRUE.
 {
     enumerator_t *enumerator;
     task_t *task;
     message_t *message;
     host_t *me, *other;
     exchange_type_t exchange = EXCHANGE_TYPE_UNDEFINED;
     bool new_mid = FALSE, expect_response = FALSE, cancelled = FALSE, keep = FALSE;
     if (this->initiating.type != EXCHANGE_TYPE_UNDEFINED &&
         this->initiating.type != INFORMATIONAL_V1)
     {
         DBG2(DBG_IKE, "delaying task initiation, %N exchange in progress",
                 exchange_type_names, this->initiating.type);
         /* do not initiate if we already have a message in the air */
         return SUCCESS;
     }
     if (this->active_tasks->get_count(this->active_tasks) == 0)
     {
         DBG2(DBG_IKE, "activating new tasks");
         switch (this->ike_sa->get_state(this->ike_sa))
         {
             case IKE_CREATED:
                 activate_task(this, TASK_ISAKMP_VENDOR);
                 activate_task(this, TASK_ISAKMP_CERT_PRE);
                 if (activate_task(this, TASK_MAIN_MODE))
                 {
                     exchange = ID_PROT;
                 }
                 else if (activate_task(this, TASK_AGGRESSIVE_MODE))
                 {
                     exchange = AGGRESSIVE;
                 }
                 activate_task(this, TASK_ISAKMP_CERT_POST);
                 activate_task(this, TASK_ISAKMP_NATD);
                 break;
             case IKE_CONNECTING:
                 if (activate_task(this, TASK_ISAKMP_DELETE))
                 {
                     exchange = INFORMATIONAL_V1;
                     new_mid = TRUE;
                     break;
                 }
                 if (activate_task(this, TASK_XAUTH))
                 {
                     exchange = TRANSACTION;
                     new_mid = TRUE;
                     break;
                 }
                 if (activate_task(this, TASK_INFORMATIONAL))
                 {
                     exchange = INFORMATIONAL_V1;
                     new_mid = TRUE;
                     break;
                 }
                 break;
             case IKE_ESTABLISHED:
                 if (activate_task(this, TASK_MODE_CONFIG))
                 {
                     exchange = TRANSACTION;
                     new_mid = TRUE;
                     break;
                 }
                 if (!mode_config_expected(this) &&
                     activate_task(this, TASK_QUICK_MODE))
                 {
                     exchange = QUICK_MODE;
                     new_mid = TRUE;
                     break;
                 }
                 if (activate_task(this, TASK_INFORMATIONAL))
                 {
                     exchange = INFORMATIONAL_V1;
                     new_mid = TRUE;
                     break;
                 }
                 if (activate_task(this, TASK_QUICK_DELETE))
                 {
                     exchange = INFORMATIONAL_V1;
                     new_mid = TRUE;
                     break;
                 }
                 if (activate_task(this, TASK_ISAKMP_DELETE))
                 {
                     exchange = INFORMATIONAL_V1;
                     new_mid = TRUE;
                     break;
                 }
                 if (activate_task(this, TASK_ISAKMP_DPD))
                 {
                     exchange = INFORMATIONAL_V1;
                     new_mid = TRUE;
                     break;
                 }
                 break;
             default:
                 break;
         }
     }
     else
     {
         DBG2(DBG_IKE, "reinitiating already active tasks");
         enumerator = this->active_tasks->create_enumerator(this->active_tasks);
         while (enumerator->enumerate(enumerator, (void**)&task))
         {
             DBG2(DBG_IKE, "  %N task", task_type_names, task->get_type(task));
             switch (task->get_type(task))
             {
                 case TASK_MAIN_MODE:
                     exchange = ID_PROT;
                     break;
                 case TASK_AGGRESSIVE_MODE:
                     exchange = AGGRESSIVE;
                     break;
                 case TASK_QUICK_MODE:
                     exchange = QUICK_MODE;
                     break;
                 case TASK_XAUTH:
                     exchange = TRANSACTION;
                     new_mid = TRUE;
                     break;
                 default:
                     continue;
             }
             break;
         }
         enumerator->destroy(enumerator);
     }
     if (exchange == EXCHANGE_TYPE_UNDEFINED)
     {
         DBG2(DBG_IKE, "nothing to initiate");
         /* nothing to do yet... */
         return SUCCESS;
     }
     me = this->ike_sa->get_my_host(this->ike_sa);
     other = this->ike_sa->get_other_host(this->ike_sa);
     if (new_mid)
     {
         if (!this->rng->get_bytes(this->rng, sizeof(this->initiating.mid),
                                  (void*)&this->initiating.mid))
         {
             DBG1(DBG_IKE, "failed to allocate message ID, destroying IKE_SA");
             flush(this);
             return DESTROY_ME;
         }
     }
     message = message_create(IKEV1_MAJOR_VERSION, IKEV1_MINOR_VERSION);
     message->set_message_id(message, this->initiating.mid);
     message->set_source(message, me->clone(me));
     message->set_destination(message, other->clone(other));
     message->set_exchange_type(message, exchange);
     this->initiating.type = exchange;
     this->initiating.retransmitted = 0;
     enumerator = this->active_tasks->create_enumerator(this->active_tasks);
     while (enumerator->enumerate(enumerator, (void*)&task))
     {
         switch (task->build(task, message))
         {
             case SUCCESS:
                 /* task completed, remove it */
                 this->active_tasks->remove_at(this->active_tasks, enumerator);
                 if (task->get_type(task) == TASK_AGGRESSIVE_MODE ||
                     task->get_type(task) == TASK_QUICK_MODE)
                 {   /* last message of three message exchange */
                     keep = TRUE;
                 }
                 task->destroy(task);
                 continue;
             case NEED_MORE:
                 expect_response = TRUE;
                 /* processed, but task needs another exchange */
                 continue;
             case ALREADY_DONE:
                 cancelled = TRUE;
                 break;
             case FAILED:
             default:
                 if (this->ike_sa->get_state(this->ike_sa) != IKE_CONNECTING)
                 {
                     charon->bus->ike_updown(charon->bus, this->ike_sa, FALSE);
                 }
                 /* FALL */
             case DESTROY_ME:
                 /* critical failure, destroy IKE_SA */
                 enumerator->destroy(enumerator);
                 message->destroy(message);
                 flush(this);
                 return DESTROY_ME;
         }
         break;
     }
     enumerator->destroy(enumerator);
     if (this->active_tasks->get_count(this->active_tasks) == 0 &&
         (exchange == QUICK_MODE || exchange == AGGRESSIVE))
     {   /* tasks completed, no exchange active anymore */
         this->initiating.type = EXCHANGE_TYPE_UNDEFINED;
     }
     if (cancelled)
     {
         message->destroy(message);
         return initiate(this);
     }
     clear_packets(this->initiating.packets);
     if (!generate_message(this, message, &this->initiating.packets))
     {
         /* message generation failed. There is nothing more to do than to
          * close the SA */
         message->destroy(message);
         flush(this);
         charon->bus->ike_updown(charon->bus, this->ike_sa, FALSE);
         return DESTROY_ME;
     }
     this->initiating.seqnr++;
     if (expect_response)
     {
         message->destroy(message);
         return retransmit(this, this->initiating.seqnr);
     }
     if (keep)
     {   /* keep the packet for retransmission, the responder might request it */
         send_packets(this, this->initiating.packets);
     }
     else
     {
         send_packets(this, this->initiating.packets);
         clear_packets(this->initiating.packets);
     }
     message->destroy(message);
     if (exchange == INFORMATIONAL_V1)
     {
         switch (this->ike_sa->get_state(this->ike_sa))
         {
             case IKE_CONNECTING:
                 /* close after sending an INFORMATIONAL when unestablished */
                 return FAILED;
             case IKE_DELETING:
                 /* close after sending a DELETE */
                 return DESTROY_ME;
             default:
                 break;
         }
     }
     return initiate(this);
 }
METHOD (task_manager_t , process_message , status_t , private_task_manager_t * this, message_t * msg)
Definition at line 1305 of file task_manager_v1.c.
References AGGRESSIVE, bus_t::alert, ALERT_RETRANSMIT_RECEIVE, array_count(), daemon_t::backends, daemon_t::bus, charon, chunk_hash(), DBG1, DBG_IKE, delete_ike_sa_job_create(), ike_cfg_t::destroy, DESTROY_ME, exchange_type_names, FAILED, FALSE, message_t::get_destination, message_t::get_exchange_type, message_t::get_first_payload_type, backend_manager_t::get_ike_cfg, settings_t::get_int, message_t::get_message_id, message_t::get_packet_data, message_t::get_source, HALF_OPEN_IKE_SA_TIMEOUT, hash, have_aggressive_mode_task(), ID_PROT, IKE_CONNECTING, IKE_CREATED, IKEV1, INFORMATIONAL_V1, lib, MAX_OLD_HASHES, me, bus_t::message, NEED_MORE, NO_PROPOSAL_CHOSEN, notify_type_names, library_t::ns, parse_message(), PLV1_FRAGMENT, process_request(), process_response(), queue_message(), QUICK_MODE, scheduler_t::schedule_job, library_t::scheduler, send_notify(), send_packets(), message_t::set_request, library_t::settings, STAT_INBOUND, status, SUCCESS, time_monotonic(), TRANSACTION, and TRUE.
 {
     u_int32_t hash, mid, i;
     host_t *me, *other;
     status_t status;
     /* TODO-IKEv1: update hosts more selectively */
     me = msg->get_destination(msg);
     other = msg->get_source(msg);
     mid = msg->get_message_id(msg);
     hash = chunk_hash(msg->get_packet_data(msg));
     for (i = 0; i < MAX_OLD_HASHES; i++)
     {
         if (this->initiating.old_hashes[i] == hash)
         {
             if (array_count(this->initiating.packets) &&
                 i == (this->initiating.old_hash_pos % MAX_OLD_HASHES) &&
                 (msg->get_exchange_type(msg) == QUICK_MODE ||
                  msg->get_exchange_type(msg) == AGGRESSIVE))
             {
                 DBG1(DBG_IKE, "received retransmit of response with ID %u, "
                      "resending last request", mid);
                 send_packets(this, this->initiating.packets);
                 return SUCCESS;
             }
             DBG1(DBG_IKE, "received retransmit of response with ID %u, "
                  "but next request already sent", mid);
             return SUCCESS;
         }
     }
     if ((mid && mid == this->initiating.mid) ||
         (this->initiating.mid == 0 &&
          msg->get_exchange_type(msg) == this->initiating.type &&
          this->active_tasks->get_count(this->active_tasks)))
     {
         msg->set_request(msg, FALSE);
         charon->bus->message(charon->bus, msg, TRUE, FALSE);
         status = parse_message(this, msg);
         if (status == NEED_MORE)
         {
             return SUCCESS;
         }
         if (status != SUCCESS)
         {
             return status;
         }
         this->ike_sa->set_statistic(this->ike_sa, STAT_INBOUND,
                                     time_monotonic(NULL));
         this->ike_sa->update_hosts(this->ike_sa, me, other, TRUE);
         charon->bus->message(charon->bus, msg, TRUE, TRUE);
         if (process_response(this, msg) != SUCCESS)
         {
             flush(this);
             return DESTROY_ME;
         }
         this->initiating.old_hashes[(++this->initiating.old_hash_pos) %
                                     MAX_OLD_HASHES] = hash;
     }
     else
     {
         if (hash == this->responding.hash)
         {
             if (array_count(this->responding.packets))
             {
                 DBG1(DBG_IKE, "received retransmit of request with ID %u, "
                      "retransmitting response", mid);
                 send_packets(this, this->responding.packets);
             }
             else if (array_count(this->initiating.packets) &&
                      this->initiating.type == INFORMATIONAL_V1)
             {
                 DBG1(DBG_IKE, "received retransmit of DPD request, "
                      "retransmitting response");
                 send_packets(this, this->initiating.packets);
             }
             else
             {
                 DBG1(DBG_IKE, "received retransmit of request with ID %u, "
                      "but no response to retransmit", mid);
             }
             charon->bus->alert(charon->bus, ALERT_RETRANSMIT_RECEIVE, msg);
             return SUCCESS;
         }
         /* reject Main/Aggressive Modes once established */
         if (msg->get_exchange_type(msg) == ID_PROT ||
             msg->get_exchange_type(msg) == AGGRESSIVE)
         {
             if (this->ike_sa->get_state(this->ike_sa) != IKE_CREATED &&
                 this->ike_sa->get_state(this->ike_sa) != IKE_CONNECTING &&
                 msg->get_first_payload_type(msg) != PLV1_FRAGMENT)
             {
                 DBG1(DBG_IKE, "ignoring %N in established IKE_SA state",
                      exchange_type_names, msg->get_exchange_type(msg));
                 return FAILED;
             }
         }
         /* drop XAuth/Mode Config/Quick Mode messages until we received the last
          * Aggressive Mode message.  since Informational messages are not
          * retransmitted we queue them. */
         if (have_aggressive_mode_task(this))
         {
             if (msg->get_exchange_type(msg) == INFORMATIONAL_V1)
             {
                 return queue_message(this, msg);
             }
             else if (msg->get_exchange_type(msg) != AGGRESSIVE)
             {
                 DBG1(DBG_IKE, "ignoring %N request while phase 1 is incomplete",
                      exchange_type_names, msg->get_exchange_type(msg));
                 return FAILED;
             }
         }
         /* queue XAuth/Mode Config messages unless the Main Mode exchange we
          * initiated is complete */
         if (msg->get_exchange_type(msg) == TRANSACTION &&
             this->active_tasks->get_count(this->active_tasks))
         {
             return queue_message(this, msg);
         }
         msg->set_request(msg, TRUE);
         charon->bus->message(charon->bus, msg, TRUE, FALSE);
         status = parse_message(this, msg);
         if (status == NEED_MORE)
         {
             return SUCCESS;
         }
         if (status != SUCCESS)
         {
             return status;
         }
         /* if this IKE_SA is virgin, we check for a config */
         if (this->ike_sa->get_ike_cfg(this->ike_sa) == NULL)
         {
             ike_sa_id_t *ike_sa_id;
             ike_cfg_t *ike_cfg;
             job_t *job;
             ike_cfg = charon->backends->get_ike_cfg(charon->backends,
                                                     me, other, IKEV1);
             if (ike_cfg == NULL)
             {
                 /* no config found for these hosts, destroy */
                 DBG1(DBG_IKE, "no IKE config found for %H...%H, sending %N",
                      me, other, notify_type_names, NO_PROPOSAL_CHOSEN);
                 send_notify(this, msg, NO_PROPOSAL_CHOSEN);
                 return DESTROY_ME;
             }
             this->ike_sa->set_ike_cfg(this->ike_sa, ike_cfg);
             ike_cfg->destroy(ike_cfg);
             /* add a timeout if peer does not establish it completely */
             ike_sa_id = this->ike_sa->get_id(this->ike_sa);
             job = (job_t*)delete_ike_sa_job_create(ike_sa_id, FALSE);
             lib->scheduler->schedule_job(lib->scheduler, job,
                     lib->settings->get_int(lib->settings,
                             "%s.half_open_timeout", HALF_OPEN_IKE_SA_TIMEOUT,
                             lib->ns));
         }
         this->ike_sa->update_hosts(this->ike_sa, me, other, TRUE);
         charon->bus->message(charon->bus, msg, TRUE, TRUE);
         if (process_request(this, msg) != SUCCESS)
         {
             flush(this);
             return DESTROY_ME;
         }
         this->responding.hash = hash;
     }
     return SUCCESS;
 }
METHOD (task_manager_t , queue_task , void , private_task_manager_t * this, task_t * task)
Definition at line 1502 of file task_manager_v1.c.
References DBG2, DBG_IKE, task_t::destroy, task_t::get_type, has_queued(), TASK_MODE_CONFIG, task_type_names, TASK_XAUTH, and type.
 {
     task_type_t type = task->get_type(task);
     switch (type)
     {
         case TASK_MODE_CONFIG:
         case TASK_XAUTH:
             if (has_queued(this, type))
             {
                 task->destroy(task);
                 return;
             }
             break;
         default:
             break;
     }
     DBG2(DBG_IKE, "queueing %N task", task_type_names, task->get_type(task));
     this->queued_tasks->insert_last(this->queued_tasks, task);
 }
METHOD (task_manager_t , queue_ike , void , private_task_manager_t * this)
Definition at line 1524 of file task_manager_v1.c.
References aggressive_mode_create(), has_queued(), isakmp_cert_post_create(), isakmp_cert_pre_create(), isakmp_natd_create(), isakmp_vendor_create(), main_mode_create(), TASK_AGGRESSIVE_MODE, TASK_ISAKMP_CERT_POST, TASK_ISAKMP_CERT_PRE, TASK_ISAKMP_NATD, TASK_ISAKMP_VENDOR, TASK_MAIN_MODE, TRUE, and peer_cfg_t::use_aggressive.
 {
     peer_cfg_t *peer_cfg;
     if (!has_queued(this, TASK_ISAKMP_VENDOR))
     {
         queue_task(this, (task_t*)isakmp_vendor_create(this->ike_sa, TRUE));
     }
     if (!has_queued(this, TASK_ISAKMP_CERT_PRE))
     {
         queue_task(this, (task_t*)isakmp_cert_pre_create(this->ike_sa, TRUE));
     }
     peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
     if (peer_cfg->use_aggressive(peer_cfg))
     {
         if (!has_queued(this, TASK_AGGRESSIVE_MODE))
         {
             queue_task(this, (task_t*)aggressive_mode_create(this->ike_sa, TRUE));
         }
     }
     else
     {
         if (!has_queued(this, TASK_MAIN_MODE))
         {
             queue_task(this, (task_t*)main_mode_create(this->ike_sa, TRUE));
         }
     }
     if (!has_queued(this, TASK_ISAKMP_CERT_POST))
     {
         queue_task(this, (task_t*)isakmp_cert_post_create(this->ike_sa, TRUE));
     }
     if (!has_queued(this, TASK_ISAKMP_NATD))
     {
         queue_task(this, (task_t*)isakmp_natd_create(this->ike_sa, TRUE));
     }
 }
METHOD (task_manager_t , queue_ike_reauth , void , private_task_manager_t * this)
Definition at line 1562 of file task_manager_v1.c.
References daemon_t::bus, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout_new, bus_t::children_migrate, host_t::clone, DBG1, DBG_IKE, enumerator_t::destroy, DESTROY_ME, enumerator_t::enumerate, task_t::get_type, host, IKE_REKEYING, daemon_t::ike_sa_manager, task_t::migrate, ike_sa_t::set_peer_cfg, bus_t::set_sa, TASK_QUICK_MODE, and TRUE.
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     ike_sa_t *new;
     host_t *host;
     new = charon->ike_sa_manager->checkout_new(charon->ike_sa_manager,
                                 this->ike_sa->get_version(this->ike_sa), TRUE);
     if (!new)
     {   /* shouldn't happen */
         return;
     }
     new->set_peer_cfg(new, this->ike_sa->get_peer_cfg(this->ike_sa));
     host = this->ike_sa->get_other_host(this->ike_sa);
     new->set_other_host(new, host->clone(host));
     host = this->ike_sa->get_my_host(this->ike_sa);
     new->set_my_host(new, host->clone(host));
     enumerator = this->ike_sa->create_virtual_ip_enumerator(this->ike_sa, TRUE);
     while (enumerator->enumerate(enumerator, &host))
     {
         new->add_virtual_ip(new, TRUE, host);
     }
     enumerator->destroy(enumerator);
     charon->bus->children_migrate(charon->bus, new->get_id(new),
                                   new->get_unique_id(new));
     enumerator = this->ike_sa->create_child_sa_enumerator(this->ike_sa);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         this->ike_sa->remove_child_sa(this->ike_sa, enumerator);
         new->add_child_sa(new, child_sa);
     }
     enumerator->destroy(enumerator);
     charon->bus->set_sa(charon->bus, new);
     charon->bus->children_migrate(charon->bus, NULL, 0);
     charon->bus->set_sa(charon->bus, this->ike_sa);
     if (!new->get_child_count(new))
     {   /* check if a Quick Mode task is queued (UNITY_LOAD_BALANCE case) */
         task_t *task;
         enumerator = this->queued_tasks->create_enumerator(this->queued_tasks);
         while (enumerator->enumerate(enumerator, &task))
         {
             if (task->get_type(task) == TASK_QUICK_MODE)
             {
                 this->queued_tasks->remove_at(this->queued_tasks, enumerator);
                 task->migrate(task, new);
                 new->queue_task(new, task);
             }
         }
         enumerator->destroy(enumerator);
     }
     if (new->initiate(new, NULL, 0, NULL, NULL) != DESTROY_ME)
     {
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, new);
         this->ike_sa->set_state(this->ike_sa, IKE_REKEYING);
     }
     else
     {
         charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager, new);
         DBG1(DBG_IKE, "reauthenticating IKE_SA failed");
     }
     charon->bus->set_sa(charon->bus, this->ike_sa);
 }
METHOD (task_manager_t , queue_ike_rekey , void , private_task_manager_t * this)
Definition at line 1632 of file task_manager_v1.c.
 {
     queue_ike_reauth(this);
 }
METHOD (task_manager_t , queue_ike_delete , void , private_task_manager_t * this)
Definition at line 1638 of file task_manager_v1.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, child_sa_t::get_protocol, child_sa_t::get_spi, isakmp_delete_create(), quick_delete_create(), and TRUE.
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     enumerator = this->ike_sa->create_child_sa_enumerator(this->ike_sa);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         queue_task(this, (task_t*)
             quick_delete_create(this->ike_sa, child_sa->get_protocol(child_sa),
                                 child_sa->get_spi(child_sa, TRUE), FALSE, FALSE));
     }
     enumerator->destroy(enumerator);
     queue_task(this, (task_t*)isakmp_delete_create(this->ike_sa, TRUE));
 }
METHOD (task_manager_t , queue_mobike , void , private_task_manager_t * this, bool roam, bool address)
Definition at line 1656 of file task_manager_v1.c.
 {
     /* Not supported in IKEv1 */
 }
METHOD (task_manager_t , queue_child , void , private_task_manager_t * this, child_cfg_t * cfg, u_int32_t reqid, traffic_selector_t * tsi, traffic_selector_t * tsr)
Definition at line 1662 of file task_manager_v1.c.
References quick_mode_create(), quick_mode_t::task, and quick_mode_t::use_reqid.
 {
     quick_mode_t *task;
     task = quick_mode_create(this->ike_sa, cfg, tsi, tsr);
     task->use_reqid(task, reqid);
     queue_task(this, &task->task);
 }
METHOD (task_manager_t , queue_child_rekey , void , private_task_manager_t * this, protocol_id_t protocol, u_int32_t spi)
Definition at line 1741 of file task_manager_v1.c.
References CHILD_INSTALLED, CHILD_REKEYING, FALSE, child_sa_t::get_config, get_first_ts(), child_sa_t::get_mark, child_cfg_t::get_ref, child_sa_t::get_reqid, child_sa_t::get_spi, child_sa_t::get_state, is_redundant(), quick_delete_create(), quick_mode_create(), quick_mode_t::rekey, child_sa_t::set_state, quick_mode_t::task, TRUE, quick_mode_t::use_marks, quick_mode_t::use_reqid, and mark_t::value.
 {
     child_sa_t *child_sa;
     child_cfg_t *cfg;
     quick_mode_t *task;
     child_sa = this->ike_sa->get_child_sa(this->ike_sa, protocol, spi, TRUE);
     if (!child_sa)
     {
         child_sa = this->ike_sa->get_child_sa(this->ike_sa, protocol, spi, FALSE);
     }
     if (child_sa && child_sa->get_state(child_sa) == CHILD_INSTALLED)
     {
         if (is_redundant(this, child_sa))
         {
             queue_task(this, (task_t*)quick_delete_create(this->ike_sa,
                                                 protocol, spi, FALSE, FALSE));
         }
         else
         {
             child_sa->set_state(child_sa, CHILD_REKEYING);
             cfg = child_sa->get_config(child_sa);
             task = quick_mode_create(this->ike_sa, cfg->get_ref(cfg),
                 get_first_ts(child_sa, TRUE), get_first_ts(child_sa, FALSE));
             task->use_reqid(task, child_sa->get_reqid(child_sa));
             task->use_marks(task, child_sa->get_mark(child_sa, TRUE).value,
                             child_sa->get_mark(child_sa, FALSE).value);
             task->rekey(task, child_sa->get_spi(child_sa, TRUE));
             queue_task(this, &task->task);
         }
     }
 }
METHOD (task_manager_t , queue_child_delete , void , private_task_manager_t * this, protocol_id_t protocol, u_int32_t spi, bool expired)
Definition at line 1776 of file task_manager_v1.c.
References FALSE, and quick_delete_create().
 {
     queue_task(this, (task_t*)quick_delete_create(this->ike_sa, protocol,
                                                   spi, FALSE, expired));
 }
METHOD (task_manager_t , queue_dpd , void , private_task_manager_t * this)
Definition at line 1784 of file task_manager_v1.c.
References DPD_R_U_THERE, dpd_timeout_job_create(), peer_cfg_t::get_dpd, peer_cfg_t::get_dpd_timeout, isakmp_dpd_create(), lib, retransmit(), scheduler_t::schedule_job_ms, and library_t::scheduler.
 {
     peer_cfg_t *peer_cfg;
     u_int32_t t, retransmit;
     queue_task(this, (task_t*)isakmp_dpd_create(this->ike_sa, DPD_R_U_THERE,
                                                 this->dpd_send++));
     peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
     /* compute timeout in milliseconds */
     t = 1000 * peer_cfg->get_dpd_timeout(peer_cfg);
     if (t == 0)
     {
         /* use the same timeout as a retransmitting IKE message would have */
         for (retransmit = 0; retransmit <= this->retransmit_tries; retransmit++)
         {
             t += (u_int32_t)(this->retransmit_timeout * 1000.0 *
                             pow(this->retransmit_base, retransmit));
         }
     }
     /* compensate for the already elapsed dpd delay */
     t -= 1000 * peer_cfg->get_dpd(peer_cfg);
     /* schedule DPD timeout job */
     lib->scheduler->schedule_job_ms(lib->scheduler,
         (job_t*)dpd_timeout_job_create(this->ike_sa->get_id(this->ike_sa)), t);
 }
METHOD (task_manager_t , adopt_tasks , void , private_task_manager_t * this, task_manager_t * other_public)
Definition at line 1813 of file task_manager_v1.c.
References DBG2, DBG_IKE, task_t::get_type, task_t::migrate, private_task_manager_t::queued_tasks, linked_list_t::remove_last, SUCCESS, and task_type_names.
 {
     private_task_manager_t *other = (private_task_manager_t*)other_public;
     task_t *task;
     /* move queued tasks from other to this */
     while (other->queued_tasks->remove_last(other->queued_tasks,
                                                 (void**)&task) == SUCCESS)
     {
         DBG2(DBG_IKE, "migrating %N task", task_type_names, task->get_type(task));
         task->migrate(task, this->ike_sa);
         this->queued_tasks->insert_first(this->queued_tasks, task);
     }
 }
METHOD (task_manager_t , adopt_child_tasks , void , private_task_manager_t * this, task_manager_t * other_public)
Definition at line 1851 of file task_manager_v1.c.
References private_task_manager_t::active_tasks, migrate_child_tasks(), and private_task_manager_t::queued_tasks.
 {
     private_task_manager_t *other = (private_task_manager_t*)other_public;
     /* move active child tasks from other to this */
     migrate_child_tasks(this, other->active_tasks, this->queued_tasks);
     /* do the same for queued tasks */
     migrate_child_tasks(this, other->queued_tasks, this->queued_tasks);
 }
METHOD (task_manager_t , busy , bool , private_task_manager_t * this)
Definition at line 1862 of file task_manager_v1.c.
 {
     return (this->active_tasks->get_count(this->active_tasks) > 0);
 }
METHOD (task_manager_t , incr_mid , void , private_task_manager_t * this, bool initiate)
Definition at line 1868 of file task_manager_v1.c.
 {
 }
METHOD (task_manager_t , reset , void , private_task_manager_t * this, u_int32_t initiate, u_int32_t respond)
Definition at line 1873 of file task_manager_v1.c.
References clear_packets(), enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, EXCHANGE_TYPE_UNDEFINED, initiate(), task_t::migrate, RESPONDING_SEQ, and SUCCESS.
 {
     enumerator_t *enumerator;
     task_t *task;
     /* reset message counters and retransmit packets */
     clear_packets(this->responding.packets);
     clear_packets(this->initiating.packets);
     this->responding.seqnr = RESPONDING_SEQ;
     this->responding.retransmitted = 0;
     this->initiating.mid = 0;
     this->initiating.seqnr = 0;
     this->initiating.retransmitted = 0;
     this->initiating.type = EXCHANGE_TYPE_UNDEFINED;
     DESTROY_IF(this->defrag);
     this->defrag = NULL;
     if (initiate != UINT_MAX)
     {
         this->dpd_send = initiate;
     }
     if (respond != UINT_MAX)
     {
         this->dpd_recv = respond;
     }
     /* reset queued tasks */
     enumerator = this->queued_tasks->create_enumerator(this->queued_tasks);
     while (enumerator->enumerate(enumerator, &task))
     {
         task->migrate(task, this->ike_sa);
     }
     enumerator->destroy(enumerator);
     /* reset active tasks */
     while (this->active_tasks->remove_last(this->active_tasks,
                                            (void**)&task) == SUCCESS)
     {
         task->migrate(task, this->ike_sa);
         this->queued_tasks->insert_first(this->queued_tasks, task);
     }
 }
METHOD (task_manager_t , create_task_enumerator , enumerator_t * , private_task_manager_t * this, task_queue_t queue)
Definition at line 1916 of file task_manager_v1.c.
References enumerator_create_empty(), TASK_QUEUE_ACTIVE, TASK_QUEUE_PASSIVE, and TASK_QUEUE_QUEUED.
 {
     switch (queue)
     {
         case TASK_QUEUE_ACTIVE:
             return this->active_tasks->create_enumerator(this->active_tasks);
         case TASK_QUEUE_PASSIVE:
             return this->passive_tasks->create_enumerator(this->passive_tasks);
         case TASK_QUEUE_QUEUED:
             return this->queued_tasks->create_enumerator(this->queued_tasks);
         default:
             return enumerator_create_empty();
     }
 }
METHOD (task_manager_t , destroy , void , private_task_manager_t * this)
Definition at line 1932 of file task_manager_v1.c.
References array_destroy(), clear_packets(), DESTROY_IF, free(), and rng.
 {
     flush(this);
     this->active_tasks->destroy(this->active_tasks);
     this->queued_tasks->destroy(this->queued_tasks);
     this->passive_tasks->destroy(this->passive_tasks);
     DESTROY_IF(this->defrag);
     DESTROY_IF(this->queued);
     clear_packets(this->responding.packets);
     array_destroy(this->responding.packets);
     clear_packets(this->initiating.packets);
     array_destroy(this->initiating.packets);
     DESTROY_IF(this->rng);
     free(this);
 }
static void migrate_child_tasks (private_task_manager_t * this, linked_list_t * src, linked_list_t * dst) static
Migrates child-creating tasks from src to dst
Definition at line 1832 of file task_manager_v1.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, task_t::get_type, linked_list_t::insert_last, task_t::migrate, linked_list_t::remove_at, and TASK_QUICK_MODE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     task_t *task;
     enumerator = src->create_enumerator(src);
     while (enumerator->enumerate(enumerator, &task))
     {
         if (task->get_type(task) == TASK_QUICK_MODE)
         {
             src->remove_at(src, enumerator);
             task->migrate(task, this->ike_sa);
             dst->insert_last(dst, task);
         }
     }
     enumerator->destroy(enumerator);
 }
static bool mode_config_expected (private_task_manager_t * this) static
Check if we have to wait for a mode config before starting a quick mode
Definition at line 405 of file task_manager_v1.c.
References peer_cfg_t::create_pool_enumerator, peer_cfg_t::create_virtual_ip_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, host, TRUE, and peer_cfg_t::use_pull_mode.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     peer_cfg_t *peer_cfg;
     char *pool;
     bool local;
     host_t *host;
     peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
     if (peer_cfg)
     {
         if (peer_cfg->use_pull_mode(peer_cfg))
         {
             enumerator = peer_cfg->create_pool_enumerator(peer_cfg);
             if (!enumerator->enumerate(enumerator, &pool))
             {   /* no pool configured */
                 enumerator->destroy(enumerator);
                 return FALSE;
             }
             enumerator->destroy(enumerator);
             local = FALSE;
         }
         else
         {
             enumerator = peer_cfg->create_virtual_ip_enumerator(peer_cfg);
             if (!enumerator->enumerate(enumerator, &host))
             {   /* not requesting a vip */
                 enumerator->destroy(enumerator);
                 return FALSE;
             }
             enumerator->destroy(enumerator);
             local = TRUE;
         }
         enumerator = this->ike_sa->create_virtual_ip_enumerator(this->ike_sa,
                                                                 local);
         if (!enumerator->enumerate(enumerator, &host))
         {   /* expecting a VIP exchange, but no VIP assigned yet */
             enumerator->destroy(enumerator);
             return TRUE;
         }
         enumerator->destroy(enumerator);
     }
     return FALSE;
 }
static status_t parse_message (private_task_manager_t * this, message_t * msg) static
Parse the given message and verify that it is valid.
Definition at line 1230 of file task_manager_v1.c.
References bus_t::alert, ALERT_PARSE_ERROR_BODY, daemon_t::bus, charon, DBG1, DBG_IKE, DESTROY_ME, exchange_type_names, FAILED, message_t::get_exchange_type, message_t::get_first_payload_type, message_t::get_message_id, message_t::get_request, handle_fragment(), IKE_CREATED, INVALID_EXCHANGE_TYPE, INVALID_HASH_INFORMATION, INVALID_STATE, NOT_SUPPORTED, message_t::parse_body, PARSE_ERROR, PAYLOAD_MALFORMED, PLV1_FRAGMENT, send_notify(), status, SUCCESS, and VERIFY_ERROR.
Referenced by METHOD().
 {
     status_t status;
     status = msg->parse_body(msg, this->ike_sa->get_keymat(this->ike_sa));
     if (status != SUCCESS)
     {
         switch (status)
         {
             case NOT_SUPPORTED:
                 DBG1(DBG_IKE, "unsupported exchange type");
                 send_notify(this, msg, INVALID_EXCHANGE_TYPE);
                 break;
             case PARSE_ERROR:
                 DBG1(DBG_IKE, "message parsing failed");
                 send_notify(this, msg, PAYLOAD_MALFORMED);
                 break;
             case VERIFY_ERROR:
                 DBG1(DBG_IKE, "message verification failed");
                 send_notify(this, msg, PAYLOAD_MALFORMED);
                 break;
             case FAILED:
                 DBG1(DBG_IKE, "integrity check failed");
                 send_notify(this, msg, INVALID_HASH_INFORMATION);
                 break;
             case INVALID_STATE:
                 DBG1(DBG_IKE, "found encrypted message, but no keys available");
                 send_notify(this, msg, PAYLOAD_MALFORMED);
             default:
                 break;
         }
         DBG1(DBG_IKE, "%N %s with message ID %u processing failed",
              exchange_type_names, msg->get_exchange_type(msg),
              msg->get_request(msg) ? "request" : "response",
              msg->get_message_id(msg));
         charon->bus->alert(charon->bus, ALERT_PARSE_ERROR_BODY, msg, status);
         if (this->ike_sa->get_state(this->ike_sa) == IKE_CREATED)
         {   /* invalid initiation attempt, close SA */
             return DESTROY_ME;
         }
     }
     if (msg->get_first_payload_type(msg) == PLV1_FRAGMENT)
     {
         return handle_fragment(this, msg);
     }
     return status;
 }
static bool process_dpd (private_task_manager_t * this, message_t * message) static
Process a DPD request/response
Definition at line 856 of file task_manager_v1.c.
References data, DBG1, DBG_IKE, DPD_R_U_THERE, DPD_R_U_THERE_ACK, FALSE, notify_payload_t::get_notification_data, message_t::get_notify, isakmp_dpd_create(), chunk_t::len, notify(), chunk_t::ptr, seq, STAT_INBOUND, time_monotonic(), TRUE, type, and untoh32().
Referenced by process_request().
 {
     notify_payload_t *notify;
     notify_type_t type;
     u_int32_t seq;
     chunk_t data;
     type = DPD_R_U_THERE;
     notify = message->get_notify(message, type);
     if (!notify)
     {
         type = DPD_R_U_THERE_ACK;
         notify = message->get_notify(message, type);
     }
     if (!notify)
     {
         return FALSE;
     }
     data = notify->get_notification_data(notify);
     if (data.len != 4)
     {
         return FALSE;
     }
     seq = untoh32(data.ptr);
     if (type == DPD_R_U_THERE)
     {
         if (this->dpd_recv == 0 || seq == this->dpd_recv)
         {   /* check sequence validity */
             this->dpd_recv = seq + 1;
             this->ike_sa->set_statistic(this->ike_sa, STAT_INBOUND,
                                         time_monotonic(NULL));
         }
         /* but respond anyway */
         this->ike_sa->queue_task(this->ike_sa,
                 &isakmp_dpd_create(this->ike_sa, DPD_R_U_THERE_ACK, seq)->task);
     }
     else /* DPD_R_U_THERE_ACK */
     {
         if (seq == this->dpd_send - 1)
         {
             this->ike_sa->set_statistic(this->ike_sa, STAT_INBOUND,
                                         time_monotonic(NULL));
         }
         else
         {
             DBG1(DBG_IKE, "received invalid DPD sequence number %u "
                  "(expected %u), ignored", seq, this->dpd_send - 1);
         }
     }
     return TRUE;
 }
static status_t process_request (private_task_manager_t * this, message_t * message) static
handle an incoming request message
Definition at line 962 of file task_manager_v1.c.
References AGGRESSIVE, aggressive_mode_create(), ALREADY_DONE, build_response(), daemon_t::bus, charon, clear_packets(), DBG1, DBG_IKE, enumerator_t::destroy, task_t::destroy, message_t::destroy, DESTROY_ME, enumerator_t::enumerate, FAILED, FALSE, message_t::get_exchange_type, message_t::get_message_id, task_t::get_type, have_quick_mode_task(), ID_PROT, IKE_CONNECTING, IKE_ESTABLISHED, bus_t::ike_updown, informational_create(), INFORMATIONAL_V1, initiate(), INVALID_ARG, isakmp_cert_post_create(), isakmp_cert_pre_create(), isakmp_natd_create(), isakmp_vendor_create(), main_mode_create(), mode_config_create(), NEED_MORE, task_t::process, process_dpd(), QUICK_MODE, quick_mode_create(), send_response(), STAT_INBOUND, status, SUCCESS, TASK_QUICK_MODE, time_monotonic(), TRANSACTION, TRUE, and xauth_create().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     task_t *task = NULL;
     bool send_response = FALSE, dpd = FALSE;
     if (message->get_exchange_type(message) == INFORMATIONAL_V1 ||
         message->get_exchange_type(message) == QUICK_MODE ||
         this->passive_tasks->get_count(this->passive_tasks) == 0)
     {   /* create tasks depending on request type, if not already some queued */
         switch (message->get_exchange_type(message))
         {
             case ID_PROT:
                 task = (task_t *)isakmp_vendor_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t*)isakmp_cert_pre_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t *)main_mode_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t*)isakmp_cert_post_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t *)isakmp_natd_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 break;
             case AGGRESSIVE:
                 task = (task_t *)isakmp_vendor_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t*)isakmp_cert_pre_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t *)aggressive_mode_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t*)isakmp_cert_post_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 task = (task_t *)isakmp_natd_create(this->ike_sa, FALSE);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 break;
             case QUICK_MODE:
                 if (this->ike_sa->get_state(this->ike_sa) != IKE_ESTABLISHED)
                 {
                     DBG1(DBG_IKE, "received quick mode request for "
                          "unestablished IKE_SA, ignored");
                     return FAILED;
                 }
                 if (have_quick_mode_task(this, message->get_message_id(message)))
                 {
                     break;
                 }
                 task = (task_t *)quick_mode_create(this->ike_sa, NULL,
                                                    NULL, NULL);
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 break;
             case INFORMATIONAL_V1:
                 if (process_dpd(this, message))
                 {
                     dpd = TRUE;
                 }
                 else
                 {
                     task = (task_t *)informational_create(this->ike_sa, NULL);
                     this->passive_tasks->insert_first(this->passive_tasks, task);
                 }
                 break;
             case TRANSACTION:
                 if (this->ike_sa->get_state(this->ike_sa) != IKE_CONNECTING)
                 {
                     task = (task_t *)mode_config_create(this->ike_sa,
                                                         FALSE, TRUE);
                 }
                 else
                 {
                     task = (task_t *)xauth_create(this->ike_sa, FALSE);
                 }
                 this->passive_tasks->insert_last(this->passive_tasks, task);
                 break;
             default:
                 return FAILED;
         }
     }
     if (dpd)
     {
         return initiate(this);
     }
     this->ike_sa->set_statistic(this->ike_sa, STAT_INBOUND, time_monotonic(NULL));
     /* let the tasks process the message */
     enumerator = this->passive_tasks->create_enumerator(this->passive_tasks);
     while (enumerator->enumerate(enumerator, (void*)&task))
     {
         switch (task->process(task, message))
         {
             case SUCCESS:
                 /* task completed, remove it */
                 this->passive_tasks->remove_at(this->passive_tasks, enumerator);
                 task->destroy(task);
                 continue;
             case NEED_MORE:
                 /* processed, but task needs at least another call to build() */
                 send_response = TRUE;
                 continue;
             case ALREADY_DONE:
                 send_response = FALSE;
                 break;
             case INVALID_ARG:
                 if (task->get_type(task) == TASK_QUICK_MODE)
                 {   /* not responsible for this exchange */
                     continue;
                 }
                 /* FALL */
             case FAILED:
             default:
                 charon->bus->ike_updown(charon->bus, this->ike_sa, FALSE);
                 /* FALL */
             case DESTROY_ME:
                 /* critical failure, destroy IKE_SA */
                 this->passive_tasks->remove_at(this->passive_tasks, enumerator);
                 enumerator->destroy(enumerator);
                 task->destroy(task);
                 return DESTROY_ME;
         }
         break;
     }
     enumerator->destroy(enumerator);
     if (send_response)
     {
         if (build_response(this, message) != SUCCESS)
         {
             return DESTROY_ME;
         }
     }
     else
     {   /* We don't send a response, so don't retransmit one if we get
          * the same message again. */
         clear_packets(this->responding.packets);
     }
     if (this->queued &&
         this->queued->get_exchange_type(this->queued) == INFORMATIONAL_V1)
     {
         message_t *queued;
         status_t status;
         queued = this->queued;
         this->queued = NULL;
         status = this->public.task_manager.process_message(
                                             &this->public.task_manager, queued);
         queued->destroy(queued);
         if (status == DESTROY_ME)
         {
             return status;
         }
     }
     if (this->passive_tasks->get_count(this->passive_tasks) == 0 &&
         this->queued_tasks->get_count(this->queued_tasks) > 0)
     {
         /* passive tasks completed, check if an active task has been queued,
          * such as XAUTH or modeconfig push */
         return initiate(this);
     }
     return SUCCESS;
 }
static status_t process_response (private_task_manager_t * this, message_t * message) static
handle an incoming response message
Definition at line 1127 of file task_manager_v1.c.
References ALREADY_DONE, daemon_t::bus, charon, clear_packets(), DBG1, DBG_IKE, enumerator_t::destroy, task_t::destroy, message_t::destroy, DESTROY_ME, enumerator_t::enumerate, exchange_type_names, EXCHANGE_TYPE_UNDEFINED, FAILED, FALSE, message_t::get_exchange_type, message_t::get_notify, bus_t::ike_updown, INITIAL_CONTACT, initiate(), NEED_MORE, task_t::process, QUICK_MODE, status, SUCCESS, and TRANSACTION.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     message_t *queued;
     status_t status;
     task_t *task;
     if (message->get_exchange_type(message) != this->initiating.type)
     {
         /* Windows server sends a fourth quick mode message having an initial
          * contact notify. Ignore this message for compatibility. */
         if (this->initiating.type == EXCHANGE_TYPE_UNDEFINED &&
             message->get_exchange_type(message) == QUICK_MODE &&
             message->get_notify(message, INITIAL_CONTACT))
         {
             DBG1(DBG_IKE, "ignoring fourth Quick Mode message");
             return SUCCESS;
         }
         DBG1(DBG_IKE, "received %N response, but expected %N",
              exchange_type_names, message->get_exchange_type(message),
              exchange_type_names, this->initiating.type);
         charon->bus->ike_updown(charon->bus, this->ike_sa, FALSE);
         return DESTROY_ME;
     }
     enumerator = this->active_tasks->create_enumerator(this->active_tasks);
     while (enumerator->enumerate(enumerator, (void*)&task))
     {
         switch (task->process(task, message))
         {
             case SUCCESS:
                 /* task completed, remove it */
                 this->active_tasks->remove_at(this->active_tasks, enumerator);
                 task->destroy(task);
                 continue;
             case NEED_MORE:
                 /* processed, but task needs another exchange */
                 continue;
             case ALREADY_DONE:
                 break;
             case FAILED:
             default:
                 charon->bus->ike_updown(charon->bus, this->ike_sa, FALSE);
                 /* FALL */
             case DESTROY_ME:
                 /* critical failure, destroy IKE_SA */
                 this->active_tasks->remove_at(this->active_tasks, enumerator);
                 enumerator->destroy(enumerator);
                 task->destroy(task);
                 return DESTROY_ME;
         }
         break;
     }
     enumerator->destroy(enumerator);
     this->initiating.type = EXCHANGE_TYPE_UNDEFINED;
     clear_packets(this->initiating.packets);
     if (this->queued && !this->active_tasks->get_count(this->active_tasks) &&
         this->queued->get_exchange_type(this->queued) == TRANSACTION)
     {
         queued = this->queued;
         this->queued = NULL;
         status = this->public.task_manager.process_message(
                                             &this->public.task_manager, queued);
         queued->destroy(queued);
         if (status == DESTROY_ME)
         {
             return status;
         }
     }
     return initiate(this);
 }
static status_t queue_message (private_task_manager_t * this, message_t * msg) static
Queue the given message if possible
Definition at line 1285 of file task_manager_v1.c.
References DBG1, DBG_IKE, message_t::destroy, exchange_type_names, FAILED, message_t::get_exchange_type, message_t::get_packet, message_create_from_packet(), and SUCCESS.
Referenced by METHOD().
 {
     if (this->queued)
     {
         DBG1(DBG_IKE, "ignoring %N request, queue full",
              exchange_type_names, msg->get_exchange_type(msg));
         return FAILED;
     }
     this->queued = message_create_from_packet(msg->get_packet(msg));
     if (this->queued->parse_header(this->queued) != SUCCESS)
     {
         this->queued->destroy(this->queued);
         this->queued = NULL;
         return FAILED;
     }
     DBG1(DBG_IKE, "queueing %N request as tasks still active",
          exchange_type_names, msg->get_exchange_type(msg));
     return SUCCESS;
 }
static status_t retransmit_packet (private_task_manager_t * this, u_int32_t seqnr, u_int mid, u_int retransmitted, array_t * packets) static
Retransmit a packet (or its fragments)
Definition at line 344 of file task_manager_v1.c.
References bus_t::alert, ALERT_RETRANSMIT_SEND, ALERT_RETRANSMIT_SEND_TIMEOUT, array_get(), daemon_t::bus, charon, DBG1, DBG_IKE, DESTROY_ME, lib, NEED_MORE, RESPONDING_SEQ, retransmit_job_create(), scheduler_t::schedule_job_ms, library_t::scheduler, and send_packets().
Referenced by METHOD().
 {
     packet_t *packet;
     u_int32_t t;
     array_get(packets, 0, &packet);
     if (retransmitted > this->retransmit_tries)
     {
         DBG1(DBG_IKE, "giving up after %u retransmits", retransmitted - 1);
         charon->bus->alert(charon->bus, ALERT_RETRANSMIT_SEND_TIMEOUT, packet);
         return DESTROY_ME;
     }
     t = (u_int32_t)(this->retransmit_timeout * 1000.0 *
                     pow(this->retransmit_base, retransmitted));
     if (retransmitted)
     {
         DBG1(DBG_IKE, "sending retransmit %u of %s message ID %u, seq %u",
              retransmitted, seqnr < RESPONDING_SEQ ? "request" : "response",
              mid, seqnr < RESPONDING_SEQ ? seqnr : seqnr - RESPONDING_SEQ);
         charon->bus->alert(charon->bus, ALERT_RETRANSMIT_SEND, packet);
     }
     send_packets(this, packets);
     lib->scheduler->schedule_job_ms(lib->scheduler, (job_t*)
             retransmit_job_create(seqnr, this->ike_sa->get_id(this->ike_sa)), t);
     return NEED_MORE;
 }
static void send_notify (private_task_manager_t * this, message_t * request, notify_type_t type) static
Send a notify in a separate INFORMATIONAL exchange back to the sender. The notify protocol_id is set to ISAKMP
Definition at line 804 of file task_manager_v1.c.
References message_t::add_payload, array_destroy(), clear_packets(), host_t::clone, DBG1, DBG_IKE, message_t::destroy, generate_message(), message_t::get_destination, message_t::get_exchange_type, message_t::get_source, IKEV1_MAJOR_VERSION, IKEV1_MINOR_VERSION, INFORMATIONAL_V1, host_t::is_anyaddr, me, message_create(), notify_payload_create_from_protocol_and_type(), PLV1_NOTIFY, PROTO_IKE, response, rng, send_packets(), message_t::set_destination, message_t::set_exchange_type, message_t::set_message_id, message_t::set_request, message_t::set_source, and TRUE.
Referenced by METHOD(), and parse_message().
 {
     message_t *response;
     array_t *packets = NULL;
     host_t *me, *other;
     u_int32_t mid;
     if (request->get_exchange_type(request) == INFORMATIONAL_V1)
     {   /* don't respond to INFORMATIONAL requests to avoid a notify war */
         DBG1(DBG_IKE, "ignore malformed INFORMATIONAL request");
         return;
     }
     if (!this->rng->get_bytes(this->rng, sizeof(mid), (void*)&mid))
     {
         DBG1(DBG_IKE, "failed to allocate message ID");
         return;
     }
     response = message_create(IKEV1_MAJOR_VERSION, IKEV1_MINOR_VERSION);
     response->set_exchange_type(response, INFORMATIONAL_V1);
     response->set_request(response, TRUE);
     response->set_message_id(response, mid);
     response->add_payload(response, (payload_t*)
                 notify_payload_create_from_protocol_and_type(PLV1_NOTIFY,
                                                     PROTO_IKE, type));
     me = this->ike_sa->get_my_host(this->ike_sa);
     if (me->is_anyaddr(me))
     {
         me = request->get_destination(request);
         this->ike_sa->set_my_host(this->ike_sa, me->clone(me));
     }
     other = this->ike_sa->get_other_host(this->ike_sa);
     if (other->is_anyaddr(other))
     {
         other = request->get_source(request);
         this->ike_sa->set_other_host(this->ike_sa, other->clone(other));
     }
     response->set_source(response, me->clone(me));
     response->set_destination(response, other->clone(other));
     if (generate_message(this, response, &packets))
     {
         send_packets(this, packets);
     }
     clear_packets(packets);
     array_destroy(packets);
     response->destroy(response);
 }
static void send_packets (private_task_manager_t * this, array_t * packets) static
Send packets in the given array (they get cloned)
Definition at line 306 of file task_manager_v1.c.
References array_create_enumerator(), charon, packet_t::clone, enumerator_t::destroy, enumerator_t::enumerate, sender_t::send, and daemon_t::sender.
Referenced by build_response(), METHOD(), retransmit_packet(), and send_notify().
 {
     enumerator_t *enumerator;
     packet_t *packet;
     enumerator = array_create_enumerator(packets);
     while (enumerator->enumerate(enumerator, &packet))
     {
         charon->sender->send(charon->sender, packet->clone(packet));
     }
     enumerator->destroy(enumerator);
 }