strongSwan: imv_test_agent.c File Reference
imv_test_agent.c File Reference
#include "imv_test_agent.h"
#include "imv_test_state.h"
#include <imv/imv_agent.h>
#include <imv/imv_msg.h>
#include <ietf/ietf_attr.h>
#include <ietf/ietf_attr_pa_tnc_error.h>
#include <ita/ita_attr.h>
#include <ita/ita_attr_get_settings.h>
#include <ita/ita_attr_command.h>
#include <ita/ita_attr_dummy.h>
#include <tncif_names.h>
#include <tncif_pa_subtypes.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_imv_test_agent_t
Typedefs
typedef struct
private_imv_test_agent_t private_imv_test_agent_t
Functions
METHOD (imv_agent_if_t, bind_functions, TNC_Result, private_imv_test_agent_t *this, TNC_TNCS_BindFunctionPointer bind_function)
METHOD (imv_agent_if_t, notify_connection_change, TNC_Result, private_imv_test_agent_t *this, TNC_ConnectionID id, TNC_ConnectionState new_state)
static TNC_Result receive_msg (private_imv_test_agent_t *this, imv_state_t *state, imv_msg_t *in_msg)
METHOD (imv_agent_if_t, receive_message, TNC_Result, private_imv_test_agent_t *this, TNC_ConnectionID id, TNC_MessageType msg_type, chunk_t msg)
METHOD (imv_agent_if_t, receive_message_long, TNC_Result, private_imv_test_agent_t *this, TNC_ConnectionID id, TNC_UInt32 src_imc_id, TNC_UInt32 dst_imv_id, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, chunk_t msg)
METHOD (imv_agent_if_t, batch_ending, TNC_Result, private_imv_test_agent_t *this, TNC_ConnectionID id)
METHOD (imv_agent_if_t, solicit_recommendation, TNC_Result, private_imv_test_agent_t *this, TNC_ConnectionID id)
METHOD (imv_agent_if_t, destroy, void, private_imv_test_agent_t *this)
imv_agent_if_t * imv_test_agent_create (const char *name, TNC_IMVID id, TNC_Version *actual_version)
Variables
static pen_type_t msg_types []
Typedef Documentation
typedef struct private_imv_test_agent_t private_imv_test_agent_t
Definition at line 34 of file imv_test_agent.c.
Function Documentation
METHOD (imv_agent_if_t , bind_functions , TNC_Result , private_imv_test_agent_t * this, TNC_TNCS_BindFunctionPointer bind_function)
Definition at line 58 of file imv_test_agent.c.
 {
     return this->agent->bind_functions(this->agent, bind_function);
 }
METHOD (imv_agent_if_t , notify_connection_change , TNC_Result , private_imv_test_agent_t * this, TNC_ConnectionID id, TNC_ConnectionState new_state)
Definition at line 64 of file imv_test_agent.c.
References imv_test_state_create(), TNC_CONNECTION_STATE_CREATE, and TNC_CONNECTION_STATE_DELETE.
 {
     imv_state_t *state;
     switch (new_state)
     {
         case TNC_CONNECTION_STATE_CREATE:
             state = imv_test_state_create(id);
             return this->agent->create_state(this->agent, state);
         case TNC_CONNECTION_STATE_DELETE:
             return this->agent->delete_state(this->agent, id);
         default:
             return this->agent->change_state(this->agent, id, new_state, NULL);
     }
 }
METHOD (imv_agent_if_t , receive_message , TNC_Result , private_imv_test_agent_t * this, TNC_ConnectionID id, TNC_MessageType msg_type, chunk_t msg)
Definition at line 228 of file imv_test_agent.c.
References imv_msg_t::destroy, imv_msg_create_from_data(), receive_msg(), result, and TNC_RESULT_FATAL.
 {
     imv_state_t *state;
     imv_msg_t *in_msg;
     TNC_Result result;
     if (!this->agent->get_state(this->agent, id, &state))
     {
         return TNC_RESULT_FATAL;
     }
     in_msg = imv_msg_create_from_data(this->agent, state, id, msg_type, msg);
     result = receive_msg(this, state, in_msg);
     in_msg->destroy(in_msg);
     return result;
 }
METHOD (imv_agent_if_t , receive_message_long , TNC_Result , private_imv_test_agent_t * this, TNC_ConnectionID id, TNC_UInt32 src_imc_id, TNC_UInt32 dst_imv_id, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, chunk_t msg)
Definition at line 247 of file imv_test_agent.c.
References imv_msg_t::destroy, imv_msg_create_from_long_data(), receive_msg(), result, and TNC_RESULT_FATAL.
 {
     imv_state_t *state;
     imv_msg_t *in_msg;
     TNC_Result result;
     if (!this->agent->get_state(this->agent, id, &state))
     {
         return TNC_RESULT_FATAL;
     }
     in_msg = imv_msg_create_from_long_data(this->agent, state, id,
                     src_imc_id, dst_imv_id, msg_vid, msg_subtype, msg);
     result = receive_msg(this, state, in_msg);
     in_msg->destroy(in_msg);
     return result;
 }
METHOD (imv_agent_if_t , batch_ending , TNC_Result , private_imv_test_agent_t * this, TNC_ConnectionID id)
Definition at line 269 of file imv_test_agent.c.
References TNC_RESULT_SUCCESS.
 {
     return TNC_RESULT_SUCCESS;
 }
METHOD (imv_agent_if_t , solicit_recommendation , TNC_Result , private_imv_test_agent_t * this, TNC_ConnectionID id)
Definition at line 275 of file imv_test_agent.c.
References TNC_RESULT_FATAL.
 {
     imv_state_t *state;
     if (!this->agent->get_state(this->agent, id, &state))
     {
         return TNC_RESULT_FATAL;
     }
     return this->agent->provide_recommendation(this->agent, state);
 }
METHOD (imv_agent_if_t , destroy , void , private_imv_test_agent_t * this)
Definition at line 287 of file imv_test_agent.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->agent);
     free(this);
 }
static TNC_Result receive_msg (private_imv_test_agent_t * this, imv_state_t * state, imv_msg_t * in_msg) static
Process a received message
Definition at line 85 of file imv_test_agent.c.
References imv_msg_t::add_attribute, imv_test_state_t::add_imc, imv_test_state_t::another_round, command, imv_msg_t::create_attribute_enumerator, DBG1, DBG_IMV, enumerator_t::destroy, imv_msg_t::destroy, enumerator_t::enumerate, FALSE, ita_attr_command_t::get_command, imv_state_t::get_connection_id, settings_t::get_int, ita_attr_dummy_t::get_size, imv_msg_t::get_src_id, pa_tnc_attr_t::get_type, imv_msg_create_as_reply(), ITA_ATTR_COMMAND, ita_attr_command_create(), ITA_ATTR_DUMMY, lib, library_t::ns, PEN_ITA, imv_msg_t::receive, result, imv_msg_t::send, imv_msg_t::send_assessment, imv_state_t::set_recommendation, imv_test_state_t::set_rounds, library_t::settings, streq(), TNC_IMV_ACTION_RECOMMENDATION_ALLOW, TNC_IMV_ACTION_RECOMMENDATION_ISOLATE, TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, TNC_IMV_EVALUATION_RESULT_COMPLIANT, TNC_IMV_EVALUATION_RESULT_ERROR, TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MAJOR, TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MINOR, TNC_RESULT_SUCCESS, TNC_RETRY_REASON_IMV_SERIOUS_EVENT, TRUE, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by METHOD().
 {
     imv_msg_t *out_msg;
     imv_test_state_t *test_state;
     enumerator_t *enumerator;
     pa_tnc_attr_t *attr;
     pen_type_t attr_type;
     TNC_Result result;
     int rounds;
     bool fatal_error = FALSE, received_command = FALSE, retry = FALSE;
     /* generate an outgoing PA-TNC message - we might need it */
     out_msg = imv_msg_create_as_reply(in_msg);
     /* parse received PA-TNC message and handle local and remote errors */
     result = in_msg->receive(in_msg, out_msg, &fatal_error);
     if (result != TNC_RESULT_SUCCESS)
     {
         out_msg->destroy(out_msg);
         return result;
     }
     /* add any new IMC and set its number of rounds */
     rounds = lib->settings->get_int(lib->settings,
                                     "%s.plugins.imv-test.rounds", 0, lib->ns);
     test_state = (imv_test_state_t*)state;
     test_state->add_imc(test_state, in_msg->get_src_id(in_msg), rounds);
     /* analyze PA-TNC attributes */
     enumerator = in_msg->create_attribute_enumerator(in_msg);
     while (enumerator->enumerate(enumerator, &attr))
     {
         attr_type = attr->get_type(attr);
         if (attr_type.vendor_id != PEN_ITA)
         {
             continue;
         }
         if (attr_type.type == ITA_ATTR_COMMAND)
         {
             ita_attr_command_t *ita_attr;
             char *command;
             received_command = TRUE;
             ita_attr = (ita_attr_command_t*)attr;
             command = ita_attr->get_command(ita_attr);
             if (streq(command, "allow"))
             {
                 state->set_recommendation(state,
                                 TNC_IMV_ACTION_RECOMMENDATION_ALLOW,
                                 TNC_IMV_EVALUATION_RESULT_COMPLIANT);
             }
             else if (streq(command, "isolate"))
             {
                 state->set_recommendation(state,
                                 TNC_IMV_ACTION_RECOMMENDATION_ISOLATE,
                                 TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MINOR);
             }
             else if (streq(command, "block") || streq(command, "none"))
             {
                 state->set_recommendation(state,
                                 TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS,
                                 TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MAJOR);
             }
             else if (streq(command, "retry"))
             {
                 retry = TRUE;
             }
             else
             {
                 DBG1(DBG_IMV, "unsupported ITA Command '%s'", command);
                 state->set_recommendation(state,
                                 TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION,
                                 TNC_IMV_EVALUATION_RESULT_ERROR);
             }
         }
         else if (attr_type.type == ITA_ATTR_DUMMY)
         {
             ita_attr_dummy_t *ita_attr;
             ita_attr = (ita_attr_dummy_t*)attr;
             DBG1(DBG_IMV, "received dummy attribute value (%d bytes)",
                            ita_attr->get_size(ita_attr));
         }
     }
     enumerator->destroy(enumerator);
     if (fatal_error)
     {
         state->set_recommendation(state,
                             TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION,
                             TNC_IMV_EVALUATION_RESULT_ERROR);
         result = out_msg->send_assessment(out_msg);
         if (result == TNC_RESULT_SUCCESS)
         {
             result = this->agent->provide_recommendation(this->agent, state);
         }
         return result;
     }
     /* request a handshake retry ? */
     if (retry)
     {
         test_state->set_rounds(test_state, rounds);
         return this->agent->request_handshake_retry(
                                     this->agent->get_id(this->agent),
                                     state->get_connection_id(state),
                                     TNC_RETRY_REASON_IMV_SERIOUS_EVENT);
     }
     /* repeat the measurement ? */
     if (test_state->another_round(test_state, in_msg->get_src_id(in_msg)))
     {
         attr = ita_attr_command_create("repeat");
         out_msg->add_attribute(out_msg, attr);
         /* send PA-TNC message with excl flag set */
         result = out_msg->send(out_msg, TRUE);
         out_msg->destroy(out_msg);
         return result;
     }
     if (received_command)
     {
         result = out_msg->send_assessment(out_msg);
         if (result == TNC_RESULT_SUCCESS)
         {
             result = this->agent->provide_recommendation(this->agent, state);
         }
     }
     else
     {
         /* send PA-TNC message with the EXCL flag set */
         result = out_msg->send(out_msg, TRUE);
     }
     out_msg->destroy(out_msg);
     return result;
  }
Variable Documentation
pen_type_t msg_types[] static
Initial value:
= {
    { PEN_ITA, PA_SUBTYPE_ITA_TEST }
}
Definition at line 37 of file imv_test_agent.c.