strongSwan: uci_parser.c File Reference
uci_parser.c File Reference
#include "uci_parser.h"
#include <stdarg.h>
#include <library.h>
#include <uci.h>
Classes
struct private_uci_parser_t
struct section_enumerator_t
Typedefs
typedef struct private_uci_parser_t private_uci_parser_t
Functions
METHOD (enumerator_t, section_enumerator_enumerate, bool, section_enumerator_t *this,...)
METHOD (enumerator_t, section_enumerator_destroy, void, section_enumerator_t *this)
METHOD (uci_parser_t, create_section_enumerator, enumerator_t *, private_uci_parser_t *this,...)
METHOD (uci_parser_t, destroy, void, private_uci_parser_t *this)
uci_parser_t * uci_parser_create (char *package)
Typedef Documentation
typedef struct private_uci_parser_t private_uci_parser_t
Definition at line 24 of file uci_parser.c.
Function Documentation
METHOD (enumerator_t , section_enumerator_enumerate , bool , section_enumerator_t * this, ...)
Definition at line 60 of file uci_parser.c.
References ctx, FALSE, TRUE, and value.
 {
     struct uci_element *element;
     char **value;
     va_list args;
     int i;
     if (&this->current->list == this->list)
     {
         return FALSE;
     }
     va_start(args, this);
     value = va_arg(args, char**);
     if (value)
     {
         if (uci_lookup(this->ctx, &element, this->package,
                        this->current->name, "name") == UCI_OK)
         {   /* use "name" attribute as config name if available ... */
             *value = uci_to_option(element)->value;
         }
         else
         {   /* ... or the section name becomes config name */
             *value = uci_to_section(this->current)->type;
         }
     }
     /* followed by keyword parameters */
     for (i = 0; this->keywords[i]; i++)
     {
         value = va_arg(args, char**);
         if (value && uci_lookup(this->ctx, &element, this->package,
                           this->current->name, this->keywords[i]) == UCI_OK)
         {
             *value = uci_to_option(element)->value;
         }
     }
     va_end(args);
     this->current = list_to_element(this->current->list.next);
     return TRUE;
 }
METHOD (enumerator_t , section_enumerator_destroy , void , section_enumerator_t * this)
Definition at line 105 of file uci_parser.c.
References ctx, and free().
 {
     uci_free_context(this->ctx);
     free(this);
 }
METHOD (uci_parser_t , create_section_enumerator , enumerator_t * , private_uci_parser_t * this, ...)
Definition at line 112 of file uci_parser.c.
References section_enumerator_t::ctx, section_enumerator_t::current, enumerator_t::destroy, enumerator_t::enumerate, section_enumerator_t::keywords, section_enumerator_t::list, malloc(), section_enumerator_t::package, and section_enumerator_t::public.
 {
     section_enumerator_t *e;
     va_list args;
     int i;
     /* allocate enumerator large enought to hold keyword pointers */
     i = 1;
     va_start(args, this);
     while (va_arg(args, char*))
     {
         i++;
     }
     va_end(args);
     e = malloc(sizeof(section_enumerator_t) + sizeof(char*) * i);
     i = 0;
     va_start(args, this);
     do
     {
         e->keywords[i] = va_arg(args, char*);
     }
     while (e->keywords[i++]);
     va_end(args);
     e->public.enumerate = (void*)_section_enumerator_enumerate;
     e->public.destroy = _section_enumerator_destroy;
     /* load uci context */
     e->ctx = uci_alloc_context();
     if (uci_load(e->ctx, this->package, &e->package) != UCI_OK)
     {
         section_enumerator_destroy(e);
         return NULL;
     }
     e->list = &e->package->sections;
     e->current = list_to_element(e->list->next);
     if (e->current->type != UCI_TYPE_SECTION)
     {
         section_enumerator_destroy(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (uci_parser_t , destroy , void , private_uci_parser_t * this)
Definition at line 157 of file uci_parser.c.
References free().
 {
     free(this->package);
     free(this);
 }