strongSwan: condvar_t Struct Reference
condvar_t Struct Reference
condvar
#include "condvar.h"
Public Attributes
void(* wait)(condvar_t *this, mutex_t *mutex)
bool(* timed_wait)(condvar_t *this, mutex_t *mutex, u_int timeout)
bool(* timed_wait_abs)(condvar_t *this, mutex_t *mutex, timeval_t tv)
void(* signal)(condvar_t *this)
void(* broadcast)(condvar_t *this)
void(* destroy)(condvar_t *this)
Detailed Description
Condvar wrapper to use in conjunction with mutex_t.
Definition at line 41 of file condvar.h.
Member Data Documentation
void(* condvar_t::broadcast)(condvar_t *this)
Wake up all threads in a condvar.
Definition at line 79 of file condvar.h.
Referenced by activate_all(), addr_entry_unregister(), CALLBACK(), condvar_cancel_run(), handle_ack(), handle_offer(), METHOD(), notify_end(), process_addr(), receive_events(), resolve_hosts(), START_TEST(), and wait_remove_entry().
void(* condvar_t::destroy)(condvar_t *this)
Destroy a condvar and free its resources.
Definition at line 84 of file condvar.h.
Referenced by CALLBACK(), cancellation_cond(), destroy_entry(), destroy_service(), entry_destroy(), METHOD(), on_accept(), session_entry_destroy(), START_TEST(), and vici_disconnect().
void(* condvar_t::signal)(condvar_t *this)
Wake up a single thread in a condvar.
Definition at line 74 of file condvar.h.
Referenced by CALLBACK(), condvar_recursive_run(), condvar_run(), destroy_async_data(), dispatch(), do_load_test(), get_route(), METHOD(), put_entry(), queue(), wait_for_entry(), and wait_result().
bool(* condvar_t::timed_wait)(condvar_t *this, mutex_t *mutex, u_int timeout)
Wait on a condvar until it gets signalized, or times out.
Parameters
mutex mutex to release while waiting
timeout timeout im ms
Returns
TRUE if timed out, FALSE otherwise
Definition at line 57 of file condvar.h.
Referenced by get_route(), METHOD(), send_once(), START_TEST(), and watchdog().
bool(* condvar_t::timed_wait_abs)(condvar_t *this, mutex_t *mutex, timeval_t tv)
Wait on a condvar until it gets signalized, or times out.
The passed timeval should be calculated based on the time_monotonic() function.
Parameters
mutex mutex to release while waiting
tv absolute time until timeout
Returns
TRUE if timed out, FALSE otherwise
Definition at line 69 of file condvar.h.
Referenced by METHOD(), schedule(), and START_TEST().
void(* condvar_t::wait)(condvar_t *this, mutex_t *mutex)
Wait on a condvar until it gets signalized.
Parameters
mutex mutex to release while waiting
Definition at line 48 of file condvar.h.
Referenced by cancellation_cond(), condvar_cancel_run(), condvar_run_broad(), dispatch(), find_entry(), get_route(), METHOD(), on_accept(), register_load_tester(), remove_entry(), schedule(), send_once(), START_TEST(), vici_register(), vici_submit(), wait_for_entry(), and wait_remove_entry().
The documentation for this struct was generated from the following file:
condvar.h