strongSwan: gcm_aead.c File Reference
gcm_aead.c File Reference
#include "gcm_aead.h"
#include <limits.h>
#include <crypto/iv/iv_gen_seq.h>
Classes
struct private_gcm_aead_t
Macros
#define BLOCK_SIZE 16
#define NONCE_SIZE 12
#define IV_SIZE 8
#define SALT_SIZE (NONCE_SIZE - IV_SIZE)
#define htobeword htonl
#define bewordtoh ntohl
#define SHIFT_WORD_TYPE u_int32_t
Typedefs
typedef struct private_gcm_aead_t private_gcm_aead_t
Functions
static void sr_block (char *block)
static void mult_block (char *x, char *y, char *res)
static void ghash (private_gcm_aead_t *this, chunk_t x, char *res)
static bool gctr (private_gcm_aead_t *this, char *icb, chunk_t x)
static void create_j (private_gcm_aead_t *this, char *iv, char *j)
static bool create_h (private_gcm_aead_t *this, char *h)
static bool crypt (private_gcm_aead_t *this, char *j, chunk_t in, chunk_t out)
static bool create_icv (private_gcm_aead_t *this, chunk_t assoc, chunk_t crypt, char *j, char *icv)
static bool verify_icv (private_gcm_aead_t *this, chunk_t assoc, chunk_t crypt, char *j, char *icv)
METHOD (aead_t, encrypt, bool, private_gcm_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encrypted)
METHOD (aead_t, decrypt, bool, private_gcm_aead_t *this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t *plain)
METHOD (aead_t, get_block_size, size_t, private_gcm_aead_t *this)
METHOD (aead_t, get_icv_size, size_t, private_gcm_aead_t *this)
METHOD (aead_t, get_iv_size, size_t, private_gcm_aead_t *this)
METHOD (aead_t, get_iv_gen, iv_gen_t *, private_gcm_aead_t *this)
METHOD (aead_t, get_key_size, size_t, private_gcm_aead_t *this)
METHOD (aead_t, set_key, bool, private_gcm_aead_t *this, chunk_t key)
METHOD (aead_t, destroy, void, private_gcm_aead_t *this)
gcm_aead_t * gcm_aead_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Macro Definition Documentation
#define bewordtoh ntohl
Definition at line 73 of file gcm_aead.c.
Referenced by sr_block().
#define BLOCK_SIZE 16
Definition at line 21 of file gcm_aead.c.
Referenced by create_h(), create_icv(), crypt(), gctr(), ghash(), METHOD(), mult_block(), and sr_block().
#define htobeword htonl
Find a suiteable word size and network order conversion functions
Definition at line 72 of file gcm_aead.c.
Referenced by sr_block().
#define IV_SIZE 8
Definition at line 23 of file gcm_aead.c.
Referenced by create_j(), and METHOD().
#define NONCE_SIZE 12
Definition at line 22 of file gcm_aead.c.
#define SALT_SIZE (NONCE_SIZE - IV_SIZE)
Definition at line 24 of file gcm_aead.c.
Referenced by create_j(), gcm_aead_create(), and METHOD().
#define SHIFT_WORD_TYPE u_int32_t
Definition at line 74 of file gcm_aead.c.
Referenced by sr_block().
Typedef Documentation
typedef struct private_gcm_aead_t private_gcm_aead_t
Definition at line 26 of file gcm_aead.c.
Function Documentation
static bool create_h (private_gcm_aead_t * this, char * h) static
Create GHASH subkey H
Definition at line 193 of file gcm_aead.c.
References BLOCK_SIZE, chunk_create(), chunk_from_thing, crypter, and memset.
Referenced by METHOD().
 {
     char zero[BLOCK_SIZE];
     memset(zero, 0, BLOCK_SIZE);
     memset(h, 0, BLOCK_SIZE);
     return this->crypter->encrypt(this->crypter, chunk_create(h, BLOCK_SIZE),
                                   chunk_from_thing(zero), NULL);
 }
static bool create_icv (private_gcm_aead_t * this, chunk_t assoc, chunk_t crypt, char * j, char * icv) static
Create ICV
Definition at line 225 of file gcm_aead.c.
References BLOCK_SIZE, chunk_alloc, chunk_from_thing, FALSE, free(), gctr(), ghash(), htoun32(), chunk_t::len, memcpy, memset, chunk_t::ptr, s, and TRUE.
Referenced by METHOD(), and verify_icv().
 {
     size_t assoc_pad, crypt_pad;
     chunk_t chunk;
     char s[BLOCK_SIZE], *pos;
     assoc_pad = (BLOCK_SIZE - (assoc.len % BLOCK_SIZE)) % BLOCK_SIZE;
     crypt_pad = (BLOCK_SIZE - (crypt.len % BLOCK_SIZE)) % BLOCK_SIZE;
     /* concatenate data to a new chunk */
     chunk = chunk_alloc(assoc.len + assoc_pad +
                         crypt.len + crypt_pad + BLOCK_SIZE);
     pos = chunk.ptr;
     /* add associated data */
     memcpy(pos, assoc.ptr, assoc.len);
     pos += assoc.len;
     memset(pos, 0, assoc_pad);
     pos += assoc_pad;
     /* add encrypted data */
     memcpy(pos, crypt.ptr, crypt.len);
     pos += crypt.len;
     memset(pos, 0, crypt_pad);
     pos += crypt_pad;
     /* write associated len */
     memset(pos, 0, 4);
     pos += 4;
     htoun32(pos, assoc.len * 8);
     pos += 4;
     /* write encrypted length */
     memset(pos, 0, 4);
     pos += 4;
     htoun32(pos, crypt.len * 8);
     pos += 4;
     ghash(this, chunk, s);
     free(chunk.ptr);
     if (!gctr(this, j, chunk_from_thing(s)))
     {
         return FALSE;
     }
     memcpy(icv, s, this->icv_size);
     return TRUE;
 }
static void create_j (private_gcm_aead_t * this, char * iv, char * j) static
Generate the block J0
Definition at line 183 of file gcm_aead.c.
References htoun32(), IV_SIZE, memcpy, salt, and SALT_SIZE.
Referenced by METHOD().
 {
     memcpy(j, this->salt, SALT_SIZE);
     memcpy(j + SALT_SIZE, iv, IV_SIZE);
     htoun32(j + SALT_SIZE + IV_SIZE, 1);
 }
static bool crypt (private_gcm_aead_t * this, char * j, chunk_t in, chunk_t out) static
Encrypt/decrypt
Definition at line 207 of file gcm_aead.c.
References BLOCK_SIZE, chunk_from_thing, chunk_increment(), gctr(), chunk_t::len, memcpy, and chunk_t::ptr.
Referenced by METHOD().
 {
     char icb[BLOCK_SIZE];
     memcpy(icb, j, BLOCK_SIZE);
     chunk_increment(chunk_from_thing(icb));
     out.len = in.len;
     if (in.ptr != out.ptr)
     {
         memcpy(out.ptr, in.ptr, in.len);
     }
     return gctr(this, icb, out);
 }
static bool gctr (private_gcm_aead_t * this, char * icb, chunk_t x) static
GCTR function, en-/decrypts x inline
Definition at line 158 of file gcm_aead.c.
References BLOCK_SIZE, cb(), chunk_from_thing, chunk_increment(), chunk_skip(), crypter, FALSE, chunk_t::len, memcpy, memset, memxor(), min, chunk_t::ptr, and TRUE.
Referenced by create_icv(), and crypt().
 {
     char cb[BLOCK_SIZE], iv[BLOCK_SIZE], tmp[BLOCK_SIZE];
     memset(iv, 0, BLOCK_SIZE);
     memcpy(cb, icb, BLOCK_SIZE);
     while (x.len)
     {
         memcpy(tmp, cb, BLOCK_SIZE);
         if (!this->crypter->encrypt(this->crypter, chunk_from_thing(tmp),
                                     chunk_from_thing(iv), NULL))
         {
             return FALSE;
         }
         memxor(x.ptr, tmp, min(BLOCK_SIZE, x.len));
         chunk_increment(chunk_from_thing(cb));
         x = chunk_skip(x, BLOCK_SIZE);
     }
     return TRUE;
 }
static void ghash (private_gcm_aead_t * this, chunk_t x, char * res) static
GHASH function
Definition at line 140 of file gcm_aead.c.
References BLOCK_SIZE, chunk_skip(), chunk_t::len, memcpy, memset, memxor(), mult_block(), and chunk_t::ptr.
Referenced by create_icv().
 {
     char y[BLOCK_SIZE];
     memset(y, 0, BLOCK_SIZE);
     while (x.len)
     {
         memxor(y, x.ptr, BLOCK_SIZE);
         mult_block(y, this->h, y);
         x = chunk_skip(x, BLOCK_SIZE);
     }
     memcpy(res, y, BLOCK_SIZE);
 }
METHOD (aead_t , encrypt , bool , private_gcm_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t * encrypted)
Definition at line 282 of file gcm_aead.c.
References BLOCK_SIZE, chunk_alloc, chunk_create(), create_icv(), create_j(), crypt(), chunk_t::len, and chunk_t::ptr.
 {
     char j[BLOCK_SIZE];
     create_j(this, iv.ptr, j);
     if (encrypted)
     {
         *encrypted = chunk_alloc(plain.len + this->icv_size);
         return crypt(this, j, plain, *encrypted) &&
                create_icv(this, assoc,
                     chunk_create(encrypted->ptr, encrypted->len - this->icv_size),
                     j, encrypted->ptr + encrypted->len - this->icv_size);
     }
     return crypt(this, j, plain, plain) &&
            create_icv(this, assoc, plain, j, plain.ptr + plain.len);
 }
METHOD (aead_t , decrypt , bool , private_gcm_aead_t * this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t * plain)
Definition at line 302 of file gcm_aead.c.
References BLOCK_SIZE, chunk_alloc, create_j(), crypt(), FALSE, chunk_t::len, chunk_t::ptr, and verify_icv().
 {
     char j[BLOCK_SIZE];
     if (encrypted.len < this->icv_size)
     {
         return FALSE;
     }
     create_j(this, iv.ptr, j);
     encrypted.len -= this->icv_size;
     if (!verify_icv(this, assoc, encrypted, j, encrypted.ptr + encrypted.len))
     {
         return FALSE;
     }
     if (plain)
     {
         *plain = chunk_alloc(encrypted.len);
         return crypt(this, j, encrypted, *plain);
     }
     return crypt(this, j, encrypted, encrypted);
 }
METHOD (aead_t , get_block_size , size_t , private_gcm_aead_t * this)
Definition at line 328 of file gcm_aead.c.
 {
     return 1;
 }
METHOD (aead_t , get_icv_size , size_t , private_gcm_aead_t * this)
Definition at line 334 of file gcm_aead.c.
 {
     return this->icv_size;
 }
METHOD (aead_t , get_iv_size , size_t , private_gcm_aead_t * this)
Definition at line 340 of file gcm_aead.c.
References IV_SIZE.
 {
     return IV_SIZE;
 }
METHOD (aead_t , get_iv_gen , iv_gen_t * , private_gcm_aead_t * this)
Definition at line 346 of file gcm_aead.c.
 {
     return this->iv_gen;
 }
METHOD (aead_t , get_key_size , size_t , private_gcm_aead_t * this)
Definition at line 352 of file gcm_aead.c.
References crypter, and SALT_SIZE.
 {
     return this->crypter->get_key_size(this->crypter) + SALT_SIZE;
 }
METHOD (aead_t , set_key , bool , private_gcm_aead_t * this, chunk_t key)
Definition at line 358 of file gcm_aead.c.
References create_h(), crypter, chunk_t::len, memcpy, chunk_t::ptr, salt, and SALT_SIZE.
 {
     memcpy(this->salt, key.ptr + key.len - SALT_SIZE, SALT_SIZE);
     key.len -= SALT_SIZE;
     return this->crypter->set_key(this->crypter, key) &&
            create_h(this, this->h);
 }
METHOD (aead_t , destroy , void , private_gcm_aead_t * this)
Definition at line 367 of file gcm_aead.c.
References crypter, and free().
 {
     this->crypter->destroy(this->crypter);
     this->iv_gen->destroy(this->iv_gen);
     free(this);
 }
static void mult_block (char * x, char * y, char * res) static
Naive implementation of block multiplication in GF128, no tables
Definition at line 106 of file gcm_aead.c.
References BLOCK_SIZE, memcpy, memset, memxor(), r, and sr_block().
Referenced by ghash().
 {
     char z[BLOCK_SIZE], v[BLOCK_SIZE], r;
     int bit, byte;
     r = 0xE1;
     memset(z, 0, BLOCK_SIZE);
     memcpy(v, y, BLOCK_SIZE);
     for (byte = 0; byte < BLOCK_SIZE; byte++)
     {
         for (bit = 7; bit >= 0; bit--)
         {
             if (x[byte] & (1 << bit))
             {
                 memxor(z, v, BLOCK_SIZE);
             }
             if (v[BLOCK_SIZE - 1] & 0x01)
             {
                 sr_block(v);
                 v[0] ^= r;
             }
             else
             {
                 sr_block(v);
             }
         }
     }
     memcpy(res, z, BLOCK_SIZE);
 }
static void sr_block (char * block) static
Bitshift a block right by one bit
Definition at line 80 of file gcm_aead.c.
References bewordtoh, BLOCK_SIZE, htobeword, and SHIFT_WORD_TYPE.
Referenced by mult_block().
 {
     int i;
     SHIFT_WORD_TYPE *word = (SHIFT_WORD_TYPE*)block;
     for (i = 0; i < BLOCK_SIZE / sizeof(*word); i++)
     {
         word[i] = bewordtoh(word[i]);
     }
     for (i = BLOCK_SIZE / sizeof(*word) - 1; i >= 0; i--)
     {
         word[i] >>= 1;
         if (i != 0)
         {
             word[i] |= word[i - 1] << (sizeof(*word) * 8 - 1);
         }
     }
     for (i = 0; i < BLOCK_SIZE / sizeof(*word); i++)
     {
         word[i] = htobeword(word[i]);
     }
 }
static bool verify_icv (private_gcm_aead_t * this, chunk_t assoc, chunk_t crypt, char * j, char * icv) static
Verify the ICV value
Definition at line 273 of file gcm_aead.c.
References create_icv(), and memeq_const().
Referenced by METHOD().
 {
     char tmp[this->icv_size];
     return create_icv(this, assoc, crypt, j, tmp) &&
            memeq_const(tmp, icv, this->icv_size);
 }