strongSwan: padlock_aes_crypter.c File Reference
padlock_aes_crypter.c File Reference
#include "padlock_aes_crypter.h"
#include <stdio.h>
Classes
struct private_padlock_aes_crypter_t
struct cword
Macros
#define AES_BLOCK_SIZE 16
#define PADLOCK_ALIGN __attribute__ ((__aligned__(16)))
Typedefs
typedef struct
private_padlock_aes_crypter_t private_padlock_aes_crypter_t
Functions
static void padlock_crypt (void *key, void *ctrl, void *src, void *dst, int count, void *iv)
static void crypt (private_padlock_aes_crypter_t *this, char *iv, chunk_t src, chunk_t *dst, bool enc)
METHOD (crypter_t, decrypt, bool, private_padlock_aes_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *dst)
METHOD (crypter_t, encrypt, bool, private_padlock_aes_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *dst)
METHOD (crypter_t, get_block_size, size_t, private_padlock_aes_crypter_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_padlock_aes_crypter_t *this)
METHOD (crypter_t, get_key_size, size_t, private_padlock_aes_crypter_t *this)
METHOD (crypter_t, set_key, bool, private_padlock_aes_crypter_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_padlock_aes_crypter_t *this)
padlock_aes_crypter_t * padlock_aes_crypter_create (encryption_algorithm_t algo, size_t key_size)
Macro Definition Documentation
#define AES_BLOCK_SIZE 16
Definition at line 20 of file padlock_aes_crypter.c.
Referenced by crypt(), and METHOD().
#define PADLOCK_ALIGN __attribute__ ((__aligned__(16)))
Definition at line 21 of file padlock_aes_crypter.c.
Referenced by crypt().
Typedef Documentation
typedef struct private_padlock_aes_crypter_t private_padlock_aes_crypter_t
Definition at line 23 of file padlock_aes_crypter.c.
Function Documentation
static void crypt (private_padlock_aes_crypter_t * this, char * iv, chunk_t src, chunk_t * dst, bool enc) static
Do encryption/decryption operation using Padlock control word
Definition at line 84 of file padlock_aes_crypter.c.
References AES_BLOCK_SIZE, chunk_alloc, enc, key, chunk_t::len, memcpy, memset, memwipe(), PADLOCK_ALIGN, padlock_crypt(), and chunk_t::ptr.
Referenced by METHOD().
 {
     cword cword PADLOCK_ALIGN;
     u_char key_aligned[256] PADLOCK_ALIGN;
     u_char iv_aligned[16] PADLOCK_ALIGN;
     memset(&cword, 0, sizeof(cword));
     /* set encryption/decryption flag */
     cword.encdec = enc;
     /* calculate rounds and key size */
     cword.rounds = 10 + (this->key.len - 16) / 4;
     cword.ksize = (this->key.len - 16) / 8;
     /* enable autoalign */
     cword.algo |= 2;
     /* move data to aligned buffers */
     memcpy(iv_aligned, iv, sizeof(iv_aligned));
     memcpy(key_aligned, this->key.ptr, this->key.len);
     *dst = chunk_alloc(src.len);
     padlock_crypt(key_aligned, &cword, src.ptr, dst->ptr,
                   src.len / AES_BLOCK_SIZE, iv_aligned);
     memwipe(key_aligned, sizeof(key_aligned));
 }
METHOD (crypter_t , decrypt , bool , private_padlock_aes_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * dst)
Definition at line 112 of file padlock_aes_crypter.c.
References crypt(), chunk_t::ptr, and TRUE.
 {
     crypt(this, iv.ptr, data, dst, TRUE);
     return TRUE;
 }
METHOD (crypter_t , encrypt , bool , private_padlock_aes_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * dst)
Definition at line 119 of file padlock_aes_crypter.c.
References crypt(), FALSE, chunk_t::ptr, and TRUE.
 {
     crypt(this, iv.ptr, data, dst, FALSE);
     return TRUE;
 }
METHOD (crypter_t , get_block_size , size_t , private_padlock_aes_crypter_t * this)
Definition at line 126 of file padlock_aes_crypter.c.
References AES_BLOCK_SIZE.
 {
     return AES_BLOCK_SIZE;
 }
METHOD (crypter_t , get_iv_size , size_t , private_padlock_aes_crypter_t * this)
Definition at line 132 of file padlock_aes_crypter.c.
References AES_BLOCK_SIZE.
 {
     return AES_BLOCK_SIZE;
 }
METHOD (crypter_t , get_key_size , size_t , private_padlock_aes_crypter_t * this)
Definition at line 138 of file padlock_aes_crypter.c.
References key.
 {
     return this->key.len;
 }
METHOD (crypter_t , set_key , bool , private_padlock_aes_crypter_t * this, chunk_t key)
Definition at line 144 of file padlock_aes_crypter.c.
References chunk_t::len, memcpy, min, chunk_t::ptr, and TRUE.
 {
     memcpy(this->key.ptr, key.ptr, min(key.len, this->key.len));
     return TRUE;
 }
METHOD (crypter_t , destroy , void , private_padlock_aes_crypter_t * this)
Definition at line 151 of file padlock_aes_crypter.c.
References chunk_clear(), free(), and key.
 {
     chunk_clear(&this->key);
     free(this);
 }
static void padlock_crypt (void * key, void * ctrl, void * src, void * dst, int count, void * iv) static
Invoke the actual de/encryption
Definition at line 59 of file padlock_aes_crypter.c.
References count, and src.
Referenced by crypt().
 {
     asm volatile(
         "pushl %%eax\n pushl %%ebx\n pushl %%ecx\n"
         "pushl %%edx\n pushl %%esi\n pushl %%edi\n"
         "pushfl\n popfl\n"
         "movl %0, %%eax\n"
         "movl %1, %%ebx\n"
         "movl %2, %%ecx\n"
         "movl %3, %%edx\n"
         "movl %4, %%esi\n"
         "movl %5, %%edi\n"
         "rep\n"
         ".byte 0x0f, 0xa7, 0xd0\n"
         "popl %%edi\n popl %%esi\n popl %%edx\n"
         "popl %%ecx\n popl %%ebx\n popl %%eax\n"
         :
         : "m"(iv),"m"(key), "m"(count), "m"(ctrl), "m"(src), "m"(dst)
         : "eax", "ecx", "edx", "esi", "edi");
 }