strongSwan: sa_payload
sa_payload
payloads
Classes
struct sa_payload_t
Typedefs
typedef struct sa_payload_t sa_payload_t
Functions
sa_payload_t * sa_payload_create (payload_type_t type)
sa_payload_t * sa_payload_create_from_proposals_v2 (linked_list_t *proposals)
sa_payload_t * sa_payload_create_from_proposal_v2 (proposal_t *proposal)
sa_payload_t * sa_payload_create_from_proposals_v1 (linked_list_t *proposals, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp, u_int16_t cpi)
sa_payload_t * sa_payload_create_from_proposal_v1 (proposal_t *proposal, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp, u_int16_t cpi)
Detailed Description
Typedef Documentation
typedef struct sa_payload_t sa_payload_t
Definition at line 25 of file sa_payload.h.
Function Documentation
sa_payload_t* sa_payload_create (payload_type_t type)
Creates an empty sa_payload_t object
Parameters
type PLV2_SECURITY_ASSOCIATION or PLV1_SECURITY_ASSOCIATION
Returns
created sa_payload_t object
Definition at line 485 of file sa_payload.c.
References compute_length(), IKEV1_DOI_IPSEC, INIT, linked_list_create(), PL_NONE, SIT_IDENTITY_ONLY, and type.
Referenced by payload_create(), sa_payload_create_from_proposal_v2(), sa_payload_create_from_proposals_v1(), and sa_payload_create_from_proposals_v2().
 {
     private_sa_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_proposals = _get_proposals,
             .get_ipcomp_proposals = _get_ipcomp_proposals,
             .create_substructure_enumerator = _create_substructure_enumerator,
             .get_lifetime = _get_lifetime,
             .get_lifebytes = _get_lifebytes,
             .get_auth_method = _get_auth_method,
             .get_encap_mode = _get_encap_mode,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .proposals = linked_list_create(),
         .type = type,
         /* for IKEv1 only */
         .doi = IKEV1_DOI_IPSEC,
         .situation = SIT_IDENTITY_ONLY,
     );
     compute_length(this);
     return &this->public;
 }
sa_payload_t* sa_payload_create_from_proposal_v1 (proposal_t * proposal, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp, u_int16_t cpi)
Creates an IKEv1 sa_payload_t object from a single proposal.
Parameters
proposal proposal from which the payload should be built.
lifetime lifetime in seconds
lifebytes lifebytes, in bytes
auth authentication method to use, or AUTH_NONE
mode IPsec encapsulation mode, TRANSPORT or TUNNEL
udp ENCAP_UDP to use UDP encapsulation
cpi CPI in case IPComp should be used
Returns
sa_payload_t object
Definition at line 604 of file sa_payload.c.
References linked_list_t::destroy, linked_list_t::insert_last, linked_list_create(), and sa_payload_create_from_proposals_v1().
Referenced by METHOD().
 {
     private_sa_payload_t *this;
     linked_list_t *proposals;
     proposals = linked_list_create();
     proposals->insert_last(proposals, proposal);
     this = (private_sa_payload_t*)sa_payload_create_from_proposals_v1(proposals,
                                     lifetime, lifebytes, auth, mode, udp, cpi);
     proposals->destroy(proposals);
     return &this->public;
 }
sa_payload_t* sa_payload_create_from_proposal_v2 (proposal_t * proposal)
Creates an IKEv2 sa_payload_t object from a single proposal.
Parameters
proposal proposal from which the payload should be built.
Returns
sa_payload_t object
Definition at line 546 of file sa_payload.c.
References add_proposal_v2(), PLV2_SECURITY_ASSOCIATION, and sa_payload_create().
Referenced by build_payloads(), and process_auth_response().
 {
     private_sa_payload_t *this;
     this = (private_sa_payload_t*)sa_payload_create(PLV2_SECURITY_ASSOCIATION);
     add_proposal_v2(this, proposal);
     return &this->public;
 }
sa_payload_t* sa_payload_create_from_proposals_v1 (linked_list_t * proposals, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp, u_int16_t cpi)
Creates an IKEv1 sa_payload_t object from a list of proposals.
Parameters
proposals list of proposals to build the payload from
lifetime lifetime in seconds
lifebytes lifebytes, in bytes
auth authentication method to use, or AUTH_NONE
mode IPsec encapsulation mode, TRANSPORT or TUNNEL
udp ENCAP_UDP to use UDP encapsulation
cpi CPI in case IPComp should be used
Returns
sa_payload_t object
Definition at line 560 of file sa_payload.c.
References compute_length(), FALSE, linked_list_t::get_count, proposal_substructure_t::get_proposal_number, linked_list_t::insert_last, PLV1_SECURITY_ASSOCIATION, proposal_substructure_create_for_ipcomp_v1(), proposal_substructure_create_from_proposals_v1(), sa_payload_create(), proposal_substructure_t::set_is_last_proposal, proposal_substructure_t::set_proposal_number, and TRUE.
Referenced by METHOD(), and sa_payload_create_from_proposal_v1().
 {
     proposal_substructure_t *substruct;
     private_sa_payload_t *this;
     this = (private_sa_payload_t*)sa_payload_create(PLV1_SECURITY_ASSOCIATION);
     if (!proposals || !proposals->get_count(proposals))
     {
         return &this->public;
     }
     /* IKEv1 encodes multiple proposals in a single substructure
      * TODO-IKEv1: Encode ESP+AH proposals in two substructs with same num */
     substruct = proposal_substructure_create_from_proposals_v1(proposals,
                                         lifetime, lifebytes, auth, mode, udp);
     this->proposals->insert_last(this->proposals, substruct);
     substruct->set_is_last_proposal(substruct, FALSE);
     if (cpi)
     {
         u_int8_t proposal_number = substruct->get_proposal_number(substruct);
         substruct = proposal_substructure_create_for_ipcomp_v1(lifetime,
                     lifebytes, cpi, mode, udp, proposal_number);
         this->proposals->insert_last(this->proposals, substruct);
         substruct->set_is_last_proposal(substruct, FALSE);
         /* add the proposals again without IPComp */
         substruct = proposal_substructure_create_from_proposals_v1(proposals,
                                         lifetime, lifebytes, auth, mode, udp);
         substruct->set_proposal_number(substruct, proposal_number + 1);
         this->proposals->insert_last(this->proposals, substruct);
     }
     substruct->set_is_last_proposal(substruct, TRUE);
     compute_length(this);
     return &this->public;
 }
sa_payload_t* sa_payload_create_from_proposals_v2 (linked_list_t * proposals)
Creates an IKEv2 sa_payload_t object from a list of proposals.
Parameters
proposals list of proposals to build the payload from
Returns
sa_payload_t object
Definition at line 526 of file sa_payload.c.
References add_proposal_v2(), linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, PLV2_SECURITY_ASSOCIATION, proposal, and sa_payload_create().
Referenced by build_payloads(), and METHOD().
 {
     private_sa_payload_t *this;
     enumerator_t *enumerator;
     proposal_t *proposal;
     this = (private_sa_payload_t*)sa_payload_create(PLV2_SECURITY_ASSOCIATION);
     enumerator = proposals->create_enumerator(proposals);
     while (enumerator->enumerate(enumerator, &proposal))
     {
         add_proposal_v2(this, proposal);
     }
     enumerator->destroy(enumerator);
     return &this->public;
 }