strongSwan: debug
debug
utils
Macros
#define DEBUG_LEVEL 4
#define DBG0(group, fmt,...) dbg(group, 0, fmt, ##__VA_ARGS__)
#define DBG1(group, fmt,...) dbg(group, 1, fmt, ##__VA_ARGS__)
#define DBG2(group, fmt,...) dbg(group, 2, fmt, ##__VA_ARGS__)
#define DBG3(group, fmt,...) dbg(group, 3, fmt, ##__VA_ARGS__)
#define DBG4(group, fmt,...) dbg(group, 4, fmt, ##__VA_ARGS__)
Typedefs
typedef enum debug_t debug_t
typedef enum level_t level_t
Enumerations
enum debug_t {
DBG_DMN, DBG_MGR, DBG_IKE, DBG_CHD,
DBG_JOB, DBG_CFG, DBG_KNL, DBG_NET,
DBG_ASN, DBG_ENC, DBG_TNC, DBG_IMC,
DBG_IMV, DBG_PTS, DBG_TLS, DBG_APP,
DBG_ESP, DBG_LIB, DBG_MAX, DBG_ANY = DBG_MAX
}
enum level_t {
LEVEL_SILENT = -1, LEVEL_AUDIT = 0, LEVEL_CTRL = 1, LEVEL_DIAG = 2,
LEVEL_RAW = 3, LEVEL_PRIVATE = 4
}
Functions
void dbg_default (debug_t group, level_t level, char *fmt,...)
void dbg_default_set_level (level_t level)
void dbg_default_set_stream (FILE *stream)
Variables
enum_name_t * debug_names
enum_name_t * debug_lower_names
void(* dbg)(debug_t group, level_t level, char *fmt,...)
Detailed Description
Macro Definition Documentation
#define DBG0 (group, fmt, ...) dbg(group, 0, fmt, ##__VA_ARGS__)
debug macros, they call the dbg function hook
Definition at line 111 of file debug.h.
#define DBG1 (group, fmt, ...) dbg(group, 1, fmt, ##__VA_ARGS__)
Definition at line 114 of file debug.h.
#define DBG2 (group, fmt, ...) dbg(group, 2, fmt, ##__VA_ARGS__)
Definition at line 117 of file debug.h.
#define DBG3 (group, fmt, ...) dbg(group, 3, fmt, ##__VA_ARGS__)
Definition at line 120 of file debug.h.
#define DBG4 (group, fmt, ...) dbg(group, 4, fmt, ##__VA_ARGS__)
Definition at line 123 of file debug.h.
#define DEBUG_LEVEL 4
Definition at line 106 of file debug.h.
Typedef Documentation
typedef enum debug_t debug_t
Definition at line 24 of file debug.h.
typedef enum level_t level_t
Definition at line 25 of file debug.h.
Enumeration Type Documentation
enum debug_t
Debug message group.
Enumerator
DBG_DMN
daemon specific
DBG_MGR
IKE_SA_MANAGER
DBG_IKE
IKE_SA
DBG_CHD
CHILD_SA
DBG_JOB
job processing
DBG_CFG
configuration backends
DBG_KNL
kernel interface
DBG_NET
networking/sockets
DBG_ASN
low-level encoding/decoding (ASN.1, X.509 etc.)
DBG_ENC
message encoding/decoding
DBG_TNC
trusted network connect
DBG_IMC
integrity measurement client
DBG_IMV
integrity measurement verifier
DBG_PTS
platform trust service
DBG_TLS
libtls
DBG_APP
applications other than daemons
DBG_ESP
libipsec
DBG_LIB
libstrongswan
DBG_MAX
number of groups
DBG_ANY
pseudo group with all groups
Definition at line 34 of file debug.h.
              {
     DBG_DMN,
     DBG_MGR,
     DBG_IKE,
     DBG_CHD,
     DBG_JOB,
     DBG_CFG,
     DBG_KNL,
     DBG_NET,
     DBG_ASN,
     DBG_ENC,
     DBG_TNC,
     DBG_IMC,
     DBG_IMV,
     DBG_PTS,
     DBG_TLS,
     DBG_APP,
     DBG_ESP,
     DBG_LIB,
     DBG_MAX,
     DBG_ANY = DBG_MAX,
 };
enum level_t
Debug levels used to control output verbosity.
Enumerator
LEVEL_SILENT
absolutely silent
LEVEL_AUDIT
most important auditing logs
LEVEL_CTRL
control flow
LEVEL_DIAG
diagnose problems
LEVEL_RAW
raw binary blobs
LEVEL_PRIVATE
including sensitive data (private keys)
Definition at line 90 of file debug.h.
              {
     LEVEL_SILENT = -1,
     LEVEL_AUDIT =   0,
     LEVEL_CTRL =    1,
     LEVEL_DIAG =    2,
     LEVEL_RAW =     3,
     LEVEL_PRIVATE = 4,
 };
Function Documentation
void dbg_default (debug_t group, level_t level, char * fmt, ...)
default logging function
default dbg function which printf all to stderr
Definition at line 75 of file debug.c.
References default_level, default_stream, fprintf, and vfprintf.
 {
     if (!default_stream)
     {
         default_stream = stderr;
     }
     if (level <= default_level)
     {
         va_list args;
         va_start(args, fmt);
         vfprintf(default_stream, fmt, args);
         fprintf(default_stream, "\n");
         va_end(args);
     }
 }
void dbg_default_set_level (level_t level)
set the level logged by dbg_default()
set the level logged by the default stderr logger
Definition at line 95 of file debug.c.
References default_level.
Referenced by command_getopt(), main(), process_common_opts(), test_runner_run(), and vici_init().
 {
     default_level = level;
 }
void dbg_default_set_stream (FILE * stream)
set the stream logged by dbg_default() to
Definition at line 103 of file debug.c.
References default_stream.
 {
     default_stream = stream;
 }
Variable Documentation
void(* dbg)(debug_t group, level_t level, char *fmt,...)
dbg function hook, uses dbg_default() by default
The registered debug hook.
Definition at line 111 of file debug.c.
enum_name_t* debug_lower_names
short names of debug message group, lower case.
Referenced by CALLBACK(), load_file_logger(), load_log_levels(), and load_sys_logger().
enum_name_t* debug_names
short names of debug message group.
Referenced by dbg_stderr(), dbg_syslog(), log_vici(), METHOD(), stroke_loglevel(), and xml_callback().