strongSwan: eap_sim_file_triplets
eap_sim_file_triplets
eap_sim_file
Classes
struct eap_sim_file_triplets_t
Typedefs
typedef struct
eap_sim_file_triplets_t eap_sim_file_triplets_t
Functions
eap_sim_file_triplets_t * eap_sim_file_triplets_create (char *file)
Detailed Description
Typedef Documentation
typedef struct eap_sim_file_triplets_t eap_sim_file_triplets_t
Definition at line 26 of file eap_sim_file_triplets.h.
Function Documentation
eap_sim_file_triplets_t* eap_sim_file_triplets_create (char * file)
Create a eap_sim_file_triplets instance.
Parameters
file triplet file to read from
See header
Definition at line 244 of file eap_sim_file_triplets.c.
References destroy(), INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, and read_triplets().
Referenced by load_triplets().
 {
     private_eap_sim_file_triplets_t *this;
     INIT(this,
         .public = {
             .create_enumerator = _create_enumerator,
             .destroy = _destroy,
         },
         .triplets = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     if (!read_triplets(this, file))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }