strongSwan: args.h File Reference
args.h File Reference
#include "keywords.h"
Functions
bool assign_arg (kw_token_t token, kw_token_t first, char *key, char *value, void *base, bool *assigned)
void free_args (kw_token_t first, kw_token_t last, void *base)
bool cmp_args (kw_token_t first, kw_token_t last, void *base1, void *base2)
Function Documentation
bool assign_arg (kw_token_t token, kw_token_t first, char * key, char * value, void * base, bool * assigned)
Definition at line 224 of file args.c.
References ARG_ENUM, ARG_NONE, ARG_PCNT, ARG_STR, ARG_TIME, ARG_UBIN, ARG_UINT, ARG_ULLI, ARG_ULNG, b, cp, DBG1, DBG3, DBG_APP, FALSE, free(), list, token_info_t::list, LST_bool, match(), offset, strdupnull(), streq(), TRUE, and type.
Referenced by kw_end(), load_ca(), load_conn(), and load_setup().
 {
     char *p = (char*)base + token_info[token].offset;
     const char **list = token_info[token].list;
     int index = -1;  /* used for enumeration arguments */
     *assigned = FALSE;
     DBG3(DBG_APP, "  %s=%s", key, value);
     /* is there a keyword list? */
     if (list != NULL)
     {
         bool match = FALSE;
         while (*list != NULL && !match)
         {
             index++;
             match = streq(value, *list++);
         }
         if (!match)
         {
             DBG1(DBG_APP, "# bad value: %s=%s", key, value);
             return FALSE;
         }
     }
     switch (token_info[token].type)
     {
         case ARG_NONE:
             DBG1(DBG_APP, "# option '%s' not supported yet", key);
             return FALSE;
         case ARG_ENUM:
         {
             if (index < 0)
             {
                 DBG1(DBG_APP, "# bad enumeration value: %s=%s (%d)",
                      key, value, index);
                 return FALSE;
             }
             if (token_info[token].list == LST_bool)
             {
                 bool *b = (bool *)p;
                 *b = (index > 0);
             }
             else
             {   /* FIXME: this is not entirely correct as the args are enums */
                 int *i = (int *)p;
                 *i = index;
             }
             break;
         }
         case ARG_UINT:
         {
             char *endptr;
             u_int *u = (u_int *)p;
             *u = strtoul(value, &endptr, 10);
             if (*endptr != '\0')
             {
                 DBG1(DBG_APP, "# bad integer value: %s=%s", key, value);
                 return FALSE;
             }
             break;
         }
         case ARG_ULNG:
         case ARG_PCNT:
         {
             char *endptr;
             unsigned long *l = (unsigned long *)p;
             *l = strtoul(value, &endptr, 10);
             if (token_info[token].type == ARG_ULNG)
             {
                 if (*endptr != '\0')
                 {
                     DBG1(DBG_APP, "# bad integer value: %s=%s", key, value);
                     return FALSE;
                 }
             }
             else
             {
                 if ((*endptr != '%') || (endptr[1] != '\0') || endptr == value)
                 {
                     DBG1(DBG_APP, "# bad percent value: %s=%s", key, value);
                     return FALSE;
                 }
             }
             break;
         }
         case ARG_ULLI:
         {
             char *endptr;
             unsigned long long *ll = (unsigned long long *)p;
             *ll = strtoull(value, &endptr, 10);
             if (*endptr != '\0')
             {
                 DBG1(DBG_APP, "# bad integer value: %s=%s", key, value);
                 return FALSE;
             }
             break;
         }
         case ARG_UBIN:
         {
             char *endptr;
             u_int *u = (u_int *)p;
             *u = strtoul(value, &endptr, 2);
             if (*endptr != '\0')
             {
                 DBG1(DBG_APP, "# bad binary value: %s=%s", key, value);
                 return FALSE;
             }
             break;
         }
         case ARG_TIME:
         {
             char *endptr;
             time_t *t = (time_t *)p;
             *t = strtoul(value, &endptr, 10);
             /* time in seconds? */
             if (*endptr == '\0' || (*endptr == 's' && endptr[1] == '\0'))
             {
                 break;
             }
             if (endptr[1] == '\0')
             {
                 if (*endptr == 'm')  /* time in minutes? */
                 {
                     *t *= 60;
                     break;
                 }
                 if (*endptr == 'h')  /* time in hours? */
                 {
                     *t *= 3600;
                     break;
                 }
                 if (*endptr == 'd')  /* time in days? */
                 {
                     *t *= 3600*24;
                     break;
                 }
             }
             DBG1(DBG_APP, "# bad duration value: %s=%s", key, value);
             return FALSE;
         }
         case ARG_STR:
         {
             char **cp = (char **)p;
             /* free any existing string */
             free(*cp);
             /* assign the new string */
             *cp = strdupnull(value);
             break;
         }
         default:
             return TRUE;
     }
     *assigned = TRUE;
     return TRUE;
 }
bool cmp_args (kw_token_t first, kw_token_t last, void * base1, void * base2)
Definition at line 427 of file args.c.
References ARG_ENUM, ARG_PCNT, ARG_STR, ARG_TIME, ARG_UINT, ARG_ULLI, ARG_ULNG, FALSE, list, LST_bool, offset, TRUE, and type.
Referenced by starter_cmp_ca(), starter_cmp_conn(), and starter_cmp_end().
 {
     kw_token_t token;
     for (token = first; token <= last; token++)
     {
         char *p1 = (char*)base1 + token_info[token].offset;
         char *p2 = (char*)base2 + token_info[token].offset;
         switch (token_info[token].type)
         {
             case ARG_ENUM:
             {
                 if (token_info[token].list == LST_bool)
                 {
                     bool *b1 = (bool *)p1;
                     bool *b2 = (bool *)p2;
                     if (*b1 != *b2)
                     {
                         return FALSE;
                     }
                 }
                 else
                 {
                     int *i1 = (int *)p1;
                     int *i2 = (int *)p2;
                     if (*i1 != *i2)
                     {
                         return FALSE;
                     }
                 }
                 break;
             }
             case ARG_UINT:
             {
                 u_int *u1 = (u_int *)p1;
                 u_int *u2 = (u_int *)p2;
                 if (*u1 != *u2)
                 {
                     return FALSE;
                 }
                 break;
             }
             case ARG_ULNG:
             case ARG_PCNT:
             {
                 unsigned long *l1 = (unsigned long *)p1;
                 unsigned long *l2 = (unsigned long *)p2;
                 if (*l1 != *l2)
                 {
                     return FALSE;
                 }
                 break;
             }
             case ARG_ULLI:
             {
                 unsigned long long *ll1 = (unsigned long long *)p1;
                 unsigned long long *ll2 = (unsigned long long *)p2;
                 if (*ll1 != *ll2)
                 {
                     return FALSE;
                 }
                 break;
             }
             case ARG_TIME:
             {
                 time_t *t1 = (time_t *)p1;
                 time_t *t2 = (time_t *)p2;
                 if (*t1 != *t2)
                 {
                     return FALSE;
                 }
                 break;
             }
             case ARG_STR:
             {
                 char **cp1 = (char **)p1;
                 char **cp2 = (char **)p2;
                 if (*cp1 == NULL && *cp2 == NULL)
                 {
                     break;
                 }
                 if (*cp1 == NULL || *cp2 == NULL || strcmp(*cp1, *cp2) != 0)
                 {
                     return FALSE;
                 }
                 break;
             }
             default:
                 break;
         }
     }
     return TRUE;
 }
void free_args (kw_token_t first, kw_token_t last, void * base)
Definition at line 400 of file args.c.
References ARG_STR, cp, free(), offset, and type.
Referenced by confread_free(), confread_free_ca(), and confread_free_conn().
 {
     kw_token_t token;
     for (token = first; token <= last; token++)
     {
         char *p = (char*)base + token_info[token].offset;
         switch (token_info[token].type)
         {
             case ARG_STR:
             {
                 char **cp = (char **)p;
                 free(*cp);
                 *cp = NULL;
                 break;
             }
             default:
                 break;
         }
     }
 }