strongSwan: ike_cfg_t Struct Reference
ike_cfg_t Struct Reference
ike_cfg
#include "ike_cfg.h"
Public Attributes
ike_version_t(* get_version)(ike_cfg_t *this)
host_t *(* resolve_me)(ike_cfg_t *this, int family)
host_t *(* resolve_other)(ike_cfg_t *this, int family)
u_int(* match_me)(ike_cfg_t *this, host_t *host)
u_int(* match_other)(ike_cfg_t *this, host_t *host)
char *(* get_my_addr)(ike_cfg_t *this)
char *(* get_other_addr)(ike_cfg_t *this)
u_int16_t(* get_my_port)(ike_cfg_t *this)
u_int16_t(* get_other_port)(ike_cfg_t *this)
u_int8_t(* get_dscp)(ike_cfg_t *this)
void(* add_proposal)(ike_cfg_t *this, proposal_t *proposal)
linked_list_t *(* get_proposals)(ike_cfg_t *this)
proposal_t *(* select_proposal)(ike_cfg_t *this, linked_list_t *proposals, bool private)
bool(* send_certreq)(ike_cfg_t *this)
bool(* force_encap)(ike_cfg_t *this)
fragmentation_t(* fragmentation)(ike_cfg_t *this)
diffie_hellman_group_t(* get_dh_group)(ike_cfg_t *this)
bool(* equals)(ike_cfg_t *this, ike_cfg_t *other)
ike_cfg_t *(* get_ref)(ike_cfg_t *this)
void(* destroy)(ike_cfg_t *this)
Detailed Description
An ike_cfg_t defines the rules to set up an IKE_SA.
See Also
peer_cfg_t to get an overview over the configurations.
Definition at line 71 of file ike_cfg.h.
Member Data Documentation
void(* ike_cfg_t::add_proposal)(ike_cfg_t *this, proposal_t *proposal)
Adds a proposal to the list.
The first added proposal has the highest priority, the last added the lowest. It is safe to add NULL as proposal, which has no effect.
Parameters
proposal proposal to add, or NULL
Definition at line 156 of file ike_cfg.h.
Referenced by add_ike_proposals(), add_proposals(), CALLBACK(), connect_(), create_peer_cfg(), generate_config(), initiate_connection(), load_ike_config(), METHOD(), and setup_tunnel().
void(* ike_cfg_t::destroy)(ike_cfg_t *this)
Destroys a ike_cfg_t object.
Decrements the internal reference counter and destroys the ike_cfg when it reaches zero.
Definition at line 228 of file ike_cfg.h.
Referenced by assert_family(), and METHOD().
bool(* ike_cfg_t::equals)(ike_cfg_t *this, ike_cfg_t *other)
Check if two IKE configs are equal.
Parameters
other other to check for equality
Returns
TRUE if other equal to this
Definition at line 213 of file ike_cfg.h.
Referenced by merge_config(), and METHOD().
bool(* ike_cfg_t::force_encap)(ike_cfg_t *this)
Enforce UDP encapsulation by faking NATD notifies?
Returns
TRUE to enforce UDP encapsulation
Definition at line 191 of file ike_cfg.h.
Referenced by force_encap().
fragmentation_t(* ike_cfg_t::fragmentation)(ike_cfg_t *this)
Use proprietary IKEv1 fragmentation
Returns
TRUE to use fragmentation
Definition at line 198 of file ike_cfg.h.
Referenced by build().
diffie_hellman_group_t(* ike_cfg_t::get_dh_group)(ike_cfg_t *this)
Get the DH group to use for IKE_SA setup.
Returns
dh group to use for initialization
Definition at line 205 of file ike_cfg.h.
u_int8_t(* ike_cfg_t::get_dscp)(ike_cfg_t *this)
Get the DSCP value to use for IKE packets send from connections.
Returns
DSCP value
Definition at line 145 of file ike_cfg.h.
Referenced by set_dscp().
char*(* ike_cfg_t::get_my_addr)(ike_cfg_t *this)
Get own address.
Returns
string of address/DNS name
Definition at line 117 of file ike_cfg.h.
Referenced by build_peer_cfg(), CALLBACK(), and METHOD().
u_int16_t(* ike_cfg_t::get_my_port)(ike_cfg_t *this)
Get the port to use as our source port.
Returns
source address port, host order
Definition at line 131 of file ike_cfg.h.
Referenced by METHOD().
char*(* ike_cfg_t::get_other_addr)(ike_cfg_t *this)
Get peer's address.
Returns
string of address/DNS name
Definition at line 124 of file ike_cfg.h.
Referenced by CALLBACK(), and METHOD().
u_int16_t(* ike_cfg_t::get_other_port)(ike_cfg_t *this)
Get the port to use as destination port.
Returns
destination address, host order
Definition at line 138 of file ike_cfg.h.
Referenced by METHOD().
linked_list_t*(* ike_cfg_t::get_proposals)(ike_cfg_t *this)
Returns a list of all supported proposals.
Returned list and its proposals must be destroyed after use.
Returns
list containing all the proposals
Definition at line 165 of file ike_cfg.h.
ike_cfg_t*(* ike_cfg_t::get_ref)(ike_cfg_t *this)
Increase reference count.
Returns
reference to this
Definition at line 220 of file ike_cfg.h.
Referenced by METHOD().
ike_version_t(* ike_cfg_t::get_version)(ike_cfg_t *this)
Get the IKE version to use with this configuration.
Returns
IKE major version
Definition at line 78 of file ike_cfg.h.
Referenced by get_ike_match().
u_int(* ike_cfg_t::match_me)(ike_cfg_t *this, host_t *host)
Check how good a host matches to the configured local address.
Parameters
host host to check match quality
Returns
quality of the match, 0 if not matching at all
Definition at line 102 of file ike_cfg.h.
Referenced by get_ike_match().
u_int(* ike_cfg_t::match_other)(ike_cfg_t *this, host_t *host)
Check how good a host matches to the configured remote address.
Parameters
host host to check match quality
Returns
quality of the match, 0 if not matching at all
Definition at line 110 of file ike_cfg.h.
Referenced by get_ike_match().
host_t*(* ike_cfg_t::resolve_me)(ike_cfg_t *this, int family)
Resolve the local address to use for initiation.
Parameters
family address family to prefer, or AF_UNSPEC
Returns
resolved host, NULL on error
Definition at line 86 of file ike_cfg.h.
Referenced by METHOD().
host_t*(* ike_cfg_t::resolve_other)(ike_cfg_t *this, int family)
Resolve the remote address to use for initiation.
Parameters
family address family to prefer, or AF_UNSPEC
Returns
resolved host, NULL on error
Definition at line 94 of file ike_cfg.h.
Referenced by METHOD().
proposal_t*(* ike_cfg_t::select_proposal)(ike_cfg_t *this, linked_list_t *proposals, bool private)
Select a proposed from suggested proposals.
Returned proposal must be destroyed after use.
Parameters
proposals list of proposals to select from
private accept algorithms from a private range
Returns
selected proposal, or NULL if none matches.
Definition at line 176 of file ike_cfg.h.
bool(* ike_cfg_t::send_certreq)(ike_cfg_t *this)
Should we send a certificate request in IKE_SA_INIT?
Returns
certificate request sending policy
Definition at line 184 of file ike_cfg.h.
Referenced by build_certreqs().
The documentation for this struct was generated from the following file:
ike_cfg.h