strongSwan: load_tester.c File Reference
load_tester.c File Reference
#include "load_tester_control.h"
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
Functions
static FILE * make_connection ()
static int initiate (unsigned int count, unsigned int delay)
int main (int argc, char *argv[])
Function Documentation
static int initiate (unsigned int count, unsigned int delay) static
Initiate load-tests
Definition at line 65 of file load_tester.c.
References c, fprintf, and make_connection().
Referenced by main().
 {
     FILE *stream;
     char c;
     stream = make_connection();
     if (!stream)
     {
         return 1;
     }
     fprintf(stream, "%u %u\n", count, delay);
     while (1)
     {
         fflush(stream);
         c = fgetc(stream);
         if (c == EOF)
         {
             break;
         }
         if (fputc(c, stdout) == EOF)
         {
             break;
         }
         fflush(stdout);
     }
     fclose(stream);
     return 0;
 }
int main (int argc, char * argv[])
Definition at line 96 of file load_tester.c.
References fprintf, and initiate().
 {
     if (argc >= 3 && strcmp(argv[1], "initiate") == 0)
     {
         return initiate(atoi(argv[2]), argc > 3 ? atoi(argv[3]) : 0);
     }
     fprintf(stderr, "Usage:\n");
     fprintf(stderr, "  %s initiate <count> [<delay in ms>]\n", argv[0]);
     return 1;
 }
static FILE* make_connection () static
Connect to the daemon, return stream
Definition at line 30 of file load_tester.c.
References close, connect, fprintf, LOAD_TESTER_SOCKET, socket, and strerror.
Referenced by initiate().
 {
     struct sockaddr_un addr;
     FILE *stream;
     int fd;
     addr.sun_family = AF_UNIX;
     strcpy(addr.sun_path, LOAD_TESTER_SOCKET);
     fd = socket(AF_UNIX, SOCK_STREAM, 0);
     if (fd < 0)
     {
         fprintf(stderr, "opening socket failed: %s\n", strerror(errno));
         return NULL;
     }
     if (connect(fd, (struct sockaddr *)&addr,
             offsetof(struct sockaddr_un, sun_path) + strlen(addr.sun_path)) < 0)
     {
         fprintf(stderr, "connecting to %s failed: %s\n",
                 LOAD_TESTER_SOCKET, strerror(errno));
         close(fd);
         return NULL;
     }
     stream = fdopen(fd, "r+");
     if (!stream)
     {
         close(fd);
         return NULL;
     }
     return stream;
 }