strongSwan: simaka_provider_t Struct Reference
simaka_provider_t Struct Reference
simaka_provider
#include "simaka_provider.h"
Public Attributes
bool(* get_triplet)(simaka_provider_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
bool(* get_quintuplet)(simaka_provider_t *this, identification_t *id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int *xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
bool(* resync)(simaka_provider_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
identification_t *(* is_pseudonym)(simaka_provider_t *this, identification_t *id)
identification_t *(* gen_pseudonym)(simaka_provider_t *this, identification_t *id)
identification_t *(* is_reauth)(simaka_provider_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
identification_t *(* gen_reauth)(simaka_provider_t *this, identification_t *id, char mk[HASH_SIZE_SHA1])
Detailed Description
Interface for a triplet/quintuplet provider (used as EAP server).
A SIM provider hands out triplets for SIM authentication and quintuplets for AKA authentication. Multiple SIM provider instances can serve as authentication backend to authenticate clients using SIM/AKA. An implementation supporting only one of SIM/AKA authentication may implement the other methods with return_false().
Definition at line 39 of file simaka_provider.h.
Member Data Documentation
identification_t*(* simaka_provider_t::gen_pseudonym)(simaka_provider_t *this, identification_t *id)
Generate a pseudonym identitiy for a given peer identity.
Parameters
id permanent identity to generate a pseudonym for
Returns
generated pseudonym, NULL to not use a pseudonym identity
Definition at line 103 of file simaka_provider.h.
Referenced by METHOD().
identification_t*(* simaka_provider_t::gen_reauth)(simaka_provider_t *this, identification_t *id, char mk[HASH_SIZE_SHA1])
Generate a fast reauthentication identity, associated to a master key.
Parameters
id permanent peer identity
mk master key to store along with generated identity
Returns
fast reauthentication identity, NULL to not use reauth
Definition at line 124 of file simaka_provider.h.
Referenced by METHOD().
bool(* simaka_provider_t::get_quintuplet)(simaka_provider_t *this, identification_t *id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int *xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
Create a challenge for AKA authentication.
The XRES value is the only one with variable length. Pass a buffer of at least AKA_RES_MAX, the actual number of bytes is written to the xres_len value. While the standard would allow any bit length between 32 and 128 bits, we support only full bytes for now.
Parameters
id permanent identity of peer to create challenge for
rand buffer receiving random value rand
xres buffer receiving expected authentication result xres
xres_len nubmer of bytes written to xres buffer
ck buffer receiving encryption key ck
ik buffer receiving integrity key ik
autn authentication token autn
Returns
TRUE if quintuplet generated successfully
Definition at line 71 of file simaka_provider.h.
Referenced by METHOD().
bool(* simaka_provider_t::get_triplet)(simaka_provider_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
Create a challenge for SIM authentication.
Parameters
id permanent identity of peer to gen triplet for
rand RAND output buffer, fixed size 16 bytes
sres SRES output buffer, fixed size 4 byte
kc KC output buffer, fixed size 8 bytes
Returns
TRUE if triplet received, FALSE otherwise
Definition at line 50 of file simaka_provider.h.
Referenced by METHOD().
identification_t*(* simaka_provider_t::is_pseudonym)(simaka_provider_t *this, identification_t *id)
Check if peer uses a pseudonym, get permanent identity.
Parameters
id pseudonym identity candidate
Returns
permanent identity, NULL if id not a pseudonym
Definition at line 94 of file simaka_provider.h.
Referenced by METHOD().
identification_t*(* simaka_provider_t::is_reauth)(simaka_provider_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
Check if peer uses reauthentication, retrieve reauth parameters.
Parameters
id reauthentication identity (candidate)
mk buffer receiving master key MK
counter pointer receiving current counter value, host order
Returns
permanent identity, NULL if id not a reauth identity
Definition at line 114 of file simaka_provider.h.
Referenced by METHOD().
bool(* simaka_provider_t::resync)(simaka_provider_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
Process AKA resynchroniusation request of a peer.
Parameters
id permanent identity of peer requesting resynchronisation
rand random value rand
auts synchronization parameter auts
Returns
TRUE if resynchronized successfully
Definition at line 85 of file simaka_provider.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
simaka_provider.h