strongSwan: path
path
utils
Macros
#define DIRECTORY_SEPARATOR "/"
Functions
char * path_dirname (const char *path)
char * path_basename (const char *path)
bool path_absolute (const char *path)
bool mkdir_p (const char *path, mode_t mode)
Detailed Description
Macro Definition Documentation
#define DIRECTORY_SEPARATOR "/"
Directory separator character in paths on this platform
Definition at line 31 of file path.h.
Referenced by add_file_key_value(), add_file_list_key(), get_separator(), METHOD(), path_absolute(), path_basename(), and path_dirname().
Function Documentation
bool mkdir_p (const char * path, mode_t mode)
Creates a directory and all required parent directories.
Parameters
path path to the new directory
mode permissions of the new directory/directories
Returns
TRUE on success
Described in header.
Definition at line 123 of file path.c.
References DBG1, DBG_LIB, FALSE, len, snprintf, and TRUE.
Referenced by METHOD().
 {
     int len;
     char *pos, full[PATH_MAX];
     pos = full;
     if (!path || *path == '\0')
     {
         return TRUE;
     }
     len = snprintf(full, sizeof(full)-1, "%s", path);
     if (len < 0 || len >= sizeof(full)-1)
     {
         DBG1(DBG_LIB, "path string %s too long", path);
         return FALSE;
     }
     /* ensure that the path ends with a '/' */
     if (full[len-1] != '/')
     {
         full[len++] = '/';
         full[len] = '\0';
     }
     /* skip '/' at the beginning */
     while (*pos == '/')
     {
         pos++;
     }
     while ((pos = strchr(pos, '/')))
     {
         *pos = '\0';
         if (access(full, F_OK) < 0)
         {
 #ifdef WIN32
             if (_mkdir(full) < 0)
 #else
             if (mkdir(full, mode) < 0)
 #endif
             {
                 DBG1(DBG_LIB, "failed to create directory %s", full);
                 return FALSE;
             }
         }
         *pos = '/';
         pos++;
     }
     return TRUE;
 }
bool path_absolute (const char * path)
Check if a given path is absolute.
Parameters
path path to check
Returns
TRUE if absolute, FALSE if relative
Described in header.
Definition at line 96 of file path.c.
References DIRECTORY_SEPARATOR, FALSE, strpfx(), and TRUE.
Referenced by add_file_key_value(), add_file_list_key(), METHOD(), and START_TEST().
 {
     if (!path)
     {
         return FALSE;
     }
 #ifdef WIN32
     if (strpfx(path, "\\\\"))
     {   /* UNC */
         return TRUE;
     }
     if (strlen(path) && isalpha(path[0]) && path[1] == ':')
     {   /* drive letter */
         return TRUE;
     }
 #else /* !WIN32 */
     if (path[0] == DIRECTORY_SEPARATOR[0])
     {
         return TRUE;
     }
 #endif
     return FALSE;
 }
char* path_basename (const char * path)
Like basename(3) returns the filename part of the given null-terminated path, i.e. the part following the final '/' (or '.' if path is empty or NULL). Trailing '/' are not counted as part of the pathname.
The difference is that it does this in a thread-safe manner (i.e. it does not use static buffers) and does not modify the original path.
Parameters
path original pathname
Returns
allocated filename component
Described in header.
Definition at line 67 of file path.c.
References DIRECTORY_SEPARATOR, memrchr, strdup, and strndup().
Referenced by do_args(), METHOD(), pts_file_meas_create_from_path(), and START_TEST().
 {
     char *pos, *trail = NULL;
     if (!path || !*path)
     {
         return strdup(".");
     }
     pos = strrchr(path, DIRECTORY_SEPARATOR[0]);
     if (pos && !pos[1])
     {   /* if path ends with slashes we have to look beyond them */
         while (pos > path && *pos == DIRECTORY_SEPARATOR[0])
         {   /* skip trailing slashes */
             pos--;
         }
         if (pos == path && *pos == DIRECTORY_SEPARATOR[0])
         {   /* contains only slashes */
             return strdup(DIRECTORY_SEPARATOR);
         }
         trail = pos + 1;
         pos = memrchr(path, DIRECTORY_SEPARATOR[0], trail - path);
     }
     pos = pos ? pos + 1 : (char*)path;
     return trail ? strndup(pos, trail - pos) : strdup(pos);
 }
char* path_dirname (const char * path)
Like dirname(3) returns the directory part of the given null-terminated pathname, up to but not including the final '/' (or '.' if no '/' is found). Trailing '/' are not counted as part of the pathname.
The difference is that it does this in a thread-safe manner (i.e. it does not use static buffers) and does not modify the original path.
Parameters
path original pathname
Returns
allocated directory component
Described in header.
Definition at line 30 of file path.c.
References chunk_clone, chunk_from_chars, DIRECTORY_SEPARATOR, memrchr, strdup, and strndup().
Referenced by do_args(), load_configs(), load_secrets(), METHOD(), and START_TEST().
 {
     char *pos;
     pos = path ? strrchr(path, DIRECTORY_SEPARATOR[0]) : NULL;
     if (pos && !pos[1])
     {   /* if path ends with slashes we have to look beyond them */
         while (pos > path && *pos == DIRECTORY_SEPARATOR[0])
         {   /* skip trailing slashes */
             pos--;
         }
         pos = memrchr(path, DIRECTORY_SEPARATOR[0], pos - path + 1);
     }
     if (!pos)
     {
 #ifdef WIN32
         if (path && strlen(path))
         {
             if ((isalpha(path[0]) && path[1] == ':'))
             {   /* if just a drive letter given, return that as dirname */
                 return chunk_clone(chunk_from_chars(path[0], ':', 0)).ptr;
             }
         }
 #endif
         return strdup(".");
     }
     while (pos > path && *pos == DIRECTORY_SEPARATOR[0])
     {   /* skip superfluous slashes */
         pos--;
     }
     return strndup(path, pos - path + 1);
 }