strongSwan: test_message.c File Reference
test_message.c File Reference
#include <test_suite.h>
#include "../vici_message.h"
#include "../vici_builder.h"
#include <unistd.h>
Classes
struct endecode_test_t
struct endecode_enum_t
Functions
static bool endecode_enumerate (endecode_enum_t *this, vici_type_t *type, char **name, chunk_t *data)
static enumerator_t * endecode_create_enumerator (endecode_test_t *test)
static void compare_vici (enumerator_t *parse, enumerator_t *tmpl)
START_TEST (test_endecode)
END_TEST START_TEST (test_vararg)
END_TEST START_TEST (test_builder)
END_TEST START_TEST (test_builder_fmt)
static END_TEST vici_message_t * build_getter_msg ()
START_TEST (test_get_str)
END_TEST START_TEST (test_get_int)
END_TEST START_TEST (test_get_bool)
END_TEST START_TEST (test_get_value)
END_TEST Suite * message_suite_create ()
Variables
static char blob []
static endecode_test_t endecode_test_simple []
static endecode_test_t endecode_test_nested []
static endecode_test_t endecode_test_list []
static endecode_test_t endecode_test_blobs []
static endecode_test_t * endecode_tests []
Function Documentation
static END_TEST vici_message_t* build_getter_msg () static
Definition at line 310 of file test_message.c.
References chunk_from_str, VICI_END, VICI_KEY_VALUE, vici_message_create_from_args(), VICI_SECTION_END, and VICI_SECTION_START.
Referenced by START_TEST().
 {
     return vici_message_create_from_args(
             VICI_KEY_VALUE, "key1", chunk_from_str("1"),
             VICI_SECTION_START, "section1",
              VICI_KEY_VALUE, "key2", chunk_from_str("0x12"),
              VICI_SECTION_START, "section2",
               VICI_KEY_VALUE, "key3", chunk_from_str("-1"),
              VICI_SECTION_END,
              VICI_KEY_VALUE, "key4", chunk_from_str("asdf"),
             VICI_SECTION_END,
             VICI_KEY_VALUE, "key5", chunk_from_str(""),
             VICI_END);
 }
static void compare_vici (enumerator_t * parse, enumerator_t * tmpl) static
Definition at line 161 of file test_message.c.
References chunk_equals(), ck_assert, ck_assert_int_eq, data, enumerator_t::enumerate, FALSE, name, streq(), TRUE, type, VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_SECTION_END, and VICI_SECTION_START.
Referenced by START_TEST().
 {
     vici_type_t type, ttype;
     char *name, *tname;
     chunk_t data, tdata;;
     while (TRUE)
     {
         ck_assert(parse->enumerate(parse, &type, &name, &data));
         ck_assert(tmpl->enumerate(tmpl, &ttype, &tname, &tdata));
         ck_assert_int_eq(type, ttype);
         switch (type)
         {
             case VICI_END:
                 return;
             case VICI_SECTION_START:
             case VICI_LIST_START:
                 ck_assert(streq(name, tname));
                 break;
             case VICI_LIST_ITEM:
                 ck_assert(chunk_equals(data, tdata));
                 break;
             case VICI_KEY_VALUE:
                 ck_assert(streq(name, tname));
                 ck_assert(chunk_equals(data, tdata));
                 break;
             case VICI_SECTION_END:
             case VICI_LIST_END:
                 break;
             default:
                 ck_assert(FALSE);
                 break;
         }
     }
 }
static enumerator_t* endecode_create_enumerator (endecode_test_t * test) static
Definition at line 146 of file test_message.c.
References destroy(), endecode_enumerate(), free(), INIT, and endecode_enum_t::public.
Referenced by START_TEST().
 {
     endecode_enum_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)endecode_enumerate,
             .destroy = (void*)free,
         },
         .next = test,
     );
     return &enumerator->public;
 }
static bool endecode_enumerate (endecode_enum_t * this, vici_type_t * type, char ** name, chunk_t * data) static
Definition at line 125 of file test_message.c.
References FALSE, next, TRUE, and VICI_END.
Referenced by endecode_create_enumerator().
 {
     if (this->next)
     {
         *type = this->next->type;
         *name = this->next->name;
         *data = this->next->data;
         if (this->next->type == VICI_END)
         {
             this->next = NULL;
         }
         else
         {
             this->next++;
         }
         return TRUE;
     }
     return FALSE;
 }
END_TEST Suite* message_suite_create ()
Definition at line 407 of file test_message.c.
References countof, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("vici message");
     tc = tcase_create("enumerator en/decode");
     tcase_add_loop_test(tc, test_endecode, 0, countof(endecode_tests));
     suite_add_tcase(s, tc);
     tc = tcase_create("vararg encode");
     tcase_add_test(tc, test_vararg);
     suite_add_tcase(s, tc);
     tc = tcase_create("builder encode");
     tcase_add_test(tc, test_builder);
     suite_add_tcase(s, tc);
     tc = tcase_create("builder format encode");
     tcase_add_test(tc, test_builder_fmt);
     suite_add_tcase(s, tc);
     tc = tcase_create("convenience getters");
     tcase_add_test(tc, test_get_str);
     tcase_add_test(tc, test_get_int);
     tcase_add_test(tc, test_get_bool);
     tcase_add_test(tc, test_get_value);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_endecode)
Definition at line 197 of file test_message.c.
References chunk_clone, ck_assert, compare_vici(), vici_message_t::create_enumerator, data, enumerator_t::destroy, vici_message_t::destroy, endecode_create_enumerator(), vici_message_t::get_encoding, m, parse(), TRUE, vici_message_create_from_data(), and vici_message_create_from_enumerator().
 {
     enumerator_t *parse, *tmpl;
     vici_message_t *m;
     chunk_t data;
     tmpl = endecode_create_enumerator(endecode_tests[_i]);
     m = vici_message_create_from_enumerator(tmpl);
     ck_assert(m);
     data = chunk_clone(m->get_encoding(m));
     tmpl = endecode_create_enumerator(endecode_tests[_i]);
     parse = m->create_enumerator(m);
     ck_assert(parse);
     compare_vici(parse, tmpl);
     tmpl->destroy(tmpl);
     parse->destroy(parse);
     m->destroy(m);
     m = vici_message_create_from_data(data, TRUE);
     ck_assert(m);
     tmpl = endecode_create_enumerator(endecode_tests[_i]);
     parse = m->create_enumerator(m);
     ck_assert(parse);
     compare_vici(parse, tmpl);
     tmpl->destroy(tmpl);
     parse->destroy(parse);
     m->destroy(m);
 }
END_TEST START_TEST (test_vararg)
Definition at line 227 of file test_message.c.
References chunk_from_str, ck_assert, compare_vici(), vici_message_t::create_enumerator, enumerator_t::destroy, vici_message_t::destroy, endecode_create_enumerator(), m, parse(), VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, vici_message_create_from_args(), VICI_SECTION_END, and VICI_SECTION_START.
 {
     enumerator_t *parse, *tmpl;
     vici_message_t *m;
     m = vici_message_create_from_args(
         VICI_SECTION_START, "section1",
          VICI_LIST_START, "list1",
           VICI_LIST_ITEM, chunk_from_str("item1"),
           VICI_LIST_ITEM, chunk_from_str("item2"),
          VICI_LIST_END,
          VICI_KEY_VALUE, "key1", chunk_from_str("value1"),
          VICI_SECTION_END,
         VICI_END);
     ck_assert(m);
     tmpl = endecode_create_enumerator(endecode_test_list);
     parse = m->create_enumerator(m);
     ck_assert(parse);
     compare_vici(parse, tmpl);
     m->destroy(m);
     tmpl->destroy(tmpl);
     parse->destroy(parse);
 }
END_TEST START_TEST (test_builder)
Definition at line 254 of file test_message.c.
References vici_builder_t::add, b, chunk_from_str, ck_assert, compare_vici(), vici_message_t::create_enumerator, enumerator_t::destroy, vici_message_t::destroy, endecode_create_enumerator(), vici_builder_t::finalize, m, parse(), vici_builder_create(), VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_SECTION_END, and VICI_SECTION_START.
 {
     enumerator_t *parse, *tmpl;
     vici_message_t *m;
     vici_builder_t *b;
     b = vici_builder_create();
     b->add(b, VICI_SECTION_START, "section1");
     b->add(b,  VICI_LIST_START, "list1");
     b->add(b,   VICI_LIST_ITEM, chunk_from_str("item1"));
     b->add(b,   VICI_LIST_ITEM, chunk_from_str("item2"));
     b->add(b,  VICI_LIST_END);
     b->add(b,  VICI_KEY_VALUE, "key1", chunk_from_str("value1"));
     b->add(b, VICI_SECTION_END);
     m = b->finalize(b);
     ck_assert(m);
     tmpl = endecode_create_enumerator(endecode_test_list);
     parse = m->create_enumerator(m);
     ck_assert(parse);
     compare_vici(parse, tmpl);
     m->destroy(m);
     tmpl->destroy(tmpl);
     parse->destroy(parse);
 }
END_TEST START_TEST (test_builder_fmt)
Definition at line 282 of file test_message.c.
References vici_builder_t::add_kv, vici_builder_t::add_li, b, vici_builder_t::begin_list, vici_builder_t::begin_section, ck_assert, compare_vici(), vici_message_t::create_enumerator, enumerator_t::destroy, vici_message_t::destroy, vici_builder_t::end_list, vici_builder_t::end_section, endecode_create_enumerator(), vici_builder_t::finalize, m, parse(), and vici_builder_create().
 {
     enumerator_t *parse, *tmpl;
     vici_message_t *m;
     vici_builder_t *b;
     b = vici_builder_create();
     b->begin_section(b, "section1");
     b->begin_list(b, "list1");
     b->add_li(b, "item%u", 1);
     b->add_li(b, "%s%u", "item", 2);
     b->end_list(b);
     b->add_kv(b, "key1", "value%u", 1);
     b->end_section(b);
     m = b->finalize(b);
     ck_assert(m);
     tmpl = endecode_create_enumerator(endecode_test_list);
     parse = m->create_enumerator(m);
     ck_assert(parse);
     compare_vici(parse, tmpl);
     m->destroy(m);
     tmpl->destroy(tmpl);
     parse->destroy(parse);
 }
START_TEST (test_get_str)
Definition at line 325 of file test_message.c.
References build_getter_msg(), ck_assert_str_eq, vici_message_t::destroy, vici_message_t::get_str, and m.
 {
     vici_message_t *m;
     m = build_getter_msg();
     ck_assert_str_eq(m->get_str(m, "def", "key1"), "1");
     ck_assert_str_eq(m->get_str(m, "def", "section1.key2"), "0x12");
     ck_assert_str_eq(m->get_str(m, "def", "section%d.section2.key3", 1), "-1");
     ck_assert_str_eq(m->get_str(m, "def", "section1.key4"), "asdf");
     ck_assert_str_eq(m->get_str(m, "def", "key5"), "");
     ck_assert_str_eq(m->get_str(m, "no", "nonexistent"), "no");
     ck_assert_str_eq(m->get_str(m, "no", "n.o.n.e.x.i.s.t.e.n.t"), "no");
     m->destroy(m);
 }
END_TEST START_TEST (test_get_int)
Definition at line 343 of file test_message.c.
References build_getter_msg(), ck_assert_int_eq, vici_message_t::destroy, vici_message_t::get_int, and m.
 {
     vici_message_t *m;
     m = build_getter_msg();
     ck_assert_int_eq(m->get_int(m, 2, "key1"), 1);
     ck_assert_int_eq(m->get_int(m, 2, "section1.key2"), 0x12);
     ck_assert_int_eq(m->get_int(m, 2, "section1.section2.key3"), -1);
     ck_assert_int_eq(m->get_int(m, 2, "section1.key4"), 2);
     ck_assert_int_eq(m->get_int(m, 2, "key5"), 2);
     ck_assert_int_eq(m->get_int(m, 2, "nonexistent"), 2);
     ck_assert_int_eq(m->get_int(m, 2, "n.o.n.e.x.i.s.t.e.n.t"), 2);
     m->destroy(m);
 }
END_TEST START_TEST (test_get_bool)
Definition at line 361 of file test_message.c.
References build_getter_msg(), ck_assert, vici_message_t::destroy, FALSE, vici_message_t::get_bool, m, and TRUE.
 {
     vici_message_t *m;
     m = build_getter_msg();
     ck_assert(m->get_bool(m, TRUE, "key1"));
     ck_assert(m->get_bool(m, FALSE, "key1"));
     ck_assert(m->get_bool(m, TRUE, "section1.key2"));
     ck_assert(m->get_bool(m, TRUE, "section1.section2.key3"));
     ck_assert(m->get_bool(m, TRUE, "section1.key4"));
     ck_assert(m->get_bool(m, TRUE, "key5"));
     ck_assert(m->get_bool(m, TRUE, "nonexistent"));
     ck_assert(m->get_bool(m, TRUE, "n.o.n.e.x.i.s.t.e.n.t"));
     ck_assert(!m->get_bool(m, FALSE, "section1.key2"));
     ck_assert(!m->get_bool(m, FALSE, "section1.section2.key3"));
     ck_assert(!m->get_bool(m, FALSE, "section1.key4"));
     ck_assert(!m->get_bool(m, FALSE, "key5"));
     ck_assert(!m->get_bool(m, FALSE, "nonexistent"));
     ck_assert(!m->get_bool(m, FALSE, "n.o.n.e.x.i.s.t.e.n.t"));
     m->destroy(m);
 }
END_TEST START_TEST (test_get_value)
Definition at line 388 of file test_message.c.
References build_getter_msg(), chunk_empty, chunk_from_chars, chunk_from_str, ck_assert_chunk_eq, vici_message_t::destroy, vici_message_t::get_value, and m.
 {
     vici_message_t *m;
     chunk_t d = chunk_from_chars('d','e','f');
     m = build_getter_msg();
     ck_assert_chunk_eq(m->get_value(m, d, "key1"), chunk_from_str("1"));
     ck_assert_chunk_eq(m->get_value(m, d, "section1.key2"), chunk_from_str("0x12"));
     ck_assert_chunk_eq(m->get_value(m, d, "section1.section2.key3"), chunk_from_str("-1"));
     ck_assert_chunk_eq(m->get_value(m, d, "section1.key4"), chunk_from_str("asdf"));
     ck_assert_chunk_eq(m->get_value(m, d, "key5"), chunk_empty);
     ck_assert_chunk_eq(m->get_value(m, d, "nonexistent"), d);
     ck_assert_chunk_eq(m->get_value(m, d, "n.o.n.e.x.i.s.t.e.n.t"), d);
     m->destroy(m);
 }
Variable Documentation
char blob[] static
Definition at line 26 of file test_message.c.
Referenced by add_attr(), add_certification_state(), add_configuration_state(), asn1_parser_create(), bliss_public_key_load(), build_pub_info(), build_sha1(), decrypt_private_key(), del_attr(), dnskey_public_key_load(), load_from_stream(), main(), METHOD(), openssl_crl_load(), openssl_ec_public_key_load(), openssl_rsa_private_key_load(), openssl_rsa_public_key_load(), openssl_x509_load(), parse_public_key(), pem_to_bin(), pgp_cert_load(), pgp_private_key_load(), pgp_public_key_load(), pkcs11_public_key_load(), pkcs12_decode(), pkcs1_private_key_load(), pkcs1_public_key_load(), pkcs7_data_gen(), pkcs7_enveloped_data_gen(), pkcs7_generic_load(), pkcs7_signed_data_gen(), pkcs8_private_key_load(), pubkey_cert_wrap(), read_key(), sshkey_public_key_load(), START_TEST(), tkm_public_key_load(), x509_ac_load(), x509_cert_load(), x509_crl_load(), x509_ocsp_response_load(), and x509_pkcs10_load().
endecode_test_t endecode_test_blobs[] static
Initial value:
= {
    { VICI_KEY_VALUE,               "key1",     { blob, countof(blob) }     },
    { VICI_SECTION_START,           "section1", {}                          },
    {  VICI_LIST_START,             "list1",    {}                          },
    {   VICI_LIST_ITEM,             NULL,       { blob, countof(blob) }     },
    {   VICI_LIST_ITEM,             NULL,       { blob, countof(blob) }     },
    {  VICI_LIST_END,               NULL,       {}                          },
    {  VICI_KEY_VALUE,              "key2",     { blob, countof(blob) }     },
    { VICI_SECTION_END,             NULL,       {}                          },
    { VICI_END,                     NULL,       {}                          },
}
Definition at line 101 of file test_message.c.
endecode_test_t endecode_test_list[] static
Initial value:
= {
    { VICI_SECTION_START,           "section1", {}                          },
    {  VICI_LIST_START,             "list1",    {}                          },
    {   VICI_LIST_ITEM,             NULL,       { "item1", 5 }              },
    {   VICI_LIST_ITEM,             NULL,       { "item2", 5 }              },
    {  VICI_LIST_END,               NULL,       {}                          },
    {  VICI_KEY_VALUE,              "key1",     { "value1", 6 }             },
    { VICI_SECTION_END,             NULL,       {}                          },
    { VICI_END,                     NULL,       {}                          },
}
Definition at line 90 of file test_message.c.
endecode_test_t endecode_test_nested[] static
Initial value:
= {
    { VICI_SECTION_START,           "section1", {}                          },
    {  VICI_SECTION_START,          "section2", {}                          },
    {   VICI_SECTION_START,         "section3", {}                          },
    {    VICI_KEY_VALUE,            "key1",     { "value1", 6 }             },
    {    VICI_SECTION_START,        "section4", {}                          },
    {     VICI_KEY_VALUE,           "key2",     { "value2", 6 }             },
    {    VICI_SECTION_END,          NULL,       {}                          },
    {   VICI_SECTION_END,           NULL,       {}                          },
    {  VICI_SECTION_END,            NULL,       {}                          },
    {  VICI_KEY_VALUE,              "key3",     { "value3", 6 }             },
    { VICI_SECTION_END,             NULL,       {}                          },
    { VICI_END,                     NULL,       {}                          },
}
Definition at line 75 of file test_message.c.
endecode_test_t endecode_test_simple[] static
Initial value:
= {
    { VICI_SECTION_START,           "section1", {}                          },
    {  VICI_KEY_VALUE,              "key1",     { "value1", 6 }             },
    {  VICI_KEY_VALUE,              "key2",     { "value2", 6 }             },
    { VICI_SECTION_END,             NULL,       {}                          },
    { VICI_END,                     NULL,       {}                          },
}
Definition at line 67 of file test_message.c.
endecode_test_t* endecode_tests[] static
Initial value:
= {
    endecode_test_simple,
    endecode_test_nested,
    endecode_test_list,
    endecode_test_blobs,
}
Definition at line 113 of file test_message.c.