strongSwan: eap_tls.c File Reference
eap_tls.c File Reference
#include "eap_tls.h"
#include <tls_eap.h>
#include <daemon.h>
#include <library.h>
Classes
struct private_eap_tls_t
Macros
#define MAX_MESSAGE_COUNT 32
#define MAX_FRAGMENT_LEN 1024
Typedefs
typedef struct private_eap_tls_t private_eap_tls_t
Functions
METHOD (eap_method_t, initiate, status_t, private_eap_tls_t *this, eap_payload_t **out)
METHOD (eap_method_t, process, status_t, private_eap_tls_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_tls_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_tls_t *this, chunk_t *msk)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_tls_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_tls_t *this, u_int8_t identifier)
METHOD (eap_method_t, is_mutual, bool, private_eap_tls_t *this)
METHOD (eap_method_t, get_auth, auth_cfg_t *, private_eap_tls_t *this)
METHOD (eap_method_t, destroy, void, private_eap_tls_t *this)
static eap_tls_t * eap_tls_create (identification_t *server, identification_t *peer, bool is_server)
eap_tls_t * eap_tls_create_server (identification_t *server, identification_t *peer)
eap_tls_t * eap_tls_create_peer (identification_t *server, identification_t *peer)
Macro Definition Documentation
#define MAX_FRAGMENT_LEN 1024
Default size of a EAP-TLS fragment
Definition at line 44 of file eap_tls.c.
Referenced by eap_tls_create().
#define MAX_MESSAGE_COUNT 32
Maximum number of EAP-TLS messages/fragments allowed
Definition at line 42 of file eap_tls.c.
Referenced by eap_tls_create().
Typedef Documentation
typedef struct private_eap_tls_t private_eap_tls_t
Definition at line 23 of file eap_tls.c.
Function Documentation
static eap_tls_t* eap_tls_create (identification_t * server, identification_t * peer, bool is_server) static
Generic private constructor
Definition at line 128 of file eap_tls.c.
References EAP_TLS, free(), settings_t::get_bool, settings_t::get_int, INIT, lib, MAX_FRAGMENT_LEN, MAX_MESSAGE_COUNT, library_t::ns, library_t::settings, tls, tls_create(), tls_eap_create(), TLS_PURPOSE_EAP_TLS, and TRUE.
Referenced by eap_tls_create_peer(), and eap_tls_create_server().
 {
     private_eap_tls_t *this;
     size_t frag_size;
     int max_msg_count;
     bool include_length;
     tls_t *tls;
     INIT(this,
         .public = {
             .eap_method = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .get_auth = _get_auth,
                 .destroy = _destroy,
             },
         },
     );
     frag_size = lib->settings->get_int(lib->settings,
                     "%s.plugins.eap-tls.fragment_size", MAX_FRAGMENT_LEN,
                     lib->ns);
     max_msg_count = lib->settings->get_int(lib->settings,
                     "%s.plugins.eap-tls.max_message_count", MAX_MESSAGE_COUNT,
                     lib->ns);
     include_length = lib->settings->get_bool(lib->settings,
                     "%s.plugins.eap-tls.include_length", TRUE, lib->ns);
     tls = tls_create(is_server, server, peer, TLS_PURPOSE_EAP_TLS, NULL, NULL);
     this->tls_eap = tls_eap_create(EAP_TLS, tls, frag_size, max_msg_count,
                                                  include_length);
     if (!this->tls_eap)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }
METHOD (eap_method_t , initiate , status_t , private_eap_tls_t * this, eap_payload_t ** out)
Definition at line 46 of file eap_tls.c.
References data, eap_payload_create_data(), FAILED, free(), NEED_MORE, and chunk_t::ptr.
 {
     chunk_t data;
     if (this->tls_eap->initiate(this->tls_eap, &data) == NEED_MORE)
     {
         *out = eap_payload_create_data(data);
         free(data.ptr);
         return NEED_MORE;
     }
     return FAILED;
 }
METHOD (eap_method_t , process , status_t , private_eap_tls_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 60 of file eap_tls.c.
References data, eap_payload_create_data(), free(), eap_payload_t::get_data, NEED_MORE, chunk_t::ptr, and status.
 {
     status_t status;
     chunk_t data;
     data = in->get_data(in);
     status = this->tls_eap->process(this->tls_eap, data, &data);
     if (status == NEED_MORE)
     {
         *out = eap_payload_create_data(data);
         free(data.ptr);
     }
     return status;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_tls_t * this, u_int32_t * vendor)
Definition at line 76 of file eap_tls.c.
References EAP_TLS.
 {
     *vendor = 0;
     return EAP_TLS;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_tls_t * this, chunk_t * msk)
Definition at line 83 of file eap_tls.c.
References FAILED, chunk_t::len, and SUCCESS.
 {
     *msk = this->tls_eap->get_msk(this->tls_eap);
     if (msk->len)
     {
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_tls_t * this)
Definition at line 94 of file eap_tls.c.
 {
     return this->tls_eap->get_identifier(this->tls_eap);
 }
METHOD (eap_method_t , set_identifier , void , private_eap_tls_t * this, u_int8_t identifier)
Definition at line 100 of file eap_tls.c.
 {
     this->tls_eap->set_identifier(this->tls_eap, identifier);
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_tls_t * this)
Definition at line 106 of file eap_tls.c.
References TRUE.
 {
     return TRUE;
 }
METHOD (eap_method_t , get_auth , auth_cfg_t * , private_eap_tls_t * this)
Definition at line 112 of file eap_tls.c.
 {
     return this->tls_eap->get_auth(this->tls_eap);
 }
METHOD (eap_method_t , destroy , void , private_eap_tls_t * this)
Definition at line 118 of file eap_tls.c.
References free().
 {
     this->tls_eap->destroy(this->tls_eap);
     free(this);
 }