strongSwan: swid_tag.c File Reference
swid_tag.c File Reference
#include "swid_tag.h"
Classes
struct private_swid_tag_t
Typedefs
typedef struct private_swid_tag_t private_swid_tag_t
Functions
METHOD (swid_tag_t, get_encoding, chunk_t, private_swid_tag_t *this)
METHOD (swid_tag_t, get_instance_id, chunk_t, private_swid_tag_t *this)
METHOD (swid_tag_t, get_ref, swid_tag_t *, private_swid_tag_t *this)
METHOD (swid_tag_t, destroy, void, private_swid_tag_t *this)
swid_tag_t * swid_tag_create (chunk_t encoding, chunk_t instance_id)
Typedef Documentation
typedef struct private_swid_tag_t private_swid_tag_t
Definition at line 18 of file swid_tag.c.
Function Documentation
METHOD (swid_tag_t , get_encoding , chunk_t , private_swid_tag_t * this)
Definition at line 47 of file swid_tag.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (swid_tag_t , get_instance_id , chunk_t , private_swid_tag_t * this)
Definition at line 53 of file swid_tag.c.
 {
     return this->instance_id;
 }
METHOD (swid_tag_t , get_ref , swid_tag_t * , private_swid_tag_t * this)
Definition at line 59 of file swid_tag.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (swid_tag_t , destroy , void , private_swid_tag_t * this)
Definition at line 66 of file swid_tag.c.
References encoding, free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         free(this->encoding.ptr);
         free(this->instance_id.ptr);
         free(this);
     }
 }