strongSwan: ts_payload
ts_payload
payloads
Classes
struct ts_payload_t
Typedefs
typedef struct ts_payload_t ts_payload_t
Functions
ts_payload_t * ts_payload_create (bool is_initiator)
ts_payload_t * ts_payload_create_from_traffic_selectors (bool is_initiator, linked_list_t *traffic_selectors)
Detailed Description
Typedef Documentation
typedef struct ts_payload_t ts_payload_t
Definition at line 25 of file ts_payload.h.
Function Documentation
ts_payload_t* ts_payload_create (bool is_initiator)
Creates an empty ts_payload_t object.
Parameters
is_initiator TRUE for TSi, FALSE for TSr payload type
Returns
ts_payload_t object
Definition at line 251 of file ts_payload.c.
References INIT, linked_list_create(), and PL_NONE.
Referenced by payload_create(), and ts_payload_create_from_traffic_selectors().
 {
     private_ts_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_initiator = _get_initiator,
             .set_initiator = _set_initiator,
             .get_traffic_selectors = _get_traffic_selectors,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
         .is_initiator = is_initiator,
         .substrs = linked_list_create(),
     );
     return &this->public;
 }
ts_payload_t* ts_payload_create_from_traffic_selectors (bool is_initiator, linked_list_t * traffic_selectors)
Creates ts_payload with a list of traffic_selector_t
Parameters
is_initiator TRUE for TSi, FALSE for TSr payload type
traffic_selectors list of traffic selectors to include
Returns
ts_payload_t object
Definition at line 283 of file ts_payload.c.
References compute_length(), linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, traffic_selector_substructure_create_from_traffic_selector(), and ts_payload_create().
Referenced by build_payloads(), and process_auth_response().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     traffic_selector_substructure_t *subst;
     private_ts_payload_t *this;
     this = (private_ts_payload_t*)ts_payload_create(is_initiator);
     enumerator = traffic_selectors->create_enumerator(traffic_selectors);
     while (enumerator->enumerate(enumerator, &ts))
     {
         subst = traffic_selector_substructure_create_from_traffic_selector(ts);
         this->substrs->insert_last(this->substrs, subst);
     }
     enumerator->destroy(enumerator);
     compute_length(this);
     return &this->public;
 }