strongSwan: certexpire_export.c File Reference
certexpire_export.c File Reference
#include "certexpire_export.h"
#include "certexpire_cron.h"
#include <time.h>
#include <limits.h>
#include <errno.h>
#include <utils/debug.h>
#include <daemon.h>
#include <collections/hashtable.h>
#include <threading/mutex.h>
#include <credentials/certificates/x509.h>
Classes
struct private_certexpire_export_t
struct entry_t
Macros
#define MAX_TRUSTCHAIN_LENGTH 7
Typedefs
typedef struct
private_certexpire_export_t private_certexpire_export_t
Functions
static u_int hash (entry_t *key)
static bool equals (entry_t *a, entry_t *b)
static void export_csv (private_certexpire_export_t *this, char *path, hashtable_t *chains)
METHOD (certexpire_export_t, add, void, private_certexpire_export_t *this, linked_list_t *trustchain, bool local)
static void add_local_certs (private_certexpire_export_t *this)
static void cron_export (private_certexpire_export_t *this)
METHOD (certexpire_export_t, destroy, void, private_certexpire_export_t *this)
certexpire_export_t * certexpire_export_create ()
Macro Definition Documentation
#define MAX_TRUSTCHAIN_LENGTH 7
Maximum number of expiration dates we store (for subject + IM CAs + CA)
Definition at line 101 of file certexpire_export.c.
Referenced by export_csv(), and METHOD().
Typedef Documentation
typedef struct private_certexpire_export_t private_certexpire_export_t
Definition at line 30 of file certexpire_export.c.
Function Documentation
static void add_local_certs (private_certexpire_export_t * this) static
Add trustchains we have a private key for to the list
Definition at line 316 of file certexpire_export.c.
References add(), cert, CERT_X509, credential_manager_t::create_cert_enumerator, library_t::credmgr, enumerator_t::destroy, identification_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, FALSE, credential_manager_t::get_cert, x509_t::get_flags, certificate_t::get_issuer, credential_manager_t::get_private, certificate_t::get_public_key, certificate_t::get_ref, ID_KEY_ID, identification_create_from_encoding(), linked_list_t::insert_last, KEY_ANY, keyid(), KEYID_PUBKEY_INFO_SHA1, lib, linked_list_create(), public, TRUE, and X509_SELF_SIGNED.
Referenced by cron_export().
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     enumerator = lib->credmgr->create_cert_enumerator(lib->credmgr,
                                             CERT_X509, KEY_ANY, NULL, FALSE);
     while (enumerator->enumerate(enumerator, &cert))
     {
         linked_list_t *trustchain;
         private_key_t *private;
         public_key_t *public;
         identification_t *keyid;
         chunk_t chunk;
         x509_t *x509 = (x509_t*)cert;
         trustchain = linked_list_create();
         public = cert->get_public_key(cert);
         if (public)
         {
             if (public->get_fingerprint(public, KEYID_PUBKEY_INFO_SHA1, &chunk))
             {
                 keyid = identification_create_from_encoding(ID_KEY_ID, chunk);
                 private = lib->credmgr->get_private(lib->credmgr,
                                         public->get_type(public), keyid, NULL);
                 keyid->destroy(keyid);
                 if (private)
                 {
                     trustchain->insert_last(trustchain, cert->get_ref(cert));
                     while (!(x509->get_flags(x509) & X509_SELF_SIGNED))
                     {
                         cert = lib->credmgr->get_cert(lib->credmgr, CERT_X509,
                                         KEY_ANY, cert->get_issuer(cert), FALSE);
                         if (!cert)
{
                             break;
                         }
                         x509 = (x509_t*)cert;
                         trustchain->insert_last(trustchain, cert);
                     }
                     private->destroy(private);
                 }
             }
             public->destroy(public);
         }
         add(this, trustchain, TRUE);
         trustchain->destroy_offset(trustchain, offsetof(certificate_t, destroy));
     }
     enumerator->destroy(enumerator);
 }
static void cron_export (private_certexpire_export_t * this) static
Export cached trustchain expiration dates to CSV files
Definition at line 372 of file certexpire_export.c.
References add_local_certs(), and export_csv().
Referenced by certexpire_export_create().
 {
     if (this->local_path)
     {
         if (this->force)
         {
             add_local_certs(this);
         }
         export_csv(this, this->local_path, this->local);
     }
     if (this->remote_path)
     {
         export_csv(this, this->remote_path, this->remote);
     }
 }
static bool equals (entry_t * a, entry_t * b) static
Hashtable equals function
Definition at line 124 of file certexpire_export.c.
References entry_t::id, and streq().
Referenced by certexpire_export_create().
 {
     return streq(a->id, b->id);
 }
static void export_csv (private_certexpire_export_t * this, char * path, hashtable_t * chains) static
Export a single trustchain to a path
Definition at line 132 of file certexpire_export.c.
References hashtable_t::create_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, entry_t::expire, fprintf, free(), hashtable_t::get_count, entry_t::id, localtime_r(), mutex_t::lock, MAX_TRUSTCHAIN_LENGTH, mutex, hashtable_t::remove_at, strerror, and mutex_t::unlock.
Referenced by cron_export(), and METHOD().
 {
     enumerator_t *enumerator;
     char buf[PATH_MAX];
     entry_t *entry;
     FILE *file;
     struct tm tm;
     time_t t;
     int i;
     t = time(NULL);
     localtime_r(&t, &tm);
     strftime(buf, sizeof(buf), path, &tm);
     file = fopen(buf, "a");
     if (file)
     {
         DBG1(DBG_CFG, "exporting expiration dates of %d trustchain%s to '%s'",
              chains->get_count(chains),
              chains->get_count(chains) == 1 ? "" : "s", buf);
         this->mutex->lock(this->mutex);
         enumerator = chains->create_enumerator(chains);
         while (enumerator->enumerate(enumerator, NULL, &entry))
         {
             fprintf(file, "%s%s", entry->id, this->separator);
             for (i = 0; i < MAX_TRUSTCHAIN_LENGTH; i++)
             {
                 if (entry->expire[i])
                 {
                     localtime_r(&entry->expire[i], &tm);
                     strftime(buf, sizeof(buf), this->format, &tm);
                     fprintf(file, "%s", buf);
                 }
                 if (i == MAX_TRUSTCHAIN_LENGTH - 1)
                 {
                     fprintf(file, "\n");
                 }
                 else if (entry->expire[i])
                 {
                     fprintf(file, "%s", this->separator);
                 }
                 else if (this->fixed_fields)
                 {
                     fprintf(file, "%s%s", this->empty_string, this->separator);
                 }
             }
             chains->remove_at(chains, enumerator);
             free(entry);
         }
         enumerator->destroy(enumerator);
         this->mutex->unlock(this->mutex);
         fclose(file);
     }
     else
     {
         DBG1(DBG_CFG, "opening CSV file '%s' failed: %s", buf, strerror(errno));
     }
 }
static u_int hash (entry_t * key) static
Hashtable hash function
Definition at line 116 of file certexpire_export.c.
References chunk_create(), chunk_hash(), and entry_t::id.
Referenced by certexpire_export_create().
 {
     return chunk_hash(chunk_create(key->id, strlen(key->id)));
 }
METHOD (certexpire_export_t , add , void , private_certexpire_export_t * this, linked_list_t * trustchain, bool local)
Definition at line 192 of file certexpire_export.c.
References cert, CERT_X509, count, linked_list_t::create_enumerator, x509_t::create_subjectAltName_enumerator, data, enumerator_t::destroy, enumerator_t::enumerate, entry_t::expire, export_csv(), free(), linked_list_t::get_count, certificate_t::get_subject, certificate_t::get_type, identification_t::get_type, certificate_t::get_validity, id, entry_t::id, ID_FQDN, ID_PART_RDN_CN, INIT, chunk_t::len, mutex_t::lock, MAX_TRUSTCHAIN_LENGTH, min, mutex, chunk_t::ptr, snprintf, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     int count;
     /* don't store expiration dates if no path configured */
     if (local)
     {
         if (!this->local_path)
         {
             return;
         }
     }
     else
     {
         if (!this->remote_path)
         {
             return;
         }
     }
     count = min(trustchain->get_count(trustchain), MAX_TRUSTCHAIN_LENGTH) - 1;
     enumerator = trustchain->create_enumerator(trustchain);
     /* get subject cert */
     if (enumerator->enumerate(enumerator, &cert))
     {
         identification_t *id;
         entry_t *entry;
         int i;
         INIT(entry);
         /* prefer FQDN subjectAltName... */
         if (cert->get_type(cert) == CERT_X509)
         {
             x509_t *x509 = (x509_t*)cert;
             enumerator_t *sans;
             sans = x509->create_subjectAltName_enumerator(x509);
             while (sans->enumerate(sans, &id))
             {
                 if (id->get_type(id) == ID_FQDN)
                 {
                     snprintf(entry->id, sizeof(entry->id), "%Y", id);
                     break;
                 }
             }
             sans->destroy(sans);
         }
         /* fallback to CN of DN */
         if (!entry->id[0])
         {
             enumerator_t *parts;
             id_part_t part;
             chunk_t data;
             id = cert->get_subject(cert);
             parts = id->create_part_enumerator(id);
             while (parts->enumerate(parts, &part, &data))
             {
                 if (part == ID_PART_RDN_CN)
                 {
                     snprintf(entry->id, sizeof(entry->id), "%.*s",
                              (int)data.len, data.ptr);
                     break;
                 }
             }
             parts->destroy(parts);
         }
         /* no usable identity? skip */
         if (!entry->id[0])
         {
             enumerator->destroy(enumerator);
             free(entry);
             return;
         }
         /* get intermediate CA expiration dates */
         cert->get_validity(cert, NULL, NULL, &entry->expire[0]);
         for (i = 1; i < count && enumerator->enumerate(enumerator, &cert); i++)
         {
             cert->get_validity(cert, NULL, NULL, &entry->expire[i]);
         }
         /* get CA expiration date, as last array entry */
         if (enumerator->enumerate(enumerator, &cert))
         {
             cert->get_validity(cert, NULL, NULL,
                                &entry->expire[MAX_TRUSTCHAIN_LENGTH - 1]);
         }
         this->mutex->lock(this->mutex);
         if (local)
         {
             entry = this->local->put(this->local, entry, entry);
         }
         else
         {
             entry = this->remote->put(this->remote, entry, entry);
         }
         this->mutex->unlock(this->mutex);
         if (entry)
         {
             free(entry);
         }
         if (!this->cron)
         {   /* export directly if no cron job defined */
             if (local)
             {
                 export_csv(this, this->local_path, this->local);
             }
             else
             {
                 export_csv(this, this->remote_path, this->remote);
             }
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (certexpire_export_t , destroy , void , private_certexpire_export_t * this)
Definition at line 388 of file certexpire_export.c.
References enumerator_t::destroy, mutex_t::destroy, DESTROY_IF, enumerator_t::enumerate, free(), key, mutex, and value.
 {
     entry_t *key, *value;
     enumerator_t *enumerator;
     enumerator = this->local->create_enumerator(this->local);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         free(value);
     }
     enumerator->destroy(enumerator);
     enumerator = this->remote->create_enumerator(this->remote);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         free(value);
     }
     enumerator->destroy(enumerator);
     this->local->destroy(this->local);
     this->remote->destroy(this->remote);
     DESTROY_IF(this->cron);
     this->mutex->destroy(this->mutex);
     free(this);
 }