strongSwan: connect_manager
connect_manager
ikev2
Classes
struct connect_manager_t
Typedefs
typedef struct connect_manager_t connect_manager_t
Functions
connect_manager_t * connect_manager_create (void)
Detailed Description
Typedef Documentation
typedef struct connect_manager_t connect_manager_t
Definition at line 24 of file connect_manager.h.
Function Documentation
connect_manager_t* connect_manager_create (void)
Create a manager.
Returns
connect_manager_t object
Definition at line 1587 of file connect_manager.c.
References crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_IKE, destroy(), HASH_SHA1, hasher, INIT, lib, linked_list_create(), mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by METHOD().
 {
     private_connect_manager_t *this;
     INIT(this,
         .public = {
             .destroy = _destroy,
             .check_and_register = _check_and_register,
             .check_and_initiate = _check_and_initiate,
             .set_initiator_data = _set_initiator_data,
             .set_responder_data = _set_responder_data,
             .process_check = _process_check,
             .stop_checks = _stop_checks,
         },
         .hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .checklists = linked_list_create(),
         .initiated = linked_list_create(),
     );
     if (this->hasher == NULL)
     {
         DBG1(DBG_IKE, "unable to create connect manager, SHA1 not supported");
         destroy(this);
         return NULL;
     }
     return &this->public;
 }