strongSwan: pb_reason_string_msg.c File Reference
pb_reason_string_msg.c File Reference
#include "pb_reason_string_msg.h"
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pb_reason_string_msg_t
Typedefs
typedef struct
private_pb_reason_string_msg_t private_pb_reason_string_msg_t
Functions
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_reason_string_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_reason_string_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_reason_string_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_reason_string_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_reason_string_msg_t *this)
METHOD (pb_reason_string_msg_t, get_reason_string, chunk_t, private_pb_reason_string_msg_t *this)
METHOD (pb_reason_string_msg_t, get_language_code, chunk_t, private_pb_reason_string_msg_t *this)
pb_tnc_msg_t * pb_reason_string_msg_create_from_data (chunk_t data)
pb_tnc_msg_t * pb_reason_string_msg_create (chunk_t reason_string, chunk_t language_code)
Typedef Documentation
typedef struct private_pb_reason_string_msg_t private_pb_reason_string_msg_t
Definition at line 22 of file pb_reason_string_msg.c.
Function Documentation
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_reason_string_msg_t * this)
Definition at line 69 of file pb_reason_string_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_reason_string_msg_t * this)
Definition at line 75 of file pb_reason_string_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_reason_string_msg_t * this)
Definition at line 81 of file pb_reason_string_msg.c.
References bio_writer_create(), chunk_clone, bio_writer_t::destroy, encoding, bio_writer_t::get_buf, bio_writer_t::write_data32, and bio_writer_t::write_data8.
 {
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     writer = bio_writer_create(64);
     writer->write_data32(writer, this->reason_string);
     writer->write_data8 (writer, this->language_code);
     this->encoding = writer->get_buf(writer);
     this->encoding = chunk_clone(this->encoding);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_reason_string_msg_t * this, u_int32_t * offset)
Definition at line 99 of file pb_reason_string_msg.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, encoding, FAILED, bio_reader_t::read_data32, bio_reader_t::read_data8, and SUCCESS.
 {
     bio_reader_t *reader;
     reader = bio_reader_create(this->encoding);
     if (!reader->read_data32(reader, &this->reason_string))
     {
         DBG1(DBG_TNC, "could not parse reason string");
         reader->destroy(reader);
         *offset = 0;
         return FAILED;
     };
     this->reason_string = chunk_clone(this->reason_string);
     if (this->reason_string.len &&
         this->reason_string.ptr[this->reason_string.len-1] == '\0')
     {
         DBG1(DBG_TNC, "reason string must not be null terminated");
         reader->destroy(reader);
         *offset = 3 + this->reason_string.len;
         return FAILED;
     }
     if (!reader->read_data8(reader, &this->language_code))
     {
         DBG1(DBG_TNC, "could not parse language code");
         reader->destroy(reader);
         *offset = 4 + this->reason_string.len;
         return FAILED;
     };
     this->language_code = chunk_clone(this->language_code);
     reader->destroy(reader);
     if (this->language_code.len &&
         this->language_code.ptr[this->language_code.len-1] == '\0')
     {
         DBG1(DBG_TNC, "language code must not be null terminated");
         *offset = 4 + this->reason_string.len + this->language_code.len;
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_reason_string_msg_t * this)
Definition at line 144 of file pb_reason_string_msg.c.
References encoding, and free().
 {
     free(this->encoding.ptr);
     free(this->reason_string.ptr);
     free(this->language_code.ptr);
     free(this);
 }
METHOD (pb_reason_string_msg_t , get_reason_string , chunk_t , private_pb_reason_string_msg_t * this)
Definition at line 153 of file pb_reason_string_msg.c.
 {
     return this->reason_string;
 }
METHOD (pb_reason_string_msg_t , get_language_code , chunk_t , private_pb_reason_string_msg_t * this)
Definition at line 159 of file pb_reason_string_msg.c.
 {
     return this->language_code;
 }