strongSwan: hashtable_t Struct Reference
hashtable_t Struct Reference
hashtable
#include "hashtable.h"
Public Attributes
enumerator_t *(* create_enumerator)(hashtable_t *this)
void *(* put)(hashtable_t *this, const void *key, void *value)
void *(* get)(hashtable_t *this, const void *key)
void *(* get_match)(hashtable_t *this, const void *key, hashtable_equals_t match)
void *(* remove)(hashtable_t *this, const void *key)
void(* remove_at)(hashtable_t *this, enumerator_t *enumerator)
u_int(* get_count)(hashtable_t *this)
void(* destroy)(hashtable_t *this)
void(* destroy_function)(hashtable_t *this, void(*)(void *val, const void *key))
Detailed Description
Class implementing a hash table.
General purpose hash table. This hash table is not synchronized.
Definition at line 84 of file hashtable.h.
Member Data Documentation
enumerator_t*(* hashtable_t::create_enumerator)(hashtable_t *this)
Create an enumerator over the hash table key/value pairs.
Returns
enumerator over (void *key, void *value)
Definition at line 91 of file hashtable.h.
Referenced by addr_map_destroy(), destroy_dh_mapping(), do_remove_at(), export_csv(), free_hashtable(), METHOD(), print_traces(), register_dh_mapping(), resolve_also(), START_TEST(), and vici_disconnect().
void(* hashtable_t::destroy)(hashtable_t *this)
Destroys a hash table object.
Definition at line 158 of file hashtable.h.
Referenced by addr_map_destroy(), apply_filter(), destroy_dh_mapping(), free_hashtable(), METHOD(), on_accept(), print_traces(), register_dh_mapping(), register_functions(), START_TEARDOWN(), START_TEST(), testable_function_register(), threads_deinit(), and vici_disconnect().
void(* hashtable_t::destroy_function)(hashtable_t *this, void(*)(void *val, const void *key))
Destroys a hash table object and calls the given function for each item and its key in the hash table.
Parameters
function function to call on each item and key
Definition at line 166 of file hashtable.h.
void*(* hashtable_t::get)(hashtable_t *this, const void *key)
Returns the value with the given key, if the hash table contains such an entry, otherwise NULL is returned.
Parameters
key the key of the requested value
Returns
the value, NULL if not found
Definition at line 112 of file hashtable.h.
Referenced by apply_filter(), builtin_vsnprintf(), CALLBACK(), do_remove(), do_remove_at(), get_current_thread(), get_or_create_entry(), handle_event(), kv_filter(), lookup_queue(), METHOD(), print_traces(), put(), remove_first(), remove_specific(), resolve_also(), resolve_also_single(), section_filter(), START_TEST(), testable_function_get(), thread_tls_get(), and tkm_diffie_hellman_create().
u_int(* hashtable_t::get_count)(hashtable_t *this)
Gets the number of items in the hash table.
Returns
number of items
Definition at line 153 of file hashtable.h.
Referenced by do_remove(), do_remove_at(), export_csv(), on_accept(), register_dh_mapping(), START_SETUP(), START_TEST(), and testable_function_register().
void*(* hashtable_t::get_match)(hashtable_t *this, const void *key, hashtable_equals_t match)
Returns the value with a matching key, if the hash table contains such an entry, otherwise NULL is returned.
Compared to get() the given match function is used to compare the keys for equality. The hash function does have to be deviced properly in order to make this work if the match function compares keys differently than the equals function provided to the constructor. This basically allows to enumerate all entries with the same hash value.
Parameters
key the key to match against
match match function to be used when comparing keys
Returns
the value, NULL if not found
Definition at line 128 of file hashtable.h.
Referenced by START_TEST().
void*(* hashtable_t::put)(hashtable_t *this, const void *key, void *value)
Adds the given value with the given key to the hash table, if there exists no entry with that key. NULL is returned in this case. Otherwise the existing value is replaced and the function returns the old value.
Parameters
key the key to store
value the value to store
Returns
NULL if no item was replaced, the old value otherwise
Definition at line 103 of file hashtable.h.
Referenced by addr_map_entry_add(), apply_filter(), CALLBACK(), do_remove(), do_remove_at(), get_or_create_entry(), kv_filter(), lookup_queue(), METHOD(), migrate_entry(), print_traces(), put(), put_or_destroy_entry(), put_thread(), register_dh_mapping(), section_filter(), START_TEST(), testable_function_register(), thread_tls_put(), and vici_register().
void*(* hashtable_t::remove)(hashtable_t *this, const void *key)
Removes the value with the given key from the hash table and returns the removed value (or NULL if no such value existed).
Parameters
key the key of the value to remove
Returns
the removed value, NULL if not found
Definition at line 138 of file hashtable.h.
Referenced by addr_map_entry_remove(), cleanup_tls(), do_remove(), migrate_entry(), remove_addr(), remove_attr(), remove_if_empty(), remove_queue(), remove_thread(), resolve_hosts(), START_TEST(), testable_function_register(), thread_tls_remove(), threads_deinit(), and vici_register().
void(* hashtable_t::remove_at)(hashtable_t *this, enumerator_t *enumerator)
Removes the key and value pair from the hash table at which the given enumerator currently points.
Parameters
enumerator enumerator, from create_enumerator
Definition at line 146 of file hashtable.h.
Referenced by do_remove_at(), and export_csv().
The documentation for this struct was generated from the following file:
hashtable.h