strongSwan: mysql_database.c File Reference
mysql_database.c File Reference
#include "mysql_database.h"
#include <string.h>
#include <mysql.h>
#include <utils/debug.h>
#include <utils/chunk.h>
#include <threading/thread_value.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
Classes
struct private_mysql_database_t
struct conn_t
struct transaction_t
struct mysql_enumerator_t
Macros
#define _GNU_SOURCE
#define MYSQL_DATA_TRUNCATED 101
Typedefs
typedef struct
private_mysql_database_t private_mysql_database_t
typedef struct conn_t conn_t
Functions
static void conn_release (private_mysql_database_t *this, conn_t *conn)
static void transaction_destroy (private_mysql_database_t *this, transaction_t *trans)
static void thread_initialize ()
bool mysql_database_init ()
void mysql_database_deinit ()
static void conn_destroy (conn_t *this)
static conn_t * conn_get (private_mysql_database_t *this, transaction_t **trans)
static MYSQL_STMT * run (MYSQL *mysql, char *sql, va_list *args)
static void mysql_enumerator_destroy (mysql_enumerator_t *this)
static bool mysql_enumerator_enumerate (mysql_enumerator_t *this,...)
METHOD (database_t, query, enumerator_t *, private_mysql_database_t *this, char *sql,...)
METHOD (database_t, execute, int, private_mysql_database_t *this, int *rowid, char *sql,...)
METHOD (database_t, transaction, bool, private_mysql_database_t *this, bool serializable)
static bool finalize_transaction (private_mysql_database_t *this, bool rollback)
METHOD (database_t, commit_, bool, private_mysql_database_t *this)
METHOD (database_t, rollback, bool, private_mysql_database_t *this)
METHOD (database_t, get_driver, db_driver_t, private_mysql_database_t *this)
METHOD (database_t, destroy, void, private_mysql_database_t *this)
static bool parse_uri (private_mysql_database_t *this, char *uri)
mysql_database_t * mysql_database_create (char *uri)
Variables
thread_value_t * initialized
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 19 of file mysql_database.c.
#define MYSQL_DATA_TRUNCATED 101
Definition at line 33 of file mysql_database.c.
Referenced by mysql_enumerator_enumerate().
Typedef Documentation
typedef struct conn_t conn_t
Definition at line 89 of file mysql_database.c.
typedef struct private_mysql_database_t private_mysql_database_t
Definition at line 36 of file mysql_database.c.
Function Documentation
static void conn_destroy (conn_t * this) static
Destroy a mysql connection
Definition at line 192 of file mysql_database.c.
References free().
Referenced by conn_get(), and METHOD().
 {
     mysql_close(this->mysql);
     free(this);
 }
static conn_t* conn_get (private_mysql_database_t * this, transaction_t ** trans) static
Acquire/Reuse a mysql connection
Definition at line 201 of file mysql_database.c.
References transaction_t::conn, conn_destroy(), DBG1, DBG2, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, found, host, conn_t::in_use, INIT, mutex_t::lock, mutex, conn_t::mysql, port, thread_initialize(), TRUE, and mutex_t::unlock.
Referenced by METHOD(), and mysql_database_create().
 {
     conn_t *current, *found = NULL;
     enumerator_t *enumerator;
     transaction_t *transaction;
     thread_initialize();
     transaction = this->transaction->get(this->transaction);
     if (transaction)
     {
         if (trans)
         {
             *trans = transaction;
         }
         return transaction->conn;
     }
     while (TRUE)
     {
         this->mutex->lock(this->mutex);
         enumerator = this->pool->create_enumerator(this->pool);
         while (enumerator->enumerate(enumerator, &current))
         {
             if (!current->in_use)
             {
                 found = current;
                 found->in_use = TRUE;
                 break;
             }
         }
         enumerator->destroy(enumerator);
         this->mutex->unlock(this->mutex);
         if (found)
         {   /* check connection if found, release if ping fails */
             if (mysql_ping(found->mysql) == 0)
             {
                 break;
             }
             this->mutex->lock(this->mutex);
             this->pool->remove(this->pool, found, NULL);
             this->mutex->unlock(this->mutex);
             conn_destroy(found);
             found = NULL;
             continue;
         }
         break;
     }
     if (found == NULL)
     {
         INIT(found,
             .in_use = TRUE,
             .mysql = mysql_init(NULL),
         );
         if (!mysql_real_connect(found->mysql, this->host, this->username,
                                 this->password, this->database, this->port,
                                 NULL, 0))
         {
             DBG1(DBG_LIB, "connecting to mysql://%s:***@%s:%d/%s failed: %s",
                  this->username, this->host, this->port, this->database,
                  mysql_error(found->mysql));
             conn_destroy(found);
             found = NULL;
         }
         else
         {
             this->mutex->lock(this->mutex);
             this->pool->insert_last(this->pool, found);
             DBG2(DBG_LIB, "increased MySQL connection pool size to %d",
                  this->pool->get_count(this->pool));
             this->mutex->unlock(this->mutex);
         }
     }
     return found;
 }
static void conn_release (private_mysql_database_t * this, conn_t * conn) static
Release a mysql connection
Definition at line 132 of file mysql_database.c.
References FALSE, conn_t::in_use, mutex_t::lock, mutex, and mutex_t::unlock.
Referenced by METHOD(), mysql_database_create(), mysql_enumerator_destroy(), and transaction_destroy().
 {
     this->mutex->lock(this->mutex);
     conn->in_use = FALSE;
     this->mutex->unlock(this->mutex);
 }
static bool finalize_transaction (private_mysql_database_t * this, bool rollback) static
Finalize a transaction depending on the reference count and if it should be rolled back.
Definition at line 702 of file mysql_database.c.
References command, transaction_t::conn, DBG1, DBG_LIB, FALSE, conn_t::mysql, ref_put(), transaction_t::refs, transaction_t::rollback, transaction_destroy(), and TRUE.
Referenced by METHOD().
 {
     transaction_t *trans;
     char *command = "COMMIT";
     bool success;
     trans = this->transaction->get(this->transaction);
     if (!trans)
     {
         DBG1(DBG_LIB, "no database transaction found");
         return FALSE;
     }
     /* set flag, can't be unset */
     trans->rollback |= rollback;
     if (ref_put(&trans->refs))
     {
         if (trans->rollback)
         {
             command = "ROLLBACK";
         }
         success = mysql_query(trans->conn->mysql, command) == 0;
         this->transaction->set(this->transaction, NULL);
         transaction_destroy(this, trans);
         return success;
     }
     return TRUE;
 }
METHOD (database_t , query , enumerator_t * , private_mysql_database_t * this, char * sql, ...)
Definition at line 533 of file mysql_database.c.
References mysql_enumerator_t::bind, conn, conn_get(), conn_release(), DB_BLOB, DB_DOUBLE, DB_INT, DB_TEXT, DB_UINT, DBG1, DBG_LIB, destroy(), INIT, mysql_enumerator_t::length, conn_t::mysql, mysql_enumerator_destroy(), mysql_enumerator_enumerate(), mysql_enumerator_t::p_double, mysql_enumerator_t::p_int, mysql_enumerator_t::p_uint, mysql_enumerator_t::p_void, run(), TRUE, and mysql_enumerator_t::val.
 {
     MYSQL_STMT *stmt;
     va_list args;
     mysql_enumerator_t *enumerator = NULL;
     conn_t *conn;
     conn = conn_get(this, NULL);
     if (!conn)
     {
         return NULL;
     }
     va_start(args, sql);
     stmt = run(conn->mysql, sql, &args);
     if (stmt)
     {
         int columns, i;
         INIT(enumerator,
             .public = {
                 .enumerate = (void*)mysql_enumerator_enumerate,
                 .destroy = (void*)mysql_enumerator_destroy,
             },
             .db = this,
             .stmt = stmt,
             .conn = conn,
         );
         columns = mysql_stmt_field_count(stmt);
         enumerator->bind = calloc(columns, sizeof(MYSQL_BIND));
         enumerator->length = calloc(columns, sizeof(unsigned long));
         enumerator->val.p_void = calloc(columns, sizeof(enumerator->val));
         for (i = 0; i < columns; i++)
         {
             switch (va_arg(args, db_type_t))
             {
                 case DB_INT:
                 {
                     enumerator->bind[i].buffer_type = MYSQL_TYPE_LONG;
                     enumerator->bind[i].buffer = (char*)&enumerator->val.p_int[i];
                     break;
                 }
                 case DB_UINT:
                 {
                     enumerator->bind[i].buffer_type = MYSQL_TYPE_LONG;
                     enumerator->bind[i].buffer = (char*)&enumerator->val.p_uint[i];
                     enumerator->bind[i].is_unsigned = TRUE;
                     break;
                 }
                 case DB_TEXT:
                 {
                     enumerator->bind[i].buffer_type = MYSQL_TYPE_STRING;
                     enumerator->bind[i].length = &enumerator->length[i];
                     break;
                 }
                 case DB_BLOB:
                 {
                     enumerator->bind[i].buffer_type = MYSQL_TYPE_BLOB;
                     enumerator->bind[i].length = &enumerator->length[i];
                     break;
                 }
                 case DB_DOUBLE:
                 {
                     enumerator->bind[i].buffer_type = MYSQL_TYPE_DOUBLE;
                     enumerator->bind[i].buffer = (char*)&enumerator->val.p_double[i];
                     break;
                 }
                 default:
                     DBG1(DBG_LIB, "invalid result data type supplied");
                     mysql_enumerator_destroy(enumerator);
                     va_end(args);
                     return NULL;
             }
         }
         if (mysql_stmt_bind_result(stmt, enumerator->bind))
         {
             DBG1(DBG_LIB, "binding MySQL result failed: %s",
                  mysql_stmt_error(stmt));
             mysql_enumerator_destroy(enumerator);
             enumerator = NULL;
         }
     }
     else
     {
         conn_release(this, conn);
     }
     va_end(args);
     return (enumerator_t*)enumerator;
 }
METHOD (database_t , execute , int , private_mysql_database_t * this, int * rowid, char * sql, ...)
Definition at line 625 of file mysql_database.c.
References conn, conn_get(), conn_release(), conn_t::mysql, and run().
 {
     MYSQL_STMT *stmt;
     va_list args;
     conn_t *conn;
     int affected = -1;
     conn = conn_get(this, NULL);
     if (!conn)
     {
         return -1;
     }
     va_start(args, sql);
     stmt = run(conn->mysql, sql, &args);
     if (stmt)
     {
         if (rowid)
         {
             *rowid = mysql_stmt_insert_id(stmt);
         }
         affected = mysql_stmt_affected_rows(stmt);
         mysql_stmt_close(stmt);
     }
     va_end(args);
     conn_release(this, conn);
     return affected;
 }
METHOD (database_t , transaction , bool , private_mysql_database_t * this, bool serializable)
Definition at line 654 of file mysql_database.c.
References conn, conn_get(), conn_release(), DBG1, DBG_LIB, FALSE, INIT, conn_t::mysql, ref_get(), transaction_t::refs, and TRUE.
 {
     transaction_t *trans = NULL;
     conn_t *conn;
     conn = conn_get(this, &trans);
     if (!conn)
     {
         return FALSE;
     }
     else if (trans)
     {
         ref_get(&trans->refs);
         return TRUE;
     }
     /* these statements are not supported in prepared statements that are used
      * by the execute() method */
     if (serializable)
     {
         if (mysql_query(conn->mysql,
                         "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE") != 0)
         {
             DBG1(DBG_LIB, "starting transaction failed: %s",
                  mysql_error(conn->mysql));
             conn_release(this, conn);
             return FALSE;
         }
     }
     if (mysql_query(conn->mysql, "START TRANSACTION") != 0)
     {
         DBG1(DBG_LIB, "starting transaction failed: %s",
              mysql_error(conn->mysql));
         conn_release(this, conn);
         return FALSE;
     }
     INIT(trans,
         .conn = conn,
         .refs = 1,
     );
     this->transaction->set(this->transaction, trans);
     return TRUE;
 }
METHOD (database_t , commit_ , bool , private_mysql_database_t * this)
Definition at line 733 of file mysql_database.c.
References FALSE, and finalize_transaction().
 {
     return finalize_transaction(this, FALSE);
 }
METHOD (database_t , rollback , bool , private_mysql_database_t * this)
Definition at line 739 of file mysql_database.c.
References finalize_transaction(), and TRUE.
 {
     return finalize_transaction(this, TRUE);
 }
METHOD (database_t , get_driver , db_driver_t , private_mysql_database_t * this)
Definition at line 745 of file mysql_database.c.
References DB_MYSQL.
 {
     return DB_MYSQL;
 }
METHOD (database_t , destroy , void , private_mysql_database_t * this)
Definition at line 751 of file mysql_database.c.
References conn_destroy(), mutex_t::destroy, free(), host, and mutex.
 {
     this->transaction->destroy(this->transaction);
     this->pool->destroy_function(this->pool, (void*)conn_destroy);
     this->mutex->destroy(this->mutex);
     free(this->host);
     free(this->username);
     free(this->password);
     free(this->database);
     free(this);
 }
static void mysql_enumerator_destroy (mysql_enumerator_t * this) static
create a mysql enumerator
Definition at line 409 of file mysql_database.c.
References bind, conn, conn_release(), db, free(), length, and val.
Referenced by METHOD().
 {
     int columns, i;
     columns = mysql_stmt_field_count(this->stmt);
     for (i = 0; i < columns; i++)
     {
         switch (this->bind[i].buffer_type)
         {
             case MYSQL_TYPE_STRING:
             case MYSQL_TYPE_BLOB:
             {
                 free(this->bind[i].buffer);
                 break;
             }
             default:
                 break;
         }
     }
     mysql_stmt_close(this->stmt);
     conn_release(this->db, this->conn);
     free(this->bind);
     free(this->val.p_void);
     free(this->length);
     free(this);
 }
static bool mysql_enumerator_enumerate (mysql_enumerator_t * this, ...) static
Implementation of database.query().enumerate
Definition at line 440 of file mysql_database.c.
References bind, DBG1, DBG_LIB, FALSE, free(), chunk_t::len, length, malloc(), MYSQL_DATA_TRUNCATED, chunk_t::ptr, TRUE, val, and value.
Referenced by METHOD().
 {
     int i, columns;
     va_list args;
     columns = mysql_stmt_field_count(this->stmt);
     /* free/reset data set of previous call */
     for (i = 0; i < columns; i++)
     {
         switch (this->bind[i].buffer_type)
         {
             case MYSQL_TYPE_STRING:
             case MYSQL_TYPE_BLOB:
             {
                 free(this->bind[i].buffer);
                 this->bind[i].buffer = NULL;
                 this->bind[i].buffer_length = 0;
                 this->bind[i].length = &this->length[i];
                 this->length[i] = 0;
                 break;
             }
             default:
                 break;
         }
     }
     switch (mysql_stmt_fetch(this->stmt))
     {
         case 0:
         case MYSQL_DATA_TRUNCATED:
             break;
         case MYSQL_NO_DATA:
             return FALSE;
         default:
             DBG1(DBG_LIB, "fetching MySQL row failed: %s",
                  mysql_stmt_error(this->stmt));
             return FALSE;
     }
     va_start(args, this);
     for (i = 0; i < columns; i++)
     {
         switch (this->bind[i].buffer_type)
         {
             case MYSQL_TYPE_LONG:
             {
                 if (this->bind[i].is_unsigned)
                 {
                     u_int *value = va_arg(args, u_int*);
                     *value = this->val.p_uint[i];
                 }
                 else
                 {
                     int *value = va_arg(args, int*);
                     *value = this->val.p_int[i];
                 }
                 break;
             }
             case MYSQL_TYPE_STRING:
             {
                 char **value = va_arg(args, char**);
                 this->bind[i].buffer = malloc(this->length[i]+1);
                 this->bind[i].buffer_length = this->length[i];
                 *value = this->bind[i].buffer;
                 mysql_stmt_fetch_column(this->stmt, &this->bind[i], i, 0);
                 ((char*)this->bind[i].buffer)[this->length[i]] = '\0';
                 break;
             }
             case MYSQL_TYPE_BLOB:
             {
                 chunk_t *value = va_arg(args, chunk_t*);
                 this->bind[i].buffer = malloc(this->length[i]);
                 this->bind[i].buffer_length = this->length[i];
                 value->ptr = this->bind[i].buffer;
                 value->len = this->length[i];
                 mysql_stmt_fetch_column(this->stmt, &this->bind[i], i, 0);
                 break;
             }
             case MYSQL_TYPE_DOUBLE:
             {
                 double *value = va_arg(args, double*);
                 *value = this->val.p_double[i];
                 break;
             }
             default:
                 break;
         }
     }
     va_end(args);
     return TRUE;
 }
static bool parse_uri (private_mysql_database_t * this, char * uri) static
parse mysql://username:pass:port/database uri
Definition at line 764 of file mysql_database.c.
References DBG1, DBG_LIB, FALSE, free(), host, port, strdup, and TRUE.
Referenced by mysql_database_create().
 {
     char *username, *password, *host, *port = "0", *database, *pos;
     username = strdup(uri + 8);
     pos = strchr(username, ':');
     if (pos)
     {
         *pos = '\0';
         password = pos + 1;
         pos = strrchr(password, '@');
         if (pos)
         {
             *pos = '\0';
             host = pos + 1;
             pos = strrchr(host, ':');
             if (pos)
             {
                 *pos = '\0';
                 port = pos + 1;
                 pos = strchr(port, '/');
             }
             else
             {
                 pos = strchr(host, '/');
             }
             if (pos)
             {
                 *pos = '\0';
                 database = pos + 1;
                 this->host = strdup(host);
                 this->username = strdup(username);
                 this->password = strdup(password);
                 this->database = strdup(database);
                 this->port = atoi(port);
                 free(username);
                 return TRUE;
             }
         }
     }
     free(username);
     DBG1(DBG_LIB, "parsing MySQL database uri '%s' failed", uri);
     return FALSE;
 }
static MYSQL_STMT* run (MYSQL * mysql, char * sql, va_list * args) static
Create and run a MySQL stmt using a sql string and args
Definition at line 280 of file mysql_database.c.
References bind, DB_BLOB, DB_DOUBLE, DB_INT, DB_NULL, DB_TEXT, DB_UINT, DBG1, DBG_LIB, chunk_t::len, memset, params, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     MYSQL_STMT *stmt;
     int params;
     stmt = mysql_stmt_init(mysql);
     if (stmt == NULL)
     {
         DBG1(DBG_LIB, "creating MySQL statement failed: %s",
              mysql_error(mysql));
         return NULL;
     }
     if (mysql_stmt_prepare(stmt, sql, strlen(sql)))
     {
         DBG1(DBG_LIB, "preparing MySQL statement failed: %s",
              mysql_stmt_error(stmt));
         mysql_stmt_close(stmt);
         return NULL;
     }
     params = mysql_stmt_param_count(stmt);
     if (params > 0)
     {
         int i;
         MYSQL_BIND *bind;
         bind = alloca(sizeof(MYSQL_BIND) * params);
         memset(bind, 0, sizeof(MYSQL_BIND) * params);
         for (i = 0; i < params; i++)
         {
             switch (va_arg(*args, db_type_t))
             {
                 case DB_INT:
                 {
                     bind[i].buffer_type = MYSQL_TYPE_LONG;
                     bind[i].buffer = (char*)alloca(sizeof(int));
                     *(int*)bind[i].buffer = va_arg(*args, int);
                     bind[i].buffer_length = sizeof(int);
                     break;
                 }
                 case DB_UINT:
                 {
                     bind[i].buffer_type = MYSQL_TYPE_LONG;
                     bind[i].buffer = (char*)alloca(sizeof(u_int));
                     *(u_int*)bind[i].buffer = va_arg(*args, u_int);
                     bind[i].buffer_length = sizeof(u_int);
                     bind[i].is_unsigned = TRUE;
                     break;
                 }
                 case DB_TEXT:
                 {
                     bind[i].buffer_type = MYSQL_TYPE_STRING;;
                     bind[i].buffer = va_arg(*args, char*);
                     if (bind[i].buffer)
                     {
                         bind[i].buffer_length = strlen(bind[i].buffer);
                     }
                     break;
                 }
                 case DB_BLOB:
                 {
                     chunk_t chunk = va_arg(*args, chunk_t);
                     bind[i].buffer_type = MYSQL_TYPE_BLOB;
                     bind[i].buffer = chunk.ptr;
                     bind[i].buffer_length = chunk.len;
                     break;
                 }
                 case DB_DOUBLE:
                 {
                     bind[i].buffer_type = MYSQL_TYPE_DOUBLE;
                     bind[i].buffer = (char*)alloca(sizeof(double));
                     *(double*)bind[i].buffer = va_arg(*args, double);
                     bind[i].buffer_length = sizeof(double);
                     break;
                 }
                 case DB_NULL:
                 {
                     bind[i].buffer_type = MYSQL_TYPE_NULL;
                     break;
                 }
                 default:
                     DBG1(DBG_LIB, "invalid data type supplied");
                     mysql_stmt_close(stmt);
                     return NULL;
             }
         }
         if (mysql_stmt_bind_param(stmt, bind))
         {
             DBG1(DBG_LIB, "binding MySQL param failed: %s",
                  mysql_stmt_error(stmt));
             mysql_stmt_close(stmt);
             return NULL;
         }
     }
     if (mysql_stmt_execute(stmt))
     {
         DBG1(DBG_LIB, "executing MySQL statement failed: %s",
              mysql_stmt_error(stmt));
         mysql_stmt_close(stmt);
         return NULL;
     }
     return stmt;
 }
static void thread_initialize () static
Initialize a thread for mysql usage
Definition at line 157 of file mysql_database.c.
References thread_value_t::get, thread_value_t::set, and TRUE.
Referenced by conn_get().
 {
     if (initialized->get(initialized) == NULL)
     {
         initialized->set(initialized, (void*)TRUE);
         mysql_thread_init();
     }
 }
static void transaction_destroy (private_mysql_database_t * this, transaction_t * trans) static
Destroy a transaction and release the connection
Definition at line 142 of file mysql_database.c.
References transaction_t::conn, conn_release(), and free().
Referenced by finalize_transaction().
 {
     conn_release(this, trans->conn);
     free(trans);
 }
Variable Documentation
thread_value_t* initialized
thread specific initialization flag
Definition at line 152 of file mysql_database.c.