strongSwan: authenticator
authenticator
sa
Classes
struct authenticator_t
Typedefs
typedef enum auth_method_t auth_method_t
typedef struct authenticator_t authenticator_t
Enumerations
enum auth_method_t {
AUTH_NONE = 0, AUTH_RSA = 1, AUTH_PSK = 2, AUTH_DSS = 3,
AUTH_ECDSA_256 = 9, AUTH_ECDSA_384 = 10, AUTH_ECDSA_521 = 11, AUTH_GSPM = 12,
AUTH_NULL = 13, AUTH_DS = 14, AUTH_XAUTH_INIT_PSK = 256, AUTH_XAUTH_RESP_PSK,
AUTH_XAUTH_INIT_RSA, AUTH_XAUTH_RESP_RSA, AUTH_HYBRID_INIT_RSA, AUTH_HYBRID_RESP_RSA
}
Functions
authenticator_t * authenticator_create_builder (ike_sa_t *ike_sa, auth_cfg_t *cfg, chunk_t received_nonce, chunk_t sent_nonce, chunk_t received_init, chunk_t sent_init, char reserved[3])
authenticator_t * authenticator_create_verifier (ike_sa_t *ike_sa, message_t *message, chunk_t received_nonce, chunk_t sent_nonce, chunk_t received_init, chunk_t sent_init, char reserved[3])
authenticator_t * authenticator_create_v1 (ike_sa_t *ike_sa, bool initiator, auth_method_t auth_method, diffie_hellman_t *dh, chunk_t dh_value, chunk_t sa_payload, chunk_t id_payload)
Variables
enum_name_t * auth_method_names
Detailed Description
Typedef Documentation
typedef enum auth_method_t auth_method_t
Definition at line 26 of file authenticator.h.
typedef struct authenticator_t authenticator_t
Definition at line 27 of file authenticator.h.
Enumeration Type Documentation
enum auth_method_t
Method to use for authentication, as defined in IKEv2.
Enumerator
AUTH_NONE
No authentication used.
AUTH_RSA
Computed as specified in section 2.15 of RFC using an RSA private key over a PKCS#1 padded hash.
AUTH_PSK
Computed as specified in section 2.15 of RFC using the shared key associated with the identity in the ID payload and the negotiated prf function
AUTH_DSS
Computed as specified in section 2.15 of RFC using a DSS private key over a SHA-1 hash.
AUTH_ECDSA_256
ECDSA with SHA-256 on the P-256 curve as specified in RFC 4754
AUTH_ECDSA_384
ECDSA with SHA-384 on the P-384 curve as specified in RFC 4754
AUTH_ECDSA_521
ECDSA with SHA-512 on the P-521 curve as specified in RFC 4754
AUTH_GSPM
Generic Secure Password Authentication Method as specified in RFC 6467
AUTH_NULL
NULL Authentication Method as specified in draft-ietf-ipsecme-ikev2-null-auth
AUTH_DS
Digital Signature as specified in RFC 7427
AUTH_XAUTH_INIT_PSK
IKEv1 initiator XAUTH with PSK, outside of IANA range
AUTH_XAUTH_RESP_PSK
IKEv1 responder XAUTH with PSK, outside of IANA range
AUTH_XAUTH_INIT_RSA
IKEv1 initiator XAUTH with RSA, outside of IANA range
AUTH_XAUTH_RESP_RSA
IKEv1 responder XAUTH with RSA, outside of IANA range
AUTH_HYBRID_INIT_RSA
IKEv1 initiator XAUTH, responder RSA, outside of IANA range
AUTH_HYBRID_RESP_RSA
IKEv1 responder XAUTH, initiator RSA, outside of IANA range
Definition at line 36 of file authenticator.h.
                    {
     AUTH_NONE = 0,
     AUTH_RSA = 1,
     AUTH_PSK = 2,
     AUTH_DSS = 3,
     AUTH_ECDSA_256 = 9,
     AUTH_ECDSA_384 = 10,
     AUTH_ECDSA_521 = 11,
     AUTH_GSPM = 12,
     AUTH_NULL = 13,
     AUTH_DS = 14,
     AUTH_XAUTH_INIT_PSK = 256,
     AUTH_XAUTH_RESP_PSK,
     AUTH_XAUTH_INIT_RSA,
     AUTH_XAUTH_RESP_RSA,
     AUTH_HYBRID_INIT_RSA,
     AUTH_HYBRID_RESP_RSA,
 };
Function Documentation
authenticator_t* authenticator_create_builder (ike_sa_t * ike_sa, auth_cfg_t * cfg, chunk_t received_nonce, chunk_t sent_nonce, chunk_t received_init, chunk_t sent_init, char reserved[3])
Create an IKEv2 authenticator to build signatures.
Parameters
ike_sa associated ike_sa
cfg authentication configuration
received_nonce nonce received in IKE_SA_INIT
sent_nonce nonce sent in IKE_SA_INIT
received_init received IKE_SA_INIT message data
sent_init sent IKE_SA_INIT message data
reserved reserved bytes of the ID payload
Returns
authenticator, NULL if not supported
Referenced by METHOD().
authenticator_t* authenticator_create_v1 (ike_sa_t * ike_sa, bool initiator, auth_method_t auth_method, diffie_hellman_t * dh, chunk_t dh_value, chunk_t sa_payload, chunk_t id_payload)
Create an IKEv1 authenticator to build and verify signatures or hash payloads.
Note
Due to the fixed ID, these authenticators can only be used in one direction at a time.
Parameters
ike_sa associated IKE_SA
initiator TRUE if we are the IKE_SA initiator
auth_method negotiated authentication method to use
dh diffie hellman key exchange
dh_value others public diffie hellman value
sa_payload generated SA payload data, without payload header
id_payload encoded ID payload of peer to authenticate or verify without payload header (gets owned)
Returns
authenticator, NULL if not supported
Referenced by create_authenticator(), and hybrid_authenticator_create().
authenticator_t* authenticator_create_verifier (ike_sa_t * ike_sa, message_t * message, chunk_t received_nonce, chunk_t sent_nonce, chunk_t received_init, chunk_t sent_init, char reserved[3])
Create an IKEv2 authenticator to verify signatures.
Parameters
ike_sa associated ike_sa
message message containing authentication data
received_nonce nonce received in IKE_SA_INIT
sent_nonce nonce sent in IKE_SA_INIT
received_init received IKE_SA_INIT message data
sent_init sent IKE_SA_INIT message data
reserved reserved bytes of the ID payload
Returns
authenticator, NULL if not supported
Referenced by METHOD().
Variable Documentation
enum_name_t* auth_method_names
enum names for auth_method_t.
Referenced by build_auth(), create_authenticator(), METHOD(), rebuild_auth(), and sign_classic().