strongSwan: parser_helper_t Struct Reference
parser_helper_t Struct Reference
parser_helper
#include "parser_helper.h"
Public Attributes
const void * context
void * scanner
int(* get_lineno)(void *scanner)
void(* file_include)(parser_helper_t *this, char *pattern)
FILE *(* file_next)(parser_helper_t *this)
void(* string_init)(parser_helper_t *this)
void(* string_add)(parser_helper_t *this, char *str)
char *(* string_get)(parser_helper_t *this)
void(* destroy)(parser_helper_t *this)
Detailed Description
Helper class for flex/bison based parsers.
PREFIX equals whatever is configure with option prefix resp. name-prefix.
Definition at line 36 of file parser_helper.h.
Member Data Documentation
const void* parser_helper_t::context
A user defined parser context object.
Definition at line 41 of file parser_helper.h.
Referenced by add_section(), add_setting(), pop_section(), push_section(), and yyparse().
void(* parser_helper_t::destroy)(parser_helper_t *this)
Destroy this instance.
Definition at line 120 of file parser_helper.h.
Referenced by conf_parser_parse_file(), settings_parser_parse_file(), and settings_parser_parse_string().
void(* parser_helper_t::file_include)(parser_helper_t *this, char *pattern)
Resolves the given include pattern, relative to the location of the current file.
Call file_next() to open the next file.
Parameters
pattern file pattern
Definition at line 69 of file parser_helper.h.
Referenced by conf_parser_parse_file(), include_files(), and settings_parser_parse_file().
FILE*(* parser_helper_t::file_next)(parser_helper_t *this)
Get the next file to process.
This will return NULL if all files matching the most recent pattern have been handled. If there are other patterns the next call will then return the next file matching the previous pattern.
When hitting <<EOF>> first call
PREFIXpop_buffer_state(yyscanner);
then call this method to check if there are more files to include for the most recent call to file_include(), if so, call
PREFIXset_in(file, helper->scanner);
PREFIXpush_buffer_state(PREFIX_create_buffer(file, YY_BUF_SIZE,
                        helper->scanner), helper->scanner);
If there are no more files to process check YY_CURRENT_BUFFER and if it is FALSE call yyterminate().
Returns
next file to process, or NULL (see comment)
Definition at line 95 of file parser_helper.h.
Referenced by conf_parser_open_next_file(), and settings_parser_open_next_file().
int(* parser_helper_t::get_lineno)(void *scanner)
Function to determine the current line number (defined by the lexer).
Basically, this should be assigned to PREFIXget_lineno.
Parameters
scanner the lexer
Returns
current line number
Definition at line 59 of file parser_helper.h.
Referenced by conf_parser_parse_file(), parser_helper_log(), settings_parser_parse_file(), and settings_parser_parse_string().
void* parser_helper_t::scanner
Opaque object allocated by the lexer, should be set with:
PREFIXlex_init_extra(helper, &helper->scanner).
Definition at line 49 of file parser_helper.h.
Referenced by conf_parser_error(), conf_parser_open_next_file(), conf_parser_parse_file(), parser_helper_log(), settings_parser_error(), settings_parser_load_string(), settings_parser_open_next_file(), settings_parser_parse_file(), settings_parser_parse_string(), and yylex().
void(* parser_helper_t::string_add)(parser_helper_t *this, char *str)
Append the given string.
Parameters
str string to append
Definition at line 107 of file parser_helper.h.
char*(* parser_helper_t::string_get)(parser_helper_t *this)
Extract the current string buffer as null-terminated string. Can only be called once per string.
Returns
allocated string
Definition at line 115 of file parser_helper.h.
Referenced by include_files().
void(* parser_helper_t::string_init)(parser_helper_t *this)
Start parsing a string, discards any currently stored data.
Definition at line 100 of file parser_helper.h.
The documentation for this struct was generated from the following file:
parser_helper.h