strongSwan: bio_reader_t Struct Reference
bio_reader_t Struct Reference
bio_reader
#include "bio_reader.h"
Public Attributes
u_int32_t(* remaining)(bio_reader_t *this)
chunk_t(* peek)(bio_reader_t *this)
bool(* read_uint8)(bio_reader_t *this, u_int8_t *res)
bool(* read_uint16)(bio_reader_t *this, u_int16_t *res)
bool(* read_uint24)(bio_reader_t *this, u_int32_t *res)
bool(* read_uint32)(bio_reader_t *this, u_int32_t *res)
bool(* read_uint64)(bio_reader_t *this, u_int64_t *res)
bool(* read_data)(bio_reader_t *this, u_int32_t len, chunk_t *res)
bool(* read_uint8_end)(bio_reader_t *this, u_int8_t *res)
bool(* read_uint16_end)(bio_reader_t *this, u_int16_t *res)
bool(* read_uint24_end)(bio_reader_t *this, u_int32_t *res)
bool(* read_uint32_end)(bio_reader_t *this, u_int32_t *res)
bool(* read_uint64_end)(bio_reader_t *this, u_int64_t *res)
bool(* read_data_end)(bio_reader_t *this, u_int32_t len, chunk_t *res)
bool(* read_data8)(bio_reader_t *this, chunk_t *res)
bool(* read_data16)(bio_reader_t *this, chunk_t *res)
bool(* read_data24)(bio_reader_t *this, chunk_t *res)
bool(* read_data32)(bio_reader_t *this, chunk_t *res)
void(* destroy)(bio_reader_t *this)
Detailed Description
Buffered input parser.
Note
Integers are returned in host byte order.
Definition at line 36 of file bio_reader.h.
Member Data Documentation
void(* bio_reader_t::destroy)(bio_reader_t *this)
Destroy a bio_reader_t.
Definition at line 185 of file bio_reader.h.
Referenced by assess(), CALLBACK(), dnscert_create_frm_rr(), do_sasl(), find_private_key(), get_identity_attribute(), handle_supported_hash_algorithms(), ipseckey_create_frm_rr(), METHOD(), negotiate_version(), parse_public_key(), peer_supports_curve(), process_cert_verify(), process_certificate(), process_certreq(), process_client_hello(), process_handshake(), process_tnc_msg(), pt_tls_read(), read_sasl(), read_sasl_mech_selection(), receive_msg(), remove_padding(), seg_env_create_from_data(), select_and_do_sasl(), and START_TEST().
chunk_t(* bio_reader_t::peek)(bio_reader_t *this)
Peek the remaining data, not consuming any bytes.
Returns
remaining data
Definition at line 50 of file bio_reader.h.
Referenced by assert_reader_after_read(), assess(), CALLBACK(), do_sasl(), METHOD(), parse_public_key(), process_application(), process_cert_verify(), process_certificate(), process_certreq(), process_client_hello(), process_ec_key_exchange(), process_hello_done(), process_key_exchange(), process_key_exchange_dhe(), process_key_exchange_encrypted(), process_modp_key_exchange(), process_server_hello(), read_sasl_mech_selection(), receive_msg(), and remove_padding().
bool(* bio_reader_t::read_data)(bio_reader_t *this, u_int32_t len, chunk_t *res)
Read a chunk of len bytes, advance.
Parameters
len number of bytes to read
res pointer to result, not cloned
Returns
TRUE if data read successfully
Definition at line 99 of file bio_reader.h.
Referenced by dnscert_create_frm_rr(), ipseckey_create_frm_rr(), METHOD(), process_client_hello(), process_finished(), process_handshake(), process_server_hello(), read_sasl(), read_sasl_mech_selection(), select_and_do_sasl(), and START_TEST().
bool(* bio_reader_t::read_data16)(bio_reader_t *this, chunk_t *res)
Read a chunk of bytes with a 16-bit length header, advance.
Parameters
res pointer to result, not cloned
Returns
TRUE if data read successfully
Definition at line 164 of file bio_reader.h.
Referenced by METHOD(), process_certreq(), process_client_hello(), process_key_exchange_dhe(), process_key_exchange_encrypted(), process_modp_key_exchange(), and process_server_hello().
bool(* bio_reader_t::read_data24)(bio_reader_t *this, chunk_t *res)
Read a chunk of bytes with a 24-bit length header, advance.
Parameters
res pointer to result, not cloned
Returns
TRUE if data read successfully
Definition at line 172 of file bio_reader.h.
Referenced by process_certificate().
bool(* bio_reader_t::read_data32)(bio_reader_t *this, chunk_t *res)
Read a chunk of bytes with a 32-bit length header, advance.
Parameters
res pointer to result, not cloned
Returns
TRUE if data read successfully
Definition at line 180 of file bio_reader.h.
Referenced by METHOD(), and parse_public_key().
bool(* bio_reader_t::read_data8)(bio_reader_t *this, chunk_t *res)
Read a chunk of bytes with a 8-bit length header, advance.
Parameters
res pointer to result, not cloned
Returns
TRUE if data read successfully
Definition at line 156 of file bio_reader.h.
Referenced by CALLBACK(), METHOD(), process_certreq(), process_client_hello(), process_ec_key_exchange(), process_key_exchange_dhe(), and process_server_hello().
bool(* bio_reader_t::read_data_end)(bio_reader_t *this, u_int32_t len, chunk_t *res)
Read a chunk of len bytes from the end of the buffer, reduce remaining.
Parameters
len number of bytes to read
res ponter to result, not cloned
Returns
TRUE if data read successfully
Definition at line 148 of file bio_reader.h.
Referenced by METHOD(), remove_padding(), and START_TEST().
bool(* bio_reader_t::read_uint16)(bio_reader_t *this, u_int16_t *res)
Read a 16-bit integer from the buffer, advance.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 66 of file bio_reader.h.
Referenced by dnscert_create_frm_rr(), handle_supported_hash_algorithms(), METHOD(), peer_supports_curve(), process_client_hello(), process_ec_key_exchange(), and process_server_hello().
bool(* bio_reader_t::read_uint16_end)(bio_reader_t *this, u_int16_t *res)
Read a 16-bit integer from the end of the buffer, reduce remaining.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 115 of file bio_reader.h.
bool(* bio_reader_t::read_uint24)(bio_reader_t *this, u_int32_t *res)
Read a 24-bit integer from the buffer, advance.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 74 of file bio_reader.h.
Referenced by METHOD(), negotiate_version(), process_handshake(), process_tnc_msg(), and pt_tls_read().
bool(* bio_reader_t::read_uint24_end)(bio_reader_t *this, u_int32_t *res)
Read a 24-bit integer from the end of the buffer, reduce remaining.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 123 of file bio_reader.h.
bool(* bio_reader_t::read_uint32)(bio_reader_t *this, u_int32_t *res)
Read a 32-bit integer from the buffer, advance.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 82 of file bio_reader.h.
Referenced by get_identity_attribute(), METHOD(), process_tnc_msg(), pt_tls_read(), and receive_msg().
bool(* bio_reader_t::read_uint32_end)(bio_reader_t *this, u_int32_t *res)
Read a 32-bit integer from the end of the buffer, reduce remaining.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 131 of file bio_reader.h.
bool(* bio_reader_t::read_uint64)(bio_reader_t *this, u_int64_t *res)
Read a 64-bit integer from the buffer, advance.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 90 of file bio_reader.h.
Referenced by METHOD().
bool(* bio_reader_t::read_uint64_end)(bio_reader_t *this, u_int64_t *res)
Read a 64-bit integer from the end of the buffer, reduce remaining.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 139 of file bio_reader.h.
bool(* bio_reader_t::read_uint8)(bio_reader_t *this, u_int8_t *res)
Read a 8-bit integer from the buffer, advance.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 58 of file bio_reader.h.
Referenced by CALLBACK(), dnscert_create_frm_rr(), do_sasl(), find_private_key(), ipseckey_create_frm_rr(), METHOD(), negotiate_version(), process_alert(), process_ec_key_exchange(), process_handshake(), process_server_hello(), process_tnc_msg(), pt_tls_read(), read_sasl_mech_selection(), and select_and_do_sasl().
bool(* bio_reader_t::read_uint8_end)(bio_reader_t *this, u_int8_t *res)
Read a 8-bit integer from the end of the buffer, reduce remaining.
Parameters
res pointer to result
Returns
TRUE if integer read successfully
Definition at line 107 of file bio_reader.h.
Referenced by remove_padding().
u_int32_t(* bio_reader_t::remaining)(bio_reader_t *this)
Get the number of remaining bytes.
Returns
number of remaining bytes in buffer
Definition at line 43 of file bio_reader.h.
Referenced by assert_reader_after_read(), dnscert_create_frm_rr(), find_private_key(), handle_supported_hash_algorithms(), ipseckey_create_frm_rr(), METHOD(), peer_supports_curve(), process_application(), process_certificate(), process_certreq(), process_client_hello(), process_handshake(), process_server_hello(), read_sasl(), read_sasl_mech_selection(), select_and_do_sasl(), and START_TEST().
The documentation for this struct was generated from the following file:
bio_reader.h