strongSwan: xauth.c File Reference
xauth.c File Reference
#include "xauth.h"
#include <daemon.h>
#include <hydra.h>
#include <encoding/payloads/cp_payload.h>
#include <processing/jobs/adopt_children_job.h>
#include <sa/ikev1/tasks/mode_config.h>
Classes
struct private_xauth_t
Typedefs
typedef struct private_xauth_t private_xauth_t
Enumerations
enum xauth_status_t { XAUTH_FAILED = 0, XAUTH_OK = 1 }
Functions
static xauth_method_t * load_method (private_xauth_t *this)
static bool allowed (private_xauth_t *this)
static bool establish (private_xauth_t *this)
static bool is_compliant (private_xauth_t *this, peer_cfg_t *peer_cfg, bool log)
static bool select_compliant_config (private_xauth_t *this)
static bool add_auth_cfg (private_xauth_t *this, identification_t *id, bool local)
METHOD (task_t, build_i_status, status_t, private_xauth_t *this, message_t *message)
METHOD (task_t, process_i_status, status_t, private_xauth_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_xauth_t *this, message_t *message)
METHOD (task_t, build_r_ack, status_t, private_xauth_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_xauth_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_xauth_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_xauth_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_xauth_t *this)
METHOD (task_t, migrate, void, private_xauth_t *this, ike_sa_t *ike_sa)
METHOD (xauth_t, queue_mode_config_push, void, private_xauth_t *this)
METHOD (task_t, destroy, void, private_xauth_t *this)
xauth_t * xauth_create (ike_sa_t *ike_sa, bool initiator)
Typedef Documentation
typedef struct private_xauth_t private_xauth_t
Definition at line 24 of file xauth.c.
Enumeration Type Documentation
enum xauth_status_t
Status types exchanged
Enumerator
XAUTH_FAILED
XAUTH_OK
Definition at line 29 of file xauth.c.
              {
     XAUTH_FAILED = 0,
     XAUTH_OK = 1,
 } xauth_status_t;
Function Documentation
static bool add_auth_cfg (private_xauth_t * this, identification_t * id, bool local) static
Create auth config after successful authentication
Definition at line 268 of file xauth.c.
References auth_cfg_t::add, auth_cfg_create(), AUTH_CLASS_XAUTH, AUTH_RULE_AUTH_CLASS, AUTH_RULE_XAUTH_IDENTITY, identification_t::clone, FALSE, auth_cfg_t::merge, and select_compliant_config().
Referenced by METHOD().
 {
     auth_cfg_t *auth;
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_XAUTH);
     if (id)
     {
         auth->add(auth, AUTH_RULE_XAUTH_IDENTITY, id->clone(id));
     }
     auth->merge(auth, this->ike_sa->get_auth_cfg(this->ike_sa, local), FALSE);
     this->ike_sa->add_auth_cfg(this->ike_sa, local, auth);
     return select_compliant_config(this);
 }
static bool allowed (private_xauth_t * this) static
Check if XAuth connection is allowed to succeed
Definition at line 149 of file xauth.c.
References bus_t::authorize, daemon_t::bus, charon, ike_sa_manager_t::check_uniqueness, DBG1, DBG_IKE, FALSE, daemon_t::ike_sa_manager, and TRUE.
Referenced by do_netstat(), and METHOD().
 {
     if (charon->ike_sa_manager->check_uniqueness(charon->ike_sa_manager,
                                                  this->ike_sa, FALSE))
     {
         DBG1(DBG_IKE, "cancelling XAuth due to uniqueness policy");
         return FALSE;
     }
     if (!charon->bus->authorize(charon->bus, FALSE))
     {
         DBG1(DBG_IKE, "XAuth authorization hook forbids IKE_SA, cancelling");
         return FALSE;
     }
     if (!charon->bus->authorize(charon->bus, TRUE))
     {
         DBG1(DBG_IKE, "final authorization hook forbids IKE_SA, cancelling");
         return FALSE;
     }
     return TRUE;
 }
static bool establish (private_xauth_t * this) static
Set IKE_SA to established state
Definition at line 173 of file xauth.c.
References daemon_t::bus, charon, DBG0, DBG_IKE, IKE_ESTABLISHED, bus_t::ike_updown, and TRUE.
Referenced by METHOD().
 {
     DBG0(DBG_IKE, "IKE_SA %s[%d] established between %H[%Y]...%H[%Y]",
          this->ike_sa->get_name(this->ike_sa),
          this->ike_sa->get_unique_id(this->ike_sa),
          this->ike_sa->get_my_host(this->ike_sa),
          this->ike_sa->get_my_id(this->ike_sa),
          this->ike_sa->get_other_host(this->ike_sa),
          this->ike_sa->get_other_id(this->ike_sa));
     this->ike_sa->set_state(this->ike_sa, IKE_ESTABLISHED);
     charon->bus->ike_updown(charon->bus, this->ike_sa, TRUE);
     return TRUE;
 }
static bool is_compliant (private_xauth_t * this, peer_cfg_t * peer_cfg, bool log) static
Check if we are compliant to a given peer config
Definition at line 192 of file xauth.c.
References auth_cfg_t::complies, peer_cfg_t::create_auth_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, and TRUE.
Referenced by select_compliant_config().
 {
     bool complies = TRUE;
     enumerator_t *e1, *e2;
     auth_cfg_t *c1, *c2;
     e1 = peer_cfg->create_auth_cfg_enumerator(peer_cfg, FALSE);
     e2 = this->ike_sa->create_auth_cfg_enumerator(this->ike_sa, FALSE);
     while (e1->enumerate(e1, &c1))
     {
         if (!e2->enumerate(e2, &c2) || !c2->complies(c2, c1, log))
         {
             complies = FALSE;
             break;
         }
     }
     e1->destroy(e1);
     e2->destroy(e2);
     return complies;
 }
static xauth_method_t* load_method (private_xauth_t * this) static
Load XAuth backend
Definition at line 88 of file xauth.c.
References AUTH_CLASS_XAUTH, AUTH_RULE_AUTH_CLASS, AUTH_RULE_XAUTH_BACKEND, AUTH_RULE_XAUTH_IDENTITY, charon, peer_cfg_t::create_auth_cfg_enumerator, xauth_manager_t::create_instance, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, auth_cfg_t::get, initiator, name, server, daemon_t::xauth, XAUTH_PEER, and XAUTH_SERVER.
Referenced by METHOD().
 {
     identification_t *server, *peer;
     enumerator_t *enumerator;
     xauth_method_t *xauth;
     xauth_role_t role;
     peer_cfg_t *peer_cfg;
     auth_cfg_t *auth;
     char *name;
     if (this->initiator)
     {
         server = this->ike_sa->get_my_id(this->ike_sa);
         peer = this->ike_sa->get_other_id(this->ike_sa);
         role = XAUTH_SERVER;
     }
     else
     {
         peer = this->ike_sa->get_my_id(this->ike_sa);
         server = this->ike_sa->get_other_id(this->ike_sa);
         role = XAUTH_PEER;
     }
     peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
     enumerator = peer_cfg->create_auth_cfg_enumerator(peer_cfg, !this->initiator);
     if (!enumerator->enumerate(enumerator, &auth) ||
         (uintptr_t)auth->get(auth, AUTH_RULE_AUTH_CLASS) != AUTH_CLASS_XAUTH)
     {
         if (!enumerator->enumerate(enumerator, &auth) ||
             (uintptr_t)auth->get(auth, AUTH_RULE_AUTH_CLASS) != AUTH_CLASS_XAUTH)
         {
             DBG1(DBG_CFG, "no XAuth authentication round found");
             enumerator->destroy(enumerator);
             return NULL;
         }
     }
     name = auth->get(auth, AUTH_RULE_XAUTH_BACKEND);
     this->user = auth->get(auth, AUTH_RULE_XAUTH_IDENTITY);
     enumerator->destroy(enumerator);
     if (!this->initiator && this->user)
     {   /* use XAUTH username, if configured */
         peer = this->user;
     }
     xauth = charon->xauth->create_instance(charon->xauth, name, role,
                                            server, peer);
     if (!xauth)
     {
         if (name)
         {
             DBG1(DBG_CFG, "no XAuth method found for '%s'", name);
         }
         else
         {
             DBG1(DBG_CFG, "no XAuth method found");
         }
     }
     return xauth;
 }
METHOD (task_t , build_i_status , status_t , private_xauth_t * this, message_t * message)
Definition at line 284 of file xauth.c.
References cp_payload_t::add_attribute, message_t::add_payload, CFG_SET, configuration_attribute_create_value(), cp, cp_payload_create_type(), NEED_MORE, PLV1_CONFIGURATION, status, and XAUTH_STATUS.
 {
     cp_payload_t *cp;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_SET);
     cp->add_attribute(cp,
             configuration_attribute_create_value(XAUTH_STATUS, this->status));
     message->add_payload(message, (payload_t *)cp);
     return NEED_MORE;
 }
METHOD (task_t , process_i_status , status_t , private_xauth_t * this, message_t * message)
Definition at line 298 of file xauth.c.
References adopt_children_job_create(), CFG_ACK, COND_XAUTH_AUTHENTICATED, cp, DBG1, DBG_IKE, establish(), FAILED, FALSE, message_t::get_payload, cp_payload_t::get_type, lib, mode_config_create(), PLV1_CONFIGURATION, library_t::processor, processor_t::queue_job, adopt_children_job_t::queue_task, status, SUCCESS, TRUE, and XAUTH_OK.
 {
     cp_payload_t *cp;
     adopt_children_job_t *job;
     cp = (cp_payload_t*)message->get_payload(message, PLV1_CONFIGURATION);
     if (!cp || cp->get_type(cp) != CFG_ACK)
     {
         DBG1(DBG_IKE, "received invalid XAUTH status response");
         return FAILED;
     }
     if (this->status != XAUTH_OK)
     {
         DBG1(DBG_IKE, "destroying IKE_SA after failed XAuth authentication");
         return FAILED;
     }
     if (!establish(this))
     {
         return FAILED;
     }
     this->ike_sa->set_condition(this->ike_sa, COND_XAUTH_AUTHENTICATED, TRUE);
     job = adopt_children_job_create(this->ike_sa->get_id(this->ike_sa));
     if (this->mode_config_push)
     {
         job->queue_task(job,
                 (task_t*)mode_config_create(this->ike_sa, TRUE, FALSE));
     }
     lib->processor->queue_job(lib->processor, (job_t*)job);
     return SUCCESS;
 }
METHOD (task_t , build_i , status_t , private_xauth_t * this, message_t * message)
Definition at line 330 of file xauth.c.
References add_auth_cfg(), message_t::add_payload, allowed(), cp, DESTROY_IF, FAILED, FALSE, load_method(), NEED_MORE, status, SUCCESS, and XAUTH_OK.
 {
     if (!this->xauth)
     {
         cp_payload_t *cp = NULL;
         this->xauth = load_method(this);
         if (!this->xauth)
         {
             return FAILED;
         }
         switch (this->xauth->initiate(this->xauth, &cp))
         {
             case NEED_MORE:
                 break;
             case SUCCESS:
                 DESTROY_IF(cp);
                 if (add_auth_cfg(this, NULL, FALSE) && allowed(this))
                 {
                     this->status = XAUTH_OK;
                 }
                 this->public.task.process = _process_i_status;
                 return build_i_status(this, message);
             default:
                 return FAILED;
         }
         message->add_payload(message, (payload_t *)cp);
         return NEED_MORE;
     }
     if (this->cp)
     {   /* send previously generated payload */
         message->add_payload(message, (payload_t *)this->cp);
         this->cp = NULL;
         return NEED_MORE;
     }
     return FAILED;
 }
METHOD (task_t , build_r_ack , status_t , private_xauth_t * this, message_t * message)
Definition at line 370 of file xauth.c.
References cp_payload_t::add_attribute, message_t::add_payload, allowed(), CFG_ACK, chunk_empty, configuration_attribute_create_chunk(), cp, cp_payload_create_type(), establish(), FAILED, identifier, PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, cp_payload_t::set_identifier, status, SUCCESS, XAUTH_OK, and XAUTH_STATUS.
 {
     cp_payload_t *cp;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_ACK);
     cp->set_identifier(cp, this->identifier);
     cp->add_attribute(cp,
             configuration_attribute_create_chunk(
                     PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_STATUS, chunk_empty));
     message->add_payload(message, (payload_t *)cp);
     if (this->status == XAUTH_OK && allowed(this) && establish(this))
     {
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (task_t , process_r , status_t , private_xauth_t * this, message_t * message)
Definition at line 390 of file xauth.c.
References add_auth_cfg(), CFG_REQUEST, CFG_SET, cp, cp_payload_t::create_attribute_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FAILED, cp_payload_t::get_identifier, message_t::get_payload, configuration_attribute_t::get_type, cp_payload_t::get_type, configuration_attribute_t::get_value, identifier, load_method(), NEED_MORE, PLV1_CONFIGURATION, status, SUCCESS, TRUE, XAUTH_OK, and XAUTH_STATUS.
 {
     cp_payload_t *cp;
     if (!this->xauth)
     {
         this->xauth = load_method(this);
         if (!this->xauth)
         {   /* send empty reply */
             return NEED_MORE;
         }
     }
     cp = (cp_payload_t*)message->get_payload(message, PLV1_CONFIGURATION);
     if (!cp)
     {
         DBG1(DBG_IKE, "configuration payload missing in XAuth request");
         return FAILED;
     }
     if (cp->get_type(cp) == CFG_REQUEST)
     {
         switch (this->xauth->process(this->xauth, cp, &this->cp))
         {
             case NEED_MORE:
                 return NEED_MORE;
             case SUCCESS:
             case FAILED:
             default:
                 break;
         }
         this->cp = NULL;
         return NEED_MORE;
     }
     if (cp->get_type(cp) == CFG_SET)
     {
         configuration_attribute_t *attribute;
         enumerator_t *enumerator;
         enumerator = cp->create_attribute_enumerator(cp);
         while (enumerator->enumerate(enumerator, &attribute))
         {
             if (attribute->get_type(attribute) == XAUTH_STATUS)
             {
                 this->status = attribute->get_value(attribute);
             }
         }
         enumerator->destroy(enumerator);
         if (this->status == XAUTH_OK &&
             add_auth_cfg(this, this->xauth->get_identity(this->xauth), TRUE))
         {
             DBG1(DBG_IKE, "XAuth authentication of '%Y' (myself) successful",
                  this->xauth->get_identity(this->xauth));
         }
         else
         {
             DBG1(DBG_IKE, "XAuth authentication of '%Y' (myself) failed",
                  this->xauth->get_identity(this->xauth));
         }
     }
     this->identifier = cp->get_identifier(cp);
     this->public.task.build = _build_r_ack;
     return NEED_MORE;
 }
METHOD (task_t , build_r , status_t , private_xauth_t * this, message_t * message)
Definition at line 454 of file xauth.c.
References message_t::add_payload, CFG_REPLY, cp, cp_payload_create_type(), NEED_MORE, and PLV1_CONFIGURATION.
 {
     if (!this->cp)
     {   /* send empty reply if building data failed */
         this->cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REPLY);
     }
     message->add_payload(message, (payload_t *)this->cp);
     this->cp = NULL;
     return NEED_MORE;
 }
METHOD (task_t , process_i , status_t , private_xauth_t * this, message_t * message)
Definition at line 466 of file xauth.c.
References add_auth_cfg(), allowed(), cp, DBG1, DBG_IKE, FAILED, FALSE, message_t::get_payload, id, NEED_MORE, PLV1_CONFIGURATION, status, SUCCESS, and XAUTH_OK.
 {
     identification_t *id;
     cp_payload_t *cp;
     cp = (cp_payload_t*)message->get_payload(message, PLV1_CONFIGURATION);
     if (!cp)
     {
         DBG1(DBG_IKE, "configuration payload missing in XAuth response");
         return FAILED;
     }
     switch (this->xauth->process(this->xauth, cp, &this->cp))
     {
         case NEED_MORE:
             return NEED_MORE;
         case SUCCESS:
             id = this->xauth->get_identity(this->xauth);
             DBG1(DBG_IKE, "XAuth authentication of '%Y' successful", id);
             if (add_auth_cfg(this, id, FALSE) && allowed(this))
             {
                 this->status = XAUTH_OK;
             }
             break;
         case FAILED:
             DBG1(DBG_IKE, "XAuth authentication of '%Y' failed",
                  this->xauth->get_identity(this->xauth));
             break;
         default:
             return FAILED;
     }
     this->public.task.build = _build_i_status;
     this->public.task.process = _process_i_status;
     return NEED_MORE;
 }
METHOD (task_t , get_type , task_type_t , private_xauth_t * this)
Definition at line 502 of file xauth.c.
References TASK_XAUTH.
 {
     return TASK_XAUTH;
 }
METHOD (task_t , migrate , void , private_xauth_t * this, ike_sa_t * ike_sa)
Definition at line 508 of file xauth.c.
References cp, DESTROY_IF, initiator, status, and XAUTH_FAILED.
 {
     DESTROY_IF(this->xauth);
     DESTROY_IF(this->cp);
     this->ike_sa = ike_sa;
     this->xauth = NULL;
     this->cp = NULL;
     this->user = NULL;
     this->status = XAUTH_FAILED;
     if (this->initiator)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
     }
 }
METHOD (xauth_t , queue_mode_config_push , void , private_xauth_t * this)
Definition at line 532 of file xauth.c.
References TRUE.
 {
     this->mode_config_push = TRUE;
 }
METHOD (task_t , destroy , void , private_xauth_t * this)
Definition at line 538 of file xauth.c.
References cp, DESTROY_IF, and free().
 {
     DESTROY_IF(this->xauth);
     DESTROY_IF(this->cp);
     free(this);
 }
static bool select_compliant_config (private_xauth_t * this) static
Check if we are compliant to current config, switch to another if not
Definition at line 217 of file xauth.c.
References daemon_t::backends, charon, backend_manager_t::create_peer_cfg_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, peer_cfg_t::get_name, IKEV1, is_compliant(), and TRUE.
Referenced by add_auth_cfg().
 {
     peer_cfg_t *peer_cfg = NULL, *old, *current;
     identification_t *my_id, *other_id;
     host_t *my_host, *other_host;
     enumerator_t *enumerator;
     bool aggressive;
     old = this->ike_sa->get_peer_cfg(this->ike_sa);
     if (is_compliant(this, old, TRUE))
     {   /* current config is fine */
         return TRUE;
     }
     DBG1(DBG_CFG, "selected peer config '%s' inacceptable",
          old->get_name(old));
     aggressive = old->use_aggressive(old);
     my_host = this->ike_sa->get_my_host(this->ike_sa);
     other_host = this->ike_sa->get_other_host(this->ike_sa);
     my_id = this->ike_sa->get_my_id(this->ike_sa);
     other_id = this->ike_sa->get_other_id(this->ike_sa);
     enumerator = charon->backends->create_peer_cfg_enumerator(charon->backends,
                                 my_host, other_host, my_id, other_id, IKEV1);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (!current->equals(current, old) &&
             current->use_aggressive(current) == aggressive &&
             is_compliant(this, current, FALSE))
         {
             peer_cfg = current;
             break;
         }
     }
     if (peer_cfg)
     {
         DBG1(DBG_CFG, "switching to peer config '%s'",
              peer_cfg->get_name(peer_cfg));
         this->ike_sa->set_peer_cfg(this->ike_sa, peer_cfg);
     }
     else
     {
         DBG1(DBG_CFG, "no alternative config found");
     }
     enumerator->destroy(enumerator);
     return peer_cfg != NULL;
 }