strongSwan: test_socket.c File Reference
libtls/tests/suites/test_socket.c File Reference
#include <test_suite.h>
#include <unistd.h>
#include <errno.h>
#include <processing/jobs/callback_job.h>
#include <credentials/sets/mem_cred.h>
#include "tls_socket.h"
Classes
struct echo_server_config_t
Functions
START_SETUP (setup_creds)
END_SETUP START_TEARDOWN (teardown_creds)
static job_requeue_t serve_echo (echo_server_config_t *config)
static void start_echo_server (echo_server_config_t *config)
static void run_echo_client (echo_server_config_t *config)
static void test_tls (tls_version_t version, u_int16_t port, bool cauth, u_int i)
START_TEST (test_tls12)
END_TEST START_TEST (test_tls12_mutual)
END_TEST START_TEST (test_tls11)
END_TEST START_TEST (test_tls11_mutual)
END_TEST START_TEST (test_tls10)
END_TEST START_TEST (test_tls10_mutual)
END_TEST Suite * socket_suite_create ()
Variables
static mem_cred_t * creds
static char rsa []
static char ecdsa []
static char rsa_crt []
static char ecdsa_crt []
Function Documentation
static void run_echo_client (echo_server_config_t * config) static
Run client to perform echo test
Definition at line 358 of file libtls/tests/suites/test_socket.c.
References echo_server_config_t::addr, echo_server_config_t::cauth, ck_assert, ck_assert_int_eq, client(), close, connect, data, echo_server_config_t::data, tls_socket_t::destroy, host_t::destroy, identification_t::destroy, EWOULDBLOCK, FALSE, host_t::get_sockaddr, host_t::get_sockaddr_len, host, host_create_from_string(), identification_create_from_string(), chunk_t::len, len, memeq(), echo_server_config_t::port, chunk_t::ptr, tls_socket_t::read, server, socket, tls, tls_socket_create(), TRUE, echo_server_config_t::version, and tls_socket_t::write.
Referenced by test_tls().
 {
     tls_socket_t *tls;
     ssize_t len, rd, wr;
     int fd;
     host_t *host;
     identification_t *server, *client = NULL;
     char buf[128];
     host = host_create_from_string(config->addr, config->port);
     server = identification_create_from_string(config->addr);
     if (config->cauth)
     {
         client = server;
     }
     fd = socket(AF_INET, SOCK_STREAM, 0);
     ck_assert(fd != -1);
     ck_assert(connect(fd, host->get_sockaddr(host),
                       *host->get_sockaddr_len(host)) != -1);
     tls = tls_socket_create(FALSE, server, client, fd, NULL,
                             config->version, TRUE);
     ck_assert(tls != NULL);
     wr = rd = 0;
     while (rd < config->data.len)
     {
         len = tls->write(tls, config->data.ptr + wr, config->data.len - wr);
         ck_assert(len >= 0);
         wr += len;
         len = tls->read(tls, buf, sizeof(buf), FALSE);
         if (len == -1 && errno == EWOULDBLOCK)
         {
             continue;
         }
         if (len == 0)
         {
             ck_assert_int_eq(rd, config->data.len);
             break;
         }
         ck_assert(len > 0);
         ck_assert(rd + len <= config->data.len);
         ck_assert(memeq(buf, config->data.ptr + rd, len));
         rd += len;
     }
     tls->destroy(tls);
     close(fd);
     host->destroy(host);
     server->destroy(server);
 }
static job_requeue_t serve_echo (echo_server_config_t * config) static
Run an echo server
Definition at line 280 of file libtls/tests/suites/test_socket.c.
References accept, echo_server_config_t::addr, echo_server_config_t::cauth, ck_assert, ck_assert_msg, client(), close, tls_socket_t::destroy, identification_t::destroy, echo_server_config_t::fd, identification_create_from_string(), JOB_REQUEUE_NONE, len, tls_socket_t::read, server, strerror, tls, tls_socket_create(), TRUE, echo_server_config_t::version, and tls_socket_t::write.
Referenced by start_echo_server().
 {
     tls_socket_t *tls;
     int sfd, cfd;
     identification_t *server, *client = NULL;
     ssize_t len, total, done;
     char buf[128];
     server = identification_create_from_string(config->addr);
     if (config->cauth)
     {
         client = server;
     }
     sfd = config->fd;
     while (TRUE)
     {
         cfd = accept(sfd, NULL, NULL);
         if (cfd < 0)
         {
             break;
         }
         tls = tls_socket_create(TRUE, server, client, cfd, NULL,
                                 config->version, TRUE);
         ck_assert(tls != NULL);
         while (TRUE)
         {
             len = tls->read(tls, buf, sizeof(buf), TRUE);
             if (len <= 0)
             {
                 break;
             }
             total = 0;
             while (total < len)
             {
                 done = tls->write(tls, buf + total, len - total);
                 ck_assert_msg(done > 0, "%s", strerror(errno));
                 total += done;
             }
         }
         tls->destroy(tls);
         close(cfd);
     }
     server->destroy(server);
     return JOB_REQUEUE_NONE;
 }
END_TEST Suite* socket_suite_create ()
Definition at line 483 of file libtls/tests/suites/test_socket.c.
References count, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_checked_fixture, tcase_add_loop_test, tcase_create, tls_crypto_get_supported_suites(), and TRUE.
 {
     Suite *s;
     TCase *tc;
     int count;
     count = tls_crypto_get_supported_suites(TRUE, NULL);
     s = suite_create("socket");
     tc = tcase_create("TLS 1.2/anon");
     tcase_add_checked_fixture(tc, setup_creds, teardown_creds);
     tcase_add_loop_test(tc, test_tls12, 0, count);
     suite_add_tcase(s, tc);
     tc = tcase_create("TLS 1.2/mutl");
     tcase_add_checked_fixture(tc, setup_creds, teardown_creds);
     tcase_add_loop_test(tc, test_tls12_mutual, 0, count);
     suite_add_tcase(s, tc);
     tc = tcase_create("TLS 1.1/anon");
     tcase_add_checked_fixture(tc, setup_creds, teardown_creds);
     tcase_add_loop_test(tc, test_tls11, 0, count);
     suite_add_tcase(s, tc);
     tc = tcase_create("TLS 1.1/mutl");
     tcase_add_checked_fixture(tc, setup_creds, teardown_creds);
     tcase_add_loop_test(tc, test_tls11_mutual, 0, count);
     suite_add_tcase(s, tc);
     tc = tcase_create("TLS 1.0/anon");
     tcase_add_checked_fixture(tc, setup_creds, teardown_creds);
     tcase_add_loop_test(tc, test_tls10, 0, count);
     suite_add_tcase(s, tc);
     tc = tcase_create("TLS 1.0/mutl");
     tcase_add_checked_fixture(tc, setup_creds, teardown_creds);
     tcase_add_loop_test(tc, test_tls10_mutual, 0, count);
     suite_add_tcase(s, tc);
     return s;
 }
static void start_echo_server (echo_server_config_t * config) static
Start a echo server using config
Definition at line 333 of file libtls/tests/suites/test_socket.c.
References echo_server_config_t::addr, bind, callback_job_create(), ck_assert, ck_assert_msg, host_t::destroy, echo_server_config_t::fd, host_t::get_sockaddr, host_t::get_sockaddr_len, host, host_create_from_string(), lib, echo_server_config_t::port, library_t::processor, processor_t::queue_job, serve_echo(), processor_t::set_threads, setsockopt, socket, and strerror.
Referenced by test_tls().
 {
     host_t *host;
     int on = 1;
     host = host_create_from_string(config->addr, config->port);
     config->fd = socket(AF_INET, SOCK_STREAM, 0);
     ck_assert(config->fd != -1);
     ck_assert(setsockopt(config->fd, SOL_SOCKET, SO_REUSEADDR,
                          (void*)&on, sizeof(on)) != -1);
     ck_assert_msg(bind(config->fd, host->get_sockaddr(host),
                   *host->get_sockaddr_len(host)) != -1, "%s", strerror(errno));
     host->destroy(host);
     ck_assert(listen(config->fd, 1) != -1);
     lib->processor->set_threads(lib->processor, 8);
     lib->processor->queue_job(lib->processor, (job_t*)
                 callback_job_create((void*)serve_echo, config, NULL, NULL));
 }
START_SETUP (setup_creds)
Definition at line 222 of file libtls/tests/suites/test_socket.c.
References mem_cred_t::add_cert, mem_cred_t::add_key, credential_manager_t::add_set, BUILD_BLOB, BUILD_END, cert, CERT_X509, chunk_from_thing, credential_factory_t::create, CRED_CERTIFICATE, CRED_PRIVATE_KEY, library_t::credmgr, library_t::creds, ecdsa, ecdsa_crt, key, KEY_ECDSA, KEY_RSA, lib, mem_cred_create(), rsa, rsa_crt, mem_cred_t::set, and TRUE.
 {
     private_key_t *key;
     certificate_t *cert;
     creds = mem_cred_create();
     key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                              BUILD_BLOB, chunk_from_thing(rsa), BUILD_END);
     if (key)
     {
         creds->add_key(creds, key);
     }
     key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_ECDSA,
                              BUILD_BLOB, chunk_from_thing(ecdsa), BUILD_END);
     if (key)
     {
         creds->add_key(creds, key);
     }
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_BLOB, chunk_from_thing(rsa_crt), BUILD_END);
     if (cert)
     {
         creds->add_cert(creds, TRUE, cert);
     }
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_BLOB, chunk_from_thing(ecdsa_crt), BUILD_END);
     if (cert)
     {
         creds->add_cert(creds, TRUE, cert);
     }
     lib->credmgr->add_set(lib->credmgr, &creds->set);
 }
END_SETUP START_TEARDOWN (teardown_creds)
Definition at line 258 of file libtls/tests/suites/test_socket.c.
References library_t::credmgr, mem_cred_t::destroy, lib, credential_manager_t::remove_set, and mem_cred_t::set.
 {
     lib->credmgr->remove_set(lib->credmgr, &creds->set);
     creds->destroy(creds);
 }
START_TEST (test_tls12)
Definition at line 447 of file libtls/tests/suites/test_socket.c.
References FALSE, test_tls(), and TLS_1_2.
 {
     test_tls(TLS_1_2, 5671, FALSE, _i);
 }
END_TEST START_TEST (test_tls12_mutual)
Definition at line 453 of file libtls/tests/suites/test_socket.c.
References test_tls(), TLS_1_2, and TRUE.
 {
     test_tls(TLS_1_2, 5672, TRUE, _i);
 }
END_TEST START_TEST (test_tls11)
Definition at line 459 of file libtls/tests/suites/test_socket.c.
References FALSE, test_tls(), and TLS_1_1.
 {
     test_tls(TLS_1_1, 5673, FALSE, _i);
 }
END_TEST START_TEST (test_tls11_mutual)
Definition at line 465 of file libtls/tests/suites/test_socket.c.
References test_tls(), TLS_1_1, and TRUE.
 {
     test_tls(TLS_1_1, 5674, TRUE, _i);
 }
END_TEST START_TEST (test_tls10)
Definition at line 471 of file libtls/tests/suites/test_socket.c.
References FALSE, test_tls(), and TLS_1_0.
 {
     test_tls(TLS_1_0, 5675, FALSE, _i);
 }
END_TEST START_TEST (test_tls10_mutual)
Definition at line 477 of file libtls/tests/suites/test_socket.c.
References test_tls(), TLS_1_0, and TRUE.
 {
     test_tls(TLS_1_0, 5676, TRUE, _i);
 }
static void test_tls (tls_version_t version, u_int16_t port, bool cauth, u_int i) static
Common test wrapper function for different test variants
Definition at line 414 of file libtls/tests/suites/test_socket.c.
References addr, chunk_from_chars, ck_assert, close, count, data, echo_server_config_t::fd, free(), INIT, lib, library_t::ns, run_echo_client(), settings_t::set_str, library_t::settings, SHUT_RDWR, shutdown, snprintf, start_echo_server(), tls_cipher_suite_names, tls_crypto_get_supported_suites(), and TRUE.
Referenced by START_TEST(), and threading_suite_create().
 {
     echo_server_config_t *config;
     tls_cipher_suite_t *suites;
     char suite[128];
     int count;
     INIT(config,
         .version = version,
         .addr = "127.0.0.1",
         .port = port,
         .cauth = cauth,
         .data = chunk_from_chars(0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08),
     );
     start_echo_server(config);
     count = tls_crypto_get_supported_suites(TRUE, &suites);
     ck_assert(i < count);
     snprintf(suite, sizeof(suite), "%N", tls_cipher_suite_names, suites[i]);
     lib->settings->set_str(lib->settings, "%s.tls.suites", suite, lib->ns);
     run_echo_client(config);
     free(suites);
     shutdown(config->fd, SHUT_RDWR);
     close(config->fd);
     free(config);
 }
Variable Documentation
mem_cred_t* creds static
Credentials for authentication
Definition at line 29 of file libtls/tests/suites/test_socket.c.
char ecdsa[] static
Initial value:
= {
    0x30,0x81,0xa4,0x02,0x01,0x01,0x04,0x30,0xc0,0x1f,0xfd,0x65,0xc6,0xc4,0x4c,0xb8,
    0xff,0x56,0x08,0xb5,0xbd,0xb8,0xf5,0x93,0xf7,0x51,0x0e,0x92,0x1f,0x06,0xbf,0xa6,
    0xd9,0x1d,0xae,0xa3,0x16,0x0d,0x0f,0xc9,0xd5,0x97,0x90,0x46,0xf1,0x98,0xa8,0x18,
    0x07,0xba,0xcf,0x91,0x8e,0x07,0xed,0x88,0xa0,0x07,0x06,0x05,0x2b,0x81,0x04,0x00,
    0x22,0xa1,0x64,0x03,0x62,0x00,0x04,0xd6,0xba,0xe1,0xf0,0x09,0x22,0x21,0x12,0x69,
    0xed,0x0e,0xd5,0x02,0x8c,0xb8,0x52,0xbb,0x57,0x68,0x0e,0xf3,0xdb,0xb9,0xb1,0xee,
    0x9c,0x67,0xa0,0xb8,0xdc,0x13,0x1e,0x5b,0x44,0x71,0x04,0xef,0x4e,0xe3,0xdd,0xf4,
    0xa6,0xc3,0xba,0x77,0x53,0xb8,0x28,0x5f,0xd2,0x97,0x05,0xa3,0x5b,0xe6,0xde,0x0a,
    0xce,0x11,0xa8,0xaf,0x02,0xbd,0xfa,0x17,0xf9,0xa7,0x38,0x3e,0x5b,0x57,0xb0,0x01,
    0xb3,0xc6,0x09,0x29,0x65,0xae,0xfb,0x87,0x92,0xa3,0xd7,0x3d,0x9a,0x1c,0x52,0x09,
    0xb1,0x47,0xc8,0xf6,0x18,0xbb,0x97,
}
ECDSA private key
Definition at line 115 of file libtls/tests/suites/test_socket.c.
Referenced by build_cipher_suite_list(), METHOD(), parse_pubkey_constraints(), START_SETUP(), and tls_crypto_create().
char ecdsa_crt[] static
TLS certificate for ECDSA key
Definition at line 189 of file libtls/tests/suites/test_socket.c.
Referenced by START_SETUP().
char rsa[] static
RSA private key, 2048 bit
Definition at line 34 of file libtls/tests/suites/test_socket.c.
Referenced by build_cipher_suite_list(), build_emsa_pkcs1_signature(), METHOD(), openssl_rsa_private_key_connect(), openssl_rsa_private_key_gen(), openssl_rsa_private_key_load(), openssl_rsa_public_key_load(), parse_pubkey_constraints(), START_SETUP(), tls_crypto_create(), and verify_emsa_pkcs1_signature().
char rsa_crt[] static
TLS certificate for RSA key
Definition at line 132 of file libtls/tests/suites/test_socket.c.
Referenced by START_SETUP().