strongSwan: database_t Struct Reference
database_t Struct Reference
database
#include "database.h"
Public Attributes
enumerator_t *(* query)(database_t *this, char *sql,...)
int(* execute)(database_t *this, int *rowid, char *sql,...)
bool(* transaction)(database_t *this, bool serializable)
bool(* commit)(database_t *this)
bool(* rollback)(database_t *this)
db_driver_t(* get_driver)(database_t *this)
void(* destroy)(database_t *this)
Detailed Description
Interface for a database implementation.
int affected, rowid, aint;
char *atext;
database_t *db;
enumerator_t *enumerator;
db = lib->database->create("mysql://user:pass@host/database");
affected = db->execute(db, &rowid, "INSERT INTO table VALUES (?, ?)",
                      DB_INT, 77, DB_TEXT, "a text");
printf("inserted %d row, new row ID: %d\n", affected, rowid);
enumerator = db->query(db, "SELECT aint, atext FROM table WHERE aint > ?",
                      DB_INT, 10,      // 1 argument to SQL string
                      DB_INT, DB_TEXT); // 2 enumerated types in query
if (enumerator)
{
   while (enumerator->enumerate(enumerator, &aint, &atext))
   {
       printf("%d: %s\n", aint, atext);
   }
   enumerator->destroy(enumerator);
}
Definition at line 93 of file database.h.
Member Data Documentation
bool(* database_t::commit)(database_t *this)
Commit all changes made during the current transaction.
Returns
TRUE on success
Definition at line 141 of file database.h.
Referenced by add(), add_addresses(), batch(), get_identity(), and resize().
void(* database_t::destroy)(database_t *this)
Destroy a database connection.
Definition at line 163 of file database.h.
Referenced by cleanup(), load_db(), main(), METHOD(), open_database(), and process_packages().
int(* database_t::execute)(database_t *this, int *rowid, char *sql,...)
Execute a query which does not return rows, such as INSERT.
Parameters
rowid pointer to write inserted AUTO_INCREMENT row ID, or NULL
sql sql string, containing '?' placeholders
... list of sql placeholder db_type_t followed by its value
Returns
number of affected rows, < 0 on failure
Definition at line 113 of file database.h.
Referenced by add(), add_address(), add_addresses(), add_attr(), add_hash(), attr_sql_provider_create(), check_lease(), create_pool(), create_session(), del(), del_attr(), delete(), edit(), get_attr_pool(), get_identity(), get_lease(), insert_file_hash(), iterate_enforcements(), medcli_listener_create(), METHOD(), policy_start(), policy_stop(), process_packages(), purge(), resize(), set_state(), and update_database().
db_driver_t(* database_t::get_driver)(database_t *this)
Get the database implementation type.
To allow driver specific SQL or performance optimizations each database implementations can be queried for its type.
Returns
database implementation type
Definition at line 158 of file database.h.
enumerator_t*(* database_t::query)(database_t *this, char *sql,...)
Run a query which returns rows, such as a SELECT.
Parameters
sql sql query string, containing '?' placeholders
... list of sql placeholder db_type_t followed by its value, followed by enumerators arguments as db_type_t's
Returns
enumerator as defined with arguments, NULL on failure
Definition at line 103 of file database.h.
Referenced by add_child_cfgs(), add_esp_proposals(), add_hash(), add_ike_proposals(), add_traffic_selectors(), add_workitems(), check_lease(), create_lease_query(), create_pool(), create_session(), del(), del_attr(), edit(), get_attr_pool(), get_identity(), get_ike_cfg_by_id(), get_lease(), get_peer_cfg_by_id(), get_pool(), insert_file_hash(), iterate_enforcements(), list(), login(), METHOD(), policy_start(), policy_stop(), process_packages(), resize(), schedule_autoinit(), status(), status_attr(), and update_database().
bool(* database_t::rollback)(database_t *this)
Rollback/revert all changes made during the current transaction.
Returns
TRUE on success
Definition at line 148 of file database.h.
Referenced by get_identity().
bool(* database_t::transaction)(database_t *this, bool serializable)
Start a transaction.
A serializable transaction forces a strict separation between other transactions. Due to the performance overhead they should only be used in certain situations (e.g. SELECT->INSERT|UPDATE).
Note
Either commit() or rollback() has to be called to end the transaction.
Transactions are thread-specific. So commit()/rollbak() has to be called from the same thread.
While this method can be called multiple times (commit/rollback have to be called an equal number of times) real nested transactions are not supported. So if any if the "inner" transactions are rolled back the outer most transaction is rolled back.
Parameters
serializable TRUE to create a serializable transaction
Returns
TRUE on success
Definition at line 134 of file database.h.
Referenced by add(), add_addresses(), batch(), get_identity(), and resize().
The documentation for this struct was generated from the following file:
database.h