strongSwan: conf_parser
conf_parser
starter
Classes
struct conf_parser_t
Typedefs
typedef enum conf_parser_section_t conf_parser_section_t
typedef struct conf_parser_t conf_parser_t
Enumerations
enum conf_parser_section_t { CONF_PARSER_CONFIG_SETUP, CONF_PARSER_CONN, CONF_PARSER_CA }
Functions
conf_parser_t * conf_parser_create (const char *file)
Detailed Description
Typedef Documentation
typedef enum conf_parser_section_t conf_parser_section_t
Definition at line 29 of file conf_parser.h.
typedef struct conf_parser_t conf_parser_t
Definition at line 30 of file conf_parser.h.
Enumeration Type Documentation
enum conf_parser_section_t
Type of section
Enumerator
CONF_PARSER_CONFIG_SETUP
config setup
CONF_PARSER_CONN
conn name
CONF_PARSER_CA
ca name
Definition at line 35 of file conf_parser.h.
{
     CONF_PARSER_CONFIG_SETUP,
     CONF_PARSER_CONN,
     CONF_PARSER_CA,
 };
Function Documentation
conf_parser_t* conf_parser_create (const char * file)
Create a conf_parser_t instance.
Parameters
file ipsec.conf file to parse (gets copied)
Returns
conf_parser_t instance
Definition at line 643 of file conf_parser.c.
References array_create(), hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), INIT, section_create(), and strdupnull().
Referenced by confread_load(), and create_parser().
 {
     private_conf_parser_t *this;
     INIT(this,
         .public = {
             .parse = _parse,
             .get_sections = _get_sections,
             .get_section = _get_section,
             .add_section = _add_section,
             .add_setting = _add_setting,
             .destroy = _destroy,
         },
         .file = strdupnull(file),
         .cas = hashtable_create(hashtable_hash_str,
                                 hashtable_equals_str, 8),
         .conns = hashtable_create(hashtable_hash_str,
                                   hashtable_equals_str, 8),
         .conns_order = array_create(0, 0),
         .config_setup = section_create(NULL),
         .ref = 1,
     );
     return &this->public;
 }