strongSwan: tkm_nonceg.c File Reference
tkm_nonceg.c File Reference
#include <tkm/client.h>
#include <tkm/constants.h>
#include "tkm.h"
#include "tkm_nonceg.h"
Classes
struct private_tkm_nonceg_t
Typedefs
typedef struct private_tkm_nonceg_t private_tkm_nonceg_t
Functions
METHOD (nonce_gen_t, get_nonce, bool, private_tkm_nonceg_t *this, size_t size, u_int8_t *buffer)
METHOD (nonce_gen_t, allocate_nonce, bool, private_tkm_nonceg_t *this, size_t size, chunk_t *chunk)
METHOD (nonce_gen_t, destroy, void, private_tkm_nonceg_t *this)
tkm_nonceg_t * tkm_nonceg_create ()
Typedef Documentation
typedef struct private_tkm_nonceg_t private_tkm_nonceg_t
Definition at line 23 of file tkm_nonceg.c.
Function Documentation
METHOD (nonce_gen_t , get_nonce , bool , private_tkm_nonceg_t * this, size_t size, u_int8_t * buffer)
Definition at line 41 of file tkm_nonceg.c.
References tkm_id_manager_t::acquire_id, chunk_clone, chunk_create(), tkm_t::chunk_map, FALSE, tkm_t::idmgr, tkm_chunk_map_t::insert, memcpy, tkm_id_manager_t::release_id, tkm, TKM_CTX_NONCE, and TRUE.
 {
     nonce_type nonce;
     uint64_t nc_id;
     nc_id = tkm->idmgr->acquire_id(tkm->idmgr, TKM_CTX_NONCE);
     if (!nc_id)
     {
         return FALSE;
     }
     if (ike_nc_create(nc_id, size, &nonce) != TKM_OK)
     {
         tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_NONCE, nc_id);
         return FALSE;
     }
     memcpy(buffer, &nonce.data, size);
     this->nonce = chunk_clone(chunk_create(buffer, size));
     tkm->chunk_map->insert(tkm->chunk_map, &this->nonce, nc_id);
     return TRUE;
 }
METHOD (nonce_gen_t , allocate_nonce , bool , private_tkm_nonceg_t * this, size_t size, chunk_t * chunk)
Definition at line 65 of file tkm_nonceg.c.
References chunk_alloc, get_nonce(), chunk_t::len, and chunk_t::ptr.
 {
     *chunk = chunk_alloc(size);
     return get_nonce(this, chunk->len, chunk->ptr);
 }
METHOD (nonce_gen_t , destroy , void , private_tkm_nonceg_t * this)
Definition at line 72 of file tkm_nonceg.c.
References chunk_free(), tkm_t::chunk_map, DBG1, DBG_IKE, free(), tkm_chunk_map_t::get_id, tkm_t::idmgr, tkm_id_manager_t::release_id, tkm_chunk_map_t::remove, tkm, and TKM_CTX_NONCE.
 {
     uint64_t nc_id;
     nc_id = tkm->chunk_map->get_id(tkm->chunk_map, &this->nonce);
     if (nc_id)
     {
         DBG1(DBG_IKE, "resetting stale nonce context %llu", nc_id);
         if (ike_nc_reset(nc_id) != TKM_OK)
         {
             DBG1(DBG_IKE, "failed to reset nonce context %llu", nc_id);
         }
         tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_NONCE, nc_id);
         tkm->chunk_map->remove(tkm->chunk_map, &this->nonce);
     }
     chunk_free(&this->nonce);
     free(this);
 }