strongSwan: openssl_hasher
openssl_hasher
openssl
Classes
struct openssl_hasher_t
Typedefs
typedef struct openssl_hasher_t openssl_hasher_t
Functions
openssl_hasher_t * openssl_hasher_create (hash_algorithm_t algo)
Detailed Description
Typedef Documentation
typedef struct openssl_hasher_t openssl_hasher_t
Definition at line 24 of file openssl_hasher.h.
Function Documentation
openssl_hasher_t* openssl_hasher_create (hash_algorithm_t algo)
Constructor to create openssl_hasher_t.
Parameters
algo algorithm
Returns
openssl_hasher_t, NULL if not supported
Definition at line 94 of file openssl_hasher.c.
References ctx, destroy(), enum_to_name(), free(), hash_algorithm_short_names, hasher, INIT, and name.
Referenced by METHOD().
 {
     private_openssl_hasher_t *this;
     char* name;
     name = enum_to_name(hash_algorithm_short_names, algo);
     if (!name)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .hasher = {
                 .get_hash = _get_hash,
                 .allocate_hash = _allocate_hash,
                 .get_hash_size = _get_hash_size,
                 .reset = _reset,
                 .destroy = _destroy,
             },
         },
     );
     this->hasher = EVP_get_digestbyname(name);
     if (!this->hasher)
     {
         /* OpenSSL does not support the requested algo */
         free(this);
         return NULL;
     }
     this->ctx = EVP_MD_CTX_create();
     /* initialization */
     if (!reset(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }