strongSwan: eap_manager
eap_manager
eap
Classes
struct eap_manager_t
Typedefs
typedef struct eap_manager_t eap_manager_t
Functions
eap_manager_t * eap_manager_create ()
Detailed Description
Typedef Documentation
typedef struct eap_manager_t eap_manager_t
Definition at line 27 of file eap_manager.h.
Function Documentation
eap_manager_t* eap_manager_create ()
Create a eap_manager instance.
Definition at line 184 of file eap_manager.c.
References INIT, linked_list_create(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by daemon_create().
 {
     private_eap_manager_t *this;
     INIT(this,
             .public = {
                 .add_method = _add_method,
                 .remove_method = _remove_method,
                 .create_enumerator = _create_enumerator,
                 .create_instance = _create_instance,
                 .destroy = _destroy,
             },
             .methods = linked_list_create(),
             .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return &this->public;
 }