strongSwan: add_notify.c File Reference
add_notify.c File Reference
#include "hook.h"
Classes
struct private_add_notify_t
Typedefs
typedef struct private_add_notify_t private_add_notify_t
Functions
METHOD (listener_t, message, bool, private_add_notify_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (hook_t, destroy, void, private_add_notify_t *this)
hook_t * add_notify_hook_create (char *name)
Typedef Documentation
typedef struct private_add_notify_t private_add_notify_t
Definition at line 18 of file add_notify.c.
Function Documentation
hook_t* add_notify_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 113 of file add_notify.c.
References conftest, FALSE, settings_t::get_bool, settings_t::get_int, settings_t::get_str, INIT, conftest_t::test, and TRUE.
 {
     private_add_notify_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .message = _message,
             },
             .destroy = _destroy,
         },
         .req = conftest->test->get_bool(conftest->test,
                                         "hooks.%s.request", TRUE, name),
         .id = conftest->test->get_int(conftest->test,
                                         "hooks.%s.id", 0, name),
         .type = conftest->test->get_str(conftest->test,
                                         "hooks.%s.type", "", name),
         .data = conftest->test->get_str(conftest->test,
                                         "hooks.%s.data", "", name),
         .spi = conftest->test->get_int(conftest->test,
                                         "hooks.%s.spi", 0, name),
         .esp = conftest->test->get_bool(conftest->test,
                                         "hooks.%s.esp", FALSE, name),
     );
     return &this->hook;
 }
METHOD (listener_t , message , bool , private_add_notify_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 61 of file add_notify.c.
References message_t::add_payload, chunk_clone, chunk_create(), chunk_empty, chunk_from_hex(), chunk_skip(), data, DBG1, DBG_CFG, enum_from_name, free(), message_t::get_message_id, message_t::get_request, id, chunk_t::len, notify(), notify_payload_create_from_protocol_and_type(), notify_type_names, notify_payload_t::payload_interface, PLV2_NOTIFY, PROTO_ESP, PROTO_IKE, chunk_t::ptr, req(), notify_payload_t::set_notification_data, notify_payload_t::set_spi, strncaseeq(), TRUE, and type.
 {
     if (!incoming && plain &&
         message->get_request(message) == this->req &&
         message->get_message_id(message) == this->id)
     {
         notify_type_t type;
         notify_payload_t *notify;
         chunk_t data = chunk_empty;
         type = atoi(this->type);
         if (!type)
         {
             if (!enum_from_name(notify_type_names, this->type, &type))
             {
                 DBG1(DBG_CFG, "unknown notify: '%s', skipped", this->type);
                 return TRUE;
             }
         }
         if (strncaseeq(this->data, "0x", 2))
         {
             data = chunk_skip(chunk_create(this->data, strlen(this->data)), 2);
             data = chunk_from_hex(data, NULL);
         }
         else if (strlen(this->data))
         {
             data = chunk_clone(chunk_create(this->data, strlen(this->data)));
         }
         notify = notify_payload_create_from_protocol_and_type(PLV2_NOTIFY,
                                     this->esp ? PROTO_ESP : PROTO_IKE, type);
         notify->set_spi(notify, this->spi);
         if (data.len)
         {
             notify->set_notification_data(notify, data);
             free(data.ptr);
         }
         message->add_payload(message, &notify->payload_interface);
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_add_notify_t * this)
Definition at line 104 of file add_notify.c.
References free().
 {
     free(this);
 }