strongSwan: pt_tls_server
pt_tls_server
libpttls
Classes
struct pt_tls_server_t
Typedefs
typedef struct pt_tls_server_t pt_tls_server_t
Functions
pt_tls_server_t * pt_tls_server_create (identification_t *server, int fd, pt_tls_auth_t auth, tnccs_t *tnccs)
Detailed Description
Typedef Documentation
typedef struct pt_tls_server_t pt_tls_server_t
Definition at line 30 of file pt_tls_server.h.
Function Documentation
pt_tls_server_t* pt_tls_server_create (identification_t * server, int fd, pt_tls_auth_t auth, tnccs_t * tnccs)
Create a pt_tls_server connection instance.
Parameters
server TLS server identity
fd client connection socket
auth client authentication requirements
tnccs inner TNCCS protocol handler to use for this connection
Returns
PT-TLS server
See header
Definition at line 523 of file pt_tls_server.c.
References FALSE, free(), INIT, tls, TLS_1_2, tls_socket_create(), and TRUE.
Referenced by METHOD(), and pt_tls_receive().
 {
     private_pt_tls_server_t *this;
     INIT(this,
         .public = {
             .handle = _handle,
             .get_fd = _get_fd,
             .destroy = _destroy,
         },
         .state = PT_TLS_SERVER_VERSION,
         .tls = tls_socket_create(TRUE, server, NULL, fd, NULL, TLS_1_2, FALSE),
         .tnccs = (tls_t*)tnccs,
         .auth = auth,
     );
     if (!this->tls)
     {
         this->tnccs->destroy(this->tnccs);
         free(this);
         return NULL;
     }
     return &this->public;
 }