strongSwan: tnc.c File Reference
tnc.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include "tnc.h"
#include <utils/lexparser.h>
#include <utils/debug.h>
Classes
struct private_tnc_t
Macros
#define _GNU_SOURCE /* for stdndup() */
#define DEFAULT_TNC_CONFIG "/etc/tnc_config"
Typedefs
typedef struct private_tnc_t private_tnc_t
typedef tnccs_manager_t *(* tnc_create_tnccs_manager_t)(void)
typedef imc_manager_t *(* tnc_create_imc_manager_t)(void)
typedef imv_manager_t *(* tnc_create_imv_manager_t)(void)
Functions
void libtnccs_init (void)
void libtnccs_deinit (void)
static bool load_imcvs_from_config (char *filename, bool is_imc)
bool tnc_manager_register (plugin_t *plugin, plugin_feature_t *feature, bool reg, void *data)
Variables
tnc_t * tnc
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 16 of file tnc.c.
#define DEFAULT_TNC_CONFIG "/etc/tnc_config"
Definition at line 32 of file tnc.c.
Referenced by tnc_manager_register().
Typedef Documentation
typedef struct private_tnc_t private_tnc_t
Definition at line 35 of file tnc.c.
typedef imc_manager_t*(* tnc_create_imc_manager_t)(void)
Definition at line 38 of file tnc.c.
typedef imv_manager_t*(* tnc_create_imv_manager_t)(void)
Definition at line 39 of file tnc.c.
typedef tnccs_manager_t*(* tnc_create_tnccs_manager_t)(void)
Definition at line 37 of file tnc.c.
Function Documentation
static bool load_imcvs_from_config (char * filename, bool is_imc) static
Definition at line 103 of file tnc.c.
References chunk_map(), chunk_unmap(), DBG1, DBG_TNC, eat_whitespace(), extract_token(), FALSE, fetchline(), free(), tnc_t::imcs, tnc_t::imvs, chunk_t::len, imc_manager_t::load, imv_manager_t::load, match(), name, path, chunk_t::ptr, src, strerror, strndup(), and TRUE.
Referenced by tnc_manager_register().
 {
     bool success = FALSE;
     int line_nr = 0;
     chunk_t *src, line;
     char *label;
     if (!filename || !*filename)
     {
         return TRUE;
     }
     label = is_imc ? "IMC" : "IMV";
     DBG1(DBG_TNC, "loading %ss from '%s'", label, filename);
     src = chunk_map(filename, FALSE);
     if (!src)
     {
         DBG1(DBG_TNC, "opening configuration file '%s' failed: %s", filename,
              strerror(errno));
         return FALSE;
     }
     while (fetchline(src, &line))
     {
         char *name, *path;
         chunk_t token;
         line_nr++;
         /* skip comments or empty lines */
         if (*line.ptr == '#' || !eat_whitespace(&line))
         {
             continue;
         }
         /* determine keyword */
         if (!extract_token(&token, ' ', &line))
         {
             DBG1(DBG_TNC, "line %d: keyword must be followed by a space",
                            line_nr);
             break;
         }
         /* only interested in IMCs or IMVs depending on label */
         if (!match(label, &token))
         {
             continue;
         }
         /* advance to the IMC/IMV name and extract it */
         if (!extract_token(&token, '"', &line) ||
             !extract_token(&token, '"', &line))
         {
             DBG1(DBG_TNC, "line %d: %s name must be set in double quotes",
                            line_nr, label);
             break;
         }
         /* copy the IMC/IMV name */
         name = strndup(token.ptr, token.len);
         /* advance to the IMC/IMV path and extract it */
         if (!eat_whitespace(&line))
         {
             DBG1(DBG_TNC, "line %d: %s path is missing", line_nr, label);
             free(name);
             break;
         }
         if (!extract_token(&token, ' ', &line))
         {
             token = line;
         }
         /* copy the IMC/IMV path */
         path = strndup(token.ptr, token.len);
         /* load and register an IMC/IMV instance */
         if (is_imc)
         {
             success = tnc->imcs->load(tnc->imcs, name, path);
         }
         else
         {
             success = tnc->imvs->load(tnc->imvs, name, path);
         }
         free(name);
         free(path);
         if (!success)
         {
             break;
         }
     }
     chunk_unmap(src);
     return success;
 }