strongSwan: proposal_substructure_t Struct Reference
proposal_substructure_t Struct Reference
proposal_substructure
#include "proposal_substructure.h"
Public Attributes
payload_t payload_interface
void(* set_proposal_number)(proposal_substructure_t *this, u_int8_t proposal_number)
u_int8_t(* get_proposal_number)(proposal_substructure_t *this)
void(* set_protocol_id)(proposal_substructure_t *this, u_int8_t protocol_id)
u_int8_t(* get_protocol_id)(proposal_substructure_t *this)
void(* set_is_last_proposal)(proposal_substructure_t *this, bool is_last)
chunk_t(* get_spi)(proposal_substructure_t *this)
void(* set_spi)(proposal_substructure_t *this, chunk_t spi)
bool(* get_cpi)(proposal_substructure_t *this, u_int16_t *cpi)
void(* get_proposals)(proposal_substructure_t *this, linked_list_t *list)
enumerator_t *(* create_substructure_enumerator)(proposal_substructure_t *this)
u_int32_t(* get_lifetime)(proposal_substructure_t *this)
u_int64_t(* get_lifebytes)(proposal_substructure_t *this)
auth_method_t(* get_auth_method)(proposal_substructure_t *this)
ipsec_mode_t(* get_encap_mode)(proposal_substructure_t *this, bool *udp)
void(* destroy)(proposal_substructure_t *this)
Detailed Description
Class representing an IKEv1/IKEv2 proposal substructure.
Definition at line 49 of file proposal_substructure.h.
Member Data Documentation
enumerator_t*(* proposal_substructure_t::create_substructure_enumerator)(proposal_substructure_t *this)
Create an enumerator over transform substructures.
Returns
enumerator over transform_substructure_t
Definition at line 131 of file proposal_substructure.h.
Referenced by set_byte().
void(* proposal_substructure_t::destroy)(proposal_substructure_t *this)
Destroys an proposal_substructure_t object.
Definition at line 165 of file proposal_substructure.h.
auth_method_t(* proposal_substructure_t::get_auth_method)(proposal_substructure_t *this)
Get the first authentication method from the proposal (IKEv1 only).
Returns
auth method, or AUTH_NONE
Definition at line 152 of file proposal_substructure.h.
Referenced by METHOD().
bool(* proposal_substructure_t::get_cpi)(proposal_substructure_t *this, u_int16_t *cpi)
Gets the CPI of the current proposal (IKEv1 only).
Parameters
cpi the CPI if a supported algorithm is proposed
Returns
TRUE if a supported algorithm is proposed
Definition at line 117 of file proposal_substructure.h.
Referenced by METHOD().
ipsec_mode_t(* proposal_substructure_t::get_encap_mode)(proposal_substructure_t *this, bool *udp)
Get the (first) encapsulation mode from a proposal (IKEv1 only).
Parameters
udp set to TRUE if UDP encapsulation used
Returns
ipsec encapsulation mode
Definition at line 160 of file proposal_substructure.h.
Referenced by METHOD().
u_int64_t(* proposal_substructure_t::get_lifebytes)(proposal_substructure_t *this)
Get the (shortest) life duration of a proposal (IKEv1 only).
Returns
life duration, in bytes
Definition at line 145 of file proposal_substructure.h.
Referenced by METHOD().
u_int32_t(* proposal_substructure_t::get_lifetime)(proposal_substructure_t *this)
Get the (shortest) lifetime of a proposal (IKEv1 only).
Returns
lifetime, in seconds
Definition at line 138 of file proposal_substructure.h.
Referenced by METHOD().
u_int8_t(* proposal_substructure_t::get_proposal_number)(proposal_substructure_t *this)
get proposal number of current proposal.
Returns
proposal number of current proposal substructure.
Definition at line 68 of file proposal_substructure.h.
Referenced by METHOD(), and sa_payload_create_from_proposals_v1().
void(* proposal_substructure_t::get_proposals)(proposal_substructure_t *this, linked_list_t *list)
Get proposals contained in a propsal_substructure_t.
Parameters
list list to add created proposals to
Definition at line 124 of file proposal_substructure.h.
Referenced by METHOD().
u_int8_t(* proposal_substructure_t::get_protocol_id)(proposal_substructure_t *this)
get protocol id of current proposal.
Returns
protocol id of current proposal substructure.
Definition at line 83 of file proposal_substructure.h.
Referenced by METHOD().
chunk_t(* proposal_substructure_t::get_spi)(proposal_substructure_t *this)
Returns the currently set SPI of this proposal.
Returns
chunk_t pointing to the value
Definition at line 100 of file proposal_substructure.h.
payload_t proposal_substructure_t::payload_interface
The payload_t interface.
Definition at line 54 of file proposal_substructure.h.
Referenced by METHOD(), and set_byte().
void(* proposal_substructure_t::set_is_last_proposal)(proposal_substructure_t *this, bool is_last)
Sets the next_payload field of this substructure
If this is the last proposal, next payload field is set to 0, otherwise to 2
Parameters
is_last When TRUE, next payload field is set to 0, otherwise to 2
Definition at line 93 of file proposal_substructure.h.
Referenced by add_proposal_v2(), and sa_payload_create_from_proposals_v1().
void(* proposal_substructure_t::set_proposal_number)(proposal_substructure_t *this, u_int8_t proposal_number)
Sets the proposal number of current proposal.
Parameters
id proposal number to set
Definition at line 61 of file proposal_substructure.h.
Referenced by add_proposal_v2(), and sa_payload_create_from_proposals_v1().
void(* proposal_substructure_t::set_protocol_id)(proposal_substructure_t *this, u_int8_t protocol_id)
Sets the protocol id of current proposal.
Parameters
id protocol id to set
Definition at line 75 of file proposal_substructure.h.
void(* proposal_substructure_t::set_spi)(proposal_substructure_t *this, chunk_t spi)
Sets the SPI of the current proposal.
Warning
SPI is getting copied
Parameters
spi chunk_t pointing to the value to set
Definition at line 109 of file proposal_substructure.h.
The documentation for this struct was generated from the following file:
proposal_substructure.h