strongSwan: mutex.c File Reference
windows/mutex.c File Reference
#include "thread.h"
#include <utils/debug.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
Classes
struct private_mutex_t
struct private_condvar_t
Typedefs
typedef struct private_mutex_t private_mutex_t
typedef struct private_condvar_t private_condvar_t
Functions
METHOD (mutex_t, lock, void, private_mutex_t *this)
METHOD (mutex_t, unlock, void, private_mutex_t *this)
METHOD (mutex_t, mutex_destroy, void, private_mutex_t *this)
mutex_t * mutex_create (mutex_type_t type)
METHOD (condvar_t, timed_wait, bool, private_condvar_t *this, mutex_t *pubmutex, u_int timeout)
METHOD (condvar_t, wait_, void, private_condvar_t *this, mutex_t *mutex)
METHOD (condvar_t, timed_wait_abs, bool, private_condvar_t *this, mutex_t *mutex, timeval_t tv)
METHOD (condvar_t, signal_, void, private_condvar_t *this)
METHOD (condvar_t, broadcast, void, private_condvar_t *this)
METHOD (condvar_t, condvar_destroy, void, private_condvar_t *this)
condvar_t * condvar_create (condvar_type_t type)
Typedef Documentation
typedef struct private_condvar_t private_condvar_t
Definition at line 23 of file windows/mutex.c.
typedef struct private_mutex_t private_mutex_t
Definition at line 22 of file windows/mutex.c.
Function Documentation
METHOD (mutex_t , lock , void , private_mutex_t * this)
Definition at line 63 of file windows/mutex.c.
 {
     EnterCriticalSection(&this->cs);
     this->times++;
 }
METHOD (mutex_t , unlock , void , private_mutex_t * this)
Definition at line 70 of file windows/mutex.c.
 {
     this->times--;
     LeaveCriticalSection(&this->cs);
 }
METHOD (mutex_t , mutex_destroy , void , private_mutex_t * this)
Definition at line 77 of file windows/mutex.c.
References free().
 {
     DeleteCriticalSection(&this->cs);
     free(this);
 }
METHOD (condvar_t , timed_wait , bool , private_condvar_t * this, mutex_t * pubmutex, u_int timeout)
Definition at line 105 of file windows/mutex.c.
References private_mutex_t::cs, mutex, thread_set_active_condvar(), and private_mutex_t::times.
 {
     private_mutex_t *mutex = (private_mutex_t*)pubmutex;
     u_int times;
     bool ret;
     thread_set_active_condvar(&this->cv);
     /* while a CriticalSection is recursive, waiting in a condvar releases
      * only one mutex. So release (and reaquire) all locks except the last. */
     times = mutex->times;
     while (mutex->times-- > 1)
     {
         LeaveCriticalSection(&mutex->cs);
     }
     ret = SleepConditionVariableCS(&this->cv, &mutex->cs, timeout);
     while (++mutex->times < times)
     {
         EnterCriticalSection(&mutex->cs);
     }
     thread_set_active_condvar(NULL);
     return ret == 0;
 }
METHOD (condvar_t , wait_ , void , private_condvar_t * this, mutex_t * mutex)
Definition at line 134 of file windows/mutex.c.
 {
     timed_wait(this, mutex, INFINITE);
 }
METHOD (condvar_t , timed_wait_abs , bool , private_condvar_t * this, mutex_t * mutex, timeval_t tv)
Definition at line 140 of file windows/mutex.c.
References DWORD, time_monotonic(), timersub(), and TRUE.
 {
     DWORD timeout;
     timeval_t now, diff;
     time_monotonic(&now);
     if (timercmp(&now, &tv, >))
     {
         return TRUE;
     }
     timersub(&tv, &now, &diff);
     timeout = diff.tv_sec * 1000 + diff.tv_usec / 1000;
     return timed_wait(this, mutex, timeout);
 }
METHOD (condvar_t , signal_ , void , private_condvar_t * this)
Definition at line 157 of file windows/mutex.c.
 {
     WakeConditionVariable(&this->cv);
 }
METHOD (condvar_t , broadcast , void , private_condvar_t * this)
Definition at line 163 of file windows/mutex.c.
 {
     WakeAllConditionVariable(&this->cv);
 }
METHOD (condvar_t , condvar_destroy , void , private_condvar_t * this)
Definition at line 169 of file windows/mutex.c.
References free().
 {
     free(this);
 }