strongSwan: sshkey_public_key
sshkey_public_key
sshkey
Classes
struct sshkey_public_key_t
Typedefs
typedef struct sshkey_public_key_t sshkey_public_key_t
Functions
sshkey_public_key_t * sshkey_public_key_load (key_type_t type, va_list args)
certificate_t * sshkey_certificate_load (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct sshkey_public_key_t sshkey_public_key_t
Definition at line 27 of file sshkey_builder.h.
Function Documentation
certificate_t* sshkey_certificate_load (certificate_type_t type, va_list args)
Load a public key in RFC 4253 format as certificate.
Takes a BUILD_FROM_FILE and BUILD_SUBJECT argument.
Parameters
type type of the certificate, must be CERT_TRUSTED_PUBKEY
args builder_part_t argument list
Returns
built certificate, NULL on failure
See header.
Definition at line 242 of file sshkey_builder.c.
References BUILD_END, BUILD_FROM_FILE, BUILD_PUBLIC_KEY, BUILD_SUBJECT, cert, CERT_TRUSTED_PUBKEY, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, public_key_t::destroy, key, lib, load_from_file(), subject, and TRUE.
Referenced by METHOD().
 {
     certificate_t *cert;
     public_key_t *key;
     identification_t *subject = NULL;
     char *file = NULL;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_FROM_FILE:
                 file = va_arg(args, char*);
                 continue;
             case BUILD_SUBJECT:
                 subject = va_arg(args, identification_t*);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!file || !subject)
     {
         return NULL;
     }
     key = (public_key_t*)load_from_file(file);
     if (!key)
     {
         return NULL;
     }
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                               CERT_TRUSTED_PUBKEY, BUILD_PUBLIC_KEY, key,
                               BUILD_SUBJECT, subject, BUILD_END);
     key->destroy(key);
     return cert;
 }
sshkey_public_key_t* sshkey_public_key_load (key_type_t type, va_list args)
Load a public key in RFC 4253 format.
Takes a BUILD_BLOB_SSHKEY to parse the public key.
Parameters
type type of the key, must be KEY_ANY
args builder_part_t argument list
Returns
built key, NULL on failure
See header.
Definition at line 199 of file sshkey_builder.c.
References blob, BUILD_BLOB, BUILD_BLOB_SSHKEY, BUILD_END, BUILD_FROM_FILE, chunk_empty, load_from_blob(), load_from_file(), parse_public_key(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     chunk_t sshkey = chunk_empty, blob = chunk_empty;
     char *file = NULL;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_SSHKEY:
                 sshkey = va_arg(args, chunk_t);
                 continue;
             case BUILD_FROM_FILE:
                 file = va_arg(args, char*);
                 continue;
             case BUILD_BLOB:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (sshkey.ptr)
     {
         return parse_public_key(sshkey);
     }
     if (file)
     {
         return load_from_file(file);
     }
     if (blob.ptr)
     {
         return load_from_blob(blob);
     }
     return NULL;
 }