strongSwan: imv_attestation_state.c File Reference
imv_attestation_state.c File Reference
#include "imv_attestation_state.h"
#include <imcv.h>
#include <imv/imv_lang_string.h>
#include "imv/imv_reason_string.h"
#include <tncif_policy.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_imv_attestation_state_t
struct func_comp_t
Typedefs
typedef struct
private_imv_attestation_state_t private_imv_attestation_state_t
typedef struct file_meas_request_t file_meas_request_t
typedef struct func_comp_t func_comp_t
Functions
static void free_func_comp (func_comp_t *this)
METHOD (imv_state_t, get_connection_id, TNC_ConnectionID, private_imv_attestation_state_t *this)
METHOD (imv_state_t, has_long, bool, private_imv_attestation_state_t *this)
METHOD (imv_state_t, has_excl, bool, private_imv_attestation_state_t *this)
METHOD (imv_state_t, set_flags, void, private_imv_attestation_state_t *this, bool has_long, bool has_excl)
METHOD (imv_state_t, set_max_msg_len, void, private_imv_attestation_state_t *this, uint32_t max_msg_len)
METHOD (imv_state_t, get_max_msg_len, uint32_t, private_imv_attestation_state_t *this)
METHOD (imv_state_t, set_action_flags, void, private_imv_attestation_state_t *this, uint32_t flags)
METHOD (imv_state_t, get_action_flags, uint32_t, private_imv_attestation_state_t *this)
METHOD (imv_state_t, set_session, void, private_imv_attestation_state_t *this, imv_session_t *session)
METHOD (imv_state_t, get_session, imv_session_t *, private_imv_attestation_state_t *this)
METHOD (imv_state_t, get_contracts, seg_contract_manager_t *, private_imv_attestation_state_t *this)
METHOD (imv_state_t, change_state, void, private_imv_attestation_state_t *this, TNC_ConnectionState new_state)
METHOD (imv_state_t, get_recommendation, void, private_imv_attestation_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
METHOD (imv_state_t, set_recommendation, void, private_imv_attestation_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, update_recommendation, void, private_imv_attestation_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_attestation_state_t, add_file_meas_reasons, void, private_imv_attestation_state_t *this, imv_reason_string_t *reason_string)
METHOD (imv_attestation_state_t, add_comp_evid_reasons, void, private_imv_attestation_state_t *this, imv_reason_string_t *reason_string)
METHOD (imv_state_t, get_reason_string, bool, private_imv_attestation_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
METHOD (imv_state_t, get_remediation_instructions, bool, private_imv_attestation_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
METHOD (imv_state_t, destroy, void, private_imv_attestation_state_t *this)
METHOD (imv_attestation_state_t, get_handshake_state, imv_attestation_handshake_state_t, private_imv_attestation_state_t *this)
METHOD (imv_attestation_state_t, set_handshake_state, void, private_imv_attestation_state_t *this, imv_attestation_handshake_state_t new_state)
METHOD (imv_attestation_state_t, get_pts, pts_t *, private_imv_attestation_state_t *this)
METHOD (imv_attestation_state_t, create_component, pts_component_t *, private_imv_attestation_state_t *this, pts_comp_func_name_t *name, uint32_t depth, pts_database_t *pts_db)
static bool entry_filter (void *null, func_comp_t **entry, uint8_t *flags, void *i2, uint32_t *depth, void *i3, pts_comp_func_name_t **comp_name)
METHOD (imv_attestation_state_t, create_component_enumerator, enumerator_t *, private_imv_attestation_state_t *this)
METHOD (imv_attestation_state_t, get_component, pts_component_t *, private_imv_attestation_state_t *this, pts_comp_func_name_t *name)
METHOD (imv_attestation_state_t, get_measurement_error, uint32_t, private_imv_attestation_state_t *this)
METHOD (imv_attestation_state_t, set_measurement_error, void, private_imv_attestation_state_t *this, uint32_t error)
METHOD (imv_attestation_state_t, finalize_components, void, private_imv_attestation_state_t *this, bio_writer_t *result)
imv_state_t * imv_attestation_state_create (TNC_ConnectionID connection_id)
Variables
static char * languages [] = { "en", "de", "mn" }
static imv_lang_string_t reason_file_meas_fail []
static imv_lang_string_t reason_file_meas_pend []
static imv_lang_string_t reason_no_trusted_aik []
static imv_lang_string_t reason_comp_evid_fail []
static imv_lang_string_t reason_comp_evid_pend []
static imv_lang_string_t reason_tpm_quote_fail []
Typedef Documentation
typedef struct file_meas_request_t file_meas_request_t
Definition at line 29 of file imv_attestation_state.c.
typedef struct func_comp_t func_comp_t
Definition at line 30 of file imv_attestation_state.c.
typedef struct private_imv_attestation_state_t private_imv_attestation_state_t
Definition at line 28 of file imv_attestation_state.c.
Function Documentation
static bool entry_filter (void * null, func_comp_t ** entry, uint8_t * flags, void * i2, uint32_t * depth, void * i3, pts_comp_func_name_t ** comp_name) static
Enumerate file measurement entries
Definition at line 424 of file imv_attestation_state.c.
References pts_component_t::get_depth, pts_component_t::get_evidence_flags, name, and TRUE.
Referenced by METHOD().
 {
     pts_component_t *comp;
     pts_comp_func_name_t *name;
     comp = (*entry)->comp;
     name = (*entry)->name;
     *flags = comp->get_evidence_flags(comp);
     *depth = comp->get_depth(comp);
     *comp_name = name;
     return TRUE;
 }
static void free_func_comp (func_comp_t * this) static
Frees a func_comp_t object
Definition at line 130 of file imv_attestation_state.c.
References free(), and name.
Referenced by METHOD().
 {
     this->comp->destroy(this->comp);
     this->name->destroy(this->name);
     free(this);
 }
METHOD (imv_state_t , get_connection_id , TNC_ConnectionID , private_imv_attestation_state_t * this)
Definition at line 186 of file imv_attestation_state.c.
 {
     return this->connection_id;
 }
METHOD (imv_state_t , has_long , bool , private_imv_attestation_state_t * this)
Definition at line 192 of file imv_attestation_state.c.
 {
     return this->has_long;
 }
METHOD (imv_state_t , has_excl , bool , private_imv_attestation_state_t * this)
Definition at line 198 of file imv_attestation_state.c.
 {
     return this->has_excl;
 }
METHOD (imv_state_t , set_flags , void , private_imv_attestation_state_t * this, bool has_long, bool has_excl)
Definition at line 204 of file imv_attestation_state.c.
 {
     this->has_long = has_long;
     this->has_excl = has_excl;
 }
METHOD (imv_state_t , set_max_msg_len , void , private_imv_attestation_state_t * this, uint32_t max_msg_len)
Definition at line 211 of file imv_attestation_state.c.
 {
     this->max_msg_len = max_msg_len;
 }
METHOD (imv_state_t , get_max_msg_len , uint32_t , private_imv_attestation_state_t * this)
Definition at line 217 of file imv_attestation_state.c.
 {
     return this->max_msg_len;
 }
METHOD (imv_state_t , set_action_flags , void , private_imv_attestation_state_t * this, uint32_t flags)
Definition at line 223 of file imv_attestation_state.c.
References flags.
 {
     this->action_flags |= flags;
 }
METHOD (imv_state_t , get_action_flags , uint32_t , private_imv_attestation_state_t * this)
Definition at line 229 of file imv_attestation_state.c.
 {
     return this->action_flags;
 }
METHOD (imv_state_t , set_session , void , private_imv_attestation_state_t * this, imv_session_t * session)
Definition at line 235 of file imv_attestation_state.c.
 {
     this->session = session;
 }
METHOD (imv_state_t , get_session , imv_session_t * , private_imv_attestation_state_t * this)
Definition at line 241 of file imv_attestation_state.c.
 {
     return this->session;
 }
METHOD (imv_state_t , get_contracts , seg_contract_manager_t * , private_imv_attestation_state_t * this)
Definition at line 247 of file imv_attestation_state.c.
 {
     return this->contracts;
 }
METHOD (imv_state_t , change_state , void , private_imv_attestation_state_t * this, TNC_ConnectionState new_state)
Definition at line 253 of file imv_attestation_state.c.
 {
     this->state = new_state;
 }
METHOD (imv_state_t , get_recommendation , void , private_imv_attestation_state_t * this, TNC_IMV_Action_Recommendation * rec, TNC_IMV_Evaluation_Result * eval)
Definition at line 259 of file imv_attestation_state.c.
 {
     *rec = this->rec;
     *eval = this->eval;
 }
METHOD (imv_state_t , set_recommendation , void , private_imv_attestation_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 267 of file imv_attestation_state.c.
 {
     this->rec = rec;
     this->eval = eval;
 }
METHOD (imv_state_t , update_recommendation , void , private_imv_attestation_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 275 of file imv_attestation_state.c.
References tncif_policy_update_evaluation(), and tncif_policy_update_recommendation().
 {
     this->rec  = tncif_policy_update_recommendation(this->rec, rec);
     this->eval = tncif_policy_update_evaluation(this->eval, eval);
 }
METHOD (imv_attestation_state_t , add_file_meas_reasons , void , private_imv_attestation_state_t * this, imv_reason_string_t * reason_string)
Definition at line 283 of file imv_attestation_state.c.
References imv_reason_string_t::add_reason, IMV_ATTESTATION_ERROR_FILE_MEAS_FAIL, and IMV_ATTESTATION_ERROR_FILE_MEAS_PEND.
 {
     if (this->measurement_error & IMV_ATTESTATION_ERROR_FILE_MEAS_FAIL)
     {
         reason_string->add_reason(reason_string, reason_file_meas_fail);
     }
     if (this->measurement_error & IMV_ATTESTATION_ERROR_FILE_MEAS_PEND)
     {
         reason_string->add_reason(reason_string, reason_file_meas_pend);
     }
 }
METHOD (imv_attestation_state_t , add_comp_evid_reasons , void , private_imv_attestation_state_t * this, imv_reason_string_t * reason_string)
Definition at line 296 of file imv_attestation_state.c.
References imv_reason_string_t::add_reason, IMV_ATTESTATION_ERROR_COMP_EVID_FAIL, IMV_ATTESTATION_ERROR_COMP_EVID_PEND, IMV_ATTESTATION_ERROR_NO_TRUSTED_AIK, and IMV_ATTESTATION_ERROR_TPM_QUOTE_FAIL.
 {
     if (this->measurement_error & IMV_ATTESTATION_ERROR_NO_TRUSTED_AIK)
     {
         reason_string->add_reason(reason_string, reason_no_trusted_aik);
     }
     if (this->measurement_error & IMV_ATTESTATION_ERROR_COMP_EVID_FAIL)
     {
         reason_string->add_reason(reason_string, reason_comp_evid_fail);
     }
     if (this->measurement_error & IMV_ATTESTATION_ERROR_COMP_EVID_PEND)
     {
         reason_string->add_reason(reason_string, reason_comp_evid_pend);
     }
     if (this->measurement_error & IMV_ATTESTATION_ERROR_TPM_QUOTE_FAIL)
     {
         reason_string->add_reason(reason_string, reason_tpm_quote_fail);
     }
 }
METHOD (imv_state_t , get_reason_string , bool , private_imv_attestation_state_t * this, enumerator_t * language_enumerator, chunk_t * reason_string, char ** reason_language)
Definition at line 317 of file imv_attestation_state.c.
References countof, DESTROY_IF, imv_lang_string_select_lang(), imv_reason_string_create(), languages, and TRUE.
 {
     *reason_language = imv_lang_string_select_lang(language_enumerator,
                                               languages, countof(languages));
     /* Instantiate a TNC Reason String object */
     DESTROY_IF(this->reason_string);
     this->reason_string = imv_reason_string_create(*reason_language, "\n");
     add_file_meas_reasons(this, this->reason_string);
     add_comp_evid_reasons(this, this->reason_string);
     *reason_string = this->reason_string->get_encoding(this->reason_string);
     return TRUE;
 }
METHOD (imv_state_t , get_remediation_instructions , bool , private_imv_attestation_state_t * this, enumerator_t * language_enumerator, chunk_t * string, char ** lang_code, char ** uri)
Definition at line 334 of file imv_attestation_state.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (imv_state_t , destroy , void , private_imv_attestation_state_t * this)
Definition at line 341 of file imv_attestation_state.c.
References DESTROY_IF, free(), and free_func_comp().
 {
     DESTROY_IF(this->session);
     DESTROY_IF(this->reason_string);
     this->components->destroy_function(this->components, (void *)free_func_comp);
     this->pts->destroy(this->pts);
     this->contracts->destroy(this->contracts);
     free(this);
 }
METHOD (imv_attestation_state_t , get_handshake_state , imv_attestation_handshake_state_t , private_imv_attestation_state_t * this)
Definition at line 352 of file imv_attestation_state.c.
 {
     return this->handshake_state;
 }
METHOD (imv_attestation_state_t , set_handshake_state , void , private_imv_attestation_state_t * this, imv_attestation_handshake_state_t new_state)
Definition at line 358 of file imv_attestation_state.c.
 {
     this->handshake_state = new_state;
 }
METHOD (imv_attestation_state_t , get_pts , pts_t * , private_imv_attestation_state_t * this)
Definition at line 365 of file imv_attestation_state.c.
 {
     return this->pts;
 }
METHOD (imv_attestation_state_t , create_component , pts_component_t * , private_imv_attestation_state_t * this, pts_comp_func_name_t * name, uint32_t depth, pts_database_t * pts_db)
Definition at line 371 of file imv_attestation_state.c.
References pts_comp_func_name_t::clone, func_comp_t::comp, pts_component_manager_t::create, enumerator_t::destroy, enumerator_t::enumerate, pts_comp_func_name_t::equals, FALSE, found, pts_component_t::get_comp_func_name, pts_component_t::get_ref, imcv_pts_components, malloc_thing, func_comp_t::name, and TRUE.
 {
     enumerator_t *enumerator;
     func_comp_t *entry, *new_entry;
     pts_component_t *component;
     bool found = FALSE;
     enumerator = this->components->create_enumerator(this->components);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (name->equals(name, entry->comp->get_comp_func_name(entry->comp)))
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (found)
     {
         if (name->equals(name, entry->name))
         {
             /* duplicate entry */
             return NULL;
         }
         new_entry = malloc_thing(func_comp_t);
         new_entry->name = name->clone(name);
         new_entry->comp = entry->comp->get_ref(entry->comp);
         this->components->insert_last(this->components, new_entry);
         return entry->comp;
     }
     else
     {
         component = imcv_pts_components->create(imcv_pts_components,
                                                 name, depth, pts_db);
         if (!component)
         {
             /* unsupported component */
             return NULL;
         }
         new_entry = malloc_thing(func_comp_t);
         new_entry->name = name->clone(name);
         new_entry->comp = component;
         this->components->insert_last(this->components, new_entry);
         return component;
     }
 }
METHOD (imv_attestation_state_t , create_component_enumerator , enumerator_t * , private_imv_attestation_state_t * this)
Definition at line 441 of file imv_attestation_state.c.
References entry_filter(), and enumerator_create_filter().
 {
     return enumerator_create_filter(
                 this->components->create_enumerator(this->components),
                 (void*)entry_filter, NULL, NULL);
 }
METHOD (imv_attestation_state_t , get_component , pts_component_t * , private_imv_attestation_state_t * this, pts_comp_func_name_t * name)
Definition at line 449 of file imv_attestation_state.c.
References func_comp_t::comp, enumerator_t::destroy, enumerator_t::enumerate, pts_comp_func_name_t::equals, found, and func_comp_t::name.
 {
     enumerator_t *enumerator;
     func_comp_t *entry;
     pts_component_t *found = NULL;
     enumerator = this->components->create_enumerator(this->components);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (name->equals(name, entry->name))
         {
             found = entry->comp;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (imv_attestation_state_t , get_measurement_error , uint32_t , private_imv_attestation_state_t * this)
Definition at line 469 of file imv_attestation_state.c.
 {
     return this->measurement_error;
 }
METHOD (imv_attestation_state_t , set_measurement_error , void , private_imv_attestation_state_t * this, uint32_t error)
Definition at line 475 of file imv_attestation_state.c.
 {
     this->measurement_error |= error;
 }
METHOD (imv_attestation_state_t , finalize_components , void , private_imv_attestation_state_t * this, bio_writer_t * result)
Definition at line 481 of file imv_attestation_state.c.
References chunk_from_str, func_comp_t::comp, FALSE, pts_component_t::finalize, free_func_comp(), pts_comp_func_name_t::get_qualifier, IMV_ATTESTATION_ERROR_COMP_EVID_PEND, func_comp_t::name, result, SUCCESS, TRUE, and bio_writer_t::write_data.
 {
     func_comp_t *entry;
     bool first = TRUE;
     while (this->components->remove_last(this->components,
                                         (void**)&entry) == SUCCESS)
     {
         if (first)
         {
             first = FALSE;
         }
         else
         {
             result->write_data(result, chunk_from_str("; "));
         }
         if (!entry->comp->finalize(entry->comp,
                                    entry->name->get_qualifier(entry->name),
                                    result))
         {
             set_measurement_error(this, IMV_ATTESTATION_ERROR_COMP_EVID_PEND);
         }
         free_func_comp(entry);
     }
 }
Variable Documentation
char* languages[] = { "en", "de", "mn" } static
Supported languages
Definition at line 140 of file imv_attestation_state.c.
Referenced by METHOD().
imv_lang_string_t reason_comp_evid_fail[] static
Initial value:
= {
    { "en", "Incorrect component evidence" },
    { "de", "Falsche Komponenten-Evidenz" },
    { "mn", "  " },
    { NULL, NULL }
}
Definition at line 165 of file imv_attestation_state.c.
imv_lang_string_t reason_comp_evid_pend[] static
Initial value:
= {
    { "en", "Pending component evidence" },
    { "de", "Ausstehende Komponenten-Evidenz" },
    { "mn", "X  " },
    { NULL, NULL }
}
Definition at line 172 of file imv_attestation_state.c.
imv_lang_string_t reason_file_meas_fail[] static
Initial value:
= {
    { "en", "Incorrect file measurement" },
    { "de", "Falsche Dateimessung" },
    { "mn", "  " },
    { NULL, NULL }
}
Table of reason strings
Definition at line 145 of file imv_attestation_state.c.
imv_lang_string_t reason_file_meas_pend[] static
Initial value:
= {
    { "en", "Pending file measurement" },
    { "de", "Ausstehende Dateimessung" },
    { "mn", "X  " },
    { NULL, NULL }
}
Definition at line 152 of file imv_attestation_state.c.
imv_lang_string_t reason_no_trusted_aik[] static
Initial value:
= {
    { "en", "No trusted AIK available" },
    { "de", "Kein vetrauenswrdiger AIK verfgbar" },
    { NULL, NULL }
}
Definition at line 159 of file imv_attestation_state.c.
imv_lang_string_t reason_tpm_quote_fail[] static
Initial value:
= {
    { "en", "Invalid TPM Quote signature received" },
    { "de", "Falsche TPM Quote Signature erhalten" },
    { "mn", " TPM Quote  " },
    { NULL, NULL }
}
Definition at line 179 of file imv_attestation_state.c.