strongSwan: af_alg_ops.c File Reference
af_alg_ops.c File Reference
#include "af_alg_ops.h"
#include <unistd.h>
#include <errno.h>
#include <linux/socket.h>
#include <utils/debug.h>
Classes
struct private_af_alg_ops_t
Typedefs
typedef struct private_af_alg_ops_t private_af_alg_ops_t
Functions
METHOD (af_alg_ops_t, reset, void, private_af_alg_ops_t *this)
METHOD (af_alg_ops_t, hash, bool, private_af_alg_ops_t *this, chunk_t data, char *out, size_t outlen)
METHOD (af_alg_ops_t, crypt, bool, private_af_alg_ops_t *this, u_int32_t type, chunk_t iv, chunk_t data, char *out)
METHOD (af_alg_ops_t, set_key, bool, private_af_alg_ops_t *this, chunk_t key)
METHOD (af_alg_ops_t, destroy, void, private_af_alg_ops_t *this)
af_alg_ops_t * af_alg_ops_create (char *type, char *alg)
Typedef Documentation
typedef struct private_af_alg_ops_t private_af_alg_ops_t
Definition at line 24 of file af_alg_ops.c.
Function Documentation
METHOD (af_alg_ops_t , reset , void , private_af_alg_ops_t * this)
Definition at line 47 of file af_alg_ops.c.
References close.
 {
     if (this->op != -1)
     {
         close(this->op);
         this->op = -1;
     }
 }
METHOD (af_alg_ops_t , hash , bool , private_af_alg_ops_t * this, chunk_t data, char * out, size_t outlen)
Definition at line 57 of file af_alg_ops.c.
References accept, chunk_skip(), DBG1, DBG_LIB, FALSE, chunk_t::len, len, chunk_t::ptr, read, send, strerror, and TRUE.
 {
     ssize_t len;
     while (this->op == -1)
     {
         this->op = accept(this->tfm, NULL, 0);
         if (this->op == -1 && errno != EINTR)
         {
             DBG1(DBG_LIB, "opening AF_ALG hasher failed: %s", strerror(errno));
             return FALSE;
         }
     }
     do
     {
         len = send(this->op, data.ptr, data.len, out ? 0 : MSG_MORE);
         if (len == -1)
         {
             if (errno == EINTR)
             {
                 continue;
             }
             DBG1(DBG_LIB, "writing to AF_ALG hasher failed: %s", strerror(errno));
             return FALSE;
         }
         data = chunk_skip(data, len);
     }
     while (data.len);
     if (out)
     {
         while (outlen)
         {
             len = read(this->op, out, outlen);
             if (len == -1)
             {
                 if (errno == EINTR)
                 {
                     continue;
                 }
                 DBG1(DBG_LIB, "reading AF_ALG hasher failed: %s", strerror(errno));
                 return FALSE;
             }
             outlen -= len;
             out += len;
         }
         reset(this);
     }
     return TRUE;
 }
METHOD (af_alg_ops_t , crypt , bool , private_af_alg_ops_t * this, u_int32_t type, chunk_t iv, chunk_t data, char * out)
Definition at line 110 of file af_alg_ops.c.
References accept, ALG_SET_IV, ALG_SET_OP, chunk_skip(), close, DBG1, DBG_LIB, FALSE, af_alg_iv::iv, af_alg_iv::ivlen, chunk_t::len, len, memcpy, memset, chunk_t::ptr, read, SOL_ALG, strerror, and TRUE.
 {
     struct msghdr msg = {};
     struct cmsghdr *cmsg;
     struct af_alg_iv *ivm;
     struct iovec iov;
     char buf[CMSG_SPACE(sizeof(type)) +
              CMSG_SPACE(offsetof(struct af_alg_iv, iv) + iv.len)];
     ssize_t len;
     int op;
     do
     {
         op = accept(this->tfm, NULL, 0);
         if (op == -1 && errno != EINTR)
         {
             DBG1(DBG_LIB, "accepting AF_ALG crypter failed: %s", strerror(errno));
             return FALSE;
         }
     }
     while (op == -1);
     memset(buf, 0, sizeof(buf));
     msg.msg_control = buf;
     msg.msg_controllen = sizeof(buf);
     cmsg = CMSG_FIRSTHDR(&msg);
     cmsg->cmsg_level = SOL_ALG;
     cmsg->cmsg_type = ALG_SET_OP;
     cmsg->cmsg_len = CMSG_LEN(sizeof(type));
     memcpy(CMSG_DATA(cmsg), &type, sizeof(type));
     cmsg = CMSG_NXTHDR(&msg, cmsg);
     cmsg->cmsg_level = SOL_ALG;
     cmsg->cmsg_type = ALG_SET_IV;
     cmsg->cmsg_len = CMSG_LEN(offsetof(struct af_alg_iv, iv) + iv.len);
     ivm = (void*)CMSG_DATA(cmsg);
     ivm->ivlen = iv.len;
     memcpy(ivm->iv, iv.ptr, iv.len);
     msg.msg_iov = &iov;
     msg.msg_iovlen = 1;
     while (data.len)
     {
         iov.iov_base = data.ptr;
         iov.iov_len = data.len;
         len = sendmsg(op, &msg, 0);
         if (len == -1)
         {
             if (errno == EINTR)
             {
                 continue;
             }
             DBG1(DBG_LIB, "writing to AF_ALG crypter failed: %s", strerror(errno));
             return FALSE;
         }
         while (read(op, out, len) != len)
         {
             if (errno != EINTR)
             {
                 DBG1(DBG_LIB, "reading from AF_ALG crypter failed: %s",
                      strerror(errno));
                 return FALSE;
             }
         }
         data = chunk_skip(data, len);
         /* no IV for subsequent data chunks */
         msg.msg_controllen = 0;
     }
     close(op);
     return TRUE;
 }
METHOD (af_alg_ops_t , set_key , bool , private_af_alg_ops_t * this, chunk_t key)
Definition at line 188 of file af_alg_ops.c.
References ALG_SET_KEY, DBG1, DBG_LIB, FALSE, chunk_t::len, chunk_t::ptr, setsockopt, SOL_ALG, strerror, and TRUE.
 {
     if (setsockopt(this->tfm, SOL_ALG, ALG_SET_KEY, key.ptr, key.len) == -1)
     {
         DBG1(DBG_LIB, "setting AF_ALG key failed: %s", strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
METHOD (af_alg_ops_t , destroy , void , private_af_alg_ops_t * this)
Definition at line 199 of file af_alg_ops.c.
References close, and free().
 {
     close(this->tfm);
     if (this->op != -1)
     {
         close(this->op);
     }
     free(this);
 }