strongSwan: guest_t Struct Reference
guest_t Struct Reference
#include "guest.h"
Public Attributes
char *(* get_name)(guest_t *this)
pid_t(* get_pid)(guest_t *this)
guest_state_t(* get_state)(guest_t *this)
bool(* start)(guest_t *this, invoke_function_t invoke, void *data, idle_function_t idle)
void(* stop)(guest_t *this, idle_function_t idle)
iface_t *(* create_iface)(guest_t *this, char *name)
void(* destroy_iface)(guest_t *this, iface_t *iface)
enumerator_t *(* create_iface_enumerator)(guest_t *this)
bool(* add_overlay)(guest_t *this, char *dir)
bool(* del_overlay)(guest_t *this, char *dir)
bool(* pop_overlay)(guest_t *this)
int(* exec)(guest_t *this, void(*cb)(void *, char *, size_t), void *data, char *cmd,...)
int(* exec_str)(guest_t *this, void(*cb)(void *, char *), bool lines, void *data, char *cmd,...)
void(* sigchild)(guest_t *this)
void(* destroy)(guest_t *this)
Detailed Description
A guest is a UML instance running on the host.
Definition at line 73 of file guest.h.
Member Data Documentation
bool(* guest_t::add_overlay)(guest_t *this, char *dir)
Adds a COWFS overlay. The directory is created if it does not exist.
Parameters
dir directory where overlay diff should point to
Returns
FALSE, if failed
Definition at line 142 of file guest.h.
Referenced by guest_add_overlay(), and METHOD().
iface_t*(* guest_t::create_iface)(guest_t *this, char *name)
Create a new interface in the current scenario.
Parameters
name name of the interface in the guest
Returns
created interface, or NULL if failed
Definition at line 120 of file guest.h.
Referenced by connect_guest(), and guest_add_iface().
enumerator_t*(* guest_t::create_iface_enumerator)(guest_t *this)
Create an enumerator over all guest interfaces.
Returns
enumerator over iface_t's
Definition at line 134 of file guest.h.
Referenced by guest_each_iface(), and guest_find_iface().
bool(* guest_t::del_overlay)(guest_t *this, char *dir)
Removes the specified COWFS overlay.
Parameters
dir directory where overlay diff points to
Returns
FALSE, if no found
Definition at line 150 of file guest.h.
Referenced by guest_del_overlay(), and METHOD().
void(* guest_t::destroy)(guest_t *this)
Close and destroy a guest with all interfaces
Definition at line 197 of file guest.h.
Referenced by METHOD().
void(* guest_t::destroy_iface)(guest_t *this, iface_t *iface)
Destroy an interface on guest.
Parameters
iface interface to destroy
Definition at line 127 of file guest.h.
Referenced by iface_delete().
int(* guest_t::exec)(guest_t *this, void(*cb)(void *, char *, size_t), void *data, char *cmd,...)
Execute a command on the guests mconsole.
Parameters
cb callback to call for each read block
data data to pass to callback
cmd command to execute
... printf style argument list for cmd
Returns
return value
Definition at line 168 of file guest.h.
int(* guest_t::exec_str)(guest_t *this, void(*cb)(void *, char *), bool lines, void *data, char *cmd,...)
Execute a command on the guests mconsole, with output formatter.
If lines is TRUE, callback is invoked for each output line. Otherwise the full result is returned in one callback invocation.
Note
This function does not work with binary output.
Parameters
cb callback to call for each line or for the complete output
lines TRUE if the callback should be called for each line
data data to pass to callback
cmd command to execute
... printf style argument list for cmd
Returns
return value
Definition at line 186 of file guest.h.
Referenced by guest_exec(), and guest_mconsole().
char*(* guest_t::get_name)(guest_t *this)
Get the name of this guest.
Returns
name of the guest
Definition at line 80 of file guest.h.
Referenced by create_page(), guest_hash_create(), guest_to_s(), and METHOD().
pid_t(* guest_t::get_pid)(guest_t *this)
Get the process ID of the guest child process.
Returns
name of the guest
Definition at line 87 of file guest.h.
Referenced by child_exited(), guest_delete(), guest_running(), and sigchld_handler().
guest_state_t(* guest_t::get_state)(guest_t *this)
Get the state of the guest (stopped, started, etc.).
Returns
guests state
Definition at line 94 of file guest.h.
Referenced by connect_guest(), quit(), start_all_guests(), start_guest(), and stop_guest().
bool(* guest_t::pop_overlay)(guest_t *this)
Removes the latest COWFS overlay.
Returns
FALSE, if no overlay was found
Definition at line 157 of file guest.h.
Referenced by guest_pop_overlay(), and METHOD().
void(* guest_t::sigchild)(guest_t *this)
Called whenever a SIGCHILD for the guests PID is received.
Definition at line 192 of file guest.h.
Referenced by child_exited(), and sigchld_handler().
bool(* guest_t::start)(guest_t *this, invoke_function_t invoke, void *data, idle_function_t idle)
Start the guest.
Parameters
invoke UML guest invocation function
data data to pass back to invoke function
idle idle function to call while waiting on child
Returns
TRUE if guest successfully started
Definition at line 104 of file guest.h.
Referenced by guest_start(), start_all_guests(), and start_guest().
void(* guest_t::stop)(guest_t *this, idle_function_t idle)
Kill the guest.
Parameters
idle idle function to call while waiting to termination
Definition at line 112 of file guest.h.
Referenced by delete_guest(), guest_stop(), METHOD(), quit(), and stop_guest().
The documentation for this struct was generated from the following file:
guest.h