strongSwan: eap_radius_dae.c File Reference
eap_radius_dae.c File Reference
#include "eap_radius_dae.h"
#include <radius_message.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <unistd.h>
#include <errno.h>
#include <daemon.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
#include <processing/jobs/delete_ike_sa_job.h>
Classes
struct private_eap_radius_dae_t
struct entry_t
Macros
#define RADIUS_DAE_PORT 3799
Typedefs
typedef struct
private_eap_radius_dae_t private_eap_radius_dae_t
Functions
static void entry_destroy (entry_t *entry)
static void save_retransmit (private_eap_radius_dae_t *this, radius_message_t *response, host_t *client)
static void send_message (private_eap_radius_dae_t *this, radius_message_t *message, host_t *client)
static bool send_retransmit (private_eap_radius_dae_t *this, radius_message_t *request, host_t *client)
static void send_response (private_eap_radius_dae_t *this, radius_message_t *request, radius_message_code_t code, host_t *client)
static void add_matching_ike_sas (linked_list_t *list, identification_t *user)
static linked_list_t * get_matching_ike_sas (private_eap_radius_dae_t *this, radius_message_t *request, host_t *client)
static void process_disconnect (private_eap_radius_dae_t *this, radius_message_t *request, host_t *client)
static void apply_lifetime (private_eap_radius_dae_t *this, ike_sa_id_t *id, u_int32_t lifetime)
static void process_coa (private_eap_radius_dae_t *this, radius_message_t *request, host_t *client)
static bool receive (private_eap_radius_dae_t *this)
static bool open_socket (private_eap_radius_dae_t *this)
METHOD (eap_radius_dae_t, destroy, void, private_eap_radius_dae_t *this)
eap_radius_dae_t * eap_radius_dae_create (eap_radius_accounting_t *accounting)
Macro Definition Documentation
#define RADIUS_DAE_PORT 3799
Definition at line 31 of file eap_radius_dae.c.
Referenced by open_socket().
Typedef Documentation
typedef struct private_eap_radius_dae_t private_eap_radius_dae_t
Definition at line 33 of file eap_radius_dae.c.
Function Documentation
static void add_matching_ike_sas (linked_list_t * list, identification_t * user) static
Add all IKE_SAs matching to user to a list
Definition at line 202 of file eap_radius_dae.c.
References charon, ike_sa_id_t::clone, ike_sa_manager_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, ike_sa_t::get_id, ike_sa_t::get_other_eap_id, id, daemon_t::ike_sa_manager, linked_list_t::insert_last, and identification_t::matches.
Referenced by get_matching_ike_sas().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     ike_sa_id_t *id;
     enumerator = charon->ike_sa_manager->create_enumerator(
                                                 charon->ike_sa_manager, FALSE);
     while (enumerator->enumerate(enumerator, &ike_sa))
     {
         if (user->matches(user, ike_sa->get_other_eap_id(ike_sa)))
         {
             id = ike_sa->get_id(ike_sa);
             list->insert_last(list, id->clone(id));
         }
     }
     enumerator->destroy(enumerator);
 }
static void apply_lifetime (private_eap_radius_dae_t * this, ike_sa_id_t * id, u_int32_t lifetime) static
Apply a new lifetime to an IKE_SA
Definition at line 295 of file eap_radius_dae.c.
References charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout, DESTROY_ME, daemon_t::ike_sa_manager, and ike_sa_t::set_auth_lifetime.
Referenced by process_coa().
 {
     ike_sa_t *ike_sa;
     ike_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager, id);
     if (ike_sa)
     {
         if (ike_sa->set_auth_lifetime(ike_sa, lifetime) == DESTROY_ME)
         {
             charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                         ike_sa);
         }
         else
         {
             charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
         }
     }
 }
static void entry_destroy (entry_t * entry) static
Clean up an entry
Definition at line 89 of file eap_radius_dae.c.
References entry_t::client, host_t::destroy, radius_message_t::destroy, free(), and entry_t::response.
Referenced by METHOD().
 {
     entry->response->destroy(entry->response);
     entry->client->destroy(entry->client);
     free(entry);
 }
static linked_list_t* get_matching_ike_sas (private_eap_radius_dae_t * this, radius_message_t * request, host_t * client) static
Get list of IKE_SAs matching a Disconnect/CoA request
Definition at line 224 of file eap_radius_dae.c.
References add_matching_ike_sas(), client(), radius_message_t::create_enumerator, data, DBG1, DBG_CFG, enumerator_t::destroy, identification_t::destroy, enumerator_t::enumerate, radius_message_t::get_code, identification_create_from_data(), chunk_t::len, linked_list_create(), radius_message_code_names, RAT_USER_NAME, and type.
Referenced by process_coa(), and process_disconnect().
 {
     enumerator_t *enumerator;
     identification_t *user;
     linked_list_t *ids;
     chunk_t data;
     int type;
     ids = linked_list_create();
     enumerator = request->create_enumerator(request);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (type == RAT_USER_NAME && data.len)
         {
             user = identification_create_from_data(data);
             DBG1(DBG_CFG, "received RADIUS DAE %N for %Y from %H",
                  radius_message_code_names, request->get_code(request),
                  user, client);
             add_matching_ike_sas(ids, user);
             user->destroy(user);
         }
     }
     enumerator->destroy(enumerator);
     return ids;
 }
METHOD (eap_radius_dae_t , destroy , void , private_eap_radius_dae_t * this)
Definition at line 477 of file eap_radius_dae.c.
References close, DESTROY_IF, entry_destroy(), free(), hasher, lib, watcher_t::remove, signer, and library_t::watcher.
 {
     if (this->fd != -1)
     {
         lib->watcher->remove(lib->watcher, this->fd);
         close(this->fd);
     }
     DESTROY_IF(this->signer);
     DESTROY_IF(this->hasher);
     this->responses->destroy_function(this->responses, (void*)entry_destroy);
     free(this);
 }
static bool open_socket (private_eap_radius_dae_t * this) static
Open DAE socket
Definition at line 442 of file eap_radius_dae.c.
References bind, DBG1, DBG_CFG, host_t::destroy, FALSE, settings_t::get_int, host_t::get_sockaddr, host_t::get_sockaddr_len, settings_t::get_str, host, host_create_from_string(), lib, library_t::ns, RADIUS_DAE_PORT, library_t::settings, socket, strerror, and TRUE.
Referenced by eap_radius_dae_create().
 {
     host_t *host;
     this->fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
     if (this->fd == -1)
     {
         DBG1(DBG_CFG, "unable to open RADIUS DAE socket: %s", strerror(errno));
         return FALSE;
     }
     host = host_create_from_string(
                 lib->settings->get_str(lib->settings,
                             "%s.plugins.eap-radius.dae.listen", "0.0.0.0",
                             lib->ns),
                 lib->settings->get_int(lib->settings,
                             "%s.plugins.eap-radius.dae.port", RADIUS_DAE_PORT,
                             lib->ns));
     if (!host)
     {
         DBG1(DBG_CFG, "invalid RADIUS DAE listen address");
         return FALSE;
     }
     if (bind(this->fd, host->get_sockaddr(host),
              *host->get_sockaddr_len(host)) == -1)
     {
         DBG1(DBG_CFG, "unable to bind RADIUS DAE socket: %s", strerror(errno));
         host->destroy(host);
         return FALSE;
     }
     host->destroy(host);
     return TRUE;
 }
static void process_coa (private_eap_radius_dae_t * this, radius_message_t * request, host_t * client) static
Process a DAE CoA request, send response
Definition at line 318 of file eap_radius_dae.c.
References apply_lifetime(), linked_list_t::create_enumerator, radius_message_t::create_enumerator, data, DBG1, DBG_CFG, enumerator_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, FALSE, linked_list_t::get_count, get_matching_ike_sas(), id, chunk_t::len, chunk_t::ptr, radius_message_code_names, RAT_SESSION_TIMEOUT, RMC_COA_ACK, RMC_COA_NAK, RMC_COA_REQUEST, send_response(), TRUE, type, and untoh32().
Referenced by receive().
 {
     enumerator_t *enumerator;
     linked_list_t *ids;
     ike_sa_id_t *id;
     chunk_t data;
     int type;
     u_int32_t lifetime = 0;
     bool lifetime_seen = FALSE;
     ids = get_matching_ike_sas(this, request, client);
     if (ids->get_count(ids))
     {
         enumerator = request->create_enumerator(request);
         while (enumerator->enumerate(enumerator, &type, &data))
         {
             if (type == RAT_SESSION_TIMEOUT && data.len == 4)
             {
                 lifetime = untoh32(data.ptr);
                 lifetime_seen = TRUE;
                 break;
             }
         }
         enumerator->destroy(enumerator);
         if (lifetime_seen)
         {
             DBG1(DBG_CFG, "applying %us lifetime to %d IKE_SA%s matching %N, "
                  "sending %N", lifetime, ids->get_count(ids),
                  ids->get_count(ids) > 1 ? "s" : "",
                  radius_message_code_names, RMC_COA_REQUEST,
                  radius_message_code_names, RMC_COA_ACK);
             enumerator = ids->create_enumerator(ids);
             while (enumerator->enumerate(enumerator, &id))
             {
                 apply_lifetime(this, id, lifetime);
             }
             enumerator->destroy(enumerator);
             send_response(this, request, RMC_COA_ACK, client);
         }
         else
         {
             DBG1(DBG_CFG, "no Session-Timeout attribute found in %N, sending %N",
                  radius_message_code_names, RMC_COA_REQUEST,
                  radius_message_code_names, RMC_COA_NAK);
             send_response(this, request, RMC_COA_NAK, client);
         }
     }
     else
     {
         DBG1(DBG_CFG, "no IKE_SA matches %N, sending %N",
              radius_message_code_names, RMC_COA_REQUEST,
              radius_message_code_names, RMC_COA_NAK);
         send_response(this, request, RMC_COA_NAK, client);
     }
     ids->destroy_offset(ids, offsetof(ike_sa_id_t, destroy));
 }
static void process_disconnect (private_eap_radius_dae_t * this, radius_message_t * request, host_t * client) static
Process a DAE disconnect request, send response
Definition at line 256 of file eap_radius_dae.c.
References linked_list_t::create_enumerator, DBG1, DBG_CFG, delete_ike_sa_job_create(), destroy(), linked_list_t::destroy_offset, linked_list_t::get_count, get_matching_ike_sas(), id, lib, library_t::processor, processor_t::queue_job, radius_message_code_names, RMC_DISCONNECT_ACK, RMC_DISCONNECT_NAK, RMC_DISCONNECT_REQUEST, send_response(), and TRUE.
Referenced by receive().
 {
     enumerator_t *enumerator;
     linked_list_t *ids;
     ike_sa_id_t *id;
     ids = get_matching_ike_sas(this, request, client);
     if (ids->get_count(ids))
     {
         DBG1(DBG_CFG, "closing %d IKE_SA%s matching %N, sending %N",
              ids->get_count(ids), ids->get_count(ids) > 1 ? "s" : "",
              radius_message_code_names, RMC_DISCONNECT_REQUEST,
              radius_message_code_names, RMC_DISCONNECT_ACK);
         enumerator = ids->create_enumerator(ids);
         while (enumerator->enumerate(enumerator, &id))
         {
             lib->processor->queue_job(lib->processor, (job_t*)
                                       delete_ike_sa_job_create(id, TRUE));
         }
         enumerator->destroy(enumerator);
         send_response(this, request, RMC_DISCONNECT_ACK, client);
     }
     else
     {
         DBG1(DBG_CFG, "no IKE_SA matches %N, sending %N",
              radius_message_code_names, RMC_DISCONNECT_REQUEST,
              radius_message_code_names, RMC_DISCONNECT_NAK);
         send_response(this, request, RMC_DISCONNECT_NAK, client);
     }
     ids->destroy_offset(ids, offsetof(ike_sa_id_t, destroy));
 }
static bool receive (private_eap_radius_dae_t * this) static
Receive RADIUS DAE requests
Definition at line 382 of file eap_radius_dae.c.
References addr, chunk_create(), client(), DBG1, DBG_CFG, DBG_NET, host_t::destroy, radius_message_t::destroy, EWOULDBLOCK, radius_message_t::get_code, host_create_from_sockaddr(), len, MSG_DONTWAIT, process_coa(), process_disconnect(), radius_message_code_names, radius_message_parse(), recvfrom, request(), RMC_COA_REQUEST, RMC_DISCONNECT_REQUEST, send_retransmit(), strerror, TRUE, and radius_message_t::verify.
Referenced by dhcp_socket_create(), eap_radius_dae_create(), fetch_ocsp(), and METHOD().
 {
     struct sockaddr_storage addr;
     socklen_t addr_len = sizeof(addr);
     radius_message_t *request;
     char buf[2048];
     ssize_t len;
     host_t *client;
     len = recvfrom(this->fd, buf, sizeof(buf), MSG_DONTWAIT,
                    (struct sockaddr*)&addr, &addr_len);
     if (len > 0)
     {
         request = radius_message_parse(chunk_create(buf, len));
         if (request)
         {
             client = host_create_from_sockaddr((struct sockaddr*)&addr);
             if (client)
             {
                 if (!send_retransmit(this, request, client))
                 {
                     if (request->verify(request, NULL, this->secret,
                                         this->hasher, this->signer))
                     {
                         switch (request->get_code(request))
{
                             case RMC_DISCONNECT_REQUEST:
                                 process_disconnect(this, request, client);
                                 break;
                             case RMC_COA_REQUEST:
                                 process_coa(this, request, client);
                                 break;
                             default:
                                 DBG1(DBG_CFG, "ignoring unsupported RADIUS DAE "
                                      "%N message from %H",
                                      radius_message_code_names,
                                      request->get_code(request), client);
                             break;
                         }
                     }
                 }
                 client->destroy(client);
             }
             request->destroy(request);
         }
         else
         {
             DBG1(DBG_NET, "ignoring invalid RADIUS DAE request");
         }
     }
     else if (errno != EWOULDBLOCK)
     {
         DBG1(DBG_NET, "receiving RADIUS DAE request failed: %s", strerror(errno));
     }
     return TRUE;
 }
static void save_retransmit (private_eap_radius_dae_t * this, radius_message_t * response, host_t * client) static
Save/Replace response for retransmission
Definition at line 99 of file eap_radius_dae.c.
References entry_t::client, host_t::clone, enumerator_t::destroy, radius_message_t::destroy, enumerator_t::enumerate, host_t::equals, FALSE, found, INIT, entry_t::response, response, and TRUE.
Referenced by send_response().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool found = FALSE;
     enumerator = this->responses->create_enumerator(this->responses);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (client->equals(client, entry->client))
         {
             entry->response->destroy(entry->response);
             entry->response = response;
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         INIT(entry,
             .response = response,
             .client = client->clone(client),
         );
         this->responses->insert_first(this->responses, entry);
     }
 }
static void send_message (private_eap_radius_dae_t * this, radius_message_t * message, host_t * client) static
Send a RADIUS message to client
Definition at line 132 of file eap_radius_dae.c.
References data, DBG1, DBG_CFG, radius_message_t::get_encoding, host_t::get_sockaddr, host_t::get_sockaddr_len, chunk_t::len, chunk_t::ptr, sendto, and strerror.
Referenced by send_response(), and send_retransmit().
 {
     chunk_t data;
     data = message->get_encoding(message);
     if (sendto(this->fd, data.ptr, data.len, 0, client->get_sockaddr(client),
                *client->get_sockaddr_len(client)) != data.len)
     {
         DBG1(DBG_CFG, "sending RADIUS DAE response failed: %s", strerror(errno));
     }
 }
static void send_response (private_eap_radius_dae_t * this, radius_message_t * request, radius_message_code_t code, host_t * client) static
Send an ACK/NAK response for a request
Definition at line 179 of file eap_radius_dae.c.
References radius_message_t::destroy, FALSE, radius_message_t::get_authenticator, radius_message_t::get_identifier, hasher, radius_message_create(), response, save_retransmit(), send_message(), radius_message_t::set_identifier, radius_message_t::sign, and signer.
Referenced by process_coa(), process_disconnect(), and process_request().
 {
     radius_message_t *response;
     response = radius_message_create(code);
     response->set_identifier(response, request->get_identifier(request));
     if (response->sign(response, request->get_authenticator(request),
                        this->secret, this->hasher, this->signer, NULL, FALSE))
     {
         send_message(this, response, client);
         save_retransmit(this, response, client);
     }
     else
     {
         response->destroy(response);
     }
 }
static bool send_retransmit (private_eap_radius_dae_t * this, radius_message_t * request, host_t * client) static
Check if we request is a retransmit, retransmit stored response
Definition at line 148 of file eap_radius_dae.c.
References client(), entry_t::client, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, host_t::equals, FALSE, found, radius_message_t::get_code, radius_message_t::get_identifier, radius_message_code_names, entry_t::response, send_message(), and TRUE.
Referenced by receive().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool found = FALSE;
     enumerator = this->responses->create_enumerator(this->responses);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (client->equals(client, entry->client) &&
             request->get_identifier(request) ==
                             entry->response->get_identifier(entry->response))
         {
             DBG1(DBG_CFG, "received retransmit of RADIUS %N, retransmitting %N "
                  "to %H", radius_message_code_names, request->get_code(request),
                  radius_message_code_names,
                  entry->response->get_code(entry->response), client);
             send_message(this, entry->response, client);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }