strongSwan: eap_simaka_pseudonym_provider.c File Reference
eap_simaka_pseudonym_provider.c File Reference
#include "eap_simaka_pseudonym_provider.h"
#include <utils/debug.h>
#include <collections/hashtable.h>
Classes
struct private_eap_simaka_pseudonym_provider_t
Typedefs
typedef struct
private_eap_simaka_pseudonym_provider_t private_eap_simaka_pseudonym_provider_t
Functions
static u_int hash (identification_t *key)
static bool equals (identification_t *key1, identification_t *key2)
METHOD (simaka_provider_t, is_pseudonym, identification_t *, private_eap_simaka_pseudonym_provider_t *this, identification_t *id)
static identification_t * gen_identity (private_eap_simaka_pseudonym_provider_t *this)
METHOD (simaka_provider_t, gen_pseudonym, identification_t *, private_eap_simaka_pseudonym_provider_t *this, identification_t *id)
METHOD (eap_simaka_pseudonym_provider_t, destroy, void, private_eap_simaka_pseudonym_provider_t *this)
eap_simaka_pseudonym_provider_t * eap_simaka_pseudonym_provider_create ()
Typedef Documentation
typedef struct private_eap_simaka_pseudonym_provider_t private_eap_simaka_pseudonym_provider_t
Definition at line 21 of file eap_simaka_pseudonym_provider.c.
Function Documentation
static bool equals (identification_t * key1, identification_t * key2) static
hashtable equals function
Definition at line 60 of file eap_simaka_pseudonym_provider.c.
References identification_t::equals.
Referenced by eap_simaka_pseudonym_provider_create().
 {
     return key1->equals(key1, key2);
 }
static identification_t* gen_identity (private_eap_simaka_pseudonym_provider_t * this) static
Generate a random identity
Definition at line 81 of file eap_simaka_pseudonym_provider.c.
References chunk_create(), chunk_to_hex(), FALSE, identification_create_from_string(), and rng.
Referenced by METHOD().
 {
     char buf[8], hex[sizeof(buf) * 2 + 1];
     if (!this->rng->get_bytes(this->rng, sizeof(buf), buf))
     {
         return NULL;
     }
     chunk_to_hex(chunk_create(buf, sizeof(buf)), hex, FALSE);
     return identification_create_from_string(hex);
 }
static u_int hash (identification_t * key) static
hashtable hash function
Definition at line 52 of file eap_simaka_pseudonym_provider.c.
References chunk_hash(), and identification_t::get_encoding.
Referenced by eap_simaka_pseudonym_provider_create().
 {
     return chunk_hash(key->get_encoding(key));
 }
METHOD (simaka_provider_t , is_pseudonym , identification_t * , private_eap_simaka_pseudonym_provider_t * this, identification_t * id)
Definition at line 65 of file eap_simaka_pseudonym_provider.c.
References identification_t::clone.
 {
     identification_t *permanent;
     permanent = this->permanent->get(this->permanent, id);
     if (permanent)
     {
         return permanent->clone(permanent);
     }
     return NULL;
 }
METHOD (simaka_provider_t , gen_pseudonym , identification_t * , private_eap_simaka_pseudonym_provider_t * this, identification_t * id)
Definition at line 95 of file eap_simaka_pseudonym_provider.c.
References identification_t::clone, DBG1, DBG_CFG, identification_t::destroy, and gen_identity().
 {
     identification_t *pseudonym, *permanent;
     /* remove old entry */
     pseudonym = this->pseudonym->remove(this->pseudonym, id);
     if (pseudonym)
     {
         permanent = this->permanent->remove(this->permanent, pseudonym);
         if (permanent)
         {
             permanent->destroy(permanent);
         }
         pseudonym->destroy(pseudonym);
     }
     pseudonym = gen_identity(this);
     if (!pseudonym)
     {
         DBG1(DBG_CFG, "failed to generate pseudonym");
         return NULL;
     }
     /* create new entries */
     id = id->clone(id);
     this->pseudonym->put(this->pseudonym, id, pseudonym);
     this->permanent->put(this->permanent, pseudonym, id);
     return pseudonym->clone(pseudonym);
 }
METHOD (eap_simaka_pseudonym_provider_t , destroy , void , private_eap_simaka_pseudonym_provider_t * this)
Definition at line 127 of file eap_simaka_pseudonym_provider.c.
References enumerator_t::destroy, enumerator_t::enumerate, free(), id, key, and rng.
 {
     enumerator_t *enumerator;
     identification_t *id;
     void *key;
     enumerator = this->pseudonym->create_enumerator(this->pseudonym);
     while (enumerator->enumerate(enumerator, &key, &id))
     {
         id->destroy(id);
     }
     enumerator->destroy(enumerator);
     enumerator = this->permanent->create_enumerator(this->permanent);
     while (enumerator->enumerate(enumerator, &key, &id))
     {
         id->destroy(id);
     }
     enumerator->destroy(enumerator);
     this->pseudonym->destroy(this->pseudonym);
     this->permanent->destroy(this->permanent);
     this->rng->destroy(this->rng);
     free(this);
 }