strongSwan: ike_me
ike_me
tasks
Classes
struct ike_me_t
Typedefs
typedef struct ike_me_t ike_me_t
Functions
ike_me_t * ike_me_create (ike_sa_t *ike_sa, bool initiator)
Detailed Description
Typedef Documentation
typedef struct ike_me_t ike_me_t
Definition at line 24 of file ike_me.h.
Function Documentation
ike_me_t* ike_me_create (ike_sa_t * ike_sa, bool initiator)
Create a new ike_me task.
Parameters
ike_sa IKE_SA this task works for
initiator TRUE if task is initiated by us
Returns
ike_me task to be handled by the task_manager
Definition at line 794 of file ike_me.c.
References COND_ORIGINAL_INITIATOR, ike_sa_t::has_condition, INIT, initiator, and linked_list_create().
Referenced by METHOD(), and process_request().
 {
     private_ike_me_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
             .connect = _me_connect,
             .respond = _me_respond,
             .callback = _me_callback,
             .relay = _relay,
         },
         .ike_sa = ike_sa,
         .initiator = initiator,
         .local_endpoints = linked_list_create(),
         .remote_endpoints = linked_list_create(),
     );
     if (ike_sa->has_condition(ike_sa, COND_ORIGINAL_INITIATOR))
     {
         if (initiator)
         {
             this->public.task.build = _build_i;
             this->public.task.process = _process_i;
         }
         else
         {
             this->public.task.build = _build_r;
             this->public.task.process = _process_r;
         }
     }
     else
     {
         /* mediation server */
         if (initiator)
         {
             this->public.task.build = _build_i_ms;
             this->public.task.process = _process_i_ms;
         }
         else
         {
             this->public.task.build = _build_r_ms;
             this->public.task.process = _process_r_ms;
         }
     }
     return &this->public;
 }