strongSwan: bliss_param_set
bliss_param_set
bliss
Classes
struct bliss_param_set_t
Typedefs
typedef enum bliss_param_set_id_t bliss_param_set_id_t
typedef struct bliss_param_set_t bliss_param_set_t
Enumerations
enum bliss_param_set_id_t {
BLISS_I = 1, BLISS_II = 2, BLISS_III = 3, BLISS_IV = 4,
BLISS_B_I = 5, BLISS_B_II = 6, BLISS_B_III = 7, BLISS_B_IV = 8
}
Functions
bliss_param_set_t * bliss_param_set_get_by_id (bliss_param_set_id_t id)
bliss_param_set_t * bliss_param_set_get_by_oid (int oid)
Variables
enum_name_t * bliss_param_set_id_names
Detailed Description
Typedef Documentation
typedef enum bliss_param_set_id_t bliss_param_set_id_t
Definition at line 24 of file bliss_param_set.h.
typedef struct bliss_param_set_t bliss_param_set_t
Definition at line 25 of file bliss_param_set.h.
Enumeration Type Documentation
enum bliss_param_set_id_t
BLISS signature parameter set ID list
Enumerator
BLISS_I
BLISS_II
BLISS_III
BLISS_IV
BLISS_B_I
BLISS_B_II
BLISS_B_III
BLISS_B_IV
Definition at line 35 of file bliss_param_set.h.
{
     BLISS_I =     1,
     BLISS_II =    2,
     BLISS_III =   3,
     BLISS_IV =    4,
     BLISS_B_I =   5,
     BLISS_B_II =  6,
     BLISS_B_III = 7,
     BLISS_B_IV =  8
 };
Function Documentation
bliss_param_set_t* bliss_param_set_get_by_id (bliss_param_set_id_t id)
Get BLISS signature parameter set by BLISS parameter set ID
Parameters
id BLISS parameter set ID
Returns
BLISS parameter set
See header.
Definition at line 309 of file bliss_param_set.c.
References countof.
Referenced by bliss_private_key_gen(), bliss_private_key_load(), main(), and START_TEST().
 {
     int i;
     for (i = 0; i < countof(bliss_param_sets); i++)
     {
         if (bliss_param_sets[i].id == id)
         {
             return &bliss_param_sets[i];
         }
     }
     return NULL;
 }
bliss_param_set_t* bliss_param_set_get_by_oid (int oid)
Get BLISS signature parameter set by BLISS parameter set OID
Parameters
oid BLISS parameter set OID
Returns
BLISS parameter set
See header.
Definition at line 327 of file bliss_param_set.c.
References countof.
Referenced by bliss_private_key_load(), and bliss_public_key_load().
 {
     int i;
     for (i = 0; i < countof(bliss_param_sets); i++)
     {
         if (bliss_param_sets[i].oid == oid)
         {
             return &bliss_param_sets[i];
         }
     }
     return NULL;
 }
Variable Documentation
enum_name_t* bliss_param_set_id_names
Referenced by bliss_signature_create_from_data(), and METHOD().