strongSwan: imc_os_info.c File Reference
imc_os_info.c File Reference
#include "imc_os_info.h"
#include <stdio.h>
#include <stdarg.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
#include <sys/utsname.h>
Classes
struct private_imc_os_info_t
struct package_enumerator_t
Macros
#define RELEASE_LSB 0
#define RELEASE_DEBIAN 1
Typedefs
typedef struct
private_imc_os_info_t private_imc_os_info_t
Functions
METHOD (imc_os_info_t, get_type, os_type_t, private_imc_os_info_t *this)
METHOD (imc_os_info_t, get_name, chunk_t, private_imc_os_info_t *this)
METHOD (imc_os_info_t, get_numeric_version, void, private_imc_os_info_t *this, u_int32_t *major, u_int32_t *minor)
METHOD (imc_os_info_t, get_version, chunk_t, private_imc_os_info_t *this)
METHOD (imc_os_info_t, get_default_pwd_status, bool, private_imc_os_info_t *this)
METHOD (imc_os_info_t, get_fwd_status, os_fwd_status_t, private_imc_os_info_t *this)
METHOD (imc_os_info_t, get_uptime, time_t, private_imc_os_info_t *this)
METHOD (imc_os_info_t, get_setting, chunk_t, private_imc_os_info_t *this, char *name)
static void package_enumerator_destroy (package_enumerator_t *this)
static bool package_enumerator_enumerate (package_enumerator_t *this,...)
METHOD (imc_os_info_t, create_package_enumerator, enumerator_t *, private_imc_os_info_t *this)
static bool extract_platform_info (os_type_t *type, chunk_t *name, chunk_t *version)
METHOD (imc_os_info_t, destroy, void, private_imc_os_info_t *this)
imc_os_info_t * imc_os_info_create (void)
Macro Definition Documentation
#define RELEASE_DEBIAN 1
Definition at line 375 of file imc_os_info.c.
Referenced by extract_platform_info().
#define RELEASE_LSB 0
Definition at line 374 of file imc_os_info.c.
Referenced by extract_platform_info().
Typedef Documentation
typedef struct private_imc_os_info_t private_imc_os_info_t
Definition at line 29 of file imc_os_info.c.
Function Documentation
static bool extract_platform_info (os_type_t * type, chunk_t * name, chunk_t * version) static
Determine Linux distribution version and hardware platform
Definition at line 380 of file imc_os_info.c.
References BUF_LEN, chunk_alloc, chunk_clone, chunk_create(), chunk_empty, countof, DBG1, DBG_IMC, DBG_PTS, enum_to_name(), FALSE, chunk_t::len, len, memcpy, min, OS_TYPE_DEBIAN, os_type_from_name(), os_type_names, OS_TYPE_UNKNOWN, chunk_t::ptr, RELEASE_DEBIAN, RELEASE_LSB, and TRUE.
Referenced by imc_os_info_create().
 {
     FILE *file;
     u_char buf[BUF_LEN], *pos = buf;
     int len = BUF_LEN - 1;
     os_type_t os_type = OS_TYPE_UNKNOWN;
     chunk_t os_name = chunk_empty;
     chunk_t os_version = chunk_empty;
     char *os_str;
     struct utsname uninfo;
     int i;
     /* Linux/Unix distribution release info (from http://linuxmafia.com) */
     const char* releases[] = {
         "/etc/lsb-release",           "/etc/debian_version",
         "/etc/SuSE-release",          "/etc/novell-release",
         "/etc/sles-release",          "/etc/redhat-release",
         "/etc/fedora-release",        "/etc/gentoo-release",
         "/etc/slackware-version",     "/etc/annvix-release",
         "/etc/arch-release",          "/etc/arklinux-release",
         "/etc/aurox-release",         "/etc/blackcat-release",
         "/etc/cobalt-release",        "/etc/conectiva-release",
         "/etc/debian_release",        "/etc/immunix-release",
         "/etc/lfs-release",           "/etc/linuxppc-release",
         "/etc/mandrake-release",      "/etc/mandriva-release",
         "/etc/mandrakelinux-release", "/etc/mklinux-release",
         "/etc/pld-release",           "/etc/redhat_version",
         "/etc/slackware-release",     "/etc/e-smith-release",
         "/etc/release",               "/etc/sun-release",
         "/etc/tinysofa-release",      "/etc/turbolinux-release",
         "/etc/ultrapenguin-release",  "/etc/UnitedLinux-release",
         "/etc/va-release",            "/etc/yellowdog-release"
     };
     const char lsb_distrib_id[]      = "DISTRIB_ID=";
     const char lsb_distrib_release[] = "DISTRIB_RELEASE=";
     for (i = 0; i < countof(releases); i++)
     {
         file = fopen(releases[i], "r");
         if (!file)
         {
             continue;
         }
         /* read release file into buffer */
         fseek(file, 0, SEEK_END);
         len = min(ftell(file), len);
         rewind(file);
         buf[len] = '\0';
         if (fread(buf, 1, len, file) != len)
         {
             DBG1(DBG_IMC, "failed to read file \"%s\"", releases[i]);
             fclose(file);
             return FALSE;
         }
         fclose(file);
         DBG1(DBG_IMC, "processing \"%s\" file", releases[i]);
         switch (i)
         {
             case RELEASE_LSB:
             {
                 /* Determine Distribution ID */
                 pos = strstr(buf, lsb_distrib_id);
                 if (!pos)
                 {
                     DBG1(DBG_IMC, "failed to find begin of DISTRIB_ID field");
                     return FALSE;
                 }
                 pos += strlen(lsb_distrib_id);
                 os_name.ptr = pos;
                 pos = strchr(pos, '\n');
                 if (!pos)
                 {
                     DBG1(DBG_IMC, "failed to find end of DISTRIB_ID field");
                     return FALSE;
                 }
                 os_name.len = pos - os_name.ptr;
                 /* Determine Distribution Release */
                 pos = strstr(buf, lsb_distrib_release);
                 if (!pos)
                 {
                     DBG1(DBG_IMC, "failed to find begin of DISTRIB_RELEASE field");
                     return FALSE;
                 }
                 pos += strlen(lsb_distrib_release);
                 os_version.ptr = pos;
                 pos = strchr(pos, '\n');
                 if (!pos)
                 {
                     DBG1(DBG_IMC, "failed to find end of DISTRIB_RELEASE field");
                     return FALSE;
                 }
                 os_version.len = pos - os_version.ptr;
                 break;
             }
             case RELEASE_DEBIAN:
             {
                 os_type = OS_TYPE_DEBIAN;
                 os_version.ptr = buf;
                 pos = strchr(buf, '\n');
                 if (!pos)
                 {
                     DBG1(DBG_PTS, "failed to find end of release string");
                     return FALSE;
                 }
                 os_version.len = pos - os_version.ptr;
                 break;
             }
             default:
             {
                 const char str_release[] = " release ";
                 os_name.ptr = buf;
                 pos = strstr(buf, str_release);
                 if (!pos)
                 {
                     DBG1(DBG_IMC, "failed to find release keyword");
                     return FALSE;
                 }
                 os_name.len = pos - os_name.ptr;
                 pos += strlen(str_release);
                 os_version.ptr = pos;
                 pos = strchr(pos, '\n');
                 if (!pos)
                 {
                     DBG1(DBG_IMC, "failed to find end of release string");
                     return FALSE;
                 }
                 os_version.len = pos - os_version.ptr;
                 break;
             }
         }
         break;
     }
     if (!os_version.ptr)
     {
         DBG1(DBG_IMC, "no distribution release file found");
         return FALSE;
     }
     if (uname(&uninfo) < 0)
     {
         DBG1(DBG_IMC, "could not retrieve machine architecture");
         return FALSE;
     }
     /* Try to find a matching OS type based on the OS name */
     if (os_type == OS_TYPE_UNKNOWN)
     {
         os_type = os_type_from_name(os_name);
     }
     /* If known use the official OS name */
     if (os_type != OS_TYPE_UNKNOWN)
     {
         os_str = enum_to_name(os_type_names, os_type);
         os_name = chunk_create(os_str, strlen(os_str));
     }
     /* copy OS type */
     *type = os_type;
     /* copy OS name */
     *name = chunk_clone(os_name);
     /* copy OS version and machine architecture */
     *version = chunk_alloc(os_version.len + 1 + strlen(uninfo.machine));
     pos = version->ptr;
     memcpy(pos, os_version.ptr, os_version.len);
     pos += os_version.len;
     *pos++ = ' ';
     memcpy(pos, uninfo.machine, strlen(uninfo.machine));
     return TRUE;
 }
METHOD (imc_os_info_t , get_type , os_type_t , private_imc_os_info_t * this)
Definition at line 59 of file imc_os_info.c.
References type.
 {
     return this->type;
 }
METHOD (imc_os_info_t , get_name , chunk_t , private_imc_os_info_t * this)
Definition at line 65 of file imc_os_info.c.
References name.
 {
     return this->name;
 }
METHOD (imc_os_info_t , get_numeric_version , void , private_imc_os_info_t * this, u_int32_t * major, u_int32_t * minor)
Definition at line 71 of file imc_os_info.c.
References chunk_t::ptr, and version.
 {
     u_char *pos;
     if (major)
     {
         *major = atol(this->version.ptr);
     }
     pos = memchr(this->version.ptr, '.', this->version.len);
     if (minor)
     {
         *minor = pos ? atol(pos + 1) : 0;
     }
 }
METHOD (imc_os_info_t , get_version , chunk_t , private_imc_os_info_t * this)
Definition at line 87 of file imc_os_info.c.
References version.
 {
     return this->version;
 }
METHOD (imc_os_info_t , get_default_pwd_status , bool , private_imc_os_info_t * this)
Definition at line 93 of file imc_os_info.c.
References FALSE, settings_t::get_bool, lib, library_t::ns, and library_t::settings.
 {
     /* As an option the default password status can be configured manually */
     return lib->settings->get_bool(lib->settings,
                     "%s.imcv.os_info.default_password_enabled", FALSE, lib->ns);
 }
METHOD (imc_os_info_t , get_fwd_status , os_fwd_status_t , private_imc_os_info_t * this)
Definition at line 166 of file imc_os_info.c.
References DBG1, DBG_IMC, OS_FWD_DISABLED, OS_FWD_ENABLED, and OS_FWD_UNKNOWN.
 {
     const char ip_forward[] = "/proc/sys/net/ipv4/ip_forward";
     char buf[2];
     FILE *file;
     os_fwd_status_t fwd_status = OS_FWD_UNKNOWN;
     file = fopen(ip_forward, "r");
     if (file)
     {
         if (fread(buf, 1, 1, file) == 1)
         {
             switch (buf[0])
             {
                 case '0':
                     fwd_status = OS_FWD_DISABLED;
                     break;
                 case '1':
                     fwd_status = OS_FWD_ENABLED;
                     break;
                 default:
                     DBG1(DBG_IMC, "\"%s\" returns invalid value ", ip_forward);
                     break;
             }
         }
         else
         {
             DBG1(DBG_IMC, "could not read from \"%s\"", ip_forward);
         }
         fclose(file);
     }
     else
     {
         DBG1(DBG_IMC, "failed to open \"%s\"", ip_forward);
     }
     return fwd_status;
 }
METHOD (imc_os_info_t , get_uptime , time_t , private_imc_os_info_t * this)
Definition at line 207 of file imc_os_info.c.
References DBG1, and DBG_IMC.
 {
     const char proc_uptime[] = "/proc/uptime";
     FILE *file;
     u_int uptime;
     file = fopen(proc_uptime, "r");
     if (!file)
     {
         DBG1(DBG_IMC, "failed to open \"%s\"", proc_uptime);
         return 0;
     }
     if (fscanf(file, "%u", &uptime) != 1)
     {
         DBG1(DBG_IMC, "failed to read file \"%s\"", proc_uptime);
         uptime = 0;
     }
     fclose(file);
     return uptime;
 }
METHOD (imc_os_info_t , get_setting , chunk_t , private_imc_os_info_t * this, char * name)
In order to guarantee privacy, only settings from the /etc/, /proc/ and /sys/ directories can be retrieved
Definition at line 230 of file imc_os_info.c.
References chunk_clone, chunk_create(), chunk_empty, DBG1, DBG_IMC, strpfx(), and value.
 {
     FILE *file;
     u_char buf[2048];
     size_t i = 0;
     chunk_t value;
     if (!strpfx(name, "/etc/") && !strpfx(name, "/proc/") &&
         !strpfx(name, "/sys/") && !strpfx(name, "/var/"))
     {
         DBG1(DBG_IMC, "not allowed to access '%s'", name);
         return chunk_empty;
     }
     file = fopen(name, "r");
     if (!file)
     {
         DBG1(DBG_IMC, "failed to open '%s'", name);
         return chunk_empty;
     }
     while (i < sizeof(buf) && fread(buf + i, 1, 1, file) == 1)
     {
         i++;
     }
     fclose(file);
     value = chunk_create(buf, i);
     return chunk_clone(value);
 }
METHOD (imc_os_info_t , create_package_enumerator , enumerator_t * , private_imc_os_info_t * this)
Definition at line 343 of file imc_os_info.c.
References command, DBG1, DBG_IMC, enumerator_t::destroy, enumerator_t::enumerate, package_enumerator_t::file, malloc_thing, OS_TYPE_DEBIAN, OS_TYPE_UBUNTU, package_enumerator_destroy(), package_enumerator_enumerate(), and package_enumerator_t::public.
 {
     FILE *file;
     const char command[] = "dpkg-query --show --showformat="
                                 "'${Status}\t${Package}\t${Version}\n'";
     package_enumerator_t *enumerator;
     /* Only Debian and Ubuntu package enumeration is currently supported */
     if (this->type != OS_TYPE_DEBIAN && this->type != OS_TYPE_UBUNTU)
     {
         return NULL;
     }
     /* Open a pipe stream for reading the output of the dpkg-query commmand */
     file = popen(command, "r");
     if (!file)
     {
         DBG1(DBG_IMC, "failed to run dpkg command");
         return NULL;
     }
     /* Create a package enumerator instance */
     enumerator = malloc_thing(package_enumerator_t);
     enumerator->public.enumerate = (void*)package_enumerator_enumerate;
     enumerator->public.destroy = (void*)package_enumerator_destroy;
     enumerator->file = file;
     return (enumerator_t*)enumerator;
 }
METHOD (imc_os_info_t , destroy , void , private_imc_os_info_t * this)
Definition at line 578 of file imc_os_info.c.
References free(), and chunk_t::ptr.
 {
     free(this->name.ptr);
     free(this->version.ptr);
     free(this);
 }
static void package_enumerator_destroy (package_enumerator_t * this) static
Implementation of package_enumerator.destroy.
Definition at line 289 of file imc_os_info.c.
References free().
Referenced by METHOD().
 {
     pclose(this->file);
     free(this);
 }
static bool package_enumerator_enumerate (package_enumerator_t * this, ...) static
Implementation of package_enumerator.enumerate
Definition at line 298 of file imc_os_info.c.
References FALSE, chunk_t::len, name, chunk_t::ptr, streq(), TRUE, and version.
Referenced by METHOD().
 {
     chunk_t *name, *version;
     u_char *pos;
     va_list args;
     while (TRUE)
     {
         if (!fgets(this->line, sizeof(this->line), this->file))
         {
             return FALSE;
         }
         pos = strchr(this->line, '\t');
         if (!pos)
         {
             return FALSE;
         }
         *pos++ = '\0';
         if (!streq(this->line, "install ok installed"))
         {
             continue;
         }
         va_start(args, this);
         name = va_arg(args, chunk_t*);
         name->ptr = pos;
         pos = strchr(pos, '\t');
         if (!pos)
         {
             va_end(args);
             return FALSE;
         }
         name->len = pos++ - name->ptr;
         version = va_arg(args, chunk_t*);
         version->ptr = pos;
         version->len = strlen(pos) - 1;
         va_end(args);
         return TRUE;
     }
 }