strongSwan: tnccs_recommendation_msg
tnccs_recommendation_msg
tnccs_11
Classes
struct tnccs_recommendation_msg_t
Typedefs
typedef struct
tnccs_recommendation_msg_t tnccs_recommendation_msg_t
Functions
tnccs_msg_t * tnccs_recommendation_msg_create_from_node (xmlNodePtr node, linked_list_t *errors)
tnccs_msg_t * tnccs_recommendation_msg_create (TNC_IMV_Action_Recommendation rec)
Detailed Description
Typedef Documentation
typedef struct tnccs_recommendation_msg_t tnccs_recommendation_msg_t
Definition at line 24 of file tnccs_recommendation_msg.h.
Function Documentation
tnccs_msg_t* tnccs_recommendation_msg_create (TNC_IMV_Action_Recommendation rec)
Create a TNCCS-Recommendation message from parameters
Parameters
rec Action Recommendation
See header
Definition at line 138 of file tnccs_recommendation_msg.c.
References enum_to_name(), INIT, n, TNC_IMV_ACTION_RECOMMENDATION_ALLOW, TNC_IMV_ACTION_RECOMMENDATION_ISOLATE, TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, TNCCS_MSG_RECOMMENDATION, tnccs_msg_type_names, and type.
Referenced by check_and_build_recommendation().
 {
     private_tnccs_recommendation_msg_t *this;
     xmlNodePtr n, n2;
     char *rec_string;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .destroy = _destroy,
             },
             .get_recommendation = _get_recommendation,
         },
         .type = TNCCS_MSG_RECOMMENDATION,
         .node =  xmlNewNode(NULL, "TNCC-TNCS-Message"),
         .rec = rec,
     );
     /* add the message type number in hex */
     n = xmlNewNode(NULL, "Type");
     xmlNodeSetContent(n, "00000001");
     xmlAddChild(this->node, n);
     n = xmlNewNode(NULL, "XML");
     xmlAddChild(this->node, n);
     switch (rec)
     {
         case TNC_IMV_ACTION_RECOMMENDATION_ALLOW:
             rec_string = "allow";
             break;
         case TNC_IMV_ACTION_RECOMMENDATION_ISOLATE:
             rec_string = "isolate";
             break;
         case TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS:
         case TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION:
         default:
             rec_string = "none";
     }
     n2 = xmlNewNode(NULL, enum_to_name(tnccs_msg_type_names, this->type));
     xmlNewProp(n2, BAD_CAST "type", rec_string);
     xmlNodeSetContent(n2, "");
     xmlAddChild(n, n2);
     return &this->public.tnccs_msg_interface;
 }
tnccs_msg_t* tnccs_recommendation_msg_create_from_node (xmlNodePtr node, linked_list_t * errors)
Create a TNCCS-Recommendation message from XML-encoded message node
Parameters
node XML-encoded message node
errors linked list of TNCCS error messages
See header
Definition at line 76 of file tnccs_recommendation_msg.c.
References BUF_LEN, destroy(), INIT, linked_list_t::insert_last, msg, snprintf, streq(), TNC_IMV_ACTION_RECOMMENDATION_ALLOW, TNC_IMV_ACTION_RECOMMENDATION_ISOLATE, TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS, TNCCS_ERROR_MALFORMED_BATCH, tnccs_error_msg_create(), and TNCCS_MSG_RECOMMENDATION.
Referenced by tnccs_msg_create_from_node().
 {
     private_tnccs_recommendation_msg_t *this;
     xmlChar *rec_string;
     char *error_msg, buf[BUF_LEN];
     tnccs_error_type_t error_type = TNCCS_ERROR_MALFORMED_BATCH;
     tnccs_msg_t *msg;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .destroy = _destroy,
             },
             .get_recommendation = _get_recommendation,
         },
         .type = TNCCS_MSG_RECOMMENDATION,
         .node = node,
     );
     rec_string = xmlGetProp(node, "type");
     if (!rec_string)
     {
         error_msg = "type property in TNCCS-Recommendation is missing";
         goto fatal;
     }
     else if (streq(rec_string, "allow"))
     {
         this->rec = TNC_IMV_ACTION_RECOMMENDATION_ALLOW;
     }
     else if (streq(rec_string, "isolate"))
     {
         this->rec = TNC_IMV_ACTION_RECOMMENDATION_ISOLATE;
     }
     else if (streq(rec_string, "none"))
     {
         this->rec = TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS;
     }
     else
     {
         error_msg = buf;
         snprintf(buf, BUF_LEN, "unsupported type property value '%s' "
                                "in TNCCS-Recommendation", rec_string);
         xmlFree(rec_string);
         goto fatal;
     }
     xmlFree(rec_string);
     return &this->public.tnccs_msg_interface;
 fatal:
     msg = tnccs_error_msg_create(error_type, error_msg);
     errors->insert_last(errors, msg);
     destroy(this);
     return NULL;
 }