strongSwan: keyid2sql.c File Reference
keyid2sql.c File Reference
#include <stdio.h>
#include <library.h>
#include <utils/debug.h>
#include <credentials/keys/private_key.h>
#include <credentials/keys/public_key.h>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
print the keyids of a private or public key in sql format
Definition at line 25 of file keyid2sql.c.
References BUILD_BLOB_PEM, BUILD_END, chunk_clone, chunk_create(), credential_factory_t::create, CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, library_t::creds, fprintf, ID_KEY_ID, KEY_ANY, KEY_RSA, KEYID_PUBKEY_SHA1, chunk_t::len, lib, library_deinit(), library_init(), plugin_loader_t::load, n, PLUGINS, library_t::plugins, printf, private, chunk_t::ptr, public, and read.
 {
     public_key_t *public;
     private_key_t *private;
     chunk_t chunk;
     char buf[8096];
     int read, n;
     library_init(NULL, "keyid2sql");
     lib->plugins->load(lib->plugins, PLUGINS);
     atexit(library_deinit);
     read = fread(buf, 1, sizeof(buf), stdin);
     if (read <= 0)
     {
         fprintf(stderr, "reading key failed.\n");
         return -1;
     }
     chunk = chunk_create(buf, read);
     private = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                  BUILD_BLOB_PEM, chunk_clone(chunk),
                                  BUILD_END);
     if (private)
     {
         if (private->get_fingerprint(private, KEYID_PUBKEY_SHA1, &chunk))
         {
             printf("%d, X'", ID_KEY_ID);
             for (n = 0; n < chunk.len; n++)
             {
                 printf("%.2x", chunk.ptr[n]);
             }
             printf("'\n");
         }
         private->destroy(private);
         return 0;
     }
     public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_ANY,
                                 BUILD_BLOB_PEM, chunk_clone(chunk),
                                 BUILD_END);
     if (!public)
     {
         public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                                     BUILD_BLOB_PEM, chunk_clone(chunk),
                                     BUILD_END);
     }
     if (public)
     {
         if (public->get_fingerprint(public, KEYID_PUBKEY_SHA1, &chunk))
         {
             printf("%d, X'", ID_KEY_ID);
             for (n = 0; n < chunk.len; n++)
             {
                 printf("%.2x", chunk.ptr[n]);
             }
             printf("'\n");
         }
         public->destroy(public);
         return 0;
     }
     fprintf(stderr, "unable to parse input key.\n");
     return -1;
 }