strongSwan: xml
xml
manager
Classes
struct xml_t
Typedefs
typedef struct xml_t xml_t
Functions
xml_t * xml_create (char *xml)
Detailed Description
Typedef Documentation
typedef struct xml_t xml_t
Definition at line 26 of file xml.h.
Function Documentation
xml_t* xml_create (char * xml)
Create a xml instance.
Definition at line 143 of file xml.c.
References free(), INIT, and format-options::root.
Referenced by METHOD(), and read_result().
 {
     private_xml_t *this;
     INIT(this,
         .public = {
             .get_attribute = _get_attribute,
             .children = _children,
         },
         .doc = xmlReadMemory(xml, strlen(xml), NULL, NULL, 0),
     );
     if (!this->doc)
     {
         free(this);
         return NULL;
     }
     this->node = xmlDocGetRootElement(this->doc);
     this->root = this;
     return &this->public;
 }