strongSwan: controller.c File Reference
controller.c File Reference
#include "controller.h"
#include <sys/types.h>
#include <dirent.h>
#include <sys/stat.h>
#include <daemon.h>
#include <library.h>
#include <threading/thread.h>
#include <threading/spinlock.h>
#include <threading/semaphore.h>
Classes
struct private_controller_t
struct interface_logger_t
struct interface_listener_t
struct interface_job_t
Typedefs
typedef struct private_controller_t private_controller_t
typedef struct interface_listener_t interface_listener_t
typedef struct interface_logger_t interface_logger_t
typedef struct interface_job_t interface_job_t
Functions
static bool listener_done (interface_listener_t *listener)
static void listener_unregister (interface_listener_t *listener)
static bool wait_for_listener (interface_job_t *job, u_int timeout)
METHOD (logger_t, listener_log, void, interface_logger_t *this, debug_t group, level_t level, int thread, ike_sa_t *ike_sa, const char *message)
METHOD (logger_t, listener_get_level, level_t, interface_logger_t *this, debug_t group)
METHOD (job_t, get_priority_medium, job_priority_t, job_t *this)
METHOD (listener_t, ike_state_change, bool, interface_listener_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
METHOD (listener_t, child_state_change, bool, interface_listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, child_sa_state_t state)
METHOD (job_t, destroy_job, void, interface_job_t *this)
METHOD (controller_t, create_ike_sa_enumerator, enumerator_t *, private_controller_t *this, bool wait)
METHOD (job_t, initiate_execute, job_requeue_t, interface_job_t *job)
METHOD (controller_t, initiate, status_t, private_controller_t *this, peer_cfg_t *peer_cfg, child_cfg_t *child_cfg, controller_cb_t callback, void *param, u_int timeout, bool limits)
METHOD (job_t, terminate_ike_execute, job_requeue_t, interface_job_t *job)
METHOD (controller_t, terminate_ike, status_t, controller_t *this, u_int32_t unique_id, controller_cb_t callback, void *param, u_int timeout)
METHOD (job_t, terminate_child_execute, job_requeue_t, interface_job_t *job)
METHOD (controller_t, terminate_child, status_t, controller_t *this, u_int32_t unique_id, controller_cb_t callback, void *param, u_int timeout)
bool controller_cb_empty (void *param, debug_t group, level_t level, ike_sa_t *ike_sa, const char *message)
METHOD (controller_t, destroy, void, private_controller_t *this)
controller_t * controller_create (void)
Typedef Documentation
typedef struct interface_job_t interface_job_t
Definition at line 127 of file controller.c.
typedef struct interface_listener_t interface_listener_t
Definition at line 31 of file controller.c.
typedef struct interface_logger_t interface_logger_t
Definition at line 32 of file controller.c.
typedef struct private_controller_t private_controller_t
Definition at line 30 of file controller.c.
Function Documentation
static bool listener_done (interface_listener_t * listener) inline static
This function wakes a thread that is waiting in wait_for_listener(), either from a listener or from a job.
Definition at line 156 of file controller.c.
References interface_listener_t::done, FALSE, and semaphore_t::post.
Referenced by METHOD().
 {
     if (listener->done)
     {
         listener->done->post(listener->done);
     }
     return FALSE;
 }
static void listener_unregister (interface_listener_t * listener) static
thread_cleanup_t handler to unregister a listener.
Definition at line 168 of file controller.c.
References daemon_t::bus, charon, interface_listener_t::logger, interface_logger_t::public, interface_listener_t::public, bus_t::remove_listener, and bus_t::remove_logger.
Referenced by wait_for_listener().
 {
     charon->bus->remove_listener(charon->bus, &listener->public);
     charon->bus->remove_logger(charon->bus, &listener->logger.public);
 }
METHOD (logger_t , listener_log , void , interface_logger_t * this, debug_t group, level_t level, int thread, ike_sa_t * ike_sa, const char * message)
Definition at line 214 of file controller.c.
References callback, listener, listener_done(), and NEED_MORE.
 {
     ike_sa_t *target;
     this->listener->lock->lock(this->listener->lock);
     target = this->listener->ike_sa;
     this->listener->lock->unlock(this->listener->lock);
     if (target == ike_sa)
     {
         if (!this->callback(this->param, group, level, ike_sa, message))
         {
             this->listener->status = NEED_MORE;
             listener_done(this->listener);
         }
     }
 }
METHOD (logger_t , listener_get_level , level_t , interface_logger_t * this, debug_t group)
Definition at line 234 of file controller.c.
References callback, controller_cb_empty(), LEVEL_PRIVATE, and LEVEL_SILENT.
 {
     /* in order to allow callback listeners to decide what they want to log
      * we request any log message, but only if we actually want logging */
     return this->callback == controller_cb_empty ? LEVEL_SILENT : LEVEL_PRIVATE;
 }
METHOD (job_t , get_priority_medium , job_priority_t , job_t * this)
Definition at line 242 of file controller.c.
References JOB_PRIO_MEDIUM.
 {
     return JOB_PRIO_MEDIUM;
 }
METHOD (listener_t , ike_state_change , bool , interface_listener_t * this, ike_sa_t * ike_sa, ike_sa_state_t state)
Definition at line 248 of file controller.c.
References ike_sa_t::get_peer_cfg, ike_sa_t::get_state, IKE_DELETING, IKE_DESTROYING, IKE_ESTABLISHED, listener_done(), spinlock_t::lock, lock, status, SUCCESS, TRUE, and spinlock_t::unlock.
 {
     ike_sa_t *target;
     this->lock->lock(this->lock);
     target = this->ike_sa;
     this->lock->unlock(this->lock);
     if (target == ike_sa)
     {
         switch (state)
         {
 #ifdef ME
             case IKE_ESTABLISHED:
             {   /* mediation connections are complete without CHILD_SA */
                 peer_cfg_t *peer_cfg = ike_sa->get_peer_cfg(ike_sa);
                 if (peer_cfg->is_mediation(peer_cfg))
                 {
                     this->status = SUCCESS;
                     return listener_done(this);
                 }
                 break;
             }
 #endif /* ME */
             case IKE_DESTROYING:
                 if (ike_sa->get_state(ike_sa) == IKE_DELETING)
                 {   /* proper termination */
                     this->status = SUCCESS;
                 }
                 return listener_done(this);
             default:
                 break;
         }
     }
     return TRUE;
 }
METHOD (listener_t , child_state_change , bool , interface_listener_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, child_sa_state_t state)
Definition at line 287 of file controller.c.
References CHILD_CREATED, CHILD_DELETING, CHILD_DESTROYING, CHILD_INSTALLED, CHILD_RETRYING, FAILED, child_sa_t::get_state, listener_done(), spinlock_t::lock, lock, NEED_MORE, status, SUCCESS, TRUE, and spinlock_t::unlock.
 {
     ike_sa_t *target;
     this->lock->lock(this->lock);
     target = this->ike_sa;
     this->lock->unlock(this->lock);
     if (target == ike_sa)
     {
         switch (state)
         {
             case CHILD_INSTALLED:
                 this->status = SUCCESS;
                 return listener_done(this);
             case CHILD_DESTROYING:
                 switch (child_sa->get_state(child_sa))
                 {
                     case CHILD_DELETING:
                         /* proper delete */
                         this->status = SUCCESS;
                         break;
                     case CHILD_RETRYING:
                         /* retrying with a different DH group; survive another
                          * initiation round */
                         this->status = NEED_MORE;
                         return TRUE;
                     case CHILD_CREATED:
                         if (this->status == NEED_MORE)
{
                             this->status = FAILED;
                             return TRUE;
                         }
                         break;
                     default:
                         break;
                 }
                 return listener_done(this);
             default:
                 break;
         }
     }
     return TRUE;
 }
METHOD (job_t , destroy_job , void , interface_job_t * this)
Definition at line 334 of file controller.c.
References tkm_listener_t::destroy, DESTROY_IF, free(), listener, and ref_put().
 {
     if (ref_put(&this->refcount))
     {
         this->listener.lock->destroy(this->listener.lock);
         DESTROY_IF(this->listener.done);
         free(this);
     }
 }
METHOD (controller_t , create_ike_sa_enumerator , enumerator_t * , private_controller_t * this, bool wait)
Definition at line 345 of file controller.c.
References charon, ike_sa_manager_t::create_enumerator, and daemon_t::ike_sa_manager.
 {
     return charon->ike_sa_manager->create_enumerator(charon->ike_sa_manager,
                                                      wait);
 }
METHOD (job_t , initiate_execute , job_requeue_t , interface_job_t * job)
Definition at line 352 of file controller.c.
References interface_logger_t::callback, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout_by_config, interface_listener_t::child_cfg, DBG1, DBG_IKE, child_cfg_t::destroy, peer_cfg_t::destroy, FAILED, FALSE, ike_sa_manager_t::get_half_open_count, settings_t::get_int, processor_t::get_job_load, ike_sa_t::get_peer_cfg, ike_sa_t::get_state, IKE_CREATED, interface_listener_t::ike_sa, daemon_t::ike_sa_manager, ike_sa_t::initiate, INVALID_STATE, JOB_PRIO_MAX, JOB_REQUEUE_NONE, lib, interface_listener_t::limits, listener, interface_job_t::listener, listener_done(), spinlock_t::lock, interface_listener_t::lock, interface_listener_t::logger, library_t::ns, interface_listener_t::peer_cfg, library_t::processor, ike_sa_t::set_peer_cfg, library_t::settings, interface_listener_t::status, SUCCESS, and spinlock_t::unlock.
 {
     ike_sa_t *ike_sa;
     interface_listener_t *listener = &job->listener;
     peer_cfg_t *peer_cfg = listener->peer_cfg;
     ike_sa = charon->ike_sa_manager->checkout_by_config(charon->ike_sa_manager,
                                                         peer_cfg);
     if (!ike_sa)
     {
         listener->child_cfg->destroy(listener->child_cfg);
         peer_cfg->destroy(peer_cfg);
         listener->status = FAILED;
         listener_done(listener);
         return JOB_REQUEUE_NONE;
     }
     listener->lock->lock(listener->lock);
     listener->ike_sa = ike_sa;
     listener->lock->unlock(listener->lock);
     if (ike_sa->get_peer_cfg(ike_sa) == NULL)
     {
         ike_sa->set_peer_cfg(ike_sa, peer_cfg);
     }
     peer_cfg->destroy(peer_cfg);
     if (listener->limits && ike_sa->get_state(ike_sa) == IKE_CREATED)
     {   /* only check if we are not reusing an IKE_SA */
         u_int half_open, limit_half_open, limit_job_load;
         half_open = charon->ike_sa_manager->get_half_open_count(
                                         charon->ike_sa_manager, NULL, FALSE);
         limit_half_open = lib->settings->get_int(lib->settings,
                                         "%s.init_limit_half_open", 0, lib->ns);
         limit_job_load = lib->settings->get_int(lib->settings,
                                         "%s.init_limit_job_load", 0, lib->ns);
         if (limit_half_open && half_open >= limit_half_open)
         {
             DBG1(DBG_IKE, "abort IKE_SA initiation, half open IKE_SA count of "
                  "%d exceeds limit of %d", half_open, limit_half_open);
             charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                         ike_sa);
             listener->child_cfg->destroy(listener->child_cfg);
             listener->status = INVALID_STATE;
             listener_done(listener);
             return JOB_REQUEUE_NONE;
         }
         if (limit_job_load)
         {
             u_int jobs = 0, i;
             for (i = 0; i < JOB_PRIO_MAX; i++)
             {
                 jobs += lib->processor->get_job_load(lib->processor, i);
             }
             if (jobs > limit_job_load)
             {
                 DBG1(DBG_IKE, "abort IKE_SA initiation, job load of %d exceeds "
                      "limit of %d", jobs, limit_job_load);
                 charon->ike_sa_manager->checkin_and_destroy(
                                                 charon->ike_sa_manager, ike_sa);
                 listener->child_cfg->destroy(listener->child_cfg);
                 listener->status = INVALID_STATE;
                 listener_done(listener);
                 return JOB_REQUEUE_NONE;
             }
         }
     }
     if (ike_sa->initiate(ike_sa, listener->child_cfg, 0, NULL, NULL) == SUCCESS)
     {
         if (!listener->logger.callback)
         {
             listener->status = SUCCESS;
         }
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
     }
     else
     {
         listener->status = FAILED;
         charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                     ike_sa);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (controller_t , initiate , status_t , private_controller_t * this, peer_cfg_t * peer_cfg, child_cfg_t * child_cfg, controller_cb_t callback, void * param, u_int timeout, bool limits)
Definition at line 439 of file controller.c.
References callback, FAILED, INIT, limits, listener, interface_logger_t::listener, interface_job_t::listener, interface_listener_t::logger, OUT_OF_RES, spinlock_create(), status, interface_listener_t::status, thread_cleanup_pop(), thread_cleanup_push(), TRUE, and wait_for_listener().
 {
     interface_job_t *job;
     status_t status;
     INIT(job,
         .listener = {
             .public = {
                 .ike_state_change = _ike_state_change,
                 .child_state_change = _child_state_change,
             },
             .logger = {
                 .public = {
                     .log = _listener_log,
                     .get_level = _listener_get_level,
                 },
                 .callback = callback,
                 .param = param,
             },
             .status = FAILED,
             .child_cfg = child_cfg,
             .peer_cfg = peer_cfg,
             .lock = spinlock_create(),
             .limits = limits,
         },
         .public = {
             .execute = _initiate_execute,
             .get_priority = _get_priority_medium,
             .destroy = _destroy_job,
         },
         .refcount = 1,
     );
     job->listener.logger.listener = &job->listener;
     thread_cleanup_push((void*)destroy_job, job);
     if (callback == NULL)
     {
         initiate_execute(job);
     }
     else
     {
         if (wait_for_listener(job, timeout))
         {
             job->listener.status = OUT_OF_RES;
         }
     }
     status = job->listener.status;
     thread_cleanup_pop(TRUE);
     return status;
 }
METHOD (job_t , terminate_ike_execute , job_requeue_t , interface_job_t * job)
Definition at line 492 of file controller.c.
References interface_logger_t::callback, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout_by_id, DBG1, DBG_IKE, ike_sa_t::delete, DESTROY_ME, FAILED, interface_listener_t::id, interface_listener_t::ike_sa, daemon_t::ike_sa_manager, JOB_REQUEUE_NONE, listener, interface_job_t::listener, listener_done(), spinlock_t::lock, interface_listener_t::lock, interface_listener_t::logger, NOT_FOUND, interface_listener_t::status, SUCCESS, unique_id, and spinlock_t::unlock.
 {
     interface_listener_t *listener = &job->listener;
     u_int32_t unique_id = listener->id;
     ike_sa_t *ike_sa;
     ike_sa = charon->ike_sa_manager->checkout_by_id(charon->ike_sa_manager,
                                                     unique_id);
     if (!ike_sa)
     {
         DBG1(DBG_IKE, "unable to terminate IKE_SA: ID %d not found", unique_id);
         listener->status = NOT_FOUND;
         /* release listener */
         listener_done(listener);
         return JOB_REQUEUE_NONE;
     }
     listener->lock->lock(listener->lock);
     listener->ike_sa = ike_sa;
     listener->lock->unlock(listener->lock);
     if (ike_sa->delete(ike_sa) != DESTROY_ME)
     {   /* delete failed */
         listener->status = FAILED;
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
     }
     else
     {
         if (!listener->logger.callback)
         {
             listener->status = SUCCESS;
         }
         charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                     ike_sa);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (controller_t , terminate_ike , status_t , controller_t * this, u_int32_t unique_id, controller_cb_t callback, void * param, u_int timeout)
Definition at line 530 of file controller.c.
References callback, spinlock_t::destroy, FAILED, INIT, listener, interface_logger_t::listener, interface_job_t::listener, interface_listener_t::logger, OUT_OF_RES, spinlock_create(), status, interface_listener_t::status, thread_cleanup_pop(), thread_cleanup_push(), TRUE, unique_id, and wait_for_listener().
 {
     interface_job_t *job;
     status_t status;
     INIT(job,
         .listener = {
             .public = {
                 .ike_state_change = _ike_state_change,
                 .child_state_change = _child_state_change,
             },
             .logger = {
                 .public = {
                     .log = _listener_log,
                     .get_level = _listener_get_level,
                 },
                 .callback = callback,
                 .param = param,
             },
             .status = FAILED,
             .id = unique_id,
             .lock = spinlock_create(),
         },
         .public = {
             .execute = _terminate_ike_execute,
             .get_priority = _get_priority_medium,
             .destroy = _destroy_job,
         },
         .refcount = 1,
     );
     job->listener.logger.listener = &job->listener;
     thread_cleanup_push((void*)destroy_job, job);
     if (callback == NULL)
     {
         terminate_ike_execute(job);
     }
     else
     {
         if (wait_for_listener(job, timeout))
         {
             job->listener.status = OUT_OF_RES;
         }
     }
     status = job->listener.status;
     thread_cleanup_pop(TRUE);
     return status;
 }
METHOD (job_t , terminate_child_execute , job_requeue_t , interface_job_t * job)
Definition at line 581 of file controller.c.
References interface_logger_t::callback, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, child_sa_manager_t::checkout_by_id, CHILD_ROUTED, daemon_t::child_sa_manager, DBG1, DBG_IKE, ike_sa_t::delete_child_sa, DESTROY_ME, FAILED, FALSE, child_sa_t::get_protocol, child_sa_t::get_spi, child_sa_t::get_state, interface_listener_t::id, interface_listener_t::ike_sa, daemon_t::ike_sa_manager, JOB_REQUEUE_NONE, listener, interface_job_t::listener, listener_done(), spinlock_t::lock, interface_listener_t::lock, interface_listener_t::logger, NOT_FOUND, interface_listener_t::status, SUCCESS, TRUE, and spinlock_t::unlock.
 {
     interface_listener_t *listener = &job->listener;
     u_int32_t id = listener->id;
     child_sa_t *child_sa;
     ike_sa_t *ike_sa;
     ike_sa = charon->child_sa_manager->checkout_by_id(charon->child_sa_manager,
                                                       id, &child_sa);
     if (!ike_sa)
     {
         DBG1(DBG_IKE, "unable to terminate, CHILD_SA with ID %d not found", id);
         listener->status = NOT_FOUND;
         /* release listener */
         listener_done(listener);
         return JOB_REQUEUE_NONE;
     }
     listener->lock->lock(listener->lock);
     listener->ike_sa = ike_sa;
     listener->lock->unlock(listener->lock);
     if (child_sa->get_state(child_sa) == CHILD_ROUTED)
     {
         DBG1(DBG_IKE, "unable to terminate, established "
              "CHILD_SA with ID %d not found", id);
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
         listener->status = NOT_FOUND;
         /* release listener */
         listener_done(listener);
         return JOB_REQUEUE_NONE;
     }
     if (ike_sa->delete_child_sa(ike_sa, child_sa->get_protocol(child_sa),
                     child_sa->get_spi(child_sa, TRUE), FALSE) != DESTROY_ME)
     {
         if (!listener->logger.callback)
         {
             listener->status = SUCCESS;
         }
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
     }
     else
     {
         listener->status = FAILED;
         charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                     ike_sa);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (controller_t , terminate_child , status_t , controller_t * this, u_int32_t unique_id, controller_cb_t callback, void * param, u_int timeout)
Definition at line 632 of file controller.c.
References callback, spinlock_t::destroy, FAILED, INIT, listener, interface_logger_t::listener, interface_job_t::listener, interface_listener_t::logger, OUT_OF_RES, spinlock_create(), status, interface_listener_t::status, thread_cleanup_pop(), thread_cleanup_push(), TRUE, unique_id, and wait_for_listener().
 {
     interface_job_t *job;
     status_t status;
     INIT(job,
         .listener = {
             .public = {
                 .ike_state_change = _ike_state_change,
                 .child_state_change = _child_state_change,
             },
             .logger = {
                 .public = {
                     .log = _listener_log,
                     .get_level = _listener_get_level,
                 },
                 .callback = callback,
                 .param = param,
             },
             .status = FAILED,
             .id = unique_id,
             .lock = spinlock_create(),
         },
         .public = {
             .execute = _terminate_child_execute,
             .get_priority = _get_priority_medium,
             .destroy = _destroy_job,
         },
         .refcount = 1,
     );
     job->listener.logger.listener = &job->listener;
     thread_cleanup_push((void*)destroy_job, job);
     if (callback == NULL)
     {
         terminate_child_execute(job);
     }
     else
     {
         if (wait_for_listener(job, timeout))
         {
             job->listener.status = OUT_OF_RES;
         }
     }
     status = job->listener.status;
     thread_cleanup_pop(TRUE);
     return status;
 }
METHOD (controller_t , destroy , void , private_controller_t * this)
Definition at line 692 of file controller.c.
References free().
 {
     free(this);
 }
static bool wait_for_listener (interface_job_t * job, u_int timeout) static
Registers the listener, executes the job and then waits synchronously until the listener is done or the timeout occurred.
Note
Use 'return listener_done(listener)' to properly unregister a listener
Parameters
listener listener to register
job job to execute asynchronously when registered, or NULL
timeout max timeout in ms to listen for events, 0 to disable
Returns
TRUE if timed out
Definition at line 185 of file controller.c.
References bus_t::add_listener, bus_t::add_logger, daemon_t::bus, charon, interface_listener_t::done, FALSE, lib, listener, interface_job_t::listener, listener_unregister(), interface_listener_t::logger, library_t::processor, interface_logger_t::public, interface_listener_t::public, interface_job_t::public, processor_t::queue_job, ref_get(), interface_job_t::refcount, semaphore_create, thread_cancelability(), thread_cleanup_pop(), thread_cleanup_push(), semaphore_t::timed_wait, TRUE, and semaphore_t::wait.
Referenced by METHOD().
 {
     interface_listener_t *listener = &job->listener;
     bool old, timed_out = FALSE;
     /* avoid that the job is destroyed too early */
     ref_get(&job->refcount);
     listener->done = semaphore_create(0);
     charon->bus->add_logger(charon->bus, &listener->logger.public);
     charon->bus->add_listener(charon->bus, &listener->public);
     lib->processor->queue_job(lib->processor, &job->public);
     thread_cleanup_push((thread_cleanup_t)listener_unregister, listener);
     old = thread_cancelability(TRUE);
     if (timeout)
     {
         timed_out = listener->done->timed_wait(listener->done, timeout);
     }
     else
     {
         listener->done->wait(listener->done);
     }
     thread_cancelability(old);
     thread_cleanup_pop(TRUE);
     return timed_out;
 }