strongSwan: duplicheck_listener
duplicheck_listener
duplicheck
Classes
struct duplicheck_listener_t
Typedefs
typedef struct
duplicheck_listener_t duplicheck_listener_t
Functions
duplicheck_listener_t * duplicheck_listener_create (duplicheck_notify_t *notify)
Detailed Description
Typedef Documentation
typedef struct duplicheck_listener_t duplicheck_listener_t
Definition at line 28 of file duplicheck_listener.h.
Function Documentation
duplicheck_listener_t* duplicheck_listener_create (duplicheck_notify_t * notify)
Create a duplicheck_listener instance.
Parameters
notify socket to send notifications to
Returns
listener
See header
Definition at line 301 of file duplicheck_listener.c.
References equals(), hash(), hashtable_create(), INIT, mutex_create(), MUTEX_TYPE_DEFAULT, and notify().
Referenced by duplicheck_plugin_create().
 {
     private_duplicheck_listener_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .ike_rekey = _ike_rekey,
                 .ike_updown = _ike_updown,
                 .message = _message_hook,
             },
             .destroy = _destroy,
         },
         .notify = notify,
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .active = hashtable_create((hashtable_hash_t)hash,
                                    (hashtable_equals_t)equals, 32),
         .checking = hashtable_create((hashtable_hash_t)hash,
                                      (hashtable_equals_t)equals, 2),
     );
     return &this->public;
 }