strongSwan: command.c File Reference
swanctl/command.c File Reference
#include "command.h"
#include <getopt.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <library.h>
#include <utils/debug.h>
#include <utils/optionsfrom.h>
Macros
#define _GNU_SOURCE
Functions
static void build_opts ()
int command_getopt (char **arg)
void command_register (command_t command)
int command_usage (char *error,...)
static void cleanup ()
static bool process_common_opts ()
static int call_command (command_t *cmd)
int command_dispatch (int c, char *v[])
Variables
static command_t cmds [MAX_COMMANDS]
static int active = 0
static int registered = 0
static int help_idx
static char * uri = NULL
static int argc
static char ** argv
static options_t * options
static struct option command_opts [MAX_COMMANDS > MAX_OPTIONS?MAX_COMMANDS:MAX_OPTIONS]
static char command_optstring [(MAX_COMMANDS > MAX_OPTIONS?MAX_COMMANDS:MAX_OPTIONS)*3]
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 18 of file swanctl/command.c.
Function Documentation
static void build_opts () static
Build command_opts/command_optstr for the active command
Definition at line 75 of file swanctl/command.c.
References active, command_option_t::arg, command_t::cmd, command_opts, command_optstring, help_idx, MAX_COMMANDS, memset, command_option_t::name, command_option_t::op, command_t::op, and command_t::options.
Referenced by command_dispatch().
 {
     int i, pos = 0;
     memset(command_opts, 0, sizeof(command_opts));
     memset(command_optstring, 0, sizeof(command_optstring));
     if (active == help_idx)
     {
         for (i = 0; i < MAX_COMMANDS && cmds[i].cmd; i++)
         {
             command_opts[i].name = cmds[i].cmd;
             command_opts[i].val = cmds[i].op;
             command_optstring[i] = cmds[i].op;
         }
     }
     else
     {
         for (i = 0; cmds[active].options[i].name; i++)
         {
             command_opts[i].name = cmds[active].options[i].name;
             command_opts[i].has_arg = cmds[active].options[i].arg;
             command_opts[i].val = cmds[active].options[i].op;
             command_optstring[pos++] = cmds[active].options[i].op;
             switch (cmds[active].options[i].arg)
             {
                 case optional_argument:
                     command_optstring[pos++] = ':';
                     /* FALL */
                 case required_argument:
                     command_optstring[pos++] = ':';
                     /* FALL */
                 case no_argument:
                 default:
                     break;
             }
         }
     }
 }
static int call_command (command_t * cmd) static
Open vici connection, call a command
Definition at line 284 of file swanctl/command.c.
References command_t::call, command_usage(), conn, strerror, uri, vici_connect(), and vici_disconnect().
Referenced by command_dispatch().
 {
     vici_conn_t *conn;
     int ret;
     conn = vici_connect(uri);
     if (!conn)
     {
         ret = errno;
         command_usage("connecting to '%s' URI failed: %s",
                       uri ?: "default", strerror(errno));
         return ret;
     }
     ret = cmd->call(conn);
     vici_disconnect(conn);
     return ret;
 }
static void cleanup (void) static
Dispatch cleanup hook
Definition at line 245 of file swanctl/command.c.
References options_t::destroy.
Referenced by command_dispatch().
 {
     options->destroy(options);
 }
static bool process_common_opts () static
Process options common for all commands
Definition at line 253 of file swanctl/command.c.
References argc, argv, command_opts, command_optstring, dbg_default_set_level(), FALSE, options_t::from, TRUE, and uri.
Referenced by command_dispatch().
 {
     while (TRUE)
     {
         switch (getopt_long(argc, argv, command_optstring, command_opts, NULL))
         {
             case '+':
                 if (!options->from(options, optarg, &argc, &argv, optind))
                 {
                     return FALSE;
                 }
                 continue;
             case 'v':
                 dbg_default_set_level(atoi(optarg));
                 continue;
             case 'u':
                 uri = optarg;
                 continue;
             default:
                 continue;
             case '?':
                 return FALSE;
             case EOF:
                 return TRUE;
         }
     }
 }
Variable Documentation
int active = 0 static
active command.
Definition at line 37 of file swanctl/command.c.
Referenced by build_opts(), command_dispatch(), command_register(), and command_usage().
int argc static
Definition at line 54 of file swanctl/command.c.
Referenced by command_dispatch(), command_getopt(), and process_common_opts().
char** argv static
Definition at line 56 of file swanctl/command.c.
Referenced by command_dispatch(), command_getopt(), and process_common_opts().
command_t cmds[MAX_COMMANDS] static
Registered commands.
Definition at line 32 of file swanctl/command.c.
struct option command_opts[MAX_COMMANDS > MAX_OPTIONS?MAX_COMMANDS:MAX_OPTIONS] static
Global options used by all subcommands
Definition at line 63 of file swanctl/command.c.
Referenced by build_opts(), command_dispatch(), command_getopt(), and process_common_opts().
char command_optstring[(MAX_COMMANDS > MAX_OPTIONS?MAX_COMMANDS:MAX_OPTIONS)*3] static
Global optstring used by all subcommands
Definition at line 70 of file swanctl/command.c.
Referenced by build_opts(), command_dispatch(), command_getopt(), and process_common_opts().
int help_idx static
help command index
Definition at line 47 of file swanctl/command.c.
Referenced by build_opts(), command_dispatch(), and command_usage().
options_t* options static
Definition at line 58 of file swanctl/command.c.
int registered = 0 static
number of registered commands
Definition at line 42 of file swanctl/command.c.
Referenced by command_dispatch(), and command_register().
char* uri = NULL static
Uri to connect to
Definition at line 52 of file swanctl/command.c.
Referenced by call_command(), and process_common_opts().