strongSwan: tcg_swid_attr_req_t Struct Reference
tcg_swid_attr_req_t Struct Reference
tcg_swid_attr_req
#include "tcg_swid_attr_req.h"
Public Attributes
pa_tnc_attr_t pa_tnc_attribute
u_int8_t(* get_flags)(tcg_swid_attr_req_t *this)
u_int32_t(* get_request_id)(tcg_swid_attr_req_t *this)
u_int32_t(* get_earliest_eid)(tcg_swid_attr_req_t *this)
void(* add_target)(tcg_swid_attr_req_t *this, swid_tag_id_t *tag_id)
swid_inventory_t *(* get_targets)(tcg_swid_attr_req_t *this)
Detailed Description
Class implementing the TCG SWID Request attribute
Definition at line 44 of file tcg_swid_attr_req.h.
Member Data Documentation
void(* tcg_swid_attr_req_t::add_target)(tcg_swid_attr_req_t *this, swid_tag_id_t *tag_id)
Add Tag ID
Parameters
tag_id SWID Tag ID (is not cloned by constructor!)
Definition at line 77 of file tcg_swid_attr_req.h.
Referenced by METHOD().
u_int32_t(* tcg_swid_attr_req_t::get_earliest_eid)(tcg_swid_attr_req_t *this)
Get Earliest EID
Returns
Event ID
Definition at line 70 of file tcg_swid_attr_req.h.
u_int8_t(* tcg_swid_attr_req_t::get_flags)(tcg_swid_attr_req_t *this)
Get SWID request flags
Returns
Flags
Definition at line 56 of file tcg_swid_attr_req.h.
Referenced by receive_message().
u_int32_t(* tcg_swid_attr_req_t::get_request_id)(tcg_swid_attr_req_t *this)
Get Request ID
Returns
Request ID
Definition at line 63 of file tcg_swid_attr_req.h.
Referenced by receive_message().
swid_inventory_t*(* tcg_swid_attr_req_t::get_targets)(tcg_swid_attr_req_t *this)
Create Tag ID enumerator
Returns
Get a list of target tag IDs
Definition at line 84 of file tcg_swid_attr_req.h.
Referenced by receive_message().
pa_tnc_attr_t tcg_swid_attr_req_t::pa_tnc_attribute
Public PA-TNC attribute interface
Definition at line 49 of file tcg_swid_attr_req.h.
The documentation for this struct was generated from the following file:
tcg_swid_attr_req.h