strongSwan: tnccs_error_msg.c File Reference
tnccs_error_msg.c File Reference
#include "tnccs_error_msg.h"
#include <utils/debug.h>
Classes
struct private_tnccs_error_msg_t
Typedefs
typedef struct
private_tnccs_error_msg_t private_tnccs_error_msg_t
Functions
ENUM (tnccs_error_type_names, TNCCS_ERROR_BATCH_TOO_LONG, TNCCS_ERROR_OTHER,"batch-too-long","malformed-batch","invalid-batch-id","invalid-recipient-type","internal-error","other")
METHOD (tnccs_msg_t, get_type, tnccs_msg_type_t, private_tnccs_error_msg_t *this)
METHOD (tnccs_msg_t, get_node, xmlNodePtr, private_tnccs_error_msg_t *this)
METHOD (tnccs_msg_t, get_ref, tnccs_msg_t *, private_tnccs_error_msg_t *this)
METHOD (tnccs_msg_t, destroy, void, private_tnccs_error_msg_t *this)
METHOD (tnccs_error_msg_t, get_message, char *, private_tnccs_error_msg_t *this, tnccs_error_type_t *type)
tnccs_msg_t * tnccs_error_msg_create_from_node (xmlNodePtr node)
tnccs_msg_t * tnccs_error_msg_create (tnccs_error_type_t type, char *msg)
Typedef Documentation
typedef struct private_tnccs_error_msg_t private_tnccs_error_msg_t
Definition at line 29 of file tnccs_error_msg.c.
Function Documentation
ENUM (tnccs_error_type_names , TNCCS_ERROR_BATCH_TOO_LONG , TNCCS_ERROR_OTHER , "batch-too-long" , "malformed-batch" , "invalid-batch-id" , "invalid-recipient-type" , "internal-error" , "other")
METHOD (tnccs_msg_t , get_type , tnccs_msg_type_t , private_tnccs_error_msg_t * this)
Definition at line 67 of file tnccs_error_msg.c.
References type.
 {
     return this->type;
 }
METHOD (tnccs_msg_t , get_node , xmlNodePtr , private_tnccs_error_msg_t * this)
Definition at line 73 of file tnccs_error_msg.c.
 {
     return this->node;
 }
METHOD (tnccs_msg_t , get_ref , tnccs_msg_t * , private_tnccs_error_msg_t * this)
Definition at line 79 of file tnccs_error_msg.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.tnccs_msg_interface;
 }
METHOD (tnccs_msg_t , destroy , void , private_tnccs_error_msg_t * this)
Definition at line 86 of file tnccs_error_msg.c.
References free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         free(this->error_msg);
         free(this);
     }
 }
METHOD (tnccs_error_msg_t , get_message , char * , private_tnccs_error_msg_t * this, tnccs_error_type_t * type)
Definition at line 96 of file tnccs_error_msg.c.
 {
     *type = this->error_type;
     return this->error_msg;
 }