strongSwan: dumm.h File Reference
dumm.h File Reference
#include <signal.h>
#include <library.h>
#include <collections/enumerator.h>
#include "guest.h"
#include "bridge.h"
Classes
struct dumm_t
Typedefs
typedef struct dumm_t dumm_t
Functions
dumm_t * dumm_create (char *dir)
Typedef Documentation
typedef struct dumm_t dumm_t
Definition at line 28 of file dumm.h.
Function Documentation
dumm_t* dumm_create (char * dir)
Create a group of UML hosts and networks.
Parameters
dir directory to create guests/load from, NULL for cwd
Returns
created UML group, or NULL if failed.
create a dumm instance
Definition at line 376 of file dumm.c.
References asprintf(), DBG1, DBG_LIB, destroy(), free(), GUEST_DIR, INIT, linked_list_create(), load_guests(), PERME, and strdup.
Referenced by Init_dumm(), and main().
 {
     char cwd[PATH_MAX];
     private_dumm_t *this;
     INIT(this,
         .public = {
             .create_guest = _create_guest,
             .create_guest_enumerator = _create_guest_enumerator,
             .delete_guest = _delete_guest,
             .create_bridge = _create_bridge,
             .create_bridge_enumerator = _create_bridge_enumerator,
             .delete_bridge = _delete_bridge,
             .add_overlay = _add_overlay,
             .del_overlay = _del_overlay,
             .pop_overlay = _pop_overlay,
             .load_template = _load_template,
             .create_template_enumerator = _create_template_enumerator,
             .destroy = _destroy,
         },
     );
     if (dir && *dir == '/')
     {
         this->dir = strdup(dir);
     }
     else
     {
         if (getcwd(cwd, sizeof(cwd)) == NULL)
         {
             free(this);
             return NULL;
         }
         if (dir)
         {
             if (asprintf(&this->dir, "%s/%s", cwd, dir) < 0)
             {
                 this->dir = NULL;
             }
         }
         else
         {
             this->dir = strdup(cwd);
         }
     }
     if (asprintf(&this->guest_dir, "%s/%s", this->dir, GUEST_DIR) < 0)
     {
         this->guest_dir = NULL;
     }
     this->guests = linked_list_create();
     this->bridges = linked_list_create();
     if (this->dir == NULL || this->guest_dir == NULL ||
         (mkdir(this->guest_dir, PERME) < 0 && errno != EEXIST))
     {
         DBG1(DBG_LIB, "creating guest directory '%s' failed: %m",
              this->guest_dir);
         destroy(this);
         return NULL;
     }
     load_guests(this);
     return &this->public;
 }