strongSwan: pts_component_manager.c File Reference
pts_component_manager.c File Reference
#include "pts/components/pts_component_manager.h"
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct vendor_entry_t
struct component_entry_t
struct private_pts_component_manager_t
Macros
#define PTS_QUALIFIER_SIZE 6
Typedefs
typedef struct
private_pts_component_manager_t private_pts_component_manager_t
typedef struct vendor_entry_t vendor_entry_t
typedef struct component_entry_t component_entry_t
Functions
static void vendor_entry_destroy (vendor_entry_t *entry)
METHOD (pts_component_manager_t, add_vendor, void, private_pts_component_manager_t *this, pen_t vendor_id, enum_name_t *comp_func_names, int qualifier_type_size, char *qualifier_flag_names, enum_name_t *qualifier_type_names)
METHOD (pts_component_manager_t, get_comp_func_names, enum_name_t *, private_pts_component_manager_t *this, pen_t vendor_id)
METHOD (pts_component_manager_t, get_qualifier_type_names, enum_name_t *, private_pts_component_manager_t *this, pen_t vendor_id)
METHOD (pts_component_manager_t, add_component, void, private_pts_component_manager_t *this, pen_t vendor_id, u_int32_t name, pts_component_create_t create)
METHOD (pts_component_manager_t, remove_vendor, void, private_pts_component_manager_t *this, pen_t vendor_id)
METHOD (pts_component_manager_t, get_qualifier, u_int8_t, private_pts_component_manager_t *this, pts_comp_func_name_t *name, char *flags)
METHOD (pts_component_manager_t, create, pts_component_t *, private_pts_component_manager_t *this, pts_comp_func_name_t *name, u_int32_t depth, pts_database_t *pts_db)
METHOD (pts_component_manager_t, destroy, void, private_pts_component_manager_t *this)
pts_component_manager_t * pts_component_manager_create (void)
Macro Definition Documentation
#define PTS_QUALIFIER_SIZE 6
Definition at line 25 of file pts_component_manager.c.
Referenced by METHOD().
Typedef Documentation
typedef struct component_entry_t component_entry_t
Definition at line 23 of file pts_component_manager.c.
typedef struct private_pts_component_manager_t private_pts_component_manager_t
Definition at line 21 of file pts_component_manager.c.
typedef struct vendor_entry_t vendor_entry_t
Definition at line 22 of file pts_component_manager.c.
Function Documentation
METHOD (pts_component_manager_t , add_vendor , void , private_pts_component_manager_t * this, pen_t vendor_id, enum_name_t * comp_func_names, int qualifier_type_size, char * qualifier_flag_names, enum_name_t * qualifier_type_names)
Definition at line 105 of file pts_component_manager.c.
References vendor_entry_t::comp_func_names, vendor_entry_t::components, DBG2, DBG_PTS, linked_list_t::insert_last, linked_list_create(), list, malloc_thing, pen_names, vendor_entry_t::qualifier_flag_names, vendor_entry_t::qualifier_type_names, vendor_entry_t::qualifier_type_size, and vendor_entry_t::vendor_id.
 {
     vendor_entry_t *entry;
     entry = malloc_thing(vendor_entry_t);
     entry->vendor_id = vendor_id;
     entry->comp_func_names = comp_func_names;
     entry->qualifier_type_size = qualifier_type_size;
     entry->qualifier_flag_names = qualifier_flag_names;
     entry->qualifier_type_names = qualifier_type_names;
     entry->components = linked_list_create();
     this->list->insert_last(this->list, entry);
     DBG2(DBG_PTS, "added %N functional component namespace",
          pen_names, vendor_id);
 }
METHOD (pts_component_manager_t , get_comp_func_names , enum_name_t * , private_pts_component_manager_t * this, pen_t vendor_id)
Definition at line 125 of file pts_component_manager.c.
References vendor_entry_t::comp_func_names, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, list, and vendor_entry_t::vendor_id.
 {
     enumerator_t *enumerator;
     vendor_entry_t *entry;
     enum_name_t *names = NULL;
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->vendor_id == vendor_id)
         {
             names = entry->comp_func_names;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return names;
 }
METHOD (pts_component_manager_t , get_qualifier_type_names , enum_name_t * , private_pts_component_manager_t * this, pen_t vendor_id)
Definition at line 146 of file pts_component_manager.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, list, vendor_entry_t::qualifier_type_names, and vendor_entry_t::vendor_id.
 {
     enumerator_t *enumerator;
     vendor_entry_t *entry;
     enum_name_t *names = NULL;
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->vendor_id == vendor_id)
         {
             names = entry->qualifier_type_names;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return names;
 }
METHOD (pts_component_manager_t , add_component , void , private_pts_component_manager_t * this, pen_t vendor_id, u_int32_t name, pts_component_create_t create)
Definition at line 167 of file pts_component_manager.c.
References vendor_entry_t::components, create, component_entry_t::create, linked_list_t::create_enumerator, DBG2, DBG_PTS, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, list, malloc_thing, name, component_entry_t::name, pen_names, and vendor_entry_t::vendor_id.
 {
     enumerator_t *enumerator;
     vendor_entry_t *entry;
     component_entry_t *component;
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->vendor_id == vendor_id)
         {
             component = malloc_thing(component_entry_t);
             component->name = name;
             component->create = create;
             entry->components->insert_last(entry->components, component);
             DBG2(DBG_PTS, "added %N functional component '%N'",
                  pen_names, vendor_id,
                  get_comp_func_names(this, vendor_id), name);
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (pts_component_manager_t , remove_vendor , void , private_pts_component_manager_t * this, pen_t vendor_id)
Definition at line 193 of file pts_component_manager.c.
References linked_list_t::create_enumerator, DBG2, DBG_PTS, enumerator_t::destroy, enumerator_t::enumerate, list, pen_names, linked_list_t::remove_at, vendor_entry_destroy(), and vendor_entry_t::vendor_id.
 {
     enumerator_t *enumerator;
     vendor_entry_t *entry;
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->vendor_id == vendor_id)
         {
             this->list->remove_at(this->list, enumerator);
             vendor_entry_destroy(entry);
             DBG2(DBG_PTS, "removed %N functional component namespace",
                  pen_names, vendor_id);
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (pts_component_manager_t , get_qualifier , u_int8_t , private_pts_component_manager_t * this, pts_comp_func_name_t * name, char * flags)
Definition at line 213 of file pts_component_manager.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, pts_comp_func_name_t::get_qualifier, pts_comp_func_name_t::get_vendor_id, list, PTS_QUALIFIER_SIZE, vendor_entry_t::qualifier_flag_names, vendor_entry_t::qualifier_type_size, size, type, and vendor_entry_t::vendor_id.
 {
     enumerator_t *enumerator;
     vendor_entry_t *entry;
     u_int8_t qualifier, size, flag, type = 0;
     int i;
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->vendor_id == name->get_vendor_id(name))
         {
             qualifier = name->get_qualifier(name);
             size = entry->qualifier_type_size;
             /* mask qualifier type field */
             type = qualifier & ((1 << size) - 1);
             /* determine flags */
             size = PTS_QUALIFIER_SIZE - size;
             flag = (1 << (PTS_QUALIFIER_SIZE - 1));
             if (flags)
             {
                 for (i = 0 ; i < size; i++)
                 {
                     flags[i] = (qualifier & flag) ?
                                 entry->qualifier_flag_names[i] : '.';
                     flag >>= 1;
                 }
                 flags[size] = '\0';
             }
         }
     }
     enumerator->destroy(enumerator);
     return type;
 }
METHOD (pts_component_manager_t , create , pts_component_t * , private_pts_component_manager_t * this, pts_comp_func_name_t * name, u_int32_t depth, pts_database_t * pts_db)
Definition at line 253 of file pts_component_manager.c.
References vendor_entry_t::components, component_entry_t::create, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, pts_comp_func_name_t::get_name, pts_comp_func_name_t::get_vendor_id, list, component_entry_t::name, and vendor_entry_t::vendor_id.
 {
     enumerator_t *enumerator, *e2;
     vendor_entry_t *entry;
     component_entry_t *entry2;
     pts_component_t *component = NULL;
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->vendor_id == name->get_vendor_id(name))
         {
             e2 = entry->components->create_enumerator(entry->components);
             while (e2->enumerate(e2, &entry2))
             {
                 if (entry2->name == name->get_name(name) && entry2->create)
                 {
                     component = entry2->create(depth, pts_db);
                     break;
                 }
             }
             e2->destroy(e2);
             break;
         }
     }
     enumerator->destroy(enumerator);
     return component;
 }
METHOD (pts_component_manager_t , destroy , void , private_pts_component_manager_t * this)
Definition at line 285 of file pts_component_manager.c.
References linked_list_t::destroy_function, free(), list, and vendor_entry_destroy().
 {
     this->list->destroy_function(this->list, (void *)vendor_entry_destroy);
     free(this);
 }
static void vendor_entry_destroy (vendor_entry_t * entry) static
Destroy a vendor_entry_t object
Definition at line 66 of file pts_component_manager.c.
References vendor_entry_t::components, linked_list_t::destroy_function, and free().
Referenced by METHOD().
 {
     entry->components->destroy_function(entry->components, free);
     free(entry);
 }