strongSwan: hash_algorithm_set.c File Reference
hash_algorithm_set.c File Reference
#include "hash_algorithm_set.h"
#include <collections/array.h>
Classes
struct private_hash_algorithm_set_t
Typedefs
typedef struct
private_hash_algorithm_set_t private_hash_algorithm_set_t
Functions
static int hash_sort (const void *a, const void *b, void *user)
static int hash_find (const void *a, const void *b)
METHOD (hash_algorithm_set_t, contains, bool, private_hash_algorithm_set_t *this, hash_algorithm_t hash)
METHOD (hash_algorithm_set_t, add, void, private_hash_algorithm_set_t *this, hash_algorithm_t hash)
METHOD (hash_algorithm_set_t, count, int, private_hash_algorithm_set_t *this)
static bool hash_filter (void *data, void **in, hash_algorithm_t *out)
METHOD (hash_algorithm_set_t, create_enumerator, enumerator_t *, private_hash_algorithm_set_t *this)
METHOD (hash_algorithm_set_t, destroy, void, private_hash_algorithm_set_t *this)
hash_algorithm_set_t * hash_algorithm_set_create ()
Typedef Documentation
typedef struct private_hash_algorithm_set_t private_hash_algorithm_set_t
Definition at line 20 of file hash_algorithm_set.c.
Function Documentation
static bool hash_filter (void * data, void ** in, hash_algorithm_t * out) static
Definition at line 74 of file hash_algorithm_set.c.
References TRUE.
Referenced by METHOD().
 {
     *out = **(hash_algorithm_t**)in;
     return TRUE;
 }
static int hash_find (const void * a, const void * b) static
Find a hash algorithm
Definition at line 47 of file hash_algorithm_set.c.
References hash_sort().
Referenced by METHOD().
 {
     return hash_sort(a, b, NULL);
 }
static int hash_sort (const void * a, const void * b, void * user) static
Sort hash algorithms
Definition at line 38 of file hash_algorithm_set.c.
References a, and b.
Referenced by hash_find(), and METHOD().
 {
     const hash_algorithm_t *ha = a, *hb = b;
     return *ha - *hb;
 }
METHOD (hash_algorithm_set_t , contains , bool , private_hash_algorithm_set_t * this, hash_algorithm_t hash)
Definition at line 52 of file hash_algorithm_set.c.
References array_bsearch(), and hash_find().
 {
     return array_bsearch(this->algorithms, &hash, hash_find, NULL) != -1;
 }
METHOD (hash_algorithm_set_t , add , void , private_hash_algorithm_set_t * this, hash_algorithm_t hash)
Definition at line 58 of file hash_algorithm_set.c.
References array_insert(), array_sort(), ARRAY_TAIL, and hash_sort().
 {
     if (!contains(this, hash))
     {
         array_insert(this->algorithms, ARRAY_TAIL, &hash);
         array_sort(this->algorithms, hash_sort, NULL);
     }
 }
METHOD (hash_algorithm_set_t , count , int , private_hash_algorithm_set_t * this)
Definition at line 68 of file hash_algorithm_set.c.
References array_count().
 {
     return array_count(this->algorithms);
 }
METHOD (hash_algorithm_set_t , create_enumerator , enumerator_t * , private_hash_algorithm_set_t * this)
Definition at line 80 of file hash_algorithm_set.c.
References array_create_enumerator(), enumerator_create_filter(), and hash_filter().
 {
     return enumerator_create_filter(array_create_enumerator(this->algorithms),
                                     (void*)hash_filter, NULL, NULL);
 }
METHOD (hash_algorithm_set_t , destroy , void , private_hash_algorithm_set_t * this)
Definition at line 87 of file hash_algorithm_set.c.
References array_destroy(), and free().
 {
     array_destroy(this->algorithms);
     free(this);
 }