strongSwan: test_event.c File Reference
test_event.c File Reference
#include <test_suite.h>
#include "../vici_dispatcher.h"
#include "../libvici.h"
#include <unistd.h>
Macros
#define URI "unix:///tmp/strongswan-vici-event-test"
#define EVENT_COUNT 500
Functions
static void event_cb (void *user, char *name, vici_res_t *ev)
START_TEST (test_event)
CALLBACK (raise_cb, vici_message_t *, vici_dispatcher_t *dispatcher, char *name, u_int id, vici_message_t *req)
CALLBACK (raise_event_cb, void, int *count, char *name, vici_res_t *ev)
START_TEST (test_raise_events)
END_TEST START_TEST (test_stress)
END_TEST Suite * event_suite_create ()
Macro Definition Documentation
#define EVENT_COUNT 500
Definition at line 82 of file test_event.c.
Referenced by CALLBACK(), and START_TEST().
#define URI "unix:///tmp/strongswan-vici-event-test"
Definition at line 26 of file test_event.c.
Referenced by START_TEST().
Function Documentation
CALLBACK (raise_cb , vici_message_t * , vici_dispatcher_t * dispatcher, char * name, u_int id, vici_message_t * req)
Definition at line 84 of file test_event.c.
References chunk_from_thing, EVENT_COUNT, vici_dispatcher_t::raise_event, VICI_END, VICI_KEY_VALUE, and vici_message_create_from_args().
 {
     u_int i;
     for (i = 0; i < EVENT_COUNT; i++)
     {
         dispatcher->raise_event(dispatcher, "event", id,
             vici_message_create_from_args(
                  VICI_KEY_VALUE, "counter", chunk_from_thing(i),
                 VICI_END));
     }
     return vici_message_create_from_args(VICI_END);
 }
CALLBACK (raise_event_cb , void , int * count, char * name, vici_res_t * ev)
Definition at line 99 of file test_event.c.
References ck_assert, ck_assert_int_eq, ck_assert_str_eq, len, value, vici_parse(), VICI_PARSE_END, VICI_PARSE_KEY_VALUE, vici_parse_name(), and vici_parse_value().
 {
     u_int *value, len;
     ck_assert_str_eq(name, "event");
     ck_assert(vici_parse(ev) == VICI_PARSE_KEY_VALUE);
     ck_assert_str_eq(vici_parse_name(ev), "counter");
     value = vici_parse_value(ev, &len);
     ck_assert_int_eq(len, sizeof(*value));
     ck_assert(vici_parse(ev) == VICI_PARSE_END);
     ck_assert_int_eq(*count, *value);
     (*count)++;
 }
static void event_cb (void * user, char * name, vici_res_t * ev) static
Definition at line 29 of file test_event.c.
References ck_assert, ck_assert_str_eq, count, vici_parse(), VICI_PARSE_END, VICI_PARSE_KEY_VALUE, vici_parse_name(), and vici_parse_value_str().
Referenced by START_TEST().
 {
     int *count = (int*)user;
     ck_assert_str_eq(name, "test");
     ck_assert(vici_parse(ev) == VICI_PARSE_KEY_VALUE);
     ck_assert_str_eq(vici_parse_name(ev), "key1");
     ck_assert_str_eq(vici_parse_value_str(ev), "value1");
     ck_assert(vici_parse(ev) == VICI_PARSE_END);
     (*count)++;
 }
END_TEST Suite* event_suite_create ()
Definition at line 204 of file test_event.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("vici events");
     tc = tcase_create("single");
     tcase_add_test(tc, test_event);
     suite_add_tcase(s, tc);
     tc = tcase_create("raise events");
     tcase_add_test(tc, test_raise_events);
     suite_add_tcase(s, tc);
     tc = tcase_create("stress");
     tcase_add_test(tc, test_stress);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_event)
Definition at line 42 of file test_event.c.
References processor_t::cancel, chunk_from_str, ck_assert, conn, count, vici_dispatcher_t::destroy, event_cb(), FALSE, lib, vici_dispatcher_t::manage_event, library_t::processor, vici_dispatcher_t::raise_event, processor_t::set_threads, TRUE, URI, usleep(), vici_connect(), vici_deinit(), vici_disconnect(), vici_dispatcher_create(), VICI_END, vici_init(), VICI_KEY_VALUE, vici_message_create_from_args(), and vici_register().
 {
     vici_dispatcher_t *dispatcher;
     vici_conn_t *conn;
     int count = 0;
     lib->processor->set_threads(lib->processor, 8);
     dispatcher = vici_dispatcher_create(URI);
     ck_assert(dispatcher);
     dispatcher->manage_event(dispatcher, "test", TRUE);
     vici_init();
     conn = vici_connect(URI);
     ck_assert(conn);
     ck_assert(vici_register(conn, "test", event_cb, &count) == 0);
     ck_assert(vici_register(conn, "nonexistent", event_cb, &count) != 0);
     dispatcher->raise_event(dispatcher, "test", 0, vici_message_create_from_args(
          VICI_KEY_VALUE, "key1", chunk_from_str("value1"),
         VICI_END));
     while (count == 0)
     {
         usleep(1000);
     }
     vici_disconnect(conn);
     dispatcher->manage_event(dispatcher, "test", FALSE);
     lib->processor->cancel(lib->processor);
     dispatcher->destroy(dispatcher);
     vici_deinit();
 }
START_TEST (test_raise_events)
Definition at line 115 of file test_event.c.
References processor_t::cancel, ck_assert, ck_assert_int_eq, conn, count, vici_dispatcher_t::destroy, EVENT_COUNT, FALSE, lib, vici_dispatcher_t::manage_command, vici_dispatcher_t::manage_event, library_t::processor, res, processor_t::set_threads, TRUE, URI, vici_begin(), vici_connect(), vici_deinit(), vici_disconnect(), vici_dispatcher_create(), vici_free_res(), vici_init(), vici_register(), and vici_submit().
 {
     vici_dispatcher_t *dispatcher;
     vici_res_t *res;
     vici_conn_t *conn;
     int count = 0;
     lib->processor->set_threads(lib->processor, 8);
     dispatcher = vici_dispatcher_create(URI);
     ck_assert(dispatcher);
     dispatcher->manage_event(dispatcher, "event", TRUE);
     dispatcher->manage_command(dispatcher, "raise", raise_cb, dispatcher);
     vici_init();
     conn = vici_connect(URI);
     ck_assert(conn);
     ck_assert(vici_register(conn, "event", raise_event_cb, &count) == 0);
     res = vici_submit(vici_begin("raise"), conn);
     ck_assert_int_eq(count, EVENT_COUNT);
     ck_assert(res);
     vici_free_res(res);
     vici_disconnect(conn);
     dispatcher->manage_event(dispatcher, "event", FALSE);
     dispatcher->manage_command(dispatcher, "raise", NULL, NULL);
     lib->processor->cancel(lib->processor);
     dispatcher->destroy(dispatcher);
     vici_deinit();
 }
END_TEST START_TEST (test_stress)
Definition at line 154 of file test_event.c.
References processor_t::cancel, chunk_from_str, ck_assert, conn, count, vici_dispatcher_t::destroy, event_cb(), FALSE, lib, vici_dispatcher_t::manage_event, library_t::processor, vici_dispatcher_t::raise_event, processor_t::set_threads, TRUE, URI, usleep(), vici_connect(), vici_deinit(), vici_disconnect(), vici_dispatcher_create(), VICI_END, vici_init(), VICI_KEY_VALUE, vici_message_create_from_args(), and vici_register().
 {
     vici_dispatcher_t *dispatcher;
     vici_conn_t *conn;
     int count = 0, i, total = 50;
     lib->processor->set_threads(lib->processor, 8);
     dispatcher = vici_dispatcher_create(URI);
     ck_assert(dispatcher);
     dispatcher->manage_event(dispatcher, "test", TRUE);
     dispatcher->manage_event(dispatcher, "dummy", TRUE);
     vici_init();
     conn = vici_connect(URI);
     ck_assert(conn);
     vici_register(conn, "test", event_cb, &count);
     for (i = 0; i < total; i++)
     {
         /* do some event re/deregistration in between */
         ck_assert(vici_register(conn, "dummy", event_cb, NULL) == 0);
         dispatcher->raise_event(dispatcher, "test", 0,
             vici_message_create_from_args(
                  VICI_KEY_VALUE, "key1", chunk_from_str("value1"),
                 VICI_END));
         ck_assert(vici_register(conn, "dummy", NULL, NULL) == 0);
     }
     while (count < total)
     {
         usleep(1000);
     }
     vici_disconnect(conn);
     dispatcher->manage_event(dispatcher, "test", FALSE);
     dispatcher->manage_event(dispatcher, "dummy", FALSE);
     lib->processor->cancel(lib->processor);
     dispatcher->destroy(dispatcher);
     vici_deinit();
 }