strongSwan: proposal_substructure.c File Reference
proposal_substructure.c File Reference
#include <stddef.h>
#include "proposal_substructure.h"
#include <encoding/payloads/encodings.h>
#include <encoding/payloads/transform_substructure.h>
#include <library.h>
#include <collections/linked_list.h>
#include <daemon.h>
Classes
struct private_proposal_substructure_t
struct algo_map_t
Macros
#define PROPOSAL_TYPE_VALUE 2
Typedefs
typedef struct
private_proposal_substructure_t private_proposal_substructure_t
Enumerations
enum ikev1_encryption_t {
IKEV1_ENCR_DES_CBC = 1, IKEV1_ENCR_IDEA_CBC = 2, IKEV1_ENCR_BLOWFISH_CBC = 3, IKEV1_ENCR_RC5_R16_B64_CBC = 4,
IKEV1_ENCR_3DES_CBC = 5, IKEV1_ENCR_CAST_CBC = 6, IKEV1_ENCR_AES_CBC = 7, IKEV1_ENCR_CAMELLIA_CBC = 8,
IKEV1_ENCR_SERPENT_CBC = 65004, IKEV1_ENCR_TWOFISH_CBC = 65005
}
enum ikev1_hash_t {
IKEV1_HASH_MD5 = 1, IKEV1_HASH_SHA1 = 2, IKEV1_HASH_TIGER = 3, IKEV1_HASH_SHA2_256 = 4,
IKEV1_HASH_SHA2_384 = 5, IKEV1_HASH_SHA2_512 = 6
}
enum ikev1_ike_transid_t { IKEV1_TRANSID_KEY_IKE = 1 }
enum ikev1_esp_transid_t {
IKEV1_ESP_ENCR_DES_IV64 = 1, IKEV1_ESP_ENCR_DES = 2, IKEV1_ESP_ENCR_3DES = 3, IKEV1_ESP_ENCR_RC5 = 4,
IKEV1_ESP_ENCR_IDEA = 5, IKEV1_ESP_ENCR_CAST = 6, IKEV1_ESP_ENCR_BLOWFISH = 7, IKEV1_ESP_ENCR_3IDEA = 8,
IKEV1_ESP_ENCR_DES_IV32 = 9, IKEV1_ESP_ENCR_RC4 = 10, IKEV1_ESP_ENCR_NULL = 11, IKEV1_ESP_ENCR_AES_CBC = 12,
IKEV1_ESP_ENCR_AES_CTR = 13, IKEV1_ESP_ENCR_AES_CCM_8 = 14, IKEV1_ESP_ENCR_AES_CCM_12 = 15, IKEV1_ESP_ENCR_AES_CCM_16 = 16,
IKEV1_ESP_ENCR_AES_GCM_8 = 18, IKEV1_ESP_ENCR_AES_GCM_12 = 19, IKEV1_ESP_ENCR_AES_GCM_16 = 20, IKEV1_ESP_ENCR_SEED_CBC = 21,
IKEV1_ESP_ENCR_CAMELLIA = 22, IKEV1_ESP_ENCR_NULL_AUTH_AES_GMAC = 23, IKEV1_ESP_ENCR_SERPENT = 252, IKEV1_ESP_ENCR_TWOFISH = 253
}
enum ikev1_ah_transid_t {
IKEV1_AH_HMAC_MD5 = 2, IKEV1_AH_HMAC_SHA = 3, IKEV1_AH_DES_MAC = 4, IKEV1_AH_HMAC_SHA2_256 = 5,
IKEV1_AH_HMAC_SHA2_384 = 6, IKEV1_AH_HMAC_SHA2_512 = 7, IKEV1_AH_RIPEMD = 8, IKEV1_AH_AES_XCBC_MAC = 9,
IKEV1_AH_RSA = 10, IKEV1_AH_AES_128_GMAC = 11, IKEV1_AH_AES_192_GMAC = 12, IKEV1_AH_AES_256_GMAC = 13
}
enum ikev1_auth_algo_t {
IKEV1_AUTH_HMAC_MD5 = 1, IKEV1_AUTH_HMAC_SHA = 2, IKEV1_AUTH_DES_MAC = 3, IKEV1_AUTH_KPDK = 4,
IKEV1_AUTH_HMAC_SHA2_256 = 5, IKEV1_AUTH_HMAC_SHA2_384 = 6, IKEV1_AUTH_HMAC_SHA2_512 = 7, IKEV1_AUTH_HMAC_RIPEMD = 8,
IKEV1_AUTH_AES_XCBC_MAC = 9, IKEV1_AUTH_SIG_RSA = 10, IKEV1_AUTH_AES_128_GMAC = 11, IKEV1_AUTH_AES_192_GMAC = 12,
IKEV1_AUTH_AES_256_GMAC = 13
}
enum ikev1_esp_encap_t {
IKEV1_ENCAP_TUNNEL = 1, IKEV1_ENCAP_TRANSPORT = 2, IKEV1_ENCAP_UDP_TUNNEL = 3, IKEV1_ENCAP_UDP_TRANSPORT = 4,
IKEV1_ENCAP_UDP_TUNNEL_DRAFT_00_03 = 61443, IKEV1_ENCAP_UDP_TRANSPORT_DRAFT_00_03 = 61444
}
enum ikev1_life_type_t { IKEV1_LIFE_TYPE_SECONDS = 1, IKEV1_LIFE_TYPE_KILOBYTES = 2 }
enum ikev1_auth_method_t {
IKEV1_AUTH_PSK = 1, IKEV1_AUTH_DSS_SIG = 2, IKEV1_AUTH_RSA_SIG = 3, IKEV1_AUTH_RSA_ENC = 4,
IKEV1_AUTH_RSA_ENC_REV = 5, IKEV1_AUTH_ECDSA_256 = 9, IKEV1_AUTH_ECDSA_384 = 10, IKEV1_AUTH_ECDSA_521 = 11,
IKEV1_AUTH_XAUTH_INIT_PSK = 65001, IKEV1_AUTH_XAUTH_RESP_PSK = 65002, IKEV1_AUTH_XAUTH_INIT_DSS = 65003, IKEV1_AUTH_XAUTH_RESP_DSS = 65004,
IKEV1_AUTH_XAUTH_INIT_RSA = 65005, IKEV1_AUTH_XAUTH_RESP_RSA = 65006, IKEV1_AUTH_XAUTH_INIT_RSA_ENC = 65007, IKEV1_AUTH_XAUTH_RESP_RSA_ENC = 65008,
IKEV1_AUTH_XAUTH_INIT_RSA_ENC_REV = 65009, IKEV1_AUTH_XAUTH_RESP_RSA_ENC_REV = 65010, IKEV1_AUTH_HYBRID_INIT_RSA = 64221, IKEV1_AUTH_HYBRID_RESP_RSA = 64222,
IKEV1_AUTH_HYBRID_INIT_DSS = 64223, IKEV1_AUTH_HYBRID_RESP_DSS = 64224
}
enum ikev1_ipcomp_transform_t { IKEV1_IPCOMP_OUI = 1, IKEV1_IPCOMP_DEFLATE = 2, IKEV1_IPCOMP_LZS = 3 }
Functions
METHOD (payload_t, verify, status_t, private_proposal_substructure_t *this)
METHOD (payload_t, get_encoding_rules, int, private_proposal_substructure_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_proposal_substructure_t *this)
METHOD (payload_t, get_type, payload_type_t, private_proposal_substructure_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_proposal_substructure_t *this)
METHOD (payload_t, set_next_type, void, private_proposal_substructure_t *this, payload_type_t type)
static void compute_length (private_proposal_substructure_t *this)
METHOD (payload_t, get_length, size_t, private_proposal_substructure_t *this)
static void add_transform_substructure (private_proposal_substructure_t *this, transform_substructure_t *transform)
METHOD (proposal_substructure_t, set_is_last_proposal, void, private_proposal_substructure_t *this, bool is_last)
METHOD (proposal_substructure_t, set_proposal_number, void, private_proposal_substructure_t *this, u_int8_t proposal_number)
METHOD (proposal_substructure_t, get_proposal_number, u_int8_t, private_proposal_substructure_t *this)
METHOD (proposal_substructure_t, set_protocol_id, void, private_proposal_substructure_t *this, u_int8_t protocol_id)
METHOD (proposal_substructure_t, get_protocol_id, u_int8_t, private_proposal_substructure_t *this)
METHOD (proposal_substructure_t, set_spi, void, private_proposal_substructure_t *this, chunk_t spi)
METHOD (proposal_substructure_t, get_spi, chunk_t, private_proposal_substructure_t *this)
METHOD (proposal_substructure_t, get_cpi, bool, private_proposal_substructure_t *this, u_int16_t *cpi)
static void add_to_proposal_v2 (proposal_t *proposal, transform_substructure_t *transform)
static u_int16_t ikev2_from_ikev1 (algo_map_t *map, int count, u_int16_t def, u_int16_t value)
static u_int16_t ikev1_from_ikev2 (algo_map_t *map, int count, u_int16_t value)
static u_int16_t get_alg_from_ikev1 (transform_type_t type, u_int16_t value)
static u_int16_t get_ikev1_from_alg (transform_type_t type, u_int16_t value)
static u_int16_t get_alg_from_ikev1_transid (transform_type_t type, u_int16_t value)
static u_int16_t get_ikev1_transid_from_alg (transform_type_t type, u_int16_t value)
static u_int16_t get_alg_from_ikev1_auth (u_int16_t value)
static u_int16_t get_ikev1_auth_from_alg (u_int16_t value)
static u_int16_t get_ikev1_auth (auth_method_t method)
static u_int16_t get_ikev1_mode (ipsec_mode_t mode, encap_t udp)
static void add_to_proposal_v1_ike (proposal_t *proposal, transform_substructure_t *transform)
static void add_to_proposal_v1 (proposal_t *proposal, transform_substructure_t *transform, protocol_id_t proto)
METHOD (proposal_substructure_t, get_proposals, void, private_proposal_substructure_t *this, linked_list_t *proposals)
METHOD (proposal_substructure_t, create_substructure_enumerator, enumerator_t *, private_proposal_substructure_t *this)
static u_int64_t get_attr (private_proposal_substructure_t *this, transform_attribute_type_t type)
static u_int64_t get_life_duration (private_proposal_substructure_t *this, transform_attribute_type_t type_attr, ikev1_life_type_t type, transform_attribute_type_t dur_attr)
METHOD (proposal_substructure_t, get_lifetime, u_int32_t, private_proposal_substructure_t *this)
METHOD (proposal_substructure_t, get_lifebytes, u_int64_t, private_proposal_substructure_t *this)
METHOD (proposal_substructure_t, get_auth_method, auth_method_t, private_proposal_substructure_t *this)
METHOD (proposal_substructure_t, get_encap_mode, ipsec_mode_t, private_proposal_substructure_t *this, bool *udp)
METHOD2 (payload_t, proposal_substructure_t, destroy, void, private_proposal_substructure_t *this)
proposal_substructure_t * proposal_substructure_create (payload_type_t type)
static void set_from_proposal_v1_ike (private_proposal_substructure_t *this, proposal_t *proposal, u_int32_t lifetime, auth_method_t method, int number)
static void set_from_proposal_v1 (private_proposal_substructure_t *this, proposal_t *proposal, u_int32_t lifetime, u_int64_t lifebytes, ipsec_mode_t mode, encap_t udp, int number)
static void set_from_proposal_v2 (private_proposal_substructure_t *this, proposal_t *proposal)
static void set_data (private_proposal_substructure_t *this, proposal_t *proposal)
proposal_substructure_t * proposal_substructure_create_from_proposal_v2 (proposal_t *proposal)
proposal_substructure_t * proposal_substructure_create_from_proposal_v1 (proposal_t *proposal, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp)
proposal_substructure_t * proposal_substructure_create_from_proposals_v1 (linked_list_t *proposals, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp)
proposal_substructure_t * proposal_substructure_create_for_ipcomp_v1 (u_int32_t lifetime, u_int64_t lifebytes, u_int16_t cpi, ipsec_mode_t mode, encap_t udp, u_int8_t proposal_number)
Variables
static encoding_rule_t encodings_v1 []
static encoding_rule_t encodings_v2 []
static algo_map_t map_encr []
static algo_map_t map_integ []
static algo_map_t map_prf []
static algo_map_t map_esp []
static algo_map_t map_ah []
static algo_map_t map_auth []
Macro Definition Documentation
#define PROPOSAL_TYPE_VALUE 2
IKEv2 Value for a proposal payload.
Definition at line 31 of file proposal_substructure.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_proposal_substructure_t private_proposal_substructure_t
Definition at line 33 of file proposal_substructure.c.
Enumeration Type Documentation
enum ikev1_ah_transid_t
IKEv1 Transform ID AH authentication algorithm.
Enumerator
IKEV1_AH_HMAC_MD5
IKEV1_AH_HMAC_SHA
IKEV1_AH_DES_MAC
IKEV1_AH_HMAC_SHA2_256
IKEV1_AH_HMAC_SHA2_384
IKEV1_AH_HMAC_SHA2_512
IKEV1_AH_RIPEMD
IKEV1_AH_AES_XCBC_MAC
IKEV1_AH_RSA
IKEV1_AH_AES_128_GMAC
IKEV1_AH_AES_192_GMAC
IKEV1_AH_AES_256_GMAC
Definition at line 232 of file proposal_substructure.c.
              {
     IKEV1_AH_HMAC_MD5 = 2,
     IKEV1_AH_HMAC_SHA = 3,
     IKEV1_AH_DES_MAC = 4,
     IKEV1_AH_HMAC_SHA2_256 = 5,
     IKEV1_AH_HMAC_SHA2_384 = 6,
     IKEV1_AH_HMAC_SHA2_512 = 7,
     IKEV1_AH_RIPEMD = 8,
     IKEV1_AH_AES_XCBC_MAC = 9,
     IKEV1_AH_RSA = 10,
     IKEV1_AH_AES_128_GMAC = 11,
     IKEV1_AH_AES_192_GMAC = 12,
     IKEV1_AH_AES_256_GMAC = 13,
 } ikev1_ah_transid_t;
enum ikev1_auth_algo_t
IKEv1 authentication algorithm.
Enumerator
IKEV1_AUTH_HMAC_MD5
IKEV1_AUTH_HMAC_SHA
IKEV1_AUTH_DES_MAC
IKEV1_AUTH_KPDK
IKEV1_AUTH_HMAC_SHA2_256
IKEV1_AUTH_HMAC_SHA2_384
IKEV1_AUTH_HMAC_SHA2_512
IKEV1_AUTH_HMAC_RIPEMD
IKEV1_AUTH_AES_XCBC_MAC
IKEV1_AUTH_SIG_RSA
IKEV1_AUTH_AES_128_GMAC
IKEV1_AUTH_AES_192_GMAC
IKEV1_AUTH_AES_256_GMAC
Definition at line 250 of file proposal_substructure.c.
              {
     IKEV1_AUTH_HMAC_MD5 = 1,
     IKEV1_AUTH_HMAC_SHA = 2,
     IKEV1_AUTH_DES_MAC = 3,
     IKEV1_AUTH_KPDK = 4,
     IKEV1_AUTH_HMAC_SHA2_256 = 5,
     IKEV1_AUTH_HMAC_SHA2_384 = 6,
     IKEV1_AUTH_HMAC_SHA2_512 = 7,
     IKEV1_AUTH_HMAC_RIPEMD = 8,
     IKEV1_AUTH_AES_XCBC_MAC = 9,
     IKEV1_AUTH_SIG_RSA = 10,
     IKEV1_AUTH_AES_128_GMAC = 11,
     IKEV1_AUTH_AES_192_GMAC = 12,
     IKEV1_AUTH_AES_256_GMAC = 13,
 } ikev1_auth_algo_t;
enum ikev1_auth_method_t
IKEv1 authentication methods
Enumerator
IKEV1_AUTH_PSK
IKEV1_AUTH_DSS_SIG
IKEV1_AUTH_RSA_SIG
IKEV1_AUTH_RSA_ENC
IKEV1_AUTH_RSA_ENC_REV
IKEV1_AUTH_ECDSA_256
IKEV1_AUTH_ECDSA_384
IKEV1_AUTH_ECDSA_521
IKEV1_AUTH_XAUTH_INIT_PSK
IKEV1_AUTH_XAUTH_RESP_PSK
IKEV1_AUTH_XAUTH_INIT_DSS
IKEV1_AUTH_XAUTH_RESP_DSS
IKEV1_AUTH_XAUTH_INIT_RSA
IKEV1_AUTH_XAUTH_RESP_RSA
IKEV1_AUTH_XAUTH_INIT_RSA_ENC
IKEV1_AUTH_XAUTH_RESP_RSA_ENC
IKEV1_AUTH_XAUTH_INIT_RSA_ENC_REV
IKEV1_AUTH_XAUTH_RESP_RSA_ENC_REV
IKEV1_AUTH_HYBRID_INIT_RSA
IKEV1_AUTH_HYBRID_RESP_RSA
IKEV1_AUTH_HYBRID_INIT_DSS
IKEV1_AUTH_HYBRID_RESP_DSS
Definition at line 289 of file proposal_substructure.c.
              {
     IKEV1_AUTH_PSK = 1,
     IKEV1_AUTH_DSS_SIG = 2,
     IKEV1_AUTH_RSA_SIG = 3,
     IKEV1_AUTH_RSA_ENC = 4,
     IKEV1_AUTH_RSA_ENC_REV = 5,
     IKEV1_AUTH_ECDSA_256 = 9,
     IKEV1_AUTH_ECDSA_384 = 10,
     IKEV1_AUTH_ECDSA_521 = 11,
     /* XAuth Modes */
     IKEV1_AUTH_XAUTH_INIT_PSK = 65001,
     IKEV1_AUTH_XAUTH_RESP_PSK = 65002,
     IKEV1_AUTH_XAUTH_INIT_DSS = 65003,
     IKEV1_AUTH_XAUTH_RESP_DSS = 65004,
     IKEV1_AUTH_XAUTH_INIT_RSA = 65005,
     IKEV1_AUTH_XAUTH_RESP_RSA = 65006,
     IKEV1_AUTH_XAUTH_INIT_RSA_ENC = 65007,
     IKEV1_AUTH_XAUTH_RESP_RSA_ENC = 65008,
     IKEV1_AUTH_XAUTH_INIT_RSA_ENC_REV = 65009,
     IKEV1_AUTH_XAUTH_RESP_RSA_ENC_REV = 65010,
     /* Hybrid Modes */
     IKEV1_AUTH_HYBRID_INIT_RSA = 64221,
     IKEV1_AUTH_HYBRID_RESP_RSA = 64222,
     IKEV1_AUTH_HYBRID_INIT_DSS = 64223,
     IKEV1_AUTH_HYBRID_RESP_DSS = 64224,
 } ikev1_auth_method_t;
enum ikev1_encryption_t
Encryption.
Enumerator
IKEV1_ENCR_DES_CBC
IKEV1_ENCR_IDEA_CBC
IKEV1_ENCR_BLOWFISH_CBC
IKEV1_ENCR_RC5_R16_B64_CBC
IKEV1_ENCR_3DES_CBC
IKEV1_ENCR_CAST_CBC
IKEV1_ENCR_AES_CBC
IKEV1_ENCR_CAMELLIA_CBC
IKEV1_ENCR_SERPENT_CBC
IKEV1_ENCR_TWOFISH_CBC
Definition at line 165 of file proposal_substructure.c.
              {
     IKEV1_ENCR_DES_CBC = 1,
     IKEV1_ENCR_IDEA_CBC = 2,
     IKEV1_ENCR_BLOWFISH_CBC = 3,
     IKEV1_ENCR_RC5_R16_B64_CBC = 4,
     IKEV1_ENCR_3DES_CBC = 5,
     IKEV1_ENCR_CAST_CBC = 6,
     IKEV1_ENCR_AES_CBC = 7,
     IKEV1_ENCR_CAMELLIA_CBC = 8,
     /* FreeS/WAN proprietary */
     IKEV1_ENCR_SERPENT_CBC = 65004,
     IKEV1_ENCR_TWOFISH_CBC = 65005,
 } ikev1_encryption_t;
enum ikev1_esp_encap_t
IKEv1 ESP Encapsulation mode.
Enumerator
IKEV1_ENCAP_TUNNEL
IKEV1_ENCAP_TRANSPORT
IKEV1_ENCAP_UDP_TUNNEL
IKEV1_ENCAP_UDP_TRANSPORT
IKEV1_ENCAP_UDP_TUNNEL_DRAFT_00_03
IKEV1_ENCAP_UDP_TRANSPORT_DRAFT_00_03
Definition at line 269 of file proposal_substructure.c.
              {
   IKEV1_ENCAP_TUNNEL = 1,
   IKEV1_ENCAP_TRANSPORT = 2,
   IKEV1_ENCAP_UDP_TUNNEL = 3,
   IKEV1_ENCAP_UDP_TRANSPORT = 4,
   IKEV1_ENCAP_UDP_TUNNEL_DRAFT_00_03 = 61443,
   IKEV1_ENCAP_UDP_TRANSPORT_DRAFT_00_03 = 61444,
 } ikev1_esp_encap_t;
enum ikev1_esp_transid_t
IKEv1 Transform ID ESP encryption algorithm.
Enumerator
IKEV1_ESP_ENCR_DES_IV64
IKEV1_ESP_ENCR_DES
IKEV1_ESP_ENCR_3DES
IKEV1_ESP_ENCR_RC5
IKEV1_ESP_ENCR_IDEA
IKEV1_ESP_ENCR_CAST
IKEV1_ESP_ENCR_BLOWFISH
IKEV1_ESP_ENCR_3IDEA
IKEV1_ESP_ENCR_DES_IV32
IKEV1_ESP_ENCR_RC4
IKEV1_ESP_ENCR_NULL
IKEV1_ESP_ENCR_AES_CBC
IKEV1_ESP_ENCR_AES_CTR
IKEV1_ESP_ENCR_AES_CCM_8
IKEV1_ESP_ENCR_AES_CCM_12
IKEV1_ESP_ENCR_AES_CCM_16
IKEV1_ESP_ENCR_AES_GCM_8
IKEV1_ESP_ENCR_AES_GCM_12
IKEV1_ESP_ENCR_AES_GCM_16
IKEV1_ESP_ENCR_SEED_CBC
IKEV1_ESP_ENCR_CAMELLIA
IKEV1_ESP_ENCR_NULL_AUTH_AES_GMAC
IKEV1_ESP_ENCR_SERPENT
IKEV1_ESP_ENCR_TWOFISH
Definition at line 201 of file proposal_substructure.c.
              {
     IKEV1_ESP_ENCR_DES_IV64 = 1,
     IKEV1_ESP_ENCR_DES = 2,
     IKEV1_ESP_ENCR_3DES = 3,
     IKEV1_ESP_ENCR_RC5 = 4,
     IKEV1_ESP_ENCR_IDEA = 5,
     IKEV1_ESP_ENCR_CAST = 6,
     IKEV1_ESP_ENCR_BLOWFISH = 7,
     IKEV1_ESP_ENCR_3IDEA = 8,
     IKEV1_ESP_ENCR_DES_IV32 = 9,
     IKEV1_ESP_ENCR_RC4 = 10,
     IKEV1_ESP_ENCR_NULL = 11,
     IKEV1_ESP_ENCR_AES_CBC = 12,
     IKEV1_ESP_ENCR_AES_CTR = 13,
     IKEV1_ESP_ENCR_AES_CCM_8 = 14,
     IKEV1_ESP_ENCR_AES_CCM_12 = 15,
     IKEV1_ESP_ENCR_AES_CCM_16 = 16,
     IKEV1_ESP_ENCR_AES_GCM_8 = 18,
     IKEV1_ESP_ENCR_AES_GCM_12 = 19,
     IKEV1_ESP_ENCR_AES_GCM_16 = 20,
     IKEV1_ESP_ENCR_SEED_CBC = 21,
     IKEV1_ESP_ENCR_CAMELLIA = 22,
     IKEV1_ESP_ENCR_NULL_AUTH_AES_GMAC = 23,
     /* FreeS/WAN proprietary */
     IKEV1_ESP_ENCR_SERPENT = 252,
     IKEV1_ESP_ENCR_TWOFISH = 253,
 } ikev1_esp_transid_t;
enum ikev1_hash_t
IKEv1 hash.
Enumerator
IKEV1_HASH_MD5
IKEV1_HASH_SHA1
IKEV1_HASH_TIGER
IKEV1_HASH_SHA2_256
IKEV1_HASH_SHA2_384
IKEV1_HASH_SHA2_512
Definition at line 182 of file proposal_substructure.c.
              {
     IKEV1_HASH_MD5 = 1,
     IKEV1_HASH_SHA1 = 2,
     IKEV1_HASH_TIGER = 3,
     IKEV1_HASH_SHA2_256 = 4,
     IKEV1_HASH_SHA2_384 = 5,
     IKEV1_HASH_SHA2_512 = 6,
 } ikev1_hash_t;
enum ikev1_ike_transid_t
IKEv1 Transform ID IKE.
Enumerator
IKEV1_TRANSID_KEY_IKE
Definition at line 194 of file proposal_substructure.c.
              {
     IKEV1_TRANSID_KEY_IKE = 1,
 } ikev1_ike_transid_t;
enum ikev1_ipcomp_transform_t
IKEv1 IPComp transform IDs
Enumerator
IKEV1_IPCOMP_OUI
IKEV1_IPCOMP_DEFLATE
IKEV1_IPCOMP_LZS
Definition at line 319 of file proposal_substructure.c.
              {
     IKEV1_IPCOMP_OUI = 1,
     IKEV1_IPCOMP_DEFLATE = 2,
     IKEV1_IPCOMP_LZS = 3,
 } ikev1_ipcomp_transform_t;
enum ikev1_life_type_t
IKEv1 Life duration types.
Enumerator
IKEV1_LIFE_TYPE_SECONDS
IKEV1_LIFE_TYPE_KILOBYTES
Definition at line 281 of file proposal_substructure.c.
              {
     IKEV1_LIFE_TYPE_SECONDS = 1,
     IKEV1_LIFE_TYPE_KILOBYTES = 2,
 } ikev1_life_type_t;
Function Documentation
static void add_to_proposal_v1 (proposal_t * proposal, transform_substructure_t * transform, protocol_id_t proto) static
Add an ESP/AH transform to a proposal for IKEv1
Definition at line 929 of file proposal_substructure.c.
References proposal_t::add_algorithm, transform_substructure_t::create_attribute_enumerator, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, ENCR_AES_CBC, ENCRYPTION_ALGORITHM, enumerator_t::enumerate, EXTENDED_SEQUENCE_NUMBERS, get_alg_from_ikev1_auth(), get_alg_from_ikev1_transid(), transform_attribute_t::get_attribute_type, transform_substructure_t::get_transform_id, transform_attribute_t::get_value, INTEGRITY_ALGORITHM, NO_EXT_SEQ_NUMBERS, PROTO_ESP, TATTR_PH2_AUTH_ALGORITHM, TATTR_PH2_GROUP, TATTR_PH2_KEY_LENGTH, type, and value.
Referenced by METHOD().
 {
     transform_attribute_type_t type;
     transform_attribute_t *tattr;
     enumerator_t *enumerator;
     u_int16_t encr, value, key_length = 0;
     enumerator = transform->create_attribute_enumerator(transform);
     while (enumerator->enumerate(enumerator, &tattr))
     {
         type = tattr->get_attribute_type(tattr);
         value = tattr->get_value(tattr);
         switch (type)
         {
             case TATTR_PH2_KEY_LENGTH:
                 key_length = value;
                 break;
             case TATTR_PH2_AUTH_ALGORITHM:
                 proposal->add_algorithm(proposal, INTEGRITY_ALGORITHM,
                                         get_alg_from_ikev1_auth(value), 0);
                 break;
             case TATTR_PH2_GROUP:
                 proposal->add_algorithm(proposal, DIFFIE_HELLMAN_GROUP,
                         value, 0);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     /* TODO-IKEv1: handle ESN attribute */
     proposal->add_algorithm(proposal, EXTENDED_SEQUENCE_NUMBERS,
                             NO_EXT_SEQ_NUMBERS, 0);
     if (proto == PROTO_ESP)
     {
         encr = get_alg_from_ikev1_transid(ENCRYPTION_ALGORITHM,
                                     transform->get_transform_id(transform));
         if (encr)
         {
             if (encr == ENCR_AES_CBC && !key_length)
             {   /* some implementations don't send a Key Length attribute for
                  * AES-128, early drafts of RFC 3602 allowed that for IKE, some
                  * also seem to do it for ESP */
                 key_length = 128;
             }
             proposal->add_algorithm(proposal, ENCRYPTION_ALGORITHM, encr,
                                     key_length);
         }
     }
 }
static void add_to_proposal_v1_ike (proposal_t * proposal, transform_substructure_t * transform) static
Add an IKE transform to a proposal for IKEv1
Definition at line 877 of file proposal_substructure.c.
References proposal_t::add_algorithm, transform_substructure_t::create_attribute_enumerator, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, ENCR_AES_CBC, ENCR_UNDEFINED, ENCRYPTION_ALGORITHM, enumerator_t::enumerate, get_alg_from_ikev1(), transform_attribute_t::get_attribute_type, transform_attribute_t::get_value, INTEGRITY_ALGORITHM, PSEUDO_RANDOM_FUNCTION, TATTR_PH1_ENCRYPTION_ALGORITHM, TATTR_PH1_GROUP, TATTR_PH1_HASH_ALGORITHM, TATTR_PH1_KEY_LENGTH, type, and value.
Referenced by METHOD().
 {
     transform_attribute_type_t type;
     transform_attribute_t *tattr;
     enumerator_t *enumerator;
     u_int16_t value, key_length = 0;
     u_int16_t encr = ENCR_UNDEFINED;
     enumerator = transform->create_attribute_enumerator(transform);
     while (enumerator->enumerate(enumerator, &tattr))
     {
         type = tattr->get_attribute_type(tattr);
         value = tattr->get_value(tattr);
         switch (type)
         {
             case TATTR_PH1_ENCRYPTION_ALGORITHM:
                 encr = get_alg_from_ikev1(ENCRYPTION_ALGORITHM, value);
                 break;
             case TATTR_PH1_KEY_LENGTH:
                 key_length = value;
                 break;
             case TATTR_PH1_HASH_ALGORITHM:
                 proposal->add_algorithm(proposal, INTEGRITY_ALGORITHM,
                         get_alg_from_ikev1(INTEGRITY_ALGORITHM, value), 0);
                 proposal->add_algorithm(proposal, PSEUDO_RANDOM_FUNCTION,
                         get_alg_from_ikev1(PSEUDO_RANDOM_FUNCTION, value), 0);
                 break;
             case TATTR_PH1_GROUP:
                 proposal->add_algorithm(proposal, DIFFIE_HELLMAN_GROUP,
                         value, 0);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (encr != ENCR_UNDEFINED)
     {
         if (encr == ENCR_AES_CBC && !key_length)
         {   /* some implementations don't send a Key Length attribute for
              * AES-128, early drafts of RFC 3602 allowed that */
             key_length = 128;
         }
         proposal->add_algorithm(proposal, ENCRYPTION_ALGORITHM, encr, key_length);
     }
 }
static void add_to_proposal_v2 (proposal_t * proposal, transform_substructure_t * transform) static
Add a transform to a proposal for IKEv2
Definition at line 552 of file proposal_substructure.c.
References proposal_t::add_algorithm, transform_substructure_t::create_attribute_enumerator, enumerator_t::destroy, enumerator_t::enumerate, transform_attribute_t::get_attribute_type, transform_substructure_t::get_transform_id, transform_substructure_t::get_transform_type_or_number, transform_attribute_t::get_value, and TATTR_IKEV2_KEY_LENGTH.
Referenced by METHOD().
 {
     transform_attribute_t *tattr;
     enumerator_t *enumerator;
     u_int16_t key_length = 0;
     enumerator = transform->create_attribute_enumerator(transform);
     while (enumerator->enumerate(enumerator, &tattr))
     {
         if (tattr->get_attribute_type(tattr) == TATTR_IKEV2_KEY_LENGTH)
         {
             key_length = tattr->get_value(tattr);
             break;
         }
     }
     enumerator->destroy(enumerator);
     proposal->add_algorithm(proposal,
                         transform->get_transform_type_or_number(transform),
                         transform->get_transform_id(transform), key_length);
 }
static void add_transform_substructure (private_proposal_substructure_t * this, transform_substructure_t * transform) static
Add a transform substructure to the proposal
Definition at line 460 of file proposal_substructure.c.
References compute_length(), FALSE, transform_substructure_t::set_is_last_transform, and TRUE.
Referenced by proposal_substructure_create_for_ipcomp_v1(), set_from_proposal_v1(), set_from_proposal_v1_ike(), and set_from_proposal_v2().
 {
     if (this->transforms->get_count(this->transforms) > 0)
     {
         transform_substructure_t *last;
         this->transforms->get_last(this->transforms, (void **)&last);
         last->set_is_last_transform(last, FALSE);
     }
     transform->set_is_last_transform(transform,TRUE);
     this->transforms->insert_last(this->transforms, transform);
     compute_length(this);
 }
static void compute_length (private_proposal_substructure_t * this) static
(re-)compute the length of the payload.
Definition at line 435 of file proposal_substructure.c.
References enumerator_t::destroy, enumerator_t::enumerate, and payload_t::get_length.
Referenced by add_transform_substructure(), METHOD(), proposal_substructure_create(), proposal_substructure_create_for_ipcomp_v1(), and set_data().
 {
     enumerator_t *enumerator;
     payload_t *transform;
     this->transforms_count = 0;
     this->proposal_length = get_header_length(this);
     enumerator = this->transforms->create_enumerator(this->transforms);
     while (enumerator->enumerate(enumerator, &transform))
     {
         this->proposal_length += transform->get_length(transform);
         this->transforms_count++;
     }
     enumerator->destroy(enumerator);
 }
static u_int16_t get_alg_from_ikev1 (transform_type_t type, u_int16_t value) static
Get IKEv2 algorithm from IKEv1 identifier
Definition at line 719 of file proposal_substructure.c.
References AUTH_UNDEFINED, countof, ENCR_UNDEFINED, ENCRYPTION_ALGORITHM, ikev2_from_ikev1(), INTEGRITY_ALGORITHM, PRF_UNDEFINED, and PSEUDO_RANDOM_FUNCTION.
Referenced by add_to_proposal_v1_ike().
 {
     switch (type)
     {
         case ENCRYPTION_ALGORITHM:
             return ikev2_from_ikev1(map_encr, countof(map_encr),
                                     ENCR_UNDEFINED, value);
         case INTEGRITY_ALGORITHM:
             return ikev2_from_ikev1(map_integ, countof(map_integ),
                                     AUTH_UNDEFINED, value);
         case PSEUDO_RANDOM_FUNCTION:
             return ikev2_from_ikev1(map_prf, countof(map_prf),
                                     PRF_UNDEFINED, value);
         default:
             return 0;
     }
 }
static u_int16_t get_alg_from_ikev1_auth (u_int16_t value) static
Get IKEv1 authentication algorithm from IKEv2 identifier
Definition at line 794 of file proposal_substructure.c.
References AUTH_UNDEFINED, countof, and ikev2_from_ikev1().
Referenced by add_to_proposal_v1().
 {
     return ikev2_from_ikev1(map_auth, countof(map_auth), AUTH_UNDEFINED, value);
 }
static u_int16_t get_alg_from_ikev1_transid (transform_type_t type, u_int16_t value) static
Get IKEv2 algorithm from IKEv1 ESP/AH transform ID
Definition at line 758 of file proposal_substructure.c.
References AUTH_UNDEFINED, countof, ENCR_UNDEFINED, ENCRYPTION_ALGORITHM, ikev2_from_ikev1(), and INTEGRITY_ALGORITHM.
Referenced by add_to_proposal_v1().
 {
     switch (type)
     {
         case ENCRYPTION_ALGORITHM:
             return ikev2_from_ikev1(map_esp, countof(map_esp),
                                     ENCR_UNDEFINED, value);
         case INTEGRITY_ALGORITHM:
             return ikev2_from_ikev1(map_ah, countof(map_ah),
                                     AUTH_UNDEFINED, value);
         default:
             return 0;
     }
 }
static u_int64_t get_attr (private_proposal_substructure_t * this, transform_attribute_type_t type) static
Get an attribute from any transform, 0 if not found
Definition at line 1045 of file proposal_substructure.c.
References attributes, transform_substructure_t::create_attribute_enumerator, enumerator_t::destroy, enumerator_t::enumerate, transform_attribute_t::get_attribute_type, transform_attribute_t::get_value, and type.
Referenced by METHOD().
 {
     enumerator_t *transforms, *attributes;
     transform_substructure_t *transform;
     transform_attribute_t *attr;
     transforms = this->transforms->create_enumerator(this->transforms);
     while (transforms->enumerate(transforms, &transform))
     {
         attributes = transform->create_attribute_enumerator(transform);
         while (attributes->enumerate(attributes, &attr))
         {
             if (attr->get_attribute_type(attr) == type)
             {
                 attributes->destroy(attributes);
                 transforms->destroy(transforms);
                 return attr->get_value(attr);
             }
         }
         attributes->destroy(attributes);
     }
     transforms->destroy(transforms);
     return 0;
 }
static u_int16_t get_ikev1_auth (auth_method_t method) static
Get IKEv1 authentication attribute from auth_method_t
Definition at line 810 of file proposal_substructure.c.
References AUTH_DSS, AUTH_ECDSA_256, AUTH_ECDSA_384, AUTH_ECDSA_521, AUTH_HYBRID_INIT_RSA, AUTH_HYBRID_RESP_RSA, AUTH_PSK, AUTH_RSA, AUTH_XAUTH_INIT_PSK, AUTH_XAUTH_INIT_RSA, AUTH_XAUTH_RESP_PSK, AUTH_XAUTH_RESP_RSA, IKEV1_AUTH_DSS_SIG, IKEV1_AUTH_ECDSA_256, IKEV1_AUTH_ECDSA_384, IKEV1_AUTH_ECDSA_521, IKEV1_AUTH_HYBRID_INIT_RSA, IKEV1_AUTH_HYBRID_RESP_RSA, IKEV1_AUTH_PSK, IKEV1_AUTH_RSA_SIG, IKEV1_AUTH_XAUTH_INIT_PSK, IKEV1_AUTH_XAUTH_INIT_RSA, IKEV1_AUTH_XAUTH_RESP_PSK, and IKEV1_AUTH_XAUTH_RESP_RSA.
Referenced by set_from_proposal_v1_ike().
 {
     switch (method)
     {
         case AUTH_RSA:
             return IKEV1_AUTH_RSA_SIG;
         case AUTH_DSS:
             return IKEV1_AUTH_DSS_SIG;
         case AUTH_XAUTH_INIT_PSK:
             return IKEV1_AUTH_XAUTH_INIT_PSK;
         case AUTH_XAUTH_RESP_PSK:
             return IKEV1_AUTH_XAUTH_RESP_PSK;
         case AUTH_XAUTH_INIT_RSA:
             return IKEV1_AUTH_XAUTH_INIT_RSA;
         case AUTH_XAUTH_RESP_RSA:
             return IKEV1_AUTH_XAUTH_RESP_RSA;
         case AUTH_HYBRID_INIT_RSA:
             return IKEV1_AUTH_HYBRID_INIT_RSA;
         case AUTH_HYBRID_RESP_RSA:
             return IKEV1_AUTH_HYBRID_RESP_RSA;
         case AUTH_ECDSA_256:
             return IKEV1_AUTH_ECDSA_256;
         case AUTH_ECDSA_384:
             return IKEV1_AUTH_ECDSA_384;
         case AUTH_ECDSA_521:
             return IKEV1_AUTH_ECDSA_521;
         case AUTH_PSK:
         default:
             return IKEV1_AUTH_PSK;
     }
 }
static u_int16_t get_ikev1_auth_from_alg (u_int16_t value) static
Get IKEv1 authentication algorithm from IKEv2 identifier
Definition at line 802 of file proposal_substructure.c.
References countof, and ikev1_from_ikev2().
Referenced by set_from_proposal_v1().
 {
     return ikev1_from_ikev2(map_auth, countof(map_auth), value);
 }
static u_int16_t get_ikev1_from_alg (transform_type_t type, u_int16_t value) static
Get IKEv1 algorithm from IKEv2 identifier
Definition at line 740 of file proposal_substructure.c.
References countof, ENCRYPTION_ALGORITHM, ikev1_from_ikev2(), INTEGRITY_ALGORITHM, and PSEUDO_RANDOM_FUNCTION.
Referenced by set_from_proposal_v1_ike().
 {
     switch (type)
     {
         case ENCRYPTION_ALGORITHM:
             return ikev1_from_ikev2(map_encr, countof(map_encr), value);
         case INTEGRITY_ALGORITHM:
             return ikev1_from_ikev2(map_integ, countof(map_integ), value);
         case PSEUDO_RANDOM_FUNCTION:
             return ikev1_from_ikev2(map_prf, countof(map_prf), value);
         default:
             return 0;
     }
 }
static u_int16_t get_ikev1_mode (ipsec_mode_t mode, encap_t udp) static
Get IKEv1 encapsulation mode
Definition at line 845 of file proposal_substructure.c.
References ENCAP_UDP, ENCAP_UDP_DRAFT_00_03, IKEV1_ENCAP_TRANSPORT, IKEV1_ENCAP_TUNNEL, IKEV1_ENCAP_UDP_TRANSPORT, IKEV1_ENCAP_UDP_TRANSPORT_DRAFT_00_03, IKEV1_ENCAP_UDP_TUNNEL, IKEV1_ENCAP_UDP_TUNNEL_DRAFT_00_03, MODE_TRANSPORT, and MODE_TUNNEL.
Referenced by proposal_substructure_create_for_ipcomp_v1(), and set_from_proposal_v1().
 {
     switch (mode)
     {
         case MODE_TUNNEL:
             switch (udp)
             {
                 case ENCAP_UDP:
                     return IKEV1_ENCAP_UDP_TUNNEL;
                 case ENCAP_UDP_DRAFT_00_03:
                     return IKEV1_ENCAP_UDP_TUNNEL_DRAFT_00_03;
                 default:
                     return IKEV1_ENCAP_TUNNEL;
             }
         case MODE_TRANSPORT:
             switch (udp)
             {
                 case ENCAP_UDP:
                     return IKEV1_ENCAP_UDP_TRANSPORT;
                 case ENCAP_UDP_DRAFT_00_03:
                     return IKEV1_ENCAP_UDP_TRANSPORT_DRAFT_00_03;
                 default:
                     return IKEV1_ENCAP_TRANSPORT;
             }
         default:
             return IKEV1_ENCAP_TUNNEL;
     }
 }
static u_int16_t get_ikev1_transid_from_alg (transform_type_t type, u_int16_t value) static
Get IKEv1 ESP/AH transform ID from IKEv2 identifier
Definition at line 777 of file proposal_substructure.c.
References countof, ENCRYPTION_ALGORITHM, ikev1_from_ikev2(), and INTEGRITY_ALGORITHM.
Referenced by set_from_proposal_v1().
 {
     switch (type)
     {
         case ENCRYPTION_ALGORITHM:
             return ikev1_from_ikev2(map_esp, countof(map_esp), value);
         case INTEGRITY_ALGORITHM:
             return ikev1_from_ikev2(map_ah, countof(map_ah), value);
         default:
             return 0;
     }
 }
static u_int64_t get_life_duration (private_proposal_substructure_t * this, transform_attribute_type_t type_attr, ikev1_life_type_t type, transform_attribute_type_t dur_attr) static
Look up a lifetime duration of a given kind in all transforms
Definition at line 1074 of file proposal_substructure.c.
References attributes, transform_substructure_t::create_attribute_enumerator, enumerator_t::destroy, enumerator_t::enumerate, transform_attribute_t::get_attribute_type, transform_attribute_t::get_value, and type.
Referenced by METHOD().
 {
     enumerator_t *transforms, *attributes;
     transform_substructure_t *transform;
     transform_attribute_t *attr;
     transforms = this->transforms->create_enumerator(this->transforms);
     while (transforms->enumerate(transforms, &transform))
     {
         attributes = transform->create_attribute_enumerator(transform);
         while (attributes->enumerate(attributes, &attr))
         {
             if (attr->get_attribute_type(attr) == type_attr &&
                 attr->get_value(attr) == type)
             {   /* got type attribute, look for duration following next */
                 while (attributes->enumerate(attributes, &attr))
                 {
                     if (attr->get_attribute_type(attr) == dur_attr)
                     {
                         attributes->destroy(attributes);
                         transforms->destroy(transforms);
                         return attr->get_value(attr);
                     }
                 }
             }
         }
         attributes->destroy(attributes);
     }
     transforms->destroy(transforms);
     return 0;
 }
static u_int16_t ikev1_from_ikev2 (algo_map_t * map, int count, u_int16_t value) static
Map an IKEv2 to an IKEv1 identifier
Definition at line 702 of file proposal_substructure.c.
References count, algo_map_t::ikev1, and ikev2.
Referenced by get_ikev1_auth_from_alg(), get_ikev1_from_alg(), and get_ikev1_transid_from_alg().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         if (map[i].ikev2 == value)
         {
             return map[i].ikev1;
         }
     }
     return 0;
 }
static u_int16_t ikev2_from_ikev1 (algo_map_t * map, int count, u_int16_t def, u_int16_t value) static
Map an IKEv1 to an IKEv2 identifier
Definition at line 684 of file proposal_substructure.c.
References count, and algo_map_t::ikev2.
Referenced by get_alg_from_ikev1(), get_alg_from_ikev1_auth(), and get_alg_from_ikev1_transid().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         if (map[i].ikev1 == value)
         {
             return map[i].ikev2;
         }
     }
     return def;
 }
METHOD (payload_t , verify , status_t , private_proposal_substructure_t * this)
Definition at line 325 of file proposal_substructure.c.
References DBG1, DBG_ENC, enumerator_t::destroy, enumerator_t::enumerate, FAILED, PL_NONE, PLV1_PROPOSAL_SUBSTRUCTURE, PROTO_AH, PROTO_ESP, PROTO_IKE, PROTO_IPCOMP, protocol_id_names, status, SUCCESS, type, and payload_t::verify.
 {
     status_t status = SUCCESS;
     enumerator_t *enumerator;
     payload_t *current;
     if (this->next_payload != PL_NONE && this->next_payload != 2)
     {
         /* must be 0 or 2 */
         DBG1(DBG_ENC, "inconsistent next payload");
         return FAILED;
     }
     if (this->transforms_count != this->transforms->get_count(this->transforms))
     {
         /* must be the same! */
         DBG1(DBG_ENC, "transform count invalid");
         return FAILED;
     }
     switch (this->protocol_id)
     {
         case PROTO_IPCOMP:
             if (this->spi.len != 2 && this->spi.len != 4)
             {
                 DBG1(DBG_ENC, "invalid CPI length in IPCOMP proposal");
                 return FAILED;
             }
             break;
         case PROTO_AH:
         case PROTO_ESP:
             if (this->spi.len != 4)
             {
                 DBG1(DBG_ENC, "invalid SPI length in %N proposal",
                      protocol_id_names, this->protocol_id);
                 return FAILED;
             }
             break;
         case PROTO_IKE:
             if (this->type == PLV1_PROPOSAL_SUBSTRUCTURE)
             {
                 if (this->spi.len <= 16)
                 {   /* according to RFC 2409, section 3.5 anything between
                      * 0 and 16 is fine */
                     break;
                 }
             }
             else if (this->spi.len == 0 || this->spi.len  == 8)
             {
                 break;
             }
             DBG1(DBG_ENC, "invalid SPI length in IKE proposal");
             return FAILED;
         default:
             break;
     }
     enumerator = this->transforms->create_enumerator(this->transforms);
     while (enumerator->enumerate(enumerator, &current))
     {
         status = current->verify(current);
         if (status != SUCCESS)
         {
             DBG1(DBG_ENC, "TRANSFORM_SUBSTRUCTURE verification failed");
             break;
         }
     }
     enumerator->destroy(enumerator);
     /* proposal number is checked in SA payload */
     return status;
 }
METHOD (payload_t , get_encoding_rules , int , private_proposal_substructure_t * this, encoding_rule_t ** rules)
Definition at line 397 of file proposal_substructure.c.
References countof, encodings_v1, encodings_v2, PLV2_PROPOSAL_SUBSTRUCTURE, and type.
 {
     if (this->type == PLV2_PROPOSAL_SUBSTRUCTURE)
     {
         *rules = encodings_v2;
         return countof(encodings_v2);
     }
     *rules = encodings_v1;
     return countof(encodings_v1);
 }
METHOD (payload_t , get_header_length , int , private_proposal_substructure_t * this)
Definition at line 409 of file proposal_substructure.c.
 {
     return 8 + this->spi_size;
 }
METHOD (payload_t , get_type , payload_type_t , private_proposal_substructure_t * this)
Definition at line 415 of file proposal_substructure.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_proposal_substructure_t * this)
Definition at line 421 of file proposal_substructure.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_proposal_substructure_t * this, payload_type_t type)
Definition at line 427 of file proposal_substructure.c.
 {
 }
METHOD (payload_t , get_length , size_t , private_proposal_substructure_t * this)
Definition at line 451 of file proposal_substructure.c.
 {
     return this->proposal_length;
 }
METHOD (proposal_substructure_t , set_is_last_proposal , void , private_proposal_substructure_t * this, bool is_last)
Definition at line 475 of file proposal_substructure.c.
References PROPOSAL_TYPE_VALUE.
 {
     this->next_payload = is_last ? 0 : PROPOSAL_TYPE_VALUE;
 }
METHOD (proposal_substructure_t , set_proposal_number , void , private_proposal_substructure_t * this, u_int8_t proposal_number)
Definition at line 481 of file proposal_substructure.c.
 {
     this->proposal_number = proposal_number;
 }
METHOD (proposal_substructure_t , get_proposal_number , u_int8_t , private_proposal_substructure_t * this)
Definition at line 487 of file proposal_substructure.c.
 {
     return this->proposal_number;
 }
METHOD (proposal_substructure_t , set_protocol_id , void , private_proposal_substructure_t * this, u_int8_t protocol_id)
Definition at line 493 of file proposal_substructure.c.
 {
     this->protocol_id = protocol_id;
 }
METHOD (proposal_substructure_t , get_protocol_id , u_int8_t , private_proposal_substructure_t * this)
Definition at line 499 of file proposal_substructure.c.
 {
     return this->protocol_id;
 }
METHOD (proposal_substructure_t , set_spi , void , private_proposal_substructure_t * this, chunk_t spi)
Definition at line 505 of file proposal_substructure.c.
References chunk_clone, compute_length(), free(), chunk_t::len, and chunk_t::ptr.
 {
     free(this->spi.ptr);
     this->spi = chunk_clone(spi);
     this->spi_size = spi.len;
     compute_length(this);
 }
METHOD (proposal_substructure_t , get_spi , chunk_t , private_proposal_substructure_t * this)
Definition at line 514 of file proposal_substructure.c.
 {
     return this->spi;
 }
METHOD (proposal_substructure_t , get_cpi , bool , private_proposal_substructure_t * this, u_int16_t * cpi)
Definition at line 520 of file proposal_substructure.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, transform_substructure_t::get_transform_id, IKEV1_IPCOMP_DEFLATE, PROTO_IPCOMP, TRUE, and untoh16().
 {
     transform_substructure_t *transform;
     enumerator_t *enumerator;
     if (this->protocol_id != PROTO_IPCOMP)
     {
         return FALSE;
     }
     enumerator = this->transforms->create_enumerator(this->transforms);
     while (enumerator->enumerate(enumerator, &transform))
     {
         if (transform->get_transform_id(transform) == IKEV1_IPCOMP_DEFLATE)
         {
             if (cpi)
             {
                 *cpi = htons(untoh16(this->spi.ptr + this->spi.len - 2));
             }
             enumerator->destroy(enumerator);
             return TRUE;
         }
     }
     enumerator->destroy(enumerator);
     return FALSE;
 }
METHOD (proposal_substructure_t , get_proposals , void , private_proposal_substructure_t * this, linked_list_t * proposals)
Definition at line 982 of file proposal_substructure.c.
References add_to_proposal_v1(), add_to_proposal_v1_ike(), add_to_proposal_v2(), enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, PLV2_PROPOSAL_SUBSTRUCTURE, proposal, proposal_create(), PROTO_AH, PROTO_ESP, PROTO_IKE, proposal_t::set_spi, and type.
 {
     transform_substructure_t *transform;
     enumerator_t *enumerator;
     proposal_t *proposal = NULL;
     u_int64_t spi = 0;
     switch (this->spi.len)
     {
         case 4:
             spi =  *((u_int32_t*)this->spi.ptr);
             break;
         case 8:
             spi = *((u_int64_t*)this->spi.ptr);
             break;
         default:
             break;
     }
     enumerator = this->transforms->create_enumerator(this->transforms);
     while (enumerator->enumerate(enumerator, &transform))
     {
         if (!proposal)
         {
             proposal = proposal_create(this->protocol_id, this->proposal_number);
             proposal->set_spi(proposal, spi);
             proposals->insert_last(proposals, proposal);
         }
         if (this->type == PLV2_PROPOSAL_SUBSTRUCTURE)
         {
             add_to_proposal_v2(proposal, transform);
         }
         else
         {
             switch (this->protocol_id)
             {
                 case PROTO_IKE:
                     add_to_proposal_v1_ike(proposal, transform);
                     break;
                 case PROTO_ESP:
                 case PROTO_AH:
                     add_to_proposal_v1(proposal, transform, this->protocol_id);
                     break;
                 default:
                     break;
             }
             /* create a new proposal for each transform in IKEv1 */
             proposal = NULL;
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (proposal_substructure_t , create_substructure_enumerator , enumerator_t * , private_proposal_substructure_t * this)
Definition at line 1036 of file proposal_substructure.c.
 {
     return this->transforms->create_enumerator(this->transforms);
 }
METHOD (proposal_substructure_t , get_lifetime , u_int32_t , private_proposal_substructure_t * this)
Definition at line 1108 of file proposal_substructure.c.
References get_life_duration(), IKEV1_LIFE_TYPE_SECONDS, PROTO_AH, PROTO_ESP, PROTO_IKE, TATTR_PH1_LIFE_DURATION, TATTR_PH1_LIFE_TYPE, TATTR_PH2_SA_LIFE_DURATION, and TATTR_PH2_SA_LIFE_TYPE.
 {
     u_int32_t duration;
     switch (this->protocol_id)
     {
         case PROTO_IKE:
             return get_life_duration(this, TATTR_PH1_LIFE_TYPE,
                         IKEV1_LIFE_TYPE_SECONDS, TATTR_PH1_LIFE_DURATION);
         case PROTO_ESP:
         case PROTO_AH:
             duration = get_life_duration(this, TATTR_PH2_SA_LIFE_TYPE,
                         IKEV1_LIFE_TYPE_SECONDS, TATTR_PH2_SA_LIFE_DURATION);
             if (!duration)
             {   /* default to 8 hours, RFC 2407 */
                 return 28800;
             }
             return duration;
         default:
             return 0;
     }
 }
METHOD (proposal_substructure_t , get_lifebytes , u_int64_t , private_proposal_substructure_t * this)
Definition at line 1132 of file proposal_substructure.c.
References get_life_duration(), IKEV1_LIFE_TYPE_KILOBYTES, PROTO_AH, PROTO_ESP, PROTO_IKE, TATTR_PH2_SA_LIFE_DURATION, and TATTR_PH2_SA_LIFE_TYPE.
 {
     switch (this->protocol_id)
     {
         case PROTO_ESP:
         case PROTO_AH:
             return 1000 * get_life_duration(this, TATTR_PH2_SA_LIFE_TYPE,
                     IKEV1_LIFE_TYPE_KILOBYTES, TATTR_PH2_SA_LIFE_DURATION);
         case PROTO_IKE:
         default:
             return 0;
     }
 }
METHOD (proposal_substructure_t , get_auth_method , auth_method_t , private_proposal_substructure_t * this)
Definition at line 1147 of file proposal_substructure.c.
References AUTH_DSS, AUTH_ECDSA_256, AUTH_ECDSA_384, AUTH_ECDSA_521, AUTH_HYBRID_INIT_RSA, AUTH_HYBRID_RESP_RSA, AUTH_NONE, AUTH_PSK, AUTH_RSA, AUTH_XAUTH_INIT_PSK, AUTH_XAUTH_INIT_RSA, AUTH_XAUTH_RESP_PSK, AUTH_XAUTH_RESP_RSA, get_attr(), IKEV1_AUTH_DSS_SIG, IKEV1_AUTH_ECDSA_256, IKEV1_AUTH_ECDSA_384, IKEV1_AUTH_ECDSA_521, IKEV1_AUTH_HYBRID_INIT_RSA, IKEV1_AUTH_HYBRID_RESP_RSA, IKEV1_AUTH_PSK, IKEV1_AUTH_RSA_SIG, IKEV1_AUTH_XAUTH_INIT_PSK, IKEV1_AUTH_XAUTH_INIT_RSA, IKEV1_AUTH_XAUTH_RESP_PSK, IKEV1_AUTH_XAUTH_RESP_RSA, and TATTR_PH1_AUTH_METHOD.
 {
     switch (get_attr(this, TATTR_PH1_AUTH_METHOD))
     {
         case IKEV1_AUTH_PSK:
             return AUTH_PSK;
         case IKEV1_AUTH_RSA_SIG:
             return AUTH_RSA;
         case IKEV1_AUTH_DSS_SIG:
             return AUTH_DSS;
         case IKEV1_AUTH_XAUTH_INIT_PSK:
             return AUTH_XAUTH_INIT_PSK;
         case IKEV1_AUTH_XAUTH_RESP_PSK:
             return AUTH_XAUTH_RESP_PSK;
         case IKEV1_AUTH_XAUTH_INIT_RSA:
             return AUTH_XAUTH_INIT_RSA;
         case IKEV1_AUTH_XAUTH_RESP_RSA:
             return AUTH_XAUTH_RESP_RSA;
         case IKEV1_AUTH_HYBRID_INIT_RSA:
             return AUTH_HYBRID_INIT_RSA;
         case IKEV1_AUTH_HYBRID_RESP_RSA:
             return AUTH_HYBRID_RESP_RSA;
         case IKEV1_AUTH_ECDSA_256:
             return AUTH_ECDSA_256;
         case IKEV1_AUTH_ECDSA_384:
             return AUTH_ECDSA_384;
         case IKEV1_AUTH_ECDSA_521:
             return AUTH_ECDSA_521;
         default:
             return AUTH_NONE;
     }
 }
METHOD (proposal_substructure_t , get_encap_mode , ipsec_mode_t , private_proposal_substructure_t * this, bool * udp)
Definition at line 1181 of file proposal_substructure.c.
References FALSE, get_attr(), IKEV1_ENCAP_TRANSPORT, IKEV1_ENCAP_TUNNEL, IKEV1_ENCAP_UDP_TRANSPORT, IKEV1_ENCAP_UDP_TRANSPORT_DRAFT_00_03, IKEV1_ENCAP_UDP_TUNNEL, IKEV1_ENCAP_UDP_TUNNEL_DRAFT_00_03, MODE_TRANSPORT, MODE_TUNNEL, TATTR_PH2_ENCAP_MODE, and TRUE.
 {
     *udp = FALSE;
     switch (get_attr(this, TATTR_PH2_ENCAP_MODE))
     {
         case IKEV1_ENCAP_TRANSPORT:
             return MODE_TRANSPORT;
         case IKEV1_ENCAP_TUNNEL:
             return MODE_TUNNEL;
         case IKEV1_ENCAP_UDP_TRANSPORT:
         case IKEV1_ENCAP_UDP_TRANSPORT_DRAFT_00_03:
             *udp = TRUE;
             return MODE_TRANSPORT;
         case IKEV1_ENCAP_UDP_TUNNEL:
         case IKEV1_ENCAP_UDP_TUNNEL_DRAFT_00_03:
             *udp = TRUE;
             return MODE_TUNNEL;
         default:
             /* default to TUNNEL, RFC 2407 says implementation specific */
             return MODE_TUNNEL;
     }
 }
METHOD2 (payload_t , proposal_substructure_t , destroy , void , private_proposal_substructure_t * this)
Definition at line 1205 of file proposal_substructure.c.
References chunk_free(), destroy(), and free().
 {
     this->transforms->destroy_offset(this->transforms,
                                      offsetof(payload_t, destroy));
     chunk_free(&this->spi);
     free(this);
 }
static void set_data (private_proposal_substructure_t * this, proposal_t * proposal) static
Set SPI and other data from proposal, compute length
Definition at line 1486 of file proposal_substructure.c.
References chunk_clone, chunk_from_thing, compute_length(), proposal_t::get_number, proposal_t::get_protocol, proposal_t::get_spi, PROTO_AH, PROTO_ESP, and PROTO_IKE.
Referenced by eap_payload_create_data(), eap_payload_create_data_own(), proposal_substructure_create_from_proposal_v1(), and proposal_substructure_create_from_proposal_v2().
 {
     u_int64_t spi64;
     u_int32_t spi32;
     /* add SPI, if necessary */
     switch (proposal->get_protocol(proposal))
     {
         case PROTO_AH:
         case PROTO_ESP:
             spi32 = proposal->get_spi(proposal);
             this->spi = chunk_clone(chunk_from_thing(spi32));
             this->spi_size = this->spi.len;
             break;
         case PROTO_IKE:
             spi64 = proposal->get_spi(proposal);
             if (spi64)
             {   /* IKE only uses SPIS when rekeying, but on initial setup */
                 this->spi = chunk_clone(chunk_from_thing(spi64));
                 this->spi_size = this->spi.len;
             }
             break;
         default:
             break;
     }
     this->proposal_number = proposal->get_number(proposal);
     this->protocol_id = proposal->get_protocol(proposal);
     compute_length(this);
 }
static void set_from_proposal_v1 (private_proposal_substructure_t * this, proposal_t * proposal, u_int32_t lifetime, u_int64_t lifebytes, ipsec_mode_t mode, encap_t udp, int number) static
Add an IKEv1 ESP/AH proposal to the substructure
Definition at line 1332 of file proposal_substructure.c.
References transform_substructure_t::add_transform_attribute, add_transform_substructure(), alg, proposal_t::create_enumerator, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, enumerator_t::enumerate, get_ikev1_auth_from_alg(), get_ikev1_mode(), get_ikev1_transid_from_alg(), IKEV1_LIFE_TYPE_KILOBYTES, IKEV1_LIFE_TYPE_SECONDS, INTEGRITY_ALGORITHM, key_size, PLV1_TRANSFORM_ATTRIBUTE, PLV1_TRANSFORM_SUBSTRUCTURE, TATTR_PH2_AUTH_ALGORITHM, TATTR_PH2_ENCAP_MODE, TATTR_PH2_GROUP, TATTR_PH2_KEY_LENGTH, TATTR_PH2_SA_LIFE_DURATION, TATTR_PH2_SA_LIFE_TYPE, transform_attribute_create_value(), and transform_substructure_create_type().
Referenced by proposal_substructure_create_from_proposal_v1(), and proposal_substructure_create_from_proposals_v1().
 {
     transform_substructure_t *transform = NULL;
     u_int16_t alg, transid, key_size;
     enumerator_t *enumerator;
     enumerator = proposal->create_enumerator(proposal, ENCRYPTION_ALGORITHM);
     if (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         transid = get_ikev1_transid_from_alg(ENCRYPTION_ALGORITHM, alg);
         if (transid)
         {
             transform = transform_substructure_create_type(
                                 PLV1_TRANSFORM_SUBSTRUCTURE, number, transid);
             if (key_size)
             {
                 transform->add_transform_attribute(transform,
                     transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                                             TATTR_PH2_KEY_LENGTH, key_size));
             }
         }
     }
     enumerator->destroy(enumerator);
     enumerator = proposal->create_enumerator(proposal, INTEGRITY_ALGORITHM);
     if (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         transid = get_ikev1_transid_from_alg(INTEGRITY_ALGORITHM, alg);
         alg = get_ikev1_auth_from_alg(alg);
         if (transid && alg)
         {
             if (!transform)
             {
                 transform = transform_substructure_create_type(
                                 PLV1_TRANSFORM_SUBSTRUCTURE, number, transid);
             }
             transform->add_transform_attribute(transform,
                 transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                                     TATTR_PH2_AUTH_ALGORITHM, alg));
         }
     }
     enumerator->destroy(enumerator);
     if (!transform)
     {
         return;
     }
     enumerator = proposal->create_enumerator(proposal, DIFFIE_HELLMAN_GROUP);
     if (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                                     TATTR_PH2_GROUP, alg));
     }
     enumerator->destroy(enumerator);
     transform->add_transform_attribute(transform,
         transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_ENCAP_MODE, get_ikev1_mode(mode, udp)));
     if (lifetime)
     {
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_TYPE, IKEV1_LIFE_TYPE_SECONDS));
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_DURATION, lifetime));
     }
     if (lifebytes)
     {
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_TYPE, IKEV1_LIFE_TYPE_KILOBYTES));
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_DURATION, lifebytes / 1000));
     }
     add_transform_substructure(this, transform);
 }
static void set_from_proposal_v1_ike (private_proposal_substructure_t * this, proposal_t * proposal, u_int32_t lifetime, auth_method_t method, int number) static
Add an IKEv1 IKE proposal to the substructure
Definition at line 1261 of file proposal_substructure.c.
References transform_substructure_t::add_transform_attribute, add_transform_substructure(), alg, proposal_t::create_enumerator, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, enumerator_t::enumerate, get_ikev1_auth(), get_ikev1_from_alg(), IKEV1_LIFE_TYPE_SECONDS, IKEV1_TRANSID_KEY_IKE, INTEGRITY_ALGORITHM, key_size, PLV1_TRANSFORM_ATTRIBUTE, PLV1_TRANSFORM_SUBSTRUCTURE, TATTR_PH1_AUTH_METHOD, TATTR_PH1_ENCRYPTION_ALGORITHM, TATTR_PH1_GROUP, TATTR_PH1_HASH_ALGORITHM, TATTR_PH1_KEY_LENGTH, TATTR_PH1_LIFE_DURATION, TATTR_PH1_LIFE_TYPE, transform_attribute_create_value(), and transform_substructure_create_type().
Referenced by proposal_substructure_create_from_proposal_v1(), and proposal_substructure_create_from_proposals_v1().
 {
     transform_substructure_t *transform;
     u_int16_t alg, key_size;
     enumerator_t *enumerator;
     transform = transform_substructure_create_type(PLV1_TRANSFORM_SUBSTRUCTURE,
                                                 number, IKEV1_TRANSID_KEY_IKE);
     enumerator = proposal->create_enumerator(proposal, ENCRYPTION_ALGORITHM);
     while (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         alg = get_ikev1_from_alg(ENCRYPTION_ALGORITHM, alg);
         if (alg)
         {
             transform->add_transform_attribute(transform,
                 transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                                     TATTR_PH1_ENCRYPTION_ALGORITHM, alg));
             if (key_size)
             {
                 transform->add_transform_attribute(transform,
                     transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                                         TATTR_PH1_KEY_LENGTH, key_size));
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     /* encode the integrity algorithm as hash and assume use the same PRF */
     enumerator = proposal->create_enumerator(proposal, INTEGRITY_ALGORITHM);
     while (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         alg = get_ikev1_from_alg(INTEGRITY_ALGORITHM, alg);
         if (alg)
         {
             transform->add_transform_attribute(transform,
                 transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                                     TATTR_PH1_HASH_ALGORITHM, alg));
             break;
         }
     }
     enumerator->destroy(enumerator);
     enumerator = proposal->create_enumerator(proposal, DIFFIE_HELLMAN_GROUP);
     if (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                                 TATTR_PH1_GROUP, alg));
     }
     enumerator->destroy(enumerator);
     transform->add_transform_attribute(transform,
         transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH1_AUTH_METHOD, get_ikev1_auth(method)));
     transform->add_transform_attribute(transform,
         transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH1_LIFE_TYPE, IKEV1_LIFE_TYPE_SECONDS));
     transform->add_transform_attribute(transform,
         transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH1_LIFE_DURATION, lifetime));
     add_transform_substructure(this, transform);
 }
static void set_from_proposal_v2 (private_proposal_substructure_t * this, proposal_t * proposal) static
Add an IKEv2 proposal to the substructure
Definition at line 1419 of file proposal_substructure.c.
References transform_substructure_t::add_transform_attribute, add_transform_substructure(), alg, proposal_t::create_enumerator, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, enumerator_t::enumerate, EXTENDED_SEQUENCE_NUMBERS, INTEGRITY_ALGORITHM, key_size, PLV2_TRANSFORM_ATTRIBUTE, PLV2_TRANSFORM_SUBSTRUCTURE, PSEUDO_RANDOM_FUNCTION, TATTR_IKEV2_KEY_LENGTH, transform_attribute_create_value(), and transform_substructure_create_type().
Referenced by proposal_substructure_create_from_proposal_v2().
 {
     transform_substructure_t *transform;
     u_int16_t alg, key_size;
     enumerator_t *enumerator;
     /* encryption algorithm is only available in ESP */
     enumerator = proposal->create_enumerator(proposal, ENCRYPTION_ALGORITHM);
     while (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         transform = transform_substructure_create_type(PLV2_TRANSFORM_SUBSTRUCTURE,
                                                 ENCRYPTION_ALGORITHM, alg);
         if (key_size)
         {
             transform->add_transform_attribute(transform,
                 transform_attribute_create_value(PLV2_TRANSFORM_ATTRIBUTE,
                                             TATTR_IKEV2_KEY_LENGTH, key_size));
         }
         add_transform_substructure(this, transform);
     }
     enumerator->destroy(enumerator);
     /* integrity algorithms */
     enumerator = proposal->create_enumerator(proposal, INTEGRITY_ALGORITHM);
     while (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         transform = transform_substructure_create_type(PLV2_TRANSFORM_SUBSTRUCTURE,
                                                 INTEGRITY_ALGORITHM, alg);
         add_transform_substructure(this, transform);
     }
     enumerator->destroy(enumerator);
     /* prf algorithms */
     enumerator = proposal->create_enumerator(proposal, PSEUDO_RANDOM_FUNCTION);
     while (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         transform = transform_substructure_create_type(PLV2_TRANSFORM_SUBSTRUCTURE,
                                                 PSEUDO_RANDOM_FUNCTION, alg);
         add_transform_substructure(this, transform);
     }
     enumerator->destroy(enumerator);
     /* dh groups */
     enumerator = proposal->create_enumerator(proposal, DIFFIE_HELLMAN_GROUP);
     while (enumerator->enumerate(enumerator, &alg, NULL))
     {
         transform = transform_substructure_create_type(PLV2_TRANSFORM_SUBSTRUCTURE,
                                                 DIFFIE_HELLMAN_GROUP, alg);
         add_transform_substructure(this, transform);
     }
     enumerator->destroy(enumerator);
     /* extended sequence numbers */
     enumerator = proposal->create_enumerator(proposal, EXTENDED_SEQUENCE_NUMBERS);
     while (enumerator->enumerate(enumerator, &alg, NULL))
     {
         transform = transform_substructure_create_type(PLV2_TRANSFORM_SUBSTRUCTURE,
                                                 EXTENDED_SEQUENCE_NUMBERS, alg);
         add_transform_substructure(this, transform);
     }
     enumerator->destroy(enumerator);
 }
Variable Documentation
encoding_rule_t encodings_v1[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_proposal_substructure_t, next_payload)     },
    { RESERVED_BYTE,    offsetof(private_proposal_substructure_t, reserved)         },
    { PAYLOAD_LENGTH,   offsetof(private_proposal_substructure_t, proposal_length)  },
    { U_INT_8,          offsetof(private_proposal_substructure_t, proposal_number)  },
    { U_INT_8,          offsetof(private_proposal_substructure_t, protocol_id)      },
    { SPI_SIZE,         offsetof(private_proposal_substructure_t, spi_size)         },
    { U_INT_8,          offsetof(private_proposal_substructure_t, transforms_count) },
    { SPI,              offsetof(private_proposal_substructure_t, spi)              },
    { PAYLOAD_LIST + PLV1_TRANSFORM_SUBSTRUCTURE,
                        offsetof(private_proposal_substructure_t, transforms)       },
}
Encoding rules for a IKEv1 Proposal substructure.
Definition at line 99 of file proposal_substructure.c.
Referenced by METHOD().
encoding_rule_t encodings_v2[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_proposal_substructure_t, next_payload)     },
    { RESERVED_BYTE,    offsetof(private_proposal_substructure_t, reserved)         },
    { PAYLOAD_LENGTH,   offsetof(private_proposal_substructure_t, proposal_length)  },
    { U_INT_8,          offsetof(private_proposal_substructure_t, proposal_number)  },
    { U_INT_8,          offsetof(private_proposal_substructure_t, protocol_id)      },
    { SPI_SIZE,         offsetof(private_proposal_substructure_t, spi_size)         },
    { U_INT_8,          offsetof(private_proposal_substructure_t, transforms_count) },
    { SPI,              offsetof(private_proposal_substructure_t, spi)              },
    { PAYLOAD_LIST + PLV2_TRANSFORM_SUBSTRUCTURE,
                        offsetof(private_proposal_substructure_t, transforms)       },
}
Encoding rules for a IKEv2 Proposal substructure.
Definition at line 124 of file proposal_substructure.c.
Referenced by METHOD().
algo_map_t map_ah[] static
Initial value:
= {
    { IKEV1_AH_HMAC_MD5,        AUTH_HMAC_MD5_96 },
    { IKEV1_AH_HMAC_SHA,        AUTH_HMAC_SHA1_96 },
    { IKEV1_AH_DES_MAC,         AUTH_DES_MAC },
    { IKEV1_AH_HMAC_SHA2_256,   AUTH_HMAC_SHA2_256_128 },
    { IKEV1_AH_HMAC_SHA2_384,   AUTH_HMAC_SHA2_384_192 },
    { IKEV1_AH_HMAC_SHA2_512,   AUTH_HMAC_SHA2_512_256 },
    { IKEV1_AH_AES_XCBC_MAC,    AUTH_AES_XCBC_96 },
    { IKEV1_AH_AES_128_GMAC,    AUTH_AES_128_GMAC },
    { IKEV1_AH_AES_192_GMAC,    AUTH_AES_192_GMAC },
    { IKEV1_AH_AES_256_GMAC,    AUTH_AES_256_GMAC },
}
AH authentication algorithm mapping
Definition at line 651 of file proposal_substructure.c.
algo_map_t map_auth[] static
Initial value:
= {
    { IKEV1_AUTH_HMAC_MD5,          AUTH_HMAC_MD5_96 },
    { IKEV1_AUTH_HMAC_SHA,          AUTH_HMAC_SHA1_96 },
    { IKEV1_AUTH_DES_MAC,           AUTH_DES_MAC },
    { IKEV1_AUTH_KPDK,              AUTH_KPDK_MD5 },
    { IKEV1_AUTH_HMAC_SHA2_256,     AUTH_HMAC_SHA2_256_128 },
    { IKEV1_AUTH_HMAC_SHA2_384,     AUTH_HMAC_SHA2_384_192 },
    { IKEV1_AUTH_HMAC_SHA2_512,     AUTH_HMAC_SHA2_512_256 },
    { IKEV1_AUTH_AES_XCBC_MAC,      AUTH_AES_XCBC_96 },
    { IKEV1_AUTH_AES_128_GMAC,      AUTH_AES_128_GMAC },
    { IKEV1_AUTH_AES_192_GMAC,      AUTH_AES_192_GMAC },
    { IKEV1_AUTH_AES_256_GMAC,      AUTH_AES_256_GMAC },
}
ESP/AH authentication algorithm mapping
Definition at line 667 of file proposal_substructure.c.
algo_map_t map_encr[] static
Initial value:
= {
    { IKEV1_ENCR_DES_CBC,       ENCR_DES },
    { IKEV1_ENCR_IDEA_CBC,      ENCR_IDEA },
    { IKEV1_ENCR_BLOWFISH_CBC,  ENCR_BLOWFISH },
    { IKEV1_ENCR_3DES_CBC,      ENCR_3DES },
    { IKEV1_ENCR_CAST_CBC,      ENCR_CAST },
    { IKEV1_ENCR_AES_CBC,       ENCR_AES_CBC },
    { IKEV1_ENCR_CAMELLIA_CBC,  ENCR_CAMELLIA_CBC },
    { IKEV1_ENCR_SERPENT_CBC,   ENCR_SERPENT_CBC },
    { IKEV1_ENCR_TWOFISH_CBC,   ENCR_TWOFISH_CBC },
}
Encryption algorithm mapping
Definition at line 586 of file proposal_substructure.c.
algo_map_t map_esp[] static
Initial value:
= {
    { IKEV1_ESP_ENCR_DES_IV64,              ENCR_DES_IV64 },
    { IKEV1_ESP_ENCR_DES,                   ENCR_DES },
    { IKEV1_ESP_ENCR_3DES,                  ENCR_3DES },
    { IKEV1_ESP_ENCR_RC5,                   ENCR_RC5 },
    { IKEV1_ESP_ENCR_IDEA,                  ENCR_IDEA },
    { IKEV1_ESP_ENCR_CAST,                  ENCR_CAST },
    { IKEV1_ESP_ENCR_BLOWFISH,              ENCR_BLOWFISH },
    { IKEV1_ESP_ENCR_3IDEA,                 ENCR_3IDEA },
    { IKEV1_ESP_ENCR_DES_IV32,              ENCR_DES_IV32 },
    { IKEV1_ESP_ENCR_NULL,                  ENCR_NULL },
    { IKEV1_ESP_ENCR_AES_CBC,               ENCR_AES_CBC },
    { IKEV1_ESP_ENCR_AES_CTR,               ENCR_AES_CTR },
    { IKEV1_ESP_ENCR_AES_CCM_8,             ENCR_AES_CCM_ICV8 },
    { IKEV1_ESP_ENCR_AES_CCM_12,            ENCR_AES_CCM_ICV12 },
    { IKEV1_ESP_ENCR_AES_CCM_16,            ENCR_AES_CCM_ICV16 },
    { IKEV1_ESP_ENCR_AES_GCM_8,             ENCR_AES_GCM_ICV8 },
    { IKEV1_ESP_ENCR_AES_GCM_12,            ENCR_AES_GCM_ICV12 },
    { IKEV1_ESP_ENCR_AES_GCM_16,            ENCR_AES_GCM_ICV16 },
    { IKEV1_ESP_ENCR_CAMELLIA,              ENCR_CAMELLIA_CBC },
    { IKEV1_ESP_ENCR_NULL_AUTH_AES_GMAC,    ENCR_NULL_AUTH_AES_GMAC },
    { IKEV1_ESP_ENCR_SERPENT,               ENCR_SERPENT_CBC },
    { IKEV1_ESP_ENCR_TWOFISH,               ENCR_TWOFISH_CBC },
}
ESP encryption algorithm mapping
Definition at line 623 of file proposal_substructure.c.
algo_map_t map_integ[] static
Initial value:
= {
    { IKEV1_HASH_MD5,           AUTH_HMAC_MD5_96 },
    { IKEV1_HASH_SHA1,          AUTH_HMAC_SHA1_96 },
    { IKEV1_HASH_SHA2_256,      AUTH_HMAC_SHA2_256_128 },
    { IKEV1_HASH_SHA2_384,      AUTH_HMAC_SHA2_384_192 },
    { IKEV1_HASH_SHA2_512,      AUTH_HMAC_SHA2_512_256 },
}
Integrity algorithm mapping
Definition at line 601 of file proposal_substructure.c.
algo_map_t map_prf[] static
Initial value:
= {
    { IKEV1_HASH_MD5,           PRF_HMAC_MD5 },
    { IKEV1_HASH_SHA1,          PRF_HMAC_SHA1 },
    { IKEV1_HASH_SHA2_256,      PRF_HMAC_SHA2_256 },
    { IKEV1_HASH_SHA2_384,      PRF_HMAC_SHA2_384 },
    { IKEV1_HASH_SHA2_512,      PRF_HMAC_SHA2_512 },
}
PRF algorithm mapping
Definition at line 612 of file proposal_substructure.c.