strongSwan: imc_test.c File Reference
imc_test.c File Reference
#include "imc_test_state.h"
#include <imc/imc_agent.h>
#include <imc/imc_msg.h>
#include <ietf/ietf_attr.h>
#include <ita/ita_attr.h>
#include <ita/ita_attr_command.h>
#include <ita/ita_attr_dummy.h>
#include <tncif_pa_subtypes.h>
#include <pen/pen.h>
#include <utils/debug.h>
Functions
TNC_Result TNC_IMC_Initialize (TNC_IMCID imc_id, TNC_Version min_version, TNC_Version max_version, TNC_Version *actual_version)
TNC_Result TNC_IMC_NotifyConnectionChange (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_ConnectionState new_state)
static void create_message (imc_state_t *state, imc_msg_t *out_msg)
TNC_Result TNC_IMC_BeginHandshake (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
static TNC_Result receive_message (imc_state_t *state, imc_msg_t *in_msg)
TNC_Result TNC_IMC_ReceiveMessage (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
TNC_Result TNC_IMC_ReceiveMessageLong (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
TNC_Result TNC_IMC_BatchEnding (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
TNC_Result TNC_IMC_Terminate (TNC_IMCID imc_id)
TNC_Result TNC_IMC_ProvideBindFunction (TNC_IMCID imc_id, TNC_TNCC_BindFunctionPointer bind_function)
Variables
static const char imc_name [] = "Test"
static pen_type_t msg_types []
static imc_agent_t * imc_test
Function Documentation
static void create_message (imc_state_t * state, imc_msg_t * out_msg) static
Definition at line 184 of file imc_test.c.
References imc_msg_t::add_attribute, imc_test_state_t::get_command, imc_test_state_t::get_dummy_size, ita_attr_command_create(), ita_attr_dummy_create(), pa_tnc_attr_t::set_noskip_flag, and TRUE.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     imc_test_state_t *test_state;
     pa_tnc_attr_t *attr;
     test_state = (imc_test_state_t*)state;
     if (test_state->get_dummy_size(test_state))
     {
         attr = ita_attr_dummy_create(test_state->get_dummy_size(test_state));
         attr->set_noskip_flag(attr, TRUE);
         out_msg->add_attribute(out_msg, attr);
     }
     attr = ita_attr_command_create(test_state->get_command(test_state));
     attr->set_noskip_flag(attr, TRUE);
     out_msg->add_attribute(out_msg, attr);
 }
static TNC_Result receive_message (imc_state_t * state, imc_msg_t * in_msg) static
Definition at line 263 of file imc_test.c.
References imc_msg_t::create_attribute_enumerator, create_message(), DBG1, DBG_IMC, enumerator_t::destroy, imc_msg_t::destroy, enumerator_t::enumerate, FALSE, ita_attr_command_t::get_command, imc_msg_t::get_dst_id, imc_state_t::get_result, ita_attr_dummy_t::get_size, pa_tnc_attr_t::get_type, imc_msg_create_as_reply(), ITA_ATTR_COMMAND, ITA_ATTR_DUMMY, PEN_ITA, imc_msg_t::receive, result, imc_msg_t::send, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, TRUE, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by TNC_IMC_ReceiveMessage(), and TNC_IMC_ReceiveMessageLong().
 {
     imc_msg_t *out_msg;
     enumerator_t *enumerator;
     pa_tnc_attr_t *attr;
     pen_type_t attr_type;
     TNC_Result result = TNC_RESULT_SUCCESS;
     bool fatal_error = FALSE;
     /* generate an outgoing PA-TNC message - we might need it */
     out_msg = imc_msg_create_as_reply(in_msg);
     /* parse received PA-TNC message and handle local and remote errors */
     result = in_msg->receive(in_msg, out_msg, &fatal_error);
     if (result != TNC_RESULT_SUCCESS)
     {
         out_msg->destroy(out_msg);
         return result;
     }
     /* analyze PA-TNC attributes */
     enumerator = in_msg->create_attribute_enumerator(in_msg);
     while (enumerator->enumerate(enumerator, &attr))
     {
         attr_type = attr->get_type(attr);
         if (attr_type.vendor_id != PEN_ITA)
         {
             continue;
         }
         if (attr_type.type == ITA_ATTR_COMMAND)
         {
             ita_attr_command_t *ita_attr;
             ita_attr = (ita_attr_command_t*)attr;
             DBG1(DBG_IMC, "received command '%s'",
                  ita_attr->get_command(ita_attr));
         }
         else if (attr_type.type == ITA_ATTR_DUMMY)
         {
             ita_attr_dummy_t *ita_attr;
             ita_attr = (ita_attr_dummy_t*)attr;
             DBG1(DBG_IMC, "received dummy attribute value (%d bytes)",
                  ita_attr->get_size(ita_attr));
         }
     }
     enumerator->destroy(enumerator);
     if (fatal_error)
     {
         result = TNC_RESULT_FATAL;
     }
     else
     {
         /* if no assessment result is known then repeat the measurement */
         if (!state->get_result(state, in_msg->get_dst_id(in_msg), NULL))
         {
             create_message(state, out_msg);
         }
         result = out_msg->send(out_msg, TRUE);
     }
     out_msg->destroy(out_msg);
     return result;
 }
Variable Documentation
const char imc_name[] = "Test" static
Definition at line 32 of file imc_test.c.
Referenced by TNC_IMC_BatchEnding(), TNC_IMC_BeginHandshake(), TNC_IMC_Initialize(), TNC_IMC_NotifyConnectionChange(), TNC_IMC_ProvideBindFunction(), TNC_IMC_ReceiveMessage(), TNC_IMC_ReceiveMessageLong(), and TNC_IMC_Terminate().
imc_agent_t* imc_test static
Definition at line 38 of file imc_test.c.
pen_type_t msg_types[] static
Initial value:
= {
    { PEN_ITA, PA_SUBTYPE_ITA_TEST }
}
Definition at line 34 of file imc_test.c.