strongSwan: tls_socket.c File Reference
tls_socket.c File Reference
#include "tls_socket.h"
#include <unistd.h>
#include <errno.h>
#include <utils/debug.h>
#include <threading/thread.h>
Classes
struct private_tls_application_t
struct private_tls_socket_t
Macros
#define PLAIN_BUF_SIZE TLS_MAX_FRAGMENT_LEN
#define CRYPTO_BUF_SIZE TLS_MAX_FRAGMENT_LEN + 2048
Typedefs
typedef struct private_tls_socket_t private_tls_socket_t
typedef struct
private_tls_application_t private_tls_application_t
Functions
METHOD (tls_application_t, process, status_t, private_tls_application_t *this, bio_reader_t *reader)
METHOD (tls_application_t, build, status_t, private_tls_application_t *this, bio_writer_t *writer)
static bool exchange (private_tls_socket_t *this, bool wr, bool block)
METHOD (tls_socket_t, read_, ssize_t, private_tls_socket_t *this, void *buf, size_t len, bool block)
METHOD (tls_socket_t, write_, ssize_t, private_tls_socket_t *this, void *buf, size_t len)
METHOD (tls_socket_t, splice, bool, private_tls_socket_t *this, int rfd, int wfd)
METHOD (tls_socket_t, get_fd, int, private_tls_socket_t *this)
METHOD (tls_socket_t, get_server_id, identification_t *, private_tls_socket_t *this)
METHOD (tls_socket_t, get_peer_id, identification_t *, private_tls_socket_t *this)
METHOD (tls_socket_t, destroy, void, private_tls_socket_t *this)
tls_socket_t * tls_socket_create (bool is_server, identification_t *server, identification_t *peer, int fd, tls_cache_t *cache, tls_version_t max_version, bool nullok)
Macro Definition Documentation
#define CRYPTO_BUF_SIZE TLS_MAX_FRAGMENT_LEN + 2048
Buffer size for encrypted side I/O
Definition at line 32 of file tls_socket.c.
Referenced by exchange().
#define PLAIN_BUF_SIZE TLS_MAX_FRAGMENT_LEN
Buffer size for plain side I/O
Definition at line 27 of file tls_socket.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tls_application_t private_tls_application_t
Definition at line 35 of file tls_socket.c.
typedef struct private_tls_socket_t private_tls_socket_t
Definition at line 34 of file tls_socket.c.
Function Documentation
static bool exchange (private_tls_socket_t * this, bool wr, bool block) static
TLS data exchange loop
Definition at line 156 of file tls_socket.c.
References ALREADY_DONE, CRYPTO_BUF_SIZE, DBG1, DBG_TLS, EWOULDBLOCK, FALSE, flags, in, INVALID_STATE, len, MSG_DONTWAIT, NEED_MORE, out, recv, strerror, SUCCESS, tls, TRUE, and write.
Referenced by METHOD().
 {
     char buf[CRYPTO_BUF_SIZE], *pos;
     ssize_t in, out;
     size_t len;
     int round = 0, flags;
     for (round = 0; TRUE; round++)
     {
         while (TRUE)
         {
             len = sizeof(buf);
             switch (this->tls->build(this->tls, buf, &len, NULL))
             {
                 case NEED_MORE:
                 case ALREADY_DONE:
                     pos = buf;
                     while (len)
                     {
                         out = write(this->fd, pos, len);
                         if (out == -1)
{
                             DBG1(DBG_TLS, "TLS crypto write error: %s",
                                  strerror(errno));
                             return FALSE;
                         }
                         len -= out;
                         pos += out;
                     }
                     continue;
                 case INVALID_STATE:
                     break;
                 case SUCCESS:
                     return TRUE;
                 default:
                     return FALSE;
             }
             break;
         }
         if (wr)
         {
             if (this->app.out_done == this->app.out.len)
             {   /* all data written */
                 return TRUE;
             }
         }
         else
         {
             if (this->app.in_done == this->app.in.len)
             {   /* buffer fully received */
                 return TRUE;
             }
         }
         flags = 0;
         if (this->app.out_done == this->app.out.len)
         {
             if (!block || this->app.in_done)
             {
                 flags |= MSG_DONTWAIT;
             }
         }
         in = recv(this->fd, buf, sizeof(buf), flags);
         if (in < 0)
         {
             if (errno == EAGAIN || errno == EWOULDBLOCK)
             {
                 if (this->app.in_done == 0)
                 {
                     /* reading, nothing got yet, and call would block */
                     errno = EWOULDBLOCK;
                     this->app.in_done = -1;
                 }
                 return TRUE;
             }
             return FALSE;
         }
         if (in == 0)
         {   /* EOF */
             return TRUE;
         }
         switch (this->tls->process(this->tls, buf, in))
         {
             case NEED_MORE:
                 break;
             case SUCCESS:
                 return TRUE;
             default:
                 return FALSE;
         }
     }
 }
METHOD (tls_application_t , process , status_t , private_tls_application_t * this, bio_reader_t * reader)
Definition at line 106 of file tls_socket.c.
References cache(), chunk_cat, close, data, FAILED, in, chunk_t::len, len, memcpy, min, NEED_MORE, chunk_t::ptr, bio_reader_t::read_data, bio_reader_t::remaining, and SUCCESS.
 {
     chunk_t data;
     size_t len;
     if (this->close)
     {
         return SUCCESS;
     }
     len = min(reader->remaining(reader), this->in.len - this->in_done);
     if (len)
     {   /* copy to read buffer as much as fits in */
         if (!reader->read_data(reader, len, &data))
         {
             return FAILED;
         }
         memcpy(this->in.ptr + this->in_done, data.ptr, data.len);
         this->in_done += data.len;
     }
     else
     {   /* read buffer is full, cache for next read */
         if (!reader->read_data(reader, reader->remaining(reader), &data))
         {
             return FAILED;
         }
         this->cache = chunk_cat("mc", this->cache, data);
     }
     return NEED_MORE;
 }
METHOD (tls_application_t , build , status_t , private_tls_application_t * this, bio_writer_t * writer)
Definition at line 137 of file tls_socket.c.
References close, INVALID_STATE, NEED_MORE, out, SUCCESS, and bio_writer_t::write_data.
 {
     if (this->close)
     {
         return SUCCESS;
     }
     if (this->out.len > this->out_done)
     {
         writer->write_data(writer, this->out);
         this->out_done = this->out.len;
         return NEED_MORE;
     }
     return INVALID_STATE;
 }
METHOD (tls_socket_t , read_ , ssize_t , private_tls_socket_t * this, void * buf, size_t len, bool block)
Definition at line 249 of file tls_socket.c.
References cache(), chunk_free(), exchange(), FALSE, len, memcpy, and min.
 {
     if (this->app.cache.len)
     {
         size_t cache;
         cache = min(len, this->app.cache.len - this->app.cache_done);
         memcpy(buf, this->app.cache.ptr + this->app.cache_done, cache);
         this->app.cache_done += cache;
         if (this->app.cache_done == this->app.cache.len)
         {
             chunk_free(&this->app.cache);
             this->app.cache_done = 0;
         }
         return cache;
     }
     this->app.in.ptr = buf;
     this->app.in.len = len;
     this->app.in_done = 0;
     if (exchange(this, FALSE, block))
     {
         return this->app.in_done;
     }
     return -1;
 }
METHOD (tls_socket_t , write_ , ssize_t , private_tls_socket_t * this, void * buf, size_t len)
Definition at line 277 of file tls_socket.c.
References exchange(), FALSE, len, and TRUE.
 {
     this->app.out.ptr = buf;
     this->app.out.len = len;
     this->app.out_done = 0;
     if (exchange(this, TRUE, FALSE))
     {
         return this->app.out_done;
     }
     return -1;
 }
METHOD (tls_socket_t , splice , bool , private_tls_socket_t * this, int rfd, int wfd)
Definition at line 290 of file tls_socket.c.
References countof, DBG1, DBG_TLS, EWOULDBLOCK, FALSE, pollfd::fd, in, out, PLAIN_BUF_SIZE, poll, POLLHUP, POLLIN, POLLNVAL, read, pollfd::revents, strerror, thread_cancelability(), TRUE, and write.
 {
     char buf[PLAIN_BUF_SIZE], *pos;
     ssize_t in, out;
     bool old, plain_eof = FALSE, crypto_eof = FALSE;
     struct pollfd pfd[] = {
         { .fd = this->fd,   .events = POLLIN, },
         { .fd = rfd,        .events = POLLIN, },
     };
     while (!plain_eof && !crypto_eof)
     {
         old = thread_cancelability(TRUE);
         in = poll(pfd, countof(pfd), -1);
         thread_cancelability(old);
         if (in == -1)
         {
             DBG1(DBG_TLS, "TLS select error: %s", strerror(errno));
             return FALSE;
         }
         while (!plain_eof && pfd[0].revents & (POLLIN | POLLHUP | POLLNVAL))
         {
             in = read_(this, buf, sizeof(buf), FALSE);
             switch (in)
             {
                 case 0:
                     plain_eof = TRUE;
                     break;
                 case -1:
                     if (errno != EWOULDBLOCK)
                     {
                         DBG1(DBG_TLS, "TLS read error: %s", strerror(errno));
                         return FALSE;
                     }
                     break;
                 default:
                     pos = buf;
                     while (in)
                     {
                         out = write(wfd, pos, in);
                         if (out == -1)
{
                             DBG1(DBG_TLS, "TLS plain write error: %s",
                                  strerror(errno));
                             return FALSE;
                         }
                         in -= out;
                         pos += out;
                     }
                     continue;
             }
             break;
         }
         if (!crypto_eof && pfd[1].revents & (POLLIN | POLLHUP | POLLNVAL))
         {
             in = read(rfd, buf, sizeof(buf));
             switch (in)
             {
                 case 0:
                     crypto_eof = TRUE;
                     break;
                 case -1:
                     DBG1(DBG_TLS, "TLS plain read error: %s", strerror(errno));
                     return FALSE;
                 default:
                     pos = buf;
                     while (in)
                     {
                         out = write_(this, pos, in);
                         if (out == -1)
{
                             DBG1(DBG_TLS, "TLS write error");
                             return FALSE;
                         }
                         in -= out;
                         pos += out;
                     }
                     break;
             }
         }
     }
     return TRUE;
 }
METHOD (tls_socket_t , get_fd , int , private_tls_socket_t * this)
Definition at line 375 of file tls_socket.c.
References pollfd::fd.
 {
     return this->fd;
 }
METHOD (tls_socket_t , get_server_id , identification_t * , private_tls_socket_t * this)
Definition at line 381 of file tls_socket.c.
References tls.
 {
     return this->tls->get_server_id(this->tls);
 }
METHOD (tls_socket_t , get_peer_id , identification_t * , private_tls_socket_t * this)
Definition at line 387 of file tls_socket.c.
References tls.
 {
     return this->tls->get_peer_id(this->tls);
 }
METHOD (tls_socket_t , destroy , void , private_tls_socket_t * this)
Definition at line 393 of file tls_socket.c.
References thread_value_t::destroy, free(), tls, and TRUE.
 {
     /* send a TLS close notify if not done yet */
     this->app.close = TRUE;
     write_(this, NULL, 0);
     free(this->app.cache.ptr);
     this->tls->destroy(this->tls);
     free(this);
 }