strongSwan: cmac
cmac
cmac
Functions
prf_t * cmac_prf_create (pseudo_random_function_t algo)
signer_t * cmac_signer_create (integrity_algorithm_t algo)
Detailed Description
Cipher-based Message Authentication Code (CMAC).
This class implements the message authentication algorithm described in RFC 4493.
Function Documentation
prf_t* cmac_prf_create (pseudo_random_function_t algo)
Creates a new prf_t object based on a CMAC.
Parameters
algo algorithm to implement
Returns
prf_t object, NULL if not supported
Definition at line 356 of file cmac.c.
References cmac_create(), ENCR_AES_CBC, mac_prf_create(), and PRF_AES128_CMAC.
Referenced by METHOD().
 {
     mac_t *cmac;
     switch (algo)
     {
         case PRF_AES128_CMAC:
             cmac = cmac_create(ENCR_AES_CBC, 16);
             break;
         default:
             return NULL;
     }
     if (cmac)
     {
         return mac_prf_create(cmac);
     }
     return NULL;
 }
signer_t* cmac_signer_create (integrity_algorithm_t algo)
Creates a new signer_t object based on a CMAC.
Parameters
algo algorithm to implement
Returns
signer_t, NULL if not supported
Definition at line 378 of file cmac.c.
References AUTH_AES_CMAC_96, cmac_create(), ENCR_AES_CBC, and mac_signer_create().
Referenced by METHOD().
 {
     size_t truncation;
     mac_t *cmac;
     switch (algo)
     {
         case AUTH_AES_CMAC_96:
             cmac = cmac_create(ENCR_AES_CBC, 16);
             truncation = 12;
             break;
         default:
             return NULL;
     }
     if (cmac)
     {
         return mac_signer_create(cmac, truncation);
     }
     return NULL;
 }