strongSwan: tcg_seg_attr_next_seg
tcg_seg_attr_next_seg
tcg_attr
Classes
struct tcg_seg_attr_next_seg_t
Macros
#define TCG_SEG_ATTR_NEXT_SEG_SIZE 4
Typedefs
typedef struct
tcg_seg_attr_next_seg_t tcg_seg_attr_next_seg_t
Functions
pa_tnc_attr_t * tcg_seg_attr_next_seg_create (uint32_t base_attr_id, bool cancel)
pa_tnc_attr_t * tcg_seg_attr_next_seg_create_from_data (size_t length, chunk_t value)
Detailed Description
Macro Definition Documentation
#define TCG_SEG_ATTR_NEXT_SEG_SIZE 4
Definition at line 28 of file tcg_seg_attr_next_seg.h.
Referenced by METHOD().
Typedef Documentation
typedef struct tcg_seg_attr_next_seg_t tcg_seg_attr_next_seg_t
Definition at line 24 of file tcg_seg_attr_next_seg.h.
Function Documentation
pa_tnc_attr_t* tcg_seg_attr_next_seg_create (uint32_t base_attr_id, bool cancel)
Creates an tcg_seg_attr_next_seg_t object
Parameters
base_attr_id Base Attribute ID
cancel If TRUE set Cancel flag
Described in header.
Definition at line 198 of file tcg_seg_attr_next_seg.c.
References cancel(), INIT, PEN_TCG, and TCG_SEG_NEXT_SEG_REQ.
Referenced by METHOD().
 {
     private_tcg_seg_attr_next_seg_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_base_attr_id = _get_base_attr_id,
             .get_cancel_flag = _get_cancel_flag,
         },
         .type = { PEN_TCG, TCG_SEG_NEXT_SEG_REQ },
         .base_attr_id = base_attr_id,
         .cancel_flag = cancel,
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* tcg_seg_attr_next_seg_create_from_data (size_t length, chunk_t data)
Creates an tcg_seg_attr_next_seg_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 230 of file tcg_seg_attr_next_seg.c.
References chunk_clone, INIT, length, PEN_TCG, and TCG_SEG_NEXT_SEG_REQ.
Referenced by tcg_attr_create_from_data().
 {
     private_tcg_seg_attr_next_seg_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_base_attr_id = _get_base_attr_id,
             .get_cancel_flag = _get_cancel_flag,
         },
         .type = { PEN_TCG, TCG_SEG_NEXT_SEG_REQ },
         .length = length,
         .value = chunk_clone(data),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }