strongSwan: cp_payload.c File Reference
cp_payload.c File Reference
#include <stddef.h>
#include "cp_payload.h"
#include <encoding/payloads/encodings.h>
#include <collections/linked_list.h>
Classes
struct private_cp_payload_t
Typedefs
typedef struct private_cp_payload_t private_cp_payload_t
Functions
ENUM (config_type_names, CFG_REQUEST, CFG_ACK,"CFG_REQUEST","CFG_REPLY","CFG_SET","CFG_ACK",)
METHOD (payload_t, verify, status_t, private_cp_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_cp_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_cp_payload_t *this)
METHOD (payload_t, get_type, payload_type_t, private_cp_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_cp_payload_t *this)
METHOD (payload_t, set_next_type, void, private_cp_payload_t *this, payload_type_t type)
static void compute_length (private_cp_payload_t *this)
METHOD (payload_t, get_length, size_t, private_cp_payload_t *this)
METHOD (cp_payload_t, create_attribute_enumerator, enumerator_t *, private_cp_payload_t *this)
METHOD (cp_payload_t, add_attribute, void, private_cp_payload_t *this, configuration_attribute_t *attribute)
METHOD (cp_payload_t, get_config_type, config_type_t, private_cp_payload_t *this)
METHOD (cp_payload_t, get_identifier, u_int16_t, private_cp_payload_t *this)
METHOD (cp_payload_t, set_identifier, void, private_cp_payload_t *this, u_int16_t identifier)
METHOD2 (payload_t, cp_payload_t, destroy, void, private_cp_payload_t *this)
cp_payload_t * cp_payload_create_type (payload_type_t type, config_type_t cfg_type)
cp_payload_t * cp_payload_create (payload_type_t type)
Variables
static encoding_rule_t encodings_v2 []
static encoding_rule_t encodings_v1 []
Typedef Documentation
typedef struct private_cp_payload_t private_cp_payload_t
Definition at line 32 of file cp_payload.c.
Function Documentation
static void compute_length (private_cp_payload_t * this) static
recompute the length of the payload.
Definition at line 232 of file cp_payload.c.
References attributes, enumerator_t::destroy, enumerator_t::enumerate, and payload_t::get_length.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *attribute;
     this->payload_length = get_header_length(this);
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &attribute))
     {
         this->payload_length += attribute->get_length(attribute);
     }
     enumerator->destroy(enumerator);
 }
ENUM (config_type_names , CFG_REQUEST , CFG_ACK , "CFG_REQUEST" , "CFG_REPLY" , "CFG_SET" , "CFG_ACK")
METHOD (payload_t , verify , status_t , private_cp_payload_t * this)
Definition at line 173 of file cp_payload.c.
References attributes, enumerator_t::destroy, enumerator_t::enumerate, status, SUCCESS, and payload_t::verify.
 {
     status_t status = SUCCESS;
     enumerator_t *enumerator;
     payload_t *attribute;
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &attribute))
     {
         status = attribute->verify(attribute);
         if (status != SUCCESS)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return status;
 }
METHOD (payload_t , get_encoding_rules , int , private_cp_payload_t * this, encoding_rule_t ** rules)
Definition at line 193 of file cp_payload.c.
References countof, encodings_v1, encodings_v2, PLV2_CONFIGURATION, and type.
 {
     if (this->type == PLV2_CONFIGURATION)
     {
         *rules = encodings_v2;
         return countof(encodings_v2);
     }
     *rules = encodings_v1;
     return countof(encodings_v1);
 }
METHOD (payload_t , get_header_length , int , private_cp_payload_t * this)
Definition at line 205 of file cp_payload.c.
 {
     return 8;
 }
METHOD (payload_t , get_type , payload_type_t , private_cp_payload_t * this)
Definition at line 211 of file cp_payload.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_cp_payload_t * this)
Definition at line 217 of file cp_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_cp_payload_t * this, payload_type_t type)
Definition at line 223 of file cp_payload.c.
References type.
 {
     this->next_payload = type;
 }
METHOD (payload_t , get_length , size_t , private_cp_payload_t * this)
Definition at line 247 of file cp_payload.c.
 {
     return this->payload_length;
 }
METHOD (cp_payload_t , create_attribute_enumerator , enumerator_t * , private_cp_payload_t * this)
Definition at line 253 of file cp_payload.c.
References attributes.
 {
     return this->attributes->create_enumerator(this->attributes);
 }
METHOD (cp_payload_t , add_attribute , void , private_cp_payload_t * this, configuration_attribute_t * attribute)
Definition at line 259 of file cp_payload.c.
References attributes, and compute_length().
 {
     this->attributes->insert_last(this->attributes, attribute);
     compute_length(this);
 }
METHOD (cp_payload_t , get_config_type , config_type_t , private_cp_payload_t * this)
Definition at line 266 of file cp_payload.c.
 {
     return this->cfg_type;
 }
METHOD (cp_payload_t , get_identifier , u_int16_t , private_cp_payload_t * this)
Definition at line 272 of file cp_payload.c.
References identifier.
 {
     return this->identifier;
 }
METHOD (cp_payload_t , set_identifier , void , private_cp_payload_t * this, u_int16_t identifier)
Definition at line 277 of file cp_payload.c.
References identifier.
 {
     this->identifier = identifier;
 }
METHOD2 (payload_t , cp_payload_t , destroy , void , private_cp_payload_t * this)
Definition at line 283 of file cp_payload.c.
References attributes, destroy(), and free().
 {
     this->attributes->destroy_offset(this->attributes,
                                 offsetof(configuration_attribute_t, destroy));
     free(this);
 }
Variable Documentation
encoding_rule_t encodings_v1[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_cp_payload_t, next_payload)    },
    { FLAG,             offsetof(private_cp_payload_t, critical)        },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[0]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[1]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[2]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[3]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[4]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[5]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[6]) },
    { PAYLOAD_LENGTH,   offsetof(private_cp_payload_t, payload_length)  },
    { U_INT_8,          offsetof(private_cp_payload_t, cfg_type)        },
    { RESERVED_BYTE,    offsetof(private_cp_payload_t, reserved_byte[0])},
    { U_INT_16,         offsetof(private_cp_payload_t, identifier)},
    { PAYLOAD_LIST + PLV1_CONFIGURATION_ATTRIBUTE,
                        offsetof(private_cp_payload_t, attributes)      },
}
Encoding rules to for an IKEv1 configuration payload
Definition at line 135 of file cp_payload.c.
Referenced by METHOD().
encoding_rule_t encodings_v2[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_cp_payload_t, next_payload)    },
    { FLAG,             offsetof(private_cp_payload_t, critical)        },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[0]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[1]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[2]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[3]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[4]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[5]) },
    { RESERVED_BIT,     offsetof(private_cp_payload_t, reserved_bit[6]) },
    { PAYLOAD_LENGTH,   offsetof(private_cp_payload_t, payload_length)  },
    { U_INT_8,          offsetof(private_cp_payload_t, cfg_type)        },
    { RESERVED_BYTE,    offsetof(private_cp_payload_t, reserved_byte[0])},
    { RESERVED_BYTE,    offsetof(private_cp_payload_t, reserved_byte[1])},
    { RESERVED_BYTE,    offsetof(private_cp_payload_t, reserved_byte[2])},
    { PAYLOAD_LIST + PLV2_CONFIGURATION_ATTRIBUTE,
                        offsetof(private_cp_payload_t, attributes)      },
}
Encoding rules to for an IKEv2 configuration payload
Definition at line 93 of file cp_payload.c.
Referenced by METHOD().