strongSwan: bliss_huffman_code
bliss_huffman_code
bliss
Classes
struct bliss_huffman_code_tuple_t
struct bliss_huffman_code_node_t
struct bliss_huffman_code_t
Macros
#define BLISS_HUFFMAN_CODE_NO_TUPLE -1
#define BLISS_HUFFMAN_CODE_NO_NODE -1
Typedefs
typedef struct bliss_huffman_code_t bliss_huffman_code_t
typedef struct
bliss_huffman_code_tuple_t bliss_huffman_code_tuple_t
typedef struct
bliss_huffman_code_node_t bliss_huffman_code_node_t
Functions
bliss_huffman_code_t * bliss_huffman_code_get_by_id (bliss_param_set_id_t id)
Detailed Description
Macro Definition Documentation
#define BLISS_HUFFMAN_CODE_NO_NODE -1
Definition at line 38 of file bliss_huffman_code.h.
Referenced by METHOD(), and write_node().
#define BLISS_HUFFMAN_CODE_NO_TUPLE -1
Definition at line 37 of file bliss_huffman_code.h.
Referenced by METHOD(), and write_node().
Typedef Documentation
typedef struct bliss_huffman_code_node_t bliss_huffman_code_node_t
Definition at line 30 of file bliss_huffman_code.h.
typedef struct bliss_huffman_code_t bliss_huffman_code_t
Definition at line 28 of file bliss_huffman_code.h.
typedef struct bliss_huffman_code_tuple_t bliss_huffman_code_tuple_t
Definition at line 29 of file bliss_huffman_code.h.
Function Documentation
bliss_huffman_code_t* bliss_huffman_code_get_by_id (bliss_param_set_id_t id)
Get Optimum Huffman code for BLISS signature given by BLISS parameter set ID
Parameters
id BLISS parameter set ID
Returns
Optimum Huffman code for BLISS signature
See header.
Definition at line 25 of file bliss_huffman_code.c.
References BLISS_B_I, BLISS_B_III, BLISS_B_IV, bliss_huffman_code_1, bliss_huffman_code_3, bliss_huffman_code_4, BLISS_I, BLISS_III, and BLISS_IV.
Referenced by bliss_signature_create_from_data(), METHOD(), and START_TEST().
 {
     switch (id)
     {
         case BLISS_I:
         case BLISS_B_I:
             return &bliss_huffman_code_1;
         case BLISS_III:
         case BLISS_B_III:
             return &bliss_huffman_code_3;
         case BLISS_IV:
         case BLISS_B_IV:
             return &bliss_huffman_code_4;
         default:
             return NULL;
     }
 }