strongSwan: ntru_drbg.c File Reference
ntru_drbg.c File Reference
#include "ntru_drbg.h"
#include <utils/debug.h>
#include <utils/test.h>
Classes
struct private_ntru_drbg_t
Macros
#define MAX_STRENGTH_BITS 256
#define MAX_DRBG_REQUESTS 0xfffffffe
Typedefs
typedef struct private_ntru_drbg_t private_ntru_drbg_t
Functions
static bool update (private_ntru_drbg_t *this, chunk_t data)
METHOD (ntru_drbg_t, get_strength, u_int32_t, private_ntru_drbg_t *this)
METHOD (ntru_drbg_t, reseed, bool, private_ntru_drbg_t *this)
METHOD (ntru_drbg_t, generate, bool, private_ntru_drbg_t *this, u_int32_t strength, u_int32_t len, u_int8_t *out)
METHOD (ntru_drbg_t, get_ref, ntru_drbg_t *, private_ntru_drbg_t *this)
METHOD (ntru_drbg_t, destroy, void, private_ntru_drbg_t *this)
ntru_drbg_t * ntru_drbg_create (u_int32_t strength, chunk_t pers_str, rng_t *entropy)
EXPORT_FUNCTION_FOR_TESTS (ntru, ntru_drbg_create)
Macro Definition Documentation
#define MAX_DRBG_REQUESTS 0xfffffffe
Definition at line 22 of file ntru_drbg.c.
Referenced by ntru_drbg_create().
#define MAX_STRENGTH_BITS 256
Definition at line 21 of file ntru_drbg.c.
Referenced by ntru_drbg_create().
Typedef Documentation
typedef struct private_ntru_drbg_t private_ntru_drbg_t
Definition at line 24 of file ntru_drbg.c.
Function Documentation
EXPORT_FUNCTION_FOR_TESTS (ntru , ntru_drbg_create)
METHOD (ntru_drbg_t , get_strength , u_int32_t , private_ntru_drbg_t * this)
Definition at line 114 of file ntru_drbg.c.
 {
     return this->strength;
 }
METHOD (ntru_drbg_t , reseed , bool , private_ntru_drbg_t * this)
Definition at line 120 of file ntru_drbg.c.
References BITS_PER_BYTE, chunk_alloc, chunk_clear(), chunk_free(), DBG2, DBG_LIB, FALSE, chunk_t::len, chunk_t::ptr, TRUE, and update().
 {
     chunk_t seed;
     seed = chunk_alloc(this->strength / BITS_PER_BYTE);
     DBG2(DBG_LIB, "DRBG requests %u bytes of entropy", seed.len);
     if (!this->entropy->get_bytes(this->entropy, seed.len, seed.ptr))
     {
         chunk_free(&seed);
         return FALSE;
     }
     if (!update(this, seed))
     {
         chunk_free(&seed);
         return FALSE;
     }
     chunk_clear(&seed);
     this->reseed_counter = 1;
     return TRUE;
 }
METHOD (ntru_drbg_t , generate , bool , private_ntru_drbg_t * this, u_int32_t strength, u_int32_t len, u_int8_t * out)
Definition at line 144 of file ntru_drbg.c.
References chunk_create(), chunk_empty, DBG2, DBG4, DBG_LIB, FALSE, memcpy, min, reseed(), TRUE, update(), and value.
 {
     size_t delta;
     chunk_t output;
     DBG2(DBG_LIB, "DRBG generates %u pseudorandom bytes", len);
     if (!out || len == 0)
     {
         return FALSE;
     }
     output = chunk_create(out, len);
     if (this->reseed_counter > this->max_requests)
     {
         if (!reseed(this))
         {
             return FALSE;
         }
     }
     while (len)
     {
         if (!this->hmac->get_signature(this->hmac, this->value,
                                                    this->value.ptr))
         {
             return FALSE;
         }
         delta = min(len, this->value.len);
         memcpy(out, this->value.ptr, delta);
         len -= delta;
         out += delta;
     }
     DBG4(DBG_LIB, "HMAC_DRBG Out: %B", &output);
     if (!update(this, chunk_empty))
     {
         return FALSE;
     }
     this->reseed_counter++;
     return TRUE;
 }
METHOD (ntru_drbg_t , get_ref , ntru_drbg_t * , private_ntru_drbg_t * this)
Definition at line 187 of file ntru_drbg.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (ntru_drbg_t , destroy , void , private_ntru_drbg_t * this)
Definition at line 194 of file ntru_drbg.c.
References chunk_clear(), free(), key, ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         this->hmac->destroy(this->hmac);
         chunk_clear(&this->key);
         chunk_clear(&this->value);
         free(this);
     }
 }
static bool update (private_ntru_drbg_t * this, chunk_t data) static
Update the internal state of the HMAC_DRBG
Definition at line 79 of file ntru_drbg.c.
References chunk_from_chars, DBG4, DBG_LIB, FALSE, key, chunk_t::len, TRUE, and value.
Referenced by METHOD(), and ntru_drbg_create().
 {
     chunk_t ch_00 = chunk_from_chars(0x00);
     chunk_t ch_01 = chunk_from_chars(0x01);
     if (!this->hmac->set_key(this->hmac, this->key) ||
         !this->hmac->get_signature(this->hmac, this->value, NULL) ||
         !this->hmac->get_signature(this->hmac, ch_00, NULL) ||
         !this->hmac->get_signature(this->hmac, data, this->key.ptr) ||
         !this->hmac->set_key(this->hmac, this->key) ||
         !this->hmac->get_signature(this->hmac, this->value,
                                                this->value.ptr))
     {
         return FALSE;
     }
     if (data.len > 0)
     {
         if (!this->hmac->set_key(this->hmac, this->key) ||
             !this->hmac->get_signature(this->hmac, this->value, NULL) ||
             !this->hmac->get_signature(this->hmac, ch_01, NULL) ||
             !this->hmac->get_signature(this->hmac, data, this->key.ptr) ||
             !this->hmac->set_key(this->hmac, this->key) ||
             !this->hmac->get_signature(this->hmac, this->value,
                                                    this->value.ptr))
         {
             return FALSE;
         }
     }
     DBG4(DBG_LIB, "HMAC_DRBG V: %B", &this->value);
     DBG4(DBG_LIB, "HMAC_DRBG K: %B", &this->key);
     return TRUE;
 }