strongSwan: asn1_parser
asn1_parser
asn1
Classes
struct asn1Object_t
struct asn1_parser_t
Macros
#define ASN1_NONE 0x00
#define ASN1_DEF 0x01
#define ASN1_OPT 0x02
#define ASN1_LOOP 0x04
#define ASN1_END 0x08
#define ASN1_OBJ 0x10
#define ASN1_BODY 0x20
#define ASN1_RAW 0x40
#define ASN1_EXIT 0x80
Typedefs
typedef struct asn1Object_t asn1Object_t
typedef struct asn1_parser_t asn1_parser_t
Functions
asn1_parser_t * asn1_parser_create (asn1Object_t const *objects, chunk_t blob)
Detailed Description
Macro Definition Documentation
#define ASN1_BODY 0x20
Definition at line 41 of file asn1_parser.h.
Referenced by METHOD().
#define ASN1_DEF 0x01
Definition at line 36 of file asn1_parser.h.
Referenced by METHOD().
#define ASN1_END 0x08
Definition at line 39 of file asn1_parser.h.
Referenced by METHOD().
#define ASN1_EXIT 0x80
Definition at line 43 of file asn1_parser.h.
Referenced by METHOD().
#define ASN1_LOOP 0x04
Definition at line 38 of file asn1_parser.h.
Referenced by METHOD().
#define ASN1_NONE 0x00
Definition of ASN.1 flags
Definition at line 35 of file asn1_parser.h.
#define ASN1_OBJ 0x10
Definition at line 40 of file asn1_parser.h.
Referenced by METHOD().
#define ASN1_OPT 0x02
Definition at line 37 of file asn1_parser.h.
Referenced by METHOD().
#define ASN1_RAW 0x40
Definition at line 42 of file asn1_parser.h.
Referenced by METHOD().
Typedef Documentation
typedef struct asn1_parser_t asn1_parser_t
Definition at line 57 of file asn1_parser.h.
typedef struct asn1Object_t asn1Object_t
Definition at line 45 of file asn1_parser.h.
Function Documentation
asn1_parser_t* asn1_parser_create (asn1Object_t const * objects, chunk_t blob)
Create an ASN.1 parser
Parameters
objects syntax definition of the ASN.1 object to be parsed
blob ASN.1 coded binary blob
Returns
ASN.1 context
Defined in header.
Definition at line 270 of file asn1_parser.c.
References blob, INIT, and TRUE.
Referenced by add_certificate(), asn1_parse_algorithmIdentifier(), asn1_parse_time(), bliss_private_key_load(), bliss_public_key_load(), parse(), parse_attributes(), parse_authenticated_safe(), parse_authorityInfoAccess(), parse_basicConstraints(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_certificatePolicies(), parse_contentInfo(), parse_digest_info(), parse_ecdsa_public_key(), parse_encrypted_private_key(), parse_extendedKeyUsage(), parse_extension_request(), parse_generalName(), parse_groups(), parse_ipAddrBlocks(), parse_nameConstraints(), parse_OCSPResponse(), parse_otherName(), parse_pbes1_params(), parse_pbes2_params(), parse_pbkdf2_params(), parse_PFX(), parse_policyConstraints(), parse_policyMappings(), parse_private_key(), parse_public_key(), parse_responses(), parse_roleSyntax(), parse_rsa_private_key(), parse_rsa_public_key(), parse_safe_contents(), parse_singleResponse(), run_parser_test(), START_TEST(), verify_emsa_pkcs1_signature(), x509_parse_authorityKeyIdentifier(), x509_parse_crlDistributionPoints(), and x509_parse_generalNames().
 {
     private_asn1_parser_t *this;
     INIT(this,
         .public = {
             .iterate = _iterate,
             .get_level = _get_level,
             .set_top_level = _set_top_level,
             .set_flags = _set_flags,
             .success = _success,
             .destroy = _destroy,
         },
         .objects = objects,
         .blobs[0] = blob,
         .line = -1,
         .success = TRUE,
     );
     return &this->public;
 }