strongSwan: ipseckey
ipseckey
ipseckey
Classes
struct ipseckey_t
Typedefs
typedef struct ipseckey_t ipseckey_t
typedef enum ipseckey_algorithm_t ipseckey_algorithm_t
typedef enum ipseckey_gw_type_t ipseckey_gw_type_t
Enumerations
enum ipseckey_gw_type_t { IPSECKEY_GW_TP_NOT_PRESENT = 0, IPSECKEY_GW_TP_IPV4 = 1, IPSECKEY_GW_TP_IPV6 = 2, IPSECKEY_GW_TP_WR_ENC_DNAME = 3 }
enum ipseckey_algorithm_t { IPSECKEY_ALGORITHM_NONE = 0, IPSECKEY_ALGORITHM_DSA = 1, IPSECKEY_ALGORITHM_RSA = 2 }
Functions
ipseckey_t * ipseckey_create_frm_rr (rr_t *rr)
Detailed Description
Typedef Documentation
typedef enum ipseckey_algorithm_t ipseckey_algorithm_t
Definition at line 25 of file ipseckey.h.
typedef enum ipseckey_gw_type_t ipseckey_gw_type_t
Definition at line 26 of file ipseckey.h.
typedef struct ipseckey_t ipseckey_t
Definition at line 24 of file ipseckey.h.
Enumeration Type Documentation
enum ipseckey_algorithm_t
IPSECKEY algorithms as defined in RFC 4025.
Enumerator
IPSECKEY_ALGORITHM_NONE
No key present
IPSECKEY_ALGORITHM_DSA
DSA key
IPSECKEY_ALGORITHM_RSA
RSA key
Definition at line 47 of file ipseckey.h.
{
     IPSECKEY_ALGORITHM_NONE = 0,
     IPSECKEY_ALGORITHM_DSA = 1,
     IPSECKEY_ALGORITHM_RSA = 2,
 };
enum ipseckey_gw_type_t
IPSECKEY gateway types as defined in RFC 4025.
Enumerator
IPSECKEY_GW_TP_NOT_PRESENT
No gateway is present
IPSECKEY_GW_TP_IPV4
A 4-byte IPv4 address is present
IPSECKEY_GW_TP_IPV6
A 16-byte IPv6 address is present
IPSECKEY_GW_TP_WR_ENC_DNAME
A wire-encoded domain name is present
Definition at line 33 of file ipseckey.h.
{
     IPSECKEY_GW_TP_NOT_PRESENT = 0,
     IPSECKEY_GW_TP_IPV4 = 1,
     IPSECKEY_GW_TP_IPV6 = 2,
     IPSECKEY_GW_TP_WR_ENC_DNAME = 3,
 };
Function Documentation
ipseckey_t* ipseckey_create_frm_rr (rr_t * rr)
Create an ipseckey instance out of a resource record.
Parameters
rr resource record which contains an IPSECKEY
Returns
ipseckey, NULL on failure
Parse the content (RDATA field) of the RR
Uncompressed domain name as defined in RFC 1035 chapter 3.
TODO: Currently we ignore wire encoded domain names.
Definition at line 101 of file ipseckey.c.
References algorithm, bio_reader_create(), chunk_clone, chunk_free(), DBG1, DBG_CFG, bio_reader_t::destroy, free(), rr_t::get_rdata, rr_t::get_type, INIT, IPSECKEY_GW_TP_IPV4, IPSECKEY_GW_TP_IPV6, IPSECKEY_GW_TP_NOT_PRESENT, IPSECKEY_GW_TP_WR_ENC_DNAME, public_key, bio_reader_t::read_data, bio_reader_t::read_uint8, bio_reader_t::remaining, and RR_TYPE_IPSECKEY.
Referenced by METHOD().
 {
     private_ipseckey_t *this;
     bio_reader_t *reader = NULL;
     u_int8_t label;
     chunk_t tmp;
     INIT(this,
             .public = {
                 .get_precedence = _get_precedence,
                 .get_gateway_type = _get_gateway_type,
                 .get_algorithm = _get_algorithm,
                 .get_gateway = _get_gateway,
                 .get_public_key = _get_public_key,
                 .destroy = _destroy,
             },
     );
     if (rr->get_type(rr) != RR_TYPE_IPSECKEY)
     {
         DBG1(DBG_CFG, "unable to create an ipseckey out of an RR "
                       "whose type is not IPSECKEY");
         free(this);
         return NULL;
     }
     reader = bio_reader_create(rr->get_rdata(rr));
     if (!reader->read_uint8(reader, &this->precedence) ||
         !reader->read_uint8(reader, &this->gateway_type) ||
         !reader->read_uint8(reader, &this->algorithm))
     {
         DBG1(DBG_CFG, "ipseckey RR has a wrong format");
         reader->destroy(reader);
         free(this);
         return NULL;
     }
     switch (this->gateway_type)
     {
         case IPSECKEY_GW_TP_NOT_PRESENT:
             break;
         case IPSECKEY_GW_TP_IPV4:
             if (!reader->read_data(reader, 4, &this->gateway))
             {
                 DBG1(DBG_CFG, "ipseckey gateway field does not contain an "
                               "IPv4 address as expected");
                 reader->destroy(reader);
                 free(this);
                 return NULL;
             }
             this->gateway = chunk_clone(this->gateway);
             break;
         case IPSECKEY_GW_TP_IPV6:
             if (!reader->read_data(reader, 16, &this->gateway))
             {
                 DBG1(DBG_CFG, "ipseckey gateway field does not contain an "
                               "IPv6 address as expected");
                 reader->destroy(reader);
                 free(this);
                 return NULL;
             }
             this->gateway = chunk_clone(this->gateway);
             break;
         case IPSECKEY_GW_TP_WR_ENC_DNAME:
             while (reader->read_uint8(reader, &label) &&
                    label != 0 && label < 192)
             {
                 if (!reader->read_data(reader, label, &tmp))
                 {
                     DBG1(DBG_CFG, "wrong wire encoded domain name format "
                                   "in ipseckey gateway field");
                     reader->destroy(reader);
                     free(this);
                     return NULL;
                 }
             }
             break;
         default:
             DBG1(DBG_CFG, "unable to parse ipseckey gateway field");
             reader->destroy(reader);
             free(this);
             return NULL;
     }
     if (!reader->read_data(reader, reader->remaining(reader),
                            &this->public_key))
     {
         DBG1(DBG_CFG, "failed to read ipseckey public key field");
         reader->destroy(reader);
         chunk_free(&this->gateway);
         free(this);
         return NULL;
     }
     this->public_key = chunk_clone(this->public_key);
     reader->destroy(reader);
     return &this->public;
 }