strongSwan: processor.c File Reference
processor.c File Reference
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "processor.h"
#include <utils/debug.h>
#include <threading/thread.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
#include <threading/thread_value.h>
#include <collections/linked_list.h>
Classes
struct private_processor_t
struct worker_thread_t
Typedefs
typedef struct private_processor_t private_processor_t
Functions
static void process_jobs (worker_thread_t *worker)
static void restart (worker_thread_t *worker)
static u_int get_idle_threads_nolock (private_processor_t *this)
static bool get_job (private_processor_t *this, worker_thread_t *worker)
static void process_job (private_processor_t *this, worker_thread_t *worker)
METHOD (processor_t, get_total_threads, u_int, private_processor_t *this)
METHOD (processor_t, get_idle_threads, u_int, private_processor_t *this)
static job_priority_t sane_prio (job_priority_t prio)
METHOD (processor_t, get_working_threads, u_int, private_processor_t *this, job_priority_t prio)
METHOD (processor_t, get_job_load, u_int, private_processor_t *this, job_priority_t prio)
METHOD (processor_t, queue_job, void, private_processor_t *this, job_t *job)
METHOD (processor_t, execute_job, void, private_processor_t *this, job_t *job)
METHOD (processor_t, set_threads, void, private_processor_t *this, u_int count)
METHOD (processor_t, cancel, void, private_processor_t *this)
METHOD (processor_t, destroy, void, private_processor_t *this)
processor_t * processor_create ()
Typedef Documentation
typedef struct private_processor_t private_processor_t
Definition at line 32 of file processor.c.
Function Documentation
static u_int get_idle_threads_nolock (private_processor_t * this) static
Get number of idle threads, non-locking variant
Definition at line 170 of file processor.c.
References count, and JOB_PRIO_MAX.
Referenced by get_job(), and METHOD().
 {
     u_int count, i;
     count = this->total_threads;
     for (i = 0; i < JOB_PRIO_MAX; i++)
     {
         count -= this->working_threads[i];
     }
     return count;
 }
static bool get_job (private_processor_t * this, worker_thread_t * worker) static
Get a job from any job queue, starting with the highest priority.
this->mutex is expected to be locked.
Definition at line 187 of file processor.c.
References DBG2, DBG_JOB, FALSE, get_idle_threads_nolock(), idle(), worker_thread_t::job, JOB_PRIO_MAX, job_priority_names, worker_thread_t::priority, remove_first(), reserved, SUCCESS, and TRUE.
Referenced by process_jobs().
 {
     int i, reserved = 0, idle;
     idle = get_idle_threads_nolock(this);
     for (i = 0; i < JOB_PRIO_MAX; i++)
     {
         if (reserved && reserved >= idle)
         {
             DBG2(DBG_JOB, "delaying %N priority jobs: %d threads idle, "
                  "but %d reserved for higher priorities",
                  job_priority_names, i, idle, reserved);
             /* wait until a job of higher priority gets queued */
             return FALSE;
         }
         if (this->working_threads[i] < this->prio_threads[i])
         {
             reserved += this->prio_threads[i] - this->working_threads[i];
         }
         if (this->jobs[i]->remove_first(this->jobs[i],
                                         (void**)&worker->job) == SUCCESS)
         {
             worker->priority = i;
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (processor_t , get_total_threads , u_int , private_processor_t * this)
Definition at line 333 of file processor.c.
References count, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     u_int count;
     this->mutex->lock(this->mutex);
     count = this->total_threads;
     this->mutex->unlock(this->mutex);
     return count;
 }
METHOD (processor_t , get_idle_threads , u_int , private_processor_t * this)
Definition at line 344 of file processor.c.
References count, get_idle_threads_nolock(), mutex_t::lock, mutex, and mutex_t::unlock.
 {
     u_int count;
     this->mutex->lock(this->mutex);
     count = get_idle_threads_nolock(this);
     this->mutex->unlock(this->mutex);
     return count;
 }
METHOD (processor_t , get_working_threads , u_int , private_processor_t * this, job_priority_t prio)
Definition at line 367 of file processor.c.
References count, mutex_t::lock, mutex, sane_prio(), and mutex_t::unlock.
 {
     u_int count;
     this->mutex->lock(this->mutex);
     count = this->working_threads[sane_prio(prio)];
     this->mutex->unlock(this->mutex);
     return count;
 }
METHOD (processor_t , get_job_load , u_int , private_processor_t * this, job_priority_t prio)
Definition at line 378 of file processor.c.
References load(), mutex_t::lock, mutex, sane_prio(), and mutex_t::unlock.
 {
     u_int load;
     prio = sane_prio(prio);
     this->mutex->lock(this->mutex);
     load = this->jobs[prio]->get_count(this->jobs[prio]);
     this->mutex->unlock(this->mutex);
     return load;
 }
METHOD (processor_t , queue_job , void , private_processor_t * this, job_t * job)
Definition at line 390 of file processor.c.
References job_t::get_priority, JOB_STATUS_QUEUED, mutex_t::lock, mutex, sane_prio(), job_t::status, and mutex_t::unlock.
 {
     job_priority_t prio;
     prio = sane_prio(job->get_priority(job));
     job->status = JOB_STATUS_QUEUED;
     this->mutex->lock(this->mutex);
     this->jobs[prio]->insert_last(this->jobs[prio], job);
     this->job_added->signal(this->job_added);
     this->mutex->unlock(this->mutex);
 }
METHOD (processor_t , execute_job , void , private_processor_t * this, job_t * job)
Definition at line 404 of file processor.c.
References job_t::destroy, job_t::execute, FALSE, get_idle_threads_nolock(), job_t::get_priority, JOB_STATUS_QUEUED, mutex_t::lock, mutex, sane_prio(), job_t::status, TRUE, and mutex_t::unlock.
 {
     job_priority_t prio;
     bool queued = FALSE;
     this->mutex->lock(this->mutex);
     if (this->desired_threads && get_idle_threads_nolock(this))
     {
         prio = sane_prio(job->get_priority(job));
         job->status = JOB_STATUS_QUEUED;
         /* insert job in front to execute it immediately */
         this->jobs[prio]->insert_first(this->jobs[prio], job);
         queued = TRUE;
     }
     this->job_added->signal(this->job_added);
     this->mutex->unlock(this->mutex);
     if (!queued)
     {
         job->execute(job);
         job->destroy(job);
     }
 }
METHOD (processor_t , set_threads , void , private_processor_t * this, u_int count)
Definition at line 429 of file processor.c.
References count, DBG1, DBG_JOB, free(), INIT, mutex_t::lock, mutex, process_jobs(), worker_thread_t::thread, thread_create, threads, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     if (count > this->total_threads)
     {   /* increase thread count */
         worker_thread_t *worker;
         int i;
         this->desired_threads = count;
         DBG1(DBG_JOB, "spawning %d worker threads", count - this->total_threads);
         for (i = this->total_threads; i < count; i++)
         {
             INIT(worker,
                 .processor = this,
             );
             worker->thread = thread_create((thread_main_t)process_jobs, worker);
             if (worker->thread)
             {
                 this->threads->insert_last(this->threads, worker);
                 this->total_threads++;
             }
             else
             {
                 free(worker);
             }
         }
     }
     else if (count < this->total_threads)
     {   /* decrease thread count */
         this->desired_threads = count;
     }
     this->job_added->broadcast(this->job_added);
     this->mutex->unlock(this->mutex);
 }
METHOD (processor_t , cancel , void , private_processor_t * this)
Definition at line 465 of file processor.c.
References thread_t::cancel, job_t::cancel, hashtable_t::create_enumerator, enumerator_t::destroy, job_t::destroy, enumerator_t::enumerate, free(), worker_thread_t::job, JOB_PRIO_MAX, JOB_STATUS_CANCELED, thread_t::join, mutex_t::lock, mutex, remove_first(), job_t::status, SUCCESS, worker_thread_t::thread, threads, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     worker_thread_t *worker;
     job_t *job;
     int i;
     this->mutex->lock(this->mutex);
     this->desired_threads = 0;
     /* cancel potentially blocking jobs */
     enumerator = this->threads->create_enumerator(this->threads);
     while (enumerator->enumerate(enumerator, (void**)&worker))
     {
         if (worker->job && worker->job->cancel)
         {
             worker->job->status = JOB_STATUS_CANCELED;
             if (!worker->job->cancel(worker->job))
             {   /* job requests to be canceled explicitly, otherwise we assume
                  * the thread terminates itself and can be joined */
                 worker->thread->cancel(worker->thread);
             }
         }
     }
     enumerator->destroy(enumerator);
     while (this->total_threads > 0)
     {
         this->job_added->broadcast(this->job_added);
         this->thread_terminated->wait(this->thread_terminated, this->mutex);
     }
     while (this->threads->remove_first(this->threads,
                                       (void**)&worker) == SUCCESS)
     {
         worker->thread->join(worker->thread);
         free(worker);
     }
     for (i = 0; i < JOB_PRIO_MAX; i++)
     {
         while (this->jobs[i]->remove_first(this->jobs[i],
                                            (void**)&job) == SUCCESS)
         {
             job->destroy(job);
         }
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (processor_t , destroy , void , private_processor_t * this)
Definition at line 512 of file processor.c.
References cancel(), mutex_t::destroy, hashtable_t::destroy, free(), JOB_PRIO_MAX, mutex, and threads.
 {
     int i;
     cancel(this);
     this->thread_terminated->destroy(this->thread_terminated);
     this->job_added->destroy(this->job_added);
     this->mutex->destroy(this->mutex);
     for (i = 0; i < JOB_PRIO_MAX; i++)
     {
         this->jobs[i]->destroy(this->jobs[i]);
     }
     this->threads->destroy(this->threads);
     free(this);
 }
static void process_job (private_processor_t * this, worker_thread_t * worker) static
Process a single job (provided in worker->job, worker->priority is also expected to be set)
this->mutex is expected to be locked.
Definition at line 223 of file processor.c.
References job_requeue_t::abs, job_t::cancel, job_t::destroy, job_t::execute, FALSE, worker_thread_t::job, JOB_REQUEUE_TYPE_DIRECT, JOB_REQUEUE_TYPE_FAIR, JOB_REQUEUE_TYPE_NONE, JOB_REQUEUE_TYPE_SCHEDULE, JOB_STATUS_CANCELED, JOB_STATUS_DONE, JOB_STATUS_EXECUTING, JOB_STATUS_QUEUED, lib, mutex_t::lock, mutex, worker_thread_t::priority, job_requeue_t::rel, restart(), job_requeue_t::schedule, scheduler_t::schedule_job, scheduler_t::schedule_job_ms, scheduler_t::schedule_job_tv, library_t::scheduler, job_t::status, thread_cleanup_pop(), thread_cleanup_push(), job_requeue_t::time, TRUE, job_requeue_t::type, and mutex_t::unlock.
Referenced by process_jobs().
 {
     job_t *to_destroy = NULL;
     job_requeue_t requeue;
     this->working_threads[worker->priority]++;
     worker->job->status = JOB_STATUS_EXECUTING;
     this->mutex->unlock(this->mutex);
     /* canceled threads are restarted to get a constant pool */
     thread_cleanup_push((thread_cleanup_t)restart, worker);
     while (TRUE)
     {
         requeue = worker->job->execute(worker->job);
         if (requeue.type != JOB_REQUEUE_TYPE_DIRECT)
         {
             break;
         }
         else if (!worker->job->cancel)
         {   /* only allow cancelable jobs to requeue directly */
             requeue.type = JOB_REQUEUE_TYPE_FAIR;
             break;
         }
     }
     thread_cleanup_pop(FALSE);
     this->mutex->lock(this->mutex);
     this->working_threads[worker->priority]--;
     if (worker->job->status == JOB_STATUS_CANCELED)
     {   /* job was canceled via a custom cancel() method or did not
          * use JOB_REQUEUE_TYPE_DIRECT */
         to_destroy = worker->job;
     }
     else
     {
         switch (requeue.type)
         {
             case JOB_REQUEUE_TYPE_NONE:
                 worker->job->status = JOB_STATUS_DONE;
                 to_destroy = worker->job;
                 break;
             case JOB_REQUEUE_TYPE_FAIR:
                 worker->job->status = JOB_STATUS_QUEUED;
                 this->jobs[worker->priority]->insert_last(
                                     this->jobs[worker->priority], worker->job);
                 this->job_added->signal(this->job_added);
                 break;
             case JOB_REQUEUE_TYPE_SCHEDULE:
                 /* scheduler_t does not hold its lock when queuing jobs
                  * so this should be safe without unlocking our mutex */
                 switch (requeue.schedule)
                 {
                     case JOB_SCHEDULE:
                         lib->scheduler->schedule_job(lib->scheduler,
                                                 worker->job, requeue.time.rel);
                         break;
                     case JOB_SCHEDULE_MS:
                         lib->scheduler->schedule_job_ms(lib->scheduler,
                                                 worker->job, requeue.time.rel);
                         break;
                     case JOB_SCHEDULE_TV:
                         lib->scheduler->schedule_job_tv(lib->scheduler,
                                                 worker->job, requeue.time.abs);
                         break;
                 }
                 break;
             default:
                 break;
         }
     }
     /* unset the current job to avoid interference with cancel() when
      * destroying the job below */
     worker->job = NULL;
     if (to_destroy)
     {   /* release mutex to avoid deadlocks if the same lock is required
          * during queue_job() and in the destructor called here */
         this->mutex->unlock(this->mutex);
         to_destroy->destroy(to_destroy);
         this->mutex->lock(this->mutex);
     }
 }
static void process_jobs (worker_thread_t * worker) static
Process queued jobs, called by the worker threads
Definition at line 307 of file processor.c.
References DBG2, DBG_JOB, FALSE, get_job(), mutex_t::lock, mutex, process_job(), worker_thread_t::processor, thread_cancelability(), thread_current_id(), and mutex_t::unlock.
Referenced by METHOD(), and restart().
 {
     private_processor_t *this = worker->processor;
     /* worker threads are not cancelable by default */
     thread_cancelability(FALSE);
     DBG2(DBG_JOB, "started worker thread %.2u", thread_current_id());
     this->mutex->lock(this->mutex);
     while (this->desired_threads >= this->total_threads)
     {
         if (get_job(this, worker))
         {
             process_job(this, worker);
         }
         else
         {
             this->job_added->wait(this->job_added, this->mutex);
         }
     }
     this->total_threads--;
     this->thread_terminated->signal(this->thread_terminated);
     this->mutex->unlock(this->mutex);
 }
static void restart (worker_thread_t * worker) static
restart a terminated thread
Definition at line 123 of file processor.c.
References DBG2, DBG_JOB, job_t::destroy, free(), INIT, worker_thread_t::job, JOB_STATUS_CANCELED, mutex_t::lock, mutex, worker_thread_t::priority, process_jobs(), worker_thread_t::processor, job_t::status, worker_thread_t::thread, thread_create, thread_current_id(), threads, and mutex_t::unlock.
Referenced by METHOD(), and process_job().
 {
     private_processor_t *this = worker->processor;
     job_t *job;
     DBG2(DBG_JOB, "terminated worker thread %.2u", thread_current_id());
     this->mutex->lock(this->mutex);
     /* cleanup worker thread  */
     this->working_threads[worker->priority]--;
     worker->job->status = JOB_STATUS_CANCELED;
     job = worker->job;
     /* unset the job before releasing the mutex, otherwise cancel() might
      * interfere */
     worker->job = NULL;
     /* release mutex to avoid deadlocks if the same lock is required
      * during queue_job() and in the destructor called here */
     this->mutex->unlock(this->mutex);
     job->destroy(job);
     this->mutex->lock(this->mutex);
     /* respawn thread if required */
     if (this->desired_threads >= this->total_threads)
     {
         worker_thread_t *new_worker;
         INIT(new_worker,
             .processor = this,
         );
         new_worker->thread = thread_create((thread_main_t)process_jobs,
                                            new_worker);
         if (new_worker->thread)
         {
             this->threads->insert_last(this->threads, new_worker);
             this->mutex->unlock(this->mutex);
             return;
         }
         free(new_worker);
     }
     this->total_threads--;
     this->thread_terminated->signal(this->thread_terminated);
     this->mutex->unlock(this->mutex);
 }
static job_priority_t sane_prio (job_priority_t prio) static
Check priority bounds
Definition at line 358 of file processor.c.
References JOB_PRIO_MAX.
Referenced by METHOD().
 {
     if ((int)prio < 0 || prio >= JOB_PRIO_MAX)
     {
         return JOB_PRIO_MAX - 1;
     }
     return prio;
 }