strongSwan: dnscert_cred.c File Reference
dnscert_cred.c File Reference
#include <stdio.h>
#include <string.h>
#include "dnscert_cred.h"
#include "dnscert.h"
Classes
struct private_dnscert_cred_t
struct cert_enumerator_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_dnscert_cred_t private_dnscert_cred_t
Functions
METHOD (enumerator_t, cert_enumerator_enumerate, bool, cert_enumerator_t *this, certificate_t **cert)
METHOD (enumerator_t, cert_enumerator_destroy, void, cert_enumerator_t *this)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_dnscert_cred_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (dnscert_cred_t, destroy, void, private_dnscert_cred_t *this)
dnscert_cred_t * dnscert_cred_create (resolver_t *res)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 38 of file dnscert_cred.c.
Typedef Documentation
typedef struct private_dnscert_cred_t private_dnscert_cred_t
Definition at line 45 of file dnscert_cred.c.
Function Documentation
METHOD (enumerator_t , cert_enumerator_enumerate , bool , cert_enumerator_t * this, certificate_t ** cert)
Definition at line 75 of file dnscert_cred.c.
References BUILD_BLOB_PEM, BUILD_END, CERT_ANY, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_CFG, dnscert_t::destroy, dnscert_create_frm_rr(), DNSCERT_TYPE_PGP, DNSCERT_TYPE_PKIX, FALSE, dnscert_t::get_cert_type, dnscert_t::get_certificate, lib, and TRUE.
 {
     dnscert_t *cur_crt;
     rr_t *cur_rr;
     chunk_t certificate;
     /* Get the next supported CERT using the inner enumerator. */
     while (this->inner->enumerate(this->inner, &cur_rr))
     {
         cur_crt = dnscert_create_frm_rr(cur_rr);
         if (!cur_crt)
         {
             DBG1(DBG_CFG, "  failed to parse CERT RR, skipping");
             continue;
         }
         if (cur_crt->get_cert_type(cur_crt) != DNSCERT_TYPE_PKIX &&
             cur_crt->get_cert_type(cur_crt) != DNSCERT_TYPE_PGP)
         {
             DBG1(DBG_CFG, "  unsupported CERT type [%d], skipping",
                  cur_crt->get_cert_type(cur_crt));
             cur_crt->destroy(cur_crt);
             continue;
         }
         /* Try to parse PEM certificate container. Both x509 and PGP should
          * presumably come as PEM encoded certs. */
         certificate = cur_crt->get_certificate(cur_crt);
         *cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_ANY,
                                    BUILD_BLOB_PEM, certificate,
                                    BUILD_END);
         if (*cert == NULL)
         {
             DBG1(DBG_CFG, "  unable to parse certificate, skipping",
                  cur_crt->get_cert_type(cur_crt));
             cur_crt->destroy(cur_crt);
             continue;
         }
         cur_crt->destroy(cur_crt);
         return TRUE;
     }
     return FALSE;
 }
METHOD (enumerator_t , cert_enumerator_destroy , void , cert_enumerator_t * this)
Definition at line 120 of file dnscert_cred.c.
References free(), and response.
 {
     this->inner->destroy(this->inner);
     this->response->destroy(this->response);
     free(this);
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_dnscert_cred_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 128 of file dnscert_cred.c.
References asprintf(), rr_set_t::create_rr_enumerator, DBG1, DBG_CFG, resolver_response_t::destroy, destroy(), enumerator_create_empty(), free(), resolver_response_t::get_rr_set, resolver_response_t::get_security_state, identification_t::get_type, resolver_response_t::has_data, ID_FQDN, INIT, cert_enumerator_t::public, resolver_response_t::query_name_exist, res, response, RR_CLASS_IN, RR_TYPE_CERT, and SECURE.
 {
     resolver_response_t *response;
     cert_enumerator_t *e;
     char *fqdn;
     if (!id || id->get_type(id) != ID_FQDN)
     {
         return enumerator_create_empty();
     }
     /* query the DNS for the required CERT RRs */
     if (asprintf(&fqdn, "%Y", id) <= 0)
     {
         DBG1(DBG_CFG, "failed to determine FQDN to retrieve CERT RRs");
         return enumerator_create_empty();
     }
     DBG1(DBG_CFG, "performing a DNS query for CERT RRs of '%s'", fqdn);
     response = this->res->query(this->res, fqdn, RR_CLASS_IN, RR_TYPE_CERT);
     if (!response)
     {
         DBG1(DBG_CFG, "  query for CERT RRs failed");
         free(fqdn);
         return enumerator_create_empty();
     }
     free(fqdn);
     if (!response->has_data(response) ||
         !response->query_name_exist(response))
     {
         DBG1(DBG_CFG, "  unable to retrieve CERT RRs from the DNS");
         response->destroy(response);
         return enumerator_create_empty();
     }
     if (response->get_security_state(response) != SECURE)
     {
         DBG1(DBG_CFG, "  DNSSEC state of CERT RRs is not secure");
         response->destroy(response);
         return enumerator_create_empty();
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_cert_enumerator_enumerate,
             .destroy = _cert_enumerator_destroy,
         },
         .inner = response->get_rr_set(response)->create_rr_enumerator(
                                       response->get_rr_set(response)),
         .response = response
     );
     return &e->public;
 }
METHOD (dnscert_cred_t , destroy , void , private_dnscert_cred_t * this)
Definition at line 185 of file dnscert_cred.c.
References free(), and res.
 {
     this->res->destroy(this->res);
     free(this);
 }