strongSwan: af_alg_prf
af_alg_prf
af_alg
Classes
struct af_alg_prf_t
Macros
#define AF_ALG_PRF 7
Typedefs
typedef struct af_alg_prf_t af_alg_prf_t
Functions
af_alg_prf_t * af_alg_prf_create (pseudo_random_function_t algo)
void af_alg_prf_probe (plugin_feature_t *features, int *pos)
Detailed Description
Macro Definition Documentation
#define AF_ALG_PRF 7
Number of PRFs
Definition at line 30 of file af_alg_prf.h.
Referenced by METHOD().
Typedef Documentation
typedef struct af_alg_prf_t af_alg_prf_t
Definition at line 24 of file af_alg_prf.h.
Function Documentation
af_alg_prf_t* af_alg_prf_create (pseudo_random_function_t algo)
Creates a new af_alg_prf_t object.
Parameters
algo algorithm to implement
Returns
af_alg_prf_t object, NULL if hash not supported
Definition at line 177 of file af_alg_prf.c.
References af_alg_ops_create(), block_size, free(), INIT, lookup_alg(), name, and xcbc.
Referenced by METHOD().
 {
     private_af_alg_prf_t *this;
     size_t block_size;
     bool xcbc;
     char *name;
     block_size = lookup_alg(algo, &name, &xcbc);
     if (!block_size)
     {   /* not supported by kernel */
         return NULL;
     }
     INIT(this,
         .public = {
             .prf = {
                 .get_bytes = _get_bytes,
                 .allocate_bytes = _allocate_bytes,
                 .get_block_size = _get_block_size,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .ops = af_alg_ops_create("hash", name),
         .block_size = block_size,
         .xcbc = xcbc,
     );
     if (!this->ops)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }
void af_alg_prf_probe (plugin_feature_t * features, int * pos)
Probe algorithms and return plugin features.
Parameters
features plugin features to create
pos current position in features
See header.
Definition at line 73 of file af_alg_prf.c.
References af_alg_ops_create(), algs, countof, af_alg_ops_t::destroy, name, and PLUGIN_PROVIDE.
Referenced by METHOD().
 {
     af_alg_ops_t *ops;
     int i;
     for (i = 0; i < countof(algs); i++)
     {
         ops = af_alg_ops_create("hash", algs[i].name);
         if (ops)
         {
             ops->destroy(ops);
             features[(*pos)++] = PLUGIN_PROVIDE(PRF, algs[i].id);
         }
     }
 }