strongSwan: settings_types.c File Reference
settings_types.c File Reference
#include "settings_types.h"
Functions
kv_t * settings_kv_create (char *key, char *value)
void settings_kv_destroy (kv_t *this, array_t *contents)
section_t * settings_section_create (char *name)
static void section_destroy (section_t *section, int idx, array_t *contents)
static void kv_destroy (kv_t *kv, int idx, array_t *contents)
void settings_section_destroy (section_t *this, array_t *contents)
void settings_kv_set (kv_t *kv, char *value, array_t *contents)
void settings_kv_add (section_t *section, kv_t *kv, array_t *contents)
static void add_section (section_t *parent, section_t *section, array_t *contents, bool purge)
void settings_section_add (section_t *parent, section_t *section, array_t *contents)
static bool section_purge (section_t *this, array_t *contents)
void settings_section_extend (section_t *base, section_t *extension, array_t *contents, bool purge)
int settings_section_find (const void *a, const void *b)
int settings_section_sort (const void *a, const void *b, void *user)
int settings_kv_find (const void *a, const void *b)
int settings_kv_sort (const void *a, const void *b, void *user)
Function Documentation
static void add_section (section_t * parent, section_t * section, array_t * contents, bool purge) static
Definition at line 136 of file settings_types.c.
References array_bsearch(), array_insert_create(), array_sort(), ARRAY_TAIL, found, section_t::name, section_t::sections, section_t::sections_order, settings_section_destroy(), settings_section_extend(), settings_section_find(), and settings_section_sort().
Referenced by settings_section_add(), and settings_section_extend().
 {
     section_t *found;
     if (array_bsearch(parent->sections, section->name, settings_section_find,
                       &found) == -1)
     {
         array_insert_create(&parent->sections, ARRAY_TAIL, section);
         array_sort(parent->sections, settings_section_sort, NULL);
         array_insert_create(&parent->sections_order, ARRAY_TAIL, section);
     }
     else
     {
         settings_section_extend(found, section, contents, purge);
         settings_section_destroy(section, contents);
     }
 }
static void kv_destroy (kv_t * kv, int idx, array_t * contents) static
Definition at line 67 of file settings_types.c.
References settings_kv_destroy().
Referenced by section_purge(), and settings_section_destroy().
 {
     settings_kv_destroy(kv, contents);
 }
static void section_destroy (section_t * section, int idx, array_t * contents) static
Definition at line 62 of file settings_types.c.
References settings_section_destroy().
Referenced by settings_section_destroy().
 {
     settings_section_destroy(section, contents);
 }
static bool section_purge (section_t * this, array_t * contents) static
Purge contents of a section, returns TRUE if section can be safely removed.
Definition at line 167 of file settings_types.c.
References array_bsearch(), array_count(), array_destroy(), array_destroy_function(), array_get(), array_remove(), kv_destroy(), section_t::name, settings_section_destroy(), and settings_section_find().
Referenced by settings_section_extend().
 {
     section_t *current;
     int i, idx;
     array_destroy_function(this->kv, (void*)kv_destroy, contents);
     this->kv = NULL;
     array_destroy(this->kv_order);
     this->kv_order = NULL;
     /* we ensure sections used as fallback, or configured with fallbacks (or
      * having any such subsections) are not removed */
     for (i = array_count(this->sections_order) - 1; i >= 0; i--)
     {
         array_get(this->sections, i, &current);
         if (section_purge(current, contents))
         {
             array_remove(this->sections_order, i, NULL);
             idx = array_bsearch(this->sections, current->name,
                                 settings_section_find, NULL);
             array_remove(this->sections, idx, NULL);
             settings_section_destroy(current, contents);
         }
     }
     return !this->fallbacks && !array_count(this->sections);
 }