strongSwan: host_resolver
host_resolver
networking
Classes
struct host_resolver_t
Typedefs
typedef struct host_resolver_t host_resolver_t
Functions
host_resolver_t * host_resolver_create ()
Detailed Description
Typedef Documentation
typedef struct host_resolver_t host_resolver_t
Definition at line 26 of file host_resolver.h.
Function Documentation
host_resolver_t* host_resolver_create ()
Create a host_resolver_t instance.
Definition at line 342 of file host_resolver.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, settings_t::get_int, hashtable_create(), INIT, lib, linked_list_create(), max, MAX_THREADS_DEFAULT, MIN_THREADS_DEFAULT, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, query_equals(), query_hash(), and library_t::settings.
Referenced by library_init().
 {
     private_host_resolver_t *this;
     INIT(this,
         .public = {
             .resolve = _resolve,
             .flush = _flush,
             .destroy = _destroy,
         },
         .queries = hashtable_create((hashtable_hash_t)query_hash,
                                     (hashtable_equals_t)query_equals, 8),
         .queue = linked_list_create(),
         .pool = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .new_query = condvar_create(CONDVAR_TYPE_DEFAULT),
     );
     this->min_threads = max(0, lib->settings->get_int(lib->settings,
                                                 "%s.host_resolver.min_threads",
                                                 MIN_THREADS_DEFAULT, lib->ns));
     this->max_threads = max(this->min_threads ?: 1,
                             lib->settings->get_int(lib->settings,
                                                 "%s.host_resolver.max_threads",
                                                 MAX_THREADS_DEFAULT, lib->ns));
     return &this->public;
 }