strongSwan: auth_cfg_wrapper
auth_cfg_wrapper
sets
Classes
struct auth_cfg_wrapper_t
Typedefs
typedef struct auth_cfg_wrapper_t auth_cfg_wrapper_t
Functions
auth_cfg_wrapper_t * auth_cfg_wrapper_create (auth_cfg_t *auth)
Detailed Description
Typedef Documentation
typedef struct auth_cfg_wrapper_t auth_cfg_wrapper_t
Definition at line 27 of file auth_cfg_wrapper.h.
Function Documentation
auth_cfg_wrapper_t* auth_cfg_wrapper_create (auth_cfg_t * auth)
Create a auth_cfg_wrapper instance.
Parameters
auth the wrapped auth info
Returns
wrapper around auth
Definition at line 206 of file auth_cfg_wrapper.c.
References destroy(), INIT, nop(), and return_null().
Referenced by METHOD().
 {
     private_auth_cfg_wrapper_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_cert_enumerator = _create_enumerator,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .destroy = _destroy,
         },
         .auth = auth,
     );
     return &this->public;
 }