strongSwan: pki
pki
Modules
command
Functions
bool get_form (char *form, cred_encoding_type_t *enc, credential_type_t type)
bool calculate_lifetime (char *format, char *nbstr, char *nastr, time_t span, time_t *nb, time_t *na)
void set_file_mode (FILE *stream, cred_encoding_type_t enc)
hash_algorithm_t get_default_digest (private_key_t *private)
Detailed Description
Function Documentation
bool calculate_lifetime (char * format, char * nbstr, char * nastr, time_t span, time_t * nb, time_t * na)
Calculate start/end lifetime for certificates.
If both nbstr and nastr are given, span is ignored. Otherwise missing arguments are calculated, or assumed to be now.
Parameters
format strptime() format, NULL for default: d.m.y T
nbstr string describing notBefore datetime, or NULL
nastr string describing notAfter datetime, or NULL
span lifetime span, from notBefore to notAfter
nb calculated notBefore time
na calculated notAfter time
Returns
TRUE of nb/na calculated successfully
See header
Definition at line 166 of file pki.c.
References convert_time(), FALSE, localtime_r(), and TRUE.
Referenced by acert(), issue(), self(), and sign_crl().
 {
     struct tm tm;
     time_t now;
     now = time(NULL);
     localtime_r(&now, &tm);
     if (nbstr)
     {
         if (!convert_time(nbstr, format, &tm))
         {
             return FALSE;
         }
     }
     *nb = mktime(&tm);
     if (*nb == -1)
     {
         return FALSE;
     }
     localtime_r(&now, &tm);
     if (nastr)
     {
         if (!convert_time(nastr, format, &tm))
         {
             return FALSE;
         }
     }
     *na = mktime(&tm);
     if (*na == -1)
     {
         return FALSE;
     }
     if (!nbstr && nastr)
     {
         *nb = *na - span;
     }
     else if (!nastr)
     {
         *na = *nb + span;
     }
     return TRUE;
 }
hash_algorithm_t get_default_digest (private_key_t * private)
Select default digest for signatures with the given key
Parameters
private private key
Returns
hash algorithm
Definition at line 243 of file pki.c.
References alg, enumerator_t::destroy, enumerator_t::enumerate, HASH_SHA256, HASH_UNKNOWN, hasher_from_signature_scheme(), private, scheme, and signature_schemes_for_key().
Referenced by acert(), issue(), req(), self(), and sign_crl().
 {
     enumerator_t *enumerator;
     signature_scheme_t scheme;
     hash_algorithm_t alg = HASH_UNKNOWN;
     enumerator = signature_schemes_for_key(private->get_type(private),
                                            private->get_keysize(private));
     if (enumerator->enumerate(enumerator, &scheme))
     {
         alg = hasher_from_signature_scheme(scheme);
     }
     enumerator->destroy(enumerator);
     /* default to SHA-256 */
     return alg == HASH_UNKNOWN ? HASH_SHA256 : alg;
 }
bool get_form (char * form, cred_encoding_type_t * enc, credential_type_t type)
Convert a form string to a encoding type
Definition at line 32 of file pki.c.
References CERT_ASN1_DER, CERT_PEM, CRED_CERTIFICATE, CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, FALSE, PRIVKEY_ASN1_DER, PRIVKEY_PEM, PRIVKEY_PGP, PUBKEY_DNSKEY, PUBKEY_PEM, PUBKEY_PGP, PUBKEY_SPKI_ASN1_DER, PUBKEY_SSHKEY, streq(), and TRUE.
Referenced by acert(), export(), gen(), issue(), pub(), req(), self(), and sign_crl().
 {
     if (streq(form, "der"))
     {
         switch (type)
         {
             case CRED_CERTIFICATE:
                 *enc = CERT_ASN1_DER;
                 return TRUE;
             case CRED_PRIVATE_KEY:
                 *enc = PRIVKEY_ASN1_DER;
                 return TRUE;
             case CRED_PUBLIC_KEY:
                 /* der encoded keys usually contain the complete
                  * SubjectPublicKeyInfo */
                 *enc = PUBKEY_SPKI_ASN1_DER;
                 return TRUE;
             default:
                 return FALSE;
         }
     }
     else if (streq(form, "pem"))
     {
         switch (type)
         {
             case CRED_CERTIFICATE:
                 *enc = CERT_PEM;
                 return TRUE;
             case CRED_PRIVATE_KEY:
                 *enc = PRIVKEY_PEM;
                 return TRUE;
             case CRED_PUBLIC_KEY:
                 *enc = PUBKEY_PEM;
                 return TRUE;
             default:
                 return FALSE;
         }
     }
     else if (streq(form, "pgp"))
     {
         switch (type)
         {
             case CRED_PRIVATE_KEY:
                 *enc = PRIVKEY_PGP;
                 return TRUE;
             case CRED_PUBLIC_KEY:
                 *enc = PUBKEY_PGP;
                 return TRUE;
             default:
                 return FALSE;
         }
     }
     else if (streq(form, "dnskey"))
     {
         switch (type)
         {
             case CRED_PUBLIC_KEY:
                 *enc = PUBKEY_DNSKEY;
                 return TRUE;
             default:
                 return FALSE;
         }
     }
     else if (streq(form, "sshkey"))
     {
         switch (type)
         {
             case CRED_PUBLIC_KEY:
                 *enc = PUBKEY_SSHKEY;
                 return TRUE;
             default:
                 return FALSE;
         }
     }
     return FALSE;
 }
void set_file_mode (FILE * stream, cred_encoding_type_t enc)
Set output file mode appropriate for credential encoding form on Windows
Definition at line 216 of file pki.c.
References CERT_PEM, PRIVKEY_PEM, and PUBKEY_PEM.
Referenced by acert(), dn(), export(), gen(), issue(), keyid(), pkcs12(), print(), pub(), req(), self(), sign_crl(), verify(), and write_to_stream().
 {
 #ifdef WIN32
     int fd;
     switch (enc)
     {
         case CERT_PEM:
         case PRIVKEY_PEM:
         case PUBKEY_PEM:
             /* keep default text mode */
             return;
         default:
             /* switch to binary mode */
             break;
     }
     fd = fileno(stream);
     if (fd != -1)
     {
         _setmode(fd, _O_BINARY);
     }
 #endif
 }