strongSwan: medcli_creds
medcli_creds
medcli
Classes
struct medcli_creds_t
Typedefs
typedef struct medcli_creds_t medcli_creds_t
Functions
medcli_creds_t * medcli_creds_create (database_t *database)
Detailed Description
Typedef Documentation
typedef struct medcli_creds_t medcli_creds_t
Definition at line 27 of file medcli_creds.h.
Function Documentation
medcli_creds_t* medcli_creds_create (database_t * db)
Create the medcli credential set.
Parameters
database underlying database
Returns
credential set implementation on that database
Described in header.
Definition at line 213 of file medcli_creds.c.
References destroy(), INIT, nop(), and return_null().
Referenced by open_database().
 {
     private_medcli_creds_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_private_enumerator = _create_private_enumerator,
                 .create_cert_enumerator = _create_cert_enumerator,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .destroy = _destroy,
         },
         .db = db,
     );
     return &this->public;
 }