strongSwan: ha_socket
ha_socket
ha
Classes
struct ha_socket_t
Typedefs
typedef struct ha_socket_t ha_socket_t
Functions
ha_socket_t * ha_socket_create (char *local, char *remote)
Detailed Description
Typedef Documentation
typedef struct ha_socket_t ha_socket_t
Definition at line 28 of file ha_socket.h.
Function Documentation
ha_socket_t* ha_socket_create (char * local, char * remote)
Create a ha_socket instance.
See header
Definition at line 199 of file ha_socket.c.
References DBG1, DBG_CFG, destroy(), HA_PORT, host_create_from_dns(), INIT, and open_socket().
Referenced by initialize_plugin().
 {
     private_ha_socket_t *this;
     INIT(this,
         .public = {
             .push = _push,
             .pull = _pull,
             .destroy = _destroy,
         },
         .local = host_create_from_dns(local, 0, HA_PORT),
         .remote = host_create_from_dns(remote, 0, HA_PORT),
         .fd = -1,
     );
     if (!this->local || !this->remote)
     {
         DBG1(DBG_CFG, "invalid local/remote HA address");
         destroy(this);
         return NULL;
     }
     if (!open_socket(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }