strongSwan: mgf1_bitspender.c File Reference
mgf1_bitspender.c File Reference
#include "mgf1_bitspender.h"
#include <crypto/mgf1/mgf1.h>
Classes
struct private_mgf1_bitspender_t
Typedefs
typedef struct
private_mgf1_bitspender_t private_mgf1_bitspender_t
Functions
METHOD (mgf1_bitspender_t, get_bits, bool, private_mgf1_bitspender_t *this, int bits_needed, uint32_t *bits)
METHOD (mgf1_bitspender_t, get_byte, bool, private_mgf1_bitspender_t *this, uint8_t *byte)
METHOD (mgf1_bitspender_t, destroy, void, private_mgf1_bitspender_t *this)
mgf1_bitspender_t * mgf1_bitspender_create (hash_algorithm_t alg, chunk_t seed, bool hash_seed)
Typedef Documentation
typedef struct private_mgf1_bitspender_t private_mgf1_bitspender_t
Definition at line 20 of file mgf1_bitspender.c.
Function Documentation
METHOD (mgf1_bitspender_t , get_bits , bool , private_mgf1_bitspender_t * this, int bits_needed, uint32_t * bits)
Definition at line 78 of file mgf1_bitspender.c.
References bits, FALSE, TRUE, and untoh32().
 {
     int bits_now;
     *bits = 0x00000000;
     if (bits_needed == 0)
     {
         /* trivial */
         return TRUE;
     }
     if (bits_needed > 32)
     {
         /* too many bits requested */
         return FALSE;
     }
     while (bits_needed)
     {
         if (this->bits_left == 0)
         {
             if (this->octets_left == 0)
             {
                 /* get another block from MGF1 */
                 if (!this->mgf1->get_mask(this->mgf1, this->hash_len,
                                                       this->octets))
                 {
                     /* no block available */
                     return FALSE;
                 }
                 this->octets_left = this->hash_len;
                 this->octets_count += this->hash_len;
             }
             this->bits = untoh32(this->octets + this->hash_len -
                                                 this->octets_left);
             this->bits_left = 32;
             this->octets_left -= 4;
         }
         if (bits_needed > this->bits_left)
         {
             bits_now = this->bits_left;
             this->bits_left = 0;
             bits_needed -= bits_now;
         }
         else
         {
             bits_now = bits_needed;
             this->bits_left -= bits_needed;
             bits_needed = 0;
         }
         if (bits_now == 32)
         {
             *bits = this->bits;
         }
         else
         {
             *bits <<= bits_now;
             *bits |= this->bits >> this->bits_left;
             if (this->bits_left)
             {
                 this->bits &= 0xffffffff >> (32 - this->bits_left);
             }
         }
     }
     return TRUE;
 }
METHOD (mgf1_bitspender_t , get_byte , bool , private_mgf1_bitspender_t * this, uint8_t * byte)
Definition at line 146 of file mgf1_bitspender.c.
References bytes, FALSE, memcpy, and TRUE.
 {
     if (this->bytes_left == 0)
     {
         if (this->octets_left == 0)
         {
             /* get another block from MGF1 */
             if (!this->mgf1->get_mask(this->mgf1, this->hash_len, this->octets))
             {
                 /* no block available */
                 return FALSE;
             }
             this->octets_left = this->hash_len;
             this->octets_count += this->hash_len;
         }
         memcpy(this->bytes, this->octets + this->hash_len - this->octets_left, 4);
         this->bytes_left = 4;
         this->octets_left -= 4;
     }
     *byte = this->bytes[4 - this->bytes_left--];
     return TRUE;
 }
METHOD (mgf1_bitspender_t , destroy , void , private_mgf1_bitspender_t * this)
Definition at line 171 of file mgf1_bitspender.c.
References DBG2, DBG_LIB, free(), and memwipe().
 {
     DBG2(DBG_LIB, "mgf1 generated %u octets", this->octets_count);
     memwipe(this->octets, sizeof(this->octets));
     this->mgf1->destroy(this->mgf1);
     free(this);
 }