strongSwan: eap_dynamic.c File Reference
eap_dynamic.c File Reference
#include "eap_dynamic.h"
#include <daemon.h>
#include <library.h>
Classes
struct private_eap_dynamic_t
Typedefs
typedef struct
private_eap_dynamic_t private_eap_dynamic_t
Functions
static bool entry_matches (eap_vendor_type_t *item, eap_vendor_type_t *other)
static eap_method_t * load_method (private_eap_dynamic_t *this, eap_type_t type, u_int32_t vendor)
static void select_method (private_eap_dynamic_t *this)
METHOD (eap_method_t, initiate, status_t, private_eap_dynamic_t *this, eap_payload_t **out)
METHOD (eap_method_t, process, status_t, private_eap_dynamic_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_dynamic_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_dynamic_t *this, chunk_t *msk)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_dynamic_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_dynamic_t *this, u_int8_t identifier)
METHOD (eap_method_t, is_mutual, bool, private_eap_dynamic_t *this)
METHOD (eap_method_t, destroy, void, private_eap_dynamic_t *this)
static void handle_preferred_eap_types (private_eap_dynamic_t *this, char *methods)
static void get_supported_eap_types (private_eap_dynamic_t *this)
eap_dynamic_t * eap_dynamic_create (identification_t *server, identification_t *peer)
Typedef Documentation
typedef struct private_eap_dynamic_t private_eap_dynamic_t
Definition at line 21 of file eap_dynamic.c.
Function Documentation
static bool entry_matches (eap_vendor_type_t * item, eap_vendor_type_t * other) static
Compare two eap_vendor_type_t objects
Definition at line 67 of file eap_dynamic.c.
References eap_vendor_type_t::type, and eap_vendor_type_t::vendor.
Referenced by handle_preferred_eap_types(), and select_method().
 {
     return item->type == other->type && item->vendor == other->vendor;
 }
static void get_supported_eap_types (private_eap_dynamic_t * this) static
Get all supported EAP methods
Definition at line 334 of file eap_dynamic.c.
References charon, eap_manager_t::create_enumerator, enumerator_t::destroy, daemon_t::eap, EAP_SERVER, enumerator_t::enumerate, INIT, and type.
Referenced by eap_dynamic_create().
 {
     enumerator_t *enumerator;
     eap_type_t type;
     u_int32_t vendor;
     enumerator = charon->eap->create_enumerator(charon->eap, EAP_SERVER);
     while (enumerator->enumerate(enumerator, &type, &vendor))
     {
         eap_vendor_type_t *entry;
         INIT(entry,
             .type = type,
             .vendor = vendor,
         );
         this->types->insert_last(this->types, entry);
     }
     enumerator->destroy(enumerator);
 }
static void handle_preferred_eap_types (private_eap_dynamic_t * this, char * methods) static
Parse preferred EAP types
Definition at line 291 of file eap_dynamic.c.
References enumerator_t::destroy, linked_list_t::destroy, eap_vendor_type_from_string(), entry_matches(), enumerator_t::enumerate, enumerator_create_token(), free(), linked_list_t::insert_last, linked_list_create(), linked_list_t::remove_last, SUCCESS, and type.
Referenced by eap_dynamic_create().
 {
     enumerator_t *enumerator;
     eap_vendor_type_t *type, *entry;
     linked_list_t *preferred;
     char *method;
     /* parse preferred EAP methods, format: type[-vendor], ... */
     preferred = linked_list_create();
     enumerator = enumerator_create_token(methods, ",", " ");
     while (enumerator->enumerate(enumerator, &method))
     {
         type = eap_vendor_type_from_string(method);
         if (type)
         {
             preferred->insert_last(preferred, type);
         }
     }
     enumerator->destroy(enumerator);
     enumerator = this->types->create_enumerator(this->types);
     while (preferred->remove_last(preferred, (void**)&type) == SUCCESS)
     {   /* move (supported) types to the front, maintain the preferred order */
         this->types->reset_enumerator(this->types, enumerator);
         while (enumerator->enumerate(enumerator, &entry))
         {
             if (entry_matches(entry, type))
             {
                 this->types->remove_at(this->types, enumerator);
                 this->types->insert_first(this->types, entry);
                 break;
             }
         }
         free(type);
     }
     enumerator->destroy(enumerator);
     preferred->destroy(preferred);
 }
static eap_method_t* load_method (private_eap_dynamic_t * this, eap_type_t type, u_int32_t vendor) static
Load the given EAP method
Definition at line 75 of file eap_dynamic.c.
References charon, eap_manager_t::create_instance, DBG1, DBG_IKE, daemon_t::eap, EAP_SERVER, and eap_type_names.
Referenced by select_method().
 {
     eap_method_t *method;
     method = charon->eap->create_instance(charon->eap, type, vendor, EAP_SERVER,
                                           this->server, this->peer);
     if (!method)
     {
         if (vendor)
         {
             DBG1(DBG_IKE, "loading vendor specific EAP method %d-%d failed",
                  type, vendor);
         }
         else
         {
             DBG1(DBG_IKE, "loading %N method failed", eap_type_names, type);
         }
     }
     return method;
 }
METHOD (eap_method_t , initiate , status_t , private_eap_dynamic_t * this, eap_payload_t ** out)
Definition at line 155 of file eap_dynamic.c.
References DBG1, DBG_IKE, FAILED, and select_method().
 {
     if (!this->method)
     {
         select_method(this);
         if (!this->method)
         {
             DBG1(DBG_IKE, "no supported EAP method found");
             return FAILED;
         }
     }
     return this->method->initiate(this->method, out);
 }
METHOD (eap_method_t , process , status_t , private_eap_dynamic_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 170 of file eap_dynamic.c.
References DBG1, DBG_IKE, enumerator_t::destroy, EAP_NAK, eap_type_names, enumerator_t::enumerate, FAILED, eap_payload_t::get_type, eap_payload_t::get_types, INIT, initiate(), linked_list_create(), and type.
 {
     eap_type_t received_type, type;
     u_int32_t received_vendor, vendor;
     received_type = in->get_type(in, &received_vendor);
     if (received_vendor == 0 && received_type == EAP_NAK)
     {
         enumerator_t *enumerator;
         DBG1(DBG_IKE, "received %N, selecting a different EAP method",
              eap_type_names, EAP_NAK);
         if (this->other_types)
         {   /* we already received a Nak or a proper response before */
             DBG1(DBG_IKE, "%N is not supported in this state", eap_type_names,
                  EAP_NAK);
             return FAILED;
         }
         this->other_types = linked_list_create();
         enumerator = in->get_types(in);
         while (enumerator->enumerate(enumerator, &type, &vendor))
         {
             eap_vendor_type_t *entry;
             if (!type)
             {
                 DBG1(DBG_IKE, "peer does not support any other EAP methods");
                 enumerator->destroy(enumerator);
                 return FAILED;
             }
             INIT(entry,
                 .type = type,
                 .vendor = vendor,
             );
             this->other_types->insert_last(this->other_types, entry);
         }
         enumerator->destroy(enumerator);
         /* restart with a different method */
         this->method->destroy(this->method);
         this->method = NULL;
         return initiate(this, out);
     }
     if (!this->other_types)
     {   /* so we don't handle EAP-Naks later */
         this->other_types = linked_list_create();
     }
     if (this->method)
     {
         return this->method->process(this->method, in, out);
     }
     return FAILED;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_dynamic_t * this, u_int32_t * vendor)
Definition at line 227 of file eap_dynamic.c.
References EAP_DYNAMIC.
 {
     if (this->method)
     {
         return this->method->get_type(this->method, vendor);
     }
     *vendor = 0;
     return EAP_DYNAMIC;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_dynamic_t * this, chunk_t * msk)
Definition at line 238 of file eap_dynamic.c.
References FAILED.
 {
     if (this->method)
     {
         return this->method->get_msk(this->method, msk);
     }
     return FAILED;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_dynamic_t * this)
Definition at line 248 of file eap_dynamic.c.
 {
     if (this->method)
     {
         return this->method->get_identifier(this->method);
     }
     return 0;
 }
METHOD (eap_method_t , set_identifier , void , private_eap_dynamic_t * this, u_int8_t identifier)
Definition at line 258 of file eap_dynamic.c.
 {
     if (this->method)
     {
         this->method->set_identifier(this->method, identifier);
     }
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_dynamic_t * this)
Definition at line 267 of file eap_dynamic.c.
References FALSE.
 {
     if (this->method)
     {
         return this->method->is_mutual(this->method);
     }
     return FALSE;
 }
METHOD (eap_method_t , destroy , void , private_eap_dynamic_t * this)
Definition at line 277 of file eap_dynamic.c.
References DESTROY_FUNCTION_IF, DESTROY_IF, free(), and server.
 {
     DESTROY_IF(this->method);
     this->types->destroy_function(this->types, (void*)free);
     DESTROY_FUNCTION_IF(this->other_types, (void*)free);
     this->server->destroy(this->server);
     this->peer->destroy(this->peer);
     free(this);
 }
static void select_method (private_eap_dynamic_t * this) static
Select the first method we can instantiate and is supported by both peers.
Definition at line 100 of file eap_dynamic.c.
References DBG1, DBG2, DBG_IKE, eap_type_names, entry_matches(), free(), load_method(), linked_list_t::remove_first, SUCCESS, eap_vendor_type_t::type, and eap_vendor_type_t::vendor.
Referenced by METHOD().
 {
     eap_vendor_type_t *entry;
     linked_list_t *outer = this->types, *inner = this->other_types;
     char *who = "peer";
     if (this->other_types && this->prefer_peer)
     {
         outer = this->other_types;
         inner = this->types;
         who = "us";
     }
     while (outer->remove_first(outer, (void*)&entry) == SUCCESS)
     {
         if (inner)
         {
             if (inner->find_first(inner, (void*)entry_matches,
                                   NULL, entry) != SUCCESS)
             {
                 if (entry->vendor)
                 {
                     DBG2(DBG_IKE, "proposed vendor specific EAP method %d-%d "
                          "not supported by %s, skipped", entry->type,
                           entry->vendor, who);
                 }
                 else
                 {
                     DBG2(DBG_IKE, "proposed %N method not supported by %s, "
                          "skipped", eap_type_names, entry->type, who);
                 }
                 free(entry);
                 continue;
             }
         }
         this->method = load_method(this, entry->type, entry->vendor);
         if (this->method)
         {
             if (entry->vendor)
             {
                 DBG1(DBG_IKE, "vendor specific EAP method %d-%d selected",
                      entry->type, entry->vendor);
             }
             else
             {
                 DBG1(DBG_IKE, "%N method selected", eap_type_names,
                      entry->type);
             }
             free(entry);
             break;
         }
         free(entry);
     }
 }