strongSwan: xauth_manager
xauth_manager
xauth
Classes
struct xauth_manager_t
Typedefs
typedef struct xauth_manager_t xauth_manager_t
Functions
xauth_manager_t * xauth_manager_create ()
Detailed Description
Typedef Documentation
typedef struct xauth_manager_t xauth_manager_t
Definition at line 26 of file xauth_manager.h.
Function Documentation
xauth_manager_t* xauth_manager_create ()
Create a eap_manager instance.
Definition at line 162 of file xauth_manager.c.
References INIT, linked_list_create(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by daemon_create().
 {
     private_xauth_manager_t *this;
     INIT(this,
         .public = {
             .add_method = _add_method,
             .remove_method = _remove_method,
             .create_instance = _create_instance,
             .destroy = _destroy,
         },
         .methods = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return &this->public;
 }