strongSwan: quick_mode.c File Reference
quick_mode.c File Reference
#include "quick_mode.h"
#include <string.h>
#include <daemon.h>
#include <sa/ikev1/keymat_v1.h>
#include <encoding/payloads/sa_payload.h>
#include <encoding/payloads/nonce_payload.h>
#include <encoding/payloads/ke_payload.h>
#include <encoding/payloads/id_payload.h>
#include <encoding/payloads/payload.h>
#include <sa/ikev1/tasks/informational.h>
#include <sa/ikev1/tasks/quick_delete.h>
#include <processing/jobs/inactivity_job.h>
Classes
struct private_quick_mode_t
Typedefs
typedef struct private_quick_mode_t private_quick_mode_t
Functions
static void schedule_inactivity_timeout (private_quick_mode_t *this)
static bool have_pool (ike_sa_t *ike_sa)
static linked_list_t * get_dynamic_hosts (ike_sa_t *ike_sa, bool local)
static bool install (private_quick_mode_t *this)
static bool add_nonce (private_quick_mode_t *this, chunk_t *nonce, message_t *message)
static bool get_nonce (private_quick_mode_t *this, chunk_t *nonce, message_t *message)
static bool add_ke (private_quick_mode_t *this, message_t *message)
static bool get_ke (private_quick_mode_t *this, message_t *message)
static traffic_selector_t * select_ts (private_quick_mode_t *this, bool local, linked_list_t *supplied)
static void add_ts (private_quick_mode_t *this, message_t *message)
static bool get_ts (private_quick_mode_t *this, message_t *message)
static encap_t get_encap (ike_sa_t *ike_sa, bool udp)
static payload_type_t get_nat_oa_payload_type (ike_sa_t *ike_sa)
static void add_nat_oa_payloads (private_quick_mode_t *this, message_t *message)
static void get_lifetimes (private_quick_mode_t *this)
static void apply_lifetimes (private_quick_mode_t *this, sa_payload_t *sa_payload)
static status_t send_notify (private_quick_mode_t *this, notify_type_t type)
static linked_list_t * get_proposals (private_quick_mode_t *this, diffie_hellman_group_t group)
METHOD (task_t, build_i, status_t, private_quick_mode_t *this, message_t *message)
static bool has_notify_errors (private_quick_mode_t *this, message_t *message)
static void check_for_rekeyed_child (private_quick_mode_t *this)
METHOD (task_t, process_r, status_t, private_quick_mode_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_quick_mode_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_quick_mode_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_quick_mode_t *this)
METHOD (quick_mode_t, get_mid, u_int32_t, private_quick_mode_t *this)
METHOD (quick_mode_t, use_reqid, void, private_quick_mode_t *this, u_int32_t reqid)
METHOD (quick_mode_t, use_marks, void, private_quick_mode_t *this, u_int in, u_int out)
METHOD (quick_mode_t, rekey, void, private_quick_mode_t *this, u_int32_t spi)
METHOD (task_t, migrate, void, private_quick_mode_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_quick_mode_t *this)
quick_mode_t * quick_mode_create (ike_sa_t *ike_sa, child_cfg_t *config, traffic_selector_t *tsi, traffic_selector_t *tsr)
Typedef Documentation
typedef struct private_quick_mode_t private_quick_mode_t
Definition at line 56 of file quick_mode.c.
Function Documentation
static bool add_ke (private_quick_mode_t * this, message_t * message) static
Add KE payload to message
Definition at line 473 of file quick_mode.c.
References message_t::add_payload, DBG1, DBG_IKE, dh, FALSE, ke_payload_create_from_diffie_hellman(), ke_payload_t::payload_interface, PLV1_KEY_EXCHANGE, and TRUE.
Referenced by METHOD().
 {
     ke_payload_t *ke_payload;
     ke_payload = ke_payload_create_from_diffie_hellman(PLV1_KEY_EXCHANGE,
                                                        this->dh);
     if (!ke_payload)
     {
         DBG1(DBG_IKE, "creating KE payload failed");
         return FALSE;
     }
     message->add_payload(message, &ke_payload->payload_interface);
     return TRUE;
 }
static void add_nat_oa_payloads (private_quick_mode_t * this, message_t * message) static
Add NAT-OA payloads
Definition at line 676 of file quick_mode.c.
References message_t::add_payload, dst, message_t::get_destination, get_nat_oa_payload_type(), host_t::get_sockaddr, message_t::get_source, id, id_payload_create_from_identification(), identification_create_from_sockaddr(), initiator, and src.
Referenced by METHOD().
 {
     identification_t *id;
     id_payload_t *nat_oa;
     host_t *src, *dst;
     payload_type_t nat_oa_payload_type;
     src = message->get_source(message);
     dst = message->get_destination(message);
     src = this->initiator ? src : dst;
     dst = this->initiator ? dst : src;
     nat_oa_payload_type = get_nat_oa_payload_type(this->ike_sa);
     /* first NAT-OA is the initiator's address */
     id = identification_create_from_sockaddr(src->get_sockaddr(src));
     nat_oa = id_payload_create_from_identification(nat_oa_payload_type, id);
     message->add_payload(message, (payload_t*)nat_oa);
     id->destroy(id);
     /* second NAT-OA is that of the responder */
     id = identification_create_from_sockaddr(dst->get_sockaddr(dst));
     nat_oa = id_payload_create_from_identification(nat_oa_payload_type, id);
     message->add_payload(message, (payload_t*)nat_oa);
     id->destroy(id);
 }
static bool add_nonce (private_quick_mode_t * this, chunk_t * nonce, message_t * message) static
Generate and add NONCE
Definition at line 424 of file quick_mode.c.
References message_t::add_payload, nonce_gen_t::allocate_nonce, DBG1, DBG_IKE, nonce_gen_t::destroy, FALSE, nonce_payload_create(), NONCE_SIZE, nonce_payload_t::payload_interface, PLV1_NONCE, nonce_payload_t::set_nonce, and TRUE.
Referenced by METHOD().
 {
     nonce_payload_t *nonce_payload;
     nonce_gen_t *nonceg;
     nonceg = this->keymat->keymat.create_nonce_gen(&this->keymat->keymat);
     if (!nonceg)
     {
         DBG1(DBG_IKE, "no nonce generator found to create nonce");
         return FALSE;
     }
     if (!nonceg->allocate_nonce(nonceg, NONCE_SIZE, nonce))
     {
         DBG1(DBG_IKE, "nonce allocation failed");
         nonceg->destroy(nonceg);
         return FALSE;
     }
     nonceg->destroy(nonceg);
     nonce_payload = nonce_payload_create(PLV1_NONCE);
     nonce_payload->set_nonce(nonce_payload, *nonce);
     message->add_payload(message, &nonce_payload->payload_interface);
     return TRUE;
 }
static void add_ts (private_quick_mode_t * this, message_t * message) static
Add selected traffic selectors to message
Definition at line 540 of file quick_mode.c.
References message_t::add_payload, id_payload_create_from_ts(), and id_payload_t::payload_interface.
Referenced by METHOD().
 {
     id_payload_t *id_payload;
     id_payload = id_payload_create_from_ts(this->tsi);
     message->add_payload(message, &id_payload->payload_interface);
     id_payload = id_payload_create_from_ts(this->tsr);
     message->add_payload(message, &id_payload->payload_interface);
 }
static void apply_lifetimes (private_quick_mode_t * this, sa_payload_t * sa_payload) static
Check and apply lifetimes
Definition at line 726 of file quick_mode.c.
References DBG1, DBG_IKE, sa_payload_t::get_lifebytes, and sa_payload_t::get_lifetime.
Referenced by METHOD().
 {
     u_int32_t lifetime;
     u_int64_t lifebytes;
     lifetime = sa_payload->get_lifetime(sa_payload);
     lifebytes = sa_payload->get_lifebytes(sa_payload);
     if (this->lifetime != lifetime)
     {
         DBG1(DBG_IKE, "received %us lifetime, configured %us",
              lifetime, this->lifetime);
         this->lifetime = lifetime;
     }
     if (this->lifebytes != lifebytes)
     {
         DBG1(DBG_IKE, "received %llu lifebytes, configured %llu",
              lifebytes, this->lifebytes);
         this->lifebytes = lifebytes;
     }
 }
static void check_for_rekeyed_child (private_quick_mode_t * this) static
Check if this is a rekey for an existing CHILD_SA, reuse reqid if so
Definition at line 977 of file quick_mode.c.
References CHILD_INSTALLED, CHILD_REKEYED, CHILD_REKEYING, child_sa_t::create_policy_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, proposal_t::equals, traffic_selector_t::equals, FALSE, child_sa_t::get_mark, child_sa_t::get_name, child_sa_t::get_proposal, child_sa_t::get_reqid, child_sa_t::get_spi, child_sa_t::get_state, child_sa_t::get_unique_id, name, proposal, child_sa_t::set_state, streq(), TRUE, and mark_t::value.
Referenced by METHOD().
 {
     enumerator_t *enumerator, *policies;
     traffic_selector_t *local, *remote;
     child_sa_t *child_sa;
     proposal_t *proposal;
     char *name;
     name = this->config->get_name(this->config);
     enumerator = this->ike_sa->create_child_sa_enumerator(this->ike_sa);
     while (this->reqid == 0 && enumerator->enumerate(enumerator, &child_sa))
     {
         if (streq(child_sa->get_name(child_sa), name))
         {
             proposal = child_sa->get_proposal(child_sa);
             switch (child_sa->get_state(child_sa))
             {
                 case CHILD_INSTALLED:
                 case CHILD_REKEYING:
                 case CHILD_REKEYED:
                     policies = child_sa->create_policy_enumerator(child_sa);
                     if (policies->enumerate(policies, &local, &remote) &&
                         local->equals(local, this->tsr) &&
                         remote->equals(remote, this->tsi) &&
                         this->proposal->equals(this->proposal, proposal))
                     {
                         this->reqid = child_sa->get_reqid(child_sa);
                         this->rekey = child_sa->get_spi(child_sa, TRUE);
                         this->mark_in = child_sa->get_mark(child_sa,
                                                             TRUE).value;
                         this->mark_out = child_sa->get_mark(child_sa,
                                                             FALSE).value;
                         child_sa->set_state(child_sa, CHILD_REKEYING);
                         DBG1(DBG_IKE, "detected rekeying of CHILD_SA %s{%u}",
                              child_sa->get_name(child_sa),
                              child_sa->get_unique_id(child_sa));
                     }
                     policies->destroy(policies);
                 break;
             default:
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
 }
static linked_list_t* get_dynamic_hosts (ike_sa_t * ike_sa, bool local) static
Get hosts to use for dynamic traffic selectors
Definition at line 245 of file quick_mode.c.
References ike_sa_t::create_virtual_ip_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, ike_sa_t::get_my_host, ike_sa_t::get_other_host, have_pool(), host, linked_list_t::insert_last, linked_list_create(), and list.
Referenced by METHOD(), and select_ts().
 {
     enumerator_t *enumerator;
     linked_list_t *list;
     host_t *host;
     list = linked_list_create();
     enumerator = ike_sa->create_virtual_ip_enumerator(ike_sa, local);
     while (enumerator->enumerate(enumerator, &host))
     {
         list->insert_last(list, host);
     }
     enumerator->destroy(enumerator);
     if (list->get_count(list) == 0)
     {   /* no virtual IPs assigned */
         if (local)
         {
             host = ike_sa->get_my_host(ike_sa);
             list->insert_last(list, host);
         }
         else if (!have_pool(ike_sa))
         {   /* use host only if we don't have a pool configured */
             host = ike_sa->get_other_host(ike_sa);
             list->insert_last(list, host);
         }
     }
     return list;
 }
static encap_t get_encap (ike_sa_t * ike_sa, bool udp) static
Get encap
Definition at line 648 of file quick_mode.c.
References ENCAP_NONE, ENCAP_UDP, ENCAP_UDP_DRAFT_00_03, EXT_NATT_DRAFT_02_03, and ike_sa_t::supports_extension.
Referenced by METHOD().
 {
     if (!udp)
     {
         return ENCAP_NONE;
     }
     if (ike_sa->supports_extension(ike_sa, EXT_NATT_DRAFT_02_03))
     {
         return ENCAP_UDP_DRAFT_00_03;
     }
     return ENCAP_UDP;
 }
static bool get_ke (private_quick_mode_t * this, message_t * message) static
Get DH value from a KE payload
Definition at line 491 of file quick_mode.c.
References DBG1, DBG_IKE, dh, FALSE, ke_payload_t::get_key_exchange_data, message_t::get_payload, PLV1_KEY_EXCHANGE, and TRUE.
Referenced by METHOD().
 {
     ke_payload_t *ke_payload;
     ke_payload = (ke_payload_t*)message->get_payload(message, PLV1_KEY_EXCHANGE);
     if (!ke_payload)
     {
         DBG1(DBG_IKE, "KE payload missing");
         return FALSE;
     }
     if (!this->dh->set_other_public_value(this->dh,
                                 ke_payload->get_key_exchange_data(ke_payload)))
     {
         DBG1(DBG_IKE, "unable to apply received KE value");
         return FALSE;
     }
     return TRUE;
 }
static void get_lifetimes (private_quick_mode_t * this) static
Look up lifetimes
Definition at line 707 of file quick_mode.c.
References lifetime_cfg_t::bytes, free(), lifetime_cfg_t::life, and lifetime_cfg_t::time.
Referenced by METHOD().
 {
     lifetime_cfg_t *lft;
     lft = this->config->get_lifetime(this->config);
     if (lft->time.life)
     {
         this->lifetime = lft->time.life;
     }
     else if (lft->bytes.life)
     {
         this->lifebytes = lft->bytes.life;
     }
     free(lft);
 }
static payload_type_t get_nat_oa_payload_type (ike_sa_t * ike_sa) static
Get NAT-OA payload type (RFC 3947 or RFC 3947 drafts).
Definition at line 664 of file quick_mode.c.
References EXT_NATT_DRAFT_02_03, PLV1_NAT_OA, PLV1_NAT_OA_DRAFT_00_03, and ike_sa_t::supports_extension.
Referenced by add_nat_oa_payloads().
 {
     if (ike_sa->supports_extension(ike_sa, EXT_NATT_DRAFT_02_03))
     {
         return PLV1_NAT_OA_DRAFT_00_03;
     }
     return PLV1_NAT_OA;
 }
static bool get_nonce (private_quick_mode_t * this, chunk_t * nonce, message_t * message) static
Extract nonce from NONCE payload
Definition at line 454 of file quick_mode.c.
References DBG1, DBG_IKE, FALSE, nonce_payload_t::get_nonce, message_t::get_payload, PLV1_NONCE, and TRUE.
Referenced by METHOD().
 {
     nonce_payload_t *nonce_payload;
     nonce_payload = (nonce_payload_t*)message->get_payload(message, PLV1_NONCE);
     if (!nonce_payload)
     {
         DBG1(DBG_IKE, "NONCE payload missing in message");
         return FALSE;
     }
     *nonce = nonce_payload->get_nonce(nonce_payload);
     return TRUE;
 }
static linked_list_t* get_proposals (private_quick_mode_t * this, diffie_hellman_group_t group) static
Prepare a list of proposals from child_config containing only the specified DH group, unless it is set to MODP_NONE.
Definition at line 770 of file quick_mode.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, proposal_t::destroy, enumerator_t::enumerate, FALSE, proposal_t::has_dh_group, list, MODP_NONE, proposal, linked_list_t::remove_at, proposal_t::set_spi, and proposal_t::strip_dh.
Referenced by METHOD().
 {
     linked_list_t *list;
     proposal_t *proposal;
     enumerator_t *enumerator;
     list = this->config->get_proposals(this->config, FALSE);
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &proposal))
     {
         if (group != MODP_NONE)
         {
             if (!proposal->has_dh_group(proposal, group))
             {
                 list->remove_at(list, enumerator);
                 proposal->destroy(proposal);
                 continue;
             }
             proposal->strip_dh(proposal, group);
         }
         proposal->set_spi(proposal, this->spi_i);
     }
     enumerator->destroy(enumerator);
     return list;
 }
static bool get_ts (private_quick_mode_t * this, message_t * message) static
Get traffic selectors from received message
Definition at line 553 of file quick_mode.c.
References host_t::clone, message_t::create_payload_enumerator, DBG1, DBG2, DBG_IKE, enumerator_t::destroy, traffic_selector_t::destroy, DESTROY_IF, enumerator_t::enumerate, FALSE, host_t::get_family, traffic_selector_t::get_subset, id_payload_t::get_ts, payload_t::get_type, initiator, traffic_selector_t::is_host, MODE_TRANSPORT, PLV1_ID, traffic_selector_t::set_address, traffic_selector_create_from_subnet(), and TRUE.
Referenced by METHOD().
 {
     traffic_selector_t *tsi = NULL, *tsr = NULL;
     enumerator_t *enumerator;
     id_payload_t *id_payload;
     payload_t *payload;
     host_t *hsi, *hsr;
     bool first = TRUE;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV1_ID)
         {
             id_payload = (id_payload_t*)payload;
             if (first)
             {
                 tsi = id_payload->get_ts(id_payload);
                 first = FALSE;
             }
             else
             {
                 tsr = id_payload->get_ts(id_payload);
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     /* create host2host selectors if ID payloads missing */
     if (this->initiator)
     {
         hsi = this->ike_sa->get_my_host(this->ike_sa);
         hsr = this->ike_sa->get_other_host(this->ike_sa);
     }
     else
     {
         hsr = this->ike_sa->get_my_host(this->ike_sa);
         hsi = this->ike_sa->get_other_host(this->ike_sa);
     }
     if (!tsi)
     {
         tsi = traffic_selector_create_from_subnet(hsi->clone(hsi),
                     hsi->get_family(hsi) == AF_INET ? 32 : 128, 0, 0, 65535);
     }
     if (!tsr)
     {
         tsr = traffic_selector_create_from_subnet(hsr->clone(hsr),
                     hsr->get_family(hsr) == AF_INET ? 32 : 128, 0, 0, 65535);
     }
     if (this->mode == MODE_TRANSPORT && this->udp &&
        (!tsi->is_host(tsi, hsi) || !tsr->is_host(tsr, hsr)))
     {   /* change TS in case of a NAT in transport mode */
         DBG2(DBG_IKE, "changing received traffic selectors %R=== %R due to NAT",
              tsi, tsr);
         tsi->set_address(tsi, hsi);
         tsr->set_address(tsr, hsr);
     }
     if (this->initiator)
     {
         traffic_selector_t *tsisub, *tsrsub;
         /* check if peer selection is valid */
         tsisub = this->tsi->get_subset(this->tsi, tsi);
         tsrsub = this->tsr->get_subset(this->tsr, tsr);
         if (!tsisub || !tsrsub)
         {
             DBG1(DBG_IKE, "peer selected invalid traffic selectors: "
                  "%R for %R, %R for %R", tsi, this->tsi, tsr, this->tsr);
             DESTROY_IF(tsisub);
             DESTROY_IF(tsrsub);
             tsi->destroy(tsi);
             tsr->destroy(tsr);
             return FALSE;
         }
         tsi->destroy(tsi);
         tsr->destroy(tsr);
         this->tsi->destroy(this->tsi);
         this->tsr->destroy(this->tsr);
         this->tsi = tsisub;
         this->tsr = tsrsub;
     }
     else
     {
         this->tsi = tsi;
         this->tsr = tsr;
     }
     return TRUE;
 }
static bool has_notify_errors (private_quick_mode_t * this, message_t * message) static
Check for notify errors, return TRUE if error found
Definition at line 940 of file quick_mode.c.
References message_t::create_payload_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, notify_payload_t::get_notify_type, payload_t::get_type, notify(), notify_type_names, PLV1_NOTIFY, TRUE, and type.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     bool err = FALSE;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV1_NOTIFY)
         {
             notify_payload_t *notify;
             notify_type_t type;
             notify = (notify_payload_t*)payload;
             type = notify->get_notify_type(notify);
             if (type < 16384)
             {
                 DBG1(DBG_IKE, "received %N error notify",
                      notify_type_names, type);
                 err = TRUE;
             }
             else
             {
                 DBG1(DBG_IKE, "received %N notify", notify_type_names, type);
             }
         }
     }
     enumerator->destroy(enumerator);
     return err;
 }
static bool have_pool (ike_sa_t * ike_sa) static
Check if we have a an address pool configured
Definition at line 222 of file quick_mode.c.
References peer_cfg_t::create_pool_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, ike_sa_t::get_peer_cfg, and TRUE.
Referenced by get_dynamic_hosts().
 {
     enumerator_t *enumerator;
     peer_cfg_t *peer_cfg;
     char *pool;
     bool found = FALSE;
     peer_cfg = ike_sa->get_peer_cfg(ike_sa);
     if (peer_cfg)
     {
         enumerator = peer_cfg->create_pool_enumerator(peer_cfg);
         if (enumerator->enumerate(enumerator, &pool))
         {
             found = TRUE;
         }
         enumerator->destroy(enumerator);
     }
     return found;
 }
static bool install (private_quick_mode_t * this) static
Install negotiated CHILD_SA
Definition at line 278 of file quick_mode.c.
References daemon_t::bus, charon, CHILD_INSTALLED, CHILD_INSTALLING, bus_t::child_keys, bus_t::child_rekey, CHILD_REKEYED, bus_t::child_updown, chunk_clear(), chunk_empty, DBG0, DBG1, DBG_IKE, linked_list_t::destroy, destroy(), linked_list_t::destroy_offset, FAILED, FALSE, linked_list_t::get_count, initiator, IPCOMP_DEFLATE, linked_list_create_from_enumerator(), linked_list_create_with_items(), bus_t::narrow, NARROW_INITIATOR_POST_AUTH, NARROW_RESPONDER_POST, proposal, schedule_inactivity_timeout(), child_sa_t::set_proposal, child_sa_t::set_state, status, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     status_t status, status_i, status_o;
     chunk_t encr_i, encr_r, integ_i, integ_r;
     linked_list_t *tsi, *tsr, *my_ts, *other_ts;
     child_sa_t *old = NULL;
     this->child_sa->set_proposal(this->child_sa, this->proposal);
     this->child_sa->set_state(this->child_sa, CHILD_INSTALLING);
     this->child_sa->set_mode(this->child_sa, this->mode);
     if (this->cpi_i && this->cpi_r)
     {   /* DEFLATE is the only transform we currently support */
         this->child_sa->set_ipcomp(this->child_sa, IPCOMP_DEFLATE);
     }
     else
     {
         this->cpi_i = this->cpi_r = 0;
     }
     this->child_sa->set_protocol(this->child_sa,
                                  this->proposal->get_protocol(this->proposal));
     status_i = status_o = FAILED;
     encr_i = encr_r = integ_i = integ_r = chunk_empty;
     tsi = linked_list_create_with_items(this->tsi->clone(this->tsi), NULL);
     tsr = linked_list_create_with_items(this->tsr->clone(this->tsr), NULL);
     if (this->initiator)
     {
         charon->bus->narrow(charon->bus, this->child_sa,
                             NARROW_INITIATOR_POST_AUTH, tsi, tsr);
     }
     else
     {
         charon->bus->narrow(charon->bus, this->child_sa,
                             NARROW_RESPONDER_POST, tsr, tsi);
     }
     if (tsi->get_count(tsi) == 0 || tsr->get_count(tsr) == 0)
     {
         tsi->destroy_offset(tsi, offsetof(traffic_selector_t, destroy));
         tsr->destroy_offset(tsr, offsetof(traffic_selector_t, destroy));
         DBG1(DBG_IKE, "no acceptable traffic selectors found");
         return FALSE;
     }
     if (this->keymat->derive_child_keys(this->keymat, this->proposal, this->dh,
                         this->spi_i, this->spi_r, this->nonce_i, this->nonce_r,
                         &encr_i, &integ_i, &encr_r, &integ_r))
     {
         if (this->initiator)
         {
             status_i = this->child_sa->install(this->child_sa,
                                     encr_r, integ_r, this->spi_i, this->cpi_i,
                                     this->initiator, TRUE, FALSE, tsi, tsr);
             status_o = this->child_sa->install(this->child_sa,
                                     encr_i, integ_i, this->spi_r, this->cpi_r,
                                     this->initiator, FALSE, FALSE, tsi, tsr);
         }
         else
         {
             status_i = this->child_sa->install(this->child_sa,
                                     encr_i, integ_i, this->spi_r, this->cpi_r,
                                     this->initiator, TRUE, FALSE, tsr, tsi);
             status_o = this->child_sa->install(this->child_sa,
                                     encr_r, integ_r, this->spi_i, this->cpi_i,
                                     this->initiator, FALSE, FALSE, tsr, tsi);
         }
     }
     chunk_clear(&integ_i);
     chunk_clear(&integ_r);
     chunk_clear(&encr_i);
     chunk_clear(&encr_r);
     if (status_i != SUCCESS || status_o != SUCCESS)
     {
         DBG1(DBG_IKE, "unable to install %s%s%sIPsec SA (SAD) in kernel",
             (status_i != SUCCESS) ? "inbound " : "",
             (status_i != SUCCESS && status_o != SUCCESS) ? "and ": "",
             (status_o != SUCCESS) ? "outbound " : "");
         tsi->destroy_offset(tsi, offsetof(traffic_selector_t, destroy));
         tsr->destroy_offset(tsr, offsetof(traffic_selector_t, destroy));
         return FALSE;
     }
     if (this->initiator)
     {
         status = this->child_sa->add_policies(this->child_sa, tsi, tsr);
     }
     else
     {
         status = this->child_sa->add_policies(this->child_sa, tsr, tsi);
     }
     tsi->destroy_offset(tsi, offsetof(traffic_selector_t, destroy));
     tsr->destroy_offset(tsr, offsetof(traffic_selector_t, destroy));
     if (status != SUCCESS)
     {
         DBG1(DBG_IKE, "unable to install IPsec policies (SPD) in kernel");
         return FALSE;
     }
     charon->bus->child_keys(charon->bus, this->child_sa, this->initiator,
                             this->dh, this->nonce_i, this->nonce_r);
     /* add to IKE_SA, and remove from task */
     this->child_sa->set_state(this->child_sa, CHILD_INSTALLED);
     this->ike_sa->add_child_sa(this->ike_sa, this->child_sa);
     my_ts = linked_list_create_from_enumerator(
                 this->child_sa->create_ts_enumerator(this->child_sa, TRUE));
     other_ts = linked_list_create_from_enumerator(
                 this->child_sa->create_ts_enumerator(this->child_sa, FALSE));
     DBG0(DBG_IKE, "CHILD_SA %s{%d} established "
          "with SPIs %.8x_i %.8x_o and TS %#R === %#R",
          this->child_sa->get_name(this->child_sa),
          this->child_sa->get_unique_id(this->child_sa),
          ntohl(this->child_sa->get_spi(this->child_sa, TRUE)),
          ntohl(this->child_sa->get_spi(this->child_sa, FALSE)), my_ts, other_ts);
     my_ts->destroy(my_ts);
     other_ts->destroy(other_ts);
     if (this->rekey)
     {
         old = this->ike_sa->get_child_sa(this->ike_sa,
                                 this->proposal->get_protocol(this->proposal),
                                 this->rekey, TRUE);
     }
     if (old)
     {
         charon->bus->child_rekey(charon->bus, old, this->child_sa);
         /* rekeyed CHILD_SAs stay installed until they expire */
         old->set_state(old, CHILD_REKEYED);
     }
     else
     {
         charon->bus->child_updown(charon->bus, this->child_sa, TRUE);
     }
     schedule_inactivity_timeout(this);
     this->child_sa = NULL;
     return TRUE;
 }
METHOD (task_t , build_i , status_t , private_quick_mode_t * this, message_t * message)
Definition at line 798 of file quick_mode.c.
References add_ke(), add_nat_oa_payloads(), add_nonce(), message_t::add_payload, add_ts(), AUTH_NONE, daemon_t::bus, charon, child_sa_create(), COND_NAT_ANY, DBG1, DBG_IKE, linked_list_t::destroy, destroy(), linked_list_t::destroy_offset, dh, DIFFIE_HELLMAN_GROUP, diffie_hellman_group_names, FAILED, FALSE, proposal_t::get_algorithm, linked_list_t::get_count, get_encap(), linked_list_t::get_first, get_lifetimes(), get_proposals(), proposal_t::get_protocol, group, linked_list_create_with_items(), list, MODE_TRANSPORT, MODP_NONE, bus_t::narrow, NARROW_INITIATOR_PRE_AUTH, NEED_MORE, sa_payload_t::payload_interface, proposal, proto, linked_list_t::remove_first, sa_payload_create_from_proposals_v1(), select_ts(), SUCCESS, and TRUE.
 {
     switch (this->state)
     {
         case QM_INIT:
         {
             sa_payload_t *sa_payload;
             linked_list_t *list, *tsi, *tsr;
             proposal_t *proposal;
             diffie_hellman_group_t group;
             encap_t encap;
             this->udp = this->ike_sa->has_condition(this->ike_sa, COND_NAT_ANY);
             this->mode = this->config->get_mode(this->config);
             this->child_sa = child_sa_create(
                                     this->ike_sa->get_my_host(this->ike_sa),
                                     this->ike_sa->get_other_host(this->ike_sa),
                                     this->config, this->reqid, this->udp,
                                     this->mark_in, this->mark_out);
             if (this->udp && this->mode == MODE_TRANSPORT)
             {
                 /* TODO-IKEv1: disable NAT-T for TRANSPORT mode by default? */
                 add_nat_oa_payloads(this, message);
             }
             if (this->config->use_ipcomp(this->config))
             {
                 this->cpi_i = this->child_sa->alloc_cpi(this->child_sa);
                 if (!this->cpi_i)
                 {
                     DBG1(DBG_IKE, "unable to allocate a CPI from kernel, "
                          "IPComp disabled");
                 }
             }
             list = this->config->get_proposals(this->config, MODP_NONE);
             if (list->get_first(list, (void**)&proposal) == SUCCESS)
             {
                 this->proto = proposal->get_protocol(proposal);
             }
             list->destroy_offset(list, offsetof(proposal_t, destroy));
             this->spi_i = this->child_sa->alloc_spi(this->child_sa, this->proto);
             if (!this->spi_i)
             {
                 DBG1(DBG_IKE, "allocating SPI from kernel failed");
                 return FAILED;
             }
             group = this->config->get_dh_group(this->config);
             if (group != MODP_NONE)
             {
                 proposal_t *proposal;
                 u_int16_t preferred_group;
                 proposal = this->ike_sa->get_proposal(this->ike_sa);
                 proposal->get_algorithm(proposal, DIFFIE_HELLMAN_GROUP,
                                         &preferred_group, NULL);
                 /* try the negotiated DH group from IKE_SA */
                 list = get_proposals(this, preferred_group);
                 if (list->get_count(list))
                 {
                     group = preferred_group;
                 }
                 else
                 {
                     /* fall back to the first configured DH group */
                     list->destroy(list);
                     list = get_proposals(this, group);
                 }
                 this->dh = this->keymat->keymat.create_dh(&this->keymat->keymat,
                                                           group);
                 if (!this->dh)
                 {
                     DBG1(DBG_IKE, "configured DH group %N not supported",
                          diffie_hellman_group_names, group);
                     list->destroy_offset(list, offsetof(proposal_t, destroy));
                     return FAILED;
                 }
             }
             else
             {
                 list = get_proposals(this, MODP_NONE);
             }
             get_lifetimes(this);
             encap = get_encap(this->ike_sa, this->udp);
             sa_payload = sa_payload_create_from_proposals_v1(list,
                                 this->lifetime, this->lifebytes, AUTH_NONE,
                                 this->mode, encap, this->cpi_i);
             list->destroy_offset(list, offsetof(proposal_t, destroy));
             message->add_payload(message, &sa_payload->payload_interface);
             if (!add_nonce(this, &this->nonce_i, message))
             {
                 return FAILED;
             }
             if (group != MODP_NONE)
             {
                 if (!add_ke(this, message))
                 {
                     return FAILED;
                 }
             }
             if (!this->tsi)
             {
                 this->tsi = select_ts(this, TRUE, NULL);
             }
             if (!this->tsr)
             {
                 this->tsr = select_ts(this, FALSE, NULL);
             }
             tsi = linked_list_create_with_items(this->tsi, NULL);
             tsr = linked_list_create_with_items(this->tsr, NULL);
             this->tsi = this->tsr = NULL;
             charon->bus->narrow(charon->bus, this->child_sa,
                                 NARROW_INITIATOR_PRE_AUTH, tsi, tsr);
             tsi->remove_first(tsi, (void**)&this->tsi);
             tsr->remove_first(tsr, (void**)&this->tsr);
             tsi->destroy_offset(tsi, offsetof(traffic_selector_t, destroy));
             tsr->destroy_offset(tsr, offsetof(traffic_selector_t, destroy));
             if (!this->tsi || !this->tsr)
             {
                 return FAILED;
             }
             add_ts(this, message);
             return NEED_MORE;
         }
         case QM_NEGOTIATED:
         {
             return SUCCESS;
         }
         default:
             return FAILED;
     }
 }
METHOD (task_t , process_r , status_t , private_quick_mode_t * this, message_t * message)
Definition at line 1024 of file quick_mode.c.
References ALREADY_DONE, apply_lifetimes(), daemon_t::bus, charon, check_for_rekeyed_child(), child_sa_create(), DBG1, DBG_IKE, linked_list_t::destroy, destroy(), DESTROY_IF, linked_list_t::destroy_offset, dh, DIFFIE_HELLMAN_GROUP, diffie_hellman_group_names, EXT_STRONGSWAN, FAILED, FALSE, ike_sa_t::flush_queue, linked_list_t::get_count, get_dynamic_hosts(), sa_payload_t::get_encap_mode, message_t::get_exchange_type, sa_payload_t::get_ipcomp_proposals, get_ke(), get_lifetimes(), message_t::get_message_id, get_nonce(), message_t::get_payload, sa_payload_t::get_proposals, get_ts(), group, has_notify_errors(), INFORMATIONAL_V1, install(), INVALID_ARG, INVALID_ID_INFORMATION, INVALID_KEY_INFORMATION, INVALID_PAYLOAD_TYPE, linked_list_create_with_items(), list, bus_t::narrow, NARROW_RESPONDER, NEED_MORE, NO_PROPOSAL_CHOSEN, notify_type_names, PLV1_DELETE, PLV1_SECURITY_ASSOCIATION, proposal, ike_sa_t::queue_task, quick_delete_create(), linked_list_t::remove_first, peer_cfg_t::select_child_cfg, select_ts(), send_notify(), SUCCESS, TASK_QUEUE_PASSIVE, and TRUE.
 {
     if (this->mid && this->mid != message->get_message_id(message))
     {   /* not responsible for this quick mode exchange */
         return INVALID_ARG;
     }
     switch (this->state)
     {
         case QM_INIT:
         {
             sa_payload_t *sa_payload;
             linked_list_t *tsi, *tsr, *hostsi, *hostsr, *list = NULL;
             peer_cfg_t *peer_cfg;
             u_int16_t group;
             bool private;
             sa_payload = (sa_payload_t*)message->get_payload(message,
                                                     PLV1_SECURITY_ASSOCIATION);
             if (!sa_payload)
             {
                 DBG1(DBG_IKE, "sa payload missing");
                 return send_notify(this, INVALID_PAYLOAD_TYPE);
             }
             this->mode = sa_payload->get_encap_mode(sa_payload, &this->udp);
             if (!get_ts(this, message))
             {
                 return FAILED;
             }
             peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
             tsi = linked_list_create_with_items(this->tsi, NULL);
             tsr = linked_list_create_with_items(this->tsr, NULL);
             this->tsi = this->tsr = NULL;
             hostsi = get_dynamic_hosts(this->ike_sa, FALSE);
             hostsr = get_dynamic_hosts(this->ike_sa, TRUE);
             this->config = peer_cfg->select_child_cfg(peer_cfg, tsr, tsi,
                                                       hostsr, hostsi);
             hostsi->destroy(hostsi);
             hostsr->destroy(hostsr);
             if (this->config)
             {
                 this->tsi = select_ts(this, FALSE, tsi);
                 this->tsr = select_ts(this, TRUE, tsr);
             }
             tsi->destroy_offset(tsi, offsetof(traffic_selector_t, destroy));
             tsr->destroy_offset(tsr, offsetof(traffic_selector_t, destroy));
             if (!this->config || !this->tsi || !this->tsr ||
                 this->mode != this->config->get_mode(this->config))
             {
                 DBG1(DBG_IKE, "no matching CHILD_SA config found");
                 return send_notify(this, INVALID_ID_INFORMATION);
             }
             if (this->config->use_ipcomp(this->config))
             {
                 list = sa_payload->get_ipcomp_proposals(sa_payload,
                                                         &this->cpi_i);
                 if (!list->get_count(list))
                 {
                     DBG1(DBG_IKE, "expected IPComp proposal but peer did "
                          "not send one, IPComp disabled");
                     this->cpi_i = 0;
                 }
             }
             if (!list || !list->get_count(list))
             {
                 DESTROY_IF(list);
                 list = sa_payload->get_proposals(sa_payload);
             }
             private = this->ike_sa->supports_extension(this->ike_sa,
                                                        EXT_STRONGSWAN);
             this->proposal = this->config->select_proposal(this->config,
                                                            list, FALSE, private);
             list->destroy_offset(list, offsetof(proposal_t, destroy));
             get_lifetimes(this);
             apply_lifetimes(this, sa_payload);
             if (!this->proposal)
             {
                 DBG1(DBG_IKE, "no matching proposal found, sending %N",
                      notify_type_names, NO_PROPOSAL_CHOSEN);
                 return send_notify(this, NO_PROPOSAL_CHOSEN);
             }
             this->spi_i = this->proposal->get_spi(this->proposal);
             if (!get_nonce(this, &this->nonce_i, message))
             {
                 return send_notify(this, INVALID_PAYLOAD_TYPE);
             }
             if (this->proposal->get_algorithm(this->proposal,
                                         DIFFIE_HELLMAN_GROUP, &group, NULL))
             {
                 this->dh = this->keymat->keymat.create_dh(&this->keymat->keymat,
                                                           group);
                 if (!this->dh)
                 {
                     DBG1(DBG_IKE, "negotiated DH group %N not supported",
                          diffie_hellman_group_names, group);
                     return send_notify(this, INVALID_KEY_INFORMATION);
                 }
                 if (!get_ke(this, message))
                 {
                     return send_notify(this, INVALID_PAYLOAD_TYPE);
                 }
             }
             check_for_rekeyed_child(this);
             this->child_sa = child_sa_create(
                                     this->ike_sa->get_my_host(this->ike_sa),
                                     this->ike_sa->get_other_host(this->ike_sa),
                                     this->config, this->reqid, this->udp,
                                     this->mark_in, this->mark_out);
             tsi = linked_list_create_with_items(this->tsi, NULL);
             tsr = linked_list_create_with_items(this->tsr, NULL);
             this->tsi = this->tsr = NULL;
             charon->bus->narrow(charon->bus, this->child_sa,
                                 NARROW_RESPONDER, tsr, tsi);
             if (tsi->remove_first(tsi, (void**)&this->tsi) != SUCCESS ||
                 tsr->remove_first(tsr, (void**)&this->tsr) != SUCCESS)
             {
                 tsi->destroy_offset(tsi, offsetof(traffic_selector_t, destroy));
                 tsr->destroy_offset(tsr, offsetof(traffic_selector_t, destroy));
                 return send_notify(this, INVALID_ID_INFORMATION);
             }
             tsi->destroy_offset(tsi, offsetof(traffic_selector_t, destroy));
             tsr->destroy_offset(tsr, offsetof(traffic_selector_t, destroy));
             return NEED_MORE;
         }
         case QM_NEGOTIATED:
         {
             if (has_notify_errors(this, message))
             {
                 return SUCCESS;
             }
             if (message->get_exchange_type(message) == INFORMATIONAL_V1)
             {
                 if (message->get_payload(message, PLV1_DELETE))
                 {
                     /* If the DELETE for a Quick Mode follows immediately
                      * after rekeying, we might receive it before the
                      * third completing Quick Mode message. Ignore it, as
                      * it gets handled by a separately queued delete task. */
                     return NEED_MORE;
                 }
                 return SUCCESS;
             }
             if (!install(this))
             {
                 ike_sa_t *ike_sa = this->ike_sa;
                 task_t *task;
                 task = (task_t*)quick_delete_create(this->ike_sa,
                                 this->proposal->get_protocol(this->proposal),
                                 this->spi_i, TRUE, TRUE);
                 /* flush_queue() destroys the current task */
                 ike_sa->flush_queue(ike_sa, TASK_QUEUE_PASSIVE);
                 ike_sa->queue_task(ike_sa, task);
                 return ALREADY_DONE;
             }
             return SUCCESS;
         }
         default:
             return FAILED;
     }
 }
METHOD (task_t , build_r , status_t , private_quick_mode_t * this, message_t * message)
Definition at line 1198 of file quick_mode.c.
References add_ke(), add_nat_oa_payloads(), add_nonce(), message_t::add_payload, add_ts(), ALREADY_DONE, AUTH_NONE, DBG1, DBG_IKE, dh, FAILED, get_encap(), message_t::get_exchange_type, message_t::get_message_id, INFORMATIONAL_V1, INVALID_ARG, MODE_TRANSPORT, NEED_MORE, NO_PROPOSAL_CHOSEN, sa_payload_t::payload_interface, proposal, proto, sa_payload_create_from_proposal_v1(), and send_notify().
 {
     if (this->mid && this->mid != message->get_message_id(message))
     {   /* not responsible for this quick mode exchange */
         return INVALID_ARG;
     }
     switch (this->state)
     {
         case QM_INIT:
         {
             sa_payload_t *sa_payload;
             encap_t encap;
             this->proto = this->proposal->get_protocol(this->proposal);
             this->spi_r = this->child_sa->alloc_spi(this->child_sa, this->proto);
             if (!this->spi_r)
             {
                 DBG1(DBG_IKE, "allocating SPI from kernel failed");
                 return send_notify(this, NO_PROPOSAL_CHOSEN);
             }
             this->proposal->set_spi(this->proposal, this->spi_r);
             if (this->cpi_i)
             {
                 this->cpi_r = this->child_sa->alloc_cpi(this->child_sa);
                 if (!this->cpi_r)
                 {
                     DBG1(DBG_IKE, "unable to allocate a CPI from "
                          "kernel, IPComp disabled");
                     return send_notify(this, NO_PROPOSAL_CHOSEN);
                 }
             }
             if (this->udp && this->mode == MODE_TRANSPORT)
             {
                 /* TODO-IKEv1: disable NAT-T for TRANSPORT mode by default? */
                 add_nat_oa_payloads(this, message);
             }
             encap = get_encap(this->ike_sa, this->udp);
             sa_payload = sa_payload_create_from_proposal_v1(this->proposal,
                                 this->lifetime, this->lifebytes, AUTH_NONE,
                                 this->mode, encap, this->cpi_r);
             message->add_payload(message, &sa_payload->payload_interface);
             if (!add_nonce(this, &this->nonce_r, message))
             {
                 return FAILED;
             }
             if (this->dh)
             {
                 if (!add_ke(this, message))
                 {
                     return FAILED;
                 }
             }
             add_ts(this, message);
             this->state = QM_NEGOTIATED;
             this->mid = message->get_message_id(message);
             return NEED_MORE;
         }
         case QM_NEGOTIATED:
             if (message->get_exchange_type(message) == INFORMATIONAL_V1)
             {
                 /* skip INFORMATIONAL response if we received a INFORMATIONAL
                  * delete, see process_r() */
                 return ALREADY_DONE;
             }
             /* fall */
         default:
             return FAILED;
     }
 }
METHOD (task_t , process_i , status_t , private_quick_mode_t * this, message_t * message)
Definition at line 1276 of file quick_mode.c.
References apply_lifetimes(), DBG1, DBG_IKE, destroy(), DESTROY_IF, linked_list_t::destroy_offset, dh, EXT_STRONGSWAN, FAILED, FALSE, linked_list_t::get_count, sa_payload_t::get_ipcomp_proposals, get_ke(), get_nonce(), message_t::get_payload, sa_payload_t::get_proposals, get_ts(), install(), INVALID_KEY_INFORMATION, INVALID_PAYLOAD_TYPE, list, NEED_MORE, NO_PROPOSAL_CHOSEN, PLV1_SECURITY_ASSOCIATION, proposal, and send_notify().
 {
     switch (this->state)
     {
         case QM_INIT:
         {
             sa_payload_t *sa_payload;
             linked_list_t *list = NULL;
             bool private;
             sa_payload = (sa_payload_t*)message->get_payload(message,
                                                     PLV1_SECURITY_ASSOCIATION);
             if (!sa_payload)
             {
                 DBG1(DBG_IKE, "sa payload missing");
                 return send_notify(this, NO_PROPOSAL_CHOSEN);
             }
             if (this->cpi_i)
             {
                 list = sa_payload->get_ipcomp_proposals(sa_payload,
                                                         &this->cpi_r);
                 if (!list->get_count(list))
                 {
                     DBG1(DBG_IKE, "peer did not acccept our IPComp proposal, "
                          "IPComp disabled");
                     this->cpi_i = 0;
                 }
             }
             if (!list || !list->get_count(list))
             {
                 DESTROY_IF(list);
                 list = sa_payload->get_proposals(sa_payload);
             }
             private = this->ike_sa->supports_extension(this->ike_sa,
                                                        EXT_STRONGSWAN);
             this->proposal = this->config->select_proposal(this->config,
                                                            list, FALSE, private);
             list->destroy_offset(list, offsetof(proposal_t, destroy));
             if (!this->proposal)
             {
                 DBG1(DBG_IKE, "no matching proposal found");
                 return send_notify(this, NO_PROPOSAL_CHOSEN);
             }
             this->spi_r = this->proposal->get_spi(this->proposal);
             apply_lifetimes(this, sa_payload);
             if (!get_nonce(this, &this->nonce_r, message))
             {
                 return send_notify(this, INVALID_PAYLOAD_TYPE);
             }
             if (this->dh && !get_ke(this, message))
             {
                 return send_notify(this, INVALID_KEY_INFORMATION);
             }
             if (!get_ts(this, message))
             {
                 return send_notify(this, INVALID_PAYLOAD_TYPE);
             }
             if (!install(this))
             {
                 return send_notify(this, NO_PROPOSAL_CHOSEN);
             }
             this->state = QM_NEGOTIATED;
             return NEED_MORE;
         }
         default:
             return FAILED;
     }
 }
METHOD (task_t , get_type , task_type_t , private_quick_mode_t * this)
Definition at line 1348 of file quick_mode.c.
References TASK_QUICK_MODE.
 {
     return TASK_QUICK_MODE;
 }
METHOD (quick_mode_t , get_mid , u_int32_t , private_quick_mode_t * this)
Definition at line 1354 of file quick_mode.c.
 {
     return this->mid;
 }
METHOD (quick_mode_t , use_reqid , void , private_quick_mode_t * this, u_int32_t reqid)
Definition at line 1360 of file quick_mode.c.
 {
     this->reqid = reqid;
 }
METHOD (quick_mode_t , use_marks , void , private_quick_mode_t * this, u_int in, u_int out)
Definition at line 1366 of file quick_mode.c.
References in, and out.
 {
     this->mark_in = in;
     this->mark_out = out;
 }
METHOD (quick_mode_t , rekey , void , private_quick_mode_t * this, u_int32_t spi)
Definition at line 1373 of file quick_mode.c.
 {
     this->rekey = spi;
 }
METHOD (task_t , migrate , void , private_quick_mode_t * this, ike_sa_t * ike_sa)
Definition at line 1379 of file quick_mode.c.
References chunk_free(), DESTROY_IF, dh, ike_sa_t::get_keymat, initiator, and proposal.
 {
     chunk_free(&this->nonce_i);
     chunk_free(&this->nonce_r);
     DESTROY_IF(this->tsi);
     DESTROY_IF(this->tsr);
     DESTROY_IF(this->proposal);
     DESTROY_IF(this->child_sa);
     DESTROY_IF(this->dh);
     this->ike_sa = ike_sa;
     this->keymat = (keymat_v1_t*)ike_sa->get_keymat(ike_sa);
     this->state = QM_INIT;
     this->mid = 0;
     this->tsi = NULL;
     this->tsr = NULL;
     this->proposal = NULL;
     this->child_sa = NULL;
     this->dh = NULL;
     this->spi_i = 0;
     this->spi_r = 0;
     this->mark_in = 0;
     this->mark_out = 0;
     if (!this->initiator)
     {
         DESTROY_IF(this->config);
         this->config = NULL;
     }
 }
METHOD (task_t , destroy , void , private_quick_mode_t * this)
Definition at line 1411 of file quick_mode.c.
References chunk_free(), DESTROY_IF, dh, free(), and proposal.
 {
     chunk_free(&this->nonce_i);
     chunk_free(&this->nonce_r);
     DESTROY_IF(this->tsi);
     DESTROY_IF(this->tsr);
     DESTROY_IF(this->proposal);
     DESTROY_IF(this->child_sa);
     DESTROY_IF(this->config);
     DESTROY_IF(this->dh);
     free(this);
 }
static void schedule_inactivity_timeout (private_quick_mode_t * this) static
Schedule inactivity timeout for CHILD_SA with reqid, if enabled
Definition at line 203 of file quick_mode.c.
References close_ike(), FALSE, settings_t::get_bool, inactivity_job_create(), lib, library_t::ns, scheduler_t::schedule_job, library_t::scheduler, and library_t::settings.
Referenced by install().
 {
     u_int32_t timeout;
     bool close_ike;
     timeout = this->config->get_inactivity(this->config);
     if (timeout)
     {
         close_ike = lib->settings->get_bool(lib->settings,
                                     "%s.inactivity_close_ike", FALSE, lib->ns);
         lib->scheduler->schedule_job(lib->scheduler, (job_t*)
             inactivity_job_create(this->child_sa->get_unique_id(this->child_sa),
                                   timeout, close_ike), timeout);
     }
 }
static traffic_selector_t* select_ts (private_quick_mode_t * this, bool local, linked_list_t * supplied) static
Select a traffic selector from configuration
Definition at line 513 of file quick_mode.c.
References traffic_selector_t::clone, DBG1, DBG_IKE, linked_list_t::destroy, destroy(), linked_list_t::destroy_offset, get_dynamic_hosts(), linked_list_t::get_first, list, and SUCCESS.
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     linked_list_t *list, *hosts;
     hosts = get_dynamic_hosts(this->ike_sa, local);
     list = this->config->get_traffic_selectors(this->config,
                                                local, supplied, hosts);
     hosts->destroy(hosts);
     if (list->get_first(list, (void**)&ts) == SUCCESS)
     {
         ts = ts->clone(ts);
     }
     else
     {
         DBG1(DBG_IKE, "%s traffic selector missing in configuration",
              local ? "local" : "remote");
         ts = NULL;
     }
     list->destroy_offset(list, offsetof(traffic_selector_t, destroy));
     return ts;
 }
static status_t send_notify (private_quick_mode_t * this, notify_type_t type) static
Set the task ready to build notify error message
Definition at line 750 of file quick_mode.c.
References ALREADY_DONE, informational_create(), initiator, notify(), notify_payload_create_from_protocol_and_type(), PLV1_NOTIFY, proto, notify_payload_t::set_spi, TASK_QUEUE_ACTIVE, and TASK_QUEUE_PASSIVE.
Referenced by METHOD().
 {
     notify_payload_t *notify;
     notify = notify_payload_create_from_protocol_and_type(PLV1_NOTIFY,
                                                           this->proto, type);
     notify->set_spi(notify, this->spi_i);
     this->ike_sa->queue_task(this->ike_sa,
                         (task_t*)informational_create(this->ike_sa, notify));
     /* cancel all active/passive tasks in favour of informational */
     this->ike_sa->flush_queue(this->ike_sa,
                     this->initiator ? TASK_QUEUE_ACTIVE : TASK_QUEUE_PASSIVE);
     return ALREADY_DONE;
 }