strongSwan: pwg_attr_vendor_smi_code.c File Reference
pwg_attr_vendor_smi_code.c File Reference
#include "pwg_attr_vendor_smi_code.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pwg_attr_vendor_smi_code_t
Macros
#define VENDOR_SMI_CODE_SIZE 4
Typedefs
typedef struct
private_pwg_attr_vendor_smi_code_t private_pwg_attr_vendor_smi_code_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_pwg_attr_vendor_smi_code_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_pwg_attr_vendor_smi_code_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_pwg_attr_vendor_smi_code_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_pwg_attr_vendor_smi_code_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_pwg_attr_vendor_smi_code_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_pwg_attr_vendor_smi_code_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_pwg_attr_vendor_smi_code_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_pwg_attr_vendor_smi_code_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_pwg_attr_vendor_smi_code_t *this)
METHOD (pwg_attr_vendor_smi_code_t, get_vendor_smi_code, pen_t, private_pwg_attr_vendor_smi_code_t *this)
pa_tnc_attr_t * pwg_attr_vendor_smi_code_create (pen_t vendor_smi_code)
pa_tnc_attr_t * pwg_attr_vendor_smi_code_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define VENDOR_SMI_CODE_SIZE 4
PWG HCD PA-TNC Vendor SMI Code
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Vendor SMI Code | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 35 of file pwg_attr_vendor_smi_code.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pwg_attr_vendor_smi_code_t private_pwg_attr_vendor_smi_code_t
Definition at line 23 of file pwg_attr_vendor_smi_code.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_pwg_attr_vendor_smi_code_t * this)
Definition at line 78 of file pwg_attr_vendor_smi_code.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_pwg_attr_vendor_smi_code_t * this)
Definition at line 84 of file pwg_attr_vendor_smi_code.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_pwg_attr_vendor_smi_code_t * this)
Definition at line 90 of file pwg_attr_vendor_smi_code.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_pwg_attr_vendor_smi_code_t * this, bool noskip)
Definition at line 96 of file pwg_attr_vendor_smi_code.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_pwg_attr_vendor_smi_code_t * this)
Definition at line 102 of file pwg_attr_vendor_smi_code.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, value, VENDOR_SMI_CODE_SIZE, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(VENDOR_SMI_CODE_SIZE);
     writer->write_uint32(writer, this->vendor_smi_code);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_pwg_attr_vendor_smi_code_t * this, u_int32_t * offset)
Definition at line 119 of file pwg_attr_vendor_smi_code.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, bio_reader_t::read_uint24, bio_reader_t::read_uint8, reserved, SUCCESS, value, and VENDOR_SMI_CODE_SIZE.
 {
     bio_reader_t *reader;
     uint32_t vendor_smi_code;
     uint8_t reserved;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len != VENDOR_SMI_CODE_SIZE)
     {
         DBG1(DBG_TNC, "incorrect attribute length for PWG HCD Vendor SMI Code");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &reserved);
     reader->read_uint24(reader, &vendor_smi_code);
     reader->destroy(reader);
     this->vendor_smi_code = vendor_smi_code;
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_pwg_attr_vendor_smi_code_t * this, chunk_t segment)
Definition at line 146 of file pwg_attr_vendor_smi_code.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_pwg_attr_vendor_smi_code_t * this)
Definition at line 152 of file pwg_attr_vendor_smi_code.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_pwg_attr_vendor_smi_code_t * this)
Definition at line 159 of file pwg_attr_vendor_smi_code.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (pwg_attr_vendor_smi_code_t , get_vendor_smi_code , pen_t , private_pwg_attr_vendor_smi_code_t * this)
Definition at line 169 of file pwg_attr_vendor_smi_code.c.
 {
     return this->vendor_smi_code;
 }