strongSwan: pkcs7_attributes.c File Reference
pkcs7_attributes.c File Reference
#include <library.h>
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <collections/linked_list.h>
#include "pkcs7_attributes.h"
Classes
struct private_pkcs7_attributes_t
struct attribute_t
Macros
#define ATTRIBUTE_OBJ_TYPE 2
#define ATTRIBUTE_OBJ_VALUE 4
Typedefs
typedef struct
private_pkcs7_attributes_t private_pkcs7_attributes_t
typedef struct attribute_t attribute_t
Functions
static void attribute_destroy (attribute_t *this)
static attribute_t * attribute_create (int oid, chunk_t value)
static void build_encoding (private_pkcs7_attributes_t *this)
METHOD (pkcs7_attributes_t, get_encoding, chunk_t, private_pkcs7_attributes_t *this)
METHOD (pkcs7_attributes_t, get_attribute, chunk_t, private_pkcs7_attributes_t *this, int oid)
METHOD (pkcs7_attributes_t, add_attribute, void, private_pkcs7_attributes_t *this, int oid, chunk_t value)
METHOD (pkcs7_attributes_t, destroy, void, private_pkcs7_attributes_t *this)
pkcs7_attributes_t * pkcs7_attributes_create (void)
static bool parse_attributes (chunk_t chunk, int level0, private_pkcs7_attributes_t *this)
pkcs7_attributes_t * pkcs7_attributes_create_from_chunk (chunk_t chunk, u_int level)
Variables
static const asn1Object_t attributesObjects []
Macro Definition Documentation
#define ATTRIBUTE_OBJ_TYPE 2
Definition at line 217 of file pkcs7_attributes.c.
Referenced by parse_attributes().
#define ATTRIBUTE_OBJ_VALUE 4
Definition at line 218 of file pkcs7_attributes.c.
Referenced by parse_attributes().
Typedef Documentation
typedef struct attribute_t attribute_t
Definition at line 28 of file pkcs7_attributes.c.
typedef struct private_pkcs7_attributes_t private_pkcs7_attributes_t
Definition at line 27 of file pkcs7_attributes.c.
Function Documentation
static attribute_t* attribute_create (int oid, chunk_t value) static
Create an attribute_t object.
Definition at line 83 of file pkcs7_attributes.c.
References chunk_clone, and INIT.
Referenced by METHOD(), and parse_attributes().
 {
     attribute_t *this;
     INIT(this,
         .oid = oid,
         .value = chunk_clone(value),
     );
     return this;
 }
static void attribute_destroy (attribute_t * this) static
Destroy an attribute_t object.
Definition at line 74 of file pkcs7_attributes.c.
References free(), and value.
Referenced by METHOD().
 {
     free(this->value.ptr);
     free(this);
 }
static void build_encoding (private_pkcs7_attributes_t * this) static
Build encoding of the attribute list
Definition at line 98 of file pkcs7_attributes.c.
References asn1_build_known_oid(), asn1_build_object(), ASN1_SEQUENCE, ASN1_SET, asn1_wrap(), attributes, count, enumerator_t::destroy, encoding, enumerator_t::enumerate, free(), chunk_t::len, len, malloc(), memcpy, attribute_t::oid, and attribute_t::value.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     attribute_t *attribute;
     u_int len = 0, count, i = 0;
     chunk_t *chunks;
     u_char *pos;
     count = this->attributes->get_count(this->attributes);
     chunks = malloc(sizeof(chunk_t) * count);
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &attribute))
     {
         chunks[i] = asn1_wrap(ASN1_SEQUENCE, "mm",
                                 asn1_build_known_oid(attribute->oid),
                                 asn1_wrap(ASN1_SET, "c", attribute->value));
         len += chunks[i].len;
         i++;
     }
     enumerator->destroy(enumerator);
     pos = asn1_build_object(&this->encoding, ASN1_SET, len);
     for (i = 0; i < count; i++)
     {
         memcpy(pos, chunks[i].ptr, chunks[i].len);
         pos += chunks[i].len;
         free(chunks[i].ptr);
     }
     free(chunks);
 }
METHOD (pkcs7_attributes_t , get_encoding , chunk_t , private_pkcs7_attributes_t * this)
Definition at line 130 of file pkcs7_attributes.c.
References build_encoding(), and encoding.
 {
     if (!this->encoding.len)
     {
         build_encoding(this);
     }
     return this->encoding;
 }
METHOD (pkcs7_attributes_t , get_attribute , chunk_t , private_pkcs7_attributes_t * this, int oid)
Definition at line 140 of file pkcs7_attributes.c.
References ASN1_INVALID, asn1_unwrap(), attributes, chunk_empty, enumerator_t::destroy, enumerator_t::enumerate, chunk_t::len, attribute_t::oid, attribute_t::value, and value.
 {
     enumerator_t *enumerator;
     chunk_t value = chunk_empty;
     attribute_t *attribute;
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &attribute))
     {
         if (attribute->oid == oid)
         {
             value = attribute->value;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (value.len && asn1_unwrap(&value, &value) != ASN1_INVALID)
     {
         return value;
     }
     return chunk_empty;
 }
METHOD (pkcs7_attributes_t , add_attribute , void , private_pkcs7_attributes_t * this, int oid, chunk_t value)
Definition at line 164 of file pkcs7_attributes.c.
References attribute_create(), attributes, chunk_free(), and encoding.
 {
     this->attributes->insert_last(this->attributes,
                                   attribute_create(oid, value));
     chunk_free(&value);
     /* rebuild encoding when adding attributes */
     chunk_free(&this->encoding);
 }
METHOD (pkcs7_attributes_t , destroy , void , private_pkcs7_attributes_t * this)
Definition at line 175 of file pkcs7_attributes.c.
References attribute_destroy(), attributes, encoding, and free().
 {
     this->attributes->destroy_function(this->attributes,
                                        (void*)attribute_destroy);
     free(this->encoding.ptr);
     free(this);
 }
static bool parse_attributes (chunk_t chunk, int level0, private_pkcs7_attributes_t * this) static
Parse a PKCS#9 attribute list
Definition at line 223 of file pkcs7_attributes.c.
References asn1_known_oid(), asn1_parser_create(), attribute_create(), ATTRIBUTE_OBJ_TYPE, ATTRIBUTE_OBJ_VALUE, attributes, asn1_parser_t::destroy, FALSE, asn1_parser_t::iterate, OID_UNKNOWN, parser, asn1_parser_t::set_top_level, and asn1_parser_t::success.
Referenced by pkcs7_attributes_create_from_chunk().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int oid = OID_UNKNOWN;
     bool success = FALSE;
     parser = asn1_parser_create(attributesObjects, chunk);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case ATTRIBUTE_OBJ_TYPE:
                 oid = asn1_known_oid(object);
                 break;
             case ATTRIBUTE_OBJ_VALUE:
                 if (oid != OID_UNKNOWN)
                 {
                     this->attributes->insert_last(this->attributes,
                                                   attribute_create(oid, object));
                 }
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     return success;
 }
Variable Documentation
const asn1Object_t attributesObjects[] static
Initial value:
= {
    { 0, "attributes",      ASN1_SET,       ASN1_LOOP },
    { 1,   "attribute",     ASN1_SEQUENCE,  ASN1_NONE },
    { 2,     "type",        ASN1_OID,       ASN1_BODY },
    { 2,     "values",      ASN1_SET,       ASN1_LOOP },
    { 3,       "value",     ASN1_EOC,       ASN1_RAW  },
    { 2,     "end loop",    ASN1_EOC,       ASN1_END  },
    { 0, "end loop",        ASN1_EOC,       ASN1_END  },
    { 0, "exit",            ASN1_EOC,       ASN1_EXIT }
}
ASN.1 definition of the X.501 atttribute type
Definition at line 207 of file pkcs7_attributes.c.