strongSwan: ipsec_policy_t Struct Reference
ipsec_policy_t Struct Reference
ipsec_policy
#include "ipsec_policy.h"
Public Attributes
traffic_selector_t *(* get_source_ts)(ipsec_policy_t *this)
traffic_selector_t *(* get_destination_ts)(ipsec_policy_t *this)
policy_dir_t(* get_direction)(ipsec_policy_t *this)
policy_priority_t(* get_priority)(ipsec_policy_t *this)
policy_type_t(* get_type)(ipsec_policy_t *this)
u_int32_t(* get_reqid)(ipsec_policy_t *this)
ipsec_policy_t *(* get_ref)(ipsec_policy_t *this)
bool(* match)(ipsec_policy_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t priority)
bool(* match_packet)(ipsec_policy_t *this, ip_packet_t *packet)
void(* destroy)(ipsec_policy_t *this)
Detailed Description
IPsec Policy
Definition at line 38 of file ipsec_policy.h.
Member Data Documentation
void(* ipsec_policy_t::destroy)(ipsec_policy_t *this)
Destroy an ipsec_policy_t
Definition at line 115 of file ipsec_policy.h.
Referenced by process_inbound(), and process_outbound().
traffic_selector_t*(* ipsec_policy_t::get_destination_ts)(ipsec_policy_t *this)
Get the destination traffic selector of this policy
Returns
the destination traffic selector
Definition at line 52 of file ipsec_policy.h.
Referenced by policy_entry_create().
policy_dir_t(* ipsec_policy_t::get_direction)(ipsec_policy_t *this)
Get the direction of this policy
Returns
direction
Definition at line 59 of file ipsec_policy.h.
Referenced by METHOD().
policy_priority_t(* ipsec_policy_t::get_priority)(ipsec_policy_t *this)
Get the priority of this policy
Returns
priority
Definition at line 66 of file ipsec_policy.h.
Referenced by policy_entry_create().
ipsec_policy_t*(* ipsec_policy_t::get_ref)(ipsec_policy_t *this)
Get another reference to this policy
Returns
additional reference to the policy
Definition at line 87 of file ipsec_policy.h.
Referenced by METHOD().
u_int32_t(* ipsec_policy_t::get_reqid)(ipsec_policy_t *this)
Get the reqid associated to this policy
Returns
the reqid
Definition at line 80 of file ipsec_policy.h.
Referenced by METHOD(), and process_outbound().
traffic_selector_t*(* ipsec_policy_t::get_source_ts)(ipsec_policy_t *this)
Get the source traffic selector of this policy
Returns
the source traffic selector
Definition at line 45 of file ipsec_policy.h.
Referenced by policy_entry_create().
policy_type_t(* ipsec_policy_t::get_type)(ipsec_policy_t *this)
Get the type of this policy (e.g. IPsec)
Returns
the policy type
Definition at line 73 of file ipsec_policy.h.
bool(* ipsec_policy_t::match)(ipsec_policy_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t priority)
Check if this policy matches all given parameters
Parameters
src_ts source traffic selector
dst_ts destination traffic selector
direction traffic direction
reqid reqid of the policy
mark mark for this policy
prioirty policy priority
Returns
TRUE if policy matches all parameters
Definition at line 100 of file ipsec_policy.h.
Referenced by METHOD().
bool(* ipsec_policy_t::match_packet)(ipsec_policy_t *this, ip_packet_t *packet)
Check if this policy matches the given IP packet
Parameters
packet IP packet
Returns
TRUE if policy matches the packet
Definition at line 110 of file ipsec_policy.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ipsec_policy.h