strongSwan: pt_tls_dispatcher
pt_tls_dispatcher
libpttls
Classes
struct pt_tls_dispatcher_t
Typedefs
typedef struct pt_tls_dispatcher_t pt_tls_dispatcher_t
typedef tnccs_t *(pt_tls_tnccs_constructor_t)(identification_t *server, identification_t *peer)
Functions
pt_tls_dispatcher_t * pt_tls_dispatcher_create (host_t *address, identification_t *id, pt_tls_auth_t auth)
Detailed Description
Typedef Documentation
typedef struct pt_tls_dispatcher_t pt_tls_dispatcher_t
Definition at line 31 of file pt_tls_dispatcher.h.
typedef tnccs_t*(pt_tls_tnccs_constructor_t)(identification_t *server, identification_t *peer)
Constructor callback to create TNCCS to use within PT-TLS.
Parameters
server server identity
peer peer identity
Definition at line 39 of file pt_tls_dispatcher.h.
Function Documentation
pt_tls_dispatcher_t* pt_tls_dispatcher_create (host_t * address, identification_t * id, pt_tls_auth_t auth)
Create a pt_tls_dispatcher instance.
Parameters
address server address with port to listen on, gets owned
id TLS server identity, gets owned
auth client authentication to perform
Returns
dispatcher service
See header
Definition at line 178 of file pt_tls_dispatcher.c.
References chunk_empty, destroy(), ID_ANY, identification_create_from_encoding(), INIT, and open_socket().
 {
     private_pt_tls_dispatcher_t *this;
     INIT(this,
         .public = {
             .dispatch = _dispatch,
             .destroy = _destroy,
         },
         .server = id->clone(id),
         /* we currently don't authenticate the peer, use %any identity */
         .peer = identification_create_from_encoding(ID_ANY, chunk_empty),
         .fd = -1,
         .auth = auth,
     );
     if (!open_socket(this, address))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }