strongSwan: load_conns.h File Reference
load_conns.h File Reference
#include "command.h"
Functions
int load_conns_cfg (vici_conn_t *conn, command_format_options_t format, settings_t *cfg)
Function Documentation
int load_conns_cfg (vici_conn_t * conn, command_format_options_t format, settings_t * cfg)
Load all connections from configuration file
Parameters
conn vici connection to load to
format output format
cfg configuration to load from
See header.
Definition at line 353 of file load_conns.c.
References COMMAND_FORMAT_RAW, settings_t::create_section_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, found, fprintf, free(), list_conns(), load_conn(), printf, linked_list_t::remove_first, remove_from_list(), section, SUCCESS, and unload_conn().
Referenced by load_all(), and load_conns().
 {
     u_int found = 0, loaded = 0, unloaded = 0;
     char *section;
     enumerator_t *enumerator;
     linked_list_t *conns;
     conns = list_conns(conn, format);
     enumerator = cfg->create_section_enumerator(cfg, "connections");
     while (enumerator->enumerate(enumerator, &section))
     {
         remove_from_list(conns, section);
         found++;
         if (load_conn(conn, cfg, section, format))
         {
             loaded++;
         }
     }
     enumerator->destroy(enumerator);
     /* unload all connection in daemon, but not in file */
     while (conns->remove_first(conns, (void**)&section) == SUCCESS)
     {
         if (unload_conn(conn, section, format))
         {
             unloaded++;
         }
         free(section);
     }
     conns->destroy(conns);
     if (format & COMMAND_FORMAT_RAW)
     {
         return 0;
     }
     if (found == 0)
     {
         printf("no connections found, %u unloaded\n", unloaded);
         return 0;
     }
     if (loaded == found)
     {
         printf("successfully loaded %u connections, %u unloaded\n",
                loaded, unloaded);
         return 0;
     }
     fprintf(stderr, "loaded %u of %u connections, %u failed to load, "
             "%u unloaded\n", loaded, found, found - loaded, unloaded);
     return EINVAL;
 }