strongSwan: whitelist_listener.c File Reference
whitelist_listener.c File Reference
#include "whitelist_listener.h"
#include <daemon.h>
#include <collections/hashtable.h>
#include <threading/rwlock.h>
Classes
struct private_whitelist_listener_t
Typedefs
typedef struct
private_whitelist_listener_t private_whitelist_listener_t
Functions
static u_int hash (identification_t *key)
static bool equals (identification_t *a, identification_t *b)
METHOD (listener_t, authorize, bool, private_whitelist_listener_t *this, ike_sa_t *ike_sa, bool final, bool *success)
METHOD (whitelist_listener_t, add, void, private_whitelist_listener_t *this, identification_t *id)
METHOD (whitelist_listener_t, remove_, void, private_whitelist_listener_t *this, identification_t *id)
static bool whitelist_filter (rwlock_t *lock, identification_t **key, identification_t **id, identification_t **value)
METHOD (whitelist_listener_t, create_enumerator, enumerator_t *, private_whitelist_listener_t *this)
METHOD (whitelist_listener_t, flush, void, private_whitelist_listener_t *this, identification_t *id)
METHOD (whitelist_listener_t, set_active, void, private_whitelist_listener_t *this, bool enable)
METHOD (whitelist_listener_t, destroy, void, private_whitelist_listener_t *this)
whitelist_listener_t * whitelist_listener_create ()
Typedef Documentation
typedef struct private_whitelist_listener_t private_whitelist_listener_t
Definition at line 22 of file whitelist_listener.c.
Function Documentation
static bool equals (identification_t * a, identification_t * b) static
Hashtable equals function
Definition at line 61 of file whitelist_listener.c.
References identification_t::equals.
Referenced by whitelist_listener_create().
 {
     return a->equals(a, b);
 }
static u_int hash (identification_t * key) static
Hashtable hash function
Definition at line 53 of file whitelist_listener.c.
References identification_t::hash.
Referenced by whitelist_listener_create().
 {
     return key->hash(key, 0);
 }
METHOD (listener_t , authorize , bool , private_whitelist_listener_t * this, ike_sa_t * ike_sa, bool final, bool * success)
Definition at line 66 of file whitelist_listener.c.
References AUTH_RULE_EAP_IDENTITY, AUTH_RULE_IDENTITY, DBG1, DBG2, DBG_CFG, enabled, FALSE, auth_cfg_t::get, ike_sa_t::get_auth_cfg, id, lock, TRUE, and spinlock_t::unlock.
 {
     /* check each authentication round */
     if (this->enabled && !final)
     {
         bool whitelisted = FALSE;
         identification_t *id;
         auth_cfg_t *auth;
         auth = ike_sa->get_auth_cfg(ike_sa, FALSE);
         /* for authenticated with EAP, check EAP identity */
         id = auth->get(auth, AUTH_RULE_EAP_IDENTITY);
         if (!id)
         {
             id = auth->get(auth, AUTH_RULE_IDENTITY);
         }
         if (id)
         {
             this->lock->read_lock(this->lock);
             whitelisted = this->ids->get(this->ids, id) != NULL;
             this->lock->unlock(this->lock);
         }
         if (whitelisted)
         {
             DBG2(DBG_CFG, "peer identity '%Y' whitelisted", id);
         }
         else
         {
             DBG1(DBG_CFG, "peer identity '%Y' not whitelisted", id);
             *success = FALSE;
         }
     }
     return TRUE;
 }
METHOD (whitelist_listener_t , add , void , private_whitelist_listener_t * this, identification_t * id)
Definition at line 103 of file whitelist_listener.c.
References DESTROY_IF, lock, and spinlock_t::unlock.
 {
     id = id->clone(id);
     this->lock->write_lock(this->lock);
     id = this->ids->put(this->ids, id, id);
     this->lock->unlock(this->lock);
     DESTROY_IF(id);
 }
METHOD (whitelist_listener_t , remove_ , void , private_whitelist_listener_t * this, identification_t * id)
Definition at line 113 of file whitelist_listener.c.
References DESTROY_IF, lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     id = this->ids->remove(this->ids, id);
     this->lock->unlock(this->lock);
     DESTROY_IF(id);
 }
METHOD (whitelist_listener_t , create_enumerator , enumerator_t * , private_whitelist_listener_t * this)
Definition at line 132 of file whitelist_listener.c.
References enumerator_create_filter(), lock, spinlock_t::unlock, and whitelist_filter().
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(this->ids->create_enumerator(this->ids),
                                     (void*)whitelist_filter, this->lock,
                                     (void*)this->lock->unlock);
 }
METHOD (whitelist_listener_t , flush , void , private_whitelist_listener_t * this, identification_t * id)
Definition at line 141 of file whitelist_listener.c.
References enumerator_t::destroy, identification_t::destroy, enumerator_t::enumerate, key, lock, identification_t::matches, spinlock_t::unlock, and value.
 {
     enumerator_t *enumerator;
     identification_t *key, *value;
     this->lock->write_lock(this->lock);
     enumerator = this->ids->create_enumerator(this->ids);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         if (value->matches(value, id))
         {
             this->ids->remove_at(this->ids, enumerator);
             value->destroy(value);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (whitelist_listener_t , set_active , void , private_whitelist_listener_t * this, bool enable)
Definition at line 161 of file whitelist_listener.c.
References DBG1, DBG_CFG, and enabled.
 {
     DBG1(DBG_CFG, "whitelist functionality %s%sabled",
         (this->enabled == enable) ? "was already " : "", enable ? "en" : "dis");
     this->enabled = enable;
 }
METHOD (whitelist_listener_t , destroy , void , private_whitelist_listener_t * this)
Definition at line 169 of file whitelist_listener.c.
References spinlock_t::destroy, enumerator_t::destroy, identification_t::destroy, enumerator_t::enumerate, free(), key, lock, and value.
 {
     identification_t *key, *value;
     enumerator_t *enumerator;
     enumerator = this->ids->create_enumerator(this->ids);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         value->destroy(value);
     }
     enumerator->destroy(enumerator);
     this->ids->destroy(this->ids);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool whitelist_filter (rwlock_t * lock, identification_t ** key, identification_t ** id, identification_t ** value) static
Enumerator filter, from hashtable (key, value) to single identity
Definition at line 125 of file whitelist_listener.c.
References TRUE, and value.
Referenced by METHOD().
 {
     *id = *value;
     return TRUE;
 }