strongSwan: mediation_job.c File Reference
mediation_job.c File Reference
#include "mediation_job.h"
#include <encoding/payloads/endpoint_notify.h>
#include <daemon.h>
Classes
struct private_mediation_job_t
Typedefs
typedef struct
private_mediation_job_t private_mediation_job_t
Functions
METHOD (job_t, destroy, void, private_mediation_job_t *this)
METHOD (job_t, execute, job_requeue_t, private_mediation_job_t *this)
METHOD (job_t, get_priority, job_priority_t, private_mediation_job_t *this)
static private_mediation_job_t * mediation_job_create_empty ()
mediation_job_t * mediation_job_create (identification_t *peer_id, identification_t *requester, chunk_t connect_id, chunk_t connect_key, linked_list_t *endpoints, bool response)
mediation_job_t * mediation_callback_job_create (identification_t *requester, identification_t *peer_id)
Typedef Documentation
typedef struct private_mediation_job_t private_mediation_job_t
Definition at line 22 of file mediation_job.c.
Function Documentation
static private_mediation_job_t* mediation_job_create_empty () static
Creates an empty mediation job
Definition at line 143 of file mediation_job.c.
References INIT.
Referenced by mediation_callback_job_create(), and mediation_job_create().
 {
     private_mediation_job_t *this;
     INIT(this,
         .public = {
             .job_interface = {
                 .execute = _execute,
                 .get_priority = _get_priority,
                 .destroy = _destroy,
             },
         },
     );
     return this;
 }
METHOD (job_t , destroy , void , private_mediation_job_t * this)
Definition at line 69 of file mediation_job.c.
References chunk_free(), destroy(), DESTROY_IF, DESTROY_OFFSET_IF, free(), and source.
 {
     DESTROY_IF(this->target);
     DESTROY_IF(this->source);
     chunk_free(&this->connect_id);
     chunk_free(&this->connect_key);
     DESTROY_OFFSET_IF(this->endpoints, offsetof(endpoint_notify_t, destroy));
     free(this);
 }
METHOD (job_t , execute , job_requeue_t , private_mediation_job_t * this)
Definition at line 80 of file mediation_job.c.
References callback, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkout, DBG1, DBG_JOB, daemon_t::ike_sa_manager, JOB_REQUEUE_NONE, source, and SUCCESS.
 {
     ike_sa_id_t *target_sa_id;
     target_sa_id = charon->mediation_manager->check(charon->mediation_manager, this->target);
     if (target_sa_id)
     {
         ike_sa_t *target_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager,
                                               target_sa_id);
         if (target_sa)
         {
             if (this->callback)
             {
                 /* send callback to a peer */
                 if (target_sa->callback(target_sa, this->source) != SUCCESS)
                 {
                     DBG1(DBG_JOB, "callback for '%Y' to '%Y' failed",
                             this->source, this->target);
                     charon->ike_sa_manager->checkin(charon->ike_sa_manager, target_sa);
                     return JOB_REQUEUE_NONE;
                 }
             }
             else
             {
                 /* normal mediation between two peers */
                 if (target_sa->relay(target_sa, this->source, this->connect_id,
                         this->connect_key, this->endpoints, this->response) != SUCCESS)
                 {
                     DBG1(DBG_JOB, "mediation between '%Y' and '%Y' failed",
                             this->source, this->target);
                     charon->ike_sa_manager->checkin(charon->ike_sa_manager, target_sa);
                     /* FIXME: notify the initiator */
                     return JOB_REQUEUE_NONE;
                 }
             }
             charon->ike_sa_manager->checkin(charon->ike_sa_manager, target_sa);
         }
         else
         {
             DBG1(DBG_JOB, "mediation between '%Y' and '%Y' failed: "
                     "SA not found", this->source, this->target);
         }
     }
     else
     {
         DBG1(DBG_JOB, "mediation between '%Y' and '%Y' failed: "
                 "peer is not online anymore", this->source, this->target);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (job_t , get_priority , job_priority_t , private_mediation_job_t * this)
Definition at line 134 of file mediation_job.c.
References JOB_PRIO_MEDIUM.
 {
     return JOB_PRIO_MEDIUM;
 }