strongSwan: peer_cfg_t Struct Reference
peer_cfg_t Struct Reference
peer_cfg
#include "peer_cfg.h"
Public Attributes
char *(* get_name)(peer_cfg_t *this)
ike_version_t(* get_ike_version)(peer_cfg_t *this)
ike_cfg_t *(* get_ike_cfg)(peer_cfg_t *this)
void(* add_child_cfg)(peer_cfg_t *this, child_cfg_t *child_cfg)
void(* remove_child_cfg)(peer_cfg_t *this, enumerator_t *enumerator)
enumerator_t *(* create_child_cfg_enumerator)(peer_cfg_t *this)
child_cfg_t *(* select_child_cfg)(peer_cfg_t *this, linked_list_t *my_ts, linked_list_t *other_ts, linked_list_t *my_hosts, linked_list_t *other_hosts)
void(* add_auth_cfg)(peer_cfg_t *this, auth_cfg_t *cfg, bool local)
enumerator_t *(* create_auth_cfg_enumerator)(peer_cfg_t *this, bool local)
cert_policy_t(* get_cert_policy)(peer_cfg_t *this)
unique_policy_t(* get_unique_policy)(peer_cfg_t *this)
u_int32_t(* get_keyingtries)(peer_cfg_t *this)
u_int32_t(* get_rekey_time)(peer_cfg_t *this, bool jitter)
u_int32_t(* get_reauth_time)(peer_cfg_t *this, bool jitter)
u_int32_t(* get_over_time)(peer_cfg_t *this)
bool(* use_mobike)(peer_cfg_t *this)
bool(* use_aggressive)(peer_cfg_t *this)
bool(* use_pull_mode)(peer_cfg_t *this)
u_int32_t(* get_dpd)(peer_cfg_t *this)
u_int32_t(* get_dpd_timeout)(peer_cfg_t *this)
void(* add_virtual_ip)(peer_cfg_t *this, host_t *vip)
enumerator_t *(* create_virtual_ip_enumerator)(peer_cfg_t *this)
void(* add_pool)(peer_cfg_t *this, char *name)
enumerator_t *(* create_pool_enumerator)(peer_cfg_t *this)
bool(* equals)(peer_cfg_t *this, peer_cfg_t *other)
peer_cfg_t *(* get_ref)(peer_cfg_t *this)
void(* destroy)(peer_cfg_t *this)
Detailed Description
Configuration of a peer, specified by IDs.
The peer config defines a connection between two given IDs. It contains exactly one ike_cfg_t, which is used for initiation. Additionally, it contains multiple child_cfg_t defining which CHILD_SAs are allowed for this peer.
                       +-------------------+        +---------------+
+---------------+      |     peer_cfg      |      +---------------+ |
|    ike_cfg    |      +-------------------+      |   child_cfg   | |
+---------------+      | - ids             |      +---------------+ |
| - hosts       | 1  1 | - cas             | 1  n | - proposals   | |
| - proposals   |<-----| - auth info       |----->| - traffic sel | |
| - ...         |      | - dpd config      |      | - ...         |-+
+---------------+      | - ...             |      +---------------+
                       +-------------------+
                          | 1         0 |
                          |             |
                          v n         n V
          +-------------------+     +-------------------+
        +-------------------+ |   +-------------------+ |
        |     auth_cfg      | |   |     auth_cfg      | |
        +-------------------+ |   +-------------------+ |
        | - local rules     |-+   | - remote constr.  |-+
        +-------------------+     +-------------------+
Each peer_cfg has two lists of authentication config attached. Local authentication configs define how to authenticate ourself against the remote peer. Each config is enforced using the multiple authentication extension (RFC4739). The remote authentication configs are handled as constraints. The peer has to fulfill each of these rules (using multiple authentication, in any order) to gain access to the configuration.
Definition at line 117 of file peer_cfg.h.
Member Data Documentation
void(* peer_cfg_t::add_auth_cfg)(peer_cfg_t *this, auth_cfg_t *cfg, bool local)
Add an authentication config to the peer configuration.
Parameters
cfg config to add
local TRUE for local rules, FALSE for remote constraints
Definition at line 182 of file peer_cfg.h.
Referenced by add_auth_cfg(), build_peer_cfg(), CALLBACK(), connect_(), generate_auth_cfg(), initiate_connection(), load_peer_config(), METHOD(), and setup_tunnel().
void(* peer_cfg_t::add_child_cfg)(peer_cfg_t *this, child_cfg_t *child_cfg)
Attach a CHILD config.
Parameters
child_cfg CHILD config to add
Definition at line 147 of file peer_cfg.h.
Referenced by add_child_cfgs(), CALLBACK(), connect_(), create_child_cfg(), generate_config(), initiate_connection(), load_peer_config(), METHOD(), replace_children(), and setup_tunnel().
void(* peer_cfg_t::add_pool)(peer_cfg_t *this, char *name)
Add a pool name this configuration uses to select virtual IPs.
Parameters
name pool name to use for virtual IP lookup
Definition at line 292 of file peer_cfg.h.
Referenced by build_peer_cfg(), CALLBACK(), generate_config(), and load_peer_config().
void(* peer_cfg_t::add_virtual_ip)(peer_cfg_t *this, host_t *vip)
Add a virtual IP to request as initiator.
Parameters
vip virtual IP to request, may be any or any6
Definition at line 276 of file peer_cfg.h.
Referenced by build_peer_cfg(), CALLBACK(), connect_(), create_child_cfg(), generate_config(), and initiate_connection().
enumerator_t*(* peer_cfg_t::create_auth_cfg_enumerator)(peer_cfg_t *this, bool local)
Create an enumerator over registered authentication configs.
Parameters
local TRUE for local rules, FALSE for remote constraints
Returns
enumerator over auth_cfg_t*
Definition at line 190 of file peer_cfg.h.
Referenced by build_auth_cfgs(), build_certreqs(), get_auth_cfg(), get_auth_class(), get_peer_match(), is_compliant(), load_method(), log_auth_cfgs(), log_ike_sa(), METHOD(), send_certreq(), and send_supported_hash_algorithms().
enumerator_t*(* peer_cfg_t::create_child_cfg_enumerator)(peer_cfg_t *this)
Create an enumerator for all attached CHILD configs.
Returns
an enumerator over all CHILD configs.
Definition at line 161 of file peer_cfg.h.
Referenced by CALLBACK(), clear_start_actions(), do_load_test(), find_child_cfg(), get_child_from_peer(), get_remote_identity_id(), initiate(), initiate_config(), METHOD(), on_accept(), replace_children(), request_control_initiate(), request_query_config(), and run_start_actions().
enumerator_t*(* peer_cfg_t::create_pool_enumerator)(peer_cfg_t *this)
Create an enumerator over pool names of this config.
Returns
enumerator over char*
Definition at line 299 of file peer_cfg.h.
Referenced by build_reply(), build_set(), have_pool(), METHOD(), mode_config_expected(), and process_ike_update().
enumerator_t*(* peer_cfg_t::create_virtual_ip_enumerator)(peer_cfg_t *this)
Create an enumerator over virtual IPs to request.
The returned enumerator enumerates over IPs added with add_virtual_ip().
Returns
enumerator over host_t*
Definition at line 285 of file peer_cfg.h.
Referenced by accept_push(), build_request(), METHOD(), and mode_config_expected().
void(* peer_cfg_t::destroy)(peer_cfg_t *this)
Destroys the peer_cfg object.
Decrements the internal reference counter and destroys the peer_cfg when it reaches zero.
Definition at line 352 of file peer_cfg.h.
Referenced by build_peer_cfg(), CALLBACK(), connect_(), initiate(), initiate_connection(), merge_config(), METHOD(), on_accept(), peer_enum_filter_destroy(), process_ike_update(), request_control_initiate(), and schedule_autoinit().
bool(* peer_cfg_t::equals)(peer_cfg_t *this, peer_cfg_t *other)
Check if two peer configurations are equal.
This method does not compare associated ike/child_cfg.
Parameters
other candidate to check for equality against this
Returns
TRUE if peer_cfg and ike_cfg are equal
Definition at line 337 of file peer_cfg.h.
Referenced by merge_config(), and METHOD().
cert_policy_t(* peer_cfg_t::get_cert_policy)(peer_cfg_t *this)
Should a certificate be sent for this connection?
Returns
certificate sending policy
Definition at line 197 of file peer_cfg.h.
Referenced by build_certs().
u_int32_t(* peer_cfg_t::get_dpd)(peer_cfg_t *this)
Get the DPD check interval.
Returns
dpd_delay in seconds
Definition at line 262 of file peer_cfg.h.
Referenced by METHOD().
u_int32_t(* peer_cfg_t::get_dpd_timeout)(peer_cfg_t *this)
Get the DPD timeout interval (IKEv1 only)
Returns
dpd_timeout in seconds
Definition at line 269 of file peer_cfg.h.
Referenced by METHOD().
ike_cfg_t*(* peer_cfg_t::get_ike_cfg)(peer_cfg_t *this)
Get the IKE config to use for initiaton.
Returns
the IKE config to use
Definition at line 140 of file peer_cfg.h.
Referenced by CALLBACK(), merge_config(), METHOD(), and request_query_config().
ike_version_t(* peer_cfg_t::get_ike_version)(peer_cfg_t *this)
Get the IKE version to use for initiating.
Returns
IKE major version
Definition at line 133 of file peer_cfg.h.
Referenced by CALLBACK(), and METHOD().
u_int32_t(* peer_cfg_t::get_keyingtries)(peer_cfg_t *this)
Get the max number of retries after timeout.
Returns
max number retries
Definition at line 211 of file peer_cfg.h.
char*(* peer_cfg_t::get_name)(peer_cfg_t *this)
Get the name of the peer_cfg.
Returned object is not getting cloned.
Returns
peer_cfg's name
Definition at line 126 of file peer_cfg.h.
Referenced by CALLBACK(), get_ike_sa_name(), load_cfg_candidates(), log_auth_cfgs(), merge_config(), METHOD(), request_query_config(), select_compliant_config(), and status().
u_int32_t(* peer_cfg_t::get_over_time)(peer_cfg_t *this)
Get the timeout of a rekeying/reauthenticating SA.
Returns
timeout in s
Definition at line 234 of file peer_cfg.h.
u_int32_t(* peer_cfg_t::get_reauth_time)(peer_cfg_t *this, bool jitter)
Get a time to start reauthentication.
Parameters
jitter remove a jitter value to randomize time
Returns
time in s when to start reauthentication, 0 disables it
Definition at line 227 of file peer_cfg.h.
peer_cfg_t*(* peer_cfg_t::get_ref)(peer_cfg_t *this)
Increase reference count.
Returns
reference to this
Definition at line 344 of file peer_cfg.h.
Referenced by find_child_cfg(), initiate_config(), load_cfg_candidates(), METHOD(), and run_start_action().
u_int32_t(* peer_cfg_t::get_rekey_time)(peer_cfg_t *this, bool jitter)
Get a time to start rekeying.
Parameters
jitter remove a jitter value to randomize time
Returns
time in s when to start rekeying, 0 disables rekeying
Definition at line 219 of file peer_cfg.h.
unique_policy_t(* peer_cfg_t::get_unique_policy)(peer_cfg_t *this)
How to handle uniqueness of IKE_SAs?
Returns
unique policy
Definition at line 204 of file peer_cfg.h.
Referenced by METHOD().
void(* peer_cfg_t::remove_child_cfg)(peer_cfg_t *this, enumerator_t *enumerator)
Detach a CHILD config, pointed to by an enumerator.
Parameters
enumerator enumerator indicating element position
Definition at line 154 of file peer_cfg.h.
Referenced by METHOD(), and replace_children().
child_cfg_t*(* peer_cfg_t::select_child_cfg)(peer_cfg_t *this, linked_list_t *my_ts, linked_list_t *other_ts, linked_list_t *my_hosts, linked_list_t *other_hosts)
Select a CHILD config from traffic selectors.
Parameters
my_ts TS for local side
other_ts TS for remote side
my_hosts hosts to narrow down dynamic TS for local side
other_hosts hosts to narrow down dynamic TS for remote side
Returns
selected CHILD config, or NULL if no match found
Definition at line 172 of file peer_cfg.h.
Referenced by METHOD(), and select_child_cfg().
bool(* peer_cfg_t::use_aggressive)(peer_cfg_t *this)
Use/Accept aggressive mode with IKEv1?.
Returns
TRUE to use aggressive mode
Definition at line 248 of file peer_cfg.h.
Referenced by create_fragment(), lookup_shared_key(), and METHOD().
bool(* peer_cfg_t::use_mobike)(peer_cfg_t *this)
Use MOBIKE (RFC4555) if peer supports it?
Returns
TRUE to enable MOBIKE support
Definition at line 241 of file peer_cfg.h.
Referenced by METHOD(), and process_payloads().
bool(* peer_cfg_t::use_pull_mode)(peer_cfg_t *this)
Use pull or push mode for mode config?
Returns
TRUE to use pull, FALSE to use push mode
Definition at line 255 of file peer_cfg.h.
Referenced by accept_push(), and mode_config_expected().
The documentation for this struct was generated from the following file:
peer_cfg.h