strongSwan: aesni_cbc
aesni_cbc
aesni
Classes
struct aesni_cbc_t
Typedefs
typedef struct aesni_cbc_t aesni_cbc_t
Functions
aesni_cbc_t * aesni_cbc_create (encryption_algorithm_t algo, size_t key_size)
Detailed Description
Typedef Documentation
typedef struct aesni_cbc_t aesni_cbc_t
Definition at line 26 of file aesni_cbc.h.
Function Documentation
aesni_cbc_t* aesni_cbc_create (encryption_algorithm_t algo, size_t key_size)
Create a aesni_cbc instance.
Parameters
algo encryption algorithm, AES_ENCR_CBC
key_size AES key size, in bytes
Returns
AES-CBC crypter, NULL if not supported
See header
Definition at line 618 of file aesni_cbc.c.
References decrypt, decrypt_cbc128(), decrypt_cbc192(), decrypt_cbc256(), ENCR_AES_CBC, encrypt(), encrypt_cbc128(), encrypt_cbc192(), encrypt_cbc256(), INIT_ALIGN, and key_size.
Referenced by METHOD().
 {
     private_aesni_cbc_t *this;
     if (algo != ENCR_AES_CBC)
     {
         return NULL;
     }
     switch (key_size)
     {
         case 0:
             key_size = 16;
             break;
         case 16:
         case 24:
         case 32:
             break;
         default:
             return NULL;
     }
     INIT_ALIGN(this, sizeof(__m128i),
         .public = {
             .crypter = {
                 .encrypt = _encrypt,
                 .decrypt = _decrypt,
                 .get_block_size = _get_block_size,
                 .get_iv_size = _get_iv_size,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .key_size = key_size,
     );
     switch (key_size)
     {
         case 16:
             this->encrypt = encrypt_cbc128;
             this->decrypt = decrypt_cbc128;
             break;
         case 24:
             this->encrypt = encrypt_cbc192;
             this->decrypt = decrypt_cbc192;
             break;
         case 32:
             this->encrypt = encrypt_cbc256;
             this->decrypt = decrypt_cbc256;
             break;
     }
     return &this->public;
 }