strongSwan: private_key
private_key
keys
Classes
struct private_key_t
Typedefs
typedef struct private_key_t private_key_t
Functions
bool private_key_equals (private_key_t *private, private_key_t *other)
bool private_key_belongs_to (private_key_t *private, public_key_t *public)
bool private_key_has_fingerprint (private_key_t *private, chunk_t fingerprint)
Detailed Description
Typedef Documentation
typedef struct private_key_t private_key_t
Definition at line 24 of file private_key.h.
Function Documentation
bool private_key_belongs_to (private_key_t * private, public_key_t * public)
Generic private key belongs_to() implementation, usable by implementors.
Parameters
private private key to check
public public key to compare
Returns
TRUE if this is equal to other
See header.
Definition at line 45 of file private_key.c.
References a, b, chunk_equals(), CRED_ENCODING_MAX, FALSE, private, and type.
Referenced by agent_private_key_open(), bliss_private_key_create_empty(), create_empty(), gmp_rsa_private_key_create_empty(), pkcs11_private_key_connect(), read_key(), and tkm_private_key_init().
 {
     cred_encoding_type_t type;
     chunk_t a, b;
     for (type = 0; type < CRED_ENCODING_MAX; type++)
     {
         if (private->get_fingerprint(private, type, &a) &&
             public->get_fingerprint(public, type, &b))
         {
             return chunk_equals(a, b);
         }
     }
     return FALSE;
 }
bool private_key_equals (private_key_t * this, private_key_t * other)
Generic private key equals() implementation, usable by implementors.
Parameters
private private key to check
other key to compare
Returns
TRUE if this is equal to other
See header.
Definition at line 21 of file private_key.c.
References a, b, chunk_equals(), CRED_ENCODING_MAX, FALSE, private_key_t::get_fingerprint, TRUE, and type.
Referenced by agent_private_key_open(), bliss_private_key_create_empty(), create_empty(), gmp_rsa_private_key_create_empty(), pkcs11_private_key_connect(), and tkm_private_key_init().
 {
     cred_encoding_type_t type;
     chunk_t a, b;
     if (this == other)
     {
         return TRUE;
     }
     for (type = 0; type < CRED_ENCODING_MAX; type++)
     {
         if (this->get_fingerprint(this, type, &a) &&
             other->get_fingerprint(other, type, &b))
         {
             return chunk_equals(a, b);
         }
     }
     return FALSE;
 }
bool private_key_has_fingerprint (private_key_t * private, chunk_t fingerprint)
Generic private key has_fingerprint() implementation, usable by implementors.
Parameters
private private key to check
fingerprint fingerprint to check
Returns
TRUE if key has given fingerprint
See header.
Definition at line 64 of file private_key.c.
References chunk_equals(), FALSE, KEYID_MAX, private, TRUE, and type.
Referenced by agent_private_key_open(), bliss_private_key_create_empty(), create_empty(), gmp_rsa_private_key_create_empty(), pkcs11_private_key_connect(), and tkm_private_key_init().
 {
     cred_encoding_type_t type;
     chunk_t current;
     for (type = 0; type < KEYID_MAX; type++)
     {
         if (private->get_fingerprint(private, type, &current) &&
             chunk_equals(current, fingerprint))
         {
             return TRUE;
         }
     }
     return FALSE;
 }