strongSwan: addrblock_validator.c File Reference
addrblock_validator.c File Reference
#include "addrblock_validator.h"
#include <utils/debug.h>
#include <credentials/certificates/x509.h>
#include <selectors/traffic_selector.h>
Classes
struct private_addrblock_validator_t
Typedefs
typedef struct
private_addrblock_validator_t private_addrblock_validator_t
Functions
static bool check_addrblock (x509_t *subject, x509_t *issuer)
METHOD (cert_validator_t, validate, bool, private_addrblock_validator_t *this, certificate_t *subject, certificate_t *issuer, bool online, u_int pathlen, bool anchor, auth_cfg_t *auth)
METHOD (addrblock_validator_t, destroy, void, private_addrblock_validator_t *this)
addrblock_validator_t * addrblock_validator_create ()
Typedef Documentation
typedef struct private_addrblock_validator_t private_addrblock_validator_t
Definition at line 22 of file addrblock_validator.c.
Function Documentation
static bool check_addrblock (x509_t * subject, x509_t * issuer) static
Do the addrblock check for two x509 plugins
Definition at line 38 of file addrblock_validator.c.
References contained, x509_t::create_ipAddrBlock_enumerator, DBG1, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, x509_t::get_flags, traffic_selector_t::is_contained_in, TRUE, and X509_IP_ADDR_BLOCKS.
Referenced by METHOD().
 {
     bool subject_const, issuer_const, contained = TRUE;
     enumerator_t *subject_enumerator, *issuer_enumerator;
     traffic_selector_t *subject_ts, *issuer_ts;
     subject_const = subject->get_flags(subject) & X509_IP_ADDR_BLOCKS;
     issuer_const = issuer->get_flags(issuer) & X509_IP_ADDR_BLOCKS;
     if (!subject_const && !issuer_const)
     {
         return TRUE;
     }
     if (!subject_const)
     {
         DBG1(DBG_CFG, "subject certficate lacks ipAddrBlocks extension");
         return FALSE;
     }
     if (!issuer_const)
     {
         DBG1(DBG_CFG, "issuer certficate lacks ipAddrBlocks extension");
         return FALSE;
     }
     subject_enumerator = subject->create_ipAddrBlock_enumerator(subject);
     while (subject_enumerator->enumerate(subject_enumerator, &subject_ts))
     {
         contained = FALSE;
         issuer_enumerator = issuer->create_ipAddrBlock_enumerator(issuer);
         while (issuer_enumerator->enumerate(issuer_enumerator, &issuer_ts))
         {
             if (subject_ts->is_contained_in(subject_ts, issuer_ts))
             {
                 DBG2(DBG_CFG, "  subject address block %R is contained in "
                               "issuer address block %R", subject_ts, issuer_ts);
                 contained = TRUE;
                 break;
             }
         }
         issuer_enumerator->destroy(issuer_enumerator);
         if (!contained)
         {
             DBG1(DBG_CFG, "subject address block %R is not contained in any "
                           "issuer address block", subject_ts);
             break;
         }
     }
     subject_enumerator->destroy(subject_enumerator);
     return contained;
 }
METHOD (cert_validator_t , validate , bool , private_addrblock_validator_t * this, certificate_t * subject, certificate_t * issuer, bool online, u_int pathlen, bool anchor, auth_cfg_t * auth)
Definition at line 89 of file addrblock_validator.c.
References credential_manager_t::call_hook, CERT_X509, check_addrblock(), CRED_HOOK_POLICY_VIOLATION, library_t::credmgr, FALSE, certificate_t::get_type, lib, and TRUE.
 {
     if (subject->get_type(subject) == CERT_X509 &&
         issuer->get_type(issuer) == CERT_X509)
     {
         if (!check_addrblock((x509_t*)subject, (x509_t*)issuer))
         {
             lib->credmgr->call_hook(lib->credmgr, CRED_HOOK_POLICY_VIOLATION,
                                     subject);
             return FALSE;
         }
     }
     return TRUE;
 }
METHOD (addrblock_validator_t , destroy , void , private_addrblock_validator_t * this)
Definition at line 107 of file addrblock_validator.c.
References free().
 {
     free(this);
 }