strongSwan: processor
processor
processing
Modules
watcher
Classes
struct processor_t
Typedefs
typedef struct processor_t processor_t
Functions
processor_t * processor_create ()
Detailed Description
Typedef Documentation
typedef struct processor_t processor_t
Definition at line 28 of file processor.h.
Function Documentation
processor_t* processor_create ()
Create the thread pool without any threads.
Use the set_threads method to start processing jobs.
Returns
processor_t object
Definition at line 532 of file processor.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, settings_t::get_int, INIT, JOB_PRIO_MAX, job_priority_names, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, and library_t::settings.
Referenced by library_init().
 {
     private_processor_t *this;
     int i;
     INIT(this,
         .public = {
             .get_total_threads = _get_total_threads,
             .get_idle_threads = _get_idle_threads,
             .get_working_threads = _get_working_threads,
             .get_job_load = _get_job_load,
             .queue_job = _queue_job,
             .execute_job = _execute_job,
             .set_threads = _set_threads,
             .cancel = _cancel,
             .destroy = _destroy,
         },
         .threads = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .job_added = condvar_create(CONDVAR_TYPE_DEFAULT),
         .thread_terminated = condvar_create(CONDVAR_TYPE_DEFAULT),
     );
     for (i = 0; i < JOB_PRIO_MAX; i++)
     {
         this->jobs[i] = linked_list_create();
         this->prio_threads[i] = lib->settings->get_int(lib->settings,
                         "%s.processor.priority_threads.%N", 0, lib->ns,
                         job_priority_names, i);
     }
     return &this->public;
 }