strongSwan: unsort_message.c File Reference
unsort_message.c File Reference
#include "hook.h"
Classes
struct private_unsort_message_t
Typedefs
typedef struct
private_unsort_message_t private_unsort_message_t
Functions
METHOD (listener_t, message, bool, private_unsort_message_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (hook_t, destroy, void, private_unsort_message_t *this)
hook_t * unsort_message_hook_create (char *name)
Typedef Documentation
typedef struct private_unsort_message_t private_unsort_message_t
Definition at line 18 of file unsort_message.c.
Function Documentation
METHOD (listener_t , message , bool , private_unsort_message_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 46 of file unsort_message.c.
References message_t::add_payload, linked_list_t::create_enumerator, message_t::create_payload_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, linked_list_t::destroy, message_t::disable_sort, enum_from_name, enumerator_t::enumerate, enumerator_create_token(), message_t::get_message_id, message_t::get_request, payload_t::get_type, id, linked_list_t::insert_last, linked_list_create(), list, name, payload_type_short_names, linked_list_t::remove_at, linked_list_t::remove_first, message_t::remove_payload_at, req(), SUCCESS, TRUE, and type.
 {
     if (!incoming && plain &&
         message->get_request(message) == this->req &&
         message->get_message_id(message) == this->id)
     {
         enumerator_t *enumerator, *order;
         linked_list_t *list;
         payload_type_t type;
         payload_t *payload;
         char *name;
         list = linked_list_create();
         enumerator = message->create_payload_enumerator(message);
         while (enumerator->enumerate(enumerator, &payload))
         {
             message->remove_payload_at(message, enumerator);
             list->insert_last(list, payload);
         }
         enumerator->destroy(enumerator);
         order = enumerator_create_token(this->order, ", ", " ");
         while (order->enumerate(order, &name))
         {
             if (enum_from_name(payload_type_short_names, name, &type))
             {
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &payload))
                 {
                     if (payload->get_type(payload) == type)
                     {
                         list->remove_at(list, enumerator);
                         message->add_payload(message, payload);
                     }
                 }
                 enumerator->destroy(enumerator);
             }
             else
             {
                 DBG1(DBG_CFG, "unknown payload to sort: '%s', skipped", name);
             }
         }
         order->destroy(order);
         while (list->remove_first(list, (void**)&payload) == SUCCESS)
         {
             message->add_payload(message, payload);
         }
         list->destroy(list);
         message->disable_sort(message);
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_unsort_message_t * this)
Definition at line 103 of file unsort_message.c.
References free().
 {
     free(this);
 }
hook_t* unsort_message_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 112 of file unsort_message.c.
References conftest, settings_t::get_bool, settings_t::get_int, settings_t::get_str, INIT, conftest_t::test, and TRUE.
 {
     private_unsort_message_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .message = _message,
             },
             .destroy = _destroy,
         },
         .req = conftest->test->get_bool(conftest->test,
                                         "hooks.%s.request", TRUE, name),
         .id = conftest->test->get_int(conftest->test,
                                         "hooks.%s.id", 0, name),
         .order = conftest->test->get_str(conftest->test,
                                         "hooks.%s.order", "", name),
     );
     return &this->hook;
 }