strongSwan: farp_listener.c File Reference
farp_listener.c File Reference
#include "farp_listener.h"
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_farp_listener_t
struct entry_t
Typedefs
typedef struct
private_farp_listener_t private_farp_listener_t
Functions
METHOD (listener_t, child_updown, bool, private_farp_listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool up)
METHOD (farp_listener_t, has_tunnel, bool, private_farp_listener_t *this, host_t *local, host_t *remote)
METHOD (farp_listener_t, destroy, void, private_farp_listener_t *this)
farp_listener_t * farp_listener_create ()
Typedef Documentation
typedef struct private_farp_listener_t private_farp_listener_t
Definition at line 21 of file farp_listener.c.
Function Documentation
METHOD (listener_t , child_updown , bool , private_farp_listener_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, bool up)
Definition at line 56 of file farp_listener.c.
References traffic_selector_t::clone, child_sa_t::create_ts_enumerator, enumerator_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, FALSE, free(), child_sa_t::get_reqid, INIT, linked_list_t::insert_last, linked_list_create(), entry_t::local, lock, entry_t::remote, entry_t::reqid, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     entry_t *entry;
     if (up)
     {
         INIT(entry,
             .local = linked_list_create(),
             .remote = linked_list_create(),
             .reqid = child_sa->get_reqid(child_sa),
         );
         enumerator = child_sa->create_ts_enumerator(child_sa, TRUE);
         while (enumerator->enumerate(enumerator, &ts))
         {
             entry->local->insert_last(entry->local, ts->clone(ts));
         }
         enumerator->destroy(enumerator);
         enumerator = child_sa->create_ts_enumerator(child_sa, FALSE);
         while (enumerator->enumerate(enumerator, &ts))
         {
             entry->remote->insert_last(entry->remote, ts->clone(ts));
         }
         enumerator->destroy(enumerator);
         this->lock->write_lock(this->lock);
         this->entries->insert_last(this->entries, entry);
         this->lock->unlock(this->lock);
     }
     else
     {
         this->lock->write_lock(this->lock);
         enumerator = this->entries->create_enumerator(this->entries);
         while (enumerator->enumerate(enumerator, &entry))
         {
             if (entry->reqid == child_sa->get_reqid(child_sa))
             {
                 this->entries->remove_at(this->entries, enumerator);
                 entry->local->destroy_offset(entry->local,
                                         offsetof(traffic_selector_t, destroy));
                 entry->remote->destroy_offset(entry->remote,
                                         offsetof(traffic_selector_t, destroy));
                 free(entry);
             }
         }
         enumerator->destroy(enumerator);
         this->lock->unlock(this->lock);
     }
     return TRUE;
 }
METHOD (farp_listener_t , has_tunnel , bool , private_farp_listener_t * this, host_t * local, host_t * remote)
Definition at line 112 of file farp_listener.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, traffic_selector_t::includes, entry_t::local, locals, lock, entry_t::remote, and spinlock_t::unlock.
 {
     enumerator_t *entries, *locals, *remotes;
     traffic_selector_t *ts;
     bool found = FALSE;
     entry_t *entry;
     this->lock->read_lock(this->lock);
     entries = this->entries->create_enumerator(this->entries);
     while (!found && entries->enumerate(entries, &entry))
     {
         remotes = entry->remote->create_enumerator(entry->remote);
         while (!found && remotes->enumerate(remotes, &ts))
         {
             if (ts->includes(ts, remote))
             {
                 locals = entry->local->create_enumerator(entry->local);
                 while (!found && locals->enumerate(locals, &ts))
                 {
                     found = ts->includes(ts, local);
                 }
                 locals->destroy(locals);
             }
         }
         remotes->destroy(remotes);
     }
     entries->destroy(entries);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (farp_listener_t , destroy , void , private_farp_listener_t * this)
Definition at line 145 of file farp_listener.c.
References spinlock_t::destroy, free(), and lock.
 {
     this->entries->destroy(this->entries);
     this->lock->destroy(this->lock);
     free(this);
 }