strongSwan: sshkey_plugin.c File Reference
sshkey_plugin.c File Reference
#include "sshkey_plugin.h"
#include <library.h>
#include "sshkey_builder.h"
#include "sshkey_encoder.h"
Classes
struct private_sshkey_plugin_t
Typedefs
typedef struct
private_sshkey_plugin_t private_sshkey_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_sshkey_plugin_t *this)
METHOD (plugin_t, get_features, int, private_sshkey_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_sshkey_plugin_t *this)
plugin_t * sshkey_plugin_create ()
Typedef Documentation
typedef struct private_sshkey_plugin_t private_sshkey_plugin_t
Definition at line 22 of file sshkey_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_sshkey_plugin_t * this)
Definition at line 35 of file sshkey_plugin.c.
 {
     return "sshkey";
 }
METHOD (plugin_t , get_features , int , private_sshkey_plugin_t * this, plugin_feature_t * features[])
Definition at line 41 of file sshkey_plugin.c.
References CERT_TRUSTED_PUBKEY, countof, FALSE, KEY_ANY, PLUGIN_PROVIDE, PLUGIN_REGISTER, sshkey_certificate_load(), and sshkey_public_key_load().
 {
     static plugin_feature_t f[] = {
         PLUGIN_REGISTER(PUBKEY, sshkey_public_key_load, FALSE),
             PLUGIN_PROVIDE(PUBKEY, KEY_ANY),
         PLUGIN_REGISTER(CERT_DECODE, sshkey_certificate_load, FALSE),
             PLUGIN_PROVIDE(CERT_DECODE, CERT_TRUSTED_PUBKEY),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_sshkey_plugin_t * this)
Definition at line 54 of file sshkey_plugin.c.
References library_t::encoding, free(), lib, cred_encoding_t::remove_encoder, and sshkey_encoder_encode().
 {
     lib->encoding->remove_encoder(lib->encoding, sshkey_encoder_encode);
     free(this);
 }
plugin_t* sshkey_plugin_create ()
Definition at line 64 of file sshkey_plugin.c.
References cred_encoding_t::add_encoder, library_t::encoding, INIT, lib, and sshkey_encoder_encode().
 {
     private_sshkey_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     lib->encoding->add_encoder(lib->encoding, sshkey_encoder_encode);
     return &this->public.plugin;
 }