strongSwan: string
string
utils
Functions
static bool streq (const char *x, const char *y)
static bool strneq (const char *x, const char *y, size_t len)
static bool strpfx (const char *x, const char *prefix)
static bool strcaseeq (const char *x, const char *y)
static bool strncaseeq (const char *x, const char *y, size_t len)
static bool strcasepfx (const char *x, const char *prefix)
static char * strdupnull (const char *s)
char * translate (char *str, const char *from, const char *to)
char * strreplace (const char *str, const char *search, const char *replace)
Detailed Description
Function Documentation
static bool strcaseeq (const char * x, const char * y) inline static
Helper function that compares two strings for equality ignoring case
Definition at line 52 of file string.h.
Referenced by CALLBACK(), close_ike(), decrypt_with_config(), eap_tnc_create(), eap_type_from_string(), enum_from_name_as_int(), filter_cipher_config_suites(), filter_key_exchange_config_suites(), filter_mac_config_suites(), is_attribute(), is_file_list_key(), is_list_key(), liveness(), main(), parse_attributes(), parse_map(), parse_parameter(), parse_proposal(), parse_rounds(), pts_dh_group_update(), pts_meas_algo_update(), rekey_ike(), settings_value_as_bool(), and stroke_loglevel().
 {
     return strcasecmp(x, y) == 0;
 }
static bool strcasepfx (const char * x, const char * prefix) inline static
Helper function that checks if a string starts with a given prefix
Definition at line 68 of file string.h.
References strncaseeq().
Referenced by CALLBACK(), create_from_string_with_prefix_type(), get_next_test_vector(), load_secret(), mark_from_string(), servicing(), and START_TEST().
 {
     return strncaseeq(x, prefix, strlen(prefix));
 }
static char* strdupnull (const char * s) inline static
NULL-safe strdup variant
Definition at line 76 of file string.h.
References strdup.
Referenced by assign_arg(), child_cfg_create(), conf_parser_create(), conn_defaults(), getenv_cb(), handle_firewall(), kw_end(), library_init(), load_conn(), METHOD(), set_value(), START_TEST(), and x509_cert_gen().
 {
     return s ? strdup(s) : NULL;
 }
static bool streq (const char * x, const char * y) inline static
Helper function that compares two strings for equality
Definition at line 28 of file string.h.
Referenced by add_file_list_key(), add_key_values(), add_ts(), assign_arg(), attack_chunk(), attack_memeq(), bridge_find(), build_auth_cfg(), build_binary_checksum(), build_peer_cfg(), ca_filter(), CALLBACK(), check_for_rekeyed_child(), check_oid(), clear_start_action(), close_child(), compare_vici(), conn_filter(), connect_(), connect_guest(), connection_name(), contains_dir(), create_lease_query(), create_switch(), dbus_req_handler(), determine_credtype(), dispatch(), dlsym_next(), dn(), do_remove(), do_remove_at(), eap_vendor_type_from_string(), entry_equals(), enumerate_dir_enum(), equals(), find_checksum(), find_child_cfg(), find_lib(), find_pool(), find_reqid(), find_token(), find_value(), gen(), generate_auth_cfg(), generate_config(), get_child_from_peer(), get_form(), get_pool(), get_separator(), get_syslog_facility(), guest_find_iface(), handle_keyword(), handle_result(), handle_syslog_identifier(), hashtable_equals_str(), host_create_from_string_and_family(), identification_create_from_string(), iface_entry_by_name(), ike_cfg_get_family(), imc_imv_msg_create_from_node(), imv_lang_string_select_lang(), imv_lang_string_select_string(), init_address_list(), initiate(), initiate_connection(), is_contained_in(), is_redundant(), is_reinject_config(), issue(), kernel_netlink_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), keyid(), kw_end(), list(), load_authority(), load_cert(), load_conn(), load_entries(), load_key(), load_loggers(), load_pool(), load_secret(), logger_entry_match(), main(), manage_policy(), manage_route(), merge_config(), METHOD(), need_secrets(), net_change_equals(), ntru_ke_create(), on_read(), on_write(), overlay_equals(), package_enumerator_enumerate(), parse_protoport(), parse_pubkey_constraints(), parse_ranges(), parse_rules(), parse_validation_uri(), pkcs11_creds_load(), plugin_feature_equals(), plugin_feature_matches(), plugin_loaded(), print(), process(), process_childsa(), process_ikesa(), process_peerconfig(), process_sasl(), pub(), query_equals(), read_result(), receive_msg(), reinstall_routes(), rekey_child(), reload_by_name(), reload_settings(), remove_from_list(), repopulate_iface(), req(), request(), request_control(), request_control_initiate(), request_control_terminate(), request_query(), route_entry_equals(), sasl_mechanism_create(), sasl_plain_create(), self(), send_stroke_msg(), servicing(), session_equals(), settings_kv_set(), settings_parser_parse_file(), setup_interface(), sign_crl(), simaka_manager_register(), START_TEST(), starter_stroke_add_conn(), status(), stroke_export(), terminate(), TNC_IMC_BeginHandshake(), tnc_manager_register(), TNC_TNCC_BindFunction(), TNC_TNCS_BindFunction(), tnccs_method_register(), tnccs_msg_create_from_node(), tnccs_recommendation_msg_create_from_node(), unload_authority(), unload_conn(), unload_pool(), update_database(), verify(), verify_list(), verify_password(), vici_parse_name_eq(), and while().
 {
     return strcmp(x, y) == 0;
 }
static bool strncaseeq (const char * x, const char * y, size_t len) inline static
Helper function that compares two strings for equality ignoring case, length limited
Definition at line 60 of file string.h.
Referenced by has_entry(), load_action(), load_cdps(), load_cert(), load_keys(), METHOD(), soap_init(), and strcasepfx().
 {
     return strncasecmp(x, y, len) == 0;
 }
static bool strneq (const char * x, const char * y, size_t len) inline static
Helper function that compares two strings for equality, length limited
Definition at line 36 of file string.h.
Referenced by equal_match(), present(), query_protocols(), START_TEST(), and strpfx().
 {
     return strncmp(x, y, len) == 0;
 }
static bool strpfx (const char * x, const char * prefix) inline static
Helper function that checks if a string starts with a given prefix
Definition at line 44 of file string.h.
References strneq().
Referenced by add_feature_with_ssl(), build_auth_cfg(), CALLBACK(), decrypt_with_config(), generate_auth_cfg(), get_next_test_vector(), load_ca_cert(), load_from_file(), load_from_stream(), load_pin(), load_secret(), load_secrets(), main(), METHOD(), mysql_database_create(), openssl_plugin_create(), parse_public_key(), path_absolute(), process_peer_failure(), process_peer_success(), remove_nameserver(), sqlite_database_create(), START_TEST(), stream_parse_uri_tcp(), and stream_parse_uri_unix().
 {
     return strneq(x, prefix, strlen(prefix));
 }
char* strreplace (const char * str, const char * search, const char * replace)
Replaces all occurrences of search in the given string with replace.
Allocates memory only if anything is replaced in the string. The original string is also returned if any of the arguments are invalid (e.g. if search is empty or any of them are NULL).
Parameters
str original string
search string to search for and replace
replace string to replace found occurrences with
Returns
allocated string, if anything got replaced, str otherwise
Described in header.
Definition at line 44 of file string.c.
References count, dst, found, len, malloc(), memcpy, res, and str.
Referenced by METHOD(), and START_TEST().
 {
     size_t len, slen, rlen, count = 0;
     char *res, *pos, *found = NULL, *dst;
     if (!str || !*str || !search || !*search || !replace)
     {
         return (char*)str;
     }
     slen = strlen(search);
     rlen = strlen(replace);
     if (slen != rlen)
     {
         for (pos = (char*)str; (pos = strstr(pos, search)); pos += slen)
         {
             found = pos;
             count++;
         }
         if (!count)
         {
             return (char*)str;
         }
         len = (found - str) + strlen(found) + count * (rlen - slen);
     }
     else
     {
         len = strlen(str);
     }
     found = strstr(str, search);
     if (!found)
     {
         return (char*)str;
     }
     dst = res = malloc(len + 1);
     pos = (char*)str;
     do
     {
         len = found - pos;
         memcpy(dst, pos, len);
         dst += len;
         memcpy(dst, replace, rlen);
         dst += rlen;
         pos = found + slen;
     }
     while ((found = strstr(pos, search)));
     strcpy(dst, pos);
     return res;
 }
char* translate (char * str, const char * from, const char * to)
Translates the characters in the given string, searching for characters in 'from' and mapping them to characters in 'to'. The two characters sets 'from' and 'to' must contain the same number of characters.
Described in header.
Definition at line 22 of file string.c.
References from, match(), and str.
Referenced by build_plugin_checksums(), create_plugin(), plugin_loader_add_plugindirs(), and START_TEST().
 {
     char *pos = str;
     if (strlen(from) != strlen(to))
     {
         return str;
     }
     while (pos && *pos)
     {
         char *match;
         if ((match = strchr(from, *pos)) != NULL)
         {
             *pos = to[match - from];
         }
         pos++;
     }
     return str;
 }