strongSwan: ipseckey_cred.c File Reference
ipseckey_cred.c File Reference
#include <stdio.h>
#include <string.h>
#include "ipseckey_cred.h"
#include "ipseckey.h"
#include <bio/bio_reader.h>
Classes
struct private_ipseckey_cred_t
struct cert_enumerator_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_ipseckey_cred_t private_ipseckey_cred_t
Functions
METHOD (enumerator_t, cert_enumerator_enumerate, bool, cert_enumerator_t *this, certificate_t **cert)
METHOD (enumerator_t, cert_enumerator_destroy, void, cert_enumerator_t *this)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_ipseckey_cred_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (ipseckey_cred_t, destroy, void, private_ipseckey_cred_t *this)
ipseckey_cred_t * ipseckey_cred_create (resolver_t *res)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file ipseckey_cred.c.
Typedef Documentation
typedef struct private_ipseckey_cred_t private_ipseckey_cred_t
Definition at line 26 of file ipseckey_cred.c.
Function Documentation
METHOD (enumerator_t , cert_enumerator_enumerate , bool , cert_enumerator_t * this, certificate_t ** cert)
Definition at line 62 of file ipseckey_cred.c.
References BUILD_BLOB_DNSKEY, BUILD_END, BUILD_NOT_AFTER_TIME, BUILD_NOT_BEFORE_TIME, BUILD_PUBLIC_KEY, BUILD_SUBJECT, CERT_TRUSTED_PUBKEY, credential_factory_t::create, CRED_CERTIFICATE, CRED_PUBLIC_KEY, library_t::creds, DBG1, DBG_CFG, ipseckey_t::destroy, FALSE, ipseckey_t::get_algorithm, ipseckey_t::get_public_key, IPSECKEY_ALGORITHM_RSA, ipseckey_create_frm_rr(), key, KEY_RSA, lib, and TRUE.
 {
     ipseckey_t *cur_ipseckey;
     public_key_t *public;
     rr_t *cur_rr;
     chunk_t key;
     /* Get the next supported IPSECKEY using the inner enumerator. */
     while (this->inner->enumerate(this->inner, &cur_rr))
     {
         cur_ipseckey = ipseckey_create_frm_rr(cur_rr);
         if (!cur_ipseckey)
         {
             DBG1(DBG_CFG, "  failed to parse IPSECKEY, skipping");
             continue;
         }
         if (cur_ipseckey->get_algorithm(cur_ipseckey) != IPSECKEY_ALGORITHM_RSA)
         {
             DBG1(DBG_CFG, "  unsupported IPSECKEY algorithm, skipping");
             cur_ipseckey->destroy(cur_ipseckey);
             continue;
         }
         /* wrap the key of the IPSECKEY in a certificate and return this
          * certificate */
         key = cur_ipseckey->get_public_key(cur_ipseckey);
         public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                                     BUILD_BLOB_DNSKEY, key,
                                     BUILD_END);
         if (!public)
         {
             DBG1(DBG_CFG, "  failed to create public key from IPSECKEY");
             cur_ipseckey->destroy(cur_ipseckey);
             continue;
         }
         *cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                                    CERT_TRUSTED_PUBKEY,
                                    BUILD_PUBLIC_KEY, public,
                                    BUILD_SUBJECT, this->identity,
                                    BUILD_NOT_BEFORE_TIME, this->notBefore,
                                    BUILD_NOT_AFTER_TIME, this->notAfter,
                                    BUILD_END);
         if (*cert == NULL)
         {
             DBG1(DBG_CFG, "  failed to create certificate from IPSECKEY");
             cur_ipseckey->destroy(cur_ipseckey);
             public->destroy(public);
             continue;
         }
         cur_ipseckey->destroy(cur_ipseckey);
         return TRUE;
     }
     return FALSE;
 }
METHOD (enumerator_t , cert_enumerator_destroy , void , cert_enumerator_t * this)
Definition at line 121 of file ipseckey_cred.c.
References free(), and response.
 {
     this->inner->destroy(this->inner);
     this->response->destroy(this->response);
     free(this);
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_ipseckey_cred_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 129 of file ipseckey_cred.c.
References asprintf(), bio_reader_create(), rr_set_t::create_rr_enumerator, rr_set_t::create_rrsig_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, resolver_response_t::destroy, bio_reader_t::destroy, destroy(), DESTROY_IF, enumerator_t::enumerate, enumerator_create_empty(), free(), rr_t::get_rdata, resolver_response_t::get_rr_set, resolver_response_t::get_security_state, identification_t::get_type, resolver_response_t::has_data, id, ID_FQDN, ignore(), INIT, cert_enumerator_t::public, resolver_response_t::query_name_exist, bio_reader_t::read_data, bio_reader_t::read_uint32, res, response, RR_CLASS_IN, RR_TYPE_IPSECKEY, and SECURE.
 {
     resolver_response_t *response;
     enumerator_t *rrsig_enum;
     cert_enumerator_t *e;
     rr_set_t *rrset;
     rr_t *rrsig;
     bio_reader_t *reader;
     u_int32_t nBefore, nAfter;
     chunk_t ignore;
     char *fqdn;
     if (!id || id->get_type(id) != ID_FQDN)
     {
         return enumerator_create_empty();
     }
     /* query the DNS for the required IPSECKEY RRs */
     if (asprintf(&fqdn, "%Y", id) <= 0)
     {
         DBG1(DBG_CFG, "failed to determine FQDN to retrieve IPSECKEY RRs");
         return enumerator_create_empty();
     }
     DBG1(DBG_CFG, "performing a DNS query for IPSECKEY RRs of '%s'", fqdn);
     response = this->res->query(this->res, fqdn, RR_CLASS_IN, RR_TYPE_IPSECKEY);
     if (!response)
     {
         DBG1(DBG_CFG, "  query for IPSECKEY RRs failed");
         free(fqdn);
         return enumerator_create_empty();
     }
     free(fqdn);
     if (!response->has_data(response) ||
         !response->query_name_exist(response))
     {
         DBG1(DBG_CFG, "  unable to retrieve IPSECKEY RRs from the DNS");
         response->destroy(response);
         return enumerator_create_empty();
     }
     if (response->get_security_state(response) != SECURE)
     {
         DBG1(DBG_CFG, "  DNSSEC state of IPSECKEY RRs is not secure");
         response->destroy(response);
         return enumerator_create_empty();
     }
     /* determine the validity period of the retrieved IPSECKEYs
      *
      * we use the "Signature Inception" and "Signature Expiration" field
      * of the first RRSIG RR to determine the validity period of the
      * IPSECKEY RRs.
      * TODO: Take multiple RRSIGs into account. */
     rrset = response->get_rr_set(response);
     rrsig_enum = rrset->create_rrsig_enumerator(rrset);
     if (!rrsig_enum || !rrsig_enum->enumerate(rrsig_enum, &rrsig))
     {
         DBG1(DBG_CFG, "  unable to determine the validity period of "
              "IPSECKEY RRs because no RRSIGs are present");
         DESTROY_IF(rrsig_enum);
         response->destroy(response);
         return enumerator_create_empty();
     }
     rrsig_enum->destroy(rrsig_enum);
     /* parse the RRSIG for its validity period (RFC 4034) */
     reader = bio_reader_create(rrsig->get_rdata(rrsig));
     if (!reader->read_data(reader, 8, &ignore) ||
         !reader->read_uint32(reader, &nAfter) ||
         !reader->read_uint32(reader, &nBefore))
     {
         DBG1(DBG_CFG, "  unable to determine the validity period of RRSIG RRs");
         reader->destroy(reader);
         response->destroy(response);
         return enumerator_create_empty();
     }
     reader->destroy(reader);
     INIT(e,
         .public = {
             .enumerate = (void*)_cert_enumerator_enumerate,
             .destroy = _cert_enumerator_destroy,
         },
         .inner = rrset->create_rr_enumerator(rrset),
         .response = response,
         .notBefore = nBefore,
         .notAfter = nAfter,
         .identity = id,
     );
     return &e->public;
 }
METHOD (ipseckey_cred_t , destroy , void , private_ipseckey_cred_t * this)
Definition at line 224 of file ipseckey_cred.c.
References free(), and res.
 {
     this->res->destroy(this->res);
     free(this);
 }