strongSwan: pts.c File Reference
pts.c File Reference
#include "pts.h"
#include <utils/debug.h>
#include <crypto/hashers/hasher.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <libgen.h>
#include <unistd.h>
#include <errno.h>
Classes
struct private_pts_t
Macros
#define TPM_TAG_QUOTE_INFO2 0x0036
#define TPM_LOC_ZERO 0x01
Typedefs
typedef struct private_pts_t private_pts_t
Functions
METHOD (pts_t, get_proto_caps, pts_proto_caps_flag_t, private_pts_t *this)
METHOD (pts_t, set_proto_caps, void, private_pts_t *this, pts_proto_caps_flag_t flags)
METHOD (pts_t, get_meas_algorithm, pts_meas_algorithms_t, private_pts_t *this)
METHOD (pts_t, set_meas_algorithm, void, private_pts_t *this, pts_meas_algorithms_t algorithm)
METHOD (pts_t, get_dh_hash_algorithm, pts_meas_algorithms_t, private_pts_t *this)
METHOD (pts_t, set_dh_hash_algorithm, void, private_pts_t *this, pts_meas_algorithms_t algorithm)
METHOD (pts_t, create_dh_nonce, bool, private_pts_t *this, pts_dh_group_t group, int nonce_len)
METHOD (pts_t, get_my_public_value, bool, private_pts_t *this, chunk_t *value, chunk_t *nonce)
METHOD (pts_t, set_peer_public_value, bool, private_pts_t *this, chunk_t value, chunk_t nonce)
METHOD (pts_t, calculate_secret, bool, private_pts_t *this)
static void print_tpm_version_info (private_pts_t *this)
METHOD (pts_t, get_platform_id, int, private_pts_t *this)
METHOD (pts_t, set_platform_id, void, private_pts_t *this, int pid)
METHOD (pts_t, get_tpm_version_info, bool, private_pts_t *this, chunk_t *info)
METHOD (pts_t, set_tpm_version_info, void, private_pts_t *this, chunk_t info)
static void load_aik_blob (private_pts_t *this)
static void load_aik (private_pts_t *this)
METHOD (pts_t, get_aik, certificate_t *, private_pts_t *this)
METHOD (pts_t, set_aik, void, private_pts_t *this, certificate_t *aik, int aik_id)
METHOD (pts_t, get_aik_id, int, private_pts_t *this)
METHOD (pts_t, is_path_valid, bool, private_pts_t *this, char *path, pts_error_code_t *error_code)
static bool file_metadata (char *pathname, pts_file_metadata_t **entry)
METHOD (pts_t, get_metadata, pts_file_meta_t *, private_pts_t *this, char *pathname, bool is_directory)
METHOD (pts_t, read_pcr, bool, private_pts_t *this, u_int32_t pcr_num, chunk_t *pcr_value)
METHOD (pts_t, extend_pcr, bool, private_pts_t *this, u_int32_t pcr_num, chunk_t input, chunk_t *output)
METHOD (pts_t, quote_tpm, bool, private_pts_t *this, bool use_quote2, chunk_t *pcr_comp, chunk_t *quote_sig)
METHOD (pts_t, get_quote_info, bool, private_pts_t *this, bool use_quote2, bool use_ver_info, pts_meas_algorithms_t comp_hash_algo, chunk_t *out_pcr_comp, chunk_t *out_quote_info)
METHOD (pts_t, verify_quote_signature, bool, private_pts_t *this, chunk_t data, chunk_t signature)
METHOD (pts_t, get_pcrs, pts_pcr_t *, private_pts_t *this)
METHOD (pts_t, destroy, void, private_pts_t *this)
static bool has_tpm (private_pts_t *this)
pts_t * pts_create (bool is_imc)
Macro Definition Documentation
#define TPM_LOC_ZERO 0x01
Definition at line 36 of file pts.c.
Referenced by METHOD().
#define TPM_TAG_QUOTE_INFO2 0x0036
Definition at line 33 of file pts.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pts_t private_pts_t
Definition at line 46 of file pts.c.
Function Documentation
static bool file_metadata (char * pathname, pts_file_metadata_t ** entry) static
Obtain statistical information describing a file
Definition at line 500 of file pts.c.
References DBG1, DBG_PTS, FALSE, free(), group, malloc_thing, PTS_FILE_BLOCK_SPEC, PTS_FILE_CHAR_SPEC, PTS_FILE_DIRECTORY, PTS_FILE_FIFO, PTS_FILE_OTHER, PTS_FILE_REGULAR, PTS_FILE_SOCKET, PTS_FILE_SYM_LINK, TRUE, and type.
Referenced by METHOD().
 {
     struct stat st;
     pts_file_metadata_t *this;
     this = malloc_thing(pts_file_metadata_t);
     if (stat(pathname, &st))
     {
         DBG1(DBG_PTS, "unable to obtain statistics about '%s'", pathname);
         free(this);
         return FALSE;
     }
     if (S_ISREG(st.st_mode))
     {
         this->type = PTS_FILE_REGULAR;
     }
     else if (S_ISDIR(st.st_mode))
     {
         this->type = PTS_FILE_DIRECTORY;
     }
     else if (S_ISCHR(st.st_mode))
     {
         this->type = PTS_FILE_CHAR_SPEC;
     }
     else if (S_ISBLK(st.st_mode))
     {
         this->type = PTS_FILE_BLOCK_SPEC;
     }
     else if (S_ISFIFO(st.st_mode))
     {
         this->type = PTS_FILE_FIFO;
     }
 #ifndef WIN32
     else if (S_ISLNK(st.st_mode))
     {
         this->type = PTS_FILE_SYM_LINK;
     }
     else if (S_ISSOCK(st.st_mode))
     {
         this->type = PTS_FILE_SOCKET;
     }
 #endif /* WIN32 */
     else
     {
         this->type = PTS_FILE_OTHER;
     }
     this->filesize = st.st_size;
     this->created =  st.st_ctime;
     this->modified = st.st_mtime;
     this->accessed = st.st_atime;
     this->owner =    st.st_uid;
     this->group =    st.st_gid;
     *entry = this;
     return TRUE;
 }
static bool has_tpm (private_pts_t * this) static
Definition at line 1131 of file pts.c.
References FALSE.
Referenced by METHOD(), and pts_create().
 {
     return FALSE;
 }
static void load_aik (private_pts_t * this) static
Load an AIK certificate or public key the certificate having precedence over the public key if both are present
Definition at line 411 of file pts.c.
References BUILD_END, BUILD_FROM_FILE, CERT_TRUSTED_PUBKEY, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG2, DBG_PTS, settings_t::get_str, lib, library_t::ns, and library_t::settings.
Referenced by pts_create().
 {
     char *cert_path, *key_path;
     cert_path = lib->settings->get_str(lib->settings,
                         "%s.plugins.imc-attestation.aik_cert", NULL, lib->ns);
     key_path = lib->settings->get_str(lib->settings,
                         "%s.plugins.imc-attestation.aik_pubkey", NULL, lib->ns);
     if (cert_path)
     {
         this->aik = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                                        CERT_X509, BUILD_FROM_FILE,
                                        cert_path, BUILD_END);
         if (this->aik)
         {
             DBG2(DBG_PTS, "loaded AIK certificate from '%s'", cert_path);
             return;
         }
     }
     if (key_path)
     {
         this->aik = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                                        CERT_TRUSTED_PUBKEY, BUILD_FROM_FILE,
                                        key_path, BUILD_END);
         if (this->aik)
         {
             DBG2(DBG_PTS, "loaded AIK public key from '%s'", key_path);
             return;
         }
     }
     DBG1(DBG_PTS, "neither AIK certificate nor public key is available");
 }
static void load_aik_blob (private_pts_t * this) static
Load an AIK Blob (TSS_TSPATTRIB_KEYBLOB_BLOB attribute)
Definition at line 378 of file pts.c.
References chunk_clone, chunk_map(), chunk_unmap(), DBG1, DBG2, DBG3, DBG_PTS, FALSE, settings_t::get_str, lib, library_t::ns, path, library_t::settings, and strerror.
Referenced by pts_create().
 {
     char *path;
     chunk_t *map;
     path = lib->settings->get_str(lib->settings,
                         "%s.plugins.imc-attestation.aik_blob", NULL, lib->ns);
     if (path)
     {
         map = chunk_map(path, FALSE);
         if (map)
         {
             DBG2(DBG_PTS, "loaded AIK Blob from '%s'", path);
             DBG3(DBG_PTS, "AIK Blob: %B", map);
             this->aik_blob = chunk_clone(*map);
             chunk_unmap(map);
         }
         else
         {
             DBG1(DBG_PTS, "unable to map AIK Blob file '%s': %s",
                  path, strerror(errno));
         }
     }
     else
     {
         DBG1(DBG_PTS, "AIK Blob is not available");
     }
 }
METHOD (pts_t , get_proto_caps , pts_proto_caps_flag_t , private_pts_t * this)
Definition at line 136 of file pts.c.
 {
     return this->proto_caps;
 }
METHOD (pts_t , set_proto_caps , void , private_pts_t * this, pts_proto_caps_flag_t flags)
Definition at line 142 of file pts.c.
References DBG2, DBG_PTS, flags, PTS_PROTO_CAPS_C, PTS_PROTO_CAPS_D, PTS_PROTO_CAPS_T, PTS_PROTO_CAPS_V, and PTS_PROTO_CAPS_X.
 {
     this->proto_caps = flags;
     DBG2(DBG_PTS, "supported PTS protocol capabilities: %s%s%s%s%s",
          flags & PTS_PROTO_CAPS_C ? "C" : ".",
          flags & PTS_PROTO_CAPS_V ? "V" : ".",
          flags & PTS_PROTO_CAPS_D ? "D" : ".",
          flags & PTS_PROTO_CAPS_T ? "T" : ".",
          flags & PTS_PROTO_CAPS_X ? "X" : ".");
 }
METHOD (pts_t , get_meas_algorithm , pts_meas_algorithms_t , private_pts_t * this)
Definition at line 154 of file pts.c.
References algorithm.
 {
     return this->algorithm;
 }
METHOD (pts_t , set_meas_algorithm , void , private_pts_t * this, pts_meas_algorithms_t algorithm)
Definition at line 160 of file pts.c.
References algorithm, DBG2, DBG_PTS, hash_algorithm_names, HASH_UNKNOWN, and pts_meas_algo_to_hash().
 {
     hash_algorithm_t hash_alg;
     hash_alg = pts_meas_algo_to_hash(algorithm);
     DBG2(DBG_PTS, "selected PTS measurement algorithm is %N",
                    hash_algorithm_names, hash_alg);
     if (hash_alg != HASH_UNKNOWN)
     {
         this->algorithm = algorithm;
     }
 }
METHOD (pts_t , get_dh_hash_algorithm , pts_meas_algorithms_t , private_pts_t * this)
Definition at line 174 of file pts.c.
 {
     return this->dh_hash_algorithm;
 }
METHOD (pts_t , set_dh_hash_algorithm , void , private_pts_t * this, pts_meas_algorithms_t algorithm)
Definition at line 180 of file pts.c.
References algorithm, DBG2, DBG_PTS, hash_algorithm_names, HASH_UNKNOWN, and pts_meas_algo_to_hash().
 {
     hash_algorithm_t hash_alg;
     hash_alg = pts_meas_algo_to_hash(algorithm);
     DBG2(DBG_PTS, "selected DH hash algorithm is %N",
                    hash_algorithm_names, hash_alg);
     if (hash_alg != HASH_UNKNOWN)
     {
         this->dh_hash_algorithm = algorithm;
     }
 }
METHOD (pts_t , create_dh_nonce , bool , private_pts_t * this, pts_dh_group_t group, int nonce_len)
Definition at line 195 of file pts.c.
References rng_t::allocate_bytes, chunk_free(), crypto_factory_t::create_dh, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG2, DBG_PTS, rng_t::destroy, DESTROY_IF, dh, diffie_hellman_group_names, FALSE, lib, pts_dh_group_to_ike(), rng, RNG_STRONG, and TRUE.
 {
     diffie_hellman_group_t dh_group;
     chunk_t *nonce;
     rng_t *rng;
     dh_group = pts_dh_group_to_ike(group);
     DBG2(DBG_PTS, "selected PTS DH group is %N",
                    diffie_hellman_group_names, dh_group);
     DESTROY_IF(this->dh);
     this->dh = lib->crypto->create_dh(lib->crypto, dh_group);
     rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
     if (!rng)
     {
         DBG1(DBG_PTS, "no rng available");
         return FALSE;
     }
     DBG2(DBG_PTS, "nonce length is %d", nonce_len);
     nonce = this->is_imc ? &this->responder_nonce : &this->initiator_nonce;
     chunk_free(nonce);
     if (!rng->allocate_bytes(rng, nonce_len, nonce))
     {
         DBG1(DBG_PTS, "failed to allocate nonce");
         rng->destroy(rng);
         return FALSE;
     }
     rng->destroy(rng);
     return TRUE;
 }
METHOD (pts_t , get_my_public_value , bool , private_pts_t * this, chunk_t * value, chunk_t * nonce)
Definition at line 227 of file pts.c.
References dh, FALSE, and TRUE.
 {
     if (!this->dh->get_my_public_value(this->dh, value))
     {
         return FALSE;
     }
     *nonce = this->is_imc ? this->responder_nonce : this->initiator_nonce;
     return TRUE;
 }
METHOD (pts_t , set_peer_public_value , bool , private_pts_t * this, chunk_t value, chunk_t nonce)
Definition at line 238 of file pts.c.
References chunk_clone, dh, FALSE, and TRUE.
 {
     if (!this->dh->set_other_public_value(this->dh, value))
     {
         return FALSE;
     }
     nonce = chunk_clone(nonce);
     if (this->is_imc)
     {
         this->initiator_nonce = nonce;
     }
     else
     {
         this->responder_nonce = nonce;
     }
     return TRUE;
 }
METHOD (pts_t , calculate_secret , bool , private_pts_t * this)
Definition at line 258 of file pts.c.
References hasher_t::allocate_hash, chunk_clear(), chunk_from_chars, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG3, DBG_PTS, hasher_t::destroy, DESTROY_IF, dh, FALSE, hasher_t::get_hash, hasher, lib, min, pts_meas_algo_to_hash(), and TRUE.
 {
     hasher_t *hasher;
     hash_algorithm_t hash_alg;
     chunk_t shared_secret;
     /* Check presence of nonces */
     if (!this->initiator_nonce.len || !this->responder_nonce.len)
     {
         DBG1(DBG_PTS, "initiator and/or responder nonce is not available");
         return FALSE;
     }
     DBG3(DBG_PTS, "initiator nonce: %B", &this->initiator_nonce);
     DBG3(DBG_PTS, "responder nonce: %B", &this->responder_nonce);
     /* Calculate the DH secret */
     if (!this->dh->get_shared_secret(this->dh, &shared_secret))
     {
         DBG1(DBG_PTS, "shared DH secret computation failed");
         return FALSE;
     }
     DBG3(DBG_PTS, "shared DH secret: %B", &shared_secret);
     /* Calculate the secret assessment value */
     hash_alg = pts_meas_algo_to_hash(this->dh_hash_algorithm);
     hasher = lib->crypto->create_hasher(lib->crypto, hash_alg);
     if (!hasher ||
         !hasher->get_hash(hasher, chunk_from_chars('1'), NULL) ||
         !hasher->get_hash(hasher, this->initiator_nonce, NULL) ||
         !hasher->get_hash(hasher, this->responder_nonce, NULL) ||
         !hasher->allocate_hash(hasher, shared_secret, &this->secret))
     {
         DESTROY_IF(hasher);
         return FALSE;
     }
     hasher->destroy(hasher);
     /* The DH secret must be destroyed */
     chunk_clear(&shared_secret);
     /*
      * Truncate the hash to 20 bytes to fit the ExternalData
      * argument of the TPM Quote command
      */
     this->secret.len = min(this->secret.len, 20);
     DBG3(DBG_PTS, "secret assessment value: %B", &this->secret);
     return TRUE;
 }
METHOD (pts_t , get_platform_id , int , private_pts_t * this)
Definition at line 344 of file pts.c.
 {
     return this->platform_id;
 }
METHOD (pts_t , set_platform_id , void , private_pts_t * this, int pid)
Definition at line 350 of file pts.c.
 {
     this->platform_id = pid;
 }
METHOD (pts_t , get_tpm_version_info , bool , private_pts_t * this, chunk_t * info)
Definition at line 356 of file pts.c.
References FALSE, has_tpm(), print_tpm_version_info(), and TRUE.
 {
     if (!this->has_tpm)
     {
         return FALSE;
     }
     *info = this->tpm_version_info;
     print_tpm_version_info(this);
     return TRUE;
 }
METHOD (pts_t , set_tpm_version_info , void , private_pts_t * this, chunk_t info)
Definition at line 368 of file pts.c.
References chunk_clone, and print_tpm_version_info().
 {
     this->tpm_version_info = chunk_clone(info);
     print_tpm_version_info(this);
 }
METHOD (pts_t , get_aik , certificate_t * , private_pts_t * this)
Definition at line 446 of file pts.c.
 {
     return this->aik;
 }
METHOD (pts_t , set_aik , void , private_pts_t * this, certificate_t * aik, int aik_id)
Definition at line 452 of file pts.c.
References DESTROY_IF, and certificate_t::get_ref.
 {
     DESTROY_IF(this->aik);
     this->aik = aik->get_ref(aik);
     this->aik_id = aik_id;
 }
METHOD (pts_t , get_aik_id , int , private_pts_t * this)
Definition at line 460 of file pts.c.
 {
     return this->aik_id;
 }
METHOD (pts_t , is_path_valid , bool , private_pts_t * this, char * path, pts_error_code_t * error_code)
Definition at line 466 of file pts.c.
References DBG1, DBG_PTS, FALSE, strerror, TCG_PTS_FILE_NOT_FOUND, TCG_PTS_INVALID_PATH, and TRUE.
 {
     struct stat st;
     *error_code = 0;
     if (!stat(path, &st))
     {
         return TRUE;
     }
     else if (errno == ENOENT || errno == ENOTDIR)
     {
         DBG1(DBG_PTS, "file/directory does not exist %s", path);
         *error_code = TCG_PTS_FILE_NOT_FOUND;
     }
     else if (errno == EFAULT)
     {
         DBG1(DBG_PTS, "bad address %s", path);
         *error_code = TCG_PTS_INVALID_PATH;
     }
     else
     {
         DBG1(DBG_PTS, "error: %s occurred while validating path: %s",
                        strerror(errno), path);
         return FALSE;
     }
     return TRUE;
 }
METHOD (pts_t , get_metadata , pts_file_meta_t * , private_pts_t * this, char * pathname, bool is_directory)
Definition at line 560 of file pts.c.
References pts_file_meta_t::add, DBG1, DBG_PTS, pts_file_meta_t::destroy, enumerator_create_directory(), file_metadata(), pts_file_metadata_t::filename, path_basename(), pts_file_meta_create(), strdup, and strerror.
 {
     pts_file_meta_t *metadata;
     pts_file_metadata_t *entry;
     /* Create a metadata object */
     metadata = pts_file_meta_create();
     if (is_directory)
     {
         enumerator_t *enumerator;
         char *rel_name, *abs_name;
         struct stat st;
         enumerator = enumerator_create_directory(pathname);
         if (!enumerator)
         {
             DBG1(DBG_PTS,"  directory '%s' can not be opened, %s", pathname,
                  strerror(errno));
             metadata->destroy(metadata);
             return NULL;
         }
         while (enumerator->enumerate(enumerator, &rel_name, &abs_name, &st))
         {
             /* measure regular files only */
             if (S_ISREG(st.st_mode) && *rel_name != '.')
             {
                 if (!file_metadata(abs_name, &entry))
                 {
                     enumerator->destroy(enumerator);
                     metadata->destroy(metadata);
                     return NULL;
                 }
                 entry->filename = strdup(rel_name);
                 metadata->add(metadata, entry);
             }
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         if (!file_metadata(pathname, &entry))
         {
             metadata->destroy(metadata);
             return NULL;
         }
         entry->filename = path_basename(pathname);
         metadata->add(metadata, entry);
     }
     return metadata;
 }
METHOD (pts_t , read_pcr , bool , private_pts_t * this, u_int32_t pcr_num, chunk_t * pcr_value)
Definition at line 878 of file pts.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (pts_t , extend_pcr , bool , private_pts_t * this, u_int32_t pcr_num, chunk_t input, chunk_t * output)
Definition at line 884 of file pts.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (pts_t , quote_tpm , bool , private_pts_t * this, bool use_quote2, chunk_t * pcr_comp, chunk_t * quote_sig)
Definition at line 890 of file pts.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (pts_t , get_quote_info , bool , private_pts_t * this, bool use_quote2, bool use_ver_info, pts_meas_algorithms_t comp_hash_algo, chunk_t * out_pcr_comp, chunk_t * out_quote_info)
TPM_QUOTE_INFO structure: 4 bytes of version 4 bytes 'Q' 'U' 'O' 'T' 20 byte SHA1 of TCPA_PCR_COMPOSITE 20 byte nonce
TPM_QUOTE_INFO2 structure: 2 bytes Tag 0x0036 TPM_Tag_Quote_info2 4 bytes 'Q' 'U' 'T' '2' 20 bytes nonce 26 bytes PCR_INFO_SHORT
Definition at line 912 of file pts.c.
References hasher_t::allocate_hash, bio_writer_create(), chunk_clone, chunk_create(), chunk_free(), chunk_from_chars, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG3, DBG_PTS, hasher_t::destroy, bio_writer_t::destroy, DESTROY_IF, bio_writer_t::extract_buf, FALSE, free(), HASH_SHA1, hasher, chunk_t::len, lib, chunk_t::ptr, pts_meas_algo_to_hash(), TPM_LOC_ZERO, TPM_QUOTE_INFO_LEN, TPM_TAG_QUOTE_INFO2, TRUE, bio_writer_t::write_data, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
 {
     chunk_t selection, pcr_comp, hash_pcr_comp;
     bio_writer_t *writer;
     hasher_t *hasher;
     if (!this->pcrs->get_count(this->pcrs))
     {
         DBG1(DBG_PTS, "No extended PCR entries available, "
                       "unable to construct TPM Quote Info");
         return FALSE;
     }
     if (!this->secret.ptr)
     {
         DBG1(DBG_PTS, "Secret assessment value unavailable, ",
                       "unable to construct TPM Quote Info");
         return FALSE;
     }
     if (use_quote2 && use_ver_info && !this->tpm_version_info.ptr)
     {
         DBG1(DBG_PTS, "TPM Version Information unavailable, ",
                       "unable to construct TPM Quote Info2");
         return FALSE;
     }
     pcr_comp = this->pcrs->get_composite(this->pcrs);
     /* Output the TPM_PCR_COMPOSITE expected from IMC */
     if (comp_hash_algo)
     {
         hash_algorithm_t algo;
         algo = pts_meas_algo_to_hash(comp_hash_algo);
         hasher = lib->crypto->create_hasher(lib->crypto, algo);
         /* Hash the PCR Composite Structure */
         if (!hasher || !hasher->allocate_hash(hasher, pcr_comp, out_pcr_comp))
         {
             DESTROY_IF(hasher);
             free(pcr_comp.ptr);
             return FALSE;
         }
         DBG3(DBG_PTS, "constructed PCR Composite hash: %#B", out_pcr_comp);
         hasher->destroy(hasher);
     }
     else
     {
         *out_pcr_comp = chunk_clone(pcr_comp);
     }
     /* SHA1 hash of PCR Composite to construct TPM_QUOTE_INFO */
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher || !hasher->allocate_hash(hasher, pcr_comp, &hash_pcr_comp))
     {
         DESTROY_IF(hasher);
         chunk_free(out_pcr_comp);
         free(pcr_comp.ptr);
         return FALSE;
     }
     hasher->destroy(hasher);
     /* Construct TPM_QUOTE_INFO/TPM_QUOTE_INFO2 structure */
     writer = bio_writer_create(TPM_QUOTE_INFO_LEN);
     if (use_quote2)
     {
         /* TPM Structure Tag */
         writer->write_uint16(writer, TPM_TAG_QUOTE_INFO2);
         /* Magic QUT2 value */
         writer->write_data(writer, chunk_create("QUT2", 4));
         /* Secret assessment value 20 bytes (nonce) */
         writer->write_data(writer, this->secret);
         /* PCR selection */
         selection.ptr = pcr_comp.ptr;
         selection.len = 2 + this->pcrs->get_selection_size(this->pcrs);
         writer->write_data(writer, selection);
         /* TPM Locality Selection */
         writer->write_uint8(writer, TPM_LOC_ZERO);
         /* PCR Composite Hash */
         writer->write_data(writer, hash_pcr_comp);
         if (use_ver_info)
         {
             /* TPM version Info */
             writer->write_data(writer, this->tpm_version_info);
         }
     }
     else
     {
         /* Version number */
         writer->write_data(writer, chunk_from_chars(1, 1, 0, 0));
         /* Magic QUOT value */
         writer->write_data(writer, chunk_create("QUOT", 4));
         /* PCR Composite Hash */
         writer->write_data(writer, hash_pcr_comp);
         /* Secret assessment value 20 bytes (nonce) */
         writer->write_data(writer, this->secret);
     }
     /* TPM Quote Info */
     *out_quote_info = writer->extract_buf(writer);
     DBG3(DBG_PTS, "constructed TPM Quote Info: %B", out_quote_info);
     writer->destroy(writer);
     free(pcr_comp.ptr);
     free(hash_pcr_comp.ptr);
     return TRUE;
 }
METHOD (pts_t , verify_quote_signature , bool , private_pts_t * this, chunk_t data, chunk_t signature)
Definition at line 1034 of file pts.c.
References DBG1, DBG_PTS, public_key_t::destroy, DESTROY_IF, FALSE, SIGN_RSA_EMSA_PKCS1_SHA1, TRUE, and public_key_t::verify.
 {
     public_key_t *aik_pub_key;
     aik_pub_key = this->aik->get_public_key(this->aik);
     if (!aik_pub_key)
     {
         DBG1(DBG_PTS, "failed to get public key from AIK certificate");
         return FALSE;
     }
     if (!aik_pub_key->verify(aik_pub_key, SIGN_RSA_EMSA_PKCS1_SHA1,
         data, signature))
     {
         DBG1(DBG_PTS, "signature verification failed for TPM Quote Info");
         DESTROY_IF(aik_pub_key);
         return FALSE;
     }
     aik_pub_key->destroy(aik_pub_key);
     return TRUE;
 }
METHOD (pts_t , get_pcrs , pts_pcr_t * , private_pts_t * this)
Definition at line 1058 of file pts.c.
 {
     return this->pcrs;
 }
METHOD (pts_t , destroy , void , private_pts_t * this)
Definition at line 1064 of file pts.c.
References DESTROY_IF, dh, and free().
 {
     DESTROY_IF(this->pcrs);
     DESTROY_IF(this->aik);
     DESTROY_IF(this->dh);
     free(this->initiator_nonce.ptr);
     free(this->responder_nonce.ptr);
     free(this->secret.ptr);
     free(this->aik_blob.ptr);
     free(this->tpm_version_info.ptr);
     free(this);
 }
static void print_tpm_version_info (private_pts_t * this) static
Definition at line 337 of file pts.c.
References DBG1, and DBG_PTS.
Referenced by METHOD().
 {
     DBG1(DBG_PTS, "unknown TPM version: no TSS implementation available");
 }