strongSwan: mac
mac
hmac
Functions
prf_t * hmac_prf_create (pseudo_random_function_t algo)
signer_t * hmac_signer_create (integrity_algorithm_t algo)
Detailed Description
Implements the message authentication algorithm described in RFC2104.
It uses a hash function, which must be implemented as a hasher_t class.
Function Documentation
prf_t* hmac_prf_create (pseudo_random_function_t algo)
Creates a new prf_t object based on an HMAC.
Parameters
algo algorithm to implement
Returns
prf_t object, NULL if not supported
Definition at line 192 of file hmac.c.
References hasher_algorithm_from_prf(), hmac_create(), and mac_prf_create().
Referenced by METHOD().
 {
     mac_t *hmac;
     hmac = hmac_create(hasher_algorithm_from_prf(algo));
     if (hmac)
     {
         return mac_prf_create(hmac);
     }
     return NULL;
 }
signer_t* hmac_signer_create (integrity_algorithm_t algo)
Creates a new signer_t object based on an HMAC.
Parameters
algo algorithm to implement
Returns
signer_t, NULL if not supported
Definition at line 207 of file hmac.c.
References hasher_algorithm_from_integrity(), hmac_create(), and mac_signer_create().
Referenced by METHOD().
 {
     mac_t *hmac;
     size_t trunc;
     hmac = hmac_create(hasher_algorithm_from_integrity(algo, &trunc));
     if (hmac)
     {
         return mac_signer_create(hmac, trunc);
     }
     return NULL;
 }