strongSwan: delete_child_sa_job
delete_child_sa_job
jobs
Classes
struct delete_child_sa_job_t
struct delete_ike_sa_job_t
Typedefs
typedef struct
delete_child_sa_job_t delete_child_sa_job_t
typedef struct delete_ike_sa_job_t delete_ike_sa_job_t
Functions
delete_child_sa_job_t * delete_child_sa_job_create (protocol_id_t protocol, u_int32_t spi, host_t *dst, bool expired)
delete_ike_sa_job_t * delete_ike_sa_job_create (ike_sa_id_t *ike_sa_id, bool delete_if_established)
Detailed Description
Typedef Documentation
typedef struct delete_child_sa_job_t delete_child_sa_job_t
Definition at line 24 of file delete_child_sa_job.h.
typedef struct delete_ike_sa_job_t delete_ike_sa_job_t
Definition at line 25 of file delete_ike_sa_job.h.
Function Documentation
delete_child_sa_job_t* delete_child_sa_job_create (protocol_id_t protocol, u_int32_t spi, host_t * dst, bool expired)
Creates a job of type DELETE_CHILD_SA.
Parameters
protocol protocol of the CHILD_SA
spi security parameter index of the CHILD_SA
dst SA destination address
expired TRUE if CHILD_SA already expired
Returns
delete_child_sa_job_t object
Definition at line 91 of file delete_child_sa_job.c.
References host_t::clone, INIT, and protocol.
Referenced by METHOD().
 {
     private_delete_child_sa_job_t *this;
     INIT(this,
         .public = {
             .job_interface = {
                 .execute = _execute,
                 .get_priority = _get_priority,
                 .destroy = _destroy,
             },
         },
         .protocol = protocol,
         .spi = spi,
         .dst = dst->clone(dst),
         .expired = expired,
     );
     return &this->public;
 }
delete_ike_sa_job_t* delete_ike_sa_job_create (ike_sa_id_t * ike_sa_id, bool delete_if_established)
Creates a job of type DELETE_IKE_SA.
Parameters
ike_sa_id id of the IKE_SA to delete
delete_if_established should the IKE_SA be deleted if it is established?
Returns
created delete_ike_sa_job_t object
Definition at line 115 of file delete_ike_sa_job.c.
References ike_sa_id_t::clone, and INIT.
Referenced by check_systime(), delete_all_async(), eap_radius_handle_timeout(), enforce_replace(), handle_child_sa_failure(), METHOD(), process_disconnect(), and schedule_timeout().
 {
     private_delete_ike_sa_job_t *this;
     INIT(this,
         .public = {
             .job_interface = {
                 .execute = _execute,
                 .get_priority = _get_priority,
                 .destroy = _destroy,
             },
         },
         .ike_sa_id = ike_sa_id->clone(ike_sa_id),
         .delete_if_established = delete_if_established,
     );
     return &(this->public);
 }