strongSwan: pa_tnc_attr_manager_t Struct Reference
pa_tnc_attr_manager_t Struct Reference
pa_tnc_attr_manager
#include "pa_tnc_attr_manager.h"
Public Attributes
void(* add_vendor)(pa_tnc_attr_manager_t *this, pen_t vendor_id, pa_tnc_attr_create_t attr_create, enum_name_t *attr_names)
void(* remove_vendor)(pa_tnc_attr_manager_t *this, pen_t vendor_id)
enum_name_t *(* get_names)(pa_tnc_attr_manager_t *this, pen_t vendor_id)
pa_tnc_attr_t *(* create)(pa_tnc_attr_manager_t *this, bio_reader_t *reader, bool segmented, uint32_t *offset, chunk_t msg_info, pa_tnc_attr_t **error)
pa_tnc_attr_t *(* construct)(pa_tnc_attr_manager_t *this, pen_t vendor_id, uint32_t type, chunk_t value)
void(* destroy)(pa_tnc_attr_manager_t *this)
Detailed Description
Manages PA-TNC attributes for arbitrary PENs
Definition at line 37 of file pa_tnc_attr_manager.h.
Member Data Documentation
void(* pa_tnc_attr_manager_t::add_vendor)(pa_tnc_attr_manager_t *this, pen_t vendor_id, pa_tnc_attr_create_t attr_create, enum_name_t *attr_names)
Add vendor-specific attribute names and creation method
Parameters
vendor_id Private Enterprise Number (PEN)
attr_create Vendor-specific attribute create method
attr_names Vendor-specific attribute names
Definition at line 46 of file pa_tnc_attr_manager.h.
Referenced by libimcv_init().
pa_tnc_attr_t*(* pa_tnc_attr_manager_t::construct)(pa_tnc_attr_manager_t *this, pen_t vendor_id, uint32_t type, chunk_t value)
Generically construct a PA-TNC attribute from type and data
Parameters
vendor_id Private Enterprise Number (PEN)
type PA-TNC attribute type
value PA-TNC attribute value as encoded data
Returns
PA-TNC attribute object if supported, NULL else
Definition at line 87 of file pa_tnc_attr_manager.h.
pa_tnc_attr_t*(* pa_tnc_attr_manager_t::create)(pa_tnc_attr_manager_t *this, bio_reader_t *reader, bool segmented, uint32_t *offset, chunk_t msg_info, pa_tnc_attr_t **error)
Create and pre-parse a PA-TNC attribute object from data
Parameters
reader PA-TNC attribute as encoded data
segmented TRUE if attribute is segmented
offset Offset in bytes where an error has been found
msg_info Message info added to an error attribute
error Error attribute if an error occurred
Returns
PA-TNC attribute object if supported, NULL else
Definition at line 75 of file pa_tnc_attr_manager.h.
Referenced by METHOD(), and seg_env_create_from_data().
void(* pa_tnc_attr_manager_t::destroy)(pa_tnc_attr_manager_t *this)
Destroys a pa_tnc_attr_manager_t object.
Definition at line 93 of file pa_tnc_attr_manager.h.
enum_name_t*(* pa_tnc_attr_manager_t::get_names)(pa_tnc_attr_manager_t *this, pen_t vendor_id)
Definition at line 63 of file pa_tnc_attr_manager.h.
Referenced by METHOD().
void(* pa_tnc_attr_manager_t::remove_vendor)(pa_tnc_attr_manager_t *this, pen_t vendor_id)
Remove vendor-specific attribute names and creation method
Parameters
vendor_id Private Enterprise Number (PEN)
Definition at line 55 of file pa_tnc_attr_manager.h.
Referenced by libimcv_deinit().
The documentation for this struct was generated from the following file:
pa_tnc_attr_manager.h