strongSwan: task_t Struct Reference
task_t Struct Reference
task
#include "task.h"
Public Attributes
status_t(* build)(task_t *this, message_t *message)
status_t(* process)(task_t *this, message_t *message)
task_type_t(* get_type)(task_t *this)
void(* migrate)(task_t *this, ike_sa_t *ike_sa)
void(* destroy)(task_t *this)
Detailed Description
Interface for a task, an operation handled within exchanges.
A task is an elemantary operation. It may be handled by a single or by multiple exchanges. An exchange may even complete multiple tasks. A task has a build() and an process() operation. The build() operation creates payloads and adds it to the message. The process() operation inspects a message and handles its payloads. An initiator of an exchange first calls build() to build the request, and processes the response message with the process() method. A responder does the opposite; it calls process() first to handle an incoming request and secondly calls build() to build an appropriate response. Both methods return either SUCCESS, NEED_MORE or FAILED. A SUCCESS indicates that the task completed, even when the task completed unsuccessfully. The manager then removes the task from the list. A NEED_MORE is returned when the task needs further build()/process() calls to complete, the manager leaves the taks in the queue. A returned FAILED indicates a critical failure. The manager closes the IKE_SA whenever a task returns FAILED.
Definition at line 128 of file task.h.
Member Data Documentation
status_t(* task_t::build)(task_t *this, message_t *message)
Build a request or response message for this task.
Parameters
message message to add payloads to
Returns
FAILED if a critical error occurred
DESTROY_ME if IKE_SA has been properly deleted
NEED_MORE if another call to build/process needed
ALREADY_DONE to cancel task processing
SUCCESS if task completed
Definition at line 141 of file task.h.
Referenced by build_response(), and METHOD().
void(* task_t::destroy)(task_t *this)
Destroys a task_t object.
Definition at line 179 of file task.h.
Referenced by build_response(), METHOD(), process_request(), and process_response().
task_type_t(* task_t::get_type)(task_t *this)
Get the type of the task implementation.
Definition at line 159 of file task.h.
Referenced by activate_task(), build_response(), cancel_quick_mode(), handle_collisions(), has_queued(), have_aggressive_mode_task(), have_quick_mode_task(), is_child_queued(), list_task_queue(), log_task_q(), METHOD(), migrate_child_tasks(), process_request(), and trigger_mbb_reauth().
void(* task_t::migrate)(task_t *this, ike_sa_t *ike_sa)
Migrate a task to a new IKE_SA.
After migrating a task, it goes back to a state where it can be used again to initate an exchange. This is useful when a task has to get migrated to a new IKE_SA. A special usage is when a INVALID_KE_PAYLOAD is received. A call to reset resets the task, but uses another DH group for the next try. The ike_sa is the new IKE_SA this task belongs to and operates on.
Parameters
ike_sa new IKE_SA this task works for
Definition at line 174 of file task.h.
Referenced by METHOD(), migrate_child_tasks(), and trigger_mbb_reauth().
status_t(* task_t::process)(task_t *this, message_t *message)
Process a request or response message for this task.
Parameters
message message to read payloads from
Returns
FAILED if a critical error occurred
DESTROY_ME if IKE_SA has been properly deleted
NEED_MORE if another call to build/process needed
ALREADY_DONE to cancel task processing
SUCCESS if task completed
Definition at line 154 of file task.h.
Referenced by process_request(), and process_response().
The documentation for this struct was generated from the following file:
task.h