strongSwan: diffie_hellman_t Struct Reference
diffie_hellman_t Struct Reference
diffie_hellman
#include "diffie_hellman.h"
Public Attributes
bool(* get_shared_secret)(diffie_hellman_t *this, chunk_t *secret) __attribute__((warn_unused_result))
bool(* set_other_public_value)(diffie_hellman_t *this, chunk_t value) __attribute__((warn_unused_result))
bool(* get_my_public_value)(diffie_hellman_t *this, chunk_t *value) __attribute__((warn_unused_result))
bool(* set_private_value)(diffie_hellman_t *this, chunk_t value) __attribute__((warn_unused_result))
diffie_hellman_group_t(* get_dh_group)(diffie_hellman_t *this)
void(* destroy)(diffie_hellman_t *this)
Detailed Description
Implementation of the Diffie-Hellman algorithm, as in RFC2631.
Definition at line 84 of file diffie_hellman.h.
Member Data Documentation
void(* diffie_hellman_t::destroy)(diffie_hellman_t *this)
Destroys a diffie_hellman_t object.
Definition at line 141 of file diffie_hellman.h.
Referenced by bench_dh(), METHOD(), process_ike_add(), run_test(), and START_TEST().
diffie_hellman_group_t(* diffie_hellman_t::get_dh_group)(diffie_hellman_t *this)
Get the DH group used.
Returns
DH group set in construction
Definition at line 136 of file diffie_hellman.h.
Referenced by ke_payload_create_from_diffie_hellman(), and START_TEST().
bool(* diffie_hellman_t::get_my_public_value)(diffie_hellman_t *this, chunk_t *value) __attribute__((warn_unused_result))
Gets the own public value to transmit.
Space for returned chunk is allocated and must be freed by the caller.
Parameters
value public value of caller is stored at this location
Returns
TRUE if public value retrieved
Definition at line 116 of file diffie_hellman.h.
Referenced by bench_dh(), ke_payload_create_from_diffie_hellman(), METHOD(), run_test(), and START_TEST().
bool(* diffie_hellman_t::get_shared_secret)(diffie_hellman_t *this, chunk_t *secret) __attribute__((warn_unused_result))
Returns the shared secret of this diffie hellman exchange.
Space for returned secret is allocated and must be freed by the caller.
Parameters
secret shared secret will be written into this chunk
Returns
TRUE if shared secret computed successfully
Definition at line 94 of file diffie_hellman.h.
Referenced by bench_dh(), METHOD(), and START_TEST().
bool(* diffie_hellman_t::set_other_public_value)(diffie_hellman_t *this, chunk_t value) __attribute__((warn_unused_result))
Sets the public value of partner.
Chunk gets cloned and can be destroyed afterwards.
Parameters
value public value of partner
Returns
TRUE if other public value verified and set
Definition at line 105 of file diffie_hellman.h.
Referenced by bench_dh(), METHOD(), run_test(), and START_TEST().
bool(* diffie_hellman_t::set_private_value)(diffie_hellman_t *this, chunk_t value) __attribute__((warn_unused_result))
Set an explicit own private value to use.
Calling this method is usually not required, as the DH backend generates an appropriate private value itself. It is optional to implement, and used mostly for testing purposes.
Parameters
value private value to set
Definition at line 128 of file diffie_hellman.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
diffie_hellman.h