strongSwan: pts_ima_bios_list.c File Reference
pts_ima_bios_list.c File Reference
#include "pts_ima_bios_list.h"
#include <utils/debug.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
Classes
struct private_pts_ima_bios_list_t
struct bios_entry_t
Typedefs
typedef struct
private_pts_ima_bios_list_t private_pts_ima_bios_list_t
typedef struct bios_entry_t bios_entry_t
typedef enum event_type_t event_type_t
Enumerations
enum event_type_t {
EV_PREBOOT_CERT = 0x00000000, EV_POST_CODE = 0x00000001, EV_UNUSED = 0x00000002, EV_NO_ACTION = 0x00000003,
EV_SEPARATOR = 0x00000004, EV_ACTION = 0x00000005, EV_EVENT_TAG = 0x00000006, EV_S_CRTM_CONTENTS = 0x00000007,
EV_S_CRTM_VERSION = 0x00000008, EV_CPU_MICROCODE = 0x00000009, EV_PLATFORM_CONFIG_FLAGS = 0x0000000A, EV_TABLE_OF_DEVICES = 0x0000000B,
EV_COMPACT_HASH = 0x0000000C, EV_IPL = 0x0000000D, EV_IPL_PARTITION_DATA = 0x0000000E, EV_NONHOST_CODE = 0x0000000F,
EV_NONHOST_CONFIG = 0x00000010, EV_NONHOST_INFO = 0x00000011, EV_OMIT_BOOT_DEVICE_EVENTS = 0x00000012, EV_EFI_EVENT_BASE = 0x80000000,
EV_EFI_VARIABLE_DRIVER_CONFIG = 0x80000001, EV_EFI_VARIABLE_BOOT = 0x80000002, EV_EFI_BOOT_SERVICES_APPLICATION = 0x80000003, EV_EFI_BOOT_SERVICES_DRIVER = 0x80000004,
EV_EFI_RUNTIME_SERVICES_DRIVER = 0x80000005, EV_EFI_GPT_EVENT = 0x80000006, EV_EFI_ACTION = 0x80000007, EV_EFI_PLATFORM_FIRMWARE_BLOB = 0x80000008,
EV_EFI_HANDOFF_TABLES = 0x80000009, EV_EFI_VARIABLE_AUTHORITY = 0x800000E0
}
Functions
ENUM_BEGIN (event_type_names, EV_PREBOOT_CERT, EV_OMIT_BOOT_DEVICE_EVENTS,"Preboot Cert","POST Code","Unused","No Action","Separator","Action","Event Tag","S-CRTM Contents","S-CRTM Version","CPU Microcode","Platform Config Flags","Table of Devices","Compact Hash","IPL","IPL Partition Data","Nonhost Code","Nonhost Config","Nonhost Info","Omit Boot Device Events")
ENUM_NEXT (event_type_names, EV_EFI_EVENT_BASE, EV_EFI_HANDOFF_TABLES, EV_OMIT_BOOT_DEVICE_EVENTS,"EFI Event Base","EFI Variable Driver Config","EFI Variable Boot","EFI Boot Services Application","EFI Boot Services Driver","EFI Runtime Services Driver","EFI GPT Event","EFI Action","EFI Platform Firmware Blob","EFI Handoff Tables")
ENUM_NEXT (event_type_names, EV_EFI_VARIABLE_AUTHORITY, EV_EFI_VARIABLE_AUTHORITY, EV_EFI_HANDOFF_TABLES,"EFI Variable Authority")
ENUM_END (event_type_names, EV_EFI_VARIABLE_AUTHORITY)
static void free_bios_entry (bios_entry_t *this)
METHOD (pts_ima_bios_list_t, get_time, time_t, private_pts_ima_bios_list_t *this)
METHOD (pts_ima_bios_list_t, get_count, int, private_pts_ima_bios_list_t *this)
METHOD (pts_ima_bios_list_t, get_next, status_t, private_pts_ima_bios_list_t *this, uint32_t *pcr, chunk_t *measurement)
METHOD (pts_ima_bios_list_t, destroy, void, private_pts_ima_bios_list_t *this)
pts_ima_bios_list_t * pts_ima_bios_list_create (char *file)
Typedef Documentation
typedef struct bios_entry_t bios_entry_t
Definition at line 27 of file pts_ima_bios_list.c.
typedef enum event_type_t event_type_t
Definition at line 28 of file pts_ima_bios_list.c.
typedef struct private_pts_ima_bios_list_t private_pts_ima_bios_list_t
Definition at line 26 of file pts_ima_bios_list.c.
Enumeration Type Documentation
enum event_type_t
Enumerator
EV_PREBOOT_CERT
EV_POST_CODE
EV_UNUSED
EV_NO_ACTION
EV_SEPARATOR
EV_ACTION
EV_EVENT_TAG
EV_S_CRTM_CONTENTS
EV_S_CRTM_VERSION
EV_CPU_MICROCODE
EV_PLATFORM_CONFIG_FLAGS
EV_TABLE_OF_DEVICES
EV_COMPACT_HASH
EV_IPL
EV_IPL_PARTITION_DATA
EV_NONHOST_CODE
EV_NONHOST_CONFIG
EV_NONHOST_INFO
EV_OMIT_BOOT_DEVICE_EVENTS
EV_EFI_EVENT_BASE
EV_EFI_VARIABLE_DRIVER_CONFIG
EV_EFI_VARIABLE_BOOT
EV_EFI_BOOT_SERVICES_APPLICATION
EV_EFI_BOOT_SERVICES_DRIVER
EV_EFI_RUNTIME_SERVICES_DRIVER
EV_EFI_GPT_EVENT
EV_EFI_ACTION
EV_EFI_PLATFORM_FIRMWARE_BLOB
EV_EFI_HANDOFF_TABLES
EV_EFI_VARIABLE_AUTHORITY
Definition at line 30 of file pts_ima_bios_list.c.
                   {
     /* BIOS Events (TCG PC Client Specification for Conventional BIOS 1.21) */
     EV_PREBOOT_CERT =                  0x00000000,
     EV_POST_CODE =                     0x00000001,
     EV_UNUSED =                        0x00000002,
     EV_NO_ACTION =                     0x00000003,
     EV_SEPARATOR =                     0x00000004,
     EV_ACTION =                        0x00000005,
     EV_EVENT_TAG =                     0x00000006,
     EV_S_CRTM_CONTENTS =               0x00000007,
     EV_S_CRTM_VERSION =                0x00000008,
     EV_CPU_MICROCODE =                 0x00000009,
     EV_PLATFORM_CONFIG_FLAGS =         0x0000000A,
     EV_TABLE_OF_DEVICES =              0x0000000B,
     EV_COMPACT_HASH =                  0x0000000C,
     EV_IPL =                           0x0000000D,
     EV_IPL_PARTITION_DATA =            0x0000000E,
     EV_NONHOST_CODE =                  0x0000000F,
     EV_NONHOST_CONFIG =                0x00000010,
     EV_NONHOST_INFO =                  0x00000011,
     EV_OMIT_BOOT_DEVICE_EVENTS =       0x00000012,
     /* EFI Events (TCG EFI Platform Specification 1.22) */
     EV_EFI_EVENT_BASE =                0x80000000,
     EV_EFI_VARIABLE_DRIVER_CONFIG =    0x80000001,
     EV_EFI_VARIABLE_BOOT =             0x80000002,
     EV_EFI_BOOT_SERVICES_APPLICATION = 0x80000003,
     EV_EFI_BOOT_SERVICES_DRIVER =      0x80000004,
     EV_EFI_RUNTIME_SERVICES_DRIVER =   0x80000005,
     EV_EFI_GPT_EVENT =                 0x80000006,
     EV_EFI_ACTION =                    0x80000007,
     EV_EFI_PLATFORM_FIRMWARE_BLOB =    0x80000008,
     EV_EFI_HANDOFF_TABLES =            0x80000009,
     EV_EFI_VARIABLE_AUTHORITY =        0x800000E0
 };
Function Documentation
ENUM_BEGIN (event_type_names , EV_PREBOOT_CERT , EV_OMIT_BOOT_DEVICE_EVENTS , "Preboot Cert" , "POST Code" , "Unused" , "No Action" , "Separator" , "Action" , "Event Tag" , "S-CRTM Contents" , "S-CRTM Version" , "CPU Microcode" , "Platform Config Flags" , "Table of Devices" , "Compact Hash" , "IPL" , "IPL Partition Data" , "Nonhost Code" , "Nonhost Config" , "Nonhost Info" , "Omit Boot Device Events")
ENUM_END (event_type_names , EV_EFI_VARIABLE_AUTHORITY)
ENUM_NEXT (event_type_names , EV_EFI_EVENT_BASE , EV_EFI_HANDOFF_TABLES , EV_OMIT_BOOT_DEVICE_EVENTS , "EFI Event Base" , "EFI Variable Driver Config" , "EFI Variable Boot" , "EFI Boot Services Application" , "EFI Boot Services Driver" , "EFI Runtime Services Driver" , "EFI GPT Event" , "EFI Action" , "EFI Platform Firmware Blob" , "EFI Handoff Tables")
ENUM_NEXT (event_type_names , EV_EFI_VARIABLE_AUTHORITY , EV_EFI_VARIABLE_AUTHORITY , EV_EFI_HANDOFF_TABLES , "EFI Variable Authority")
static void free_bios_entry (bios_entry_t * this) static
Free a bios_entry_t object
Definition at line 150 of file pts_ima_bios_list.c.
References free().
Referenced by METHOD(), and pts_ima_bios_list_create().
 {
     free(this->measurement.ptr);
     free(this);
 }
METHOD (pts_ima_bios_list_t , get_time , time_t , private_pts_ima_bios_list_t * this)
Definition at line 156 of file pts_ima_bios_list.c.
 {
     return this->creation_time;
 }
METHOD (pts_ima_bios_list_t , get_count , int , private_pts_ima_bios_list_t * this)
Definition at line 162 of file pts_ima_bios_list.c.
References linked_list_t::get_count, and list.
 {
     return this->list->get_count(this->list);
 }
METHOD (pts_ima_bios_list_t , get_next , status_t , private_pts_ima_bios_list_t * this, uint32_t * pcr, chunk_t * measurement)
Definition at line 168 of file pts_ima_bios_list.c.
References free(), list, bios_entry_t::measurement, bios_entry_t::pcr, linked_list_t::remove_first, and status.
 {
     bios_entry_t *entry;
     status_t status;
     status = this->list->remove_first(this->list, (void**)&entry);
     *pcr = entry->pcr;
     *measurement = entry->measurement;
     free(entry);
     return status;
 }
METHOD (pts_ima_bios_list_t , destroy , void , private_pts_ima_bios_list_t * this)
Definition at line 182 of file pts_ima_bios_list.c.
References linked_list_t::destroy_function, free(), free_bios_entry(), and list.
 {
     this->list->destroy_function(this->list, (void *)free_bios_entry);
     free(this);
 }