strongSwan: eap_radius_forward
eap_radius_forward
eap_radius
Classes
struct eap_radius_forward_t
Typedefs
typedef struct eap_radius_forward_t eap_radius_forward_t
Functions
eap_radius_forward_t * eap_radius_forward_create ()
void eap_radius_forward_from_ike (radius_message_t *request)
void eap_radius_forward_to_ike (radius_message_t *response)
Detailed Description
Typedef Documentation
typedef struct eap_radius_forward_t eap_radius_forward_t
Definition at line 28 of file eap_radius_forward.h.
Function Documentation
eap_radius_forward_t* eap_radius_forward_create ()
Create a eap_radius_forward instance.
See header
Definition at line 410 of file eap_radius_forward.c.
References destroy(), from, settings_t::get_str, hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), INIT, lib, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, parse_selector(), and library_t::settings.
Referenced by plugin_cb().
 {
     private_eap_radius_forward_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .message = _message,
                 .ike_updown = _ike_updown,
             },
             .destroy = _destroy,
         },
         .from_attr = parse_selector(lib->settings->get_str(lib->settings,
                             "%s.plugins.eap-radius.forward.ike_to_radius", "",
                             lib->ns)),
         .to_attr = parse_selector(lib->settings->get_str(lib->settings,
                             "%s.plugins.eap-radius.forward.radius_to_ike", "",
                             lib->ns)),
         .from = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 8),
         .to = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 8),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     if (this->from_attr->get_count(this->from_attr) == 0 &&
         this->to_attr->get_count(this->to_attr) == 0)
     {
         destroy(this);
         return NULL;
     }
     singleton = this;
     return &this->public;
 }
void eap_radius_forward_from_ike (radius_message_t * request)
Forward RADIUS attributes from IKE notifies to a RADIUS request.
Parameters
request RADIUS request message to add attributes to
See header.
Definition at line 272 of file eap_radius_forward.c.
References from, lookup_queue(), queue(), queue2radius(), and singleton.
Referenced by add_radius_request_attrs(), and verify_radius().
 {
     private_eap_radius_forward_t *this = singleton;
     linked_list_t *queue;
     if (this)
     {
         queue = lookup_queue(this, this->from);
         if (queue)
         {
             queue2radius(queue, request);
         }
     }
 }
void eap_radius_forward_to_ike (radius_message_t * response)
Forward RADIUS attributes from a RADIUS response to IKE notifies.
Parameters
response RADIUS respose to read notifies from
See header.
Definition at line 290 of file eap_radius_forward.c.
References lookup_queue(), queue(), radius2queue(), singleton, and to.
Referenced by METHOD(), and verify_radius().
 {
     private_eap_radius_forward_t *this = singleton;
     linked_list_t *queue;
     if (this)
     {
         queue = lookup_queue(this, this->to);
         if (queue)
         {
             radius2queue(response, queue, this->to_attr);
         }
     }
 }