strongSwan: packet_t Struct Reference
packet_t Struct Reference
packet
#include "packet.h"
Public Attributes
void(* set_source)(packet_t *packet, host_t *source)
void(* set_destination)(packet_t *packet, host_t *destination)
host_t *(* get_source)(packet_t *packet)
host_t *(* get_destination)(packet_t *packet)
chunk_t(* get_data)(packet_t *packet)
void(* set_data)(packet_t *packet, chunk_t data)
u_int8_t(* get_dscp)(packet_t *this)
void(* set_dscp)(packet_t *this, u_int8_t value)
void(* skip_bytes)(packet_t *packet, size_t bytes)
packet_t *(* clone)(packet_t *packet)
void(* destroy)(packet_t *packet)
Detailed Description
Abstraction of an IP/UDP-Packet, contains data, sender and receiver.
Definition at line 39 of file packet.h.
Member Data Documentation
packet_t*(* packet_t::clone)(packet_t *packet)
Clones a packet_t object.
Note
Data is cloned without skipped bytes.
Parameters
clone clone of the packet
Definition at line 115 of file packet.h.
Referenced by filter_fragments(), METHOD(), retransmit(), send_check(), and send_packets().
void(* packet_t::destroy)(packet_t *packet)
Destroy the packet, freeing contained data.
Definition at line 120 of file packet.h.
Referenced by clear_packets(), METHOD(), receive_packets(), send_check(), and send_packets().
chunk_t(* packet_t::get_data)(packet_t *packet)
Get the data from the packet.
Returns
chunk containing the data (internal data)
Definition at line 74 of file packet.h.
Referenced by message_create_from_packet(), METHOD(), receive_packets(), and START_TEST().
host_t*(* packet_t::get_destination)(packet_t *packet)
Get the destination address.
Returns
destination address (internal data)
Definition at line 67 of file packet.h.
Referenced by METHOD(), and receive_packets().
u_int8_t(* packet_t::get_dscp)(packet_t *this)
Get the DiffServ Code Point set on this packet.
Returns
DSCP value
Definition at line 88 of file packet.h.
Referenced by METHOD().
host_t*(* packet_t::get_source)(packet_t *packet)
Get the source address.
Returns
source address (internal data)
Definition at line 60 of file packet.h.
Referenced by METHOD(), and receive_packets().
void(* packet_t::set_data)(packet_t *packet, chunk_t data)
Set the data in the packet.
Parameters
data chunk with data to set (gets owned)
Definition at line 81 of file packet.h.
Referenced by METHOD(), and receive_packet().
void(* packet_t::set_destination)(packet_t *packet, host_t *destination)
Set the destination address.
Parameters
source address to set as destination (gets owned)
Definition at line 53 of file packet.h.
Referenced by METHOD(), receive_packet(), and send_packets().
void(* packet_t::set_dscp)(packet_t *this, u_int8_t value)
Set the DiffServ Code Point to use on this packet.
Parameters
value DSCP value
Definition at line 95 of file packet.h.
Referenced by METHOD(), and set_dscp().
void(* packet_t::set_source)(packet_t *packet, host_t *source)
Set the source address.
Parameters
source address to set as source (gets owned)
Definition at line 46 of file packet.h.
Referenced by METHOD(), receive_packet(), and send_packets().
void(* packet_t::skip_bytes)(packet_t *packet, size_t bytes)
Increase the offset where the actual packet data starts.
The total offset applies to future calls of get_data() and clone().
Note
The offset is reset to 0 when set_data() is called.
Parameters
bytes the number of additional bytes to skip
Definition at line 106 of file packet.h.
Referenced by receive_packets().
The documentation for this struct was generated from the following file:
packet.h