strongSwan: library.c File Reference
library.c File Reference
#include "library.h"
#include <stdlib.h>
#include <utils/debug.h>
#include <threading/thread.h>
#include <utils/identification.h>
#include <networking/host.h>
#include <collections/array.h>
#include <collections/hashtable.h>
#include <utils/backtrace.h>
#include <selectors/traffic_selector.h>
Classes
struct private_library_t
Macros
#define CHECKSUM_LIBRARY IPSEC_LIB_DIR"/libchecksum.so"
#define STRONGSWAN_CONF NULL
#define MEMWIPE_WIPE_WORDS 16
Typedefs
typedef struct private_library_t private_library_t
Functions
void library_deinit ()
METHOD (library_t, get, void *, private_library_t *this, char *name)
METHOD (library_t, set, bool, private_library_t *this, char *name, void *object)
static u_int hash (char *key)
static bool equals (char *a, char *b)
__attribute__ ((noinline))
static bool check_memwipe ()
bool library_init (char *settings, const char *namespace)
Variables
library_t * lib = NULL
Macro Definition Documentation
#define CHECKSUM_LIBRARY IPSEC_LIB_DIR"/libchecksum.so"
Definition at line 30 of file library.c.
Referenced by library_init().
#define MEMWIPE_WIPE_WORDS 16
Number of words we write and memwipe() in memwipe check
Definition at line 202 of file library.c.
Referenced by __attribute__(), and check_memwipe().
#define STRONGSWAN_CONF NULL
Definition at line 33 of file library.c.
Referenced by library_init().
Typedef Documentation
typedef struct private_library_t private_library_t
Definition at line 36 of file library.c.
Function Documentation
__attribute__ ((noinline))
Write magic to memory, and try to clear it with memwipe()
Definition at line 207 of file library.c.
References countof, dbg, DBG_LIB, magic, memwipe(), and MEMWIPE_WIPE_WORDS.
 {
     int buf[MEMWIPE_WIPE_WORDS], i;
     *out = buf;
     for (i = 0; i < countof(buf); i++)
     {
         buf[i] = *magic;
     }
     /* passing buf to dbg should make sure the compiler can't optimize out buf.
      * we use directly dbg(3), as DBG3() might be stripped with DEBUG_LEVEL. */
     dbg(DBG_LIB, 3, "memwipe() pre: %b", buf, sizeof(buf));
     memwipe(buf, sizeof(buf));
 }
static bool check_memwipe () static
Check if memwipe works as expected
Definition at line 226 of file library.c.
References DBG1, DBG_LIB, FALSE, magic, MEMWIPE_WIPE_WORDS, and TRUE.
Referenced by library_init().
 {
     int magic = 0xCAFEBABE, *buf, i;
     do_magic(&magic, &buf);
     for (i = 0; i < MEMWIPE_WIPE_WORDS; i++)
     {
         if (buf[i] == magic)
         {
             DBG1(DBG_LIB, "memwipe() check failed: stackdir: %b",
                  buf, MEMWIPE_WIPE_WORDS * sizeof(int));
             return FALSE;
         }
     }
     return TRUE;
 }
static bool equals (char * a, char * b) static
Hashtable equals function
Definition at line 194 of file library.c.
References streq().
Referenced by library_init().
 {
     return streq(a, b);
 }
static u_int hash (char * key) static
Hashtable hash function
Definition at line 186 of file library.c.
References chunk_create(), and chunk_hash().
Referenced by library_init().
 {
     return chunk_hash(chunk_create(key, strlen(key)));
 }
METHOD (library_t , get , void * , private_library_t * this, char * name)
Definition at line 162 of file library.c.
 {
     return this->objects->get(this->objects, name);
 }
METHOD (library_t , set , bool , private_library_t * this, char * name, void * object)
Definition at line 168 of file library.c.
References FALSE, and TRUE.
 {
     if (object)
     {
         if (this->objects->get(this->objects, name))
         {
             return FALSE;
         }
         this->objects->put(this->objects, name, object);
         return TRUE;
     }
     return this->objects->remove(this->objects, name) != NULL;
 }