strongSwan: ntru_public_key
ntru_public_key
ntru
Classes
struct ntru_public_key_t
Typedefs
typedef struct ntru_public_key_t ntru_public_key_t
Functions
ntru_public_key_t * ntru_public_key_create (ntru_drbg_t *drbg, ntru_param_set_t *params, uint16_t *pubkey)
ntru_public_key_t * ntru_public_key_create_from_data (ntru_drbg_t *drbg, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct ntru_public_key_t ntru_public_key_t
Definition at line 24 of file ntru_public_key.h.
Function Documentation
ntru_public_key_t* ntru_public_key_create (ntru_drbg_t * drbg, ntru_param_set_t * params, uint16_t * pubkey)
Creates an NTRU encryption public key from coefficients
Parameters
drbg Deterministic random bit generator
params NTRU encryption parameter set to be used
pubkey Coefficients of public key polynomial h
Definition at line 322 of file ntru_public_key.c.
References generate_encoding(), ntru_drbg_t::get_ref, INIT, malloc(), ntru_param_set_t::N, and params.
Referenced by METHOD().
 {
     private_ntru_public_key_t *this;
     int i;
     INIT(this,
         .public = {
             .get_id = _get_id,
             .get_encoding = _get_encoding,
             .encrypt = _encrypt,
             .destroy = _destroy,
         },
         .params = params,
         .pubkey = malloc(params->N * sizeof(uint16_t)),
         .drbg = drbg->get_ref(drbg),
     );
     for (i = 0; i < params->N; i++)
     {
         this->pubkey[i] = pubkey[i];
     }
     /* generate public key encoding */
     generate_encoding(this);
     return &this->public;
 }
ntru_public_key_t* ntru_public_key_create_from_data (ntru_drbg_t * drbg, chunk_t data)
Creates an NTRU encryption public key from encoding
Parameters
drbg Deterministic random bit generator
data Encoded NTRU public key
Definition at line 355 of file ntru_public_key.c.
References chunk_clone, DBG1, DBG_LIB, ntru_drbg_t::get_ref, INIT, chunk_t::len, malloc(), ntru_param_set_t::N, ntru_octets_2_elements(), NTRU_OID_LEN, ntru_param_set_get_by_oid(), NTRU_PUBKEY_TAG, params, chunk_t::ptr, and ntru_param_set_t::q_bits.
 {
     private_ntru_public_key_t *this;
     size_t header_len, pubkey_packed_len;
     ntru_param_set_t *params;
     header_len = 2 + NTRU_OID_LEN;
     /* check the NTRU public key header format */
     if (data.len < header_len ||
         data.ptr[0] != NTRU_PUBKEY_TAG ||
         data.ptr[1] != NTRU_OID_LEN)
     {
         DBG1(DBG_LIB, "received NTRU public key with invalid header");
         return NULL;
     }
     params =  ntru_param_set_get_by_oid(data.ptr + 2);
     if (!params)
     {
         DBG1(DBG_LIB, "received NTRU public key with unknown OID");
         return NULL;
     }
     pubkey_packed_len = (params->N * params->q_bits + 7) / 8;
     if (data.len < header_len + pubkey_packed_len)
     {
         DBG1(DBG_LIB, "received NTRU public key with wrong packed key size");
         return NULL;
     }
     INIT(this,
         .public = {
             .get_id = _get_id,
             .get_encoding = _get_encoding,
             .encrypt = _encrypt,
             .destroy = _destroy,
         },
         .params = params,
         .pubkey = malloc(params->N * sizeof(uint16_t)),
         .encoding = chunk_clone(data),
         .drbg = drbg->get_ref(drbg),
     );
     /* unpack the encoded public key */
     ntru_octets_2_elements(pubkey_packed_len, data.ptr + header_len,
                            params->q_bits, this->pubkey);
     return &this->public;
 }