strongSwan: eap_sim_plugin.c File Reference
eap_sim_plugin.c File Reference
#include "eap_sim_plugin.h"
#include "eap_sim_server.h"
#include "eap_sim_peer.h"
#include <daemon.h>
#include <simaka_manager.h>
Classes
struct private_eap_sim_plugin_t
Typedefs
typedef struct
private_eap_sim_plugin_t private_eap_sim_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_eap_sim_plugin_t *this)
METHOD (plugin_t, get_features, int, private_eap_sim_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_eap_sim_plugin_t *this)
plugin_t * eap_sim_plugin_create ()
Typedef Documentation
typedef struct private_eap_sim_plugin_t private_eap_sim_plugin_t
Definition at line 24 of file eap_sim_plugin.c.
Function Documentation
plugin_t* eap_sim_plugin_create ()
Definition at line 83 of file eap_sim_plugin.c.
References INIT, lib, library_t::set, and simaka_manager_create().
 {
     private_eap_sim_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .mgr = simaka_manager_create(),
     );
     lib->set(lib, "sim-manager", this->mgr);
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_eap_sim_plugin_t * this)
Definition at line 42 of file eap_sim_plugin.c.
 {
     return "eap-sim";
 }
METHOD (plugin_t , get_features , int , private_eap_sim_plugin_t * this, plugin_feature_t * features[])
Definition at line 48 of file eap_sim_plugin.c.
References AUTH_HMAC_SHA1_128, countof, eap_method_register(), EAP_PEER, EAP_SERVER, EAP_SIM, eap_sim_peer_create(), eap_sim_server_create(), ENCR_AES_CBC, HASH_SHA1, PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, PRF_FIPS_SHA1_160, and RNG_WEAK.
 {
     static plugin_feature_t f[] = {
         PLUGIN_PROVIDE(CUSTOM, "sim-manager"),
         PLUGIN_CALLBACK(eap_method_register, eap_sim_server_create),
             PLUGIN_PROVIDE(EAP_SERVER, EAP_SIM),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(PRF, PRF_FIPS_SHA1_160),
                 PLUGIN_DEPENDS(SIGNER, AUTH_HMAC_SHA1_128),
                 PLUGIN_DEPENDS(CRYPTER, ENCR_AES_CBC, 16),
         PLUGIN_CALLBACK(eap_method_register, eap_sim_peer_create),
             PLUGIN_PROVIDE(EAP_PEER, EAP_SIM),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(PRF, PRF_FIPS_SHA1_160),
                 PLUGIN_DEPENDS(SIGNER, AUTH_HMAC_SHA1_128),
                 PLUGIN_DEPENDS(CRYPTER, ENCR_AES_CBC, 16),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_eap_sim_plugin_t * this)
Definition at line 72 of file eap_sim_plugin.c.
References free(), lib, and library_t::set.
 {
     lib->set(lib, "sim-manager", NULL);
     this->mgr->destroy(this->mgr);
     free(this);
 }