strongSwan: ha_attribute
ha_attribute
ha
Classes
struct ha_attribute_t
Typedefs
typedef struct ha_attribute_t ha_attribute_t
Functions
ha_attribute_t * ha_attribute_create (ha_kernel_t *kernel, ha_segments_t *segments)
Detailed Description
Typedef Documentation
typedef struct ha_attribute_t ha_attribute_t
Definition at line 29 of file ha_attribute.h.
Function Documentation
ha_attribute_t* ha_attribute_create (ha_kernel_t * kernel, ha_segments_t * segments)
Create a ha_attribute instance.
See header
Definition at line 369 of file ha_attribute.c.
References enumerator_t::destroy, enumerator_create_empty(), INIT, linked_list_create(), load_pools(), mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by initialize_plugin().
 {
     private_ha_attribute_t *this;
     INIT(this,
         .public = {
             .provider = {
                 .acquire_address = _acquire_address,
                 .release_address = _release_address,
                 .create_attribute_enumerator = enumerator_create_empty,
             },
             .reserve = _reserve,
             .destroy = _destroy,
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .pools = linked_list_create(),
         .kernel = kernel,
         .segments = segments,
     );
     load_pools(this);
     return &this->public;
 }