strongSwan: gcrypt_rsa_public_key
gcrypt_rsa_public_key
gcrypt
Classes
struct gcrypt_rsa_public_key_t
Typedefs
typedef struct
gcrypt_rsa_public_key_t gcrypt_rsa_public_key_t
Functions
gcrypt_rsa_public_key_t * gcrypt_rsa_public_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct gcrypt_rsa_public_key_t gcrypt_rsa_public_key_t
Definition at line 27 of file gcrypt_rsa_public_key.h.
Function Documentation
gcrypt_rsa_public_key_t* gcrypt_rsa_public_key_load (key_type_t type, va_list args)
Load a RSA public key using gcrypt.
Accepts BUILD_RSA_* components.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 298 of file gcrypt_rsa_public_key.c.
References BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_empty, DBG1, DBG_LIB, free(), INIT, key, chunk_t::len, n, chunk_t::ptr, public_key_equals(), public_key_has_fingerprint(), and TRUE.
Referenced by METHOD().
 {
     private_gcrypt_rsa_public_key_t *this;
     gcry_error_t err;
     chunk_t n, e;
     n = e = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_RSA_MODULUS:
                 n = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PUB_EXP:
                 e = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .verify = _verify,
                 .encrypt = _encrypt_,
                 .equals = public_key_equals,
                 .get_keysize = _get_keysize,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = public_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     err = gcry_sexp_build(&this->key, NULL, "(public-key(rsa(n %b)(e %b)))",
                           n.len, n.ptr, e.len, e.ptr);
     if (err)
     {
         DBG1(DBG_LIB, "loading public key failed: %s", gpg_strerror(err));
         free(this);
         return NULL;
     }
     return &this->public;
 }