strongSwan: pts_ita_comp_func_name
pts_ita_comp_func_name
pts
Macros
#define PTS_ITA_QUALIFIER_FLAG_KERNEL (1<<5)
#define PTS_ITA_QUALIFIER_FLAG_SUB (1<<4)
#define PTS_ITA_QUALIFIER_TYPE_SIZE 4
Typedefs
typedef enum
pts_ita_qualifier_type_t pts_ita_qualifier_type_t
typedef enum
pts_ita_comp_func_name_t pts_ita_comp_func_name_t
Enumerations
enum pts_ita_qualifier_type_t {
PTS_ITA_QUALIFIER_TYPE_UNKNOWN = 0x0, PTS_ITA_QUALIFIER_TYPE_TRUSTED = 0x1, PTS_ITA_QUALIFIER_TYPE_OS = 0x2, PTS_ITA_QUALIFIER_TYPE_GUI = 0x3,
PTS_ITA_QUALIFIER_TYPE_APP = 0x4, PTS_ITA_QUALIFIER_TYPE_NET = 0x5, PTS_ITA_QUALIFIER_TYPE_LIB = 0x6, PTS_ITA_QUALIFIER_TYPE_TNC = 0x7,
PTS_ITA_QUALIFIER_TYPE_ALL = 0xF
}
enum pts_ita_comp_func_name_t { PTS_ITA_COMP_FUNC_NAME_IGNORE = 0x0000, PTS_ITA_COMP_FUNC_NAME_TGRUB = 0x0001, PTS_ITA_COMP_FUNC_NAME_TBOOT = 0x0002, PTS_ITA_COMP_FUNC_NAME_IMA = 0x0003 }
Functions
pts_component_t * pts_ita_comp_ima_create (u_int32_t depth, pts_database_t *pts_db)
pts_component_t * pts_ita_comp_tboot_create (u_int32_t depth, pts_database_t *pts_db)
pts_component_t * pts_ita_comp_tgrub_create (u_int32_t depth, pts_database_t *pts_db)
Variables
char pts_ita_qualifier_flag_names []
enum_name_t * pts_ita_qualifier_type_names
enum_name_t * pts_ita_comp_func_names
Detailed Description
Macro Definition Documentation
#define PTS_ITA_QUALIFIER_FLAG_KERNEL (1<<5)
PTS Component Functional Name Qualifier Flags for the ITA namespace
Definition at line 32 of file ita_comp_func_name.h.
Referenced by METHOD(), pts_ita_comp_tboot_create(), and pts_ita_comp_tgrub_create().
#define PTS_ITA_QUALIFIER_FLAG_SUB (1<<4)
Definition at line 33 of file ita_comp_func_name.h.
#define PTS_ITA_QUALIFIER_TYPE_SIZE 4
Size of the PTS Component Functional Name Qualifier Type field
Definition at line 40 of file ita_comp_func_name.h.
Referenced by libimcv_init().
Typedef Documentation
typedef enum pts_ita_comp_func_name_t pts_ita_comp_func_name_t
Definition at line 25 of file ita_comp_func_name.h.
typedef enum pts_ita_qualifier_type_t pts_ita_qualifier_type_t
Definition at line 24 of file ita_comp_func_name.h.
Enumeration Type Documentation
enum pts_ita_comp_func_name_t
PTS Component Functional Name Binary Enumeration for the ITA namespace
Enumerator
PTS_ITA_COMP_FUNC_NAME_IGNORE
Ignore
PTS_ITA_COMP_FUNC_NAME_TGRUB
Trusted GRUB Boot Loader
PTS_ITA_COMP_FUNC_NAME_TBOOT
Trusted Boot
PTS_ITA_COMP_FUNC_NAME_IMA
Linux Integrity Measurement Architecture
Definition at line 72 of file ita_comp_func_name.h.
{
     PTS_ITA_COMP_FUNC_NAME_IGNORE =             0x0000,
     PTS_ITA_COMP_FUNC_NAME_TGRUB =              0x0001,
     PTS_ITA_COMP_FUNC_NAME_TBOOT =              0x0002,
     PTS_ITA_COMP_FUNC_NAME_IMA =                0x0003,
 };
enum pts_ita_qualifier_type_t
PTS Component Functional Name Qualifier Types for the ITA namespace equal to section 5.2 of PTS Protocol: Binding to TNC IF-M Specification
Enumerator
PTS_ITA_QUALIFIER_TYPE_UNKNOWN
Unknown
PTS_ITA_QUALIFIER_TYPE_TRUSTED
Trusted Platform
PTS_ITA_QUALIFIER_TYPE_OS
Operating System
PTS_ITA_QUALIFIER_TYPE_GUI
Graphical User Interface
PTS_ITA_QUALIFIER_TYPE_APP
Application
PTS_ITA_QUALIFIER_TYPE_NET
Networking
PTS_ITA_QUALIFIER_TYPE_LIB
Library
PTS_ITA_QUALIFIER_TYPE_TNC
TNC Defined Component
PTS_ITA_QUALIFIER_TYPE_ALL
All Matching Components
Definition at line 46 of file ita_comp_func_name.h.
{
     PTS_ITA_QUALIFIER_TYPE_UNKNOWN =            0x0,
     PTS_ITA_QUALIFIER_TYPE_TRUSTED =            0x1,
     PTS_ITA_QUALIFIER_TYPE_OS =                 0x2,
     PTS_ITA_QUALIFIER_TYPE_GUI =                0x3,
     PTS_ITA_QUALIFIER_TYPE_APP =                0x4,
     PTS_ITA_QUALIFIER_TYPE_NET =                0x5,
     PTS_ITA_QUALIFIER_TYPE_LIB =                0x6,
     PTS_ITA_QUALIFIER_TYPE_TNC =                0x7,
     PTS_ITA_QUALIFIER_TYPE_ALL =                0xF,
 };
Function Documentation
pts_component_t* pts_ita_comp_ima_create (u_int32_t depth, pts_database_t * pts_db)
Create a PTS ITS Functional Component object
Parameters
depth Sub-component depth
pts_db PTS measurement database
pts_component_t* pts_ita_comp_tboot_create (u_int32_t depth, pts_database_t * pts_db)
Create a PTS ITS Functional Component object
Parameters
depth Sub-component depth
pts_db PTS measurement database
See header
Definition at line 331 of file ita_comp_tboot.c.
References INIT, PEN_ITA, pts_comp_func_name_create(), PTS_ITA_COMP_FUNC_NAME_TBOOT, PTS_ITA_QUALIFIER_FLAG_KERNEL, and PTS_ITA_QUALIFIER_TYPE_TRUSTED.
Referenced by libimcv_init().
 {
     pts_ita_comp_tboot_t *this;
     INIT(this,
         .public = {
             .get_comp_func_name = _get_comp_func_name,
             .get_evidence_flags = _get_evidence_flags,
             .get_depth = _get_depth,
             .measure = _measure,
             .verify = _verify,
             .finalize = _finalize,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .name = pts_comp_func_name_create(PEN_ITA, PTS_ITA_COMP_FUNC_NAME_TBOOT,
                                           PTS_ITA_QUALIFIER_FLAG_KERNEL |
                                           PTS_ITA_QUALIFIER_TYPE_TRUSTED),
         .depth = depth,
         .pts_db = pts_db,
         .ref = 1,
     );
     return &this->public;
 }
pts_component_t* pts_ita_comp_tgrub_create (u_int32_t depth, pts_database_t * pts_db)
Create a PTS ITS Functional Component object
Parameters
depth Sub-component depth
pts_db PTS measurement database
See header
Definition at line 183 of file ita_comp_tgrub.c.
References INIT, PEN_ITA, pts_comp_func_name_create(), PTS_ITA_COMP_FUNC_NAME_TGRUB, PTS_ITA_QUALIFIER_FLAG_KERNEL, and PTS_ITA_QUALIFIER_TYPE_TRUSTED.
Referenced by libimcv_init().
 {
     pts_ita_comp_tgrub_t *this;
     INIT(this,
         .public = {
             .get_comp_func_name = _get_comp_func_name,
             .get_evidence_flags = _get_evidence_flags,
             .get_depth = _get_depth,
             .measure = _measure,
             .verify = _verify,
             .finalize = _finalize,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .name = pts_comp_func_name_create(PEN_ITA, PTS_ITA_COMP_FUNC_NAME_TGRUB,
                                           PTS_ITA_QUALIFIER_FLAG_KERNEL |
                                           PTS_ITA_QUALIFIER_TYPE_TRUSTED),
         .depth = depth,
         .pts_db = pts_db,
         .ref = 1,
     );
     return &this->public;
 }
Variable Documentation
enum_name_t* pts_ita_comp_func_names
Referenced by libimcv_init().
char pts_ita_qualifier_flag_names[]
Definition at line 18 of file ita_comp_func_name.c.
Referenced by libimcv_init().
enum_name_t* pts_ita_qualifier_type_names
Referenced by libimcv_init().