strongSwan: ctr_ipsec_crypter.c File Reference
ctr_ipsec_crypter.c File Reference
#include "ctr_ipsec_crypter.h"
Classes
struct private_ctr_ipsec_crypter_t
Typedefs
typedef struct
private_ctr_ipsec_crypter_t private_ctr_ipsec_crypter_t
Functions
static bool crypt_ctr (private_ctr_ipsec_crypter_t *this, chunk_t in, chunk_t out)
METHOD (crypter_t, crypt, bool, private_ctr_ipsec_crypter_t *this, chunk_t in, chunk_t iv, chunk_t *out)
METHOD (crypter_t, get_block_size, size_t, private_ctr_ipsec_crypter_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_ctr_ipsec_crypter_t *this)
METHOD (crypter_t, get_key_size, size_t, private_ctr_ipsec_crypter_t *this)
METHOD (crypter_t, set_key, bool, private_ctr_ipsec_crypter_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_ctr_ipsec_crypter_t *this)
ctr_ipsec_crypter_t * ctr_ipsec_crypter_create (encryption_algorithm_t algo, size_t key_size)
Typedef Documentation
typedef struct private_ctr_ipsec_crypter_t private_ctr_ipsec_crypter_t
Definition at line 18 of file ctr_ipsec_crypter.c.
Function Documentation
static bool crypt_ctr (private_ctr_ipsec_crypter_t * this, chunk_t in, chunk_t out) static
Do the CTR crypto operation
Definition at line 48 of file ctr_ipsec_crypter.c.
References chunk_create(), chunk_increment(), chunk_skip(), private_ctr_ipsec_crypter_t::crypter, crypter_t::encrypt, FALSE, crypter_t::get_iv_size, private_ctr_ipsec_crypter_t::iv, memcpy, memset, memxor(), min, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     size_t is, bs;
     chunk_t state;
     is = this->crypter->get_iv_size(this->crypter);
     bs = sizeof(this->state);
     this->state.counter = htonl(1);
     state = chunk_create((char*)&this->state, bs);
     while (in.len > 0)
     {
         char iv[is], block[bs];
         memset(iv, 0, is);
         memcpy(block, state.ptr, bs);
         if (!this->crypter->encrypt(this->crypter, chunk_create(block, bs),
                                     chunk_create(iv, is), NULL))
         {
             return FALSE;
         }
         chunk_increment(state);
         if (in.ptr != out.ptr)
         {
             memcpy(out.ptr, in.ptr, min(in.len, bs));
         }
         memxor(out.ptr, block, min(in.len, bs));
         in = chunk_skip(in, bs);
         out = chunk_skip(out, bs);
     }
     return TRUE;
 }
METHOD (crypter_t , crypt , bool , private_ctr_ipsec_crypter_t * this, chunk_t in, chunk_t iv, chunk_t * out)
Definition at line 84 of file ctr_ipsec_crypter.c.
References chunk_alloc, crypt_ctr(), chunk_t::len, memcpy, and chunk_t::ptr.
 {
     memcpy(this->state.iv, iv.ptr, sizeof(this->state.iv));
     if (out)
     {
         *out = chunk_alloc(in.len);
         return crypt_ctr(this, in, *out);
     }
     return crypt_ctr(this, in, in);
 }
METHOD (crypter_t , get_block_size , size_t , private_ctr_ipsec_crypter_t * this)
Definition at line 97 of file ctr_ipsec_crypter.c.
 {
     return 1;
 }
METHOD (crypter_t , get_iv_size , size_t , private_ctr_ipsec_crypter_t * this)
Definition at line 103 of file ctr_ipsec_crypter.c.
 {
     return sizeof(this->state.iv);
 }
METHOD (crypter_t , get_key_size , size_t , private_ctr_ipsec_crypter_t * this)
Definition at line 109 of file ctr_ipsec_crypter.c.
References private_ctr_ipsec_crypter_t::crypter, and crypter_t::get_key_size.
 {
     return this->crypter->get_key_size(this->crypter)
             + sizeof(this->state.nonce);
 }
METHOD (crypter_t , set_key , bool , private_ctr_ipsec_crypter_t * this, chunk_t key)
Definition at line 116 of file ctr_ipsec_crypter.c.
References private_ctr_ipsec_crypter_t::crypter, chunk_t::len, memcpy, chunk_t::ptr, and crypter_t::set_key.
 {
     memcpy(this->state.nonce, key.ptr + key.len - sizeof(this->state.nonce),
            sizeof(this->state.nonce));
     key.len -= sizeof(this->state.nonce);
     return this->crypter->set_key(this->crypter, key);
 }
METHOD (crypter_t , destroy , void , private_ctr_ipsec_crypter_t * this)
Definition at line 125 of file ctr_ipsec_crypter.c.
References private_ctr_ipsec_crypter_t::crypter, crypter_t::destroy, and free().
 {
     this->crypter->destroy(this->crypter);
     free(this);
 }