strongSwan: pem_builder
pem_builder
pem
Functions
private_key_t * pem_private_key_load (key_type_t type, va_list args)
public_key_t * pem_public_key_load (key_type_t type, va_list args)
certificate_t * pem_certificate_load (certificate_type_t type, va_list args)
container_t * pem_container_load (container_type_t type, va_list args)
Detailed Description
Function Documentation
certificate_t* pem_certificate_load (certificate_type_t type, va_list args)
Build PEM encoded certificates.
Parameters
type type of the certificate
args builder_part_t argument list
Returns
certificate, NULL if failed
Certificate PEM loader.
Definition at line 522 of file pem_builder.c.
References CRED_CERTIFICATE, and pem_load().
Referenced by METHOD().
 {
     return pem_load(CRED_CERTIFICATE, type, args);
 }
container_t* pem_container_load (container_type_t type, va_list args)
Build PEM encoded containers.
Parameters
type type of the container
args builder_part_t argument list
Returns
container, NULL if failed
Container PEM loader.
Definition at line 530 of file pem_builder.c.
References CRED_CONTAINER, and pem_load().
Referenced by METHOD().
 {
     return pem_load(CRED_CONTAINER, type, args);
 }
private_key_t* pem_private_key_load (key_type_t type, va_list args)
Load PEM encoded private keys.
Parameters
type type of the key
args builder_part_t argument list
Returns
private key, NULL if failed
Private key PEM loader.
Definition at line 506 of file pem_builder.c.
References CRED_PRIVATE_KEY, and pem_load().
Referenced by METHOD().
 {
     return pem_load(CRED_PRIVATE_KEY, type, args);
 }
public_key_t* pem_public_key_load (key_type_t type, va_list args)
Load PEM encoded public keys.
Parameters
type type of the key
args builder_part_t argument list
Returns
public key, NULL if failed
Public key PEM loader.
Definition at line 514 of file pem_builder.c.
References CRED_PUBLIC_KEY, and pem_load().
Referenced by METHOD().
 {
     return pem_load(CRED_PUBLIC_KEY, type, args);
 }