strongSwan: openssl_ec_diffie_hellman.c File Reference
openssl_ec_diffie_hellman.c File Reference
#include <openssl/opensslconf.h>
#include <openssl/bn.h>
#include <openssl/ec.h>
#include <openssl/objects.h>
#include "openssl_ec_diffie_hellman.h"
#include "openssl_util.h"
#include <utils/debug.h>
Classes
struct private_openssl_ec_diffie_hellman_t
struct bp_curve
Typedefs
typedef struct
private_openssl_ec_diffie_hellman_t private_openssl_ec_diffie_hellman_t
Functions
static bool chunk2ecp (const EC_GROUP *group, chunk_t chunk, EC_POINT *point)
static bool ecp2chunk (const EC_GROUP *group, const EC_POINT *point, chunk_t *chunk, bool x_coordinate_only)
static bool compute_shared_key (private_openssl_ec_diffie_hellman_t *this, chunk_t *shared_secret)
METHOD (diffie_hellman_t, set_other_public_value, bool, private_openssl_ec_diffie_hellman_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_my_public_value, bool, private_openssl_ec_diffie_hellman_t *this, chunk_t *value)
METHOD (diffie_hellman_t, set_private_value, bool, private_openssl_ec_diffie_hellman_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_shared_secret, bool, private_openssl_ec_diffie_hellman_t *this, chunk_t *secret)
METHOD (diffie_hellman_t, get_dh_group, diffie_hellman_group_t, private_openssl_ec_diffie_hellman_t *this)
METHOD (diffie_hellman_t, destroy, void, private_openssl_ec_diffie_hellman_t *this)
EC_GROUP * ec_group_new_brainpool (bp_curve *curve)
static EC_KEY * ec_key_new_brainpool (diffie_hellman_group_t group)
openssl_ec_diffie_hellman_t * openssl_ec_diffie_hellman_create (diffie_hellman_group_t group)
Variables
static bp_curve bp_curves []
Typedef Documentation
typedef struct private_openssl_ec_diffie_hellman_t private_openssl_ec_diffie_hellman_t
Definition at line 30 of file openssl_ec_diffie_hellman.c.
Function Documentation
static bool chunk2ecp (const EC_GROUP * group, chunk_t chunk, EC_POINT * point) static
Convert a chunk to an EC_POINT (which must already exist). The x and y coordinates of the point have to be concatenated in the chunk.
Definition at line 76 of file openssl_ec_diffie_hellman.c.
References ctx, FALSE, openssl_bn_split(), and TRUE.
Referenced by METHOD().
 {
     BN_CTX *ctx;
     BIGNUM *x, *y;
     bool ret = FALSE;
     ctx = BN_CTX_new();
     if (!ctx)
     {
         return FALSE;
     }
     BN_CTX_start(ctx);
     x = BN_CTX_get(ctx);
     y = BN_CTX_get(ctx);
     if (!x || !y)
     {
         goto error;
     }
     if (!openssl_bn_split(chunk, x, y))
     {
         goto error;
     }
     if (!EC_POINT_set_affine_coordinates_GFp(group, point, x, y, ctx))
     {
         goto error;
     }
     if (!EC_POINT_is_on_curve(group, point, ctx))
     {
         goto error;
     }
     ret = TRUE;
 error:
     BN_CTX_end(ctx);
     BN_CTX_free(ctx);
     return ret;
 }
static bool compute_shared_key (private_openssl_ec_diffie_hellman_t * this, chunk_t * shared_secret) static
Compute the shared secret.
We cannot use the function ECDH_compute_key() because that returns only the x coordinate of the shared secret point (which is defined, for instance, in 'NIST SP 800-56A'). However, we need both coordinates as RFC 4753 says: "The Diffie-Hellman public value is obtained by concatenating the x and y values. The format of the Diffie-Hellman shared secret value is the same as that of the Diffie-Hellman public value."
Definition at line 175 of file openssl_ec_diffie_hellman.c.
References ecp2chunk(), FALSE, settings_t::get_bool, key, lib, library_t::ns, library_t::settings, and TRUE.
Referenced by METHOD().
 {
     const BIGNUM *priv_key;
     EC_POINT *secret = NULL;
     bool x_coordinate_only, ret = FALSE;
     priv_key = EC_KEY_get0_private_key(this->key);
     if (!priv_key)
     {
         goto error;
     }
     secret = EC_POINT_new(this->ec_group);
     if (!secret)
     {
         goto error;
     }
     if (!EC_POINT_mul(this->ec_group, secret, NULL, this->pub_key, priv_key, NULL))
     {
         goto error;
     }
     /*
      * The default setting ecp_x_coordinate_only = TRUE
      * applies the following errata for RFC 4753:
      * http://www.rfc-editor.org/errata_search.php?eid=9
      */
     x_coordinate_only = lib->settings->get_bool(lib->settings,
                                     "%s.ecp_x_coordinate_only", TRUE, lib->ns);
     if (!ecp2chunk(this->ec_group, secret, shared_secret, x_coordinate_only))
     {
         goto error;
     }
     ret = TRUE;
 error:
     if (secret)
     {
         EC_POINT_clear_free(secret);
     }
     return ret;
 }
EC_GROUP* ec_group_new_brainpool (bp_curve * curve)
Create an EC_GROUP object for an ECC Brainpool curve
Definition at line 476 of file openssl_ec_diffie_hellman.c.
References a, bp_curve::a, b, bp_curve::b, ctx, G, group, chunk_t::len, bp_curve::p, chunk_t::ptr, q, bp_curve::q, result, bp_curve::x, and bp_curve::y.
Referenced by ec_key_new_brainpool().
 {
     BIGNUM *p, *a, *b, *x, *y, *q;
     const BIGNUM *h;
     EC_POINT *G = NULL;
     EC_GROUP *group = NULL, *result = NULL;
     BN_CTX *ctx = NULL;
     ctx = BN_CTX_new();
     p = BN_bin2bn(curve->p.ptr, curve->p.len, NULL);
     a = BN_bin2bn(curve->a.ptr, curve->a.len, NULL);
     b = BN_bin2bn(curve->b.ptr, curve->b.len, NULL);
     x = BN_bin2bn(curve->x.ptr, curve->x.len, NULL);
     y = BN_bin2bn(curve->y.ptr, curve->y.len, NULL);
     q = BN_bin2bn(curve->q.ptr, curve->q.len, NULL);
     /* all supported groups have a cofactor of 1 */
     h = BN_value_one();
     if (!ctx || !p || !a || !b || !x || !y || !q)
     {
         goto failed;
     }
     group = EC_GROUP_new_curve_GFp(p, a, b, ctx);
     if (!group)
     {
         goto failed;
     }
     G = EC_POINT_new(group);
     if (!G || !EC_POINT_set_affine_coordinates_GFp(group, G, x, y, ctx))
     {
         goto failed;
     }
     if (!EC_GROUP_set_generator(group, G, q, h))
     {
         goto failed;
     }
     result = group;
 failed:
     if (!result && group)
     {
         EC_GROUP_free(group);
     }
     if (G)
     {
         EC_POINT_free(G);
     }
     BN_CTX_free(ctx);
     BN_free(p);
     BN_free(a);
     BN_free(b);
     BN_free(x);
     BN_free(y);
     BN_free(q);
     return result;
 }
static EC_KEY* ec_key_new_brainpool (diffie_hellman_group_t group) static
Create an EC_KEY for ECC Brainpool curves as defined above
Definition at line 535 of file openssl_ec_diffie_hellman.c.
References countof, curve, ec_group_new_brainpool(), and key.
Referenced by openssl_ec_diffie_hellman_create().
 {
     bp_curve *curve = NULL;
     EC_GROUP *ec_group;
     EC_KEY *key = NULL;
     int i;
     for (i = 0; i < countof(bp_curves); i++)
     {
         if (bp_curves[i].group == group)
         {
             curve = &bp_curves[i];
         }
     }
     if (!curve)
     {
         return NULL;
     }
     ec_group = ec_group_new_brainpool(curve);
     if (!ec_group)
     {
         return NULL;
     }
     key = EC_KEY_new();
     if (!key || !EC_KEY_set_group(key, ec_group))
     {
         EC_KEY_free(key);
         key = NULL;
     }
     EC_GROUP_free(ec_group);
     return key;
 }
static bool ecp2chunk (const EC_GROUP * group, const EC_POINT * point, chunk_t * chunk, bool x_coordinate_only) static
Convert an EC_POINT to a chunk by concatenating the x and y coordinates of the point. This function allocates memory for the chunk.
Definition at line 122 of file openssl_ec_diffie_hellman.c.
References ctx, EC_FIELD_ELEMENT_LEN, FALSE, openssl_bn_cat(), and TRUE.
Referenced by compute_shared_key(), and METHOD().
 {
     BN_CTX *ctx;
     BIGNUM *x, *y;
     bool ret = FALSE;
     ctx = BN_CTX_new();
     if (!ctx)
     {
         return FALSE;
     }
     BN_CTX_start(ctx);
     x = BN_CTX_get(ctx);
     y = BN_CTX_get(ctx);
     if (!x || !y)
     {
         goto error;
     }
     if (!EC_POINT_get_affine_coordinates_GFp(group, point, x, y, ctx))
     {
         goto error;
     }
     if (x_coordinate_only)
     {
         y = NULL;
     }
     if (!openssl_bn_cat(EC_FIELD_ELEMENT_LEN(group), x, y, chunk))
     {
         goto error;
     }
     ret = TRUE;
 error:
     BN_CTX_end(ctx);
     BN_CTX_free(ctx);
     return ret;
 }
METHOD (diffie_hellman_t , set_other_public_value , bool , private_openssl_ec_diffie_hellman_t * this, chunk_t value)
Definition at line 220 of file openssl_ec_diffie_hellman.c.
References chunk2ecp(), chunk_clear(), compute_shared_key(), DBG1, DBG_LIB, diffie_hellman_verify_value(), FALSE, group, and TRUE.
 {
     if (!diffie_hellman_verify_value(this->group, value))
     {
         return FALSE;
     }
     if (!chunk2ecp(this->ec_group, value, this->pub_key))
     {
         DBG1(DBG_LIB, "ECDH public value is malformed");
         return FALSE;
     }
     chunk_clear(&this->shared_secret);
     if (!compute_shared_key(this, &this->shared_secret)) {
         DBG1(DBG_LIB, "ECDH shared secret computation failed");
         return FALSE;
     }
     this->computed = TRUE;
     return TRUE;
 }
METHOD (diffie_hellman_t , get_my_public_value , bool , private_openssl_ec_diffie_hellman_t * this, chunk_t * value)
Definition at line 245 of file openssl_ec_diffie_hellman.c.
References ecp2chunk(), FALSE, key, and TRUE.
 {
     ecp2chunk(this->ec_group, EC_KEY_get0_public_key(this->key), value, FALSE);
     return TRUE;
 }
METHOD (diffie_hellman_t , set_private_value , bool , private_openssl_ec_diffie_hellman_t * this, chunk_t value)
Definition at line 252 of file openssl_ec_diffie_hellman.c.
References FALSE, key, chunk_t::len, chunk_t::ptr, pub(), and TRUE.
 {
     EC_POINT *pub = NULL;
     BIGNUM *priv = NULL;
     bool ret = FALSE;
     priv = BN_bin2bn(value.ptr, value.len, NULL);
     if (!priv)
     {
         goto error;
     }
     pub = EC_POINT_new(EC_KEY_get0_group(this->key));
     if (!pub)
     {
         goto error;
     }
     if (EC_POINT_mul(this->ec_group, pub, priv, NULL, NULL, NULL) != 1)
     {
         goto error;
     }
     if (EC_KEY_set_private_key(this->key, priv) != 1)
     {
         goto error;
     }
     if (EC_KEY_set_public_key(this->key, pub) != 1)
     {
         goto error;
     }
     ret = TRUE;
 error:
     if (pub)
     {
         EC_POINT_free(pub);
     }
     if (priv)
     {
         BN_free(priv);
     }
     return ret;
 }
METHOD (diffie_hellman_t , get_shared_secret , bool , private_openssl_ec_diffie_hellman_t * this, chunk_t * secret)
Definition at line 295 of file openssl_ec_diffie_hellman.c.
References chunk_clone, FALSE, and TRUE.
 {
     if (!this->computed)
     {
         return FALSE;
     }
     *secret = chunk_clone(this->shared_secret);
     return TRUE;
 }
METHOD (diffie_hellman_t , get_dh_group , diffie_hellman_group_t , private_openssl_ec_diffie_hellman_t * this)
Definition at line 306 of file openssl_ec_diffie_hellman.c.
References group.
 {
     return this->group;
 }
METHOD (diffie_hellman_t , destroy , void , private_openssl_ec_diffie_hellman_t * this)
Definition at line 312 of file openssl_ec_diffie_hellman.c.
References chunk_clear(), free(), and key.
 {
     if (this->pub_key)
     {
         EC_POINT_clear_free(this->pub_key);
     }
     if (this->key)
     {
         EC_KEY_free(this->key);
     }
     chunk_clear(&this->shared_secret);
     free(this);
 }
Variable Documentation
bp_curve bp_curves[] static
List of ECC Brainpool curves
Definition at line 364 of file openssl_ec_diffie_hellman.c.