strongSwan: id manager
id manager
tkm
Classes
struct tkm_id_manager_t
Typedefs
typedef struct tkm_id_manager_t tkm_id_manager_t
typedef enum tkm_context_kind_t tkm_context_kind_t
typedef uint64_t tkm_limits_t [TKM_CTX_MAX]
Enumerations
enum tkm_context_kind_t {
TKM_CTX_NONCE, TKM_CTX_DH, TKM_CTX_CC, TKM_CTX_ISA,
TKM_CTX_AE, TKM_CTX_ESA, TKM_CTX_MAX
}
Functions
tkm_id_manager_t * tkm_id_manager_create (const tkm_limits_t limits)
Variables
enum_name_t * tkm_context_kind_names
Detailed Description
Typedef Documentation
typedef enum tkm_context_kind_t tkm_context_kind_t
Definition at line 28 of file tkm_id_manager.h.
typedef struct tkm_id_manager_t tkm_id_manager_t
Definition at line 27 of file tkm_id_manager.h.
typedef uint64_t tkm_limits_t[TKM_CTX_MAX]
TKM context limits.
Definition at line 59 of file tkm_id_manager.h.
Enumeration Type Documentation
enum tkm_context_kind_t
Trusted key manager context kinds.
Enumerator
TKM_CTX_NONCE
Nonce context
TKM_CTX_DH
Diffie-Hellman context
TKM_CTX_CC
Certificate chain context
TKM_CTX_ISA
IKE SA context
TKM_CTX_AE
Authenticated Endpoint context
TKM_CTX_ESA
ESP SA context
TKM_CTX_MAX
helper to determine the number of elements in this enum
Definition at line 33 of file tkm_id_manager.h.
{
     TKM_CTX_NONCE,
     TKM_CTX_DH,
     TKM_CTX_CC,
     TKM_CTX_ISA,
     TKM_CTX_AE,
     TKM_CTX_ESA,
     TKM_CTX_MAX,
 };
Function Documentation
tkm_id_manager_t* tkm_id_manager_create (const tkm_limits_t limits)
Create a tkm id manager instance using the given context limits.
Definition at line 142 of file tkm_id_manager.c.
References DBG2, DBG_LIB, INIT, rwlock_create(), RWLOCK_TYPE_DEFAULT, tkm_context_kind_names, and TKM_CTX_MAX.
Referenced by START_TEST(), and tkm_init().
 {
     private_tkm_id_manager_t *this;
     int i;
     INIT(this,
         .public = {
             .acquire_id = _acquire_id,
             .release_id = _release_id,
             .destroy = _destroy,
         },
     );
     for (i = 0; i < TKM_CTX_MAX; i++)
     {
         this->limits[i] = limits[i];
         this->ctxids[i] = calloc(limits[i], sizeof(bool));
         this->locks[i] = rwlock_create(RWLOCK_TYPE_DEFAULT);
         DBG2(DBG_LIB, "%N initialized, %llu slot(s)", tkm_context_kind_names, i,
              limits[i]);
     }
     return &this->public;
 }
Variable Documentation
enum_name_t* tkm_context_kind_names
enum name for context_kind_t.
Referenced by METHOD(), and tkm_id_manager_create().