strongSwan: unbound_response
unbound_response
unbound
Classes
struct unbound_response_t
Typedefs
typedef struct unbound_response_t unbound_response_t
Functions
unbound_response_t * unbound_response_create_frm_libub_response (struct ub_result *response)
Detailed Description
Typedef Documentation
typedef struct unbound_response_t unbound_response_t
Definition at line 27 of file unbound_response.h.
Function Documentation
unbound_response_t* unbound_response_create_frm_libub_response (struct ub_result * response)
Create an unbound_response instance from a response of the unbound library.
Parameters
response a response of the unbound library
Returns
an unbound_response conforming to the resolver_response interface, or NULL on failure
Create RRset
Parse the received DNS packet using the ldns library
Create the RRset for which the query was performed.
Definition at line 118 of file unbound_response.c.
References BOGUS, DBG1, DBG_LIB, destroy(), INDETERMINATE, INIT, linked_list_t::insert_last, linked_list_create(), rr_set_create(), SECURE, status, strdup, and unbound_rr_create_frm_ldns_rr().
Referenced by METHOD().
 {
     private_unbound_response_t *this = NULL;
     INIT(this,
         .public = {
             .interface = {
                 .get_query_name = _get_query_name,
                 .get_canon_name = _get_canon_name,
                 .has_data = _has_data,
                 .query_name_exist = _query_name_exist,
                 .get_security_state = _get_security_state,
                 .get_rr_set = _get_rr_set,
                 .destroy = _destroy,
             },
         },
     );
     this->query_name = strdup(libub_response->qname);
     if (libub_response->canonname)
     {
         this->canon_name = strdup(libub_response->canonname);
     }
     this->has_data = libub_response->havedata;
     this->query_name_exist = !(libub_response->nxdomain);
     if (libub_response->secure)
     {
         this->security_state = SECURE;
     }
     else if (libub_response->bogus)
     {
         this->security_state = BOGUS;
     }
     else
     {
         this->security_state = INDETERMINATE;
     }
     if (this->query_name_exist && this->has_data)
     {
         ldns_pkt *dns_pkt = NULL;
         ldns_rr_list *orig_rr_list = NULL;
         size_t orig_rr_count;
         ldns_rr *orig_rr = NULL;
         ldns_rdf *orig_rdf = NULL;
         ldns_status status;
         linked_list_t *rr_list = NULL, *rrsig_list = NULL;
         unbound_rr_t *rr = NULL;
         int i;
         status = ldns_wire2pkt(&dns_pkt, libub_response->answer_packet,
                                libub_response->answer_len);
         if (status != LDNS_STATUS_OK)
         {
             DBG1(DBG_LIB, "failed to parse DNS packet");
             destroy(this);
             return NULL;
         }
         /* Create a list with the queried RRs. If there are corresponding RRSIGs
          * create also a list with these.
          */
         rr_list = linked_list_create();
         orig_rr_list = ldns_pkt_get_section_clone(dns_pkt, LDNS_SECTION_ANSWER);
         orig_rr_count = ldns_rr_list_rr_count(orig_rr_list);
         for (i = 0; i < orig_rr_count; i++)
         {
             orig_rr = ldns_rr_list_rr(orig_rr_list, i);
             if (ldns_rr_get_type(orig_rr) == libub_response->qtype &&
                 ldns_rr_get_class(orig_rr) == libub_response->qclass)
             {
                 /* RR is part of the queried RRset.
                  * => add it to the list of Resource Records.
                  */
                 rr = unbound_rr_create_frm_ldns_rr(orig_rr);
                 if (rr)
                 {
                     rr_list->insert_last(rr_list, rr);
                 }
                 else
                 {
                     DBG1(DBG_LIB, "failed to create RR");
                 }
             }
             if (ldns_rr_get_type(orig_rr) == LDNS_RR_TYPE_RRSIG)
             {
                 orig_rdf = ldns_rr_rrsig_typecovered(orig_rr);
                 if (!orig_rdf)
                 {
                     DBG1(DBG_LIB, "failed to get the type covered by an RRSIG");
                 }
                 else if (ldns_rdf2native_int16(orig_rdf) == libub_response->qtype)
                 {
                     /* The current RR represent a signature (RRSIG)
                      * which belongs to the queried RRset.
                      * => add it to the list of signatures.
                      */
                     rr = unbound_rr_create_frm_ldns_rr(orig_rr);
                     if (rr)
                     {
                         if (!rrsig_list)
{
                             rrsig_list = linked_list_create();
                         }
                         rrsig_list->insert_last(rrsig_list, rr);
                     }
                     else
                     {
                         DBG1(DBG_LIB, "failed to create RRSIG");
                     }
                 }
                 else
                 {
                     DBG1(DBG_LIB, "failed to determine the RR type "
                                   "covered by RRSIG RR");
                 }
             }
         }
         this->rr_set = rr_set_create(rr_list, rrsig_list);
         ldns_pkt_free(dns_pkt);
         ldns_rr_list_free(orig_rr_list);
     }
     return &this->public;
 }