strongSwan: x509_plugin.c File Reference
x509_plugin.c File Reference
#include "x509_plugin.h"
#include <library.h>
#include "x509_cert.h"
#include "x509_ac.h"
#include "x509_crl.h"
#include "x509_ocsp_request.h"
#include "x509_ocsp_response.h"
#include "x509_pkcs10.h"
Classes
struct private_x509_plugin_t
Typedefs
typedef struct
private_x509_plugin_t private_x509_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_x509_plugin_t *this)
METHOD (plugin_t, get_features, int, private_x509_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_x509_plugin_t *this)
plugin_t * x509_plugin_create ()
Typedef Documentation
typedef struct private_x509_plugin_t private_x509_plugin_t
Definition at line 26 of file x509_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_x509_plugin_t * this)
Definition at line 39 of file x509_plugin.c.
 {
     return "x509";
 }
METHOD (plugin_t , get_features , int , private_x509_plugin_t * this, plugin_feature_t * features[])
Definition at line 45 of file x509_plugin.c.
References CERT_PKCS10_REQUEST, CERT_X509, CERT_X509_AC, CERT_X509_CRL, CERT_X509_OCSP_REQUEST, CERT_X509_OCSP_RESPONSE, countof, FALSE, HASH_SHA1, KEY_ANY, PLUGIN_DEPENDS, PLUGIN_PROVIDE, PLUGIN_REGISTER, RNG_WEAK, TRUE, x509_ac_gen(), x509_ac_load(), x509_cert_gen(), x509_cert_load(), x509_crl_gen(), x509_crl_load(), x509_ocsp_request_gen(), x509_ocsp_response_load(), x509_pkcs10_gen(), and x509_pkcs10_load().
 {
     static plugin_feature_t f[] = {
         PLUGIN_REGISTER(CERT_ENCODE, x509_cert_gen, FALSE),
             PLUGIN_PROVIDE(CERT_ENCODE, CERT_X509),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
         PLUGIN_REGISTER(CERT_DECODE, x509_cert_load, TRUE),
             PLUGIN_PROVIDE(CERT_DECODE, CERT_X509),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(PUBKEY, KEY_ANY),
         PLUGIN_REGISTER(CERT_ENCODE, x509_ac_gen, FALSE),
             PLUGIN_PROVIDE(CERT_ENCODE, CERT_X509_AC),
         PLUGIN_REGISTER(CERT_DECODE, x509_ac_load, TRUE),
             PLUGIN_PROVIDE(CERT_DECODE, CERT_X509_AC),
         PLUGIN_REGISTER(CERT_ENCODE, x509_crl_gen, FALSE),
             PLUGIN_PROVIDE(CERT_ENCODE, CERT_X509_CRL),
         PLUGIN_REGISTER(CERT_DECODE, x509_crl_load, TRUE),
             PLUGIN_PROVIDE(CERT_DECODE, CERT_X509_CRL),
         PLUGIN_REGISTER(CERT_ENCODE, x509_ocsp_request_gen, FALSE),
             PLUGIN_PROVIDE(CERT_ENCODE, CERT_X509_OCSP_REQUEST),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
         PLUGIN_REGISTER(CERT_DECODE, x509_ocsp_response_load, TRUE),
             PLUGIN_PROVIDE(CERT_DECODE, CERT_X509_OCSP_RESPONSE),
         PLUGIN_REGISTER(CERT_ENCODE, x509_pkcs10_gen, FALSE),
             PLUGIN_PROVIDE(CERT_ENCODE, CERT_PKCS10_REQUEST),
         PLUGIN_REGISTER(CERT_DECODE, x509_pkcs10_load, TRUE),
             PLUGIN_PROVIDE(CERT_DECODE, CERT_PKCS10_REQUEST),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_x509_plugin_t * this)
Definition at line 83 of file x509_plugin.c.
References free().
 {
     free(this);
 }
plugin_t* x509_plugin_create ()
Definition at line 92 of file x509_plugin.c.
References INIT.
 {
     private_x509_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }