strongSwan: os_info
os_info
libimcv
Typedefs
typedef enum os_type_t os_type_t
typedef enum os_fwd_status_t os_fwd_status_t
typedef enum os_package_state_t os_package_state_t
Enumerations
enum os_type_t {
OS_TYPE_UNKNOWN, OS_TYPE_DEBIAN, OS_TYPE_UBUNTU, OS_TYPE_FEDORA,
OS_TYPE_REDHAT, OS_TYPE_CENTOS, OS_TYPE_SUSE, OS_TYPE_GENTOO,
OS_TYPE_ANDROID, OS_TYPE_WINDOWS, OS_TYPE_ROOF
}
enum os_package_state_t { OS_PACKAGE_STATE_UPDATE = 0, OS_PACKAGE_STATE_SECURITY = 1, OS_PACKAGE_STATE_BLACKLIST = 2 }
enum os_fwd_status_t { OS_FWD_DISABLED = 0, OS_FWD_ENABLED = 1, OS_FWD_UNKNOWN = 2 }
Functions
os_type_t os_type_from_name (chunk_t name)
Variables
enum_name_t * os_type_names
enum_name_t * os_package_state_names
enum_name_t * os_fwd_status_names
Detailed Description
Typedef Documentation
typedef enum os_fwd_status_t os_fwd_status_t
Definition at line 25 of file os_info.h.
typedef enum os_package_state_t os_package_state_t
Definition at line 26 of file os_info.h.
typedef enum os_type_t os_type_t
Definition at line 24 of file os_info.h.
Enumeration Type Documentation
enum os_fwd_status_t
Defines the IPv4 forwarding status
Enumerator
OS_FWD_DISABLED
OS_FWD_ENABLED
OS_FWD_UNKNOWN
Definition at line 62 of file os_info.h.
                      {
     OS_FWD_DISABLED =   0,
     OS_FWD_ENABLED =    1,
     OS_FWD_UNKNOWN =    2
 };
enum os_package_state_t
Defines the security state of a package stored in the database
Enumerator
OS_PACKAGE_STATE_UPDATE
OS_PACKAGE_STATE_SECURITY
OS_PACKAGE_STATE_BLACKLIST
Definition at line 51 of file os_info.h.
{
     OS_PACKAGE_STATE_UPDATE =    0,     /* latest update */
     OS_PACKAGE_STATE_SECURITY =  1,     /* latest security fix */
     OS_PACKAGE_STATE_BLACKLIST = 2      /* blacklisted package */
 };
enum os_type_t
Enumerator
OS_TYPE_UNKNOWN
OS_TYPE_DEBIAN
OS_TYPE_UBUNTU
OS_TYPE_FEDORA
OS_TYPE_REDHAT
OS_TYPE_CENTOS
OS_TYPE_SUSE
OS_TYPE_GENTOO
OS_TYPE_ANDROID
OS_TYPE_WINDOWS
OS_TYPE_ROOF
Definition at line 32 of file os_info.h.
                {
     OS_TYPE_UNKNOWN,
     OS_TYPE_DEBIAN,
     OS_TYPE_UBUNTU,
     OS_TYPE_FEDORA,
     OS_TYPE_REDHAT,
     OS_TYPE_CENTOS,
     OS_TYPE_SUSE,
     OS_TYPE_GENTOO,
     OS_TYPE_ANDROID,
     OS_TYPE_WINDOWS,
     OS_TYPE_ROOF
 };
Function Documentation
os_type_t os_type_from_name (chunk_t name)
Convert an OS name into an OS enumeration type
Parameters
name OS name
Returns
OS enumeration type
See header
Definition at line 46 of file os_info.c.
References enum_to_name(), chunk_t::len, memeq(), min, OS_TYPE_DEBIAN, os_type_names, OS_TYPE_ROOF, OS_TYPE_UNKNOWN, chunk_t::ptr, and type.
Referenced by extract_platform_info(), imc_os_info_create(), and METHOD().
 {
     os_type_t type;
     char *name_str;
     for (type = OS_TYPE_DEBIAN; type < OS_TYPE_ROOF; type++)
     {
         /* name_str is a substring of name.ptr */
         name_str = enum_to_name(os_type_names, type);
         if (memeq(name.ptr, name_str, min(name.len, strlen(name_str))))
         {
             return type;
         }
     }
     return OS_TYPE_UNKNOWN;
 }
Variable Documentation
enum_name_t* os_fwd_status_names
Referenced by add_forwarding_enabled(), add_fwd_enabled(), and receive_msg().
enum_name_t* os_package_state_names
Referenced by METHOD().
enum_name_t* os_type_names
Referenced by extract_platform_info(), METHOD(), and os_type_from_name().