strongSwan: tkm_cred.c File Reference
tkm_cred.c File Reference
#include <credentials/sets/mem_cred.h>
#include <collections/hashtable.h>
#include <threading/rwlock.h>
#include <utils/debug.h>
#include "tkm_private_key.h"
#include "tkm_cred.h"
Classes
struct private_tkm_cred_t
Typedefs
typedef struct private_tkm_cred_t private_tkm_cred_t
Functions
METHOD (credential_set_t, create_private_enumerator, enumerator_t *, private_tkm_cred_t *this, key_type_t type, identification_t *id)
METHOD (tkm_cred_t, destroy, void, private_tkm_cred_t *this)
static u_int hash (identification_t *id)
static bool equals (identification_t *a, identification_t *b)
tkm_cred_t * tkm_cred_create ()
Typedef Documentation
typedef struct private_tkm_cred_t private_tkm_cred_t
Definition at line 25 of file tkm_cred.c.
Function Documentation
static bool equals (identification_t * a, identification_t * b) static
Hashtable equals function.
Definition at line 118 of file tkm_cred.c.
References identification_t::equals.
Referenced by algo_list_equals(), get_internal(), id_equals(), METHOD(), peer_cfg_create(), shared_entry_equals(), and tkm_cred_create().
 {
     return a->equals(a, b);
 }
static u_int hash (identification_t * id) static
Hashtable hash function.
Definition at line 110 of file tkm_cred.c.
References chunk_hash(), and identification_t::get_encoding.
Referenced by tkm_cred_create().
 {
     return chunk_hash(id->get_encoding(id));
 }
METHOD (credential_set_t , create_private_enumerator , enumerator_t * , private_tkm_cred_t * this, key_type_t type, identification_t * id)
Definition at line 54 of file tkm_cred.c.
References mem_cred_t::add_key, identification_t::clone, credential_set_t::create_private_enumerator, creds, DBG1, DBG_CFG, key, lock, mem_cred_t::set, tkm_private_key_init(), and spinlock_t::unlock.
 {
     identification_t *entry;
     if (!id)
     {
         return this->known_keys->create_enumerator(this->known_keys);
     }
     this->lock->write_lock(this->lock);
     entry = this->known_keys->get(this->known_keys, id);
     if (!entry)
     {
         identification_t *clone = id->clone(id);
         tkm_private_key_t *key = tkm_private_key_init(id);
         DBG1(DBG_CFG, "adding private key proxy for id '%Y'", clone);
         if (!key)
         {
             DBG1(DBG_CFG, "unable to create private key for id '%Y'", clone);
             this->lock->unlock(this->lock);
             return NULL;
         }
         this->creds->add_key(this->creds, (private_key_t *)key);
         entry = this->known_keys->put(this->known_keys, clone, clone);
     }
     this->lock->unlock(this->lock);
     return this->creds->set.create_private_enumerator(&this->creds->set,
                                                       type, id);
 }
METHOD (tkm_cred_t , destroy , void , private_tkm_cred_t * this)
Definition at line 88 of file tkm_cred.c.
References creds, spinlock_t::destroy, enumerator_t::destroy, mem_cred_t::destroy, identification_t::destroy, enumerator_t::enumerate, free(), and lock.
 {
     enumerator_t *enumerator;
     identification_t *entry;
     enumerator = this->known_keys->create_enumerator(this->known_keys);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         entry->destroy(entry);
     }
     enumerator->destroy(enumerator);
     this->known_keys->destroy(this->known_keys);
     this->creds->destroy(this->creds);
     this->lock->destroy(this->lock);
     free(this);
 }