strongSwan: ntru_trits
ntru_trits
ntru
Classes
struct ntru_trits_t
Typedefs
typedef struct ntru_trits_t ntru_trits_t
Functions
ntru_trits_t * ntru_trits_create (size_t size, hash_algorithm_t alg, chunk_t seed)
Detailed Description
Typedef Documentation
typedef struct ntru_trits_t ntru_trits_t
Definition at line 24 of file ntru_trits.h.
Function Documentation
ntru_trits_t* ntru_trits_create (size_t size, hash_algorithm_t alg, chunk_t seed)
Create a trits array from a seed using MGF1 with a base hash function
Parameters
size size of the trits array
alg hash algorithm to be used by MGF1
seed seed used by MGF1 to generate trits from
Definition at line 70 of file ntru_trits.c.
References mgf1_bitspender_t::destroy, destroy(), mgf1_bitspender_t::get_byte, INIT, len, malloc(), memcpy, mgf1_bitspender_create(), ntru_octet_2_trits(), and TRUE.
 {
     private_ntru_trits_t *this;
     uint8_t octet, buf[5], *trits;
     size_t trits_needed;
     mgf1_bitspender_t *bitspender;
     bitspender = mgf1_bitspender_create(alg, seed, TRUE);
     if (!bitspender)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .get_size = _get_size,
             .get_trits = _get_trits,
             .destroy = _destroy,
         },
         .trits_len = len,
         .trits = malloc(len),
     );
     trits = this->trits;
     trits_needed = this->trits_len;
     while (trits_needed > 0)
     {
         if (!bitspender->get_byte(bitspender, &octet))
         {
             bitspender->destroy(bitspender);
             destroy(this);
             return NULL;
         }
         if (octet < 243)  /* 243 = 3^5 */
         {
             ntru_octet_2_trits(octet, (trits_needed < 5) ? buf : trits);
             if (trits_needed < 5)
             {
                 memcpy(trits, buf, trits_needed);
                 break;
             }
             trits += 5;
             trits_needed -= 5;
         }
     }
     bitspender->destroy(bitspender);
     return &this->public;
 }