strongSwan: task_manager_v1
task_manager_v1
ikev1
Classes
struct task_manager_v1_t
Typedefs
typedef struct task_manager_v1_t task_manager_v1_t
Functions
task_manager_v1_t * task_manager_v1_create (ike_sa_t *ike_sa)
Detailed Description
Typedef Documentation
typedef struct task_manager_v1_t task_manager_v1_t
Definition at line 24 of file task_manager_v1.h.
Function Documentation
task_manager_v1_t* task_manager_v1_create (ike_sa_t * ike_sa)
Create an instance of the task manager.
Parameters
ike_sa IKE_SA to manage.
Definition at line 1954 of file task_manager_v1.c.
References crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_IKE, destroy(), EXCHANGE_TYPE_UNDEFINED, settings_t::get_double, settings_t::get_int, INIT, lib, linked_list_create(), library_t::ns, RESPONDING_SEQ, RETRANSMIT_BASE, RETRANSMIT_TIMEOUT, RETRANSMIT_TRIES, rng, RNG_WEAK, and library_t::settings.
Referenced by task_manager_create().
 {
     private_task_manager_t *this;
     INIT(this,
         .public = {
             .task_manager = {
                 .process_message = _process_message,
                 .queue_task = _queue_task,
                 .queue_ike = _queue_ike,
                 .queue_ike_rekey = _queue_ike_rekey,
                 .queue_ike_reauth = _queue_ike_reauth,
                 .queue_ike_delete = _queue_ike_delete,
                 .queue_mobike = _queue_mobike,
                 .queue_child = _queue_child,
                 .queue_child_rekey = _queue_child_rekey,
                 .queue_child_delete = _queue_child_delete,
                 .queue_dpd = _queue_dpd,
                 .initiate = _initiate,
                 .retransmit = _retransmit,
                 .incr_mid = _incr_mid,
                 .reset = _reset,
                 .adopt_tasks = _adopt_tasks,
                 .adopt_child_tasks = _adopt_child_tasks,
                 .busy = _busy,
                 .create_task_enumerator = _create_task_enumerator,
                 .flush = _flush,
                 .flush_queue = _flush_queue,
                 .destroy = _destroy,
             },
         },
         .initiating = {
             .type = EXCHANGE_TYPE_UNDEFINED,
         },
         .responding = {
             .seqnr = RESPONDING_SEQ,
         },
         .ike_sa = ike_sa,
         .rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK),
         .queued_tasks = linked_list_create(),
         .active_tasks = linked_list_create(),
         .passive_tasks = linked_list_create(),
         .retransmit_tries = lib->settings->get_int(lib->settings,
                         "%s.retransmit_tries", RETRANSMIT_TRIES, lib->ns),
         .retransmit_timeout = lib->settings->get_double(lib->settings,
                         "%s.retransmit_timeout", RETRANSMIT_TIMEOUT, lib->ns),
         .retransmit_base = lib->settings->get_double(lib->settings,
                         "%s.retransmit_base", RETRANSMIT_BASE, lib->ns),
     );
     if (!this->rng)
     {
         DBG1(DBG_IKE, "no RNG found, unable to create IKE_SA");
         destroy(this);
         return NULL;
     }
     if (!this->rng->get_bytes(this->rng, sizeof(this->dpd_send),
                               (void*)&this->dpd_send))
     {
         DBG1(DBG_IKE, "failed to allocate message ID, unable to create IKE_SA");
         destroy(this);
         return NULL;
     }
     this->dpd_send &= 0x7FFFFFFF;
     return &this->public;
 }