strongSwan: eap_mschapv2.c File Reference
eap_mschapv2.c File Reference
#include "eap_mschapv2.h"
#include <ctype.h>
#include <unistd.h>
#include <daemon.h>
#include <library.h>
#include <collections/enumerator.h>
#include <crypto/crypters/crypter.h>
#include <crypto/hashers/hasher.h>
Classes
struct private_eap_mschapv2_t
struct eap_mschapv2_header_t
struct eap_mschapv2_challenge_t
struct eap_mschapv2_response_t
Macros
#define CHALLENGE_LEN 16
#define RESPONSE_LEN 49
#define AUTH_RESPONSE_LEN 42
#define MSCHAPV2_HOST_NAME "strongSwan"
#define SUCCESS_MESSAGE " M=Welcome2strongSwan"
#define FAILURE_MESSAGE "E=691 R=1 C="
#define FAILURE_MESSAGE_LEN (sizeof(FAILURE_MESSAGE) + CHALLENGE_LEN * 2)
#define RETRY_DELAY 2
#define MAX_RETRIES 2
#define HEADER_LEN (sizeof(eap_mschapv2_header_t))
#define SHORT_HEADER_LEN (HEADER_LEN - 3)
#define CHALLENGE_PAYLOAD_LEN (HEADER_LEN + sizeof(eap_mschapv2_challenge_t))
#define RESPONSE_PAYLOAD_LEN (HEADER_LEN + sizeof(eap_mschapv2_response_t))
Typedefs
typedef struct
private_eap_mschapv2_t private_eap_mschapv2_t
typedef struct
eap_mschapv2_header_t eap_mschapv2_header_t
typedef struct
eap_mschapv2_challenge_t eap_mschapv2_challenge_t
typedef struct
eap_mschapv2_response_t eap_mschapv2_response_t
Enumerations
enum mschapv2_opcode_t {
MSCHAPV2_CHALLENGE = 1, MSCHAPV2_RESPONSE = 2, MSCHAPV2_SUCCESS = 3, MSCHAPV2_FAILURE = 4,
MSCHAPV2_CHANGE_PASSWORD = 7
}
enum mschapv2_error_t {
ERROR_RESTRICTED_LOGON_HOURS = 646, ERROR_ACCT_DISABLED = 647, ERROR_PASSWD_EXPIRED = 648, ERROR_NO_DIALIN_PERMISSION = 649,
ERROR_AUTHENTICATION_FAILURE = 691, ERROR_CHANGING_PASSWORD = 709
}
Functions
ENUM_BEGIN (mschapv2_opcode_names, MSCHAPV2_CHALLENGE, MSCHAPV2_FAILURE,"CHALLENGE","RESPONSE","SUCCESS","FAILURE")
ENUM_NEXT (mschapv2_opcode_names, MSCHAPV2_CHANGE_PASSWORD, MSCHAPV2_CHANGE_PASSWORD, MSCHAPV2_FAILURE,"CHANGE_PASSWORD")
ENUM_END (mschapv2_opcode_names, MSCHAPV2_CHANGE_PASSWORD)
ENUM_BEGIN (mschapv2_error_names, ERROR_RESTRICTED_LOGON_HOURS, ERROR_NO_DIALIN_PERMISSION,"ERROR_RESTRICTED_LOGON_HOURS","ERROR_ACCT_DISABLED","ERROR_PASSWD_EXPIRED","ERROR_NO_DIALIN_PERMISSION")
ENUM_NEXT (mschapv2_error_names, ERROR_AUTHENTICATION_FAILURE, ERROR_AUTHENTICATION_FAILURE, ERROR_NO_DIALIN_PERMISSION,"ERROR_AUTHENTICATION_FAILURE")
ENUM_NEXT (mschapv2_error_names, ERROR_CHANGING_PASSWORD, ERROR_CHANGING_PASSWORD, ERROR_AUTHENTICATION_FAILURE,"ERROR_CHANGING_PASSWORD")
ENUM_END (mschapv2_error_names, ERROR_CHANGING_PASSWORD)
struct eap_mschapv2_header_t __attribute__ ((__packed__))
static chunk_t ExpandDESKey (chunk_t key)
static status_t NtPasswordHash (chunk_t password, chunk_t *password_hash)
static status_t ChallengeHash (chunk_t peer_challenge, chunk_t server_challenge, chunk_t username, chunk_t *challenge_hash)
static status_t ChallengeResponse (chunk_t challenge_hash, chunk_t password_hash, chunk_t *response)
static status_t AuthenticatorResponse (chunk_t password_hash_hash, chunk_t challenge_hash, chunk_t nt_response, chunk_t *response)
static status_t GenerateMSK (chunk_t password_hash_hash, chunk_t nt_response, chunk_t *msk)
static status_t GenerateStuff (private_eap_mschapv2_t *this, chunk_t server_challenge, chunk_t peer_challenge, chunk_t username, chunk_t nt_hash)
static chunk_t ascii_to_unicode (chunk_t ascii)
static char * sanitize (char *str)
static chunk_t extract_username (chunk_t id)
static void set_ms_length (eap_mschapv2_header_t *eap, u_int16_t len)
METHOD (eap_method_t, initiate_peer, status_t, private_eap_mschapv2_t *this, eap_payload_t **out)
METHOD (eap_method_t, initiate_server, status_t, private_eap_mschapv2_t *this, eap_payload_t **out)
static bool get_nt_hash (private_eap_mschapv2_t *this, identification_t *me, identification_t *other, chunk_t *nt_hash)
static status_t process_peer_challenge (private_eap_mschapv2_t *this, eap_payload_t *in, eap_payload_t **out)
static status_t process_peer_success (private_eap_mschapv2_t *this, eap_payload_t *in, eap_payload_t **out)
static status_t process_peer_failure (private_eap_mschapv2_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, process_peer, status_t, private_eap_mschapv2_t *this, eap_payload_t *in, eap_payload_t **out)
static status_t process_server_retry (private_eap_mschapv2_t *this, eap_payload_t **out)
static status_t process_server_response (private_eap_mschapv2_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, process_server, status_t, private_eap_mschapv2_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_mschapv2_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_mschapv2_t *this, chunk_t *msk)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_mschapv2_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_mschapv2_t *this, u_int8_t identifier)
METHOD (eap_method_t, is_mutual, bool, private_eap_mschapv2_t *this)
METHOD (eap_method_t, get_auth, auth_cfg_t *, private_eap_mschapv2_t *this)
METHOD (eap_method_t, destroy, void, private_eap_mschapv2_t *this)
static private_eap_mschapv2_t * eap_mschapv2_create_generic (identification_t *server, identification_t *peer)
eap_mschapv2_t * eap_mschapv2_create_server (identification_t *server, identification_t *peer)
eap_mschapv2_t * eap_mschapv2_create_peer (identification_t *server, identification_t *peer)
Variables
u_int8_t code
u_int8_t identifier
u_int16_t length
u_int8_t type
u_int8_t opcode
u_int8_t ms_chapv2_id
u_int16_t ms_length
u_int8_t data []
u_int8_t value_size
u_int8_t challenge [CHALLENGE_LEN]
u_int8_t name []
struct {
u_int8_t peer_challenge [CHALLENGE_LEN]
u_int8_t peer_reserved [8]
u_int8_t nt_response [24]
u_int8_t flags
} response
Macro Definition Documentation
#define AUTH_RESPONSE_LEN 42
Definition at line 157 of file eap_mschapv2.c.
Referenced by process_peer_success(), and process_server_response().
#define CHALLENGE_LEN 16
Definition at line 153 of file eap_mschapv2.c.
Referenced by METHOD(), process_peer_challenge(), process_peer_failure(), process_server_response(), and process_server_retry().
#define CHALLENGE_PAYLOAD_LEN (HEADER_LEN + sizeof(eap_mschapv2_challenge_t))
The minimum length of an MS-CHAPv2 Challenge packet (the name MUST be at least one octet)
Definition at line 250 of file eap_mschapv2.c.
Referenced by METHOD(), and process_peer_challenge().
#define FAILURE_MESSAGE "E=691 R=1 C="
Definition at line 163 of file eap_mschapv2.c.
Referenced by process_server_retry().
#define FAILURE_MESSAGE_LEN (sizeof(FAILURE_MESSAGE) + CHALLENGE_LEN * 2)
Definition at line 165 of file eap_mschapv2.c.
Referenced by process_server_retry().
#define HEADER_LEN (sizeof(eap_mschapv2_header_t))
Length of the MS-CHAPv2 header
Definition at line 238 of file eap_mschapv2.c.
Referenced by process_peer_failure(), process_peer_success(), process_server_response(), and process_server_retry().
#define MAX_RETRIES 2
Definition at line 170 of file eap_mschapv2.c.
Referenced by process_server_retry().
#define MSCHAPV2_HOST_NAME "strongSwan"
Definition at line 159 of file eap_mschapv2.c.
Referenced by METHOD().
#define RESPONSE_LEN 49
Definition at line 155 of file eap_mschapv2.c.
Referenced by process_peer_challenge().
#define RESPONSE_PAYLOAD_LEN (HEADER_LEN + sizeof(eap_mschapv2_response_t))
The minimum length of an MS-CHAPv2 Response packet
Definition at line 255 of file eap_mschapv2.c.
Referenced by process_peer_challenge(), and process_server_response().
#define RETRY_DELAY 2
Definition at line 168 of file eap_mschapv2.c.
Referenced by process_server_retry().
#define SHORT_HEADER_LEN (HEADER_LEN - 3)
Length of the header for MS-CHAPv2 success/failure packets (does not include MS-CHAPv2-ID and MS-Length, i.e. 3 octets)
Definition at line 244 of file eap_mschapv2.c.
Referenced by METHOD(), and process_peer_success().
#define SUCCESS_MESSAGE " M=Welcome2strongSwan"
Definition at line 161 of file eap_mschapv2.c.
Referenced by process_server_response().
Typedef Documentation
typedef struct eap_mschapv2_challenge_t eap_mschapv2_challenge_t
Definition at line 173 of file eap_mschapv2.c.
typedef struct eap_mschapv2_header_t eap_mschapv2_header_t
Definition at line 172 of file eap_mschapv2.c.
typedef struct eap_mschapv2_response_t eap_mschapv2_response_t
Definition at line 174 of file eap_mschapv2.c.
typedef struct private_eap_mschapv2_t private_eap_mschapv2_t
Definition at line 28 of file eap_mschapv2.c.
Enumeration Type Documentation
enum mschapv2_error_t
Error codes
Enumerator
ERROR_RESTRICTED_LOGON_HOURS
ERROR_ACCT_DISABLED
ERROR_PASSWD_EXPIRED
ERROR_NO_DIALIN_PERMISSION
ERROR_AUTHENTICATION_FAILURE
ERROR_CHANGING_PASSWORD
Definition at line 128 of file eap_mschapv2.c.
 {
     ERROR_RESTRICTED_LOGON_HOURS    = 646,
     ERROR_ACCT_DISABLED             = 647,
     ERROR_PASSWD_EXPIRED            = 648,
     ERROR_NO_DIALIN_PERMISSION      = 649,
     ERROR_AUTHENTICATION_FAILURE    = 691,
     ERROR_CHANGING_PASSWORD         = 709,
 };
enum mschapv2_opcode_t
OpCodes
Enumerator
MSCHAPV2_CHALLENGE
MSCHAPV2_RESPONSE
MSCHAPV2_SUCCESS
MSCHAPV2_FAILURE
MSCHAPV2_CHANGE_PASSWORD
Definition at line 104 of file eap_mschapv2.c.
 {
     MSCHAPV2_CHALLENGE = 1,
     MSCHAPV2_RESPONSE = 2,
     MSCHAPV2_SUCCESS = 3,
     MSCHAPV2_FAILURE = 4,
     MSCHAPV2_CHANGE_PASSWORD = 7,
 };
Function Documentation
static chunk_t ascii_to_unicode (chunk_t ascii) static
Converts an ASCII string into a UTF-16 (little-endian) string
Definition at line 548 of file eap_mschapv2.c.
References chunk_alloc, chunk_t::len, and chunk_t::ptr.
Referenced by get_nt_hash().
 {
     int i;
     chunk_t unicode = chunk_alloc(ascii.len * 2);
     for (i = 0; i < ascii.len; i++)
     {
         unicode.ptr[i * 2] = ascii.ptr[i];
         unicode.ptr[i * 2 + 1] = 0;
     }
     return unicode;
 }
static status_t AuthenticatorResponse (chunk_t password_hash_hash, chunk_t challenge_hash, chunk_t nt_response, chunk_t * response) static
Computes the authenticator response
Definition at line 383 of file eap_mschapv2.c.
References hasher_t::allocate_hash, chunk_cata, chunk_empty, chunk_free(), chunk_from_chars, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_IKE, hasher_t::destroy, FAILED, HASH_SHA1, hasher, lib, and SUCCESS.
Referenced by GenerateStuff().
 {
     chunk_t magic1 = chunk_from_chars(
         0x4D, 0x61, 0x67, 0x69, 0x63, 0x20, 0x73, 0x65, 0x72, 0x76,
         0x65, 0x72, 0x20, 0x74, 0x6F, 0x20, 0x63, 0x6C, 0x69, 0x65,
         0x6E, 0x74, 0x20, 0x73, 0x69, 0x67, 0x6E, 0x69, 0x6E, 0x67,
         0x20, 0x63, 0x6F, 0x6E, 0x73, 0x74, 0x61, 0x6E, 0x74);
     chunk_t magic2 = chunk_from_chars(
         0x50, 0x61, 0x64, 0x20, 0x74, 0x6F, 0x20, 0x6D, 0x61, 0x6B,
         0x65, 0x20, 0x69, 0x74, 0x20, 0x64, 0x6F, 0x20, 0x6D, 0x6F,
         0x72, 0x65, 0x20, 0x74, 0x68, 0x61, 0x6E, 0x20, 0x6F, 0x6E,
         0x65, 0x20, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6F,
         0x6E);
     chunk_t digest = chunk_empty, concat;
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (hasher == NULL)
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, SHA1 not supported");
         return FAILED;
     }
     concat = chunk_cata("ccc", password_hash_hash, nt_response, magic1);
     if (!hasher->allocate_hash(hasher, concat, &digest))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     concat = chunk_cata("ccc", digest, challenge_hash, magic2);
     if (!hasher->allocate_hash(hasher, concat, response))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     hasher->destroy(hasher);
     chunk_free(&digest);
     return SUCCESS;
 }
static status_t ChallengeHash (chunk_t peer_challenge, chunk_t server_challenge, chunk_t username, chunk_t * challenge_hash) static
Calculate the challenge hash (i.e. hash [peer_challenge | server_challenge | username (without domain part)] with SHA1)
Definition at line 312 of file eap_mschapv2.c.
References hasher_t::allocate_hash, chunk_cata, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_IKE, hasher_t::destroy, FAILED, HASH_SHA1, hasher, chunk_t::len, lib, and SUCCESS.
Referenced by GenerateStuff().
 {
     chunk_t concat;
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (hasher == NULL)
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, SHA1 not supported");
         return FAILED;
     }
     concat = chunk_cata("ccc", peer_challenge, server_challenge, username);
     if (!hasher->allocate_hash(hasher, concat, challenge_hash))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     hasher->destroy(hasher);
     /* we need only the first 8 octets */
     challenge_hash->len = 8;
     return SUCCESS;
 }
static status_t ChallengeResponse (chunk_t challenge_hash, chunk_t password_hash, chunk_t * response) static
Calculate the challenge response (i.e. expand password_hash to three DES keys and then encrypt the 8-octet challenge_hash with these keys and concatenate the results).
Definition at line 340 of file eap_mschapv2.c.
References chunk_alloc, chunk_alloca, chunk_clear(), chunk_empty, chunk_split(), crypto_factory_t::create_crypter, crypter, library_t::crypto, DBG1, DBG_IKE, crypter_t::destroy, ENCR_DES_ECB, crypter_t::encrypt, ExpandDESKey(), FAILED, keys, chunk_t::len, lib, memcpy, memset, chunk_t::ptr, crypter_t::set_key, and SUCCESS.
Referenced by GenerateStuff().
 {
     int i;
     crypter_t *crypter;
     chunk_t keys[3], z_password_hash;
     crypter = lib->crypto->create_crypter(lib->crypto, ENCR_DES_ECB, 8);
     if (crypter == NULL)
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, DES-ECB not supported");
         return FAILED;
     }
     /* prepare keys: first pad password_hash to 21 octets, these get then split
      * into 7-octet chunks, which then get expanded into 8-octet DES keys */
     z_password_hash = chunk_alloca(21);
     memset(z_password_hash.ptr, 0, z_password_hash.len);
     memcpy(z_password_hash.ptr, password_hash.ptr, password_hash.len);
     chunk_split(z_password_hash, "mmm", 7, &keys[0], 7, &keys[1], 7, &keys[2]);
     *response = chunk_alloc(24);
     for (i = 0; i < 3; i++)
     {
         chunk_t expanded, encrypted;
         expanded = ExpandDESKey(keys[i]);
         if (!crypter->set_key(crypter, expanded) ||
             !crypter->encrypt(crypter, challenge_hash, chunk_empty, &encrypted))
         {
             chunk_clear(&expanded);
             crypter->destroy(crypter);
             return FAILED;
         }
         memcpy(&response->ptr[i * 8], encrypted.ptr, encrypted.len);
         chunk_clear(&encrypted);
         chunk_clear(&expanded);
     }
     crypter->destroy(crypter);
     return SUCCESS;
 }
static private_eap_mschapv2_t* eap_mschapv2_create_generic (identification_t * server, identification_t * peer) static
Generic constructor
Definition at line 1273 of file eap_mschapv2.c.
References auth_cfg_create(), identification_t::clone, and INIT.
Referenced by eap_mschapv2_create_peer(), and eap_mschapv2_create_server().
 {
     private_eap_mschapv2_t *this;
     INIT(this,
         .public = {
             .eap_method_interface = {
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .get_auth = _get_auth,
                 .destroy = _destroy,
             },
         },
         .peer = peer->clone(peer),
         .server = server->clone(server),
         .auth = auth_cfg_create(),
         .state = S_EXPECT_CHALLENGE,
     );
     return this;
 }
ENUM_BEGIN (mschapv2_opcode_names , MSCHAPV2_CHALLENGE , MSCHAPV2_FAILURE , "CHALLENGE" , "RESPONSE" , "SUCCESS" , "FAILURE")
Names for OpCodes
ENUM_BEGIN (mschapv2_error_names , ERROR_RESTRICTED_LOGON_HOURS , ERROR_NO_DIALIN_PERMISSION , "ERROR_RESTRICTED_LOGON_HOURS" , "ERROR_ACCT_DISABLED" , "ERROR_PASSWD_EXPIRED" , "ERROR_NO_DIALIN_PERMISSION")
Names for error codes
ENUM_END (mschapv2_opcode_names , MSCHAPV2_CHANGE_PASSWORD)
ENUM_END (mschapv2_error_names , ERROR_CHANGING_PASSWORD)
ENUM_NEXT (mschapv2_opcode_names , MSCHAPV2_CHANGE_PASSWORD , MSCHAPV2_CHANGE_PASSWORD , MSCHAPV2_FAILURE , "CHANGE_PASSWORD")
ENUM_NEXT (mschapv2_error_names , ERROR_AUTHENTICATION_FAILURE , ERROR_AUTHENTICATION_FAILURE , ERROR_NO_DIALIN_PERMISSION , "ERROR_AUTHENTICATION_FAILURE")
ENUM_NEXT (mschapv2_error_names , ERROR_CHANGING_PASSWORD , ERROR_CHANGING_PASSWORD , ERROR_AUTHENTICATION_FAILURE , "ERROR_CHANGING_PASSWORD")
static chunk_t ExpandDESKey (chunk_t key) static
Expand a 56-bit key to a 64-bit DES key by adding parity bits (odd parity)
Definition at line 261 of file eap_mschapv2.c.
References chunk_alloc, chunk_t::ptr, and val.
Referenced by ChallengeResponse().
 {
     static const u_char bitmask[] = { 0xfe, 0xfc, 0xf8, 0xf0, 0xe0, 0xc0, 0x80 };
     int i;
     u_char carry = 0;
     chunk_t expanded;
     /* expand the 7 octets to 8 octets */
     expanded = chunk_alloc(8);
     for (i = 0; i < 7; i++)
     {
         expanded.ptr[i] = ((key.ptr[i] & bitmask[i]) >> i) | (carry << (8 - i));
         carry = key.ptr[i] & ~bitmask[i];
     }
     expanded.ptr[7] = carry << 1;
     /* add parity bits to each octet */
     for (i = 0; i < 8; i++)
     {
         u_char val = expanded.ptr[i];
         val = (val ^ (val >> 4)) & 0x0f;
         expanded.ptr[i] |= (0x9669 >> val) & 1;
     }
     return expanded;
 }
static chunk_t extract_username (chunk_t id) static
Returns a chunk of just the username part of the given user identity. Note: the chunk points to internal data of the given chunk
Definition at line 582 of file eap_mschapv2.c.
References chunk_create(), chunk_empty, id, and len.
Referenced by process_peer_challenge(), and process_server_response().
 {
     char *has_domain;
     has_domain = (char*)memchr(id.ptr, '\\', id.len);
     if (has_domain)
     {
         int len;
         has_domain++; /* skip the backslash */
         len = id.len - ((u_char*)has_domain - id.ptr);
         return len > 0 ? chunk_create(has_domain, len) : chunk_empty;
     }
     return id;
 }
static status_t GenerateMSK (chunk_t password_hash_hash, chunk_t nt_response, chunk_t * msk) static
Generate the master session key according to RFC3079
Definition at line 427 of file eap_mschapv2.c.
References chunk_cat, chunk_cata, chunk_create(), chunk_from_chars, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_IKE, hasher_t::destroy, FAILED, hasher_t::get_hash, HASH_SHA1, HASH_SIZE_SHA1, hasher, lib, and SUCCESS.
Referenced by GenerateStuff().
 {
     chunk_t magic1 = chunk_from_chars(
         0x54, 0x68, 0x69, 0x73, 0x20, 0x69, 0x73, 0x20, 0x74,
         0x68, 0x65, 0x20, 0x4d, 0x50, 0x50, 0x45, 0x20, 0x4d,
         0x61, 0x73, 0x74, 0x65, 0x72, 0x20, 0x4b, 0x65, 0x79);
     chunk_t magic2 = chunk_from_chars(
         0x4f, 0x6e, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63, 0x6c, 0x69,
         0x65, 0x6e, 0x74, 0x20, 0x73, 0x69, 0x64, 0x65, 0x2c, 0x20,
         0x74, 0x68, 0x69, 0x73, 0x20, 0x69, 0x73, 0x20, 0x74, 0x68,
         0x65, 0x20, 0x73, 0x65, 0x6e, 0x64, 0x20, 0x6b, 0x65, 0x79,
         0x3b, 0x20, 0x6f, 0x6e, 0x20, 0x74, 0x68, 0x65, 0x20, 0x73,
         0x65, 0x72, 0x76, 0x65, 0x72, 0x20, 0x73, 0x69, 0x64, 0x65,
         0x2c, 0x20, 0x69, 0x74, 0x20, 0x69, 0x73, 0x20, 0x74, 0x68,
         0x65, 0x20, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x20,
         0x6b, 0x65, 0x79, 0x2e);
     chunk_t magic3 = chunk_from_chars(
         0x4f, 0x6e, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63, 0x6c, 0x69,
         0x65, 0x6e, 0x74, 0x20, 0x73, 0x69, 0x64, 0x65, 0x2c, 0x20,
         0x74, 0x68, 0x69, 0x73, 0x20, 0x69, 0x73, 0x20, 0x74, 0x68,
         0x65, 0x20, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x20,
         0x6b, 0x65, 0x79, 0x3b, 0x20, 0x6f, 0x6e, 0x20, 0x74, 0x68,
         0x65, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x20, 0x73,
         0x69, 0x64, 0x65, 0x2c, 0x20, 0x69, 0x74, 0x20, 0x69, 0x73,
         0x20, 0x74, 0x68, 0x65, 0x20, 0x73, 0x65, 0x6e, 0x64, 0x20,
         0x6b, 0x65, 0x79, 0x2e);
     chunk_t shapad1 = chunk_from_chars(
         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00);
     chunk_t shapad2 = chunk_from_chars(
         0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2,
         0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2,
         0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2,
         0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2, 0xf2);
     chunk_t keypad = chunk_from_chars(
         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
         0x00, 0x00, 0x00, 0x00, 0x00, 0x00);
     char master_key[HASH_SIZE_SHA1];
     char master_receive_key[HASH_SIZE_SHA1], master_send_key[HASH_SIZE_SHA1];
     chunk_t concat, master;
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (hasher == NULL)
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, SHA1 not supported");
         return FAILED;
     }
     concat = chunk_cata("ccc", password_hash_hash, nt_response, magic1);
     if (!hasher->get_hash(hasher, concat, master_key))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     master = chunk_create(master_key, 16);
     concat = chunk_cata("cccc", master, shapad1, magic2, shapad2);
     if (!hasher->get_hash(hasher, concat, master_receive_key))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     concat = chunk_cata("cccc", master, shapad1, magic3, shapad2);
     if (!hasher->get_hash(hasher, concat, master_send_key))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     *msk = chunk_cat("cccc", chunk_create(master_receive_key, 16),
                      chunk_create(master_send_key, 16), keypad, keypad);
     hasher->destroy(hasher);
     return SUCCESS;
 }
static status_t GenerateStuff (private_eap_mschapv2_t * this, chunk_t server_challenge, chunk_t peer_challenge, chunk_t username, chunk_t nt_hash) static
Definition at line 506 of file eap_mschapv2.c.
References AuthenticatorResponse(), ChallengeHash(), ChallengeResponse(), chunk_empty, chunk_free(), FAILED, GenerateMSK(), nt_response, NtPasswordHash(), status, and SUCCESS.
Referenced by process_peer_challenge(), and process_server_response().
 {
     status_t status = FAILED;
     chunk_t nt_hash_hash = chunk_empty, challenge_hash = chunk_empty;
     if (NtPasswordHash(nt_hash, &nt_hash_hash) != SUCCESS)
     {
         goto error;
     }
     if (ChallengeHash(peer_challenge, server_challenge, username,
                         &challenge_hash) != SUCCESS)
     {
         goto error;
     }
     if (ChallengeResponse(challenge_hash, nt_hash,
                         &this->nt_response) != SUCCESS)
     {
         goto error;
     }
     if (AuthenticatorResponse(nt_hash_hash, challenge_hash,
                         this->nt_response, &this->auth_response) != SUCCESS)
     {
         goto error;
     }
     if (GenerateMSK(nt_hash_hash, this->nt_response, &this->msk) != SUCCESS)
     {
         goto error;
     }
     status = SUCCESS;
 error:
     chunk_free(&nt_hash_hash);
     chunk_free(&challenge_hash);
     return status;
 }
static bool get_nt_hash (private_eap_mschapv2_t * this, identification_t * me, identification_t * other, chunk_t * nt_hash) static
Definition at line 650 of file eap_mschapv2.c.
References ascii_to_unicode(), chunk_clear(), chunk_clone, library_t::credmgr, shared_key_t::destroy, FALSE, shared_key_t::get_key, credential_manager_t::get_shared, lib, NtPasswordHash(), SHARED_EAP, SHARED_NT_HASH, SUCCESS, and TRUE.
Referenced by process_peer_challenge(), and process_server_response().
 {
     shared_key_t *shared;
     chunk_t password;
     /* try to find a stored NT_HASH first */
     shared = lib->credmgr->get_shared(lib->credmgr, SHARED_NT_HASH, me, other);
     if (shared )
     {
         *nt_hash = chunk_clone(shared->get_key(shared));
         shared->destroy(shared);
         return TRUE;
     }
     /* fallback to plaintext password */
     shared = lib->credmgr->get_shared(lib->credmgr, SHARED_EAP, me, other);
     if (shared)
     {
         password = ascii_to_unicode(shared->get_key(shared));
         shared->destroy(shared);
         if (NtPasswordHash(password, nt_hash) == SUCCESS)
         {
             chunk_clear(&password);
             return TRUE;
         }
         chunk_clear(&password);
     }
     return FALSE;
 }
METHOD (eap_method_t , initiate_peer , status_t , private_eap_mschapv2_t * this, eap_payload_t ** out)
Definition at line 606 of file eap_mschapv2.c.
References FAILED.
 {
     /* peer never initiates */
     return FAILED;
 }
METHOD (eap_method_t , initiate_server , status_t , private_eap_mschapv2_t * this, eap_payload_t ** out)
Definition at line 613 of file eap_mschapv2.c.
References eap_mschapv2_challenge_t::challenge, CHALLENGE_LEN, CHALLENGE_PAYLOAD_LEN, chunk_create(), eap_mschapv2_header_t::code, crypto_factory_t::create_rng, library_t::crypto, eap_mschapv2_header_t::data, DBG1, DBG_IKE, DESTROY_IF, EAP_MSCHAPV2, eap_payload_create_data(), EAP_REQUEST, FAILED, identifier, eap_mschapv2_header_t::identifier, len, eap_mschapv2_header_t::length, lib, memcpy, eap_mschapv2_header_t::ms_chapv2_id, MSCHAPV2_CHALLENGE, MSCHAPV2_HOST_NAME, name, eap_mschapv2_challenge_t::name, NEED_MORE, eap_mschapv2_header_t::opcode, rng, RNG_WEAK, set_ms_length(), eap_mschapv2_header_t::type, and eap_mschapv2_challenge_t::value_size.
 {
     rng_t *rng;
     eap_mschapv2_header_t *eap;
     eap_mschapv2_challenge_t *cha;
     const char *name = MSCHAPV2_HOST_NAME;
     u_int16_t len = CHALLENGE_PAYLOAD_LEN + sizeof(MSCHAPV2_HOST_NAME) - 1;
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng || !rng->allocate_bytes(rng, CHALLENGE_LEN, &this->challenge))
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, no challenge");
         DESTROY_IF(rng);
         return FAILED;
     }
     rng->destroy(rng);
     eap = alloca(len);
     eap->code = EAP_REQUEST;
     eap->identifier = this->identifier;
     eap->length = htons(len);
     eap->type = EAP_MSCHAPV2;
     eap->opcode = MSCHAPV2_CHALLENGE;
     eap->ms_chapv2_id = this->mschapv2id;
     set_ms_length(eap, len);
     cha = (eap_mschapv2_challenge_t*)eap->data;
     cha->value_size = CHALLENGE_LEN;
     memcpy(cha->challenge, this->challenge.ptr, this->challenge.len);
     memcpy(cha->name, name, sizeof(MSCHAPV2_HOST_NAME) - 1);
     *out = eap_payload_create_data(chunk_create((void*) eap, len));
     this->state = S_EXPECT_RESPONSE;
     return NEED_MORE;
 }
METHOD (eap_method_t , process_peer , status_t , private_eap_mschapv2_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 952 of file eap_mschapv2.c.
References data, DBG1, DBG_IKE, FAILED, eap_payload_t::get_data, eap_payload_t::get_identifier, identifier, chunk_t::len, MSCHAPV2_CHALLENGE, MSCHAPV2_FAILURE, MSCHAPV2_SUCCESS, eap_mschapv2_header_t::opcode, process_peer_challenge(), process_peer_failure(), process_peer_success(), chunk_t::ptr, and SHORT_HEADER_LEN.
 {
     chunk_t data;
     eap_mschapv2_header_t *eap;
     this->identifier = in->get_identifier(in);
     data = in->get_data(in);
     if (data.len < SHORT_HEADER_LEN)
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message");
         return FAILED;
     }
     eap = (eap_mschapv2_header_t*)data.ptr;
     switch (this->state)
     {
         case S_EXPECT_CHALLENGE:
             if (eap->opcode == MSCHAPV2_CHALLENGE)
             {
                 return process_peer_challenge(this, in, out);
             }
             break;
         case S_EXPECT_SUCCESS:
             switch (eap->opcode)
             {
                 case MSCHAPV2_SUCCESS:
                     return process_peer_success(this, in, out);
                 case MSCHAPV2_FAILURE:
                     return process_peer_failure(this, in, out);
             }
             break;
         default:
             break;
     }
     switch (eap->opcode)
     {
         case MSCHAPV2_CHALLENGE:
         case MSCHAPV2_SUCCESS:
         case MSCHAPV2_FAILURE:
             DBG1(DBG_IKE, "received unexpected EAP-MS-CHAPv2 message with "
                  "OpCode (%N)!", mschapv2_opcode_names, eap->opcode);
             break;
         default:
             DBG1(DBG_IKE, "EAP-MS-CHAPv2 received packet with unsupported "
                  "OpCode (%N)!", mschapv2_opcode_names, eap->opcode);
             break;
     }
     return FAILED;
 }
METHOD (eap_method_t , process_server , status_t , private_eap_mschapv2_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 1156 of file eap_mschapv2.c.
References data, DBG1, DBG_IKE, FAILED, eap_payload_t::get_data, eap_payload_t::get_identifier, identifier, chunk_t::len, MSCHAPV2_FAILURE, MSCHAPV2_RESPONSE, MSCHAPV2_SUCCESS, eap_mschapv2_header_t::opcode, process_server_response(), chunk_t::ptr, SHORT_HEADER_LEN, and SUCCESS.
 {
     eap_mschapv2_header_t *eap;
     chunk_t data;
     if (this->identifier != in->get_identifier(in))
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: "
              "unexpected identifier");
         return FAILED;
     }
     data = in->get_data(in);
     if (data.len < SHORT_HEADER_LEN)
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: too short");
         return FAILED;
     }
     eap = (eap_mschapv2_header_t*)data.ptr;
     switch (this->state)
     {
         case S_EXPECT_RESPONSE:
             if (eap->opcode == MSCHAPV2_RESPONSE)
             {
                 return process_server_response(this, in, out);
             }
             break;
         case S_EXPECT_SUCCESS:
             if (eap->opcode == MSCHAPV2_SUCCESS &&
                 this->msk.ptr)
             {
                 return SUCCESS;
             }
             break;
         default:
             break;
     }
     switch (eap->opcode)
     {
         case MSCHAPV2_FAILURE:
             /* the client may abort the authentication by sending us a failure
              * in any state */
             return FAILED;
         case MSCHAPV2_RESPONSE:
         case MSCHAPV2_SUCCESS:
             DBG1(DBG_IKE, "received unexpected EAP-MS-CHAPv2 message with "
                  "OpCode (%N)!", mschapv2_opcode_names, eap->opcode);
             break;
         default:
             DBG1(DBG_IKE, "EAP-MS-CHAPv2 received packet with unsupported "
                  "OpCode (%N)!", mschapv2_opcode_names, eap->opcode);
             break;
     }
     return FAILED;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_mschapv2_t * this, u_int32_t * vendor)
Definition at line 1215 of file eap_mschapv2.c.
References EAP_MSCHAPV2.
 {
     *vendor = 0;
     return EAP_MSCHAPV2;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_mschapv2_t * this, chunk_t * msk)
Definition at line 1222 of file eap_mschapv2.c.
References FAILED, chunk_t::ptr, and SUCCESS.
 {
     if (this->msk.ptr)
     {
         *msk = this->msk;
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_mschapv2_t * this)
Definition at line 1233 of file eap_mschapv2.c.
References identifier.
 {
     return this->identifier;
 }
METHOD (eap_method_t , set_identifier , void , private_eap_mschapv2_t * this, u_int8_t identifier)
Definition at line 1239 of file eap_mschapv2.c.
References identifier.
 {
     this->identifier = identifier;
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_mschapv2_t * this)
Definition at line 1245 of file eap_mschapv2.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (eap_method_t , get_auth , auth_cfg_t * , private_eap_mschapv2_t * this)
Definition at line 1251 of file eap_mschapv2.c.
 {
     return this->auth;
 }
METHOD (eap_method_t , destroy , void , private_eap_mschapv2_t * this)
Definition at line 1257 of file eap_mschapv2.c.
References challenge, chunk_free(), free(), nt_response, and server.
 {
     this->peer->destroy(this->peer);
     this->server->destroy(this->server);
     this->auth->destroy(this->auth);
     chunk_free(&this->challenge);
     chunk_free(&this->nt_response);
     chunk_free(&this->auth_response);
     chunk_free(&this->msk);
     free(this);
 }
static status_t NtPasswordHash (chunk_t password, chunk_t * password_hash) static
Calculate the NT password hash (i.e. hash the (unicode) password with MD4)
Definition at line 290 of file eap_mschapv2.c.
References hasher_t::allocate_hash, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_IKE, hasher_t::destroy, FAILED, HASH_MD4, hasher, lib, and SUCCESS.
Referenced by GenerateStuff(), and get_nt_hash().
 {
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_MD4);
     if (hasher == NULL)
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, no MD4 hasher available");
         return FAILED;
     }
     if (!hasher->allocate_hash(hasher, password, password_hash))
     {
         hasher->destroy(hasher);
         return FAILED;
     }
     hasher->destroy(hasher);
     return SUCCESS;
 }
static status_t process_peer_challenge (private_eap_mschapv2_t * this, eap_payload_t * in, eap_payload_t ** out) static
Process MS-CHAPv2 Challenge Requests
Definition at line 685 of file eap_mschapv2.c.
References challenge, eap_mschapv2_challenge_t::challenge, CHALLENGE_LEN, CHALLENGE_PAYLOAD_LEN, chunk_alloca, chunk_clear(), chunk_clone, chunk_create(), eap_mschapv2_header_t::code, crypto_factory_t::create_rng, library_t::crypto, data, eap_mschapv2_header_t::data, DBG1, DBG_IKE, rng_t::destroy, DESTROY_IF, EAP_MSCHAPV2, eap_payload_create_data(), EAP_RESPONSE, extract_username(), FAILED, GenerateStuff(), rng_t::get_bytes, eap_payload_t::get_data, get_nt_hash(), identifier, eap_mschapv2_header_t::identifier, if(), chunk_t::len, len, eap_mschapv2_header_t::length, lib, memcpy, memset, eap_mschapv2_header_t::ms_chapv2_id, MSCHAPV2_RESPONSE, eap_mschapv2_response_t::name, NEED_MORE, NOT_FOUND, eap_mschapv2_response_t::nt_response, eap_mschapv2_header_t::opcode, peer_challenge, eap_mschapv2_response_t::peer_challenge, chunk_t::ptr, res, eap_mschapv2_response_t::response, RESPONSE_LEN, RESPONSE_PAYLOAD_LEN, rng, RNG_WEAK, server, set_ms_length(), SUCCESS, eap_mschapv2_header_t::type, eap_mschapv2_challenge_t::value_size, and eap_mschapv2_response_t::value_size.
Referenced by METHOD().
 {
     rng_t *rng;
     eap_mschapv2_header_t *eap;
     eap_mschapv2_challenge_t *cha;
     eap_mschapv2_response_t *res;
     chunk_t data, peer_challenge, userid, username, nt_hash;
     u_int16_t len = RESPONSE_PAYLOAD_LEN;
     data = in->get_data(in);
     eap = (eap_mschapv2_header_t*)data.ptr;
     /* the name MUST be at least one octet long */
     if (data.len < CHALLENGE_PAYLOAD_LEN + 1)
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: too short");
         return FAILED;
     }
     cha = (eap_mschapv2_challenge_t*)eap->data;
     if (cha->value_size != CHALLENGE_LEN)
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: "
              "invalid challenge size");
         return FAILED;
     }
     this->mschapv2id = eap->ms_chapv2_id;
     this->challenge = chunk_clone(chunk_create(cha->challenge, CHALLENGE_LEN));
     peer_challenge = chunk_alloca(CHALLENGE_LEN);
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng || !rng->get_bytes(rng, CHALLENGE_LEN, peer_challenge.ptr))
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, allocating challenge failed");
         DESTROY_IF(rng);
         return FAILED;
     }
     rng->destroy(rng);
     if (!get_nt_hash(this, this->peer, this->server, &nt_hash))
     {
         DBG1(DBG_IKE, "no EAP key found for hosts '%Y' - '%Y'",
              this->server, this->peer);
         return NOT_FOUND;
     }
     /* we transmit the whole user identity (including the domain part) but
      * only use the user part when calculating the challenge hash */
     userid = this->peer->get_encoding(this->peer);
     len += userid.len;
     username = extract_username(userid);
     if (GenerateStuff(this, this->challenge, peer_challenge,
                       username, nt_hash) != SUCCESS)
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 generating NT-Response failed");
         chunk_clear(&nt_hash);
         return FAILED;
     }
     chunk_clear(&nt_hash);
     eap = alloca(len);
     eap->code = EAP_RESPONSE;
     eap->identifier = this->identifier;
     eap->length = htons(len);
     eap->type = EAP_MSCHAPV2;
     eap->opcode = MSCHAPV2_RESPONSE;
     eap->ms_chapv2_id = this->mschapv2id;
     set_ms_length(eap, len);
     res = (eap_mschapv2_response_t*)eap->data;
     res->value_size = RESPONSE_LEN;
     memset(&res->response, 0, RESPONSE_LEN);
     memcpy(res->response.peer_challenge, peer_challenge.ptr, peer_challenge.len);
     memcpy(res->response.nt_response, this->nt_response.ptr, this->nt_response.len);
     memcpy(res->name, userid.ptr, userid.len);
     *out = eap_payload_create_data(chunk_create((void*) eap, len));
     this->state = S_EXPECT_SUCCESS;
     return NEED_MORE;
 }
static status_t process_peer_failure (private_eap_mschapv2_t * this, eap_payload_t * in, eap_payload_t ** out) static
at this point, if the error is retriable, we MAY retry the authentication or MAY send a Change Password packet.
if the error is not retriable (or if we do neither of the above), we SHOULD send a Failure Response packet. windows clients don't do that, and since windows server 2008 r2 behaves pretty odd if we do send a Failure Response, we just don't send one either. windows 7 actually sends a delete notify (which, according to the logs, results in an error on windows server 2008 r2).
btw, windows server 2008 r2 does not send non-retriable errors for e.g. a disabled account but returns the windows error code in a notify payload of type 12345.
Definition at line 858 of file eap_mschapv2.c.
References challenge, CHALLENGE_LEN, chunk_create(), chunk_empty, chunk_free(), chunk_from_hex(), data, eap_mschapv2_header_t::data, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), FAILED, free(), eap_payload_t::get_data, HEADER_LEN, if(), chunk_t::len, malloc(), memcpy, msg, chunk_t::ptr, sanitize(), status, strdup, and strpfx().
Referenced by METHOD().
 {
     status_t status = FAILED;
     enumerator_t *enumerator;
     eap_mschapv2_header_t *eap;
     chunk_t data;
     char *message, *token, *msg = NULL;
     int message_len, error = 0;
     chunk_t challenge = chunk_empty;
     data = in->get_data(in);
     eap = (eap_mschapv2_header_t*)data.ptr;
     if (data.len < 3) /* we want at least an error code: E=e */
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: too short");
         return FAILED;
     }
     message_len = data.len - HEADER_LEN;
     message = malloc(message_len + 1);
     memcpy(message, eap->data, message_len);
     message[message_len] = '\0';
     /* E=eeeeeeeeee R=r C=cccccccccccccccccccccccccccccccc V=vvvvvvvvvv M=<msg> */
     enumerator = enumerator_create_token(message, " ", " ");
     while (enumerator->enumerate(enumerator, &token))
     {
         if (strpfx(token, "E="))
         {
             token += 2;
             error = atoi(token);
         }
         else if (strpfx(token, "R="))
         {
             /* ignore retriable */
         }
         else if (strpfx(token, "C="))
         {
             chunk_t hex;
             token += 2;
             if (strlen(token) != 2 * CHALLENGE_LEN)
             {
                 DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message:"
                      "invalid challenge");
                 goto error;
             }
             chunk_free(&challenge);
             hex = chunk_create(token, 2 * CHALLENGE_LEN);
             challenge = chunk_from_hex(hex, NULL);
         }
         else if (strpfx(token, "V="))
         {
             /* ignore version */
         }
         else if (strpfx(token, "M="))
         {
             token += 2;
             free(msg);
             msg = strdup(token);
         }
     }
     enumerator->destroy(enumerator);
     DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed with error %N: '%s'",
          mschapv2_error_names, error, sanitize(msg));
     status = FAILED;
     this->state = S_DONE;
 error:
     chunk_free(&challenge);
     free(message);
     free(msg);
     return status;
 }
static status_t process_peer_success (private_eap_mschapv2_t * this, eap_payload_t * in, eap_payload_t ** out) static
Process MS-CHAPv2 Success Requests
Definition at line 773 of file eap_mschapv2.c.
References AUTH_RESPONSE_LEN, chunk_create(), chunk_empty, chunk_equals_const(), chunk_free(), chunk_from_hex(), eap_mschapv2_header_t::code, data, eap_mschapv2_header_t::data, DBG1, DBG_IKE, enumerator_t::destroy, EAP_MSCHAPV2, eap_payload_create_data(), EAP_RESPONSE, enumerator_t::enumerate, enumerator_create_token(), FAILED, free(), eap_payload_t::get_data, HEADER_LEN, identifier, eap_mschapv2_header_t::identifier, if(), chunk_t::len, len, eap_mschapv2_header_t::length, malloc(), memcpy, MSCHAPV2_SUCCESS, msg, NEED_MORE, eap_mschapv2_header_t::opcode, chunk_t::ptr, sanitize(), SHORT_HEADER_LEN, status, strdup, strpfx(), and eap_mschapv2_header_t::type.
Referenced by METHOD().
 {
     status_t status = FAILED;
     enumerator_t *enumerator;
     eap_mschapv2_header_t *eap;
     chunk_t data, auth_string = chunk_empty;
     char *message, *token, *msg = NULL;
     int message_len;
     u_int16_t len = SHORT_HEADER_LEN;
     data = in->get_data(in);
     eap = (eap_mschapv2_header_t*)data.ptr;
     if (data.len < AUTH_RESPONSE_LEN)
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: too short");
         return FAILED;
     }
     message_len = data.len - HEADER_LEN;
     message = malloc(message_len + 1);
     memcpy(message, eap->data, message_len);
     message[message_len] = '\0';
     /* S=<auth_string> M=<msg> */
     enumerator = enumerator_create_token(message, " ", " ");
     while (enumerator->enumerate(enumerator, &token))
     {
         if (strpfx(token, "S="))
         {
             chunk_t hex;
             token += 2;
             if (strlen(token) != AUTH_RESPONSE_LEN - 2)
             {
                 DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: "
                      "invalid auth string");
                 goto error;
             }
             chunk_free(&auth_string);
             hex = chunk_create(token, AUTH_RESPONSE_LEN - 2);
             auth_string = chunk_from_hex(hex, NULL);
         }
         else if (strpfx(token, "M="))
         {
             token += 2;
             free(msg);
             msg = strdup(token);
         }
     }
     enumerator->destroy(enumerator);
     if (auth_string.ptr == NULL)
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: "
              "auth string missing");
         goto error;
     }
     if (!chunk_equals_const(this->auth_response, auth_string))
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 verification failed");
         goto error;
     }
     DBG1(DBG_IKE, "EAP-MS-CHAPv2 succeeded: '%s'", sanitize(msg));
     eap = alloca(len);
     eap->code = EAP_RESPONSE;
     eap->identifier = this->identifier;
     eap->length = htons(len);
     eap->type = EAP_MSCHAPV2;
     eap->opcode = MSCHAPV2_SUCCESS;
     *out = eap_payload_create_data(chunk_create((void*) eap, len));
     status = NEED_MORE;
     this->state = S_DONE;
 error:
     chunk_free(&auth_string);
     free(message);
     free(msg);
     return status;
 }
static status_t process_server_response (private_eap_mschapv2_t * this, eap_payload_t * in, eap_payload_t ** out) static
Process MS-CHAPv2 Response response packets
Definition at line 1069 of file eap_mschapv2.c.
References AUTH_RESPONSE_LEN, AUTH_RULE_EAP_IDENTITY, challenge, CHALLENGE_LEN, chunk_clear(), chunk_create(), chunk_free(), chunk_to_hex(), data, eap_mschapv2_header_t::data, DBG1, DBG_IKE, identification_t::destroy, EAP_MSCHAPV2, eap_payload_create_data(), EAP_REQUEST, identification_t::equals, extract_username(), FAILED, GenerateStuff(), eap_payload_t::get_data, identification_t::get_encoding, get_nt_hash(), HEADER_LEN, identification_create_from_string(), identifier, if(), chunk_t::len, len, memcpy, memeq_const(), min, MSCHAPV2_SUCCESS, msg, eap_mschapv2_response_t::name, NEED_MORE, eap_mschapv2_response_t::nt_response, peer_challenge, eap_mschapv2_response_t::peer_challenge, process_server_retry(), chunk_t::ptr, res, eap_mschapv2_response_t::response, RESPONSE_PAYLOAD_LEN, server, set_ms_length(), snprintf, SUCCESS, SUCCESS_MESSAGE, and TRUE.
Referenced by METHOD().
 {
     eap_mschapv2_header_t *eap;
     eap_mschapv2_response_t *res;
     chunk_t data, peer_challenge, username, nt_hash;
     identification_t *userid;
     int name_len;
     char buf[256];
     data = in->get_data(in);
     eap = (eap_mschapv2_header_t*)data.ptr;
     if (data.len < RESPONSE_PAYLOAD_LEN)
     {
         DBG1(DBG_IKE, "received invalid EAP-MS-CHAPv2 message: too short");
         return FAILED;
     }
     res = (eap_mschapv2_response_t*)eap->data;
     peer_challenge = chunk_create(res->response.peer_challenge, CHALLENGE_LEN);
     name_len = min(data.len - RESPONSE_PAYLOAD_LEN, 255);
     snprintf(buf, sizeof(buf), "%.*s", name_len, res->name);
     userid = identification_create_from_string(buf);
     if (!userid->equals(userid, this->peer))
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 username: '%Y'", userid);
     }
     /* userid can only be destroyed after the last use of username */
     username = extract_username(userid->get_encoding(userid));
     if (!get_nt_hash(this, this->server, userid, &nt_hash))
     {
         DBG1(DBG_IKE, "no EAP key found for hosts '%Y' - '%Y'",
                       this->server, userid);
         /* FIXME: windows 7 always sends the username that is first entered in
          * the username box, even, if the user changes it during retries (probably
          * to keep consistent with the EAP-Identity).
          * thus, we could actually fail here, because retries do not make much
          * sense. on the other hand, an attacker could guess usernames, if the
          * error messages were different. */
         userid->destroy(userid);
         return process_server_retry(this, out);
     }
     if (GenerateStuff(this, this->challenge, peer_challenge,
                       username, nt_hash) != SUCCESS)
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 verification failed");
         userid->destroy(userid);
         chunk_clear(&nt_hash);
         return FAILED;
     }
     chunk_clear(&nt_hash);
     if (memeq_const(res->response.nt_response, this->nt_response.ptr,
                     this->nt_response.len))
     {
         chunk_t hex;
         char msg[AUTH_RESPONSE_LEN + sizeof(SUCCESS_MESSAGE)];
         u_int16_t len = HEADER_LEN + AUTH_RESPONSE_LEN + sizeof(SUCCESS_MESSAGE);
         eap = alloca(len);
         eap->code = EAP_REQUEST;
         eap->identifier = ++this->identifier;
         eap->length = htons(len);
         eap->type = EAP_MSCHAPV2;
         eap->opcode = MSCHAPV2_SUCCESS;
         eap->ms_chapv2_id = this->mschapv2id;
         set_ms_length(eap, len);
         hex = chunk_to_hex(this->auth_response, NULL, TRUE);
         snprintf(msg, AUTH_RESPONSE_LEN + sizeof(SUCCESS_MESSAGE),
                       "S=%s%s", hex.ptr, SUCCESS_MESSAGE);
         chunk_free(&hex);
         memcpy(eap->data, msg, AUTH_RESPONSE_LEN + sizeof(SUCCESS_MESSAGE));
         *out = eap_payload_create_data(chunk_create((void*) eap, len));
         this->auth->add(this->auth, AUTH_RULE_EAP_IDENTITY, userid);
         this->state = S_EXPECT_SUCCESS;
         return NEED_MORE;
     }
     userid->destroy(userid);
     return process_server_retry(this, out);
 }
static status_t process_server_retry (private_eap_mschapv2_t * this, eap_payload_t ** out) static
Handles retries on the server
Definition at line 1007 of file eap_mschapv2.c.
References challenge, CHALLENGE_LEN, chunk_create(), chunk_free(), chunk_to_hex(), eap_mschapv2_header_t::code, crypto_factory_t::create_rng, library_t::crypto, eap_mschapv2_header_t::data, DBG1, DBG_IKE, rng_t::destroy, DESTROY_IF, EAP_MSCHAPV2, eap_payload_create_data(), EAP_REQUEST, FAILED, FAILURE_MESSAGE, FAILURE_MESSAGE_LEN, rng_t::get_bytes, HEADER_LEN, identifier, eap_mschapv2_header_t::identifier, len, eap_mschapv2_header_t::length, lib, MAX_RETRIES, memcpy, eap_mschapv2_header_t::ms_chapv2_id, MSCHAPV2_FAILURE, msg, NEED_MORE, nt_response, eap_mschapv2_header_t::opcode, chunk_t::ptr, RETRY_DELAY, rng, RNG_WEAK, set_ms_length(), sleep, snprintf, TRUE, and eap_mschapv2_header_t::type.
Referenced by process_server_response().
 {
     eap_mschapv2_header_t *eap;
     rng_t *rng;
     chunk_t hex;
     char msg[FAILURE_MESSAGE_LEN];
     u_int16_t len = HEADER_LEN + FAILURE_MESSAGE_LEN - 1; /* no null byte */
     if (++this->retries > MAX_RETRIES)
     {
         /* we MAY send a Failure Request with R=0, but windows 7 does not
          * really like that and does not respond with a Failure Response.
          * so, to clean up our state we just fail with an EAP-Failure.
          * this gives an unknown error on the windows side, but is also fine
          * with the standard. */
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 verification failed: "
              "maximum number of retries reached");
         return FAILED;
     }
     DBG1(DBG_IKE, "EAP-MS-CHAPv2 verification failed, retry (%d)", this->retries);
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng || !rng->get_bytes(rng, CHALLENGE_LEN, this->challenge.ptr))
     {
         DBG1(DBG_IKE, "EAP-MS-CHAPv2 failed, allocating challenge failed");
         DESTROY_IF(rng);
         return FAILED;
     }
     rng->destroy(rng);
     chunk_free(&this->nt_response);
     chunk_free(&this->auth_response);
     chunk_free(&this->msk);
     eap = alloca(len);
     eap->code = EAP_REQUEST;
     eap->identifier = ++this->identifier;
     eap->length = htons(len);
     eap->type = EAP_MSCHAPV2;
     eap->opcode = MSCHAPV2_FAILURE;
     eap->ms_chapv2_id = this->mschapv2id++; /* increase for each retry */
     set_ms_length(eap, len);
     hex = chunk_to_hex(this->challenge, NULL, TRUE);
     snprintf(msg, FAILURE_MESSAGE_LEN, "%s%s", FAILURE_MESSAGE, hex.ptr);
     chunk_free(&hex);
     memcpy(eap->data, msg, FAILURE_MESSAGE_LEN - 1); /* no null byte */
     *out = eap_payload_create_data(chunk_create((void*) eap, len));
     /* delay the response for some time to make brute-force attacks harder */
     sleep(RETRY_DELAY);
     /* since the error is retryable the state does not change, we still
      * expect an MSCHAPV2_RESPONSE from the peer */
     return NEED_MORE;
 }
static char* sanitize (char * str) static
sanitize a string for printing
Definition at line 563 of file eap_mschapv2.c.
References str.
Referenced by process_peer_failure(), and process_peer_success().
 {
     char *pos = str;
     while (pos && *pos)
     {
         if (!isprint(*pos))
         {
             *pos = '?';
         }
         pos++;
     }
     return str;
 }
static void set_ms_length (eap_mschapv2_header_t * eap, u_int16_t len) static
Set the ms_length field using aligned write
Definition at line 600 of file eap_mschapv2.c.
References memcpy, and eap_mschapv2_header_t::ms_length.
Referenced by METHOD(), process_peer_challenge(), process_server_response(), and process_server_retry().
 {
     len = htons(len - 5);
     memcpy(&eap->ms_length, &len, sizeof(u_int16_t));
 }
Variable Documentation
u_int8_t challenge[CHALLENGE_LEN]
Challenge
Definition at line 154 of file eap_mschapv2.c.
Referenced by hash_challenge(), METHOD(), process_peer_challenge(), process_peer_failure(), process_server_response(), and process_server_retry().
u_int8_t code
EAP code (REQUEST/RESPONSE)
Definition at line 152 of file eap_mschapv2.c.
u_int8_t data[]
packet data (determined by OpCode)
Definition at line 166 of file eap_mschapv2.c.
Referenced by METHOD(), process_peer_challenge(), process_peer_failure(), process_peer_success(), and process_server_response().
u_int8_t flags
Definition at line 163 of file eap_mschapv2.c.
Referenced by __attribute__(), append_header(), append_header_frag(), builtin_vsnprintf(), chunk_map(), create_notify(), exchange(), fragment_payload_create_from_data(), imc_attestation_process(), imv_attestation_build(), imv_attestation_process(), issue(), manage_ipaddr(), manage_srcroute(), METHOD(), openssl_x509_load(), parse_basicConstraints(), parse_basicConstraints_ext(), parse_certificate(), parse_extendedKeyUsage(), parse_extKeyUsage_ext(), parse_ipAddrBlocks(), parse_keyUsage(), parse_keyUsage_ext(), pem_load(), print_cfn(), print_x509(), process_tnc_msg(), receive_message(), request(), self(), set_nonblock(), START_TEST(), tcg_pts_attr_proto_caps_create(), tcg_pts_attr_simple_evid_final_create(), tcg_seg_attr_seg_env_create(), wait_for_notify(), and x509_cert_load().
u_int8_t identifier
unique message identifier
Definition at line 154 of file eap_mschapv2.c.
Referenced by eap_mschapv2_create_server(), METHOD(), process_peer_challenge(), process_peer_success(), process_server_response(), and process_server_retry().
u_int16_t length
length of whole message
Definition at line 156 of file eap_mschapv2.c.
u_int8_t ms_chapv2_id
MS-CHAPv2-ID (equals identifier)
Definition at line 162 of file eap_mschapv2.c.
u_int16_t ms_length
MS-Length (defined as length - 5)
Definition at line 164 of file eap_mschapv2.c.
u_int8_t name[]
Name
Definition at line 156 of file eap_mschapv2.c.
Referenced by METHOD().
u_int8_t nt_response[24]
Definition at line 161 of file eap_mschapv2.c.
Referenced by GenerateStuff(), METHOD(), and process_server_retry().
u_int8_t opcode
MS-CHAPv2 OpCode
Definition at line 160 of file eap_mschapv2.c.
Referenced by __attribute__(), dhcp_socket_create(), and farp_spoofer_create().
u_int8_t peer_challenge[CHALLENGE_LEN]
Definition at line 157 of file eap_mschapv2.c.
Referenced by process_peer_challenge(), and process_server_response().
u_int8_t peer_reserved[8]
Definition at line 159 of file eap_mschapv2.c.
struct { ... } response
Response
Referenced by add_policy_internal(), auth_conv(), fetch_ocsp(), get_better_ocsp(), get_spi_internal(), main(), mediation_job_create(), METHOD(), ocsp_response_wrapper_create(), parse_singleResponse(), process_acquire(), process_expire(), process_payloads(), process_request(), receive_events(), save_retransmit(), send_message(), send_notify(), send_notify_response(), send_response(), verify_eap(), and verify_radius().
u_int8_t type
EAP type
Definition at line 158 of file eap_mschapv2.c.
u_int8_t value_size
Value-Size
Definition at line 152 of file eap_mschapv2.c.