strongSwan: farp_plugin.c File Reference
farp_plugin.c File Reference
#include "farp_plugin.h"
#include "farp_listener.h"
#include "farp_spoofer.h"
#include <daemon.h>
Classes
struct private_farp_plugin_t
Typedefs
typedef struct
private_farp_plugin_t private_farp_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_farp_plugin_t *this)
static bool plugin_cb (private_farp_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_farp_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_farp_plugin_t *this)
plugin_t * farp_plugin_create ()
Typedef Documentation
typedef struct private_farp_plugin_t private_farp_plugin_t
Definition at line 23 of file farp_plugin.c.
Function Documentation
plugin_t* farp_plugin_create ()
Plugin constructor
Definition at line 91 of file farp_plugin.c.
References CAP_NET_RAW, library_t::caps, DBG1, DBG_NET, destroy(), farp_listener_create(), farp_spoofer_create(), INIT, capabilities_t::keep, lib, and listener.
 {
     private_farp_plugin_t *this;
     if (!lib->caps->keep(lib->caps, CAP_NET_RAW))
     {   /* required to open ARP socket (AF_PACKET). according to capabilities(7)
          * it is also require to use the socket */
         DBG1(DBG_NET, "farp plugin requires CAP_NET_RAW capability");
         return NULL;
     }
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .listener = farp_listener_create(),
     );
     this->spoofer = farp_spoofer_create(this->listener);
     if (!this->spoofer)
     {
         destroy(this);
         return NULL;
     }
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_farp_plugin_t * this)
Definition at line 46 of file farp_plugin.c.
 {
     return "farp";
 }
METHOD (plugin_t , get_features , int , private_farp_plugin_t * this, plugin_feature_t * features[])
Definition at line 69 of file farp_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "farp"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_farp_plugin_t * this)
Definition at line 80 of file farp_plugin.c.
References tkm_listener_t::destroy, DESTROY_IF, free(), and listener.
 {
     DESTROY_IF(this->spoofer);
     this->listener->destroy(this->listener);
     free(this);
 }
static bool plugin_cb (private_farp_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 55 of file farp_plugin.c.
References bus_t::add_listener, daemon_t::bus, charon, bus_t::remove_listener, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
     }
     return TRUE;
 }