strongSwan: settings_parser.c File Reference
settings_parser.c File Reference
#include <stdio.h>
#include <library.h>
#include <collections/array.h>
#include <settings/settings_types.h>
#include <utils/parser_helper.h>
#include "settings_parser.h"
#include <stddef.h>
Classes
union yyalloc
Macros
#define YYBISON 1
#define YYBISON_VERSION "3.0.2"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 1
#define YYPUSH 0
#define YYPULL 1
#define yyparse settings_parser_parse
#define yylex settings_parser_lex
#define yyerror settings_parser_error
#define yydebug settings_parser_debug
#define yynerrs settings_parser_nerrs
#define _GNU_SOURCE /* for asprintf() */
#define YYDEBUG 1
#define YY_NULLPTR 0
#define YYERROR_VERBOSE 1
#define YY_SETTINGS_PARSER_SETTINGS_SETTINGS_PARSER_H_INCLUDED
#define NAME 258
#define STRING 259
#define NEWLINE 260
#define STRING_ERROR 261
#define YYSIZE_T size_t
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(Msgid) Msgid
#define YY_ATTRIBUTE(Spec) /* empty */
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#define _Noreturn YY_ATTRIBUTE ((__noreturn__))
#define YYUSE(E) ((void) (E))
#define YY_INITIAL_VALUE(Value) Value
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC malloc
#define YYFREE free
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYCOPY(Dst, Src, Count)
#define YYFINAL 2
#define YYLAST 13
#define YYNTOKENS 10
#define YYNNTS 8
#define YYNRULES 15
#define YYNSTATES 20
#define YYUNDEFTOK 2
#define YYMAXUTOK 261
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -11
#define yypact_value_is_default(Yystate) (!!((Yystate) == (-11)))
#define YYTABLE_NINF -1
#define yytable_value_is_error(Yytable_value) 0
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYFPRINTF fprintf
#define YYDPRINTF(Args)
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYCASE_(N, S)
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define YYSYNTAX_ERROR
Typedefs
typedef unsigned char yytype_uint8
typedef signed char yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Functions
int settings_parser_lex (YYSTYPE *lvalp, void *scanner)
int settings_parser_lex_init_extra (parser_helper_t *extra, void *scanner)
int settings_parser_lex_destroy (void *scanner)
int settings_parser_set_in (FILE *in, void *scanner)
void settings_parser_set_debug (int debug, void *scanner)
char * settings_parser_get_text (void *scanner)
int settings_parser_get_leng (void *scanner)
int settings_parser_get_lineno (void *scanner)
bool settings_parser_open_next_file (parser_helper_t *ctx)
bool settings_parser_load_string (parser_helper_t *ctx, const char *content)
static void settings_parser_error (parser_helper_t *ctx, const char *s)
static section_t * push_section (parser_helper_t *ctx, char *name)
static section_t * pop_section (parser_helper_t *ctx)
static void add_section (parser_helper_t *ctx, section_t *section)
static void add_setting (parser_helper_t *ctx, kv_t *kv)
static int yylex (YYSTYPE *lvalp, parser_helper_t *ctx)
int settings_parser_parse (parser_helper_t *ctx)
void * malloc (YYSIZE_T)
void free (void *)
static void yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep, parser_helper_t *ctx)
static void yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep, parser_helper_t *ctx)
static void yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
static void yy_reduce_print (yytype_int16 *yyssp, YYSTYPE *yyvsp, int yyrule, parser_helper_t *ctx)
static YYSIZE_T yystrlen (const char *yystr)
static char * yystpcpy (char *yydest, const char *yysrc)
static YYSIZE_T yytnamerr (char *yyres, const char *yystr)
static int yysyntax_error (YYSIZE_T *yymsg_alloc, char **yymsg, yytype_int16 *yyssp, int yytoken)
static void yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep, parser_helper_t *ctx)
int yyparse (parser_helper_t *ctx)
bool settings_parser_parse_file (section_t *root, char *name)
bool settings_parser_parse_string (section_t *root, char *settings)
Variables
int settings_parser_debug
static const yytype_uint8 yytranslate []
static const yytype_uint8 yyrline []
static const char *const yytname []
static const yytype_int8 yypact []
static const yytype_uint8 yydefact []
static const yytype_int8 yypgoto []
static const yytype_int8 yydefgoto []
static const yytype_uint8 yytable []
static const yytype_uint8 yycheck []
static const yytype_uint8 yystos []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
int yydebug
Macro Definition Documentation
#define _GNU_SOURCE /* for asprintf() */
Definition at line 88 of file settings_parser.c.
#define _Noreturn YY_ATTRIBUTE ((__noreturn__))
Definition at line 286 of file settings_parser.c.
#define NAME 258
Definition at line 176 of file settings_parser.c.
#define NEWLINE 260
Definition at line 178 of file settings_parser.c.
Referenced by while().
#define STRING 259
Definition at line 177 of file settings_parser.c.
Referenced by while().
#define STRING_ERROR 261
Definition at line 179 of file settings_parser.c.
Referenced by while().
#define YY_ (Msgid) Msgid
Definition at line 259 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
#define YY_ATTRIBUTE (Spec) /* empty */
Definition at line 269 of file settings_parser.c.
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
Definition at line 274 of file settings_parser.c.
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
Definition at line 278 of file settings_parser.c.
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
Definition at line 309 of file settings_parser.c.
Referenced by yydestruct(), and yyparse().
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
Definition at line 310 of file settings_parser.c.
Referenced by yydestruct(), and yyparse().
#define YY_INITIAL_VALUE (Value) Value
Definition at line 306 of file settings_parser.c.
Referenced by yyparse().
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
Definition at line 657 of file settings_parser.c.
#define YY_NULLPTR 0
Definition at line 140 of file settings_parser.c.
Referenced by yysyntax_error().
#define YY_REDUCE_PRINT (Rule)
Value:
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule, ctx); \
} while (0)
Definition at line 755 of file settings_parser.c.
Referenced by yyparse().
#define YY_SETTINGS_PARSER_SETTINGS_SETTINGS_PARSER_H_INCLUDED
Definition at line 155 of file settings_parser.c.
#define YY_STACK_PRINT (Bottom, Top)
Value:
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)
Definition at line 724 of file settings_parser.c.
Referenced by yyparse().
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Value:
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value, ctx); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)
Definition at line 661 of file settings_parser.c.
Referenced by yydestruct(), and yyparse().
#define YYABORT goto yyabortlab
Definition at line 612 of file settings_parser.c.
Referenced by yyparse().
#define YYACCEPT goto yyacceptlab
Definition at line 611 of file settings_parser.c.
Referenced by yyparse().
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY)                                        \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (yylen);                                       \
      yystate = *yyssp;                                         \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (ctx, YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)
Definition at line 618 of file settings_parser.c.
#define YYBISON 1
Definition at line 44 of file settings_parser.c.
#define YYBISON_VERSION "3.0.2"
Definition at line 47 of file settings_parser.c.
#define YYCASE_ (N, S)
Value:
case N:                               \
        yyformat = S;                       \
      break
Referenced by yysyntax_error().
#define yyclearin (yychar = YYEMPTY)
Definition at line 607 of file settings_parser.c.
#define YYCOPY (Dst, Src, Count)
Value:
do                                        \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
Definition at line 433 of file settings_parser.c.
#define YYCOPY_NEEDED 1
Definition at line 405 of file settings_parser.c.
#define yydebug settings_parser_debug
Definition at line 66 of file settings_parser.c.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
#define YYDEBUG 1
Definition at line 98 of file settings_parser.c.
#define YYDPRINTF (Args)
Value:
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)
Definition at line 649 of file settings_parser.c.
Referenced by yyparse().
#define YYEMPTY (-2)
Definition at line 608 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
#define YYEOF 0
Definition at line 609 of file settings_parser.c.
Referenced by yyparse().
#define YYERRCODE 256
Definition at line 637 of file settings_parser.c.
#define yyerrok (yyerrstatus = 0)
Definition at line 606 of file settings_parser.c.
#define yyerror settings_parser_error
Definition at line 65 of file settings_parser.c.
Referenced by yyparse().
#define YYERROR goto yyerrorlab
Definition at line 613 of file settings_parser.c.
Referenced by yyparse().
#define YYERROR_VERBOSE 1
Definition at line 149 of file settings_parser.c.
#define YYFINAL 2
Definition at line 446 of file settings_parser.c.
Referenced by yyparse().
#define YYFPRINTF fprintf
Definition at line 646 of file settings_parser.c.
Referenced by yy_reduce_print(), yy_stack_print(), and yy_symbol_print().
#define YYFREE free
Definition at line 376 of file settings_parser.c.
#define YYINITDEPTH 200
Definition at line 774 of file settings_parser.c.
Referenced by yyparse().
#define YYLAST 13
Definition at line 448 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
#define yylex settings_parser_lex
Definition at line 64 of file settings_parser.c.
Referenced by yyparse().
#define YYMALLOC malloc
Definition at line 370 of file settings_parser.c.
#define YYMAXDEPTH 10000
Definition at line 785 of file settings_parser.c.
Referenced by yyparse().
#define YYMAXUTOK 261
Definition at line 462 of file settings_parser.c.
#define yynerrs settings_parser_nerrs
Definition at line 67 of file settings_parser.c.
Referenced by yyparse().
#define YYNNTS 8
Definition at line 453 of file settings_parser.c.
#define YYNRULES 15
Definition at line 455 of file settings_parser.c.
#define YYNSTATES 20
Definition at line 457 of file settings_parser.c.
#define YYNTOKENS 10
Definition at line 451 of file settings_parser.c.
Referenced by yy_symbol_print(), yy_symbol_value_print(), yyparse(), and yysyntax_error().
#define YYPACT_NINF -11
Definition at line 529 of file settings_parser.c.
#define yypact_value_is_default (Yystate) (!!((Yystate) == (-11)))
Definition at line 531 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
#define yyparse settings_parser_parse
Definition at line 63 of file settings_parser.c.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
Referenced by yyparse().
#define YYPULL 1
Definition at line 59 of file settings_parser.c.
#define YYPURE 1
Definition at line 53 of file settings_parser.c.
#define YYPUSH 0
Definition at line 56 of file settings_parser.c.
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 616 of file settings_parser.c.
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 249 of file settings_parser.c.
#define YYSIZE_T size_t
Definition at line 243 of file settings_parser.c.
Referenced by yyparse(), yystrlen(), yysyntax_error(), and yytnamerr().
#define YYSKELETON_NAME "yacc.c"
Definition at line 50 of file settings_parser.c.
#define YYSTACK_ALLOC YYMALLOC
Definition at line 356 of file settings_parser.c.
Referenced by yyparse().
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 359 of file settings_parser.c.
Referenced by yysyntax_error().
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 401 of file settings_parser.c.
Referenced by yyparse().
#define YYSTACK_FREE YYFREE
Definition at line 357 of file settings_parser.c.
Referenced by yyparse().
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 397 of file settings_parser.c.
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)
Definition at line 412 of file settings_parser.c.
Referenced by yyparse().
#define YYSYNTAX_ERROR
Value:
yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
Referenced by yyparse().
#define YYTABLE_NINF -1
Definition at line 534 of file settings_parser.c.
#define yytable_value_is_error (Yytable_value) 0
Definition at line 536 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
#define YYTERROR 1
Definition at line 636 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 464 of file settings_parser.c.
Referenced by yyparse().
#define YYUNDEFTOK 2
Definition at line 461 of file settings_parser.c.
#define YYUSE (E) ((void) (E))
Definition at line 292 of file settings_parser.c.
Referenced by yy_symbol_value_print(), and yydestruct().
Typedef Documentation
typedef short int yytype_int16
Definition at line 233 of file settings_parser.c.
typedef signed char yytype_int8
Definition at line 221 of file settings_parser.c.
typedef unsigned short int yytype_uint16
Definition at line 227 of file settings_parser.c.
typedef unsigned char yytype_uint8
Definition at line 215 of file settings_parser.c.
Function Documentation
static void add_section (parser_helper_t * ctx, section_t * section) static
Adds the given section to the section on top of the stack
Definition at line 1679 of file settings_parser.c.
References array_get(), ARRAY_TAIL, parser_helper_t::context, and settings_section_add().
Referenced by yyparse().
 {
     array_t *sections = (array_t*)ctx->context;
     section_t *parent;
     array_get(sections, ARRAY_TAIL, &parent);
     settings_section_add(parent, section, NULL);
 }
static void add_setting (parser_helper_t * ctx, kv_t * kv) static
Adds the given key/value pair to the section on top of the stack
Definition at line 1691 of file settings_parser.c.
References array_get(), ARRAY_TAIL, parser_helper_t::context, section, and settings_kv_add().
Referenced by yyparse().
 {
     array_t *sections = (array_t*)ctx->context;
     section_t *section;
     array_get(sections, ARRAY_TAIL, &section);
     settings_kv_add(section, kv, NULL);
 }
void free (void *)
Referenced by acert(), add(), add_attr(), add_cdps(), add_device_id(), add_exclude_route(), add_hash(), add_policy_internal(), addr_entry_destroy(), addr_map_destroy(), addr_map_entry_add(), addr_map_entry_remove(), address_enumerator_destroy(), af_alg_crypter_create(), af_alg_hasher_create(), af_alg_ops_create(), af_alg_prf_create(), af_alg_signer_create(), agent_private_key_open(), append_header(), array_create_enumerator(), array_destroy(), asn1_bitstring(), asn1_debug_simple_object(), asn1_integer(), asn1_wrap(), assign_arg(), atodn(), attribute_destroy(), attribute_entry_destroy(), attributes_destroy(), authority_destroy(), barrier_destroy(), bench_aead(), bench_crypter(), bench_hasher(), bench_prf(), bench_rng(), bench_signer(), bliss_private_key_gen(), bliss_public_key_fingerprint(), bridge_create(), build_ac(), build_attributes(), build_auth_cfg(), build_cipher_suite_list(), build_der_signature(), build_emsa_pkcs1_signature(), build_encoding(), burn_aead(), burn_crypter(), burn_signer(), ca_cert_destroy(), ca_section_destroy(), CALLBACK(), callback_data_destroy(), ccm_aead_create(), cdp_data_destroy(), cdp_destroy(), cert_data_destroy(), cert_enumerator_destroy(), cert_payload_create_from_cert(), cert_policy_destroy(), certreq_payload_create_type(), challenge(), check_destroy(), check_list_destroy(), check_policy(), check_policy_constraints(), child_entry_destroy(), chunk_create_cat(), chunk_free(), chunk_from_fd(), chunk_map(), chunk_unmap(), cleanup(), cleanup_sas(), clear_template(), conf_parser_free(), confread_free(), confread_free_ca(), confread_free_conn(), conn_destroy(), connect_(), connected_peers_destroy(), cowfs_create(), cowfs_readdir(), create_cert_ext(), create_ecp(), create_generic(), create_icv(), create_inner_cdp_hashandurl(), create_modp(), create_rdn_enumerator(), create_rt_enumerator(), create_secret(), create_session(), create_vector_from_seed(), crl_uri_destroy(), ctr_ipsec_crypter_create(), curl_fetcher_create(), decrypt(), decrypt_and_unpack(), del_attr(), des_crypter_create(), destroy(), destroy_acquire(), destroy_async_data(), destroy_attr(), destroy_cdp(), destroy_cdp_data(), destroy_cert_data(), destroy_cert_policy(), destroy_cleaner(), destroy_dh_mapping(), destroy_dir_enum(), destroy_dns_pair(), destroy_entry(), destroy_entry_value(), destroy_filter(), destroy_function(), destroy_interim_data(), destroy_internal(), destroy_nested(), destroy_node(), destroy_policy_mapping(), destroy_private_data(), destroy_route(), destroy_service(), destroy_shared_data(), destroy_single(), destroy_suite(), destroy_token_enum(), destroy_trap(), disconnect(), dispatch(), dn(), dnscert_create_frm_rr(), do_args(), do_sasl(), do_write(), dumm_create(), duplicheck_plugin_create(), eap_aka_3gpp2_functions_create(), eap_aka_peer_create(), eap_aka_server_create(), eap_payload_create_data_own(), eap_peap_create(), eap_radius_create(), eap_sim_peer_create(), eap_sim_server_create(), eap_simaka_pseudonym_provider_create(), eap_simaka_reauth_provider_create(), eap_tls_create(), eap_tnc_create(), eap_ttls_create(), edit(), encode(), encrypt(), encrypt_mppe_key(), endecode_create_enumerator(), endpoint_pair_destroy(), entry_destroy(), entry_enumerator_destroy(), enumerator_create_directory(), enumerator_create_empty(), enumerator_destroy(), error_notify_plugin_create(), escape_http_request(), event_destroy(), exclude_route_destroy(), exit_aikgen(), exit_scepclient(), expire_data_destroy(), export(), export_csv(), extend_pcr(), extract_attributes(), farp_spoofer_create(), fast_request_create(), fast_smtp_create(), fetch_cert(), file_metadata(), finalize_transaction(), find_certificates(), find_pubkey_in_certs(), fips_prf_create(), flush_allocated_spis(), fragment_destroy(), free_align(), free_args(), free_attribute(), free_attrs(), free_bios_entry(), free_child_data(), free_client_entry(), free_condition(), free_conditions(), free_entry(), free_env(), free_event_entry(), free_func_comp(), free_hashtable(), free_no_ld(), free_package_entry(), free_peer_data(), gcm_aead_create(), gcrypt_crypter_create(), gcrypt_hasher_create(), gcrypt_rsa_private_key_gen(), gcrypt_rsa_private_key_load(), gcrypt_rsa_public_key_load(), gen(), generate(), generate_encoding(), get_cert_hash(), get_lifetimes(), get_replay_state(), get_route(), get_slot_list(), get_spi_internal(), group_destroy(), guest_create_generic(), half_open_destroy(), handle_attribute(), handle_event(), handle_preferred_eap_types(), handle_response(), has_group(), have_vips_from_pool(), hmac_create(), HOOK(), host_create_any(), host_create_from_range(), host_create_from_sockaddr(), iface_create(), iface_destroy(), iface_entry_destroy(), ike_enumerator_destroy(), ike_sa_manager_create(), imc_imv_msg_create(), imv_attestation_process(), include_files(), init_address_list(), init_supplementary_groups(), initiate_data_destroy(), initiated_destroy(), initiator_destroy(), install_route(), invoke_once(), ipsec_event_destroy(), ipsec_sa_create(), ipsec_sa_destroy(), ipseckey_create_frm_rr(), issue(), iterenv_cb(), iv_data_destroy(), iv_gen_seq_create(), job_data_destroy(), journal_register(), kernel_libipsec_router_create(), key_data_destroy(), keyid(), kw_end(), language_enumerator_destroy(), leak_detective_create(), lib_entry_destroy(), libhydra_deinit(), libipsec_deinit(), library_deinit(), libtnccs_deinit(), list_plugins(), load_authorities_cfg(), load_conns_cfg(), load_dependencies(), load_feature(), load_from_file(), load_from_smartcard(), load_imcvs_from_config(), load_pin(), load_pkcs12(), load_pools(), load_pools_cfg(), load_provided(), load_secrets(), logger_entry_destroy(), login(), main(), mconsole_create(), merge_fragments(), METHOD(), METHOD2(), modular_pluginlist(), mysql_database_create(), mysql_enumerator_destroy(), mysql_enumerator_enumerate(), net_change_destroy(), nm_backend_deinit(), notify_down(), notify_end(), notify_up(), ntru_poly_create_from_seed(), ntru_private_key_create(), ntru_private_key_create_from_data(), offset2host(), on_accept(), openssl_crypter_create(), openssl_diffie_hellman_create(), openssl_ec_diffie_hellman_create(), openssl_ec_fingerprint(), openssl_hasher_create(), openssl_rsa_fingerprint(), openssl_x509_name2id(), overlay_destroy(), package_enumerator_destroy(), padlock_rng_create(), parse_attributes(), parse_authKeyIdentifier_ext(), parse_certificate(), parse_crlDistributionPoints_ext(), parse_crlNumber_ext(), parse_singleResponse(), parse_subjectKeyIdentifier_ext(), parse_token(), parse_uri(), parser_helper_file_destroy(), peer_destroy(), peer_enum_destroy(), peer_enum_filter_destroy(), peer_enumerator_destroy(), pem_encode(), pem_to_bin(), pkcs11_creds_load(), pkcs11_hasher_create(), pkcs11_library_create(), pkcs11_manager_create(), pkcs11_private_key_connect(), pkcs11_rng_create(), pkcs12(), pkcs7(), plugin_entry_destroy(), plugin_priority_free(), policy_entry_destroy(), policy_mapping_destroy(), policy_sa_destroy(), policy_stop(), pool_destroy(), print(), print_ac(), print_all(), print_pem(), print_pem_cert(), print_traces(), print_x509(), printf_hook_create(), process_addr(), process_destroy(), process_eap(), process_ec_key_exchange(), process_init_request(), process_link(), process_modp_key_exchange(), process_packages(), process_peer_failure(), process_peer_success(), process_server_hello(), process_start(), process_start_shell(), pt_tls_server_create(), pts_file_meas_create_from_path(), pub(), qm_data_destroy(), query_destroy(), query_slots(), radius2ike(), read_result(), read_tls(), receive_msg(), receiver_create(), register_pfkey_socket(), rehash(), reinstall_routes(), reinstall_vip(), rekey_children(), remove_connected_peers(), remove_element(), remove_entry(), remove_entry_at(), remove_exclude_route(), remove_from_list(), remove_half_open(), remove_init_hash(), req(), reqid_entry_destroy(), restart(), revoked_destroy(), route_entry_destroy(), rt_entry_destroy(), sad_entry_destroy(), sasl_mechanism_create_enumerator(), save_state(), scep_build_request(), scep_generate_transaction_id(), scep_http_request(), schedule(), schedule_expiration(), section_destroy(), select_method(), self(), send_certificate(), send_interim(), send_key_exchange_dhe(), send_key_exchange_encrypt(), send_request(), send_server_key_exchange(), send_stroke_msg(), session_entry_destroy(), setting_destroy(), settings_kv_destroy(), settings_kv_set(), settings_parser_free(), settings_section_destroy(), shared_data_destroy(), shared_entry_destroy(), show(), sign(), sign_bliss(), sign_crl(), signal_handler(), signature_schemes_for_key(), signerinfo_destroy(), smp_plugin_create(), soap_init(), socket_dynamic_socket_create(), sp_entry_destroy(), sqlite_enumerator_destroy(), START_TEST(), storage_create(), stroke_list_acerts(), test_good_sig(), test_tls(), thread_cleanup(), thread_cleanup_pop(), thread_cleanup_popall(), thread_destroy(), thread_tls_cleanup(), threading_cleanup(), tkm_deinit(), tkm_diffie_hellman_create(), tkm_keymat_create(), tkm_spi_generator_register(), tls_aead_create_aead(), tls_aead_create_null(), tls_prf_create_12(), tls_socket_create(), traffic_selector_create_from_bytes(), traffic_selector_create_from_rfc3779_format(), traffic_selector_create_from_string(), traffic_selector_create_from_subnet(), transaction_destroy(), triplet_destroy(), uncache_iface(), uninstall_route(), unregister_feature(), unregister_listener(), unregister_logger(), unwrap_ec_point(), update_database(), vadd_kv_or_li(), vendor_entry_destroy(), verify(), verify_bliss(), verify_der_signature(), verify_emsa_pkcs1_signature(), verify_rng(), vici_disconnect(), vici_free_req(), vici_free_res(), vici_register(), vici_submit(), watch(), whitelist_control_create(), winhttp_fetcher_create(), wrapper_enumerator_destroy(), write_ec_identifier(), write_sasl(), xml_create(), yydestruct(), and yyparse().
void* malloc (YYSIZE_T)
Referenced by array_create(), asn1_build_object(), auth_conv(), backtrace_create(), bliss_private_key_gen(), bliss_private_key_load(), bliss_public_key_from_asn1(), bliss_signature_create(), bliss_signature_create_from_data(), build_cipher_suite_list(), build_emsa_pkcs1_signature(), build_encoding(), chunk_from_base64(), chunk_from_fd(), chunk_from_hex(), chunk_split(), chunk_to_base32(), chunk_to_base64(), chunk_to_hex(), cmac_create(), conf_parser_alloc(), create_inner_cdp_hashandurl(), create_vector_from_seed(), escape_http_request(), find_certificates(), fips_prf_create(), generate_encoding(), generator_create(), get_attributes(), get_replay_state(), get_slot_list(), get_strerror_buf(), gmp_rsa_private_key_gen(), gmp_rsa_private_key_load(), ha_message_create(), handle_event(), hmac_create(), HOOK(), iv_gen_seq_create(), loaded_plugins_list(), main(), malloc_align(), METHOD(), mysql_enumerator_enumerate(), ntru_poly_create(), ntru_poly_create_from_seed(), ntru_private_key_create(), ntru_private_key_create_from_data(), ntru_public_key_create(), ntru_public_key_create_from_data(), ntru_trits_create(), on_accept(), openssl_bn_cat(), pem_encode(), pfkey_send_socket(), process_peer_failure(), process_peer_success(), pts_ima_event_list_create(), queue(), radius_message_parse(), read_tls(), save_state(), scep_http_request(), settings_parser_alloc(), sign_bliss(), simaka_message_create_data(), START_TEST(), strdup_windows(), strndup(), strreplace(), threading_init(), tnccs_reason_strings_msg_create(), ts2condition(), verify_bliss(), verify_emsa_pkcs1_signature(), vstr_wrapper_vasprintf(), and xcbc_create().
static section_t * pop_section (parser_helper_t * ctx) static
Removes the top section of the stack and returns it
Definition at line 1667 of file settings_parser.c.
References array_remove(), ARRAY_TAIL, parser_helper_t::context, and section.
Referenced by yydestruct(), and yyparse().
 {
     array_t *sections = (array_t*)ctx->context;
     section_t *section;
     array_remove(sections, ARRAY_TAIL, &section);
     return section;
 }
static section_t * push_section (parser_helper_t * ctx, char * name) static
Create a section and push it to the stack (the name is adopted), returns the created section
Definition at line 1654 of file settings_parser.c.
References array_insert(), ARRAY_TAIL, parser_helper_t::context, section, and settings_section_create().
Referenced by yyparse().
 {
     array_t *sections = (array_t*)ctx->context;
     section_t *section;
     section = settings_section_create(name);
     array_insert(sections, ARRAY_TAIL, section);
     return section;
 }
static void settings_parser_error (parser_helper_t * ctx, const char * s) static
Forward declarations
Referenced by the generated parser
Definition at line 1638 of file settings_parser.c.
References len, PARSER_DBG1, parser_helper_t::scanner, settings_parser_get_leng(), and settings_parser_get_text().
 {
     char *text = settings_parser_get_text(ctx->scanner);
     int len = settings_parser_get_leng(ctx->scanner);
     if (len && text[len-1] == '\n')
     {   /* cut off newline at the end to avoid muti-line log messages */
         len--;
     }
     PARSER_DBG1(ctx, "%s [%.*s]", s, len, text);
 }
int settings_parser_get_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters
yyscanner The scanner object.
Definition at line 2339 of file settings_lexer.c.
References yyleng.
Referenced by settings_parser_error().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyleng;
 }
int settings_parser_get_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters
yyscanner The scanner object.
Definition at line 2295 of file settings_lexer.c.
References YY_CURRENT_BUFFER, and yylineno.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         if (! YY_CURRENT_BUFFER)
             return 0;
     return yylineno;
 }
char* settings_parser_get_text (yyscan_t yyscanner)
Get the current token.
Parameters
yyscanner The scanner object.
Definition at line 2349 of file settings_lexer.c.
References yytext.
Referenced by settings_parser_error().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yytext;
 }
int settings_parser_lex (YYSTYPE * lvalp, void * scanner)
Defined by the lexer
Referenced by yylex().
int settings_parser_lex_destroy (void * scanner)
Definition at line 2553 of file settings_lexer.c.
References settings_parser__delete_buffer(), settings_parser_free(), settings_parser_pop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     /* Pop the buffer stack, destroying each element. */
     while(YY_CURRENT_BUFFER){
         settings_parser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
         YY_CURRENT_BUFFER_LVALUE = NULL;
         settings_parser_pop_buffer_state(yyscanner);
     }
     /* Destroy the stack itself. */
     settings_parser_free(yyg->yy_buffer_stack ,yyscanner);
     yyg->yy_buffer_stack = NULL;
     /* Destroy the start condition stack. */
         settings_parser_free(yyg->yy_start_stack ,yyscanner );
         yyg->yy_start_stack = NULL;
     /* Reset the globals. This is important in a non-reentrant scanner so the next time
      * settings_parser_lex() is called, initialization will occur. */
     yy_init_globals( yyscanner);
 /* %if-reentrant */
     /* Destroy the main struct (reentrant only). */
     settings_parser_free ( yyscanner , yyscanner );
     yyscanner = NULL;
 /* %endif */
     return 0;
 }
int settings_parser_lex_init_extra (parser_helper_t * extra, void * scanner)
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
bool settings_parser_load_string (parser_helper_t * ctx, const char * content)
Load the given string to be parsed next
Definition at line 2679 of file settings_lexer.c.
References parser_helper_t::scanner, and settings_parser__scan_string().
Referenced by settings_parser_parse_string().
 {
     settings_parser__scan_string(content, ctx->scanner);
 }
bool settings_parser_open_next_file (parser_helper_t * ctx)
Open the next file, if any is queued and readable, otherwise returns FALSE.
Definition at line 2645 of file settings_lexer.c.
References FALSE, parser_helper_t::file_next, parser_helper_t::scanner, settings_parser__create_buffer(), settings_parser_push_buffer_state(), settings_parser_set_in(), TRUE, and YY_BUF_SIZE.
Referenced by include_files(), settings_parser_parse_file(), and while().
 {
     FILE *file;
     file = ctx->file_next(ctx);
     if (!file)
     {
         return FALSE;
     }
     settings_parser_set_in(file, ctx->scanner);
     settings_parser_push_buffer_state(
             settings_parser__create_buffer(file, YY_BUF_SIZE,
                                            ctx->scanner), ctx->scanner);
     return TRUE;
 }
int settings_parser_parse (parser_helper_t * ctx)
bool settings_parser_parse_file (section_t * root, char * name)
Parse the given file and add all sections and key/value pairs to the given section.
Definition at line 1704 of file settings_parser.c.
References array_destroy(), array_insert_create(), ARRAY_TAIL, library_t::conf, DBG1, DBG2, DBG_CFG, parser_helper_t::destroy, FALSE, parser_helper_t::file_include, parser_helper_t::get_lineno, lib, parser_helper_create(), parser_helper_t::scanner, settings_parser_get_lineno(), settings_parser_lex_destroy(), settings_parser_lex_init_extra(), settings_parser_open_next_file(), settings_parser_set_debug(), streq(), yydebug, and yyparse.
Referenced by load_internal().
 {
     parser_helper_t *helper;
     array_t *sections = NULL;
     bool success = FALSE;
     array_insert_create(&sections, ARRAY_TAIL, root);
     helper = parser_helper_create(sections);
     helper->get_lineno = settings_parser_get_lineno;
     if (settings_parser_lex_init_extra(helper, &helper->scanner) != 0)
     {
         helper->destroy(helper);
         array_destroy(sections);
         return FALSE;
     }
     helper->file_include(helper, name);
     if (!settings_parser_open_next_file(helper))
     {
         if (lib->conf && streq(name, lib->conf))
         {
             DBG2(DBG_CFG, "failed to open config file '%s'", name);
         }
         else
         {
             DBG1(DBG_CFG, "failed to open config file '%s'", name);
         }
     }
     else
     {
         if (getenv("DEBUG_SETTINGS_PARSER"))
         {
             yydebug = 1;
             settings_parser_set_debug(1, helper->scanner);
         }
         success = yyparse(helper) == 0;
         if (!success)
         {
             DBG1(DBG_CFG, "invalid config file '%s'", name);
         }
     }
     array_destroy(sections);
     settings_parser_lex_destroy(helper->scanner);
     helper->destroy(helper);
     return success;
 }
bool settings_parser_parse_string (section_t * root, char * settings)
Parse the given string and add all sections and key/value pairs to the given section.
Definition at line 1754 of file settings_parser.c.
References array_destroy(), array_insert_create(), ARRAY_TAIL, DBG1, DBG_CFG, parser_helper_t::destroy, FALSE, parser_helper_t::get_lineno, parser_helper_create(), parser_helper_t::scanner, settings_parser_get_lineno(), settings_parser_lex_destroy(), settings_parser_lex_init_extra(), settings_parser_load_string(), settings_parser_set_debug(), yydebug, and yyparse.
Referenced by load_internal().
 {
     parser_helper_t *helper;
     array_t *sections = NULL;
     bool success = FALSE;
     array_insert_create(&sections, ARRAY_TAIL, root);
     helper = parser_helper_create(sections);
     helper->get_lineno = settings_parser_get_lineno;
     if (settings_parser_lex_init_extra(helper, &helper->scanner) != 0)
     {
         helper->destroy(helper);
         array_destroy(sections);
         return FALSE;
     }
     settings_parser_load_string(helper, settings);
     if (getenv("DEBUG_SETTINGS_PARSER"))
     {
         yydebug = 1;
         settings_parser_set_debug(1, helper->scanner);
     }
     success = yyparse(helper) == 0;
     if (!success)
     {
         DBG1(DBG_CFG, "failed to parse settings '%s'", settings);
     }
     array_destroy(sections);
     settings_parser_lex_destroy(helper->scanner);
     helper->destroy(helper);
     return success;
 }
void settings_parser_set_debug (int debug, void * scanner)
Definition at line 2423 of file settings_lexer.c.
References yy_flex_debug.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yy_flex_debug = bdebug ;
 }
int settings_parser_set_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream. This does not discard the current input buffer.
Parameters
in_str A readable stream.
yyscanner The scanner object.
See Also
settings_parser__switch_to_buffer
Definition at line 2405 of file settings_lexer.c.
References yyin.
Referenced by settings_parser_open_next_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyin = in_str ;
 }
static void yy_reduce_print (yytype_int16 * yyssp, YYSTYPE * yyvsp, int yyrule, parser_helper_t * ctx) static
Definition at line 736 of file settings_parser.c.
References yy_symbol_print(), YYFPRINTF, yyr2, yyrline, and yystos.
 {
   unsigned long int yylno = yyrline[yyrule];
   int yynrhs = yyr2[yyrule];
   int yyi;
   YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
              yyrule - 1, yylno);
   /* The symbols being reduced.  */
   for (yyi = 0; yyi < yynrhs; yyi++)
     {
       YYFPRINTF (stderr, "   $%d = ", yyi + 1);
       yy_symbol_print (stderr,
                        yystos[yyssp[yyi + 1 - yynrhs]],
                        &(yyvsp[(yyi + 1) - (yynrhs)])
                                               , ctx);
       YYFPRINTF (stderr, "\n");
     }
 }
static void yy_stack_print (yytype_int16 * yybottom, yytype_int16 * yytop) static
Definition at line 713 of file settings_parser.c.
References YYFPRINTF.
 {
   YYFPRINTF (stderr, "Stack now");
   for (; yybottom <= yytop; yybottom++)
     {
       int yybot = *yybottom;
       YYFPRINTF (stderr, " %d", yybot);
     }
   YYFPRINTF (stderr, "\n");
 }
static void yy_symbol_print (FILE * yyoutput, int yytype, YYSTYPE const *const yyvaluep, parser_helper_t * ctx) static
Definition at line 698 of file settings_parser.c.
References yy_symbol_value_print(), YYFPRINTF, YYNTOKENS, and yytname.
Referenced by yy_reduce_print().
 {
   YYFPRINTF (yyoutput, "%s %s (",
              yytype < YYNTOKENS ? "token" : "nterm", yytname[yytype]);
   yy_symbol_value_print (yyoutput, yytype, yyvaluep, ctx);
   YYFPRINTF (yyoutput, ")");
 }
static void yy_symbol_value_print (FILE * yyoutput, int yytype, YYSTYPE const *const yyvaluep, parser_helper_t * ctx) static
Definition at line 678 of file settings_parser.c.
References YYNTOKENS, and YYUSE.
Referenced by yy_symbol_print().
 {
   FILE *yyo = yyoutput;
   YYUSE (yyo);
   YYUSE (ctx);
   if (!yyvaluep)
     return;
 # ifdef YYPRINT
   if (yytype < YYNTOKENS)
     YYPRINT (yyoutput, yytoknum[yytype], *yyvaluep);
 # endif
   YYUSE (yytype);
 }
static void yydestruct (const char * yymsg, int yytype, YYSTYPE * yyvaluep, parser_helper_t * ctx) static
Definition at line 1016 of file settings_parser.c.
References free(), pop_section(), settings_kv_destroy(), settings_section_destroy(), YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_SYMBOL_PRINT, and YYUSE.
Referenced by yyparse().
 {
   YYUSE (yyvaluep);
   YYUSE (ctx);
   if (!yymsg)
     yymsg = "Deleting";
   YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   switch (yytype)
     {
           case 3: /* NAME  */
 #line 91 "settings/settings_parser.y" /* yacc.c:1257  */
       { free(((*yyvaluep).s)); }
 #line 1031 "settings/settings_parser.c" /* yacc.c:1257  */
         break;
     case 4: /* STRING  */
 #line 91 "settings/settings_parser.y" /* yacc.c:1257  */
       { free(((*yyvaluep).s)); }
 #line 1037 "settings/settings_parser.c" /* yacc.c:1257  */
         break;
     case 13: /* section  */
 #line 93 "settings/settings_parser.y" /* yacc.c:1257  */
       { pop_section(ctx); settings_section_destroy(((*yyvaluep).sec), NULL); }
 #line 1043 "settings/settings_parser.c" /* yacc.c:1257  */
         break;
     case 14: /* section_start  */
 #line 93 "settings/settings_parser.y" /* yacc.c:1257  */
       { pop_section(ctx); settings_section_destroy(((*yyvaluep).sec), NULL); }
 #line 1049 "settings/settings_parser.c" /* yacc.c:1257  */
         break;
     case 15: /* setting  */
 #line 94 "settings/settings_parser.y" /* yacc.c:1257  */
       { settings_kv_destroy(((*yyvaluep).kv), NULL); }
 #line 1055 "settings/settings_parser.c" /* yacc.c:1257  */
         break;
     case 16: /* value  */
 #line 91 "settings/settings_parser.y" /* yacc.c:1257  */
       { free(((*yyvaluep).s)); }
 #line 1061 "settings/settings_parser.c" /* yacc.c:1257  */
         break;
     case 17: /* valuepart  */
 #line 91 "settings/settings_parser.y" /* yacc.c:1257  */
       { free(((*yyvaluep).s)); }
 #line 1067 "settings/settings_parser.c" /* yacc.c:1257  */
         break;
       default:
         break;
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_END
 }
static int yylex (YYSTYPE * lvalp, parser_helper_t * ctx) static
Make sure to call lexer with the proper context
Definition at line 128 of file settings_parser.c.
References parser_helper_t::scanner, and settings_parser_lex().
 {
     return settings_parser_lex(lvalp, ctx->scanner);
 }
int yyparse (parser_helper_t * ctx)
Definition at line 1084 of file settings_parser.c.
References add_section(), add_setting(), asprintf(), free(), YYSTYPE::kv, pop_section(), push_section(), YYSTYPE::s, s, YYSTYPE::sec, settings_kv_create(), YY_, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_INITIAL_VALUE, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYERROR, YYFINAL, YYINITDEPTH, YYLAST, yylex, yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact, yypact_value_is_default, yypgoto, YYPOPSTACK, yyr1, yyr2, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystos, YYSYNTAX_ERROR, yytable, yytable_value_is_error, YYTERROR, YYTRANSLATE, and yyalloc::yyvs_alloc.
 {
 /* The lookahead symbol.  */
 int yychar;
 /* The semantic value of the lookahead symbol.  */
 /* Default value used for initialization, for pacifying older GCCs
    or non-GCC compilers.  */
 YY_INITIAL_VALUE (static YYSTYPE yyval_default;)
 YYSTYPE yylval YY_INITIAL_VALUE (= yyval_default);
     /* Number of syntax errors so far.  */
     int yynerrs;
     int yystate;
     /* Number of tokens to shift before error messages enabled.  */
     int yyerrstatus;
     /* The stacks and their tools:
        'yyss': related to states.
        'yyvs': related to semantic values.
        Refer to the stacks through separate pointers, to allow yyoverflow
        to reallocate them elsewhere.  */
     /* The state stack.  */
     yytype_int16 yyssa[YYINITDEPTH];
     yytype_int16 *yyss;
     yytype_int16 *yyssp;
     /* The semantic value stack.  */
     YYSTYPE yyvsa[YYINITDEPTH];
     YYSTYPE *yyvs;
     YYSTYPE *yyvsp;
     YYSIZE_T yystacksize;
   int yyn;
   int yyresult;
   /* Lookahead token as an internal (translated) token number.  */
   int yytoken = 0;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
 #if YYERROR_VERBOSE
   /* Buffer for error messages, and its allocated size.  */
   char yymsgbuf[128];
   char *yymsg = yymsgbuf;
   YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
 #endif
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   yyssp = yyss = yyssa;
   yyvsp = yyvs = yyvsa;
   yystacksize = YYINITDEPTH;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY; /* Cause a token to be read.  */
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- Push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
  yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
  yysetstate:
   *yyssp = yystate;
   if (yyss + yystacksize - 1 <= yyssp)
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = yyssp - yyss + 1;
 #ifdef yyoverflow
       {
         /* Give user a chance to reallocate the stack.  Use copies of
            these so that the &'s don't force the real ones into
            memory.  */
         YYSTYPE *yyvs1 = yyvs;
         yytype_int16 *yyss1 = yyss;
         /* Each stack pointer address is followed by the size of the
            data in use in that stack, in bytes.  This used to be a
            conditional around just the two extra args, but that might
            be undefined if yyoverflow is a macro.  */
         yyoverflow (YY_("memory exhausted"),
                     &yyss1, yysize * sizeof (*yyssp),
                     &yyvs1, yysize * sizeof (*yyvsp),
                     &yystacksize);
         yyss = yyss1;
         yyvs = yyvs1;
       }
 #else /* no yyoverflow */
 # ifndef YYSTACK_RELOCATE
       goto yyexhaustedlab;
 # else
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
         goto yyexhaustedlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
         yystacksize = YYMAXDEPTH;
       {
         yytype_int16 *yyss1 = yyss;
         union yyalloc *yyptr =
           (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
         if (! yyptr)
           goto yyexhaustedlab;
         YYSTACK_RELOCATE (yyss_alloc, yyss);
         YYSTACK_RELOCATE (yyvs_alloc, yyvs);
 #  undef YYSTACK_RELOCATE
         if (yyss1 != yyssa)
           YYSTACK_FREE (yyss1);
       }
 # endif
 #endif /* no yyoverflow */
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                   (unsigned long int) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
         YYABORT;
     }
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yypact_value_is_default (yyn))
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token: "));
       yychar = yylex (&yylval, ctx);
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yytable_value_is_error (yyn))
         goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   yystate = yyn;
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- Do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      '$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
         case 5:
 #line 113 "settings/settings_parser.y" /* yacc.c:1646  */
     {
         add_section(ctx, (yyvsp[0].sec));
     }
 #line 1337 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
   case 6:
 #line 117 "settings/settings_parser.y" /* yacc.c:1646  */
     {
         add_setting(ctx, (yyvsp[0].kv));
     }
 #line 1345 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
   case 7:
 #line 124 "settings/settings_parser.y" /* yacc.c:1646  */
     {
         pop_section(ctx);
         (yyval.sec) = (yyvsp[-2].sec);
     }
 #line 1354 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
   case 8:
 #line 132 "settings/settings_parser.y" /* yacc.c:1646  */
     {
         (yyval.sec) = push_section(ctx, (yyvsp[-1].s));
     }
 #line 1362 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
   case 9:
 #line 137 "settings/settings_parser.y" /* yacc.c:1646  */
     {
         (yyval.sec) = push_section(ctx, (yyvsp[-2].s));
     }
 #line 1370 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
   case 10:
 #line 144 "settings/settings_parser.y" /* yacc.c:1646  */
     {
         (yyval.kv) = settings_kv_create((yyvsp[-2].s), (yyvsp[0].s));
     }
 #line 1378 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
   case 11:
 #line 149 "settings/settings_parser.y" /* yacc.c:1646  */
     {
         (yyval.kv) = settings_kv_create((yyvsp[-1].s), NULL);
     }
 #line 1386 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
   case 13:
 #line 157 "settings/settings_parser.y" /* yacc.c:1646  */
     {   /* just put a single space between them, use strings for more */
         if (asprintf(&(yyval.s), "%s %s", (yyvsp[-1].s), (yyvsp[0].s)) < 0)
         {
             free((yyvsp[-1].s));
             free((yyvsp[0].s));
             YYERROR;
         }
         free((yyvsp[-1].s));
         free((yyvsp[0].s));
     }
 #line 1401 "settings/settings_parser.c" /* yacc.c:1646  */
     break;
 #line 1405 "settings/settings_parser.c" /* yacc.c:1646  */
       default: break;
     }
   /* User semantic actions sometimes alter yychar, and that requires
      that yytoken be updated with the new translation.  We take the
      approach of translating immediately before every use of yytoken.
      One alternative is translating here after every semantic action,
      but that translation would be missed if the semantic action invokes
      YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
      if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
      incorrect destructor might then be invoked immediately.  In the
      case of YYERROR or YYBACKUP, subsequent parser actions might lead
      to an incorrect destructor call or verbose syntax error message
      before the lookahead is translated.  */
   YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   *++yyvsp = yyval;
   /* Now 'shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   yyn = yyr1[yyn];
   yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
   if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
     yystate = yytable[yystate];
   else
     yystate = yydefgoto[yyn - YYNTOKENS];
   goto yynewstate;
 /*--------------------------------------.
 | yyerrlab -- here on detecting error.  |
 `--------------------------------------*/
 yyerrlab:
   /* Make sure we have latest lookahead translation.  See comments at
      user semantic actions for why this is necessary.  */
   yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if ! YYERROR_VERBOSE
       yyerror (ctx, YY_("syntax error"));
 #else
 # define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                         yyssp, yytoken)
       {
         char const *yymsgp = YY_("syntax error");
         int yysyntax_error_status;
         yysyntax_error_status = YYSYNTAX_ERROR;
         if (yysyntax_error_status == 0)
           yymsgp = yymsg;
         else if (yysyntax_error_status == 1)
           {
             if (yymsg != yymsgbuf)
               YYSTACK_FREE (yymsg);
             yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
             if (!yymsg)
               {
                 yymsg = yymsgbuf;
                 yymsg_alloc = sizeof yymsgbuf;
                 yysyntax_error_status = 2;
               }
             else
               {
                 yysyntax_error_status = YYSYNTAX_ERROR;
                 yymsgp = yymsg;
               }
           }
         yyerror (ctx, yymsgp);
         if (yysyntax_error_status == 2)
           goto yyexhaustedlab;
       }
 # undef YYSYNTAX_ERROR
 #endif
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
          error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* Return failure if at end of input.  */
           if (yychar == YYEOF)
             YYABORT;
         }
       else
         {
           yydestruct ("Error: discarding",
                       yytoken, &yylval, ctx);
           yychar = YYEMPTY;
         }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers like GCC when the user code never invokes
      YYERROR and the label yyerrorlab therefore never appears in user
      code.  */
   if (/*CONSTCOND*/ 0)
      goto yyerrorlab;
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYERROR.  */
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;      /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (!yypact_value_is_default (yyn))
         {
           yyn += YYTERROR;
           if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
             {
               yyn = yytable[yyn];
               if (0 < yyn)
                 break;
             }
         }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
         YYABORT;
       yydestruct ("Error: popping",
                   yystos[yystate], yyvsp, ctx);
       YYPOPSTACK (1);
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Shift the error token.  */
   YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturn;
 #if !defined yyoverflow || YYERROR_VERBOSE
 /*-------------------------------------------------.
 | yyexhaustedlab -- memory exhaustion comes here.  |
 `-------------------------------------------------*/
 yyexhaustedlab:
   yyerror (ctx, YY_("memory exhausted"));
   yyresult = 2;
   /* Fall through.  */
 #endif
 yyreturn:
   if (yychar != YYEMPTY)
     {
       /* Make sure we have latest lookahead translation.  See comments at
          user semantic actions for why this is necessary.  */
       yytoken = YYTRANSLATE (yychar);
       yydestruct ("Cleanup: discarding lookahead",
                   yytoken, &yylval, ctx);
     }
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK (yylen);
   YY_STACK_PRINT (yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct ("Cleanup: popping",
                   yystos[*yyssp], yyvsp, ctx);
       YYPOPSTACK (1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
 #if YYERROR_VERBOSE
   if (yymsg != yymsgbuf)
     YYSTACK_FREE (yymsg);
 #endif
   return yyresult;
 }
static char* yystpcpy (char * yydest, const char * yysrc) static
Definition at line 814 of file settings_parser.c.
Referenced by yytnamerr().
 {
   char *yyd = yydest;
   const char *yys = yysrc;
   while ((*yyd++ = *yys++) != '\0')
     continue;
   return yyd - 1;
 }
static YYSIZE_T yystrlen (const char * yystr) static
Definition at line 797 of file settings_parser.c.
References YYSIZE_T.
Referenced by yysyntax_error(), and yytnamerr().
 {
   YYSIZE_T yylen;
   for (yylen = 0; yystr[yylen]; yylen++)
     continue;
   return yylen;
 }
static int yysyntax_error (YYSIZE_T * yymsg_alloc, char ** yymsg, yytype_int16 * yyssp, int yytoken) static
Definition at line 884 of file settings_parser.c.
References YY_, YY_NULLPTR, YYCASE_, yycheck, YYEMPTY, YYLAST, YYNTOKENS, yypact, yypact_value_is_default, YYSIZE_T, YYSTACK_ALLOC_MAXIMUM, yystrlen(), yytable, yytable_value_is_error, YYTERROR, yytname, and yytnamerr().
 {
   YYSIZE_T yysize0 = yytnamerr (YY_NULLPTR, yytname[yytoken]);
   YYSIZE_T yysize = yysize0;
   enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
   /* Internationalized format string. */
   const char *yyformat = YY_NULLPTR;
   /* Arguments of yyformat. */
   char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
   /* Number of reported tokens (one for the "unexpected", one per
      "expected"). */
   int yycount = 0;
   /* There are many possibilities here to consider:
      - If this state is a consistent state with a default action, then
        the only way this function was invoked is if the default action
        is an error action.  In that case, don't check for expected
        tokens because there are none.
      - The only way there can be no lookahead present (in yychar) is if
        this state is a consistent state with a default action.  Thus,
        detecting the absence of a lookahead is sufficient to determine
        that there is no unexpected or expected token to report.  In that
        case, just report a simple "syntax error".
      - Don't assume there isn't a lookahead just because this state is a
        consistent state with a default action.  There might have been a
        previous inconsistent state, consistent state with a non-default
        action, or user semantic action that manipulated yychar.
      - Of course, the expected token list depends on states to have
        correct lookahead information, and it depends on the parser not
        to perform extra reductions after fetching a lookahead from the
        scanner and before detecting a syntax error.  Thus, state merging
        (from LALR or IELR) and default reductions corrupt the expected
        token list.  However, the list is correct for canonical LR with
        one exception: it will still contain any token that will not be
        accepted due to an error action in a later state.
   */
   if (yytoken != YYEMPTY)
     {
       int yyn = yypact[*yyssp];
       yyarg[yycount++] = yytname[yytoken];
       if (!yypact_value_is_default (yyn))
         {
           /* Start YYX at -YYN if negative to avoid negative indexes in
              YYCHECK.  In other words, skip the first -YYN actions for
              this state because they are default actions.  */
           int yyxbegin = yyn < 0 ? -yyn : 0;
           /* Stay within bounds of both yycheck and yytname.  */
           int yychecklim = YYLAST - yyn + 1;
           int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
           int yyx;
           for (yyx = yyxbegin; yyx < yyxend; ++yyx)
             if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR
                 && !yytable_value_is_error (yytable[yyx + yyn]))
               {
                 if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                   {
                     yycount = 1;
                     yysize = yysize0;
                     break;
                   }
                 yyarg[yycount++] = yytname[yyx];
                 {
                   YYSIZE_T yysize1 = yysize + yytnamerr (YY_NULLPTR, yytname[yyx]);
                   if (! (yysize <= yysize1
                          && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
                     return 2;
                   yysize = yysize1;
                 }
               }
         }
     }
   switch (yycount)
     {
 # define YYCASE_(N, S)                      \
       case N:                               \
         yyformat = S;                       \
       break
       YYCASE_(0, YY_("syntax error"));
       YYCASE_(1, YY_("syntax error, unexpected %s"));
       YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
       YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
       YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
       YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
 # undef YYCASE_
     }
   {
     YYSIZE_T yysize1 = yysize + yystrlen (yyformat);
     if (! (yysize <= yysize1 && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
       return 2;
     yysize = yysize1;
   }
   if (*yymsg_alloc < yysize)
     {
       *yymsg_alloc = 2 * yysize;
       if (! (yysize <= *yymsg_alloc
              && *yymsg_alloc <= YYSTACK_ALLOC_MAXIMUM))
         *yymsg_alloc = YYSTACK_ALLOC_MAXIMUM;
       return 1;
     }
   /* Avoid sprintf, as that infringes on the user's name space.
      Don't have undefined behavior even if the translation
      produced a string with the wrong number of "%s"s.  */
   {
     char *yyp = *yymsg;
     int yyi = 0;
     while ((*yyp = *yyformat) != '\0')
       if (*yyp == '%' && yyformat[1] == 's' && yyi < yycount)
         {
           yyp += yytnamerr (yyp, yyarg[yyi++]);
           yyformat += 2;
         }
       else
         {
           yyp++;
           yyformat++;
         }
   }
   return 0;
 }
static YYSIZE_T yytnamerr (char * yyres, const char * yystr) static
Definition at line 836 of file settings_parser.c.
References YYSIZE_T, yystpcpy(), and yystrlen().
Referenced by yysyntax_error().
 {
   if (*yystr == '"')
     {
       YYSIZE_T yyn = 0;
       char const *yyp = yystr;
       for (;;)
         switch (*++yyp)
           {
           case '\'':
           case ',':
             goto do_not_strip_quotes;
           case '\\':
             if (*++yyp != '\\')
               goto do_not_strip_quotes;
             /* Fall through.  */
           default:
             if (yyres)
               yyres[yyn] = *yyp;
             yyn++;
             break;
           case '"':
             if (yyres)
               yyres[yyn] = '\0';
             return yyn;
           }
     do_not_strip_quotes: ;
     }
   if (! yyres)
     return yystrlen (yystr);
   return yystpcpy (yyres, yystr) - yyres;
 }
Variable Documentation
int settings_parser_debug
const yytype_uint8 yycheck[] static
Initial value:
=
{
       0,     3,     4,     3,     5,     5,    16,     8,     9,     3,
       8,     5,     7,     7
}
Definition at line 577 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
int yydebug
Definition at line 763 of file settings_parser.c.
const yytype_uint8 yydefact[] static
Initial value:
=
{
       2,     0,     1,     0,     3,     4,     5,     2,     6,     0,
       8,    11,     0,     9,    14,    15,    10,    12,     7,    13
}
Definition at line 550 of file settings_parser.c.
Referenced by yyparse().
const yytype_int8 yydefgoto[] static
Initial value:
=
{
      -1,     1,     5,     6,     7,     8,    16,    17
}
Definition at line 563 of file settings_parser.c.
Referenced by yyparse().
const yytype_int8 yypact[] static
Initial value:
=
{
     -11,     0,   -11,    -1,   -11,   -11,   -11,   -11,   -11,     2,
     -11,    -2,     6,   -11,   -11,   -11,    -2,   -11,   -11,   -11
}
Definition at line 541 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
const yytype_int8 yypgoto[] static
Initial value:
=
{
     -11,     5,   -11,   -11,   -11,   -11,   -11,   -10
}
Definition at line 557 of file settings_parser.c.
Referenced by yyparse().
const yytype_uint8 yyr1[] static
Initial value:
=
{
       0,    10,    11,    11,    11,    12,    12,    13,    14,    14,
      15,    15,    16,    16,    17,    17
}
Definition at line 592 of file settings_parser.c.
Referenced by yyparse().
const yytype_uint8 yyr2[] static
Initial value:
=
{
       0,     2,     0,     2,     2,     1,     1,     3,     2,     3,
       3,     2,     1,     2,     1,     1
}
Definition at line 599 of file settings_parser.c.
Referenced by yy_reduce_print(), and yyparse().
const yytype_uint8 yyrline[] static
Initial value:
=
{
       0,   105,   105,   107,   108,   112,   116,   123,   131,   136,
     143,   148,   155,   156,   170,   171
}
Definition at line 502 of file settings_parser.c.
Referenced by yy_reduce_print().
const yytype_uint8 yystos[] static
Initial value:
=
{
       0,    11,     0,     3,     5,    12,    13,    14,    15,     5,
       8,     9,    11,     8,     3,     4,    16,    17,     7,    17
}
Definition at line 585 of file settings_parser.c.
Referenced by yy_reduce_print(), and yyparse().
const yytype_uint8 yytable[] static
Initial value:
=
{
       2,    14,    15,     3,     9,     4,    19,    10,    11,     3,
      13,     4,    12,    18
}
Definition at line 571 of file settings_parser.c.
Referenced by yyparse(), and yysyntax_error().
const char* const yytname[] static
Initial value:
=
{
  "$end", "error", "$undefined", "NAME", "STRING", "NEWLINE",
  "STRING_ERROR", "'}'", "'{'", "'='", "$accept", "statements",
  "statement", "section", "section_start", "setting", "value", "valuepart", YY_NULLPTR
}
Definition at line 512 of file settings_parser.c.
Referenced by yy_symbol_print(), and yysyntax_error().
const yytype_uint8 yytranslate[] static
Initial value:
=
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     9,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     8,     2,     7,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6
}
Definition at line 469 of file settings_parser.c.