strongSwan: fast_request_t Struct Reference
fast_request_t Struct Reference
fast_request
#include "fast_request.h"
Public Attributes
void(* add_cookie)(fast_request_t *this, char *name, char *value)
char *(* get_cookie)(fast_request_t *this, char *name)
char *(* get_path)(fast_request_t *this)
char *(* get_base)(fast_request_t *this)
char *(* get_host)(fast_request_t *this)
char *(* get_user_agent)(fast_request_t *this)
char *(* get_query_data)(fast_request_t *this, char *name)
char *(* get_env_var)(fast_request_t *this, char *name)
int(* read_data)(fast_request_t *this, char *buf, int len)
void(* close_session)(fast_request_t *this)
bool(* session_closed)(fast_request_t *this)
void(* redirect)(fast_request_t *this, char *fmt,...)
char *(* get_referer)(fast_request_t *this)
void(* to_referer)(fast_request_t *this)
void(* set)(fast_request_t *this, char *key, char *value)
void(* setf)(fast_request_t *this, char *format,...)
void(* render)(fast_request_t *this, char *template)
int(* streamf)(fast_request_t *this, char *format,...)
void(* serve)(fast_request_t *this, char *headers, chunk_t chunk)
bool(* sendfile)(fast_request_t *this, char *path, char *mime)
fast_request_t *(* get_ref)(fast_request_t *this)
void(* destroy)(fast_request_t *this)
Detailed Description
A HTTP request, encapsulates FCGX_Request.
The response is also handled through the request object.
Definition at line 34 of file fast_request.h.
Member Data Documentation
void(* fast_request_t::add_cookie)(fast_request_t *this, char *name, char *value)
Add a cookie to the reply (Set-Cookie header).
Parameters
name name of the cookie to set
value value of the cookie
Definition at line 42 of file fast_request.h.
Referenced by METHOD().
void(* fast_request_t::close_session)(fast_request_t *this)
Close the session and it's context after handling.
Definition at line 108 of file fast_request.h.
Referenced by edit(), and logout().
void(* fast_request_t::destroy)(fast_request_t *this)
Destroy the fast_request_t.
Definition at line 206 of file fast_request.h.
Referenced by dispatch().
char*(* fast_request_t::get_base)(fast_request_t *this)
Get the base path of the application.
Returns
base path
Definition at line 64 of file fast_request.h.
Referenced by METHOD().
char*(* fast_request_t::get_cookie)(fast_request_t *this, char *name)
Get a cookie the client sent in the request.
Parameters
name name of the cookie
Returns
cookie value, NULL if no such cookie found
Definition at line 50 of file fast_request.h.
Referenced by dispatch().
char*(* fast_request_t::get_env_var)(fast_request_t *this, char *name)
Get an arbitrary environment variable.
Parameters
name name of the environment variable
Returns
value, NULL if not found
Definition at line 94 of file fast_request.h.
char*(* fast_request_t::get_host)(fast_request_t *this)
Get the remote host address of this request.
Returns
host address as string
Definition at line 71 of file fast_request.h.
Referenced by dispatch().
char*(* fast_request_t::get_path)(fast_request_t *this)
Get the request path relative to the application.
Returns
path
Definition at line 57 of file fast_request.h.
Referenced by METHOD().
char*(* fast_request_t::get_query_data)(fast_request_t *this, char *name)
Get a post/get variable included in the request.
Parameters
name name of the POST/GET variable
Returns
value, NULL if not found
Definition at line 86 of file fast_request.h.
Referenced by _select(), add(), check(), edit(), and login().
fast_request_t*(* fast_request_t::get_ref)(fast_request_t *this)
Increase the reference count to the stream.
Returns
this with increased refcount
Definition at line 201 of file fast_request.h.
char*(* fast_request_t::get_referer)(fast_request_t *this)
Get the HTTP referer.
Returns
HTTP referer
Definition at line 130 of file fast_request.h.
char*(* fast_request_t::get_user_agent)(fast_request_t *this)
Get the user agent string.
Returns
user agent string
Definition at line 78 of file fast_request.h.
int(* fast_request_t::read_data)(fast_request_t *this, char *buf, int len)
Read raw POST/PUT data from HTTP request.
Parameters
buf buffer to read data into
len size of the supplied buffer
Returns
number of bytes read, < 0 on error
Definition at line 103 of file fast_request.h.
void(* fast_request_t::redirect)(fast_request_t *this, char *fmt,...)
Redirect the client to another location.
Parameters
fmt location format string
... variable argument for fmt
Definition at line 123 of file fast_request.h.
Referenced by _select(), add(), check(), edit(), login(), logout(), and METHOD().
void(* fast_request_t::render)(fast_request_t *this, char *template)
Render a template.
The render() function additionally sets a HDF variable "base" which points to the root of the web application and allows to point to other targets without to worry about path location.
Parameters
template clearsilver template file location
Definition at line 165 of file fast_request.h.
Referenced by add(), edit(), handle_result(), list(), login(), and METHOD().
bool(* fast_request_t::sendfile)(fast_request_t *this, char *path, char *mime)
Send a file from the file system.
Parameters
path path to file to serve
mime mime type of file to send, or NULL
Returns
TRUE if file served successfully
Definition at line 194 of file fast_request.h.
void(* fast_request_t::serve)(fast_request_t *this, char *headers, chunk_t chunk)
Serve a request with headers and a body.
Parameters
headers HTTP headers,
separated
chunk body to write to output
Definition at line 185 of file fast_request.h.
bool(* fast_request_t::session_closed)(fast_request_t *this)
Has the session been closed by close_session()?
Returns
TRUE if session has been closed
Definition at line 115 of file fast_request.h.
Referenced by dispatch().
void(* fast_request_t::set)(fast_request_t *this, char *key, char *value)
Set a template value.
Parameters
key key to set
value value to set key to
Definition at line 143 of file fast_request.h.
Referenced by add(), edit(), handle_result(), list(), login(), and METHOD().
void(* fast_request_t::setf)(fast_request_t *this, char *format,...)
Set a template value using format strings.
Format string is in the form "key=value", where printf like format substitution occurs over the whole string.
Parameters
format printf like format string
... variable argument list
Definition at line 154 of file fast_request.h.
Referenced by add(), edit(), handle_result(), initiate(), list(), login(), parse_public_key(), process_childsa(), process_ikesa(), process_peerconfig(), terminate(), verify_alias(), verify_login(), and verify_password().
int(* fast_request_t::streamf)(fast_request_t *this, char *format,...)
Stream a format string to the client.
Stream is not closed and may be called multiple times to allow server-push functionality.
Parameters
format printf like format string
... argmuent list to format string
Returns
number of streamed bytes, < 0 if stream closed
Definition at line 177 of file fast_request.h.
Referenced by METHOD().
void(* fast_request_t::to_referer)(fast_request_t *this)
Redirect back to the referer.
Definition at line 135 of file fast_request.h.
The documentation for this struct was generated from the following file:
fast_request.h