strongSwan: log.c File Reference
log.c File Reference
#include "command.h"
#include <errno.h>
#include <unistd.h>
Functions
CALLBACK (log_cb, void, command_format_options_t *format, char *name, vici_res_t *msg)
static int logcmd (vici_conn_t *conn)
static void __attribute__ ((constructor))
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 92 of file log.c.
References command_register(), and logcmd().
 {
     command_register((command_t) {
         logcmd, 'T', "log", "trace logging output",
         {"[--raw|--pretty]"},
         {
             {"help",        'h', 0, "show usage information"},
             {"raw",         'r', 0, "dump raw response message"},
             {"pretty",      'P', 0, "dump raw response message in pretty print"},
         }
     });
 }
CALLBACK (log_cb , void , command_format_options_t * format, char * name, vici_res_t * msg)
Definition at line 21 of file log.c.
References COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, next, printf, vici_dump(), vici_find_int(), and vici_find_str().
 {
     if (*format & COMMAND_FORMAT_RAW)
     {
         vici_dump(msg, "log", *format & COMMAND_FORMAT_PRETTY, stdout);
     }
     else
     {
         char *current, *next;
         current = vici_find_str(msg, NULL, "msg");
         while (current)
         {
             next = strchr(current, '\n');
             printf("%.2d[%s] ", vici_find_int(msg, 0, "thread"),
                    vici_find_str(msg, "   ", "group"));
             if (next == NULL)
             {
                 printf("%s\n", current);
                 break;
             }
             printf("%.*s\n", (int)(next - current), current);
             current = next + 1;
         }
     }
 }
static int logcmd (vici_conn_t * conn) static
Definition at line 49 of file log.c.
References COMMAND_FORMAT_NONE, COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, command_getopt(), command_usage(), fprintf, log_cb(), strerror, TRUE, vici_register(), and wait_sigint().
Referenced by __attribute__().
 {
     command_format_options_t format = COMMAND_FORMAT_NONE;
     char *arg;
     int ret;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 'P':
                 format |= COMMAND_FORMAT_PRETTY;
                 /* fall through to raw */
             case 'r':
                 format |= COMMAND_FORMAT_RAW;
                 continue;
             case EOF:
                 break;
             default:
                 return command_usage("invalid --log option");
         }
         break;
     }
     if (vici_register(conn, "log", log_cb, &format) != 0)
     {
         ret = errno;
         fprintf(stderr, "registering for log failed: %s\n", strerror(errno));
         return ret;
     }
     wait_sigint();
     fprintf(stderr, "disconnecting...\n");
     return 0;
 }