strongSwan: credential_factory.c File Reference
credential_factory.c File Reference
#include <stdint.h>
#include "credential_factory.h"
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <threading/thread_value.h>
#include <threading/rwlock.h>
#include <credentials/certificates/x509.h>
#include <credentials/containers/container.h>
Classes
struct private_credential_factory_t
struct entry_t
Typedefs
typedef struct
private_credential_factory_t private_credential_factory_t
typedef struct entry_t entry_t
Functions
ENUM (credential_type_names, CRED_PRIVATE_KEY, CRED_CONTAINER,"CRED_PRIVATE_KEY","CRED_PUBLIC_KEY","CRED_CERTIFICATE","CRED_CONTAINER",)
METHOD (credential_factory_t, add_builder, void, private_credential_factory_t *this, credential_type_t type, int subtype, bool final, builder_function_t constructor)
METHOD (credential_factory_t, remove_builder, void, private_credential_factory_t *this, builder_function_t constructor)
METHOD (credential_factory_t, create, void *, private_credential_factory_t *this, credential_type_t type, int subtype,...)
static bool builder_filter (void *null, entry_t **entry, credential_type_t *type, void *dummy1, int *subtype)
METHOD (credential_factory_t, create_builder_enumerator, enumerator_t *, private_credential_factory_t *this)
METHOD (credential_factory_t, destroy, void, private_credential_factory_t *this)
credential_factory_t * credential_factory_create ()
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 62 of file credential_factory.c.
typedef struct private_credential_factory_t private_credential_factory_t
Definition at line 34 of file credential_factory.c.
Function Documentation
static bool builder_filter (void * null, entry_t ** entry, credential_type_t * type, void * dummy1, int * subtype) static
Filter function for builder enumerator
Definition at line 169 of file credential_factory.c.
References FALSE, and TRUE.
Referenced by METHOD().
 {
     if ((*entry)->final)
     {
         *type = (*entry)->type;
         *subtype = (*entry)->subtype;
         return TRUE;
     }
     return FALSE;
 }
ENUM (credential_type_names , CRED_PRIVATE_KEY , CRED_CONTAINER , "CRED_PRIVATE_KEY" , "CRED_PUBLIC_KEY" , "CRED_CERTIFICATE" , "CRED_CONTAINER")
METHOD (credential_factory_t , add_builder , void , private_credential_factory_t * this, credential_type_t type, int subtype, bool final, builder_function_t constructor)
Definition at line 74 of file credential_factory.c.
References entry_t::constructor, entry_t::final, lock, malloc_thing, entry_t::subtype, subtype, type, entry_t::type, and spinlock_t::unlock.
 {
     entry_t *entry = malloc_thing(entry_t);
     entry->type = type;
     entry->subtype = subtype;
     entry->final = final;
     entry->constructor = constructor;
     this->lock->write_lock(this->lock);
     this->constructors->insert_last(this->constructors, entry);
     this->lock->unlock(this->lock);
 }
METHOD (credential_factory_t , remove_builder , void , private_credential_factory_t * this, builder_function_t constructor)
Definition at line 89 of file credential_factory.c.
References entry_t::constructor, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     this->lock->write_lock(this->lock);
     enumerator = this->constructors->create_enumerator(this->constructors);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->constructor == constructor)
         {
             this->constructors->remove_at(this->constructors, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (credential_factory_t , create , void * , private_credential_factory_t * this, credential_type_t type, int subtype, ...)
Definition at line 109 of file credential_factory.c.
References certificate_type_names, entry_t::constructor, container_type_names, CRED_CERTIFICATE, CRED_CONTAINER, CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, credential_type_names, DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, key_type_names, lock, entry_t::subtype, entry_t::type, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     va_list args;
     void *construct = NULL;
     int failures = 0;
     uintptr_t level;
     level = (uintptr_t)this->recursive->get(this->recursive);
     this->recursive->set(this->recursive, (void*)level + 1);
     this->lock->read_lock(this->lock);
     enumerator = this->constructors->create_enumerator(this->constructors);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->type == type && entry->subtype == subtype)
         {
             va_start(args, subtype);
             construct = entry->constructor(subtype, args);
             va_end(args);
             if (construct)
             {
                 break;
             }
             failures++;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!construct && !level)
     {
         enum_name_t *names;
         switch (type)
         {
             case CRED_CERTIFICATE:
                 names = certificate_type_names;
                 break;
             case CRED_CONTAINER:
                 names = container_type_names;
                 break;
             case CRED_PRIVATE_KEY:
             case CRED_PUBLIC_KEY:
             default:
                 names = key_type_names;
                 break;
         }
         DBG1(DBG_LIB, "building %N - %N failed, tried %d builders",
              credential_type_names, type, names, subtype, failures);
     }
     this->recursive->set(this->recursive, (void*)level);
     return construct;
 }
METHOD (credential_factory_t , create_builder_enumerator , enumerator_t * , private_credential_factory_t * this)
Definition at line 181 of file credential_factory.c.
References builder_filter(), enumerator_create_filter(), lock, and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(
                 this->constructors->create_enumerator(this->constructors),
                 (void*)builder_filter, this->lock, (void*)this->lock->unlock);
 }
METHOD (credential_factory_t , destroy , void , private_credential_factory_t * this)
Definition at line 190 of file credential_factory.c.
References spinlock_t::destroy, free(), and lock.
 {
     this->constructors->destroy_function(this->constructors, free);
     this->recursive->destroy(this->recursive);
     this->lock->destroy(this->lock);
     free(this);
 }