strongSwan: radius_config_t Struct Reference
radius_config_t Struct Reference
radius_config
#include "radius_config.h"
Public Attributes
radius_socket_t *(* get_socket)(radius_config_t *this)
void(* put_socket)(radius_config_t *this, radius_socket_t *skt, bool result)
chunk_t(* get_nas_identifier)(radius_config_t *this)
int(* get_preference)(radius_config_t *this)
char *(* get_name)(radius_config_t *this)
radius_config_t *(* get_ref)(radius_config_t *this)
void(* destroy)(radius_config_t *this)
Detailed Description
RADIUS server configuration.
Definition at line 53 of file radius_config.h.
Member Data Documentation
void(* radius_config_t::destroy)(radius_config_t *this)
Destroy a radius_config_t.
Definition at line 102 of file radius_config.h.
char*(* radius_config_t::get_name)(radius_config_t *this)
Get the name of the RADIUS server.
Returns
server name
Definition at line 90 of file radius_config.h.
Referenced by eap_radius_create_client().
chunk_t(* radius_config_t::get_nas_identifier)(radius_config_t *this)
Get the NAS-Identifier to use with this server.
Returns
NAS-Identifier, internal data
Definition at line 75 of file radius_config.h.
int(* radius_config_t::get_preference)(radius_config_t *this)
Get the preference of this server.
Based on the available sockets and the server reachability a preference value is calculated: better servers return a higher value.
Definition at line 83 of file radius_config.h.
Referenced by eap_radius_create_client().
radius_config_t*(* radius_config_t::get_ref)(radius_config_t *this)
Increase reference count of this server configuration.
Returns
this
Definition at line 97 of file radius_config.h.
Referenced by eap_radius_create_client().
radius_socket_t*(* radius_config_t::get_socket)(radius_config_t *this)
Get a RADIUS socket from the pool to communicate with this config.
Returns
RADIUS socket
Definition at line 60 of file radius_config.h.
void(* radius_config_t::put_socket)(radius_config_t *this, radius_socket_t *skt, bool result)
Release a socket to the pool after use.
Parameters
skt RADIUS socket to release
result result of the socket use, TRUE for success
Definition at line 68 of file radius_config.h.
The documentation for this struct was generated from the following file:
radius_config.h