strongSwan: pb_access_recommendation_msg.c File Reference
pb_access_recommendation_msg.c File Reference
#include "pb_access_recommendation_msg.h"
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pb_access_recommendation_msg_t
Macros
#define ACCESS_RECOMMENDATION_RESERVED 0x0000
#define ACCESS_RECOMMENDATION_MSG_SIZE 4
Typedefs
typedef struct
private_pb_access_recommendation_msg_t private_pb_access_recommendation_msg_t
Functions
ENUM (pb_access_recommendation_code_names, PB_REC_ACCESS_ALLOWED, PB_REC_QUARANTINED,"Access Allowed","Access Denied","Quarantined")
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_access_recommendation_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_access_recommendation_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_access_recommendation_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_access_recommendation_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_access_recommendation_msg_t *this)
METHOD (pb_access_recommendation_msg_t, get_access_recommendation, u_int16_t, private_pb_access_recommendation_msg_t *this)
pb_tnc_msg_t * pb_access_recommendation_msg_create_from_data (chunk_t data)
pb_tnc_msg_t * pb_access_recommendation_msg_create (u_int16_t recommendation)
Macro Definition Documentation
#define ACCESS_RECOMMENDATION_MSG_SIZE 4
Definition at line 41 of file pb_access_recommendation_msg.c.
Referenced by METHOD().
#define ACCESS_RECOMMENDATION_RESERVED 0x0000
PB-Access-Recommendation message (see section 4.7 of RFC 5793)
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Access Recommendation Code | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 40 of file pb_access_recommendation_msg.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pb_access_recommendation_msg_t private_pb_access_recommendation_msg_t
Definition at line 28 of file pb_access_recommendation_msg.c.
Function Documentation
ENUM (pb_access_recommendation_code_names , PB_REC_ACCESS_ALLOWED , PB_REC_QUARANTINED , "Access Allowed" , "Access Denied" , "Quarantined")
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_access_recommendation_msg_t * this)
Definition at line 68 of file pb_access_recommendation_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_access_recommendation_msg_t * this)
Definition at line 74 of file pb_access_recommendation_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_access_recommendation_msg_t * this)
Definition at line 80 of file pb_access_recommendation_msg.c.
References ACCESS_RECOMMENDATION_MSG_SIZE, ACCESS_RECOMMENDATION_RESERVED, bio_writer_create(), chunk_clone, bio_writer_t::destroy, encoding, bio_writer_t::get_buf, and bio_writer_t::write_uint16.
 {
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     writer = bio_writer_create(ACCESS_RECOMMENDATION_MSG_SIZE);
     writer->write_uint16(writer, ACCESS_RECOMMENDATION_RESERVED);
     writer->write_uint16(writer, this->recommendation);
     this->encoding = writer->get_buf(writer);
     this->encoding = chunk_clone(this->encoding);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_access_recommendation_msg_t * this, u_int32_t * offset)
Definition at line 97 of file pb_access_recommendation_msg.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, encoding, FAILED, PB_REC_ACCESS_ALLOWED, PB_REC_QUARANTINED, bio_reader_t::read_uint16, reserved, and SUCCESS.
 {
     bio_reader_t *reader;
     u_int16_t reserved;
     reader = bio_reader_create(this->encoding);
     reader->read_uint16(reader, &reserved);
     reader->read_uint16(reader, &this->recommendation);
     reader->destroy(reader);
     if (this->recommendation < PB_REC_ACCESS_ALLOWED ||
         this->recommendation > PB_REC_QUARANTINED)
     {
         DBG1(DBG_TNC, "invalid access recommendation code (%u)",
                        this->recommendation);
         *offset = 2;
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_access_recommendation_msg_t * this)
Definition at line 120 of file pb_access_recommendation_msg.c.
References encoding, and free().
 {
     free(this->encoding.ptr);
     free(this);
 }
METHOD (pb_access_recommendation_msg_t , get_access_recommendation , u_int16_t , private_pb_access_recommendation_msg_t * this)
Definition at line 127 of file pb_access_recommendation_msg.c.
 {
     return this->recommendation;
 }