strongSwan: eap_payload_t Struct Reference
eap_payload_t Struct Reference
eap_payload
#include "eap_payload.h"
Public Attributes
payload_t payload_interface
void(* set_data)(eap_payload_t *this, chunk_t data)
chunk_t(* get_data)(eap_payload_t *this)
eap_code_t(* get_code)(eap_payload_t *this)
u_int8_t(* get_identifier)(eap_payload_t *this)
eap_type_t(* get_type)(eap_payload_t *this, u_int32_t *vendor)
enumerator_t *(* get_types)(eap_payload_t *this)
bool(* is_expanded)(eap_payload_t *this)
void(* destroy)(eap_payload_t *this)
Detailed Description
Class representing an IKEv2 EAP payload.
The EAP payload format is described in RFC section 3.16.
Definition at line 37 of file eap_payload.h.
Member Data Documentation
void(* eap_payload_t::destroy)(eap_payload_t *this)
Destroys an eap_payload_t object.
Definition at line 103 of file eap_payload.h.
Referenced by METHOD(), process_eap(), and verify_eap().
eap_code_t(* eap_payload_t::get_code)(eap_payload_t *this)
Get the EAP code.
Returns
EAP message as chunk_t
Definition at line 68 of file eap_payload.h.
Referenced by get_string(), METHOD(), and server_process_eap().
chunk_t(* eap_payload_t::get_data)(eap_payload_t *this)
Get the contained EAP data.
This contains the FULL EAP message starting with "code".
Returns
EAP data (pointer to internal data)
Definition at line 61 of file eap_payload.h.
Referenced by METHOD(), process_peer_challenge(), process_peer_failure(), process_peer_success(), process_server_response(), and send_response().
u_int8_t(* eap_payload_t::get_identifier)(eap_payload_t *this)
Get the EAP identifier.
Returns
unique identifier
Definition at line 75 of file eap_payload.h.
Referenced by client_process_eap(), METHOD(), process_eap(), server_initiate_eap(), and server_process_eap().
eap_type_t(* eap_payload_t::get_type)(eap_payload_t *this, u_int32_t *vendor)
Get the EAP method type.
Parameters
vendor pointer receiving vendor identifier
Returns
EAP method type, vendor specific if vendor != 0
Definition at line 83 of file eap_payload.h.
Referenced by client_process_eap(), get_string(), METHOD(), process_eap(), radius2ike(), server_process_eap(), and verify_eap().
enumerator_t*(* eap_payload_t::get_types)(eap_payload_t *this)
Enumerate the EAP method types contained in an EAP-Nak (i.e. get_type() returns EAP_NAK).
Returns
enumerator over (eap_type_t type, u_int32_t vendor)
Definition at line 91 of file eap_payload.h.
Referenced by METHOD().
bool(* eap_payload_t::is_expanded)(eap_payload_t *this)
Check if the EAP method type is encoded in the Expanded Type format.
Returns
TRUE if in Expanded Type format
Definition at line 98 of file eap_payload.h.
Referenced by client_process_eap(), and METHOD().
payload_t eap_payload_t::payload_interface
The payload_t interface.
Definition at line 42 of file eap_payload.h.
void(* eap_payload_t::set_data)(eap_payload_t *this, chunk_t data)
Set the contained EAP data.
This contains the FULL EAP message starting with "code". Chunk gets cloned.
Parameters
message EAP data
Definition at line 52 of file eap_payload.h.
The documentation for this struct was generated from the following file:
eap_payload.h