strongSwan: printf_hook_glibc.c File Reference
printf_hook_glibc.c File Reference
#include "printf_hook.h"
#include <utils/utils.h>
#include <utils/debug.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <printf.h>
Classes
struct private_printf_hook_t
struct printf_hook_handler_t
struct printf_hook_data_t
Macros
#define SPEC_TO_INDEX(spec) ((int)(spec) - (int)'A')
Typedefs
typedef struct
private_printf_hook_t private_printf_hook_t
typedef struct
printf_hook_handler_t printf_hook_handler_t
Functions
size_t print_in_hook (printf_hook_data_t *data, char *fmt,...)
static int custom_print (FILE *stream, const struct printf_info *info, const void *const *args)
static int custom_arginfo (const struct printf_info *info, size_t n, int *argtypes)
METHOD (printf_hook_t, add_handler, void, private_printf_hook_t *this, char spec, printf_hook_function_t hook,...)
METHOD (printf_hook_t, destroy, void, private_printf_hook_t *this)
printf_hook_t * printf_hook_create ()
Variables
static printf_hook_handler_t * printf_hooks [58]
Macro Definition Documentation
#define SPEC_TO_INDEX (spec) ((int)(spec) - (int)'A')
Definition at line 76 of file printf_hook_glibc.c.
Referenced by custom_arginfo(), custom_print(), and METHOD().
Typedef Documentation
typedef struct printf_hook_handler_t printf_hook_handler_t
Definition at line 28 of file printf_hook_glibc.c.
typedef struct private_printf_hook_t private_printf_hook_t
Definition at line 27 of file printf_hook_glibc.c.
Function Documentation
static int custom_arginfo (const struct printf_info * info, size_t n, int * argtypes) static
Printf hook arginfo function, which is actually of type "printf_arginfo_[size_]function".
Definition at line 124 of file printf_hook_glibc.c.
References printf_hook_handler_t::argtypes, printf_hook_handler_t::numargs, and SPEC_TO_INDEX.
Referenced by METHOD().
 {
     int i;
     printf_hook_handler_t *handler;
     handler = printf_hooks[SPEC_TO_INDEX(info->spec)];
     if (handler->numargs <= n)
     {
         for (i = 0; i < handler->numargs; ++i)
         {
             argtypes[i] = handler->argtypes[i];
         }
     }
     /* we never set "size", as we have no user defined types */
     return handler->numargs;
 }
static int custom_print (FILE * stream, const struct printf_info * info, const void *const * args) static
Printf hook print function. This is actually of type "printf_function", however glibc does it typedef to function, but uclibc to a pointer. So we redefine it here.
Definition at line 102 of file printf_hook_glibc.c.
References data, printf_hook_spec_t::hash, printf_hook_handler_t::hook, printf_hook_spec_t::minus, printf_hook_spec_t::plus, SPEC_TO_INDEX, and printf_hook_spec_t::width.
Referenced by METHOD().
 {
     printf_hook_spec_t spec;
     printf_hook_handler_t *handler;
     printf_hook_data_t data = {
         .stream = stream,
     };
     handler =  printf_hooks[SPEC_TO_INDEX(info->spec)];
     spec.hash = info->alt;
     spec.plus = info->showsign;
     spec.minus = info->left;
     spec.width = info->width;
     return handler->hook(&data, &spec, args);
 }
METHOD (printf_hook_t , add_handler , void , private_printf_hook_t * this, char spec, printf_hook_function_t hook, ...)
Definition at line 145 of file printf_hook_glibc.c.
References printf_hook_handler_t::argtypes, countof, custom_arginfo(), custom_print(), DBG1, DBG_LIB, FALSE, free(), INIT, printf_hook_handler_t::numargs, PRINTF_HOOK_ARGTYPE_END, PRINTF_HOOK_ARGTYPE_INT, PRINTF_HOOK_ARGTYPE_POINTER, SPEC_TO_INDEX, and TRUE.
 {
     int i = -1;
     bool failed = FALSE;
     printf_hook_handler_t *handler;
     printf_hook_argtype_t argtype;
     va_list args;
     if (SPEC_TO_INDEX(spec) <= -1 ||
         SPEC_TO_INDEX(spec) >= countof(printf_hooks))
     {
         DBG1(DBG_LIB, "'%c' is not a valid printf hook specifier, "
              "not registered!", spec);
         return;
     }
     INIT(handler,
         .hook = hook,
     );
     va_start(args, hook);
     while (!failed)
     {
         argtype = va_arg(args, printf_hook_argtype_t);
         if (argtype == PRINTF_HOOK_ARGTYPE_END)
         {
             break;
         }
         if (++i >= countof(handler->argtypes))
         {
             DBG1(DBG_LIB, "Too many arguments for printf hook with "
                  "specifier '%c', not registered!", spec);
             failed = TRUE;
             break;
         }
         switch (argtype)
         {
             case PRINTF_HOOK_ARGTYPE_INT:
                 handler->argtypes[i] = PA_INT;
                 break;
             case PRINTF_HOOK_ARGTYPE_POINTER:
                 handler->argtypes[i] = PA_POINTER;
                 break;
             default:
                 DBG1(DBG_LIB, "Invalid printf hook arg type for '%c'", spec);
                 failed = TRUE;
                 break;
         }
     }
     va_end(args);
     handler->numargs = i + 1;
     if (!failed && handler->numargs > 0)
     {
 #   ifdef HAVE_PRINTF_SPECIFIER
         register_printf_specifier(spec, custom_print, custom_arginfo);
 #   else
         register_printf_function(spec, custom_print, custom_arginfo);
 #   endif
         printf_hooks[SPEC_TO_INDEX(spec)] = handler;
     }
     else
     {
         free(handler);
     }
 }
METHOD (printf_hook_t , destroy , void , private_printf_hook_t * this)
Definition at line 215 of file printf_hook_glibc.c.
References countof, and free().
 {
     int i;
     for (i = 0; i < countof(printf_hooks); i++)
     {
         free(printf_hooks[i]);
     }
     free(this);
 }
Variable Documentation
printf_hook_handler_t* printf_hooks[58] static
Definition at line 74 of file printf_hook_glibc.c.