strongSwan: radius_message
radius_message
libradius
Classes
struct radius_message_t
Macros
#define MAX_RADIUS_ATTRIBUTE_SIZE 253
#define RADIUS_TUNNEL_TYPE_ESP 9
Typedefs
typedef struct radius_message_t radius_message_t
typedef enum radius_message_code_t radius_message_code_t
typedef enum
radius_attribute_type_t radius_attribute_type_t
Enumerations
enum radius_message_code_t {
RMC_ACCESS_REQUEST = 1, RMC_ACCESS_ACCEPT = 2, RMC_ACCESS_REJECT = 3, RMC_ACCOUNTING_REQUEST = 4,
RMC_ACCOUNTING_RESPONSE = 5, RMC_ACCESS_CHALLENGE = 11, RMC_DISCONNECT_REQUEST = 40, RMC_DISCONNECT_ACK = 41,
RMC_DISCONNECT_NAK = 42, RMC_COA_REQUEST = 43, RMC_COA_ACK = 44, RMC_COA_NAK = 45
}
enum radius_attribute_type_t {
RAT_USER_NAME = 1, RAT_USER_PASSWORD = 2, RAT_CHAP_PASSWORD = 3, RAT_NAS_IP_ADDRESS = 4,
RAT_NAS_PORT = 5, RAT_SERVICE_TYPE = 6, RAT_FRAMED_PROTOCOL = 7, RAT_FRAMED_IP_ADDRESS = 8,
RAT_FRAMED_IP_NETMASK = 9, RAT_FRAMED_ROUTING = 10, RAT_FILTER_ID = 11, RAT_FRAMED_MTU = 12,
RAT_FRAMED_COMPRESSION = 13, RAT_LOGIN_IP_HOST = 14, RAT_LOGIN_SERVICE = 15, RAT_LOGIN_TCP_PORT = 16,
RAT_REPLY_MESSAGE = 18, RAT_CALLBACK_NUMBER = 19, RAT_CALLBACK_ID = 20, RAT_FRAMED_ROUTE = 22,
RAT_FRAMED_IPX_NETWORK = 23, RAT_STATE = 24, RAT_CLASS = 25, RAT_VENDOR_SPECIFIC = 26,
RAT_SESSION_TIMEOUT = 27, RAT_IDLE_TIMEOUT = 28, RAT_TERMINATION_ACTION = 29, RAT_CALLED_STATION_ID = 30,
RAT_CALLING_STATION_ID = 31, RAT_NAS_IDENTIFIER = 32, RAT_PROXY_STATE = 33, RAT_LOGIN_LAT_SERVICE = 34,
RAT_LOGIN_LAT_NODE = 35, RAT_LOGIN_LAT_GROUP = 36, RAT_FRAMED_APPLETALK_LINK = 37, RAT_FRAMED_APPLETALK_NETWORK = 38,
RAT_FRAMED_APPLETALK_ZONE = 39, RAT_ACCT_STATUS_TYPE = 40, RAT_ACCT_DELAY_TIME = 41, RAT_ACCT_INPUT_OCTETS = 42,
RAT_ACCT_OUTPUT_OCTETS = 43, RAT_ACCT_SESSION_ID = 44, RAT_ACCT_AUTHENTIC = 45, RAT_ACCT_SESSION_TIME = 46,
RAT_ACCT_INPUT_PACKETS = 47, RAT_ACCT_OUTPUT_PACKETS = 48, RAT_ACCT_TERMINATE_CAUSE = 49, RAT_ACCT_MULTI_SESSION_ID = 50,
RAT_ACCT_LINK_COUNT = 51, RAT_ACCT_INPUT_GIGAWORDS = 52, RAT_ACCT_OUTPUT_GIGAWORDS = 53, RAT_EVENT_TIMESTAMP = 55,
RAT_EGRESS_VLANID = 56, RAT_INGRESS_FILTERS = 57, RAT_EGRESS_VLAN_NAME = 58, RAT_USER_PRIORITY_TABLE = 59,
RAT_CHAP_CHALLENGE = 60, RAT_NAS_PORT_TYPE = 61, RAT_PORT_LIMIT = 62, RAT_LOGIN_LAT_PORT = 63,
RAT_TUNNEL_TYPE = 64, RAT_TUNNEL_MEDIUM_TYPE = 65, RAT_TUNNEL_CLIENT_ENDPOINT = 66, RAT_TUNNEL_SERVER_ENDPOINT = 67,
RAT_ACCT_TUNNEL_CONNECTION = 68, RAT_TUNNEL_PASSWORD = 69, RAT_ARAP_PASSWORD = 70, RAT_ARAP_FEATURES = 71,
RAT_ARAP_ZONE_ACCESS = 72, RAT_ARAP_SECURITY = 73, RAT_ARAP_SECURITY_DATA = 74, RAT_PASSWORD_RETRY = 75,
RAT_PROMPT = 76, RAT_CONNECT_INFO = 77, RAT_CONFIGURATION_TOKEN = 78, RAT_EAP_MESSAGE = 79,
RAT_MESSAGE_AUTHENTICATOR = 80, RAT_TUNNEL_PRIVATE_GROUP_ID = 81, RAT_TUNNEL_ASSIGNMENT_ID = 82, RAT_TUNNEL_PREFERENCE = 83,
RAT_ARAP_CHALLENGE_RESPONSE = 84, RAT_ACCT_INTERIM_INTERVAL = 85, RAT_ACCT_TUNNEL_PACKETS_LOST = 86, RAT_NAS_PORT_ID = 87,
RAT_FRAMED_POOL = 88, RAT_CUI = 89, RAT_TUNNEL_CLIENT_AUTH_ID = 90, RAT_TUNNEL_SERVER_AUTH_ID = 91,
RAT_NAS_FILTER_RULE = 92, RAT_UNASSIGNED = 93, RAT_ORIGINATING_LINE_INFO = 94, RAT_NAS_IPV6_ADDRESS = 95,
RAT_FRAMED_INTERFACE_ID = 96, RAT_FRAMED_IPV6_PREFIX = 97, RAT_LOGIN_IPV6_HOST = 98, RAT_FRAMED_IPV6_ROUTE = 99,
RAT_FRAMED_IPV6_POOL = 100, RAT_ERROR_CAUSE = 101, RAT_EAP_KEY_NAME = 102, RAT_DIGEST_RESPONSE = 103,
RAT_DIGEST_REALM = 104, RAT_DIGEST_NONCE = 105, RAT_DIGEST_RESPONSE_AUTH = 106, RAT_DIGEST_NEXTNONCE = 107,
RAT_DIGEST_METHOD = 108, RAT_DIGEST_URI = 109, RAT_DIGEST_QOP = 110, RAT_DIGEST_ALGORITHM = 111,
RAT_DIGEST_ENTITY_BODY_HASH = 112, RAT_DIGEST_CNONCE = 113, RAT_DIGEST_NONCE_COUNT = 114, RAT_DIGEST_USERNAME = 115,
RAT_DIGEST_OPAQUE = 116, RAT_DIGEST_AUTH_PARAM = 117, RAT_DIGEST_AKA_AUTS = 118, RAT_DIGEST_DOMAIN = 119,
RAT_DIGEST_STALE = 120, RAT_DIGEST_HA1 = 121, RAT_SIP_AOR = 122, RAT_DELEGATED_IPV6_PREFIX = 123,
RAT_MIP6_FEATURE_VECTOR = 124, RAT_MIP6_HOME_LINK_PREFIX = 125, RAT_FRAMED_IPV6_ADDRESS = 168, RAT_FRAMED_IPV6_DNS_SERVER = 169,
RAT_ROUTE_IPV6_INFORMATION = 170, RAT_DELEGATED_IPV6_PREFIX_POOL = 171, RAT_STATEFUL_IPV6_ADDRESS_POOL = 172
}
Functions
radius_message_t * radius_message_create (radius_message_code_t code)
radius_message_t * radius_message_parse (chunk_t data)
Variables
enum_name_t * radius_message_code_names
enum_name_t * radius_attribute_type_names
Detailed Description
Macro Definition Documentation
#define MAX_RADIUS_ATTRIBUTE_SIZE 253
Definition at line 32 of file radius_message.h.
Referenced by add_ike_sa_parameters(), METHOD(), and send_response().
#define RADIUS_TUNNEL_TYPE_ESP 9
Definition at line 34 of file radius_message.h.
Referenced by process_filter_id(), and send_response().
Typedef Documentation
typedef enum radius_attribute_type_t radius_attribute_type_t
Definition at line 38 of file radius_message.h.
typedef enum radius_message_code_t radius_message_code_t
Definition at line 37 of file radius_message.h.
typedef struct radius_message_t radius_message_t
Definition at line 36 of file radius_message.h.
Enumeration Type Documentation
enum radius_attribute_type_t
RADIUS Attribute Types.
Enumerator
RAT_USER_NAME
RAT_USER_PASSWORD
RAT_CHAP_PASSWORD
RAT_NAS_IP_ADDRESS
RAT_NAS_PORT
RAT_SERVICE_TYPE
RAT_FRAMED_PROTOCOL
RAT_FRAMED_IP_ADDRESS
RAT_FRAMED_IP_NETMASK
RAT_FRAMED_ROUTING
RAT_FILTER_ID
RAT_FRAMED_MTU
RAT_FRAMED_COMPRESSION
RAT_LOGIN_IP_HOST
RAT_LOGIN_SERVICE
RAT_LOGIN_TCP_PORT
RAT_REPLY_MESSAGE
RAT_CALLBACK_NUMBER
RAT_CALLBACK_ID
RAT_FRAMED_ROUTE
RAT_FRAMED_IPX_NETWORK
RAT_STATE
RAT_CLASS
RAT_VENDOR_SPECIFIC
RAT_SESSION_TIMEOUT
RAT_IDLE_TIMEOUT
RAT_TERMINATION_ACTION
RAT_CALLED_STATION_ID
RAT_CALLING_STATION_ID
RAT_NAS_IDENTIFIER
RAT_PROXY_STATE
RAT_LOGIN_LAT_SERVICE
RAT_LOGIN_LAT_NODE
RAT_LOGIN_LAT_GROUP
RAT_FRAMED_APPLETALK_LINK
RAT_FRAMED_APPLETALK_NETWORK
RAT_FRAMED_APPLETALK_ZONE
RAT_ACCT_STATUS_TYPE
RAT_ACCT_DELAY_TIME
RAT_ACCT_INPUT_OCTETS
RAT_ACCT_OUTPUT_OCTETS
RAT_ACCT_SESSION_ID
RAT_ACCT_AUTHENTIC
RAT_ACCT_SESSION_TIME
RAT_ACCT_INPUT_PACKETS
RAT_ACCT_OUTPUT_PACKETS
RAT_ACCT_TERMINATE_CAUSE
RAT_ACCT_MULTI_SESSION_ID
RAT_ACCT_LINK_COUNT
RAT_ACCT_INPUT_GIGAWORDS
RAT_ACCT_OUTPUT_GIGAWORDS
RAT_EVENT_TIMESTAMP
RAT_EGRESS_VLANID
RAT_INGRESS_FILTERS
RAT_EGRESS_VLAN_NAME
RAT_USER_PRIORITY_TABLE
RAT_CHAP_CHALLENGE
RAT_NAS_PORT_TYPE
RAT_PORT_LIMIT
RAT_LOGIN_LAT_PORT
RAT_TUNNEL_TYPE
RAT_TUNNEL_MEDIUM_TYPE
RAT_TUNNEL_CLIENT_ENDPOINT
RAT_TUNNEL_SERVER_ENDPOINT
RAT_ACCT_TUNNEL_CONNECTION
RAT_TUNNEL_PASSWORD
RAT_ARAP_PASSWORD
RAT_ARAP_FEATURES
RAT_ARAP_ZONE_ACCESS
RAT_ARAP_SECURITY
RAT_ARAP_SECURITY_DATA
RAT_PASSWORD_RETRY
RAT_PROMPT
RAT_CONNECT_INFO
RAT_CONFIGURATION_TOKEN
RAT_EAP_MESSAGE
RAT_MESSAGE_AUTHENTICATOR
RAT_TUNNEL_PRIVATE_GROUP_ID
RAT_TUNNEL_ASSIGNMENT_ID
RAT_TUNNEL_PREFERENCE
RAT_ARAP_CHALLENGE_RESPONSE
RAT_ACCT_INTERIM_INTERVAL
RAT_ACCT_TUNNEL_PACKETS_LOST
RAT_NAS_PORT_ID
RAT_FRAMED_POOL
RAT_CUI
RAT_TUNNEL_CLIENT_AUTH_ID
RAT_TUNNEL_SERVER_AUTH_ID
RAT_NAS_FILTER_RULE
RAT_UNASSIGNED
RAT_ORIGINATING_LINE_INFO
RAT_NAS_IPV6_ADDRESS
RAT_FRAMED_INTERFACE_ID
RAT_FRAMED_IPV6_PREFIX
RAT_LOGIN_IPV6_HOST
RAT_FRAMED_IPV6_ROUTE
RAT_FRAMED_IPV6_POOL
RAT_ERROR_CAUSE
RAT_EAP_KEY_NAME
RAT_DIGEST_RESPONSE
RAT_DIGEST_REALM
RAT_DIGEST_NONCE
RAT_DIGEST_RESPONSE_AUTH
RAT_DIGEST_NEXTNONCE
RAT_DIGEST_METHOD
RAT_DIGEST_URI
RAT_DIGEST_QOP
RAT_DIGEST_ALGORITHM
RAT_DIGEST_ENTITY_BODY_HASH
RAT_DIGEST_CNONCE
RAT_DIGEST_NONCE_COUNT
RAT_DIGEST_USERNAME
RAT_DIGEST_OPAQUE
RAT_DIGEST_AUTH_PARAM
RAT_DIGEST_AKA_AUTS
RAT_DIGEST_DOMAIN
RAT_DIGEST_STALE
RAT_DIGEST_HA1
RAT_SIP_AOR
RAT_DELEGATED_IPV6_PREFIX
RAT_MIP6_FEATURE_VECTOR
RAT_MIP6_HOME_LINK_PREFIX
RAT_FRAMED_IPV6_ADDRESS
RAT_FRAMED_IPV6_DNS_SERVER
RAT_ROUTE_IPV6_INFORMATION
RAT_DELEGATED_IPV6_PREFIX_POOL
RAT_STATEFUL_IPV6_ADDRESS_POOL
Definition at line 66 of file radius_message.h.
{
     RAT_USER_NAME = 1,
     RAT_USER_PASSWORD = 2,
     RAT_CHAP_PASSWORD = 3,
     RAT_NAS_IP_ADDRESS = 4,
     RAT_NAS_PORT = 5,
     RAT_SERVICE_TYPE = 6,
     RAT_FRAMED_PROTOCOL = 7,
     RAT_FRAMED_IP_ADDRESS = 8,
     RAT_FRAMED_IP_NETMASK = 9,
     RAT_FRAMED_ROUTING = 10,
     RAT_FILTER_ID = 11,
     RAT_FRAMED_MTU = 12,
     RAT_FRAMED_COMPRESSION = 13,
     RAT_LOGIN_IP_HOST = 14,
     RAT_LOGIN_SERVICE = 15,
     RAT_LOGIN_TCP_PORT = 16,
     RAT_REPLY_MESSAGE = 18,
     RAT_CALLBACK_NUMBER = 19,
     RAT_CALLBACK_ID = 20,
     RAT_FRAMED_ROUTE = 22,
     RAT_FRAMED_IPX_NETWORK = 23,
     RAT_STATE = 24,
     RAT_CLASS = 25,
     RAT_VENDOR_SPECIFIC = 26,
     RAT_SESSION_TIMEOUT = 27,
     RAT_IDLE_TIMEOUT = 28,
     RAT_TERMINATION_ACTION = 29,
     RAT_CALLED_STATION_ID = 30,
     RAT_CALLING_STATION_ID = 31,
     RAT_NAS_IDENTIFIER = 32,
     RAT_PROXY_STATE = 33,
     RAT_LOGIN_LAT_SERVICE = 34,
     RAT_LOGIN_LAT_NODE = 35,
     RAT_LOGIN_LAT_GROUP = 36,
     RAT_FRAMED_APPLETALK_LINK = 37,
     RAT_FRAMED_APPLETALK_NETWORK = 38,
     RAT_FRAMED_APPLETALK_ZONE = 39,
     RAT_ACCT_STATUS_TYPE = 40,
     RAT_ACCT_DELAY_TIME = 41,
     RAT_ACCT_INPUT_OCTETS = 42,
     RAT_ACCT_OUTPUT_OCTETS = 43,
     RAT_ACCT_SESSION_ID = 44,
     RAT_ACCT_AUTHENTIC = 45,
     RAT_ACCT_SESSION_TIME = 46,
     RAT_ACCT_INPUT_PACKETS = 47,
     RAT_ACCT_OUTPUT_PACKETS = 48,
     RAT_ACCT_TERMINATE_CAUSE = 49,
     RAT_ACCT_MULTI_SESSION_ID = 50,
     RAT_ACCT_LINK_COUNT = 51,
     RAT_ACCT_INPUT_GIGAWORDS = 52,
     RAT_ACCT_OUTPUT_GIGAWORDS = 53,
     RAT_EVENT_TIMESTAMP = 55,
     RAT_EGRESS_VLANID = 56,
     RAT_INGRESS_FILTERS = 57,
     RAT_EGRESS_VLAN_NAME = 58,
     RAT_USER_PRIORITY_TABLE = 59,
     RAT_CHAP_CHALLENGE = 60,
     RAT_NAS_PORT_TYPE = 61,
     RAT_PORT_LIMIT = 62,
     RAT_LOGIN_LAT_PORT = 63,
     RAT_TUNNEL_TYPE = 64,
     RAT_TUNNEL_MEDIUM_TYPE = 65,
     RAT_TUNNEL_CLIENT_ENDPOINT = 66,
     RAT_TUNNEL_SERVER_ENDPOINT = 67,
     RAT_ACCT_TUNNEL_CONNECTION = 68,
     RAT_TUNNEL_PASSWORD = 69,
     RAT_ARAP_PASSWORD = 70,
     RAT_ARAP_FEATURES = 71,
     RAT_ARAP_ZONE_ACCESS = 72,
     RAT_ARAP_SECURITY = 73,
     RAT_ARAP_SECURITY_DATA = 74,
     RAT_PASSWORD_RETRY = 75,
     RAT_PROMPT = 76,
     RAT_CONNECT_INFO = 77,
     RAT_CONFIGURATION_TOKEN = 78,
     RAT_EAP_MESSAGE = 79,
     RAT_MESSAGE_AUTHENTICATOR = 80,
     RAT_TUNNEL_PRIVATE_GROUP_ID = 81,
     RAT_TUNNEL_ASSIGNMENT_ID = 82,
     RAT_TUNNEL_PREFERENCE = 83,
     RAT_ARAP_CHALLENGE_RESPONSE = 84,
     RAT_ACCT_INTERIM_INTERVAL = 85,
     RAT_ACCT_TUNNEL_PACKETS_LOST = 86,
     RAT_NAS_PORT_ID = 87,
     RAT_FRAMED_POOL = 88,
     RAT_CUI = 89,
     RAT_TUNNEL_CLIENT_AUTH_ID = 90,
     RAT_TUNNEL_SERVER_AUTH_ID = 91,
     RAT_NAS_FILTER_RULE = 92,
     RAT_UNASSIGNED = 93,
     RAT_ORIGINATING_LINE_INFO = 94,
     RAT_NAS_IPV6_ADDRESS = 95,
     RAT_FRAMED_INTERFACE_ID = 96,
     RAT_FRAMED_IPV6_PREFIX = 97,
     RAT_LOGIN_IPV6_HOST = 98,
     RAT_FRAMED_IPV6_ROUTE = 99,
     RAT_FRAMED_IPV6_POOL = 100,
     RAT_ERROR_CAUSE = 101,
     RAT_EAP_KEY_NAME = 102,
     RAT_DIGEST_RESPONSE = 103,
     RAT_DIGEST_REALM = 104,
     RAT_DIGEST_NONCE = 105,
     RAT_DIGEST_RESPONSE_AUTH = 106,
     RAT_DIGEST_NEXTNONCE = 107,
     RAT_DIGEST_METHOD = 108,
     RAT_DIGEST_URI = 109,
     RAT_DIGEST_QOP = 110,
     RAT_DIGEST_ALGORITHM = 111,
     RAT_DIGEST_ENTITY_BODY_HASH = 112,
     RAT_DIGEST_CNONCE = 113,
     RAT_DIGEST_NONCE_COUNT = 114,
     RAT_DIGEST_USERNAME = 115,
     RAT_DIGEST_OPAQUE = 116,
     RAT_DIGEST_AUTH_PARAM = 117,
     RAT_DIGEST_AKA_AUTS = 118,
     RAT_DIGEST_DOMAIN = 119,
     RAT_DIGEST_STALE = 120,
     RAT_DIGEST_HA1 = 121,
     RAT_SIP_AOR = 122,
     RAT_DELEGATED_IPV6_PREFIX = 123,
     RAT_MIP6_FEATURE_VECTOR = 124,
     RAT_MIP6_HOME_LINK_PREFIX = 125,
     RAT_FRAMED_IPV6_ADDRESS = 168,
     RAT_FRAMED_IPV6_DNS_SERVER = 169,
     RAT_ROUTE_IPV6_INFORMATION = 170,
     RAT_DELEGATED_IPV6_PREFIX_POOL = 171,
     RAT_STATEFUL_IPV6_ADDRESS_POOL = 172,
 };
enum radius_message_code_t
RADIUS Message Codes.
Enumerator
RMC_ACCESS_REQUEST
RMC_ACCESS_ACCEPT
RMC_ACCESS_REJECT
RMC_ACCOUNTING_REQUEST
RMC_ACCOUNTING_RESPONSE
RMC_ACCESS_CHALLENGE
RMC_DISCONNECT_REQUEST
RMC_DISCONNECT_ACK
RMC_DISCONNECT_NAK
RMC_COA_REQUEST
RMC_COA_ACK
RMC_COA_NAK
Definition at line 43 of file radius_message.h.
{
     RMC_ACCESS_REQUEST = 1,
     RMC_ACCESS_ACCEPT = 2,
     RMC_ACCESS_REJECT = 3,
     RMC_ACCOUNTING_REQUEST = 4,
     RMC_ACCOUNTING_RESPONSE = 5,
     RMC_ACCESS_CHALLENGE = 11,
     RMC_DISCONNECT_REQUEST = 40,
     RMC_DISCONNECT_ACK = 41,
     RMC_DISCONNECT_NAK = 42,
     RMC_COA_REQUEST = 43,
     RMC_COA_ACK = 44,
     RMC_COA_NAK = 45,
 };
Function Documentation
radius_message_t* radius_message_create (radius_message_code_t code)
Create an empty RADIUS message.
Parameters
code request type
Returns
radius_message_t object
See header
Definition at line 672 of file radius_message.c.
References identifier, INIT, length, msg, and radius_message_create_empty().
Referenced by METHOD(), send_interim(), send_response(), send_start(), send_stop(), and verify_radius().
 {
     private_radius_message_t *this = radius_message_create_empty();
     INIT(this->msg,
         .code = code,
         .identifier = 0,
         .length = htons(sizeof(rmsg_t)),
     );
     return &this->public;
 }
radius_message_t* radius_message_parse (chunk_t data)
Parse and verify a recevied RADIUS message.
Parameters
data received message data
Returns
radius_message_t object, NULL if length invalid
See header
Definition at line 688 of file radius_message.c.
References DBG1, DBG_IKE, destroy(), chunk_t::len, malloc(), memcpy, msg, chunk_t::ptr, and radius_message_create_empty().
Referenced by radius_receive(), receive(), and receive_response().
 {
     private_radius_message_t *this = radius_message_create_empty();
     this->msg = malloc(data.len);
     memcpy(this->msg, data.ptr, data.len);
     if (data.len < sizeof(rmsg_t) ||
         ntohs(this->msg->length) != data.len)
     {
         DBG1(DBG_IKE, "RADIUS message has invalid length");
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
Variable Documentation
enum_name_t* radius_attribute_type_names
Enum names for radius_attribute_type_t.
Referenced by add_radius_attribute(), parse_selector(), and print_radius_attributes().
enum_name_t* radius_message_code_names
Enum names for radius_attribute_type_t.
Referenced by get_matching_ike_sas(), METHOD(), process_coa(), process_disconnect(), radius_receive(), receive(), send_response(), and send_retransmit().