strongSwan: x509_ac.c File Reference
x509_ac.c File Reference
#include "x509_ac.h"
#include <time.h>
#include <library.h>
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <utils/identification.h>
#include <collections/linked_list.h>
#include <credentials/certificates/x509.h>
#include <credentials/keys/private_key.h>
Classes
struct private_x509_ac_t
struct group_t
Macros
#define IETF_ATTR_OCTETS 4
#define IETF_ATTR_OID 6
#define IETF_ATTR_STRING 8
#define AC_OBJ_CERTIFICATE_INFO 1
#define AC_OBJ_VERSION 2
#define AC_OBJ_HOLDER_ISSUER 5
#define AC_OBJ_HOLDER_SERIAL 6
#define AC_OBJ_ENTITY_NAME 10
#define AC_OBJ_ISSUER_NAME 19
#define AC_OBJ_ISSUER 23
#define AC_OBJ_SIG_ALG 35
#define AC_OBJ_SERIAL_NUMBER 36
#define AC_OBJ_NOT_BEFORE 38
#define AC_OBJ_NOT_AFTER 39
#define AC_OBJ_ATTRIBUTE_TYPE 42
#define AC_OBJ_ATTRIBUTE_VALUE 44
#define AC_OBJ_EXTN_ID 49
#define AC_OBJ_CRITICAL 50
#define AC_OBJ_EXTN_VALUE 51
#define AC_OBJ_ALGORITHM 53
#define AC_OBJ_SIGNATURE 54
Typedefs
typedef struct private_x509_ac_t private_x509_ac_t
Functions
chunk_t x509_parse_authorityKeyIdentifier (chunk_t blob, int level0, chunk_t *authKeySerialNumber)
static void group_destroy (group_t *group)
void x509_parse_generalNames (chunk_t blob, int level0, bool implicit, linked_list_t *list)
static bool parse_directoryName (chunk_t blob, int level, bool implicit, identification_t **name)
static void parse_roleSyntax (chunk_t blob, int level0)
static bool parse_groups (private_x509_ac_t *this, chunk_t encoded, int level0)
static bool parse_certificate (private_x509_ac_t *this)
static chunk_t build_directoryName (asn1_t tag, chunk_t name)
static chunk_t build_holder (private_x509_ac_t *this)
static chunk_t build_v2_form (private_x509_ac_t *this)
static chunk_t build_attr_cert_validity (private_x509_ac_t *this)
static chunk_t build_attribute_type (int type, chunk_t content)
static chunk_t build_attributes (private_x509_ac_t *this)
static chunk_t build_authorityKeyIdentifier (private_x509_ac_t *this)
static chunk_t build_extensions (private_x509_ac_t *this)
static chunk_t build_attr_cert_info (private_x509_ac_t *this)
static bool build_ac (private_x509_ac_t *this)
METHOD (ac_t, get_serial, chunk_t, private_x509_ac_t *this)
METHOD (ac_t, get_holderSerial, chunk_t, private_x509_ac_t *this)
METHOD (ac_t, get_holderIssuer, identification_t *, private_x509_ac_t *this)
METHOD (ac_t, get_authKeyIdentifier, chunk_t, private_x509_ac_t *this)
static bool attr_filter (void *null, group_t **in, ac_group_type_t *type, void *in2, chunk_t *out)
METHOD (ac_t, create_group_enumerator, enumerator_t *, private_x509_ac_t *this)
METHOD (certificate_t, get_type, certificate_type_t, private_x509_ac_t *this)
METHOD (certificate_t, get_subject, identification_t *, private_x509_ac_t *this)
METHOD (certificate_t, get_issuer, identification_t *, private_x509_ac_t *this)
METHOD (certificate_t, has_subject, id_match_t, private_x509_ac_t *this, identification_t *subject)
METHOD (certificate_t, has_issuer, id_match_t, private_x509_ac_t *this, identification_t *issuer)
METHOD (certificate_t, issued_by, bool, private_x509_ac_t *this, certificate_t *issuer, signature_scheme_t *schemep)
METHOD (certificate_t, get_public_key, public_key_t *, private_x509_ac_t *this)
METHOD (certificate_t, get_ref, certificate_t *, private_x509_ac_t *this)
METHOD (certificate_t, get_validity, bool, private_x509_ac_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_x509_ac_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, equals, bool, private_x509_ac_t *this, certificate_t *other)
METHOD (certificate_t, destroy, void, private_x509_ac_t *this)
static private_x509_ac_t * create_empty (void)
x509_ac_t * x509_ac_load (certificate_type_t type, va_list args)
static void add_groups_from_list (private_x509_ac_t *this, linked_list_t *list)
x509_ac_t * x509_ac_gen (certificate_type_t type, va_list args)
Variables
static chunk_t ASN1_noRevAvail_ext
static const asn1Object_t roleSyntaxObjects []
static const asn1Object_t ietfAttrSyntaxObjects []
static const asn1Object_t acObjects []
Macro Definition Documentation
#define AC_OBJ_ALGORITHM 53
Definition at line 412 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_ATTRIBUTE_TYPE 42
Definition at line 407 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_ATTRIBUTE_VALUE 44
Definition at line 408 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_CERTIFICATE_INFO 1
Definition at line 396 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_CRITICAL 50
Definition at line 410 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_ENTITY_NAME 10
Definition at line 400 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_EXTN_ID 49
Definition at line 409 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_EXTN_VALUE 51
Definition at line 411 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_HOLDER_ISSUER 5
Definition at line 398 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_HOLDER_SERIAL 6
Definition at line 399 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_ISSUER 23
Definition at line 402 of file x509_ac.c.
#define AC_OBJ_ISSUER_NAME 19
Definition at line 401 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_NOT_AFTER 39
Definition at line 406 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_NOT_BEFORE 38
Definition at line 405 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_SERIAL_NUMBER 36
Definition at line 404 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_SIG_ALG 35
Definition at line 403 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_SIGNATURE 54
Definition at line 413 of file x509_ac.c.
Referenced by parse_certificate().
#define AC_OBJ_VERSION 2
Definition at line 397 of file x509_ac.c.
Referenced by parse_certificate().
#define IETF_ATTR_OCTETS 4
Definition at line 280 of file x509_ac.c.
Referenced by parse_groups().
#define IETF_ATTR_OID 6
Definition at line 281 of file x509_ac.c.
Referenced by parse_groups().
#define IETF_ATTR_STRING 8
Definition at line 282 of file x509_ac.c.
Referenced by parse_groups().
Typedef Documentation
typedef struct private_x509_ac_t private_x509_ac_t
Definition at line 37 of file x509_ac.c.
Function Documentation
static void add_groups_from_list (private_x509_ac_t * this, linked_list_t * list) static
Add groups from a list into AC group memberships
Definition at line 1095 of file x509_ac.c.
References AC_GROUP_TYPE_STRING, chunk_clone, chunk_from_str, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, group, groups, INIT, name, type, and value.
Referenced by x509_ac_gen().
 {
     enumerator_t *enumerator;
     group_t *group;
     char *name;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &name))
     {
         INIT(group,
             .type = AC_GROUP_TYPE_STRING,
             .value = chunk_clone(chunk_from_str(name)),
         );
         this->groups->insert_last(this->groups, group);
     }
     enumerator->destroy(enumerator);
 }
static bool attr_filter (void * null, group_t ** in, ac_group_type_t * type, void * in2, chunk_t * out) static
Filter function for attribute enumeration
Definition at line 806 of file x509_ac.c.
References AC_GROUP_TYPE_STRING, chunk_printable(), FALSE, and TRUE.
Referenced by METHOD().
 {
     if ((*in)->type == AC_GROUP_TYPE_STRING &&
         !chunk_printable((*in)->value, NULL, 0))
     {   /* skip non-printable strings */
         return FALSE;
     }
     *type = (*in)->type;
     *out = (*in)->value;
     return TRUE;
 }
static bool build_ac (private_x509_ac_t * this) static
build an X.509 attribute certificate
Definition at line 757 of file x509_ac.c.
References asn1_algorithmIdentifier(), asn1_bitstring(), ASN1_SEQUENCE, asn1_wrap(), build_attr_cert_info(), encoding, FALSE, free(), OID_SHA1_WITH_RSA, chunk_t::ptr, SIGN_RSA_EMSA_PKCS1_SHA1, and TRUE.
Referenced by x509_ac_gen().
 {
     chunk_t signatureValue, attributeCertificateInfo;
     attributeCertificateInfo = build_attr_cert_info(this);
     if (!this->signerKey->sign(this->signerKey, SIGN_RSA_EMSA_PKCS1_SHA1,
                                attributeCertificateInfo, &signatureValue))
     {
         free(attributeCertificateInfo.ptr);
         return FALSE;
     }
     this->encoding = asn1_wrap(ASN1_SEQUENCE, "mmm",
                         attributeCertificateInfo,
                         asn1_algorithmIdentifier(OID_SHA1_WITH_RSA),
                         asn1_bitstring("m", signatureValue));
     return TRUE;
 }
static chunk_t build_attr_cert_info (private_x509_ac_t * this) static
build attributeCertificateInfo
Definition at line 741 of file x509_ac.c.
References asn1_algorithmIdentifier(), ASN1_INTEGER, ASN1_INTEGER_1, ASN1_SEQUENCE, asn1_simple_object(), asn1_wrap(), build_attr_cert_validity(), build_attributes(), build_extensions(), build_holder(), build_v2_form(), OID_SHA1_WITH_RSA, and serialNumber.
Referenced by build_ac().
 {
     return asn1_wrap(ASN1_SEQUENCE, "cmmmmmmm",
                 ASN1_INTEGER_1,
                 build_holder(this),
                 build_v2_form(this),
                 asn1_algorithmIdentifier(OID_SHA1_WITH_RSA),
                 asn1_simple_object(ASN1_INTEGER, this->serialNumber),
                 build_attr_cert_validity(this),
                 build_attributes(this),
                 build_extensions(this));
 }
static chunk_t build_attr_cert_validity (private_x509_ac_t * this) static
build attrCertValidityPeriod
Definition at line 616 of file x509_ac.c.
References asn1_from_time(), ASN1_GENERALIZEDTIME, ASN1_SEQUENCE, and asn1_wrap().
Referenced by build_attr_cert_info().
 {
     return asn1_wrap(ASN1_SEQUENCE, "mm",
                 asn1_from_time(&this->notBefore, ASN1_GENERALIZEDTIME),
                 asn1_from_time(&this->notAfter, ASN1_GENERALIZEDTIME));
 }
static chunk_t build_attribute_type (int type, chunk_t content) static
build attribute type
Definition at line 626 of file x509_ac.c.
References asn1_build_known_oid(), ASN1_SEQUENCE, ASN1_SET, and asn1_wrap().
Referenced by build_attributes().
 {
     return asn1_wrap(ASN1_SEQUENCE, "mm",
                 asn1_build_known_oid(type),
                 asn1_wrap(ASN1_SET, "m", content));
 }
static chunk_t build_attributes (private_x509_ac_t * this) static
build attributes
Definition at line 636 of file x509_ac.c.
References AC_GROUP_TYPE_OCTETS, AC_GROUP_TYPE_OID, AC_GROUP_TYPE_STRING, asn1_build_object(), ASN1_OCTET_STRING, ASN1_OID, ASN1_SEQUENCE, asn1_simple_object(), ASN1_UTF8STRING, asn1_wrap(), build_attribute_type(), enumerator_t::destroy, enumerator_t::enumerate, free(), group, groups, chunk_t::len, len, memcpy, OID_GROUP, chunk_t::ptr, size, type, group_t::type, and group_t::value.
Referenced by build_attr_cert_info().
 {
     enumerator_t *enumerator;
     group_t *group;
     chunk_t values;
     size_t size = 0, len;
     u_char *pos;
     /* precalculate the total size of all values */
     enumerator = this->groups->create_enumerator(this->groups);
     while (enumerator->enumerate(enumerator, &group))
     {
         len = group->value.len;
         size += 1 + (len > 0) + (len >= 128) +
                 (len >= 256) + (len >= 65536) + len;
     }
     enumerator->destroy(enumerator);
     pos = asn1_build_object(&values, ASN1_SEQUENCE, size);
     enumerator = this->groups->create_enumerator(this->groups);
     while (enumerator->enumerate(enumerator, &group))
     {
         chunk_t attr;
         asn1_t type;
         switch (group->type)
         {
             case AC_GROUP_TYPE_OCTETS:
                 type = ASN1_OCTET_STRING;
                 break;
             case AC_GROUP_TYPE_STRING:
                 type = ASN1_UTF8STRING;
                 break;
             case AC_GROUP_TYPE_OID:
                 type = ASN1_OID;
                 break;
             default:
                 continue;
         }
         attr = asn1_simple_object(type, group->value);
         memcpy(pos, attr.ptr, attr.len);
         pos += attr.len;
         free(attr.ptr);
     }
     enumerator->destroy(enumerator);
     return asn1_wrap(ASN1_SEQUENCE, "m",
                 build_attribute_type(OID_GROUP,
                     asn1_wrap(ASN1_SEQUENCE, "m", values)));
 }
static chunk_t build_authorityKeyIdentifier (private_x509_ac_t * this) static
build authorityKeyIdentifier
Definition at line 692 of file x509_ac.c.
References asn1_build_known_oid(), ASN1_CONTEXT_C_1, ASN1_CONTEXT_S_2, ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_simple_object(), asn1_wrap(), build_directoryName(), chunk_clone, chunk_empty, identification_t::get_encoding, x509_t::get_serial, KEYID_PUBKEY_SHA1, OID_AUTHORITY_KEY_ID, and public.
Referenced by build_extensions().
 {
     chunk_t keyIdentifier = chunk_empty;
     chunk_t authorityCertIssuer;
     chunk_t authorityCertSerialNumber;
     identification_t *issuer;
     public_key_t *public;
     x509_t *x509;
     x509 = (x509_t*)this->signerCert;
     issuer = this->signerCert->get_issuer(this->signerCert);
     public = this->signerCert->get_public_key(this->signerCert);
     if (public)
     {
         if (public->get_fingerprint(public, KEYID_PUBKEY_SHA1, &keyIdentifier))
         {
             this->authKeyIdentifier = chunk_clone(keyIdentifier);
         }
         public->destroy(public);
     }
     authorityCertIssuer = build_directoryName(ASN1_CONTEXT_C_1,
                                             issuer->get_encoding(issuer));
     authorityCertSerialNumber = asn1_simple_object(ASN1_CONTEXT_S_2,
                                             x509->get_serial(x509));
     return asn1_wrap(ASN1_SEQUENCE, "mm",
                 asn1_build_known_oid(OID_AUTHORITY_KEY_ID),
                 asn1_wrap(ASN1_OCTET_STRING, "m",
                     asn1_wrap(ASN1_SEQUENCE, "cmm",
                         keyIdentifier,
                         authorityCertIssuer,
                         authorityCertSerialNumber
                     )
                 )
            );
 }
static chunk_t build_directoryName (asn1_t tag, chunk_t name) static
build directoryName
Definition at line 576 of file x509_ac.c.
References ASN1_CONTEXT_C_4, asn1_simple_object(), and asn1_wrap().
Referenced by build_authorityKeyIdentifier(), build_holder(), and build_v2_form().
 {
     return asn1_wrap(tag, "m",
                 asn1_simple_object(ASN1_CONTEXT_C_4, name));
 }
static chunk_t build_extensions (private_x509_ac_t * this) static
build extensions
Definition at line 731 of file x509_ac.c.
References ASN1_SEQUENCE, asn1_wrap(), and build_authorityKeyIdentifier().
Referenced by build_attr_cert_info().
 {
     return asn1_wrap(ASN1_SEQUENCE, "mc",
                 build_authorityKeyIdentifier(this),
                 ASN1_noRevAvail_ext);
 }
static chunk_t build_holder (private_x509_ac_t * this) static
build holder
Definition at line 585 of file x509_ac.c.
References ASN1_CONTEXT_C_0, ASN1_CONTEXT_C_1, ASN1_INTEGER, ASN1_SEQUENCE, asn1_simple_object(), asn1_wrap(), build_directoryName(), identification_t::get_encoding, x509_t::get_serial, and subject.
Referenced by build_attr_cert_info().
 {
     x509_t* x509 = (x509_t*)this->holderCert;
     identification_t *issuer, *subject;
     issuer = this->holderCert->get_issuer(this->holderCert);
     subject = this->holderCert->get_subject(this->holderCert);
     return asn1_wrap(ASN1_SEQUENCE, "mm",
         asn1_wrap(ASN1_CONTEXT_C_0, "mm",
             build_directoryName(ASN1_SEQUENCE, issuer->get_encoding(issuer)),
             asn1_simple_object(ASN1_INTEGER, x509->get_serial(x509))),
         build_directoryName(ASN1_CONTEXT_C_1, subject->get_encoding(subject)));
 }
static chunk_t build_v2_form (private_x509_ac_t * this) static
build v2Form
Definition at line 603 of file x509_ac.c.
References ASN1_CONTEXT_C_0, ASN1_SEQUENCE, asn1_wrap(), build_directoryName(), identification_t::get_encoding, and subject.
Referenced by build_attr_cert_info().
 {
     identification_t *subject;
     subject = this->signerCert->get_subject(this->signerCert);
     return asn1_wrap(ASN1_CONTEXT_C_0, "m",
                 build_directoryName(ASN1_SEQUENCE,
                     subject->get_encoding(subject)));
 }
static private_x509_ac_t* create_empty (void) static
create an empty but initialized X.509 attribute certificate
Definition at line 1022 of file x509_ac.c.
References INIT, and linked_list_create().
Referenced by x509_ac_gen(), and x509_ac_load().
 {
     private_x509_ac_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .certificate = {
                     .get_type = _get_type,
                     .get_subject = _get_subject,
                     .get_issuer = _get_issuer,
                     .has_subject = _has_subject,
                     .has_issuer = _has_issuer,
                     .issued_by = _issued_by,
                     .get_public_key = _get_public_key,
                     .get_validity = _get_validity,
                     .get_encoding = _get_encoding,
                     .equals = _equals,
                     .get_ref = _get_ref,
                     .destroy = _destroy,
                 },
                 .get_serial = _get_serial,
                 .get_holderSerial = _get_holderSerial,
                 .get_holderIssuer = _get_holderIssuer,
                 .get_authKeyIdentifier = _get_authKeyIdentifier,
                 .create_group_enumerator = _create_group_enumerator,
             },
         },
         .groups = linked_list_create(),
         .ref = 1,
     );
     return this;
 }
static void group_destroy (group_t * group) static
Clean up a group entry
Definition at line 163 of file x509_ac.c.
References free(), chunk_t::ptr, and group_t::value.
Referenced by METHOD().
 {
     free(group->value.ptr);
     free(group);
 }
METHOD (ac_t , get_serial , chunk_t , private_x509_ac_t * this)
Definition at line 775 of file x509_ac.c.
References serialNumber.
 {
     return this->serialNumber;
 }
METHOD (ac_t , get_holderSerial , chunk_t , private_x509_ac_t * this)
Definition at line 781 of file x509_ac.c.
References chunk_empty.
 {
     if (this->holderSerial)
     {
         return this->holderSerial->get_encoding(this->holderSerial);
     }
     return chunk_empty;
 }
METHOD (ac_t , get_holderIssuer , identification_t * , private_x509_ac_t * this)
Definition at line 791 of file x509_ac.c.
 {
     return this->holderIssuer;
 }
METHOD (ac_t , get_authKeyIdentifier , chunk_t , private_x509_ac_t * this)
Definition at line 797 of file x509_ac.c.
 {
     return this->authKeyIdentifier;
 }
METHOD (ac_t , create_group_enumerator , enumerator_t * , private_x509_ac_t * this)
Definition at line 819 of file x509_ac.c.
References attr_filter(), enumerator_create_filter(), and groups.
 {
     return enumerator_create_filter(
                             this->groups->create_enumerator(this->groups),
                             (void*)attr_filter, NULL, NULL);
 }
METHOD (certificate_t , get_type , certificate_type_t , private_x509_ac_t * this)
Definition at line 827 of file x509_ac.c.
References CERT_X509_AC.
 {
     return CERT_X509_AC;
 }
METHOD (certificate_t , get_subject , identification_t * , private_x509_ac_t * this)
Definition at line 833 of file x509_ac.c.
 {
     if (this->entityName)
     {
         return this->entityName;
     }
     return this->holderSerial;
 }
METHOD (certificate_t , get_issuer , identification_t * , private_x509_ac_t * this)
Definition at line 843 of file x509_ac.c.
 {
     return this->issuerName;
 }
METHOD (certificate_t , has_subject , id_match_t , private_x509_ac_t * this, identification_t * subject)
Definition at line 849 of file x509_ac.c.
References ID_MATCH_NONE, and max.
 {
     id_match_t entity = ID_MATCH_NONE, serial = ID_MATCH_NONE;
     if (this->entityName)
     {
         entity = this->entityName->matches(this->entityName, subject);
     }
     if (this->holderSerial)
     {
         serial = this->holderSerial->matches(this->holderSerial, subject);
     }
     return max(entity, serial);
 }
METHOD (certificate_t , has_issuer , id_match_t , private_x509_ac_t * this, identification_t * issuer)
Definition at line 865 of file x509_ac.c.
References chunk_equals(), identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, and ID_MATCH_PERFECT.
 {
     if (issuer->get_type(issuer) == ID_KEY_ID &&
         this->authKeyIdentifier.ptr &&
         chunk_equals(this->authKeyIdentifier, issuer->get_encoding(issuer)))
     {
         return ID_MATCH_PERFECT;
     }
     return this->issuerName->matches(this->issuerName, issuer);
 }
METHOD (certificate_t , issued_by , bool , private_x509_ac_t * this, certificate_t * issuer, signature_scheme_t * schemep)
Definition at line 877 of file x509_ac.c.
References algorithm, CERT_X509, chunk_equals(), public_key_t::destroy, FALSE, fingerprint, public_key_t::get_fingerprint, x509_t::get_flags, certificate_t::get_public_key, certificate_t::get_subject, certificate_t::get_type, key, KEYID_PUBKEY_SHA1, scheme, SIGN_UNKNOWN, signature_scheme_from_oid(), valid, public_key_t::verify, and X509_AA.
 {
     public_key_t *key;
     signature_scheme_t scheme;
     bool valid;
     x509_t *x509 = (x509_t*)issuer;
     /* check if issuer is an X.509 AA certificate */
     if (issuer->get_type(issuer) != CERT_X509)
     {
         return FALSE;
     }
     if (!(x509->get_flags(x509) & X509_AA))
     {
         return FALSE;
     }
     /* get the public key of the issuer */
     key = issuer->get_public_key(issuer);
     /* compare keyIdentifiers if available, otherwise use DNs */
     if (this->authKeyIdentifier.ptr && key)
     {
         chunk_t fingerprint;
         if (!key->get_fingerprint(key, KEYID_PUBKEY_SHA1, &fingerprint) ||
             !chunk_equals(fingerprint, this->authKeyIdentifier))
         {
             return FALSE;
         }
     }
     else
     {
         if (!this->issuerName->equals(this->issuerName,
                                       issuer->get_subject(issuer)))
         {
             return FALSE;
         }
     }
     /* determine signature scheme */
     scheme = signature_scheme_from_oid(this->algorithm);
     if (scheme == SIGN_UNKNOWN || key == NULL)
     {
         return FALSE;
     }
     valid = key->verify(key, scheme, this->certificateInfo, this->signature);
     key->destroy(key);
     if (valid && schemep)
     {
         *schemep = scheme;
     }
     return valid;
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_x509_ac_t * this)
Definition at line 934 of file x509_ac.c.
 {
     return NULL;
 }
METHOD (certificate_t , get_ref , certificate_t * , private_x509_ac_t * this)
Definition at line 940 of file x509_ac.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.interface.certificate;
 }
METHOD (certificate_t , get_validity , bool , private_x509_ac_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 947 of file x509_ac.c.
 {
     time_t t = when ? *when : time(NULL);
     if (not_before)
     {
         *not_before = this->notBefore;
     }
     if (not_after)
     {
         *not_after = this->notAfter;
     }
     return (t >= this->notBefore && t <= this->notAfter);
 }
METHOD (certificate_t , get_encoding , bool , private_x509_ac_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 963 of file x509_ac.c.
References CERT_ASN1_DER, chunk_clone, CRED_PART_END, CRED_PART_X509_AC_ASN1_DER, cred_encoding_t::encode, library_t::encoding, lib, and TRUE.
 {
     if (type == CERT_ASN1_DER)
     {
         *encoding = chunk_clone(this->encoding);
         return TRUE;
     }
     return lib->encoding->encode(lib->encoding, type, NULL, encoding,
                     CRED_PART_X509_AC_ASN1_DER, this->encoding, CRED_PART_END);
 }
METHOD (certificate_t , equals , bool , private_x509_ac_t * this, certificate_t * other)
Definition at line 975 of file x509_ac.c.
References CERT_ASN1_DER, chunk_equals(), encoding, certificate_t::equals, FALSE, free(), certificate_t::get_encoding, chunk_t::ptr, and TRUE.
 {
     chunk_t encoding;
     bool equal;
     if ((certificate_t*)this == other)
     {
         return TRUE;
     }
     if (other->equals == _equals)
     {   /* skip allocation if we have the same implementation */
         return chunk_equals(this->encoding,
                             ((private_x509_ac_t*)other)->encoding);
     }
     if (!other->get_encoding(other, CERT_ASN1_DER, &encoding))
     {
         return FALSE;
     }
     equal = chunk_equals(this->encoding, encoding);
     free(encoding.ptr);
     return equal;
 }
METHOD (certificate_t , destroy , void , private_x509_ac_t * this)
Definition at line 999 of file x509_ac.c.
References DESTROY_IF, encoding, free(), group_destroy(), groups, chunk_t::ptr, ref_put(), and serialNumber.
 {
     if (ref_put(&this->ref))
     {
         DESTROY_IF(this->holderIssuer);
         DESTROY_IF(this->holderSerial);
         DESTROY_IF(this->entityName);
         DESTROY_IF(this->issuerName);
         DESTROY_IF(this->holderCert);
         DESTROY_IF(this->signerCert);
         DESTROY_IF(this->signerKey);
         this->groups->destroy_function(this->groups, (void*)group_destroy);
         free(this->serialNumber.ptr);
         free(this->authKeyIdentifier.ptr);
         free(this->encoding.ptr);
         free(this);
     }
 }
static bool parse_certificate (private_x509_ac_t * this) static
Parses an X.509 attribute certificate
Definition at line 418 of file x509_ac.c.
References AC_OBJ_ALGORITHM, AC_OBJ_ATTRIBUTE_TYPE, AC_OBJ_ATTRIBUTE_VALUE, AC_OBJ_CERTIFICATE_INFO, AC_OBJ_CRITICAL, AC_OBJ_ENTITY_NAME, AC_OBJ_EXTN_ID, AC_OBJ_EXTN_VALUE, AC_OBJ_HOLDER_ISSUER, AC_OBJ_HOLDER_SERIAL, AC_OBJ_ISSUER_NAME, AC_OBJ_NOT_AFTER, AC_OBJ_NOT_BEFORE, AC_OBJ_SERIAL_NUMBER, AC_OBJ_SIG_ALG, AC_OBJ_SIGNATURE, AC_OBJ_VERSION, algorithm, ASN1_GENERALIZEDTIME, asn1_known_oid(), asn1_parse_algorithmIdentifier(), asn1_parser_create(), asn1_to_time(), chunk_clone, chunk_skip(), DBG1, DBG2, DBG_ASN, asn1_parser_t::destroy, encoding, end, FALSE, asn1_parser_t::get_level, ID_KEY_ID, identification_create_from_encoding(), asn1_parser_t::iterate, OID_ACCESS_IDENTITY, OID_AUTHENTICATION_INFO, OID_AUTHORITY_KEY_ID, OID_CHARGING_IDENTITY, OID_CRL_DISTRIBUTION_POINTS, OID_GROUP, OID_NO_REV_AVAIL, OID_ROLE, OID_TARGET_INFORMATION, OID_UNKNOWN, parse_directoryName(), parse_groups(), parse_roleSyntax(), parser, serialNumber, asn1_parser_t::success, TRUE, type, version, and x509_parse_authorityKeyIdentifier().
Referenced by x509_ac_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int type     = OID_UNKNOWN;
     int extn_oid = OID_UNKNOWN;
     int sig_alg  = OID_UNKNOWN;
     bool success = FALSE;
     bool critical;
     parser = asn1_parser_create(acObjects, this->encoding);
     while (parser->iterate(parser, &objectID, &object))
     {
         u_int level = parser->get_level(parser)+1;
         switch (objectID)
         {
             case AC_OBJ_CERTIFICATE_INFO:
                 this->certificateInfo = object;
                 break;
             case AC_OBJ_VERSION:
                 this->version = (object.len) ? (1 + (u_int)*object.ptr) : 1;
                 DBG2(DBG_ASN, "  v%d", this->version);
                 if (this->version != 2)
                 {
                     DBG1(DBG_ASN, "v%d attribute certificates are not "
                          "supported", this->version);
                     goto end;
                 }
                 break;
             case AC_OBJ_HOLDER_ISSUER:
                 if (!parse_directoryName(object, level, FALSE,
                                          &this->holderIssuer))
                 {
                     goto end;
                 }
                 break;
             case AC_OBJ_HOLDER_SERIAL:
                 this->holderSerial = identification_create_from_encoding(
                                                             ID_KEY_ID, object);
                 break;
             case AC_OBJ_ENTITY_NAME:
                 if (!parse_directoryName(object, level, TRUE,
                                          &this->entityName))
                 {
                     goto end;
                 }
                 break;
             case AC_OBJ_ISSUER_NAME:
                 if (!parse_directoryName(object, level, FALSE,
                                          &this->issuerName))
                 {
                     goto end;
                 }
                 break;
             case AC_OBJ_SIG_ALG:
                 sig_alg = asn1_parse_algorithmIdentifier(object, level, NULL);
                 break;
             case AC_OBJ_SERIAL_NUMBER:
                 this->serialNumber = chunk_clone(object);
                 break;
             case AC_OBJ_NOT_BEFORE:
                 this->notBefore = asn1_to_time(&object, ASN1_GENERALIZEDTIME);
                 break;
             case AC_OBJ_NOT_AFTER:
                 this->notAfter = asn1_to_time(&object, ASN1_GENERALIZEDTIME);
                 break;
             case AC_OBJ_ATTRIBUTE_TYPE:
                 type = asn1_known_oid(object);
                 break;
             case AC_OBJ_ATTRIBUTE_VALUE:
             {
                 switch (type)
                 {
                     case OID_AUTHENTICATION_INFO:
                         DBG2(DBG_ASN, "  need to parse authenticationInfo");
                         break;
                     case OID_ACCESS_IDENTITY:
                         DBG2(DBG_ASN, "  need to parse accessIdentity");
                         break;
                     case OID_CHARGING_IDENTITY:
                         DBG2(DBG_ASN, "  need to parse chargingIdentity");
                         break;
                     case OID_GROUP:
                         DBG2(DBG_ASN, "-- > --");
                         if (!parse_groups(this, object, level))
{
                             goto end;
                         }
                         DBG2(DBG_ASN, "-- < --");
                         break;
                     case OID_ROLE:
                         parse_roleSyntax(object, level);
                         break;
                     default:
                         break;
                 }
                 break;
             }
             case AC_OBJ_EXTN_ID:
                 extn_oid = asn1_known_oid(object);
                 break;
             case AC_OBJ_CRITICAL:
                 critical = object.len && *object.ptr;
                 DBG2(DBG_ASN, "  %s",(critical)?"TRUE":"FALSE");
                 break;
             case AC_OBJ_EXTN_VALUE:
             {
                 switch (extn_oid)
                 {
                     case OID_CRL_DISTRIBUTION_POINTS:
                         DBG2(DBG_ASN, "  need to parse crlDistributionPoints");
                         break;
                     case OID_AUTHORITY_KEY_ID:
                         this->authKeyIdentifier =
                                 x509_parse_authorityKeyIdentifier(object,
                                             level, &this->authKeySerialNumber);
                         break;
                     case OID_TARGET_INFORMATION:
                         DBG2(DBG_ASN, "  need to parse targetInformation");
                         break;
                     case OID_NO_REV_AVAIL:
                         this->noRevAvail = TRUE;
                         break;
                     default:
                         break;
                 }
                 break;
             }
             case AC_OBJ_ALGORITHM:
                 this->algorithm = asn1_parse_algorithmIdentifier(object, level,
                                                                  NULL);
                 if (this->algorithm != sig_alg)
                 {
                     DBG1(DBG_ASN, "  signature algorithms do not agree");
                     success = FALSE;
                     goto end;
                 }
                 break;
             case AC_OBJ_SIGNATURE:
                 this->signature = chunk_skip(object, 1);
                 break;
             default:
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     return success;
 }
static bool parse_directoryName (chunk_t blob, int level, bool implicit, identification_t ** name) static
parses a directoryName
Definition at line 185 of file x509_ac.c.
References linked_list_t::create_enumerator, DBG1, DBG_ASN, enumerator_t::destroy, linked_list_t::destroy, identification_t::destroy, enumerator_t::enumerate, FALSE, linked_list_create(), list, TRUE, and x509_parse_generalNames().
Referenced by parse_certificate().
 {
     identification_t *directoryName;
     enumerator_t *enumerator;
     bool first = TRUE;
     linked_list_t *list;
     list = linked_list_create();
     x509_parse_generalNames(blob, level, implicit, list);
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &directoryName))
     {
         if (first)
         {
             *name = directoryName;
             first = FALSE;
         }
         else
         {
             DBG1(DBG_ASN, "more than one directory name - first selected");
             directoryName->destroy(directoryName);
             break;
         }
     }
     enumerator->destroy(enumerator);
     list->destroy(list);
     if (first)
     {
         DBG1(DBG_ASN, "no directoryName found");
         return FALSE;
     }
     return TRUE;
 }
static bool parse_groups (private_x509_ac_t * this, chunk_t encoded, int level0) static
Parse group memberships, IETF attributes
Definition at line 287 of file x509_ac.c.
References AC_GROUP_TYPE_OCTETS, AC_GROUP_TYPE_OID, AC_GROUP_TYPE_STRING, asn1_parser_create(), chunk_clone, asn1_parser_t::destroy, group, groups, IETF_ATTR_OCTETS, IETF_ATTR_OID, IETF_ATTR_STRING, INIT, asn1_parser_t::iterate, parser, asn1_parser_t::set_top_level, asn1_parser_t::success, type, and value.
Referenced by parse_certificate().
 {
     ac_group_type_t type;
     group_t *group;
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool success;
     parser = asn1_parser_create(ietfAttrSyntaxObjects, encoded);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case IETF_ATTR_OCTETS:
                 type = AC_GROUP_TYPE_OCTETS;
                 break;
             case IETF_ATTR_OID:
                 type = AC_GROUP_TYPE_OID;
                 break;
             case IETF_ATTR_STRING:
                 type = AC_GROUP_TYPE_STRING;
                 break;
             default:
                 continue;
         }
         INIT(group,
             .type = type,
             .value = chunk_clone(object),
         );
         this->groups->insert_last(this->groups, group);
     }
     success = parser->success(parser);
     parser->destroy(parser);
     return success;
 }
static void parse_roleSyntax (chunk_t blob, int level0) static
Parses roleSyntax
Definition at line 238 of file x509_ac.c.
References asn1_parser_create(), asn1_parser_t::destroy, asn1_parser_t::iterate, parser, and asn1_parser_t::set_top_level.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(roleSyntaxObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             default:
                 break;
         }
     }
     parser->destroy(parser);
 }
chunk_t x509_parse_authorityKeyIdentifier (chunk_t blob, int level0, chunk_t * authKeySerialNumber)
Extracts an authoritykeyIdentifier
Definition at line 551 of file x509_cert.c.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     chunk_t authKeyIdentifier = chunk_empty;
     *authKeySerialNumber = chunk_empty;
     parser = asn1_parser_create(authKeyIdentifierObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case AUTH_KEY_ID_KEY_ID:
                 authKeyIdentifier = chunk_clone(object);
                 break;
             case AUTH_KEY_ID_CERT_ISSUER:
                 /* TODO: x509_parse_generalNames(object, level+1, TRUE); */
                 break;
             case AUTH_KEY_ID_CERT_SERIAL:
                 *authKeySerialNumber = object;
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
     return authKeyIdentifier;
 }
void x509_parse_generalNames (chunk_t blob, int level0, bool implicit, linked_list_t * list)
declaration of function implemented in x509_cert.c
Extracts one or several GNs and puts them into a chained list
Definition at line 505 of file x509_cert.c.
Referenced by parse_directoryName().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(generalNamesObjects, blob);
     parser->set_top_level(parser, level0);
     parser->set_flags(parser, implicit, FALSE);
     while (parser->iterate(parser, &objectID, &object))
     {
         if (objectID == GENERAL_NAMES_GN)
         {
             identification_t *gn = parse_generalName(object,
                                             parser->get_level(parser)+1);
             if (gn)
             {
                 list->insert_last(list, (void *)gn);
             }
         }
     }
     parser->destroy(parser);
 }
Variable Documentation
const asn1Object_t acObjects[] static
ASN.1 definition of an X509 attribute certificate
Definition at line 329 of file x509_ac.c.
chunk_t ASN1_noRevAvail_ext static
Initial value:
= chunk_from_chars(
    0x30, 0x09,
          0x06, 0x03,
                0x55, 0x1d, 0x38,
          0x04, 0x02,
                0x05, 0x00
)
Definition at line 169 of file x509_ac.c.
const asn1Object_t ietfAttrSyntaxObjects[] static
Initial value:
=
{
    { 0, "ietfAttrSyntax",      ASN1_SEQUENCE,      ASN1_NONE },
    { 1,   "policyAuthority",   ASN1_CONTEXT_C_0,   ASN1_OPT |
                                                    ASN1_BODY },
    { 1,   "end opt",           ASN1_EOC,           ASN1_END  },
    { 1,   "values",            ASN1_SEQUENCE,      ASN1_LOOP },
    { 2,     "octets",          ASN1_OCTET_STRING,  ASN1_OPT |
                                                    ASN1_BODY },
    { 2,     "end choice",      ASN1_EOC,           ASN1_END  },
    { 2,     "oid",             ASN1_OID,           ASN1_OPT |
                                                    ASN1_BODY },
    { 2,     "end choice",      ASN1_EOC,           ASN1_END  },
    { 2,     "string",          ASN1_UTF8STRING,    ASN1_OPT |
                                                    ASN1_BODY },
    { 2,     "end choice",      ASN1_EOC,           ASN1_END  },
    { 1,   "end loop",          ASN1_EOC,           ASN1_END  },
    { 0, "exit",                ASN1_EOC,           ASN1_EXIT }
}
ASN.1 definition of ietfAttrSyntax
Definition at line 261 of file x509_ac.c.
const asn1Object_t roleSyntaxObjects[] static
Initial value:
=
{
    { 0, "roleSyntax",      ASN1_SEQUENCE,      ASN1_NONE },
    { 1,   "roleAuthority", ASN1_CONTEXT_C_0,   ASN1_OPT |
                                                ASN1_OBJ  },
    { 1,   "end opt",       ASN1_EOC,           ASN1_END  },
    { 1,   "roleName",      ASN1_CONTEXT_C_1,   ASN1_OBJ  },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT }
}
ASN.1 definition of roleSyntax
Definition at line 225 of file x509_ac.c.