strongSwan: tkm_id_manager.c File Reference
tkm_id_manager.c File Reference
#include "tkm_id_manager.h"
#include <utils/debug.h>
#include <threading/rwlock.h>
Classes
struct private_tkm_id_manager_t
Typedefs
typedef struct
private_tkm_id_manager_t private_tkm_id_manager_t
Functions
ENUM_BEGIN (tkm_context_kind_names, TKM_CTX_NONCE, TKM_CTX_ESA,"NONCE_CONTEXT","DH_CONTEXT","CC_CONTEXT","ISA_CONTEXT","AE_CONTEXT","ESA_CONTEXT")
ENUM_END (tkm_context_kind_names, TKM_CTX_ESA)
static bool is_valid_kind (const tkm_context_kind_t kind)
METHOD (tkm_id_manager_t, acquire_id, int, private_tkm_id_manager_t *const this, const tkm_context_kind_t kind)
METHOD (tkm_id_manager_t, release_id, bool, private_tkm_id_manager_t *const this, const tkm_context_kind_t kind, const int id)
METHOD (tkm_id_manager_t, destroy, void, private_tkm_id_manager_t *this)
tkm_id_manager_t * tkm_id_manager_create (const tkm_limits_t limits)
Typedef Documentation
typedef struct private_tkm_id_manager_t private_tkm_id_manager_t
Definition at line 31 of file tkm_id_manager.c.
Function Documentation
ENUM_BEGIN (tkm_context_kind_names , TKM_CTX_NONCE , TKM_CTX_ESA , "NONCE_CONTEXT" , "DH_CONTEXT" , "CC_CONTEXT" , "ISA_CONTEXT" , "AE_CONTEXT" , "ESA_CONTEXT")
ENUM_END (tkm_context_kind_names , TKM_CTX_ESA)
static bool is_valid_kind (const tkm_context_kind_t kind) static
Check if given kind is a valid context kind value.
Parameters
kind context kind to check
Returns
TRUE if given kind is a valid context kind, FALSE otherwise
Definition at line 67 of file tkm_id_manager.c.
References TKM_CTX_MAX.
Referenced by METHOD().
 {
     return (int)kind >= 0 && kind < TKM_CTX_MAX;
 };
METHOD (tkm_id_manager_t , acquire_id , int , private_tkm_id_manager_t *const this, const tkm_context_kind_t kind)
Definition at line 72 of file tkm_id_manager.c.
References DBG1, DBG_LIB, id, is_valid_kind(), limits, and tkm_context_kind_names.
 {
     int id = 0;
     uint64_t j;
     if (!is_valid_kind(kind))
     {
         DBG1(DBG_LIB, "tried to acquire id for invalid context kind '%d'",
              kind);
         return 0;
     }
     this->locks[kind]->write_lock(this->locks[kind]);
     for (j = 0; j < this->limits[kind]; j++)
     {
         if (!this->ctxids[kind][j])
         {
             this->ctxids[kind][j] = true;
             id = j + 1;
             break;
         }
     }
     this->locks[kind]->unlock(this->locks[kind]);
     if (!id)
     {
         DBG1(DBG_LIB, "acquiring %N context id failed", tkm_context_kind_names,
              kind);
     }
     return id;
 }
METHOD (tkm_id_manager_t , release_id , bool , private_tkm_id_manager_t *const this, const tkm_context_kind_t kind, const int id)
Definition at line 106 of file tkm_id_manager.c.
References DBG1, DBG_LIB, FALSE, is_valid_kind(), and TRUE.
 {
     const int idx = id - 1;
     if (!is_valid_kind(kind))
     {
         DBG1(DBG_LIB, "tried to release id %d for invalid context kind '%d'",
              id, kind);
         return FALSE;
     }
     this->locks[kind]->write_lock(this->locks[kind]);
     this->ctxids[kind][idx] = false;
     this->locks[kind]->unlock(this->locks[kind]);
     return TRUE;
 }
METHOD (tkm_id_manager_t , destroy , void , private_tkm_id_manager_t * this)
Definition at line 127 of file tkm_id_manager.c.
References free(), and TKM_CTX_MAX.
 {
     int i;
     for (i = 0; i < TKM_CTX_MAX; i++)
     {
         free(this->ctxids[i]);
         this->locks[i]->destroy(this->locks[i]);
     }
     free(this);
 }