strongSwan: x509_ocsp_request
x509_ocsp_request
x509
Classes
struct x509_ocsp_request_t
Typedefs
typedef struct x509_ocsp_request_t x509_ocsp_request_t
Functions
x509_ocsp_request_t * x509_ocsp_request_gen (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct x509_ocsp_request_t x509_ocsp_request_t
Definition at line 27 of file x509_ocsp_request.h.
Function Documentation
x509_ocsp_request_t* x509_ocsp_request_gen (certificate_type_t type, va_list args)
Generate a X.509 OCSP request.
The resulting builder accepts: BUILD_CA_CERT: CA of the checked certificates, exactly one BUILD_CERT: certificates to check with the request, at least one BUILD_SUBJECT: subject requesting check, optional BUILD_SIGNING_CERT: certificate to create requestor signature, optional BUILD_SIGNING_KEY: private key to create requestor signature, optional
Parameters
type certificate type, CERT_X509_OCSP_REQUEST only
args builder_part_t argument list
Returns
OCSP request, NULL on failure
See header.
Definition at line 502 of file x509_ocsp_request.c.
References BUILD_CA_CERT, BUILD_CERT, BUILD_END, build_OCSPRequest(), BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, BUILD_SUBJECT, private_x509_ocsp_request_t::ca, private_x509_ocsp_request_t::candidates, private_x509_ocsp_request_t::cert, cert, CERT_X509, identification_t::clone, create_empty(), destroy(), private_x509_ocsp_request_t::encoding, private_key_t::get_ref, certificate_t::get_ref, certificate_t::get_type, linked_list_t::insert_last, private_x509_ocsp_request_t::key, private_x509_ocsp_request_t::public, req(), private_x509_ocsp_request_t::requestor, subject, and TRUE.
Referenced by METHOD().
 {
     private_x509_ocsp_request_t *req;
     certificate_t *cert;
     private_key_t *private;
     identification_t *subject;
     req = create_empty();
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_CA_CERT:
                 cert = va_arg(args, certificate_t*);
                 if (cert->get_type(cert) == CERT_X509)
                 {
                     req->ca = (x509_t*)cert->get_ref(cert);
                 }
                 continue;
             case BUILD_CERT:
                 cert = va_arg(args, certificate_t*);
                 if (cert->get_type(cert) == CERT_X509)
                 {
                     req->candidates->insert_last(req->candidates,
                                                  cert->get_ref(cert));
                 }
                 continue;
             case BUILD_SIGNING_CERT:
                 cert = va_arg(args, certificate_t*);
                 req->cert = cert->get_ref(cert);
                 continue;
             case BUILD_SIGNING_KEY:
                 private = va_arg(args, private_key_t*);
                 req->key = private->get_ref(private);
                 continue;
             case BUILD_SUBJECT:
                 subject = va_arg(args, identification_t*);
                 req->requestor = subject->clone(subject);
                 continue;
             case BUILD_END:
                 break;
             default:
                 destroy(req);
                 return NULL;
         }
         break;
     }
     if (req->ca)
     {
         req->encoding = build_OCSPRequest(req);
         return &req->public;
     }
     destroy(req);
     return NULL;
 }