strongSwan: pkcs11_dh.c File Reference
pkcs11_dh.c File Reference
#include "pkcs11_dh.h"
#include <utils/debug.h>
#include <library.h>
#include <asn1/asn1.h>
#include <asn1/oid.h>
#include "pkcs11_manager.h"
Classes
struct private_pkcs11_dh_t
Typedefs
typedef struct private_pkcs11_dh_t private_pkcs11_dh_t
Functions
static bool derive_secret (private_pkcs11_dh_t *this, chunk_t other)
METHOD (diffie_hellman_t, set_other_public_value, bool, private_pkcs11_dh_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_my_public_value, bool, private_pkcs11_dh_t *this, chunk_t *value)
METHOD (diffie_hellman_t, get_shared_secret, bool, private_pkcs11_dh_t *this, chunk_t *secret)
METHOD (diffie_hellman_t, get_dh_group, diffie_hellman_group_t, private_pkcs11_dh_t *this)
METHOD (diffie_hellman_t, destroy, void, private_pkcs11_dh_t *this)
static bool generate_key_pair (private_pkcs11_dh_t *this, CK_ATTRIBUTE_PTR pub, int pub_len, CK_ATTRIBUTE_PTR pri, int pri_len, CK_ATTRIBUTE_TYPE attr)
static bool generate_key_pair_modp (private_pkcs11_dh_t *this, size_t exp_len, chunk_t g, chunk_t p)
static bool generate_key_pair_ecp (private_pkcs11_dh_t *this, chunk_t ecparams)
static pkcs11_library_t * find_token (private_pkcs11_dh_t *this, CK_SESSION_HANDLE *session)
static private_pkcs11_dh_t * create_generic (diffie_hellman_group_t group, CK_MECHANISM_TYPE key, CK_MECHANISM_TYPE derive)
static pkcs11_dh_t * create_ecp (diffie_hellman_group_t group, chunk_t ecparam)
static pkcs11_dh_t * create_modp (diffie_hellman_group_t group, size_t exp_len, chunk_t g, chunk_t p)
static chunk_t ecparams_lookup (diffie_hellman_group_t group)
pkcs11_dh_t * pkcs11_dh_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Typedef Documentation
typedef struct private_pkcs11_dh_t private_pkcs11_dh_t
Definition at line 25 of file pkcs11_dh.c.
Function Documentation
static pkcs11_dh_t* create_ecp (diffie_hellman_group_t group, chunk_t ecparam) static
Definition at line 354 of file pkcs11_dh.c.
References chunk_free(), CKM_EC_KEY_PAIR_GEN, CKM_ECDH1_DERIVE, create_generic(), free(), and generate_key_pair_ecp().
Referenced by pkcs11_dh_create().
 {
     private_pkcs11_dh_t *this = create_generic(group, CKM_EC_KEY_PAIR_GEN,
                                                CKM_ECDH1_DERIVE);
     if (this)
     {
         if (generate_key_pair_ecp(this, ecparam))
         {
             chunk_free(&ecparam);
             return &this->public;
         }
         chunk_free(&ecparam);
         free(this);
     }
     return NULL;
 }
static private_pkcs11_dh_t* create_generic (diffie_hellman_group_t group, CK_MECHANISM_TYPE key, CK_MECHANISM_TYPE derive) static
Generic internal constructor
Definition at line 324 of file pkcs11_dh.c.
References find_token(), free(), group, INIT, key, and lib.
Referenced by create_ecp(), and create_modp().
 {
     private_pkcs11_dh_t *this;
     INIT(this,
         .public = {
             .dh = {
                 .get_shared_secret = _get_shared_secret,
                 .set_other_public_value = _set_other_public_value,
                 .get_my_public_value = _get_my_public_value,
                 .get_dh_group = _get_dh_group,
                 .destroy = _destroy,
             },
         },
         .group = group,
         .mech_key = key,
         .mech_derive = derive,
     );
     this->lib = find_token(this, &this->session);
     if (!this->lib)
     {
         free(this);
         return NULL;
     }
     return this;
 }
static pkcs11_dh_t* create_modp (diffie_hellman_group_t group, size_t exp_len, chunk_t g, chunk_t p) static
Constructor for MODP DH
Definition at line 375 of file pkcs11_dh.c.
References CKM_DH_PKCS_DERIVE, CKM_DH_PKCS_KEY_PAIR_GEN, create_generic(), free(), and generate_key_pair_modp().
Referenced by pkcs11_dh_create().
 {
     private_pkcs11_dh_t *this = create_generic(group, CKM_DH_PKCS_KEY_PAIR_GEN,
                                                CKM_DH_PKCS_DERIVE);
     if (this)
     {
         if (generate_key_pair_modp(this, exp_len, g, p))
         {
             return &this->public;
         }
         free(this);
     }
     return NULL;
 }
static bool derive_secret (private_pkcs11_dh_t * this, chunk_t other) static
Derive a DH/ECDH shared secret.
If this succeeds the shared secret is stored in this->secret.
Definition at line 84 of file pkcs11_dh.c.
References chunk_free(), ck_rv_names, CKA_CLASS, CKA_KEY_TYPE, CKA_VALUE, CKK_GENERIC_SECRET, CKO_SECRET_KEY, CKR_OK, countof, DBG1, DBG_CFG, FALSE, chunk_t::len, lib, chunk_t::ptr, TRUE, and type.
Referenced by METHOD().
 {
     CK_OBJECT_CLASS klass = CKO_SECRET_KEY;
     CK_KEY_TYPE type = CKK_GENERIC_SECRET;
     CK_ATTRIBUTE attr[] = {
         { CKA_CLASS, &klass, sizeof(klass) },
         { CKA_KEY_TYPE, &type, sizeof(type) },
     };
     CK_MECHANISM mech = {
         this->mech_derive,
         other.ptr,
         other.len,
     };
     CK_OBJECT_HANDLE secret;
     CK_RV rv;
     rv = this->lib->f->C_DeriveKey(this->session, &mech, this->pri_key,
                                    attr, countof(attr), &secret);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_DeriveKey() error: %N", ck_rv_names, rv);
         return FALSE;
     }
     if (!this->lib->get_ck_attribute(this->lib, this->session, secret,
                                      CKA_VALUE, &this->secret))
     {
         chunk_free(&this->secret);
         return FALSE;
     }
     return TRUE;
 }
static chunk_t ecparams_lookup (diffie_hellman_group_t group) static
Lookup the EC params for the given group.
Definition at line 395 of file pkcs11_dh.c.
References asn1_build_known_oid(), chunk_empty, ECP_192_BIT, ECP_224_BIT, ECP_256_BIT, ECP_384_BIT, ECP_521_BIT, OID_PRIME192V1, OID_PRIME256V1, OID_SECT224R1, OID_SECT384R1, and OID_SECT521R1.
Referenced by pkcs11_dh_create().
 {
     switch (group)
     {
         case ECP_192_BIT:
             return asn1_build_known_oid(OID_PRIME192V1);
         case ECP_224_BIT:
             return asn1_build_known_oid(OID_SECT224R1);
         case ECP_256_BIT:
             return asn1_build_known_oid(OID_PRIME256V1);
         case ECP_384_BIT:
             return asn1_build_known_oid(OID_SECT384R1);
         case ECP_521_BIT:
             return asn1_build_known_oid(OID_SECT521R1);
         default:
             break;
     }
     return chunk_empty;
 }
static pkcs11_library_t* find_token (private_pkcs11_dh_t * this, CK_SESSION_HANDLE * session) static
Find a token we can use for DH/ECDH algorithm
Definition at line 280 of file pkcs11_dh.c.
References ck_function_list::C_OpenSession, CKF_SERIAL_SESSION, CKR_OK, pkcs11_library_t::create_mechanism_enumerator, pkcs11_manager_t::create_token_enumerator, enumerator_t::destroy, enumerator_t::enumerate, pkcs11_library_t::f, found, library_t::get, lib, mechs, and type.
Referenced by create_generic().
 {
     enumerator_t *tokens, *mechs;
     pkcs11_manager_t *manager;
     pkcs11_library_t *current, *found = NULL;
     CK_MECHANISM_TYPE type;
     CK_SLOT_ID slot;
     manager = lib->get(lib, "pkcs11-manager");
     if (!manager)
     {
         return NULL;
     }
     tokens = manager->create_token_enumerator(manager);
     while (tokens->enumerate(tokens, &current, &slot))
     {
         mechs = current->create_mechanism_enumerator(current, slot);
         while (mechs->enumerate(mechs, &type, NULL))
         {   /* we assume we can generate key pairs if the derive mechanism
              * is supported */
             if (type == this->mech_derive)
             {
                 if (current->f->C_OpenSession(slot, CKF_SERIAL_SESSION,
                                               NULL, NULL, session) == CKR_OK)
                 {
                     found = current;
                     break;
                 }
             }
         }
         mechs->destroy(mechs);
         if (found)
         {
             break;
         }
     }
     tokens->destroy(tokens);
     return found;
 }
static bool generate_key_pair (private_pkcs11_dh_t * this, CK_ATTRIBUTE_PTR pub, int pub_len, CK_ATTRIBUTE_PTR pri, int pri_len, CK_ATTRIBUTE_TYPE attr) static
Generate a DH/ECDH key pair.
If this succeeds, this->pri_key has a handle to the private key and this->pub_key stores the public key.
Definition at line 196 of file pkcs11_dh.c.
References chunk_free(), ck_rv_names, CKR_OK, DBG1, DBG_CFG, FALSE, lib, and TRUE.
Referenced by generate_key_pair_ecp(), and generate_key_pair_modp().
 {
     CK_MECHANISM mech = {
         this->mech_key,
         NULL,
         0,
     };
     CK_OBJECT_HANDLE pub_key;
     CK_RV rv;
     rv = this->lib->f->C_GenerateKeyPair(this->session, &mech, pub, pub_len,
                             pri, pri_len, &pub_key, &this->pri_key);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_GenerateKeyPair() error: %N", ck_rv_names, rv);
         return FALSE;
     }
     if (!this->lib->get_ck_attribute(this->lib, this->session, pub_key,
                                      attr, &this->pub_key))
     {
         chunk_free(&this->pub_key);
         return FALSE;
     }
     return TRUE;
 }
static bool generate_key_pair_ecp (private_pkcs11_dh_t * this, chunk_t ecparams) static
Generate ECDH key pair.
Definition at line 248 of file pkcs11_dh.c.
References chunk_clear(), chunk_clone, chunk_skip(), CK_TRUE, CKA_DERIVE, CKA_EC_PARAMS, CKA_EC_POINT, countof, FALSE, generate_key_pair(), chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by create_ecp().
 {
     CK_BBOOL ck_true = CK_TRUE;
     CK_ATTRIBUTE pub_attr[] = {
         { CKA_DERIVE, &ck_true, sizeof(ck_true) },
         { CKA_EC_PARAMS, ecparams.ptr, ecparams.len },
     };
     CK_ATTRIBUTE pri_attr[] = {
         { CKA_DERIVE, &ck_true, sizeof(ck_true) },
     };
     chunk_t pub_key;
     if (!generate_key_pair(this, pub_attr, countof(pub_attr), pri_attr,
                            countof(pri_attr), CKA_EC_POINT))
     {
         return FALSE;
     }
     if (this->pub_key.len <= 0 || this->pub_key.ptr[0] != 0x04)
     {   /* we currently only support the point in uncompressed form which
          * looks like this: 0x04 || x || y */
         chunk_clear(&this->pub_key);
         return FALSE;
     }
     pub_key = chunk_clone(chunk_skip(this->pub_key, 1));
     chunk_clear(&this->pub_key);
     this->pub_key = pub_key;
     return TRUE;
 }
static bool generate_key_pair_modp (private_pkcs11_dh_t * this, size_t exp_len, chunk_t g, chunk_t p) static
Generate DH key pair.
Definition at line 227 of file pkcs11_dh.c.
References bits, CK_TRUE, CKA_BASE, CKA_DERIVE, CKA_PRIME, CKA_VALUE, CKA_VALUE_BITS, countof, generate_key_pair(), chunk_t::len, and chunk_t::ptr.
Referenced by create_modp().
 {
     CK_BBOOL ck_true = CK_TRUE;
     CK_ATTRIBUTE pub_attr[] = {
         { CKA_DERIVE, &ck_true, sizeof(ck_true) },
         { CKA_PRIME, p.ptr, p.len },
         { CKA_BASE, g.ptr, g.len },
     };
     CK_ULONG bits = exp_len * 8;
     CK_ATTRIBUTE pri_attr[] = {
         { CKA_DERIVE, &ck_true, sizeof(ck_true) },
         { CKA_VALUE_BITS, &bits, sizeof(bits) },
     };
     return generate_key_pair(this, pub_attr, countof(pub_attr), pri_attr,
                              countof(pri_attr), CKA_VALUE);
 }
METHOD (diffie_hellman_t , set_other_public_value , bool , private_pkcs11_dh_t * this, chunk_t value)
Definition at line 116 of file pkcs11_dh.c.
References chunk_cata, chunk_from_chars, chunk_from_thing, CKD_NULL, derive_secret(), diffie_hellman_verify_value(), ECP_192_BIT, ECP_224_BIT, ECP_256_BIT, ECP_384_BIT, ECP_521_BIT, FALSE, settings_t::get_bool, group, chunk_t::len, lib, library_t::ns, params, chunk_t::ptr, library_t::settings, and TRUE.
 {
     if (!diffie_hellman_verify_value(this->group, value))
     {
         return FALSE;
     }
     switch (this->group)
     {
         case ECP_192_BIT:
         case ECP_224_BIT:
         case ECP_256_BIT:
         case ECP_384_BIT:
         case ECP_521_BIT:
         {   /* we expect the public value to just be the concatenated x and y
              * coordinates, so we tag the value as an uncompressed ECPoint */
             chunk_t tag = chunk_from_chars(0x04);
             chunk_t pubkey = chunk_cata("cc", tag, value);
             CK_ECDH1_DERIVE_PARAMS params = {
                 CKD_NULL,
                 0,
                 NULL,
                 pubkey.len,
                 pubkey.ptr,
             };
             if (!lib->settings->get_bool(lib->settings,
                                     "%s.ecp_x_coordinate_only", TRUE, lib->ns))
             {   /* we only get the x coordinate back */
                 return FALSE;
             }
             value = chunk_from_thing(params);
             break;
         }
         default:
             break;
     }
     return derive_secret(this, value);
 }
METHOD (diffie_hellman_t , get_my_public_value , bool , private_pkcs11_dh_t * this, chunk_t * value)
Definition at line 157 of file pkcs11_dh.c.
References chunk_clone, and TRUE.
 {
     *value = chunk_clone(this->pub_key);
     return TRUE;
 }
METHOD (diffie_hellman_t , get_shared_secret , bool , private_pkcs11_dh_t * this, chunk_t * secret)
Definition at line 164 of file pkcs11_dh.c.
References chunk_clone, FALSE, chunk_t::ptr, and TRUE.
 {
     if (!this->secret.ptr)
     {
         return FALSE;
     }
     *secret = chunk_clone(this->secret);
     return TRUE;
 }
METHOD (diffie_hellman_t , get_dh_group , diffie_hellman_group_t , private_pkcs11_dh_t * this)
Definition at line 175 of file pkcs11_dh.c.
References group.
 {
     return this->group;
 }
METHOD (diffie_hellman_t , destroy , void , private_pkcs11_dh_t * this)
Definition at line 181 of file pkcs11_dh.c.
References chunk_clear(), free(), and lib.
 {
     this->lib->f->C_CloseSession(this->session);
     chunk_clear(&this->pub_key);
     chunk_clear(&this->secret);
     free(this);
 }