strongSwan: chunk
chunk
utils
Classes
struct chunk_t
Macros
#define chunk_from_chars(...) ((chunk_t){(u_char[]){__VA_ARGS__}, sizeof((u_char[]){__VA_ARGS__})})
#define chunk_from_thing(thing) chunk_create((u_char*)&(thing), sizeof(thing))
#define chunk_from_str(str) ({char *x = (str); chunk_create((u_char*)x, strlen(x));})
#define chunk_alloc(bytes) ({size_t x = (bytes); chunk_create(x ? malloc(x) : NULL, x);})
#define chunk_alloca(bytes) ({size_t x = (bytes); chunk_create(x ? alloca(x) : NULL, x);})
#define chunk_clone(chunk) ({chunk_t x = (chunk); chunk_create_clone(x.len ? malloc(x.len) : NULL, x);})
#define chunk_clonea(chunk) ({chunk_t x = (chunk); chunk_create_clone(x.len ? alloca(x.len) : NULL, x);})
#define chunk_cat(mode,...) chunk_create_cat(malloc(chunk_length(mode, __VA_ARGS__)), mode, __VA_ARGS__)
#define chunk_cata(mode,...) chunk_create_cat(alloca(chunk_length(mode, __VA_ARGS__)), mode, __VA_ARGS__)
Typedefs
typedef struct chunk_t chunk_t
Functions
static chunk_t chunk_create (u_char *ptr, size_t len)
chunk_t chunk_create_clone (u_char *ptr, chunk_t chunk)
size_t chunk_length (const char *mode,...)
chunk_t chunk_create_cat (u_char *ptr, const char *mode,...)
void chunk_split (chunk_t chunk, const char *mode,...)
bool chunk_write (chunk_t chunk, char *path, mode_t mask, bool force)
bool chunk_from_fd (int fd, chunk_t *chunk)
chunk_t * chunk_map (char *path, bool wr)
bool chunk_unmap (chunk_t *chunk)
chunk_t chunk_to_hex (chunk_t chunk, char *buf, bool uppercase)
chunk_t chunk_from_hex (chunk_t hex, char *buf)
chunk_t chunk_to_base64 (chunk_t chunk, char *buf)
chunk_t chunk_from_base64 (chunk_t base64, char *buf)
chunk_t chunk_to_base32 (chunk_t chunk, char *buf)
static void chunk_free (chunk_t *chunk)
static void chunk_clear (chunk_t *chunk)
static chunk_t chunk_skip (chunk_t chunk, size_t bytes)
static chunk_t chunk_skip_zero (chunk_t chunk)
int chunk_compare (chunk_t a, chunk_t b)
static bool chunk_equals (chunk_t a, chunk_t b)
static bool chunk_equals_const (chunk_t a, chunk_t b)
static bool chunk_equals_ptr (chunk_t *a, chunk_t *b)
bool chunk_increment (chunk_t chunk)
bool chunk_printable (chunk_t chunk, chunk_t *sane, char replace)
void chunk_hash_seed ()
u_int32_t chunk_hash (chunk_t chunk)
u_int32_t chunk_hash_inc (chunk_t chunk, u_int32_t hash)
u_int32_t chunk_hash_static (chunk_t chunk)
u_int32_t chunk_hash_static_inc (chunk_t chunk, u_int32_t hash)
u_int64_t chunk_mac (chunk_t chunk, u_char *key)
u_int16_t chunk_internet_checksum (chunk_t data)
u_int16_t chunk_internet_checksum_inc (chunk_t data, u_int16_t checksum)
int chunk_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Variables
chunk_t chunk_empty
Detailed Description
Macro Definition Documentation
#define chunk_alloc (bytes) ({size_t x = (bytes); chunk_create(x ? malloc(x) : NULL, x);})
Allocate a chunk on the heap
Definition at line 241 of file chunk.h.
Referenced by add_policy_internal(), ascii_to_unicode(), asn1_build_known_oid(), bench_aead(), bench_crypter(), bench_hasher(), bench_prf(), bench_rng(), bench_signer(), bio_writer_create(), bliss_bitpacker_create(), bliss_bitpacker_create_from_data(), build_der_signature(), build_emsa_pkcs1_signature(), build_pub(), burn_aead(), burn_crypter(), burn_signer(), ChallengeResponse(), create_icv(), crypt(), decode_base64(), do_read(), do_test_gcm(), encode_base64(), encrypt_content(), encrypt_mppe_key(), esp_context_create(), exec_str_cb(), expand_keys(), expand_skeyid_e(), ExpandDESKey(), export_mpi(), extract_platform_info(), gcrypt_rsa_find_token(), generate(), generate_encoding(), handle_response(), METHOD(), mgf1_create(), ntru_drbg_create(), ntru_private_key_create(), openssl_bn2chunk(), openssl_crypter_create(), openssl_ec_fingerprint(), openssl_hash_chunk(), openssl_rsa_fingerprint(), padlock_aes_crypter_create(), parse(), parse_attributes(), parse_chunk(), pem_encoder_encode(), prf_plus_create(), process_handshake(), pts_ima_bios_list_create(), pts_ima_event_list_create(), pts_pcr_create(), radius2queue(), rng_allocate_bytes_not_zero(), scep_generate_transaction_id(), sequence_to_chunk(), sign_raw(), START_TEST(), tcg_seg_attr_seg_env_create(), tls_aead_create_implicit(), vadd_kv_or_li(), and verify_raw().
#define chunk_alloca (bytes) ({size_t x = (bytes); chunk_create(x ? alloca(x) : NULL, x);})
Allocate a chunk on the stack
Definition at line 246 of file chunk.h.
Referenced by bliss_utils_generate_c(), build_vip(), ChallengeResponse(), cookie_build(), decrypt_mppe_key(), derive_key(), do_test_gcm(), do_test_mct(), expand_keys(), final(), manage_srcroute(), METHOD(), pbkdf1(), pbkdf2(), pbkdf2_f(), pkcs12_derive_key(), process_challenge(), process_peer_challenge(), process_start(), scep_generate_pkcs10_fingerprint(), scep_generate_transaction_id(), START_TEST(), update(), and verify_mac().
#define chunk_cat (mode, ...) chunk_create_cat(malloc(chunk_length(mode, __VA_ARGS__)), mode, __VA_ARGS__)
Concatenate chunks into a chunk on heap
Definition at line 261 of file chunk.h.
Referenced by append_header(), append_header_frag(), build_notification_data(), build_requestList(), build_signature(), build_signature_auth_data(), CALLBACK(), cert_payload_create_from_hash_and_url(), cookie_build(), generate(), generate_natd_hash(), GenerateMSK(), id_payload_create_from_ts(), ip_packet_create_from_data(), ip_packet_create_udp_from_data(), load_entries(), METHOD(), openssl_bn2chunk(), process_eap(), process_ec_key_exchange(), process_modp_key_exchange(), radius2ike(), radius2queue(), send_once(), send_server_key_exchange(), START_TEST(), x509_build_crlDistributionPoints(), and x509_build_subjectAltNames().
#define chunk_cata (mode, ...) chunk_create_cat(alloca(chunk_length(mode, __VA_ARGS__)), mode, __VA_ARGS__)
Concatenate chunks into a chunk on stack
Definition at line 266 of file chunk.h.
Referenced by add_initial_contact(), add_ipcomp_notify(), add_radius_request_attrs(), AuthenticatorResponse(), build_vip(), challenge(), ChallengeHash(), cookie_build(), derive_master(), do_test_gcm(), encode_rsa(), encrypt_mppe_key(), expand_keys(), generate_iv(), generate_natd_hash(), GenerateMSK(), hash_challenge(), hash_password(), METHOD(), p_hash(), pbkdf2(), process_challenge(), process_start(), send_notify(), and START_TEST().
#define chunk_clone (chunk) ({chunk_t x = (chunk); chunk_create_clone(x.len ? malloc(x.len) : NULL, x);})
Clone a chunk on heap
Definition at line 251 of file chunk.h.
Referenced by add_device_id(), add_fragment(), add_groups_from_list(), add_legacy_entry(), add_revoked(), asn1_oid_from_string(), attribute_create(), build(), build_application(), build_authorityKeyIdentifier(), build_handshake(), build_pkt(), build_pub_modulus(), build_sha1(), CALLBACK(), callback_data_create(), callback_shared(), cb(), certreq_payload_create_dn(), challenge(), check_alerts(), check_list_create(), chunk_printable(), configuration_attribute_create_chunk(), create_ack(), create_from_string_with_num_type(), create_from_string_with_prefix_type(), decrypt_mppe_key(), decrypt_with_config(), dnscert_create_frm_rr(), do_args(), do_test_mct(), echo_inbound(), encrypted_fragment_payload_create_from_data(), extend_pcr(), extract_platform_info(), extract_secret(), finalize_message(), find_certificates(), find_pubkey_in_certs(), fragment_payload_create_from_data(), gcrypt_rsa_find_token(), generate(), generate_key_pair_ecp(), generic_attr_bool_create_from_data(), generic_attr_chunk_create_from_data(), generic_attr_string_create_from_data(), get_nt_hash(), get_ts_from_subnet(), ha_message_parse(), handle_tcg_message(), hash_data(), have_vips_from_pool(), hybrid_authenticator_create(), id_payload_create_from_identification(), id_payload_create_from_ts(), identification_create_from_encoding(), identification_create_from_string(), ietf_attr_assess_result_create_from_data(), ietf_attr_attr_request_create_from_data(), ietf_attr_fwd_enabled_create_from_data(), ietf_attr_installed_packages_create_from_data(), ietf_attr_numeric_version_create_from_data(), ietf_attr_op_status_create_from_data(), ietf_attr_pa_tnc_error_create(), ietf_attr_pa_tnc_error_create_from_data(), ietf_attr_pa_tnc_error_create_with_offset(), ietf_attr_port_filter_create_from_data(), ietf_attr_product_info_create(), ietf_attr_product_info_create_from_data(), ietf_attr_remediation_instr_create(), ietf_attr_remediation_instr_create_from_data(), ietf_attr_string_version_create(), ietf_attr_string_version_create_from_data(), ike2queue(), imc_imv_msg_create(), imc_os_info_create(), initiate_connection(), install_route(), ipseckey_create_frm_rr(), ita_attr_command_create_from_data(), ita_attr_dummy_create_from_data(), ita_attr_get_settings_create_from_data(), ita_attr_settings_create_from_data(), load(), load_aik_blob(), load_entries(), load_from_blob(), load_secret(), load_tester_creds_create(), main(), mediation_job_create(), METHOD(), ntru_private_key_create_from_data(), ntru_public_key_create_from_data(), offset2host(), openssl_crl_load(), openssl_x509_load(), pa_tnc_msg_create_from_data(), parse(), parse_attributes(), parse_authKeyIdentifier_ext(), parse_certificate(), parse_certificatePolicies(), parse_crlNumber_ext(), parse_groups(), parse_pbes1_params(), parse_pbes2_params(), parse_pbkdf2_params(), parse_policyMappings(), parse_public_key(), parse_subjectKeyIdentifier_ext(), passphrase_cb(), path_dirname(), pb_access_recommendation_msg_create_from_data(), pb_assessment_result_msg_create_from_data(), pb_error_msg_create_from_data(), pb_experimental_msg_create_from_data(), pb_language_preference_msg_create(), pb_language_preference_msg_create_from_data(), pb_mutual_capability_msg_create_from_data(), pb_pa_msg_create(), pb_pa_msg_create_from_data(), pb_pdp_referral_msg_create(), pb_pdp_referral_msg_create_from_data(), pb_reason_string_msg_create(), pb_reason_string_msg_create_from_data(), pb_remediation_parameters_msg_create(), pb_remediation_parameters_msg_create_from_data(), pb_tnc_batch_create_from_data(), pem_to_bin(), pgp_cert_load(), pin_cb(), pkcs11_creds_load(), pkcs7_attributes_create_from_chunk(), pkcs7_data_load(), pkcs7_encrypted_data_load(), pkcs7_enveloped_data_gen(), pkcs7_enveloped_data_load(), pkcs7_signed_data_gen(), pkcs7_signed_data_load(), prf_plus_create(), process_certreq(), process_client_hello(), process_ike_add(), process_init_response(), process_payloads(), process_peer_challenge(), process_request(), process_server_hello(), process_start(), proposal_substructure_create_for_ipcomp_v1(), put_half_open(), pwg_attr_vendor_smi_code_create_from_data(), read_from_stream(), read_key(), read_revoked(), reauthenticate(), receive_packet(), route_entry_clone(), save_state(), send_check(), sender(), server_process_eap(), set_data(), setup_tunnel(), shared_cb(), sign_crl(), START_TEST(), swid_tag_create(), swid_tag_id_create(), tcg_pts_attr_aik_create_from_data(), tcg_pts_attr_dh_nonce_finish_create(), tcg_pts_attr_dh_nonce_finish_create_from_data(), tcg_pts_attr_dh_nonce_params_req_create_from_data(), tcg_pts_attr_dh_nonce_params_resp_create(), tcg_pts_attr_dh_nonce_params_resp_create_from_data(), tcg_pts_attr_file_meas_create_from_data(), tcg_pts_attr_gen_attest_evid_create_from_data(), tcg_pts_attr_get_aik_create_from_data(), tcg_pts_attr_get_tpm_version_info_create_from_data(), tcg_pts_attr_meas_algo_create_from_data(), tcg_pts_attr_proto_caps_create_from_data(), tcg_pts_attr_req_file_meas_create_from_data(), tcg_pts_attr_req_file_meta_create_from_data(), tcg_pts_attr_req_func_comp_evid_create_from_data(), tcg_pts_attr_simple_comp_evid_create_from_data(), tcg_pts_attr_simple_evid_final_create_from_data(), tcg_pts_attr_tpm_version_info_create(), tcg_pts_attr_tpm_version_info_create_from_data(), tcg_pts_attr_unix_file_meta_create_from_data(), tcg_seg_attr_max_size_create_from_data(), tcg_seg_attr_next_seg_create_from_data(), tcg_seg_attr_seg_env_create_from_data(), tcg_swid_attr_req_create_from_data(), tcg_swid_attr_tag_id_inv_create_from_data(), tcg_swid_attr_tag_inv_create_from_data(), tkm_public_key_load(), tnccs_batch_create_from_data(), tnccs_reason_strings_msg_create_from_node(), traffic_selector_substructure_create_from_traffic_selector(), transform_attribute_create_value(), unwrap_ec_point(), x509_ac_gen(), x509_ac_load(), x509_cert_gen(), x509_cert_load(), x509_crl_gen(), x509_crl_load(), x509_parse_authorityKeyIdentifier(), x509_pkcs10_gen(), and x509_pkcs10_load().
#define chunk_clonea (chunk) ({chunk_t x = (chunk); chunk_create_clone(x.len ? alloca(x.len) : NULL, x);})
Clone a chunk on stack
Definition at line 256 of file chunk.h.
Referenced by add(), check_lease(), create_ts(), do_memxor(), get_lease(), manage_route(), METHOD(), resize(), and START_TEST().
#define chunk_from_chars (...) ((chunk_t){(u_char[]){__VA_ARGS__}, sizeof((u_char[]){__VA_ARGS__})})
Initialize a chunk using a char array
Definition at line 226 of file chunk.h.
Referenced by asn1_integer(), AuthenticatorResponse(), build_natd_payload(), CALLBACK(), derive_key(), eap_payload_create_code(), encode_rsa(), generate(), GenerateMSK(), issue(), load_entries(), main(), METHOD(), openssl_bn2chunk(), parse_public_key(), path_dirname(), prepare_dhcp(), receive_msg(), receive_packets(), sign_crl(), START_TEST(), test_bad_sigs(), test_good_sig(), test_tls(), update(), and write_sasl().
#define chunk_from_str (str) ({char *x = (str); chunk_create((u_char*)x, strlen(x));})
Initialize a chunk from a string, not containing 0-terminator
Definition at line 236 of file chunk.h.
Referenced by add_attrs_natural_lang(), add_certification_state(), add_configuration_state(), add_device_id(), add_groups_from_list(), add_ike_sa_parameters(), add_machine_type_model(), add_quadruple(), add_radius_request_attrs(), add_time_source(), add_vendor_name(), build_getter_msg(), build_public_key(), build_round(), CALLBACK(), callback_shared(), cb(), collect_tags(), create_from_string_with_num_type(), create_from_string_with_prefix_type(), decode_list(), decode_section(), decrypt_with_config(), do_sasl(), eap_radius_build_attributes(), get_next_test_vector(), get_port_list(), hash(), hashtable_hash_str(), identification_create_from_string(), imv_attestation_process(), load_entries(), load_from_stream(), load_secret(), main(), METHOD(), ntru_ke_create(), parse_ec_identifier(), parse_public_key(), send_op(), send_sasl_mechs(), soap_init(), START_SETUP(), START_TEST(), swid_error_create(), tnc_pdp_create(), tnccs_reason_strings_msg_create_from_node(), and write_ec_identifier().
#define chunk_from_thing (thing) chunk_create((u_char*)&(thing), sizeof(thing))
Initialize a chunk to point to a thing
Definition at line 231 of file chunk.h.
Referenced by add_auth_lifetime(), add_ike_sa_parameters(), add_initial_contact(), add_ipcomp_notify(), addr2ts(), append_header(), append_header_frag(), bench_aead(), bench_crypter(), bench_signer(), build_natd_payload(), build_notification_data(), build_signature(), build_signature_auth_data(), CALLBACK(), cookie_build(), cookie_verify(), create_ack(), create_cert(), create_cert_ext(), create_h(), create_icv(), crypt(), crypt_data(), crypt_icv(), decrypt_mppe_key(), derive_master(), drop_ike_sa_init(), eap_radius_build_attributes(), gctr(), generate(), generate_iv(), generate_natd_hash(), get_init_hash(), get_route(), handle_ack(), handle_offer(), hash(), hash_challenge(), hash_data(), hash_id(), hash_in(), hash_out(), hash_reqid(), hash_reqid_by_ts(), hash_sa(), hash_trap(), hashtable_hash_ptr(), ip_packet_create(), ip_packet_create_from_data(), ip_packet_create_udp_from_data(), ipsec_sa_hash(), load_entries(), main(), manage_ipaddr(), manage_rule(), METHOD(), p_hash(), parse_message(), pbkdf2(), plugin_feature_hash(), policy_hash(), prf_plus_create(), print_host(), process_client_hello(), process_ec_key_exchange(), process_finished(), process_key_exchange_dhe(), process_key_exchange_encrypted(), process_modp_key_exchange(), process_server_hello(), proposal_substructure_create_for_ipcomp_v1(), pseudo_header_checksum(), query_hash(), rdrand_mixed(), receive_casts(), route_entry_hash(), scep_build_request(), send_client_hello(), send_finished(), send_interim(), send_key_exchange_dhe(), send_key_exchange_encrypt(), send_notify(), send_server_hello(), send_server_key_exchange(), send_start(), send_stop(), set_data(), spi_hash(), START_SETUP(), START_TEST(), and transform_attribute_create_value().
Typedef Documentation
typedef struct chunk_t chunk_t
Definition at line 35 of file chunk.h.
Function Documentation
static void chunk_clear (chunk_t * chunk) inline static
Overwrite the contents of a chunk and free it
Definition at line 214 of file chunk.h.
References chunk_free(), chunk_t::len, memwipe(), and chunk_t::ptr.
Referenced by add_key(), asn1_wrap(), attr2string(), CALLBACK(), challenge(), ChallengeResponse(), chunk_create_cat(), compute_prime(), create_aead(), create_generic(), decrypt_private_key(), derive_ike_aead(), derive_ike_traditional(), do_write(), encode_ecdsa(), entry_destroy(), expand_skeyid_e(), fingerprint_ecdsa(), generate(), generate_key_pair_ecp(), get_nt_hash(), gmp_rsa_private_key_gen(), install(), load_from_blob(), load_key_anytype(), load_pin(), load_secret(), METHOD(), ntru_drbg_create(), ntru_private_key_create(), pem_encoder_encode(), process_challenge(), process_child_add(), process_key_exchange_dhe(), process_key_exchange_encrypted(), process_peer_challenge(), process_reauthentication(), process_server_response(), rng_allocate_bytes_not_zero(), select_and_install(), send_key_exchange_dhe(), and START_TEST().
 {
     if (chunk->ptr)
     {
         memwipe(chunk->ptr, chunk->len);
         chunk_free(chunk);
     }
 }
int chunk_compare (chunk_t a, chunk_t b)
Compare two chunks, returns zero if a equals b or negative/positive if a is small/greater than b
Described in header.
Definition at line 719 of file chunk.c.
References if(), chunk_t::len, len, and chunk_t::ptr.
Referenced by crl_is_newer(), have_vips_from_pool(), and START_TEST().
 {
     int compare_len = a.len - b.len;
     int len = (compare_len < 0)? a.len : b.len;
     if (compare_len != 0 || len == 0)
     {
         return compare_len;
     }
     return memcmp(a.ptr, b.ptr, len);
 };
static chunk_t chunk_create (u_char * ptr, size_t len) inline static
Create a new chunk pointing to "ptr" with length "len"
Definition at line 57 of file chunk.h.
Referenced by acert(), add_eap_identity(), asn1_oid_from_string(), assess(), attack_aeads(), attack_signers(), attr_enum_filter(), bench_aead(), bench_prf(), build(), build_pkt(), burn_aead(), CALLBACK(), cert_payload_create_from_hash_and_url(), challenge(), check_boot_aggregate(), chunk_create_cat(), chunk_from_base64(), chunk_from_fd(), chunk_from_hex(), chunk_map(), chunk_to_base32(), chunk_to_base64(), chunk_to_hex(), collect_tags(), create_client_error(), create_h(), create_secret(), create_sid(), create_ts(), crypt_ctr(), curl_cb(), decode_list(), decode_section(), decrypt_and_extract(), decrypt_content(), decrypt_mppe_key(), derive_key(), do_args(), do_netstat(), email_matches(), encode_base64(), encode_ecdsa(), encode_rsa(), encrypt_content(), encrypt_mppe_key(), expand_keys(), expand_skeyid_e(), extract_platform_info(), extract_username(), filter_chunks(), final(), finalize_message(), find_certificates(), find_pubkey_in_certs(), fqdn_matches(), gen_identity(), generate(), GenerateMSK(), get_attributes(), get_cert_hash(), get_identity_attribute(), get_ts_from_range(), get_ts_from_subnet(), get_vid_data(), handle_event(), handle_message(), handle_offer(), hash(), hash_file(), hash_match(), hash_password(), id_payload_create_from_ts(), identification_create_from_sockaddr(), ima_hash(), imc_imv_msg_create_from_node(), initiate_connection(), is_known_vid(), issue(), load_certs(), load_from_smartcard(), load_issuer_cert(), load_issuer_key(), load_pin(), load_tester_creds_create(), main(), mem_pool_create_range(), METHOD(), net_change_hash(), openssl_asn1_obj2chunk(), openssl_asn1_str2chunk(), p_hash(), parse_attributes(), parse_public_key(), parse_route(), parse_token(), passphrase_cb(), pem_encoder_encode(), pgp_read_mpi(), pgp_read_packet(), pin_cb(), pkcs11_creds_load(), pkcs12_kdf(), plugin_feature_hash(), print_value(), process(), process_challenge(), process_eap(), process_peer_challenge(), process_peer_failure(), process_peer_success(), process_reauthentication(), process_route(), process_server_response(), process_server_retry(), pts_file_meas_create_from_path(), pts_ima_bios_list_create(), pub(), query_hash(), radius_config_create(), radius_receive(), read_data_internal(), read_from_stream(), read_key(), read_result(), read_string(), read_swid_tag_ids(), read_swid_tags(), read_tls(), reauthenticate(), receive(), receive_arp(), receive_packet(), receive_response(), req(), scep_build_request(), selector2ts(), self(), send_interim(), send_once(), send_response(), send_start(), send_stop(), session_hash(), setup_tunnel(), sign_bliss(), sign_crl(), simaka_message_create(), soup_cb(), START_TEST(), status_attr(), step3(), TNC_IMC_ReceiveMessage(), TNC_IMC_ReceiveMessageLong(), TNC_IMV_ReceiveMessage(), TNC_IMV_ReceiveMessageLong(), update(), vadd_kv_or_li(), verify_bliss(), verify_emsa_pkcs1_signature(), vici_add_key_value(), vici_add_list_item(), x509_build_crlDistributionPoints(), and xfrm2host().
 {
     chunk_t chunk = {ptr, len};
     return chunk;
 }
chunk_t chunk_create_cat (u_char * ptr, const char * mode, ...)
Concatenate chunks into a chunk pointing to "ptr".
The mode string specifies the number of chunks, and how to handle each of them with a single character: 'c' for copy (allocate new chunk), 'm' for move (free given chunk) or 's' for sensitive-move (clear given chunk, then free).
Described in header.
Definition at line 87 of file chunk.c.
References chunk_clear(), chunk_create(), FALSE, free(), chunk_t::len, memcpy, chunk_t::ptr, and TRUE.
 {
     va_list chunks;
     chunk_t construct = chunk_create(ptr, 0);
     va_start(chunks, mode);
     while (TRUE)
     {
         bool free_chunk = FALSE, clear_chunk = FALSE;
         chunk_t ch;
         switch (*mode++)
         {
             case 's':
                 clear_chunk = TRUE;
                 /* FALL */
             case 'm':
                 free_chunk = TRUE;
                 /* FALL */
             case 'c':
                 ch = va_arg(chunks, chunk_t);
                 memcpy(ptr, ch.ptr, ch.len);
                 ptr += ch.len;
                 construct.len += ch.len;
                 if (clear_chunk)
                 {
                     chunk_clear(&ch);
                 }
                 else if (free_chunk)
                 {
                     free(ch.ptr);
                 }
                 continue;
             default:
                 break;
         }
         break;
     }
     va_end(chunks);
     return construct;
 }
chunk_t chunk_create_clone (u_char * ptr, chunk_t chunk)
Create a clone of a chunk pointing to "ptr"
Described in header.
Definition at line 40 of file chunk.c.
References chunk_empty, chunk_t::len, memcpy, and chunk_t::ptr.
Referenced by tnccs_reason_strings_msg_create().
 {
     chunk_t clone = chunk_empty;
     if (chunk.ptr && chunk.len > 0)
     {
         clone.ptr = ptr;
         clone.len = chunk.len;
         memcpy(clone.ptr, chunk.ptr, chunk.len);
     }
     return clone;
 }
static bool chunk_equals (chunk_t a, chunk_t b) inline static
Compare two chunks for equality, NULL chunks are never equal.
Definition at line 306 of file chunk.h.
References chunk_t::len, memeq(), and chunk_t::ptr.
Referenced by add(), assert_reader_after_read(), CALLBACK(), check_and_put_init_hash(), chunk_equals_ptr(), collect_tags(), compare_dn(), compare_vici(), decode_list(), decode_section(), dn_matches(), do_memxor(), email_matches(), equals(), equals_entry(), fqdn_matches(), get_better_crl(), has_no_any_policy(), has_policy(), insert_file_hash(), is_known_vid(), is_policy_valid(), match_checklist_by_id(), mem_pool_create_range(), METHOD(), parse_certificate(), parse_crl(), parse_ec_identifier(), parse_public_key(), pin_cb(), prepare_dhcp(), private_key_belongs_to(), private_key_equals(), private_key_has_fingerprint(), process(), process_payloads(), process_server_hello(), process_start(), public_key_equals(), public_key_has_fingerprint(), put_half_open(), receive_msg(), remove_half_open(), remove_init_hash(), route_entry_equals(), scep_parse_response(), shared_entry_equals(), START_TEST(), and verify_address().
 {
     return a.ptr != NULL  && b.ptr != NULL &&
             a.len == b.len && memeq(a.ptr, b.ptr, a.len);
 }
static bool chunk_equals_const (chunk_t a, chunk_t b) inline static
Compare two chunks for equality, constant time for cryptographic purposes.
Note that this function is constant time only for chunks with the same length, i.e. it does not protect against guessing the length of one of the chunks.
Definition at line 319 of file chunk.h.
References chunk_t::len, memeq_const(), and chunk_t::ptr.
Referenced by CALLBACK(), check_boot_aggregate(), cookie_verify(), imv_attestation_process(), METHOD(), process_challenge(), process_finished(), process_peer_success(), process_reauthentication(), START_TEST(), verify_auth(), verify_emsa_pkcs1_signature(), and verify_mac().
 {
     return a.ptr != NULL  && b.ptr != NULL &&
             a.len == b.len && memeq_const(a.ptr, b.ptr, a.len);
 }
static bool chunk_equals_ptr (chunk_t * a, chunk_t * b) inline static
Compare two chunks (given as pointers) for equality (useful as callback), NULL chunks are never equal.
Definition at line 329 of file chunk.h.
References chunk_equals().
Referenced by tkm_chunk_map_create().
 {
     return a != NULL && b != NULL && chunk_equals(*a, *b);
 }
static void chunk_free (chunk_t * chunk) inline static
Free contents of a chunk
Definition at line 205 of file chunk.h.
References chunk_empty, free(), and chunk_t::ptr.
Referenced by acert(), add_cert(), add_certification_state(), add_configuration_state(), add_settings(), AuthenticatorResponse(), bench_dh(), build_auth(), build_cert_chain(), build_cert_payload(), build_cookie(), build_curve_signature(), build_emsa_pkcs1_signature(), build_natd_payload(), build_pub(), build_requestList(), build_signature(), callback_data_destroy(), check_destroy(), check_list_destroy(), chunk_clear(), cookie_verify(), create_ecp(), decrypt_generic(), decrypt_private_key(), derive_secret(), dn(), dntoa(), do_test_mct(), drop_ike_sa_init(), entry_destroy(), fetch_crl(), fetch_ocsp(), find_key_by_keyid(), fragment_destroy(), generate(), generate_iv(), generate_key_pair(), generate_message(), generate_natd_hash(), GenerateStuff(), get_next_test_vector(), get_ts_from_subnet(), gmp_rsa_private_key_gen(), half_open_destroy(), hash_pubkey(), identification_printf_hook(), imv_attestation_process(), ip_packet_create(), ip_packet_create_udp_from_data(), ipseckey_create_frm_rr(), iv_data_destroy(), load_from_stream(), main(), METHOD(), METHOD2(), ntru_drbg_create(), ntru_private_key_create(), openssl_bn2chunk(), openssl_bn_cat(), openssl_hash_chunk(), openssl_rsa_fingerprint(), parse_attributes(), parse_authenticated_safe(), parse_PFX(), parse_public_key(), pem_decrypt(), pkcs11_public_key_load(), process_handshake(), process_payloads(), process_peer_failure(), process_peer_success(), process_server_response(), process_server_retry(), qm_data_destroy(), rebuild_auth(), remove_padding(), route_entry_destroy(), run_test(), save_state(), send_response(), sign_classic(), sign_pkcs1(), sign_raw(), sign_signature_auth(), START_TEST(), test_vector_free(), verify_auth(), verify_curve_signature(), verify_pkcs1(), and verify_raw().
 {
     free(chunk->ptr);
     *chunk = chunk_empty;
 }
chunk_t chunk_from_base64 (chunk_t base64, char * buf)
Convert a base64 in a binary chunk.
If buf is supplied, it must hold at least (base64.len / 4 * 3).
Parameters
base64 base64 encoded input data
buf buffer to write decoded data, NULL to malloc
Returns
converted data
Described in header.
Definition at line 623 of file chunk.c.
References b642bin(), chunk_create(), chunk_t::len, len, malloc(), and chunk_t::ptr.
Referenced by decode_base64(), extract_secret(), load_from_stream(), load_secret(), METHOD(), pem_to_bin(), and START_TEST().
 {
     u_char *pos, byte[4];
     int i, j, len, outlen;
     len = base64.len / 4 * 3;
     if (!buf)
     {
         buf = malloc(len);
     }
     pos = base64.ptr;
     outlen = 0;
     for (i = 0; i < len; i+=3)
     {
         outlen += 3;
         for (j = 0; j < 4; j++)
         {
             if (*pos == '=')
             {
                 outlen--;
             }
             byte[j] = b642bin(*pos++);
         }
         buf[i] = (byte[0] << 2) | (byte[1] >> 4);
         buf[i+1] = (byte[1] << 4) | (byte[2] >> 2);
         buf[i+2] = (byte[2] << 6) | (byte[3]);
     }
     return chunk_create(buf, outlen);
 }
bool chunk_from_fd (int fd, chunk_t * out)
Store data read from FD into a chunk
On error, errno is set appropriately.
Parameters
fd file descriptor to read from
chunk chunk receiving allocated buffer
Returns
TRUE if successful, FALSE on failure
Described in header.
Definition at line 256 of file chunk.c.
References chunk_create(), FALSE, free(), len, malloc(), read, recv, and TRUE.
Referenced by acert(), chunk_map(), dn(), issue(), keyid(), pkcs12(), print(), pub(), req(), self(), START_TEST(), and verify().
 {
     struct stat sb;
     char *buf, *tmp;
     ssize_t len, total = 0, bufsize;
     if (fstat(fd, &sb) == 0 && S_ISREG(sb.st_mode))
     {
         bufsize = sb.st_size;
     }
     else
     {
         bufsize = 256;
     }
     buf = malloc(bufsize);
     if (!buf)
     {   /* for huge files */
         return FALSE;
     }
     while (TRUE)
     {
         len = read(fd, buf + total, bufsize - total);
 #ifdef WIN32
         if (len == -1 && errno == EBADF)
         {   /* operating on a Winsock socket? */
             len = recv(fd, buf + total, bufsize - total, 0);
         }
 #endif
         if (len < 0)
         {
             free(buf);
             return FALSE;
         }
         if (len == 0)
         {
             break;
         }
         total += len;
         if (total == bufsize)
         {
             bufsize *= 2;
             tmp = realloc(buf, bufsize);
             if (!tmp)
             {
                 free(buf);
                 return FALSE;
             }
             buf = tmp;
         }
     }
     if (total == 0)
     {
         free(buf);
         buf = NULL;
     }
     else if (total < bufsize)
     {
         buf = realloc(buf, total);
     }
     *out = chunk_create(buf, total);
     return TRUE;
 }
chunk_t chunk_from_hex (chunk_t hex, char * buf)
Convert a hex encoded in a binary chunk.
If buf is supplied, it must hold at least (hex.len / 2) + (hex.len % 2) bytes. It is filled by the right to give correct values for short inputs.
Parameters
hex hex encoded input data
buf buffer to write decoded data, NULL to malloc
Returns
converted data
Described in header.
Definition at line 501 of file chunk.c.
References chunk_create(), FALSE, hex2bin(), chunk_t::len, len, malloc(), memset, chunk_t::ptr, and TRUE.
Referenced by acert(), add_certification_state(), add_configuration_state(), add_quadruple(), create_from_string_with_num_type(), create_from_string_with_prefix_type(), do_args(), extract_secret(), get_next_test_vector(), identification_create_from_string(), issue(), load_from_smartcard(), load_pin(), load_secret(), METHOD(), parse_attributes(), parse_token(), pem_to_bin(), process_peer_failure(), process_peer_success(), pub(), self(), sign_crl(), and START_TEST().
 {
     int i, len;
     u_char *ptr;
     bool odd = FALSE;
    /* subtract the number of optional ':' separation characters */
     len = hex.len;
     ptr = hex.ptr;
     for (i = 0; i < hex.len; i++)
     {
         if (*ptr++ == ':')
         {
             len--;
         }
     }
     /* compute the number of binary bytes */
     if (len % 2)
     {
         odd = TRUE;
         len++;
     }
     len /= 2;
     /* allocate buffer memory unless provided by caller */
     if (!buf)
     {
         buf = malloc(len);
     }
     /* buffer is filled from the right */
     memset(buf, 0, len);
     hex.ptr += hex.len;
     for (i = len - 1; i >= 0; i--)
     {
         /* skip separation characters */
         if (*(--hex.ptr) == ':')
         {
             --hex.ptr;
         }
         buf[i] = hex2bin(*hex.ptr);
         if (i > 0 || !odd)
         {
             buf[i] |= hex2bin(*(--hex.ptr)) << 4;
         }
     }
     return chunk_create(buf, len);
 }
u_int32_t chunk_hash (chunk_t chunk)
Computes a 32 bit hash of the given chunk.
Note
The output of this function is randomized, that is, it will only produce the same output for the same input when calling it from the same process. For a more predictable hash function use chunk_hash_static() instead.
This hash is only intended for hash tables not for cryptographic purposes.
Parameters
chunk data to hash
Returns
hash value
Described in header.
Definition at line 969 of file chunk.c.
References chunk_mac(), and key.
Referenced by addr_map_entry_hash(), build_natd_payload(), check_and_put_init_hash(), get_message_id_or_hash(), hash(), hash_id(), hash_id_host(), hash_in(), hash_match(), hash_out(), hash_reqid(), hash_reqid_by_ts(), hash_sa(), hash_trap(), hashtable_hash_ptr(), hashtable_hash_str(), id_hash(), ipsec_sa_hash(), METHOD(), net_change_hash(), plugin_feature_hash(), policy_hash(), put_connected_peers(), put_half_open(), query_hash(), remove_connected_peers(), remove_half_open(), remove_init_hash(), route_entry_hash(), session_hash(), spi_hash(), START_TEST(), and tun_entry_hash().
 {
     return chunk_mac(chunk, key);
 }
u_int32_t chunk_hash_inc (chunk_t chunk, u_int32_t hash)
Incremental version of chunk_hash. Use this to hash two or more chunks.
Parameters
chunk data to hash
hash previous hash value
Returns
hash value
Described in header.
Definition at line 960 of file chunk.c.
References chunk_mac_inc(), and key.
Referenced by hash(), hash_addr(), hash_id_host(), hash_in(), hash_out(), hash_reqid(), hash_reqid_by_ts(), hash_route(), hash_sa(), ipsec_sa_hash(), METHOD(), plugin_feature_hash(), policy_hash(), put_connected_peers(), query_hash(), remove_connected_peers(), route_entry_hash(), and START_TEST().
 {
     /* we could use a mac of the previous hash, but this is faster */
     return chunk_mac_inc(chunk, key, ((u_int64_t)hash) << 32 | hash);
 }
void chunk_hash_seed ()
Seed initial key for chunk_hash().
This call should get invoked once during startup. This is usually done by calling library_init(). Calling it multiple times is safe, it gets executed just once.
See header
Definition at line 918 of file chunk.c.
References close, FALSE, key, len, random, read, srandom, and TRUE.
Referenced by library_init(), and testable_function_register().
 {
     static bool seeded = FALSE;
     ssize_t len;
     size_t done = 0;
     int fd;
     if (seeded)
     {
         /* just once to have the same seed during the whole process lifetimes */
         return;
     }
     fd = open("/dev/urandom", O_RDONLY);
     if (fd >= 0)
     {
         while (done < sizeof(key))
         {
             len = read(fd, key + done, sizeof(key) - done);
             if (len < 0)
             {
                 break;
             }
             done += len;
         }
         close(fd);
     }
     /* on error we use random() to generate the key (better than nothing) */
     if (done < sizeof(key))
     {
         srandom(time(NULL) + getpid());
         for (; done < sizeof(key); done++)
         {
             key[done] = (u_char)random();
         }
     }
     seeded = TRUE;
 }
u_int32_t chunk_hash_static (chunk_t chunk)
Computes a 32 bit hash of the given chunk.
Compared to chunk_hash() this will always calculate the same output for the same input. Therefore, it should not be used for hash tables (to prevent hash flooding).
Note
This hash is not intended for cryptographic purposes.
Parameters
chunk data to hash
Returns
hash value
Described in header.
Definition at line 985 of file chunk.c.
References chunk_mac(), and static_key.
Referenced by METHOD(), prepare_dhcp(), and START_TEST().
 {
     return chunk_mac(chunk, static_key);
 }
u_int32_t chunk_hash_static_inc (chunk_t chunk, u_int32_t hash)
Incremental version of chunk_hash_static(). Use this to hash two or more chunks in a predictable way.
Parameters
chunk data to hash
hash previous hash value
Returns
hash value
Described in header.
Definition at line 977 of file chunk.c.
References chunk_mac_inc(), and static_key.
Referenced by START_TEST().
 {   /* we could use a mac of the previous hash, but this is faster */
     return chunk_mac_inc(chunk, static_key, ((u_int64_t)hash) << 32 | hash);
 }
bool chunk_increment (chunk_t chunk)
Increment a chunk, as it would reprensent a network order integer.
Parameters
chunk chunk to increment
Returns
TRUE if an overflow occurred
Described in header.
Definition at line 735 of file chunk.c.
References FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by add(), crypt(), crypt_ctr(), crypt_data(), gctr(), METHOD(), resize(), sign_crl(), and START_TEST().
 {
     int i;
     for (i = chunk.len - 1; i >= 0; i--)
     {
         if (++chunk.ptr[i] != 0)
         {
             return FALSE;
         }
     }
     return TRUE;
 }
u_int16_t chunk_internet_checksum (chunk_t data)
Calculate the Internet Checksum according to RFC 1071 for the given chunk.
If the result is used with chunk_internet_checksum_inc() and the data length is not a multiple of 16 bit the checksum bytes have to be swapped to compensate the even/odd alignment.
Parameters
data data to process
Returns
checksum (one's complement, network order)
Described in header.
Definition at line 1016 of file chunk.c.
References chunk_internet_checksum_inc().
Referenced by ip_packet_create_from_data(), pseudo_header_checksum(), and START_TEST().
 {
     return chunk_internet_checksum_inc(data, 0xffff);
 }
u_int16_t chunk_internet_checksum_inc (chunk_t data, u_int16_t checksum)
Extend the given Internet Checksum (one's complement, in network byte order) with the given data.
If data is not a multiple of 16 bits the checksum may have to be swapped to compensate even/odd alignment (see chunk_internet_checksum()).
Parameters
data data to process
checksum previous checksum (one's complement, network order)
Returns
checksum (one's complement, network order)
Described in header.
Definition at line 993 of file chunk.c.
References chunk_skip(), chunk_t::len, chunk_t::ptr, and untoh16().
Referenced by chunk_internet_checksum(), fix_transport_header(), and START_TEST().
 {
     u_int32_t sum = ntohs((u_int16_t)~checksum);
     while (data.len > 1)
     {
         sum += untoh16(data.ptr);
         data = chunk_skip(data, 2);
     }
     if (data.len)
     {
         sum += (u_int16_t)*data.ptr << 8;
     }
     while (sum >> 16)
     {
         sum = (sum & 0xffff) + (sum >> 16);
     }
     return htons(~sum);
 }
size_t chunk_length (const char * mode, ...)
Calculate length of multiple chunks
Described in header.
Definition at line 57 of file chunk.c.
References chunk_t::len, length, and TRUE.
Referenced by START_TEST().
 {
     va_list chunks;
     size_t length = 0;
     va_start(chunks, mode);
     while (TRUE)
     {
         switch (*mode++)
         {
             case 'm':
             case 'c':
             case 's':
             {
                 chunk_t ch = va_arg(chunks, chunk_t);
                 length += ch.len;
                 continue;
             }
             default:
                 break;
         }
         break;
     }
     va_end(chunks);
     return length;
 }
u_int64_t chunk_mac (chunk_t chunk, u_char * key)
Computes a quick MAC from the given chunk and key using SipHash.
The key must have a length of 128-bit (16 bytes).
Note
While SipHash has strong features using it for cryptographic purposes is not recommended (in particular because of the rather short output size).
Parameters
chunk data to process
key key to use
Returns
MAC for given input and key
Described in header.
Definition at line 899 of file chunk.c.
References chunk_mac_inc().
Referenced by chunk_hash(), chunk_hash_static(), and START_TEST().
 {
     return chunk_mac_inc(chunk, key, 0);
 }
chunk_t* chunk_map (char * path, bool wr)
mmap() a file to a chunk
The returned chunk structure is allocated from heap, but it must be freed through chunk_unmap(). A user may alter the chunk ptr or len, but must pass the chunk pointer returned from chunk_map() to chunk_unmap() after use.
On error, errno is set appropriately.
Parameters
path path of file to map
wr TRUE to sync writes to disk
Returns
mapped chunk, NULL on error
See header.
Definition at line 339 of file chunk.c.
References chunk_create(), chunk_from_fd(), chunk_unmap(), mmaped_chunk_t::fd, flags, free(), INIT, chunk_t::len, mmaped_chunk_t::len, mmaped_chunk_t::map, chunk_t::ptr, and mmaped_chunk_t::public.
Referenced by add_file_key_value(), add_file_list_key(), add_radius_attribute(), collect_tags(), load_aik_blob(), load_certs(), load_containers(), load_from_file(), load_imcvs_from_config(), load_keys(), load_secrets(), METHOD(), START_TEST(), and tkm_deinit().
 {
     mmaped_chunk_t *chunk;
     struct stat sb;
     int tmp, flags;
     flags = wr ? O_RDWR : O_RDONLY;
 #ifdef WIN32
     flags |= O_BINARY;
 #endif
     INIT(chunk,
         .fd = open(path, flags),
         .wr = wr,
     );
     if (chunk->fd == -1)
     {
         free(chunk);
         return NULL;
     }
     if (fstat(chunk->fd, &sb) == -1)
     {
         tmp = errno;
         chunk_unmap(&chunk->public);
         errno = tmp;
         return NULL;
     }
 #ifdef HAVE_MMAP
     chunk->len = sb.st_size;
     /* map non-empty files only, as mmap() complains otherwise */
     if (chunk->len)
     {
         /* in read-only mode, we allow writes, but don't sync to disk */
         chunk->map = mmap(NULL, chunk->len, PROT_READ | PROT_WRITE,
                           wr ? MAP_SHARED : MAP_PRIVATE, chunk->fd, 0);
         if (chunk->map == MAP_FAILED)
         {
             tmp = errno;
             chunk_unmap(&chunk->public);
             errno = tmp;
             return NULL;
         }
     }
     chunk->public = chunk_create(chunk->map, chunk->len);
 #else /* !HAVE_MMAP */
     if (!chunk_from_fd(chunk->fd, &chunk->public))
     {
         tmp = errno;
         chunk_unmap(&chunk->public);
         errno = tmp;
         return NULL;
     }
     chunk->map = chunk->public.ptr;
     chunk->len = chunk->public.len;
 #endif /* !HAVE_MMAP */
     return &chunk->public;
 }
bool chunk_printable (chunk_t chunk, chunk_t * sane, char replace)
Check if a chunk has printable characters only.
If sane is given, chunk is cloned into sane and all non printable characters get replaced by "replace".
Parameters
chunk chunk to check for printability
sane pointer where sane version is allocated, or NULL
replace character to use for replaceing unprintable characters
Returns
TRUE if all characters in chunk are printable
Remove non-printable characters from a chunk.
Definition at line 752 of file chunk.c.
References chunk_clone, FALSE, chunk_t::len, printable, chunk_t::ptr, replace, and TRUE.
Referenced by attr2string(), attr_filter(), CALLBACK(), dntoa(), identification_printf_hook(), METHOD(), parse_certificatePolicies(), print_radius_attributes(), START_TEST(), vici_parse_value_str(), and vici_stringify().
 {
     bool printable = TRUE;
     int i;
     if (sane)
     {
         *sane = chunk_clone(chunk);
     }
     for (i = 0; i < chunk.len; i++)
     {
         if (!isprint(chunk.ptr[i]))
         {
             if (sane)
             {
                 sane->ptr[i] = replace;
             }
             printable = FALSE;
         }
     }
     return printable;
 }
int chunk_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook function for chunk_t.
Arguments are: chunk_t *chunk Use #-modifier to print a compact version Use +-modifier to print a compact version without separator
Described in header.
Definition at line 1024 of file chunk.c.
References copy(), FALSE, printf_hook_spec_t::hash, chunk_t::len, mem_printf_hook(), printf_hook_spec_t::plus, print_in_hook(), chunk_t::ptr, and TRUE.
Referenced by library_init().
 {
     chunk_t *chunk = *((chunk_t**)(args[0]));
     bool first = TRUE;
     chunk_t copy = *chunk;
     int written = 0;
     if (!spec->hash && !spec->plus)
     {
         u_int chunk_len = chunk->len;
         const void *new_args[] = {&chunk->ptr, &chunk_len};
         return mem_printf_hook(data, spec, new_args);
     }
     while (copy.len > 0)
     {
         if (first)
         {
             first = FALSE;
         }
         else if (!spec->plus)
         {
             written += print_in_hook(data, ":");
         }
         written += print_in_hook(data, "%02x", *copy.ptr++);
         copy.len--;
     }
     return written;
 }
static chunk_t chunk_skip (chunk_t chunk, size_t bytes) inline static
Skip n bytes in chunk (forward pointer, shorten length)
Definition at line 271 of file chunk.h.
References bytes, chunk_empty, chunk_t::len, and chunk_t::ptr.
Referenced by asn1_oid_to_string(), asn1_unwrap(), bliss_private_key_load(), bliss_public_key_from_asn1(), build_pub(), build_v3_fingerprint(), chunk_internet_checksum_inc(), chunk_split(), crypt_ctr(), crypt_data(), derive_key(), email_matches(), expand_keys(), extract_secret(), find_boundary(), fqdn_matches(), gcrypt_rsa_find_token(), gctr(), generate_key_pair_ecp(), get_ts_from_range(), get_ts_from_subnet(), ghash(), host2offset(), ike2queue(), ip_packet_create(), ip_packet_create_from_data(), load_secrets(), main(), METHOD(), parse(), parse_attributes(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_crlNumber_ext(), parse_ecdsa_public_key(), parse_keyUsage(), parse_public_key(), parse_rsa_public_key(), parse_signature_auth_data(), parse_subjectKeyIdentifier_ext(), parse_subnets(), pgp_old_packet_length(), pgp_read_mpi(), pgp_read_packet(), pgp_read_scalar(), pkcs11_public_key_load(), present(), print_radius_attributes(), process_challenge(), process_ec_key_exchange(), process_key_exchange_dhe(), process_start(), process_tnc_msg(), queue2radius(), rdrand_chunk(), rdrand_mixed(), read_byte(), read_string(), read_uint32(), rebuild_auth(), send_response(), START_TEST(), update(), verify_der_signature(), and verify_emsa_pkcs1_signature().
 {
     if (chunk.len > bytes)
     {
         chunk.ptr += bytes;
         chunk.len -= bytes;
         return chunk;
     }
     return chunk_empty;
 }
static chunk_t chunk_skip_zero (chunk_t chunk) inline static
Skip a leading zero-valued byte
Definition at line 285 of file chunk.h.
References chunk_t::len, and chunk_t::ptr.
Referenced by build_public_key(), encode_rsa(), METHOD(), print_ac(), print_crl(), print_x509(), sign_crl(), START_TEST(), stroke_list_acerts(), stroke_list_certs(), and stroke_list_crls().
 {
     if (chunk.len > 1 && *chunk.ptr == 0x00)
     {
         chunk.ptr++;
         chunk.len--;
     }
     return chunk;
 }
void chunk_split (chunk_t chunk, const char * mode, ...)
Split up a chunk into parts, "mode" is a string of "a" (alloc), "c" (copy) and "m" (move). Each letter say for the corresponding chunk if it should get allocated on heap, copied into existing chunk, or the chunk should point into "chunk". The length of each part is an argument before each target chunk. E.g.: chunk_split(chunk, "mcac", 3, &a, 7, &b, 5, &c, d.len, &d);
Described in header.
Definition at line 133 of file chunk.c.
References chunk_skip(), chunk_t::len, len, malloc(), memcpy, min, chunk_t::ptr, and TRUE.
Referenced by ChallengeResponse(), METHOD(), and START_TEST().
 {
     va_list chunks;
     u_int len;
     chunk_t *ch;
     va_start(chunks, mode);
     while (TRUE)
     {
         if (*mode == '\0')
         {
             break;
         }
         len = va_arg(chunks, u_int);
         ch = va_arg(chunks, chunk_t*);
         /* a null chunk means skip len bytes */
         if (ch == NULL)
         {
             chunk = chunk_skip(chunk, len);
             continue;
         }
         switch (*mode++)
         {
             case 'm':
             {
                 ch->len = min(chunk.len, len);
                 if (ch->len)
                 {
                     ch->ptr = chunk.ptr;
                 }
                 else
                 {
                     ch->ptr = NULL;
                 }
                 chunk = chunk_skip(chunk, ch->len);
                 continue;
             }
             case 'a':
             {
                 ch->len = min(chunk.len, len);
                 if (ch->len)
                 {
                     ch->ptr = malloc(ch->len);
                     memcpy(ch->ptr, chunk.ptr, ch->len);
                 }
                 else
                 {
                     ch->ptr = NULL;
                 }
                 chunk = chunk_skip(chunk, ch->len);
                 continue;
             }
             case 'c':
             {
                 ch->len = min(ch->len, chunk.len);
                 ch->len = min(ch->len, len);
                 if (ch->len)
                 {
                     memcpy(ch->ptr, chunk.ptr, ch->len);
                 }
                 else
                 {
                     ch->ptr = NULL;
                 }
                 chunk = chunk_skip(chunk, ch->len);
                 continue;
             }
             default:
                 break;
         }
         break;
     }
     va_end(chunks);
 }
chunk_t chunk_to_base32 (chunk_t chunk, char * buf)
Convert a chunk of data to its base32 encoding.
The resulting string is '\0' terminated, but the chunk does not include the '\0'. If buf is supplied, it must hold (chunk.len * 8 / 5 + 1) bytes.
Parameters
chunk data to convert
buf buffer to write to, NULL to malloc
Returns
chunk of encoded data
Described in header.
Definition at line 659 of file chunk.c.
References b32digits, chunk_create(), chunk_t::len, len, malloc(), memset, and chunk_t::ptr.
Referenced by START_TEST().
 {
     int i, len;
     char *pos;
     len = chunk.len + ((5 - chunk.len % 5) % 5);
     if (!buf)
     {
         buf = malloc(len * 8 / 5 + 1);
     }
     pos = buf;
     for (i = 0; i < len; i+=5)
     {
         *pos++ = b32digits[chunk.ptr[i] >> 3];
         if (i+1 >= chunk.len)
         {
             *pos++ = b32digits[(chunk.ptr[i] & 0x07) << 2];
             memset(pos, '=', 6);
             pos += 6;
             break;
         }
         *pos++ = b32digits[((chunk.ptr[i] & 0x07) << 2) |
                            (chunk.ptr[i+1] >> 6)];
         *pos++ = b32digits[(chunk.ptr[i+1] & 0x3E) >> 1];
         if (i+2 >= chunk.len)
         {
             *pos++ = b32digits[(chunk.ptr[i+1] & 0x01) << 4];
             memset(pos, '=', 4);
             pos += 4;
             break;
         }
         *pos++ = b32digits[((chunk.ptr[i+1] & 0x01) << 4) |
                            (chunk.ptr[i+2] >> 4)];
         if (i+3 >= chunk.len)
         {
             *pos++ = b32digits[(chunk.ptr[i+2] & 0x0F) << 1];
             memset(pos, '=', 3);
             pos += 3;
             break;
         }
         *pos++ = b32digits[((chunk.ptr[i+2] & 0x0F) << 1) |
                            (chunk.ptr[i+3] >> 7)];
         *pos++ = b32digits[(chunk.ptr[i+3] & 0x7F) >> 2];
         if (i+4 >= chunk.len)
         {
             *pos++ = b32digits[(chunk.ptr[i+3] & 0x03) << 3];
             *pos++ = '=';
             break;
         }
         *pos++ = b32digits[((chunk.ptr[i+3] & 0x03) << 3) |
                            (chunk.ptr[i+4] >> 5)];
         *pos++ = b32digits[chunk.ptr[i+4] & 0x1F];
     }
     *pos = '\0';
     return chunk_create(buf, len * 8 / 5);
 }
chunk_t chunk_to_base64 (chunk_t chunk, char * buf)
Convert a chunk of data to its base64 encoding.
The resulting string is '\0' terminated, but the chunk does not include the '\0'. If buf is supplied, it must hold at least (chunk.len * 4 / 3 + 1).
Parameters
chunk data to convert
buf buffer to write to, NULL to malloc
Returns
chunk of encoded data
Described in header.
Definition at line 559 of file chunk.c.
References b64digits, chunk_create(), chunk_t::len, len, malloc(), and chunk_t::ptr.
Referenced by build_pub(), build_public_key(), dn(), encode_base64(), escape_http_request(), pem_encode(), pem_encoder_encode(), soap_init(), and START_TEST().
 {
     int i, len;
     char *pos;
     len = chunk.len + ((3 - chunk.len % 3) % 3);
     if (!buf)
     {
         buf = malloc(len * 4 / 3 + 1);
     }
     pos = buf;
     for (i = 0; i < len; i+=3)
     {
         *pos++ = b64digits[chunk.ptr[i] >> 2];
         if (i+1 >= chunk.len)
         {
             *pos++ = b64digits[(chunk.ptr[i] & 0x03) << 4];
             *pos++ = '=';
             *pos++ = '=';
             break;
         }
         *pos++ = b64digits[((chunk.ptr[i] & 0x03) << 4) | (chunk.ptr[i+1] >> 4)];
         if (i+2 >= chunk.len)
         {
             *pos++ = b64digits[(chunk.ptr[i+1] & 0x0F) << 2];
             *pos++ = '=';
             break;
         }
         *pos++ = b64digits[((chunk.ptr[i+1] & 0x0F) << 2) | (chunk.ptr[i+2] >> 6)];
         *pos++ = b64digits[chunk.ptr[i+2] & 0x3F];
     }
     *pos = '\0';
     return chunk_create(buf, len * 4 / 3);
 }
chunk_t chunk_to_hex (chunk_t chunk, char * buf, bool uppercase)
Convert a chunk of data to hex encoding.
The resulting string is '\0' terminated, but the chunk does not include the '\0'. If buf is supplied, it must hold at least (chunk.len * 2 + 1).
Parameters
chunk data to convert to hex encoding
buf buffer to write to, NULL to malloc
uppercase TRUE to use uppercase letters
Returns
chunk of encoded data
Described in header.
Definition at line 455 of file chunk.c.
References chunk_create(), hexdig_lower, hexdig_upper, chunk_t::len, len, malloc(), and chunk_t::ptr.
Referenced by add_device_id(), create_inner_cdp_hashandurl(), create_sid(), dn(), gen_identity(), get_cert_hash(), imv_attestation_process(), METHOD(), openssl_rsa_private_key_connect(), process_server_response(), process_server_retry(), scep_generate_pkcs10_fingerprint(), scep_generate_transaction_id(), and START_TEST().
 {
     int i, len;
     char *hexdig = hexdig_lower;
     if (uppercase)
     {
         hexdig = hexdig_upper;
     }
     len = chunk.len * 2;
     if (!buf)
     {
         buf = malloc(len + 1);
     }
     buf[len] = '\0';
     for (i = 0; i < chunk.len; i++)
     {
         buf[i*2]   = hexdig[(chunk.ptr[i] >> 4) & 0xF];
         buf[i*2+1] = hexdig[(chunk.ptr[i]     ) & 0xF];
     }
     return chunk_create(buf, len);
 }
bool chunk_unmap (chunk_t * public)
munmap() a chunk previously mapped with chunk_map()
When unmapping a writeable map, the return value should be checked to ensure changes landed on disk.
Parameters
chunk pointer returned from chunk_map()
Returns
TRUE of changes written back to file
See header.
Definition at line 401 of file chunk.c.
References close, FALSE, mmaped_chunk_t::fd, free(), len, mmaped_chunk_t::len, mmaped_chunk_t::map, TRUE, mmaped_chunk_t::wr, and write.
Referenced by add_file_key_value(), add_file_list_key(), add_radius_attribute(), chunk_map(), collect_tags(), load_aik_blob(), load_certs(), load_containers(), load_from_file(), load_imcvs_from_config(), load_keys(), load_secrets(), METHOD(), and START_TEST().
 {
     mmaped_chunk_t *chunk;
     bool ret = FALSE;
     int tmp = 0;
     chunk = (mmaped_chunk_t*)public;
 #ifdef HAVE_MMAP
     if (chunk->map && chunk->map != MAP_FAILED)
     {
         ret = munmap(chunk->map, chunk->len) == 0;
         tmp = errno;
     }
 #else /* !HAVE_MMAP */
     if (chunk->wr)
     {
         if (lseek(chunk->fd, 0, SEEK_SET) != -1)
         {
             int len, total = 0;
             ret = TRUE;
             while (total < chunk->len)
             {
                 len = write(chunk->fd, chunk->map + total, chunk->len - total);
                 if (len <= 0)
                 {
                     ret = FALSE;
                     break;
                 }
                 total += len;
             }
         }
         tmp = errno;
     }
     else
     {
         ret = TRUE;
     }
     free(chunk->map);
 #endif /* !HAVE_MMAP */
     close(chunk->fd);
     free(chunk);
     errno = tmp;
     return ret;
 }
bool chunk_write (chunk_t chunk, char * path, mode_t mask, bool force)
Write the binary contents of a chunk_t to a file
If the write fails, errno is set appropriately.
Parameters
chunk contents to write to file
path path where file is written to
mask file mode creation mask
force overwrite existing file by force
Returns
TRUE if write operation was successful
Described in header.
Definition at line 211 of file chunk.c.
References FALSE, good, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by create_parser(), create_settings(), main(), METHOD(), START_SETUP(), and START_TEST().
 {
     mode_t oldmask;
     FILE *fd;
     bool good = FALSE;
     int tmp = 0;
     if (!force && access(path, F_OK) == 0)
     {
         errno = EEXIST;
         return FALSE;
     }
     oldmask = umask(mask);
     fd = fopen(path,
 #ifdef WIN32
                 "wb"
 #else
                 "w"
 #endif
     );
     if (fd)
     {
         if (fwrite(chunk.ptr, sizeof(u_char), chunk.len, fd) == chunk.len)
         {
             good = TRUE;
         }
         else
         {
             tmp = errno;
         }
         fclose(fd);
     }
     else
     {
         tmp = errno;
     }
     umask(oldmask);
     errno = tmp;
     return good;
 }
Variable Documentation
chunk_t chunk_empty
A { NULL, 0 }-chunk handy for initialization.
Empty chunk.
Definition at line 35 of file chunk.c.
Referenced by acert(), add_device_id(), add_string_version(), asn1_algorithmIdentifier(), asn1_build_known_oid(), atodn(), attack_aeads(), attack_signers(), attr_filter(), attribute_enumerate(), authenticate(), AuthenticatorResponse(), bench_dh(), bliss_private_key_load(), bliss_public_key_load(), build_ack(), build_address_list(), build_auth_cfg(), build_authorityKeyIdentifier(), build_certreqs(), build_emsa_pkcs1_signature(), build_generalName(), build_issuerAndSerialNumber(), build_nonce(), build_notification_data(), build_OCSPRequest(), build_optionalSignature(), build_payloads(), build_requestList(), build_requestorName(), build_round(), build_signature(), build_vip(), CALLBACK(), challenge(), ChallengeResponse(), check_boot_aggregate(), chunk_create_clone(), chunk_free(), chunk_skip(), chunk_skip_end(), collect_tags(), create_client_error(), create_lease_query(), create_rdn_enumerator(), decrypt_and_extract(), decrypt_mppe_key(), derive_ike_aead(), derive_ike_traditional(), derive_key(), derive_keys(), dnskey_public_key_load(), do_netstat(), eap_identity_create_peer(), eap_identity_create_server(), eap_ttls_avp_create(), ecparams_lookup(), encrypt_mppe_key(), enumerate_dns(), enumerate_nbns(), esp_packet_create_from_payload(), extend_pcr(), extract_platform_info(), extract_token(), extract_token_str(), extract_username(), extract_value(), find_boundary(), find_pubkey_in_certs(), g_sha1(), gcrypt_rsa_find_token(), gcrypt_rsa_private_key_load(), gcrypt_rsa_public_key_load(), generate(), generate_auth_cfg(), generate_iv(), generate_message(), generate_natd_hash(), generate_natd_hash_faked(), GenerateStuff(), get_next_test_vector(), get_port_list(), gmp_rsa_private_key_load(), gmp_rsa_public_key_load(), hash_file(), hash_password(), identity(), ike_sa_create(), install(), issue(), load_from_file(), load_from_stream(), load_pin(), load_secrets(), load_shared(), main(), METHOD(), openssl_asn1_obj2chunk(), openssl_asn1_str2chunk(), openssl_crl_load(), openssl_diffie_hellman_create(), openssl_ec_private_key_load(), openssl_ec_public_key_load(), openssl_pkcs12_load(), openssl_rsa_fingerprint(), openssl_rsa_private_key_connect(), openssl_rsa_private_key_load(), openssl_rsa_public_key_load(), openssl_x509_load(), packet_create(), parse(), parse_attributes(), parse_basicOCSPResponse(), parse_contentInfo(), parse_ec_identifier(), parse_message(), parse_PFX(), parse_private_key(), parse_route(), parse_singleResponse(), pem_encoder_encode(), pem_load(), pem_to_bin(), pgp_cert_load(), pgp_private_key_load(), pgp_public_key_load(), pkcs11_creds_load(), pkcs11_private_key_connect(), pkcs11_public_key_load(), pkcs12_decode(), pkcs12_derive_key(), pkcs1_private_key_load(), pkcs1_public_key_load(), pkcs7(), pkcs7_data_gen(), pkcs7_enveloped_data_gen(), pkcs7_generic_load(), pkcs7_signed_data_gen(), pkcs8_private_key_load(), plugin_feature_hash(), process_addr(), process_auth_response(), process_challenge(), process_child_add(), process_client_hello(), process_eap(), process_filter_id(), process_identity(), process_ike_add(), process_ike_iv(), process_notification(), process_peer_failure(), process_peer_success(), process_reauthentication(), process_server_hello(), process_start(), process_synchronize(), pt_tls_dispatcher_create(), pt_tls_receive(), pubkey_cert_create(), pubkey_cert_wrap(), radius2ike(), read_from_stream(), read_result(), read_string(), read_swid_tag_ids(), read_swid_tags(), reauthenticate(), receive_msg(), receive_packets(), req(), scep_build_request(), scep_generate_pkcs10_fingerprint(), scep_generate_transaction_id(), scep_http_request(), select_and_install(), self(), send_auth_failed_informational(), shared_cb(), sign_bliss(), sign_classic(), sign_crl(), sign_signature_auth(), sshkey_public_key_load(), START_TEST(), tkm_keymat_create(), tkm_public_key_load(), tnc_imv_recommendations_create(), vendor_id_payload_create(), vici_find(), vici_submit(), x509_ac_load(), x509_build_crlDistributionPoints(), x509_build_subjectAltNames(), x509_cert_load(), x509_crl_load(), x509_ocsp_response_load(), x509_parse_authorityKeyIdentifier(), and x509_pkcs10_load().