strongSwan: gcm_aead
gcm_aead
gcm
Classes
struct gcm_aead_t
Typedefs
typedef struct gcm_aead_t gcm_aead_t
Functions
gcm_aead_t * gcm_aead_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Detailed Description
Typedef Documentation
typedef struct gcm_aead_t gcm_aead_t
Definition at line 26 of file gcm_aead.h.
Function Documentation
gcm_aead_t* gcm_aead_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Create a gcm_aead instance.
Parameters
algo algorithm to implement, a gcm mode
key_size key size in bytes
salt_size size of implicit salt length
Returns
aead, NULL if not supported
See header
Definition at line 378 of file gcm_aead.c.
References crypto_factory_t::create_crypter, crypter, library_t::crypto, ENCR_AES_CBC, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, free(), INIT, iv_gen_seq_create(), lib, and SALT_SIZE.
Referenced by METHOD().
 {
     private_gcm_aead_t *this;
     size_t icv_size;
     switch (key_size)
     {
         case 0:
             key_size = 16;
             break;
         case 16:
         case 24:
         case 32:
             break;
         default:
             return NULL;
     }
     if (salt_size && salt_size != SALT_SIZE)
     {
         /* currently not supported */
         return NULL;
     }
     switch (algo)
     {
         case ENCR_AES_GCM_ICV8:
             algo = ENCR_AES_CBC;
             icv_size = 8;
             break;
         case ENCR_AES_GCM_ICV12:
             algo = ENCR_AES_CBC;
             icv_size = 12;
             break;
         case ENCR_AES_GCM_ICV16:
             algo = ENCR_AES_CBC;
             icv_size = 16;
             break;
         default:
             return NULL;
     }
     INIT(this,
         .public = {
             .aead = {
                 .encrypt = _encrypt,
                 .decrypt = _decrypt,
                 .get_block_size = _get_block_size,
                 .get_icv_size = _get_icv_size,
                 .get_iv_size = _get_iv_size,
                 .get_iv_gen = _get_iv_gen,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .crypter = lib->crypto->create_crypter(lib->crypto, algo, key_size),
         .iv_gen = iv_gen_seq_create(),
         .icv_size = icv_size,
     );
     if (!this->crypter)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }