strongSwan: credential set
credential set
tkm
Classes
struct tkm_cred_t
Typedefs
typedef struct tkm_cred_t tkm_cred_t
Functions
tkm_cred_t * tkm_cred_create ()
Detailed Description
Typedef Documentation
typedef struct tkm_cred_t tkm_cred_t
Definition at line 25 of file tkm_cred.h.
Function Documentation
tkm_cred_t* tkm_cred_create ()
Create a tkm_cred instance.
See header
Definition at line 126 of file tkm_cred.c.
References create_private_enumerator(), equals(), hash(), hashtable_create(), INIT, mem_cred_create(), nop(), return_null(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by main().
 {
     private_tkm_cred_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_shared_enumerator = (void*)return_null,
                 .create_private_enumerator = _create_private_enumerator,
                 .create_cert_enumerator = (void*)return_null,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .destroy = _destroy,
         },
         .creds = mem_cred_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .known_keys = hashtable_create((hashtable_hash_t)hash,
                                        (hashtable_equals_t)equals, 4),
     );
     return &this->public;
 }