strongSwan: mediation_manager.c File Reference
mediation_manager.c File Reference
#include "mediation_manager.h"
#include <daemon.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include <processing/jobs/mediation_job.h>
Classes
struct peer_t
struct private_mediation_manager_t
Typedefs
typedef struct peer_t peer_t
typedef struct
private_mediation_manager_t private_mediation_manager_t
Functions
static void peer_destroy (peer_t *this)
static peer_t * peer_create (identification_t *id, ike_sa_id_t *ike_sa_id)
static void register_peer (peer_t *peer, identification_t *peer_id)
static status_t get_peer_by_id (private_mediation_manager_t *this, identification_t *id, peer_t **peer)
static void unregister_peer (private_mediation_manager_t *this, identification_t *peer_id)
METHOD (mediation_manager_t, remove_sa, void, private_mediation_manager_t *this, ike_sa_id_t *ike_sa_id)
METHOD (mediation_manager_t, update_sa_id, void, private_mediation_manager_t *this, identification_t *peer_id, ike_sa_id_t *ike_sa_id)
METHOD (mediation_manager_t, check, ike_sa_id_t *, private_mediation_manager_t *this, identification_t *peer_id)
METHOD (mediation_manager_t, check_and_register, ike_sa_id_t *, private_mediation_manager_t *this, identification_t *peer_id, identification_t *requester)
METHOD (mediation_manager_t, destroy, void, private_mediation_manager_t *this)
mediation_manager_t * mediation_manager_create ()
Typedef Documentation
typedef struct peer_t peer_t
Definition at line 23 of file mediation_manager.c.
typedef struct private_mediation_manager_t private_mediation_manager_t
Definition at line 65 of file mediation_manager.c.
Function Documentation
static status_t get_peer_by_id (private_mediation_manager_t * this, identification_t * id, peer_t ** peer) static
Get a peer_t object by a peer's id
Definition at line 113 of file mediation_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, identification_t::equals, peer_t::id, NOT_FOUND, status, and SUCCESS.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     peer_t *current;
     status_t status = NOT_FOUND;
     enumerator = this->peers->create_enumerator(this->peers);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (id->equals(id, current->id))
         {
             if (peer)
             {
                 *peer = current;
             }
             status = SUCCESS;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return status;
 }
METHOD (mediation_manager_t , remove_sa , void , private_mediation_manager_t * this, ike_sa_id_t * ike_sa_id)
Definition at line 176 of file mediation_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, ike_sa_id_t::equals, peer_t::id, peer_t::ike_sa_id, mutex_t::lock, mutex, peer_destroy(), mutex_t::unlock, and unregister_peer().
 {
     enumerator_t *enumerator;
     peer_t *peer;
     this->mutex->lock(this->mutex);
     enumerator = this->peers->create_enumerator(this->peers);
     while (enumerator->enumerate(enumerator, (void**)&peer))
     {
         if (ike_sa_id->equals(ike_sa_id, peer->ike_sa_id))
         {
             this->peers->remove_at(this->peers, enumerator);
             unregister_peer(this, peer->id);
             peer_destroy(peer);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (mediation_manager_t , update_sa_id , void , private_mediation_manager_t * this, identification_t * peer_id, ike_sa_id_t * ike_sa_id)
Definition at line 202 of file mediation_manager.c.
References ike_sa_id_t::clone, DBG2, DBG_IKE, enumerator_t::destroy, identification_t::destroy, DESTROY_IF, enumerator_t::enumerate, identification_t::equals, FALSE, found, peer_t::id, peer_t::ike_sa_id, lib, mutex_t::lock, mediation_callback_job_create(), mutex, peer_create(), library_t::processor, processor_t::queue_job, linked_list_t::remove_last, peer_t::requested_by, SUCCESS, TRUE, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     peer_t *peer;
     bool found = FALSE;
     this->mutex->lock(this->mutex);
     enumerator = this->peers->create_enumerator(this->peers);
     while (enumerator->enumerate(enumerator, (void**)&peer))
     {
         if (peer_id->equals(peer_id, peer->id))
         {
             DESTROY_IF(peer->ike_sa_id);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         DBG2(DBG_IKE, "adding peer '%Y'", peer_id);
         peer = peer_create(peer_id, NULL);
         this->peers->insert_last(this->peers, peer);
     }
     DBG2(DBG_IKE, "changing registered IKE_SA ID of peer '%Y'", peer_id);
     peer->ike_sa_id = ike_sa_id ? ike_sa_id->clone(ike_sa_id) : NULL;
     /* send callbacks to registered peers */
     identification_t *requester;
     while(peer->requested_by->remove_last(peer->requested_by,
                                           (void**)&requester) == SUCCESS)
     {
         job_t *job = (job_t*)mediation_callback_job_create(requester, peer_id);
         lib->processor->queue_job(lib->processor, job);
         requester->destroy(requester);
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (mediation_manager_t , check , ike_sa_id_t * , private_mediation_manager_t * this, identification_t * peer_id)
Definition at line 247 of file mediation_manager.c.
References get_peer_by_id(), peer_t::ike_sa_id, mutex_t::lock, mutex, SUCCESS, and mutex_t::unlock.
 {
     peer_t *peer;
     ike_sa_id_t *ike_sa_id;
     this->mutex->lock(this->mutex);
     if (get_peer_by_id(this, peer_id, &peer) != SUCCESS)
     {
         this->mutex->unlock(this->mutex);
         return NULL;
     }
     ike_sa_id = peer->ike_sa_id;
     this->mutex->unlock(this->mutex);
     return ike_sa_id;
 }
METHOD (mediation_manager_t , check_and_register , ike_sa_id_t * , private_mediation_manager_t * this, identification_t * peer_id, identification_t * requester)
Definition at line 268 of file mediation_manager.c.
References DBG2, DBG_IKE, get_peer_by_id(), peer_t::ike_sa_id, mutex_t::lock, mutex, peer_create(), register_peer(), SUCCESS, and mutex_t::unlock.
 {
     peer_t *peer;
     ike_sa_id_t *ike_sa_id;
     this->mutex->lock(this->mutex);
     if (get_peer_by_id(this, peer_id, &peer) != SUCCESS)
     {
         DBG2(DBG_IKE, "adding peer %Y", peer_id);
         peer = peer_create(peer_id, NULL);
         this->peers->insert_last(this->peers, peer);
     }
     if (!peer->ike_sa_id)
     {
         /* the peer is not online */
         DBG2(DBG_IKE, "requested peer '%Y' is offline, registering peer '%Y'",
              peer_id, requester);
         register_peer(peer, requester);
         this->mutex->unlock(this->mutex);
         return NULL;
     }
     ike_sa_id = peer->ike_sa_id;
     this->mutex->unlock(this->mutex);
     return ike_sa_id;
 }
METHOD (mediation_manager_t , destroy , void , private_mediation_manager_t * this)
Definition at line 301 of file mediation_manager.c.
References mutex_t::destroy, free(), mutex_t::lock, mutex, peer_destroy(), and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->peers->destroy_function(this->peers, (void*)peer_destroy);
     this->mutex->unlock(this->mutex);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static peer_t* peer_create (identification_t * id, ike_sa_id_t * ike_sa_id) static
Creates a new entry for the list.
Definition at line 54 of file mediation_manager.c.
References ike_sa_id_t::clone, identification_t::clone, INIT, and linked_list_create().
Referenced by METHOD().
 {
     peer_t *this;
     INIT(this,
         .id = id->clone(id),
         .ike_sa_id = ike_sa_id ? ike_sa_id->clone(ike_sa_id) : NULL,
         .requested_by = linked_list_create(),
     );
     return this;
 }
static void peer_destroy (peer_t * this) static
Implementation of peer_t.destroy.
Definition at line 42 of file mediation_manager.c.
References destroy(), DESTROY_IF, and free().
Referenced by METHOD(), and unregister_peer().
 {
     DESTROY_IF(this->id);
     DESTROY_IF(this->ike_sa_id);
     this->requested_by->destroy_offset(this->requested_by,
                                        offsetof(identification_t, destroy));
     free(this);
 }
static void register_peer (peer_t * peer, identification_t * peer_id) static
Registers a peer's ID at another peer, if it is not yet registered
Definition at line 90 of file mediation_manager.c.
References identification_t::clone, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, identification_t::equals, linked_list_t::insert_last, and peer_t::requested_by.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     identification_t *current;
     enumerator = peer->requested_by->create_enumerator(peer->requested_by);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (peer_id->equals(peer_id, current))
         {
             enumerator->destroy(enumerator);
             return;
         }
     }
     enumerator->destroy(enumerator);
     peer->requested_by->insert_last(peer->requested_by,
                                     peer_id->clone(peer_id));
 }
static void unregister_peer (private_mediation_manager_t * this, identification_t * peer_id) static
Check if a given peer is registered at other peers. If so, remove it there and then remove peers completely that are not online and have no registered peers.
Definition at line 143 of file mediation_manager.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, identification_t::destroy, enumerator_t::enumerate, identification_t::equals, linked_list_t::get_count, peer_t::ike_sa_id, peer_destroy(), registered, linked_list_t::remove_at, and peer_t::requested_by.
Referenced by METHOD().
 {
     enumerator_t *enumerator, *enumerator_r;
     peer_t *peer;
     identification_t *registered;
     enumerator = this->peers->create_enumerator(this->peers);
     while (enumerator->enumerate(enumerator, (void**)&peer))
     {
         enumerator_r = peer->requested_by->create_enumerator(peer->requested_by);
         while (enumerator_r->enumerate(enumerator_r, (void**)&registered))
         {
             if (peer_id->equals(peer_id, registered))
             {
                 peer->requested_by->remove_at(peer->requested_by, enumerator_r);
                 registered->destroy(registered);
                 break;
             }
         }
         enumerator_r->destroy(enumerator_r);
         if (!peer->ike_sa_id &&
             !peer->requested_by->get_count(peer->requested_by))
         {
             this->peers->remove_at(this->peers, enumerator);
             peer_destroy(peer);
             break;
         }
     }
     enumerator->destroy(enumerator);
 }