strongSwan: swid_inventory
swid_inventory
swid
Classes
struct swid_inventory_t
Macros
#define SWID_MAX_ATTR_SIZE 100000000
Typedefs
typedef struct swid_inventory_t swid_inventory_t
Functions
swid_inventory_t * swid_inventory_create (bool full_tags)
Detailed Description
Macro Definition Documentation
#define SWID_MAX_ATTR_SIZE 100000000
Definition at line 27 of file swid_inventory.h.
Referenced by METHOD(), and TNC_IMC_BeginHandshake().
Typedef Documentation
typedef struct swid_inventory_t swid_inventory_t
Definition at line 29 of file swid_inventory.h.
Function Documentation
swid_inventory_t* swid_inventory_create (bool full_tags)
Creates a swid_inventory_t object
Parameters
full_tags TRUE if full tags, FALSE if tag IDs only
See header
Definition at line 437 of file swid_inventory.c.
References INIT, and linked_list_create().
Referenced by add_swid_inventory(), METHOD(), tcg_swid_attr_req_create(), tcg_swid_attr_req_create_from_data(), tcg_swid_attr_tag_id_inv_create(), tcg_swid_attr_tag_id_inv_create_from_data(), tcg_swid_attr_tag_inv_create(), and tcg_swid_attr_tag_inv_create_from_data().
 {
     private_swid_inventory_t *this;
     INIT(this,
         .public = {
             .collect = _collect,
             .add = _add,
             .get_count = _get_count,
             .create_enumerator = _create_enumerator,
             .destroy = _destroy,
         },
         .full_tags = full_tags,
         .list = linked_list_create(),
     );
     return &this->public;
 }