strongSwan: gmp_rsa_public_key.c File Reference
gmp_rsa_public_key.c File Reference
#include <gmp.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include "gmp_rsa_public_key.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <crypto/hashers/hasher.h>
Classes
struct private_gmp_rsa_public_key_t
Macros
#define DIGEST_INFO 0
#define DIGEST_INFO_ALGORITHM 1
#define DIGEST_INFO_DIGEST 2
#define MIN_PS_PADDING 8
Typedefs
typedef struct
private_gmp_rsa_public_key_t private_gmp_rsa_public_key_t
Functions
chunk_t gmp_mpz_to_chunk (const mpz_t value)
static chunk_t rsaep (private_gmp_rsa_public_key_t *this, chunk_t data)
static chunk_t rsavp1 (private_gmp_rsa_public_key_t *this, chunk_t data)
static bool verify_emsa_pkcs1_signature (private_gmp_rsa_public_key_t *this, hash_algorithm_t algorithm, chunk_t data, chunk_t signature)
METHOD (public_key_t, get_type, key_type_t, private_gmp_rsa_public_key_t *this)
METHOD (public_key_t, verify, bool, private_gmp_rsa_public_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
METHOD (public_key_t, encrypt_, bool, private_gmp_rsa_public_key_t *this, encryption_scheme_t scheme, chunk_t plain, chunk_t *crypto)
METHOD (public_key_t, get_keysize, int, private_gmp_rsa_public_key_t *this)
METHOD (public_key_t, get_encoding, bool, private_gmp_rsa_public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (public_key_t, get_fingerprint, bool, private_gmp_rsa_public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (public_key_t, get_ref, public_key_t *, private_gmp_rsa_public_key_t *this)
METHOD (public_key_t, destroy, void, private_gmp_rsa_public_key_t *this)
gmp_rsa_public_key_t * gmp_rsa_public_key_load (key_type_t type, va_list args)
Variables
static const asn1Object_t digestInfoObjects []
Macro Definition Documentation
#define DIGEST_INFO 0
Definition at line 118 of file gmp_rsa_public_key.c.
Referenced by verify_emsa_pkcs1_signature().
#define DIGEST_INFO_ALGORITHM 1
Definition at line 119 of file gmp_rsa_public_key.c.
Referenced by verify_emsa_pkcs1_signature().
#define DIGEST_INFO_DIGEST 2
Definition at line 120 of file gmp_rsa_public_key.c.
Referenced by verify_emsa_pkcs1_signature().
#define MIN_PS_PADDING 8
Definition at line 313 of file gmp_rsa_public_key.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_gmp_rsa_public_key_t private_gmp_rsa_public_key_t
Definition at line 36 of file gmp_rsa_public_key.c.
Function Documentation
chunk_t gmp_mpz_to_chunk (const mpz_t value)
Shared functions defined in gmp_rsa_private_key.c
Convert a MP integer into a chunk_t
Definition at line 126 of file gmp_rsa_private_key.c.
References BITS_PER_BYTE, chunk_t::len, n, and chunk_t::ptr.
Referenced by METHOD().
 {
     chunk_t n;
     n.len = 1 + mpz_sizeinbase(value, 2) / BITS_PER_BYTE;
     n.ptr = mpz_export(NULL, NULL, 1, n.len, 1, 0, value);
     if (n.ptr == NULL)
     {   /* if we have zero in "value", gmp returns NULL */
         n.len = 0;
     }
     return n;
 }
METHOD (public_key_t , get_type , key_type_t , private_gmp_rsa_public_key_t * this)
Definition at line 280 of file gmp_rsa_public_key.c.
References KEY_RSA.
 {
     return KEY_RSA;
 }
METHOD (public_key_t , verify , bool , private_gmp_rsa_public_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
Definition at line 286 of file gmp_rsa_public_key.c.
References DBG1, DBG_LIB, FALSE, HASH_MD5, HASH_SHA1, HASH_SHA224, HASH_SHA256, HASH_SHA384, HASH_SHA512, HASH_UNKNOWN, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, signature_scheme_names, and verify_emsa_pkcs1_signature().
 {
     switch (scheme)
     {
         case SIGN_RSA_EMSA_PKCS1_NULL:
             return verify_emsa_pkcs1_signature(this, HASH_UNKNOWN, data, signature);
         case SIGN_RSA_EMSA_PKCS1_MD5:
             return verify_emsa_pkcs1_signature(this, HASH_MD5, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA1:
             return verify_emsa_pkcs1_signature(this, HASH_SHA1, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA224:
             return verify_emsa_pkcs1_signature(this, HASH_SHA224, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA256:
             return verify_emsa_pkcs1_signature(this, HASH_SHA256, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA384:
             return verify_emsa_pkcs1_signature(this, HASH_SHA384, data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA512:
             return verify_emsa_pkcs1_signature(this, HASH_SHA512, data, signature);
         default:
             DBG1(DBG_LIB, "signature scheme %N not supported in RSA",
                  signature_scheme_names, scheme);
             return FALSE;
     }
 }
METHOD (public_key_t , encrypt_ , bool , private_gmp_rsa_public_key_t * this, encryption_scheme_t scheme, chunk_t plain, chunk_t * crypto)
Definition at line 315 of file gmp_rsa_public_key.c.
References chunk_clear(), crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG2, DBG3, DBG_LIB, rng_t::destroy, ENCRYPT_RSA_PKCS1, encryption_scheme_names, FALSE, chunk_t::len, lib, malloc(), memcpy, MIN_PS_PADDING, padding, chunk_t::ptr, rng, rng_get_bytes_not_zero(), RNG_WEAK, rsaep(), and TRUE.
 {
     chunk_t em;
     u_char *pos;
     int padding;
     rng_t *rng;
     if (scheme != ENCRYPT_RSA_PKCS1)
     {
         DBG1(DBG_LIB, "encryption scheme %N not supported",
              encryption_scheme_names, scheme);
         return FALSE;
     }
     /* number of pseudo-random padding octets */
     padding = this->k - plain.len - 3;
     if (padding < MIN_PS_PADDING)
     {
         DBG1(DBG_LIB, "pseudo-random padding must be at least %d octets",
              MIN_PS_PADDING);
         return FALSE;
     }
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (rng == NULL)
     {
         DBG1(DBG_LIB, "no random generator available");
         return FALSE;
     }
     /* padding according to PKCS#1 7.2.1 (RSAES-PKCS1-v1.5-ENCRYPT) */
     DBG2(DBG_LIB, "padding %u bytes of data to the rsa modulus size of"
          " %u bytes", plain.len, this->k);
     em.len = this->k;
     em.ptr = malloc(em.len);
     pos = em.ptr;
     *pos++ = 0x00;
     *pos++ = 0x02;
     /* fill with pseudo random octets */
     if (!rng_get_bytes_not_zero(rng, padding, pos, TRUE))
     {
         DBG1(DBG_LIB, "failed to allocate padding");
         chunk_clear(&em);
         rng->destroy(rng);
         return FALSE;
     }
     rng->destroy(rng);
     pos += padding;
     /* append the padding terminator */
     *pos++ = 0x00;
     /* now add the data */
     memcpy(pos, plain.ptr, plain.len);
     DBG3(DBG_LIB, "padded data before rsa encryption: %B", &em);
     /* rsa encryption using PKCS#1 RSAEP */
     *crypto = rsaep(this, em);
     DBG3(DBG_LIB, "rsa encrypted data: %B", crypto);
     chunk_clear(&em);
     return TRUE;
 }
METHOD (public_key_t , get_keysize , int , private_gmp_rsa_public_key_t * this)
Definition at line 380 of file gmp_rsa_public_key.c.
References n.
 {
     return mpz_sizeinbase(this->n, 2);
 }
METHOD (public_key_t , get_encoding , bool , private_gmp_rsa_public_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 386 of file gmp_rsa_public_key.c.
References chunk_free(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, cred_encoding_t::encode, library_t::encoding, gmp_mpz_to_chunk(), lib, and n.
 {
     chunk_t n, e;
     bool success;
     n = gmp_mpz_to_chunk(this->n);
     e = gmp_mpz_to_chunk(this->e);
     success = lib->encoding->encode(lib->encoding, type, NULL, encoding,
             CRED_PART_RSA_MODULUS, n, CRED_PART_RSA_PUB_EXP, e, CRED_PART_END);
     chunk_free(&n);
     chunk_free(&e);
     return success;
 }
METHOD (public_key_t , get_fingerprint , bool , private_gmp_rsa_public_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 404 of file gmp_rsa_public_key.c.
References chunk_free(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, cred_encoding_t::encode, library_t::encoding, cred_encoding_t::get_cache, gmp_mpz_to_chunk(), lib, n, and TRUE.
 {
     chunk_t n, e;
     bool success;
     if (lib->encoding->get_cache(lib->encoding, type, this, fp))
     {
         return TRUE;
     }
     n = gmp_mpz_to_chunk(this->n);
     e = gmp_mpz_to_chunk(this->e);
     success = lib->encoding->encode(lib->encoding, type, this, fp,
             CRED_PART_RSA_MODULUS, n, CRED_PART_RSA_PUB_EXP, e, CRED_PART_END);
     chunk_free(&n);
     chunk_free(&e);
     return success;
 }
METHOD (public_key_t , get_ref , public_key_t * , private_gmp_rsa_public_key_t * this)
Definition at line 425 of file gmp_rsa_public_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (public_key_t , destroy , void , private_gmp_rsa_public_key_t * this)
Definition at line 432 of file gmp_rsa_public_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), lib, n, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         mpz_clear(this->n);
         mpz_clear(this->e);
         lib->encoding->clear_cache(lib->encoding, this);
         free(this);
     }
 }
static chunk_t rsaep (private_gmp_rsa_public_key_t * this, chunk_t data) static
RSAEP algorithm specified in PKCS#1.
Definition at line 76 of file gmp_rsa_public_key.c.
References c, chunk_t::len, m, n, and chunk_t::ptr.
Referenced by METHOD(), and rsavp1().
 {
     mpz_t m, c;
     chunk_t encrypted;
     mpz_init(c);
     mpz_init(m);
     mpz_import(m, data.len, 1, 1, 1, 0, data.ptr);
     mpz_powm(c, m, this->e, this->n);
     encrypted.len = this->k;
     encrypted.ptr = mpz_export(NULL, NULL, 1, encrypted.len, 1, 0, c);
     if (encrypted.ptr == NULL)
     {
         encrypted.len = 0;
     }
     mpz_clear(c);
     mpz_clear(m);
     return encrypted;
 }
static chunk_t rsavp1 (private_gmp_rsa_public_key_t * this, chunk_t data) static
RSAVP1 algorithm specified in PKCS#1.
Definition at line 104 of file gmp_rsa_public_key.c.
References rsaep().
Referenced by verify_emsa_pkcs1_signature().
 {
     return rsaep(this, data);
 }
static bool verify_emsa_pkcs1_signature (private_gmp_rsa_public_key_t * this, hash_algorithm_t algorithm, chunk_t data, chunk_t signature) static
Verification of an EMPSA PKCS1 signature described in PKCS#1
Definition at line 125 of file gmp_rsa_public_key.c.
References hasher_t::allocate_hash, asn1_parse_algorithmIdentifier(), asn1_parser_create(), chunk_skip(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG2, DBG_LIB, asn1_parser_t::destroy, hasher_t::destroy, DIGEST_INFO, DIGEST_INFO_ALGORITHM, DIGEST_INFO_DIGEST, end, FALSE, free(), hasher_t::get_hash_size, asn1_parser_t::get_level, hash, hash_algorithm_names, HASH_UNKNOWN, hasher, hasher_algorithm_from_oid(), asn1_parser_t::iterate, chunk_t::len, len, lib, memeq_const(), parser, chunk_t::ptr, rsavp1(), and asn1_parser_t::success.
Referenced by METHOD().
 {
     chunk_t em_ori, em;
     bool success = FALSE;
     /* remove any preceding 0-bytes from signature */
     while (signature.len && *(signature.ptr) == 0x00)
     {
         signature = chunk_skip(signature, 1);
     }
     if (signature.len == 0 || signature.len > this->k)
     {
         return FALSE;
     }
     /* unpack signature */
     em_ori = em = rsavp1(this, signature);
     /* result should look like this:
      * EM = 0x00 || 0x01 || PS || 0x00 || T.
      * PS = 0xFF padding, with length to fill em
      * T = oid || hash
      */
     /* check magic bytes */
     if (*(em.ptr) != 0x00 || *(em.ptr+1) != 0x01)
     {
         goto end;
     }
     em = chunk_skip(em, 2);
     /* find magic 0x00 */
     while (em.len > 0)
     {
         if (*em.ptr == 0x00)
         {
             /* found magic byte, stop */
             em = chunk_skip(em, 1);
             break;
         }
         else if (*em.ptr != 0xFF)
         {
             /* bad padding, decryption failed ?!*/
             goto end;
         }
         em = chunk_skip(em, 1);
     }
     if (em.len == 0)
     {
         /* no digestInfo found */
         goto end;
     }
     if (algorithm == HASH_UNKNOWN)
     {   /* IKEv1 signatures without digestInfo */
         if (em.len != data.len)
         {
             DBG1(DBG_LIB, "hash size in signature is %u bytes instead of"
                  " %u bytes", em.len, data.len);
             goto end;
         }
         success = memeq_const(em.ptr, data.ptr, data.len);
     }
     else
     {   /* IKEv2 and X.509 certificate signatures */
         asn1_parser_t *parser;
         chunk_t object;
         int objectID;
         hash_algorithm_t hash_algorithm = HASH_UNKNOWN;
         DBG2(DBG_LIB, "signature verification:");
         parser = asn1_parser_create(digestInfoObjects, em);
         while (parser->iterate(parser, &objectID, &object))
         {
             switch (objectID)
             {
                 case DIGEST_INFO:
                 {
                     if (em.len > object.len)
                     {
                         DBG1(DBG_LIB, "digestInfo field in signature is"
                              " followed by %u surplus bytes",
                              em.len - object.len);
                         goto end_parser;
                     }
                     break;
                 }
                 case DIGEST_INFO_ALGORITHM:
                 {
                     int hash_oid = asn1_parse_algorithmIdentifier(object,
                                          parser->get_level(parser)+1, NULL);
                     hash_algorithm = hasher_algorithm_from_oid(hash_oid);
                     if (hash_algorithm == HASH_UNKNOWN || hash_algorithm != algorithm)
                     {
                         DBG1(DBG_LIB, "expected hash algorithm %N, but found"
                              " %N (OID: %#B)", hash_algorithm_names, algorithm,
                              hash_algorithm_names, hash_algorithm,  &object);
                         goto end_parser;
                     }
                     break;
                 }
                 case DIGEST_INFO_DIGEST:
                 {
                     chunk_t hash;
                     hasher_t *hasher;
                     hasher = lib->crypto->create_hasher(lib->crypto, hash_algorithm);
                     if (hasher == NULL)
                     {
                         DBG1(DBG_LIB, "hash algorithm %N not supported",
                              hash_algorithm_names, hash_algorithm);
                         goto end_parser;
                     }
                     if (object.len != hasher->get_hash_size(hasher))
                     {
                         DBG1(DBG_LIB, "hash size in signature is %u bytes"
                              " instead of %u bytes", object.len,
                              hasher->get_hash_size(hasher));
                         hasher->destroy(hasher);
                         goto end_parser;
                     }
                     /* build our own hash and compare */
                     if (!hasher->allocate_hash(hasher, data, &hash))
                     {
                         hasher->destroy(hasher);
                         goto end_parser;
                     }
                     hasher->destroy(hasher);
                     success = memeq_const(object.ptr, hash.ptr, hash.len);
                     free(hash.ptr);
                     break;
                 }
                 default:
                     break;
             }
         }
 end_parser:
         success &= parser->success(parser);
         parser->destroy(parser);
     }
 end:
     free(em_ori.ptr);
     return success;
 }
Variable Documentation
const asn1Object_t digestInfoObjects[] static
Initial value:
= {
    { 0, "digestInfo",          ASN1_SEQUENCE,      ASN1_OBJ  },
    { 1,   "digestAlgorithm",   ASN1_EOC,           ASN1_RAW  },
    { 1,   "digest",            ASN1_OCTET_STRING,  ASN1_BODY },
    { 0, "exit",                ASN1_EOC,           ASN1_EXIT }
}
ASN.1 definition of digestInfo
Definition at line 112 of file gmp_rsa_public_key.c.