strongSwan: xauth_pam_listener.c File Reference
xauth_pam_listener.c File Reference
#include <stdio.h>
#include "xauth_pam_listener.h"
#include <daemon.h>
#include <library.h>
#include <security/pam_appl.h>
Classes
struct private_xauth_pam_listener_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_xauth_pam_listener_t private_xauth_pam_listener_t
Functions
static int conv (int num_msg, const struct pam_message **msg, struct pam_response **resp, void *data)
METHOD (listener_t, ike_updown, bool, private_xauth_pam_listener_t *this, ike_sa_t *ike_sa, bool up)
METHOD (xauth_pam_listener_t, listener_destroy, void, private_xauth_pam_listener_t *this)
xauth_pam_listener_t * xauth_pam_listener_create ()
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 24 of file xauth_pam_listener.c.
Typedef Documentation
typedef struct private_xauth_pam_listener_t private_xauth_pam_listener_t
Definition at line 34 of file xauth_pam_listener.c.
Function Documentation
static int conv (int num_msg, const struct pam_message ** msg, struct pam_response ** resp, void * data) static
PAM conv callback function
Definition at line 55 of file xauth_pam_listener.c.
Referenced by METHOD().
 {
     int i;
     for (i = 0; i < num_msg; i++)
     {
         /* ignore any text info, but fail on any interaction request */
         if (msg[i]->msg_style != PAM_TEXT_INFO)
         {
             return PAM_CONV_ERR;
         }
     }
     return PAM_SUCCESS;
 }
METHOD (listener_t , ike_updown , bool , private_xauth_pam_listener_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 71 of file xauth_pam_listener.c.
References asprintf(), conv(), DBG1, DBG_IKE, free(), ike_sa_t::get_other_eap_id, and TRUE.
 {
     struct pam_conv null_conv = {
         .conv = conv,
     };
     pam_handle_t *pamh = NULL;
     char *user;
     int ret;
     if (asprintf(&user, "%Y", ike_sa->get_other_eap_id(ike_sa)) != -1)
     {
         ret = pam_start(this->service, user, &null_conv, &pamh);
         if (ret == PAM_SUCCESS)
         {
             if (up)
             {
                 ret = pam_open_session(pamh, 0);
                 if (ret != PAM_SUCCESS)
                 {
                     DBG1(DBG_IKE, "XAuth pam_open_session for '%s' failed: %s",
                          user, pam_strerror(pamh, ret));
                 }
             }
             else
             {
                 ret = pam_close_session(pamh, 0);
                 if (ret != PAM_SUCCESS)
                 {
                     DBG1(DBG_IKE, "XAuth pam_close_session for '%s' failed: %s",
                          user, pam_strerror(pamh, ret));
                 }
             }
         }
         else
         {
             DBG1(DBG_IKE, "XAuth pam_start for '%s' failed: %s",
                  user, pam_strerror(pamh, ret));
         }
         pam_end(pamh, ret);
         free(user);
     }
     return TRUE;
 }
METHOD (xauth_pam_listener_t , listener_destroy , void , private_xauth_pam_listener_t * this)
Definition at line 116 of file xauth_pam_listener.c.
References free().
 {
     free(this);
 }