strongSwan: kernel_libipsec_router
kernel_libipsec_router
kernel_libipsec
Classes
struct kernel_libipsec_router_t
Typedefs
typedef struct
kernel_libipsec_router_t kernel_libipsec_router_t
Functions
kernel_libipsec_router_t * kernel_libipsec_router_create ()
Variables
kernel_libipsec_router_t * router
Detailed Description
Typedef Documentation
typedef struct kernel_libipsec_router_t kernel_libipsec_router_t
Definition at line 26 of file kernel_libipsec_router.h.
Function Documentation
kernel_libipsec_router_t* kernel_libipsec_router_create ()
Create a kernel_libipsec_router_t instance.
Returns
kernel_libipsec_router_t instance
Definition at line 323 of file kernel_libipsec_router.c.
References receiver_t::add_esp_cb, kernel_interface_t::add_listener, callback_job_create(), charon, DBG1, DBG_KNL, deliver_plain(), free(), library_t::get, handle_plain(), hashtable_create(), hydra, INIT, ipsec, hydra_t::kernel_interface, lib, lock, notify(), ipsec_t::processor, library_t::processor, processor_t::queue_job, daemon_t::receiver, receiver_esp_cb(), ipsec_processor_t::register_inbound, ipsec_processor_t::register_outbound, return_false(), rwlock_create(), RWLOCK_TYPE_DEFAULT, send_esp(), set_nonblock(), tun_entry_equals(), and tun_entry_hash().
Referenced by create_router().
 {
     private_kernel_libipsec_router_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .tun = _tun,
             },
             .get_tun_name = _get_tun_name,
             .destroy = _destroy,
         },
         .tun = {
             .tun = lib->get(lib, "kernel-libipsec-tun"),
         }
     );
     if (pipe(this->notify) != 0 ||
         !set_nonblock(this->notify[0]) || !set_nonblock(this->notify[1]))
     {
         DBG1(DBG_KNL, "creating notify pipe for kernel-libipsec router failed");
         free(this);
         return NULL;
     }
     this->tun.fd = this->tun.tun->get_fd(this->tun.tun);
     this->tuns = hashtable_create((hashtable_hash_t)tun_entry_hash,
                                   (hashtable_equals_t)tun_entry_equals, 4);
     this->lock = rwlock_create(RWLOCK_TYPE_DEFAULT);
     hydra->kernel_interface->add_listener(hydra->kernel_interface,
                                           &this->public.listener);
     ipsec->processor->register_outbound(ipsec->processor, send_esp, NULL);
     ipsec->processor->register_inbound(ipsec->processor,
                                     (ipsec_inbound_cb_t)deliver_plain, this);
     charon->receiver->add_esp_cb(charon->receiver,
                                     (receiver_esp_cb_t)receiver_esp_cb, NULL);
     lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create((callback_job_cb_t)handle_plain, this,
                                     NULL, (callback_job_cancel_t)return_false));
     router = &this->public;
     return &this->public;
 }
Variable Documentation
kernel_libipsec_router_t* router
Single instance of this class, if created
Single instance of the router
Definition at line 47 of file kernel_libipsec_router.c.
Referenced by create_router(), install_route(), manage_route(), and METHOD().