strongSwan: thread.c File Reference
windows/thread.c File Reference
#include "thread.h"
#include <utils/debug.h>
#include <threading/spinlock.h>
#include <threading/thread.h>
#include <collections/hashtable.h>
#include <collections/array.h>
Classes
struct private_thread_t
struct cleanup_t
Typedefs
typedef struct private_thread_t private_thread_t
Functions
static private_thread_t * create_internal (DWORD id)
static bool set_leak_detective (bool state)
static void put_thread (private_thread_t *this)
static void remove_thread (private_thread_t *this)
static private_thread_t * get_current_thread ()
void * thread_tls_put (void *key, void *value)
void * thread_tls_get (void *key)
void * thread_tls_remove (void *key)
static void docleanup (private_thread_t *this)
static void destroy (private_thread_t *this)
static void end_thread (private_thread_t *this)
void thread_set_active_condvar (CONDITION_VARIABLE *condvar)
static void WINAPI docancel (ULONG_PTR dwParam)
METHOD (thread_t, cancel, void, private_thread_t *this)
METHOD (thread_t, kill_, void, private_thread_t *this, int sig)
METHOD (thread_t, detach, void, private_thread_t *this)
METHOD (thread_t, join, void *, private_thread_t *this)
static DWORD thread_cb (private_thread_t *this)
thread_t * thread_create (thread_main_t main, void *arg)
thread_t * thread_current ()
u_int thread_current_id ()
void thread_cleanup_push (thread_cleanup_t cb, void *arg)
void thread_cleanup_pop (bool execute)
void thread_cleanup_popall ()
bool thread_cancelability (bool enable)
void thread_cancellation_point ()
void thread_exit (void *val)
static void cleanup_tls ()
BOOL WINAPI DllMain (HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
void threads_init ()
void threads_deinit ()
Variables
static hashtable_t * threads
static spinlock_t * threads_lock
static u_int threads_ids = 0
Typedef Documentation
typedef struct private_thread_t private_thread_t
Definition at line 25 of file windows/thread.c.
Function Documentation
static void cleanup_tls () static
Clean up thread data while it detaches
Definition at line 630 of file windows/thread.c.
References destroy(), FALSE, spinlock_t::lock, hashtable_t::remove, set_leak_detective(), and spinlock_t::unlock.
Referenced by DllMain().
 {
     private_thread_t *this;
     bool old;
     old = set_leak_detective(FALSE);
     threads_lock->lock(threads_lock);
     this = threads->remove(threads, (void*)(uintptr_t)GetCurrentThreadId());
     threads_lock->unlock(threads_lock);
     set_leak_detective(old);
     if (this)
     {
         /* If the thread exited, but has not been joined, it is in terminated
          * state. We must not mangle it, as we target externally spawned
          * threads only. */
         if (!this->terminated && !this->detached)
         {
             destroy(this);
         }
     }
 }
static private_thread_t * create_internal (DWORD id) static
Forward declaration
Create an internal thread object.
Definition at line 442 of file windows/thread.c.
References array_create(), FALSE, handle, hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), id, INIT, spinlock_t::lock, set_leak_detective(), threads_ids, TRUE, and spinlock_t::unlock.
Referenced by get_current_thread(), thread_create(), and threads_init().
 {
     private_thread_t *this;
     bool old;
     old = set_leak_detective(FALSE);
     INIT(this,
         .public = {
             .cancel = _cancel,
             .kill = _kill_,
             .detach = _detach,
             .join = _join,
         },
         .cleanup = array_create(sizeof(cleanup_t), 0),
         .tls = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 4),
         .id = id,
         .cancelability = TRUE,
     );
     set_leak_detective(old);
     threads_lock->lock(threads_lock);
     this->tid = threads_ids++;
     threads_lock->unlock(threads_lock);
     if (id)
     {
         this->handle = OpenThread(THREAD_ALL_ACCESS, FALSE, id);
     }
     return this;
 }
static void destroy (private_thread_t * this) static
Clean up and destroy a thread
Definition at line 295 of file windows/thread.c.
References array_destroy(), cleanup, thread_value_t::destroy, docleanup(), FALSE, free(), handle, set_leak_detective(), and tls.
Referenced by cleanup_tls(), end_thread(), METHOD(), thread_create(), and threads_deinit().
 {
     bool old;
     docleanup(this);
     old = set_leak_detective(FALSE);
     array_destroy(this->cleanup);
     this->tls->destroy(this->tls);
     if (this->handle)
     {
         CloseHandle(this->handle);
     }
     free(this);
     set_leak_detective(old);
 }
BOOL WINAPI DllMain (HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
DllMain called for dll events
Definition at line 658 of file windows/thread.c.
References cleanup_tls(), and TRUE.
 {
     switch (fdwReason)
     {
         case DLL_THREAD_DETACH:
             cleanup_tls();
             break;
         default:
             break;
     }
     return TRUE;
 }
static void WINAPI docancel (ULONG_PTR dwParam) static
APC to cancel a thread
Definition at line 351 of file windows/thread.c.
References end_thread(), spinlock_t::lock, and spinlock_t::unlock.
Referenced by METHOD().
 {
     private_thread_t *this = (private_thread_t*)dwParam;
     /* make sure cancel() does not access this anymore */
     threads_lock->lock(threads_lock);
     threads_lock->unlock(threads_lock);
     end_thread(this);
     ExitThread(0);
 }
static void docleanup (private_thread_t * this) static
Invoke pushed/tls cleanup handlers
Definition at line 261 of file windows/thread.c.
References cleanup_t::arg, array_remove(), cleanup_t::cb, cleanup, enumerator_t::destroy, enumerator_t::enumerate, FALSE, spinlock_t::lock, set_leak_detective(), thread_tls_cleanup(), tls, and spinlock_t::unlock.
Referenced by destroy(), and end_thread().
 {
     enumerator_t *enumerator;
     cleanup_t cleanup, *tls;
     bool old;
     old = set_leak_detective(FALSE);
     while (array_remove(this->cleanup, -1, &cleanup))
     {
         set_leak_detective(old);
         cleanup.cb(cleanup.arg);
         set_leak_detective(FALSE);
     }
     threads_lock->lock(threads_lock);
     enumerator = this->tls->create_enumerator(this->tls);
     while (enumerator->enumerate(enumerator, NULL, &tls))
     {
         this->tls->remove_at(this->tls, enumerator);
         set_leak_detective(old);
         thread_tls_cleanup(tls);
         set_leak_detective(FALSE);
     }
     enumerator->destroy(enumerator);
     threads_lock->unlock(threads_lock);
     set_leak_detective(old);
 }
static void end_thread (private_thread_t * this) static
End a thread, destroy when detached
Definition at line 317 of file windows/thread.c.
References destroy(), docleanup(), remove_thread(), and TRUE.
Referenced by docancel(), thread_cb(), and thread_exit().
 {
     if (this->detached)
     {
         remove_thread(this);
         destroy(this);
     }
     else
     {
         this->terminated = TRUE;
         docleanup(this);
     }
 }
static private_thread_t* get_current_thread () static
Get thread data for calling thread
Definition at line 174 of file windows/thread.c.
References create_internal(), hashtable_t::get, spinlock_t::lock, put_thread(), and spinlock_t::unlock.
Referenced by thread_cancelability(), thread_cleanup_pop(), thread_cleanup_popall(), thread_cleanup_push(), thread_current(), thread_current_id(), thread_exit(), thread_set_active_condvar(), thread_tls_get(), thread_tls_put(), and thread_tls_remove().
 {
     private_thread_t *this;
     threads_lock->lock(threads_lock);
     this = threads->get(threads, (void*)(uintptr_t)GetCurrentThreadId());
     threads_lock->unlock(threads_lock);
     if (!this)
     {
         this = create_internal(GetCurrentThreadId());
         put_thread(this);
     }
     return this;
 }
METHOD (thread_t , cancel , void , private_thread_t * this)
Definition at line 363 of file windows/thread.c.
References condvar, docancel(), handle, spinlock_t::lock, TRUE, and spinlock_t::unlock.
 {
     this->canceled = TRUE;
     if (this->cancelability)
     {
         threads_lock->lock(threads_lock);
         if (!this->cancel_pending)
         {
             this->cancel_pending = TRUE;
             QueueUserAPC(docancel, this->handle, (uintptr_t)this);
             if (this->condvar)
             {
                 WakeAllConditionVariable(this->condvar);
             }
         }
         threads_lock->unlock(threads_lock);
     }
 }
METHOD (thread_t , kill_ , void , private_thread_t * this, int sig)
Definition at line 383 of file windows/thread.c.
 {
 }
METHOD (thread_t , detach , void , private_thread_t * this)
Definition at line 388 of file windows/thread.c.
References TRUE.
 {
     this->detached = TRUE;
 }
METHOD (thread_t , join , void * , private_thread_t * this)
Definition at line 394 of file windows/thread.c.
References destroy(), handle, remove_thread(), and TRUE.
 {
     void *ret;
     if (this->detached)
     {
         return NULL;
     }
     while (!this->terminated)
     {
         /* join is a cancellation point, use alertable wait */
         WaitForSingleObjectEx(this->handle, INFINITE, TRUE);
     }
     ret = this->ret;
     remove_thread(this);
     destroy(this);
     return ret;
 }
static void put_thread (private_thread_t * this) static
Store thread in index
Definition at line 142 of file windows/thread.c.
References FALSE, spinlock_t::lock, hashtable_t::put, set_leak_detective(), and spinlock_t::unlock.
Referenced by get_current_thread(), thread_create(), and threads_init().
 {
     bool old;
     old = set_leak_detective(FALSE);
     threads_lock->lock(threads_lock);
     threads->put(threads, (void*)(uintptr_t)this->id, this);
     threads_lock->unlock(threads_lock);
     set_leak_detective(old);
 }
static void remove_thread (private_thread_t * this) static
Remove thread from index
Definition at line 158 of file windows/thread.c.
References FALSE, spinlock_t::lock, hashtable_t::remove, set_leak_detective(), and spinlock_t::unlock.
Referenced by end_thread(), and METHOD().
 {
     bool old;
     old = set_leak_detective(FALSE);
     threads_lock->lock(threads_lock);
     threads->remove(threads, (void*)(uintptr_t)this->id);
     threads_lock->unlock(threads_lock);
     set_leak_detective(old);
 }
static bool set_leak_detective (bool state) inline static
Set leak detective state
Definition at line 128 of file windows/thread.c.
References FALSE, library_t::leak_detective, lib, and leak_detective_t::set_state.
Referenced by cleanup_tls(), create_internal(), destroy(), docleanup(), put_thread(), remove_thread(), thread_cleanup_pop(), thread_cleanup_popall(), thread_cleanup_push(), thread_tls_get(), thread_tls_put(), and thread_tls_remove().
 {
 #ifdef LEAK_DETECTIVE
     if (lib && lib->leak_detective)
     {
         return lib->leak_detective->set_state(lib->leak_detective, state);
     }
 #endif
     return FALSE;
 }
static DWORD thread_cb (private_thread_t * this) static
Main function wrapper for threads
Definition at line 421 of file windows/thread.c.
References cancel(), end_thread(), main(), and TRUE.
Referenced by thread_create().
 {
     /* Enable cancelability once the thread starts. We must check for any
      * pending cancellation request an queue the APC that gets executed
      * at the first cancellation point. */
     this->cancelability = TRUE;
     if (this->canceled)
     {
         cancel(this);
     }
     this->ret = this->main(this->arg);
     end_thread(this);
     return 0;
 }
Variable Documentation
hashtable_t* threads static
Global list of threads, GetCurrentThreadId() => private_thread_t
Definition at line 108 of file windows/thread.c.
Referenced by main(), METHOD(), resolve_hosts(), restart(), and START_TEST().
u_int threads_ids = 0 static
Counter to assign printable thread IDs
Definition at line 118 of file windows/thread.c.
Referenced by create_internal(), and threads_init().
spinlock_t* threads_lock static
Lock for threads table
Definition at line 113 of file windows/thread.c.