strongSwan: simaka_message
simaka_message
libsimaka
Classes
struct simaka_message_t
Typedefs
typedef enum simaka_attribute_t simaka_attribute_t
typedef enum simaka_subtype_t simaka_subtype_t
typedef enum simaka_notification_t simaka_notification_t
typedef enum simaka_client_error_t simaka_client_error_t
typedef struct simaka_message_t simaka_message_t
Enumerations
enum simaka_subtype_t {
AKA_CHALLENGE = 1, AKA_AUTHENTICATION_REJECT = 2, AKA_SYNCHRONIZATION_FAILURE = 4, AKA_IDENTITY = 5,
SIM_START = 10, SIM_CHALLENGE = 11, SIM_NOTIFICATION = 12, AKA_NOTIFICATION = 12,
SIM_REAUTHENTICATION = 13, AKA_REAUTHENTICATION = 13, SIM_CLIENT_ERROR = 14, AKA_CLIENT_ERROR = 14
}
enum simaka_attribute_t {
AT_RAND = 1, AT_AUTN = 2, AT_RES = 3, AT_AUTS = 4,
AT_PADDING = 6, AT_NONCE_MT = 7, AT_PERMANENT_ID_REQ = 10, AT_MAC = 11,
AT_NOTIFICATION = 12, AT_ANY_ID_REQ = 13, AT_IDENTITY = 14, AT_VERSION_LIST = 15,
AT_SELECTED_VERSION = 16, AT_FULLAUTH_ID_REQ = 17, AT_COUNTER = 19, AT_COUNTER_TOO_SMALL = 20,
AT_NONCE_S = 21, AT_CLIENT_ERROR_CODE = 22, AT_IV = 129, AT_ENCR_DATA = 130,
AT_NEXT_PSEUDONYM = 132, AT_NEXT_REAUTH_ID = 133, AT_CHECKCODE = 134, AT_RESULT_IND = 135
}
enum simaka_notification_t {
SIM_GENERAL_FAILURE_AA = 0, AKA_GENERAL_FAILURE_AA = 0, SIM_GENERAL_FAILURE = 16384, AKA_GENERAL_FAILURE = 16384,
SIM_TEMP_DENIED = 1026, AKA_TEMP_DENIED = 1026, SIM_NOT_SUBSCRIBED = 1031, AKA_NOT_SUBSCRIBED = 1031,
SIM_SUCCESS = 32768, AKA_SUCCESS = 32768
}
enum simaka_client_error_t {
AKA_UNABLE_TO_PROCESS = 0, SIM_UNABLE_TO_PROCESS = 0, SIM_UNSUPPORTED_VERSION = 1, SIM_INSUFFICIENT_CHALLENGES = 2,
SIM_RANDS_NOT_FRESH = 3
}
Functions
bool simaka_attribute_skippable (simaka_attribute_t attribute)
simaka_message_t * simaka_message_create (bool request, u_int8_t identifier, eap_type_t type, simaka_subtype_t subtype, simaka_crypto_t *crypto)
simaka_message_t * simaka_message_create_from_payload (chunk_t data, simaka_crypto_t *crypto)
Variables
enum_name_t * simaka_subtype_names
enum_name_t * simaka_attribute_names
enum_name_t * simaka_notification_names
enum_name_t * simaka_client_error_names
Detailed Description
Typedef Documentation
typedef enum simaka_attribute_t simaka_attribute_t
Definition at line 34 of file simaka_message.h.
typedef enum simaka_client_error_t simaka_client_error_t
Definition at line 37 of file simaka_message.h.
typedef struct simaka_message_t simaka_message_t
Definition at line 38 of file simaka_message.h.
typedef enum simaka_notification_t simaka_notification_t
Definition at line 36 of file simaka_message.h.
typedef enum simaka_subtype_t simaka_subtype_t
Definition at line 35 of file simaka_message.h.
Enumeration Type Documentation
enum simaka_attribute_t
Attributes in EAP-SIM/AKA messages
Enumerator
AT_RAND
AT_AUTN
AT_RES
AT_AUTS
AT_PADDING
AT_NONCE_MT
AT_PERMANENT_ID_REQ
AT_MAC
AT_NOTIFICATION
AT_ANY_ID_REQ
AT_IDENTITY
AT_VERSION_LIST
AT_SELECTED_VERSION
AT_FULLAUTH_ID_REQ
AT_COUNTER
AT_COUNTER_TOO_SMALL
AT_NONCE_S
AT_CLIENT_ERROR_CODE
AT_IV
AT_ENCR_DATA
AT_NEXT_PSEUDONYM
AT_NEXT_REAUTH_ID
AT_CHECKCODE
AT_RESULT_IND
Definition at line 66 of file simaka_message.h.
{
     AT_RAND = 1,
     AT_AUTN = 2,
     AT_RES = 3,
     AT_AUTS = 4,
     AT_PADDING = 6,
     AT_NONCE_MT = 7,
     AT_PERMANENT_ID_REQ = 10,
     AT_MAC = 11,
     AT_NOTIFICATION = 12,
     AT_ANY_ID_REQ = 13,
     AT_IDENTITY = 14,
     AT_VERSION_LIST = 15,
     AT_SELECTED_VERSION = 16,
     AT_FULLAUTH_ID_REQ = 17,
     AT_COUNTER = 19,
     AT_COUNTER_TOO_SMALL = 20,
     AT_NONCE_S = 21,
     AT_CLIENT_ERROR_CODE = 22,
     AT_IV = 129,
     AT_ENCR_DATA = 130,
     AT_NEXT_PSEUDONYM = 132,
     AT_NEXT_REAUTH_ID = 133,
     AT_CHECKCODE = 134,
     AT_RESULT_IND = 135,
 };
enum simaka_client_error_t
Error codes sent in AT_CLIENT_ERROR_CODE attribute
Enumerator
AKA_UNABLE_TO_PROCESS
AKA unable to process packet
SIM_UNABLE_TO_PROCESS
SIM unable to process packet
SIM_UNSUPPORTED_VERSION
SIM unsupported version
SIM_INSUFFICIENT_CHALLENGES
SIM insufficient number of challenges
SIM_RANDS_NOT_FRESH
SIM RANDs are not fresh
Definition at line 132 of file simaka_message.h.
{
     AKA_UNABLE_TO_PROCESS = 0,
     SIM_UNABLE_TO_PROCESS = 0,
     SIM_UNSUPPORTED_VERSION = 1,
     SIM_INSUFFICIENT_CHALLENGES = 2,
     SIM_RANDS_NOT_FRESH = 3,
 };
enum simaka_notification_t
Notification codes used within AT_NOTIFICATION attribute.
Enumerator
SIM_GENERAL_FAILURE_AA
SIM General failure after authentication. (Implies failure)
AKA_GENERAL_FAILURE_AA
AKA General failure after authentication. (Implies failure)
SIM_GENERAL_FAILURE
SIM General failure. (Implies failure, used before authentication)
AKA_GENERAL_FAILURE
AKA General failure. (Implies failure, used before authentication)
SIM_TEMP_DENIED
SIM User has been temporarily denied access to the requested service.
AKA_TEMP_DENIED
AKA User has been temporarily denied access to the requested service.
SIM_NOT_SUBSCRIBED
SIM User has not subscribed to the requested service.
AKA_NOT_SUBSCRIBED
AKA User has not subscribed to the requested service.
SIM_SUCCESS
SIM Success. User has been successfully authenticated.
AKA_SUCCESS
AKA Success. User has been successfully authenticated.
Definition at line 101 of file simaka_message.h.
{
     SIM_GENERAL_FAILURE_AA = 0,
     AKA_GENERAL_FAILURE_AA = 0,
     SIM_GENERAL_FAILURE = 16384,
     AKA_GENERAL_FAILURE = 16384,
     SIM_TEMP_DENIED = 1026,
     AKA_TEMP_DENIED = 1026,
     SIM_NOT_SUBSCRIBED = 1031,
     AKA_NOT_SUBSCRIBED = 1031,
     SIM_SUCCESS = 32768,
     AKA_SUCCESS = 32768,
 };
enum simaka_subtype_t
Subtypes of EAP-SIM/AKA messages
Enumerator
AKA_CHALLENGE
AKA_AUTHENTICATION_REJECT
AKA_SYNCHRONIZATION_FAILURE
AKA_IDENTITY
SIM_START
SIM_CHALLENGE
SIM_NOTIFICATION
AKA_NOTIFICATION
SIM_REAUTHENTICATION
AKA_REAUTHENTICATION
SIM_CLIENT_ERROR
AKA_CLIENT_ERROR
Definition at line 43 of file simaka_message.h.
                       {
     AKA_CHALLENGE = 1,
     AKA_AUTHENTICATION_REJECT = 2,
     AKA_SYNCHRONIZATION_FAILURE = 4,
     AKA_IDENTITY = 5,
     SIM_START = 10,
     SIM_CHALLENGE = 11,
     SIM_NOTIFICATION = 12,
     AKA_NOTIFICATION = 12,
     SIM_REAUTHENTICATION = 13,
     AKA_REAUTHENTICATION = 13,
     SIM_CLIENT_ERROR = 14,
     AKA_CLIENT_ERROR = 14,
 };
Function Documentation
bool simaka_attribute_skippable (simaka_attribute_t attribute)
Check if an EAP-SIM/AKA attribute is "skippable".
Parameters
attribute attribute to check
Returns
TRUE if attribute skippable, FALSE if non-skippable
Check if an EAP-SIM/AKA attribute is skippable
Definition at line 140 of file simaka_message.c.
References DBG1, DBG_LIB, and simaka_attribute_names.
Referenced by process_challenge(), process_client_error(), process_identity(), process_notification(), process_reauthentication(), process_start(), and process_synchronize().
 {
     bool skippable = !((int)attribute >= 0 && attribute <= 127);
     DBG1(DBG_LIB, "%sskippable EAP-SIM/AKA attribute %N",
          skippable ? "ignoring " : "found non-",
          simaka_attribute_names, attribute);
     return skippable;
 }
simaka_message_t* simaka_message_create (bool request, u_int8_t identifier, eap_type_t type, simaka_subtype_t subtype, simaka_crypto_t * crypto)
Create an empty simaka_message.
Parameters
request TRUE for a request message, FALSE for a response
identifier EAP message identifier
type EAP type: EAP-SIM or EAP-AKA
subtype subtype of the EAP message
crypto EAP-SIM/AKA crypto helper
Returns
empty message of requested kind, NULL on error
See header.
Definition at line 915 of file simaka_message.c.
References chunk_create(), hdr_t::code, EAP_REQUEST, EAP_RESPONSE, identifier, simaka_message_create_data(), subtype, and type.
Referenced by challenge(), create_client_error(), identity(), METHOD(), process_challenge(), process_identity(), process_notification(), process_reauthentication(), process_start(), and reauthenticate().
 {
     hdr_t hdr = {
         .code = request ? EAP_REQUEST : EAP_RESPONSE,
         .identifier = identifier,
         .length = htons(sizeof(hdr_t)),
         .type = type,
         .subtype = subtype,
     };
     return simaka_message_create_data(chunk_create((char*)&hdr, sizeof(hdr)),
                                       crypto);
 }
simaka_message_t* simaka_message_create_from_payload (chunk_t data, simaka_crypto_t * crypto)
Create an simaka_message from a chunk of data.
Parameters
data message data to parse
crypto EAP-SIM/AKA crypto helper
Returns
EAP message, NULL on error
See header.
Definition at line 906 of file simaka_message.c.
References simaka_message_create_data().
Referenced by METHOD().
 {
     return simaka_message_create_data(data, crypto);
 }
Variable Documentation
enum_name_t* simaka_attribute_names
Enum names for simaka_attribute_t
Referenced by invalid_length(), METHOD(), not_encrypted(), process_reauthentication(), and simaka_attribute_skippable().
enum_name_t* simaka_client_error_names
Enum names for simaka_client_error_t
Referenced by create_client_error(), and process_client_error().
enum_name_t* simaka_notification_names
Enum names for simaka_notification_t
Referenced by process_notification().
enum_name_t* simaka_subtype_names
Enum names for simaka_subtype_t
Referenced by METHOD(), process_authentication_reject(), process_challenge(), process_identity(), process_reauthentication(), process_start(), and process_synchronize().