strongSwan: test_runner
test_runner
libtest
Classes
struct test_configuration_t
Typedefs
typedef struct test_configuration_t test_configuration_t
typedef bool(* test_runner_init_t)(bool init)
Functions
int test_runner_run (const char *name, test_configuration_t config[], test_runner_init_t init_cb)
Detailed Description
Typedef Documentation
typedef struct test_configuration_t test_configuration_t
Definition at line 33 of file test_runner.h.
typedef bool(* test_runner_init_t)(bool init)
Callback called before and after each test case to de-/initialize the environment (e.g. to load plugins). It is also called before and after the test suites are loaded.
It is called after libstrongswan has been initialized and likewise before it gets deinitialized.
Parameters
init TRUE during initialization
Returns
FALSE if de-/init failed
Definition at line 46 of file test_runner.h.
Function Documentation
int test_runner_run (const char * name, test_configuration_t configs[], test_runner_init_t init)
Run test configuration.
The configs array must be terminated with a NULL element. The following environment variables are currently supported:
TESTS_VERBOSITY: Numerical loglevel for debug log
TESTS_STRONGSWAN_CONF: Specify a path to a custom strongswan.conf
TESTS_PLUGINS: Specify an explicit list of plugins to load
TESTS_SUITES: Run specific test suites only
TESTS_SUITES_EXCLUDE: Don't run specific test suites
TESTS_REDUCED_KEYLENGTHS: Test minimal keylengths for public key tests only
Please note that TESTS_PLUGINS actually must be implemented by the init callback function, as plugin loading is delegated.
Parameters
name name of test runner
config test suite constructors with dependencies
init_cb init/deinit callback
Returns
test result, EXIT_SUCCESS if all tests passed
See header.
Definition at line 519 of file test_runner.c.
References array_count(), array_create_enumerator(), dbg_default_set_level(), enumerator_t::destroy, enumerator_t::enumerate, fprintf, LEVEL_SILENT, load_suites(), result, run_suite(), TTY, and unload_suites().
Referenced by main().
 {
     array_t *suites;
     test_suite_t *suite;
     enumerator_t *enumerator;
     int passed = 0, result;
     level_t level = LEVEL_SILENT;
     char *cfg, *verbosity;
     /* redirect all output to stderr (to redirect make's stdout to /dev/null) */
     dup2(2, 1);
     cfg = getenv("TESTS_STRONGSWAN_CONF");
     suites = load_suites(configs, init, cfg);
     if (!suites)
     {
         return EXIT_FAILURE;
     }
     verbosity = getenv("TESTS_VERBOSITY");
     if (verbosity)
     {
         level = atoi(verbosity);
     }
     dbg_default_set_level(level);
     fprintf(stderr, "Running %u '%s' test suites:\n", array_count(suites), name);
     enumerator = array_create_enumerator(suites);
     while (enumerator->enumerate(enumerator, &suite))
     {
         if (run_suite(suite, init, cfg))
         {
             passed++;
         }
     }
     enumerator->destroy(enumerator);
     if (passed == array_count(suites))
     {
         fprintf(stderr, "%sPassed all %u '%s' suites%s\n",
                 TTY(GREEN), array_count(suites), name, TTY(DEF));
         result = EXIT_SUCCESS;
     }
     else
     {
         fprintf(stderr, "%sPassed %u of %u '%s' suites%s\n",
                 TTY(RED), passed, array_count(suites), name, TTY(DEF));
         result = EXIT_FAILURE;
     }
     unload_suites(suites);
     return result;
 }