strongSwan: child_sa.c File Reference
child_sa.c File Reference
#include "child_sa.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <hydra.h>
#include <daemon.h>
#include <collections/array.h>
Classes
struct private_child_sa_t
struct policy_enumerator_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct private_child_sa_t private_child_sa_t
typedef struct policy_enumerator_t policy_enumerator_t
Functions
ENUM (child_sa_state_names, CHILD_CREATED, CHILD_DESTROYING,"CREATED","ROUTED","INSTALLING","INSTALLED","UPDATING","REKEYING","REKEYED","RETRYING","DELETING","DESTROYING",)
static u_int8_t proto_ike2ip (protocol_id_t protocol)
METHOD (child_sa_t, get_name, char *, private_child_sa_t *this)
METHOD (child_sa_t, get_reqid, u_int32_t, private_child_sa_t *this)
METHOD (child_sa_t, get_unique_id, u_int32_t, private_child_sa_t *this)
METHOD (child_sa_t, get_config, child_cfg_t *, private_child_sa_t *this)
METHOD (child_sa_t, set_state, void, private_child_sa_t *this, child_sa_state_t state)
METHOD (child_sa_t, get_state, child_sa_state_t, private_child_sa_t *this)
METHOD (child_sa_t, get_spi, u_int32_t, private_child_sa_t *this, bool inbound)
METHOD (child_sa_t, get_cpi, u_int16_t, private_child_sa_t *this, bool inbound)
METHOD (child_sa_t, get_protocol, protocol_id_t, private_child_sa_t *this)
METHOD (child_sa_t, set_protocol, void, private_child_sa_t *this, protocol_id_t protocol)
METHOD (child_sa_t, get_mode, ipsec_mode_t, private_child_sa_t *this)
METHOD (child_sa_t, set_mode, void, private_child_sa_t *this, ipsec_mode_t mode)
METHOD (child_sa_t, has_encap, bool, private_child_sa_t *this)
METHOD (child_sa_t, get_ipcomp, ipcomp_transform_t, private_child_sa_t *this)
METHOD (child_sa_t, set_ipcomp, void, private_child_sa_t *this, ipcomp_transform_t ipcomp)
METHOD (child_sa_t, set_close_action, void, private_child_sa_t *this, action_t action)
METHOD (child_sa_t, get_close_action, action_t, private_child_sa_t *this)
METHOD (child_sa_t, set_dpd_action, void, private_child_sa_t *this, action_t action)
METHOD (child_sa_t, get_dpd_action, action_t, private_child_sa_t *this)
METHOD (child_sa_t, get_proposal, proposal_t *, private_child_sa_t *this)
METHOD (child_sa_t, set_proposal, void, private_child_sa_t *this, proposal_t *proposal)
METHOD (child_sa_t, create_ts_enumerator, enumerator_t *, private_child_sa_t *this, bool local)
METHOD (enumerator_t, policy_enumerate, bool, policy_enumerator_t *this, traffic_selector_t **my_out, traffic_selector_t **other_out)
METHOD (enumerator_t, policy_destroy, void, policy_enumerator_t *this)
METHOD (child_sa_t, create_policy_enumerator, enumerator_t *, private_child_sa_t *this)
static status_t update_usebytes (private_child_sa_t *this, bool inbound)
static bool update_usetime (private_child_sa_t *this, bool inbound)
METHOD (child_sa_t, get_usestats, void, private_child_sa_t *this, bool inbound, time_t *time, u_int64_t *bytes, u_int64_t *packets)
METHOD (child_sa_t, get_mark, mark_t, private_child_sa_t *this, bool inbound)
METHOD (child_sa_t, get_lifetime, time_t, private_child_sa_t *this, bool hard)
METHOD (child_sa_t, get_installtime, time_t, private_child_sa_t *this)
METHOD (child_sa_t, alloc_spi, u_int32_t, private_child_sa_t *this, protocol_id_t protocol)
METHOD (child_sa_t, alloc_cpi, u_int16_t, private_child_sa_t *this)
METHOD (child_sa_t, install, status_t, private_child_sa_t *this, chunk_t encr, chunk_t integ, u_int32_t spi, u_int16_t cpi, bool initiator, bool inbound, bool tfcv3, linked_list_t *my_ts, linked_list_t *other_ts)
static bool require_policy_update ()
static void prepare_sa_cfg (private_child_sa_t *this, ipsec_sa_cfg_t *my_sa, ipsec_sa_cfg_t *other_sa)
static status_t install_policies_internal (private_child_sa_t *this, host_t *my_addr, host_t *other_addr, traffic_selector_t *my_ts, traffic_selector_t *other_ts, ipsec_sa_cfg_t *my_sa, ipsec_sa_cfg_t *other_sa, policy_type_t type, policy_priority_t priority)
static void del_policies_internal (private_child_sa_t *this, host_t *my_addr, host_t *other_addr, traffic_selector_t *my_ts, traffic_selector_t *other_ts, ipsec_sa_cfg_t *my_sa, ipsec_sa_cfg_t *other_sa, policy_type_t type, policy_priority_t priority)
METHOD (child_sa_t, add_policies, status_t, private_child_sa_t *this, linked_list_t *my_ts_list, linked_list_t *other_ts_list)
static void reinstall_vip (host_t *vip, host_t *me)
METHOD (child_sa_t, update, status_t, private_child_sa_t *this, host_t *me, host_t *other, linked_list_t *vips, bool encap)
METHOD (child_sa_t, destroy, void, private_child_sa_t *this)
static host_t * get_proxy_addr (child_cfg_t *config, host_t *ike, bool local)
child_sa_t * child_sa_create (host_t *me, host_t *other, child_cfg_t *config, u_int32_t rekey, bool encap, u_int mark_in, u_int mark_out)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 19 of file child_sa.c.
Typedef Documentation
typedef struct policy_enumerator_t policy_enumerator_t
Definition at line 373 of file child_sa.c.
typedef struct private_child_sa_t private_child_sa_t
Definition at line 43 of file child_sa.c.
Function Documentation
static void del_policies_internal (private_child_sa_t * this, host_t * my_addr, host_t * other_addr, traffic_selector_t * my_ts, traffic_selector_t * other_ts, ipsec_sa_cfg_t * my_sa, ipsec_sa_cfg_t * other_sa, policy_type_t type, policy_priority_t priority) static
Delete 3 policies: out, in and forward
Definition at line 858 of file child_sa.c.
References kernel_interface_t::del_policy, hydra, hydra_t::kernel_interface, MODE_TRANSPORT, POLICY_FWD, POLICY_IN, and POLICY_OUT.
Referenced by METHOD().
 {
     hydra->kernel_interface->del_policy(hydra->kernel_interface,
                         my_addr, other_addr, my_ts, other_ts, POLICY_OUT, type,
                         other_sa, this->mark_out, priority);
     hydra->kernel_interface->del_policy(hydra->kernel_interface,
                         other_addr, my_addr, other_ts, my_ts, POLICY_IN,
                         type, my_sa, this->mark_in, priority);
     if (this->mode != MODE_TRANSPORT)
     {
         hydra->kernel_interface->del_policy(hydra->kernel_interface,
                         other_addr, my_addr, other_ts, my_ts, POLICY_FWD,
                         type, my_sa, this->mark_in, priority);
     }
 }
ENUM (child_sa_state_names , CHILD_CREATED , CHILD_DESTROYING , "CREATED" , "ROUTED" , "INSTALLING" , "INSTALLED" , "UPDATING" , "REKEYING" , "REKEYED" , "RETRYING" , "DELETING" , "DESTROYING")
static host_t* get_proxy_addr (child_cfg_t * config, host_t * ike, bool local) static
Get proxy address for one side, if any
Definition at line 1180 of file child_sa.c.
References host_t::clone, linked_list_t::create_enumerator, DBG1, DBG_CHD, enumerator_t::destroy, linked_list_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, child_cfg_t::get_traffic_selectors, host, traffic_selector_t::is_host, linked_list_create_with_items(), list, mask, and traffic_selector_t::to_subnet.
Referenced by child_sa_create().
 {
     host_t *host = NULL;
     u_int8_t mask;
     enumerator_t *enumerator;
     linked_list_t *ts_list, *list;
     traffic_selector_t *ts;
     list = linked_list_create_with_items(ike, NULL);
     ts_list = config->get_traffic_selectors(config, local, NULL, list);
     list->destroy(list);
     enumerator = ts_list->create_enumerator(ts_list);
     while (enumerator->enumerate(enumerator, &ts))
     {
         if (ts->is_host(ts, NULL) && ts->to_subnet(ts, &host, &mask))
         {
             DBG1(DBG_CHD, "%s address: %H is a transport mode proxy for %H",
                  local ? "my" : "other", ike, host);
             break;
         }
     }
     enumerator->destroy(enumerator);
     ts_list->destroy_offset(ts_list, offsetof(traffic_selector_t, destroy));
     if (!host)
     {
         host = ike->clone(ike);
     }
     return host;
 }
static status_t install_policies_internal (private_child_sa_t * this, host_t * my_addr, host_t * other_addr, traffic_selector_t * my_ts, traffic_selector_t * other_ts, ipsec_sa_cfg_t * my_sa, ipsec_sa_cfg_t * other_sa, policy_type_t type, policy_priority_t priority) static
Install 3 policies: out, in and forward
Definition at line 830 of file child_sa.c.
References kernel_interface_t::add_policy, hydra, hydra_t::kernel_interface, MODE_TRANSPORT, POLICY_FWD, POLICY_IN, POLICY_OUT, status, and SUCCESS.
Referenced by METHOD().
 {
     status_t status = SUCCESS;
     status |= hydra->kernel_interface->add_policy(hydra->kernel_interface,
                             my_addr, other_addr, my_ts, other_ts,
                             POLICY_OUT, type, other_sa,
                             this->mark_out, priority);
     status |= hydra->kernel_interface->add_policy(hydra->kernel_interface,
                             other_addr, my_addr, other_ts, my_ts,
                             POLICY_IN, type, my_sa,
                             this->mark_in, priority);
     if (this->mode != MODE_TRANSPORT)
     {
         status |= hydra->kernel_interface->add_policy(hydra->kernel_interface,
                             other_addr, my_addr, other_ts, my_ts,
                             POLICY_FWD, type, my_sa,
                             this->mark_in, priority);
     }
     return status;
 }
METHOD (child_sa_t , get_name , char * , private_child_sa_t * this)
Definition at line 236 of file child_sa.c.
 {
     return this->config->get_name(this->config);
 }
METHOD (child_sa_t , get_reqid , u_int32_t , private_child_sa_t * this)
Definition at line 242 of file child_sa.c.
 {
     return this->reqid;
 }
METHOD (child_sa_t , get_unique_id , u_int32_t , private_child_sa_t * this)
Definition at line 248 of file child_sa.c.
References unique_id.
 {
     return this->unique_id;
 }
METHOD (child_sa_t , get_config , child_cfg_t * , private_child_sa_t * this)
Definition at line 254 of file child_sa.c.
 {
     return this->config;
 }
METHOD (child_sa_t , set_state , void , private_child_sa_t * this, child_sa_state_t state)
Definition at line 260 of file child_sa.c.
References daemon_t::bus, charon, and bus_t::child_state_change.
 {
     charon->bus->child_state_change(charon->bus, &this->public, state);
     this->state = state;
 }
METHOD (child_sa_t , get_state , child_sa_state_t , private_child_sa_t * this)
Definition at line 267 of file child_sa.c.
 {
     return this->state;
 }
METHOD (child_sa_t , get_spi , u_int32_t , private_child_sa_t * this, bool inbound)
Definition at line 273 of file child_sa.c.
 {
     return inbound ? this->my_spi : this->other_spi;
 }
METHOD (child_sa_t , get_cpi , u_int16_t , private_child_sa_t * this, bool inbound)
Definition at line 279 of file child_sa.c.
 {
     return inbound ? this->my_cpi : this->other_cpi;
 }
METHOD (child_sa_t , get_protocol , protocol_id_t , private_child_sa_t * this)
Definition at line 285 of file child_sa.c.
References protocol.
 {
     return this->protocol;
 }
METHOD (child_sa_t , set_protocol , void , private_child_sa_t * this, protocol_id_t protocol)
Definition at line 291 of file child_sa.c.
References protocol.
 {
     this->protocol = protocol;
 }
METHOD (child_sa_t , get_mode , ipsec_mode_t , private_child_sa_t * this)
Definition at line 297 of file child_sa.c.
 {
     return this->mode;
 }
METHOD (child_sa_t , set_mode , void , private_child_sa_t * this, ipsec_mode_t mode)
Definition at line 303 of file child_sa.c.
 {
     this->mode = mode;
 }
METHOD (child_sa_t , has_encap , bool , private_child_sa_t * this)
Definition at line 309 of file child_sa.c.
 {
     return this->encap;
 }
METHOD (child_sa_t , get_ipcomp , ipcomp_transform_t , private_child_sa_t * this)
Definition at line 315 of file child_sa.c.
 {
     return this->ipcomp;
 }
METHOD (child_sa_t , set_ipcomp , void , private_child_sa_t * this, ipcomp_transform_t ipcomp)
Definition at line 321 of file child_sa.c.
 {
     this->ipcomp = ipcomp;
 }
METHOD (child_sa_t , set_close_action , void , private_child_sa_t * this, action_t action)
Definition at line 327 of file child_sa.c.
 {
     this->close_action = action;
 }
METHOD (child_sa_t , get_close_action , action_t , private_child_sa_t * this)
Definition at line 333 of file child_sa.c.
 {
     return this->close_action;
 }
METHOD (child_sa_t , set_dpd_action , void , private_child_sa_t * this, action_t action)
Definition at line 339 of file child_sa.c.
 {
     this->dpd_action = action;
 }
METHOD (child_sa_t , get_dpd_action , action_t , private_child_sa_t * this)
Definition at line 345 of file child_sa.c.
 {
     return this->dpd_action;
 }
METHOD (child_sa_t , get_proposal , proposal_t * , private_child_sa_t * this)
Definition at line 351 of file child_sa.c.
References proposal.
 {
     return this->proposal;
 }
METHOD (child_sa_t , set_proposal , void , private_child_sa_t * this, proposal_t * proposal)
Definition at line 357 of file child_sa.c.
References proposal_t::clone.
 {
     this->proposal = proposal->clone(proposal);
 }
METHOD (child_sa_t , create_ts_enumerator , enumerator_t * , private_child_sa_t * this, bool local)
Definition at line 363 of file child_sa.c.
References array_create_enumerator().
 {
     if (local)
     {
         return array_create_enumerator(this->my_ts);
     }
     return array_create_enumerator(this->other_ts);
 }
METHOD (enumerator_t , policy_enumerate , bool , policy_enumerator_t * this, traffic_selector_t ** my_out, traffic_selector_t ** other_out)
Definition at line 391 of file child_sa.c.
References array_create_enumerator(), traffic_selector_t::destroy, FALSE, traffic_selector_t::get_protocol, traffic_selector_t::get_type, and TRUE.
 {
     traffic_selector_t *other_ts;
     while (this->ts || this->mine->enumerate(this->mine, &this->ts))
     {
         if (!this->other->enumerate(this->other, &other_ts))
         {   /* end of others list, restart with new of mine */
             this->other->destroy(this->other);
             this->other = array_create_enumerator(this->array);
             this->ts = NULL;
             continue;
         }
         if (this->ts->get_type(this->ts) != other_ts->get_type(other_ts))
         {   /* family mismatch */
             continue;
         }
         if (this->ts->get_protocol(this->ts) &&
             other_ts->get_protocol(other_ts) &&
             this->ts->get_protocol(this->ts) != other_ts->get_protocol(other_ts))
         {   /* protocol mismatch */
             continue;
         }
         if (my_out)
         {
             *my_out = this->ts;
         }
         if (other_out)
         {
             *other_out = other_ts;
         }
         return TRUE;
     }
     return FALSE;
 }
METHOD (enumerator_t , policy_destroy , void , policy_enumerator_t * this)
Definition at line 429 of file child_sa.c.
References free().
 {
     this->mine->destroy(this->mine);
     this->other->destroy(this->other);
     free(this);
 }
METHOD (child_sa_t , create_policy_enumerator , enumerator_t * , private_child_sa_t * this)
Definition at line 437 of file child_sa.c.
References array_create_enumerator(), destroy(), INIT, and policy_enumerator_t::public.
 {
     policy_enumerator_t *e;
     INIT(e,
         .public = {
             .enumerate = (void*)_policy_enumerate,
             .destroy = _policy_destroy,
         },
         .mine = array_create_enumerator(this->my_ts),
         .other = array_create_enumerator(this->other_ts),
         .array = this->other_ts,
         .ts = NULL,
     );
     return &e->public;
 }
METHOD (child_sa_t , get_usestats , void , private_child_sa_t * this, bool inbound, time_t * time, u_int64_t * bytes, u_int64_t * packets)
Definition at line 575 of file child_sa.c.
References FAILED, update_usebytes(), and update_usetime().
 {
     if ((!bytes && !packets) || update_usebytes(this, inbound) != FAILED)
     {
         /* there was traffic since last update or the kernel interface
          * does not support querying the number of usebytes.
          */
         if (time)
         {
             if (!update_usetime(this, inbound) && !bytes && !packets)
             {
                 /* if policy query did not yield a usetime, query SAs instead */
                 update_usebytes(this, inbound);
             }
         }
     }
     if (time)
     {
         *time = inbound ? this->my_usetime : this->other_usetime;
     }
     if (bytes)
     {
         *bytes = inbound ? this->my_usebytes : this->other_usebytes;
     }
     if (packets)
     {
         *packets = inbound ? this->my_usepackets : this->other_usepackets;
     }
 }
METHOD (child_sa_t , get_mark , mark_t , private_child_sa_t * this, bool inbound)
Definition at line 607 of file child_sa.c.
 {
     if (inbound)
     {
         return this->mark_in;
     }
     return this->mark_out;
 }
METHOD (child_sa_t , get_lifetime , time_t , private_child_sa_t * this, bool hard)
Definition at line 617 of file child_sa.c.
 {
     return hard ? this->expire_time : this->rekey_time;
 }
METHOD (child_sa_t , get_installtime , time_t , private_child_sa_t * this)
Definition at line 623 of file child_sa.c.
 {
     return this->install_time;
 }
METHOD (child_sa_t , alloc_spi , u_int32_t , private_child_sa_t * this, protocol_id_t protocol)
Definition at line 629 of file child_sa.c.
References kernel_interface_t::get_spi, hydra, hydra_t::kernel_interface, proto_ike2ip(), protocol, and SUCCESS.
 {
     if (hydra->kernel_interface->get_spi(hydra->kernel_interface,
                                          this->other_addr, this->my_addr,
                                          proto_ike2ip(protocol),
                                          &this->my_spi) == SUCCESS)
     {
         /* if we allocate a SPI, but then are unable to establish the SA, we
          * need to know the protocol family to delete the partial SA */
         this->protocol = protocol;
         return this->my_spi;
     }
     return 0;
 }
METHOD (child_sa_t , alloc_cpi , u_int16_t , private_child_sa_t * this)
Definition at line 645 of file child_sa.c.
References kernel_interface_t::get_cpi, hydra, hydra_t::kernel_interface, and SUCCESS.
 {
     if (hydra->kernel_interface->get_cpi(hydra->kernel_interface,
                                          this->other_addr, this->my_addr,
                                          &this->my_cpi) == SUCCESS)
     {
         return this->my_cpi;
     }
     return 0;
 }
METHOD (child_sa_t , install , status_t , private_child_sa_t * this, chunk_t encr, chunk_t integ, u_int32_t spi, u_int16_t cpi, bool initiator, bool inbound, bool tfcv3, linked_list_t * my_ts, linked_list_t * other_ts)
Definition at line 657 of file child_sa.c.
References kernel_interface_t::add_sa, kernel_interface_t::alloc_reqid, AUTH_UNDEFINED, DBG2, DBG_CHD, dst, ENCR_UNDEFINED, ENCRYPTION_ALGORITHM, EXTENDED_SEQUENCE_NUMBERS, FALSE, free(), hydra, initiator, INTEGRITY_ALGORITHM, lifetime_cfg_t::jitter, hydra_t::kernel_interface, lifetime_cfg_t::life, min, NO_EXT_SEQ_NUMBERS, proposal, proto_ike2ip(), protocol, protocol_id_names, lifetime_cfg_t::rekey, size, src, status, SUCCESS, lifetime_cfg_t::time, time_monotonic(), TRUE, and update().
 {
     u_int16_t enc_alg = ENCR_UNDEFINED, int_alg = AUTH_UNDEFINED, size;
     u_int16_t esn = NO_EXT_SEQ_NUMBERS;
     linked_list_t *src_ts = NULL, *dst_ts = NULL;
     time_t now;
     lifetime_cfg_t *lifetime;
     u_int32_t tfc = 0;
     host_t *src, *dst;
     status_t status;
     bool update = FALSE;
     /* now we have to decide which spi to use. Use self allocated, if "in",
      * or the one in the proposal, if not "in" (others). Additionally,
      * source and dest host switch depending on the role */
     if (inbound)
     {
         dst = this->my_addr;
         src = this->other_addr;
         if (this->my_spi == spi)
         {   /* alloc_spi has been called, do an SA update */
             update = TRUE;
         }
         this->my_spi = spi;
         this->my_cpi = cpi;
     }
     else
     {
         src = this->my_addr;
         dst = this->other_addr;
         this->other_spi = spi;
         this->other_cpi = cpi;
         if (tfcv3)
         {
             tfc = this->config->get_tfc(this->config);
         }
     }
     DBG2(DBG_CHD, "adding %s %N SA", inbound ? "inbound" : "outbound",
          protocol_id_names, this->protocol);
     /* send SA down to the kernel */
     DBG2(DBG_CHD, "  SPI 0x%.8x, src %H dst %H", ntohl(spi), src, dst);
     this->proposal->get_algorithm(this->proposal, ENCRYPTION_ALGORITHM,
                                   &enc_alg, &size);
     this->proposal->get_algorithm(this->proposal, INTEGRITY_ALGORITHM,
                                   &int_alg, &size);
     this->proposal->get_algorithm(this->proposal, EXTENDED_SEQUENCE_NUMBERS,
                                   &esn, NULL);
     if (!this->reqid_allocated && !this->static_reqid)
     {
         status = hydra->kernel_interface->alloc_reqid(hydra->kernel_interface,
                             my_ts, other_ts, this->mark_in, this->mark_out,
                             &this->reqid);
         if (status != SUCCESS)
         {
             return status;
         }
         this->reqid_allocated = TRUE;
     }
     lifetime = this->config->get_lifetime(this->config);
     now = time_monotonic(NULL);
     if (lifetime->time.rekey)
     {
         if (this->rekey_time)
         {
             this->rekey_time = min(this->rekey_time, now + lifetime->time.rekey);
         }
         else
         {
             this->rekey_time = now + lifetime->time.rekey;
         }
     }
     if (lifetime->time.life)
     {
         this->expire_time = now + lifetime->time.life;
     }
     if (!lifetime->time.jitter && !inbound)
     {   /* avoid triggering multiple rekey events */
         lifetime->time.rekey = 0;
     }
     /* BEET requires the bound address from the traffic selectors */
     if (inbound)
     {
         dst_ts = my_ts;
         src_ts = other_ts;
     }
     else
     {
         src_ts = my_ts;
         dst_ts = other_ts;
     }
     status = hydra->kernel_interface->add_sa(hydra->kernel_interface,
                 src, dst, spi, proto_ike2ip(this->protocol), this->reqid,
                 inbound ? this->mark_in : this->mark_out, tfc,
                 lifetime, enc_alg, encr, int_alg, integ, this->mode,
                 this->ipcomp, cpi, this->config->get_replay_window(this->config),
                 initiator, this->encap, esn, inbound, update, src_ts, dst_ts);
     free(lifetime);
     return status;
 }
METHOD (child_sa_t , add_policies , status_t , private_child_sa_t * this, linked_list_t * my_ts_list, linked_list_t * other_ts_list)
Definition at line 878 of file child_sa.c.
References kernel_interface_t::alloc_reqid, array_insert(), array_sort(), ARRAY_TAIL, CHILD_CREATED, CHILD_ROUTED, traffic_selector_t::clone, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, hydra, install_policies_internal(), hydra_t::kernel_interface, POLICY_DROP, POLICY_IPSEC, POLICY_PRIORITY_DEFAULT, POLICY_PRIORITY_FALLBACK, POLICY_PRIORITY_ROUTED, prepare_sa_cfg(), require_policy_update(), set_state(), status, SUCCESS, traffic_selector_cmp(), and TRUE.
 {
     enumerator_t *enumerator;
     traffic_selector_t *my_ts, *other_ts;
     status_t status = SUCCESS;
     if (!this->reqid_allocated && !this->static_reqid)
     {
         /* trap policy, get or confirm reqid */
         status = hydra->kernel_interface->alloc_reqid(
                             hydra->kernel_interface, my_ts_list, other_ts_list,
                             this->mark_in, this->mark_out, &this->reqid);
         if (status != SUCCESS)
         {
             return status;
         }
         this->reqid_allocated = TRUE;
     }
     /* apply traffic selectors */
     enumerator = my_ts_list->create_enumerator(my_ts_list);
     while (enumerator->enumerate(enumerator, &my_ts))
     {
         array_insert(this->my_ts, ARRAY_TAIL, my_ts->clone(my_ts));
     }
     enumerator->destroy(enumerator);
     array_sort(this->my_ts, (void*)traffic_selector_cmp, NULL);
     enumerator = other_ts_list->create_enumerator(other_ts_list);
     while (enumerator->enumerate(enumerator, &other_ts))
     {
         array_insert(this->other_ts, ARRAY_TAIL, other_ts->clone(other_ts));
     }
     enumerator->destroy(enumerator);
     array_sort(this->other_ts, (void*)traffic_selector_cmp, NULL);
     if (this->config->install_policy(this->config))
     {
         policy_priority_t priority;
         ipsec_sa_cfg_t my_sa, other_sa;
         prepare_sa_cfg(this, &my_sa, &other_sa);
         /* if we're not in state CHILD_INSTALLING (i.e. if there is no SAD
          * entry) we install a trap policy */
         this->trap = this->state == CHILD_CREATED;
         priority = this->trap ? POLICY_PRIORITY_ROUTED
                               : POLICY_PRIORITY_DEFAULT;
         /* enumerate pairs of traffic selectors */
         enumerator = create_policy_enumerator(this);
         while (enumerator->enumerate(enumerator, &my_ts, &other_ts))
         {
             /* install outbound drop policy to avoid packets leaving unencrypted
              * when updating policies */
             if (priority == POLICY_PRIORITY_DEFAULT && require_policy_update())
             {
                 status |= install_policies_internal(this, this->my_addr,
                                     this->other_addr, my_ts, other_ts,
                                     &my_sa, &other_sa, POLICY_DROP,
                                     POLICY_PRIORITY_FALLBACK);
             }
             /* install policies */
             status |= install_policies_internal(this, this->my_addr,
                                     this->other_addr, my_ts, other_ts,
                                     &my_sa, &other_sa, POLICY_IPSEC, priority);
             if (status != SUCCESS)
             {
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     if (status == SUCCESS && this->trap)
     {
         set_state(this, CHILD_ROUTED);
     }
     return status;
 }
METHOD (child_sa_t , update , status_t , private_child_sa_t * this, host_t * me, host_t * other, linked_list_t * vips, bool encap)
Definition at line 979 of file child_sa.c.
References CHILD_UPDATING, host_t::clone, traffic_selector_t::clone, del_policies_internal(), enumerator_t::destroy, host_t::destroy, DESTROY_IF, enumerator_t::enumerate, host_t::equals, hydra, install_policies_internal(), linked_list_t::invoke_function, host_t::ip_equals, IPCOMP_NONE, traffic_selector_t::is_host, hydra_t::kernel_interface, MODE_TRANSPORT, NOT_SUPPORTED, POLICY_DROP, POLICY_IPSEC, POLICY_PRIORITY_DEFAULT, POLICY_PRIORITY_FALLBACK, prepare_sa_cfg(), proto_ike2ip(), protocol, reinstall_vip(), require_policy_update(), traffic_selector_t::set_address, set_state(), SUCCESS, and kernel_interface_t::update_sa.
 {
     child_sa_state_t old;
     bool transport_proxy_mode;
     /* anything changed at all? */
     if (me->equals(me, this->my_addr) &&
         other->equals(other, this->other_addr) && this->encap == encap)
     {
         return SUCCESS;
     }
     old = this->state;
     set_state(this, CHILD_UPDATING);
     transport_proxy_mode = this->config->use_proxy_mode(this->config) &&
                            this->mode == MODE_TRANSPORT;
     if (!transport_proxy_mode)
     {
         /* update our (initiator) SA */
         if (this->my_spi)
         {
             if (hydra->kernel_interface->update_sa(hydra->kernel_interface,
                             this->my_spi, proto_ike2ip(this->protocol),
                             this->ipcomp != IPCOMP_NONE ? this->my_cpi : 0,
                             this->other_addr, this->my_addr, other, me,
                             this->encap, encap, this->mark_in) == NOT_SUPPORTED)
             {
                 set_state(this, old);
                 return NOT_SUPPORTED;
             }
         }
         /* update his (responder) SA */
         if (this->other_spi)
         {
             if (hydra->kernel_interface->update_sa(hydra->kernel_interface,
                             this->other_spi, proto_ike2ip(this->protocol),
                             this->ipcomp != IPCOMP_NONE ? this->other_cpi : 0,
                             this->my_addr, this->other_addr, me, other,
                             this->encap, encap, this->mark_out) == NOT_SUPPORTED)
             {
                 set_state(this, old);
                 return NOT_SUPPORTED;
             }
         }
     }
     if (this->config->install_policy(this->config) && require_policy_update())
     {
         if (!me->ip_equals(me, this->my_addr) ||
             !other->ip_equals(other, this->other_addr))
         {
             ipsec_sa_cfg_t my_sa, other_sa;
             enumerator_t *enumerator;
             traffic_selector_t *my_ts, *other_ts;
             prepare_sa_cfg(this, &my_sa, &other_sa);
             /* always use high priorities, as hosts getting updated are INSTALLED */
             enumerator = create_policy_enumerator(this);
             while (enumerator->enumerate(enumerator, &my_ts, &other_ts))
             {
                 traffic_selector_t *old_my_ts = NULL, *old_other_ts = NULL;
                 /* remove old policies first */
                 del_policies_internal(this, this->my_addr, this->other_addr,
                                       my_ts, other_ts, &my_sa, &other_sa,
                                       POLICY_IPSEC, POLICY_PRIORITY_DEFAULT);
                 /* check if we have to update a "dynamic" traffic selector */
                 if (!me->ip_equals(me, this->my_addr) &&
                     my_ts->is_host(my_ts, this->my_addr))
                 {
                     old_my_ts = my_ts->clone(my_ts);
                     my_ts->set_address(my_ts, me);
                 }
                 if (!other->ip_equals(other, this->other_addr) &&
                     other_ts->is_host(other_ts, this->other_addr))
                 {
                     old_other_ts = other_ts->clone(other_ts);
                     other_ts->set_address(other_ts, other);
                 }
                 /* we reinstall the virtual IP to handle interface roaming
                  * correctly */
                 vips->invoke_function(vips, (void*)reinstall_vip, me);
                 /* reinstall updated policies */
                 install_policies_internal(this, me, other, my_ts, other_ts,
                                           &my_sa, &other_sa, POLICY_IPSEC,
                                           POLICY_PRIORITY_DEFAULT);
                 /* update fallback policies after the new policy is in place */
                 del_policies_internal(this, this->my_addr, this->other_addr,
                                       old_my_ts ?: my_ts,
                                       old_other_ts ?: other_ts,
                                       &my_sa, &other_sa, POLICY_DROP,
                                       POLICY_PRIORITY_FALLBACK);
                 install_policies_internal(this, me, other, my_ts, other_ts,
                                           &my_sa, &other_sa, POLICY_DROP,
                                           POLICY_PRIORITY_FALLBACK);
                 DESTROY_IF(old_my_ts);
                 DESTROY_IF(old_other_ts);
             }
             enumerator->destroy(enumerator);
         }
     }
     if (!transport_proxy_mode)
     {
         /* apply hosts */
         if (!me->equals(me, this->my_addr))
         {
             this->my_addr->destroy(this->my_addr);
             this->my_addr = me->clone(me);
         }
         if (!other->equals(other, this->other_addr))
         {
             this->other_addr->destroy(this->other_addr);
             this->other_addr = other->clone(other);
         }
     }
     this->encap = encap;
     set_state(this, old);
     return SUCCESS;
 }
METHOD (child_sa_t , destroy , void , private_child_sa_t * this)
Definition at line 1110 of file child_sa.c.
References array_destroy_offset(), CHILD_DESTROYING, DBG1, DBG_CHD, del_policies_internal(), kernel_interface_t::del_sa, enumerator_t::destroy, destroy(), DESTROY_IF, enumerator_t::enumerate, free(), hydra, hydra_t::kernel_interface, POLICY_DROP, POLICY_IPSEC, POLICY_PRIORITY_DEFAULT, POLICY_PRIORITY_FALLBACK, POLICY_PRIORITY_ROUTED, prepare_sa_cfg(), proposal, proto_ike2ip(), protocol, kernel_interface_t::release_reqid, require_policy_update(), set_state(), and SUCCESS.
 {
     enumerator_t *enumerator;
     traffic_selector_t *my_ts, *other_ts;
     policy_priority_t priority;
     priority = this->trap ? POLICY_PRIORITY_ROUTED : POLICY_PRIORITY_DEFAULT;
     set_state(this, CHILD_DESTROYING);
     if (this->config->install_policy(this->config))
     {
         ipsec_sa_cfg_t my_sa, other_sa;
         prepare_sa_cfg(this, &my_sa, &other_sa);
         /* delete all policies in the kernel */
         enumerator = create_policy_enumerator(this);
         while (enumerator->enumerate(enumerator, &my_ts, &other_ts))
         {
             del_policies_internal(this, this->my_addr, this->other_addr,
                     my_ts, other_ts, &my_sa, &other_sa, POLICY_IPSEC, priority);
             if (priority == POLICY_PRIORITY_DEFAULT && require_policy_update())
             {
                 del_policies_internal(this, this->my_addr, this->other_addr,
                                 my_ts, other_ts, &my_sa, &other_sa, POLICY_DROP,
                                 POLICY_PRIORITY_FALLBACK);
             }
         }
         enumerator->destroy(enumerator);
     }
     /* delete SAs in the kernel, if they are set up */
     if (this->my_spi)
     {
         hydra->kernel_interface->del_sa(hydra->kernel_interface,
                     this->other_addr, this->my_addr, this->my_spi,
                     proto_ike2ip(this->protocol), this->my_cpi,
                     this->mark_in);
     }
     if (this->other_spi)
     {
         hydra->kernel_interface->del_sa(hydra->kernel_interface,
                     this->my_addr, this->other_addr, this->other_spi,
                     proto_ike2ip(this->protocol), this->other_cpi,
                     this->mark_out);
     }
     if (this->reqid_allocated)
     {
         if (hydra->kernel_interface->release_reqid(hydra->kernel_interface,
                         this->reqid, this->mark_in, this->mark_out) != SUCCESS)
         {
             DBG1(DBG_CHD, "releasing reqid %u failed", this->reqid);
         }
     }
     array_destroy_offset(this->my_ts, offsetof(traffic_selector_t, destroy));
     array_destroy_offset(this->other_ts, offsetof(traffic_selector_t, destroy));
     this->my_addr->destroy(this->my_addr);
     this->other_addr->destroy(this->other_addr);
     DESTROY_IF(this->proposal);
     this->config->destroy(this->config);
     free(this);
 }
static void prepare_sa_cfg (private_child_sa_t * this, ipsec_sa_cfg_t * my_sa, ipsec_sa_cfg_t * other_sa) static
Prepare SA config to install/delete policies
Definition at line 786 of file child_sa.c.
References ipsec_sa_cfg_t::ah, ipsec_sa_cfg_t::cpi, enumerator_t::destroy, enumerator_t::enumerate, ipsec_sa_cfg_t::esp, ipsec_sa_cfg_t::ipcomp, ipsec_sa_cfg_t::mode, ipsec_sa_cfg_t::policy_count, PROTO_ESP, protocol, ipsec_sa_cfg_t::spi, TRUE, and ipsec_sa_cfg_t::use.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     *my_sa = (ipsec_sa_cfg_t){
         .mode = this->mode,
         .reqid = this->reqid,
         .ipcomp = {
             .transform = this->ipcomp,
         },
     };
     *other_sa = *my_sa;
     my_sa->ipcomp.cpi = this->my_cpi;
     other_sa->ipcomp.cpi = this->other_cpi;
     if (this->protocol == PROTO_ESP)
     {
         my_sa->esp.use = TRUE;
         my_sa->esp.spi = this->my_spi;
         other_sa->esp.use = TRUE;
         other_sa->esp.spi = this->other_spi;
     }
     else
     {
         my_sa->ah.use = TRUE;
         my_sa->ah.spi = this->my_spi;
         other_sa->ah.use = TRUE;
         other_sa->ah.spi = this->other_spi;
     }
     enumerator = create_policy_enumerator(this);
     while (enumerator->enumerate(enumerator, NULL, NULL))
     {
         my_sa->policy_count++;
         other_sa->policy_count++;
     }
     enumerator->destroy(enumerator);
 }
static u_int8_t proto_ike2ip (protocol_id_t protocol) inline static
convert an IKEv2 specific protocol identifier to the IP protocol identifier.
Definition at line 223 of file child_sa.c.
References PROTO_AH, PROTO_ESP, and protocol.
Referenced by METHOD(), and update_usebytes().
 {
     switch (protocol)
     {
         case PROTO_ESP:
             return IPPROTO_ESP;
         case PROTO_AH:
             return IPPROTO_AH;
         default:
             return protocol;
     }
 }
static void reinstall_vip (host_t * vip, host_t * me) static
Callback to reinstall a virtual IP
Definition at line 966 of file child_sa.c.
References kernel_interface_t::add_ip, kernel_interface_t::del_ip, free(), kernel_interface_t::get_interface, hydra, hydra_t::kernel_interface, and TRUE.
Referenced by METHOD().
 {
     char *iface;
     if (hydra->kernel_interface->get_interface(hydra->kernel_interface,
                                                me, &iface))
     {
         hydra->kernel_interface->del_ip(hydra->kernel_interface, vip, -1, TRUE);
         hydra->kernel_interface->add_ip(hydra->kernel_interface, vip, -1, iface);
         free(iface);
     }
 }
static bool require_policy_update () static
Check kernel interface if policy updates are required
Definition at line 775 of file child_sa.c.
References kernel_interface_t::get_features, hydra, hydra_t::kernel_interface, and KERNEL_NO_POLICY_UPDATES.
Referenced by METHOD().
 {
     kernel_feature_t f;
     f = hydra->kernel_interface->get_features(hydra->kernel_interface);
     return !(f & KERNEL_NO_POLICY_UPDATES);
 }
static status_t update_usebytes (private_child_sa_t * this, bool inbound) static
update the cached usebytes returns SUCCESS if the usebytes have changed, FAILED if not or no SPIs are available, and NOT_SUPPORTED if the kernel interface does not support querying the usebytes.
Definition at line 462 of file child_sa.c.
References bytes, FAILED, hydra, hydra_t::kernel_interface, proto_ike2ip(), protocol, kernel_interface_t::query_sa, status, and SUCCESS.
Referenced by METHOD().
 {
     status_t status = FAILED;
     u_int64_t bytes, packets;
     time_t time;
     if (inbound)
     {
         if (this->my_spi)
         {
             status = hydra->kernel_interface->query_sa(hydra->kernel_interface,
                             this->other_addr, this->my_addr, this->my_spi,
                             proto_ike2ip(this->protocol), this->mark_in,
                             &bytes, &packets, &time);
             if (status == SUCCESS)
             {
                 if (bytes > this->my_usebytes)
                 {
                     this->my_usebytes = bytes;
                     this->my_usepackets = packets;
                     if (time)
                     {
                         this->my_usetime = time;
                     }
                     return SUCCESS;
                 }
                 return FAILED;
             }
         }
     }
     else
     {
         if (this->other_spi)
         {
             status = hydra->kernel_interface->query_sa(hydra->kernel_interface,
                             this->my_addr, this->other_addr, this->other_spi,
                             proto_ike2ip(this->protocol), this->mark_out,
                             &bytes, &packets, &time);
             if (status == SUCCESS)
             {
                 if (bytes > this->other_usebytes)
                 {
                     this->other_usebytes = bytes;
                     this->other_usepackets = packets;
                     if (time)
                     {
                         this->other_usetime = time;
                     }
                     return SUCCESS;
                 }
                 return FAILED;
             }
         }
     }
     return status;
 }
static bool update_usetime (private_child_sa_t * this, bool inbound) static
updates the cached usetime
Definition at line 522 of file child_sa.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, hydra, in, hydra_t::kernel_interface, max, MODE_TRANSPORT, out, POLICY_FWD, POLICY_IN, POLICY_OUT, kernel_interface_t::query_policy, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     traffic_selector_t *my_ts, *other_ts;
     time_t last_use = 0;
     enumerator = create_policy_enumerator(this);
     while (enumerator->enumerate(enumerator, &my_ts, &other_ts))
     {
         time_t in, out, fwd;
         if (inbound)
         {
             if (hydra->kernel_interface->query_policy(hydra->kernel_interface,
                         other_ts, my_ts, POLICY_IN, this->mark_in, &in) == SUCCESS)
             {
                 last_use = max(last_use, in);
             }
             if (this->mode != MODE_TRANSPORT)
             {
                 if (hydra->kernel_interface->query_policy(hydra->kernel_interface,
                         other_ts, my_ts, POLICY_FWD, this->mark_in, &fwd) == SUCCESS)
                 {
                     last_use = max(last_use, fwd);
                 }
             }
         }
         else
         {
             if (hydra->kernel_interface->query_policy(hydra->kernel_interface,
                         my_ts, other_ts, POLICY_OUT, this->mark_out, &out) == SUCCESS)
             {
                 last_use = max(last_use, out);
             }
         }
     }
     enumerator->destroy(enumerator);
     if (last_use == 0)
     {
         return FALSE;
     }
     if (inbound)
     {
         this->my_usetime = last_use;
     }
     else
     {
         this->other_usetime = last_use;
     }
     return TRUE;
 }