strongSwan: swid_error
swid_error
swid
Typedefs
typedef enum swid_error_code_t swid_error_code_t
Enumerations
enum swid_error_code_t { TCG_SWID_ERROR = 0x20, TCG_SWID_SUBSCRIPTION_DENIED = 0x21, TCG_SWID_RESPONSE_TOO_LARGE = 0x22 }
Functions
pa_tnc_attr_t * swid_error_create (swid_error_code_t code, u_int32_t request, u_int32_t max_attr_size, char *description)
Variables
enum_name_t * swid_error_code_names
Detailed Description
Typedef Documentation
typedef enum swid_error_code_t swid_error_code_t
Definition at line 24 of file swid_error.h.
Enumeration Type Documentation
enum swid_error_code_t
SWID Error Codes see section 3.14.2 of PTS Protocol: Binding to TNC IF-M Specification
Enumerator
TCG_SWID_ERROR
TCG_SWID_SUBSCRIPTION_DENIED
TCG_SWID_RESPONSE_TOO_LARGE
Definition at line 35 of file swid_error.h.
{
     TCG_SWID_ERROR =                0x20,
     TCG_SWID_SUBSCRIPTION_DENIED =  0x21,
     TCG_SWID_RESPONSE_TOO_LARGE =   0x22
 };
Function Documentation
pa_tnc_attr_t* swid_error_create (swid_error_code_t code, u_int32_t request_id, u_int32_t max_attr_size, char * description)
Creates a SWID Error Attribute see section 4.12 of TNC SWID Message and Attributes for IF-M
Parameters
code SWID error code
request SWID request ID
max_attr_size Maximum IF-M attribute size (if applicable)
description Optional description string or NULL
Described in header.
Definition at line 30 of file swid_error.c.
References bio_writer_create(), chunk_from_str, bio_writer_t::destroy, error_code, bio_writer_t::get_buf, ietf_attr_pa_tnc_error_create(), PEN_TCG, pen_type_create(), TCG_SWID_RESPONSE_TOO_LARGE, bio_writer_t::write_data, and bio_writer_t::write_uint32.
Referenced by add_swid_inventory(), and receive_message().
 {
     bio_writer_t *writer;
     chunk_t msg_info;
     pa_tnc_attr_t *attr;
     pen_type_t error_code;
     error_code = pen_type_create( PEN_TCG, code);
     writer = bio_writer_create(4);
     writer->write_uint32(writer, request_id);
     if (code == TCG_SWID_RESPONSE_TOO_LARGE)
     {
         writer->write_uint32(writer, max_attr_size);
     }
     if (description)
     {
         writer->write_data(writer, chunk_from_str(description));
     }
     msg_info = writer->get_buf(writer);
     attr = ietf_attr_pa_tnc_error_create(error_code, msg_info);
     writer->destroy(writer);
     return attr;
 }
Variable Documentation
enum_name_t* swid_error_code_names
enum name for swid_error_code_t.
Referenced by receive_msg().