strongSwan: public_key
public_key
keys
Classes
struct public_key_t
Typedefs
typedef struct public_key_t public_key_t
typedef enum key_type_t key_type_t
typedef enum signature_scheme_t signature_scheme_t
typedef enum encryption_scheme_t encryption_scheme_t
Enumerations
enum key_type_t {
KEY_ANY = 0, KEY_RSA = 1, KEY_ECDSA = 2, KEY_DSA = 3,
KEY_BLISS = 4
}
enum signature_scheme_t {
SIGN_UNKNOWN, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_SHA1,
SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512,
SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER,
SIGN_ECDSA_WITH_NULL, SIGN_ECDSA_256, SIGN_ECDSA_384, SIGN_ECDSA_521,
SIGN_BLISS_WITH_SHA2_256, SIGN_BLISS_WITH_SHA2_384, SIGN_BLISS_WITH_SHA2_512, SIGN_BLISS_WITH_SHA3_256,
SIGN_BLISS_WITH_SHA3_384, SIGN_BLISS_WITH_SHA3_512
}
enum encryption_scheme_t {
ENCRYPT_UNKNOWN, ENCRYPT_RSA_PKCS1, ENCRYPT_RSA_OAEP_SHA1, ENCRYPT_RSA_OAEP_SHA224,
ENCRYPT_RSA_OAEP_SHA256, ENCRYPT_RSA_OAEP_SHA384, ENCRYPT_RSA_OAEP_SHA512
}
Functions
bool public_key_equals (public_key_t *public, public_key_t *other)
bool public_key_has_fingerprint (public_key_t *public, chunk_t fingerprint)
signature_scheme_t signature_scheme_from_oid (int oid)
int signature_scheme_to_oid (signature_scheme_t scheme)
enumerator_t * signature_schemes_for_key (key_type_t type, int size)
key_type_t key_type_from_signature_scheme (signature_scheme_t scheme)
Variables
enum_name_t * key_type_names
enum_name_t * signature_scheme_names
enum_name_t * encryption_scheme_names
Detailed Description
Typedef Documentation
typedef enum encryption_scheme_t encryption_scheme_t
Definition at line 29 of file public_key.h.
typedef enum key_type_t key_type_t
Definition at line 27 of file public_key.h.
typedef struct public_key_t public_key_t
Definition at line 26 of file public_key.h.
typedef enum signature_scheme_t signature_scheme_t
Definition at line 28 of file public_key.h.
Enumeration Type Documentation
enum encryption_scheme_t
Encryption scheme for public key data encryption.
Enumerator
ENCRYPT_UNKNOWN
Unknown encryption scheme
ENCRYPT_RSA_PKCS1
RSAES-PKCS1-v1_5 as in PKCS#1
ENCRYPT_RSA_OAEP_SHA1
RSAES-OAEP as in PKCS#1, using SHA1 as hash, no label
ENCRYPT_RSA_OAEP_SHA224
RSAES-OAEP as in PKCS#1, using SHA-224 as hash, no label
ENCRYPT_RSA_OAEP_SHA256
RSAES-OAEP as in PKCS#1, using SHA-256 as hash, no label
ENCRYPT_RSA_OAEP_SHA384
RSAES-OAEP as in PKCS#1, using SHA-384 as hash, no label
ENCRYPT_RSA_OAEP_SHA512
RSAES-OAEP as in PKCS#1, using SHA-512 as hash, no label
Definition at line 119 of file public_key.h.
{
     ENCRYPT_UNKNOWN,
     ENCRYPT_RSA_PKCS1,
     ENCRYPT_RSA_OAEP_SHA1,
     ENCRYPT_RSA_OAEP_SHA224,
     ENCRYPT_RSA_OAEP_SHA256,
     ENCRYPT_RSA_OAEP_SHA384,
     ENCRYPT_RSA_OAEP_SHA512,
 };
enum key_type_t
Type of a key pair, the used crypto system
Enumerator
KEY_ANY
key type wildcard
KEY_RSA
RSA crypto system as in PKCS#1
KEY_ECDSA
ECDSA as in ANSI X9.62
KEY_DSA
DSA
KEY_BLISS
BLISS
Definition at line 38 of file public_key.h.
                 {
     KEY_ANY   = 0,
     KEY_RSA   = 1,
     KEY_ECDSA = 2,
     KEY_DSA   = 3,
     KEY_BLISS = 4,
 };
enum signature_scheme_t
Signature scheme for signature creation
EMSA-PKCS1 signatures are defined in PKCS#1 standard. A prepended ASN.1 encoded digestInfo field contains the OID of the used hash algorithm.
Enumerator
SIGN_UNKNOWN
Unknown signature scheme
SIGN_RSA_EMSA_PKCS1_NULL
EMSA-PKCS1_v1.5 signature over digest without digestInfo
SIGN_RSA_EMSA_PKCS1_MD5
EMSA-PKCS1_v1.5 signature as in PKCS#1 using RSA and MD5
SIGN_RSA_EMSA_PKCS1_SHA1
EMSA-PKCS1_v1.5 signature as in PKCS#1 using RSA and SHA-1
SIGN_RSA_EMSA_PKCS1_SHA224
EMSA-PKCS1_v1.5 signature as in PKCS#1 using RSA and SHA-224
SIGN_RSA_EMSA_PKCS1_SHA256
EMSA-PKCS1_v1.5 signature as in PKCS#1 using RSA and SHA-256
SIGN_RSA_EMSA_PKCS1_SHA384
EMSA-PKCS1_v1.5 signature as in PKCS#1 using RSA and SHA-384
SIGN_RSA_EMSA_PKCS1_SHA512
EMSA-PKCS1_v1.5 signature as in PKCS#1 using RSA and SHA-512
SIGN_ECDSA_WITH_SHA1_DER
ECDSA with SHA-1 using DER encoding as in RFC 3279
SIGN_ECDSA_WITH_SHA256_DER
ECDSA with SHA-256 using DER encoding as in RFC 3279
SIGN_ECDSA_WITH_SHA384_DER
ECDSA with SHA-384 using DER encoding as in RFC 3279
SIGN_ECDSA_WITH_SHA512_DER
ECDSA with SHA-1 using DER encoding as in RFC 3279
SIGN_ECDSA_WITH_NULL
ECDSA over precomputed digest, signature as in RFC 4754
SIGN_ECDSA_256
ECDSA on the P-256 curve with SHA-256 as in RFC 4754
SIGN_ECDSA_384
ECDSA on the P-384 curve with SHA-384 as in RFC 4754
SIGN_ECDSA_521
ECDSA on the P-521 curve with SHA-512 as in RFC 4754
SIGN_BLISS_WITH_SHA2_256
BLISS with SHA-2_256
SIGN_BLISS_WITH_SHA2_384
BLISS with SHA-2_384
SIGN_BLISS_WITH_SHA2_512
BLISS with SHA-2_512
SIGN_BLISS_WITH_SHA3_256
BLISS with SHA-3_256
SIGN_BLISS_WITH_SHA3_384
BLISS with SHA-3_384
SIGN_BLISS_WITH_SHA3_512
BLISS with SHA-3_512
Definition at line 64 of file public_key.h.
{
     SIGN_UNKNOWN,
     SIGN_RSA_EMSA_PKCS1_NULL,
     SIGN_RSA_EMSA_PKCS1_MD5,
     SIGN_RSA_EMSA_PKCS1_SHA1,
     SIGN_RSA_EMSA_PKCS1_SHA224,
     SIGN_RSA_EMSA_PKCS1_SHA256,
     SIGN_RSA_EMSA_PKCS1_SHA384,
     SIGN_RSA_EMSA_PKCS1_SHA512,
     SIGN_ECDSA_WITH_SHA1_DER,
     SIGN_ECDSA_WITH_SHA256_DER,
     SIGN_ECDSA_WITH_SHA384_DER,
     SIGN_ECDSA_WITH_SHA512_DER,
     SIGN_ECDSA_WITH_NULL,
     SIGN_ECDSA_256,
     SIGN_ECDSA_384,
     SIGN_ECDSA_521,
     SIGN_BLISS_WITH_SHA2_256,
     SIGN_BLISS_WITH_SHA2_384,
     SIGN_BLISS_WITH_SHA2_512,
     SIGN_BLISS_WITH_SHA3_256,
     SIGN_BLISS_WITH_SHA3_384,
     SIGN_BLISS_WITH_SHA3_512,
 };
Function Documentation
key_type_t key_type_from_signature_scheme (signature_scheme_t scheme)
Determine the type of key associated with a given signature scheme.
Parameters
scheme signature scheme
Returns
key type (could be KEY_ANY)
Definition at line 279 of file public_key.c.
References KEY_ANY, KEY_BLISS, KEY_ECDSA, KEY_RSA, SIGN_BLISS_WITH_SHA2_256, SIGN_BLISS_WITH_SHA2_384, SIGN_BLISS_WITH_SHA2_512, SIGN_BLISS_WITH_SHA3_256, SIGN_BLISS_WITH_SHA3_384, SIGN_BLISS_WITH_SHA3_512, SIGN_ECDSA_256, SIGN_ECDSA_384, SIGN_ECDSA_521, SIGN_ECDSA_WITH_NULL, SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, and SIGN_UNKNOWN.
Referenced by parse_signature_auth_data(), and select_signature_schemes().
 {
     switch (scheme)
     {
         case SIGN_UNKNOWN:
             break;
         case SIGN_RSA_EMSA_PKCS1_NULL:
         case SIGN_RSA_EMSA_PKCS1_MD5:
         case SIGN_RSA_EMSA_PKCS1_SHA1:
         case SIGN_RSA_EMSA_PKCS1_SHA224:
         case SIGN_RSA_EMSA_PKCS1_SHA256:
         case SIGN_RSA_EMSA_PKCS1_SHA384:
         case SIGN_RSA_EMSA_PKCS1_SHA512:
             return KEY_RSA;
         case SIGN_ECDSA_WITH_SHA1_DER:
         case SIGN_ECDSA_WITH_SHA256_DER:
         case SIGN_ECDSA_WITH_SHA384_DER:
         case SIGN_ECDSA_WITH_SHA512_DER:
         case SIGN_ECDSA_WITH_NULL:
         case SIGN_ECDSA_256:
         case SIGN_ECDSA_384:
         case SIGN_ECDSA_521:
             return KEY_ECDSA;
         case SIGN_BLISS_WITH_SHA2_256:
         case SIGN_BLISS_WITH_SHA2_384:
         case SIGN_BLISS_WITH_SHA2_512:
         case SIGN_BLISS_WITH_SHA3_256:
         case SIGN_BLISS_WITH_SHA3_384:
         case SIGN_BLISS_WITH_SHA3_512:
             return KEY_BLISS;
     }
     return KEY_ANY;
 }
bool public_key_equals (public_key_t * this, public_key_t * other)
Generic public key equals() implementation, usable by implementors.
Parameters
public public key to check
other key to compare
Returns
TRUE if this is equal to other
See header.
Definition at line 68 of file public_key.c.
References a, b, chunk_equals(), CRED_ENCODING_MAX, FALSE, public_key_t::get_fingerprint, TRUE, and type.
Referenced by bliss_public_key_load(), create(), create_empty(), gcrypt_rsa_public_key_load(), gmp_rsa_public_key_load(), METHOD(), and tkm_public_key_load().
 {
     cred_encoding_type_t type;
     chunk_t a, b;
     if (this == other)
     {
         return TRUE;
     }
     for (type = 0; type < CRED_ENCODING_MAX; type++)
     {
         if (this->get_fingerprint(this, type, &a) &&
             other->get_fingerprint(other, type, &b))
         {
             return chunk_equals(a, b);
         }
     }
     return FALSE;
 }
bool public_key_has_fingerprint (public_key_t * public, chunk_t fingerprint)
Generic public key has_fingerprint() implementation, usable by implementors.
Parameters
public public key to check
fingerprint fingerprint to check
Returns
TRUE if key has given fingerprint
See header.
Definition at line 92 of file public_key.c.
References chunk_equals(), FALSE, KEYID_MAX, public, TRUE, and type.
Referenced by bliss_public_key_load(), create(), create_empty(), gcrypt_rsa_public_key_load(), gmp_rsa_public_key_load(), and tkm_public_key_load().
 {
     cred_encoding_type_t type;
     chunk_t current;
     for (type = 0; type < KEYID_MAX; type++)
     {
         if (public->get_fingerprint(public, type, &current) &&
             chunk_equals(current, fingerprint))
         {
             return TRUE;
         }
     }
     return FALSE;
 }
signature_scheme_t signature_scheme_from_oid (int oid)
Conversion of ASN.1 signature or hash OID to signature scheme.
Parameters
oid ASN.1 OID
Returns
signature scheme, SIGN_UNKNOWN if OID is unsupported
Definition at line 111 of file public_key.c.
References OID_BLISS_PUBLICKEY, OID_BLISS_WITH_SHA2_256, OID_BLISS_WITH_SHA2_384, OID_BLISS_WITH_SHA2_512, OID_BLISS_WITH_SHA3_256, OID_BLISS_WITH_SHA3_384, OID_BLISS_WITH_SHA3_512, OID_EC_PUBLICKEY, OID_ECDSA_WITH_SHA1, OID_ECDSA_WITH_SHA256, OID_ECDSA_WITH_SHA384, OID_ECDSA_WITH_SHA512, OID_MD5, OID_MD5_WITH_RSA, OID_SHA1, OID_SHA1_WITH_RSA, OID_SHA224, OID_SHA224_WITH_RSA, OID_SHA256, OID_SHA256_WITH_RSA, OID_SHA384, OID_SHA384_WITH_RSA, OID_SHA512, OID_SHA512_WITH_RSA, SIGN_BLISS_WITH_SHA2_256, SIGN_BLISS_WITH_SHA2_384, SIGN_BLISS_WITH_SHA2_512, SIGN_BLISS_WITH_SHA3_256, SIGN_BLISS_WITH_SHA3_384, SIGN_BLISS_WITH_SHA3_512, SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, and SIGN_UNKNOWN.
Referenced by generate(), METHOD(), parse_certificate(), parse_crl(), and parse_signature_auth_data().
 {
     switch (oid)
     {
         case OID_MD5_WITH_RSA:
         case OID_MD5:
             return SIGN_RSA_EMSA_PKCS1_MD5;
         case OID_SHA1_WITH_RSA:
         case OID_SHA1:
             return SIGN_RSA_EMSA_PKCS1_SHA1;
         case OID_SHA224_WITH_RSA:
         case OID_SHA224:
             return SIGN_RSA_EMSA_PKCS1_SHA224;
         case OID_SHA256_WITH_RSA:
         case OID_SHA256:
             return SIGN_RSA_EMSA_PKCS1_SHA256;
         case OID_SHA384_WITH_RSA:
         case OID_SHA384:
             return SIGN_RSA_EMSA_PKCS1_SHA384;
         case OID_SHA512_WITH_RSA:
         case OID_SHA512:
             return SIGN_RSA_EMSA_PKCS1_SHA512;
         case OID_ECDSA_WITH_SHA1:
         case OID_EC_PUBLICKEY:
             return SIGN_ECDSA_WITH_SHA1_DER;
         case OID_ECDSA_WITH_SHA256:
             return SIGN_ECDSA_WITH_SHA256_DER;
         case OID_ECDSA_WITH_SHA384:
             return SIGN_ECDSA_WITH_SHA384_DER;
         case OID_ECDSA_WITH_SHA512:
             return SIGN_ECDSA_WITH_SHA512_DER;
         case OID_BLISS_PUBLICKEY:
         case OID_BLISS_WITH_SHA2_512:
             return SIGN_BLISS_WITH_SHA2_512;
         case OID_BLISS_WITH_SHA2_384:
             return SIGN_BLISS_WITH_SHA2_384;
         case OID_BLISS_WITH_SHA2_256:
             return SIGN_BLISS_WITH_SHA2_256;
         case OID_BLISS_WITH_SHA3_512:
             return SIGN_BLISS_WITH_SHA3_512;
         case OID_BLISS_WITH_SHA3_384:
             return SIGN_BLISS_WITH_SHA3_384;
         case OID_BLISS_WITH_SHA3_256:
             return SIGN_BLISS_WITH_SHA3_256;
     }
     return SIGN_UNKNOWN;
 }
int signature_scheme_to_oid (signature_scheme_t scheme)
Conversion of signature scheme to ASN.1 signature OID.
Parameters
scheme signature scheme
Returns
ASN.1 OID, OID_UNKNOWN if not supported
Definition at line 162 of file public_key.c.
References OID_BLISS_WITH_SHA2_256, OID_BLISS_WITH_SHA2_384, OID_BLISS_WITH_SHA2_512, OID_BLISS_WITH_SHA3_256, OID_BLISS_WITH_SHA3_384, OID_BLISS_WITH_SHA3_512, OID_ECDSA_WITH_SHA1, OID_ECDSA_WITH_SHA256, OID_ECDSA_WITH_SHA384, OID_ECDSA_WITH_SHA512, OID_MD5_WITH_RSA, OID_SHA1_WITH_RSA, OID_SHA224_WITH_RSA, OID_SHA256_WITH_RSA, OID_SHA384_WITH_RSA, OID_SHA512_WITH_RSA, OID_UNKNOWN, SIGN_BLISS_WITH_SHA2_256, SIGN_BLISS_WITH_SHA2_384, SIGN_BLISS_WITH_SHA2_512, SIGN_BLISS_WITH_SHA3_256, SIGN_BLISS_WITH_SHA3_384, SIGN_BLISS_WITH_SHA3_512, SIGN_ECDSA_256, SIGN_ECDSA_384, SIGN_ECDSA_521, SIGN_ECDSA_WITH_NULL, SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, and SIGN_UNKNOWN.
Referenced by build_signature_auth_data().
 {
     switch (scheme)
     {
         case SIGN_UNKNOWN:
         case SIGN_RSA_EMSA_PKCS1_NULL:
         case SIGN_ECDSA_WITH_NULL:
         case SIGN_ECDSA_256:
         case SIGN_ECDSA_384:
         case SIGN_ECDSA_521:
             break;
         case SIGN_RSA_EMSA_PKCS1_MD5:
             return OID_MD5_WITH_RSA;
         case SIGN_RSA_EMSA_PKCS1_SHA1:
             return OID_SHA1_WITH_RSA;
         case SIGN_RSA_EMSA_PKCS1_SHA224:
             return OID_SHA224_WITH_RSA;
         case SIGN_RSA_EMSA_PKCS1_SHA256:
             return OID_SHA256_WITH_RSA;
         case SIGN_RSA_EMSA_PKCS1_SHA384:
             return OID_SHA384_WITH_RSA;
         case SIGN_RSA_EMSA_PKCS1_SHA512:
             return OID_SHA512_WITH_RSA;
         case SIGN_ECDSA_WITH_SHA1_DER:
             return OID_ECDSA_WITH_SHA1;
         case SIGN_ECDSA_WITH_SHA256_DER:
             return OID_ECDSA_WITH_SHA256;
         case SIGN_ECDSA_WITH_SHA384_DER:
             return OID_ECDSA_WITH_SHA384;
         case SIGN_ECDSA_WITH_SHA512_DER:
             return OID_ECDSA_WITH_SHA512;
         case SIGN_BLISS_WITH_SHA2_256:
             return OID_BLISS_WITH_SHA2_256;
         case SIGN_BLISS_WITH_SHA2_384:
             return OID_BLISS_WITH_SHA2_384;
         case SIGN_BLISS_WITH_SHA2_512:
             return OID_BLISS_WITH_SHA2_512;
         case SIGN_BLISS_WITH_SHA3_256:
             return OID_BLISS_WITH_SHA3_256;
         case SIGN_BLISS_WITH_SHA3_384:
             return OID_BLISS_WITH_SHA3_384;
         case SIGN_BLISS_WITH_SHA3_512:
             return OID_BLISS_WITH_SHA3_512;
     }
     return OID_UNKNOWN;
 }
enumerator_t* signature_schemes_for_key (key_type_t type, int size)
Enumerate signature schemes that are appropriate for a key of the given type and size|strength.
Parameters
type type of the key
size size or strength of the key
Returns
enumerator over signature_scheme_t (increasing strength)
Definition at line 259 of file public_key.c.
References destroy(), free(), INIT, size, and type.
Referenced by get_default_digest(), select_signature_schemes(), and START_TEST().
 {
     private_enumerator_t *this;
     INIT(this,
         .public = {
             .enumerate = (void*)_signature_schemes_enumerate,
             .destroy = (void*)free,
         },
         .index = -1,
         .type = type,
         .size = size,
     );
     return &this->public;
 }
Variable Documentation
enum_name_t* encryption_scheme_names
Enum names for encryption_scheme_t
Referenced by METHOD(), and plugin_feature_get_string().
enum_name_t* key_type_names
Enum names for key_type_t
Referenced by build_auth(), build_optionalSignature(), CALLBACK(), create_key(), filter_key_suites(), get_key_strength(), get_pubkey_method(), list_public_key(), load_key(), load_pkcs12(), load_private(), main(), METHOD(), plugin_feature_get_string(), print_pubkey(), rebuild_auth(), show(), sign_classic(), and sign_signature_auth().
enum_name_t* signature_scheme_names
Enum names for signature_scheme_t
Referenced by build_curve_signature(), METHOD(), plugin_feature_get_string(), sign_signature_auth(), test_bad_sigs(), test_good_sig(), and verify_curve_signature().