strongSwan: tests.c File Reference
charon-tkm/tests/tests.c File Reference
#include <tests/test_runner.h>
#include <library.h>
#include <hydra.h>
#include <daemon.h>
#include "tkm.h"
#include "tkm_nonceg.h"
#include "tkm_diffie_hellman.h"
#include "tkm_kernel_ipsec.h"
#include "tests.h"
Macros
#define TEST_SUITE(x) test_suite_t* x();
#define TEST_SUITE_DEPEND(x,...) TEST_SUITE(x)
#define TEST_SUITE(x) { .suite = x, },
#define TEST_SUITE_DEPEND(x, type,...) { .suite = x, .feature = PLUGIN_DEPENDS(type, __VA_ARGS__) },
Functions
static bool test_runner_init (bool init)
int main (int argc, char *argv[])
Variables
static test_configuration_t tests []
static bool tkm_initialized = false
Macro Definition Documentation
#define TEST_SUITE (x) test_suite_t* x();
Definition at line 30 of file charon-tkm/tests/tests.c.
#define TEST_SUITE (x) { .suite = x, },
Definition at line 30 of file charon-tkm/tests/tests.c.
#define TEST_SUITE_DEPEND (x, ...) TEST_SUITE(x)
Definition at line 31 of file charon-tkm/tests/tests.c.
#define TEST_SUITE_DEPEND (x, type, ...) { .suite = x, .feature = PLUGIN_DEPENDS(type, __VA_ARGS__) },
Definition at line 31 of file charon-tkm/tests/tests.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 102 of file charon-tkm/tests/tests.c.
References result, setenv(), test_runner_init(), test_runner_run(), and tkm_deinit().
 {
     bool result;
     /* disable leak detective because of how tkm_init/deinit is called, which
      * does not work otherwise due to limitations of the external libraries */
     setenv("LEAK_DETECTIVE_DISABLE", "1", 1);
     result = test_runner_run("tkm", tests, test_runner_init);
     tkm_deinit();
     return result;
 }
static bool test_runner_init (bool init) static
Definition at line 47 of file charon-tkm/tests/tests.c.
References plugin_loader_t::add_static_features, charon, countof, destroy_dh_mapping(), FALSE, features, daemon_t::initialize, kernel_ipsec_register(), lib, libcharon_deinit(), libcharon_init(), libhydra_deinit(), libhydra_init(), daemon_t::load_loggers, MODP_3072_BIT, MODP_4096_BIT, library_t::ns, PLUGIN_CALLBACK, plugin_loader_add_plugindirs(), PLUGIN_PROVIDE, PLUGIN_REGISTER, PLUGINS, library_t::plugins, register_dh_mapping(), result, settings_t::set_int, library_t::settings, tkm_init(), tkm_initialized, tkm_kernel_ipsec_create(), tkm_nonceg_create(), and TRUE.
Referenced by main().
 {
     bool result = TRUE;
     if (init)
     {
         libhydra_init();
         libcharon_init();
         lib->settings->set_int(lib->settings,
                                "test-runner.filelog.stdout.default", 0);
         charon->load_loggers(charon, NULL, FALSE);
         /* Register TKM specific plugins */
         static plugin_feature_t features[] = {
             PLUGIN_REGISTER(NONCE_GEN, tkm_nonceg_create),
                 PLUGIN_PROVIDE(NONCE_GEN),
             PLUGIN_CALLBACK(kernel_ipsec_register, tkm_kernel_ipsec_create),
                 PLUGIN_PROVIDE(CUSTOM, "kernel-ipsec"),
         };
         lib->plugins->add_static_features(lib->plugins, "tkm-tests", features,
                                           countof(features), TRUE, NULL, NULL);
         lib->settings->set_int(lib->settings, "%s.dh_mapping.%d", 1,
                                lib->ns, MODP_3072_BIT);
         lib->settings->set_int(lib->settings, "%s.dh_mapping.%d", 2,
                                lib->ns, MODP_4096_BIT);
         register_dh_mapping();
         plugin_loader_add_plugindirs(BUILDDIR "/src/libstrongswan/plugins",
                                      PLUGINS);
         plugin_loader_add_plugindirs(BUILDDIR "/src/libhydra/plugins",
                                      PLUGINS);
         plugin_loader_add_plugindirs(BUILDDIR "/src/libcharon/plugins",
                                      PLUGINS);
         if (charon->initialize(charon, PLUGINS))
         {
             if (!tkm_initialized)
             {
                 if (!tkm_init())
                 {
                     return FALSE;
                 }
                 tkm_initialized = true;
             }
             return TRUE;
         }
         result = FALSE;
     }
     destroy_dh_mapping();
     libcharon_deinit();
     libhydra_deinit();
     return result;
 }
Variable Documentation
test_configuration_t tests[] static
Initial value:
= {
#define TEST_SUITE(x)
#define TEST_SUITE_DEPEND(x, type, ...)
    { .suite = NULL, }
}
Definition at line 36 of file charon-tkm/tests/tests.c.
Referenced by sign_bliss().
bool tkm_initialized = false static
Definition at line 45 of file charon-tkm/tests/tests.c.
Referenced by test_runner_init().