strongSwan: vici_builder_t Struct Reference
vici_builder_t Struct Reference
vici_builder
#include "vici_builder.h"
Public Attributes
void(* add)(vici_builder_t *this, vici_type_t type,...)
void(* add_kv)(vici_builder_t *this, char *key, char *fmt,...)
void(* vadd_kv)(vici_builder_t *this, char *key, char *fmt, va_list args)
void(* add_li)(vici_builder_t *this, char *fmt,...)
void(* vadd_li)(vici_builder_t *this, char *fmt, va_list args)
void(* begin_section)(vici_builder_t *this, char *name)
void(* end_section)(vici_builder_t *this)
void(* begin_list)(vici_builder_t *this, char *name)
void(* end_list)(vici_builder_t *this)
vici_message_t *(* finalize)(vici_builder_t *this)
void(* destroy)(vici_builder_t *this)
Detailed Description
Build helper for vici message
Definition at line 31 of file vici_builder.h.
Member Data Documentation
void(* vici_builder_t::add)(vici_builder_t *this, vici_type_t type,...)
Append a generic message element to message.
The additional arguments are type specific, it may be nothing, a string, a chunk value or both.
Parameters
type element type to add
... additional type specific arguments
Definition at line 42 of file vici_builder.h.
Referenced by CALLBACK(), START_TEST(), vici_add_key_value(), vici_add_list_item(), vici_begin_list(), vici_begin_section(), vici_end_list(), vici_end_section(), vici_message_create_from_args(), and vici_message_create_from_enumerator().
void(* vici_builder_t::add_kv)(vici_builder_t *this, char *key, char *fmt,...)
Append a key/value element using a format string.
Instead of passing the type specific value as a chunk, this method takes a printf() style format string followed by its arguments. The key name for a key/value type is still a fixed string.
Parameters
key key name of the key/value to add
fmt value format string
... arguments to value format string
Definition at line 55 of file vici_builder.h.
Referenced by add_condition(), build_auth_cfgs(), CALLBACK(), create_reply(), list_child(), list_ike(), log_vici(), METHOD(), raise_policy(), raise_policy_cfg(), send_reply(), and START_TEST().
void(* vici_builder_t::add_li)(vici_builder_t *this, char *fmt,...)
Append a list item element using a format string.
Instead of passing the type specific value as a chunk, this method takes a printf() style format string followed by its arguments.
Parameters
fmt value format string
... arguments to value format string
Definition at line 79 of file vici_builder.h.
Referenced by build_auth_cfgs(), CALLBACK(), list_child(), list_task_queue(), list_vips(), raise_policy(), raise_policy_cfg(), and START_TEST().
void(* vici_builder_t::begin_list)(vici_builder_t *this, char *name)
Begin a new list.
Parameters
name name of list to begin
Definition at line 109 of file vici_builder.h.
Referenced by build_auth_cfgs(), CALLBACK(), list_child(), list_task_queue(), list_vips(), raise_policy(), raise_policy_cfg(), and START_TEST().
void(* vici_builder_t::begin_section)(vici_builder_t *this, char *name)
Begin a new section.
Parameters
name name of section to begin
Definition at line 97 of file vici_builder.h.
Referenced by build_auth_cfgs(), CALLBACK(), METHOD(), raise_policy(), raise_policy_cfg(), and START_TEST().
void(* vici_builder_t::destroy)(vici_builder_t *this)
Destroy a vici builder without finalization.
Note that finalize() already destroys the message, and calling destroy() is required only if the message does not get finalize()d.
Definition at line 129 of file vici_builder.h.
Referenced by vici_free_req().
void(* vici_builder_t::end_list)(vici_builder_t *this)
End the currently open list.
Definition at line 114 of file vici_builder.h.
Referenced by build_auth_cfgs(), CALLBACK(), list_child(), list_task_queue(), list_vips(), raise_policy(), raise_policy_cfg(), and START_TEST().
void(* vici_builder_t::end_section)(vici_builder_t *this)
End the currently open section.
Definition at line 102 of file vici_builder.h.
Referenced by build_auth_cfgs(), CALLBACK(), METHOD(), raise_policy(), raise_policy_cfg(), and START_TEST().
vici_message_t*(* vici_builder_t::finalize)(vici_builder_t *this)
Finalize a vici message with all added elements, destroy builder.
Returns
vici message, NULL on error
Definition at line 121 of file vici_builder.h.
Referenced by CALLBACK(), create_reply(), log_vici(), METHOD(), raise_policy(), raise_policy_cfg(), send_reply(), START_TEST(), vici_message_create_from_args(), vici_message_create_from_enumerator(), and vici_submit().
void(* vici_builder_t::vadd_kv)(vici_builder_t *this, char *key, char *fmt, va_list args)
Append a message element using a format string and va_list.
Instead of passing the type specific value as a chunk, this method takes a printf() style format string followed by its arguments. The key name for a key/value type is still a fixed string.
Parameters
key key name of the key/value to add
fmt value format string
args arguments to value format string
Definition at line 68 of file vici_builder.h.
Referenced by create_reply(), send_reply(), and vici_add_key_valuef().
void(* vici_builder_t::vadd_li)(vici_builder_t *this, char *fmt, va_list args)
Append a list item element using a format string and va_list.
Instead of passing the type specific value as a chunk, this method takes a printf() style format string followed by its arguments.
Parameters
fmt value format string
args arguments to value format string
Definition at line 90 of file vici_builder.h.
Referenced by vici_add_list_itemf().
The documentation for this struct was generated from the following file:
vici_builder.h