strongSwan: bliss_fft.c File Reference
bliss_fft.c File Reference
#include "bliss_fft.h"
Classes
struct private_bliss_fft_t
Typedefs
typedef struct private_bliss_fft_t private_bliss_fft_t
Functions
METHOD (bliss_fft_t, get_size, uint16_t, private_bliss_fft_t *this)
METHOD (bliss_fft_t, get_modulus, uint16_t, private_bliss_fft_t *this)
static void butterfly (private_bliss_fft_t *this, uint32_t *x, int i1, int i2, int iw)
static void butterfly_last (private_bliss_fft_t *this, uint32_t *x, int i1)
METHOD (bliss_fft_t, transform, void, private_bliss_fft_t *this, uint32_t *a, uint32_t *b, bool inverse)
METHOD (bliss_fft_t, destroy, void, private_bliss_fft_t *this)
bliss_fft_t * bliss_fft_create (bliss_fft_params_t *params)
Typedef Documentation
typedef struct private_bliss_fft_t private_bliss_fft_t
Definition at line 18 of file bliss_fft.c.
Function Documentation
static void butterfly (private_bliss_fft_t * this, uint32_t * x, int i1, int i2, int iw) static
Do an FFT butterfly operation
x[i1] —|+|----— x[i1] \/ /\ w[iw] x[i2] —|-|–|*|– x[i2]
Definition at line 57 of file bliss_fft.c.
Referenced by METHOD().
 {
     uint32_t xp, xm;
     xp = x[i1] + x[i2];
     xm = x[i1] + (this->p->q - x[i2]);
     if (xp >= this->p->q)
     {
         xp -= this->p->q;
     }
     x[i1] =  xp;
     x[i2] = (xm * this->p->w[iw]) % this->p->q;
 }
static void butterfly_last (private_bliss_fft_t * this, uint32_t * x, int i1) static
Trivial butterfly operation of last FFT stage
Definition at line 75 of file bliss_fft.c.
Referenced by METHOD().
 {
     uint32_t xp, xm;
     int i2 = i1 + 1;
     xp = x[i1] + x[i2];
     xm = x[i1] + (this->p->q - x[i2]);
     if (xp >= this->p->q)
     {
         xp -= this->p->q;
     }
     if (xm >= this->p->q)
     {
         xm -= this->p->q;
     }
     x[i1] = xp;
     x[i2] = xm;
 }
METHOD (bliss_fft_t , get_size , uint16_t , private_bliss_fft_t * this)
Definition at line 36 of file bliss_fft.c.
 {
     return this->p->n;
 }
METHOD (bliss_fft_t , get_modulus , uint16_t , private_bliss_fft_t * this)
Definition at line 42 of file bliss_fft.c.
 {
     return this->p->q;
 }
METHOD (bliss_fft_t , transform , void , private_bliss_fft_t * this, uint32_t * a, uint32_t * b, bool inverse)
Compensate the linear phase needed for negative wrapped convolution and normalize the output array with 1/n mod q after the inverse FFT.
Definition at line 94 of file bliss_fft.c.
References butterfly(), butterfly_last(), m, n, and q.
 {
     int stage, i, j, k, m, n, t, iw, i_rev;
     uint16_t q;
     uint32_t tmp;
     /* we are going to use the transform size n and the modulus q a lot */
     n = this->p->n;
     q = this->p->q;
     if (!inverse)
     {
         /* apply linear phase needed for negative wrapped convolution */
         for (i = 0; i < n; i++)
         {
             b[i] = (a[i] * this->p->w[i]) % q;
         }
     }
     else if (a != b)
     {
         /* copy if input and output array are not the same */
         for (i = 0; i < n; i++)
         {
             b[i] = a[i];
         }
     }
     m = n;
     k = 1;
     for (stage = this->p->stages; stage > 0; stage--)
     {
         m >>= 1;
         t = 0;
         for (j = 0; j < k; j++)
         {
             if (stage == 1)
             {
                 butterfly_last(this, b, t);
             }
             else
             {
                 for (i = 0; i < m; i++)
                 {
                     iw = 2 * (inverse ? (n - i * k) : (i * k));
                     butterfly(this, b, t + i, t + i + m, iw);
                 }
             }
             t += 2*m;
         }
         k <<= 1;
     }
     /* Sort output in bit-reverse order */
     for (i = 0; i < n; i++)
     {
         i_rev = this->p->rev[i];
         if (i_rev > i)
         {
             tmp = b[i];
             b[i] = b[i_rev];
             b[i_rev] = tmp;
         }
     }
     if (inverse)
     {
         for (i = 0; i < n; i++)
         {
             b[i] = (((b[i] * this->p->w[2*n - i]) % q) * this->p->n_inv) % q;
         }
     }
 }
METHOD (bliss_fft_t , destroy , void , private_bliss_fft_t * this)
Definition at line 175 of file bliss_fft.c.
References free().
 {
     free(this);
 }