strongSwan: phase1
phase1
ikev1
Classes
struct phase1_t
Typedefs
typedef struct phase1_t phase1_t
Functions
phase1_t * phase1_create (ike_sa_t *ike_sa, bool initiator)
Detailed Description
Typedef Documentation
typedef struct phase1_t phase1_t
Definition at line 24 of file phase1.h.
Function Documentation
phase1_t* phase1_create (ike_sa_t * ike_sa, bool initiator)
Create a phase1 instance.
Parameters
ike_sa IKE_SA to set up
initiator TRUE if initiating actively
Returns
Phase 1 helper
See header
Definition at line 789 of file phase1.c.
References ike_sa_t::get_keymat, INIT, initiator, and linked_list_create().
Referenced by aggressive_mode_create(), main_mode_create(), and METHOD().
 {
     private_phase1_t *this;
     INIT(this,
         .public = {
             .create_hasher = _create_hasher,
             .create_dh = _create_dh,
             .derive_keys = _derive_keys,
             .get_auth_method = _get_auth_method,
             .get_id = _get_id,
             .select_config = _select_config,
             .has_virtual_ip = _has_virtual_ip,
             .has_pool = _has_pool,
             .verify_auth = _verify_auth,
             .build_auth = _build_auth,
             .save_sa_payload = _save_sa_payload,
             .add_nonce_ke = _add_nonce_ke,
             .get_nonce_ke = _get_nonce_ke,
             .destroy = _destroy,
         },
         .candidates = linked_list_create(),
         .ike_sa = ike_sa,
         .initiator = initiator,
         .keymat = (keymat_v1_t*)ike_sa->get_keymat(ike_sa),
     );
     return &this->public;
 }