strongSwan: openssl_rsa_private_key
openssl_rsa_private_key
openssl
Classes
struct openssl_rsa_private_key_t
Typedefs
typedef struct
openssl_rsa_private_key_t openssl_rsa_private_key_t
Functions
openssl_rsa_private_key_t * openssl_rsa_private_key_gen (key_type_t type, va_list args)
openssl_rsa_private_key_t * openssl_rsa_private_key_load (key_type_t type, va_list args)
openssl_rsa_private_key_t * openssl_rsa_private_key_connect (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct openssl_rsa_private_key_t openssl_rsa_private_key_t
Definition at line 27 of file openssl_rsa_private_key.h.
Function Documentation
openssl_rsa_private_key_t* openssl_rsa_private_key_connect (key_type_t type, va_list args)
Connect to a RSA private key on a smartcard.
Accepts the BUILD_SMARTCARD_KEYID and the BUILD_SMARTCARD_PIN arguments.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 511 of file openssl_rsa_private_key.c.
References BUILD_END, BUILD_PKCS11_KEYID, BUILD_PKCS11_MODULE, BUILD_PKCS11_SLOT, chunk_empty, chunk_to_hex(), create_empty(), DBG1, DBG2, DBG_LIB, destroy(), FALSE, settings_t::get_str, key, keyid(), chunk_t::len, lib, login(), memset, library_t::ns, rsa, library_t::settings, snprintf, and TRUE.
Referenced by METHOD().
 {
 #ifndef OPENSSL_NO_ENGINE
     private_openssl_rsa_private_key_t *this;
     char *engine_id = NULL;
     char keyname[64];
     chunk_t keyid = chunk_empty;;
     EVP_PKEY *key;
     ENGINE *engine;
     int slot = -1;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_PKCS11_KEYID:
                 keyid = va_arg(args, chunk_t);
                 continue;
             case BUILD_PKCS11_SLOT:
                 slot = va_arg(args, int);
                 continue;
             case BUILD_PKCS11_MODULE:
                 engine_id = va_arg(args, char*);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!keyid.len || keyid.len > 40)
     {
         return NULL;
     }
     memset(keyname, 0, sizeof(keyname));
     if (slot != -1)
     {
         snprintf(keyname, sizeof(keyname), "%d:", slot);
     }
     if (sizeof(keyname) - strlen(keyname) <= keyid.len * 4 / 3 + 1)
     {
         return NULL;
     }
     chunk_to_hex(keyid, keyname + strlen(keyname), FALSE);
     if (!engine_id)
     {
         engine_id = lib->settings->get_str(lib->settings,
                             "%s.plugins.openssl.engine_id", "pkcs11", lib->ns);
     }
     engine = ENGINE_by_id(engine_id);
     if (!engine)
     {
         DBG2(DBG_LIB, "engine '%s' is not available", engine_id);
         return NULL;
     }
     if (!ENGINE_init(engine))
     {
         DBG1(DBG_LIB, "failed to initialize engine '%s'", engine_id);
         ENGINE_free(engine);
         return NULL;
     }
     if (!login(engine, keyid))
     {
         DBG1(DBG_LIB, "login to engine '%s' failed", engine_id);
         ENGINE_free(engine);
         return NULL;
     }
     key = ENGINE_load_private_key(engine, keyname, NULL, NULL);
     if (!key)
     {
         DBG1(DBG_LIB, "failed to load private key with ID '%s' from "
              "engine '%s'", keyname, engine_id);
         ENGINE_free(engine);
         return NULL;
     }
     ENGINE_free(engine);
     this = create_empty();
     this->rsa = EVP_PKEY_get1_RSA(key);
     this->engine = TRUE;
     if (!this->rsa)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 #else /* OPENSSL_NO_ENGINE */
     return NULL;
 #endif /* OPENSSL_NO_ENGINE */
 }
openssl_rsa_private_key_t* openssl_rsa_private_key_gen (key_type_t type, va_list args)
Generate a RSA private key using OpenSSL.
Accepts the BUILD_KEY_SIZE argument.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
generated key, NULL on failure
See header.
Definition at line 326 of file openssl_rsa_private_key.c.
References BUILD_END, BUILD_KEY_SIZE, create_empty(), key_size, PUBLIC_EXPONENT, rsa, and TRUE.
Referenced by METHOD().
 {
     private_openssl_rsa_private_key_t *this;
     u_int key_size = 0;
     RSA *rsa = NULL;
     BIGNUM *e = NULL;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_KEY_SIZE:
                 key_size = va_arg(args, u_int);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!key_size)
     {
         return NULL;
     }
     e = BN_new();
     if (!e || !BN_set_word(e, PUBLIC_EXPONENT))
     {
         goto error;
     }
     rsa = RSA_new();
     if (!rsa || !RSA_generate_key_ex(rsa, key_size, e, NULL))
     {
         goto error;
     }
     this = create_empty();
     this->rsa = rsa;
     BN_free(e);
     return &this->public;
 error:
     if (e)
     {
         BN_free(e);
     }
     if (rsa)
     {
         RSA_free(rsa);
     }
     return NULL;
 }
openssl_rsa_private_key_t* openssl_rsa_private_key_load (key_type_t type, va_list args)
Load a RSA private key using OpenSSL.
Accepts a BUILD_BLOB_ASN1_DER argument.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header
Definition at line 382 of file openssl_rsa_private_key.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_RSA_COEFF, BUILD_RSA_EXP1, BUILD_RSA_EXP2, BUILD_RSA_MODULUS, BUILD_RSA_PRIME1, BUILD_RSA_PRIME2, BUILD_RSA_PRIV_EXP, BUILD_RSA_PUB_EXP, chunk_empty, create_empty(), destroy(), chunk_t::len, n, chunk_t::ptr, q, rsa, and TRUE.
Referenced by METHOD().
 {
     private_openssl_rsa_private_key_t *this;
     chunk_t blob, n, e, d, p, q, exp1, exp2, coeff;
     blob = n = e = d = p = q = exp1 = exp2 = coeff = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_MODULUS:
                 n = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PUB_EXP:
                 e = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIV_EXP:
                 d = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIME1:
                 p = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIME2:
                 q = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_EXP1:
                 exp1 = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_EXP2:
                 exp2 = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_COEFF:
                 coeff = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     this = create_empty();
     if (blob.ptr)
     {
         this->rsa = d2i_RSAPrivateKey(NULL, (const u_char**)&blob.ptr, blob.len);
         if (this->rsa && RSA_check_key(this->rsa) == 1)
         {
             return &this->public;
         }
     }
     else if (n.ptr && e.ptr && d.ptr && p.ptr && q.ptr && coeff.ptr)
     {
         this->rsa = RSA_new();
         this->rsa->n = BN_bin2bn((const u_char*)n.ptr, n.len, NULL);
         this->rsa->e = BN_bin2bn((const u_char*)e.ptr, e.len, NULL);
         this->rsa->d = BN_bin2bn((const u_char*)d.ptr, d.len, NULL);
         this->rsa->p = BN_bin2bn((const u_char*)p.ptr, p.len, NULL);
         this->rsa->q = BN_bin2bn((const u_char*)q.ptr, q.len, NULL);
         if (exp1.ptr)
         {
             this->rsa->dmp1 = BN_bin2bn((const u_char*)exp1.ptr, exp1.len, NULL);
         }
         if (exp2.ptr)
         {
             this->rsa->dmq1 = BN_bin2bn((const u_char*)exp2.ptr, exp2.len, NULL);
         }
         this->rsa->iqmp = BN_bin2bn((const u_char*)coeff.ptr, coeff.len, NULL);
         if (RSA_check_key(this->rsa) == 1)
         {
             return &this->public;
         }
     }
     destroy(this);
     return NULL;
 }