strongSwan: resolver_manager_t Struct Reference
resolver_manager_t Struct Reference
resolver_manager
#include "resolver_manager.h"
Public Attributes
void(* add_resolver)(resolver_manager_t *this, resolver_constructor_t constructor)
void(* remove_resolver)(resolver_manager_t *this, resolver_constructor_t constructor)
resolver_t *(* create)(resolver_manager_t *this)
void(* destroy)(resolver_manager_t *this)
Detailed Description
The resolver_manager manages the resolver implementations and creates instances of them.
A resolver plugin is registered by providing its constructor function to the manager. The manager creates instances of the resolver plugin using the registered constructor function.
Definition at line 36 of file resolver_manager.h.
Member Data Documentation
void(* resolver_manager_t::add_resolver)(resolver_manager_t *this, resolver_constructor_t constructor)
Register a resolver implementation.
Parameters
constructor resolver constructor function
Definition at line 43 of file resolver_manager.h.
Referenced by plugin_feature_load().
resolver_t*(* resolver_manager_t::create)(resolver_manager_t *this)
Get a new resolver instance.
Returns
resolver instance.
Definition at line 59 of file resolver_manager.h.
Referenced by main(), and plugin_cb().
void(* resolver_manager_t::destroy)(resolver_manager_t *this)
Destroy a resolver_manager instance.
Definition at line 64 of file resolver_manager.h.
void(* resolver_manager_t::remove_resolver)(resolver_manager_t *this, resolver_constructor_t constructor)
Unregister a previously registered resolver implementation.
Parameters
constructor resolver constructor function to unregister
Definition at line 51 of file resolver_manager.h.
Referenced by plugin_feature_unload().
The documentation for this struct was generated from the following file:
resolver_manager.h