strongSwan: eap_aka_3gpp2_plugin.c File Reference
eap_aka_3gpp2_plugin.c File Reference
#include "eap_aka_3gpp2_plugin.h"
#include "eap_aka_3gpp2_card.h"
#include "eap_aka_3gpp2_provider.h"
#include "eap_aka_3gpp2_functions.h"
#include <daemon.h>
Classes
struct private_eap_aka_3gpp2_t
Typedefs
typedef struct
private_eap_aka_3gpp2_t private_eap_aka_3gpp2_t
Functions
METHOD (plugin_t, get_name, char *, private_eap_aka_3gpp2_t *this)
static bool register_functions (private_eap_aka_3gpp2_t *this, plugin_feature_t *feature, bool reg, void *data)
static simaka_card_t * get_card (private_eap_aka_3gpp2_t *this)
static simaka_provider_t * get_provider (private_eap_aka_3gpp2_t *this)
METHOD (plugin_t, get_features, int, private_eap_aka_3gpp2_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_eap_aka_3gpp2_t *this)
plugin_t * eap_aka_3gpp2_plugin_create ()
Typedef Documentation
typedef struct private_eap_aka_3gpp2_t private_eap_aka_3gpp2_t
Definition at line 23 of file eap_aka_3gpp2_plugin.c.
Function Documentation
plugin_t* eap_aka_3gpp2_plugin_create ()
See header
Definition at line 128 of file eap_aka_3gpp2_plugin.c.
References INIT.
 {
     private_eap_aka_3gpp2_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
static simaka_card_t* get_card (private_eap_aka_3gpp2_t * this) static
Callback providing our card to register
Definition at line 86 of file eap_aka_3gpp2_plugin.c.
Referenced by METHOD().
 {
     return &this->card->card;
 }
static simaka_provider_t* get_provider (private_eap_aka_3gpp2_t * this) static
Callback providing our provider to register
Definition at line 94 of file eap_aka_3gpp2_plugin.c.
Referenced by METHOD().
 {
     return &this->provider->provider;
 }
METHOD (plugin_t , get_name , char * , private_eap_aka_3gpp2_t * this)
Definition at line 51 of file eap_aka_3gpp2_plugin.c.
 {
     return "eap-aka-3gpp2";
 }
METHOD (plugin_t , get_features , int , private_eap_aka_3gpp2_t * this, plugin_feature_t * features[])
Definition at line 99 of file eap_aka_3gpp2_plugin.c.
References countof, get_card(), get_provider(), PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, PRF_KEYED_SHA1, register_functions(), and simaka_manager_register().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((void*)register_functions, NULL),
             PLUGIN_PROVIDE(CUSTOM, "eap-aka-3gpp2-functions"),
                 PLUGIN_DEPENDS(PRF, PRF_KEYED_SHA1),
         PLUGIN_CALLBACK(simaka_manager_register, get_card),
             PLUGIN_PROVIDE(CUSTOM, "aka-card"),
                 PLUGIN_DEPENDS(CUSTOM, "aka-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-aka-3gpp2-functions"),
         PLUGIN_CALLBACK(simaka_manager_register, get_provider),
             PLUGIN_PROVIDE(CUSTOM, "aka-provider"),
                 PLUGIN_DEPENDS(CUSTOM, "aka-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-aka-3gpp2-functions"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_eap_aka_3gpp2_t * this)
Definition at line 119 of file eap_aka_3gpp2_plugin.c.
References free().
 {
     free(this);
 }
static bool register_functions (private_eap_aka_3gpp2_t * this, plugin_feature_t * feature, bool reg, void * data) static
Try to instanciate 3gpp2 functions and card/provider backends
Definition at line 60 of file eap_aka_3gpp2_plugin.c.
References hashtable_t::destroy, eap_aka_3gpp2_card_create(), eap_aka_3gpp2_functions_create(), eap_aka_3gpp2_provider_create(), FALSE, functions, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->functions = eap_aka_3gpp2_functions_create();
         if (!this->functions)
         {
             return FALSE;
         }
         this->card = eap_aka_3gpp2_card_create(this->functions);
         this->provider = eap_aka_3gpp2_provider_create(this->functions);
         return TRUE;
     }
     this->card->destroy(this->card);
     this->provider->destroy(this->provider);
     this->functions->destroy(this->functions);
     this->card = NULL;
     this->provider = NULL;
     this->functions = NULL;
     return TRUE;
 }