strongSwan: semaphore.c File Reference
windows/semaphore.c File Reference
#include <library.h>
#include <threading/semaphore.h>
Classes
struct private_semaphore_t
Typedefs
typedef struct private_semaphore_t private_semaphore_t
Functions
METHOD (semaphore_t, timed_wait, bool, private_semaphore_t *this, u_int timeout)
METHOD (semaphore_t, timed_wait_abs, bool, private_semaphore_t *this, timeval_t tv)
METHOD (semaphore_t, wait_, void, private_semaphore_t *this)
METHOD (semaphore_t, post, void, private_semaphore_t *this)
METHOD (semaphore_t, destroy, void, private_semaphore_t *this)
semaphore_t * semaphore_create (u_int value)
Typedef Documentation
typedef struct private_semaphore_t private_semaphore_t
Definition at line 19 of file windows/semaphore.c.
Function Documentation
METHOD (semaphore_t , timed_wait , bool , private_semaphore_t * this, u_int timeout)
Definition at line 36 of file windows/semaphore.c.
References handle, and TRUE.
 {
     /* use alertable wait to allow cancellation */
     return WaitForSingleObjectEx(this->handle, timeout, TRUE) == WAIT_TIMEOUT;
 }
METHOD (semaphore_t , timed_wait_abs , bool , private_semaphore_t * this, timeval_t tv)
Definition at line 43 of file windows/semaphore.c.
References DWORD, time_monotonic(), timersub(), and TRUE.
 {
     DWORD timeout;
     timeval_t now, diff;
     time_monotonic(&now);
     if (timercmp(&now, &tv, >))
     {
         return TRUE;
     }
     timersub(&tv, &now, &diff);
     timeout = diff.tv_sec * 1000 + diff.tv_usec / 1000;
     return timed_wait(this, timeout);
 }
METHOD (semaphore_t , wait_ , void , private_semaphore_t * this)
Definition at line 60 of file windows/semaphore.c.
 {
     timed_wait(this, INFINITE);
 }
METHOD (semaphore_t , post , void , private_semaphore_t * this)
Definition at line 66 of file windows/semaphore.c.
References handle.
 {
     ReleaseSemaphore(this->handle, 1, NULL);
 }
METHOD (semaphore_t , destroy , void , private_semaphore_t * this)
Definition at line 72 of file windows/semaphore.c.
References free(), and handle.
 {
     CloseHandle(this->handle);
     free(this);
 }