strongSwan: dhcp_transaction.c File Reference
dhcp_transaction.c File Reference
#include "dhcp_transaction.h"
#include <collections/linked_list.h>
Classes
struct private_dhcp_transaction_t
struct attribute_entry_t
Typedefs
typedef struct
private_dhcp_transaction_t private_dhcp_transaction_t
Functions
METHOD (dhcp_transaction_t, get_id, u_int32_t, private_dhcp_transaction_t *this)
METHOD (dhcp_transaction_t, get_identity, identification_t *, private_dhcp_transaction_t *this)
METHOD (dhcp_transaction_t, set_address, void, private_dhcp_transaction_t *this, host_t *address)
METHOD (dhcp_transaction_t, get_address, host_t *, private_dhcp_transaction_t *this)
METHOD (dhcp_transaction_t, set_server, void, private_dhcp_transaction_t *this, host_t *server)
METHOD (dhcp_transaction_t, get_server, host_t *, private_dhcp_transaction_t *this)
METHOD (dhcp_transaction_t, add_attribute, void, private_dhcp_transaction_t *this, configuration_attribute_type_t type, chunk_t data)
static bool attribute_filter (void *null, attribute_entry_t **entry, configuration_attribute_type_t *type, void **dummy, chunk_t *data)
METHOD (dhcp_transaction_t, create_attribute_enumerator, enumerator_t *, private_dhcp_transaction_t *this)
static void attribute_entry_destroy (attribute_entry_t *entry)
METHOD (dhcp_transaction_t, destroy, void, private_dhcp_transaction_t *this)
dhcp_transaction_t * dhcp_transaction_create (u_int32_t id, identification_t *identity)
Typedef Documentation
typedef struct private_dhcp_transaction_t private_dhcp_transaction_t
Definition at line 20 of file dhcp_transaction.c.
Function Documentation
static void attribute_entry_destroy (attribute_entry_t * entry) static
Clean up an attribute entry
Definition at line 140 of file dhcp_transaction.c.
References attribute_entry_t::data, free(), and chunk_t::ptr.
Referenced by METHOD().
 {
     free(entry->data.ptr);
     free(entry);
 }
static bool attribute_filter (void * null, attribute_entry_t ** entry, configuration_attribute_type_t * type, void ** dummy, chunk_t * data) static
Filter function to map entries to type/data
Definition at line 120 of file dhcp_transaction.c.
References TRUE.
Referenced by METHOD().
 {
     *type = (*entry)->type;
     *data = (*entry)->data;
     return TRUE;
 }
METHOD (dhcp_transaction_t , get_id , u_int32_t , private_dhcp_transaction_t * this)
Definition at line 66 of file dhcp_transaction.c.
References id.
 {
     return this->id;
 }
METHOD (dhcp_transaction_t , get_identity , identification_t * , private_dhcp_transaction_t * this)
Definition at line 72 of file dhcp_transaction.c.
References identity.
 {
     return this->identity;
 }
METHOD (dhcp_transaction_t , set_address , void , private_dhcp_transaction_t * this, host_t * address)
Definition at line 78 of file dhcp_transaction.c.
References DESTROY_IF.
 {
     DESTROY_IF(this->address);
     this->address = address;
 }
METHOD (dhcp_transaction_t , get_address , host_t * , private_dhcp_transaction_t * this)
Definition at line 85 of file dhcp_transaction.c.
 {
     return this->address;
 }
METHOD (dhcp_transaction_t , set_server , void , private_dhcp_transaction_t * this, host_t * server)
Definition at line 91 of file dhcp_transaction.c.
References DESTROY_IF, and server.
 {
     DESTROY_IF(this->server);
     this->server = server;
 }
METHOD (dhcp_transaction_t , get_server , host_t * , private_dhcp_transaction_t * this)
Definition at line 98 of file dhcp_transaction.c.
References server.
 {
     return this->server;
 }
METHOD (dhcp_transaction_t , add_attribute , void , private_dhcp_transaction_t * this, configuration_attribute_type_t type, chunk_t data)
Definition at line 104 of file dhcp_transaction.c.
References attributes, chunk_clone, and INIT.
 {
     attribute_entry_t *entry;
     INIT(entry,
         .type = type,
         .data = chunk_clone(data),
     );
     this->attributes->insert_last(this->attributes, entry);
 }
METHOD (dhcp_transaction_t , create_attribute_enumerator , enumerator_t * , private_dhcp_transaction_t * this)
Definition at line 129 of file dhcp_transaction.c.
References attribute_filter(), attributes, and enumerator_create_filter().
 {
     return enumerator_create_filter(
                         this->attributes->create_enumerator(this->attributes),
                         (void*)attribute_filter, NULL, NULL);
 }
METHOD (dhcp_transaction_t , destroy , void , private_dhcp_transaction_t * this)
Definition at line 146 of file dhcp_transaction.c.
References attribute_entry_destroy(), attributes, DESTROY_IF, free(), identity, and server.
 {
     this->identity->destroy(this->identity);
     DESTROY_IF(this->address);
     DESTROY_IF(this->server);
     this->attributes->destroy_function(this->attributes,
                                        (void*)attribute_entry_destroy);
     free(this);
 }