strongSwan: ita_attr_dummy.c File Reference
ita_attr_dummy.c File Reference
#include "ita_attr.h"
#include "ita_attr_dummy.h"
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_ita_attr_dummy_t
Typedefs
typedef struct
private_ita_attr_dummy_t private_ita_attr_dummy_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ita_attr_dummy_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ita_attr_dummy_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ita_attr_dummy_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ita_attr_dummy_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ita_attr_dummy_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ita_attr_dummy_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ita_attr_dummy_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ita_attr_dummy_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ita_attr_dummy_t *this)
METHOD (ita_attr_dummy_t, get_size, int, private_ita_attr_dummy_t *this)
pa_tnc_attr_t * ita_attr_dummy_create (size_t size)
pa_tnc_attr_t * ita_attr_dummy_create_from_data (size_t length, chunk_t data)
Typedef Documentation
typedef struct private_ita_attr_dummy_t private_ita_attr_dummy_t
Definition at line 23 of file ita_attr_dummy.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ita_attr_dummy_t * this)
Definition at line 66 of file ita_attr_dummy.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ita_attr_dummy_t * this)
Definition at line 72 of file ita_attr_dummy.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ita_attr_dummy_t * this)
Definition at line 78 of file ita_attr_dummy.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ita_attr_dummy_t * this, bool noskip)
Definition at line 84 of file ita_attr_dummy.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ita_attr_dummy_t * this)
Definition at line 90 of file ita_attr_dummy.c.
References chunk_alloc, length, memset, and value.
 {
     if (this->value.ptr)
     {
         return;
     }
     this->value = chunk_alloc(this->length);
     memset(this->value.ptr, 0xdd, this->value.len);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ita_attr_dummy_t * this, u_int32_t * offset)
Definition at line 101 of file ita_attr_dummy.c.
References NEED_MORE, SUCCESS, and value.
 {
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ita_attr_dummy_t * this, chunk_t segment)
Definition at line 113 of file ita_attr_dummy.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ita_attr_dummy_t * this)
Definition at line 119 of file ita_attr_dummy.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ita_attr_dummy_t * this)
Definition at line 126 of file ita_attr_dummy.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ita_attr_dummy_t , get_size , int , private_ita_attr_dummy_t * this)
Definition at line 136 of file ita_attr_dummy.c.
References length.
 {
     return this->length;
 }