strongSwan: vici_authority.c File Reference
vici_authority.c File Reference
#include "vici_authority.h"
#include "vici_builder.h"
#include <threading/rwlock.h>
#include <collections/linked_list.h>
#include <credentials/certificates/x509.h>
#include <utils/debug.h>
#include <stdio.h>
Classes
struct private_vici_authority_t
struct authority_t
struct parse_rule_t
struct request_data_t
struct load_data_t
struct cdp_data_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_vici_authority_t private_vici_authority_t
typedef struct authority_t authority_t
Functions
static authority_t * authority_create (char *name)
static void authority_destroy (authority_t *this)
static vici_message_t * create_reply (char *fmt,...)
static bool parse_rules (parse_rule_t *rules, int count, char *name, chunk_t value, vici_message_t **reply)
CALLBACK (parse_string, bool, char **str, chunk_t v)
CALLBACK (parse_uris, bool, linked_list_t *out, chunk_t v)
CALLBACK (parse_cacert, bool, certificate_t **cacert, chunk_t v)
CALLBACK (authority_kv, bool, load_data_t *data, vici_message_t *message, char *name, chunk_t value)
CALLBACK (authority_li, bool, load_data_t *data, vici_message_t *message, char *name, chunk_t value)
static void log_authority_data (authority_t *authority)
CALLBACK (authority_sn, bool, request_data_t *request, vici_message_t *message, vici_parse_context_t *ctx, char *name)
CALLBACK (load_authority, vici_message_t *, private_vici_authority_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (unload_authority, vici_message_t *, private_vici_authority_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (get_authorities, vici_message_t *, private_vici_authority_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (list_authorities, vici_message_t *, private_vici_authority_t *this, char *name, u_int id, vici_message_t *request)
static void manage_command (private_vici_authority_t *this, char *name, vici_command_cb_t cb, bool reg)
static void manage_commands (private_vici_authority_t *this, bool reg)
static void cdp_data_destroy (cdp_data_t *data)
static enumerator_t * create_inner_cdp (authority_t *authority, cdp_data_t *data)
static enumerator_t * create_inner_cdp_hashandurl (authority_t *authority, cdp_data_t *data)
METHOD (credential_set_t, create_cdp_enumerator, enumerator_t *, private_vici_authority_t *this, certificate_type_t type, identification_t *id)
METHOD (vici_authority_t, check_for_hash_and_url, void, private_vici_authority_t *this, certificate_t *cert)
METHOD (vici_authority_t, destroy, void, private_vici_authority_t *this)
vici_authority_t * vici_authority_create (vici_dispatcher_t *dispatcher, vici_cred_t *cred)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file vici_authority.c.
Typedef Documentation
typedef struct authority_t authority_t
Definition at line 62 of file vici_authority.c.
typedef struct private_vici_authority_t private_vici_authority_t
Definition at line 28 of file vici_authority.c.
Function Documentation
static authority_t* authority_create (char * name) static
create a new certification authority
Definition at line 103 of file vici_authority.c.
References INIT, linked_list_create(), and strdup.
Referenced by CALLBACK().
 {
     authority_t *authority;
     INIT(authority,
         .name = strdup(name),
         .crl_uris = linked_list_create(),
         .ocsp_uris = linked_list_create(),
         .hashes = linked_list_create(),
     );
     return authority;
 }
static void authority_destroy (authority_t * this) static
destroy a certification authority
Definition at line 120 of file vici_authority.c.
References cert, destroy(), DESTROY_IF, free(), and name.
Referenced by CALLBACK(), and METHOD().
 {
     this->crl_uris->destroy_function(this->crl_uris, free);
     this->ocsp_uris->destroy_function(this->ocsp_uris, free);
     this->hashes->destroy_offset(this->hashes, offsetof(identification_t, destroy));
     DESTROY_IF(this->cert);
     free(this->cert_uri_base);
     free(this->name);
     free(this);
 }
CALLBACK (parse_string , bool , char ** str, chunk_t v)
Parse a string
Definition at line 207 of file vici_authority.c.
References chunk_printable(), FALSE, chunk_t::len, chunk_t::ptr, strndup(), and TRUE.
 {
     if (!chunk_printable(v, NULL, ' '))
     {
         return FALSE;
     }
     *str = strndup(v.ptr, v.len);
     return TRUE;
 }
CALLBACK (parse_uris , bool , linked_list_t * out, chunk_t v)
Parse list of URIs
Definition at line 222 of file vici_authority.c.
References chunk_printable(), FALSE, linked_list_t::insert_last, chunk_t::len, chunk_t::ptr, strndup(), TRUE, and uri.
 {
     char *uri;
     if (!chunk_printable(v, NULL, ' '))
     {
         return FALSE;
     }
     uri = strndup(v.ptr, v.len);
     out->insert_last(out, uri);
     return TRUE;
 }
CALLBACK (parse_cacert , bool , certificate_t ** cacert, chunk_t v)
Parse a CA certificate
Definition at line 240 of file vici_authority.c.
References BUILD_BLOB_PEM, BUILD_END, cert, CERT_X509, certificate_type_names, credential_factory_t::create, create_reply(), CRED_CERTIFICATE, library_t::creds, certificate_t::destroy, x509_t::get_flags, lib, TRUE, and X509_CA.
 {
     certificate_t *cert;
     x509_t *x509;
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                           BUILD_BLOB_PEM, v, BUILD_END);
     if (!cert)
     {
         return create_reply("parsing %N certificate failed",
                             certificate_type_names, CERT_X509);
     }
     x509 = (x509_t*)cert;
     if ((x509->get_flags(x509) & X509_CA) != X509_CA)
     {
         cert->destroy(cert);
         return create_reply("certificate without CA flag, rejected");
     }
     *cacert = cert;
     return TRUE;
 }
CALLBACK (authority_kv , bool , load_data_t * data, vici_message_t * message, char * name, chunk_t value)
Definition at line 265 of file vici_authority.c.
References load_data_t::authority, authority_t::cert, authority_t::cert_uri_base, countof, parse_rules(), request_data_t::reply, and load_data_t::request.
 {
     parse_rule_t rules[] = {
         { "cacert",         parse_cacert, &data->authority->cert          },
         { "cert_uri_base",  parse_string, &data->authority->cert_uri_base },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &data->request->reply);
 }
CALLBACK (authority_li , bool , load_data_t * data, vici_message_t * message, char * name, chunk_t value)
Definition at line 277 of file vici_authority.c.
References load_data_t::authority, countof, authority_t::crl_uris, authority_t::ocsp_uris, parse_rules(), request_data_t::reply, and load_data_t::request.
 {
     parse_rule_t rules[] = {
         { "crl_uris",   parse_uris, data->authority->crl_uris  },
         { "ocsp_uris",  parse_uris, data->authority->ocsp_uris },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &data->request->reply);
 }
CALLBACK (authority_sn , bool , request_data_t * request, vici_message_t * message, vici_parse_context_t * ctx, char * name)
Definition at line 336 of file vici_authority.c.
References vici_cred_t::add_cert, load_data_t::authority, authority_create(), authority_destroy(), authority_t::cert, linked_list_t::create_enumerator, data, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, linked_list_t::insert_last, private_vici_attribute_t::lock, log_authority_data(), authority_t::name, vici_message_t::parse, linked_list_t::remove_at, request(), streq(), request_data_t::this, TRUE, rwlock_t::unlock, and rwlock_t::write_lock.
 {
     enumerator_t *enumerator;
     linked_list_t *authorities;
     authority_t *authority;
     vici_cred_t *cred;
     load_data_t data = {
         .request = request,
         .authority = authority_create(name),
     };
     DBG2(DBG_CFG, " authority %s:", name);
     if (!message->parse(message, ctx, NULL, authority_kv, authority_li, &data) ||
         !data.authority->cert)
     {
         authority_destroy(data.authority);
         return FALSE;
     }
     log_authority_data(data.authority);
     request->this->lock->write_lock(request->this->lock);
     authorities = request->this->authorities;
     enumerator = authorities->create_enumerator(authorities);
     while (enumerator->enumerate(enumerator, &authority))
     {
         if (streq(authority->name, name))
         {
             /* remove the old authority definition */
             authorities->remove_at(authorities, enumerator);
             authority_destroy(authority);
             break;
         }
     }
     enumerator->destroy(enumerator);
     authorities->insert_last(authorities, data.authority);
     cred = request->this->cred;
     data.authority->cert = cred->add_cert(cred, data.authority->cert);
     request->this->lock->unlock(request->this->lock);
     return TRUE;
 }
CALLBACK (load_authority , vici_message_t * , private_vici_authority_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 385 of file vici_authority.c.
References create_reply(), vici_message_t::parse, request_data_t::reply, and request().
 {
     request_data_t request = {
         .this = this,
     };
     if (!message->parse(message, NULL, authority_sn, NULL, NULL, &request))
     {
         if (request.reply)
         {
             return request.reply;
         }
         return create_reply("parsing request failed");
     }
     return create_reply(NULL);
 }
CALLBACK (unload_authority , vici_message_t * , private_vici_authority_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 403 of file vici_authority.c.
References authority_destroy(), create_reply(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, vici_message_t::get_str, lock, authority_t::name, streq(), TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     authority_t *authority;
     char *authority_name;
     bool found = FALSE;
     authority_name = message->get_str(message, NULL, "name");
     if (!authority_name)
     {
         return create_reply("unload: missing authority name");
     }
     this->lock->write_lock(this->lock);
     enumerator = this->authorities->create_enumerator(this->authorities);
     while (enumerator->enumerate(enumerator, &authority))
     {
         if (streq(authority->name, authority_name))
         {
             this->authorities->remove_at(this->authorities, enumerator);
             authority_destroy(authority);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!found)
     {
         return create_reply("unload: authority '%s' not found", authority_name);
     }
     return create_reply(NULL);
 }
CALLBACK (get_authorities , vici_message_t * , private_vici_authority_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 439 of file vici_authority.c.
References vici_builder_t::add_li, vici_builder_t::begin_list, enumerator_t::destroy, vici_builder_t::end_list, enumerator_t::enumerate, vici_builder_t::finalize, lock, authority_t::name, spinlock_t::unlock, and vici_builder_create().
 {
     vici_builder_t *builder;
     enumerator_t *enumerator;
     authority_t *authority;
     builder = vici_builder_create();
     builder->begin_list(builder, "authorities");
     this->lock->read_lock(this->lock);
     enumerator = this->authorities->create_enumerator(this->authorities);
     while (enumerator->enumerate(enumerator, &authority))
     {
         builder->add_li(builder, "%s", authority->name);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     builder->end_list(builder);
     return builder->finalize(builder);
 }
CALLBACK (list_authorities , vici_message_t * , private_vici_authority_t * this, char * name, u_int id, vici_message_t * request)
Definition at line 464 of file vici_authority.c.
References vici_builder_t::add_kv, vici_builder_t::add_li, b, vici_builder_t::begin_list, vici_builder_t::begin_section, authority_t::cert, authority_t::cert_uri_base, linked_list_t::create_enumerator, authority_t::crl_uris, enumerator_t::destroy, vici_builder_t::end_list, vici_builder_t::end_section, enumerator_t::enumerate, vici_builder_t::finalize, vici_message_t::get_str, certificate_t::get_subject, lock, authority_t::name, authority_t::ocsp_uris, str, streq(), spinlock_t::unlock, uri, and vici_builder_create().
 {
     enumerator_t *enumerator, *e;
     authority_t *authority;
     vici_builder_t *b;
     char *str, *uri;
     str = request->get_str(request, NULL, "name");
     this->lock->read_lock(this->lock);
     enumerator = this->authorities->create_enumerator(this->authorities);
     while (enumerator->enumerate(enumerator, &authority))
     {
         if (str && !streq(str, authority->name))
         {
             continue;
         }
         b = vici_builder_create();
         /* open authority section */
         b->begin_section(b, authority->name);
         /* subject DN of cacert */
         b->add_kv(b, "cacert", "%Y",
                       authority->cert->get_subject(authority->cert));
         /* list of crl_uris */
         b->begin_list(b, "crl_uris");
         e = authority->crl_uris->create_enumerator(authority->crl_uris);
         while (e->enumerate(e, &uri))
         {
             b->add_li(b, "%s", uri);
         }
         e->destroy(e);
         b->end_list(b);
         /* list of ocsp_uris */
         b->begin_list(b, "ocsp_uris");
         e = authority->ocsp_uris->create_enumerator(authority->ocsp_uris);
         while (e->enumerate(e, &uri))
         {
             b->add_li(b, "%s", uri);
         }
         e->destroy(e);
         b->end_list(b);
         /* cert_uri_base */
         if (authority->cert_uri_base)
         {
             b->add_kv(b, "cert_uri_base", "%s", authority->cert_uri_base);
         }
         /* close authority and raise event */
         b->end_section(b);
         this->dispatcher->raise_event(this->dispatcher, "list-authority", id,
                                       b->finalize(b));
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     b = vici_builder_create();
     return b->finalize(b);
 }
static void cdp_data_destroy (cdp_data_t * data) static
destroy cdp enumerator data and unlock list
Definition at line 561 of file vici_authority.c.
References free(), private_stroke_ca_t::lock, cdp_data_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static enumerator_t* create_inner_cdp (authority_t * authority, cdp_data_t * data) static
inner enumerator constructor for CDP URIs
Definition at line 570 of file vici_authority.c.
References authority_t::cert, CERT_X509_OCSP_RESPONSE, linked_list_t::create_enumerator, authority_t::crl_uris, enumerator_t::destroy, identification_t::get_encoding, certificate_t::get_public_key, cdp_data_t::id, list, authority_t::ocsp_uris, public, and cdp_data_t::type.
Referenced by METHOD().
 {
     public_key_t *public;
     enumerator_t *enumerator = NULL;
     linked_list_t *list;
     if (data->type == CERT_X509_OCSP_RESPONSE)
     {
         list = authority->ocsp_uris;
     }
     else
     {
         list = authority->crl_uris;
     }
     public = authority->cert->get_public_key(authority->cert);
     if (public)
     {
         if (!data->id)
         {
             enumerator = list->create_enumerator(list);
         }
         else
         {
             if (public->has_fingerprint(public, data->id->get_encoding(data->id)))
             {
                 enumerator = list->create_enumerator(list);
             }
         }
         public->destroy(public);
     }
     return enumerator;
 }
static enumerator_t* create_inner_cdp_hashandurl (authority_t * authority, cdp_data_t * data) static
inner enumerator constructor for "Hash and URL"
Definition at line 607 of file vici_authority.c.
References authority_t::cert_uri_base, chunk_to_hex(), linked_list_t::create_enumerator, enumerator_create_single(), FALSE, free(), identification_t::get_encoding, hash, authority_t::hashes, cdp_data_t::id, malloc(), and identification_t::matches.
Referenced by METHOD().
 {
     enumerator_t *enumerator = NULL, *hash_enum;
     identification_t *current;
     if (!data->id || !authority->cert_uri_base)
     {
         return NULL;
     }
     hash_enum = authority->hashes->create_enumerator(authority->hashes);
     while (hash_enum->enumerate(hash_enum, &current))
     {
         if (current->matches(current, data->id))
         {
             char *url, *hash;
             url = malloc(strlen(authority->cert_uri_base) + 40 + 1);
             strcpy(url, authority->cert_uri_base);
             hash = chunk_to_hex(current->get_encoding(current), NULL, FALSE).ptr;
             strncat(url, hash, 40);
             free(hash);
             enumerator = enumerator_create_single(url, free);
             break;
         }
     }
     hash_enum->destroy(hash_enum);
     return enumerator;
 }
static vici_message_t* create_reply (char * fmt, ...) static
Create a (error) reply message
Definition at line 135 of file vici_authority.c.
References vici_builder_t::add_kv, vici_builder_t::finalize, vici_builder_t::vadd_kv, and vici_builder_create().
Referenced by CALLBACK(), and parse_rules().
 {
     vici_builder_t *builder;
     va_list args;
     builder = vici_builder_create();
     builder->add_kv(builder, "success", fmt ? "no" : "yes");
     if (fmt)
     {
         va_start(args, fmt);
         builder->vadd_kv(builder, "errmsg", fmt, args);
         va_end(args);
     }
     return builder->finalize(builder);
 }
static void log_authority_data (authority_t * authority) static
Definition at line 289 of file vici_authority.c.
References authority_t::cert, authority_t::cert_uri_base, linked_list_t::create_enumerator, authority_t::crl_uris, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, certificate_t::get_subject, authority_t::ocsp_uris, subject, TRUE, and uri.
Referenced by CALLBACK().
 {
     enumerator_t *enumerator;
     identification_t *subject;
     bool first = TRUE;
     char *uri;
     subject = authority->cert->get_subject(authority->cert);
     DBG2(DBG_CFG, "  cacert = %Y", subject);
     enumerator = authority->crl_uris->create_enumerator(authority->crl_uris);
     while (enumerator->enumerate(enumerator, &uri))
     {
         if (first)
         {
             DBG2(DBG_CFG, "  crl_uris = %s", uri);
             first = FALSE;
         }
         else
         {
             DBG2(DBG_CFG, "             %s", uri);
         }
     }
     enumerator->destroy(enumerator);
     first = TRUE;
     enumerator = authority->ocsp_uris->create_enumerator(authority->ocsp_uris);
     while (enumerator->enumerate(enumerator, &uri))
     {
         if (first)
         {
             DBG2(DBG_CFG, "  ocsp_uris = %s", uri);
             first = FALSE;
         }
         else
         {
             DBG2(DBG_CFG, "              %s", uri);
         }
     }
     enumerator->destroy(enumerator);
     if (authority->cert_uri_base)
     {
         DBG2(DBG_CFG, "  cert_uri_base = %s", authority->cert_uri_base);
     }
 }
static void manage_command (private_vici_authority_t * this, char * name, vici_command_cb_t cb, bool reg) static
Definition at line 529 of file vici_authority.c.
Referenced by manage_commands().
 {
     this->dispatcher->manage_command(this->dispatcher, name,
                                      reg ? cb : NULL, this);
 }
static void manage_commands (private_vici_authority_t * this, bool reg) static
(Un-)register dispatcher functions
Definition at line 539 of file vici_authority.c.
References list_authorities(), load_authority(), manage_command(), and unload_authority().
Referenced by METHOD(), and vici_authority_create().
 {
     this->dispatcher->manage_event(this->dispatcher, "list-authority", reg);
     manage_command(this, "load-authority", load_authority, reg);
     manage_command(this, "unload-authority", unload_authority, reg);
     manage_command(this, "get-authorities", get_authorities, reg);
     manage_command(this, "list-authorities", list_authorities, reg);
 }
METHOD (credential_set_t , create_cdp_enumerator , enumerator_t * , private_vici_authority_t * this, certificate_type_t type, identification_t * id)
Definition at line 639 of file vici_authority.c.
References cdp_data_destroy(), CERT_ANY, CERT_X509, CERT_X509_CRL, CERT_X509_OCSP_RESPONSE, create_inner_cdp(), create_inner_cdp_hashandurl(), data, enumerator_create_nested(), id, cdp_data_t::id, lock, malloc_thing, cdp_data_t::this, type, and cdp_data_t::type.
 {
     cdp_data_t *data;
     switch (type)
     {   /* we serve CRLs, OCSP responders and URLs for "Hash and URL" */
         case CERT_X509:
         case CERT_X509_CRL:
         case CERT_X509_OCSP_RESPONSE:
         case CERT_ANY:
             break;
         default:
             return NULL;
     }
     data = malloc_thing(cdp_data_t);
     data->this = this;
     data->type = type;
     data->id = id;
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(
             this->authorities->create_enumerator(this->authorities),
             (type == CERT_X509) ? (void*)create_inner_cdp_hashandurl :
             (void*)create_inner_cdp, data, (void*)cdp_data_destroy);
 }
METHOD (vici_authority_t , check_for_hash_and_url , void , private_vici_authority_t * this, certificate_t * cert)
Definition at line 668 of file vici_authority.c.
References hasher_t::allocate_hash, authority_t::cert, CERT_ASN1_DER, authority_t::cert_uri_base, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_CFG, enumerator_t::destroy, hasher_t::destroy, enumerator_t::enumerate, certificate_t::get_encoding, hash, HASH_SHA1, hasher, authority_t::hashes, ID_KEY_ID, identification_create_from_encoding(), linked_list_t::insert_last, certificate_t::issued_by, lib, lock, and spinlock_t::unlock.
 {
     authority_t *authority;
     enumerator_t *enumerator;
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (hasher == NULL)
     {
         DBG1(DBG_CFG, "unable to use hash-and-url: sha1 not supported");
         return;
     }
     this->lock->write_lock(this->lock);
     enumerator = this->authorities->create_enumerator(this->authorities);
     while (enumerator->enumerate(enumerator, &authority))
     {
         if (authority->cert_uri_base &&
             cert->issued_by(cert, authority->cert, NULL))
         {
             chunk_t hash, encoded;
             if (cert->get_encoding(cert, CERT_ASN1_DER, &encoded))
             {
                 if (hasher->allocate_hash(hasher, encoded, &hash))
                 {
                     authority->hashes->insert_last(authority->hashes,
                         identification_create_from_encoding(ID_KEY_ID, hash));
                     chunk_free(&hash);
                 }
                 chunk_free(&encoded);
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     hasher->destroy(hasher);
 }
METHOD (vici_authority_t , destroy , void , private_vici_authority_t * this)
Definition at line 710 of file vici_authority.c.
References authority_destroy(), spinlock_t::destroy, FALSE, free(), lock, and manage_commands().
 {
     manage_commands(this, FALSE);
     this->authorities->destroy_function(this->authorities,
                                        (void*)authority_destroy);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool parse_rules (parse_rule_t * rules, int count, char * name, chunk_t value, vici_message_t ** reply) static
Parse key/values using a rule-set
Definition at line 166 of file vici_authority.c.
References count, create_reply(), FALSE, out, parse(), streq(), and TRUE.
Referenced by CALLBACK().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         if (streq(name, rules[i].name))
         {
             if (rules[i].parse(rules[i].out, value))
             {
                 return TRUE;
             }
             *reply = create_reply("invalid value for: %s, authority discarded",
                                   name);
             return FALSE;
         }
     }
     *reply = create_reply("unknown option: %s, authority discarded", name);
     return FALSE;
 }