strongSwan: ietf_attr_installed_packages
ietf_attr_installed_packages
ietf_attr
Classes
struct ietf_attr_installed_packages_t
Macros
#define IETF_INSTALLED_PACKAGES_MIN_SIZE 4
Typedefs
typedef struct
ietf_attr_installed_packages_t ietf_attr_installed_packages_t
Functions
pa_tnc_attr_t * ietf_attr_installed_packages_create (void)
pa_tnc_attr_t * ietf_attr_installed_packages_create_from_data (size_t length, chunk_t value)
Detailed Description
Macro Definition Documentation
#define IETF_INSTALLED_PACKAGES_MIN_SIZE 4
Definition at line 29 of file ietf_attr_installed_packages.h.
Referenced by METHOD().
Typedef Documentation
typedef struct ietf_attr_installed_packages_t ietf_attr_installed_packages_t
Definition at line 24 of file ietf_attr_installed_packages.h.
Function Documentation
pa_tnc_attr_t* ietf_attr_installed_packages_create (void)
Creates an ietf_attr_installed_packages_t object
Described in header.
Definition at line 333 of file ietf_attr_installed_packages.c.
References IETF_ATTR_INSTALLED_PACKAGES, INIT, linked_list_create(), and PEN_IETF.
Referenced by add_installed_packages().
 {
     private_ietf_attr_installed_packages_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add = _add,
             .create_enumerator = _create_enumerator,
             .get_count = _get_count,
             .clear_packages = _clear_packages,
         },
         .type = { PEN_IETF, IETF_ATTR_INSTALLED_PACKAGES },
         .packages = linked_list_create(),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ietf_attr_installed_packages_create_from_data (size_t length, chunk_t data)
Creates an ietf_attr_installed_packages_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header. .length = length,
Definition at line 367 of file ietf_attr_installed_packages.c.
References chunk_clone, IETF_ATTR_INSTALLED_PACKAGES, INIT, length, linked_list_create(), PEN_IETF, segment, and value.
Referenced by ietf_attr_create_from_data().
 {
     private_ietf_attr_installed_packages_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add = _add,
             .create_enumerator = _create_enumerator,
             .get_count = _get_count,
             .clear_packages = _clear_packages,
         },
         .type = {PEN_IETF, IETF_ATTR_INSTALLED_PACKAGES },
         .length = length,
         .segment = chunk_clone(data),
         .packages = linked_list_create(),
         .ref = 1,
     );
     /* received either complete attribute value or first segment */
     this->value = this->segment;
     return &this->public.pa_tnc_attribute;
 }