strongSwan: main.c File Reference
manager/main.c File Reference
#include <fast_dispatcher.h>
#include <utils/debug.h>
#include <stdio.h>
#include "manager.h"
#include "storage.h"
#include "controller/auth_controller.h"
#include "controller/ikesa_controller.h"
#include "controller/gateway_controller.h"
#include "controller/control_controller.h"
#include "controller/config_controller.h"
Functions
int main (int arc, char *argv[])
Function Documentation
int main (int arc, char * argv[])
Definition at line 28 of file manager/main.c.
References fast_dispatcher_t::add_controller, auth_controller_create(), config_controller_create(), control_controller_create(), DBG1, DBG_LIB, storage_t::destroy, fast_dispatcher_t::destroy, FALSE, fast_dispatcher_create(), gateway_controller_create(), settings_t::get_bool, settings_t::get_int, settings_t::get_str, settings_t::get_time, ikesa_controller_create(), lib, library_deinit(), library_init(), plugin_loader_t::load, manager_create(), PLUGINS, library_t::plugins, fast_dispatcher_t::run, library_t::settings, socket, storage_create(), threads, and fast_dispatcher_t::waitsignal.
 {
     fast_dispatcher_t *dispatcher;
     storage_t *storage;
     char *socket;
     char *database;
     bool debug;
     int threads, timeout;
     library_init(NULL, "manager");
     if (!lib->plugins->load(lib->plugins,
             lib->settings->get_str(lib->settings, "manager.load", PLUGINS)))
     {
         return 1;
     }
     socket = lib->settings->get_str(lib->settings, "manager.socket", NULL);
     debug = lib->settings->get_bool(lib->settings, "manager.debug", FALSE);
     timeout = lib->settings->get_time(lib->settings, "manager.timeout", 900);
     threads = lib->settings->get_int(lib->settings, "manager.threads", 10);
     database = lib->settings->get_str(lib->settings, "manager.database", NULL);
     if (!database)
     {
         DBG1(DBG_LIB, "database URI undefined, set manager.database "
              "in strongswan.conf");
         //return 1;
     }
     storage = storage_create(database);
     if (storage == NULL)
     {
         return 1;
     }
     dispatcher = fast_dispatcher_create(socket, debug, timeout,
                         (fast_context_constructor_t)manager_create, storage);
     dispatcher->add_controller(dispatcher, ikesa_controller_create, NULL);
     dispatcher->add_controller(dispatcher, gateway_controller_create, NULL);
     dispatcher->add_controller(dispatcher, auth_controller_create, NULL);
     dispatcher->add_controller(dispatcher, control_controller_create, NULL);
     dispatcher->add_controller(dispatcher, config_controller_create, NULL);
     dispatcher->run(dispatcher, threads);
     dispatcher->waitsignal(dispatcher);
     dispatcher->destroy(dispatcher);
     storage->destroy(storage);
     library_deinit();
     return 0;
 }