strongSwan: pt_tls.c File Reference
pt_tls.c File Reference
#include "pt_tls.h"
#include <utils/debug.h>
#include <pen/pen.h>
Functions
void libpttls_init (void)
ENUM (pt_tls_message_type_names, PT_TLS_EXPERIMENTAL, PT_TLS_ERROR,"Experimental","Version Request","Version Response","SASL Mechanisms","SASL Mechanism Selection","SASL Authentication Data","SASL Result","PB-TNC Batch","PT-TLS Error")
ENUM (pt_tls_sasl_result_names, PT_TLS_SASL_RESULT_SUCCESS, PT_TLS_SASL_RESULT_MECH_FAILURE,"Success","Failure","Abort","Mechanism Failure")
static bio_reader_t * read_tls (tls_socket_t *tls, size_t len)
bio_reader_t * pt_tls_read (tls_socket_t *tls, u_int32_t *vendor, u_int32_t *type, u_int32_t *identifier)
bool pt_tls_write (tls_socket_t *tls, pt_tls_message_type_t type, u_int32_t identifier, chunk_t data)
Function Documentation
ENUM (pt_tls_message_type_names , PT_TLS_EXPERIMENTAL , PT_TLS_ERROR , "Experimental" , "Version Request" , "Version Response" , "SASL Mechanisms" , "SASL Mechanism Selection" , "SASL Authentication Data" , "SASL Result" , "PB-TNC Batch" , "PT-TLS Error")
ENUM (pt_tls_sasl_result_names , PT_TLS_SASL_RESULT_SUCCESS , PT_TLS_SASL_RESULT_MECH_FAILURE , "Success" , "Failure" , "Abort" , "Mechanism Failure")
static bio_reader_t* read_tls (tls_socket_t * tls, size_t len) static
Read a chunk of data from TLS, returning a reader for it
Definition at line 68 of file pt_tls.c.
References bio_reader_create_own(), chunk_create(), free(), malloc(), tls_socket_t::read, and TRUE.
Referenced by pt_tls_read().
 {
     ssize_t got, total = 0;
     char *buf;
     buf = malloc(len);
     while (total < len)
     {
         got = tls->read(tls, buf + total, len - total, TRUE);
         if (got <= 0)
         {
             free(buf);
             return NULL;
         }
         total += got;
     }
     return bio_reader_create_own(chunk_create(buf, len));
 }