strongSwan: simaka_crypto.c File Reference
simaka_crypto.c File Reference
#include "simaka_crypto.h"
#include "simaka_manager.h"
#include <utils/debug.h>
Classes
struct private_simaka_crypto_t
Macros
#define KENCR_LEN 16
#define KAUTH_LEN 16
#define MSK_LEN 64
#define EMSK_LEN 64
Typedefs
typedef struct
private_simaka_crypto_t private_simaka_crypto_t
Functions
METHOD (simaka_crypto_t, get_signer, signer_t *, private_simaka_crypto_t *this)
METHOD (simaka_crypto_t, get_crypter, crypter_t *, private_simaka_crypto_t *this)
METHOD (simaka_crypto_t, get_rng, rng_t *, private_simaka_crypto_t *this)
static void call_hook (private_simaka_crypto_t *this, chunk_t encr, chunk_t auth)
METHOD (simaka_crypto_t, derive_keys_full, bool, private_simaka_crypto_t *this, identification_t *id, chunk_t data, chunk_t *mk, chunk_t *msk)
METHOD (simaka_crypto_t, derive_keys_reauth, bool, private_simaka_crypto_t *this, chunk_t mk)
METHOD (simaka_crypto_t, derive_keys_reauth_msk, bool, private_simaka_crypto_t *this, identification_t *id, chunk_t counter, chunk_t nonce_s, chunk_t mk, chunk_t *msk)
METHOD (simaka_crypto_t, clear_keys, void, private_simaka_crypto_t *this)
METHOD (simaka_crypto_t, destroy, void, private_simaka_crypto_t *this)
simaka_crypto_t * simaka_crypto_create (eap_type_t type)
Macro Definition Documentation
#define EMSK_LEN 64
length of the EMSK
Definition at line 29 of file simaka_crypto.c.
#define KAUTH_LEN 16
length of the k_auth key
Definition at line 25 of file simaka_crypto.c.
Referenced by METHOD().
#define KENCR_LEN 16
length of the k_encr key
Definition at line 23 of file simaka_crypto.c.
Referenced by METHOD().
#define MSK_LEN 64
length of the MSK
Definition at line 27 of file simaka_crypto.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_simaka_crypto_t private_simaka_crypto_t
Definition at line 31 of file simaka_crypto.c.
Function Documentation
static void call_hook (private_simaka_crypto_t * this, chunk_t encr, chunk_t auth) static
Call SIM/AKA key hook
Definition at line 100 of file simaka_crypto.c.
References EAP_AKA, EAP_SIM, library_t::get, simaka_manager_t::key_hook, lib, and type.
Referenced by check_lifetime(), METHOD(), and verify_trust_chain().
 {
     simaka_manager_t *mgr;
     switch (this->type)
     {
         case EAP_SIM:
             mgr = lib->get(lib, "sim-manager");
             break;
         case EAP_AKA:
             mgr = lib->get(lib, "aka-manager");
             break;
         default:
             return;
     }
     mgr->key_hook(mgr, encr, auth);
 }
METHOD (simaka_crypto_t , get_signer , signer_t * , private_simaka_crypto_t * this)
Definition at line 79 of file simaka_crypto.c.
References signer.
 {
     return this->derived ? this->signer : NULL;
 }
METHOD (simaka_crypto_t , get_crypter , crypter_t * , private_simaka_crypto_t * this)
Definition at line 85 of file simaka_crypto.c.
References crypter.
 {
     return this->derived ? this->crypter : NULL;
 }
METHOD (simaka_crypto_t , get_rng , rng_t * , private_simaka_crypto_t * this)
Definition at line 91 of file simaka_crypto.c.
References rng.
 {
     return this->rng;
 }
METHOD (simaka_crypto_t , derive_keys_full , bool , private_simaka_crypto_t * this, identification_t * id, chunk_t data, chunk_t * mk, chunk_t * msk)
Definition at line 118 of file simaka_crypto.c.
References call_hook(), chunk_alloca, chunk_clear(), chunk_clone, chunk_create(), chunk_empty, crypter, DBG3, DBG_LIB, FALSE, identification_t::get_encoding, hasher, KAUTH_LEN, KENCR_LEN, chunk_t::len, MSK_LEN, prf, chunk_t::ptr, signer, str, and TRUE.
 {
     chunk_t str, k_encr, k_auth;
     int i;
     /* For SIM: MK = SHA1(Identity|n*Kc|NONCE_MT|Version List|Selected Version)
      * For AKA: MK = SHA1(Identity|IK|CK) */
     if (!this->hasher->get_hash(this->hasher, id->get_encoding(id), NULL) ||
         !this->hasher->allocate_hash(this->hasher, data, mk))
     {
         return FALSE;
     }
     DBG3(DBG_LIB, "MK %B", mk);
     /* K_encr | K_auth | MSK | EMSK = prf() | prf() | prf() | prf() */
     if (!this->prf->set_key(this->prf, *mk))
     {
         chunk_clear(mk);
         return FALSE;
     }
     str = chunk_alloca(this->prf->get_block_size(this->prf) * 3);
     for (i = 0; i < 3; i++)
     {
         if (!this->prf->get_bytes(this->prf, chunk_empty,
                                   str.ptr + str.len / 3 * i))
         {
             chunk_clear(mk);
             return FALSE;
         }
     }
     k_encr = chunk_create(str.ptr, KENCR_LEN);
     k_auth = chunk_create(str.ptr + KENCR_LEN, KAUTH_LEN);
     if (!this->signer->set_key(this->signer, k_auth) ||
         !this->crypter->set_key(this->crypter, k_encr))
     {
         chunk_clear(mk);
         return FALSE;
     }
     *msk = chunk_clone(chunk_create(str.ptr + KENCR_LEN + KAUTH_LEN, MSK_LEN));
     DBG3(DBG_LIB, "K_encr %B\nK_auth %B\nMSK %B", &k_encr, &k_auth, msk);
     call_hook(this, k_encr, k_auth);
     this->derived = TRUE;
     return TRUE;
 }
METHOD (simaka_crypto_t , derive_keys_reauth , bool , private_simaka_crypto_t * this, chunk_t mk)
Definition at line 170 of file simaka_crypto.c.
References call_hook(), chunk_alloca, chunk_create(), chunk_empty, crypter, DBG3, DBG_LIB, FALSE, KAUTH_LEN, KENCR_LEN, chunk_t::len, prf, chunk_t::ptr, signer, str, and TRUE.
 {
     chunk_t str, k_encr, k_auth;
     int i;
     /* K_encr | K_auth = prf() | prf() */
     if (!this->prf->set_key(this->prf, mk))
     {
         return FALSE;
     }
     str = chunk_alloca(this->prf->get_block_size(this->prf) * 2);
     for (i = 0; i < 2; i++)
     {
         if (!this->prf->get_bytes(this->prf, chunk_empty,
                                   str.ptr + str.len / 2 * i))
         {
             return FALSE;
         }
     }
     k_encr = chunk_create(str.ptr, KENCR_LEN);
     k_auth = chunk_create(str.ptr + KENCR_LEN, KAUTH_LEN);
     DBG3(DBG_LIB, "K_encr %B\nK_auth %B", &k_encr, &k_auth);
     if (!this->signer->set_key(this->signer, k_auth) ||
         !this->crypter->set_key(this->crypter, k_encr))
     {
         return FALSE;
     }
     call_hook(this, k_encr, k_auth);
     this->derived = TRUE;
     return TRUE;
 }
METHOD (simaka_crypto_t , derive_keys_reauth_msk , bool , private_simaka_crypto_t * this, identification_t * id, chunk_t counter, chunk_t nonce_s, chunk_t mk, chunk_t * msk)
Definition at line 206 of file simaka_crypto.c.
References chunk_alloca, chunk_clone, chunk_create(), chunk_empty, DBG3, DBG_LIB, FALSE, identification_t::get_encoding, HASH_SIZE_SHA1, hasher, chunk_t::len, MSK_LEN, prf, chunk_t::ptr, str, and TRUE.
 {
     char xkey[HASH_SIZE_SHA1];
     chunk_t str;
     int i;
     if (!this->hasher->get_hash(this->hasher, id->get_encoding(id), NULL) ||
         !this->hasher->get_hash(this->hasher, counter, NULL) ||
         !this->hasher->get_hash(this->hasher, nonce_s, NULL) ||
         !this->hasher->get_hash(this->hasher, mk, xkey))
     {
         return FALSE;
     }
     /* MSK | EMSK = prf() | prf() | prf() | prf() */
     if (!this->prf->set_key(this->prf, chunk_create(xkey, sizeof(xkey))))
     {
         return FALSE;
     }
     str = chunk_alloca(this->prf->get_block_size(this->prf) * 2);
     for (i = 0; i < 2; i++)
     {
         if (!this->prf->get_bytes(this->prf, chunk_empty,
                                   str.ptr + str.len / 2 * i))
         {
             return FALSE;
         }
     }
     *msk = chunk_clone(chunk_create(str.ptr, MSK_LEN));
     DBG3(DBG_LIB, "MSK %B", msk);
     return TRUE;
 }
METHOD (simaka_crypto_t , clear_keys , void , private_simaka_crypto_t * this)
Definition at line 242 of file simaka_crypto.c.
References FALSE.
 {
     this->derived = FALSE;
 }
METHOD (simaka_crypto_t , destroy , void , private_simaka_crypto_t * this)
Definition at line 248 of file simaka_crypto.c.
References crypter, DESTROY_IF, free(), hasher, prf, rng, and signer.
 {
     DESTROY_IF(this->rng);
     DESTROY_IF(this->hasher);
     DESTROY_IF(this->prf);
     DESTROY_IF(this->signer);
     DESTROY_IF(this->crypter);
     free(this);
 }
simaka_crypto_t* simaka_crypto_create (eap_type_t type)
See header
Definition at line 262 of file simaka_crypto.c.
References AUTH_HMAC_SHA1_128, crypto_factory_t::create_crypter, crypto_factory_t::create_hasher, crypto_factory_t::create_prf, crypto_factory_t::create_rng, crypto_factory_t::create_signer, crypter, library_t::crypto, DBG1, DBG_LIB, destroy(), eap_type_names, ENCR_AES_CBC, HASH_SHA1, hasher, INIT, lib, prf, PRF_FIPS_SHA1_160, rng, RNG_WEAK, signer, and type.
Referenced by eap_aka_peer_create(), eap_aka_server_create(), eap_sim_peer_create(), and eap_sim_server_create().
 {
     private_simaka_crypto_t *this;
     INIT(this,
         .public = {
             .get_signer = _get_signer,
             .get_crypter = _get_crypter,
             .get_rng = _get_rng,
             .derive_keys_full = _derive_keys_full,
             .derive_keys_reauth = _derive_keys_reauth,
             .derive_keys_reauth_msk = _derive_keys_reauth_msk,
             .clear_keys = _clear_keys,
             .destroy = _destroy,
         },
         .type = type,
         .rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK),
         .hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1),
         .prf = lib->crypto->create_prf(lib->crypto, PRF_FIPS_SHA1_160),
         .signer = lib->crypto->create_signer(lib->crypto, AUTH_HMAC_SHA1_128),
         .crypter = lib->crypto->create_crypter(lib->crypto, ENCR_AES_CBC, 16),
     );
     if (!this->rng || !this->hasher || !this->prf ||
         !this->signer || !this->crypter)
     {
         DBG1(DBG_LIB, "unable to use %N, missing algorithms",
              eap_type_names, type);
         destroy(this);
         return NULL;
     }
     return &this->public;
 }