strongSwan: tkm_public_key.c File Reference
tkm_public_key.c File Reference
#include <utils/debug.h>
#include "tkm_public_key.h"
Classes
struct private_tkm_public_key_t
Typedefs
typedef struct
private_tkm_public_key_t private_tkm_public_key_t
Functions
METHOD (public_key_t, get_type, key_type_t, private_tkm_public_key_t *this)
METHOD (public_key_t, verify, bool, private_tkm_public_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
METHOD (public_key_t, encrypt_, bool, private_tkm_public_key_t *this, encryption_scheme_t scheme, chunk_t plain, chunk_t *crypto)
METHOD (public_key_t, get_keysize, int, private_tkm_public_key_t *this)
METHOD (public_key_t, get_encoding, bool, private_tkm_public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (public_key_t, get_fingerprint, bool, private_tkm_public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (public_key_t, get_ref, public_key_t *, private_tkm_public_key_t *this)
METHOD (public_key_t, destroy, void, private_tkm_public_key_t *this)
tkm_public_key_t * tkm_public_key_load (key_type_t type, va_list args)
Typedef Documentation
typedef struct private_tkm_public_key_t private_tkm_public_key_t
Definition at line 21 of file tkm_public_key.c.
Function Documentation
METHOD (public_key_t , get_type , key_type_t , private_tkm_public_key_t * this)
Definition at line 49 of file tkm_public_key.c.
References key_type.
 {
     return this->key_type;
 }
METHOD (public_key_t , verify , bool , private_tkm_public_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
Definition at line 55 of file tkm_public_key.c.
References TRUE.
 {
     return TRUE;
 }
METHOD (public_key_t , encrypt_ , bool , private_tkm_public_key_t * this, encryption_scheme_t scheme, chunk_t plain, chunk_t * crypto)
Definition at line 62 of file tkm_public_key.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (public_key_t , get_keysize , int , private_tkm_public_key_t * this)
Definition at line 69 of file tkm_public_key.c.
 {
     return 0;
 }
METHOD (public_key_t , get_encoding , bool , private_tkm_public_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 75 of file tkm_public_key.c.
 {
     return NULL;
 }
METHOD (public_key_t , get_fingerprint , bool , private_tkm_public_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 82 of file tkm_public_key.c.
References CRED_PART_END, CRED_PART_RSA_PUB_ASN1_DER, DBG1, DBG_LIB, cred_encoding_t::encode, library_t::encoding, FALSE, cred_encoding_t::get_cache, KEY_RSA, key_type, key_type_names, lib, and TRUE.
 {
     if (lib->encoding->get_cache(lib->encoding, type, this, fp))
     {
         return TRUE;
     }
     switch(this->key_type)
     {
         case KEY_RSA:
             return lib->encoding->encode(lib->encoding, type, this, fp,
                                          CRED_PART_RSA_PUB_ASN1_DER,
                                          this->asn_blob, CRED_PART_END);
         default:
             DBG1(DBG_LIB, "%N public key not supported, fingerprinting failed",
                  key_type_names, this->key_type);
             return FALSE;
     }
 }
METHOD (public_key_t , get_ref , public_key_t * , private_tkm_public_key_t * this)
Definition at line 102 of file tkm_public_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (public_key_t , destroy , void , private_tkm_public_key_t * this)
Definition at line 109 of file tkm_public_key.c.
References chunk_free(), cred_encoding_t::clear_cache, library_t::encoding, free(), lib, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         lib->encoding->clear_cache(lib->encoding, this);
         chunk_free(&this->asn_blob);
         free(this);
     }
 }