strongSwan: eap_mschapv2
eap_mschapv2
eap_mschapv2
Classes
struct eap_mschapv2_t
Typedefs
typedef struct eap_mschapv2_t eap_mschapv2_t
Functions
eap_mschapv2_t * eap_mschapv2_create_server (identification_t *server, identification_t *peer)
eap_mschapv2_t * eap_mschapv2_create_peer (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_mschapv2_t eap_mschapv2_t
Definition at line 24 of file eap_mschapv2.h.
Function Documentation
eap_mschapv2_t* eap_mschapv2_create_peer (identification_t * server, identification_t * peer)
Creates the EAP method EAP-MS-CHAPv2 acting as peer.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_mschapv2_t object
Definition at line 1322 of file eap_mschapv2.c.
References eap_mschapv2_create_generic().
Referenced by METHOD().
 {
     private_eap_mschapv2_t *this = eap_mschapv2_create_generic(server, peer);
     this->public.eap_method_interface.initiate = _initiate_peer;
     this->public.eap_method_interface.process = _process_peer;
     return &this->public;
 }
eap_mschapv2_t* eap_mschapv2_create_server (identification_t * server, identification_t * peer)
Creates the EAP method EAP-MS-CHAPv2 acting as server.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_mschapv2_t object
Definition at line 1301 of file eap_mschapv2.c.
References eap_mschapv2_create_generic(), identifier, and random.
Referenced by METHOD().
 {
     private_eap_mschapv2_t *this = eap_mschapv2_create_generic(server, peer);
     this->public.eap_method_interface.initiate = _initiate_server;
     this->public.eap_method_interface.process = _process_server;
     /* generate a non-zero identifier */
     do
     {
         this->identifier = random();
     } while (!this->identifier);
     this->mschapv2id = this->identifier;
     return &this->public;
 }