strongSwan: resolver_response_t Struct Reference
resolver_response_t Struct Reference
resolver_response
#include "resolver_response.h"
Public Attributes
char *(* get_query_name)(resolver_response_t *this)
char *(* get_canon_name)(resolver_response_t *this)
bool(* has_data)(resolver_response_t *this)
bool(* query_name_exist)(resolver_response_t *this)
dnssec_status_t(* get_security_state)(resolver_response_t *this)
rr_set_t *(* get_rr_set)(resolver_response_t *this)
void(* destroy)(resolver_response_t *this)
Detailed Description
A response of the DNS resolver to a DNS query.
A response represents the answer of the Domain Name System to a query. It contains the RRset with the queried Resource Records and additional information.
Definition at line 77 of file resolver_response.h.
Member Data Documentation
void(* resolver_response_t::destroy)(resolver_response_t *this)
Destroy this response.
Definition at line 140 of file resolver_response.h.
Referenced by main(), and METHOD().
char*(* resolver_response_t::get_canon_name)(resolver_response_t *this)
Get the canonical name of the result.
The string to which the returned pointer points, is still owned by the resolver_response. Clone it if necessary.
Returns
- canonical name of result
NULL, if result has no canonical name
Definition at line 98 of file resolver_response.h.
char*(* resolver_response_t::get_query_name)(resolver_response_t *this)
Get the original question string.
The string to which the returned pointer points, is still owned by the resolver_response. Clone it if necessary.
Returns
the queried name
Definition at line 87 of file resolver_response.h.
rr_set_t*(* resolver_response_t::get_rr_set)(resolver_response_t *this)
Get the RRset with all Resource Records of this response.
Returns
- RRset
NULL if there is no data or the query name does not exist
Definition at line 135 of file resolver_response.h.
Referenced by main(), and METHOD().
dnssec_status_t(* resolver_response_t::get_security_state)(resolver_response_t *this)
Get the DNSSEC security state of the response.
Returns
DNSSEC security state
Definition at line 126 of file resolver_response.h.
Referenced by main(), and METHOD().
bool(* resolver_response_t::has_data)(resolver_response_t *this)
Does the RRset of this response contain some Resource Records?
Returns TRUE if the RRset of this response contains some RRs (RRSIG Resource Records are ignored).
Returns
TRUE, if there are some RRs in the RRset
FALSE, otherwise
Definition at line 110 of file resolver_response.h.
Referenced by main(), and METHOD().
bool(* resolver_response_t::query_name_exist)(resolver_response_t *this)
Does the queried name exist?
Returns
TRUE, if the queried name exists
FALSE, otherwise
Definition at line 119 of file resolver_response.h.
Referenced by main(), and METHOD().
The documentation for this struct was generated from the following file:
resolver_response.h