strongSwan: pts_comp_evidence
pts_comp_evidence
pts
Classes
struct pts_comp_evidence_t
Typedefs
typedef struct pts_comp_evidence_t pts_comp_evidence_t
typedef enum pts_pcr_transform_t pts_pcr_transform_t
typedef enum
pts_comp_evid_validation_t pts_comp_evid_validation_t
Enumerations
enum pts_pcr_transform_t { PTS_PCR_TRANSFORM_NO = 0, PTS_PCR_TRANSFORM_MATCH = 1, PTS_PCR_TRANSFORM_SHORT = 2, PTS_PCR_TRANSFORM_LONG = 3 }
enum pts_comp_evid_validation_t { PTS_COMP_EVID_VALIDATION_NONE = 0x00, PTS_COMP_EVID_VALIDATION_UNABLE = 0x20, PTS_COMP_EVID_VALIDATION_FAILED = 0x40, PTS_COMP_EVID_VALIDATION_PASSED = 0x60 }
Functions
pts_comp_evidence_t * pts_comp_evidence_create (pts_comp_func_name_t *name, u_int32_t depth, u_int32_t extended_pcr, pts_meas_algorithms_t algo, pts_pcr_transform_t transform, time_t measurement_time, chunk_t measurement)
pts_pcr_transform_t pts_meas_algo_to_pcr_transform (pts_meas_algorithms_t algo, size_t pcr_len)
Detailed Description
Typedef Documentation
typedef enum pts_comp_evid_validation_t pts_comp_evid_validation_t
Definition at line 26 of file pts_comp_evidence.h.
typedef struct pts_comp_evidence_t pts_comp_evidence_t
Definition at line 24 of file pts_comp_evidence.h.
typedef enum pts_pcr_transform_t pts_pcr_transform_t
Definition at line 25 of file pts_comp_evidence.h.
Enumeration Type Documentation
enum pts_comp_evid_validation_t
PTS Component Evidence Validation Result Flags
Enumerator
PTS_COMP_EVID_VALIDATION_NONE
No Validation was attempted
PTS_COMP_EVID_VALIDATION_UNABLE
Attempted validation, unable to verify
PTS_COMP_EVID_VALIDATION_FAILED
Attempted validation, verification failed
PTS_COMP_EVID_VALIDATION_PASSED
Attempted validation, verification passed
Definition at line 50 of file pts_comp_evidence.h.
{
     PTS_COMP_EVID_VALIDATION_NONE =     0x00,
     PTS_COMP_EVID_VALIDATION_UNABLE =   0x20,
     PTS_COMP_EVID_VALIDATION_FAILED =   0x40,
     PTS_COMP_EVID_VALIDATION_PASSED =   0x60,
 };
enum pts_pcr_transform_t
PTS PCR Transformations
Enumerator
PTS_PCR_TRANSFORM_NO
No Transformation
PTS_PCR_TRANSFORM_MATCH
Hash Value matched PCR size
PTS_PCR_TRANSFORM_SHORT
Hash value shorter than PCR size
PTS_PCR_TRANSFORM_LONG
Hash value longer than PCR size
Definition at line 36 of file pts_comp_evidence.h.
{
     PTS_PCR_TRANSFORM_NO =      0,
     PTS_PCR_TRANSFORM_MATCH =   1,
     PTS_PCR_TRANSFORM_SHORT =   2,
     PTS_PCR_TRANSFORM_LONG =    3,
 };
Function Documentation
pts_comp_evidence_t* pts_comp_evidence_create (pts_comp_func_name_t * name, u_int32_t depth, u_int32_t extended_pcr, pts_meas_algorithms_t algo, pts_pcr_transform_t transform, time_t measurement_time, chunk_t measurement)
Creates a pts_comp_evidence_t object
Parameters
name Component Functional Name
depth Sub-component depth
extended_pcr PCR the measurement was extended into
algo Measurement hash algorithm
transform Transformation used for PCR extension
measurement_time Time the measurement was taken, 0 if unknown
measurement Measurement hash value
See header
Definition at line 195 of file pts_comp_evidence.c.
References DBG3, DBG_PTS, FALSE, INIT, pts_comp_func_name_t::log, and name.
Referenced by extend_pcr(), and METHOD().
 {
     private_pts_comp_evidence_t *this;
     INIT(this,
         .public = {
             .get_comp_func_name = _get_comp_func_name,
             .get_extended_pcr = _get_extended_pcr,
             .get_measurement = _get_measurement,
             .get_pcr_info = _get_pcr_info,
             .set_pcr_info = _set_pcr_info,
             .get_validation = _get_validation,
             .set_validation = _set_validation,
             .destroy = _destroy,
         },
         .name = name,
         .depth = depth,
         .extended_pcr = extended_pcr,
         .hash_algorithm = algo,
         .transform = transform,
         .measurement_time = measurement_time,
         .measurement = measurement,
     );
     name->log(name, "");
     DBG3(DBG_PTS, "measurement time: %T", &measurement_time, FALSE);
     DBG3(DBG_PTS, "PCR %2d extended with: %#B", extended_pcr, &measurement);
     return &this->public;
 }
pts_pcr_transform_t pts_meas_algo_to_pcr_transform (pts_meas_algorithms_t algo, size_t pcr_len)
Determine transform to fit measurement hash into PCR register
Parameters
algo Measurement hash algorithm
pcr_len Length of the PCR registers in bytes
Returns
PCR transform type
See header
Definition at line 235 of file pts_comp_evidence.c.
References pts_meas_algo_hash_size(), PTS_PCR_TRANSFORM_LONG, PTS_PCR_TRANSFORM_MATCH, PTS_PCR_TRANSFORM_NO, and PTS_PCR_TRANSFORM_SHORT.
Referenced by extend_pcr(), and METHOD().
 {
     size_t hash_size;
     hash_size = pts_meas_algo_hash_size(algo);
     if (hash_size == 0)
     {
         return PTS_PCR_TRANSFORM_NO;
     }
     if (hash_size == pcr_len)
     {
         return PTS_PCR_TRANSFORM_MATCH;
     }
     if (hash_size > pcr_len)
     {
         return PTS_PCR_TRANSFORM_LONG;
     }
     return PTS_PCR_TRANSFORM_SHORT;
 }