strongSwan: gcrypt_crypter.c File Reference
gcrypt_crypter.c File Reference
#include "gcrypt_crypter.h"
#include <gcrypt.h>
#include <utils/debug.h>
Classes
struct private_gcrypt_crypter_t
Typedefs
typedef struct
private_gcrypt_crypter_t private_gcrypt_crypter_t
Functions
static bool set_iv (private_gcrypt_crypter_t *this, chunk_t iv)
METHOD (crypter_t, decrypt, bool, private_gcrypt_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *dst)
METHOD (crypter_t, encrypt, bool, private_gcrypt_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *dst)
METHOD (crypter_t, get_block_size, size_t, private_gcrypt_crypter_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_gcrypt_crypter_t *this)
METHOD (crypter_t, get_key_size, size_t, private_gcrypt_crypter_t *this)
METHOD (crypter_t, set_key, bool, private_gcrypt_crypter_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_gcrypt_crypter_t *this)
gcrypt_crypter_t * gcrypt_crypter_create (encryption_algorithm_t algo, size_t key_size)
Typedef Documentation
typedef struct private_gcrypt_crypter_t private_gcrypt_crypter_t
Definition at line 22 of file gcrypt_crypter.c.
Function Documentation
METHOD (crypter_t , decrypt , bool , private_gcrypt_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * dst)
Definition at line 73 of file gcrypt_crypter.c.
References chunk_alloc, FALSE, private_gcrypt_crypter_t::h, chunk_t::len, chunk_t::ptr, and set_iv().
 {
     if (!set_iv(this, iv))
     {
         return FALSE;
     }
     if (dst)
     {
         *dst = chunk_alloc(data.len);
         return gcry_cipher_decrypt(this->h, dst->ptr, dst->len,
                                    data.ptr, data.len) == 0;
     }
     return gcry_cipher_decrypt(this->h, data.ptr, data.len, NULL, 0) == 0;
 }
METHOD (crypter_t , encrypt , bool , private_gcrypt_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * dst)
Definition at line 89 of file gcrypt_crypter.c.
References chunk_alloc, FALSE, private_gcrypt_crypter_t::h, chunk_t::len, chunk_t::ptr, and set_iv().
 {
     if (!set_iv(this, iv))
     {
         return FALSE;
     }
     if (dst)
     {
         *dst = chunk_alloc(data.len);
         return gcry_cipher_encrypt(this->h, dst->ptr, dst->len,
                                    data.ptr, data.len) == 0;
     }
     return gcry_cipher_encrypt(this->h, data.ptr, data.len, NULL, 0) == 0;
 }
METHOD (crypter_t , get_block_size , size_t , private_gcrypt_crypter_t * this)
Definition at line 105 of file gcrypt_crypter.c.
References private_gcrypt_crypter_t::alg, private_gcrypt_crypter_t::ctr_mode, and len.
 {
     size_t len = 0;
     if (this->ctr_mode)
     {   /* counter mode does not need any padding */
         return 1;
     }
     gcry_cipher_algo_info(this->alg, GCRYCTL_GET_BLKLEN, NULL, &len);
     return len;
 }
METHOD (crypter_t , get_iv_size , size_t , private_gcrypt_crypter_t * this)
Definition at line 118 of file gcrypt_crypter.c.
References private_gcrypt_crypter_t::alg, private_gcrypt_crypter_t::ctr_mode, and len.
 {
     size_t len = 0;
     if (this->ctr_mode)
     {
         return sizeof(this->ctr.iv);
     }
     gcry_cipher_algo_info(this->alg, GCRYCTL_GET_BLKLEN, NULL, &len);
     return len;
 }
METHOD (crypter_t , get_key_size , size_t , private_gcrypt_crypter_t * this)
Definition at line 131 of file gcrypt_crypter.c.
References private_gcrypt_crypter_t::alg, private_gcrypt_crypter_t::ctr_mode, and len.
 {
     size_t len = 0;
     gcry_cipher_algo_info(this->alg, GCRYCTL_GET_KEYLEN, NULL, &len);
     if (this->ctr_mode)
     {
         return len + sizeof(this->ctr.nonce);
     }
     return len;
 }
METHOD (crypter_t , set_key , bool , private_gcrypt_crypter_t * this, chunk_t key)
Definition at line 144 of file gcrypt_crypter.c.
References private_gcrypt_crypter_t::ctr_mode, private_gcrypt_crypter_t::h, chunk_t::len, memcpy, and chunk_t::ptr.
 {
     if (this->ctr_mode)
     {
         /* last 4 bytes are the nonce */
         memcpy(this->ctr.nonce, key.ptr + key.len - sizeof(this->ctr.nonce),
                sizeof(this->ctr.nonce));
         key.len -= sizeof(this->ctr.nonce);
     }
     return gcry_cipher_setkey(this->h, key.ptr, key.len) == 0;
 }
METHOD (crypter_t , destroy , void , private_gcrypt_crypter_t * this)
Definition at line 157 of file gcrypt_crypter.c.
References free(), and private_gcrypt_crypter_t::h.
 {
     gcry_cipher_close(this->h);
     free(this);
 }
static bool set_iv (private_gcrypt_crypter_t * this, chunk_t iv) static
Set the IV for en/decryption
Definition at line 62 of file gcrypt_crypter.c.
References private_gcrypt_crypter_t::ctr_mode, private_gcrypt_crypter_t::h, and memcpy.
Referenced by METHOD().
 {
     if (this->ctr_mode)
     {
         memcpy(this->ctr.iv, iv.ptr, sizeof(this->ctr.iv));
         this->ctr.counter = htonl(1);
         return gcry_cipher_setctr(this->h, &this->ctr, sizeof(this->ctr)) == 0;
     }
     return gcry_cipher_setiv(this->h, iv.ptr, iv.len) == 0;
 }