strongSwan: charon.c File Reference
charon.c File Reference
#include <stdio.h>
#include <signal.h>
#include <pthread.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <unistd.h>
#include <getopt.h>
#include <fcntl.h>
#include <errno.h>
#include <hydra.h>
#include <daemon.h>
#include <library.h>
#include <utils/backtrace.h>
#include <threading/thread.h>
Macros
#define PID_FILE IPSEC_PIDDIR "/charon.pid"
#define IPSEC_USER NULL
#define IPSEC_GROUP NULL
Functions
static void dbg_stderr (debug_t group, level_t level, char *fmt,...)
static void run ()
static bool lookup_uid_gid ()
static void segv_handler (int signal)
static bool check_pidfile ()
static void unlink_pidfile ()
static void usage (const char *msg)
int main (int argc, char *argv[])
Variables
static FILE * pidfile = NULL
static level_t levels [DBG_MAX]
static bool use_syslog = FALSE
void(* dbg)(debug_t group, level_t level, char *fmt,...)
Macro Definition Documentation
#define IPSEC_GROUP NULL
Definition at line 54 of file charon.c.
Referenced by lookup_uid_gid().
#define IPSEC_USER NULL
Default user and group
Definition at line 50 of file charon.c.
Referenced by lookup_uid_gid().
#define PID_FILE IPSEC_PIDDIR "/charon.pid"
PID file, in which charon stores its process id
Definition at line 44 of file charon.c.
Referenced by check_pidfile(), main(), and unlink_pidfile().
Function Documentation
static bool check_pidfile () static
Check/create PID file, return TRUE if already running
Definition at line 198 of file charon.c.
References library_t::caps, DBG1, DBG_DMN, DBG_LIB, FALSE, fprintf, capabilities_t::get_gid, capabilities_t::get_uid, ignore_result, lib, memset, PID_FILE, pidfile, strerror, and TRUE.
Referenced by main().
 {
     struct stat stb;
     if (stat(PID_FILE, &stb) == 0)
     {
         pidfile = fopen(PID_FILE, "r");
         if (pidfile)
         {
             char buf[64];
             pid_t pid = 0;
             memset(buf, 0, sizeof(buf));
             if (fread(buf, 1, sizeof(buf), pidfile))
             {
                 buf[sizeof(buf) - 1] = '\0';
                 pid = atoi(buf);
             }
             fclose(pidfile);
             if (pid && kill(pid, 0) == 0)
             {   /* such a process is running */
                 return TRUE;
             }
         }
         DBG1(DBG_DMN, "removing pidfile '"PID_FILE"', process not running");
         unlink(PID_FILE);
     }
     /* create new pidfile */
     pidfile = fopen(PID_FILE, "w");
     if (pidfile)
     {
         int fd;
         fd = fileno(pidfile);
         if (fd == -1 || fcntl(fd, F_SETFD, FD_CLOEXEC) == -1)
         {
             DBG1(DBG_LIB, "setting FD_CLOEXEC for '"PID_FILE"' failed: %s",
                  strerror(errno));
         }
         ignore_result(fchown(fileno(pidfile),
                              lib->caps->get_uid(lib->caps),
                              lib->caps->get_gid(lib->caps)));
         fprintf(pidfile, "%d\n", getpid());
         fflush(pidfile);
     }
     return FALSE;
 }
static void dbg_stderr (debug_t group, level_t level, char * fmt, ...) static
Logging hook for library logs, using stderr output
Definition at line 80 of file charon.c.
References debug_names, fprintf, and vfprintf.
Referenced by main().
 {
     va_list args;
     if (level <= 1)
     {
         va_start(args, fmt);
         fprintf(stderr, "00[%N] ", debug_names, group);
         vfprintf(stderr, fmt, args);
         fprintf(stderr, "\n");
         va_end(args);
     }
 }
static bool lookup_uid_gid () static
lookup UID and GID
Definition at line 158 of file charon.c.
References library_t::caps, FALSE, settings_t::get_str, IPSEC_GROUP, IPSEC_USER, lib, name, capabilities_t::resolve_gid, capabilities_t::resolve_uid, capabilities_t::set_uid, library_t::settings, and TRUE.
Referenced by main().
 {
     char *name;
     name = lib->settings->get_str(lib->settings, "charon.user", IPSEC_USER);
     if (name && !lib->caps->resolve_uid(lib->caps, name))
     {
         return FALSE;
     }
     name = lib->settings->get_str(lib->settings, "charon.group", IPSEC_GROUP);
     if (name && !lib->caps->resolve_gid(lib->caps, name))
     {
         return FALSE;
     }
 #ifdef ANDROID
     lib->caps->set_uid(lib->caps, AID_VPN);
 #endif
     return TRUE;
 }
int main (int argc, char * argv[])
Main function, starts the daemon.
Definition at line 288 of file charon.c.
References c, library_t::caps, charon, integrity_checker_t::check_file, check_pidfile(), dbg, DBG1, DBG_ASN, DBG_CFG, DBG_CHD, DBG_DMN, DBG_ENC, DBG_ESP, DBG_IKE, DBG_IMC, DBG_IMV, DBG_JOB, DBG_KNL, DBG_LIB, DBG_MAX, DBG_MGR, DBG_NET, DBG_PTS, dbg_stderr(), DBG_TLS, DBG_TNC, capabilities_t::drop, settings_t::get_str, group, daemon_t::initialize, library_t::integrity, LEVEL_CTRL, levels, lib, libcharon_deinit(), libcharon_init(), libhydra_deinit(), libhydra_init(), library_deinit(), library_init(), daemon_t::load_loggers, lookup_uid_gid(), memset, PID_FILE, PLUGINS, library_t::plugins, printf, run(), segv_handler(), library_t::settings, SS_RC_DAEMON_INTEGRITY, SS_RC_INITIALIZATION_FAILED, SS_RC_LIBSTRONGSWAN_INTEGRITY, daemon_t::start, status, plugin_loader_t::status, TRUE, unlink_pidfile(), usage(), and use_syslog.
 {
     struct sigaction action;
     int group, status = SS_RC_INITIALIZATION_FAILED;
     struct utsname utsname;
     /* logging for library during initialization, as we have no bus yet */
     dbg = dbg_stderr;
     /* initialize library */
     if (!library_init(NULL, "charon"))
     {
         library_deinit();
         exit(SS_RC_LIBSTRONGSWAN_INTEGRITY);
     }
     if (lib->integrity &&
         !lib->integrity->check_file(lib->integrity, "charon", argv[0]))
     {
         dbg_stderr(DBG_DMN, 1, "integrity check of charon failed");
         library_deinit();
         exit(SS_RC_DAEMON_INTEGRITY);
     }
     if (!libhydra_init())
     {
         dbg_stderr(DBG_DMN, 1, "initialization failed - aborting charon");
         libhydra_deinit();
         library_deinit();
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     if (!libcharon_init())
     {
         dbg_stderr(DBG_DMN, 1, "initialization failed - aborting charon");
         goto deinit;
     }
     /* use CTRL loglevel for default */
     for (group = 0; group < DBG_MAX; group++)
     {
         levels[group] = LEVEL_CTRL;
     }
     /* handle arguments */
     for (;;)
     {
         struct option long_opts[] = {
             { "help", no_argument, NULL, 'h' },
             { "version", no_argument, NULL, 'v' },
             { "use-syslog", no_argument, NULL, 'l' },
             /* TODO: handle "debug-all" */
             { "debug-dmn", required_argument, &group, DBG_DMN },
             { "debug-mgr", required_argument, &group, DBG_MGR },
             { "debug-ike", required_argument, &group, DBG_IKE },
             { "debug-chd", required_argument, &group, DBG_CHD },
             { "debug-job", required_argument, &group, DBG_JOB },
             { "debug-cfg", required_argument, &group, DBG_CFG },
             { "debug-knl", required_argument, &group, DBG_KNL },
             { "debug-net", required_argument, &group, DBG_NET },
             { "debug-asn", required_argument, &group, DBG_ASN },
             { "debug-enc", required_argument, &group, DBG_ENC },
             { "debug-tnc", required_argument, &group, DBG_TNC },
             { "debug-imc", required_argument, &group, DBG_IMC },
             { "debug-imv", required_argument, &group, DBG_IMV },
             { "debug-pts", required_argument, &group, DBG_PTS },
             { "debug-tls", required_argument, &group, DBG_TLS },
             { "debug-esp", required_argument, &group, DBG_ESP },
             { "debug-lib", required_argument, &group, DBG_LIB },
             { 0,0,0,0 }
         };
         int c = getopt_long(argc, argv, "", long_opts, NULL);
         switch (c)
         {
             case EOF:
                 break;
             case 'h':
                 usage(NULL);
                 status = 0;
                 goto deinit;
             case 'v':
                 printf("Linux strongSwan %s\n", VERSION);
                 status = 0;
                 goto deinit;
             case 'l':
                 use_syslog = TRUE;
                 continue;
             case 0:
                 /* option is in group */
                 levels[group] = atoi(optarg);
                 continue;
             default:
                 usage("");
                 status = 1;
                 goto deinit;
         }
         break;
     }
     if (!lookup_uid_gid())
     {
         dbg_stderr(DBG_DMN, 1, "invalid uid/gid - aborting charon");
         goto deinit;
     }
     charon->load_loggers(charon, levels, !use_syslog);
     if (uname(&utsname) != 0)
     {
         memset(&utsname, 0, sizeof(utsname));
     }
     DBG1(DBG_DMN, "Starting IKE charon daemon (strongSwan "VERSION", %s %s, %s)",
           utsname.sysname, utsname.release, utsname.machine);
     if (lib->integrity)
     {
         DBG1(DBG_DMN, "integrity tests enabled:");
         DBG1(DBG_DMN, "lib    'libstrongswan': passed file and segment integrity tests");
         DBG1(DBG_DMN, "lib    'libhydra': passed file and segment integrity tests");
         DBG1(DBG_DMN, "lib    'libcharon': passed file and segment integrity tests");
         DBG1(DBG_DMN, "daemon 'charon': passed file integrity test");
     }
     /* initialize daemon */
     if (!charon->initialize(charon,
                 lib->settings->get_str(lib->settings, "charon.load", PLUGINS)))
     {
         DBG1(DBG_DMN, "initialization failed - aborting charon");
         goto deinit;
     }
     lib->plugins->status(lib->plugins, LEVEL_CTRL);
     if (check_pidfile())
     {
         DBG1(DBG_DMN, "charon already running (\""PID_FILE"\" exists)");
         goto deinit;
     }
     if (!lib->caps->drop(lib->caps))
     {
         DBG1(DBG_DMN, "capability dropping failed - aborting charon");
         goto deinit;
     }
     /* add handler for SEGV and ILL,
      * INT, TERM and HUP are handled by sigwaitinfo() in run() */
     action.sa_handler = segv_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaddset(&action.sa_mask, SIGINT);
     sigaddset(&action.sa_mask, SIGTERM);
     sigaddset(&action.sa_mask, SIGHUP);
     sigaction(SIGSEGV, &action, NULL);
     sigaction(SIGILL, &action, NULL);
     sigaction(SIGBUS, &action, NULL);
     action.sa_handler = SIG_IGN;
     sigaction(SIGPIPE, &action, NULL);
     pthread_sigmask(SIG_SETMASK, &action.sa_mask, NULL);
     /* start daemon (i.e. the threads in the thread-pool) */
     charon->start(charon);
     /* main thread goes to run loop */
     run();
     /* normal termination, cleanup and exit */
     unlink_pidfile();
     status = 0;
 deinit:
     libcharon_deinit();
     libhydra_deinit();
     library_deinit();
     return status;
 }
static void run () static
Run the daemon and handle unix signals
Definition at line 97 of file charon.c.
References bus_t::alert, ALERT_SHUTDOWN_SIGNAL, daemon_t::bus, charon, library_t::conf, DBG1, DBG_DMN, FALSE, levels, lib, settings_t::load_files, daemon_t::load_loggers, library_t::plugins, plugin_loader_t::reload, library_t::settings, sig, sigwaitinfo(), strerror, TRUE, and use_syslog.
Referenced by main().
 {
     sigset_t set;
     /* handle SIGINT, SIGHUP and SIGTERM in this handler */
     sigemptyset(&set);
     sigaddset(&set, SIGINT);
     sigaddset(&set, SIGHUP);
     sigaddset(&set, SIGTERM);
     sigprocmask(SIG_BLOCK, &set, NULL);
     while (TRUE)
     {
         int sig;
         sig = sigwaitinfo(&set, NULL);
         if (sig == -1)
         {
             if (errno == EINTR)
             {   /* ignore signals we didn't wait for */
                 continue;
             }
             DBG1(DBG_DMN, "waiting for signal failed: %s", strerror(errno));
             return;
         }
         switch (sig)
         {
             case SIGHUP:
             {
                 DBG1(DBG_DMN, "signal of type SIGHUP received. Reloading "
                      "configuration");
                 if (lib->settings->load_files(lib->settings, lib->conf, FALSE))
                 {
                     charon->load_loggers(charon, levels, !use_syslog);
                     lib->plugins->reload(lib->plugins, NULL);
                 }
                 else
                 {
                     DBG1(DBG_DMN, "reloading config failed, keeping old");
                 }
                 break;
             }
             case SIGINT:
             {
                 DBG1(DBG_DMN, "signal of type SIGINT received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return;
             }
             case SIGTERM:
             {
                 DBG1(DBG_DMN, "signal of type SIGTERM received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return;
             }
         }
     }
 }
static void segv_handler (int signal) static
Handle SIGSEGV/SIGILL signals raised by threads
Definition at line 181 of file charon.c.
References backtrace, backtrace_create(), DBG1, DBG_DMN, backtrace_t::destroy, backtrace_t::log, thread_current_id(), and TRUE.
Referenced by main().
 {
     backtrace_t *backtrace;
     DBG1(DBG_DMN, "thread %u received %d", thread_current_id(), signal);
     backtrace = backtrace_create(2);
     backtrace->log(backtrace, NULL, TRUE);
     backtrace->log(backtrace, stderr, TRUE);
     backtrace->destroy(backtrace);
     DBG1(DBG_DMN, "killing ourself, received critical signal");
     abort();
 }
static void unlink_pidfile () static
Delete/truncate the PID file
Definition at line 250 of file charon.c.
References ignore_result, PID_FILE, and pidfile.
Referenced by main().
 {
     /* because unlinking the PID file may fail, we truncate it to ensure the
      * daemon can be properly restarted.  one probable cause for this is the
      * combination of not running as root and the effective user lacking
      * permissions on the parent dir(s) of the PID file */
     if (pidfile)
     {
         ignore_result(ftruncate(fileno(pidfile), 0));
         fclose(pidfile);
     }
     unlink(PID_FILE);
 }
static void usage (const char * msg) static
print command line usage and exit
Definition at line 267 of file charon.c.
References fprintf.
Referenced by main().
 {
     if (msg != NULL && *msg != '\0')
     {
         fprintf(stderr, "%s\n", msg);
     }
     fprintf(stderr, "Usage: charon\n"
                     "         [--help]\n"
                     "         [--version]\n"
                     "         [--use-syslog]\n"
                     "         [--debug-<type> <level>]\n"
                     "           <type>:  log context type (dmn|mgr|ike|chd|job|cfg|knl|net|asn|enc|tnc|imc|imv|pts|tls|esp|lib)\n"
                     "           <level>: log verbosity (-1 = silent, 0 = audit, 1 = control,\n"
                     "                                    2 = controlmore, 3 = raw, 4 = private)\n"
                     "\n"
            );
 }
Variable Documentation
void(* dbg)(debug_t group, level_t level, char *fmt,...)
hook in library for debugging messages
The registered debug hook.
Definition at line 111 of file debug.c.
Referenced by __attribute__(), init(), init_log(), libimcv_init(), main(), METHOD(), openssl_plugin_create(), and parser_helper_log().
level_t levels[DBG_MAX] static
Log levels as defined via command line arguments
Definition at line 65 of file charon.c.
Referenced by CALLBACK(), init_and_run(), main(), METHOD(), and run().
FILE* pidfile = NULL static
Global reference to PID file (required to truncate, if undeletable)
Definition at line 60 of file charon.c.
Referenced by check_pid(), check_pidfile(), and unlink_pidfile().
bool use_syslog = FALSE static
Whether to only use syslog when logging
Definition at line 70 of file charon.c.
Referenced by main(), and run().