strongSwan: ike_sa_id
ike_sa_id
sa
Classes
struct ike_sa_id_t
Typedefs
typedef struct ike_sa_id_t ike_sa_id_t
Functions
ike_sa_id_t * ike_sa_id_create (u_int8_t ike_version, u_int64_t initiator_spi, u_int64_t responder_spi, bool is_initiaor)
Detailed Description
Typedef Documentation
typedef struct ike_sa_id_t ike_sa_id_t
Definition at line 26 of file ike_sa_id.h.
Function Documentation
ike_sa_id_t* ike_sa_id_create (u_int8_t ike_version, u_int64_t initiator_spi, u_int64_t responder_spi, bool is_initiaor)
Creates an ike_sa_id_t object.
Parameters
ike_version major IKE version
initiator_spi initiators SPI
responder_spi responders SPI
is_initiaor TRUE if we are the original initiator
Returns
ike_sa_id_t object
Definition at line 137 of file ike_sa_id.c.
References ike_version, INIT, initiator_spi, and responder_spi.
Referenced by METHOD(), send_check(), and START_TEST().
 {
     private_ike_sa_id_t *this;
     INIT(this,
         .public = {
             .get_ike_version = _get_ike_version,
             .set_responder_spi = _set_responder_spi,
             .set_initiator_spi = _set_initiator_spi,
             .get_responder_spi = _get_responder_spi,
             .get_initiator_spi = _get_initiator_spi,
             .equals = (void*)_equals,
             .replace_values = (void*)_replace_values,
             .is_initiator = _is_initiator,
             .switch_initiator = _switch_initiator,
             .clone = _clone_,
             .destroy = _destroy,
         },
         .ike_version = ike_version,
         .initiator_spi = initiator_spi,
         .responder_spi = responder_spi,
         .is_initiator_flag = is_initiator_flag,
     );
     return &this->public;
 }