strongSwan: imc_scanner.c File Reference
imc_scanner.c File Reference
#include "imc_scanner_state.h"
#include <imc/imc_agent.h>
#include <imc/imc_msg.h>
#include <ietf/ietf_attr.h>
#include <ietf/ietf_attr_attr_request.h>
#include <ietf/ietf_attr_port_filter.h>
#include <tncif_pa_subtypes.h>
#include <pen/pen.h>
#include <utils/lexparser.h>
#include <utils/debug.h>
#include <stdio.h>
Functions
TNC_Result TNC_IMC_Initialize (TNC_IMCID imc_id, TNC_Version min_version, TNC_Version max_version, TNC_Version *actual_version)
TNC_Result TNC_IMC_NotifyConnectionChange (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_ConnectionState new_state)
static bool do_netstat (ietf_attr_port_filter_t *attr)
static TNC_Result add_port_filter (imc_msg_t *msg)
TNC_Result TNC_IMC_BeginHandshake (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
static TNC_Result receive_message (imc_msg_t *in_msg)
TNC_Result TNC_IMC_ReceiveMessage (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
TNC_Result TNC_IMC_ReceiveMessageLong (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
TNC_Result TNC_IMC_BatchEnding (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
TNC_Result TNC_IMC_Terminate (TNC_IMCID imc_id)
TNC_Result TNC_IMC_ProvideBindFunction (TNC_IMCID imc_id, TNC_TNCC_BindFunctionPointer bind_function)
Variables
static const char imc_name [] = "Scanner"
static pen_type_t msg_types []
static imc_agent_t * imc_scanner
Function Documentation
static TNC_Result add_port_filter (imc_msg_t * msg) static
Add IETF Port Filter attribute to the send queue
Definition at line 239 of file imc_scanner.c.
References imc_msg_t::add_attribute, pa_tnc_attr_t::destroy, do_netstat(), IETF_ATTR_PORT_FILTER, ietf_attr_port_filter_create(), PEN_IETF, pen_type_create(), pa_tnc_attr_t::set_noskip_flag, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, and TRUE.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     ietf_attr_port_filter_t *attr_port_filter;
     attr = ietf_attr_port_filter_create(pen_type_create(PEN_IETF,
                                         IETF_ATTR_PORT_FILTER));
     attr->set_noskip_flag(attr, TRUE);
     attr_port_filter = (ietf_attr_port_filter_t*)attr;
     if (!do_netstat(attr_port_filter))
     {
         attr->destroy(attr);
         return TNC_RESULT_FATAL;
     }
     msg->add_attribute(msg, attr);
     return TNC_RESULT_SUCCESS;
 }
static bool do_netstat (ietf_attr_port_filter_t * attr) static
Determine all TCP and UDP server sockets listening on physical interfaces
Definition at line 108 of file imc_scanner.c.
References ietf_attr_port_filter_t::add_port, allowed(), BUF_LEN, chunk_create(), chunk_empty, ietf_attr_port_filter_t::create_port_enumerator, DBG1, DBG2, DBG_IMC, enumerator_t::destroy, eat_whitespace(), end, enumerator_t::enumerate, extract_token(), FALSE, found, chunk_t::len, match(), memeq(), n, port, protocol, chunk_t::ptr, and TRUE.
Referenced by add_port_filter().
 {
     FILE *file;
     char buf[BUF_LEN];
     chunk_t line, token;
     int n = 0;
     bool success = FALSE;
     const char system_v4[]   = "127.0.1.1";
     const char loopback_v4[] = "127.0.0.1";
     const char loopback_v6[] = "::1";
     /* Open a pipe stream for reading the output of the netstat commmand */
     file = popen("/bin/netstat -n -l -p -4 -6 --inet", "r");
     if (!file)
     {
         DBG1(DBG_IMC, "failed to run netstat command");
         return FALSE;
     }
     /* Read the output a line at a time */
     while (fgets(buf, sizeof(buf), file))
     {
         u_char *pos;
         u_int8_t new_protocol, protocol;
         u_int16_t new_port, port;
         int i;
         enumerator_t *enumerator;
         bool allowed, found = FALSE;
         DBG2(DBG_IMC, "%.*s", (int)(strlen(buf)-1), buf);
         if (n++ < 2)
         {
             /* skip the first two header lines */
             continue;
         }
         line = chunk_create(buf, strlen(buf));
         /* Extract the IP protocol type */
         if (!extract_token(&token, ' ', &line))
         {
             DBG1(DBG_IMC, "protocol field in netstat output not found");
             goto end;
         }
         if (match("tcp", &token) || match("tcp6", &token))
         {
             new_protocol = IPPROTO_TCP;
         }
         else if (match("udp", &token) || match("udp6", &token))
         {
             new_protocol = IPPROTO_UDP;
         }
         else
         {
             DBG1(DBG_IMC, "skipped unknown IP protocol in netstat output");
             continue;
         }
         /* Skip the Recv-Q and Send-Q fields */
         for (i = 0; i < 3; i++)
         {
             if (!eat_whitespace(&line) || !extract_token(&token, ' ', &line))
             {
                 token = chunk_empty;
                 break;
             }
         }
         if (token.len == 0)
         {
             DBG1(DBG_IMC, "local address field in netstat output not found");
             goto end;
         }
         /* Find the local port appended to the local address */
         pos = token.ptr + token.len;
         while (*--pos != ':' && --token.len);
         if (*pos != ':')
         {
             DBG1(DBG_IMC, "local port field in netstat output not found");
             goto end;
         }
         token.len--;
         /* ignore ports of IPv4 and IPv6 loopback interfaces
            and the internal system IPv4 address */
         if ((token.len == strlen(system_v4) &&
                 memeq(system_v4, token.ptr, token.len)) ||
             (token.len == strlen(loopback_v4) &&
                 memeq(loopback_v4, token.ptr, token.len)) ||
             (token.len == strlen(loopback_v6) &&
                 memeq(loopback_v6, token.ptr, token.len)))
         {
             continue;
         }
         /* convert the port string to an integer */
         new_port = atoi(pos+1);
         /* check if the there is already a port entry */
         enumerator = attr->create_port_enumerator(attr);
         while (enumerator->enumerate(enumerator, &allowed, &protocol, &port))
         {
             if (new_port == port && new_protocol == protocol)
             {
                 found = TRUE;
             }
         }
         enumerator->destroy(enumerator);
         /* Skip the duplicate port entry */
         if (found)
         {
             continue;
         }
         /* Add new port entry */
         attr->add_port(attr, FALSE, new_protocol, new_port);
     }
     /* Successfully completed the parsing of the netstat output */
     success = TRUE;
 end:
     /* Close the pipe stream */
     pclose(file);
     return success;
 }
static TNC_Result receive_message (imc_msg_t * in_msg) static
Definition at line 294 of file imc_scanner.c.
References add_port_filter(), imc_msg_t::create_attribute_enumerator, ietf_attr_attr_request_t::create_enumerator, enumerator_t::destroy, imc_msg_t::destroy, enumerator_t::enumerate, FALSE, pa_tnc_attr_t::get_type, IETF_ATTR_ATTRIBUTE_REQUEST, IETF_ATTR_PORT_FILTER, imc_msg_create_as_reply(), PEN_IETF, imc_msg_t::receive, result, imc_msg_t::send, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, TRUE, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by TNC_IMC_ReceiveMessage(), and TNC_IMC_ReceiveMessageLong().
 {
     imc_msg_t *out_msg;
     enumerator_t *enumerator;
     pa_tnc_attr_t *attr;
     pen_type_t attr_type;
     TNC_Result result = TNC_RESULT_SUCCESS;
     bool fatal_error = FALSE;
     /* generate an outgoing PA-TNC message - we might need it */
     out_msg = imc_msg_create_as_reply(in_msg);
     /* parse received PA-TNC message and handle local and remote errors */
     result = in_msg->receive(in_msg, out_msg, &fatal_error);
     if (result != TNC_RESULT_SUCCESS)
     {
         out_msg->destroy(out_msg);
         return result;
     }
     /* analyze PA-TNC attributes */
     enumerator = in_msg->create_attribute_enumerator(in_msg);
     while (enumerator->enumerate(enumerator, &attr))
     {
         attr_type = attr->get_type(attr);
         if (attr_type.vendor_id != PEN_IETF)
         {
             continue;
         }
         if (attr_type.type == IETF_ATTR_ATTRIBUTE_REQUEST)
         {
             ietf_attr_attr_request_t *attr_cast;
             pen_type_t *entry;
             enumerator_t *e;
             attr_cast = (ietf_attr_attr_request_t*)attr;
             e = attr_cast->create_enumerator(attr_cast);
             while (e->enumerate(e, &entry))
             {
                 if (entry->vendor_id != PEN_IETF)
                 {
                     continue;
                 }
                 switch (entry->type)
                 {
                     case IETF_ATTR_PORT_FILTER:
                         result = add_port_filter(out_msg);
                         break;
                     default:
                         break;
                 }
             }
             e->destroy(e);
         }
     }
     enumerator->destroy(enumerator);
     if (fatal_error)
     {
         result = TNC_RESULT_FATAL;
     }
     else if (result == TNC_RESULT_SUCCESS)
     {
         /* send PA-TNC message with the EXCL flag set */
         result = out_msg->send(out_msg, TRUE);
     }
     out_msg->destroy(out_msg);
     return result;
 }
Variable Documentation
const char imc_name[] = "Scanner" static
Definition at line 34 of file imc_scanner.c.
Referenced by TNC_IMC_BatchEnding(), TNC_IMC_BeginHandshake(), TNC_IMC_Initialize(), TNC_IMC_NotifyConnectionChange(), TNC_IMC_ProvideBindFunction(), TNC_IMC_ReceiveMessage(), TNC_IMC_ReceiveMessageLong(), and TNC_IMC_Terminate().
imc_agent_t* imc_scanner static
Definition at line 40 of file imc_scanner.c.
pen_type_t msg_types[] static
Initial value:
= {
    { PEN_IETF, PA_SUBTYPE_IETF_FIREWALL }
}
Definition at line 36 of file imc_scanner.c.