strongSwan: dnskey_builder.c File Reference
dnskey_builder.c File Reference
#include "dnskey_builder.h"
#include <utils/debug.h>
#include <credentials/keys/private_key.h>
Classes
struct dnskey_rr_t
Typedefs
typedef struct dnskey_rr_t dnskey_rr_t
typedef enum dnskey_algorithm_t dnskey_algorithm_t
Enumerations
enum dnskey_algorithm_t {
DNSKEY_ALG_RSA_MD5 = 1, DNSKEY_ALG_DH = 2, DNSKEY_ALG_DSA = 3, DNSKEY_ALG_RSA_SHA1 = 5,
DNSKEY_ALG_DSA_NSEC3_SHA1 = 6, DNSKEY_ALG_RSA_SHA1_NSEC3_SHA1 = 7, DNSKEY_ALG_RSA_SHA256 = 8, DNSKEY_ALG_RSA_SHA512 = 10,
DNSKEY_ALG_ECC_GOST = 12, DNSKEY_ALG_ECDSA_P256_SHA256 = 13, DNSKEY_ALG_ECDSA_P384_SHA384 = 14
}
Functions
struct dnskey_rr_t __attribute__ ((__packed__))
static dnskey_public_key_t * parse_public_key (chunk_t blob)
static dnskey_public_key_t * parse_rsa_public_key (chunk_t blob)
dnskey_public_key_t * dnskey_public_key_load (key_type_t type, va_list args)
Variables
u_int16_t flags
u_int8_t protocol
u_int8_t algorithm
u_int8_t data []
enum dnskey_algorithm_t __attribute__
Typedef Documentation
typedef enum dnskey_algorithm_t dnskey_algorithm_t
Definition at line 23 of file dnskey_builder.c.
typedef struct dnskey_rr_t dnskey_rr_t
Definition at line 22 of file dnskey_builder.c.
Enumeration Type Documentation
enum dnskey_algorithm_t
DNSSEC algorithms, RFC4034 Appendix A.1.
Enumerator
DNSKEY_ALG_RSA_MD5
DNSKEY_ALG_DH
DNSKEY_ALG_DSA
DNSKEY_ALG_RSA_SHA1
DNSKEY_ALG_DSA_NSEC3_SHA1
DNSKEY_ALG_RSA_SHA1_NSEC3_SHA1
DNSKEY_ALG_RSA_SHA256
DNSKEY_ALG_RSA_SHA512
DNSKEY_ALG_ECC_GOST
DNSKEY_ALG_ECDSA_P256_SHA256
DNSKEY_ALG_ECDSA_P384_SHA384
Definition at line 38 of file dnskey_builder.c.
{
     DNSKEY_ALG_RSA_MD5 = 1,
     DNSKEY_ALG_DH = 2,
     DNSKEY_ALG_DSA = 3,
     DNSKEY_ALG_RSA_SHA1 = 5,
     DNSKEY_ALG_DSA_NSEC3_SHA1 = 6,
     DNSKEY_ALG_RSA_SHA1_NSEC3_SHA1 = 7,
     DNSKEY_ALG_RSA_SHA256 = 8,
     DNSKEY_ALG_RSA_SHA512 = 10,
     DNSKEY_ALG_ECC_GOST = 12,
     DNSKEY_ALG_ECDSA_P256_SHA256 = 13,
     DNSKEY_ALG_ECDSA_P384_SHA384 = 14
 };
Function Documentation
static dnskey_public_key_t* parse_public_key (chunk_t blob) static
Load a generic public key from a DNSKEY RR blob
Definition at line 55 of file dnskey_builder.c.
References dnskey_rr_t::algorithm, BUILD_BLOB_DNSKEY, BUILD_END, chunk_skip(), credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, DBG1, DBG_LIB, DNSKEY_ALG_RSA_MD5, DNSKEY_ALG_RSA_SHA1, DNSKEY_ALG_RSA_SHA1_NSEC3_SHA1, DNSKEY_ALG_RSA_SHA256, DNSKEY_ALG_RSA_SHA512, if(), KEY_RSA, chunk_t::len, lib, and chunk_t::ptr.
Referenced by dnskey_public_key_load().
 {
     dnskey_rr_t *rr = (dnskey_rr_t*)blob.ptr;
     if (blob.len < sizeof(dnskey_rr_t))
     {
         DBG1(DBG_LIB, "DNSKEY too short");
         return NULL;
     }
     blob = chunk_skip(blob, sizeof(dnskey_rr_t));
     switch (rr->algorithm)
     {
         case DNSKEY_ALG_RSA_MD5:
         case DNSKEY_ALG_RSA_SHA1:
         case DNSKEY_ALG_RSA_SHA1_NSEC3_SHA1:
         case DNSKEY_ALG_RSA_SHA256:
         case DNSKEY_ALG_RSA_SHA512:
             return lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                                       BUILD_BLOB_DNSKEY, blob, BUILD_END);
         default:
             DBG1(DBG_LIB, "DNSKEY public key algorithm %d not supported",
                  rr->algorithm);
             return NULL;
     }
 }
static dnskey_public_key_t* parse_rsa_public_key (chunk_t blob) static
Load a RSA public key from DNSKEY RR data
Definition at line 85 of file dnskey_builder.c.
References BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_skip(), credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, DBG1, DBG_LIB, KEY_RSA, chunk_t::len, lib, n, and chunk_t::ptr.
Referenced by dnskey_public_key_load().
 {
     chunk_t n, e;
     if (blob.len < 3)
     {
         DBG1(DBG_LIB, "RFC 3110 public key blob too short for exponent length");
         return NULL;
     }
     if (blob.ptr[0])
     {
         e.len = blob.ptr[0];
         blob = chunk_skip(blob, 1);
     }
     else
     {
         e.len = blob.ptr[1] * 256 + blob.ptr[2];
         blob = chunk_skip(blob, 3);
     }
     e.ptr = blob.ptr;
     if (e.len >= blob.len)
     {
         DBG1(DBG_LIB, "RFC 3110 public key blob too short for exponent");
         return NULL;
     }
     n = chunk_skip(blob, e.len);
     return lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                         BUILD_RSA_MODULUS, n, BUILD_RSA_PUB_EXP, e,
                         BUILD_END);
 }
Variable Documentation
enum dnskey_algorithm_t __attribute__
u_int8_t algorithm
Definition at line 42 of file dnskey_builder.c.
Referenced by dnscert_create_frm_rr(), generate(), ipseckey_create_frm_rr(), METHOD(), parse(), parse_certificate(), parse_certificate_request(), and sha3_hasher_create().
u_int8_t data[]
Definition at line 43 of file dnskey_builder.c.
u_int16_t flags
Definition at line 40 of file dnskey_builder.c.
u_int8_t protocol
Definition at line 41 of file dnskey_builder.c.