strongSwan: pkcs8_builder
pkcs8_builder
pkcs8
Functions
private_key_t * pkcs8_private_key_load (key_type_t type, va_list args)
Detailed Description
Function Documentation
private_key_t* pkcs8_private_key_load (key_type_t type, va_list args)
Load an RSA or ECDSA private key from PKCS#8 data.
Parameters
type type of the key, KEY_RSA or KEY_ECDSA
args builder_part_t argument list
Returns
private key, NULL on failure
See header.
Definition at line 194 of file pkcs8_builder.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, key, parse_encrypted_private_key(), parse_private_key(), and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     private_key_t *key;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     /* we don't know whether it is encrypted or not, try both ways */
     key = parse_encrypted_private_key(blob);
     if (!key)
     {
         key = parse_private_key(blob);
     }
     return key;
 }