strongSwan: plugin_loader
plugin_loader
plugins
Classes
struct plugin_loader_t
Typedefs
typedef struct plugin_loader_t plugin_loader_t
Functions
plugin_loader_t * plugin_loader_create ()
void plugin_loader_add_plugindirs (char *basedir, char *plugins)
Detailed Description
Typedef Documentation
typedef struct plugin_loader_t plugin_loader_t
Definition at line 25 of file plugin_loader.h.
Function Documentation
void plugin_loader_add_plugindirs (char * basedir, char * plugins)
Convenience function to add plugin directories for the given plugins within the given base directory according to the conventions in the src/build tree.
Parameters
basedir base directory
plugins space separated list of plugins
Definition at line 1351 of file plugin_loader.c.
References plugin_loader_t::add_path, enumerator_t::destroy, dir, enumerator_t::enumerate, enumerator_create_token(), lib, name, path, library_t::plugins, snprintf, and translate().
Referenced by test_runner_init().
 {
     enumerator_t *enumerator;
     char *name, path[PATH_MAX], dir[64];
     enumerator = enumerator_create_token(plugins, " ", "");
     while (enumerator->enumerate(enumerator, &name))
     {
         snprintf(dir, sizeof(dir), "%s", name);
         translate(dir, "-", "_");
         snprintf(path, sizeof(path), "%s/%s/.libs", basedir, dir);
         lib->plugins->add_path(lib->plugins, path);
     }
     enumerator->destroy(enumerator);
 }
plugin_loader_t* plugin_loader_create ()
Create a plugin_loader instance.
Returns
plugin loader instance
Definition at line 1321 of file plugin_loader.c.
References hashtable_create(), INIT, linked_list_create(), registered_feature_equals(), and registered_feature_hash().
Referenced by library_init().
 {
     private_plugin_loader_t *this;
     INIT(this,
         .public = {
             .add_static_features = _add_static_features,
             .load = _load_plugins,
             .add_path = _add_path,
             .reload = _reload,
             .unload = _unload,
             .create_plugin_enumerator = _create_plugin_enumerator,
             .has_feature = _has_feature,
             .loaded_plugins = _loaded_plugins,
             .status = _status,
             .destroy = _destroy,
         },
         .plugins = linked_list_create(),
         .loaded = linked_list_create(),
         .features = hashtable_create(
                             (hashtable_hash_t)registered_feature_hash,
                             (hashtable_equals_t)registered_feature_equals, 64),
     );
     return &this->public;
 }