strongSwan: hybrid_authenticator
hybrid_authenticator
authenticators
Classes
struct hybrid_authenticator_t
Typedefs
typedef struct
hybrid_authenticator_t hybrid_authenticator_t
Functions
hybrid_authenticator_t * hybrid_authenticator_create (ike_sa_t *ike_sa, bool initiator, diffie_hellman_t *dh, chunk_t dh_value, chunk_t sa_payload, chunk_t id_payload)
Detailed Description
Typedef Documentation
typedef struct hybrid_authenticator_t hybrid_authenticator_t
Definition at line 24 of file hybrid_authenticator.h.
Function Documentation
hybrid_authenticator_t* hybrid_authenticator_create (ike_sa_t * ike_sa, bool initiator, diffie_hellman_t * dh, chunk_t dh_value, chunk_t sa_payload, chunk_t id_payload)
Create an authenticator to build hybrid signatures.
Parameters
ike_sa associated IKE_SA
initiator TRUE if we are the IKE_SA initiator
dh diffie hellman key exchange
dh_value others public diffie hellman value
sa_payload generated SA payload data, without payload header
id_payload encoded ID payload of peer to authenticate or verify without payload header (gets owned)
Returns
hybrid authenticator
Definition at line 79 of file hybrid_authenticator.c.
References AUTH_RSA, authenticator_create_v1(), chunk_clone, destroy(), hash, INIT, psk_v1_authenticator_create(), return_false(), sig, and TRUE.
 {
     private_hybrid_authenticator_t *this;
     INIT(this,
         .public = {
             .authenticator = {
                 .is_mutual = (void*)return_false,
                 .destroy = _destroy,
             },
         },
         .hash = (authenticator_t*)psk_v1_authenticator_create(ike_sa, initiator,
                         dh, dh_value, sa_payload, id_payload, TRUE),
         .sig = authenticator_create_v1(ike_sa, initiator, AUTH_RSA, dh,
                         dh_value, sa_payload, chunk_clone(id_payload)),
     );
     if (!this->sig || !this->hash)
     {
         destroy(this);
         return NULL;
     }
     if (initiator)
     {
         this->public.authenticator.build = _build_i;
         this->public.authenticator.process = _process_i;
     }
     else
     {
         this->public.authenticator.build = _build_r;
         this->public.authenticator.process = _process_r;
     }
     return &this->public;
 }