strongSwan: receiver
receiver
network
Classes
struct receiver_t
Typedefs
typedef struct receiver_t receiver_t
typedef void(* receiver_esp_cb_t)(void *data, packet_t *packet)
Functions
receiver_t * receiver_create (void)
Detailed Description
Typedef Documentation
typedef void(* receiver_esp_cb_t)(void *data, packet_t *packet)
Callback called for any received UDP encapsulated ESP packet.
Implementation should be quick as the receiver doesn't receive any packets while calling this function.
Parameters
data data supplied during registration of the callback
packet decapsulated ESP packet
Definition at line 41 of file receiver.h.
typedef struct receiver_t receiver_t
Definition at line 26 of file receiver.h.
Function Documentation
receiver_t* receiver_create (void)
Create a receiver_t object.
The receiver thread will start working, get data from the socket and add those packets to the job queue.
Returns
receiver_t object, NULL if initialization fails
Definition at line 622 of file receiver.c.
References BLOCK_THRESHOLD_DEFAULT, callback_job_create_with_prio(), COOKIE_THRESHOLD_DEFAULT, crypto_factory_t::create_hasher, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_NET, destroy(), FALSE, free(), settings_t::get_bool, settings_t::get_int, HASH_SHA1, hasher, INIT, JOB_PRIO_CRITICAL, lib, memcpy, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, library_t::processor, processor_t::queue_job, random, receive_packets(), return_false(), rng, RNG_STRONG, SECRET_LENGTH, library_t::settings, time_monotonic(), and TRUE.
Referenced by sender_receiver_cb().
 {
     private_receiver_t *this;
     u_int32_t now = time_monotonic(NULL);
     INIT(this,
         .public = {
             .add_esp_cb = _add_esp_cb,
             .del_esp_cb = _del_esp_cb,
             .destroy = _destroy,
         },
         .esp_cb_mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .secret_switch = now,
         .secret_offset = random() % now,
     );
     if (lib->settings->get_bool(lib->settings,
                                 "%s.dos_protection", TRUE, lib->ns))
     {
         this->cookie_threshold = lib->settings->get_int(lib->settings,
                     "%s.cookie_threshold", COOKIE_THRESHOLD_DEFAULT, lib->ns);
         this->block_threshold = lib->settings->get_int(lib->settings,
                     "%s.block_threshold", BLOCK_THRESHOLD_DEFAULT, lib->ns);
     }
     this->init_limit_job_load = lib->settings->get_int(lib->settings,
                     "%s.init_limit_job_load", 0, lib->ns);
     this->init_limit_half_open = lib->settings->get_int(lib->settings,
                     "%s.init_limit_half_open", 0, lib->ns);
     this->receive_delay = lib->settings->get_int(lib->settings,
                     "%s.receive_delay", 0, lib->ns);
     this->receive_delay_type = lib->settings->get_int(lib->settings,
                     "%s.receive_delay_type", 0, lib->ns),
     this->receive_delay_request = lib->settings->get_bool(lib->settings,
                     "%s.receive_delay_request", TRUE, lib->ns),
     this->receive_delay_response = lib->settings->get_bool(lib->settings,
                     "%s.receive_delay_response", TRUE, lib->ns),
     this->initiator_only = lib->settings->get_bool(lib->settings,
                     "%s.initiator_only", FALSE, lib->ns),
     this->hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!this->hasher)
     {
         DBG1(DBG_NET, "creating cookie hasher failed, no hashers supported");
         free(this);
         return NULL;
     }
     this->rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
     if (!this->rng)
     {
         DBG1(DBG_NET, "creating cookie RNG failed, no RNG supported");
         this->hasher->destroy(this->hasher);
         free(this);
         return NULL;
     }
     if (!this->rng->get_bytes(this->rng, SECRET_LENGTH, this->secret))
     {
         DBG1(DBG_NET, "creating cookie secret failed");
         destroy(this);
         return NULL;
     }
     memcpy(this->secret_old, this->secret, SECRET_LENGTH);
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create_with_prio((callback_job_cb_t)receive_packets,
             this, NULL, (callback_job_cancel_t)return_false, JOB_PRIO_CRITICAL));
     return &this->public;
 }