strongSwan: generic_attr_string.c File Reference
generic_attr_string.c File Reference
#include "generic_attr_string.h"
#include <imcv.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_generic_attr_string_t
Typedefs
typedef struct
private_generic_attr_string_t private_generic_attr_string_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_generic_attr_string_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_generic_attr_string_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_generic_attr_string_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_generic_attr_string_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_generic_attr_string_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_generic_attr_string_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_generic_attr_string_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_generic_attr_string_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_generic_attr_string_t *this)
pa_tnc_attr_t * generic_attr_string_create_from_data (size_t length, chunk_t value, pen_type_t type)
pa_tnc_attr_t * generic_attr_string_create (chunk_t value, pen_type_t type)
Typedef Documentation
typedef struct private_generic_attr_string_t private_generic_attr_string_t
Definition at line 22 of file generic_attr_string.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_generic_attr_string_t * this)
Definition at line 60 of file generic_attr_string.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_generic_attr_string_t * this)
Definition at line 66 of file generic_attr_string.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_generic_attr_string_t * this)
Definition at line 72 of file generic_attr_string.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_generic_attr_string_t * this, bool noskip)
Definition at line 78 of file generic_attr_string.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_generic_attr_string_t * this)
Definition at line 84 of file generic_attr_string.c.
 {
     return;
 }
METHOD (pa_tnc_attr_t , process , status_t , private_generic_attr_string_t * this, u_int32_t * offset)
Definition at line 90 of file generic_attr_string.c.
References DBG1, DBG_TNC, FAILED, pa_tnc_attr_manager_t::get_names, imcv_pa_tnc_attributes, NEED_MORE, pen_names, SUCCESS, type, and value.
 {
     enum_name_t *pa_attr_names;
     u_char *pos;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     pa_attr_names = imcv_pa_tnc_attributes->get_names(imcv_pa_tnc_attributes,
                                                       this->type.vendor_id);
     if (this->value.len > this->length)
     {
         DBG1(DBG_TNC, "inconsistent length of %N/%N string attribute",
              pen_names, this->type.vendor_id, pa_attr_names, this->type.type);
         return FAILED;
     }
     pos = memchr(this->value.ptr, '\0', this->value.len);
     if (pos)
     {
         DBG1(DBG_TNC, "nul termination in %N/%N string attribute",
              pen_names, this->type.vendor_id, pa_attr_names, this->type.type);
         *offset = pos - this->value.ptr;
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_generic_attr_string_t * this, chunk_t segment)
Definition at line 122 of file generic_attr_string.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_generic_attr_string_t * this)
Definition at line 128 of file generic_attr_string.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_generic_attr_string_t * this)
Definition at line 135 of file generic_attr_string.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }