strongSwan: tcg_seg_attr_seg_env.c File Reference
tcg_seg_attr_seg_env.c File Reference
#include "tcg_seg_attr_seg_env.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_seg_attr_seg_env_t
Typedefs
typedef struct
private_tcg_seg_attr_seg_env_t private_tcg_seg_attr_seg_env_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_seg_attr_seg_env_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_seg_attr_seg_env_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_seg_attr_seg_env_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_seg_attr_seg_env_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_seg_attr_seg_env_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_seg_attr_seg_env_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_seg_attr_seg_env_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_seg_attr_seg_env_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_seg_attr_seg_env_t *this)
METHOD (tcg_seg_attr_seg_env_t, get_segment, chunk_t, private_tcg_seg_attr_seg_env_t *this, uint8_t *flags)
METHOD (tcg_seg_attr_seg_env_t, get_base_attr_id, uint32_t, private_tcg_seg_attr_seg_env_t *this)
pa_tnc_attr_t * tcg_seg_attr_seg_env_create (chunk_t segment, uint8_t flags, uint32_t base_attr_id)
pa_tnc_attr_t * tcg_seg_attr_seg_env_create_from_data (size_t length, chunk_t data)
Typedef Documentation
typedef struct private_tcg_seg_attr_seg_env_t private_tcg_seg_attr_seg_env_t
Definition at line 23 of file tcg_seg_attr_seg_env.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_seg_attr_seg_env_t * this)
Definition at line 89 of file tcg_seg_attr_seg_env.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_seg_attr_seg_env_t * this)
Definition at line 95 of file tcg_seg_attr_seg_env.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_seg_attr_seg_env_t * this)
Definition at line 101 of file tcg_seg_attr_seg_env.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_seg_attr_seg_env_t * this, bool noskip)
Definition at line 107 of file tcg_seg_attr_seg_env.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_seg_attr_seg_env_t * this)
Definition at line 113 of file tcg_seg_attr_seg_env.c.
References length, and value.
 {
     /* constructor already allocated and built value */
     this->length = this->value.len;
     return;
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_seg_attr_seg_env_t * this, u_int32_t * offset)
Definition at line 121 of file tcg_seg_attr_seg_env.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, flags, pen_names, PEN_TCG, bio_reader_t::read_uint24, bio_reader_t::read_uint8, SUCCESS, tcg_attr_names, TCG_SEG_ATTR_SEG_ENV_HEADER, type, and value.
 {
     bio_reader_t *reader;
     *offset = 0;
     if (this->value.len < this->length)
     {
         DBG1(DBG_TNC, "segmentation not allowed for %N/%N", pen_names, PEN_TCG,
                        tcg_attr_names, this->type.type);
         return FAILED;
     }
     if (this->value.len < TCG_SEG_ATTR_SEG_ENV_HEADER)
     {
         DBG1(DBG_TNC, "insufficient data for %N/%N", pen_names, PEN_TCG,
                        tcg_attr_names, this->type.type);
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &this->flags);
     reader->read_uint24(reader, &this->base_attr_id);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_seg_attr_seg_env_t * this, chunk_t segment)
Definition at line 148 of file tcg_seg_attr_seg_env.c.
 {
     /* no segments are expected */
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_seg_attr_seg_env_t * this)
Definition at line 154 of file tcg_seg_attr_seg_env.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_seg_attr_seg_env_t * this)
Definition at line 161 of file tcg_seg_attr_seg_env.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_seg_attr_seg_env_t , get_segment , chunk_t , private_tcg_seg_attr_seg_env_t * this, uint8_t * flags)
Definition at line 171 of file tcg_seg_attr_seg_env.c.
References chunk_skip(), flags, TCG_SEG_ATTR_SEG_ENV_HEADER, and value.
 {
     if (flags)
     {
         *flags = this->flags;
     }
     return chunk_skip(this->value, TCG_SEG_ATTR_SEG_ENV_HEADER);
 }
METHOD (tcg_seg_attr_seg_env_t , get_base_attr_id , uint32_t , private_tcg_seg_attr_seg_env_t * this)
Definition at line 181 of file tcg_seg_attr_seg_env.c.
 {
     return this->base_attr_id;
 }