strongSwan: agent_private_key
agent_private_key
agent
Classes
struct agent_private_key_t
Typedefs
typedef struct agent_private_key_t agent_private_key_t
Functions
agent_private_key_t * agent_private_key_open (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct agent_private_key_t agent_private_key_t
Definition at line 27 of file agent_private_key.h.
Function Documentation
agent_private_key_t* agent_private_key_open (key_type_t type, va_list args)
Open connection to a private key stored in a SSH agent.
The function takes BUILD_AGENT_SOCKET and optionally a BUILD_PUBLIC_KEY to select a specific key loaded in ssh-agent.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
built key, NULL on failure
See header.
Definition at line 384 of file agent_private_key.c.
References BUILD_AGENT_SOCKET, BUILD_END, BUILD_PUBLIC_KEY, destroy(), free(), INIT, open_connection(), path, private_key_belongs_to(), private_key_equals(), private_key_has_fingerprint(), read_key(), socket, and TRUE.
Referenced by METHOD().
 {
     private_agent_private_key_t *this;
     public_key_t *pubkey = NULL;
     char *path = NULL;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_AGENT_SOCKET:
                 path = va_arg(args, char*);
                 continue;
             case BUILD_PUBLIC_KEY:
                 pubkey = va_arg(args, public_key_t*);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!path)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .sign = _sign,
                 .decrypt = _decrypt,
                 .get_keysize = _get_keysize,
                 .get_public_key = _get_public_key,
                 .belongs_to = private_key_belongs_to,
                 .equals = private_key_equals,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = private_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     this->socket = open_connection(path);
     if (this->socket < 0)
     {
         free(this);
         return NULL;
     }
     if (!read_key(this, pubkey))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }