strongSwan: settings
settings
settings
Classes
struct settings_t
Typedefs
typedef struct settings_t settings_t
Functions
bool settings_value_as_bool (char *value, bool def)
int settings_value_as_int (char *value, int def)
u_int64_t settings_value_as_uint64 (char *value, u_int64_t def)
double settings_value_as_double (char *value, double def)
u_int32_t settings_value_as_time (char *value, u_int32_t def)
settings_t * settings_create (char *file)
settings_t * settings_create_string (char *settings)
Detailed Description
Typedef Documentation
typedef struct settings_t settings_t
Definition at line 28 of file settings.h.
Function Documentation
settings_t* settings_create (char * file)
Load settings from a file.
Note
If parsing the file fails the object is still created.
Parameters
file optional file to read settings from
Returns
settings object
Definition at line 997 of file settings.c.
References FALSE, and settings_create_base().
Referenced by create_settings(), library_init(), load_all(), load_authorities(), load_configs(), load_conns(), load_creds(), and load_pools().
 {
     private_settings_t *this = settings_create_base();
     load_files(this, file, FALSE);
     return &this->public;
 }
settings_t* settings_create_string (char * settings)
Load settings from a string.
Note
If parsing the file fails the object is still created.
Parameters
settings string to read settings from
Returns
settings object, or NULL
Definition at line 1009 of file settings.c.
References FALSE, and settings_create_base().
Referenced by START_TEST().
 {
     private_settings_t *this = settings_create_base();
     load_string(this, settings, FALSE);
     return &this->public;
 }
bool settings_value_as_bool (char * value, bool def) inline
Convert a string value returned by a key/value enumerator to a boolean.
See Also
settings_t.create_key_value_enumerator()
settings_t.get_bool()
Parameters
value the string value
def the default value, if value is NULL or invalid
Described in header
Definition at line 474 of file settings.c.
References FALSE, strcaseeq(), and TRUE.
Referenced by METHOD().
 {
     if (value)
     {
         if (strcaseeq(value, "1") ||
             strcaseeq(value, "yes") ||
             strcaseeq(value, "true") ||
             strcaseeq(value, "enabled"))
         {
             return TRUE;
         }
         else if (strcaseeq(value, "0") ||
                  strcaseeq(value, "no") ||
                  strcaseeq(value, "false") ||
                  strcaseeq(value, "disabled"))
         {
             return FALSE;
         }
     }
     return def;
 }
double settings_value_as_double (char * value, double def) inline
Convert a string value returned by a key/value enumerator to a double.
See Also
settings_t.create_key_value_enumerator()
settings_t.get_double()
Parameters
value the string value
def the default value, if value is NULL or invalid
Described in header
Definition at line 568 of file settings.c.
References end.
Referenced by METHOD().
 {
     double dval;
     char *end;
     if (value)
     {
         errno = 0;
         dval = strtod(value, &end);
         if (errno == 0 && *end == 0 && end != value)
         {
             return dval;
         }
     }
     return def;
 }
int settings_value_as_int (char * value, int def) inline
Convert a string value returned by a key/value enumerator to an integer.
See Also
settings_t.create_key_value_enumerator()
settings_t.get_int()
Parameters
value the string value
def the default value, if value is NULL or invalid
Described in header
Definition at line 511 of file settings.c.
References end.
Referenced by METHOD(), and register_dh_mapping().
 {
     int intval;
     char *end;
     if (value)
     {
         errno = 0;
         intval = strtol(value, &end, 10);
         if (errno == 0 && *end == 0 && end != value)
         {
             return intval;
         }
     }
     return def;
 }
u_int32_t settings_value_as_time (char * value, u_int32_t def) inline
Convert a string value returned by a key/value enumerator to a time value.
See Also
settings_t.create_key_value_enumerator()
settings_t.get_time()
Parameters
value the string value
def the default value, if value is NULL or invalid
Described in header
Definition at line 600 of file settings.c.
Referenced by METHOD().
 {
     char *endptr;
     u_int32_t timeval;
     if (value)
     {
         errno = 0;
         timeval = strtoul(value, &endptr, 10);
         if (endptr == value)
         {
             return def;
         }
         if (errno == 0)
         {
             while (isspace(*endptr))
             {
                 endptr++;
             }
             switch (*endptr)
             {
                 case 'd':       /* time in days */
                     timeval *= 24 * 3600;
                     break;
                 case 'h':       /* time in hours */
                     timeval *= 3600;
                     break;
                 case 'm':       /* time in minutes */
                     timeval *= 60;
                     break;
                 case 's':       /* time in seconds */
                 case '\0':
                     break;
                 default:
                     return def;
             }
             return timeval;
         }
     }
     return def;
 }
u_int64_t settings_value_as_uint64 (char * value, u_int64_t def) inline
Convert a string value returned by a key/value enumerator to an u_int64_t.
See Also
settings_t.create_key_value_enumerator()
Parameters
value the string value
def the default value, if value is NULL or invalid
Described in header
Definition at line 543 of file settings.c.
References base, and end.
Referenced by START_TEST(), and tkm_spi_generator_register().
 {
     u_int64_t intval;
     char *end;
     int base = 10;
     if (value)
     {
         errno = 0;
         if (value[0] == '0' && value[1] == 'x')
         {   /* manually detect 0x prefix as we want to avoid octal encoding */
             base = 16;
         }
         intval = strtoull(value, &end, base);
         if (errno == 0 && *end == 0 && end != value)
         {
             return intval;
         }
     }
     return def;
 }