strongSwan: command
command
pki | swanctl
Classes
struct command_option_t
struct command_t
Macros
#define MAX_COMMANDS 14
#define MAX_OPTIONS 36
#define MAX_LINES 10
#define MAX_COMMANDS 21
#define MAX_OPTIONS 32
#define MAX_LINES 10
Typedefs
typedef struct command_t command_t
typedef struct command_option_t command_option_t
typedef enum command_type_t command_type_t
typedef struct command_t command_t
typedef struct command_option_t command_option_t
typedef enum
command_format_options_t command_format_options_t
Enumerations
enum command_format_options_t { COMMAND_FORMAT_NONE = 0, COMMAND_FORMAT_RAW = (1<<0), COMMAND_FORMAT_PRETTY = (1<<1), COMMAND_FORMAT_PEM = (1<<2) }
Functions
int command_getopt (char **arg)
void command_register (command_t command)
int command_dispatch (int argc, char *argv[])
int command_usage (char *error)
int command_usage (char *error,...)
Detailed Description
Macro Definition Documentation
#define MAX_COMMANDS 14
Maximum number of commands (+1).
Definition at line 27 of file pki/command.h.
Referenced by build_opts(), command_dispatch(), command_register(), and command_usage().
#define MAX_COMMANDS 21
Maximum number of commands (+1).
Definition at line 30 of file swanctl/command.h.
#define MAX_LINES 10
Maximum number of usage summary lines (+1)
Definition at line 37 of file pki/command.h.
#define MAX_LINES 10
Maximum number of usage summary lines (+1)
Definition at line 40 of file swanctl/command.h.
#define MAX_OPTIONS 36
Maximum number of options in a command (+3)
Definition at line 32 of file pki/command.h.
#define MAX_OPTIONS 32
Maximum number of options in a command (+3)
Definition at line 35 of file swanctl/command.h.
Typedef Documentation
typedef enum command_format_options_t command_format_options_t
Definition at line 44 of file swanctl/command.h.
typedef struct command_option_t command_option_t
Definition at line 40 of file pki/command.h.
typedef struct command_option_t command_option_t
Definition at line 43 of file swanctl/command.h.
typedef struct command_t command_t
Definition at line 39 of file pki/command.h.
typedef struct command_t command_t
Definition at line 42 of file swanctl/command.h.
typedef enum command_type_t command_type_t
Definition at line 41 of file pki/command.h.
Enumeration Type Documentation
enum command_format_options_t
Command format options
Enumerator
COMMAND_FORMAT_NONE
COMMAND_FORMAT_RAW
COMMAND_FORMAT_PRETTY
COMMAND_FORMAT_PEM
Definition at line 81 of file swanctl/command.h.
{
     COMMAND_FORMAT_NONE   = 0,
     COMMAND_FORMAT_RAW    = (1<<0),
     COMMAND_FORMAT_PRETTY = (1<<1),
     COMMAND_FORMAT_PEM    = (1<<2),
 };
Function Documentation
int command_dispatch (int c, char * v[])
Dispatch commands.
Definition at line 253 of file pki/command.c.
References active, argc, argv, build_opts(), c, command_t::call, call_command(), cleanup(), command_t::cmd, command_opts, command_optstring, command_register(), command_usage(), help(), help_idx, MAX_COMMANDS, options_create(), process_common_opts(), and registered.
Referenced by main().
 {
     int op, i;
     options = options_create();
     atexit(cleanup);
     active = help_idx = registered;
     argc = c;
     argv = v;
     command_register((command_t){help, 'h', "help", "show usage information"});
     build_opts();
     op = getopt_long(c, v, command_optstring, command_opts, NULL);
     for (i = 0; i < MAX_COMMANDS && cmds[i].cmd; i++)
     {
         if (cmds[i].op == op)
         {
             active = i;
             build_opts();
             return cmds[i].call();
         }
     }
     return command_usage(c > 1 ? "invalid operation" : NULL);
 }
int command_getopt (char ** arg)
Get the next option, as with getopt.
getopt_long wrapper
Get the next option, as with getopt.
getopt_long wrapper
Definition at line 110 of file pki/command.c.
References argc, argv, command_opts, command_optstring, dbg_default_set_level(), options_t::from, and TRUE.
Referenced by acert(), dn(), gen(), initiate(), issue(), keyid(), list_authorities(), list_certs(), list_conns(), list_pols(), list_pools(), list_sas(), load_all(), load_authorities(), load_conns(), load_creds(), load_pools(), logcmd(), manage_policy(), monitor_sas(), pkcs12(), pkcs7(), print(), pub(), reload_settings(), req(), self(), sign_crl(), stats(), terminate(), verify(), and version().
 {
     int op;
     while (TRUE)
     {
         op = getopt_long(argc, argv, command_optstring, command_opts, NULL);
         switch (op)
         {
             case '+':
                 if (!options->from(options, optarg, &argc, &argv, optind))
                 {
                     /* a error value */
                     return 255;
                 }
                 continue;
             case 'v':
                 dbg_default_set_level(atoi(optarg));
                 continue;
             default:
                 *arg = optarg;
                 return op;
         }
     }
 }
void command_register (command_t command)
Register a command.
Register a command
Register a command.
Register a command
Definition at line 139 of file pki/command.c.
References active, command_t::cmd, command, countof, fprintf, MAX_COMMANDS, name, command_t::options, and registered.
Referenced by __attribute__(), and command_dispatch().
 {
     int i;
     if (registered == MAX_COMMANDS)
     {
         fprintf(stderr, "unable to register command, please increase "
                 "MAX_COMMANDS\n");
         return;
     }
     cmds[registered] = command;
     /* append default options, but not to --help */
     if (!active)
     {
         for (i = 0; i < countof(cmds[registered].options) - 1; i++)
         {
             if (!cmds[registered].options[i].name)
             {
                 break;
             }
         }
         if (i > countof(cmds[registered].options) - 3)
         {
             fprintf(stderr, "command '%s' registered too many options, please "
                     "increase MAX_OPTIONS\n", command.cmd);
         }
         else
         {
             cmds[registered].options[i++] = (command_option_t) {
                 "debug",    'v', 1, "set debug level, default: 1"
             };
             cmds[registered].options[i++] = (command_option_t) {
                 "options",  '+', 1, "read command line options from file"
             };
         }
     }
     registered++;
 }
int command_usage (char * error)
Show usage information of active command.
Print usage text, with an optional error
Definition at line 182 of file pki/command.c.
References active, cmd, command_t::cmd, desc, fprintf, help_idx, lib, command_t::line, plugin_loader_t::loaded_plugins, MAX_COMMANDS, name, command_option_t::name, command_t::options, out, and library_t::plugins.
Referenced by acert(), command_dispatch(), dn(), export(), gen(), help(), initiate(), issue(), keyid(), list_authorities(), list_certs(), list_conns(), list_pols(), list_pools(), list_sas(), load_all(), load_authorities(), load_conns(), load_creds(), load_pools(), logcmd(), manage_policy(), monitor_sas(), pkcs12(), pkcs7(), print(), pub(), reload_settings(), req(), self(), sign_crl(), stats(), terminate(), verify(), and version().
 {
     FILE *out = stdout;
     int i;
     if (error)
     {
         out = stderr;
         fprintf(out, "Error: %s\n", error);
     }
     fprintf(out, "strongSwan %s PKI tool\n", VERSION);
     if (active == help_idx)
     {
         fprintf(out, "loaded plugins: %s\n",
                 lib->plugins->loaded_plugins(lib->plugins));
     }
     fprintf(out, "usage:\n");
     if (active == help_idx)
     {
         for (i = 0; i < MAX_COMMANDS && cmds[i].cmd; i++)
         {
             fprintf(out, "  pki --%-7s (-%c)  %s\n",
                     cmds[i].cmd, cmds[i].op, cmds[i].description);
         }
     }
     else
     {
         for (i = 0; cmds[active].line[i]; i++)
         {
             if (i == 0)
             {
                 fprintf(out, "  pki --%s %s\n",
                         cmds[active].cmd, cmds[active].line[i]);
             }
             else
             {
                 fprintf(out, "              %s\n", cmds[active].line[i]);
             }
         }
         for (i = 0; cmds[active].options[i].name; i++)
         {
             fprintf(out, "        --%-15s (-%c)  %s\n",
                     cmds[active].options[i].name, cmds[active].options[i].op,
                     cmds[active].options[i].desc);
         }
     }
     return error != NULL;
 }
int command_usage (char * error, ...)
Show usage information of active command.
Print usage text, with an optional error
Definition at line 186 of file swanctl/command.c.
References active, cmd, command_t::cmd, desc, fprintf, help_idx, lib, command_t::line, plugin_loader_t::loaded_plugins, MAX_COMMANDS, name, command_option_t::name, command_t::options, out, library_t::plugins, and vfprintf.
Referenced by call_command(), and command_dispatch().
 {
     va_list args;
     FILE *out = stdout;
     int i;
     if (error)
     {
         out = stderr;
         fprintf(out, "Error: ");
         va_start(args, error);
         vfprintf(out, error, args);
         va_end(args);
         fprintf(out, "\n");
     }
     fprintf(out, "strongSwan %s swanctl\n", VERSION);
     if (active == help_idx)
     {
         fprintf(out, "loaded plugins: %s\n",
                 lib->plugins->loaded_plugins(lib->plugins));
     }
     fprintf(out, "usage:\n");
     if (active == help_idx)
     {
         for (i = 0; i < MAX_COMMANDS && cmds[i].cmd; i++)
         {
             fprintf(out, "  swanctl --%-16s (-%c)  %s\n",
                     cmds[i].cmd, cmds[i].op, cmds[i].description);
         }
     }
     else
     {
         for (i = 0; cmds[active].line[i]; i++)
         {
             if (i == 0)
             {
                 fprintf(out, "  swanctl --%s %s\n",
                         cmds[active].cmd, cmds[active].line[i]);
             }
             else
             {
                 fprintf(out, "                 %s\n", cmds[active].line[i]);
             }
         }
         for (i = 0; cmds[active].options[i].name; i++)
         {
             fprintf(out, "           --%-15s (-%c)  %s\n",
                     cmds[active].options[i].name, cmds[active].options[i].op,
                     cmds[active].options[i].desc);
         }
     }
     return error != NULL;
 }