strongSwan: tncif_pa_subtypes
tncif_pa_subtypes
libtncif
Typedefs
typedef enum pa_subtype_ietf_t pa_subtype_ietf_t
typedef enum pa_subtype_tcg_t pa_subtype_tcg_t
typedef enum pa_subtype_pwg_t pa_subtype_pwg_t
typedef enum pa_subtype_fhh_t pa_subtype_fhh_t
typedef enum pa_subtype_ita_t pa_subtype_ita_t
Enumerations
enum pa_subtype_ietf_t {
PA_SUBTYPE_IETF_TESTING = 0x00, PA_SUBTYPE_IETF_OPERATING_SYSTEM = 0x01, PA_SUBTYPE_IETF_ANTI_VIRUS = 0x02, PA_SUBTYPE_IETF_ANTI_SPYWARE = 0x03,
PA_SUBTYPE_IETF_ANTI_MALWARE = 0x04, PA_SUBTYPE_IETF_FIREWALL = 0x05, PA_SUBTYPE_IETF_IDPS = 0x06, PA_SUBTYPE_IETF_VPN = 0x07,
PA_SUBTYPE_IETF_NEA_CLIENT = 0x08, PA_SUBTYPE_IETF_ANY = 0xff
}
enum pa_subtype_tcg_t { PA_SUBTYPE_TCG_PTS = 0x01, PA_SUBTYPE_TCG_SCAP = 0x02, PA_SUBTYPE_TCG_SWID = 0x03, PA_SUBTYPE_TCG_ANY = 0xff }
enum pa_subtype_pwg_t {
PA_SUBTYPE_PWG_HCD_TESTING = 0x00, PA_SUBTYPE_PWG_HCD_OTHER = 0x01, PA_SUBTYPE_PWG_HCD_UNKNOWN = 0x02, PA_SUBTYPE_PWG_HCD_CONSOLE = 0x04,
PA_SUBTYPE_PWG_HCD_SYSTEM = 0x05, PA_SUBTYPE_PWG_HCD_COVER = 0x06, PA_SUBTYPE_PWG_HCD_INPUT_TRAY = 0x08, PA_SUBTYPE_PWG_HCD_OUTPUT_TRAY = 0x09,
PA_SUBTYPE_PWG_HCD_MARKER = 0x0a, PA_SUBTYPE_PWG_HCD_MEDIA_PATH = 0x0d, PA_SUBTYPE_PWG_HCD_CHANNEL = 0x0e, PA_SUBTYPE_PWG_HCD_INTERPRETER = 0x0f,
PA_SUBTYPE_PWG_HCD_FINISHER = 0x1e, PA_SUBTYPE_PWG_HCD_INTERFACE = 0x28, PA_SUBTYPE_PWG_HCD_SCANNER = 0x32, PA_SUBTYPE_PWG_ANY = 0xff
}
enum pa_subtype_fhh_t {
PA_SUBTYPE_FHH_HOSTSCANNER = 0x30, PA_SUBTYPE_FHH_DUMMY = 0x31, PA_SUBTYPE_FHH_PLATID = 0x33, PA_SUBTYPE_FHH_ATTESTATION = 0x34,
PA_SUBTYPE_FHH_CLAMAV = 0x41, PA_SUBTYPE_FHH_ANY = 0xff
}
enum pa_subtype_ita_t { PA_SUBTYPE_ITA_TEST = 0x01, PA_SUBTYPE_ITA_ECHO = 0x02, PA_SUBTYPE_ITA_ANY = 0xff }
Functions
enum_name_t * get_pa_subtype_names (pen_t pen)
Variables
enum_name_t * pa_subtype_ietf_names
enum_name_t * pa_subtype_tcg_names
enum_name_t * pa_subtype_pwg_names
enum_name_t * pa_subtype_fhh_names
enum_name_t * pa_subtype_ita_names
Detailed Description
Typedef Documentation
typedef enum pa_subtype_fhh_t pa_subtype_fhh_t
Definition at line 27 of file tncif_pa_subtypes.h.
typedef enum pa_subtype_ietf_t pa_subtype_ietf_t
Definition at line 24 of file tncif_pa_subtypes.h.
typedef enum pa_subtype_ita_t pa_subtype_ita_t
Definition at line 28 of file tncif_pa_subtypes.h.
typedef enum pa_subtype_pwg_t pa_subtype_pwg_t
Definition at line 26 of file tncif_pa_subtypes.h.
typedef enum pa_subtype_tcg_t pa_subtype_tcg_t
Definition at line 25 of file tncif_pa_subtypes.h.
Enumeration Type Documentation
enum pa_subtype_fhh_t
PA-TNC FHH Subtypes
Enumerator
PA_SUBTYPE_FHH_HOSTSCANNER
PA_SUBTYPE_FHH_DUMMY
PA_SUBTYPE_FHH_PLATID
PA_SUBTYPE_FHH_ATTESTATION
PA_SUBTYPE_FHH_CLAMAV
PA_SUBTYPE_FHH_ANY
Definition at line 99 of file tncif_pa_subtypes.h.
{
     PA_SUBTYPE_FHH_HOSTSCANNER =        0x30,
     PA_SUBTYPE_FHH_DUMMY =              0x31,
     PA_SUBTYPE_FHH_PLATID =             0x33,
     PA_SUBTYPE_FHH_ATTESTATION =        0x34,
     PA_SUBTYPE_FHH_CLAMAV =             0x41,
     PA_SUBTYPE_FHH_ANY =                0xff
 };
enum pa_subtype_ietf_t
PA-TNC IETF Standard Subtypes as defined in section 3.5 of RFC 5792
Enumerator
PA_SUBTYPE_IETF_TESTING
PA_SUBTYPE_IETF_OPERATING_SYSTEM
PA_SUBTYPE_IETF_ANTI_VIRUS
PA_SUBTYPE_IETF_ANTI_SPYWARE
PA_SUBTYPE_IETF_ANTI_MALWARE
PA_SUBTYPE_IETF_FIREWALL
PA_SUBTYPE_IETF_IDPS
PA_SUBTYPE_IETF_VPN
PA_SUBTYPE_IETF_NEA_CLIENT
PA_SUBTYPE_IETF_ANY
Definition at line 36 of file tncif_pa_subtypes.h.
{
     PA_SUBTYPE_IETF_TESTING =           0x00,
     PA_SUBTYPE_IETF_OPERATING_SYSTEM =  0x01,
     PA_SUBTYPE_IETF_ANTI_VIRUS =        0x02,
     PA_SUBTYPE_IETF_ANTI_SPYWARE =      0x03,
     PA_SUBTYPE_IETF_ANTI_MALWARE =      0x04,
     PA_SUBTYPE_IETF_FIREWALL =          0x05,
     PA_SUBTYPE_IETF_IDPS =              0x06,
     PA_SUBTYPE_IETF_VPN =               0x07,
     PA_SUBTYPE_IETF_NEA_CLIENT =        0x08,
     PA_SUBTYPE_IETF_ANY =               0xff
 };
enum pa_subtype_ita_t
PA-TNC ITA-HSR Subtypes
Enumerator
PA_SUBTYPE_ITA_TEST
PA_SUBTYPE_ITA_ECHO
PA_SUBTYPE_ITA_ANY
Definition at line 116 of file tncif_pa_subtypes.h.
{
     PA_SUBTYPE_ITA_TEST =               0x01,
     PA_SUBTYPE_ITA_ECHO =               0x02,
     PA_SUBTYPE_ITA_ANY =                0xff
 };
enum pa_subtype_pwg_t
PA-TNC PWG Subtypes
Enumerator
PA_SUBTYPE_PWG_HCD_TESTING
PA_SUBTYPE_PWG_HCD_OTHER
PA_SUBTYPE_PWG_HCD_UNKNOWN
PA_SUBTYPE_PWG_HCD_CONSOLE
PA_SUBTYPE_PWG_HCD_SYSTEM
PA_SUBTYPE_PWG_HCD_COVER
PA_SUBTYPE_PWG_HCD_INPUT_TRAY
PA_SUBTYPE_PWG_HCD_OUTPUT_TRAY
PA_SUBTYPE_PWG_HCD_MARKER
PA_SUBTYPE_PWG_HCD_MEDIA_PATH
PA_SUBTYPE_PWG_HCD_CHANNEL
PA_SUBTYPE_PWG_HCD_INTERPRETER
PA_SUBTYPE_PWG_HCD_FINISHER
PA_SUBTYPE_PWG_HCD_INTERFACE
PA_SUBTYPE_PWG_HCD_SCANNER
PA_SUBTYPE_PWG_ANY
Definition at line 72 of file tncif_pa_subtypes.h.
{
     PA_SUBTYPE_PWG_HCD_TESTING =        0x00,
     PA_SUBTYPE_PWG_HCD_OTHER =          0x01,
     PA_SUBTYPE_PWG_HCD_UNKNOWN =        0x02,
     PA_SUBTYPE_PWG_HCD_CONSOLE =        0x04,
     PA_SUBTYPE_PWG_HCD_SYSTEM =         0x05,
     PA_SUBTYPE_PWG_HCD_COVER =          0x06,
     PA_SUBTYPE_PWG_HCD_INPUT_TRAY =     0x08,
     PA_SUBTYPE_PWG_HCD_OUTPUT_TRAY =    0x09,
     PA_SUBTYPE_PWG_HCD_MARKER =         0x0a,
     PA_SUBTYPE_PWG_HCD_MEDIA_PATH =     0x0d,
     PA_SUBTYPE_PWG_HCD_CHANNEL =        0x0e,
     PA_SUBTYPE_PWG_HCD_INTERPRETER =    0x0f,
     PA_SUBTYPE_PWG_HCD_FINISHER =       0x1e,
     PA_SUBTYPE_PWG_HCD_INTERFACE =      0x28,
     PA_SUBTYPE_PWG_HCD_SCANNER =        0x32,
     PA_SUBTYPE_PWG_ANY =                0xff
 };
enum pa_subtype_tcg_t
PA-TNC TCG Subtypes
Enumerator
PA_SUBTYPE_TCG_PTS
PA_SUBTYPE_TCG_SCAP
PA_SUBTYPE_TCG_SWID
PA_SUBTYPE_TCG_ANY
Definition at line 57 of file tncif_pa_subtypes.h.
{
     PA_SUBTYPE_TCG_PTS =                0x01,
     PA_SUBTYPE_TCG_SCAP =               0x02,
     PA_SUBTYPE_TCG_SWID =               0x03,
     PA_SUBTYPE_TCG_ANY =                0xff
 };
Function Documentation
enum_name_t* get_pa_subtype_names (pen_t pen)
Return the pa_subtype_names for a given PEN
Parameters
pen Private Enterprise Number (PEN)
Returns
pa_subtype_names if found, NULL else
See header
Definition at line 132 of file tncif_pa_subtypes.c.
References pa_subtype_fhh_names, pa_subtype_ietf_names, pa_subtype_ita_names, pa_subtype_pwg_names, pa_subtype_tcg_names, PEN_FHH, PEN_IETF, PEN_ITA, PEN_PWG, and PEN_TCG.
Referenced by handle_ietf_message(), handle_message(), METHOD(), and receive_msg().
 {
     switch (pen)
     {
         case PEN_IETF:
             return pa_subtype_ietf_names;
         case PEN_TCG:
             return pa_subtype_tcg_names;
         case PEN_PWG:
             return pa_subtype_pwg_names;
         case PEN_FHH:
             return pa_subtype_fhh_names;
         case PEN_ITA:
             return pa_subtype_ita_names;
         default:
             break;
     }
     return NULL;
 }
Variable Documentation
enum_name_t* pa_subtype_fhh_names
enum name for pa_subtype_fhh_t.
Referenced by get_pa_subtype_names().
enum_name_t* pa_subtype_ietf_names
enum name for pa_subtype_ietf_t.
Referenced by get_pa_subtype_names().
enum_name_t* pa_subtype_ita_names
enum name for pa_subtype_ita_t.
Referenced by get_pa_subtype_names().
enum_name_t* pa_subtype_pwg_names
enum name for pa_subtype_pwg_t.
Referenced by get_pa_subtype_names(), and TNC_IMC_BeginHandshake().
enum_name_t* pa_subtype_tcg_names
enum name for pa_subtype_tcg_t.
Referenced by get_pa_subtype_names().