strongSwan: byteorder
byteorder
utils
Macros
#define BITFIELD2(t, a, b,...) struct { t a; t b; __VA_ARGS__}
#define BITFIELD3(t, a, b, c,...) struct { t a; t b; t c; __VA_ARGS__}
#define BITFIELD4(t, a, b, c, d,...) struct { t a; t b; t c; t d; __VA_ARGS__}
#define BITFIELD5(t, a, b, c, d, e,...) struct { t a; t b; t c; t d; t e; __VA_ARGS__}
Functions
static void htoun16 (void *network, u_int16_t host)
static void htoun32 (void *network, u_int32_t host)
static void htoun64 (void *network, u_int64_t host)
static u_int16_t untoh16 (void *network)
static u_int32_t untoh32 (void *network)
static u_int64_t untoh64 (void *network)
Detailed Description
Macro Definition Documentation
#define BITFIELD2 (t, a, b, ...) struct { t a; t b; __VA_ARGS__}
Architecture independent bitfield definition helpers (at least with GCC).
Defines a bitfield with a type t and a fixed size of bitfield members, e.g.: BITFIELD2(u_int8_t, low: 4, high: 4,) flags; The member defined first placed at bit 0.
Definition at line 36 of file byteorder.h.
#define BITFIELD3 (t, a, b, c, ...) struct { t a; t b; t c; __VA_ARGS__}
Definition at line 37 of file byteorder.h.
#define BITFIELD4 (t, a, b, c, d, ...) struct { t a; t b; t c; t d; __VA_ARGS__}
Definition at line 38 of file byteorder.h.
Referenced by __attribute__().
#define BITFIELD5 (t, a, b, c, d, e, ...) struct { t a; t b; t c; t d; t e; __VA_ARGS__}
Definition at line 39 of file byteorder.h.
Function Documentation
static void htoun16 (void * network, u_int16_t host) inline static
Write a 16-bit host order value in network order to an unaligned address.
Parameters
host host order 16-bit value
network unaligned address to write network order value to
Definition at line 53 of file byteorder.h.
References memcpy.
Referenced by bliss_utils_generate_c(), build_pkt(), build_pub(), create_ack(), create_icv(), eap_payload_create_code(), eap_payload_create_nak(), icv_header(), METHOD(), open_tcp_socket(), open_udp_socket(), process_key_exchange_encrypted(), send_key_exchange_encrypt(), and START_TEST().
 {
     char *unaligned = (char*)network;
     host = htons(host);
     memcpy(unaligned, &host, sizeof(host));
 }
static void htoun32 (void * network, u_int32_t host) inline static
Write a 32-bit host order value in network order to an unaligned address.
Parameters
host host order 32-bit value
network unaligned address to write network order value to
Definition at line 67 of file byteorder.h.
References memcpy.
Referenced by build_b0(), build_ctr(), build_pkt(), create_icv(), create_j(), finalize_message(), have_vips_from_pool(), METHOD(), open_tcp_socket(), open_udp_socket(), pbkdf2(), process_client_hello(), seg_env_create_from_data(), send_client_hello(), send_response(), START_TEST(), tcg_seg_attr_seg_env_create(), and uint_attribute().
 {
     char *unaligned = (char*)network;
     host = htonl(host);
     memcpy((char*)unaligned, &host, sizeof(host));
 }
static void htoun64 (void * network, u_int64_t host) inline static
Write a 64-bit host order value in network order to an unaligned address.
Parameters
host host order 64-bit value
network unaligned address to write network order value to
Definition at line 81 of file byteorder.h.
References memcpy.
Referenced by icv_tailer(), METHOD(), START_TEST(), and transform_attribute_create_value().
 {
     char *unaligned = (char*)network;
 #ifdef be64toh
     host = htobe64(host);
     memcpy((char*)unaligned, &host, sizeof(host));
 #else
     u_int32_t high_part, low_part;
     high_part = host >> 32;
     high_part = htonl(high_part);
     low_part  = host & 0xFFFFFFFFLL;
     low_part  = htonl(low_part);
     memcpy(unaligned, &high_part, sizeof(high_part));
     unaligned += sizeof(high_part);
     memcpy(unaligned, &low_part, sizeof(low_part));
 #endif
 }
static u_int16_t untoh16 (void * network) inline static
Read a 16-bit value in network order from an unaligned address to host order.
Parameters
network unaligned address to read network order value from
Returns
host order value
Definition at line 108 of file byteorder.h.
References memcpy.
Referenced by chunk_internet_checksum_inc(), ip_packet_create(), METHOD(), parse(), process_client_hello(), process_key_exchange_encrypted(), process_pkt(), read_uint16_internal(), and START_TEST().
 {
     char *unaligned = (char*)network;
     u_int16_t tmp;
     memcpy(&tmp, unaligned, sizeof(tmp));
     return ntohs(tmp);
 }
static u_int32_t untoh32 (void * network) inline static
Read a 32-bit value in network order from an unaligned address to host order.
Parameters
network unaligned address to read network order value from
Returns
host order value
Definition at line 123 of file byteorder.h.
References memcpy.
Referenced by add_tunnel_provider(), addr2ts(), do_read(), extract_type(), get_string(), get_uint_attribute(), have_vips_from_pool(), host2address6(), hosts2traffic(), is_attribute_selected(), is_known_vid(), mem_pool_create_range(), METHOD(), network_id_diff(), prefix2mask(), print_host(), process_coa(), process_dpd(), process_filter_id(), process_pkt(), process_timeout(), read_uint24_internal(), read_uint32_internal(), START_TEST(), and ts2condition().
 {
     char *unaligned = (char*)network;
     u_int32_t tmp;
     memcpy(&tmp, unaligned, sizeof(tmp));
     return ntohl(tmp);
 }
static u_int64_t untoh64 (void * network) inline static
Read a 64-bit value in network order from an unaligned address to host order.
Parameters
network unaligned address to read network order value from
Returns
host order value
Definition at line 138 of file byteorder.h.
References memcpy.
Referenced by METHOD(), read_uint64_internal(), and START_TEST().
 {
     char *unaligned = (char*)network;
 #ifdef be64toh
     u_int64_t tmp;
     memcpy(&tmp, unaligned, sizeof(tmp));
     return be64toh(tmp);
 #else
     u_int32_t high_part, low_part;
     memcpy(&high_part, unaligned, sizeof(high_part));
     unaligned += sizeof(high_part);
     memcpy(&low_part, unaligned, sizeof(low_part));
     high_part = ntohl(high_part);
     low_part  = ntohl(low_part);
     return (((u_int64_t)high_part) << 32) + low_part;
 #endif
 }