strongSwan: unencrypted_notify.c File Reference
unencrypted_notify.c File Reference
#include "hook.h"
Classes
struct private_unencrypted_notify_t
Typedefs
typedef struct
private_unencrypted_notify_t private_unencrypted_notify_t
Functions
METHOD (listener_t, ike_updown, bool, private_unencrypted_notify_t *this, ike_sa_t *ike_sa, bool up)
METHOD (hook_t, destroy, void, private_unencrypted_notify_t *this)
hook_t * unencrypted_notify_hook_create (char *name)
Typedef Documentation
typedef struct private_unencrypted_notify_t private_unencrypted_notify_t
Definition at line 18 of file unencrypted_notify.c.
Function Documentation
METHOD (listener_t , ike_updown , bool , private_unencrypted_notify_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 56 of file unencrypted_notify.c.
References message_t::add_payload, charon, chunk_clone, chunk_create(), chunk_empty, chunk_from_hex(), chunk_skip(), host_t::clone, data, DBG1, DBG_CFG, message_t::destroy, enum_from_name, free(), message_t::generate, ike_sa_t::get_id, ike_sa_t::get_my_host, ike_sa_t::get_other_host, host, IKEV2_MAJOR_VERSION, IKEV2_MINOR_VERSION, INFORMATIONAL, chunk_t::len, message_create(), notify(), notify_payload_create_from_protocol_and_type(), notify_type_names, notify_payload_t::payload_interface, PLV2_NOTIFY, PROTO_ESP, PROTO_IKE, chunk_t::ptr, sender_t::send, daemon_t::sender, message_t::set_destination, message_t::set_exchange_type, message_t::set_ike_sa_id, message_t::set_message_id, notify_payload_t::set_notification_data, message_t::set_request, message_t::set_source, notify_payload_t::set_spi, strncaseeq(), SUCCESS, TRUE, and type.
 {
     if (up)
     {
         message_t *message;
         host_t *host;
         notify_type_t type;
         notify_payload_t *notify;
         chunk_t data = chunk_empty;
         packet_t *packet;
         type = atoi(this->type);
         if (!type)
         {
             if (!enum_from_name(notify_type_names, this->type, &type))
             {
                 DBG1(DBG_CFG, "unknown notify: '%s', skipped", this->type);
                 return TRUE;
             }
         }
         if (strncaseeq(this->data, "0x", 2))
         {
             data = chunk_skip(chunk_create(this->data, strlen(this->data)), 2);
             data = chunk_from_hex(data, NULL);
         }
         else if (strlen(this->data))
         {
             data = chunk_clone(chunk_create(this->data, strlen(this->data)));
         }
         notify = notify_payload_create_from_protocol_and_type(PLV2_NOTIFY,
                                     this->esp ? PROTO_ESP : PROTO_IKE, type);
         notify->set_spi(notify, this->spi);
         if (data.len)
         {
             notify->set_notification_data(notify, data);
             free(data.ptr);
         }
         DBG1(DBG_CFG, "injecting unencrypted INFORMATIONAL message");
         message = message_create(IKEV2_MAJOR_VERSION, IKEV2_MINOR_VERSION);
         message->set_message_id(message, this->id);
         message->set_ike_sa_id(message, ike_sa->get_id(ike_sa));
         message->set_exchange_type(message, INFORMATIONAL);
         message->set_request(message, TRUE);
         host = ike_sa->get_my_host(ike_sa);
         message->set_source(message, host->clone(host));
         host = ike_sa->get_other_host(ike_sa);
         message->set_destination(message, host->clone(host));
         message->add_payload(message, &notify->payload_interface);
         if (message->generate(message, NULL, &packet) != SUCCESS)
         {
             DBG1(DBG_CFG, "generating message failed");
             message->destroy(message);
             return TRUE;
         }
         message->destroy(message);
         charon->sender->send(charon->sender, packet);
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_unencrypted_notify_t * this)
Definition at line 119 of file unencrypted_notify.c.
References free().
 {
     free(this);
 }
hook_t* unencrypted_notify_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 128 of file unencrypted_notify.c.
References conftest, FALSE, settings_t::get_bool, settings_t::get_int, settings_t::get_str, INIT, and conftest_t::test.
 {
     private_unencrypted_notify_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .ike_updown = _ike_updown,
             },
             .destroy = _destroy,
         },
         .id = conftest->test->get_int(conftest->test,
                                         "hooks.%s.id", 2, name),
         .type = conftest->test->get_str(conftest->test,
                                         "hooks.%s.type", "", name),
         .data = conftest->test->get_str(conftest->test,
                                         "hooks.%s.data", "", name),
         .spi = conftest->test->get_int(conftest->test,
                                         "hooks.%s.spi", 0, name),
         .esp = conftest->test->get_bool(conftest->test,
                                         "hooks.%s.esp", FALSE, name),
     );
     return &this->hook;
 }