strongSwan: conf_parser.c File Reference
conf_parser.c File Reference
#include "conf_parser.h"
#include <collections/array.h>
#include <collections/hashtable.h>
Classes
struct private_conf_parser_t
struct setting_t
struct section_t
struct section_dictionary_t
struct dictionary_enumerator_t
Typedefs
typedef struct
private_conf_parser_t private_conf_parser_t
typedef struct section_t section_t
Functions
bool conf_parser_parse_file (conf_parser_t *this, char *file)
int setting_find (const void *a, const void *b)
int setting_sort (const void *a, const void *b, void *user)
static void setting_destroy (setting_t *this)
static section_t * section_create (char *name)
static void section_destroy (section_t *this)
METHOD (enumerator_t, dictionary_enumerate, bool, dictionary_enumerator_t *this, char **key, char **value)
METHOD (enumerator_t, dictionary_enumerator_destroy, void, dictionary_enumerator_t *this)
METHOD (dictionary_t, dictionary_create_enumerator, enumerator_t *, section_dictionary_t *this)
METHOD (dictionary_t, dictionary_get, void *, section_dictionary_t *this, const void *key)
METHOD (dictionary_t, dictionary_destroy, void, section_dictionary_t *this)
static dictionary_t * section_dictionary_create (private_conf_parser_t *parser, section_t *section)
static bool conn_filter (void *unused, section_t **section, char **name)
static bool ca_filter (void *unused, void *key, char **name, section_t **section)
METHOD (conf_parser_t, get_sections, enumerator_t *, private_conf_parser_t *this, conf_parser_section_t type)
METHOD (conf_parser_t, get_section, dictionary_t *, private_conf_parser_t *this, conf_parser_section_t type, char *name)
METHOD (conf_parser_t, add_section, bool, private_conf_parser_t *this, conf_parser_section_t type, char *name)
METHOD (conf_parser_t, add_setting, void, private_conf_parser_t *this, char *key, char *value)
static bool is_contained_in (array_t *arr, section_t *section)
static bool resolve_also_single (hashtable_t *sections, section_t *section, section_t *def, array_t *stack)
static bool resolve_also (hashtable_t *sections)
METHOD (conf_parser_t, parse, bool, private_conf_parser_t *this)
METHOD (conf_parser_t, destroy, void, private_conf_parser_t *this)
conf_parser_t * conf_parser_create (const char *file)
Typedef Documentation
typedef struct private_conf_parser_t private_conf_parser_t
Definition at line 26 of file conf_parser.c.
typedef struct section_t section_t
Definition at line 27 of file conf_parser.c.
Function Documentation
static bool ca_filter (void * unused, void * key, char ** name, section_t ** section) static
Definition at line 303 of file conf_parser.c.
References FALSE, streq(), and TRUE.
Referenced by METHOD().
 {
     if (streq((*section)->name, "%default"))
     {
         return FALSE;
     }
     *name = (*section)->name;
     return TRUE;
 }
bool conf_parser_parse_file (conf_parser_t * this, char * name)
Provided by the generated parser
Parse the given file
Definition at line 1671 of file starter/parser/parser.c.
References conf_parser_get_lineno(), conf_parser_lex_destroy(), conf_parser_lex_init_extra(), conf_parser_open_next_file(), conf_parser_set_debug(), DBG1, DBG_CFG, parser_helper_t::destroy, FALSE, parser_helper_t::file_include, parser_helper_t::get_lineno, parser_helper_create(), parser_helper_t::scanner, yydebug, and yyparse.
Referenced by METHOD().
 {
     parser_helper_t *helper;
     bool success = FALSE;
     helper = parser_helper_create(this);
     helper->get_lineno = conf_parser_get_lineno;
     if (conf_parser_lex_init_extra(helper, &helper->scanner) != 0)
     {
         helper->destroy(helper);
         return FALSE;
     }
     helper->file_include(helper, name);
     if (!conf_parser_open_next_file(helper))
     {
         DBG1(DBG_CFG, "failed to open config file '%s'", name);
     }
     else
     {
         if (getenv("DEBUG_CONF_PARSER"))
         {
             yydebug = 1;
             conf_parser_set_debug(1, helper->scanner);
         }
         success = yyparse(helper) == 0;
         if (!success)
         {
             DBG1(DBG_CFG, "invalid config file '%s'", name);
         }
     }
     conf_parser_lex_destroy(helper->scanner);
     helper->destroy(helper);
     return success;
 }
static bool conn_filter (void * unused, section_t ** section, char ** name) static
Definition at line 293 of file conf_parser.c.
References FALSE, streq(), and TRUE.
Referenced by METHOD().
 {
     if (streq((*section)->name, "%default"))
     {
         return FALSE;
     }
     *name = (*section)->name;
     return TRUE;
 }
static bool is_contained_in (array_t * arr, section_t * section) static
Check if the given section is contained in the given array. The search starts at the given index.
Definition at line 453 of file conf_parser.c.
References array_count(), array_get(), FALSE, section_t::name, streq(), and TRUE.
Referenced by resolve_also_single().
 {
     section_t *current;
     int i;
     for (i = 0; i < array_count(arr); i++)
     {
         array_get(arr, i, &current);
         if (streq(section->name, current->name))
         {
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (enumerator_t , dictionary_enumerate , bool , dictionary_enumerator_t * this, char ** key, char ** value)
Definition at line 160 of file conf_parser.c.
References array_create_enumerator(), DESTROY_IF, FALSE, setting_t::key, settings, section_t::settings, TRUE, and setting_t::value.
 {
     setting_t *setting;
     section_t *parent;
     while (TRUE)
     {
         if (this->settings &&
             this->settings->enumerate(this->settings, &setting))
         {
             if (this->seen->get(this->seen, setting->key))
             {
                 continue;
             }
             this->seen->put(this->seen, setting->key, setting->key);
             if (!setting->value)
             {
                 continue;
             }
             if (key)
             {
                 *key = setting->key;
             }
             if (value)
             {
                 *value = setting->value;
             }
             return TRUE;
         }
         DESTROY_IF(this->settings);
         this->settings = NULL;
         if (this->parents &&
             this->parents->enumerate(this->parents, &parent))
         {
             if (parent->settings)
             {
                 this->settings = array_create_enumerator(parent->settings);
             }
             continue;
         }
         DESTROY_IF(this->parents);
         this->parents = NULL;
         break;
     }
     return FALSE;
 }
METHOD (enumerator_t , dictionary_enumerator_destroy , void , dictionary_enumerator_t * this)
Definition at line 208 of file conf_parser.c.
References DESTROY_IF, free(), and settings.
 {
     DESTROY_IF(this->settings);
     DESTROY_IF(this->parents);
     this->seen->destroy(this->seen);
     free(this);
 }
METHOD (dictionary_t , dictionary_create_enumerator , enumerator_t * , section_dictionary_t * this)
Definition at line 217 of file conf_parser.c.
References array_create_enumerator(), destroy(), hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), INIT, dictionary_enumerator_t::parents, dictionary_enumerator_t::public, section, and dictionary_enumerator_t::settings.
 {
     dictionary_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_dictionary_enumerate,
             .destroy = _dictionary_enumerator_destroy,
         },
         .seen = hashtable_create(hashtable_hash_str, hashtable_equals_str, 8),
     );
     if (this->section->settings)
     {
         enumerator->settings = array_create_enumerator(this->section->settings);
     }
     if (this->section->parents)
     {
         enumerator->parents = array_create_enumerator(this->section->parents);
     }
     return &enumerator->public;
 }
METHOD (dictionary_t , dictionary_get , void * , section_dictionary_t * this, const void * key)
Definition at line 240 of file conf_parser.c.
References array_bsearch(), array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, section_t::parents, section, setting_find(), section_t::settings, setting_t::value, and value.
 {
     enumerator_t *parents;
     section_t *section;
     setting_t *setting;
     char *value = NULL;
     section = this->section;
     if (array_bsearch(section->settings, key, setting_find, &setting) != -1)
     {
         return setting->value;
     }
     parents = array_create_enumerator(section->parents);
     while (parents->enumerate(parents, &section))
     {
         if (array_bsearch(section->settings, key, setting_find, &setting) != -1)
         {
             value = setting->value;
             break;
         }
     }
     parents->destroy(parents);
     return value;
 }
METHOD (dictionary_t , dictionary_destroy , void , section_dictionary_t * this)
Definition at line 266 of file conf_parser.c.
References conf_parser_t::destroy, free(), and parser.
 {
     this->parser->public.destroy(&this->parser->public);
     free(this);
 }
METHOD (conf_parser_t , get_sections , enumerator_t * , private_conf_parser_t * this, conf_parser_section_t type)
Definition at line 313 of file conf_parser.c.
References array_create_enumerator(), ca_filter(), CONF_PARSER_CA, CONF_PARSER_CONFIG_SETUP, CONF_PARSER_CONN, conn_filter(), enumerator_create_empty(), and enumerator_create_filter().
 {
     switch (type)
     {
         case CONF_PARSER_CONN:
             return enumerator_create_filter(
                         array_create_enumerator(this->conns_order),
                         (void*)conn_filter, NULL, NULL);
         case CONF_PARSER_CA:
             return enumerator_create_filter(
                         this->cas->create_enumerator(this->cas),
                         (void*)ca_filter, NULL, NULL);
         case CONF_PARSER_CONFIG_SETUP:
         default:
             return enumerator_create_empty();
     }
 }
METHOD (conf_parser_t , get_section , dictionary_t * , private_conf_parser_t * this, conf_parser_section_t type, char * name)
Definition at line 332 of file conf_parser.c.
References CONF_PARSER_CA, CONF_PARSER_CONFIG_SETUP, CONF_PARSER_CONN, section, section_dictionary_create(), and streq().
 {
     section_t *section = NULL;
     if (name && streq(name, "%default"))
     {
         return NULL;
     }
     switch (type)
     {
         case CONF_PARSER_CONFIG_SETUP:
             section = this->config_setup;
             break;
         case CONF_PARSER_CONN:
             section = this->conns->get(this->conns, name);
             break;
         case CONF_PARSER_CA:
             section = this->cas->get(this->cas, name);
             break;
         default:
             break;
     }
     return section ? section_dictionary_create(this, section) : NULL;
 }
METHOD (conf_parser_t , add_section , bool , private_conf_parser_t * this, conf_parser_section_t type, char * name)
Definition at line 358 of file conf_parser.c.
References array_insert(), ARRAY_TAIL, CONF_PARSER_CA, CONF_PARSER_CONFIG_SETUP, CONF_PARSER_CONN, FALSE, free(), hashtable_t::get, hashtable_t::put, section, section_create(), and TRUE.
 {
     hashtable_t *sections = this->conns;
     array_t *order = this->conns_order;
     section_t *section = NULL;
     bool exists = FALSE;
     if (!this->parsing)
     {
         free(name);
         return exists;
     }
     switch (type)
     {
         case CONF_PARSER_CONFIG_SETUP:
             section = this->config_setup;
             /* we don't expect a name, but just in case */
             free(name);
             break;
         case CONF_PARSER_CA:
             sections = this->cas;
             order = NULL;
             /* fall-through */
         case CONF_PARSER_CONN:
             section = sections->get(sections, name);
             if (!section)
             {
                 section = section_create(name);
                 sections->put(sections, name, section);
                 if (order)
                 {
                     array_insert(order, ARRAY_TAIL, section);
                 }
             }
             else
             {
                 exists = TRUE;
                 free(name);
             }
             break;
     }
     this->current_section = section;
     return exists;
 }
METHOD (conf_parser_t , add_setting , void , private_conf_parser_t * this, char * key, char * value)
Definition at line 405 of file conf_parser.c.
References section_t::also, array_bsearch(), ARRAY_HEAD, array_insert_create(), array_sort(), ARRAY_TAIL, free(), INIT, section, setting_find(), setting_sort(), section_t::settings, streq(), setting_t::value, and value.
 {
     section_t *section = this->current_section;
     setting_t *setting;
     if (!this->parsing || !this->current_section)
     {
         free(key);
         free(value);
         return;
     }
     if (streq(key, "also"))
     {
         if (!value || !strlen(value) || streq(value, "%default"))
         {   /* we require a name, but all sections inherit from %default */
             free(key);
             free(value);
             return;
         }
         INIT(setting,
             .key = key,
             .value = value,
         );
         array_insert_create(&section->also, ARRAY_HEAD, setting);
         return;
     }
     if (array_bsearch(section->settings, key, setting_find, &setting) == -1)
     {
         INIT(setting,
             .key = key,
             .value = value,
         );
         array_insert_create(&section->settings, ARRAY_TAIL, setting);
         array_sort(section->settings, setting_sort, NULL);
     }
     else
     {
         free(setting->value);
         setting->value = value;
         free(key);
     }
 }
METHOD (conf_parser_t , parse , bool , private_conf_parser_t * this)
Definition at line 611 of file conf_parser.c.
References conf_parser_parse_file(), FALSE, resolve_also(), and TRUE.
 {
     bool success;
     if (!this->file)
     {   /* no file, lets assume this is OK */
         return TRUE;
     }
     this->parsing = TRUE;
     success = conf_parser_parse_file(&this->public, this->file);
     this->parsing = FALSE;
     return success && resolve_also(this->conns) && resolve_also(this->cas);
 }
METHOD (conf_parser_t , destroy , void , private_conf_parser_t * this)
Definition at line 626 of file conf_parser.c.
References array_destroy(), free(), ref_put(), and section_destroy().
 {
     if (ref_put(&this->ref))
     {
         this->cas->destroy_function(this->cas, (void*)section_destroy);
         this->conns->destroy_function(this->conns, (void*)section_destroy);
         section_destroy(this->config_setup);
         array_destroy(this->conns_order);
         free(this->file);
         free(this);
     }
 }
static bool resolve_also (hashtable_t * sections) static
Resolve also= statements. The functions returns TRUE if everything is fine, or FALSE if either a referenced section does not exist, or if the section inheritance can't be determined properly (e.g. if there are loops or if a section inherits from multiple sections - perhaps over several levels - in an ambiguous way).
Definition at line 583 of file conf_parser.c.
References array_create(), array_destroy(), hashtable_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, hashtable_t::get, section_t::parents, resolve_also_single(), section, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     section_t *def, *section;
     array_t *stack;
     bool success = TRUE;
     stack = array_create(0, 0);
     def = sections->get(sections, "%default");
     if (def)
     {   /* the default section is the only one with an empty parents list */
         def->parents = array_create(0, 0);
     }
     enumerator = sections->create_enumerator(sections);
     while (enumerator->enumerate(enumerator, NULL, &section))
     {
         if (section->parents)
         {   /* already determined */
             continue;
         }
         success = resolve_also_single(sections, section, def, stack) && success;
     }
     enumerator->destroy(enumerator);
     array_destroy(stack);
     return success;
 }
static bool resolve_also_single (hashtable_t * sections, section_t * section, section_t * def, array_t * stack) static
This algorithm to linearize sections uses a bottom-first depth-first semantic, with an additional elimination step that removes all but the last occurrence of each section.
Consider this configuration:
conn A conn B also=A conn C also=A conn D also=C also=B
The linearization would yield D B A C A, which gets reduced to D B C A.
Ambiguous configurations are handled pragmatically.
Consider the following configuration:
conn A conn B conn C also=A also=B conn D also=B also=A conn E also=C also=D
It is ambiguous because D and C include the same two sections but in a different order.
The linearization would yield E D A B C B A which gets reduced to E D C B A.
Definition at line 508 of file conf_parser.c.
References section_t::also, array_count(), array_create(), array_create_enumerator(), array_destroy(), array_get(), ARRAY_HEAD, array_insert(), array_insert_create(), array_remove(), array_remove_at(), ARRAY_TAIL, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, hashtable_t::get, is_contained_in(), section_t::name, section_t::parents, setting_destroy(), TRUE, and setting_t::value.
Referenced by resolve_also().
 {
     enumerator_t *enumerator;
     array_t *parents;
     section_t *parent, *grandparent;
     setting_t *also;
     bool success = TRUE;
     int i;
     array_insert(stack, ARRAY_HEAD, section);
     parents = array_create(0, 0);
     enumerator = array_create_enumerator(section->also);
     while (enumerator->enumerate(enumerator, &also))
     {
         parent = sections->get(sections, also->value);
         if (!parent || is_contained_in(stack, parent))
         {
             if (!parent)
             {
                 DBG1(DBG_CFG, "section '%s' referenced in section '%s' not "
                      "found", also->value, section->name);
             }
             else
             {
                 DBG1(DBG_CFG, "section '%s' referenced in section '%s' causes "
                      "a loop", parent->name, section->name);
             }
             array_remove_at(section->also, enumerator);
             setting_destroy(also);
             success = FALSE;
             continue;
         }
         if (!parent->parents)
         {
             if (!resolve_also_single(sections, parent, def, stack))
             {
                 success = FALSE;
                 continue;
             }
         }
         /* add the grandparents and the parent to the list */
         array_insert(parents, ARRAY_TAIL, parent);
         for (i = 0; i < array_count(parent->parents); i++)
         {
             array_get(parent->parents, i, &grandparent);
             array_insert(parents, ARRAY_TAIL, grandparent);
         }
     }
     enumerator->destroy(enumerator);
     array_remove(stack, ARRAY_HEAD, NULL);
     if (success && def && !array_count(parents))
     {
         array_insert(parents, ARRAY_TAIL, def);
     }
     while (success && array_remove(parents, ARRAY_HEAD, &parent))
     {
         if (!is_contained_in(parents, parent))
         {   /* last occurrence of this section */
             array_insert_create(&section->parents, ARRAY_TAIL, parent);
         }
     }
     array_destroy(parents);
     return success;
 }
static section_t* section_create (char * name) static
Definition at line 121 of file conf_parser.c.
References INIT.
Referenced by conf_parser_create(), and METHOD().
 {
     section_t *this;
     INIT(this,
         .name = name,
     );
     return this;
 }
static void section_destroy (section_t * this) static
Definition at line 131 of file conf_parser.c.
References array_destroy(), array_destroy_function(), free(), name, setting_destroy(), and settings.
Referenced by METHOD().
 {
     array_destroy_function(this->settings, (void*)setting_destroy, NULL);
     array_destroy_function(this->also, (void*)setting_destroy, NULL);
     array_destroy(this->parents);
     free(this->name);
     free(this);
 }
static dictionary_t* section_dictionary_create (private_conf_parser_t * parser, section_t * section) static
Definition at line 273 of file conf_parser.c.
References INIT, parser, private_conf_parser_t::ref, ref_get(), and section.
Referenced by METHOD().
 {
     section_dictionary_t *this;
     INIT(this,
         .public = {
             .create_enumerator = _dictionary_create_enumerator,
             .get = _dictionary_get,
             .destroy = _dictionary_destroy,
         },
         .parser = parser,
         .section = section,
     );
     ref_get(&parser->ref);
     return &this->public;
 }
static void setting_destroy (setting_t * this) static
Definition at line 100 of file conf_parser.c.
References free(), key, and value.
Referenced by resolve_also_single(), and section_destroy().
 {
     free(this->key);
     free(this->value);
     free(this);
 }
int setting_find (const void * a, const void * b)
Definition at line 87 of file conf_parser.c.
References a, b, setting_t::key, and key.
Referenced by METHOD().
 {
     const char *key = a;
     const setting_t *setting = b;
     return strcmp(key, setting->key);
 }
int setting_sort (const void * a, const void * b, void * user)
Definition at line 94 of file conf_parser.c.
References a, b, setting_t::key, and sa.
Referenced by METHOD().
 {
     const setting_t *sa = a, *sb = b;
     return strcmp(sa->key, sb->key);
 }