strongSwan: private_key_t Struct Reference
private_key_t Struct Reference
private_key
#include "private_key.h"
Public Attributes
key_type_t(* get_type)(private_key_t *this)
bool(* sign)(private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
bool(* decrypt)(private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
int(* get_keysize)(private_key_t *this)
public_key_t *(* get_public_key)(private_key_t *this)
bool(* equals)(private_key_t *this, private_key_t *other)
bool(* belongs_to)(private_key_t *this, public_key_t *public)
bool(* get_fingerprint)(private_key_t *this, cred_encoding_type_t type, chunk_t *fp)
bool(* has_fingerprint)(private_key_t *this, chunk_t fp)
bool(* get_encoding)(private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
private_key_t *(* get_ref)(private_key_t *this)
void(* destroy)(private_key_t *this)
Detailed Description
Abstract private key interface.
Definition at line 32 of file private_key.h.
Member Data Documentation
bool(* private_key_t::belongs_to)(private_key_t *this, public_key_t *public)
Check if a private key belongs to a public key.
Parameters
public public key
Returns
TRUE, if keys belong together
Definition at line 90 of file private_key.h.
bool(* private_key_t::decrypt)(private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
Decrypt a chunk of data.
Parameters
scheme expected encryption scheme used
crypto chunk containing encrypted data
plain where to allocate decrypted data
Returns
TRUE if data decrypted and plaintext allocated
Definition at line 59 of file private_key.h.
Referenced by parse_private_key(), and START_TEST().
void(* private_key_t::destroy)(private_key_t *this)
Decrease refcount, destroy private_key if no more references.
Definition at line 130 of file private_key.h.
Referenced by create_cert(), create_cert_ext(), find_client_id(), find_private(), gen(), issue(), list_public_key(), load_agent(), METHOD(), need_secrets(), print(), select_suite_and_key(), and START_TEST().
bool(* private_key_t::equals)(private_key_t *this, private_key_t *other)
Check if two private keys are equal.
Parameters
other other private key
Returns
TRUE, if equality
Definition at line 82 of file private_key.h.
Referenced by METHOD().
bool(* private_key_t::get_encoding)(private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
Get the key in an encoded form as a chunk.
Parameters
type type of the encoding, one of PRIVKEY_*
encoding encoding of the key, allocated
Returns
TRUE if encoding supported
Definition at line 117 of file private_key.h.
Referenced by export(), gen(), main(), and START_TEST().
bool(* private_key_t::get_fingerprint)(private_key_t *this, cred_encoding_type_t type, chunk_t *fp)
Get the fingerprint of the key.
Parameters
type type of fingerprint, one of KEYID_*
fp fingerprint, points to internal data
Returns
TRUE if fingerprint type supported
Definition at line 99 of file private_key.h.
Referenced by generate(), private_key_equals(), and START_TEST().
int(* private_key_t::get_keysize)(private_key_t *this)
Get the strength of the key in bits.
Returns
strength of the key in bits
Definition at line 67 of file private_key.h.
Referenced by main(), show(), START_TEST(), and test_good_sig().
public_key_t*(* private_key_t::get_public_key)(private_key_t *this)
Get the public part from the private key.
Returns
public key
Definition at line 74 of file private_key.h.
Referenced by create_cert(), create_cert_ext(), generate(), issue(), load_agent(), main(), print_key(), and START_TEST().
private_key_t*(* private_key_t::get_ref)(private_key_t *this)
Increase the refcount to this private key.
Returns
this, with an increased refcount
Definition at line 125 of file private_key.h.
Referenced by get_private_by_keyid(), load_pkcs12(), main(), METHOD(), START_TEST(), x509_ac_gen(), and x509_ocsp_request_gen().
key_type_t(* private_key_t::get_type)(private_key_t *this)
Get the key type.
Returns
type of the key
Definition at line 39 of file private_key.h.
Referenced by generate(), key_filter(), load_pkcs12(), load_private(), METHOD(), select_suite_and_key(), show(), and START_TEST().
bool(* private_key_t::has_fingerprint)(private_key_t *this, chunk_t fp)
Check if a key has a given fingerprint of any kind.
Parameters
fp fingerprint to check
Returns
TRUE if key has given fingerprint
Definition at line 108 of file private_key.h.
Referenced by key_filter().
bool(* private_key_t::sign)(private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
Create a signature over a chunk of data.
Parameters
scheme signature scheme to use
data chunk of data to sign
signature where to allocate created signature
Returns
TRUE if signature created
Definition at line 49 of file private_key.h.
Referenced by generate(), METHOD(), parse_private_key(), START_TEST(), and test_good_sig().
The documentation for this struct was generated from the following file:
private_key.h