strongSwan: load_creds.h File Reference
load_creds.h File Reference
#include "command.h"
Functions
int load_creds_cfg (vici_conn_t *conn, command_format_options_t format, settings_t *cfg, bool clear, bool noprompt)
Function Documentation
int load_creds_cfg (vici_conn_t * conn, command_format_options_t format, settings_t * cfg, bool clear, bool noprompt)
Load all credentials from configuration file
Parameters
conn vici connection to load to
format output format
cfg configuration to load from
clear TRUE to clear existing credentials
noprompt TRUE to skip any password prompt
See header.
Definition at line 661 of file load_creds.c.
References clear_creds(), settings_t::create_section_enumerator, enumerator_t::destroy, ECONNREFUSED, enumerator_t::enumerate, load_certs(), load_containers(), load_keys(), load_secret(), section, SWANCTL_ECDSADIR, SWANCTL_PKCS12DIR, SWANCTL_PKCS8DIR, SWANCTL_RSADIR, SWANCTL_X509AADIR, SWANCTL_X509ACDIR, SWANCTL_X509CADIR, SWANCTL_X509CRLDIR, and SWANCTL_X509DIR.
Referenced by load_all(), and load_creds().
 {
     enumerator_t *enumerator;
     char *section;
     if (clear)
     {
         if (!clear_creds(conn, format))
         {
             return ECONNREFUSED;
         }
     }
     load_certs(conn, format, "x509", SWANCTL_X509DIR);
     load_certs(conn, format, "x509ca", SWANCTL_X509CADIR);
     load_certs(conn, format, "x509aa", SWANCTL_X509AADIR);
     load_certs(conn, format, "x509crl", SWANCTL_X509CRLDIR);
     load_certs(conn, format, "x509ac", SWANCTL_X509ACDIR);
     load_keys(conn, format, noprompt, cfg, "rsa", SWANCTL_RSADIR);
     load_keys(conn, format, noprompt, cfg, "ecdsa", SWANCTL_ECDSADIR);
     load_keys(conn, format, noprompt, cfg, "pkcs8", SWANCTL_PKCS8DIR);
     load_containers(conn, format, noprompt, cfg, "pkcs12", SWANCTL_PKCS12DIR);
     enumerator = cfg->create_section_enumerator(cfg, "secrets");
     while (enumerator->enumerate(enumerator, &section))
     {
         load_secret(conn, cfg, section, format);
     }
     enumerator->destroy(enumerator);
     return 0;
 }