strongSwan: pgp_cert.c File Reference
pgp_cert.c File Reference
#include "pgp_cert.h"
#include "pgp_utils.h"
#include <time.h>
#include <utils/debug.h>
Classes
struct private_pgp_cert_t
Typedefs
typedef struct private_pgp_cert_t private_pgp_cert_t
Functions
METHOD (certificate_t, get_type, certificate_type_t, private_pgp_cert_t *this)
METHOD (certificate_t, get_subject, identification_t *, private_pgp_cert_t *this)
METHOD (certificate_t, get_issuer, identification_t *, private_pgp_cert_t *this)
METHOD (certificate_t, has_subject, id_match_t, private_pgp_cert_t *this, identification_t *subject)
METHOD (certificate_t, has_issuer, id_match_t, private_pgp_cert_t *this, identification_t *issuer)
METHOD (certificate_t, issued_by, bool, private_pgp_cert_t *this, certificate_t *issuer, signature_scheme_t *scheme)
METHOD (certificate_t, get_public_key, public_key_t *, private_pgp_cert_t *this)
METHOD (certificate_t, get_ref, certificate_t *, private_pgp_cert_t *this)
METHOD (certificate_t, get_validity, bool, private_pgp_cert_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_pgp_cert_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, equals, bool, private_pgp_cert_t *this, certificate_t *other)
METHOD (certificate_t, destroy, void, private_pgp_cert_t *this)
METHOD (pgp_certificate_t, get_fingerprint, chunk_t, private_pgp_cert_t *this)
private_pgp_cert_t * create_empty ()
static bool parse_public_key (private_pgp_cert_t *this, chunk_t packet)
static bool parse_signature (private_pgp_cert_t *this, chunk_t packet)
static bool parse_user_id (private_pgp_cert_t *this, chunk_t packet)
pgp_cert_t * pgp_cert_load (certificate_type_t type, va_list args)
Typedef Documentation
typedef struct private_pgp_cert_t private_pgp_cert_t
Definition at line 23 of file pgp_cert.c.
Function Documentation
private_pgp_cert_t* create_empty (void)
See header
Definition at line 232 of file pgp_cert.c.
References INIT.
Referenced by pgp_cert_load().
 {
     private_pgp_cert_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .interface = {
                     .get_type = _get_type,
                     .get_subject = _get_subject,
                     .get_issuer = _get_issuer,
                     .has_subject = _has_subject,
                     .has_issuer = _has_issuer,
                     .issued_by = _issued_by,
                     .get_public_key = _get_public_key,
                     .get_validity = _get_validity,
                     .get_encoding = _get_encoding,
                     .equals = _equals,
                     .get_ref = _get_ref,
                     .destroy = _destroy,
                 },
                 .get_fingerprint = _get_fingerprint,
             },
         },
         .ref = 1,
     );
     return this;
 }
METHOD (certificate_t , get_type , certificate_type_t , private_pgp_cert_t * this)
Definition at line 77 of file pgp_cert.c.
References CERT_GPG.
 {
     return CERT_GPG;
 }
METHOD (certificate_t , get_subject , identification_t * , private_pgp_cert_t * this)
Definition at line 83 of file pgp_cert.c.
 {
     return this->user_id;
 }
METHOD (certificate_t , get_issuer , identification_t * , private_pgp_cert_t * this)
Definition at line 89 of file pgp_cert.c.
 {
     return this->user_id;
 }
METHOD (certificate_t , has_subject , id_match_t , private_pgp_cert_t * this, identification_t * subject)
Definition at line 95 of file pgp_cert.c.
References chunk_equals(), fingerprint, identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, ID_MATCH_NONE, and ID_MATCH_PERFECT.
 {
     id_match_t match_user_id;
     match_user_id = this->user_id->matches(this->user_id, subject);
     if (match_user_id == ID_MATCH_NONE &&
         subject->get_type(subject) == ID_KEY_ID &&
         chunk_equals(this->fingerprint, subject->get_encoding(subject)))
     {
         return ID_MATCH_PERFECT;
     }
     return match_user_id;
 }
METHOD (certificate_t , has_issuer , id_match_t , private_pgp_cert_t * this, identification_t * issuer)
Definition at line 110 of file pgp_cert.c.
References ID_MATCH_NONE.
 {
     return ID_MATCH_NONE;
 }
METHOD (certificate_t , issued_by , bool , private_pgp_cert_t * this, certificate_t * issuer, signature_scheme_t * scheme)
Definition at line 116 of file pgp_cert.c.
References FALSE.
 {
     /* TODO: check signature blobs for a valid signature */
     return FALSE;
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_pgp_cert_t * this)
Definition at line 123 of file pgp_cert.c.
References key.
 {
     this->key->get_ref(this->key);
     return this->key;
 }
METHOD (certificate_t , get_ref , certificate_t * , private_pgp_cert_t * this)
Definition at line 130 of file pgp_cert.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.interface.interface;
 }
METHOD (certificate_t , get_validity , bool , private_pgp_cert_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 137 of file pgp_cert.c.
References TIME_32_BIT_SIGNED_MAX, and valid.
 {
     time_t t, until;
     if (when)
     {
         t = *when;
     }
     else
     {
         t = time(NULL);
     }
     if (not_before)
     {
         *not_before = this->created;
     }
     if (this->valid)
     {
         until = this->valid + this->created * 24 * 60 * 60;
     }
     else
     {
         /* Jan 19 03:14:07 UTC 2038 */
         until = TIME_32_BIT_SIGNED_MAX;
     }
     if (not_after)
     {
         *not_after = until;
     }
     return (t >= this->valid && t <= until);
 }
METHOD (certificate_t , get_encoding , bool , private_pgp_cert_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 171 of file pgp_cert.c.
References CERT_PGP_PKT, chunk_clone, CRED_PART_END, CRED_PART_PGP_CERT, cred_encoding_t::encode, library_t::encoding, lib, and TRUE.
 {
     if (type == CERT_PGP_PKT)
     {
         *encoding = chunk_clone(this->encoding);
         return TRUE;
     }
     return lib->encoding->encode(lib->encoding, type, NULL, encoding,
                         CRED_PART_PGP_CERT, this->encoding, CRED_PART_END);
 }
METHOD (certificate_t , equals , bool , private_pgp_cert_t * this, certificate_t * other)
Definition at line 183 of file pgp_cert.c.
References CERT_PGP_PKT, CERT_X509, chunk_equals(), encoding, equals(), certificate_t::equals, FALSE, free(), certificate_t::get_encoding, certificate_t::get_type, chunk_t::ptr, and TRUE.
 {
     chunk_t encoding;
     bool equal;
     if (this == (private_pgp_cert_t*)other)
     {
         return TRUE;
     }
     if (other->get_type(other) != CERT_X509)
     {
         return FALSE;
     }
     if (other->equals == (void*)equals)
     {   /* skip allocation if we have the same implementation */
         return chunk_equals(this->encoding, ((private_pgp_cert_t*)other)->encoding);
     }
     if (!other->get_encoding(other, CERT_PGP_PKT, &encoding))
     {
         return FALSE;
     }
     equal = chunk_equals(this->encoding, encoding);
     free(encoding.ptr);
     return equal;
 }
METHOD (certificate_t , destroy , void , private_pgp_cert_t * this)
Definition at line 210 of file pgp_cert.c.
References DESTROY_IF, encoding, fingerprint, free(), key, chunk_t::ptr, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         DESTROY_IF(this->key);
         DESTROY_IF(this->user_id);
         free(this->fingerprint.ptr);
         free(this->encoding.ptr);
         free(this);
     }
 }
METHOD (pgp_certificate_t , get_fingerprint , chunk_t , private_pgp_cert_t * this)
Definition at line 223 of file pgp_cert.c.
References fingerprint.
 {
     return this->fingerprint;
 }
static bool parse_public_key (private_pgp_cert_t * this, chunk_t packet) static
Parse the public key packet of a PGP certificate
Definition at line 265 of file pgp_cert.c.
References hasher_t::allocate_hash, BUILD_BLOB_PGP, BUILD_END, chunk_clone, chunk_from_chars, credential_factory_t::create, crypto_factory_t::create_hasher, CRED_PUBLIC_KEY, library_t::creds, library_t::crypto, DBG1, DBG2, DBG_ASN, hasher_t::destroy, DESTROY_IF, FALSE, fingerprint, HASH_SHA1, hasher, key, KEY_ANY, KEYID_PGPV3, chunk_t::len, lib, pgp_read_scalar(), TRUE, valid, and version.
Referenced by pgp_cert_load().
 {
     chunk_t pubkey_packet = packet;
     if (!pgp_read_scalar(&packet, 1, &this->version))
     {
         return FALSE;
     }
     switch (this->version)
     {
         case 3:
             if (!pgp_read_scalar(&packet, 4, &this->created) ||
                 !pgp_read_scalar(&packet, 2, &this->valid))
             {
                 return FALSE;
             }
             break;
         case 4:
             if (!pgp_read_scalar(&packet, 4, &this->created))
             {
                 return FALSE;
             }
             break;
         default:
             DBG1(DBG_ASN, "PGP packet version V%d not supported",
                  this->version);
             return FALSE;
     }
     if (this->valid)
     {
         DBG2(DBG_ASN, "L2 - created %T, valid %d days", &this->created, FALSE,
              this->valid);
     }
     else
     {
         DBG2(DBG_ASN, "L2 - created %T, never expires", &this->created, FALSE);
     }
     DESTROY_IF(this->key);
     this->key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_ANY,
                                     BUILD_BLOB_PGP, packet, BUILD_END);
     if (this->key == NULL)
     {
         return FALSE;
     }
     /* compute V4 or V3 fingerprint according to section 12.2 of RFC 4880 */
     if (this->version == 4)
     {
         chunk_t pubkey_packet_header = chunk_from_chars(
                     0x99, pubkey_packet.len / 256, pubkey_packet.len % 256
                 );
         hasher_t *hasher;
         hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
         if (hasher == NULL)
         {
             DBG1(DBG_ASN, "no SHA-1 hasher available");
             return FALSE;
         }
         if (!hasher->allocate_hash(hasher, pubkey_packet_header, NULL) ||
             !hasher->allocate_hash(hasher, pubkey_packet, &this->fingerprint))
         {
             hasher->destroy(hasher);
             return FALSE;
         }
         hasher->destroy(hasher);
         DBG2(DBG_ASN, "L2 - v4 fingerprint %#B", &this->fingerprint);
     }
     else
     {
         /* V3 fingerprint is computed by public_key_t class */
         if (!this->key->get_fingerprint(this->key, KEYID_PGPV3,
                                         &this->fingerprint))
         {
             return FALSE;
         }
         this->fingerprint = chunk_clone(this->fingerprint);
         DBG2(DBG_ASN, "L2 - v3 fingerprint %#B", &this->fingerprint);
     }
     return TRUE;
 }
static bool parse_signature (private_pgp_cert_t * this, chunk_t packet) static
Parse the signature packet of a PGP certificate
Definition at line 350 of file pgp_cert.c.
References DBG2, DBG_ASN, FALSE, len, pgp_read_scalar(), TRUE, type, and version.
Referenced by pgp_cert_load().
 {
     u_int32_t version, len, type, created;
     if (!pgp_read_scalar(&packet, 1, &version))
     {
         return FALSE;
     }
     /* we parse only v3 or v4 signature packets */
     if (version != 3 && version != 4)
     {
         DBG2(DBG_ASN, "L2 - v%d signature ignored", version);
         return TRUE;
     }
     if (version == 4)
     {
         if (!pgp_read_scalar(&packet, 1, &type))
         {
             return FALSE;
         }
         DBG2(DBG_ASN, "L2 - v%d signature of type 0x%02x", version, type);
     }
     else
     {
         if (!pgp_read_scalar(&packet, 1, &len) || len != 5)
         {
             return FALSE;
         }
         if (!pgp_read_scalar(&packet, 1, &type) ||
             !pgp_read_scalar(&packet, 4, &created))
         {
             return FALSE;
         }
         DBG2(DBG_ASN, "L2 - v3 signature of type 0x%02x, created %T", type,
              &created, FALSE);
     }
     /* TODO: parse and save signature to a list */
     return TRUE;
 }
static bool parse_user_id (private_pgp_cert_t * this, chunk_t packet) static
Parse the userid packet of a PGP certificate
Definition at line 394 of file pgp_cert.c.
References DBG2, DBG_ASN, DESTROY_IF, ID_KEY_ID, identification_create_from_encoding(), and TRUE.
Referenced by pgp_cert_load().
 {
     DESTROY_IF(this->user_id);
     this->user_id = identification_create_from_encoding(ID_KEY_ID, packet);
     DBG2(DBG_ASN, "L2 - '%Y'", this->user_id);
     return TRUE;
 }