strongSwan: pkcs1_builder
pkcs1_builder
pkcs1
Functions
public_key_t * pkcs1_public_key_load (key_type_t type, va_list args)
private_key_t * pkcs1_private_key_load (key_type_t type, va_list args)
Detailed Description
Function Documentation
private_key_t* pkcs1_private_key_load (key_type_t type, va_list args)
Load a RSA public key from PKCS#1 data.
Parameters
type type of the key, KEY_RSA
args builder_part_t argument list
Returns
private key, NULL on failure
See header.
Definition at line 286 of file pkcs1_builder.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, parse_rsa_private_key(), and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     return parse_rsa_private_key(blob);
 }
public_key_t* pkcs1_public_key_load (key_type_t type, va_list args)
Load a generic or an RSA public key from PKCS#1 data.
Parameters
type type of the key, either KEY_ANY or KEY_RSA
args builder_part_t argument list
Returns
public key, NULL on failure
See header.
Definition at line 254 of file pkcs1_builder.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, KEY_ANY, KEY_RSA, parse_public_key(), parse_rsa_public_key(), and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     switch (type)
     {
         case KEY_ANY:
             return parse_public_key(blob);
         case KEY_RSA:
             return parse_rsa_public_key(blob);
         default:
             return NULL;
     }
 }