strongSwan: stroke_counter
stroke_counter
stroke
Classes
struct stroke_counter_t
Typedefs
typedef struct stroke_counter_t stroke_counter_t
typedef enum stroke_counter_type_t stroke_counter_type_t
Enumerations
enum stroke_counter_type_t {
COUNTER_INIT_IKE_SA_REKEY, COUNTER_RESP_IKE_SA_REKEY, COUNTER_CHILD_SA_REKEY, COUNTER_IN_INVALID,
COUNTER_IN_INVALID_IKE_SPI, COUNTER_IN_IKE_SA_INIT_REQ, COUNTER_IN_IKE_SA_INIT_RSP, COUNTER_OUT_IKE_SA_INIT_REQ,
COUNTER_OUT_IKE_SA_INIT_RES, COUNTER_IN_IKE_AUTH_REQ, COUNTER_IN_IKE_AUTH_RSP, COUNTER_OUT_IKE_AUTH_REQ,
COUNTER_OUT_IKE_AUTH_RSP, COUNTER_IN_CREATE_CHILD_SA_REQ, COUNTER_IN_CREATE_CHILD_SA_RSP, COUNTER_OUT_CREATE_CHILD_SA_REQ,
COUNTER_OUT_CREATE_CHILD_SA_RSP, COUNTER_IN_INFORMATIONAL_REQ, COUNTER_IN_INFORMATIONAL_RSP, COUNTER_OUT_INFORMATIONAL_REQ,
COUNTER_OUT_INFORMATIONAL_RSP, COUNTER_MAX
}
Functions
stroke_counter_t * stroke_counter_create ()
Detailed Description
Typedef Documentation
typedef struct stroke_counter_t stroke_counter_t
Definition at line 26 of file stroke_counter.h.
typedef enum stroke_counter_type_t stroke_counter_type_t
Definition at line 27 of file stroke_counter.h.
Enumeration Type Documentation
enum stroke_counter_type_t
Enumerator
COUNTER_INIT_IKE_SA_REKEY
initiated IKE_SA rekeyings
COUNTER_RESP_IKE_SA_REKEY
responded IKE_SA rekeyings
COUNTER_CHILD_SA_REKEY
completed CHILD_SA rekeyings
COUNTER_IN_INVALID
messages with invalid types, length, or a value out of range
COUNTER_IN_INVALID_IKE_SPI
messages with an invalid IKE SPI
COUNTER_IN_IKE_SA_INIT_REQ
received IKE_SA_INIT requests
COUNTER_IN_IKE_SA_INIT_RSP
received IKE_SA_INIT responses
COUNTER_OUT_IKE_SA_INIT_REQ
sent IKE_SA_INIT requests
COUNTER_OUT_IKE_SA_INIT_RES
sent IKE_SA_INIT responses
COUNTER_IN_IKE_AUTH_REQ
received IKE_AUTH requests
COUNTER_IN_IKE_AUTH_RSP
received IKE_AUTH responses
COUNTER_OUT_IKE_AUTH_REQ
sent IKE_AUTH requests
COUNTER_OUT_IKE_AUTH_RSP
sent IKE_AUTH responses
COUNTER_IN_CREATE_CHILD_SA_REQ
received CREATE_CHILD_SA requests
COUNTER_IN_CREATE_CHILD_SA_RSP
received CREATE_CHILD_SA responses
COUNTER_OUT_CREATE_CHILD_SA_REQ
sent CREATE_CHILD_SA requests
COUNTER_OUT_CREATE_CHILD_SA_RSP
sent CREATE_CHILD_SA responses
COUNTER_IN_INFORMATIONAL_REQ
received INFORMATIONAL requests
COUNTER_IN_INFORMATIONAL_RSP
received INFORMATIONAL responses
COUNTER_OUT_INFORMATIONAL_REQ
sent INFORMATIONAL requests
COUNTER_OUT_INFORMATIONAL_RSP
sent INFORMATIONAL responses
COUNTER_MAX
number of counter types
Definition at line 29 of file stroke_counter.h.
{
     COUNTER_INIT_IKE_SA_REKEY,
     COUNTER_RESP_IKE_SA_REKEY,
     COUNTER_CHILD_SA_REKEY,
     COUNTER_IN_INVALID,
     COUNTER_IN_INVALID_IKE_SPI,
     COUNTER_IN_IKE_SA_INIT_REQ,
     COUNTER_IN_IKE_SA_INIT_RSP,
     COUNTER_OUT_IKE_SA_INIT_REQ,
     COUNTER_OUT_IKE_SA_INIT_RES,
     COUNTER_IN_IKE_AUTH_REQ,
     COUNTER_IN_IKE_AUTH_RSP,
     COUNTER_OUT_IKE_AUTH_REQ,
     COUNTER_OUT_IKE_AUTH_RSP,
     COUNTER_IN_CREATE_CHILD_SA_REQ,
     COUNTER_IN_CREATE_CHILD_SA_RSP,
     COUNTER_OUT_CREATE_CHILD_SA_REQ,
     COUNTER_OUT_CREATE_CHILD_SA_RSP,
     COUNTER_IN_INFORMATIONAL_REQ,
     COUNTER_IN_INFORMATIONAL_RSP,
     COUNTER_OUT_INFORMATIONAL_REQ,
     COUNTER_OUT_INFORMATIONAL_RSP,
     COUNTER_MAX
 };
Function Documentation
stroke_counter_t* stroke_counter_create ()
Create a stroke_counter instance.
See header
Definition at line 442 of file stroke_counter.c.
References equals(), hash(), hashtable_create(), INIT, and spinlock_create().
Referenced by stroke_socket_create().
 {
     private_stroke_counter_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .alert = _alert,
                 .ike_rekey = _ike_rekey,
                 .child_rekey = _child_rekey,
                 .message = _message_hook,
             },
             .print = _print,
             .reset = _reset,
             .destroy = _destroy,
         },
         .conns = hashtable_create((hashtable_hash_t)hash,
                                   (hashtable_equals_t)equals, 4),
         .lock = spinlock_create(),
     );
     return &this->public;
 }