strongSwan: child_cfg
child_cfg
config
Classes
struct child_cfg_t
Typedefs
typedef enum action_t action_t
typedef struct child_cfg_t child_cfg_t
Enumerations
enum action_t { ACTION_NONE, ACTION_ROUTE, ACTION_RESTART }
Functions
child_cfg_t * child_cfg_create (char *name, lifetime_cfg_t *lifetime, char *updown, bool hostaccess, ipsec_mode_t mode, action_t start_action, action_t dpd_action, action_t close_action, bool ipcomp, u_int32_t inactivity, u_int32_t reqid, mark_t *mark_in, mark_t *mark_out, u_int32_t tfc)
Variables
enum_name_t * action_names
Detailed Description
Typedef Documentation
typedef enum action_t action_t
Definition at line 26 of file child_cfg.h.
typedef struct child_cfg_t child_cfg_t
Definition at line 27 of file child_cfg.h.
Enumeration Type Documentation
enum action_t
Action to take when connection is loaded, DPD is detected or connection gets closed by peer.
Enumerator
ACTION_NONE
No action
ACTION_ROUTE
Route config to establish or reestablish on demand
ACTION_RESTART
Start or restart config immediately
Definition at line 38 of file child_cfg.h.
               {
     ACTION_NONE,
     ACTION_ROUTE,
     ACTION_RESTART,
 };
Function Documentation
child_cfg_t* child_cfg_create (char * name, lifetime_cfg_t * lifetime, char * updown, bool hostaccess, ipsec_mode_t mode, action_t start_action, action_t dpd_action, action_t close_action, bool ipcomp, u_int32_t inactivity, u_int32_t reqid, mark_t * mark_in, mark_t * mark_out, u_int32_t tfc)
Create a configuration template for CHILD_SA setup.
The "name" string gets cloned.
The lifetime_cfg_t object gets cloned. To prevent two peers to start rekeying at the same time, a jitter may be specified. Rekeying of an SA starts at (x.rekey - random(0, x.jitter)).
After a call to create, a reference is obtained (refcount = 1).
Parameters
name name of the child_cfg
lifetime lifetime_cfg_t for this child_cfg
updown updown script to execute on up/down event
hostaccess TRUE to allow access to the local host
mode mode to propose for CHILD_SA, transport, tunnel or BEET
start_action start action
dpd_action DPD action
close_action close action
ipcomp use IPComp, if peer supports it
inactivity inactivity timeout in s before closing a CHILD_SA
reqid specific reqid to use for CHILD_SA, 0 for auto assign
mark_in optional inbound mark (can be NULL)
mark_out optional outbound mark (can be NULL)
tfc TFC padding size, 0 to disable, -1 to pad to PMTU
Returns
child_cfg_t object
Definition at line 561 of file child_cfg.c.
References DEFAULT_REPLAY_WINDOW, FALSE, settings_t::get_int, INIT, lib, linked_list_create(), memcpy, library_t::ns, library_t::settings, strdup, strdupnull(), and TRUE.
Referenced by add_exclude_async(), build_child_cfg(), CALLBACK(), connect_(), create_child_cfg(), generate_config(), initiate_connection(), load_child_config(), METHOD(), and setup_tunnel().
 {
     private_child_cfg_t *this;
     INIT(this,
         .public = {
             .get_name = _get_name,
             .add_traffic_selector = _add_traffic_selector,
             .get_traffic_selectors = _get_traffic_selectors,
             .add_proposal = _add_proposal,
             .get_proposals = _get_proposals,
             .select_proposal = _select_proposal,
             .get_updown = _get_updown,
             .get_hostaccess = _get_hostaccess,
             .get_mode = _get_mode,
             .get_start_action = _get_start_action,
             .get_dpd_action = _get_dpd_action,
             .get_close_action = _get_close_action,
             .get_lifetime = _get_lifetime,
             .get_dh_group = _get_dh_group,
             .set_mipv6_options = _set_mipv6_options,
             .use_ipcomp = _use_ipcomp,
             .get_inactivity = _get_inactivity,
             .get_reqid = _get_reqid,
             .get_mark = _get_mark,
             .get_tfc = _get_tfc,
             .get_replay_window = _get_replay_window,
             .set_replay_window = _set_replay_window,
             .use_proxy_mode = _use_proxy_mode,
             .install_policy = _install_policy,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .name = strdup(name),
         .updown = strdupnull(updown),
         .hostaccess = hostaccess,
         .mode = mode,
         .start_action = start_action,
         .dpd_action = dpd_action,
         .close_action = close_action,
         .use_ipcomp = ipcomp,
         .inactivity = inactivity,
         .reqid = reqid,
         .proxy_mode = FALSE,
         .install_policy = TRUE,
         .refcount = 1,
         .proposals = linked_list_create(),
         .my_ts = linked_list_create(),
         .other_ts = linked_list_create(),
         .tfc = tfc,
         .replay_window = lib->settings->get_int(lib->settings,
                 "%s.replay_window", DEFAULT_REPLAY_WINDOW, lib->ns),
     );
     if (mark_in)
     {
         this->mark_in = *mark_in;
     }
     if (mark_out)
     {
         this->mark_out = *mark_out;
     }
     memcpy(&this->lifetime, lifetime, sizeof(lifetime_cfg_t));
     return &this->public;
 }
Variable Documentation
enum_name_t* action_names
enum names for action_t.
Referenced by log_child_data(), and METHOD().