strongSwan: test_process.c File Reference
test_process.c File Reference
#include "test_suite.h"
#include <unistd.h>
#include <utils/process.h>
Functions
START_TEST (test_retval_true)
END_TEST START_TEST (test_retval_false)
END_TEST START_TEST (test_not_found)
END_TEST START_TEST (test_echo)
END_TEST START_TEST (test_echo_err)
END_TEST START_TEST (test_env)
END_TEST START_TEST (test_shell)
END_TEST Suite * process_suite_create ()
Function Documentation
END_TEST Suite* process_suite_create ()
Definition at line 197 of file test_process.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("process");
     tc = tcase_create("return values");
     tcase_add_test(tc, test_retval_true);
     tcase_add_test(tc, test_retval_false);
     suite_add_tcase(s, tc);
     tc = tcase_create("not found");
     tcase_add_test(tc, test_not_found);
     suite_add_tcase(s, tc);
     tc = tcase_create("echo");
     tcase_add_test(tc, test_echo);
     tcase_add_test(tc, test_echo_err);
     suite_add_tcase(s, tc);
     tc = tcase_create("env");
     tcase_add_test(tc, test_env);
     suite_add_tcase(s, tc);
     tc = tcase_create("shell");
     tcase_add_test(tc, test_shell);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_retval_true)
Definition at line 22 of file test_process.c.
References argv, ck_assert, ck_assert_int_eq, process(), process_start(), TRUE, and process_t::wait.
 {
     process_t *process;
     char *argv[] = {
 #ifdef WIN32
         "C:\\Windows\\system32\\cmd.exe",
         "/C",
         "exit 0",
 #else
         "/bin/sh",
         "-c",
         "true",
 #endif
         NULL
     };
     int retval;
     process = process_start(argv, NULL, NULL, NULL, NULL, TRUE);
     ck_assert(process != NULL);
     ck_assert(process->wait(process, &retval));
     ck_assert_int_eq(retval, 0);
 }
END_TEST START_TEST (test_retval_false)
Definition at line 46 of file test_process.c.
References argv, ck_assert, process(), process_start(), TRUE, and process_t::wait.
 {
     process_t *process;
     char *argv[] = {
 #ifdef WIN32
         "C:\\Windows\\system32\\cmd.exe",
         "/C",
         "exit 1",
 #else
         "/bin/sh",
         "-c",
         "false",
 #endif
         NULL
     };
     int retval;
     process = process_start(argv, NULL, NULL, NULL, NULL, TRUE);
     ck_assert(process != NULL);
     ck_assert(process->wait(process, &retval));
     ck_assert(retval != 0);
 }
END_TEST START_TEST (test_not_found)
Definition at line 70 of file test_process.c.
References argv, ck_assert, process(), process_start(), TRUE, and process_t::wait.
 {
     process_t *process;
     char *argv[] = {
         "/bin/does-not-exist",
         NULL
     };
     process = process_start(argv, NULL, NULL, NULL, NULL, TRUE);
     /* both is acceptable behavior */
     ck_assert(process == NULL || !process->wait(process, NULL));
 }
END_TEST START_TEST (test_echo)
Definition at line 84 of file test_process.c.
References argv, ck_assert, ck_assert_int_eq, ck_assert_str_eq, close, in, memset, msg, out, process(), process_start(), read, TRUE, process_t::wait, and write.
 {
     process_t *process;
     char *argv[] = {
 #ifdef WIN32
         "C:\\Windows\\system32\\more.com",
 #else
         "/bin/sh",
         "-c",
         "cat",
 #endif
         NULL
     };
     int retval, in, out;
     char *msg = "test";
     char buf[strlen(msg) + 1];
     memset(buf, 0, strlen(msg) + 1);
     process = process_start(argv, NULL, &in, &out, NULL, TRUE);
     ck_assert(process != NULL);
     ck_assert_int_eq(write(in, msg, strlen(msg)), strlen(msg));
     ck_assert(close(in) == 0);
     ck_assert_int_eq(read(out, buf, strlen(msg) + 1), strlen(msg));
     ck_assert_str_eq(buf, msg);
     ck_assert(close(out) == 0);
     ck_assert(process->wait(process, &retval));
     ck_assert_int_eq(retval, 0);
 }
END_TEST START_TEST (test_echo_err)
Definition at line 115 of file test_process.c.
References argv, ck_assert, ck_assert_int_eq, ck_assert_str_eq, close, in, memset, msg, process(), process_start(), read, TRUE, process_t::wait, and write.
 {
     process_t *process;
     char *argv[] = {
 #ifdef WIN32
         "C:\\Windows\\system32\\cmd.exe",
         "/C",
         "1>&2 C:\\Windows\\system32\\more.com",
 #else
         "/bin/sh",
         "-c",
         "1>&2 cat",
 #endif
         NULL
     };
     int retval, in, err;
     char *msg = "a longer test message";
     char buf[strlen(msg) + 1];
     memset(buf, 0, strlen(msg) + 1);
     process = process_start(argv, NULL, &in, NULL, &err, TRUE);
     ck_assert(process != NULL);
     ck_assert_int_eq(write(in, msg, strlen(msg)), strlen(msg));
     ck_assert(close(in) == 0);
     ck_assert_int_eq(read(err, buf, strlen(msg) + 1), strlen(msg));
     ck_assert_str_eq(buf, msg);
     ck_assert(close(err) == 0);
     ck_assert(process->wait(process, &retval));
     ck_assert_int_eq(retval, 0);
 }
END_TEST START_TEST (test_env)
Definition at line 148 of file test_process.c.
References argv, ck_assert, ck_assert_int_eq, ck_assert_str_eq, close, out, process(), process_start(), read, TRUE, and process_t::wait.
 {
     process_t *process;
     char *argv[] = {
 #ifdef WIN32
         "C:\\Windows\\system32\\cmd.exe",
         "/C",
         "echo %A% %B%",
 #else
         "/bin/sh",
         "-c",
         "/bin/echo -n $A $B",
 #endif
         NULL
     };
     char *envp[] = {
         "A=atest",
         "B=bstring",
         NULL
     };
     int retval, out;
     char buf[64] = {};
     process = process_start(argv, envp, NULL, &out, NULL, TRUE);
     ck_assert(process != NULL);
     ck_assert(read(out, buf, sizeof(buf)) > 0);
 #ifdef WIN32
     ck_assert_str_eq(buf, "atest bstring\r\n");
 #else
     ck_assert_str_eq(buf, "atest bstring");
 #endif
     ck_assert(close(out) == 0);
     ck_assert(process->wait(process, &retval));
     ck_assert_int_eq(retval, 0);
 }
END_TEST START_TEST (test_shell)
Definition at line 185 of file test_process.c.
References ck_assert, ck_assert_int_eq, process(), process_start_shell(), and process_t::wait.
 {
     process_t *process;
     int retval;
     process = process_start_shell(NULL, NULL, NULL, NULL, "exit %d", 3);
     ck_assert(process != NULL);
     ck_assert(process->wait(process, &retval));
     ck_assert_int_eq(retval, 3);
 }