strongSwan: lookip_listener.c File Reference
lookip_listener.c File Reference
#include "lookip_listener.h"
#include <daemon.h>
#include <collections/hashtable.h>
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_lookip_listener_t
struct listener_entry_t
struct entry_t
Typedefs
typedef struct
private_lookip_listener_t private_lookip_listener_t
Functions
static void entry_destroy (entry_t *entry)
static u_int hash (host_t *key)
static bool equals (host_t *a, host_t *b)
static bool notify_up (listener_entry_t *listener, entry_t *entry)
static bool notify_down (listener_entry_t *listener, entry_t *entry)
static void add_entry (private_lookip_listener_t *this, ike_sa_t *ike_sa)
static void remove_entry (private_lookip_listener_t *this, ike_sa_t *ike_sa)
METHOD (listener_t, message_hook, bool, private_lookip_listener_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (listener_t, ike_updown, bool, private_lookip_listener_t *this, ike_sa_t *ike_sa, bool up)
METHOD (listener_t, ike_rekey, bool, private_lookip_listener_t *this, ike_sa_t *old, ike_sa_t *new)
METHOD (lookip_listener_t, lookup, int, private_lookip_listener_t *this, host_t *vip, lookip_callback_t cb, void *user)
METHOD (lookip_listener_t, add_listener, void, private_lookip_listener_t *this, lookip_callback_t cb, void *user)
METHOD (lookip_listener_t, remove_listener, void, private_lookip_listener_t *this, void *user)
METHOD (lookip_listener_t, destroy, void, private_lookip_listener_t *this)
lookip_listener_t * lookip_listener_create ()
Typedef Documentation
typedef struct private_lookip_listener_t private_lookip_listener_t
Definition at line 23 of file lookip_listener.c.
Function Documentation
static void add_entry (private_lookip_listener_t * this, ike_sa_t * ike_sa) static
Add a new entry to the hashtable
Definition at line 136 of file lookip_listener.c.
References host_t::clone, ike_sa_t::create_virtual_ip_enumerator, enumerator_t::destroy, entry_destroy(), enumerator_t::enumerate, FALSE, ike_sa_t::get_name, ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, ike_sa_t::get_unique_id, id, INIT, lock, notify_up(), strdup, unique_id, spinlock_t::unlock, entry_t::vip, and vip.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     host_t *vip, *other;
     identification_t *id;
     entry_t *entry;
     enumerator = ike_sa->create_virtual_ip_enumerator(ike_sa, FALSE);
     while (enumerator->enumerate(enumerator, &vip))
     {
         other = ike_sa->get_other_host(ike_sa);
         id = ike_sa->get_other_eap_id(ike_sa);
         INIT(entry,
             .vip = vip->clone(vip),
             .other = other->clone(other),
             .id = id->clone(id),
             .name = strdup(ike_sa->get_name(ike_sa)),
             .unique_id = ike_sa->get_unique_id(ike_sa),
         );
         this->lock->read_lock(this->lock);
         this->listeners->remove(this->listeners, entry, (void*)notify_up);
         this->lock->unlock(this->lock);
         this->lock->write_lock(this->lock);
         entry = this->entries->put(this->entries, entry->vip, entry);
         this->lock->unlock(this->lock);
         if (entry)
         {
             entry_destroy(entry);
         }
     }
     enumerator->destroy(enumerator);
 }
static void entry_destroy (entry_t * entry) static
Destroy a hashtable entry
Definition at line 80 of file lookip_listener.c.
References host_t::destroy, identification_t::destroy, free(), entry_t::id, entry_t::name, entry_t::other, and entry_t::vip.
Referenced by add_entry(), and remove_entry().
 {
     entry->vip->destroy(entry->vip);
     entry->other->destroy(entry->other);
     entry->id->destroy(entry->id);
     free(entry->name);
     free(entry);
 }
static bool equals (host_t * a, host_t * b) static
Hashtable equals function
Definition at line 100 of file lookip_listener.c.
References host_t::ip_equals.
Referenced by lookip_listener_create().
 {
     return a->ip_equals(a, b);
 }
static u_int hash (host_t * key) static
Hashtable hash function
Definition at line 92 of file lookip_listener.c.
References chunk_hash(), and host_t::get_address.
Referenced by lookip_listener_create().
 {
     return chunk_hash(key->get_address(key));
 }
METHOD (listener_t , message_hook , bool , private_lookip_listener_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 199 of file lookip_listener.c.
References add_entry(), message_t::get_exchange_type, message_t::get_request, ike_sa_t::get_state, ike_sa_t::get_version, IKE_AUTH, IKE_ESTABLISHED, IKEV1, IKEV2, TRANSACTION, and TRUE.
 {
     if (plain && ike_sa->get_state(ike_sa) == IKE_ESTABLISHED &&
         !incoming && !message->get_request(message))
     {
         if (ike_sa->get_version(ike_sa) == IKEV1 &&
             message->get_exchange_type(message) == TRANSACTION)
         {
             add_entry(this, ike_sa);
         }
         if (ike_sa->get_version(ike_sa) == IKEV2 &&
             message->get_exchange_type(message) == IKE_AUTH)
         {
             add_entry(this, ike_sa);
         }
     }
     return TRUE;
 }
METHOD (listener_t , ike_updown , bool , private_lookip_listener_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 220 of file lookip_listener.c.
References remove_entry(), and TRUE.
 {
     if (!up)
     {
         remove_entry(this, ike_sa);
     }
     return TRUE;
 }
METHOD (listener_t , ike_rekey , bool , private_lookip_listener_t * this, ike_sa_t * old, ike_sa_t * new)
Definition at line 230 of file lookip_listener.c.
References add_entry(), remove_entry(), and TRUE.
 {
     /* During IKE_SA rekey, the unique identifier changes. Fire update events
      * and update the cached entry. During the invocation of this hook, the
      * virtual IPs have been migrated to new, hence remove that entry. */
     remove_entry(this, new);
     add_entry(this, new);
     return TRUE;
 }
METHOD (lookip_listener_t , lookup , int , private_lookip_listener_t * this, host_t * vip, lookip_callback_t cb, void * user)
Definition at line 242 of file lookip_listener.c.
References cb(), enumerator_t::destroy, enumerator_t::enumerate, entry_t::id, lock, entry_t::name, entry_t::other, TRUE, entry_t::unique_id, spinlock_t::unlock, and entry_t::vip.
 {
     entry_t *entry;
     int matches = 0;
     this->lock->read_lock(this->lock);
     if (vip)
     {
         entry = this->entries->get(this->entries, vip);
         if (entry)
         {
             cb(user, TRUE, entry->vip, entry->other, entry->id,
                entry->name, entry->unique_id);
             matches ++;
         }
     }
     else
     {
         enumerator_t *enumerator;
         enumerator = this->entries->create_enumerator(this->entries);
         while (enumerator->enumerate(enumerator, &vip, &entry))
         {
             cb(user, TRUE, entry->vip, entry->other, entry->id,
                entry->name, entry->unique_id);
             matches++;
         }
         enumerator->destroy(enumerator);
     }
     this->lock->unlock(this->lock);
     return matches;
 }
METHOD (lookip_listener_t , add_listener , void , private_lookip_listener_t * this, lookip_callback_t cb, void * user)
Definition at line 278 of file lookip_listener.c.
References INIT, listener, lock, and spinlock_t::unlock.
 {
     listener_entry_t *listener;
     INIT(listener,
         .cb = cb,
         .user = user,
     );
     this->lock->write_lock(this->lock);
     this->listeners->insert_last(this->listeners, listener);
     this->lock->unlock(this->lock);
 }
METHOD (lookip_listener_t , remove_listener , void , private_lookip_listener_t * this, void * user)
Definition at line 293 of file lookip_listener.c.
References enumerator_t::destroy, enumerator_t::enumerate, free(), listener, lock, spinlock_t::unlock, and listener_entry_t::user.
 {
     listener_entry_t *listener;
     enumerator_t *enumerator;
     this->lock->write_lock(this->lock);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &listener))
     {
         if (listener->user == user)
         {
             this->listeners->remove_at(this->listeners, enumerator);
             free(listener);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (lookip_listener_t , destroy , void , private_lookip_listener_t * this)
Definition at line 313 of file lookip_listener.c.
References spinlock_t::destroy, free(), and lock.
 {
     this->listeners->destroy_function(this->listeners, free);
     this->entries->destroy(this->entries);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool notify_down (listener_entry_t * listener, entry_t * entry) static
Compare callback that invokes down callback of all registered listeners
Definition at line 122 of file lookip_listener.c.
References listener_entry_t::cb, FALSE, free(), entry_t::id, entry_t::name, entry_t::other, TRUE, entry_t::unique_id, listener_entry_t::user, and entry_t::vip.
Referenced by remove_entry().
 {
     if (!listener->cb(listener->user, FALSE, entry->vip, entry->other,
                       entry->id, entry->name, entry->unique_id))
     {
         free(listener);
         return TRUE;
     }
     return FALSE;
 }
static bool notify_up (listener_entry_t * listener, entry_t * entry) static
Compare callback that invokes up callback of all registered listeners
Definition at line 108 of file lookip_listener.c.
References listener_entry_t::cb, FALSE, free(), entry_t::id, entry_t::name, entry_t::other, TRUE, entry_t::unique_id, listener_entry_t::user, and entry_t::vip.
Referenced by add_entry().
 {
     if (!listener->cb(listener->user, TRUE, entry->vip, entry->other,
                       entry->id, entry->name, entry->unique_id))
     {
         free(listener);
         return TRUE;
     }
     return FALSE;
 }
static void remove_entry (private_lookip_listener_t * this, ike_sa_t * ike_sa) static
Remove an entry from the hashtable
Definition at line 175 of file lookip_listener.c.
References ike_sa_t::create_virtual_ip_enumerator, enumerator_t::destroy, entry_destroy(), enumerator_t::enumerate, FALSE, lock, notify_down(), spinlock_t::unlock, and vip.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     host_t *vip;
     entry_t *entry;
     enumerator = ike_sa->create_virtual_ip_enumerator(ike_sa, FALSE);
     while (enumerator->enumerate(enumerator, &vip))
     {
         this->lock->write_lock(this->lock);
         entry = this->entries->remove(this->entries, vip);
         this->lock->unlock(this->lock);
         if (entry)
         {
             this->lock->read_lock(this->lock);
             this->listeners->remove(this->listeners, entry, (void*)notify_down);
             this->lock->unlock(this->lock);
             entry_destroy(entry);
         }
     }
     enumerator->destroy(enumerator);
 }