strongSwan: callback_cred.c File Reference
callback_cred.c File Reference
#include "callback_cred.h"
Classes
struct private_callback_cred_t
struct shared_enumerator_t
Typedefs
typedef struct
private_callback_cred_t private_callback_cred_t
Functions
METHOD (enumerator_t, shared_enumerate, bool, shared_enumerator_t *this, shared_key_t **out, id_match_t *match_me, id_match_t *match_other)
METHOD (enumerator_t, shared_destroy, void, shared_enumerator_t *this)
METHOD (credential_set_t, create_shared_enumerator, enumerator_t *, private_callback_cred_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
METHOD (callback_cred_t, destroy, void, private_callback_cred_t *this)
static private_callback_cred_t * create_generic (void *cb, void *data)
callback_cred_t * callback_cred_create_shared (callback_cred_shared_cb_t cb, void *data)
Typedef Documentation
typedef struct private_callback_cred_t private_callback_cred_t
Definition at line 18 of file callback_cred.c.
Function Documentation
static private_callback_cred_t* create_generic (void * cb, void * data) static
Create a generic callback credential set
Definition at line 112 of file callback_cred.c.
References create_private_enumerator(), destroy(), INIT, nop(), and return_null().
Referenced by callback_cred_create_shared().
 {
     private_callback_cred_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_shared_enumerator = (void*)return_null,
                 .create_private_enumerator = (void*)return_null,
                 .create_cert_enumerator = (void*)return_null,
                 .create_cdp_enumerator  = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .destroy = _destroy,
         },
         .cb.generic = cb,
         .data = data,
     );
     return this;
 }
METHOD (enumerator_t , shared_enumerate , bool , shared_enumerator_t * this, shared_key_t ** out, id_match_t * match_me, id_match_t * match_other)
Definition at line 62 of file callback_cred.c.
References cb(), data, DESTROY_IF, FALSE, me, TRUE, and type.
 {
     DESTROY_IF(this->current);
     this->current = this->this->cb.shared(this->this->data, this->type,
                                 this->me, this->other, match_me, match_other);
     if (this->current)
     {
         *out = this->current;
         return TRUE;
     }
     return FALSE;
 }
METHOD (enumerator_t , shared_destroy , void , shared_enumerator_t * this)
Definition at line 77 of file callback_cred.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     free(this);
 }
METHOD (credential_set_t , create_shared_enumerator , enumerator_t * , private_callback_cred_t * this, shared_key_type_t type, identification_t * me, identification_t * other)
Definition at line 84 of file callback_cred.c.
References destroy(), INIT, and shared_enumerator_t::public.
 {
     shared_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_shared_enumerate,
             .destroy = _shared_destroy,
         },
         .this = this,
         .type = type,
         .me = me,
         .other = other,
     );
     return &enumerator->public;
 }
METHOD (callback_cred_t , destroy , void , private_callback_cred_t * this)
Definition at line 103 of file callback_cred.c.
References free().
 {
     free(this);
 }