strongSwan: tcg_swid_attr_tag_id_inv.c File Reference
tcg_swid_attr_tag_id_inv.c File Reference
#include "tcg_swid_attr_tag_id_inv.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_swid_attr_tag_id_inv_t
Macros
#define TCG_SWID_TAG_ID_INV_RESERVED 0x00
Typedefs
typedef struct
private_tcg_swid_attr_tag_id_inv_t private_tcg_swid_attr_tag_id_inv_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_swid_attr_tag_id_inv_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_swid_attr_tag_id_inv_t *this, uint32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_swid_attr_tag_id_inv_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (tcg_swid_attr_tag_id_inv_t, add, void, private_tcg_swid_attr_tag_id_inv_t *this, swid_tag_id_t *tag_id)
METHOD (tcg_swid_attr_tag_id_inv_t, get_request_id, uint32_t, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (tcg_swid_attr_tag_id_inv_t, get_last_eid, uint32_t, private_tcg_swid_attr_tag_id_inv_t *this, uint32_t *eid_epoch)
METHOD (tcg_swid_attr_tag_id_inv_t, get_tag_id_count, uint32_t, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (tcg_swid_attr_tag_id_inv_t, get_inventory, swid_inventory_t *, private_tcg_swid_attr_tag_id_inv_t *this)
METHOD (tcg_swid_attr_tag_id_inv_t, clear_inventory, void, private_tcg_swid_attr_tag_id_inv_t *this)
pa_tnc_attr_t * tcg_swid_attr_tag_id_inv_create (uint32_t request_id, uint32_t eid_epoch, uint32_t eid)
pa_tnc_attr_t * tcg_swid_attr_tag_id_inv_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define TCG_SWID_TAG_ID_INV_RESERVED 0x00
SWID Tag Identifier Inventory see section 4.8 of TCG TNC SWID Message and Attributes for IF-M
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Tag ID Count | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Request ID Copy | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | EID Epoch | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Last EID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Tag Creator Length | Tag Creator (variable length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Unique Software ID Length |Unique Software ID (var length)| +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Instance ID Length | Instance ID (variable length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 49 of file tcg_swid_attr_tag_id_inv.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_swid_attr_tag_id_inv_t private_tcg_swid_attr_tag_id_inv_t
Definition at line 24 of file tcg_swid_attr_tag_id_inv.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 122 of file tcg_swid_attr_tag_id_inv.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 128 of file tcg_swid_attr_tag_id_inv.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 134 of file tcg_swid_attr_tag_id_inv.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_swid_attr_tag_id_inv_t * this, bool noskip)
Definition at line 140 of file tcg_swid_attr_tag_id_inv.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 146 of file tcg_swid_attr_tag_id_inv.c.
References bio_writer_create(), enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::extract_buf, swid_tag_id_t::get_tag_creator, swid_tag_id_t::get_unique_sw_id, length, segment, TCG_SWID_TAG_ID_INV_MIN_SIZE, TCG_SWID_TAG_ID_INV_RESERVED, value, bio_writer_t::write_data16, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     swid_tag_id_t *tag_id;
     chunk_t tag_creator, unique_sw_id, instance_id;
     enumerator_t *enumerator;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(TCG_SWID_TAG_ID_INV_MIN_SIZE);
     writer->write_uint8 (writer, TCG_SWID_TAG_ID_INV_RESERVED);
     writer->write_uint24(writer, this->inventory->get_count(this->inventory));
     writer->write_uint32(writer, this->request_id);
     writer->write_uint32(writer, this->eid_epoch);
     writer->write_uint32(writer, this->last_eid);
     enumerator = this->inventory->create_enumerator(this->inventory);
     while (enumerator->enumerate(enumerator, &tag_id))
     {
         tag_creator = tag_id->get_tag_creator(tag_id);
         unique_sw_id = tag_id->get_unique_sw_id(tag_id, &instance_id);
         writer->write_data16(writer, tag_creator);
         writer->write_data16(writer, unique_sw_id);
         writer->write_data16(writer, instance_id);
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->segment = this->value;
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_swid_attr_tag_id_inv_t * this, uint32_t * offset)
Definition at line 183 of file tcg_swid_attr_tag_id_inv.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, end, FAILED, length, NEED_MORE, offset, bio_reader_t::peek, pen_names, PEN_TCG, bio_reader_t::read_data16, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, status, SUCCESS, swid_tag_id_create(), tcg_attr_names, TCG_SWID_TAG_ID_INV_MIN_SIZE, type, and value.
 {
     bio_reader_t *reader;
     uint8_t reserved;
     chunk_t tag_creator, unique_sw_id, instance_id;
     swid_tag_id_t *tag_id;
     status_t status = NEED_MORE;
     if (this->offset == 0)
     {
         if (this->length < TCG_SWID_TAG_ID_INV_MIN_SIZE)
         {
             DBG1(DBG_TNC, "insufficient data for %N/%N", pen_names, PEN_TCG,
                            tcg_attr_names, this->type.type);
             *offset = this->offset;
             return FAILED;
         }
         if (this->value.len < TCG_SWID_TAG_ID_INV_MIN_SIZE)
         {
             return NEED_MORE;
         }
         reader = bio_reader_create(this->value);
         reader->read_uint8 (reader, &reserved);
         reader->read_uint24(reader, &this->tag_id_count);
         reader->read_uint32(reader, &this->request_id);
         reader->read_uint32(reader, &this->eid_epoch);
         reader->read_uint32(reader, &this->last_eid);
         this->offset = TCG_SWID_TAG_ID_INV_MIN_SIZE;
         this->value = reader->peek(reader);
         reader->destroy(reader);
     }
     reader = bio_reader_create(this->value);
     while (this->tag_id_count)
     {
         if (!reader->read_data16(reader, &tag_creator)  ||
             !reader->read_data16(reader, &unique_sw_id) ||
             !reader->read_data16(reader, &instance_id))
         {
             goto end;
         }
         tag_id = swid_tag_id_create(tag_creator, unique_sw_id, instance_id);
         this->inventory->add(this->inventory, tag_id);
         this->offset += this->value.len - reader->remaining(reader);
         this->value = reader->peek(reader);
         /* at least one tag ID was processed */
         status = SUCCESS;
         this->tag_id_count--;
     }
     if (this->length != this->offset)
     {
         DBG1(DBG_TNC, "inconsistent length for %N/%N", pen_names, PEN_TCG,
                        tcg_attr_names, this->type.type);
         *offset = this->offset;
         status = FAILED;
     }
 end:
     reader->destroy(reader);
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_swid_attr_tag_id_inv_t * this, chunk_t segment)
Definition at line 249 of file tcg_swid_attr_tag_id_inv.c.
References chunk_cat, chunk_free(), and value.
 {
     this->value = chunk_cat("cc", this->value, segment);
     chunk_free(&this->segment);
     this->segment = this->value;
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 257 of file tcg_swid_attr_tag_id_inv.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 264 of file tcg_swid_attr_tag_id_inv.c.
References free(), chunk_t::ptr, ref_put(), and segment.
 {
     if (ref_put(&this->ref))
     {
         this->inventory->destroy(this->inventory);
         free(this->segment.ptr);
         free(this);
     }
 }
METHOD (tcg_swid_attr_tag_id_inv_t , add , void , private_tcg_swid_attr_tag_id_inv_t * this, swid_tag_id_t * tag_id)
Definition at line 275 of file tcg_swid_attr_tag_id_inv.c.
 {
     this->inventory->add(this->inventory, tag_id);
 }
METHOD (tcg_swid_attr_tag_id_inv_t , get_request_id , uint32_t , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 281 of file tcg_swid_attr_tag_id_inv.c.
 {
     return this->request_id;
 }
METHOD (tcg_swid_attr_tag_id_inv_t , get_last_eid , uint32_t , private_tcg_swid_attr_tag_id_inv_t * this, uint32_t * eid_epoch)
Definition at line 287 of file tcg_swid_attr_tag_id_inv.c.
 {
     if (eid_epoch)
     {
         *eid_epoch = this->eid_epoch;
     }
     return this->last_eid;
 }
METHOD (tcg_swid_attr_tag_id_inv_t , get_tag_id_count , uint32_t , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 297 of file tcg_swid_attr_tag_id_inv.c.
 {
     return this->tag_id_count;
 }
METHOD (tcg_swid_attr_tag_id_inv_t , get_inventory , swid_inventory_t * , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 303 of file tcg_swid_attr_tag_id_inv.c.
 {
     return this->inventory;
 }
METHOD (tcg_swid_attr_tag_id_inv_t , clear_inventory , void , private_tcg_swid_attr_tag_id_inv_t * this)
Definition at line 309 of file tcg_swid_attr_tag_id_inv.c.
References FALSE, and swid_inventory_create().
 {
     this->inventory->destroy(this->inventory);
     this->inventory = swid_inventory_create(FALSE);
 }