strongSwan: openssl_ec_private_key.c File Reference
openssl_ec_private_key.c File Reference
#include <openssl/opensslconf.h>
#include "openssl_ec_private_key.h"
#include "openssl_ec_public_key.h"
#include "openssl_util.h"
#include <utils/debug.h>
#include <openssl/evp.h>
#include <openssl/ecdsa.h>
#include <openssl/x509.h>
Classes
struct private_openssl_ec_private_key_t
Typedefs
typedef struct
private_openssl_ec_private_key_t private_openssl_ec_private_key_t
Functions
bool openssl_ec_fingerprint (EC_KEY *ec, cred_encoding_type_t type, chunk_t *fp)
static bool build_signature (private_openssl_ec_private_key_t *this, chunk_t hash, chunk_t *signature)
static bool build_curve_signature (private_openssl_ec_private_key_t *this, signature_scheme_t scheme, int nid_hash, int nid_curve, chunk_t data, chunk_t *signature)
static bool build_der_signature (private_openssl_ec_private_key_t *this, int hash_nid, chunk_t data, chunk_t *signature)
METHOD (private_key_t, sign, bool, private_openssl_ec_private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
METHOD (private_key_t, decrypt, bool, private_openssl_ec_private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
METHOD (private_key_t, get_keysize, int, private_openssl_ec_private_key_t *this)
METHOD (private_key_t, get_type, key_type_t, private_openssl_ec_private_key_t *this)
METHOD (private_key_t, get_public_key, public_key_t *, private_openssl_ec_private_key_t *this)
METHOD (private_key_t, get_fingerprint, bool, private_openssl_ec_private_key_t *this, cred_encoding_type_t type, chunk_t *fingerprint)
METHOD (private_key_t, get_encoding, bool, private_openssl_ec_private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (private_key_t, get_ref, private_key_t *, private_openssl_ec_private_key_t *this)
METHOD (private_key_t, destroy, void, private_openssl_ec_private_key_t *this)
static
private_openssl_ec_private_key_t * create_empty (void)
openssl_ec_private_key_t * openssl_ec_private_key_gen (key_type_t type, va_list args)
openssl_ec_private_key_t * openssl_ec_private_key_load (key_type_t type, va_list args)
Typedef Documentation
typedef struct private_openssl_ec_private_key_t private_openssl_ec_private_key_t
Definition at line 31 of file openssl_ec_private_key.c.
Function Documentation
static bool build_curve_signature (private_openssl_ec_private_key_t * this, signature_scheme_t scheme, int nid_hash, int nid_curve, chunk_t data, chunk_t * signature) static
Build a RFC 4754 signature for a specified curve and hash algorithm
Definition at line 79 of file openssl_ec_private_key.c.
References build_signature(), chunk_free(), DBG1, DBG_LIB, FALSE, hash, openssl_hash_chunk(), and signature_scheme_names.
Referenced by METHOD().
 {
     const EC_GROUP *my_group;
     EC_GROUP *req_group;
     chunk_t hash;
     bool built;
     req_group = EC_GROUP_new_by_curve_name(nid_curve);
     if (!req_group)
     {
         DBG1(DBG_LIB, "signature scheme %N not supported in EC (required curve "
              "not supported)", signature_scheme_names, scheme);
         return FALSE;
     }
     my_group = EC_KEY_get0_group(this->ec);
     if (EC_GROUP_cmp(my_group, req_group, NULL) != 0)
     {
         DBG1(DBG_LIB, "signature scheme %N not supported by private key",
              signature_scheme_names, scheme);
         return FALSE;
     }
     EC_GROUP_free(req_group);
     if (!openssl_hash_chunk(nid_hash, data, &hash))
     {
         return FALSE;
     }
     built = build_signature(this, hash, signature);
     chunk_free(&hash);
     return built;
 }
static bool build_der_signature (private_openssl_ec_private_key_t * this, int hash_nid, chunk_t data, chunk_t * signature) static
Build a DER encoded signature as in RFC 3279
Definition at line 115 of file openssl_ec_private_key.c.
References chunk_alloc, FALSE, free(), hash, chunk_t::len, openssl_hash_chunk(), chunk_t::ptr, and sig.
Referenced by METHOD().
 {
     chunk_t hash, sig;
     int siglen = 0;
     bool built;
     if (!openssl_hash_chunk(hash_nid, data, &hash))
     {
         return FALSE;
     }
     sig = chunk_alloc(ECDSA_size(this->ec));
     built = ECDSA_sign(0, hash.ptr, hash.len, sig.ptr, &siglen, this->ec) == 1;
     sig.len = siglen;
     if (built)
     {
         *signature = sig;
     }
     else
     {
         free(sig.ptr);
     }
     free(hash.ptr);
     return built;
 }
static bool build_signature (private_openssl_ec_private_key_t * this, chunk_t hash, chunk_t * signature) static
Build a signature as in RFC 4754
Definition at line 59 of file openssl_ec_private_key.c.
References EC_FIELD_ELEMENT_LEN, FALSE, chunk_t::len, openssl_bn_cat(), chunk_t::ptr, and sig.
Referenced by build_curve_signature(), and METHOD().
 {
     bool built = FALSE;
     ECDSA_SIG *sig;
     sig = ECDSA_do_sign(hash.ptr, hash.len, this->ec);
     if (sig)
     {
         /* concatenate BNs r/s to a signature chunk */
         built = openssl_bn_cat(EC_FIELD_ELEMENT_LEN(EC_KEY_get0_group(this->ec)),
                                sig->r, sig->s, signature);
         ECDSA_SIG_free(sig);
     }
     return built;
 }
static private_openssl_ec_private_key_t* create_empty (void) static
Internal generic constructor
Definition at line 274 of file openssl_ec_private_key.c.
References INIT, private_key_belongs_to(), private_key_equals(), and private_key_has_fingerprint().
Referenced by openssl_ec_private_key_gen(), and openssl_ec_private_key_load().
 {
     private_openssl_ec_private_key_t *this;
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .sign = _sign,
                 .decrypt = _decrypt,
                 .get_keysize = _get_keysize,
                 .get_public_key = _get_public_key,
                 .equals = private_key_equals,
                 .belongs_to = private_key_belongs_to,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = private_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     return this;
 }
METHOD (private_key_t , sign , bool , private_openssl_ec_private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * signature)
Definition at line 141 of file openssl_ec_private_key.c.
References build_curve_signature(), build_der_signature(), build_signature(), DBG1, DBG_LIB, FALSE, SIGN_ECDSA_256, SIGN_ECDSA_384, SIGN_ECDSA_521, SIGN_ECDSA_WITH_NULL, SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER, and signature_scheme_names.
 {
     switch (scheme)
     {
         case SIGN_ECDSA_WITH_NULL:
             return build_signature(this, data, signature);
         case SIGN_ECDSA_WITH_SHA1_DER:
             return build_der_signature(this, NID_sha1, data, signature);
         case SIGN_ECDSA_WITH_SHA256_DER:
             return build_der_signature(this, NID_sha256, data, signature);
         case SIGN_ECDSA_WITH_SHA384_DER:
             return build_der_signature(this, NID_sha384, data, signature);
         case SIGN_ECDSA_WITH_SHA512_DER:
             return build_der_signature(this, NID_sha512, data, signature);
         case SIGN_ECDSA_256:
             return build_curve_signature(this, scheme, NID_sha256,
                                          NID_X9_62_prime256v1, data, signature);
         case SIGN_ECDSA_384:
             return build_curve_signature(this, scheme, NID_sha384,
                                          NID_secp384r1, data, signature);
         case SIGN_ECDSA_521:
             return build_curve_signature(this, scheme, NID_sha512,
                                          NID_secp521r1, data, signature);
         default:
             DBG1(DBG_LIB, "signature scheme %N not supported",
                  signature_scheme_names, scheme);
             return FALSE;
     }
 }
METHOD (private_key_t , decrypt , bool , private_openssl_ec_private_key_t * this, encryption_scheme_t scheme, chunk_t crypto, chunk_t * plain)
Definition at line 173 of file openssl_ec_private_key.c.
References DBG1, DBG_LIB, and FALSE.
 {
     DBG1(DBG_LIB, "EC private key decryption not implemented");
     return FALSE;
 }
METHOD (private_key_t , get_keysize , int , private_openssl_ec_private_key_t * this)
Definition at line 181 of file openssl_ec_private_key.c.
 {
     return EC_GROUP_get_degree(EC_KEY_get0_group(this->ec));
 }
METHOD (private_key_t , get_type , key_type_t , private_openssl_ec_private_key_t * this)
Definition at line 187 of file openssl_ec_private_key.c.
References KEY_ECDSA.
 {
     return KEY_ECDSA;
 }
METHOD (private_key_t , get_public_key , public_key_t * , private_openssl_ec_private_key_t * this)
Definition at line 193 of file openssl_ec_private_key.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, chunk_alloc, credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, free(), key, KEY_ECDSA, lib, and chunk_t::ptr.
 {
     public_key_t *public;
     chunk_t key;
     u_char *p;
     key = chunk_alloc(i2d_EC_PUBKEY(this->ec, NULL));
     p = key.ptr;
     i2d_EC_PUBKEY(this->ec, &p);
     public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_ECDSA,
                                 BUILD_BLOB_ASN1_DER, key, BUILD_END);
     free(key.ptr);
     return public;
 }
METHOD (private_key_t , get_fingerprint , bool , private_openssl_ec_private_key_t * this, cred_encoding_type_t type, chunk_t * fingerprint)
Definition at line 210 of file openssl_ec_private_key.c.
References openssl_ec_fingerprint().
 {
     return openssl_ec_fingerprint(this->ec, type, fingerprint);
 }
METHOD (private_key_t , get_encoding , bool , private_openssl_ec_private_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 217 of file openssl_ec_private_key.c.
References chunk_alloc, chunk_clear(), CRED_PART_ECDSA_PRIV_ASN1_DER, CRED_PART_END, cred_encoding_t::encode, encoding, library_t::encoding, FALSE, lib, PRIVKEY_ASN1_DER, PRIVKEY_PEM, chunk_t::ptr, and TRUE.
 {
     u_char *p;
     switch (type)
     {
         case PRIVKEY_ASN1_DER:
         case PRIVKEY_PEM:
         {
             bool success = TRUE;
             *encoding = chunk_alloc(i2d_ECPrivateKey(this->ec, NULL));
             p = encoding->ptr;
             i2d_ECPrivateKey(this->ec, &p);
             if (type == PRIVKEY_PEM)
             {
                 chunk_t asn1_encoding = *encoding;
                 success = lib->encoding->encode(lib->encoding, PRIVKEY_PEM,
                                 NULL, encoding, CRED_PART_ECDSA_PRIV_ASN1_DER,
                                 asn1_encoding, CRED_PART_END);
                 chunk_clear(&asn1_encoding);
             }
             return success;
         }
         default:
             return FALSE;
     }
 }
METHOD (private_key_t , get_ref , private_key_t * , private_openssl_ec_private_key_t * this)
Definition at line 250 of file openssl_ec_private_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (private_key_t , destroy , void , private_openssl_ec_private_key_t * this)
Definition at line 257 of file openssl_ec_private_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), lib, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         if (this->ec)
         {
             lib->encoding->clear_cache(lib->encoding, this->ec);
             EC_KEY_free(this->ec);
         }
         free(this);
     }
 }
bool openssl_ec_fingerprint (EC_KEY * ec, cred_encoding_type_t type, chunk_t * fp)
Calculate fingerprint from a EC_KEY, also used in ec private key.
Definition at line 188 of file openssl_ec_public_key.c.
References hasher_t::allocate_hash, cred_encoding_t::cache, chunk_alloc, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, library_t::encoding, FALSE, free(), cred_encoding_t::get_cache, HASH_SHA1, hasher, key, KEYID_PUBKEY_INFO_SHA1, KEYID_PUBKEY_SHA1, lib, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     hasher_t *hasher;
     chunk_t key;
     u_char *p;
     if (lib->encoding->get_cache(lib->encoding, type, ec, fp))
     {
         return TRUE;
     }
     switch (type)
     {
         case KEYID_PUBKEY_SHA1:
             key = chunk_alloc(i2o_ECPublicKey(ec, NULL));
             p = key.ptr;
             i2o_ECPublicKey(ec, &p);
             break;
         case KEYID_PUBKEY_INFO_SHA1:
             key = chunk_alloc(i2d_EC_PUBKEY(ec, NULL));
             p = key.ptr;
             i2d_EC_PUBKEY(ec, &p);
             break;
         default:
             return FALSE;
     }
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher || !hasher->allocate_hash(hasher, key, fp))
     {
         DBG1(DBG_LIB, "SHA1 hash algorithm not supported, fingerprinting failed");
         DESTROY_IF(hasher);
         free(key.ptr);
         return FALSE;
     }
     hasher->destroy(hasher);
     free(key.ptr);
     lib->encoding->cache(lib->encoding, type, ec, *fp);
     return TRUE;
 }