strongSwan: tcg_pts_attr_dh_nonce_params_req.c File Reference
tcg_pts_attr_dh_nonce_params_req.c File Reference
#include "tcg_pts_attr_dh_nonce_params_req.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_dh_nonce_params_req_t
Macros
#define PTS_DH_NONCE_PARAMS_REQ_SIZE 4
#define PTS_DH_NONCE_PARAMS_REQ_RESERVED 0x00
Typedefs
typedef struct
private_tcg_pts_attr_dh_nonce_params_req_t private_tcg_pts_attr_dh_nonce_params_req_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_dh_nonce_params_req_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_dh_nonce_params_req_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_dh_nonce_params_req_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_dh_nonce_params_req_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_dh_nonce_params_req_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_dh_nonce_params_req_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_dh_nonce_params_req_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_dh_nonce_params_req_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_dh_nonce_params_req_t *this)
METHOD (tcg_pts_attr_dh_nonce_params_req_t, get_min_nonce_len, u_int8_t, private_tcg_pts_attr_dh_nonce_params_req_t *this)
METHOD (tcg_pts_attr_dh_nonce_params_req_t, get_dh_groups, pts_dh_group_t, private_tcg_pts_attr_dh_nonce_params_req_t *this)
pa_tnc_attr_t * tcg_pts_attr_dh_nonce_params_req_create (u_int8_t min_nonce_len, pts_dh_group_t dh_groups)
pa_tnc_attr_t * tcg_pts_attr_dh_nonce_params_req_create_from_data (size_t length, chunk_t value)
Macro Definition Documentation
#define PTS_DH_NONCE_PARAMS_REQ_RESERVED 0x00
Definition at line 40 of file tcg_pts_attr_dh_nonce_params_req.c.
Referenced by METHOD().
#define PTS_DH_NONCE_PARAMS_REQ_SIZE 4
PTS DH Nonce Parameters Request see section 3.8.1 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Min. Nonce Len | D-H Group Set | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 39 of file tcg_pts_attr_dh_nonce_params_req.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_dh_nonce_params_req_t private_tcg_pts_attr_dh_nonce_params_req_t
Definition at line 24 of file tcg_pts_attr_dh_nonce_params_req.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 88 of file tcg_pts_attr_dh_nonce_params_req.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 94 of file tcg_pts_attr_dh_nonce_params_req.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 100 of file tcg_pts_attr_dh_nonce_params_req.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_dh_nonce_params_req_t * this, bool noskip)
Definition at line 106 of file tcg_pts_attr_dh_nonce_params_req.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 112 of file tcg_pts_attr_dh_nonce_params_req.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, PTS_DH_NONCE_PARAMS_REQ_RESERVED, PTS_DH_NONCE_PARAMS_REQ_SIZE, value, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PTS_DH_NONCE_PARAMS_REQ_SIZE);
     writer->write_uint8 (writer, PTS_DH_NONCE_PARAMS_REQ_RESERVED);
     writer->write_uint8 (writer, this->min_nonce_len);
     writer->write_uint16(writer, this->dh_groups);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_dh_nonce_params_req_t * this, u_int32_t * offset)
Definition at line 131 of file tcg_pts_attr_dh_nonce_params_req.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, PTS_DH_NONCE_PARAMS_REQ_SIZE, bio_reader_t::read_uint16, bio_reader_t::read_uint8, reserved, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int8_t reserved;
     u_int16_t dh_groups;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_DH_NONCE_PARAMS_REQ_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for PTS DH Nonce Parameters Request");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8(reader, &reserved);
     reader->read_uint8(reader, &this->min_nonce_len);
     reader->read_uint16(reader, &dh_groups);
     this->dh_groups = dh_groups;
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_dh_nonce_params_req_t * this, chunk_t segment)
Definition at line 159 of file tcg_pts_attr_dh_nonce_params_req.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 165 of file tcg_pts_attr_dh_nonce_params_req.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 172 of file tcg_pts_attr_dh_nonce_params_req.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_dh_nonce_params_req_t , get_min_nonce_len , u_int8_t , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 182 of file tcg_pts_attr_dh_nonce_params_req.c.
 {
     return this->min_nonce_len;
 }
METHOD (tcg_pts_attr_dh_nonce_params_req_t , get_dh_groups , pts_dh_group_t , private_tcg_pts_attr_dh_nonce_params_req_t * this)
Definition at line 188 of file tcg_pts_attr_dh_nonce_params_req.c.
 {
     return this->dh_groups;
 }