strongSwan: charon-nm.c File Reference
charon-nm.c File Reference
#include <stdio.h>
#include <syslog.h>
#include <signal.h>
#include <sys/types.h>
#include <unistd.h>
#include <errno.h>
#include <hydra.h>
#include <daemon.h>
#include <library.h>
#include <utils/backtrace.h>
#include <threading/thread.h>
#include <nm/nm_backend.h>
Macros
#define IPSEC_USER NULL
#define IPSEC_GROUP NULL
Functions
static void dbg_syslog (debug_t group, level_t level, char *fmt,...)
static void run ()
static void segv_handler (int signal)
static bool lookup_uid_gid ()
int main (int argc, char *argv[])
Variables
void(* dbg)(debug_t group, level_t level, char *fmt,...)
Macro Definition Documentation
#define IPSEC_GROUP NULL
Definition at line 40 of file charon-nm.c.
Referenced by lookup_uid_gid().
#define IPSEC_USER NULL
Default user and group
Definition at line 36 of file charon-nm.c.
Referenced by lookup_uid_gid().
Function Documentation
static void dbg_syslog (debug_t group, level_t level, char * fmt, ...) static
Simple logging hook for library logs, using syslog output
Definition at line 51 of file charon-nm.c.
References debug_names, snprintf, and vsnprintf.
Referenced by main().
 {
     if (level <= 1)
     {
         char buffer[8192], groupstr[4];
         va_list args;
         va_start(args, fmt);
         /* write in memory buffer first */
         vsnprintf(buffer, sizeof(buffer), fmt, args);
         /* cache group name */
         snprintf(groupstr, sizeof(groupstr), "%N", debug_names, group);
         syslog(LOG_DAEMON|LOG_INFO, "00[%s] %s", groupstr, buffer);
         va_end(args);
     }
 }
static bool lookup_uid_gid () static
Lookup UID and GID
Definition at line 132 of file charon-nm.c.
References library_t::caps, FALSE, settings_t::get_str, IPSEC_GROUP, IPSEC_USER, lib, name, capabilities_t::resolve_gid, capabilities_t::resolve_uid, library_t::settings, and TRUE.
Referenced by main().
 {
     char *name;
     name = lib->settings->get_str(lib->settings, "charon-nm.user",
                                   IPSEC_USER);
     if (name && !lib->caps->resolve_uid(lib->caps, name))
     {
         return FALSE;
     }
     name = lib->settings->get_str(lib->settings, "charon-nm.group",
                                   IPSEC_GROUP);
     if (name && !lib->caps->resolve_gid(lib->caps, name))
     {
         return FALSE;
     }
     return TRUE;
 }
int main (int argc, char * argv[])
Main function, starts NetworkManager backend.
Definition at line 154 of file charon-nm.c.
References library_t::caps, charon, integrity_checker_t::check_file, dbg, DBG1, DBG_DMN, dbg_syslog(), capabilities_t::drop, FALSE, settings_t::get_int, settings_t::get_str, daemon_t::initialize, library_t::integrity, LEVEL_CTRL, lib, libcharon_deinit(), libcharon_init(), libhydra_deinit(), libhydra_init(), library_deinit(), library_init(), daemon_t::load_loggers, lookup_uid_gid(), nm_backend_register(), PLUGINS, library_t::plugins, run(), segv_handler(), settings_t::set_int, setenv(), library_t::settings, SS_RC_DAEMON_INTEGRITY, SS_RC_INITIALIZATION_FAILED, SS_RC_LIBSTRONGSWAN_INTEGRITY, daemon_t::start, status, and plugin_loader_t::status.
 {
     struct sigaction action;
     int status = SS_RC_INITIALIZATION_FAILED;
     /* logging for library during initialization, as we have no bus yet */
     dbg = dbg_syslog;
     /* LD causes a crash probably due to Glib */
     setenv("LEAK_DETECTIVE_DISABLE", "1", 1);
     /* initialize library */
     if (!library_init(NULL, "charon-nm"))
     {
         library_deinit();
         exit(SS_RC_LIBSTRONGSWAN_INTEGRITY);
     }
     if (lib->integrity &&
         !lib->integrity->check_file(lib->integrity, "charon-nm", argv[0]))
     {
         dbg_syslog(DBG_DMN, 1, "integrity check of charon-nm failed");
         library_deinit();
         exit(SS_RC_DAEMON_INTEGRITY);
     }
     if (!libhydra_init())
     {
         dbg_syslog(DBG_DMN, 1, "initialization failed - aborting charon-nm");
         libhydra_deinit();
         library_deinit();
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     if (!libcharon_init())
     {
         dbg_syslog(DBG_DMN, 1, "initialization failed - aborting charon-nm");
         goto deinit;
     }
     if (!lookup_uid_gid())
     {
         dbg_syslog(DBG_DMN, 1, "invalid uid/gid - aborting charon-nm");
         goto deinit;
     }
     /* make sure we log to the DAEMON facility by default */
     lib->settings->set_int(lib->settings, "charon-nm.syslog.daemon.default",
         lib->settings->get_int(lib->settings,
                                "charon-nm.syslog.daemon.default", 1));
     charon->load_loggers(charon, NULL, FALSE);
     /* use random ports to avoid conflicts with regular charon */
     lib->settings->set_int(lib->settings, "charon-nm.port", 0);
     lib->settings->set_int(lib->settings, "charon-nm.port_natt_t", 0);
     DBG1(DBG_DMN, "Starting charon NetworkManager backend (strongSwan "VERSION")");
     if (lib->integrity)
     {
         DBG1(DBG_DMN, "integrity tests enabled:");
         DBG1(DBG_DMN, "lib    'libstrongswan': passed file and segment integrity tests");
         DBG1(DBG_DMN, "lib    'libhydra': passed file and segment integrity tests");
         DBG1(DBG_DMN, "lib    'libcharon': passed file and segment integrity tests");
         DBG1(DBG_DMN, "daemon 'charon-nm': passed file integrity test");
     }
     /* register NM backend to be loaded with plugins */
     nm_backend_register();
     /* initialize daemon */
     if (!charon->initialize(charon,
             lib->settings->get_str(lib->settings, "charon-nm.load", PLUGINS)))
     {
         DBG1(DBG_DMN, "initialization failed - aborting charon-nm");
         goto deinit;
     }
     lib->plugins->status(lib->plugins, LEVEL_CTRL);
     if (!lib->caps->drop(lib->caps))
     {
         DBG1(DBG_DMN, "capability dropping failed - aborting charon-nm");
         goto deinit;
     }
     /* add handler for SEGV and ILL,
      * INT and TERM are handled by sigwaitinfo() in run() */
     action.sa_handler = segv_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaddset(&action.sa_mask, SIGINT);
     sigaddset(&action.sa_mask, SIGTERM);
     sigaction(SIGSEGV, &action, NULL);
     sigaction(SIGILL, &action, NULL);
     sigaction(SIGBUS, &action, NULL);
     action.sa_handler = SIG_IGN;
     sigaction(SIGPIPE, &action, NULL);
     pthread_sigmask(SIG_SETMASK, &action.sa_mask, NULL);
     /* start daemon (i.e. the threads in the thread-pool) */
     charon->start(charon);
     /* main thread goes to run loop */
     run();
     status = 0;
 deinit:
     libcharon_deinit();
     libhydra_deinit();
     library_deinit();
     return status;
 }
static void run () static
Run the daemon and handle unix signals
Definition at line 71 of file charon-nm.c.
References bus_t::alert, ALERT_SHUTDOWN_SIGNAL, daemon_t::bus, charon, DBG1, DBG_DMN, sig, sigwaitinfo(), strerror, and TRUE.
Referenced by main().
 {
     sigset_t set;
     /* handle SIGINT and SIGTERM in this handler */
     sigemptyset(&set);
     sigaddset(&set, SIGINT);
     sigaddset(&set, SIGTERM);
     sigprocmask(SIG_BLOCK, &set, NULL);
     while (TRUE)
     {
         int sig;
         sig = sigwaitinfo(&set, NULL);
         if (sig == -1)
         {
             if (errno == EINTR)
             {   /* ignore signals we didn't wait for */
                 continue;
             }
             DBG1(DBG_DMN, "waiting for signal failed: %s", strerror(errno));
             return;
         }
         switch (sig)
         {
             case SIGINT:
             {
                 DBG1(DBG_DMN, "signal of type SIGINT received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return;
             }
             case SIGTERM:
             {
                 DBG1(DBG_DMN, "signal of type SIGTERM received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return;
             }
         }
     }
 }
static void segv_handler (int signal) static
Handle SIGSEGV/SIGILL signals raised by threads
Definition at line 116 of file charon-nm.c.
References backtrace, backtrace_create(), DBG1, DBG_DMN, backtrace_t::destroy, backtrace_t::log, thread_current_id(), and TRUE.
Referenced by main().
 {
     backtrace_t *backtrace;
     DBG1(DBG_DMN, "thread %u received %d", thread_current_id(), signal);
     backtrace = backtrace_create(2);
     backtrace->log(backtrace, stderr, TRUE);
     backtrace->destroy(backtrace);
     DBG1(DBG_DMN, "killing ourself, received critical signal");
     abort();
 }
Variable Documentation
void(* dbg)(debug_t group, level_t level, char *fmt,...)
Hook in library for debugging messages
The registered debug hook.
Definition at line 111 of file debug.c.
Referenced by main().