strongSwan: cp_payload
cp_payload
payloads
Classes
struct cp_payload_t
Typedefs
typedef enum config_type_t config_type_t
typedef struct cp_payload_t cp_payload_t
Enumerations
enum config_type_t { CFG_REQUEST = 1, CFG_REPLY = 2, CFG_SET = 3, CFG_ACK = 4 }
Functions
cp_payload_t * cp_payload_create (payload_type_t type)
cp_payload_t * cp_payload_create_type (payload_type_t type, config_type_t cfg_type)
Variables
enum_name_t * config_type_names
Detailed Description
Typedef Documentation
typedef enum config_type_t config_type_t
Definition at line 25 of file cp_payload.h.
typedef struct cp_payload_t cp_payload_t
Definition at line 26 of file cp_payload.h.
Enumeration Type Documentation
enum config_type_t
Config Type of an Configuration Payload.
Enumerator
CFG_REQUEST
CFG_REPLY
CFG_SET
CFG_ACK
Definition at line 36 of file cp_payload.h.
                    {
     CFG_REQUEST = 1,
     CFG_REPLY = 2,
     CFG_SET = 3,
     CFG_ACK = 4,
 };
Function Documentation
cp_payload_t* cp_payload_create (payload_type_t type)
Creates an empty configuration payload
Parameters
type payload type, PLV2_CONFIGURATION or PLV1_CONFIGURATION
Returns
empty configuration payload
Definition at line 329 of file cp_payload.c.
References CFG_REQUEST, and cp_payload_create_type().
Referenced by payload_create().
 {
     return cp_payload_create_type(type, CFG_REQUEST);
 }
cp_payload_t* cp_payload_create_type (payload_type_t type, config_type_t cfg_type)
Creates an cp_payload_t with type and value
Parameters
type payload type, PLV2_CONFIGURATION or PLV1_CONFIGURATION
cfg_type type of configuration payload to create
Returns
created configuration payload
Definition at line 294 of file cp_payload.c.
References INIT, linked_list_create(), PL_NONE, and type.
Referenced by build_ack(), build_reply(), build_request(), build_set(), cp_payload_create(), and METHOD().
 {
     private_cp_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .create_attribute_enumerator = _create_attribute_enumerator,
             .add_attribute = _add_attribute,
             .get_type = _get_config_type,
             .get_identifier = _get_identifier,
             .set_identifier = _set_identifier,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
         .attributes = linked_list_create(),
         .cfg_type = cfg_type,
         .type = type,
     );
     return &this->public;
 }
Variable Documentation
enum_name_t* config_type_names
enum name for config_type_t.
Referenced by process_payloads().