strongSwan: pki.c File Reference
pki.c File Reference
#include "command.h"
#include "pki.h"
#include <time.h>
#include <unistd.h>
#include <fcntl.h>
#include <utils/debug.h>
#include <credentials/sets/mem_cred.h>
#include <credentials/sets/callback_cred.h>
Macros
#define _GNU_SOURCE
Functions
bool get_form (char *form, cred_encoding_type_t *enc, credential_type_t type)
static bool convert_time (char *str, char *format, struct tm *tm)
bool calculate_lifetime (char *format, char *nbstr, char *nastr, time_t span, time_t *nb, time_t *na)
void set_file_mode (FILE *stream, cred_encoding_type_t enc)
hash_algorithm_t get_default_digest (private_key_t *private)
static shared_key_t * cb (void *data, shared_key_type_t type, identification_t *me, identification_t *other, id_match_t *match_me, id_match_t *match_other)
static void add_callback ()
static void remove_callback ()
int main (int argc, char *argv[])
Variables
static callback_cred_t * cb_set
static mem_cred_t * cb_creds
static shared_key_type_t prompted
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file pki.c.
Function Documentation
static void add_callback () static
Register PIN/Passphrase callback function
Definition at line 324 of file pki.c.
References credential_manager_t::add_set, callback_cred_create_shared(), cb(), library_t::credmgr, lib, mem_cred_create(), mem_cred_t::set, and callback_cred_t::set.
Referenced by main().
 {
     cb_set = callback_cred_create_shared(cb, NULL);
     lib->credmgr->add_set(lib->credmgr, &cb_set->set);
     cb_creds = mem_cred_create();
     lib->credmgr->add_set(lib->credmgr, &cb_creds->set);
 }
static shared_key_t* cb (void * data, shared_key_type_t type, identification_t * me, identification_t * other, id_match_t * match_me, id_match_t * match_other) static
Callback function to receive credentials
Definition at line 276 of file pki.c.
References mem_cred_t::add_shared, chunk_clone, chunk_from_str, shared_key_t::get_ref, getpass(), ID_MATCH_NONE, ID_MATCH_PERFECT, prompted, shared_key_create(), SHARED_PIN, SHARED_PRIVATE_KEY_PASS, snprintf, and type.
Referenced by add_callback().
 {
     char buf[64], *label, *secret = NULL;
     shared_key_t *shared;
     if (prompted == type)
     {
         return NULL;
     }
     switch (type)
     {
         case SHARED_PIN:
             label = "Smartcard PIN";
             break;
         case SHARED_PRIVATE_KEY_PASS:
             label = "Private key passphrase";
             break;
         default:
             return NULL;
     }
     snprintf(buf, sizeof(buf), "%s: ", label);
 #ifdef HAVE_GETPASS
     secret = getpass(buf);
 #endif
     if (secret && strlen(secret))
     {
         prompted = type;
         if (match_me)
         {
             *match_me = ID_MATCH_PERFECT;
         }
         if (match_other)
         {
             *match_other = ID_MATCH_NONE;
         }
         shared = shared_key_create(type, chunk_clone(chunk_from_str(secret)));
         /* cache password in case it is required more than once */
         cb_creds->add_shared(cb_creds, shared, NULL);
         return shared->get_ref(shared);
     }
     return NULL;
 }
static bool convert_time (char * str, char * format, struct tm * tm) static
Convert a time string to struct tm using strptime format
Definition at line 112 of file pki.c.
References end, FALSE, fprintf, strptime(), and TRUE.
Referenced by calculate_lifetime().
 {
 #ifdef HAVE_STRPTIME
     char *end;
     if (!format)
     {
         format = "%d.%m.%y %T";
     }
     end = strptime(str, format, tm);
     if (end == NULL || *end != '\0')
     {
         return FALSE;
     }
     return TRUE;
 #else /* !HAVE_STRPTIME */
     if (format)
     {
         fprintf(stderr, "custom datetime string format not supported\n");
         return FALSE;
     }
     if (sscanf(str, "%d.%d.%d %d:%d:%d",
                &tm->tm_mday, &tm->tm_mon, &tm->tm_year,
                &tm->tm_hour, &tm->tm_min, &tm->tm_sec) != 6)
     {
         return FALSE;
     }
     /* strptime() interprets two-digit years > 68 as 19xx, do the same here.
      * mktime() expects years based on 1900 */
     if (tm->tm_year <= 68)
     {
         tm->tm_year += 100;
     }
     else if (tm->tm_year >= 1900)
     {   /* looks like four digits? */
         tm->tm_year -= 1900;
     }
     /* month is specified from 0-11 */
     tm->tm_mon--;
     /* automatically detect daylight saving time */
     tm->tm_isdst = -1;
     return TRUE;
 #endif /* !HAVE_STRPTIME */
 }
int main (int argc, char * argv[])
Library initialization and operation parsing
Definition at line 346 of file pki.c.
References add_callback(), integrity_checker_t::check_file, command_dispatch(), fprintf, settings_t::get_str, library_t::integrity, lib, library_deinit(), library_init(), plugin_loader_t::load, PLUGINS, library_t::plugins, remove_callback(), library_t::settings, SS_RC_DAEMON_INTEGRITY, SS_RC_INITIALIZATION_FAILED, and SS_RC_LIBSTRONGSWAN_INTEGRITY.
 {
     atexit(library_deinit);
     if (!library_init(NULL, "pki"))
     {
         exit(SS_RC_LIBSTRONGSWAN_INTEGRITY);
     }
     if (lib->integrity &&
         !lib->integrity->check_file(lib->integrity, "pki", argv[0]))
     {
         fprintf(stderr, "integrity check of pki failed\n");
         exit(SS_RC_DAEMON_INTEGRITY);
     }
     if (!lib->plugins->load(lib->plugins,
             lib->settings->get_str(lib->settings, "pki.load", PLUGINS)))
     {
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     add_callback();
     atexit(remove_callback);
     return command_dispatch(argc, argv);
 }
static void remove_callback () static
Unregister PIN/Passphrase callback function
Definition at line 335 of file pki.c.
References library_t::credmgr, callback_cred_t::destroy, mem_cred_t::destroy, lib, credential_manager_t::remove_set, mem_cred_t::set, and callback_cred_t::set.
Referenced by main().
 {
     lib->credmgr->remove_set(lib->credmgr, &cb_creds->set);
     cb_creds->destroy(cb_creds);
     lib->credmgr->remove_set(lib->credmgr, &cb_set->set);
     cb_set->destroy(cb_set);
 }
Variable Documentation
mem_cred_t* cb_creds static
Credential set to cache entered secrets
Definition at line 269 of file pki.c.
callback_cred_t* cb_set static
Callback credential set pki uses
Definition at line 264 of file pki.c.
shared_key_type_t prompted static
Definition at line 271 of file pki.c.
Referenced by callback_shared(), and cb().