strongSwan: test
test
utils
Macros
#define EXPORT_FUNCTION_FOR_TESTS(ns, fn)
#define IMPORT_FUNCTION_FOR_TESTS(ns, name, ret,...) static ret (*TEST_##ns##name)(__VA_ARGS__);
#define TEST_FUNCTION(ns, name,...)
Functions
void testable_function_register (char *name, void *fn)
void * testable_function_get (char *name)
Detailed Description
Macro Definition Documentation
#define EXPORT_FUNCTION_FOR_TESTS (ns, fn)
Value:
static void testable_function_register_##fn() __attribute__ ((constructor)); \
static void testable_function_register_##fn() \
{ \
    testable_function_register(#ns "/" #fn, fn); \
} \
static void testable_function_unregister_##fn() __attribute__ ((destructor)); \
static void testable_function_unregister_##fn() \
{ \
    testable_function_register(#ns "/" #fn, NULL); \
}
Macro to automatically register/unregister a function that can be called from tests.
Note
The constructor has a priority set so that it runs after the constructor that creates the hashtable. The destructor, on the other hand, does not have a priority set, as test coverage would report that function as untested otherwise.
Parameters
ns namespace
fn function to register
Definition at line 54 of file test.h.
#define IMPORT_FUNCTION_FOR_TESTS (ns, name, ret, ...) static ret (*TEST_##ns##name)(__VA_ARGS__);
Import a registered function so that it can be called from tests.
Parameters
ns namespace of the function
name name of the function
ret return type of the function
... arguments of the function
Definition at line 74 of file test.h.
#define TEST_FUNCTION (ns, name, ...)
Value:
({ \
    TEST_##ns##name = testable_function_get( #ns "/" #name); \
    if (!TEST_##ns##name) \
    { \
        test_fail_msg(__FILE__, __LINE__, "function " #name " (" #ns ") not found"); \
    } \
    TEST_##ns##name(__VA_ARGS__); \
})
Call a registered function from tests.
Parameters
ns namespace of the function
name name of the function
... arguments for the function
Definition at line 84 of file test.h.
Referenced by START_TEST().
Function Documentation
void* testable_function_get (char * name)
Find a previously registered testable function.
Parameters
name name (namespace/function)
Returns
function, NULL if not found
Definition at line 85 of file test.c.
References hashtable_t::get.
 {
     if (functions)
     {
         return functions->get(functions, name);
     }
     return NULL;
 }
void testable_function_register (char * name, void * fn)
Register a (possibly static) function so that it can be called from tests.
Parameters
name name (namespace/function)
fn function to register (set to NULL to unregister)
Definition at line 44 of file test.c.
References chunk_hash_seed(), hashtable_t::destroy, FALSE, hashtable_t::get_count, has_libtest_linkage(), hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), library_t::leak_detective, lib, hashtable_t::put, hashtable_t::remove, and leak_detective_t::set_state.
 {
     bool old = FALSE;
     if (lib && lib->leak_detective)
     {
         old = lib->leak_detective->set_state(lib->leak_detective, FALSE);
     }
     if (has_libtest_linkage())
     {
         if (!functions)
         {
             chunk_hash_seed();
             functions = hashtable_create(hashtable_hash_str,
                                          hashtable_equals_str, 8);
         }
         if (fn)
         {
             functions->put(functions, name, fn);
         }
         else
         {
             functions->remove(functions, name);
             if (functions->get_count(functions) == 0)
             {
                 functions->destroy(functions);
                 functions = NULL;
             }
         }
     }
     if (lib && lib->leak_detective)
     {
         lib->leak_detective->set_state(lib->leak_detective, old);
     }
 }