strongSwan: seg_env
seg_env
seg
Classes
struct seg_env_t
Typedefs
typedef struct seg_env_t seg_env_t
typedef enum seg_env_flags_t seg_env_flags_t
Enumerations
enum seg_env_flags_t { SEG_ENV_FLAG_NONE = 0, SEG_ENV_FLAG_MORE = (1<<7), SEG_ENV_FLAG_START = (1<<6) }
Functions
seg_env_t * seg_env_create (uint32_t base_attr_id, pa_tnc_attr_t *base_attr, uint32_t max_seg_size)
seg_env_t * seg_env_create_from_data (uint32_t base_attr_id, chunk_t data, uint32_t max_seg_size, pa_tnc_attr_t **error)
Detailed Description
Typedef Documentation
typedef enum seg_env_flags_t seg_env_flags_t
Definition at line 25 of file seg_env.h.
typedef struct seg_env_t seg_env_t
Definition at line 24 of file seg_env.h.
Enumeration Type Documentation
enum seg_env_flags_t
Segment Envelope flags
Enumerator
SEG_ENV_FLAG_NONE
SEG_ENV_FLAG_MORE
SEG_ENV_FLAG_START
Definition at line 34 of file seg_env.h.
                      {
     SEG_ENV_FLAG_NONE =   0,
     SEG_ENV_FLAG_MORE =  (1<<7),
     SEG_ENV_FLAG_START = (1<<6)
 };
Function Documentation
seg_env_t* seg_env_create (uint32_t base_attr_id, pa_tnc_attr_t * base_attr, uint32_t max_seg_size)
Create a PA-TNC attribute segment envelope object
Parameters
base_attr_id Base Attribute ID
base_attr Base Attribute to be segmented, owned by seg_env_t
max_seg_size Maximum segment size
See header
The PA-TNC attribute header must not be segmented and there must be at least a first and one next segment
Definition at line 213 of file seg_env.c.
References base_attr, pa_tnc_attr_t::build, pa_tnc_attr_t::destroy, pa_tnc_attr_t::get_value, INIT, chunk_t::len, max_seg_size, PA_TNC_ATTR_HEADER_SIZE, and value.
Referenced by METHOD(), and START_TEST().
 {
     private_seg_env_t *this;
     chunk_t value;
     base_attr->build(base_attr);
     value = base_attr->get_value(base_attr);
     if (max_seg_size <  PA_TNC_ATTR_HEADER_SIZE ||
         max_seg_size >= PA_TNC_ATTR_HEADER_SIZE + value.len)
     {
         base_attr->destroy(base_attr);
         return NULL;
     }
     INIT(this,
         .public = {
             .get_base_attr_id = _get_base_attr_id,
             .get_base_attr = _get_base_attr,
             .get_base_attr_info = _get_base_attr_info,
             .first_segment = _first_segment,
             .next_segment = _next_segment,
             .add_segment = _add_segment,
             .destroy = _destroy,
         },
         .base_attr_id = base_attr_id,
         .base_attr = base_attr,
         .max_seg_size = max_seg_size,
         .data = base_attr->get_value(base_attr),
     );
     return &this->public;
 }
seg_env_t* seg_env_create_from_data (uint32_t base_attr_id, chunk_t data, uint32_t max_seg_size, pa_tnc_attr_t ** error)
Create a PA-TNC attribute segment envelope object
Parameters
base_attr_id Base Attribute ID
data First attribute segment
max_seg_size Maximum segment size
error Error attribute if a parsing error occurred
See header
Definition at line 255 of file seg_env.c.
References base_attr, bio_reader_create(), pa_tnc_attr_manager_t::create, bio_reader_t::destroy, destroy(), error_code, htoun32(), IETF_ATTR_PA_TNC_ERROR, ietf_attr_pa_tnc_error_create_with_offset(), imcv_pa_tnc_attributes, INIT, max_seg_size, memset, NEED_MORE, offset, PA_ERROR_INVALID_PARAMETER, PA_TNC_ATTR_HEADER_SIZE, PEN_IETF, pen_type_create(), status, SUCCESS, TRUE, type, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by METHOD(), and START_TEST().
 {
     private_seg_env_t *this;
     pen_type_t type, error_code;
     bio_reader_t *reader;
     chunk_t msg_info;
     uint32_t offset = 0, attr_offset;
     status_t status;
     INIT(this,
         .public = {
             .get_base_attr_id = _get_base_attr_id,
             .get_base_attr = _get_base_attr,
             .get_base_attr_info = _get_base_attr_info,
             .first_segment = _first_segment,
             .next_segment = _next_segment,
             .add_segment = _add_segment,
             .destroy = _destroy,
         },
         .base_attr_id = base_attr_id,
         .max_seg_size = max_seg_size,
     );
     /* create info field to be used by PA-TNC error messages */
     memset(this->base_attr_info, 0xff, 4);
     htoun32(this->base_attr_info + 4, base_attr_id);
     msg_info = get_base_attr_info(this);
     /* extract from base attribute segment from data */
     reader = bio_reader_create(data);
     this->base_attr = imcv_pa_tnc_attributes->create(imcv_pa_tnc_attributes,
                                      reader, TRUE, &offset, msg_info, error);
     reader->destroy(reader);
     if (!this->base_attr)
     {
         destroy(this);
         return NULL;
     }
     status = this->base_attr->process(this->base_attr, &attr_offset);
     if (status != SUCCESS && status != NEED_MORE)
     {
         type = this->base_attr->get_type(this->base_attr);
         if (!(type.vendor_id == PEN_IETF &&
               type.type == IETF_ATTR_PA_TNC_ERROR))
         {
             error_code = pen_type_create(PEN_IETF, PA_ERROR_INVALID_PARAMETER);
             *error = ietf_attr_pa_tnc_error_create_with_offset(error_code,
                         msg_info, PA_TNC_ATTR_HEADER_SIZE + attr_offset);
         }
         destroy(this);
         return NULL;
     }
     this->need_more = (status == NEED_MORE);
     return &this->public;
 }