strongSwan: vici_attribute.c File Reference
vici_attribute.c File Reference
#include "vici_attribute.h"
#include "vici_builder.h"
#include <daemon.h>
#include <collections/hashtable.h>
#include <collections/array.h>
#include <threading/rwlock.h>
#include <attributes/mem_pool.h>
Classes
struct private_vici_attribute_t
struct attribute_t
struct pool_t
struct nested_data_t
struct request_data_t
struct load_data_t
Typedefs
typedef struct
private_vici_attribute_t private_vici_attribute_t
Functions
static void attribute_destroy (attribute_t *attr)
static void pool_destroy (pool_t *pool)
static host_t * find_addr (private_vici_attribute_t *this, linked_list_t *pools, identification_t *id, host_t *requested, mem_pool_op_t op, host_t *peer)
METHOD (attribute_provider_t, acquire_address, host_t *, private_vici_attribute_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
METHOD (attribute_provider_t, release_address, bool, private_vici_attribute_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
static bool attr_filter (void *data, attribute_t **attr, configuration_attribute_type_t *type, void *in, chunk_t *value)
CALLBACK (create_nested, enumerator_t *, pool_t *pool, void *this)
CALLBACK (nested_cleanup, void, nested_data_t *data)
static bool have_vips_from_pool (mem_pool_t *pool, linked_list_t *vips)
METHOD (attribute_provider_t, create_attribute_enumerator, enumerator_t *, private_vici_attribute_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
static bool merge_pool (private_vici_attribute_t *this, pool_t *new)
static vici_message_t * create_reply (char *fmt,...)
static mem_pool_t * create_pool_range (char *name, char *buf)
CALLBACK (pool_li, bool, load_data_t *data, vici_message_t *message, char *name, chunk_t value)
CALLBACK (pool_kv, bool, load_data_t *data, vici_message_t *message, char *name, chunk_t value)
CALLBACK (pool_sn, bool, request_data_t *request, vici_message_t *message, vici_parse_context_t *ctx, char *name)
CALLBACK (load_pool, vici_message_t *, private_vici_attribute_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (unload_pool, vici_message_t *, private_vici_attribute_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (get_pools, vici_message_t *, private_vici_attribute_t *this, char *name, u_int id, vici_message_t *message)
static void manage_command (private_vici_attribute_t *this, char *name, vici_command_cb_t cb, bool reg)
static void manage_commands (private_vici_attribute_t *this, bool reg)
METHOD (vici_attribute_t, destroy, void, private_vici_attribute_t *this)
vici_attribute_t * vici_attribute_create (vici_dispatcher_t *dispatcher)
Typedef Documentation
typedef struct private_vici_attribute_t private_vici_attribute_t
Definition at line 28 of file vici_attribute.c.
Function Documentation
static bool attr_filter (void * data, attribute_t ** attr, configuration_attribute_type_t * type, void * in, chunk_t * value) static
Filter mapping attribute_t to enumerated type/value arguments
Definition at line 190 of file vici_attribute.c.
References TRUE.
Referenced by CALLBACK().
 {
     *type = (*attr)->type;
     *value = (*attr)->value;
     return TRUE;
 }
static void attribute_destroy (attribute_t * attr) static
Clean up an attribute
Definition at line 69 of file vici_attribute.c.
References free(), chunk_t::ptr, and attribute_t::value.
Referenced by pool_destroy().
 {
     free(attr->value.ptr);
     free(attr);
 }
CALLBACK (create_nested , enumerator_t * , pool_t * pool, void * this)
Create nested inner enumerator over pool attributes
Definition at line 202 of file vici_attribute.c.
References array_create_enumerator(), attr_filter(), pool_t::attrs, and enumerator_create_filter().
 {
     return enumerator_create_filter(array_create_enumerator(pool->attrs),
                                     (void*)attr_filter, NULL, NULL);
 }
CALLBACK (nested_cleanup , void , nested_data_t * data)
Clean up nested enumerator data
Definition at line 220 of file vici_attribute.c.
References linked_list_t::destroy, free(), nested_data_t::list, private_vici_attribute_t::lock, nested_data_t::this, and rwlock_t::unlock.
 {
     data->this->lock->unlock(data->this->lock);
     data->list->destroy(data->list);
     free(data);
 }
CALLBACK (pool_li , bool , load_data_t * data, vici_message_t * message, char * name, chunk_t value)
Definition at line 404 of file vici_attribute.c.
References array_insert_create(), ARRAY_TAIL, pool_t::attrs, chunk_cat, chunk_clone, chunk_from_chars, chunk_from_thing, countof, create_reply(), host_t::destroy, encoding, FALSE, host_t::get_address, host_t::get_family, host, host_create_from_string(), host_create_from_subnet(), INIT, INTERNAL_IP4_ADDRESS, INTERNAL_IP4_DHCP, INTERNAL_IP4_DNS, INTERNAL_IP4_NBNS, INTERNAL_IP4_NETMASK, INTERNAL_IP4_SERVER, INTERNAL_IP4_SUBNET, INTERNAL_IP6_ADDRESS, INTERNAL_IP6_DHCP, INTERNAL_IP6_DNS, INTERNAL_IP6_NBNS, INTERNAL_IP6_NETMASK, INTERNAL_IP6_SERVER, INTERNAL_IP6_SUBNET, keys, mask, name, load_data_t::pool, request_data_t::reply, load_data_t::request, streq(), TRUE, type, UNITY_LOCAL_LAN, UNITY_SPLIT_INCLUDE, attribute_type_key_t::v4, attribute_type_key_t::v6, and vici_stringify().
 {
     struct {
         char *name;
         configuration_attribute_type_t v4;
         configuration_attribute_type_t v6;
     } keys[] = {
         {"address",         INTERNAL_IP4_ADDRESS,   INTERNAL_IP6_ADDRESS    },
         {"dns",             INTERNAL_IP4_DNS,       INTERNAL_IP6_DNS        },
         {"nbns",            INTERNAL_IP4_NBNS,      INTERNAL_IP6_NBNS       },
         {"dhcp",            INTERNAL_IP4_DHCP,      INTERNAL_IP6_DHCP       },
         {"netmask",         INTERNAL_IP4_NETMASK,   INTERNAL_IP6_NETMASK    },
         {"server",          INTERNAL_IP4_SERVER,    INTERNAL_IP6_SERVER     },
         {"subnet",          INTERNAL_IP4_SUBNET,    INTERNAL_IP6_SUBNET     },
         {"split_include",   UNITY_SPLIT_INCLUDE,    UNITY_SPLIT_INCLUDE     },
         {"split_exclude",   UNITY_LOCAL_LAN,        UNITY_LOCAL_LAN         },
     };
     char buf[256];
     int i, index = -1, mask = -1, type = 0;
     chunk_t encoding;
     attribute_t *attr;
     host_t *host = NULL;
     for (i = 0; i < countof(keys); i++)
     {
         if (streq(name, keys[i].name))
         {
             index = i;
             break;
         }
     }
     if (index == -1)
     {
         type = atoi(name);
         if (!type)
         {
             data->request->reply = create_reply("invalid attribute: %s", name);
             return FALSE;
         }
     }
     if (vici_stringify(value, buf, sizeof(buf)))
     {
         if (strchr(buf, '/'))
         {
             host = host_create_from_subnet(buf, &mask);
         }
         else
         {
             host = host_create_from_string(buf, 0);
         }
     }
     if (host)
     {
         if (index != -1)
         {
             switch (host->get_family(host))
             {
                 case AF_INET:
                     type = keys[index].v4;
                     break;
                 case AF_INET6:
                 default:
                     type = keys[index].v6;
                     break;
             }
         }
         if (mask == -1)
         {
             encoding = chunk_clone(host->get_address(host));
         }
         else
         {
             if (host->get_family(host) == AF_INET)
             {   /* IPv4 attributes contain a subnet mask */
                 u_int32_t netmask = 0;
                 if (mask)
                 {   /* shifting u_int32_t by 32 or more is undefined */
                     mask = 32 - mask;
                     netmask = htonl((0xFFFFFFFF >> mask) << mask);
                 }
                 encoding = chunk_cat("cc", host->get_address(host),
                                      chunk_from_thing(netmask));
             }
             else
             {   /* IPv6 addresses the prefix only */
                 encoding = chunk_cat("cc", host->get_address(host),
                                      chunk_from_chars(mask));
             }
         }
         host->destroy(host);
     }
     else
     {
         if (index != -1)
         {
             data->request->reply = create_reply("invalid attribute value "
                                                 "for %s", name);
             return FALSE;
         }
         /* use raw binary data for numbered attributes */
         encoding = chunk_clone(value);
     }
     INIT(attr,
         .type = type,
         .value = encoding,
     );
     array_insert_create(&data->pool->attrs, ARRAY_TAIL, attr);
     return TRUE;
 }
CALLBACK (pool_kv , bool , load_data_t * data, vici_message_t * message, char * name, chunk_t value)
Definition at line 517 of file vici_attribute.c.
References base, bits, create_pool_range(), create_reply(), host_t::destroy, FALSE, host_create_from_subnet(), mem_pool_create(), load_data_t::name, load_data_t::pool, request_data_t::reply, load_data_t::request, streq(), TRUE, vici_stringify(), and pool_t::vips.
 {
     if (streq(name, "addrs"))
     {
         char buf[128];
         mem_pool_t *pool;
         host_t *base = NULL;
         int bits;
         if (data->pool->vips)
         {
             data->request->reply = create_reply("multiple addrs defined");
             return FALSE;
         }
         if (!vici_stringify(value, buf, sizeof(buf)))
         {
             data->request->reply = create_reply("invalid addrs value");
             return FALSE;
         }
         pool = create_pool_range(data->name, buf);
         if (!pool)
         {
             base = host_create_from_subnet(buf, &bits);
             if (base)
             {
                 pool = mem_pool_create(data->name, base, bits);
                 base->destroy(base);
             }
         }
         if (!pool)
         {
             data->request->reply = create_reply("invalid addrs value: %s", buf);
             return FALSE;
         }
         data->pool->vips = pool;
         return TRUE;
     }
     data->request->reply = create_reply("invalid attribute: %s", name);
     return FALSE;
 }
CALLBACK (pool_sn , bool , request_data_t * request, vici_message_t * message, vici_parse_context_t * ctx, char * name)
Definition at line 559 of file vici_attribute.c.
References create_reply(), data, FALSE, INIT, private_vici_attribute_t::lock, merge_pool(), name, vici_message_t::parse, load_data_t::pool, pool_destroy(), request_data_t::reply, request(), request_data_t::this, rwlock_t::unlock, pool_t::vips, and rwlock_t::write_lock.
 {
     load_data_t data = {
         .request = request,
         .name = name,
     };
     bool merged;
     INIT(data.pool);
     if (!message->parse(message, ctx, NULL, pool_kv, pool_li, &data))
     {
         pool_destroy(data.pool);
         return FALSE;
     }
     if (!data.pool->vips)
     {
         request->reply = create_reply("missing addrs for pool '%s'", name);
         pool_destroy(data.pool);
         return FALSE;
     }
     request->this->lock->write_lock(request->this->lock);
     merged = merge_pool(request->this, data.pool);
     request->this->lock->unlock(request->this->lock);
     if (!merged)
     {
         request->reply = create_reply("vici pool %s has online leases, "
                                       "unable to replace", name);
         pool_destroy(data.pool);
     }
     return merged;
 }
CALLBACK (load_pool , vici_message_t * , private_vici_attribute_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 597 of file vici_attribute.c.
References create_reply(), vici_message_t::parse, request_data_t::reply, and request().
 {
     request_data_t request = {
         .this = this,
     };
     if (!message->parse(message, NULL, pool_sn, NULL, NULL, &request))
     {
         if (request.reply)
         {
             return request.reply;
         }
         return create_reply("parsing request failed");
     }
     return create_reply(NULL);
 }
CALLBACK (unload_pool , vici_message_t * , private_vici_attribute_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 616 of file vici_attribute.c.
References create_reply(), DBG1, DBG_CFG, mem_pool_t::get_name, mem_pool_t::get_online, vici_message_t::get_str, lock, pool_destroy(), spinlock_t::unlock, and pool_t::vips.
 {
     vici_message_t *reply;
     u_int online;
     pool_t *pool;
     name = message->get_str(message, NULL, "name");
     if (!name)
     {
         return create_reply("missing pool name to unload");
     }
     this->lock->write_lock(this->lock);
     pool = this->pools->remove(this->pools, name);
     if (pool)
     {
         online = pool->vips->get_online(pool->vips);
         if (online)
         {
             DBG1(DBG_CFG, "vici pool %s has %u online leases, unable to unload",
                  name, online);
             reply = create_reply("%s has online leases, unable to unload", name);
             this->pools->put(this->pools, pool->vips->get_name(pool->vips), pool);
         }
         else
         {
             DBG1(DBG_CFG, "unloaded vici pool %s", name);
             reply = create_reply(NULL);
             pool_destroy(pool);
         }
     }
     else
     {
         reply = create_reply("%s not found", name);
     }
     this->lock->unlock(this->lock);
     return reply;
 }
CALLBACK (get_pools , vici_message_t * , private_vici_attribute_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 660 of file vici_attribute.c.
References vici_builder_t::add_kv, vici_builder_t::begin_section, mem_pool_t::create_lease_enumerator, enumerator_t::destroy, vici_builder_t::end_section, enumerator_t::enumerate, FALSE, vici_builder_t::finalize, mem_pool_t::get_base, vici_message_t::get_bool, mem_pool_t::get_offline, mem_pool_t::get_online, mem_pool_t::get_size, leases(), lock, snprintf, spinlock_t::unlock, vici_builder_create(), and pool_t::vips.
 {
     vici_builder_t *builder;
     enumerator_t *enumerator, *leases;
     mem_pool_t *vips;
     pool_t *pool;
     identification_t *uid;
     host_t *lease;
     bool list_leases, on;
     char buf[32];
     int i;
     list_leases = message->get_bool(message, FALSE, "leases");
     builder = vici_builder_create();
     this->lock->read_lock(this->lock);
     enumerator = this->pools->create_enumerator(this->pools);
     while (enumerator->enumerate(enumerator, &name, &pool))
     {
         vips = pool->vips;
         builder->begin_section(builder, name);
         builder->add_kv(builder, "base", "%H", vips->get_base(vips));
         builder->add_kv(builder, "size", "%u", vips->get_size(vips));
         builder->add_kv(builder, "online", "%u", vips->get_online(vips));
         builder->add_kv(builder, "offline", "%u", vips->get_offline(vips));
         if (list_leases)
         {
             i = 0;
             builder->begin_section(builder, "leases");
             leases = vips->create_lease_enumerator(vips);
             while (leases && leases->enumerate(leases, &uid, &lease, &on))
             {
                 snprintf(buf, sizeof(buf), "%d", i++);
                 builder->begin_section(builder, buf);
                 builder->add_kv(builder, "address", "%H", lease);
                 builder->add_kv(builder, "identity", "%Y", uid);
                 builder->add_kv(builder, "status", on ? "online" : "offline");
                 builder->end_section(builder);
             }
             leases->destroy(leases);
             builder->end_section(builder);
         }
         builder->end_section(builder);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return builder->finalize(builder);
 }
static mem_pool_t* create_pool_range (char * name, char * buf) static
Parse a range definition of an address pool
Definition at line 372 of file vici_attribute.c.
References host_t::destroy, from, host_create_from_range(), mem_pool_create_range(), and to.
Referenced by CALLBACK().
 {
     mem_pool_t *pool;
     host_t *from, *to;
     if (!host_create_from_range(buf, &from, &to))
     {
         return NULL;
     }
     pool = mem_pool_create_range(name, from, to);
     from->destroy(from);
     to->destroy(to);
     return pool;
 }
static vici_message_t* create_reply (char * fmt, ...) static
Create a (error) reply message
Definition at line 353 of file vici_attribute.c.
References vici_builder_t::add_kv, vici_builder_t::finalize, vici_builder_t::vadd_kv, and vici_builder_create().
Referenced by CALLBACK().
 {
     vici_builder_t *builder;
     va_list args;
     builder = vici_builder_create();
     builder->add_kv(builder, "success", fmt ? "no" : "yes");
     if (fmt)
     {
         va_start(args, fmt);
         builder->vadd_kv(builder, "errmsg", fmt, args);
         va_end(args);
     }
     return builder->finalize(builder);
 }
static host_t* find_addr (private_vici_attribute_t * this, linked_list_t * pools, identification_t * id, host_t * requested, mem_pool_op_t op, host_t * peer) static
Find an existing or not yet existing lease
Definition at line 98 of file vici_attribute.c.
References mem_pool_t::acquire_address, addr, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, name, and pool_t::vips.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     host_t *addr = NULL;
     pool_t *pool;
     char *name;
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = this->pools->get(this->pools, name);
         if (pool)
         {
             addr = pool->vips->acquire_address(pool->vips, id, requested,
                                                op, peer);
             if (addr)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     return addr;
 }
static bool have_vips_from_pool (mem_pool_t * pool, linked_list_t * vips) static
Check if any of vips is from pool
Definition at line 231 of file vici_attribute.c.
References chunk_clone, chunk_compare(), linked_list_t::create_enumerator, end, FALSE, found, free(), host_t::get_address, mem_pool_t::get_base, mem_pool_t::get_size, host, htoun32(), chunk_t::len, chunk_t::ptr, size, start, TRUE, and untoh32().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     host_t *host;
     chunk_t start, end, current;
     u_int32_t size;
     bool found = FALSE;
     host = pool->get_base(pool);
     start = host->get_address(host);
     if (start.len >= sizeof(size))
     {
         end = chunk_clone(start);
         /* mem_pool is currenty limited to 2^31 addresses, so 32-bit
          * calculations should be sufficient. */
         size = untoh32(start.ptr + start.len - sizeof(size));
         htoun32(end.ptr + end.len - sizeof(size), size + pool->get_size(pool));
         enumerator = vips->create_enumerator(vips);
         while (enumerator->enumerate(enumerator, &host))
         {
             current = host->get_address(host);
             if (chunk_compare(current, start) >= 0 &&
                 chunk_compare(current, end) < 0)
             {
                 found = TRUE;
                 break;
             }
         }
         enumerator->destroy(enumerator);
         free(end.ptr);
     }
     return found;
 }
static void manage_command (private_vici_attribute_t * this, char * name, vici_command_cb_t cb, bool reg) static
Definition at line 716 of file vici_attribute.c.
Referenced by manage_commands().
 {
     this->dispatcher->manage_command(this->dispatcher, name,
                                      reg ? cb : NULL, this);
 }
static void manage_commands (private_vici_attribute_t * this, bool reg) static
(Un-)register dispatcher functions
Definition at line 726 of file vici_attribute.c.
References load_pool(), manage_command(), and unload_pool().
Referenced by METHOD(), and vici_attribute_create().
 {
     manage_command(this, "load-pool", load_pool, reg);
     manage_command(this, "unload-pool", unload_pool, reg);
     manage_command(this, "get-pools", get_pools, reg);
 }
static bool merge_pool (private_vici_attribute_t * this, pool_t * new) static
Merge a pool configuration with existing ones
Definition at line 303 of file vici_attribute.c.
References base, DBG1, DBG_CFG, FALSE, mem_pool_t::get_base, mem_pool_t::get_name, mem_pool_t::get_online, mem_pool_t::get_size, host_t::ip_equals, name, pool_destroy(), size, TRUE, and pool_t::vips.
Referenced by CALLBACK().
 {
     mem_pool_t *tmp;
     host_t *base;
     pool_t *old;
     const char *name;
     u_int size;
     name = new->vips->get_name(new->vips);
     base = new->vips->get_base(new->vips);
     size = new->vips->get_size(new->vips);
     old = this->pools->remove(this->pools, name);
     if (!old)
     {
         this->pools->put(this->pools, name, new);
         DBG1(DBG_CFG, "added vici pool %s: %H, %u entries", name, base, size);
         return TRUE;
     }
     if (base->ip_equals(base, old->vips->get_base(old->vips)) &&
         size == old->vips->get_size(old->vips))
     {
         /* no changes in pool, so keep existing, but use new attributes */
         DBG1(DBG_CFG, "updated vici pool %s: %H, %u entries", name, base, size);
         tmp = new->vips;
         new->vips = old->vips;
         old->vips = tmp;
         this->pools->put(this->pools, new->vips->get_name(new->vips), new);
         pool_destroy(old);
         return TRUE;
     }
     if (old->vips->get_online(old->vips) == 0)
     {
         /* can replace old pool, no online leases */
         DBG1(DBG_CFG, "replaced vici pool %s: %H, %u entries", name, base, size);
         this->pools->put(this->pools, name, new);
         pool_destroy(old);
         return TRUE;
     }
     /* have online leases, unable to replace, TODO: migrate leases? */
     DBG1(DBG_CFG, "vici pool %s has %u online leases, unable to replace",
          name, old->vips->get_online(old->vips));
     this->pools->put(this->pools, old->vips->get_name(old->vips), old);
     return FALSE;
 }
METHOD (attribute_provider_t , acquire_address , host_t * , private_vici_attribute_t * this, linked_list_t * pools, ike_sa_t * ike_sa, host_t * requested)
Definition at line 126 of file vici_attribute.c.
References addr, find_addr(), ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, id, lock, MEM_POOL_EXISTING, MEM_POOL_NEW, MEM_POOL_REASSIGN, and spinlock_t::unlock.
 {
     identification_t *id;
     host_t *addr, *peer;
     id = ike_sa->get_other_eap_id(ike_sa);
     peer = ike_sa->get_other_host(ike_sa);
     this->lock->read_lock(this->lock);
     addr = find_addr(this, pools, id, requested, MEM_POOL_EXISTING, peer);
     if (!addr)
     {
         addr = find_addr(this, pools, id, requested, MEM_POOL_NEW, peer);
         if (!addr)
         {
             addr = find_addr(this, pools, id, requested, MEM_POOL_REASSIGN, peer);
         }
     }
     this->lock->unlock(this->lock);
     return addr;
 }
METHOD (attribute_provider_t , release_address , bool , private_vici_attribute_t * this, linked_list_t * pools, host_t * address, ike_sa_t * ike_sa)
Definition at line 153 of file vici_attribute.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, ike_sa_t::get_other_eap_id, id, lock, name, mem_pool_t::release_address, spinlock_t::unlock, and pool_t::vips.
 {
     enumerator_t *enumerator;
     identification_t *id;
     bool found = FALSE;
     pool_t *pool;
     char *name;
     id = ike_sa->get_other_eap_id(ike_sa);
     this->lock->read_lock(this->lock);
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = this->pools->get(this->pools, name);
         if (pool)
         {
             found = pool->vips->release_address(pool->vips, address, id);
             if (found)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (attribute_provider_t , create_attribute_enumerator , enumerator_t * , private_vici_attribute_t * this, linked_list_t * pools, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 269 of file vici_attribute.c.
References linked_list_t::create_enumerator, data, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_nested(), have_vips_from_pool(), INIT, linked_list_t::insert_last, linked_list_create(), list, nested_data_t::list, lock, name, and pool_t::vips.
 {
     enumerator_t *enumerator;
     nested_data_t *data;
     pool_t *pool;
     char *name;
     INIT(data,
         .this = this,
         .list = linked_list_create(),
     );
     this->lock->read_lock(this->lock);
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = this->pools->get(this->pools, name);
         if (pool && have_vips_from_pool(pool->vips, vips))
         {
             data->list->insert_last(data->list, pool);
         }
     }
     enumerator->destroy(enumerator);
     return enumerator_create_nested(data->list->create_enumerator(data->list),
                                     create_nested, data, nested_cleanup);
 }
METHOD (vici_attribute_t , destroy , void , private_vici_attribute_t * this)
Definition at line 733 of file vici_attribute.c.
References spinlock_t::destroy, enumerator_t::destroy, enumerator_t::enumerate, FALSE, free(), lock, manage_commands(), and pool_destroy().
 {
     enumerator_t *enumerator;
     pool_t *pool;
     manage_commands(this, FALSE);
     enumerator = this->pools->create_enumerator(this->pools);
     while (enumerator->enumerate(enumerator, NULL, &pool))
     {
         pool_destroy(pool);
     }
     enumerator->destroy(enumerator);
     this->pools->destroy(this->pools);
     this->lock->destroy(this->lock);
     free(this);
 }
static void pool_destroy (pool_t * pool) static
Clean up a pool instance
Definition at line 88 of file vici_attribute.c.
References array_destroy_function(), attribute_destroy(), pool_t::attrs, DESTROY_IF, free(), and pool_t::vips.
Referenced by CALLBACK(), merge_pool(), and METHOD().
 {
     DESTROY_IF(pool->vips);
     array_destroy_function(pool->attrs, (void*)attribute_destroy, NULL);
     free(pool);
 }