strongSwan: lexer.c File Reference
lexer.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <utils/parser_helper.h>
#include <parser/conf_parser.h>
#include "parser.h"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Macros
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define YY_TYPEDEF_YY_SCANNER_T
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE conf_parser_restart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_TYPEDEF_YY_SIZE_T
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER conf_parser__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer conf_parser__create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define conf_parser_wrap(n) 1
#define YY_SKIP_YYWRAP
#define FLEX_DEBUG
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_NO_INPUT 1
#define INITIAL 0
#define inc 1
#define str 2
#define YY_EXTRA_TYPE parser_helper_t*
#define yylval yyg->yylval_r
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_DECL_IS_OURS 1
#define YY_DECL
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void conf_parser_restart (FILE *input_file, yyscan_t yyscanner)
void conf_parser__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
YY_BUFFER_STATE conf_parser__create_buffer (FILE *file, int size, yyscan_t yyscanner)
void conf_parser__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void conf_parser__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void conf_parser_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
void conf_parser_pop_buffer_state (yyscan_t yyscanner)
static void conf_parser_ensure_buffer_stack (yyscan_t yyscanner)
static void conf_parser__load_buffer_state (yyscan_t yyscanner)
static void conf_parser__init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
YY_BUFFER_STATE conf_parser__scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
YY_BUFFER_STATE conf_parser__scan_string (yyconst char *yy_str, yyscan_t yyscanner)
YY_BUFFER_STATE conf_parser__scan_bytes (yyconst char *bytes, int len, yyscan_t yyscanner)
void * conf_parser_alloc (yy_size_t, yyscan_t yyscanner)
void * conf_parser_realloc (void *, yy_size_t, yyscan_t yyscanner)
void conf_parser_free (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner)
bool conf_parser_open_next_file (parser_helper_t *ctx)
static void include_files (parser_helper_t *ctx)
static int yy_init_globals (yyscan_t yyscanner)
int conf_parser_lex_init (yyscan_t *scanner)
int conf_parser_lex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t *scanner)
int conf_parser_lex_destroy (yyscan_t yyscanner)
int conf_parser_get_debug (yyscan_t yyscanner)
void conf_parser_set_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE conf_parser_get_extra (yyscan_t yyscanner)
void conf_parser_set_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
FILE * conf_parser_get_in (yyscan_t yyscanner)
void conf_parser_set_in (FILE *in_str, yyscan_t yyscanner)
FILE * conf_parser_get_out (yyscan_t yyscanner)
void conf_parser_set_out (FILE *out_str, yyscan_t yyscanner)
int conf_parser_get_leng (yyscan_t yyscanner)
char * conf_parser_get_text (yyscan_t yyscanner)
int conf_parser_get_lineno (yyscan_t yyscanner)
void conf_parser_set_lineno (int line_number, yyscan_t yyscanner)
YYSTYPE * conf_parser_get_lval (yyscan_t yyscanner)
void conf_parser_set_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
static void yyunput (int c, char *buf_ptr, yyscan_t yyscanner)
static void yy_push_state (int new_state, yyscan_t yyscanner)
static void yy_pop_state (yyscan_t yyscanner)
static int yy_top_state (yyscan_t yyscanner)
int conf_parser_lex (YYSTYPE *yylval_param, yyscan_t yyscanner)
if (!yyg->yy_init)
while (1)
static void yyunput (int c, register char *yy_bp, yyscan_t yyscanner)
int isatty (int)
static void yy_fatal_error (yyconst char *msg, yyscan_t yyscanner)
int conf_parser_get_column (yyscan_t yyscanner)
void conf_parser_set_column (int column_no, yyscan_t yyscanner)
Variables
static yyconst flex_int16_t yy_accept [80]
static yyconst flex_int32_t yy_ec [256]
static yyconst flex_int32_t yy_meta [28]
static yyconst flex_int16_t yy_base [91]
static yyconst flex_int16_t yy_def [91]
static yyconst flex_int16_t yy_nxt [212]
static yyconst flex_int16_t yy_chk [212]
static yyconst flex_int32_t yy_rule_can_match_eol [27]
static yyconst flex_int16_t yy_rule_linenum [26]
YY_DECL
register char * yy_cp
register char * yy_bp
register int yy_act
struct yyguts_t * yyg = (struct yyguts_t*)yyscanner
yylval = yylval_param
Macro Definition Documentation
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 185 of file lexer.c.
Referenced by yy_pop_state(), and yy_push_state().
#define conf_parser_wrap (n) 1
Definition at line 426 of file lexer.c.
Referenced by while().
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
Definition at line 844 of file lexer.c.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 232 of file lexer.c.
Referenced by while(), and yy_get_next_buffer().
#define EOB_ACT_END_OF_FILE 1
Definition at line 233 of file lexer.c.
Referenced by while(), and yy_get_next_buffer().
#define EOB_ACT_LAST_MATCH 2
Definition at line 234 of file lexer.c.
Referenced by while(), and yy_get_next_buffer().
#define FLEX_BETA
Definition at line 22 of file lexer.c.
#define FLEX_DEBUG
Definition at line 429 of file lexer.c.
#define FLEX_SCANNER
Definition at line 17 of file lexer.c.
#define FLEXINT_H
Definition at line 54 of file lexer.c.
#define inc 1
Definition at line 663 of file lexer.c.
Referenced by while().
#define INITIAL 0
Definition at line 662 of file lexer.c.
Referenced by while().
#define INT16_MAX (32767)
Definition at line 96 of file lexer.c.
#define INT16_MIN (-32767-1)
Definition at line 87 of file lexer.c.
#define INT32_MAX (2147483647)
Definition at line 99 of file lexer.c.
#define INT32_MIN (-2147483647-1)
Definition at line 90 of file lexer.c.
#define INT8_MAX (127)
Definition at line 93 of file lexer.c.
#define INT8_MIN (-128)
Definition at line 84 of file lexer.c.
#define REJECT reject_used_but_not_detected
Definition at line 617 of file lexer.c.
#define str 2
Definition at line 664 of file lexer.c.
Referenced by while().
#define UINT16_MAX (65535U)
Definition at line 105 of file lexer.c.
#define UINT32_MAX (4294967295U)
Definition at line 108 of file lexer.c.
#define UINT8_MAX (255U)
Definition at line 102 of file lexer.c.
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 265 of file lexer.c.
Referenced by while().
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 421 of file lexer.c.
Referenced by while(), and yy_get_previous_state().
#define YY_BREAK break;
Definition at line 950 of file lexer.c.
Referenced by while().
#define YY_BUF_SIZE 16384
Definition at line 211 of file lexer.c.
Referenced by conf_parser_open_next_file(), conf_parser_restart(), and if().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 337 of file lexer.c.
Referenced by yy_get_next_buffer().
#define YY_BUFFER_NEW 0
Definition at line 325 of file lexer.c.
Referenced by conf_parser__flush_buffer(), conf_parser__scan_buffer(), and while().
#define YY_BUFFER_NORMAL 1
Definition at line 326 of file lexer.c.
Referenced by while().
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 357 of file lexer.c.
Referenced by conf_parser__delete_buffer(), conf_parser__flush_buffer(), conf_parser__init_buffer(), conf_parser__switch_to_buffer(), conf_parser_get_column(), conf_parser_get_lineno(), conf_parser_lex_destroy(), conf_parser_pop_buffer_state(), conf_parser_push_buffer_state(), conf_parser_restart(), conf_parser_set_column(), conf_parser_set_lineno(), if(), while(), and yy_get_next_buffer().
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 364 of file lexer.c.
Referenced by conf_parser__delete_buffer(), conf_parser__load_buffer_state(), conf_parser__switch_to_buffer(), conf_parser_lex_destroy(), conf_parser_pop_buffer_state(), conf_parser_push_buffer_state(), conf_parser_restart(), if(), while(), yy_get_next_buffer(), and yyunput().
#define YY_DECL
Value:
int conf_parser_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
Definition at line 934 of file lexer.c.
#define YY_DECL_IS_OURS 1
Definition at line 928 of file lexer.c.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
    yyleng = (size_t) (yy_cp - yy_bp); \
    yyg->yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
    yyg->yy_c_buf_p = yy_cp;
Definition at line 449 of file lexer.c.
Referenced by while().
#define YY_END_OF_BUFFER 27
Definition at line 460 of file lexer.c.
Referenced by while().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 200 of file lexer.c.
Referenced by conf_parser__flush_buffer(), conf_parser__scan_buffer(), conf_parser__scan_bytes(), and yy_get_next_buffer().
#define YY_EXIT_FAILURE 2
Definition at line 2294 of file lexer.c.
Referenced by yy_fatal_error().
#define YY_EXTRA_TYPE parser_helper_t*
Definition at line 678 of file lexer.c.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 905 of file lexer.c.
Referenced by conf_parser__create_buffer(), conf_parser__scan_buffer(), conf_parser__scan_bytes(), conf_parser_ensure_buffer_stack(), while(), yy_get_next_buffer(), yy_pop_state(), yy_push_state(), and yyunput().
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 174 of file lexer.c.
Referenced by conf_parser_get_debug(), conf_parser_set_debug(), and while().
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 18 of file lexer.c.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 19 of file lexer.c.
#define YY_FLEX_SUBMINOR_VERSION 35
Definition at line 20 of file lexer.c.
#define YY_FLUSH_BUFFER conf_parser__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 387 of file lexer.c.
#define YY_INPUT (buf, result, max_size)
Definition at line 854 of file lexer.c.
Referenced by yy_get_next_buffer().
#define YY_INT_ALIGNED short int
Definition at line 5 of file lexer.c.
#define YY_LESS_LINENO (n)
Value:
do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
Definition at line 243 of file lexer.c.
#define YY_MORE_ADJ 0
Definition at line 619 of file lexer.c.
Referenced by while(), yy_get_next_buffer(), and yy_get_previous_state().
#define yy_new_buffer conf_parser__create_buffer
Definition at line 399 of file lexer.c.
#define YY_NEW_FILE conf_parser_restart(yyin ,yyscanner)
Definition at line 198 of file lexer.c.
Referenced by while().
#define YY_NO_INPUT 1
Definition at line 649 of file lexer.c.
#define YY_NULL 0
Definition at line 144 of file lexer.c.
#define YY_NUM_RULES 26
Definition at line 459 of file lexer.c.
#define YY_READ_BUF_SIZE 8192
Definition at line 834 of file lexer.c.
Referenced by yy_get_next_buffer().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 620 of file lexer.c.
Referenced by while().
#define YY_RULE_SETUP
Value:
if (yyleng > 0) \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
                (yytext[yyleng - 1] == '\n'); \
    YY_USER_ACTION
Definition at line 954 of file lexer.c.
Referenced by while().
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 154 of file lexer.c.
Referenced by while(), and yy_get_previous_state().
#define yy_set_bol (at_bol)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){\
        conf_parser_ensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            conf_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
    }
Definition at line 411 of file lexer.c.
Referenced by while().
#define yy_set_interactive (is_interactive)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){ \
        conf_parser_ensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            conf_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
    }
Definition at line 401 of file lexer.c.
#define YY_SKIP_YYWRAP
Definition at line 427 of file lexer.c.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 191 of file lexer.c.
Referenced by while(), and yy_push_state().
#define YY_START_STACK_INCR 25
Definition at line 899 of file lexer.c.
Referenced by yy_push_state().
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 217 of file lexer.c.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 195 of file lexer.c.
Referenced by while().
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 273 of file lexer.c.
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 220 of file lexer.c.
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 161 of file lexer.c.
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 268 of file lexer.c.
#define YY_USER_ACTION
Definition at line 945 of file lexer.c.
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 173 of file lexer.c.
Referenced by conf_parser_get_column(), conf_parser_set_column(), and while().
#define yyconst
Definition at line 138 of file lexer.c.
#define yyextra yyg->yyextra_r
Definition at line 169 of file lexer.c.
Referenced by conf_parser_get_extra(), conf_parser_set_extra(), and while().
#define yyin yyg->yyin_r
Definition at line 167 of file lexer.c.
Referenced by conf_parser__load_buffer_state(), conf_parser_get_in(), conf_parser_restart(), conf_parser_set_in(), if(), while(), yy_get_next_buffer(), and yy_init_globals().
#define yyleng yyg->yyleng_r
Definition at line 170 of file lexer.c.
Referenced by conf_parser_get_leng(), and while().
#define yyless (n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        *yy_cp = yyg->yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )
Definition at line 2310 of file lexer.c.
#define yyless (n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        yytext[yyleng] = yyg->yy_hold_char; \
        yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
        yyg->yy_hold_char = *yyg->yy_c_buf_p; \
        *yyg->yy_c_buf_p = '\0'; \
        yyleng = yyless_macro_arg; \
        } \
    while ( 0 )
Definition at line 2310 of file lexer.c.
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 172 of file lexer.c.
Referenced by conf_parser_get_lineno(), conf_parser_set_lineno(), while(), and yyunput().
#define yylval yyg->yylval_r
Definition at line 729 of file lexer.c.
Referenced by conf_parser_get_lval(), conf_parser_set_lval(), and while().
#define yymore () yymore_used_but_not_detected
Definition at line 618 of file lexer.c.
#define yyout yyg->yyout_r
Definition at line 168 of file lexer.c.
Referenced by conf_parser_get_out(), conf_parser_set_out(), if(), and yy_init_globals().
#define YYSTATE YY_START
Definition at line 192 of file lexer.c.
#define YYTABLES_NAME "yytables"
Definition at line 2681 of file lexer.c.
#define yyterminate () return YY_NULL
Definition at line 894 of file lexer.c.
Referenced by while().
#define yytext yyg->yytext_r
Definition at line 171 of file lexer.c.
Referenced by conf_parser_get_text(), and while().
#define yytext_ptr yytext_r
Definition at line 435 of file lexer.c.
Typedef Documentation
typedef short int flex_int16_t
Definition at line 76 of file lexer.c.
typedef int flex_int32_t
Definition at line 77 of file lexer.c.
typedef signed char flex_int8_t
Definition at line 75 of file lexer.c.
typedef unsigned short int flex_uint16_t
Definition at line 79 of file lexer.c.
typedef unsigned int flex_uint32_t
Definition at line 80 of file lexer.c.
typedef unsigned char flex_uint8_t
Definition at line 78 of file lexer.c.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 221 of file lexer.c.
typedef unsigned char YY_CHAR
Definition at line 431 of file lexer.c.
typedef size_t yy_size_t
Definition at line 269 of file lexer.c.
typedef int yy_state_type
Definition at line 433 of file lexer.c.
typedef void* yyscan_t
Definition at line 162 of file lexer.c.
Function Documentation
YY_BUFFER_STATE conf_parser__create_buffer (FILE * file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
Parameters
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
yyscanner The scanner object.
Returns
the allocated buffer state.
Definition at line 1898 of file lexer.c.
References b, conf_parser__init_buffer(), conf_parser_alloc(), size, yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by conf_parser_open_next_file(), conf_parser_restart(), and if().
 {
     YY_BUFFER_STATE b;
     b = (YY_BUFFER_STATE) conf_parser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
     if ( ! b )
         YY_FATAL_ERROR( "out of dynamic memory in conf_parser__create_buffer()" );
     b->yy_buf_size = size;
     /* yy_ch_buf has to be 2 characters longer than the size given because
      * we need to put in 2 end-of-buffer characters.
      */
     b->yy_ch_buf = (char *) conf_parser_alloc(b->yy_buf_size + 2 ,yyscanner );
     if ( ! b->yy_ch_buf )
         YY_FATAL_ERROR( "out of dynamic memory in conf_parser__create_buffer()" );
     b->yy_is_our_buffer = 1;
     conf_parser__init_buffer(b,file ,yyscanner);
     return b;
 }
void conf_parser__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
Parameters
b a buffer created with conf_parser__create_buffer()
yyscanner The scanner object.
Definition at line 1930 of file lexer.c.
References conf_parser_free(), yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_buffer_state::yy_is_our_buffer.
Referenced by conf_parser_lex_destroy(), and conf_parser_pop_buffer_state().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( ! b )
         return;
     if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
         YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;
     if ( b->yy_is_our_buffer )
         conf_parser_free((void *) b->yy_ch_buf ,yyscanner );
     conf_parser_free((void *) b ,yyscanner );
 }
void conf_parser__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters. On the next scan, YY_INPUT will be called.
Parameters
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 2003 of file lexer.c.
References conf_parser__load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by conf_parser__init_buffer().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( ! b )
         return;
     b->yy_n_chars = 0;
     /* We always need two end-of-buffer characters.  The first causes
      * a transition to the end-of-buffer state.  The second causes
      * a jam in that state.
      */
     b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
     b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
     b->yy_buf_pos = &b->yy_ch_buf[0];
     b->yy_at_bol = 1;
     b->yy_buffer_status = YY_BUFFER_NEW;
     if ( b == YY_CURRENT_BUFFER )
         conf_parser__load_buffer_state(yyscanner );
 }
static void conf_parser__init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) static
Definition at line 1965 of file lexer.c.
References conf_parser__flush_buffer(), isatty(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by conf_parser__create_buffer(), and conf_parser_restart().
 {
     int oerrno = errno;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     conf_parser__flush_buffer(b ,yyscanner);
     b->yy_input_file = file;
     b->yy_fill_buffer = 1;
     /* If b is the current buffer, then conf_parser__init_buffer was _probably_
      * called from conf_parser_restart() or through yy_get_next_buffer.
      * In that case, we don't want to reset the lineno or column.
      */
     if (b != YY_CURRENT_BUFFER){
         b->yy_bs_lineno = 1;
         b->yy_bs_column = 0;
     }
 /* %if-c-only */
         b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
 /* %endif */
 /* %if-c++-only */
 /* %endif */
     errno = oerrno;
 }
static void conf_parser__load_buffer_state (yyscan_t yyscanner) static
Definition at line 1879 of file lexer.c.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yyin.
Referenced by conf_parser__flush_buffer(), conf_parser__switch_to_buffer(), conf_parser_pop_buffer_state(), conf_parser_push_buffer_state(), conf_parser_restart(), and if().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
     yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
     yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
     yyg->yy_hold_char = *yyg->yy_c_buf_p;
 }
YY_BUFFER_STATE conf_parser__scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Definition at line 2156 of file lexer.c.
References b, base, conf_parser__switch_to_buffer(), conf_parser_alloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, and yy_buffer_state::yy_n_chars.
Referenced by conf_parser__scan_bytes().
 {
     YY_BUFFER_STATE b;
     if ( size < 2 ||
          base[size-2] != YY_END_OF_BUFFER_CHAR ||
          base[size-1] != YY_END_OF_BUFFER_CHAR )
         /* They forgot to leave room for the EOB's. */
         return 0;
     b = (YY_BUFFER_STATE) conf_parser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
     if ( ! b )
         YY_FATAL_ERROR( "out of dynamic memory in conf_parser__scan_buffer()" );
     b->yy_buf_size = size - 2;  /* "- 2" to take care of EOB's */
     b->yy_buf_pos = b->yy_ch_buf = base;
     b->yy_is_our_buffer = 0;
     b->yy_input_file = 0;
     b->yy_n_chars = b->yy_buf_size;
     b->yy_is_interactive = 0;
     b->yy_at_bol = 1;
     b->yy_fill_buffer = 0;
     b->yy_buffer_status = YY_BUFFER_NEW;
     conf_parser__switch_to_buffer(b ,yyscanner );
     return b;
 }
YY_BUFFER_STATE conf_parser__scan_bytes (yyconst char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes. The next call to conf_parser_lex() will scan from a copy of bytes.
Parameters
yybytes the byte buffer to scan
_yybytes_len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Definition at line 2210 of file lexer.c.
References b, conf_parser__scan_buffer(), conf_parser_alloc(), n, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by conf_parser__scan_string().
 {
     YY_BUFFER_STATE b;
     char *buf;
     yy_size_t n;
     int i;
     /* Get memory for full buffer, including space for trailing EOB's. */
     n = _yybytes_len + 2;
     buf = (char *) conf_parser_alloc(n ,yyscanner );
     if ( ! buf )
         YY_FATAL_ERROR( "out of dynamic memory in conf_parser__scan_bytes()" );
     for ( i = 0; i < _yybytes_len; ++i )
         buf[i] = yybytes[i];
     buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;
     b = conf_parser__scan_buffer(buf,n ,yyscanner);
     if ( ! b )
         YY_FATAL_ERROR( "bad buffer in conf_parser__scan_bytes()" );
     /* It's okay to grow etc. this buffer, and we should throw it
      * away when we're done.
      */
     b->yy_is_our_buffer = 1;
     return b;
 }
YY_BUFFER_STATE conf_parser__scan_string (yyconst char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string. The next call to conf_parser_lex() will scan from a copy of str.
Parameters
yystr a NUL-terminated string to scan
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Note
If you want to scan bytes that may contain NUL values, then use conf_parser__scan_bytes() instead.
Definition at line 2195 of file lexer.c.
References conf_parser__scan_bytes().
 {
     return conf_parser__scan_bytes(yystr,strlen(yystr) ,yyscanner);
 }
void conf_parser__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
Parameters
new_buffer The new input buffer.
yyscanner The scanner object.
Definition at line 1843 of file lexer.c.
References conf_parser__load_buffer_state(), conf_parser_ensure_buffer_stack(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
Referenced by conf_parser__scan_buffer().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     /* TODO. We should be able to replace this entire function body
      * with
      *      conf_parser_pop_buffer_state();
      *      conf_parser_push_buffer_state(new_buffer);
      */
     conf_parser_ensure_buffer_stack (yyscanner);
     if ( YY_CURRENT_BUFFER == new_buffer )
         return;
     if ( YY_CURRENT_BUFFER )
         {
         /* Flush out information for old buffer. */
         *yyg->yy_c_buf_p = yyg->yy_hold_char;
         YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
         }
     YY_CURRENT_BUFFER_LVALUE = new_buffer;
     conf_parser__load_buffer_state(yyscanner );
     /* We don't actually know whether we did this switch during
      * EOF (conf_parser_wrap()) processing, but the only time this flag
      * is looked at is after conf_parser_wrap() is called, so it's safe
      * to go ahead and always set it.
      */
     yyg->yy_did_buffer_switch_on_eof = 1;
 }
void * conf_parser_alloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 2657 of file lexer.c.
References malloc().
Referenced by conf_parser__create_buffer(), conf_parser__scan_buffer(), conf_parser__scan_bytes(), conf_parser_ensure_buffer_stack(), conf_parser_lex_init(), conf_parser_lex_init_extra(), and yy_push_state().
 {
     return (void *) malloc( size );
 }
static void conf_parser_ensure_buffer_stack (yyscan_t yyscanner) static
Definition at line 2101 of file lexer.c.
References conf_parser_alloc(), conf_parser_realloc(), memset, yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, and YY_FATAL_ERROR.
Referenced by conf_parser__switch_to_buffer(), conf_parser_push_buffer_state(), conf_parser_restart(), and if().
 {
     int num_to_alloc;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if (!yyg->yy_buffer_stack) {
         /* First allocation is just for 2 elements, since we don't know if this
          * scanner will even need a stack. We use 2 instead of 1 to avoid an
          * immediate realloc on the next call.
          */
         num_to_alloc = 1;
         yyg->yy_buffer_stack = (struct yy_buffer_state**)conf_parser_alloc
                                 (num_to_alloc * sizeof(struct yy_buffer_state*)
                                 , yyscanner);
         if ( ! yyg->yy_buffer_stack )
             YY_FATAL_ERROR( "out of dynamic memory in conf_parser_ensure_buffer_stack()" );
         memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
         yyg->yy_buffer_stack_max = num_to_alloc;
         yyg->yy_buffer_stack_top = 0;
         return;
     }
     if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){
         /* Increase the buffer to prepare for a possible push. */
         int grow_size = 8 /* arbitrary grow size */;
         num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
         yyg->yy_buffer_stack = (struct yy_buffer_state**)conf_parser_realloc
                                 (yyg->yy_buffer_stack,
                                 num_to_alloc * sizeof(struct yy_buffer_state*)
                                 , yyscanner);
         if ( ! yyg->yy_buffer_stack )
             YY_FATAL_ERROR( "out of dynamic memory in conf_parser_ensure_buffer_stack()" );
         /* zero only the new slots.*/
         memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
         yyg->yy_buffer_stack_max = num_to_alloc;
     }
 }
void conf_parser_free (void * ptr, yyscan_t yyscanner)
Definition at line 2674 of file lexer.c.
References free().
Referenced by conf_parser__delete_buffer(), and conf_parser_lex_destroy().
 {
     free( (char *) ptr );   /* see conf_parser_realloc() for (char *) cast */
 }
int conf_parser_get_column (yyscan_t yyscanner)
Get the current column number.
Parameters
yyscanner The scanner object.
Definition at line 2356 of file lexer.c.
References YY_CURRENT_BUFFER, and yycolumn.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         if (! YY_CURRENT_BUFFER)
             return 0;
     return yycolumn;
 }
int conf_parser_get_debug (yyscan_t yyscanner)
Definition at line 2465 of file lexer.c.
References yy_flex_debug.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yy_flex_debug;
 }
YY_EXTRA_TYPE conf_parser_get_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters
yyscanner The scanner object.
Definition at line 2332 of file lexer.c.
References yyextra.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyextra;
 }
FILE * conf_parser_get_in (yyscan_t yyscanner)
Get the input stream.
Parameters
yyscanner The scanner object.
Definition at line 2369 of file lexer.c.
References yyin.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyin;
 }
int conf_parser_get_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters
yyscanner The scanner object.
Definition at line 2387 of file lexer.c.
References yyleng.
Referenced by conf_parser_error().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyleng;
 }
int conf_parser_get_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters
yyscanner The scanner object.
Definition at line 2343 of file lexer.c.
References YY_CURRENT_BUFFER, and yylineno.
Referenced by conf_parser_parse_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         if (! YY_CURRENT_BUFFER)
             return 0;
     return yylineno;
 }
YYSTYPE * conf_parser_get_lval (yyscan_t yyscanner)
Definition at line 2484 of file lexer.c.
References yylval.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yylval;
 }
FILE * conf_parser_get_out (yyscan_t yyscanner)
Get the output stream.
Parameters
yyscanner The scanner object.
Definition at line 2378 of file lexer.c.
References yyout.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyout;
 }
char * conf_parser_get_text (yyscan_t yyscanner)
Get the current token.
Parameters
yyscanner The scanner object.
Definition at line 2397 of file lexer.c.
References yytext.
Referenced by conf_parser_error().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yytext;
 }
int conf_parser_lex (YYSTYPE * yylval_param, yyscan_t yyscanner)
int conf_parser_lex_destroy (yyscan_t yyscanner)
Definition at line 2601 of file lexer.c.
References conf_parser__delete_buffer(), conf_parser_free(), conf_parser_pop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
Referenced by conf_parser_parse_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     /* Pop the buffer stack, destroying each element. */
     while(YY_CURRENT_BUFFER){
         conf_parser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
         YY_CURRENT_BUFFER_LVALUE = NULL;
         conf_parser_pop_buffer_state(yyscanner);
     }
     /* Destroy the stack itself. */
     conf_parser_free(yyg->yy_buffer_stack ,yyscanner);
     yyg->yy_buffer_stack = NULL;
     /* Destroy the start condition stack. */
         conf_parser_free(yyg->yy_start_stack ,yyscanner );
         yyg->yy_start_stack = NULL;
     /* Reset the globals. This is important in a non-reentrant scanner so the next time
      * conf_parser_lex() is called, initialization will occur. */
     yy_init_globals( yyscanner);
 /* %if-reentrant */
     /* Destroy the main struct (reentrant only). */
     conf_parser_free ( yyscanner , yyscanner );
     yyscanner = NULL;
 /* %endif */
     return 0;
 }
int conf_parser_lex_init (yyscan_t * scanner)
Definition at line 2505 of file lexer.c.
References conf_parser_alloc(), memset, and yy_init_globals().
 {
     if (ptr_yy_globals == NULL){
         errno = EINVAL;
         return 1;
     }
     *ptr_yy_globals = (yyscan_t) conf_parser_alloc ( sizeof( struct yyguts_t ), NULL );
     if (*ptr_yy_globals == NULL){
         errno = ENOMEM;
         return 1;
     }
     /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
     memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
     return yy_init_globals ( *ptr_yy_globals );
 }
int conf_parser_lex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t * scanner)
Definition at line 2534 of file lexer.c.
References conf_parser_alloc(), conf_parser_set_extra(), memset, and yy_init_globals().
 {
     struct yyguts_t dummy_yyguts;
     conf_parser_set_extra (yy_user_defined, &dummy_yyguts);
     if (ptr_yy_globals == NULL){
         errno = EINVAL;
         return 1;
     }
     *ptr_yy_globals = (yyscan_t) conf_parser_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
     if (*ptr_yy_globals == NULL){
         errno = ENOMEM;
         return 1;
     }
     /* By setting to 0xAA, we expose bugs in
     yy_init_globals. Leave at 0x00 for releases. */
     memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
     conf_parser_set_extra (yy_user_defined, *ptr_yy_globals);
     return yy_init_globals ( *ptr_yy_globals );
 }
bool conf_parser_open_next_file (parser_helper_t * ctx)
Open the next file, if any is queued and readable, otherwise returns FALSE.
Definition at line 2693 of file lexer.c.
References conf_parser__create_buffer(), conf_parser_push_buffer_state(), conf_parser_set_in(), FALSE, parser_helper_t::file_next, parser_helper_t::scanner, TRUE, and YY_BUF_SIZE.
Referenced by conf_parser_parse_file(), include_files(), and while().
 {
     FILE *file;
     file = ctx->file_next(ctx);
     if (!file)
     {
         return FALSE;
     }
     conf_parser_set_in(file, ctx->scanner);
     conf_parser_push_buffer_state(
             conf_parser__create_buffer(file, YY_BUF_SIZE,
                                        ctx->scanner), ctx->scanner);
     return TRUE;
 }
void conf_parser_pop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present. The next element becomes the new top.
Parameters
yyscanner The scanner object.
Definition at line 2075 of file lexer.c.
References conf_parser__delete_buffer(), conf_parser__load_buffer_state(), yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by conf_parser_lex_destroy(), and while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if (!YY_CURRENT_BUFFER)
         return;
     conf_parser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
     YY_CURRENT_BUFFER_LVALUE = NULL;
     if (yyg->yy_buffer_stack_top > 0)
         --yyg->yy_buffer_stack_top;
     if (YY_CURRENT_BUFFER) {
         conf_parser__load_buffer_state(yyscanner );
         yyg->yy_did_buffer_switch_on_eof = 1;
     }
 }
void conf_parser_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack. The new state becomes the current state. This function will allocate the stack if necessary.
Parameters
new_buffer The new state.
yyscanner The scanner object.
Definition at line 2038 of file lexer.c.
References conf_parser__load_buffer_state(), conf_parser_ensure_buffer_stack(), yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
Referenced by conf_parser_open_next_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if (new_buffer == NULL)
         return;
     conf_parser_ensure_buffer_stack(yyscanner);
     /* This block is copied from conf_parser__switch_to_buffer. */
     if ( YY_CURRENT_BUFFER )
         {
         /* Flush out information for old buffer. */
         *yyg->yy_c_buf_p = yyg->yy_hold_char;
         YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
         }
     /* Only push if top exists. Otherwise, replace top. */
     if (YY_CURRENT_BUFFER)
         yyg->yy_buffer_stack_top++;
     YY_CURRENT_BUFFER_LVALUE = new_buffer;
     /* copied from conf_parser__switch_to_buffer. */
     conf_parser__load_buffer_state(yyscanner );
     yyg->yy_did_buffer_switch_on_eof = 1;
 }
void * conf_parser_realloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 2662 of file lexer.c.
Referenced by conf_parser_ensure_buffer_stack(), yy_get_next_buffer(), and yy_push_state().
 {
     /* The cast to (char *) in the following accommodates both
      * implementations that use char* generic pointers, and those
      * that use void* generic pointers.  It works with the latter
      * because both ANSI C and C++ allow castless assignment from
      * any pointer type to void*, and deal with argument conversions
      * as though doing an assignment.
      */
     return (void *) realloc( (char *) ptr, size );
 }
void conf_parser_restart (FILE * input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
Parameters
input_file A readable stream.
yyscanner The scanner object.
Note
This function does not reset the start condition to INITIAL .
Definition at line 1821 of file lexer.c.
References conf_parser__create_buffer(), conf_parser__init_buffer(), conf_parser__load_buffer_state(), conf_parser_ensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyin.
Referenced by yy_get_next_buffer().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( ! YY_CURRENT_BUFFER ){
         conf_parser_ensure_buffer_stack (yyscanner);
         YY_CURRENT_BUFFER_LVALUE =
             conf_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
     }
     conf_parser__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
     conf_parser__load_buffer_state(yyscanner );
 }
void conf_parser_set_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters
line_number
yyscanner The scanner object.
Definition at line 2436 of file lexer.c.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         /* column is only valid if an input buffer exists. */
         if (! YY_CURRENT_BUFFER )
            yy_fatal_error( "conf_parser_set_column called with no buffer" , yyscanner);
     yycolumn = column_no;
 }
void conf_parser_set_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 2471 of file lexer.c.
References yy_flex_debug.
Referenced by conf_parser_parse_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yy_flex_debug = bdebug ;
 }
void conf_parser_set_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data. This data is never touched by the scanner.
Parameters
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 2409 of file lexer.c.
References yyextra.
Referenced by conf_parser_lex_init_extra().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyextra = user_defined ;
 }
void conf_parser_set_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream. This does not discard the current input buffer.
Parameters
in_str A readable stream.
yyscanner The scanner object.
See Also
conf_parser__switch_to_buffer
Definition at line 2453 of file lexer.c.
References yyin.
Referenced by conf_parser_open_next_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyin = in_str ;
 }
void conf_parser_set_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters
line_number
yyscanner The scanner object.
Definition at line 2421 of file lexer.c.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         /* lineno is only valid if an input buffer exists. */
         if (! YY_CURRENT_BUFFER )
            yy_fatal_error( "conf_parser_set_lineno called with no buffer" , yyscanner);
     yylineno = line_number;
 }
void conf_parser_set_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Definition at line 2490 of file lexer.c.
References yylval.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yylval = yylval_param;
 }
void conf_parser_set_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 2459 of file lexer.c.
References yyout.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyout = out_str ;
 }
if (!yyg-> yy_init)
Definition at line 979 of file lexer.c.
References conf_parser__create_buffer(), conf_parser__load_buffer_state(), conf_parser_ensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_init, yyguts_t::yy_start, yyin, and yyout.
         {
         yyg->yy_init = 1;
 #ifdef YY_USER_INIT
         YY_USER_INIT;
 #endif
         if ( ! yyg->yy_start )
             yyg->yy_start = 1;  /* first start state */
         if ( ! yyin )
 /* %if-c-only */
             yyin = stdin;
 /* %endif */
 /* %if-c++-only */
 /* %endif */
         if ( ! yyout )
 /* %if-c-only */
             yyout = stdout;
 /* %endif */
 /* %if-c++-only */
 /* %endif */
         if ( ! YY_CURRENT_BUFFER ) {
             conf_parser_ensure_buffer_stack (yyscanner);
             YY_CURRENT_BUFFER_LVALUE =
                 conf_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
         }
         conf_parser__load_buffer_state(yyscanner );
         }
static void include_files (parser_helper_t * ctx) static
Assumes that the file pattern to include is currently stored as string on the helper object.
Definition at line 2714 of file lexer.c.
References conf_parser_open_next_file(), parser_helper_t::file_include, free(), and parser_helper_t::string_get.
Referenced by while().
 {
     char *pattern = ctx->string_get(ctx);
     ctx->file_include(ctx, pattern);
     free(pattern);
     conf_parser_open_next_file(ctx);
 }
int isatty (int)
Referenced by conf_parser__init_buffer().
while (1)
Definition at line 1013 of file lexer.c.
References CA, conf_parser_open_next_file(), conf_parser_pop_buffer_state(), conf_parser_wrap, CONFIG_SETUP, CONN, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, EQ, fprintf, inc, include_files(), INITIAL, NEWLINE, PARSER_DBG1, SPACES, str, strdup, streq(), STRING, STRING_ERROR, unput, yy_accept, YY_AT_BOL, yy_base, YY_BREAK, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_def, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_flex_debug, yy_get_next_buffer(), yy_get_previous_state(), yyguts_t::yy_hold_char, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_nxt, yy_pop_state(), yy_push_state(), YY_RESTORE_YY_MORE_OFFSET, yy_rule_can_match_eol, yy_rule_linenum, YY_RULE_SETUP, YY_SC_TO_UI, yy_set_bol, YY_START, yyguts_t::yy_start, YY_STATE_EOF, yy_top_state(), yy_try_NUL_trans(), yycolumn, yyextra, yyin, yyleng, yylineno, yylval, yyterminate, and yytext.
         {
 /* %% [8.0] yymore()-related code goes here */
         yy_cp = yyg->yy_c_buf_p;
         /* Support of yytext. */
         *yy_cp = yyg->yy_hold_char;
         /* yy_bp points to the position in yy_ch_buf of the start of
          * the current run.
          */
         yy_bp = yy_cp;
 /* %% [9.0] code to set up and find next match goes here */
         yy_current_state = yyg->yy_start;
         yy_current_state += YY_AT_BOL();
 yy_match:
         do
             {
             register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
             if ( yy_accept[yy_current_state] )
                 {
                 yyg->yy_last_accepting_state = yy_current_state;
                 yyg->yy_last_accepting_cpos = yy_cp;
                 }
             while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                 {
                 yy_current_state = (int) yy_def[yy_current_state];
                 if ( yy_current_state >= 80 )
                     yy_c = yy_meta[(unsigned int) yy_c];
                 }
             yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
             ++yy_cp;
             }
         while ( yy_base[yy_current_state] != 184 );
 yy_find_action:
 /* %% [10.0] code to find the action number goes here */
         yy_act = yy_accept[yy_current_state];
         if ( yy_act == 0 )
             { /* have to back up */
             yy_cp = yyg->yy_last_accepting_cpos;
             yy_current_state = yyg->yy_last_accepting_state;
             yy_act = yy_accept[yy_current_state];
             }
         YY_DO_BEFORE_ACTION;
 /* %% [11.0] code for yylineno update goes here */
         if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
             {
             int yyl;
             for ( yyl = 0; yyl < yyleng; ++yyl )
                 if ( yytext[yyl] == '\n' )
     do{ yylineno++;
         yycolumn=0;
     }while(0)
 ;
             }
 do_action:  /* This label is used only to access EOF actions. */
 /* %% [12.0] debug code goes here */
         if ( yy_flex_debug )
             {
             if ( yy_act == 0 )
                 fprintf( stderr, "--scanner backing up\n" );
             else if ( yy_act < 26 )
                 fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
                          (long)yy_rule_linenum[yy_act], yytext );
             else if ( yy_act == 26 )
                 fprintf( stderr, "--accepting default rule (\"%s\")\n",
                          yytext );
             else if ( yy_act == 27 )
                 fprintf( stderr, "--(end of buffer or a NUL)\n" );
             else
                 fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
             }
         switch ( yy_act )
     { /* beginning of action switch */
 /* %% [13.0] actions go here */
             case 0: /* must back up */
             /* undo the effects of YY_DO_BEFORE_ACTION */
             *yy_cp = yyg->yy_hold_char;
             yy_cp = yyg->yy_last_accepting_cpos;
             yy_current_state = yyg->yy_last_accepting_state;
             goto yy_find_action;
 case 1:
 *yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
 yyg->yy_c_buf_p = yy_cp -= 1;
 YY_DO_BEFORE_ACTION; /* set up yytext again */
 YY_RULE_SETUP
 #line 60 "parser/lexer.l"
 /* eat legacy version delcaration */
     YY_BREAK
 case 2:
 YY_RULE_SETUP
 #line 61 "parser/lexer.l"
 return SPACES;
     YY_BREAK
 case 3:
 YY_RULE_SETUP
 #line 62 "parser/lexer.l"
 /* eat other whitespace */
     YY_BREAK
 case 4:
 YY_RULE_SETUP
 #line 63 "parser/lexer.l"
 /* eat comments */
     YY_BREAK
 case 5:
 /* rule 5 can match eol */
 YY_RULE_SETUP
 #line 65 "parser/lexer.l"
 return NEWLINE;
     YY_BREAK
 case 6:
 YY_RULE_SETUP
 #line 67 "parser/lexer.l"
 return EQ;
     YY_BREAK
 case 7:
 YY_RULE_SETUP
 #line 68 "parser/lexer.l"
 return CONFIG_SETUP;
     YY_BREAK
 case 8:
 YY_RULE_SETUP
 #line 69 "parser/lexer.l"
 return CONN;
     YY_BREAK
 case 9:
 YY_RULE_SETUP
 #line 70 "parser/lexer.l"
 return CA;
     YY_BREAK
 case 10:
 /* rule 10 can match eol */
 *yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
 yyg->yy_c_buf_p = yy_cp -= 1;
 YY_DO_BEFORE_ACTION; /* set up yytext again */
 YY_RULE_SETUP
 #line 72 "parser/lexer.l"
 {
     yyextra->string_init(yyextra);
     yy_push_state(inc, yyscanner);
 }
     YY_BREAK
 case 11:
 YY_RULE_SETUP
 #line 77 "parser/lexer.l"
 {
     yyextra->string_init(yyextra);
     yy_push_state(str, yyscanner);
 }
     YY_BREAK
 case 12:
 YY_RULE_SETUP
 #line 82 "parser/lexer.l"
 {
     yylval->s = strdup(yytext);
     return STRING;
 }
     YY_BREAK
 /* we allow all characters except # and spaces, they can be escaped */
 case YY_STATE_EOF(inc):
 #line 89 "parser/lexer.l"
 case 13:
 /* rule 13 can match eol */
 YY_RULE_SETUP
 #line 90 "parser/lexer.l"
 {
         if (*yytext)
         {
             switch (yytext[0])
             {
                 case '\n':
                     /* put the newline back to fix the line numbers */
                     unput('\n');
                     yy_set_bol(0);
                     break;
                 case '#':
                     /* comments are parsed outside of this start condition */
                     unput(yytext[0]);
                     break;
             }
         }
         include_files(yyextra);
         yy_pop_state(yyscanner);
     }
     YY_BREAK
 case 14:
 YY_RULE_SETUP
 #line 109 "parser/lexer.l"
 {   /* string include */
         yy_push_state(str, yyscanner);
     }
     YY_BREAK
 case 15:
 YY_RULE_SETUP
 #line 112 "parser/lexer.l"
 {
         yyextra->string_add(yyextra, yytext);
     }
     YY_BREAK
 case 16:
 YY_RULE_SETUP
 #line 115 "parser/lexer.l"
 {
         yyextra->string_add(yyextra, yytext+1);
     }
     YY_BREAK
 case 17:
 YY_RULE_SETUP
 #line 118 "parser/lexer.l"
 {
         yyextra->string_add(yyextra, yytext);
     }
     YY_BREAK
 case 18:
 #line 125 "parser/lexer.l"
 case YY_STATE_EOF(str):
 #line 125 "parser/lexer.l"
 case 19:
 YY_RULE_SETUP
 #line 126 "parser/lexer.l"
 {
         if (!streq(yytext, "\""))
         {
             PARSER_DBG1(yyextra, "unterminated string detected");
             return STRING_ERROR;
         }
         if (yy_top_state(yyscanner) == inc)
         {   /* string include */
             include_files(yyextra);
             yy_pop_state(yyscanner);
             yy_pop_state(yyscanner);
         }
         else
         {
             yy_pop_state(yyscanner);
             yylval->s = yyextra->string_get(yyextra);
             return STRING;
         }
     }
     YY_BREAK
 case 20:
 YY_RULE_SETUP
 #line 145 "parser/lexer.l"
 yyextra->string_add(yyextra, "\n");
     YY_BREAK
 case 21:
 YY_RULE_SETUP
 #line 146 "parser/lexer.l"
 yyextra->string_add(yyextra, "\r");
     YY_BREAK
 case 22:
 YY_RULE_SETUP
 #line 147 "parser/lexer.l"
 yyextra->string_add(yyextra, "\t");
     YY_BREAK
 case 23:
 /* rule 23 can match eol */
 YY_RULE_SETUP
 #line 148 "parser/lexer.l"
 /* merge lines that end with EOL characters */
     YY_BREAK
 case 24:
 YY_RULE_SETUP
 #line 149 "parser/lexer.l"
 yyextra->string_add(yyextra, yytext+1);
     YY_BREAK
 case 25:
 /* rule 25 can match eol */
 YY_RULE_SETUP
 #line 150 "parser/lexer.l"
 {
         yyextra->string_add(yyextra, yytext);
     }
     YY_BREAK
 case YY_STATE_EOF(INITIAL):
 #line 155 "parser/lexer.l"
 {
     conf_parser_pop_buffer_state(yyscanner);
     if (!conf_parser_open_next_file(yyextra) && !YY_CURRENT_BUFFER)
     {
         yyterminate();
     }
 }
     YY_BREAK
 case 26:
 YY_RULE_SETUP
 #line 163 "parser/lexer.l"
 YY_FATAL_ERROR( "flex scanner jammed" );
     YY_BREAK
 #line 1317 "parser/lexer.c"
     case YY_END_OF_BUFFER:
         {
         /* Amount of text matched not including the EOB char. */
         int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;
         /* Undo the effects of YY_DO_BEFORE_ACTION. */
         *yy_cp = yyg->yy_hold_char;
         YY_RESTORE_YY_MORE_OFFSET
         if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
             {
             /* We're scanning a new file or input source.  It's
              * possible that this happened because the user
              * just pointed yyin at a new source and called
              * conf_parser_lex().  If so, then we have to assure
              * consistency between YY_CURRENT_BUFFER and our
              * globals.  Here is the right place to do so, because
              * this is the first action (other than possibly a
              * back-up) that will match for the new input source.
              */
             yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
             YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
             YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
             }
         /* Note that here we test for yy_c_buf_p "<=" to the position
          * of the first EOB in the buffer, since yy_c_buf_p will
          * already have been incremented past the NUL character
          * (since all states make transitions on EOB to the
          * end-of-buffer state).  Contrast this with the test
          * in input().
          */
         if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
             { /* This was really a NUL. */
             yy_state_type yy_next_state;
             yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;
             yy_current_state = yy_get_previous_state( yyscanner );
             /* Okay, we're now positioned to make the NUL
              * transition.  We couldn't have
              * yy_get_previous_state() go ahead and do it
              * for us because it doesn't know how to deal
              * with the possibility of jamming (and we don't
              * want to build jamming into it because then it
              * will run more slowly).
              */
             yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);
             yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
             if ( yy_next_state )
                 {
                 /* Consume the NUL. */
                 yy_cp = ++yyg->yy_c_buf_p;
                 yy_current_state = yy_next_state;
                 goto yy_match;
                 }
             else
                 {
 /* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
                 yy_cp = yyg->yy_c_buf_p;
                 goto yy_find_action;
                 }
             }
         else switch ( yy_get_next_buffer( yyscanner ) )
             {
             case EOB_ACT_END_OF_FILE:
                 {
                 yyg->yy_did_buffer_switch_on_eof = 0;
                 if ( conf_parser_wrap(yyscanner ) )
                     {
                     /* Note: because we've taken care in
                      * yy_get_next_buffer() to have set up
                      * yytext, we can now set up
                      * yy_c_buf_p so that if some total
                      * hoser (like flex itself) wants to
                      * call the scanner after we return the
                      * YY_NULL, it'll still work - another
                      * YY_NULL will get returned.
                      */
                     yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;
                     yy_act = YY_STATE_EOF(YY_START);
                     goto do_action;
                     }
                 else
                     {
                     if ( ! yyg->yy_did_buffer_switch_on_eof )
                         YY_NEW_FILE;
                     }
                 break;
                 }
             case EOB_ACT_CONTINUE_SCAN:
                 yyg->yy_c_buf_p =
                     yyg->yytext_ptr + yy_amount_of_matched_text;
                 yy_current_state = yy_get_previous_state( yyscanner );
                 yy_cp = yyg->yy_c_buf_p;
                 yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                 goto yy_match;
             case EOB_ACT_LAST_MATCH:
                 yyg->yy_c_buf_p =
                 &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];
                 yy_current_state = yy_get_previous_state( yyscanner );
                 yy_cp = yyg->yy_c_buf_p;
                 yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                 goto yy_find_action;
             }
         break;
         }
     default:
         YY_FATAL_ERROR(
             "fatal flex scanner internal error--no action found" );
     } /* end of action switch */
         } /* end of scanning one token */
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner) static
Referenced by conf_parser_set_column(), and conf_parser_set_lineno().
static void yy_fatal_error (yyconst char * msg, yyscan_t yyscanner) static
Definition at line 2298 of file lexer.c.
References fprintf, and YY_EXIT_FAILURE.
 {
         (void) fprintf( stderr, "%s\n", msg );
     exit( YY_EXIT_FAILURE );
 }
static int yy_get_next_buffer (yyscan_t yyscanner) static
Definition at line 1464 of file lexer.c.
References b, conf_parser_realloc(), conf_parser_restart(), dest, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, source, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_READ_BUF_SIZE, and yyin.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
     register char *source = yyg->yytext_ptr;
     register int number_to_move, i;
     int ret_val;
     if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
         YY_FATAL_ERROR(
         "fatal flex scanner internal error--end of buffer missed" );
     if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
         { /* Don't try to fill the buffer, so this is an EOF. */
         if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
             {
             /* We matched a single character, the EOB, so
              * treat this as a final EOF.
              */
             return EOB_ACT_END_OF_FILE;
             }
         else
             {
             /* We matched some text prior to the EOB, first
              * process it.
              */
             return EOB_ACT_LAST_MATCH;
             }
         }
     /* Try to read more data. */
     /* First move last chars to start of buffer. */
     number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;
     for ( i = 0; i < number_to_move; ++i )
         *(dest++) = *(source++);
     if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
         /* don't do the read, it's not guaranteed to return an EOF,
          * just force an EOF
          */
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;
     else
         {
             int num_to_read =
             YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
         while ( num_to_read <= 0 )
             { /* Not enough room in the buffer - grow it. */
             /* just a shorter name for the current buffer */
             YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
             int yy_c_buf_p_offset =
                 (int) (yyg->yy_c_buf_p - b->yy_ch_buf);
             if ( b->yy_is_our_buffer )
                 {
                 int new_size = b->yy_buf_size * 2;
                 if ( new_size <= 0 )
                     b->yy_buf_size += b->yy_buf_size / 8;
                 else
                     b->yy_buf_size *= 2;
                 b->yy_ch_buf = (char *)
                     /* Include room in for 2 EOB chars. */
                     conf_parser_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
                 }
             else
                 /* Can't grow it, we don't own it. */
                 b->yy_ch_buf = 0;
             if ( ! b->yy_ch_buf )
                 YY_FATAL_ERROR(
                 "fatal error - scanner input buffer overflow" );
             yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
             num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                         number_to_move - 1;
             }
         if ( num_to_read > YY_READ_BUF_SIZE )
             num_to_read = YY_READ_BUF_SIZE;
         /* Read in more data. */
         YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
             yyg->yy_n_chars, (size_t) num_to_read );
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
         }
     if ( yyg->yy_n_chars == 0 )
         {
         if ( number_to_move == YY_MORE_ADJ )
             {
             ret_val = EOB_ACT_END_OF_FILE;
             conf_parser_restart(yyin  ,yyscanner);
             }
         else
             {
             ret_val = EOB_ACT_LAST_MATCH;
             YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
                 YY_BUFFER_EOF_PENDING;
             }
         }
     else
         ret_val = EOB_ACT_CONTINUE_SCAN;
     if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
         /* Extend the array by 50%, plus the number we really need. */
         yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
         YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) conf_parser_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
         if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
             YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
     }
     yyg->yy_n_chars += number_to_move;
     YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
     YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
     yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];
     return ret_val;
 }
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) static
Definition at line 1605 of file lexer.c.
References yy_accept, YY_AT_BOL, yy_base, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, yy_def, yy_ec, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_nxt, YY_SC_TO_UI, and yyguts_t::yy_start.
Referenced by while().
 {
     register yy_state_type yy_current_state;
     register char *yy_cp;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
 /* %% [15.0] code to get the start state into yy_current_state goes here */
     yy_current_state = yyg->yy_start;
     yy_current_state += YY_AT_BOL();
     for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
         {
 /* %% [16.0] code to find the next state goes here */
         register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
         if ( yy_accept[yy_current_state] )
             {
             yyg->yy_last_accepting_state = yy_current_state;
             yyg->yy_last_accepting_cpos = yy_cp;
             }
         while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
             {
             yy_current_state = (int) yy_def[yy_current_state];
             if ( yy_current_state >= 80 )
                 yy_c = yy_meta[(unsigned int) yy_c];
             }
         yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
         }
     return yy_current_state;
 }
static int yy_init_globals (yyscan_t yyscanner) static
Definition at line 2565 of file lexer.c.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
Referenced by conf_parser_lex_destroy(), conf_parser_lex_init(), and conf_parser_lex_init_extra().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     /* Initialization is the same as for the non-reentrant scanner.
      * This function is called from conf_parser_lex_destroy(), so don't allocate here.
      */
     yyg->yy_buffer_stack = 0;
     yyg->yy_buffer_stack_top = 0;
     yyg->yy_buffer_stack_max = 0;
     yyg->yy_c_buf_p = (char *) 0;
     yyg->yy_init = 0;
     yyg->yy_start = 0;
     yyg->yy_start_stack_ptr = 0;
     yyg->yy_start_stack_depth = 0;
     yyg->yy_start_stack =  NULL;
 /* Defined in main.c */
 #ifdef YY_STDINIT
     yyin = stdin;
     yyout = stdout;
 #else
     yyin = (FILE *) 0;
     yyout = (FILE *) 0;
 #endif
     /* For future reference: Set errno on error, since we are called by
      * conf_parser_lex_init()
      */
     return 0;
 }
static void yy_pop_state (yyscan_t yyscanner) static
Definition at line 2271 of file lexer.c.
References BEGIN, YY_FATAL_ERROR, yyguts_t::yy_start_stack, and yyguts_t::yy_start_stack_ptr.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( --yyg->yy_start_stack_ptr < 0 )
         YY_FATAL_ERROR( "start-condition stack underflow" );
     BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
 }
static void yy_push_state (int new_state, yyscan_t yyscanner) static
Definition at line 2242 of file lexer.c.
References BEGIN, conf_parser_alloc(), conf_parser_realloc(), YY_FATAL_ERROR, YY_START, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, YY_START_STACK_INCR, and yyguts_t::yy_start_stack_ptr.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
         {
         yy_size_t new_size;
         yyg->yy_start_stack_depth += YY_START_STACK_INCR;
         new_size = yyg->yy_start_stack_depth * sizeof( int );
         if ( ! yyg->yy_start_stack )
             yyg->yy_start_stack = (int *) conf_parser_alloc(new_size ,yyscanner );
         else
             yyg->yy_start_stack = (int *) conf_parser_realloc((void *) yyg->yy_start_stack,new_size ,yyscanner );
         if ( ! yyg->yy_start_stack )
             YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
         }
     yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;
     BEGIN(new_state);
 }
static int yy_top_state (yyscan_t yyscanner) static
Definition at line 2284 of file lexer.c.
References yyguts_t::yy_start_stack, and yyguts_t::yy_start_stack_ptr.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyg->yy_start_stack[yyg->yy_start_stack_ptr - 1];
 }
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) static
Definition at line 1645 of file lexer.c.
References yy_accept, yy_base, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, yy_def, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, and yy_nxt.
Referenced by while().
 {
     register int yy_is_jam;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
 /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
     register char *yy_cp = yyg->yy_c_buf_p;
     register YY_CHAR yy_c = 1;
     if ( yy_accept[yy_current_state] )
         {
         yyg->yy_last_accepting_state = yy_current_state;
         yyg->yy_last_accepting_cpos = yy_cp;
         }
     while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
         {
         yy_current_state = (int) yy_def[yy_current_state];
         if ( yy_current_state >= 80 )
             yy_c = yy_meta[(unsigned int) yy_c];
         }
     yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
     yy_is_jam = (yy_current_state == 79);
     return yy_is_jam ? 0 : yy_current_state;
 }
static void yyunput (int c, char * buf_ptr, yyscan_t yyscanner) static
static void yyunput (int c, register char * yy_bp, yyscan_t yyscanner) static
Definition at line 1675 of file lexer.c.
References dest, source, yy_bp, yyguts_t::yy_c_buf_p, yy_cp, YY_CURRENT_BUFFER_LVALUE, YY_FATAL_ERROR, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yylineno.
 {
     register char *yy_cp;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yy_cp = yyg->yy_c_buf_p;
     /* undo effects of setting up yytext */
     *yy_cp = yyg->yy_hold_char;
     if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
         { /* need to shift things up to make room */
         /* +2 for EOB chars. */
         register int number_to_move = yyg->yy_n_chars + 2;
         register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
                     YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
         register char *source =
                 &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];
         while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
             *--dest = *--source;
         yy_cp += (int) (dest - source);
         yy_bp += (int) (dest - source);
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
             yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;
         if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
             YY_FATAL_ERROR( "flex scanner push-back overflow" );
         }
     *--yy_cp = (char) c;
 /* %% [18.0] update yylineno here */
     if ( c == '\n' ){
         --yylineno;
     }
     yyg->yytext_ptr = yy_bp;
     yyg->yy_hold_char = *yy_cp;
     yyg->yy_c_buf_p = yy_cp;
 }
Variable Documentation
yyconst flex_int16_t yy_accept[80] static
Initial value:
=
    {   0,
        0,    0,    0,    0,    0,    0,   27,   12,    3,    5,
       11,    4,    6,   12,   12,    2,   12,   12,   17,   13,
       14,   15,   25,   18,   19,   12,    3,    4,    4,    0,
       12,    2,    0,    9,   12,   12,   17,   16,   25,   24,
       23,   24,   20,   21,   22,   12,    0,   12,   12,   12,
        0,   12,    8,   12,   12,    0,   12,   12,   12,    0,
       12,   12,   12,    0,    0,   12,    0,    0,    0,   12,
        0,    1,   10,   10,    0,    0,    0,    7,    0
    }
Definition at line 468 of file lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register int yy_act
Definition at line 968 of file lexer.c.
yyconst flex_int16_t yy_base[91] static
Initial value:
=
    {   0,
        0,   16,   41,   50,    4,    5,  101,    0,   24,  184,
      184,    0,  184,   92,   79,   32,   16,   83,    0,  184,
      184,   56,    0,  184,   81,    0,   33,    0,    0,    0,
       84,   62,   81,    0,   75,   71,    0,  184,    0,  184,
      184,   89,  184,  184,  184,   73,   68,    1,   66,   62,
       63,   65,    0,   64,   67,   62,   62,   57,   62,   55,
       67,   47,   63,   40,   31,  104,   68,   47,   35,  111,
       42,  184,  184,   69,   17,    7,    9,  184,  184,  119,
      125,  131,  137,  143,  149,  154,  159,  165,  171,  177
    }
Definition at line 519 of file lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register char * yy_bp
Definition at line 967 of file lexer.c.
Referenced by yyunput().
yyconst flex_int16_t yy_chk[212] static
Initial value:
=
    {   0,
        0,    1,    1,    0,    1,    1,    1,    1,    1,    5,
        6,    0,    0,    5,    6,   48,    1,    2,    2,   48,
        2,    2,    2,    2,    2,    9,   17,    2,    9,   77,
        9,   76,    2,   16,   27,   17,   16,   27,   16,   27,
       75,    2,    3,    3,   71,    3,    3,    3,   69,   68,
        3,    4,    4,   65,    4,    4,    4,   16,   64,    4,
       22,   22,   22,   32,   63,   62,   32,   63,   32,   67,
       74,   61,   67,   74,   60,   59,   58,   57,   56,   55,
       54,   52,   22,   25,   25,   51,   50,   32,   49,   47,
       46,   42,   36,   35,   33,   31,   18,   15,   14,   25,
        7,    0,   25,    0,   25,   66,   66,    0,   66,   66,
       66,   66,   70,   70,    0,   70,   70,   70,   70,   80,
       80,   80,   80,   80,   80,   81,   81,   81,   81,   81,
       81,   82,   82,   82,   82,   82,   82,   83,    0,    0,
        0,    0,   83,   84,   84,    0,   84,   84,   84,   85,
        0,    0,    0,   85,   86,   86,   86,    0,   86,   87,
       87,   87,   87,   87,   87,   88,   88,   88,   88,   88,
       88,   89,   89,   89,   89,    0,   89,   90,   90,   90,
       90,   90,   90,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79
    }
Definition at line 573 of file lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register char* yy_cp
Definition at line 967 of file lexer.c.
Referenced by while(), yy_get_previous_state(), yy_try_NUL_trans(), and yyunput().
YY_DECL
Initial value:
{
    register yy_state_type yy_current_state
The main scanner function which does all the work.
Definition at line 965 of file lexer.c.
yyconst flex_int16_t yy_def[91] static
Initial value:
=
    {   0,
       80,   80,   81,   81,   82,   82,   79,   83,   79,   79,
       79,   84,   79,   83,   83,   79,   83,   83,   85,   79,
       79,   79,   86,   79,   87,   83,   79,   84,   84,   83,
       83,   79,   79,   83,   83,   83,   85,   79,   86,   79,
       79,   79,   79,   79,   79,   83,   79,   83,   83,   83,
       79,   83,   83,   83,   83,   79,   83,   83,   83,   79,
       83,   83,   83,   79,   79,   88,   89,   90,   79,   88,
       90,   79,   79,   89,   79,   79,   79,   79,    0,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79
    }
Definition at line 532 of file lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int32_t yy_ec[256] static
Definition at line 480 of file lexer.c.
Referenced by while(), and yy_get_previous_state().
yyconst flex_int32_t yy_meta[28] static
Initial value:
=
    {   0,
        1,    2,    3,    1,    2,    4,    2,    5,    1,    6,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    }
Definition at line 512 of file lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int16_t yy_nxt[212] static
Initial value:
=
    {   0,
       79,    9,   10,   79,    9,   11,   12,   13,   14,   24,
       24,   79,   79,   25,   25,   52,   15,   16,   10,   53,
       16,   11,   12,   13,   14,   27,   34,   17,   27,   78,
       28,   77,   15,   32,   27,   35,   32,   27,   28,   28,
       76,   18,   20,   20,   72,   20,   21,   20,   75,   72,
       22,   20,   20,   69,   20,   21,   20,   33,   68,   22,
       38,   38,   38,   32,   67,   66,   32,   67,   28,   74,
       74,   65,   74,   74,   64,   63,   62,   61,   60,   59,
       58,   57,   38,   41,   42,   56,   55,   33,   54,   51,
       50,   41,   49,   48,   47,   46,   36,   31,   30,   43,
       79,   79,   44,   79,   45,   71,   72,   79,   71,   71,
       71,   71,   71,   72,   79,   71,   71,   71,   71,    8,
        8,    8,    8,    8,    8,   19,   19,   19,   19,   19,
       19,   23,   23,   23,   23,   23,   23,   26,   79,   79,
       79,   79,   26,   29,   29,   79,   29,   29,   29,   37,
       79,   79,   79,   37,   39,   39,   39,   79,   39,   40,
       40,   40,   40,   40,   40,   70,   70,   70,   70,   70,
       70,   73,   73,   73,   73,   79,   73,   71,   71,   71,
       71,   71,   71,    7,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79
    }
Definition at line 545 of file lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int32_t yy_rule_can_match_eol[27] static
Initial value:
=
    {   0,
0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 1, 0,     }
Definition at line 602 of file lexer.c.
Referenced by while().
yyconst flex_int16_t yy_rule_linenum[26] static
Initial value:
=
    {   0,
       60,   61,   62,   63,   65,   67,   68,   69,   70,   72,
       77,   82,   90,  109,  112,  115,  118,  124,  126,  145,
      146,  147,  148,  149,  150
    }
Definition at line 607 of file lexer.c.
Referenced by while().
struct yyguts_t* yyg = (struct yyguts_t*)yyscanner
Definition at line 969 of file lexer.c.
yylval = yylval_param
Definition at line 977 of file lexer.c.