strongSwan: ietf_attr_pa_tnc_error_t Struct Reference
ietf_attr_pa_tnc_error_t Struct Reference
ietf_attr_pa_tnc_error
#include "ietf_attr_pa_tnc_error.h"
Public Attributes
pa_tnc_attr_t pa_tnc_attribute
pen_type_t(* get_error_code)(ietf_attr_pa_tnc_error_t *this)
chunk_t(* get_msg_info)(ietf_attr_pa_tnc_error_t *this)
pen_type_t(* get_unsupported_attr)(ietf_attr_pa_tnc_error_t *this, uint8_t *flags)
void(* set_unsupported_attr)(ietf_attr_pa_tnc_error_t *this, uint8_t flags, pen_type_t type)
uint32_t(* get_offset)(ietf_attr_pa_tnc_error_t *this)
Detailed Description
Class implementing the IETF PA-TNC Error attribute.
Definition at line 50 of file ietf_attr_pa_tnc_error.h.
Member Data Documentation
pen_type_t(* ietf_attr_pa_tnc_error_t::get_error_code)(ietf_attr_pa_tnc_error_t *this)
Get Vendor-specific PA-TNC error code
Returns
error code
Definition at line 62 of file ietf_attr_pa_tnc_error.h.
Referenced by METHOD(), receive_message(), receive_msg(), and START_TEST().
chunk_t(* ietf_attr_pa_tnc_error_t::get_msg_info)(ietf_attr_pa_tnc_error_t *this)
Get first 8 bytes of erroneous PA-TNC message
Returns
PA-TNC message info
Definition at line 69 of file ietf_attr_pa_tnc_error.h.
Referenced by METHOD(), receive_message(), and receive_msg().
uint32_t(* ietf_attr_pa_tnc_error_t::get_offset)(ietf_attr_pa_tnc_error_t *this)
Get the PA-TNC error offset
Returns
PA-TNC error offset
Definition at line 94 of file ietf_attr_pa_tnc_error.h.
Referenced by METHOD().
pen_type_t(* ietf_attr_pa_tnc_error_t::get_unsupported_attr)(ietf_attr_pa_tnc_error_t *this, uint8_t *flags)
Get flags, vendor ID and type of unsupported PA-TNC attribute
Parameters
flags PA-TNC attribute flags
Returns
PA-TNC attribute vendor ID and type
Definition at line 77 of file ietf_attr_pa_tnc_error.h.
Referenced by METHOD().
pa_tnc_attr_t ietf_attr_pa_tnc_error_t::pa_tnc_attribute
Public PA-TNC attribute interface
Definition at line 55 of file ietf_attr_pa_tnc_error.h.
void(* ietf_attr_pa_tnc_error_t::set_unsupported_attr)(ietf_attr_pa_tnc_error_t *this, uint8_t flags, pen_type_t type)
Set flags, vendor ID and type of unsupported PA-TNC attribute
Parameters
flags PA-TNC attribute flags
attr_info PA-TNC attribute vendor ID and type
Definition at line 86 of file ietf_attr_pa_tnc_error.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ietf_attr_pa_tnc_error.h