strongSwan: inactivity_job.c File Reference
inactivity_job.c File Reference
#include "inactivity_job.h"
#include <daemon.h>
Classes
struct private_inactivity_job_t
Typedefs
typedef struct
private_inactivity_job_t private_inactivity_job_t
Functions
METHOD (job_t, destroy, void, private_inactivity_job_t *this)
METHOD (job_t, execute, job_requeue_t, private_inactivity_job_t *this)
METHOD (job_t, get_priority, job_priority_t, private_inactivity_job_t *this)
inactivity_job_t * inactivity_job_create (u_int32_t unique_id, u_int32_t timeout, bool close_ike)
Typedef Documentation
typedef struct private_inactivity_job_t private_inactivity_job_t
Definition at line 20 of file inactivity_job.c.
Function Documentation
METHOD (job_t , destroy , void , private_inactivity_job_t * this)
Definition at line 48 of file inactivity_job.c.
References free().
 {
     free(this);
 }
METHOD (job_t , execute , job_requeue_t , private_inactivity_job_t * this)
Definition at line 54 of file inactivity_job.c.
References charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, child_sa_manager_t::checkout_by_id, daemon_t::child_sa_manager, close_ike(), ike_sa_t::create_child_sa_enumerator, DBG1, DBG_JOB, ike_sa_t::delete, ike_sa_t::delete_child_sa, enumerator_t::destroy, DESTROY_ME, enumerator_t::enumerate, FALSE, child_sa_t::get_installtime, child_sa_t::get_protocol, child_sa_t::get_spi, child_sa_t::get_unique_id, child_sa_t::get_usestats, id, daemon_t::ike_sa_manager, in, install(), JOB_REQUEUE_NONE, JOB_RESCHEDULE, max, out, proto, status, SUCCESS, time_monotonic(), and TRUE.
 {
     ike_sa_t *ike_sa;
     u_int32_t reschedule = 0;
     ike_sa = charon->child_sa_manager->checkout_by_id(charon->child_sa_manager,
                                                       this->id, NULL);
     if (ike_sa)
     {
         enumerator_t *enumerator;
         child_sa_t *child_sa;
         u_int32_t delete = 0;
         protocol_id_t proto = 0;
         int children = 0;
         status_t status = SUCCESS;
         enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
         while (enumerator->enumerate(enumerator, &child_sa))
         {
             if (child_sa->get_unique_id(child_sa) == this->id)
             {
                 time_t in, out, install, diff;
                 child_sa->get_usestats(child_sa, TRUE, &in, NULL, NULL);
                 child_sa->get_usestats(child_sa, FALSE, &out, NULL, NULL);
                 install = child_sa->get_installtime(child_sa);
                 diff = time_monotonic(NULL) - max(max(in, out), install);
                 if (diff >= this->timeout)
                 {
                     delete = child_sa->get_spi(child_sa, TRUE);
                     proto = child_sa->get_protocol(child_sa);
                 }
                 else
                 {
                     reschedule = this->timeout - diff;
                 }
             }
             children++;
         }
         enumerator->destroy(enumerator);
         if (delete)
         {
             if (children == 1 && this->close_ike)
             {
                 DBG1(DBG_JOB, "deleting IKE_SA after %d seconds "
                      "of CHILD_SA inactivity", this->timeout);
                 status = ike_sa->delete(ike_sa);
             }
             else
             {
                 DBG1(DBG_JOB, "deleting CHILD_SA after %d seconds "
                      "of inactivity", this->timeout);
                 status = ike_sa->delete_child_sa(ike_sa, proto, delete, FALSE);
             }
         }
         if (status == DESTROY_ME)
         {
             charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                         ike_sa);
         }
         else
         {
             charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
         }
     }
     if (reschedule)
     {
         return JOB_RESCHEDULE(reschedule);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (job_t , get_priority , job_priority_t , private_inactivity_job_t * this)
Definition at line 130 of file inactivity_job.c.
References JOB_PRIO_MEDIUM.
 {
     return JOB_PRIO_MEDIUM;
 }