strongSwan: tcg_pts_attr_get_aik.c File Reference
tcg_pts_attr_get_aik.c File Reference
#include "tcg_pts_attr_get_aik.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_get_aik_t
Macros
#define PTS_GET_AIK_SIZE 4
#define PTS_GET_AIK_RESERVED 0x00000000
Typedefs
typedef struct
private_tcg_pts_attr_get_aik_t private_tcg_pts_attr_get_aik_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_get_aik_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_get_aik_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_get_aik_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_get_aik_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_get_aik_t *this)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_get_aik_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_get_aik_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_get_aik_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_get_aik_t *this)
pa_tnc_attr_t * tcg_pts_attr_get_aik_create ()
pa_tnc_attr_t * tcg_pts_attr_get_aik_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define PTS_GET_AIK_RESERVED 0x00000000
Definition at line 38 of file tcg_pts_attr_get_aik.c.
Referenced by METHOD().
#define PTS_GET_AIK_SIZE 4
Get Attestation Identity Key see section 3.12 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 37 of file tcg_pts_attr_get_aik.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_get_aik_t private_tcg_pts_attr_get_aik_t
Definition at line 24 of file tcg_pts_attr_get_aik.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_get_aik_t * this)
Definition at line 76 of file tcg_pts_attr_get_aik.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_get_aik_t * this)
Definition at line 82 of file tcg_pts_attr_get_aik.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_get_aik_t * this)
Definition at line 88 of file tcg_pts_attr_get_aik.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_get_aik_t * this, bool noskip)
Definition at line 94 of file tcg_pts_attr_get_aik.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_get_aik_t * this)
Definition at line 100 of file tcg_pts_attr_get_aik.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, PTS_GET_AIK_RESERVED, PTS_GET_AIK_SIZE, value, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PTS_GET_AIK_SIZE);
     writer->write_uint32 (writer, PTS_GET_AIK_RESERVED);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_get_aik_t * this, chunk_t segment)
Definition at line 117 of file tcg_pts_attr_get_aik.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_get_aik_t * this, u_int32_t * offset)
Definition at line 123 of file tcg_pts_attr_get_aik.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, PTS_GET_AIK_SIZE, bio_reader_t::read_uint32, reserved, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int32_t reserved;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_GET_AIK_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for Get AIK");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint32 (reader, &reserved);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_get_aik_t * this)
Definition at line 147 of file tcg_pts_attr_get_aik.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_get_aik_t * this)
Definition at line 154 of file tcg_pts_attr_get_aik.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
      }
 }