strongSwan: tcg_swid_attr_tag_id_inv_t Struct Reference
tcg_swid_attr_tag_id_inv_t Struct Reference
tcg_swid_attr_tag_id_inv
#include "tcg_swid_attr_tag_id_inv.h"
Public Attributes
pa_tnc_attr_t pa_tnc_attribute
void(* add)(tcg_swid_attr_tag_id_inv_t *this, swid_tag_id_t *tag_id)
uint32_t(* get_request_id)(tcg_swid_attr_tag_id_inv_t *this)
uint32_t(* get_last_eid)(tcg_swid_attr_tag_id_inv_t *this, uint32_t *eid_epoch)
uint32_t(* get_tag_id_count)(tcg_swid_attr_tag_id_inv_t *this)
swid_inventory_t *(* get_inventory)(tcg_swid_attr_tag_id_inv_t *this)
void(* clear_inventory)(tcg_swid_attr_tag_id_inv_t *this)
Detailed Description
Class implementing the TCG SWID Tag Identifier Inventory attribute
Definition at line 38 of file tcg_swid_attr_tag_id_inv.h.
Member Data Documentation
void(* tcg_swid_attr_tag_id_inv_t::add)(tcg_swid_attr_tag_id_inv_t *this, swid_tag_id_t *tag_id)
Add a Tag ID to the attribute
Parameters
tag_id SWID Tag ID to be added
Definition at line 50 of file tcg_swid_attr_tag_id_inv.h.
Referenced by add_swid_inventory().
void(* tcg_swid_attr_tag_id_inv_t::clear_inventory)(tcg_swid_attr_tag_id_inv_t *this)
Remove all SWID Tag IDs from the Inventory
Definition at line 85 of file tcg_swid_attr_tag_id_inv.h.
Referenced by receive_msg().
swid_inventory_t*(* tcg_swid_attr_tag_id_inv_t::get_inventory)(tcg_swid_attr_tag_id_inv_t *this)
Get Inventory of SWID tag IDs
Returns
SWID Tag ID Inventory
Definition at line 80 of file tcg_swid_attr_tag_id_inv.h.
Referenced by receive_msg().
uint32_t(* tcg_swid_attr_tag_id_inv_t::get_last_eid)(tcg_swid_attr_tag_id_inv_t *this, uint32_t *eid_epoch)
Get Last Event ID
Parameters
eid_epoch Event ID Epoch
Returns
Last Event ID
Definition at line 65 of file tcg_swid_attr_tag_id_inv.h.
Referenced by receive_msg().
uint32_t(* tcg_swid_attr_tag_id_inv_t::get_request_id)(tcg_swid_attr_tag_id_inv_t *this)
Get Request ID
Returns
Request ID
Definition at line 57 of file tcg_swid_attr_tag_id_inv.h.
Referenced by receive_msg().
uint32_t(* tcg_swid_attr_tag_id_inv_t::get_tag_id_count)(tcg_swid_attr_tag_id_inv_t *this)
Get count of remaining SWID tag IDs
Returns
SWID Tag ID count
Definition at line 73 of file tcg_swid_attr_tag_id_inv.h.
Referenced by receive_msg().
pa_tnc_attr_t tcg_swid_attr_tag_id_inv_t::pa_tnc_attribute
Public PA-TNC attribute interface
Definition at line 43 of file tcg_swid_attr_tag_id_inv.h.
The documentation for this struct was generated from the following file:
tcg_swid_attr_tag_id_inv.h