strongSwan: kernel_netlink_shared.c File Reference
kernel_netlink_shared.c File Reference
#include <sys/socket.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/xfrm.h>
#include <errno.h>
#include <unistd.h>
#include "kernel_netlink_shared.h"
#include <utils/debug.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <collections/array.h>
#include <collections/hashtable.h>
Classes
struct private_netlink_socket_t
struct entry_t
Macros
#define msg_loss_hook(msg) FALSE
Typedefs
typedef struct
private_netlink_socket_t private_netlink_socket_t
Functions
static void destroy_entry (entry_t *entry)
static bool write_msg (private_netlink_socket_t *this, struct nlmsghdr *msg)
static ssize_t read_msg (private_netlink_socket_t *this, char *buf, size_t buflen, bool block)
static bool queue (private_netlink_socket_t *this, struct nlmsghdr *buf)
static bool read_and_queue (private_netlink_socket_t *this, bool block)
CALLBACK (watch, bool, private_netlink_socket_t *this, int fd, watcher_event_t event)
static status_t send_once (private_netlink_socket_t *this, struct nlmsghdr *in, uintptr_t seq, struct nlmsghdr **out, size_t *out_len)
static void ignore_retransmit_error (private_netlink_socket_t *this, struct nlmsgerr *err, int type)
METHOD (netlink_socket_t, netlink_send, status_t, private_netlink_socket_t *this, struct nlmsghdr *in, struct nlmsghdr **out, size_t *out_len)
METHOD (netlink_socket_t, netlink_send_ack, status_t, private_netlink_socket_t *this, struct nlmsghdr *in)
METHOD (netlink_socket_t, destroy, void, private_netlink_socket_t *this)
netlink_socket_t * netlink_socket_create (int protocol, enum_name_t *names, bool parallel)
void netlink_add_attribute (struct nlmsghdr *hdr, int rta_type, chunk_t data, size_t buflen)
void * netlink_reserve (struct nlmsghdr *hdr, int buflen, int type, int len)
Macro Definition Documentation
#define msg_loss_hook (msg) FALSE
#definable hook to simulate request message loss
Definition at line 108 of file kernel_netlink_shared.c.
Referenced by write_msg().
Typedef Documentation
typedef struct private_netlink_socket_t private_netlink_socket_t
Definition at line 33 of file kernel_netlink_shared.c.
Function Documentation
CALLBACK (watch , bool , private_netlink_socket_t * this, int fd, watcher_event_t event)
Definition at line 267 of file kernel_netlink_shared.c.
References FALSE, read_and_queue(), TRUE, and WATCHER_READ.
 {
     if (event == WATCHER_READ)
     {
         read_and_queue(this, FALSE);
     }
     return TRUE;
 }
static void destroy_entry (entry_t * entry) static
Clean up a thread waiting entry
Definition at line 126 of file kernel_netlink_shared.c.
References array_destroy_function(), entry_t::condvar, condvar_t::destroy, free(), and entry_t::hdrs.
Referenced by send_once().
 {
     entry->condvar->destroy(entry->condvar);
     array_destroy_function(entry->hdrs, (void*)free, NULL);
     free(entry);
 }
static void ignore_retransmit_error (private_netlink_socket_t * this, struct nlmsgerr * err, int type) static
Ignore errors for message types that might have completed previously
Definition at line 367 of file kernel_netlink_shared.c.
References nlmsgerr::error, NETLINK_ROUTE, NETLINK_XFRM, protocol, RTM_DELADDR, RTM_DELLINK, RTM_DELNEIGH, RTM_DELROUTE, RTM_DELRULE, RTM_NEWADDR, RTM_NEWLINK, RTM_NEWNEIGH, RTM_NEWROUTE, RTM_NEWRULE, XFRM_MSG_DELPOLICY, XFRM_MSG_DELSA, XFRM_MSG_NEWPOLICY, and XFRM_MSG_NEWSA.
Referenced by METHOD().
 {
     switch (err->error)
     {
         case -EEXIST:
             switch (this->protocol)
             {
                 case NETLINK_XFRM:
                     switch (type)
                     {
                         case XFRM_MSG_NEWPOLICY:
                         case XFRM_MSG_NEWSA:
                             err->error = 0;
                             break;
                     }
                     break;
                 case NETLINK_ROUTE:
                     switch (type)
                     {
                         case RTM_NEWADDR:
                         case RTM_NEWLINK:
                         case RTM_NEWNEIGH:
                         case RTM_NEWROUTE:
                         case RTM_NEWRULE:
                             err->error = 0;
                             break;
                     }
                     break;
             }
             break;
         case -ENOENT:
             switch (this->protocol)
             {
                 case NETLINK_XFRM:
                     switch (type)
                     {
                         case XFRM_MSG_DELPOLICY:
                         case XFRM_MSG_DELSA:
                             err->error = 0;
                             break;
                     }
                     break;
                 case NETLINK_ROUTE:
                     switch (type)
                     {
                         case RTM_DELADDR:
                         case RTM_DELLINK:
                         case RTM_DELNEIGH:
                         case RTM_DELROUTE:
                         case RTM_DELRULE:
                             err->error = 0;
                             break;
                     }
                     break;
             }
             break;
     }
 }
METHOD (netlink_socket_t , netlink_send , status_t , private_netlink_socket_t * this, struct nlmsghdr * in, struct nlmsghdr ** out, size_t * out_len)
Definition at line 427 of file kernel_netlink_shared.c.
References DBG1, DBG_KNL, nlmsgerr::error, free(), ignore_retransmit_error(), len, NLMSG_DATA, NLMSG_ERROR, nlmsghdr::nlmsg_type, OUT_OF_RES, ref_get(), send_once(), seq, status, and SUCCESS.
 {
     uintptr_t seq;
     u_int try;
     seq = ref_get(&this->seq);
     for (try = 0; try <= this->retries; ++try)
     {
         struct nlmsghdr *hdr;
         status_t status;
         size_t len;
         if (try > 0)
         {
             DBG1(DBG_KNL, "retransmitting Netlink request (%u/%u)",
                  try, this->retries);
         }
         status = send_once(this, in, seq, &hdr, &len);
         switch (status)
         {
             case SUCCESS:
                 break;
             case OUT_OF_RES:
                 continue;
             default:
                 return status;
         }
         if (hdr->nlmsg_type == NLMSG_ERROR)
         {
             struct nlmsgerr* err;
             err = NLMSG_DATA(hdr);
             if (err->error == -EBUSY)
             {
                 free(hdr);
                 try--;
                 continue;
             }
             if (this->ignore_retransmit_errors && try > 0)
             {
                 ignore_retransmit_error(this, err, in->nlmsg_type);
             }
         }
         *out = hdr;
         *out_len = len;
         return SUCCESS;
     }
     DBG1(DBG_KNL, "Netlink request timed out after %u retransmits",
          this->retries);
     return OUT_OF_RES;
 }
METHOD (netlink_socket_t , netlink_send_ack , status_t , private_netlink_socket_t * this, struct nlmsghdr * in)
Definition at line 482 of file kernel_netlink_shared.c.
References ALREADY_DONE, DBG1, DBG_KNL, nlmsgerr::error, FAILED, free(), len, NLMSG_DATA, NLMSG_DONE, NLMSG_ERROR, NLMSG_NEXT, NLMSG_OK, nlmsghdr::nlmsg_type, NOT_FOUND, out, strerror, and SUCCESS.
 {
     struct nlmsghdr *out, *hdr;
     size_t len;
     if (netlink_send(this, in, &out, &len) != SUCCESS)
     {
         return FAILED;
     }
     hdr = out;
     while (NLMSG_OK(hdr, len))
     {
         switch (hdr->nlmsg_type)
         {
             case NLMSG_ERROR:
             {
                 struct nlmsgerr* err = NLMSG_DATA(hdr);
                 if (err->error)
                 {
                     if (-err->error == EEXIST)
                     {   /* do not report existing routes */
                         free(out);
                         return ALREADY_DONE;
                     }
                     if (-err->error == ESRCH)
                     {   /* do not report missing entries */
                         free(out);
                         return NOT_FOUND;
                     }
                     DBG1(DBG_KNL, "received netlink error: %s (%d)",
                          strerror(-err->error), -err->error);
                     free(out);
                     return FAILED;
                 }
                 free(out);
                 return SUCCESS;
             }
             default:
                 hdr = NLMSG_NEXT(hdr, len);
                 continue;
             case NLMSG_DONE:
                 break;
         }
         break;
     }
     DBG1(DBG_KNL, "netlink request not acknowledged");
     free(out);
     return FAILED;
 }
METHOD (netlink_socket_t , destroy , void , private_netlink_socket_t * this)
Definition at line 534 of file kernel_netlink_shared.c.
References close, mutex_t::destroy, free(), lib, mutex, watcher_t::remove, socket, and library_t::watcher.
 {
     if (this->socket != -1)
     {
         if (this->parallel)
         {
             lib->watcher->remove(lib->watcher, this->socket);
         }
         close(this->socket);
     }
     this->entries->destroy(this->entries);
     this->mutex->destroy(this->mutex);
     free(this);
 }
void netlink_add_attribute (struct nlmsghdr * hdr, int rta_type, chunk_t data, size_t buflen)
Described in header.
Definition at line 618 of file kernel_netlink_shared.c.
References DBG1, DBG_KNL, chunk_t::len, memcpy, NLMSG_ALIGN, nlmsghdr::nlmsg_len, chunk_t::ptr, RTA_DATA, rtattr::rta_len, RTA_LENGTH, and rtattr::rta_type.
Referenced by CALLBACK(), get_route(), manage_ipaddr(), manage_rule(), manage_srcroute(), METHOD(), and START_TEST().
 {
     struct rtattr *rta;
     if (NLMSG_ALIGN(hdr->nlmsg_len) + RTA_LENGTH(data.len) > buflen)
     {
         DBG1(DBG_KNL, "unable to add attribute, buffer too small");
         return;
     }
     rta = (struct rtattr*)(((char*)hdr) + NLMSG_ALIGN(hdr->nlmsg_len));
     rta->rta_type = rta_type;
     rta->rta_len = RTA_LENGTH(data.len);
     memcpy(RTA_DATA(rta), data.ptr, data.len);
     hdr->nlmsg_len = NLMSG_ALIGN(hdr->nlmsg_len) + rta->rta_len;
 }
void* netlink_reserve (struct nlmsghdr * hdr, int buflen, int type, int len)
Described in header.
Definition at line 639 of file kernel_netlink_shared.c.
References DBG1, DBG_KNL, NLMSG_ALIGN, nlmsghdr::nlmsg_len, RTA_DATA, rtattr::rta_len, RTA_LENGTH, rtattr::rta_type, and type.
Referenced by add_mark(), add_policy_internal(), and METHOD().
 {
     struct rtattr *rta;
     if (NLMSG_ALIGN(hdr->nlmsg_len) + RTA_LENGTH(len) > buflen)
     {
         DBG1(DBG_KNL, "unable to add attribute, buffer too small");
         return NULL;
     }
     rta = ((void*)hdr) + NLMSG_ALIGN(hdr->nlmsg_len);
     rta->rta_type = type;
     rta->rta_len = RTA_LENGTH(len);
     hdr->nlmsg_len = NLMSG_ALIGN(hdr->nlmsg_len) + rta->rta_len;
     return RTA_DATA(rta);
 }
netlink_socket_t* netlink_socket_create (int protocol, enum_name_t * names, bool parallel)
Described in header.
Definition at line 553 of file kernel_netlink_shared.c.
References watcher_t::add, bind, DBG1, DBG_KNL, destroy(), FALSE, settings_t::get_bool, settings_t::get_int, hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), INIT, lib, min, mutex_create(), MUTEX_TYPE_RECURSIVE, sockaddr_nl::nl_family, library_t::ns, protocol, library_t::settings, socket, watch(), library_t::watcher, and WATCHER_READ.
Referenced by kernel_netlink_ipsec_create(), kernel_netlink_net_create(), and START_TEST().
 {
     private_netlink_socket_t *this;
     struct sockaddr_nl addr = {
         .nl_family = AF_NETLINK,
     };
     INIT(this,
         .public = {
             .send = _netlink_send,
             .send_ack = _netlink_send_ack,
             .destroy = _destroy,
         },
         .seq = 200,
         .mutex = mutex_create(MUTEX_TYPE_RECURSIVE),
         .socket = socket(AF_NETLINK, SOCK_RAW, protocol),
         .entries = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 4),
         .protocol = protocol,
         .names = names,
         .buflen = lib->settings->get_int(lib->settings,
                             "%s.plugins.kernel-netlink.buflen", 0, lib->ns),
         .timeout = lib->settings->get_int(lib->settings,
                             "%s.plugins.kernel-netlink.timeout", 0, lib->ns),
         .retries = lib->settings->get_int(lib->settings,
                             "%s.plugins.kernel-netlink.retries", 0, lib->ns),
         .ignore_retransmit_errors = lib->settings->get_bool(lib->settings,
                             "%s.plugins.kernel-netlink.ignore_retransmit_errors",
                             FALSE, lib->ns),
         .parallel = parallel,
     );
     if (!this->buflen)
     {
         long pagesize = sysconf(_SC_PAGESIZE);
         if (pagesize == -1)
         {
             pagesize = 4096;
         }
         /* base this on NLMSG_GOODSIZE */
         this->buflen = min(pagesize, 8192);
     }
     if (this->socket == -1)
     {
         DBG1(DBG_KNL, "unable to create netlink socket");
         destroy(this);
         return NULL;
     }
     if (bind(this->socket, (struct sockaddr*)&addr, sizeof(addr)))
     {
         DBG1(DBG_KNL, "unable to bind netlink socket");
         destroy(this);
         return NULL;
     }
     if (this->parallel)
     {
         lib->watcher->add(lib->watcher, this->socket, WATCHER_READ, watch, this);
     }
     return &this->public;
 }
static bool queue (private_netlink_socket_t * this, struct nlmsghdr * buf) static
Queue received response message
Definition at line 208 of file kernel_netlink_shared.c.
References array_insert(), ARRAY_TAIL, entry_t::complete, entry_t::condvar, DBG1, DBG_KNL, entry_t::hdrs, malloc(), memcpy, mutex, NLM_F_MULTI, NLMSG_DONE, nlmsghdr::nlmsg_flags, nlmsghdr::nlmsg_len, nlmsghdr::nlmsg_seq, nlmsghdr::nlmsg_type, seq, condvar_t::signal, TRUE, and mutex_t::unlock.
Referenced by CALLBACK(), eap_radius_forward_from_ike(), eap_radius_forward_to_ike(), handle_events(), lookup_queue(), METHOD(), queue_messsage(), raise_events(), read_and_queue(), remove_queue(), and resolve_hosts().
 {
     struct nlmsghdr *hdr;
     entry_t *entry;
     uintptr_t seq;
     seq = (uintptr_t)buf->nlmsg_seq;
     this->mutex->lock(this->mutex);
     entry = this->entries->get(this->entries, (void*)seq);
     if (entry)
     {
         hdr = malloc(buf->nlmsg_len);
         memcpy(hdr, buf, buf->nlmsg_len);
         array_insert(entry->hdrs, ARRAY_TAIL, hdr);
         if (hdr->nlmsg_type == NLMSG_DONE || !(hdr->nlmsg_flags & NLM_F_MULTI))
         {
             entry->complete = TRUE;
             entry->condvar->signal(entry->condvar);
         }
     }
     else
     {
         DBG1(DBG_KNL, "received unknown netlink seq %u, ignored", seq);
     }
     this->mutex->unlock(this->mutex);
     return entry != NULL;
 }
static bool read_and_queue (private_netlink_socket_t * this, bool block) static
Read and queue response message, optionally blocking, returns TRUE on timeout
Definition at line 241 of file kernel_netlink_shared.c.
References FALSE, len, NLMSG_NEXT, NLMSG_OK, queue(), read_msg(), and TRUE.
Referenced by CALLBACK(), and send_once().
 {
     struct nlmsghdr *hdr;
     char buf[this->buflen];
     ssize_t len;
     len = read_msg(this, buf, sizeof(buf), block);
     if (len == -1)
     {
         return TRUE;
     }
     if (len)
     {
         hdr = (struct nlmsghdr*)buf;
         while (NLMSG_OK(hdr, len))
         {
             if (!queue(this, hdr))
             {
                 break;
             }
             hdr = NLMSG_NEXT(hdr, len);
         }
     }
     return FALSE;
 }
static ssize_t read_msg (private_netlink_socket_t * this, char * buf, size_t buflen, bool block) static
Read a single Netlink message from socket, return 0 on error, -1 on timeout
Definition at line 168 of file kernel_netlink_shared.c.
References DBG1, DBG_KNL, EWOULDBLOCK, len, MSG_DONTWAIT, recv, select, socket, strerror, and timeval_add_ms().
Referenced by read_and_queue().
 {
     ssize_t len;
     if (block)
     {
         fd_set set;
         timeval_t tv = {};
         FD_ZERO(&set);
         FD_SET(this->socket, &set);
         timeval_add_ms(&tv, this->timeout);
         if (select(this->socket + 1, &set, NULL, NULL,
                    this->timeout ? &tv : NULL) <= 0)
         {
             return -1;
         }
     }
     len = recv(this->socket, buf, buflen, MSG_TRUNC|(block ? 0 : MSG_DONTWAIT));
     if (len > buflen)
     {
         DBG1(DBG_KNL, "netlink response exceeds buffer size");
         return 0;
     }
     if (len < 0)
     {
         if (errno != EAGAIN && errno != EWOULDBLOCK && errno != EINTR)
         {
             DBG1(DBG_KNL, "netlink read error: %s", strerror(errno));
         }
         return 0;
     }
     return len;
 }
static status_t send_once (private_netlink_socket_t * this, struct nlmsghdr * in, uintptr_t seq, struct nlmsghdr ** out, size_t * out_len) static
Send a netlink request, try once
Definition at line 280 of file kernel_netlink_shared.c.
References array_create(), ARRAY_HEAD, array_remove(), chunk_cat, chunk_create(), entry_t::complete, entry_t::condvar, condvar, condvar_create(), CONDVAR_TYPE_DEFAULT, DBG3, DBG_KNL, destroy_entry(), FAILED, watcher_t::get_state, entry_t::hdrs, INIT, chunk_t::len, lib, mutex_t::lock, mutex, nlmsghdr::nlmsg_len, nlmsghdr::nlmsg_pid, nlmsghdr::nlmsg_seq, nlmsghdr::nlmsg_type, OUT_OF_RES, chunk_t::ptr, read_and_queue(), result, seq, SUCCESS, condvar_t::timed_wait, TRUE, mutex_t::unlock, condvar_t::wait, library_t::watcher, WATCHER_RUNNING, and write_msg().
Referenced by METHOD().
 {
     struct nlmsghdr *hdr;
     chunk_t result = {};
     entry_t *entry;
     in->nlmsg_seq = seq;
     in->nlmsg_pid = getpid();
     if (this->names)
     {
         DBG3(DBG_KNL, "sending %N %u: %b", this->names, in->nlmsg_type,
              (u_int)seq, in, in->nlmsg_len);
     }
     this->mutex->lock(this->mutex);
     if (!write_msg(this, in))
     {
         this->mutex->unlock(this->mutex);
         return FAILED;
     }
     INIT(entry,
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .hdrs = array_create(0, 0),
     );
     this->entries->put(this->entries, (void*)seq, entry);
     while (!entry->complete)
     {
         if (this->parallel &&
             lib->watcher->get_state(lib->watcher) == WATCHER_RUNNING)
         {
             if (this->timeout)
             {
                 if (entry->condvar->timed_wait(entry->condvar, this->mutex,
                                                this->timeout))
                 {
                     break;
                 }
             }
             else
             {
                 entry->condvar->wait(entry->condvar, this->mutex);
             }
         }
         else
         {   /* During (de-)initialization, no watcher thread is active.
              * collect responses ourselves. */
             if (read_and_queue(this, TRUE))
             {
                 break;
             }
         }
     }
     this->entries->remove(this->entries, (void*)seq);
     this->mutex->unlock(this->mutex);
     if (!entry->complete)
     {   /* timeout */
         destroy_entry(entry);
         return OUT_OF_RES;
     }
     while (array_remove(entry->hdrs, ARRAY_HEAD, &hdr))
     {
         if (this->names)
         {
             DBG3(DBG_KNL, "received %N %u: %b", this->names, hdr->nlmsg_type,
                  hdr->nlmsg_seq, hdr, hdr->nlmsg_len);
         }
         result = chunk_cat("mm", result,
                            chunk_create((char*)hdr, hdr->nlmsg_len));
     }
     destroy_entry(entry);
     *out_len = result.len;
     *out = (struct nlmsghdr*)result.ptr;
     return SUCCESS;
 }
static bool write_msg (private_netlink_socket_t * this, struct nlmsghdr * msg) static
Write a Netlink message to socket
Definition at line 136 of file kernel_netlink_shared.c.
References DBG1, DBG_KNL, FALSE, len, msg_loss_hook, sockaddr_nl::nl_family, nlmsghdr::nlmsg_len, sendto, socket, strerror, and TRUE.
Referenced by send_once().
 {
     struct sockaddr_nl addr = {
         .nl_family = AF_NETLINK,
     };
     int len;
     if (msg_loss_hook(msg))
     {
         return TRUE;
     }
     while (TRUE)
     {
         len = sendto(this->socket, msg, msg->nlmsg_len, 0,
                      (struct sockaddr*)&addr, sizeof(addr));
         if (len != msg->nlmsg_len)
         {
             if (errno == EINTR)
             {
                 continue;
             }
             DBG1(DBG_KNL, "netlink write error: %s", strerror(errno));
             return FALSE;
         }
         return TRUE;
     }
 }