strongSwan: certexpire_export
certexpire_export
certexpire
Classes
struct certexpire_export_t
Typedefs
typedef struct certexpire_export_t certexpire_export_t
Functions
certexpire_export_t * certexpire_export_create ()
Detailed Description
Typedef Documentation
typedef struct certexpire_export_t certexpire_export_t
Definition at line 24 of file certexpire_export.h.
Function Documentation
certexpire_export_t* certexpire_export_create ()
Create a certexpire_export instance.
See header
Definition at line 417 of file certexpire_export.c.
References certexpire_cron_create(), cron_export(), equals(), settings_t::get_bool, settings_t::get_str, hash(), hashtable_create(), INIT, lib, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, library_t::settings, and TRUE.
Referenced by certexpire_plugin_create().
 {
     private_certexpire_export_t *this;
     char *cron;
     INIT(this,
         .public = {
             .add = _add,
             .destroy = _destroy,
         },
         .local = hashtable_create((hashtable_hash_t)hash,
                                   (hashtable_equals_t)equals, 4),
         .remote = hashtable_create((hashtable_hash_t)hash,
                                    (hashtable_equals_t)equals, 32),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .local_path = lib->settings->get_str(lib->settings,
                                     "%s.plugins.certexpire.csv.local",
                                     NULL, lib->ns),
         .remote_path = lib->settings->get_str(lib->settings,
                                     "%s.plugins.certexpire.csv.remote",
                                     NULL, lib->ns),
         .separator = lib->settings->get_str(lib->settings,
                                     "%s.plugins.certexpire.csv.separator",
                                     ",", lib->ns),
         .format = lib->settings->get_str(lib->settings,
                                     "%s.plugins.certexpire.csv.format",
                                     "%d:%m:%Y", lib->ns),
         .fixed_fields = lib->settings->get_bool(lib->settings,
                                     "%s.plugins.certexpire.csv.fixed_fields",
                                     TRUE, lib->ns),
         .empty_string = lib->settings->get_str(lib->settings,
                                     "%s.plugins.certexpire.csv.empty_string",
                                     "", lib->ns),
         .force = lib->settings->get_bool(lib->settings,
                                     "%s.plugins.certexpire.csv.force",
                                     TRUE, lib->ns),
     );
     cron = lib->settings->get_str(lib->settings,
                                   "%s.plugins.certexpire.csv.cron",
                                   NULL, lib->ns);
     if (cron)
     {
         this->cron = certexpire_cron_create(cron,
                                     (certexpire_cron_job_t)cron_export, this);
     }
     return &this->public;
 }