strongSwan: imc_hcd.c File Reference
imc_hcd.c File Reference
#include "imc_hcd_state.h"
#include <imc/imc_agent.h>
#include <imc/imc_msg.h>
#include <imc/imc_os_info.h>
#include <generic/generic_attr_bool.h>
#include <generic/generic_attr_chunk.h>
#include <generic/generic_attr_string.h>
#include <ietf/ietf_attr.h>
#include <ietf/ietf_attr_attr_request.h>
#include "ietf/ietf_attr_fwd_enabled.h"
#include <pwg/pwg_attr.h>
#include <pwg/pwg_attr_vendor_smi_code.h>
#include <tncif_pa_subtypes.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct section_subtype_t
struct quadruple_t
Typedefs
typedef struct section_subtype_t section_subtype_t
typedef struct quadruple_t quadruple_t
Functions
TNC_Result TNC_IMC_API TNC_IMC_Initialize (TNC_IMCID imc_id, TNC_Version min_version, TNC_Version max_version, TNC_Version *actual_version)
TNC_Result TNC_IMC_API TNC_IMC_NotifyConnectionChange (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_ConnectionState new_state)
static void add_attrs_natural_lang (imc_msg_t *msg, char *section)
static void add_default_pwd_enabled (imc_msg_t *msg)
static void add_forwarding_enabled (imc_msg_t *msg)
static void add_machine_type_model (imc_msg_t *msg)
static void add_pstn_fax_enabled (imc_msg_t *msg)
static void add_time_source (imc_msg_t *msg)
static void add_user_app_enabled (imc_msg_t *msg)
static void add_user_app_persist_enabled (imc_msg_t *msg)
static void add_vendor_name (imc_msg_t *msg)
static void add_vendor_smi_code (imc_msg_t *msg)
static void add_certification_state (imc_msg_t *msg)
static void add_configuration_state (imc_msg_t *msg)
static void add_quadruple (imc_msg_t *msg, char *section, quadruple_t *quad)
TNC_Result TNC_IMC_API TNC_IMC_BeginHandshake (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
static TNC_Result receive_message (imc_state_t *state, imc_msg_t *in_msg)
TNC_Result TNC_IMC_API TNC_IMC_ReceiveMessage (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
TNC_Result TNC_IMC_API TNC_IMC_ReceiveMessageLong (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
TNC_Result TNC_IMC_API TNC_IMC_BatchEnding (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
TNC_Result TNC_IMC_API TNC_IMC_Terminate (TNC_IMCID imc_id)
TNC_Result TNC_IMC_API TNC_IMC_ProvideBindFunction (TNC_IMCID imc_id, TNC_TNCC_BindFunctionPointer bind_function)
Variables
static const char imc_name [] = "HCD"
static pen_type_t msg_types []
static imc_agent_t * imc_hcd
static imc_os_info_t * os
static section_subtype_t section_subtypes []
static quadruple_t quadruples []
Typedef Documentation
typedef struct quadruple_t quadruple_t
Definition at line 67 of file imc_hcd.c.
typedef struct section_subtype_t section_subtype_t
Definition at line 51 of file imc_hcd.c.
Function Documentation
static void add_attrs_natural_lang (imc_msg_t * msg, char * section) static
Add AttributesNaturalLanguage attribute to send queue
Definition at line 164 of file imc_hcd.c.
References imc_msg_t::add_attribute, chunk_from_str, DBG2, DBG_IMC, generic_attr_string_create(), settings_t::get_str, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_ATTRS_NATURAL_LANG, library_t::settings, and string.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     char *string;
     string = lib->settings->get_str(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.%s.attributes_natural_language",
                 "en", lib->ns, section);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_ATTRS_NATURAL_LANG,
                 string);
     attr = generic_attr_string_create(chunk_from_str(string),
                 pen_type_create(PEN_PWG, PWG_HCD_ATTRS_NATURAL_LANG));
     msg->add_attribute(msg, attr);
 }
static void add_certification_state (imc_msg_t * msg) static
Add CertificationState attribute to send queue
Definition at line 339 of file imc_hcd.c.
References imc_msg_t::add_attribute, blob, chunk_free(), chunk_from_hex(), chunk_from_str, DBG2, DBG_IMC, generic_attr_chunk_create(), settings_t::get_str, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_CERTIFICATION_STATE, and library_t::settings.
Referenced by receive_message().
 {
     pa_tnc_attr_t *attr;
     char *hex_string;
     chunk_t blob;
     hex_string = lib->settings->get_str(lib->settings,
                     "%s.plugins.imc-hcd.subtypes.system.certification_state",
                     NULL, lib->ns);
     if (hex_string)
     {
         blob = chunk_from_hex(chunk_from_str(hex_string), NULL);
         DBG2(DBG_IMC, "  %N: %B", pwg_attr_names, PWG_HCD_CERTIFICATION_STATE,
                     &blob);
         attr = generic_attr_chunk_create(blob,
                     pen_type_create(PEN_PWG, PWG_HCD_CERTIFICATION_STATE));
         msg->add_attribute(msg, attr);
         chunk_free(&blob);
     }
 }
static void add_configuration_state (imc_msg_t * msg) static
Add CertificationState attribute to send queue
Definition at line 364 of file imc_hcd.c.
References imc_msg_t::add_attribute, blob, chunk_free(), chunk_from_hex(), chunk_from_str, DBG2, DBG_IMC, generic_attr_chunk_create(), settings_t::get_str, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_CONFIGURATION_STATE, and library_t::settings.
Referenced by receive_message().
 {
     pa_tnc_attr_t *attr;
     char *hex_string;
     chunk_t blob;
     hex_string = lib->settings->get_str(lib->settings,
                     "%s.plugins.imc-hcd.subtypes.system.configuration_state",
                     NULL, lib->ns);
     if (hex_string)
     {
         blob = chunk_from_hex(chunk_from_str(hex_string), NULL);
         DBG2(DBG_IMC, "  %N: %B", pwg_attr_names, PWG_HCD_CONFIGURATION_STATE,
                     &blob);
         attr = generic_attr_chunk_create(blob,
                     pen_type_create(PEN_PWG, PWG_HCD_CONFIGURATION_STATE));
         msg->add_attribute(msg, attr);
         chunk_free(&blob);
     }
 }
static void add_default_pwd_enabled (imc_msg_t * msg) static
Add DefaultPasswordEnabled attribute to send queue
Definition at line 182 of file imc_hcd.c.
References imc_msg_t::add_attribute, DBG2, DBG_IMC, generic_attr_bool_create(), imc_os_info_t::get_default_pwd_status, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_DEFAULT_PWD_ENABLED, and status.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     bool status;
     status = os->get_default_pwd_status(os);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_DEFAULT_PWD_ENABLED,
                 status ? "yes" : "no");
     attr = generic_attr_bool_create(status,
                 pen_type_create(PEN_PWG, PWG_HCD_DEFAULT_PWD_ENABLED));
     msg->add_attribute(msg, attr);
 }
static void add_forwarding_enabled (imc_msg_t * msg) static
Add ForwardingEnabled attribute to send queue
Definition at line 198 of file imc_hcd.c.
References imc_msg_t::add_attribute, DBG2, DBG_IMC, imc_os_info_t::get_fwd_status, ietf_attr_fwd_enabled_create(), os_fwd_status_names, PEN_PWG, pen_type_create(), pwg_attr_names, and PWG_HCD_FORWARDING_ENABLED.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     os_fwd_status_t fwd_status;
     fwd_status = os->get_fwd_status(os);
     DBG2(DBG_IMC, "  %N: %N", pwg_attr_names, PWG_HCD_FORWARDING_ENABLED,
                 os_fwd_status_names, fwd_status);
     attr = ietf_attr_fwd_enabled_create(fwd_status,
                 pen_type_create(PEN_PWG, PWG_HCD_FORWARDING_ENABLED));
     msg->add_attribute(msg, attr);
 }
static void add_machine_type_model (imc_msg_t * msg) static
Add MachineTypeModel attribute to send queue
Definition at line 214 of file imc_hcd.c.
References imc_msg_t::add_attribute, chunk_from_str, DBG2, DBG_IMC, generic_attr_string_create(), settings_t::get_str, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_MACHINE_TYPE_MODEL, library_t::settings, and string.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     char *string;
     string = lib->settings->get_str(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.system.machine_type_model",
                 "", lib->ns);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_MACHINE_TYPE_MODEL,
                 string);
     attr = generic_attr_string_create(chunk_from_str(string),
                 pen_type_create(PEN_PWG, PWG_HCD_MACHINE_TYPE_MODEL));
     msg->add_attribute(msg, attr);
 }
static void add_pstn_fax_enabled (imc_msg_t * msg) static
Add PSTNFaxEnabled attribute to send queue
Definition at line 232 of file imc_hcd.c.
References imc_msg_t::add_attribute, DBG2, DBG_IMC, FALSE, generic_attr_bool_create(), settings_t::get_bool, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_PSTN_FAX_ENABLED, library_t::settings, and status.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     bool status;
     status = lib->settings->get_bool(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.system.pstn_fax_enabled",
                 FALSE, lib->ns);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_PSTN_FAX_ENABLED,
                 status ? "yes" : "no");
     attr = generic_attr_bool_create(status,
                 pen_type_create(PEN_PWG, PWG_HCD_PSTN_FAX_ENABLED));
     msg->add_attribute(msg, attr);
 }
static void add_quadruple (imc_msg_t * msg, char * section, quadruple_t * quad) static
Add Correlated Attributes to send queue
Definition at line 389 of file imc_hcd.c.
References imc_msg_t::add_attribute, chunk_from_hex(), chunk_from_str, settings_t::create_section_enumerator, DBG2, DBG_IMC, enumerator_t::destroy, enumerator_t::enumerate, generic_attr_chunk_create(), generic_attr_string_create(), settings_t::get_str, len, lib, name, quadruple_t::name_attr, library_t::ns, quadruple_t::patches_attr, PEN_PWG, pen_type_create(), pwg_attr_names, quadruple_t::section, library_t::settings, quadruple_t::string_version_attr, version, and quadruple_t::version_attr.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     const size_t version_len = 16;
     char version[version_len];
     char hex_version_default[] = "00000000000000000000000000000000";
     char *app, *name, *patches, *string_version, *hex_version;
     size_t len;
     chunk_t num_version;
     enumerator_t *enumerator;
     enumerator = lib->settings->create_section_enumerator(lib->settings,
                     "%s.plugins.imc-hcd.subtypes.%s.%s",
                     lib->ns, section, quad->section);
     while (enumerator->enumerate(enumerator, &app))
     {
         name = lib->settings->get_str(lib->settings,
                     "%s.plugins.imc-hcd.subtypes.%s.%s.%s.name",
                     "", lib->ns, section, quad->section, app);
         patches = lib->settings->get_str(lib->settings,
                     "%s.plugins.imc-hcd.subtypes.%s.%s.%s.patches",
                     "", lib->ns, section, quad->section, app);
         string_version = lib->settings->get_str(lib->settings,
                     "%s.plugins.imc-hcd.subtypes.%s.%s.%s.string_version",
                     "", lib->ns, section, quad->section, app);
         hex_version = lib->settings->get_str(lib->settings,
                     "%s.plugins.imc-hcd.subtypes.%s.%s.%s.version",
                     hex_version_default, lib->ns, section, quad->section, app);
         /* convert hex string into binary chunk */
         if (strlen(hex_version) > 2 * version_len)
         {
             hex_version = hex_version_default;
         }
         num_version = chunk_from_hex(chunk_from_str(hex_version), version);
         DBG2(DBG_IMC, "--- %s ---", app);
         DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, quad->name_attr, name);
         attr = generic_attr_string_create(chunk_from_str(name),
                         pen_type_create(PEN_PWG, quad->name_attr));
         msg->add_attribute(msg, attr);
         /* remove any trailing LF from patches string for logging */
         len = strlen(patches);
         if (len && (patches[len - 1] == '\n'))
         {
             len--;
         }
         DBG2(DBG_IMC, "  %N:%s%.*s", pwg_attr_names, quad->patches_attr,
                         len ? "\n" : " ", len, patches);
         attr = generic_attr_string_create(chunk_from_str(patches),
                         pen_type_create(PEN_PWG, quad->patches_attr));
         msg->add_attribute(msg, attr);
         DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, quad->string_version_attr,
                         string_version);
         attr = generic_attr_string_create(chunk_from_str(string_version),
                         pen_type_create(PEN_PWG, quad->string_version_attr));
         msg->add_attribute(msg, attr);
         DBG2(DBG_IMC, "  %N: %#B", pwg_attr_names, quad->version_attr, &num_version);
         attr = generic_attr_chunk_create(num_version,
                         pen_type_create(PEN_PWG, quad->version_attr));
         msg->add_attribute(msg, attr);
     }
     enumerator->destroy(enumerator);
 }
static void add_time_source (imc_msg_t * msg) static
Add TimeSource attribute to send queue
Definition at line 250 of file imc_hcd.c.
References imc_msg_t::add_attribute, chunk_from_str, DBG2, DBG_IMC, generic_attr_string_create(), settings_t::get_str, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_TIME_SOURCE, library_t::settings, and string.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     char *string;
     string = lib->settings->get_str(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.system.time_source",
                 "", lib->ns);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_TIME_SOURCE,
                 string);
     attr = generic_attr_string_create(chunk_from_str(string),
                 pen_type_create(PEN_PWG, PWG_HCD_TIME_SOURCE));
     msg->add_attribute(msg, attr);
 }
static void add_user_app_enabled (imc_msg_t * msg) static
Add UserApplicationEnabled attribute to send queue
Definition at line 268 of file imc_hcd.c.
References imc_msg_t::add_attribute, DBG2, DBG_IMC, FALSE, generic_attr_bool_create(), settings_t::get_bool, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_USER_APP_ENABLED, library_t::settings, and status.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     bool status;
     status = lib->settings->get_bool(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.system.user_application_enabled",
                 FALSE, lib->ns);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_USER_APP_ENABLED,
                 status ? "yes" : "no");
     attr = generic_attr_bool_create(status,
                 pen_type_create(PEN_PWG, PWG_HCD_USER_APP_ENABLED));
     msg->add_attribute(msg, attr);
 }
static void add_user_app_persist_enabled (imc_msg_t * msg) static
Add UserApplicationPersistenceEnabled attribute to send queue
Definition at line 286 of file imc_hcd.c.
References imc_msg_t::add_attribute, DBG2, DBG_IMC, FALSE, generic_attr_bool_create(), settings_t::get_bool, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_USER_APP_PERSIST_ENABLED, library_t::settings, and status.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     bool status;
     status = lib->settings->get_bool(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.system.user_application_persistence.enabled",
                 FALSE, lib->ns);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_USER_APP_PERSIST_ENABLED,
                 status ? "yes" : "no");
     attr = generic_attr_bool_create(status,
                 pen_type_create(PEN_PWG, PWG_HCD_USER_APP_PERSIST_ENABLED));
     msg->add_attribute(msg, attr);
 }
static void add_vendor_name (imc_msg_t * msg) static
Add VendorName attribute to send queue
Definition at line 304 of file imc_hcd.c.
References imc_msg_t::add_attribute, chunk_from_str, DBG2, DBG_IMC, generic_attr_string_create(), settings_t::get_str, lib, library_t::ns, PEN_PWG, pen_type_create(), pwg_attr_names, PWG_HCD_VENDOR_NAME, library_t::settings, and string.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     char *string;
     string = lib->settings->get_str(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.system.vendor_name",
                 "", lib->ns);
     DBG2(DBG_IMC, "  %N: %s", pwg_attr_names, PWG_HCD_VENDOR_NAME,
                 string);
     attr = generic_attr_string_create(chunk_from_str(string),
                 pen_type_create(PEN_PWG, PWG_HCD_VENDOR_NAME));
     msg->add_attribute(msg, attr);
 }
static void add_vendor_smi_code (imc_msg_t * msg) static
Add VendorSMICode attribute to send queue
Definition at line 322 of file imc_hcd.c.
References imc_msg_t::add_attribute, DBG2, DBG_IMC, settings_t::get_int, lib, library_t::ns, pwg_attr_names, pwg_attr_vendor_smi_code_create(), PWG_HCD_VENDOR_SMI_CODE, and library_t::settings.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     int smi_code;
     smi_code = lib->settings->get_int(lib->settings,
                 "%s.plugins.imc-hcd.subtypes.system.vendor_smi_code",
                 0, lib->ns);
     DBG2(DBG_IMC, "  %N: 0x%06x (%d)", pwg_attr_names, PWG_HCD_VENDOR_SMI_CODE,
                 smi_code, smi_code);
     attr = pwg_attr_vendor_smi_code_create(smi_code);
     msg->add_attribute(msg, attr);
 }
static TNC_Result receive_message (imc_state_t * state, imc_msg_t * in_msg) static
Definition at line 544 of file imc_hcd.c.
References add_attrs_natural_lang(), add_certification_state(), add_configuration_state(), add_default_pwd_enabled(), add_forwarding_enabled(), add_machine_type_model(), add_pstn_fax_enabled(), add_quadruple(), add_time_source(), add_user_app_enabled(), add_user_app_persist_enabled(), add_vendor_name(), add_vendor_smi_code(), countof, imc_msg_t::create_attribute_enumerator, ietf_attr_attr_request_t::create_enumerator, enumerator_t::destroy, imc_msg_t::destroy, enumerator_t::enumerate, FALSE, settings_t::get_bool, imc_msg_t::get_msg_type, pa_tnc_attr_t::get_type, IETF_ATTR_ATTRIBUTE_REQUEST, imc_msg_create_as_reply(), lib, library_t::ns, PEN_IETF, PEN_PWG, PWG_HCD_ATTRS_NATURAL_LANG, PWG_HCD_CERTIFICATION_STATE, PWG_HCD_CONFIGURATION_STATE, PWG_HCD_DEFAULT_PWD_ENABLED, PWG_HCD_FIRMWARE_NAME, PWG_HCD_FORWARDING_ENABLED, PWG_HCD_MACHINE_TYPE_MODEL, PWG_HCD_PSTN_FAX_ENABLED, PWG_HCD_RESIDENT_APP_NAME, PWG_HCD_TIME_SOURCE, PWG_HCD_USER_APP_ENABLED, PWG_HCD_USER_APP_NAME, PWG_HCD_USER_APP_PERSIST_ENABLED, PWG_HCD_VENDOR_NAME, PWG_HCD_VENDOR_SMI_CODE, imc_msg_t::receive, result, section_subtype_t::section, section, imc_msg_t::send, library_t::settings, section_subtype_t::subtype, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, TRUE, type, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by TNC_IMC_ReceiveMessage(), and TNC_IMC_ReceiveMessageLong().
 {
     imc_msg_t *out_msg;
     enumerator_t *enumerator;
     pa_tnc_attr_t *attr;
     pen_type_t type, msg_type;
     TNC_Result result;
     char *section = NULL;
     int i;
     bool fatal_error = FALSE, pushed_info;
     /* generate an outgoing PA-TNC message - we might need it */
     out_msg = imc_msg_create_as_reply(in_msg);
     /* parse received PA-TNC message and handle local and remote errors */
     result = in_msg->receive(in_msg, out_msg, &fatal_error);
     if (result != TNC_RESULT_SUCCESS)
     {
         out_msg->destroy(out_msg);
         return result;
     }
     msg_type = in_msg->get_msg_type(in_msg);
     for (i = 0; i < countof(section_subtypes); i++)
     {
         if (msg_type.type == section_subtypes[i].subtype)
         {
             section = section_subtypes[i].section;
             break;
         }
     }
     pushed_info = lib->settings->get_bool(lib->settings,
                         "%s.plugins.imc-hcd.push_info", FALSE, lib->ns);
     /* analyze PA-TNC attributes */
     enumerator = in_msg->create_attribute_enumerator(in_msg);
     while (enumerator->enumerate(enumerator, &attr))
     {
         type = attr->get_type(attr);
         if (type.vendor_id == PEN_IETF)
         {
             if (type.type == IETF_ATTR_ATTRIBUTE_REQUEST)
             {
                 ietf_attr_attr_request_t *attr_cast;
                 pen_type_t *entry;
                 enumerator_t *e;
                 attr_cast = (ietf_attr_attr_request_t*)attr;
                 e = attr_cast->create_enumerator(attr_cast);
                 while (e->enumerate(e, &entry))
                 {
                     if (entry->vendor_id == PEN_PWG)
                     {
                         switch (entry->type)
{
                             case PWG_HCD_ATTRS_NATURAL_LANG:
                                 add_attrs_natural_lang(out_msg, section);
                                 break;
                             case PWG_HCD_DEFAULT_PWD_ENABLED:
                                 add_default_pwd_enabled(out_msg);
                                 break;
                             case PWG_HCD_FORWARDING_ENABLED:
                                 add_forwarding_enabled(out_msg);
                                 break;
                             case PWG_HCD_MACHINE_TYPE_MODEL:
                                 add_machine_type_model(out_msg);
                                 break;
                             case PWG_HCD_PSTN_FAX_ENABLED:
                                 add_pstn_fax_enabled(out_msg);
                                 break;
                             case PWG_HCD_TIME_SOURCE:
                                 add_time_source(out_msg);
                                 break;
                             case PWG_HCD_USER_APP_ENABLED:
                                 add_user_app_enabled(out_msg);
                                 break;
                             case PWG_HCD_USER_APP_PERSIST_ENABLED:
                                 add_user_app_persist_enabled(out_msg);
                                 break;
                             case PWG_HCD_VENDOR_NAME:
                                 add_vendor_name(out_msg);
                                 break;
                             case PWG_HCD_VENDOR_SMI_CODE:
                                 add_vendor_smi_code(out_msg);
                                 break;
                             case PWG_HCD_CERTIFICATION_STATE:
                                 add_certification_state(out_msg);
                                 break;
                             case PWG_HCD_CONFIGURATION_STATE:
                                 add_configuration_state(out_msg);
                                 break;
                             default:
                                 if (pushed_info)
{
                                     continue;
                                 }
                         }
                         /* if not pushed, deliver on request */
                         switch (entry->type)
{
                             case PWG_HCD_FIRMWARE_NAME:
                                 add_quadruple(out_msg, section, &quadruples[0]);
                                 break;
                             case PWG_HCD_RESIDENT_APP_NAME:
                                 add_quadruple(out_msg, section, &quadruples[1]);
                                 break;
                             case PWG_HCD_USER_APP_NAME:
                                 add_quadruple(out_msg, section, &quadruples[2]);
                                 break;
                             default:
                                 break;
                         }
                     }
                 }
                 e->destroy(e);
             }
         }
     }
     enumerator->destroy(enumerator);
     if (fatal_error)
     {
         result = TNC_RESULT_FATAL;
     }
     else
     {
         /* send PA-TNC message with the EXCL flag set */
         result = out_msg->send(out_msg, TRUE);
     }
     out_msg->destroy(out_msg);
     return result;
 }
Variable Documentation
imc_agent_t* imc_hcd static
Definition at line 48 of file imc_hcd.c.
const char imc_name[] = "HCD" static
Definition at line 37 of file imc_hcd.c.
Referenced by TNC_IMC_BatchEnding(), TNC_IMC_BeginHandshake(), TNC_IMC_Initialize(), TNC_IMC_NotifyConnectionChange(), TNC_IMC_ProvideBindFunction(), TNC_IMC_ReceiveMessage(), TNC_IMC_ReceiveMessageLong(), and TNC_IMC_Terminate().
pen_type_t msg_types[] static
Initial value:
= {
    { PEN_PWG, PA_SUBTYPE_PWG_HCD_SYSTEM },
    { PEN_PWG, PA_SUBTYPE_PWG_HCD_CONSOLE },
    { PEN_PWG, PA_SUBTYPE_PWG_HCD_MARKER },
    { PEN_PWG, PA_SUBTYPE_PWG_HCD_FINISHER },
    { PEN_PWG, PA_SUBTYPE_PWG_HCD_INTERFACE },
    { PEN_PWG, PA_SUBTYPE_PWG_HCD_SCANNER }
}
Definition at line 39 of file imc_hcd.c.
imc_os_info_t* os static
Definition at line 49 of file imc_hcd.c.
quadruple_t quadruples[] static
Initial value:
= {
    { "firmware",
       PWG_HCD_FIRMWARE_NAME, PWG_HCD_FIRMWARE_PATCHES,
       PWG_HCD_FIRMWARE_STRING_VERSION, PWG_HCD_FIRMWARE_VERSION },
    { "resident_application",
       PWG_HCD_RESIDENT_APP_NAME, PWG_HCD_RESIDENT_APP_PATCHES,
       PWG_HCD_RESIDENT_APP_STRING_VERSION, PWG_HCD_RESIDENT_APP_VERSION },
    { "user_application",
       PWG_HCD_USER_APP_NAME, PWG_HCD_USER_APP_PATCHES,
       PWG_HCD_USER_APP_STRING_VERSION, PWG_HCD_USER_APP_VERSION }
}
Definition at line 77 of file imc_hcd.c.
section_subtype_t section_subtypes[] static
Initial value:
= {
    { "system",    PA_SUBTYPE_PWG_HCD_SYSTEM    },
    { "console",   PA_SUBTYPE_PWG_HCD_CONSOLE   },
    { "marker",    PA_SUBTYPE_PWG_HCD_MARKER    },
    { "finisher",  PA_SUBTYPE_PWG_HCD_FINISHER  },
    { "interface", PA_SUBTYPE_PWG_HCD_INTERFACE },
    { "scanner"  , PA_SUBTYPE_PWG_HCD_SCANNER   }
}
Definition at line 58 of file imc_hcd.c.