strongSwan: listener_t Struct Reference
listener_t Struct Reference
listener
#include "listener.h"
Public Attributes
bool(* alert)(listener_t *this, ike_sa_t *ike_sa, alert_t alert, va_list args)
bool(* ike_state_change)(listener_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
bool(* child_state_change)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, child_sa_state_t state)
bool(* message)(listener_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
bool(* ike_keys)(listener_t *this, ike_sa_t *ike_sa, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_t *rekey, shared_key_t *shared)
bool(* child_keys)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool initiator, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r)
bool(* ike_updown)(listener_t *this, ike_sa_t *ike_sa, bool up)
bool(* ike_rekey)(listener_t *this, ike_sa_t *old, ike_sa_t *new)
bool(* ike_update)(listener_t *this, ike_sa_t *ike_sa, bool local, host_t *new)
bool(* ike_reestablish_pre)(listener_t *this, ike_sa_t *old, ike_sa_t *new)
bool(* ike_reestablish_post)(listener_t *this, ike_sa_t *old, ike_sa_t *new, bool initiated)
bool(* child_updown)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool up)
bool(* child_rekey)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *old, child_sa_t *new)
bool(* children_migrate)(listener_t *this, ike_sa_t *ike_sa, ike_sa_id_t *new, u_int32_t unique)
bool(* authorize)(listener_t *this, ike_sa_t *ike_sa, bool final, bool *success)
bool(* narrow)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, narrow_hook_t type, linked_list_t *local, linked_list_t *remote)
bool(* assign_vips)(listener_t *this, ike_sa_t *ike_sa, bool assign)
bool(* handle_vips)(listener_t *this, ike_sa_t *ike_sa, bool handle)
Detailed Description
Listener interface, listens to events if registered to the bus.
Definition at line 32 of file listener.h.
Member Data Documentation
bool(* listener_t::alert)(listener_t *this, ike_sa_t *ike_sa, alert_t alert, va_list args)
Hook called if a critical alert is raised.
Parameters
ike_sa IKE_SA associated to the alert, if any
alert kind of alert
... alert specific argument list
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 42 of file listener.h.
Referenced by METHOD().
bool(* listener_t::assign_vips)(listener_t *this, ike_sa_t *ike_sa, bool assign)
Virtual IP address assignment hook.
This hook gets invoked after virtual IPs have been assigned to a peer for a specific IKE_SA, and again before they get released.
Parameters
ike_sa IKE_SA the VIPs are assigned to
assign TRUE if assigned to IKE_SA, FALSE if released
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 246 of file listener.h.
Referenced by METHOD().
bool(* listener_t::authorize)(listener_t *this, ike_sa_t *ike_sa, bool final, bool *success)
Hook called to invoke additional authorization rules.
An authorization hook gets invoked several times: After each authentication round, the hook gets invoked with with final = FALSE. After authentication is complete and the peer configuration is selected, it is invoked again, but with final = TRUE.
Parameters
ike_sa IKE_SA to authorize
final TRUE if this is the final hook invocation
success set to TRUE to complete IKE_SA, FALSE abort
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 218 of file listener.h.
Referenced by METHOD().
bool(* listener_t::child_keys)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool initiator, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r)
Hook called with CHILD_SA key material.
Parameters
ike_sa IKE_SA the child sa belongs to
child_sa CHILD_SA this keymat is used for
initiator initiator of the CREATE_CHILD_SA exchange
dh diffie hellman shared secret
nonce_i initiators nonce
nonce_r responders nonce
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 108 of file listener.h.
Referenced by METHOD().
bool(* listener_t::child_rekey)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *old, child_sa_t *new)
Hook called when an CHILD_SA gets rekeyed.
Parameters
ike_sa IKE_SA containing the rekeyed CHILD_SA
old rekeyed CHILD_SA getting obsolete
new new CHILD_SA replacing old
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 187 of file listener.h.
Referenced by METHOD().
bool(* listener_t::child_state_change)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, child_sa_state_t state)
Handle state changes in a CHILD_SA.
Parameters
ike_sa IKE_SA containing the affected CHILD_SA
child_sa CHILD_SA which changes its state
state new CHILD_SA state this CHILD_SA changes to
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 63 of file listener.h.
Referenced by connect_(), and METHOD().
bool(* listener_t::child_updown)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool up)
Hook called when a CHILD_SA gets up or down.
Parameters
ike_sa IKE_SA containing the handled CHILD_SA
child_sa CHILD_SA coming up/going down
up TRUE for an up event, FALSE for a down event
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 176 of file listener.h.
Referenced by METHOD(), and nm_strongswan_plugin_init().
bool(* listener_t::children_migrate)(listener_t *this, ike_sa_t *ike_sa, ike_sa_id_t *new, u_int32_t unique)
Hook called when CHILD_SAs get migrated from one IKE_SA to another during IKEv1 reauthentication.
This is called twice, once for the old IKE_SA before the CHILD_SAs are removed, and once for the new IKE_SA just after they got added.
Parameters
ike_sa new or old IKE_SA
new ID of new SA when called for the old, NULL otherwise
unique unique ID of new SA when called for the old, 0 otherwise
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 202 of file listener.h.
Referenced by METHOD().
bool(* listener_t::handle_vips)(listener_t *this, ike_sa_t *ike_sa, bool handle)
Virtual IP and configuration attribute handler hook.
This hook gets invoked after virtual IP and other configuration attributes just got installed or are about to get uninstalled on a peer receiving them.
Parameters
ike_sa IKE_SA the VIPs/attributes are handled on
handle TRUE if handled by IKE_SA, FALSE on release
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 259 of file listener.h.
Referenced by METHOD().
bool(* listener_t::ike_keys)(listener_t *this, ike_sa_t *ike_sa, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_t *rekey, shared_key_t *shared)
Hook called with IKE_SA key material.
Parameters
ike_sa IKE_SA this keymat belongs to
dh diffie hellman shared secret
dh_other others DH public value (IKEv1 only)
nonce_i initiators nonce
nonce_r responders nonce
rekey IKE_SA we are rekeying, if any (IKEv2 only)
shared shared key used for key derivation (IKEv1-PSK only)
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 93 of file listener.h.
Referenced by METHOD().
bool(* listener_t::ike_reestablish_post)(listener_t *this, ike_sa_t *old, ike_sa_t *new, bool initiated)
Hook called when an initiator reestablishes an IKE_SA.
This is invoked right before the new IKE_SA is checked in after initiating it. It is not invoked on the responder.
Parameters
old IKE_SA getting reestablished (is destroyed)
new new IKE_SA replacing old (gets established)
initiated TRUE if initiation was successful, FALSE otherwise
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 165 of file listener.h.
Referenced by METHOD().
bool(* listener_t::ike_reestablish_pre)(listener_t *this, ike_sa_t *old, ike_sa_t *new)
Hook called when an initiator reestablishes an IKE_SA.
This is invoked right after creating the new IKE_SA and setting the peer_cfg (and the old hosts), but before resolving the hosts anew. It is not invoked on the responder.
Parameters
old IKE_SA getting reestablished (is destroyed)
new new IKE_SA replacing old (gets established)
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 152 of file listener.h.
Referenced by METHOD().
bool(* listener_t::ike_rekey)(listener_t *this, ike_sa_t *old, ike_sa_t *new)
Hook called when an IKE_SA gets rekeyed.
Parameters
old rekeyed IKE_SA getting obsolete
new new IKE_SA replacing old
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 128 of file listener.h.
Referenced by METHOD(), and nm_strongswan_plugin_init().
bool(* listener_t::ike_state_change)(listener_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
Handle state changes in an IKE_SA.
Parameters
ike_sa IKE_SA which changes its state
state new IKE_SA state this IKE_SA changes to
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 52 of file listener.h.
Referenced by child_updown(), connect_(), and METHOD().
bool(* listener_t::ike_update)(listener_t *this, ike_sa_t *ike_sa, bool local, host_t *new)
Hook called for IKE_SA peer endpoint updates.
Parameters
ike_sa updated IKE_SA, having old endpoints set
local TRUE if local endpoint gets updated, FALSE for remote
new new endpoint address and port
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 138 of file listener.h.
Referenced by METHOD().
bool(* listener_t::ike_updown)(listener_t *this, ike_sa_t *ike_sa, bool up)
Hook called if an IKE_SA gets up or down.
Parameters
ike_sa IKE_SA coming up/going down
up TRUE for an up event, FALSE for a down event
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 119 of file listener.h.
Referenced by METHOD().
bool(* listener_t::message)(listener_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
Hook called for received/sent messages of an IKE_SA.
The hook is invoked twice for each message: Once with plain, parsed data and once encoded and encrypted.
Parameters
ike_sa IKE_SA sending/receiving a message
message message object
incoming TRUE for incoming messages, FALSE for outgoing
plain TRUE if message is parsed and decrypted, FALSE it not
Returns
TRUE to stay registered, FALSE to unregister
Definition at line 78 of file listener.h.
Referenced by METHOD().
bool(* listener_t::narrow)(listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, narrow_hook_t type, linked_list_t *local, linked_list_t *remote)
CHILD_SA traffic selector narrowing hook.
This hook is invoked for each CHILD_SA and allows plugins to modify the traffic selector list negotiated for this CHILD_SA.
Parameters
ike_sa IKE_SA the created CHILD_SA is created in
child_sa CHILD_SA set up with these traffic selectors
type type of hook getting invoked
local list of local traffic selectors to narrow
remote list of remote traffic selectors to narrow
Definition at line 233 of file listener.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
listener.h