strongSwan: mutex
mutex
threading
Classes
struct mutex_t
Typedefs
typedef struct mutex_t mutex_t
typedef enum mutex_type_t mutex_type_t
Enumerations
enum mutex_type_t { MUTEX_TYPE_DEFAULT = 0, MUTEX_TYPE_RECURSIVE = 1 }
Functions
mutex_t * mutex_create (mutex_type_t type)
Detailed Description
Typedef Documentation
typedef struct mutex_t mutex_t
Definition at line 25 of file mutex.h.
typedef enum mutex_type_t mutex_type_t
Definition at line 26 of file mutex.h.
Enumeration Type Documentation
enum mutex_type_t
Type of mutex.
Enumerator
MUTEX_TYPE_DEFAULT
default mutex
MUTEX_TYPE_RECURSIVE
allow recursive locking of the mutex
Definition at line 31 of file mutex.h.
                   {
     MUTEX_TYPE_DEFAULT  = 0,
     MUTEX_TYPE_RECURSIVE    = 1,
 };
Function Documentation
mutex_t* mutex_create (mutex_type_t type)
Create a mutex instance.
Parameters
type type of mutex to create
Returns
unlocked mutex instance
Definition at line 172 of file mutex.c.
References INIT, mutex, MUTEX_TYPE_DEFAULT, MUTEX_TYPE_RECURSIVE, profiler_init, and TRUE.
Referenced by android_log_logger_create(), barrier_create(), blocking_queue_create(), bus_create(), cancellation_cond(), capabilities_create(), certexpire_export_create(), child_sa_manager_create(), connect_manager_create(), coupling_validator_create(), create_function(), create_generic(), CreateMutex(), credential_manager_create(), daemon_create(), database_factory_create(), dhcp_provider_create(), dhcp_socket_create(), duplicheck_listener_create(), duplicheck_notify_create(), eap_radius_accounting_create(), eap_radius_forward_create(), eap_radius_provider_create(), eap_sim_file_triplets_create(), error_notify_socket_create(), fast_dispatcher_create(), file_logger_create(), ha_attribute_create(), ha_cache_create(), ha_segments_create(), host_resolver_create(), ike_sa_manager_create(), imv_session_manager_create(), ipsec_sa_mgr_create(), kernel_interface_create(), kernel_iph_net_create(), kernel_libipsec_ipsec_create(), kernel_netlink_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), kernel_wfp_ipsec_create(), led_listener_create(), load_tester_config_create(), load_tester_plugin_create(), lookip_socket_create(), mediation_manager_create(), mysql_database_create(), netlink_socket_create(), on_accept(), peer_cfg_create(), pkcs11_hasher_create(), pkcs11_plugin_create(), processor_create(), radius_config_create(), receiver_create(), resolve_handler_create(), rwlock_condvar_create(), rwlock_create(), scheduler_create(), semaphore_create(), sender_create(), spinlock_create(), sqlite_database_create(), START_TEST(), stream_service_create_from_fd(), stroke_config_create(), sys_logger_create(), thread_create_internal(), threading_init(), threads_init(), tkm_kernel_sad_create(), tnc_imc_create_empty(), tnc_imc_manager_create(), tnc_imv_create_empty(), tnc_imv_manager_create(), tnccs_11_create(), tnccs_20_client_create(), tnccs_20_server_create(), trap_manager_create(), unity_handler_create(), vici_connect(), vici_dispatcher_create(), vici_logger_create(), vici_socket_create(), and watcher_create().
 {
     switch (type)
     {
         case MUTEX_TYPE_RECURSIVE:
         {
             private_r_mutex_t *this;
             INIT(this,
                 .generic = {
                     .public = {
                         .lock = _lock_r,
                         .unlock = _unlock_r,
                         .destroy = _mutex_destroy_r,
                     },
                     .recursive = TRUE,
                 },
             );
             pthread_mutex_init(&this->generic.mutex, NULL);
             profiler_init(&this->generic.profile);
             return &this->generic.public;
         }
         case MUTEX_TYPE_DEFAULT:
         default:
         {
             private_mutex_t *this;
             INIT(this,
                 .public = {
                     .lock = _lock,
                     .unlock = _unlock,
                     .destroy = _mutex_destroy,
                 },
             );
             pthread_mutex_init(&this->mutex, NULL);
             profiler_init(&this->profile);
             return &this->public;
         }
     }
 }