strongSwan: fast_request.c File Reference
fast_request.c File Reference
#include "fast_request.h"
#include <library.h>
#include <utils/debug.h>
#include <stdlib.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <ClearSilver/ClearSilver.h>
#include <threading/thread.h>
#include <threading/thread_value.h>
Classes
struct private_fast_request_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_fast_request_t private_fast_request_t
Functions
static int read_cb (void *null, char *buf, int size)
static int writef_cb (void *null, const char *format, va_list args)
static int write_cb (void *null, const char *buf, int size)
static char * getenv_cb (void *null, const char *key)
static int putenv_cb (void *null, const char *key, const char *value)
static int iterenv_cb (void *null, int num, char **key, char **value)
METHOD (fast_request_t, get_cookie, char *, private_fast_request_t *this, char *name)
METHOD (fast_request_t, get_path, char *, private_fast_request_t *this)
METHOD (fast_request_t, get_host, char *, private_fast_request_t *this)
METHOD (fast_request_t, get_user_agent, char *, private_fast_request_t *this)
METHOD (fast_request_t, get_query_data, char *, private_fast_request_t *this, char *name)
METHOD (fast_request_t, get_env_var, char *, private_fast_request_t *this, char *name)
METHOD (fast_request_t, read_data, int, private_fast_request_t *this, char *buf, int len)
METHOD (fast_request_t, get_base, char *, private_fast_request_t *this)
METHOD (fast_request_t, add_cookie, void, private_fast_request_t *this, char *name, char *value)
METHOD (fast_request_t, redirect, void, private_fast_request_t *this, char *fmt,...)
METHOD (fast_request_t, get_referer, char *, private_fast_request_t *this)
METHOD (fast_request_t, to_referer, void, private_fast_request_t *this)
METHOD (fast_request_t, session_closed, bool, private_fast_request_t *this)
METHOD (fast_request_t, close_session, void, private_fast_request_t *this)
METHOD (fast_request_t, serve, void, private_fast_request_t *this, char *headers, chunk_t chunk)
METHOD (fast_request_t, sendfile, bool, private_fast_request_t *this, char *path, char *mime)
METHOD (fast_request_t, render, void, private_fast_request_t *this, char *template)
METHOD (fast_request_t, streamf, int, private_fast_request_t *this, char *format,...)
METHOD (fast_request_t, set, void, private_fast_request_t *this, char *key, char *value)
METHOD (fast_request_t, setf, void, private_fast_request_t *this, char *format,...)
METHOD (fast_request_t, get_ref, fast_request_t *, private_fast_request_t *this)
METHOD (fast_request_t, destroy, void, private_fast_request_t *this)
static void init (void)
fast_request_t * fast_request_create (int fd, bool debug)
Variables
static thread_value_t * thread_this
pthread_once_t once = PTHREAD_ONCE_INIT
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file fast_request.c.
Typedef Documentation
typedef struct private_fast_request_t private_fast_request_t
Definition at line 34 of file fast_request.c.
Function Documentation
static char* getenv_cb (void * null, const char * key) static
fcgiwrap getenv callback
Definition at line 127 of file fast_request.c.
References thread_value_t::get, req(), strdupnull(), and value.
Referenced by init().
 {
     char *value;
     private_fast_request_t *this;
     this = (private_fast_request_t*)thread_this->get(thread_this);
     value = FCGX_GetParam(key, this->req.envp);
     return strdupnull(value);
 }
static void init (void) static
This initialization method is guaranteed to run only once for all threads.
Definition at line 399 of file fast_request.c.
References getenv_cb(), iterenv_cb(), putenv_cb(), read_cb(), thread_value_create(), write_cb(), and writef_cb().
Referenced by fast_request_create().
 {
     cgiwrap_init_emu(NULL, read_cb, writef_cb, write_cb,
                      getenv_cb, putenv_cb, iterenv_cb);
     thread_this = thread_value_create(NULL);
 }
static int iterenv_cb (void * null, int num, char ** key, char ** value) static
fcgiwrap iterenv callback
Definition at line 150 of file fast_request.c.
References free(), thread_value_t::get, req(), strdup, and strndup().
Referenced by init().
 {
     private_fast_request_t *this;
     *key = NULL;
     *value = NULL;
     this = (private_fast_request_t*)thread_this->get(thread_this);
     if (num < this->req_env_len)
     {
         char *eq;
         eq = strchr(this->req.envp[num], '=');
         if (eq)
         {
             *key = strndup(this->req.envp[num], eq - this->req.envp[num]);
             *value = strdup(eq + 1);
         }
         if (*key == NULL || *value == NULL)
         {
             free(*key);
             free(*value);
             return 1;
         }
     }
     return 0;
 }
METHOD (fast_request_t , get_cookie , char * , private_fast_request_t * this, char * name)
Definition at line 178 of file fast_request.c.
 {
     return hdf_get_valuef(this->hdf, "Cookie.%s", name);
 }
METHOD (fast_request_t , get_path , char * , private_fast_request_t * this)
Definition at line 184 of file fast_request.c.
References path, and req().
 {
     char *path = FCGX_GetParam("PATH_INFO", this->req.envp);
     return path ? path : "";
 }
METHOD (fast_request_t , get_host , char * , private_fast_request_t * this)
Definition at line 191 of file fast_request.c.
References addr, and req().
 {
     char *addr = FCGX_GetParam("REMOTE_ADDR", this->req.envp);
     return addr ? addr : "";
 }
METHOD (fast_request_t , get_user_agent , char * , private_fast_request_t * this)
Definition at line 198 of file fast_request.c.
References req().
 {
     char *agent = FCGX_GetParam("HTTP_USER_AGENT", this->req.envp);
     return agent ? agent : "";
 }
METHOD (fast_request_t , get_query_data , char * , private_fast_request_t * this, char * name)
Definition at line 205 of file fast_request.c.
 {
     return hdf_get_valuef(this->hdf, "Query.%s", name);
 }
METHOD (fast_request_t , get_env_var , char * , private_fast_request_t * this, char * name)
Definition at line 211 of file fast_request.c.
References req().
 {
     return FCGX_GetParam(name, this->req.envp);
 }
METHOD (fast_request_t , read_data , int , private_fast_request_t * this, char * buf, int len)
Definition at line 217 of file fast_request.c.
References req().
 {
     return FCGX_GetStr(buf, len, this->req.in);
 }
METHOD (fast_request_t , get_base , char * , private_fast_request_t * this)
Definition at line 223 of file fast_request.c.
References req().
 {
     return FCGX_GetParam("SCRIPT_NAME", this->req.envp);
 }
METHOD (fast_request_t , add_cookie , void , private_fast_request_t * this, char * name, char * value)
Definition at line 229 of file fast_request.c.
References thread_value_t::set.
 {
     thread_this->set(thread_this, this);
     cgi_cookie_set(this->cgi, name, value, NULL, NULL, NULL, 0, 0);
 }
METHOD (fast_request_t , redirect , void , private_fast_request_t * this, char * fmt, ...)
Definition at line 236 of file fast_request.c.
References req().
 {
     va_list args;
     FCGX_FPrintF(this->req.out, "Status: 303 See Other\n");
     FCGX_FPrintF(this->req.out, "Location: %s%s", get_base(this),
                  *fmt == '/' ? "" : "/");
     va_start(args, fmt);
     FCGX_VFPrintF(this->req.out, fmt, args);
     va_end(args);
     FCGX_FPrintF(this->req.out, "\n\n");
 }
METHOD (fast_request_t , get_referer , char * , private_fast_request_t * this)
Definition at line 250 of file fast_request.c.
References req().
 {
     return FCGX_GetParam("HTTP_REFERER", this->req.envp);
 }
METHOD (fast_request_t , to_referer , void , private_fast_request_t * this)
Definition at line 256 of file fast_request.c.
References req().
 {
     char *referer;
     referer = get_referer(this);
     if (referer)
     {
         FCGX_FPrintF(this->req.out, "Status: 303 See Other\n");
         FCGX_FPrintF(this->req.out, "Location: %s\n\n", referer);
     }
     else
     {
         redirect(this, "/");
     }
 }
METHOD (fast_request_t , session_closed , bool , private_fast_request_t * this)
Definition at line 273 of file fast_request.c.
 {
     return this->closed;
 }
METHOD (fast_request_t , close_session , void , private_fast_request_t * this)
Definition at line 279 of file fast_request.c.
References TRUE.
 {
     this->closed = TRUE;
 }
METHOD (fast_request_t , serve , void , private_fast_request_t * this, char * headers, chunk_t chunk)
Definition at line 285 of file fast_request.c.
References chunk_t::len, chunk_t::ptr, and req().
 {
     FCGX_FPrintF(this->req.out, "%s\n\n", headers);
     FCGX_PutStr(chunk.ptr, chunk.len, this->req.out);
 }
METHOD (fast_request_t , sendfile , bool , private_fast_request_t * this, char * path, char * mime)
Definition at line 293 of file fast_request.c.
References chunk_map(), chunk_skip(), chunk_unmap(), data, FALSE, chunk_t::len, chunk_t::ptr, req(), snprintf, and TRUE.
 {
     chunk_t *data;
     int written;
     char buf[24];
     data = chunk_map(path, FALSE);
     if (!data)
     {
         return FALSE;
     }
     /* FCGX does not like large integers, print to a buffer using libc */
     snprintf(buf, sizeof(buf), "%lld", (int64_t)data->len);
     FCGX_FPrintF(this->req.out, "Content-Length: %s\n", buf);
     if (mime)
     {
         FCGX_FPrintF(this->req.out, "Content-Type: %s\n", mime);
     }
     FCGX_FPrintF(this->req.out, "\n");
     while (data->len)
     {
         written = FCGX_PutStr(data->ptr, data->len, this->req.out);
         if (written == -1)
         {
             chunk_unmap(data);
             return FALSE;
         }
         *data = chunk_skip(*data, written);
     }
     chunk_unmap(data);
     return TRUE;
 }
METHOD (fast_request_t , render , void , private_fast_request_t * this, char * template)
Definition at line 329 of file fast_request.c.
References thread_value_t::set.
 {
     NEOERR* err;
     thread_this->set(thread_this, this);
     err = cgi_display(this->cgi, template);
     if (err)
     {
         cgi_neo_error(this->cgi, err);
         nerr_log_error(err);
     }
 }
METHOD (fast_request_t , streamf , int , private_fast_request_t * this, char * format, ...)
Definition at line 343 of file fast_request.c.
References req().
 {
     va_list args;
     int written;
     va_start(args, format);
     written = FCGX_VFPrintF(this->req.out, format, args);
     va_end(args);
     if (written >= 0 &&
         FCGX_FFlush(this->req.out) == -1)
     {
         return -1;
     }
     return written;
 }
METHOD (fast_request_t , set , void , private_fast_request_t * this, char * key, char * value)
Definition at line 360 of file fast_request.c.
 {
     hdf_set_value(this->hdf, key, value);
 }
METHOD (fast_request_t , setf , void , private_fast_request_t * this, char * format, ...)
Definition at line 366 of file fast_request.c.
 {
     va_list args;
     va_start(args, format);
     hdf_set_valuevf(this->hdf, format, args);
     va_end(args);
 }
METHOD (fast_request_t , get_ref , fast_request_t * , private_fast_request_t * this)
Definition at line 376 of file fast_request.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (fast_request_t , destroy , void , private_fast_request_t * this)
Definition at line 383 of file fast_request.c.
References free(), ref_put(), req(), and thread_value_t::set.
 {
     if (ref_put(&this->ref))
     {
         thread_this->set(thread_this, this);
         cgi_destroy(&this->cgi);
         FCGX_Finish_r(&this->req);
         free(this);
     }
 }
static int putenv_cb (void * null, const char * key, const char * value) static
fcgiwrap getenv callback
Definition at line 141 of file fast_request.c.
Referenced by init().
 {
     /* not supported */
     return 1;
 }
static int read_cb (void * null, char * buf, int size) static
fcgiwrap read callback
Definition at line 91 of file fast_request.c.
References thread_value_t::get, and req().
Referenced by add_watcher(), init(), METHOD(), and watch().
 {
     private_fast_request_t *this;
     this = (private_fast_request_t*)thread_this->get(thread_this);
     return FCGX_GetStr(buf, size, this->req.in);
 }
static int write_cb (void * null, const char * buf, int size) static
fcgiwrap write callback
Definition at line 115 of file fast_request.c.
References thread_value_t::get, and req().
Referenced by add_watcher(), init(), METHOD(), and watch().
 {
     private_fast_request_t *this;
     this = (private_fast_request_t*)thread_this->get(thread_this);
     return FCGX_PutStr(buf, size, this->req.out);
 }
static int writef_cb (void * null, const char * format, va_list args) static
fcgiwrap writef callback
Definition at line 103 of file fast_request.c.
References thread_value_t::get, and req().
Referenced by init().
 {
     private_fast_request_t *this;
     this = (private_fast_request_t*)thread_this->get(thread_this);
     FCGX_VFPrintF(this->req.out, format, args);
     return 0;
 }
Variable Documentation
pthread_once_t once = PTHREAD_ONCE_INIT
control variable for pthread_once
Definition at line 86 of file fast_request.c.
Referenced by fast_request_create().
thread_value_t* thread_this static
ClearSilver cgiwrap is not threadsave, so we use a private context for each thread.
Definition at line 81 of file fast_request.c.