strongSwan: esp_context.c File Reference
esp_context.c File Reference
#include <limits.h>
#include <stdint.h>
#include "esp_context.h"
#include <library.h>
#include <utils/debug.h>
Classes
struct private_esp_context_t
Macros
#define ESP_DEFAULT_WINDOW_SIZE 128
Typedefs
typedef struct
private_esp_context_t private_esp_context_t
Functions
static void set_window_bit (private_esp_context_t *this, u_int index, bool set)
static bool get_window_bit (private_esp_context_t *this, u_int index)
static bool check_window (private_esp_context_t *this, u_int32_t seqno)
METHOD (esp_context_t, verify_seqno, bool, private_esp_context_t *this, u_int32_t seqno)
METHOD (esp_context_t, set_authenticated_seqno, void, private_esp_context_t *this, u_int32_t seqno)
METHOD (esp_context_t, get_seqno, u_int32_t, private_esp_context_t *this)
METHOD (esp_context_t, next_seqno, bool, private_esp_context_t *this, u_int32_t *seqno)
METHOD (esp_context_t, get_aead, aead_t *, private_esp_context_t *this)
METHOD (esp_context_t, destroy, void, private_esp_context_t *this)
static bool create_aead (private_esp_context_t *this, int alg, chunk_t key)
static bool create_traditional (private_esp_context_t *this, int enc_alg, chunk_t enc_key, int int_alg, chunk_t int_key)
esp_context_t * esp_context_create (int enc_alg, chunk_t enc_key, int int_alg, chunk_t int_key, bool inbound)
Macro Definition Documentation
#define ESP_DEFAULT_WINDOW_SIZE 128
Should be a multiple of 8
Definition at line 29 of file esp_context.c.
Referenced by esp_context_create().
Typedef Documentation
typedef struct private_esp_context_t private_esp_context_t
Definition at line 31 of file esp_context.c.
Function Documentation
static bool check_window (private_esp_context_t * this, u_int32_t seqno) static
Returns TRUE if the supplied seqno is not already marked in the window
Definition at line 106 of file esp_context.c.
References get_window_bit(), and offset.
Referenced by METHOD().
 {
     u_int offset;
     offset = this->last_seqno - seqno;
     offset = (this->seqno_index - offset) % this->window_size;
     return !get_window_bit(this, offset);
 }
static bool create_aead (private_esp_context_t * this, int alg, chunk_t key) static
Create an AEAD algorithm
Definition at line 210 of file esp_context.c.
References aead, crypto_factory_t::create_aead, library_t::crypto, DBG1, DBG_ESP, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, ENCR_CHACHA20_POLY1305, encryption_algorithm_names, FALSE, chunk_t::len, lib, aead_t::set_key, and TRUE.
Referenced by esp_context_create().
 {
     switch (alg)
     {
         case ENCR_AES_GCM_ICV8:
         case ENCR_AES_GCM_ICV12:
         case ENCR_AES_GCM_ICV16:
         case ENCR_CHACHA20_POLY1305:
             /* the key includes a 4 byte salt */
             this->aead = lib->crypto->create_aead(lib->crypto, alg,
                                                   key.len - 4, 4);
             break;
         default:
             break;
     }
     if (!this->aead)
     {
         DBG1(DBG_ESP, "failed to create ESP context: unsupported AEAD "
              "algorithm %N", encryption_algorithm_names, alg);
         return FALSE;
     }
     if (!this->aead->set_key(this->aead, key))
     {
         DBG1(DBG_ESP, "failed to create ESP context: setting AEAD key failed");
         return FALSE;
     }
     return TRUE;
 }
static bool create_traditional (private_esp_context_t * this, int enc_alg, chunk_t enc_key, int int_alg, chunk_t int_key) static
Create AEAD wrapper around traditional encryption/integrity algorithms
Definition at line 243 of file esp_context.c.
References aead, aead_create(), crypto_factory_t::create_crypter, crypto_factory_t::create_signer, crypter, library_t::crypto, DBG1, DBG_ESP, DESTROY_IF, ENCR_AES_CTR, ENCR_CAMELLIA_CTR, encryption_algorithm_names, FALSE, integrity_algorithm_names, iv_gen_create_for_alg(), chunk_t::len, lib, signer_t::set_key, crypter_t::set_key, signer, and TRUE.
Referenced by esp_context_create().
 {
     crypter_t *crypter = NULL;
     signer_t *signer = NULL;
     iv_gen_t *ivg;
     switch (enc_alg)
     {
         case ENCR_AES_CTR:
         case ENCR_CAMELLIA_CTR:
             /* the key includes a 4 byte salt */
             crypter = lib->crypto->create_crypter(lib->crypto, enc_alg,
                                                   enc_key.len - 4);
             break;
         default:
             crypter = lib->crypto->create_crypter(lib->crypto, enc_alg,
                                                   enc_key.len);
             break;
     }
     if (!crypter)
     {
         DBG1(DBG_ESP, "failed to create ESP context: unsupported encryption "
              "algorithm %N", encryption_algorithm_names, enc_alg);
         goto failed;
     }
     if (!crypter->set_key(crypter, enc_key))
     {
         DBG1(DBG_ESP, "failed to create ESP context: setting encryption key "
              "failed");
         goto failed;
     }
     signer = lib->crypto->create_signer(lib->crypto, int_alg);
     if (!signer)
     {
         DBG1(DBG_ESP, "failed to create ESP context: unsupported integrity "
              "algorithm %N", integrity_algorithm_names, int_alg);
         goto failed;
     }
     if (!signer->set_key(signer, int_key))
     {
         DBG1(DBG_ESP, "failed to create ESP context: setting signature key "
              "failed");
         goto failed;
     }
     ivg = iv_gen_create_for_alg(enc_alg);
     if (!ivg)
     {
         DBG1(DBG_ESP, "failed to create ESP context: creating iv gen failed");
         goto failed;
     }
     this->aead = aead_create(crypter, signer, ivg);
     return TRUE;
 failed:
     DESTROY_IF(crypter);
     DESTROY_IF(signer);
     return FALSE;
 }
static bool get_window_bit (private_esp_context_t * this, u_int index) inline static
Get a bit from the window.
Definition at line 96 of file esp_context.c.
References window.
Referenced by check_window().
 {
     u_int i = index / CHAR_BIT;
     return this->window.ptr[i] & (1 << index % CHAR_BIT);
 }
METHOD (esp_context_t , verify_seqno , bool , private_esp_context_t * this, u_int32_t seqno)
Definition at line 115 of file esp_context.c.
References check_window(), FALSE, and TRUE.
 {
     if (!this->inbound)
     {
         return FALSE;
     }
     if (seqno > this->last_seqno)
     {   /*       |----------------------------------------|
          *  <---------^   ^   or    <---------^     ^
          *     WIN    H   S            WIN    H     S
          */
         return TRUE;
     }
     else if (seqno > 0 && this->window_size > this->last_seqno - seqno)
     {   /*       |----------------------------------------|
          *  <---------^      or     <---------^
          *     WIN ^  H                WIN ^  H
          *         S                       S
          */
         return check_window(this, seqno);
     }
     else
     {   /*       |----------------------------------------|
          *                       ^  <---------^
          *                       S     WIN    H
          */
         return FALSE;
     }
 }
METHOD (esp_context_t , set_authenticated_seqno , void , private_esp_context_t * this, u_int32_t seqno)
Definition at line 147 of file esp_context.c.
References FALSE, set_window_bit(), and TRUE.
 {
     u_int i, shift;
     if (!this->inbound)
     {
         return;
     }
     if (seqno > this->last_seqno)
     {   /* shift the window to the new highest authenticated seqno */
         shift = seqno - this->last_seqno;
         shift = shift < this->window_size ? shift : this->window_size;
         for (i = 0; i < shift; ++i)
         {
             this->seqno_index = (this->seqno_index + 1) % this->window_size;
             set_window_bit(this, this->seqno_index, FALSE);
         }
         set_window_bit(this, this->seqno_index, TRUE);
         this->last_seqno = seqno;
     }
     else
     {   /* seqno is inside the window, set the corresponding window bit */
         i = this->last_seqno - seqno;
         set_window_bit(this, (this->seqno_index - i) % this->window_size, TRUE);
     }
 }
METHOD (esp_context_t , get_seqno , u_int32_t , private_esp_context_t * this)
Definition at line 176 of file esp_context.c.
 {
     return this->last_seqno;
 }
METHOD (esp_context_t , next_seqno , bool , private_esp_context_t * this, u_int32_t * seqno)
Definition at line 182 of file esp_context.c.
References FALSE, TRUE, and UINT32_MAX.
 {
     if (this->inbound || this->last_seqno == UINT32_MAX)
     {   /* inbound or segno would cycle */
         return FALSE;
     }
     *seqno = ++this->last_seqno;
     return TRUE;
 }
METHOD (esp_context_t , get_aead , aead_t * , private_esp_context_t * this)
Definition at line 193 of file esp_context.c.
References aead.
 {
     return this->aead;
 }
METHOD (esp_context_t , destroy , void , private_esp_context_t * this)
Definition at line 199 of file esp_context.c.
References aead, chunk_free(), DESTROY_IF, free(), and window.
 {
     chunk_free(&this->window);
     DESTROY_IF(this->aead);
     free(this);
 }
static void set_window_bit (private_esp_context_t * this, u_int index, bool set) inline static
Set or unset a bit in the window.
Definition at line 78 of file esp_context.c.
References window.
Referenced by METHOD().
 {
     u_int i = index / CHAR_BIT;
     if (set)
     {
         this->window.ptr[i] |= 1 << (index % CHAR_BIT);
     }
     else
     {
         this->window.ptr[i] &= ~(1 << (index % CHAR_BIT));
     }
 }