strongSwan: seg_contract_manager.c File Reference
seg_contract_manager.c File Reference
#include "seg_contract_manager.h"
Classes
struct private_seg_contract_manager_t
Typedefs
typedef struct
private_seg_contract_manager_t private_seg_contract_manager_t
Functions
METHOD (seg_contract_manager_t, add_contract, void, private_seg_contract_manager_t *this, seg_contract_t *contract)
METHOD (seg_contract_manager_t, get_contract, seg_contract_t *, private_seg_contract_manager_t *this, pen_type_t msg_type, bool is_issuer, TNC_UInt32 id)
METHOD (seg_contract_manager_t, destroy, void, private_seg_contract_manager_t *this)
seg_contract_manager_t * seg_contract_manager_create (void)
Typedef Documentation
typedef struct private_seg_contract_manager_t private_seg_contract_manager_t
Definition at line 18 of file seg_contract_manager.c.
Function Documentation
METHOD (seg_contract_manager_t , add_contract , void , private_seg_contract_manager_t * this, seg_contract_t * contract)
Definition at line 38 of file seg_contract_manager.c.
 {
     this->contracts->insert_last(this->contracts, contract);
 }
METHOD (seg_contract_manager_t , get_contract , seg_contract_t * , private_seg_contract_manager_t * this, pen_type_t msg_type, bool is_issuer, TNC_UInt32 id)
Definition at line 44 of file seg_contract_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, seg_contract_t::get_issuer, seg_contract_t::get_msg_type, seg_contract_t::get_responder, seg_contract_t::is_issuer, and pen_type_equals().
 {
     enumerator_t *enumerator;
     seg_contract_t *contract, *found = NULL;
     enumerator = this->contracts->create_enumerator(this->contracts);
     while (enumerator->enumerate(enumerator, &contract))
     {
         if (contract->is_issuer(contract) == is_issuer &&
             pen_type_equals(contract->get_msg_type(contract), msg_type) &&
             id == (is_issuer ? contract->get_responder(contract) :
                                contract->get_issuer(contract)))
         {
             found = contract;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (seg_contract_manager_t , destroy , void , private_seg_contract_manager_t * this)
Definition at line 68 of file seg_contract_manager.c.
References destroy(), and free().
 {
     this->contracts->destroy_offset(this->contracts,
                                     offsetof(seg_contract_t, destroy));
     free(this);
 }