strongSwan: imv_attestation_state
imv_attestation_state
imv_attestation
Classes
struct imv_attestation_state_t
Typedefs
typedef struct
imv_attestation_state_t imv_attestation_state_t
typedef enum imv_attestation_flag_t imv_attestation_flag_t
typedef enum
imv_attestation_handshake_state_t imv_attestation_handshake_state_t
typedef enum imv_meas_error_t imv_meas_error_t
Enumerations
enum imv_attestation_flag_t {
IMV_ATTESTATION_ATTR_PRODUCT_INFO = (1<<0), IMV_ATTESTATION_ATTR_STRING_VERSION = (1<<1), IMV_ATTESTATION_ATTR_DEVICE_ID = (1<<2), IMV_ATTESTATION_ATTR_MUST = (1<<3)-1,
IMV_ATTESTATION_ATTR_REQ = (1<<3), IMV_ATTESTATION_ALGO = (1<<4), IMV_ATTESTATION_DH_NONCE = (1<<5), IMV_ATTESTATION_AIK = (1<<6),
IMV_ATTESTATION_FILE_MEAS = (1<<7), IMV_ATTESTATION_REC = (1<<8)
}
enum imv_attestation_handshake_state_t {
IMV_ATTESTATION_STATE_INIT, IMV_ATTESTATION_STATE_DISCOVERY, IMV_ATTESTATION_STATE_NONCE_REQ, IMV_ATTESTATION_STATE_TPM_INIT,
IMV_ATTESTATION_STATE_COMP_EVID, IMV_ATTESTATION_STATE_EVID_FINAL, IMV_ATTESTATION_STATE_END
}
enum imv_meas_error_t {
IMV_ATTESTATION_ERROR_FILE_MEAS_FAIL = 1, IMV_ATTESTATION_ERROR_FILE_MEAS_PEND = 2, IMV_ATTESTATION_ERROR_NO_TRUSTED_AIK = 4, IMV_ATTESTATION_ERROR_COMP_EVID_FAIL = 8,
IMV_ATTESTATION_ERROR_COMP_EVID_PEND = 16, IMV_ATTESTATION_ERROR_TPM_QUOTE_FAIL = 32
}
Functions
imv_state_t * imv_attestation_state_create (TNC_ConnectionID id)
Detailed Description
Typedef Documentation
typedef enum imv_attestation_flag_t imv_attestation_flag_t
Definition at line 37 of file imv_attestation_state.h.
typedef enum imv_attestation_handshake_state_t imv_attestation_handshake_state_t
Definition at line 38 of file imv_attestation_state.h.
typedef struct imv_attestation_state_t imv_attestation_state_t
Definition at line 36 of file imv_attestation_state.h.
typedef enum imv_meas_error_t imv_meas_error_t
Definition at line 39 of file imv_attestation_state.h.
Enumeration Type Documentation
enum imv_attestation_flag_t
IMV Attestation Flags set for completed actions
Enumerator
IMV_ATTESTATION_ATTR_PRODUCT_INFO
IMV_ATTESTATION_ATTR_STRING_VERSION
IMV_ATTESTATION_ATTR_DEVICE_ID
IMV_ATTESTATION_ATTR_MUST
IMV_ATTESTATION_ATTR_REQ
IMV_ATTESTATION_ALGO
IMV_ATTESTATION_DH_NONCE
IMV_ATTESTATION_AIK
IMV_ATTESTATION_FILE_MEAS
IMV_ATTESTATION_REC
Definition at line 44 of file imv_attestation_state.h.
{
     IMV_ATTESTATION_ATTR_PRODUCT_INFO =   (1<<0),
     IMV_ATTESTATION_ATTR_STRING_VERSION = (1<<1),
     IMV_ATTESTATION_ATTR_DEVICE_ID =      (1<<2),
     IMV_ATTESTATION_ATTR_MUST =           (1<<3)-1,
     IMV_ATTESTATION_ATTR_REQ =            (1<<3),
     IMV_ATTESTATION_ALGO =                (1<<4),
     IMV_ATTESTATION_DH_NONCE =            (1<<5),
     IMV_ATTESTATION_AIK =                 (1<<6),
     IMV_ATTESTATION_FILE_MEAS =           (1<<7),
     IMV_ATTESTATION_REC =                 (1<<8)
 };
enum imv_attestation_handshake_state_t
IMV Attestation Handshake States (state machine)
Enumerator
IMV_ATTESTATION_STATE_INIT
IMV_ATTESTATION_STATE_DISCOVERY
IMV_ATTESTATION_STATE_NONCE_REQ
IMV_ATTESTATION_STATE_TPM_INIT
IMV_ATTESTATION_STATE_COMP_EVID
IMV_ATTESTATION_STATE_EVID_FINAL
IMV_ATTESTATION_STATE_END
Definition at line 60 of file imv_attestation_state.h.
{
     IMV_ATTESTATION_STATE_INIT,
     IMV_ATTESTATION_STATE_DISCOVERY,
     IMV_ATTESTATION_STATE_NONCE_REQ,
     IMV_ATTESTATION_STATE_TPM_INIT,
     IMV_ATTESTATION_STATE_COMP_EVID,
     IMV_ATTESTATION_STATE_EVID_FINAL,
     IMV_ATTESTATION_STATE_END,
 };
enum imv_meas_error_t
IMV Measurement Error Types
Enumerator
IMV_ATTESTATION_ERROR_FILE_MEAS_FAIL
IMV_ATTESTATION_ERROR_FILE_MEAS_PEND
IMV_ATTESTATION_ERROR_NO_TRUSTED_AIK
IMV_ATTESTATION_ERROR_COMP_EVID_FAIL
IMV_ATTESTATION_ERROR_COMP_EVID_PEND
IMV_ATTESTATION_ERROR_TPM_QUOTE_FAIL
Definition at line 73 of file imv_attestation_state.h.
                       {
     IMV_ATTESTATION_ERROR_FILE_MEAS_FAIL =  1,
     IMV_ATTESTATION_ERROR_FILE_MEAS_PEND =  2,
     IMV_ATTESTATION_ERROR_NO_TRUSTED_AIK =  4,
     IMV_ATTESTATION_ERROR_COMP_EVID_FAIL =  8,
     IMV_ATTESTATION_ERROR_COMP_EVID_PEND = 16,
     IMV_ATTESTATION_ERROR_TPM_QUOTE_FAIL = 32
 };
Function Documentation
imv_state_t* imv_attestation_state_create (TNC_ConnectionID connection_id)
Create an imv_attestation_state_t instance
Parameters
id connection ID
Described in header.
Definition at line 511 of file imv_attestation_state.c.
References FALSE, IMV_ATTESTATION_STATE_INIT, INIT, linked_list_create(), pts_create(), seg_contract_manager_create(), TNC_CONNECTION_STATE_CREATE, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TNC_IMV_EVALUATION_RESULT_DONT_KNOW.
Referenced by METHOD().
 {
     private_imv_attestation_state_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_connection_id = _get_connection_id,
                 .has_long = _has_long,
                 .has_excl = _has_excl,
                 .set_flags = _set_flags,
                 .set_max_msg_len = _set_max_msg_len,
                 .get_max_msg_len = _get_max_msg_len,
                 .set_action_flags = _set_action_flags,
                 .get_action_flags = _get_action_flags,
                 .set_session = _set_session,
                 .get_session = _get_session,
                 .get_contracts = _get_contracts,
                 .change_state = _change_state,
                 .get_recommendation = _get_recommendation,
                 .set_recommendation = _set_recommendation,
                 .update_recommendation = _update_recommendation,
                 .get_reason_string = _get_reason_string,
                 .get_remediation_instructions = _get_remediation_instructions,
                 .destroy = _destroy,
             },
             .get_handshake_state = _get_handshake_state,
             .set_handshake_state = _set_handshake_state,
             .get_pts = _get_pts,
             .create_component = _create_component,
             .create_component_enumerator = _create_component_enumerator,
             .get_component = _get_component,
             .finalize_components = _finalize_components,
             .get_measurement_error = _get_measurement_error,
             .set_measurement_error = _set_measurement_error,
             .add_file_meas_reasons = _add_file_meas_reasons,
             .add_comp_evid_reasons = _add_comp_evid_reasons,
         },
         .connection_id = connection_id,
         .state = TNC_CONNECTION_STATE_CREATE,
         .handshake_state = IMV_ATTESTATION_STATE_INIT,
         .rec = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION,
         .eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW,
         .contracts = seg_contract_manager_create(),
         .components = linked_list_create(),
         .pts = pts_create(FALSE),
     );
     return &this->public.interface;
 }