strongSwan: imv_scanner_state.c File Reference
imv_scanner_state.c File Reference
#include "imv_scanner_state.h"
#include "imv/imv_lang_string.h"
#include "imv/imv_reason_string.h"
#include "imv/imv_remediation_string.h"
#include <tncif_policy.h>
#include <utils/lexparser.h>
#include <utils/debug.h>
Classes
struct private_imv_scanner_state_t
Typedefs
typedef struct
private_imv_scanner_state_t private_imv_scanner_state_t
Functions
METHOD (imv_state_t, get_connection_id, TNC_ConnectionID, private_imv_scanner_state_t *this)
METHOD (imv_state_t, has_long, bool, private_imv_scanner_state_t *this)
METHOD (imv_state_t, has_excl, bool, private_imv_scanner_state_t *this)
METHOD (imv_state_t, set_flags, void, private_imv_scanner_state_t *this, bool has_long, bool has_excl)
METHOD (imv_state_t, set_max_msg_len, void, private_imv_scanner_state_t *this, uint32_t max_msg_len)
METHOD (imv_state_t, get_max_msg_len, uint32_t, private_imv_scanner_state_t *this)
METHOD (imv_state_t, set_action_flags, void, private_imv_scanner_state_t *this, uint32_t flags)
METHOD (imv_state_t, get_action_flags, uint32_t, private_imv_scanner_state_t *this)
METHOD (imv_state_t, set_session, void, private_imv_scanner_state_t *this, imv_session_t *session)
METHOD (imv_state_t, get_session, imv_session_t *, private_imv_scanner_state_t *this)
METHOD (imv_state_t, get_contracts, seg_contract_manager_t *, private_imv_scanner_state_t *this)
METHOD (imv_state_t, change_state, void, private_imv_scanner_state_t *this, TNC_ConnectionState new_state)
METHOD (imv_state_t, get_recommendation, void, private_imv_scanner_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
METHOD (imv_state_t, set_recommendation, void, private_imv_scanner_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, update_recommendation, void, private_imv_scanner_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, get_reason_string, bool, private_imv_scanner_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
METHOD (imv_state_t, get_remediation_instructions, bool, private_imv_scanner_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
METHOD (imv_state_t, destroy, void, private_imv_scanner_state_t *this)
METHOD (imv_scanner_state_t, set_handshake_state, void, private_imv_scanner_state_t *this, imv_scanner_handshake_state_t new_state)
METHOD (imv_scanner_state_t, get_handshake_state, imv_scanner_handshake_state_t, private_imv_scanner_state_t *this)
METHOD (imv_scanner_state_t, set_port_filter_attr, void, private_imv_scanner_state_t *this, ietf_attr_port_filter_t *attr)
METHOD (imv_scanner_state_t, get_port_filter_attr, ietf_attr_port_filter_t *, private_imv_scanner_state_t *this)
METHOD (imv_scanner_state_t, add_violating_port, void, private_imv_scanner_state_t *this, char *port)
imv_state_t * imv_scanner_state_create (TNC_ConnectionID connection_id)
Variables
static char * languages [] = { "en", "de", "fr", "pl" }
static imv_lang_string_t reasons []
static imv_lang_string_t instr_ports_title []
static imv_lang_string_t instr_ports_descr []
static imv_lang_string_t instr_ports_header []
Typedef Documentation
typedef struct private_imv_scanner_state_t private_imv_scanner_state_t
Definition at line 26 of file imv_scanner_state.c.
Function Documentation
METHOD (imv_state_t , get_connection_id , TNC_ConnectionID , private_imv_scanner_state_t * this)
Definition at line 158 of file imv_scanner_state.c.
 {
     return this->connection_id;
 }
METHOD (imv_state_t , has_long , bool , private_imv_scanner_state_t * this)
Definition at line 164 of file imv_scanner_state.c.
 {
     return this->has_long;
 }
METHOD (imv_state_t , has_excl , bool , private_imv_scanner_state_t * this)
Definition at line 170 of file imv_scanner_state.c.
 {
     return this->has_excl;
 }
METHOD (imv_state_t , set_flags , void , private_imv_scanner_state_t * this, bool has_long, bool has_excl)
Definition at line 176 of file imv_scanner_state.c.
 {
     this->has_long = has_long;
     this->has_excl = has_excl;
 }
METHOD (imv_state_t , set_max_msg_len , void , private_imv_scanner_state_t * this, uint32_t max_msg_len)
Definition at line 183 of file imv_scanner_state.c.
 {
     this->max_msg_len = max_msg_len;
 }
METHOD (imv_state_t , get_max_msg_len , uint32_t , private_imv_scanner_state_t * this)
Definition at line 189 of file imv_scanner_state.c.
 {
     return this->max_msg_len;
 }
METHOD (imv_state_t , set_action_flags , void , private_imv_scanner_state_t * this, uint32_t flags)
Definition at line 195 of file imv_scanner_state.c.
References flags.
 {
     this->action_flags |= flags;
 }
METHOD (imv_state_t , get_action_flags , uint32_t , private_imv_scanner_state_t * this)
Definition at line 201 of file imv_scanner_state.c.
 {
     return this->action_flags;
 }
METHOD (imv_state_t , set_session , void , private_imv_scanner_state_t * this, imv_session_t * session)
Definition at line 207 of file imv_scanner_state.c.
 {
     this->session = session;
 }
METHOD (imv_state_t , get_session , imv_session_t * , private_imv_scanner_state_t * this)
Definition at line 213 of file imv_scanner_state.c.
 {
     return this->session;
 }
METHOD (imv_state_t , get_contracts , seg_contract_manager_t * , private_imv_scanner_state_t * this)
Definition at line 219 of file imv_scanner_state.c.
 {
     return this->contracts;
 }
METHOD (imv_state_t , change_state , void , private_imv_scanner_state_t * this, TNC_ConnectionState new_state)
Definition at line 225 of file imv_scanner_state.c.
 {
     this->state = new_state;
 }
METHOD (imv_state_t , get_recommendation , void , private_imv_scanner_state_t * this, TNC_IMV_Action_Recommendation * rec, TNC_IMV_Evaluation_Result * eval)
Definition at line 231 of file imv_scanner_state.c.
 {
     *rec = this->rec;
     *eval = this->eval;
 }
METHOD (imv_state_t , set_recommendation , void , private_imv_scanner_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 239 of file imv_scanner_state.c.
 {
     this->rec = rec;
     this->eval = eval;
 }
METHOD (imv_state_t , update_recommendation , void , private_imv_scanner_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 247 of file imv_scanner_state.c.
References tncif_policy_update_evaluation(), and tncif_policy_update_recommendation().
 {
     this->rec  = tncif_policy_update_recommendation(this->rec, rec);
     this->eval = tncif_policy_update_evaluation(this->eval, eval);
 }
METHOD (imv_state_t , get_reason_string , bool , private_imv_scanner_state_t * this, enumerator_t * language_enumerator, chunk_t * reason_string, char ** reason_language)
Definition at line 255 of file imv_scanner_state.c.
References countof, DESTROY_IF, FALSE, imv_lang_string_select_lang(), imv_reason_string_create(), languages, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TRUE.
 {
     if (this->violating_ports->get_count(this->violating_ports) == 0)
     {
         return FALSE;
     }
     *reason_language = imv_lang_string_select_lang(language_enumerator,
                                               languages, countof(languages));
     /* Instantiate a TNC Reason String object */
     DESTROY_IF(this->reason_string);
     this->reason_string = imv_reason_string_create(*reason_language, "\n");
     if (this->rec != TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION)
     {
         this->reason_string->add_reason(this->reason_string, reasons);
     }
     *reason_string = this->reason_string->get_encoding(this->reason_string);
     return TRUE;
 }
METHOD (imv_state_t , get_remediation_instructions , bool , private_imv_scanner_state_t * this, enumerator_t * language_enumerator, chunk_t * string, char ** lang_code, char ** uri)
Definition at line 278 of file imv_scanner_state.c.
References countof, DESTROY_IF, FALSE, settings_t::get_str, imv_lang_string_select_lang(), imv_remediation_string_create(), languages, lib, library_t::ns, library_t::settings, and TRUE.
 {
     if (this->violating_ports->get_count(this->violating_ports) == 0)
     {
         return FALSE;
     }
     *lang_code = imv_lang_string_select_lang(language_enumerator,
                                         languages, countof(languages));
     /* Instantiate an IETF Remediation Instructions String object */
     DESTROY_IF(this->remediation_string);
     this->remediation_string = imv_remediation_string_create(
                                     TRUE, *lang_code);  /* TODO get os_type */
     this->remediation_string->add_instruction(this->remediation_string,
                                     instr_ports_title,
                                     instr_ports_descr,
                                     instr_ports_header,
                                     this->violating_ports);
     *string = this->remediation_string->get_encoding(this->remediation_string);
     *uri = lib->settings->get_str(lib->settings,
                     "%s.plugins.imv-scanner.remediation_uri", NULL, lib->ns);
     return TRUE;
 }
METHOD (imv_state_t , destroy , void , private_imv_scanner_state_t * this)
Definition at line 306 of file imv_scanner_state.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->session);
     DESTROY_IF(this->reason_string);
     DESTROY_IF(this->remediation_string);
     DESTROY_IF(&this->port_filter_attr->pa_tnc_attribute);
     this->contracts->destroy(this->contracts);
     this->violating_ports->destroy_function(this->violating_ports, free);
     free(this);
 }
METHOD (imv_scanner_state_t , set_handshake_state , void , private_imv_scanner_state_t * this, imv_scanner_handshake_state_t new_state)
Definition at line 318 of file imv_scanner_state.c.
 {
     this->handshake_state = new_state;
 }
METHOD (imv_scanner_state_t , get_handshake_state , imv_scanner_handshake_state_t , private_imv_scanner_state_t * this)
Definition at line 324 of file imv_scanner_state.c.
 {
     return this->handshake_state;
 }
METHOD (imv_scanner_state_t , set_port_filter_attr , void , private_imv_scanner_state_t * this, ietf_attr_port_filter_t * attr)
Definition at line 330 of file imv_scanner_state.c.
References DESTROY_IF.
 {
     DESTROY_IF(&this->port_filter_attr->pa_tnc_attribute);
     this->port_filter_attr = attr;
 }
METHOD (imv_scanner_state_t , get_port_filter_attr , ietf_attr_port_filter_t * , private_imv_scanner_state_t * this)
Definition at line 337 of file imv_scanner_state.c.
 {
     return this->port_filter_attr;
 }
METHOD (imv_scanner_state_t , add_violating_port , void , private_imv_scanner_state_t * this, char * port)
Definition at line 343 of file imv_scanner_state.c.
 {
     this->violating_ports->insert_last(this->violating_ports, port);
 }
Variable Documentation
imv_lang_string_t instr_ports_descr[] static
Initial value:
= {
    { "en", "Open Internet ports have been detected" },
    { "de", "Offenen Internet-Ports wurden festgestellt" },
    { "fr", "Il y'a des ports Internet ouverts" },
    { "pl", "Porty internetowe s otwarte" },
    { NULL, NULL }
}
Definition at line 142 of file imv_scanner_state.c.
imv_lang_string_t instr_ports_header[] static
Initial value:
= {
    { "en", "Please close the following server ports:" },
    { "de", "Bitte schliessen Sie die folgenden Serverports:" },
    { "fr", "Fermez les ports du serveur suivants s'il vous plait:" },
    { "pl", "Prosz zamkn nastpujce porty serwera:" },
    { NULL, NULL }
}
Definition at line 150 of file imv_scanner_state.c.
imv_lang_string_t instr_ports_title[] static
Initial value:
= {
    { "en", "Open Server Ports" },
    { "de", "Offene Server Ports" },
    { "fr", "Ports ouverts du serveur" },
    { "pl", "Otwarte Porty Serwera" },
    { NULL, NULL }
}
Instruction strings for "Port Filters"
Definition at line 134 of file imv_scanner_state.c.
char* languages[] = { "en", "de", "fr", "pl" } static
Supported languages
Definition at line 118 of file imv_scanner_state.c.
Referenced by METHOD().
imv_lang_string_t reasons[] static
Initial value:
= {
    { "en", "Open server ports were detected" },
    { "de", "Offene Serverports wurden festgestellt" },
    { "fr", "Il y a des ports du serveur ouverts" },
    { "pl", "S otwarte porty serwera" },
    { NULL, NULL }
}
Reason strings for "Port Filter"
Definition at line 123 of file imv_scanner_state.c.