strongSwan: swid_inventory_t Struct Reference
swid_inventory_t Struct Reference
swid_inventory
#include "swid_inventory.h"
Public Attributes
bool(* collect)(swid_inventory_t *this, char *directory, char *generator, swid_inventory_t *targets, bool pretty, bool full)
void(* add)(swid_inventory_t *this, void *item)
int(* get_count)(swid_inventory_t *this)
enumerator_t *(* create_enumerator)(swid_inventory_t *this)
void(* destroy)(swid_inventory_t *this)
Detailed Description
Class managing SWID tag inventory
Definition at line 34 of file swid_inventory.h.
Member Data Documentation
void(* swid_inventory_t::add)(swid_inventory_t *this, void *item)
Collect the SWID tags stored on the endpoint
Parameters
item SWID tag or tag ID to be added
Definition at line 54 of file swid_inventory.h.
bool(* swid_inventory_t::collect)(swid_inventory_t *this, char *directory, char *generator, swid_inventory_t *targets, bool pretty, bool full)
Collect the SWID tags stored on the endpoint
Parameters
directory SWID directory path
generator Path to SWID generator
targets List of target tag IDs
pretty Generate indented XML SWID tags
full Include file information in SWID tags
Returns
TRUE if successful
Definition at line 46 of file swid_inventory.h.
Referenced by add_swid_inventory().
enumerator_t*(* swid_inventory_t::create_enumerator)(swid_inventory_t *this)
Create a SWID tag inventory enumerator
Returns
Enumerator returning either tag ID or full tag
Definition at line 68 of file swid_inventory.h.
Referenced by add_swid_inventory(), collect_tags(), generate_tags(), METHOD(), and receive_msg().
void(* swid_inventory_t::destroy)(swid_inventory_t *this)
Destroys a swid_inventory_t object.
Definition at line 73 of file swid_inventory.h.
Referenced by add_swid_inventory().
int(* swid_inventory_t::get_count)(swid_inventory_t *this)
Get the number of collected SWID tags
Returns
Number of collected SWID tags
Definition at line 61 of file swid_inventory.h.
Referenced by add_swid_inventory(), collect_tags(), generate_tags(), and receive_msg().
The documentation for this struct was generated from the following file:
swid_inventory.h