strongSwan: pb_experimental_msg
pb_experimental_msg
tnccs_20
Classes
struct pb_experimental_msg_t
Typedefs
typedef struct
pb_experimental_msg_t pb_experimental_msg_t
Functions
pb_tnc_msg_t * pb_experimental_msg_create (chunk_t body)
pb_tnc_msg_t * pb_experimental_msg_create_from_data (chunk_t data)
Detailed Description
Typedef Documentation
typedef struct pb_experimental_msg_t pb_experimental_msg_t
Definition at line 24 of file pb_experimental_msg.h.
Function Documentation
pb_tnc_msg_t* pb_experimental_msg_create (chunk_t body)
Create a PB-Experimental message from parameters
Parameters
body message body
See header
Definition at line 99 of file pb_experimental_msg.c.
References pb_experimental_msg_create_from_data().
 {
     return pb_experimental_msg_create_from_data(body);
 }
pb_tnc_msg_t* pb_experimental_msg_create_from_data (chunk_t data)
Create an unprocessed PB-Experimental message from raw data
Parameters
data PB-Experimental message data
See header
Definition at line 75 of file pb_experimental_msg.c.
References chunk_clone, INIT, PB_MSG_EXPERIMENTAL, and PEN_IETF.
Referenced by pb_experimental_msg_create(), and pb_tnc_msg_create_from_data().
 {
     private_pb_experimental_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .destroy = _destroy,
             },
         },
         .type = { PEN_IETF, PB_MSG_EXPERIMENTAL },
         .encoding = chunk_clone(data),
     );
     return &this->public.pb_interface;
 }