strongSwan: pts_component_t Struct Reference
pts_component_t Struct Reference
pts_component
#include "pts_component.h"
Public Attributes
pts_comp_func_name_t *(* get_comp_func_name)(pts_component_t *this)
u_int8_t(* get_evidence_flags)(pts_component_t *this)
u_int32_t(* get_depth)(pts_component_t *this)
status_t(* measure)(pts_component_t *this, u_int8_t qualifier, pts_t *pts, pts_comp_evidence_t **evidence)
status_t(* verify)(pts_component_t *this, u_int8_t qualifier, pts_t *pts, pts_comp_evidence_t *evidence)
bool(* finalize)(pts_component_t *this, u_int8_t qualifier, bio_writer_t *result)
pts_component_t *(* get_ref)(pts_component_t *this)
void(* destroy)(pts_component_t *this)
Detailed Description
PTS Functional Component Interface
Definition at line 38 of file pts_component.h.
Member Data Documentation
void(* pts_component_t::destroy)(pts_component_t *this)
Destroys a pts_component_t object.
Definition at line 105 of file pts_component.h.
bool(* pts_component_t::finalize)(pts_component_t *this, u_int8_t qualifier, bio_writer_t *result)
Tell the PTS Functional Component to finalize pending registrations and check for missing measurements
Parameters
qualifier PTS Component Functional Name Qualifier
result writer appending concise measurement result
Returns
TRUE if finalization successful
Definition at line 92 of file pts_component.h.
Referenced by METHOD().
pts_comp_func_name_t*(* pts_component_t::get_comp_func_name)(pts_component_t *this)
Get the PTS Component Functional Name
Returns
PTS Component Functional Name
Definition at line 45 of file pts_component.h.
Referenced by METHOD().
u_int32_t(* pts_component_t::get_depth)(pts_component_t *this)
Get the PTS Sub-component Depth
Returns
PTS Sub-component Depth
Definition at line 59 of file pts_component.h.
Referenced by entry_filter().
u_int8_t(* pts_component_t::get_evidence_flags)(pts_component_t *this)
Get the PTS Component Evidence Flags
Returns
PTS Component Functional Name
Definition at line 52 of file pts_component.h.
Referenced by entry_filter().
pts_component_t*(* pts_component_t::get_ref)(pts_component_t *this)
Get a new reference to the PTS Functional Component
Returns
this, with an increased refcount
Definition at line 100 of file pts_component.h.
Referenced by METHOD().
status_t(* pts_component_t::measure)(pts_component_t *this, u_int8_t qualifier, pts_t *pts, pts_comp_evidence_t **evidence)
Do evidence measurements on the PTS Functional Component
Parameters
qualifier PTS Component Functional Name Qualifier
pts PTS interface
evidence returns component evidence measureemt
measurements additional file measurements (NULL if not present)
Returns
status return code
Definition at line 70 of file pts_component.h.
Referenced by imc_attestation_process().
status_t(* pts_component_t::verify)(pts_component_t *this, u_int8_t qualifier, pts_t *pts, pts_comp_evidence_t *evidence)
Verify the evidence measurements of the PTS Functional Component
Parameters
qualifier PTS Component Functional Name Qualifier
pts PTS interface
evidence component evidence measurement to be verified
Returns
status return code
Definition at line 81 of file pts_component.h.
Referenced by imv_attestation_process().
The documentation for this struct was generated from the following file:
pts_component.h