strongSwan: eap_sim_server.c File Reference
eap_sim_server.c File Reference
#include "eap_sim_server.h"
#include <daemon.h>
#include <simaka_message.h>
#include <simaka_crypto.h>
#include <simaka_manager.h>
Classes
struct private_eap_sim_server_t
Macros
#define TRIPLET_COUNT 3
#define NONCE_LEN 16
Typedefs
typedef struct
private_eap_sim_server_t private_eap_sim_server_t
Functions
static bool generate_payload (simaka_message_t *message, chunk_t data, eap_payload_t **out)
METHOD (eap_method_t, initiate, status_t, private_eap_sim_server_t *this, eap_payload_t **out)
static status_t reauthenticate (private_eap_sim_server_t *this, char mk[HASH_SIZE_SHA1], u_int16_t counter, eap_payload_t **out)
static status_t process_reauthentication (private_eap_sim_server_t *this, simaka_message_t *in, eap_payload_t **out)
static status_t process_start (private_eap_sim_server_t *this, simaka_message_t *in, eap_payload_t **out)
static status_t process_challenge (private_eap_sim_server_t *this, simaka_message_t *in, eap_payload_t **out)
static status_t process_client_error (private_eap_sim_server_t *this, simaka_message_t *in)
METHOD (eap_method_t, process, status_t, private_eap_sim_server_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_sim_server_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_sim_server_t *this, chunk_t *msk)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_sim_server_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_sim_server_t *this, u_int8_t identifier)
METHOD (eap_method_t, is_mutual, bool, private_eap_sim_server_t *this)
METHOD (eap_method_t, destroy, void, private_eap_sim_server_t *this)
eap_sim_server_t * eap_sim_server_create (identification_t *server, identification_t *peer)
Variables
static chunk_t version = chunk_from_chars(0x00,0x01)
Macro Definition Documentation
#define NONCE_LEN 16
length of the AT_NONCE_S value
Definition at line 28 of file eap_sim_server.c.
Referenced by reauthenticate().
#define TRIPLET_COUNT 3
Definition at line 25 of file eap_sim_server.c.
Referenced by process_start().
Typedef Documentation
typedef struct private_eap_sim_server_t private_eap_sim_server_t
Definition at line 30 of file eap_sim_server.c.
Function Documentation
static bool generate_payload (simaka_message_t * message, chunk_t data, eap_payload_t ** out) static
Generate a payload from a message, destroy message
Definition at line 119 of file eap_sim_server.c.
References simaka_message_t::destroy, eap_payload_create_data_own(), simaka_message_t::generate, and ok.
Referenced by METHOD(), process_start(), and reauthenticate().
 {
     chunk_t chunk;
     bool ok;
     ok = message->generate(message, data, &chunk);
     if (ok)
     {
         *out = eap_payload_create_data_own(chunk);
     }
     message->destroy(message);
     return ok;
 }
METHOD (eap_method_t , initiate , status_t , private_eap_sim_server_t * this, eap_payload_t ** out)
Definition at line 134 of file eap_sim_server.c.
References simaka_message_t::add_attribute, AT_ANY_ID_REQ, AT_FULLAUTH_ID_REQ, AT_PERMANENT_ID_REQ, AT_VERSION_LIST, chunk_empty, EAP_SIM, FAILED, generate_payload(), identifier, NEED_MORE, SIM_START, simaka_message_create(), and TRUE.
 {
     simaka_message_t *message;
     message = simaka_message_create(TRUE, this->identifier++, EAP_SIM,
                                     SIM_START, this->crypto);
     message->add_attribute(message, AT_VERSION_LIST, version);
     if (this->use_reauth)
     {
         message->add_attribute(message, AT_ANY_ID_REQ, chunk_empty);
     }
     else if (this->use_pseudonym)
     {
         message->add_attribute(message, AT_FULLAUTH_ID_REQ, chunk_empty);
     }
     else if (this->use_permanent)
     {
         message->add_attribute(message, AT_PERMANENT_ID_REQ, chunk_empty);
     }
     if (!generate_payload(message, chunk_empty, out))
     {
         return FAILED;
     }
     this->pending = SIM_START;
     return NEED_MORE;
 }
METHOD (eap_method_t , process , status_t , private_eap_sim_server_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 513 of file eap_sim_server.c.
References DBG1, DBG_IKE, simaka_message_t::destroy, FAILED, eap_payload_t::get_data, simaka_message_t::get_subtype, simaka_message_t::parse, process_challenge(), process_client_error(), process_reauthentication(), process_start(), SIM_CHALLENGE, SIM_CLIENT_ERROR, SIM_REAUTHENTICATION, SIM_START, simaka_message_create_from_payload(), simaka_subtype_names, and status.
 {
     simaka_message_t *message;
     status_t status;
     message = simaka_message_create_from_payload(in->get_data(in), this->crypto);
     if (!message)
     {
         return FAILED;
     }
     if (!message->parse(message))
     {
         message->destroy(message);
         return FAILED;
     }
     switch (message->get_subtype(message))
     {
         case SIM_START:
             status = process_start(this, message, out);
             break;
         case SIM_CHALLENGE:
             status = process_challenge(this, message, out);
             break;
         case SIM_REAUTHENTICATION:
             status = process_reauthentication(this, message, out);
             break;
         case SIM_CLIENT_ERROR:
             status = process_client_error(this, message);
             break;
         default:
             DBG1(DBG_IKE, "unable to process EAP-SIM subtype %N",
                  simaka_subtype_names, message->get_subtype(message));
             status = FAILED;
             break;
     }
     message->destroy(message);
     return status;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_sim_server_t * this, u_int32_t * vendor)
Definition at line 553 of file eap_sim_server.c.
References EAP_SIM.
 {
     *vendor = 0;
     return EAP_SIM;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_sim_server_t * this, chunk_t * msk)
Definition at line 560 of file eap_sim_server.c.
References FAILED, chunk_t::ptr, and SUCCESS.
 {
     if (this->msk.ptr)
     {
         *msk = this->msk;
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_sim_server_t * this)
Definition at line 571 of file eap_sim_server.c.
References identifier.
 {
     return this->identifier;
 }
METHOD (eap_method_t , set_identifier , void , private_eap_sim_server_t * this, u_int8_t identifier)
Definition at line 577 of file eap_sim_server.c.
References identifier.
 {
     this->identifier = identifier;
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_sim_server_t * this)
Definition at line 583 of file eap_sim_server.c.
References TRUE.
 {
     return TRUE;
 }
METHOD (eap_method_t , destroy , void , private_eap_sim_server_t * this)
Definition at line 589 of file eap_sim_server.c.
References DESTROY_IF, free(), and reauth().
 {
     this->crypto->destroy(this->crypto);
     this->permanent->destroy(this->permanent);
     DESTROY_IF(this->pseudonym);
     DESTROY_IF(this->reauth);
     free(this->sreses.ptr);
     free(this->nonce.ptr);
     free(this->msk.ptr);
     free(this->counter.ptr);
     free(this);
 }
static status_t process_challenge (private_eap_sim_server_t * this, simaka_message_t * in, eap_payload_t ** out) static
process an EAP-SIM/Response/Challenge message
Definition at line 450 of file eap_sim_server.c.
References simaka_message_t::create_attribute_enumerator, data, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FAILED, SIM_CHALLENGE, simaka_attribute_skippable(), simaka_subtype_names, SUCCESS, type, and simaka_message_t::verify.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     simaka_attribute_t type;
     chunk_t data;
     if (this->pending != SIM_CHALLENGE)
     {
         DBG1(DBG_IKE, "received %N, but not expected",
              simaka_subtype_names, SIM_CHALLENGE);
         return FAILED;
     }
     /* verify AT_MAC attribute, signature is over "EAP packet | n*SRES"  */
     if (!in->verify(in, this->sreses))
     {
         return FAILED;
     }
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (!simaka_attribute_skippable(type))
         {
             enumerator->destroy(enumerator);
             return FAILED;
         }
     }
     enumerator->destroy(enumerator);
     return SUCCESS;
 }
static status_t process_client_error (private_eap_sim_server_t * this, simaka_message_t * in) static
EAP-SIM/Response/ClientErrorCode message
Definition at line 486 of file eap_sim_server.c.
References AT_CLIENT_ERROR_CODE, code, simaka_message_t::create_attribute_enumerator, data, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FAILED, memcpy, chunk_t::ptr, simaka_attribute_skippable(), simaka_client_error_names, and type.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     simaka_attribute_t type;
     chunk_t data;
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (type == AT_CLIENT_ERROR_CODE)
         {
             u_int16_t code;
             memcpy(&code, data.ptr, sizeof(code));
             DBG1(DBG_IKE, "received EAP-SIM client error '%N'",
                  simaka_client_error_names, ntohs(code));
         }
         else if (!simaka_attribute_skippable(type))
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return FAILED;
 }
static status_t process_reauthentication (private_eap_sim_server_t * this, simaka_message_t * in, eap_payload_t ** out) static
process an EAP-SIM/Response/Reauthentication message
Definition at line 215 of file eap_sim_server.c.
References AT_COUNTER, AT_COUNTER_TOO_SMALL, chunk_empty, chunk_equals_const(), simaka_message_t::create_attribute_enumerator, data, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FAILED, FALSE, initiate(), SIM_REAUTHENTICATION, simaka_attribute_names, simaka_attribute_skippable(), simaka_subtype_names, SUCCESS, TRUE, type, and simaka_message_t::verify.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     simaka_attribute_t type;
     chunk_t data, counter = chunk_empty;
     bool too_small = FALSE;
     if (this->pending != SIM_REAUTHENTICATION)
     {
         DBG1(DBG_IKE, "received %N, but not expected",
              simaka_subtype_names, SIM_REAUTHENTICATION);
         return FAILED;
     }
     /* verify AT_MAC attribute, signature is over "EAP packet | NONCE_S"  */
     if (!in->verify(in, this->nonce))
     {
         return FAILED;
     }
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         switch (type)
         {
             case AT_COUNTER:
                 counter = data;
                 break;
             case AT_COUNTER_TOO_SMALL:
                 too_small = TRUE;
                 break;
             default:
                 if (!simaka_attribute_skippable(type))
                 {
                     enumerator->destroy(enumerator);
                     return FAILED;
                 }
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (too_small)
     {
         DBG1(DBG_IKE, "received %N, initiating full authentication",
              simaka_attribute_names, AT_COUNTER_TOO_SMALL);
         this->use_reauth = FALSE;
         this->crypto->clear_keys(this->crypto);
         return initiate(this, out);
     }
     if (!chunk_equals_const(counter, this->counter))
     {
         DBG1(DBG_IKE, "received counter does not match");
         return FAILED;
     }
     return SUCCESS;
 }
static status_t process_start (private_eap_sim_server_t * this, simaka_message_t * in, eap_payload_t ** out) static
process an EAP-SIM/Response/Start message
Definition at line 276 of file eap_sim_server.c.
References simaka_message_t::add_attribute, AT_IDENTITY, AT_NEXT_PSEUDONYM, AT_NEXT_REAUTH_ID, AT_NONCE_MT, AT_RAND, AT_SELECTED_VERSION, chunk_alloca, chunk_cata, chunk_clone, chunk_empty, chunk_equals(), chunk_skip(), identification_t::clone, simaka_message_t::create_attribute_enumerator, data, DBG1, DBG_IKE, enumerator_t::destroy, identification_t::destroy, DESTROY_IF, EAP_SIM, enumerator_t::enumerate, FAILED, FALSE, free(), generate_payload(), identification_t::get_encoding, HASH_SIZE_SHA1, id, identification_create_from_data(), identifier, identity, initiate(), chunk_t::len, NEED_MORE, chunk_t::ptr, reauth(), reauthenticate(), SIM_CHALLENGE, SIM_KC_LEN, SIM_RAND_LEN, SIM_SRES_LEN, SIM_START, simaka_attribute_skippable(), simaka_message_create(), simaka_subtype_names, TRIPLET_COUNT, TRUE, and type.
Referenced by METHOD().
 {
     simaka_message_t *message;
     enumerator_t *enumerator;
     simaka_attribute_t type;
     chunk_t data, identity = chunk_empty, nonce = chunk_empty, mk;
     chunk_t rands, rand, kcs, kc, sreses, sres;
     bool supported = FALSE;
     identification_t *id;
     int i;
     if (this->pending != SIM_START)
     {
         DBG1(DBG_IKE, "received %N, but not expected",
              simaka_subtype_names, SIM_START);
         return FAILED;
     }
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         switch (type)
         {
             case AT_NONCE_MT:
                 nonce = data;
                 break;
             case AT_SELECTED_VERSION:
                 if (chunk_equals(data, version))
                 {
                     supported = TRUE;
                 }
                 break;
             case AT_IDENTITY:
                 identity = data;
                 break;
             default:
                 if (!simaka_attribute_skippable(type))
                 {
                     enumerator->destroy(enumerator);
                     return FAILED;
                 }
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (identity.len)
     {
         identification_t *permanent;
         id = identification_create_from_data(identity);
         if (this->use_reauth && !nonce.len)
         {
             char mk[HASH_SIZE_SHA1];
             u_int16_t counter;
             permanent = this->mgr->provider_is_reauth(this->mgr, id,
                                                       mk, &counter);
             if (permanent)
             {
                 this->permanent->destroy(this->permanent);
                 this->permanent = permanent;
                 this->reauth = id;
                 return reauthenticate(this, mk, counter, out);
             }
             DBG1(DBG_IKE, "received unknown reauthentication identity '%Y', "
                  "initiating full authentication", id);
             this->use_reauth = FALSE;
             id->destroy(id);
             return initiate(this, out);
         }
         if (this->use_pseudonym)
         {
             permanent = this->mgr->provider_is_pseudonym(this->mgr, id);
             if (permanent)
             {
                 this->permanent->destroy(this->permanent);
                 this->permanent = permanent;
                 this->pseudonym = id->clone(id);
                 /* we already have a new permanent identity now */
                 this->use_permanent = FALSE;
             }
         }
         if (!this->pseudonym && this->use_permanent)
         {
             DBG1(DBG_IKE, "received %spermanent identity '%Y'",
                  this->use_pseudonym ? "pseudonym or " : "", id);
             this->permanent->destroy(this->permanent);
             this->permanent = id->clone(id);
         }
         id->destroy(id);
     }
     if (!supported || !nonce.len)
     {
         DBG1(DBG_IKE, "received incomplete EAP-SIM/Response/Start");
         return FAILED;
     }
     /* read triplets from provider */
     rand = rands = chunk_alloca(SIM_RAND_LEN * TRIPLET_COUNT);
     kc = kcs = chunk_alloca(SIM_KC_LEN * TRIPLET_COUNT);
     sres = sreses = chunk_alloca(SIM_SRES_LEN * TRIPLET_COUNT);
     rands.len = kcs.len = sreses.len = 0;
     for (i = 0; i < TRIPLET_COUNT; i++)
     {
         if (!this->mgr->provider_get_triplet(this->mgr, this->permanent,
                                              rand.ptr, sres.ptr, kc.ptr))
         {
             if (this->use_pseudonym)
             {
                 /* probably received a pseudonym we couldn't map */
                 DBG1(DBG_IKE, "failed to map pseudonym identity '%Y', "
                      "fallback to permanent identity request", this->permanent);
                 this->use_pseudonym = FALSE;
                 DESTROY_IF(this->pseudonym);
                 this->pseudonym = NULL;
                 return initiate(this, out);
             }
             return FAILED;
         }
         rands.len += SIM_RAND_LEN;
         sreses.len += SIM_SRES_LEN;
         kcs.len += SIM_KC_LEN;
         rand = chunk_skip(rand, SIM_RAND_LEN);
         sres = chunk_skip(sres, SIM_SRES_LEN);
         kc = chunk_skip(kc, SIM_KC_LEN);
     }
     free(this->sreses.ptr);
     this->sreses = chunk_clone(sreses);
     data = chunk_cata("cccc", kcs, nonce, version, version);
     free(this->msk.ptr);
     id = this->permanent;
     if (this->pseudonym)
     {
         id = this->pseudonym;
     }
     if (!this->crypto->derive_keys_full(this->crypto, id, data, &mk, &this->msk))
     {
         return FAILED;
     }
     /* build response with AT_MAC, built over "EAP packet | NONCE_MT" */
     message = simaka_message_create(TRUE, this->identifier++, EAP_SIM,
                                     SIM_CHALLENGE, this->crypto);
     message->add_attribute(message, AT_RAND, rands);
     id = this->mgr->provider_gen_reauth(this->mgr, this->permanent, mk.ptr);
     free(mk.ptr);
     if (id)
     {
         message->add_attribute(message, AT_NEXT_REAUTH_ID,
                                id->get_encoding(id));
         id->destroy(id);
     }
     id = this->mgr->provider_gen_pseudonym(this->mgr, this->permanent);
     if (id)
     {
         message->add_attribute(message, AT_NEXT_PSEUDONYM,
                                id->get_encoding(id));
         id->destroy(id);
     }
     if (!generate_payload(message, nonce, out))
     {
         return FAILED;
     }
     this->pending = SIM_CHALLENGE;
     return NEED_MORE;
 }
static status_t reauthenticate (private_eap_sim_server_t * this, char mk[HASH_SIZE_SHA1], u_int16_t counter, eap_payload_t ** out) static
Initiate EAP-SIM/Request/Re-authentication message
Definition at line 165 of file eap_sim_server.c.
References simaka_message_t::add_attribute, rng_t::allocate_bytes, AT_COUNTER, AT_NEXT_REAUTH_ID, AT_NONCE_S, chunk_clone, chunk_create(), chunk_empty, DBG1, DBG_IKE, identification_t::destroy, EAP_SIM, FAILED, generate_payload(), identification_t::get_encoding, identifier, NEED_MORE, next, NONCE_LEN, reauth(), rng, SIM_REAUTHENTICATION, simaka_message_create(), and TRUE.
Referenced by process_start().
 {
     simaka_message_t *message;
     identification_t *next;
     chunk_t mkc;
     rng_t *rng;
     DBG1(DBG_IKE, "initiating EAP-SIM reauthentication");
     rng = this->crypto->get_rng(this->crypto);
     if (!rng->allocate_bytes(rng, NONCE_LEN, &this->nonce))
     {
         return FAILED;
     }
     mkc = chunk_create(mk, HASH_SIZE_SHA1);
     counter = htons(counter);
     this->counter = chunk_clone(chunk_create((char*)&counter, sizeof(counter)));
     if (!this->crypto->derive_keys_reauth(this->crypto, mkc) ||
         !this->crypto->derive_keys_reauth_msk(this->crypto,
                     this->reauth, this->counter, this->nonce, mkc, &this->msk))
     {
         return FAILED;
     }
     message = simaka_message_create(TRUE, this->identifier++, EAP_SIM,
                                     SIM_REAUTHENTICATION, this->crypto);
     message->add_attribute(message, AT_COUNTER, this->counter);
     message->add_attribute(message, AT_NONCE_S, this->nonce);
     next = this->mgr->provider_gen_reauth(this->mgr, this->permanent, mk);
     if (next)
     {
         message->add_attribute(message, AT_NEXT_REAUTH_ID,
                                next->get_encoding(next));
         next->destroy(next);
     }
     if (!generate_payload(message, chunk_empty, out))
     {
         return FAILED;
     }
     this->pending = SIM_REAUTHENTICATION;
     return NEED_MORE;
 }
Variable Documentation
chunk_t version = chunk_from_chars(0x00,0x01) static
Definition at line 114 of file eap_sim_server.c.