strongSwan: load_tester_creds
load_tester_creds
load_tester
Classes
struct load_tester_creds_t
Typedefs
typedef struct load_tester_creds_t load_tester_creds_t
Functions
load_tester_creds_t * load_tester_creds_create ()
Detailed Description
Typedef Documentation
typedef struct load_tester_creds_t load_tester_creds_t
Definition at line 26 of file load_tester_creds.h.
Function Documentation
load_tester_creds_t* load_tester_creds_create ()
Create a credential set for load testing.
Returns
credential set
Definition at line 449 of file load_tester_creds.c.
References chunk_clone, chunk_create(), DBG1, DBG_CFG, default_psk, default_pwd, enum_from_name, settings_t::get_str, hash_algorithm_short_names, HASH_SHA1, INIT, lib, linked_list_create(), load_ca_certs(), load_issuer_cert(), load_issuer_key(), nop(), library_t::ns, return_null(), library_t::settings, SHARED_EAP, SHARED_IKE, shared_key_create(), and uri.
Referenced by register_load_tester().
 {
     private_load_tester_creds_t *this;
     char *pwd, *psk, *digest, *crl;
     psk = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.preshared_key", default_psk, lib->ns);
     pwd = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.eap_password", default_pwd, lib->ns);
     digest = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.digest", "sha1", lib->ns);
     crl = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.crl", NULL, lib->ns);
     INIT(this,
         .public = {
             .credential_set = {
                 .create_shared_enumerator = _create_shared_enumerator,
                 .create_private_enumerator = _create_private_enumerator,
                 .create_cert_enumerator = _create_cert_enumerator,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .destroy = _destroy,
         },
         .private = load_issuer_key(),
         .ca = load_issuer_cert(),
         .cas = linked_list_create(),
         .cdps = linked_list_create(),
         .psk = shared_key_create(SHARED_IKE,
                                  chunk_clone(chunk_create(psk, strlen(psk)))),
         .pwd = shared_key_create(SHARED_EAP,
                                  chunk_clone(chunk_create(pwd, strlen(pwd)))),
     );
     if (this->ca)
     {
         this->cas->insert_last(this->cas, this->ca->get_ref(this->ca));
     }
     if (!enum_from_name(hash_algorithm_short_names, digest, &this->digest))
     {
         DBG1(DBG_CFG, "invalid load-tester digest: '%s', using sha1", digest);
         this->digest = HASH_SHA1;
     }
     if (crl)
     {
         x509_cdp_t *cdp;
         INIT(cdp,
             .uri = crl,
         );
         this->cdps->insert_last(this->cdps, cdp);
     }
     load_ca_certs(this);
     return &this->public;
 }