strongSwan: nm_handler.c File Reference
nm_handler.c File Reference
#include "nm_handler.h"
#include <daemon.h>
Classes
struct private_nm_handler_t
Typedefs
typedef struct private_nm_handler_t private_nm_handler_t
Functions
METHOD (attribute_handler_t, handle, bool, private_nm_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
static bool enumerate_nbns (enumerator_t *this, configuration_attribute_type_t *type, chunk_t *data)
static bool enumerate_dns (enumerator_t *this, configuration_attribute_type_t *type, chunk_t *data)
METHOD (attribute_handler_t, create_attribute_enumerator, enumerator_t *, private_nm_handler_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
static bool filter_chunks (void *null, char **in, chunk_t *out)
METHOD (nm_handler_t, create_enumerator, enumerator_t *, private_nm_handler_t *this, configuration_attribute_type_t type)
METHOD (nm_handler_t, reset, void, private_nm_handler_t *this)
METHOD (nm_handler_t, destroy, void, private_nm_handler_t *this)
nm_handler_t * nm_handler_create ()
Typedef Documentation
typedef struct private_nm_handler_t private_nm_handler_t
Definition at line 20 of file nm_handler.c.
Function Documentation
static bool enumerate_dns (enumerator_t * this, configuration_attribute_type_t * type, chunk_t * data) static
Implementation of create_attribute_enumerator().enumerate() for DNS
Definition at line 84 of file nm_handler.c.
References chunk_empty, enumerate(), enumerate_nbns(), INTERNAL_IP4_DNS, and TRUE.
Referenced by METHOD().
 {
     *type = INTERNAL_IP4_DNS;
     *data = chunk_empty;
     /* enumerate WINS server as next attribute ... */
     this->enumerate = (void*)enumerate_nbns;
     return TRUE;
 }
static bool enumerate_nbns (enumerator_t * this, configuration_attribute_type_t * type, chunk_t * data) static
Implementation of create_attribute_enumerator().enumerate() for WINS
Definition at line 71 of file nm_handler.c.
References chunk_empty, enumerate(), INTERNAL_IP4_NBNS, return_false(), and TRUE.
Referenced by enumerate_dns().
 {
     *type = INTERNAL_IP4_NBNS;
     *data = chunk_empty;
     /* done */
     this->enumerate = (void*)return_false;
     return TRUE;
 }
static bool filter_chunks (void * null, char ** in, chunk_t * out) static
convert plain byte ptrs to handy chunk during enumeration
Definition at line 114 of file nm_handler.c.
References chunk_create(), and TRUE.
Referenced by METHOD().
 {
     *out = chunk_create(*in, 4);
     return TRUE;
 }
METHOD (attribute_handler_t , handle , bool , private_nm_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 43 of file nm_handler.c.
References chunk_clone, FALSE, linked_list_t::insert_last, INTERNAL_IP4_DNS, INTERNAL_IP4_NBNS, chunk_t::len, list, and TRUE.
 {
     linked_list_t *list;
     switch (type)
     {
         case INTERNAL_IP4_DNS:
             list = this->dns;
             break;
         case INTERNAL_IP4_NBNS:
             list = this->nbns;
             break;
         default:
             return FALSE;
     }
     if (data.len != 4)
     {
         return FALSE;
     }
     list->insert_last(list, chunk_clone(data).ptr);
     return TRUE;
 }
METHOD (attribute_handler_t , create_attribute_enumerator , enumerator_t * , private_nm_handler_t * this, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 94 of file nm_handler.c.
References destroy(), enumerate(), enumerate_dns(), enumerator_create_empty(), free(), linked_list_t::get_count, and INIT.
 {
     if (vips->get_count(vips))
     {
         enumerator_t *enumerator;
         INIT(enumerator,
             /* enumerate DNS attribute first ... */
             .enumerate = (void*)enumerate_dns,
             .destroy = (void*)free,
         );
         return enumerator;
     }
     return enumerator_create_empty();
 }
METHOD (nm_handler_t , create_enumerator , enumerator_t * , private_nm_handler_t * this, configuration_attribute_type_t type)
Definition at line 120 of file nm_handler.c.
References linked_list_t::create_enumerator, enumerator_create_empty(), enumerator_create_filter(), filter_chunks(), INTERNAL_IP4_DNS, INTERNAL_IP4_NBNS, and list.
 {
     linked_list_t *list;
     switch (type)
     {
         case INTERNAL_IP4_DNS:
             list = this->dns;
             break;
         case INTERNAL_IP4_NBNS:
             list = this->nbns;
             break;
         default:
             return enumerator_create_empty();
     }
     return enumerator_create_filter(list->create_enumerator(list),
                         (void*)filter_chunks, NULL, NULL);
 }
METHOD (nm_handler_t , reset , void , private_nm_handler_t * this)
Definition at line 140 of file nm_handler.c.
References data, free(), and SUCCESS.
 {
     void *data;
     while (this->dns->remove_last(this->dns, (void**)&data) == SUCCESS)
     {
         free(data);
     }
     while (this->nbns->remove_last(this->nbns, (void**)&data) == SUCCESS)
     {
         free(data);
     }
 }
METHOD (nm_handler_t , destroy , void , private_nm_handler_t * this)
Definition at line 155 of file nm_handler.c.
References free().
 {
     reset(this);
     this->dns->destroy(this->dns);
     this->nbns->destroy(this->nbns);
     free(this);
 }