strongSwan: gmp_diffie_hellman.c File Reference
gmp_diffie_hellman.c File Reference
#include <gmp.h>
#include "gmp_diffie_hellman.h"
#include <utils/debug.h>
Classes
struct private_gmp_diffie_hellman_t
Typedefs
typedef struct
private_gmp_diffie_hellman_t private_gmp_diffie_hellman_t
Functions
METHOD (diffie_hellman_t, set_other_public_value, bool, private_gmp_diffie_hellman_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_my_public_value, bool, private_gmp_diffie_hellman_t *this, chunk_t *value)
METHOD (diffie_hellman_t, set_private_value, bool, private_gmp_diffie_hellman_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_shared_secret, bool, private_gmp_diffie_hellman_t *this, chunk_t *secret)
METHOD (diffie_hellman_t, get_dh_group, diffie_hellman_group_t, private_gmp_diffie_hellman_t *this)
METHOD (diffie_hellman_t, destroy, void, private_gmp_diffie_hellman_t *this)
static gmp_diffie_hellman_t * create_generic (diffie_hellman_group_t group, size_t exp_len, chunk_t g, chunk_t p)
gmp_diffie_hellman_t * gmp_diffie_hellman_create (diffie_hellman_group_t group)
gmp_diffie_hellman_t * gmp_diffie_hellman_create_custom (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Typedef Documentation
typedef struct private_gmp_diffie_hellman_t private_gmp_diffie_hellman_t
Definition at line 31 of file gmp_diffie_hellman.c.
Function Documentation
static gmp_diffie_hellman_t* create_generic (diffie_hellman_group_t group, size_t exp_len, chunk_t g, chunk_t p) static
Generic internal constructor
Definition at line 211 of file gmp_diffie_hellman.c.
References rng_t::allocate_bytes, chunk_clear(), crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG2, DBG_LIB, rng_t::destroy, destroy(), group, INIT, chunk_t::len, lib, chunk_t::ptr, random, rng, rng_quality_names, and RNG_STRONG.
Referenced by gmp_diffie_hellman_create(), and gmp_diffie_hellman_create_custom().
 {
     private_gmp_diffie_hellman_t *this;
     chunk_t random;
     rng_t *rng;
     INIT(this,
         .public = {
             .dh = {
                 .get_shared_secret = _get_shared_secret,
                 .set_other_public_value = _set_other_public_value,
                 .get_my_public_value = _get_my_public_value,
                 .set_private_value = _set_private_value,
                 .get_dh_group = _get_dh_group,
                 .destroy = _destroy,
             },
         },
         .group = group,
         .p_len = p.len,
     );
     mpz_init(this->p);
     mpz_init(this->yb);
     mpz_init(this->ya);
     mpz_init(this->xa);
     mpz_init(this->zz);
     mpz_init(this->g);
     mpz_import(this->g, g.len, 1, 1, 1, 0, g.ptr);
     mpz_import(this->p, p.len, 1, 1, 1, 0, p.ptr);
     rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
     if (!rng)
     {
         DBG1(DBG_LIB, "no RNG found for quality %N", rng_quality_names,
              RNG_STRONG);
         destroy(this);
         return NULL;
     }
     if (!rng->allocate_bytes(rng, exp_len, &random))
     {
         DBG1(DBG_LIB, "failed to allocate DH secret");
         rng->destroy(rng);
         destroy(this);
         return NULL;
     }
     rng->destroy(rng);
     if (exp_len == this->p_len)
     {
         /* achieve bitsof(p)-1 by setting MSB to 0 */
         *random.ptr &= 0x7F;
     }
     mpz_import(this->xa, random.len, 1, 1, 1, 0, random.ptr);
     chunk_clear(&random);
     DBG2(DBG_LIB, "size of DH secret exponent: %u bits",
          mpz_sizeinbase(this->xa, 2));
     mpz_powm(this->ya, this->g, this->xa, this->p);
     return &this->public;
 }
METHOD (diffie_hellman_t , set_other_public_value , bool , private_gmp_diffie_hellman_t * this, chunk_t value)
Definition at line 88 of file gmp_diffie_hellman.c.
References DBG1, DBG_LIB, diffie_hellman_get_params(), diffie_hellman_verify_value(), FALSE, group, chunk_t::len, params, chunk_t::ptr, q, diffie_hellman_params_t::subgroup, and TRUE.
 {
     mpz_t p_min_1;
     if (!diffie_hellman_verify_value(this->group, value))
     {
         return FALSE;
     }
     mpz_init(p_min_1);
     mpz_sub_ui(p_min_1, this->p, 1);
     mpz_import(this->yb, value.len, 1, 1, 1, 0, value.ptr);
     /* check public value:
      * 1. 0 or 1 is invalid as 0^a = 0 and 1^a = 1
      * 2. a public value larger or equal the modulus is invalid */
     if (mpz_cmp_ui(this->yb, 1) > 0 &&
         mpz_cmp(this->yb, p_min_1) < 0)
     {
 #ifdef EXTENDED_DH_TEST
         /* 3. test if y ^ q mod p = 1, where q = (p - 1)/2. */
         mpz_t q, one;
         diffie_hellman_params_t *params;
         mpz_init(q);
         mpz_init(one);
         params = diffie_hellman_get_params(this->group);
         if (!params->subgroup.len)
         {
             mpz_fdiv_q_2exp(q, p_min_1, 1);
         }
         else
         {
             mpz_import(q, params->subgroup.len, 1, 1, 1, 0, params->subgroup.ptr);
         }
         mpz_powm(one, this->yb, q, this->p);
         mpz_clear(q);
         if (mpz_cmp_ui(one, 1) == 0)
         {
             mpz_powm(this->zz, this->yb, this->xa, this->p);
             this->computed = TRUE;
         }
         else
         {
             DBG1(DBG_LIB, "public DH value verification failed:"
                  " y ^ q mod p != 1");
         }
         mpz_clear(one);
 #else
         mpz_powm(this->zz, this->yb, this->xa, this->p);
         this->computed = TRUE;
 #endif
     }
     else
     {
         DBG1(DBG_LIB, "public DH value verification failed:"
              " y < 2 || y > p - 1 ");
     }
     mpz_clear(p_min_1);
     return this->computed;
 }
METHOD (diffie_hellman_t , get_my_public_value , bool , private_gmp_diffie_hellman_t * this, chunk_t * value)
Definition at line 153 of file gmp_diffie_hellman.c.
References chunk_t::len, chunk_t::ptr, and TRUE.
 {
     value->len = this->p_len;
     value->ptr = mpz_export(NULL, NULL, 1, value->len, 1, 0, this->ya);
     if (value->ptr == NULL)
     {
         value->len = 0;
     }
     return TRUE;
 }
METHOD (diffie_hellman_t , set_private_value , bool , private_gmp_diffie_hellman_t * this, chunk_t value)
Definition at line 165 of file gmp_diffie_hellman.c.
References FALSE, g, chunk_t::len, chunk_t::ptr, and TRUE.
 {
     mpz_import(this->xa, value.len, 1, 1, 1, 0, value.ptr);
     mpz_powm(this->ya, this->g, this->xa, this->p);
     this->computed = FALSE;
     return TRUE;
 }
METHOD (diffie_hellman_t , get_shared_secret , bool , private_gmp_diffie_hellman_t * this, chunk_t * secret)
Definition at line 174 of file gmp_diffie_hellman.c.
References FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
 {
     if (!this->computed)
     {
         return FALSE;
     }
     secret->len = this->p_len;
     secret->ptr = mpz_export(NULL, NULL, 1, secret->len, 1, 0, this->zz);
     if (secret->ptr == NULL)
     {
         return FALSE;
     }
     return TRUE;
 }
METHOD (diffie_hellman_t , get_dh_group , diffie_hellman_group_t , private_gmp_diffie_hellman_t * this)
Definition at line 190 of file gmp_diffie_hellman.c.
References group.
 {
     return this->group;
 }
METHOD (diffie_hellman_t , destroy , void , private_gmp_diffie_hellman_t * this)
Definition at line 196 of file gmp_diffie_hellman.c.
References free(), and g.
 {
     mpz_clear(this->p);
     mpz_clear(this->xa);
     mpz_clear(this->ya);
     mpz_clear(this->yb);
     mpz_clear(this->zz);
     mpz_clear(this->g);
     free(this);
 }