strongSwan: bliss_private_key
bliss_private_key
bliss
Classes
struct bliss_private_key_t
Typedefs
typedef struct bliss_private_key_t bliss_private_key_t
Functions
bliss_private_key_t * bliss_private_key_gen (key_type_t type, va_list args)
bliss_private_key_t * bliss_private_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct bliss_private_key_t bliss_private_key_t
Definition at line 27 of file bliss_private_key.h.
Function Documentation
bliss_private_key_t* bliss_private_key_gen (key_type_t type, va_list args)
Generate a BLISS private key.
Accepts the BUILD_KEY_SIZE argument.
Parameters
type type of the key, must be KEY_BLISS
args builder_part_t argument list
Returns
generated key, NULL on failure
See header.
Definition at line 995 of file bliss_private_key.c.
References a, BLISS_B_I, BLISS_B_II, BLISS_B_III, BLISS_B_IV, bliss_fft_create(), BLISS_I, BLISS_II, BLISS_III, BLISS_IV, bliss_param_set_get_by_id(), bliss_private_key_create_empty(), BUILD_END, BUILD_KEY_SIZE, crypto_factory_t::create_rng, create_secret(), library_t::crypto, DBG1, DBG4, DBG_LIB, bliss_fft_t::destroy, rng_t::destroy, destroy(), FALSE, bliss_param_set_t::fft_params, free(), settings_t::get_bool, invert(), key_size, lib, malloc(), memwipe(), bliss_fft_params_t::n, bliss_param_set_t::n, n, library_t::ns, bliss_fft_params_t::q, q, bliss_param_set_t::q, rng, RNG_TRUE, SECRET_KEY_TRIALS_MAX, library_t::settings, bliss_fft_t::transform, and TRUE.
Referenced by METHOD().
 {
     private_bliss_private_key_t *this;
     u_int key_size = BLISS_B_I;
     int i, n, trials = 0;
     uint32_t *S1, *S2, *a;
     uint16_t q;
     bool success = FALSE;
     bliss_param_set_t *set;
     bliss_fft_t *fft;
     rng_t *rng;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_KEY_SIZE:
                 key_size = va_arg(args, u_int);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (lib->settings->get_bool(lib->settings, "%s.plugins.bliss.use_bliss_b",
                                 TRUE, lib->ns))
     {
         switch (key_size)
         {
             case BLISS_I:
                 key_size = BLISS_B_I;
                 break;
             case BLISS_II:
                 key_size = BLISS_B_II;
                 break;
             case BLISS_III:
                 key_size = BLISS_B_III;
                 break;
             case BLISS_IV:
                 key_size = BLISS_B_IV;
                 break;
             default:
                 break;
         }
     }
     /* Only BLISS or BLISS-B types I, III, or IV are currently supported */
     set = bliss_param_set_get_by_id(key_size);
     if (!set)
     {
         DBG1(DBG_LIB, "BLISS parameter set %u not supported", key_size);
         return NULL;
     }
     /* Some shortcuts for often used variables */
     n = set->n;
     q = set->q;
     if (set->fft_params->n != n || set->fft_params->q != q)
     {
         DBG1(DBG_LIB, "FFT parameters do not match BLISS parameters");
         return NULL;
     }
     this = bliss_private_key_create_empty();
     this->set = set;
     /* We derive the public key from the private key using the FFT */
     fft = bliss_fft_create(set->fft_params);
     /* Some vectors needed to derive the publi key */
     S1 = malloc(n * sizeof(uint32_t));
     S2 = malloc(n * sizeof(uint32_t));
     a  = malloc(n * sizeof(uint32_t));
     this->A = malloc(n * sizeof(uint32_t));
     /* Instantiate a true random generator */
     rng = lib->crypto->create_rng(lib->crypto, RNG_TRUE);
     /* Loop until we have an invertible polynomial s1 */
     do
     {
         if (!create_secret(this, rng, &this->s1, &this->s2, &trials))
         {
             break;
         }
         /* Convert signed arrays to unsigned arrays before FFT */
         for (i = 0; i < n; i++)
         {
             S1[i] = (this->s1[i] < 0) ? this->s1[i] + q :  this->s1[i];
             S2[i] = (this->s2[i] > 0) ? q - this->s2[i] : -this->s2[i];
         }
         fft->transform(fft, S1, S1, FALSE);
         fft->transform(fft, S2, S2, FALSE);
         success = TRUE;
         for (i = 0; i < n; i++)
         {
             if (S1[i] == 0)
             {
                 DBG1(DBG_LIB, "S1[%d] is zero - s1 is not invertible", i);
                 free(this->s1);
                 free(this->s2);
                 this->s1 = NULL;
                 this->s2 = NULL;
                 success = FALSE;
                 break;
             }
             this->A[i] = invert(S1[i], q);
             this->A[i] = (S2[i] * this->A[i]) % q;
         }
     }
     while (!success && trials < SECRET_KEY_TRIALS_MAX);
     DBG1(DBG_LIB, "secret key generation %s after %d trial%s",
          success ? "succeeded" : "failed", trials, (trials == 1) ? "" : "s");
     if (success)
     {
         fft->transform(fft, this->A, a, TRUE);
         DBG4(DBG_LIB, "   i   f   g     a     F     G     A");
         for (i = 0; i < n; i++)
         {
             DBG4(DBG_LIB, "%4d %3d %3d %5u %5u %5u %5u",
                  i, this->s1[i], this->s2[i], a[i], S1[i], S2[i], this->A[i]);
         }
     }
     else
     {
         destroy(this);
     }
     /* Cleanup */
     fft->destroy(fft);
     rng->destroy(rng);
     memwipe(S1, n * sizeof(uint32_t));
     memwipe(S2, n * sizeof(uint32_t));
     free(S1);
     free(S2);
     free(a);
     return success ? &this->public : NULL;
 }
bliss_private_key_t* bliss_private_key_load (key_type_t type, va_list args)
Load a BLISS private key.
Accepts BUILD_BLISS_* components.
Parameters
type type of the key, must be KEY_BLISS
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 1162 of file bliss_private_key.c.
References asn1_known_oid(), asn1_parser_create(), BLISS_B_I, BLISS_B_III, BLISS_B_IV, bliss_bitpacker_create_from_data(), BLISS_I, BLISS_III, BLISS_IV, bliss_param_set_get_by_id(), bliss_param_set_get_by_oid(), bliss_private_key_create_empty(), bliss_public_key_from_asn1(), BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, chunk_skip(), bliss_bitpacker_t::destroy, asn1_parser_t::destroy, destroy(), end, FALSE, settings_t::get_bool, asn1_parser_t::iterate, key, chunk_t::len, len, lib, malloc(), library_t::ns, OID_UNKNOWN, parser, PRIV_KEY_PUBLIC, PRIV_KEY_SECRET1, PRIV_KEY_SECRET2, PRIV_KEY_TYPE, bliss_bitpacker_t::read_bits, s, asn1_parser_t::set_flags, library_t::settings, asn1_parser_t::success, TRUE, and value.
Referenced by METHOD().
 {
     private_bliss_private_key_t *this;
     chunk_t key = chunk_empty, object;
     bliss_bitpacker_t *packer;
     asn1_parser_t *parser;
     size_t s_bits = 0;
     int8_t s, s_min = 0, s_max = 0;
     uint32_t s_sign = 0x02, s_mask = 0xfffffffc, value;
     bool success = FALSE;
     int objectID, oid, i;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 key = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (key.len == 0)
     {
         return NULL;
     }
     this = bliss_private_key_create_empty();
     parser = asn1_parser_create(privkeyObjects, key);
     parser->set_flags(parser, FALSE, TRUE);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case PRIV_KEY_TYPE:
                 oid = asn1_known_oid(object);
                 if (oid == OID_UNKNOWN)
                 {
                     goto end;
                 }
                 this->set = bliss_param_set_get_by_oid(oid);
                 if (this->set == NULL)
                 {
                     goto end;
                 }
                 if (lib->settings->get_bool(lib->settings,
                             "%s.plugins.bliss.use_bliss_b",TRUE, lib->ns))
                 {
                     switch (this->set->id)
                     {
                         case BLISS_I:
                             this->set = bliss_param_set_get_by_id(BLISS_B_I);
                             break;
                         case BLISS_III:
                             this->set = bliss_param_set_get_by_id(BLISS_B_III);
                             break;
                         case BLISS_IV:
                             this->set = bliss_param_set_get_by_id(BLISS_B_IV);
                             break;
                         default:
                             break;
                     }
                 }
                 if (this->set->non_zero2)
                 {
                     s_min = -2;
                     s_max =  2;
                     s_bits = 3;
                 }
                 else
                 {
                     s_min = -1;
                     s_max =  1;
                     s_bits = 2;
                 }
                 s_sign = 1 << (s_bits - 1);
                 s_mask = ((1 << (32 - s_bits)) - 1) << s_bits;
                 break;
             case PRIV_KEY_PUBLIC:
                 if (!bliss_public_key_from_asn1(object, this->set, &this->A))
                 {
                     goto end;
                 }
                 break;
             case PRIV_KEY_SECRET1:
                 if (object.len != 1 + (s_bits * this->set->n + 7)/8)
                 {
                     goto end;
                 }
                 this->s1 = malloc(this->set->n);
                 /* Skip unused bits octet */
                 object = chunk_skip(object, 1);
                 packer = bliss_bitpacker_create_from_data(object);
                 for (i = 0; i < this->set->n; i++)
                 {
                     packer->read_bits(packer, &value, s_bits);
                     s = (value & s_sign) ? value | s_mask : value;
                     if (s < s_min || s > s_max)
                     {
                         packer->destroy(packer);
                         goto end;
                     }
                     this->s1[i] = s;
                 }
                 packer->destroy(packer);
                 break;
             case PRIV_KEY_SECRET2:
                 if (object.len != 1 + (s_bits * this->set->n + 7)/8)
                 {
                     goto end;
                 }
                 this->s2 = malloc(this->set->n);
                 /* Skip unused bits octet */
                 object = chunk_skip(object, 1);
                 packer = bliss_bitpacker_create_from_data(object);
                 for (i = 0; i < this->set->n; i++)
                 {
                     packer->read_bits(packer, &value, s_bits);
                     s = (value & s_sign) ? value | s_mask : value;
                     if (s < s_min || s > s_max)
                     {
                         packer->destroy(packer);
                         goto end;
                     }
                     this->s2[i] = 2 * s;
                     if (i == 0)
                     {
                         this->s2[0] += 1;
                     }
                 }
                 packer->destroy(packer);
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     if (!success)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }