strongSwan: unity_provider
unity_provider
unity
Classes
struct unity_provider_t
Typedefs
typedef struct unity_provider_t unity_provider_t
Functions
unity_provider_t * unity_provider_create ()
Detailed Description
Typedef Documentation
typedef struct unity_provider_t unity_provider_t
Definition at line 24 of file unity_provider.h.
Function Documentation
unity_provider_t* unity_provider_create ()
Create a unity_provider instance.
See header
Definition at line 204 of file unity_provider.c.
References INIT, return_false(), and return_null().
Referenced by unity_plugin_create().
 {
     private_unity_provider_t *this;
     INIT(this,
         .public = {
             .provider = {
                 .acquire_address = (void*)return_null,
                 .release_address = (void*)return_false,
                 .create_attribute_enumerator = _create_attribute_enumerator,
             },
             .destroy = _destroy,
         },
     );
     return &this->public;
 }