strongSwan: pkcs12_decode.c File Reference
pkcs12_decode.c File Reference
#include "pkcs12_decode.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <credentials/sets/mem_cred.h>
Classes
struct private_pkcs12_t
Macros
#define CERT_BAG_ID 1
#define CERT_BAG_VALUE 2
#define SAFE_BAG_ID 2
#define SAFE_BAG_VALUE 3
#define AUTHENTICATED_SAFE_DATA 1
#define DIGEST_INFO_ALGORITHM 1
#define DIGEST_INFO_DIGEST 2
#define PFX_AUTH_SAFE 2
#define PFX_MAC 4
#define PFX_SALT 5
#define PFX_ITERATIONS 6
Typedefs
typedef struct private_pkcs12_t private_pkcs12_t
Functions
METHOD (container_t, get_type, container_type_t, private_pkcs12_t *this)
METHOD (container_t, get_data, bool, private_pkcs12_t *this, chunk_t *data)
METHOD (container_t, get_encoding, bool, private_pkcs12_t *this, chunk_t *encoding)
METHOD (pkcs12_t, create_cert_enumerator, enumerator_t *, private_pkcs12_t *this)
METHOD (pkcs12_t, create_key_enumerator, enumerator_t *, private_pkcs12_t *this)
METHOD (container_t, destroy, void, private_pkcs12_t *this)
static private_pkcs12_t * pkcs12_create ()
static bool add_certificate (private_pkcs12_t *this, int level0, chunk_t blob)
static bool parse_safe_contents (private_pkcs12_t *this, int level0, chunk_t blob)
static bool parse_authenticated_safe (private_pkcs12_t *this, chunk_t blob)
static bool verify_mac (hash_algorithm_t hash, chunk_t salt, u_int64_t iterations, chunk_t data, chunk_t mac)
static bool parse_digest_info (chunk_t blob, int level0, hash_algorithm_t *hash, chunk_t *digest)
static bool parse_PFX (private_pkcs12_t *this, chunk_t blob)
pkcs12_t * pkcs12_decode (container_type_t type, va_list args)
Variables
static const asn1Object_t certBagObjects []
static const asn1Object_t safeContentsObjects []
static const asn1Object_t authenticatedSafeObjects []
static const asn1Object_t digestInfoObjects []
static const asn1Object_t PFXObjects []
Macro Definition Documentation
#define AUTHENTICATED_SAFE_DATA 1
Definition at line 260 of file pkcs12_decode.c.
Referenced by parse_authenticated_safe().
#define CERT_BAG_ID 1
Definition at line 114 of file pkcs12_decode.c.
Referenced by add_certificate().
#define CERT_BAG_VALUE 2
Definition at line 115 of file pkcs12_decode.c.
Referenced by add_certificate().
#define DIGEST_INFO_ALGORITHM 1
Definition at line 379 of file pkcs12_decode.c.
Referenced by parse_digest_info().
#define DIGEST_INFO_DIGEST 2
Definition at line 380 of file pkcs12_decode.c.
Referenced by parse_digest_info().
#define PFX_AUTH_SAFE 2
Definition at line 437 of file pkcs12_decode.c.
Referenced by parse_PFX().
#define PFX_ITERATIONS 6
Definition at line 440 of file pkcs12_decode.c.
Referenced by parse_PFX().
#define PFX_MAC 4
Definition at line 438 of file pkcs12_decode.c.
Referenced by parse_PFX().
#define PFX_SALT 5
Definition at line 439 of file pkcs12_decode.c.
Referenced by parse_PFX().
#define SAFE_BAG_ID 2
Definition at line 184 of file pkcs12_decode.c.
Referenced by parse_safe_contents().
#define SAFE_BAG_VALUE 3
Definition at line 185 of file pkcs12_decode.c.
Referenced by parse_safe_contents().
Typedef Documentation
typedef struct private_pkcs12_t private_pkcs12_t
Definition at line 24 of file pkcs12_decode.c.
Function Documentation
static bool add_certificate (private_pkcs12_t * this, int level0, chunk_t blob) static
Parse a CertBag structure and extract certificate
Definition at line 120 of file pkcs12_decode.c.
References mem_cred_t::add_cert, asn1_known_oid(), ASN1_OCTET_STRING, asn1_parse_simple_object(), asn1_parser_create(), BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_BAG_ID, CERT_BAG_VALUE, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, creds, library_t::creds, DBG2, DBG_ASN, asn1_parser_t::destroy, FALSE, asn1_parser_t::get_level, asn1_parser_t::iterate, lib, OID_UNKNOWN, OID_X509_CERTIFICATE, parser, asn1_parser_t::set_top_level, and asn1_parser_t::success.
Referenced by parse_safe_contents().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int oid = OID_UNKNOWN;
     bool success = FALSE;
     parser = asn1_parser_create(certBagObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case CERT_BAG_ID:
                 oid = asn1_known_oid(object);
                 break;
             case CERT_BAG_VALUE:
             {
                 if (oid == OID_X509_CERTIFICATE &&
                     asn1_parse_simple_object(&object, ASN1_OCTET_STRING,
                                 parser->get_level(parser)+1, "x509Certificate"))
                 {
                     certificate_t *cert;
                     DBG2(DBG_ASN, "-- > parsing certificate from PKCS#12");
                     cert = lib->creds->create(lib->creds,
                                               CRED_CERTIFICATE, CERT_X509,
                                               BUILD_BLOB_ASN1_DER, object,
                                               BUILD_END);
                     if (cert)
                     {
                         this->creds->add_cert(this->creds, FALSE, cert);
                         DBG2(DBG_ASN, "-- < --");
                     }
                     else
                     {
                         DBG2(DBG_ASN, "-- < failed parsing certificate from "
                              "PKCS#12");
                     }
                 }
                 break;
             }
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     return success;
 }
METHOD (container_t , get_type , container_type_t , private_pkcs12_t * this)
Definition at line 42 of file pkcs12_decode.c.
References CONTAINER_PKCS12.
 {
     return CONTAINER_PKCS12;
 }
METHOD (container_t , get_data , bool , private_pkcs12_t * this, chunk_t * data)
Definition at line 48 of file pkcs12_decode.c.
References FALSE.
 {
     /* we could return the content of the outer-most PKCS#7 container (authSafe)
      * don't really see the point though */
     return FALSE;
 }
METHOD (container_t , get_encoding , bool , private_pkcs12_t * this, chunk_t * encoding)
Definition at line 56 of file pkcs12_decode.c.
References FALSE.
 {
     /* similar to get_data() we don't have any use for it at the moment */
     return FALSE;
 }
METHOD (pkcs12_t , create_cert_enumerator , enumerator_t * , private_pkcs12_t * this)
Definition at line 63 of file pkcs12_decode.c.
References CERT_ANY, credential_set_t::create_cert_enumerator, creds, FALSE, KEY_ANY, and mem_cred_t::set.
 {
     return this->creds->set.create_cert_enumerator(&this->creds->set, CERT_ANY,
                                                    KEY_ANY, NULL, FALSE);
 }
METHOD (pkcs12_t , create_key_enumerator , enumerator_t * , private_pkcs12_t * this)
Definition at line 70 of file pkcs12_decode.c.
References credential_set_t::create_private_enumerator, creds, KEY_ANY, and mem_cred_t::set.
 {
     return this->creds->set.create_private_enumerator(&this->creds->set,
                                                       KEY_ANY, NULL);
 }
METHOD (container_t , destroy , void , private_pkcs12_t * this)
Definition at line 77 of file pkcs12_decode.c.
References creds, mem_cred_t::destroy, and free().
 {
     this->creds->destroy(this->creds);
     free(this);
 }
static bool parse_authenticated_safe (private_pkcs12_t * this, chunk_t blob) static
Parse an AuthenticatedSafe structure
Definition at line 265 of file pkcs12_decode.c.
References asn1_parser_create(), AUTHENTICATED_SAFE_DATA, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_free(), CONTAINER_PKCS7, CONTAINER_PKCS7_DATA, CONTAINER_PKCS7_ENCRYPTED_DATA, CONTAINER_PKCS7_ENVELOPED_DATA, credential_factory_t::create, CRED_CONTAINER, library_t::creds, data, container_t::destroy, asn1_parser_t::destroy, end, FALSE, container_t::get_data, asn1_parser_t::get_level, container_t::get_type, asn1_parser_t::iterate, lib, parse_safe_contents(), parser, and asn1_parser_t::success.
Referenced by parse_PFX().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool success = FALSE;
     parser = asn1_parser_create(authenticatedSafeObjects, blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case AUTHENTICATED_SAFE_DATA:
             {
                 container_t *container;
                 chunk_t data;
                 container = lib->creds->create(lib->creds, CRED_CONTAINER,
                                         CONTAINER_PKCS7, BUILD_BLOB_ASN1_DER,
                                         object, BUILD_END);
                 if (!container)
                 {
                     goto end;
                 }
                 switch (container->get_type(container))
                 {
                     case CONTAINER_PKCS7_DATA:
                     case CONTAINER_PKCS7_ENCRYPTED_DATA:
                     case CONTAINER_PKCS7_ENVELOPED_DATA:
                         if (container->get_data(container, &data))
{
                             break;
                         }
                         /* fall-through */
                     default:
                         container->destroy(container);
                         goto end;
                 }
                 container->destroy(container);
                 if (!parse_safe_contents(this, parser->get_level(parser)+1,
                                          data))
                 {
                     chunk_free(&data);
                     goto end;
                 }
                 chunk_free(&data);
                 break;
             }
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     return success;
 }
static bool parse_digest_info (chunk_t blob, int level0, hash_algorithm_t * hash, chunk_t * digest) static
Parse a digestInfo structure
Definition at line 385 of file pkcs12_decode.c.
References asn1_parse_algorithmIdentifier(), asn1_parser_create(), asn1_parser_t::destroy, DIGEST_INFO_ALGORITHM, DIGEST_INFO_DIGEST, asn1_parser_t::get_level, hasher_algorithm_from_oid(), asn1_parser_t::iterate, parser, asn1_parser_t::set_top_level, and asn1_parser_t::success.
Referenced by parse_PFX().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool success;
     parser = asn1_parser_create(digestInfoObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case DIGEST_INFO_ALGORITHM:
             {
                 int oid = asn1_parse_algorithmIdentifier(object,
                                      parser->get_level(parser)+1, NULL);
                 *hash = hasher_algorithm_from_oid(oid);
                 break;
             }
             case DIGEST_INFO_DIGEST:
             {
                 *digest = object;
                 break;
             }
             default:
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     return success;
 }
static bool parse_PFX (private_pkcs12_t * this, chunk_t blob) static
Parse an ASN.1 encoded PFX structure
Definition at line 445 of file pkcs12_decode.c.
References asn1_parse_integer_uint64(), asn1_parser_create(), BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, chunk_free(), CONTAINER_PKCS7, CONTAINER_PKCS7_DATA, CONTAINER_PKCS7_SIGNED_DATA, credential_factory_t::create, container_t::create_signature_enumerator, CRED_CONTAINER, library_t::creds, data, DBG1, DBG2, DBG_ASN, enumerator_t::destroy, asn1_parser_t::destroy, DESTROY_IF, end, enumerator_t::enumerate, FALSE, container_t::get_data, asn1_parser_t::get_level, container_t::get_type, hash, HASH_UNKNOWN, asn1_parser_t::iterate, lib, parse_authenticated_safe(), parse_digest_info(), parser, PFX_AUTH_SAFE, PFX_ITERATIONS, PFX_MAC, PFX_SALT, salt, asn1_parser_t::success, and verify_mac().
Referenced by pkcs12_decode().
 {
     asn1_parser_t *parser;
     int objectID;
     chunk_t object, auth_safe, digest = chunk_empty, salt = chunk_empty,
             data = chunk_empty;
     hash_algorithm_t hash = HASH_UNKNOWN;
     container_t *container = NULL;
     u_int64_t iterations = 0;
     bool success = FALSE;
     parser = asn1_parser_create(PFXObjects, blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case PFX_AUTH_SAFE:
             {
                 auth_safe = object;
                 break;
             }
             case PFX_MAC:
             {
                 if (!parse_digest_info(object, parser->get_level(parser)+1,
                                        &hash, &digest))
                 {
                     goto end_parse;
                 }
                 break;
             }
             case PFX_SALT:
             {
                 salt = object;
                 break;
             }
             case PFX_ITERATIONS:
             {
                 iterations = object.len ? asn1_parse_integer_uint64(object) : 1;
                 break;
             }
         }
     }
     success = parser->success(parser);
 end_parse:
     parser->destroy(parser);
     if (!success)
     {
         return FALSE;
     }
     success = FALSE;
     DBG2(DBG_ASN, "-- > --");
     container = lib->creds->create(lib->creds, CRED_CONTAINER, CONTAINER_PKCS7,
                                    BUILD_BLOB_ASN1_DER, auth_safe, BUILD_END);
     if (container && container->get_data(container, &data))
     {
         if (hash != HASH_UNKNOWN)
         {
             if (container->get_type(container) != CONTAINER_PKCS7_DATA)
             {
                 goto end;
             }
             if (!verify_mac(hash, salt, iterations, data, digest))
             {
                 DBG1(DBG_ASN, "  MAC verification of PKCS#12 container failed");
                 goto end;
             }
         }
         else
         {
             enumerator_t *enumerator;
             auth_cfg_t *auth;
             if (container->get_type(container) != CONTAINER_PKCS7_SIGNED_DATA)
             {
                 goto end;
             }
             enumerator = container->create_signature_enumerator(container);
             if (!enumerator->enumerate(enumerator, &auth))
             {
                 DBG1(DBG_ASN, "  signature verification of PKCS#12 container "
                      "failed");
                 enumerator->destroy(enumerator);
                 goto end;
             }
             enumerator->destroy(enumerator);
         }
         success = parse_authenticated_safe(this, data);
     }
 end:
     DBG2(DBG_ASN, "-- < --");
     DESTROY_IF(container);
     chunk_free(&data);
     return success;
 }
static bool parse_safe_contents (private_pkcs12_t * this, int level0, chunk_t blob) static
Parse a SafeContents structure and extract credentials
Definition at line 190 of file pkcs12_decode.c.
References add_certificate(), mem_cred_t::add_key, asn1_known_oid(), asn1_parser_create(), BUILD_BLOB_ASN1_DER, BUILD_END, credential_factory_t::create, CRED_PRIVATE_KEY, creds, library_t::creds, DBG2, DBG_ASN, asn1_parser_t::destroy, FALSE, asn1_parser_t::get_level, asn1_parser_t::iterate, key, KEY_ANY, lib, OID_P12_CERT_BAG, OID_P12_KEY_BAG, OID_P12_PKCS8_KEY_BAG, OID_UNKNOWN, parser, SAFE_BAG_ID, SAFE_BAG_VALUE, asn1_parser_t::set_top_level, and asn1_parser_t::success.
Referenced by parse_authenticated_safe().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int oid = OID_UNKNOWN;
     bool success = FALSE;
     parser = asn1_parser_create(safeContentsObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case SAFE_BAG_ID:
                 oid = asn1_known_oid(object);
                 break;
             case SAFE_BAG_VALUE:
             {
                 switch (oid)
                 {
                     case OID_P12_CERT_BAG:
                     {
                         add_certificate(this, parser->get_level(parser)+1,
                                         object);
                         break;
                     }
                     case OID_P12_KEY_BAG:
                     case OID_P12_PKCS8_KEY_BAG:
                     {
                         private_key_t *key;
                         DBG2(DBG_ASN, "-- > parsing private key from PKCS#12");
                         key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY,
                                         KEY_ANY, BUILD_BLOB_ASN1_DER, object,
                                         BUILD_END);
                         if (key)
{
                             this->creds->add_key(this->creds, key);
                             DBG2(DBG_ASN, "-- < --");
                         }
                         else
{
                             DBG2(DBG_ASN, "-- < failed parsing private key "
                                  "from PKCS#12");
                         }
                     }
                     default:
                         break;
                 }
                 break;
             }
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     return success;
 }
static private_pkcs12_t* pkcs12_create () static
Definition at line 84 of file pkcs12_decode.c.
References creds, destroy(), enumerator_create_empty(), INIT, and mem_cred_create().
Referenced by pkcs12_decode().
 {
     private_pkcs12_t *this;
     INIT(this,
         .public = {
             .container = {
                 .get_type = _get_type,
                 .create_signature_enumerator = (void*)enumerator_create_empty,
                 .get_data = _get_data,
                 .get_encoding = _get_encoding,
                 .destroy = _destroy,
             },
             .create_cert_enumerator = _create_cert_enumerator,
             .create_key_enumerator = _create_key_enumerator,
         },
         .creds = mem_cred_create(),
     );
     return this;
 }
static bool verify_mac (hash_algorithm_t hash, chunk_t salt, u_int64_t iterations, chunk_t data, chunk_t mac) static
Verify the given MAC with available passwords.
Definition at line 326 of file pkcs12_decode.c.
References chunk_alloca, chunk_equals_const(), credential_manager_t::create_shared_enumerator, crypto_factory_t::create_signer, library_t::credmgr, library_t::crypto, signer_t::destroy, FALSE, signer_t::get_block_size, shared_key_t::get_key, signer_t::get_key_size, signer_t::get_signature, hasher_algorithm_to_integrity(), integ, key, chunk_t::len, lib, pkcs12_derive_key(), PKCS12_KEY_MAC, chunk_t::ptr, salt, signer_t::set_key, SHARED_PRIVATE_KEY_PASS, signer, and TRUE.
Referenced by parse_PFX().
 {
     integrity_algorithm_t integ;
     enumerator_t *enumerator;
     shared_key_t *shared;
     signer_t *signer;
     chunk_t key, calculated;
     bool success = FALSE;
     integ = hasher_algorithm_to_integrity(hash, mac.len);
     signer = lib->crypto->create_signer(lib->crypto, integ);
     if (!signer)
     {
         return FALSE;
     }
     key = chunk_alloca(signer->get_key_size(signer));
     calculated = chunk_alloca(signer->get_block_size(signer));
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                         SHARED_PRIVATE_KEY_PASS, NULL, NULL);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         if (!pkcs12_derive_key(hash, shared->get_key(shared), salt, iterations,
                                PKCS12_KEY_MAC, key))
         {
             break;
         }
         if (!signer->set_key(signer, key) ||
             !signer->get_signature(signer, data, calculated.ptr))
         {
             break;
         }
         if (chunk_equals_const(mac, calculated))
         {
             success = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     signer->destroy(signer);
     return success;
 }
Variable Documentation
const asn1Object_t authenticatedSafeObjects[] static
Initial value:
= {
    { 0, "AuthenticatedSafe",   ASN1_SEQUENCE,  ASN1_LOOP   },
    { 1,   "ContentInfo",       ASN1_SEQUENCE,  ASN1_OBJ    },
    { 0, "end loop",            ASN1_EOC,       ASN1_END    },
    { 0, "exit",                ASN1_EOC,       ASN1_EXIT   }
}
ASN.1 definition of an AuthenticatedSafe structure
Definition at line 254 of file pkcs12_decode.c.
const asn1Object_t certBagObjects[] static
Initial value:
= {
    { 0, "CertBag",         ASN1_SEQUENCE,      ASN1_BODY           },
    { 1,   "certId",        ASN1_OID,           ASN1_BODY           },
    { 1,   "certValue",     ASN1_CONTEXT_C_0,   ASN1_BODY           },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of an CertBag structure
Definition at line 108 of file pkcs12_decode.c.
const asn1Object_t digestInfoObjects[] static
Initial value:
= {
    { 0, "digestInfo",          ASN1_SEQUENCE,      ASN1_OBJ    },
    { 1,   "digestAlgorithm",   ASN1_EOC,           ASN1_RAW    },
    { 1,   "digest",            ASN1_OCTET_STRING,  ASN1_BODY   },
    { 0, "exit",                ASN1_EOC,           ASN1_EXIT   }
}
ASN.1 definition of digestInfo
Definition at line 373 of file pkcs12_decode.c.
const asn1Object_t PFXObjects[] static
Initial value:
= {
    { 0, "PFX",             ASN1_SEQUENCE,      ASN1_NONE           },
    { 1,   "version",       ASN1_INTEGER,       ASN1_BODY           },
    { 1,   "authSafe",      ASN1_SEQUENCE,      ASN1_OBJ            },
    { 1,   "macData",       ASN1_SEQUENCE,      ASN1_OPT|ASN1_BODY  },
    { 2,     "mac",         ASN1_SEQUENCE,      ASN1_RAW            },
    { 2,     "macSalt",     ASN1_OCTET_STRING,  ASN1_BODY           },
    { 2,     "iterations",  ASN1_INTEGER,       ASN1_DEF|ASN1_BODY  },
    { 1,   "end opt",       ASN1_EOC,           ASN1_END            },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of a PFX structure
Definition at line 426 of file pkcs12_decode.c.
const asn1Object_t safeContentsObjects[] static
Initial value:
= {
    { 0, "SafeContents",    ASN1_SEQUENCE,      ASN1_LOOP           },
    { 1,   "SafeBag",       ASN1_SEQUENCE,      ASN1_BODY           },
    { 2,     "bagId",       ASN1_OID,           ASN1_BODY           },
    { 2,     "bagValue",    ASN1_CONTEXT_C_0,   ASN1_BODY           },
    { 2,     "bagAttr",     ASN1_SET,           ASN1_OPT|ASN1_RAW   },
    { 2,     "end opt",     ASN1_EOC,           ASN1_END            },
    { 0, "end loop",        ASN1_EOC,           ASN1_END            },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of an AuthenticatedSafe structure
Definition at line 174 of file pkcs12_decode.c.