strongSwan: vici_message
vici_message
vici
Classes
struct vici_message_t
Typedefs
typedef struct vici_message_t vici_message_t
typedef struct vici_parse_context_t vici_parse_context_t
typedef enum vici_type_t vici_type_t
typedef bool(* vici_value_cb_t)(void *user, vici_message_t *message, char *name, chunk_t value)
typedef bool(* vici_section_cb_t)(void *user, vici_message_t *message, vici_parse_context_t *ctx, char *name)
Enumerations
enum vici_type_t {
VICI_START = 0, VICI_SECTION_START = 1, VICI_SECTION_END = 2, VICI_KEY_VALUE = 3,
VICI_LIST_START = 4, VICI_LIST_ITEM = 5, VICI_LIST_END = 6, VICI_END = 7
}
Functions
vici_message_t * vici_message_create_from_data (chunk_t data, bool cleanup)
vici_message_t * vici_message_create_from_enumerator (enumerator_t *enumerator)
vici_message_t * vici_message_create_from_args (vici_type_t type,...)
bool vici_stringify (chunk_t chunk, char *buf, size_t size)
bool vici_verify_type (vici_type_t type, u_int section, bool list)
Variables
enum_name_t * vici_type_names
Detailed Description
Typedef Documentation
typedef struct vici_message_t vici_message_t
Definition at line 29 of file vici_message.h.
typedef struct vici_parse_context_t vici_parse_context_t
Definition at line 30 of file vici_message.h.
typedef bool(* vici_section_cb_t)(void *user, vici_message_t *message, vici_parse_context_t *ctx, char *name)
Callback function for sections, invoked by parse().
Parameters
user user data, as passed to parse()
message message currently parsing
ctx parse context, to pass to recursive parse() invocations.
name name of the section
Returns
TRUE if parsed successfully
Definition at line 78 of file vici_message.h.
typedef enum vici_type_t vici_type_t
Definition at line 31 of file vici_message.h.
typedef bool(* vici_value_cb_t)(void *user, vici_message_t *message, char *name, chunk_t value)
Callback function for key/value and list items, invoked by parse().
Parameters
user user data, as passed to parse()
message message currently parsing
name name of key or list
value parsed value
Returns
TRUE if parsed successfully
Definition at line 66 of file vici_message.h.
Enumeration Type Documentation
enum vici_type_t
Vici message encoding types
Enumerator
VICI_START
never used in an argument list, needed by dump as initial value
VICI_SECTION_START
begin of new section, argument is section name as char*
VICI_SECTION_END
end of current section, no arguments
VICI_KEY_VALUE
key/value, arguments are key as char*, value as chunk_t
VICI_LIST_START
list start, argument is list name as char*
VICI_LIST_ITEM
list item, argument is item value as chunk_t
VICI_LIST_END
end of list, no arguments
VICI_END
end of argument list, no arguments (never encoded)
Definition at line 36 of file vici_message.h.
                  {
     VICI_START =         0,
     VICI_SECTION_START = 1,
     VICI_SECTION_END =   2,
     VICI_KEY_VALUE =     3,
     VICI_LIST_START =    4,
     VICI_LIST_ITEM =     5,
     VICI_LIST_END =      6,
     VICI_END =           7
 };
Function Documentation
vici_message_t* vici_message_create_from_args (vici_type_t type, ...)
Create vici message from a variable argument list.
Parameters
type first type beginning message
... vici_type_t and args, terminated by VICI_END
Returns
message representation, NULL on error
See header
Definition at line 734 of file vici_message.c.
References vici_builder_t::add, vici_builder_t::finalize, name, value, vici_builder_create(), VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_SECTION_END, and VICI_SECTION_START.
Referenced by build_getter_msg(), CALLBACK(), and START_TEST().
 {
     vici_builder_t *builder;
     va_list args;
     char *name;
     chunk_t value;
     builder = vici_builder_create();
     va_start(args, type);
     while (type != VICI_END)
     {
         switch (type)
         {
             case VICI_LIST_START:
             case VICI_SECTION_START:
                 name = va_arg(args, char*);
                 builder->add(builder, type, name);
                 break;
             case VICI_KEY_VALUE:
                 name = va_arg(args, char*);
                 value = va_arg(args, chunk_t);
                 builder->add(builder, type, name, value);
                 break;
             case VICI_LIST_ITEM:
                 value = va_arg(args, chunk_t);
                 builder->add(builder, type, value);
                 break;
             case VICI_SECTION_END:
             case VICI_LIST_END:
             default:
                 builder->add(builder, type);
                 break;
         }
         type = va_arg(args, vici_type_t);
     }
     va_end(args);
     return builder->finalize(builder);
 }
vici_message_t* vici_message_create_from_data (chunk_t data, bool cleanup)
Create a vici_message from encoded data.
Parameters
data message encoding
cleanup TRUE to free data during
Returns
message representation
See header
Definition at line 663 of file vici_message.c.
References cleanup, data, INIT, and linked_list_create().
Referenced by handle_event(), METHOD(), process_request(), START_TEST(), and vici_submit().
 {
     private_vici_message_t *this;
     INIT(this,
         .public = {
             .create_enumerator = _create_enumerator,
             .get_str = _get_str,
             .vget_str = _vget_str,
             .get_int = _get_int,
             .vget_int = _vget_int,
             .get_bool = _get_bool,
             .vget_bool = _vget_bool,
             .get_value = _get_value,
             .vget_value = _vget_value,
             .get_encoding = _get_encoding,
             .parse = _parse,
             .dump = _dump,
             .destroy = _destroy,
         },
         .strings = linked_list_create(),
         .encoding = data,
         .cleanup = cleanup,
     );
     return &this->public;
 }
vici_message_t* vici_message_create_from_enumerator (enumerator_t * enumerator)
Create a vici_message from an enumerator.
The enumerator uses the same signature as the enumerator returned by create_enumerator(), and gets destroyed by this function. It should return VICI_END to close the message, return FALSE to indicate a failure.
Parameters
enumerator enumerator over (vici_type_t, char*, chunk_t)
Returns
message representation, NULL on error
See header
Definition at line 694 of file vici_message.c.
References vici_builder_t::add, enumerator_t::destroy, enumerator_t::enumerate, vici_builder_t::finalize, name, type, value, vici_builder_create(), VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_SECTION_END, and VICI_SECTION_START.
Referenced by echo_cb(), and START_TEST().
 {
     vici_builder_t *builder;
     vici_type_t type;
     char *name;
     chunk_t value;
     builder = vici_builder_create();
     while (enumerator->enumerate(enumerator, &type, &name, &value))
     {
         switch (type)
         {
             case VICI_SECTION_START:
             case VICI_LIST_START:
                 builder->add(builder, type, name);
                 continue;
             case VICI_KEY_VALUE:
                 builder->add(builder, type, name, value);
                 continue;
             case VICI_LIST_ITEM:
                 builder->add(builder, type, value);
                 continue;
             case VICI_SECTION_END:
             case VICI_LIST_END:
             default:
                 builder->add(builder, type);
                 continue;
             case VICI_END:
                 break;
         }
         break;
     }
     enumerator->destroy(enumerator);
     return builder->finalize(builder);
 }
bool vici_stringify (chunk_t chunk, char * buf, size_t size)
Check if a chunk has a printable string, and print it to buf.
Parameters
chunk chunk containing potential string
buf buffer to write string to
size size of buf
Returns
TRUE if printable and string written to buf
See header.
Definition at line 69 of file vici_message.c.
References chunk_printable(), FALSE, chunk_t::len, chunk_t::ptr, snprintf, and TRUE.
Referenced by CALLBACK(), METHOD(), parse_id(), parse_map(), and parse_proposal().
 {
     if (!chunk_printable(chunk, NULL, 0))
     {
         return FALSE;
     }
     snprintf(buf, size, "%.*s", (int)chunk.len, chunk.ptr);
     return TRUE;
 }
bool vici_verify_type (vici_type_t type, u_int section, bool list)
Verify the occurrence of a given type for given section/list nesting
See header.
Definition at line 82 of file vici_message.c.
References DBG1, DBG_ENC, FALSE, TRUE, VICI_END, VICI_LIST_END, VICI_LIST_ITEM, VICI_SECTION_END, and vici_type_names.
Referenced by METHOD().
 {
     if (list)
     {
         if (type != VICI_LIST_END && type != VICI_LIST_ITEM)
         {
             DBG1(DBG_ENC, "'%N' within list", vici_type_names, type);
             return FALSE;
         }
     }
     else
     {
         if (type == VICI_LIST_ITEM || type == VICI_LIST_END)
         {
             DBG1(DBG_ENC, "'%N' outside list", vici_type_names, type);
             return FALSE;
         }
     }
     if (type == VICI_SECTION_END && section == 0)
     {
         DBG1(DBG_ENC, "'%N' outside of section", vici_type_names, type);
         return FALSE;
     }
     if (type == VICI_END)
     {
         if (section)
         {
             DBG1(DBG_ENC, "'%N' within section", vici_type_names, type);
             return FALSE;
         }
         if (list)
         {
             DBG1(DBG_ENC, "'%N' within list", vici_type_names, type);
             return FALSE;
         }
     }
     return TRUE;
 }
Variable Documentation
enum_name_t* vici_type_names
Names for vici encoding types
Referenced by METHOD(), and vici_verify_type().