strongSwan: stroke_cred.c File Reference
stroke_cred.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <limits.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include "stroke_cred.h"
#include <credentials/certificates/x509.h>
#include <credentials/certificates/crl.h>
#include <credentials/certificates/ac.h>
#include <credentials/containers/pkcs12.h>
#include <credentials/sets/mem_cred.h>
#include <credentials/sets/callback_cred.h>
#include <collections/linked_list.h>
#include <utils/lexparser.h>
#include <threading/rwlock.h>
#include <daemon.h>
Classes
struct private_stroke_cred_t
struct passphrase_cb_data_t
struct pin_cb_data_t
Macros
#define CONFIG_DIR IPSEC_CONFDIR
#define IPSEC_D_DIR CONFIG_DIR "/ipsec.d"
#define PRIVATE_KEY_DIR IPSEC_D_DIR "/private"
#define CERTIFICATE_DIR IPSEC_D_DIR "/certs"
#define CA_CERTIFICATE_DIR IPSEC_D_DIR "/cacerts"
#define AA_CERTIFICATE_DIR IPSEC_D_DIR "/aacerts"
#define ATTR_CERTIFICATE_DIR IPSEC_D_DIR "/acerts"
#define OCSP_CERTIFICATE_DIR IPSEC_D_DIR "/ocspcerts"
#define CRL_DIR IPSEC_D_DIR "/crls"
#define SECRETS_FILE CONFIG_DIR "/ipsec.secrets"
#define MAX_SECRETS_RECURSION 10
#define SC_PART_LEN 128
Typedefs
typedef struct
private_stroke_cred_t private_stroke_cred_t
Enumerations
enum smartcard_format_t { SC_FORMAT_SLOT_MODULE_KEYID, SC_FORMAT_SLOT_KEYID, SC_FORMAT_KEYID, SC_FORMAT_INVALID }
Functions
static smartcard_format_t parse_smartcard (char *smartcard, u_int *slot, char *module, char *keyid)
static certificate_t * load_from_smartcard (smartcard_format_t format, u_int slot, char *module, char *keyid, credential_type_t type, int subtype)
METHOD (stroke_cred_t, load_peer, certificate_t *, private_stroke_cred_t *this, char *filename)
METHOD (stroke_cred_t, load_pubkey, certificate_t *, private_stroke_cred_t *this, char *filename, identification_t *identity)
static certificate_t * load_ca_cert (char *filename, bool force_ca_cert)
certificate_t * stroke_load_ca_cert (char *filename)
static void load_x509_ca (private_stroke_cred_t *this, char *file, mem_cred_t *creds)
static void load_x509_aa (private_stroke_cred_t *this, char *file, mem_cred_t *creds)
static void load_x509 (private_stroke_cred_t *this, char *file, x509_flag_t flag, mem_cred_t *creds)
static void load_x509_crl (private_stroke_cred_t *this, char *file, mem_cred_t *creds)
static void load_x509_ac (private_stroke_cred_t *this, char *file, mem_cred_t *creds)
static void load_certdir (private_stroke_cred_t *this, char *path, certificate_type_t type, x509_flag_t flag, mem_cred_t *creds)
METHOD (stroke_cred_t, cache_cert, void, private_stroke_cred_t *this, certificate_t *cert)
METHOD (stroke_cred_t, cachecrl, void, private_stroke_cred_t *this, bool enabled)
static err_t extract_secret (chunk_t *secret, chunk_t *line)
static shared_key_t * passphrase_cb (passphrase_cb_data_t *data, shared_key_type_t type, identification_t *me, identification_t *other, id_match_t *match_me, id_match_t *match_other)
static shared_key_t * pin_cb (pin_cb_data_t *data, shared_key_type_t type, identification_t *me, identification_t *other, id_match_t *match_me, id_match_t *match_other)
static bool load_pin (mem_cred_t *secrets, chunk_t line, int line_nr, FILE *prompt)
static bool load_from_file (chunk_t line, int line_nr, FILE *prompt, char *path, int type, int subtype, void **result)
static bool load_private (mem_cred_t *secrets, chunk_t line, int line_nr, FILE *prompt, key_type_t key_type)
static bool load_pkcs12 (private_stroke_cred_t *this, mem_cred_t *secrets, chunk_t line, int line_nr, FILE *prompt)
static bool load_shared (mem_cred_t *secrets, chunk_t line, int line_nr, shared_key_type_t type, chunk_t ids)
static void load_secrets (private_stroke_cred_t *this, mem_cred_t *secrets, char *file, int level, FILE *prompt)
static void load_certs (private_stroke_cred_t *this)
METHOD (stroke_cred_t, reread, void, private_stroke_cred_t *this, stroke_msg_t *msg, FILE *prompt)
METHOD (stroke_cred_t, add_shared, void, private_stroke_cred_t *this, shared_key_t *shared, linked_list_t *owners)
METHOD (stroke_cred_t, destroy, void, private_stroke_cred_t *this)
stroke_cred_t * stroke_cred_create (stroke_ca_t *ca)
Macro Definition Documentation
#define AA_CERTIFICATE_DIR IPSEC_D_DIR "/aacerts"
Definition at line 47 of file stroke_cred.c.
Referenced by load_certs(), and METHOD().
#define ATTR_CERTIFICATE_DIR IPSEC_D_DIR "/acerts"
Definition at line 48 of file stroke_cred.c.
Referenced by load_certs(), and METHOD().
#define CA_CERTIFICATE_DIR IPSEC_D_DIR "/cacerts"
Definition at line 46 of file stroke_cred.c.
Referenced by load_ca_cert(), load_certs(), and METHOD().
#define CERTIFICATE_DIR IPSEC_D_DIR "/certs"
Definition at line 45 of file stroke_cred.c.
Referenced by METHOD().
#define CONFIG_DIR IPSEC_CONFDIR
Definition at line 42 of file stroke_cred.c.
#define CRL_DIR IPSEC_D_DIR "/crls"
Definition at line 50 of file stroke_cred.c.
Referenced by load_certs(), and METHOD().
#define IPSEC_D_DIR CONFIG_DIR "/ipsec.d"
Definition at line 43 of file stroke_cred.c.
#define MAX_SECRETS_RECURSION 10
Definition at line 53 of file stroke_cred.c.
Referenced by load_secrets().
#define OCSP_CERTIFICATE_DIR IPSEC_D_DIR "/ocspcerts"
Definition at line 49 of file stroke_cred.c.
Referenced by load_certs(), and METHOD().
#define PRIVATE_KEY_DIR IPSEC_D_DIR "/private"
Definition at line 44 of file stroke_cred.c.
Referenced by load_from_file().
#define SC_PART_LEN 128
Length of smartcard specifier parts (module, keyid)
Definition at line 100 of file stroke_cred.c.
Referenced by load_ca_cert(), load_pin(), METHOD(), and parse_smartcard().
#define SECRETS_FILE CONFIG_DIR "/ipsec.secrets"
Definition at line 51 of file stroke_cred.c.
Referenced by stroke_cred_create().
Typedef Documentation
typedef struct private_stroke_cred_t private_stroke_cred_t
Definition at line 55 of file stroke_cred.c.
Enumeration Type Documentation
enum smartcard_format_t
Kind of smartcard specifier token
Enumerator
SC_FORMAT_SLOT_MODULE_KEYID
SC_FORMAT_SLOT_KEYID
SC_FORMAT_KEYID
SC_FORMAT_INVALID
Definition at line 105 of file stroke_cred.c.
              {
     SC_FORMAT_SLOT_MODULE_KEYID,
     SC_FORMAT_SLOT_KEYID,
     SC_FORMAT_KEYID,
     SC_FORMAT_INVALID,
 } smartcard_format_t;
Function Documentation
static err_t extract_secret (chunk_t * secret, chunk_t * line) static
Convert a string of characters into a binary secret A string between single or double quotes is treated as ASCII characters A string prepended by 0x is treated as HEX and prepended by 0s as Base64
Definition at line 616 of file stroke_cred.c.
References chunk_clone, chunk_from_base64(), chunk_from_hex(), chunk_skip(), eat_whitespace(), extract_token(), FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by load_from_file(), load_pin(), and load_shared().
 {
     chunk_t raw_secret;
     char delimiter = ' ';
     bool quotes = FALSE;
     if (!eat_whitespace(line))
     {
         return "missing secret";
     }
     if (*line->ptr == '\'' || *line->ptr == '"')
     {
         quotes = TRUE;
         delimiter = *line->ptr;
         line->ptr++;  line->len--;
     }
     if (!extract_token(&raw_secret, delimiter, line))
     {
         if (delimiter == ' ')
         {
             raw_secret = *line;
         }
         else
         {
             return "missing second delimiter";
         }
     }
     if (quotes)
     {
         /* treat as an ASCII string */
         *secret = chunk_clone(raw_secret);
         return NULL;
     }
     /* treat 0x as hex, 0s as base64 */
     if (raw_secret.len > 2)
     {
         if (strncasecmp("0x", raw_secret.ptr, 2) == 0)
         {
             *secret = chunk_from_hex(chunk_skip(raw_secret, 2), NULL);
             return NULL;
         }
         if (strncasecmp("0s", raw_secret.ptr, 2) == 0)
         {
             *secret = chunk_from_base64(chunk_skip(raw_secret, 2), NULL);
             return NULL;
         }
     }
     *secret = chunk_clone(raw_secret);
     return NULL;
 }
static certificate_t* load_ca_cert (char * filename, bool force_ca_cert) static
Load a CA certificate, optionally force it to be one
Definition at line 325 of file stroke_cred.c.
References BUILD_END, BUILD_FROM_FILE, BUILD_X509_FLAG, CA_CERTIFICATE_DIR, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_CFG, certificate_t::destroy, x509_t::get_flags, certificate_t::get_subject, keyid(), lib, load_from_smartcard(), parse_smartcard(), path, SC_FORMAT_INVALID, SC_PART_LEN, snprintf, strpfx(), and X509_CA.
Referenced by load_x509_ca(), and stroke_load_ca_cert().
 {
     certificate_t *cert = NULL;
     char path[PATH_MAX];
     if (strpfx(filename, "%smartcard"))
     {
         smartcard_format_t format;
         char module[SC_PART_LEN], keyid[SC_PART_LEN];
         u_int slot;
         format = parse_smartcard(filename, &slot, module, keyid);
         if (format != SC_FORMAT_INVALID)
         {
             cert = (certificate_t*)load_from_smartcard(format,
                             slot, module, keyid, CRED_CERTIFICATE, CERT_X509);
         }
     }
     else
     {
         if (*filename == '/')
         {
             snprintf(path, sizeof(path), "%s", filename);
         }
         else
         {
             snprintf(path, sizeof(path), "%s/%s", CA_CERTIFICATE_DIR, filename);
         }
         if (force_ca_cert)
         {   /* we treat this certificate as a CA certificate even if it has no
              * CA basic constraint */
             cert = lib->creds->create(lib->creds,
                                   CRED_CERTIFICATE, CERT_X509,
                                   BUILD_FROM_FILE, path, BUILD_X509_FLAG, X509_CA,
                                   BUILD_END);
         }
         else
         {
             cert = lib->creds->create(lib->creds,
                                   CRED_CERTIFICATE, CERT_X509,
                                   BUILD_FROM_FILE, path,
                                   BUILD_END);
         }
     }
     if (cert)
     {
         x509_t *x509 = (x509_t*)cert;
         if (!(x509->get_flags(x509) & X509_CA))
         {
             DBG1(DBG_CFG, "  ca certificate \"%Y\" lacks ca basic constraint, "
                  "discarded", cert->get_subject(cert));
             cert->destroy(cert);
             return NULL;
         }
         DBG1(DBG_CFG, "  loaded ca certificate \"%Y\" from '%s'",
              cert->get_subject(cert), filename);
         return cert;
     }
     return NULL;
 }
static void load_certdir (private_stroke_cred_t * this, char * path, certificate_type_t type, x509_flag_t flag, mem_cred_t * creds) static
load trusted certificates from a directory
Definition at line 513 of file stroke_cred.c.
References CERT_X509, CERT_X509_AC, CERT_X509_CRL, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_directory(), load_x509(), load_x509_aa(), load_x509_ac(), load_x509_ca(), load_x509_crl(), X509_AA, and X509_CA.
Referenced by load_certs(), and METHOD().
 {
     enumerator_t *enumerator;
     struct stat st;
     char *file;
     enumerator = enumerator_create_directory(path);
     if (enumerator)
     {
         while (enumerator->enumerate(enumerator, NULL, &file, &st))
         {
             if (!S_ISREG(st.st_mode))
             {
                 /* skip special file */
                 continue;
             }
             switch (type)
             {
                 case CERT_X509:
                     if (flag & X509_CA)
                     {
                         load_x509_ca(this, file, creds);
                     }
                     else if (flag & X509_AA)
                     {
                         load_x509_aa(this, file, creds);
                     }
                     else
                     {
                         load_x509(this, file, flag, creds);
                     }
                     break;
                 case CERT_X509_CRL:
                     load_x509_crl(this, file, creds);
                     break;
                 case CERT_X509_AC:
                     load_x509_ac(this, file, creds);
                     break;
                 default:
                     break;
             }
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         DBG1(DBG_CFG, "  reading directory failed");
     }
 }
static void load_certs (private_stroke_cred_t * this) static
load all certificates from ipsec.d
Definition at line 1348 of file stroke_cred.c.
References AA_CERTIFICATE_DIR, ATTR_CERTIFICATE_DIR, CA_CERTIFICATE_DIR, CERT_X509, CERT_X509_AC, CERT_X509_CRL, creds, CRL_DIR, DBG1, DBG_CFG, mem_cred_t::destroy, load_certdir(), mem_cred_create(), OCSP_CERTIFICATE_DIR, X509_AA, X509_CA, and X509_OCSP_SIGNER.
Referenced by stroke_cred_create().
 {
     mem_cred_t *creds;
     DBG1(DBG_CFG, "loading ca certificates from '%s'",
          CA_CERTIFICATE_DIR);
     creds = mem_cred_create();
     load_certdir(this, CA_CERTIFICATE_DIR, CERT_X509, X509_CA, creds);
     this->ca->replace_certs(this->ca, creds);
     creds->destroy(creds);
     DBG1(DBG_CFG, "loading aa certificates from '%s'",
          AA_CERTIFICATE_DIR);
     load_certdir(this, AA_CERTIFICATE_DIR, CERT_X509, X509_AA, this->aacerts);
     DBG1(DBG_CFG, "loading ocsp signer certificates from '%s'",
          OCSP_CERTIFICATE_DIR);
     load_certdir(this, OCSP_CERTIFICATE_DIR, CERT_X509, X509_OCSP_SIGNER,
                  this->creds);
     DBG1(DBG_CFG, "loading attribute certificates from '%s'",
          ATTR_CERTIFICATE_DIR);
     load_certdir(this, ATTR_CERTIFICATE_DIR, CERT_X509_AC, 0, this->creds);
     DBG1(DBG_CFG, "loading crls from '%s'",
          CRL_DIR);
     load_certdir(this, CRL_DIR, CERT_X509_CRL, 0, this->creds);
 }
static bool load_from_file (chunk_t line, int line_nr, FILE * prompt, char * path, int type, int subtype, void ** result) static
Load a private key or PKCS#12 container from a file
Definition at line 913 of file stroke_cred.c.
References credential_manager_t::add_local_set, mem_cred_t::add_shared, BUILD_END, BUILD_FROM_FILE, passphrase_cb_data_t::cache, callback_cred_create_shared(), cb(), chunk_empty, credential_factory_t::create, library_t::credmgr, library_t::creds, DBG1, DBG_CFG, callback_cred_t::destroy, mem_cred_t::destroy, eat_whitespace(), extract_secret(), extract_value(), FALSE, free(), chunk_t::len, lib, mem_cred_create(), passphrase_cb(), path, PRIVATE_KEY_DIR, passphrase_cb_data_t::prompt, chunk_t::ptr, credential_manager_t::remove_local_set, mem_cred_t::set, callback_cred_t::set, shared_key_create(), SHARED_PRIVATE_KEY_PASS, snprintf, strpfx(), TRUE, and type.
Referenced by load_pkcs12(), and load_private().
 {
     chunk_t filename;
     chunk_t secret = chunk_empty;
     err_t ugh = extract_value(&filename, &line);
     if (ugh != NULL)
     {
         DBG1(DBG_CFG, "line %d: %s", line_nr, ugh);
         return FALSE;
     }
     if (filename.len == 0)
     {
         DBG1(DBG_CFG, "line %d: empty filename", line_nr);
         return FALSE;
     }
     if (*filename.ptr == '/')
     {
         /* absolute path name */
         snprintf(path, PATH_MAX, "%.*s", (int)filename.len, filename.ptr);
     }
     else
     {
         /* relative path name */
         snprintf(path, PATH_MAX, "%s/%.*s", PRIVATE_KEY_DIR,
                  (int)filename.len, filename.ptr);
     }
     /* check for optional passphrase */
     if (eat_whitespace(&line))
     {
         ugh = extract_secret(&secret, &line);
         if (ugh != NULL)
         {
             DBG1(DBG_CFG, "line %d: malformed passphrase: %s", line_nr, ugh);
             return FALSE;
         }
     }
     if (secret.len == 7 && strpfx(secret.ptr, "%prompt"))
     {
         callback_cred_t *cb;
         passphrase_cb_data_t pp_data = {
             .prompt = prompt,
             .type = type,
             .path = path,
             .try = 0,
         };
         free(secret.ptr);
         if (!prompt)
         {
             *result = NULL;
             return TRUE;
         }
         /* add cache first so if valid passphrases are needed multiple times
          * the callback is not called anymore */
         pp_data.cache = mem_cred_create();
         lib->credmgr->add_local_set(lib->credmgr, &pp_data.cache->set, FALSE);
         /* use callback credential set to prompt for the passphrase */
         cb = callback_cred_create_shared((void*)passphrase_cb, &pp_data);
         lib->credmgr->add_local_set(lib->credmgr, &cb->set, FALSE);
         *result = lib->creds->create(lib->creds, type, subtype,
                                      BUILD_FROM_FILE, path, BUILD_END);
         lib->credmgr->remove_local_set(lib->credmgr, &cb->set);
         cb->destroy(cb);
         lib->credmgr->remove_local_set(lib->credmgr, &pp_data.cache->set);
         pp_data.cache->destroy(pp_data.cache);
     }
     else
     {
         mem_cred_t *mem = NULL;
         shared_key_t *shared;
         /* provide our pin in a temporary credential set */
         shared = shared_key_create(SHARED_PRIVATE_KEY_PASS, secret);
         mem = mem_cred_create();
         mem->add_shared(mem, shared, NULL);
         if (eat_whitespace(&line))
         {   /* if there is a second passphrase add that too, could be needed for
              * PKCS#12 files using different passwords for MAC and encryption */
             ugh = extract_secret(&secret, &line);
             if (ugh != NULL)
             {
                 DBG1(DBG_CFG, "line %d: malformed passphrase: %s", line_nr, ugh);
                 mem->destroy(mem);
                 return FALSE;
             }
             shared = shared_key_create(SHARED_PRIVATE_KEY_PASS, secret);
             mem->add_shared(mem, shared, NULL);
         }
         lib->credmgr->add_local_set(lib->credmgr, &mem->set, FALSE);
         *result = lib->creds->create(lib->creds, type, subtype,
                                      BUILD_FROM_FILE, path, BUILD_END);
         lib->credmgr->remove_local_set(lib->credmgr, &mem->set);
         mem->destroy(mem);
     }
     return TRUE;
 }
static certificate_t* load_from_smartcard (smartcard_format_t format, u_int slot, char * module, char * keyid, credential_type_t type, int subtype) static
Load a credential from a smartcard
Definition at line 151 of file stroke_cred.c.
References BUILD_END, BUILD_PKCS11_KEYID, BUILD_PKCS11_MODULE, BUILD_PKCS11_SLOT, chunk_create(), chunk_from_hex(), credential_factory_t::create, library_t::creds, free(), lib, chunk_t::ptr, SC_FORMAT_KEYID, SC_FORMAT_SLOT_KEYID, and SC_FORMAT_SLOT_MODULE_KEYID.
Referenced by load_ca_cert(), load_pin(), and METHOD().
 {
     chunk_t chunk;
     void *cred;
     chunk = chunk_from_hex(chunk_create(keyid, strlen(keyid)), NULL);
     switch (format)
     {
         case SC_FORMAT_SLOT_MODULE_KEYID:
             cred = lib->creds->create(lib->creds, type, subtype,
                             BUILD_PKCS11_SLOT, slot,
                             BUILD_PKCS11_MODULE, module,
                             BUILD_PKCS11_KEYID, chunk, BUILD_END);
             break;
         case SC_FORMAT_SLOT_KEYID:
             cred = lib->creds->create(lib->creds, type, subtype,
                             BUILD_PKCS11_SLOT, slot,
                             BUILD_PKCS11_KEYID, chunk, BUILD_END);
             break;
         case SC_FORMAT_KEYID:
             cred = lib->creds->create(lib->creds, type, subtype,
                             BUILD_PKCS11_KEYID, chunk, BUILD_END);
             break;
         default:
             cred = NULL;
             break;
     }
     free(chunk.ptr);
     return cred;
 }
static bool load_pin (mem_cred_t * secrets, chunk_t line, int line_nr, FILE * prompt) static
Load a smartcard with a PIN
Definition at line 810 of file stroke_cred.c.
References mem_cred_t::add_key, credential_manager_t::add_local_set, mem_cred_t::add_shared, BUF_LEN, callback_cred_create_shared(), pin_cb_data_t::card, cb(), chunk_clear(), chunk_create(), chunk_empty, chunk_from_hex(), CRED_PRIVATE_KEY, library_t::credmgr, DBG1, DBG_CFG, callback_cred_t::destroy, mem_cred_t::destroy, eat_whitespace(), extract_secret(), extract_value(), FALSE, free(), id, ID_KEY_ID, identification_create_from_encoding(), key, KEY_ANY, keyid(), pin_cb_data_t::keyid, chunk_t::len, lib, load_from_smartcard(), mem_cred_create(), parse_smartcard(), pin_cb(), pin_cb_data_t::prompt, chunk_t::ptr, credential_manager_t::remove_local_set, SC_FORMAT_INVALID, SC_PART_LEN, mem_cred_t::set, callback_cred_t::set, shared_key_create(), SHARED_PIN, snprintf, strpfx(), TRUE, and pin_cb_data_t::try.
Referenced by load_secrets().
 {
     chunk_t sc = chunk_empty, secret = chunk_empty;
     char smartcard[BUF_LEN], keyid[SC_PART_LEN], module[SC_PART_LEN];
     private_key_t *key = NULL;
     u_int slot;
     chunk_t chunk;
     shared_key_t *shared;
     identification_t *id;
     mem_cred_t *mem = NULL;
     callback_cred_t *cb = NULL;
     pin_cb_data_t pin_data;
     smartcard_format_t format;
     err_t ugh = extract_value(&sc, &line);
     if (ugh != NULL)
     {
         DBG1(DBG_CFG, "line %d: %s", line_nr, ugh);
         return FALSE;
     }
     if (sc.len == 0)
     {
         DBG1(DBG_CFG, "line %d: expected %%smartcard specifier", line_nr);
         return FALSE;
     }
     snprintf(smartcard, sizeof(smartcard), "%.*s", (int)sc.len, sc.ptr);
     smartcard[sizeof(smartcard) - 1] = '\0';
     format = parse_smartcard(smartcard, &slot, module, keyid);
     if (format == SC_FORMAT_INVALID)
     {
         DBG1(DBG_CFG, "line %d: the given %%smartcard specifier is not"
                 " supported or invalid", line_nr);
         return FALSE;
     }
     if (!eat_whitespace(&line))
     {
         DBG1(DBG_CFG, "line %d: expected PIN", line_nr);
         return FALSE;
     }
     ugh = extract_secret(&secret, &line);
     if (ugh != NULL)
     {
         DBG1(DBG_CFG, "line %d: malformed PIN: %s", line_nr, ugh);
         return FALSE;
     }
     chunk = chunk_from_hex(chunk_create(keyid, strlen(keyid)), NULL);
     if (secret.len == 7 && strpfx(secret.ptr, "%prompt"))
     {
         free(secret.ptr);
         if (!prompt)
         {   /* no IO channel to prompt, skip */
             chunk_clear(&chunk);
             return TRUE;
         }
         /* use callback credential set to prompt for the pin */
         pin_data.prompt = prompt;
         pin_data.card = smartcard;
         pin_data.keyid = chunk;
         pin_data.try = 0;
         cb = callback_cred_create_shared((void*)pin_cb, &pin_data);
         lib->credmgr->add_local_set(lib->credmgr, &cb->set, FALSE);
     }
     else
     {
         /* provide our pin in a temporary credential set */
         shared = shared_key_create(SHARED_PIN, secret);
         id = identification_create_from_encoding(ID_KEY_ID, chunk);
         mem = mem_cred_create();
         mem->add_shared(mem, shared, id, NULL);
         lib->credmgr->add_local_set(lib->credmgr, &mem->set, FALSE);
     }
     /* unlock: smartcard needs the pin and potentially calls public set */
     key = (private_key_t*)load_from_smartcard(format, slot, module, keyid,
                                               CRED_PRIVATE_KEY, KEY_ANY);
     if (mem)
     {
         lib->credmgr->remove_local_set(lib->credmgr, &mem->set);
         mem->destroy(mem);
     }
     if (cb)
     {
         lib->credmgr->remove_local_set(lib->credmgr, &cb->set);
         cb->destroy(cb);
     }
     chunk_clear(&chunk);
     if (key)
     {
         DBG1(DBG_CFG, "  loaded private key from %.*s", (int)sc.len, sc.ptr);
         secrets->add_key(secrets, key);
     }
     return TRUE;
 }
static bool load_pkcs12 (private_stroke_cred_t * this, mem_cred_t * secrets, chunk_t line, int line_nr, FILE * prompt) static
Load a PKCS#12 container
Definition at line 1049 of file stroke_cred.c.
References mem_cred_t::add_cert, mem_cred_t::add_key, cert, pkcs12_t::container, CONTAINER_PKCS12, pkcs12_t::create_cert_enumerator, pkcs12_t::create_key_enumerator, CRED_CONTAINER, creds, DBG1, DBG_CFG, enumerator_t::destroy, container_t::destroy, enumerator_t::enumerate, FALSE, x509_t::get_flags, private_key_t::get_ref, certificate_t::get_ref, certificate_t::get_subject, private_key_t::get_type, key, key_type_names, load_from_file(), path, pkcs12(), TRUE, and X509_CA.
Referenced by load_secrets().
 {
     enumerator_t *enumerator;
     char path[PATH_MAX];
     certificate_t *cert;
     private_key_t *key;
     pkcs12_t *pkcs12;
     if (!load_from_file(line, line_nr, prompt, path, CRED_CONTAINER,
                         CONTAINER_PKCS12, (void**)&pkcs12))
     {
         return FALSE;
     }
     if (!pkcs12)
     {
         DBG1(DBG_CFG, "  loading credentials from '%s' failed", path);
         return TRUE;
     }
     enumerator = pkcs12->create_cert_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &cert))
     {
         x509_t *x509 = (x509_t*)cert;
         if (x509->get_flags(x509) & X509_CA)
         {
             DBG1(DBG_CFG, "  loaded ca certificate \"%Y\" from '%s'",
                  cert->get_subject(cert), path);
         }
         else
         {
             DBG1(DBG_CFG, "  loaded certificate \"%Y\" from '%s'",
                  cert->get_subject(cert), path);
         }
         this->creds->add_cert(this->creds, TRUE, cert->get_ref(cert));
     }
     enumerator->destroy(enumerator);
     enumerator = pkcs12->create_key_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &key))
     {
         DBG1(DBG_CFG, "  loaded %N private key from '%s'",
              key_type_names, key->get_type(key), path);
         secrets->add_key(secrets, key->get_ref(key));
     }
     enumerator->destroy(enumerator);
     pkcs12->container.destroy(&pkcs12->container);
     return TRUE;
 }
static bool load_private (mem_cred_t * secrets, chunk_t line, int line_nr, FILE * prompt, key_type_t key_type) static
Load a private key
Definition at line 1022 of file stroke_cred.c.
References mem_cred_t::add_key, CRED_PRIVATE_KEY, DBG1, DBG_CFG, FALSE, private_key_t::get_type, key, key_type_names, load_from_file(), path, and TRUE.
Referenced by load_secrets().
 {
     char path[PATH_MAX];
     private_key_t *key;
     if (!load_from_file(line, line_nr, prompt, path, CRED_PRIVATE_KEY,
                         key_type, (void**)&key))
     {
         return FALSE;
     }
     if (key)
     {
         DBG1(DBG_CFG, "  loaded %N private key from '%s'",
              key_type_names, key->get_type(key), path);
         secrets->add_key(secrets, key);
     }
     else
     {
         DBG1(DBG_CFG, "  loading private key from '%s' failed", path);
     }
     return TRUE;
 }
static void load_secrets (private_stroke_cred_t * this, mem_cred_t * secrets, char * file, int level, FILE * prompt) static
reload ipsec.secrets
Definition at line 1163 of file stroke_cred.c.
References chunk_empty, chunk_map(), chunk_skip(), chunk_unmap(), creds, DBG1, DBG_CFG, mem_cred_t::destroy, dir, eat_whitespace(), extract_token(), extract_token_str(), FALSE, fetchline(), free(), KEY_BLISS, KEY_ECDSA, KEY_RSA, key_type, chunk_t::len, load_pin(), load_pkcs12(), load_private(), load_shared(), match(), MAX_SECRETS_RECURSION, mem_cred_create(), path_dirname(), chunk_t::ptr, mem_cred_t::replace_secrets, SHARED_EAP, SHARED_IKE, SHARED_NT_HASH, snprintf, src, strerror, strpfx(), and type.
Referenced by METHOD(), and stroke_cred_create().
 {
     int line_nr = 0;
     chunk_t *src, line;
     DBG1(DBG_CFG, "loading secrets from '%s'", file);
     src = chunk_map(file, FALSE);
     if (!src)
     {
         DBG1(DBG_CFG, "opening secrets file '%s' failed: %s", file,
              strerror(errno));
         return;
     }
     if (!secrets)
     {
         secrets = mem_cred_create();
     }
     while (fetchline(src, &line))
     {
         chunk_t ids, token;
         key_type_t key_type;
         shared_key_type_t type;
         line_nr++;
         if (!eat_whitespace(&line))
         {
             continue;
         }
         if (line.len > strlen("include ") && strpfx(line.ptr, "include "))
         {
             char **expanded, *dir, pattern[PATH_MAX];
             u_char *pos;
             if (level > MAX_SECRETS_RECURSION)
             {
                 DBG1(DBG_CFG, "maximum level of %d includes reached, ignored",
                      MAX_SECRETS_RECURSION);
                 continue;
             }
             /* terminate filename by space */
             line = chunk_skip(line, strlen("include "));
             pos = memchr(line.ptr, ' ', line.len);
             if (pos)
             {
                 line.len = pos - line.ptr;
             }
             if (line.len && line.ptr[0] == '/')
             {
                 if (line.len + 1 > sizeof(pattern))
                 {
                     DBG1(DBG_CFG, "include pattern too long, ignored");
                     continue;
                 }
                 snprintf(pattern, sizeof(pattern), "%.*s",
                          (int)line.len, line.ptr);
             }
             else
             {   /* use directory of current file if relative */
                 dir = path_dirname(file);
                 if (line.len + 1 + strlen(dir) + 1 > sizeof(pattern))
                 {
                     DBG1(DBG_CFG, "include pattern too long, ignored");
                     free(dir);
                     continue;
                 }
                 snprintf(pattern, sizeof(pattern), "%s/%.*s",
                          dir, (int)line.len, line.ptr);
                 free(dir);
             }
 #ifdef HAVE_GLOB_H
             {
                 glob_t buf;
                 if (glob(pattern, GLOB_ERR, NULL, &buf) != 0)
                 {
                     DBG1(DBG_CFG, "expanding file expression '%s' failed",
                          pattern);
                 }
                 else
                 {
                     for (expanded = buf.gl_pathv; *expanded != NULL; expanded++)
                     {
                         load_secrets(this, secrets, *expanded, level + 1,
                                      prompt);
                     }
                 }
                 globfree(&buf);
             }
 #else /* HAVE_GLOB_H */
             /* if glob(3) is not available, try to load pattern directly */
             load_secrets(this, secrets, pattern, level + 1, prompt);
 #endif /* HAVE_GLOB_H */
             continue;
         }
         if (line.len > 2 && strpfx(line.ptr, ": "))
         {
             /* no ids, skip the ':' */
             ids = chunk_empty;
             line.ptr++;
             line.len--;
         }
         else if (extract_token_str(&ids, " : ", &line))
         {
             /* NULL terminate the extracted id string */
             *(ids.ptr + ids.len) = '\0';
         }
         else
         {
             DBG1(DBG_CFG, "line %d: missing ' : ' separator", line_nr);
             break;
         }
         if (!eat_whitespace(&line) || !extract_token(&token, ' ', &line))
         {
             DBG1(DBG_CFG, "line %d: missing token", line_nr);
             break;
         }
         if (match("RSA", &token) || match("ECDSA", &token) ||
             match("BLISS", &token))
         {
             if (match("RSA", &token))
             {
                 key_type = KEY_RSA;
             }
             else if (match("ECDSA", &token))
             {
                 key_type = KEY_ECDSA;
             }
             else
             {
                 key_type = KEY_BLISS;
             }
             if (!load_private(secrets, line, line_nr, prompt, key_type))
             {
                 break;
             }
         }
         else if (match("P12", &token))
         {
             if (!load_pkcs12(this, secrets, line, line_nr, prompt))
             {
                 break;
             }
         }
         else if (match("PIN", &token))
         {
             if (!load_pin(secrets, line, line_nr, prompt))
             {
                 break;
             }
         }
         else if ((match("PSK", &token) && (type = SHARED_IKE)) ||
                  (match("EAP", &token) && (type = SHARED_EAP)) ||
                  (match("NTLM", &token) && (type = SHARED_NT_HASH)) ||
                  (match("XAUTH", &token) && (type = SHARED_EAP)))
         {
             if (!load_shared(secrets, line, line_nr, type, ids))
             {
                 break;
             }
         }
         else
         {
             DBG1(DBG_CFG, "line %d: token must be either RSA, ECDSA, BLISS, "
                           "P12, PIN, PSK, EAP, XAUTH or NTLM", line_nr);
             break;
         }
     }
     chunk_unmap(src);
     if (level == 0)
     {   /* replace secrets in active credential set */
         this->creds->replace_secrets(this->creds, secrets, FALSE);
         secrets->destroy(secrets);
     }
 }
static bool load_shared (mem_cred_t * secrets, chunk_t line, int line_nr, shared_key_type_t type, chunk_t ids) static
Load a shared key
Definition at line 1101 of file stroke_cred.c.
References mem_cred_t::add_shared_list, chunk_empty, DBG1, DBG4, DBG_CFG, shared_key_t::destroy, identification_t::destroy, destroy(), linked_list_t::destroy_offset, extract_secret(), extract_value(), FALSE, identification_t::get_type, id, ID_ANY, identification_create_from_encoding(), identification_create_from_string(), linked_list_t::insert_last, chunk_t::len, len, linked_list_create(), chunk_t::ptr, shared_key_create(), shared_key_type_names, and TRUE.
Referenced by load_secrets(), and manage_commands().
 {
     shared_key_t *shared_key;
     linked_list_t *owners;
     chunk_t secret = chunk_empty;
     bool any = TRUE;
     err_t ugh = extract_secret(&secret, &line);
     if (ugh != NULL)
     {
         DBG1(DBG_CFG, "line %d: malformed secret: %s", line_nr, ugh);
         return FALSE;
     }
     shared_key = shared_key_create(type, secret);
     DBG1(DBG_CFG, "  loaded %N secret for %s", shared_key_type_names, type,
          ids.len > 0 ? (char*)ids.ptr : "%any");
     DBG4(DBG_CFG, "  secret: %#B", &secret);
     owners = linked_list_create();
     while (ids.len > 0)
     {
         chunk_t id;
         identification_t *peer_id;
         ugh = extract_value(&id, &ids);
         if (ugh != NULL)
         {
             DBG1(DBG_CFG, "line %d: %s", line_nr, ugh);
             shared_key->destroy(shared_key);
             owners->destroy_offset(owners, offsetof(identification_t, destroy));
             return FALSE;
         }
         if (id.len == 0)
         {
             continue;
         }
         /* NULL terminate the ID string */
         *(id.ptr + id.len) = '\0';
         peer_id = identification_create_from_string(id.ptr);
         if (peer_id->get_type(peer_id) == ID_ANY)
         {
             peer_id->destroy(peer_id);
             continue;
         }
         owners->insert_last(owners, peer_id);
         any = FALSE;
     }
     if (any)
     {
         owners->insert_last(owners,
                     identification_create_from_encoding(ID_ANY, chunk_empty));
     }
     secrets->add_shared_list(secrets, shared_key, owners);
     return TRUE;
 }
static void load_x509 (private_stroke_cred_t * this, char * file, x509_flag_t flag, mem_cred_t * creds) static
Load a certificate with flags from disk
Definition at line 447 of file stroke_cred.c.
References mem_cred_t::add_cert, BUILD_END, BUILD_FROM_FILE, BUILD_X509_FLAG, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_CFG, certificate_t::get_subject, lib, and TRUE.
Referenced by load_certdir().
 {
     certificate_t *cert;
     /* for all other flags, we add them to the certificate. */
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_FROM_FILE, file,
                               BUILD_X509_FLAG, flag, BUILD_END);
     if (cert)
     {
         DBG1(DBG_CFG, "  loaded certificate \"%Y\" from '%s'",
              cert->get_subject(cert), file);
         creds->add_cert(creds, TRUE, cert);
     }
     else
     {
         DBG1(DBG_CFG, "  loading certificate from '%s' failed", file);
     }
 }
static void load_x509_aa (private_stroke_cred_t * this, char * file, mem_cred_t * creds) static
Load AA certificate with flags from disk
Definition at line 424 of file stroke_cred.c.
References mem_cred_t::add_cert, BUILD_END, BUILD_FROM_FILE, BUILD_X509_FLAG, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_CFG, certificate_t::get_subject, lib, TRUE, and X509_AA.
Referenced by load_certdir().
 {
     certificate_t *cert;
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_FROM_FILE, file,
                               BUILD_X509_FLAG, X509_AA, BUILD_END);
     if (cert)
     {
         DBG1(DBG_CFG, "  loaded AA certificate \"%Y\" from '%s'",
              cert->get_subject(cert), file);
         creds->add_cert(creds, TRUE, cert);
     }
     else
     {
         DBG1(DBG_CFG, "  loading AA certificate from '%s' failed", file);
     }
 }
static void load_x509_ac (private_stroke_cred_t * this, char * file, mem_cred_t * creds) static
Load an attribute certificate from a file
Definition at line 492 of file stroke_cred.c.
References mem_cred_t::add_cert, BUILD_END, BUILD_FROM_FILE, cert, CERT_X509_AC, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_CFG, FALSE, and lib.
Referenced by load_certdir().
 {
     certificate_t *cert;
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509_AC,
                               BUILD_FROM_FILE, file, BUILD_END);
     if (cert)
     {
         DBG1(DBG_CFG, "  loaded attribute certificate from '%s'", file);
         creds->add_cert(creds, FALSE, cert);
     }
     else
     {
         DBG1(DBG_CFG, "  loading attribute certificate from '%s' failed", file);
     }
 }
static void load_x509_ca (private_stroke_cred_t * this, char * file, mem_cred_t * creds) static
Load a CA certificate from disk
Definition at line 404 of file stroke_cred.c.
References mem_cred_t::add_cert, cert, DBG1, DBG_CFG, load_ca_cert(), and TRUE.
Referenced by load_certdir().
 {
     certificate_t *cert;
     cert = load_ca_cert(file, this->force_ca_cert);
     if (cert)
     {
         cert = this->ca->get_cert_ref(this->ca, cert);
         creds->add_cert(creds, TRUE, cert);
     }
     else
     {
         DBG1(DBG_CFG, "  loading ca certificate from '%s' failed", file);
     }
 }
static void load_x509_crl (private_stroke_cred_t * this, char * file, mem_cred_t * creds) static
Load a CRL from a file
Definition at line 471 of file stroke_cred.c.
References mem_cred_t::add_crl, BUILD_END, BUILD_FROM_FILE, cert, CERT_X509_CRL, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_CFG, and lib.
Referenced by load_certdir().
 {
     certificate_t *cert;
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509_CRL,
                               BUILD_FROM_FILE, file, BUILD_END);
     if (cert)
     {
         DBG1(DBG_CFG, "  loaded crl from '%s'",  file);
         creds->add_crl(creds, (crl_t*)cert);
     }
     else
     {
         DBG1(DBG_CFG, "  loading crl from '%s' failed", file);
     }
 }
METHOD (stroke_cred_t , load_peer , certificate_t * , private_stroke_cred_t * this, char * filename)
Definition at line 185 of file stroke_cred.c.
References mem_cred_t::add_cert_ref, BUILD_END, BUILD_FROM_FILE, cert, CERT_ANY, CERT_X509, CERTIFICATE_DIR, credential_factory_t::create, CRED_CERTIFICATE, creds, library_t::creds, DBG1, DBG_CFG, certificate_t::get_subject, keyid(), lib, load_from_smartcard(), parse_smartcard(), path, SC_FORMAT_INVALID, SC_PART_LEN, snprintf, strpfx(), and TRUE.
 {
     certificate_t *cert = NULL;
     char path[PATH_MAX];
     if (strpfx(filename, "%smartcard"))
     {
         smartcard_format_t format;
         char module[SC_PART_LEN], keyid[SC_PART_LEN];
         u_int slot;
         format = parse_smartcard(filename, &slot, module, keyid);
         if (format != SC_FORMAT_INVALID)
         {
             cert = (certificate_t*)load_from_smartcard(format,
                             slot, module, keyid, CRED_CERTIFICATE, CERT_X509);
         }
     }
     else
     {
         if (*filename == '/')
         {
             snprintf(path, sizeof(path), "%s", filename);
         }
         else
         {
             snprintf(path, sizeof(path), "%s/%s", CERTIFICATE_DIR, filename);
         }
         cert = lib->creds->create(lib->creds,
                                   CRED_CERTIFICATE, CERT_ANY,
                                   BUILD_FROM_FILE, path,
                                   BUILD_END);
     }
     if (cert)
     {
         cert = this->creds->add_cert_ref(this->creds, TRUE, cert);
         DBG1(DBG_CFG, "  loaded certificate \"%Y\" from '%s'",
                       cert->get_subject(cert), filename);
         return cert;
     }
     DBG1(DBG_CFG, "  loading certificate from '%s' failed", filename);
     return NULL;
 }
METHOD (stroke_cred_t , load_pubkey , certificate_t * , private_stroke_cred_t * this, char * filename, identification_t * identity)
Definition at line 231 of file stroke_cred.c.
References mem_cred_t::add_cert_ref, BUILD_BLOB_ASN1_DER, BUILD_BLOB_DNSKEY, BUILD_BLOB_SSHKEY, BUILD_END, BUILD_FROM_FILE, BUILD_PUBLIC_KEY, BUILD_SUBJECT, cert, CERT_TRUSTED_PUBKEY, CERTIFICATE_DIR, chunk_create(), chunk_free(), chunk_from_base64(), chunk_from_hex(), credential_factory_t::create, CRED_CERTIFICATE, CRED_PUBLIC_KEY, creds, library_t::creds, DBG1, DBG_CFG, public_key_t::destroy, certificate_t::get_public_key, public_key_t::get_type, key, KEY_ANY, KEY_RSA, key_type_names, lib, path, snprintf, streq(), strncaseeq(), TRUE, and type.
 {
     certificate_t *cert;
     public_key_t *key;
     char path[PATH_MAX];
     builder_part_t build_part;
     key_type_t type = KEY_ANY;
     if (streq(filename, "%dns"))
     {
         return NULL;
     }
     if (strncaseeq(filename, "dns:", 4))
     {   /* RFC 3110 format */
         build_part = BUILD_BLOB_DNSKEY;
         /* not a complete RR, only RSA supported */
         type = KEY_RSA;
         filename += 4;
     }
     else if (strncaseeq(filename, "ssh:", 4))
     {   /* SSH key */
         build_part = BUILD_BLOB_SSHKEY;
         filename += 4;
     }
     else
     {   /* try PKCS#1 by default */
         build_part = BUILD_BLOB_ASN1_DER;
     }
     if (strncaseeq(filename, "0x", 2) || strncaseeq(filename, "0s", 2))
     {
         chunk_t printable_key, raw_key;
         printable_key = chunk_create(filename + 2, strlen(filename) - 2);
         raw_key = strncaseeq(filename, "0x", 2) ?
                                  chunk_from_hex(printable_key, NULL) :
                                  chunk_from_base64(printable_key, NULL);
         key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, type,
                                  build_part, raw_key, BUILD_END);
         chunk_free(&raw_key);
         if (key)
         {
             cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                                       CERT_TRUSTED_PUBKEY,
                                       BUILD_PUBLIC_KEY, key,
                                       BUILD_SUBJECT, identity,
                                       BUILD_END);
             type = key->get_type(key);
             key->destroy(key);
             if (cert)
             {
                 cert = this->creds->add_cert_ref(this->creds, TRUE, cert);
                 DBG1(DBG_CFG, "  loaded %N public key for \"%Y\"",
                      key_type_names, type, identity);
                 return cert;
             }
         }
         DBG1(DBG_CFG, "  loading public key for \"%Y\" failed", identity);
     }
     else
     {
         if (*filename == '/')
         {
             snprintf(path, sizeof(path), "%s", filename);
         }
         else
         {
             snprintf(path, sizeof(path), "%s/%s", CERTIFICATE_DIR, filename);
         }
         cert = lib->creds->create(lib->creds,
                                   CRED_CERTIFICATE, CERT_TRUSTED_PUBKEY,
                                   BUILD_FROM_FILE, path,
                                   BUILD_SUBJECT, identity,
                                   BUILD_END);
         if (cert)
         {
             cert = this->creds->add_cert_ref(this->creds, TRUE, cert);
             key = cert->get_public_key(cert);
             type = key->get_type(key);
             key->destroy(key);
             DBG1(DBG_CFG, "  loaded %N public key for \"%Y\" from '%s'",
                  key_type_names, type, identity, filename);
             return cert;
         }
         DBG1(DBG_CFG, "  loading public key for \"%Y\" from '%s' failed",
              identity, filename);
     }
     return NULL;
 }
METHOD (stroke_cred_t , cache_cert , void , private_stroke_cred_t * this, certificate_t * cert)
Definition at line 565 of file stroke_cred.c.
References mem_cred_t::add_crl, BUF_LEN, CERT_ASN1_DER, CERT_X509_CRL, chunk_to_hex(), chunk_write(), creds, CRL_DIR, DBG1, DBG_CFG, FALSE, free(), crl_t::get_authKeyIdentifier, certificate_t::get_encoding, certificate_t::get_ref, certificate_t::get_type, chunk_t::len, chunk_t::ptr, snprintf, strerror, and TRUE.
 {
     if (cert->get_type(cert) == CERT_X509_CRL && this->cachecrl)
     {
         /* CRLs get written to /etc/ipsec.d/crls/<authkeyId>.crl */
         crl_t *crl = (crl_t*)cert;
         cert->get_ref(cert);
         if (this->creds->add_crl(this->creds, crl))
         {
             char buf[BUF_LEN];
             chunk_t chunk, hex;
             chunk = crl->get_authKeyIdentifier(crl);
             hex = chunk_to_hex(chunk, NULL, FALSE);
             snprintf(buf, sizeof(buf), "%s/%s.crl", CRL_DIR, hex.ptr);
             free(hex.ptr);
             if (cert->get_encoding(cert, CERT_ASN1_DER, &chunk))
             {
                 if (chunk_write(chunk, buf, 022, TRUE))
                 {
                     DBG1(DBG_CFG, "  written crl file '%s' (%d bytes)",
                          buf, chunk.len);
                 }
                 else
                 {
                     DBG1(DBG_CFG, "  writing crl file '%s' failed: %s",
                          buf, strerror(errno));
                 }
                 free(chunk.ptr);
             }
         }
     }
 }
METHOD (stroke_cred_t , cachecrl , void , private_stroke_cred_t * this, bool enabled)
Definition at line 602 of file stroke_cred.c.
References CRL_DIR, DBG1, DBG_CFG, and enabled.
 {
     DBG1(DBG_CFG, "crl caching to %s %s",
          CRL_DIR, enabled ? "enabled" : "disabled");
     this->cachecrl = enabled;
 }
METHOD (stroke_cred_t , reread , void , private_stroke_cred_t * this, stroke_msg_t * msg, FILE * prompt)
Definition at line 1377 of file stroke_cred.c.
References AA_CERTIFICATE_DIR, ATTR_CERTIFICATE_DIR, CA_CERTIFICATE_DIR, CERT_X509, CERT_X509_AC, CERT_X509_CRL, library_t::credmgr, creds, CRL_DIR, DBG1, DBG_CFG, mem_cred_t::destroy, FALSE, credential_manager_t::flush_cache, lib, load_certdir(), load_secrets(), mem_cred_create(), OCSP_CERTIFICATE_DIR, stroke_msg_t::reread, REREAD_AACERTS, REREAD_ACERTS, REREAD_CACERTS, REREAD_CRLS, REREAD_OCSPCERTS, REREAD_SECRETS, X509_AA, X509_CA, and X509_OCSP_SIGNER.
 {
     mem_cred_t *creds;
     if (msg->reread.flags & REREAD_SECRETS)
     {
         DBG1(DBG_CFG, "rereading secrets");
         load_secrets(this, NULL, this->secrets_file, 0, prompt);
     }
     if (msg->reread.flags & REREAD_CACERTS)
     {
         /* first reload certificates in ca sections, so we can refer to them */
         this->ca->reload_certs(this->ca);
         DBG1(DBG_CFG, "rereading ca certificates from '%s'",
              CA_CERTIFICATE_DIR);
         creds = mem_cred_create();
         load_certdir(this, CA_CERTIFICATE_DIR, CERT_X509, X509_CA, creds);
         this->ca->replace_certs(this->ca, creds);
         creds->destroy(creds);
     }
     if (msg->reread.flags & REREAD_AACERTS)
     {
         DBG1(DBG_CFG, "rereading aa certificates from '%s'",
              AA_CERTIFICATE_DIR);
         creds = mem_cred_create();
         load_certdir(this, AA_CERTIFICATE_DIR, CERT_X509, X509_AA, creds);
         this->aacerts->replace_certs(this->aacerts, creds, FALSE);
         creds->destroy(creds);
         lib->credmgr->flush_cache(lib->credmgr, CERT_X509);
     }
     if (msg->reread.flags & REREAD_OCSPCERTS)
     {
         DBG1(DBG_CFG, "rereading ocsp signer certificates from '%s'",
              OCSP_CERTIFICATE_DIR);
         load_certdir(this, OCSP_CERTIFICATE_DIR, CERT_X509,
              X509_OCSP_SIGNER, this->creds);
     }
     if (msg->reread.flags & REREAD_ACERTS)
     {
         DBG1(DBG_CFG, "rereading attribute certificates from '%s'",
              ATTR_CERTIFICATE_DIR);
         load_certdir(this, ATTR_CERTIFICATE_DIR, CERT_X509_AC, 0, this->creds);
     }
     if (msg->reread.flags & REREAD_CRLS)
     {
         DBG1(DBG_CFG, "rereading crls from '%s'",
              CRL_DIR);
         load_certdir(this, CRL_DIR, CERT_X509_CRL, 0, this->creds);
     }
 }
METHOD (stroke_cred_t , add_shared , void , private_stroke_cred_t * this, shared_key_t * shared, linked_list_t * owners)
Definition at line 1430 of file stroke_cred.c.
References mem_cred_t::add_shared_list, and creds.
 {
     this->creds->add_shared_list(this->creds, shared, owners);
 }
METHOD (stroke_cred_t , destroy , void , private_stroke_cred_t * this)
Definition at line 1436 of file stroke_cred.c.
References library_t::credmgr, creds, mem_cred_t::destroy, free(), lib, and credential_manager_t::remove_set.
 {
     lib->credmgr->remove_set(lib->credmgr, &this->aacerts->set);
     lib->credmgr->remove_set(lib->credmgr, &this->creds->set);
     this->aacerts->destroy(this->aacerts);
     this->creds->destroy(this->creds);
     free(this);
 }
static smartcard_format_t parse_smartcard (char * smartcard, u_int * slot, char * module, char * keyid) static
Parse a smartcard specifier token
Definition at line 115 of file stroke_cred.c.
References SC_FORMAT_INVALID, SC_FORMAT_KEYID, SC_FORMAT_SLOT_KEYID, SC_FORMAT_SLOT_MODULE_KEYID, SC_PART_LEN, and snprintf.
Referenced by load_ca_cert(), load_pin(), and METHOD().
 {
     /* The token has one of the following three formats:
      * - %smartcard<slot>@<module>:<keyid>
      * - %smartcard<slot>:<keyid>
      * - %smartcard:<keyid>
      */
     char buf[2 * SC_PART_LEN], *pos;
     if (sscanf(smartcard, "%%smartcard%u@%255s", slot, buf) == 2)
     {
         pos = strchr(buf, ':');
         if (!pos)
         {
             return SC_FORMAT_INVALID;
         }
         *pos++ = '\0';
         snprintf(module, SC_PART_LEN, "%s", buf);
         snprintf(keyid, SC_PART_LEN, "%s", pos);
         return SC_FORMAT_SLOT_MODULE_KEYID;
     }
     if (sscanf(smartcard, "%%smartcard%u:%127s", slot, keyid) == 2)
     {
         return SC_FORMAT_SLOT_KEYID;
     }
     if (sscanf(smartcard, "%%smartcard:%127s", keyid) == 1)
     {
         return SC_FORMAT_KEYID;
     }
     return SC_FORMAT_INVALID;
 }
static shared_key_t* passphrase_cb (passphrase_cb_data_t * data, shared_key_type_t type, identification_t * me, identification_t * other, id_match_t * match_me, id_match_t * match_other) static
Callback function to receive passphrases
Definition at line 689 of file stroke_cred.c.
References mem_cred_t::add_shared, passphrase_cb_data_t::cache, chunk_clone, chunk_create(), CRED_PRIVATE_KEY, fprintf, shared_key_t::get_ref, ID_MATCH_NONE, ID_MATCH_PERFECT, chunk_t::len, passphrase_cb_data_t::path, passphrase_cb_data_t::prompt, SHARED_ANY, shared_key_create(), SHARED_PRIVATE_KEY_PASS, passphrase_cb_data_t::try, and passphrase_cb_data_t::type.
Referenced by load_from_file().
 {
     static const int max_tries = 3;
     shared_key_t *shared;
     chunk_t secret;
     char buf[256];
     if (type != SHARED_ANY && type != SHARED_PRIVATE_KEY_PASS)
     {
         return NULL;
     }
     data->try++;
     if (data->try > max_tries + 1)
     {   /* another builder might call this after we gave up, fail silently */
         return NULL;
     }
     if (data->try > max_tries)
     {
         fprintf(data->prompt, "Passphrase invalid, giving up.\n");
         return NULL;
     }
     if (data->try > 1)
     {
         fprintf(data->prompt, "Passphrase invalid!\n");
     }
     fprintf(data->prompt, "%s '%s' is encrypted.\n",
             data->type == CRED_PRIVATE_KEY ? "Private key" : "PKCS#12 file",
             data->path);
     fprintf(data->prompt, "Passphrase:\n");
     if (fgets(buf, sizeof(buf), data->prompt))
     {
         secret = chunk_create(buf, strlen(buf));
         if (secret.len > 1)
         {   /* trim appended \n */
             secret.len--;
             if (match_me)
             {
                 *match_me = ID_MATCH_PERFECT;
             }
             if (match_other)
             {
                 *match_other = ID_MATCH_NONE;
             }
             shared = shared_key_create(SHARED_PRIVATE_KEY_PASS,
                                        chunk_clone(secret));
             data->cache->add_shared(data->cache, shared->get_ref(shared), NULL);
             return shared;
         }
     }
     return NULL;
 }
static shared_key_t* pin_cb (pin_cb_data_t * data, shared_key_type_t type, identification_t * me, identification_t * other, id_match_t * match_me, id_match_t * match_other) static
Callback function to receive PINs
Definition at line 762 of file stroke_cred.c.
References pin_cb_data_t::card, chunk_clone, chunk_create(), chunk_equals(), fprintf, identification_t::get_encoding, ID_MATCH_NONE, ID_MATCH_PERFECT, pin_cb_data_t::keyid, chunk_t::len, pin_cb_data_t::prompt, SHARED_ANY, shared_key_create(), SHARED_PIN, and pin_cb_data_t::try.
Referenced by load_pin().
 {
     chunk_t secret;
     char buf[256];
     if (type != SHARED_ANY && type != SHARED_PIN)
     {
         return NULL;
     }
     if (!me || !chunk_equals(me->get_encoding(me), data->keyid))
     {
         return NULL;
     }
     data->try++;
     if (data->try > 1)
     {
         fprintf(data->prompt, "PIN invalid, aborting.\n");
         return NULL;
     }
     fprintf(data->prompt, "Login to '%s' required\n", data->card);
     fprintf(data->prompt, "PIN:\n");
     if (fgets(buf, sizeof(buf), data->prompt))
     {
         secret = chunk_create(buf, strlen(buf));
         if (secret.len > 1)
         {   /* trim appended \n */
             secret.len--;
             if (match_me)
             {
                 *match_me = ID_MATCH_PERFECT;
             }
             if (match_other)
             {
                 *match_other = ID_MATCH_NONE;
             }
             return shared_key_create(SHARED_PIN, chunk_clone(secret));
         }
     }
     return NULL;
 }
certificate_t* stroke_load_ca_cert (char * filename)
Used by stroke_ca.c
Definition at line 391 of file stroke_cred.c.
References FALSE, settings_t::get_bool, lib, load_ca_cert(), library_t::ns, and library_t::settings.
Referenced by METHOD().
 {
     bool force_ca_cert;
     force_ca_cert = lib->settings->get_bool(lib->settings,
                         "%s.plugins.stroke.ignore_missing_ca_basic_constraint",
                         FALSE, lib->ns);
     return load_ca_cert(filename, force_ca_cert);
 }