strongSwan: imv_msg
imv_msg
imv
Classes
struct imv_msg_t
Typedefs
typedef struct imv_msg_t imv_msg_t
Functions
imv_msg_t * imv_msg_create (imv_agent_t *agent, imv_state_t *state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, pen_type_t msg_type)
imv_msg_t * imv_msg_create_as_reply (imv_msg_t *msg)
imv_msg_t * imv_msg_create_from_data (imv_agent_t *agent, imv_state_t *state, TNC_ConnectionID connection_id, TNC_MessageType msg_type, chunk_t msg)
imv_msg_t * imv_msg_create_from_long_data (imv_agent_t *agent, imv_state_t *state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, chunk_t msg)
Detailed Description
Typedef Documentation
typedef struct imv_msg_t imv_msg_t
Definition at line 26 of file imv_msg.h.
Function Documentation
imv_msg_t* imv_msg_create (imv_agent_t * agent, imv_state_t * state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, pen_type_t msg_type)
Create a wrapper for an outbound message
Parameters
agent IMV agent responsible for the message
state IMV state for the given connection ID
connection_id connection ID
src_id source IMV ID
dst_id destination IMC ID
msg_type PA-TNC message type
See header
Definition at line 569 of file imv_msg.c.
References INIT, and linked_list_create().
Referenced by imv_msg_create_as_reply(), imv_msg_create_from_long_data(), and METHOD().
 {
     private_imv_msg_t *this;
     INIT(this,
         .public = {
             .get_src_id = _get_src_id,
             .get_dst_id = _get_dst_id,
             .set_msg_type = _set_msg_type,
             .get_msg_type = _get_msg_type,
             .send = _send_,
             .send_assessment = _send_assessment,
             .receive = _receive,
             .add_attribute = _add_attribute,
             .get_attribute_count = _get_attribute_count,
             .create_attribute_enumerator = _create_attribute_enumerator,
             .get_encoding = _get_encoding,
             .destroy = _destroy,
         },
         .connection_id = connection_id,
         .src_id = src_id,
         .dst_id = dst_id,
         .msg_type = msg_type,
         .attr_list = linked_list_create(),
         .agent = agent,
         .state = state,
     );
     return &this->public;
 }
imv_msg_t* imv_msg_create_as_reply (imv_msg_t * msg)
Create a wrapper for an outbound message based on a received message
Parameters
msg received message the reply is based on
See header
Definition at line 606 of file imv_msg.c.
References private_imv_msg_t::agent, private_imv_msg_t::connection_id, private_imv_msg_t::dst_id, imv_agent_t::get_id, imv_msg_create(), in, private_imv_msg_t::msg_type, private_imv_msg_t::src_id, private_imv_msg_t::state, and TNC_IMVID_ANY.
Referenced by receive_msg().
 {
     private_imv_msg_t *in;
     TNC_UInt32 src_id;
     in = (private_imv_msg_t*)msg;
     src_id = (in->dst_id != TNC_IMVID_ANY) ?
               in->dst_id : in->agent->get_id(in->agent);
     return imv_msg_create(in->agent, in->state, in->connection_id, src_id,
                           in->src_id, in->msg_type);
 }
imv_msg_t* imv_msg_create_from_data (imv_agent_t * agent, imv_state_t * state, TNC_ConnectionID connection_id, TNC_MessageType msg_type, chunk_t msg)
Create a wrapper around message data received via the legacy IF-IMV interface
Parameters
agent IMV agent responsible for the message
state IMV state for the given connection ID
connection_id connection ID
msg_type PA-TNC message type
msg received PA-TNC message blob
See header
Definition at line 622 of file imv_msg.c.
References imv_agent_t::get_id, imv_msg_create_from_long_data(), msg, TNC_IMCID_ANY, and TNC_SUBTYPE_ANY.
Referenced by METHOD().
 {
     TNC_VendorID msg_vid;
     TNC_MessageSubtype msg_subtype;
     msg_vid = msg_type >> 8;
     msg_subtype = msg_type & TNC_SUBTYPE_ANY;
     return imv_msg_create_from_long_data(agent, state, connection_id,
                                 TNC_IMCID_ANY, agent->get_id(agent),
                                 msg_vid, msg_subtype, msg);
 }
imv_msg_t* imv_msg_create_from_long_data (imv_agent_t * agent, imv_state_t * state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, chunk_t msg)
Create a wrapper around message data received via the long IF-IMV interface
Parameters
agent IMV agent responsible for the message
state IMV state for the given connection ID
connection_id connection ID
src_id source IMC ID
dst_id destination IMV ID
msg_vid PA-TNC message vendor ID
msg_subtype PA-TNC subtype
msg received PA-TNC message blob
See header
Definition at line 641 of file imv_msg.c.
References imv_msg_create(), pa_tnc_msg_create_from_data(), and pen_type_create().
Referenced by imv_msg_create_from_data(), and METHOD().
 {
     private_imv_msg_t *this;
     this = (private_imv_msg_t*)imv_msg_create(agent, state,
                                         connection_id, src_id, dst_id,
                                         pen_type_create(msg_vid, msg_subtype));
     this->pa_msg = pa_tnc_msg_create_from_data(msg);
     return &this->public;
 }