strongSwan: pb_pdp_referral_msg
pb_pdp_referral_msg
tnccs_20
Classes
struct pb_pdp_referral_msg_t
Typedefs
typedef enum
pb_pdp_identifier_type_t pb_pdp_identifier_type_t
typedef struct
pb_pdp_referral_msg_t pb_pdp_referral_msg_t
Enumerations
enum pb_pdp_identifier_type_t { PB_PDP_ID_FQDN = 0, PB_PDP_ID_IPV4 = 1, PB_PDP_ID_IPV6 = 2 }
Functions
pb_tnc_msg_t * pb_pdp_referral_msg_create (pen_type_t identifier_type, chunk_t identifier)
pb_tnc_msg_t * pb_pdp_referral_msg_create_from_fqdn (chunk_t fqdn, u_int16_t port)
pb_tnc_msg_t * pb_pdp_referral_msg_create_from_data (chunk_t data)
Variables
enum_name_t * pb_pdp_identifier_type_names
Detailed Description
Typedef Documentation
typedef enum pb_pdp_identifier_type_t pb_pdp_identifier_type_t
Definition at line 24 of file pb_pdp_referral_msg.h.
typedef struct pb_pdp_referral_msg_t pb_pdp_referral_msg_t
Definition at line 25 of file pb_pdp_referral_msg.h.
Enumeration Type Documentation
enum pb_pdp_identifier_type_t
PB-TNC PDP Identifier Types as defined in section 3.1.1.2 of the TCG TNC PDP Discovery and Validation Specification 1.0
Enumerator
PB_PDP_ID_FQDN
PB_PDP_ID_IPV4
PB_PDP_ID_IPV6
Definition at line 35 of file pb_pdp_referral_msg.h.
{
     PB_PDP_ID_FQDN =    0,
     PB_PDP_ID_IPV4 =    1,
     PB_PDP_ID_IPV6 =    2
 };
Function Documentation
pb_tnc_msg_t* pb_pdp_referral_msg_create (pen_type_t identifier_type, chunk_t identifier)
Create a general PB-PDP-Referral message
Parameters
identifier_type PDP Identifier Type
identifier PDP Identifier
See header
Definition at line 242 of file pb_pdp_referral_msg.c.
References chunk_clone, INIT, PB_TCG_MSG_PDP_REFERRAL, and PEN_TCG.
Referenced by pb_pdp_referral_msg_create_from_fqdn().
 {
     private_pb_pdp_referral_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .destroy = _destroy,
             },
             .get_identifier_type = _get_identifier_type,
             .get_identifier = _get_identifier,
         },
         .type = { PEN_TCG, PB_TCG_MSG_PDP_REFERRAL },
         .identifier_type = identifier_type,
         .identifier = chunk_clone(identifier),
     );
     return &this->public.pb_interface;
 }
pb_tnc_msg_t* pb_pdp_referral_msg_create_from_data (chunk_t data)
Create an unprocessed PB-PDP-Referral message from raw data
Parameters
data PB-PDP-Referral message data
See header
Definition at line 291 of file pb_pdp_referral_msg.c.
References chunk_clone, INIT, PB_TCG_MSG_PDP_REFERRAL, and PEN_TCG.
Referenced by pb_tnc_msg_create_from_data().
 {
     private_pb_pdp_referral_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .destroy = _destroy,
             },
             .get_identifier_type = _get_identifier_type,
             .get_identifier = _get_identifier,
             .get_fqdn = _get_fqdn,
         },
         .type = { PEN_TCG, PB_TCG_MSG_PDP_REFERRAL },
         .encoding = chunk_clone(data),
     );
     return &this->public.pb_interface;
 }
pb_tnc_msg_t* pb_pdp_referral_msg_create_from_fqdn (chunk_t fqdn, u_int16_t port)
Create a PB-PDP-Referral message of TCG Type PDP FQDN Identifier
Parameters
fqdn Fully Qualified Domain Name of PDP
port PT-TLS port the PDP is listening on
See header
Definition at line 270 of file pb_pdp_referral_msg.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::get_buf, chunk_t::len, msg, PB_PDP_ID_FQDN, pb_pdp_referral_msg_create(), PDP_REFERRAL_ID_HEADER_SIZE, PDP_REFERRAL_PROTOCOL, PDP_REFERRAL_RESERVED, PEN_TCG, type, bio_writer_t::write_data, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
Referenced by METHOD().
 {
     pb_tnc_msg_t *msg;
     bio_writer_t *writer;
     pen_type_t type = { PEN_TCG, PB_PDP_ID_FQDN };
     writer = bio_writer_create(PDP_REFERRAL_ID_HEADER_SIZE + fqdn.len);
     writer->write_uint8 (writer, PDP_REFERRAL_RESERVED);
     writer->write_uint8 (writer, PDP_REFERRAL_PROTOCOL);
     writer->write_uint16(writer, port);
     writer->write_data  (writer, fqdn);
     msg = pb_pdp_referral_msg_create(type, writer->get_buf(writer));
     writer->destroy(writer);
     return msg;
 }
Variable Documentation
enum_name_t* pb_pdp_identifier_type_names
enum name for pb_pdp_identifier_type_t.