strongSwan: ke_payload_t Struct Reference
ke_payload_t Struct Reference
ke_payload
#include "ke_payload.h"
Public Attributes
payload_t payload_interface
chunk_t(* get_key_exchange_data)(ke_payload_t *this)
diffie_hellman_group_t(* get_dh_group_number)(ke_payload_t *this)
void(* destroy)(ke_payload_t *this)
Detailed Description
Class representing an IKEv1 or IKEv2 key exchange payload.
Definition at line 36 of file ke_payload.h.
Member Data Documentation
void(* ke_payload_t::destroy)(ke_payload_t *this)
Destroys a ke_payload_t object.
Definition at line 60 of file ke_payload.h.
diffie_hellman_group_t(* ke_payload_t::get_dh_group_number)(ke_payload_t *this)
Gets the Diffie-Hellman Group Number of this KE payload (IKEv2 only).
Returns
DH Group Number of this payload
Definition at line 55 of file ke_payload.h.
Referenced by METHOD(), and process_payloads().
chunk_t(* ke_payload_t::get_key_exchange_data)(ke_payload_t *this)
Returns the key exchange data of this KE payload.
Returns
chunk_t pointing to internal data
Definition at line 48 of file ke_payload.h.
Referenced by get_ke(), METHOD(), and process_payloads().
payload_t ke_payload_t::payload_interface
The payload_t interface.
Definition at line 41 of file ke_payload.h.
Referenced by add_ke(), and METHOD().
The documentation for this struct was generated from the following file:
ke_payload.h