strongSwan: pkcs7_data
pkcs7_data
pkcs7
Functions
pkcs7_t * pkcs7_data_load (chunk_t encoding, chunk_t content)
pkcs7_t * pkcs7_data_gen (container_type_t type, va_list args)
Detailed Description
Function Documentation
pkcs7_t* pkcs7_data_gen (container_type_t type, va_list args)
Generate a PKCS#7 data container.
The only accepted builder argument is BUILDER_BLOB.
Parameters
type container type, must be CONTAINER_PKCS7_DATA
args builder_t arguments to use.
See header.
Definition at line 125 of file pkcs7_data.c.
References asn1_build_known_oid(), ASN1_CONTEXT_C_0, ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_wrap(), blob, BUILD_BLOB, BUILD_END, chunk_empty, create_empty(), encoding, chunk_t::len, OID_PKCS7_DATA, and TRUE.
Referenced by METHOD().
 {
     private_pkcs7_data_t *this;
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.len)
     {
         this = create_empty();
         this->content = asn1_wrap(ASN1_OCTET_STRING, "c", blob);
         this->encoding = asn1_wrap(ASN1_SEQUENCE, "mm",
                             asn1_build_known_oid(OID_PKCS7_DATA),
                             asn1_wrap(ASN1_CONTEXT_C_0, "c", this->content));
         return &this->public;
     }
     return NULL;
 }
pkcs7_t* pkcs7_data_load (chunk_t encoding, chunk_t content)
Parse a PKCS#7 "data" container.
Parameters
encoding full contentInfo encoding
content DER encoded content from contentInfo
Returns
CONTAINER_PKCS7_DATA container, NULL on failure
See header.
Definition at line 112 of file pkcs7_data.c.
References chunk_clone, and create_empty().
Referenced by parse_contentInfo().
 {
     private_pkcs7_data_t *this = create_empty();
     this->encoding = chunk_clone(encoding);
     this->content = chunk_clone(content);
     return &this->public;
 }