strongSwan: pts_creds
pts_creds
pts
Classes
struct pts_creds_t
Typedefs
typedef struct pts_creds_t pts_creds_t
Functions
pts_creds_t * pts_creds_create (char *path)
Detailed Description
Typedef Documentation
typedef struct pts_creds_t pts_creds_t
Definition at line 24 of file pts_creds.h.
Function Documentation
pts_creds_t* pts_creds_create (char * path)
Creates an pts_creds_t object
Parameters
path path to the PTS cacerts directory
See header
Definition at line 114 of file pts_creds.c.
References DBG1, DBG_PTS, INIT, load_cacerts(), and mem_cred_create().
Referenced by imv_attestation_agent_create().
 {
     private_pts_creds_t *this;
     if (!path)
     {
         DBG1(DBG_PTS, "no PTS cacerts directory defined");
         return NULL;
     }
     INIT(this,
         .public = {
             .get_set = _get_set,
             .destroy = _destroy,
         },
         .creds = mem_cred_create(),
     );
     load_cacerts(this, path);
     return &this->public;
 }