strongSwan: cmd_connection.c File Reference
cmd_connection.c File Reference
#include "cmd_connection.h"
#include <signal.h>
#include <unistd.h>
#include <utils/debug.h>
#include <processing/jobs/callback_job.h>
#include <threading/thread.h>
#include <daemon.h>
Classes
struct private_cmd_connection_t
Typedefs
typedef enum profile_t profile_t
typedef struct
private_cmd_connection_t private_cmd_connection_t
Enumerations
enum profile_t {
PROF_UNDEF, PROF_V2_PUB, PROF_V2_EAP, PROF_V2_PUB_EAP,
PROF_V1_PUB, PROF_V1_PUB_AM, PROF_V1_XAUTH, PROF_V1_XAUTH_AM,
PROF_V1_XAUTH_PSK, PROF_V1_XAUTH_PSK_AM, PROF_V1_HYBRID, PROF_V1_HYBRID_AM
}
Functions
ENUM (profile_names, PROF_V2_PUB, PROF_V1_HYBRID_AM,"ikev2-pub","ikev2-eap","ikev2-pub-eap","ikev1-pub","ikev1-pub-am","ikev1-xauth","ikev1-xauth-am","ikev1-xauth-psk","ikev1-xauth-psk-am","ikev1-hybrid","ikev1-hybrid-am",)
static void terminate (pid_t pid)
static peer_cfg_t * create_peer_cfg (private_cmd_connection_t *this)
static void add_auth_cfg (private_cmd_connection_t *this, peer_cfg_t *peer_cfg, bool local, auth_class_t class)
static bool add_auth_cfgs (private_cmd_connection_t *this, peer_cfg_t *peer_cfg)
static child_cfg_t * create_child_cfg (private_cmd_connection_t *this, peer_cfg_t *peer_cfg)
static job_requeue_t initiate (private_cmd_connection_t *this)
static void add_ts (private_cmd_connection_t *this, linked_list_t *list, char *string)
static void set_profile (private_cmd_connection_t *this, char *name)
METHOD (cmd_connection_t, handle, bool, private_cmd_connection_t *this, cmd_option_type_t opt, char *arg)
METHOD (cmd_connection_t, destroy, void, private_cmd_connection_t *this)
cmd_connection_t * cmd_connection_create ()
Typedef Documentation
typedef struct private_cmd_connection_t private_cmd_connection_t
Definition at line 30 of file cmd_connection.c.
typedef enum profile_t profile_t
Definition at line 29 of file cmd_connection.c.
Enumeration Type Documentation
enum profile_t
Connection profiles we support
Enumerator
PROF_UNDEF
PROF_V2_PUB
PROF_V2_EAP
PROF_V2_PUB_EAP
PROF_V1_PUB
PROF_V1_PUB_AM
PROF_V1_XAUTH
PROF_V1_XAUTH_AM
PROF_V1_XAUTH_PSK
PROF_V1_XAUTH_PSK_AM
PROF_V1_HYBRID
PROF_V1_HYBRID_AM
Definition at line 35 of file cmd_connection.c.
                {
     PROF_UNDEF,
     PROF_V2_PUB,
     PROF_V2_EAP,
     PROF_V2_PUB_EAP,
     PROF_V1_PUB,
     PROF_V1_PUB_AM,
     PROF_V1_XAUTH,
     PROF_V1_XAUTH_AM,
     PROF_V1_XAUTH_PSK,
     PROF_V1_XAUTH_PSK_AM,
     PROF_V1_HYBRID,
     PROF_V1_HYBRID_AM,
 };
Function Documentation
static void add_auth_cfg (private_cmd_connection_t * this, peer_cfg_t * peer_cfg, bool local, auth_class_t class) static
Add a single auth cfg of given class to peer cfg
Definition at line 206 of file cmd_connection.c.
References auth_cfg_t::add, peer_cfg_t::add_auth_cfg, auth_cfg_create(), AUTH_CLASS_EAP, AUTH_CLASS_XAUTH, AUTH_RULE_AUTH_CLASS, AUTH_RULE_EAP_IDENTITY, AUTH_RULE_IDENTITY, AUTH_RULE_IDENTITY_LOOSE, AUTH_RULE_XAUTH_IDENTITY, host, id, identification_create_from_string(), identity, server, and TRUE.
Referenced by add_auth_cfgs(), and peer_cfg_create().
 {
     identification_t *id;
     auth_cfg_t *auth;
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, class);
     if (local)
     {
         id = identification_create_from_string(this->identity);
         if (this->xautheap)
         {
             switch (class)
             {
                 case AUTH_CLASS_EAP:
                     auth->add(auth, AUTH_RULE_EAP_IDENTITY,
                             identification_create_from_string(this->xautheap));
                     break;
                 case AUTH_CLASS_XAUTH:
                     auth->add(auth, AUTH_RULE_XAUTH_IDENTITY,
                             identification_create_from_string(this->xautheap));
                     break;
                 default:
                     break;
             }
         }
     }
     else
     {
         if (this->server)
         {
             id = identification_create_from_string(this->server);
         }
         else
         {
             id = identification_create_from_string(this->host);
         }
         auth->add(auth, AUTH_RULE_IDENTITY_LOOSE, TRUE);
     }
     auth->add(auth, AUTH_RULE_IDENTITY, id);
     peer_cfg->add_auth_cfg(peer_cfg, auth, local);
 }
static bool add_auth_cfgs (private_cmd_connection_t * this, peer_cfg_t * peer_cfg) static
Attach authentication configs to peer config
Definition at line 253 of file cmd_connection.c.
References add_auth_cfg(), AUTH_CLASS_ANY, AUTH_CLASS_EAP, AUTH_CLASS_PSK, AUTH_CLASS_PUBKEY, AUTH_CLASS_XAUTH, DBG1, DBG_CFG, FALSE, PROF_UNDEF, PROF_V1_HYBRID, PROF_V1_HYBRID_AM, PROF_V1_PUB, PROF_V1_PUB_AM, PROF_V1_XAUTH, PROF_V1_XAUTH_AM, PROF_V1_XAUTH_PSK, PROF_V1_XAUTH_PSK_AM, PROF_V2_EAP, PROF_V2_PUB, PROF_V2_PUB_EAP, and TRUE.
Referenced by initiate().
 {
     if (this->profile == PROF_UNDEF)
     {
         if (this->key_seen)
         {
             this->profile = PROF_V2_PUB;
         }
         else
         {
             this->profile = PROF_V2_EAP;
         }
     }
     switch (this->profile)
     {
         case PROF_V2_PUB:
         case PROF_V2_PUB_EAP:
         case PROF_V1_PUB:
         case PROF_V1_XAUTH:
         case PROF_V1_PUB_AM:
         case PROF_V1_XAUTH_AM:
             if (!this->key_seen)
             {
                 DBG1(DBG_CFG, "missing private key for profile %N",
                      profile_names, this->profile);
                 return FALSE;
             }
             break;
         default:
             break;
     }
     switch (this->profile)
     {
         case PROF_V2_PUB:
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_PUBKEY);
             add_auth_cfg(this, peer_cfg, FALSE, AUTH_CLASS_ANY);
             break;
         case PROF_V2_EAP:
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_EAP);
             add_auth_cfg(this, peer_cfg, FALSE, AUTH_CLASS_ANY);
             break;
         case PROF_V2_PUB_EAP:
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_PUBKEY);
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_EAP);
             add_auth_cfg(this, peer_cfg, FALSE, AUTH_CLASS_ANY);
             break;
         case PROF_V1_PUB:
         case PROF_V1_PUB_AM:
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_PUBKEY);
             add_auth_cfg(this, peer_cfg, FALSE, AUTH_CLASS_PUBKEY);
             break;
         case PROF_V1_XAUTH:
         case PROF_V1_XAUTH_AM:
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_PUBKEY);
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_XAUTH);
             add_auth_cfg(this, peer_cfg, FALSE, AUTH_CLASS_PUBKEY);
             break;
         case PROF_V1_XAUTH_PSK:
         case PROF_V1_XAUTH_PSK_AM:
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_PSK);
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_XAUTH);
             add_auth_cfg(this, peer_cfg, FALSE, AUTH_CLASS_PSK);
             break;
         case PROF_V1_HYBRID:
         case PROF_V1_HYBRID_AM:
             add_auth_cfg(this, peer_cfg, TRUE, AUTH_CLASS_XAUTH);
             add_auth_cfg(this, peer_cfg, FALSE, AUTH_CLASS_PUBKEY);
             break;
         default:
             return FALSE;
     }
     return TRUE;
 }
static void add_ts (private_cmd_connection_t * this, linked_list_t * list, char * string) static
Create a traffic selector from string, add to list
Definition at line 447 of file cmd_connection.c.
References DBG1, DBG_CFG, linked_list_t::insert_last, and traffic_selector_create_from_cidr().
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     ts = traffic_selector_create_from_cidr(string, 0, 0, 65535);
     if (!ts)
     {
         DBG1(DBG_CFG, "invalid traffic selector: %s", string);
         exit(1);
     }
     list->insert_last(list, ts);
 }
static child_cfg_t* create_child_cfg (private_cmd_connection_t * this, peer_cfg_t * peer_cfg) static
Attach child config to peer config
Definition at line 331 of file cmd_connection.c.
References ACTION_NONE, peer_cfg_t::add_child_cfg, child_cfg_t::add_proposal, child_cfg_t::add_traffic_selector, peer_cfg_t::add_virtual_ip, child_cfg_create(), FALSE, child_cfg_t::get_ref, traffic_selector_t::get_type, host_create_from_string(), lifetime_cfg_t::life, MODE_TUNNEL, proposal, proposal_create_default(), proposal_create_default_aead(), PROTO_ESP, SUCCESS, lifetime_cfg_t::time, traffic_selector_create_from_string(), TRUE, TS_IPV4_ADDR_RANGE, and TS_IPV6_ADDR_RANGE.
Referenced by initiate().
 {
     child_cfg_t *child_cfg;
     traffic_selector_t *ts;
     proposal_t *proposal;
     bool has_v4 = FALSE, has_v6 = FALSE;
     lifetime_cfg_t lifetime = {
         .time = {
             .life = 10800 /* 3h */,
             .rekey = 10200 /* 2h50min */,
             .jitter = 300 /* 5min */
         }
     };
     child_cfg = child_cfg_create("cmd", &lifetime,
                                  NULL, FALSE, MODE_TUNNEL, /* updown, hostaccess */
                                  ACTION_NONE, ACTION_NONE, ACTION_NONE, FALSE,
                                  0, 0, NULL, NULL, 0);
     if (this->child_proposals->get_count(this->child_proposals))
     {
         while (this->child_proposals->remove_first(this->child_proposals,
                                                 (void**)&proposal) == SUCCESS)
         {
             child_cfg->add_proposal(child_cfg, proposal);
         }
     }
     else
     {
         child_cfg->add_proposal(child_cfg, proposal_create_default(PROTO_ESP));
         child_cfg->add_proposal(child_cfg,
                                 proposal_create_default_aead(PROTO_ESP));
     }
     while (this->local_ts->remove_first(this->local_ts, (void**)&ts) == SUCCESS)
     {
         child_cfg->add_traffic_selector(child_cfg, TRUE, ts);
     }
     if (this->remote_ts->get_count(this->remote_ts) == 0)
     {
         /* add a 0.0.0.0/0 TS for remote side if none given */
         ts = traffic_selector_create_from_string(0, TS_IPV4_ADDR_RANGE,
                                     "0.0.0.0", 0, "255.255.255.255", 65535);
         this->remote_ts->insert_last(this->remote_ts, ts);
         has_v4 = TRUE;
     }
     while (this->remote_ts->remove_first(this->remote_ts,
                                          (void**)&ts) == SUCCESS)
     {
         switch (ts->get_type(ts))
         {
             case TS_IPV4_ADDR_RANGE:
                 has_v4 = TRUE;
                 break;
             case TS_IPV6_ADDR_RANGE:
                 has_v6 = TRUE;
                 break;
         }
         child_cfg->add_traffic_selector(child_cfg, FALSE, ts);
     }
     if (has_v4)
     {
         peer_cfg->add_virtual_ip(peer_cfg, host_create_from_string("0.0.0.0", 0));
     }
     if (has_v6)
     {
         peer_cfg->add_virtual_ip(peer_cfg, host_create_from_string("::", 0));
     }
     peer_cfg->add_child_cfg(peer_cfg, child_cfg->get_ref(child_cfg));
     return child_cfg;
 }
static peer_cfg_t* create_peer_cfg (private_cmd_connection_t * this) static
Create peer config with associated ike config
Definition at line 141 of file cmd_connection.c.
References ike_cfg_t::add_proposal, CERT_SEND_IF_ASKED, charon, FALSE, FRAGMENTATION_NO, socket_manager_t::get_port, host, IKE_ANY, ike_cfg_create(), IKEV1, IKEV2, IKEV2_NATT_PORT, IKEV2_UDP_PORT, peer_cfg_create(), PROF_UNDEF, PROF_V1_HYBRID, PROF_V1_HYBRID_AM, PROF_V1_PUB, PROF_V1_PUB_AM, PROF_V1_XAUTH, PROF_V1_XAUTH_AM, PROF_V1_XAUTH_PSK, PROF_V1_XAUTH_PSK_AM, PROF_V2_EAP, PROF_V2_PUB, PROF_V2_PUB_EAP, proposal, proposal_create_default(), proposal_create_default_aead(), PROTO_IKE, daemon_t::socket, SUCCESS, TRUE, UNIQUE_REPLACE, and version.
Referenced by initiate().
 {
     ike_cfg_t *ike_cfg;
     peer_cfg_t *peer_cfg;
     u_int16_t local_port, remote_port = IKEV2_UDP_PORT;
     ike_version_t version = IKE_ANY;
     bool aggressive = FALSE;
     proposal_t *proposal;
     switch (this->profile)
     {
         case PROF_UNDEF:
         case PROF_V2_PUB:
         case PROF_V2_EAP:
         case PROF_V2_PUB_EAP:
             version = IKEV2;
             break;
         case PROF_V1_PUB_AM:
         case PROF_V1_XAUTH_AM:
         case PROF_V1_XAUTH_PSK_AM:
         case PROF_V1_HYBRID_AM:
             aggressive = TRUE;
             /* FALL */
         case PROF_V1_PUB:
         case PROF_V1_XAUTH:
         case PROF_V1_XAUTH_PSK:
         case PROF_V1_HYBRID:
             version = IKEV1;
             break;
     }
     local_port = charon->socket->get_port(charon->socket, FALSE);
     if (local_port != IKEV2_UDP_PORT)
     {
         remote_port = IKEV2_NATT_PORT;
     }
     ike_cfg = ike_cfg_create(version, TRUE, FALSE, "0.0.0.0", local_port,
                     this->host, remote_port, FRAGMENTATION_NO, 0);
     if (this->ike_proposals->get_count(this->ike_proposals))
     {
         while (this->ike_proposals->remove_first(this->ike_proposals,
                                                  (void**)&proposal) == SUCCESS)
         {
             ike_cfg->add_proposal(ike_cfg, proposal);
         }
     }
     else
     {
         ike_cfg->add_proposal(ike_cfg, proposal_create_default(PROTO_IKE));
         ike_cfg->add_proposal(ike_cfg, proposal_create_default_aead(PROTO_IKE));
     }
     peer_cfg = peer_cfg_create("cmd", ike_cfg,
                     CERT_SEND_IF_ASKED, UNIQUE_REPLACE, 1, /* keyingtries */
                     36000, 0, /* rekey 10h, reauth none */
                     600, 600, /* jitter, over 10min */
                     TRUE, aggressive, TRUE, /* mobike, aggressive, pull */
                     30, 0, /* DPD delay, timeout */
                     FALSE, NULL, NULL); /* mediation */
     return peer_cfg;
 }
ENUM (profile_names , PROF_V2_PUB , PROF_V1_HYBRID_AM , "ikev2-pub" , "ikev2-eap" , "ikev2-pub-eap" , "ikev1-pub" , "ikev1-pub-am" , "ikev1-xauth" , "ikev1-xauth-am" , "ikev1-xauth-psk" , "ikev1-xauth-psk-am" , "ikev1-hybrid" , "ikev1-hybrid-am")
static job_requeue_t initiate (private_cmd_connection_t * this) static
Initiate the configured connection
Definition at line 406 of file cmd_connection.c.
References add_auth_cfgs(), charon, daemon_t::controller, controller_cb_empty(), create_child_cfg(), create_peer_cfg(), DBG1, DBG_CFG, peer_cfg_t::destroy, FALSE, host, identity, controller_t::initiate, JOB_REQUEUE_NONE, SUCCESS, and terminate().
Referenced by build_response(), cmd_connection_create(), del_connection(), initiate_connection(), manage_commands(), METHOD(), process_reauthentication(), process_request(), process_response(), process_start(), starter_stroke_initiate_conn(), and terminate_connection().
 {
     peer_cfg_t *peer_cfg;
     child_cfg_t *child_cfg;
     pid_t pid = this->pid;
     if (!this->host)
     {
         DBG1(DBG_CFG, "unable to initiate, missing --host option");
         terminate(pid);
         return JOB_REQUEUE_NONE;
     }
     if (!this->identity)
     {
         DBG1(DBG_CFG, "unable to initiate, missing --identity option");
         terminate(pid);
         return JOB_REQUEUE_NONE;
     }
     peer_cfg = create_peer_cfg(this);
     if (!add_auth_cfgs(this, peer_cfg))
     {
         peer_cfg->destroy(peer_cfg);
         terminate(pid);
         return JOB_REQUEUE_NONE;
     }
     child_cfg = create_child_cfg(this, peer_cfg);
     if (charon->controller->initiate(charon->controller, peer_cfg, child_cfg,
                                 controller_cb_empty, NULL, 0, FALSE) != SUCCESS)
     {
         terminate(pid);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (cmd_connection_t , handle , bool , private_cmd_connection_t * this, cmd_option_type_t opt, char * arg)
Definition at line 476 of file cmd_connection.c.
References add_ts(), CMD_OPT_AGENT, CMD_OPT_AH_PROPOSAL, CMD_OPT_EAP_IDENTITY, CMD_OPT_ESP_PROPOSAL, CMD_OPT_HOST, CMD_OPT_IDENTITY, CMD_OPT_IKE_PROPOSAL, CMD_OPT_LOCAL_TS, CMD_OPT_PKCS12, CMD_OPT_PROFILE, CMD_OPT_REMOTE_IDENTITY, CMD_OPT_REMOTE_TS, CMD_OPT_RSA, CMD_OPT_XAUTH_USER, FALSE, host, identity, proposal, proposal_create_from_string(), PROTO_AH, PROTO_ESP, PROTO_IKE, server, set_profile(), and TRUE.
 {
     proposal_t *proposal;
     switch (opt)
     {
         case CMD_OPT_HOST:
             this->host = arg;
             break;
         case CMD_OPT_REMOTE_IDENTITY:
             this->server = arg;
             break;
         case CMD_OPT_IDENTITY:
             this->identity = arg;
             break;
         case CMD_OPT_EAP_IDENTITY:
         case CMD_OPT_XAUTH_USER:
             this->xautheap = arg;
             break;
         case CMD_OPT_RSA:
         case CMD_OPT_AGENT:
         case CMD_OPT_PKCS12:
             this->key_seen = TRUE;
             break;
         case CMD_OPT_LOCAL_TS:
             add_ts(this, this->local_ts, arg);
             break;
         case CMD_OPT_REMOTE_TS:
             add_ts(this, this->remote_ts, arg);
             break;
         case CMD_OPT_IKE_PROPOSAL:
             proposal = proposal_create_from_string(PROTO_IKE, arg);
             if (!proposal)
             {
                 exit(1);
             }
             this->ike_proposals->insert_last(this->ike_proposals, proposal);
             break;
         case CMD_OPT_ESP_PROPOSAL:
             proposal = proposal_create_from_string(PROTO_ESP, arg);
             if (!proposal)
             {
                 exit(1);
             }
             this->child_proposals->insert_last(this->child_proposals, proposal);
             break;
         case CMD_OPT_AH_PROPOSAL:
             proposal = proposal_create_from_string(PROTO_AH, arg);
             if (!proposal)
             {
                 exit(1);
             }
             this->child_proposals->insert_last(this->child_proposals, proposal);
             break;
         case CMD_OPT_PROFILE:
             set_profile(this, arg);
             break;
         default:
             return FALSE;
     }
     return TRUE;
 }
METHOD (cmd_connection_t , destroy , void , private_cmd_connection_t * this)
Definition at line 540 of file cmd_connection.c.
References destroy(), and free().
 {
     this->ike_proposals->destroy_offset(this->ike_proposals,
                                 offsetof(proposal_t, destroy));
     this->child_proposals->destroy_offset(this->child_proposals,
                                 offsetof(proposal_t, destroy));
     this->local_ts->destroy_offset(this->local_ts,
                                 offsetof(traffic_selector_t, destroy));
     this->remote_ts->destroy_offset(this->remote_ts,
                                 offsetof(traffic_selector_t, destroy));
     free(this);
 }
static void set_profile (private_cmd_connection_t * this, char * name) static
Parse profile name identifier
Definition at line 464 of file cmd_connection.c.
References DBG1, DBG_CFG, and enum_from_name.
Referenced by METHOD().
 {
     profile_t profile;
     if (!enum_from_name(profile_names, name, &profile))
     {
         DBG1(DBG_CFG, "unknown connection profile: %s", name);
         exit(1);
     }
     this->profile = profile;
 }
static void terminate (pid_t pid) static
Shut down application
Definition at line 133 of file cmd_connection.c.
Referenced by initiate(), manage_commands(), tnc_imc_create_from_functions(), and tnc_imv_create_from_functions().
 {
     kill(pid, SIGUSR1);
 }