strongSwan: dhcp_socket.c File Reference
dhcp_socket.c File Reference
#include "dhcp_socket.h"
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <netinet/udp.h>
#include <linux/if_arp.h>
#include <linux/if_ether.h>
#include <linux/filter.h>
#include <collections/linked_list.h>
#include <utils/identification.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <threading/thread.h>
#include <hydra.h>
#include <daemon.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_dhcp_socket_t
Macros
#define DHCP_SERVER_PORT 67
#define DHCP_CLIENT_PORT 68
#define DHCP_TRIES 5
Typedefs
typedef struct
private_dhcp_socket_t private_dhcp_socket_t
Enumerations
enum dhcp_opcode_t { BOOTREQUEST = 1, BOOTREPLY = 2 }
enum dhcp_option_type_t {
DHCP_DNS_SERVER = 6, DHCP_HOST_NAME = 12, DHCP_NBNS_SERVER = 44, DHCP_REQUESTED_IP = 50,
DHCP_MESSAGE_TYPE = 53, DHCP_SERVER_ID = 54, DHCP_PARAM_REQ_LIST = 55, DHCP_CLIENT_ID = 61,
DHCP_OPTEND = 255
}
enum dhcp_message_type_t {
DHCP_DISCOVER = 1, DHCP_OFFER = 2, DHCP_REQUEST = 3, DHCP_DECLINE = 4,
DHCP_ACK = 5, DHCP_NAK = 6, DHCP_RELEASE = 7, DHCP_INFORM = 8
}
Functions
struct __attribute__ ((packed))
static int prepare_dhcp (private_dhcp_socket_t *this, dhcp_transaction_t *transaction, dhcp_message_type_t type, dhcp_t *dhcp)
static bool send_dhcp (private_dhcp_socket_t *this, dhcp_transaction_t *transaction, dhcp_t *dhcp, int optlen)
static bool discover (private_dhcp_socket_t *this, dhcp_transaction_t *transaction)
static bool request (private_dhcp_socket_t *this, dhcp_transaction_t *transaction)
METHOD (dhcp_socket_t, enroll, dhcp_transaction_t *, private_dhcp_socket_t *this, identification_t *identity)
METHOD (dhcp_socket_t, release, void, private_dhcp_socket_t *this, dhcp_transaction_t *transaction)
static void handle_offer (private_dhcp_socket_t *this, dhcp_t *dhcp, int optlen)
static void handle_ack (private_dhcp_socket_t *this, dhcp_t *dhcp, int optlen)
static bool receive_dhcp (private_dhcp_socket_t *this, int fd, watcher_event_t event)
METHOD (dhcp_socket_t, destroy, void, private_dhcp_socket_t *this)
static bool bind_to_device (int fd, char *iface)
dhcp_socket_t * dhcp_socket_create ()
Variables
dhcp_option_t
dhcp_t
Macro Definition Documentation
#define DHCP_CLIENT_PORT 68
Definition at line 39 of file dhcp_socket.c.
Referenced by dhcp_socket_create().
#define DHCP_SERVER_PORT 67
Definition at line 38 of file dhcp_socket.c.
Referenced by dhcp_socket_create(), and handle_offer().
#define DHCP_TRIES 5
Definition at line 40 of file dhcp_socket.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_dhcp_socket_t private_dhcp_socket_t
Definition at line 42 of file dhcp_socket.c.
Enumeration Type Documentation
enum dhcp_message_type_t
DHCP messages types in the DHCP_MESSAGE_TYPE option
Enumerator
DHCP_DISCOVER
DHCP_OFFER
DHCP_REQUEST
DHCP_DECLINE
DHCP_ACK
DHCP_NAK
DHCP_RELEASE
DHCP_INFORM
Definition at line 141 of file dhcp_socket.c.
              {
     DHCP_DISCOVER = 1,
     DHCP_OFFER = 2,
     DHCP_REQUEST = 3,
     DHCP_DECLINE = 4,
     DHCP_ACK = 5,
     DHCP_NAK = 6,
     DHCP_RELEASE = 7,
     DHCP_INFORM = 8,
 } dhcp_message_type_t;
enum dhcp_opcode_t
DHCP opcode (or BOOTP actually)
Enumerator
BOOTREQUEST
BOOTREPLY
Definition at line 118 of file dhcp_socket.c.
              {
     BOOTREQUEST = 1,
     BOOTREPLY = 2,
 } dhcp_opcode_t;
enum dhcp_option_type_t
Some DHCP options used
Enumerator
DHCP_DNS_SERVER
DHCP_HOST_NAME
DHCP_NBNS_SERVER
DHCP_REQUESTED_IP
DHCP_MESSAGE_TYPE
DHCP_SERVER_ID
DHCP_PARAM_REQ_LIST
DHCP_CLIENT_ID
DHCP_OPTEND
Definition at line 126 of file dhcp_socket.c.
              {
     DHCP_DNS_SERVER = 6,
     DHCP_HOST_NAME = 12,
     DHCP_NBNS_SERVER = 44,
     DHCP_REQUESTED_IP = 50,
     DHCP_MESSAGE_TYPE = 53,
     DHCP_SERVER_ID = 54,
     DHCP_PARAM_REQ_LIST = 55,
     DHCP_CLIENT_ID = 61,
     DHCP_OPTEND = 255,
 } dhcp_option_type_t;
Function Documentation
static bool bind_to_device (int fd, char * iface) static
Bind a socket to a particular interface name
Definition at line 648 of file dhcp_socket.c.
References DBG1, DBG_CFG, FALSE, memcpy, setsockopt, strerror, and TRUE.
Referenced by dhcp_socket_create().
 {
     struct ifreq ifreq;
     if (strlen(iface) > sizeof(ifreq.ifr_name))
     {
         DBG1(DBG_CFG, "name for DHCP interface too long: '%s'", iface);
         return FALSE;
     }
     memcpy(ifreq.ifr_name, iface, sizeof(ifreq.ifr_name));
     if (setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, &ifreq, sizeof(ifreq)))
     {
         DBG1(DBG_CFG, "binding DHCP socket to '%s' failed: %s",
              iface, strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
static bool discover (private_dhcp_socket_t * this, dhcp_transaction_t * transaction) static
Send DHCP discover using a given transaction
Definition at line 286 of file dhcp_socket.c.
References DBG1, DBG_CFG, DHCP_DISCOVER, DHCP_DNS_SERVER, DHCP_NBNS_SERVER, DHCP_OPTEND, dhcp_option_t, DHCP_PARAM_REQ_LIST, dhcp_t, dst, FALSE, prepare_dhcp(), send_dhcp(), strerror, and TRUE.
Referenced by handle_offer(), and METHOD().
 {
     dhcp_option_t *option;
     dhcp_t dhcp;
     int optlen;
     optlen = prepare_dhcp(this, transaction, DHCP_DISCOVER, &dhcp);
     DBG1(DBG_CFG, "sending DHCP DISCOVER to %H", this->dst);
     option = (dhcp_option_t*)&dhcp.options[optlen];
     option->type = DHCP_PARAM_REQ_LIST;
     option->len = 2;
     option->data[0] = DHCP_DNS_SERVER;
     option->data[1] = DHCP_NBNS_SERVER;
     optlen += sizeof(dhcp_option_t) + option->len;
     dhcp.options[optlen++] = DHCP_OPTEND;
     if (!send_dhcp(this, transaction, &dhcp, optlen))
     {
         DBG1(DBG_CFG, "sending DHCP DISCOVER failed: %s", strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
static void handle_ack (private_dhcp_socket_t * this, dhcp_t * dhcp, int optlen) static
Handle a DHCP ACK
Definition at line 535 of file dhcp_socket.c.
References condvar_t::broadcast, chunk_from_thing, condvar, DBG1, DBG_CFG, enumerator_t::destroy, host_t::destroy, enumerator_t::enumerate, dhcp_transaction_t::get_id, host_create_from_chunk(), mutex_t::lock, mutex, request(), and mutex_t::unlock.
Referenced by receive_dhcp().
 {
     dhcp_transaction_t *transaction;
     enumerator_t *enumerator;
     host_t *offer;
     offer = host_create_from_chunk(AF_INET,
                         chunk_from_thing(dhcp->your_address), 0);
     this->mutex->lock(this->mutex);
     enumerator = this->request->create_enumerator(this->request);
     while (enumerator->enumerate(enumerator, &transaction))
     {
         if (transaction->get_id(transaction) == dhcp->transaction_id)
         {
             DBG1(DBG_CFG, "received DHCP ACK for %H", offer);
             this->request->remove_at(this->request, enumerator);
             this->completed->insert_last(this->completed, transaction);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     this->condvar->broadcast(this->condvar);
     offer->destroy(offer);
 }
static void handle_offer (private_dhcp_socket_t * this, dhcp_t * dhcp, int optlen) static
Handle a DHCP OFFER
Definition at line 465 of file dhcp_socket.c.
References dhcp_transaction_t::add_attribute, condvar_t::broadcast, chunk_create(), chunk_from_thing, host_t::clone, condvar, DBG1, DBG_CFG, enumerator_t::destroy, host_t::destroy, DHCP_DNS_SERVER, DHCP_NBNS_SERVER, DHCP_OPTEND, dhcp_option_t, DHCP_SERVER_ID, DHCP_SERVER_PORT, discover(), enumerator_t::enumerate, dhcp_transaction_t::get_id, host_create_from_chunk(), INTERNAL_IP4_DNS, INTERNAL_IP4_NBNS, mutex_t::lock, mutex, request(), server, dhcp_transaction_t::set_address, dhcp_transaction_t::set_server, and mutex_t::unlock.
Referenced by receive_dhcp().
 {
     dhcp_transaction_t *transaction = NULL;
     enumerator_t *enumerator;
     host_t *offer, *server = NULL;
     offer = host_create_from_chunk(AF_INET,
                     chunk_from_thing(dhcp->your_address), 0);
     this->mutex->lock(this->mutex);
     enumerator = this->discover->create_enumerator(this->discover);
     while (enumerator->enumerate(enumerator, &transaction))
     {
         if (transaction->get_id(transaction) == dhcp->transaction_id)
         {
             this->discover->remove_at(this->discover, enumerator);
             this->request->insert_last(this->request, transaction);
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (transaction)
     {
         int optsize, optpos = 0, pos;
         dhcp_option_t *option;
         while (optlen > sizeof(dhcp_option_t))
         {
             option = (dhcp_option_t*)&dhcp->options[optpos];
             optsize = sizeof(dhcp_option_t) + option->len;
             if (option->type == DHCP_OPTEND || optlen < optsize)
             {
                 break;
             }
             if (option->type == DHCP_DNS_SERVER ||
                 option->type == DHCP_NBNS_SERVER)
             {
                 for (pos = 0; pos + 4 <= option->len; pos += 4)
                 {
                     transaction->add_attribute(transaction, option->type ==
                         DHCP_DNS_SERVER ? INTERNAL_IP4_DNS : INTERNAL_IP4_NBNS,
                         chunk_create((char*)&option->data[pos], 4));
                 }
             }
             if (!server && option->type == DHCP_SERVER_ID && option->len == 4)
             {
                 server = host_create_from_chunk(AF_INET,
                             chunk_create(option->data, 4), DHCP_SERVER_PORT);
             }
             optlen -= optsize;
             optpos += optsize;
         }
         if (!server)
         {
             server = host_create_from_chunk(AF_INET,
                 chunk_from_thing(dhcp->server_address), DHCP_SERVER_PORT);
         }
         DBG1(DBG_CFG, "received DHCP OFFER %H from %H", offer, server);
         transaction->set_address(transaction, offer->clone(offer));
         transaction->set_server(transaction, server);
     }
     this->mutex->unlock(this->mutex);
     this->condvar->broadcast(this->condvar);
     offer->destroy(offer);
 }
METHOD (dhcp_socket_t , enroll , dhcp_transaction_t * , private_dhcp_socket_t * this, identification_t * identity)
Definition at line 367 of file dhcp_socket.c.
References condvar, DBG1, DBG_CFG, dhcp_transaction_t::destroy, dhcp_transaction_create(), DHCP_TRIES, discover(), id, mutex_t::lock, mutex, request(), rng, SUCCESS, condvar_t::timed_wait, and mutex_t::unlock.
 {
     dhcp_transaction_t *transaction;
     u_int32_t id;
     int try;
     if (!this->rng->get_bytes(this->rng, sizeof(id), (u_int8_t*)&id))
     {
         DBG1(DBG_CFG, "DHCP DISCOVER failed, no transaction ID");
         return NULL;
     }
     transaction = dhcp_transaction_create(id, identity);
     this->mutex->lock(this->mutex);
     this->discover->insert_last(this->discover, transaction);
     try = 1;
     while (try <= DHCP_TRIES && discover(this, transaction))
     {
         if (!this->condvar->timed_wait(this->condvar, this->mutex, 1000 * try) &&
             this->request->find_first(this->request, NULL,
                                       (void**)&transaction) == SUCCESS)
         {
             break;
         }
         try++;
     }
     if (this->discover->remove(this->discover, transaction, NULL))
     {   /* no OFFER received */
         this->mutex->unlock(this->mutex);
         transaction->destroy(transaction);
         DBG1(DBG_CFG, "DHCP DISCOVER timed out");
         return NULL;
     }
     try = 1;
     while (try <= DHCP_TRIES && request(this, transaction))
     {
         if (!this->condvar->timed_wait(this->condvar, this->mutex, 1000 * try) &&
             this->completed->remove(this->completed, transaction, NULL))
         {
             break;
         }
         try++;
     }
     if (this->request->remove(this->request, transaction, NULL))
     {   /* no ACK received */
         this->mutex->unlock(this->mutex);
         transaction->destroy(transaction);
         DBG1(DBG_CFG, "DHCP REQUEST timed out");
         return NULL;
     }
     this->mutex->unlock(this->mutex);
     return transaction;
 }
METHOD (dhcp_socket_t , release , void , private_dhcp_socket_t * this, dhcp_transaction_t * transaction)
Definition at line 424 of file dhcp_socket.c.
References DBG1, DBG_CFG, DHCP_OPTEND, dhcp_option_t, DHCP_RELEASE, DHCP_SERVER_ID, dhcp_t, dhcp_transaction_t::get_address, host_t::get_address, dhcp_transaction_t::get_server, if(), chunk_t::len, memcpy, min, prepare_dhcp(), chunk_t::ptr, send_dhcp(), server, and strerror.
 {
     dhcp_option_t *option;
     dhcp_t dhcp;
     host_t *release, *server;
     chunk_t chunk;
     int optlen;
     optlen = prepare_dhcp(this, transaction, DHCP_RELEASE, &dhcp);
     release = transaction->get_address(transaction);
     server = transaction->get_server(transaction);
     if (!release || !server)
     {
         return;
     }
     DBG1(DBG_CFG, "sending DHCP RELEASE for %H to %H", release, server);
     chunk = release->get_address(release);
     memcpy(&dhcp.client_address, chunk.ptr,
            min(chunk.len, sizeof(dhcp.client_address)));
     option = (dhcp_option_t*)&dhcp.options[optlen];
     option->type = DHCP_SERVER_ID;
     option->len = 4;
     chunk = server->get_address(server);
     memcpy(option->data, chunk.ptr, min(chunk.len, option->len));
     optlen += sizeof(dhcp_option_t) + option->len;
     dhcp.options[optlen++] = DHCP_OPTEND;
     if (!send_dhcp(this, transaction, &dhcp, optlen))
     {
         DBG1(DBG_CFG, "sending DHCP RELEASE failed: %s", strerror(errno));
     }
 }
METHOD (dhcp_socket_t , destroy , void , private_dhcp_socket_t * this)
Definition at line 616 of file dhcp_socket.c.
References close, condvar, mutex_t::destroy, condvar_t::destroy, destroy(), DESTROY_IF, discover(), dst, free(), lib, mutex, receive(), watcher_t::remove, request(), rng, send, condvar_t::signal, and library_t::watcher.
 {
     while (this->waiting)
     {
         this->condvar->signal(this->condvar);
     }
     if (this->send > 0)
     {
         close(this->send);
     }
     if (this->receive > 0)
     {
         lib->watcher->remove(lib->watcher, this->receive);
         close(this->receive);
     }
     this->mutex->destroy(this->mutex);
     this->condvar->destroy(this->condvar);
     this->discover->destroy_offset(this->discover,
                                 offsetof(dhcp_transaction_t, destroy));
     this->request->destroy_offset(this->request,
                                 offsetof(dhcp_transaction_t, destroy));
     this->completed->destroy_offset(this->completed,
                                 offsetof(dhcp_transaction_t, destroy));
     DESTROY_IF(this->rng);
     DESTROY_IF(this->dst);
     free(this);
 }
static int prepare_dhcp (private_dhcp_socket_t * this, dhcp_transaction_t * transaction, dhcp_message_type_t type, dhcp_t * dhcp) static
Prepare a DHCP message for a given transaction
Definition at line 186 of file dhcp_socket.c.
References BOOTREQUEST, chunk_equals(), chunk_from_chars, chunk_hash_static(), host_t::destroy, DHCP_CLIENT_ID, DHCP_HOST_NAME, DHCP_MESSAGE_TYPE, dhcp_option_t, dst, host_t::get_address, identification_t::get_encoding, dhcp_transaction_t::get_id, dhcp_transaction_t::get_identity, kernel_interface_t::get_source_addr, identification_t::get_type, hydra, id, ID_FQDN, identity, hydra_t::kernel_interface, chunk_t::len, memcpy, memset, min, chunk_t::ptr, and src.
Referenced by discover(), METHOD(), and request().
 {
     chunk_t chunk, broadcast = chunk_from_chars(0xFF,0xFF,0xFF,0xFF);
     identification_t *identity;
     dhcp_option_t *option;
     int optlen = 0;
     host_t *src;
     u_int32_t id;
     memset(dhcp, 0, sizeof(*dhcp));
     dhcp->opcode = BOOTREQUEST;
     dhcp->hw_type = ARPHRD_ETHER;
     dhcp->hw_addr_len = 6;
     dhcp->transaction_id = transaction->get_id(transaction);
     if (chunk_equals(broadcast, this->dst->get_address(this->dst)))
     {
         /* Set broadcast flag to get broadcasted replies, as we actually
          * do not own the MAC we request an address for. */
         dhcp->flags = htons(0x8000);
         /* TODO: send with 0.0.0.0 source address */
     }
     else
     {
         /* act as relay agent */
         src = hydra->kernel_interface->get_source_addr(hydra->kernel_interface,
                                                        this->dst, NULL);
         if (src)
         {
             memcpy(&dhcp->gateway_address, src->get_address(src).ptr,
                    sizeof(dhcp->gateway_address));
             src->destroy(src);
         }
     }
     identity = transaction->get_identity(transaction);
     chunk = identity->get_encoding(identity);
     /* magic bytes, a locally administered unicast MAC */
     dhcp->client_hw_addr[0] = 0x7A;
     dhcp->client_hw_addr[1] = 0xA7;
     /* with ID specific postfix */
     if (this->identity_lease)
     {
         id = htonl(chunk_hash_static(chunk));
     }
     else
     {
         id = transaction->get_id(transaction);
     }
     memcpy(&dhcp->client_hw_addr[2], &id, sizeof(id));
     dhcp->magic_cookie = htonl(0x63825363);
     option = (dhcp_option_t*)&dhcp->options[optlen];
     option->type = DHCP_MESSAGE_TYPE;
     option->len = 1;
     option->data[0] = type;
     optlen += sizeof(dhcp_option_t) + option->len;
     if (identity->get_type(identity) == ID_FQDN)
     {
         option = (dhcp_option_t*)&dhcp->options[optlen];
         option->type = DHCP_HOST_NAME;
         option->len = min(chunk.len, 64);
         memcpy(option->data, chunk.ptr, option->len);
         optlen += sizeof(dhcp_option_t) + option->len;
     }
     option = (dhcp_option_t*)&dhcp->options[optlen];
     option->type = DHCP_CLIENT_ID;
     option->len = min(chunk.len, 64);
     memcpy(option->data, chunk.ptr, option->len);
     optlen += sizeof(dhcp_option_t) + option->len;
     return optlen;
 }
static bool receive_dhcp (private_dhcp_socket_t * this, int fd, watcher_event_t event) static
Receive DHCP responses
Definition at line 565 of file dhcp_socket.c.
References __attribute__(), addr, DHCP_ACK, DHCP_MESSAGE_TYPE, DHCP_OFFER, DHCP_OPTEND, dhcp_option_t, dhcp_t, handle_ack(), handle_offer(), len, MSG_DONTWAIT, format-options::options, recvfrom, and TRUE.
Referenced by dhcp_socket_create().
 {
     struct sockaddr_ll addr;
     socklen_t addr_len = sizeof(addr);
     struct __attribute__((packed)) {
         struct iphdr ip;
         struct udphdr udp;
         dhcp_t dhcp;
     } packet;
     int optlen, origoptlen, optsize, optpos = 0;
     ssize_t len;
     dhcp_option_t *option;
     len = recvfrom(fd, &packet, sizeof(packet), MSG_DONTWAIT,
                     (struct sockaddr*)&addr, &addr_len);
     if (len >= sizeof(struct iphdr) + sizeof(struct udphdr) +
         offsetof(dhcp_t, options))
     {
         origoptlen = optlen = len - sizeof(struct iphdr) +
                      sizeof(struct udphdr) + offsetof(dhcp_t, options);
         while (optlen > sizeof(dhcp_option_t))
         {
             option = (dhcp_option_t*)&packet.dhcp.options[optpos];
             optsize = sizeof(dhcp_option_t) + option->len;
             if (option->type == DHCP_OPTEND || optlen < optsize)
             {
                 break;
             }
             if (option->type == DHCP_MESSAGE_TYPE && option->len == 1)
             {
                 switch (option->data[0])
                 {
                     case DHCP_OFFER:
                         handle_offer(this, &packet.dhcp, origoptlen);
                         break;
                     case DHCP_ACK:
                         handle_ack(this, &packet.dhcp, origoptlen);
                     default:
                         break;
                 }
                 break;
             }
             optlen -= optsize;
             optpos += optsize;
         }
     }
     return TRUE;
 }
static bool request (private_dhcp_socket_t * this, dhcp_transaction_t * transaction) static
Send DHCP request using a given transaction
Definition at line 317 of file dhcp_socket.c.
References DBG1, DBG_CFG, DHCP_DNS_SERVER, DHCP_NBNS_SERVER, DHCP_OPTEND, dhcp_option_t, DHCP_PARAM_REQ_LIST, DHCP_REQUEST, DHCP_REQUESTED_IP, DHCP_SERVER_ID, dhcp_t, FALSE, dhcp_transaction_t::get_address, host_t::get_address, dhcp_transaction_t::get_server, if(), chunk_t::len, memcpy, min, prepare_dhcp(), chunk_t::ptr, send_dhcp(), server, strerror, and TRUE.
Referenced by handle_ack(), handle_offer(), and METHOD().
 {
     dhcp_option_t *option;
     dhcp_t dhcp;
     host_t *offer, *server;
     chunk_t chunk;
     int optlen;
     optlen = prepare_dhcp(this, transaction, DHCP_REQUEST, &dhcp);
     offer = transaction->get_address(transaction);
     server = transaction->get_server(transaction);
     if (!offer || !server)
     {
         return FALSE;
     }
     DBG1(DBG_CFG, "sending DHCP REQUEST for %H to %H", offer, server);
     option = (dhcp_option_t*)&dhcp.options[optlen];
     option->type = DHCP_REQUESTED_IP;
     option->len = 4;
     chunk = offer->get_address(offer);
     memcpy(option->data, chunk.ptr, min(chunk.len, option->len));
     optlen += sizeof(dhcp_option_t) + option->len;
     option = (dhcp_option_t*)&dhcp.options[optlen];
     option->type = DHCP_SERVER_ID;
     option->len = 4;
     chunk = server->get_address(server);
     memcpy(option->data, chunk.ptr, min(chunk.len, option->len));
     optlen += sizeof(dhcp_option_t) + option->len;
     option = (dhcp_option_t*)&dhcp.options[optlen];
     option->type = DHCP_PARAM_REQ_LIST;
     option->len = 2;
     option->data[0] = DHCP_DNS_SERVER;
     option->data[1] = DHCP_NBNS_SERVER;
     optlen += sizeof(dhcp_option_t) + option->len;
     dhcp.options[optlen++] = DHCP_OPTEND;
     if (!send_dhcp(this, transaction, &dhcp, optlen))
     {
         DBG1(DBG_CFG, "sending DHCP REQUEST failed: %s", strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
static bool send_dhcp (private_dhcp_socket_t * this, dhcp_transaction_t * transaction, dhcp_t * dhcp, int optlen) static
Send a DHCP message with given options length
Definition at line 267 of file dhcp_socket.c.
References dhcp_t, dst, dhcp_transaction_t::get_server, host_t::get_sockaddr, host_t::get_sockaddr_len, len, send, and sendto.
Referenced by discover(), METHOD(), and request().
 {
     host_t *dst;
     ssize_t len;
     dst = transaction->get_server(transaction);
     if (!dst || this->force_dst)
     {
         dst = this->dst;
     }
     len = offsetof(dhcp_t, magic_cookie) + ((optlen + 4) / 64 * 64 + 64);
     return sendto(this->send, dhcp, len, 0, dst->get_sockaddr(dst),
                   *dst->get_sockaddr_len(dst)) == len;
 }
Variable Documentation
dhcp_option_t
Definition at line 158 of file dhcp_socket.c.
Referenced by discover(), handle_offer(), METHOD(), prepare_dhcp(), receive_dhcp(), and request().
dhcp_t
Definition at line 181 of file dhcp_socket.c.
Referenced by dhcp_socket_create(), discover(), METHOD(), receive_dhcp(), request(), and send_dhcp().