strongSwan: pkcs12.c File Reference
libstrongswan/credentials/containers/pkcs12.c File Reference
#include "pkcs12.h"
#include <utils/debug.h>
Macros
#define PKCS12_LEN(len, v) (((len) + v-1) & ~(v-1))
Functions
static void copy_chunk (chunk_t dst, chunk_t src)
static void add_chunks (chunk_t a, chunk_t b)
static bool derive_key (hash_algorithm_t hash, chunk_t unicode, chunk_t salt, u_int64_t iterations, char id, chunk_t result)
bool pkcs12_derive_key (hash_algorithm_t hash, chunk_t password, chunk_t salt, u_int64_t iterations, pkcs12_key_type_t type, chunk_t key)
Macro Definition Documentation
#define PKCS12_LEN (len, v) (((len) + v-1) & ~(v-1))
v * ceiling(len/v)
Definition at line 23 of file libstrongswan/credentials/containers/pkcs12.c.
Referenced by derive_key().
Function Documentation
static void add_chunks (chunk_t a, chunk_t b) static
Treat two chunks as integers in network order and add them together. The result is stored in the first chunk, if the second chunk is longer or the result overflows this is ignored.
Definition at line 43 of file libstrongswan/credentials/containers/pkcs12.c.
References chunk_t::len, and chunk_t::ptr.
Referenced by derive_key().
 {
     u_int16_t sum;
     u_int8_t rem = 0;
     ssize_t i, j;
     for (i = a.len - 1, j = b.len -1; i >= 0 && j >= 0; i--, j--)
     {
         sum = a.ptr[i] + b.ptr[j] + rem;
         a.ptr[i] = (u_char)sum;
         rem = sum >> 8;
     }
     for (; i >= 0 && rem; i--)
     {
         sum = a.ptr[i] + rem;
         a.ptr[i] = (u_char)sum;
         rem = sum >> 8;
     }
 }
static void copy_chunk (chunk_t dst, chunk_t src) inline static
Copy src to dst as many times as possible
Definition at line 28 of file libstrongswan/credentials/containers/pkcs12.c.
References chunk_t::len, and chunk_t::ptr.
Referenced by derive_key().
 {
     size_t i;
     for (i = 0; i < dst.len; i++)
     {
         dst.ptr[i] = src.ptr[i % src.len];
     }
 }
static bool derive_key (hash_algorithm_t hash, chunk_t unicode, chunk_t salt, u_int64_t iterations, char id, chunk_t result) static
Do the actual key derivation with the given hasher, password and id.
Definition at line 66 of file libstrongswan/credentials/containers/pkcs12.c.
References add_chunks(), chunk_alloca, chunk_create(), chunk_empty, chunk_from_chars, chunk_skip(), copy_chunk(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_ASN, hasher_t::destroy, end, FALSE, hasher_t::get_hash, hasher_t::get_hash_size, hash_algorithm_names, HASH_MD2, HASH_MD5, HASH_SHA1, HASH_SHA224, HASH_SHA256, HASH_SHA384, HASH_SHA512, hasher, I, chunk_t::len, lib, memcpy, memset, min, out, PKCS12_LEN, chunk_t::ptr, result, S, and TRUE.
Referenced by pkcs12_derive_key().
 {
     chunk_t out = result, D, S, P = chunk_empty, I, Ai, B, Ij;
     hasher_t *hasher;
     size_t Slen, v, u;
     u_int64_t i;
     bool success = FALSE;
     hasher = lib->crypto->create_hasher(lib->crypto, hash);
     if (!hasher)
     {
         DBG1(DBG_ASN, "  %N hash algorithm not available",
              hash_algorithm_names, hash);
         return  FALSE;
     }
     switch (hash)
     {
         case HASH_MD2:
         case HASH_MD5:
         case HASH_SHA1:
         case HASH_SHA224:
         case HASH_SHA256:
             v = 64;
             break;
         case HASH_SHA384:
         case HASH_SHA512:
             v = 128;
             break;
         default:
             goto end;
     }
     u = hasher->get_hash_size(hasher);
     D = chunk_alloca(v);
     memset(D.ptr, id, D.len);
     Slen = PKCS12_LEN(salt.len, v);
     I = chunk_alloca(Slen + PKCS12_LEN(unicode.len, v));
     S = chunk_create(I.ptr, Slen);
     P = chunk_create(I.ptr + Slen, I.len - Slen);
     copy_chunk(S, salt);
     copy_chunk(P, unicode);
     Ai = chunk_alloca(u);
     B = chunk_alloca(v);
     while (TRUE)
     {
         if (!hasher->get_hash(hasher, D, NULL) ||
             !hasher->get_hash(hasher, I, Ai.ptr))
         {
             goto end;
         }
         for (i = 1; i < iterations; i++)
         {
             if (!hasher->get_hash(hasher, Ai, Ai.ptr))
             {
                 goto end;
             }
         }
         memcpy(out.ptr, Ai.ptr, min(out.len, Ai.len));
         out = chunk_skip(out, Ai.len);
         if (!out.len)
         {
             break;
         }
         copy_chunk(B, Ai);
         /* B = B+1 */
         add_chunks(B, chunk_from_chars(0x01));
         Ij = chunk_create(I.ptr, v);
         for (i = 0; i < I.len; i += v, Ij.ptr += v)
         {   /* Ij = Ij + B + 1 */
             add_chunks(Ij, B);
         }
     }
     success = TRUE;
 end:
     hasher->destroy(hasher);
     return success;
 }