strongSwan: vici_socket
vici_socket
vici
Classes
struct vici_socket_t
Macros
#define VICI_MESSAGE_SIZE_MAX (512 * 1024)
Typedefs
typedef struct vici_socket_t vici_socket_t
typedef void(* vici_inbound_cb_t)(void *user, u_int id, chunk_t data)
typedef void(* vici_connect_cb_t)(void *user, u_int id)
typedef void(* vici_disconnect_cb_t)(void *user, u_int id)
Functions
vici_socket_t * vici_socket_create (char *uri, vici_inbound_cb_t inbound, vici_connect_cb_t connect, vici_disconnect_cb_t disconnect, void *user)
Detailed Description
Macro Definition Documentation
#define VICI_MESSAGE_SIZE_MAX (512 * 1024)
Maximum size of a single message exchanged.
Definition at line 29 of file vici_socket.h.
Referenced by CALLBACK(), do_read(), and METHOD().
Typedef Documentation
typedef void(* vici_connect_cb_t)(void *user, u_int id)
Callback function invoked when new clients connect
Parameters
user user data, as passed during registration
id unique client connection identifier
Returns
client connection context
Definition at line 49 of file vici_socket.h.
typedef void(* vici_disconnect_cb_t)(void *user, u_int id)
Callback function invoked when connected clients disconnect
Parameters
user user data, as passed during registration
id unique client connection identifier
Definition at line 57 of file vici_socket.h.
typedef void(* vici_inbound_cb_t)(void *user, u_int id, chunk_t data)
Callback function for dispatching inbound client messages.
Parameters
user user data, as passed during registration
id unique client connection identifier
data incoming message data
Definition at line 40 of file vici_socket.h.
typedef struct vici_socket_t vici_socket_t
Definition at line 31 of file vici_socket.h.
Function Documentation
vici_socket_t* vici_socket_create (char * uri, vici_inbound_cb_t inbound, vici_connect_cb_t connect, vici_disconnect_cb_t disconnect, void * user)
Create a vici_socket instance.
Parameters
uri socket URI to listen on
inbound inbound message callback
connect connect callback
disconnect disconnect callback
user user data to pass to callbacks
Definition at line 671 of file vici_socket.c.
References connect, stream_manager_t::create_service, DBG1, DBG_CFG, destroy(), disconnect(), INIT, JOB_PRIO_CRITICAL, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, on_accept(), and library_t::streams.
Referenced by START_TEST(), and vici_dispatcher_create().
 {
     private_vici_socket_t *this;
     INIT(this,
         .public = {
             .send = _send_,
             .destroy = _destroy,
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .connections = linked_list_create(),
         .inbound = inbound,
         .connect = connect,
         .disconnect = disconnect,
         .user = user,
     );
     this->service = lib->streams->create_service(lib->streams, uri, 3);
     if (!this->service)
     {
         DBG1(DBG_CFG, "creating vici socket failed");
         destroy(this);
         return NULL;
     }
     this->service->on_accept(this->service, on_accept, this,
                              JOB_PRIO_CRITICAL, 0);
     return &this->public;
 }