strongSwan: bliss_bitpacker_t Struct Reference
bliss_bitpacker_t Struct Reference
bliss_bitpacker
#include "bliss_bitpacker.h"
Public Attributes
size_t(* get_bits)(bliss_bitpacker_t *this)
bool(* write_bits)(bliss_bitpacker_t *this, uint32_t value, size_t bits)
bool(* read_bits)(bliss_bitpacker_t *this, uint32_t *value, size_t bits)
chunk_t(* extract_buf)(bliss_bitpacker_t *this)
void(* destroy)(bliss_bitpacker_t *this)
Detailed Description
Reads and writes a variable number of bits in packed format from and to an octet buffer
Definition at line 32 of file bliss_bitpacker.h.
Member Data Documentation
void(* bliss_bitpacker_t::destroy)(bliss_bitpacker_t *this)
Destroy bliss_bitpacker_t object
Definition at line 68 of file bliss_bitpacker.h.
Referenced by bliss_private_key_load(), bliss_public_key_encode(), bliss_public_key_from_asn1(), METHOD(), and START_TEST().
chunk_t(* bliss_bitpacker_t::extract_buf)(bliss_bitpacker_t *this)
Detach the internal octet buffer and return it
Definition at line 63 of file bliss_bitpacker.h.
Referenced by bliss_public_key_encode(), METHOD(), and START_TEST().
size_t(* bliss_bitpacker_t::get_bits)(bliss_bitpacker_t *this)
Get the number of bits written into buffer
Returns
Number of bits written
Definition at line 39 of file bliss_bitpacker.h.
Referenced by METHOD(), and START_TEST().
bool(* bliss_bitpacker_t::read_bits)(bliss_bitpacker_t *this, uint32_t *value, size_t bits)
Get the prime modulus of the Number Theoretic Transform
Parameters
value Value returned
bits Number of bits to be read
Returns
TRUE if value could be read from buffer
Definition at line 58 of file bliss_bitpacker.h.
Referenced by bliss_private_key_load(), bliss_public_key_from_asn1(), and START_TEST().
bool(* bliss_bitpacker_t::write_bits)(bliss_bitpacker_t *this, uint32_t value, size_t bits)
Get the prime modulus of the Number Theoretic Transform
Parameters
value Value to be written
bits Number of bits to be written
Returns
TRUE if value could be written into buffer
Definition at line 48 of file bliss_bitpacker.h.
Referenced by bliss_public_key_encode(), METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
bliss_bitpacker.h