strongSwan: libpttls
libpttls
Modules
pt_tls_client
pt_tls_dispatcher
pt_tls_server
sasl
Macros
#define PT_TLS_VERSION 1
#define PT_TLS_HEADER_LEN 16
#define PT_TLS_MAX_MESSAGE_LEN 128 * TLS_MAX_FRAGMENT_LEN - PT_TLS_HEADER_LEN
#define PT_TLS_PORT 271
Typedefs
typedef enum pt_tls_message_type_t pt_tls_message_type_t
typedef enum pt_tls_sasl_result_t pt_tls_sasl_result_t
typedef enum pt_tls_auth_t pt_tls_auth_t
Enumerations
enum pt_tls_message_type_t {
PT_TLS_EXPERIMENTAL = 0, PT_TLS_VERSION_REQUEST = 1, PT_TLS_VERSION_RESPONSE = 2, PT_TLS_SASL_MECHS = 3,
PT_TLS_SASL_MECH_SELECTION = 4, PT_TLS_SASL_AUTH_DATA = 5, PT_TLS_SASL_RESULT = 6, PT_TLS_PB_TNC_BATCH = 7,
PT_TLS_ERROR = 8
}
enum pt_tls_sasl_result_t { PT_TLS_SASL_RESULT_SUCCESS = 0, PT_TLS_SASL_RESULT_FAILURE = 1, PT_TLS_SASL_RESULT_ABORT = 2, PT_TLS_SASL_RESULT_MECH_FAILURE = 3 }
enum pt_tls_auth_t {
PT_TLS_AUTH_NONE, PT_TLS_AUTH_TLS, PT_TLS_AUTH_SASL, PT_TLS_AUTH_TLS_OR_SASL,
PT_TLS_AUTH_TLS_AND_SASL
}
Functions
bio_reader_t * pt_tls_read (tls_socket_t *tls, u_int32_t *vendor, u_int32_t *type, u_int32_t *identifier)
bool pt_tls_write (tls_socket_t *tls, pt_tls_message_type_t type, u_int32_t identifier, chunk_t data)
void libpttls_init (void)
Variables
enum_name_t * pt_tls_message_type_names
enum_name_t * pt_tls_sasl_result_names
Detailed Description
Macro Definition Documentation
#define PT_TLS_HEADER_LEN 16
Length of a PT-TLS header
Definition at line 38 of file pt_tls.h.
Referenced by pt_tls_read(), and pt_tls_write().
#define PT_TLS_MAX_MESSAGE_LEN 128 * TLS_MAX_FRAGMENT_LEN - PT_TLS_HEADER_LEN
Maximum size of a PT-TLS message
Definition at line 43 of file pt_tls.h.
Referenced by assess().
#define PT_TLS_PORT 271
Default PT-TLS port
Definition at line 48 of file pt_tls.h.
Referenced by main(), and tnc_pdp_create().
#define PT_TLS_VERSION 1
PT-TLS version we support
Definition at line 33 of file pt_tls.h.
Referenced by METHOD(), and negotiate_version().
Typedef Documentation
typedef enum pt_tls_auth_t pt_tls_auth_t
Definition at line 52 of file pt_tls.h.
typedef enum pt_tls_message_type_t pt_tls_message_type_t
Definition at line 50 of file pt_tls.h.
typedef enum pt_tls_sasl_result_t pt_tls_sasl_result_t
Definition at line 51 of file pt_tls.h.
Enumeration Type Documentation
enum pt_tls_auth_t
Client authentication to require as PT-TLS server.
Enumerator
PT_TLS_AUTH_NONE
don't require TLS client certificate or request SASL authentication
PT_TLS_AUTH_TLS
require TLS certificate authentication, no SASL
PT_TLS_AUTH_SASL
do SASL regardless of TLS certificate authentication
PT_TLS_AUTH_TLS_OR_SASL
PT_TLS_AUTH_TLS_AND_SASL
Definition at line 86 of file pt_tls.h.
                    {
     PT_TLS_AUTH_NONE,
     PT_TLS_AUTH_TLS,
     PT_TLS_AUTH_SASL,
     /* if client does not authenticate with a TLS certificate, request SASL */
     PT_TLS_AUTH_TLS_OR_SASL,
     /* require both, TLS certificate authentication and SASL */
     PT_TLS_AUTH_TLS_AND_SASL,
 };
enum pt_tls_message_type_t
Message types, as defined by NEA PT-TLS
Enumerator
PT_TLS_EXPERIMENTAL
PT_TLS_VERSION_REQUEST
PT_TLS_VERSION_RESPONSE
PT_TLS_SASL_MECHS
PT_TLS_SASL_MECH_SELECTION
PT_TLS_SASL_AUTH_DATA
PT_TLS_SASL_RESULT
PT_TLS_PB_TNC_BATCH
PT_TLS_ERROR
Definition at line 57 of file pt_tls.h.
{
     PT_TLS_EXPERIMENTAL = 0,
     PT_TLS_VERSION_REQUEST = 1,
     PT_TLS_VERSION_RESPONSE = 2,
     PT_TLS_SASL_MECHS = 3,
     PT_TLS_SASL_MECH_SELECTION = 4,
     PT_TLS_SASL_AUTH_DATA = 5,
     PT_TLS_SASL_RESULT = 6,
     PT_TLS_PB_TNC_BATCH = 7,
     PT_TLS_ERROR = 8,
 };
enum pt_tls_sasl_result_t
Result code for a single SASL mechansim, as sent in PT_TLS_SASL_RESULT
Enumerator
PT_TLS_SASL_RESULT_SUCCESS
PT_TLS_SASL_RESULT_FAILURE
PT_TLS_SASL_RESULT_ABORT
PT_TLS_SASL_RESULT_MECH_FAILURE
Definition at line 74 of file pt_tls.h.
{
     PT_TLS_SASL_RESULT_SUCCESS = 0,
     PT_TLS_SASL_RESULT_FAILURE = 1,
     PT_TLS_SASL_RESULT_ABORT = 2,
     PT_TLS_SASL_RESULT_MECH_FAILURE = 3,
 };
Function Documentation
void libpttls_init (void)
Dummy libpttls initialization function needed for integrity test
Described in header.
Definition at line 23 of file pt_tls.c.
 {
     /* empty */
 }
bio_reader_t* pt_tls_read (tls_socket_t * tls, u_int32_t * vendor, u_int32_t * type, u_int32_t * identifier)
Read a PT-TLS message, create reader over Message Value.
Parameters
tls TLS socket to read from
vendor receives Message Type Vendor ID from header
type receives Message Type from header
identifier receives Message Identifer
Returns
reader over message value, NULL on error
Read a PT-TLS message, return header data
Definition at line 90 of file pt_tls.c.
References DBG1, DBG2, DBG_TNC, bio_reader_t::destroy, len, PEN_IETF, PT_TLS_HEADER_LEN, pt_tls_message_type_names, read_tls(), bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, and reserved.
Referenced by assess(), do_sasl(), negotiate_version(), read_sasl(), read_sasl_mech_selection(), and select_and_do_sasl().
 {
     bio_reader_t *reader;
     u_int32_t len;
     u_int8_t reserved;
     reader = read_tls(tls, PT_TLS_HEADER_LEN);
     if (!reader)
     {
         return NULL;
     }
     if (!reader->read_uint8(reader, &reserved) ||
         !reader->read_uint24(reader, vendor) ||
         !reader->read_uint32(reader, type) ||
         !reader->read_uint32(reader, &len) ||
         !reader->read_uint32(reader, identifier))
     {
         reader->destroy(reader);
         return NULL;
     }
     reader->destroy(reader);
     if (len < PT_TLS_HEADER_LEN)
     {
         DBG1(DBG_TNC, "received short PT-TLS header (%d bytes)", len);
         return NULL;
     }
     if (*vendor == PEN_IETF)
     {
         DBG2(DBG_TNC, "received PT-TLS message #%d of type '%N' (%d bytes)",
                       *identifier, pt_tls_message_type_names, *type, len);
     }
     else
     {
         DBG2(DBG_TNC, "received PT-TLS message #%d of unknown type "
                       "0x%06x/0x%08x (%d bytes)",
                       *identifier, *vendor, *type, len);
     }
     return read_tls(tls, len - PT_TLS_HEADER_LEN);
 }
bool pt_tls_write (tls_socket_t * tls, pt_tls_message_type_t type, u_int32_t identifier, chunk_t data)
Prepend a PT-TLS header to a writer, send data, destroy writer.
Parameters
tls TLS socket to write to
type Message Type to write
identifier Message Identifier to write
data Message value to write
Returns
TRUE if data written successfully
Prepend a PT-TLS header to a writer, send data, destroy writer
Definition at line 137 of file pt_tls.c.
References bio_writer_create(), DBG2, DBG_TNC, bio_writer_t::destroy, bio_writer_t::get_buf, chunk_t::len, len, out, PT_TLS_HEADER_LEN, pt_tls_message_type_names, chunk_t::ptr, tls_socket_t::write, bio_writer_t::write_data, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
Referenced by assess(), authenticate(), do_sasl(), negotiate_version(), process_sasl(), send_sasl_mechs(), and write_sasl().
 {
     bio_writer_t *writer;
     chunk_t out;
     ssize_t len;
     len = PT_TLS_HEADER_LEN + data.len;
     writer = bio_writer_create(len);
     /* write PT-TLS header */
     writer->write_uint8 (writer, 0);
     writer->write_uint24(writer, 0);
     writer->write_uint32(writer, type);
     writer->write_uint32(writer, len);
     writer->write_uint32(writer, identifier);
     /* write PT-TLS body */
     writer->write_data(writer, data);
     DBG2(DBG_TNC, "sending PT-TLS message #%d of type '%N' (%d bytes)",
                    identifier, pt_tls_message_type_names, type, len);
     out = writer->get_buf(writer);
     len = tls->write(tls, out.ptr, out.len);
     writer->destroy(writer);
     return len == out.len;
 }
Variable Documentation
enum_name_t* pt_tls_message_type_names
Referenced by pt_tls_read(), and pt_tls_write().
enum_name_t* pt_tls_sasl_result_names
Referenced by do_sasl().