strongSwan: xauth_noauth_plugin.c File Reference
xauth_noauth_plugin.c File Reference
#include "xauth_noauth_plugin.h"
#include "xauth_noauth.h"
#include <daemon.h>
Functions
METHOD (plugin_t, get_name, char *, xauth_noauth_plugin_t *this)
METHOD (plugin_t, get_features, int, xauth_noauth_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, xauth_noauth_plugin_t *this)
plugin_t * xauth_noauth_plugin_create ()
Function Documentation
METHOD (plugin_t , get_name , char * , xauth_noauth_plugin_t * this)
Definition at line 21 of file xauth_noauth_plugin.c.
 {
     return "xauth-noauth";
 }
METHOD (plugin_t , get_features , int , xauth_noauth_plugin_t * this, plugin_feature_t * features[])
Definition at line 27 of file xauth_noauth_plugin.c.
References countof, PLUGIN_CALLBACK, PLUGIN_PROVIDE, xauth_method_register(), xauth_noauth_create_server(), and XAUTH_SERVER.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(xauth_method_register, xauth_noauth_create_server),
             PLUGIN_PROVIDE(XAUTH_SERVER, "noauth"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , xauth_noauth_plugin_t * this)
Definition at line 38 of file xauth_noauth_plugin.c.
References free().
 {
     free(this);
 }
plugin_t* xauth_noauth_plugin_create ()
Definition at line 47 of file xauth_noauth_plugin.c.
References INIT, and plugin.
 {
     xauth_noauth_plugin_t *this;
     INIT(this,
         .plugin = {
             .get_name = _get_name,
             .get_features = _get_features,
             .destroy = _destroy,
         },
     );
     return &this->plugin;
 }