strongSwan: charon-cmd.c File Reference
charon-cmd.c File Reference
#include <stdio.h>
#include <signal.h>
#include <pthread.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <unistd.h>
#include <getopt.h>
#include <errno.h>
#include <library.h>
#include <hydra.h>
#include <daemon.h>
#include <utils/backtrace.h>
#include <threading/thread.h>
#include "cmd/cmd_options.h"
#include "cmd/cmd_connection.h"
#include "cmd/cmd_creds.h"
Functions
static void dbg_stderr (debug_t group, level_t level, char *fmt,...)
static void cleanup_conn ()
static void cleanup_creds ()
static int run ()
static bool lookup_uid_gid ()
static void segv_handler (int signal)
static void usage (FILE *out, char *msg, char *binary)
static void handle_arguments (int argc, char *argv[], bool simple)
int main (int argc, char *argv[])
Variables
static level_t default_loglevel = LEVEL_CTRL
static level_t levels [DBG_MAX]
static cmd_connection_t * conn
static cmd_creds_t * creds
void(* dbg)(debug_t group, level_t level, char *fmt,...)
Function Documentation
static void cleanup_conn () static
Clean up connection definition atexit()
Definition at line 83 of file charon-cmd.c.
References DESTROY_IF.
Referenced by main().
 {
     DESTROY_IF(conn);
 }
static void cleanup_creds () static
Clean up credentials atexit()
Definition at line 91 of file charon-cmd.c.
References DESTROY_IF.
Referenced by main().
 {
     DESTROY_IF(creds);
 }
static void dbg_stderr (debug_t group, level_t level, char * fmt, ...) static
Logging hook for library logs, using stderr output
Definition at line 66 of file charon-cmd.c.
References debug_names, default_loglevel, fprintf, and vfprintf.
Referenced by main().
 {
     va_list args;
     if (level <= default_loglevel)
     {
         va_start(args, fmt);
         fprintf(stderr, "00[%N] ", debug_names, group);
         vfprintf(stderr, fmt, args);
         fprintf(stderr, "\n");
         va_end(args);
     }
 }
static void handle_arguments (int argc, char * argv[], bool simple) static
Handle command line options, if simple is TRUE only arguments like –help and –version are handled.
Definition at line 256 of file charon-cmd.c.
References CMD_OPT_COUNT, CMD_OPT_DEBUG, CMD_OPT_HELP, CMD_OPT_VERSION, cmd_options, default_loglevel, FALSE, cmd_creds_t::handle, cmd_connection_t::handle, cmd_option_t::has_arg, cmd_option_t::id, cmd_option_t::name, printf, TRUE, and usage().
Referenced by main().
 {
     struct option long_opts[CMD_OPT_COUNT + 1] = {};
     int i, opt;
     for (i = 0; i < CMD_OPT_COUNT; i++)
     {
         long_opts[i].name = cmd_options[i].name;
         long_opts[i].val = cmd_options[i].id;
         long_opts[i].has_arg = cmd_options[i].has_arg;
     }
     /* reset option parser */
     optind = 1;
     while (TRUE)
     {
         bool handled = FALSE;
         opt = getopt_long(argc, argv, "", long_opts, NULL);
         switch (opt)
         {
             case EOF:
                 break;
             case CMD_OPT_HELP:
                 usage(stdout, NULL, argv[0]);
                 exit(0);
             case CMD_OPT_VERSION:
                 printf("%s, strongSwan %s\n", "charon-cmd", VERSION);
                 exit(0);
             case CMD_OPT_DEBUG:
                 default_loglevel = atoi(optarg);
                 continue;
             default:
                 if (simple)
                 {
                     continue;
                 }
                 handled |= conn->handle(conn, opt, optarg);
                 handled |= creds->handle(creds, opt, optarg);
                 if (handled)
                 {
                     continue;
                 }
                 /* fall-through */
             case '?':
                 /* missing argument, unrecognized option */
                 usage(stderr, NULL, argv[0]);
                 exit(1);
         }
         break;
     }
 }
static bool lookup_uid_gid () static
lookup UID and GID
Definition at line 166 of file charon-cmd.c.
References library_t::caps, FALSE, IPSEC_GROUP, IPSEC_USER, lib, capabilities_t::resolve_gid, capabilities_t::resolve_uid, and TRUE.
Referenced by main().
 {
 #ifdef IPSEC_USER
     if (!lib->caps->resolve_uid(lib->caps, IPSEC_USER))
     {
         return FALSE;
     }
 #endif
 #ifdef IPSEC_GROUP
     if (!lib->caps->resolve_gid(lib->caps, IPSEC_GROUP))
     {
         return FALSE;
     }
 #endif
     return TRUE;
 }
int main (int argc, char * argv[])
Main function, starts the daemon.
Definition at line 311 of file charon-cmd.c.
References library_t::caps, charon, integrity_checker_t::check_file, cleanup_conn(), cleanup_creds(), cmd_connection_create(), cmd_creds_create(), dbg, DBG1, DBG_DMN, DBG_MAX, dbg_stderr(), default_loglevel, capabilities_t::drop, FALSE, settings_t::get_str, group, handle_arguments(), daemon_t::initialize, library_t::integrity, LEVEL_CTRL, levels, lib, libcharon_deinit(), libcharon_init(), libhydra_deinit(), libhydra_init(), library_deinit(), library_init(), daemon_t::load_loggers, lookup_uid_gid(), memset, PLUGINS, library_t::plugins, run(), segv_handler(), settings_t::set_default_str, library_t::settings, SS_RC_DAEMON_INTEGRITY, SS_RC_INITIALIZATION_FAILED, SS_RC_LIBSTRONGSWAN_INTEGRITY, daemon_t::start, plugin_loader_t::status, and TRUE.
 {
     struct sigaction action;
     struct utsname utsname;
     int group;
     /* handle simple arguments */
     handle_arguments(argc, argv, TRUE);
     dbg = dbg_stderr;
     atexit(library_deinit);
     if (!library_init(NULL, "charon-cmd"))
     {
         exit(SS_RC_LIBSTRONGSWAN_INTEGRITY);
     }
     if (lib->integrity)
     {
         if (!lib->integrity->check_file(lib->integrity, "charon-cmd", argv[0]))
         {
             exit(SS_RC_DAEMON_INTEGRITY);
         }
     }
     atexit(libhydra_deinit);
     if (!libhydra_init())
     {
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     atexit(libcharon_deinit);
     if (!libcharon_init())
     {
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     for (group = 0; group < DBG_MAX; group++)
     {
         levels[group] = default_loglevel;
     }
     charon->load_loggers(charon, levels, TRUE);
     if (!lookup_uid_gid())
     {
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     lib->settings->set_default_str(lib->settings, "charon-cmd.port", "0");
     lib->settings->set_default_str(lib->settings, "charon-cmd.port_nat_t", "0");
     if (!charon->initialize(charon,
             lib->settings->get_str(lib->settings, "charon-cmd.load", PLUGINS)))
     {
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     if (!lib->caps->drop(lib->caps))
     {
         exit(SS_RC_INITIALIZATION_FAILED);
     }
     conn = cmd_connection_create();
     atexit(cleanup_conn);
     creds = cmd_creds_create();
     atexit(cleanup_creds);
     /* handle all arguments */
     handle_arguments(argc, argv, FALSE);
     if (uname(&utsname) != 0)
     {
         memset(&utsname, 0, sizeof(utsname));
     }
     DBG1(DBG_DMN, "Starting charon-cmd IKE client (strongSwan %s, %s %s, %s)",
          VERSION, utsname.sysname, utsname.release, utsname.machine);
     lib->plugins->status(lib->plugins, LEVEL_CTRL);
     /* add handler for SEGV and ILL,
      * INT, TERM and HUP are handled by sigwaitinfo() in run() */
     action.sa_handler = segv_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaddset(&action.sa_mask, SIGINT);
     sigaddset(&action.sa_mask, SIGTERM);
     sigaddset(&action.sa_mask, SIGHUP);
     sigaddset(&action.sa_mask, SIGUSR1);
     sigaction(SIGSEGV, &action, NULL);
     sigaction(SIGILL, &action, NULL);
     sigaction(SIGBUS, &action, NULL);
     action.sa_handler = SIG_IGN;
     sigaction(SIGPIPE, &action, NULL);
     pthread_sigmask(SIG_SETMASK, &action.sa_mask, NULL);
     /* start daemon with thread-pool */
     charon->start(charon);
     /* wait for signal */
     return run();
 }
static int run () static
Run the daemon and handle unix signals
Definition at line 99 of file charon-cmd.c.
References bus_t::alert, ALERT_SHUTDOWN_SIGNAL, daemon_t::bus, charon, library_t::conf, DBG1, DBG_DMN, FALSE, levels, lib, settings_t::load_files, daemon_t::load_loggers, library_t::plugins, plugin_loader_t::reload, library_t::settings, sig, sigwaitinfo(), strerror, and TRUE.
Referenced by main().
 {
     sigset_t set;
     /* handle SIGINT, SIGHUP and SIGTERM in this handler */
     sigemptyset(&set);
     sigaddset(&set, SIGINT);
     sigaddset(&set, SIGHUP);
     sigaddset(&set, SIGTERM);
     sigaddset(&set, SIGUSR1);
     sigprocmask(SIG_BLOCK, &set, NULL);
     while (TRUE)
     {
         int sig;
         sig = sigwaitinfo(&set, NULL);
         if (sig == -1)
         {
             if (errno == EINTR)
             {   /* ignore signals we didn't wait for */
                 continue;
             }
             DBG1(DBG_DMN, "waiting for signal failed: %s", strerror(errno));
             return 1;
         }
         switch (sig)
         {
             case SIGHUP:
             {
                 DBG1(DBG_DMN, "signal of type SIGHUP received. Reloading "
                      "configuration");
                 if (lib->settings->load_files(lib->settings, lib->conf, FALSE))
                 {
                     charon->load_loggers(charon, levels, TRUE);
                     lib->plugins->reload(lib->plugins, NULL);
                 }
                 else
                 {
                     DBG1(DBG_DMN, "reloading config failed, keeping old");
                 }
                 break;
             }
             case SIGINT:
             {
                 DBG1(DBG_DMN, "signal of type SIGINT received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return 0;
             }
             case SIGTERM:
             {
                 DBG1(DBG_DMN, "signal of type SIGTERM received. Shutting down");
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return 0;
             }
             case SIGUSR1:
             {   /* an error occurred */
                 charon->bus->alert(charon->bus, ALERT_SHUTDOWN_SIGNAL, sig);
                 return 1;
             }
         }
     }
 }
static void segv_handler (int signal) static
Handle SIGSEGV/SIGILL signals raised by threads
Definition at line 186 of file charon-cmd.c.
References backtrace, backtrace_create(), DBG1, DBG_DMN, backtrace_t::destroy, backtrace_t::log, thread_current_id(), and TRUE.
Referenced by main().
 {
     backtrace_t *backtrace;
     DBG1(DBG_DMN, "thread %u received %d", thread_current_id(), signal);
     backtrace = backtrace_create(2);
     backtrace->log(backtrace, stderr, TRUE);
     backtrace->destroy(backtrace);
     DBG1(DBG_DMN, "killing ourself, received critical signal");
     abort();
 }
static void usage (FILE * out, char * msg, char * binary) static
Print command line usage and exit
Definition at line 202 of file charon-cmd.c.
References cmd, CMD_OPT_COUNT, cmd_options, countof, desc, fprintf, name, and snprintf.
Referenced by handle_arguments().
 {
     static const int padto = 18;
     char cmd[64], *pre, *post;
     int i, line, pad;
     if (msg)
     {
         fprintf(out, "%s\n", msg);
     }
     fprintf(out, "Usage: %s\n", binary);
     for (i = 0; i < CMD_OPT_COUNT; i++)
     {
         switch (cmd_options[i].has_arg)
         {
             case required_argument:
                 pre = " <";
                 post = ">";
                 break;
             case optional_argument:
                 pre = "[=";
                 post = "]";
                 break;
             case no_argument:
             default:
                 pre = "  ";
                 post = " ";
                 break;
         }
         snprintf(cmd, sizeof(cmd), "  --%s%s%s%s", cmd_options[i].name,
                  pre, cmd_options[i].arg, post);
         pad = padto - strlen(cmd);
         if (pad >= 1)
         {
             fprintf(out, "%s%-*s%s\n", cmd, pad, "", cmd_options[i].desc);
         }
         else
         {   /* write description to a separate line */
             fprintf(out, "%s\n%-*s%s\n", cmd, padto, "", cmd_options[i].desc);
         }
         for (line = 0; line < countof(cmd_options[i].lines); line++)
         {
             if (cmd_options[i].lines[line])
             {
                 fprintf(out, "%-*s%s\n", padto, "", cmd_options[i].lines[line]);
             }
         }
     }
 }
Variable Documentation
cmd_connection_t* conn static
Connection to initiate
Definition at line 51 of file charon-cmd.c.
Referenced by call_command(), confread_free(), confread_load(), connect_(), main(), METHOD(), mysql_database_create(), mysql_enumerator_destroy(), START_TEST(), and vici_connect().
cmd_creds_t* creds static
Credential backend
Definition at line 56 of file charon-cmd.c.
void(* dbg)(debug_t group, level_t level, char *fmt,...)
hook in library for debugging messages
The registered debug hook.
Definition at line 111 of file debug.c.
Referenced by main().
level_t default_loglevel = LEVEL_CTRL static
Default loglevel
Definition at line 41 of file charon-cmd.c.
Referenced by dbg_stderr(), handle_arguments(), and main().
level_t levels[DBG_MAX] static
Loglevel configuration
Definition at line 46 of file charon-cmd.c.
Referenced by main(), and run().