strongSwan: ita_attr_command.c File Reference
ita_attr_command.c File Reference
#include <string.h>
#include "ita_attr.h"
#include "ita_attr_command.h"
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_ita_attr_command_t
Macros
#define _GNU_SOURCE /* for stdndup() */
Typedefs
typedef struct
private_ita_attr_command_t private_ita_attr_command_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ita_attr_command_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ita_attr_command_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ita_attr_command_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ita_attr_command_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ita_attr_command_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ita_attr_command_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ita_attr_command_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ita_attr_command_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ita_attr_command_t *this)
METHOD (ita_attr_command_t, get_command, char *, private_ita_attr_command_t *this)
pa_tnc_attr_t * ita_attr_command_create (char *command)
pa_tnc_attr_t * ita_attr_command_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 16 of file ita_attr_command.c.
Typedef Documentation
typedef struct private_ita_attr_command_t private_ita_attr_command_t
Definition at line 25 of file ita_attr_command.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ita_attr_command_t * this)
Definition at line 68 of file ita_attr_command.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ita_attr_command_t * this)
Definition at line 74 of file ita_attr_command.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ita_attr_command_t * this)
Definition at line 80 of file ita_attr_command.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ita_attr_command_t * this, bool noskip)
Definition at line 86 of file ita_attr_command.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ita_attr_command_t * this)
Definition at line 92 of file ita_attr_command.c.
References chunk_clone, chunk_from_str, command, length, and value.
 {
     if (this->value.ptr)
     {
         return;
     }
     this->value = chunk_clone(chunk_from_str(this->command));
     this->length = this->value.len;
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ita_attr_command_t * this, u_int32_t * offset)
Definition at line 103 of file ita_attr_command.c.
References command, NEED_MORE, strndup(), SUCCESS, and value.
 {
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     this->command = strndup(this->value.ptr, this->value.len);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ita_attr_command_t * this, chunk_t segment)
Definition at line 117 of file ita_attr_command.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ita_attr_command_t * this)
Definition at line 123 of file ita_attr_command.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ita_attr_command_t * this)
Definition at line 130 of file ita_attr_command.c.
References command, free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this->command);
         free(this);
     }
 }
METHOD (ita_attr_command_t , get_command , char * , private_ita_attr_command_t * this)
Definition at line 141 of file ita_attr_command.c.
References command.
 {
     return this->command;
 }