strongSwan: bliss_fft_t Struct Reference
bliss_fft_t Struct Reference
bliss_fft
#include "bliss_fft.h"
Public Attributes
uint16_t(* get_size)(bliss_fft_t *this)
uint16_t(* get_modulus)(bliss_fft_t *this)
void(* transform)(bliss_fft_t *this, uint32_t *a, uint32_t *b, bool inverse)
void(* destroy)(bliss_fft_t *this)
Detailed Description
Implements a Number Theoretic Transform (NTT) via the FFT algorithm
Definition at line 33 of file bliss_fft.h.
Member Data Documentation
void(* bliss_fft_t::destroy)(bliss_fft_t *this)
Destroy bliss_fft_t object
Definition at line 61 of file bliss_fft.h.
Referenced by bliss_private_key_gen(), sign_bliss(), START_TEST(), and verify_bliss().
uint16_t(* bliss_fft_t::get_modulus)(bliss_fft_t *this)
Get the prime modulus of the Number Theoretic Transform
Returns
Prime modulus
Definition at line 47 of file bliss_fft.h.
Referenced by START_TEST().
uint16_t(* bliss_fft_t::get_size)(bliss_fft_t *this)
Get the size of the Number Theoretic Transform
Returns
Transform size
Definition at line 40 of file bliss_fft.h.
Referenced by START_TEST().
void(* bliss_fft_t::transform)(bliss_fft_t *this, uint32_t *a, uint32_t *b, bool inverse)
Compute the [inverse] NTT of a polynomial
Parameters
a Coefficient of input polynomial
b Coefficient of output polynomial
inverse TRUE if the inverse NTT has to be computed
Definition at line 56 of file bliss_fft.h.
Referenced by bliss_private_key_gen(), sign_bliss(), START_TEST(), and verify_bliss().
The documentation for this struct was generated from the following file:
bliss_fft.h