strongSwan: tnccs_20.c File Reference
tnccs_20.c File Reference
#include "tnccs_20.h"
#include "tnccs_20_handler.h"
#include "tnccs_20_server.h"
#include "tnccs_20_client.h"
#include "batch/pb_tnc_batch.h"
#include "messages/pb_tnc_msg.h"
#include "messages/ietf/pb_pa_msg.h"
#include <tncif_names.h>
#include <tncif_pa_subtypes.h>
#include <utils/debug.h>
Classes
struct private_tnccs_20_t
Typedefs
typedef struct private_tnccs_20_t private_tnccs_20_t
Functions
METHOD (tnccs_t, send_msg, TNC_Result, private_tnccs_20_t *this, TNC_IMCID imc_id, TNC_IMVID imv_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
METHOD (tls_t, process, status_t, private_tnccs_20_t *this, void *buf, size_t buflen)
METHOD (tls_t, build, status_t, private_tnccs_20_t *this, void *buf, size_t *buflen, size_t *msglen)
METHOD (tls_t, is_server, bool, private_tnccs_20_t *this)
METHOD (tls_t, get_server_id, identification_t *, private_tnccs_20_t *this)
METHOD (tls_t, set_peer_id, void, private_tnccs_20_t *this, identification_t *id)
METHOD (tls_t, get_peer_id, identification_t *, private_tnccs_20_t *this)
METHOD (tls_t, get_purpose, tls_purpose_t, private_tnccs_20_t *this)
METHOD (tls_t, is_complete, bool, private_tnccs_20_t *this)
METHOD (tls_t, get_eap_msk, chunk_t, private_tnccs_20_t *this)
METHOD (tls_t, destroy, void, private_tnccs_20_t *this)
METHOD (tnccs_t, get_server_ip, host_t *, private_tnccs_20_t *this)
METHOD (tnccs_t, get_peer_ip, host_t *, private_tnccs_20_t *this)
METHOD (tnccs_t, get_transport, tnc_ift_type_t, private_tnccs_20_t *this)
METHOD (tnccs_t, set_transport, void, private_tnccs_20_t *this, tnc_ift_type_t transport)
METHOD (tnccs_t, get_auth_type, u_int32_t, private_tnccs_20_t *this)
METHOD (tnccs_t, set_auth_type, void, private_tnccs_20_t *this, u_int32_t auth_type)
METHOD (tnccs_t, get_pdp_server, chunk_t, private_tnccs_20_t *this, u_int16_t *port)
METHOD (tnccs_t, get_ref, tnccs_t *, private_tnccs_20_t *this)
tnccs_t * tnccs_20_create (bool is_server, identification_t *server_id, identification_t *peer_id, host_t *server_ip, host_t *peer_ip, tnc_ift_type_t transport, tnccs_cb_t cb)
Typedef Documentation
typedef struct private_tnccs_20_t private_tnccs_20_t
Definition at line 30 of file tnccs_20.c.
Function Documentation
METHOD (tnccs_t , send_msg , TNC_Result , private_tnccs_20_t * this, TNC_IMCID imc_id, TNC_IMVID imv_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
Definition at line 129 of file tnccs_20.c.
References chunk_create(), DBG1, DBG2, DBG_TNC, get_pa_subtype_names(), pb_pa_msg_create(), pen_names, TNC_MESSAGE_FLAGS_EXCLUSIVE, TNC_RESULT_ILLEGAL_OPERATION, and TNC_RESULT_SUCCESS.
 {
     pb_tnc_msg_t *pb_tnc_msg;
     enum_name_t *pa_subtype_names;
     bool excl;
     if (!this->tnccs_handler->get_send_flag(this->tnccs_handler))
     {
         DBG1(DBG_TNC, "%s %u not allowed to call SendMessage()",
                        this->to_server ? "IMC" : "IMV",
                        this->to_server ? imc_id : imv_id);
         return TNC_RESULT_ILLEGAL_OPERATION;
     }
     excl = (msg_flags & TNC_MESSAGE_FLAGS_EXCLUSIVE) != 0;
     pb_tnc_msg = pb_pa_msg_create(msg_vid, msg_subtype, imc_id, imv_id,
                                   excl, chunk_create(msg, msg_len));
     pa_subtype_names = get_pa_subtype_names(msg_vid);
     if (pa_subtype_names)
     {
         DBG2(DBG_TNC, "creating PB-PA message type '%N/%N' 0x%06x/0x%08x",
                        pen_names, msg_vid, pa_subtype_names, msg_subtype,
                        msg_vid, msg_subtype);
     }
     else
     {
         DBG2(DBG_TNC, "creating PB-PA message type '%N' 0x%06x/0x%08x",
                        pen_names, msg_vid, msg_vid, msg_subtype);
     }
     this->tnccs_handler->add_msg(this->tnccs_handler, pb_tnc_msg);
     return TNC_RESULT_SUCCESS;
 }
METHOD (tls_t , process , status_t , private_tnccs_20_t * this, void * buf, size_t buflen)
Definition at line 171 of file tnccs_20.c.
References batch(), chunk_create(), data, DBG1, DBG2, DBG3, DBG_TNC, pb_tnc_batch_t::destroy, FAILED, FALSE, chunk_t::len, NEED_MORE, PB_STATE_DECIDED, PB_STATE_END, PB_STATE_INIT, pb_tnc_batch_create_from_data(), pb_tnc_batch_t::process_header, status, SUCCESS, tnccs_20_client_create(), tnccs_20_server_create(), TRUE, and VERIFY_ERROR.
 {
     pb_tnc_batch_t *batch;
     bool from_server, fatal_header_error = FALSE;
     status_t status;
     chunk_t data;
     /* On arrival of first batch from TNC client create TNC server */
     if (this->is_server && !this->tnc_server)
     {
         this->tnc_server = tnccs_20_server_create(&this->public, _send_msg,
                                     this->max_batch_len, this->max_msg_len,
                                     this->eap_transport);
         if (!this->tnc_server)
         {
             return FAILED;
         }
         this->tnccs_handler = this->tnc_server;
         this->tnccs_handler->begin_handshake(this->tnccs_handler, FALSE);
     }
     data = chunk_create(buf, buflen);
     DBG1(DBG_TNC, "received TNCCS batch (%u bytes)", data.len);
     DBG3(DBG_TNC, "%B", &data);
     /* Parse the header of the received PB-TNC batch */
     batch = pb_tnc_batch_create_from_data(data);
     status = batch->process_header(batch, !this->mutual, this->is_server,
                                    &from_server);
     if (status == FAILED)
     {
         fatal_header_error = TRUE;
         status = VERIFY_ERROR;
     }
     this->to_server = this->mutual ? from_server : !this->is_server;
     /* In the mutual case, first batch from TNC server requires a TNC client */
     if (this->to_server && !this->tnc_client)
     {
         this->tnc_client = tnccs_20_client_create(&this->public, _send_msg,
                                     this->max_batch_len, this->max_msg_len);
         if (!this->tnc_client)
         {
             batch->destroy(batch);
             return FAILED;
         }
         this->tnccs_handler = this->tnc_client;
         this->tnccs_handler->begin_handshake(this->tnccs_handler, this->mutual);
     }
     else
     {
         /* Set active TNCCS handler for processing */
         this->tnccs_handler = this->to_server ? this->tnc_client :
                                                 this->tnc_server;
     }
     DBG2(DBG_TNC, "TNC %s is handling inbound connection",
                    this->to_server ? "client" : "server");
     if (status == SUCCESS)
     {
         status = this->tnccs_handler->process(this->tnccs_handler, batch);
     }
     if (status == VERIFY_ERROR)
     {
         this->tnccs_handler->handle_errors(this->tnccs_handler, batch,
                                            fatal_header_error);
         status = NEED_MORE;
     }
     batch->destroy(batch);
     /* Has a mutual connection been established? */
     this->mutual = this->is_server ?
                    this->tnc_server->get_mutual(this->tnc_server) :
                    this->tnc_client->get_mutual(this->tnc_client);
     if (this->mutual && !this->is_server)
     {
         pb_tnc_state_t client_state, server_state;
         client_state = !this->tnc_client ? PB_STATE_INIT :
                         this->tnc_client->get_state(this->tnc_client);
         server_state = !this->tnc_server ? PB_STATE_INIT :
                         this->tnc_server->get_state(this->tnc_server);
         /* In half-duplex mutual mode toggle the direction on the client side */
         if ((!this->to_server && client_state != PB_STATE_DECIDED) ||
             ( this->to_server && server_state != PB_STATE_END))
         {
             this->to_server = !this->to_server;
         }
         else if (client_state == PB_STATE_DECIDED &&
                  server_state == PB_STATE_END)
         {
             /* Cause the final CLOSE batch to be sent to the TNC server */
             this->to_server = TRUE;
         }
         /* Suppress a successful CLOSE batch coming from the TNC server */
         if (status == SUCCESS)
         {
             status = NEED_MORE;
         }
     }
     return status;
 }
METHOD (tls_t , build , status_t , private_tnccs_20_t * this, void * buf, size_t * buflen, size_t * msglen)
Definition at line 279 of file tnccs_20.c.
References DBG2, DBG_TNC, FAILED, tnccs_20_client_create(), and tnccs_20_server_create().
 {
     if (this->to_server)
     {
         DBG2(DBG_TNC, "TNC client is handling outbound connection");
         /* Before sending the first PB-TNC batch create TNC client */
         if (this->tnc_client)
         {
             this->tnccs_handler = this->tnc_client;
         }
         else
         {
             this->tnc_client = tnccs_20_client_create(&this->public, _send_msg,
                                                       this->max_batch_len,
                                                       this->max_msg_len);
             if (!this->tnc_client)
             {
                 return FAILED;
             }
             this->tnccs_handler = this->tnc_client;
             this->tnccs_handler->begin_handshake(this->tnccs_handler,
                                                  this->mutual);
         }
     }
     else
     {
         DBG2(DBG_TNC, "TNC server is handling outbound connection");
         /* Before sending the first PB-TNC batch create TNC server */
         if (this->tnc_server)
         {
             this->tnccs_handler = this->tnc_server;
         }
         else
         {
             this->tnc_server = tnccs_20_server_create(&this->public, _send_msg,
                                         this->max_batch_len, this->max_msg_len,
                                         this->eap_transport);
             if (!this->tnc_server)
             {
                 return FAILED;
             }
             this->tnccs_handler = this->tnc_server;
             this->tnccs_handler->begin_handshake(this->tnccs_handler,
                                                  this->mutual);
         }
     }
     return this->tnccs_handler->build(this->tnccs_handler, buf, buflen, msglen);
 }
METHOD (tls_t , is_server , bool , private_tnccs_20_t * this)
Definition at line 331 of file tnccs_20.c.
 {
     return this->is_server;
 }
METHOD (tls_t , get_server_id , identification_t * , private_tnccs_20_t * this)
Definition at line 337 of file tnccs_20.c.
 {
     return this->server_id;
 }
METHOD (tls_t , set_peer_id , void , private_tnccs_20_t * this, identification_t * id)
Definition at line 343 of file tnccs_20.c.
References DESTROY_IF.
 {
     DESTROY_IF(this->peer_id);
     this->peer_id = id->clone(id);
 }
METHOD (tls_t , get_peer_id , identification_t * , private_tnccs_20_t * this)
Definition at line 350 of file tnccs_20.c.
 {
     return this->peer_id;
 }
METHOD (tls_t , get_purpose , tls_purpose_t , private_tnccs_20_t * this)
Definition at line 356 of file tnccs_20.c.
References TLS_PURPOSE_EAP_TNC.
 {
     return TLS_PURPOSE_EAP_TNC;
 }
METHOD (tls_t , is_complete , bool , private_tnccs_20_t * this)
Definition at line 362 of file tnccs_20.c.
References callback, FALSE, tnccs_20_server_t::have_recommendation, and TRUE.
 {
     TNC_IMV_Action_Recommendation rec;
     TNC_IMV_Evaluation_Result eval;
     if (this->tnc_server)
     {
         tnccs_20_server_t *tnc_server;
         tnc_server = (tnccs_20_server_t*)this->tnc_server;
         if (tnc_server->have_recommendation(tnc_server, &rec, &eval))
         {
             return this->callback ? this->callback(rec, eval) : TRUE;
         }
     }
     return FALSE;
 }
METHOD (tls_t , get_eap_msk , chunk_t , private_tnccs_20_t * this)
Definition at line 381 of file tnccs_20.c.
References chunk_empty.
 {
     return chunk_empty;
 }
METHOD (tls_t , destroy , void , private_tnccs_20_t * this)
Definition at line 387 of file tnccs_20.c.
References DESTROY_IF, free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         DESTROY_IF(this->tnc_server);
         DESTROY_IF(this->tnc_client);
         this->server_id->destroy(this->server_id);
         this->peer_id->destroy(this->peer_id);
         this->server_ip->destroy(this->server_ip);
         this->peer_ip->destroy(this->peer_ip);
         free(this);
     }
 }
METHOD (tnccs_t , get_server_ip , host_t * , private_tnccs_20_t * this)
Definition at line 402 of file tnccs_20.c.
 {
     return this->server_ip;
 }
METHOD (tnccs_t , get_peer_ip , host_t * , private_tnccs_20_t * this)
Definition at line 408 of file tnccs_20.c.
 {
     return this->peer_ip;
 }
METHOD (tnccs_t , get_transport , tnc_ift_type_t , private_tnccs_20_t * this)
Definition at line 414 of file tnccs_20.c.
 {
     return this->transport;
 }
METHOD (tnccs_t , set_transport , void , private_tnccs_20_t * this, tnc_ift_type_t transport)
Definition at line 420 of file tnccs_20.c.
 {
     this->transport = transport;
 }
METHOD (tnccs_t , get_auth_type , u_int32_t , private_tnccs_20_t * this)
Definition at line 426 of file tnccs_20.c.
 {
     return this->auth_type;
 }
METHOD (tnccs_t , set_auth_type , void , private_tnccs_20_t * this, u_int32_t auth_type)
Definition at line 432 of file tnccs_20.c.
 {
     this->auth_type = auth_type;
 }
METHOD (tnccs_t , get_pdp_server , chunk_t , private_tnccs_20_t * this, u_int16_t * port)
Definition at line 438 of file tnccs_20.c.
References chunk_empty, and tnccs_20_client_t::get_pdp_server.
 {
     if (this->tnc_client)
     {
         tnccs_20_client_t *tnc_client;
         tnc_client = (tnccs_20_client_t*)this->tnc_client;
         return tnc_client->get_pdp_server(tnc_client, port);
     }
     else
     {
         *port = 0;
         return chunk_empty;
     }
 }
METHOD (tnccs_t , get_ref , tnccs_t * , private_tnccs_20_t * this)
Definition at line 456 of file tnccs_20.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }