strongSwan: asn1_parser.c File Reference
asn1_parser.c File Reference
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <utils/debug.h>
#include "asn1.h"
#include "asn1_parser.h"
Classes
struct private_asn1_parser_t
Macros
#define ASN1_MAX_LEVEL 10
Typedefs
typedef struct
private_asn1_parser_t private_asn1_parser_t
Functions
METHOD (asn1_parser_t, iterate, bool, private_asn1_parser_t *this, int *objectID, chunk_t *object)
METHOD (asn1_parser_t, get_level, u_int, private_asn1_parser_t *this)
METHOD (asn1_parser_t, set_top_level, void, private_asn1_parser_t *this, u_int level0)
METHOD (asn1_parser_t, set_flags, void, private_asn1_parser_t *this, bool implicit, bool private)
METHOD (asn1_parser_t, success, bool, private_asn1_parser_t *this)
METHOD (asn1_parser_t, destroy, void, private_asn1_parser_t *this)
asn1_parser_t * asn1_parser_create (asn1Object_t const *objects, chunk_t blob)
Macro Definition Documentation
#define ASN1_MAX_LEVEL 10
Definition at line 27 of file asn1_parser.c.
Typedef Documentation
typedef struct private_asn1_parser_t private_asn1_parser_t
Definition at line 29 of file asn1_parser.c.
Function Documentation
METHOD (asn1_parser_t , iterate , bool , private_asn1_parser_t * this, int * objectID, chunk_t * object)
Definition at line 81 of file asn1_parser.c.
References ASN1_BODY, ASN1_CONSTRUCTED, asn1_debug_simple_object(), ASN1_DEF, ASN1_END, ASN1_EXIT, ASN1_INVALID_LENGTH, asn1_length(), ASN1_LOOP, ASN1_OBJ, ASN1_OPT, ASN1_RAW, blob, chunk_empty, DBG1, DBG2, DBG3, DBG4, DBG_ASN, end, FALSE, asn1Object_t::flags, flags, chunk_t::len, asn1Object_t::level, asn1Object_t::name, chunk_t::ptr, and asn1Object_t::type.
 {
     chunk_t *blob, *blob1;
     u_char *start_ptr;
     u_int level;
     asn1Object_t obj;
     *object = chunk_empty;
     /* Advance to the next object syntax definition line */
     obj = this->objects[++(this->line)];
     /* Terminate if the end of the object syntax definition has been reached */
     if (obj.flags & ASN1_EXIT)
     {
         return FALSE;
     }
     if (obj.flags & ASN1_END)  /* end of loop or option found */
     {
         if (this->loopAddr[obj.level] && this->blobs[obj.level+1].len > 0)
         {
             this->line = this->loopAddr[obj.level]; /* another iteration */
             obj = this->objects[this->line];
         }
         else
         {
             this->loopAddr[obj.level] = 0;       /* exit loop or option*/
             goto end;
         }
     }
     level = this->level0 + obj.level;
     blob = this->blobs + obj.level;
     blob1 = blob + 1;
     start_ptr = blob->ptr;
     /* handle ASN.1 defaults values */
     if ((obj.flags & ASN1_DEF) && (blob->len == 0 || *start_ptr != obj.type) )
     {
         /* field is missing */
         DBG2(DBG_ASN, "L%d - %s:", level, obj.name);
         if (obj.type & ASN1_CONSTRUCTED)
         {
             this->line++ ;  /* skip context-specific tag */
         }
         goto end;
     }
     /* handle ASN.1 options */
     if ((obj.flags & ASN1_OPT)
             && (blob->len == 0 || *start_ptr != obj.type))
     {
         /* advance to end of missing option field */
         do
         {
             this->line++;
         }
         while (!((this->objects[this->line].flags & ASN1_END) &&
                  (this->objects[this->line].level == obj.level)));
         goto end;
     }
     /* an ASN.1 object must possess at least a tag and length field */
     if (blob->len < 2)
     {
         DBG1(DBG_ASN, "L%d - %s:  ASN.1 object smaller than 2 octets",
                     level, obj.name);
         this->success = FALSE;
         goto end;
     }
     blob1->len = asn1_length(blob);
     if (blob1->len == ASN1_INVALID_LENGTH)
     {
         DBG1(DBG_ASN, "L%d - %s:  length of ASN.1 object invalid or too large",
                     level, obj.name);
         this->success = FALSE;
         goto end;
     }
     blob1->ptr = blob->ptr;
     blob->ptr += blob1->len;
     blob->len -= blob1->len;
     /* return raw ASN.1 object without prior type checking */
     if (obj.flags & ASN1_RAW)
     {
         DBG2(DBG_ASN, "L%d - %s:", level, obj.name);
         object->ptr = start_ptr;
         object->len = (size_t)(blob->ptr - start_ptr);
         goto end;
     }
     if (*start_ptr != obj.type && !(this->implicit && this->line == 0))
     {
         DBG2(DBG_ASN, "L%d - %s: ASN1 tag 0x%02x expected, but is 0x%02x",
                     level, obj.name, obj.type, *start_ptr);
         DBG3(DBG_ASN, "%b", start_ptr, (u_int)(blob->ptr - start_ptr));
         this->success = FALSE;
         goto end;
     }
     DBG2(DBG_ASN, "L%d - %s:", level, obj.name);
     /* In case of "SEQUENCE OF" or "SET OF" start a loop */
     if (obj.flags & ASN1_LOOP)
     {
         if (blob1->len > 0)
         {
             /* at least one item, start the loop */
             this->loopAddr[obj.level] = this->line + 1;
         }
         else
         {
             /* no items, advance directly to end of loop */
             do
             {
                 this->line++;
             }
             while (!((this->objects[this->line].flags & ASN1_END) &&
                      (this->objects[this->line].level == obj.level)));
             goto end;
         }
     }
     if (obj.flags & ASN1_OBJ)
     {
         object->ptr = start_ptr;
         object->len = (size_t)(blob->ptr - start_ptr);
         if (this->private)
         {
             DBG4(DBG_ASN, "%B", object);
         }
         else
         {
             DBG3(DBG_ASN, "%B", object);
         }
     }
     else if (obj.flags & ASN1_BODY)
     {
         *object = *blob1;
         asn1_debug_simple_object(*object, obj.type, this->private);
     }
 end:
     *objectID = this->line;
     return this->success;
 }
METHOD (asn1_parser_t , get_level , u_int , private_asn1_parser_t * this)
Definition at line 236 of file asn1_parser.c.
 {
     return this->level0 + this->objects[this->line].level;
 }
METHOD (asn1_parser_t , set_top_level , void , private_asn1_parser_t * this, u_int level0)
Definition at line 242 of file asn1_parser.c.
 {
     this->level0 = level0;
 }
METHOD (asn1_parser_t , set_flags , void , private_asn1_parser_t * this, bool implicit, bool private)
Definition at line 248 of file asn1_parser.c.
 {
     this->implicit = implicit;
     this->private = private;
 }
METHOD (asn1_parser_t , success , bool , private_asn1_parser_t * this)
Definition at line 255 of file asn1_parser.c.
 {
     return this->success;
 }
METHOD (asn1_parser_t , destroy , void , private_asn1_parser_t * this)
Definition at line 261 of file asn1_parser.c.
References free().
 {
     free(this);
 }