strongSwan: pkcs1_encoder
pkcs1_encoder
pkcs1
Functions
bool pkcs1_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Detailed Description
Function Documentation
bool pkcs1_encoder_encode (cred_encoding_type_t type, chunk_t * encoding, va_list args)
Encoding function for PKCS#1/ASN.1 fingerprints/key formats.
See header.
Definition at line 162 of file pkcs1_encoder.c.
References build_info_sha1(), build_priv(), build_pub(), build_pub_info(), build_pub_modulus(), build_sha1(), FALSE, KEYID_PUBKEY_INFO_SHA1, KEYID_PUBKEY_SHA1, PRIVKEY_ASN1_DER, PUBKEY_ASN1_DER, PUBKEY_RSA_MODULUS, and PUBKEY_SPKI_ASN1_DER.
Referenced by METHOD(), and pkcs1_plugin_create().
 {
     switch (type)
     {
         case KEYID_PUBKEY_INFO_SHA1:
             return build_info_sha1(encoding, args);
         case KEYID_PUBKEY_SHA1:
             return build_sha1(encoding, args);
         case PUBKEY_ASN1_DER:
             return build_pub(encoding, args);
         case PUBKEY_SPKI_ASN1_DER:
             return build_pub_info(encoding, args);
         case PUBKEY_RSA_MODULUS:
             return build_pub_modulus(encoding, args);
         case PRIVKEY_ASN1_DER:
             return build_priv(encoding, args);
         default:
             return FALSE;
     }
 }