strongSwan: load_authorities.c File Reference
load_authorities.c File Reference
#include <stdio.h>
#include <errno.h>
#include <limits.h>
#include "command.h"
#include "swanctl.h"
#include "load_authorities.h"
Macros
#define _GNU_SOURCE
Functions
static void add_list_key (vici_req_t *req, char *key, char *value)
static bool add_file_key_value (vici_req_t *req, char *key, char *value)
static bool add_key_values (vici_req_t *req, settings_t *cfg, char *section)
static bool load_authority (vici_conn_t *conn, settings_t *cfg, char *section, command_format_options_t format)
CALLBACK (list_authority, int, linked_list_t *list, vici_res_t *res, char *name, void *value, int len)
static linked_list_t * list_authorities (vici_conn_t *conn, command_format_options_t format)
static void remove_from_list (linked_list_t *list, char *str)
static bool unload_authority (vici_conn_t *conn, char *name, command_format_options_t format)
int load_authorities_cfg (vici_conn_t *conn, command_format_options_t format, settings_t *cfg)
static int load_authorities (vici_conn_t *conn)
static void __attribute__ ((constructor))
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file load_authorities.c.
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 353 of file load_authorities.c.
References command_register(), and load_authorities().
 {
     command_register((command_t) {
         load_authorities, 'b',
         "load-authorities", "(re-)load authority configuration",
         {"[--raw|--pretty]"},
         {
             {"help",        'h', 0, "show usage information"},
             {"raw",         'r', 0, "dump raw response message"},
             {"pretty",      'P', 0, "dump raw response message in pretty print"},
         }
     });
 }
static bool add_file_key_value (vici_req_t * req, char * key, char * value) static
Add a vici certificate blob value given by its file patch
Definition at line 46 of file load_authorities.c.
References chunk_map(), chunk_unmap(), DIRECTORY_SEPARATOR, FALSE, fprintf, chunk_t::len, path, path_absolute(), chunk_t::ptr, snprintf, strerror, SWANCTL_X509CADIR, TRUE, value, and vici_add_key_value().
Referenced by add_key_values().
 {
     chunk_t *map;
     char *path, buf[PATH_MAX];
     if (path_absolute(value))
     {
         path = value;
     }
     else
     {
         path = buf;
         snprintf(path, PATH_MAX, "%s%s%s",
                  SWANCTL_X509CADIR, DIRECTORY_SEPARATOR, value);
     }
     map = chunk_map(path, FALSE);
     if (map)
     {
         vici_add_key_value(req, key, map->ptr, map->len);
         chunk_unmap(map);
         return TRUE;
     }
     else
     {
         fprintf(stderr, "loading ca certificate '%s' failed: %s\n",
                 path, strerror(errno));
         return FALSE;
     }
 }
static bool add_key_values (vici_req_t * req, settings_t * cfg, char * section) static
Translate sletting key/values from a section into vici key-values/lists
Definition at line 80 of file load_authorities.c.
References add_file_key_value(), add_list_key(), settings_t::create_key_value_enumerator, enumerator_t::destroy, enumerator_t::enumerate, key, streq(), TRUE, value, and vici_add_key_valuef().
Referenced by load_authority().
 {
     enumerator_t *enumerator;
     char *key, *value;
     bool ret = TRUE;
     enumerator = cfg->create_key_value_enumerator(cfg, section);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         /* pool subnet is encoded as key/value, all other attributes as list */
         if (streq(key, "cacert"))
         {
             ret = add_file_key_value(req, key, value);
         }
         else if (streq(key, "cert_uri_base"))
         {
             vici_add_key_valuef(req, key, "%s", value);
         }
         else
         {
             add_list_key(req, key, value);
         }
         if (!ret)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return ret;
 }
static void add_list_key (vici_req_t * req, char * key, char * value) static
Add a vici list from a comma separated string value
Definition at line 28 of file load_authorities.c.
References enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), vici_add_list_itemf(), vici_begin_list(), and vici_end_list().
Referenced by add_key_values().
 {
     enumerator_t *enumerator;
     char *token;
     vici_begin_list(req, key);
     enumerator = enumerator_create_token(value, ",", " ");
     while (enumerator->enumerate(enumerator, &token))
     {
         vici_add_list_itemf(req, "%s", token);
     }
     enumerator->destroy(enumerator);
     vici_end_list(req);
 }
CALLBACK (list_authority , int , linked_list_t * list, vici_res_t * res, char * name, void * value, int len)
Definition at line 160 of file load_authorities.c.
References asprintf(), linked_list_t::insert_last, str, and streq().
 {
     if (streq(name, "authorities"))
     {
         char *str;
         if (asprintf(&str, "%.*s", len, value) != -1)
         {
             list->insert_last(list, str);
         }
     }
     return 0;
 }
static linked_list_t* list_authorities (vici_conn_t * conn, command_format_options_t format) static
Create a list of currently loaded authorities
Definition at line 178 of file load_authorities.c.
References COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, linked_list_create(), list, res, vici_begin(), vici_dump(), vici_free_res(), vici_parse_cb(), and vici_submit().
Referenced by load_authorities_cfg().
 {
     linked_list_t *list;
     vici_res_t *res;
     list = linked_list_create();
     res = vici_submit(vici_begin("get-authorities"), conn);
     if (res)
     {
         if (format & COMMAND_FORMAT_RAW)
         {
             vici_dump(res, "get-authorities reply", format & COMMAND_FORMAT_PRETTY,
                       stdout);
         }
         vici_parse_cb(res, NULL, NULL, list_authority, list);
         vici_free_res(res);
     }
     return list;
 }
static int load_authorities (vici_conn_t * conn) static
Definition at line 309 of file load_authorities.c.
References COMMAND_FORMAT_NONE, COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, command_getopt(), command_usage(), settings_t::destroy, fprintf, load_authorities_cfg(), settings_create(), SWANCTL_CONF, and TRUE.
Referenced by __attribute__().
 {
     command_format_options_t format = COMMAND_FORMAT_NONE;
     settings_t *cfg;
     char *arg;
     int ret;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 'P':
                 format |= COMMAND_FORMAT_PRETTY;
                 /* fall through to raw */
             case 'r':
                 format |= COMMAND_FORMAT_RAW;
                 continue;
             case EOF:
                 break;
             default:
                 return command_usage("invalid --load-authorities option");
         }
         break;
     }
     cfg = settings_create(SWANCTL_CONF);
     if (!cfg)
     {
         fprintf(stderr, "parsing '%s' failed\n", SWANCTL_CONF);
         return EINVAL;
     }
     ret = load_authorities_cfg(conn, format, cfg);
     cfg->destroy(cfg);
     return ret;
 }
int load_authorities_cfg (vici_conn_t * conn, command_format_options_t format, settings_t * cfg)
See header.
Definition at line 256 of file load_authorities.c.
References COMMAND_FORMAT_RAW, settings_t::create_section_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, found, fprintf, free(), list_authorities(), load_authority(), printf, linked_list_t::remove_first, remove_from_list(), section, SUCCESS, and unload_authority().
Referenced by load_all(), and load_authorities().
 {
     u_int found = 0, loaded = 0, unloaded = 0;
     char *section;
     enumerator_t *enumerator;
     linked_list_t *authorities;
     authorities = list_authorities(conn, format);
     enumerator = cfg->create_section_enumerator(cfg, "authorities");
     while (enumerator->enumerate(enumerator, &section))
     {
         remove_from_list(authorities, section);
         found++;
         if (load_authority(conn, cfg, section, format))
         {
             loaded++;
         }
     }
     enumerator->destroy(enumerator);
     /* unload all authorities in daemon, but not in file */
     while (authorities->remove_first(authorities, (void**)&section) == SUCCESS)
     {
         if (unload_authority(conn, section, format))
         {
             unloaded++;
         }
         free(section);
     }
     authorities->destroy(authorities);
     if (format & COMMAND_FORMAT_RAW)
     {
         return 0;
     }
     if (found == 0)
     {
         printf("no authorities found, %u unloaded\n", unloaded);
         return 0;
     }
     if (loaded == found)
     {
         printf("successfully loaded %u authorities, %u unloaded\n",
                loaded, unloaded);
         return 0;
     }
     fprintf(stderr, "loaded %u of %u authorities, %u failed to load, "
             "%u unloaded\n", loaded, found, found - loaded, unloaded);
     return EINVAL;
 }
static bool load_authority (vici_conn_t * conn, settings_t * cfg, char * section, command_format_options_t format) static
Load an authority configuration
Definition at line 115 of file load_authorities.c.
References add_key_values(), COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, FALSE, fprintf, printf, req(), res, snprintf, streq(), strerror, TRUE, vici_begin(), vici_begin_section(), vici_dump(), vici_end_section(), vici_find_str(), vici_free_req(), vici_free_res(), and vici_submit().
Referenced by load_authorities_cfg(), and manage_commands().
 {
     vici_req_t *req;
     vici_res_t *res;
     bool ret = TRUE;
     char buf[128];
     snprintf(buf, sizeof(buf), "%s.%s", "authorities", section);
     req = vici_begin("load-authority");
     vici_begin_section(req, section);
     if (!add_key_values(req, cfg, buf))
     {
         vici_free_req(req);
         return FALSE;
     }
     vici_end_section(req);
     res = vici_submit(req, conn);
     if (!res)
     {
         fprintf(stderr, "load-authority request failed: %s\n", strerror(errno));
         return FALSE;
     }
     if (format & COMMAND_FORMAT_RAW)
     {
         vici_dump(res, "load-authority reply", format & COMMAND_FORMAT_PRETTY,
                   stdout);
     }
     else if (!streq(vici_find_str(res, "no", "success"), "yes"))
     {
         fprintf(stderr, "loading authority '%s' failed: %s\n",
                 section, vici_find_str(res, "", "errmsg"));
         ret = FALSE;
     }
     else
     {
         printf("loaded authority '%s'\n", section);
     }
     vici_free_res(res);
     return ret;
 }
static void remove_from_list (linked_list_t * list, char * str) static
Remove and free a string from a list
Definition at line 203 of file load_authorities.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, free(), linked_list_t::remove_at, and streq().
Referenced by load_authorities_cfg().
 {
     enumerator_t *enumerator;
     char *current;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (streq(current, str))
         {
             list->remove_at(list, enumerator);
             free(current);
         }
     }
     enumerator->destroy(enumerator);
 }
static bool unload_authority (vici_conn_t * conn, char * name, command_format_options_t format) static
Unload a authority by name
Definition at line 223 of file load_authorities.c.
References COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, FALSE, fprintf, req(), res, streq(), strerror, TRUE, vici_add_key_valuef(), vici_begin(), vici_dump(), vici_find_str(), vici_free_res(), and vici_submit().
Referenced by load_authorities_cfg(), and manage_commands().
 {
     vici_req_t *req;
     vici_res_t *res;
     bool ret = TRUE;
     req = vici_begin("unload-authority");
     vici_add_key_valuef(req, "name", "%s", name);
     res = vici_submit(req, conn);
     if (!res)
     {
         fprintf(stderr, "unload-authority request failed: %s\n", strerror(errno));
         return FALSE;
     }
     if (format & COMMAND_FORMAT_RAW)
     {
         vici_dump(res, "unload-authority reply", format & COMMAND_FORMAT_PRETTY,
                   stdout);
     }
     else if (!streq(vici_find_str(res, "no", "success"), "yes"))
     {
         fprintf(stderr, "unloading authority '%s' failed: %s\n",
                 name, vici_find_str(res, "", "errmsg"));
         ret = FALSE;
     }
     vici_free_res(res);
     return ret;
 }