strongSwan: ext_auth_listener.c File Reference
ext_auth_listener.c File Reference
#include "ext_auth_listener.h"
#include <daemon.h>
#include <utils/process.h>
#include <stdio.h>
#include <unistd.h>
Classes
struct private_ext_auth_listener_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_ext_auth_listener_t private_ext_auth_listener_t
Functions
static bool push_env (char *envp[], u_int count, char *fmt,...)
static void free_env (char *envp[])
METHOD (listener_t, authorize, bool, private_ext_auth_listener_t *this, ike_sa_t *ike_sa, bool final, bool *success)
METHOD (ext_auth_listener_t, destroy, void, private_ext_auth_listener_t *this)
ext_auth_listener_t * ext_auth_listener_create (char *script)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 26 of file ext_auth_listener.c.
Typedef Documentation
typedef struct private_ext_auth_listener_t private_ext_auth_listener_t
Definition at line 35 of file ext_auth_listener.c.
Function Documentation
static void free_env (char * envp[]) static
Free all allocated environment strings
Definition at line 81 of file ext_auth_listener.c.
References free().
Referenced by METHOD().
 {
     int i;
     for (i = 0; envp[i]; i++)
     {
         free(envp[i]);
     }
 }
METHOD (listener_t , authorize , bool , private_ext_auth_listener_t * this, ike_sa_t * ike_sa, bool final, bool * success)
Definition at line 91 of file ext_auth_listener.c.
References close, COND_EAP_AUTHENTICATED, COND_XAUTH_AUTHENTICATED, countof, DBG1, DBG_CFG, DBG_CHD, FALSE, free_env(), ike_sa_t::get_my_host, ike_sa_t::get_my_id, ike_sa_t::get_name, ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, ike_sa_t::get_other_id, ike_sa_t::get_unique_id, ike_sa_t::has_condition, out, process(), process_start_shell(), push_env(), TRUE, and process_t::wait.
 {
     if (final)
     {
         FILE *shell;
         process_t *process;
         char *envp[32] = {};
         int out, retval;
         *success = FALSE;
         push_env(envp, countof(envp), "IKE_UNIQUE_ID=%u",
                  ike_sa->get_unique_id(ike_sa));
         push_env(envp, countof(envp), "IKE_NAME=%s",
                  ike_sa->get_name(ike_sa));
         push_env(envp, countof(envp), "IKE_LOCAL_HOST=%H",
                  ike_sa->get_my_host(ike_sa));
         push_env(envp, countof(envp), "IKE_REMOTE_HOST=%H",
                  ike_sa->get_other_host(ike_sa));
         push_env(envp, countof(envp), "IKE_LOCAL_ID=%Y",
                  ike_sa->get_my_id(ike_sa));
         push_env(envp, countof(envp), "IKE_REMOTE_ID=%Y",
                  ike_sa->get_other_id(ike_sa));
         if (ike_sa->has_condition(ike_sa, COND_EAP_AUTHENTICATED) ||
             ike_sa->has_condition(ike_sa, COND_XAUTH_AUTHENTICATED))
         {
             push_env(envp, countof(envp), "IKE_REMOTE_EAP_ID=%Y",
                      ike_sa->get_other_eap_id(ike_sa));
         }
         process = process_start_shell(envp, NULL, &out, NULL,
                                       "2>&1 %s", this->script);
         if (process)
         {
             shell = fdopen(out, "r");
             if (shell)
             {
                 while (TRUE)
                 {
                     char resp[128], *e;
                     if (fgets(resp, sizeof(resp), shell) == NULL)
                     {
                         if (ferror(shell))
{
                             DBG1(DBG_CFG, "error reading from ext-auth script");
                         }
                         break;
                     }
                     else
                     {
                         e = resp + strlen(resp);
                         if (e > resp && e[-1] == '\n')
{
                             e[-1] = '\0';
                         }
                         DBG1(DBG_CHD, "ext-auth: %s", resp);
                     }
                 }
                 fclose(shell);
             }
             else
             {
                 close(out);
             }
             if (process->wait(process, &retval))
             {
                 if (retval == EXIT_SUCCESS)
                 {
                     *success = TRUE;
                 }
                 else
                 {
                     DBG1(DBG_CFG, "rejecting IKE_SA for ext-auth result: %d",
                          retval);
                 }
             }
         }
         free_env(envp);
     }
     return TRUE;
 }
METHOD (ext_auth_listener_t , destroy , void , private_ext_auth_listener_t * this)
Definition at line 179 of file ext_auth_listener.c.
References free().
 {
     free(this);
 }
static bool push_env (char * envp[], u_int count, char * fmt, ...) static
Allocate and push a format string to the environment
Definition at line 56 of file ext_auth_listener.c.
References FALSE, str, and vasprintf().
Referenced by METHOD().
 {
     int i = 0;
     char *str;
     va_list args;
     while (envp[i])
     {
         if (++i + 1 >= count)
         {
             return FALSE;
         }
     }
     va_start(args, fmt);
     if (vasprintf(&str, fmt, args) >= 0)
     {
         envp[i] = str;
     }
     va_end(args);
     return envp[i] != NULL;
 }