strongSwan: backtrace_t Struct Reference
backtrace_t Struct Reference
backtrace
#include "backtrace.h"
Public Attributes
void(* log)(backtrace_t *this, FILE *file, bool detailed)
bool(* contains_function)(backtrace_t *this, char *function[], int count)
bool(* equals)(backtrace_t *this, backtrace_t *other)
backtrace_t *(* clone)(backtrace_t *this)
enumerator_t *(* create_frame_enumerator)(backtrace_t *this)
void(* destroy)(backtrace_t *this)
Detailed Description
A backtrace registers the frames on the stack during creation.
Definition at line 33 of file backtrace.h.
Member Data Documentation
backtrace_t*(* backtrace_t::clone)(backtrace_t *this)
Create a copy of this backtrace.
Returns
cloned copy
Definition at line 68 of file backtrace.h.
Referenced by print_traces(), and report_leaks().
bool(* backtrace_t::contains_function)(backtrace_t *this, char *function[], int count)
Check if the backtrace contains a frame having a function in a list.
Parameters
function name array
number of elements in function array
Returns
TRUE if one of the functions is in the stack
Definition at line 53 of file backtrace.h.
Referenced by print_traces().
enumerator_t*(* backtrace_t::create_frame_enumerator)(backtrace_t *this)
Create an enumerator over the stack frame addresses.
Returns
enumerator_t over void*
Definition at line 75 of file backtrace.h.
Referenced by hash().
void(* backtrace_t::destroy)(backtrace_t *this)
Destroy a backtrace instance.
Definition at line 80 of file backtrace.h.
Referenced by backtrace_dump(), fatal_signal_handler(), HOOK(), print_failures(), and segv_handler().
bool(* backtrace_t::equals)(backtrace_t *this, backtrace_t *other)
Check two backtraces for equality.
Parameters
other backtrace to compare to this
Returns
TRUE if backtraces are equal
Definition at line 61 of file backtrace.h.
Referenced by equals().
void(* backtrace_t::log)(backtrace_t *this, FILE *file, bool detailed)
Log the backtrace to a FILE stream.
If no file pointer is given, the backtrace is reported over the debug framework to the registered dbg() callback function.
Parameters
file FILE to log backtrace to, NULL for dbg() function
detailed TRUE to resolve line/file using addr2line (slow)
Definition at line 44 of file backtrace.h.
Referenced by backtrace_dump(), fatal_signal_handler(), get_methods(), HOOK(), print_failures(), report_usage(), segv_handler(), and test_sighandler().
The documentation for this struct was generated from the following file:
backtrace.h