strongSwan: test_rsa.c File Reference
test_rsa.c File Reference
#include "test_suite.h"
#include <plugins/plugin_feature.h>
Functions
static void test_good_sig (private_key_t *privkey, public_key_t *pubkey)
static void test_bad_sigs (public_key_t *pubkey)
START_TEST (test_gen)
START_TEST (test_load)
END_TEST Suite * rsa_suite_create ()
Variables
static signature_scheme_t schemes []
static chunk_t invalid_sigs []
static int key_sizes []
static END_TEST chunk_t keys []
Function Documentation
END_TEST Suite* rsa_suite_create ()
Definition at line 376 of file test_rsa.c.
References countof, key_sizes, min, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, tcase_create, and tcase_set_timeout.
 {
     Suite *s;
     TCase *tc;
     int gen_count = countof(key_sizes);
     s = suite_create("rsa");
     if (getenv("TESTS_REDUCED_KEYLENGTHS") != NULL)
     {
         gen_count = min(1, gen_count);
     }
     tc = tcase_create("generate");
     tcase_add_loop_test(tc, test_gen, 0, gen_count);
     tcase_set_timeout(tc, 8);
     suite_add_tcase(s, tc);
     tc = tcase_create("load");
     tcase_add_loop_test(tc, test_load, 0, countof(keys));
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_gen)
Definition at line 123 of file test_rsa.c.
References BUILD_END, BUILD_KEY_SIZE, ck_assert, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, private_key_t::destroy, public_key_t::destroy, private_key_t::get_public_key, KEY_RSA, key_sizes, lib, test_bad_sigs(), and test_good_sig().
 {
     private_key_t *privkey;
     public_key_t *pubkey;
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                  BUILD_KEY_SIZE, key_sizes[_i], BUILD_END);
     ck_assert(privkey != NULL);
     pubkey = privkey->get_public_key(privkey);
     ck_assert(pubkey != NULL);
     test_good_sig(privkey, pubkey);
     test_bad_sigs(pubkey);
     pubkey->destroy(pubkey);
     privkey->destroy(privkey);
 }
START_TEST (test_load)
Definition at line 356 of file test_rsa.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, ck_assert, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, private_key_t::destroy, public_key_t::destroy, private_key_t::get_public_key, KEY_RSA, lib, test_bad_sigs(), and test_good_sig().
 {
     private_key_t *privkey;
     public_key_t *pubkey;
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                  BUILD_BLOB_ASN1_DER, keys[_i], BUILD_END);
     ck_assert(privkey != NULL);
     pubkey = privkey->get_public_key(privkey);
     ck_assert(pubkey != NULL);
     test_good_sig(privkey, pubkey);
     test_bad_sigs(pubkey);
     pubkey->destroy(pubkey);
     privkey->destroy(privkey);
 }
static void test_bad_sigs (public_key_t * pubkey) static
Check public key that it properly fails against some crafted sigs
Definition at line 94 of file test_rsa.c.
References chunk_from_chars, countof, data, fail_if, plugin_loader_t::has_feature, lib, PLUGIN_PROVIDE, library_t::plugins, s, schemes, signature_scheme_names, and public_key_t::verify.
Referenced by START_TEST().
 {
     chunk_t data = chunk_from_chars(0x01,0x02,0x03,0xFD,0xFE,0xFF);
     int s, i;
     for (s = 0; s < countof(schemes); s++)
     {
             if (!lib->plugins->has_feature(lib->plugins,
                             PLUGIN_PROVIDE(PUBKEY_VERIFY, schemes[s])))
             {
                 continue;
             }
         for (i = 0; i < countof(invalid_sigs); i++)
         {
             fail_if(
                 pubkey->verify(pubkey, schemes[s], data, invalid_sigs[i]),
                 "bad %N sig accepted %B", signature_scheme_names, schemes[s],
                 &invalid_sigs[i]);
         }
     }
 }
static void test_good_sig (private_key_t * privkey, public_key_t * pubkey) static
Perform a signature verification "good" test having a keypair
Definition at line 36 of file test_rsa.c.
References chunk_from_chars, countof, data, fail_unless, free(), plugin_loader_t::has_feature, lib, PLUGIN_PROVIDE, library_t::plugins, chunk_t::ptr, schemes, sig, private_key_t::sign, signature_scheme_names, and public_key_t::verify.
Referenced by START_TEST().
 {
     chunk_t sig, data = chunk_from_chars(0x01,0x02,0x03,0xFD,0xFE,0xFF);
     int i;
     for (i = 0; i < countof(schemes); i++)
     {
         if (!lib->plugins->has_feature(lib->plugins,
                         PLUGIN_PROVIDE(PUBKEY_VERIFY, schemes[i])) ||
             !lib->plugins->has_feature(lib->plugins,
                         PLUGIN_PROVIDE(PRIVKEY_SIGN, schemes[i])))
         {
             continue;
         }
         fail_unless(privkey->sign(privkey, schemes[i], data, &sig),
                     "sign %N", signature_scheme_names, schemes[i]);
         fail_unless(pubkey->verify(pubkey, schemes[i], data, sig),
                     "verify %N", signature_scheme_names, schemes[i]);
         free(sig.ptr);
     }
 }
Variable Documentation
chunk_t invalid_sigs[] static
Initial value:
= {
    chunk_from_chars(),
    chunk_from_chars(0x00),
    chunk_from_chars(0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
}
Some special signatures that should never validate successfully
Definition at line 61 of file test_rsa.c.
int key_sizes[] static
Initial value:
= {
    768, 1024, 1536, 2048, 3072, 4096,
}
RSA key sizes to test
Definition at line 119 of file test_rsa.c.
Referenced by rsa_suite_create(), and START_TEST().
END_TEST chunk_t keys[] static
Private keys to load
Definition at line 146 of file test_rsa.c.
signature_scheme_t schemes[] static
Initial value:
= {
    SIGN_RSA_EMSA_PKCS1_NULL,
    SIGN_RSA_EMSA_PKCS1_MD5,
    SIGN_RSA_EMSA_PKCS1_SHA1,
    SIGN_RSA_EMSA_PKCS1_SHA224,
    SIGN_RSA_EMSA_PKCS1_SHA256,
    SIGN_RSA_EMSA_PKCS1_SHA384,
    SIGN_RSA_EMSA_PKCS1_SHA512,
}
Signature schemes to test
Definition at line 23 of file test_rsa.c.
Referenced by test_bad_sigs(), and test_good_sig().