strongSwan: custom_proposal.c File Reference
custom_proposal.c File Reference
#include "hook.h"
#include <errno.h>
#include <encoding/payloads/sa_payload.h>
#include <config/proposal.h>
Classes
struct private_custom_proposal_t
Typedefs
typedef struct
private_custom_proposal_t private_custom_proposal_t
Functions
static linked_list_t * load_proposals (private_custom_proposal_t *this, protocol_id_t proto, u_int64_t spi)
METHOD (listener_t, message, bool, private_custom_proposal_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (hook_t, destroy, void, private_custom_proposal_t *this)
hook_t * custom_proposal_hook_create (char *name)
Typedef Documentation
typedef struct private_custom_proposal_t private_custom_proposal_t
Definition at line 23 of file custom_proposal.c.
Function Documentation
hook_t* custom_proposal_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 167 of file custom_proposal.c.
References conftest, settings_t::get_bool, settings_t::get_int, INIT, strdup, conftest_t::test, and TRUE.
 {
     private_custom_proposal_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .message = _message,
             },
             .destroy = _destroy,
         },
         .req = conftest->test->get_bool(conftest->test,
                                         "hooks.%s.request", TRUE, name),
         .id = conftest->test->get_int(conftest->test,
                                         "hooks.%s.id", 0, name),
         .name = strdup(name),
     );
     return &this->hook;
 }
static linked_list_t* load_proposals (private_custom_proposal_t * this, protocol_id_t proto, u_int64_t spi) static
Load custom proposal configuration to proposal list
Definition at line 54 of file custom_proposal.c.
References proposal_t::add_algorithm, alg, proposal_token_t::algorithm, algs, conftest, settings_t::create_key_value_enumerator, settings_t::create_section_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, end, enum_from_name, enumerator_t::enumerate, proposal_keywords_t::get_token, linked_list_t::insert_last, key, proposal_token_t::keysize, lib, linked_list_create(), list, library_t::proposal, proposal, proposal_create(), proposal_t::set_spi, conftest_t::test, transform_type_names, type, and value.
Referenced by METHOD().
 {
     enumerator_t *props, *algs;
     char *number, *key, *value;
     linked_list_t *list;
     list = linked_list_create();
     props = conftest->test->create_section_enumerator(conftest->test,
                                                       "hooks.%s", this->name);
     while (props->enumerate(props, &number))
     {
         const proposal_token_t *token = NULL;
         proposal_t *proposal;
         u_int16_t type, alg, keysize = 0;
         char *end;
         proposal = proposal_create(proto, atoi(number));
         proposal->set_spi(proposal, spi);
         algs = conftest->test->create_key_value_enumerator(conftest->test,
                                             "hooks.%s.%s", this->name, number);
         while (algs->enumerate(algs, &key, &value))
         {
             errno = 0;
             type = strtoul(key, &end, 10);
             if (end == key || errno)
             {
                 if (!enum_from_name(transform_type_names, key, &type))
                 {
                     DBG1(DBG_CFG, "unknown transform: '%s', skipped", key);
                     continue;
                 }
             }
             errno = 0;
             alg = strtoul(value, &end, 10);
             if (end == value || errno)
             {
                 token = lib->proposal->get_token(lib->proposal, value);
                 if (!token)
                 {
                     DBG1(DBG_CFG, "unknown algorithm: '%s', skipped", value);
                     continue;
                 }
                 keysize = token->keysize;
                 alg = token->algorithm;
             }
             proposal->add_algorithm(proposal, type, alg, keysize);
         }
         algs->destroy(algs);
         list->insert_last(list, proposal);
     }
     props->destroy(props);
     return list;
 }
METHOD (listener_t , message , bool , private_custom_proposal_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 110 of file custom_proposal.c.
References message_t::add_payload, linked_list_t::create_enumerator, message_t::create_payload_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, sa_payload_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, message_t::get_message_id, sa_payload_t::get_proposals, proposal_t::get_protocol, message_t::get_request, proposal_t::get_spi, payload_t::get_type, id, load_proposals(), PLV2_SECURITY_ASSOCIATION, proposal, message_t::remove_payload_at, req(), sa_payload_create_from_proposals_v2(), and TRUE.
 {
     if (!incoming && plain &&
         message->get_request(message) == this->req &&
         message->get_message_id(message) == this->id)
     {
         enumerator_t *enumerator;
         payload_t *payload;
         sa_payload_t *new, *old = NULL;
         linked_list_t *new_props, *old_props;
         proposal_t *proposal;
         enumerator = message->create_payload_enumerator(message);
         while (enumerator->enumerate(enumerator, &payload))
         {
             if (payload->get_type(payload) == PLV2_SECURITY_ASSOCIATION)
             {
                 old = (sa_payload_t*)payload;
                 message->remove_payload_at(message, enumerator);
             }
         }
         enumerator->destroy(enumerator);
         if (old)
         {
             old_props = old->get_proposals(old);
             old->destroy(old);
             enumerator = old_props->create_enumerator(old_props);
             if (enumerator->enumerate(enumerator, &proposal))
             {
                 new_props = load_proposals(this,
                                            proposal->get_protocol(proposal),
                                            proposal->get_spi(proposal));
                 DBG1(DBG_CFG, "injecting custom proposal: %#P", new_props);
                 new = sa_payload_create_from_proposals_v2(new_props);
                 message->add_payload(message, (payload_t*)new);
                 new_props->destroy_offset(new_props, offsetof(proposal_t, destroy));
             }
             enumerator->destroy(enumerator);
             old_props->destroy_offset(old_props, offsetof(proposal_t, destroy));
         }
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_custom_proposal_t * this)
Definition at line 157 of file custom_proposal.c.
References free(), and name.
 {
     free(this->name);
     free(this);
 }