strongSwan: af_alg_hasher
af_alg_hasher
af_alg
Classes
struct af_alg_hasher_t
Macros
#define AF_ALG_HASHER 7
Typedefs
typedef struct af_alg_hasher_t af_alg_hasher_t
Functions
af_alg_hasher_t * af_alg_hasher_create (hash_algorithm_t algo)
void af_alg_hasher_probe (plugin_feature_t *features, int *pos)
Detailed Description
Macro Definition Documentation
#define AF_ALG_HASHER 7
Number of hashers
Definition at line 30 of file af_alg_hasher.h.
Referenced by METHOD().
Typedef Documentation
typedef struct af_alg_hasher_t af_alg_hasher_t
Definition at line 24 of file af_alg_hasher.h.
Function Documentation
af_alg_hasher_t* af_alg_hasher_create (hash_algorithm_t algo)
Constructor to create af_alg_hasher_t.
Parameters
algo algorithm
Returns
af_alg_hasher_t, NULL if not supported
Definition at line 136 of file af_alg_hasher.c.
References af_alg_ops_create(), free(), INIT, lookup_alg(), name, and size.
Referenced by METHOD().
 {
     private_af_alg_hasher_t *this;
     char *name;
     size_t size;
     size = lookup_alg(algo, &name);
     if (!size)
     {   /* not supported by kernel */
         return NULL;
     }
     INIT(this,
         .public = {
             .hasher = {
                 .get_hash = _get_hash,
                 .allocate_hash = _allocate_hash,
                 .get_hash_size = _get_hash_size,
                 .reset = _reset,
                 .destroy = _destroy,
             },
         },
         .ops = af_alg_ops_create("hash", name),
         .size = size,
     );
     if (!this->ops)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }
void af_alg_hasher_probe (plugin_feature_t * features, int * pos)
Probe algorithms and return plugin features.
Parameters
features plugin features to create
pos current position in deps
See header.
Definition at line 62 of file af_alg_hasher.c.
References af_alg_ops_create(), algs, countof, af_alg_ops_t::destroy, name, and PLUGIN_PROVIDE.
Referenced by METHOD().
 {
     af_alg_ops_t *ops;
     int i;
     for (i = 0; i < countof(algs); i++)
     {
         ops = af_alg_ops_create("hash", algs[i].name);
         if (ops)
         {
             ops->destroy(ops);
             features[(*pos)++] = PLUGIN_PROVIDE(HASHER, algs[i].id);
         }
     }
 }