strongSwan: bliss_fft
bliss_fft
bliss
Classes
struct bliss_fft_t
Typedefs
typedef struct bliss_fft_t bliss_fft_t
Functions
bliss_fft_t * bliss_fft_create (bliss_fft_params_t *params)
Detailed Description
Typedef Documentation
typedef struct bliss_fft_t bliss_fft_t
Definition at line 28 of file bliss_fft.h.
Function Documentation
bliss_fft_t* bliss_fft_create (bliss_fft_params_t * params)
Create a bliss_fft_t object for a given FFT parameter set
Parameters
params FFT parameters
See header.
Definition at line 184 of file bliss_fft.c.
References INIT, and params.
Referenced by bliss_private_key_gen(), sign_bliss(), START_TEST(), and verify_bliss().
 {
     private_bliss_fft_t *this;
     INIT(this,
         .public = {
             .get_size = _get_size,
             .get_modulus = _get_modulus,
             .transform = _transform,
             .destroy = _destroy,
         },
         .p = params,
     );
     return &this->public;
 }