strongSwan: spinlock_t Struct Reference
spinlock_t Struct Reference
spinlock
#include "spinlock.h"
Public Attributes
void(* lock)(spinlock_t *this)
void(* unlock)(spinlock_t *this)
void(* destroy)(spinlock_t *this)
Detailed Description
Spin lock wrapper implements a lock with low overhead when the lock is held only for a short time (waiting wastes processor cycles, though).
If native spin locks are not available regular mutexes are used as fallback.
Definition at line 32 of file spinlock.h.
Member Data Documentation
void(* spinlock_t::destroy)(spinlock_t *this)
Destroy the instance.
Definition at line 47 of file spinlock.h.
Referenced by atomics_deinit(), cowfs_create(), journal_register(), METHOD(), START_TEST(), strerror_deinit(), and threads_deinit().
void(* spinlock_t::lock)(spinlock_t *this)
Acquire the lock.
Definition at line 37 of file spinlock.h.
Referenced by add_hdr(), cleanup_tls(), create_internal(), docancel(), docleanup(), get_current_thread(), has_hdr(), METHOD(), print_all(), print_global(), print_one(), print_traces(), put_thread(), ref_cur(), ref_get(), ref_put(), remove_hdr(), remove_thread(), spinlock_run(), strerror_safe(), thread_set_active_condvar(), and thread_tls_remove().
void(* spinlock_t::unlock)(spinlock_t *this)
Release the lock.
Definition at line 42 of file spinlock.h.
Referenced by add_cert_internal(), add_entry(), add_fallback_to_section(), add_hdr(), build_fds(), cache_queue(), CALLBACK(), check_timeouts(), cleanup_tls(), cowfs_readdir(), create_enumerator(), create_internal(), create_usercert_enumerator(), deliver_inbound(), deliver_plain(), docancel(), docleanup(), encode(), ensure_section(), find_socket(), find_token(), find_value(), get_any_socket(), get_current_thread(), get_interface_index(), get_rd(), get_route(), get_wr(), handle_events(), handle_plain(), has_hdr(), init_address_list(), initiator_destroy(), load_internal(), merge_config(), METHOD(), parse_token(), print_all(), print_global(), print_one(), print_traces(), process_addr(), process_link(), process_route(), put_thread(), ref_cur(), ref_get(), ref_put(), remove_entry(), remove_hdr(), remove_thread(), scan_fds(), send_outbound(), set_value(), spinlock_run(), strerror_safe(), thread_set_active_condvar(), and thread_tls_remove().
The documentation for this struct was generated from the following file:
spinlock.h