strongSwan: identification
identification
utils
Classes
struct identification_t
Typedefs
typedef enum id_type_t id_type_t
typedef struct identification_t identification_t
typedef enum id_match_t id_match_t
typedef enum id_part_t id_part_t
Enumerations
enum id_match_t {
ID_MATCH_NONE = 0, ID_MATCH_ANY = 1, ID_MATCH_MAX_WILDCARDS = 2, ID_MATCH_ONE_WILDCARD = 19,
ID_MATCH_PERFECT = 20
}
enum id_type_t {
ID_ANY = 0, ID_IPV4_ADDR = 1, ID_FQDN = 2, ID_USER_FQDN = 3,
ID_RFC822_ADDR = 3, ID_IPV4_ADDR_SUBNET = 4, ID_IPV6_ADDR = 5, ID_IPV6_ADDR_SUBNET = 6,
ID_IPV4_ADDR_RANGE = 7, ID_IPV6_ADDR_RANGE = 8, ID_DER_ASN1_DN = 9, ID_DER_ASN1_GN = 10,
ID_KEY_ID = 11, ID_DER_ASN1_GN_URI = 201
}
enum id_part_t {
ID_PART_USERNAME, ID_PART_DOMAIN, ID_PART_TLD, ID_PART_SLD,
ID_PART_ALD, ID_PART_RDN_C, ID_PART_RDN_CN, ID_PART_RDN_D,
ID_PART_RDN_E, ID_PART_RDN_EN, ID_PART_RDN_G, ID_PART_RDN_I,
ID_PART_RDN_DNQ, ID_PART_RDN_ID, ID_PART_RDN_L, ID_PART_RDN_N,
ID_PART_RDN_O, ID_PART_RDN_OU, ID_PART_RDN_S, ID_PART_RDN_SN,
ID_PART_RDN_ST, ID_PART_RDN_T
}
Functions
identification_t * identification_create_from_string (char *string)
identification_t * identification_create_from_data (chunk_t data)
identification_t * identification_create_from_encoding (id_type_t type, chunk_t encoded)
identification_t * identification_create_from_sockaddr (sockaddr_t *sockaddr)
int identification_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Variables
enum_name_t * id_match_names
enum_name_t * id_type_names
Detailed Description
Typedef Documentation
typedef enum id_match_t id_match_t
Definition at line 29 of file identification.h.
typedef enum id_part_t id_part_t
Definition at line 30 of file identification.h.
typedef enum id_type_t id_type_t
Definition at line 27 of file identification.h.
typedef struct identification_t identification_t
Definition at line 28 of file identification.h.
Enumeration Type Documentation
enum id_match_t
Matches returned from identification_t.match
Enumerator
ID_MATCH_NONE
ID_MATCH_ANY
ID_MATCH_MAX_WILDCARDS
ID_MATCH_ONE_WILDCARD
ID_MATCH_PERFECT
Definition at line 38 of file identification.h.
                 {
     /* no match */
     ID_MATCH_NONE = 0,
     /* match to %any ID */
     ID_MATCH_ANY = 1,
     /* match with maximum allowed wildcards */
     ID_MATCH_MAX_WILDCARDS = 2,
     /* match with only one wildcard */
     ID_MATCH_ONE_WILDCARD = 19,
     /* perfect match, won't get better */
     ID_MATCH_PERFECT = 20,
 };
enum id_part_t
Type of an ID sub part.
Enumerator
ID_PART_USERNAME
Username part of an RFC822_ADDR
ID_PART_DOMAIN
Domain part of an RFC822_ADDR
ID_PART_TLD
Top-Level domain of a FQDN
ID_PART_SLD
Second-Level domain of a FQDN
ID_PART_ALD
Another Level domain of a FQDN
ID_PART_RDN_C
Country RDN of a DN
ID_PART_RDN_CN
CommonName RDN of a DN
ID_PART_RDN_D
Description RDN of a DN
ID_PART_RDN_E
Email RDN of a DN
ID_PART_RDN_EN
EmployeeNumber RDN of a DN
ID_PART_RDN_G
GivenName RDN of a DN
ID_PART_RDN_I
Initials RDN of a DN
ID_PART_RDN_DNQ
DN Qualifier RDN of a DN
ID_PART_RDN_ID
UniqueIdentifier RDN of a DN
ID_PART_RDN_L
Locality RDN of a DN
ID_PART_RDN_N
Name RDN of a DN
ID_PART_RDN_O
Organization RDN of a DN
ID_PART_RDN_OU
OrganizationUnit RDN of a DN
ID_PART_RDN_S
Surname RDN of a DN
ID_PART_RDN_SN
SerialNumber RDN of a DN
ID_PART_RDN_ST
StateOrProvince RDN of a DN
ID_PART_RDN_T
Title RDN of a DN
Definition at line 142 of file identification.h.
                {
     ID_PART_USERNAME,
     ID_PART_DOMAIN,
     ID_PART_TLD,
     ID_PART_SLD,
     ID_PART_ALD,
     ID_PART_RDN_C,
     ID_PART_RDN_CN,
     ID_PART_RDN_D,
     ID_PART_RDN_E,
     ID_PART_RDN_EN,
     ID_PART_RDN_G,
     ID_PART_RDN_I,
     ID_PART_RDN_DNQ,
     ID_PART_RDN_ID,
     ID_PART_RDN_L,
     ID_PART_RDN_N,
     ID_PART_RDN_O,
     ID_PART_RDN_OU,
     ID_PART_RDN_S,
     ID_PART_RDN_SN,
     ID_PART_RDN_ST,
     ID_PART_RDN_T,
 };
enum id_type_t
ID Types in a ID payload.
Enumerator
ID_ANY
private type which matches any other id.
ID_IPV4_ADDR
ID data is a single four (4) octet IPv4 address.
ID_FQDN
ID data is a fully-qualified domain name string. An example of a ID_FQDN is "example.com". The string MUST not contain any terminators (e.g., NULL, CR, etc.).
ID_USER_FQDN
ID data is a fully-qualified RFC822 email address string. An example of an ID_RFC822_ADDR is "jsmith@example.com". The string MUST NOT contain any terminators.
ID_RFC822_ADDR
ID_IPV4_ADDR_SUBNET
ID data is an IPv4 subnet (IKEv1 only)
ID_IPV6_ADDR
ID data is a single sixteen (16) octet IPv6 address.
ID_IPV6_ADDR_SUBNET
ID data is an IPv6 subnet (IKEv1 only)
ID_IPV4_ADDR_RANGE
ID data is an IPv4 address range (IKEv1 only)
ID_IPV6_ADDR_RANGE
ID data is an IPv6 address range (IKEv1 only)
ID_DER_ASN1_DN
ID data is the binary DER encoding of an ASN.1 X.501 Distinguished Name
ID_DER_ASN1_GN
ID data is the binary DER encoding of an ASN.1 X.509 GeneralName
ID_KEY_ID
ID data is an opaque octet stream which may be used to pass vendor- specific information necessary to do certain proprietary types of identification.
ID_DER_ASN1_GN_URI
Private ID type which represents a GeneralName of type URI
Definition at line 59 of file identification.h.
                {
     ID_ANY = 0,
     ID_IPV4_ADDR = 1,
     ID_FQDN = 2,
     ID_USER_FQDN   = 3, /* IKEv1 only */
     ID_RFC822_ADDR = 3, /* IKEv2 only */
     ID_IPV4_ADDR_SUBNET = 4,
     ID_IPV6_ADDR = 5,
     ID_IPV6_ADDR_SUBNET = 6,
     ID_IPV4_ADDR_RANGE = 7,
     ID_IPV6_ADDR_RANGE = 8,
     ID_DER_ASN1_DN = 9,
     ID_DER_ASN1_GN = 10,
     ID_KEY_ID = 11,
     ID_DER_ASN1_GN_URI = 201,
 };
Function Documentation
identification_t* identification_create_from_data (chunk_t data)
Creates an identification from a chunk of data, guessing its type.
Parameters
data identification data
Returns
identification_t
Definition at line 1166 of file identification.c.
References ID_DER_ASN1_DN, identification_create_from_encoding(), identification_create_from_string(), is_asn1(), chunk_t::len, chunk_t::ptr, and snprintf.
Referenced by apply(), get_matching_ike_sas(), METHOD(), process_challenge(), process_class(), process_eap(), process_filter_id(), process_identity(), process_reauthentication(), process_start(), server_process_eap(), and START_TEST().
 {
     char buf[data.len + 1];
     if (is_asn1(data))
     {
         return identification_create_from_encoding(ID_DER_ASN1_DN, data);
     }
     else
     {
         /* use string constructor */
         snprintf(buf, sizeof(buf), "%.*s", (int)data.len, data.ptr);
         return identification_create_from_string(buf);
     }
 }
identification_t* identification_create_from_encoding (id_type_t type, chunk_t encoded)
Creates an identification_t object from an encoded chunk.
Parameters
type type of this id, such as ID_IPV4_ADDR
encoded encoded bytes, such as from identification_t.get_encoding
Returns
identification_t
Definition at line 1185 of file identification.c.
References chunk_clone, ID_ANY, and identification_create().
Referenced by add_attribute_certs(), add_local_certs(), build_auth_cfg(), build_cert_payload(), build_peer_cfg(), check_crl(), check_delta_crl(), check_ocsp(), find_client_id(), find_private(), general_name2id(), generate_auth_cfg(), get_private_by_cert(), has_privkey(), identification_create_from_data(), identification_create_from_sockaddr(), ike_sa_create(), issue(), leases(), list(), list_public_key(), load_cdps(), load_pin(), load_shared(), login(), METHOD(), openssl_x509_name2id(), parse(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_generalName(), parse_user_id(), pkcs11_private_key_connect(), process_certreq(), pt_tls_dispatcher_create(), pt_tls_receive(), pubkey_cert_create(), rebuild_auth(), START_TEST(), status_attr(), and try_get_cert().
 {
     private_identification_t *this = identification_create(type);
     /* apply encoded chunk */
     if (type != ID_ANY)
     {
         this->encoded = chunk_clone(encoded);
     }
     return &(this->public);
 }
identification_t* identification_create_from_sockaddr (sockaddr_t * sockaddr)
Creates an identification_t object from a sockaddr struct
Parameters
sockaddr sockaddr struct which contains family and address
Returns
identification_t
Definition at line 1201 of file identification.c.
References addr, chunk_create(), ID_ANY, ID_IPV4_ADDR, ID_IPV6_ADDR, identification_create(), and identification_create_from_encoding().
Referenced by add_nat_oa_payloads(), lookup_shared_key(), METHOD(), and START_TEST().
 {
     switch (sockaddr->sa_family)
     {
         case AF_INET:
         {
             struct in_addr *addr = &(((struct sockaddr_in*)sockaddr)->sin_addr);
             return identification_create_from_encoding(ID_IPV4_ADDR,
                     chunk_create((u_char*)addr, sizeof(struct in_addr)));
         }
         case AF_INET6:
         {
             struct in6_addr *addr = &(((struct sockaddr_in6*)sockaddr)->sin6_addr);
             return identification_create_from_encoding(ID_IPV6_ADDR,
                     chunk_create((u_char*)addr, sizeof(struct in6_addr)));
         }
         default:
         {
             private_identification_t *this = identification_create(ID_ANY);
             return &(this->public);
         }
     }
 }
identification_t* identification_create_from_string (char * string)
Creates an identification_t object from a string.
The input string may be e.g. one of the following:
ID_IPV4_ADDR: 192.168.0.1
ID_IPV6_ADDR: 2001:0db8:85a3:08d3:1319:8a2e:0370:7345
ID_FQDN: www.strongswan.org (optionally with a prepended @)
ID_RFC822_ADDR: alice.nosp@m.@won.nosp@m.derla.nosp@m.nd.o.nosp@m.rg
ID_DER_ASN1_DN: C=CH, O=Linux strongSwan, CN=bob
In favour of pluto, domainnames are prepended with an @, since pluto resolves domainnames without an @ to IPv4 addresses. Since we use a separate host_t class for addresses, this doesn't make sense for us.
A distinguished name may contain one or more of the following RDNs: ND, UID, DC, CN, S, SN, serialNumber, C, L, ST, O, OU, T, D, N, G, I, dnQualifier, ID, EN, EmployeeNumber, E, Email, emailAddress, UN, unstructuredName, TCGID.
To skip automatic type detection the following prefixes may be used to enforce a specific type: ipv4:, ipv6:, rfc822:, email:, userfqdn:, fqdn:, dns:, asn1dn:, asn1gn: and keyid:. If a # follows the :, the remaining data is interpreted as hex encoded binary data for that ID, otherwise the raw string following the prefix is used as identity data, without conversion. To specify a non-standard ID type, the numerical type may be prefixed between curly backets, building a prefix. For instance the "{1}:" prefix defines an ID_IPV4_ADDR type.
This constructor never returns NULL. If it does not find a suitable conversion function, it will copy the string to an ID_KEY_ID.
Parameters
string input string, which will be converted
Returns
identification_t
Definition at line 1042 of file identification.c.
References atodn(), chunk_clone, chunk_from_hex(), chunk_from_str, create_from_string_with_num_type(), create_from_string_with_prefix_type(), ID_ANY, ID_DER_ASN1_DN, ID_FQDN, ID_IPV4_ADDR, ID_IPV6_ADDR, ID_KEY_ID, ID_RFC822_ADDR, ID_USER_FQDN, identification_create(), inet_pton(), strdup, streq(), and SUCCESS.
Referenced by add_address(), add_attr(), add_auth_cfg(), allocate_addr(), assert_acquire(), build_auth_cfg(), build_peer_cfg(), CALLBACK(), client(), connect_(), create_cert(), create_cert_ext(), create_lease_query(), del_attr(), enforce_recommendation(), gen_identity(), generate_auth_cfg(), id_contains_wildcards(), id_equals(), id_hash_equals(), id_matches(), id_matches_rev(), identification_create_from_data(), initiate_connection(), issue(), load_agent(), load_peer_config(), load_shared(), main(), METHOD(), on_accept(), parse_id(), pretend_auth_hook_create(), process_server_response(), read_triplets(), rebuild_auth_hook_create(), req(), run_echo_client(), self(), serve_echo(), setup_tunnel(), START_TEST(), string_equals(), stroke_export(), tnc_pdp_create(), and xauth_noauth_create_server().
 {
     private_identification_t *this;
     chunk_t encoded;
     if (string == NULL)
     {
         string = "%any";
     }
     this = create_from_string_with_prefix_type(string);
     if (this)
     {
         return &this->public;
     }
     this = create_from_string_with_num_type(string);
     if (this)
     {
         return &this->public;
     }
     if (strchr(string, '=') != NULL)
     {
         /* we interpret this as an ASCII X.501 ID_DER_ASN1_DN.
          * convert from LDAP style or openssl x509 -subject style to ASN.1 DN
          */
         if (atodn(string, &encoded) == SUCCESS)
         {
             this = identification_create(ID_DER_ASN1_DN);
             this->encoded = encoded;
         }
         else
         {
             this = identification_create(ID_KEY_ID);
             this->encoded = chunk_from_str(strdup(string));
         }
         return &this->public;
     }
     else if (strchr(string, '@') == NULL)
     {
         if (streq(string, "")
         ||  streq(string, "%any")
         ||  streq(string, "%any6")
         ||  streq(string, "0.0.0.0")
         ||  streq(string, "*")
         ||  streq(string, "::")
         ||  streq(string, "0::0"))
         {
             /* any ID will be accepted */
             this = identification_create(ID_ANY);
             return &this->public;
         }
         else
         {
             if (strchr(string, ':') == NULL)
             {
                 struct in_addr address;
                 chunk_t chunk = {(void*)&address, sizeof(address)};
                 if (inet_pton(AF_INET, string, &address) > 0)
                 {   /* is IPv4 */
                     this = identification_create(ID_IPV4_ADDR);
                     this->encoded = chunk_clone(chunk);
                 }
                 else
                 {   /* not IPv4, mostly FQDN */
                     this = identification_create(ID_FQDN);
                     this->encoded = chunk_from_str(strdup(string));
                 }
                 return &this->public;
             }
             else
             {
                 struct in6_addr address;
                 chunk_t chunk = {(void*)&address, sizeof(address)};
                 if (inet_pton(AF_INET6, string, &address) > 0)
                 {   /* is IPv6 */
                     this = identification_create(ID_IPV6_ADDR);
                     this->encoded = chunk_clone(chunk);
                 }
                 else
                 {   /* not IPv4/6 fallback to KEY_ID */
                     this = identification_create(ID_KEY_ID);
                     this->encoded = chunk_from_str(strdup(string));
                 }
                 return &this->public;
             }
         }
     }
     else
     {
         if (*string == '@')
         {
             string++;
             if (*string == '#')
             {
                 this = identification_create(ID_KEY_ID);
                 this->encoded = chunk_from_hex(chunk_from_str(string + 1), NULL);
                 return &this->public;
             }
             else if (*string == '@')
             {
                 this = identification_create(ID_USER_FQDN);
                 this->encoded = chunk_clone(chunk_from_str(string + 1));
                 return &this->public;
             }
             else
             {
                 this = identification_create(ID_FQDN);
                 this->encoded = chunk_clone(chunk_from_str(string));
                 return &this->public;
             }
         }
         else
         {
             this = identification_create(ID_RFC822_ADDR);
             this->encoded = chunk_from_str(strdup(string));
             return &this->public;
         }
     }
 }
int identification_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook function for identification_t.
Arguments are: identification_t *identification
Described in header.
Definition at line 827 of file identification.c.
References chunk_free(), chunk_printable(), dntoa(), HASH_SIZE_SHA1, ID_ANY, ID_DER_ASN1_DN, ID_DER_ASN1_GN, ID_DER_ASN1_GN_URI, ID_FQDN, ID_IPV4_ADDR, ID_IPV6_ADDR, ID_KEY_ID, ID_RFC822_ADDR, inet_ntop(), chunk_t::len, printf_hook_spec_t::minus, print_in_hook(), chunk_t::ptr, snprintf, type, and printf_hook_spec_t::width.
Referenced by library_init().
 {
     private_identification_t *this = *((private_identification_t**)(args[0]));
     chunk_t proper;
     char buf[512];
     if (this == NULL)
     {
         return print_in_hook(data, "%*s", spec->width, "(null)");
     }
     switch (this->type)
     {
         case ID_ANY:
             snprintf(buf, sizeof(buf), "%%any");
             break;
         case ID_IPV4_ADDR:
             if (this->encoded.len < sizeof(struct in_addr) ||
                 inet_ntop(AF_INET, this->encoded.ptr, buf, sizeof(buf)) == NULL)
             {
                 snprintf(buf, sizeof(buf), "(invalid ID_IPV4_ADDR)");
             }
             break;
         case ID_IPV6_ADDR:
             if (this->encoded.len < sizeof(struct in6_addr) ||
                 inet_ntop(AF_INET6, this->encoded.ptr, buf, INET6_ADDRSTRLEN) == NULL)
             {
                 snprintf(buf, sizeof(buf), "(invalid ID_IPV6_ADDR)");
             }
             break;
         case ID_FQDN:
         case ID_RFC822_ADDR:
         case ID_DER_ASN1_GN_URI:
             chunk_printable(this->encoded, &proper, '?');
             snprintf(buf, sizeof(buf), "%.*s", (int)proper.len, proper.ptr);
             chunk_free(&proper);
             break;
         case ID_DER_ASN1_DN:
             dntoa(this->encoded, buf, sizeof(buf));
             break;
         case ID_DER_ASN1_GN:
             snprintf(buf, sizeof(buf), "(ASN.1 general name)");
             break;
         case ID_KEY_ID:
             if (chunk_printable(this->encoded, NULL, '?') &&
                 this->encoded.len != HASH_SIZE_SHA1)
             {   /* fully printable, use ascii version */
                 snprintf(buf, sizeof(buf), "%.*s", (int)this->encoded.len,
                          this->encoded.ptr);
             }
             else
             {   /* not printable, hex dump */
                 snprintf(buf, sizeof(buf), "%#B", &this->encoded);
             }
             break;
         default:
             snprintf(buf, sizeof(buf), "(unknown ID type: %d)", this->type);
             break;
     }
     if (spec->minus)
     {
         return print_in_hook(data, "%-*s", spec->width, buf);
     }
     return print_in_hook(data, "%*s", spec->width, buf);
 }
Variable Documentation
enum_name_t* id_match_names
enum names for id_match_t.
enum_name_t* id_type_names
enum names for id_type_t.
Referenced by build_generalName(), get_peer_match(), METHOD(), name_constraint_inherited(), name_constraint_matches(), and START_TEST().