strongSwan: socket_default_socket.c File Reference
socket_default_socket.c File Reference
#include "socket_default_socket.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <netinet/in_systm.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <netinet/udp.h>
#include <net/if.h>
#include <hydra.h>
#include <daemon.h>
#include <threading/thread.h>
Classes
struct private_socket_default_socket_t
Macros
#define _GNU_SOURCE
#define __APPLE_USE_RFC_3542
#define SOL_IP IPPROTO_IP
#define SOL_IPV6 IPPROTO_IPV6
#define IPV6_TCLASS 67
#define IPV6_RECVPKTINFO IPV6_PKTINFO
#define IN6ADDR_ANY_INIT {{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}}}
Typedefs
typedef struct
private_socket_default_socket_t private_socket_default_socket_t
Functions
static host_t * get_dst_v4 (struct cmsghdr *cmsgptr, u_int16_t port)
static host_t * get_dst_v6 (struct cmsghdr *cmsgptr, u_int16_t port)
METHOD (socket_t, receiver, status_t, private_socket_default_socket_t *this, packet_t **packet)
static ssize_t send_msg_generic (int skt, struct msghdr *msg)
static ssize_t send_msg_v4 (int skt, struct msghdr *msg, host_t *src)
static ssize_t send_msg_v6 (int skt, struct msghdr *msg, host_t *src)
METHOD (socket_t, sender, status_t, private_socket_default_socket_t *this, packet_t *packet)
METHOD (socket_t, get_port, u_int16_t, private_socket_default_socket_t *this, bool nat_t)
METHOD (socket_t, supported_families, socket_family_t, private_socket_default_socket_t *this)
static int open_socket (private_socket_default_socket_t *this, int family, u_int16_t *port)
static bool use_family (int family)
static void open_socketpair (private_socket_default_socket_t *this, int family, int *skt, int *skt_natt, char *label)
METHOD (socket_t, destroy, void, private_socket_default_socket_t *this)
socket_default_socket_t * socket_default_socket_create ()
Variables
static const struct in6_addr in6addr_any = IN6ADDR_ANY_INIT
Macro Definition Documentation
#define __APPLE_USE_RFC_3542
Definition at line 26 of file socket_default_socket.c.
#define _GNU_SOURCE
Definition at line 20 of file socket_default_socket.c.
#define IN6ADDR_ANY_INIT {{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}}}
Definition at line 66 of file socket_default_socket.c.
#define IPV6_RECVPKTINFO IPV6_PKTINFO
Definition at line 62 of file socket_default_socket.c.
Referenced by open_socket().
#define IPV6_TCLASS 67
Definition at line 56 of file socket_default_socket.c.
Referenced by METHOD().
#define SOL_IP IPPROTO_IP
Definition at line 50 of file socket_default_socket.c.
Referenced by add_socket_bypass(), METHOD(), and open_socket().
#define SOL_IPV6 IPPROTO_IPV6
Definition at line 53 of file socket_default_socket.c.
Referenced by add_socket_bypass(), METHOD(), and open_socket().
Typedef Documentation
typedef struct private_socket_default_socket_t private_socket_default_socket_t
Definition at line 73 of file socket_default_socket.c.
Function Documentation
static host_t* get_dst_v4 (struct cmsghdr * cmsgptr, u_int16_t port) static
Get the destination IPv4 address of a received packet, depending on the available mechanism.
Definition at line 197 of file socket_default_socket.c.
Referenced by METHOD().
 {
     return NULL;
 }
static host_t* get_dst_v6 (struct cmsghdr * cmsgptr, u_int16_t port) static
Get the destination IPv6 address of a received packet, depending on the available mechanism.
Definition at line 229 of file socket_default_socket.c.
Referenced by METHOD().
 {
     return NULL;
 }
METHOD (socket_t , receiver , status_t , private_socket_default_socket_t * this, packet_t ** packet)
Definition at line 236 of file socket_default_socket.c.
References chunk_clone, chunk_create(), countof, data, DBG1, DBG2, DBG3, DBG_NET, dest, FAILED, pollfd::fd, get_dst_v4(), get_dst_v6(), host_create_from_sockaddr(), packet_create(), poll, POLLIN, port, pollfd::revents, packet_t::set_data, packet_t::set_destination, packet_t::set_source, SOL_IP, SOL_IPV6, source, src, strerror, SUCCESS, thread_cancelability(), and TRUE.
 {
     char buffer[this->max_packet];
     chunk_t data;
     packet_t *pkt;
     host_t *source = NULL, *dest = NULL;
     int i, rr, index, bytes_read = 0, selected = -1;
     bool oldstate;
     u_int16_t port = 0;
     struct pollfd pfd[] = {
         { .fd = this->ipv4,         .events = POLLIN },
         { .fd = this->ipv4_natt,    .events = POLLIN },
         { .fd = this->ipv6,         .events = POLLIN },
         { .fd = this->ipv6_natt,    .events = POLLIN },
     };
     int ports[] = {
         /* port numbers associated to pollfds */
         this->port, this->natt, this->port, this->natt,
     };
     DBG2(DBG_NET, "waiting for data on sockets");
     oldstate = thread_cancelability(TRUE);
     if (poll(pfd, countof(pfd), -1) <= 0)
     {
         thread_cancelability(oldstate);
         return FAILED;
     }
     thread_cancelability(oldstate);
     rr = this->rr_counter++;
     for (i = 0; i < countof(pfd); i++)
     {
         /* To serve all ports with equal priority, we use a round-robin
          * scheme to choose the one to process in this invocation */
         index = (rr + i) % countof(pfd);
         if (pfd[index].revents & POLLIN)
         {
             selected = pfd[index].fd;
             port = ports[index];
             break;
         }
     }
     if (selected != -1)
     {
         struct msghdr msg;
         struct cmsghdr *cmsgptr;
         struct iovec iov;
         char ancillary[64];
         union {
             struct sockaddr_in in4;
             struct sockaddr_in6 in6;
         } src;
         msg.msg_name = &src;
         msg.msg_namelen = sizeof(src);
         iov.iov_base = buffer;
         iov.iov_len = this->max_packet;
         msg.msg_iov = &iov;
         msg.msg_iovlen = 1;
         msg.msg_control = ancillary;
         msg.msg_controllen = sizeof(ancillary);
         msg.msg_flags = 0;
         bytes_read = recvmsg(selected, &msg, 0);
         if (bytes_read < 0)
         {
             DBG1(DBG_NET, "error reading socket: %s", strerror(errno));
             return FAILED;
         }
         if (msg.msg_flags & MSG_TRUNC)
         {
             DBG1(DBG_NET, "receive buffer too small, packet discarded");
             return FAILED;
         }
         DBG3(DBG_NET, "received packet %b", buffer, bytes_read);
         /* read ancillary data to get destination address */
         for (cmsgptr = CMSG_FIRSTHDR(&msg); cmsgptr != NULL;
              cmsgptr = CMSG_NXTHDR(&msg, cmsgptr))
         {
             if (cmsgptr->cmsg_len == 0)
             {
                 DBG1(DBG_NET, "error reading ancillary data");
                 return FAILED;
             }
             if (cmsgptr->cmsg_level == SOL_IP)
             {
                 dest = get_dst_v4(cmsgptr, port);
             }
             else if (cmsgptr->cmsg_level == SOL_IPV6)
             {
                 dest = get_dst_v6(cmsgptr, port);
             }
             if (dest)
             {
                 break;
             }
         }
         if (dest == NULL)
         {
             DBG1(DBG_NET, "error reading IP header");
             return FAILED;
         }
         source = host_create_from_sockaddr((sockaddr_t*)&src);
         pkt = packet_create();
         pkt->set_source(pkt, source);
         pkt->set_destination(pkt, dest);
         DBG2(DBG_NET, "received packet: from %#H to %#H", source, dest);
         data = chunk_create(buffer, bytes_read);
         pkt->set_data(pkt, chunk_clone(data));
     }
     else
     {
         /* oops, shouldn't happen */
         return FAILED;
     }
     /* return packet */
     *packet = pkt;
     return SUCCESS;
 }
METHOD (socket_t , sender , status_t , private_socket_default_socket_t * this, packet_t * packet)
Definition at line 459 of file socket_default_socket.c.
References data, DBG1, DBG2, DBG_NET, dst, FAILED, family, packet_t::get_data, packet_t::get_destination, packet_t::get_dscp, host_t::get_family, host_t::get_port, host_t::get_sockaddr, host_t::get_sockaddr_len, packet_t::get_source, IPV6_TCLASS, host_t::is_anyaddr, chunk_t::len, memset, chunk_t::ptr, send_msg_generic(), send_msg_v4(), send_msg_v6(), setsockopt, SOL_IP, SOL_IPV6, src, strerror, and SUCCESS.
 {
     int sport, skt = -1, family;
     ssize_t bytes_sent;
     chunk_t data;
     host_t *src, *dst;
     struct msghdr msg;
     struct iovec iov;
     u_int8_t *dscp;
     src = packet->get_source(packet);
     dst = packet->get_destination(packet);
     data = packet->get_data(packet);
     DBG2(DBG_NET, "sending packet: from %#H to %#H", src, dst);
     /* send data */
     sport = src->get_port(src);
     family = dst->get_family(dst);
     if (sport == 0 || sport == this->port)
     {
         switch (family)
         {
             case AF_INET:
                 skt = this->ipv4;
                 dscp = &this->dscp4;
                 break;
             case AF_INET6:
                 skt = this->ipv6;
                 dscp = &this->dscp6;
                 break;
             default:
                 return FAILED;
         }
     }
     else if (sport == this->natt)
     {
         switch (family)
         {
             case AF_INET:
                 skt = this->ipv4_natt;
                 dscp = &this->dscp4_natt;
                 break;
             case AF_INET6:
                 skt = this->ipv6_natt;
                 dscp = &this->dscp6_natt;
                 break;
             default:
                 return FAILED;
         }
     }
     if (skt == -1)
     {
         DBG1(DBG_NET, "no socket found to send IPv%d packet from port %d",
              family == AF_INET ? 4 : 6, sport);
         return FAILED;
     }
     /* setting DSCP values per-packet in a cmsg seems not to be supported
      * on Linux. We instead setsockopt() before sending it, this should be
      * safe as only a single thread calls send(). */
     if (*dscp != packet->get_dscp(packet))
     {
         if (family == AF_INET)
         {
             u_int8_t ds4;
             ds4 = packet->get_dscp(packet) << 2;
             if (setsockopt(skt, SOL_IP, IP_TOS, &ds4, sizeof(ds4)) == 0)
             {
                 *dscp = packet->get_dscp(packet);
             }
             else
             {
                 DBG1(DBG_NET, "unable to set IP_TOS on socket: %s",
                      strerror(errno));
             }
         }
         else
         {
             u_int ds6;
             ds6 = packet->get_dscp(packet) << 2;
             if (setsockopt(skt, SOL_IPV6, IPV6_TCLASS, &ds6, sizeof(ds6)) == 0)
             {
                 *dscp = packet->get_dscp(packet);
             }
             else
             {
                 DBG1(DBG_NET, "unable to set IPV6_TCLASS on socket: %s",
                      strerror(errno));
             }
         }
     }
     memset(&msg, 0, sizeof(struct msghdr));
     msg.msg_name = dst->get_sockaddr(dst);;
     msg.msg_namelen = *dst->get_sockaddr_len(dst);
     iov.iov_base = data.ptr;
     iov.iov_len = data.len;
     msg.msg_iov = &iov;
     msg.msg_iovlen = 1;
     msg.msg_flags = 0;
     if (this->set_source && !src->is_anyaddr(src))
     {
         if (family == AF_INET)
         {
             bytes_sent = send_msg_v4(skt, &msg, src);
         }
         else
         {
             bytes_sent = send_msg_v6(skt, &msg, src);
         }
     }
     else
     {
         bytes_sent = send_msg_generic(skt, &msg);
     }
     if (bytes_sent != data.len)
     {
         DBG1(DBG_NET, "error writing to socket: %s", strerror(errno));
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (socket_t , get_port , u_int16_t , private_socket_default_socket_t * this, bool nat_t)
Definition at line 588 of file socket_default_socket.c.
References port.
 {
     return nat_t ? this->natt : this->port;
 }
METHOD (socket_t , supported_families , socket_family_t , private_socket_default_socket_t * this)
Definition at line 594 of file socket_default_socket.c.
References SOCKET_FAMILY_IPV4, SOCKET_FAMILY_IPV6, and SOCKET_FAMILY_NONE.
 {
     socket_family_t families = SOCKET_FAMILY_NONE;
     if (this->ipv4 != -1 || this->ipv4_natt != -1)
     {
         families |= SOCKET_FAMILY_IPV4;
     }
     if (this->ipv6 != -1 || this->ipv6_natt != -1)
     {
         families |= SOCKET_FAMILY_IPV6;
     }
     return families;
 }
METHOD (socket_t , destroy , void , private_socket_default_socket_t * this)
Definition at line 788 of file socket_default_socket.c.
References close, and free().
 {
     if (this->ipv4 != -1)
     {
         close(this->ipv4);
     }
     if (this->ipv4_natt != -1)
     {
         close(this->ipv4_natt);
     }
     if (this->ipv6 != -1)
     {
         close(this->ipv6);
     }
     if (this->ipv6_natt != -1)
     {
         close(this->ipv6_natt);
     }
     free(this);
 }
static int open_socket (private_socket_default_socket_t * this, int family, u_int16_t * port) static
open a socket to send and receive packets
Definition at line 613 of file socket_default_socket.c.
References addr, bind, kernel_interface_t::bypass_socket, close, DBG1, DBG_NET, kernel_interface_t::enable_udp_decap, family, settings_t::get_str, getsockname, hydra, in6addr_any, IPV6_RECVPKTINFO, hydra_t::kernel_interface, lib, mark_from_string(), memcpy, memset, library_t::ns, setsockopt, library_t::settings, socket, SOL_IP, SOL_IPV6, strerror, TRUE, and mark_t::value.
Referenced by open_socketpair().
 {
     int on = TRUE;
     union {
         struct sockaddr sockaddr;
         struct sockaddr_in sin;
         struct sockaddr_in6 sin6;
     } addr;
     socklen_t addrlen;
     u_int sol, pktinfo = 0;
     int skt;
     memset(&addr, 0, sizeof(addr));
     addr.sockaddr.sa_family = family;
     /* precalculate constants depending on address family */
     switch (family)
     {
         case AF_INET:
             addr.sin.sin_addr.s_addr = htonl(INADDR_ANY);
             addr.sin.sin_port = htons(*port);
             addrlen = sizeof(addr.sin);
             sol = SOL_IP;
 #ifdef IP_PKTINFO
             pktinfo = IP_PKTINFO;
 #elif defined(IP_RECVDSTADDR)
             pktinfo = IP_RECVDSTADDR;
 #endif
             break;
         case AF_INET6:
             memcpy(&addr.sin6.sin6_addr, &in6addr_any, sizeof(in6addr_any));
             addr.sin6.sin6_port = htons(*port);
             addrlen = sizeof(addr.sin6);
             sol = SOL_IPV6;
             pktinfo = IPV6_RECVPKTINFO;
             break;
         default:
             return -1;
     }
     skt = socket(family, SOCK_DGRAM, IPPROTO_UDP);
     if (skt < 0)
     {
         DBG1(DBG_NET, "could not open socket: %s", strerror(errno));
         return -1;
     }
     if (setsockopt(skt, SOL_SOCKET, SO_REUSEADDR, (void*)&on, sizeof(on)) < 0)
     {
         DBG1(DBG_NET, "unable to set SO_REUSEADDR on socket: %s", strerror(errno));
         close(skt);
         return -1;
     }
     /* bind the socket */
     if (bind(skt, &addr.sockaddr, addrlen) < 0)
     {
         DBG1(DBG_NET, "unable to bind socket: %s", strerror(errno));
         close(skt);
         return -1;
     }
     /* retrieve randomly allocated port if needed */
     if (*port == 0)
     {
         if (getsockname(skt, &addr.sockaddr, &addrlen) < 0)
         {
             DBG1(DBG_NET, "unable to determine port: %s", strerror(errno));
             close(skt);
             return -1;
         }
         switch (family)
         {
             case AF_INET:
                 *port = ntohs(addr.sin.sin_port);
                 break;
             case AF_INET6:
                 *port = ntohs(addr.sin6.sin6_port);
                 break;
         }
     }
     /* get additional packet info on receive */
     if (pktinfo > 0)
     {
         if (setsockopt(skt, sol, pktinfo, &on, sizeof(on)) < 0)
         {
             DBG1(DBG_NET, "unable to set IP_PKTINFO on socket: %s", strerror(errno));
             close(skt);
             return -1;
         }
     }
 #ifdef SO_MARK
     {   /* set optional MARK on socket (requires CAP_NET_ADMIN) */
         char *fwmark;
         mark_t mark;
         fwmark = lib->settings->get_str(lib->settings,
                             "%s.plugins.socket-default.fwmark", NULL, lib->ns);
         if (fwmark && mark_from_string(fwmark, &mark))
         {
             if (setsockopt(skt, SOL_SOCKET, SO_MARK, &mark.value,
                            sizeof(mark.value)) < 0)
             {
                 DBG1(DBG_NET, "unable to set SO_MARK on socket: %s",
                      strerror(errno));
             }
         }
     }
 #endif
     if (!hydra->kernel_interface->bypass_socket(hydra->kernel_interface,
                                                 skt, family))
     {
         DBG1(DBG_NET, "installing IKE bypass policy failed");
     }
     /* enable UDP decapsulation for NAT-T sockets */
     if (port == &this->natt &&
         !hydra->kernel_interface->enable_udp_decap(hydra->kernel_interface,
                                                    skt, family, this->natt))
     {
         DBG1(DBG_NET, "enabling UDP decapsulation for %s on port %d failed",
              family == AF_INET ? "IPv4" : "IPv6", this->natt);
     }
     return skt;
 }
static void open_socketpair (private_socket_default_socket_t * this, int family, int * skt, int * skt_natt, char * label) static
Open a socket pair (normal and NAT traversal) for a given address family
Definition at line 762 of file socket_default_socket.c.
References DBG1, DBG_NET, open_socket(), and use_family().
Referenced by socket_default_socket_create().
 {
     if (!use_family(family))
     {
         *skt = -1;
         *skt_natt = -1;
         return;
     }
     *skt = open_socket(this, family, &this->port);
     if (*skt == -1)
     {
         *skt_natt = -1;
         DBG1(DBG_NET, "could not open %s socket, %s disabled", label, label);
     }
     else
     {
         *skt_natt = open_socket(this, family, &this->natt);
         if (*skt_natt == -1)
         {
             DBG1(DBG_NET, "could not open %s NAT-T socket", label);
         }
     }
 }
static ssize_t send_msg_generic (int skt, struct msghdr * msg) static
Generic function to send a message.
Definition at line 361 of file socket_default_socket.c.
Referenced by METHOD(), send_msg_v4(), and send_msg_v6().
 {
     return sendmsg(skt, msg, 0);
 }
static ssize_t send_msg_v4 (int skt, struct msghdr * msg, host_t * src) static
Send a message with the IPv4 source address set, if possible.
Definition at line 419 of file socket_default_socket.c.
References send_msg_generic().
Referenced by METHOD().
 {
     return send_msg_generic(skt, msg);
 }
static ssize_t send_msg_v6 (int skt, struct msghdr * msg, host_t * src) static
Send a message with the IPv6 source address set, if possible.
Definition at line 452 of file socket_default_socket.c.
References send_msg_generic().
Referenced by METHOD().
 {
     return send_msg_generic(skt, msg);
 }
static bool use_family (int family) static
Check if we should use the given family
Definition at line 744 of file socket_default_socket.c.
References FALSE, settings_t::get_bool, lib, library_t::ns, library_t::settings, and TRUE.
Referenced by open_socketpair().
 {
     switch (family)
     {
         case AF_INET:
             return lib->settings->get_bool(lib->settings,
                         "%s.plugins.socket-default.use_ipv4", TRUE, lib->ns);
         case AF_INET6:
             return lib->settings->get_bool(lib->settings,
                         "%s.plugins.socket-default.use_ipv6", TRUE, lib->ns);
         default:
             return FALSE;
     }
 }
Variable Documentation
const struct in6_addr in6addr_any = IN6ADDR_ANY_INIT static
Definition at line 70 of file socket_default_socket.c.
Referenced by open_socket(), open_tcp_socket(), and open_udp_socket().