strongSwan: openssl_pkcs12.c File Reference
openssl_pkcs12.c File Reference
#include <stdio.h>
#include <openssl/pkcs12.h>
#include "openssl_pkcs12.h"
#include "openssl_util.h"
#include <library.h>
#include <credentials/sets/mem_cred.h>
Classes
struct private_pkcs12_t
Macros
#define _GNU_SOURCE /* for asprintf() */
Typedefs
typedef struct private_pkcs12_t private_pkcs12_t
Functions
static bool add_cert (private_pkcs12_t *this, X509 *x509)
static bool add_cas (private_pkcs12_t *this, STACK_OF(X509)*cas)
static bool add_key (private_pkcs12_t *this, EVP_PKEY *private)
static bool decrypt_and_unpack (private_pkcs12_t *this)
METHOD (container_t, get_type, container_type_t, private_pkcs12_t *this)
METHOD (pkcs12_t, create_cert_enumerator, enumerator_t *, private_pkcs12_t *this)
METHOD (pkcs12_t, create_key_enumerator, enumerator_t *, private_pkcs12_t *this)
METHOD (container_t, destroy, void, private_pkcs12_t *this)
static pkcs12_t * parse (chunk_t blob)
pkcs12_t * openssl_pkcs12_load (container_type_t type, va_list args)
Macro Definition Documentation
#define _GNU_SOURCE /* for asprintf() */
Definition at line 16 of file openssl_pkcs12.c.
Typedef Documentation
typedef struct private_pkcs12_t private_pkcs12_t
Definition at line 26 of file openssl_pkcs12.c.
Function Documentation
static bool add_cas (private_pkcs12_t * this, STACK_OF(X509)* cas) static
Add CA certificates to our credential set
Definition at line 80 of file openssl_pkcs12.c.
References add_cert(), FALSE, and TRUE.
Referenced by decrypt_and_unpack().
 {
     bool success = TRUE;
     int i;
     if (!cas)
     {   /* no CAs is ok */
         return TRUE;
     }
     for (i = 0; i < sk_X509_num(cas); i++)
     {
         if (!add_cert(this, sk_X509_value(cas, i)))
         {   /* continue to free all X509 objects */
             success = FALSE;
         }
     }
     sk_X509_free(cas);
     return success;
 }
static bool add_cert (private_pkcs12_t * this, X509 * x509) static
Decode certificate and add it to our credential set
Definition at line 52 of file openssl_pkcs12.c.
References mem_cred_t::add_cert, BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, chunk_free(), credential_factory_t::create, CRED_CERTIFICATE, creds, library_t::creds, encoding, FALSE, lib, openssl_i2chunk, chunk_t::ptr, and TRUE.
Referenced by add_cas(), decrypt_and_unpack(), and mem_cred_create().
 {
     certificate_t *cert = NULL;
     chunk_t encoding;
     if (!x509)
     {   /* no certificate is ok */
         return TRUE;
     }
     encoding = openssl_i2chunk(X509, x509);
     if (encoding.ptr)
     {
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_BLOB_ASN1_DER, encoding,
                                   BUILD_END);
         if (cert)
         {
             this->creds->add_cert(this->creds, FALSE, cert);
         }
     }
     chunk_free(&encoding);
     X509_free(x509);
     return cert != NULL;
 }
static bool add_key (private_pkcs12_t * this, EVP_PKEY * private) static
Decode private key and add it to our credential set
Definition at line 103 of file openssl_pkcs12.c.
References mem_cred_t::add_key, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_clear(), credential_factory_t::create, CRED_PRIVATE_KEY, creds, library_t::creds, encoding, FALSE, key, KEY_ECDSA, KEY_RSA, lib, openssl_i2chunk, private, chunk_t::ptr, TRUE, and type.
Referenced by decrypt_and_unpack(), and mem_cred_create().
 {
     private_key_t *key = NULL;
     chunk_t encoding;
     key_type_t type;
     if (!private)
     {   /* no private key is ok */
         return TRUE;
     }
     switch (EVP_PKEY_type(private->type))
     {
         case EVP_PKEY_RSA:
             type = KEY_RSA;
             break;
         case EVP_PKEY_EC:
             type = KEY_ECDSA;
             break;
         default:
             EVP_PKEY_free(private);
             return FALSE;
     }
     encoding = openssl_i2chunk(PrivateKey, private);
     if (encoding.ptr)
     {
         key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, type,
                                  BUILD_BLOB_ASN1_DER, encoding,
                                  BUILD_END);
         if (key)
         {
             this->creds->add_key(this->creds, key);
         }
     }
     chunk_clear(&encoding);
     EVP_PKEY_free(private);
     return key != NULL;
 }
static bool decrypt_and_unpack (private_pkcs12_t * this) static
Decrypt PKCS#12 file and unpack credentials
Definition at line 144 of file openssl_pkcs12.c.
References add_cas(), add_cert(), add_key(), asprintf(), cert, credential_manager_t::create_shared_enumerator, library_t::credmgr, enumerator_t::destroy, enumerator_t::enumerate, FALSE, free(), shared_key_t::get_key, key, chunk_t::len, lib, chunk_t::ptr, and SHARED_PRIVATE_KEY_PASS.
Referenced by parse().
 {
     enumerator_t *enumerator;
     shared_key_t *shared;
     STACK_OF(X509) *cas = NULL;
     EVP_PKEY *private;
     X509 *cert;
     chunk_t key;
     char *password;
     bool success = FALSE;
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                         SHARED_PRIVATE_KEY_PASS, NULL, NULL);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         key = shared->get_key(shared);
         if (!key.ptr || asprintf(&password, "%.*s", (int)key.len, key.ptr) < 0)
         {
             password = NULL;
         }
         if (PKCS12_parse(this->p12, password, &private, &cert, &cas))
         {
             success = add_key(this, private);
             success &= add_cert(this, cert);
             success &= add_cas(this, cas);
             free(password);
             break;
         }
         free(password);
     }
     enumerator->destroy(enumerator);
     return success;
 }
METHOD (container_t , get_type , container_type_t , private_pkcs12_t * this)
Definition at line 178 of file openssl_pkcs12.c.
References CONTAINER_PKCS12.
 {
     return CONTAINER_PKCS12;
 }
METHOD (pkcs12_t , create_cert_enumerator , enumerator_t * , private_pkcs12_t * this)
Definition at line 184 of file openssl_pkcs12.c.
References CERT_ANY, credential_set_t::create_cert_enumerator, creds, FALSE, KEY_ANY, and mem_cred_t::set.
 {
     return this->creds->set.create_cert_enumerator(&this->creds->set, CERT_ANY,
                                                    KEY_ANY, NULL, FALSE);
 }
METHOD (pkcs12_t , create_key_enumerator , enumerator_t * , private_pkcs12_t * this)
Definition at line 191 of file openssl_pkcs12.c.
References credential_set_t::create_private_enumerator, creds, KEY_ANY, and mem_cred_t::set.
 {
     return this->creds->set.create_private_enumerator(&this->creds->set,
                                                       KEY_ANY, NULL);
 }
METHOD (container_t , destroy , void , private_pkcs12_t * this)
Definition at line 198 of file openssl_pkcs12.c.
References creds, mem_cred_t::destroy, and free().
 {
     if (this->p12)
     {
         PKCS12_free(this->p12);
     }
     this->creds->destroy(this->creds);
     free(this);
 }
static pkcs12_t* parse (chunk_t blob) static
Parse a PKCS#12 container
Definition at line 212 of file openssl_pkcs12.c.
References creds, decrypt_and_unpack(), destroy(), enumerator_create_empty(), INIT, chunk_t::len, mem_cred_create(), chunk_t::ptr, and return_false().
Referenced by openssl_pkcs12_load().
 {
     private_pkcs12_t *this;
     BIO *bio;
     INIT(this,
         .public = {
             .container = {
                 .get_type = _get_type,
                 .create_signature_enumerator = (void*)enumerator_create_empty,
                 .get_data = (void*)return_false,
                 .get_encoding = (void*)return_false,
                 .destroy = _destroy,
             },
             .create_cert_enumerator = _create_cert_enumerator,
             .create_key_enumerator = _create_key_enumerator,
         },
         .creds = mem_cred_create(),
     );
     bio = BIO_new_mem_buf(blob.ptr, blob.len);
     this->p12 = d2i_PKCS12_bio(bio, NULL);
     BIO_free(bio);
     if (!this->p12 || !decrypt_and_unpack(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }