strongSwan: settings_t Struct Reference
settings_t Struct Reference
settings
#include "settings.h"
Public Attributes
char *(* get_str)(settings_t *this, char *key, char *def,...)
bool(* get_bool)(settings_t *this, char *key, bool def,...)
int(* get_int)(settings_t *this, char *key, int def,...)
double(* get_double)(settings_t *this, char *key, double def,...)
u_int32_t(* get_time)(settings_t *this, char *key, u_int32_t def,...)
void(* set_str)(settings_t *this, char *key, char *value,...)
void(* set_bool)(settings_t *this, char *key, bool value,...)
void(* set_int)(settings_t *this, char *key, int value,...)
void(* set_double)(settings_t *this, char *key, double value,...)
void(* set_time)(settings_t *this, char *key, u_int32_t value,...)
bool(* set_default_str)(settings_t *this, char *key, char *value,...)
enumerator_t *(* create_section_enumerator)(settings_t *this, char *section,...)
enumerator_t *(* create_key_value_enumerator)(settings_t *this, char *section,...)
void(* add_fallback)(settings_t *this, const char *section, const char *fallback,...)
bool(* load_files)(settings_t *this, char *pattern, bool merge)
bool(* load_files_section)(settings_t *this, char *pattern, bool merge, char *section,...)
bool(* load_string)(settings_t *this, char *settings, bool merge)
bool(* load_string_section)(settings_t *this, char *settings, bool merge, char *section,...)
void(* destroy)(settings_t *this)
Detailed Description
Generic configuration options read from a config file.
The syntax is quite simple:
settings := (section|keyvalue)*
section  := name { settings }
keyvalue := key = value\n
E.g.:
a = b
section-one {
   somevalue = asdf
   subsection {
       othervalue = xxx
   }
   yetanother = zz
}
section-two {
}
The values are accessed using the get() functions using dotted keys, e.g. section-one.subsection.othervalue
Currently only a limited set of printf format specifiers are supported (namely s, d and N, see implementation for details).
Including other files
Other files can be included, using the include statement e.g.
include /somepath/subconfig.conf
Shell patterns like *.conf are possible.
If the path is relative, the directory of the file containing the include statement is used as base.
Sections loaded from included files extend previously loaded sections, already existing values are replaced.
All settings included from files are added relative to the section the include statement is in.
The following files result in the same final config as above:
a = b
section-one {
   somevalue = before include
   include include.conf
}
include two.conf
include.conf
somevalue = asdf
subsection {
   othervalue = yyy
}
yetanother = zz
two.conf
section-one {
   subsection {
       othervalue = xxx
   }
}
section-two {
}
Definition at line 156 of file settings.h.
Member Data Documentation
void(* settings_t::add_fallback)(settings_t *this, const char *section, const char *fallback,...)
Add a fallback for the given section.
Example: When the fallback 'section-two' is configured for 'section-one.two' any failed lookup for a section or key in 'section-one.two' will result in a lookup for the same section/key in 'section-two'.
Note
Lookups are depth-first and currently strictly top-down. For instance, if app.sec had lib1.sec as fallback and lib1 had lib2 as fallback the keys/sections in lib2.sec would not be considered. But if app had lib3 as fallback the contents of lib3.sec would (as app is passed during the initial lookup). In the last example the order during enumerations would be app.sec, lib1.sec, lib3.sec.
Additional arguments will be applied to both section format strings so they must be compatible.
Parameters
section section for which a fallback is configured, printf style
fallback fallback section, printf style
... argument list for section and fallback
Definition at line 305 of file settings.h.
Referenced by attr_sql_plugin_create(), libimcv_init(), libtnccs_init(), START_TEST(), and tls_create().
enumerator_t*(* settings_t::create_key_value_enumerator)(settings_t *this, char *section,...)
Create an enumerator over key/value pairs in a section.
Parameters
section section name to list key/value pairs of, printf style
... argument list for section
Returns
enumerator over (char *key, char *value)
Definition at line 280 of file settings.h.
Referenced by add_key_values(), decrypt_with_config(), load_addrs(), load_cert(), load_entries(), load_keys(), load_pools(), load_proposals(), load_secret(), parse_rounds(), register_dh_mapping(), run_scripts(), and verify_key_values().
enumerator_t*(* settings_t::create_section_enumerator)(settings_t *this, char *section,...)
Create an enumerator over subsection names of a section.
Parameters
section section including parents, printf style format
... argument list for key
Returns
enumerator over subsection names
Definition at line 270 of file settings.h.
Referenced by add_quadruple(), add_sections(), decrypt_with_config(), load_actions(), load_authorities_cfg(), load_cdps(), load_configs(), load_conns_cfg(), load_creds_cfg(), load_hooks(), load_loggers(), load_peer_config(), load_pools_cfg(), load_proposals(), METHOD(), modular_pluginlist(), pkcs11_manager_create(), TNC_IMC_BeginHandshake(), and verify_sections().
void(* settings_t::destroy)(settings_t *this)
Destroy a settings instance.
Definition at line 393 of file settings.h.
Referenced by enumerator_destroy(), load_all(), load_authorities(), load_conns(), load_creds(), load_pools(), START_TEARDOWN(), and START_TEST().
bool(* settings_t::get_bool)(settings_t *this, char *key, bool def,...)
Get a boolean yes|no, true|false value.
Parameters
key key including sections, printf style format
def value returned if key not found
... argument list for key
Returns
value of the key
Definition at line 176 of file settings.h.
Referenced by accept_unencrypted_mm(), add_notify_hook_create(), add_payload_hook_create(), add_pstn_fax_enabled(), add_swid_inventory(), add_user_app_enabled(), add_user_app_persist_enabled(), attr_sql_provider_create(), bliss_private_key_gen(), bliss_private_key_load(), build(), build_certreqs(), certexpire_export_create(), compute_shared_key(), credential_manager_create(), crypto_factory_create(), crypto_tester_create(), custom_proposal_hook_create(), dhcp_socket_create(), diffie_hellman_get_params(), diffie_hellman_init(), duplicheck_plugin_create(), eap_aka_3gpp2_card_create(), eap_aka_server_create(), eap_dynamic_create(), eap_peap_create(), eap_peap_server_create(), eap_radius_accounting_create(), eap_radius_build_attributes(), eap_radius_create(), eap_radius_handle_timeout(), eap_radius_process_attributes(), eap_sim_server_create(), eap_tls_create(), eap_ttls_create(), gcrypt_plugin_create(), handle_child_sa_failure(), ignore_message_hook_create(), ike_auth_fill_hook_create(), ike_init_create(), ike_sa_create(), ike_sa_manager_create(), imc_attestation_process(), imv_attestation_agent_create(), initialize_plugin(), kernel_libipsec_ipsec_create(), kernel_netlink_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), library_deinit(), load_addrs(), load_child_config(), load_db(), load_file_logger(), load_ike_config(), load_logger_options(), load_plugin(), load_sys_logger(), load_tester_config_create(), load_tester_listener_create(), load_tester_plugin_create(), main(), METHOD(), modular_pluginlist(), multiple_auth_enabled(), netlink_socket_create(), osx_attr_handler_create(), parse(), parse_certificate(), parse_extensions(), pkcs11_manager_create(), plugin_cb(), pts_ita_comp_ima_create(), pubkey_authenticator_create_verifier(), random_plugin_create(), receive_message(), receiver_create(), register_load_tester(), schedule_inactivity_timeout(), send_interim(), sender_create(), set_critical_hook_create(), set_ike_initiator_hook_create(), set_ike_request_hook_create(), set_ike_spi_hook_create(), set_ike_version_hook_create(), set_length_hook_create(), set_proposal_number_hook_create(), set_reserved_hook_create(), socket_default_socket_create(), start_phase2_tnc(), stroke_cred_create(), stroke_list_create(), stroke_load_ca_cert(), stroke_socket_create(), swap_ends(), systime_fix_plugin_create(), task_manager_v2_create(), TNC_IMC_BeginHandshake(), tnc_imc_create(), TNC_IMC_Initialize(), TNC_IMC_NotifyConnectionChange(), tnc_imv_create(), tnc_pdp_create(), tnccs_20_handle_ita_mutual_capability_msg(), token_event_cb(), trap_manager_create(), unencrypted_notify_hook_create(), unsort_message_hook_create(), use_family(), and whitelist_listener_create().
double(* settings_t::get_double)(settings_t *this, char *key, double def,...)
Get an double value.
Parameters
key key including sections, printf style format
def value returned if key not found
... argument list for key
Returns
value of the key
Definition at line 196 of file settings.h.
Referenced by load_configs(), task_manager_v1_create(), and task_manager_v2_create().
int(* settings_t::get_int)(settings_t *this, char *key, int def,...)
Get an integer value.
Parameters
key key including sections, printf style format
def value returned if key not found
... argument list for key
Returns
value of the key
Definition at line 186 of file settings.h.
Referenced by add_notify_hook_create(), add_payload_hook_create(), add_vendor_smi_code(), android_log_logger_create(), CALLBACK(), child_cfg_create(), coupling_validator_create(), crypto_tester_create(), custom_proposal_hook_create(), eap_peap_create(), eap_tls_create(), eap_tnc_create(), eap_ttls_create(), ha_segments_create(), host_resolver_create(), ignore_message_hook_create(), ike_auth_fill_hook_create(), ike_sa_create(), ike_sa_manager_create(), imc_attestation_process(), imv_attestation_build(), imv_attestation_process(), imv_swid_agent_create(), initialize_plugin(), kernel_netlink_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), keymat_v1_create(), led_listener_create(), libimcv_init(), load_action(), load_addrs(), load_child_config(), load_configs(), load_file_logger(), load_ike_config(), load_log_levels(), load_peer_config(), load_sys_logger(), load_tester_config_create(), load_tester_plugin_create(), main(), message_create_defrag(), METHOD(), modular_pluginlist(), netlink_socket_create(), ntru_drbg_create(), open_socket(), openssl_plugin_create(), processor_create(), radattr_listener_create(), receive_msg(), receiver_create(), sender_create(), set_critical_hook_create(), set_ike_initiator_hook_create(), set_ike_request_hook_create(), set_ike_spi_hook_create(), set_ike_version_hook_create(), set_length_hook_create(), set_proposal_number_hook_create(), set_reserved_hook_create(), socket_default_socket_create(), socket_dynamic_socket_create(), socket_win_socket_create(), sql_logger_create(), stroke_control_create(), stroke_socket_create(), systime_fix_plugin_create(), task_manager_v1_create(), task_manager_v2_create(), tnc_ifmap_listener_create(), TNC_IMC_NotifyConnectionChange(), tnc_pdp_connections_create(), tnc_pdp_create(), tnccs_11_create(), tnccs_20_create(), unencrypted_notify_hook_create(), unsort_message_hook_create(), and user_controller_create().
char*(* settings_t::get_str)(settings_t *this, char *key, char *def,...)
Get a settings value as a string.
Parameters
key key including sections, printf style format
def value returned if key not found
... argument list for key
Returns
value pointing to internal string
Definition at line 166 of file settings.h.
Referenced by add_attrs_natural_lang(), add_certification_state(), add_configuration_state(), add_device_id(), add_legacy_entry(), add_machine_type_model(), add_notify_hook_create(), add_payload_hook_create(), add_quadruple(), add_swid_inventory(), add_time_source(), add_vendor_name(), certexpire_export_create(), coupling_validator_create(), create_listener(), decrypt_with_config(), dhcp_socket_create(), duplicheck_notify_create(), eap_dynamic_create(), eap_radius_create(), eap_radius_dae_create(), eap_radius_forward_create(), eap_tnc_create(), error_notify_socket_create(), filter_cipher_config_suites(), filter_key_exchange_config_suites(), filter_mac_config_suites(), filter_specific_config_suites(), forecast_listener_create(), handle_syslog_identifier(), imc_os_info_create(), imv_attestation_agent_create(), imv_swid_agent_create(), init(), initialize_plugin(), join_groups(), kernel_interface_create(), kernel_netlink_net_create(), led_listener_create(), libimcv_init(), load_action(), load_aik(), load_aik_blob(), load_ca_certs(), load_cdps(), load_child_config(), load_configs(), load_db(), load_file_logger(), load_ike_config(), load_issuer_cert(), load_issuer_key(), load_logger_options(), load_peer_config(), load_secret(), load_tester_config_create(), load_tester_control_create(), load_tester_creds_create(), load_validator(), lookip_socket_create(), lookup_uid_gid(), main(), manage_rule(), METHOD(), ntru_ke_create(), open_database(), open_socket(), openssl_rsa_private_key_connect(), pkcs11_manager_create(), policy_stop(), pre_test(), pretend_auth_hook_create(), process_packages(), radattr_listener_create(), random_plugin_create(), rebuild_auth_hook_create(), register_vici(), resolve_handler_create(), send_stroke_msg(), set_critical_hook_create(), set_ike_spi_hook_create(), set_length_hook_create(), setup_interface(), soap_init(), start_phase2_auth(), start_phase2_tnc(), START_TEST(), stroke_cred_create(), stroke_socket_create(), test_runner_init(), tkm_init(), tkm_spi_generator_register(), TNC_IMC_NotifyConnectionChange(), tnc_imv_manager_create(), tnc_manager_register(), tnc_pdp_create(), unbound_resolver_create(), unencrypted_notify_hook_create(), unsort_message_hook_create(), whitelist_control_create(), xauth_pam_listener_create(), and xauth_pam_plugin_create().
u_int32_t(* settings_t::get_time)(settings_t *this, char *key, u_int32_t def,...)
Get a time value.
Parameters
key key including sections, printf style format
def value returned if key not found
... argument list for key
Returns
value of the key (in seconds)
Definition at line 206 of file settings.h.
Referenced by ike_sa_create(), main(), medcli_config_create(), medsrv_config_create(), and send_start().
bool(* settings_t::load_files)(settings_t *this, char *pattern, bool merge)
Load settings from the files matching the given pattern.
If merge is TRUE, existing sections are extended, existing values replaced, by those found in the loaded files. If it is FALSE, existing sections are purged before reading the new config.
Note
If any of the files matching the pattern fails to load, no settings are added at all. So, it's all or nothing.
Parameters
pattern file pattern
merge TRUE to merge config with existing values
Returns
TRUE, if settings were loaded successfully
Definition at line 322 of file settings.h.
Referenced by CALLBACK(), load_configs(), run(), and START_TEST().
bool(* settings_t::load_files_section)(settings_t *this, char *pattern, bool merge, char *section,...)
Load settings from the files matching the given pattern.
If merge is TRUE, existing sections are extended, existing values replaced, by those found in the loaded files. If it is FALSE, existing sections are purged before reading the new config.
All settings are loaded relative to the given section. The section is created, if it does not yet exist.
Note
If any of the files matching the pattern fails to load, no settings are added at all. So, it's all or nothing.
Parameters
pattern file pattern
merge TRUE to merge config with existing values
section section name of parent section, printf style
... argument list for section
Returns
TRUE, if settings were loaded successfully
Definition at line 343 of file settings.h.
Referenced by START_TEST().
bool(* settings_t::load_string)(settings_t *this, char *settings, bool merge)
Load settings from the given string.
If merge is TRUE, existing sections are extended, existing values replaced, by those found in the string. If it is FALSE, existing sections are purged before reading the new config.
Note
If the string contains include statements they should be absolute paths.
If any failures occur, no settings are added at all. So, it's all or nothing.
Parameters
settings string to parse
merge TRUE to merge config with existing values
Returns
TRUE, if settings were loaded successfully
Definition at line 363 of file settings.h.
Referenced by START_TEST().
bool(* settings_t::load_string_section)(settings_t *this, char *settings, bool merge, char *section,...)
Load settings from the given string.
If merge is TRUE, existing sections are extended, existing values replaced, by those found in the string. If it is FALSE, existing sections are purged before reading the new config.
All settings are loaded relative to the given section. The section is created, if it does not yet exist.
Note
If the string contains include statements they should be absolute paths.
If any failures occur, no settings are added at all. So, it's all or nothing.
Parameters
settings string to parse
merge TRUE to merge config with existing values
section section name of parent section, printf style
... argument list for section
Returns
TRUE, if settings were loaded successfully
Definition at line 387 of file settings.h.
Referenced by START_TEST().
void(* settings_t::set_bool)(settings_t *this, char *key, bool value,...)
Set a boolean value.
Parameters
key key including sections, printf style format
value value to set
... argument list for key
Definition at line 224 of file settings.h.
Referenced by main(), and START_TEST().
bool(* settings_t::set_default_str)(settings_t *this, char *key, char *value,...)
Set a default for string value.
Parameters
key key including sections, printf style format
def value to set if unconfigured
... argument list for key
Returns
TRUE if a new default value for key has been set
Definition at line 261 of file settings.h.
Referenced by main(), pre_test(), and START_TEST().
void(* settings_t::set_double)(settings_t *this, char *key, double value,...)
Set an double value.
Parameters
key key including sections, printf style format
value value to set
... argument list for key
Definition at line 242 of file settings.h.
Referenced by START_TEST().
void(* settings_t::set_int)(settings_t *this, char *key, int value,...)
Set an integer value.
Parameters
key key including sections, printf style format
value value to set
... argument list for key
Definition at line 233 of file settings.h.
Referenced by main(), START_TEST(), and test_runner_init().
void(* settings_t::set_str)(settings_t *this, char *key, char *value,...)
Set a string value.
Parameters
key key including sections, printf style format
value value to set (gets cloned)
... argument list for key
Definition at line 215 of file settings.h.
Referenced by kernel_libipsec_plugin_create(), START_TEST(), and test_tls().
void(* settings_t::set_time)(settings_t *this, char *key, u_int32_t value,...)
Set a time value.
Parameters
key key including sections, printf style format
def value to set
... argument list for key
Definition at line 251 of file settings.h.
Referenced by START_TEST().
The documentation for this struct was generated from the following file:
settings.h