strongSwan: psk_authenticator
psk_authenticator
authenticators
Classes
struct psk_authenticator_t
Typedefs
typedef struct psk_authenticator_t psk_authenticator_t
Functions
psk_authenticator_t * psk_authenticator_create_builder (ike_sa_t *ike_sa, chunk_t received_nonce, chunk_t sent_init, char reserved[3])
psk_authenticator_t * psk_authenticator_create_verifier (ike_sa_t *ike_sa, chunk_t sent_nonce, chunk_t received_init, char reserved[3])
Detailed Description
Typedef Documentation
typedef struct psk_authenticator_t psk_authenticator_t
Definition at line 24 of file psk_authenticator.h.
Function Documentation
psk_authenticator_t* psk_authenticator_create_builder (ike_sa_t * ike_sa, chunk_t received_nonce, chunk_t sent_init, char reserved[3])
Create an authenticator to build PSK signatures.
Parameters
ike_sa associated ike_sa
received_nonce nonce received in IKE_SA_INIT
sent_init sent IKE_SA_INIT message data
reserved reserved bytes of ID payload
Returns
PSK authenticator
Definition at line 162 of file psk_authenticator.c.
References INIT, memcpy, return_failed(), and return_false().
 {
     private_psk_authenticator_t *this;
     INIT(this,
         .public = {
             .authenticator = {
                 .build = _build,
                 .process = (void*)return_failed,
                 .is_mutual = (void*)return_false,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .ike_sa_init = sent_init,
         .nonce = received_nonce,
     );
     memcpy(this->reserved, reserved, sizeof(this->reserved));
     return &this->public;
 }
psk_authenticator_t* psk_authenticator_create_verifier (ike_sa_t * ike_sa, chunk_t sent_nonce, chunk_t received_init, char reserved[3])
Create an authenticator to verify PSK signatures.
Parameters
ike_sa associated ike_sa
sent_nonce nonce sent in IKE_SA_INIT
received_init received IKE_SA_INIT message data
reserved reserved bytes of ID payload
Returns
PSK authenticator
Definition at line 189 of file psk_authenticator.c.
References INIT, memcpy, process(), return_failed(), and return_false().
 {
     private_psk_authenticator_t *this;
     INIT(this,
         .public = {
             .authenticator = {
                 .build = (void*)return_failed,
                 .process = _process,
                 .is_mutual = (void*)return_false,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .ike_sa_init = received_init,
         .nonce = sent_nonce,
     );
     memcpy(this->reserved, reserved, sizeof(this->reserved));
     return &this->public;
 }