strongSwan: crypto_factory
crypto_factory
crypto
Classes
struct crypto_factory_t
Macros
#define CRYPTO_MAX_ALG_LINE 120 /* characters */
Typedefs
typedef struct crypto_factory_t crypto_factory_t
typedef crypter_t *(* crypter_constructor_t)(encryption_algorithm_t algo, size_t key_size)
typedef aead_t *(* aead_constructor_t)(encryption_algorithm_t algo, size_t key_size, size_t salt_size)
typedef signer_t *(* signer_constructor_t)(integrity_algorithm_t algo)
typedef hasher_t *(* hasher_constructor_t)(hash_algorithm_t algo)
typedef prf_t *(* prf_constructor_t)(pseudo_random_function_t algo)
typedef rng_t *(* rng_constructor_t)(rng_quality_t quality)
typedef nonce_gen_t *(* nonce_gen_constructor_t)()
typedef diffie_hellman_t *(* dh_constructor_t)(diffie_hellman_group_t group,...)
Functions
crypto_factory_t * crypto_factory_create ()
Detailed Description
Macro Definition Documentation
#define CRYPTO_MAX_ALG_LINE 120 /* characters */
Definition at line 38 of file crypto_factory.h.
Referenced by print_alg().
Typedef Documentation
typedef aead_t*(* aead_constructor_t)(encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Constructor function for aead transforms
Definition at line 48 of file crypto_factory.h.
typedef crypter_t*(* crypter_constructor_t)(encryption_algorithm_t algo, size_t key_size)
Constructor function for crypters
Definition at line 43 of file crypto_factory.h.
typedef struct crypto_factory_t crypto_factory_t
Definition at line 24 of file crypto_factory.h.
typedef diffie_hellman_t*(* dh_constructor_t)(diffie_hellman_group_t group,...)
Constructor function for diffie hellman
The DH constructor accepts additional arguments for:
MODP_CUSTOM: chunk_t generator, chunk_t prime
Definition at line 81 of file crypto_factory.h.
typedef hasher_t*(* hasher_constructor_t)(hash_algorithm_t algo)
Constructor function for hashers
Definition at line 58 of file crypto_factory.h.
typedef nonce_gen_t*(* nonce_gen_constructor_t)()
Constructor function for nonce generators
Definition at line 73 of file crypto_factory.h.
typedef prf_t*(* prf_constructor_t)(pseudo_random_function_t algo)
Constructor function for pseudo random functions
Definition at line 63 of file crypto_factory.h.
typedef rng_t*(* rng_constructor_t)(rng_quality_t quality)
Constructor function for source of randomness
Definition at line 68 of file crypto_factory.h.
typedef signer_t*(* signer_constructor_t)(integrity_algorithm_t algo)
Constructor function for signers
Definition at line 53 of file crypto_factory.h.
Function Documentation
crypto_factory_t* crypto_factory_create ()
Create a crypto_factory instance.
Definition at line 1050 of file crypto_factory.c.
References crypto_tester_create(), FALSE, settings_t::get_bool, INIT, lib, linked_list_create(), library_t::ns, rwlock_create(), RWLOCK_TYPE_DEFAULT, and library_t::settings.
Referenced by library_init(), and START_TEST().
 {
     private_crypto_factory_t *this;
     INIT(this,
         .public = {
             .create_crypter = _create_crypter,
             .create_aead = _create_aead,
             .create_signer = _create_signer,
             .create_hasher = _create_hasher,
             .create_prf = _create_prf,
             .create_rng = _create_rng,
             .create_nonce_gen = _create_nonce_gen,
             .create_dh = _create_dh,
             .add_crypter = _add_crypter,
             .remove_crypter = _remove_crypter,
             .add_aead = _add_aead,
             .remove_aead = _remove_aead,
             .add_signer = _add_signer,
             .remove_signer = _remove_signer,
             .add_hasher = _add_hasher,
             .remove_hasher = _remove_hasher,
             .add_prf = _add_prf,
             .remove_prf = _remove_prf,
             .add_rng = _add_rng,
             .remove_rng = _remove_rng,
             .add_nonce_gen = _add_nonce_gen,
             .remove_nonce_gen = _remove_nonce_gen,
             .add_dh = _add_dh,
             .remove_dh = _remove_dh,
             .create_crypter_enumerator = _create_crypter_enumerator,
             .create_aead_enumerator = _create_aead_enumerator,
             .create_signer_enumerator = _create_signer_enumerator,
             .create_hasher_enumerator = _create_hasher_enumerator,
             .create_prf_enumerator = _create_prf_enumerator,
             .create_dh_enumerator = _create_dh_enumerator,
             .create_rng_enumerator = _create_rng_enumerator,
             .create_nonce_gen_enumerator = _create_nonce_gen_enumerator,
             .add_test_vector = _add_test_vector,
             .create_verify_enumerator = _create_verify_enumerator,
             .destroy = _destroy,
         },
         .crypters = linked_list_create(),
         .aeads = linked_list_create(),
         .signers = linked_list_create(),
         .hashers = linked_list_create(),
         .prfs = linked_list_create(),
         .rngs = linked_list_create(),
         .nonce_gens = linked_list_create(),
         .dhs = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .tester = crypto_tester_create(),
         .test_on_add = lib->settings->get_bool(lib->settings,
                                 "%s.crypto_test.on_add", FALSE, lib->ns),
         .test_on_create = lib->settings->get_bool(lib->settings,
                                 "%s.crypto_test.on_create", FALSE, lib->ns),
         .bench = lib->settings->get_bool(lib->settings,
                                 "%s.crypto_test.bench", FALSE, lib->ns),
     );
     return &this->public;
 }