strongSwan: pkcs7_enveloped_data
pkcs7_enveloped_data
pkcs7
Functions
pkcs7_t * pkcs7_enveloped_data_load (chunk_t encoding, chunk_t content)
pkcs7_t * pkcs7_enveloped_data_gen (container_type_t type, va_list args)
Detailed Description
Function Documentation
pkcs7_t* pkcs7_enveloped_data_gen (container_type_t type, va_list args)
Generate a PKCS#7 enveloped-data container.
Parameters
type container type, must be CONTAINER_PKCS7_ENVELOPED_DATA
args builder_t arguments to use.
See header.
Definition at line 570 of file pkcs7_enveloped_data.c.
References alg, blob, BUILD_BLOB, BUILD_CERT, BUILD_ENCRYPTION_ALG, BUILD_END, BUILD_KEY_SIZE, cert, chunk_clone, chunk_empty, create_empty(), destroy(), ENCR_AES_CBC, generate(), key_size, chunk_t::len, and TRUE.
Referenced by METHOD().
 {
     private_pkcs7_enveloped_data_t *this;
     chunk_t blob = chunk_empty;
     encryption_algorithm_t alg = ENCR_AES_CBC;
     certificate_t *cert = NULL;
     int key_size = 128;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_CERT:
                 cert = va_arg(args, certificate_t*);
                 continue;
             case BUILD_ENCRYPTION_ALG:
                 alg = va_arg(args, int);
                 continue;
             case BUILD_KEY_SIZE:
                 key_size = va_arg(args, int);
                 continue;
             case BUILD_BLOB:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.len && cert)
     {
         this = create_empty();
         this->content = chunk_clone(blob);
         if (generate(this, cert, alg, key_size))
         {
             return &this->public;
         }
         destroy(this);
     }
     return NULL;
 }
pkcs7_t* pkcs7_enveloped_data_load (chunk_t encoding, chunk_t content)
Parse a PKCS#7 enveloped-data container.
Parameters
encoding full contentInfo encoding
content DER encoded content from contentInfo
Returns
CONTAINER_PKCS7_ENVELOPED_DATA container, NULL on failure
See header.
Definition at line 394 of file pkcs7_enveloped_data.c.
References chunk_clone, create_empty(), destroy(), and parse().
Referenced by parse_contentInfo().
 {
     private_pkcs7_enveloped_data_t *this = create_empty();
     this->encoding = chunk_clone(encoding);
     if (!parse(this, content))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }