strongSwan: load_all.c File Reference
load_all.c File Reference
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <sys/stat.h>
#include "command.h"
#include "swanctl.h"
#include "load_creds.h"
#include "load_authorities.h"
#include "load_pools.h"
#include "load_conns.h"
Macros
#define _GNU_SOURCE
Functions
static int load_all (vici_conn_t *conn)
static void __attribute__ ((constructor))
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file load_all.c.
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 95 of file load_all.c.
References command_register(), and load_all().
 {
     command_register((command_t) {
         load_all, 'q', "load-all",
         "load credentials, authorities, pools and connections",
         {"[--raw|--pretty] [--clear] [--noprompt]"},
         {
             {"help",        'h', 0, "show usage information"},
             {"clear",       'c', 0, "clear previously loaded credentials"},
             {"noprompt",    'n', 0, "do not prompt for passwords"},
             {"raw",         'r', 0, "dump raw response message"},
             {"pretty",      'P', 0, "dump raw response message in pretty print"},
         }
     });
 }
static int load_all (vici_conn_t * conn) static
Definition at line 29 of file load_all.c.
References COMMAND_FORMAT_NONE, COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, command_getopt(), command_usage(), settings_t::destroy, FALSE, fprintf, load_authorities_cfg(), load_conns_cfg(), load_creds_cfg(), load_pools_cfg(), settings_create(), SWANCTL_CONF, and TRUE.
Referenced by __attribute__().
 {
     bool clear = FALSE, noprompt = FALSE;
     command_format_options_t format = COMMAND_FORMAT_NONE;
     settings_t *cfg;
     int ret = 0;
     char *arg;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 'c':
                 clear = TRUE;
                 continue;
             case 'n':
                 noprompt = TRUE;
                 continue;
             case 'P':
                 format |= COMMAND_FORMAT_PRETTY;
                 /* fall through to raw */
             case 'r':
                 format |= COMMAND_FORMAT_RAW;
                 continue;
             case EOF:
                 break;
             default:
                 return command_usage("invalid --load-all option");
         }
         break;
     }
     cfg = settings_create(SWANCTL_CONF);
     if (!cfg)
     {
         fprintf(stderr, "parsing '%s' failed\n", SWANCTL_CONF);
         return EINVAL;
     }
     if (ret == 0)
     {
         ret = load_creds_cfg(conn, format, cfg, clear, noprompt);
     }
     if (ret == 0)
     {
         ret = load_authorities_cfg(conn, format, cfg);
     }
     if (ret == 0)
     {
         ret = load_pools_cfg(conn, format, cfg);
     }
     if (ret == 0)
     {
         ret = load_conns_cfg(conn, format, cfg);
     }
     cfg->destroy(cfg);
     return ret;
 }