strongSwan: pb_tnc_msg_t Struct Reference
pb_tnc_msg_t Struct Reference
pb_tnc_msg
#include "pb_tnc_msg.h"
Public Attributes
pen_type_t(* get_type)(pb_tnc_msg_t *this)
chunk_t(* get_encoding)(pb_tnc_msg_t *this)
void(* build)(pb_tnc_msg_t *this)
status_t(* process)(pb_tnc_msg_t *this, u_int32_t *offset)
pb_tnc_msg_t *(* get_ref)(pb_tnc_msg_t *this)
void(* destroy)(pb_tnc_msg_t *this)
Detailed Description
Generic interface for all PB-TNC message types.
To handle all messages in a generic way, this interface must be implemented by each message type.
Definition at line 114 of file pb_tnc_msg.h.
Member Data Documentation
void(* pb_tnc_msg_t::build)(pb_tnc_msg_t *this)
Build the PB-TNC Message Value
Definition at line 133 of file pb_tnc_msg.h.
Referenced by METHOD().
void(* pb_tnc_msg_t::destroy)(pb_tnc_msg_t *this)
Destroys a pb_tnc_msg_t object.
Definition at line 153 of file pb_tnc_msg.h.
Referenced by change_batch_type(), METHOD(), and process_tnc_msg().
chunk_t(* pb_tnc_msg_t::get_encoding)(pb_tnc_msg_t *this)
Get the encoding of the PB-TNC Message Value
Returns
encoded PB-TNC Message Value
Definition at line 128 of file pb_tnc_msg.h.
Referenced by METHOD().
pb_tnc_msg_t*(* pb_tnc_msg_t::get_ref)(pb_tnc_msg_t *this)
Get a new reference to the message.
Returns
this, with an increased refcount
Definition at line 148 of file pb_tnc_msg.h.
Referenced by METHOD().
pen_type_t(* pb_tnc_msg_t::get_type)(pb_tnc_msg_t *this)
Get the PB-TNC Message Type
Returns
PB-TNC Message Type
Definition at line 121 of file pb_tnc_msg.h.
Referenced by handle_ietf_message(), handle_ita_message(), handle_message(), handle_tcg_message(), and METHOD().
status_t(* pb_tnc_msg_t::process)(pb_tnc_msg_t *this, u_int32_t *offset)
Process the PB-TNC Message Value
Parameters
relative offset where an error occurred
Returns
return processing status
Definition at line 141 of file pb_tnc_msg.h.
Referenced by process_tnc_msg().
The documentation for this struct was generated from the following file:
pb_tnc_msg.h