strongSwan: ita_comp_tgrub.c File Reference
ita_comp_tgrub.c File Reference
#include "ita_comp_tgrub.h"
#include "ita_comp_func_name.h"
#include "pts/components/pts_component.h"
#include <utils/debug.h>
#include <pen/pen.h>
Classes
struct pts_ita_comp_tgrub_t
Typedefs
typedef struct pts_ita_comp_tgrub_t pts_ita_comp_tgrub_t
Functions
METHOD (pts_component_t, get_comp_func_name, pts_comp_func_name_t *, pts_ita_comp_tgrub_t *this)
METHOD (pts_component_t, get_evidence_flags, u_int8_t, pts_ita_comp_tgrub_t *this)
METHOD (pts_component_t, get_depth, u_int32_t, pts_ita_comp_tgrub_t *this)
METHOD (pts_component_t, measure, status_t, pts_ita_comp_tgrub_t *this, u_int8_t qualifier, pts_t *pts, pts_comp_evidence_t **evidence)
METHOD (pts_component_t, verify, status_t, pts_ita_comp_tgrub_t *this, u_int8_t qualifier, pts_t *pts, pts_comp_evidence_t *evidence)
METHOD (pts_component_t, finalize, bool, pts_ita_comp_tgrub_t *this, u_int8_t qualifier, bio_writer_t *result)
METHOD (pts_component_t, get_ref, pts_component_t *, pts_ita_comp_tgrub_t *this)
METHOD (pts_component_t, destroy, void, pts_ita_comp_tgrub_t *this)
pts_component_t * pts_ita_comp_tgrub_create (u_int32_t depth, pts_database_t *pts_db)
Typedef Documentation
typedef struct pts_ita_comp_tgrub_t pts_ita_comp_tgrub_t
Definition at line 24 of file ita_comp_tgrub.c.
Function Documentation
METHOD (pts_component_t , get_comp_func_name , pts_comp_func_name_t * , pts_ita_comp_tgrub_t * this)
Definition at line 59 of file ita_comp_tgrub.c.
References name.
 {
     return this->name;
 }
METHOD (pts_component_t , get_evidence_flags , u_int8_t , pts_ita_comp_tgrub_t * this)
Definition at line 65 of file ita_comp_tgrub.c.
References PTS_REQ_FUNC_COMP_EVID_PCR.
 {
     return PTS_REQ_FUNC_COMP_EVID_PCR;
 }
METHOD (pts_component_t , get_depth , u_int32_t , pts_ita_comp_tgrub_t * this)
Definition at line 71 of file ita_comp_tgrub.c.
 {
     return this->depth;
 }
METHOD (pts_component_t , measure , status_t , pts_ita_comp_tgrub_t * this, u_int8_t qualifier, pts_t * pts, pts_comp_evidence_t ** evidence)
Definition at line 77 of file ita_comp_tgrub.c.
References chunk_alloc, DBG1, DBG_PTS, FAILED, HASH_SIZE_SHA1, chunk_t::len, memset, name, PCR_DEBUG, chunk_t::ptr, pts_comp_evidence_create(), PTS_MEAS_ALGO_SHA1, pts_meas_algo_to_pcr_transform(), pts_t::read_pcr, pts_comp_evidence_t::set_pcr_info, and SUCCESS.
 {
     size_t pcr_len;
     pts_pcr_transform_t pcr_transform;
     pts_meas_algorithms_t hash_algo;
     pts_comp_evidence_t *evid;
     u_int32_t extended_pcr;
     time_t measurement_time;
     chunk_t measurement, pcr_before, pcr_after;
     /* Provisional implementation for TGRUB */
     extended_pcr = PCR_DEBUG;
     time(&measurement_time);
     if (!pts->read_pcr(pts, extended_pcr, &pcr_after))
     {
         DBG1(DBG_PTS, "error occurred while reading PCR: %d", extended_pcr);
         return FAILED;
     }
     hash_algo = PTS_MEAS_ALGO_SHA1;
     pcr_len = HASH_SIZE_SHA1;
     pcr_transform = pts_meas_algo_to_pcr_transform(hash_algo, pcr_len);
     measurement = chunk_alloc(pcr_len);
     memset(measurement.ptr, 0x00, measurement.len);
     pcr_before = chunk_alloc(pcr_len);
     memset(pcr_before.ptr, 0x00, pcr_before.len);
     evid = *evidence = pts_comp_evidence_create(this->name->clone(this->name),
                                 this->depth, extended_pcr,
                                 hash_algo, pcr_transform,
                                 measurement_time, measurement);
     evid->set_pcr_info(evid, pcr_before, pcr_after);
     return SUCCESS;
 }
METHOD (pts_component_t , verify , status_t , pts_ita_comp_tgrub_t * this, u_int8_t qualifier, pts_t * pts, pts_comp_evidence_t * evidence)
Definition at line 118 of file ita_comp_tgrub.c.
References __attribute__, chunk_equals_const(), DBG1, DBG_PTS, FAILED, pts_pcr_t::get, pts_comp_evidence_t::get_measurement, pts_comp_evidence_t::get_pcr_info, pts_t::get_pcrs, PCR_DEBUG, pts_pcr_t::set, SUCCESS, and unused.
 {
     bool has_pcr_info;
     u_int32_t extended_pcr;
     pts_meas_algorithms_t algo;
     pts_pcr_transform_t transform;
     pts_pcr_t *pcrs;
     time_t measurement_time;
     chunk_t pcr_before, pcr_after;
     chunk_t measurement __attribute__((unused));
     pcrs = pts->get_pcrs(pts);
     measurement = evidence->get_measurement(evidence, &extended_pcr,
                                 &algo, &transform, &measurement_time);
     if (extended_pcr != PCR_DEBUG)
     {
         return FAILED;
     }
     /* TODO check measurement in database */
     has_pcr_info = evidence->get_pcr_info(evidence, &pcr_before, &pcr_after);
     if (has_pcr_info)
     {
         if (!chunk_equals_const(pcr_before, pcrs->get(pcrs, extended_pcr)))
         {
             DBG1(DBG_PTS, "PCR %2u: pcr_before is not equal to pcr value");
         }
         if (pcrs->set(pcrs, extended_pcr, pcr_after))
         {
             return SUCCESS;
         }
     }
     return SUCCESS;
 }
METHOD (pts_component_t , finalize , bool , pts_ita_comp_tgrub_t * this, u_int8_t qualifier, bio_writer_t * result)
Definition at line 157 of file ita_comp_tgrub.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (pts_component_t , get_ref , pts_component_t * , pts_ita_comp_tgrub_t * this)
Definition at line 163 of file ita_comp_tgrub.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (pts_component_t , destroy , void , pts_ita_comp_tgrub_t * this)
Definition at line 170 of file ita_comp_tgrub.c.
References free(), name, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         this->name->destroy(this->name);
         free(this);
     }
 }