strongSwan: eap_radius.c File Reference
eap_radius.c File Reference
#include "eap_radius.h"
#include "eap_radius_plugin.h"
#include "eap_radius_forward.h"
#include "eap_radius_provider.h"
#include "eap_radius_accounting.h"
#include <radius_message.h>
#include <radius_client.h>
#include <bio/bio_writer.h>
#include <daemon.h>
Classes
struct private_eap_radius_t
Typedefs
typedef struct private_eap_radius_t private_eap_radius_t
Functions
static void add_eap_identity (private_eap_radius_t *this, radius_message_t *request)
static bool radius2ike (private_eap_radius_t *this, radius_message_t *msg, eap_payload_t **out)
void eap_radius_build_attributes (radius_message_t *request)
static void add_radius_request_attrs (private_eap_radius_t *this, radius_message_t *request)
METHOD (eap_method_t, initiate, status_t, private_eap_radius_t *this, eap_payload_t **out)
static void process_class (radius_message_t *msg)
static void process_filter_id (radius_message_t *msg)
static void process_timeout (radius_message_t *msg)
static void add_unity_attribute (eap_radius_provider_t *provider, u_int32_t id, int type, chunk_t data)
static void add_nameserver_attribute (eap_radius_provider_t *provider, u_int32_t id, int type, chunk_t data)
static void add_unity_split_attribute (eap_radius_provider_t *provider, u_int32_t id, configuration_attribute_type_t type, chunk_t data)
static void process_cfg_attributes (radius_message_t *msg)
void eap_radius_process_attributes (radius_message_t *message)
METHOD (eap_method_t, process, status_t, private_eap_radius_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_radius_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_radius_t *this, chunk_t *out)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_radius_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_radius_t *this, u_int8_t identifier)
METHOD (eap_method_t, is_mutual, bool, private_eap_radius_t *this)
METHOD (eap_method_t, destroy, void, private_eap_radius_t *this)
eap_radius_t * eap_radius_create (identification_t *server, identification_t *peer)
Typedef Documentation
typedef struct private_eap_radius_t private_eap_radius_t
Definition at line 28 of file eap_radius.c.
Function Documentation
static void add_eap_identity (private_eap_radius_t * this, radius_message_t * request) static
Add EAP-Identity to RADIUS message
EAP code (REQUEST/RESPONSE)
unique message identifier
length of whole message
EAP type
identity data
Definition at line 84 of file eap_radius.c.
References __attribute__, radius_message_t::add, chunk_create(), code, data, EAP_IDENTITY, EAP_RESPONSE, id, identifier, chunk_t::len, len, length, memcpy, prefix, chunk_t::ptr, RAT_EAP_MESSAGE, and type.
Referenced by METHOD().
 {
     struct {
         u_int8_t code;
         u_int8_t identifier;
         u_int16_t length;
         u_int8_t type;
         u_int8_t data[];
     } __attribute__((__packed__)) *hdr;
     chunk_t id, prefix;
     size_t len;
     id = this->peer->get_encoding(this->peer);
     prefix = chunk_create(this->id_prefix, strlen(this->id_prefix));
     len = sizeof(*hdr) + prefix.len + id.len;
     hdr = alloca(len);
     hdr->code = EAP_RESPONSE;
     hdr->identifier = this->identifier;
     hdr->length = htons(len);
     hdr->type = EAP_IDENTITY;
     memcpy(hdr->data, prefix.ptr, prefix.len);
     memcpy(hdr->data + prefix.len, id.ptr, id.len);
     request->add(request, RAT_EAP_MESSAGE, chunk_create((u_char*)hdr, len));
 }
static void add_nameserver_attribute (eap_radius_provider_t * provider, u_int32_t id, int type, chunk_t data) static
Add a DNS/NBNS configuration attribute
Definition at line 419 of file eap_radius.c.
References eap_radius_provider_t::add_attribute, INTERNAL_IP4_DNS, INTERNAL_IP4_NBNS, INTERNAL_IP6_DNS, and RAT_FRAMED_IPV6_DNS_SERVER.
Referenced by process_cfg_attributes().
 {
     /* these are from different vendors, but there is currently no conflict */
     switch (type)
     {
         case  5: /* CVPN3000-Primary-DNS */
         case  6: /* CVPN3000-Secondary-DNS */
         case 28: /* MS-Primary-DNS-Server */
         case 29: /* MS-Secondary-DNS-Server */
             provider->add_attribute(provider, id, INTERNAL_IP4_DNS, data);
             break;
         case  7: /* CVPN3000-Primary-WINS */
         case  8: /* CVPN3000-Secondary-WINS */
         case 30: /* MS-Primary-NBNS-Server */
         case 31: /* MS-Secondary-NBNS-Server */
             provider->add_attribute(provider, id, INTERNAL_IP4_NBNS, data);
             break;
         case RAT_FRAMED_IPV6_DNS_SERVER:
             provider->add_attribute(provider, id, INTERNAL_IP6_DNS, data);
             break;
     }
 }
static void add_radius_request_attrs (private_eap_radius_t * this, radius_message_t * request) static
Add a set of RADIUS attributes to a request message
Definition at line 210 of file eap_radius.c.
References radius_message_t::add, chunk_cata, chunk_from_str, eap_radius_build_attributes(), eap_radius_forward_from_ike(), and RAT_USER_NAME.
Referenced by METHOD().
 {
     chunk_t chunk;
     chunk = chunk_from_str(this->id_prefix);
     chunk = chunk_cata("cc", chunk, this->peer->get_encoding(this->peer));
     request->add(request, RAT_USER_NAME, chunk);
     eap_radius_build_attributes(request);
     eap_radius_forward_from_ike(request);
 }
static void add_unity_attribute (eap_radius_provider_t * provider, u_int32_t id, int type, chunk_t data) static
Add a Cisco Unity configuration attribute
Definition at line 398 of file eap_radius.c.
References eap_radius_provider_t::add_attribute, UNITY_BANNER, UNITY_DEF_DOMAIN, and UNITY_SPLITDNS_NAME.
Referenced by process_cfg_attributes().
 {
     switch (type)
     {
         case 15: /* CVPN3000-IPSec-Banner1 */
         case 36: /* CVPN3000-IPSec-Banner2 */
             provider->add_attribute(provider, id, UNITY_BANNER, data);
             break;
         case 28: /* CVPN3000-IPSec-Default-Domain */
             provider->add_attribute(provider, id, UNITY_DEF_DOMAIN, data);
             break;
         case 29: /* CVPN3000-IPSec-Split-DNS-Names */
             provider->add_attribute(provider, id, UNITY_SPLITDNS_NAME, data);
             break;
     }
 }
static void add_unity_split_attribute (eap_radius_provider_t * provider, u_int32_t id, configuration_attribute_type_t type, chunk_t data) static
Add a UNITY_LOCAL_LAN or UNITY_SPLIT_INCLUDE attribute
Definition at line 446 of file eap_radius.c.
References eap_radius_provider_t::add_attribute, bio_writer_create(), enumerator_t::destroy, host_t::destroy, bio_writer_t::destroy, DESTROY_IF, enumerator_t::enumerate, enumerator_create_token(), host_t::get_address, bio_writer_t::get_buf, host_t::get_family, host_create_from_string(), chunk_t::len, mask, memset, net, padding, chunk_t::ptr, bio_writer_t::skip, snprintf, and bio_writer_t::write_data.
Referenced by process_cfg_attributes().
 {
     enumerator_t *enumerator;
     bio_writer_t *writer;
     char buffer[256], *token, *slash;
     if (snprintf(buffer, sizeof(buffer), "%.*s", (int)data.len,
                  data.ptr) >= sizeof(buffer))
     {
         return;
     }
     writer = bio_writer_create(16); /* two IPv4 addresses and 6 bytes padding */
     enumerator = enumerator_create_token(buffer, ",", " ");
     while (enumerator->enumerate(enumerator, &token))
     {
         host_t *net, *mask = NULL;
         chunk_t padding;
         slash = strchr(token, '/');
         if (slash)
         {
             *slash++ = '\0';
             mask = host_create_from_string(slash, 0);
         }
         if (!mask)
         {   /* default to /32 */
             mask = host_create_from_string("255.255.255.255", 0);
         }
         net = host_create_from_string(token, 0);
         if (!net || net->get_family(net) != AF_INET ||
              mask->get_family(mask) != AF_INET)
         {
             mask->destroy(mask);
             DESTROY_IF(net);
             continue;
         }
         writer->write_data(writer, net->get_address(net));
         writer->write_data(writer, mask->get_address(mask));
         padding = writer->skip(writer, 6); /* 6 bytes pdding */
         memset(padding.ptr, 0, padding.len);
         mask->destroy(mask);
         net->destroy(net);
     }
     enumerator->destroy(enumerator);
     data = writer->get_buf(writer);
     if (data.len)
     {
         provider->add_attribute(provider, id, type, data);
     }
     writer->destroy(writer);
 }
METHOD (eap_method_t , initiate , status_t , private_eap_radius_t * this, eap_payload_t ** out)
Definition at line 223 of file eap_radius.c.
References radius_message_t::add, add_eap_identity(), add_radius_request_attrs(), chunk_empty, client(), DBG1, DBG_IKE, radius_message_t::destroy, eap_radius_forward_to_ike(), eap_radius_handle_timeout(), FAILED, radius_message_t::get_code, NEED_MORE, radius2ike(), radius_message_create(), RAT_EAP_MESSAGE, request(), response, RMC_ACCESS_ACCEPT, RMC_ACCESS_CHALLENGE, RMC_ACCESS_REJECT, RMC_ACCESS_REQUEST, and status.
 {
     radius_message_t *request, *response;
     status_t status = FAILED;
     request = radius_message_create(RMC_ACCESS_REQUEST);
     add_radius_request_attrs(this, request);
     if (this->eap_start)
     {
         request->add(request, RAT_EAP_MESSAGE, chunk_empty);
     }
     else
     {
         add_eap_identity(this, request);
     }
     response = this->client->request(this->client, request);
     if (response)
     {
         eap_radius_forward_to_ike(response);
         switch (response->get_code(response))
         {
             case RMC_ACCESS_CHALLENGE:
                 if (radius2ike(this, response, out))
                 {
                     status = NEED_MORE;
                 }
                 break;
             case RMC_ACCESS_ACCEPT:
                 /* Microsoft RADIUS servers can run in a mode where they respond
                  * like this on the first request (i.e. without authentication),
                  * we treat this as Access-Reject */
             case RMC_ACCESS_REJECT:
             default:
                 DBG1(DBG_IKE, "RADIUS authentication of '%Y' failed",
                      this->peer);
                 break;
         }
         response->destroy(response);
     }
     else
     {
         eap_radius_handle_timeout(NULL);
     }
     request->destroy(request);
     return status;
 }
METHOD (eap_method_t , process , status_t , private_eap_radius_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 648 of file eap_radius.c.
References radius_message_t::add, add_radius_request_attrs(), chunk_create(), chunk_skip(), client(), data, DBG1, DBG3, DBG_IKE, radius_message_t::destroy, eap_radius_forward_to_ike(), eap_radius_process_attributes(), eap_type_names, FAILED, radius_message_t::get_code, eap_payload_t::get_data, chunk_t::len, MAX_RADIUS_ATTRIBUTE_SIZE, NEED_MORE, chunk_t::ptr, radius2ike(), radius_message_create(), RAT_EAP_MESSAGE, request(), response, RMC_ACCESS_ACCEPT, RMC_ACCESS_CHALLENGE, RMC_ACCESS_REJECT, RMC_ACCESS_REQUEST, status, SUCCESS, and type.
 {
     radius_message_t *request, *response;
     status_t status = FAILED;
     chunk_t data;
     request = radius_message_create(RMC_ACCESS_REQUEST);
     add_radius_request_attrs(this, request);
     data = in->get_data(in);
     DBG3(DBG_IKE, "%N payload %B", eap_type_names, this->type, &data);
     /* fragment data suitable for RADIUS */
     while (data.len > MAX_RADIUS_ATTRIBUTE_SIZE)
     {
         request->add(request, RAT_EAP_MESSAGE,
                      chunk_create(data.ptr,MAX_RADIUS_ATTRIBUTE_SIZE));
         data = chunk_skip(data, MAX_RADIUS_ATTRIBUTE_SIZE);
     }
     request->add(request, RAT_EAP_MESSAGE, data);
     response = this->client->request(this->client, request);
     if (response)
     {
         eap_radius_forward_to_ike(response);
         switch (response->get_code(response))
         {
             case RMC_ACCESS_CHALLENGE:
                 if (radius2ike(this, response, out))
                 {
                     status = NEED_MORE;
                     break;
                 }
                 status = FAILED;
                 break;
             case RMC_ACCESS_ACCEPT:
                 eap_radius_process_attributes(response);
                 DBG1(DBG_IKE, "RADIUS authentication of '%Y' successful",
                      this->peer);
                 status = SUCCESS;
                 break;
             case RMC_ACCESS_REJECT:
             default:
                 DBG1(DBG_IKE, "RADIUS authentication of '%Y' failed",
                      this->peer);
                 status = FAILED;
                 break;
         }
         response->destroy(response);
     }
     request->destroy(request);
     return status;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_radius_t * this, u_int32_t * vendor)
Definition at line 703 of file eap_radius.c.
References type.
 {
     *vendor = this->vendor;
     return this->type;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_radius_t * this, chunk_t * out)
Definition at line 710 of file eap_radius.c.
References client(), FAILED, chunk_t::len, and SUCCESS.
 {
     chunk_t msk;
     msk = this->client->get_msk(this->client);
     if (msk.len)
     {
         *out = msk;
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_radius_t * this)
Definition at line 724 of file eap_radius.c.
References identifier.
 {
     return this->identifier;
 }
METHOD (eap_method_t , set_identifier , void , private_eap_radius_t * this, u_int8_t identifier)
Definition at line 730 of file eap_radius.c.
References identifier.
 {
     this->identifier = identifier;
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_radius_t * this)
Definition at line 736 of file eap_radius.c.
References EAP_AKA, EAP_SIM, FALSE, TRUE, and type.
 {
     switch (this->type)
     {
         case EAP_AKA:
         case EAP_SIM:
             return TRUE;
         default:
             return FALSE;
     }
 }
METHOD (eap_method_t , destroy , void , private_eap_radius_t * this)
Definition at line 749 of file eap_radius.c.
References client(), free(), and server.
 {
     this->peer->destroy(this->peer);
     this->server->destroy(this->server);
     this->client->destroy(this->client);
     free(this);
 }
static void process_cfg_attributes (radius_message_t * msg) static
Handle Framed-IP-Address and other IKE configuration attributes
Definition at line 504 of file eap_radius.c.
References eap_radius_provider_t::add_attribute, eap_radius_provider_t::add_framed_ip, add_nameserver_attribute(), add_unity_attribute(), add_unity_split_attribute(), daemon_t::bus, charon, radius_message_t::create_enumerator, radius_message_t::create_vendor_enumerator, data, enumerator_t::destroy, eap_radius_provider_get(), enumerator_t::enumerate, EXT_CISCO_UNITY, bus_t::get_sa, ike_sa_t::get_unique_id, host, host_create_from_chunk(), INTERNAL_IP4_NETMASK, chunk_t::len, PEN_ALTIGA, PEN_MICROSOFT, chunk_t::ptr, RAT_FRAMED_IP_ADDRESS, RAT_FRAMED_IP_NETMASK, RAT_FRAMED_IPV6_ADDRESS, RAT_FRAMED_IPV6_DNS_SERVER, ike_sa_t::supports_extension, type, UNITY_LOCAL_LAN, and UNITY_SPLIT_INCLUDE.
Referenced by eap_radius_process_attributes().
 {
     eap_radius_provider_t *provider;
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     host_t *host;
     chunk_t data;
     configuration_attribute_type_t split_type = 0;
     int type, vendor;
     ike_sa = charon->bus->get_sa(charon->bus);
     provider = eap_radius_provider_get();
     if (provider && ike_sa)
     {
         enumerator = msg->create_enumerator(msg);
         while (enumerator->enumerate(enumerator, &type, &data))
         {
             if ((type == RAT_FRAMED_IP_ADDRESS && data.len == 4) ||
                 (type == RAT_FRAMED_IPV6_ADDRESS && data.len == 16))
             {
                 host = host_create_from_chunk(AF_UNSPEC, data, 0);
                 if (host)
                 {
                     provider->add_framed_ip(provider,
                                     ike_sa->get_unique_id(ike_sa), host);
                 }
             }
             else if (type == RAT_FRAMED_IP_NETMASK && data.len == 4)
             {
                 provider->add_attribute(provider, ike_sa->get_unique_id(ike_sa),
                                         INTERNAL_IP4_NETMASK, data);
             }
             else if (type == RAT_FRAMED_IPV6_DNS_SERVER && data.len == 16)
             {
                 add_nameserver_attribute(provider,
                                     ike_sa->get_unique_id(ike_sa), type, data);
             }
         }
         enumerator->destroy(enumerator);
         enumerator = msg->create_vendor_enumerator(msg);
         while (enumerator->enumerate(enumerator, &vendor, &type, &data))
         {
             if (vendor == PEN_ALTIGA /* aka Cisco VPN3000 */)
             {
                 switch (type)
                 {
                     case  5: /* CVPN3000-Primary-DNS */
                     case  6: /* CVPN3000-Secondary-DNS */
                     case  7: /* CVPN3000-Primary-WINS */
                     case  8: /* CVPN3000-Secondary-WINS */
                         if (data.len == 4)
{
                             add_nameserver_attribute(provider,
                                     ike_sa->get_unique_id(ike_sa), type, data);
                         }
                         break;
                     case 15: /* CVPN3000-IPSec-Banner1 */
                     case 28: /* CVPN3000-IPSec-Default-Domain */
                     case 29: /* CVPN3000-IPSec-Split-DNS-Names */
                     case 36: /* CVPN3000-IPSec-Banner2 */
                         if (ike_sa->supports_extension(ike_sa, EXT_CISCO_UNITY))
{
                             add_unity_attribute(provider,
                                     ike_sa->get_unique_id(ike_sa), type, data);
                         }
                         break;
                     case 55: /* CVPN3000-IPSec-Split-Tunneling-Policy */
                         if (data.len)
{
                             switch (data.ptr[data.len - 1])
{
                                 case 0: /* tunnelall */
                                 default:
                                     break;
                                 case 1: /* tunnelspecified */
                                     split_type = UNITY_SPLIT_INCLUDE;
                                     break;
                                 case 2: /* excludespecified */
                                     split_type = UNITY_LOCAL_LAN;
                                     break;
                             }
                         }
                         break;
                     default:
                         break;
                 }
             }
             if (vendor == PEN_MICROSOFT)
             {
                 switch (type)
                 {
                     case 28: /* MS-Primary-DNS-Server */
                     case 29: /* MS-Secondary-DNS-Server */
                     case 30: /* MS-Primary-NBNS-Server */
                     case 31: /* MS-Secondary-NBNS-Server */
                         if (data.len == 4)
{
                             add_nameserver_attribute(provider,
                                     ike_sa->get_unique_id(ike_sa), type, data);
                         }
                         break;
                 }
             }
         }
         enumerator->destroy(enumerator);
         if (split_type != 0 &&
             ike_sa->supports_extension(ike_sa, EXT_CISCO_UNITY))
         {
             enumerator = msg->create_vendor_enumerator(msg);
             while (enumerator->enumerate(enumerator, &vendor, &type, &data))
             {
                 if (vendor == PEN_ALTIGA /* aka Cisco VPN3000 */ &&
                     type == 27 /* CVPN3000-IPSec-Split-Tunnel-List */)
                 {
                     add_unity_split_attribute(provider,
                             ike_sa->get_unique_id(ike_sa), split_type, data);
                 }
             }
             enumerator->destroy(enumerator);
         }
     }
 }
static void process_class (radius_message_t * msg) static
Handle the Class attribute as group membership information
Definition at line 276 of file eap_radius.c.
References auth_cfg_t::add, AUTH_RULE_GROUP, daemon_t::bus, charon, radius_message_t::create_enumerator, data, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, ike_sa_t::get_auth_cfg, bus_t::get_sa, id, identification_create_from_data(), chunk_t::len, RAT_CLASS, and type.
Referenced by eap_radius_process_attributes().
 {
     enumerator_t *enumerator;
     chunk_t data;
     int type;
     enumerator = msg->create_enumerator(msg);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (type == RAT_CLASS)
         {
             identification_t *id;
             ike_sa_t *ike_sa;
             auth_cfg_t *auth;
             if (data.len >= 44)
             {   /* quirk: ignore long class attributes, these are used for
                  * other purposes by some RADIUS servers (such as NPS). */
                 continue;
             }
             ike_sa = charon->bus->get_sa(charon->bus);
             if (ike_sa)
             {
                 auth = ike_sa->get_auth_cfg(ike_sa, FALSE);
                 id = identification_create_from_data(data);
                 DBG1(DBG_CFG, "received group membership '%Y' from RADIUS", id);
                 auth->add(auth, AUTH_RULE_GROUP, id);
             }
         }
     }
     enumerator->destroy(enumerator);
 }
static void process_filter_id (radius_message_t * msg) static
Handle the Filter-Id attribute as IPsec CHILD_SA name
Definition at line 313 of file eap_radius.c.
References auth_cfg_t::add, AUTH_RULE_GROUP, daemon_t::bus, charon, chunk_empty, radius_message_t::create_enumerator, data, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, ike_sa_t::get_auth_cfg, bus_t::get_sa, id, identification_create_from_data(), chunk_t::len, chunk_t::ptr, RADIUS_TUNNEL_TYPE_ESP, RAT_FILTER_ID, RAT_TUNNEL_TYPE, type, and untoh32().
Referenced by eap_radius_process_attributes().
 {
     enumerator_t *enumerator;
     int type;
     u_int8_t tunnel_tag;
     u_int32_t tunnel_type;
     chunk_t filter_id = chunk_empty, data;
     bool is_esp_tunnel = FALSE;
     enumerator = msg->create_enumerator(msg);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         switch (type)
         {
             case RAT_TUNNEL_TYPE:
                 if (data.len != 4)
                 {
                     continue;
                 }
                 tunnel_tag = *data.ptr;
                 *data.ptr = 0x00;
                 tunnel_type = untoh32(data.ptr);
                 DBG1(DBG_IKE, "received RADIUS attribute Tunnel-Type: "
                               "tag = %u, value = %u", tunnel_tag, tunnel_type);
                 is_esp_tunnel = (tunnel_type == RADIUS_TUNNEL_TYPE_ESP);
                 break;
             case RAT_FILTER_ID:
                 filter_id = data;
                 DBG1(DBG_IKE, "received RADIUS attribute Filter-Id: "
                               "'%.*s'", (int)filter_id.len, filter_id.ptr);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (is_esp_tunnel && filter_id.len)
     {
         identification_t *id;
         ike_sa_t *ike_sa;
         auth_cfg_t *auth;
         ike_sa = charon->bus->get_sa(charon->bus);
         if (ike_sa)
         {
             auth = ike_sa->get_auth_cfg(ike_sa, FALSE);
             id = identification_create_from_data(filter_id);
             auth->add(auth, AUTH_RULE_GROUP, id);
         }
     }
 }
static void process_timeout (radius_message_t * msg) static
Handle Session-Timeout attribte and Interim updates
Definition at line 369 of file eap_radius.c.
References daemon_t::bus, charon, radius_message_t::create_enumerator, data, enumerator_t::destroy, eap_radius_accounting_start_interim(), enumerator_t::enumerate, bus_t::get_sa, chunk_t::len, chunk_t::ptr, RAT_ACCT_INTERIM_INTERVAL, RAT_SESSION_TIMEOUT, ike_sa_t::set_auth_lifetime, type, and untoh32().
Referenced by eap_radius_process_attributes().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     chunk_t data;
     int type;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (ike_sa)
     {
         enumerator = msg->create_enumerator(msg);
         while (enumerator->enumerate(enumerator, &type, &data))
         {
             if (type == RAT_SESSION_TIMEOUT && data.len == 4)
             {
                 ike_sa->set_auth_lifetime(ike_sa, untoh32(data.ptr));
             }
             else if (type == RAT_ACCT_INTERIM_INTERVAL && data.len == 4)
             {
                 eap_radius_accounting_start_interim(ike_sa, untoh32(data.ptr));
             }
         }
         enumerator->destroy(enumerator);
     }
 }
static bool radius2ike (private_eap_radius_t * this, radius_message_t * msg, eap_payload_t ** out) static
Copy EAP-Message attribute from RADIUS message to an new EAP payload
Definition at line 120 of file eap_radius.c.
References chunk_cat, chunk_empty, radius_message_t::create_enumerator, data, DBG3, DBG_IKE, enumerator_t::destroy, eap_payload_create_data(), eap_type_names, enumerator_t::enumerate, FALSE, free(), eap_payload_t::get_type, chunk_t::len, chunk_t::ptr, RAT_EAP_MESSAGE, TRUE, and type.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     eap_payload_t *payload;
     chunk_t data, message = chunk_empty;
     int type;
     enumerator = msg->create_enumerator(msg);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (type == RAT_EAP_MESSAGE && data.len)
         {
             message = chunk_cat("mc", message, data);
         }
     }
     enumerator->destroy(enumerator);
     if (message.len)
     {
         *out = payload = eap_payload_create_data(message);
         /* apply EAP method selected by RADIUS server */
         this->type = payload->get_type(payload, &this->vendor);
         DBG3(DBG_IKE, "%N payload %B", eap_type_names, this->type, &message);
         free(message.ptr);
         return TRUE;
     }
     return FALSE;
 }