strongSwan: iv_gen_seq.c File Reference
iv_gen_seq.c File Reference
#include "iv_gen_seq.h"
Classes
struct private_iv_gen_t
Macros
#define SEQ_IV_INIT_STATE (~(u_int64_t)0)
#define SEQ_IV_HIGH_MASK (1ULL << 63)
Typedefs
typedef struct private_iv_gen_t private_iv_gen_t
Functions
METHOD (iv_gen_t, get_iv, bool, private_iv_gen_t *this, u_int64_t seq, size_t size, u_int8_t *buffer)
METHOD (iv_gen_t, allocate_iv, bool, private_iv_gen_t *this, u_int64_t seq, size_t size, chunk_t *chunk)
METHOD (iv_gen_t, destroy, void, private_iv_gen_t *this)
iv_gen_t * iv_gen_seq_create ()
Macro Definition Documentation
#define SEQ_IV_HIGH_MASK (1ULL << 63)
Definition at line 22 of file iv_gen_seq.c.
Referenced by METHOD().
#define SEQ_IV_INIT_STATE (~(u_int64_t)0)
Magic value for the initial IV state
Definition at line 21 of file iv_gen_seq.c.
Referenced by iv_gen_seq_create(), and METHOD().
Typedef Documentation
typedef struct private_iv_gen_t private_iv_gen_t
Definition at line 24 of file iv_gen_seq.c.
Function Documentation
METHOD (iv_gen_t , get_iv , bool , private_iv_gen_t * this, u_int64_t seq, size_t size, u_int8_t * buffer)
Definition at line 52 of file iv_gen_seq.c.
References FALSE, htoun64(), len, memcpy, memset, memxor(), salt, seq, SEQ_IV_HIGH_MASK, SEQ_IV_INIT_STATE, size, and TRUE.
 {
     u_int8_t iv[sizeof(u_int64_t)];
     size_t len = size;
     if (!this->salt)
     {
         return FALSE;
     }
     if (size < sizeof(u_int64_t))
     {
         return FALSE;
     }
     if (this->prevl != SEQ_IV_INIT_STATE && seq <= this->prevl)
     {
         seq |= SEQ_IV_HIGH_MASK;
         if (this->prevh != SEQ_IV_INIT_STATE && seq <= this->prevh)
         {
             return FALSE;
         }
     }
     if ((seq | SEQ_IV_HIGH_MASK) == SEQ_IV_INIT_STATE)
     {
         return FALSE;
     }
     if (seq & SEQ_IV_HIGH_MASK)
     {
         this->prevh = seq;
     }
     else
     {
         this->prevl = seq;
     }
     if (len > sizeof(u_int64_t))
     {
         len = sizeof(u_int64_t);
         memset(buffer, 0, size - len);
     }
     htoun64(iv, seq);
     memxor(iv, this->salt, sizeof(u_int64_t));
     memcpy(buffer + size - len, iv + sizeof(u_int64_t) - len, len);
     return TRUE;
 }
METHOD (iv_gen_t , allocate_iv , bool , private_iv_gen_t * this, u_int64_t seq, size_t size, chunk_t * chunk)
Definition at line 97 of file iv_gen_seq.c.
References chunk_alloc, chunk_free(), FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
 {
     *chunk = chunk_alloc(size);
     if (!get_iv(this, seq, chunk->len, chunk->ptr))
     {
         chunk_free(chunk);
         return FALSE;
     }
     return TRUE;
 }
METHOD (iv_gen_t , destroy , void , private_iv_gen_t * this)
Definition at line 109 of file iv_gen_seq.c.
References free(), and salt.
 {
     free(this->salt);
     free(this);
 }