strongSwan: peer_cfg.c File Reference
peer_cfg.c File Reference
#include <string.h>
#include "peer_cfg.h"
#include <daemon.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include <utils/identification.h>
Classes
struct private_peer_cfg_t
struct child_cfg_enumerator_t
Typedefs
typedef struct private_peer_cfg_t private_peer_cfg_t
Functions
ENUM (cert_policy_names, CERT_ALWAYS_SEND, CERT_NEVER_SEND,"CERT_ALWAYS_SEND","CERT_SEND_IF_ASKED","CERT_NEVER_SEND",)
ENUM (unique_policy_names, UNIQUE_NEVER, UNIQUE_KEEP,"UNIQUE_NEVER","UNIQUE_NO","UNIQUE_REPLACE","UNIQUE_KEEP",)
METHOD (peer_cfg_t, get_name, char *, private_peer_cfg_t *this)
METHOD (peer_cfg_t, get_ike_version, ike_version_t, private_peer_cfg_t *this)
METHOD (peer_cfg_t, get_ike_cfg, ike_cfg_t *, private_peer_cfg_t *this)
METHOD (peer_cfg_t, add_child_cfg, void, private_peer_cfg_t *this, child_cfg_t *child_cfg)
METHOD (peer_cfg_t, remove_child_cfg, void, private_peer_cfg_t *this, child_cfg_enumerator_t *enumerator)
METHOD (enumerator_t, child_cfg_enumerator_destroy, void, child_cfg_enumerator_t *this)
METHOD (enumerator_t, child_cfg_enumerate, bool, child_cfg_enumerator_t *this, child_cfg_t **chd)
METHOD (peer_cfg_t, create_child_cfg_enumerator, enumerator_t *, private_peer_cfg_t *this)
static int get_ts_match (child_cfg_t *cfg, bool local, linked_list_t *sup_list, linked_list_t *hosts)
METHOD (peer_cfg_t, select_child_cfg, child_cfg_t *, private_peer_cfg_t *this, linked_list_t *my_ts, linked_list_t *other_ts, linked_list_t *my_hosts, linked_list_t *other_hosts)
METHOD (peer_cfg_t, get_cert_policy, cert_policy_t, private_peer_cfg_t *this)
METHOD (peer_cfg_t, get_unique_policy, unique_policy_t, private_peer_cfg_t *this)
METHOD (peer_cfg_t, get_keyingtries, u_int32_t, private_peer_cfg_t *this)
METHOD (peer_cfg_t, get_rekey_time, u_int32_t, private_peer_cfg_t *this, bool jitter)
METHOD (peer_cfg_t, get_reauth_time, u_int32_t, private_peer_cfg_t *this, bool jitter)
METHOD (peer_cfg_t, get_over_time, u_int32_t, private_peer_cfg_t *this)
METHOD (peer_cfg_t, use_mobike, bool, private_peer_cfg_t *this)
METHOD (peer_cfg_t, use_aggressive, bool, private_peer_cfg_t *this)
METHOD (peer_cfg_t, use_pull_mode, bool, private_peer_cfg_t *this)
METHOD (peer_cfg_t, get_dpd, u_int32_t, private_peer_cfg_t *this)
METHOD (peer_cfg_t, get_dpd_timeout, u_int32_t, private_peer_cfg_t *this)
METHOD (peer_cfg_t, add_virtual_ip, void, private_peer_cfg_t *this, host_t *vip)
METHOD (peer_cfg_t, create_virtual_ip_enumerator, enumerator_t *, private_peer_cfg_t *this)
METHOD (peer_cfg_t, add_pool, void, private_peer_cfg_t *this, char *name)
METHOD (peer_cfg_t, create_pool_enumerator, enumerator_t *, private_peer_cfg_t *this)
METHOD (peer_cfg_t, add_auth_cfg, void, private_peer_cfg_t *this, auth_cfg_t *cfg, bool local)
METHOD (peer_cfg_t, create_auth_cfg_enumerator, enumerator_t *, private_peer_cfg_t *this, bool local)
static bool auth_cfg_equal (private_peer_cfg_t *this, private_peer_cfg_t *other)
METHOD (peer_cfg_t, equals, bool, private_peer_cfg_t *this, private_peer_cfg_t *other)
METHOD (peer_cfg_t, get_ref, peer_cfg_t *, private_peer_cfg_t *this)
METHOD (peer_cfg_t, destroy, void, private_peer_cfg_t *this)
peer_cfg_t * peer_cfg_create (char *name, ike_cfg_t *ike_cfg, cert_policy_t cert_policy, unique_policy_t unique, u_int32_t keyingtries, u_int32_t rekey_time, u_int32_t reauth_time, u_int32_t jitter_time, u_int32_t over_time, bool mobike, bool aggressive, bool pull_mode, u_int32_t dpd, u_int32_t dpd_timeout, bool mediation, peer_cfg_t *mediated_by, identification_t *peer_id)
Typedef Documentation
typedef struct private_peer_cfg_t private_peer_cfg_t
Definition at line 41 of file peer_cfg.c.
Function Documentation
static bool auth_cfg_equal (private_peer_cfg_t * this, private_peer_cfg_t * other) static
check auth configs for equality
Definition at line 487 of file peer_cfg.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, auth_cfg_t::equals, FALSE, linked_list_t::get_count, private_peer_cfg_t::local_auth, private_peer_cfg_t::remote_auth, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *e1, *e2;
     auth_cfg_t *cfg1, *cfg2;
     bool equal = TRUE;
     if (this->local_auth->get_count(this->local_auth) !=
         other->local_auth->get_count(other->local_auth))
     {
         return FALSE;
     }
     if (this->remote_auth->get_count(this->remote_auth) !=
         other->remote_auth->get_count(other->remote_auth))
     {
         return FALSE;
     }
     e1 = this->local_auth->create_enumerator(this->local_auth);
     e2 = other->local_auth->create_enumerator(other->local_auth);
     while (e1->enumerate(e1, &cfg1) && e2->enumerate(e2, &cfg2))
     {
         if (!cfg1->equals(cfg1, cfg2))
         {
             equal = FALSE;
             break;
         }
     }
     e1->destroy(e1);
     e2->destroy(e2);
     if (!equal)
     {
         return FALSE;
     }
     e1 = this->remote_auth->create_enumerator(this->remote_auth);
     e2 = other->remote_auth->create_enumerator(other->remote_auth);
     while (e1->enumerate(e1, &cfg1) && e2->enumerate(e2, &cfg2))
     {
         if (!cfg1->equals(cfg1, cfg2))
         {
             equal = FALSE;
             break;
         }
     }
     e1->destroy(e1);
     e2->destroy(e2);
     return equal;
 }
ENUM (cert_policy_names , CERT_ALWAYS_SEND , CERT_NEVER_SEND , "CERT_ALWAYS_SEND" , "CERT_SEND_IF_ASKED" , "CERT_NEVER_SEND")
ENUM (unique_policy_names , UNIQUE_NEVER , UNIQUE_KEEP , "UNIQUE_NEVER" , "UNIQUE_NO" , "UNIQUE_REPLACE" , "UNIQUE_KEEP")
static int get_ts_match (child_cfg_t * cfg, bool local, linked_list_t * sup_list, linked_list_t * hosts) static
Check how good a list of TS matches a given child config
Definition at line 253 of file peer_cfg.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, traffic_selector_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, traffic_selector_t::equals, linked_list_t::get_count, traffic_selector_t::get_subset, child_cfg_t::get_traffic_selectors, and match().
Referenced by METHOD().
 {
     linked_list_t *cfg_list;
     enumerator_t *sup_enum, *cfg_enum;
     traffic_selector_t *sup_ts, *cfg_ts, *subset;
     int match = 0, round;
     /* fetch configured TS list, narrowing dynamic TS */
     cfg_list = cfg->get_traffic_selectors(cfg, local, NULL, hosts);
     /* use a round counter to rate leading TS with higher priority */
     round = sup_list->get_count(sup_list);
     sup_enum = sup_list->create_enumerator(sup_list);
     while (sup_enum->enumerate(sup_enum, &sup_ts))
     {
         cfg_enum = cfg_list->create_enumerator(cfg_list);
         while (cfg_enum->enumerate(cfg_enum, &cfg_ts))
         {
             if (cfg_ts->equals(cfg_ts, sup_ts))
             {   /* equality is honored better than matches */
                 match += round * 5;
             }
             else
             {
                 subset = cfg_ts->get_subset(cfg_ts, sup_ts);
                 if (subset)
                 {
                     subset->destroy(subset);
                     match += round * 1;
                 }
             }
         }
         cfg_enum->destroy(cfg_enum);
         round--;
     }
     sup_enum->destroy(sup_enum);
     cfg_list->destroy_offset(cfg_list, offsetof(traffic_selector_t, destroy));
     return match;
 }
METHOD (peer_cfg_t , get_name , char * , private_peer_cfg_t * this)
Definition at line 177 of file peer_cfg.c.
References name.
 {
     return this->name;
 }
METHOD (peer_cfg_t , get_ike_version , ike_version_t , private_peer_cfg_t * this)
Definition at line 183 of file peer_cfg.c.
 {
     return this->ike_cfg->get_version(this->ike_cfg);
 }
METHOD (peer_cfg_t , get_ike_cfg , ike_cfg_t * , private_peer_cfg_t * this)
Definition at line 189 of file peer_cfg.c.
 {
     return this->ike_cfg;
 }
METHOD (peer_cfg_t , add_child_cfg , void , private_peer_cfg_t * this, child_cfg_t * child_cfg)
Definition at line 195 of file peer_cfg.c.
References mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->child_cfgs->insert_last(this->child_cfgs, child_cfg);
     this->mutex->unlock(this->mutex);
 }
METHOD (peer_cfg_t , remove_child_cfg , void , private_peer_cfg_t * this, child_cfg_enumerator_t * enumerator)
Definition at line 212 of file peer_cfg.c.
References child_cfg_enumerator_t::wrapped.
 {
     this->child_cfgs->remove_at(this->child_cfgs, enumerator->wrapped);
 }
METHOD (enumerator_t , child_cfg_enumerator_destroy , void , child_cfg_enumerator_t * this)
Definition at line 218 of file peer_cfg.c.
References free(), mutex, and mutex_t::unlock.
 {
     this->mutex->unlock(this->mutex);
     this->wrapped->destroy(this->wrapped);
     free(this);
 }
METHOD (enumerator_t , child_cfg_enumerate , bool , child_cfg_enumerator_t * this, child_cfg_t ** chd)
Definition at line 226 of file peer_cfg.c.
 {
     return this->wrapped->enumerate(this->wrapped, chd);
 }
METHOD (peer_cfg_t , create_child_cfg_enumerator , enumerator_t * , private_peer_cfg_t * this)
Definition at line 232 of file peer_cfg.c.
References destroy(), INIT, mutex_t::lock, mutex, and child_cfg_enumerator_t::public.
 {
     child_cfg_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_child_cfg_enumerate,
             .destroy = (void*)_child_cfg_enumerator_destroy,
         },
         .mutex = this->mutex,
         .wrapped = this->child_cfgs->create_enumerator(this->child_cfgs),
     );
     this->mutex->lock(this->mutex);
     return &enumerator->public;
 }
METHOD (peer_cfg_t , select_child_cfg , child_cfg_t * , private_peer_cfg_t * this, linked_list_t * my_ts, linked_list_t * other_ts, linked_list_t * my_hosts, linked_list_t * other_hosts)
Definition at line 297 of file peer_cfg.c.
References DBG2, DBG_CFG, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, FALSE, found, child_cfg_t::get_name, child_cfg_t::get_ref, get_ts_match(), and TRUE.
 {
     child_cfg_t *current, *found = NULL;
     enumerator_t *enumerator;
     int best = 0;
     DBG2(DBG_CFG, "looking for a child config for %#R === %#R", my_ts, other_ts);
     enumerator = create_child_cfg_enumerator(this);
     while (enumerator->enumerate(enumerator, &current))
     {
         int my_prio, other_prio;
         my_prio = get_ts_match(current, TRUE, my_ts, my_hosts);
         other_prio = get_ts_match(current, FALSE, other_ts, other_hosts);
         if (my_prio && other_prio)
         {
             DBG2(DBG_CFG, "  candidate \"%s\" with prio %d+%d",
                  current->get_name(current), my_prio, other_prio);
             if (my_prio + other_prio > best)
             {
                 best = my_prio + other_prio;
                 DESTROY_IF(found);
                 found = current->get_ref(current);
             }
         }
     }
     enumerator->destroy(enumerator);
     if (found)
     {
         DBG2(DBG_CFG, "found matching child config \"%s\" with prio %d",
              found->get_name(found), best);
     }
     return found;
 }
METHOD (peer_cfg_t , get_cert_policy , cert_policy_t , private_peer_cfg_t * this)
Definition at line 335 of file peer_cfg.c.
 {
     return this->cert_policy;
 }
METHOD (peer_cfg_t , get_unique_policy , unique_policy_t , private_peer_cfg_t * this)
Definition at line 341 of file peer_cfg.c.
 {
     return this->unique;
 }
METHOD (peer_cfg_t , get_keyingtries , u_int32_t , private_peer_cfg_t * this)
Definition at line 347 of file peer_cfg.c.
 {
     return this->keyingtries;
 }
METHOD (peer_cfg_t , get_rekey_time , u_int32_t , private_peer_cfg_t * this, bool jitter)
Definition at line 353 of file peer_cfg.c.
References random.
 {
     if (this->rekey_time == 0)
     {
         return 0;
     }
     if (this->jitter_time == 0 || !jitter)
     {
         return this->rekey_time;
     }
     return this->rekey_time - (random() % this->jitter_time);
 }
METHOD (peer_cfg_t , get_reauth_time , u_int32_t , private_peer_cfg_t * this, bool jitter)
Definition at line 367 of file peer_cfg.c.
References random.
 {
     if (this->reauth_time == 0)
     {
         return 0;
     }
     if (this->jitter_time == 0 || !jitter)
     {
         return this->reauth_time;
     }
     return this->reauth_time - (random() % this->jitter_time);
 }
METHOD (peer_cfg_t , get_over_time , u_int32_t , private_peer_cfg_t * this)
Definition at line 381 of file peer_cfg.c.
 {
     return this->over_time;
 }
METHOD (peer_cfg_t , use_mobike , bool , private_peer_cfg_t * this)
Definition at line 387 of file peer_cfg.c.
 {
     return this->use_mobike;
 }
METHOD (peer_cfg_t , use_aggressive , bool , private_peer_cfg_t * this)
Definition at line 393 of file peer_cfg.c.
 {
     return this->aggressive;
 }
METHOD (peer_cfg_t , use_pull_mode , bool , private_peer_cfg_t * this)
Definition at line 399 of file peer_cfg.c.
 {
     return this->pull_mode;
 }
METHOD (peer_cfg_t , get_dpd , u_int32_t , private_peer_cfg_t * this)
Definition at line 405 of file peer_cfg.c.
 {
     return this->dpd;
 }
METHOD (peer_cfg_t , get_dpd_timeout , u_int32_t , private_peer_cfg_t * this)
Definition at line 411 of file peer_cfg.c.
 {
     return this->dpd_timeout;
 }
METHOD (peer_cfg_t , add_virtual_ip , void , private_peer_cfg_t * this, host_t * vip)
Definition at line 417 of file peer_cfg.c.
 {
     this->vips->insert_last(this->vips, vip);
 }
METHOD (peer_cfg_t , create_virtual_ip_enumerator , enumerator_t * , private_peer_cfg_t * this)
Definition at line 423 of file peer_cfg.c.
 {
     return this->vips->create_enumerator(this->vips);
 }
METHOD (peer_cfg_t , add_pool , void , private_peer_cfg_t * this, char * name)
Definition at line 429 of file peer_cfg.c.
References strdup.
 {
     this->pools->insert_last(this->pools, strdup(name));
 }
METHOD (peer_cfg_t , create_pool_enumerator , enumerator_t * , private_peer_cfg_t * this)
Definition at line 435 of file peer_cfg.c.
 {
     return this->pools->create_enumerator(this->pools);
 }
METHOD (peer_cfg_t , add_auth_cfg , void , private_peer_cfg_t * this, auth_cfg_t * cfg, bool local)
Definition at line 441 of file peer_cfg.c.
 {
     if (local)
     {
         this->local_auth->insert_last(this->local_auth, cfg);
     }
     else
     {
         this->remote_auth->insert_last(this->remote_auth, cfg);
     }
 }
METHOD (peer_cfg_t , create_auth_cfg_enumerator , enumerator_t * , private_peer_cfg_t * this, bool local)
Definition at line 454 of file peer_cfg.c.
 {
     if (local)
     {
         return this->local_auth->create_enumerator(this->local_auth);
     }
     return this->remote_auth->create_enumerator(this->remote_auth);
 }
METHOD (peer_cfg_t , equals , bool , private_peer_cfg_t * this, private_peer_cfg_t * other)
Definition at line 538 of file peer_cfg.c.
References private_peer_cfg_t::aggressive, auth_cfg_equal(), private_peer_cfg_t::cert_policy, enumerator_t::destroy, private_peer_cfg_t::dpd, enumerator_t::enumerate, equals(), peer_cfg_t::equals, FALSE, linked_list_t::get_count, host_t::ip_equals, private_peer_cfg_t::jitter_time, private_peer_cfg_t::keyingtries, private_peer_cfg_t::over_time, private_peer_cfg_t::pools, private_peer_cfg_t::public, private_peer_cfg_t::pull_mode, private_peer_cfg_t::reauth_time, private_peer_cfg_t::rekey_time, streq(), TRUE, private_peer_cfg_t::unique, private_peer_cfg_t::use_mobike, and private_peer_cfg_t::vips.
 {
     enumerator_t *e1, *e2;
     host_t *vip1, *vip2;
     char *pool1, *pool2;
     if (this == other)
     {
         return TRUE;
     }
     if (this->public.equals != other->public.equals)
     {
         return FALSE;
     }
     if (this->vips->get_count(this->vips) != other->vips->get_count(other->vips))
     {
         return FALSE;
     }
     e1 = create_virtual_ip_enumerator(this);
     e2 = create_virtual_ip_enumerator(other);
     if (e1->enumerate(e1, &vip1) && e2->enumerate(e2, &vip2))
     {
         if (!vip1->ip_equals(vip1, vip2))
         {
             e1->destroy(e1);
             e2->destroy(e2);
             return FALSE;
         }
     }
     e1->destroy(e1);
     e2->destroy(e2);
     if (this->pools->get_count(this->pools) !=
         other->pools->get_count(other->pools))
     {
         return FALSE;
     }
     e1 = create_pool_enumerator(this);
     e2 = create_pool_enumerator(other);
     if (e1->enumerate(e1, &pool1) && e2->enumerate(e2, &pool2))
     {
         if (!streq(pool1, pool2))
         {
             e1->destroy(e1);
             e2->destroy(e2);
             return FALSE;
         }
     }
     e1->destroy(e1);
     e2->destroy(e2);
     return (
         get_ike_version(this) == get_ike_version(other) &&
         this->cert_policy == other->cert_policy &&
         this->unique == other->unique &&
         this->keyingtries == other->keyingtries &&
         this->use_mobike == other->use_mobike &&
         this->rekey_time == other->rekey_time &&
         this->reauth_time == other->reauth_time &&
         this->jitter_time == other->jitter_time &&
         this->over_time == other->over_time &&
         this->dpd == other->dpd &&
         this->aggressive == other->aggressive &&
         this->pull_mode == other->pull_mode &&
         auth_cfg_equal(this, other)
 #ifdef ME
         && this->mediation == other->mediation &&
         this->mediated_by == other->mediated_by &&
         (this->peer_id == other->peer_id ||
          (this->peer_id && other->peer_id &&
           this->peer_id->equals(this->peer_id, other->peer_id)))
 #endif /* ME */
         );
 }
METHOD (peer_cfg_t , get_ref , peer_cfg_t * , private_peer_cfg_t * this)
Definition at line 615 of file peer_cfg.c.
References ref_get().
 {
     ref_get(&this->refcount);
     return &this->public;
 }
METHOD (peer_cfg_t , destroy , void , private_peer_cfg_t * this)
Definition at line 622 of file peer_cfg.c.
References mutex_t::destroy, destroy(), DESTROY_IF, free(), mutex, name, and ref_put().
 {
     if (ref_put(&this->refcount))
     {
         this->ike_cfg->destroy(this->ike_cfg);
         this->child_cfgs->destroy_offset(this->child_cfgs,
                                         offsetof(child_cfg_t, destroy));
         this->local_auth->destroy_offset(this->local_auth,
                                         offsetof(auth_cfg_t, destroy));
         this->remote_auth->destroy_offset(this->remote_auth,
                                         offsetof(auth_cfg_t, destroy));
         this->vips->destroy_offset(this->vips, offsetof(host_t, destroy));
         this->pools->destroy_function(this->pools, free);
 #ifdef ME
         DESTROY_IF(this->mediated_by);
         DESTROY_IF(this->peer_id);
 #endif /* ME */
         this->mutex->destroy(this->mutex);
         free(this->name);
         free(this);
     }
 }