strongSwan: private key
private key
tkm
Classes
struct tkm_private_key_t
Typedefs
typedef struct tkm_private_key_t tkm_private_key_t
Functions
tkm_private_key_t * tkm_private_key_init (identification_t *const id)
Detailed Description
Typedef Documentation
typedef struct tkm_private_key_t tkm_private_key_t
Definition at line 27 of file tkm_private_key.h.
Function Documentation
tkm_private_key_t* tkm_private_key_init (identification_t *const id)
Initialize TKM private key with given key ID.
See header.
Definition at line 143 of file tkm_private_key.c.
References cert, CERT_ANY, library_t::credmgr, public_key_t::destroy, destroy(), FALSE, credential_manager_t::get_cert, public_key_t::get_type, INIT, KEY_ANY, key_type, lib, private_key_belongs_to(), private_key_equals(), and private_key_has_fingerprint().
Referenced by METHOD().
 {
     private_tkm_private_key_t *this;
     certificate_t *cert;
     public_key_t *pubkey;
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .sign = _sign,
                 .decrypt = _decrypt,
                 .get_keysize = _get_keysize,
                 .get_public_key = _get_public_key,
                 .equals = private_key_equals,
                 .belongs_to = private_key_belongs_to,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = private_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
         .id = id->clone(id),
     );
     /* get key type from associated public key */
     cert = lib->credmgr->get_cert(lib->credmgr, CERT_ANY, KEY_ANY, id, FALSE);
     if (!cert)
     {
         destroy(this);
         return NULL;
     }
     pubkey = cert->get_public_key(cert);
     if (!pubkey)
     {
         cert->destroy(cert);
         destroy(this);
         return NULL;
     }
     this->key_type = pubkey->get_type(pubkey);
     pubkey->destroy(pubkey);
     cert->destroy(cert);
     return &this->public;
 }