strongSwan: file_logger.c File Reference
file_logger.c File Reference
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include "file_logger.h"
#include <daemon.h>
#include <threading/mutex.h>
#include <threading/rwlock.h>
Classes
struct private_file_logger_t
Typedefs
typedef struct
private_file_logger_t private_file_logger_t
Functions
METHOD (logger_t, log_, void, private_file_logger_t *this, debug_t group, level_t level, int thread, ike_sa_t *ike_sa, const char *message)
METHOD (logger_t, get_level, level_t, private_file_logger_t *this, debug_t group)
METHOD (file_logger_t, set_level, void, private_file_logger_t *this, debug_t group, level_t level)
METHOD (file_logger_t, set_options, void, private_file_logger_t *this, char *time_format, bool add_ms, bool ike_name)
static void close_file (private_file_logger_t *this)
METHOD (file_logger_t, open_, void, private_file_logger_t *this, bool flush_line, bool append)
METHOD (file_logger_t, destroy, void, private_file_logger_t *this)
file_logger_t * file_logger_create (char *filename)
Typedef Documentation
typedef struct private_file_logger_t private_file_logger_t
Definition at line 30 of file file_logger.c.
Function Documentation
static void close_file (private_file_logger_t * this) static
Close the current file, if any
Definition at line 215 of file file_logger.c.
References out.
Referenced by METHOD().
 {
     if (this->out && this->out != stdout && this->out != stderr)
     {
         fclose(this->out);
         this->out = NULL;
     }
 }
METHOD (logger_t , log_ , void , private_file_logger_t * this, debug_t group, level_t level, int thread, ike_sa_t * ike_sa, const char * message)
Definition at line 88 of file file_logger.c.
References debug_names, fprintf, ike_sa_t::get_name, ike_sa_t::get_peer_cfg, ike_sa_t::get_unique_id, localtime_r(), mutex_t::lock, lock, mutex, next, out, s, snprintf, TRUE, spinlock_t::unlock, and mutex_t::unlock.
 {
     char timestr[128], namestr[128] = "";
     const char *current = message, *next;
     struct tm tm;
     timeval_t tv;
     time_t s;
     u_int ms = 0;
     this->lock->read_lock(this->lock);
     if (!this->out)
     {   /* file is not open */
         this->lock->unlock(this->lock);
         return;
     }
     if (this->time_format)
     {
         gettimeofday(&tv, NULL);
         s = tv.tv_sec;
         ms = tv.tv_usec / 1000;
         localtime_r(&s, &tm);
         strftime(timestr, sizeof(timestr), this->time_format, &tm);
     }
     if (this->ike_name && ike_sa)
     {
         if (ike_sa->get_peer_cfg(ike_sa))
         {
             snprintf(namestr, sizeof(namestr), " <%s|%d>",
                 ike_sa->get_name(ike_sa), ike_sa->get_unique_id(ike_sa));
         }
         else
         {
             snprintf(namestr, sizeof(namestr), " <%d>",
                 ike_sa->get_unique_id(ike_sa));
         }
     }
     else
     {
         namestr[0] = '\0';
     }
     /* prepend a prefix in front of every line */
     this->mutex->lock(this->mutex);
     while (TRUE)
     {
         next = strchr(current, '\n');
         if (this->time_format)
         {
             if (this->add_ms)
             {
                 fprintf(this->out, "%s.%03u %.2d[%N]%s ",
                         timestr, ms, thread, debug_names, group, namestr);
             }
             else
             {
                 fprintf(this->out, "%s %.2d[%N]%s ",
                         timestr, thread, debug_names, group, namestr);
             }
         }
         else
         {
             fprintf(this->out, "%.2d[%N]%s ",
                     thread, debug_names, group, namestr);
         }
         if (next == NULL)
         {
             fprintf(this->out, "%s\n", current);
             break;
         }
         fprintf(this->out, "%.*s\n", (int)(next - current), current);
         current = next + 1;
     }
 #ifndef HAVE_SETLINEBUF
     if (this->flush_line)
     {
         fflush(this->out);
     }
 #endif /* !HAVE_SETLINEBUF */
     this->mutex->unlock(this->mutex);
     this->lock->unlock(this->lock);
 }
METHOD (logger_t , get_level , level_t , private_file_logger_t * this, debug_t group)
Definition at line 172 of file file_logger.c.
References group, levels, lock, and spinlock_t::unlock.
 {
     level_t level;
     this->lock->read_lock(this->lock);
     level = this->levels[group];
     this->lock->unlock(this->lock);
     return level;
 }
METHOD (file_logger_t , set_level , void , private_file_logger_t * this, debug_t group, level_t level)
Definition at line 183 of file file_logger.c.
References DBG_ANY, DBG_MAX, group, levels, lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     if (group < DBG_ANY)
     {
         this->levels[group] = level;
     }
     else
     {
         for (group = 0; group < DBG_MAX; group++)
         {
             this->levels[group] = level;
         }
     }
     this->lock->unlock(this->lock);
 }
METHOD (file_logger_t , set_options , void , private_file_logger_t * this, char * time_format, bool add_ms, bool ike_name)
Definition at line 201 of file file_logger.c.
References free(), lock, strdupnull(), and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     free(this->time_format);
     this->time_format = strdupnull(time_format);
     this->add_ms = add_ms;
     this->ike_name = ike_name;
     this->lock->unlock(this->lock);
 }
METHOD (file_logger_t , open_ , void , private_file_logger_t * this, bool flush_line, bool append)
Definition at line 224 of file file_logger.c.
References close_file(), DBG1, DBG_DMN, lock, out, streq(), strerror, and spinlock_t::unlock.
 {
     FILE *file;
     if (streq(this->filename, "stderr"))
     {
         file = stderr;
     }
     else if (streq(this->filename, "stdout"))
     {
         file = stdout;
     }
     else
     {
         file = fopen(this->filename, append ? "a" : "w");
         if (file == NULL)
         {
             DBG1(DBG_DMN, "opening file %s for logging failed: %s",
                  this->filename, strerror(errno));
             return;
         }
 #ifdef HAVE_SETLINEBUF
         if (flush_line)
         {
             setlinebuf(file);
         }
 #endif /* HAVE_SETLINEBUF */
     }
     this->lock->write_lock(this->lock);
     close_file(this);
     this->out = file;
     this->flush_line = flush_line;
     this->lock->unlock(this->lock);
 }
METHOD (file_logger_t , destroy , void , private_file_logger_t * this)
Definition at line 260 of file file_logger.c.
References close_file(), spinlock_t::destroy, mutex_t::destroy, free(), lock, mutex, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     close_file(this);
     this->lock->unlock(this->lock);
     this->mutex->destroy(this->mutex);
     this->lock->destroy(this->lock);
     free(this->time_format);
     free(this->filename);
     free(this);
 }