strongSwan: ietf_attr_op_status.c File Reference
ietf_attr_op_status.c File Reference
#include "ietf_attr_op_status.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
#include <time.h>
Classes
struct private_ietf_attr_op_status_t
Macros
#define OP_STATUS_SIZE 24
Typedefs
typedef struct
private_ietf_attr_op_status_t private_ietf_attr_op_status_t
Functions
ENUM (op_status_names, OP_STATUS_UNKNOWN, OP_STATUS_OPERATIONAL,"unknown","not installed","installed","operational")
ENUM (op_result_names, OP_RESULT_UNKNOWN, OP_RESULT_UNSUCCESSFUL,"unknown","successful","errored","unsuccessful")
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_op_status_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_op_status_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_op_status_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_op_status_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_op_status_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_op_status_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_op_status_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_op_status_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_op_status_t *this)
METHOD (ietf_attr_op_status_t, get_status, u_int8_t, private_ietf_attr_op_status_t *this)
METHOD (ietf_attr_op_status_t, get_result, u_int8_t, private_ietf_attr_op_status_t *this)
METHOD (ietf_attr_op_status_t, get_last_use, time_t, private_ietf_attr_op_status_t *this)
pa_tnc_attr_t * ietf_attr_op_status_create (u_int8_t status, u_int8_t result, time_t last_use)
pa_tnc_attr_t * ietf_attr_op_status_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define OP_STATUS_SIZE 24
PA-TNC Operational Status type (see section 4.2.5 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Status | Result | Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Last Use | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Last Use (continued) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Last Use (continued) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Last Use (continued) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Last Use (continued) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 61 of file ietf_attr_op_status.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_op_status_t private_ietf_attr_op_status_t
Definition at line 25 of file ietf_attr_op_status.c.
Function Documentation
ENUM (op_status_names , OP_STATUS_UNKNOWN , OP_STATUS_OPERATIONAL , "unknown" , "not installed" , "installed" , "operational")
ENUM (op_result_names , OP_RESULT_UNKNOWN , OP_RESULT_UNSUCCESSFUL , "unknown" , "successful" , "errored" , "unsuccessful")
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_op_status_t * this)
Definition at line 114 of file ietf_attr_op_status.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_op_status_t * this)
Definition at line 120 of file ietf_attr_op_status.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_op_status_t * this)
Definition at line 126 of file ietf_attr_op_status.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_op_status_t * this, bool noskip)
Definition at line 132 of file ietf_attr_op_status.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_op_status_t * this)
Definition at line 138 of file ietf_attr_op_status.c.
References bio_writer_create(), chunk_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, gmtime_r(), length, OP_STATUS_SIZE, result, snprintf, status, value, bio_writer_t::write_data, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     char last_use[24];
     struct tm t;
     if (this->value.ptr)
     {
         return;
     }
     /* Conversion from time_t to RFC 3339 ASCII string */
     gmtime_r(&this->last_use, &t);
     snprintf(last_use, 21, "%04d-%02d-%02dT%02d:%02d:%02dZ", 1900 + t.tm_year,
              t.tm_mon + 1, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec);
     writer = bio_writer_create(OP_STATUS_SIZE);
     writer->write_uint8 (writer, this->status);
     writer->write_uint8 (writer, this->result);
     writer->write_uint16(writer, 0x0000);
     writer->write_data  (writer, chunk_create(last_use, 20));
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_op_status_t * this, u_int32_t * offset)
Definition at line 166 of file ietf_attr_op_status.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, OP_RESULT_ROOF, OP_STATUS_ROOF, OP_STATUS_SIZE, chunk_t::ptr, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint8, reserved, result, status, SUCCESS, and value.
 {
     bio_reader_t *reader;
     chunk_t last_use;
     u_int16_t reserved;
     struct tm t;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len != OP_STATUS_SIZE)
     {
         DBG1(DBG_TNC, "incorrect size for IETF operational status");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &this->status);
     reader->read_uint8 (reader, &this->result);
     reader->read_uint16(reader, &reserved);
     reader->read_data  (reader, 20, &last_use);
     reader->destroy(reader);
     if (this->status > OP_STATUS_ROOF)
     {
         DBG1(DBG_TNC, "invalid status value %c for IETF operational status",
                        this->status);
         return FAILED;
     }
     *offset = 1;
     if (this->result > OP_RESULT_ROOF)
     {
         DBG1(DBG_TNC, "invalid result value %c for IETF operational status",
                        this->result);
         return FAILED;
     }
     *offset = 4;
     /* Conversion from RFC 3339 ASCII string to time_t */
     if (sscanf(last_use.ptr, "%4d-%2d-%2dT%2d:%2d:%2dZ", &t.tm_year, &t.tm_mon,
                &t.tm_mday, &t.tm_hour, &t.tm_min, &t.tm_sec) != 6)
     {
         DBG1(DBG_TNC, "invalid last_use time format in IETF operational status");
         return FAILED;
     }
     t.tm_year -= 1900;
     t.tm_mon -= 1;
     t.tm_isdst = 0;
     this->last_use = mktime(&t) - timezone;
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_op_status_t * this, chunk_t segment)
Definition at line 225 of file ietf_attr_op_status.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_op_status_t * this)
Definition at line 231 of file ietf_attr_op_status.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_op_status_t * this)
Definition at line 238 of file ietf_attr_op_status.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_op_status_t , get_status , u_int8_t , private_ietf_attr_op_status_t * this)
Definition at line 248 of file ietf_attr_op_status.c.
References status.
 {
     return this->status;
 }
METHOD (ietf_attr_op_status_t , get_result , u_int8_t , private_ietf_attr_op_status_t * this)
Definition at line 254 of file ietf_attr_op_status.c.
References result.
 {
     return this->result;
 }
METHOD (ietf_attr_op_status_t , get_last_use , time_t , private_ietf_attr_op_status_t * this)
Definition at line 260 of file ietf_attr_op_status.c.
 {
     return this->last_use;
 }