strongSwan: stroke_cred
stroke_cred
stroke
Classes
struct stroke_cred_t
Typedefs
typedef struct stroke_cred_t stroke_cred_t
Functions
stroke_cred_t * stroke_cred_create (stroke_ca_t *ca)
Detailed Description
Typedef Documentation
typedef struct stroke_cred_t stroke_cred_t
Definition at line 34 of file stroke_cred.h.
Function Documentation
stroke_cred_t* stroke_cred_create (stroke_ca_t * ca)
Create a stroke_cred instance.
Definition at line 1449 of file stroke_cred.c.
References credential_manager_t::add_set, library_t::credmgr, destroy(), FALSE, settings_t::get_bool, settings_t::get_str, INIT, lib, load_certs(), load_secrets(), mem_cred_create(), library_t::ns, reread(), return_null(), SECRETS_FILE, and library_t::settings.
Referenced by stroke_socket_create().
 {
     private_stroke_cred_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_private_enumerator = (void*)return_null,
                 .create_cert_enumerator = (void*)return_null,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)_cache_cert,
             },
             .reread = _reread,
             .load_peer = _load_peer,
             .load_pubkey = _load_pubkey,
             .add_shared = _add_shared,
             .cachecrl = _cachecrl,
             .destroy = _destroy,
         },
         .secrets_file = lib->settings->get_str(lib->settings,
                                 "%s.plugins.stroke.secrets_file", SECRETS_FILE,
                                 lib->ns),
         .creds = mem_cred_create(),
         .aacerts = mem_cred_create(),
         .ca = ca,
     );
     lib->credmgr->add_set(lib->credmgr, &this->creds->set);
     lib->credmgr->add_set(lib->credmgr, &this->aacerts->set);
     this->force_ca_cert = lib->settings->get_bool(lib->settings,
                         "%s.plugins.stroke.ignore_missing_ca_basic_constraint",
                         FALSE, lib->ns);
     load_certs(this);
     load_secrets(this, NULL, this->secrets_file, 0, NULL);
     return &this->public;
 }