strongSwan: stream_t Struct Reference
stream_t Struct Reference
stream
#include "stream.h"
Public Attributes
ssize_t(* read)(stream_t *this, void *buf, size_t len, bool block)
bool(* read_all)(stream_t *this, void *buf, size_t len)
void(* on_read)(stream_t *this, stream_cb_t cb, void *data)
ssize_t(* write)(stream_t *this, void *buf, size_t len, bool block)
bool(* write_all)(stream_t *this, void *buf, size_t len)
void(* on_write)(stream_t *this, stream_cb_t cb, void *data)
FILE *(* get_file)(stream_t *this)
void(* destroy)(stream_t *this)
Detailed Description
Abstraction of a Berkley socket using stream semantics.
Definition at line 55 of file stream.h.
Member Data Documentation
void(* stream_t::destroy)(stream_t *this)
Destroy a stream_t.
Definition at line 134 of file stream.h.
Referenced by accept_async(), CALLBACK(), entry_destroy(), METHOD(), send_stroke_msg(), START_TEST(), and vici_disconnect().
FILE*(* stream_t::get_file)(stream_t *this)
Get a FILE reference for this stream.
Returns
FILE*, must be fclose()d, NULL on error
Definition at line 129 of file stream.h.
Referenced by on_accept().
void(* stream_t::on_read)(stream_t *this, stream_cb_t cb, void *data)
Register a callback to invoke when stream has data to read.
Parameters
cb callback function, NULL to unregister
data data to pass to callback
Definition at line 89 of file stream.h.
Referenced by CALLBACK(), on_accept(), START_TEST(), vici_connect(), vici_register(), and vici_submit().
void(* stream_t::on_write)(stream_t *this, stream_cb_t cb, void *data)
Register a callback to invoke when a write would not block.
Parameters
cb callback function, NULL to unregister
data data to pass to callback
Definition at line 122 of file stream.h.
Referenced by CALLBACK(), and START_TEST().
ssize_t(* stream_t::read)(stream_t *this, void *buf, size_t len, bool block)
Read data from the stream.
If "block" is FALSE and no data is available, the function returns -1 and sets errno to EWOULDBLOCK.
Parameters
buf data buffer to read into
len number of bytes to read
block TRUE to use a blocking read
Returns
number of bytes read, -1 on error
Definition at line 68 of file stream.h.
Referenced by all(), CALLBACK(), do_read(), on_read(), send_stroke_msg(), servicing(), and START_TEST().
bool(* stream_t::read_all)(stream_t *this, void *buf, size_t len)
Read data from the stream, avoiding short reads.
This call is always blocking, and reads until len has been read completely. If the connection is closed before enough bytes could be returned, errno is set to ECONNRESET.
Parameters
buf data buffer to read into
len number of bytes to read
Returns
TRUE if len bytes read, FALSE on error
Definition at line 81 of file stream.h.
Referenced by CALLBACK(), handle_event(), handle_response(), on_accept(), on_read(), servicing(), and START_TEST().
ssize_t(* stream_t::write)(stream_t *this, void *buf, size_t len, bool block)
Write data to the stream.
If "block" is FALSE and the write would block, the function returns -1 and sets errno to EWOULDBLOCK.
Parameters
buf data buffer to write
len number of bytes to write
block TRUE to use a blocking write
Returns
number of bytes written, -1 on error
Definition at line 102 of file stream.h.
Referenced by all(), concurrency(), do_write(), on_write(), servicing(), and START_TEST().
bool(* stream_t::write_all)(stream_t *this, void *buf, size_t len)
Write data to the stream, avoiding short writes.
This call is always blocking, and writes until len bytes has been written.
Parameters
buf data buffer to write
len number of bytes to write
Returns
TRUE if len bytes written, FALSE on error
Definition at line 114 of file stream.h.
Referenced by event_cb(), list(), METHOD(), query(), query_cb(), send_stroke_msg(), servicing(), START_TEST(), vici_register(), and vici_submit().
The documentation for this struct was generated from the following file:
stream.h