strongSwan: mutex.c File Reference
mutex.c File Reference
#include <pthread.h>
#include <stdint.h>
#include <time.h>
#include <errno.h>
#include <library.h>
#include <utils/debug.h>
#include "thread.h"
#include "condvar.h"
#include "mutex.h"
#include "lock_profiler.h"
Classes
struct private_mutex_t
struct private_r_mutex_t
struct private_condvar_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct private_mutex_t private_mutex_t
typedef struct private_r_mutex_t private_r_mutex_t
typedef struct private_condvar_t private_condvar_t
Functions
METHOD (mutex_t, lock, void, private_mutex_t *this)
METHOD (mutex_t, unlock, void, private_mutex_t *this)
METHOD (mutex_t, lock_r, void, private_r_mutex_t *this)
METHOD (mutex_t, unlock_r, void, private_r_mutex_t *this)
METHOD (mutex_t, mutex_destroy, void, private_mutex_t *this)
METHOD (mutex_t, mutex_destroy_r, void, private_r_mutex_t *this)
mutex_t * mutex_create (mutex_type_t type)
METHOD (condvar_t, wait_, void, private_condvar_t *this, private_mutex_t *mutex)
METHOD (condvar_t, timed_wait_abs, bool, private_condvar_t *this, private_mutex_t *mutex, timeval_t time)
METHOD (condvar_t, timed_wait, bool, private_condvar_t *this, private_mutex_t *mutex, u_int timeout)
METHOD (condvar_t, signal_, void, private_condvar_t *this)
METHOD (condvar_t, broadcast, void, private_condvar_t *this)
METHOD (condvar_t, condvar_destroy, void, private_condvar_t *this)
condvar_t * condvar_create (condvar_type_t type)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file mutex.c.
Typedef Documentation
typedef struct private_condvar_t private_condvar_t
Definition at line 33 of file mutex.c.
typedef struct private_mutex_t private_mutex_t
Definition at line 31 of file mutex.c.
typedef struct private_r_mutex_t private_r_mutex_t
Definition at line 32 of file mutex.c.
Function Documentation
METHOD (mutex_t , lock , void , private_mutex_t * this)
Definition at line 100 of file mutex.c.
References DBG1, DBG_LIB, mutex, profiler_end, profiler_start, and strerror.
 {
     int err;
     profiler_start(&this->profile);
     err = pthread_mutex_lock(&this->mutex);
     if (err)
     {
         DBG1(DBG_LIB, "!!! MUTEX LOCK ERROR: %s !!!", strerror(err));
     }
     profiler_end(&this->profile);
 }
METHOD (mutex_t , unlock , void , private_mutex_t * this)
Definition at line 114 of file mutex.c.
References DBG1, DBG_LIB, mutex, and strerror.
 {
     int err;
     err = pthread_mutex_unlock(&this->mutex);
     if (err)
     {
         DBG1(DBG_LIB, "!!! MUTEX UNLOCK ERROR: %s !!!", strerror(err));
     }
 }
METHOD (mutex_t , lock_r , void , private_r_mutex_t * this)
Definition at line 126 of file mutex.c.
References cas_ptr(), lock, and thread_current().
 {
     thread_t *self = thread_current();
     if (cas_ptr(&this->thread, self, self))
     {
         this->times++;
     }
     else
     {
         lock(&this->generic);
         cas_ptr(&this->thread, NULL, self);
         this->times = 1;
     }
 }
METHOD (mutex_t , unlock_r , void , private_r_mutex_t * this)
Definition at line 143 of file mutex.c.
References cas_ptr(), and thread_current().
 {
     if (--this->times == 0)
     {
         cas_ptr(&this->thread, thread_current(), NULL);
         unlock(&this->generic);
     }
 }
METHOD (mutex_t , mutex_destroy , void , private_mutex_t * this)
Definition at line 153 of file mutex.c.
References free(), mutex, and profiler_cleanup.
 {
     profiler_cleanup(&this->profile);
     pthread_mutex_destroy(&this->mutex);
     free(this);
 }
METHOD (mutex_t , mutex_destroy_r , void , private_r_mutex_t * this)
Definition at line 161 of file mutex.c.
References free(), mutex, and profiler_cleanup.
 {
     profiler_cleanup(&this->generic.profile);
     pthread_mutex_destroy(&this->generic.mutex);
     free(this);
 }
METHOD (condvar_t , wait_ , void , private_condvar_t * this, private_mutex_t * mutex)
Definition at line 218 of file mutex.c.
References cas_ptr(), condvar, private_mutex_t::mutex, private_mutex_t::recursive, private_r_mutex_t::thread, thread_current(), and private_r_mutex_t::times.
 {
     if (mutex->recursive)
     {
         private_r_mutex_t* recursive = (private_r_mutex_t*)mutex;
         thread_t *self = thread_current();
         u_int times;
         /* keep track of the number of times this thread locked the mutex */
         times = recursive->times;
         /* mutex owner gets cleared during condvar wait */
         cas_ptr(&recursive->thread, self, NULL);
         pthread_cond_wait(&this->condvar, &mutex->mutex);
         cas_ptr(&recursive->thread, NULL, self);
         recursive->times = times;
     }
     else
     {
         pthread_cond_wait(&this->condvar, &mutex->mutex);
     }
 }
METHOD (condvar_t , timed_wait_abs , bool , private_condvar_t * this, private_mutex_t * mutex, timeval_t time)
Definition at line 246 of file mutex.c.
References cas_ptr(), condvar, ETIMEDOUT, private_mutex_t::mutex, private_mutex_t::recursive, private_r_mutex_t::thread, thread_current(), and private_r_mutex_t::times.
 {
     struct timespec ts;
     bool timed_out;
     ts.tv_sec = time.tv_sec;
     ts.tv_nsec = time.tv_usec * 1000;
     if (mutex->recursive)
     {
         private_r_mutex_t* recursive = (private_r_mutex_t*)mutex;
         thread_t *self = thread_current();
         u_int times;
         times = recursive->times;
         cas_ptr(&recursive->thread, self, NULL);
         timed_out = pthread_cond_timedwait(&this->condvar, &mutex->mutex,
                                            &ts) == ETIMEDOUT;
         cas_ptr(&recursive->thread, NULL, self);
         recursive->times = times;
     }
     else
     {
         timed_out = pthread_cond_timedwait(&this->condvar, &mutex->mutex,
                                            &ts) == ETIMEDOUT;
     }
     return timed_out;
 }
METHOD (condvar_t , timed_wait , bool , private_condvar_t * this, private_mutex_t * mutex, u_int timeout)
Definition at line 276 of file mutex.c.
References s, time_monotonic(), and timeval_add_ms().
 {
     timeval_t tv;
     u_int s, ms;
     time_monotonic(&tv);
     s = timeout / 1000;
     ms = timeout % 1000;
     tv.tv_sec += s;
     timeval_add_ms(&tv, ms);
     return timed_wait_abs(this, mutex, tv);
 }
METHOD (condvar_t , signal_ , void , private_condvar_t * this)
Definition at line 292 of file mutex.c.
References condvar.
 {
     pthread_cond_signal(&this->condvar);
 }
METHOD (condvar_t , broadcast , void , private_condvar_t * this)
Definition at line 298 of file mutex.c.
References condvar.
 {
     pthread_cond_broadcast(&this->condvar);
 }
METHOD (condvar_t , condvar_destroy , void , private_condvar_t * this)
Definition at line 304 of file mutex.c.
References condvar, and free().
 {
     pthread_cond_destroy(&this->condvar);
     free(this);
 }