strongSwan: imv_os_state.c File Reference
imv_os_state.c File Reference
#include "imv_os_state.h"
#include "imv/imv_lang_string.h"
#include "imv/imv_reason_string.h"
#include "imv/imv_remediation_string.h"
#include "imv/imv_os_info.h"
#include <tncif_policy.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
Classes
struct private_imv_os_state_t
Typedefs
typedef struct
private_imv_os_state_t private_imv_os_state_t
typedef struct package_entry_t package_entry_t
typedef struct entry_t entry_t
typedef struct instruction_entry_t instruction_entry_t
Functions
METHOD (imv_state_t, get_connection_id, TNC_ConnectionID, private_imv_os_state_t *this)
METHOD (imv_state_t, has_long, bool, private_imv_os_state_t *this)
METHOD (imv_state_t, has_excl, bool, private_imv_os_state_t *this)
METHOD (imv_state_t, set_flags, void, private_imv_os_state_t *this, bool has_long, bool has_excl)
METHOD (imv_state_t, set_max_msg_len, void, private_imv_os_state_t *this, uint32_t max_msg_len)
METHOD (imv_state_t, get_max_msg_len, uint32_t, private_imv_os_state_t *this)
METHOD (imv_state_t, set_action_flags, void, private_imv_os_state_t *this, uint32_t flags)
METHOD (imv_state_t, get_action_flags, uint32_t, private_imv_os_state_t *this)
METHOD (imv_state_t, set_session, void, private_imv_os_state_t *this, imv_session_t *session)
METHOD (imv_state_t, get_session, imv_session_t *, private_imv_os_state_t *this)
METHOD (imv_state_t, get_contracts, seg_contract_manager_t *, private_imv_os_state_t *this)
METHOD (imv_state_t, get_recommendation, void, private_imv_os_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
METHOD (imv_state_t, set_recommendation, void, private_imv_os_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, update_recommendation, void, private_imv_os_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, change_state, void, private_imv_os_state_t *this, TNC_ConnectionState new_state)
METHOD (imv_state_t, get_reason_string, bool, private_imv_os_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
METHOD (imv_state_t, get_remediation_instructions, bool, private_imv_os_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
METHOD (imv_state_t, destroy, void, private_imv_os_state_t *this)
METHOD (imv_os_state_t, set_handshake_state, void, private_imv_os_state_t *this, imv_os_handshake_state_t new_state)
METHOD (imv_os_state_t, get_handshake_state, imv_os_handshake_state_t, private_imv_os_state_t *this)
METHOD (imv_os_state_t, set_count, void, private_imv_os_state_t *this, int count, int count_update, int count_blacklist, int count_ok)
METHOD (imv_os_state_t, get_count, void, private_imv_os_state_t *this, int *count, int *count_update, int *count_blacklist, int *count_ok)
METHOD (imv_os_state_t, set_os_settings, void, private_imv_os_state_t *this, u_int settings)
METHOD (imv_os_state_t, get_os_settings, u_int, private_imv_os_state_t *this)
METHOD (imv_os_state_t, set_missing, void, private_imv_os_state_t *this, uint16_t missing)
METHOD (imv_os_state_t, get_missing, uint16_t, private_imv_os_state_t *this)
METHOD (imv_os_state_t, add_bad_package, void, private_imv_os_state_t *this, char *package, os_package_state_t package_state)
imv_state_t * imv_os_state_create (TNC_ConnectionID connection_id)
Variables
static char * languages [] = { "en", "de", "pl" }
static imv_lang_string_t reason_settings []
static imv_lang_string_t reason_packages []
static imv_lang_string_t instr_update_packages_title []
static imv_lang_string_t instr_update_packages_descr []
static imv_lang_string_t instr_update_packages_header []
static imv_lang_string_t instr_remove_packages_title []
static imv_lang_string_t instr_remove_packages_descr []
static imv_lang_string_t instr_remove_packages_header []
static imv_lang_string_t instr_fwd_enabled_title []
static imv_lang_string_t instr_fwd_enabled_descr []
static imv_lang_string_t instr_default_pwd_enabled_title []
static imv_lang_string_t instr_default_pwd_enabled_descr []
static imv_lang_string_t instr_unknown_source_title []
static imv_lang_string_t instr_unknown_source_descr []
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 30 of file imv_os_state.c.
typedef struct instruction_entry_t instruction_entry_t
Definition at line 31 of file imv_os_state.c.
typedef struct package_entry_t package_entry_t
Definition at line 29 of file imv_os_state.c.
typedef struct private_imv_os_state_t private_imv_os_state_t
Definition at line 28 of file imv_os_state.c.
Function Documentation
METHOD (imv_state_t , get_connection_id , TNC_ConnectionID , private_imv_os_state_t * this)
Definition at line 274 of file imv_os_state.c.
 {
     return this->connection_id;
 }
METHOD (imv_state_t , has_long , bool , private_imv_os_state_t * this)
Definition at line 280 of file imv_os_state.c.
 {
     return this->has_long;
 }
METHOD (imv_state_t , has_excl , bool , private_imv_os_state_t * this)
Definition at line 286 of file imv_os_state.c.
 {
     return this->has_excl;
 }
METHOD (imv_state_t , set_flags , void , private_imv_os_state_t * this, bool has_long, bool has_excl)
Definition at line 292 of file imv_os_state.c.
 {
     this->has_long = has_long;
     this->has_excl = has_excl;
 }
METHOD (imv_state_t , set_max_msg_len , void , private_imv_os_state_t * this, uint32_t max_msg_len)
Definition at line 299 of file imv_os_state.c.
 {
     this->max_msg_len = max_msg_len;
 }
METHOD (imv_state_t , get_max_msg_len , uint32_t , private_imv_os_state_t * this)
Definition at line 305 of file imv_os_state.c.
 {
     return this->max_msg_len;
 }
METHOD (imv_state_t , set_action_flags , void , private_imv_os_state_t * this, uint32_t flags)
Definition at line 311 of file imv_os_state.c.
References flags.
 {
     this->action_flags |= flags;
 }
METHOD (imv_state_t , get_action_flags , uint32_t , private_imv_os_state_t * this)
Definition at line 317 of file imv_os_state.c.
 {
     return this->action_flags;
 }
METHOD (imv_state_t , set_session , void , private_imv_os_state_t * this, imv_session_t * session)
Definition at line 323 of file imv_os_state.c.
 {
     this->session = session;
 }
METHOD (imv_state_t , get_session , imv_session_t * , private_imv_os_state_t * this)
Definition at line 329 of file imv_os_state.c.
 {
     return this->session;
 }
METHOD (imv_state_t , get_contracts , seg_contract_manager_t * , private_imv_os_state_t * this)
Definition at line 335 of file imv_os_state.c.
 {
     return this->contracts;
 }
METHOD (imv_state_t , get_recommendation , void , private_imv_os_state_t * this, TNC_IMV_Action_Recommendation * rec, TNC_IMV_Evaluation_Result * eval)
Definition at line 341 of file imv_os_state.c.
 {
     *rec = this->rec;
     *eval = this->eval;
 }
METHOD (imv_state_t , set_recommendation , void , private_imv_os_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 349 of file imv_os_state.c.
 {
     this->rec = rec;
     this->eval = eval;
 }
METHOD (imv_state_t , update_recommendation , void , private_imv_os_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 357 of file imv_os_state.c.
References tncif_policy_update_evaluation(), and tncif_policy_update_recommendation().
 {
     this->rec  = tncif_policy_update_recommendation(this->rec, rec);
     this->eval = tncif_policy_update_evaluation(this->eval, eval);
 }
METHOD (imv_state_t , change_state , void , private_imv_os_state_t * this, TNC_ConnectionState new_state)
Definition at line 365 of file imv_os_state.c.
 {
     this->state = new_state;
 }
METHOD (imv_state_t , get_reason_string , bool , private_imv_os_state_t * this, enumerator_t * language_enumerator, chunk_t * reason_string, char ** reason_language)
Definition at line 371 of file imv_os_state.c.
References countof, DESTROY_IF, FALSE, imv_lang_string_select_lang(), imv_reason_string_create(), languages, and TRUE.
 {
     if (!this->count_update && !this->count_blacklist & !this->os_settings)
     {
         return FALSE;
     }
     *reason_language = imv_lang_string_select_lang(language_enumerator,
                                               languages, countof(languages));
     /* Instantiate a TNC Reason String object */
     DESTROY_IF(this->reason_string);
     this->reason_string = imv_reason_string_create(*reason_language, "\n");
     if (this->count_update || this->count_blacklist)
     {
         this->reason_string->add_reason(this->reason_string, reason_packages);
     }
     if (this->os_settings)
     {
         this->reason_string->add_reason(this->reason_string, reason_settings);
     }
     *reason_string = this->reason_string->get_encoding(this->reason_string);
     return TRUE;
 }
METHOD (imv_state_t , get_remediation_instructions , bool , private_imv_os_state_t * this, enumerator_t * language_enumerator, chunk_t * string, char ** lang_code, char ** uri)
Definition at line 399 of file imv_os_state.c.
References countof, DESTROY_IF, FALSE, settings_t::get_str, imv_os_info_t::get_type, imv_lang_string_select_lang(), imv_remediation_string_create(), languages, lib, library_t::ns, OS_SETTINGS_DEFAULT_PWD_ENABLED, OS_SETTINGS_FWD_ENABLED, OS_SETTINGS_UNKNOWN_SOURCE, OS_TYPE_ANDROID, library_t::settings, and TRUE.
 {
     imv_os_info_t *os_info;
     bool as_xml = FALSE;
     if (!this->count_update && !this->count_blacklist & !this->os_settings)
     {
         return FALSE;
     }
     *lang_code = imv_lang_string_select_lang(language_enumerator,
                                         languages, countof(languages));
     /* Instantiate an IETF Remediation Instructions String object */
     DESTROY_IF(this->remediation_string);
     if (this->session)
     {
         os_info = this->session->get_os_info(this->session);
         as_xml = os_info->get_type(os_info) == OS_TYPE_ANDROID;
     }
     this->remediation_string = imv_remediation_string_create(as_xml, *lang_code);
     /* List of blacklisted packages to be removed, if any */
     if (this->count_blacklist)
     {
         this->remediation_string->add_instruction(this->remediation_string,
                             instr_remove_packages_title,
                             instr_remove_packages_descr,
                             instr_remove_packages_header,
                             this->remove_packages);
     }
     /* List of packages in need of an update, if any */
     if (this->count_update)
     {
         this->remediation_string->add_instruction(this->remediation_string,
                             instr_update_packages_title,
                             instr_update_packages_descr,
                             instr_update_packages_header,
                             this->update_packages);
     }
     /* Add instructions concerning improper OS settings */
     if (this->os_settings & OS_SETTINGS_FWD_ENABLED)
     {
         this->remediation_string->add_instruction(this->remediation_string,
                             instr_fwd_enabled_title,
                             instr_fwd_enabled_descr, NULL, NULL);
     }
     if (this->os_settings & OS_SETTINGS_DEFAULT_PWD_ENABLED)
     {
         this->remediation_string->add_instruction(this->remediation_string,
                             instr_default_pwd_enabled_title,
                             instr_default_pwd_enabled_descr, NULL, NULL);
     }
     if (this->os_settings & OS_SETTINGS_UNKNOWN_SOURCE)
     {
         this->remediation_string->add_instruction(this->remediation_string,
                             instr_unknown_source_title,
                             instr_unknown_source_descr, NULL, NULL);
     }
     *string = this->remediation_string->get_encoding(this->remediation_string);
     *uri = lib->settings->get_str(lib->settings,
                             "%s.plugins.imv-os.remediation_uri", NULL, lib->ns);
     return TRUE;
 }
METHOD (imv_state_t , destroy , void , private_imv_os_state_t * this)
Definition at line 469 of file imv_os_state.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->session);
     DESTROY_IF(this->reason_string);
     DESTROY_IF(this->remediation_string);
     this->contracts->destroy(this->contracts);
     this->update_packages->destroy_function(this->update_packages, free);
     this->remove_packages->destroy_function(this->remove_packages, free);
     free(this);
 }
METHOD (imv_os_state_t , set_handshake_state , void , private_imv_os_state_t * this, imv_os_handshake_state_t new_state)
Definition at line 481 of file imv_os_state.c.
 {
     this->handshake_state = new_state;
 }
METHOD (imv_os_state_t , get_handshake_state , imv_os_handshake_state_t , private_imv_os_state_t * this)
Definition at line 487 of file imv_os_state.c.
 {
     return this->handshake_state;
 }
METHOD (imv_os_state_t , set_count , void , private_imv_os_state_t * this, int count, int count_update, int count_blacklist, int count_ok)
Definition at line 494 of file imv_os_state.c.
References count.
 {
     this->count           += count;
     this->count_update    += count_update;
     this->count_blacklist += count_blacklist;
     this->count_ok        += count_ok;
 }
METHOD (imv_os_state_t , get_count , void , private_imv_os_state_t * this, int * count, int * count_update, int * count_blacklist, int * count_ok)
Definition at line 504 of file imv_os_state.c.
References count.
 {
     if (count)
     {
         *count = this->count;
     }
     if (count_update)
     {
         *count_update = this->count_update;
     }
     if (count_blacklist)
     {
         *count_blacklist = this->count_blacklist;
     }
     if (count_ok)
     {
         *count_ok = this->count_ok;
     }
 }
METHOD (imv_os_state_t , set_os_settings , void , private_imv_os_state_t * this, u_int settings)
Definition at line 526 of file imv_os_state.c.
References settings.
 {
     this->os_settings |= settings;
 }
METHOD (imv_os_state_t , get_os_settings , u_int , private_imv_os_state_t * this)
Definition at line 532 of file imv_os_state.c.
 {
     return this->os_settings;
 }
METHOD (imv_os_state_t , set_missing , void , private_imv_os_state_t * this, uint16_t missing)
Definition at line 538 of file imv_os_state.c.
 {
     this->missing = missing;
 }
METHOD (imv_os_state_t , get_missing , uint16_t , private_imv_os_state_t * this)
Definition at line 544 of file imv_os_state.c.
 {
     return this->missing;
 }
METHOD (imv_os_state_t , add_bad_package , void , private_imv_os_state_t * this, char * package, os_package_state_t package_state)
Definition at line 550 of file imv_os_state.c.
References OS_PACKAGE_STATE_BLACKLIST.
 {
     package = strdup(package);
     if (package_state == OS_PACKAGE_STATE_BLACKLIST)
     {
         this->remove_packages->insert_last(this->remove_packages, package);
     }
     else
     {
         this->update_packages->insert_last(this->update_packages, package);
     }
 }
Variable Documentation
imv_lang_string_t instr_default_pwd_enabled_descr[] static
Initial value:
= {
    { "en", "Please change the default password" },
    { "de", "Bitte ndern Sie das Default Passwort" },
    { "pl", "Prosz zmieni domylne haso" },
    { NULL, NULL }
}
Definition at line 250 of file imv_os_state.c.
imv_lang_string_t instr_default_pwd_enabled_title[] static
Initial value:
= {
    { "en", "Default Password" },
    { "de", "Default Passwort" },
    { "pl", "Haso domylne" },
    { NULL, NULL }
}
Instruction strings for "Default Password Enabled"
Definition at line 243 of file imv_os_state.c.
imv_lang_string_t instr_fwd_enabled_descr[] static
Initial value:
= {
    { "en", "Please disable the forwarding of IP packets" },
    { "de", "Bitte deaktivieren Sie das Forwarding von IP Paketen" },
    { "pl", "Prosz zdezaktywowa przekazywanie pakietw IP" },
    { NULL, NULL }
}
Definition at line 233 of file imv_os_state.c.
imv_lang_string_t instr_fwd_enabled_title[] static
Initial value:
= {
    { "en", "IP Packet Forwarding" },
    { "de", "Weiterleitung von IP Paketen" },
    { "pl", "Przekazywanie pakietw IP" },
    { NULL, NULL }
}
Instruction strings for "Forwarding Enabled"
Definition at line 226 of file imv_os_state.c.
imv_lang_string_t instr_remove_packages_descr[] static
Initial value:
= {
    { "en", "Dangerous software packages were found" },
    { "de", "Gefhrliche Softwarepakete wurden gefunden" },
    { "pl", "Znaleziono niebezpieczne pakiety" },
    { NULL, NULL }
}
Definition at line 209 of file imv_os_state.c.
imv_lang_string_t instr_remove_packages_header[] static
Initial value:
= {
    { "en", "Please remove the following software packages:" },
    { "de", "Bitte entfernen Sie die folgenden Softwarepakete:" },
    { "pl", "Prosz usun nastpujce pakiety:" },
    { NULL, NULL }
}
Definition at line 216 of file imv_os_state.c.
imv_lang_string_t instr_remove_packages_title[] static
Initial value:
= {
    { "en", "Blacklisted Software Packages" },
    { "de", "Gesperrte Softwarepakete" },
    { "pl", "Pakiety bdce na czarnej licie" },
    { NULL, NULL }
}
Instruction strings for "Blacklisted Software Packages"
Definition at line 202 of file imv_os_state.c.
imv_lang_string_t instr_unknown_source_descr[] static
Initial value:
= {
    { "en", "Do not allow the installation of apps from unknown sources" },
    { "de", "Erlauben Sie nicht die Installation von Apps aus unbekannten Quellen" },
    { "pl", "Prosz nie dopuszcza do instalacji Apps z nieznanych rde" },
    { NULL, NULL }
}
Definition at line 267 of file imv_os_state.c.
imv_lang_string_t instr_unknown_source_title[] static
Initial value:
= {
    { "en", "Unknown Software Origin" },
    { "de", "Unbekannte Softwareherkunft" },
    { "pl", "Nieznane pochodzenie softwaru" },
    { NULL, NULL }
}
Instruction strings for "Unknown Source"
Definition at line 260 of file imv_os_state.c.
imv_lang_string_t instr_update_packages_descr[] static
Initial value:
= {
    { "en", "Packages with security vulnerabilities were found" },
    { "de", "Softwarepakete mit Sicherheitsschwachstellen wurden gefunden" },
    { "pl", "Znaleziono pakiety podatne na atak" },
    { NULL, NULL }
}
Definition at line 185 of file imv_os_state.c.
imv_lang_string_t instr_update_packages_header[] static
Initial value:
= {
    { "en", "Please update the following software packages:" },
    { "de", "Bitte updaten Sie die folgenden Softwarepakete:" },
    { "pl", "Prosz zaktualizowa nastpujce pakiety:" },
    { NULL, NULL }
}
Definition at line 192 of file imv_os_state.c.
imv_lang_string_t instr_update_packages_title[] static
Initial value:
= {
    { "en", "Software Security Updates" },
    { "de", "Software Sicherheitsupdates" },
    { "pl", "Aktualizacja softwaru zabezpieczajcego" },
    { NULL, NULL }
}
Instruction strings for "Software Security Updates"
Definition at line 178 of file imv_os_state.c.
char* languages[] = { "en", "de", "pl" } static
Supported languages
Definition at line 153 of file imv_os_state.c.
Referenced by METHOD().
imv_lang_string_t reason_packages[] static
Initial value:
= {
    { "en", "Vulnerable or blacklisted software packages were found" },
    { "de", "Schwachstellenbehaftete oder gesperrte Softwarepakete wurden gefunden" },
    { "pl", "Znaleziono pakiety podatne na atak lub bdce na czarnej licie" },
    { NULL, NULL }
}
Reason strings for "installed software packages"
Definition at line 168 of file imv_os_state.c.
imv_lang_string_t reason_settings[] static
Initial value:
= {
    { "en", "Improper OS settings were detected" },
    { "de", "Unzulssige OS Einstellungen wurden festgestellt" },
    { "pl", "Stwierdzono niewaciwe ustawienia OS" },
    { NULL, NULL }
}
Reason strings for "OS settings"
Definition at line 158 of file imv_os_state.c.