strongSwan: eap_peap
eap_peap
eap_peap
Classes
struct eap_peap_t
Typedefs
typedef struct eap_peap_t eap_peap_t
Functions
eap_peap_t * eap_peap_create_server (identification_t *server, identification_t *peer)
eap_peap_t * eap_peap_create_peer (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_peap_t eap_peap_t
Definition at line 24 of file eap_peap.h.
Function Documentation
eap_peap_t* eap_peap_create_peer (identification_t * server, identification_t * peer)
Creates the EAP method EAP-PEAP acting as peer.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_peap_t object
Definition at line 202 of file eap_peap.c.
References eap_peap_peer_t::application, eap_peap_t::eap_method, eap_peap_create(), eap_peap_create_empty(), eap_peap_peer_create(), FALSE, and private_eap_peap_t::public.
Referenced by METHOD().
 {
     private_eap_peap_t *eap_peap;
     eap_method_t *eap_method;
     eap_peap_peer_t *eap_peap_peer;
     tls_application_t *application;
     /* the tunneled application needs a reference to the outer EAP-PEAP method */
     eap_peap = eap_peap_create_empty();
     eap_method = &eap_peap->public.eap_method;
     eap_peap_peer = eap_peap_peer_create(server, peer, eap_method);
     application = &eap_peap_peer->application;
     return eap_peap_create(eap_peap, server, peer, FALSE, application);
 }
eap_peap_t* eap_peap_create_server (identification_t * server, identification_t * peer)
Creates the EAP method EAP-PEAP acting as server.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_peap_t object
Definition at line 185 of file eap_peap.c.
References eap_peap_server_t::application, eap_peap_t::eap_method, eap_peap_create(), eap_peap_create_empty(), eap_peap_server_create(), private_eap_peap_t::public, and TRUE.
Referenced by METHOD().
 {
     private_eap_peap_t *eap_peap;
     eap_method_t *eap_method;
     eap_peap_server_t *eap_peap_server;
     tls_application_t *application;
     /* the tunneled application needs a reference to the outer EAP-PEAP method */
     eap_peap = eap_peap_create_empty();
     eap_method = &eap_peap->public.eap_method;
     eap_peap_server = eap_peap_server_create(server, peer, eap_method);
     application = &eap_peap_server->application;
     return eap_peap_create(eap_peap, server, peer, TRUE, application);
 }