strongSwan: proposal
proposal
config
Classes
struct proposal_t
Typedefs
typedef enum protocol_id_t protocol_id_t
typedef enum
extended_sequence_numbers_t extended_sequence_numbers_t
typedef struct proposal_t proposal_t
Enumerations
enum protocol_id_t {
PROTO_NONE = 0, PROTO_IKE = 1, PROTO_AH = 2, PROTO_ESP = 3,
PROTO_IPCOMP = 4
}
Functions
proposal_t * proposal_create (protocol_id_t protocol, u_int number)
proposal_t * proposal_create_default (protocol_id_t protocol)
proposal_t * proposal_create_default_aead (protocol_id_t protocol)
proposal_t * proposal_create_from_string (protocol_id_t protocol, const char *algs)
int proposal_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Variables
enum_name_t * protocol_id_names
Detailed Description
Typedef Documentation
typedef enum extended_sequence_numbers_t extended_sequence_numbers_t
Definition at line 25 of file proposal.h.
typedef struct proposal_t proposal_t
Definition at line 26 of file proposal.h.
typedef enum protocol_id_t protocol_id_t
Definition at line 24 of file proposal.h.
Enumeration Type Documentation
enum protocol_id_t
Protocol ID of a proposal.
Enumerator
PROTO_NONE
PROTO_IKE
PROTO_AH
PROTO_ESP
PROTO_IPCOMP
Definition at line 41 of file proposal.h.
                    {
     PROTO_NONE = 0,
     PROTO_IKE = 1,
     PROTO_AH = 2,
     PROTO_ESP = 3,
     PROTO_IPCOMP = 4, /* IKEv1 only */
 };
Function Documentation
proposal_t* proposal_create (protocol_id_t protocol, u_int number)
Create a child proposal for AH, ESP or IKE.
Parameters
protocol protocol, such as PROTO_ESP
number proposal number, as encoded in SA payload
Returns
proposal_t object
Definition at line 601 of file proposal.c.
References array_create(), INIT, and protocol.
Referenced by load_proposals(), METHOD(), process_child_add(), process_ike_add(), proposal_create_default(), proposal_create_default_aead(), and proposal_create_from_string().
 {
     private_proposal_t *this;
     INIT(this,
         .public = {
             .add_algorithm = _add_algorithm,
             .create_enumerator = _create_enumerator,
             .get_algorithm = _get_algorithm,
             .has_dh_group = _has_dh_group,
             .strip_dh = _strip_dh,
             .select = _select_proposal,
             .get_protocol = _get_protocol,
             .set_spi = _set_spi,
             .get_spi = _get_spi,
             .get_number = _get_number,
             .equals = _equals,
             .clone = _clone_,
             .destroy = _destroy,
         },
         .protocol = protocol,
         .number = number,
         .transforms = array_create(sizeof(entry_t), 0),
     );
     return &this->public;
 }
proposal_t* proposal_create_default (protocol_id_t protocol)
Create a default proposal if nothing further specified.
Parameters
protocol protocol, such as PROTO_ESP
Returns
proposal_t object
Definition at line 794 of file proposal.c.
References AUTH_AES_XCBC_96, AUTH_HMAC_MD5_96, AUTH_HMAC_SHA1_96, destroy(), ENCR_3DES, ENCR_AES_CBC, ENCR_BLOWFISH, ENCRYPTION_ALGORITHM, EXTENDED_SEQUENCE_NUMBERS, FALSE, INTEGRITY_ALGORITHM, NO_EXT_SEQ_NUMBERS, proposal_add_supported_ike(), proposal_create(), PROTO_AH, PROTO_ESP, and PROTO_IKE.
Referenced by add_esp_proposals(), add_ike_proposals(), add_proposals(), CALLBACK(), connect_(), create_child_cfg(), create_peer_cfg(), initiate_connection(), load_child_config(), load_ike_config(), medcli_config_create(), medsrv_config_create(), METHOD(), parse_proposal(), and setup_tunnel().
 {
     private_proposal_t *this = (private_proposal_t*)proposal_create(protocol, 0);
     switch (protocol)
     {
         case PROTO_IKE:
             if (!proposal_add_supported_ike(this, FALSE))
             {
                 destroy(this);
                 return NULL;
             }
             break;
         case PROTO_ESP:
             add_algorithm(this, ENCRYPTION_ALGORITHM,   ENCR_AES_CBC,         128);
             add_algorithm(this, ENCRYPTION_ALGORITHM,   ENCR_AES_CBC,         192);
             add_algorithm(this, ENCRYPTION_ALGORITHM,   ENCR_AES_CBC,         256);
             add_algorithm(this, ENCRYPTION_ALGORITHM,   ENCR_3DES,              0);
             add_algorithm(this, ENCRYPTION_ALGORITHM,   ENCR_BLOWFISH,        256);
             add_algorithm(this, INTEGRITY_ALGORITHM,    AUTH_HMAC_SHA1_96,      0);
             add_algorithm(this, INTEGRITY_ALGORITHM,    AUTH_AES_XCBC_96,       0);
             add_algorithm(this, INTEGRITY_ALGORITHM,    AUTH_HMAC_MD5_96,       0);
             add_algorithm(this, EXTENDED_SEQUENCE_NUMBERS, NO_EXT_SEQ_NUMBERS,  0);
             break;
         case PROTO_AH:
             add_algorithm(this, INTEGRITY_ALGORITHM,    AUTH_HMAC_SHA1_96,      0);
             add_algorithm(this, INTEGRITY_ALGORITHM,    AUTH_AES_XCBC_96,       0);
             add_algorithm(this, INTEGRITY_ALGORITHM,    AUTH_HMAC_MD5_96,       0);
             add_algorithm(this, EXTENDED_SEQUENCE_NUMBERS, NO_EXT_SEQ_NUMBERS,  0);
             break;
         default:
             break;
     }
     return &this->public;
 }
proposal_t* proposal_create_default_aead (protocol_id_t protocol)
Create a default proposal for supported AEAD algorithms
Parameters
protocol protocol, such as PROTO_ESP
Returns
proposal_t object, NULL if none supported
Definition at line 833 of file proposal.c.
References destroy(), proposal_add_supported_ike(), proposal_create(), PROTO_AH, PROTO_ESP, PROTO_IKE, and TRUE.
Referenced by add_esp_proposals(), add_ike_proposals(), add_proposals(), CALLBACK(), connect_(), create_child_cfg(), create_peer_cfg(), initiate_connection(), load_child_config(), load_ike_config(), medcli_config_create(), medsrv_config_create(), METHOD(), parse_proposal(), and setup_tunnel().
 {
     private_proposal_t *this;
     switch (protocol)
     {
         case PROTO_IKE:
             this = (private_proposal_t*)proposal_create(protocol, 0);
             if (!proposal_add_supported_ike(this, TRUE))
             {
                 destroy(this);
                 return NULL;
             }
             return &this->public;
         case PROTO_ESP:
             /* we currently don't include any AEAD proposal for ESP, as we
              * don't know if our kernel backend actually supports it. */
             return NULL;
         case PROTO_AH:
         default:
             return NULL;
     }
 }
proposal_t* proposal_create_from_string (protocol_id_t protocol, const char * algs)
Create a proposal from a string identifying the algorithms.
The string is in the same form as a in the ipsec.conf file. E.g.: aes128-sha2_256-modp2048 3des-md5 An additional '!' at the end of the string forces this proposal, without it the peer may choose another algorithm we support.
Parameters
protocol protocol, such as PROTO_ESP
algs algorithms as string
Returns
proposal_t object
Definition at line 860 of file proposal.c.
References add_string_algo(), alg, check_proposal(), enumerator_t::destroy, destroy(), enumerator_t::enumerate, enumerator_create_token(), FALSE, proposal_create(), and TRUE.
Referenced by add_esp_proposals(), add_ike_proposals(), add_proposals(), create_proposal(), load_child_config(), load_ike_config(), load_tester_config_create(), METHOD(), parse_proposal(), and START_TEST().
 {
     private_proposal_t *this;
     enumerator_t *enumerator;
     bool failed = TRUE;
     char *alg;
     this = (private_proposal_t*)proposal_create(protocol, 0);
     /* get all tokens, separated by '-' */
     enumerator = enumerator_create_token(algs, "-", " ");
     while (enumerator->enumerate(enumerator, &alg))
     {
         if (!add_string_algo(this, alg))
         {
             failed = TRUE;
             break;
         }
         failed = FALSE;
     }
     enumerator->destroy(enumerator);
     if (failed)
     {
         destroy(this);
         return NULL;
     }
     check_proposal(this);
     return &this->public;
 }
int proposal_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook function for proposal_t.
Arguments are: proposal_t proposal With the #-specifier, arguments are: linked_list_t *list containing proposal_t
Described in header.
Definition at line 544 of file proposal.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, diffie_hellman_group_names, ENCRYPTION_ALGORITHM, encryption_algorithm_names, enumerator_t::enumerate, EXTENDED_SEQUENCE_NUMBERS, extended_sequence_numbers_names, FALSE, printf_hook_spec_t::hash, INTEGRITY_ALGORITHM, integrity_algorithm_names, list, print_alg(), print_in_hook(), protocol, protocol_id_names, PSEUDO_RANDOM_FUNCTION, pseudo_random_function_names, and TRUE.
Referenced by libcharon_init().
 {
     private_proposal_t *this = *((private_proposal_t**)(args[0]));
     linked_list_t *list = *((linked_list_t**)(args[0]));
     enumerator_t *enumerator;
     size_t written = 0;
     bool first = TRUE;
     if (this == NULL)
     {
         return print_in_hook(data, "(null)");
     }
     if (spec->hash)
     {
         enumerator = list->create_enumerator(list);
         while (enumerator->enumerate(enumerator, &this))
         {   /* call recursivly */
             if (first)
             {
                 written += print_in_hook(data, "%P", this);
                 first = FALSE;
             }
             else
             {
                 written += print_in_hook(data, ", %P", this);
             }
         }
         enumerator->destroy(enumerator);
         return written;
     }
     written = print_in_hook(data, "%N:", protocol_id_names, this->protocol);
     written += print_alg(this, data, ENCRYPTION_ALGORITHM,
                          encryption_algorithm_names, &first);
     written += print_alg(this, data, INTEGRITY_ALGORITHM,
                          integrity_algorithm_names, &first);
     written += print_alg(this, data, PSEUDO_RANDOM_FUNCTION,
                          pseudo_random_function_names, &first);
     written += print_alg(this, data, DIFFIE_HELLMAN_GROUP,
                          diffie_hellman_group_names, &first);
     written += print_alg(this, data, EXTENDED_SEQUENCE_NUMBERS,
                          extended_sequence_numbers_names, &first);
     return written;
 }
Variable Documentation
enum_name_t* protocol_id_names
enum names for protocol_id_t
Referenced by build_payloads(), list_child(), log_child_sa(), METHOD(), process_payloads(), and proposal_printf_hook().