strongSwan: hash_algorithm_set_t Struct Reference
hash_algorithm_set_t Struct Reference
hash_algorithm_set
#include "hash_algorithm_set.h"
Public Attributes
void(* add)(hash_algorithm_set_t *this, hash_algorithm_t alg)
bool(* contains)(hash_algorithm_set_t *this, hash_algorithm_t alg)
int(* count)(hash_algorithm_set_t *this)
enumerator_t *(* create_enumerator)(hash_algorithm_set_t *this)
void(* destroy)(hash_algorithm_set_t *this)
Detailed Description
A set of hash algorithms
Definition at line 32 of file hash_algorithm_set.h.
Member Data Documentation
void(* hash_algorithm_set_t::add)(hash_algorithm_set_t *this, hash_algorithm_t alg)
Add the given algorithm to the set.
Parameters
alg hash algorithm
Definition at line 39 of file hash_algorithm_set.h.
Referenced by send_supported_hash_algorithms().
bool(* hash_algorithm_set_t::contains)(hash_algorithm_set_t *this, hash_algorithm_t alg)
Check if the given algorithm is contained in the set.
Parameters
alg hash algorithm
Returns
TRUE if contained in set
Definition at line 47 of file hash_algorithm_set.h.
int(* hash_algorithm_set_t::count)(hash_algorithm_set_t *this)
Number of hash algorithms contained in the set.
Returns
number of algorithms
Definition at line 54 of file hash_algorithm_set.h.
Referenced by send_supported_hash_algorithms().
enumerator_t*(* hash_algorithm_set_t::create_enumerator)(hash_algorithm_set_t *this)
Enumerate the algorithms contained in the set.
Returns
enumerator over hash_algorithm_t (sorted by identifier)
Definition at line 61 of file hash_algorithm_set.h.
Referenced by send_supported_hash_algorithms().
void(* hash_algorithm_set_t::destroy)(hash_algorithm_set_t *this)
Destroy a hash_algorithm_set_t instance
Definition at line 66 of file hash_algorithm_set.h.
Referenced by send_supported_hash_algorithms().
The documentation for this struct was generated from the following file:
hash_algorithm_set.h