strongSwan: af_alg_signer
af_alg_signer
af_alg
Classes
struct af_alg_signer_t
Macros
#define AF_ALG_SIGNER 14
Typedefs
typedef struct af_alg_signer_t af_alg_signer_t
Functions
af_alg_signer_t * af_alg_signer_create (integrity_algorithm_t algo)
void af_alg_signer_probe (plugin_feature_t *features, int *pos)
Detailed Description
Macro Definition Documentation
#define AF_ALG_SIGNER 14
Number of signers
Definition at line 30 of file af_alg_signer.h.
Referenced by METHOD().
Typedef Documentation
typedef struct af_alg_signer_t af_alg_signer_t
Definition at line 24 of file af_alg_signer.h.
Function Documentation
af_alg_signer_t* af_alg_signer_create (integrity_algorithm_t algo)
Creates a new af_alg_signer_t.
Parameters
algo algorithm to implement
Returns
af_alg_signer_t, NULL if not supported
Definition at line 173 of file af_alg_signer.c.
References af_alg_ops_create(), block_size, free(), INIT, key_size, lookup_alg(), and name.
Referenced by METHOD().
 {
     private_af_alg_signer_t *this;
     size_t block_size, key_size;
     char *name;
     block_size = lookup_alg(algo, &name, &key_size);
     if (!block_size)
     {   /* not supported by kernel */
         return NULL;
     }
     INIT(this,
         .public = {
             .signer = {
                 .get_signature = _get_signature,
                 .allocate_signature = _allocate_signature,
                 .verify_signature = _verify_signature,
                 .get_key_size = _get_key_size,
                 .get_block_size = _get_block_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .ops = af_alg_ops_create("hash", name),
         .block_size = block_size,
         .key_size = key_size,
     );
     if (!this->ops)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }
void af_alg_signer_probe (plugin_feature_t * features, int * pos)
Probe algorithms and return plugin features.
Parameters
features plugin features to create
pos current position in features
See header.
Definition at line 75 of file af_alg_signer.c.
References af_alg_ops_create(), algs, countof, af_alg_ops_t::destroy, name, and PLUGIN_PROVIDE.
Referenced by METHOD().
 {
     af_alg_ops_t *ops;
     int i;
     for (i = 0; i < countof(algs); i++)
     {
         ops = af_alg_ops_create("hash", algs[i].name);
         if (ops)
         {
             ops->destroy(ops);
             features[(*pos)++] = PLUGIN_PROVIDE(SIGNER, algs[i].id);
         }
     }
 }