strongSwan: rwlock
rwlock
threading
Classes
struct rwlock_t
Typedefs
typedef struct rwlock_t rwlock_t
typedef enum rwlock_type_t rwlock_type_t
Enumerations
enum rwlock_type_t { RWLOCK_TYPE_DEFAULT = 0 }
Functions
rwlock_t * rwlock_create (rwlock_type_t type)
Detailed Description
Typedef Documentation
typedef struct rwlock_t rwlock_t
Definition at line 25 of file rwlock.h.
typedef enum rwlock_type_t rwlock_type_t
Definition at line 26 of file rwlock.h.
Enumeration Type Documentation
enum rwlock_type_t
Type of read-write lock.
Enumerator
RWLOCK_TYPE_DEFAULT
default condvar
Definition at line 31 of file rwlock.h.
                    {
     RWLOCK_TYPE_DEFAULT = 0,
 };
Function Documentation
rwlock_t* rwlock_create (rwlock_type_t type)
Create a read-write lock instance.
Parameters
type type of rwlock to create
Returns
unlocked rwlock instance
Definition at line 365 of file rwlock.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, INIT, initialize_is_reader(), mutex_create(), MUTEX_TYPE_DEFAULT, profiler_init, RWLOCK_TYPE_DEFAULT, and thread_value_create().
Referenced by attr_provider_create(), attribute_manager_create(), backend_manager_create(), bus_create(), cancellation_rwcond(), cert_cache_create(), cowfs_create(), cred_encoding_create(), credential_factory_create(), credential_manager_create(), crypto_factory_create(), eap_manager_create(), eap_radius_plugin_create(), farp_listener_create(), fetcher_manager_create(), file_logger_create(), forecast_listener_create(), ike_sa_manager_create(), imc_agent_create(), imv_agent_create(), ipsec_event_relay_create(), ipsec_policy_mgr_create(), ipsec_processor_create(), journal_register(), kernel_libipsec_router_create(), kernel_netlink_net_create(), kernel_pfroute_net_create(), lookip_listener_create(), mem_cred_create(), nm_creds_create(), pkcs11_plugin_create(), proposal_keywords_create(), settings_create_base(), shunt_manager_create(), simaka_manager_create(), socket_dynamic_socket_create(), socket_manager_create(), START_TEST(), stream_manager_create(), stroke_attribute_create(), stroke_ca_create(), stroke_handler_create(), sys_logger_create(), tkm_chunk_map_create(), tkm_cred_create(), tkm_id_manager_create(), tls_cache_create(), tnc_imc_manager_create(), tnc_imv_manager_create(), tnc_pdp_connections_create(), tnc_tnccs_manager_create(), trap_manager_create(), updown_handler_create(), vici_attribute_create(), vici_authority_create(), vici_config_create(), whitelist_listener_create(), and xauth_manager_create().
 {
     pthread_once(&is_reader_initialized,  initialize_is_reader);
     switch (type)
     {
         case RWLOCK_TYPE_DEFAULT:
         default:
         {
             private_rwlock_t *this;
             INIT(this,
                 .public = {
                     .read_lock = _read_lock,
                     .write_lock = _write_lock,
                     .try_write_lock = _try_write_lock,
                     .unlock = _unlock,
                     .destroy = _destroy,
                 },
                 .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
                 .writers = condvar_create(CONDVAR_TYPE_DEFAULT),
                 .readers = condvar_create(CONDVAR_TYPE_DEFAULT),
             );
             profiler_init(&this->profile);
             return &this->public;
         }
     }
 }