strongSwan: eap_identity.c File Reference
eap_identity.c File Reference
#include "eap_identity.h"
#include <daemon.h>
#include <library.h>
Classes
struct private_eap_identity_t
struct eap_identity_header_t
Typedefs
typedef struct
private_eap_identity_t private_eap_identity_t
typedef struct
eap_identity_header_t eap_identity_header_t
Functions
struct eap_identity_header_t __attribute__ ((__packed__))
METHOD (eap_method_t, process_peer, status_t, private_eap_identity_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, initiate_peer, status_t, private_eap_identity_t *this, eap_payload_t **out)
METHOD (eap_method_t, process_server, status_t, private_eap_identity_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, initiate_server, status_t, private_eap_identity_t *this, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_identity_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_identity_t *this, chunk_t *msk)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_identity_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_identity_t *this, u_int8_t identifier)
METHOD (eap_method_t, is_mutual, bool, private_eap_identity_t *this)
METHOD (eap_method_t, destroy, void, private_eap_identity_t *this)
eap_identity_t * eap_identity_create_peer (identification_t *server, identification_t *peer)
eap_identity_t * eap_identity_create_server (identification_t *server, identification_t *peer)
Variables
u_int8_t code
u_int8_t identifier
u_int16_t length
u_int8_t type
u_int8_t data []
Typedef Documentation
typedef struct eap_identity_header_t eap_identity_header_t
Definition at line 49 of file eap_identity.c.
typedef struct private_eap_identity_t private_eap_identity_t
Definition at line 21 of file eap_identity.c.
Function Documentation
METHOD (eap_method_t , process_peer , status_t , private_eap_identity_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 67 of file eap_identity.c.
References chunk_create(), eap_identity_header_t::code, eap_identity_header_t::data, EAP_IDENTITY, eap_payload_create_data(), EAP_RESPONSE, eap_payload_t::get_identifier, id, identifier, eap_identity_header_t::identifier, len, eap_identity_header_t::length, memcpy, SUCCESS, and eap_identity_header_t::type.
 {
     chunk_t id;
     eap_identity_header_t *hdr;
     size_t len;
     id = this->peer->get_encoding(this->peer);
     len = sizeof(eap_identity_header_t) + id.len;
     if (in)
     {
         this->identifier = in->get_identifier(in);
     }
     hdr = alloca(len);
     hdr->code = EAP_RESPONSE;
     hdr->identifier = this->identifier;
     hdr->length = htons(len);
     hdr->type = EAP_IDENTITY;
     memcpy(hdr->data, id.ptr, id.len);
     *out = eap_payload_create_data(chunk_create((u_char*)hdr, len));
     return SUCCESS;
 }
METHOD (eap_method_t , initiate_peer , status_t , private_eap_identity_t * this, eap_payload_t ** out)
Definition at line 91 of file eap_identity.c.
References FAILED.
 {
     /* peer never initiates */
     return FAILED;
 }
METHOD (eap_method_t , process_server , status_t , private_eap_identity_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 98 of file eap_identity.c.
References chunk_clone, chunk_skip(), data, eap_payload_t::get_data, identity, chunk_t::len, and SUCCESS.
 {
     chunk_t data;
     data = chunk_skip(in->get_data(in), 5);
     if (data.len)
     {
         this->identity = chunk_clone(data);
     }
     return SUCCESS;
 }
METHOD (eap_method_t , initiate_server , status_t , private_eap_identity_t * this, eap_payload_t ** out)
Definition at line 111 of file eap_identity.c.
References chunk_create(), eap_identity_header_t::code, EAP_IDENTITY, eap_payload_create_data(), EAP_REQUEST, identifier, eap_identity_header_t::identifier, eap_identity_header_t::length, NEED_MORE, and eap_identity_header_t::type.
 {
     eap_identity_header_t hdr;
     hdr.code = EAP_REQUEST;
     hdr.identifier = this->identifier;
     hdr.length = htons(sizeof(eap_identity_header_t));
     hdr.type = EAP_IDENTITY;
     *out = eap_payload_create_data(chunk_create((u_char*)&hdr,
                                                 sizeof(eap_identity_header_t)));
     return NEED_MORE;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_identity_t * this, u_int32_t * vendor)
Definition at line 126 of file eap_identity.c.
References EAP_IDENTITY.
 {
     *vendor = 0;
     return EAP_IDENTITY;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_identity_t * this, chunk_t * msk)
Definition at line 133 of file eap_identity.c.
References FAILED, identity, and SUCCESS.
 {
     if (this->identity.ptr)
     {
         *msk = this->identity;
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_identity_t * this)
Definition at line 144 of file eap_identity.c.
References identifier.
 {
     return this->identifier;
 }
METHOD (eap_method_t , set_identifier , void , private_eap_identity_t * this, u_int8_t identifier)
Definition at line 150 of file eap_identity.c.
References identifier.
 {
     this->identifier = identifier;
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_identity_t * this)
Definition at line 156 of file eap_identity.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (eap_method_t , destroy , void , private_eap_identity_t * this)
Definition at line 162 of file eap_identity.c.
References free(), and identity.
 {
     this->peer->destroy(this->peer);
     free(this->identity.ptr);
     free(this);
 }
Variable Documentation
u_int8_t code
EAP code (REQUEST/RESPONSE)
Definition at line 41 of file eap_identity.c.
u_int8_t data[]
identity data
Definition at line 49 of file eap_identity.c.
Referenced by METHOD().
u_int8_t identifier
unique message identifier
Definition at line 43 of file eap_identity.c.
Referenced by METHOD().
u_int16_t length
length of whole message
Definition at line 45 of file eap_identity.c.
u_int8_t type
EAP type
Definition at line 47 of file eap_identity.c.