strongSwan: tkm
tkm
Modules
ees callbacks
exception handler
chunk map
credential set
diffie hellman
credential encoder
id manager
kernel ipsec
kernel sad
keymat
listener
nonce generator
private key
public key
spi generator
types
utils
Classes
struct tkm_t
Typedefs
typedef struct tkm_t tkm_t
Functions
bool tkm_init ()
void tkm_deinit ()
Variables
tkm_t * tkm
Detailed Description
Untrusted IKEv2 component used with Trusted Key Manager for IKE disaggregation.
The untrusted IKEv2 component used in conjunction with the Trusted Key Manager infrastructure is implemented as a separate charon instance located in its own directory below the strongSwan top-level source directory (src/charon-tkm). This has the advantage that the TKM code is contained and does not mix with other strongSwan files. The charon-tkm binary startup code is modeled after the charon-nm instance, a special charon daemon variant to be used with the GNOME NetworkManager project. The major difference is the registration of custom TKM plugins as the final step of the startup phase. The charon-tkm daemon does not rely on the dynamic plugin loading mechanism for its core plugins, they are statically registered before entering the main processing loop.
The following diagram shows the main components of the system and how they communicate.
    +------------+            +------------+             +------------+
    | xfrm-proxy |<-[tkm-rpc->| charon-tkm |<-[tkm-rpc]->|    TKM     |
    +------------+            +------------+             +------------+
          ^                                                    ^
 [Netlink | XFRM]                                        [XFRM | Netlink]
          |                                                    v
    +-----------------------------------------------------------------+
    |                            Kernel                               |
    +-----------------------------------------------------------------+
Since the charon-tkm code uses the tkm-rpc library written in Ada, the daemon has to be built using an Ada-aware toolchain. The integration of Ada code into the strongSwan codebase is explained in the TKM documentation, section 5.4.1: http://www.codelabs.ch/tkm#anchor-doc.
The Trusted Key Manager (TKM) is a minimal Trusted Computing Base which implements security-critical functions of the IKEv2 protocol.
The xfrm-proxy receives XFRM Acquire and Expiry events from the kernel and forwards them to the charon-tkm IKE daemon for further processing.
The underlying concept of IKE disaggregation and the design of TKM and all related components, of which charon-tkm is one component, is presented in detail in the project documentation found at http://www.codelabs.ch/tkm#anchor-doc.
Typedef Documentation
typedef struct tkm_t tkm_t
Definition at line 77 of file tkm.h.
Function Documentation
void tkm_deinit ()
Deinitialize trusted key manager, destroys "tkm" instance.
Described in header.
Definition at line 109 of file tkm.c.
References chunk_map(), tkm_id_manager_t::destroy, ees_server_finalize(), free(), and tkm_t::idmgr.
Referenced by main().
 {
     if (!tkm)
     {
         return;
     }
     private_tkm_t *this = (private_tkm_t*)tkm;
     this->public.idmgr->destroy(this->public.idmgr);
     this->public.chunk_map->destroy(this->public.chunk_map);
     this->public.sad->destroy(this->public.sad);
     ees_server_finalize();
     tkmlib_final();
     free(this);
     tkm = NULL;
 }
bool tkm_init ()
Initialize trusted key manager, creates "tkm" instance.
Returns
FALSE if initialization error occurred
Described in header.
Definition at line 52 of file tkm.c.
References DBG1, DBG_DMN, ees_server_finalize(), ees_server_init(), EES_SOCKET, ehandler_init(), FALSE, settings_t::get_str, IKE_SOCKET, INIT, lib, limits, library_t::ns, library_t::settings, tkm_chunk_map_create(), TKM_CTX_AE, TKM_CTX_CC, TKM_CTX_DH, TKM_CTX_ESA, TKM_CTX_ISA, TKM_CTX_NONCE, tkm_id_manager_create(), tkm_kernel_sad_create(), and TRUE.
Referenced by main(), and test_runner_init().
 {
     private_tkm_t *this;
     active_requests_type max_requests;
     char *ikesock, *eessock;
     tkm_limits_t limits;
     /* initialize TKM client library */
     tkmlib_init();
     ehandler_init();
     ikesock = lib->settings->get_str(lib->settings, "%s.ike_socket", IKE_SOCKET,
                                      lib->ns);
     if (ike_init(ikesock) != TKM_OK)
     {
         tkmlib_final();
         return FALSE;
     }
     DBG1(DBG_DMN, "connected to TKM via socket '%s'", ikesock);
     eessock = lib->settings->get_str(lib->settings, "%s.ees_socket", EES_SOCKET,
                                      lib->ns);
     ees_server_init(eessock);
     DBG1(DBG_DMN, "serving EES requests on socket '%s'", eessock);
     if (ike_tkm_reset() != TKM_OK)
     {
         ees_server_finalize();
         tkmlib_final();
         return FALSE;
     }
     /* get limits from tkm */
     if (ike_tkm_limits(&max_requests, &limits[TKM_CTX_NONCE], &limits[TKM_CTX_DH],
                        &limits[TKM_CTX_CC], &limits[TKM_CTX_AE],
                        &limits[TKM_CTX_ISA], &limits[TKM_CTX_ESA]) != TKM_OK)
     {
         ees_server_finalize();
         tkmlib_final();
         return FALSE;
     }
     INIT(this,
         .public = {
             .idmgr = tkm_id_manager_create(limits),
             .chunk_map = tkm_chunk_map_create(),
             .sad = tkm_kernel_sad_create(),
         },
     );
     tkm = &this->public;
     return TRUE;
 }
Variable Documentation
tkm_t* tkm
Trusted key manager instance, set after tkm_init() and before tkm_deinit() calls.
Single instance of tkm_t.
Definition at line 47 of file tkm.c.
Referenced by charon_esa_expire(), METHOD(), START_TEST(), tkm_diffie_hellman_create(), and tkm_keymat_create().