strongSwan: test_ecdsa.c File Reference
test_ecdsa.c File Reference
#include "test_suite.h"
#include <plugins/plugin_feature.h>
Functions
static void test_good_sig (private_key_t *privkey, public_key_t *pubkey)
static void test_bad_sigs (public_key_t *pubkey)
START_TEST (test_gen)
START_TEST (test_load)
END_TEST Suite * ecdsa_suite_create ()
Variables
struct {
int key_size
signature_scheme_t scheme
} schemes []
static chunk_t invalid_sigs []
static int key_sizes []
static END_TEST chunk_t keys []
Function Documentation
END_TEST Suite* ecdsa_suite_create ()
Definition at line 221 of file test_ecdsa.c.
References countof, key_sizes, min, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     int gen_count = countof(key_sizes);
     s = suite_create("ecdsa");
     if (getenv("TESTS_REDUCED_KEYLENGTHS") != NULL)
     {
         gen_count = min(1, gen_count);
     }
     tc = tcase_create("generate");
     tcase_add_loop_test(tc, test_gen, 0, gen_count);
     suite_add_tcase(s, tc);
     tc = tcase_create("load");
     tcase_add_loop_test(tc, test_load, 0, countof(keys));
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_gen)
Definition at line 139 of file test_ecdsa.c.
References BUILD_END, BUILD_KEY_SIZE, ck_assert, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, private_key_t::destroy, public_key_t::destroy, private_key_t::get_public_key, KEY_ECDSA, key_sizes, lib, test_bad_sigs(), and test_good_sig().
 {
     private_key_t *privkey;
     public_key_t *pubkey;
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_ECDSA,
                                  BUILD_KEY_SIZE, key_sizes[_i], BUILD_END);
     ck_assert(privkey != NULL);
     pubkey = privkey->get_public_key(privkey);
     ck_assert(pubkey != NULL);
     test_good_sig(privkey, pubkey);
     test_bad_sigs(pubkey);
     pubkey->destroy(pubkey);
     privkey->destroy(privkey);
 }
START_TEST (test_load)
Definition at line 201 of file test_ecdsa.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, ck_assert, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, private_key_t::destroy, public_key_t::destroy, private_key_t::get_public_key, KEY_ECDSA, lib, test_bad_sigs(), and test_good_sig().
 {
     private_key_t *privkey;
     public_key_t *pubkey;
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_ECDSA,
                                  BUILD_BLOB_ASN1_DER, keys[_i], BUILD_END);
     ck_assert(privkey != NULL);
     pubkey = privkey->get_public_key(privkey);
     ck_assert(pubkey != NULL);
     test_good_sig(privkey, pubkey);
     test_bad_sigs(pubkey);
     pubkey->destroy(pubkey);
     privkey->destroy(privkey);
 }
static void test_bad_sigs (public_key_t * pubkey) static
Check public key that it properly fails against some crafted sigs
Definition at line 104 of file test_ecdsa.c.
References chunk_from_chars, countof, data, fail_if, public_key_t::get_keysize, plugin_loader_t::has_feature, key_size, lib, PLUGIN_PROVIDE, library_t::plugins, s, scheme, schemes, signature_scheme_names, and public_key_t::verify.
Referenced by START_TEST().
 {
     chunk_t data = chunk_from_chars(0x01,0x02,0x03,0xFD,0xFE,0xFF);
     int s, i;
     for (s = 0; s < countof(schemes); s++)
     {
         if (schemes[s].key_size != 0 &&
             schemes[s].scheme != pubkey->get_keysize(pubkey))
         {
             continue;
         }
         if (!lib->plugins->has_feature(lib->plugins,
                         PLUGIN_PROVIDE(PUBKEY_VERIFY, schemes[s].scheme)))
         {
             continue;
         }
         for (i = 0; i < countof(invalid_sigs); i++)
         {
             fail_if(
                 pubkey->verify(pubkey, schemes[s].scheme, data, invalid_sigs[i]),
                 "bad %N sig accepted %B",
                 signature_scheme_names, schemes[s].scheme,
                 &invalid_sigs[i]);
         }
     }
 }
static void test_good_sig (private_key_t * privkey, public_key_t * pubkey) static
Perform a signature verification "good" test having a keypair
Definition at line 41 of file test_ecdsa.c.
References chunk_from_chars, countof, data, fail_unless, free(), private_key_t::get_keysize, plugin_loader_t::has_feature, key_size, lib, PLUGIN_PROVIDE, library_t::plugins, chunk_t::ptr, scheme, schemes, sig, private_key_t::sign, signature_scheme_names, and public_key_t::verify.
Referenced by START_TEST().
 {
     chunk_t sig, data = chunk_from_chars(0x01,0x02,0x03,0xFD,0xFE,0xFF);
     int i;
     for (i = 0; i < countof(schemes); i++)
     {
         if (!lib->plugins->has_feature(lib->plugins,
                         PLUGIN_PROVIDE(PUBKEY_VERIFY, schemes[i].scheme)) ||
             !lib->plugins->has_feature(lib->plugins,
                         PLUGIN_PROVIDE(PRIVKEY_SIGN, schemes[i].scheme)))
         {
             continue;
         }
         if (schemes[i].key_size != 0 &&
             schemes[i].scheme != privkey->get_keysize(privkey))
         {
             continue;
         }
         fail_unless(privkey->sign(privkey, schemes[i].scheme, data, &sig),
                     "sign %N", signature_scheme_names, schemes[i].scheme);
         fail_unless(pubkey->verify(pubkey, schemes[i].scheme, data, sig),
                     "verify %N", signature_scheme_names, schemes[i].scheme);
         free(sig.ptr);
     }
 }
Variable Documentation
chunk_t invalid_sigs[] static
Initial value:
= {
    chunk_from_chars(),
    chunk_from_chars(0x00),
    chunk_from_chars(0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
    chunk_from_chars(0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00),
}
Some special signatures that should never validate successfully
Definition at line 71 of file test_ecdsa.c.
int key_size
Definition at line 25 of file test_ecdsa.c.
Referenced by test_bad_sigs(), and test_good_sig().
int key_sizes[] static
Initial value:
= {
    256, 384, 521,
}
ECDSA key sizes to test
Definition at line 135 of file test_ecdsa.c.
Referenced by ecdsa_suite_create(), and START_TEST().
END_TEST chunk_t keys[] static
Private keys to load
Definition at line 162 of file test_ecdsa.c.
signature_scheme_t scheme
Definition at line 26 of file test_ecdsa.c.
Referenced by test_bad_sigs(), and test_good_sig().
struct { ... } schemes[]
Initial value:
= {
    { 0, SIGN_ECDSA_WITH_SHA1_DER },
    { 0, SIGN_ECDSA_WITH_SHA256_DER },
    { 0, SIGN_ECDSA_WITH_SHA384_DER },
    { 0, SIGN_ECDSA_WITH_SHA512_DER },
    { 0, SIGN_ECDSA_WITH_NULL },
    { 256, SIGN_ECDSA_256 },
    { 384, SIGN_ECDSA_384 },
    { 521, SIGN_ECDSA_521 },
}
Signature schemes to test
Referenced by parse_pubkey_constraints(), select_signature_schemes(), sign_signature_auth(), test_bad_sigs(), and test_good_sig().