strongSwan: asn1_parser_t Struct Reference
asn1_parser_t Struct Reference
asn1_parser
#include "asn1_parser.h"
Public Attributes
bool(* iterate)(asn1_parser_t *this, int *objectID, chunk_t *object)
u_int(* get_level)(asn1_parser_t *this)
void(* set_top_level)(asn1_parser_t *this, u_int level0)
void(* set_flags)(asn1_parser_t *this, bool implicit, bool private)
bool(* success)(asn1_parser_t *this)
void(* destroy)(asn1_parser_t *this)
Detailed Description
Public interface of an ASN.1 parser
Definition at line 62 of file asn1_parser.h.
Member Data Documentation
void(* asn1_parser_t::destroy)(asn1_parser_t *this)
Destroy the ASN.1 parser
Definition at line 107 of file asn1_parser.h.
Referenced by add_certificate(), asn1_parse_algorithmIdentifier(), asn1_parse_time(), bliss_private_key_load(), parse(), parse_attributes(), parse_authenticated_safe(), parse_authorityInfoAccess(), parse_basicConstraints(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_certificatePolicies(), parse_contentInfo(), parse_digest_info(), parse_ecdsa_public_key(), parse_encrypted_private_key(), parse_extendedKeyUsage(), parse_extension_request(), parse_generalName(), parse_groups(), parse_ipAddrBlocks(), parse_nameConstraints(), parse_OCSPResponse(), parse_otherName(), parse_pbes1_params(), parse_pbes2_params(), parse_pbkdf2_params(), parse_PFX(), parse_policyConstraints(), parse_policyMappings(), parse_private_key(), parse_public_key(), parse_responses(), parse_roleSyntax(), parse_rsa_private_key(), parse_rsa_public_key(), parse_safe_contents(), parse_singleResponse(), run_parser_test(), START_TEST(), verify_emsa_pkcs1_signature(), x509_parse_authorityKeyIdentifier(), x509_parse_crlDistributionPoints(), and x509_parse_generalNames().
u_int(* asn1_parser_t::get_level)(asn1_parser_t *this)
Get the current parsing level
Returns
current level
Definition at line 80 of file asn1_parser.h.
Referenced by add_certificate(), parse(), parse_authenticated_safe(), parse_authorityInfoAccess(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_digest_info(), parse_encrypted_private_key(), parse_extension_request(), parse_generalName(), parse_nameConstraints(), parse_OCSPResponse(), parse_otherName(), parse_pbes2_params(), parse_PFX(), parse_private_key(), parse_public_key(), parse_responses(), parse_safe_contents(), parse_singleResponse(), verify_emsa_pkcs1_signature(), x509_parse_crlDistributionPoints(), and x509_parse_generalNames().
bool(* asn1_parser_t::iterate)(asn1_parser_t *this, int *objectID, chunk_t *object)
Parse the next ASN.1 object in the hierarchy and return it
Parameters
objectID current line in the object syntax definition
object current object
Returns
- FALSE if end of object syntax definition was reached or a parsing error occurred
TRUE otherwise
Definition at line 73 of file asn1_parser.h.
Referenced by add_certificate(), asn1_parse_algorithmIdentifier(), asn1_parse_time(), bliss_private_key_load(), parse(), parse_attributes(), parse_authenticated_safe(), parse_authorityInfoAccess(), parse_basicConstraints(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_certificatePolicies(), parse_contentInfo(), parse_digest_info(), parse_ecdsa_public_key(), parse_encrypted_private_key(), parse_extendedKeyUsage(), parse_extension_request(), parse_generalName(), parse_groups(), parse_ipAddrBlocks(), parse_nameConstraints(), parse_OCSPResponse(), parse_otherName(), parse_pbes1_params(), parse_pbes2_params(), parse_pbkdf2_params(), parse_PFX(), parse_policyConstraints(), parse_policyMappings(), parse_private_key(), parse_public_key(), parse_responses(), parse_roleSyntax(), parse_rsa_private_key(), parse_rsa_public_key(), parse_safe_contents(), parse_singleResponse(), run_parser_test(), START_TEST(), verify_emsa_pkcs1_signature(), x509_parse_authorityKeyIdentifier(), x509_parse_crlDistributionPoints(), and x509_parse_generalNames().
void(* asn1_parser_t::set_flags)(asn1_parser_t *this, bool implicit, bool private)
Set implicit and private flags
Parameters
implicit top-most type of object is implicit
private object data is private (use debug level 4)
Definition at line 95 of file asn1_parser.h.
Referenced by bliss_private_key_load(), parse_private_key(), parse_rsa_private_key(), and x509_parse_generalNames().
void(* asn1_parser_t::set_top_level)(asn1_parser_t *this, u_int level0)
Set the top-most level
Parameters
level top-most level
Definition at line 87 of file asn1_parser.h.
Referenced by add_certificate(), asn1_parse_algorithmIdentifier(), asn1_parse_time(), parse(), parse_attributes(), parse_authorityInfoAccess(), parse_basicConstraints(), parse_basicOCSPResponse(), parse_certificatePolicies(), parse_contentInfo(), parse_digest_info(), parse_extendedKeyUsage(), parse_extension_request(), parse_generalName(), parse_groups(), parse_ipAddrBlocks(), parse_nameConstraints(), parse_otherName(), parse_pbes1_params(), parse_pbes2_params(), parse_pbkdf2_params(), parse_policyConstraints(), parse_policyMappings(), parse_responses(), parse_roleSyntax(), parse_safe_contents(), parse_singleResponse(), x509_parse_authorityKeyIdentifier(), x509_parse_crlDistributionPoints(), and x509_parse_generalNames().
bool(* asn1_parser_t::success)(asn1_parser_t *this)
Show final parsing status
Returns
TRUE if parsing was successful, FALSE otherwise
Definition at line 102 of file asn1_parser.h.
Referenced by add_certificate(), bliss_private_key_load(), parse(), parse_attributes(), parse_authenticated_safe(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_contentInfo(), parse_digest_info(), parse_ecdsa_public_key(), parse_extension_request(), parse_groups(), parse_OCSPResponse(), parse_otherName(), parse_pbes1_params(), parse_pbes2_params(), parse_pbkdf2_params(), parse_PFX(), parse_responses(), parse_rsa_private_key(), parse_rsa_public_key(), parse_safe_contents(), parse_singleResponse(), run_parser_test(), START_TEST(), and verify_emsa_pkcs1_signature().
The documentation for this struct was generated from the following file:
asn1_parser.h