strongSwan: gateway.c File Reference
gateway.c File Reference
#include "gateway.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
#include <string.h>
#include <sys/un.h>
#include <xml.h>
Classes
struct private_gateway_t
Typedefs
typedef struct private_gateway_t private_gateway_t
Functions
static bool connect_ (private_gateway_t *this)
METHOD (gateway_t, request, char *, private_gateway_t *this, char *xml,...)
METHOD (gateway_t, query_ikesalist, enumerator_t *, private_gateway_t *this)
METHOD (gateway_t, query_configlist, enumerator_t *, private_gateway_t *this)
static enumerator_t * read_result (private_gateway_t *this, char *res)
METHOD (gateway_t, initiate, enumerator_t *, private_gateway_t *this, bool ike, char *name)
METHOD (gateway_t, terminate, enumerator_t *, private_gateway_t *this, bool ike, u_int32_t id)
METHOD (gateway_t, destroy, void, private_gateway_t *this)
static private_gateway_t * gateway_create (char *name)
gateway_t * gateway_create_tcp (char *name, host_t *host)
gateway_t * gateway_create_unix (char *name)
Variables
struct sockaddr_un unix_addr = { AF_UNIX, IPSEC_PIDDIR "/charon.xml"}
Typedef Documentation
typedef struct private_gateway_t private_gateway_t
Definition at line 27 of file gateway.c.
Function Documentation
static bool connect_ (private_gateway_t * this) static
establish connection to gateway
Definition at line 65 of file gateway.c.
References addr, close, connect, FALSE, family, host, len, socket, TRUE, and unix_addr.
Referenced by METHOD().
 {
     int family, len;
     struct sockaddr *addr;
     if (this->fd >= 0)
     {
         close(this->fd);
     }
     if (this->host)
     {
         family = AF_INET;
         addr = this->host->get_sockaddr(this->host);
         len = *this->host->get_sockaddr_len(this->host);
     }
     else
     {
         family = AF_UNIX;
         addr = (struct sockaddr*)&unix_addr;
         len = sizeof(unix_addr);
     }
     this->fd = socket(family, SOCK_STREAM, 0);
     if (this->fd < 0)
     {
         return FALSE;
     }
     if (connect(this->fd, addr, len) != 0)
     {
         close(this->fd);
         this->fd = -1;
         return FALSE;
     }
     return TRUE;
 }
static private_gateway_t* gateway_create (char * name) static
generic constructor
Definition at line 355 of file gateway.c.
References INIT, and strdup.
Referenced by gateway_create_tcp(), and gateway_create_unix().
 {
     private_gateway_t *this;
     INIT(this,
         .public = {
             .request = _request,
             .query_ikesalist = _query_ikesalist,
             .query_configlist = _query_configlist,
             .initiate = _initiate,
             .terminate = _terminate,
             .destroy = _destroy,
         },
         .name = strdup(name),
         .fd = -1,
         .xmlid = 1,
     );
     return this;
 }
METHOD (gateway_t , request , char * , private_gateway_t * this, char * xml, ...)
Definition at line 101 of file gateway.c.
References connect_(), len, recv, send, strdup, TRUE, and vsnprintf.
 {
     if (this->fd < 0)
     {
         if (!connect_(this))
         {
             return NULL;
         }
     }
     while (TRUE)
     {
         char buf[8096];
         ssize_t len;
         va_list args;
         va_start(args, xml);
         len = vsnprintf(buf, sizeof(buf), xml, args);
         va_end(args);
         if (len < 0 || len >= sizeof(buf))
         {
             return NULL;
         }
         if (send(this->fd, buf, len, 0) != len)
         {
             if (!connect_(this))
             {
                 return NULL;
             }
             continue;
         }
         len = recv(this->fd, buf, sizeof(buf) - 1, 0);
         if (len <= 0)
         {
             if (!connect_(this))
             {
                 return NULL;
             }
             continue;
         }
         buf[len] = 0;
         return strdup(buf);
     }
 }
METHOD (gateway_t , query_ikesalist , enumerator_t * , private_gateway_t * this)
Definition at line 146 of file gateway.c.
References xml_t::children, enumerator_t::destroy, enumerator_t::enumerate, free(), name, request(), str, streq(), value, and xml_create().
 {
     char *str, *name, *value;
     xml_t *xml;
     enumerator_t *e1, *e2, *e3, *e4 = NULL;
     str = request(this, "<message type=\"request\" id=\"%d\">"
                             "<query>"
                                 "<ikesalist/>"
                             "</query>"
                         "</message>", this->xmlid++);
     if (str == NULL)
     {
         return NULL;
     }
     xml = xml_create(str);
     if (xml == NULL)
     {
         return NULL;
     }
     e1 = xml->children(xml);
     free(str);
     while (e1->enumerate(e1, &xml, &name, &value))
     {
         if (streq(name, "message"))
         {
             e2 = xml->children(xml);
             while (e2->enumerate(e2, &xml, &name, &value))
             {
                 if (streq(name, "query"))
                 {
                     e3 = xml->children(xml);
                     while (e3->enumerate(e3, &xml, &name, &value))
                     {
                         if (streq(name, "ikesalist"))
{
                             e4 = xml->children(xml);
                             e1->destroy(e1);
                             e2->destroy(e2);
                             e3->destroy(e3);
                             return e4;
                         }
                     }
                     e3->destroy(e3);
                 }
             }
             e2->destroy(e2);
         }
     }
     e1->destroy(e1);
     return NULL;
 }
METHOD (gateway_t , query_configlist , enumerator_t * , private_gateway_t * this)
Definition at line 201 of file gateway.c.
References xml_t::children, enumerator_t::destroy, enumerator_t::enumerate, free(), name, request(), str, streq(), value, and xml_create().
 {
     char *str, *name, *value;
     xml_t *xml;
     enumerator_t *e1, *e2, *e3, *e4 = NULL;
     str = request(this, "<message type=\"request\" id=\"%d\">"
                             "<query>"
                                 "<configlist/>"
                             "</query>"
                         "</message>", this->xmlid++);
     if (str == NULL)
     {
         return NULL;
     }
     xml = xml_create(str);
     if (xml == NULL)
     {
         return NULL;
     }
     e1 = xml->children(xml);
     free(str);
     while (e1->enumerate(e1, &xml, &name, &value))
     {
         if (streq(name, "message"))
         {
             e2 = xml->children(xml);
             while (e2->enumerate(e2, &xml, &name, &value))
             {
                 if (streq(name, "query"))
                 {
                     e3 = xml->children(xml);
                     while (e3->enumerate(e3, &xml, &name, &value))
                     {
                         if (streq(name, "configlist"))
{
                             e4 = xml->children(xml);
                             e1->destroy(e1);
                             e2->destroy(e2);
                             e3->destroy(e3);
                             return e4;
                         }
                     }
                     e3->destroy(e3);
                 }
             }
             e2->destroy(e2);
         }
     }
     e1->destroy(e1);
     return NULL;
 }
METHOD (gateway_t , initiate , enumerator_t * , private_gateway_t * this, bool ike, char * name)
Definition at line 298 of file gateway.c.
References read_result(), request(), and str.
 {
     char *str, *kind;
     if (ike)
     {
         kind = "ike";
     }
     else
     {
         kind = "child";
     }
     str = request(this, "<message type=\"request\" id=\"%d\">"
                             "<control>"
                                 "<%ssainitiate>%s</%ssainitiate>"
                             "</control>"
                         "</message>", this->xmlid++, kind, name, kind);
     return read_result(this, str);
 }
METHOD (gateway_t , terminate , enumerator_t * , private_gateway_t * this, bool ike, u_int32_t id)
Definition at line 319 of file gateway.c.
References read_result(), request(), and str.
 {
     char *str, *kind;
     if (ike)
     {
         kind = "ike";
     }
     else
     {
         kind = "child";
     }
     str = request(this, "<message type=\"request\" id=\"%d\">"
                             "<control>"
                                 "<%ssaterminate>%d</%ssaterminate>"
                             "</control>"
                         "</message>", this->xmlid++, kind, id, kind);
     return read_result(this, str);
 }
METHOD (gateway_t , destroy , void , private_gateway_t * this)
Definition at line 340 of file gateway.c.
References close, free(), host, and name.
 {
     if (this->fd >= 0)
     {
         close(this->fd);
     }
     if (this->host) this->host->destroy(this->host);
     free(this->name);
     free(this);
 }
static enumerator_t* read_result (private_gateway_t * this, char * res) static
create enumerator over control elements children of a control response
Definition at line 259 of file gateway.c.
References xml_t::children, enumerator_t::destroy, enumerator_t::enumerate, free(), name, streq(), value, and xml_create().
Referenced by METHOD().
 {
     char *name, *value;
     xml_t *xml;
     enumerator_t *e1, *e2, *e3;
     if (res == NULL)
     {
         return NULL;
     }
     xml = xml_create(res);
     if (xml == NULL)
     {
         return NULL;
     }
     e1 = xml->children(xml);
     free(res);
     while (e1->enumerate(e1, &xml, &name, &value))
     {
         if (streq(name, "message"))
         {
             e2 = xml->children(xml);
             while (e2->enumerate(e2, &xml, &name, &value))
             {
                 if (streq(name, "control"))
                 {
                     e3 = xml->children(xml);
                     e1->destroy(e1);
                     e2->destroy(e2);
                     return e3;
                 }
             }
             e2->destroy(e2);
         }
     }
     e1->destroy(e1);
     return NULL;
 }
Variable Documentation
struct sockaddr_un unix_addr = { AF_UNIX, IPSEC_PIDDIR "/charon.xml"}
Definition at line 60 of file gateway.c.
Referenced by connect_().