strongSwan: stroke_ca.c File Reference
stroke_ca.c File Reference
#include "stroke_ca.h"
#include "stroke_cred.h"
#include <threading/rwlock.h>
#include <collections/linked_list.h>
#include <crypto/hashers/hasher.h>
#include <daemon.h>
Classes
struct private_stroke_ca_t
struct ca_section_t
struct ca_cert_t
struct cert_data_t
struct cdp_data_t
Typedefs
typedef struct private_stroke_ca_t private_stroke_ca_t
typedef struct ca_section_t ca_section_t
typedef struct ca_cert_t ca_cert_t
Functions
certificate_t * stroke_load_ca_cert (char *filename)
static ca_section_t * ca_section_create (char *name, char *path)
static void ca_section_destroy (ca_section_t *this)
static void ca_cert_destroy (ca_cert_t *this)
static void cert_data_destroy (cert_data_t *data)
static bool certs_filter (cert_data_t *data, ca_cert_t **in, certificate_t **out)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_stroke_ca_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
static void cdp_data_destroy (cdp_data_t *data)
static enumerator_t * create_inner_cdp (ca_section_t *section, cdp_data_t *data)
static enumerator_t * create_inner_cdp_hashandurl (ca_section_t *section, cdp_data_t *data)
METHOD (credential_set_t, create_cdp_enumerator, enumerator_t *, private_stroke_ca_t *this, certificate_type_t type, identification_t *id)
static bool match_cert (ca_cert_t *item, certificate_t *cert)
static bool remove_auto_certs (ca_cert_t *item, void *not_used)
static bool remove_cert (ca_cert_t *item, certificate_t *cert)
static certificate_t * add_cert_internal (private_stroke_ca_t *this, certificate_t *cert, bool automatic)
METHOD (stroke_ca_t, add, void, private_stroke_ca_t *this, stroke_msg_t *msg)
METHOD (stroke_ca_t, del, void, private_stroke_ca_t *this, stroke_msg_t *msg)
METHOD (stroke_ca_t, get_cert_ref, certificate_t *, private_stroke_ca_t *this, certificate_t *cert)
METHOD (stroke_ca_t, reload_certs, void, private_stroke_ca_t *this)
METHOD (stroke_ca_t, replace_certs, void, private_stroke_ca_t *this, mem_cred_t *certs)
static void list_uris (linked_list_t *list, char *label, FILE *out)
METHOD (stroke_ca_t, check_for_hash_and_url, void, private_stroke_ca_t *this, certificate_t *cert)
METHOD (stroke_ca_t, list, void, private_stroke_ca_t *this, stroke_msg_t *msg, FILE *out)
METHOD (stroke_ca_t, destroy, void, private_stroke_ca_t *this)
stroke_ca_t * stroke_ca_create ()
Typedef Documentation
typedef struct ca_cert_t ca_cert_t
Definition at line 28 of file stroke_ca.c.
typedef struct ca_section_t ca_section_t
Definition at line 27 of file stroke_ca.c.
typedef struct private_stroke_ca_t private_stroke_ca_t
Definition at line 26 of file stroke_ca.c.
Function Documentation
static certificate_t* add_cert_internal (private_stroke_ca_t * this, certificate_t * cert, bool automatic) static
Adds a certificate to the certificate store
Definition at line 403 of file stroke_ca.c.
References ca_cert_t::automatic, ca_cert_t::cert, cert, ca_cert_t::count, certificate_t::destroy, found, certificate_t::get_ref, INIT, match_cert(), SUCCESS, and TRUE.
Referenced by METHOD().
 {
     ca_cert_t *found;
     if (this->certs->find_first(this->certs, (linked_list_match_t)match_cert,
                                 (void**)&found, cert) == SUCCESS)
     {
         cert->destroy(cert);
         cert = found->cert->get_ref(found->cert);
     }
     else
     {
         INIT(found,
             .cert = cert->get_ref(cert)
         );
         this->certs->insert_first(this->certs, found);
     }
     if (automatic)
     {
         found->automatic = TRUE;
     }
     else
     {
         found->count++;
     }
     return cert;
 }
static void ca_cert_destroy (ca_cert_t * this) static
Destroy a ca cert entry
Definition at line 158 of file stroke_ca.c.
References cert, and free().
Referenced by METHOD(), remove_auto_certs(), and remove_cert().
 {
     this->cert->destroy(this->cert);
     free(this);
 }
static ca_section_t* ca_section_create (char * name, char * path) static
create a new CA section
Definition at line 127 of file stroke_ca.c.
References ca_section_t::certuribase, ca_section_t::crl, ca_section_t::hashes, linked_list_create(), malloc_thing, ca_section_t::name, ca_section_t::ocsp, ca_section_t::path, and strdup.
Referenced by METHOD().
 {
     ca_section_t *ca = malloc_thing(ca_section_t);
     ca->name = strdup(name);
     ca->path = strdup(path);
     ca->crl = linked_list_create();
     ca->ocsp = linked_list_create();
     ca->hashes = linked_list_create();
     ca->certuribase = NULL;
     return ca;
 }
static void ca_section_destroy (ca_section_t * this) static
destroy a ca section entry
Definition at line 143 of file stroke_ca.c.
References cert, destroy(), free(), name, and path.
Referenced by METHOD().
 {
     this->crl->destroy_function(this->crl, free);
     this->ocsp->destroy_function(this->ocsp, free);
     this->hashes->destroy_offset(this->hashes, offsetof(identification_t, destroy));
     this->cert->destroy(this->cert);
     free(this->certuribase);
     free(this->path);
     free(this->name);
     free(this);
 }
static void cdp_data_destroy (cdp_data_t * data) static
destroy cdp enumerator data and unlock list
Definition at line 254 of file stroke_ca.c.
References free(), private_stroke_ca_t::lock, cdp_data_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static void cert_data_destroy (cert_data_t * data) static
destroy cert_data
Definition at line 177 of file stroke_ca.c.
References free(), private_nm_creds_t::lock, cert_data_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static bool certs_filter (cert_data_t * data, ca_cert_t ** in, certificate_t ** out) static
filter function for certs enumerator
Definition at line 186 of file stroke_ca.c.
References cert, cert_data_t::cert, CERT_ANY, public_key_t::destroy, FALSE, identification_t::get_encoding, certificate_t::get_public_key, certificate_t::get_type, certificate_t::has_subject, cert_data_t::id, cert_data_t::key, KEY_ANY, public, and TRUE.
Referenced by METHOD().
 {
     public_key_t *public;
     certificate_t *cert = (*in)->cert;
     if (data->cert == CERT_ANY || data->cert == cert->get_type(cert))
     {
         public = cert->get_public_key(cert);
         if (public)
         {
             if (data->key == KEY_ANY || data->key == public->get_type(public))
             {
                 if (data->id && public->has_fingerprint(public,
                                             data->id->get_encoding(data->id)))
                 {
                     public->destroy(public);
                     *out = cert;
                     return TRUE;
                 }
             }
             public->destroy(public);
         }
         else if (data->key != KEY_ANY)
         {
             return FALSE;
         }
         if (data->id == NULL || cert->has_subject(cert, data->id))
         {
             *out = cert;
             return TRUE;
         }
     }
     return FALSE;
 }
static enumerator_t* create_inner_cdp (ca_section_t * section, cdp_data_t * data) static
inner enumerator constructor for CDP URIs
Definition at line 263 of file stroke_ca.c.
References ca_section_t::cert, CERT_X509_OCSP_RESPONSE, linked_list_t::create_enumerator, ca_section_t::crl, enumerator_t::destroy, identification_t::get_encoding, certificate_t::get_public_key, cdp_data_t::id, list, ca_section_t::ocsp, public, and cdp_data_t::type.
Referenced by METHOD().
 {
     public_key_t *public;
     enumerator_t *enumerator = NULL;
     linked_list_t *list;
     if (data->type == CERT_X509_OCSP_RESPONSE)
     {
         list = section->ocsp;
     }
     else
     {
         list = section->crl;
     }
     public = section->cert->get_public_key(section->cert);
     if (public)
     {
         if (!data->id)
         {
             enumerator = list->create_enumerator(list);
         }
         else
         {
             if (public->has_fingerprint(public, data->id->get_encoding(data->id)))
             {
                 enumerator = list->create_enumerator(list);
             }
         }
         public->destroy(public);
     }
     return enumerator;
 }
static enumerator_t* create_inner_cdp_hashandurl (ca_section_t * section, cdp_data_t * data) static
inner enumerator constructor for "Hash and URL"
Definition at line 300 of file stroke_ca.c.
References ca_section_t::certuribase, chunk_to_hex(), linked_list_t::create_enumerator, enumerator_create_single(), FALSE, free(), identification_t::get_encoding, hash, ca_section_t::hashes, cdp_data_t::id, malloc(), and identification_t::matches.
Referenced by METHOD().
 {
     enumerator_t *enumerator = NULL, *hash_enum;
     identification_t *current;
     if (!data->id || !section->certuribase)
     {
         return NULL;
     }
     hash_enum = section->hashes->create_enumerator(section->hashes);
     while (hash_enum->enumerate(hash_enum, &current))
     {
         if (current->matches(current, data->id))
         {
             char *url, *hash;
             url = malloc(strlen(section->certuribase) + 40 + 1);
             strcpy(url, section->certuribase);
             hash = chunk_to_hex(current->get_encoding(current), NULL, FALSE).ptr;
             strncat(url, hash, 40);
             free(hash);
             enumerator = enumerator_create_single(url, free);
             break;
         }
     }
     hash_enum->destroy(hash_enum);
     return enumerator;
 }
static void list_uris (linked_list_t * list, char * label, FILE * out) static
list crl or ocsp URIs
Definition at line 593 of file stroke_ca.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, fprintf, TRUE, and uri.
Referenced by METHOD().
 {
     bool first = TRUE;
     char *uri;
     enumerator_t *enumerator;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, (void**)&uri))
     {
         if (first)
         {
             fprintf(out, "%s", label);
             first = FALSE;
         }
         else
         {
             fprintf(out, "            ");
         }
         fprintf(out, "'%s'\n", uri);
     }
     enumerator->destroy(enumerator);
 }
static bool match_cert (ca_cert_t * item, certificate_t * cert) static
Compare the given certificate to the ca_cert_t items in the list
Definition at line 360 of file stroke_ca.c.
References ca_cert_t::cert, and certificate_t::equals.
Referenced by add_cert_internal(), and METHOD().
 {
     return cert->equals(cert, item->cert);
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_stroke_ca_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 222 of file stroke_ca.c.
References cert_data_destroy(), certs_filter(), data, enumerator_create_filter(), INIT, and lock.
 {
     enumerator_t *enumerator;
     cert_data_t *data;
     INIT(data,
         .this = this,
         .cert = cert,
         .key = key,
         .id = id,
     );
     this->lock->read_lock(this->lock);
     enumerator = this->certs->create_enumerator(this->certs);
     return enumerator_create_filter(enumerator, (void*)certs_filter, data,
                                     (void*)cert_data_destroy);
 }
METHOD (credential_set_t , create_cdp_enumerator , enumerator_t * , private_stroke_ca_t * this, certificate_type_t type, identification_t * id)
Definition at line 331 of file stroke_ca.c.
References cdp_data_destroy(), CERT_ANY, CERT_X509, CERT_X509_CRL, CERT_X509_OCSP_RESPONSE, create_inner_cdp(), create_inner_cdp_hashandurl(), data, enumerator_create_nested(), id, cdp_data_t::id, lock, malloc_thing, cdp_data_t::this, type, and cdp_data_t::type.
 {
     cdp_data_t *data;
     switch (type)
     {   /* we serve CRLs, OCSP responders and URLs for "Hash and URL" */
         case CERT_X509:
         case CERT_X509_CRL:
         case CERT_X509_OCSP_RESPONSE:
         case CERT_ANY:
             break;
         default:
             return NULL;
     }
     data = malloc_thing(cdp_data_t);
     data->this = this;
     data->type = type;
     data->id = id;
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(this->sections->create_enumerator(this->sections),
             (type == CERT_X509) ? (void*)create_inner_cdp_hashandurl : (void*)create_inner_cdp,
             data, (void*)cdp_data_destroy);
 }
METHOD (stroke_ca_t , add , void , private_stroke_ca_t * this, stroke_msg_t * msg)
Definition at line 432 of file stroke_ca.c.
References stroke_msg_t::add_ca, add_cert_internal(), ca_section_create(), ca_section_t::cert, cert, ca_section_t::certuribase, ca_section_t::crl, DBG1, DBG_CFG, FALSE, linked_list_t::insert_last, lock, ca_section_t::ocsp, strdup, stroke_load_ca_cert(), and spinlock_t::unlock.
 {
     certificate_t *cert;
     ca_section_t *ca;
     if (msg->add_ca.cacert == NULL)
     {
         DBG1(DBG_CFG, "missing cacert parameter");
         return;
     }
     cert = stroke_load_ca_cert(msg->add_ca.cacert);
     if (cert)
     {
         ca = ca_section_create(msg->add_ca.name, msg->add_ca.cacert);
         if (msg->add_ca.crluri)
         {
             ca->crl->insert_last(ca->crl, strdup(msg->add_ca.crluri));
         }
         if (msg->add_ca.crluri2)
         {
             ca->crl->insert_last(ca->crl, strdup(msg->add_ca.crluri2));
         }
         if (msg->add_ca.ocspuri)
         {
             ca->ocsp->insert_last(ca->ocsp, strdup(msg->add_ca.ocspuri));
         }
         if (msg->add_ca.ocspuri2)
         {
             ca->ocsp->insert_last(ca->ocsp, strdup(msg->add_ca.ocspuri2));
         }
         if (msg->add_ca.certuribase)
         {
             ca->certuribase = strdup(msg->add_ca.certuribase);
         }
         this->lock->write_lock(this->lock);
         ca->cert = add_cert_internal(this, cert, FALSE);
         this->sections->insert_last(this->sections, ca);
         this->lock->unlock(this->lock);
         DBG1(DBG_CFG, "added ca '%s'", msg->add_ca.name);
     }
 }
METHOD (stroke_ca_t , del , void , private_stroke_ca_t * this, stroke_msg_t * msg)
Definition at line 475 of file stroke_ca.c.
References ca_section_destroy(), ca_section_t::cert, CERT_ANY, library_t::credmgr, DBG1, DBG_CFG, stroke_msg_t::del_ca, enumerator_t::destroy, enumerator_t::enumerate, credential_manager_t::flush_cache, lib, lock, ca_section_t::name, remove_cert(), streq(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     ca_section_t *ca = NULL;
     this->lock->write_lock(this->lock);
     enumerator = this->sections->create_enumerator(this->sections);
     while (enumerator->enumerate(enumerator, &ca))
     {
         if (streq(ca->name, msg->del_ca.name))
         {
             this->sections->remove_at(this->sections, enumerator);
             break;
         }
         ca = NULL;
     }
     enumerator->destroy(enumerator);
     if (ca)
     {
         this->certs->remove(this->certs, ca->cert, (void*)remove_cert);
     }
     this->lock->unlock(this->lock);
     if (!ca)
     {
         DBG1(DBG_CFG, "no ca named '%s' found\n", msg->del_ca.name);
         return;
     }
     ca_section_destroy(ca);
     lib->credmgr->flush_cache(lib->credmgr, CERT_ANY);
 }
METHOD (stroke_ca_t , get_cert_ref , certificate_t * , private_stroke_ca_t * this, certificate_t * cert)
Definition at line 508 of file stroke_ca.c.
References ca_cert_t::cert, cert, certificate_t::destroy, found, certificate_t::get_ref, lock, match_cert(), SUCCESS, and spinlock_t::unlock.
 {
     ca_cert_t *found;
     this->lock->read_lock(this->lock);
     if (this->certs->find_first(this->certs, (linked_list_match_t)match_cert,
                                 (void**)&found, cert) == SUCCESS)
     {
         cert->destroy(cert);
         cert = found->cert->get_ref(found->cert);
     }
     this->lock->unlock(this->lock);
     return cert;
 }
METHOD (stroke_ca_t , reload_certs , void , private_stroke_ca_t * this)
Definition at line 524 of file stroke_ca.c.
References add_cert_internal(), ca_section_destroy(), ca_section_t::cert, cert, CERT_ANY, CERT_X509, library_t::credmgr, DBG1, DBG_CFG, enumerator_t::destroy, certificate_t::destroy, enumerator_t::enumerate, certificate_t::equals, FALSE, credential_manager_t::flush_cache, lib, lock, ca_section_t::name, ca_section_t::path, remove_cert(), stroke_load_ca_cert(), type, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     ca_section_t *ca;
     certificate_type_t type = CERT_X509;
     /* holding the write lock while loading/parsing certificates is not optimal,
      * however, there usually are not that many ca sections configured */
     this->lock->write_lock(this->lock);
     if (this->sections->get_count(this->sections))
     {
         DBG1(DBG_CFG, "rereading ca certificates in ca sections");
     }
     enumerator = this->sections->create_enumerator(this->sections);
     while (enumerator->enumerate(enumerator, &ca))
     {
         cert = stroke_load_ca_cert(ca->path);
         if (cert)
         {
             if (cert->equals(cert, ca->cert))
             {
                 cert->destroy(cert);
             }
             else
             {
                 this->certs->remove(this->certs, ca->cert, (void*)remove_cert);
                 ca->cert->destroy(ca->cert);
                 ca->cert = add_cert_internal(this, cert, FALSE);
             }
         }
         else
         {
             DBG1(DBG_CFG, "failed to reload certificate '%s', removing ca '%s'",
                  ca->path, ca->name);
             this->sections->remove_at(this->sections, enumerator);
             this->certs->remove(this->certs, ca->cert, (void*)remove_cert);
             ca_section_destroy(ca);
             type = CERT_ANY;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     lib->credmgr->flush_cache(lib->credmgr, type);
 }
METHOD (stroke_ca_t , replace_certs , void , private_stroke_ca_t * this, mem_cred_t * certs)
Definition at line 571 of file stroke_ca.c.
References add_cert_internal(), cert, CERT_X509, credential_set_t::create_cert_enumerator, library_t::credmgr, enumerator_t::destroy, certificate_t::destroy, enumerator_t::enumerate, credential_manager_t::flush_cache, certificate_t::get_ref, KEY_ANY, lib, lock, remove_auto_certs(), mem_cred_t::set, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     enumerator = certs->set.create_cert_enumerator(&certs->set, CERT_X509,
                                                    KEY_ANY, NULL, TRUE);
     this->lock->write_lock(this->lock);
     this->certs->remove(this->certs, NULL, (void*)remove_auto_certs);
     while (enumerator->enumerate(enumerator, &cert))
     {
         cert = add_cert_internal(this, cert->get_ref(cert), TRUE);
         cert->destroy(cert);
     }
     this->lock->unlock(this->lock);
     enumerator->destroy(enumerator);
     lib->credmgr->flush_cache(lib->credmgr, CERT_X509);
 }
METHOD (stroke_ca_t , check_for_hash_and_url , void , private_stroke_ca_t * this, certificate_t * cert)
Definition at line 616 of file stroke_ca.c.
References hasher_t::allocate_hash, ca_section_t::cert, CERT_ASN1_DER, ca_section_t::certuribase, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_IKE, enumerator_t::destroy, hasher_t::destroy, enumerator_t::enumerate, certificate_t::get_encoding, hash, HASH_SHA1, hasher, ca_section_t::hashes, ID_KEY_ID, identification_create_from_encoding(), linked_list_t::insert_last, certificate_t::issued_by, lib, lock, section, and spinlock_t::unlock.
 {
     ca_section_t *section;
     enumerator_t *enumerator;
     hasher_t *hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (hasher == NULL)
     {
         DBG1(DBG_IKE, "unable to use hash-and-url: sha1 not supported");
         return;
     }
     this->lock->write_lock(this->lock);
     enumerator = this->sections->create_enumerator(this->sections);
     while (enumerator->enumerate(enumerator, (void**)&section))
     {
         if (section->certuribase && cert->issued_by(cert, section->cert, NULL))
         {
             chunk_t hash, encoded;
             if (cert->get_encoding(cert, CERT_ASN1_DER, &encoded))
             {
                 if (hasher->allocate_hash(hasher, encoded, &hash))
                 {
                     section->hashes->insert_last(section->hashes,
                         identification_create_from_encoding(ID_KEY_ID, hash));
                     chunk_free(&hash);
                 }
                 chunk_free(&encoded);
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     hasher->destroy(hasher);
 }
METHOD (stroke_ca_t , list , void , private_stroke_ca_t * this, stroke_msg_t * msg, FILE * out)
Definition at line 656 of file stroke_ca.c.
References ca_section_t::cert, cert, ca_section_t::certuribase, ca_section_t::crl, enumerator_t::destroy, enumerator_t::enumerate, FALSE, fprintf, certificate_t::get_public_key, certificate_t::get_subject, KEYID_PUBKEY_INFO_SHA1, KEYID_PUBKEY_SHA1, list_uris(), lock, ca_section_t::ocsp, public, section, TRUE, and spinlock_t::unlock.
 {
     bool first = TRUE;
     ca_section_t *section;
     enumerator_t *enumerator;
     this->lock->read_lock(this->lock);
     enumerator = this->sections->create_enumerator(this->sections);
     while (enumerator->enumerate(enumerator, (void**)&section))
     {
         certificate_t *cert = section->cert;
         public_key_t *public = cert->get_public_key(cert);
         chunk_t chunk;
         if (first)
         {
             fprintf(out, "\n");
             fprintf(out, "List of CA Information Sections:\n");
             first = FALSE;
         }
         fprintf(out, "\n");
         fprintf(out, "  authname:    \"%Y\"\n", cert->get_subject(cert));
         /* list authkey and keyid */
         if (public)
         {
             if (public->get_fingerprint(public, KEYID_PUBKEY_SHA1, &chunk))
             {
                 fprintf(out, "  authkey:      %#B\n", &chunk);
             }
             if (public->get_fingerprint(public, KEYID_PUBKEY_INFO_SHA1, &chunk))
             {
                 fprintf(out, "  keyid:        %#B\n", &chunk);
             }
             public->destroy(public);
         }
         list_uris(section->crl, "  crluris:     ", out);
         list_uris(section->ocsp, "  ocspuris:    ", out);
         if (section->certuribase)
         {
             fprintf(out, "  certuribase: '%s'\n", section->certuribase);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (stroke_ca_t , destroy , void , private_stroke_ca_t * this)
Definition at line 704 of file stroke_ca.c.
References ca_cert_destroy(), ca_section_destroy(), spinlock_t::destroy, free(), and lock.
 {
     this->sections->destroy_function(this->sections, (void*)ca_section_destroy);
     this->certs->destroy_function(this->certs, (void*)ca_cert_destroy);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool remove_auto_certs (ca_cert_t * item, void * not_used) static
Match automatically added certificates and remove/destroy them if they are not referenced by CA sections.
Definition at line 369 of file stroke_ca.c.
References ca_cert_t::automatic, ca_cert_destroy(), ca_cert_t::count, FALSE, and TRUE.
Referenced by METHOD().
 {
     if (item->automatic)
     {
         item->automatic = FALSE;
         if (!item->count)
         {
             ca_cert_destroy(item);
             return TRUE;
         }
     }
     return FALSE;
 }
static bool remove_cert (ca_cert_t * item, certificate_t * cert) static
Find the given certificate that was referenced by a section and remove it unless it was also loaded automatically or is used by other CA sections.
Definition at line 387 of file stroke_ca.c.
References ca_cert_t::automatic, ca_cert_destroy(), ca_cert_t::cert, ca_cert_t::count, certificate_t::equals, FALSE, and TRUE.
Referenced by METHOD().
 {
     if (item->count && cert->equals(cert, item->cert))
     {
         if (--item->count == 0 && !item->automatic)
         {
             ca_cert_destroy(item);
             return TRUE;
         }
     }
     return FALSE;
 }
certificate_t* stroke_load_ca_cert (char * filename)
Provided by stroke_cred.c
Used by stroke_ca.c
Definition at line 391 of file stroke_cred.c.
References FALSE, settings_t::get_bool, lib, load_ca_cert(), library_t::ns, and library_t::settings.
Referenced by METHOD().
 {
     bool force_ca_cert;
     force_ca_cert = lib->settings->get_bool(lib->settings,
                         "%s.plugins.stroke.ignore_missing_ca_basic_constraint",
                         FALSE, lib->ns);
     return load_ca_cert(filename, force_ca_cert);
 }