strongSwan: endpoint_notify_t Struct Reference
endpoint_notify_t Struct Reference
endpoint_notify
#include "endpoint_notify.h"
Public Attributes
u_int32_t(* get_priority)(endpoint_notify_t *this)
void(* set_priority)(endpoint_notify_t *this, u_int32_t priority)
me_endpoint_type_t(* get_type)(endpoint_notify_t *this)
me_endpoint_family_t(* get_family)(endpoint_notify_t *this)
host_t *(* get_host)(endpoint_notify_t *this)
host_t *(* get_base)(endpoint_notify_t *this)
notify_payload_t *(* build_notify)(endpoint_notify_t *this)
endpoint_notify_t *(* clone)(endpoint_notify_t *this)
void(* destroy)(endpoint_notify_t *this)
Detailed Description
Class representing a ME_ENDPOINT Notify payload. In fact it's not the notify per se, but the notification data of that notify that is handled with this class.
Definition at line 79 of file endpoint_notify.h.
Member Data Documentation
notify_payload_t*(* endpoint_notify_t::build_notify)(endpoint_notify_t *this)
Generates a notification payload from this endpoint.
Returns
built notify_payload_t
Definition at line 130 of file endpoint_notify.h.
Referenced by add_endpoints_to_message(), METHOD(), and send_check().
endpoint_notify_t*(* endpoint_notify_t::clone)(endpoint_notify_t *this)
Clones an endpoint_notify_t object.
Returns
cloned object
Definition at line 137 of file endpoint_notify.h.
Referenced by process_request().
void(* endpoint_notify_t::destroy)(endpoint_notify_t *this)
Destroys an endpoint_notify_t object.
Definition at line 142 of file endpoint_notify.h.
Referenced by METHOD(), and process_request().
host_t*(* endpoint_notify_t::get_base)(endpoint_notify_t *this)
Returns the base of this endpoint.
If this is not a SERVER_REFLEXIVE endpoint, the returned host is the same as the one returned by get_host.
Returns
host
Definition at line 123 of file endpoint_notify.h.
Referenced by endpoint_pair_create().
me_endpoint_family_t(* endpoint_notify_t::get_family)(endpoint_notify_t *this)
Returns the endpoint family of this endpoint.
Returns
endpoint family
Definition at line 106 of file endpoint_notify.h.
Referenced by build_pairs().
host_t*(* endpoint_notify_t::get_host)(endpoint_notify_t *this)
Returns the host of this endpoint.
Returns
host
Definition at line 113 of file endpoint_notify.h.
Referenced by endpoint_pair_create(), match_endpoint_by_host(), METHOD(), process_payloads(), and process_response().
u_int32_t(* endpoint_notify_t::get_priority)(endpoint_notify_t *this)
Returns the priority of this endpoint.
Returns
priority
Definition at line 85 of file endpoint_notify.h.
Referenced by endpoint_pair_create(), process_request(), and process_response().
me_endpoint_type_t(* endpoint_notify_t::get_type)(endpoint_notify_t *this)
Returns the endpoint type of this endpoint.
Returns
endpoint type
Definition at line 99 of file endpoint_notify.h.
Referenced by METHOD(), and process_payloads().
void(* endpoint_notify_t::set_priority)(endpoint_notify_t *this, u_int32_t priority)
Sets the priority of this endpoint.
Parameters
priority priority
Definition at line 92 of file endpoint_notify.h.
Referenced by process_request(), and process_response().
The documentation for this struct was generated from the following file:
endpoint_notify.h