strongSwan: x509_cert.c File Reference
x509_cert.c File Reference
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include "x509_cert.h"
#include <library.h>
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <crypto/hashers/hasher.h>
#include <credentials/keys/private_key.h>
#include <collections/linked_list.h>
#include <utils/identification.h>
#include <selectors/traffic_selector.h>
Classes
struct private_x509_cert_t
Macros
#define _GNU_SOURCE
#define BASIC_CONSTRAINTS_CA 1
#define BASIC_CONSTRAINTS_PATH_LEN 2
#define ON_OBJ_ID_TYPE 0
#define ON_OBJ_VALUE 1
#define GN_OBJ_OTHER_NAME 0
#define GN_OBJ_RFC822_NAME 2
#define GN_OBJ_DNS_NAME 4
#define GN_OBJ_X400_ADDRESS 6
#define GN_OBJ_DIRECTORY_NAME 8
#define GN_OBJ_EDI_PARTY_NAME 10
#define GN_OBJ_URI 12
#define GN_OBJ_IP_ADDRESS 14
#define GN_OBJ_REGISTERED_ID 16
#define GENERAL_NAMES_GN 1
#define AUTH_KEY_ID_KEY_ID 1
#define AUTH_KEY_ID_CERT_ISSUER 3
#define AUTH_KEY_ID_CERT_SERIAL 5
#define AUTH_INFO_ACCESS_METHOD 2
#define AUTH_INFO_ACCESS_LOCATION 3
#define EXT_KEY_USAGE_PURPOSE_ID 1
#define CRL_DIST_POINTS 1
#define CRL_DIST_POINTS_FULLNAME 3
#define CRL_DIST_POINTS_ISSUER 10
#define NAME_CONSTRAINT_PERMITTED 2
#define NAME_CONSTRAINT_EXCLUDED 5
#define CERT_POLICY_ID 2
#define CERT_POLICY_QUALIFIER_ID 5
#define CERT_POLICY_CPS_URI 6
#define CERT_POLICY_EXPLICIT_TEXT 9
#define POLICY_MAPPING 1
#define POLICY_MAPPING_ISSUER 2
#define POLICY_MAPPING_SUBJECT 3
#define POLICY_CONSTRAINT_EXPLICIT 2
#define POLICY_CONSTRAINT_INHIBIT 5
#define IP_ADDR_BLOCKS_FAMILY 2
#define IP_ADDR_BLOCKS_INHERIT 3
#define IP_ADDR_BLOCKS_PREFIX 6
#define IP_ADDR_BLOCKS_MIN 9
#define IP_ADDR_BLOCKS_MAX 10
#define X509_OBJ_TBS_CERTIFICATE 1
#define X509_OBJ_VERSION 3
#define X509_OBJ_SERIAL_NUMBER 4
#define X509_OBJ_SIG_ALG 5
#define X509_OBJ_ISSUER 6
#define X509_OBJ_NOT_BEFORE 8
#define X509_OBJ_NOT_AFTER 9
#define X509_OBJ_SUBJECT 10
#define X509_OBJ_SUBJECT_PUBLIC_KEY_INFO 11
#define X509_OBJ_OPTIONAL_EXTENSIONS 16
#define X509_OBJ_EXTN_ID 19
#define X509_OBJ_CRITICAL 20
#define X509_OBJ_EXTN_VALUE 21
#define X509_OBJ_ALGORITHM 24
#define X509_OBJ_SIGNATURE 25
Typedefs
typedef struct private_x509_cert_t private_x509_cert_t
Enumerations
enum generalNames_t {
GN_OTHER_NAME = 0, GN_RFC822_NAME = 1, GN_DNS_NAME = 2, GN_X400_ADDRESS = 3,
GN_DIRECTORY_NAME = 4, GN_EDI_PARTY_NAME = 5, GN_URI = 6, GN_IP_ADDRESS = 7,
GN_REGISTERED_ID = 8
}
Functions
static void crl_uri_destroy (x509_cdp_t *this)
static void cert_policy_destroy (x509_cert_policy_t *this)
static void policy_mapping_destroy (x509_policy_mapping_t *mapping)
static u_int parse_constraint (chunk_t object)
static void parse_basicConstraints (chunk_t blob, int level0, private_x509_cert_t *this)
static bool parse_otherName (chunk_t *blob, int level0, id_type_t *type)
static identification_t * parse_generalName (chunk_t blob, int level0)
void x509_parse_generalNames (chunk_t blob, int level0, bool implicit, linked_list_t *list)
chunk_t x509_parse_authorityKeyIdentifier (chunk_t blob, int level0, chunk_t *authKeySerialNumber)
static void parse_authorityInfoAccess (chunk_t blob, int level0, private_x509_cert_t *this)
static void parse_keyUsage (chunk_t blob, private_x509_cert_t *this)
static void parse_extendedKeyUsage (chunk_t blob, int level0, private_x509_cert_t *this)
static void add_cdps (linked_list_t *list, linked_list_t *uris, linked_list_t *issuers)
void x509_parse_crlDistributionPoints (chunk_t blob, int level0, linked_list_t *list)
static void parse_nameConstraints (chunk_t blob, int level0, private_x509_cert_t *this)
static void parse_certificatePolicies (chunk_t blob, int level0, private_x509_cert_t *this)
static void parse_policyMappings (chunk_t blob, int level0, private_x509_cert_t *this)
static void parse_policyConstraints (chunk_t blob, int level0, private_x509_cert_t *this)
static bool check_address_object (ts_type_t ts_type, chunk_t object)
static void parse_ipAddrBlocks (chunk_t blob, int level0, private_x509_cert_t *this)
static bool parse_certificate (private_x509_cert_t *this)
METHOD (certificate_t, get_type, certificate_type_t, private_x509_cert_t *this)
METHOD (certificate_t, get_subject, identification_t *, private_x509_cert_t *this)
METHOD (certificate_t, get_issuer, identification_t *, private_x509_cert_t *this)
METHOD (certificate_t, has_subject, id_match_t, private_x509_cert_t *this, identification_t *subject)
METHOD (certificate_t, has_issuer, id_match_t, private_x509_cert_t *this, identification_t *issuer)
METHOD (certificate_t, issued_by, bool, private_x509_cert_t *this, certificate_t *issuer, signature_scheme_t *schemep)
METHOD (certificate_t, get_public_key, public_key_t *, private_x509_cert_t *this)
METHOD (certificate_t, get_ref, certificate_t *, private_x509_cert_t *this)
METHOD (certificate_t, get_validity, bool, private_x509_cert_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_x509_cert_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, equals, bool, private_x509_cert_t *this, certificate_t *other)
METHOD (x509_t, get_flags, x509_flag_t, private_x509_cert_t *this)
METHOD (x509_t, get_serial, chunk_t, private_x509_cert_t *this)
METHOD (x509_t, get_subjectKeyIdentifier, chunk_t, private_x509_cert_t *this)
METHOD (x509_t, get_authKeyIdentifier, chunk_t, private_x509_cert_t *this)
METHOD (x509_t, get_constraint, u_int, private_x509_cert_t *this, x509_constraint_t type)
METHOD (x509_t, create_subjectAltName_enumerator, enumerator_t *, private_x509_cert_t *this)
METHOD (x509_t, create_ocsp_uri_enumerator, enumerator_t *, private_x509_cert_t *this)
METHOD (x509_t, create_crl_uri_enumerator, enumerator_t *, private_x509_cert_t *this)
METHOD (x509_t, create_ipAddrBlock_enumerator, enumerator_t *, private_x509_cert_t *this)
METHOD (x509_t, create_name_constraint_enumerator, enumerator_t *, private_x509_cert_t *this, bool perm)
METHOD (x509_t, create_cert_policy_enumerator, enumerator_t *, private_x509_cert_t *this)
METHOD (x509_t, create_policy_mapping_enumerator, enumerator_t *, private_x509_cert_t *this)
METHOD (certificate_t, destroy, void, private_x509_cert_t *this)
static private_x509_cert_t * create_empty (void)
chunk_t build_generalName (identification_t *id)
chunk_t x509_build_subjectAltNames (linked_list_t *list)
chunk_t x509_build_crlDistributionPoints (linked_list_t *list, int extn)
static bool generate (private_x509_cert_t *cert, certificate_t *sign_cert, private_key_t *sign_key, int digest_alg)
x509_cert_t * x509_cert_load (certificate_type_t type, va_list args)
x509_cert_t * x509_cert_gen (certificate_type_t type, va_list args)
Variables
static const asn1Object_t basicConstraintsObjects []
static const asn1Object_t otherNameObjects []
static const asn1Object_t generalNameObjects []
static const asn1Object_t generalNamesObjects []
static const asn1Object_t authKeyIdentifierObjects []
static const asn1Object_t authInfoAccessObjects []
static const asn1Object_t extendedKeyUsageObjects []
static const asn1Object_t crlDistributionPointsObjects []
static const asn1Object_t nameConstraintsObjects []
static const asn1Object_t certificatePoliciesObject []
static const asn1Object_t policyMappingsObjects []
static const asn1Object_t policyConstraintsObjects []
static const asn1Object_t ipAddrBlocksObjects []
static const asn1Object_t certObjects []
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 21 of file x509_cert.c.
#define AUTH_INFO_ACCESS_LOCATION 3
Definition at line 597 of file x509_cert.c.
Referenced by parse_authorityInfoAccess().
#define AUTH_INFO_ACCESS_METHOD 2
Definition at line 596 of file x509_cert.c.
Referenced by parse_authorityInfoAccess().
#define AUTH_KEY_ID_CERT_ISSUER 3
Definition at line 545 of file x509_cert.c.
Referenced by x509_parse_authorityKeyIdentifier().
#define AUTH_KEY_ID_CERT_SERIAL 5
Definition at line 546 of file x509_cert.c.
Referenced by x509_parse_authorityKeyIdentifier().
#define AUTH_KEY_ID_KEY_ID 1
Definition at line 544 of file x509_cert.c.
Referenced by x509_parse_authorityKeyIdentifier().
#define BASIC_CONSTRAINTS_CA 1
Definition at line 277 of file x509_cert.c.
Referenced by parse_basicConstraints().
#define BASIC_CONSTRAINTS_PATH_LEN 2
Definition at line 278 of file x509_cert.c.
Referenced by parse_basicConstraints().
#define CERT_POLICY_CPS_URI 6
Definition at line 956 of file x509_cert.c.
Referenced by parse_certificatePolicies().
#define CERT_POLICY_EXPLICIT_TEXT 9
Definition at line 957 of file x509_cert.c.
Referenced by parse_certificatePolicies().
#define CERT_POLICY_ID 2
Definition at line 954 of file x509_cert.c.
Referenced by parse_certificatePolicies().
#define CERT_POLICY_QUALIFIER_ID 5
Definition at line 955 of file x509_cert.c.
Referenced by parse_certificatePolicies().
#define CRL_DIST_POINTS 1
Definition at line 787 of file x509_cert.c.
Referenced by parse_crlDistributionPoints_ext(), and x509_parse_crlDistributionPoints().
#define CRL_DIST_POINTS_FULLNAME 3
Definition at line 788 of file x509_cert.c.
Referenced by x509_parse_crlDistributionPoints().
#define CRL_DIST_POINTS_ISSUER 10
Definition at line 789 of file x509_cert.c.
Referenced by x509_parse_crlDistributionPoints().
#define EXT_KEY_USAGE_PURPOSE_ID 1
Definition at line 724 of file x509_cert.c.
Referenced by parse_extendedKeyUsage().
#define GENERAL_NAMES_GN 1
Definition at line 500 of file x509_cert.c.
Referenced by x509_parse_generalNames().
#define GN_OBJ_DIRECTORY_NAME 8
Definition at line 414 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_DNS_NAME 4
Definition at line 412 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_EDI_PARTY_NAME 10
Definition at line 415 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_IP_ADDRESS 14
Definition at line 417 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_OTHER_NAME 0
Definition at line 410 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_REGISTERED_ID 16
Definition at line 418 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_RFC822_NAME 2
Definition at line 411 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_URI 12
Definition at line 416 of file x509_cert.c.
Referenced by parse_generalName().
#define GN_OBJ_X400_ADDRESS 6
Definition at line 413 of file x509_cert.c.
Referenced by parse_generalName().
#define IP_ADDR_BLOCKS_FAMILY 2
Definition at line 1126 of file x509_cert.c.
Referenced by parse_ipAddrBlocks().
#define IP_ADDR_BLOCKS_INHERIT 3
Definition at line 1127 of file x509_cert.c.
Referenced by parse_ipAddrBlocks().
#define IP_ADDR_BLOCKS_MAX 10
Definition at line 1130 of file x509_cert.c.
Referenced by parse_ipAddrBlocks().
#define IP_ADDR_BLOCKS_MIN 9
Definition at line 1129 of file x509_cert.c.
Referenced by parse_ipAddrBlocks().
#define IP_ADDR_BLOCKS_PREFIX 6
Definition at line 1128 of file x509_cert.c.
Referenced by parse_ipAddrBlocks().
#define NAME_CONSTRAINT_EXCLUDED 5
Definition at line 894 of file x509_cert.c.
Referenced by parse_nameConstraints().
#define NAME_CONSTRAINT_PERMITTED 2
Definition at line 893 of file x509_cert.c.
Referenced by parse_nameConstraints().
#define ON_OBJ_ID_TYPE 0
Definition at line 327 of file x509_cert.c.
Referenced by parse_otherName().
#define ON_OBJ_VALUE 1
Definition at line 328 of file x509_cert.c.
Referenced by parse_otherName().
#define POLICY_CONSTRAINT_EXPLICIT 2
Definition at line 1073 of file x509_cert.c.
Referenced by parse_policyConstraints().
#define POLICY_CONSTRAINT_INHIBIT 5
Definition at line 1074 of file x509_cert.c.
Referenced by parse_policyConstraints().
#define POLICY_MAPPING 1
Definition at line 1015 of file x509_cert.c.
Referenced by parse_policyMappings().
#define POLICY_MAPPING_ISSUER 2
Definition at line 1016 of file x509_cert.c.
Referenced by parse_policyMappings().
#define POLICY_MAPPING_SUBJECT 3
Definition at line 1017 of file x509_cert.c.
Referenced by parse_policyMappings().
#define X509_OBJ_ALGORITHM 24
Definition at line 1294 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_CRITICAL 20
Definition at line 1292 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_EXTN_ID 19
Definition at line 1291 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_EXTN_VALUE 21
Definition at line 1293 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_ISSUER 6
Definition at line 1285 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_NOT_AFTER 9
Definition at line 1287 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_NOT_BEFORE 8
Definition at line 1286 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_OPTIONAL_EXTENSIONS 16
Definition at line 1290 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_SERIAL_NUMBER 4
Definition at line 1283 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_SIG_ALG 5
Definition at line 1284 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_SIGNATURE 25
Definition at line 1295 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_SUBJECT 10
Definition at line 1288 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_SUBJECT_PUBLIC_KEY_INFO 11
Definition at line 1289 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_TBS_CERTIFICATE 1
Definition at line 1281 of file x509_cert.c.
Referenced by parse_certificate().
#define X509_OBJ_VERSION 3
Definition at line 1282 of file x509_cert.c.
Referenced by parse_certificate().
Typedef Documentation
typedef struct private_x509_cert_t private_x509_cert_t
Definition at line 58 of file x509_cert.c.
Enumeration Type Documentation
enum generalNames_t
Different kinds of generalNames
Enumerator
GN_OTHER_NAME
GN_RFC822_NAME
GN_DNS_NAME
GN_X400_ADDRESS
GN_DIRECTORY_NAME
GN_EDI_PARTY_NAME
GN_URI
GN_IP_ADDRESS
GN_REGISTERED_ID
Definition at line 45 of file x509_cert.c.
              {
     GN_OTHER_NAME =     0,
     GN_RFC822_NAME =    1,
     GN_DNS_NAME =       2,
     GN_X400_ADDRESS =   3,
     GN_DIRECTORY_NAME = 4,
     GN_EDI_PARTY_NAME = 5,
     GN_URI =            6,
     GN_IP_ADDRESS =     7,
     GN_REGISTERED_ID =  8,
 } generalNames_t;
Function Documentation
static void add_cdps (linked_list_t * list, linked_list_t * uris, linked_list_t * issuers) static
Add entry to the list of each pairing of URI and Issuer
Definition at line 794 of file x509_cert.c.
References asprintf(), identification_t::clone, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, free(), linked_list_t::get_count, id, INIT, linked_list_t::insert_last, linked_list_t::remove_last, strdup, SUCCESS, and uri.
Referenced by x509_parse_crlDistributionPoints().
 {
     identification_t *issuer, *id;
     enumerator_t *enumerator;
     x509_cdp_t *cdp;
     char *uri;
     while (uris->remove_last(uris, (void**)&id) == SUCCESS)
     {
         if (asprintf(&uri, "%Y", id) > 0)
         {
             if (issuers->get_count(issuers))
             {
                 enumerator = issuers->create_enumerator(issuers);
                 while (enumerator->enumerate(enumerator, &issuer))
                 {
                     INIT(cdp,
                         .uri = strdup(uri),
                         .issuer = issuer->clone(issuer),
                     );
                     list->insert_last(list, cdp);
                 }
                 enumerator->destroy(enumerator);
                 free(uri);
             }
             else
             {
                 INIT(cdp,
                     .uri = uri,
                 );
                 list->insert_last(list, cdp);
             }
         }
         id->destroy(id);
     }
     while (issuers->remove_last(issuers, (void**)&id) == SUCCESS)
     {
         id->destroy(id);
     }
 }
chunk_t build_generalName (identification_t * id)
Build a generalName from an id
Definition at line 1897 of file x509_cert.c.
References ASN1_CONTEXT_C_4, ASN1_CONTEXT_S_1, ASN1_CONTEXT_S_2, ASN1_CONTEXT_S_7, asn1_wrap(), chunk_empty, context, DBG1, DBG_ASN, identification_t::get_encoding, identification_t::get_type, ID_DER_ASN1_DN, ID_FQDN, ID_IPV4_ADDR, ID_IPV6_ADDR, ID_RFC822_ADDR, and id_type_names.
Referenced by generate(), x509_build_crlDistributionPoints(), and x509_build_subjectAltNames().
 {
     int context;
     switch (id->get_type(id))
     {
         case ID_RFC822_ADDR:
             context = ASN1_CONTEXT_S_1;
             break;
         case ID_FQDN:
             context = ASN1_CONTEXT_S_2;
             break;
         case ID_DER_ASN1_DN:
             context = ASN1_CONTEXT_C_4;
             break;
         case ID_IPV4_ADDR:
         case ID_IPV6_ADDR:
             context = ASN1_CONTEXT_S_7;
             break;
         default:
             DBG1(DBG_ASN, "encoding %N as generalName not supported",
                  id_type_names, id->get_type(id));
             return chunk_empty;
     }
     return asn1_wrap(context, "c", id->get_encoding(id));
 }
static void cert_policy_destroy (x509_cert_policy_t * this) static
Destroy a CertificatePolicy
Definition at line 233 of file x509_cert.c.
References free().
Referenced by METHOD().
 {
     free(this->oid.ptr);
     free(this->cps_uri);
     free(this->unotice_text);
     free(this);
 }
static bool check_address_object (ts_type_t ts_type, chunk_t object) static
Definition at line 1132 of file x509_cert.c.
References DBG1, DBG_ASN, FALSE, len, TRUE, TS_IPV4_ADDR_RANGE, and TS_IPV6_ADDR_RANGE.
Referenced by parse_ipAddrBlocks().
 {
     switch (ts_type)
     {
         case TS_IPV4_ADDR_RANGE:
             if (object.len > 5)
             {
                 DBG1(DBG_ASN, "IPv4 address object is larger than 5 octets");
                 return FALSE;
             }
             break;
         case TS_IPV6_ADDR_RANGE:
             if (object.len > 17)
             {
                 DBG1(DBG_ASN, "IPv6 address object is larger than 17 octets");
                 return FALSE;
             }
             break;
         default:
             DBG1(DBG_ASN, "unknown address family");
             return FALSE;
     }
     if (object.len == 0)
     {
         DBG1(DBG_ASN, "An ASN.1 bit string must contain at least the "
              "initial octet");
         return FALSE;
     }
     if (object.len == 1 && object.ptr[0] != 0)
     {
         DBG1(DBG_ASN, "An empty ASN.1 bit string must contain a zero "
              "initial octet");
         return FALSE;
     }
     if (object.ptr[0] > 7)
     {
         DBG1(DBG_ASN, "number of unused bits is too large");
         return FALSE;
     }
     return TRUE;
 }
static private_x509_cert_t* create_empty (void) static
create an empty but initialized X.509 certificate
Definition at line 1841 of file x509_cert.c.
References INIT, linked_list_create(), and X509_NO_CONSTRAINT.
Referenced by x509_cert_gen(), and x509_cert_load().
 {
     private_x509_cert_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .interface = {
                     .get_type = _get_type,
                     .get_subject = _get_subject,
                     .get_issuer = _get_issuer,
                     .has_subject = _has_subject,
                     .has_issuer = _has_issuer,
                     .issued_by = _issued_by,
                     .get_public_key = _get_public_key,
                     .get_validity = _get_validity,
                     .get_encoding = _get_encoding,
                     .equals = _equals,
                     .get_ref = _get_ref,
                     .destroy = _destroy,
                 },
                 .get_flags = _get_flags,
                 .get_serial = _get_serial,
                 .get_subjectKeyIdentifier = _get_subjectKeyIdentifier,
                 .get_authKeyIdentifier = _get_authKeyIdentifier,
                 .get_constraint = _get_constraint,
                 .create_subjectAltName_enumerator = _create_subjectAltName_enumerator,
                 .create_crl_uri_enumerator = _create_crl_uri_enumerator,
                 .create_ocsp_uri_enumerator = _create_ocsp_uri_enumerator,
                 .create_ipAddrBlock_enumerator = _create_ipAddrBlock_enumerator,
                 .create_name_constraint_enumerator = _create_name_constraint_enumerator,
                 .create_cert_policy_enumerator = _create_cert_policy_enumerator,
                 .create_policy_mapping_enumerator = _create_policy_mapping_enumerator,
             },
         },
         .version = 1,
         .subjectAltNames = linked_list_create(),
         .crl_uris = linked_list_create(),
         .ocsp_uris = linked_list_create(),
         .ipAddrBlocks = linked_list_create(),
         .permitted_names = linked_list_create(),
         .excluded_names = linked_list_create(),
         .cert_policies = linked_list_create(),
         .policy_mappings = linked_list_create(),
         .pathLenConstraint = X509_NO_CONSTRAINT,
         .require_explicit = X509_NO_CONSTRAINT,
         .inhibit_mapping = X509_NO_CONSTRAINT,
         .inhibit_any = X509_NO_CONSTRAINT,
         .ref = 1,
     );
     return this;
 }
static void crl_uri_destroy (x509_cdp_t * this) static
Destroy a CertificateDistributionPoint
Definition at line 223 of file x509_cert.c.
References DESTROY_IF, free(), and uri.
Referenced by METHOD().
 {
     free(this->uri);
     DESTROY_IF(this->issuer);
     free(this);
 }
static bool generate (private_x509_cert_t * cert, certificate_t * sign_cert, private_key_t * sign_key, int digest_alg) static
Generate and sign a new certificate
Definition at line 1998 of file x509_cert.c.
References private_x509_cert_t::algorithm, hasher_t::allocate_hash, asn1_algorithmIdentifier(), ASN1_BIT_STRING, asn1_bitstring(), ASN1_BOOLEAN, asn1_build_known_oid(), ASN1_CONTEXT_C_0, ASN1_CONTEXT_C_1, ASN1_CONTEXT_C_3, ASN1_CONTEXT_S_0, ASN1_CONTEXT_S_6, asn1_from_time(), ASN1_IA5STRING, asn1_integer(), ASN1_INTEGER_2, ASN1_OCTET_STRING, ASN1_OID, ASN1_SEQUENCE, asn1_simple_object(), ASN1_UTCTIME, ASN1_VISIBLESTRING, asn1_wrap(), build_generalName(), private_x509_cert_t::cert_policies, chunk_cat, chunk_create(), chunk_empty, chunk_from_chars, chunk_from_thing, identification_t::clone, x509_cert_policy_t::cps_uri, linked_list_t::create_enumerator, crypto_factory_t::create_hasher, private_x509_cert_t::crl_uris, library_t::crypto, enumerator_t::destroy, hasher_t::destroy, DESTROY_IF, private_x509_cert_t::encoding, private_x509_cert_t::encoding_hash, enumerator_t::enumerate, private_x509_cert_t::excluded_names, FALSE, private_x509_cert_t::flags, linked_list_t::get_count, identification_t::get_encoding, public_key_t::get_encoding, private_key_t::get_fingerprint, public_key_t::get_fingerprint, private_key_t::get_public_key, certificate_t::get_subject, private_key_t::get_type, HASH_SHA1, hasher, hasher_signature_algorithm_to_oid(), id, private_x509_cert_t::inhibit_any, private_x509_cert_t::inhibit_mapping, x509_policy_mapping_t::issuer, private_x509_cert_t::issuer, keyid(), KEYID_PUBKEY_SHA1, lib, private_x509_cert_t::notAfter, private_x509_cert_t::notBefore, private_x509_cert_t::ocsp_uris, x509_cert_policy_t::oid, OID_AUTHORITY_INFO_ACCESS, OID_AUTHORITY_KEY_ID, OID_BASIC_CONSTRAINTS, OID_CERTIFICATE_POLICIES, OID_CLIENT_AUTH, OID_CRL_DISTRIBUTION_POINTS, OID_EXTENDED_KEY_USAGE, OID_IKE_INTERMEDIATE, OID_INHIBIT_ANY_POLICY, OID_KEY_USAGE, OID_MS_SMARTCARD_LOGON, OID_NAME_CONSTRAINTS, OID_OCSP, OID_OCSP_SIGNING, OID_POLICY_CONSTRAINTS, OID_POLICY_MAPPINGS, OID_POLICY_QUALIFIER_CPS, OID_POLICY_QUALIFIER_UNOTICE, OID_SERVER_AUTH, OID_SUBJECT_KEY_ID, OID_UNKNOWN, private_x509_cert_t::pathLenConstraint, private_x509_cert_t::permitted_names, private_x509_cert_t::policy_mappings, chunk_t::ptr, PUBKEY_SPKI_ASN1_DER, private_x509_cert_t::public_key, private_x509_cert_t::require_explicit, scheme, private_x509_cert_t::serialNumber, private_key_t::sign, private_x509_cert_t::signature, signature_scheme_from_oid(), x509_policy_mapping_t::subject, private_x509_cert_t::subject, subject, private_x509_cert_t::subjectAltNames, subjectAltNames, private_x509_cert_t::tbsCertificate, TRUE, x509_cert_policy_t::unotice_text, uri, x509_build_crlDistributionPoints(), x509_build_subjectAltNames(), X509_CA, X509_CLIENT_AUTH, X509_CRL_SIGN, X509_IKE_INTERMEDIATE, X509_MS_SMARTCARD_LOGON, X509_NO_CONSTRAINT, X509_OCSP_SIGNER, X509_SELF_SIGNED, and X509_SERVER_AUTH.
Referenced by x509_cert_gen().
 {
     chunk_t extensions = chunk_empty, extendedKeyUsage = chunk_empty;
     chunk_t serverAuth = chunk_empty, clientAuth = chunk_empty;
     chunk_t ocspSigning = chunk_empty, certPolicies = chunk_empty;
     chunk_t basicConstraints = chunk_empty, nameConstraints = chunk_empty;
     chunk_t keyUsage = chunk_empty, keyUsageBits = chunk_empty;
     chunk_t subjectAltNames = chunk_empty, policyMappings = chunk_empty;
     chunk_t subjectKeyIdentifier = chunk_empty, authKeyIdentifier = chunk_empty;
     chunk_t crlDistributionPoints = chunk_empty, authorityInfoAccess = chunk_empty;
     chunk_t policyConstraints = chunk_empty, inhibitAnyPolicy = chunk_empty;
     chunk_t ikeIntermediate = chunk_empty, msSmartcardLogon = chunk_empty;
     identification_t *issuer, *subject;
     chunk_t key_info;
     signature_scheme_t scheme;
     hasher_t *hasher;
     enumerator_t *enumerator;
     char *uri;
     subject = cert->subject;
     if (sign_cert)
     {
         issuer = sign_cert->get_subject(sign_cert);
         if (!cert->public_key)
         {
             return FALSE;
         }
     }
     else
     {   /* self signed */
         issuer = subject;
         if (!cert->public_key)
         {
             cert->public_key = sign_key->get_public_key(sign_key);
         }
         cert->flags |= X509_SELF_SIGNED;
     }
     cert->issuer = issuer->clone(issuer);
     if (!cert->notBefore)
     {
         cert->notBefore = time(NULL);
     }
     if (!cert->notAfter)
     {   /* defaults to 1 year from now */
         cert->notAfter = cert->notBefore + 60 * 60 * 24 * 365;
     }
     /* select signature scheme */
     cert->algorithm = hasher_signature_algorithm_to_oid(digest_alg,
                                 sign_key->get_type(sign_key));
     if (cert->algorithm == OID_UNKNOWN)
     {
         return FALSE;
     }
     scheme = signature_scheme_from_oid(cert->algorithm);
     if (!cert->public_key->get_encoding(cert->public_key,
                                         PUBKEY_SPKI_ASN1_DER, &key_info))
     {
         return FALSE;
     }
     /* encode subjectAltNames */
     subjectAltNames = x509_build_subjectAltNames(cert->subjectAltNames);
     crlDistributionPoints = x509_build_crlDistributionPoints(cert->crl_uris,
                                                 OID_CRL_DISTRIBUTION_POINTS);
     /* encode OCSP URIs in authorityInfoAccess extension */
     enumerator = cert->ocsp_uris->create_enumerator(cert->ocsp_uris);
     while (enumerator->enumerate(enumerator, &uri))
     {
         chunk_t accessDescription;
         accessDescription = asn1_wrap(ASN1_SEQUENCE, "mm",
                                 asn1_build_known_oid(OID_OCSP),
                                 asn1_wrap(ASN1_CONTEXT_S_6, "c",
                                           chunk_create(uri, strlen(uri))));
         authorityInfoAccess = chunk_cat("mm", authorityInfoAccess,
                                         accessDescription);
     }
     enumerator->destroy(enumerator);
     if (authorityInfoAccess.ptr)
     {
         authorityInfoAccess = asn1_wrap(ASN1_SEQUENCE, "mm",
                     asn1_build_known_oid(OID_AUTHORITY_INFO_ACCESS),
                     asn1_wrap(ASN1_OCTET_STRING, "m",
                         asn1_wrap(ASN1_SEQUENCE, "m", authorityInfoAccess)));
     }
     /* build CA basicConstraint and keyUsage flags for CA certificates */
     if (cert->flags & X509_CA)
     {
         chunk_t pathLenConstraint = chunk_empty;
         if (cert->pathLenConstraint != X509_NO_CONSTRAINT)
         {
             pathLenConstraint = asn1_integer("c",
                                     chunk_from_thing(cert->pathLenConstraint));
         }
         basicConstraints = asn1_wrap(ASN1_SEQUENCE, "mmm",
                                 asn1_build_known_oid(OID_BASIC_CONSTRAINTS),
                                 asn1_wrap(ASN1_BOOLEAN, "c",
                                     chunk_from_chars(0xFF)),
                                 asn1_wrap(ASN1_OCTET_STRING, "m",
                                         asn1_wrap(ASN1_SEQUENCE, "mm",
                                             asn1_wrap(ASN1_BOOLEAN, "c",
                                                 chunk_from_chars(0xFF)),
                                             pathLenConstraint)));
         /* set CertificateSign and implicitly CRLsign */
         keyUsageBits = chunk_from_chars(0x01, 0x06);
     }
     else if (cert->flags & X509_CRL_SIGN)
     {
         keyUsageBits = chunk_from_chars(0x01, 0x02);
     }
     if (keyUsageBits.len)
     {
         keyUsage = asn1_wrap(ASN1_SEQUENCE, "mmm",
                         asn1_build_known_oid(OID_KEY_USAGE),
                         asn1_wrap(ASN1_BOOLEAN, "c", chunk_from_chars(0xFF)),
                         asn1_wrap(ASN1_OCTET_STRING, "m",
                             asn1_wrap(ASN1_BIT_STRING, "c", keyUsageBits)));
     }
     /* add extendedKeyUsage flags */
     if (cert->flags & X509_SERVER_AUTH)
     {
         serverAuth = asn1_build_known_oid(OID_SERVER_AUTH);
     }
     if (cert->flags & X509_CLIENT_AUTH)
     {
         clientAuth = asn1_build_known_oid(OID_CLIENT_AUTH);
     }
     if (cert->flags & X509_IKE_INTERMEDIATE)
     {
         ikeIntermediate = asn1_build_known_oid(OID_IKE_INTERMEDIATE);
     }
     if (cert->flags & X509_OCSP_SIGNER)
     {
         ocspSigning = asn1_build_known_oid(OID_OCSP_SIGNING);
     }
     if (cert->flags & X509_MS_SMARTCARD_LOGON)
     {
         msSmartcardLogon = asn1_build_known_oid(OID_MS_SMARTCARD_LOGON);
     }
     if (serverAuth.ptr || clientAuth.ptr || ikeIntermediate.ptr ||
         ocspSigning.ptr)
     {
         extendedKeyUsage = asn1_wrap(ASN1_SEQUENCE, "mm",
                                 asn1_build_known_oid(OID_EXTENDED_KEY_USAGE),
                                 asn1_wrap(ASN1_OCTET_STRING, "m",
                                     asn1_wrap(ASN1_SEQUENCE, "mmmmm",
                                         serverAuth, clientAuth, ikeIntermediate,
                                         ocspSigning, msSmartcardLogon)));
     }
     /* add subjectKeyIdentifier to CA and OCSP signer certificates */
     if (cert->flags & (X509_CA | X509_OCSP_SIGNER | X509_CRL_SIGN))
     {
         chunk_t keyid;
         if (cert->public_key->get_fingerprint(cert->public_key,
                                               KEYID_PUBKEY_SHA1, &keyid))
         {
             subjectKeyIdentifier = asn1_wrap(ASN1_SEQUENCE, "mm",
                                     asn1_build_known_oid(OID_SUBJECT_KEY_ID),
                                     asn1_wrap(ASN1_OCTET_STRING, "m",
                                         asn1_wrap(ASN1_OCTET_STRING, "c", keyid)));
         }
     }
     /* add the keyid authKeyIdentifier for non self-signed certificates */
     if (sign_cert)
     {
         chunk_t keyid;
         if (sign_key->get_fingerprint(sign_key, KEYID_PUBKEY_SHA1, &keyid))
         {
             authKeyIdentifier = asn1_wrap(ASN1_SEQUENCE, "mm",
                             asn1_build_known_oid(OID_AUTHORITY_KEY_ID),
                             asn1_wrap(ASN1_OCTET_STRING, "m",
                                 asn1_wrap(ASN1_SEQUENCE, "m",
                                     asn1_wrap(ASN1_CONTEXT_S_0, "c", keyid))));
         }
     }
     if (cert->permitted_names->get_count(cert->permitted_names) ||
         cert->excluded_names->get_count(cert->excluded_names))
     {
         chunk_t permitted = chunk_empty, excluded = chunk_empty, subtree;
         identification_t *id;
         enumerator = create_name_constraint_enumerator(cert, TRUE);
         while (enumerator->enumerate(enumerator, &id))
         {
             subtree = asn1_wrap(ASN1_SEQUENCE, "m", build_generalName(id));
             permitted = chunk_cat("mm", permitted, subtree);
         }
         enumerator->destroy(enumerator);
         if (permitted.ptr)
         {
             permitted = asn1_wrap(ASN1_CONTEXT_C_0, "m", permitted);
         }
         enumerator = create_name_constraint_enumerator(cert, FALSE);
         while (enumerator->enumerate(enumerator, &id))
         {
             subtree = asn1_wrap(ASN1_SEQUENCE, "m", build_generalName(id));
             excluded = chunk_cat("mm", excluded, subtree);
         }
         enumerator->destroy(enumerator);
         if (excluded.ptr)
         {
             excluded = asn1_wrap(ASN1_CONTEXT_C_1, "m", excluded);
         }
         nameConstraints = asn1_wrap(ASN1_SEQUENCE, "mm",
                             asn1_build_known_oid(OID_NAME_CONSTRAINTS),
                             asn1_wrap(ASN1_OCTET_STRING, "m",
                                 asn1_wrap(ASN1_SEQUENCE, "mm",
                                     permitted, excluded)));
     }
     if (cert->cert_policies->get_count(cert->cert_policies))
     {
         x509_cert_policy_t *policy;
         enumerator = create_cert_policy_enumerator(cert);
         while (enumerator->enumerate(enumerator, &policy))
         {
             chunk_t chunk = chunk_empty, cps = chunk_empty, notice = chunk_empty;
             if (policy->cps_uri)
             {
                 cps = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_build_known_oid(OID_POLICY_QUALIFIER_CPS),
                         asn1_wrap(ASN1_IA5STRING, "c",
                             chunk_create(policy->cps_uri,
                                          strlen(policy->cps_uri))));
             }
             if (policy->unotice_text)
             {
                 notice = asn1_wrap(ASN1_SEQUENCE, "mm",
                             asn1_build_known_oid(OID_POLICY_QUALIFIER_UNOTICE),
                             asn1_wrap(ASN1_SEQUENCE, "m",
                                 asn1_wrap(ASN1_VISIBLESTRING, "c",
                                     chunk_create(policy->unotice_text,
                                         strlen(policy->unotice_text)))));
             }
             if (cps.len || notice.len)
             {
                 chunk = asn1_wrap(ASN1_SEQUENCE, "mm", cps, notice);
             }
             chunk = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_wrap(ASN1_OID, "c", policy->oid), chunk);
             certPolicies = chunk_cat("mm", certPolicies, chunk);
         }
         enumerator->destroy(enumerator);
         certPolicies = asn1_wrap(ASN1_SEQUENCE, "mm",
                             asn1_build_known_oid(OID_CERTIFICATE_POLICIES),
                             asn1_wrap(ASN1_OCTET_STRING, "m",
                                 asn1_wrap(ASN1_SEQUENCE, "m", certPolicies)));
     }
     if (cert->policy_mappings->get_count(cert->policy_mappings))
     {
         x509_policy_mapping_t *mapping;
         enumerator = create_policy_mapping_enumerator(cert);
         while (enumerator->enumerate(enumerator, &mapping))
         {
             chunk_t chunk;
             chunk = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_wrap(ASN1_OID, "c", mapping->issuer),
                         asn1_wrap(ASN1_OID, "c", mapping->subject));
             policyMappings = chunk_cat("mm", policyMappings, chunk);
         }
         enumerator->destroy(enumerator);
         policyMappings = asn1_wrap(ASN1_SEQUENCE, "mm",
                             asn1_build_known_oid(OID_POLICY_MAPPINGS),
                             asn1_wrap(ASN1_OCTET_STRING, "m",
                                 asn1_wrap(ASN1_SEQUENCE, "m", policyMappings)));
     }
     if (cert->inhibit_mapping != X509_NO_CONSTRAINT ||
         cert->require_explicit != X509_NO_CONSTRAINT)
     {
         chunk_t inhibit = chunk_empty, explicit = chunk_empty;
         if (cert->require_explicit != X509_NO_CONSTRAINT)
         {
             explicit = asn1_wrap(ASN1_CONTEXT_C_0, "m",
                         asn1_integer("c",
                             chunk_from_thing(cert->require_explicit)));
         }
         if (cert->inhibit_mapping != X509_NO_CONSTRAINT)
         {
             inhibit = asn1_wrap(ASN1_CONTEXT_C_1, "m",
                         asn1_integer("c",
                             chunk_from_thing(cert->inhibit_mapping)));
         }
         policyConstraints = asn1_wrap(ASN1_SEQUENCE, "mmm",
                         asn1_build_known_oid(OID_POLICY_CONSTRAINTS),
                         asn1_wrap(ASN1_BOOLEAN, "c", chunk_from_chars(0xFF)),
                         asn1_wrap(ASN1_OCTET_STRING, "m",
                             asn1_wrap(ASN1_SEQUENCE, "mm",
                                 explicit, inhibit)));
     }
     if (cert->inhibit_any != X509_NO_CONSTRAINT)
     {
         inhibitAnyPolicy = asn1_wrap(ASN1_SEQUENCE, "mmm",
                 asn1_build_known_oid(OID_INHIBIT_ANY_POLICY),
                 asn1_wrap(ASN1_BOOLEAN, "c", chunk_from_chars(0xFF)),
                 asn1_wrap(ASN1_OCTET_STRING, "m",
                     asn1_integer("c",
                         chunk_from_thing(cert->inhibit_any))));
     }
     if (basicConstraints.ptr || subjectAltNames.ptr || authKeyIdentifier.ptr ||
         crlDistributionPoints.ptr || nameConstraints.ptr)
     {
         extensions = asn1_wrap(ASN1_CONTEXT_C_3, "m",
                         asn1_wrap(ASN1_SEQUENCE, "mmmmmmmmmmmmm",
                             basicConstraints, keyUsage, subjectKeyIdentifier,
                             authKeyIdentifier, subjectAltNames,
                             extendedKeyUsage, crlDistributionPoints,
                             authorityInfoAccess, nameConstraints, certPolicies,
                             policyMappings, policyConstraints, inhibitAnyPolicy));
     }
     cert->tbsCertificate = asn1_wrap(ASN1_SEQUENCE, "mmmcmcmm",
         asn1_simple_object(ASN1_CONTEXT_C_0, ASN1_INTEGER_2),
         asn1_integer("c", cert->serialNumber),
         asn1_algorithmIdentifier(cert->algorithm),
         issuer->get_encoding(issuer),
         asn1_wrap(ASN1_SEQUENCE, "mm",
             asn1_from_time(&cert->notBefore, ASN1_UTCTIME),
             asn1_from_time(&cert->notAfter, ASN1_UTCTIME)),
         subject->get_encoding(subject),
         key_info, extensions);
     if (!sign_key->sign(sign_key, scheme, cert->tbsCertificate, &cert->signature))
     {
         return FALSE;
     }
     cert->encoding = asn1_wrap(ASN1_SEQUENCE, "cmm", cert->tbsCertificate,
                                asn1_algorithmIdentifier(cert->algorithm),
                                asn1_bitstring("c", cert->signature));
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher ||
         !hasher->allocate_hash(hasher, cert->encoding, &cert->encoding_hash))
     {
         DESTROY_IF(hasher);
         return FALSE;
     }
     hasher->destroy(hasher);
     return TRUE;
 }
METHOD (certificate_t , get_type , certificate_type_t , private_x509_cert_t * this)
Definition at line 1504 of file x509_cert.c.
References CERT_X509.
 {
     return CERT_X509;
 }
METHOD (certificate_t , get_subject , identification_t * , private_x509_cert_t * this)
Definition at line 1510 of file x509_cert.c.
References subject.
 {
     return this->subject;
 }
METHOD (certificate_t , get_issuer , identification_t * , private_x509_cert_t * this)
Definition at line 1516 of file x509_cert.c.
 {
     return this->issuer;
 }
METHOD (certificate_t , has_subject , id_match_t , private_x509_cert_t * this, identification_t * subject)
Definition at line 1522 of file x509_cert.c.
References chunk_equals(), linked_list_t::create_enumerator, enumerator_t::destroy, encoding, enumerator_t::enumerate, identification_t::get_encoding, identification_t::get_type, public_key_t::has_fingerprint, ID_KEY_ID, ID_MATCH_PERFECT, match(), identification_t::matches, public_key, serialNumber, and subjectAltNames.
 {
     identification_t *current;
     enumerator_t *enumerator;
     id_match_t match, best;
     chunk_t encoding;
     if (subject->get_type(subject) == ID_KEY_ID)
     {
         encoding = subject->get_encoding(subject);
         if (this->encoding_hash.len &&
             chunk_equals(this->encoding_hash, encoding))
         {
             return ID_MATCH_PERFECT;
         }
         if (this->subjectKeyIdentifier.len &&
             chunk_equals(this->subjectKeyIdentifier, encoding))
         {
             return ID_MATCH_PERFECT;
         }
         if (this->public_key &&
             this->public_key->has_fingerprint(this->public_key, encoding))
         {
             return ID_MATCH_PERFECT;
         }
         if (chunk_equals(this->serialNumber, encoding))
         {
             return ID_MATCH_PERFECT;
         }
     }
     best = this->subject->matches(this->subject, subject);
     enumerator = this->subjectAltNames->create_enumerator(this->subjectAltNames);
     while (enumerator->enumerate(enumerator, &current))
     {
         match = current->matches(current, subject);
         if (match > best)
         {
             best = match;
         }
     }
     enumerator->destroy(enumerator);
     return best;
 }
METHOD (certificate_t , has_issuer , id_match_t , private_x509_cert_t * this, identification_t * issuer)
Definition at line 1568 of file x509_cert.c.
References identification_t::matches.
 {
     /* issuerAltNames currently not supported */
     return this->issuer->matches(this->issuer, issuer);
 }
METHOD (certificate_t , issued_by , bool , private_x509_cert_t * this, certificate_t * issuer, signature_scheme_t * schemep)
Definition at line 1575 of file x509_cert.c.
References algorithm, CERT_X509, public_key_t::destroy, certificate_t::equals, FALSE, flags, x509_t::get_flags, certificate_t::get_public_key, certificate_t::get_subject, certificate_t::get_type, key, scheme, SIGN_UNKNOWN, signature_scheme_from_oid(), TRUE, valid, public_key_t::verify, X509_CA, and X509_SELF_SIGNED.
 {
     public_key_t *key;
     signature_scheme_t scheme;
     bool valid;
     x509_t *x509 = (x509_t*)issuer;
     if (&this->public.interface.interface == issuer)
     {
         if (this->flags & X509_SELF_SIGNED)
         {
             return TRUE;
         }
     }
     else
     {
         if (issuer->get_type(issuer) != CERT_X509)
         {
             return FALSE;
         }
         if (!(x509->get_flags(x509) & X509_CA))
         {
             return FALSE;
         }
     }
     if (!this->issuer->equals(this->issuer, issuer->get_subject(issuer)))
     {
         return FALSE;
     }
     /* determine signature scheme */
     scheme = signature_scheme_from_oid(this->algorithm);
     if (scheme == SIGN_UNKNOWN)
     {
         return FALSE;
     }
     /* get the public key of the issuer */
     key = issuer->get_public_key(issuer);
     if (!key)
     {
         return FALSE;
     }
     valid = key->verify(key, scheme, this->tbsCertificate, this->signature);
     key->destroy(key);
     if (valid && schemep)
     {
         *schemep = scheme;
     }
     return valid;
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_x509_cert_t * this)
Definition at line 1628 of file x509_cert.c.
References public_key_t::get_ref, and public_key.
 {
     this->public_key->get_ref(this->public_key);
     return this->public_key;
 }
METHOD (certificate_t , get_ref , certificate_t * , private_x509_cert_t * this)
Definition at line 1635 of file x509_cert.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.interface.interface;
 }
METHOD (certificate_t , get_validity , bool , private_x509_cert_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 1642 of file x509_cert.c.
 {
     time_t t = when ? *when : time(NULL);
     if (not_before)
     {
         *not_before = this->notBefore;
     }
     if (not_after)
     {
         *not_after = this->notAfter;
     }
     return (t >= this->notBefore && t <= this->notAfter);
 }
METHOD (certificate_t , get_encoding , bool , private_x509_cert_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 1659 of file x509_cert.c.
References CERT_ASN1_DER, chunk_clone, CRED_PART_END, CRED_PART_X509_ASN1_DER, cred_encoding_t::encode, library_t::encoding, lib, and TRUE.
 {
     if (type == CERT_ASN1_DER)
     {
         *encoding = chunk_clone(this->encoding);
         return TRUE;
     }
     return lib->encoding->encode(lib->encoding, type, NULL, encoding,
                         CRED_PART_X509_ASN1_DER, this->encoding, CRED_PART_END);
 }
METHOD (certificate_t , equals , bool , private_x509_cert_t * this, certificate_t * other)
Definition at line 1671 of file x509_cert.c.
References CERT_ASN1_DER, CERT_X509, chunk_equals(), encoding, equals(), certificate_t::equals, FALSE, free(), certificate_t::get_encoding, certificate_t::get_type, chunk_t::ptr, and TRUE.
 {
     chunk_t encoding;
     bool equal;
     if (this == (private_x509_cert_t*)other)
     {
         return TRUE;
     }
     if (other->get_type(other) != CERT_X509)
     {
         return FALSE;
     }
     if (other->equals == (void*)equals)
     {   /* skip allocation if we have the same implementation */
         return chunk_equals(this->encoding, ((private_x509_cert_t*)other)->encoding);
     }
     if (!other->get_encoding(other, CERT_ASN1_DER, &encoding))
     {
         return FALSE;
     }
     equal = chunk_equals(this->encoding, encoding);
     free(encoding.ptr);
     return equal;
 }
METHOD (x509_t , get_flags , x509_flag_t , private_x509_cert_t * this)
Definition at line 1698 of file x509_cert.c.
References flags.
 {
     return this->flags;
 }
METHOD (x509_t , get_serial , chunk_t , private_x509_cert_t * this)
Definition at line 1704 of file x509_cert.c.
References serialNumber.
 {
     return this->serialNumber;
 }
METHOD (x509_t , get_subjectKeyIdentifier , chunk_t , private_x509_cert_t * this)
Definition at line 1710 of file x509_cert.c.
References chunk_empty, fingerprint, public_key_t::get_fingerprint, KEYID_PUBKEY_SHA1, and public_key.
 {
     if (this->subjectKeyIdentifier.ptr)
     {
         return this->subjectKeyIdentifier;
     }
     else
     {
         chunk_t fingerprint;
         if (this->public_key->get_fingerprint(this->public_key,
                                     KEYID_PUBKEY_SHA1, &fingerprint))
         {
             return fingerprint;
         }
         else
         {
             return chunk_empty;
         }
     }
 }
METHOD (x509_t , get_authKeyIdentifier , chunk_t , private_x509_cert_t * this)
Definition at line 1733 of file x509_cert.c.
 {
     return this->authKeyIdentifier;
 }
METHOD (x509_t , get_constraint , u_int , private_x509_cert_t * this, x509_constraint_t type)
Definition at line 1739 of file x509_cert.c.
References X509_INHIBIT_ANY_POLICY, X509_INHIBIT_POLICY_MAPPING, X509_NO_CONSTRAINT, X509_PATH_LEN, and X509_REQUIRE_EXPLICIT_POLICY.
 {
     switch (type)
     {
         case X509_PATH_LEN:
             return this->pathLenConstraint;
         case X509_REQUIRE_EXPLICIT_POLICY:
             return this->require_explicit;
         case X509_INHIBIT_POLICY_MAPPING:
             return this->inhibit_mapping;
         case X509_INHIBIT_ANY_POLICY:
             return this->inhibit_any;
         default:
             return X509_NO_CONSTRAINT;
     }
 }
METHOD (x509_t , create_subjectAltName_enumerator , enumerator_t * , private_x509_cert_t * this)
Definition at line 1757 of file x509_cert.c.
References linked_list_t::create_enumerator, and subjectAltNames.
 {
     return this->subjectAltNames->create_enumerator(this->subjectAltNames);
 }
METHOD (x509_t , create_ocsp_uri_enumerator , enumerator_t * , private_x509_cert_t * this)
Definition at line 1763 of file x509_cert.c.
 {
     return this->ocsp_uris->create_enumerator(this->ocsp_uris);
 }
METHOD (x509_t , create_crl_uri_enumerator , enumerator_t * , private_x509_cert_t * this)
Definition at line 1769 of file x509_cert.c.
 {
     return this->crl_uris->create_enumerator(this->crl_uris);
 }
METHOD (x509_t , create_ipAddrBlock_enumerator , enumerator_t * , private_x509_cert_t * this)
Definition at line 1775 of file x509_cert.c.
 {
     return this->ipAddrBlocks->create_enumerator(this->ipAddrBlocks);
 }
METHOD (x509_t , create_name_constraint_enumerator , enumerator_t * , private_x509_cert_t * this, bool perm)
Definition at line 1781 of file x509_cert.c.
 {
     if (perm)
     {
         return this->permitted_names->create_enumerator(this->permitted_names);
     }
     return this->excluded_names->create_enumerator(this->excluded_names);
 }
METHOD (x509_t , create_cert_policy_enumerator , enumerator_t * , private_x509_cert_t * this)
Definition at line 1791 of file x509_cert.c.
 {
     return this->cert_policies->create_enumerator(this->cert_policies);
 }
METHOD (x509_t , create_policy_mapping_enumerator , enumerator_t * , private_x509_cert_t * this)
Definition at line 1797 of file x509_cert.c.
 {
     return this->policy_mappings->create_enumerator(this->policy_mappings);
 }
METHOD (certificate_t , destroy , void , private_x509_cert_t * this)
Definition at line 1803 of file x509_cert.c.
References cert_policy_destroy(), chunk_free(), crl_uri_destroy(), destroy(), DESTROY_IF, linked_list_t::destroy_offset, encoding, free(), policy_mapping_destroy(), public_key, ref_put(), serialNumber, subject, and subjectAltNames.
 {
     if (ref_put(&this->ref))
     {
         this->subjectAltNames->destroy_offset(this->subjectAltNames,
                                     offsetof(identification_t, destroy));
         this->crl_uris->destroy_function(this->crl_uris, (void*)crl_uri_destroy);
         this->ocsp_uris->destroy_function(this->ocsp_uris, free);
         this->ipAddrBlocks->destroy_offset(this->ipAddrBlocks,
                                         offsetof(traffic_selector_t, destroy));
         this->permitted_names->destroy_offset(this->permitted_names,
                                         offsetof(identification_t, destroy));
         this->excluded_names->destroy_offset(this->excluded_names,
                                         offsetof(identification_t, destroy));
         this->cert_policies->destroy_function(this->cert_policies,
                                               (void*)cert_policy_destroy);
         this->policy_mappings->destroy_function(this->policy_mappings,
                                               (void*)policy_mapping_destroy);
         DESTROY_IF(this->issuer);
         DESTROY_IF(this->subject);
         DESTROY_IF(this->public_key);
         chunk_free(&this->authKeyIdentifier);
         chunk_free(&this->encoding);
         chunk_free(&this->encoding_hash);
         if (!this->parsed)
         {   /* only parsed certificates point these fields to "encoded" */
             chunk_free(&this->signature);
             chunk_free(&this->serialNumber);
             chunk_free(&this->tbsCertificate);
         }
         free(this);
     }
 }
static void parse_authorityInfoAccess (chunk_t blob, int level0, private_x509_cert_t * this) static
Extracts an authorityInfoAcess location
Definition at line 602 of file x509_cert.c.
References asn1_known_oid(), asn1_parser_create(), asprintf(), AUTH_INFO_ACCESS_LOCATION, AUTH_INFO_ACCESS_METHOD, DBG2, DBG_ASN, asn1_parser_t::destroy, end, asn1_parser_t::get_level, id, asn1_parser_t::iterate, OID_CA_ISSUERS, OID_OCSP, OID_UNKNOWN, parse_generalName(), parser, asn1_parser_t::set_top_level, and uri.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int accessMethod = OID_UNKNOWN;
     parser = asn1_parser_create(authInfoAccessObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case AUTH_INFO_ACCESS_METHOD:
                 accessMethod = asn1_known_oid(object);
                 break;
             case AUTH_INFO_ACCESS_LOCATION:
             {
                 switch (accessMethod)
                 {
                     case OID_OCSP:
                     case OID_CA_ISSUERS:
{
                             identification_t *id;
                             char *uri;
                             id = parse_generalName(object,
                                             parser->get_level(parser)+1);
                             if (id == NULL)
{
                                 /* parsing went wrong - abort */
                                 goto end;
                             }
                             DBG2(DBG_ASN, "  '%Y'", id);
                             if (accessMethod == OID_OCSP &&
                                 asprintf(&uri, "%Y", id) > 0)
{
                                 this->ocsp_uris->insert_last(this->ocsp_uris, uri);
                             }
                             id->destroy(id);
                         }
                         break;
                     default:
                         /* unknown accessMethod, ignoring */
                         break;
                 }
                 break;
             }
             default:
                 break;
         }
     }
 end:
     parser->destroy(parser);
 }
static void parse_basicConstraints (chunk_t blob, int level0, private_x509_cert_t * this) static
Extracts the basicConstraints extension
Definition at line 283 of file x509_cert.c.
References asn1_parser_create(), BASIC_CONSTRAINTS_CA, BASIC_CONSTRAINTS_PATH_LEN, DBG2, DBG_ASN, asn1_parser_t::destroy, FALSE, flags, asn1_parser_t::iterate, parse_constraint(), parser, asn1_parser_t::set_top_level, and X509_CA.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool isCA = FALSE;
     parser = asn1_parser_create(basicConstraintsObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case BASIC_CONSTRAINTS_CA:
                 isCA = object.len && *object.ptr;
                 DBG2(DBG_ASN, "  %s", isCA ? "TRUE" : "FALSE");
                 if (isCA)
                 {
                     this->flags |= X509_CA;
                 }
                 break;
             case BASIC_CONSTRAINTS_PATH_LEN:
                 if (isCA)
                 {
                     this->pathLenConstraint = parse_constraint(object);
                 }
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
 }
static bool parse_certificate (private_x509_cert_t * this) static
Parses an X.509v3 certificate
Definition at line 1300 of file x509_cert.c.
References algorithm, hasher_t::allocate_hash, ASN1_IA5STRING, ASN1_INTEGER, asn1_known_oid(), ASN1_OCTET_STRING, asn1_parse_algorithmIdentifier(), asn1_parse_simple_object(), asn1_parse_time(), asn1_parser_create(), BUILD_BLOB_ASN1_DER, BUILD_END, chunk_skip(), credential_factory_t::create, crypto_factory_t::create_hasher, CRED_PUBLIC_KEY, library_t::creds, library_t::crypto, DBG1, DBG2, DBG_ASN, asn1_parser_t::destroy, hasher_t::destroy, DESTROY_IF, encoding, end, FALSE, flags, settings_t::get_bool, asn1_parser_t::get_level, HASH_SHA1, hasher, ID_DER_ASN1_DN, identification_create_from_encoding(), asn1_parser_t::iterate, KEY_ANY, lib, name, library_t::ns, OID_AUTHORITY_INFO_ACCESS, OID_AUTHORITY_KEY_ID, OID_BASIC_CONSTRAINTS, OID_CERTIFICATE_POLICIES, OID_CRL_DISTRIBUTION_POINTS, OID_EXTENDED_KEY_USAGE, OID_INHIBIT_ANY_POLICY, OID_IP_ADDR_BLOCKS, OID_KEY_USAGE, OID_NAME_CONSTRAINTS, oid_names, OID_NS_CA_POLICY_URL, OID_NS_CA_REVOCATION_URL, OID_NS_COMMENT, OID_NS_REVOCATION_URL, OID_POLICY_CONSTRAINTS, OID_POLICY_MAPPINGS, OID_SUBJECT_ALT_NAME, OID_SUBJECT_KEY_ID, OID_UNKNOWN, parse_authorityInfoAccess(), parse_basicConstraints(), parse_certificatePolicies(), parse_constraint(), parse_extendedKeyUsage(), parse_ipAddrBlocks(), parse_keyUsage(), parse_nameConstraints(), parse_policyConstraints(), parse_policyMappings(), parser, public_key, serialNumber, library_t::settings, subject, subjectAltNames, asn1_parser_t::success, TRUE, version, X509_OBJ_ALGORITHM, X509_OBJ_CRITICAL, X509_OBJ_EXTN_ID, X509_OBJ_EXTN_VALUE, X509_OBJ_ISSUER, X509_OBJ_NOT_AFTER, X509_OBJ_NOT_BEFORE, X509_OBJ_OPTIONAL_EXTENSIONS, X509_OBJ_SERIAL_NUMBER, X509_OBJ_SIG_ALG, X509_OBJ_SIGNATURE, X509_OBJ_SUBJECT, X509_OBJ_SUBJECT_PUBLIC_KEY_INFO, X509_OBJ_TBS_CERTIFICATE, X509_OBJ_VERSION, x509_parse_authorityKeyIdentifier(), x509_parse_crlDistributionPoints(), x509_parse_generalNames(), and X509_SELF_SIGNED.
Referenced by x509_cert_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int extn_oid = OID_UNKNOWN;
     int sig_alg  = OID_UNKNOWN;
     bool success = FALSE;
     bool critical = FALSE;
     parser = asn1_parser_create(certObjects, this->encoding);
     while (parser->iterate(parser, &objectID, &object))
     {
         u_int level = parser->get_level(parser)+1;
         switch (objectID)
         {
             case X509_OBJ_TBS_CERTIFICATE:
                 this->tbsCertificate = object;
                 break;
             case X509_OBJ_VERSION:
                 this->version = (object.len) ? (1+(u_int)*object.ptr) : 1;
                 if (this->version < 1 || this->version > 3)
                 {
                     DBG1(DBG_ASN, "X.509v%d not supported", this->version);
                     goto end;
                 }
                 else
                 {
                     DBG2(DBG_ASN, "  X.509v%d", this->version);
                 }
                 break;
             case X509_OBJ_SERIAL_NUMBER:
                 this->serialNumber = object;
                 break;
             case X509_OBJ_SIG_ALG:
                 sig_alg = asn1_parse_algorithmIdentifier(object, level, NULL);
                 break;
             case X509_OBJ_ISSUER:
                 this->issuer = identification_create_from_encoding(ID_DER_ASN1_DN, object);
                 DBG2(DBG_ASN, "  '%Y'", this->issuer);
                 break;
             case X509_OBJ_NOT_BEFORE:
                 this->notBefore = asn1_parse_time(object, level);
                 break;
             case X509_OBJ_NOT_AFTER:
                 this->notAfter = asn1_parse_time(object, level);
                 break;
             case X509_OBJ_SUBJECT:
                 this->subject = identification_create_from_encoding(ID_DER_ASN1_DN, object);
                 DBG2(DBG_ASN, "  '%Y'", this->subject);
                 break;
             case X509_OBJ_SUBJECT_PUBLIC_KEY_INFO:
                 DBG2(DBG_ASN, "-- > --");
                 this->public_key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY,
                         KEY_ANY, BUILD_BLOB_ASN1_DER, object, BUILD_END);
                 DBG2(DBG_ASN, "-- < --");
                 if (this->public_key == NULL)
                 {
                     goto end;
                 }
                 break;
             case X509_OBJ_OPTIONAL_EXTENSIONS:
                 if (this->version != 3)
                 {
                     DBG1(DBG_ASN, "Only X.509v3 certificates have extensions");
                     goto end;
                 }
                 break;
             case X509_OBJ_EXTN_ID:
                 extn_oid = asn1_known_oid(object);
                 break;
             case X509_OBJ_CRITICAL:
                 critical = object.len && *object.ptr;
                 DBG2(DBG_ASN, "  %s", critical ? "TRUE" : "FALSE");
                 break;
             case X509_OBJ_EXTN_VALUE:
             {
                 switch (extn_oid)
                 {
                     case OID_SUBJECT_KEY_ID:
                         if (!asn1_parse_simple_object(&object, ASN1_OCTET_STRING,
                                                       level, "keyIdentifier"))
{
                             goto end;
                         }
                         this->subjectKeyIdentifier = object;
                         break;
                     case OID_SUBJECT_ALT_NAME:
                         x509_parse_generalNames(object, level, FALSE,
                                                 this->subjectAltNames);
                         break;
                     case OID_BASIC_CONSTRAINTS:
                         parse_basicConstraints(object, level, this);
                         break;
                     case OID_CRL_DISTRIBUTION_POINTS:
                         x509_parse_crlDistributionPoints(object, level,
                                                          this->crl_uris);
                         break;
                     case OID_AUTHORITY_KEY_ID:
                         this->authKeyIdentifier = x509_parse_authorityKeyIdentifier(object,
                                                         level, &this->authKeySerialNumber);
                         break;
                     case OID_AUTHORITY_INFO_ACCESS:
                         parse_authorityInfoAccess(object, level, this);
                         break;
                     case OID_KEY_USAGE:
                         parse_keyUsage(object, this);
                         break;
                     case OID_EXTENDED_KEY_USAGE:
                         parse_extendedKeyUsage(object, level, this);
                         break;
                     case OID_IP_ADDR_BLOCKS:
                         parse_ipAddrBlocks(object, level, this);
                         break;
                     case OID_NAME_CONSTRAINTS:
                         parse_nameConstraints(object, level, this);
                         break;
                     case OID_CERTIFICATE_POLICIES:
                         parse_certificatePolicies(object, level, this);
                         break;
                     case OID_POLICY_MAPPINGS:
                         parse_policyMappings(object, level, this);
                         break;
                     case OID_POLICY_CONSTRAINTS:
                         parse_policyConstraints(object, level, this);
                         break;
                     case OID_INHIBIT_ANY_POLICY:
                         if (!asn1_parse_simple_object(&object, ASN1_INTEGER,
                                                       level, "inhibitAnyPolicy"))
{
                             goto end;
                         }
                         this->inhibit_any = parse_constraint(object);
                         break;
                     case OID_NS_REVOCATION_URL:
                     case OID_NS_CA_REVOCATION_URL:
                     case OID_NS_CA_POLICY_URL:
                     case OID_NS_COMMENT:
                         if (!asn1_parse_simple_object(&object, ASN1_IA5STRING,
                                             level, oid_names[extn_oid].name))
{
                             goto end;
                         }
                         break;
                     default:
                         if (critical && lib->settings->get_bool(lib->settings,
                             "%s.x509.enforce_critical", TRUE, lib->ns))
{
                             DBG1(DBG_ASN, "critical '%s' extension not supported",
                                  (extn_oid == OID_UNKNOWN) ? "unknown" :
                                  (char*)oid_names[extn_oid].name);
                             goto end;
                         }
                         break;
                 }
                 break;
             }
             case X509_OBJ_ALGORITHM:
                 this->algorithm = asn1_parse_algorithmIdentifier(object, level, NULL);
                 if (this->algorithm != sig_alg)
                 {
                     DBG1(DBG_ASN, "  signature algorithms do not agree");
                     goto end;
                 }
                 break;
             case X509_OBJ_SIGNATURE:
                 this->signature = chunk_skip(object, 1);
                 break;
             default:
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     if (success)
     {
         hasher_t *hasher;
         /* check if the certificate is self-signed */
         if (this->public.interface.interface.issued_by(
                                             &this->public.interface.interface,
                                             &this->public.interface.interface,
                                             NULL))
         {
             this->flags |= X509_SELF_SIGNED;
         }
         /* create certificate hash */
         hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
         if (!hasher ||
             !hasher->allocate_hash(hasher, this->encoding, &this->encoding_hash))
         {
             DESTROY_IF(hasher);
             DBG1(DBG_ASN, "  unable to create hash of certificate, SHA1 not supported");
             return FALSE;
         }
         hasher->destroy(hasher);
     }
     return success;
 }
static void parse_certificatePolicies (chunk_t blob, int level0, private_x509_cert_t * this) static
Parse certificatePolicies
Definition at line 962 of file x509_cert.c.
References asn1_known_oid(), asn1_parser_create(), CERT_POLICY_CPS_URI, CERT_POLICY_EXPLICIT_TEXT, CERT_POLICY_ID, CERT_POLICY_QUALIFIER_ID, chunk_clone, chunk_printable(), x509_cert_policy_t::cps_uri, asn1_parser_t::destroy, INIT, asn1_parser_t::iterate, len, OID_POLICY_QUALIFIER_CPS, OID_UNKNOWN, parser, asn1_parser_t::set_top_level, and strndup().
Referenced by parse_certificate().
 {
     x509_cert_policy_t *policy = NULL;
     asn1_parser_t *parser;
     chunk_t object;
     int objectID, qualifier = OID_UNKNOWN;
     parser = asn1_parser_create(certificatePoliciesObject, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case CERT_POLICY_ID:
                 INIT(policy,
                     .oid = chunk_clone(object),
                 );
                 this->cert_policies->insert_last(this->cert_policies, policy);
                 break;
             case CERT_POLICY_QUALIFIER_ID:
                 qualifier = asn1_known_oid(object);
                 break;
             case CERT_POLICY_CPS_URI:
                 if (policy && !policy->cps_uri && object.len &&
                     qualifier == OID_POLICY_QUALIFIER_CPS &&
                     chunk_printable(object, NULL, 0))
                 {
                     policy->cps_uri = strndup(object.ptr, object.len);
                 }
                 break;
             case CERT_POLICY_EXPLICIT_TEXT:
                 /* TODO */
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
 }
static u_int parse_constraint (chunk_t object) static
Parse a length constraint from an unwrapped integer
Definition at line 254 of file x509_cert.c.
References len, and X509_NO_CONSTRAINT.
Referenced by parse_basicConstraints(), parse_certificate(), and parse_policyConstraints().
 {
     switch (object.len)
     {
         case 0:
             return 0;
         case 1:
             return (object.ptr[0] & 0x80) ? X509_NO_CONSTRAINT : object.ptr[0];
         default:
             return X509_NO_CONSTRAINT;
     }
 }
static void parse_extendedKeyUsage (chunk_t blob, int level0, private_x509_cert_t * this) static
Extracts extendedKeyUsage OIDs
Definition at line 729 of file x509_cert.c.
References asn1_known_oid(), asn1_parser_create(), asn1_parser_t::destroy, EXT_KEY_USAGE_PURPOSE_ID, flags, asn1_parser_t::iterate, OID_CLIENT_AUTH, OID_IKE_INTERMEDIATE, OID_MS_SMARTCARD_LOGON, OID_OCSP_SIGNING, OID_SERVER_AUTH, parser, asn1_parser_t::set_top_level, X509_CLIENT_AUTH, X509_IKE_INTERMEDIATE, X509_MS_SMARTCARD_LOGON, X509_OCSP_SIGNER, and X509_SERVER_AUTH.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(extendedKeyUsageObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         if (objectID == EXT_KEY_USAGE_PURPOSE_ID)
         {
             switch (asn1_known_oid(object))
             {
                 case OID_SERVER_AUTH:
                     this->flags |= X509_SERVER_AUTH;
                     break;
                 case OID_CLIENT_AUTH:
                     this->flags |= X509_CLIENT_AUTH;
                     break;
                 case OID_IKE_INTERMEDIATE:
                     this->flags |= X509_IKE_INTERMEDIATE;
                     break;
                 case OID_OCSP_SIGNING:
                     this->flags |= X509_OCSP_SIGNER;
                     break;
                 case OID_MS_SMARTCARD_LOGON:
                     this->flags |= X509_MS_SMARTCARD_LOGON;
                     break;
                 default:
                     break;
             }
         }
     }
     parser->destroy(parser);
 }
static identification_t* parse_generalName (chunk_t blob, int level0) static
Extracts a generalName
Definition at line 423 of file x509_cert.c.
References asn1_parser_create(), DBG2, DBG_ASN, asn1_parser_t::destroy, end, asn1_parser_t::get_level, GN_OBJ_DIRECTORY_NAME, GN_OBJ_DNS_NAME, GN_OBJ_EDI_PARTY_NAME, GN_OBJ_IP_ADDRESS, GN_OBJ_OTHER_NAME, GN_OBJ_REGISTERED_ID, GN_OBJ_RFC822_NAME, GN_OBJ_URI, GN_OBJ_X400_ADDRESS, ID_ANY, ID_DER_ASN1_DN, ID_DER_ASN1_GN_URI, ID_FQDN, ID_IPV4_ADDR, ID_IPV6_ADDR, ID_RFC822_ADDR, identification_create_from_encoding(), asn1_parser_t::iterate, len, parse_otherName(), parser, and asn1_parser_t::set_top_level.
Referenced by parse_authorityInfoAccess(), parse_nameConstraints(), and x509_parse_generalNames().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID ;
     identification_t *gn = NULL;
     parser = asn1_parser_create(generalNameObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         id_type_t id_type = ID_ANY;
         switch (objectID)
         {
             case GN_OBJ_RFC822_NAME:
                 id_type = ID_RFC822_ADDR;
                 break;
             case GN_OBJ_DNS_NAME:
                 id_type = ID_FQDN;
                 break;
             case GN_OBJ_URI:
                 id_type = ID_DER_ASN1_GN_URI;
                 break;
             case GN_OBJ_DIRECTORY_NAME:
                 id_type = ID_DER_ASN1_DN;
                 break;
             case GN_OBJ_IP_ADDRESS:
                 switch (object.len)
                 {
                     case 4:
                         id_type = ID_IPV4_ADDR;
                         break;
                     case 16:
                         id_type = ID_IPV6_ADDR;
                         break;
                     default:
                         break;
                 }
                 break;
             case GN_OBJ_OTHER_NAME:
                 if (!parse_otherName(&object, parser->get_level(parser)+1,
                                      &id_type))
                 {
                     goto end;
                 }
                 break;
             case GN_OBJ_X400_ADDRESS:
             case GN_OBJ_EDI_PARTY_NAME:
             case GN_OBJ_REGISTERED_ID:
             default:
                 break;
         }
         if (id_type != ID_ANY)
         {
             gn = identification_create_from_encoding(id_type, object);
             DBG2(DBG_ASN, "  '%Y'", gn);
             goto end;
         }
     }
 end:
     parser->destroy(parser);
     return gn;
 }
static void parse_ipAddrBlocks (chunk_t blob, int level0, private_x509_cert_t * this) static
Definition at line 1174 of file x509_cert.c.
References asn1_parser_create(), check_address_object(), DBG1, DBG2, DBG_ASN, asn1_parser_t::destroy, end, flags, IP_ADDR_BLOCKS_FAMILY, IP_ADDR_BLOCKS_INHERIT, IP_ADDR_BLOCKS_MAX, IP_ADDR_BLOCKS_MIN, IP_ADDR_BLOCKS_PREFIX, asn1_parser_t::iterate, len, parser, asn1_parser_t::set_top_level, traffic_selector_create_from_rfc3779_format(), TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, ts_type_name, and X509_IP_ADDR_BLOCKS.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object, min_object;
     ts_type_t ts_type = 0;
     traffic_selector_t *ts;
     int objectID;
     parser = asn1_parser_create(ipAddrBlocksObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case IP_ADDR_BLOCKS_FAMILY:
                 ts_type = 0;
                 if (object.len == 2 && object.ptr[0] == 0)
                 {
                     if (object.ptr[1] == 1)
                     {
                         ts_type = TS_IPV4_ADDR_RANGE;
                     }
                     else if (object.ptr[1] == 2)
                     {
                         ts_type = TS_IPV6_ADDR_RANGE;
                     }
                     else
                     {
                         break;
                     }
                     DBG2(DBG_ASN, "  %N", ts_type_name, ts_type);
                 }
                 break;
             case IP_ADDR_BLOCKS_INHERIT:
                 DBG1(DBG_ASN, "inherit choice is not supported");
                 break;
             case IP_ADDR_BLOCKS_PREFIX:
                 if (!check_address_object(ts_type, object))
                 {
                     goto end;
                 }
                 ts = traffic_selector_create_from_rfc3779_format(ts_type,
                                                     object, object);
                 DBG2(DBG_ASN, "  %R", ts);
                 this->ipAddrBlocks->insert_last(this->ipAddrBlocks, ts);
                 break;
             case IP_ADDR_BLOCKS_MIN:
                 if (!check_address_object(ts_type, object))
                 {
                     goto end;
                 }
                 min_object = object;
                 break;
             case IP_ADDR_BLOCKS_MAX:
                 if (!check_address_object(ts_type, object))
                 {
                     goto end;
                 }
                 ts = traffic_selector_create_from_rfc3779_format(ts_type,
                                                     min_object, object);
                 DBG2(DBG_ASN, "  %R", ts);
                 this->ipAddrBlocks->insert_last(this->ipAddrBlocks, ts);
                 break;
             default:
                 break;
         }
     }
     this->flags |= X509_IP_ADDR_BLOCKS;
 end:
     parser->destroy(parser);
 }
static void parse_keyUsage (chunk_t blob, private_x509_cert_t * this) static
Extract KeyUsage flags
Definition at line 664 of file x509_cert.c.
References ASN1_BIT_STRING, asn1_unwrap(), chunk_skip(), flags, chunk_t::len, chunk_t::ptr, unused, and X509_CRL_SIGN.
Referenced by parse_certificate().
 {
     enum {
         KU_DIGITAL_SIGNATURE =  0,
         KU_NON_REPUDIATION =    1,
         KU_KEY_ENCIPHERMENT =   2,
         KU_DATA_ENCIPHERMENT =  3,
         KU_KEY_AGREEMENT =      4,
         KU_KEY_CERT_SIGN =      5,
         KU_CRL_SIGN =           6,
         KU_ENCIPHER_ONLY =      7,
         KU_DECIPHER_ONLY =      8,
     };
     if (asn1_unwrap(&blob, &blob) == ASN1_BIT_STRING && blob.len)
     {
         int bit, byte, unused = blob.ptr[0];
         blob = chunk_skip(blob, 1);
         for (byte = 0; byte < blob.len; byte++)
         {
             for (bit = 0; bit < 8; bit++)
             {
                 if (byte == blob.len - 1 && bit > (7 - unused))
                 {
                     break;
                 }
                 if (blob.ptr[byte] & 1 << (7 - bit))
                 {
                     switch (byte * 8 + bit)
                     {
                         case KU_CRL_SIGN:
                             this->flags |= X509_CRL_SIGN;
                             break;
                         case KU_KEY_CERT_SIGN:
                             /* we use the caBasicConstraint, MUST be set */
                         case KU_DIGITAL_SIGNATURE:
                         case KU_NON_REPUDIATION:
                         case KU_KEY_ENCIPHERMENT:
                         case KU_DATA_ENCIPHERMENT:
                         case KU_KEY_AGREEMENT:
                         case KU_ENCIPHER_ONLY:
                         case KU_DECIPHER_ONLY:
                             break;
                     }
                 }
             }
         }
     }
 }
static void parse_nameConstraints (chunk_t blob, int level0, private_x509_cert_t * this) static
Parse permitted/excluded nameConstraints
Definition at line 899 of file x509_cert.c.
References asn1_parser_create(), asn1_parser_t::destroy, asn1_parser_t::get_level, id, asn1_parser_t::iterate, NAME_CONSTRAINT_EXCLUDED, NAME_CONSTRAINT_PERMITTED, parse_generalName(), parser, and asn1_parser_t::set_top_level.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     identification_t *id;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(nameConstraintsObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case NAME_CONSTRAINT_PERMITTED:
                 id = parse_generalName(object, parser->get_level(parser) + 1);
                 if (id)
                 {
                     this->permitted_names->insert_last(this->permitted_names, id);
                 }
                 break;
             case NAME_CONSTRAINT_EXCLUDED:
                 id = parse_generalName(object, parser->get_level(parser) + 1);
                 if (id)
                 {
                     this->excluded_names->insert_last(this->excluded_names, id);
                 }
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
 }
static bool parse_otherName (chunk_t * blob, int level0, id_type_t * type) static
Extracts an otherName
Definition at line 333 of file x509_cert.c.
References asn1_known_oid(), asn1_parse_simple_object(), asn1_parser_create(), ASN1_UTF8STRING, asn1_parser_t::destroy, end, FALSE, asn1_parser_t::get_level, ID_RFC822_ADDR, asn1_parser_t::iterate, OID_UNKNOWN, OID_USER_PRINCIPAL_NAME, OID_XMPP_ADDR, ON_OBJ_ID_TYPE, ON_OBJ_VALUE, parser, asn1_parser_t::set_top_level, and asn1_parser_t::success.
Referenced by parse_generalName().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int oid = OID_UNKNOWN;
     bool success = FALSE;
     parser = asn1_parser_create(otherNameObjects, *blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case ON_OBJ_ID_TYPE:
                 oid = asn1_known_oid(object);
                 break;
             case ON_OBJ_VALUE:
                 switch (oid)
                 {
                     case OID_XMPP_ADDR:
                         if (!asn1_parse_simple_object(&object, ASN1_UTF8STRING,
                                     parser->get_level(parser)+1, "xmppAddr"))
{
                             goto end;
                         }
                         break;
                     case OID_USER_PRINCIPAL_NAME:
                         if (asn1_parse_simple_object(&object, ASN1_UTF8STRING,
                                     parser->get_level(parser)+1, "msUPN"))
                         {   /* we handle UPNs as RFC822 addr */
                             *blob = object;
                             *type = ID_RFC822_ADDR;
                         }
                         else
{
                             goto end;
                         }
                         break;
                 }
                 break;
             default:
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     return success;
 }
static void parse_policyConstraints (chunk_t blob, int level0, private_x509_cert_t * this) static
Parse policyConstraints
Definition at line 1079 of file x509_cert.c.
References asn1_parser_create(), asn1_parser_t::destroy, asn1_parser_t::iterate, parse_constraint(), parser, POLICY_CONSTRAINT_EXPLICIT, POLICY_CONSTRAINT_INHIBIT, and asn1_parser_t::set_top_level.
Referenced by parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(policyConstraintsObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case POLICY_CONSTRAINT_EXPLICIT:
                 this->require_explicit = parse_constraint(object);
                 break;
             case POLICY_CONSTRAINT_INHIBIT:
                 this->inhibit_mapping = parse_constraint(object);
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
 }
static void parse_policyMappings (chunk_t blob, int level0, private_x509_cert_t * this) static
Parse policyMappings
Definition at line 1022 of file x509_cert.c.
References asn1_parser_create(), chunk_clone, asn1_parser_t::destroy, INIT, x509_policy_mapping_t::issuer, asn1_parser_t::iterate, chunk_t::len, parser, POLICY_MAPPING, POLICY_MAPPING_ISSUER, POLICY_MAPPING_SUBJECT, asn1_parser_t::set_top_level, and x509_policy_mapping_t::subject.
Referenced by parse_certificate().
 {
     x509_policy_mapping_t *map = NULL;
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(policyMappingsObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case POLICY_MAPPING:
                 INIT(map);
                 this->policy_mappings->insert_last(this->policy_mappings, map);
                 break;
             case POLICY_MAPPING_ISSUER:
                 if (map && !map->issuer.len)
                 {
                     map->issuer = chunk_clone(object);
                 }
                 break;
             case POLICY_MAPPING_SUBJECT:
                 if (map && !map->subject.len)
                 {
                     map->subject = chunk_clone(object);
                 }
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
 }
static void policy_mapping_destroy (x509_policy_mapping_t * mapping) static
Free policy mapping
Definition at line 244 of file x509_cert.c.
References free(), x509_policy_mapping_t::issuer, chunk_t::ptr, and x509_policy_mapping_t::subject.
Referenced by METHOD().
 {
     free(mapping->issuer.ptr);
     free(mapping->subject.ptr);
     free(mapping);
 }
chunk_t x509_build_crlDistributionPoints (linked_list_t * list, int extn)
Encode CRL distribution points extension from a x509_cdp_t list
Definition at line 1957 of file x509_cert.c.
References asn1_build_known_oid(), ASN1_CONTEXT_C_0, ASN1_CONTEXT_C_2, ASN1_CONTEXT_S_6, ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_wrap(), build_generalName(), chunk_cat, chunk_create(), chunk_empty, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, x509_cdp_t::issuer, and x509_cdp_t::uri.
Referenced by generate().
 {
     chunk_t crlDistributionPoints = chunk_empty;
     enumerator_t *enumerator;
     x509_cdp_t *cdp;
     if (list->get_count(list) == 0)
     {
         return chunk_empty;
     }
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &cdp))
     {
         chunk_t distributionPoint, crlIssuer = chunk_empty;
         if (cdp->issuer)
         {
             crlIssuer = asn1_wrap(ASN1_CONTEXT_C_2, "m",
                             build_generalName(cdp->issuer));
         }
         distributionPoint = asn1_wrap(ASN1_SEQUENCE, "mm",
                     asn1_wrap(ASN1_CONTEXT_C_0, "m",
                         asn1_wrap(ASN1_CONTEXT_C_0, "m",
                             asn1_wrap(ASN1_CONTEXT_S_6, "c",
                                 chunk_create(cdp->uri, strlen(cdp->uri))))),
                     crlIssuer);
         crlDistributionPoints = chunk_cat("mm", crlDistributionPoints,
                                           distributionPoint);
     }
     enumerator->destroy(enumerator);
     return asn1_wrap(ASN1_SEQUENCE, "mm",
                 asn1_build_known_oid(extn),
                 asn1_wrap(ASN1_OCTET_STRING, "m",
                     asn1_wrap(ASN1_SEQUENCE, "m", crlDistributionPoints)));
 }
chunk_t x509_build_subjectAltNames (linked_list_t * list)
Encode a linked list of subjectAltNames
Definition at line 1927 of file x509_cert.c.
References asn1_build_known_oid(), ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_wrap(), build_generalName(), chunk_cat, chunk_empty, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, id, name, OID_SUBJECT_ALT_NAME, and subjectAltNames.
Referenced by generate().
 {
     chunk_t subjectAltNames = chunk_empty, name;
     enumerator_t *enumerator;
     identification_t *id;
     if (list->get_count(list) == 0)
     {
         return chunk_empty;
     }
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &id))
     {
         name = build_generalName(id);
         subjectAltNames = chunk_cat("mm", subjectAltNames, name);
     }
     enumerator->destroy(enumerator);
     return asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_build_known_oid(OID_SUBJECT_ALT_NAME),
                         asn1_wrap(ASN1_OCTET_STRING, "m",
                             asn1_wrap(ASN1_SEQUENCE, "m", subjectAltNames)
                         )
                      );
 }
chunk_t x509_parse_authorityKeyIdentifier (chunk_t blob, int level0, chunk_t * authKeySerialNumber)
Extracts an authoritykeyIdentifier
Definition at line 551 of file x509_cert.c.
References asn1_parser_create(), AUTH_KEY_ID_CERT_ISSUER, AUTH_KEY_ID_CERT_SERIAL, AUTH_KEY_ID_KEY_ID, chunk_clone, chunk_empty, asn1_parser_t::destroy, asn1_parser_t::iterate, parser, and asn1_parser_t::set_top_level.
Referenced by parse(), and parse_certificate().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     chunk_t authKeyIdentifier = chunk_empty;
     *authKeySerialNumber = chunk_empty;
     parser = asn1_parser_create(authKeyIdentifierObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case AUTH_KEY_ID_KEY_ID:
                 authKeyIdentifier = chunk_clone(object);
                 break;
             case AUTH_KEY_ID_CERT_ISSUER:
                 /* TODO: x509_parse_generalNames(object, level+1, TRUE); */
                 break;
             case AUTH_KEY_ID_CERT_SERIAL:
                 *authKeySerialNumber = object;
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
     return authKeyIdentifier;
 }
void x509_parse_crlDistributionPoints (chunk_t blob, int level0, linked_list_t * list)
Extracts one or several crlDistributionPoints into a list
Definition at line 839 of file x509_cert.c.
References add_cdps(), asn1_parser_create(), CRL_DIST_POINTS, CRL_DIST_POINTS_FULLNAME, CRL_DIST_POINTS_ISSUER, asn1_parser_t::destroy, linked_list_t::destroy, asn1_parser_t::get_level, asn1_parser_t::iterate, linked_list_create(), parser, asn1_parser_t::set_top_level, TRUE, and x509_parse_generalNames().
Referenced by parse(), and parse_certificate().
 {
     linked_list_t *uris, *issuers;
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     uris = linked_list_create();
     issuers = linked_list_create();
     parser = asn1_parser_create(crlDistributionPointsObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case CRL_DIST_POINTS:
                 add_cdps(list, uris, issuers);
                 break;
             case CRL_DIST_POINTS_FULLNAME:
                 x509_parse_generalNames(object, parser->get_level(parser) + 1,
                                         TRUE, uris);
                 break;
             case CRL_DIST_POINTS_ISSUER:
                 x509_parse_generalNames(object, parser->get_level(parser) + 1,
                                         TRUE, issuers);
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
     add_cdps(list, uris, issuers);
     uris->destroy(uris);
     issuers->destroy(issuers);
 }
void x509_parse_generalNames (chunk_t blob, int level0, bool implicit, linked_list_t * list)
Extracts one or several GNs and puts them into a chained list
Definition at line 505 of file x509_cert.c.
References asn1_parser_create(), asn1_parser_t::destroy, FALSE, GENERAL_NAMES_GN, asn1_parser_t::get_level, linked_list_t::insert_last, asn1_parser_t::iterate, parse_generalName(), parser, asn1_parser_t::set_flags, and asn1_parser_t::set_top_level.
Referenced by parse_certificate(), parse_directoryName(), parse_extension_request(), and x509_parse_crlDistributionPoints().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(generalNamesObjects, blob);
     parser->set_top_level(parser, level0);
     parser->set_flags(parser, implicit, FALSE);
     while (parser->iterate(parser, &objectID, &object))
     {
         if (objectID == GENERAL_NAMES_GN)
         {
             identification_t *gn = parse_generalName(object,
                                             parser->get_level(parser)+1);
             if (gn)
             {
                 list->insert_last(list, (void *)gn);
             }
         }
     }
     parser->destroy(parser);
 }
Variable Documentation
const asn1Object_t authInfoAccessObjects[] static
Initial value:
= {
    { 0, "authorityInfoAccess", ASN1_SEQUENCE,  ASN1_LOOP },
    { 1,   "accessDescription", ASN1_SEQUENCE,  ASN1_NONE },
    { 2,     "accessMethod",    ASN1_OID,       ASN1_BODY },
    { 2,     "accessLocation",  ASN1_EOC,       ASN1_RAW  },
    { 0, "end loop",            ASN1_EOC,       ASN1_END  },
    { 0, "exit",                ASN1_EOC,       ASN1_EXIT }
}
ASN.1 definition of a authorityInfoAccess extension
Definition at line 588 of file x509_cert.c.
const asn1Object_t authKeyIdentifierObjects[] static
Initial value:
= {
    { 0, "authorityKeyIdentifier",      ASN1_SEQUENCE,      ASN1_NONE           },
    { 1,   "keyIdentifier",             ASN1_CONTEXT_S_0,   ASN1_OPT|ASN1_BODY  },
    { 1,   "end opt",                   ASN1_EOC,           ASN1_END            },
    { 1,   "authorityCertIssuer",       ASN1_CONTEXT_C_1,   ASN1_OPT|ASN1_OBJ   },
    { 1,   "end opt",                   ASN1_EOC,           ASN1_END            },
    { 1,   "authorityCertSerialNumber", ASN1_CONTEXT_S_2,   ASN1_OPT|ASN1_BODY  },
    { 1,   "end opt",                   ASN1_EOC,           ASN1_END            },
    { 0, "exit",                        ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of a authorityKeyIdentifier extension
Definition at line 534 of file x509_cert.c.
const asn1Object_t basicConstraintsObjects[] static
Initial value:
= {
    { 0, "basicConstraints",    ASN1_SEQUENCE,  ASN1_NONE           },
    { 1,   "CA",                ASN1_BOOLEAN,   ASN1_DEF|ASN1_BODY  },
    { 1,   "pathLenConstraint", ASN1_INTEGER,   ASN1_OPT|ASN1_BODY  },
    { 1,   "end opt",           ASN1_EOC,       ASN1_END            },
    { 0, "exit",                ASN1_EOC,       ASN1_EXIT           }
}
ASN.1 definition of a basicConstraints extension
Definition at line 270 of file x509_cert.c.
const asn1Object_t certificatePoliciesObject[] static
Initial value:
= {
    { 0, "certificatePolicies",     ASN1_SEQUENCE,  ASN1_LOOP           },
    { 1,   "policyInformation",     ASN1_SEQUENCE,  ASN1_NONE           },
    { 2,     "policyId",            ASN1_OID,       ASN1_BODY           },
    { 2,     "qualifiers",          ASN1_SEQUENCE,  ASN1_OPT|ASN1_LOOP  },
    { 3,       "qualifierInfo",     ASN1_SEQUENCE,  ASN1_NONE           },
    { 4,         "qualifierId",     ASN1_OID,       ASN1_BODY           },
    { 4,         "cPSuri",          ASN1_IA5STRING, ASN1_OPT|ASN1_BODY  },
    { 4,         "end choice",      ASN1_EOC,       ASN1_END            },
    { 4,         "userNotice",      ASN1_SEQUENCE,  ASN1_OPT|ASN1_BODY  },
    { 5,           "explicitText",  ASN1_EOC,       ASN1_RAW            },
    { 4,         "end choice",      ASN1_EOC,       ASN1_END            },
    { 2,      "end opt/loop",       ASN1_EOC,       ASN1_END            },
    { 0, "end loop",                ASN1_EOC,       ASN1_END            },
    { 0, "exit",                    ASN1_EOC,       ASN1_EXIT           }
}
ASN.1 definition of a certificatePolicies extension
Definition at line 938 of file x509_cert.c.
const asn1Object_t certObjects[] static
Initial value:
= {
    { 0, "x509",                    ASN1_SEQUENCE,      ASN1_OBJ            },
    { 1,   "tbsCertificate",        ASN1_SEQUENCE,      ASN1_OBJ            },
    { 2,     "DEFAULT v1",          ASN1_CONTEXT_C_0,   ASN1_DEF            },
    { 3,       "version",           ASN1_INTEGER,       ASN1_BODY           },
    { 2,     "serialNumber",        ASN1_INTEGER,       ASN1_BODY           },
    { 2,     "signature",           ASN1_EOC,           ASN1_RAW            },
    { 2,     "issuer",              ASN1_SEQUENCE,      ASN1_OBJ            },
    { 2,     "validity",            ASN1_SEQUENCE,      ASN1_NONE           },
    { 3,       "notBefore",         ASN1_EOC,           ASN1_RAW            },
    { 3,       "notAfter",          ASN1_EOC,           ASN1_RAW            },
    { 2,     "subject",             ASN1_SEQUENCE,      ASN1_OBJ            },
    { 2,     "subjectPublicKeyInfo",ASN1_SEQUENCE,      ASN1_RAW            },
    { 2,     "issuerUniqueID",      ASN1_CONTEXT_C_1,   ASN1_OPT            },
    { 2,     "end opt",             ASN1_EOC,           ASN1_END            },
    { 2,     "subjectUniqueID",     ASN1_CONTEXT_C_2,   ASN1_OPT            },
    { 2,     "end opt",             ASN1_EOC,           ASN1_END            },
    { 2,     "optional extensions", ASN1_CONTEXT_C_3,   ASN1_OPT            },
    { 3,       "extensions",        ASN1_SEQUENCE,      ASN1_LOOP           },
    { 4,         "extension",       ASN1_SEQUENCE,      ASN1_NONE           },
    { 5,           "extnID",        ASN1_OID,           ASN1_BODY           },
    { 5,           "critical",      ASN1_BOOLEAN,       ASN1_DEF|ASN1_BODY  },
    { 5,           "extnValue",     ASN1_OCTET_STRING,  ASN1_BODY           },
    { 3,       "end loop",          ASN1_EOC,           ASN1_END            },
    { 2,     "end opt",             ASN1_EOC,           ASN1_END            },
    { 1,   "signatureAlgorithm",    ASN1_EOC,           ASN1_RAW            },
    { 1,   "signatureValue",        ASN1_BIT_STRING,    ASN1_BODY           },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of an X.509v3 x509_cert
Definition at line 1252 of file x509_cert.c.
const asn1Object_t crlDistributionPointsObjects[] static
Initial value:
= {
    { 0, "crlDistributionPoints",   ASN1_SEQUENCE,      ASN1_LOOP           },
    { 1,   "DistributionPoint",     ASN1_SEQUENCE,      ASN1_NONE           },
    { 2,     "distributionPoint",   ASN1_CONTEXT_C_0,   ASN1_OPT|ASN1_LOOP  },
    { 3,       "fullName",          ASN1_CONTEXT_C_0,   ASN1_OPT|ASN1_OBJ   },
    { 3,       "end choice",        ASN1_EOC,           ASN1_END            },
    { 3,       "nameRelToCRLIssuer",ASN1_CONTEXT_C_1,   ASN1_OPT|ASN1_BODY  },
    { 3,       "end choice",        ASN1_EOC,           ASN1_END            },
    { 2,     "end opt",             ASN1_EOC,           ASN1_END            },
    { 2,     "reasons",             ASN1_CONTEXT_C_1,   ASN1_OPT|ASN1_BODY  },
    { 2,     "end opt",             ASN1_EOC,           ASN1_END            },
    { 2,     "crlIssuer",           ASN1_CONTEXT_C_2,   ASN1_OPT|ASN1_OBJ   },
    { 2,     "end opt",             ASN1_EOC,           ASN1_END            },
    { 0, "end loop",                ASN1_EOC,           ASN1_END            },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of crlDistributionPoints
Definition at line 771 of file x509_cert.c.
const asn1Object_t extendedKeyUsageObjects[] static
Initial value:
= {
    { 0, "extendedKeyUsage",    ASN1_SEQUENCE,  ASN1_LOOP },
    { 1,   "keyPurposeID",      ASN1_OID,       ASN1_BODY },
    { 0, "end loop",            ASN1_EOC,       ASN1_END  },
    { 0, "exit",                ASN1_EOC,       ASN1_EXIT }
}
ASN.1 definition of a extendedKeyUsage extension
Definition at line 718 of file x509_cert.c.
const asn1Object_t generalNameObjects[] static
Initial value:
= {
    { 0, "otherName",       ASN1_CONTEXT_C_0,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "rfc822Name",      ASN1_CONTEXT_S_1,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "dnsName",         ASN1_CONTEXT_S_2,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "x400Address",     ASN1_CONTEXT_S_3,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "directoryName",   ASN1_CONTEXT_C_4,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "ediPartyName",    ASN1_CONTEXT_C_5,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "URI",             ASN1_CONTEXT_S_6,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "ipAddress",       ASN1_CONTEXT_S_7,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "registeredID",    ASN1_CONTEXT_S_8,  ASN1_OPT|ASN1_BODY   },
    { 0, "end choice",      ASN1_EOC,          ASN1_END             },
    { 0, "exit",            ASN1_EOC,          ASN1_EXIT            }
}
ASN.1 definition of generalName
Definition at line 389 of file x509_cert.c.
const asn1Object_t generalNamesObjects[] static
Initial value:
= {
    { 0, "generalNames",    ASN1_SEQUENCE,  ASN1_LOOP },
    { 1,   "generalName",   ASN1_EOC,       ASN1_RAW  },
    { 0, "end loop",        ASN1_EOC,       ASN1_END  },
    { 0, "exit",            ASN1_EOC,       ASN1_EXIT }
}
ASN.1 definition of generalNames
Definition at line 494 of file x509_cert.c.
const asn1Object_t ipAddrBlocksObjects[] static
Initial value:
= {
    { 0, "ipAddrBlocks",            ASN1_SEQUENCE,      ASN1_LOOP           },
    { 1,   "ipAddressFamily",       ASN1_SEQUENCE,      ASN1_NONE           },
    { 2,     "addressFamily",       ASN1_OCTET_STRING,  ASN1_BODY           },
    { 2,     "inherit",             ASN1_NULL,          ASN1_OPT|ASN1_NONE  },
    { 2,     "end choice",          ASN1_EOC,           ASN1_END            },
    { 2,     "addressesOrRanges",   ASN1_SEQUENCE,      ASN1_OPT|ASN1_LOOP  },
    { 3,       "addressPrefix",     ASN1_BIT_STRING,    ASN1_OPT|ASN1_BODY  },
    { 3,       "end choice",        ASN1_EOC,           ASN1_END            },
    { 3,       "addressRange",      ASN1_SEQUENCE,      ASN1_OPT|ASN1_NONE  },
    { 4,         "min",             ASN1_BIT_STRING,    ASN1_BODY           },
    { 4,         "max",             ASN1_BIT_STRING,    ASN1_BODY           },
    { 3,       "end choice",        ASN1_EOC,           ASN1_END            },
    { 2,     "end opt/loop",        ASN1_EOC,           ASN1_END            },
    { 0, "end loop",                ASN1_EOC,           ASN1_END            },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of ipAddrBlocks according to RFC 3779
Definition at line 1109 of file x509_cert.c.
const asn1Object_t nameConstraintsObjects[] static
Initial value:
= {
    { 0, "nameConstraints",         ASN1_SEQUENCE,      ASN1_LOOP           },
    { 1,   "permittedSubtrees",     ASN1_CONTEXT_C_0,   ASN1_OPT|ASN1_LOOP  },
    { 2,     "generalSubtree",      ASN1_SEQUENCE,      ASN1_BODY           },
    { 1,   "end loop",              ASN1_EOC,           ASN1_END            },
    { 1,   "excludedSubtrees",      ASN1_CONTEXT_C_1,   ASN1_OPT|ASN1_LOOP  },
    { 2,     "generalSubtree",      ASN1_SEQUENCE,      ASN1_BODY           },
    { 1,   "end loop",              ASN1_EOC,           ASN1_END            },
    { 0, "end loop",                ASN1_EOC,           ASN1_END            },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of nameConstraints
Definition at line 882 of file x509_cert.c.
const asn1Object_t otherNameObjects[] static
Initial value:
= {
    {0, "type-id",  ASN1_OID,           ASN1_BODY   },
    {0, "value",    ASN1_CONTEXT_C_0,   ASN1_BODY   },
    {0, "exit",     ASN1_EOC,           ASN1_EXIT   }
}
ASN.1 definition of otherName
Definition at line 322 of file x509_cert.c.
const asn1Object_t policyConstraintsObjects[] static
Initial value:
= {
    { 0, "policyConstraints",       ASN1_SEQUENCE,      ASN1_NONE           },
    { 1,   "requireExplicitPolicy", ASN1_CONTEXT_C_0,   ASN1_OPT|ASN1_NONE  },
    { 2,     "SkipCerts",           ASN1_INTEGER,       ASN1_BODY           },
    { 1,   "end opt",               ASN1_EOC,           ASN1_END            },
    { 1,   "inhibitPolicyMapping",  ASN1_CONTEXT_C_1,   ASN1_OPT|ASN1_NONE  },
    { 2,     "SkipCerts",           ASN1_INTEGER,       ASN1_BODY           },
    { 1,   "end opt",               ASN1_EOC,           ASN1_END            },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT           }
}
ASN.1 definition of a policyConstraints extension
Definition at line 1063 of file x509_cert.c.
const asn1Object_t policyMappingsObjects[] static
Initial value:
= {
    { 0, "policyMappings",          ASN1_SEQUENCE,  ASN1_LOOP           },
    { 1,   "policyMapping",         ASN1_SEQUENCE,  ASN1_NONE           },
    { 2,     "issuerPolicy",        ASN1_OID,       ASN1_BODY           },
    { 2,     "subjectPolicy",       ASN1_OID,       ASN1_BODY           },
    { 0, "end loop",                ASN1_EOC,       ASN1_END            },
    { 0, "exit",                    ASN1_EOC,       ASN1_EXIT           }
}
ASN.1 definition of a policyMappings extension
Definition at line 1007 of file x509_cert.c.