strongSwan: notify_payload
notify_payload
payloads
Classes
struct notify_payload_t
Typedefs
typedef enum notify_type_t notify_type_t
typedef struct notify_payload_t notify_payload_t
Enumerations
enum notify_type_t {
UNSUPPORTED_CRITICAL_PAYLOAD = 1, INVALID_PAYLOAD_TYPE = 1, INVALID_IKE_SPI = 4, INVALID_MAJOR_VERSION = 5,
INVALID_SYNTAX = 7, INVALID_EXCHANGE_TYPE = 7, INVALID_MESSAGE_ID = 9, INVALID_SPI = 11,
ATTRIBUTES_NOT_SUPPORTED = 13, NO_PROPOSAL_CHOSEN = 14, PAYLOAD_MALFORMED = 16, INVALID_KE_PAYLOAD = 17,
INVALID_KEY_INFORMATION = 17, INVALID_ID_INFORMATION = 18, INVALID_CERT_ENCODING = 19, INVALID_CERTIFICATE = 20,
CERT_TYPE_UNSUPPORTED = 21, INVALID_CERT_AUTHORITY = 22, INVALID_HASH_INFORMATION = 23, AUTHENTICATION_FAILED = 24,
SINGLE_PAIR_REQUIRED = 34, NO_ADDITIONAL_SAS = 35, INTERNAL_ADDRESS_FAILURE = 36, FAILED_CP_REQUIRED = 37,
TS_UNACCEPTABLE = 38, INVALID_SELECTORS = 39, UNACCEPTABLE_ADDRESSES = 40, UNEXPECTED_NAT_DETECTED = 41,
USE_ASSIGNED_HoA = 42, TEMPORARY_FAILURE = 43, CHILD_SA_NOT_FOUND = 44, ME_CONNECT_FAILED = 8192,
MS_NOTIFY_STATUS = 12345, INITIAL_CONTACT = 16384, SET_WINDOW_SIZE = 16385, ADDITIONAL_TS_POSSIBLE = 16386,
IPCOMP_SUPPORTED = 16387, NAT_DETECTION_SOURCE_IP = 16388, NAT_DETECTION_DESTINATION_IP = 16389, COOKIE = 16390,
USE_TRANSPORT_MODE = 16391, HTTP_CERT_LOOKUP_SUPPORTED = 16392, REKEY_SA = 16393, ESP_TFC_PADDING_NOT_SUPPORTED = 16394,
NON_FIRST_FRAGMENTS_ALSO = 16395, MOBIKE_SUPPORTED = 16396, ADDITIONAL_IP4_ADDRESS = 16397, ADDITIONAL_IP6_ADDRESS = 16398,
NO_ADDITIONAL_ADDRESSES = 16399, UPDATE_SA_ADDRESSES = 16400, COOKIE2 = 16401, NO_NATS_ALLOWED = 16402,
AUTH_LIFETIME = 16403, MULTIPLE_AUTH_SUPPORTED = 16404, ANOTHER_AUTH_FOLLOWS = 16405, REDIRECT_SUPPORTED = 16406,
REDIRECT = 16407, REDIRECTED_FROM = 16408, TICKET_LT_OPAQUE = 16409, TICKET_REQUEST = 16410,
TICKET_ACK = 16411, TICKET_NACK = 16412, TICKET_OPAQUE = 16413, LINK_ID = 16414,
USE_WESP_MODE = 16415, ROHC_SUPPORTED = 16416, EAP_ONLY_AUTHENTICATION = 16417, CHILDLESS_IKEV2_SUPPORTED = 16418,
QUICK_CRASH_DETECTION = 16419, IKEV2_MESSAGE_ID_SYNC_SUPPORTED = 16420, IKEV2_REPLAY_COUNTER_SYNC_SUPPORTED = 16421, IKEV2_MESSAGE_ID_SYNC = 16422,
IPSEC_REPLAY_COUNTER_SYNC = 16423, SECURE_PASSWORD_METHOD = 16424, PSK_PERSIST = 16425, PSK_CONFIRM = 16426,
ERX_SUPPORTED = 16427, IFOM_CAPABILITY = 16428, SENDER_REQUEST_ID = 16429, FRAGMENTATION_SUPPORTED = 16430,
SIGNATURE_HASH_ALGORITHMS = 16431, INITIAL_CONTACT_IKEV1 = 24578, DPD_R_U_THERE = 36136, DPD_R_U_THERE_ACK = 36137,
UNITY_LOAD_BALANCE = 40501, USE_BEET_MODE = 40961, ME_MEDIATION = 40962, ME_ENDPOINT = 40963,
ME_CALLBACK = 40964, ME_CONNECTID = 40965, ME_CONNECTKEY = 40966, ME_CONNECTAUTH = 40967,
ME_RESPONSE = 40968, RADIUS_ATTRIBUTE = 40969
}
Functions
notify_payload_t * notify_payload_create (payload_type_t type)
notify_payload_t * notify_payload_create_from_protocol_and_type (payload_type_t type, protocol_id_t protocol, notify_type_t notify)
Variables
enum_name_t * notify_type_names
enum_name_t * notify_type_short_names
Detailed Description
Typedef Documentation
typedef struct notify_payload_t notify_payload_t
Definition at line 28 of file notify_payload.h.
typedef enum notify_type_t notify_type_t
Definition at line 27 of file notify_payload.h.
Enumeration Type Documentation
enum notify_type_t
Notify message types for IKEv2, and a subset for IKEv1.
Enumerator
UNSUPPORTED_CRITICAL_PAYLOAD
INVALID_PAYLOAD_TYPE
INVALID_IKE_SPI
INVALID_MAJOR_VERSION
INVALID_SYNTAX
INVALID_EXCHANGE_TYPE
INVALID_MESSAGE_ID
INVALID_SPI
ATTRIBUTES_NOT_SUPPORTED
NO_PROPOSAL_CHOSEN
PAYLOAD_MALFORMED
INVALID_KE_PAYLOAD
INVALID_KEY_INFORMATION
INVALID_ID_INFORMATION
INVALID_CERT_ENCODING
INVALID_CERTIFICATE
CERT_TYPE_UNSUPPORTED
INVALID_CERT_AUTHORITY
INVALID_HASH_INFORMATION
AUTHENTICATION_FAILED
SINGLE_PAIR_REQUIRED
NO_ADDITIONAL_SAS
INTERNAL_ADDRESS_FAILURE
FAILED_CP_REQUIRED
TS_UNACCEPTABLE
INVALID_SELECTORS
UNACCEPTABLE_ADDRESSES
UNEXPECTED_NAT_DETECTED
USE_ASSIGNED_HoA
TEMPORARY_FAILURE
CHILD_SA_NOT_FOUND
ME_CONNECT_FAILED
MS_NOTIFY_STATUS
INITIAL_CONTACT
SET_WINDOW_SIZE
ADDITIONAL_TS_POSSIBLE
IPCOMP_SUPPORTED
NAT_DETECTION_SOURCE_IP
NAT_DETECTION_DESTINATION_IP
COOKIE
USE_TRANSPORT_MODE
HTTP_CERT_LOOKUP_SUPPORTED
REKEY_SA
ESP_TFC_PADDING_NOT_SUPPORTED
NON_FIRST_FRAGMENTS_ALSO
MOBIKE_SUPPORTED
ADDITIONAL_IP4_ADDRESS
ADDITIONAL_IP6_ADDRESS
NO_ADDITIONAL_ADDRESSES
UPDATE_SA_ADDRESSES
COOKIE2
NO_NATS_ALLOWED
AUTH_LIFETIME
MULTIPLE_AUTH_SUPPORTED
ANOTHER_AUTH_FOLLOWS
REDIRECT_SUPPORTED
REDIRECT
REDIRECTED_FROM
TICKET_LT_OPAQUE
TICKET_REQUEST
TICKET_ACK
TICKET_NACK
TICKET_OPAQUE
LINK_ID
USE_WESP_MODE
ROHC_SUPPORTED
EAP_ONLY_AUTHENTICATION
CHILDLESS_IKEV2_SUPPORTED
QUICK_CRASH_DETECTION
IKEV2_MESSAGE_ID_SYNC_SUPPORTED
IKEV2_REPLAY_COUNTER_SYNC_SUPPORTED
IKEV2_MESSAGE_ID_SYNC
IPSEC_REPLAY_COUNTER_SYNC
SECURE_PASSWORD_METHOD
PSK_PERSIST
PSK_CONFIRM
ERX_SUPPORTED
IFOM_CAPABILITY
SENDER_REQUEST_ID
FRAGMENTATION_SUPPORTED
SIGNATURE_HASH_ALGORITHMS
INITIAL_CONTACT_IKEV1
DPD_R_U_THERE
DPD_R_U_THERE_ACK
UNITY_LOAD_BALANCE
USE_BEET_MODE
ME_MEDIATION
ME_ENDPOINT
ME_CALLBACK
ME_CONNECTID
ME_CONNECTKEY
ME_CONNECTAUTH
ME_RESPONSE
RADIUS_ATTRIBUTE
Definition at line 38 of file notify_payload.h.
                    {
     /* notify error messages */
     UNSUPPORTED_CRITICAL_PAYLOAD = 1,
     /* IKEv1 alias */
     INVALID_PAYLOAD_TYPE = 1,
     INVALID_IKE_SPI = 4,
     INVALID_MAJOR_VERSION = 5,
     INVALID_SYNTAX = 7,
     /* IKEv1 alias */
     INVALID_EXCHANGE_TYPE = 7,
     INVALID_MESSAGE_ID = 9,
     INVALID_SPI = 11,
     /* IKEv1 only */
     ATTRIBUTES_NOT_SUPPORTED = 13,
     /* IKEv1 alias */
     NO_PROPOSAL_CHOSEN = 14,
     /* IKEv1 only */
     PAYLOAD_MALFORMED = 16,
     INVALID_KE_PAYLOAD = 17,
     /* IKEv1 alias */
     INVALID_KEY_INFORMATION = 17,
     /* IKEv1 only */
     INVALID_ID_INFORMATION = 18,
     INVALID_CERT_ENCODING = 19,
     INVALID_CERTIFICATE = 20,
     CERT_TYPE_UNSUPPORTED = 21,
     INVALID_CERT_AUTHORITY = 22,
     INVALID_HASH_INFORMATION = 23,
     AUTHENTICATION_FAILED = 24,
     SINGLE_PAIR_REQUIRED = 34,
     NO_ADDITIONAL_SAS = 35,
     INTERNAL_ADDRESS_FAILURE = 36,
     FAILED_CP_REQUIRED = 37,
     TS_UNACCEPTABLE = 38,
     INVALID_SELECTORS = 39,
     /* mobile extension, RFC 4555 */
     UNACCEPTABLE_ADDRESSES = 40,
     UNEXPECTED_NAT_DETECTED = 41,
     /* mobile IPv6 bootstrapping, RFC 5026 */
     USE_ASSIGNED_HoA = 42,
     /* IKEv2 RFC 5996 */
     TEMPORARY_FAILURE = 43,
     CHILD_SA_NOT_FOUND = 44,
     /* IKE-ME, private use */
     ME_CONNECT_FAILED = 8192,
     /* Windows error code */
     MS_NOTIFY_STATUS = 12345,
     /* notify status messages */
     INITIAL_CONTACT = 16384,
     SET_WINDOW_SIZE = 16385,
     ADDITIONAL_TS_POSSIBLE = 16386,
     IPCOMP_SUPPORTED = 16387,
     NAT_DETECTION_SOURCE_IP = 16388,
     NAT_DETECTION_DESTINATION_IP = 16389,
     COOKIE = 16390,
     USE_TRANSPORT_MODE = 16391,
     HTTP_CERT_LOOKUP_SUPPORTED = 16392,
     REKEY_SA = 16393,
     ESP_TFC_PADDING_NOT_SUPPORTED = 16394,
     NON_FIRST_FRAGMENTS_ALSO = 16395,
     /* mobike extension, RFC4555 */
     MOBIKE_SUPPORTED = 16396,
     ADDITIONAL_IP4_ADDRESS = 16397,
     ADDITIONAL_IP6_ADDRESS = 16398,
     NO_ADDITIONAL_ADDRESSES = 16399,
     UPDATE_SA_ADDRESSES = 16400,
     COOKIE2 = 16401,
     NO_NATS_ALLOWED = 16402,
     /* repeated authentication extension, RFC4478 */
     AUTH_LIFETIME = 16403,
     /* multiple authentication exchanges, RFC 4739 */
     MULTIPLE_AUTH_SUPPORTED = 16404,
     ANOTHER_AUTH_FOLLOWS = 16405,
     /* redirect mechanism, RFC 5685 */
     REDIRECT_SUPPORTED = 16406,
     REDIRECT = 16407,
     REDIRECTED_FROM = 16408,
     /* session resumption, RFC 5723 */
     TICKET_LT_OPAQUE = 16409,
     TICKET_REQUEST = 16410,
     TICKET_ACK = 16411,
     TICKET_NACK = 16412,
     TICKET_OPAQUE = 16413,
     /* IPv6 configuration, RFC 5739 */
     LINK_ID = 16414,
     /* wrapped esp, RFC 5840 */
     USE_WESP_MODE = 16415,
     /* robust header compression, RFC 5857 */
     ROHC_SUPPORTED = 16416,
     /* EAP-only authentication, RFC 5998 */
     EAP_ONLY_AUTHENTICATION = 16417,
     /* Childless initiation of IKEv2 SA, RFC 6023 */
     CHILDLESS_IKEV2_SUPPORTED = 16418,
     /* Quick crash detection for IKE, RFC 6290 */
     QUICK_CRASH_DETECTION = 16419,
     /* High availability of IKEv2/IPsec, RFC 6311 */
     IKEV2_MESSAGE_ID_SYNC_SUPPORTED = 16420,
     IKEV2_REPLAY_COUNTER_SYNC_SUPPORTED = 16421,
     IKEV2_MESSAGE_ID_SYNC = 16422,
     IPSEC_REPLAY_COUNTER_SYNC = 16423,
     /* Secure password methods, RFC 6467 */
     SECURE_PASSWORD_METHOD = 16424,
     /* PACE, RFC 6631 */
     PSK_PERSIST = 16425,
     PSK_CONFIRM = 16426,
     /* EAP Re-authentication Extension, RFC 6867 */
     ERX_SUPPORTED = 16427,
     /* IFOM capability, 3GPP TS 24.303, annex B.2 */
     IFOM_CAPABILITY = 16428,
     /* SENDER_REQUEST_ID (draft-yeung-g-ikev2) */
     SENDER_REQUEST_ID = 16429,
     /* IKEv2 fragmentation supported, RFC 7383 */
     FRAGMENTATION_SUPPORTED = 16430,
     /* Signature Hash Algorithms, RFC 7427 */
     SIGNATURE_HASH_ALGORITHMS = 16431,
     /* IKEv1 initial contact */
     INITIAL_CONTACT_IKEV1 = 24578,
     /* IKEv1 DPD */
     DPD_R_U_THERE = 36136,
     DPD_R_U_THERE_ACK = 36137,
     /* IKEv1 Cisco High Availability */
     UNITY_LOAD_BALANCE = 40501,
     /* BEET mode, not even a draft yet. private use */
     USE_BEET_MODE = 40961,
     /* IKE-ME, private use */
     ME_MEDIATION = 40962,
     ME_ENDPOINT = 40963,
     ME_CALLBACK = 40964,
     ME_CONNECTID = 40965,
     ME_CONNECTKEY = 40966,
     ME_CONNECTAUTH = 40967,
     ME_RESPONSE = 40968,
     /* RADIUS attribute received/to send to a AAA backend */
     RADIUS_ATTRIBUTE = 40969,
 };
Function Documentation
notify_payload_t* notify_payload_create (payload_type_t type)
Creates an empty notify_payload_t object
Parameters
type payload type, PLV2_NOTIFY or PLV1_NOTIFY
Returns
created notify_payload_t object
Definition at line 714 of file notify_payload.c.
References compute_length(), IKEV1_DOI_IPSEC, INIT, PL_NONE, and type.
Referenced by build_natd_payload(), METHOD(), notify_payload_create_from_protocol_and_type(), and payload_create().
 {
     private_notify_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_protocol_id = _get_protocol_id,
             .set_protocol_id  = _set_protocol_id,
             .get_notify_type = _get_notify_type,
             .set_notify_type = _set_notify_type,
             .get_spi = _get_spi,
             .set_spi = _set_spi,
             .get_spi_data = _get_spi_data,
             .set_spi_data = _set_spi_data,
             .get_notification_data = _get_notification_data,
             .set_notification_data = _set_notification_data,
             .destroy = _destroy,
         },
         .doi = IKEV1_DOI_IPSEC,
         .next_payload = PL_NONE,
         .type = type,
     );
     compute_length(this);
     return &this->public;
 }
notify_payload_t* notify_payload_create_from_protocol_and_type (payload_type_t type, protocol_id_t protocol, notify_type_t notify)
Creates an notify_payload_t object of specific type for specific protocol id.
Parameters
type payload type, PLV2_NOTIFY or PLV1_NOTIFY
protocol protocol id (IKE, AH or ESP)
notify type of notify
Returns
notify_payload_t object
Definition at line 753 of file notify_payload.c.
References notify_payload_create().
Referenced by add_initial_contact(), METHOD(), and send_notify().
 {
     notify_payload_t *this = notify_payload_create(type);
     this->set_notify_type(this, notify);
     this->set_protocol_id(this, protocol);
     return this;
 }
Variable Documentation
enum_name_t* notify_type_names
enum name for notify_type_t.
Referenced by handle_notify(), has_notify_errors(), METHOD(), and process_auth_response().
enum_name_t* notify_type_short_names
enum name for notify_type_t (shorter strings).
Referenced by get_string().