strongSwan: ipsec_event_relay
ipsec_event_relay
libipsec
Classes
struct ipsec_event_relay_t
Typedefs
typedef struct ipsec_event_relay_t ipsec_event_relay_t
Functions
ipsec_event_relay_t * ipsec_event_relay_create ()
Detailed Description
Typedef Documentation
typedef struct ipsec_event_relay_t ipsec_event_relay_t
Definition at line 29 of file ipsec_event_relay.h.
Function Documentation
ipsec_event_relay_t* ipsec_event_relay_create ()
Create an ipsec_event_relay_t instance
Returns
IPsec event relay instance
Described in header.
Definition at line 185 of file ipsec_event_relay.c.
References blocking_queue_create(), callback_job_create(), handle_events(), INIT, lib, linked_list_create(), library_t::processor, processor_t::queue_job, return_false(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by libipsec_init().
 {
     private_ipsec_event_relay_t *this;
     INIT(this,
         .public = {
             .expire = _expire,
             .register_listener = _register_listener,
             .unregister_listener = _unregister_listener,
             .destroy = _destroy,
         },
         .listeners = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .queue = blocking_queue_create(),
     );
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create((callback_job_cb_t)handle_events, this,
             NULL, (callback_job_cancel_t)return_false));
     return &this->public;
 }