strongSwan: gcrypt_rsa_public_key.c File Reference
gcrypt_rsa_public_key.c File Reference
#include <gcrypt.h>
#include "gcrypt_rsa_public_key.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <crypto/hashers/hasher.h>
Classes
struct private_gcrypt_rsa_public_key_t
Typedefs
typedef struct
private_gcrypt_rsa_public_key_t private_gcrypt_rsa_public_key_t
Functions
chunk_t gcrypt_rsa_find_token (gcry_sexp_t sexp, char *name, gcry_sexp_t key)
static bool verify_raw (private_gcrypt_rsa_public_key_t *this, chunk_t data, chunk_t signature)
static bool verify_pkcs1 (private_gcrypt_rsa_public_key_t *this, hash_algorithm_t algorithm, char *hash_name, chunk_t data, chunk_t signature)
METHOD (public_key_t, get_type, key_type_t, private_gcrypt_rsa_public_key_t *this)
METHOD (public_key_t, verify, bool, private_gcrypt_rsa_public_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
METHOD (public_key_t, encrypt_, bool, private_gcrypt_rsa_public_key_t *this, encryption_scheme_t scheme, chunk_t plain, chunk_t *encrypted)
METHOD (public_key_t, get_keysize, int, private_gcrypt_rsa_public_key_t *this)
METHOD (public_key_t, get_encoding, bool, private_gcrypt_rsa_public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (public_key_t, get_fingerprint, bool, private_gcrypt_rsa_public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (public_key_t, get_ref, public_key_t *, private_gcrypt_rsa_public_key_t *this)
METHOD (public_key_t, destroy, void, private_gcrypt_rsa_public_key_t *this)
gcrypt_rsa_public_key_t * gcrypt_rsa_public_key_load (key_type_t type, va_list args)
Typedef Documentation
typedef struct private_gcrypt_rsa_public_key_t private_gcrypt_rsa_public_key_t
Definition at line 26 of file gcrypt_rsa_public_key.c.
Function Documentation
chunk_t gcrypt_rsa_find_token (gcry_sexp_t sexp, char * name, gcry_sexp_t key)
Implemented in gcrypt_rsa_private_key.c
find a token in a S-expression. If a key is given, its length is used to pad the output to a given length.
Definition at line 52 of file gcrypt_rsa_private_key.c.
References chunk_alloc, chunk_clone, chunk_empty, chunk_skip(), data, chunk_t::len, len, memcpy, memset, and chunk_t::ptr.
Referenced by METHOD(), sign_pkcs1(), and sign_raw().
 {
     gcry_sexp_t token;
     chunk_t data = chunk_empty, tmp;
     size_t len = 0;
     token = gcry_sexp_find_token(sexp, name, 1);
     if (token)
     {
         data.ptr = (char*)gcry_sexp_nth_data(token, 1, &data.len);
         if (!data.ptr)
         {
             data.len = 0;
         }
         else
         {
             if (key)
             {
                 /* gcrypt might return more bytes than necessary. Truncate
                  * to key length if key given, or prepend zeros if needed  */
                 len = gcry_pk_get_nbits(key);
                 len = len / 8 + (len % 8 ? 1 : 0);
                 if (len > data.len)
                 {
                     tmp = chunk_alloc(len);
                     len -= data.len;
                     memset(tmp.ptr, 0, tmp.len - len);
                     memcpy(tmp.ptr + len, data.ptr, data.len);
                     data = tmp;
                 }
                 else if (len < data.len)
                 {
                     data = chunk_clone(chunk_skip(data, data.len - len));
                 }
                 else
                 {
                     data = chunk_clone(data);
                 }
             }
             else
             {
                 data = chunk_clone(data);
             }
         }
         gcry_sexp_release(token);
     }
     return data;
 }
METHOD (public_key_t , get_type , key_type_t , private_gcrypt_rsa_public_key_t * this)
Definition at line 162 of file gcrypt_rsa_public_key.c.
References KEY_RSA.
 {
     return KEY_RSA;
 }
METHOD (public_key_t , verify , bool , private_gcrypt_rsa_public_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
Definition at line 168 of file gcrypt_rsa_public_key.c.
References DBG1, DBG_LIB, FALSE, HASH_MD5, HASH_SHA1, HASH_SHA224, HASH_SHA256, HASH_SHA384, HASH_SHA512, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA224, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, signature_scheme_names, verify_pkcs1(), and verify_raw().
 {
     switch (scheme)
     {
         case SIGN_RSA_EMSA_PKCS1_NULL:
             return verify_raw(this, data, signature);
         case SIGN_RSA_EMSA_PKCS1_MD5:
             return verify_pkcs1(this, HASH_MD5, "md5", data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA1:
             return verify_pkcs1(this, HASH_SHA1, "sha1", data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA224:
             return verify_pkcs1(this, HASH_SHA224, "sha224", data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA256:
             return verify_pkcs1(this, HASH_SHA256, "sha256", data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA384:
             return verify_pkcs1(this, HASH_SHA384, "sha384", data, signature);
         case SIGN_RSA_EMSA_PKCS1_SHA512:
             return verify_pkcs1(this, HASH_SHA512, "sha512", data, signature);
         default:
             DBG1(DBG_LIB, "signature scheme %N not supported in RSA",
                  signature_scheme_names, scheme);
             return FALSE;
     }
 }
METHOD (public_key_t , encrypt_ , bool , private_gcrypt_rsa_public_key_t * this, encryption_scheme_t scheme, chunk_t plain, chunk_t * encrypted)
Definition at line 195 of file gcrypt_rsa_public_key.c.
References DBG1, DBG_LIB, ENCRYPT_RSA_PKCS1, encryption_scheme_names, FALSE, gcrypt_rsa_find_token(), in, key, chunk_t::len, out, and chunk_t::ptr.
 {
     gcry_sexp_t in, out;
     gcry_error_t err;
     if (scheme != ENCRYPT_RSA_PKCS1)
     {
         DBG1(DBG_LIB, "encryption scheme %N not supported",
              encryption_scheme_names, scheme);
         return FALSE;
     }
     /* "pkcs1" uses PKCS 1.5 (section 8.1) block type 2 encryption:
      * 00 | 02 | RANDOM | 00 | DATA */
     err = gcry_sexp_build(&in, NULL, "(data(flags pkcs1)(value %b))",
                           plain.len, plain.ptr);
     if (err)
     {
         DBG1(DBG_LIB, "building encryption S-expression failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     err = gcry_pk_encrypt(&out, in, this->key);
     gcry_sexp_release(in);
     if (err)
     {
         DBG1(DBG_LIB, "encrypting data using pkcs1 failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     *encrypted = gcrypt_rsa_find_token(out, "a", this->key);
     gcry_sexp_release(out);
     return !!encrypted->len;
 }
METHOD (public_key_t , get_keysize , int , private_gcrypt_rsa_public_key_t * this)
Definition at line 231 of file gcrypt_rsa_public_key.c.
References key.
 {
     return gcry_pk_get_nbits(this->key);
 }
METHOD (public_key_t , get_encoding , bool , private_gcrypt_rsa_public_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 237 of file gcrypt_rsa_public_key.c.
References chunk_free(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, cred_encoding_t::encode, library_t::encoding, gcrypt_rsa_find_token(), key, lib, and n.
 {
     chunk_t n, e;
     bool success;
     n = gcrypt_rsa_find_token(this->key, "n", NULL);
     e = gcrypt_rsa_find_token(this->key, "e", NULL);
     success = lib->encoding->encode(lib->encoding, type, NULL, encoding,
                             CRED_PART_RSA_MODULUS, n, CRED_PART_RSA_PUB_EXP, e,
                             CRED_PART_END);
     chunk_free(&n);
     chunk_free(&e);
     return success;
 }
METHOD (public_key_t , get_fingerprint , bool , private_gcrypt_rsa_public_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 255 of file gcrypt_rsa_public_key.c.
References chunk_free(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, cred_encoding_t::encode, library_t::encoding, gcrypt_rsa_find_token(), cred_encoding_t::get_cache, key, lib, n, and TRUE.
 {
     chunk_t n, e;
     bool success;
     if (lib->encoding->get_cache(lib->encoding, type, this, fp))
     {
         return TRUE;
     }
     n = gcrypt_rsa_find_token(this->key, "n", NULL);
     e = gcrypt_rsa_find_token(this->key, "e", NULL);
     success = lib->encoding->encode(lib->encoding,
                                 type, this, fp, CRED_PART_RSA_MODULUS, n,
                                 CRED_PART_RSA_PUB_EXP, e, CRED_PART_END);
     chunk_free(&n);
     chunk_free(&e);
     return success;
 }
METHOD (public_key_t , get_ref , public_key_t * , private_gcrypt_rsa_public_key_t * this)
Definition at line 277 of file gcrypt_rsa_public_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (public_key_t , destroy , void , private_gcrypt_rsa_public_key_t * this)
Definition at line 284 of file gcrypt_rsa_public_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), key, lib, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         gcry_sexp_release(this->key);
         lib->encoding->clear_cache(lib->encoding, this);
         free(this);
     }
 }
static bool verify_pkcs1 (private_gcrypt_rsa_public_key_t * this, hash_algorithm_t algorithm, char * hash_name, chunk_t data, chunk_t signature) static
Verification of an EMSA PKCS1 signature described in PKCS#1
Definition at line 114 of file gcrypt_rsa_public_key.c.
References hasher_t::allocate_hash, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, hash, hasher, in, key, chunk_t::len, lib, chunk_t::ptr, sig, and TRUE.
Referenced by METHOD().
 {
     hasher_t *hasher;
     chunk_t hash;
     gcry_error_t err;
     gcry_sexp_t in, sig;
     hasher = lib->crypto->create_hasher(lib->crypto, algorithm);
     if (!hasher || !hasher->allocate_hash(hasher, data, &hash))
     {
         DESTROY_IF(hasher);
         return FALSE;
     }
     hasher->destroy(hasher);
     err = gcry_sexp_build(&in, NULL, "(data(flags pkcs1)(hash %s %b))",
                           hash_name, hash.len, hash.ptr);
     chunk_free(&hash);
     if (err)
     {
         DBG1(DBG_LIB, "building data S-expression failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     err = gcry_sexp_build(&sig, NULL, "(sig-val(rsa(s %b)))",
                           signature.len, signature.ptr);
     if (err)
     {
         DBG1(DBG_LIB, "building signature S-expression failed: %s",
              gpg_strerror(err));
         gcry_sexp_release(in);
         return FALSE;
     }
     err = gcry_pk_verify(sig, in, this->key);
     gcry_sexp_release(in);
     gcry_sexp_release(sig);
     if (err)
     {
         DBG1(DBG_LIB, "RSA signature verification failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     return TRUE;
 }
static bool verify_raw (private_gcrypt_rsa_public_key_t * this, chunk_t data, chunk_t signature) static
verification of a padded PKCS1 signature without an OID
Definition at line 57 of file gcrypt_rsa_public_key.c.
References chunk_alloc, chunk_free(), DBG1, DBG_LIB, FALSE, in, key, chunk_t::len, memcpy, memset, chunk_t::ptr, sig, and TRUE.
Referenced by METHOD().
 {
     gcry_sexp_t in, sig;
     gcry_error_t err;
     chunk_t em;
     size_t k;
     /* EM = 0x00 || 0x01 || PS || 0x00 || T
      * PS = 0xFF padding, with length to fill em
      * T  = data
      */
     k = gcry_pk_get_nbits(this->key) / 8;
     if (data.len > k - 3)
     {
         return FALSE;
     }
     em = chunk_alloc(k);
     memset(em.ptr, 0xFF, em.len);
     em.ptr[0] = 0x00;
     em.ptr[1] = 0x01;
     em.ptr[em.len - data.len - 1] = 0x00;
     memcpy(em.ptr + em.len - data.len, data.ptr, data.len);
     err = gcry_sexp_build(&in, NULL, "(data(flags raw)(value %b))",
                           em.len, em.ptr);
     chunk_free(&em);
     if (err)
     {
         DBG1(DBG_LIB, "building data S-expression failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     err = gcry_sexp_build(&sig, NULL, "(sig-val(rsa(s %b)))",
                           signature.len, signature.ptr);
     if (err)
     {
         DBG1(DBG_LIB, "building signature S-expression failed: %s",
              gpg_strerror(err));
         gcry_sexp_release(in);
         return FALSE;
     }
     err = gcry_pk_verify(sig, in, this->key);
     gcry_sexp_release(in);
     gcry_sexp_release(sig);
     if (err)
     {
         DBG1(DBG_LIB, "RSA signature verification failed: %s",
              gpg_strerror(err));
         return FALSE;
     }
     return TRUE;
 }