strongSwan: bus.c File Reference
bus.c File Reference
#include "bus.h"
#include <stdint.h>
#include <threading/thread.h>
#include <threading/thread_value.h>
#include <threading/mutex.h>
#include <threading/rwlock.h>
Classes
struct private_bus_t
struct entry_t
struct log_entry_t
struct log_data_t
Macros
#define skip_level(ptr, level) FALSE
#define set_level(ptr, val) ({ *ptr = val; })
Typedefs
typedef struct private_bus_t private_bus_t
typedef struct entry_t entry_t
typedef struct log_entry_t log_entry_t
Functions
METHOD (bus_t, add_listener, void, private_bus_t *this, listener_t *listener)
METHOD (bus_t, remove_listener, void, private_bus_t *this, listener_t *listener)
static void register_logger (private_bus_t *this, debug_t group, log_entry_t *entry)
static void unregister_logger (private_bus_t *this, logger_t *logger)
METHOD (bus_t, add_logger, void, private_bus_t *this, logger_t *logger)
METHOD (bus_t, remove_logger, void, private_bus_t *this, logger_t *logger)
METHOD (bus_t, set_sa, void, private_bus_t *this, ike_sa_t *ike_sa)
METHOD (bus_t, get_sa, ike_sa_t *, private_bus_t *this)
static void log_cb (log_entry_t *entry, log_data_t *data)
static void vlog_cb (log_entry_t *entry, log_data_t *data)
METHOD (bus_t, vlog, void, private_bus_t *this, debug_t group, level_t level, char *format, va_list args)
METHOD (bus_t, log_, void, private_bus_t *this, debug_t group, level_t level, char *format,...)
static void unregister_listener (private_bus_t *this, entry_t *entry, enumerator_t *enumerator)
METHOD (bus_t, alert, void, private_bus_t *this, alert_t alert,...)
METHOD (bus_t, ike_state_change, void, private_bus_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
METHOD (bus_t, child_state_change, void, private_bus_t *this, child_sa_t *child_sa, child_sa_state_t state)
METHOD (bus_t, message, void, private_bus_t *this, message_t *message, bool incoming, bool plain)
METHOD (bus_t, ike_keys, void, private_bus_t *this, ike_sa_t *ike_sa, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_t *rekey, shared_key_t *shared)
METHOD (bus_t, child_keys, void, private_bus_t *this, child_sa_t *child_sa, bool initiator, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r)
METHOD (bus_t, child_updown, void, private_bus_t *this, child_sa_t *child_sa, bool up)
METHOD (bus_t, child_rekey, void, private_bus_t *this, child_sa_t *old, child_sa_t *new)
METHOD (bus_t, children_migrate, void, private_bus_t *this, ike_sa_id_t *new, u_int32_t unique)
METHOD (bus_t, ike_updown, void, private_bus_t *this, ike_sa_t *ike_sa, bool up)
METHOD (bus_t, ike_rekey, void, private_bus_t *this, ike_sa_t *old, ike_sa_t *new)
METHOD (bus_t, ike_update, void, private_bus_t *this, ike_sa_t *ike_sa, bool local, host_t *new)
METHOD (bus_t, ike_reestablish_pre, void, private_bus_t *this, ike_sa_t *old, ike_sa_t *new)
METHOD (bus_t, ike_reestablish_post, void, private_bus_t *this, ike_sa_t *old, ike_sa_t *new, bool initiated)
METHOD (bus_t, authorize, bool, private_bus_t *this, bool final)
METHOD (bus_t, narrow, void, private_bus_t *this, child_sa_t *child_sa, narrow_hook_t type, linked_list_t *local, linked_list_t *remote)
METHOD (bus_t, assign_vips, void, private_bus_t *this, ike_sa_t *ike_sa, bool assign)
METHOD (bus_t, handle_vips, void, private_bus_t *this, ike_sa_t *ike_sa, bool handle)
static void hook_creds (private_bus_t *this, credential_hook_type_t type, certificate_t *cert)
METHOD (bus_t, destroy, void, private_bus_t *this)
bus_t * bus_create ()
Macro Definition Documentation
#define set_level (ptr, val) ({ *ptr = val; })
Definition at line 47 of file bus.c.
Referenced by file_logger_create(), register_logger(), sys_logger_create(), and unregister_logger().
#define skip_level (ptr, level) FALSE
These operations allow us to speed up the log level checks on some platforms. In particular if acquiring the read lock is expensive even in the absence of any writers.
Note that while holding the read/write lock the read does not have to be atomic as the write lock must be held to set the level.
Definition at line 46 of file bus.c.
Referenced by METHOD().
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 101 of file bus.c.
typedef struct log_entry_t log_entry_t
Definition at line 120 of file bus.c.
typedef struct private_bus_t private_bus_t
Definition at line 51 of file bus.c.
Function Documentation
static void hook_creds (private_bus_t * this, credential_hook_type_t type, certificate_t * cert) static
Credential manager hook function to forward bus alerts
Definition at line 1000 of file bus.c.
References ALERT_CERT_EXCEEDED_PATH_LEN, ALERT_CERT_EXPIRED, ALERT_CERT_NO_ISSUER, ALERT_CERT_POLICY_VIOLATION, ALERT_CERT_REVOKED, ALERT_CERT_UNTRUSTED_ROOT, ALERT_CERT_VALIDATION_FAILED, CRED_HOOK_EXCEEDED_PATH_LEN, CRED_HOOK_EXPIRED, CRED_HOOK_NO_ISSUER, CRED_HOOK_POLICY_VIOLATION, CRED_HOOK_REVOKED, CRED_HOOK_UNTRUSTED_ROOT, and CRED_HOOK_VALIDATION_FAILED.
Referenced by bus_create().
 {
     switch (type)
     {
         case CRED_HOOK_EXPIRED:
             return alert(this, ALERT_CERT_EXPIRED, cert);
         case CRED_HOOK_REVOKED:
             return alert(this, ALERT_CERT_REVOKED, cert);
         case CRED_HOOK_VALIDATION_FAILED:
             return alert(this, ALERT_CERT_VALIDATION_FAILED, cert);
         case CRED_HOOK_NO_ISSUER:
             return alert(this, ALERT_CERT_NO_ISSUER, cert);
         case CRED_HOOK_UNTRUSTED_ROOT:
             return alert(this, ALERT_CERT_UNTRUSTED_ROOT, cert);
         case CRED_HOOK_EXCEEDED_PATH_LEN:
             return alert(this, ALERT_CERT_EXCEEDED_PATH_LEN, cert);
         case CRED_HOOK_POLICY_VIOLATION:
             return alert(this, ALERT_CERT_POLICY_VIOLATION, cert);
     }
 }
static void log_cb (log_entry_t * entry, log_data_t * data) static
logger->log() invocation as a invoke_function callback
Definition at line 328 of file bus.c.
References log_data_t::group, log_data_t::ike_sa, log_data_t::level, log_entry_t::levels, logger_t::log, log_entry_t::logger, log_data_t::message, and log_data_t::thread.
Referenced by initiate(), logcmd(), METHOD(), and terminate().
 {
     if (entry->logger->log && entry->levels[data->group] >= data->level)
     {
         entry->logger->log(entry->logger, data->group, data->level,
                            data->thread, data->ike_sa, data->message);
     }
 }
METHOD (bus_t , add_listener , void , private_bus_t * this, listener_t * listener)
Definition at line 139 of file bus.c.
References INIT, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     entry_t *entry;
     INIT(entry,
         .listener = listener,
     );
     this->mutex->lock(this->mutex);
     this->listeners->insert_last(this->listeners, entry);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , remove_listener , void , private_bus_t * this, listener_t * listener)
Definition at line 153 of file bus.c.
References enumerator_t::destroy, enumerator_t::enumerate, free(), entry_t::listener, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->listener == listener)
         {
             this->listeners->remove_at(this->listeners, enumerator);
             free(entry);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , add_logger , void , private_bus_t * this, logger_t * logger)
Definition at line 263 of file bus.c.
References DBG_MAX, logger_t::get_level, group, INIT, LEVEL_SILENT, log_entry_t::levels, register_logger(), and unregister_logger().
 {
     log_entry_t *entry;
     debug_t group;
     INIT(entry,
         .logger = logger,
     );
     this->log_lock->write_lock(this->log_lock);
     unregister_logger(this, logger);
     for (group = 0; group < DBG_MAX; group++)
     {
         entry->levels[group] = logger->get_level(logger, group);
         if (entry->levels[group] > LEVEL_SILENT)
         {
             register_logger(this, group, entry);
         }
     }
     this->loggers[DBG_MAX]->insert_last(this->loggers[DBG_MAX], entry);
     this->log_lock->unlock(this->log_lock);
 }
METHOD (bus_t , remove_logger , void , private_bus_t * this, logger_t * logger)
Definition at line 287 of file bus.c.
References unregister_logger().
 {
     this->log_lock->write_lock(this->log_lock);
     unregister_logger(this, logger);
     this->log_lock->unlock(this->log_lock);
 }
METHOD (bus_t , set_sa , void , private_bus_t * this, ike_sa_t * ike_sa)
Definition at line 295 of file bus.c.
 {
     this->thread_sa->set(this->thread_sa, ike_sa);
 }
METHOD (bus_t , get_sa , ike_sa_t * , private_bus_t * this)
Definition at line 301 of file bus.c.
 {
     return this->thread_sa->get(this->thread_sa);
 }
METHOD (bus_t , vlog , void , private_bus_t * this, debug_t group, level_t level, char * format, va_list args)
Definition at line 353 of file bus.c.
References log_data_t::args, data, free(), group, log_data_t::group, log_data_t::ike_sa, linked_list_t::invoke_function, len, log_data_t::level, log_cb(), malloc(), log_data_t::message, skip_level, log_data_t::thread, thread_current_id(), vlog_cb(), and vsnprintf.
 {
     linked_list_t *loggers;
     log_data_t data;
     /* NOTE: This is not 100% thread-safe and done here only because it is
      * performance critical.  We therefore ignore the following two issues for
      * this particular case:  1) We might miss some log messages if another
      * thread concurrently increases the log level or registers a new logger.
      * 2) We might have to acquire the read lock below even if it wouldn't be
      * necessary anymore due to another thread concurrently unregistering a
      * logger or reducing the level. */
     if (skip_level(&this->max_level[group], level) &&
         skip_level(&this->max_vlevel[group], level))
     {
         return;
     }
     this->log_lock->read_lock(this->log_lock);
     loggers = this->loggers[group];
     if (this->max_level[group] >= level)
     {
         char buf[1024];
         ssize_t len;
         data.ike_sa = this->thread_sa->get(this->thread_sa);
         data.thread = thread_current_id();
         data.group = group;
         data.level = level;
         data.message = buf;
         va_copy(data.args, args);
         len = vsnprintf(data.message, sizeof(buf), format, data.args);
         va_end(data.args);
         if (len >= sizeof(buf))
         {
             len++;
             data.message = malloc(len);
             va_copy(data.args, args);
             len = vsnprintf(data.message, len, format, data.args);
             va_end(data.args);
         }
         if (len > 0)
         {
             loggers->invoke_function(loggers, (linked_list_invoke_t)log_cb,
                                      &data);
         }
         if (data.message != buf)
         {
             free(data.message);
         }
     }
     if (this->max_vlevel[group] >= level)
     {
         data.ike_sa = this->thread_sa->get(this->thread_sa);
         data.thread = thread_current_id();
         data.group = group;
         data.level = level;
         data.message = format;
         va_copy(data.args, args);
         loggers->invoke_function(loggers, (linked_list_invoke_t)vlog_cb, &data);
         va_end(data.args);
     }
     this->log_lock->unlock(this->log_lock);
 }
METHOD (bus_t , log_ , void , private_bus_t * this, debug_t group, level_t level, char * format, ...)
Definition at line 424 of file bus.c.
 {
     va_list args;
     va_start(args, format);
     vlog(this, group, level, format, args);
     va_end(args);
 }
METHOD (bus_t , alert , void , private_bus_t * this, alert_t alert, ...)
Definition at line 444 of file bus.c.
References listener_t::alert, entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     va_list args;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->alert)
         {
             continue;
         }
         entry->calling++;
         va_start(args, alert);
         keep = entry->listener->alert(entry->listener, ike_sa, alert, args);
         va_end(args);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , ike_state_change , void , private_bus_t * this, ike_sa_t * ike_sa, ike_sa_state_t state)
Definition at line 477 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, listener_t::ike_state_change, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->ike_state_change)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->ike_state_change(entry->listener, ike_sa, state);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , child_state_change , void , private_bus_t * this, child_sa_t * child_sa, child_sa_state_t state)
Definition at line 504 of file bus.c.
References entry_t::calling, listener_t::child_state_change, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->child_state_change)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->child_state_change(entry->listener, ike_sa,
                                                    child_sa, state);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , message , void , private_bus_t * this, message_t * message, bool incoming, bool plain)
Definition at line 535 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, listener_t::message, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->message)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->message(entry->listener, ike_sa,
                                         message, incoming, plain);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , ike_keys , void , private_bus_t * this, ike_sa_t * ike_sa, diffie_hellman_t * dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_t * rekey, shared_key_t * shared)
Definition at line 566 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, listener_t::ike_keys, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->ike_keys)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->ike_keys(entry->listener, ike_sa, dh, dh_other,
                                          nonce_i, nonce_r, rekey, shared);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , child_keys , void , private_bus_t * this, child_sa_t * child_sa, bool initiator, diffie_hellman_t * dh, chunk_t nonce_i, chunk_t nonce_r)
Definition at line 596 of file bus.c.
References entry_t::calling, listener_t::child_keys, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->child_keys)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->child_keys(entry->listener, ike_sa,
                                 child_sa, initiator, dh, nonce_i, nonce_r);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , child_updown , void , private_bus_t * this, child_sa_t * child_sa, bool up)
Definition at line 628 of file bus.c.
References entry_t::calling, listener_t::child_updown, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->child_updown)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->child_updown(entry->listener,
                                              ike_sa, child_sa, up);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , child_rekey , void , private_bus_t * this, child_sa_t * old, child_sa_t * new)
Definition at line 659 of file bus.c.
References entry_t::calling, listener_t::child_rekey, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->child_rekey)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->child_rekey(entry->listener, ike_sa,
                                             old, new);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , children_migrate , void , private_bus_t * this, ike_sa_id_t * new, u_int32_t unique)
Definition at line 690 of file bus.c.
References entry_t::calling, listener_t::children_migrate, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->children_migrate)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->children_migrate(entry->listener, ike_sa, new,
                                                  unique);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , ike_updown , void , private_bus_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 721 of file bus.c.
References entry_t::calling, child_updown(), ike_sa_t::create_child_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, listener_t::ike_updown, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->ike_updown)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->ike_updown(entry->listener, ike_sa, up);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     /* a down event for IKE_SA implicitly downs all CHILD_SAs */
     if (!up)
     {
         enumerator_t *enumerator;
         child_sa_t *child_sa;
         enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
         while (enumerator->enumerate(enumerator, (void**)&child_sa))
         {
             child_updown(this, child_sa, FALSE);
         }
         enumerator->destroy(enumerator);
     }
 }
METHOD (bus_t , ike_rekey , void , private_bus_t * this, ike_sa_t * old, ike_sa_t * new)
Definition at line 762 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, listener_t::ike_rekey, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->ike_rekey)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->ike_rekey(entry->listener, old, new);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , ike_update , void , private_bus_t * this, ike_sa_t * ike_sa, bool local, host_t * new)
Definition at line 789 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, listener_t::ike_update, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->ike_update)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->ike_update(entry->listener, ike_sa, local, new);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , ike_reestablish_pre , void , private_bus_t * this, ike_sa_t * old, ike_sa_t * new)
Definition at line 816 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, listener_t::ike_reestablish_pre, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->ike_reestablish_pre)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->ike_reestablish_pre(entry->listener, old, new);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , ike_reestablish_post , void , private_bus_t * this, ike_sa_t * old, ike_sa_t * new, bool initiated)
Definition at line 843 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, listener_t::ike_reestablish_post, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->ike_reestablish_post)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->ike_reestablish_post(entry->listener, old, new,
                                                      initiated);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , authorize , bool , private_bus_t * this, bool final)
Definition at line 871 of file bus.c.
References ALERT_AUTHORIZATION_FAILED, listener_t::authorize, entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, TRUE, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep, success = TRUE;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->authorize)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->authorize(entry->listener, ike_sa,
                                           final, &success);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
         if (!success)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     if (!success)
     {
         alert(this, ALERT_AUTHORIZATION_FAILED);
     }
     return success;
 }
METHOD (bus_t , narrow , void , private_bus_t * this, child_sa_t * child_sa, narrow_hook_t type, linked_list_t * local, linked_list_t * remote)
Definition at line 911 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, listener_t::narrow, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     entry_t *entry;
     bool keep;
     ike_sa = this->thread_sa->get(this->thread_sa);
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->narrow)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->narrow(entry->listener, ike_sa, child_sa,
                                        type, local, remote);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , assign_vips , void , private_bus_t * this, ike_sa_t * ike_sa, bool assign)
Definition at line 943 of file bus.c.
References listener_t::assign_vips, entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->assign_vips)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->assign_vips(entry->listener, ike_sa, assign);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , handle_vips , void , private_bus_t * this, ike_sa_t * ike_sa, bool handle)
Definition at line 970 of file bus.c.
References entry_t::calling, enumerator_t::destroy, enumerator_t::enumerate, listener_t::handle_vips, entry_t::listener, mutex_t::lock, mutex, mutex_t::unlock, and unregister_listener().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     bool keep;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->calling || !entry->listener->handle_vips)
         {
             continue;
         }
         entry->calling++;
         keep = entry->listener->handle_vips(entry->listener, ike_sa, handle);
         entry->calling--;
         if (!keep)
         {
             unregister_listener(this, entry, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (bus_t , destroy , void , private_bus_t * this)
Definition at line 1022 of file bus.c.
References library_t::credmgr, DBG_MAX, mutex_t::destroy, free(), group, lib, mutex, and credential_manager_t::set_hook.
 {
     debug_t group;
     lib->credmgr->set_hook(lib->credmgr, NULL, NULL);
     for (group = 0; group < DBG_MAX; group++)
     {
         this->loggers[group]->destroy(this->loggers[group]);
     }
     this->loggers[DBG_MAX]->destroy_function(this->loggers[DBG_MAX],
                                              (void*)free);
     this->listeners->destroy_function(this->listeners, (void*)free);
     this->thread_sa->destroy(this->thread_sa);
     this->log_lock->destroy(this->log_lock);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void register_logger (private_bus_t * this, debug_t group, log_entry_t * entry) inline static
Register a logger on the given log group according to the requested level
Definition at line 177 of file bus.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, group, linked_list_t::insert_before, log_entry_t::levels, logger_t::log, log_entry_t::logger, max, set_level, and logger_t::vlog.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     linked_list_t *loggers;
     log_entry_t *current;
     level_t level;
     loggers = this->loggers[group];
     level = entry->levels[group];
     enumerator = loggers->create_enumerator(loggers);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current->levels[group] <= level)
         {
             break;
         }
     }
     loggers->insert_before(loggers, enumerator, entry);
     enumerator->destroy(enumerator);
     if (entry->logger->log)
     {
         set_level(&this->max_level[group], max(this->max_level[group], level));
     }
     if (entry->logger->vlog)
     {
         set_level(&this->max_vlevel[group],
                   max(this->max_vlevel[group], level));
     }
 }
static void unregister_listener (private_bus_t * this, entry_t * entry, enumerator_t * enumerator) inline static
unregister a listener
Definition at line 437 of file bus.c.
References free().
Referenced by METHOD().
 {
     this->listeners->remove_at(this->listeners, enumerator);
     free(entry);
 }
static void unregister_logger (private_bus_t * this, logger_t * logger) inline static
Unregister a logger from all log groups (destroys the log_entry_t)
Definition at line 213 of file bus.c.
References linked_list_t::create_enumerator, DBG_MAX, enumerator_t::destroy, enumerator_t::enumerate, found, free(), linked_list_t::get_first, group, LEVEL_SILENT, log_entry_t::levels, logger_t::log, log_entry_t::logger, linked_list_t::remove, linked_list_t::remove_at, set_level, SUCCESS, and logger_t::vlog.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     linked_list_t *loggers;
     log_entry_t *entry, *found = NULL;
     loggers = this->loggers[DBG_MAX];
     enumerator = loggers->create_enumerator(loggers);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->logger == logger)
         {
             loggers->remove_at(loggers, enumerator);
             found = entry;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (found)
     {
         level_t level = LEVEL_SILENT, vlevel = LEVEL_SILENT;
         debug_t group;
         for (group = 0; group < DBG_MAX; group++)
         {
             if (found->levels[group] > LEVEL_SILENT)
             {
                 loggers = this->loggers[group];
                 loggers->remove(loggers, found, NULL);
                 if (loggers->get_first(loggers, (void**)&entry) == SUCCESS)
                 {
                     if (entry->logger->log)
                     {
                         level = entry->levels[group];
                     }
                     if (entry->logger->vlog)
                     {
                         vlevel = entry->levels[group];
                     }
                 }
                 set_level(&this->max_level[group], level);
                 set_level(&this->max_vlevel[group], vlevel);
             }
         }
         free(found);
     }
 }
static void vlog_cb (log_entry_t * entry, log_data_t * data) static
logger->vlog() invocation as a invoke_function callback
Definition at line 340 of file bus.c.
References log_data_t::args, copy(), log_data_t::group, log_data_t::ike_sa, log_data_t::level, log_entry_t::levels, log_entry_t::logger, log_data_t::message, log_data_t::thread, and logger_t::vlog.
Referenced by METHOD().
 {
     if (entry->logger->vlog && entry->levels[data->group] >= data->level)
     {
         va_list copy;
         va_copy(copy, data->args);
         entry->logger->vlog(entry->logger, data->group, data->level,
                             data->thread, data->ike_sa, data->message, copy);
         va_end(copy);
     }
 }