strongSwan: vici_dispatcher_t Struct Reference
vici_dispatcher_t Struct Reference
vici_dispatcher
#include "vici_dispatcher.h"
Public Attributes
void(* manage_command)(vici_dispatcher_t *this, char *name, vici_command_cb_t cb, void *user)
void(* manage_event)(vici_dispatcher_t *this, char *name, bool reg)
bool(* has_event_listeners)(vici_dispatcher_t *this, char *name)
void(* raise_event)(vici_dispatcher_t *this, char *name, u_int id, vici_message_t *message)
void(* destroy)(vici_dispatcher_t *this)
Detailed Description
Vici command dispatcher.
Definition at line 97 of file vici_dispatcher.h.
Member Data Documentation
void(* vici_dispatcher_t::destroy)(vici_dispatcher_t *this)
Destroy a vici_dispatcher_t.
Definition at line 144 of file vici_dispatcher.h.
Referenced by START_TEST().
bool(* vici_dispatcher_t::has_event_listeners)(vici_dispatcher_t *this, char *name)
Check if an event has listeners.
This can be used to check if a vici message needs to be generated or not, as in some cases the generation can be a heavy operation.
Parameters
name event name to check
Returns
TRUE if event has listeners
Definition at line 129 of file vici_dispatcher.h.
void(* vici_dispatcher_t::manage_command)(vici_dispatcher_t *this, char *name, vici_command_cb_t cb, void *user)
Register/Unregister a callback invoked for a specific command request.
Parameters
name name of the command
cb callback function to register, NULL to unregister
user user data to pass to callback
Definition at line 106 of file vici_dispatcher.h.
Referenced by START_TEST().
void(* vici_dispatcher_t::manage_event)(vici_dispatcher_t *this, char *name, bool reg)
Register/Unregister an event type to send.
The dispatcher internally manages event subscriptions. Clients registered for an event will receive such messages when the event is raised.
Parameters
name event name to manager
reg TRUE to register, FALSE to unregister
Definition at line 118 of file vici_dispatcher.h.
Referenced by START_TEST().
void(* vici_dispatcher_t::raise_event)(vici_dispatcher_t *this, char *name, u_int id, vici_message_t *message)
Raise an event to a specific or all clients registered to that event.
Parameters
name event name to raise
id client connection ID, 0 for all
message event message to send, gets destroyed
Definition at line 138 of file vici_dispatcher.h.
Referenced by CALLBACK(), log_vici(), and START_TEST().
The documentation for this struct was generated from the following file:
vici_dispatcher.h