strongSwan: pgp_builder.c File Reference
pgp_builder.c File Reference
#include "pgp_builder.h"
#include "pgp_utils.h"
#include <utils/utils.h>
#include <utils/debug.h>
#include <credentials/keys/private_key.h>
Functions
static public_key_t * parse_public_key (chunk_t blob)
static public_key_t * parse_rsa_public_key (chunk_t blob)
static private_key_t * parse_rsa_private_key (chunk_t blob)
static bool sign_not_allowed (private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
static bool decrypt_not_allowed (private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
static private_key_t * parse_private_key (chunk_t blob)
public_key_t * pgp_public_key_load (key_type_t type, va_list args)
private_key_t * pgp_private_key_load (key_type_t type, va_list args)
Function Documentation
static bool decrypt_not_allowed (private_key_t * this, encryption_scheme_t scheme, chunk_t crypto, chunk_t * plain) static
Implementation of private_key_t.decrypt for signature-only keys
Definition at line 132 of file pgp_builder.c.
References DBG1, DBG_LIB, and FALSE.
Referenced by parse_private_key().
 {
     DBG1(DBG_LIB, "decryption failed - signature only key");
     return FALSE;
 }
static private_key_t* parse_private_key (chunk_t blob) static
Load a generic private key from a PGP packet
Definition at line 142 of file pgp_builder.c.
References alg, BUILD_BLOB_PGP, BUILD_END, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, days, DBG1, DBG_LIB, private_key_t::decrypt, decrypt_not_allowed(), key, KEY_ECDSA, KEY_RSA, lib, PGP_PUBKEY_ALG_DIFFIE_HELLMAN, PGP_PUBKEY_ALG_DSA, PGP_PUBKEY_ALG_ECC, PGP_PUBKEY_ALG_ECDSA, PGP_PUBKEY_ALG_ELGAMAL, PGP_PUBKEY_ALG_ELGAMAL_ENC_ONLY, PGP_PUBKEY_ALG_RSA, PGP_PUBKEY_ALG_RSA_ENC_ONLY, PGP_PUBKEY_ALG_RSA_SIGN_ONLY, pgp_read_packet(), pgp_read_scalar(), private_key_t::sign, sign_not_allowed(), and version.
Referenced by pgp_private_key_load().
 {
     chunk_t packet;
     pgp_packet_tag_t tag;
     u_int32_t version, created, days, alg;
     private_key_t *key;
     if (!pgp_read_packet(&blob, &packet, &tag))
     {
         return NULL;
     }
     if (!pgp_read_scalar(&packet, 1, &version))
     {
         return NULL;
     }
     switch (version)
     {
         case 3:
             if (!pgp_read_scalar(&packet, 2, &days))
             {
                 return NULL;
             }
             break;
         case 4:
             break;
         default:
             DBG1(DBG_LIB, "PGP packet version V%d not supported", version);
             return NULL;
     }
     if (!pgp_read_scalar(&packet, 4, &created))
     {
         return NULL;
     }
     if (!pgp_read_scalar(&packet, 1, &alg))
     {
         return NULL;
     }
     switch (alg)
     {
         case PGP_PUBKEY_ALG_RSA:
             return lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                       BUILD_BLOB_PGP, packet, BUILD_END);
         case PGP_PUBKEY_ALG_RSA_ENC_ONLY:
             key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                       BUILD_BLOB_PGP, packet, BUILD_END);
             if (key)
             {
                 key->sign = sign_not_allowed;
             }
             return key;
         case PGP_PUBKEY_ALG_RSA_SIGN_ONLY:
             key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                       BUILD_BLOB_PGP, packet, BUILD_END);
             if (key)
             {
                 key->decrypt = decrypt_not_allowed;
             }
             return key;
         case PGP_PUBKEY_ALG_ECDSA:
             return lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_ECDSA,
                                       BUILD_BLOB_PGP, packet, BUILD_END);
         case PGP_PUBKEY_ALG_ELGAMAL_ENC_ONLY:
         case PGP_PUBKEY_ALG_DSA:
         case PGP_PUBKEY_ALG_ECC:
         case PGP_PUBKEY_ALG_ELGAMAL:
         case PGP_PUBKEY_ALG_DIFFIE_HELLMAN:
         default:
             return NULL;
     }
 }
static public_key_t* parse_public_key (chunk_t blob) static
Load a generic public key from a PGP packet
Definition at line 27 of file pgp_builder.c.
References alg, BUILD_BLOB_PGP, BUILD_END, credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, DBG1, DBG_LIB, key, KEY_RSA, lib, pgp_pubkey_alg_names, PGP_PUBKEY_ALG_RSA, PGP_PUBKEY_ALG_RSA_SIGN_ONLY, and pgp_read_scalar().
Referenced by pgp_public_key_load().
 {
     u_int32_t alg;
     public_key_t *key;
     if (!pgp_read_scalar(&blob, 1, &alg))
     {
         return NULL;
     }
     switch (alg)
     {
         case PGP_PUBKEY_ALG_RSA:
         case PGP_PUBKEY_ALG_RSA_SIGN_ONLY:
             key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                                      BUILD_BLOB_PGP, blob, BUILD_END);
             break;
         default:
             DBG1(DBG_LIB, "PGP public key algorithm %N not supported",
                  pgp_pubkey_alg_names, alg);
             return NULL;
     }
     return key;
 }
static private_key_t* parse_rsa_private_key (chunk_t blob) static
Load a RSA private key from a PGP packet
Definition at line 74 of file pgp_builder.c.
References BUILD_END, BUILD_RSA_COEFF, BUILD_RSA_MODULUS, BUILD_RSA_PRIME1, BUILD_RSA_PRIME2, BUILD_RSA_PRIV_EXP, BUILD_RSA_PUB_EXP, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, DBG1, DBG_LIB, KEY_RSA, lib, pgp_read_mpi(), pgp_read_scalar(), pgp_sym_alg_names, and PGP_SYM_ALG_PLAIN.
Referenced by pgp_private_key_load().
 {
     chunk_t mpi[6];
     u_int32_t s2k;
     int i;
     for (i = 0; i < 2; i++)
     {
         if (!pgp_read_mpi(&blob, &mpi[i]))
         {
             return NULL;
         }
     }
     if (!pgp_read_scalar(&blob, 1, &s2k))
     {
         return NULL;
     }
     if (s2k == 255 || s2k == 254)
     {
         DBG1(DBG_LIB, "string-to-key specifiers not supported");
         return NULL;
     }
     if (s2k != PGP_SYM_ALG_PLAIN)
     {
         DBG1(DBG_LIB, "%N private key encryption not supported",
              pgp_sym_alg_names, s2k);
         return NULL;
     }
     for (i = 2; i < 6; i++)
     {
         if (!pgp_read_mpi(&blob, &mpi[i]))
         {
             return NULL;
         }
     }
     /* PGP has uses p < q, but we use p > q */
     return lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                         BUILD_RSA_MODULUS, mpi[0], BUILD_RSA_PUB_EXP, mpi[1],
                         BUILD_RSA_PRIV_EXP, mpi[2], BUILD_RSA_PRIME2, mpi[3],
                         BUILD_RSA_PRIME1, mpi[4], BUILD_RSA_COEFF, mpi[5],
                         BUILD_END);
 }
static public_key_t* parse_rsa_public_key (chunk_t blob) static
Load a RSA public key from a PGP packet
Definition at line 54 of file pgp_builder.c.
References BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, KEY_RSA, lib, and pgp_read_mpi().
Referenced by pgp_public_key_load().
 {
     chunk_t mpi[2];
     int i;
     for (i = 0; i < 2; i++)
     {
         if (!pgp_read_mpi(&blob, &mpi[i]))
         {
             return NULL;
         }
     }
     return lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                         BUILD_RSA_MODULUS, mpi[0], BUILD_RSA_PUB_EXP, mpi[1],
                         BUILD_END);
 }
static bool sign_not_allowed (private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * signature) static
Implementation of private_key_t.sign for encryption-only keys
Definition at line 122 of file pgp_builder.c.
References DBG1, DBG_LIB, and FALSE.
Referenced by parse_private_key().
 {
     DBG1(DBG_LIB, "signing failed - decryption only key");
     return FALSE;
 }