strongSwan: imv_agent_t Struct Reference
imv_agent_t Struct Reference
imv_agent
#include "imv_agent.h"
Public Attributes
TNC_Result(* request_handshake_retry)(TNC_IMVID imv_id, TNC_ConnectionID connection_id, TNC_RetryReason reason)
TNC_Result(* send_message)(TNC_IMVID imv_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
TNC_Result(* send_message_long)(TNC_IMVID imv_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 dst_imc_id)
TNC_Result(* bind_functions)(imv_agent_t *this, TNC_TNCS_BindFunctionPointer bind_function)
TNC_Result(* create_state)(imv_agent_t *this, imv_state_t *state)
TNC_Result(* delete_state)(imv_agent_t *this, TNC_ConnectionID connection_id)
TNC_Result(* change_state)(imv_agent_t *this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imv_state_t **state_p)
bool(* get_state)(imv_agent_t *this, TNC_ConnectionID connection_id, imv_state_t **state)
const char *(* get_name)(imv_agent_t *this)
TNC_IMVID(* get_id)(imv_agent_t *this)
TNC_Result(* reserve_additional_ids)(imv_agent_t *this, int count)
int(* count_additional_ids)(imv_agent_t *this)
enumerator_t *(* create_id_enumerator)(imv_agent_t *this)
enumerator_t *(* create_language_enumerator)(imv_agent_t *this, imv_state_t *state)
TNC_Result(* provide_recommendation)(imv_agent_t *this, imv_state_t *state)
void(* add_non_fatal_attr_type)(imv_agent_t *this, pen_type_t type)
linked_list_t *(* get_non_fatal_attr_types)(imv_agent_t *this)
void(* destroy)(imv_agent_t *this)
Detailed Description
Core functions of an Integrity Measurement Verifier (IMV)
Definition at line 40 of file imv_agent.h.
Member Data Documentation
void(* imv_agent_t::add_non_fatal_attr_type)(imv_agent_t *this, pen_type_t type)
Add an item to the list of non-fatal unsupported PA-TNC attribute types
Definition at line 194 of file imv_agent.h.
Referenced by imv_swid_agent_create().
TNC_Result(* imv_agent_t::bind_functions)(imv_agent_t *this, TNC_TNCS_BindFunctionPointer bind_function)
Bind TNCS functions
Parameters
bind_function function offered by the TNCS
Returns
TNC result code
Definition at line 98 of file imv_agent.h.
TNC_Result(* imv_agent_t::change_state)(imv_agent_t *this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imv_state_t **state_p)
Change the current state of a TNCCS connection
Parameters
connection_id network connection ID assigned by TNCS
new_state new state of TNCCS connection
state_p internal IMV state instance [optional argument]
Returns
TNC result code
Definition at line 126 of file imv_agent.h.
int(* imv_agent_t::count_additional_ids)(imv_agent_t *this)
Return the number of additional IMV IDs assigned by the TNCS
Returns
number of additional IMV IDs
Definition at line 168 of file imv_agent.h.
enumerator_t*(* imv_agent_t::create_id_enumerator)(imv_agent_t *this)
Create an enumerator for the additional IMV IDs
Definition at line 173 of file imv_agent.h.
enumerator_t*(* imv_agent_t::create_language_enumerator)(imv_agent_t *this, imv_state_t *state)
Create a preferred languages enumerator
Parameters
state of TNCCS connection
Definition at line 180 of file imv_agent.h.
TNC_Result(* imv_agent_t::create_state)(imv_agent_t *this, imv_state_t *state)
Create the IMV state for a TNCCS connection instance
Parameters
state internal IMV state instance
Returns
TNC result code
Definition at line 107 of file imv_agent.h.
TNC_Result(* imv_agent_t::delete_state)(imv_agent_t *this, TNC_ConnectionID connection_id)
Delete the IMV state for a TNCCS connection instance
Parameters
connection_id network connection ID assigned by TNCS
Returns
TNC result code
Definition at line 115 of file imv_agent.h.
void(* imv_agent_t::destroy)(imv_agent_t *this)
Destroys an imv_agent_t object
Definition at line 204 of file imv_agent.h.
TNC_IMVID(* imv_agent_t::get_id)(imv_agent_t *this)
Get base IMV ID
return base IMV ID
Definition at line 153 of file imv_agent.h.
Referenced by imv_msg_create_as_reply(), and imv_msg_create_from_data().
const char*(* imv_agent_t::get_name)(imv_agent_t *this)
Get IMV name
return IMV name
Definition at line 146 of file imv_agent.h.
linked_list_t*(* imv_agent_t::get_non_fatal_attr_types)(imv_agent_t *this)
Get a list of non-fatal unsupported PA-TNC attribute types
Definition at line 199 of file imv_agent.h.
bool(* imv_agent_t::get_state)(imv_agent_t *this, TNC_ConnectionID connection_id, imv_state_t **state)
Get the IMV state for a TNCCS connection instance
Parameters
connection_id network connection ID assigned by TNCS
state internal IMV state instance
Returns
TRUE if the state was found
Definition at line 138 of file imv_agent.h.
TNC_Result(* imv_agent_t::provide_recommendation)(imv_agent_t *this, imv_state_t *state)
Deliver IMV Action Recommendation and IMV Evaluation Result to the TNCS
Parameters
state state bound to a connection ID
Returns
TNC result code
Definition at line 189 of file imv_agent.h.
TNC_Result(* imv_agent_t::request_handshake_retry)(TNC_IMVID imv_id, TNC_ConnectionID connection_id, TNC_RetryReason reason)
Ask a TNCS to retry an Integrity Check Handshake
Parameters
imv_id IMV ID assigned by TNCS
connection_id network connection ID assigned by TNCS
reason IMV retry reason
Returns
TNC result code
Definition at line 50 of file imv_agent.h.
TNC_Result(* imv_agent_t::reserve_additional_ids)(imv_agent_t *this, int count)
Reserve additional IMV IDs from TNCS
Parameters
count number of additional IMV IDs to be assigned
Returns
TNC result code
Definition at line 161 of file imv_agent.h.
TNC_Result(* imv_agent_t::send_message)(TNC_IMVID imv_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
Call when an IMV-IMC message is to be sent
Parameters
imv_id IMV ID assigned by TNCS
connection_id network connection ID assigned by TNCS
msg message to send
msg_len message length in bytes
msg_type message type
Returns
TNC result code
Definition at line 64 of file imv_agent.h.
TNC_Result(* imv_agent_t::send_message_long)(TNC_IMVID imv_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 dst_imc_id)
Call when an IMV-IMC message is to be sent with long message types
Parameters
imv_id IMV ID assigned by TNCS
connection_id network connection ID assigned by TNCS
msg_flags message flags
msg message to send
msg_len message length in bytes
msg_vid message vendor ID
msg_subtype message subtype
dst_imc_id destination IMC ID
Returns
TNC result code
Definition at line 83 of file imv_agent.h.
The documentation for this struct was generated from the following file:
imv_agent.h