strongSwan: pb_assessment_result_msg.c File Reference
pb_assessment_result_msg.c File Reference
#include "pb_assessment_result_msg.h"
#include <tncifimv.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pb_assessment_result_msg_t
Macros
#define ASSESSMENT_RESULT_MSG_SIZE 4
Typedefs
typedef struct
private_pb_assessment_result_msg_t private_pb_assessment_result_msg_t
Functions
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_assessment_result_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_assessment_result_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_assessment_result_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_assessment_result_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_assessment_result_msg_t *this)
METHOD (pb_assessment_result_msg_t, get_assessment_result, u_int32_t, private_pb_assessment_result_msg_t *this)
pb_tnc_msg_t * pb_assessment_result_msg_create_from_data (chunk_t data)
pb_tnc_msg_t * pb_assessment_result_msg_create (u_int32_t assessment_result)
Macro Definition Documentation
#define ASSESSMENT_RESULT_MSG_SIZE 4
PB-Assessment-Result message (see section 4.6 of RFC 5793)
                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Assessment Result | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 36 of file pb_assessment_result_msg.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pb_assessment_result_msg_t private_pb_assessment_result_msg_t
Definition at line 24 of file pb_assessment_result_msg.c.
Function Documentation
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_assessment_result_msg_t * this)
Definition at line 64 of file pb_assessment_result_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_assessment_result_msg_t * this)
Definition at line 70 of file pb_assessment_result_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_assessment_result_msg_t * this)
Definition at line 76 of file pb_assessment_result_msg.c.
References ASSESSMENT_RESULT_MSG_SIZE, bio_writer_create(), chunk_clone, bio_writer_t::destroy, encoding, bio_writer_t::get_buf, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     writer = bio_writer_create(ASSESSMENT_RESULT_MSG_SIZE);
     writer->write_uint32(writer, this->assessment_result);
     this->encoding = writer->get_buf(writer);
     this->encoding = chunk_clone(this->encoding);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_assessment_result_msg_t * this, u_int32_t * offset)
Definition at line 92 of file pb_assessment_result_msg.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, encoding, FAILED, bio_reader_t::read_uint32, SUCCESS, TNC_IMV_EVALUATION_RESULT_COMPLIANT, and TNC_IMV_EVALUATION_RESULT_DONT_KNOW.
 {
     bio_reader_t *reader;
     reader = bio_reader_create(this->encoding);
     reader->read_uint32(reader, &this->assessment_result);
     reader->destroy(reader);
     if (this->assessment_result < TNC_IMV_EVALUATION_RESULT_COMPLIANT ||
         this->assessment_result > TNC_IMV_EVALUATION_RESULT_DONT_KNOW)
     {
         DBG1(DBG_TNC, "invalid assessment result (%u)",
                        this->assessment_result);
         *offset = 0;
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_assessment_result_msg_t * this)
Definition at line 113 of file pb_assessment_result_msg.c.
References encoding, and free().
 {
     free(this->encoding.ptr);
     free(this);
 }
METHOD (pb_assessment_result_msg_t , get_assessment_result , u_int32_t , private_pb_assessment_result_msg_t * this)
Definition at line 120 of file pb_assessment_result_msg.c.
 {
     return this->assessment_result;
 }