strongSwan: tkm_private_key.c File Reference
tkm_private_key.c File Reference
#include <utils/debug.h>
#include <tkm/constants.h>
#include <tkm/client.h>
#include "tkm_utils.h"
#include "tkm_types.h"
#include "tkm_private_key.h"
Classes
struct private_tkm_private_key_t
Typedefs
typedef struct
private_tkm_private_key_t private_tkm_private_key_t
Functions
METHOD (private_key_t, get_type, key_type_t, private_tkm_private_key_t *this)
METHOD (private_key_t, sign, bool, private_tkm_private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
METHOD (private_key_t, decrypt, bool, private_tkm_private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
METHOD (private_key_t, get_keysize, int, private_tkm_private_key_t *this)
METHOD (private_key_t, get_public_key, public_key_t *, private_tkm_private_key_t *this)
METHOD (private_key_t, get_encoding, bool, private_tkm_private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (private_key_t, get_fingerprint, bool, private_tkm_private_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (private_key_t, get_ref, private_key_t *, private_tkm_private_key_t *this)
METHOD (private_key_t, destroy, void, private_tkm_private_key_t *this)
tkm_private_key_t * tkm_private_key_init (identification_t *const id)
Typedef Documentation
typedef struct private_tkm_private_key_t private_tkm_private_key_t
Definition at line 25 of file tkm_private_key.c.
Function Documentation
METHOD (private_key_t , get_type , key_type_t , private_tkm_private_key_t * this)
Definition at line 54 of file tkm_private_key.c.
References key_type.
 {
     return this->key_type;
 }
METHOD (private_key_t , sign , bool , private_tkm_private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * signature)
Definition at line 60 of file tkm_private_key.c.
References chunk_free(), chunk_to_sequence(), DBG1, DBG_LIB, FALSE, sign_info_t::init_message, sign_info_t::isa_id, msg, chunk_t::ptr, sequence_to_chunk(), sig, sign(), and TRUE.
 {
     signature_type sig;
     init_message_type msg;
     sign_info_t sign;
     isa_id_type isa_id;
     if (data.ptr == NULL)
     {
         DBG1(DBG_LIB, "unable to get signature information");
         return FALSE;
     }
     sign = *(sign_info_t *)(data.ptr);
     chunk_to_sequence(&sign.init_message, &msg, sizeof(init_message_type));
     isa_id = sign.isa_id;
     chunk_free(&sign.init_message);
     if (ike_isa_sign(isa_id, 1, msg, &sig) != TKM_OK)
     {
         DBG1(DBG_LIB, "signature operation failed");
         return FALSE;
     }
     sequence_to_chunk(sig.data, sig.size, signature);
     return TRUE;
 }
METHOD (private_key_t , decrypt , bool , private_tkm_private_key_t * this, encryption_scheme_t scheme, chunk_t crypto, chunk_t * plain)
Definition at line 90 of file tkm_private_key.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (private_key_t , get_keysize , int , private_tkm_private_key_t * this)
Definition at line 97 of file tkm_private_key.c.
 {
     return 0;
 }
METHOD (private_key_t , get_public_key , public_key_t * , private_tkm_private_key_t * this)
Definition at line 103 of file tkm_private_key.c.
 {
     return NULL;
 }
METHOD (private_key_t , get_encoding , bool , private_tkm_private_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 109 of file tkm_private_key.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (private_key_t , get_fingerprint , bool , private_tkm_private_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 116 of file tkm_private_key.c.
References TRUE.
 {
     *fp = this->id->get_encoding(this->id);
     return TRUE;
 }
METHOD (private_key_t , get_ref , private_key_t * , private_tkm_private_key_t * this)
Definition at line 123 of file tkm_private_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (private_key_t , destroy , void , private_tkm_private_key_t * this)
Definition at line 130 of file tkm_private_key.c.
References free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         this->id->destroy(this->id);
         free(this);
     }
 }