strongSwan: vici_cred
vici_cred
vici
Classes
struct vici_cred_t
Typedefs
typedef struct vici_cred_t vici_cred_t
Functions
vici_cred_t * vici_cred_create (vici_dispatcher_t *dispatcher)
Detailed Description
Typedef Documentation
typedef struct vici_cred_t vici_cred_t
Definition at line 26 of file vici_cred.h.
Function Documentation
vici_cred_t* vici_cred_create (vici_dispatcher_t * dispatcher)
Create a vici_cred instance.
Parameters
dispatcher dispatcher to receive requests from
Returns
credential backend
See header
Definition at line 324 of file vici_cred.c.
References credential_manager_t::add_set, library_t::credmgr, INIT, lib, manage_commands(), mem_cred_create(), and TRUE.
Referenced by register_vici().
 {
     private_vici_cred_t *this;
     INIT(this,
         .public = {
             .add_cert = _add_cert,
             .destroy = _destroy,
         },
         .dispatcher = dispatcher,
         .creds = mem_cred_create(),
     );
     lib->credmgr->add_set(lib->credmgr, &this->creds->set);
     manage_commands(this, TRUE);
     return &this->public;
 }