strongSwan: vici_message.c File Reference
vici_message.c File Reference
#include "vici_message.h"
#include "vici_builder.h"
#include <bio/bio_reader.h>
#include <bio/bio_writer.h>
#include <errno.h>
Classes
struct private_vici_message_t
struct parse_enumerator_t
struct vici_parse_context_t
Typedefs
typedef struct
private_vici_message_t private_vici_message_t
Functions
ENUM (vici_type_names, VICI_START, VICI_END,"start","section-start","section-end","key-value","list-start","list-item","list-end","end")
bool vici_stringify (chunk_t chunk, char *buf, size_t size)
bool vici_verify_type (vici_type_t type, u_int section, bool list)
METHOD (enumerator_t, parse_enumerate, bool, parse_enumerator_t *this, vici_type_t *out, char **name, chunk_t *value)
METHOD (enumerator_t, parse_destroy, void, parse_enumerator_t *this)
METHOD (vici_message_t, create_enumerator, enumerator_t *, private_vici_message_t *this)
static bool find_value (private_vici_message_t *this, chunk_t *value, char *fmt, va_list args)
METHOD (vici_message_t, vget_str, char *, private_vici_message_t *this, char *def, char *fmt, va_list args)
METHOD (vici_message_t, get_str, char *, private_vici_message_t *this, char *def, char *fmt,...)
METHOD (vici_message_t, vget_int, int, private_vici_message_t *this, int def, char *fmt, va_list args)
METHOD (vici_message_t, get_int, int, private_vici_message_t *this, int def, char *fmt,...)
METHOD (vici_message_t, vget_bool, bool, private_vici_message_t *this, bool def, char *fmt, va_list args)
METHOD (vici_message_t, get_bool, bool, private_vici_message_t *this, bool def, char *fmt,...)
METHOD (vici_message_t, vget_value, chunk_t, private_vici_message_t *this, chunk_t def, char *fmt, va_list args)
METHOD (vici_message_t, get_value, chunk_t, private_vici_message_t *this, chunk_t def, char *fmt,...)
METHOD (vici_message_t, get_encoding, chunk_t, private_vici_message_t *this)
METHOD (vici_message_t, parse, bool, private_vici_message_t *this, vici_parse_context_t *ctx, vici_section_cb_t section, vici_value_cb_t kv, vici_value_cb_t li, void *user)
METHOD (vici_message_t, dump, bool, private_vici_message_t *this, char *label, bool pretty, FILE *out)
METHOD (vici_message_t, destroy, void, private_vici_message_t *this)
vici_message_t * vici_message_create_from_data (chunk_t data, bool cleanup)
vici_message_t * vici_message_create_from_enumerator (enumerator_t *enumerator)
vici_message_t * vici_message_create_from_args (vici_type_t type,...)
Typedef Documentation
typedef struct private_vici_message_t private_vici_message_t
Definition at line 27 of file vici_message.c.
Function Documentation
ENUM (vici_type_names , VICI_START , VICI_END , "start" , "section-start" , "section-end" , "key-value" , "list-start" , "list-item" , "list-end" , "end")
static bool find_value (private_vici_message_t * this, chunk_t * value, char * fmt, va_list args) static
Find a value for given vararg key
Definition at line 233 of file vici_message.c.
References create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, key, name, next, section, streq(), TRUE, type, VICI_END, VICI_KEY_VALUE, VICI_SECTION_END, VICI_SECTION_START, and vsnprintf.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     char buf[128], *name, *key, *dot, *next;
     int section = 0, keysection = 0;
     bool found = FALSE;
     chunk_t current;
     vici_type_t type;
     vsnprintf(buf, sizeof(buf), fmt, args);
     next = buf;
     enumerator = create_enumerator(this);
     /* descent into section */
     while (TRUE)
     {
         dot = strchr(next, '.');
         if (!dot)
         {
             key = next;
             break;
         }
         *dot = '\0';
         key = next;
         next = dot + 1;
         keysection++;
         while (enumerator->enumerate(enumerator, &type, &name, &current))
         {
             switch (type)
             {
                 case VICI_SECTION_START:
                     section++;
                     if (section == keysection && streq(name, key))
                     {
                         break;
                     }
                     continue;
                 case VICI_SECTION_END:
                     section--;
                     continue;
                 case VICI_END:
                     break;
                 default:
                     continue;
             }
             break;
         }
     }
     /* find key/value in current section */
     while (enumerator->enumerate(enumerator, &type, &name, &current))
     {
         switch (type)
         {
             case VICI_KEY_VALUE:
                 if (section == keysection && streq(key, name))
                 {
                     *value = current;
                     found = TRUE;
                     break;
                 }
                 continue;
             case VICI_SECTION_START:
                 section++;
                 continue;
             case VICI_SECTION_END:
                 section--;
                 continue;
             case VICI_END:
                 break;
             default:
                 continue;
         }
         break;
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (enumerator_t , parse_enumerate , bool , parse_enumerator_t * this, vici_type_t * out, char ** name, chunk_t * value)
Definition at line 137 of file vici_message.c.
References data, DBG1, DBG_ENC, FALSE, list, name, section, TRUE, type, VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_SECTION_END, VICI_SECTION_START, vici_stringify(), vici_type_names, and vici_verify_type().
 {
     u_int8_t type;
     chunk_t data;
     if (!this->reader->remaining(this->reader) ||
         !this->reader->read_uint8(this->reader, &type))
     {
         *out = VICI_END;
         return TRUE;
     }
     if (!vici_verify_type(type, this->section, this->list))
     {
         return FALSE;
     }
     switch (type)
     {
         case VICI_SECTION_START:
             if (!this->reader->read_data8(this->reader, &data) ||
                 !vici_stringify(data, this->name, sizeof(this->name)))
             {
                 DBG1(DBG_ENC, "invalid '%N' encoding", vici_type_names, type);
                 return FALSE;
             }
             *name = this->name;
             this->section++;
             break;
         case VICI_SECTION_END:
             this->section--;
             break;
         case VICI_KEY_VALUE:
             if (!this->reader->read_data8(this->reader, &data) ||
                 !vici_stringify(data, this->name, sizeof(this->name)) ||
                 !this->reader->read_data16(this->reader, value))
             {
                 DBG1(DBG_ENC, "invalid '%N' encoding", vici_type_names, type);
                 return FALSE;
             }
             *name = this->name;
             break;
         case VICI_LIST_START:
             if (!this->reader->read_data8(this->reader, &data) ||
                 !vici_stringify(data, this->name, sizeof(this->name)))
             {
                 DBG1(DBG_ENC, "invalid '%N' encoding", vici_type_names, type);
                 return FALSE;
             }
             *name = this->name;
             this->list = TRUE;
             break;
         case VICI_LIST_ITEM:
             this->reader->read_data16(this->reader, value);
             break;
         case VICI_LIST_END:
             this->list = FALSE;
             break;
         case VICI_END:
             return TRUE;
         default:
             DBG1(DBG_ENC, "unknown encoding type: %u", type);
             return FALSE;
     }
     *out = type;
     return TRUE;
 }
METHOD (enumerator_t , parse_destroy , void , parse_enumerator_t * this)
Definition at line 207 of file vici_message.c.
References free().
 {
     this->reader->destroy(this->reader);
     free(this);
 }
METHOD (vici_message_t , create_enumerator , enumerator_t * , private_vici_message_t * this)
Definition at line 214 of file vici_message.c.
References bio_reader_create(), destroy(), encoding, INIT, and parse_enumerator_t::public.
 {
     parse_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_parse_enumerate,
             .destroy = _parse_destroy,
         },
         .reader = bio_reader_create(this->encoding),
     );
     return &enumerator->public;
 }
METHOD (vici_message_t , vget_str , char * , private_vici_message_t * this, char * def, char * fmt, va_list args)
Definition at line 317 of file vici_message.c.
References chunk_printable(), find_value(), found, chunk_t::len, chunk_t::ptr, str, strndup(), and value.
 {
     chunk_t value;
     bool found;
     char *str;
     found = find_value(this, &value, fmt, args);
     if (found)
     {
         if (chunk_printable(value, NULL, 0))
         {
             str = strndup(value.ptr, value.len);
             /* keep a reference to string, so caller doesn't have to care */
             this->strings->insert_last(this->strings, str);
             return str;
         }
     }
     return def;
 }
METHOD (vici_message_t , get_str , char * , private_vici_message_t * this, char * def, char * fmt, ...)
Definition at line 338 of file vici_message.c.
References str.
 {
     va_list args;
     char *str;
     va_start(args, fmt);
     str = vget_str(this, def, fmt, args);
     va_end(args);
     return str;
 }
METHOD (vici_message_t , vget_int , int , private_vici_message_t * this, int def, char * fmt, va_list args)
Definition at line 350 of file vici_message.c.
References chunk_printable(), find_value(), found, chunk_t::len, chunk_t::ptr, snprintf, and value.
 {
     chunk_t value;
     bool found;
     char buf[32], *pos;
     int ret;
     found = find_value(this, &value, fmt, args);
     if (found)
     {
         if (value.len == 0)
         {
             return def;
         }
         if (chunk_printable(value, NULL, 0))
         {
             snprintf(buf, sizeof(buf), "%.*s", (int)value.len, value.ptr);
             errno = 0;
             ret = strtol(buf, &pos, 0);
             if (errno == 0 && pos == buf + strlen(buf))
             {
                 return ret;
             }
         }
     }
     return def;
 }
METHOD (vici_message_t , get_int , int , private_vici_message_t * this, int def, char * fmt, ...)
Definition at line 379 of file vici_message.c.
References val.
 {
     va_list args;
     int val;
     va_start(args, fmt);
     val = vget_int(this, def, fmt, args);
     va_end(args);
     return val;
 }
METHOD (vici_message_t , vget_bool , bool , private_vici_message_t * this, bool def, char * fmt, va_list args)
Definition at line 391 of file vici_message.c.
References chunk_printable(), find_value(), found, chunk_t::len, chunk_t::ptr, settings_value_as_bool(), snprintf, and value.
 {
     chunk_t value;
     bool found;
     char buf[16];
     found = find_value(this, &value, fmt, args);
     if (found)
     {
         if (value.len == 0)
         {
             return def;
         }
         if (chunk_printable(value, NULL, 0))
         {
             snprintf(buf, sizeof(buf), "%.*s", (int)value.len, value.ptr);
             return settings_value_as_bool(buf, def);
         }
     }
     return def;
 }
METHOD (vici_message_t , get_bool , bool , private_vici_message_t * this, bool def, char * fmt, ...)
Definition at line 414 of file vici_message.c.
References val.
 {
     va_list args;
     bool val;
     va_start(args, fmt);
     val = vget_bool(this, def, fmt, args);
     va_end(args);
     return val;
 }
METHOD (vici_message_t , vget_value , chunk_t , private_vici_message_t * this, chunk_t def, char * fmt, va_list args)
Definition at line 426 of file vici_message.c.
References find_value(), found, and value.
 {
     chunk_t value;
     bool found;
     found = find_value(this, &value, fmt, args);
     if (found)
     {
         return value;
     }
     return def;
 }
METHOD (vici_message_t , get_value , chunk_t , private_vici_message_t * this, chunk_t def, char * fmt, ...)
Definition at line 440 of file vici_message.c.
References value.
 {
     va_list args;
     chunk_t value;
     va_start(args, fmt);
     value = vget_value(this, def, fmt, args);
     va_end(args);
     return value;
 }
METHOD (vici_message_t , get_encoding , chunk_t , private_vici_message_t * this)
Definition at line 452 of file vici_message.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (vici_message_t , parse , bool , private_vici_message_t * this, vici_parse_context_t * ctx, vici_section_cb_t section, vici_value_cb_t kv, vici_value_cb_t li, void * user)
Definition at line 468 of file vici_message.c.
References base, create_enumerator(), enumerator_t::destroy, vici_parse_context_t::e, enumerator_t::enumerate, vici_parse_context_t::level, list, name, ok, format-options::root, section, strdup, TRUE, type, value, VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_SECTION_END, VICI_SECTION_START, and VICI_START.
 {
     vici_parse_context_t root = {};
     char *name, *list = NULL;
     vici_type_t type;
     chunk_t value;
     int base;
     bool ok = TRUE;
     if (!ctx)
     {
         ctx = &root;
         root.e = create_enumerator(this);
     }
     base = ctx->level;
     while (ok)
     {
         ok = ctx->e->enumerate(ctx->e, &type, &name, &value);
         if (ok)
         {
             switch (type)
             {
                 case VICI_START:
                     /* should never occur */
                     continue;
                 case VICI_KEY_VALUE:
                     if (ctx->level == base && kv)
                     {
                         name = strdup(name);
                         this->strings->insert_last(this->strings, name);
                         ok = kv(user, &this->public, name, value);
                     }
                     continue;
                 case VICI_LIST_START:
                     if (ctx->level == base)
                     {
                         list = strdup(name);
                         this->strings->insert_last(this->strings, list);
                     }
                     continue;
                 case VICI_LIST_ITEM:
                     if (list && li)
                     {
                         name = strdup(name);
                         this->strings->insert_last(this->strings, name);
                         ok = li(user, &this->public, list, value);
                     }
                     continue;
                 case VICI_LIST_END:
                     if (ctx->level == base)
                     {
                         list = NULL;
                     }
                     continue;
                 case VICI_SECTION_START:
                     if (ctx->level++ == base && section)
                     {
                         name = strdup(name);
                         this->strings->insert_last(this->strings, name);
                         ok = section(user, &this->public, ctx, name);
                     }
                     continue;
                 case VICI_SECTION_END:
                     if (ctx->level-- == base)
                     {
                         break;
                     }
                     continue;
                 case VICI_END:
                     break;
             }
         }
         break;
     }
     if (ctx == &root)
     {
         root.e->destroy(root.e);
     }
     return ok;
 }
METHOD (vici_message_t , dump , bool , private_vici_message_t * this, char * label, bool pretty, FILE * out)
Definition at line 555 of file vici_message.c.
References chunk_printable(), create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, fprintf, chunk_t::len, name, chunk_t::ptr, sep, TRUE, type, value, VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_SECTION_END, VICI_SECTION_START, and VICI_START.
 {
     enumerator_t *enumerator;
     int ident = 0, delta;
     vici_type_t type, last_type = VICI_START;
     char *name, *term, *sep, *separ, *assign;
     chunk_t value;
     /* pretty print uses indentation on multiple lines */
     if (pretty)
     {
         delta  = 2;
         term   = "\n";
         separ  = "";
         assign = " = ";
     }
     else
     {
         delta  = 0;
         term   = "";
         separ  = " ";
         assign = "=";
     }
     fprintf(out, "%s {%s", label, term);
     ident += delta;
     enumerator = create_enumerator(this);
     while (enumerator->enumerate(enumerator, &type, &name, &value))
     {
         switch (type)
         {
             case VICI_START:
                 /* should never occur */
                 break;
             case VICI_SECTION_START:
                 sep = (last_type != VICI_SECTION_START &&
                        last_type != VICI_START) ? separ : "";
                 fprintf(out, "%*s%s%s {%s", ident, "", sep, name, term);
                 ident += delta;
                 break;
             case VICI_SECTION_END:
                 ident -= delta;
                 fprintf(out, "%*s}%s", ident, "", term);
                 break;
             case VICI_KEY_VALUE:
                 sep = (last_type != VICI_SECTION_START &&
                        last_type != VICI_START) ? separ : "";
                 if (chunk_printable(value, NULL, ' '))
                 {
                     fprintf(out, "%*s%s%s%s%.*s%s", ident, "", sep, name,
                             assign, (int)value.len, value.ptr, term);
                 }
                 else
                 {
                     fprintf(out, "%*s%s%s%s0x%+#B%s", ident, "", sep, name,
                             assign, &value, term);
                 }
                 break;
             case VICI_LIST_START:
                 sep = (last_type != VICI_SECTION_START &&
                        last_type != VICI_START) ? separ : "";
                 fprintf(out, "%*s%s%s%s[%s", ident, "", sep, name, assign, term);
                 ident += delta;
                 break;
             case VICI_LIST_END:
                 ident -= delta;
                 fprintf(out, "%*s]%s", ident, "", term);
                 break;
             case VICI_LIST_ITEM:
                 sep = (last_type != VICI_LIST_START) ? separ : "";
                 if (chunk_printable(value, NULL, ' '))
                 {
                     fprintf(out, "%*s%s%.*s%s", ident, "", sep,
                             (int)value.len, value.ptr, term);
                 }
                 else
                 {
                     fprintf(out, "%*s%s0x%+#B%s", ident, "", sep,
                             &value, term);
                 }
                 break;
             case VICI_END:
                 fprintf(out, "}\n");
                 enumerator->destroy(enumerator);
                 return TRUE;
         }
         last_type = type;
     }
     enumerator->destroy(enumerator);
     return FALSE;
 }
METHOD (vici_message_t , destroy , void , private_vici_message_t * this)
Definition at line 649 of file vici_message.c.
References chunk_clear(), cleanup, encoding, and free().
 {
     if (this->cleanup)
     {
         chunk_clear(&this->encoding);
     }
     this->strings->destroy_function(this->strings, free);
     free(this);
 }