strongSwan: bio_reader
bio_reader
bio
Classes
struct bio_reader_t
Typedefs
typedef struct bio_reader_t bio_reader_t
Functions
bio_reader_t * bio_reader_create (chunk_t data)
bio_reader_t * bio_reader_create_own (chunk_t data)
Detailed Description
Typedef Documentation
typedef struct bio_reader_t bio_reader_t
Definition at line 27 of file bio_reader.h.
Function Documentation
bio_reader_t* bio_reader_create (chunk_t data)
Create a bio_reader instance.
Parameters
data data buffer, must survive lifetime of reader
Returns
reader
See header
Definition at line 317 of file bio_reader.c.
References data, and INIT.
Referenced by bio_reader_create_own(), CALLBACK(), dnscert_create_frm_rr(), find_private_key(), get_identity_attribute(), handle_supported_hash_algorithms(), ipseckey_create_frm_rr(), METHOD(), parse_public_key(), peer_supports_curve(), process_cert_verify(), process_certificate(), process_certreq(), process_client_hello(), process_handshake(), process_tnc_msg(), receive_msg(), remove_padding(), seg_env_create_from_data(), and START_TEST().
 {
     private_bio_reader_t *this;
     INIT(this,
         .public = {
             .remaining = _remaining,
             .peek = _peek,
             .read_uint8 = _read_uint8,
             .read_uint16 = _read_uint16,
             .read_uint24 = _read_uint24,
             .read_uint32 = _read_uint32,
             .read_uint64 = _read_uint64,
             .read_data = _read_data,
             .read_uint8_end = _read_uint8_end,
             .read_uint16_end = _read_uint16_end,
             .read_uint24_end = _read_uint24_end,
             .read_uint32_end = _read_uint32_end,
             .read_uint64_end = _read_uint64_end,
             .read_data_end = _read_data_end,
             .read_data8 = _read_data8,
             .read_data16 = _read_data16,
             .read_data24 = _read_data24,
             .read_data32 = _read_data32,
             .destroy = _destroy,
         },
         .buf = data,
     );
     return &this->public;
 }
bio_reader_t* bio_reader_create_own (chunk_t data)
Create a bio_reader instance owning buffer.
Parameters
data data buffer, gets freed with destroy()
Returns
reader
See header
Definition at line 352 of file bio_reader.c.
References bio_reader_create(), cleanup, and data.
Referenced by read_tls(), and START_TEST().
 {
     private_bio_reader_t *this;
     this = (private_bio_reader_t*)bio_reader_create(data);
     this->cleanup = data;
     return &this->public;
 }