strongSwan: auth_payload_t Struct Reference
auth_payload_t Struct Reference
auth_payload
#include "auth_payload.h"
Public Attributes
payload_t payload_interface
void(* set_auth_method)(auth_payload_t *this, auth_method_t method)
auth_method_t(* get_auth_method)(auth_payload_t *this)
void(* set_data)(auth_payload_t *this, chunk_t data)
chunk_t(* get_data)(auth_payload_t *this)
bool(* get_reserved_bit)(auth_payload_t *this, u_int nr)
void(* set_reserved_bit)(auth_payload_t *this, u_int nr)
void(* destroy)(auth_payload_t *this)
Detailed Description
Class representing an IKEv2 AUTH payload.
The AUTH payload format is described in RFC section 3.8.
Definition at line 36 of file auth_payload.h.
Member Data Documentation
void(* auth_payload_t::destroy)(auth_payload_t *this)
Destroys an auth_payload_t object.
Definition at line 89 of file auth_payload.h.
auth_method_t(* auth_payload_t::get_auth_method)(auth_payload_t *this)
Get the AUTH method.
Returns
auth_method_t used
Definition at line 55 of file auth_payload.h.
Referenced by build_certs(), and METHOD().
chunk_t(* auth_payload_t::get_data)(auth_payload_t *this)
Get the AUTH data.
Returns
AUTH data as chunk_t, internal data
Definition at line 69 of file auth_payload.h.
Referenced by METHOD(), and verify_auth().
bool(* auth_payload_t::get_reserved_bit)(auth_payload_t *this, u_int nr)
Get the value of a reserved bit.
Parameters
nr number of the reserved bit, 0-6
Returns
TRUE if bit was set, FALSE to clear
Definition at line 77 of file auth_payload.h.
payload_t auth_payload_t::payload_interface
The payload_t interface.
Definition at line 41 of file auth_payload.h.
void(* auth_payload_t::set_auth_method)(auth_payload_t *this, auth_method_t method)
Set the AUTH method.
Parameters
method auth_method_t to use
Definition at line 48 of file auth_payload.h.
Referenced by build_auth(), METHOD(), and rebuild_auth().
void(* auth_payload_t::set_data)(auth_payload_t *this, chunk_t data)
Set the AUTH data.
Parameters
data AUTH data as chunk_t, gets cloned
Definition at line 62 of file auth_payload.h.
Referenced by build_auth(), METHOD(), and rebuild_auth().
void(* auth_payload_t::set_reserved_bit)(auth_payload_t *this, u_int nr)
Set one of the reserved bits.
Parameters
nr number of the reserved bit, 0-6
Definition at line 84 of file auth_payload.h.
The documentation for this struct was generated from the following file:
auth_payload.h