strongSwan: openssl_crypter.c File Reference
openssl_crypter.c File Reference
#include "openssl_crypter.h"
#include <openssl/evp.h>
Classes
struct private_openssl_crypter_t
Typedefs
typedef struct
private_openssl_crypter_t private_openssl_crypter_t
Functions
static char * lookup_algorithm (u_int16_t ikev2_algo, size_t *key_size)
static bool crypt (private_openssl_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *dst, int enc)
METHOD (crypter_t, decrypt, bool, private_openssl_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *dst)
METHOD (crypter_t, encrypt, bool, private_openssl_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *dst)
METHOD (crypter_t, get_block_size, size_t, private_openssl_crypter_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_openssl_crypter_t *this)
METHOD (crypter_t, get_key_size, size_t, private_openssl_crypter_t *this)
METHOD (crypter_t, set_key, bool, private_openssl_crypter_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_openssl_crypter_t *this)
openssl_crypter_t * openssl_crypter_create (encryption_algorithm_t algo, size_t key_size)
Typedef Documentation
typedef struct private_openssl_crypter_t private_openssl_crypter_t
Definition at line 20 of file openssl_crypter.c.
Function Documentation
static bool crypt (private_openssl_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * dst, int enc) static
Do the actual en/decryption in an EVP context
Definition at line 93 of file openssl_crypter.c.
References chunk_alloc, ctx, key, chunk_t::len, len, out, and chunk_t::ptr.
Referenced by METHOD().
 {
     int len;
     u_char *out;
     out = data.ptr;
     if (dst)
     {
         *dst = chunk_alloc(data.len);
         out = dst->ptr;
     }
     EVP_CIPHER_CTX ctx;
     EVP_CIPHER_CTX_init(&ctx);
     return EVP_CipherInit_ex(&ctx, this->cipher, NULL, NULL, NULL, enc) &&
            EVP_CIPHER_CTX_set_padding(&ctx, 0) /* disable padding */ &&
            EVP_CIPHER_CTX_set_key_length(&ctx, this->key.len) &&
            EVP_CipherInit_ex(&ctx, NULL, NULL, this->key.ptr, iv.ptr, enc) &&
            EVP_CipherUpdate(&ctx, out, &len, data.ptr, data.len) &&
            /* since padding is disabled this does nothing */
            EVP_CipherFinal_ex(&ctx, out + len, &len) &&
            EVP_CIPHER_CTX_cleanup(&ctx);
 }
static char* lookup_algorithm (u_int16_t ikev2_algo, size_t * key_size) static
Look up an OpenSSL algorithm name and validate its key size
Definition at line 46 of file openssl_crypter.c.
References countof, ENCR_3DES, ENCR_BLOWFISH, ENCR_CAST, ENCR_DES, ENCR_IDEA, ENCR_RC5, and name.
Referenced by openssl_crypter_create().
 {
     struct {
         /* identifier specified in IKEv2 */
         int ikev2_id;
         /* name of the algorithm, as used in OpenSSL */
         char *name;
         /* default key size in bytes */
         size_t key_def;
         /* minimum key size */
         size_t key_min;
         /* maximum key size */
         size_t key_max;
     } mappings[] = {
         {ENCR_DES,          "des",           8,      8,       8},
         {ENCR_3DES,         "des3",         24,     24,      24},
         {ENCR_RC5,          "rc5",          16,      5,     255},
         {ENCR_IDEA,         "idea",         16,     16,      16},
         {ENCR_CAST,         "cast",         16,      5,      16},
         {ENCR_BLOWFISH,     "blowfish",     16,      5,      56},
     };
     int i;
     for (i = 0; i < countof(mappings); i++)
     {
         if (ikev2_algo == mappings[i].ikev2_id)
         {
             /* set the key size if it is not set */
             if (*key_size == 0)
             {
                 *key_size = mappings[i].key_def;
             }
             /* validate key size */
             if (*key_size < mappings[i].key_min ||
                 *key_size > mappings[i].key_max)
             {
                 return NULL;
             }
             return mappings[i].name;
         }
     }
     return NULL;
 }
METHOD (crypter_t , decrypt , bool , private_openssl_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * dst)
Definition at line 117 of file openssl_crypter.c.
References crypt().
 {
     return crypt(this, data, iv, dst, 0);
 }
METHOD (crypter_t , encrypt , bool , private_openssl_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * dst)
Definition at line 123 of file openssl_crypter.c.
References crypt().
 {
     return crypt(this, data, iv, dst, 1);
 }
METHOD (crypter_t , get_block_size , size_t , private_openssl_crypter_t * this)
Definition at line 129 of file openssl_crypter.c.
 {
     return this->cipher->block_size;
 }
METHOD (crypter_t , get_iv_size , size_t , private_openssl_crypter_t * this)
Definition at line 135 of file openssl_crypter.c.
 {
     return this->cipher->iv_len;
 }
METHOD (crypter_t , get_key_size , size_t , private_openssl_crypter_t * this)
Definition at line 141 of file openssl_crypter.c.
References key.
 {
     return this->key.len;
 }
METHOD (crypter_t , set_key , bool , private_openssl_crypter_t * this, chunk_t key)
Definition at line 147 of file openssl_crypter.c.
References chunk_t::len, memcpy, min, chunk_t::ptr, and TRUE.
 {
     memcpy(this->key.ptr, key.ptr, min(key.len, this->key.len));
     return TRUE;
 }
METHOD (crypter_t , destroy , void , private_openssl_crypter_t * this)
Definition at line 154 of file openssl_crypter.c.
References chunk_clear(), free(), and key.
 {
     chunk_clear(&this->key);
     free(this);
 }