strongSwan: certreq_payload
certreq_payload
payloads
Classes
struct certreq_payload_t
Typedefs
typedef struct certreq_payload_t certreq_payload_t
Functions
certreq_payload_t * certreq_payload_create (payload_type_t payload_type)
certreq_payload_t * certreq_payload_create_type (certificate_type_t type)
certreq_payload_t * certreq_payload_create_dn (identification_t *id)
Detailed Description
Typedef Documentation
typedef struct certreq_payload_t certreq_payload_t
Definition at line 25 of file certreq_payload.h.
Function Documentation
certreq_payload_t* certreq_payload_create (payload_type_t payload_type)
Creates an empty certreq_payload_t object.
Returns
certreq payload
Definition at line 257 of file certreq_payload.c.
References INIT, PL_NONE, and type.
Referenced by certreq_payload_create_dn(), certreq_payload_create_type(), and payload_create().
 {
     private_certreq_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .create_keyid_enumerator = _create_keyid_enumerator,
             .get_cert_type = _get_cert_type,
             .add_keyid = _add_keyid,
             .destroy = _destroy,
             .get_dn = _get_dn,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
         .type = type,
     );
     return &this->public;
 }
certreq_payload_t* certreq_payload_create_dn (identification_t * id)
Creates a IKEv1 certreq_payload_t for a given distinguished name.
Parameters
id distinguished name, does not get owned
Returns
certreq payload
Definition at line 312 of file certreq_payload.c.
References certreq_payload_create(), chunk_clone, data, ENC_X509_SIGNATURE, encoding, identification_t::get_encoding, and PLV1_CERTREQ.
Referenced by add_certreq().
 {
     private_certreq_payload_t *this;
     this = (private_certreq_payload_t*)
                     certreq_payload_create(PLV1_CERTREQ);
     this->encoding = ENC_X509_SIGNATURE;
     this->data = chunk_clone(id->get_encoding(id));
     this->payload_length = get_header_length(this) + this->data.len;
     return &this->public;
 }
certreq_payload_t* certreq_payload_create_type (certificate_type_t type)
Creates an empty IKEv2 certreq_payload_t for a kind of certificates.
Parameters
type type of the added keyids
Returns
certreq payload
Definition at line 289 of file certreq_payload.c.
References CERT_X509, certificate_type_names, certreq_payload_create(), DBG1, DBG_ENC, ENC_X509_SIGNATURE, encoding, free(), and PLV2_CERTREQ.
Referenced by add_certreq().
 {
     private_certreq_payload_t *this;
     this = (private_certreq_payload_t*)
                     certreq_payload_create(PLV2_CERTREQ);
     switch (type)
     {
         case CERT_X509:
             this->encoding = ENC_X509_SIGNATURE;
             break;
         default:
             DBG1(DBG_ENC, "certificate type %N not supported in requests",
                  certificate_type_names, type);
             free(this);
             return NULL;
     }
     return &this->public;
 }