strongSwan: auth_cfg_t Struct Reference
auth_cfg_t Struct Reference
auth_cfg
#include "auth_cfg.h"
Public Attributes
void(* add)(auth_cfg_t *this, auth_rule_t rule,...)
void *(* get)(auth_cfg_t *this, auth_rule_t rule)
enumerator_t *(* create_enumerator)(auth_cfg_t *this)
void(* replace)(auth_cfg_t *this, enumerator_t *pos, auth_rule_t rule,...)
bool(* complies)(auth_cfg_t *this, auth_cfg_t *constraints, bool log_error)
void(* merge)(auth_cfg_t *this, auth_cfg_t *other, bool copy)
void(* purge)(auth_cfg_t *this, bool keep_ca)
bool(* equals)(auth_cfg_t *this, auth_cfg_t *other)
auth_cfg_t *(* clone)(auth_cfg_t *this)
void(* destroy)(auth_cfg_t *this)
Detailed Description
Authentication/Authorization round.
RFC4739 defines multiple authentication rounds. This class defines such a round from a configuration perspective, either for the local or the remote peer. Local configs are called "rulesets". They define how we authenticate. Remote peer configs are called "constraits". They define what is needed to complete the authentication round successfully.
[Repeat for each configuration]
+--------------------------------------------------+
|                                                  |
|                                                  |
|   +----------+     IKE_AUTH       +--------- +   |
|   |  config  |   ----------->     |          |   |
|   |  ruleset |                    |          |   |
|   +----------+ [ <----------- ]   |          |   |
|                [ optional EAP ]   |   Peer   |   |
|   +----------+ [ -----------> ]   |          |   |
|   |  config  |                    |          |   |
|   |  constr. |   <-----------     |          |   |
|   +----------+     IKE_AUTH       +--------- +   |
|                                                  |
|                                                  |
+--------------------------------------------------+
Values for each item are either pointers (casted to void*) or short integers (use uintptr_t cast).
Definition at line 167 of file auth_cfg.h.
Member Data Documentation
void(* auth_cfg_t::add)(auth_cfg_t *this, auth_rule_t rule,...)
Add a rule to the set.
Rules we expect only once (e.g. identities) implicitly replace previous rules of the same type (but pointers to previous values will remain valid until the auth_cfg_t object is destroyed). Rules that may occur multiple times (e.g. CA certificates) are inserted so that they can be enumerated in the order in which they were added. For these get() will return the value added first.
Parameters
rule rule type
... associated value to rule
Definition at line 182 of file auth_cfg.h.
Referenced by add_auth_cfg(), apply(), build_auth_cfg(), build_crl_policy(), build_peer_cfg(), build_trustchain(), CALLBACK(), check_constraints(), check_crl(), check_ocsp(), check_policy_constraints(), connect_(), enforce_recommendation(), generate_auth_cfg(), get_key_strength(), initiate_connection(), load_peer_config(), METHOD(), parse_cert(), parse_id(), parse_pubkey_constraints(), prefer_cert(), process_ac(), process_certreq(), process_certreqs(), process_class(), process_crl(), process_filter_id(), process_ike_update(), process_pkcs7(), process_x509(), replace_eap_identity(), setup_tunnel(), soap_init(), verify_auth(), and verify_trust_chain().
auth_cfg_t*(* auth_cfg_t::clone)(auth_cfg_t *this)
Clone an authentication config, including all rules.
Returns
cloned configuration
Definition at line 253 of file auth_cfg.h.
Referenced by METHOD().
bool(* auth_cfg_t::complies)(auth_cfg_t *this, auth_cfg_t *constraints, bool log_error)
Check if a used config fulfills a set of configured constraints.
Parameters
constraints required authorization rules
log_error whether to log compliance errors
Returns
TRUE if this complies with constraints
Definition at line 221 of file auth_cfg.h.
Referenced by check_constraints(), do_another_auth(), get_auth_cfg(), is_compliant(), and update_cfg_candidates().
enumerator_t*(* auth_cfg_t::create_enumerator)(auth_cfg_t *this)
Create an enumerator over added rules.
Refer to add() regarding the order in which rules are enumerated. For rules we expect only once the latest value is enumerated only.
Returns
enumerator over (auth_rule_t, union{void*,uintpr_t})
Definition at line 202 of file auth_cfg.h.
Referenced by add_certreqs(), add_im_certs(), auth_contains_cacert(), build_auth_cfgs(), build_cert_chain(), build_certs(), check_oid(), check_policy_constraints(), has_invalid_certs(), log_auth(), log_auth_cfgs(), METHOD(), prefer_cert(), process_eap(), select_signature_schemes(), send_supported_hash_algorithms(), and stroke_export().
void(* auth_cfg_t::destroy)(auth_cfg_t *this)
Destroy a config with all associated rules/values.
Definition at line 258 of file auth_cfg.h.
Referenced by build_auth(), build_trustchain(), CALLBACK(), flush_auth_cfgs(), METHOD(), soap_init(), and verify_trust_chain().
bool(* auth_cfg_t::equals)(auth_cfg_t *this, auth_cfg_t *other)
Check two configs for equality.
For rules we expect only once the latest value is compared only.
Parameters
other other config to compare against this
Returns
TRUE if auth infos identical
Definition at line 246 of file auth_cfg.h.
Referenced by auth_cfg_equal().
void*(* auth_cfg_t::get)(auth_cfg_t *this, auth_rule_t rule)
Get a rule value.
For rules we expect only once the latest value is returned.
Parameters
rule rule type
Returns
rule or NULL (or an appropriate default) if not found
Definition at line 192 of file auth_cfg.h.
Referenced by add_attribute_certs(), add_radius_attribute(), add_subject_cert(), build_cert_chain(), build_certs(), build_trustchain(), CALLBACK(), check_constraints(), check_crl(), check_policy_constraints(), client_process_eap(), find_public_key(), get_auth_class(), get_peer_match(), get_pubkey_method(), load_method(), log_auth_cfgs(), log_ike_sa(), lookup_shared_key(), METHOD(), require_strict(), server_initiate_eap(), server_process_eap(), and verify().
void(* auth_cfg_t::merge)(auth_cfg_t *this, auth_cfg_t *other, bool copy)
Merge items from other into this.
Parameters
other items to read for merge
copy TRUE to copy items, FALSE to move them
Definition at line 229 of file auth_cfg.h.
Referenced by add_auth_cfg(), apply_auth_cfg(), METHOD(), save_auth_cfg(), and verify_trust_chain().
void(* auth_cfg_t::purge)(auth_cfg_t *this, bool keep_ca)
Purge all rules in a config.
Parameters
keep_ca whether to keep AUTH_RULE_CA_CERT entries
Definition at line 236 of file auth_cfg.h.
Referenced by flush_auth_cfgs(), and METHOD().
void(* auth_cfg_t::replace)(auth_cfg_t *this, enumerator_t *pos, auth_rule_t rule,...)
Replace a rule at enumerator position.
Parameters
pos enumerator position
rule rule type
... associated value to rule
Definition at line 211 of file auth_cfg.h.
Referenced by fetch_cert(), and prefer_cert().
The documentation for this struct was generated from the following file:
auth_cfg.h