strongSwan: kernel_netlink_shared.h File Reference
kernel_netlink_shared.h File Reference
#include <library.h>
#include <linux/rtnetlink.h>
Classes
union netlink_buf_t
struct netlink_socket_t
Typedefs
typedef struct netlink_socket_t netlink_socket_t
Functions
netlink_socket_t * netlink_socket_create (int protocol, enum_name_t *names, bool parallel)
void netlink_add_attribute (struct nlmsghdr *hdr, int rta_type, chunk_t data, size_t buflen)
void * netlink_reserve (struct nlmsghdr *hdr, int buflen, int type, int len)
Typedef Documentation
typedef struct netlink_socket_t netlink_socket_t
Definition at line 34 of file kernel_netlink_shared.h.
Function Documentation
void netlink_add_attribute (struct nlmsghdr * hdr, int rta_type, chunk_t data, size_t buflen)
Creates an rtattr and adds it to the given netlink message.
Parameters
hdr netlink message
rta_type type of the rtattr
data data to add to the rtattr
buflen length of the netlink message buffer
Described in header.
Definition at line 618 of file kernel_netlink_shared.c.
References DBG1, DBG_KNL, chunk_t::len, memcpy, NLMSG_ALIGN, nlmsghdr::nlmsg_len, chunk_t::ptr, RTA_DATA, rtattr::rta_len, RTA_LENGTH, and rtattr::rta_type.
Referenced by CALLBACK(), get_route(), manage_ipaddr(), manage_rule(), manage_srcroute(), METHOD(), and START_TEST().
 {
     struct rtattr *rta;
     if (NLMSG_ALIGN(hdr->nlmsg_len) + RTA_LENGTH(data.len) > buflen)
     {
         DBG1(DBG_KNL, "unable to add attribute, buffer too small");
         return;
     }
     rta = (struct rtattr*)(((char*)hdr) + NLMSG_ALIGN(hdr->nlmsg_len));
     rta->rta_type = rta_type;
     rta->rta_len = RTA_LENGTH(data.len);
     memcpy(RTA_DATA(rta), data.ptr, data.len);
     hdr->nlmsg_len = NLMSG_ALIGN(hdr->nlmsg_len) + rta->rta_len;
 }
void* netlink_reserve (struct nlmsghdr * hdr, int buflen, int type, int len)
Reserve space in a netlink message for given size and type, returning buffer.
Parameters
hdr netlink message
buflen size of full netlink buffer
type RTA type
len length of RTA data
Returns
buffer to len bytes of attribute data, NULL on error
Described in header.
Definition at line 639 of file kernel_netlink_shared.c.
References DBG1, DBG_KNL, NLMSG_ALIGN, nlmsghdr::nlmsg_len, RTA_DATA, rtattr::rta_len, RTA_LENGTH, rtattr::rta_type, and type.
Referenced by add_mark(), add_policy_internal(), and METHOD().
 {
     struct rtattr *rta;
     if (NLMSG_ALIGN(hdr->nlmsg_len) + RTA_LENGTH(len) > buflen)
     {
         DBG1(DBG_KNL, "unable to add attribute, buffer too small");
         return NULL;
     }
     rta = ((void*)hdr) + NLMSG_ALIGN(hdr->nlmsg_len);
     rta->rta_type = type;
     rta->rta_len = RTA_LENGTH(len);
     hdr->nlmsg_len = NLMSG_ALIGN(hdr->nlmsg_len) + rta->rta_len;
     return RTA_DATA(rta);
 }
netlink_socket_t* netlink_socket_create (int protocol, enum_name_t * names, bool parallel)
Create a netlink_socket_t object.
Parameters
protocol protocol type (e.g. NETLINK_XFRM or NETLINK_ROUTE)
names optional enum names for Netlink messages
parallel support parallel queries on this Netlink socket
Described in header.
Definition at line 553 of file kernel_netlink_shared.c.
References watcher_t::add, bind, DBG1, DBG_KNL, destroy(), FALSE, settings_t::get_bool, settings_t::get_int, hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), INIT, lib, min, mutex_create(), MUTEX_TYPE_RECURSIVE, sockaddr_nl::nl_family, library_t::ns, protocol, library_t::settings, socket, watch(), library_t::watcher, and WATCHER_READ.
Referenced by kernel_netlink_ipsec_create(), kernel_netlink_net_create(), and START_TEST().
 {
     private_netlink_socket_t *this;
     struct sockaddr_nl addr = {
         .nl_family = AF_NETLINK,
     };
     INIT(this,
         .public = {
             .send = _netlink_send,
             .send_ack = _netlink_send_ack,
             .destroy = _destroy,
         },
         .seq = 200,
         .mutex = mutex_create(MUTEX_TYPE_RECURSIVE),
         .socket = socket(AF_NETLINK, SOCK_RAW, protocol),
         .entries = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 4),
         .protocol = protocol,
         .names = names,
         .buflen = lib->settings->get_int(lib->settings,
                             "%s.plugins.kernel-netlink.buflen", 0, lib->ns),
         .timeout = lib->settings->get_int(lib->settings,
                             "%s.plugins.kernel-netlink.timeout", 0, lib->ns),
         .retries = lib->settings->get_int(lib->settings,
                             "%s.plugins.kernel-netlink.retries", 0, lib->ns),
         .ignore_retransmit_errors = lib->settings->get_bool(lib->settings,
                             "%s.plugins.kernel-netlink.ignore_retransmit_errors",
                             FALSE, lib->ns),
         .parallel = parallel,
     );
     if (!this->buflen)
     {
         long pagesize = sysconf(_SC_PAGESIZE);
         if (pagesize == -1)
         {
             pagesize = 4096;
         }
         /* base this on NLMSG_GOODSIZE */
         this->buflen = min(pagesize, 8192);
     }
     if (this->socket == -1)
     {
         DBG1(DBG_KNL, "unable to create netlink socket");
         destroy(this);
         return NULL;
     }
     if (bind(this->socket, (struct sockaddr*)&addr, sizeof(addr)))
     {
         DBG1(DBG_KNL, "unable to bind netlink socket");
         destroy(this);
         return NULL;
     }
     if (this->parallel)
     {
         lib->watcher->add(lib->watcher, this->socket, WATCHER_READ, watch, this);
     }
     return &this->public;
 }