strongSwan: utils_tests.c File Reference
utils_tests.c File Reference
#include <tests/test_suite.h>
#include <tkm/types.h>
#include "tkm_utils.h"
Functions
START_TEST (test_sequence_to_chunk)
END_TEST START_TEST (test_chunk_to_sequence)
END_TEST Suite * make_utility_tests ()
Function Documentation
END_TEST Suite* make_utility_tests ()
Definition at line 57 of file utils_tests.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("utility tests");
     tc = tcase_create("chunk<->sequence");
     tcase_add_test(tc, test_sequence_to_chunk);
     tcase_add_test(tc, test_chunk_to_sequence);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_sequence_to_chunk)
Definition at line 23 of file utils_tests.c.
References chunk_empty, chunk_free(), fail_if, key, key_type, chunk_t::len, chunk_t::ptr, and sequence_to_chunk().
 {
     key_type key = {5, {0, 1, 2, 3, 4}};
     chunk_t chunk = chunk_empty;
     sequence_to_chunk(key.data, key.size, &chunk);
     fail_if(chunk.len != key.size, "Chunk size mismatch");
     uint32_t i;
     for (i = 0; i < key.size; i++)
     {
         fail_if(chunk.ptr[i] != i, "Data mismatch");
     }
     chunk_free(&chunk);
 }
END_TEST START_TEST (test_chunk_to_sequence)
Definition at line 40 of file utils_tests.c.
References chunk_from_thing, chunk_to_sequence(), fail_if, key, key_type, and chunk_t::len.
 {
     chunk_t chunk = chunk_from_thing("ABCDEFGH");
     key_type key;
     chunk_to_sequence(&chunk, &key, sizeof(key_type));
     fail_if(key.size != chunk.len, "Seq size mismatch");
     uint32_t i;
     for (i = 0; i < key.size - 1; i++)
     {
         fail_if(key.data[i] != 65 + i, "Data mismatch (1)");
     }
     fail_if(key.data[key.size - 1] != 0, "Data mismatch (2)");
 }