strongSwan: attribute_provider_t Struct Reference
attribute_provider_t Struct Reference
attribute_provider
#include "attribute_provider.h"
Public Attributes
host_t *(* acquire_address)(attribute_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
bool(* release_address)(attribute_provider_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
enumerator_t *(* create_attribute_enumerator)(attribute_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
Detailed Description
Interface to provide attributes to peers through attribute manager.
Definition at line 33 of file attribute_provider.h.
Member Data Documentation
host_t*(* attribute_provider_t::acquire_address)(attribute_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
Acquire a virtual IP address to assign to a peer.
Parameters
pools list of pool names (char*) to acquire from
ike_sa associated IKE_SA to assign address over
requested IP in configuration request
Returns
allocated address, NULL to serve none
Definition at line 43 of file attribute_provider.h.
Referenced by METHOD().
enumerator_t*(* attribute_provider_t::create_attribute_enumerator)(attribute_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
Create an enumerator over attributes to hand out to a peer.
Parameters
pool list of pools names (char*) to query attributes from
ike_sa IKE_SA to request attributes for
vip list of virtual IPs (host_t*) to assign to peer
Returns
enumerator (configuration_attribute_type_t, chunk_t)
Definition at line 66 of file attribute_provider.h.
Referenced by responder_enum_create().
bool(* attribute_provider_t::release_address)(attribute_provider_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
Release a previously acquired address.
Parameters
pools list of pool names (char*) to release to
address address to release
ike_sa IKE_SA to release address for
Returns
TRUE if the address has been released by the provider
Definition at line 54 of file attribute_provider.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
attribute_provider.h