strongSwan: force_cookie.c File Reference
force_cookie.c File Reference
#include "hook.h"
#include <encoding/payloads/unknown_payload.h>
Classes
struct private_force_cookie_t
Typedefs
typedef struct
private_force_cookie_t private_force_cookie_t
Functions
METHOD (listener_t, message, bool, private_force_cookie_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (hook_t, destroy, void, private_force_cookie_t *this)
hook_t * force_cookie_hook_create (char *name)
Typedef Documentation
typedef struct private_force_cookie_t private_force_cookie_t
Definition at line 20 of file force_cookie.c.
Function Documentation
hook_t* force_cookie_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 103 of file force_cookie.c.
References INIT.
 {
     private_force_cookie_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .message = _message,
             },
             .destroy = _destroy,
         },
     );
     return &this->hook;
 }
METHOD (listener_t , message , bool , private_force_cookie_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 33 of file force_cookie.c.
References message_t::add_notify, charon, chunk_from_thing, host_t::clone, COOKIE, message_t::create_payload_enumerator, data, DBG1, DBG_CFG, enumerator_t::destroy, message_t::destroy, dst, enumerator_t::enumerate, EXCHANGE_TYPE_UNDEFINED, FALSE, message_t::generate, message_t::get_destination, message_t::get_exchange_type, message_t::get_ike_sa_id, notify_payload_t::get_notification_data, notify_payload_t::get_notify_type, message_t::get_request, message_t::get_source, payload_t::get_type, IKE_SA_INIT, IKEV2_MAJOR_VERSION, IKEV2_MINOR_VERSION, message_create(), notify(), PLV2_NOTIFY, response, sender_t::send, daemon_t::sender, message_t::set_destination, message_t::set_exchange_type, message_t::set_ike_sa_id, message_t::set_message_id, message_t::set_request, message_t::set_source, src, SUCCESS, ike_sa_id_t::switch_initiator, and TRUE.
 {
     if (incoming && plain && message->get_request(message) &&
         message->get_exchange_type(message) == IKE_SA_INIT)
     {
         enumerator_t *enumerator;
         bool has_cookie = FALSE;
         payload_t *payload;
         enumerator = message->create_payload_enumerator(message);
         while (enumerator->enumerate(enumerator, &payload))
         {
             if (payload->get_type(payload) == PLV2_NOTIFY)
             {
                 notify_payload_t *notify = (notify_payload_t*)payload;
                 chunk_t data;
                 if (notify->get_notify_type(notify) == COOKIE)
                 {
                     data = notify->get_notification_data(notify);
                     DBG1(DBG_CFG, "received COOKIE: %#B", &data);
                     has_cookie = TRUE;
                     break;
                 }
             }
         }
         enumerator->destroy(enumerator);
         if (!has_cookie)
         {
             message_t *response;
             host_t *src, *dst;
             packet_t *packet;
             ike_sa_id_t *ike_sa_id;
             chunk_t data = chunk_from_thing("COOKIE test data");
             DBG1(DBG_CFG, "sending COOKIE: %#B", &data);
             response = message_create(IKEV2_MAJOR_VERSION, IKEV2_MINOR_VERSION);
             dst = message->get_source(message);
             src = message->get_destination(message);
             response->set_source(response, src->clone(src));
             response->set_destination(response, dst->clone(dst));
             response->set_exchange_type(response, IKE_SA_INIT);
             response->set_request(response, FALSE);
             response->set_message_id(response, 0);
             ike_sa_id = message->get_ike_sa_id(message);
             ike_sa_id->switch_initiator(ike_sa_id);
             response->set_ike_sa_id(response, ike_sa_id);
             response->add_notify(response, FALSE, COOKIE, data);
             if (response->generate(response, NULL, &packet) == SUCCESS)
             {
                 charon->sender->send(charon->sender, packet);
                 response->destroy(response);
             }
             message->set_exchange_type(message, EXCHANGE_TYPE_UNDEFINED);
         }
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_force_cookie_t * this)
Definition at line 94 of file force_cookie.c.
References free().
 {
     free(this);
 }