strongSwan: psk_authenticator.c File Reference
psk_authenticator.c File Reference
#include "psk_authenticator.h"
#include <daemon.h>
#include <encoding/payloads/auth_payload.h>
#include <sa/ikev2/keymat_v2.h>
Classes
struct private_psk_authenticator_t
Typedefs
typedef struct
private_psk_authenticator_t private_psk_authenticator_t
Functions
METHOD (authenticator_t, build, status_t, private_psk_authenticator_t *this, message_t *message)
METHOD (authenticator_t, process, status_t, private_psk_authenticator_t *this, message_t *message)
METHOD (authenticator_t, destroy, void, private_psk_authenticator_t *this)
psk_authenticator_t * psk_authenticator_create_builder (ike_sa_t *ike_sa, chunk_t received_nonce, chunk_t sent_init, char reserved[3])
psk_authenticator_t * psk_authenticator_create_verifier (ike_sa_t *ike_sa, chunk_t sent_nonce, chunk_t received_init, char reserved[3])
Typedef Documentation
typedef struct private_psk_authenticator_t private_psk_authenticator_t
Definition at line 23 of file psk_authenticator.c.
Function Documentation
METHOD (authenticator_t , build , status_t , private_psk_authenticator_t * this, message_t * message)
Definition at line 56 of file psk_authenticator.c.
References message_t::add_payload, auth_method_names, auth_payload_create(), AUTH_PSK, chunk_free(), library_t::credmgr, DBG1, DBG2, DBG_IKE, shared_key_t::destroy, FAILED, FALSE, shared_key_t::get_key, keymat_v2_t::get_psk_sig, credential_manager_t::get_shared, key, lib, NOT_FOUND, reserved, auth_payload_t::set_auth_method, auth_payload_t::set_data, SHARED_IKE, and SUCCESS.
 {
     identification_t *my_id, *other_id;
     auth_payload_t *auth_payload;
     shared_key_t *key;
     chunk_t auth_data;
     keymat_v2_t *keymat;
     keymat = (keymat_v2_t*)this->ike_sa->get_keymat(this->ike_sa);
     my_id = this->ike_sa->get_my_id(this->ike_sa);
     other_id = this->ike_sa->get_other_id(this->ike_sa);
     DBG1(DBG_IKE, "authentication of '%Y' (myself) with %N",
          my_id, auth_method_names, AUTH_PSK);
     key = lib->credmgr->get_shared(lib->credmgr, SHARED_IKE, my_id, other_id);
     if (key == NULL)
     {
         DBG1(DBG_IKE, "no shared key found for '%Y' - '%Y'", my_id, other_id);
         return NOT_FOUND;
     }
     if (!keymat->get_psk_sig(keymat, FALSE, this->ike_sa_init, this->nonce,
                         key->get_key(key), my_id, this->reserved, &auth_data))
     {
         key->destroy(key);
         return FAILED;
     }
     key->destroy(key);
     DBG2(DBG_IKE, "successfully created shared key MAC");
     auth_payload = auth_payload_create();
     auth_payload->set_auth_method(auth_payload, AUTH_PSK);
     auth_payload->set_data(auth_payload, auth_data);
     chunk_free(&auth_data);
     message->add_payload(message, (payload_t*)auth_payload);
     return SUCCESS;
 }
METHOD (authenticator_t , process , status_t , private_psk_authenticator_t * this, message_t * message)
Definition at line 93 of file psk_authenticator.c.
References auth_cfg_t::add, AUTH_CLASS_PSK, auth_method_names, AUTH_PSK, AUTH_RULE_AUTH_CLASS, chunk_equals_const(), chunk_free(), credential_manager_t::create_shared_enumerator, library_t::credmgr, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FAILED, FALSE, auth_payload_t::get_data, shared_key_t::get_key, message_t::get_payload, keymat_v2_t::get_psk_sig, key, chunk_t::len, lib, NOT_FOUND, PLV2_AUTH, reserved, SHARED_IKE, SUCCESS, and TRUE.
 {
     chunk_t auth_data, recv_auth_data;
     identification_t *my_id, *other_id;
     auth_payload_t *auth_payload;
     auth_cfg_t *auth;
     shared_key_t *key;
     enumerator_t *enumerator;
     bool authenticated = FALSE;
     int keys_found = 0;
     keymat_v2_t *keymat;
     auth_payload = (auth_payload_t*)message->get_payload(message, PLV2_AUTH);
     if (!auth_payload)
     {
         return FAILED;
     }
     keymat = (keymat_v2_t*)this->ike_sa->get_keymat(this->ike_sa);
     recv_auth_data = auth_payload->get_data(auth_payload);
     my_id = this->ike_sa->get_my_id(this->ike_sa);
     other_id = this->ike_sa->get_other_id(this->ike_sa);
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                                 SHARED_IKE, my_id, other_id);
     while (!authenticated && enumerator->enumerate(enumerator, &key, NULL, NULL))
     {
         keys_found++;
         if (!keymat->get_psk_sig(keymat, TRUE, this->ike_sa_init, this->nonce,
                     key->get_key(key), other_id, this->reserved, &auth_data))
         {
             continue;
         }
         if (auth_data.len && chunk_equals_const(auth_data, recv_auth_data))
         {
             DBG1(DBG_IKE, "authentication of '%Y' with %N successful",
                  other_id, auth_method_names, AUTH_PSK);
             authenticated = TRUE;
         }
         chunk_free(&auth_data);
     }
     enumerator->destroy(enumerator);
     if (!authenticated)
     {
         if (keys_found == 0)
         {
             DBG1(DBG_IKE, "no shared key found for '%Y' - '%Y'", my_id, other_id);
             return NOT_FOUND;
         }
         DBG1(DBG_IKE, "tried %d shared key%s for '%Y' - '%Y', but MAC mismatched",
              keys_found, keys_found == 1 ? "" : "s", my_id, other_id);
         return FAILED;
     }
     auth = this->ike_sa->get_auth_cfg(this->ike_sa, FALSE);
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PSK);
     return SUCCESS;
 }
METHOD (authenticator_t , destroy , void , private_psk_authenticator_t * this)
Definition at line 153 of file psk_authenticator.c.
References free().
 {
     free(this);
 }