strongSwan: stream_manager.c File Reference
stream_manager.c File Reference
#include "stream_manager.h"
#include "stream_tcp.h"
#include "stream_service_tcp.h"
#include "stream_unix.h"
#include "stream_service_unix.h"
#include <threading/rwlock.h>
Classes
struct private_stream_manager_t
struct stream_entry_t
struct service_entry_t
Typedefs
typedef struct
private_stream_manager_t private_stream_manager_t
Functions
METHOD (stream_manager_t, connect_, stream_t *, private_stream_manager_t *this, char *uri)
METHOD (stream_manager_t, create_service, stream_service_t *, private_stream_manager_t *this, char *uri, int backlog)
METHOD (stream_manager_t, add_stream, void, private_stream_manager_t *this, char *prefix, stream_constructor_t create)
METHOD (stream_manager_t, remove_stream, void, private_stream_manager_t *this, stream_constructor_t create)
METHOD (stream_manager_t, add_service, void, private_stream_manager_t *this, char *prefix, stream_service_constructor_t create)
METHOD (stream_manager_t, remove_service, void, private_stream_manager_t *this, stream_service_constructor_t create)
METHOD (stream_manager_t, destroy, void, private_stream_manager_t *this)
stream_manager_t * stream_manager_create ()
Typedef Documentation
typedef struct private_stream_manager_t private_stream_manager_t
Definition at line 27 of file stream_manager.c.
Function Documentation
METHOD (stream_manager_t , connect_ , stream_t * , private_stream_manager_t * this, char * uri)
Definition at line 75 of file stream_manager.c.
References stream_entry_t::create, enumerator_t::destroy, enumerator_t::enumerate, lock, stream_entry_t::prefix, strpfx(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     stream_entry_t *entry;
     stream_t *stream = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->streams->create_enumerator(this->streams);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (strpfx(uri, entry->prefix))
         {
             stream = entry->create(uri);
             if (stream)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return stream;
 }
METHOD (stream_manager_t , create_service , stream_service_t * , private_stream_manager_t * this, char * uri, int backlog)
Definition at line 101 of file stream_manager.c.
References service_entry_t::create, enumerator_t::destroy, enumerator_t::enumerate, lock, service_entry_t::prefix, services, strpfx(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     service_entry_t *entry;
     stream_service_t *service = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->services->create_enumerator(this->services);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (strpfx(uri, entry->prefix))
         {
             service = entry->create(uri, backlog);
             if (service)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return service;
 }
METHOD (stream_manager_t , add_stream , void , private_stream_manager_t * this, char * prefix, stream_constructor_t create)
Definition at line 127 of file stream_manager.c.
References INIT, lock, strdup, and spinlock_t::unlock.
 {
     stream_entry_t *entry;
     INIT(entry,
         .prefix = strdup(prefix),
         .create = create,
     );
     this->lock->write_lock(this->lock);
     this->streams->insert_last(this->streams, entry);
     this->lock->unlock(this->lock);
 }
METHOD (stream_manager_t , remove_stream , void , private_stream_manager_t * this, stream_constructor_t create)
Definition at line 142 of file stream_manager.c.
References stream_entry_t::create, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, stream_entry_t::prefix, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     stream_entry_t *entry;
     this->lock->write_lock(this->lock);
     enumerator = this->streams->create_enumerator(this->streams);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create == create)
         {
             this->streams->remove_at(this->streams, enumerator);
             free(entry->prefix);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (stream_manager_t , add_service , void , private_stream_manager_t * this, char * prefix, stream_service_constructor_t create)
Definition at line 163 of file stream_manager.c.
References INIT, lock, services, strdup, and spinlock_t::unlock.
 {
     service_entry_t *entry;
     INIT(entry,
         .prefix = strdup(prefix),
         .create = create,
     );
     this->lock->write_lock(this->lock);
     this->services->insert_last(this->services, entry);
     this->lock->unlock(this->lock);
 }
METHOD (stream_manager_t , remove_service , void , private_stream_manager_t * this, stream_service_constructor_t create)
Definition at line 179 of file stream_manager.c.
References service_entry_t::create, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, service_entry_t::prefix, services, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     service_entry_t *entry;
     this->lock->write_lock(this->lock);
     enumerator = this->services->create_enumerator(this->services);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->create == create)
         {
             this->services->remove_at(this->services, enumerator);
             free(entry->prefix);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (stream_manager_t , destroy , void , private_stream_manager_t * this)
Definition at line 200 of file stream_manager.c.
References spinlock_t::destroy, free(), lock, services, stream_create_tcp(), stream_create_unix(), stream_service_create_tcp(), and stream_service_create_unix().
 {
     remove_stream(this, stream_create_tcp);
     remove_service(this, stream_service_create_tcp);
 #ifndef WIN32
     remove_stream(this, stream_create_unix);
     remove_service(this, stream_service_create_unix);
 #endif
     this->streams->destroy(this->streams);
     this->services->destroy(this->services);
     this->lock->destroy(this->lock);
     free(this);
 }