strongSwan: tnc_imv_recommendations.c File Reference
tnc_imv_recommendations.c File Reference
#include <tncifimv.h>
#include <tncif_names.h>
#include <tncif_policy.h>
#include <tnc/tnc.h>
#include <tnc/imv/imv.h>
#include <tnc/imv/imv_manager.h>
#include <tnc/imv/imv_recommendations.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
Classes
struct recommendation_entry_t
struct private_tnc_imv_recommendations_t
Typedefs
typedef struct
private_tnc_imv_recommendations_t private_tnc_imv_recommendations_t
typedef struct
recommendation_entry_t recommendation_entry_t
Functions
METHOD (recommendations_t, provide_recommendation, TNC_Result, private_tnc_imv_recommendations_t *this, TNC_IMVID id, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (recommendations_t, have_recommendation, bool, private_tnc_imv_recommendations_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
METHOD (recommendations_t, clear_recommendation, void, private_tnc_imv_recommendations_t *this)
METHOD (recommendations_t, get_preferred_language, chunk_t, private_tnc_imv_recommendations_t *this)
METHOD (recommendations_t, set_preferred_language, void, private_tnc_imv_recommendations_t *this, chunk_t pref_lang)
METHOD (recommendations_t, set_reason_string, TNC_Result, private_tnc_imv_recommendations_t *this, TNC_IMVID id, chunk_t reason)
METHOD (recommendations_t, set_reason_language, TNC_Result, private_tnc_imv_recommendations_t *this, TNC_IMVID id, chunk_t reason_lang)
static bool reason_filter (void *null, recommendation_entry_t **entry, TNC_IMVID *id, void *i2, chunk_t *reason, void *i3, chunk_t *reason_language)
METHOD (recommendations_t, create_reason_enumerator, enumerator_t *, private_tnc_imv_recommendations_t *this)
METHOD (recommendations_t, destroy, void, private_tnc_imv_recommendations_t *this)
recommendations_t * tnc_imv_recommendations_create (linked_list_t *imv_list)
Typedef Documentation
typedef struct private_tnc_imv_recommendations_t private_tnc_imv_recommendations_t
Definition at line 28 of file tnc_imv_recommendations.c.
typedef struct recommendation_entry_t recommendation_entry_t
Definition at line 29 of file tnc_imv_recommendations.c.
Function Documentation
METHOD (recommendations_t , provide_recommendation , TNC_Result , private_tnc_imv_recommendations_t * this, TNC_IMVID id, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 88 of file tnc_imv_recommendations.c.
References DBG2, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, recommendation_entry_t::eval, FALSE, found, recommendation_entry_t::have_recommendation, recommendation_entry_t::id, recommendation_entry_t::rec, TNC_IMV_Action_Recommendation_names, TNC_IMV_Evaluation_Result_names, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, and TRUE.
 {
     enumerator_t *enumerator;
     recommendation_entry_t *entry;
     bool found = FALSE;
     DBG2(DBG_TNC, "IMV %u provides recommendation '%N' and evaluation '%N'", id,
          TNC_IMV_Action_Recommendation_names, rec,
          TNC_IMV_Evaluation_Result_names, eval);
     enumerator = this->recs->create_enumerator(this->recs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->id == id)
         {
             found = TRUE;
             entry->have_recommendation = TRUE;
             entry->rec = rec;
             entry->eval = eval;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found ? TNC_RESULT_SUCCESS : TNC_RESULT_FATAL;
 }
METHOD (recommendations_t , have_recommendation , bool , private_tnc_imv_recommendations_t * this, TNC_IMV_Action_Recommendation * rec, TNC_IMV_Evaluation_Result * eval)
Definition at line 117 of file tnc_imv_recommendations.c.
References DBG1, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, recommendation_entry_t::eval, FALSE, imv_manager_t::get_recommendation_policy, recommendation_entry_t::have_recommendation, tnc_t::imvs, recommendation_entry_t::rec, RECOMMENDATION_POLICY_ALL, RECOMMENDATION_POLICY_ANY, RECOMMENDATION_POLICY_DEFAULT, tnc, TNC_IMV_ACTION_RECOMMENDATION_ALLOW, TNC_IMV_ACTION_RECOMMENDATION_ISOLATE, TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, TNC_IMV_EVALUATION_RESULT_COMPLIANT, TNC_IMV_EVALUATION_RESULT_DONT_KNOW, TNC_IMV_EVALUATION_RESULT_ERROR, TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MAJOR, TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MINOR, tncif_policy_update_evaluation(), tncif_policy_update_recommendation(), and TRUE.
 {
     enumerator_t *enumerator;
     recommendation_entry_t *entry;
     recommendation_policy_t policy;
     TNC_IMV_Action_Recommendation final_rec;
     TNC_IMV_Evaluation_Result final_eval;
     bool first = TRUE, incomplete = FALSE;
     final_rec  = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION;
     final_eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW;
     if (rec && eval)
     {
         *rec  = final_rec;
         *eval = final_eval;
     }
     if (this->recs->get_count(this->recs) == 0)
     {
         DBG1(DBG_TNC, "there are no IMVs to make a recommendation");
         return TRUE;
     }
     policy = tnc->imvs->get_recommendation_policy(tnc->imvs);
     enumerator = this->recs->create_enumerator(this->recs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (!entry->have_recommendation)
         {
             incomplete = TRUE;
             break;
         }
         if (first)
         {
             final_rec = entry->rec;
             final_eval = entry->eval;
             first = FALSE;
             continue;
         }
         switch (policy)
         {
             case RECOMMENDATION_POLICY_DEFAULT:
                 final_rec = tncif_policy_update_recommendation(final_rec,
                                                                entry->rec);
                 final_eval = tncif_policy_update_evaluation(final_eval,
                                                             entry->eval);
                 break;
             case RECOMMENDATION_POLICY_ALL:
                 if (entry->rec != final_rec)
                 {
                     final_rec = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION;
                 }
                 if (entry->eval != final_eval)
                 {
                     final_eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW;
                 }
                 break;
             case RECOMMENDATION_POLICY_ANY:
                 switch (entry->rec)
                 {
                     case TNC_IMV_ACTION_RECOMMENDATION_ALLOW:
                         final_rec = entry->rec;
                         break;
                     case TNC_IMV_ACTION_RECOMMENDATION_ISOLATE:
                         if (final_rec != TNC_IMV_ACTION_RECOMMENDATION_ALLOW)
{
                             final_rec = entry->rec;
                         };
                         break;
                     case TNC_IMV_ACTION_RECOMMENDATION_NO_ACCESS:
                         if (final_rec == TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION)
{
                             final_rec = entry->rec;
                         };
                         break;
                     case TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION:
                         break;
                 }
                 switch (entry->eval)
                 {
                     case TNC_IMV_EVALUATION_RESULT_COMPLIANT:
                         final_eval = entry->eval;
                         break;
                     case TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MINOR:
                         if (final_eval != TNC_IMV_EVALUATION_RESULT_COMPLIANT)
{
                             final_eval = entry->eval;
                         }
                         break;
                     case TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MAJOR:
                         if (final_eval != TNC_IMV_EVALUATION_RESULT_COMPLIANT &&
                             final_eval != TNC_IMV_EVALUATION_RESULT_NONCOMPLIANT_MINOR)
{
                             final_eval = entry->eval;
                         }
                         break;
                     case TNC_IMV_EVALUATION_RESULT_ERROR:
                         if (final_eval == TNC_IMV_EVALUATION_RESULT_DONT_KNOW)
{
                             final_eval = entry->eval;
                         }
                         break;
                     case TNC_IMV_EVALUATION_RESULT_DONT_KNOW:
                         break;
                 }
         }
     }
     enumerator->destroy(enumerator);
     if (incomplete)
     {
         return FALSE;
     }
     if (rec && eval)
     {
         *rec  = final_rec;
         *eval = final_eval;
     }
     return TRUE;
 }
METHOD (recommendations_t , clear_recommendation , void , private_tnc_imv_recommendations_t * this)
Definition at line 242 of file tnc_imv_recommendations.c.
References chunk_clear(), enumerator_t::destroy, enumerator_t::enumerate, recommendation_entry_t::eval, FALSE, recommendation_entry_t::have_recommendation, recommendation_entry_t::reason, recommendation_entry_t::reason_language, recommendation_entry_t::rec, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TNC_IMV_EVALUATION_RESULT_DONT_KNOW.
 {
     enumerator_t *enumerator;
     recommendation_entry_t *entry;
     enumerator = this->recs->create_enumerator(this->recs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         entry->have_recommendation = FALSE;
         entry->rec = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION;
         entry->eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW;
         chunk_clear(&entry->reason);
         chunk_clear(&entry->reason_language);
     }
     enumerator->destroy(enumerator);
 }
METHOD (recommendations_t , get_preferred_language , chunk_t , private_tnc_imv_recommendations_t * this)
Definition at line 260 of file tnc_imv_recommendations.c.
 {
     return this->preferred_language;
 }
METHOD (recommendations_t , set_preferred_language , void , private_tnc_imv_recommendations_t * this, chunk_t pref_lang)
Definition at line 266 of file tnc_imv_recommendations.c.
References chunk_clone, and free().
 {
     free(this->preferred_language.ptr);
     this->preferred_language = chunk_clone(pref_lang);
 }
METHOD (recommendations_t , set_reason_string , TNC_Result , private_tnc_imv_recommendations_t * this, TNC_IMVID id, chunk_t reason)
Definition at line 273 of file tnc_imv_recommendations.c.
References chunk_clone, DBG2, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, free(), recommendation_entry_t::id, chunk_t::len, chunk_t::ptr, recommendation_entry_t::reason, TNC_RESULT_INVALID_PARAMETER, TNC_RESULT_SUCCESS, and TRUE.
 {
     enumerator_t *enumerator;
     recommendation_entry_t *entry;
     bool found = FALSE;
     DBG2(DBG_TNC, "IMV %u is setting reason string to '%.*s'",
          id, (int)reason.len, reason.ptr);
     enumerator = this->recs->create_enumerator(this->recs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->id == id)
         {
             found = TRUE;
             free(entry->reason.ptr);
             entry->reason = chunk_clone(reason);
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found ? TNC_RESULT_SUCCESS : TNC_RESULT_INVALID_PARAMETER;
 }
METHOD (recommendations_t , set_reason_language , TNC_Result , private_tnc_imv_recommendations_t * this, TNC_IMVID id, chunk_t reason_lang)
Definition at line 298 of file tnc_imv_recommendations.c.
References chunk_clone, DBG2, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, free(), recommendation_entry_t::id, chunk_t::len, chunk_t::ptr, recommendation_entry_t::reason_language, TNC_RESULT_INVALID_PARAMETER, TNC_RESULT_SUCCESS, and TRUE.
 {
     enumerator_t *enumerator;
     recommendation_entry_t *entry;
     bool found = FALSE;
     DBG2(DBG_TNC, "IMV %u is setting reason language to '%.*s'",
          id, (int)reason_lang.len, reason_lang.ptr);
     enumerator = this->recs->create_enumerator(this->recs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->id == id)
         {
             found = TRUE;
             free(entry->reason_language.ptr);
             entry->reason_language = chunk_clone(reason_lang);
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found ? TNC_RESULT_SUCCESS : TNC_RESULT_INVALID_PARAMETER;
 }
METHOD (recommendations_t , create_reason_enumerator , enumerator_t * , private_tnc_imv_recommendations_t * this)
Definition at line 343 of file tnc_imv_recommendations.c.
References enumerator_create_filter(), and reason_filter().
 {
     return enumerator_create_filter(this->recs->create_enumerator(this->recs),
                     (void*)reason_filter, NULL, NULL);
 }
METHOD (recommendations_t , destroy , void , private_tnc_imv_recommendations_t * this)
Definition at line 350 of file tnc_imv_recommendations.c.
References free(), chunk_t::ptr, recommendation_entry_t::reason, recommendation_entry_t::reason_language, and SUCCESS.
 {
     recommendation_entry_t *entry;
     while (this->recs->remove_last(this->recs, (void**)&entry) == SUCCESS)
     {
         free(entry->reason.ptr);
         free(entry->reason_language.ptr);
         free(entry);
     }
     this->recs->destroy(this->recs);
     free(this->preferred_language.ptr);
     free(this);
 }
static bool reason_filter (void * null, recommendation_entry_t ** entry, TNC_IMVID * id, void * i2, chunk_t * reason, void * i3, chunk_t * reason_language) static
Enumerate reason and reason_language, not recommendation entries
Definition at line 326 of file tnc_imv_recommendations.c.
References FALSE, and TRUE.
Referenced by METHOD().
 {
     if ((*entry)->reason.len)
     {
         *id = (*entry)->id;
         *reason = (*entry)->reason;
         *reason_language = (*entry)->reason_language;
         return TRUE;
     }
     else
     {
         return FALSE;
     }
 }
recommendations_t* tnc_imv_recommendations_create (linked_list_t * imv_list)
Described in header.
Definition at line 369 of file tnc_imv_recommendations.c.
References chunk_empty, linked_list_t::create_enumerator, recommendation_entry_t::eval, FALSE, imv_t::get_id, recommendation_entry_t::have_recommendation, recommendation_entry_t::id, INIT, linked_list_create(), malloc_thing, recommendation_entry_t::reason, recommendation_entry_t::reason_language, recommendation_entry_t::rec, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TNC_IMV_EVALUATION_RESULT_DONT_KNOW.
Referenced by METHOD().
 {
     private_tnc_imv_recommendations_t *this;
     recommendation_entry_t *entry;
     enumerator_t *enumerator;
     imv_t *imv;
     INIT(this,
         .public = {
             .provide_recommendation = _provide_recommendation,
             .have_recommendation = _have_recommendation,
             .clear_recommendation = _clear_recommendation,
             .get_preferred_language = _get_preferred_language,
             .set_preferred_language = _set_preferred_language,
             .set_reason_string = _set_reason_string,
             .set_reason_language = _set_reason_language,
             .create_reason_enumerator = _create_reason_enumerator,
             .destroy = _destroy,
         },
         .recs = linked_list_create(),
     );
     enumerator = imv_list->create_enumerator(imv_list);
     while (enumerator->enumerate(enumerator, &imv))
     {
         entry = malloc_thing(recommendation_entry_t);
         entry->id = imv->get_id(imv);
         entry->have_recommendation = FALSE;
         entry->rec = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION;
         entry->eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW;
         entry->reason = chunk_empty;
         entry->reason_language = chunk_empty;
         this->recs->insert_last(this->recs, entry);
     }
     enumerator->destroy(enumerator);
     return &this->public;
 }