strongSwan: hash_payload
hash_payload
payloads
Classes
struct hash_payload_t
Typedefs
typedef struct hash_payload_t hash_payload_t
Functions
hash_payload_t * hash_payload_create (payload_type_t type)
Detailed Description
Typedef Documentation
typedef struct hash_payload_t hash_payload_t
Definition at line 24 of file hash_payload.h.
Function Documentation
hash_payload_t* hash_payload_create (payload_type_t type)
Creates an empty hash_payload_t object.
Parameters
type either PLV1_HASH or PLV1_NAT_D
Returns
hash_payload_t object
Definition at line 152 of file hash_payload.c.
References INIT, PL_NONE, and type.
Referenced by build_natd_payload(), generate_message(), METHOD(), and payload_create().
 {
     private_hash_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .set_hash = _set_hash,
             .get_hash = _get_hash,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
         .type = type,
     );
     return &this->public;
 }