strongSwan: plugin_loader.c File Reference
plugin_loader.c File Reference
#include "plugin_loader.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <limits.h>
#include <stdio.h>
#include <utils/debug.h>
#include <library.h>
#include <collections/hashtable.h>
#include <collections/array.h>
#include <collections/linked_list.h>
#include <plugins/plugin.h>
#include <utils/integrity_checker.h>
Classes
struct private_plugin_loader_t
struct registered_feature_t
struct provided_feature_t
struct plugin_entry_t
struct static_features_t
struct plugin_priority_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_plugin_loader_t private_plugin_loader_t
typedef struct registered_feature_t registered_feature_t
typedef struct provided_feature_t provided_feature_t
typedef struct plugin_entry_t plugin_entry_t
Functions
static bool registered_feature_hash (registered_feature_t *this)
static bool registered_feature_equals (registered_feature_t *a, registered_feature_t *b)
static void plugin_entry_destroy (plugin_entry_t *entry)
METHOD (plugin_t, get_static_name, char *, static_features_t *this)
METHOD (plugin_t, get_static_features, int, static_features_t *this, plugin_feature_t *features[])
METHOD (plugin_t, static_reload, bool, static_features_t *this)
METHOD (plugin_t, static_destroy, void, static_features_t *this)
static plugin_t * static_features_create (const char *name, plugin_feature_t features[], int count, bool(*reload)(void *), void *reload_data)
static status_t create_plugin (private_plugin_loader_t *this, void *handle, char *name, bool integrity, bool critical, plugin_entry_t **entry)
static plugin_entry_t * load_plugin (private_plugin_loader_t *this, char *name, char *file, bool critical)
static bool feature_filter (void *null, provided_feature_t **provided, plugin_feature_t **feature)
static bool plugin_filter (void *null, plugin_entry_t **entry, plugin_t **plugin, void *in, linked_list_t **list)
METHOD (plugin_loader_t, create_plugin_enumerator, enumerator_t *, private_plugin_loader_t *this)
METHOD (plugin_loader_t, has_feature, bool, private_plugin_loader_t *this, plugin_feature_t feature)
static char * loaded_plugins_list (private_plugin_loader_t *this)
static bool plugin_loaded (private_plugin_loader_t *this, char *name)
static void load_provided (private_plugin_loader_t *this, provided_feature_t *provided, int level)
static bool is_feature_loaded (provided_feature_t *item)
static bool is_feature_loadable (provided_feature_t *item)
static bool loaded_feature_matches (registered_feature_t *a, registered_feature_t *b)
static bool loadable_feature_equals (registered_feature_t *a, registered_feature_t *b)
static bool loadable_feature_matches (registered_feature_t *a, registered_feature_t *b)
static bool find_compatible_feature (private_plugin_loader_t *this, plugin_feature_t *dependency)
static void load_registered (private_plugin_loader_t *this, registered_feature_t *registered, int level)
static bool load_dependencies (private_plugin_loader_t *this, provided_feature_t *provided, int level)
static void load_feature (private_plugin_loader_t *this, provided_feature_t *provided, int level)
static void load_features (private_plugin_loader_t *this)
static void register_features (private_plugin_loader_t *this, plugin_entry_t *entry)
static void unregister_feature (private_plugin_loader_t *this, provided_feature_t *provided)
static void unregister_features (private_plugin_loader_t *this, plugin_entry_t *entry)
static void purge_plugins (private_plugin_loader_t *this)
METHOD (plugin_loader_t, add_static_features, void, private_plugin_loader_t *this, const char *name, plugin_feature_t features[], int count, bool critical, bool(*reload)(void *), void *reload_data)
static bool find_plugin (char *path, char *name, char *buf, char **file)
static void plugin_priority_free (const plugin_priority_t *this, int idx, void *user)
static int plugin_priority_cmp_name (const plugin_priority_t *a, const plugin_priority_t *b)
static int plugin_priority_cmp (const plugin_priority_t *a, const plugin_priority_t *b, void *user)
static char * modular_pluginlist (char *list)
METHOD (plugin_loader_t, load_plugins, bool, private_plugin_loader_t *this, char *list)
static void unload_features (private_plugin_loader_t *this)
METHOD (plugin_loader_t, unload, void, private_plugin_loader_t *this)
METHOD (plugin_loader_t, add_path, void, private_plugin_loader_t *this, char *path)
static u_int reload_by_name (private_plugin_loader_t *this, char *name)
METHOD (plugin_loader_t, reload, u_int, private_plugin_loader_t *this, char *list)
METHOD (plugin_loader_t, loaded_plugins, char *, private_plugin_loader_t *this)
METHOD (plugin_loader_t, status, void, private_plugin_loader_t *this, level_t level)
METHOD (plugin_loader_t, destroy, void, private_plugin_loader_t *this)
plugin_loader_t * plugin_loader_create ()
void plugin_loader_add_plugindirs (char *basedir, char *plugins)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file plugin_loader.c.
Typedef Documentation
typedef struct plugin_entry_t plugin_entry_t
Definition at line 41 of file plugin_loader.c.
typedef struct private_plugin_loader_t private_plugin_loader_t
Definition at line 38 of file plugin_loader.c.
typedef struct provided_feature_t provided_feature_t
Definition at line 40 of file plugin_loader.c.
typedef struct registered_feature_t registered_feature_t
Definition at line 39 of file plugin_loader.c.
Function Documentation
static status_t create_plugin (private_plugin_loader_t * this, void * handle, char * name, bool integrity, bool critical, plugin_entry_t ** entry) static
create a plugin returns: NOT_FOUND, if the constructor was not found FAILED, if the plugin could not be constructed
Definition at line 306 of file plugin_loader.c.
References integrity_checker_t::check_segment, create, DBG1, DBG2, DBG_LIB, dlsym(), FAILED, INIT, library_t::integrity, lib, linked_list_create(), NOT_FOUND, plugin, snprintf, SUCCESS, and translate().
Referenced by load_plugin().
 {
     char create[128];
     plugin_t *plugin;
     plugin_constructor_t constructor;
     if (snprintf(create, sizeof(create), "%s_plugin_create",
                  name) >= sizeof(create))
     {
         return FAILED;
     }
     translate(create, "-", "_");
     constructor = dlsym(handle, create);
     if (constructor == NULL)
     {
         return NOT_FOUND;
     }
     if (integrity && lib->integrity)
     {
         if (!lib->integrity->check_segment(lib->integrity, name, constructor))
         {
             DBG1(DBG_LIB, "plugin '%s': failed segment integrity test", name);
             return FAILED;
         }
         DBG1(DBG_LIB, "plugin '%s': passed file and segment integrity tests",
              name);
     }
     plugin = constructor();
     if (plugin == NULL)
     {
         DBG1(DBG_LIB, "plugin '%s': failed to load - %s returned NULL", name,
              create);
         return FAILED;
     }
     INIT(*entry,
         .plugin = plugin,
         .critical = critical,
         .features = linked_list_create(),
     );
     DBG2(DBG_LIB, "plugin '%s': loaded successfully", name);
     return SUCCESS;
 }
static bool feature_filter (void * null, provided_feature_t ** provided, plugin_feature_t ** feature) static
Convert enumerated provided_feature_t to plugin_feature_t
Definition at line 415 of file plugin_loader.c.
Referenced by plugin_filter().
 {
     *feature = (*provided)->feature;
     return (*provided)->loaded;
 }
static bool find_compatible_feature (private_plugin_loader_t * this, plugin_feature_t * dependency) static
Returns a compatible plugin feature for the given depencency
Definition at line 600 of file plugin_loader.c.
References loaded_feature_matches(), and lookup.
Referenced by load_dependencies().
 {
     registered_feature_t *feature, lookup = {
         .feature = dependency,
     };
     feature = this->features->get_match(this->features, &lookup,
                                        (void*)loaded_feature_matches);
     return feature != NULL;
 }
static bool find_plugin (char * path, char * name, char * buf, char ** file) static
Tries to find the plugin with the given name in the given path.
Definition at line 964 of file plugin_loader.c.
References FALSE, snprintf, and TRUE.
Referenced by METHOD().
 {
     struct stat stb;
     if (path && snprintf(buf, PATH_MAX, "%s/libstrongswan-%s.so",
                          path, name) < PATH_MAX)
     {
         if (stat(buf, &stb) == 0)
         {
             *file = buf;
             return TRUE;
         }
     }
     return FALSE;
 }
static bool is_feature_loadable (provided_feature_t * item) static
Used to find a loadable feature
Definition at line 550 of file plugin_loader.c.
References provided_feature_t::failed, provided_feature_t::loaded, and provided_feature_t::loading.
Referenced by loadable_feature_equals(), and loadable_feature_matches().
 {
     return !item->loading && !item->loaded && !item->failed;
 }
static bool is_feature_loaded (provided_feature_t * item) static
Used to find a loaded feature
Definition at line 542 of file plugin_loader.c.
References provided_feature_t::loaded.
Referenced by loaded_feature_matches(), and purge_plugins().
 {
     return item->loaded;
 }
static bool load_dependencies (private_plugin_loader_t * this, provided_feature_t * provided, int level) static
Try to load dependencies of the given feature
Definition at line 633 of file plugin_loader.c.
References plugin_entry_t::critical, DBG1, DBG2, DBG3, DBG_LIB, provided_feature_t::dependencies, provided_feature_t::entry, FALSE, registered_feature_t::feature, provided_feature_t::feature, find_compatible_feature(), free(), plugin_t::get_name, plugin_feature_t::kind, load_registered(), loadable_feature_equals(), loadable_feature_matches(), lookup, name, plugin_entry_t::plugin, plugin_feature_get_string(), registered, and TRUE.
Referenced by load_feature().
 {
     registered_feature_t *registered, lookup;
     int indent = level * 2;
     int i;
     /* first entry is provided feature, followed by dependencies */
     for (i = 1; i < provided->dependencies; i++)
     {
         if (provided->feature[i].kind != FEATURE_DEPENDS &&
             provided->feature[i].kind != FEATURE_SDEPEND)
         {   /* end of dependencies */
             break;
         }
         /* we load the feature even if a compatible one is already loaded,
          * otherwise e.g. a specific database implementation loaded before
          * another might cause a plugin feature loaded in-between to fail */
         lookup.feature = &provided->feature[i];
         do
         {   /* prefer an exactly matching feature, could be omitted but
              * results in a more predictable behavior */
             registered = this->features->get_match(this->features,
                                          &lookup,
                                          (void*)loadable_feature_equals);
             if (!registered)
             {   /* try fuzzy matching */
                 registered = this->features->get_match(this->features,
                                          &lookup,
                                          (void*)loadable_feature_matches);
             }
             if (registered)
             {
                 load_registered(this, registered, level);
             }
             /* we could stop after finding one but for dependencies like
              * DB_ANY it might be needed to load all matching features */
         }
         while (registered);
         if (!find_compatible_feature(this, &provided->feature[i]))
         {
             char *name, *provide, *depend;
             bool soft = provided->feature[i].kind == FEATURE_SDEPEND;
             name = provided->entry->plugin->get_name(provided->entry->plugin);
             provide = plugin_feature_get_string(&provided->feature[0]);
             depend = plugin_feature_get_string(&provided->feature[i]);
             if (soft)
             {
                 DBG3(DBG_LIB, "%*sfeature %s in plugin '%s' has unmet soft "
                      "dependency: %s", indent, "", provide, name, depend);
             }
             else if (provided->entry->critical)
             {
                 DBG1(DBG_LIB, "feature %s in critical plugin '%s' has unmet "
                      "dependency: %s", provide, name, depend);
             }
             else
             {
                 DBG2(DBG_LIB, "feature %s in plugin '%s' has unmet dependency: "
                      "%s", provide, name, depend);
             }
             free(provide);
             free(depend);
             if (soft)
             {   /* it's ok if we can't resolve soft dependencies */
                 continue;
             }
             return FALSE;
         }
     }
     return TRUE;
 }
static void load_feature (private_plugin_loader_t * this, provided_feature_t * provided, int level) static
Load registered plugin features
Definition at line 713 of file plugin_loader.c.
References plugin_entry_t::critical, DBG1, DBG2, DBG_LIB, provided_feature_t::entry, provided_feature_t::failed, provided_feature_t::feature, free(), plugin_t::get_name, load_dependencies(), provided_feature_t::loaded, name, plugin_entry_t::plugin, plugin_feature_get_string(), plugin_feature_load(), provided_feature_t::reg, stats(), and TRUE.
Referenced by load_provided().
 {
     if (load_dependencies(this, provided, level))
     {
         char *name, *provide;
         if (plugin_feature_load(provided->entry->plugin, provided->feature,
                                 provided->reg))
         {
             provided->loaded = TRUE;
             /* insert first so we can unload the features in reverse order */
             this->loaded->insert_first(this->loaded, provided);
             return;
         }
         name = provided->entry->plugin->get_name(provided->entry->plugin);
         provide = plugin_feature_get_string(&provided->feature[0]);
         if (provided->entry->critical)
         {
             DBG1(DBG_LIB, "feature %s in critical plugin '%s' failed to load",
                  provide, name);
         }
         else
         {
             DBG2(DBG_LIB, "feature %s in plugin '%s' failed to load",
                  provide, name);
         }
         free(provide);
     }
     else
     {   /* TODO: we could check the current level and set a different flag when
          * being loaded as dependency. If there are loops there is a chance the
          * feature can be loaded later when loading the feature directly. */
         this->stats.depends++;
     }
     provided->failed = TRUE;
     this->stats.critical += provided->entry->critical ? 1 : 0;
     this->stats.failed++;
 }
static void load_features (private_plugin_loader_t * this) static
Load registered plugin features
Definition at line 790 of file plugin_loader.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, plugin_entry_t::features, load_provided(), and plugin.
Referenced by METHOD().
 {
     enumerator_t *enumerator, *inner;
     plugin_entry_t *plugin;
     provided_feature_t *provided;
     /* we do this in plugin order to allow implicit dependencies to be resolved
      * by reordering plugins */
     enumerator = this->plugins->create_enumerator(this->plugins);
     while (enumerator->enumerate(enumerator, &plugin))
     {
         inner = plugin->features->create_enumerator(plugin->features);
         while (inner->enumerate(inner, &provided))
         {
             load_provided(this, provided, 0);
         }
         inner->destroy(inner);
     }
     enumerator->destroy(enumerator);
 }
static plugin_entry_t* load_plugin (private_plugin_loader_t * this, char * name, char * file, bool critical) static
load a single plugin
Definition at line 354 of file plugin_loader.c.
References integrity_checker_t::check_file, create_plugin(), DBG1, DBG_LIB, dlclose(), dlerror(), dlopen(), FALSE, settings_t::get_bool, handle, plugin_entry_t::handle, library_t::integrity, lib, NOT_FOUND, library_t::ns, RTLD_DEFAULT, RTLD_LAZY, RTLD_NOW, library_t::settings, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     plugin_entry_t *entry;
     void *handle;
     int flag = RTLD_LAZY;
     switch (create_plugin(this, RTLD_DEFAULT, name, FALSE, critical, &entry))
     {
         case SUCCESS:
             this->plugins->insert_last(this->plugins, entry);
             return entry;
         case NOT_FOUND:
             if (file)
             {   /* try to load the plugin from a file */
                 break;
             }
             /* fall-through */
         default:
             return NULL;
     }
     if (lib->integrity)
     {
         if (!lib->integrity->check_file(lib->integrity, name, file))
         {
             DBG1(DBG_LIB, "plugin '%s': failed file integrity test of '%s'",
                  name, file);
             return NULL;
         }
     }
     if (lib->settings->get_bool(lib->settings, "%s.dlopen_use_rtld_now",
                                 lib->ns, FALSE))
     {
         flag = RTLD_NOW;
     }
 #ifdef RTLD_NODELETE
     /* If supported, do not unload the library when unloading a plugin. It
      * really doesn't matter in productive systems, but causes many (dependency)
      * library reloads during unit tests. Some libraries can't handle that, e.g.
      * GnuTLS leaks file descriptors in its library load/unload functions. */
     flag |= RTLD_NODELETE;
 #endif
     handle = dlopen(file, flag);
     if (handle == NULL)
     {
         DBG1(DBG_LIB, "plugin '%s' failed to load: %s", name, dlerror());
         return NULL;
     }
     if (create_plugin(this, handle, name, TRUE, critical, &entry) != SUCCESS)
     {
         dlclose(handle);
         return NULL;
     }
     entry->handle = handle;
     this->plugins->insert_last(this->plugins, entry);
     return entry;
 }
static void load_provided (private_plugin_loader_t * this, provided_feature_t * provided, int level) static
Forward declaration
Load a provided feature
Definition at line 758 of file plugin_loader.c.
References DBG3, DBG_LIB, provided_feature_t::entry, provided_feature_t::failed, FALSE, provided_feature_t::feature, free(), plugin_t::get_name, load_feature(), provided_feature_t::loaded, provided_feature_t::loading, name, plugin_entry_t::plugin, plugin_feature_get_string(), and TRUE.
Referenced by load_features(), and load_registered().
 {
     char *name, *provide;
     int indent = level * 2;
     if (provided->loaded || provided->failed)
     {
         return;
     }
     name = provided->entry->plugin->get_name(provided->entry->plugin);
     provide = plugin_feature_get_string(provided->feature);
     if (provided->loading)
     {   /* prevent loop */
         DBG3(DBG_LIB, "%*sloop detected while loading %s in plugin '%s'",
              indent, "", provide, name);
         free(provide);
         return;
     }
     DBG3(DBG_LIB, "%*sloading feature %s in plugin '%s'",
          indent, "", provide, name);
     free(provide);
     provided->loading = TRUE;
     load_feature(this, provided, level + 1);
     provided->loading = FALSE;
 }
static void load_registered (private_plugin_loader_t * this, registered_feature_t * registered, int level) static
Load a registered plugin feature
Definition at line 615 of file plugin_loader.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, load_provided(), and registered_feature_t::plugins.
Referenced by load_dependencies().
 {
     enumerator_t *enumerator;
     provided_feature_t *provided;
     enumerator = registered->plugins->create_enumerator(registered->plugins);
     while (enumerator->enumerate(enumerator, &provided))
     {
         load_provided(this, provided, level);
     }
     enumerator->destroy(enumerator);
 }
static bool loadable_feature_equals (registered_feature_t * a, registered_feature_t * b) static
Find a loadable module that equals the requested feature
Definition at line 572 of file plugin_loader.c.
References FALSE, registered_feature_t::feature, linked_list_t::find_first, is_feature_loadable(), plugin_feature_equals(), registered_feature_t::plugins, and SUCCESS.
Referenced by load_dependencies().
 {
     if (plugin_feature_equals(a->feature, b->feature))
     {
         return b->plugins->find_first(b->plugins, (void*)is_feature_loadable,
                                       NULL) == SUCCESS;
     }
     return FALSE;
 }
static bool loadable_feature_matches (registered_feature_t * a, registered_feature_t * b) static
Find a loadable module that matches the requested feature
Definition at line 586 of file plugin_loader.c.
References FALSE, registered_feature_t::feature, linked_list_t::find_first, is_feature_loadable(), plugin_feature_matches(), registered_feature_t::plugins, and SUCCESS.
Referenced by load_dependencies().
 {
     if (plugin_feature_matches(a->feature, b->feature))
     {
         return b->plugins->find_first(b->plugins, (void*)is_feature_loadable,
                                       NULL) == SUCCESS;
     }
     return FALSE;
 }
static bool loaded_feature_matches (registered_feature_t * a, registered_feature_t * b) static
Find a loaded and matching feature
Definition at line 558 of file plugin_loader.c.
References FALSE, registered_feature_t::feature, linked_list_t::find_first, is_feature_loaded(), plugin_feature_matches(), registered_feature_t::plugins, and SUCCESS.
Referenced by find_compatible_feature().
 {
     if (plugin_feature_matches(a->feature, b->feature))
     {
         return b->plugins->find_first(b->plugins, (void*)is_feature_loaded,
                                       NULL) == SUCCESS;
     }
     return FALSE;
 }
static char* loaded_plugins_list (private_plugin_loader_t * this) static
Create a list of the names of all loaded plugins
Definition at line 482 of file plugin_loader.c.
References enumerator_t::destroy, enumerator_t::enumerate, plugin_t::get_name, len, malloc(), name, plugin, and snprintf.
Referenced by METHOD().
 {
     int buf_len = 128, len = 0;
     char *buf, *name;
     enumerator_t *enumerator;
     plugin_t *plugin;
     buf = malloc(buf_len);
     buf[0] = '\0';
     enumerator = create_plugin_enumerator(this);
     while (enumerator->enumerate(enumerator, &plugin, NULL))
     {
         name = plugin->get_name(plugin);
         if (len + (strlen(name) + 1) >= buf_len)
         {
             buf_len <<= 1;
             buf = realloc(buf, buf_len);
         }
         len += snprintf(&buf[len], buf_len - len, "%s ", name);
     }
     enumerator->destroy(enumerator);
     if (len > 0 && buf[len - 1] == ' ')
     {
         buf[len - 1] = '\0';
     }
     return buf;
 }
METHOD (plugin_t , get_static_name , char * , static_features_t * this)
Definition at line 242 of file plugin_loader.c.
References name.
 {
     return this->name;
 }
METHOD (plugin_t , get_static_features , int , static_features_t * this, plugin_feature_t * features[])
Definition at line 248 of file plugin_loader.c.
References count, and features.
 {
     *features = this->features;
     return this->count;
 }
METHOD (plugin_t , static_reload , bool , static_features_t * this)
Definition at line 255 of file plugin_loader.c.
References FALSE.
 {
     if (this->reload)
     {
         return this->reload(this->reload_data);
     }
     return FALSE;
 }
METHOD (plugin_t , static_destroy , void , static_features_t * this)
Definition at line 265 of file plugin_loader.c.
References features, free(), and name.
 {
     free(this->features);
     free(this->name);
     free(this);
 }
METHOD (plugin_loader_t , create_plugin_enumerator , enumerator_t * , private_plugin_loader_t * this)
Definition at line 442 of file plugin_loader.c.
References enumerator_create_filter(), and plugin_filter().
 {
     return enumerator_create_filter(
                             this->plugins->create_enumerator(this->plugins),
                             (void*)plugin_filter, NULL, NULL);
 }
METHOD (plugin_loader_t , has_feature , bool , private_plugin_loader_t * this, plugin_feature_t feature)
Definition at line 450 of file plugin_loader.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, FALSE, features, found, list, plugin, plugin_feature_matches(), and TRUE.
 {
     enumerator_t *plugins, *features;
     plugin_t *plugin;
     linked_list_t *list;
     plugin_feature_t *current;
     bool found = FALSE;
     plugins = create_plugin_enumerator(this);
     while (plugins->enumerate(plugins, &plugin, &list))
     {
         features = list->create_enumerator(list);
         while (features->enumerate(features, &current))
         {
             if (plugin_feature_matches(&feature, current))
             {
                 found = TRUE;
                 break;
             }
         }
         features->destroy(features);
         list->destroy(list);
     }
     plugins->destroy(plugins);
     return found;
 }
METHOD (plugin_loader_t , add_static_features , void , private_plugin_loader_t * this, const char * name, plugin_feature_t features[], int count, bool critical, bool(*)(void *) reload, void * reload_data)
Definition at line 942 of file plugin_loader.c.
References INIT, linked_list_create(), plugin, register_features(), and static_features_create().
 {
     plugin_entry_t *entry;
     plugin_t *plugin;
     plugin = static_features_create(name, features, count, reload, reload_data);
     INIT(entry,
         .plugin = plugin,
         .critical = critical,
         .features = linked_list_create(),
     );
     this->plugins->insert_last(this->plugins, entry);
     register_features(this, entry);
 }
METHOD (plugin_loader_t , load_plugins , bool , private_plugin_loader_t * this, char * list)
Definition at line 1107 of file plugin_loader.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), FALSE, find_plugin(), free(), len, load_features(), load_plugin(), loaded_plugins_list(), modular_pluginlist(), plugin_loaded(), purge_plugins(), register_features(), stats(), strdup, and TRUE.
 {
     enumerator_t *enumerator;
     char *default_path = NULL, *plugins, *token;
     bool critical_failed = FALSE;
 #ifdef PLUGINDIR
     default_path = PLUGINDIR;
 #endif /* PLUGINDIR */
     plugins = modular_pluginlist(list);
     enumerator = enumerator_create_token(plugins, " ", " ");
     while (!critical_failed && enumerator->enumerate(enumerator, &token))
     {
         plugin_entry_t *entry;
         bool critical = FALSE;
         char buf[PATH_MAX], *file = NULL;
         int len;
         token = strdup(token);
         len = strlen(token);
         if (token[len-1] == '!')
         {
             critical = TRUE;
             token[len-1] = '\0';
         }
         if (plugin_loaded(this, token))
         {
             free(token);
             continue;
         }
         if (this->paths)
         {
             this->paths->find_first(this->paths, (void*)find_plugin, NULL,
                                     token, buf, &file);
         }
         if (!file)
         {
             find_plugin(default_path, token, buf, &file);
         }
         entry = load_plugin(this, token, file, critical);
         if (entry)
         {
             register_features(this, entry);
         }
         else if (critical)
         {
             critical_failed = TRUE;
             DBG1(DBG_LIB, "loading critical plugin '%s' failed", token);
         }
         free(token);
     }
     enumerator->destroy(enumerator);
     if (!critical_failed)
     {
         load_features(this);
         if (this->stats.critical > 0)
         {
             critical_failed = TRUE;
             DBG1(DBG_LIB, "failed to load %d critical plugin feature%s",
                  this->stats.critical, this->stats.critical == 1 ? "" : "s");
         }
         /* unload plugins that we were not able to load any features for */
         purge_plugins(this);
     }
     if (!critical_failed)
     {
         free(this->loaded_plugins);
         this->loaded_plugins = loaded_plugins_list(this);
     }
     if (plugins != list)
     {
         free(plugins);
     }
     return !critical_failed;
 }
METHOD (plugin_loader_t , unload , void , private_plugin_loader_t * this)
Definition at line 1207 of file plugin_loader.c.
References free(), plugin_entry_t::handle, library_t::leak_detective, lib, memset, plugin_entry_destroy(), stats(), SUCCESS, unload_features(), and unregister_features().
 {
     plugin_entry_t *entry;
     /* unload features followed by plugins, in reverse order */
     unload_features(this);
     while (this->plugins->remove_last(this->plugins, (void**)&entry) == SUCCESS)
     {
         if (lib->leak_detective)
         {   /* keep handle to report leaks properly */
             entry->handle = NULL;
         }
         unregister_features(this, entry);
         plugin_entry_destroy(entry);
     }
     free(this->loaded_plugins);
     this->loaded_plugins = NULL;
     memset(&this->stats, 0, sizeof(this->stats));
 }
METHOD (plugin_loader_t , add_path , void , private_plugin_loader_t * this, char * path)
Definition at line 1228 of file plugin_loader.c.
References linked_list_create(), and strdupnull().
 {
     if (!this->paths)
     {
         this->paths = linked_list_create();
     }
     this->paths->insert_last(this->paths, strdupnull(path));
 }
METHOD (plugin_loader_t , reload , u_int , private_plugin_loader_t * this, char * list)
Definition at line 1264 of file plugin_loader.c.
References enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), name, and reload_by_name().
 {
     u_int reloaded = 0;
     enumerator_t *enumerator;
     char *name;
     if (list == NULL)
     {
         return reload_by_name(this, NULL);
     }
     enumerator = enumerator_create_token(list, " ", "");
     while (enumerator->enumerate(enumerator, &name))
     {
         reloaded += reload_by_name(this, name);
     }
     enumerator->destroy(enumerator);
     return reloaded;
 }
METHOD (plugin_loader_t , loaded_plugins , char * , private_plugin_loader_t * this)
Definition at line 1284 of file plugin_loader.c.
 {
     return this->loaded_plugins ?: "";
 }
METHOD (plugin_loader_t , status , void , private_plugin_loader_t * this, level_t level)
Definition at line 1290 of file plugin_loader.c.
References dbg, DBG2, DBG_LIB, and stats().
 {
     if (this->loaded_plugins)
     {
         dbg(DBG_LIB, level, "loaded plugins: %s", this->loaded_plugins);
         if (this->stats.failed)
         {
             DBG2(DBG_LIB, "unable to load %d plugin feature%s (%d due to unmet "
                  "dependencies)", this->stats.failed,
                  this->stats.failed == 1 ? "" : "s", this->stats.depends);
         }
     }
 }
METHOD (plugin_loader_t , destroy , void , private_plugin_loader_t * this)
Definition at line 1306 of file plugin_loader.c.
References DESTROY_FUNCTION_IF, and free().
 {
     unload(this);
     this->features->destroy(this->features);
     this->loaded->destroy(this->loaded);
     this->plugins->destroy(this->plugins);
     DESTROY_FUNCTION_IF(this->paths, free);
     free(this->loaded_plugins);
     free(this);
 }
static char* modular_pluginlist (char * list) static
Determine the list of plugins to load via load option in each plugin's config section.
Definition at line 1032 of file plugin_loader.c.
References array_bsearch(), array_create(), array_create_enumerator(), array_destroy(), array_destroy_function(), array_insert(), array_sort(), ARRAY_TAIL, asprintf(), settings_t::create_section_enumerator, plugin_priority_t::def, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), FALSE, found, free(), settings_t::get_bool, settings_t::get_int, lib, list, plugin_priority_t::name, library_t::ns, plugin, plugin_priority_cmp(), plugin_priority_cmp_name(), plugin_priority_free(), plugin_priority_t::prio, library_t::settings, and strdup.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     array_t *given, *final;
     plugin_priority_t item, *current, found;
     char *plugin, *plugins = NULL;
     int i = 0, max_prio;
     if (!lib->settings->get_bool(lib->settings, "%s.load_modular", FALSE,
                                  lib->ns))
     {
         return list;
     }
     given = array_create(sizeof(plugin_priority_t), 0);
     final = array_create(sizeof(plugin_priority_t), 0);
     enumerator = enumerator_create_token(list, " ", " ");
     while (enumerator->enumerate(enumerator, &plugin))
     {
         item.name = strdup(plugin);
         item.prio = i++;
         array_insert(given, ARRAY_TAIL, &item);
     }
     enumerator->destroy(enumerator);
     array_sort(given, (void*)plugin_priority_cmp_name, NULL);
     /* the maximum priority used for plugins not found in this list */
     max_prio = i + 1;
     enumerator = lib->settings->create_section_enumerator(lib->settings,
                                                         "%s.plugins", lib->ns);
     while (enumerator->enumerate(enumerator, &plugin))
     {
         item.prio = lib->settings->get_int(lib->settings,
                                 "%s.plugins.%s.load", 0, lib->ns, plugin);
         if (!item.prio)
         {
             if (!lib->settings->get_bool(lib->settings,
                                 "%s.plugins.%s.load", FALSE, lib->ns, plugin))
             {
                 continue;
             }
             item.prio = 1;
         }
         item.name = plugin;
         item.def = max_prio;
         if (array_bsearch(given, &item, (void*)plugin_priority_cmp_name,
                           &found) != -1)
         {
             item.def = max_prio - found.prio;
         }
         array_insert(final, ARRAY_TAIL, &item);
     }
     enumerator->destroy(enumerator);
     array_destroy_function(given, (void*)plugin_priority_free, NULL);
     array_sort(final, (void*)plugin_priority_cmp, NULL);
     plugins = strdup("");
     enumerator = array_create_enumerator(final);
     while (enumerator->enumerate(enumerator, &current))
     {
         char *prev = plugins;
         if (asprintf(&plugins, "%s %s", plugins ?: "", current->name) < 0)
         {
             plugins = prev;
             break;
         }
         free(prev);
     }
     enumerator->destroy(enumerator);
     array_destroy(final);
     return plugins;
 }
static void plugin_entry_destroy (plugin_entry_t * entry) static
Destroy a plugin entry
Definition at line 194 of file plugin_loader.c.
References linked_list_t::destroy, DESTROY_IF, dlclose(), plugin_entry_t::features, free(), plugin_entry_t::handle, and plugin_entry_t::plugin.
Referenced by METHOD(), and purge_plugins().
 {
     DESTROY_IF(entry->plugin);
     if (entry->handle)
     {
         dlclose(entry->handle);
     }
     entry->features->destroy(entry->features);
     free(entry);
 }
static bool plugin_filter (void * null, plugin_entry_t ** entry, plugin_t ** plugin, void * in, linked_list_t ** list) static
Convert enumerated entries to plugin_t
Definition at line 425 of file plugin_loader.c.
References enumerator_create_filter(), feature_filter(), features, linked_list_create_from_enumerator(), plugin, and TRUE.
Referenced by METHOD().
 {
     plugin_entry_t *this = *entry;
     *plugin = this->plugin;
     if (list)
     {
         enumerator_t *features;
         features = enumerator_create_filter(
                             this->features->create_enumerator(this->features),
                             (void*)feature_filter, NULL, NULL);
         *list = linked_list_create_from_enumerator(features);
     }
     return TRUE;
 }
static bool plugin_loaded (private_plugin_loader_t * this, char * name) static
Check if a plugin is already loaded
Definition at line 513 of file plugin_loader.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, plugin_t::get_name, name, plugin, streq(), and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     bool found = FALSE;
     plugin_t *plugin;
     enumerator = create_plugin_enumerator(this);
     while (enumerator->enumerate(enumerator, &plugin, NULL))
     {
         if (streq(plugin->get_name(plugin), name))
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static int plugin_priority_cmp (const plugin_priority_t * a, const plugin_priority_t * b, void * user) static
Sort plugins by decreasing priority or default priority then by name
Definition at line 1010 of file plugin_loader.c.
References plugin_priority_t::def, plugin_priority_t::name, and plugin_priority_t::prio.
Referenced by modular_pluginlist().
 {
     int diff;
     diff = b->prio - a->prio;
     if (!diff)
     {   /* the same priority, use default order */
         diff = b->def - a->def;
         if (!diff)
         {   /* same default priority (i.e. both were not found in that list) */
             return strcmp(a->name, b->name);
         }
     }
     return diff;
 }
static int plugin_priority_cmp_name (const plugin_priority_t * a, const plugin_priority_t * b) static
Sort plugins and their priority by name
Definition at line 1001 of file plugin_loader.c.
References plugin_priority_t::name.
Referenced by modular_pluginlist().
 {
     return strcmp(a->name, b->name);
 }
static void plugin_priority_free (const plugin_priority_t * this, int idx, void * user) static
Definition at line 992 of file plugin_loader.c.
References free().
Referenced by modular_pluginlist().
 {
     free(this->name);
 }
static void purge_plugins (private_plugin_loader_t * this) static
Remove plugins we were not able to load any plugin features from.
Definition at line 917 of file plugin_loader.c.
References DBG2, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, plugin_entry_t::features, linked_list_t::find_first, plugin_t::get_features, plugin_t::get_name, is_feature_loaded(), plugin_entry_t::plugin, plugin_entry_destroy(), SUCCESS, and unregister_features().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     plugin_entry_t *entry;
     enumerator = this->plugins->create_enumerator(this->plugins);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (!entry->plugin->get_features)
         {   /* feature interface not supported */
             continue;
         }
         if (entry->features->find_first(entry->features,
                                     (void*)is_feature_loaded, NULL) != SUCCESS)
         {
             DBG2(DBG_LIB, "unloading plugin '%s' without loaded features",
                  entry->plugin->get_name(entry->plugin));
             this->plugins->remove_at(this->plugins, enumerator);
             unregister_features(this, entry);
             plugin_entry_destroy(entry);
         }
     }
     enumerator->destroy(enumerator);
 }
static void register_features (private_plugin_loader_t * this, plugin_entry_t * entry) static
Register plugin features provided by the given plugin
Definition at line 814 of file plugin_loader.c.
References count, DBG1, DBG_LIB, registered_feature_t::feature, plugin_entry_t::features, plugin_t::get_features, plugin_t::get_name, INIT, linked_list_t::insert_last, plugin_feature_t::kind, linked_list_create(), lookup, plugin_entry_t::plugin, registered_feature_t::plugins, and registered.
Referenced by METHOD().
 {
     plugin_feature_t *feature, *reg;
     registered_feature_t *registered, lookup;
     provided_feature_t *provided;
     int count, i;
     if (!entry->plugin->get_features)
     {   /* feature interface not supported */
         DBG1(DBG_LIB, "plugin '%s' does not provide features, deprecated",
              entry->plugin->get_name(entry->plugin));
         return;
     }
     reg = NULL;
     count = entry->plugin->get_features(entry->plugin, &feature);
     for (i = 0; i < count; i++)
     {
         switch (feature->kind)
         {
             case FEATURE_PROVIDE:
                 lookup.feature = feature;
                 registered = this->features->get(this->features, &lookup);
                 if (!registered)
                 {
                     INIT(registered,
                         .feature = feature,
                         .plugins = linked_list_create(),
                     );
                     this->features->put(this->features, registered, registered);
                 }
                 INIT(provided,
                     .entry = entry,
                     .feature = feature,
                     .reg = reg,
                     .dependencies = count - i,
                 );
                 registered->plugins->insert_last(registered->plugins,
                                                  provided);
                 entry->features->insert_last(entry->features, provided);
                 break;
             case FEATURE_REGISTER:
             case FEATURE_CALLBACK:
                 reg = feature;
                 break;
             default:
                 break;
         }
         feature++;
     }
 }
static bool registered_feature_equals (registered_feature_t * a, registered_feature_t * b) static
Compare two registered features
Definition at line 118 of file plugin_loader.c.
References registered_feature_t::feature, and plugin_feature_equals().
Referenced by plugin_loader_create().
 {
     return plugin_feature_equals(a->feature, b->feature);
 }
static bool registered_feature_hash (registered_feature_t * this) static
Hash a registered feature
Definition at line 110 of file plugin_loader.c.
References plugin_feature_hash().
Referenced by plugin_loader_create().
 {
     return plugin_feature_hash(this->feature);
 }
static u_int reload_by_name (private_plugin_loader_t * this, char * name) static
Reload a plugin by name, NULL for all
Definition at line 1241 of file plugin_loader.c.
References DBG2, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, plugin_t::get_name, plugin, plugin_t::reload, and streq().
Referenced by METHOD().
 {
     u_int reloaded = 0;
     enumerator_t *enumerator;
     plugin_t *plugin;
     enumerator = create_plugin_enumerator(this);
     while (enumerator->enumerate(enumerator, &plugin, NULL))
     {
         if (name == NULL || streq(name, plugin->get_name(plugin)))
         {
             if (plugin->reload && plugin->reload(plugin))
             {
                 DBG2(DBG_LIB, "reloaded configuration of '%s' plugin",
                      plugin->get_name(plugin));
                 reloaded++;
             }
         }
     }
     enumerator->destroy(enumerator);
     return reloaded;
 }
static plugin_t* static_features_create (const char * name, plugin_feature_t features[], int count, bool(*)(void *) reload, void * reload_data) static
Create a wrapper around static plugin features.
Definition at line 276 of file plugin_loader.c.
References count, INIT, memcpy, and strdup.
Referenced by METHOD().
 {
     static_features_t *this;
     INIT(this,
         .public = {
             .get_name = _get_static_name,
             .get_features = _get_static_features,
             .reload = _static_reload,
             .destroy = _static_destroy,
         },
         .name = strdup(name),
         .reload = reload,
         .reload_data = reload_data,
         .features = calloc(count, sizeof(plugin_feature_t)),
         .count = count,
     );
     memcpy(this->features, features, sizeof(plugin_feature_t) * count);
     return &this->public;
 }
static void unload_features (private_plugin_loader_t * this) static
Unload plugin features, they are registered in reverse order
Definition at line 1189 of file plugin_loader.c.
References enumerator_t::destroy, provided_feature_t::entry, enumerator_t::enumerate, provided_feature_t::feature, plugin_entry_t::features, plugin_entry_t::plugin, plugin_feature_unload(), provided_feature_t::reg, linked_list_t::remove, and unregister_feature().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     provided_feature_t *provided;
     plugin_entry_t *entry;
     enumerator = this->loaded->create_enumerator(this->loaded);
     while (enumerator->enumerate(enumerator, &provided))
     {
         entry = provided->entry;
         plugin_feature_unload(entry->plugin, provided->feature, provided->reg);
         this->loaded->remove_at(this->loaded, enumerator);
         entry->features->remove(entry->features, provided, NULL);
         unregister_feature(this, provided);
     }
     enumerator->destroy(enumerator);
 }
static void unregister_feature (private_plugin_loader_t * this, provided_feature_t * provided) static
Unregister a plugin feature
Definition at line 869 of file plugin_loader.c.
References linked_list_t::destroy, registered_feature_t::feature, provided_feature_t::feature, free(), linked_list_t::get_count, linked_list_t::get_first, lookup, registered_feature_t::plugins, registered, and linked_list_t::remove.
Referenced by unload_features(), and unregister_features().
 {
     registered_feature_t *registered, lookup;
     lookup.feature = provided->feature;
     registered = this->features->get(this->features, &lookup);
     if (registered)
     {
         registered->plugins->remove(registered->plugins, provided, NULL);
         if (registered->plugins->get_count(registered->plugins) == 0)
         {
             this->features->remove(this->features, &lookup);
             registered->plugins->destroy(registered->plugins);
             free(registered);
         }
         else if (registered->feature == provided->feature)
         {   /* update feature in case the providing plugin gets unloaded */
             provided_feature_t *first;
             registered->plugins->get_first(registered->plugins, (void**)&first);
             registered->feature = first->feature;
         }
     }
     free(provided);
 }
static void unregister_features (private_plugin_loader_t * this, plugin_entry_t * entry) static
Unregister plugin features
Definition at line 899 of file plugin_loader.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, plugin_entry_t::features, linked_list_t::remove_at, and unregister_feature().
Referenced by METHOD(), and purge_plugins().
 {
     provided_feature_t *provided;
     enumerator_t *enumerator;
     enumerator = entry->features->create_enumerator(entry->features);
     while (enumerator->enumerate(enumerator, &provided))
     {
         entry->features->remove_at(entry->features, enumerator);
         unregister_feature(this, provided);
     }
     enumerator->destroy(enumerator);
 }