strongSwan: mysql_database
mysql_database
mysql
Classes
struct mysql_database_t
Typedefs
typedef struct mysql_database_t mysql_database_t
Functions
mysql_database_t * mysql_database_create (char *uri)
bool mysql_database_init ()
void mysql_database_deinit ()
Detailed Description
Typedef Documentation
typedef struct mysql_database_t mysql_database_t
Definition at line 27 of file mysql_database.h.
Function Documentation
mysql_database_t* mysql_database_create (char * uri)
Create a mysql_database instance.
Parameters
uri connection URI, mysql://user:pass@.nosp@m.exam.nosp@m.ple.c.nosp@m.om:port/database
Definition at line 817 of file mysql_database.c.
References conn, conn_get(), conn_release(), destroy(), free(), INIT, linked_list_create(), mutex, mutex_create(), MUTEX_TYPE_DEFAULT, parse_uri(), strpfx(), and thread_value_create().
Referenced by METHOD().
 {
     conn_t *conn;
     private_mysql_database_t *this;
     if (!strpfx(uri, "mysql://"))
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .db = {
                 .query = _query,
                 .execute = _execute,
                 .transaction = _transaction,
                 .commit = _commit_,
                 .rollback = _rollback,
                 .get_driver = _get_driver,
                 .destroy = _destroy,
             },
         },
     );
     if (!parse_uri(this, uri))
     {
         free(this);
         return NULL;
     }
     this->mutex = mutex_create(MUTEX_TYPE_DEFAULT);
     this->pool = linked_list_create();
     this->transaction = thread_value_create(NULL);
     /* check connectivity */
     conn = conn_get(this, NULL);
     if (!conn)
     {
         destroy(this);
         return NULL;
     }
     conn_release(this, conn);
     return &this->public;
 }
void mysql_database_deinit ()
Mysql client library cleanup function
mysql library cleanup function
Definition at line 182 of file mysql_database.c.
References thread_value_t::destroy.
Referenced by METHOD().
 {
     initialized->destroy(initialized);
     mysql_thread_end();
     mysql_library_end();
 }
bool mysql_database_init ()
MySQL client library initialization function
Returns
FALSE if initialization failed
mysql library initialization function
Definition at line 169 of file mysql_database.c.
References FALSE, thread_value_create(), and TRUE.
Referenced by mysql_plugin_create().
 {
     if (mysql_library_init(0, NULL, NULL))
     {
         return FALSE;
     }
     initialized = thread_value_create((thread_cleanup_t)mysql_thread_end);
     return TRUE;
 }