strongSwan: bio_writer.c File Reference
bio_writer.c File Reference
#include "bio_writer.h"
Classes
struct private_bio_writer_t
Typedefs
typedef struct private_bio_writer_t private_bio_writer_t
Functions
static void increase (private_bio_writer_t *this, size_t required)
METHOD (bio_writer_t, write_uint8, void, private_bio_writer_t *this, u_int8_t value)
METHOD (bio_writer_t, write_uint16, void, private_bio_writer_t *this, u_int16_t value)
METHOD (bio_writer_t, write_uint24, void, private_bio_writer_t *this, u_int32_t value)
METHOD (bio_writer_t, write_uint32, void, private_bio_writer_t *this, u_int32_t value)
METHOD (bio_writer_t, write_uint64, void, private_bio_writer_t *this, u_int64_t value)
METHOD (bio_writer_t, write_data, void, private_bio_writer_t *this, chunk_t value)
METHOD (bio_writer_t, write_data8, void, private_bio_writer_t *this, chunk_t value)
METHOD (bio_writer_t, write_data16, void, private_bio_writer_t *this, chunk_t value)
METHOD (bio_writer_t, write_data24, void, private_bio_writer_t *this, chunk_t value)
METHOD (bio_writer_t, write_data32, void, private_bio_writer_t *this, chunk_t value)
METHOD (bio_writer_t, wrap8, void, private_bio_writer_t *this)
METHOD (bio_writer_t, wrap16, void, private_bio_writer_t *this)
METHOD (bio_writer_t, wrap24, void, private_bio_writer_t *this)
METHOD (bio_writer_t, wrap32, void, private_bio_writer_t *this)
METHOD (bio_writer_t, skip, chunk_t, private_bio_writer_t *this, size_t len)
METHOD (bio_writer_t, get_buf, chunk_t, private_bio_writer_t *this)
METHOD (bio_writer_t, extract_buf, chunk_t, private_bio_writer_t *this)
METHOD (bio_writer_t, destroy, void, private_bio_writer_t *this)
bio_writer_t * bio_writer_create (u_int32_t bufsize)
Typedef Documentation
typedef struct private_bio_writer_t private_bio_writer_t
Definition at line 21 of file bio_writer.c.
Function Documentation
static void increase (private_bio_writer_t * this, size_t required) inline static
Increase buffer size, if required
Definition at line 52 of file bio_writer.c.
References FALSE, inc, and TRUE.
Referenced by make_head_room(), and METHOD().
 {
     bool inc = FALSE;
     while (this->used + required > this->buf.len)
     {
         this->buf.len += this->increase;
         inc = TRUE;
     }
     if (inc)
     {
         this->buf.ptr = realloc(this->buf.ptr, this->buf.len);
     }
 }
METHOD (bio_writer_t , write_uint8 , void , private_bio_writer_t * this, u_int8_t value)
Definition at line 67 of file bio_writer.c.
References increase(), and value.
 {
     increase(this, 1);
     this->buf.ptr[this->used] = value;
     this->used += 1;
 }
METHOD (bio_writer_t , write_uint16 , void , private_bio_writer_t * this, u_int16_t value)
Definition at line 75 of file bio_writer.c.
References htoun16(), and increase().
 {
     increase(this, 2);
     htoun16(this->buf.ptr + this->used, value);
     this->used += 2;
 }
METHOD (bio_writer_t , write_uint24 , void , private_bio_writer_t * this, u_int32_t value)
Definition at line 83 of file bio_writer.c.
References increase(), and memcpy.
 {
     increase(this, 3);
     value = htonl(value);
     memcpy(this->buf.ptr + this->used, ((char*)&value) + 1, 3);
     this->used += 3;
 }
METHOD (bio_writer_t , write_uint32 , void , private_bio_writer_t * this, u_int32_t value)
Definition at line 92 of file bio_writer.c.
References htoun32(), and increase().
 {
     increase(this, 4);
     htoun32(this->buf.ptr + this->used, value);
     this->used += 4;
 }
METHOD (bio_writer_t , write_uint64 , void , private_bio_writer_t * this, u_int64_t value)
Definition at line 100 of file bio_writer.c.
References htoun64(), and increase().
 {
     increase(this, 8);
     htoun64(this->buf.ptr + this->used, value);
     this->used += 8;
 }
METHOD (bio_writer_t , write_data , void , private_bio_writer_t * this, chunk_t value)
Definition at line 108 of file bio_writer.c.
References increase(), chunk_t::len, memcpy, and chunk_t::ptr.
 {
     increase(this, value.len);
     memcpy(this->buf.ptr + this->used, value.ptr, value.len);
     this->used += value.len;
 }
METHOD (bio_writer_t , write_data8 , void , private_bio_writer_t * this, chunk_t value)
Definition at line 116 of file bio_writer.c.
References increase(), and chunk_t::len.
 {
     increase(this, 1 + value.len);
     write_uint8(this, value.len);
     write_data(this, value);
 }
METHOD (bio_writer_t , write_data16 , void , private_bio_writer_t * this, chunk_t value)
Definition at line 124 of file bio_writer.c.
References increase(), and chunk_t::len.
 {
     increase(this, 2 + value.len);
     write_uint16(this, value.len);
     write_data(this, value);
 }
METHOD (bio_writer_t , write_data24 , void , private_bio_writer_t * this, chunk_t value)
Definition at line 132 of file bio_writer.c.
References increase(), and chunk_t::len.
 {
     increase(this, 3 + value.len);
     write_uint24(this, value.len);
     write_data(this, value);
 }
METHOD (bio_writer_t , write_data32 , void , private_bio_writer_t * this, chunk_t value)
Definition at line 140 of file bio_writer.c.
References increase(), and chunk_t::len.
 {
     increase(this, 4 + value.len);
     write_uint32(this, value.len);
     write_data(this, value);
 }
METHOD (bio_writer_t , wrap8 , void , private_bio_writer_t * this)
Definition at line 148 of file bio_writer.c.
References increase(), and memmove.
 {
     increase(this, 1);
     memmove(this->buf.ptr + 1, this->buf.ptr, this->used);
     this->buf.ptr[0] = this->used;
     this->used += 1;
 }
METHOD (bio_writer_t , wrap16 , void , private_bio_writer_t * this)
Definition at line 157 of file bio_writer.c.
References htoun16(), increase(), and memmove.
 {
     increase(this, 2);
     memmove(this->buf.ptr + 2, this->buf.ptr, this->used);
     htoun16(this->buf.ptr, this->used);
     this->used += 2;
 }
METHOD (bio_writer_t , wrap24 , void , private_bio_writer_t * this)
Definition at line 166 of file bio_writer.c.
References increase(), len, memcpy, and memmove.
 {
     u_int32_t len;
     increase(this, 3);
     memmove(this->buf.ptr + 3, this->buf.ptr, this->used);
     len = htonl(this->used);
     memcpy(this->buf.ptr, ((char*)&len) + 1, 3);
     this->used += 3;
 }
METHOD (bio_writer_t , wrap32 , void , private_bio_writer_t * this)
Definition at line 179 of file bio_writer.c.
References htoun32(), increase(), and memmove.
 {
     increase(this, 4);
     memmove(this->buf.ptr + 4, this->buf.ptr, this->used);
     htoun32(this->buf.ptr, this->used);
     this->used += 4;
 }
METHOD (bio_writer_t , skip , chunk_t , private_bio_writer_t * this, size_t len)
Definition at line 188 of file bio_writer.c.
References chunk_create(), increase(), and len.
 {
     chunk_t skipped;
     increase(this, len);
     skipped = chunk_create(this->buf.ptr + this->used, len);
     this->used += len;
     return skipped;
 }
METHOD (bio_writer_t , get_buf , chunk_t , private_bio_writer_t * this)
Definition at line 199 of file bio_writer.c.
References chunk_create().
 {
     return chunk_create(this->buf.ptr, this->used);
 }
METHOD (bio_writer_t , extract_buf , chunk_t , private_bio_writer_t * this)
Definition at line 205 of file bio_writer.c.
References chunk_empty.
 {
     chunk_t buf = get_buf(this);
     this->buf = chunk_empty;
     this->used = 0;
     return buf;
 }
METHOD (bio_writer_t , destroy , void , private_bio_writer_t * this)
Definition at line 214 of file bio_writer.c.
References free().
 {
     free(this->buf.ptr);
     free(this);
 }