strongSwan: parser.c File Reference
libcharon/encoding/parser.c File Reference
#include <stdlib.h>
#include <string.h>
#include "parser.h"
#include <library.h>
#include <daemon.h>
#include <collections/linked_list.h>
#include <encoding/payloads/encodings.h>
#include <encoding/payloads/payload.h>
#include <encoding/payloads/sa_payload.h>
#include <encoding/payloads/proposal_substructure.h>
#include <encoding/payloads/transform_substructure.h>
#include <encoding/payloads/transform_attribute.h>
#include <encoding/payloads/ke_payload.h>
#include <encoding/payloads/nonce_payload.h>
#include <encoding/payloads/id_payload.h>
#include <encoding/payloads/notify_payload.h>
#include <encoding/payloads/encrypted_payload.h>
#include <encoding/payloads/auth_payload.h>
#include <encoding/payloads/cert_payload.h>
#include <encoding/payloads/certreq_payload.h>
#include <encoding/payloads/ts_payload.h>
#include <encoding/payloads/delete_payload.h>
#include <encoding/payloads/vendor_id_payload.h>
#include <encoding/payloads/cp_payload.h>
#include <encoding/payloads/configuration_attribute.h>
#include <encoding/payloads/eap_payload.h>
#include <encoding/payloads/unknown_payload.h>
Classes
struct private_parser_t
Typedefs
typedef struct private_parser_t private_parser_t
Functions
static bool short_input (private_parser_t *this, int number)
static bool bad_bitpos (private_parser_t *this, int number)
static bool parse_uint4 (private_parser_t *this, int rule_number, u_int8_t *output_pos)
static bool parse_uint8 (private_parser_t *this, int rule_number, u_int8_t *output_pos)
static bool parse_uint15 (private_parser_t *this, int rule_number, u_int16_t *output_pos)
static bool parse_uint16 (private_parser_t *this, int rule_number, u_int16_t *output_pos)
static bool parse_uint32 (private_parser_t *this, int rule_number, u_int32_t *output_pos)
static bool parse_bytes (private_parser_t *this, int rule_number, u_int8_t *output_pos, int bytes)
static bool parse_bit (private_parser_t *this, int rule_number, bool *output_pos)
static bool parse_list (private_parser_t *this, int rule_number, linked_list_t **output_pos, payload_type_t payload_type, int length)
static bool parse_chunk (private_parser_t *this, int rule_number, chunk_t *output_pos, int length)
METHOD (parser_t, parse_payload, status_t, private_parser_t *this, payload_type_t payload_type, payload_t **payload)
METHOD (parser_t, get_remaining_byte_count, int, private_parser_t *this)
METHOD (parser_t, reset_context, void, private_parser_t *this)
METHOD (parser_t, set_major_version, void, private_parser_t *this, u_int8_t major_version)
METHOD (parser_t, destroy, void, private_parser_t *this)
parser_t * parser_create (chunk_t data)
Typedef Documentation
typedef struct private_parser_t private_parser_t
Definition at line 48 of file libcharon/encoding/parser.c.
Function Documentation
static bool bad_bitpos (private_parser_t * this, int number) static
Log unaligned rules
Definition at line 105 of file libcharon/encoding/parser.c.
References DBG1, DBG_ENC, encoding_type_names, FALSE, and type.
Referenced by parse_bytes(), parse_chunk(), parse_list(), parse_uint15(), parse_uint16(), parse_uint32(), parse_uint4(), and parse_uint8().
 {
     DBG1(DBG_ENC, "  found rule %d %N on bitpos %d",
          number, encoding_type_names, this->rules[number].type, this->bit_pos);
     return FALSE;
 }
METHOD (parser_t , parse_payload , status_t , private_parser_t * this, payload_type_t payload_type, payload_t ** payload)
Definition at line 365 of file libcharon/encoding/parser.c.
References ADDRESS, ATTRIBUTE_FORMAT, ATTRIBUTE_LENGTH, ATTRIBUTE_LENGTH_OR_VALUE, ATTRIBUTE_TYPE, ATTRIBUTE_VALUE, CHUNK_DATA, DBG1, DBG2, DBG3, DBG_ENC, payload_t::destroy, encoding_type_names, ENCRYPTED_DATA, FALSE, FLAG, payload_t::get_encoding_rules, payload_t::get_header_length, HEADER_LENGTH, IKE_SPI, encoding_rule_t::offset, parse_bit(), parse_bytes(), parse_chunk(), PARSE_ERROR, parse_list(), parse_uint15(), parse_uint16(), parse_uint32(), parse_uint4(), parse_uint8(), payload_create(), payload_is_known(), PAYLOAD_LENGTH, PAYLOAD_LIST, payload_type_names, PLV1_CONFIGURATION_ATTRIBUTE, PLV1_PROPOSAL_SUBSTRUCTURE, PLV1_TRANSFORM_ATTRIBUTE, PLV1_TRANSFORM_SUBSTRUCTURE, PLV2_CONFIGURATION_ATTRIBUTE, PLV2_PROPOSAL_SUBSTRUCTURE, PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE, PLV2_TRANSFORM_ATTRIBUTE, PLV2_TRANSFORM_SUBSTRUCTURE, RESERVED_BIT, RESERVED_BYTE, SPI, SPI_SIZE, SUCCESS, TS_IPV4_ADDR_RANGE, TS_TYPE, encoding_rule_t::type, U_INT_16, U_INT_32, U_INT_4, U_INT_8, and unknown_payload_create().
 {
     payload_t *pld;
     void *output;
     int payload_length = 0, spi_size = 0, attribute_length = 0, header_length;
     u_int16_t ts_type = 0;
     bool attribute_format = FALSE;
     int rule_number, rule_count;
     encoding_rule_t *rule;
     /* create instance of the payload to parse */
     if (payload_is_known(payload_type, this->major_version))
     {
         pld = payload_create(payload_type);
     }
     else
     {
         pld = (payload_t*)unknown_payload_create(payload_type);
     }
     DBG2(DBG_ENC, "parsing %N payload, %d bytes left",
          payload_type_names, payload_type, this->input_roof - this->byte_pos);
     DBG3(DBG_ENC, "parsing payload from %b",
          this->byte_pos, (u_int)(this->input_roof - this->byte_pos));
     /* base pointer for output, avoids casting in every rule */
     output = pld;
     /* parse the payload with its own rulse */
     rule_count = pld->get_encoding_rules(pld, &this->rules);
     for (rule_number = 0; rule_number < rule_count; rule_number++)
     {
         /* update header length for each rule, as it is dynamic (SPIs) */
         header_length = pld->get_header_length(pld);
         rule = &(this->rules[rule_number]);
         DBG2(DBG_ENC, "  parsing rule %d %N",
              rule_number, encoding_type_names, rule->type);
         switch ((int)rule->type)
         {
             case U_INT_4:
             {
                 if (!parse_uint4(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case U_INT_8:
             case RESERVED_BYTE:
             {
                 if (!parse_uint8(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case U_INT_16:
             {
                 if (!parse_uint16(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case U_INT_32:
             case HEADER_LENGTH:
             {
                 if (!parse_uint32(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case IKE_SPI:
             {
                 if (!parse_bytes(this, rule_number, output + rule->offset, 8))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case RESERVED_BIT:
             case FLAG:
             {
                 if (!parse_bit(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case PAYLOAD_LENGTH:
             {
                 if (!parse_uint16(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 /* parsed u_int16 should be aligned */
                 payload_length = *(u_int16_t*)(output + rule->offset);
                 /* all payloads must have at least 4 bytes header */
                 if (payload_length < 4)
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case SPI_SIZE:
             {
                 if (!parse_uint8(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 spi_size = *(u_int8_t*)(output + rule->offset);
                 break;
             }
             case SPI:
             {
                 if (!parse_chunk(this, rule_number, output + rule->offset,
                                  spi_size))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case PAYLOAD_LIST + PLV2_PROPOSAL_SUBSTRUCTURE:
             case PAYLOAD_LIST + PLV1_PROPOSAL_SUBSTRUCTURE:
             case PAYLOAD_LIST + PLV2_TRANSFORM_SUBSTRUCTURE:
             case PAYLOAD_LIST + PLV1_TRANSFORM_SUBSTRUCTURE:
             case PAYLOAD_LIST + PLV2_TRANSFORM_ATTRIBUTE:
             case PAYLOAD_LIST + PLV1_TRANSFORM_ATTRIBUTE:
             case PAYLOAD_LIST + PLV2_CONFIGURATION_ATTRIBUTE:
             case PAYLOAD_LIST + PLV1_CONFIGURATION_ATTRIBUTE:
             case PAYLOAD_LIST + PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE:
             {
                 if (payload_length < header_length ||
                     !parse_list(this, rule_number, output + rule->offset,
                                 rule->type - PAYLOAD_LIST,
                                 payload_length - header_length))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case CHUNK_DATA:
             {
                 if (payload_length < header_length ||
                     !parse_chunk(this, rule_number, output + rule->offset,
                                  payload_length - header_length))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case ENCRYPTED_DATA:
             {
                 if (!parse_chunk(this, rule_number, output + rule->offset,
                                  this->input_roof - this->byte_pos))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case ATTRIBUTE_FORMAT:
             {
                 if (!parse_bit(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 attribute_format = *(bool*)(output + rule->offset);
                 break;
             }
             case ATTRIBUTE_TYPE:
             {
                 if (!parse_uint15(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case ATTRIBUTE_LENGTH:
             {
                 if (!parse_uint16(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 attribute_length = *(u_int16_t*)(output + rule->offset);
                 break;
             }
             case ATTRIBUTE_LENGTH_OR_VALUE:
             {
                 if (!parse_uint16(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 attribute_length = *(u_int16_t*)(output + rule->offset);
                 break;
             }
             case ATTRIBUTE_VALUE:
             {
                 if (attribute_format == FALSE &&
                     !parse_chunk(this, rule_number, output + rule->offset,
                                  attribute_length))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             case TS_TYPE:
             {
                 if (!parse_uint8(this, rule_number, output + rule->offset))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 ts_type = *(u_int8_t*)(output + rule->offset);
                 break;
             }
             case ADDRESS:
             {
                 int address_length = (ts_type == TS_IPV4_ADDR_RANGE) ? 4 : 16;
                 if (!parse_chunk(this, rule_number, output + rule->offset,
                                  address_length))
                 {
                     pld->destroy(pld);
                     return PARSE_ERROR;
                 }
                 break;
             }
             default:
             {
                 DBG1(DBG_ENC, "  no rule to parse rule %d %N",
                      rule_number, encoding_type_names, rule->type);
                 pld->destroy(pld);
                 return PARSE_ERROR;
             }
         }
         /* process next rulue */
         rule++;
     }
     *payload = pld;
     DBG2(DBG_ENC, "parsing %N payload finished",
          payload_type_names, payload_type);
     return SUCCESS;
 }
METHOD (parser_t , get_remaining_byte_count , int , private_parser_t * this)
Definition at line 631 of file libcharon/encoding/parser.c.
 {
     return this->input_roof - this->byte_pos;
 }
METHOD (parser_t , reset_context , void , private_parser_t * this)
Definition at line 637 of file libcharon/encoding/parser.c.
 {
     this->byte_pos = this->input;
     this->bit_pos = 0;
 }
METHOD (parser_t , set_major_version , void , private_parser_t * this, u_int8_t major_version)
Definition at line 644 of file libcharon/encoding/parser.c.
 {
     this->major_version = major_version;
 }
METHOD (parser_t , destroy , void , private_parser_t * this)
Definition at line 650 of file libcharon/encoding/parser.c.
References free().
 {
     free(this);
 }
static bool parse_bit (private_parser_t * this, int rule_number, bool * output_pos) static
Parse a single Bit from the current parsing position
Definition at line 270 of file libcharon/encoding/parser.c.
References DBG3, DBG_ENC, mask, short_input(), and TRUE.
Referenced by METHOD().
 {
     if (this->byte_pos + sizeof(u_int8_t) > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     if (output_pos)
     {
         u_int8_t mask;
         mask = 0x01 << (7 - this->bit_pos);
         *output_pos = *this->byte_pos & mask;
         if (*output_pos)
         {   /* set to a "clean", comparable true */
             *output_pos = TRUE;
         }
         DBG3(DBG_ENC, "   => %d", *output_pos);
     }
     this->bit_pos = (this->bit_pos + 1) % 8;
     if (this->bit_pos == 0)
     {
         this->byte_pos++;
     }
     return TRUE;
 }
static bool parse_bytes (private_parser_t * this, int rule_number, u_int8_t * output_pos, int bytes) static
Parse a given amount of bytes and writes them to a specific location
Definition at line 247 of file libcharon/encoding/parser.c.
References bad_bitpos(), bytes, DBG3, DBG_ENC, memcpy, short_input(), and TRUE.
Referenced by CALLBACK(), and METHOD().
 {
     if (this->byte_pos + bytes > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     if (this->bit_pos)
     {
         return bad_bitpos(this, rule_number);
     }
     if (output_pos)
     {
         memcpy(output_pos, this->byte_pos, bytes);
         DBG3(DBG_ENC, "   %b", output_pos, bytes);
     }
     this->byte_pos += bytes;
     return TRUE;
 }
static bool parse_chunk (private_parser_t * this, int rule_number, chunk_t * output_pos, int length) static
Parse data from current parsing position in a chunk.
Definition at line 344 of file libcharon/encoding/parser.c.
References bad_bitpos(), chunk_alloc, DBG3, DBG_ENC, length, memcpy, chunk_t::ptr, short_input(), and TRUE.
Referenced by METHOD().
 {
     if (this->byte_pos + length > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     if (this->bit_pos)
     {
         return bad_bitpos(this, rule_number);
     }
     if (output_pos)
     {
         *output_pos = chunk_alloc(length);
         memcpy(output_pos->ptr, this->byte_pos, length);
         DBG3(DBG_ENC, "   %b", output_pos->ptr, length);
     }
     this->byte_pos += length;
     return TRUE;
 }
static bool parse_list (private_parser_t * this, int rule_number, linked_list_t ** output_pos, payload_type_t payload_type, int length) static
Parse substructures in a list.
Definition at line 300 of file libcharon/encoding/parser.c.
References bad_bitpos(), DBG1, DBG2, DBG_ENC, FALSE, linked_list_t::insert_last, list, payload_type_names, short_input(), SUCCESS, and TRUE.
Referenced by METHOD().
 {
     linked_list_t *list = *output_pos;
     if (length < 0)
     {
         return short_input(this, rule_number);
     }
     if (this->bit_pos)
     {
         return bad_bitpos(this, rule_number);
     }
     while (length > 0)
     {
         u_int8_t *pos_before = this->byte_pos;
         payload_t *payload;
         DBG2(DBG_ENC, "  %d bytes left, parsing recursively %N",
              length, payload_type_names, payload_type);
         if (this->public.parse_payload(&this->public, payload_type,
                                        &payload) != SUCCESS)
         {
             DBG1(DBG_ENC, "  parsing of a %N substructure failed",
                  payload_type_names, payload_type);
             return FALSE;
         }
         list->insert_last(list, payload);
         length -= this->byte_pos - pos_before;
     }
     if (length != 0)
     {   /* must yield exactly to zero */
         DBG1(DBG_ENC, "  length of %N substructure list invalid",
              payload_type_names, payload_type);
         return FALSE;
     }
     *output_pos = list;
     return TRUE;
 }
static bool parse_uint15 (private_parser_t * this, int rule_number, u_int16_t * output_pos) static
Parse a 15-Bit unsigned integer from the current parsing position.
Definition at line 175 of file libcharon/encoding/parser.c.
References bad_bitpos(), DBG3, DBG_ENC, memcpy, short_input(), and TRUE.
Referenced by METHOD().
 {
     if (this->byte_pos + sizeof(u_int16_t) > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     if (this->bit_pos != 1)
     {
         return bad_bitpos(this, rule_number);
     }
     if (output_pos)
     {
         memcpy(output_pos, this->byte_pos, sizeof(u_int16_t));
         *output_pos = ntohs(*output_pos) & ~0x8000;
         DBG3(DBG_ENC, "   => %hu", *output_pos);
     }
     this->byte_pos += sizeof(u_int16_t);
     this->bit_pos = 0;
     return TRUE;
 }
static bool parse_uint16 (private_parser_t * this, int rule_number, u_int16_t * output_pos) static
Parse a 16-Bit unsigned integer from the current parsing position.
Definition at line 200 of file libcharon/encoding/parser.c.
References bad_bitpos(), DBG3, DBG_ENC, memcpy, short_input(), and TRUE.
Referenced by METHOD().
 {
     if (this->byte_pos + sizeof(u_int16_t) > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     if (this->bit_pos)
     {
         return bad_bitpos(this, rule_number);
     }
     if (output_pos)
     {
         memcpy(output_pos, this->byte_pos, sizeof(u_int16_t));
         *output_pos = ntohs(*output_pos);
         DBG3(DBG_ENC, "   => %hu", *output_pos);
     }
     this->byte_pos += sizeof(u_int16_t);
     return TRUE;
 }
static bool parse_uint32 (private_parser_t * this, int rule_number, u_int32_t * output_pos) static
Parse a 32-Bit unsigned integer from the current parsing position.
Definition at line 223 of file libcharon/encoding/parser.c.
References bad_bitpos(), DBG3, DBG_ENC, memcpy, short_input(), and TRUE.
Referenced by CALLBACK(), and METHOD().
 {
     if (this->byte_pos + sizeof(u_int32_t) > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     if (this->bit_pos)
     {
         return bad_bitpos(this, rule_number);
     }
     if (output_pos)
     {
         memcpy(output_pos, this->byte_pos, sizeof(u_int32_t));
         *output_pos = ntohl(*output_pos);
         DBG3(DBG_ENC, "   => %u", *output_pos);
     }
     this->byte_pos += sizeof(u_int32_t);
     return TRUE;
 }
static bool parse_uint4 (private_parser_t * this, int rule_number, u_int8_t * output_pos) static
Parse a 4-Bit unsigned integer from the current parsing position.
Definition at line 115 of file libcharon/encoding/parser.c.
References bad_bitpos(), DBG3, DBG_ENC, short_input(), and TRUE.
Referenced by METHOD().
 {
     if (this->byte_pos + sizeof(u_int8_t) > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     switch (this->bit_pos)
     {
         case 0:
             if (output_pos)
             {
                 *output_pos = *(this->byte_pos) >> 4;
             }
             this->bit_pos = 4;
             break;
         case 4:
             if (output_pos)
             {
                 *output_pos = *(this->byte_pos) & 0x0F;
             }
             this->bit_pos = 0;
             this->byte_pos++;
             break;
         default:
             return bad_bitpos(this, rule_number);
     }
     if (output_pos)
     {
         DBG3(DBG_ENC, "   => %hhu", *output_pos);
     }
     return TRUE;
 }
static bool parse_uint8 (private_parser_t * this, int rule_number, u_int8_t * output_pos) static
Parse a 8-Bit unsigned integer from the current parsing position.
Definition at line 152 of file libcharon/encoding/parser.c.
References bad_bitpos(), DBG3, DBG_ENC, short_input(), and TRUE.
Referenced by METHOD().
 {
     if (this->byte_pos + sizeof(u_int8_t) > this->input_roof)
     {
         return short_input(this, rule_number);
     }
     if (this->bit_pos)
     {
         return bad_bitpos(this, rule_number);
     }
     if (output_pos)
     {
         *output_pos = *(this->byte_pos);
         DBG3(DBG_ENC, "   => %hhu", *output_pos);
     }
     this->byte_pos++;
     return TRUE;
 }
static bool short_input (private_parser_t * this, int number) static
Log invalid length error
Definition at line 95 of file libcharon/encoding/parser.c.
References DBG1, DBG_ENC, encoding_type_names, FALSE, and type.
Referenced by parse_bit(), parse_bytes(), parse_chunk(), parse_list(), parse_uint15(), parse_uint16(), parse_uint32(), parse_uint4(), and parse_uint8().
 {
     DBG1(DBG_ENC, "  not enough input to parse rule %d %N",
          number, encoding_type_names, this->rules[number].type);
     return FALSE;
 }