strongSwan: eap_aka_peer
eap_aka_peer
eap_aka
Classes
struct eap_aka_peer_t
Typedefs
typedef struct eap_aka_peer_t eap_aka_peer_t
Functions
eap_aka_peer_t * eap_aka_peer_create (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_aka_peer_t eap_aka_peer_t
Definition at line 24 of file eap_aka_peer.h.
Function Documentation
eap_aka_peer_t* eap_aka_peer_create (identification_t * server, identification_t * peer)
Creates the peer implementation of the EAP method EAP-AKA.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_aka_peer_t object
Definition at line 646 of file eap_aka_peer.c.
References identification_t::clone, EAP_AKA, free(), library_t::get, INIT, lib, and simaka_crypto_create().
Referenced by METHOD().
 {
     private_eap_aka_peer_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .destroy = _destroy,
             },
         },
         .crypto = simaka_crypto_create(EAP_AKA),
         .mgr = lib->get(lib, "aka-manager"),
     );
     if (!this->crypto)
     {
         free(this);
         return NULL;
     }
     this->permanent = peer->clone(peer);
     return &this->public;
 }