strongSwan: stream_tcp
stream_tcp
streams
Functions
stream_t * stream_create_tcp (char *uri)
int stream_parse_uri_tcp (char *uri, struct sockaddr *addr)
Detailed Description
Function Documentation
stream_t* stream_create_tcp (char * uri)
Create a stream for TCP sockets.
TCP URIs start with tcp://, followed by a hostname (FQDN or IP), followed by a colon separated port. A full TCP uri looks something like:
tcp://srv.example.com:5555 tcp://0.0.0.0:1234 tcp://[fec2::1]:7654
There is no default port, so a colon after tcp:// is mandatory.
Parameters
uri TCP socket specific URI, must start with "tcp://"
Returns
stream instance, NULL on failure
See header
Definition at line 71 of file stream_tcp.c.
References addr, close, connect, DBG1, DBG_NET, len, socket, stream_create_from_fd(), stream_parse_uri_tcp(), and strerror.
Referenced by METHOD(), and stream_manager_create().
 {
     union {
         struct sockaddr_in in;
         struct sockaddr_in6 in6;
         struct sockaddr sa;
     } addr;
     int fd, len;
     len = stream_parse_uri_tcp(uri, &addr.sa);
     if (len == -1)
     {
         DBG1(DBG_NET, "invalid stream URI: '%s'", uri);
         return NULL;
     }
     fd = socket(addr.sa.sa_family, SOCK_STREAM, 0);
     if (fd < 0)
     {
         DBG1(DBG_NET, "opening socket '%s' failed: %s", uri, strerror(errno));
         return NULL;
     }
     if (connect(fd, &addr.sa, len))
     {
         DBG1(DBG_NET, "connecting to '%s' failed: %s", uri, strerror(errno));
         close(fd);
         return NULL;
     }
     return stream_create_from_fd(fd);
 }
int stream_parse_uri_tcp (char * uri, struct sockaddr * addr)
Helper function to parse a tcp:// URI to a sockaddr
Parameters
uri URI
addr sockaddr, large enough for URI
Returns
length of sockaddr, -1 on error
See header.
Definition at line 26 of file stream_tcp.c.
References host_t::destroy, host_t::get_sockaddr, host_t::get_sockaddr_len, host, host_create_from_dns(), len, memcpy, port, snprintf, and strpfx().
Referenced by stream_create_tcp(), and stream_service_create_tcp().
 {
     char *pos, buf[128];
     host_t *host;
     u_long port;
     int len;
     if (!strpfx(uri, "tcp://"))
     {
         return -1;
     }
     uri += strlen("tcp://");
     pos = strrchr(uri, ':');
     if (!pos)
     {
         return -1;
     }
     if (*uri == '[' && pos > uri && *(pos - 1) == ']')
     {
         /* IPv6 URI */
         snprintf(buf, sizeof(buf), "%.*s", (int)(pos - uri - 2), uri + 1);
     }
     else
     {
         snprintf(buf, sizeof(buf), "%.*s", (int)(pos - uri), uri);
     }
     port = strtoul(pos + 1, &pos, 10);
     if (port == ULONG_MAX || *pos || port > 65535)
     {
         return -1;
     }
     host = host_create_from_dns(buf, AF_UNSPEC, port);
     if (!host)
     {
         return -1;
     }
     len = *host->get_sockaddr_len(host);
     memcpy(addr, host->get_sockaddr(host), len);
     host->destroy(host);
     return len;
 }