strongSwan: tnc_pdp_connections
tnc_pdp_connections
tnc_pdp
Classes
struct tnc_pdp_connections_t
Typedefs
typedef struct
tnc_pdp_connections_t tnc_pdp_connections_t
Functions
tnc_pdp_connections_t * tnc_pdp_connections_create (void)
Detailed Description
Typedef Documentation
typedef struct tnc_pdp_connections_t tnc_pdp_connections_t
Definition at line 24 of file tnc_pdp_connections.h.
Function Documentation
tnc_pdp_connections_t* tnc_pdp_connections_create (void)
Create a tnc_pdp_connections_t instance
Definition at line 286 of file tnc_pdp_connections.c.
References DEFAULT_TIMEOUT, settings_t::get_int, INIT, lib, linked_list_create(), library_t::ns, rwlock_create(), RWLOCK_TYPE_DEFAULT, and library_t::settings.
Referenced by tnc_pdp_create().
 {
     private_tnc_pdp_connections_t *this;
     INIT(this,
         .public = {
             .add = _add,
             .remove = _remove_,
             .get_state = _get_state,
             .unlock = _unlock,
             .destroy = _destroy,
         },
         .list = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .timeout = lib->settings->get_int(lib->settings,
                         "%s.plugins.tnc-pdp.timeout", DEFAULT_TIMEOUT, lib->ns),
     );
     return &this->public;
 }