strongSwan: openssl_crl.c File Reference
openssl_crl.c File Reference
#include "openssl_crl.h"
#include "openssl_util.h"
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <utils/debug.h>
#include <collections/enumerator.h>
#include <credentials/certificates/x509.h>
Classes
struct private_openssl_crl_t
struct crl_enumerator_t
Typedefs
typedef struct
private_openssl_crl_t private_openssl_crl_t
Functions
METHOD (enumerator_t, crl_enumerate, bool, crl_enumerator_t *this, chunk_t *serial, time_t *date, crl_reason_t *reason)
METHOD (crl_t, create_enumerator, enumerator_t *, private_openssl_crl_t *this)
METHOD (crl_t, get_serial, chunk_t, private_openssl_crl_t *this)
METHOD (crl_t, get_authKeyIdentifier, chunk_t, private_openssl_crl_t *this)
METHOD (certificate_t, get_type, certificate_type_t, private_openssl_crl_t *this)
METHOD (certificate_t, get_subject_or_issuer, identification_t *, private_openssl_crl_t *this)
METHOD (certificate_t, has_subject_or_issuer, id_match_t, private_openssl_crl_t *this, identification_t *id)
METHOD (certificate_t, issued_by, bool, private_openssl_crl_t *this, certificate_t *issuer, signature_scheme_t *scheme)
METHOD (certificate_t, get_public_key, public_key_t *, private_openssl_crl_t *this)
METHOD (certificate_t, get_validity, bool, private_openssl_crl_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_openssl_crl_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, equals, bool, private_openssl_crl_t *this, certificate_t *other)
METHOD (certificate_t, get_ref, certificate_t *, private_openssl_crl_t *this)
METHOD (certificate_t, destroy, void, private_openssl_crl_t *this)
static private_openssl_crl_t * create_empty ()
static bool parse_authKeyIdentifier_ext (private_openssl_crl_t *this, X509_EXTENSION *ext)
static bool parse_crlNumber_ext (private_openssl_crl_t *this, X509_EXTENSION *ext)
static bool parse_extensions (private_openssl_crl_t *this)
static bool parse_crl (private_openssl_crl_t *this)
openssl_crl_t * openssl_crl_load (certificate_type_t type, va_list args)
Typedef Documentation
typedef struct private_openssl_crl_t private_openssl_crl_t
Definition at line 49 of file openssl_crl.c.
Function Documentation
static private_openssl_crl_t* create_empty (void) static
Create an empty CRL.
Definition at line 367 of file openssl_crl.c.
References enumerator_create_empty(), INIT, and return_false().
Referenced by openssl_crl_load().
 {
     private_openssl_crl_t *this;
     INIT(this,
         .public = {
             .crl = {
                 .certificate = {
                     .get_type = _get_type,
                     .get_subject = _get_subject_or_issuer,
                     .get_issuer = _get_subject_or_issuer,
                     .has_subject = _has_subject_or_issuer,
                     .has_issuer = _has_subject_or_issuer,
                     .issued_by = _issued_by,
                     .get_public_key = _get_public_key,
                     .get_validity = _get_validity,
                     .get_encoding = _get_encoding,
                     .equals = _equals,
                     .get_ref = _get_ref,
                     .destroy = _destroy,
                 },
                 .get_serial = _get_serial,
                 .get_authKeyIdentifier = _get_authKeyIdentifier,
                 .is_delta_crl = (void*)return_false,
                 .create_delta_crl_uri_enumerator = (void*)enumerator_create_empty,
                 .create_enumerator = _create_enumerator,
             },
         },
         .ref = 1,
     );
     return this;
 }
METHOD (enumerator_t , crl_enumerate , bool , crl_enumerator_t * this, chunk_t * serial, time_t * date, crl_reason_t * reason)
Definition at line 133 of file openssl_crl.c.
References ASN1_ENUMERATED, CRL_REASON_UNSPECIFIED, FALSE, openssl_asn1_str2chunk(), openssl_asn1_to_time(), and TRUE.
 {
     if (this->i < this->num)
     {
         X509_REVOKED *revoked;
         ASN1_ENUMERATED *crlrsn;
         revoked = sk_X509_REVOKED_value(this->stack, this->i);
         if (serial)
         {
             *serial = openssl_asn1_str2chunk(revoked->serialNumber);
         }
         if (date)
         {
             *date = openssl_asn1_to_time(revoked->revocationDate);
         }
         if (reason)
         {
             *reason = CRL_REASON_UNSPECIFIED;
             crlrsn = X509_REVOKED_get_ext_d2i(revoked, NID_crl_reason,
                                               NULL, NULL);
             if (crlrsn)
             {
                 if (ASN1_STRING_type(crlrsn) == V_ASN1_ENUMERATED &&
                     ASN1_STRING_length(crlrsn) == 1)
                 {
                     *reason = *ASN1_STRING_data(crlrsn);
                 }
                 ASN1_STRING_free(crlrsn);
             }
         }
         this->i++;
         return TRUE;
     }
     return FALSE;
 }
METHOD (crl_t , create_enumerator , enumerator_t * , private_openssl_crl_t * this)
Definition at line 171 of file openssl_crl.c.
References destroy(), enumerator_create_empty(), free(), INIT, and crl_enumerator_t::public.
 {
     crl_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_crl_enumerate,
             .destroy = (void*)free,
         },
         .stack = X509_CRL_get_REVOKED(this->crl),
     );
     if (!enumerator->stack)
     {
         free(enumerator);
         return enumerator_create_empty();
     }
     enumerator->num = sk_X509_REVOKED_num(enumerator->stack);
     return &enumerator->public;
 }
METHOD (crl_t , get_serial , chunk_t , private_openssl_crl_t * this)
Definition at line 192 of file openssl_crl.c.
 {
     return this->serial;
 }
METHOD (crl_t , get_authKeyIdentifier , chunk_t , private_openssl_crl_t * this)
Definition at line 198 of file openssl_crl.c.
 {
     return this->authKeyIdentifier;
 }
METHOD (certificate_t , get_type , certificate_type_t , private_openssl_crl_t * this)
Definition at line 204 of file openssl_crl.c.
References CERT_X509_CRL.
 {
     return CERT_X509_CRL;
 }
METHOD (certificate_t , get_subject_or_issuer , identification_t * , private_openssl_crl_t * this)
Definition at line 210 of file openssl_crl.c.
 {
     return this->issuer;
 }
METHOD (certificate_t , has_subject_or_issuer , id_match_t , private_openssl_crl_t * this, identification_t * id)
Definition at line 216 of file openssl_crl.c.
References chunk_equals(), identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, and ID_MATCH_PERFECT.
 {
     if (id->get_type(id) == ID_KEY_ID &&
         chunk_equals(this->authKeyIdentifier, id->get_encoding(id)))
     {
         return ID_MATCH_PERFECT;
     }
     return this->issuer->matches(this->issuer, id);
 }
METHOD (certificate_t , issued_by , bool , private_openssl_crl_t * this, certificate_t * issuer, signature_scheme_t * scheme)
Definition at line 227 of file openssl_crl.c.
References CERT_X509, chunk_equals(), public_key_t::destroy, certificate_t::equals, FALSE, fingerprint, free(), public_key_t::get_fingerprint, x509_t::get_flags, certificate_t::get_public_key, certificate_t::get_subject, certificate_t::get_type, key, KEYID_PUBKEY_SHA1, openssl_asn1_str2chunk(), openssl_i2chunk, chunk_t::ptr, scheme, SIGN_UNKNOWN, valid, public_key_t::verify, and X509_CA.
 {
     chunk_t fingerprint, tbs;
     public_key_t *key;
     x509_t *x509;
     bool valid;
     if (issuer->get_type(issuer) != CERT_X509)
     {
         return FALSE;
     }
     x509 = (x509_t*)issuer;
     if (!(x509->get_flags(x509) & X509_CA))
     {
         return FALSE;
     }
     key = issuer->get_public_key(issuer);
     if (!key)
     {
         return FALSE;
     }
     if (this->authKeyIdentifier.ptr && key)
     {
         if (!key->get_fingerprint(key, KEYID_PUBKEY_SHA1, &fingerprint) ||
             !chunk_equals(fingerprint, this->authKeyIdentifier))
         {
             return FALSE;
         }
     }
     else
     {
         if (!this->issuer->equals(this->issuer, issuer->get_subject(issuer)))
         {
             return FALSE;
         }
     }
     if (this->scheme == SIGN_UNKNOWN)
     {
         return FALSE;
     }
     tbs = openssl_i2chunk(X509_CRL_INFO, this->crl->crl);
     valid = key->verify(key, this->scheme, tbs,
                         openssl_asn1_str2chunk(this->crl->signature));
     free(tbs.ptr);
     key->destroy(key);
     if (valid && scheme)
     {
         *scheme = this->scheme;
     }
     return valid;
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_openssl_crl_t * this)
Definition at line 281 of file openssl_crl.c.
 {
     return NULL;
 }
METHOD (certificate_t , get_validity , bool , private_openssl_crl_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 287 of file openssl_crl.c.
 {
     time_t t = when ? *when : time(NULL);
     if (not_before)
     {
         *not_before = this->thisUpdate;
     }
     if (not_after)
     {
         *not_after = this->nextUpdate;
     }
     return t <= this->nextUpdate;
 }
METHOD (certificate_t , get_encoding , bool , private_openssl_crl_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 304 of file openssl_crl.c.
References CERT_ASN1_DER, chunk_clone, CRED_PART_END, CRED_PART_X509_CRL_ASN1_DER, cred_encoding_t::encode, library_t::encoding, lib, and TRUE.
 {
     if (type == CERT_ASN1_DER)
     {
         *encoding = chunk_clone(this->encoding);
         return TRUE;
     }
     return lib->encoding->encode(lib->encoding, type, NULL, encoding,
                     CRED_PART_X509_CRL_ASN1_DER, this->encoding, CRED_PART_END);
 }
METHOD (certificate_t , equals , bool , private_openssl_crl_t * this, certificate_t * other)
Definition at line 316 of file openssl_crl.c.
References CERT_ASN1_DER, chunk_equals(), encoding, equals(), certificate_t::equals, FALSE, free(), certificate_t::get_encoding, chunk_t::ptr, and TRUE.
 {
     chunk_t encoding;
     bool equal;
     if (&this->public.crl.certificate == other)
     {
         return TRUE;
     }
     if (other->equals == (void*)equals)
     {   /* skip allocation if we have the same implementation */
         return chunk_equals(this->encoding,
                             ((private_openssl_crl_t*)other)->encoding);
     }
     if (!other->get_encoding(other, CERT_ASN1_DER, &encoding))
     {
         return FALSE;
     }
     equal = chunk_equals(this->encoding, encoding);
     free(encoding.ptr);
     return equal;
 }
METHOD (certificate_t , get_ref , certificate_t * , private_openssl_crl_t * this)
Definition at line 340 of file openssl_crl.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.crl.certificate;
 }
METHOD (certificate_t , destroy , void , private_openssl_crl_t * this)
Definition at line 347 of file openssl_crl.c.
References DESTROY_IF, encoding, free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         if (this->crl)
         {
             X509_CRL_free(this->crl);
         }
         DESTROY_IF(this->issuer);
         free(this->authKeyIdentifier.ptr);
         free(this->serial.ptr);
         free(this->encoding.ptr);
         free(this);
     }
 }
static bool parse_authKeyIdentifier_ext (private_openssl_crl_t * this, X509_EXTENSION * ext) static
Parse the authKeyIdentifier extension
Definition at line 403 of file openssl_crl.c.
References chunk_clone, FALSE, free(), keyid(), openssl_asn1_str2chunk(), and TRUE.
Referenced by parse_extensions().
 {
     AUTHORITY_KEYID *keyid;
     keyid = (AUTHORITY_KEYID *)X509V3_EXT_d2i(ext);
     if (keyid)
     {
         free(this->authKeyIdentifier.ptr);
         this->authKeyIdentifier = chunk_clone(
                         openssl_asn1_str2chunk(keyid->keyid));
         AUTHORITY_KEYID_free(keyid);
         return TRUE;
     }
     return FALSE;
 }
static bool parse_crl (private_openssl_crl_t * this) static
Parse a X509 CRL
Definition at line 494 of file openssl_crl.c.
References chunk_equals(), encoding, FALSE, openssl_asn1_known_oid(), openssl_asn1_obj2chunk(), openssl_asn1_to_time(), openssl_x509_name2id(), parse_extensions(), scheme, and signature_scheme_from_oid().
Referenced by openssl_crl_load().
 {
     const unsigned char *ptr = this->encoding.ptr;
     this->crl = d2i_X509_CRL(NULL, &ptr, this->encoding.len);
     if (!this->crl)
     {
         return FALSE;
     }
     if (!chunk_equals(
             openssl_asn1_obj2chunk(this->crl->crl->sig_alg->algorithm),
             openssl_asn1_obj2chunk(this->crl->sig_alg->algorithm)))
     {
         return FALSE;
     }
     this->scheme = signature_scheme_from_oid(openssl_asn1_known_oid(
                                                 this->crl->sig_alg->algorithm));
     this->issuer = openssl_x509_name2id(X509_CRL_get_issuer(this->crl));
     if (!this->issuer)
     {
         return FALSE;
     }
     this->thisUpdate = openssl_asn1_to_time(X509_CRL_get_lastUpdate(this->crl));
     this->nextUpdate = openssl_asn1_to_time(X509_CRL_get_nextUpdate(this->crl));
     return parse_extensions(this);
 }
static bool parse_crlNumber_ext (private_openssl_crl_t * this, X509_EXTENSION * ext) static
Parse the crlNumber extension
Definition at line 423 of file openssl_crl.c.
References chunk_clone, chunk_skip(), FALSE, free(), chunk_t::len, openssl_asn1_str2chunk(), chunk_t::ptr, and TRUE.
Referenced by parse_extensions().
 {
     chunk_t chunk;
     chunk = openssl_asn1_str2chunk(X509_EXTENSION_get_data(ext));
     /* quick and dirty INTEGER unwrap */
     if (chunk.len > 1 && chunk.ptr[0] == V_ASN1_INTEGER &&
         chunk.ptr[1] == chunk.len - 2)
     {
         chunk = chunk_skip(chunk, 2);
         free(this->serial.ptr);
         this->serial = chunk_clone(chunk);
         return TRUE;
     }
     return FALSE;
 }
static bool parse_extensions (private_openssl_crl_t * this) static
Parse X509 CRL extensions
Definition at line 444 of file openssl_crl.c.
References DBG1, DBG_LIB, FALSE, settings_t::get_bool, lib, library_t::ns, ok, parse_authKeyIdentifier_ext(), parse_crlNumber_ext(), library_t::settings, and TRUE.
Referenced by parse_crl().
 {
     bool ok;
     int i, num;
     X509_EXTENSION *ext;
     STACK_OF(X509_EXTENSION) *extensions;
     extensions = this->crl->crl->extensions;
     if (extensions)
     {
         num = sk_X509_EXTENSION_num(extensions);
         for (i = 0; i < num; ++i)
         {
             ext = sk_X509_EXTENSION_value(extensions, i);
             switch (OBJ_obj2nid(X509_EXTENSION_get_object(ext)))
             {
                 case NID_authority_key_identifier:
                     ok = parse_authKeyIdentifier_ext(this, ext);
                     break;
                 case NID_crl_number:
                     ok = parse_crlNumber_ext(this, ext);
                     break;
                 case NID_issuing_distribution_point:
                     /* TODO support of IssuingDistributionPoints */
                     ok = TRUE;
                     break;
                 default:
                     ok = X509_EXTENSION_get_critical(ext) == 0 ||
                          !lib->settings->get_bool(lib->settings,
                                     "%s.x509.enforce_critical", TRUE, lib->ns);
                     if (!ok)
                     {
                         DBG1(DBG_LIB, "found unsupported critical X.509 "
                              "CRL extension");
                     }
                     break;
             }
             if (!ok)
             {
                 return FALSE;
             }
         }
     }
     return TRUE;
 }