strongSwan: nonce generator
nonce generator
tkm
Classes
struct tkm_nonceg_t
Typedefs
typedef struct tkm_nonceg_t tkm_nonceg_t
Functions
tkm_nonceg_t * tkm_nonceg_create ()
Detailed Description
Typedef Documentation
typedef struct tkm_nonceg_t tkm_nonceg_t
Definition at line 25 of file tkm_nonceg.h.
Function Documentation
tkm_nonceg_t* tkm_nonceg_create ()
Creates a tkm_nonceg_t instance.
Returns
created tkm_nonceg_t
Definition at line 96 of file tkm_nonceg.c.
References INIT.
Referenced by main(), START_TEST(), and test_runner_init().
 {
     private_tkm_nonceg_t *this;
     INIT(this,
         .public = {
             .nonce_gen = {
                 .get_nonce = _get_nonce,
                 .allocate_nonce = _allocate_nonce,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public;
 }