strongSwan: dnssec.c File Reference
dnssec.c File Reference
#include <stdio.h>
#include <library.h>
#include <utils/debug.h>
Functions
static void dbg_dnssec (debug_t group, level_t level, char *fmt,...)
int main (int argc, char *argv[])
Variables
static level_t dbg_level = 1
Function Documentation
static void dbg_dnssec (debug_t group, level_t level, char * fmt, ...) static
Definition at line 26 of file dnssec.c.
References dbg_level, fprintf, and vfprintf.
Referenced by main().
 {
     if ((level <= dbg_level) || level <= 1)
     {
         va_list args;
         va_start(args, fmt);
         vfprintf(stderr, fmt, args);
         fprintf(stderr, "\n");
         va_end(args);
     }
 }
int main (int argc, char * argv[])
Definition at line 39 of file dnssec.c.
References BOGUS, resolver_manager_t::create, rr_set_t::create_rr_enumerator, rr_set_t::create_rrsig_enumerator, dbg, dbg_dnssec(), resolver_t::destroy, resolver_response_t::destroy, enumerator_t::enumerate, fprintf, rr_t::get_name, rr_t::get_rdata, resolver_response_t::get_rr_set, resolver_response_t::get_security_state, resolver_response_t::has_data, INDETERMINATE, INSECURE, lib, library_deinit(), library_init(), plugin_loader_t::load, PLUGINS, library_t::plugins, printf, resolver_t::query, resolver_response_t::query_name_exist, library_t::resolver, response, RR_CLASS_IN, RR_TYPE_A, and SECURE.
 {
     resolver_t *resolver;
     resolver_response_t *response;
     enumerator_t *enumerator;
     chunk_t rdata;
     rr_set_t *rrset;
     rr_t *rr;
     library_init(NULL, "dnssec");
     atexit(library_deinit);
     dbg = dbg_dnssec;
     if (!lib->plugins->load(lib->plugins, PLUGINS))
     {
         return 1;
     }
     if (argc != 2)
     {
         fprintf(stderr, "usage: dnssec <name>\n");
         return 1;
     }
     resolver = lib->resolver->create(lib->resolver);
     if (!resolver)
     {
         printf("failed to create a resolver!\n");
         return 1;
     }
     response = resolver->query(resolver, argv[1], RR_CLASS_IN, RR_TYPE_A);
     if (!response)
     {
         printf("no response received!\n");
         resolver->destroy(resolver);
         return 1;
     }
     printf("DNS response:\n");
     if (!response->has_data(response) || !response->query_name_exist(response))
     {
         if (!response->has_data(response))
         {
             printf("  no data in the response\n");
         }
         if (!response->query_name_exist(response))
         {
             printf("  query name does not exist\n");
         }
         response->destroy(response);
         resolver->destroy(resolver);
         return 1;
     }
     printf("  RRs in the response:\n");
     rrset = response->get_rr_set(response);
     if (!rrset)
     {
         printf("    response contains no RRset!\n");
         response->destroy(response);
         resolver->destroy(resolver);
         return 1;
     }
     enumerator = rrset->create_rr_enumerator(rrset);
     while (enumerator->enumerate(enumerator, &rr))
     {
         printf("    name: %s\n", rr->get_name(rr));
     }
     enumerator = rrset->create_rrsig_enumerator(rrset);
     if (enumerator)
     {
         printf("  RRSIGs for the RRset:\n");
         while (enumerator->enumerate(enumerator, &rr))
         {
             rdata = rr->get_rdata(rr);
             printf("    name: %s\n", rr->get_name(rr));
             printf("    RDATA: %#B\n", &rdata);
         }
     }
     printf("  security status of the response: ");
     switch (response->get_security_state(response))
     {
         case SECURE:
             printf("SECURE\n\n");
             break;
         case INSECURE:
             printf("INSECURE\n\n");
             break;
         case BOGUS:
             printf("BOGUS\n\n");
             break;
         case INDETERMINATE:
             printf("INDETERMINATE\n\n");
             break;
     }
     response->destroy(response);
     resolver->destroy(resolver);
     return 0;
 }
Variable Documentation
level_t dbg_level = 1 static
Define debug level
Definition at line 24 of file dnssec.c.
Referenced by dbg_dnssec().