strongSwan: iface.c File Reference
iface.c File Reference
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <linux/if_tun.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
#include "iface.h"
Classes
struct private_iface_t
Typedefs
typedef struct private_iface_t private_iface_t
Functions
bool iface_control (char *name, bool up)
METHOD (iface_t, get_guestif, char *, private_iface_t *this)
METHOD (iface_t, get_hostif, char *, private_iface_t *this)
METHOD (iface_t, add_address, bool, private_iface_t *this, host_t *addr, int bits)
static void compile_address_list (linked_list_t *list, char *address)
static void destroy_address_list (linked_list_t *list)
METHOD (iface_t, create_address_enumerator, enumerator_t *, private_iface_t *this)
METHOD (iface_t, delete_address, bool, private_iface_t *this, host_t *addr, int bits)
METHOD (iface_t, set_bridge, void, private_iface_t *this, bridge_t *bridge)
METHOD (iface_t, get_bridge, bridge_t *, private_iface_t *this)
METHOD (iface_t, get_guest, guest_t *, private_iface_t *this)
static bool destroy_tap (private_iface_t *this)
static char * create_tap (private_iface_t *this)
METHOD (iface_t, destroy, void, private_iface_t *this)
iface_t * iface_create (char *name, guest_t *guest, mconsole_t *mconsole)
Typedef Documentation
typedef struct private_iface_t private_iface_t
Definition at line 33 of file iface.c.
Function Documentation
static void compile_address_list (linked_list_t * list, char * address) static
compile a list of the addresses of an interface
Definition at line 108 of file iface.c.
References host, host_create_from_string(), and linked_list_t::insert_last.
Referenced by METHOD().
 {
     host_t *host = host_create_from_string(address, 0);
     if (host)
     {
         list->insert_last(list, host);
     }
 }
static char* create_tap (private_iface_t * this) static
create the tap device
Definition at line 209 of file iface.c.
References close, DBG1, DBG_LIB, memset, snprintf, strdup, and TAP_DEVICE.
Referenced by iface_create().
 {
     struct ifreq ifr;
     int tap;
     memset(&ifr, 0, sizeof(ifr));
     ifr.ifr_flags = IFF_TAP | IFF_NO_PI;
     snprintf(ifr.ifr_name, sizeof(ifr.ifr_name), "%s-%s",
              this->guest->get_name(this->guest), this->guestif);
     tap = open(TAP_DEVICE, O_RDWR);
     if (tap < 0)
     {
         DBG1(DBG_LIB, "unable to open tap device %s: %m", TAP_DEVICE);
         return NULL;
     }
     if (ioctl(tap, TUNSETIFF, &ifr) < 0 ||
         ioctl(tap, TUNSETPERSIST, 1) < 0 ||
         ioctl(tap, TUNSETOWNER, 0))
     {
         DBG1(DBG_LIB, "creating new tap device failed: %m");
         close(tap);
         return NULL;
     }
     close(tap);
     return strdup(ifr.ifr_name);
 }
static void destroy_address_list (linked_list_t * list) static
delete the list of addresses
Definition at line 120 of file iface.c.
References destroy(), and linked_list_t::destroy_offset.
Referenced by METHOD().
 {
     list->destroy_offset(list, offsetof(host_t, destroy));
 }
static bool destroy_tap (private_iface_t * this) static
destroy the tap device
Definition at line 176 of file iface.c.
References close, DBG1, DBG_LIB, FALSE, iface_control(), memset, TAP_DEVICE, and TRUE.
Referenced by iface_create(), and METHOD().
 {
     struct ifreq ifr;
     int tap;
     if (!iface_control(this->hostif, FALSE))
     {
         DBG1(DBG_LIB, "bringing iface down failed: %m");
     }
     memset(&ifr, 0, sizeof(ifr));
     ifr.ifr_flags = IFF_TAP | IFF_NO_PI;
     strncpy(ifr.ifr_name, this->hostif, sizeof(ifr.ifr_name) - 1);
     tap = open(TAP_DEVICE, O_RDWR);
     if (tap < 0)
     {
         DBG1(DBG_LIB, "unable to open tap device %s: %m", TAP_DEVICE);
         return FALSE;
     }
     if (ioctl(tap, TUNSETIFF, &ifr) < 0 ||
         ioctl(tap, TUNSETPERSIST, 0) < 0)
     {
         DBG1(DBG_LIB, "removing %s failed: %m", this->hostif);
         close(tap);
         return FALSE;
     }
     close(tap);
     return TRUE;
 }
bool iface_control (char * name, bool up)
bring an interface up or down (host side)
Definition at line 53 of file iface.c.
References close, FALSE, good, memset, s, socket, and TRUE.
Referenced by bridge_create(), destroy_tap(), iface_create(), and METHOD().
 {
     int s;
     bool good = FALSE;
     struct ifreq ifr;
     memset(&ifr, 0, sizeof(struct ifreq));
     strncpy(ifr.ifr_name, name, sizeof(ifr.ifr_name));
     s = socket(AF_INET, SOCK_DGRAM, 0);
     if (!s)
     {
         return FALSE;
     }
     if (ioctl(s, SIOCGIFFLAGS, &ifr) == 0)
     {
         if (up)
         {
             ifr.ifr_flags |= IFF_UP;
         }
         else
         {
             ifr.ifr_flags &= ~IFF_UP;
         }
         if (ioctl(s, SIOCSIFFLAGS, &ifr) == 0)
         {
             good = TRUE;
         }
     }
     close(s);
     return good;
 }
iface_t* iface_create (char * name, guest_t * guest, mconsole_t * mconsole)
create the iface instance
Definition at line 256 of file iface.c.
References mconsole_t::add_iface, create_tap(), DBG1, DBG_LIB, destroy_tap(), free(), iface_control(), INIT, strdup, and TRUE.
Referenced by METHOD().
 {
     private_iface_t *this;
     INIT(this,
         .public = {
             .get_hostif = _get_hostif,
             .get_guestif = _get_guestif,
             .add_address = _add_address,
             .create_address_enumerator = _create_address_enumerator,
             .delete_address = _delete_address,
             .set_bridge = _set_bridge,
             .get_bridge = _get_bridge,
             .get_guest = _get_guest,
             .destroy = _destroy,
         },
         .mconsole = mconsole,
         .guestif = strdup(name),
         .guest = guest,
     );
     this->hostif = create_tap(this);
     if (this->hostif == NULL)
     {
         destroy_tap(this);
         free(this->guestif);
         free(this);
         return NULL;
     }
     if (!this->mconsole->add_iface(this->mconsole, this->guestif, this->hostif))
     {
         DBG1(DBG_LIB, "creating interface '%s' in guest failed", this->guestif);
         destroy_tap(this);
         free(this->guestif);
         free(this->hostif);
         free(this);
         return NULL;
     }
     if (!iface_control(this->hostif, TRUE))
     {
         DBG1(DBG_LIB, "bringing iface '%s' up failed: %m", this->hostif);
     }
     return &this->public;
 }
METHOD (iface_t , get_guestif , char * , private_iface_t * this)
Definition at line 86 of file iface.c.
 {
     return this->guestif;
 }
METHOD (iface_t , get_hostif , char * , private_iface_t * this)
Definition at line 92 of file iface.c.
 {
     return this->hostif;
 }
METHOD (iface_t , add_address , bool , private_iface_t * this, host_t * addr, int bits)
Definition at line 98 of file iface.c.
 {
     return (this->guest->exec(this->guest, NULL, NULL,
             "exec ip addr add %H/%d dev %s", addr, bits, this->guestif) == 0);
 }
METHOD (iface_t , create_address_enumerator , enumerator_t * , private_iface_t * this)
Definition at line 125 of file iface.c.
References compile_address_list(), linked_list_t::create_enumerator, destroy_address_list(), enumerator_create_cleaner(), linked_list_create(), and TRUE.
 {
     linked_list_t *addresses = linked_list_create();
     this->guest->exec_str(this->guest, (void(*)(void*,char*))compile_address_list,
             TRUE, addresses,
             "exec ip addr list dev %s scope global | "
             "grep '^ \\+\\(inet6\\? \\)' | "
             "awk -F '( +|/)' '{ print $3 }'", this->guestif);
     return enumerator_create_cleaner(addresses->create_enumerator(addresses),
                     (void(*)(void*))destroy_address_list, addresses);
 }
METHOD (iface_t , delete_address , bool , private_iface_t * this, host_t * addr, int bits)
Definition at line 138 of file iface.c.
 {
     return (this->guest->exec(this->guest, NULL, NULL,
             "exec ip addr del %H/%d dev %s", addr, bits, this->guestif) == 0);
 }
METHOD (iface_t , set_bridge , void , private_iface_t * this, bridge_t * bridge)
Definition at line 145 of file iface.c.
 {
     if (this->bridge == NULL && bridge)
     {
         this->guest->exec(this->guest, NULL, NULL,
                           "exec ip link set %s up", this->guestif);
     }
     else if (this->bridge && bridge == NULL)
     {
         this->guest->exec(this->guest, NULL, NULL,
                           "exec ip link set %s down", this->guestif);
     }
     this->bridge = bridge;
 }
METHOD (iface_t , get_bridge , bridge_t * , private_iface_t * this)
Definition at line 161 of file iface.c.
 {
     return this->bridge;
 }
METHOD (iface_t , get_guest , guest_t * , private_iface_t * this)
Definition at line 167 of file iface.c.
 {
     return this->guest;
 }
METHOD (iface_t , destroy , void , private_iface_t * this)
Definition at line 237 of file iface.c.
References destroy_tap(), free(), and usleep().
 {
     if (this->bridge)
     {
         this->bridge->disconnect_iface(this->bridge, &this->public);
     }
     /* TODO: iface mgmt is not blocking yet, so wait some ticks */
     usleep(50000);
     this->mconsole->del_iface(this->mconsole, this->guestif);
     destroy_tap(this);
     free(this->guestif);
     free(this->hostif);
     free(this);
 }