strongSwan: radius_config
radius_config
libradius
Classes
struct radius_config_t
Typedefs
typedef struct radius_config_t radius_config_t
Functions
radius_config_t * radius_config_create (char *name, char *address, u_int16_t auth_port, u_int16_t acct_port, char *nas_identifier, char *secret, int sockets, int preference, u_int tries, double timeout, double base)
Detailed Description
Typedef Documentation
typedef struct radius_config_t radius_config_t
Definition at line 46 of file radius_config.h.
Function Documentation
radius_config_t* radius_config_create (char * name, char * address, u_int16_t auth_port, u_int16_t acct_port, char * nas_identifier, char * secret, int sockets, int preference, u_int tries, double timeout, double base)
Create a radius_config_t instance.
Parameters
name server name
address server address
auth_port server port for authentication
acct_port server port for accounting
nas_identifier NAS-Identifier to use with this server
secret secret to use with this server
sockets number of sockets to create in pool
preference preference boost for this server
tries number of times we retransmit messages
timeout retransmission timeout
base base to calculate retransmission timeout
See header
Definition at line 202 of file radius_config.c.
References chunk_create(), condvar_create(), CONDVAR_TYPE_DEFAULT, destroy(), INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, name, radius_socket_create(), socket, and TRUE.
Referenced by load_configs().
 {
     private_radius_config_t *this;
     radius_socket_t *socket;
     INIT(this,
         .public = {
             .get_socket = _get_socket,
             .put_socket = _put_socket,
             .get_nas_identifier = _get_nas_identifier,
             .get_preference = _get_preference,
             .get_name = _get_name,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .reachable = TRUE,
         .nas_identifier = chunk_create(nas_identifier, strlen(nas_identifier)),
         .socket_count = sockets,
         .sockets = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .name = name,
         .preference = preference,
         .ref = 1,
     );
     while (sockets--)
     {
         socket = radius_socket_create(address, auth_port, acct_port,
                                       chunk_create(secret, strlen(secret)),
                                       tries, timeout, base);
         if (!socket)
         {
             destroy(this);
             return NULL;
         }
         this->sockets->insert_last(this->sockets, socket);
     }
     return &this->public;
 }