strongSwan: child_cfg_t Struct Reference
child_cfg_t Struct Reference
child_cfg
#include "child_cfg.h"
Public Attributes
char *(* get_name)(child_cfg_t *this)
void(* add_proposal)(child_cfg_t *this, proposal_t *proposal)
linked_list_t *(* get_proposals)(child_cfg_t *this, bool strip_dh)
proposal_t *(* select_proposal)(child_cfg_t *this, linked_list_t *proposals, bool strip_dh, bool private)
void(* add_traffic_selector)(child_cfg_t *this, bool local, traffic_selector_t *ts)
linked_list_t *(* get_traffic_selectors)(child_cfg_t *this, bool local, linked_list_t *supplied, linked_list_t *hosts)
char *(* get_updown)(child_cfg_t *this)
bool(* get_hostaccess)(child_cfg_t *this)
lifetime_cfg_t *(* get_lifetime)(child_cfg_t *this)
ipsec_mode_t(* get_mode)(child_cfg_t *this)
action_t(* get_start_action)(child_cfg_t *this)
action_t(* get_dpd_action)(child_cfg_t *this)
action_t(* get_close_action)(child_cfg_t *this)
diffie_hellman_group_t(* get_dh_group)(child_cfg_t *this)
bool(* use_ipcomp)(child_cfg_t *this)
u_int32_t(* get_inactivity)(child_cfg_t *this)
u_int32_t(* get_reqid)(child_cfg_t *this)
mark_t(* get_mark)(child_cfg_t *this, bool inbound)
u_int32_t(* get_tfc)(child_cfg_t *this)
u_int32_t(* get_replay_window)(child_cfg_t *this)
void(* set_replay_window)(child_cfg_t *this, u_int32_t window)
void(* set_mipv6_options)(child_cfg_t *this, bool proxy_mode, bool install_policy)
bool(* use_proxy_mode)(child_cfg_t *this)
bool(* install_policy)(child_cfg_t *this)
child_cfg_t *(* get_ref)(child_cfg_t *this)
void(* destroy)(child_cfg_t *this)
Detailed Description
A child_cfg_t defines the config template for a CHILD_SA.
After creation, proposals and traffic selectors may be added to the config. A child_cfg object is referenced multiple times, and is not thread save. Reading from the object is save, adding things is not allowed while other threads may access the object. A reference counter handles the number of references hold to this config.
See Also
peer_cfg_t to get an overview over the configurations.
Definition at line 63 of file child_cfg.h.
Member Data Documentation
void(* child_cfg_t::add_proposal)(child_cfg_t *this, proposal_t *proposal)
Add a proposal to the list.
The proposals are stored by priority, first added is the most preferred. It is safe to add NULL as proposal, which has no effect. After add, proposal is owned by child_cfg.
Parameters
proposal proposal to add, or NULL
Definition at line 81 of file child_cfg.h.
Referenced by add_esp_proposals(), add_proposals(), CALLBACK(), connect_(), create_child_cfg(), generate_config(), initiate_connection(), load_child_config(), METHOD(), and setup_tunnel().
void(* child_cfg_t::add_traffic_selector)(child_cfg_t *this, bool local, traffic_selector_t *ts)
Add a traffic selector to the config.
Use the "local" parameter to add it for the local or the remote side. After add, traffic selector is owned by child_cfg.
Parameters
local TRUE for local side, FALSE for remote
ts traffic_selector to add
Definition at line 115 of file child_cfg.h.
Referenced by add_exclude_async(), add_traffic_selectors(), add_ts(), CALLBACK(), connect_(), create_child_cfg(), initiate_connection(), load_child_config(), METHOD(), and setup_tunnel().
void(* child_cfg_t::destroy)(child_cfg_t *this)
Destroys the child_cfg object.
Decrements the internal reference counter and destroys the child_cfg when it reaches zero.
Definition at line 289 of file child_cfg.h.
Referenced by add_exclude_async(), CALLBACK(), delete_child(), destroy_and_reestablish(), METHOD(), replace_children(), and select_child_cfg().
action_t(* child_cfg_t::get_close_action)(child_cfg_t *this)
Action to take if CHILD_SA gets closed.
Returns
close action
Definition at line 191 of file child_cfg.h.
Referenced by child_sa_create().
diffie_hellman_group_t(* child_cfg_t::get_dh_group)(child_cfg_t *this)
Get the DH group to use for CHILD_SA setup.
Returns
dh group to use
Definition at line 198 of file child_cfg.h.
action_t(* child_cfg_t::get_dpd_action)(child_cfg_t *this)
Action to take on DPD.
Returns
DPD action
Definition at line 184 of file child_cfg.h.
Referenced by child_sa_create(), and METHOD().
bool(* child_cfg_t::get_hostaccess)(child_cfg_t *this)
Should we allow access to the local host (gateway)?
Returns
value of hostaccess flag
Definition at line 150 of file child_cfg.h.
Referenced by invoke_once().
u_int32_t(* child_cfg_t::get_inactivity)(child_cfg_t *this)
Get the inactivity timeout value.
Returns
inactivity timeout in s
Definition at line 213 of file child_cfg.h.
lifetime_cfg_t*(* child_cfg_t::get_lifetime)(child_cfg_t *this)
Get the lifetime configuration of a CHILD_SA.
The rekey limits automatically contain a jitter to avoid simultaneous rekeying. These values will change with each call to this function.
Returns
lifetime_cfg_t (has to be freed)
Definition at line 160 of file child_cfg.h.
mark_t(* child_cfg_t::get_mark)(child_cfg_t *this, bool inbound)
Optional mark for CHILD_SA.
Parameters
inbound TRUE for inbound, FALSE for outbound
Returns
mark
Definition at line 228 of file child_cfg.h.
Referenced by child_sa_create(), install_shunt_policy(), invoke_once(), and uninstall_shunt_policy().
ipsec_mode_t(* child_cfg_t::get_mode)(child_cfg_t *this)
Get the mode to use for the CHILD_SA.
The mode is either tunnel, transport or BEET. The peer must agree on the method, fallback is tunnel mode.
Returns
ipsec mode
Definition at line 170 of file child_cfg.h.
Referenced by CALLBACK(), charon_route(), clear_start_action(), install_shunt_policy(), METHOD(), raise_policy_cfg(), run_start_action(), select_child_cfg(), and uninstall_shunt_policy().
char*(* child_cfg_t::get_name)(child_cfg_t *this)
Get the name of the child_cfg.
Returns
child_cfg's name
Definition at line 70 of file child_cfg.h.
Referenced by CALLBACK(), clear_start_action(), find_child_cfg(), find_reqid(), get_child_from_peer(), invoke_once(), METHOD(), raise_policy_cfg(), request_control_initiate(), request_query_config(), run_start_action(), uninstall_shunt_policy(), and write_child().
linked_list_t*(* child_cfg_t::get_proposals)(child_cfg_t *this, bool strip_dh)
Get the list of proposals for the CHILD_SA.
Resulting list and all of its proposals must be freed after use.
Parameters
strip_dh TRUE strip out diffie hellman groups
Returns
list of proposals
Definition at line 91 of file child_cfg.h.
Referenced by METHOD().
child_cfg_t*(* child_cfg_t::get_ref)(child_cfg_t *this)
Increase the reference count.
Returns
reference to this
Definition at line 281 of file child_cfg.h.
Referenced by child_sa_create(), connect_(), create_child_cfg(), delete_child(), destroy_and_reestablish(), do_load_test(), get_child_from_peer(), initiate(), initiate_config(), initiate_connection(), METHOD(), on_accept(), request_control_initiate(), run_start_action(), and trigger_mbb_reauth().
u_int32_t(* child_cfg_t::get_replay_window)(child_cfg_t *this)
Get anti-replay window size
Returns
anti-replay window size
Definition at line 242 of file child_cfg.h.
u_int32_t(* child_cfg_t::get_reqid)(child_cfg_t *this)
Specific reqid to use for CHILD_SA.
Returns
reqid
Definition at line 220 of file child_cfg.h.
Referenced by child_sa_create(), and get_remote_identity_id().
action_t(* child_cfg_t::get_start_action)(child_cfg_t *this)
Action to take to start CHILD_SA.
Returns
start action
Definition at line 177 of file child_cfg.h.
Referenced by clear_start_action(), METHOD(), and run_start_action().
u_int32_t(* child_cfg_t::get_tfc)(child_cfg_t *this)
Get the TFC padding value to use for CHILD_SA.
Returns
TFC padding, 0 to disable, -1 for MTU
Definition at line 235 of file child_cfg.h.
linked_list_t*(* child_cfg_t::get_traffic_selectors)(child_cfg_t *this, bool local, linked_list_t *supplied, linked_list_t *hosts)
Get a list of traffic selectors to use for the CHILD_SA.
The config contains two set of traffic selectors, one for the local side, one for the remote side. If a list with traffic selectors is supplied, these are used to narrow down the traffic selector list to the greatest common divisor. Some traffic selector may be "dymamic", meaning they are narrowed down to a specific address (host-to-host or virtual-IP setups). Use the "host" parameter to narrow such traffic selectors to that address. Resulted list and its traffic selectors must be destroyed after use.
Parameters
local TRUE for TS on local side, FALSE for remote
supplied list with TS to select from, or NULL
hosts addresses to use for narrowing "dynamic" TS', host_t
Returns
list containing the traffic selectors
Definition at line 135 of file child_cfg.h.
Referenced by CALLBACK(), get_proxy_addr(), get_ts_match(), install_shunt_policy(), METHOD(), narrow_responder_post(), narrow_ts(), raise_policy_cfg(), request_query_config(), and uninstall_shunt_policy().
char*(* child_cfg_t::get_updown)(child_cfg_t *this)
Get the updown script to run for the CHILD_SA.
Returns
path to updown script
Definition at line 143 of file child_cfg.h.
Referenced by invoke_once(), and METHOD().
bool(* child_cfg_t::install_policy)(child_cfg_t *this)
Check whether IPsec policies should be installed in the kernel.
Returns
TRUE, if IPsec kernel policies should be installed FALSE, otherwise
Definition at line 274 of file child_cfg.h.
proposal_t*(* child_cfg_t::select_proposal)(child_cfg_t *this, linked_list_t *proposals, bool strip_dh, bool private)
Select a proposal from a supplied list.
Returned propsal is newly created and must be destroyed after usage.
Parameters
proposals list from which proposals are selected
strip_dh TRUE strip out diffie hellman groups
private accept algorithms from a private range
Returns
selected proposal, or NULL if nothing matches
Definition at line 103 of file child_cfg.h.
void(* child_cfg_t::set_mipv6_options)(child_cfg_t *this, bool proxy_mode, bool install_policy)
Sets two options needed for Mobile IPv6 interoperability.
Parameters
proxy_mode use IPsec transport proxy mode (default FALSE)
install_policy install IPsec kernel policies (default TRUE)
Definition at line 257 of file child_cfg.h.
Referenced by build_child_cfg(), and CALLBACK().
void(* child_cfg_t::set_replay_window)(child_cfg_t *this, u_int32_t window)
Set anti-replay window size
Parameters
window anti-replay window size
Definition at line 249 of file child_cfg.h.
Referenced by build_child_cfg(), and CALLBACK().
bool(* child_cfg_t::use_ipcomp)(child_cfg_t *this)
Check whether IPComp should be used, if the other peer supports it.
Returns
TRUE, if IPComp should be used FALSE, otherwise
Definition at line 206 of file child_cfg.h.
bool(* child_cfg_t::use_proxy_mode)(child_cfg_t *this)
Check whether IPsec transport SA should be set up in proxy mode.
Returns
TRUE, if proxy mode should be used FALSE, otherwise
Definition at line 266 of file child_cfg.h.
Referenced by log_child_sa().
The documentation for this struct was generated from the following file:
child_cfg.h