strongSwan: android_dns_plugin.c File Reference
android_dns_plugin.c File Reference
#include "android_dns_plugin.h"
#include "android_dns_handler.h"
#include <daemon.h>
Classes
struct private_android_dns_plugin_t
Typedefs
typedef struct
private_android_dns_plugin_t private_android_dns_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_android_dns_plugin_t *this)
static bool plugin_cb (private_android_dns_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_android_dns_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_android_dns_plugin_t *this)
plugin_t * android_dns_plugin_create ()
Typedef Documentation
typedef struct private_android_dns_plugin_t private_android_dns_plugin_t
Definition at line 21 of file android_dns_plugin.c.
Function Documentation
plugin_t* android_dns_plugin_create ()
See header
Definition at line 85 of file android_dns_plugin.c.
References android_dns_handler_create(), and INIT.
 {
     private_android_dns_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .handler = android_dns_handler_create(),
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_android_dns_plugin_t * this)
Definition at line 39 of file android_dns_plugin.c.
 {
     return "android-dns";
 }
METHOD (plugin_t , get_features , int , private_android_dns_plugin_t * this, plugin_feature_t * features[])
Definition at line 64 of file android_dns_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "android-dns"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_android_dns_plugin_t * this)
Definition at line 75 of file android_dns_plugin.c.
References free().
 {
     this->handler->destroy(this->handler);
     free(this);
 }
static bool plugin_cb (private_android_dns_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register handler
Definition at line 48 of file android_dns_plugin.c.
References attribute_manager_t::add_handler, daemon_t::attributes, charon, attribute_manager_t::remove_handler, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->attributes->add_handler(charon->attributes,
                                         &this->handler->handler);
     }
     else
     {
         charon->attributes->remove_handler(charon->attributes,
                                            &this->handler->handler);
     }
     return TRUE;
 }