strongSwan: child_sa_t Struct Reference
child_sa_t Struct Reference
child_sa
#include "child_sa.h"
Public Attributes
char *(* get_name)(child_sa_t *this)
u_int32_t(* get_reqid)(child_sa_t *this)
u_int32_t(* get_unique_id)(child_sa_t *this)
child_cfg_t *(* get_config)(child_sa_t *this)
child_sa_state_t(* get_state)(child_sa_t *this)
void(* set_state)(child_sa_t *this, child_sa_state_t state)
u_int32_t(* get_spi)(child_sa_t *this, bool inbound)
u_int16_t(* get_cpi)(child_sa_t *this, bool inbound)
protocol_id_t(* get_protocol)(child_sa_t *this)
void(* set_protocol)(child_sa_t *this, protocol_id_t protocol)
ipsec_mode_t(* get_mode)(child_sa_t *this)
void(* set_mode)(child_sa_t *this, ipsec_mode_t mode)
ipcomp_transform_t(* get_ipcomp)(child_sa_t *this)
void(* set_ipcomp)(child_sa_t *this, ipcomp_transform_t ipcomp)
action_t(* get_close_action)(child_sa_t *this)
void(* set_close_action)(child_sa_t *this, action_t action)
action_t(* get_dpd_action)(child_sa_t *this)
void(* set_dpd_action)(child_sa_t *this, action_t action)
proposal_t *(* get_proposal)(child_sa_t *this)
void(* set_proposal)(child_sa_t *this, proposal_t *proposal)
bool(* has_encap)(child_sa_t *this)
time_t(* get_lifetime)(child_sa_t *this, bool hard)
time_t(* get_installtime)(child_sa_t *this)
void(* get_usestats)(child_sa_t *this, bool inbound, time_t *time, u_int64_t *bytes, u_int64_t *packets)
mark_t(* get_mark)(child_sa_t *this, bool inbound)
enumerator_t *(* create_ts_enumerator)(child_sa_t *this, bool local)
enumerator_t *(* create_policy_enumerator)(child_sa_t *this)
u_int32_t(* alloc_spi)(child_sa_t *this, protocol_id_t protocol)
u_int16_t(* alloc_cpi)(child_sa_t *this)
status_t(* install)(child_sa_t *this, chunk_t encr, chunk_t integ, u_int32_t spi, u_int16_t cpi, bool initiator, bool inbound, bool tfcv3, linked_list_t *my_ts, linked_list_t *other_ts)
status_t(* add_policies)(child_sa_t *this, linked_list_t *my_ts_list, linked_list_t *other_ts_list)
status_t(* update)(child_sa_t *this, host_t *me, host_t *other, linked_list_t *vips, bool encap)
void(* destroy)(child_sa_t *this)
Detailed Description
Represents an IPsec SAs between two hosts.
A child_sa_t contains two SAs. SAs for both directions are managed in one child_sa_t object. Both SAs and the policies have the same reqid.
The procedure for child sa setup is as follows:
A gets SPIs for a all protocols in its proposals via child_sa_t.alloc
A send the proposals with the allocated SPIs to B
B selects a suitable proposal
B allocates an SPI for the selected protocol
B calls child_sa_t.install for both, the allocated and received SPI
B sends the proposal with the allocated SPI to A
A calls child_sa_t.install for both, the allocated and recevied SPI
Once SAs are set up, policies can be added using add_policies.
Definition at line 114 of file child_sa.h.
Member Data Documentation
status_t(* child_sa_t::add_policies)(child_sa_t *this, linked_list_t *my_ts_list, linked_list_t *other_ts_list)
Install the policies using some traffic selectors.
Supplied lists of traffic_selector_t's specify the policies to use for this child sa.
Parameters
my_ts traffic selectors for local site
other_ts traffic selectors for remote site
Returns
SUCCESS or FAILED
Definition at line 375 of file child_sa.h.
Referenced by METHOD(), and process_child_add().
u_int16_t(* child_sa_t::alloc_cpi)(child_sa_t *this)
Allocate a CPI to use for IPComp.
Returns
CPI, 0 on failure
Definition at line 345 of file child_sa.h.
u_int32_t(* child_sa_t::alloc_spi)(child_sa_t *this, protocol_id_t protocol)
Allocate an SPI to include in a proposal.
Parameters
protocol protocol to allocate SPI for (ESP|AH)
spi SPI output pointer
Returns
SPI, 0 on failure
Definition at line 338 of file child_sa.h.
enumerator_t*(* child_sa_t::create_policy_enumerator)(child_sa_t *this)
Create an enumerator over installed policies.
The enumerated traffic selectors is a full mesh of compatible local and remote traffic selectors.
Returns
enumerator over a pair of traffic_selector_t*
Definition at line 329 of file child_sa.h.
Referenced by check_for_rekeyed_child(), manage_policies(), and METHOD().
enumerator_t*(* child_sa_t::create_ts_enumerator)(child_sa_t *this, bool local)
Create an enumerator over traffic selectors of one side.
Parameters
local TRUE for own traffic selectors, FALSE for remote.
Returns
enumerator over traffic_selector_t*
Definition at line 319 of file child_sa.h.
Referenced by add_entry(), delete_child(), get_first_ts(), have_equal_ts(), list_child(), log_child_sa(), log_children(), METHOD(), raise_policy(), status(), and write_childend().
void(* child_sa_t::destroy)(child_sa_t *this)
Destroys a child_sa.
Definition at line 391 of file child_sa.h.
Referenced by METHOD(), and process_child_add().
action_t(* child_sa_t::get_close_action)(child_sa_t *this)
Get the action to enforce if the remote peer closes the CHILD_SA.
Returns
close action
Definition at line 235 of file child_sa.h.
Referenced by delete_child(), destroy_and_reestablish(), and METHOD().
child_cfg_t*(* child_sa_t::get_config)(child_sa_t *this)
Get the config used to set up this child sa.
Returns
child_cfg
Definition at line 148 of file child_sa.h.
Referenced by delete_child(), destroy_and_reestablish(), log_child_sa(), METHOD(), trigger_mbb_reauth(), and write_child().
u_int16_t(* child_sa_t::get_cpi)(child_sa_t *this, bool inbound)
Get the CPI of this CHILD_SA.
Set the boolean parameter inbound to TRUE to get the CPI for which we receive packets, use FALSE to get those we use for sending packets.
Parameters
inbound TRUE to get inbound CPI, FALSE for outbound.
Returns
CPI of the CHILD SA
Definition at line 186 of file child_sa.h.
Referenced by list_child(), log_child_sa(), and METHOD().
action_t(* child_sa_t::get_dpd_action)(child_sa_t *this)
Get the action to enforce if the peer is considered dead.
Returns
dpd action
Definition at line 249 of file child_sa.h.
Referenced by METHOD().
time_t(* child_sa_t::get_installtime)(child_sa_t *this)
Get the absolute time when this SA has been installed.
Returns
monotonic absolute install time
Definition at line 292 of file child_sa.h.
Referenced by list_child(), and METHOD().
ipcomp_transform_t(* child_sa_t::get_ipcomp)(child_sa_t *this)
Get the used IPComp algorithm.
Returns
IPComp compression algorithm.
Definition at line 221 of file child_sa.h.
Referenced by invoke_once(), list_child(), log_child_sa(), and METHOD().
time_t(* child_sa_t::get_lifetime)(child_sa_t *this, bool hard)
Get the absolute time when the CHILD_SA expires or gets rekeyed.
Parameters
hard TRUE for hard lifetime, FALSE for soft (rekey) lifetime
Returns
absolute time
Definition at line 285 of file child_sa.h.
Referenced by is_redundant(), list_child(), and log_child_sa().
mark_t(* child_sa_t::get_mark)(child_sa_t *this, bool inbound)
Get the mark used with this CHILD_SA.
Parameters
inbound TRUE to get inbound mark, FALSE for outbound
Returns
mark used with this CHILD_SA
Definition at line 311 of file child_sa.h.
Referenced by add_entry(), check_for_rekeyed_child(), handle_sa(), manage_policies(), METHOD(), and remove_entry().
ipsec_mode_t(* child_sa_t::get_mode)(child_sa_t *this)
Get the IPsec mode of this CHILD_SA.
Returns
TUNNEL | TRANSPORT | BEET
Definition at line 207 of file child_sa.h.
Referenced by handle_sa(), list_child(), log_child_sa(), METHOD(), and raise_policy().
char*(* child_sa_t::get_name)(child_sa_t *this)
Get the name of the config this CHILD_SA uses.
Returns
name
Definition at line 121 of file child_sa.h.
Referenced by add_entry(), CALLBACK(), check_for_rekeyed_child(), clear_start_action(), close_child(), delete_child(), find_reqid(), is_redundant(), log_child_sa(), log_children(), METHOD(), process_child_add(), raise_policy(), and rekey_child().
proposal_t*(* child_sa_t::get_proposal)(child_sa_t *this)
Get the selected proposal.
Returns
selected proposal
Definition at line 263 of file child_sa.h.
Referenced by check_for_rekeyed_child(), list_child(), log_child_sa(), and METHOD().
protocol_id_t(* child_sa_t::get_protocol)(child_sa_t *this)
Get the protocol which this CHILD_SA uses to protect traffic.
Returns
AH | ESP
Definition at line 193 of file child_sa.h.
Referenced by build_payloads(), destroy_and_reestablish(), handle_sa(), invoke_once(), list_child(), log_child_sa(), METHOD(), rekey_child(), rekey_children(), and update_children().
u_int32_t(* child_sa_t::get_reqid)(child_sa_t *this)
Get the reqid of the CHILD SA.
Every CHILD_SA has a reqid. The kernel uses this ID to identify it.
Returns
reqid of the CHILD SA
Definition at line 131 of file child_sa.h.
Referenced by CALLBACK(), check_for_rekeyed_child(), clear_start_action(), complete(), delete_child(), destroy_and_reestablish(), find_reqid(), invoke_once(), list_child(), log_child_sa(), METHOD(), and write_child().
u_int32_t(* child_sa_t::get_spi)(child_sa_t *this, bool inbound)
Get the SPI of this CHILD_SA.
Set the boolean parameter inbound to TRUE to get the SPI for which we receive packets, use FALSE to get those we use for sending packets.
Parameters
inbound TRUE to get inbound SPI, FALSE for outbound.
Returns
SPI of the CHILD SA
Definition at line 174 of file child_sa.h.
Referenced by add_entry(), build_payloads(), check_for_rekeyed_child(), delete_child(), destroy_and_reestablish(), list_child(), log_child_sa(), log_children(), manage_policies(), METHOD(), rekey_child(), rekey_children(), update_children(), and write_childend().
child_sa_state_t(* child_sa_t::get_state)(child_sa_t *this)
Get the state of the CHILD_SA.
Returns
CHILD_SA state
Definition at line 155 of file child_sa.h.
Referenced by check_for_rekeyed_child(), delete_child(), get_retry_delay(), is_redundant(), list_child(), log_child_sa(), METHOD(), and process_payloads().
u_int32_t(* child_sa_t::get_unique_id)(child_sa_t *this)
Get the unique numerical identifier for this CHILD_SA.
While the same reqid might be shared between multiple SAs, the unique_id is truly unique for all CHILD_SA instances.
Returns
unique CHILD_SA identifier
Definition at line 141 of file child_sa.h.
Referenced by CALLBACK(), check_for_rekeyed_child(), checkout_ikesa(), cleanup_sas(), clear_start_action(), close_child(), collect_stats(), delete_child(), is_redundant(), list_child(), log_child_sa(), log_children(), METHOD(), process_child_add(), and update_usage().
void(* child_sa_t::get_usestats)(child_sa_t *this, bool inbound, time_t *time, u_int64_t *bytes, u_int64_t *packets)
Get last use time and the number of bytes processed.
Parameters
inbound TRUE for inbound traffic, FALSE for outbound
[out] time time of last use in seconds (NULL to ignore)
[out] bytes number of processed bytes (NULL to ignore)
[out] packets number of processed packets (NULL to ignore)
Definition at line 302 of file child_sa.h.
Referenced by collect_stats(), delete_child(), get_use_time(), list_child(), log_child_sa(), log_children(), METHOD(), and update_usage().
bool(* child_sa_t::has_encap)(child_sa_t *this)
Check if this CHILD_SA uses UDP encapsulation.
Returns
TRUE if SA encapsulates ESP packets
Definition at line 277 of file child_sa.h.
Referenced by list_child(), log_child_sa(), and METHOD().
status_t(* child_sa_t::install)(child_sa_t *this, chunk_t encr, chunk_t integ, u_int32_t spi, u_int16_t cpi, bool initiator, bool inbound, bool tfcv3, linked_list_t *my_ts, linked_list_t *other_ts)
Install an IPsec SA for one direction.
Parameters
encr encryption key, if any
integ integrity key
spi SPI to use, allocated for inbound
cpi CPI to use, allocated for outbound
initiator TRUE if initiator of exchange resulting in this SA
inbound TRUE to install an inbound SA, FALSE for outbound
tfcv3 TRUE if peer supports ESPv3 TFC
my_ts negotiated local traffic selector list
other_ts negotiated remote traffic selector list
Returns
SUCCESS or FAILED
Definition at line 361 of file child_sa.h.
Referenced by process_child_add().
void(* child_sa_t::set_close_action)(child_sa_t *this, action_t action)
Override the close action specified by the CHILD_SA config.
Parameters
close action to enforce
Definition at line 242 of file child_sa.h.
Referenced by handle_collision().
void(* child_sa_t::set_dpd_action)(child_sa_t *this, action_t action)
Override the DPD action specified by the CHILD_SA config.
Parameters
dpd action to enforce
Definition at line 256 of file child_sa.h.
void(* child_sa_t::set_ipcomp)(child_sa_t *this, ipcomp_transform_t ipcomp)
Set the IPComp algorithm to use.
Parameters
ipcomp the IPComp transform to use
Definition at line 228 of file child_sa.h.
Referenced by process_child_add().
void(* child_sa_t::set_mode)(child_sa_t *this, ipsec_mode_t mode)
Set the negotiated IPsec mode to use.
Parameters
mode TUNNEL | TRANPORT | BEET
Definition at line 214 of file child_sa.h.
Referenced by METHOD(), and process_child_add().
void(* child_sa_t::set_proposal)(child_sa_t *this, proposal_t *proposal)
Set the negotiated proposal.
Parameters
proposal selected proposal
Definition at line 270 of file child_sa.h.
Referenced by install(), and process_child_add().
void(* child_sa_t::set_protocol)(child_sa_t *this, protocol_id_t protocol)
Set the negotiated protocol to use for this CHILD_SA.
Parameters
protocol AH | ESP
Definition at line 200 of file child_sa.h.
Referenced by METHOD(), and process_child_add().
void(* child_sa_t::set_state)(child_sa_t *this, child_sa_state_t state)
Set the state of the CHILD_SA.
Parameters
state state to set on CHILD_SA
Definition at line 162 of file child_sa.h.
Referenced by build_payloads(), check_for_rekeyed_child(), delete_child(), install(), METHOD(), and process_child_add().
status_t(* child_sa_t::update)(child_sa_t *this, host_t *me, host_t *other, linked_list_t *vips, bool encap)
Update hosts and ecapulation mode in the kernel SAs and policies.
Parameters
me the new local host
other the new remote host
vips list of local virtual IPs
encap TRUE to use UDP encapsulation for NAT traversal
Returns
SUCCESS or FAILED
Definition at line 386 of file child_sa.h.
Referenced by METHOD(), and update_children().
The documentation for this struct was generated from the following file:
child_sa.h