strongSwan: pkcs11_public_key.c File Reference
pkcs11_public_key.c File Reference
#include "pkcs11_public_key.h"
#include "pkcs11.h"
#include "pkcs11_private_key.h"
#include "pkcs11_manager.h"
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <utils/debug.h>
Classes
struct private_pkcs11_public_key_t
Macros
#define PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM 2
#define PKINFO_SUBJECT_PUBLIC_KEY_NAMEDCURVE 3
#define PKINFO_SUBJECT_PUBLIC_KEY 4
Typedefs
typedef struct
private_pkcs11_public_key_t private_pkcs11_public_key_t
Functions
static size_t basepoint_order_len (int oid)
static bool keylen_from_ecparams (chunk_t ecparams, size_t *keylen)
static bool parse_ecdsa_public_key (chunk_t blob, chunk_t *ecparams, chunk_t *ecpoint, size_t *keylen)
METHOD (public_key_t, get_type, key_type_t, private_pkcs11_public_key_t *this)
METHOD (public_key_t, get_keysize, int, private_pkcs11_public_key_t *this)
METHOD (public_key_t, verify, bool, private_pkcs11_public_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t sig)
METHOD (public_key_t, encrypt, bool, private_pkcs11_public_key_t *this, encryption_scheme_t scheme, chunk_t plain, chunk_t *crypt)
static bool encode_ecdsa (private_pkcs11_public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
static bool fingerprint_ecdsa (private_pkcs11_public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
static bool encode_rsa (private_pkcs11_public_key_t *this, cred_encoding_type_t type, void *cache, chunk_t *encoding)
METHOD (public_key_t, get_encoding, bool, private_pkcs11_public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (public_key_t, get_fingerprint, bool, private_pkcs11_public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (public_key_t, get_ref, public_key_t *, private_pkcs11_public_key_t *this)
METHOD (public_key_t, destroy, void, private_pkcs11_public_key_t *this)
static
private_pkcs11_public_key_t * create (key_type_t type, size_t k, pkcs11_library_t *p11, CK_SLOT_ID slot, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE object)
static
private_pkcs11_public_key_t * find_key (key_type_t type, size_t keylen, CK_ATTRIBUTE_PTR tmpl, int count)
static
private_pkcs11_public_key_t * find_rsa_key (chunk_t n, chunk_t e, size_t keylen)
static
private_pkcs11_public_key_t * find_ecdsa_key (chunk_t ecparams, chunk_t ecpoint, size_t keylen)
static
private_pkcs11_public_key_t * create_key (key_type_t type, size_t keylen, CK_MECHANISM_TYPE_PTR mechanisms, int mcount, CK_ATTRIBUTE_PTR tmpl, int count)
static
private_pkcs11_public_key_t * create_rsa_key (chunk_t n, chunk_t e, size_t keylen)
static
private_pkcs11_public_key_t * create_ecdsa_key (chunk_t ecparams, chunk_t ecpoint, size_t keylen)
pkcs11_public_key_t * pkcs11_public_key_load (key_type_t type, va_list args)
static
private_pkcs11_public_key_t * find_key_by_keyid (pkcs11_library_t *p11, int slot, key_type_t key_type, chunk_t keyid)
public_key_t * pkcs11_public_key_connect (pkcs11_library_t *p11, int slot, key_type_t type, chunk_t keyid)
Variables
static const asn1Object_t pkinfoObjects []
Macro Definition Documentation
#define PKINFO_SUBJECT_PUBLIC_KEY 4
Definition at line 133 of file pkcs11_public_key.c.
Referenced by parse_ecdsa_public_key().
#define PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM 2
Definition at line 131 of file pkcs11_public_key.c.
Referenced by parse_ecdsa_public_key().
#define PKINFO_SUBJECT_PUBLIC_KEY_NAMEDCURVE 3
Definition at line 132 of file pkcs11_public_key.c.
Referenced by parse_ecdsa_public_key().
Typedef Documentation
typedef struct private_pkcs11_public_key_t private_pkcs11_public_key_t
Definition at line 30 of file pkcs11_public_key.c.
Function Documentation
static size_t basepoint_order_len (int oid) static
Helper function that returns the base point order length in bits of the given named curve.
Currently only a subset of defined curves is supported (namely the 5 curves over Fp recommended by NIST). IKEv2 only supports 3 out of these.
0 is returned if the given curve is not supported.
Definition at line 87 of file pkcs11_public_key.c.
References OID_PRIME192V1, OID_PRIME256V1, OID_SECT224R1, OID_SECT384R1, and OID_SECT521R1.
Referenced by keylen_from_ecparams().
 {
     switch (oid)
     {
         case OID_PRIME192V1:
             return 192;
         case OID_SECT224R1:
             return 224;
         case OID_PRIME256V1:
             return 256;
         case OID_SECT384R1:
             return 384;
         case OID_SECT521R1:
             return 521;
         default:
             return 0;
     }
 }
static private_pkcs11_public_key_t* create (key_type_t type, size_t k, pkcs11_library_t * p11, CK_SLOT_ID slot, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE object) static
Create an empty PKCS#11 public key
Definition at line 514 of file pkcs11_public_key.c.
References INIT, public_key_equals(), public_key_has_fingerprint(), and type.
Referenced by create_key(), find_key(), and find_key_by_keyid().
 {
     private_pkcs11_public_key_t *this;
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .verify = _verify,
                 .encrypt = _encrypt,
                 .equals = public_key_equals,
                 .get_keysize = _get_keysize,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = public_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .type = type,
         .k = k,
         .lib = p11,
         .slot = slot,
         .session = session,
         .object = object,
         .ref = 1,
     );
     return this;
 }
static private_pkcs11_public_key_t* create_ecdsa_key (chunk_t ecparams, chunk_t ecpoint, size_t keylen) static
Create an ECDSA key object in a suitable token session
Definition at line 741 of file pkcs11_public_key.c.
References CKA_CLASS, CKA_EC_PARAMS, CKA_EC_POINT, CKA_KEY_TYPE, CKK_ECDSA, CKM_ECDSA, CKM_ECDSA_SHA1, CKO_PUBLIC_KEY, countof, create_key(), KEY_ECDSA, chunk_t::len, mechs, chunk_t::ptr, and type.
Referenced by pkcs11_public_key_load().
 {
     CK_OBJECT_CLASS class = CKO_PUBLIC_KEY;
     CK_KEY_TYPE type = CKK_ECDSA;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_KEY_TYPE, &type, sizeof(type)},
         {CKA_EC_PARAMS, ecparams.ptr, ecparams.len},
         {CKA_EC_POINT, ecpoint.ptr, ecpoint.len},
     };
     CK_MECHANISM_TYPE mechs[] = {
         CKM_ECDSA,
         CKM_ECDSA_SHA1,
     };
     return create_key(KEY_ECDSA, keylen, mechs,
                       countof(mechs), tmpl, countof(tmpl));
 }
static private_pkcs11_public_key_t* create_key (key_type_t type, size_t keylen, CK_MECHANISM_TYPE_PTR mechanisms, int mcount, CK_ATTRIBUTE_PTR tmpl, int count) static
Create a key object in a suitable token session
Definition at line 632 of file pkcs11_public_key.c.
References ck_function_list::C_CloseSession, ck_function_list::C_CreateObject, ck_function_list::C_OpenSession, ck_rv_names, CKF_SERIAL_SESSION, CKF_VERIFY, CKR_OK, create(), pkcs11_library_t::create_mechanism_enumerator, pkcs11_manager_t::create_token_enumerator, DBG1, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, pkcs11_library_t::f, FALSE, ck_mechanism_info::flags, found, library_t::get, pkcs11_library_t::get_name, key_type_names, lib, mechs, and TRUE.
Referenced by create_ecdsa_key(), and create_rsa_key().
 {
     private_pkcs11_public_key_t *this = NULL;
     pkcs11_manager_t *manager;
     enumerator_t *enumerator, *mechs;
     pkcs11_library_t *p11;
     CK_SLOT_ID slot;
     manager = lib->get(lib, "pkcs11-manager");
     if (!manager)
     {
         return NULL;
     }
     enumerator = manager->create_token_enumerator(manager);
     while (enumerator->enumerate(enumerator, &p11, &slot))
     {
         CK_MECHANISM_TYPE mech;
         CK_MECHANISM_INFO info;
         CK_OBJECT_HANDLE object;
         CK_SESSION_HANDLE session;
         CK_RV rv;
         mechs = p11->create_mechanism_enumerator(p11, slot);
         while (mechs->enumerate(mechs, &mech, &info))
         {
             bool found = FALSE;
             int i;
             if (!(info.flags & CKF_VERIFY))
             {
                 continue;
             }
             for (i = 0; i < mcount; i++)
             {
                 if (mechanisms[i] == mech)
                 {
                     found = TRUE;
                     break;
                 }
             }
             if (!found)
             {
                 continue;
             }
             rv = p11->f->C_OpenSession(slot, CKF_SERIAL_SESSION, NULL, NULL,
                                        &session);
             if (rv != CKR_OK)
             {
                 DBG1(DBG_CFG, "opening PKCS#11 session failed: %N",
                      ck_rv_names, rv);
                 continue;
             }
             rv = p11->f->C_CreateObject(session, tmpl, count, &object);
             if (rv == CKR_OK)
             {
                 this = create(type, keylen, p11, slot, session, object);
                 DBG2(DBG_CFG, "created %N public key on token '%s':%d ",
                      key_type_names, type, p11->get_name(p11), slot);
             }
             else
             {
                 DBG1(DBG_CFG, "creating %N public key on token '%s':%d "
                      "failed: %N", key_type_names, type, p11->get_name(p11),
                      slot, ck_rv_names, rv);
                 p11->f->C_CloseSession(session);
             }
             break;
         }
         mechs->destroy(mechs);
         if (this)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return this;
 }
static private_pkcs11_public_key_t* create_rsa_key (chunk_t n, chunk_t e, size_t keylen) static
Create an RSA key object in a suitable token session
Definition at line 715 of file pkcs11_public_key.c.
References CKA_CLASS, CKA_KEY_TYPE, CKA_MODULUS, CKA_PUBLIC_EXPONENT, CKK_RSA, CKM_MD5_RSA_PKCS, CKM_RSA_PKCS, CKM_SHA1_RSA_PKCS, CKM_SHA256_RSA_PKCS, CKM_SHA384_RSA_PKCS, CKM_SHA512_RSA_PKCS, CKO_PUBLIC_KEY, countof, create_key(), KEY_RSA, chunk_t::len, mechs, chunk_t::ptr, and type.
Referenced by pkcs11_public_key_load().
 {
     CK_OBJECT_CLASS class = CKO_PUBLIC_KEY;
     CK_KEY_TYPE type = CKK_RSA;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_KEY_TYPE, &type, sizeof(type)},
         {CKA_MODULUS, n.ptr, n.len},
         {CKA_PUBLIC_EXPONENT, e.ptr, e.len},
     };
     CK_MECHANISM_TYPE mechs[] = {
         CKM_RSA_PKCS,
         CKM_SHA1_RSA_PKCS,
         CKM_SHA256_RSA_PKCS,
         CKM_SHA384_RSA_PKCS,
         CKM_SHA512_RSA_PKCS,
         CKM_MD5_RSA_PKCS,
     };
     return create_key(KEY_RSA, keylen, mechs, countof(mechs), tmpl,
                       countof(tmpl));
 }
static bool encode_ecdsa (private_pkcs11_public_key_t * this, cred_encoding_type_t type, chunk_t * encoding) static
Encode ECDSA key using a given encoding type
Definition at line 341 of file pkcs11_public_key.c.
References asn1_bitstring(), asn1_build_known_oid(), ASN1_SEQUENCE, asn1_wrap(), chunk_clear(), chunk_create(), CKA_EC_PARAMS, CKA_EC_POINT, countof, CRED_PART_ECDSA_PUB_ASN1_DER, CRED_PART_END, DESTROY_IF, cred_encoding_t::encode, encoding, library_t::encoding, enumerator_t::enumerate, FALSE, lib, OID_EC_PUBLICKEY, PUBKEY_PEM, PUBKEY_SPKI_ASN1_DER, and TRUE.
Referenced by fingerprint_ecdsa(), and METHOD().
 {
     enumerator_t *enumerator;
     bool success = FALSE;
     CK_ATTRIBUTE attr[] = {
         {CKA_EC_PARAMS, NULL, 0},
         {CKA_EC_POINT, NULL, 0},
     };
     if (type != PUBKEY_SPKI_ASN1_DER && type != PUBKEY_PEM)
     {
         return FALSE;
     }
     enumerator = this->lib->create_object_attr_enumerator(this->lib,
                             this->session, this->object, attr, countof(attr));
     if (enumerator && enumerator->enumerate(enumerator, NULL) &&
         attr[0].ulValueLen > 0 && attr[1].ulValueLen > 0)
     {
         chunk_t ecparams, ecpoint;
         ecparams = chunk_create(attr[0].pValue, attr[0].ulValueLen);
         ecpoint = chunk_create(attr[1].pValue, attr[1].ulValueLen);
         /* encode as subjectPublicKeyInfo */
         *encoding = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_wrap(ASN1_SEQUENCE, "mc",
                             asn1_build_known_oid(OID_EC_PUBLICKEY), ecparams),
                         asn1_bitstring("c", ecpoint));
         success = TRUE;
         if (type == PUBKEY_PEM)
         {
             chunk_t asn1 = *encoding;
             success = lib->encoding->encode(lib->encoding, PUBKEY_PEM,
                             NULL, encoding, CRED_PART_ECDSA_PUB_ASN1_DER,
                             asn1, CRED_PART_END);
             chunk_clear(&asn1);
         }
     }
     DESTROY_IF(enumerator);
     return success;
 }
static bool encode_rsa (private_pkcs11_public_key_t * this, cred_encoding_type_t type, void * cache, chunk_t * encoding) static
Encode RSA key using a given encoding type
Definition at line 426 of file pkcs11_public_key.c.
References chunk_cata, chunk_create(), chunk_from_chars, chunk_skip_zero(), CKA_MODULUS, CKA_PUBLIC_EXPONENT, countof, CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, DESTROY_IF, cred_encoding_t::encode, library_t::encoding, enumerator_t::enumerate, FALSE, lib, n, and chunk_t::ptr.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     bool success = FALSE;
     CK_ATTRIBUTE attr[] = {
         {CKA_MODULUS, NULL, 0},
         {CKA_PUBLIC_EXPONENT, NULL, 0},
     };
     enumerator = this->lib->create_object_attr_enumerator(this->lib,
                             this->session, this->object, attr, countof(attr));
     if (enumerator && enumerator->enumerate(enumerator, NULL) &&
         attr[0].ulValueLen > 0 && attr[1].ulValueLen > 0)
     {
         chunk_t n, e;
         /* some tokens/libraries add unnecessary 0x00 prefixes */
         n = chunk_skip_zero(chunk_create(attr[0].pValue, attr[0].ulValueLen));
         if (n.ptr[0] & 0x80)
         {   /* add leading 0x00, encoders might expect it in two's complement */
             n = chunk_cata("cc", chunk_from_chars(0x00), n);
         }
         e = chunk_skip_zero(chunk_create(attr[1].pValue, attr[1].ulValueLen));
         if (e.ptr[0] & 0x80)
         {
             e = chunk_cata("cc", chunk_from_chars(0x00), e);
         }
         success = lib->encoding->encode(lib->encoding, type, cache, encoding,
             CRED_PART_RSA_MODULUS, n, CRED_PART_RSA_PUB_EXP, e, CRED_PART_END);
     }
     DESTROY_IF(enumerator);
     return success;
 }
static private_pkcs11_public_key_t* find_ecdsa_key (chunk_t ecparams, chunk_t ecpoint, size_t keylen) static
Find an ECDSA key object
Definition at line 614 of file pkcs11_public_key.c.
References CKA_CLASS, CKA_EC_PARAMS, CKA_EC_POINT, CKA_KEY_TYPE, CKK_ECDSA, CKO_PUBLIC_KEY, countof, find_key(), KEY_ECDSA, chunk_t::len, chunk_t::ptr, and type.
Referenced by pkcs11_public_key_load().
 {
     CK_OBJECT_CLASS class = CKO_PUBLIC_KEY;
     CK_KEY_TYPE type = CKK_ECDSA;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_KEY_TYPE, &type, sizeof(type)},
         {CKA_EC_PARAMS, ecparams.ptr, ecparams.len},
         {CKA_EC_POINT, ecpoint.ptr, ecpoint.len},
     };
     return find_key(KEY_ECDSA, keylen, tmpl, countof(tmpl));
 }
static private_pkcs11_public_key_t* find_key (key_type_t type, size_t keylen, CK_ATTRIBUTE_PTR tmpl, int count) static
Find a key object, including PKCS11 library and slot
Definition at line 550 of file pkcs11_public_key.c.
References ck_function_list::C_CloseSession, ck_function_list::C_OpenSession, ck_rv_names, CKF_SERIAL_SESSION, CKR_OK, create(), pkcs11_library_t::create_object_enumerator, pkcs11_manager_t::create_token_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, pkcs11_library_t::f, library_t::get, keys, and lib.
Referenced by find_ecdsa_key(), and find_rsa_key().
 {
     private_pkcs11_public_key_t *this = NULL;
     pkcs11_manager_t *manager;
     enumerator_t *enumerator, *keys;
     pkcs11_library_t *p11;
     CK_SLOT_ID slot;
     manager = lib->get(lib, "pkcs11-manager");
     if (!manager)
     {
         return NULL;
     }
     enumerator = manager->create_token_enumerator(manager);
     while (enumerator->enumerate(enumerator, &p11, &slot))
     {
         CK_OBJECT_HANDLE object;
         CK_SESSION_HANDLE session;
         CK_RV rv;
         rv = p11->f->C_OpenSession(slot, CKF_SERIAL_SESSION, NULL, NULL,
                                    &session);
         if (rv != CKR_OK)
         {
             DBG1(DBG_CFG, "opening PKCS#11 session failed: %N", ck_rv_names, rv);
             continue;
         }
         keys = p11->create_object_enumerator(p11, session, tmpl, count,
                                              NULL, 0);
         if (keys->enumerate(keys, &object))
         {
             this = create(type, keylen, p11, slot, session, object);
             keys->destroy(keys);
             break;
         }
         keys->destroy(keys);
         p11->f->C_CloseSession(session);
     }
     enumerator->destroy(enumerator);
     return this;
 }
static private_pkcs11_public_key_t* find_key_by_keyid (pkcs11_library_t * p11, int slot, key_type_t key_type, chunk_t keyid) static
Definition at line 830 of file pkcs11_public_key.c.
References ck_function_list::C_CloseSession, ck_function_list::C_OpenSession, chunk_free(), ck_rv_names, CKA_CLASS, CKA_EC_PARAMS, CKA_ID, CKA_KEY_TYPE, CKA_MODULUS, CKF_SERIAL_SESSION, CKK_ECDSA, CKK_RSA, CKO_PUBLIC_KEY, CKR_OK, count, countof, create(), pkcs11_library_t::create_object_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, pkcs11_library_t::f, FALSE, found, pkcs11_library_t::get_ck_attribute, pkcs11_library_t::get_name, KEY_ECDSA, KEY_RSA, keylen_from_ecparams(), chunk_t::len, n, chunk_t::ptr, TRUE, and type.
Referenced by pkcs11_public_key_connect().
 {
     CK_OBJECT_CLASS class = CKO_PUBLIC_KEY;
     CK_KEY_TYPE type;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_ID, keyid.ptr, keyid.len},
         {CKA_KEY_TYPE, &type, sizeof(type)},
     };
     CK_OBJECT_HANDLE object;
     CK_ATTRIBUTE attr[] = {
         {CKA_KEY_TYPE, &type, sizeof(type)},
     };
     CK_SESSION_HANDLE session;
     CK_RV rv;
     enumerator_t *enumerator;
     int count = countof(tmpl);
     bool found = FALSE;
     size_t keylen;
     switch (key_type)
     {
         case KEY_RSA:
             type = CKK_RSA;
             break;
         case KEY_ECDSA:
             type = CKK_ECDSA;
             break;
         default:
             /* don't specify key type on KEY_ANY */
             count--;
             break;
     }
     rv = p11->f->C_OpenSession(slot, CKF_SERIAL_SESSION, NULL, NULL, &session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "opening public key session on '%s':%d failed: %N",
              p11->get_name(p11), slot, ck_rv_names, rv);
         return NULL;
     }
     enumerator = p11->create_object_enumerator(p11, session, tmpl, count, attr,
                                                countof(attr));
     if (enumerator->enumerate(enumerator, &object))
     {
         switch (type)
         {
             case CKK_ECDSA:
             {
                 chunk_t ecparams;
                 if (p11->get_ck_attribute(p11, session, object, CKA_EC_PARAMS,
                                           &ecparams) &&
                     keylen_from_ecparams(ecparams, &keylen))
                 {
                     chunk_free(&ecparams);
                     key_type = KEY_ECDSA;
                     found = TRUE;
                 }
                 break;
             }
             case CKK_RSA:
             {
                 chunk_t n;
                 if (p11->get_ck_attribute(p11, session, object, CKA_MODULUS,
                                           &n) && n.len > 0)
                 {
                     keylen = n.len * 8;
                     chunk_free(&n);
                     key_type = KEY_RSA;
                     found = TRUE;
                 }
                 break;
             }
             default:
                 DBG1(DBG_CFG, "PKCS#11 key type %d not supported", type);
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (found)
     {
         return create(key_type, keylen, p11, slot, session, object);
     }
     p11->f->C_CloseSession(session);
     return NULL;
 }
static private_pkcs11_public_key_t* find_rsa_key (chunk_t n, chunk_t e, size_t keylen) static
Find an RSA key object
Definition at line 597 of file pkcs11_public_key.c.
References CKA_CLASS, CKA_KEY_TYPE, CKA_MODULUS, CKA_PUBLIC_EXPONENT, CKK_RSA, CKO_PUBLIC_KEY, countof, find_key(), KEY_RSA, chunk_t::len, chunk_t::ptr, and type.
Referenced by pkcs11_public_key_load().
 {
     CK_OBJECT_CLASS class = CKO_PUBLIC_KEY;
     CK_KEY_TYPE type = CKK_RSA;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_KEY_TYPE, &type, sizeof(type)},
         {CKA_MODULUS, n.ptr, n.len},
         {CKA_PUBLIC_EXPONENT, e.ptr, e.len},
     };
     return find_key(KEY_RSA, keylen, tmpl, countof(tmpl));
 }
static bool fingerprint_ecdsa (private_pkcs11_public_key_t * this, cred_encoding_type_t type, chunk_t * fp) static
Compute fingerprint of an ECDSA key
Definition at line 386 of file pkcs11_public_key.c.
References hasher_t::allocate_hash, cred_encoding_t::cache, chunk_clear(), CKA_EC_POINT, crypto_factory_t::create_hasher, library_t::crypto, hasher_t::destroy, DESTROY_IF, encode_ecdsa(), library_t::encoding, FALSE, HASH_SHA1, hasher, KEYID_PUBKEY_INFO_SHA1, KEYID_PUBKEY_SHA1, lib, PUBKEY_SPKI_ASN1_DER, and TRUE.
Referenced by METHOD().
 {
     hasher_t *hasher;
     chunk_t asn1;
     switch (type)
     {
         case KEYID_PUBKEY_SHA1:
             if (!this->lib->get_ck_attribute(this->lib, this->session,
                         this->object, CKA_EC_POINT, &asn1))
             {
                 return FALSE;
             }
             break;
         case KEYID_PUBKEY_INFO_SHA1:
             if (!encode_ecdsa(this, PUBKEY_SPKI_ASN1_DER, &asn1))
             {
                 return FALSE;
             }
             break;
         default:
             return FALSE;
     }
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher || !hasher->allocate_hash(hasher, asn1, fp))
     {
         DESTROY_IF(hasher);
         chunk_clear(&asn1);
         return FALSE;
     }
     hasher->destroy(hasher);
     chunk_clear(&asn1);
     lib->encoding->cache(lib->encoding, type, this, *fp);
     return TRUE;
 }
static bool keylen_from_ecparams (chunk_t ecparams, size_t * keylen) static
Parses the given ecParameters (ASN.1) and returns the key length.
Definition at line 109 of file pkcs11_public_key.c.
References asn1_known_oid(), ASN1_OID, asn1_parse_simple_object(), basepoint_order_len(), and FALSE.
Referenced by find_key_by_keyid(), and parse_ecdsa_public_key().
 {
     if (!asn1_parse_simple_object(&ecparams, ASN1_OID, 0, "named curve"))
     {
         return FALSE;
     }
     *keylen = basepoint_order_len(asn1_known_oid(ecparams));
     return *keylen > 0;
 }
METHOD (public_key_t , get_type , key_type_t , private_pkcs11_public_key_t * this)
Definition at line 191 of file pkcs11_public_key.c.
References type.
 {
     return this->type;
 }
METHOD (public_key_t , get_keysize , int , private_pkcs11_public_key_t * this)
Definition at line 197 of file pkcs11_public_key.c.
 {
     return this->k;
 }
METHOD (public_key_t , verify , bool , private_pkcs11_public_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t sig)
Definition at line 203 of file pkcs11_public_key.c.
References hasher_t::allocate_hash, ASN1_INTEGER, ASN1_SEQUENCE, asn1_unwrap(), chunk_alloca, chunk_empty, chunk_free(), chunk_skip_zero(), ck_rv_names, CKF_SERIAL_SESSION, CKR_OK, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_CFG, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, hash, HASH_UNKNOWN, hasher, chunk_t::len, len, lib, memcpy, memset, parse(), pkcs11_signature_scheme_to_mech(), chunk_t::ptr, r, s, sig, SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER, signature_scheme_names, TRUE, and type.
 {
     CK_MECHANISM_PTR mechanism;
     CK_SESSION_HANDLE session;
     CK_RV rv;
     hash_algorithm_t hash_alg;
     chunk_t hash = chunk_empty, parse, r, s;
     size_t len;
     mechanism = pkcs11_signature_scheme_to_mech(scheme, this->type, this->k,
                                                 &hash_alg);
     if (!mechanism)
     {
         DBG1(DBG_LIB, "signature scheme %N not supported",
              signature_scheme_names, scheme);
         return FALSE;
     }
     switch (scheme)
     {
         case SIGN_ECDSA_WITH_SHA1_DER:
         case SIGN_ECDSA_WITH_SHA256_DER:
         case SIGN_ECDSA_WITH_SHA384_DER:
         case SIGN_ECDSA_WITH_SHA512_DER:
             /* PKCS#11 expects the ECDSA signatures as simple concatenation of
              * r and s, so unwrap the ASN.1 encoded sequence */
             parse = sig;
             if (asn1_unwrap(&parse, &parse) != ASN1_SEQUENCE ||
                 asn1_unwrap(&parse, &r) != ASN1_INTEGER ||
                 asn1_unwrap(&parse, &s) != ASN1_INTEGER)
             {
                 return FALSE;
             }
             r = chunk_skip_zero(r);
             s = chunk_skip_zero(s);
             len = (get_keysize(this) + 7) / 8;
             if (r.len > len || s.len > len)
             {
                 return FALSE;
             }
             /* concatenate r and s (forced to the defined length) */
             sig = chunk_alloca(2*len);
             memset(sig.ptr, 0, sig.len);
             memcpy(sig.ptr + (len - r.len), r.ptr, r.len);
             memcpy(sig.ptr + len + (len - s.len), s.ptr, s.len);
             break;
         default:
             sig = chunk_skip_zero(sig);
             break;
     }
     rv = this->lib->f->C_OpenSession(this->slot, CKF_SERIAL_SESSION, NULL, NULL,
                                      &session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "opening PKCS#11 session failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     rv = this->lib->f->C_VerifyInit(session, mechanism, this->object);
     if (rv != CKR_OK)
     {
         this->lib->f->C_CloseSession(session);
         DBG1(DBG_LIB, "C_VerifyInit() failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     if (hash_alg != HASH_UNKNOWN)
     {
         hasher_t *hasher;
         hasher = lib->crypto->create_hasher(lib->crypto, hash_alg);
         if (!hasher || !hasher->allocate_hash(hasher, data, &hash))
         {
             DESTROY_IF(hasher);
             this->lib->f->C_CloseSession(session);
             return FALSE;
         }
         hasher->destroy(hasher);
         data = hash;
     }
     rv = this->lib->f->C_Verify(session, data.ptr, data.len, sig.ptr, sig.len);
     this->lib->f->C_CloseSession(session);
     chunk_free(&hash);
     if (rv != CKR_OK)
     {
         DBG1(DBG_LIB, "C_Verify() failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     return TRUE;
 }
METHOD (public_key_t , encrypt , bool , private_pkcs11_public_key_t * this, encryption_scheme_t scheme, chunk_t plain, chunk_t * crypt)
Definition at line 293 of file pkcs11_public_key.c.
References chunk_create(), ck_rv_names, CKF_SERIAL_SESSION, CKR_OK, DBG1, DBG_CFG, DBG_LIB, encryption_scheme_names, FALSE, free(), chunk_t::len, len, lib, malloc(), pkcs11_encryption_scheme_to_mech(), chunk_t::ptr, and TRUE.
 {
     CK_MECHANISM_PTR mechanism;
     CK_SESSION_HANDLE session;
     CK_BYTE_PTR buf;
     CK_ULONG len;
     CK_RV rv;
     mechanism = pkcs11_encryption_scheme_to_mech(scheme);
     if (!mechanism)
     {
         DBG1(DBG_LIB, "encryption scheme %N not supported",
              encryption_scheme_names, scheme);
         return FALSE;
     }
     rv = this->lib->f->C_OpenSession(this->slot, CKF_SERIAL_SESSION, NULL, NULL,
                                      &session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "opening PKCS#11 session failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     rv = this->lib->f->C_EncryptInit(session, mechanism, this->object);
     if (rv != CKR_OK)
     {
         this->lib->f->C_CloseSession(session);
         DBG1(DBG_LIB, "C_EncryptInit() failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     len = (get_keysize(this) + 7) / 8;
     buf = malloc(len);
     rv = this->lib->f->C_Encrypt(session, plain.ptr, plain.len, buf, &len);
     this->lib->f->C_CloseSession(session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_LIB, "C_Encrypt() failed: %N", ck_rv_names, rv);
         free(buf);
         return FALSE;
     }
     *crypt = chunk_create(buf, len);
     return TRUE;
 }
METHOD (public_key_t , get_encoding , bool , private_pkcs11_public_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 460 of file pkcs11_public_key.c.
References encode_ecdsa(), encode_rsa(), FALSE, KEY_ECDSA, and KEY_RSA.
 {
     switch (this->type)
     {
         case KEY_RSA:
             return encode_rsa(this, type, NULL, encoding);
         case KEY_ECDSA:
             return encode_ecdsa(this, type, encoding);
         default:
             return FALSE;
     }
 }
METHOD (public_key_t , get_fingerprint , bool , private_pkcs11_public_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 475 of file pkcs11_public_key.c.
References encode_rsa(), library_t::encoding, FALSE, fingerprint_ecdsa(), cred_encoding_t::get_cache, KEY_ECDSA, KEY_RSA, lib, and TRUE.
 {
     if (lib->encoding->get_cache(lib->encoding, type, this, fp))
     {
         return TRUE;
     }
     switch (this->type)
     {
         case KEY_RSA:
             return encode_rsa(this, type, this, fp);
         case KEY_ECDSA:
             return fingerprint_ecdsa(this, type, fp);
         default:
             return FALSE;
     }
 }
METHOD (public_key_t , get_ref , public_key_t * , private_pkcs11_public_key_t * this)
Definition at line 493 of file pkcs11_public_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (public_key_t , destroy , void , private_pkcs11_public_key_t * this)
Definition at line 500 of file pkcs11_public_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), lib, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         lib->encoding->clear_cache(lib->encoding, this);
         this->lib->f->C_CloseSession(this->session);
         free(this);
     }
 }
static bool parse_ecdsa_public_key (chunk_t blob, chunk_t * ecparams, chunk_t * ecpoint, size_t * keylen) static
Extract the DER encoded Parameters and ECPoint from the given DER encoded subjectPublicKeyInfo. Memory for ecpoint is allocated.
Definition at line 140 of file pkcs11_public_key.c.
References asn1_known_oid(), ASN1_OCTET_STRING, asn1_parser_create(), asn1_wrap(), chunk_skip(), asn1_parser_t::destroy, end, FALSE, asn1_parser_t::iterate, keylen_from_ecparams(), len, OID_EC_PUBLICKEY, parser, PKINFO_SUBJECT_PUBLIC_KEY, PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM, PKINFO_SUBJECT_PUBLIC_KEY_NAMEDCURVE, and asn1_parser_t::success.
Referenced by pkcs11_public_key_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool success = FALSE;
     parser = asn1_parser_create(pkinfoObjects, blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM:
             {
                 if (asn1_known_oid(object) != OID_EC_PUBLICKEY)
                 {
                     goto end;
                 }
                 break;
             }
             case PKINFO_SUBJECT_PUBLIC_KEY_NAMEDCURVE:
             {
                 *ecparams = object;
                 if (!keylen_from_ecparams(object, keylen))
                 {
                     goto end;
                 }
                 break;
             }
             case PKINFO_SUBJECT_PUBLIC_KEY:
             {
                 if (object.len > 0 && *object.ptr == 0x00)
                 {   /* skip initial bit string octet defining 0 unused bits */
                     object = chunk_skip(object, 1);
                 }
                 /* the correct way to encode an EC_POINT in PKCS#11 is as
                  * ASN.1 octet string */
                 *ecpoint = asn1_wrap(ASN1_OCTET_STRING, "c", object);
                 break;
             }
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     return success;
 }
Variable Documentation
const asn1Object_t pkinfoObjects[] static
Initial value:
= {
    { 0, "subjectPublicKeyInfo",    ASN1_SEQUENCE,      ASN1_NONE   },
    { 1,   "algorithmIdentifier",   ASN1_SEQUENCE,      ASN1_NONE   },
    { 2,     "algorithm",           ASN1_OID,           ASN1_BODY   },
    { 2,     "namedCurve",          ASN1_OID,           ASN1_RAW    },
    { 1,   "subjectPublicKey",      ASN1_BIT_STRING,    ASN1_BODY   },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT   }
}
ASN.1 definition of a subjectPublicKeyInfo structure when used with ECDSA we currently only support named curves.
Definition at line 123 of file pkcs11_public_key.c.