strongSwan: imv_state_t Struct Reference
imv_state_t Struct Reference
imv_state
#include "imv_state.h"
Public Attributes
TNC_ConnectionID(* get_connection_id)(imv_state_t *this)
bool(* has_long)(imv_state_t *this)
bool(* has_excl)(imv_state_t *this)
void(* set_flags)(imv_state_t *this, bool has_long, bool has_excl)
void(* set_max_msg_len)(imv_state_t *this, uint32_t max_msg_len)
uint32_t(* get_max_msg_len)(imv_state_t *this)
void(* set_action_flags)(imv_state_t *this, uint32_t flags)
uint32_t(* get_action_flags)(imv_state_t *this)
void(* set_session)(imv_state_t *this, imv_session_t *session)
imv_session_t *(* get_session)(imv_state_t *this)
seg_contract_manager_t *(* get_contracts)(imv_state_t *this)
void(* change_state)(imv_state_t *this, TNC_ConnectionState new_state)
void(* get_recommendation)(imv_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
void(* set_recommendation)(imv_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
void(* update_recommendation)(imv_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
bool(* get_reason_string)(imv_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
bool(* get_remediation_instructions)(imv_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
void(* destroy)(imv_state_t *this)
Detailed Description
Internal state of an IMV connection instance
Definition at line 37 of file imv_state.h.
Member Data Documentation
void(* imv_state_t::change_state)(imv_state_t *this, TNC_ConnectionState new_state)
Change the connection state
Parameters
new_state new connection state
Definition at line 123 of file imv_state.h.
Referenced by METHOD().
void(* imv_state_t::destroy)(imv_state_t *this)
Destroys an imv_state_t object
Definition at line 187 of file imv_state.h.
Referenced by delete_connection(), and METHOD().
uint32_t(* imv_state_t::get_action_flags)(imv_state_t *this)
Get flags set for completed actions
Returns
Flags set for completed actions
Definition at line 95 of file imv_state.h.
Referenced by imv_attestation_build(), and METHOD().
TNC_ConnectionID(* imv_state_t::get_connection_id)(imv_state_t *this)
Get the TNCCS connection ID attached to the state
Returns
TNCCS connection ID of the state
Definition at line 44 of file imv_state.h.
Referenced by delete_connection(), find_connection(), METHOD(), and receive_msg().
seg_contract_manager_t*(* imv_state_t::get_contracts)(imv_state_t *this)
Get attribute segmentation contracts associated with TNCCS Connection
Returns
Contracts associated with TNCCS Connection
Definition at line 116 of file imv_state.h.
Referenced by METHOD().
uint32_t(* imv_state_t::get_max_msg_len)(imv_state_t *this)
Get the maximum size of a PA-TNC message for this TNCCS connection
Returns
maximum size of a PA-TNC message
Definition at line 81 of file imv_state.h.
Referenced by METHOD().
bool(* imv_state_t::get_reason_string)(imv_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
Get reason string based on the preferred language
Parameters
language_enumerator language enumerator
reason_string reason string
reason_language language of the returned reason string
Returns
TRUE if a reason string was found
Definition at line 166 of file imv_state.h.
Referenced by METHOD().
void(* imv_state_t::get_recommendation)(imv_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
Get IMV action recommendation and evaluation result
Parameters
rec IMV action recommendation
eval IMV evaluation result
Definition at line 132 of file imv_state.h.
Referenced by METHOD().
bool(* imv_state_t::get_remediation_instructions)(imv_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
Get remediation instructions based on the preferred language
Parameters
language_enumerator language enumerator
string remediation instruction string
lang_code language of the remediation instructions
uri remediation URI
Returns
TRUE if remediation instructions were found
Definition at line 179 of file imv_state.h.
imv_session_t*(* imv_state_t::get_session)(imv_state_t *this)
Get session associated with TNCCS Connection
Returns
Session associated with TNCCS Connection
Definition at line 109 of file imv_state.h.
Referenced by delete_connection(), imv_attestation_process(), METHOD(), and receive_msg().
bool(* imv_state_t::has_excl)(imv_state_t *this)
Checks if the exclusive delivery is supported for this TNCCS connection
Returns
TRUE if set, FALSE otherwise
Definition at line 58 of file imv_state.h.
bool(* imv_state_t::has_long)(imv_state_t *this)
Checks if long message types are supported for this TNCCS connection
Returns
TRUE if set, FALSE otherwise
Definition at line 51 of file imv_state.h.
void(* imv_state_t::set_action_flags)(imv_state_t *this, uint32_t flags)
Set flags for completed actions
Parameters
flags Flags to be set
Definition at line 88 of file imv_state.h.
Referenced by imv_attestation_process(), METHOD(), and receive_msg().
void(* imv_state_t::set_flags)(imv_state_t *this, bool has_long, bool has_excl)
Sets the long message types and exclusive flags for this TNCCS connection
Parameters
has_long TNCCS connection supports long message types
has_excl TNCCS connection supports exclusive delivery
Returns
TRUE if set, FALSE otherwise
Definition at line 67 of file imv_state.h.
Referenced by METHOD().
void(* imv_state_t::set_max_msg_len)(imv_state_t *this, uint32_t max_msg_len)
Set the maximum size of a PA-TNC message for this TNCCS connection
Parameters
max_msg_len maximum size of a PA-TNC message
Definition at line 74 of file imv_state.h.
Referenced by METHOD().
void(* imv_state_t::set_recommendation)(imv_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Set IMV action recommendation and evaluation result
Parameters
rec IMV action recommendation
eval IMV evaluation result
Definition at line 143 of file imv_state.h.
Referenced by METHOD(), and receive_msg().
void(* imv_state_t::set_session)(imv_state_t *this, imv_session_t *session)
Set session associated with TNCCS Connection
Parameters
session Session associated with TNCCS Connection
Definition at line 102 of file imv_state.h.
Referenced by METHOD().
void(* imv_state_t::update_recommendation)(imv_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Update IMV action recommendation and evaluation result
Parameters
rec IMV action recommendation
eval IMV evaluation result
Definition at line 154 of file imv_state.h.
Referenced by imv_attestation_process(), and METHOD().
The documentation for this struct was generated from the following file:
imv_state.h