strongSwan: backtrace.c File Reference
backtrace.c File Reference
#include <string.h>
#include "backtrace.h"
#include <utils/debug.h>
Classes
struct private_backtrace_t
struct frame_enumerator_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct private_backtrace_t private_backtrace_t
Functions
static backtrace_t get_methods ()
static void println (FILE *file, char *format,...)
static char * esc (FILE *file, tty_escape_t escape)
void backtrace_init ()
void backtrace_deinit ()
METHOD (backtrace_t, log_, void, private_backtrace_t *this, FILE *file, bool detailed)
METHOD (backtrace_t, contains_function, bool, private_backtrace_t *this, char *function[], int count)
METHOD (backtrace_t, equals, bool, private_backtrace_t *this, backtrace_t *other_public)
METHOD (enumerator_t, frame_enumerate, bool, frame_enumerator_t *this, void **addr)
METHOD (backtrace_t, create_frame_enumerator, enumerator_t *, private_backtrace_t *this)
METHOD (backtrace_t, clone_, backtrace_t *, private_backtrace_t *this)
METHOD (backtrace_t, destroy, void, private_backtrace_t *this)
backtrace_t * backtrace_create (int skip)
void backtrace_dump (char *label, FILE *file, bool detailed)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file backtrace.c.
Typedef Documentation
typedef struct private_backtrace_t private_backtrace_t
Definition at line 50 of file backtrace.c.
Function Documentation
static char* esc (FILE * file, tty_escape_t escape) inline static
Same as tty_escape_get(), but for a potentially NULL FILE*
Definition at line 103 of file backtrace.c.
References tty_escape_get().
Referenced by METHOD().
 {
     if (file)
     {
         return tty_escape_get(fileno(file), escape);
     }
     return "";
 }
static backtrace_t get_methods () static
Forward declaration of method getter
Get implementation methods of backtrace_t
Definition at line 807 of file backtrace.c.
References backtrace_t::log.
Referenced by backtrace_create(), and METHOD().
 {
     return (backtrace_t) {
         .log = _log_,
         .contains_function = _contains_function,
         .equals = _equals,
         .clone = _clone_,
         .create_frame_enumerator = _create_frame_enumerator,
         .destroy = _destroy,
     };
 }
METHOD (backtrace_t , log_ , void , private_backtrace_t * this, FILE * file, bool detailed)
Definition at line 430 of file backtrace.c.
References DWORD, esc(), free(), mutex_t::lock, memset, println(), process(), TTY_FG_DEF, TTY_FG_GREEN, TTY_FG_RED, TTY_FG_YELLOW, and mutex_t::unlock.
 {
 #if defined(HAVE_BACKTRACE) || defined(HAVE_LIBUNWIND_H) || defined(WIN32)
     size_t i;
     char **strings = NULL;
     println(file, " dumping %d stack frame addresses:", this->frame_count);
     for (i = 0; i < this->frame_count; i++)
     {
 #ifdef HAVE_DLADDR
         Dl_info info;
         if (dladdr(this->frames[i], &info))
         {
             void *ptr = this->frames[i];
             if (strstr(info.dli_fname, ".so"))
             {
                 ptr = (void*)(this->frames[i] - info.dli_fbase);
             }
             if (info.dli_sname)
             {
                 println(file, "  %s%s%s @ %p (%s%s%s+0x%tx) [%p]",
                         esc(file, TTY_FG_YELLOW), info.dli_fname,
                         esc(file, TTY_FG_DEF), info.dli_fbase,
                         esc(file, TTY_FG_RED), info.dli_sname,
                         esc(file, TTY_FG_DEF), this->frames[i] - info.dli_saddr,
                         this->frames[i]);
             }
             else
             {
                 println(file, "  %s%s%s @ %p [%p]",
                         esc(file, TTY_FG_YELLOW), info.dli_fname,
                         esc(file, TTY_FG_DEF), info.dli_fbase, this->frames[i]);
             }
             if (detailed && info.dli_fname[0])
             {
                 print_sourceline(file, (char*)info.dli_fname,
                                  ptr, info.dli_fbase);
             }
         }
         else
 #elif defined(HAVE_DBGHELP)
         struct {
             SYMBOL_INFO hdr;
             char buf[128];
         } symbol;
         char filename[MAX_PATH];
         HINSTANCE module;
         HANDLE process;
         DWORD64 displace, frame;
         process = GetCurrentProcess();
         frame = (uintptr_t)this->frames[i];
         memset(&symbol, 0, sizeof(symbol));
         symbol.hdr.SizeOfStruct = sizeof(symbol.hdr);
         symbol.hdr.MaxNameLen = sizeof(symbol.buf) - 1;
         dbghelp_mutex->lock(dbghelp_mutex);
         module = (HINSTANCE)SymGetModuleBase64(process, frame);
         if (module && GetModuleFileName(module, filename, sizeof(filename)))
         {
             if (SymFromAddr(process, frame, &displace, &symbol.hdr))
             {
                 println(file, "  %s%s%s @ %p (%s%s%s+0x%tx) [%p]",
                         esc(file, TTY_FG_YELLOW), filename,
                         esc(file, TTY_FG_DEF), (void*)module,
                         esc(file, TTY_FG_RED), symbol.hdr.Name,
                         esc(file, TTY_FG_DEF), displace,
                         this->frames[i]);
             }
             else
             {
                 println(file, "  %s%s%s @ %p [%p]",
                         esc(file, TTY_FG_YELLOW), filename,
                         esc(file, TTY_FG_DEF), (void*)module, this->frames[i]);
             }
             if (detailed)
             {
                 IMAGEHLP_LINE64 line;
                 DWORD off;
                 memset(&line, 0, sizeof(line));
                 line.SizeOfStruct = sizeof(line);
                 if (SymGetLineFromAddr64(process, frame, &off, &line))
                 {
                     println(file, "    -> %s%s:%u%s", esc(file, TTY_FG_GREEN),
                             line.FileName, line.LineNumber,
                             esc(file, TTY_FG_DEF));
                 }
             }
         }
         else
 #elif defined(WIN32)
         HMODULE module;
         MODULEINFO info;
         char filename[MAX_PATH];
         if (GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS,
                         this->frames[i], &module) &&
             GetModuleInformation(GetCurrentProcess(), module,
                         &info, sizeof(info)) &&
             GetModuleFileNameEx(GetCurrentProcess(), module,
                         filename, sizeof(filename)))
         {
             println(file, "  %s%s%s @ %p [%p]",
                     esc(file, TTY_FG_YELLOW), filename,
                     esc(file, TTY_FG_DEF), info.lpBaseOfDll, this->frames[i]);
 #ifdef HAVE_BFD_H
             print_sourceline(file, filename, this->frames[i], info.lpBaseOfDll);
 #endif /* HAVE_BFD_H */
         }
         else
 #endif /* HAVE_DLADDR/HAVE_DBGHELP */
         {
 #ifdef HAVE_BACKTRACE
             if (!strings)
             {
                 strings = backtrace_symbols(this->frames, this->frame_count);
             }
             if (strings)
             {
                 println(file, "    %s", strings[i]);
             }
             else
 #endif /* HAVE_BACKTRACE */
             {
                 println(file, "    %p", this->frames[i]);
             }
         }
 #ifdef HAVE_DBGHELP
         dbghelp_mutex->unlock(dbghelp_mutex);
 #endif
     }
     free(strings);
 #else /* !HAVE_BACKTRACE && !HAVE_LIBUNWIND_H */
     println(file, "no support for capturing backtraces");
 #endif /* HAVE_BACKTRACE/HAVE_LIBUNWIND_H */
 }
METHOD (backtrace_t , contains_function , bool , private_backtrace_t * this, char * function[], int count)
Definition at line 576 of file backtrace.c.
References count, FALSE, mutex_t::lock, memset, process(), streq(), TRUE, and mutex_t::unlock.
 {
 #ifdef HAVE_DLADDR
     int i, j;
     for (i = 0; i< this->frame_count; i++)
     {
         Dl_info info;
         if (dladdr(this->frames[i], &info) && info.dli_sname)
         {
             for (j = 0; j < count; j++)
             {
                 if (streq(info.dli_sname, function[j]))
                 {
                     return TRUE;
                 }
             }
         }
     }
 #elif defined(HAVE_DBGHELP)
     int i, j;
     HANDLE process;
     process = GetCurrentProcess();
     dbghelp_mutex->lock(dbghelp_mutex);
     for (i = 0; i < this->frame_count; i++)
     {
         struct {
             SYMBOL_INFO hdr;
             char buf[128];
         } symbol;
         memset(&symbol, 0, sizeof(symbol));
         symbol.hdr.SizeOfStruct = sizeof(symbol.hdr);
         symbol.hdr.MaxNameLen = sizeof(symbol.buf) - 1;
         if (SymFromAddr(process, (DWORD64)this->frames[i], NULL, &symbol.hdr))
         {
             for (j = 0; j < count; j++)
             {
                 if (streq(symbol.hdr.Name, function[j]))
                 {
                     dbghelp_mutex->unlock(dbghelp_mutex);
                     return TRUE;
                 }
             }
         }
     }
     dbghelp_mutex->unlock(dbghelp_mutex);
 #endif /* HAVE_DLADDR/HAVE_DBGHELP */
     return FALSE;
 }
METHOD (backtrace_t , equals , bool , private_backtrace_t * this, backtrace_t * other_public)
Definition at line 634 of file backtrace.c.
References FALSE, private_backtrace_t::frame_count, private_backtrace_t::frames, and TRUE.
 {
     private_backtrace_t *other = (private_backtrace_t*)other_public;
     int i;
     if (this == other)
     {
         return TRUE;
     }
     if (this->frame_count != other->frame_count)
     {
         return FALSE;
     }
     for (i = 0; i < this->frame_count; i++)
     {
         if (this->frames[i] != other->frames[i])
         {
             return FALSE;
         }
     }
     return TRUE;
 }
METHOD (enumerator_t , frame_enumerate , bool , frame_enumerator_t * this, void ** addr)
Definition at line 670 of file backtrace.c.
References FALSE, and TRUE.
 {
     if (this->i < this->bt->frame_count)
     {
         *addr = this->bt->frames[this->i++];
         return TRUE;
     }
     return FALSE;
 }
METHOD (backtrace_t , create_frame_enumerator , enumerator_t * , private_backtrace_t * this)
Definition at line 681 of file backtrace.c.
References destroy(), free(), INIT, and frame_enumerator_t::public.
 {
     frame_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_frame_enumerate,
             .destroy = (void*)free,
         },
         .bt = this,
     );
     return &enumerator->public;
 }
METHOD (backtrace_t , clone_ , backtrace_t * , private_backtrace_t * this)
Definition at line 696 of file backtrace.c.
References private_backtrace_t::frame_count, private_backtrace_t::frames, get_methods(), malloc(), memcpy, and private_backtrace_t::public.
 {
     private_backtrace_t *clone;
     clone = malloc(sizeof(private_backtrace_t) +
                    this->frame_count * sizeof(void*));
     memcpy(clone->frames, this->frames, this->frame_count * sizeof(void*));
     clone->frame_count = this->frame_count;
     clone->public = get_methods();
     return &clone->public;
 }
METHOD (backtrace_t , destroy , void , private_backtrace_t * this)
Definition at line 711 of file backtrace.c.
References free().
 {
     free(this);
 }
static void println (FILE * file, char * format, ...) static
Write a format string with arguments to a FILE line, if it is NULL to DBG
Definition at line 81 of file backtrace.c.
References DBG1, DBG_LIB, vfprintf, and vsnprintf.
Referenced by backtrace_dump(), and METHOD().
 {
     char buf[512];
     va_list args;
     va_start(args, format);
     if (file)
     {
         vfprintf(file, format, args);
         fputs("\n", file);
     }
     else
     {
         vsnprintf(buf, sizeof(buf), format, args);
         DBG1(DBG_LIB, "%s", buf);
     }
     va_end(args);
 }