strongSwan: delete_payload_t Struct Reference
delete_payload_t Struct Reference
delete_payload
#include "delete_payload.h"
Public Attributes
payload_t payload_interface
protocol_id_t(* get_protocol_id)(delete_payload_t *this)
void(* add_spi)(delete_payload_t *this, u_int32_t spi)
void(* set_ike_spi)(delete_payload_t *this, u_int64_t spi_i, u_int64_t spi_r)
bool(* get_ike_spi)(delete_payload_t *this, u_int64_t *spi_i, u_int64_t *spi_r)
enumerator_t *(* create_spi_enumerator)(delete_payload_t *this)
void(* destroy)(delete_payload_t *this)
Detailed Description
Class representing an IKEv1 or a IKEv2 DELETE payload.
Definition at line 35 of file delete_payload.h.
Member Data Documentation
void(* delete_payload_t::add_spi)(delete_payload_t *this, u_int32_t spi)
Add an SPI to the list of deleted SAs.
Parameters
spi spi to add
Definition at line 54 of file delete_payload.h.
Referenced by build_payloads(), and METHOD().
enumerator_t*(* delete_payload_t::create_spi_enumerator)(delete_payload_t *this)
Get an enumerator over the SPIs in network order.
Returns
enumerator over SPIs, u_int32_t
Definition at line 78 of file delete_payload.h.
Referenced by METHOD(), and process_payloads().
void(* delete_payload_t::destroy)(delete_payload_t *this)
Destroys an delete_payload_t object.
Definition at line 83 of file delete_payload.h.
bool(* delete_payload_t::get_ike_spi)(delete_payload_t *this, u_int64_t *spi_i, u_int64_t *spi_r)
Get the IKE SPIs from an IKEv1 delete.
Parameters
spi_i initiator SPI
spi_r responder SPI
Returns
TRUE if SPIs extracted successfully
Definition at line 71 of file delete_payload.h.
Referenced by METHOD().
protocol_id_t(* delete_payload_t::get_protocol_id)(delete_payload_t *this)
Get the protocol ID.
Returns
protocol ID
Definition at line 47 of file delete_payload.h.
Referenced by METHOD(), and process_payloads().
payload_t delete_payload_t::payload_interface
The payload_t interface.
Definition at line 40 of file delete_payload.h.
Referenced by METHOD().
void(* delete_payload_t::set_ike_spi)(delete_payload_t *this, u_int64_t spi_i, u_int64_t spi_r)
Set the IKE SPIs for an IKEv1 delete.
Parameters
spi_i initiator SPI
spi_r responder SPI
Definition at line 62 of file delete_payload.h.
The documentation for this struct was generated from the following file:
delete_payload.h