strongSwan: ita_attr_get_settings
ita_attr_get_settings
ita_attr
Classes
struct ita_attr_get_settings_t
Typedefs
typedef struct
ita_attr_get_settings_t ita_attr_get_settings_t
Functions
pa_tnc_attr_t * ita_attr_get_settings_create (char *name)
pa_tnc_attr_t * ita_attr_get_settings_create_from_data (size_t length, chunk_t value)
Detailed Description
Typedef Documentation
typedef struct ita_attr_get_settings_t ita_attr_get_settings_t
Definition at line 24 of file ita_attr_get_settings.h.
Function Documentation
pa_tnc_attr_t* ita_attr_get_settings_create (char * name)
Creates an ita_attr_get_settings_t object with an optional first entry
Parameters
name name of the requested setting or NULL
Described in header.
Definition at line 224 of file ita_attr_get_settings.c.
References add(), INIT, ITA_ATTR_GET_SETTINGS, linked_list_create(), and PEN_ITA.
Referenced by METHOD().
 {
     private_ita_attr_get_settings_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add = _add,
             .create_enumerator = _create_enumerator,
         },
         .type = { PEN_ITA, ITA_ATTR_GET_SETTINGS },
         .list = linked_list_create(),
         .ref = 1,
     );
     if (name)
     {
         add(this, name);
     }
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ita_attr_get_settings_create_from_data (size_t length, chunk_t data)
Creates an ita_attr_get_settings_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 259 of file ita_attr_get_settings.c.
References chunk_clone, INIT, ITA_ATTR_GET_SETTINGS, length, linked_list_create(), and PEN_ITA.
Referenced by ita_attr_create_from_data().
 {
     private_ita_attr_get_settings_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add = _add,
             .create_enumerator = _create_enumerator,
         },
         .type = { PEN_ITA, ITA_ATTR_GET_SETTINGS },
         .length = length,
         .value = chunk_clone(data),
         .list = linked_list_create(),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }