strongSwan: pts_t Struct Reference
pts_t Struct Reference
pts
#include "pts.h"
Public Attributes
pts_proto_caps_flag_t(* get_proto_caps)(pts_t *this)
void(* set_proto_caps)(pts_t *this, pts_proto_caps_flag_t flags)
pts_meas_algorithms_t(* get_meas_algorithm)(pts_t *this)
void(* set_meas_algorithm)(pts_t *this, pts_meas_algorithms_t algorithm)
pts_meas_algorithms_t(* get_dh_hash_algorithm)(pts_t *this)
void(* set_dh_hash_algorithm)(pts_t *this, pts_meas_algorithms_t algorithm)
bool(* create_dh_nonce)(pts_t *this, pts_dh_group_t group, int nonce_len)
bool(* get_my_public_value)(pts_t *this, chunk_t *value, chunk_t *nonce)
bool(* set_peer_public_value)(pts_t *this, chunk_t value, chunk_t nonce)
bool(* calculate_secret)(pts_t *this)
int(* get_platform_id)(pts_t *this)
void(* set_platform_id)(pts_t *this, int pid)
bool(* get_tpm_version_info)(pts_t *this, chunk_t *info)
void(* set_tpm_version_info)(pts_t *this, chunk_t info)
certificate_t *(* get_aik)(pts_t *this)
void(* set_aik)(pts_t *this, certificate_t *aik, int aik_id)
int(* get_aik_id)(pts_t *this)
bool(* is_path_valid)(pts_t *this, char *path, pts_error_code_t *error_code)
pts_file_meta_t *(* get_metadata)(pts_t *this, char *pathname, bool is_dir)
bool(* read_pcr)(pts_t *this, u_int32_t pcr_num, chunk_t *pcr_value)
bool(* extend_pcr)(pts_t *this, u_int32_t pcr_num, chunk_t input, chunk_t *output)
bool(* quote_tpm)(pts_t *this, bool use_quote2, chunk_t *pcr_comp, chunk_t *quote_sig)
pts_pcr_t *(* get_pcrs)(pts_t *this)
bool(* get_quote_info)(pts_t *this, bool use_quote2, bool ver_info_included, pts_meas_algorithms_t comp_hash_algo, chunk_t *pcr_comp, chunk_t *quote_info)
bool(* verify_quote_signature)(pts_t *this, chunk_t data, chunk_t signature)
void(* destroy)(pts_t *this)
Detailed Description
Class implementing the TCG Platform Trust Service (PTS)
Definition at line 87 of file pts.h.
Member Data Documentation
bool(* pts_t::calculate_secret)(pts_t *this)
Calculates assessment secret to be used for TPM Quote as ExternalData
Returns
TRUE unless both DH public values and nonces are set
Definition at line 165 of file pts.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
bool(* pts_t::create_dh_nonce)(pts_t *this, pts_dh_group_t group, int nonce_len)
Create PTS Diffie-Hellman object and nonce
Parameters
group PTS DH group
nonce_len Nonce length
Returns
TRUE if creation was successful
Definition at line 139 of file pts.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
void(* pts_t::destroy)(pts_t *this)
Destroys a pts_t object.
Definition at line 306 of file pts.h.
bool(* pts_t::extend_pcr)(pts_t *this, u_int32_t pcr_num, chunk_t input, chunk_t *output)
Extends given PCR with given value Expects owner secret to be WELL_KNOWN_SECRET
Parameters
pcr_num Number of PCR to extend
input Value to extend
output Chunk to save PCR value after extension
Returns
FALSE in case of TSS error, TRUE otherwise
Definition at line 257 of file pts.h.
certificate_t*(* pts_t::get_aik)(pts_t *this)
Get Attestation Identity Certificate or Public Key
Returns
AIK Certificate or Public Key
Definition at line 201 of file pts.h.
Referenced by imc_attestation_process().
int(* pts_t::get_aik_id)(pts_t *this)
Get primary key referencing AIK in database
Returns
Primary key referencing AIK in database
Definition at line 216 of file pts.h.
Referenced by imv_attestation_build(), and METHOD().
pts_meas_algorithms_t(* pts_t::get_dh_hash_algorithm)(pts_t *this)
Get DH Hash Algorithm
Returns
DH hash algorithm
Definition at line 122 of file pts.h.
pts_meas_algorithms_t(* pts_t::get_meas_algorithm)(pts_t *this)
Get PTS Measurement Algorithm
Returns
PTS measurement algorithm
Definition at line 108 of file pts.h.
Referenced by imc_attestation_process(), imv_attestation_build(), and imv_attestation_process().
pts_file_meta_t*(* pts_t::get_metadata)(pts_t *this, char *pathname, bool is_dir)
Obtain file metadata
Parameters
pathname Absolute pathname of file/directory
is_dir TRUE if directory contents are requested
Returns
PTS File Metadata or NULL if FAILED
Definition at line 236 of file pts.h.
Referenced by imc_attestation_process().
bool(* pts_t::get_my_public_value)(pts_t *this, chunk_t *value, chunk_t *nonce)
Get my Diffie-Hellman public value
Parameters
value My public DH value
nonce My DH nonce
Returns
TRUE if public value retrieved successfully
Definition at line 148 of file pts.h.
Referenced by imc_attestation_process(), and imv_attestation_build().
pts_pcr_t*(* pts_t::get_pcrs)(pts_t *this)
Get the shadow PCR set
Returns
shadow PCR set
Definition at line 278 of file pts.h.
Referenced by METHOD().
int(* pts_t::get_platform_id)(pts_t *this)
Get primary key of platform entry in database
Returns
Platform and OS info
Definition at line 172 of file pts.h.
Referenced by imv_attestation_process(), and METHOD().
pts_proto_caps_flag_t(* pts_t::get_proto_caps)(pts_t *this)
Get PTS Protocol Capabilities
Returns
Protocol capabilities flags
Definition at line 94 of file pts.h.
Referenced by imc_attestation_process(), and METHOD().
bool(* pts_t::get_quote_info)(pts_t *this, bool use_quote2, bool ver_info_included, pts_meas_algorithms_t comp_hash_algo, chunk_t *pcr_comp, chunk_t *quote_info)
Constructs and returns TPM Quote Info structure expected from IMC
Parameters
use_quote2 Version of the TPM_QUOTE_INFO to be constructed
use_ver_info Version info is concatenated to TPM_QUOTE_INFO2
comp_hash_algo Composite Hash Algorithm
pcr_comp Output variable to store PCR Composite
quote_info Output variable to store TPM Quote Info
Returns
FALSE in case of any error, TRUE otherwise
Definition at line 290 of file pts.h.
Referenced by imv_attestation_process().
bool(* pts_t::get_tpm_version_info)(pts_t *this, chunk_t *info)
Get TPM 1.2 Version Info
Parameters
info chunk containing a TPM_CAP_VERSION_INFO struct
Returns
TRUE if TPM Version Info available
Definition at line 187 of file pts.h.
Referenced by imc_attestation_process().
bool(* pts_t::is_path_valid)(pts_t *this, char *path, pts_error_code_t *error_code)
Check whether path is valid file/directory on filesystem
Parameters
path Absolute path
error_code Output variable for PTS error code
Returns
TRUE if path is valid or file/directory doesn't exist or path is invalid FALSE if local error occurred within stat function
Definition at line 227 of file pts.h.
Referenced by imc_attestation_process().
bool(* pts_t::quote_tpm)(pts_t *this, bool use_quote2, chunk_t *pcr_comp, chunk_t *quote_sig)
Quote over PCR's Expects owner and SRK secret to be WELL_KNOWN_SECRET and no password set for AIK
Parameters
use_quote2 Version of the Quote function to be used
pcr_comp Chunk to save PCR composite structure
quote_sig Chunk to save quote operation output without external data (anti-replay protection)
Returns
FALSE in case of TSS error, TRUE otherwise
Definition at line 270 of file pts.h.
Referenced by imc_attestation_process().
bool(* pts_t::read_pcr)(pts_t *this, u_int32_t pcr_num, chunk_t *pcr_value)
Reads given PCR value and returns it Expects owner secret to be WELL_KNOWN_SECRET
Parameters
pcr_num Number of PCR to read
pcr_value Chunk to save pcr read output
Returns
NULL in case of TSS error, PCR value otherwise
Definition at line 246 of file pts.h.
Referenced by METHOD().
void(* pts_t::set_aik)(pts_t *this, certificate_t *aik, int aik_id)
Set Attestation Identity Certificate or Public Key
Parameters
aik AIK Certificate or Public Key
aik_id Primary key referencing AIK in database
Definition at line 209 of file pts.h.
Referenced by imv_attestation_process().
void(* pts_t::set_dh_hash_algorithm)(pts_t *this, pts_meas_algorithms_t algorithm)
Set DH Hash Algorithm
Parameters
algorithm DH hash algorithm
Definition at line 129 of file pts.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
void(* pts_t::set_meas_algorithm)(pts_t *this, pts_meas_algorithms_t algorithm)
Set PTS Measurement Algorithm
Parameters
algorithm PTS measurement algorithm
Definition at line 115 of file pts.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
bool(* pts_t::set_peer_public_value)(pts_t *this, chunk_t value, chunk_t nonce)
Set peer Diffie.Hellman public value
Parameters
value Peer public DH value
nonce Peer DH nonce
Returns
TRUE if public value set successfully
Definition at line 157 of file pts.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
void(* pts_t::set_platform_id)(pts_t *this, int pid)
Set primary key of platform entry in database
Parameters
pid Primary key of platform entry in database
Definition at line 179 of file pts.h.
Referenced by METHOD().
void(* pts_t::set_proto_caps)(pts_t *this, pts_proto_caps_flag_t flags)
Set PTS Protocol Capabilities
Parameters
flags Protocol capabilities flags
Definition at line 101 of file pts.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
void(* pts_t::set_tpm_version_info)(pts_t *this, chunk_t info)
Set TPM 1.2 Version Info
Parameters
info chunk containing a TPM_CAP_VERSION_INFO struct
Definition at line 194 of file pts.h.
Referenced by imv_attestation_process().
bool(* pts_t::verify_quote_signature)(pts_t *this, chunk_t data, chunk_t signature)
Constructs and returns PCR Quote Digest structure expected from IMC
Parameters
data Calculated TPM Quote Digest
signature TPM Quote Signature received from IMC
Returns
FALSE if signature is not verified
Definition at line 301 of file pts.h.
Referenced by imv_attestation_process().
The documentation for this struct was generated from the following file:
pts.h