strongSwan: esp_packet.c File Reference
esp_packet.c File Reference
#include "esp_packet.h"
#include <library.h>
#include <utils/debug.h>
#include <crypto/crypters/crypter.h>
#include <crypto/signers/signer.h>
#include <bio/bio_reader.h>
#include <bio/bio_writer.h>
#include <netinet/in.h>
Classes
struct private_esp_packet_t
Typedefs
typedef struct private_esp_packet_t private_esp_packet_t
Functions
static private_esp_packet_t * esp_packet_create_internal (packet_t *packet)
METHOD (packet_t, set_source, void, private_esp_packet_t *this, host_t *src)
METHOD2 (esp_packet_t, packet_t, get_source, host_t *, private_esp_packet_t *this)
METHOD (packet_t, set_destination, void, private_esp_packet_t *this, host_t *dst)
METHOD2 (esp_packet_t, packet_t, get_destination, host_t *, private_esp_packet_t *this)
METHOD (packet_t, get_data, chunk_t, private_esp_packet_t *this)
METHOD (packet_t, set_data, void, private_esp_packet_t *this, chunk_t data)
METHOD (packet_t, get_dscp, u_int8_t, private_esp_packet_t *this)
METHOD (packet_t, set_dscp, void, private_esp_packet_t *this, u_int8_t value)
METHOD (packet_t, skip_bytes, void, private_esp_packet_t *this, size_t bytes)
METHOD (packet_t, clone_, packet_t *, private_esp_packet_t *this)
METHOD (esp_packet_t, parse_header, bool, private_esp_packet_t *this, u_int32_t *spi)
static bool check_padding (chunk_t padding)
static bool remove_padding (private_esp_packet_t *this, chunk_t plaintext)
METHOD (esp_packet_t, decrypt, status_t, private_esp_packet_t *this, esp_context_t *esp_context)
static void generate_padding (chunk_t padding)
METHOD (esp_packet_t, encrypt, status_t, private_esp_packet_t *this, esp_context_t *esp_context, u_int32_t spi)
METHOD (esp_packet_t, get_next_header, u_int8_t, private_esp_packet_t *this)
METHOD (esp_packet_t, get_payload, ip_packet_t *, private_esp_packet_t *this)
METHOD (esp_packet_t, extract_payload, ip_packet_t *, private_esp_packet_t *this)
METHOD2 (esp_packet_t, packet_t, destroy, void, private_esp_packet_t *this)
esp_packet_t * esp_packet_create_from_packet (packet_t *packet)
esp_packet_t * esp_packet_create_from_payload (host_t *src, host_t *dst, ip_packet_t *payload)
Typedef Documentation
typedef struct private_esp_packet_t private_esp_packet_t
Definition at line 30 of file esp_packet.c.
Function Documentation
static bool check_padding (chunk_t padding) static
Check padding as specified in RFC 4303
Definition at line 153 of file esp_packet.c.
References FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by remove_padding().
 {
     size_t i;
     for (i = 0; i < padding.len; ++i)
     {
         if (padding.ptr[i] != (u_int8_t)(i + 1))
         {
             return FALSE;
         }
     }
     return TRUE;
 }
static private_esp_packet_t * esp_packet_create_internal (packet_t * packet) static
Forward declaration for clone()
Definition at line 401 of file esp_packet.c.
References INIT.
Referenced by esp_packet_create_from_packet(), esp_packet_create_from_payload(), and METHOD().
 {
     private_esp_packet_t *this;
     INIT(this,
         .public = {
             .packet = {
                 .set_source = _set_source,
                 .get_source = _get_source,
                 .set_destination = _set_destination,
                 .get_destination = _get_destination,
                 .get_data = _get_data,
                 .set_data = _set_data,
                 .get_dscp = _get_dscp,
                 .set_dscp = _set_dscp,
                 .skip_bytes = _skip_bytes,
                 .clone = _clone_,
                 .destroy = _destroy,
             },
             .get_source = _get_source,
             .get_destination = _get_destination,
             .get_next_header = _get_next_header,
             .parse_header = _parse_header,
             .decrypt = _decrypt,
             .encrypt = _encrypt,
             .get_payload = _get_payload,
             .extract_payload = _extract_payload,
             .destroy = _destroy,
         },
         .packet = packet,
         .next_header = IPPROTO_NONE,
     );
     return this;
 }
static void generate_padding (chunk_t padding) static
Generate the padding as specified in RFC4303
Definition at line 269 of file esp_packet.c.
References chunk_t::len, and chunk_t::ptr.
Referenced by METHOD().
 {
     size_t i;
     for (i = 0; i < padding.len; ++i)
     {
         padding.ptr[i] = (u_int8_t)(i + 1);
     }
 }
METHOD (packet_t , set_source , void , private_esp_packet_t * this, host_t * src)
Definition at line 64 of file esp_packet.c.
 {
     return this->packet->set_source(this->packet, src);
 }
METHOD (packet_t , set_destination , void , private_esp_packet_t * this, host_t * dst)
Definition at line 76 of file esp_packet.c.
 {
     return this->packet->set_destination(this->packet, dst);
 }
METHOD (packet_t , get_data , chunk_t , private_esp_packet_t * this)
Definition at line 88 of file esp_packet.c.
 {
     return this->packet->get_data(this->packet);
 }
METHOD (packet_t , set_data , void , private_esp_packet_t * this, chunk_t data)
Definition at line 94 of file esp_packet.c.
 {
     return this->packet->set_data(this->packet, data);
 }
METHOD (packet_t , get_dscp , u_int8_t , private_esp_packet_t * this)
Definition at line 100 of file esp_packet.c.
 {
     return this->packet->get_dscp(this->packet);
 }
METHOD (packet_t , set_dscp , void , private_esp_packet_t * this, u_int8_t value)
Definition at line 106 of file esp_packet.c.
 {
     this->packet->set_dscp(this->packet, value);
 }
METHOD (packet_t , skip_bytes , void , private_esp_packet_t * this, size_t bytes)
Definition at line 112 of file esp_packet.c.
 {
     return this->packet->skip_bytes(this->packet, bytes);
 }
METHOD (packet_t , clone_ , packet_t * , private_esp_packet_t * this)
Definition at line 118 of file esp_packet.c.
References ip_packet_t::clone, esp_packet_create_internal(), private_esp_packet_t::next_header, esp_packet_t::packet, private_esp_packet_t::payload, and private_esp_packet_t::public.
 {
     private_esp_packet_t *pkt;
     pkt = esp_packet_create_internal(this->packet->clone(this->packet));
     pkt->payload = this->payload ? this->payload->clone(this->payload) : NULL;
     pkt->next_header = this->next_header;
     return &pkt->public.packet;
 }
METHOD (esp_packet_t , parse_header , bool , private_esp_packet_t * this, u_int32_t * spi)
Definition at line 129 of file esp_packet.c.
References bio_reader_create(), DBG1, DBG2, DBG_ESP, bio_reader_t::destroy, FALSE, bio_reader_t::read_uint32, seq, and TRUE.
 {
     bio_reader_t *reader;
     u_int32_t seq;
     reader = bio_reader_create(this->packet->get_data(this->packet));
     if (!reader->read_uint32(reader, spi) ||
         !reader->read_uint32(reader, &seq))
     {
         DBG1(DBG_ESP, "failed to parse ESP header: invalid length");
         reader->destroy(reader);
         return FALSE;
     }
     reader->destroy(reader);
     DBG2(DBG_ESP, "parsed ESP header with SPI %.8x [seq %u]", *spi, seq);
     *spi = htonl(*spi);
     return TRUE;
 }
METHOD (esp_packet_t , decrypt , status_t , private_esp_packet_t * this, esp_context_t * esp_context)
Definition at line 210 of file esp_packet.c.
References aead, bio_reader_create(), chunk_create(), data, DBG1, DBG3, DBG_ESP, aead_t::decrypt, bio_reader_t::destroy, DESTROY_IF, FAILED, esp_context_t::get_aead, aead_t::get_block_size, aead_t::get_icv_size, aead_t::get_iv_size, chunk_t::len, PARSE_ERROR, bio_reader_t::peek, chunk_t::ptr, bio_reader_t::read_data, bio_reader_t::read_data_end, bio_reader_t::read_uint32, bio_reader_t::remaining, remove_padding(), seq, esp_context_t::set_authenticated_seqno, SUCCESS, VERIFY_ERROR, and esp_context_t::verify_seqno.
 {
     bio_reader_t *reader;
     u_int32_t spi, seq;
     chunk_t data, iv, icv, aad, ciphertext, plaintext;
     aead_t *aead;
     DESTROY_IF(this->payload);
     this->payload = NULL;
     data = this->packet->get_data(this->packet);
     aead = esp_context->get_aead(esp_context);
     reader = bio_reader_create(data);
     if (!reader->read_uint32(reader, &spi) ||
         !reader->read_uint32(reader, &seq) ||
         !reader->read_data(reader, aead->get_iv_size(aead), &iv) ||
         !reader->read_data_end(reader, aead->get_icv_size(aead), &icv) ||
         reader->remaining(reader) % aead->get_block_size(aead))
     {
         DBG1(DBG_ESP, "ESP decryption failed: invalid length");
         return PARSE_ERROR;
     }
     ciphertext = reader->peek(reader);
     reader->destroy(reader);
     if (!esp_context->verify_seqno(esp_context, seq))
     {
         DBG1(DBG_ESP, "ESP sequence number verification failed:\n  "
              "src %H, dst %H, SPI %.8x [seq %u]",
              get_source(this), get_destination(this), spi, seq);
         return VERIFY_ERROR;
     }
     DBG3(DBG_ESP, "ESP decryption:\n  SPI %.8x [seq %u]\n  IV %B\n  "
          "encrypted %B\n  ICV %B", spi, seq, &iv, &ciphertext, &icv);
     /* include ICV in ciphertext for decryption/verification */
     ciphertext.len += icv.len;
     /* aad = spi + seq */
     aad = chunk_create(data.ptr, 8);
     if (!aead->decrypt(aead, ciphertext, aad, iv, &plaintext))
     {
         DBG1(DBG_ESP, "ESP decryption or ICV verification failed");
         return FAILED;
     }
     esp_context->set_authenticated_seqno(esp_context, seq);
     if (!remove_padding(this, plaintext))
     {
         return PARSE_ERROR;
     }
     return SUCCESS;
 }
METHOD (esp_packet_t , encrypt , status_t , private_esp_packet_t * this, esp_context_t * esp_context, u_int32_t spi)
Definition at line 279 of file esp_packet.c.
References aead, bio_writer_create(), chunk_empty, DBG1, DBG3, DBG_ESP, bio_writer_t::destroy, aead_t::encrypt, bio_writer_t::extract_buf, FAILED, generate_padding(), esp_context_t::get_aead, aead_t::get_block_size, bio_writer_t::get_buf, aead_t::get_icv_size, iv_gen_t::get_iv, aead_t::get_iv_gen, aead_t::get_iv_size, chunk_t::len, esp_context_t::next_seqno, NOT_FOUND, pad_len(), padding, chunk_t::ptr, bio_writer_t::skip, SUCCESS, bio_writer_t::write_data, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     chunk_t iv, icv, aad, padding, payload, ciphertext;
     bio_writer_t *writer;
     u_int32_t next_seqno;
     size_t blocksize, plainlen;
     aead_t *aead;
     iv_gen_t *iv_gen;
     this->packet->set_data(this->packet, chunk_empty);
     if (!esp_context->next_seqno(esp_context, &next_seqno))
     {
         DBG1(DBG_ESP, "ESP encapsulation failed: sequence numbers cycled");
         return FAILED;
     }
     aead = esp_context->get_aead(esp_context);
     iv_gen = aead->get_iv_gen(aead);
     if (!iv_gen)
     {
         DBG1(DBG_ESP, "ESP encryption failed: no IV generator");
         return NOT_FOUND;
     }
     blocksize = aead->get_block_size(aead);
     iv.len = aead->get_iv_size(aead);
     icv.len = aead->get_icv_size(aead);
     /* plaintext = payload, padding, pad_length, next_header */
     payload = this->payload ? this->payload->get_encoding(this->payload)
                             : chunk_empty;
     plainlen = payload.len + 2;
     padding.len = pad_len(plainlen, blocksize);
     /* ICV must be on a 4-byte boundary */
     padding.len += pad_len(iv.len + plainlen + padding.len, 4);
     plainlen += padding.len;
     /* len = spi, seq, IV, plaintext, ICV */
     writer = bio_writer_create(2 * sizeof(u_int32_t) + iv.len + plainlen +
                                icv.len);
     writer->write_uint32(writer, ntohl(spi));
     writer->write_uint32(writer, next_seqno);
     iv = writer->skip(writer, iv.len);
     if (!iv_gen->get_iv(iv_gen, next_seqno, iv.len, iv.ptr))
     {
         DBG1(DBG_ESP, "ESP encryption failed: could not generate IV");
         writer->destroy(writer);
         return FAILED;
     }
     /* plain-/ciphertext will start here */
     ciphertext = writer->get_buf(writer);
     ciphertext.ptr += ciphertext.len;
     ciphertext.len = plainlen;
     writer->write_data(writer, payload);
     padding = writer->skip(writer, padding.len);
     generate_padding(padding);
     writer->write_uint8(writer, padding.len);
     writer->write_uint8(writer, this->next_header);
     /* aad = spi + seq */
     aad = writer->get_buf(writer);
     aad.len = 8;
     icv = writer->skip(writer, icv.len);
     DBG3(DBG_ESP, "ESP before encryption:\n  payload = %B\n  padding = %B\n  "
          "padding length = %hhu, next header = %hhu", &payload, &padding,
          (u_int8_t)padding.len, this->next_header);
     /* encrypt/authenticate the content inline */
     if (!aead->encrypt(aead, ciphertext, aad, iv, NULL))
     {
         DBG1(DBG_ESP, "ESP encryption or ICV generation failed");
         writer->destroy(writer);
         return FAILED;
     }
     DBG3(DBG_ESP, "ESP packet:\n  SPI %.8x [seq %u]\n  IV %B\n  "
          "encrypted %B\n  ICV %B", ntohl(spi), next_seqno, &iv,
          &ciphertext, &icv);
     this->packet->set_data(this->packet, writer->extract_buf(writer));
     writer->destroy(writer);
     return SUCCESS;
 }
METHOD (esp_packet_t , get_next_header , u_int8_t , private_esp_packet_t * this)
Definition at line 371 of file esp_packet.c.
 {
     return this->next_header;
 }
METHOD (esp_packet_t , get_payload , ip_packet_t * , private_esp_packet_t * this)
Definition at line 377 of file esp_packet.c.
 {
     return this->payload;
 }
METHOD (esp_packet_t , extract_payload , ip_packet_t * , private_esp_packet_t * this)
Definition at line 383 of file esp_packet.c.
 {
     ip_packet_t *payload;
     payload = this->payload;
     this->payload = NULL;
     return payload;
 }
METHOD2 (esp_packet_t , packet_t , get_source , host_t * , private_esp_packet_t * this)
Definition at line 70 of file esp_packet.c.
 {
     return this->packet->get_source(this->packet);
 }
METHOD2 (esp_packet_t , packet_t , get_destination , host_t * , private_esp_packet_t * this)
Definition at line 82 of file esp_packet.c.
 {
     return this->packet->get_destination(this->packet);
 }
METHOD2 (esp_packet_t , packet_t , destroy , void , private_esp_packet_t * this)
Definition at line 393 of file esp_packet.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->payload);
     this->packet->destroy(this->packet);
     free(this);
 }
static bool remove_padding (private_esp_packet_t * this, chunk_t plaintext) static
Remove the padding from the payload and set the next header info
Definition at line 170 of file esp_packet.c.
References bio_reader_create(), check_padding(), chunk_free(), DBG1, DBG3, DBG_ESP, bio_reader_t::destroy, FALSE, ip_packet_create(), padding, bio_reader_t::peek, bio_reader_t::read_data_end, bio_reader_t::read_uint8_end, and TRUE.
Referenced by METHOD().
 {
     u_int8_t next_header, pad_length;
     chunk_t padding, payload;
     bio_reader_t *reader;
     reader = bio_reader_create(plaintext);
     if (!reader->read_uint8_end(reader, &next_header) ||
         !reader->read_uint8_end(reader, &pad_length))
     {
         DBG1(DBG_ESP, "parsing ESP payload failed: invalid length");
         goto failed;
     }
     if (!reader->read_data_end(reader, pad_length, &padding) ||
         !check_padding(padding))
     {
         DBG1(DBG_ESP, "parsing ESP payload failed: invalid padding");
         goto failed;
     }
     this->payload = ip_packet_create(reader->peek(reader));
     reader->destroy(reader);
     if (!this->payload)
     {
         DBG1(DBG_ESP, "parsing ESP payload failed: unsupported payload");
         return FALSE;
     }
     this->next_header = next_header;
     payload = this->payload->get_encoding(this->payload);
     DBG3(DBG_ESP, "ESP payload:\n  payload %B\n  padding %B\n  "
          "padding length = %hhu, next header = %hhu", &payload, &padding,
          pad_length, this->next_header);
     return TRUE;
 failed:
     reader->destroy(reader);
     chunk_free(&plaintext);
     return FALSE;
 }