strongSwan: kernel_iph_net
kernel_iph_net
kernel_iph
Classes
struct kernel_iph_net_t
Typedefs
typedef struct kernel_iph_net_t kernel_iph_net_t
Functions
kernel_iph_net_t * kernel_iph_net_create ()
Detailed Description
Typedef Documentation
typedef struct kernel_iph_net_t kernel_iph_net_t
Definition at line 26 of file kernel_iph_net.h.
Function Documentation
kernel_iph_net_t* kernel_iph_net_create ()
Create IP Helper network backend instance.
Returns
kernel_iph_net_t instance
Definition at line 737 of file kernel_iph_net.c.
References change_interface(), DBG1, DBG_KNL, destroy(), FALSE, INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, res, and TRUE.
Referenced by METHOD().
 {
     private_kernel_iph_net_t *this;
     ULONG res;
     INIT(this,
         .public = {
             .interface = {
                 .get_interface = _get_interface_name,
                 .create_address_enumerator = _create_address_enumerator,
                 .get_source_addr = _get_source_addr,
                 .get_nexthop = _get_nexthop,
                 .add_ip = _add_ip,
                 .del_ip = _del_ip,
                 .add_route = _add_route,
                 .del_route = _del_route,
                 .destroy = _destroy,
             },
         },
         .router = {
             .hEvent = CreateEvent(NULL, FALSE, FALSE, NULL),
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .ifaces = linked_list_create(),
     );
     /* PIPINTERFACE_CHANGE_CALLBACK is not using WINAPI in MinGW, which seems
      * to be wrong. Force a cast to our WINAPI call */
     res = NotifyIpInterfaceChange(AF_UNSPEC, (void*)change_interface,
                                   this, TRUE, &this->changes);
     if (res != NO_ERROR)
     {
         DBG1(DBG_KNL, "registering for IPH interface changes failed: 0x%08lx",
              res);
         destroy(this);
         return NULL;
     }
     return &this->public;
 }