strongSwan: test_crypter.c File Reference
test_crypter.c File Reference
#include "test_suite.h"
#include <crypto/crypters/crypter.h>
#include <asn1/oid.h>
#include <utils/test.h>
Classes
struct crypter_oid_t
struct crypter_aead_t
Functions
START_TEST (test_crypter_from_oid)
END_TEST START_TEST (test_crypter_to_oid)
START_TEST (test_crypter_is_aead)
END_TEST Suite * crypter_suite_create ()
Variables
static crypter_oid_t oids []
static crypter_aead_t aead []
Function Documentation
END_TEST Suite* crypter_suite_create ()
Definition at line 87 of file test_crypter.c.
References countof, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("crypter");
     tc = tcase_create("from_oid");
     tcase_add_loop_test(tc, test_crypter_from_oid, 2, countof(oids));
     suite_add_tcase(s, tc);
     tc = tcase_create("to_oid");
     tcase_add_loop_test(tc, test_crypter_to_oid, 0, countof(oids));
     suite_add_tcase(s, tc);
     tc = tcase_create("is_aead");
     tcase_add_loop_test(tc, test_crypter_is_aead, 0, countof(aead));
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_crypter_from_oid)
Definition at line 42 of file test_crypter.c.
References alg, ck_assert, encryption_algorithm_from_oid(), and key_size.
 {
     size_t key_size;
     ck_assert(encryption_algorithm_from_oid(oids[_i].oid, NULL) ==
                                             oids[_i].alg);
     ck_assert(encryption_algorithm_from_oid(oids[_i].oid, &key_size) ==
                                             oids[_i].alg);
     ck_assert(key_size == oids[_i].key_size);
 }
END_TEST START_TEST (test_crypter_to_oid)
Definition at line 54 of file test_crypter.c.
References alg, ck_assert, encryption_algorithm_to_oid(), and key_size.
 {
     ck_assert(encryption_algorithm_to_oid(oids[_i].alg,
                                           oids[_i].key_size) == oids[_i].oid);
 }
START_TEST (test_crypter_is_aead)
Definition at line 81 of file test_crypter.c.
References alg, ck_assert, and encryption_algorithm_is_aead().
 {
     ck_assert(encryption_algorithm_is_aead(aead[_i].alg) == aead[_i].is_aead);
 }
Variable Documentation
crypter_aead_t aead[] static
Initial value:
= {
    { ENCR_AES_CCM_ICV8, TRUE },
    { ENCR_AES_CCM_ICV12, TRUE },
    { ENCR_AES_CCM_ICV16, TRUE },
    { ENCR_AES_GCM_ICV8, TRUE },
    { ENCR_AES_GCM_ICV12, TRUE },
    { ENCR_AES_GCM_ICV16, TRUE },
    { ENCR_NULL_AUTH_AES_GMAC, TRUE },
    { ENCR_CAMELLIA_CCM_ICV8, TRUE },
    { ENCR_CAMELLIA_CCM_ICV12, TRUE },
    { ENCR_CAMELLIA_CCM_ICV16, TRUE },
    { ENCR_AES_CBC, FALSE },
    { ENCR_CAMELLIA_CBC, FALSE }
}
Definition at line 66 of file test_crypter.c.
crypter_oid_t oids[] static
Initial value:
= {
    { OID_UNKNOWN, ENCR_AES_CBC, 0 },
    { OID_UNKNOWN, ENCR_CAMELLIA_CBC, 0 },
    { OID_UNKNOWN, ENCR_UNDEFINED, 0 },
    { OID_DES_CBC, ENCR_DES, 0 },
    { OID_3DES_EDE_CBC, ENCR_3DES, 0 },
    { OID_AES128_CBC, ENCR_AES_CBC, 128 },
    { OID_AES192_CBC, ENCR_AES_CBC, 192 },
    { OID_AES256_CBC, ENCR_AES_CBC, 256 },
    { OID_CAMELLIA128_CBC, ENCR_CAMELLIA_CBC, 128 },
    { OID_CAMELLIA192_CBC, ENCR_CAMELLIA_CBC, 192 },
    { OID_CAMELLIA256_CBC, ENCR_CAMELLIA_CBC, 256 }
}
Definition at line 28 of file test_crypter.c.