strongSwan: unity_plugin.c File Reference
unity_plugin.c File Reference
#include "unity_plugin.h"
#include "unity_handler.h"
#include "unity_narrow.h"
#include "unity_provider.h"
#include <daemon.h>
Classes
struct private_unity_plugin_t
Typedefs
typedef struct
private_unity_plugin_t private_unity_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_unity_plugin_t *this)
static bool plugin_cb (private_unity_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_unity_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_unity_plugin_t *this)
plugin_t * unity_plugin_create ()
Typedef Documentation
typedef struct private_unity_plugin_t private_unity_plugin_t
Definition at line 23 of file unity_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_unity_plugin_t * this)
Definition at line 51 of file unity_plugin.c.
 {
     return "unity";
 }
METHOD (plugin_t , get_features , int , private_unity_plugin_t * this, plugin_feature_t * features[])
Definition at line 83 of file unity_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "unity"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_unity_plugin_t * this)
Definition at line 94 of file unity_plugin.c.
References free().
 {
     this->narrower->destroy(this->narrower);
     this->handler->destroy(this->handler);
     this->provider->destroy(this->provider);
     free(this);
 }
static bool plugin_cb (private_unity_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 60 of file unity_plugin.c.
References attribute_manager_t::add_handler, bus_t::add_listener, attribute_manager_t::add_provider, daemon_t::attributes, daemon_t::bus, charon, attribute_manager_t::remove_handler, bus_t::remove_listener, attribute_manager_t::remove_provider, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->attributes->add_handler(charon->attributes,
                                         &this->handler->handler);
         charon->attributes->add_provider(charon->attributes,
                                          &this->provider->provider);
         charon->bus->add_listener(charon->bus, &this->narrower->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->narrower->listener);
         charon->attributes->remove_handler(charon->attributes,
                                            &this->handler->handler);
         charon->attributes->remove_provider(charon->attributes,
                                             &this->provider->provider);
     }
     return TRUE;
 }
plugin_t* unity_plugin_create ()
Definition at line 106 of file unity_plugin.c.
References INIT, unity_handler_create(), unity_narrow_create(), and unity_provider_create().
 {
     private_unity_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .handler = unity_handler_create(),
         .provider = unity_provider_create(),
     );
     this->narrower = unity_narrow_create(this->handler);
     return &this->public.plugin;
 }