strongSwan: sqlite_database
sqlite_database
sqlite
Classes
struct sqlite_database_t
Typedefs
typedef struct sqlite_database_t sqlite_database_t
Functions
sqlite_database_t * sqlite_database_create (char *uri)
Detailed Description
Typedef Documentation
typedef struct sqlite_database_t sqlite_database_t
Definition at line 26 of file sqlite_database.h.
Function Documentation
sqlite_database_t* sqlite_database_create (char * uri)
Create a sqlite_database instance.
Parameters
uri connection URI, sqlite:///path/to/file.db
parse sqlite:///path/to/file.db uri
Definition at line 427 of file sqlite_database.c.
References busy_handler(), db, DBG1, DBG_LIB, destroy(), INIT, mutex_create(), MUTEX_TYPE_RECURSIVE, strpfx(), and thread_value_create().
Referenced by METHOD().
 {
     char *file;
     private_sqlite_database_t *this;
     if (!strpfx(uri, "sqlite://"))
     {
         return NULL;
     }
     file = uri + 9;
     INIT(this,
         .public = {
             .db = {
                 .query = _query,
                 .execute = _execute,
                 .transaction = _transaction,
                 .commit = _commit_,
                 .rollback = _rollback,
                 .get_driver = _get_driver,
                 .destroy = _destroy,
             },
         },
         .mutex = mutex_create(MUTEX_TYPE_RECURSIVE),
         .transaction = thread_value_create(NULL),
     );
     if (sqlite3_open(file, &this->db) != SQLITE_OK)
     {
         DBG1(DBG_LIB, "opening SQLite database '%s' failed: %s",
              file, sqlite3_errmsg(this->db));
         destroy(this);
         return NULL;
     }
     sqlite3_busy_handler(this->db, (void*)busy_handler, this);
     return &this->public;
 }