strongSwan: tun_device
tun_device
networking
Classes
struct tun_device_t
Typedefs
typedef struct tun_device_t tun_device_t
Functions
tun_device_t * tun_device_create (const char *name_tmpl)
Detailed Description
Typedef Documentation
typedef struct tun_device_t tun_device_t
Definition at line 28 of file tun_device.h.
Function Documentation
tun_device_t* tun_device_create (const char * name_tmpl)
Create a TUN device using the given name template.
Parameters
name_tmpl name template, defaults to "tun%d" if not given
Returns
TUN device
Definition at line 26 of file tun_device.c.
References DBG1, and DBG_LIB.
Referenced by kernel_libipsec_plugin_create(), METHOD(), and nm_strongswan_plugin_init().
 {
     DBG1(DBG_LIB, "TUN devices are not supported");
     return NULL;
 }