strongSwan: identification.c File Reference
identification.c File Reference
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include "identification.h"
#include <utils/utils.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <crypto/hashers/hasher.h>
Classes
struct x501rdn_t
struct private_identification_t
struct rdn_enumerator_t
struct rdn_part_enumerator_t
Macros
#define RDN_MAX 20
Typedefs
typedef struct
private_identification_t private_identification_t
Functions
ENUM_BEGIN (id_match_names, ID_MATCH_NONE, ID_MATCH_MAX_WILDCARDS,"MATCH_NONE","MATCH_ANY","MATCH_MAX_WILDCARDS")
ENUM_NEXT (id_match_names, ID_MATCH_PERFECT, ID_MATCH_PERFECT, ID_MATCH_MAX_WILDCARDS,"MATCH_PERFECT")
ENUM_END (id_match_names, ID_MATCH_PERFECT)
ENUM_BEGIN (id_type_names, ID_ANY, ID_KEY_ID,"ID_ANY","ID_IPV4_ADDR","ID_FQDN","ID_RFC822_ADDR","ID_IPV4_ADDR_SUBNET","ID_IPV6_ADDR","ID_IPV6_ADDR_SUBNET","ID_IPV4_ADDR_RANGE","ID_IPV6_ADDR_RANGE","ID_DER_ASN1_DN","ID_DER_ASN1_GN","ID_KEY_ID")
ENUM_NEXT (id_type_names, ID_DER_ASN1_GN_URI, ID_DER_ASN1_GN_URI, ID_KEY_ID,"ID_DER_ASN1_GN_URI")
ENUM_END (id_type_names, ID_DER_ASN1_GN_URI)
METHOD (enumerator_t, rdn_enumerate, bool, rdn_enumerator_t *this, chunk_t *oid, u_char *type, chunk_t *data)
static enumerator_t * create_rdn_enumerator (chunk_t dn)
METHOD (enumerator_t, rdn_part_enumerate, bool, rdn_part_enumerator_t *this, id_part_t *type, chunk_t *data)
METHOD (enumerator_t, rdn_part_enumerator_destroy, void, rdn_part_enumerator_t *this)
METHOD (identification_t, create_part_enumerator, enumerator_t *, private_identification_t *this)
static bool print_separator (char **buf, size_t *len)
static void dntoa (chunk_t dn, char *buf, size_t len)
static status_t atodn (char *src, chunk_t *dn)
METHOD (identification_t, get_encoding, chunk_t, private_identification_t *this)
METHOD (identification_t, get_type, id_type_t, private_identification_t *this)
METHOD (identification_t, contains_wildcards_dn, bool, private_identification_t *this)
METHOD (identification_t, contains_wildcards_memchr, bool, private_identification_t *this)
METHOD (identification_t, hash_binary, u_int, private_identification_t *this, u_int inc)
METHOD (identification_t, equals_binary, bool, private_identification_t *this, identification_t *other)
static bool compare_dn (chunk_t t_dn, chunk_t o_dn, int *wc)
METHOD (identification_t, equals_dn, bool, private_identification_t *this, identification_t *other)
METHOD (identification_t, hash_dn, u_int, private_identification_t *this, u_int inc)
METHOD (identification_t, equals_strcasecmp, bool, private_identification_t *this, identification_t *other)
METHOD (identification_t, matches_binary, id_match_t, private_identification_t *this, identification_t *other)
METHOD (identification_t, matches_string, id_match_t, private_identification_t *this, identification_t *other)
METHOD (identification_t, matches_any, id_match_t, private_identification_t *this, identification_t *other)
METHOD (identification_t, matches_dn, id_match_t, private_identification_t *this, identification_t *other)
int identification_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
METHOD (identification_t, clone_, identification_t *, private_identification_t *this)
METHOD (identification_t, destroy, void, private_identification_t *this)
static private_identification_t * identification_create (id_type_t type)
static private_identification_t * create_from_string_with_prefix_type (char *str)
static private_identification_t * create_from_string_with_num_type (char *str)
identification_t * identification_create_from_string (char *string)
identification_t * identification_create_from_data (chunk_t data)
identification_t * identification_create_from_encoding (id_type_t type, chunk_t encoded)
identification_t * identification_create_from_sockaddr (sockaddr_t *sockaddr)
Variables
static const x501rdn_t x501rdns []
Macro Definition Documentation
#define RDN_MAX 20
maximum number of RDNs in atodn()
Definition at line 98 of file identification.c.
Referenced by atodn().
Typedef Documentation
typedef struct private_identification_t private_identification_t
Definition at line 101 of file identification.c.
Function Documentation
static status_t atodn (char * src, chunk_t * dn) static
Converts an LDAP-style human-readable ASCII-encoded ASN.1 distinguished name into binary DER-encoded format
Definition at line 376 of file identification.c.
References asn1_build_known_oid(), asn1_build_object(), asn1_is_printablestring(), ASN1_PRINTABLESTRING, ASN1_SEQUENCE, ASN1_SET, ASN1_UTF8STRING, asn1_wrap(), chunk_empty, countof, FALSE, found, free(), INVALID_ARG, chunk_t::len, len, memcpy, name, NOT_SUPPORTED, OUT_OF_RES, chunk_t::ptr, RDN_MAX, sep, src, status, SUCCESS, TRUE, type, and x501rdn_t::type.
Referenced by identification_create_from_string().
 {
     /* finite state machine for atodn */
     typedef enum {
         SEARCH_OID =    0,
         READ_OID =      1,
         SEARCH_NAME =   2,
         READ_NAME =     3,
         UNKNOWN_OID =   4
     } state_t;
     chunk_t oid  = chunk_empty;
     chunk_t name = chunk_empty;
     chunk_t rdns[RDN_MAX];
     int rdn_count = 0;
     int dn_len = 0;
     int whitespace = 0;
     int i = 0;
     asn1_t rdn_type;
     state_t state = SEARCH_OID;
     status_t status = SUCCESS;
     char sep = '\0';
     do
     {
         switch (state)
         {
             case SEARCH_OID:
                 if (!sep && *src == '/')
                 {   /* use / as separator if the string starts with a slash */
                     sep = '/';
                     break;
                 }
                 if (*src != ' ' && *src != '\0')
                 {
                     if (!sep)
                     {   /* use , as separator by default */
                         sep = ',';
                     }
                     oid.ptr = src;
                     oid.len = 1;
                     state = READ_OID;
                 }
                 break;
             case READ_OID:
                 if (*src != ' ' && *src != '=')
                 {
                     oid.len++;
                 }
                 else
                 {
                     bool found = FALSE;
                     for (i = 0; i < countof(x501rdns); i++)
                     {
                         if (strlen(x501rdns[i].name) == oid.len &&
                             strncasecmp(x501rdns[i].name, oid.ptr, oid.len) == 0)
{
                             found = TRUE;
                             break;
                         }
                     }
                     if (!found)
                     {
                         status = NOT_SUPPORTED;
                         state = UNKNOWN_OID;
                         break;
                     }
                     /* reset oid and change state */
                     oid = chunk_empty;
                     state = SEARCH_NAME;
                 }
                 break;
             case SEARCH_NAME:
                 if (*src == ' ' || *src == '=')
                 {
                     break;
                 }
                 else if (*src != sep && *src != '\0')
                 {
                     name.ptr = src;
                     name.len = 1;
                     whitespace = 0;
                     state = READ_NAME;
                     break;
                 }
                 name = chunk_empty;
                 whitespace = 0;
                 state = READ_NAME;
                 /* fall-through */
             case READ_NAME:
                 if (*src != sep && *src != '\0')
                 {
                     name.len++;
                     if (*src == ' ')
                         whitespace++;
                     else
                         whitespace = 0;
                 }
                 else
                 {
                     name.len -= whitespace;
                     rdn_type = (x501rdns[i].type == ASN1_PRINTABLESTRING
                                 && !asn1_is_printablestring(name))
                                 ? ASN1_UTF8STRING : x501rdns[i].type;
                     if (rdn_count < RDN_MAX)
                     {
                         chunk_t rdn_oid;
                         rdn_oid = asn1_build_known_oid(x501rdns[i].oid);
                         if (rdn_oid.len)
{
                             rdns[rdn_count] =
                                     asn1_wrap(ASN1_SET, "m",
                                         asn1_wrap(ASN1_SEQUENCE, "mm",
                                             rdn_oid,
                                             asn1_wrap(rdn_type, "c", name)
                                         )
                                     );
                             dn_len += rdns[rdn_count++].len;
                         }
                         else
{
                             status = INVALID_ARG;
                         }
                     }
                     else
                     {
                         status = OUT_OF_RES;
                     }
                     /* reset name and change state */
                     name = chunk_empty;
                     state = SEARCH_OID;
                 }
                 break;
             case UNKNOWN_OID:
                 break;
         }
     } while (*src++ != '\0');
     if (state == READ_OID)
     {   /* unterminated OID */
         status = INVALID_ARG;
     }
     /* build the distinguished name sequence */
     {
         int i;
         u_char *pos = asn1_build_object(dn, ASN1_SEQUENCE, dn_len);
         for (i = 0; i < rdn_count; i++)
         {
             memcpy(pos, rdns[i].ptr, rdns[i].len);
             pos += rdns[i].len;
             free(rdns[i].ptr);
         }
     }
     if (status != SUCCESS)
     {
         free(dn->ptr);
         *dn = chunk_empty;
     }
     return status;
 }
static bool compare_dn (chunk_t t_dn, chunk_t o_dn, int * wc) static
Compare to DNs, for equality if wc == NULL, for match otherwise
Definition at line 611 of file identification.c.
References ASN1_IA5STRING, asn1_known_oid(), ASN1_PRINTABLESTRING, chunk_equals(), create_rdn_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, chunk_t::len, memeq(), OID_EMAIL_ADDRESS, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *t, *o;
     chunk_t t_oid, o_oid, t_data, o_data;
     u_char t_type, o_type;
     bool t_next, o_next, finished = FALSE;
     if (wc)
     {
         *wc = 0;
     }
     else
     {
         if (t_dn.len != o_dn.len)
         {
             return FALSE;
         }
     }
     /* try a binary compare */
     if (chunk_equals(t_dn, o_dn))
     {
         return TRUE;
     }
     t = create_rdn_enumerator(t_dn);
     o = create_rdn_enumerator(o_dn);
     while (TRUE)
     {
         t_next = t->enumerate(t, &t_oid, &t_type, &t_data);
         o_next = o->enumerate(o, &o_oid, &o_type, &o_data);
         if (!o_next && !t_next)
         {
             break;
         }
         finished = FALSE;
         if (o_next != t_next)
         {
             break;
         }
         if (!chunk_equals(t_oid, o_oid))
         {
             break;
         }
         if (wc && o_data.len == 1 && o_data.ptr[0] == '*')
         {
             (*wc)++;
         }
         else
         {
             if (t_data.len != o_data.len)
             {
                 break;
             }
             if (t_type == o_type &&
                 (t_type == ASN1_PRINTABLESTRING ||
                  (t_type == ASN1_IA5STRING &&
                   asn1_known_oid(t_oid) == OID_EMAIL_ADDRESS)))
             {   /* ignore case for printableStrings and email RDNs */
                 if (strncasecmp(t_data.ptr, o_data.ptr, t_data.len) != 0)
                 {
                     break;
                 }
             }
             else
             {   /* respect case and length for everything else */
                 if (!memeq(t_data.ptr, o_data.ptr, t_data.len))
                 {
                     break;
                 }
             }
         }
         /* the enumerator returns FALSE on parse error, we are finished
          * if we have reached the end of the DN only */
         if ((t_data.ptr + t_data.len == t_dn.ptr + t_dn.len) &&
             (o_data.ptr + o_data.len == o_dn.ptr + o_dn.len))
         {
             finished = TRUE;
         }
     }
     t->destroy(t);
     o->destroy(o);
     return finished;
 }
static private_identification_t* create_from_string_with_num_type (char * str) static
Create an identity for a specific type, determined by a numerical prefix
The prefix is of the form "{x}:", where x denotes the numerical identity type.
Definition at line 1012 of file identification.c.
References chunk_clone, chunk_from_hex(), chunk_from_str, identification_create(), and type.
Referenced by identification_create_from_string().
 {
     private_identification_t *this;
     u_long type;
     if (*str++ != '{')
     {
         return NULL;
     }
     errno = 0;
     type = strtoul(str, &str, 0);
     if (errno || *str++ != '}' || *str++ != ':')
     {
         return NULL;
     }
     this = identification_create(type);
     if (*str == '#')
     {
         this->encoded = chunk_from_hex(chunk_from_str(str + 1), NULL);
     }
     else
     {
         this->encoded = chunk_clone(chunk_from_str(str));
     }
     return this;
 }
static private_identification_t* create_from_string_with_prefix_type (char * str) static
Create an identity for a specific type, determined by prefix
Definition at line 966 of file identification.c.
References chunk_clone, chunk_from_hex(), chunk_from_str, countof, ID_DER_ASN1_DN, ID_DER_ASN1_GN, ID_FQDN, ID_IPV4_ADDR, ID_IPV6_ADDR, ID_KEY_ID, ID_RFC822_ADDR, ID_USER_FQDN, identification_create(), str, strcasepfx(), and type.
Referenced by identification_create_from_string().
 {
     struct {
         const char *str;
         id_type_t type;
     } prefixes[] = {
         { "ipv4:",          ID_IPV4_ADDR            },
         { "ipv6:",          ID_IPV6_ADDR            },
         { "rfc822:",        ID_RFC822_ADDR          },
         { "email:",         ID_RFC822_ADDR          },
         { "userfqdn:",      ID_USER_FQDN            },
         { "fqdn:",          ID_FQDN                 },
         { "dns:",           ID_FQDN                 },
         { "asn1dn:",        ID_DER_ASN1_DN          },
         { "asn1gn:",        ID_DER_ASN1_GN          },
         { "keyid:",         ID_KEY_ID               },
     };
     private_identification_t *this;
     int i;
     for (i = 0; i < countof(prefixes); i++)
     {
         if (strcasepfx(str, prefixes[i].str))
         {
             this = identification_create(prefixes[i].type);
             str += strlen(prefixes[i].str);
             if (*str == '#')
             {
                 this->encoded = chunk_from_hex(chunk_from_str(str + 1), NULL);
             }
             else
             {
                 this->encoded = chunk_clone(chunk_from_str(str));
             }
             return this;
         }
     }
     return NULL;
 }
static enumerator_t* create_rdn_enumerator (chunk_t dn) static
Create an enumerator over all RDNs (oid, string type, data) of a DN
Definition at line 167 of file identification.c.
References ASN1_SEQUENCE, asn1_unwrap(), chunk_empty, destroy(), enumerator_create_empty(), free(), INIT, rdn_enumerator_t::public, rdn_enumerator_t::seqs, and rdn_enumerator_t::sets.
Referenced by compare_dn(), dntoa(), and METHOD().
 {
     rdn_enumerator_t *e;
     INIT(e,
         .public = {
             .enumerate = (void*)_rdn_enumerate,
             .destroy = (void*)free,
         },
     );
     /* a DN is a SEQUENCE, get the first SET of it */
     if (asn1_unwrap(&dn, &e->sets) == ASN1_SEQUENCE)
     {
         e->seqs = chunk_empty;
         return &e->public;
     }
     free(e);
     return enumerator_create_empty();
 }
static void dntoa (chunk_t dn, char * buf, size_t len) static
Print a DN with all its RDN in a buffer to present it to the user
Definition at line 296 of file identification.c.
References asn1_known_oid(), chunk_free(), chunk_printable(), create_rdn_enumerator(), data, enumerator_t::destroy, enumerator_t::enumerate, FALSE, chunk_t::len, name, oid_names, OID_UNKNOWN, print_separator(), printable, chunk_t::ptr, snprintf, TRUE, and type.
Referenced by identification_printf_hook().
 {
     enumerator_t *e;
     chunk_t oid_data, data, printable;
     u_char type;
     int oid, written;
     bool finished = FALSE, empty = TRUE;
     e = create_rdn_enumerator(dn);
     while (e->enumerate(e, &oid_data, &type, &data))
     {
         empty = FALSE;
         /* previous RDN was empty but it wasn't the last one */
         if (finished && !print_separator(&buf, &len))
         {
             break;
         }
         finished = FALSE;
         oid = asn1_known_oid(oid_data);
         if (oid == OID_UNKNOWN)
         {
             written = snprintf(buf, len, "%#B=", &oid_data);
         }
         else
         {
             written = snprintf(buf, len,"%s=", oid_names[oid].name);
         }
         if (written < 0 || written >= len)
         {
             break;
         }
         buf += written;
         len -= written;
         written = 0;
         chunk_printable(data, &printable, '?');
         if (printable.ptr)
         {
             written = snprintf(buf, len, "%.*s", (int)printable.len,
                                printable.ptr);
         }
         chunk_free(&printable);
         if (written < 0 || written >= len)
         {
             break;
         }
         buf += written;
         len -= written;
         if (!data.ptr)
         {   /* we can't calculate if we're finished, assume we are */
             finished = TRUE;
         }
         else if (data.ptr + data.len == dn.ptr + dn.len)
         {
             finished = TRUE;
             break;
         }
         else if (!print_separator(&buf, &len))
         {
             break;
         }
     }
     if (empty)
     {
         snprintf(buf, len, "");
     }
     else if (!finished)
     {
         snprintf(buf, len, "(invalid ID_DER_ASN1_DN)");
     }
     e->destroy(e);
 }
ENUM_BEGIN (id_match_names , ID_MATCH_NONE , ID_MATCH_MAX_WILDCARDS , "MATCH_NONE" , "MATCH_ANY" , "MATCH_MAX_WILDCARDS")
ENUM_BEGIN (id_type_names , ID_ANY , ID_KEY_ID , "ID_ANY" , "ID_IPV4_ADDR" , "ID_FQDN" , "ID_RFC822_ADDR" , "ID_IPV4_ADDR_SUBNET" , "ID_IPV6_ADDR" , "ID_IPV6_ADDR_SUBNET" , "ID_IPV4_ADDR_RANGE" , "ID_IPV6_ADDR_RANGE" , "ID_DER_ASN1_DN" , "ID_DER_ASN1_GN" , "ID_KEY_ID")
ENUM_END (id_match_names , ID_MATCH_PERFECT)
ENUM_END (id_type_names , ID_DER_ASN1_GN_URI)
ENUM_NEXT (id_match_names , ID_MATCH_PERFECT , ID_MATCH_PERFECT , ID_MATCH_MAX_WILDCARDS , "MATCH_PERFECT")
ENUM_NEXT (id_type_names , ID_DER_ASN1_GN_URI , ID_DER_ASN1_GN_URI , ID_KEY_ID , "ID_DER_ASN1_GN_URI")
static private_identification_t* identification_create (id_type_t type) static
Generic constructor used for the other constructors.
Definition at line 917 of file identification.c.
References ID_ANY, ID_DER_ASN1_DN, ID_FQDN, ID_RFC822_ADDR, INIT, return_false(), return_true(), and type.
Referenced by create_from_string_with_num_type(), create_from_string_with_prefix_type(), identification_create_from_encoding(), identification_create_from_sockaddr(), and identification_create_from_string().
 {
     private_identification_t *this;
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .get_type = _get_type,
             .create_part_enumerator = _create_part_enumerator,
             .clone = _clone_,
             .destroy = _destroy,
         },
         .type = type,
     );
     switch (type)
     {
         case ID_ANY:
             this->public.hash = _hash_binary;
             this->public.matches = _matches_any;
             this->public.equals = _equals_binary;
             this->public.contains_wildcards = return_true;
             break;
         case ID_FQDN:
         case ID_RFC822_ADDR:
             this->public.hash = _hash_binary;
             this->public.matches = _matches_string;
             this->public.equals = _equals_strcasecmp;
             this->public.contains_wildcards = _contains_wildcards_memchr;
             break;
         case ID_DER_ASN1_DN:
             this->public.hash = _hash_dn;
             this->public.equals = _equals_dn;
             this->public.matches = _matches_dn;
             this->public.contains_wildcards = _contains_wildcards_dn;
             break;
         default:
             this->public.hash = _hash_binary;
             this->public.equals = _equals_binary;
             this->public.matches = _matches_binary;
             this->public.contains_wildcards = return_false;
             break;
     }
     return this;
 }
METHOD (enumerator_t , rdn_enumerate , bool , rdn_enumerator_t * this, chunk_t * oid, u_char * type, chunk_t * data)
Definition at line 135 of file identification.c.
References ASN1_INVALID, ASN1_OID, ASN1_SEQUENCE, ASN1_SET, asn1_unwrap(), FALSE, and TRUE.
 {
     chunk_t rdn;
     /* a DN contains one or more SET, each containing one or more SEQUENCES,
      * each containing a OID/value RDN */
     if (!this->seqs.len)
     {
         /* no SEQUENCEs in current SET, parse next SET */
         if (asn1_unwrap(&this->sets, &this->seqs) != ASN1_SET)
         {
             return FALSE;
         }
     }
     if (asn1_unwrap(&this->seqs, &rdn) == ASN1_SEQUENCE &&
         asn1_unwrap(&rdn, oid) == ASN1_OID)
     {
         int t = asn1_unwrap(&rdn, data);
         if (t != ASN1_INVALID)
         {
             *type = t;
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (enumerator_t , rdn_part_enumerate , bool , rdn_part_enumerator_t * this, id_part_t * type, chunk_t * data)
Definition at line 198 of file identification.c.
References asn1_known_oid(), countof, FALSE, ID_PART_RDN_C, ID_PART_RDN_CN, ID_PART_RDN_D, ID_PART_RDN_DNQ, ID_PART_RDN_E, ID_PART_RDN_EN, ID_PART_RDN_G, ID_PART_RDN_I, ID_PART_RDN_ID, ID_PART_RDN_L, ID_PART_RDN_N, ID_PART_RDN_O, ID_PART_RDN_OU, ID_PART_RDN_S, ID_PART_RDN_SN, ID_PART_RDN_ST, ID_PART_RDN_T, OID_COMMON_NAME, OID_COUNTRY, OID_DESCRIPTION, OID_DN_QUALIFIER, OID_EMAIL_ADDRESS, OID_EMPLOYEE_NUMBER, OID_GIVEN_NAME, OID_INITIALS, OID_LOCALITY, OID_NAME, OID_ORGANIZATION, OID_ORGANIZATION_UNIT, OID_SERIAL_NUMBER, OID_STATE_OR_PROVINCE, OID_SURNAME, OID_TITLE, OID_UNIQUE_IDENTIFIER, TRUE, and type.
 {
     int i, known_oid, strtype;
     chunk_t oid, inner_data;
     static const struct {
         int oid;
         id_part_t type;
     } oid2part[] = {
         {OID_COMMON_NAME,       ID_PART_RDN_CN},
         {OID_SURNAME,           ID_PART_RDN_S},
         {OID_SERIAL_NUMBER,     ID_PART_RDN_SN},
         {OID_COUNTRY,           ID_PART_RDN_C},
         {OID_LOCALITY,          ID_PART_RDN_L},
         {OID_STATE_OR_PROVINCE, ID_PART_RDN_ST},
         {OID_ORGANIZATION,      ID_PART_RDN_O},
         {OID_ORGANIZATION_UNIT, ID_PART_RDN_OU},
         {OID_TITLE,             ID_PART_RDN_T},
         {OID_DESCRIPTION,       ID_PART_RDN_D},
         {OID_NAME,              ID_PART_RDN_N},
         {OID_GIVEN_NAME,        ID_PART_RDN_G},
         {OID_INITIALS,          ID_PART_RDN_I},
         {OID_DN_QUALIFIER,      ID_PART_RDN_DNQ},
         {OID_UNIQUE_IDENTIFIER, ID_PART_RDN_ID},
         {OID_EMAIL_ADDRESS,     ID_PART_RDN_E},
         {OID_EMPLOYEE_NUMBER,   ID_PART_RDN_EN},
     };
     while (this->inner->enumerate(this->inner, &oid, &strtype, &inner_data))
     {
         known_oid = asn1_known_oid(oid);
         for (i = 0; i < countof(oid2part); i++)
         {
             if (oid2part[i].oid == known_oid)
             {
                 *type = oid2part[i].type;
                 *data = inner_data;
                 return TRUE;
             }
         }
     }
     return FALSE;
 }
METHOD (enumerator_t , rdn_part_enumerator_destroy , void , rdn_part_enumerator_t * this)
Definition at line 242 of file identification.c.
References free().
 {
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (identification_t , create_part_enumerator , enumerator_t * , private_identification_t * this)
Definition at line 249 of file identification.c.
References create_rdn_enumerator(), destroy(), enumerator_t::enumerate, enumerator_create_empty(), ID_DER_ASN1_DN, ID_FQDN, ID_RFC822_ADDR, INIT, rdn_part_enumerator_t::public, and type.
 {
     switch (this->type)
     {
         case ID_DER_ASN1_DN:
         {
             rdn_part_enumerator_t *e;
             INIT(e,
                 .inner = create_rdn_enumerator(this->encoded),
                 .public = {
                     .enumerate = (void*)_rdn_part_enumerate,
                     .destroy = _rdn_part_enumerator_destroy,
                 },
             );
             return &e->public;
         }
         case ID_RFC822_ADDR:
             /* TODO */
         case ID_FQDN:
             /* TODO */
         default:
             return enumerator_create_empty();
     }
 }
METHOD (identification_t , get_encoding , chunk_t , private_identification_t * this)
Definition at line 542 of file identification.c.
 {
     return this->encoded;
 }
METHOD (identification_t , get_type , id_type_t , private_identification_t * this)
Definition at line 548 of file identification.c.
References type.
 {
     return this->type;
 }
METHOD (identification_t , contains_wildcards_dn , bool , private_identification_t * this)
Definition at line 554 of file identification.c.
References data, enumerator_t::destroy, enumerator_t::enumerate, FALSE, chunk_t::len, chunk_t::ptr, TRUE, and type.
 {
     enumerator_t *enumerator;
     bool contains = FALSE;
     id_part_t type;
     chunk_t data;
     enumerator = create_part_enumerator(this);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (data.len == 1 && data.ptr[0] == '*')
         {
             contains = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return contains;
 }
METHOD (identification_t , contains_wildcards_memchr , bool , private_identification_t * this)
Definition at line 575 of file identification.c.
 {
     return memchr(this->encoded.ptr, '*', this->encoded.len) != NULL;
 }
METHOD (identification_t , hash_binary , u_int , private_identification_t * this, u_int inc)
Definition at line 581 of file identification.c.
References chunk_from_thing, chunk_hash_inc(), hash, ID_ANY, and type.
 {
     u_int hash;
     hash = chunk_hash_inc(chunk_from_thing(this->type), inc);
     if (this->type != ID_ANY)
     {
         hash = chunk_hash_inc(this->encoded, hash);
     }
     return hash;
 }
METHOD (identification_t , equals_binary , bool , private_identification_t * this, identification_t * other)
Definition at line 594 of file identification.c.
References chunk_equals(), FALSE, identification_t::get_encoding, identification_t::get_type, ID_ANY, TRUE, and type.
 {
     if (this->type == other->get_type(other))
     {
         if (this->type == ID_ANY)
         {
             return TRUE;
         }
         return chunk_equals(this->encoded, other->get_encoding(other));
     }
     return FALSE;
 }
METHOD (identification_t , equals_dn , bool , private_identification_t * this, identification_t * other)
Definition at line 696 of file identification.c.
References compare_dn(), and identification_t::get_encoding.
 {
     return compare_dn(this->encoded, other->get_encoding(other), NULL);
 }
METHOD (identification_t , hash_dn , u_int , private_identification_t * this, u_int inc)
Definition at line 702 of file identification.c.
References chunk_from_thing, chunk_hash_inc(), create_rdn_enumerator(), data, enumerator_t::destroy, enumerator_t::enumerate, hash, and type.
 {
     enumerator_t *rdns;
     chunk_t oid, data;
     u_char type;
     u_int hash;
     hash = chunk_hash_inc(chunk_from_thing(this->type), inc);
     rdns = create_rdn_enumerator(this->encoded);
     while (rdns->enumerate(rdns, &oid, &type, &data))
     {
         hash = chunk_hash_inc(data, chunk_hash_inc(oid, hash));
     }
     rdns->destroy(rdns);
     return hash;
 }
METHOD (identification_t , equals_strcasecmp , bool , private_identification_t * this, identification_t * other)
Definition at line 720 of file identification.c.
References FALSE, identification_t::get_encoding, chunk_t::len, chunk_t::ptr, and TRUE.
 {
     chunk_t encoded = other->get_encoding(other);
     /* we do some extra sanity checks to check for invalid IDs with a
      * terminating null in it. */
     if (this->encoded.len == encoded.len &&
         memchr(this->encoded.ptr, 0, this->encoded.len) == NULL &&
         memchr(encoded.ptr, 0, encoded.len) == NULL &&
         strncasecmp(this->encoded.ptr, encoded.ptr, this->encoded.len) == 0)
     {
         return TRUE;
     }
     return FALSE;
 }
METHOD (identification_t , matches_binary , id_match_t , private_identification_t * this, identification_t * other)
Definition at line 737 of file identification.c.
References chunk_equals(), identification_t::get_encoding, identification_t::get_type, ID_ANY, ID_MATCH_ANY, ID_MATCH_NONE, ID_MATCH_PERFECT, and type.
 {
     if (other->get_type(other) == ID_ANY)
     {
         return ID_MATCH_ANY;
     }
     if (this->type == other->get_type(other) &&
         chunk_equals(this->encoded, other->get_encoding(other)))
     {
         return ID_MATCH_PERFECT;
     }
     return ID_MATCH_NONE;
 }
METHOD (identification_t , matches_string , id_match_t , private_identification_t * this, identification_t * other)
Definition at line 752 of file identification.c.
References identification_t::get_encoding, identification_t::get_type, ID_ANY, ID_MATCH_ANY, ID_MATCH_NONE, ID_MATCH_ONE_WILDCARD, ID_MATCH_PERFECT, chunk_t::len, len, chunk_t::ptr, and type.
 {
     chunk_t encoded = other->get_encoding(other);
     u_int len = encoded.len;
     if (other->get_type(other) == ID_ANY)
     {
         return ID_MATCH_ANY;
     }
     if (this->type != other->get_type(other))
     {
         return ID_MATCH_NONE;
     }
     /* try a equals check first */
     if (equals_strcasecmp(this, other))
     {
         return ID_MATCH_PERFECT;
     }
     if (len == 0 || this->encoded.len < len)
     {
         return ID_MATCH_NONE;
     }
     /* check for single wildcard at the head of the string */
     if (*encoded.ptr == '*')
     {
         /* single asterisk matches any string */
         if (len-- == 1)
         {   /* not better than ID_ANY */
             return ID_MATCH_ANY;
         }
         if (strncasecmp(this->encoded.ptr + this->encoded.len - len,
                         encoded.ptr + 1, len) == 0)
         {
             return ID_MATCH_ONE_WILDCARD;
         }
     }
     return ID_MATCH_NONE;
 }
METHOD (identification_t , matches_any , id_match_t , private_identification_t * this, identification_t * other)
Definition at line 793 of file identification.c.
References identification_t::get_type, ID_ANY, ID_MATCH_ANY, and ID_MATCH_NONE.
 {
     if (other->get_type(other) == ID_ANY)
     {
         return ID_MATCH_ANY;
     }
     return ID_MATCH_NONE;
 }
METHOD (identification_t , matches_dn , id_match_t , private_identification_t * this, identification_t * other)
Definition at line 803 of file identification.c.
References compare_dn(), identification_t::get_encoding, identification_t::get_type, ID_ANY, ID_MATCH_ANY, ID_MATCH_MAX_WILDCARDS, ID_MATCH_NONE, ID_MATCH_ONE_WILDCARD, ID_MATCH_PERFECT, min, and type.
 {
     int wc;
     if (other->get_type(other) == ID_ANY)
     {
         return ID_MATCH_ANY;
     }
     if (this->type == other->get_type(other))
     {
         if (compare_dn(this->encoded, other->get_encoding(other), &wc))
         {
             wc = min(wc, ID_MATCH_ONE_WILDCARD - ID_MATCH_MAX_WILDCARDS);
             return ID_MATCH_PERFECT - wc;
         }
     }
     return ID_MATCH_NONE;
 }
METHOD (identification_t , clone_ , identification_t * , private_identification_t * this)
Definition at line 894 of file identification.c.
References chunk_clone, private_identification_t::encoded, malloc_thing, memcpy, and private_identification_t::public.
 {
     private_identification_t *clone = malloc_thing(private_identification_t);
     memcpy(clone, this, sizeof(private_identification_t));
     if (this->encoded.len)
     {
         clone->encoded = chunk_clone(this->encoded);
     }
     return &clone->public;
 }
METHOD (identification_t , destroy , void , private_identification_t * this)
Definition at line 907 of file identification.c.
References chunk_free(), and free().
 {
     chunk_free(&this->encoded);
     free(this);
 }
static bool print_separator (char ** buf, size_t * len) inline static
Print a separator between two RDNs
Definition at line 279 of file identification.c.
References FALSE, snprintf, and TRUE.
Referenced by dntoa().
 {
     int written;
     written = snprintf(*buf, *len, ", ");
     if (written < 0 || written >= *len)
     {
         return FALSE;
     }
     *buf += written;
     *len -= written;
     return TRUE;
 }
Variable Documentation
const x501rdn_t x501rdns[] static
Definition at line 63 of file identification.c.