strongSwan: load_pools.c File Reference
load_pools.c File Reference
#include <stdio.h>
#include <errno.h>
#include <limits.h>
#include "command.h"
#include "swanctl.h"
#include "load_pools.h"
Macros
#define _GNU_SOURCE
Functions
static void add_list_key (vici_req_t *req, char *key, char *value)
static void add_key_values (vici_req_t *req, settings_t *cfg, char *section)
static bool load_pool (vici_conn_t *conn, settings_t *cfg, char *section, command_format_options_t format)
CALLBACK (list_pool, int, linked_list_t *list, vici_res_t *res, char *name)
static linked_list_t * list_pools (vici_conn_t *conn, command_format_options_t format)
static void remove_from_list (linked_list_t *list, char *str)
static bool unload_pool (vici_conn_t *conn, char *name, command_format_options_t format)
int load_pools_cfg (vici_conn_t *conn, command_format_options_t format, settings_t *cfg)
static int load_pools (vici_conn_t *conn)
static void __attribute__ ((constructor))
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file load_pools.c.
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 296 of file load_pools.c.
References command_register(), and load_pools().
 {
     command_register((command_t) {
         load_pools, 'a', "load-pools", "(re-)load pool configuration",
         {"[--raw|--pretty]"},
         {
             {"help",        'h', 0, "show usage information"},
             {"raw",         'r', 0, "dump raw response message"},
             {"pretty",      'P', 0, "dump raw response message in pretty print"},
         }
     });
 }
static void add_key_values (vici_req_t * req, settings_t * cfg, char * section) static
Translate setting key/values from a section into vici key-values/lists
Definition at line 46 of file load_pools.c.
References add_list_key(), settings_t::create_key_value_enumerator, enumerator_t::destroy, enumerator_t::enumerate, key, streq(), value, and vici_add_key_valuef().
Referenced by load_pool().
 {
     enumerator_t *enumerator;
     char *key, *value;
     enumerator = cfg->create_key_value_enumerator(cfg, section);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         /* pool subnet is encoded as key/value, all other attributes as list */
         if (streq(key, "addrs"))
         {
             vici_add_key_valuef(req, key, "%s", value);
         }
         else
         {
             add_list_key(req, key, value);
         }
     }
     enumerator->destroy(enumerator);
 }
static void add_list_key (vici_req_t * req, char * key, char * value) static
Add a vici list from a comma separated string value
Definition at line 28 of file load_pools.c.
References enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), vici_add_list_itemf(), vici_begin_list(), and vici_end_list().
Referenced by add_key_values().
 {
     enumerator_t *enumerator;
     char *token;
     vici_begin_list(req, key);
     enumerator = enumerator_create_token(value, ",", " ");
     while (enumerator->enumerate(enumerator, &token))
     {
         vici_add_list_itemf(req, "%s", token);
     }
     enumerator->destroy(enumerator);
     vici_end_list(req);
 }
CALLBACK (list_pool , int , linked_list_t * list, vici_res_t * res, char * name)
Definition at line 111 of file load_pools.c.
References linked_list_t::insert_last, and strdup.
 {
     list->insert_last(list, strdup(name));
     return 0;
 }
static linked_list_t* list_pools (vici_conn_t * conn, command_format_options_t format) static
Create a list of currently loaded pools
Definition at line 121 of file load_pools.c.
References COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, linked_list_create(), list, res, vici_begin(), vici_dump(), vici_free_res(), vici_parse_cb(), and vici_submit().
Referenced by load_pools_cfg().
 {
     linked_list_t *list;
     vici_res_t *res;
     list = linked_list_create();
     res = vici_submit(vici_begin("get-pools"), conn);
     if (res)
     {
         if (format & COMMAND_FORMAT_RAW)
         {
             vici_dump(res, "get-pools reply", format & COMMAND_FORMAT_PRETTY,
                       stdout);
         }
         vici_parse_cb(res, list_pool, NULL, NULL, list);
         vici_free_res(res);
     }
     return list;
 }
static bool load_pool (vici_conn_t * conn, settings_t * cfg, char * section, command_format_options_t format) static
Load a pool configuration
Definition at line 70 of file load_pools.c.
References add_key_values(), COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, FALSE, fprintf, printf, req(), res, snprintf, streq(), strerror, TRUE, vici_begin(), vici_begin_section(), vici_dump(), vici_end_section(), vici_find_str(), vici_free_res(), and vici_submit().
Referenced by load_pools_cfg(), and manage_commands().
 {
     vici_req_t *req;
     vici_res_t *res;
     bool ret = TRUE;
     char buf[128];
     snprintf(buf, sizeof(buf), "%s.%s", "pools", section);
     req = vici_begin("load-pool");
     vici_begin_section(req, section);
     add_key_values(req, cfg, buf);
     vici_end_section(req);
     res = vici_submit(req, conn);
     if (!res)
     {
         fprintf(stderr, "load-pool request failed: %s\n", strerror(errno));
         return FALSE;
     }
     if (format & COMMAND_FORMAT_RAW)
     {
         vici_dump(res, "load-pool reply", format & COMMAND_FORMAT_PRETTY,
                   stdout);
     }
     else if (!streq(vici_find_str(res, "no", "success"), "yes"))
     {
         fprintf(stderr, "loading pool '%s' failed: %s\n",
                 section, vici_find_str(res, "", "errmsg"));
         ret = FALSE;
     }
     else
     {
         printf("loaded pool '%s'\n", section);
     }
     vici_free_res(res);
     return ret;
 }
static int load_pools (vici_conn_t * conn) static
Definition at line 252 of file load_pools.c.
References COMMAND_FORMAT_NONE, COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, command_getopt(), command_usage(), settings_t::destroy, fprintf, load_pools_cfg(), settings_create(), SWANCTL_CONF, and TRUE.
Referenced by __attribute__().
 {
     command_format_options_t format = COMMAND_FORMAT_NONE;
     settings_t *cfg;
     char *arg;
     int ret;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 'P':
                 format |= COMMAND_FORMAT_PRETTY;
                 /* fall through to raw */
             case 'r':
                 format |= COMMAND_FORMAT_RAW;
                 continue;
             case EOF:
                 break;
             default:
                 return command_usage("invalid --load-pools option");
         }
         break;
     }
     cfg = settings_create(SWANCTL_CONF);
     if (!cfg)
     {
         fprintf(stderr, "parsing '%s' failed\n", SWANCTL_CONF);
         return EINVAL;
     }
     ret = load_pools_cfg(conn, format, cfg);
     cfg->destroy(cfg);
     return ret;
 }
int load_pools_cfg (vici_conn_t * conn, command_format_options_t format, settings_t * cfg)
See header.
Definition at line 199 of file load_pools.c.
References COMMAND_FORMAT_RAW, settings_t::create_section_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, found, fprintf, free(), list_pools(), load_pool(), printf, linked_list_t::remove_first, remove_from_list(), section, SUCCESS, and unload_pool().
Referenced by load_all(), and load_pools().
 {
     u_int found = 0, loaded = 0, unloaded = 0;
     char *section;
     enumerator_t *enumerator;
     linked_list_t *pools;
     pools = list_pools(conn, format);
     enumerator = cfg->create_section_enumerator(cfg, "pools");
     while (enumerator->enumerate(enumerator, &section))
     {
         remove_from_list(pools, section);
         found++;
         if (load_pool(conn, cfg, section, format))
         {
             loaded++;
         }
     }
     enumerator->destroy(enumerator);
     /* unload all pools in daemon, but not in file */
     while (pools->remove_first(pools, (void**)&section) == SUCCESS)
     {
         if (unload_pool(conn, section, format))
         {
             unloaded++;
         }
         free(section);
     }
     pools->destroy(pools);
     if (format & COMMAND_FORMAT_RAW)
     {
         return 0;
     }
     if (found == 0)
     {
         printf("no pools found, %u unloaded\n", unloaded);
         return 0;
     }
     if (loaded == found)
     {
         printf("successfully loaded %u pools, %u unloaded\n",
                loaded, unloaded);
         return 0;
     }
     fprintf(stderr, "loaded %u of %u pools, %u failed to load, "
             "%u unloaded\n", loaded, found, found - loaded, unloaded);
     return EINVAL;
 }
static void remove_from_list (linked_list_t * list, char * str) static
Remove and free a string from a list
Definition at line 146 of file load_pools.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, free(), linked_list_t::remove_at, and streq().
Referenced by load_pools_cfg().
 {
     enumerator_t *enumerator;
     char *current;
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (streq(current, str))
         {
             list->remove_at(list, enumerator);
             free(current);
         }
     }
     enumerator->destroy(enumerator);
 }
static bool unload_pool (vici_conn_t * conn, char * name, command_format_options_t format) static
Unload a pool by name
Definition at line 166 of file load_pools.c.
References COMMAND_FORMAT_PRETTY, COMMAND_FORMAT_RAW, FALSE, fprintf, req(), res, streq(), strerror, TRUE, vici_add_key_valuef(), vici_begin(), vici_dump(), vici_find_str(), vici_free_res(), and vici_submit().
Referenced by load_pools_cfg(), and manage_commands().
 {
     vici_req_t *req;
     vici_res_t *res;
     bool ret = TRUE;
     req = vici_begin("unload-pool");
     vici_add_key_valuef(req, "name", "%s", name);
     res = vici_submit(req, conn);
     if (!res)
     {
         fprintf(stderr, "unload-pool request failed: %s\n", strerror(errno));
         return FALSE;
     }
     if (format & COMMAND_FORMAT_RAW)
     {
         vici_dump(res, "unload-pool reply", format & COMMAND_FORMAT_PRETTY,
                   stdout);
     }
     else if (!streq(vici_find_str(res, "no", "success"), "yes"))
     {
         fprintf(stderr, "unloading pool '%s' failed: %s\n",
                 name, vici_find_str(res, "", "errmsg"));
         ret = FALSE;
     }
     vici_free_res(res);
     return ret;
 }