strongSwan: test_certpolicy.c File Reference
test_certpolicy.c File Reference
#include "test_suite.h"
#include <asn1/asn1.h>
#include <credentials/sets/mem_cred.h>
#include <credentials/certificates/x509.h>
Functions
static certificate_t * create_cert_ext (certificate_t *ca, char *subject, char *oid, x509_flag_t flags, char *map_s, char *map_i, u_int require_explicit, u_int inhibit_mapping, u_int inhibit_any)
static certificate_t * create_cert (certificate_t *ca, char *subject, char *oid, x509_flag_t flags, char *map_s, char *map_i)
static bool check_oid (identification_t *subject, char *oid)
static bool check_trust (identification_t *subject)
START_SETUP (setup)
END_SETUP START_TEARDOWN (teardown)
END_TEARDOWN START_TEST (test_valid_fixed)
END_TEST START_TEST (test_valid_any1)
END_TEST START_TEST (test_valid_any2)
END_TEST START_TEST (test_invalid_missing)
END_TEST START_TEST (test_invalid_wrong)
END_TEST START_TEST (test_invalid_any1)
END_TEST START_TEST (test_invalid_any2)
END_TEST START_TEST (test_badchain_wrong)
END_TEST START_TEST (test_badchain_gap)
END_TEST START_TEST (test_badchain_any)
END_TEST START_TEST (test_valid_mapping)
END_TEST START_TEST (test_valid_mapping_twice)
END_TEST START_TEST (test_invalid_mapping_loop)
END_TEST START_TEST (test_invalid_mapping_notallowed)
END_TEST START_TEST (test_invalid_mapping_nopolicy)
END_TEST START_TEST (test_inhibit_mapping_good)
END_TEST START_TEST (test_inhibit_mapping_bad)
END_TEST START_TEST (test_inhibit_any_good)
END_TEST START_TEST (test_inhibit_any_bad)
END_TEST START_TEST (test_require_explicit_good)
END_TEST START_TEST (test_require_explicit_bad)
END_TEST Suite * certpolicy_suite_create ()
Variables
static char keydata []
static mem_cred_t * creds
static char * anyPolicy = "2.5.29.32.0"
static char * extended = "2.23.140.1.1"
static char * baseline = "2.23.140.1.2"
Function Documentation
END_TEST Suite* certpolicy_suite_create ()
Definition at line 576 of file test_certpolicy.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_checked_fixture, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("certpolicy");
     tc = tcase_create("policy valid");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_valid_fixed);
     tcase_add_test(tc, test_valid_any1);
     tcase_add_test(tc, test_valid_any2);
     suite_add_tcase(s, tc);
     tc = tcase_create("policy invalid");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_invalid_missing);
     tcase_add_test(tc, test_invalid_wrong);
     tcase_add_test(tc, test_invalid_any1);
     tcase_add_test(tc, test_invalid_any2);
     suite_add_tcase(s, tc);
     tc = tcase_create("policy badchain");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_badchain_wrong);
     tcase_add_test(tc, test_badchain_gap);
     tcase_add_test(tc, test_badchain_any);
     suite_add_tcase(s, tc);
     tc = tcase_create("policy valid mapping");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_valid_mapping);
     tcase_add_test(tc, test_valid_mapping_twice);
     suite_add_tcase(s, tc);
     tc = tcase_create("policy invalid mapping");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_invalid_mapping_loop);
     tcase_add_test(tc, test_invalid_mapping_notallowed);
     tcase_add_test(tc, test_invalid_mapping_nopolicy);
     suite_add_tcase(s, tc);
     tc = tcase_create("inhibit policy mapping");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_inhibit_mapping_good);
     tcase_add_test(tc, test_inhibit_mapping_bad);
     suite_add_tcase(s, tc);
     tc = tcase_create("inhibit any policy");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_inhibit_any_good);
     tcase_add_test(tc, test_inhibit_any_bad);
     suite_add_tcase(s, tc);
     tc = tcase_create("require explicit policy");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_test(tc, test_require_explicit_good);
     tcase_add_test(tc, test_require_explicit_bad);
     suite_add_tcase(s, tc);
     return s;
 }
static bool check_oid (identification_t * subject, char * oid) static
Check if a certificate with given subject has an oid
Definition at line 148 of file test_certpolicy.c.
References AUTH_RULE_CERT_POLICY, auths, cert, ck_assert_msg, auth_cfg_t::create_enumerator, credential_manager_t::create_trusted_enumerator, library_t::credmgr, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, KEY_ANY, lib, streq(), TRUE, and type.
Referenced by START_TEST().
 {
     enumerator_t *certs, *auths;
     certificate_t *cert;
     auth_cfg_t *auth;
     bool found = FALSE;
     auth_rule_t type;
     char *current;
     certs = lib->credmgr->create_trusted_enumerator(lib->credmgr, KEY_ANY,
                                                     subject, FALSE);
     if (!certs->enumerate(certs, &cert, &auth))
     {
         certs->destroy(certs);
         ck_assert_msg(FALSE, "no trusted certificate found for %Y", subject);
     }
     auths = auth->create_enumerator(auth);
     while (auths->enumerate(auths, &type, &current))
     {
         if (type == AUTH_RULE_CERT_POLICY)
         {
             if (streq(current, oid))
             {
                 found = TRUE;
                 break;
             }
         }
     }
     auths->destroy(auths);
     certs->destroy(certs);
     return found;
 }
static bool check_trust (identification_t * subject) static
Check if a certificate with given subject has a valid trustchain
Definition at line 185 of file test_certpolicy.c.
References cert, credential_manager_t::create_trusted_enumerator, library_t::credmgr, enumerator_t::destroy, enumerator_t::enumerate, FALSE, KEY_ANY, and lib.
Referenced by START_TEST().
 {
     enumerator_t *certs;
     certificate_t *cert;
     bool trusted;
     certs = lib->credmgr->create_trusted_enumerator(lib->credmgr, KEY_ANY,
                                                     subject, FALSE);
     trusted = certs->enumerate(certs, &cert, NULL);
     certs->destroy(certs);
     return trusted;
 }
static certificate_t* create_cert (certificate_t * ca, char * subject, char * oid, x509_flag_t flags, char * map_s, char * map_i) static
Issue a certificate with given certificate policy and flags
Definition at line 136 of file test_certpolicy.c.
References create_cert_ext(), and X509_NO_CONSTRAINT.
Referenced by START_TEST().
 {
     return create_cert_ext(ca, subject, oid, flags, map_s, map_i,
                            X509_NO_CONSTRAINT, X509_NO_CONSTRAINT,
                            X509_NO_CONSTRAINT);
 }
static certificate_t* create_cert_ext (certificate_t * ca, char * subject, char * oid, x509_flag_t flags, char * map_s, char * map_i, u_int require_explicit, u_int inhibit_mapping, u_int inhibit_any) static
Issue a certificate fr given policy, including extended flags
Definition at line 70 of file test_certpolicy.c.
References asn1_oid_from_string(), BUILD_BLOB_ASN1_DER, BUILD_CERTIFICATE_POLICIES, BUILD_END, BUILD_POLICY_INHIBIT_ANY, BUILD_POLICY_INHIBIT_MAPPING, BUILD_POLICY_MAPPINGS, BUILD_POLICY_REQUIRE_EXPLICIT, BUILD_PUBLIC_KEY, BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, BUILD_SUBJECT, BUILD_X509_FLAG, cert, CERT_X509, chunk_from_thing, ck_assert, credential_factory_t::create, CRED_CERTIFICATE, CRED_PRIVATE_KEY, library_t::creds, private_key_t::destroy, linked_list_t::destroy, public_key_t::destroy, free(), private_key_t::get_public_key, id, identification_create_from_string(), linked_list_t::insert_last, x509_policy_mapping_t::issuer, KEY_RSA, keydata, lib, linked_list_create(), x509_cert_policy_t::oid, chunk_t::ptr, and x509_policy_mapping_t::subject.
Referenced by create_cert(), and START_TEST().
 {
     private_key_t *privkey;
     public_key_t *pubkey;
     certificate_t *cert;
     identification_t *id;
     linked_list_t *policies, *maps;
     x509_cert_policy_t policy = {};
     x509_policy_mapping_t map = {};
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                  BUILD_BLOB_ASN1_DER, chunk_from_thing(keydata),
                                  BUILD_END);
     ck_assert(privkey);
     pubkey = privkey->get_public_key(privkey);
     ck_assert(pubkey);
     policies = linked_list_create();
     if (oid)
     {
         policy.oid = asn1_oid_from_string(oid);
         ck_assert(policy.oid.ptr);
         policies->insert_last(policies, &policy);
     }
     maps = linked_list_create();
     if (map_s && map_i)
     {
         map.subject = asn1_oid_from_string(map_s);
         ck_assert(map.subject.ptr);
         map.issuer = asn1_oid_from_string(map_i);
         ck_assert(map.issuer.ptr);
         maps->insert_last(maps, &map);
     }
     id = identification_create_from_string(subject);
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                         BUILD_SIGNING_KEY, privkey,
                         BUILD_PUBLIC_KEY, pubkey,
                         BUILD_SUBJECT, id,
                         BUILD_X509_FLAG, flags,
                         BUILD_CERTIFICATE_POLICIES, policies,
                         BUILD_POLICY_MAPPINGS, maps,
                         BUILD_SIGNING_CERT, ca,
                         BUILD_POLICY_REQUIRE_EXPLICIT, require_explicit,
                         BUILD_POLICY_INHIBIT_MAPPING, inhibit_mapping,
                         BUILD_POLICY_INHIBIT_ANY, inhibit_any,
                         BUILD_END);
     ck_assert(cert);
     id->destroy(id);
     policies->destroy(policies);
     maps->destroy(maps);
     privkey->destroy(privkey);
     pubkey->destroy(pubkey);
     free(policy.oid.ptr);
     free(map.subject.ptr);
     free(map.issuer.ptr);
     return cert;
 }
START_SETUP (setup)
Definition at line 205 of file test_certpolicy.c.
References credential_manager_t::add_set, library_t::credmgr, lib, mem_cred_create(), and mem_cred_t::set.
 {
     creds = mem_cred_create();
     lib->credmgr->add_set(lib->credmgr, &creds->set);
 }
END_SETUP START_TEARDOWN (teardown)
Definition at line 212 of file test_certpolicy.c.
References CERT_ANY, library_t::credmgr, mem_cred_t::destroy, credential_manager_t::flush_cache, lib, credential_manager_t::remove_set, and mem_cred_t::set.
 {
     lib->credmgr->remove_set(lib->credmgr, &creds->set);
     creds->destroy(creds);
     lib->credmgr->flush_cache(lib->credmgr, CERT_ANY);
 }
END_TEARDOWN START_TEST (test_valid_fixed)
Definition at line 220 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", baseline, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_valid_any1)
Definition at line 236 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", baseline, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_valid_any2)
Definition at line 252 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", anyPolicy, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_invalid_missing)
Definition at line 268 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", baseline, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", NULL, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_invalid_wrong)
Definition at line 284 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", baseline, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), extended));
 }
END_TEST START_TEST (test_invalid_any1)
Definition at line 300 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", anyPolicy, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", NULL, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_invalid_any2)
Definition at line 316 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", anyPolicy, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", anyPolicy, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_badchain_wrong)
Definition at line 332 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", extended, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", extended, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
     ck_assert(!check_oid(sj->get_subject(sj), extended));
 }
END_TEST START_TEST (test_badchain_gap)
Definition at line 349 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", NULL, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_badchain_any)
Definition at line 365 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", anyPolicy, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", extended, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), extended));
 }
END_TEST START_TEST (test_valid_mapping)
Definition at line 381 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", extended, X509_CA, baseline, extended);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_valid_mapping_twice)
Definition at line 397 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", "2.23.140.1.3", X509_CA,
                      extended, "2.23.140.1.3");
     im = create_cert(ca, "CN=IM", extended, X509_CA, baseline, extended);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_invalid_mapping_loop)
Definition at line 414 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", extended, X509_CA, baseline, baseline);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_invalid_mapping_notallowed)
Definition at line 430 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", extended, X509_CA, baseline, extended);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_invalid_mapping_nopolicy)
Definition at line 446 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), extended, FALSE, certificate_t::get_subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert(NULL, "CN=CA", baseline, X509_CA, NULL, NULL);
     im = create_cert(ca, "CN=IM", "2.23.140.1.3", X509_CA, baseline, extended);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(!check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_inhibit_mapping_good)
Definition at line 462 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_oid(), ck_assert, create_cert(), create_cert_ext(), extended, FALSE, certificate_t::get_subject, TRUE, X509_CA, and X509_NO_CONSTRAINT.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert_ext(NULL, "CN=CA", extended, X509_CA, NULL, NULL,
                          X509_NO_CONSTRAINT, 1, X509_NO_CONSTRAINT);
     im = create_cert(ca, "CN=IM", extended, X509_CA, baseline, extended);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_inhibit_mapping_bad)
Definition at line 479 of file test_certpolicy.c.
References mem_cred_t::add_cert, baseline, check_trust(), ck_assert, create_cert(), create_cert_ext(), extended, FALSE, certificate_t::get_subject, TRUE, X509_CA, and X509_NO_CONSTRAINT.
 {
     certificate_t *ca, *i1, *i2, *sj;
     ca = create_cert_ext(NULL, "CN=CA", extended, X509_CA, NULL, NULL,
                          X509_NO_CONSTRAINT, 1, X509_NO_CONSTRAINT);
     i1 = create_cert(ca, "CN=IM1", extended, X509_CA, NULL, NULL);
     i2 = create_cert(i1, "CN=IM2", extended, X509_CA, baseline, extended);
     sj = create_cert(i2, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, i1);
     creds->add_cert(creds, FALSE, i2);
     creds->add_cert(creds, FALSE, sj);
     /* TODO: we currently reject the certificate completely, but should
      * actually just invalidate the policy not mapped properly */
     ck_assert(!check_trust(sj->get_subject(sj)));
 }
END_TEST START_TEST (test_inhibit_any_good)
Definition at line 500 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), create_cert_ext(), FALSE, certificate_t::get_subject, TRUE, X509_CA, and X509_NO_CONSTRAINT.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert_ext(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL,
                          X509_NO_CONSTRAINT, X509_NO_CONSTRAINT, 1);
     im = create_cert(ca, "CN=IM", anyPolicy, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_inhibit_any_bad)
Definition at line 517 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_trust(), ck_assert, create_cert(), create_cert_ext(), FALSE, certificate_t::get_subject, TRUE, X509_CA, and X509_NO_CONSTRAINT.
 {
     certificate_t *ca, *i1, *i2, *sj;
     ca = create_cert_ext(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL,
                          X509_NO_CONSTRAINT, X509_NO_CONSTRAINT, 1);
     i1 = create_cert(ca, "CN=IM1", anyPolicy, X509_CA, NULL, NULL);
     i2 = create_cert(i1, "CN=IM2", anyPolicy, X509_CA, NULL, NULL);
     sj = create_cert(i2, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, i1);
     creds->add_cert(creds, FALSE, i2);
     creds->add_cert(creds, FALSE, sj);
     /* TODO: we currently reject the certificate completely, but should
      * actually just invalidate the policy relying on inhibited anyPolicy */
     ck_assert(!check_trust(sj->get_subject(sj)));
 }
END_TEST START_TEST (test_require_explicit_good)
Definition at line 538 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_oid(), ck_assert, create_cert(), create_cert_ext(), FALSE, certificate_t::get_subject, TRUE, X509_CA, and X509_NO_CONSTRAINT.
 {
     certificate_t *ca, *im, *sj;
     ca = create_cert_ext(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL,
                          1, X509_NO_CONSTRAINT, X509_NO_CONSTRAINT);
     im = create_cert(ca, "CN=IM", baseline, X509_CA, NULL, NULL);
     sj = create_cert(im, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_oid(sj->get_subject(sj), baseline));
 }
END_TEST START_TEST (test_require_explicit_bad)
Definition at line 555 of file test_certpolicy.c.
References mem_cred_t::add_cert, anyPolicy, baseline, check_trust(), ck_assert, create_cert(), create_cert_ext(), extended, FALSE, certificate_t::get_subject, TRUE, X509_CA, and X509_NO_CONSTRAINT.
 {
     certificate_t *ca, *i1, *i2, *sj;
     ca = create_cert_ext(NULL, "CN=CA", anyPolicy, X509_CA, NULL, NULL,
                          1, X509_NO_CONSTRAINT, X509_NO_CONSTRAINT);
     i1 = create_cert(ca, "CN=IM1", extended, X509_CA, NULL, NULL);
     i2 = create_cert(i1, "CN=IM2", extended, X509_CA, NULL, NULL);
     sj = create_cert(i2, "CN=SJ", baseline, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, i1);
     creds->add_cert(creds, FALSE, i2);
     creds->add_cert(creds, FALSE, sj);
     /* TODO: we currently reject the certificate completely, but should
      * actually just invalidate the policy violating requireExplicit */
     ck_assert(!check_trust(sj->get_subject(sj)));
 }
Variable Documentation
char* anyPolicy = "2.5.29.32.0" static
Definition at line 201 of file test_certpolicy.c.
Referenced by START_TEST().
char* baseline = "2.23.140.1.2" static
Definition at line 203 of file test_certpolicy.c.
Referenced by START_TEST().
mem_cred_t* creds static
Definition at line 199 of file test_certpolicy.c.
char* extended = "2.23.140.1.1" static
Definition at line 202 of file test_certpolicy.c.
Referenced by START_TEST().
char keydata[] static
RSA private key, so we don't have to generate one
Definition at line 25 of file test_certpolicy.c.
Referenced by create_cert_ext().