strongSwan: ntru_ke.c File Reference
ntru_ke.c File Reference
#include "ntru_ke.h"
#include "ntru_drbg.h"
#include "ntru_param_set.h"
#include "ntru_private_key.h"
#include "ntru_public_key.h"
#include <crypto/diffie_hellman.h>
#include <utils/debug.h>
Classes
struct private_ntru_ke_t
Typedefs
typedef struct private_ntru_ke_t private_ntru_ke_t
Functions
METHOD (diffie_hellman_t, get_my_public_value, bool, private_ntru_ke_t *this, chunk_t *value)
METHOD (diffie_hellman_t, get_shared_secret, bool, private_ntru_ke_t *this, chunk_t *secret)
METHOD (diffie_hellman_t, set_other_public_value, bool, private_ntru_ke_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_dh_group, diffie_hellman_group_t, private_ntru_ke_t *this)
METHOD (diffie_hellman_t, destroy, void, private_ntru_ke_t *this)
ntru_ke_t * ntru_ke_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Variables
static ntru_param_set_id_t param_sets_optimum []
static ntru_param_set_id_t param_sets_x9_98_speed []
static ntru_param_set_id_t param_sets_x9_98_bandwidth []
static ntru_param_set_id_t param_sets_x9_98_balance []
Typedef Documentation
typedef struct private_ntru_ke_t private_ntru_ke_t
Definition at line 25 of file ntru_ke.c.
Function Documentation
METHOD (diffie_hellman_t , get_my_public_value , bool , private_ntru_ke_t * this, chunk_t * value)
Definition at line 112 of file ntru_ke.c.
References chunk_clone, chunk_empty, DBG1, DBG3, DBG_LIB, drbg, FALSE, ntru_private_key_create, and TRUE.
 {
     *value = chunk_empty;
     if (this->responder)
     {
         if (this->ciphertext.len)
         {
             *value = chunk_clone(this->ciphertext);
         }
     }
     else
     {
         if (!this->pubkey)
         {
             /* generate a random NTRU public/private key pair */
             this->privkey = ntru_private_key_create(this->drbg, this->param_set);
             if (!this->privkey)
             {
                 DBG1(DBG_LIB, "NTRU keypair generation failed");
                 return FALSE;
             }
             this->pubkey = this->privkey->get_public_key(this->privkey);
         }
         *value = chunk_clone(this->pubkey->get_encoding(this->pubkey));
         DBG3(DBG_LIB, "NTRU public key: %B", value);
     }
     return TRUE;
 }
METHOD (diffie_hellman_t , get_shared_secret , bool , private_ntru_ke_t * this, chunk_t * secret)
Definition at line 143 of file ntru_ke.c.
References chunk_clone, chunk_empty, FALSE, and TRUE.
 {
     if (!this->computed || !this->shared_secret.len)
     {
         *secret = chunk_empty;
         return FALSE;
     }
     *secret = chunk_clone(this->shared_secret);
     return TRUE;
 }
METHOD (diffie_hellman_t , set_other_public_value , bool , private_ntru_ke_t * this, chunk_t value)
Definition at line 156 of file ntru_ke.c.
References BITS_PER_BYTE, chunk_alloc, chunk_free(), DBG1, DBG3, DBG_LIB, ntru_public_key_t::destroy, drbg, ntru_public_key_t::encrypt, FALSE, ntru_public_key_t::get_id, chunk_t::len, ntru_public_key_create_from_data, and TRUE.
 {
     if (this->privkey)
     {
         /* initiator decrypting shared secret */
         if (value.len == 0)
         {
             DBG1(DBG_LIB, "empty NTRU ciphertext");
             return FALSE;
         }
         DBG3(DBG_LIB, "NTRU ciphertext: %B", &value);
         /* decrypt the shared secret */
         if (!this->privkey->decrypt(this->privkey, value, &this->shared_secret))
         {
             DBG1(DBG_LIB, "NTRU decryption of shared secret failed");
             return FALSE;
         }
         this->computed = TRUE;
     }
     else
     {
         ntru_public_key_t *pubkey;
         /* responder generating and encrypting the shared secret */
         this->responder = TRUE;
         DBG3(DBG_LIB, "NTRU public key: %B", &value);
         pubkey = ntru_public_key_create_from_data(this->drbg, value);
         if (!pubkey)
         {
             return FALSE;
         }
         if (pubkey->get_id(pubkey) != this->param_set->id)
         {
             DBG1(DBG_LIB, "received NTRU public key with wrong OUI");
             pubkey->destroy(pubkey);
             return FALSE;
         }
         this->pubkey = pubkey;
         /* shared secret size is chosen as twice the cryptographical strength */
         this->shared_secret = chunk_alloc(2 * this->strength / BITS_PER_BYTE);
         /* generate the random shared secret */
         if (!this->drbg->generate(this->drbg, this->strength,
                 this->shared_secret.len, this->shared_secret.ptr))
         {
             DBG1(DBG_LIB, "generation of shared secret failed");
             chunk_free(&this->shared_secret);
             return FALSE;
         }
         this->computed = TRUE;
         /* encrypt the shared secret */
         if (!pubkey->encrypt(pubkey, this->shared_secret, &this->ciphertext))
         {
             DBG1(DBG_LIB, "NTRU encryption of shared secret failed");
             return FALSE;
         }
         DBG3(DBG_LIB, "NTRU ciphertext: %B", &this->ciphertext);
     }
     return this->computed;
 }
METHOD (diffie_hellman_t , get_dh_group , diffie_hellman_group_t , private_ntru_ke_t * this)
Definition at line 222 of file ntru_ke.c.
References group.
 {
     return this->group;
 }
METHOD (diffie_hellman_t , destroy , void , private_ntru_ke_t * this)
Definition at line 228 of file ntru_ke.c.
References chunk_clear(), chunk_free(), ntru_trits_t::destroy, DESTROY_IF, drbg, and free().
 {
     DESTROY_IF(this->privkey);
     DESTROY_IF(this->pubkey);
     this->drbg->destroy(this->drbg);
     this->entropy->destroy(this->entropy);
     chunk_free(&this->ciphertext);
     chunk_clear(&this->shared_secret);
     free(this);
 }
Variable Documentation
ntru_param_set_id_t param_sets_optimum[] static
Initial value:
= {
    NTRU_EES401EP2, NTRU_EES439EP1, NTRU_EES593EP1, NTRU_EES743EP1
}
Definition at line 28 of file ntru_ke.c.
Referenced by ntru_ke_create().
ntru_param_set_id_t param_sets_x9_98_balance[] static
Initial value:
= {
    NTRU_EES541EP1, NTRU_EES613EP1, NTRU_EES887EP1, NTRU_EES1171EP1
}
Definition at line 43 of file ntru_ke.c.
Referenced by ntru_ke_create().
ntru_param_set_id_t param_sets_x9_98_bandwidth[] static
Initial value:
= {
    NTRU_EES401EP1, NTRU_EES449EP1, NTRU_EES677EP1, NTRU_EES1087EP2
}
Definition at line 38 of file ntru_ke.c.
Referenced by ntru_ke_create().
ntru_param_set_id_t param_sets_x9_98_speed[] static
Initial value:
= {
    NTRU_EES659EP1, NTRU_EES761EP1, NTRU_EES1087EP1, NTRU_EES1499EP1
}
Definition at line 33 of file ntru_ke.c.
Referenced by ntru_ke_create().