strongSwan: options_t Struct Reference
options_t Struct Reference
optionsfrom
#include "optionsfrom.h"
Public Attributes
bool(* from)(options_t *this, char *filename, int *argcp, char **argvp[], int optind)
void(* destroy)(options_t *this)
Detailed Description
Reads additional command line arguments from a file
Definition at line 30 of file optionsfrom.h.
Member Data Documentation
void(* options_t::destroy)(options_t *this)
Destroys the options_t object.
Definition at line 47 of file optionsfrom.h.
Referenced by cleanup(), exit_aikgen(), and exit_scepclient().
bool(* options_t::from)(options_t *this, char *filename, int *argcp, char **argvp[], int optind)
Check if the PKCS#7 contentType is data
Parameters
filename file containing the options
argcp pointer to argc
argvp pointer to argv[]
optind current optind, number of next argument
Returns
TRUE if optionsfrom parsing successful
Definition at line 41 of file optionsfrom.h.
Referenced by command_getopt(), main(), and process_common_opts().
The documentation for this struct was generated from the following file:
optionsfrom.h