strongSwan: simaka_card_t Struct Reference
simaka_card_t Struct Reference
simaka_card
#include "simaka_card.h"
Public Attributes
bool(* get_triplet)(simaka_card_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
status_t(* get_quintuplet)(simaka_card_t *this, identification_t *id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int *res_len)
bool(* resync)(simaka_card_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
void(* set_pseudonym)(simaka_card_t *this, identification_t *id, identification_t *pseudonym)
identification_t *(* get_pseudonym)(simaka_card_t *this, identification_t *id)
void(* set_reauth)(simaka_card_t *this, identification_t *id, identification_t *next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
identification_t *(* get_reauth)(simaka_card_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
Detailed Description
Interface for a (U)SIM card (used as EAP client).
The SIM card completes triplets/quintuplets requested in a challenge received from the server. An implementation supporting only one of SIM/AKA authentication may implement the other methods with return_false()/return NOT_SUPPORTED/NULL.
Definition at line 38 of file simaka_card.h.
Member Data Documentation
identification_t*(* simaka_card_t::get_pseudonym)(simaka_card_t *this, identification_t *id)
Get the pseudonym previously stored via set_pseudonym().
Parameters
id permanent identity of the peer
Returns
associated pseudonym identity, NULL if none stored
Definition at line 103 of file simaka_card.h.
Referenced by METHOD().
status_t(* simaka_card_t::get_quintuplet)(simaka_card_t *this, identification_t *id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int *res_len)
Calculate CK/IK/RES from RAND/AUTN for AKA authentication.
If the received sequence number (in autn) is out of sync, INVALID_STATE is returned. The RES value is the only one with variable length. Pass a buffer of at least AKA_RES_MAX, the actual number of bytes is written to the res_len value. While the standard would allow any bit length between 32 and 128 bits, we support only full bytes for now.
Parameters
id permanent identity to request quintuplet for
rand random value rand
autn authentication token autn
ck buffer receiving encryption key ck
ik buffer receiving integrity key ik
res buffer receiving authentication result res
res_len nubmer of bytes written to res buffer
Returns
SUCCESS, FAILED, or INVALID_STATE if out of sync
Definition at line 72 of file simaka_card.h.
Referenced by METHOD().
identification_t*(* simaka_card_t::get_reauth)(simaka_card_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
Retrieve parameters for fast reauthentication stored via set_reauth().
Parameters
id permanent identity of the peer
mk buffer receiving master key MK
counter pointer receiving counter value, in host order
Returns
fast reauthentication identity, NULL if not found
Definition at line 125 of file simaka_card.h.
Referenced by METHOD().
bool(* simaka_card_t::get_triplet)(simaka_card_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
Calculate SRES/KC from a RAND for SIM authentication.
Parameters
id permanent identity to get a triplet for
rand RAND input buffer, fixed size 16 bytes
sres SRES output buffer, fixed size 4 byte
kc KC output buffer, fixed size 8 bytes
Returns
TRUE if SRES/KC calculated, FALSE on error/wrong identity
Definition at line 49 of file simaka_card.h.
Referenced by METHOD().
bool(* simaka_card_t::resync)(simaka_card_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
Calculate AUTS from RAND for AKA resynchronization.
Parameters
id permanent identity to request quintuplet for
rand random value rand
auts resynchronization parameter auts
Returns
TRUE if parameter generated successfully
Definition at line 85 of file simaka_card.h.
Referenced by METHOD().
void(* simaka_card_t::set_pseudonym)(simaka_card_t *this, identification_t *id, identification_t *pseudonym)
Set the pseudonym to use for next authentication.
Parameters
id permanent identity of the peer
pseudonym pseudonym identity received from the server
Definition at line 94 of file simaka_card.h.
Referenced by METHOD().
void(* simaka_card_t::set_reauth)(simaka_card_t *this, identification_t *id, identification_t *next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
Store parameters to use for the next fast reauthentication.
Parameters
id permanent identity of the peer
next next fast reauthentication identity to use
mk master key MK to store for reauthentication
counter counter value to store, host order
Definition at line 113 of file simaka_card.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
simaka_card.h