strongSwan: curl_fetcher.c File Reference
curl_fetcher.c File Reference
#include <curl/curl.h>
#include <library.h>
#include <utils/debug.h>
#include "curl_fetcher.h"
Classes
struct private_curl_fetcher_t
struct cb_data_t
Macros
#define CONNECT_TIMEOUT 10
Typedefs
typedef struct
private_curl_fetcher_t private_curl_fetcher_t
Functions
static size_t curl_cb (void *ptr, size_t size, size_t nmemb, cb_data_t *data)
METHOD (fetcher_t, fetch, status_t, private_curl_fetcher_t *this, char *uri, void *userdata)
METHOD (fetcher_t, set_option, bool, private_curl_fetcher_t *this, fetcher_option_t option,...)
METHOD (fetcher_t, destroy, void, private_curl_fetcher_t *this)
curl_fetcher_t * curl_fetcher_create ()
Macro Definition Documentation
#define CONNECT_TIMEOUT 10
Definition at line 24 of file curl_fetcher.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_curl_fetcher_t private_curl_fetcher_t
Definition at line 26 of file curl_fetcher.c.
Function Documentation
static size_t curl_cb (void * ptr, size_t size, size_t nmemb, cb_data_t * data) static
Curl callback function, invokes fetcher_callback_t function
Definition at line 74 of file curl_fetcher.c.
References cb_data_t::cb, chunk_create(), and cb_data_t::user.
Referenced by METHOD().
 {
     size_t realsize = size * nmemb;
     if (data->cb(data->user, chunk_create(ptr, realsize)))
     {
         return realsize;
     }
     return 0;
 }
METHOD (fetcher_t , fetch , status_t , private_curl_fetcher_t * this, char * uri, void * userdata)
Definition at line 85 of file curl_fetcher.c.
References cb(), chunk_empty, CONNECT_TIMEOUT, curl_cb(), data, DBG1, DBG2, DBG_LIB, FAILED, FALSE, fetcher_default_callback(), free(), NOT_SUPPORTED, out, result, status, strreplace(), SUCCESS, and TRUE.
 {
     char error[CURL_ERROR_SIZE], *enc_uri;
     CURLcode curl_status;
     status_t status;
     long result = 0;
     cb_data_t data = {
         .cb = this->cb,
         .user = userdata,
     };
     if (this->cb == fetcher_default_callback)
     {
         *(chunk_t*)userdata = chunk_empty;
     }
     /* the URI has to be URL-encoded, we only replace spaces as replacing other
      * characters (e.g. '/' or ':') would render the URI invalid */
     enc_uri = strreplace(uri, " ", "%20");
     if (curl_easy_setopt(this->curl, CURLOPT_URL, enc_uri) != CURLE_OK)
     {   /* URL type not supported by curl */
         status = NOT_SUPPORTED;
         goto out;
     }
     curl_easy_setopt(this->curl, CURLOPT_ERRORBUFFER, error);
     curl_easy_setopt(this->curl, CURLOPT_FAILONERROR, FALSE);
     curl_easy_setopt(this->curl, CURLOPT_NOSIGNAL, TRUE);
     if (this->timeout)
     {
         curl_easy_setopt(this->curl, CURLOPT_TIMEOUT, this->timeout);
     }
     curl_easy_setopt(this->curl, CURLOPT_CONNECTTIMEOUT, CONNECT_TIMEOUT);
     curl_easy_setopt(this->curl, CURLOPT_WRITEFUNCTION, (void*)curl_cb);
     curl_easy_setopt(this->curl, CURLOPT_WRITEDATA, &data);
     if (this->headers)
     {
         curl_easy_setopt(this->curl, CURLOPT_HTTPHEADER, this->headers);
     }
     DBG2(DBG_LIB, "  sending request to '%s'...", uri);
     curl_status = curl_easy_perform(this->curl);
     switch (curl_status)
     {
         case CURLE_UNSUPPORTED_PROTOCOL:
             status = NOT_SUPPORTED;
             break;
         case CURLE_OK:
             curl_easy_getinfo(this->curl, CURLINFO_RESPONSE_CODE,
                               &result);
             if (this->result)
             {
                 *this->result = result;
             }
             status = (result < 400) ? SUCCESS : FAILED;
             break;
         default:
             DBG1(DBG_LIB, "libcurl request failed [%d]: %s", curl_status,
                  error);
             status = FAILED;
             break;
     }
 out:
     if (enc_uri != uri)
     {
         free(enc_uri);
     }
     return status;
 }
METHOD (fetcher_t , set_option , bool , private_curl_fetcher_t * this, fetcher_option_t option, ...)
Definition at line 157 of file curl_fetcher.c.
References BUF_LEN, cb(), data, FALSE, FETCH_CALLBACK, FETCH_HTTP_VERSION_1_0, FETCH_REQUEST_DATA, FETCH_REQUEST_HEADER, FETCH_REQUEST_TYPE, FETCH_RESPONSE_CODE, FETCH_SOURCEIP, FETCH_TIMEOUT, chunk_t::len, chunk_t::ptr, result, snprintf, and TRUE.
 {
     bool supported = TRUE;
     va_list args;
     va_start(args, option);
     switch (option)
     {
         case FETCH_REQUEST_DATA:
         {
             chunk_t data = va_arg(args, chunk_t);
             curl_easy_setopt(this->curl, CURLOPT_POSTFIELDS, (char*)data.ptr);
             curl_easy_setopt(this->curl, CURLOPT_POSTFIELDSIZE, data.len);
             break;
         }
         case FETCH_REQUEST_TYPE:
         {
             char header[BUF_LEN];
             char *request_type = va_arg(args, char*);
             snprintf(header, BUF_LEN, "Content-Type: %s", request_type);
             this->headers = curl_slist_append(this->headers, header);
             break;
         }
         case FETCH_REQUEST_HEADER:
         {
             char *header = va_arg(args, char*);
             this->headers = curl_slist_append(this->headers, header);
             break;
         }
         case FETCH_HTTP_VERSION_1_0:
         {
             curl_easy_setopt(this->curl, CURLOPT_HTTP_VERSION,
                              CURL_HTTP_VERSION_1_0);
             break;
         }
         case FETCH_TIMEOUT:
         {
             this->timeout = va_arg(args, u_int);
             break;
         }
         case FETCH_CALLBACK:
         {
             this->cb = va_arg(args, fetcher_callback_t);
             break;
         }
         case FETCH_RESPONSE_CODE:
         {
             this->result = va_arg(args, u_int*);
             break;
         }
         case FETCH_SOURCEIP:
         {
             char buf[64];
             snprintf(buf, sizeof(buf), "%H", va_arg(args, host_t*));
             supported = curl_easy_setopt(this->curl, CURLOPT_INTERFACE,
                                          buf) == CURLE_OK;
             break;
         }
         default:
             supported = FALSE;
             break;
     }
     va_end(args);
     return supported;
 }
METHOD (fetcher_t , destroy , void , private_curl_fetcher_t * this)
Definition at line 228 of file curl_fetcher.c.
References free().
 {
     curl_slist_free_all(this->headers);
     curl_easy_cleanup(this->curl);
     free(this);
 }