strongSwan: libvici
libvici
vici
Typedefs
typedef struct vici_conn_t vici_conn_t
typedef struct vici_req_t vici_req_t
typedef struct vici_res_t vici_res_t
typedef void(* vici_event_cb_t)(void *user, char *name, vici_res_t *msg)
typedef int(* vici_parse_value_cb_t)(void *user, vici_res_t *res, char *name, void *value, int len)
typedef int(* vici_parse_section_cb_t)(void *user, vici_res_t *res, char *name)
Enumerations
enum vici_parse_t {
VICI_PARSE_BEGIN_SECTION, VICI_PARSE_END_SECTION, VICI_PARSE_BEGIN_LIST, VICI_PARSE_LIST_ITEM,
VICI_PARSE_END_LIST, VICI_PARSE_KEY_VALUE, VICI_PARSE_END, VICI_PARSE_ERROR
}
Functions
vici_conn_t * vici_connect (char *uri)
void vici_disconnect (vici_conn_t *conn)
vici_req_t * vici_begin (char *name)
void vici_begin_section (vici_req_t *req, char *name)
void vici_end_section (vici_req_t *req)
void vici_add_key_value (vici_req_t *req, char *key, void *buf, int len)
void vici_add_key_valuef (vici_req_t *req, char *key, char *fmt,...)
void vici_begin_list (vici_req_t *req, char *name)
void vici_add_list_item (vici_req_t *req, void *buf, int len)
void vici_add_list_itemf (vici_req_t *req, char *fmt,...)
void vici_end_list (vici_req_t *req)
vici_res_t * vici_submit (vici_req_t *req, vici_conn_t *conn)
void vici_free_req (vici_req_t *req)
int vici_dump (vici_res_t *res, char *label, int pretty, FILE *out)
vici_parse_t vici_parse (vici_res_t *res)
char * vici_parse_name (vici_res_t *res)
int vici_parse_name_eq (vici_res_t *res, char *name)
void * vici_parse_value (vici_res_t *res, int *len)
char * vici_parse_value_str (vici_res_t *res)
int vici_parse_cb (vici_res_t *res, vici_parse_section_cb_t section, vici_parse_value_cb_t kv, vici_parse_value_cb_t li, void *user)
void * vici_find (vici_res_t *res, int *len, char *fmt,...)
char * vici_find_str (vici_res_t *res, char *def, char *fmt,...)
int vici_find_int (vici_res_t *res, int def, char *fmt,...)
void vici_free_res (vici_res_t *res)
int vici_register (vici_conn_t *conn, char *name, vici_event_cb_t cb, void *user)
void vici_init ()
void vici_deinit ()
Detailed Description
libvici is a low-level client library for the "Versatile IKE Control Interface" protocol. While it uses libstrongswan and its thread-pool for asynchronous message delivery, this interface does not directly depend on libstrongswan interfaces and should be stable.
This interface provides the following basic functions:
vici_init()/vici_deinit(): Library initialization functions
vici_connect(): Connect to a vici service
vici_disconnect(): Disconnect from a vici service
Library initialization implicitly initializes libstrongswan and a small thread pool.
Connecting requires an uri, which is currently either a UNIX socket path prefixed with unix://, or a hostname:port touple prefixed with tcp://. Passing NULL takes the system default socket path.
After the connection has been established, request messages can be sent. Only a single thread may operate on a single connection instance simultaneously. To construct request messages, use the following functions:
vici_add_key_value() / vici_add_key_valuef(): Add key/value pairs
vici_begin(): Start constructing a new request message
vici_begin_section(): Open a new section to add contents to
vici_end_section(): Close a previously opened session
vici_begin_list(): Open a new list to add list items to
vici_end_list(): Close a previously opened list
vici_add_list_item() / vici_add_list_itemf(): Add list item
Once the request message is complete, it can be sent or cancelled with:
vici_submit()
vici_free_req()
If submitting a message is successful, a response message is returned. It can be processed using the following functions:
vici_parse(): Parse content type
vici_parse_name(): Parse name if content type provides one
vici_parse_name_eq(): Parse name and check if matches string
vici_parse_value() / vici_parse_value_str(): Parse value for content type
vici_dump(): Dump a full response to a FILE stream
vici_free_res(): Free response after use
Usually vici_parse() is called in a loop, and depending on the returned type the name and value can be inspected.
To register or unregister for asynchronous event messages vici_register() is used. The registered callback gets invoked by an asynchronous thread. To parse the event message, the vici_parse*() functions can be used.
Typedef Documentation
typedef struct vici_conn_t vici_conn_t
Opaque vici connection contex.
Definition at line 92 of file libvici.h.
typedef void(* vici_event_cb_t)(void *user, char *name, vici_res_t *msg)
Callback function invoked for received event messages.
It is not allowed to call vici_submit() from this callback.
Parameters
user user data, as passed to vici_connect
name name of received event
msg associated event message, destroyed by libvici
Definition at line 135 of file libvici.h.
typedef int(* vici_parse_section_cb_t)(void *user, vici_res_t *res, char *name)
Callback function for sections, invoked by vici_parse_cb().
Parameters
user user data, as passed to vici_parse_cb()
res message currently parsing
name name of the section
Returns
0 if parsed successfully
Definition at line 158 of file libvici.h.
typedef int(* vici_parse_value_cb_t)(void *user, vici_res_t *res, char *name, void *value, int len)
Callback function for key/value and list items, invoked by vici_parse_cb().
Parameters
user user data, as passed to vici_parse_cb()
res message currently parsing
name name of key or list
value value buffer
len length of value buffer
Returns
0 if parsed successfully
Definition at line 147 of file libvici.h.
typedef struct vici_req_t vici_req_t
Opaque vici request message.
Definition at line 97 of file libvici.h.
typedef struct vici_res_t vici_res_t
Opaque vici response/event message.
Definition at line 102 of file libvici.h.
Enumeration Type Documentation
enum vici_parse_t
Vici parse result, as returned by vici_parse().
Enumerator
VICI_PARSE_BEGIN_SECTION
encountered a section start, has a name
VICI_PARSE_END_SECTION
encountered a section end
VICI_PARSE_BEGIN_LIST
encountered a list start, has a name
VICI_PARSE_LIST_ITEM
encountered a list element, has a value
VICI_PARSE_END_LIST
encountered a list end
VICI_PARSE_KEY_VALUE
encountered a key/value pair, has a name and a value
VICI_PARSE_END
encountered valid end of message
VICI_PARSE_ERROR
parse error
Definition at line 107 of file libvici.h.
              {
     VICI_PARSE_BEGIN_SECTION,
     VICI_PARSE_END_SECTION,
     VICI_PARSE_BEGIN_LIST,
     VICI_PARSE_LIST_ITEM,
     VICI_PARSE_END_LIST,
     VICI_PARSE_KEY_VALUE,
     VICI_PARSE_END,
     VICI_PARSE_ERROR,
 } vici_parse_t;
Function Documentation
void vici_add_key_value (vici_req_t * req, char * key, void * buf, int len)
Add a key/value pair, using an as-is blob as value.
Parameters
req request message to add key/value pair to
key key name of key/value pair
buf pointer to blob to add as value
len length of value blob to add
Definition at line 318 of file libvici.c.
References vici_builder_t::add, vici_req_t::b, chunk_create(), and VICI_KEY_VALUE.
Referenced by add_file_key_value(), encode_section(), load_cert(), load_key(), and load_secret().
 {
     req->b->add(req->b, VICI_KEY_VALUE, key, chunk_create(buf, len));
 }
void vici_add_key_valuef (vici_req_t * req, char * key, char * fmt, ...)
Add a key/value pair, setting value from a printf() format string.
Parameters
req request message to add key/value pair to
key key name of key/value pair
fmt format string for value
... arguments to format string
Definition at line 323 of file libvici.c.
References vici_req_t::b, and vici_builder_t::vadd_kv.
Referenced by add_key_values(), encode_section(), initiate(), list_authorities(), list_certs(), list_pols(), list_pools(), list_sas(), load_cert(), load_key(), load_secret(), manage_policy(), terminate(), unload_authority(), unload_conn(), and unload_pool().
 {
     va_list args;
     va_start(args, fmt);
     req->b->vadd_kv(req->b, key, fmt, args);
     va_end(args);
 }
void vici_add_list_item (vici_req_t * req, void * buf, int len)
Add a list item to a currently open list, using an as-is blob.
Parameters
req request message to add list item to
buf pointer to blob to add as value
len length of value blob to add
Definition at line 337 of file libvici.c.
References vici_builder_t::add, vici_req_t::b, chunk_create(), and VICI_LIST_ITEM.
Referenced by add_file_list_key(), and encode_list().
 {
     req->b->add(req->b, VICI_LIST_ITEM, chunk_create(buf, len));
 }
void vici_add_list_itemf (vici_req_t * req, char * fmt, ...)
Add a list item to a currently open list, using a printf() format string.
Parameters
req request message to add list item to
fmt format string to create value from
... arguments to format string
Definition at line 342 of file libvici.c.
References vici_req_t::b, and vici_builder_t::vadd_li.
Referenced by add_list_key(), encode_list(), and load_secret().
 {
     va_list args;
     va_start(args, fmt);
     req->b->vadd_li(req->b, fmt, args);
     va_end(args);
 }
vici_req_t* vici_begin (char * name)
Begin a new vici message request.
This function always succeeds.
Parameters
name name of request command
Returns
request message, to add contents
Definition at line 296 of file libvici.c.
References b, INIT, req(), strdup, and vici_builder_create().
Referenced by clear_creds(), initiate(), list_authorities(), list_certs(), list_conns(), list_pols(), list_pools(), list_sas(), load_authority(), load_cert(), load_conn(), load_key(), load_pool(), load_secret(), manage_policy(), reload_settings(), START_TEST(), stats(), terminate(), unload_authority(), unload_conn(), unload_pool(), and version().
 {
     vici_req_t *req;
     INIT(req,
         .name = strdup(name),
         .b = vici_builder_create(),
     );
     return req;
 }
void vici_begin_list (vici_req_t * req, char * name)
Begin a list in a request message.
After starting a list, only list items can be added until the list gets closed by vici_end_list().
Parameters
req request message to begin list in
name name of list to begin
Definition at line 332 of file libvici.c.
References vici_builder_t::add, vici_req_t::b, and VICI_LIST_START.
Referenced by add_file_list_key(), add_list_key(), encode_list(), and load_secret().
 {
     req->b->add(req->b, VICI_LIST_START, name);
 }
void vici_begin_section (vici_req_t * req, char * name)
Begin a new section in a vici request message.
Parameters
req request message to create a new section in
name name of section to create
Definition at line 308 of file libvici.c.
References vici_builder_t::add, vici_req_t::b, and VICI_SECTION_START.
Referenced by add_sections(), encode_section(), load_authority(), load_conn(), and load_pool().
 {
     req->b->add(req->b, VICI_SECTION_START, name);
 }
vici_conn_t* vici_connect (char * uri)
Open a new vici connection.
On error, NULL is returned and errno is set appropriately.
Parameters
uri URI to connect to, NULL to use system default
Returns
opaque vici connection context, NULL on error
Definition at line 254 of file libvici.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, conn, stream_manager_t::connect, hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), INIT, lib, mutex, mutex_create(), MUTEX_TYPE_DEFAULT, stream_t::on_read, on_read(), library_t::streams, and VICI_DEFAULT_URI.
Referenced by call_command(), and START_TEST().
 {
     vici_conn_t *conn;
     stream_t *stream;
     stream = lib->streams->connect(lib->streams, uri ?: VICI_DEFAULT_URI);
     if (!stream)
     {
         return NULL;
     }
     INIT(conn,
         .stream = stream,
         .events = hashtable_create(hashtable_hash_str, hashtable_equals_str, 1),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .cond = condvar_create(CONDVAR_TYPE_DEFAULT),
     );
     stream->on_read(stream, on_read, conn);
     return conn;
 }
void vici_deinit ()
Deinitialize libvici after use.
Definition at line 757 of file libvici.c.
References processor_t::cancel, lib, library_deinit(), and library_t::processor.
Referenced by START_TEST().
 {
     lib->processor->cancel(lib->processor);
     library_deinit();
 }
void vici_disconnect (vici_conn_t * conn)
Close a vici connection.
Parameters
conn connection context
Definition at line 277 of file libvici.c.
References vici_conn_t::cond, hashtable_t::create_enumerator, enumerator_t::destroy, mutex_t::destroy, condvar_t::destroy, stream_t::destroy, hashtable_t::destroy, enumerator_t::enumerate, event, vici_conn_t::events, free(), vici_conn_t::mutex, event_t::name, and vici_conn_t::stream.
Referenced by call_command(), and START_TEST().
 {
     enumerator_t *enumerator;
     event_t *event;
     conn->stream->destroy(conn->stream);
     enumerator = conn->events->create_enumerator(conn->events);
     while (enumerator->enumerate(enumerator, NULL, &event))
     {
         free(event->name);
         free(event);
     }
     enumerator->destroy(enumerator);
     conn->events->destroy(conn->events);
     conn->mutex->destroy(conn->mutex);
     conn->cond->destroy(conn->cond);
     free(conn);
 }
int vici_dump (vici_res_t * res, char * label, int pretty, FILE * out)
Dump a message text representation to a FILE stream.
On error, errno is set to:
EBADMSG if the message is invalid
Parameters
res response message to dump
label a label to print for this message
pretty use pretty print with indentation
out FILE to dump to
Returns
0 if dumped complete message, 1 on error
Definition at line 435 of file libvici.c.
References vici_message_t::dump, EBADMSG, and vici_res_t::message.
Referenced by CALLBACK(), clear_creds(), initiate(), list_authorities(), list_certs(), list_conns(), list_pols(), list_pools(), list_sas(), load_authority(), load_cert(), load_conn(), load_key(), load_pool(), load_secret(), manage_policy(), reload_settings(), stats(), terminate(), unload_authority(), unload_conn(), unload_pool(), and version().
 {
     if (res->message->dump(res->message, label, pretty, out))
     {
         return 0;
     }
     errno = EBADMSG;
     return 1;
 }
void vici_end_list (vici_req_t * req)
End a previously opened list in a request message.
Parameters
req request message to end list in
Definition at line 351 of file libvici.c.
References vici_builder_t::add, vici_req_t::b, and VICI_LIST_END.
Referenced by add_file_list_key(), add_list_key(), encode_list(), and load_secret().
 {
     req->b->add(req->b, VICI_LIST_END);
 }
void vici_end_section (vici_req_t * req)
End a previously opened section.
Parameters
req request message to close an open section in
Definition at line 313 of file libvici.c.
References vici_builder_t::add, vici_req_t::b, and VICI_SECTION_END.
Referenced by add_sections(), encode_section(), load_authority(), load_conn(), and load_pool().
 {
     req->b->add(req->b, VICI_SECTION_END);
 }
void* vici_find (vici_res_t * res, int * len, char * fmt, ...)
Definition at line 633 of file libvici.c.
References chunk_empty, chunk_t::len, vici_res_t::message, chunk_t::ptr, value, and vici_message_t::vget_value.
Referenced by CALLBACK().
 {
     va_list args;
     chunk_t value;
     va_start(args, fmt);
     value = res->message->vget_value(res->message, chunk_empty, fmt, args);
     va_end(args);
     *len = value.len;
     return value.ptr;
 }
int vici_find_int (vici_res_t * res, int def, char * fmt, ...)
Find an integer value in a message for a given key.
Sections can be selected by prefixing them separated by dots.
Parameters
res response message to parse
def default value, if key not found
fmt printf format string of key and sections
... arguments to format string
Returns
integer value, def if not found
Definition at line 658 of file libvici.c.
References vici_res_t::message, val, and vici_message_t::vget_int.
Referenced by CALLBACK().
 {
     va_list args;
     int val;
     va_start(args, fmt);
     val = res->message->vget_int(res->message, def, fmt, args);
     va_end(args);
     return val;
 }
char* vici_find_str (vici_res_t * res, char * def, char * fmt, ...)
Find a string value in a message for a given key.
Sections can be selected by prefixing them separated by dots.
Parameters
res response message to parse
def default value, if key not found
fmt printf format string of key and sections
... arguments to format string
Returns
string, def if not found
Definition at line 646 of file libvici.c.
References vici_res_t::message, str, and vici_message_t::vget_str.
Referenced by CALLBACK(), initiate(), load_authority(), load_cert(), load_conn(), load_key(), load_pool(), load_secret(), manage_policy(), reload_settings(), stats(), terminate(), unload_authority(), unload_conn(), unload_pool(), and version().
 {
     va_list args;
     char *str;
     va_start(args, fmt);
     str = res->message->vget_str(res->message, def, fmt, args);
     va_end(args);
     return str;
 }
void vici_free_req (vici_req_t * req)
Cancel a request message started.
If a request created by vici_begin() does not get submitted using vici_submit(), it has to get freed using this call.
Parameters
req request message to clean up
Definition at line 428 of file libvici.c.
References vici_req_t::b, vici_builder_t::destroy, free(), and vici_req_t::name.
Referenced by load_authority(), and load_conn().
 {
     free(req->name);
     req->b->destroy(req->b);
     free(req);
 }
void vici_free_res (vici_res_t * res)
Clean up a received response message.
Event messages get cleaned up by the library, it is not allowed to call vici_free_res() from within a vici_event_cb_t.
Parameters
res response message to free
Definition at line 670 of file libvici.c.
References enumerator_t::destroy, vici_message_t::destroy, linked_list_t::destroy_function, vici_res_t::enumerator, free(), vici_res_t::message, and vici_res_t::strings.
Referenced by clear_creds(), initiate(), list_authorities(), list_certs(), list_conns(), list_pols(), list_pools(), list_sas(), load_authority(), load_cert(), load_conn(), load_key(), load_pool(), load_secret(), manage_policy(), reload_settings(), START_TEST(), stats(), terminate(), unload_authority(), unload_conn(), unload_pool(), and version().
 {
     res->strings->destroy_function(res->strings, free);
     res->message->destroy(res->message);
     res->enumerator->destroy(res->enumerator);
     free(res);
 }
void vici_init ()
Initialize libvici before first time use.
Definition at line 746 of file libvici.c.
References dbg_default_set_level(), processor_t::get_total_threads, lib, library_init(), library_t::processor, and processor_t::set_threads.
Referenced by START_TEST().
 {
     library_init(NULL, "vici");
     if (lib->processor->get_total_threads(lib->processor) < 4)
     {
         dbg_default_set_level(0);
         lib->processor->set_threads(lib->processor, 4);
         dbg_default_set_level(1);
     }
 }
vici_parse_t vici_parse (vici_res_t * res)
Parse next element from a vici response message.
Parameters
res response message to parse
Returns
parse result
Definition at line 445 of file libvici.c.
References enumerator_t::enumerate, vici_res_t::enumerator, vici_res_t::name, vici_res_t::type, vici_res_t::value, VICI_END, VICI_KEY_VALUE, VICI_LIST_END, VICI_LIST_ITEM, VICI_LIST_START, VICI_PARSE_BEGIN_LIST, VICI_PARSE_BEGIN_SECTION, VICI_PARSE_END, VICI_PARSE_END_LIST, VICI_PARSE_END_SECTION, VICI_PARSE_ERROR, VICI_PARSE_KEY_VALUE, VICI_PARSE_LIST_ITEM, VICI_SECTION_END, and VICI_SECTION_START.
Referenced by CALLBACK(), decode_list(), decode_section(), event_cb(), and vici_parse_cb().
 {
     if (!res->enumerator->enumerate(res->enumerator,
                                     &res->type, &res->name, &res->value))
     {
         return VICI_PARSE_ERROR;
     }
     switch (res->type)
     {
         case VICI_END:
             return VICI_PARSE_END;
         case VICI_SECTION_START:
             return VICI_PARSE_BEGIN_SECTION;
         case VICI_SECTION_END:
             return VICI_PARSE_END_SECTION;
         case VICI_LIST_START:
             return VICI_PARSE_BEGIN_LIST;
         case VICI_LIST_ITEM:
             return VICI_PARSE_LIST_ITEM;
         case VICI_LIST_END:
             return VICI_PARSE_END_LIST;
         case VICI_KEY_VALUE:
             return VICI_PARSE_KEY_VALUE;
         default:
             return VICI_PARSE_ERROR;
     }
 }
int vici_parse_cb (vici_res_t * res, vici_parse_section_cb_t section, vici_parse_value_cb_t kv, vici_parse_value_cb_t li, void * user)
Parse a complete message with callbacks.
Any of the callbacks may be NULL to skip this kind of item. Callbacks are invoked for the current section level only. To descent into sections, call vici_parse_cb() from within a section callback.
On error, errno is set to:
EBADMSG if message encoding invalid
Any other errno set by the invoked callbacks
Parameters
res message to parse
section callback invoked for each section
kv callback invoked for key/value pairs
li callback invoked for list items
user user data to pass to callbacks
Returns
0 if parsing successful
Definition at line 541 of file libvici.c.
References base, EBADMSG, len, vici_res_t::level, list, name, section, TRUE, value, vici_parse(), VICI_PARSE_BEGIN_LIST, VICI_PARSE_BEGIN_SECTION, VICI_PARSE_END, VICI_PARSE_END_LIST, VICI_PARSE_END_SECTION, VICI_PARSE_ERROR, VICI_PARSE_KEY_VALUE, VICI_PARSE_LIST_ITEM, vici_parse_name(), and vici_parse_value().
Referenced by CALLBACK(), list_authorities(), list_conns(), and list_pools().
 {
     char *name, *list = NULL;
     void *value;
     int base, len, ret;
     base = res->level;
     while (TRUE)
     {
         switch (vici_parse(res))
         {
             case VICI_PARSE_KEY_VALUE:
                 if (res->level == base)
                 {
                     if (kv)
                     {
                         name = vici_parse_name(res);
                         value = vici_parse_value(res, &len);
                         if (name && value)
{
                             ret = kv(user, res, name, value, len);
                             if (ret)
{
                                 return ret;
                             }
                         }
                     }
                 }
                 break;
             case VICI_PARSE_BEGIN_SECTION:
                 if (res->level++ == base)
                 {
                     if (section)
                     {
                         name = vici_parse_name(res);
                         if (name)
{
                             ret = section(user, res, name);
                             if (ret)
{
                                 return ret;
                             }
                         }
                     }
                 }
                 break;
             case VICI_PARSE_END_SECTION:
                 if (res->level-- == base)
                 {
                     return 0;
                 }
                 break;
             case VICI_PARSE_END:
                 res->level = 0;
                 return 0;
             case VICI_PARSE_BEGIN_LIST:
                 if (res->level == base)
                 {
                     list = vici_parse_name(res);
                 }
                 break;
             case VICI_PARSE_LIST_ITEM:
                 if (list && li)
                 {
                     value = vici_parse_value(res, &len);
                     if (value)
                     {
                         ret = li(user, res, list, value, len);
                         if (ret)
{
                             return ret;
                         }
                     }
                 }
                 break;
             case VICI_PARSE_END_LIST:
                 if (res->level == base)
                 {
                     list = NULL;
                 }
                 break;
             case VICI_PARSE_ERROR:
                 res->level = 0;
                 errno = EBADMSG;
                 return 1;
         }
     }
 }
char* vici_parse_name (vici_res_t * res)
Parse name tag / key of a previously parsed element.
This call is valid only after vici_parse() returned VICI_PARSE_KEY_VALUE, VICI_PARSE_BEGIN_SECTION or VICI_PARSE_BEGIN_LIST.
The string is valid until vici_free_res() is called.
On error, errno is set to:
EINVAL if not in valid parser state
Parameters
res response message to parse
Returns
name tag / key, NULL on error
Definition at line 473 of file libvici.c.
References linked_list_t::insert_last, name, vici_res_t::name, strdup, vici_res_t::strings, vici_res_t::type, VICI_KEY_VALUE, VICI_LIST_START, and VICI_SECTION_START.
Referenced by CALLBACK(), decode_list(), decode_section(), event_cb(), and vici_parse_cb().
 {
     char *name;
     switch (res->type)
     {
         case VICI_SECTION_START:
         case VICI_LIST_START:
         case VICI_KEY_VALUE:
             name = strdup(res->name);
             res->strings->insert_last(res->strings, name);
             return name;
         default:
             errno = EINVAL;
             return NULL;
     }
 }
int vici_parse_name_eq (vici_res_t * res, char * name)
Compare name tag / key of a previusly parsed element.
This call is valid only after vici_parse() returned VICI_PARSE_KEY_VALUE, VICI_PARSE_BEGIN_SECTION or VICI_PARSE_BEGIN_LIST.
Parameters
res response message to parse
name string to compare
Returns
1 if name equals, 0 if not
Definition at line 491 of file libvici.c.
References vici_res_t::name, streq(), vici_res_t::type, VICI_KEY_VALUE, VICI_LIST_START, and VICI_SECTION_START.
 {
     switch (res->type)
     {
         case VICI_SECTION_START:
         case VICI_LIST_START:
         case VICI_KEY_VALUE:
             return streq(name, res->name) ? 1 : 0;
         default:
             return 0;
     }
 }
void* vici_parse_value (vici_res_t * res, int * len)
Parse value of a previously parsed element, as a blob.
This call is valid only after vici_parse() returned VICI_PARSE_KEY_VALUE or VICI_PARSE_LIST_ITEM.
The string is valid until vici_free_res() is called.
On error, errno is set to:
EINVAL if not in valid parser state
Parameters
res response message to parse
len pointer receiving value length
Returns
pointer to value, NULL on error
Definition at line 504 of file libvici.c.
References chunk_t::len, chunk_t::ptr, vici_res_t::type, vici_res_t::value, VICI_KEY_VALUE, and VICI_LIST_ITEM.
Referenced by CALLBACK(), decode_list(), decode_section(), and vici_parse_cb().
 {
     switch (res->type)
     {
         case VICI_LIST_ITEM:
         case VICI_KEY_VALUE:
             *len = res->value.len;
             return res->value.ptr;
         default:
             *len = 0;
             errno = EINVAL;
             return NULL;
     }
 }
char* vici_parse_value_str (vici_res_t * res)
Parse value of a previously parsed element, as a string.
This call is valid only after vici_parse() returned VICI_PARSE_KEY_VALUE or VICI_PARSE_LIST_ITEM.
This call is successful only if the value contains no non-printable characters. The string is valid until vici_free_res() is called.
On error, errno is set to:
EBADMSG if value is not a printable string
EINVAL if not in valid parser state
Parameters
res response message to parse
Returns
value as string, NULL on error
Definition at line 519 of file libvici.c.
References chunk_printable(), EBADMSG, linked_list_t::insert_last, chunk_t::len, chunk_t::ptr, vici_res_t::strings, strndup(), vici_res_t::type, val, vici_res_t::value, VICI_KEY_VALUE, and VICI_LIST_ITEM.
Referenced by decode_list(), decode_section(), and event_cb().
 {
     char *val;
     switch (res->type)
     {
         case VICI_LIST_ITEM:
         case VICI_KEY_VALUE:
             if (!chunk_printable(res->value, NULL, 0))
             {
                 errno = EBADMSG;
                 return NULL;
             }
             val = strndup(res->value.ptr, res->value.len);
             res->strings->insert_last(res->strings, val);
             return val;
         default:
             errno = EINVAL;
             return NULL;
     }
 }
int vici_register (vici_conn_t * conn, char * name, vici_event_cb_t cb, void * user)
(Un-)Register for events of a given kind.
Events callbacks get invoked by a different thread from the libstrongswan thread pool. On failure, errno is set to:
ENOENT if the event name is unknown
EBADMSG if the response is invalid
Any other IO related errno
Parameters
conn connection context
name name of event messages to register to
cb callback function to register, NULL to unregister
user user data passed to callback invocations
Returns
0 if registered successfully
Definition at line 678 of file libvici.c.
References vici_conn_t::cond, vici_conn_t::error, event, vici_conn_t::events, free(), INIT, len, mutex_t::lock, vici_conn_t::mutex, event_t::name, stream_t::on_read, on_read(), hashtable_t::put, hashtable_t::remove, strdup, vici_conn_t::stream, mutex_t::unlock, VICI_EVENT_REGISTER, VICI_EVENT_UNREGISTER, condvar_t::wait, vici_conn_t::wait, WAIT_FAILURE, WAIT_IDLE, WAIT_READ_ERROR, WAIT_SUCCESS, and stream_t::write_all.
Referenced by initiate(), list_authorities(), list_certs(), list_conns(), list_pols(), list_sas(), logcmd(), monitor_sas(), START_TEST(), and terminate().
 {
     event_t *event;
     u_int32_t len;
     u_int8_t namelen, op;
     int ret = 1;
     op = cb ? VICI_EVENT_REGISTER : VICI_EVENT_UNREGISTER;
     namelen = strlen(name);
     len = htonl(sizeof(op) + sizeof(namelen) + namelen);
     if (!conn->stream->write_all(conn->stream, &len, sizeof(len)) ||
         !conn->stream->write_all(conn->stream, &op, sizeof(op)) ||
         !conn->stream->write_all(conn->stream, &namelen, sizeof(namelen)) ||
         !conn->stream->write_all(conn->stream, name, namelen))
     {
         return 1;
     }
     conn->mutex->lock(conn->mutex);
     while (conn->wait == WAIT_IDLE)
     {
         conn->cond->wait(conn->cond, conn->mutex);
     }
     switch (conn->wait)
     {
         case WAIT_SUCCESS:
             ret = 0;
             break;
         case WAIT_READ_ERROR:
             errno = conn->error;
             break;
         case WAIT_FAILURE:
         default:
             errno = ENOENT;
             break;
     }
     conn->wait = WAIT_IDLE;
     conn->mutex->unlock(conn->mutex);
     conn->stream->on_read(conn->stream, on_read, conn);
     if (ret == 0)
     {
         conn->mutex->lock(conn->mutex);
         if (cb)
         {
             INIT(event,
                 .name = strdup(name),
                 .cb = cb,
                 .user = user,
             );
             event = conn->events->put(conn->events, event->name, event);
         }
         else
         {
             event = conn->events->remove(conn->events, name);
         }
         conn->mutex->unlock(conn->mutex);
         if (event)
         {
             free(event->name);
             free(event);
         }
     }
     return ret;
 }
vici_res_t* vici_submit (vici_req_t * req, vici_conn_t * conn)
Submit a request message, and wait for response.
The request messages gets cleaned up by this call and gets invalid. On error, NULL is returned an errno is set to:
EINVAL if the request is invalid/incomplete
ENOENT if the command is unknown
EBADMSG if the response is invalid
Any other IO related errno
Parameters
req request message to send
conn connection context to send message over
Returns
response message, NULL on error
Definition at line 356 of file libvici.c.
References vici_req_t::b, chunk_empty, vici_conn_t::cond, vici_message_t::create_enumerator, data, vici_message_t::destroy, vici_conn_t::error, vici_builder_t::finalize, free(), vici_message_t::get_encoding, INIT, chunk_t::len, len, linked_list_create(), mutex_t::lock, vici_conn_t::mutex, vici_req_t::name, stream_t::on_read, on_read(), chunk_t::ptr, vici_conn_t::queue, res, vici_conn_t::stream, TRUE, mutex_t::unlock, VICI_CMD_REQUEST, vici_message_create_from_data(), condvar_t::wait, vici_conn_t::wait, WAIT_FAILURE, WAIT_IDLE, WAIT_READ_ERROR, WAIT_SUCCESS, and stream_t::write_all.
Referenced by clear_creds(), initiate(), list_authorities(), list_certs(), list_conns(), list_pols(), list_pools(), list_sas(), load_authority(), load_cert(), load_conn(), load_key(), load_pool(), load_secret(), manage_policy(), reload_settings(), START_TEST(), stats(), terminate(), unload_authority(), unload_conn(), unload_pool(), and version().
 {
     vici_message_t *message;
     vici_res_t *res;
     chunk_t data;
     u_int32_t len;
     u_int8_t namelen, op;
     message = req->b->finalize(req->b);
     if (!message)
     {
         errno = EINVAL;
         return NULL;
     }
     op = VICI_CMD_REQUEST;
     namelen = strlen(req->name);
     data = message->get_encoding(message);
     len = htonl(sizeof(op) + sizeof(namelen) + namelen + data.len);
     if (!conn->stream->write_all(conn->stream, &len, sizeof(len)) ||
         !conn->stream->write_all(conn->stream, &op, sizeof(op)) ||
         !conn->stream->write_all(conn->stream, &namelen, sizeof(namelen)) ||
         !conn->stream->write_all(conn->stream, req->name, namelen) ||
         !conn->stream->write_all(conn->stream, data.ptr, data.len))
     {
         free(req->name);
         free(req);
         message->destroy(message);
         return NULL;
     }
     free(req->name);
     free(req);
     message->destroy(message);
     message = NULL;
     conn->mutex->lock(conn->mutex);
     while (conn->wait == WAIT_IDLE)
     {
         conn->cond->wait(conn->cond, conn->mutex);
     }
     switch (conn->wait)
     {
         case WAIT_SUCCESS:
             message = vici_message_create_from_data(conn->queue, TRUE);
             conn->queue = chunk_empty;
             break;
         case WAIT_READ_ERROR:
             errno = conn->error;
             break;
         case WAIT_FAILURE:
         default:
             errno = ENOENT;
             break;
     }
     conn->wait = WAIT_IDLE;
     conn->mutex->unlock(conn->mutex);
     conn->stream->on_read(conn->stream, on_read, conn);
     if (message)
     {
         INIT(res,
             .message = message,
             .enumerator = message->create_enumerator(message),
             .strings = linked_list_create(),
         );
         return res;
     }
     return NULL;
 }