strongSwan: credential encoder
credential encoder
tkm
Functions
bool tkm_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Detailed Description
Function Documentation
bool tkm_encoder_encode (cred_encoding_type_t type, chunk_t * encoding, va_list args)
Encoding function for TKM key fingerprints.
See header.
Definition at line 94 of file tkm_encoder.c.
References build_info_sha1(), build_sha1(), FALSE, KEYID_PUBKEY_INFO_SHA1, and KEYID_PUBKEY_SHA1.
Referenced by main().
 {
     switch (type)
     {
         case KEYID_PUBKEY_INFO_SHA1:
             return build_info_sha1(encoding, args);
         case KEYID_PUBKEY_SHA1:
             return build_sha1(encoding, args);
         default:
             return FALSE;
     }
 }