strongSwan: xauth_generic.c File Reference
xauth_generic.c File Reference
#include "xauth_generic.h"
#include <daemon.h>
#include <library.h>
Classes
struct private_xauth_generic_t
Typedefs
typedef struct
private_xauth_generic_t private_xauth_generic_t
Functions
METHOD (xauth_method_t, initiate_peer, status_t, private_xauth_generic_t *this, cp_payload_t **out)
METHOD (xauth_method_t, process_peer, status_t, private_xauth_generic_t *this, cp_payload_t *in, cp_payload_t **out)
METHOD (xauth_method_t, initiate_server, status_t, private_xauth_generic_t *this, cp_payload_t **out)
METHOD (xauth_method_t, process_server, status_t, private_xauth_generic_t *this, cp_payload_t *in, cp_payload_t **out)
METHOD (xauth_method_t, get_identity, identification_t *, private_xauth_generic_t *this)
METHOD (xauth_method_t, destroy, void, private_xauth_generic_t *this)
xauth_generic_t * xauth_generic_create_peer (identification_t *server, identification_t *peer, char *profile)
xauth_generic_t * xauth_generic_create_server (identification_t *server, identification_t *peer, char *profile)
Typedef Documentation
typedef struct private_xauth_generic_t private_xauth_generic_t
Definition at line 21 of file xauth_generic.c.
Function Documentation
METHOD (xauth_method_t , initiate_peer , status_t , private_xauth_generic_t * this, cp_payload_t ** out)
Definition at line 44 of file xauth_generic.c.
References FAILED.
 {
     /* peer never initiates */
     return FAILED;
 }
METHOD (xauth_method_t , process_peer , status_t , private_xauth_generic_t * this, cp_payload_t * in, cp_payload_t ** out)
Definition at line 51 of file xauth_generic.c.
References cp_payload_t::add_attribute, CFG_REPLY, chunk_printable(), configuration_attribute_create_chunk(), cp, cp_payload_create_type(), cp_payload_t::create_attribute_enumerator, library_t::credmgr, DBG1, DBG_CFG, DBG_IKE, enumerator_t::destroy, shared_key_t::destroy, cp_payload_t::destroy, enumerator_t::enumerate, FAILED, free(), configuration_attribute_t::get_chunk, shared_key_t::get_key, credential_manager_t::get_shared, configuration_attribute_t::get_type, chunk_t::len, lib, msg, NEED_MORE, PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, chunk_t::ptr, server, SHARED_EAP, SHARED_PIN, type, XAUTH_MESSAGE, XAUTH_NEXT_PIN, XAUTH_USER_NAME, and XAUTH_USER_PASSWORD.
 {
     configuration_attribute_t *attr;
     enumerator_t *enumerator;
     shared_key_t *shared;
     cp_payload_t *cp;
     chunk_t msg;
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &attr))
     {
         if (attr->get_type(attr) == XAUTH_MESSAGE)
         {
             chunk_printable(attr->get_chunk(attr), &msg, '?');
             DBG1(DBG_CFG, "XAuth message: %.*s", (int)msg.len, msg.ptr);
             free(msg.ptr);
         }
     }
     enumerator->destroy(enumerator);
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REPLY);
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &attr))
     {
         shared_key_type_t type = SHARED_EAP;
         switch (attr->get_type(attr))
         {
             case XAUTH_USER_NAME:
                 cp->add_attribute(cp, configuration_attribute_create_chunk(
                             PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_NAME,
                             this->peer->get_encoding(this->peer)));
                 break;
             case XAUTH_NEXT_PIN:
                 type = SHARED_PIN;
                 /* FALL */
             case XAUTH_USER_PASSWORD:
                 shared = lib->credmgr->get_shared(lib->credmgr, type,
                                                   this->peer, this->server);
                 if (!shared)
                 {
                     DBG1(DBG_IKE, "no XAuth %s found for '%Y' - '%Y'",
                          type == SHARED_EAP ? "password" : "PIN",
                          this->peer, this->server);
                     enumerator->destroy(enumerator);
                     cp->destroy(cp);
                     return FAILED;
                 }
                 cp->add_attribute(cp, configuration_attribute_create_chunk(
                             PLV1_CONFIGURATION_ATTRIBUTE, attr->get_type(attr),
                             shared->get_key(shared)));
                 shared->destroy(shared);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     *out = cp;
     return NEED_MORE;
 }
METHOD (xauth_method_t , initiate_server , status_t , private_xauth_generic_t * this, cp_payload_t ** out)
Definition at line 116 of file xauth_generic.c.
References cp_payload_t::add_attribute, CFG_REQUEST, chunk_empty, configuration_attribute_create_chunk(), cp, cp_payload_create_type(), NEED_MORE, PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_NAME, and XAUTH_USER_PASSWORD.
 {
     cp_payload_t *cp;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REQUEST);
     cp->add_attribute(cp, configuration_attribute_create_chunk(
                 PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_NAME, chunk_empty));
     cp->add_attribute(cp, configuration_attribute_create_chunk(
                 PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_PASSWORD, chunk_empty));
     *out = cp;
     return NEED_MORE;
 }
METHOD (xauth_method_t , process_server , status_t , private_xauth_generic_t * this, cp_payload_t * in, cp_payload_t ** out)
Definition at line 130 of file xauth_generic.c.
References chunk_empty, chunk_equals_const(), cp_payload_t::create_attribute_enumerator, credential_manager_t::create_shared_enumerator, library_t::credmgr, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FAILED, configuration_attribute_t::get_chunk, shared_key_t::get_key, configuration_attribute_t::get_type, id, identification_create_from_data(), chunk_t::len, lib, chunk_t::ptr, server, SHARED_EAP, status, SUCCESS, XAUTH_USER_NAME, and XAUTH_USER_PASSWORD.
 {
     configuration_attribute_t *attr;
     enumerator_t *enumerator;
     shared_key_t *shared;
     identification_t *id;
     chunk_t user = chunk_empty, pass = chunk_empty;
     status_t status = FAILED;
     int tried = 0;
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &attr))
     {
         switch (attr->get_type(attr))
         {
             case XAUTH_USER_NAME:
                 user = attr->get_chunk(attr);
                 break;
             case XAUTH_USER_PASSWORD:
                 pass = attr->get_chunk(attr);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (!user.ptr || !pass.ptr)
     {
         DBG1(DBG_IKE, "peer did not respond to our XAuth request");
         return FAILED;
     }
     if (user.len)
     {
         id = identification_create_from_data(user);
         if (!id)
         {
             DBG1(DBG_IKE, "failed to parse provided XAuth username");
             return FAILED;
         }
         this->peer->destroy(this->peer);
         this->peer = id;
     }
     if (pass.len && pass.ptr[pass.len - 1] == 0)
     {   /* fix null-terminated passwords (Android etc.) */
         pass.len -= 1;
     }
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                         SHARED_EAP, this->server, this->peer);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         if (chunk_equals_const(shared->get_key(shared), pass))
         {
             status = SUCCESS;
             break;
         }
         tried++;
     }
     enumerator->destroy(enumerator);
     if (status != SUCCESS)
     {
         if (!tried)
         {
             DBG1(DBG_IKE, "no XAuth secret found for '%Y' - '%Y'",
                  this->server, this->peer);
         }
         else
         {
             DBG1(DBG_IKE, "none of %d found XAuth secrets for '%Y' - '%Y' "
                  "matched", tried, this->server, this->peer);
         }
     }
     return status;
 }
METHOD (xauth_method_t , get_identity , identification_t * , private_xauth_generic_t * this)
Definition at line 207 of file xauth_generic.c.
 {
     return this->peer;
 }
METHOD (xauth_method_t , destroy , void , private_xauth_generic_t * this)
Definition at line 213 of file xauth_generic.c.
References free(), and server.
 {
     this->server->destroy(this->server);
     this->peer->destroy(this->peer);
     free(this);
 }