strongSwan: dhcp_plugin.c File Reference
dhcp_plugin.c File Reference
#include "dhcp_plugin.h"
#include <daemon.h>
#include <plugins/plugin_feature.h>
#include "dhcp_socket.h"
#include "dhcp_provider.h"
Classes
struct private_dhcp_plugin_t
Typedefs
typedef struct
private_dhcp_plugin_t private_dhcp_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_dhcp_plugin_t *this)
static bool plugin_cb (private_dhcp_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_dhcp_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_dhcp_plugin_t *this)
plugin_t * dhcp_plugin_create ()
Typedef Documentation
typedef struct private_dhcp_plugin_t private_dhcp_plugin_t
Definition at line 27 of file dhcp_plugin.c.
Function Documentation
plugin_t* dhcp_plugin_create ()
Plugin constructor.
Definition at line 105 of file dhcp_plugin.c.
References CAP_NET_BIND_SERVICE, CAP_NET_RAW, library_t::caps, capabilities_t::check, DBG1, DBG_NET, INIT, capabilities_t::keep, and lib.
 {
     private_dhcp_plugin_t *this;
     if (!lib->caps->check(lib->caps, CAP_NET_BIND_SERVICE))
     {   /* required to bind DHCP socket (port 68) */
         DBG1(DBG_NET, "dhcp plugin requires CAP_NET_BIND_SERVICE capability");
         return NULL;
     }
     else if (!lib->caps->keep(lib->caps, CAP_NET_RAW))
     {   /* required to open DHCP receive socket (AF_PACKET). according to
          * capabilities(7) it is also required to use the socket */
         DBG1(DBG_NET, "dhcp plugin requires CAP_NET_RAW capability");
         return NULL;
     }
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_dhcp_plugin_t * this)
Definition at line 50 of file dhcp_plugin.c.
 {
     return "dhcp";
 }
METHOD (plugin_t , get_features , int , private_dhcp_plugin_t * this, plugin_feature_t * features[])
Definition at line 84 of file dhcp_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_DEPENDS, PLUGIN_PROVIDE, and RNG_WEAK.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "dhcp"),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_dhcp_plugin_t * this)
Definition at line 96 of file dhcp_plugin.c.
References free().
 {
     free(this);
 }
static bool plugin_cb (private_dhcp_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 59 of file dhcp_plugin.c.
References attribute_manager_t::add_provider, daemon_t::attributes, charon, dhcp_provider_create(), dhcp_socket_create(), FALSE, attribute_manager_t::remove_provider, socket, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->socket = dhcp_socket_create();
         if (!this->socket)
         {
             return FALSE;
         }
         this->provider = dhcp_provider_create(this->socket);
         charon->attributes->add_provider(charon->attributes,
                                          &this->provider->provider);
     }
     else
     {
         charon->attributes->remove_provider(charon->attributes,
                                             &this->provider->provider);
         this->provider->destroy(this->provider);
         this->socket->destroy(this->socket);
     }
     return TRUE;
 }