strongSwan: rdrand_plugin.c File Reference
rdrand_plugin.c File Reference
#include "rdrand_plugin.h"
#include "rdrand_rng.h"
#include <stdio.h>
#include <library.h>
#include <utils/debug.h>
#include <utils/cpu_feature.h>
Classes
struct private_rdrand_plugin_t
Typedefs
typedef struct
private_rdrand_plugin_t private_rdrand_plugin_t
typedef enum cpuid_feature_t cpuid_feature_t
Functions
METHOD (plugin_t, get_name, char *, private_rdrand_plugin_t *this)
METHOD (plugin_t, get_features, int, private_rdrand_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_rdrand_plugin_t *this)
plugin_t * rdrand_plugin_create ()
Typedef Documentation
typedef enum cpuid_feature_t cpuid_feature_t
Definition at line 26 of file rdrand_plugin.c.
typedef struct private_rdrand_plugin_t private_rdrand_plugin_t
Definition at line 25 of file rdrand_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_rdrand_plugin_t * this)
Definition at line 39 of file rdrand_plugin.c.
 {
     return "rdrand";
 }
METHOD (plugin_t , get_features , int , private_rdrand_plugin_t * this, plugin_feature_t * features[])
Definition at line 45 of file rdrand_plugin.c.
References countof, cpu_feature_available(), CPU_FEATURE_RDRAND, DBG2, DBG_LIB, ENCR_AES_CBC, PLUGIN_DEPENDS, PLUGIN_PROVIDE, PLUGIN_REGISTER, rdrand_rng_create(), RNG_STRONG, RNG_TRUE, and RNG_WEAK.
 {
     static plugin_feature_t f[] = {
         PLUGIN_REGISTER(RNG, rdrand_rng_create),
             PLUGIN_PROVIDE(RNG, RNG_WEAK),
             PLUGIN_PROVIDE(RNG, RNG_STRONG),
             PLUGIN_PROVIDE(RNG, RNG_TRUE),
                 PLUGIN_DEPENDS(CRYPTER, ENCR_AES_CBC, 16),
     };
     *features = f;
     if (cpu_feature_available(CPU_FEATURE_RDRAND))
     {
         DBG2(DBG_LIB, "detected RDRAND support, enabled");
         return countof(f);
     }
     DBG2(DBG_LIB, "no RDRAND support detected, disabled");
     return 0;
 }
METHOD (plugin_t , destroy , void , private_rdrand_plugin_t * this)
Definition at line 65 of file rdrand_plugin.c.
References free().
 {
     free(this);
 }
plugin_t* rdrand_plugin_create ()
Definition at line 74 of file rdrand_plugin.c.
References destroy(), INIT, and return_false().
 {
     private_rdrand_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .reload = (void*)return_false,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }