strongSwan: encrypted_payload.c File Reference
encrypted_payload.c File Reference
#include <stddef.h>
#include <string.h>
#include "encrypted_payload.h"
#include "encrypted_fragment_payload.h"
#include <daemon.h>
#include <encoding/payloads/encodings.h>
#include <collections/linked_list.h>
#include <encoding/parser.h>
Classes
struct private_encrypted_payload_t
struct private_encrypted_fragment_payload_t
Typedefs
typedef struct
private_encrypted_payload_t private_encrypted_payload_t
typedef struct
private_encrypted_fragment_payload_t private_encrypted_fragment_payload_t
Functions
METHOD (payload_t, verify, status_t, private_encrypted_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_encrypted_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_encrypted_payload_t *this)
METHOD (payload_t, get_type, payload_type_t, private_encrypted_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_encrypted_payload_t *this)
METHOD (payload_t, set_next_type, void, private_encrypted_payload_t *this, payload_type_t type)
static size_t compute_overhead (aead_t *aead, size_t len)
static void compute_length (private_encrypted_payload_t *this)
METHOD2 (payload_t, encrypted_payload_t, get_length, size_t, private_encrypted_payload_t *this)
METHOD (encrypted_payload_t, add_payload, void, private_encrypted_payload_t *this, payload_t *payload)
METHOD (encrypted_payload_t, remove_payload, payload_t *, private_encrypted_payload_t *this)
static chunk_t generate (private_encrypted_payload_t *this, generator_t *generator)
METHOD (encrypted_payload_t, generate_payloads, void, private_encrypted_payload_t *this, generator_t *generator)
static chunk_t append_header (private_encrypted_payload_t *this, chunk_t assoc)
static status_t encrypt_content (char *label, aead_t *aead, u_int64_t mid, chunk_t plain, chunk_t assoc, chunk_t *encrypted)
METHOD (encrypted_payload_t, encrypt, status_t, private_encrypted_payload_t *this, u_int64_t mid, chunk_t assoc)
METHOD (encrypted_payload_t, encrypt_v1, status_t, private_encrypted_payload_t *this, u_int64_t mid, chunk_t iv)
static status_t parse (private_encrypted_payload_t *this, chunk_t plain)
static status_t decrypt_content (char *label, aead_t *aead, chunk_t encrypted, chunk_t assoc, chunk_t *plain)
METHOD (encrypted_payload_t, decrypt, status_t, private_encrypted_payload_t *this, chunk_t assoc)
METHOD (encrypted_payload_t, decrypt_plain, status_t, private_encrypted_payload_t *this, chunk_t assoc)
METHOD (encrypted_payload_t, decrypt_v1, status_t, private_encrypted_payload_t *this, chunk_t iv)
METHOD (encrypted_payload_t, set_transform, void, private_encrypted_payload_t *this, aead_t *aead)
METHOD2 (payload_t, encrypted_payload_t, destroy, void, private_encrypted_payload_t *this)
encrypted_payload_t * encrypted_payload_create (payload_type_t type)
encrypted_payload_t * encrypted_payload_create_from_plain (payload_type_t next, chunk_t plain)
METHOD (payload_t, frag_verify, status_t, private_encrypted_fragment_payload_t *this)
METHOD (payload_t, frag_get_encoding_rules, int, private_encrypted_fragment_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, frag_get_header_length, int, private_encrypted_fragment_payload_t *this)
METHOD (payload_t, frag_get_type, payload_type_t, private_encrypted_fragment_payload_t *this)
METHOD (payload_t, frag_get_next_type, payload_type_t, private_encrypted_fragment_payload_t *this)
METHOD (payload_t, frag_set_next_type, void, private_encrypted_fragment_payload_t *this, payload_type_t type)
METHOD2 (payload_t, encrypted_payload_t, frag_get_length, size_t, private_encrypted_fragment_payload_t *this)
METHOD (encrypted_fragment_payload_t, get_fragment_number, u_int16_t, private_encrypted_fragment_payload_t *this)
METHOD (encrypted_fragment_payload_t, get_total_fragments, u_int16_t, private_encrypted_fragment_payload_t *this)
METHOD (encrypted_fragment_payload_t, frag_get_content, chunk_t, private_encrypted_fragment_payload_t *this)
METHOD (encrypted_payload_t, frag_add_payload, void, private_encrypted_fragment_payload_t *this, payload_t *payload)
METHOD (encrypted_payload_t, frag_set_transform, void, private_encrypted_fragment_payload_t *this, aead_t *aead)
static chunk_t append_header_frag (private_encrypted_fragment_payload_t *this, chunk_t assoc)
METHOD (encrypted_payload_t, frag_encrypt, status_t, private_encrypted_fragment_payload_t *this, u_int64_t mid, chunk_t assoc)
METHOD (encrypted_payload_t, frag_decrypt, status_t, private_encrypted_fragment_payload_t *this, chunk_t assoc)
METHOD2 (payload_t, encrypted_payload_t, frag_destroy, void, private_encrypted_fragment_payload_t *this)
encrypted_fragment_payload_t * encrypted_fragment_payload_create ()
encrypted_fragment_payload_t * encrypted_fragment_payload_create_from_data (u_int16_t num, u_int16_t total, chunk_t plain)
Variables
static encoding_rule_t encodings_v2 []
static encoding_rule_t encodings_v1 []
static encoding_rule_t encodings_fragment []
Typedef Documentation
typedef struct private_encrypted_fragment_payload_t private_encrypted_fragment_payload_t
Definition at line 31 of file encrypted_payload.c.
typedef struct private_encrypted_payload_t private_encrypted_payload_t
Definition at line 30 of file encrypted_payload.c.
Function Documentation
static chunk_t append_header (private_encrypted_payload_t * this, chunk_t assoc) static
Append the encrypted payload header to the associated data
Definition at line 402 of file encrypted_payload.c.
References __attribute__, chunk_cat, chunk_from_thing, flags, get_length(), and length.
Referenced by METHOD().
 {
     struct {
         u_int8_t next_payload;
         u_int8_t flags;
         u_int16_t length;
     } __attribute__((packed)) header = {
         .next_payload = this->next_payload,
         .flags = this->flags,
         .length = htons(get_length(this)),
     };
     return chunk_cat("cc", assoc, chunk_from_thing(header));
 }
static chunk_t append_header_frag (private_encrypted_fragment_payload_t * this, chunk_t assoc) static
Append the encrypted fragment payload header to the associated data
Definition at line 905 of file encrypted_payload.c.
References __attribute__, chunk_cat, chunk_from_thing, flags, and length.
Referenced by METHOD().
 {
     struct {
         u_int8_t next_payload;
         u_int8_t flags;
         u_int16_t length;
         u_int16_t fragment_number;
         u_int16_t total_fragments;
     } __attribute__((packed)) header = {
         .next_payload = this->next_payload,
         .flags = this->flags,
         .length = htons(frag_get_length(this)),
         .fragment_number = htons(this->fragment_number),
         .total_fragments = htons(this->total_fragments),
     };
     return chunk_cat("cc", assoc, chunk_from_thing(header));
 }
static void compute_length (private_encrypted_payload_t * this) static
Compute the length of the whole payload
Definition at line 294 of file encrypted_payload.c.
References aead, compute_overhead(), enumerator_t::destroy, enumerator_t::enumerate, payload_t::get_length, and length.
Referenced by encrypted_payload_create_from_plain(), METHOD(), and METHOD2().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     size_t length = 0;
     if (this->encrypted.len)
     {
         length = this->encrypted.len;
     }
     else
     {
         enumerator = this->payloads->create_enumerator(this->payloads);
         while (enumerator->enumerate(enumerator, &payload))
         {
             length += payload->get_length(payload);
         }
         enumerator->destroy(enumerator);
         if (this->aead)
         {
             length += compute_overhead(this->aead, length);
         }
     }
     length += get_header_length(this);
     this->payload_length = length;
 }
static size_t compute_overhead (aead_t * aead, size_t len) static
Get length of encryption/integrity overhead for the given plaintext length
Definition at line 277 of file encrypted_payload.c.
References aead_t::get_block_size, aead_t::get_icv_size, and aead_t::get_iv_size.
Referenced by compute_length(), and METHOD2().
 {
     size_t bs, overhead;
     /* padding */
     bs = aead->get_block_size(aead);
     overhead = bs - (len % bs);
     /* add iv */
     overhead += aead->get_iv_size(aead);
     /* add icv */
     overhead += aead->get_icv_size(aead);
     return overhead;
 }
static status_t decrypt_content (char * label, aead_t * aead, chunk_t encrypted, chunk_t assoc, chunk_t * plain) static
Decrypts the given data in-place and returns a chunk pointing to the resulting plaintext.
Definition at line 604 of file encrypted_payload.c.
References chunk_create(), crypt(), DBG1, DBG3, DBG_ENC, aead_t::decrypt, FAILED, aead_t::get_block_size, aead_t::get_icv_size, aead_t::get_iv_size, chunk_t::len, padding, PARSE_ERROR, chunk_t::ptr, and SUCCESS.
Referenced by METHOD().
 {
     chunk_t iv, padding, icv, crypt;
     size_t bs;
     /* prepare data to authenticate-decrypt:
      * | IV | plain | padding | ICV |
      *       \____crypt______/   ^
      *              |           /
      *              v          /
      *     assoc -> + ------->/
      */
     bs = aead->get_block_size(aead);
     iv.len = aead->get_iv_size(aead);
     iv.ptr = encrypted.ptr;
     icv.len = aead->get_icv_size(aead);
     icv.ptr = encrypted.ptr + encrypted.len - icv.len;
     crypt.ptr = iv.ptr + iv.len;
     crypt.len = encrypted.len - iv.len;
     if (iv.len + icv.len > encrypted.len ||
         (crypt.len - icv.len) % bs)
     {
         DBG1(DBG_ENC, "decrypting %s payload failed, invalid length", label);
         return FAILED;
     }
     DBG3(DBG_ENC, "%s decryption:", label);
     DBG3(DBG_ENC, "IV %B", &iv);
     DBG3(DBG_ENC, "encrypted %B", &crypt);
     DBG3(DBG_ENC, "ICV %B", &icv);
     DBG3(DBG_ENC, "assoc %B", &assoc);
     if (!aead->decrypt(aead, crypt, assoc, iv, NULL))
     {
         DBG1(DBG_ENC, "verifying %s integrity failed", label);
         return FAILED;
     }
     *plain = chunk_create(crypt.ptr, crypt.len - icv.len);
     padding.len = plain->ptr[plain->len - 1] + 1;
     if (padding.len > plain->len)
     {
         DBG1(DBG_ENC, "decrypting %s failed, padding invalid %B", label,
              &crypt);
         return PARSE_ERROR;
     }
     plain->len -= padding.len;
     padding.ptr = plain->ptr + plain->len;
     DBG3(DBG_ENC, "plain %B", plain);
     DBG3(DBG_ENC, "padding %B", &padding);
     return SUCCESS;
 }
static status_t encrypt_content (char * label, aead_t * aead, u_int64_t mid, chunk_t plain, chunk_t assoc, chunk_t * encrypted) static
Encrypts the data in plain and returns it in an allocated chunk.
Definition at line 419 of file encrypted_payload.c.
References chunk_alloc, chunk_create(), crypto_factory_t::create_rng, crypt(), library_t::crypto, DBG1, DBG3, DBG_ENC, rng_t::destroy, aead_t::encrypt, FAILED, aead_t::get_block_size, rng_t::get_bytes, aead_t::get_icv_size, iv_gen_t::get_iv, aead_t::get_iv_gen, aead_t::get_iv_size, chunk_t::len, lib, memcpy, NOT_SUPPORTED, padding, chunk_t::ptr, rng, RNG_WEAK, and SUCCESS.
Referenced by METHOD().
 {
     chunk_t iv, padding, icv, crypt;
     iv_gen_t *iv_gen;
     rng_t *rng;
     size_t bs;
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng)
     {
         DBG1(DBG_ENC, "encrypting %s failed, no RNG found", label);
         return NOT_SUPPORTED;
     }
     iv_gen = aead->get_iv_gen(aead);
     if (!iv_gen)
     {
         DBG1(DBG_ENC, "encrypting %s failed, no IV generator", label);
         return NOT_SUPPORTED;
     }
     bs = aead->get_block_size(aead);
     /* we need at least one byte padding to store the padding length */
     padding.len = bs - (plain.len % bs);
     iv.len = aead->get_iv_size(aead);
     icv.len = aead->get_icv_size(aead);
     /* prepare data to authenticate-encrypt:
      * | IV | plain | padding | ICV |
      *       \____crypt______/   ^
      *              |           /
      *              v          /
      *     assoc -> + ------->/
      */
     *encrypted = chunk_alloc(iv.len + plain.len + padding.len + icv.len);
     iv.ptr = encrypted->ptr;
     memcpy(iv.ptr + iv.len, plain.ptr, plain.len);
     plain.ptr = iv.ptr + iv.len;
     padding.ptr = plain.ptr + plain.len;
     icv.ptr = padding.ptr + padding.len;
     crypt = chunk_create(plain.ptr, plain.len + padding.len);
     if (!iv_gen->get_iv(iv_gen, mid, iv.len, iv.ptr) ||
         !rng->get_bytes(rng, padding.len - 1, padding.ptr))
     {
         DBG1(DBG_ENC, "encrypting %s failed, no IV or padding", label);
         rng->destroy(rng);
         return FAILED;
     }
     padding.ptr[padding.len - 1] = padding.len - 1;
     rng->destroy(rng);
     DBG3(DBG_ENC, "%s encryption:", label);
     DBG3(DBG_ENC, "IV %B", &iv);
     DBG3(DBG_ENC, "plain %B", &plain);
     DBG3(DBG_ENC, "padding %B", &padding);
     DBG3(DBG_ENC, "assoc %B", &assoc);
     if (!aead->encrypt(aead, crypt, assoc, iv, NULL))
     {
         return FAILED;
     }
     DBG3(DBG_ENC, "encrypted %B", &crypt);
     DBG3(DBG_ENC, "ICV %B", &icv);
     return SUCCESS;
 }
static chunk_t generate (private_encrypted_payload_t * this, generator_t * generator) static
Generate payload before encryption
Definition at line 364 of file encrypted_payload.c.
References chunk_empty, DBG2, DBG_ENC, enumerator_t::destroy, enumerator_t::enumerate, generator_t::generate_payload, generator_t::get_chunk, payload_t::get_type, next, PL_NONE, and payload_t::set_next_type.
Referenced by METHOD().
 {
     payload_t *current, *next;
     enumerator_t *enumerator;
     u_int32_t *lenpos;
     chunk_t chunk = chunk_empty;
     enumerator = this->payloads->create_enumerator(this->payloads);
     if (enumerator->enumerate(enumerator, &current))
     {
         this->next_payload = current->get_type(current);
         while (enumerator->enumerate(enumerator, &next))
         {
             current->set_next_type(current, next->get_type(next));
             generator->generate_payload(generator, current);
             current = next;
         }
         current->set_next_type(current, PL_NONE);
         generator->generate_payload(generator, current);
         chunk = generator->get_chunk(generator, &lenpos);
         DBG2(DBG_ENC, "generated content in encrypted payload");
     }
     enumerator->destroy(enumerator);
     return chunk;
 }
METHOD (payload_t , verify , status_t , private_encrypted_payload_t * this)
Definition at line 227 of file encrypted_payload.c.
References SUCCESS.
 {
     return SUCCESS;
 }
METHOD (payload_t , get_encoding_rules , int , private_encrypted_payload_t * this, encoding_rule_t ** rules)
Definition at line 233 of file encrypted_payload.c.
References countof, encodings_v1, encodings_v2, PLV2_ENCRYPTED, and type.
 {
     if (this->type == PLV2_ENCRYPTED)
     {
         *rules = encodings_v2;
         return countof(encodings_v2);
     }
     *rules = encodings_v1;
     return countof(encodings_v1);
 }
METHOD (payload_t , get_header_length , int , private_encrypted_payload_t * this)
Definition at line 245 of file encrypted_payload.c.
References PLV2_ENCRYPTED, and type.
 {
     if (this->type == PLV2_ENCRYPTED)
     {
         return 4;
     }
     return 0;
 }
METHOD (payload_t , get_type , payload_type_t , private_encrypted_payload_t * this)
Definition at line 255 of file encrypted_payload.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_encrypted_payload_t * this)
Definition at line 261 of file encrypted_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_encrypted_payload_t * this, payload_type_t type)
Definition at line 267 of file encrypted_payload.c.
References type.
 {
     /* the next payload is set during add, still allow this for IKEv1 */
     this->next_payload = type;
 }
METHOD (encrypted_payload_t , add_payload , void , private_encrypted_payload_t * this, payload_t * payload)
Definition at line 329 of file encrypted_payload.c.
References compute_length(), payload_t::get_type, PL_NONE, and payload_t::set_next_type.
 {
     payload_t *last_payload;
     if (this->payloads->get_count(this->payloads) > 0)
     {
         this->payloads->get_last(this->payloads, (void **)&last_payload);
         last_payload->set_next_type(last_payload, payload->get_type(payload));
     }
     else
     {
         this->next_payload = payload->get_type(payload);
     }
     payload->set_next_type(payload, PL_NONE);
     this->payloads->insert_last(this->payloads, payload);
     compute_length(this);
 }
METHOD (encrypted_payload_t , remove_payload , payload_t * , private_encrypted_payload_t * this)
Definition at line 348 of file encrypted_payload.c.
References SUCCESS.
 {
     payload_t *payload;
     if (this->payloads->remove_first(this->payloads,
                                      (void**)&payload) == SUCCESS)
     {
         return payload;
     }
     return NULL;
 }
METHOD (encrypted_payload_t , generate_payloads , void , private_encrypted_payload_t * this, generator_t * generator)
Definition at line 393 of file encrypted_payload.c.
References generate().
 {
     generate(this, generator);
 }
METHOD (encrypted_payload_t , encrypt , status_t , private_encrypted_payload_t * this, u_int64_t mid, chunk_t assoc)
Definition at line 488 of file encrypted_payload.c.
References aead, append_header(), DBG1, DBG_ENC, generator_t::destroy, encrypt_content(), free(), generate(), generator_create(), INVALID_STATE, chunk_t::ptr, and status.
 {
     generator_t *generator;
     chunk_t plain;
     status_t status;
     if (this->aead == NULL)
     {
         DBG1(DBG_ENC, "encrypting encrypted payload failed, transform missing");
         return INVALID_STATE;
     }
     free(this->encrypted.ptr);
     generator = generator_create();
     plain = generate(this, generator);
     assoc = append_header(this, assoc);
     /* lower 32-bits are for fragment number, if used */
     mid <<= 32;
     status = encrypt_content("encrypted payload", this->aead, mid, plain, assoc,
                              &this->encrypted);
     generator->destroy(generator);
     free(assoc.ptr);
     return status;
 }
METHOD (encrypted_payload_t , encrypt_v1 , status_t , private_encrypted_payload_t * this, u_int64_t mid, chunk_t iv)
Definition at line 514 of file encrypted_payload.c.
References aead, chunk_alloc, chunk_empty, DBG1, DBG3, DBG_ENC, generator_t::destroy, aead_t::encrypt, FAILED, free(), generate(), generator_create(), aead_t::get_block_size, INVALID_STATE, chunk_t::len, memcpy, memset, padding, chunk_t::ptr, and SUCCESS.
 {
     generator_t *generator;
     chunk_t plain, padding;
     size_t bs;
     if (this->aead == NULL)
     {
         DBG1(DBG_ENC, "encryption failed, transform missing");
         return INVALID_STATE;
     }
     generator = generator_create();
     plain = generate(this, generator);
     bs = this->aead->get_block_size(this->aead);
     padding.len = bs - (plain.len % bs);
     /* prepare data to encrypt:
      * | plain | padding | */
     free(this->encrypted.ptr);
     this->encrypted = chunk_alloc(plain.len + padding.len);
     memcpy(this->encrypted.ptr, plain.ptr, plain.len);
     plain.ptr = this->encrypted.ptr;
     padding.ptr = plain.ptr + plain.len;
     memset(padding.ptr, 0, padding.len);
     generator->destroy(generator);
     DBG3(DBG_ENC, "encrypting payloads:");
     DBG3(DBG_ENC, "IV %B", &iv);
     DBG3(DBG_ENC, "plain %B", &plain);
     DBG3(DBG_ENC, "padding %B", &padding);
     if (!this->aead->encrypt(this->aead, this->encrypted, chunk_empty, iv, NULL))
     {
         return FAILED;
     }
     DBG3(DBG_ENC, "encrypted %B", &this->encrypted);
     return SUCCESS;
 }
METHOD (encrypted_payload_t , decrypt , status_t , private_encrypted_payload_t * this, chunk_t assoc)
Definition at line 660 of file encrypted_payload.c.
References aead, append_header(), DBG1, DBG_ENC, decrypt_content(), free(), INVALID_STATE, parse(), chunk_t::ptr, status, and SUCCESS.
 {
     chunk_t plain;
     status_t status;
     if (this->aead == NULL)
     {
         DBG1(DBG_ENC, "decrypting encrypted payload failed, transform missing");
         return INVALID_STATE;
     }
     assoc = append_header(this, assoc);
     status = decrypt_content("encrypted payload", this->aead, this->encrypted,
                              assoc, &plain);
     free(assoc.ptr);
     if (status != SUCCESS)
     {
         return status;
     }
     return parse(this, plain);
 }
METHOD (encrypted_payload_t , decrypt_plain , status_t , private_encrypted_payload_t * this, chunk_t assoc)
Definition at line 684 of file encrypted_payload.c.
References FAILED, and parse().
 {
     if (!this->encrypted.ptr)
     {
         return FAILED;
     }
     return parse(this, this->encrypted);
 }
METHOD (encrypted_payload_t , decrypt_v1 , status_t , private_encrypted_payload_t * this, chunk_t iv)
Definition at line 694 of file encrypted_payload.c.
References aead, chunk_empty, DBG1, DBG3, DBG_ENC, aead_t::decrypt, FAILED, INVALID_STATE, chunk_t::len, and parse().
 {
     if (this->aead == NULL)
     {
         DBG1(DBG_ENC, "decryption failed, transform missing");
         return INVALID_STATE;
     }
     /* data must be a multiple of block size */
     if (iv.len != this->aead->get_block_size(this->aead) ||
         this->encrypted.len < iv.len || this->encrypted.len % iv.len)
     {
         DBG1(DBG_ENC, "decryption failed, invalid length");
         return FAILED;
     }
     DBG3(DBG_ENC, "decrypting payloads:");
     DBG3(DBG_ENC, "encrypted %B", &this->encrypted);
     if (!this->aead->decrypt(this->aead, this->encrypted, chunk_empty, iv, NULL))
     {
         return FAILED;
     }
     DBG3(DBG_ENC, "plain %B", &this->encrypted);
     return parse(this, this->encrypted);
 }
METHOD (encrypted_payload_t , set_transform , void , private_encrypted_payload_t * this, aead_t * aead)
Definition at line 724 of file encrypted_payload.c.
References aead.
 {
     this->aead = aead;
 }
METHOD (payload_t , frag_verify , status_t , private_encrypted_fragment_payload_t * this)
Definition at line 798 of file encrypted_payload.c.
References DBG1, DBG_ENC, FAILED, and SUCCESS.
 {
     if (!this->fragment_number || !this->total_fragments ||
         this->fragment_number > this->total_fragments)
     {
         DBG1(DBG_ENC, "invalid fragment number (%u) or total fragments (%u)",
              this->fragment_number, this->total_fragments);
         return FAILED;
     }
     if (this->fragment_number > 1 && this->next_payload != 0)
     {
         DBG1(DBG_ENC, "invalid next payload (%u) for fragment %u, ignored",
              this->next_payload, this->fragment_number);
         this->next_payload = 0;
     }
     return SUCCESS;
 }
METHOD (payload_t , frag_get_encoding_rules , int , private_encrypted_fragment_payload_t * this, encoding_rule_t ** rules)
Definition at line 817 of file encrypted_payload.c.
References countof, and encodings_fragment.
 {
     *rules = encodings_fragment;
     return countof(encodings_fragment);
 }
METHOD (payload_t , frag_get_header_length , int , private_encrypted_fragment_payload_t * this)
Definition at line 824 of file encrypted_payload.c.
 {
     return 8;
 }
METHOD (payload_t , frag_get_type , payload_type_t , private_encrypted_fragment_payload_t * this)
Definition at line 830 of file encrypted_payload.c.
References PLV2_FRAGMENT.
 {
     return PLV2_FRAGMENT;
 }
METHOD (payload_t , frag_get_next_type , payload_type_t , private_encrypted_fragment_payload_t * this)
Definition at line 836 of file encrypted_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , frag_set_next_type , void , private_encrypted_fragment_payload_t * this, payload_type_t type)
Definition at line 842 of file encrypted_payload.c.
References PL_NONE, and type.
 {
     if (this->fragment_number == 1 && this->next_payload == PL_NONE)
     {
         this->next_payload = type;
     }
 }
METHOD (encrypted_fragment_payload_t , get_fragment_number , u_int16_t , private_encrypted_fragment_payload_t * this)
Definition at line 872 of file encrypted_payload.c.
 {
     return this->fragment_number;
 }
METHOD (encrypted_fragment_payload_t , get_total_fragments , u_int16_t , private_encrypted_fragment_payload_t * this)
Definition at line 878 of file encrypted_payload.c.
 {
     return this->total_fragments;
 }
METHOD (encrypted_fragment_payload_t , frag_get_content , chunk_t , private_encrypted_fragment_payload_t * this)
Definition at line 884 of file encrypted_payload.c.
 {
     return this->plain;
 }
METHOD (encrypted_payload_t , frag_add_payload , void , private_encrypted_fragment_payload_t * this, payload_t * payload)
Definition at line 890 of file encrypted_payload.c.
References payload_t::destroy.
 {
     payload->destroy(payload);
 }
METHOD (encrypted_payload_t , frag_set_transform , void , private_encrypted_fragment_payload_t * this, aead_t * aead)
Definition at line 896 of file encrypted_payload.c.
References aead.
 {
     this->aead = aead;
 }
METHOD (encrypted_payload_t , frag_encrypt , status_t , private_encrypted_fragment_payload_t * this, u_int64_t mid, chunk_t assoc)
Definition at line 924 of file encrypted_payload.c.
References aead, append_header_frag(), DBG1, DBG_ENC, encrypt_content(), free(), INVALID_STATE, chunk_t::ptr, and status.
 {
     status_t status;
     if (!this->aead)
     {
         DBG1(DBG_ENC, "encrypting encrypted fragment payload failed, "
              "transform missing");
         return INVALID_STATE;
     }
     free(this->encrypted.ptr);
     assoc = append_header_frag(this, assoc);
     /* IKEv2 message IDs are not unique if fragmentation is used, hence include
      * the fragment number to make it unique */
     mid = mid << 32 | this->fragment_number;
     status = encrypt_content("encrypted fragment payload", this->aead, mid,
                              this->plain, assoc, &this->encrypted);
     free(assoc.ptr);
     return status;
 }
METHOD (encrypted_payload_t , frag_decrypt , status_t , private_encrypted_fragment_payload_t * this, chunk_t assoc)
Definition at line 946 of file encrypted_payload.c.
References aead, append_header_frag(), chunk_clone, DBG1, DBG_ENC, decrypt_content(), free(), INVALID_STATE, chunk_t::ptr, and status.
 {
     status_t status;
     if (!this->aead)
     {
         DBG1(DBG_ENC, "decrypting encrypted fragment payload failed, "
              "transform missing");
         return INVALID_STATE;
     }
     free(this->plain.ptr);
     assoc = append_header_frag(this, assoc);
     status = decrypt_content("encrypted fragment payload", this->aead,
                              this->encrypted, assoc, &this->plain);
     this->plain = chunk_clone(this->plain);
     free(assoc.ptr);
     return status;
 }
METHOD2 (payload_t , encrypted_payload_t , get_length , size_t , private_encrypted_payload_t * this)
Definition at line 322 of file encrypted_payload.c.
References compute_length().
 {
     compute_length(this);
     return this->payload_length;
 }
METHOD2 (payload_t , encrypted_payload_t , destroy , void , private_encrypted_payload_t * this)
Definition at line 730 of file encrypted_payload.c.
References destroy(), and free().
 {
     this->payloads->destroy_offset(this->payloads, offsetof(payload_t, destroy));
     free(this->encrypted.ptr);
     free(this);
 }
METHOD2 (payload_t , encrypted_payload_t , frag_get_length , size_t , private_encrypted_fragment_payload_t * this)
Definition at line 851 of file encrypted_payload.c.
References aead, and compute_overhead().
 {
     if (this->encrypted.len)
     {
         this->payload_length = this->encrypted.len;
     }
     else
     {
         this->payload_length = this->plain.len;
         if (this->aead)
         {
             this->payload_length += compute_overhead(this->aead,
                                                      this->payload_length);
         }
     }
     this->payload_length += frag_get_header_length(this);
     return this->payload_length;
 }
METHOD2 (payload_t , encrypted_payload_t , frag_destroy , void , private_encrypted_fragment_payload_t * this)
Definition at line 966 of file encrypted_payload.c.
References free().
 {
     free(this->encrypted.ptr);
     free(this->plain.ptr);
     free(this);
 }
static status_t parse (private_encrypted_payload_t * this, chunk_t plain) static
Parse the payloads after decryption.
Definition at line 560 of file encrypted_payload.c.
References DBG1, DBG2, DBG_ENC, parser_t::destroy, payload_t::destroy, payload_t::get_next_type, payload_t::get_type, chunk_t::len, PARSE_ERROR, parser_t::parse_payload, parser, parser_create(), payload_type_names, PL_NONE, PLV1_ENCRYPTED, chunk_t::ptr, parser_t::set_major_version, SUCCESS, type, untoh16(), payload_t::verify, and VERIFY_ERROR.
Referenced by METHOD(), parse_rules(), and START_TEST().
 {
     parser_t *parser;
     payload_type_t type;
     parser = parser_create(plain);
     parser->set_major_version(parser, this->type == PLV1_ENCRYPTED ? 1 : 2);
     type = this->next_payload;
     while (type != PL_NONE)
     {
         payload_t *payload;
         if (plain.len < 4 || untoh16(plain.ptr + 2) > plain.len)
         {
             DBG1(DBG_ENC, "invalid %N payload length, decryption failed?",
                  payload_type_names, type);
             parser->destroy(parser);
             return PARSE_ERROR;
         }
         if (parser->parse_payload(parser, type, &payload) != SUCCESS)
         {
             parser->destroy(parser);
             return PARSE_ERROR;
         }
         if (payload->verify(payload) != SUCCESS)
         {
             DBG1(DBG_ENC, "%N verification failed",
                  payload_type_names, payload->get_type(payload));
             payload->destroy(payload);
             parser->destroy(parser);
             return VERIFY_ERROR;
         }
         type = payload->get_next_type(payload);
         this->payloads->insert_last(this->payloads, payload);
     }
     parser->destroy(parser);
     DBG2(DBG_ENC, "parsed content of encrypted payload");
     return SUCCESS;
 }
Variable Documentation
encoding_rule_t encodings_fragment[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_encrypted_fragment_payload_t, next_payload)    },
    { U_INT_8,          offsetof(private_encrypted_fragment_payload_t, flags)           },
    { PAYLOAD_LENGTH,   offsetof(private_encrypted_fragment_payload_t, payload_length)  },
    { U_INT_16,         offsetof(private_encrypted_fragment_payload_t, fragment_number) },
    { U_INT_16,         offsetof(private_encrypted_fragment_payload_t, total_fragments) },
    { CHUNK_DATA,       offsetof(private_encrypted_fragment_payload_t, encrypted)       },
}
Encoding rules to parse or generate an IKEv2-Encrypted Fragment Payload.
The defined offsets are the positions in a object of type private_encrypted_payload_t.
Definition at line 192 of file encrypted_payload.c.
Referenced by METHOD().
encoding_rule_t encodings_v1[] static
Initial value:
= {
    { ENCRYPTED_DATA,   offsetof(private_encrypted_payload_t, encrypted)        },
}
Encoding rules to parse or generate a complete encrypted IKEv1 message.
The defined offsets are the positions in a object of type private_encrypted_payload_t.
Definition at line 171 of file encrypted_payload.c.
Referenced by METHOD().
encoding_rule_t encodings_v2[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_encrypted_payload_t, next_payload) },
    { U_INT_8,          offsetof(private_encrypted_payload_t, flags)            },
    { PAYLOAD_LENGTH,   offsetof(private_encrypted_payload_t, payload_length)   },
    { CHUNK_DATA,       offsetof(private_encrypted_payload_t, encrypted)        },
}
Encoding rules to parse or generate a IKEv2-Encrypted Payload.
The defined offsets are the positions in a object of type private_encrypted_payload_t.
Definition at line 135 of file encrypted_payload.c.
Referenced by METHOD().