strongSwan: host.c File Reference
host.c File Reference
#include "host.h"
#include <utils/debug.h>
#include <library.h>
Classes
struct private_host_t
Macros
#define IPV4_LEN 4
#define IPV6_LEN 16
Typedefs
typedef struct private_host_t private_host_t
Functions
static void update_sa_len (private_host_t *this)
METHOD (host_t, get_sockaddr, sockaddr_t *, private_host_t *this)
METHOD (host_t, get_sockaddr_len, socklen_t *, private_host_t *this)
METHOD (host_t, is_anyaddr, bool, private_host_t *this)
int host_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
METHOD (host_t, get_address, chunk_t, private_host_t *this)
METHOD (host_t, get_family, int, private_host_t *this)
METHOD (host_t, get_port, u_int16_t, private_host_t *this)
METHOD (host_t, set_port, void, private_host_t *this, u_int16_t port)
METHOD (host_t, clone_, host_t *, private_host_t *this)
static bool ip_equals (private_host_t *this, private_host_t *other)
static bool equals (private_host_t *this, private_host_t *other)
METHOD (host_t, destroy, void, private_host_t *this)
static private_host_t * host_create_empty (void)
static host_t * host_create_any_port (int family, u_int16_t port)
host_t * host_create_from_string_and_family (char *string, int family, u_int16_t port)
host_t * host_create_from_string (char *string, u_int16_t port)
host_t * host_create_from_sockaddr (sockaddr_t *sockaddr)
host_t * host_create_from_dns (char *string, int af, u_int16_t port)
host_t * host_create_from_chunk (int family, chunk_t address, u_int16_t port)
bool host_create_from_range (char *string, host_t **from, host_t **to)
host_t * host_create_from_subnet (char *string, int *bits)
host_t * host_create_netmask (int family, int netbits)
host_t * host_create_any (int family)
Macro Definition Documentation
#define IPV4_LEN 4
Definition at line 24 of file host.c.
Referenced by host_create_from_chunk(), and METHOD().
#define IPV6_LEN 16
Definition at line 25 of file host.c.
Referenced by host_create_from_chunk(), and METHOD().
Typedef Documentation
typedef struct private_host_t private_host_t
Definition at line 27 of file host.c.
Function Documentation
static bool equals (private_host_t * this, private_host_t * other) static
Implements host_t.equals
Definition at line 279 of file host.c.
References private_host_t::address4, private_host_t::address6, FALSE, and ip_equals().
Referenced by host_create_empty().
 {
     if (!ip_equals(this, other))
     {
         return FALSE;
     }
     switch (this->address.sa_family)
     {
         case AF_INET:
         {
             return (this->address4.sin_port == other->address4.sin_port);
         }
         case AF_INET6:
         {
             return (this->address6.sin6_port == other->address6.sin6_port);
         }
         default:
             break;
     }
     return FALSE;
 }
static host_t* host_create_any_port (int family, u_int16_t port) static
Definition at line 337 of file host.c.
References host_create_any(), and set_port().
Referenced by host_create_from_string_and_family().
 {
     host_t *this;
     this = host_create_any(family);
     this->set_port(this, port);
     return this;
 }
static private_host_t* host_create_empty (void) static
Creates an empty host_t object
Definition at line 311 of file host.c.
References bool, equals(), INIT, and ip_equals().
Referenced by host_create_any(), host_create_from_chunk(), host_create_from_sockaddr(), and host_create_netmask().
 {
     private_host_t *this;
     INIT(this,
         .public = {
             .get_sockaddr = _get_sockaddr,
             .get_sockaddr_len = _get_sockaddr_len,
             .clone = _clone_,
             .get_family = _get_family,
             .get_address = _get_address,
             .get_port = _get_port,
             .set_port = _set_port,
             .ip_equals = (bool (*)(host_t *,host_t *))ip_equals,
             .equals = (bool (*)(host_t *,host_t *)) equals,
             .is_anyaddr = _is_anyaddr,
             .destroy = _destroy,
         },
     );
     return this;
 }
static bool ip_equals (private_host_t * this, private_host_t * other) static
Implements host_t.ip_equals
Definition at line 250 of file host.c.
References private_host_t::address, private_host_t::address4, private_host_t::address6, FALSE, and memeq().
Referenced by equals(), and host_create_empty().
 {
     if (this->address.sa_family != other->address.sa_family)
     {
         /* 0.0.0.0 and 0::0 are equal */
         return (is_anyaddr(this) && is_anyaddr(other));
     }
     switch (this->address.sa_family)
     {
         case AF_INET:
         {
             return memeq(&this->address4.sin_addr, &other->address4.sin_addr,
                          sizeof(this->address4.sin_addr));
         }
         case AF_INET6:
         {
             return memeq(&this->address6.sin6_addr, &other->address6.sin6_addr,
                          sizeof(this->address6.sin6_addr));
         }
         default:
             break;
     }
     return FALSE;
 }
METHOD (host_t , get_sockaddr , sockaddr_t * , private_host_t * this)
Definition at line 67 of file host.c.
 {
     return &(this->address);
 }
METHOD (host_t , get_sockaddr_len , socklen_t * , private_host_t * this)
Definition at line 73 of file host.c.
 {
     return &(this->socklen);
 }
METHOD (host_t , is_anyaddr , bool , private_host_t * this)
Definition at line 79 of file host.c.
References FALSE, IPV4_LEN, IPV6_LEN, and memeq().
 {
     static const u_int8_t zeroes[IPV6_LEN];
     switch (this->address.sa_family)
     {
         case AF_INET:
         {
             return memeq(zeroes, &(this->address4.sin_addr.s_addr), IPV4_LEN);
         }
         case AF_INET6:
         {
             return memeq(zeroes, &(this->address6.sin6_addr.s6_addr), IPV6_LEN);
         }
         default:
         {
             return FALSE;
         }
     }
 }
METHOD (host_t , get_address , chunk_t , private_host_t * this)
Definition at line 161 of file host.c.
References chunk_empty, IPV4_LEN, IPV6_LEN, chunk_t::len, and chunk_t::ptr.
 {
     chunk_t address = chunk_empty;
     switch (this->address.sa_family)
     {
         case AF_INET:
         {
             address.ptr = (char*)&(this->address4.sin_addr.s_addr);
             address.len = IPV4_LEN;
             return address;
         }
         case AF_INET6:
         {
             address.ptr = (char*)&(this->address6.sin6_addr.s6_addr);
             address.len = IPV6_LEN;
             return address;
         }
         default:
         {
             /* return empty chunk */
             return address;
         }
     }
 }
METHOD (host_t , get_family , int , private_host_t * this)
Definition at line 188 of file host.c.
 {
     return this->address.sa_family;
 }
METHOD (host_t , get_port , u_int16_t , private_host_t * this)
Definition at line 194 of file host.c.
 {
     switch (this->address.sa_family)
     {
         case AF_INET:
         {
             return ntohs(this->address4.sin_port);
         }
         case AF_INET6:
         {
             return ntohs(this->address6.sin6_port);
         }
         default:
         {
             return 0;
         }
     }
 }
METHOD (host_t , set_port , void , private_host_t * this, u_int16_t port)
Definition at line 214 of file host.c.
 {
     switch (this->address.sa_family)
     {
         case AF_INET:
         {
             this->address4.sin_port = htons(port);
             break;
         }
         case AF_INET6:
         {
             this->address6.sin6_port = htons(port);
             break;
         }
         default:
         {
             break;
         }
     }
 }
METHOD (host_t , clone_ , host_t * , private_host_t * this)
Definition at line 236 of file host.c.
References malloc_thing, and memcpy.
 {
     private_host_t *new;
     new = malloc_thing(private_host_t);
     memcpy(new, this, sizeof(private_host_t));
     return &new->public;
 }
METHOD (host_t , destroy , void , private_host_t * this)
Definition at line 302 of file host.c.
References free().
 {
     free(this);
 }
static void update_sa_len (private_host_t * this) inline static
Update the sockaddr internal sa_len option, if available
Definition at line 60 of file host.c.
Referenced by host_create_any(), host_create_from_chunk(), host_create_from_sockaddr(), and host_create_netmask().
 {
 #ifdef HAVE_STRUCT_SOCKADDR_SA_LEN
     this->address.sa_len = this->socklen;
 #endif /* HAVE_STRUCT_SOCKADDR_SA_LEN */
 }