strongSwan: spi generator
spi generator
tkm
Functions
bool tkm_spi_generator_register (plugin_t *plugin, plugin_feature_t *feature, bool reg, void *cb_data)
Detailed Description
Function Documentation
bool tkm_spi_generator_register (plugin_t * plugin, plugin_feature_t * feature, bool reg, void * cb_data)
Register the TKM SPI generator callback.
Returns
TRUE on success
Definition at line 53 of file tkm_spi_generator.c.
References charon, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_IKE, DESTROY_IF, FALSE, free(), settings_t::get_str, daemon_t::ike_sa_manager, INIT, lib, library_t::ns, PRIx64, get_spi_args_t::rng, rng, RNG_WEAK, ike_sa_manager_t::set_spi_cb, library_t::settings, settings_value_as_uint64(), and TRUE.
Referenced by main().
 {
     u_int64_t spi_mask, spi_label;
     char *spi_val;
     rng_t *rng;
     if (reg)
     {
         rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
         if (!rng)
         {
             return FALSE;
         }
         spi_val = lib->settings->get_str(lib->settings, "%s.spi_mask", NULL,
                                          lib->ns);
         spi_mask = settings_value_as_uint64(spi_val, 0);
         spi_val = lib->settings->get_str(lib->settings, "%s.spi_label", NULL,
                                          lib->ns);
         spi_label = settings_value_as_uint64(spi_val, 0);
         INIT(spi_args,
             .rng = rng,
             .spi_mask = spi_mask,
             .spi_label = spi_label,
         );
         charon->ike_sa_manager->set_spi_cb(charon->ike_sa_manager,
                 tkm_get_spi, spi_args);
         DBG1(DBG_IKE, "using SPI label 0x%.16"PRIx64" and mask 0x%.16"PRIx64,
              spi_label, spi_mask);
     }
     else
     {
         if (spi_args)
         {
             DESTROY_IF(spi_args->rng);
             free(spi_args);
         }
     }
     return TRUE;
 }