strongSwan: conf_parser_t Struct Reference
conf_parser_t Struct Reference
conf_parser
#include "conf_parser.h"
Public Attributes
bool(* parse)(conf_parser_t *this)
enumerator_t *(* get_sections)(conf_parser_t *this, conf_parser_section_t type)
dictionary_t *(* get_section)(conf_parser_t *this, conf_parser_section_t type, char *name)
bool(* add_section)(conf_parser_t *this, conf_parser_section_t type, char *name)
void(* add_setting)(conf_parser_t *this, char *key, char *value)
void(* destroy)(conf_parser_t *this)
Detailed Description
Parser for ipsec.conf
Definition at line 55 of file conf_parser.h.
Member Data Documentation
bool(* conf_parser_t::add_section)(conf_parser_t *this, conf_parser_section_t type, char *name)
Add a section while parsing.
Note
This method can only be called while parsing the config file.
Parameters
type type of section to add
name name of the section, if applicable (gets adopted)
Returns
TRUE if the section already existed (settings get added)
Definition at line 93 of file conf_parser.h.
Referenced by yyparse().
void(* conf_parser_t::add_setting)(conf_parser_t *this, char *key, char *value)
Add a key/value pair to the latest section.
Note
This method can only be called while parsing the config file.
Parameters
name key string (gets adopted)
value optional value string (gets adopted), if no value is specified the key is set empty
Definition at line 105 of file conf_parser.h.
Referenced by yyparse().
void(* conf_parser_t::destroy)(conf_parser_t *this)
Destroy a conf_parser_t instance.
Definition at line 111 of file conf_parser.h.
Referenced by confread_load(), message_create_defrag(), METHOD(), START_TEARDOWN(), and START_TEST().
dictionary_t*(* conf_parser_t::get_section)(conf_parser_t *this, conf_parser_section_t type, char *name)
Get the section with the given type and name.
Note
The name is ignored for the config setup section.
Returns
dictionary with settings
Definition at line 81 of file conf_parser.h.
Referenced by load_ca(), load_conn(), load_setup(), and START_TEST().
enumerator_t*(* conf_parser_t::get_sections)(conf_parser_t *this, conf_parser_section_t type)
Get the names of all sections of the given type.
Note
Returns an empty enumerator for the config setup section.
Returns
enumerator over char*
Definition at line 71 of file conf_parser.h.
Referenced by confread_load(), and START_TEST().
bool(* conf_parser_t::parse)(conf_parser_t *this)
Parse the config file.
Returns
TRUE if config file was parsed successfully
Definition at line 62 of file conf_parser.h.
Referenced by confread_load(), and START_TEST().
The documentation for this struct was generated from the following file:
conf_parser.h