strongSwan: tls_cache
tls_cache
libtls
Classes
struct tls_cache_t
Typedefs
typedef struct tls_cache_t tls_cache_t
Functions
tls_cache_t * tls_cache_create (u_int max_sessions, u_int max_age)
Detailed Description
Typedef Documentation
typedef struct tls_cache_t tls_cache_t
Definition at line 24 of file tls_cache.h.
Function Documentation
tls_cache_t* tls_cache_create (u_int max_sessions, u_int max_age)
Create a tls_cache instance.
Parameters
max_sessions maximum number of sessions to store
max_age maximum age of a session, in seconds
Returns
tls cache
See header
Definition at line 217 of file tls_cache.c.
References equals(), hash(), hashtable_create(), INIT, linked_list_create(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by main().
 {
     private_tls_cache_t *this;
     INIT(this,
         .public = {
             .create = _create_,
             .lookup = _lookup,
             .check = _check,
             .destroy = _destroy,
         },
         .table = hashtable_create((hashtable_hash_t)hash,
                                   (hashtable_equals_t)equals, 8),
         .list = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .max_sessions = max_sessions,
         .max_age = max_age,
     );
     return &this->public;
 }