strongSwan: pts_error
pts_error
pts
Macros
#define PTS_MIN_NONCE_LEN 17
#define PTS_MAX_NONCE_LEN 0xffff
Typedefs
typedef enum pts_error_code_t pts_error_code_t
Enumerations
enum pts_error_code_t {
TCG_PTS_RESERVED_ERROR = 0, TCG_PTS_HASH_ALG_NOT_SUPPORTED = 1, TCG_PTS_INVALID_PATH = 2, TCG_PTS_FILE_NOT_FOUND = 3,
TCG_PTS_REG_NOT_SUPPORTED = 4, TCG_PTS_REG_KEY_NOT_FOUND = 5, TCG_PTS_DH_GRPS_NOT_SUPPORTED = 6, TCG_PTS_BAD_NONCE_LENGTH = 7,
TCG_PTS_INVALID_NAME_FAM = 8, TCG_PTS_TPM_VERS_NOT_SUPPORTED = 9, TCG_PTS_INVALID_DELIMITER = 10, TCG_PTS_OPERATION_NOT_SUPPORTED = 11,
TCG_PTS_RM_ERROR = 12, TCG_PTS_UNABLE_LOCAL_VAL = 13, TCG_PTS_UNABLE_CUR_EVID = 14, TCG_PTS_UNABLE_DET_TTC = 15,
TCG_PTS_UNABLE_DET_PCR = 16
}
Functions
pa_tnc_attr_t * pts_hash_alg_error_create (pts_meas_algorithms_t algorithms)
pa_tnc_attr_t * pts_dh_group_error_create (pts_dh_group_t dh_groups)
pa_tnc_attr_t * pts_dh_nonce_error_create (int min_nonce_len, int max_nonce_len)
Variables
enum_name_t * pts_error_code_names
Detailed Description
Macro Definition Documentation
#define PTS_MAX_NONCE_LEN 0xffff
Definition at line 33 of file pts_error.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
#define PTS_MIN_NONCE_LEN 17
Definition at line 32 of file pts_error.h.
Referenced by imc_attestation_process(), and imv_attestation_process().
Typedef Documentation
typedef enum pts_error_code_t pts_error_code_t
Definition at line 24 of file pts_error.h.
Enumeration Type Documentation
enum pts_error_code_t
PTS Attestation Error Codes see section 3.14.2 of PTS Protocol: Binding to TNC IF-M Specification
Enumerator
TCG_PTS_RESERVED_ERROR
TCG_PTS_HASH_ALG_NOT_SUPPORTED
TCG_PTS_INVALID_PATH
TCG_PTS_FILE_NOT_FOUND
TCG_PTS_REG_NOT_SUPPORTED
TCG_PTS_REG_KEY_NOT_FOUND
TCG_PTS_DH_GRPS_NOT_SUPPORTED
TCG_PTS_BAD_NONCE_LENGTH
TCG_PTS_INVALID_NAME_FAM
TCG_PTS_TPM_VERS_NOT_SUPPORTED
TCG_PTS_INVALID_DELIMITER
TCG_PTS_OPERATION_NOT_SUPPORTED
TCG_PTS_RM_ERROR
TCG_PTS_UNABLE_LOCAL_VAL
TCG_PTS_UNABLE_CUR_EVID
TCG_PTS_UNABLE_DET_TTC
TCG_PTS_UNABLE_DET_PCR
Definition at line 39 of file pts_error.h.
                       {
     TCG_PTS_RESERVED_ERROR =           0,
     TCG_PTS_HASH_ALG_NOT_SUPPORTED =   1,
     TCG_PTS_INVALID_PATH =             2,
     TCG_PTS_FILE_NOT_FOUND =           3,
     TCG_PTS_REG_NOT_SUPPORTED =        4,
     TCG_PTS_REG_KEY_NOT_FOUND =        5,
     TCG_PTS_DH_GRPS_NOT_SUPPORTED =    6,
     TCG_PTS_BAD_NONCE_LENGTH =         7,
     TCG_PTS_INVALID_NAME_FAM =         8,
     TCG_PTS_TPM_VERS_NOT_SUPPORTED =   9,
     TCG_PTS_INVALID_DELIMITER =       10,
     TCG_PTS_OPERATION_NOT_SUPPORTED = 11,
     TCG_PTS_RM_ERROR =                12,
     TCG_PTS_UNABLE_LOCAL_VAL =        13,
     TCG_PTS_UNABLE_CUR_EVID =         14,
     TCG_PTS_UNABLE_DET_TTC =          15,
     TCG_PTS_UNABLE_DET_PCR =          16,
 };
Function Documentation
pa_tnc_attr_t* pts_dh_group_error_create (pts_dh_group_t dh_groups)
Creates a PTS DH Group Not Supported Error Attribute see section 4.2.4 of PTS Protocol: Binding to TNC IF-M Specification
Parameters
dh_groups supported DH groups
Described in header.
Definition at line 64 of file pts_error.c.
References bio_writer_create(), bio_writer_t::destroy, error_code, bio_writer_t::get_buf, ietf_attr_pa_tnc_error_create(), PEN_TCG, TCG_PTS_DH_GRPS_NOT_SUPPORTED, and bio_writer_t::write_uint16.
Referenced by imc_attestation_process().
 {
     bio_writer_t *writer;
     chunk_t msg_info;
     pa_tnc_attr_t *attr;
     pen_type_t error_code = { PEN_TCG, TCG_PTS_DH_GRPS_NOT_SUPPORTED };
     writer = bio_writer_create(4);
     writer->write_uint16(writer, 0x0000);
     writer->write_uint16(writer, dh_groups);
     msg_info = writer->get_buf(writer);
     attr = ietf_attr_pa_tnc_error_create(error_code, msg_info);
     writer->destroy(writer);
     return attr;
 }
pa_tnc_attr_t* pts_dh_nonce_error_create (int min_nonce_len, int max_nonce_len)
Creates a PTS DH PN Nonce Not Supported Error Attribute see section 4.2.5 of PTS Protocol: Binding to TNC IF-M Specification
Parameters
min_nonce_len minimum nonce length
max_nonce_len maximum nonce length
Described in header.
Definition at line 84 of file pts_error.c.
References bio_writer_create(), bio_writer_t::destroy, error_code, bio_writer_t::get_buf, ietf_attr_pa_tnc_error_create(), PEN_TCG, TCG_PTS_BAD_NONCE_LENGTH, and bio_writer_t::write_uint16.
Referenced by imc_attestation_process(), and imv_attestation_process().
 {
     bio_writer_t *writer;
     chunk_t msg_info;
     pa_tnc_attr_t *attr;
     pen_type_t error_code = { PEN_TCG, TCG_PTS_BAD_NONCE_LENGTH };
     writer = bio_writer_create(4);
     writer->write_uint16(writer, min_nonce_len);
     writer->write_uint16(writer, max_nonce_len);
     msg_info = writer->get_buf(writer);
     attr = ietf_attr_pa_tnc_error_create(error_code, msg_info);
     writer->destroy(writer);
     return attr;
 }
pa_tnc_attr_t* pts_hash_alg_error_create (pts_meas_algorithms_t algorithms)
Creates a PTS Hash Algorithm Not Supported Error Attribute see section 4.2.2 of PTS Protocol: Binding to TNC IF-M Specification
Parameters
algorithms supported measurement hash algorithms
Described in header.
Definition at line 44 of file pts_error.c.
References bio_writer_create(), bio_writer_t::destroy, error_code, bio_writer_t::get_buf, ietf_attr_pa_tnc_error_create(), PEN_TCG, TCG_PTS_HASH_ALG_NOT_SUPPORTED, and bio_writer_t::write_uint16.
Referenced by imc_attestation_process(), and imv_attestation_process().
 {
     bio_writer_t *writer;
     chunk_t msg_info;
     pa_tnc_attr_t *attr;
     pen_type_t error_code = { PEN_TCG, TCG_PTS_HASH_ALG_NOT_SUPPORTED };
     writer = bio_writer_create(4);
     writer->write_uint16(writer, 0x0000);
     writer->write_uint16(writer, algorithms);
     msg_info = writer->get_buf(writer);
     attr = ietf_attr_pa_tnc_error_create(error_code, msg_info);
     writer->destroy(writer);
     return attr;
 }
Variable Documentation
enum_name_t* pts_error_code_names
enum name for pts_error_code_t.
Referenced by receive_message(), and receive_msg().