strongSwan: aggressive_mode
aggressive_mode
tasks
Classes
struct aggressive_mode_t
Typedefs
typedef struct aggressive_mode_t aggressive_mode_t
Functions
aggressive_mode_t * aggressive_mode_create (ike_sa_t *ike_sa, bool initiator)
Detailed Description
Typedef Documentation
typedef struct aggressive_mode_t aggressive_mode_t
Definition at line 24 of file aggressive_mode.h.
Function Documentation
aggressive_mode_t* aggressive_mode_create (ike_sa_t * ike_sa, bool initiator)
Create a new AGGRESSIVE_MODE task.
Parameters
ike_sa IKE_SA this task works for
initiator TRUE if task initiated locally
Returns
task to handle by the task_manager
Definition at line 746 of file aggressive_mode.c.
References INIT, initiator, and phase1_create().
Referenced by METHOD(), and process_request().
 {
     private_aggressive_mode_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .ph1 = phase1_create(ike_sa, initiator),
         .initiator = initiator,
         .state = AM_INIT,
     );
     if (initiator)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
     }
     return &this->public;
 }