strongSwan: attr_sql_plugin.c File Reference
attr_sql_plugin.c File Reference
#include <daemon.h>
#include <utils/debug.h>
#include <plugins/plugin_feature.h>
#include "attr_sql_plugin.h"
#include "attr_sql_provider.h"
Classes
struct private_attr_sql_plugin_t
Typedefs
typedef struct
private_attr_sql_plugin_t private_attr_sql_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_attr_sql_plugin_t *this)
static bool open_database (private_attr_sql_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_attr_sql_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_attr_sql_plugin_t *this)
plugin_t * attr_sql_plugin_create ()
Typedef Documentation
typedef struct private_attr_sql_plugin_t private_attr_sql_plugin_t
Definition at line 24 of file attr_sql_plugin.c.
Function Documentation
plugin_t* attr_sql_plugin_create ()
Definition at line 112 of file attr_sql_plugin.c.
References settings_t::add_fallback, INIT, lib, library_t::ns, and library_t::settings.
 {
     private_attr_sql_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     lib->settings->add_fallback(lib->settings, "%s.plugins.attr-sql",
                                 "libhydra.plugins.attr-sql", lib->ns);
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_attr_sql_plugin_t * this)
Definition at line 47 of file attr_sql_plugin.c.
 {
     return "attr-sql";
 }
METHOD (plugin_t , get_features , int , private_attr_sql_plugin_t * this, plugin_feature_t * features[])
Definition at line 91 of file attr_sql_plugin.c.
References countof, DB_ANY, open_database(), PLUGIN_CALLBACK, PLUGIN_DEPENDS, and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)open_database, NULL),
             PLUGIN_PROVIDE(CUSTOM, "attr-sql"),
                 PLUGIN_DEPENDS(DATABASE, DB_ANY),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_attr_sql_plugin_t * this)
Definition at line 103 of file attr_sql_plugin.c.
References free().
 {
     free(this);
 }
static bool open_database (private_attr_sql_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Connect to database
Definition at line 56 of file attr_sql_plugin.c.
References attribute_manager_t::add_provider, attr_sql_provider_create(), daemon_t::attributes, charon, database_factory_t::create, db, library_t::db, DBG1, DBG_CFG, database_t::destroy, FALSE, settings_t::get_str, lib, library_t::ns, attribute_manager_t::remove_provider, library_t::settings, TRUE, and uri.
Referenced by METHOD().
 {
     if (reg)
     {
         char *uri;
         uri = lib->settings->get_str(lib->settings,
                                 "%s.plugins.attr-sql.database", NULL, lib->ns);
         if (!uri)
         {
             DBG1(DBG_CFG, "attr-sql plugin: database URI not set");
             return FALSE;
         }
         this->db = lib->db->create(lib->db, uri);
         if (!this->db)
         {
             DBG1(DBG_CFG, "attr-sql plugin failed to connect to database");
             return FALSE;
         }
         this->attribute = attr_sql_provider_create(this->db);
         charon->attributes->add_provider(charon->attributes,
                                          &this->attribute->provider);
     }
     else
     {
         charon->attributes->remove_provider(charon->attributes,
                                             &this->attribute->provider);
         this->attribute->destroy(this->attribute);
         this->db->destroy(this->db);
     }
     return TRUE;
 }