strongSwan: tnccs_t Struct Reference
tnccs_t Struct Reference
tnccs
#include "tnccs.h"
Public Attributes
tls_t tls
host_t *(* get_server_ip)(tnccs_t *this)
host_t *(* get_peer_ip)(tnccs_t *this)
tnc_ift_type_t(* get_transport)(tnccs_t *this)
void(* set_transport)(tnccs_t *this, tnc_ift_type_t transport)
u_int32_t(* get_auth_type)(tnccs_t *this)
void(* set_auth_type)(tnccs_t *this, u_int32_t auth_type)
chunk_t(* get_pdp_server)(tnccs_t *this, u_int16_t *port)
tnccs_t *(* get_ref)(tnccs_t *this)
Detailed Description
TNCCS public interface
Definition at line 82 of file tnccs.h.
Member Data Documentation
u_int32_t(* tnccs_t::get_auth_type)(tnccs_t *this)
Get type of TNC Client authentication
Returns
TNC Client authentication type
Definition at line 122 of file tnccs.h.
Referenced by METHOD().
chunk_t(* tnccs_t::get_pdp_server)(tnccs_t *this, u_int16_t *port)
Get PDP server name and port number
Parameters
port PDP port number
Returns
PDP server name
Definition at line 137 of file tnccs.h.
Referenced by METHOD().
host_t*(* tnccs_t::get_peer_ip)(tnccs_t *this)
Get peer IP address
Returns
Peer IP address
Definition at line 101 of file tnccs.h.
Referenced by METHOD().
tnccs_t*(* tnccs_t::get_ref)(tnccs_t *this)
Get a new reference to the TNCCS object.
Returns
this, with an increased refcount
Definition at line 144 of file tnccs.h.
Referenced by eap_tnc_create().
host_t*(* tnccs_t::get_server_ip)(tnccs_t *this)
Get server IP address
Returns
Server IP address
Definition at line 94 of file tnccs.h.
Referenced by METHOD().
tnc_ift_type_t(* tnccs_t::get_transport)(tnccs_t *this)
Get underlying TNC IF-T transport protocol
Returns
TNC IF-T transport protocol
Definition at line 108 of file tnccs.h.
Referenced by METHOD().
void(* tnccs_t::set_auth_type)(tnccs_t *this, u_int32_t auth_type)
Set type of TNC Client authentication
Parameters
auth_type TNC Client authentication type
Definition at line 129 of file tnccs.h.
Referenced by do_sasl(), eap_tnc_create(), METHOD(), and process_sasl().
void(* tnccs_t::set_transport)(tnccs_t *this, tnc_ift_type_t transport)
Set underlying TNC IF-T transport protocol
Parameters
transport TNC IF-T transport protocol
Definition at line 115 of file tnccs.h.
tls_t tnccs_t::tls
Implements tls_t
Definition at line 87 of file tnccs.h.
Referenced by eap_tnc_create(), and METHOD().
The documentation for this struct was generated from the following file:
tnccs.h