strongSwan: sshkey_encoder
sshkey_encoder
sshkey
Functions
bool sshkey_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Detailed Description
Function Documentation
bool sshkey_encoder_encode (cred_encoding_type_t type, chunk_t * encoding, va_list args)
Encoding of public keys to RFC 4253 format.
Definition at line 115 of file sshkey_encoder.c.
References build_public_key(), FALSE, and PUBKEY_SSHKEY.
Referenced by METHOD(), and sshkey_plugin_create().
 {
     switch (type)
     {
         case PUBKEY_SSHKEY:
             return build_public_key(encoding, args);
         default:
             return FALSE;
     }
 }