strongSwan: pkcs11_private_key.c File Reference
pkcs11_private_key.c File Reference
#include "pkcs11_private_key.h"
#include "pkcs11_library.h"
#include "pkcs11_manager.h"
#include "pkcs11_public_key.h"
#include <utils/debug.h>
#include <asn1/asn1.h>
Classes
struct private_pkcs11_private_key_t
Typedefs
typedef struct
private_pkcs11_private_key_t private_pkcs11_private_key_t
Functions
METHOD (private_key_t, get_type, key_type_t, private_pkcs11_private_key_t *this)
METHOD (private_key_t, get_keysize, int, private_pkcs11_private_key_t *this)
CK_MECHANISM_PTR pkcs11_signature_scheme_to_mech (signature_scheme_t scheme, key_type_t type, size_t keylen, hash_algorithm_t *hash)
CK_MECHANISM_PTR pkcs11_encryption_scheme_to_mech (encryption_scheme_t scheme)
static bool reauth (private_pkcs11_private_key_t *this, CK_SESSION_HANDLE session)
METHOD (private_key_t, sign, bool, private_pkcs11_private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
METHOD (private_key_t, decrypt, bool, private_pkcs11_private_key_t *this, encryption_scheme_t scheme, chunk_t crypt, chunk_t *plain)
METHOD (private_key_t, get_public_key, public_key_t *, private_pkcs11_private_key_t *this)
METHOD (private_key_t, get_fingerprint, bool, private_pkcs11_private_key_t *this, cred_encoding_type_t type, chunk_t *fingerprint)
METHOD (private_key_t, get_encoding, bool, private_pkcs11_private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (private_key_t, get_ref, private_key_t *, private_pkcs11_private_key_t *this)
METHOD (private_key_t, destroy, void, private_pkcs11_private_key_t *this)
static pkcs11_library_t * find_lib (char *module)
static pkcs11_library_t * find_lib_by_keyid (chunk_t keyid, int *slot, CK_OBJECT_CLASS class)
static bool find_key (private_pkcs11_private_key_t *this, chunk_t keyid)
static bool login (private_pkcs11_private_key_t *this, int slot)
static public_key_t * find_pubkey_in_certs (private_pkcs11_private_key_t *this, chunk_t keyid)
pkcs11_private_key_t * pkcs11_private_key_connect (key_type_t type, va_list args)
Typedef Documentation
typedef struct private_pkcs11_private_key_t private_pkcs11_private_key_t
Definition at line 28 of file pkcs11_private_key.c.
Function Documentation
static bool find_key (private_pkcs11_private_key_t * this, chunk_t keyid) static
Find the key on the token
Definition at line 495 of file pkcs11_private_key.c.
References CKA_ALWAYS_AUTHENTICATE, CKA_CLASS, CKA_ID, CKA_KEY_TYPE, CKK_ECDSA, CKK_RSA, CKO_PRIVATE_KEY, count, countof, DBG1, DBG_CFG, FALSE, found, KEY_ECDSA, KEY_RSA, chunk_t::len, lib, PKCS11_ALWAYS_AUTH_KEYS, chunk_t::ptr, reauth(), TRUE, and type.
Referenced by pkcs11_private_key_connect().
 {
     CK_OBJECT_CLASS class = CKO_PRIVATE_KEY;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_ID, keyid.ptr, keyid.len},
     };
     CK_OBJECT_HANDLE object;
     CK_KEY_TYPE type;
     CK_BBOOL reauth = FALSE;
     CK_ATTRIBUTE attr[] = {
         {CKA_KEY_TYPE, &type, sizeof(type)},
         {CKA_ALWAYS_AUTHENTICATE, &reauth, sizeof(reauth)},
     };
     enumerator_t *enumerator;
     int count = countof(attr);
     bool found = FALSE;
     /* do not use CKA_ALWAYS_AUTHENTICATE if not supported */
     if (!(this->lib->get_features(this->lib) & PKCS11_ALWAYS_AUTH_KEYS))
     {
         count--;
     }
     enumerator = this->lib->create_object_enumerator(this->lib,
                             this->session, tmpl, countof(tmpl), attr, count);
     if (enumerator->enumerate(enumerator, &object))
     {
         this->type = KEY_RSA;
         switch (type)
         {
             case CKK_ECDSA:
                 this->type = KEY_ECDSA;
                 /* fall-through */
             case CKK_RSA:
                 this->reauth = reauth;
                 this->object = object;
                 found = TRUE;
                 break;
             default:
                 DBG1(DBG_CFG, "PKCS#11 key type %d not supported", type);
                 break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static pkcs11_library_t* find_lib (char * module) static
Find the PKCS#11 library by its friendly name
Definition at line 407 of file pkcs11_private_key.c.
References pkcs11_manager_t::create_token_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, library_t::get, pkcs11_library_t::get_name, lib, and streq().
Referenced by pkcs11_private_key_connect().
 {
     pkcs11_manager_t *manager;
     enumerator_t *enumerator;
     pkcs11_library_t *p11, *found = NULL;
     CK_SLOT_ID slot;
     manager = lib->get(lib, "pkcs11-manager");
     if (!manager)
     {
         return NULL;
     }
     enumerator = manager->create_token_enumerator(manager);
     while (enumerator->enumerate(enumerator, &p11, &slot))
     {
         if (streq(module, p11->get_name(p11)))
         {
             found = p11;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static pkcs11_library_t* find_lib_by_keyid (chunk_t keyid, int * slot, CK_OBJECT_CLASS class) static
Find the PKCS#11 lib having a keyid, and optionally a slot
Definition at line 435 of file pkcs11_private_key.c.
References ck_function_list::C_CloseSession, ck_function_list::C_OpenSession, ck_rv_names, CKA_CLASS, CKA_ID, CKF_SERIAL_SESSION, CKR_OK, countof, pkcs11_library_t::create_object_enumerator, pkcs11_manager_t::create_token_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, pkcs11_library_t::f, found, library_t::get, pkcs11_library_t::get_name, keys, chunk_t::len, lib, and chunk_t::ptr.
Referenced by pkcs11_private_key_connect().
 {
     pkcs11_manager_t *manager;
     enumerator_t *enumerator;
     pkcs11_library_t *p11, *found = NULL;
     CK_SLOT_ID current;
     manager = lib->get(lib, "pkcs11-manager");
     if (!manager)
     {
         return NULL;
     }
     enumerator = manager->create_token_enumerator(manager);
     while (enumerator->enumerate(enumerator, &p11, &current))
     {
         if (*slot == -1 || *slot == current)
         {
             /* look for a pubkey/cert, it is usually readable without login */
             CK_ATTRIBUTE tmpl[] = {
                 {CKA_CLASS, &class, sizeof(class)},
                 {CKA_ID, keyid.ptr, keyid.len},
             };
             CK_OBJECT_HANDLE object;
             CK_SESSION_HANDLE session;
             CK_RV rv;
             enumerator_t *keys;
             rv = p11->f->C_OpenSession(current, CKF_SERIAL_SESSION, NULL, NULL,
                                        &session);
             if (rv != CKR_OK)
             {
                 DBG1(DBG_CFG, "opening PKCS#11 session failed: %N",
                      ck_rv_names, rv);
                 continue;
             }
             keys = p11->create_object_enumerator(p11, session,
                                                  tmpl, countof(tmpl), NULL, 0);
             if (keys->enumerate(keys, &object))
             {
                 DBG1(DBG_CFG, "found key on PKCS#11 token '%s':%d",
                      p11->get_name(p11), current);
                 found = p11;
                 *slot = current;
             }
             keys->destroy(keys);
             p11->f->C_CloseSession(session);
             if (found)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static public_key_t* find_pubkey_in_certs (private_pkcs11_private_key_t * this, chunk_t keyid) static
Get a public key from a certificate with a given key ID.
Definition at line 594 of file pkcs11_private_key.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, chunk_clone, chunk_create(), chunk_empty, CKA_CERTIFICATE_TYPE, CKA_CLASS, CKA_ID, CKA_VALUE, CKC_X_509, CKO_CERTIFICATE, countof, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, data, enumerator_t::destroy, certificate_t::destroy, enumerator_t::enumerate, free(), certificate_t::get_public_key, key, chunk_t::len, lib, chunk_t::ptr, and type.
Referenced by pkcs11_private_key_connect().
 {
     CK_OBJECT_CLASS class = CKO_CERTIFICATE;
     CK_CERTIFICATE_TYPE type = CKC_X_509;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_CERTIFICATE_TYPE, &type, sizeof(type)},
         {CKA_ID, keyid.ptr, keyid.len},
     };
     CK_OBJECT_HANDLE object;
     CK_ATTRIBUTE attr[] = {
         {CKA_VALUE, NULL, 0},
     };
     enumerator_t *enumerator;
     chunk_t data = chunk_empty;
     public_key_t *key = NULL;
     certificate_t *cert;
     enumerator = this->lib->create_object_enumerator(this->lib, this->session,
                                     tmpl, countof(tmpl), attr, countof(attr));
     if (enumerator->enumerate(enumerator, &object))
     {
         data = chunk_clone(chunk_create(attr[0].pValue, attr[0].ulValueLen));
     }
     enumerator->destroy(enumerator);
     if (data.ptr)
     {
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_BLOB_ASN1_DER, data, BUILD_END);
         free(data.ptr);
         if (cert)
         {
             key = cert->get_public_key(cert);
             cert->destroy(cert);
         }
     }
     return key;
 }
static bool login (private_pkcs11_private_key_t * this, int slot) static
Find a PIN and try to log in
Definition at line 545 of file pkcs11_private_key.c.
References ck_rv_names, CKR_OK, CKS_RO_PUBLIC_SESSION, CKS_RW_PUBLIC_SESSION, CKU_USER, credential_manager_t::create_shared_enumerator, library_t::credmgr, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, shared_key_t::get_key, chunk_t::len, lib, chunk_t::ptr, SHARED_PIN, ck_session_info::state, and TRUE.
Referenced by pkcs11_private_key_connect().
 {
     enumerator_t *enumerator;
     shared_key_t *shared;
     chunk_t pin;
     CK_RV rv;
     CK_SESSION_INFO info;
     bool found = FALSE, success = FALSE;
     rv = this->lib->f->C_GetSessionInfo(this->session, &info);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_GetSessionInfo failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     if (info.state != CKS_RO_PUBLIC_SESSION &&
         info.state != CKS_RW_PUBLIC_SESSION)
     {   /* already logged in with another session, skip */
         return TRUE;
     }
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                                 SHARED_PIN, this->keyid, NULL);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         found = TRUE;
         pin = shared->get_key(shared);
         rv = this->lib->f->C_Login(this->session, CKU_USER, pin.ptr, pin.len);
         if (rv == CKR_OK)
         {
             success = TRUE;
             break;
         }
         DBG1(DBG_CFG, "login to '%s':%d failed: %N",
              this->lib->get_name(this->lib), slot, ck_rv_names, rv);
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         DBG1(DBG_CFG, "no PIN found for PKCS#11 key %Y", this->keyid);
         return FALSE;
     }
     return success;
 }
METHOD (private_key_t , get_type , key_type_t , private_pkcs11_private_key_t * this)
Definition at line 87 of file pkcs11_private_key.c.
References type.
 {
     return this->type;
 }
METHOD (private_key_t , get_keysize , int , private_pkcs11_private_key_t * this)
Definition at line 93 of file pkcs11_private_key.c.
 {
     return this->pubkey->get_keysize(this->pubkey);
 }
METHOD (private_key_t , sign , bool , private_pkcs11_private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * signature)
Definition at line 224 of file pkcs11_private_key.c.
References hasher_t::allocate_hash, asn1_integer(), ASN1_SEQUENCE, asn1_wrap(), chunk_create(), chunk_empty, chunk_free(), ck_rv_names, CKF_SERIAL_SESSION, CKR_OK, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_CFG, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, free(), hash, HASH_UNKNOWN, hasher, KEY_ECDSA, chunk_t::len, len, lib, malloc(), pkcs11_signature_scheme_to_mech(), chunk_t::ptr, reauth(), SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER, signature_scheme_names, TRUE, and type.
 {
     CK_MECHANISM_PTR mechanism;
     CK_SESSION_HANDLE session;
     CK_BYTE_PTR buf;
     CK_ULONG len;
     CK_RV rv;
     hash_algorithm_t hash_alg;
     chunk_t hash = chunk_empty;
     mechanism = pkcs11_signature_scheme_to_mech(scheme, this->type,
                                                 get_keysize(this), &hash_alg);
     if (!mechanism)
     {
         DBG1(DBG_LIB, "signature scheme %N not supported",
              signature_scheme_names, scheme);
         return FALSE;
     }
     rv = this->lib->f->C_OpenSession(this->slot, CKF_SERIAL_SESSION, NULL, NULL,
                                      &session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "opening PKCS#11 session failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     rv = this->lib->f->C_SignInit(session, mechanism, this->object);
     if (this->reauth && !reauth(this, session))
     {
         this->lib->f->C_CloseSession(session);
         return FALSE;
     }
     if (rv != CKR_OK)
     {
         this->lib->f->C_CloseSession(session);
         DBG1(DBG_LIB, "C_SignInit() failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     if (hash_alg != HASH_UNKNOWN)
     {
         hasher_t *hasher;
         hasher = lib->crypto->create_hasher(lib->crypto, hash_alg);
         if (!hasher || !hasher->allocate_hash(hasher, data, &hash))
         {
             DESTROY_IF(hasher);
             this->lib->f->C_CloseSession(session);
             return FALSE;
         }
         hasher->destroy(hasher);
         data = hash;
     }
     len = (get_keysize(this) + 7) / 8;
     if (this->type == KEY_ECDSA)
     {   /* signature is twice the length of the base point order */
         len *= 2;
     }
     buf = malloc(len);
     rv = this->lib->f->C_Sign(session, data.ptr, data.len, buf, &len);
     this->lib->f->C_CloseSession(session);
     chunk_free(&hash);
     if (rv != CKR_OK)
     {
         DBG1(DBG_LIB, "C_Sign() failed: %N", ck_rv_names, rv);
         free(buf);
         return FALSE;
     }
     switch (scheme)
     {
         case SIGN_ECDSA_WITH_SHA1_DER:
         case SIGN_ECDSA_WITH_SHA256_DER:
         case SIGN_ECDSA_WITH_SHA384_DER:
         case SIGN_ECDSA_WITH_SHA512_DER:
             /* return an ASN.1 encoded sequence of integers r and s */
             len /= 2;
             *signature = asn1_wrap(ASN1_SEQUENCE, "mm",
                                 asn1_integer("c", chunk_create(buf, len)),
                                 asn1_integer("c", chunk_create(buf+len, len)));
             free(buf);
             break;
         default:
             *signature = chunk_create(buf, len);
             break;
     }
     return TRUE;
 }
METHOD (private_key_t , decrypt , bool , private_pkcs11_private_key_t * this, encryption_scheme_t scheme, chunk_t crypt, chunk_t * plain)
Definition at line 312 of file pkcs11_private_key.c.
References chunk_create(), ck_rv_names, CKF_SERIAL_SESSION, CKR_OK, DBG1, DBG_CFG, DBG_LIB, encryption_scheme_names, FALSE, free(), chunk_t::len, len, lib, malloc(), pkcs11_encryption_scheme_to_mech(), chunk_t::ptr, reauth(), and TRUE.
 {
     CK_MECHANISM_PTR mechanism;
     CK_SESSION_HANDLE session;
     CK_BYTE_PTR buf;
     CK_ULONG len;
     CK_RV rv;
     mechanism = pkcs11_encryption_scheme_to_mech(scheme);
     if (!mechanism)
     {
         DBG1(DBG_LIB, "encryption scheme %N not supported",
              encryption_scheme_names, scheme);
         return FALSE;
     }
     rv = this->lib->f->C_OpenSession(this->slot, CKF_SERIAL_SESSION, NULL, NULL,
                                      &session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "opening PKCS#11 session failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     rv = this->lib->f->C_DecryptInit(session, mechanism, this->object);
     if (this->reauth && !reauth(this, session))
     {
         this->lib->f->C_CloseSession(session);
         return FALSE;
     }
     if (rv != CKR_OK)
     {
         this->lib->f->C_CloseSession(session);
         DBG1(DBG_LIB, "C_DecryptInit() failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     len = (get_keysize(this) + 7) / 8;
     buf = malloc(len);
     rv = this->lib->f->C_Decrypt(session, crypt.ptr, crypt.len, buf, &len);
     this->lib->f->C_CloseSession(session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_LIB, "C_Decrypt() failed: %N", ck_rv_names, rv);
         free(buf);
         return FALSE;
     }
     *plain = chunk_create(buf, len);
     return TRUE;
 }
METHOD (private_key_t , get_public_key , public_key_t * , private_pkcs11_private_key_t * this)
Definition at line 362 of file pkcs11_private_key.c.
 {
     return this->pubkey->get_ref(this->pubkey);
 }
METHOD (private_key_t , get_fingerprint , bool , private_pkcs11_private_key_t * this, cred_encoding_type_t type, chunk_t * fingerprint)
Definition at line 368 of file pkcs11_private_key.c.
 {
     return this->pubkey->get_fingerprint(this->pubkey, type, fingerprint);
 }
METHOD (private_key_t , get_encoding , bool , private_pkcs11_private_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 375 of file pkcs11_private_key.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (private_key_t , get_ref , private_key_t * , private_pkcs11_private_key_t * this)
Definition at line 382 of file pkcs11_private_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (private_key_t , destroy , void , private_pkcs11_private_key_t * this)
Definition at line 389 of file pkcs11_private_key.c.
References free(), keyid(), lib, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         if (this->pubkey)
         {
             this->pubkey->destroy(this->pubkey);
         }
         this->keyid->destroy(this->keyid);
         this->lib->f->C_CloseSession(this->session);
         free(this);
     }
 }
static bool reauth (private_pkcs11_private_key_t * this, CK_SESSION_HANDLE session) static
Reauthenticate to do a signature
Definition at line 190 of file pkcs11_private_key.c.
References ck_rv_names, CKR_OK, CKU_CONTEXT_SPECIFIC, credential_manager_t::create_shared_enumerator, library_t::credmgr, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, shared_key_t::get_key, chunk_t::len, lib, chunk_t::ptr, SHARED_PIN, and TRUE.
Referenced by build_peer_cfg(), check_systime(), eap_simaka_reauth_provider_create(), find_key(), log_ike_sa(), METHOD(), process_identity(), process_reauthentication(), process_start(), reauthenticate(), and rekey_ike_sa_job_create().
 {
     enumerator_t *enumerator;
     shared_key_t *shared;
     chunk_t pin;
     CK_RV rv;
     bool found = FALSE, success = FALSE;
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                                 SHARED_PIN, this->keyid, NULL);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         found = TRUE;
         pin = shared->get_key(shared);
         rv = this->lib->f->C_Login(session, CKU_CONTEXT_SPECIFIC,
                                    pin.ptr, pin.len);
         if (rv == CKR_OK)
         {
             success = TRUE;
             break;
         }
         DBG1(DBG_CFG, "reauthentication login failed: %N", ck_rv_names, rv);
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         DBG1(DBG_CFG, "private key requires reauthentication, but no PIN found");
         return FALSE;
     }
     return success;
 }