strongSwan: openssl_ec_public_key
openssl_ec_public_key
openssl
Classes
struct openssl_ec_public_key_t
Typedefs
typedef struct
openssl_ec_public_key_t openssl_ec_public_key_t
Functions
openssl_ec_public_key_t * openssl_ec_public_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct openssl_ec_public_key_t openssl_ec_public_key_t
Definition at line 24 of file openssl_ec_public_key.h.
Function Documentation
openssl_ec_public_key_t* openssl_ec_public_key_load (key_type_t type, va_list args)
Load a ECDSA public key using OpenSSL.
Accepts a BUILD_BLOB_ASN1_DER argument.
Parameters
type type of the key, must be KEY_ECDSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 309 of file openssl_ec_public_key.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, create_empty(), destroy(), KEY_ECDSA, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     private_openssl_ec_public_key_t *this;
     chunk_t blob = chunk_empty;
     if (type != KEY_ECDSA)
     {
         return NULL;
     }
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     this = create_empty();
     this->ec = d2i_EC_PUBKEY(NULL, (const u_char**)&blob.ptr, blob.len);
     if (!this->ec)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }