strongSwan: ntru_ke
ntru_ke
ntru
Classes
struct ntru_ke_t
Typedefs
typedef struct ntru_ke_t ntru_ke_t
Functions
ntru_ke_t * ntru_ke_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Detailed Description
Typedef Documentation
typedef struct ntru_ke_t ntru_ke_t
Definition at line 24 of file ntru_ke.h.
Function Documentation
ntru_ke_t* ntru_ke_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Creates a new ntru_ke_t object.
Parameters
group NTRU group number to use
g not used
p not used
Returns
ntru_ke_t object, NULL if not supported
Definition at line 243 of file ntru_ke.c.
References chunk_from_str, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_LIB, rng_t::destroy, drbg, settings_t::get_str, group, INIT, lib, library_t::ns, NTRU_112_BIT, NTRU_128_BIT, NTRU_192_BIT, NTRU_256_BIT, ntru_drbg_create(), ntru_param_set_get_by_id(), ntru_param_set_id_names, param_sets_optimum, param_sets_x9_98_balance, param_sets_x9_98_bandwidth, param_sets_x9_98_speed, RNG_TRUE, library_t::settings, and streq().
Referenced by METHOD().
 {
     private_ntru_ke_t *this;
     ntru_param_set_id_t *param_sets, param_set_id;
     rng_t *entropy;
     ntru_drbg_t *drbg;
     char *parameter_set;
     u_int32_t strength;
     parameter_set = lib->settings->get_str(lib->settings,
                         "%s.plugins.ntru.parameter_set", "optimum", lib->ns);
     if (streq(parameter_set, "x9_98_speed"))
     {
         param_sets = param_sets_x9_98_speed;
     }
     else if (streq(parameter_set, "x9_98_bandwidth"))
     {
         param_sets = param_sets_x9_98_bandwidth;
     }
     else if (streq(parameter_set, "x9_98_balance"))
     {
         param_sets = param_sets_x9_98_balance;
     }
     else
     {
         param_sets = param_sets_optimum;
     }
     switch (group)
     {
         case NTRU_112_BIT:
             strength = 112;
             param_set_id = param_sets[0];
             break;
         case NTRU_128_BIT:
             strength = 128;
             param_set_id = param_sets[1];
             break;
         case NTRU_192_BIT:
             strength = 192;
             param_set_id = param_sets[2];
             break;
         case NTRU_256_BIT:
             strength = 256;
             param_set_id = param_sets[3];
             break;
         default:
             return NULL;
     }
     DBG1(DBG_LIB, "%u bit %s NTRU parameter set %N selected", strength,
                    parameter_set, ntru_param_set_id_names, param_set_id);
     entropy = lib->crypto->create_rng(lib->crypto, RNG_TRUE);
     if (!entropy)
     {
         DBG1(DBG_LIB, "could not attach entropy source for DRBG");
         return NULL;
     }
     drbg = ntru_drbg_create(strength, chunk_from_str("IKE NTRU-KE"), entropy);
     if (!drbg)
     {
         DBG1(DBG_LIB, "could not instantiate DRBG at %u bit security", strength);
         entropy->destroy(entropy);
         return NULL;
     }
     INIT(this,
         .public = {
             .dh = {
                 .get_shared_secret = _get_shared_secret,
                 .set_other_public_value = _set_other_public_value,
                 .get_my_public_value = _get_my_public_value,
                 .get_dh_group = _get_dh_group,
                 .destroy = _destroy,
             },
         },
         .group = group,
         .param_set = ntru_param_set_get_by_id(param_set_id),
         .strength = strength,
         .entropy = entropy,
         .drbg = drbg,
     );
     return &this->public;
 }