strongSwan: eap_payload.c File Reference
eap_payload.c File Reference
#include <stddef.h>
#include "eap_payload.h"
#include <daemon.h>
#include <eap/eap.h>
#include <bio/bio_writer.h>
Classes
struct private_eap_payload_t
struct type_enumerator_t
Typedefs
typedef struct
private_eap_payload_t private_eap_payload_t
Functions
METHOD (payload_t, verify, status_t, private_eap_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_eap_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_eap_payload_t *this)
METHOD (payload_t, get_payload_type, payload_type_t, private_eap_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_eap_payload_t *this)
METHOD (payload_t, set_next_type, void, private_eap_payload_t *this, payload_type_t type)
METHOD (payload_t, get_length, size_t, private_eap_payload_t *this)
METHOD (eap_payload_t, get_data, chunk_t, private_eap_payload_t *this)
METHOD (eap_payload_t, set_data, void, private_eap_payload_t *this, chunk_t data)
METHOD (eap_payload_t, get_code, eap_code_t, private_eap_payload_t *this)
METHOD (eap_payload_t, get_identifier, u_int8_t, private_eap_payload_t *this)
static size_t extract_type (private_eap_payload_t *this, size_t offset, eap_type_t *type, u_int32_t *vendor)
METHOD (eap_payload_t, get_type, eap_type_t, private_eap_payload_t *this, u_int32_t *vendor)
METHOD (enumerator_t, enumerate_types, bool, type_enumerator_t *this, eap_type_t *type, u_int32_t *vendor)
METHOD (eap_payload_t, get_types, enumerator_t *, private_eap_payload_t *this)
METHOD (eap_payload_t, is_expanded, bool, private_eap_payload_t *this)
METHOD2 (payload_t, eap_payload_t, destroy, void, private_eap_payload_t *this)
eap_payload_t * eap_payload_create ()
eap_payload_t * eap_payload_create_data (chunk_t data)
eap_payload_t * eap_payload_create_data_own (chunk_t data)
eap_payload_t * eap_payload_create_code (eap_code_t code, u_int8_t identifier)
static void write_type (bio_writer_t *writer, eap_type_t type, u_int32_t vendor, bool expanded)
eap_payload_t * eap_payload_create_nak (u_int8_t identifier, eap_type_t type, u_int32_t vendor, bool expanded)
Variables
static encoding_rule_t encodings []
Typedef Documentation
typedef struct private_eap_payload_t private_eap_payload_t
Definition at line 26 of file eap_payload.c.
Function Documentation
static size_t extract_type (private_eap_payload_t * this, size_t offset, eap_type_t * type, u_int32_t * vendor) static
Get the current type at the given offset into this->data.
Returns
the new offset or 0 if failed
Definition at line 226 of file eap_payload.c.
References data, EAP_EXPANDED, offset, and untoh32().
Referenced by METHOD().
 {
     if (this->data.len > offset)
     {
         *vendor = 0;
         *type = this->data.ptr[offset];
         if (*type != EAP_EXPANDED)
         {
             return offset + 1;
         }
         if (this->data.len >= offset + 8)
         {
             *vendor = untoh32(this->data.ptr + offset) & 0x00FFFFFF;
             *type = untoh32(this->data.ptr + offset + 4);
             return offset + 8;
         }
     }
     return 0;
 }
METHOD (payload_t , verify , status_t , private_eap_payload_t * this)
Definition at line 102 of file eap_payload.c.
References code, data, DBG1, DBG_ENC, EAP_FAILURE, EAP_REQUEST, EAP_RESPONSE, EAP_SUCCESS, FAILED, length, SUCCESS, and untoh16().
 {
     u_int16_t length;
     u_int8_t code;
     if (this->data.len < 4)
     {
         DBG1(DBG_ENC, "EAP payloads EAP message too short (%d)", this->data.len);
         return FAILED;
     }
     length = untoh16(this->data.ptr + 2);
     if (this->data.len != length)
     {
         DBG1(DBG_ENC, "EAP payload length (%d) does not match contained "
              "message length (%d)", this->data.len, length);
         return FAILED;
     }
     code = this->data.ptr[0];
     switch (code)
     {
         case EAP_REQUEST:
         case EAP_RESPONSE:
         {
             if (this->data.len < 4)
             {
                 DBG1(DBG_ENC, "EAP Request/Response does not have any data");
                 return FAILED;
             }
             break;
         }
         case EAP_SUCCESS:
         case EAP_FAILURE:
         {
             if (this->data.len != 4)
             {
                 DBG1(DBG_ENC, "EAP Success/Failure has data");
                 return FAILED;
             }
             break;
         }
         default:
             return FAILED;
     }
     return SUCCESS;
 }
METHOD (payload_t , get_encoding_rules , int , private_eap_payload_t * this, encoding_rule_t ** rules)
Definition at line 149 of file eap_payload.c.
References countof, and encodings.
 {
     *rules = encodings;
     return countof(encodings);
 }
METHOD (payload_t , get_header_length , int , private_eap_payload_t * this)
Definition at line 156 of file eap_payload.c.
 {
     return 4;
 }
METHOD (payload_t , get_payload_type , payload_type_t , private_eap_payload_t * this)
Definition at line 162 of file eap_payload.c.
References PLV2_EAP.
 {
     return PLV2_EAP;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_eap_payload_t * this)
Definition at line 168 of file eap_payload.c.
 {
     return (this->next_payload);
 }
METHOD (payload_t , set_next_type , void , private_eap_payload_t * this, payload_type_t type)
Definition at line 174 of file eap_payload.c.
References type.
 {
     this->next_payload = type;
 }
METHOD (payload_t , get_length , size_t , private_eap_payload_t * this)
Definition at line 180 of file eap_payload.c.
 {
     return this->payload_length;
 }
METHOD (eap_payload_t , get_data , chunk_t , private_eap_payload_t * this)
Definition at line 186 of file eap_payload.c.
References data.
 {
     return this->data;
 }
METHOD (eap_payload_t , set_data , void , private_eap_payload_t * this, chunk_t data)
Definition at line 192 of file eap_payload.c.
References chunk_clone, free(), chunk_t::len, and chunk_t::ptr.
 {
     free(this->data.ptr);
     this->data = chunk_clone(data);
     this->payload_length = this->data.len + 4;
 }
METHOD (eap_payload_t , get_code , eap_code_t , private_eap_payload_t * this)
Definition at line 200 of file eap_payload.c.
References data.
 {
     if (this->data.len > 0)
     {
         return this->data.ptr[0];
     }
     /* should not happen, as it is verified */
     return 0;
 }
METHOD (eap_payload_t , get_identifier , u_int8_t , private_eap_payload_t * this)
Definition at line 211 of file eap_payload.c.
References data.
 {
     if (this->data.len > 1)
     {
         return this->data.ptr[1];
     }
     /* should not happen, as it is verified */
     return 0;
 }
METHOD (eap_payload_t , get_type , eap_type_t , private_eap_payload_t * this, u_int32_t * vendor)
Definition at line 247 of file eap_payload.c.
References extract_type(), and type.
 {
     eap_type_t type;
     *vendor = 0;
     if (extract_type(this, 4, &type, vendor))
     {
         return type;
     }
     return 0;
 }
METHOD (enumerator_t , enumerate_types , bool , type_enumerator_t * this, eap_type_t * type, u_int32_t * vendor)
Definition at line 272 of file eap_payload.c.
References extract_type(), and offset.
 {
     this->offset = extract_type(this->payload, this->offset, type, vendor);
     return this->offset;
 }
METHOD (eap_payload_t , get_types , enumerator_t * , private_eap_payload_t * this)
Definition at line 279 of file eap_payload.c.
References destroy(), EAP_NAK, enumerator_create_empty(), extract_type(), free(), INIT, offset, type_enumerator_t::public, and type.
 {
     type_enumerator_t *enumerator;
     eap_type_t type;
     u_int32_t vendor;
     size_t offset;
     offset = extract_type(this, 4, &type, &vendor);
     if (offset && type == EAP_NAK)
     {
         INIT(enumerator,
             .public = {
                 .enumerate = (void*)_enumerate_types,
                 .destroy = (void*)free,
             },
             .payload = this,
             .offset = offset,
         );
         return &enumerator->public;
     }
     return enumerator_create_empty();
 }
METHOD (eap_payload_t , is_expanded , bool , private_eap_payload_t * this)
Definition at line 303 of file eap_payload.c.
References data, EAP_EXPANDED, and FALSE.
 {
     return this->data.len > 4 ? this->data.ptr[4] == EAP_EXPANDED : FALSE;
 }
METHOD2 (payload_t , eap_payload_t , destroy , void , private_eap_payload_t * this)
Definition at line 309 of file eap_payload.c.
References chunk_free(), data, and free().
 {
     chunk_free(&this->data);
     free(this);
 }
static void write_type (bio_writer_t * writer, eap_type_t type, u_int32_t vendor, bool expanded) static
Write the given type either expanded or not
Definition at line 388 of file eap_payload.c.
References EAP_EXPANDED, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
Referenced by eap_payload_create_nak().
 {
     if (expanded)
     {
         writer->write_uint8(writer, EAP_EXPANDED);
         writer->write_uint24(writer, vendor);
         writer->write_uint32(writer, type);
     }
     else
     {
         writer->write_uint8(writer, type);
     }
 }
Variable Documentation
encoding_rule_t encodings[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_eap_payload_t, next_payload)   },
    { FLAG,             offsetof(private_eap_payload_t, critical)       },
    { RESERVED_BIT,     offsetof(private_eap_payload_t, reserved[0])    },
    { RESERVED_BIT,     offsetof(private_eap_payload_t, reserved[1])    },
    { RESERVED_BIT,     offsetof(private_eap_payload_t, reserved[2])    },
    { RESERVED_BIT,     offsetof(private_eap_payload_t, reserved[3])    },
    { RESERVED_BIT,     offsetof(private_eap_payload_t, reserved[4])    },
    { RESERVED_BIT,     offsetof(private_eap_payload_t, reserved[5])    },
    { RESERVED_BIT,     offsetof(private_eap_payload_t, reserved[6])    },
    { PAYLOAD_LENGTH,   offsetof(private_eap_payload_t, payload_length) },
    { CHUNK_DATA,       offsetof(private_eap_payload_t, data)           },
}
Encoding rules to parse or generate a EAP payload.
The defined offsets are the positions in a object of type private_eap_payload_t.
Definition at line 71 of file eap_payload.c.
Referenced by METHOD().