strongSwan: stroke_attribute.c File Reference
stroke_attribute.c File Reference
#include "stroke_attribute.h"
#include <daemon.h>
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_stroke_attribute_t
struct attributes_t
Typedefs
typedef struct
private_stroke_attribute_t private_stroke_attribute_t
Functions
static void attributes_destroy (attributes_t *this)
static mem_pool_t * find_pool (private_stroke_attribute_t *this, char *name)
static host_t * find_addr (private_stroke_attribute_t *this, linked_list_t *pools, identification_t *id, host_t *requested, mem_pool_op_t operation, host_t *peer)
METHOD (attribute_provider_t, acquire_address, host_t *, private_stroke_attribute_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
METHOD (attribute_provider_t, release_address, bool, private_stroke_attribute_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
static bool attr_filter (void *lock, host_t **in, configuration_attribute_type_t *type, void *dummy, chunk_t *data)
METHOD (attribute_provider_t, create_attribute_enumerator, enumerator_t *, private_stroke_attribute_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (stroke_attribute_t, add_pool, void, private_stroke_attribute_t *this, mem_pool_t *pool)
METHOD (stroke_attribute_t, add_dns, void, private_stroke_attribute_t *this, stroke_msg_t *msg)
METHOD (stroke_attribute_t, del_dns, void, private_stroke_attribute_t *this, stroke_msg_t *msg)
static bool pool_filter (void *lock, mem_pool_t **poolp, const char **name, void *d1, u_int *size, void *d2, u_int *online, void *d3, u_int *offline)
METHOD (stroke_attribute_t, create_pool_enumerator, enumerator_t *, private_stroke_attribute_t *this)
METHOD (stroke_attribute_t, create_lease_enumerator, enumerator_t *, private_stroke_attribute_t *this, char *name)
METHOD (stroke_attribute_t, destroy, void, private_stroke_attribute_t *this)
stroke_attribute_t * stroke_attribute_create ()
Typedef Documentation
typedef struct private_stroke_attribute_t private_stroke_attribute_t
Definition at line 23 of file stroke_attribute.c.
Function Documentation
static bool attr_filter (void * lock, host_t ** in, configuration_attribute_type_t * type, void * dummy, chunk_t * data) static
Filter function to convert host to DNS configuration attributes
Definition at line 184 of file stroke_attribute.c.
References FALSE, host_t::get_address, host_t::get_family, host, in, INTERNAL_IP4_DNS, INTERNAL_IP6_DNS, and TRUE.
Referenced by METHOD().
 {
     host_t *host = *in;
     switch (host->get_family(host))
     {
         case AF_INET:
             *type = INTERNAL_IP4_DNS;
             break;
         case AF_INET6:
             *type = INTERNAL_IP6_DNS;
             break;
         default:
             return FALSE;
     }
     *data = host->get_address(host);
     return TRUE;
 }
static void attributes_destroy (attributes_t * this) static
Destroy an attributes_t entry
Definition at line 64 of file stroke_attribute.c.
References destroy(), free(), and name.
Referenced by METHOD().
 {
     this->dns->destroy_offset(this->dns, offsetof(host_t, destroy));
     free(this->name);
     free(this);
 }
static host_t* find_addr (private_stroke_attribute_t * this, linked_list_t * pools, identification_t * id, host_t * requested, mem_pool_op_t operation, host_t * peer) static
Find an existing or not yet existing lease
Definition at line 95 of file stroke_attribute.c.
References mem_pool_t::acquire_address, addr, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, find_pool(), and name.
Referenced by METHOD().
 {
     host_t *addr = NULL;
     enumerator_t *enumerator;
     mem_pool_t *pool;
     char *name;
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = find_pool(this, name);
         if (pool)
         {
             addr = pool->acquire_address(pool, id, requested, operation, peer);
             if (addr)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     return addr;
 }
static mem_pool_t* find_pool (private_stroke_attribute_t * this, char * name) static
find a pool by name
Definition at line 74 of file stroke_attribute.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, mem_pool_t::get_name, and streq().
Referenced by find_addr(), and METHOD().
 {
     enumerator_t *enumerator;
     mem_pool_t *current, *found = NULL;
     enumerator = this->pools->create_enumerator(this->pools);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (streq(name, current->get_name(current)))
         {
             found = current;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (attribute_provider_t , acquire_address , host_t * , private_stroke_attribute_t * this, linked_list_t * pools, ike_sa_t * ike_sa, host_t * requested)
Definition at line 122 of file stroke_attribute.c.
References addr, find_addr(), ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, id, lock, MEM_POOL_EXISTING, MEM_POOL_NEW, MEM_POOL_REASSIGN, and spinlock_t::unlock.
 {
     identification_t *id;
     host_t *addr, *peer;
     id = ike_sa->get_other_eap_id(ike_sa);
     peer = ike_sa->get_other_host(ike_sa);
     this->lock->read_lock(this->lock);
     addr = find_addr(this, pools, id, requested, MEM_POOL_EXISTING, peer);
     if (!addr)
     {
         addr = find_addr(this, pools, id, requested, MEM_POOL_NEW, peer);
         if (!addr)
         {
             addr = find_addr(this, pools, id, requested, MEM_POOL_REASSIGN, peer);
         }
     }
     this->lock->unlock(this->lock);
     return addr;
 }
METHOD (attribute_provider_t , release_address , bool , private_stroke_attribute_t * this, linked_list_t * pools, host_t * address, ike_sa_t * ike_sa)
Definition at line 149 of file stroke_attribute.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, find_pool(), found, ike_sa_t::get_other_eap_id, id, lock, name, mem_pool_t::release_address, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     identification_t *id;
     mem_pool_t *pool;
     bool found = FALSE;
     char *name;
     id = ike_sa->get_other_eap_id(ike_sa);
     enumerator = pools->create_enumerator(pools);
     this->lock->read_lock(this->lock);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = find_pool(this, name);
         if (pool)
         {
             found = pool->release_address(pool, address, id);
             if (found)
             {
                 break;
             }
         }
     }
     this->lock->unlock(this->lock);
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (attribute_provider_t , create_attribute_enumerator , enumerator_t * , private_stroke_attribute_t * this, linked_list_t * pools, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 205 of file stroke_attribute.c.
References attr_filter(), daemon_t::bus, charon, linked_list_t::create_enumerator, enumerator_t::destroy, attributes_t::dns, enumerator_t::enumerate, enumerator_create_empty(), enumerator_create_filter(), peer_cfg_t::get_name, ike_sa_t::get_peer_cfg, bus_t::get_sa, lock, attributes_t::name, streq(), and spinlock_t::unlock.
 {
     peer_cfg_t *peer_cfg;
     enumerator_t *enumerator;
     attributes_t *attr;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (ike_sa)
     {
         peer_cfg = ike_sa->get_peer_cfg(ike_sa);
         this->lock->read_lock(this->lock);
         enumerator = this->attrs->create_enumerator(this->attrs);
         while (enumerator->enumerate(enumerator, &attr))
         {
             if (streq(attr->name, peer_cfg->get_name(peer_cfg)))
             {
                 enumerator->destroy(enumerator);
                 return enumerator_create_filter(
                                     attr->dns->create_enumerator(attr->dns),
                                     (void*)attr_filter, this->lock,
                                     (void*)this->lock->unlock);
             }
         }
         enumerator->destroy(enumerator);
         this->lock->unlock(this->lock);
     }
     return enumerator_create_empty();
 }
METHOD (stroke_attribute_t , add_pool , void , private_stroke_attribute_t * this, mem_pool_t * pool)
Definition at line 236 of file stroke_attribute.c.
References base, DBG1, DBG_CFG, enumerator_t::destroy, mem_pool_t::destroy, enumerator_t::enumerate, mem_pool_t::get_base, mem_pool_t::get_name, mem_pool_t::get_size, host_t::ip_equals, lock, size, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     mem_pool_t *current;
     host_t *base;
     int size;
     base = pool->get_base(pool);
     size = pool->get_size(pool);
     this->lock->write_lock(this->lock);
     enumerator = this->pools->create_enumerator(this->pools);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (base && current->get_base(current) &&
             base->ip_equals(base, current->get_base(current)) &&
             size == current->get_size(current))
         {
             DBG1(DBG_CFG, "reusing virtual IP address pool %s",
                  current->get_name(current));
             pool->destroy(pool);
             pool = NULL;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (pool)
     {
         if (base)
         {
             DBG1(DBG_CFG, "adding virtual IP address pool %s",
                  pool->get_name(pool));
         }
         this->pools->insert_last(this->pools, pool);
     }
     this->lock->unlock(this->lock);
 }
METHOD (stroke_attribute_t , add_dns , void , private_stroke_attribute_t * this, stroke_msg_t * msg)
Definition at line 278 of file stroke_attribute.c.
References stroke_msg_t::add_conn, DBG1, DBG_CFG, enumerator_t::destroy, attributes_t::dns, enumerator_t::enumerate, enumerator_create_token(), host, host_create_from_string(), INIT, linked_list_t::insert_last, linked_list_create(), lock, name, strdup, and spinlock_t::unlock.
 {
     if (msg->add_conn.other.dns)
     {
         enumerator_t *enumerator;
         attributes_t *attr = NULL;
         host_t *host;
         char *token;
         enumerator = enumerator_create_token(msg->add_conn.other.dns, ",", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             host = host_create_from_string(token, 0);
             if (host)
             {
                 if (!attr)
                 {
                     INIT(attr,
                         .name = strdup(msg->add_conn.name),
                         .dns = linked_list_create(),
                     );
                 }
                 attr->dns->insert_last(attr->dns, host);
             }
             else
             {
                 DBG1(DBG_CFG, "ignoring invalid DNS address '%s'", token);
             }
         }
         enumerator->destroy(enumerator);
         if (attr)
         {
             this->lock->write_lock(this->lock);
             this->attrs->insert_last(this->attrs, attr);
             this->lock->unlock(this->lock);
         }
     }
 }
METHOD (stroke_attribute_t , del_dns , void , private_stroke_attribute_t * this, stroke_msg_t * msg)
Definition at line 318 of file stroke_attribute.c.
References attributes_destroy(), stroke_msg_t::del_conn, enumerator_t::destroy, enumerator_t::enumerate, lock, attributes_t::name, streq(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     attributes_t *attr;
     this->lock->write_lock(this->lock);
     enumerator = this->attrs->create_enumerator(this->attrs);
     while (enumerator->enumerate(enumerator, &attr))
     {
         if (streq(msg->del_conn.name, attr->name))
         {
             this->attrs->remove_at(this->attrs, enumerator);
             attributes_destroy(attr);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (stroke_attribute_t , create_pool_enumerator , enumerator_t * , private_stroke_attribute_t * this)
Definition at line 361 of file stroke_attribute.c.
References enumerator_create_filter(), lock, pool_filter(), and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(this->pools->create_enumerator(this->pools),
                                     (void*)pool_filter,
                                     this->lock, (void*)this->lock->unlock);
 }
METHOD (stroke_attribute_t , create_lease_enumerator , enumerator_t * , private_stroke_attribute_t * this, char * name)
Definition at line 370 of file stroke_attribute.c.
References mem_pool_t::create_lease_enumerator, enumerator_create_cleaner(), find_pool(), lock, and spinlock_t::unlock.
 {
     mem_pool_t *pool;
     this->lock->read_lock(this->lock);
     pool = find_pool(this, name);
     if (!pool)
     {
         this->lock->unlock(this->lock);
         return NULL;
     }
     return enumerator_create_cleaner(pool->create_lease_enumerator(pool),
                                      (void*)this->lock->unlock, this->lock);
 }
METHOD (stroke_attribute_t , destroy , void , private_stroke_attribute_t * this)
Definition at line 385 of file stroke_attribute.c.
References attributes_destroy(), spinlock_t::destroy, destroy(), free(), and lock.
 {
     this->lock->destroy(this->lock);
     this->pools->destroy_offset(this->pools, offsetof(mem_pool_t, destroy));
     this->attrs->destroy_function(this->attrs, (void*)attributes_destroy);
     free(this);
 }
static bool pool_filter (void * lock, mem_pool_t ** poolp, const char ** name, void * d1, u_int * size, void * d2, u_int * online, void * d3, u_int * offline) static
Pool enumerator filter function, converts pool_t to name, size, ...
Definition at line 344 of file stroke_attribute.c.
References FALSE, mem_pool_t::get_name, mem_pool_t::get_offline, mem_pool_t::get_online, mem_pool_t::get_size, and TRUE.
Referenced by METHOD().
 {
     mem_pool_t *pool = *poolp;
     if (pool->get_size(pool) == 0)
     {
         return FALSE;
     }
     *name = pool->get_name(pool);
     *size = pool->get_size(pool);
     *online = pool->get_online(pool);
     *offline = pool->get_offline(pool);
     return TRUE;
 }