strongSwan: mediation_manager
mediation_manager
ikev2
Classes
struct mediation_manager_t
Typedefs
typedef struct mediation_manager_t mediation_manager_t
Functions
mediation_manager_t * mediation_manager_create (void)
Detailed Description
Typedef Documentation
typedef struct mediation_manager_t mediation_manager_t
Definition at line 24 of file mediation_manager.h.
Function Documentation
mediation_manager_t* mediation_manager_create (void)
Create a manager.
Returns
mediation_manager_t object
Definition at line 316 of file mediation_manager.c.
References INIT, linked_list_create(), mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by METHOD().
 {
     private_mediation_manager_t *this;
     INIT(this,
         .public = {
             .destroy = _destroy,
             .remove = _remove_sa,
             .update_sa_id = _update_sa_id,
             .check = _check,
             .check_and_register = _check_and_register,
         },
         .peers = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     return &this->public;
 }