strongSwan: dnskey_encoder.c File Reference
dnskey_encoder.c File Reference
#include "dnskey_encoder.h"
#include <utils/debug.h>
Functions
static bool build_pub (chunk_t *encoding, va_list args)
bool dnskey_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Function Documentation
static bool build_pub (chunk_t * encoding, va_list args) static
Encode an RSA public key in DNSKEY format (RFC 3110)
Definition at line 23 of file dnskey_encoder.c.
References chunk_alloc, chunk_free(), chunk_skip(), chunk_to_base64(), cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, FALSE, htoun16(), chunk_t::len, memcpy, n, chunk_t::ptr, and TRUE.
Referenced by dnskey_encoder_encode().
 {
     chunk_t n, e, pubkey;
     size_t exp_len;
     u_char *pos;
     if (cred_encoding_args(args, CRED_PART_RSA_MODULUS, &n,
                            CRED_PART_RSA_PUB_EXP, &e, CRED_PART_END))
     {
         /* remove leading zeros in exponent and modulus */
         while (*e.ptr == 0)
         {
             e = chunk_skip(e, 1);
         }
         while (*n.ptr == 0)
         {
             n = chunk_skip(n, 1);
         }
         if (e.len < 256)
         {
             /* exponent length fits into a single octet */
             exp_len = 1;
             pubkey = chunk_alloc(exp_len + e.len + n.len);
             pubkey.ptr[0] = (char)e.len;
         }
         else if (e.len < 65536)
         {
             /* exponent length fits into two octets preceded by zero octet */
             exp_len = 3;
             pubkey = chunk_alloc(exp_len + e.len + n.len);
             pubkey.ptr[0] = 0x00;
             htoun16(pubkey.ptr + 1, e.len);
         }
         else
         {
             /* exponent length is too large */
             return FALSE;
         }
         /* copy exponent and modulus and convert to base64 format */
         pos = pubkey.ptr + exp_len;
         memcpy(pos, e.ptr, e.len);
         pos += e.len;
         memcpy(pos, n.ptr, n.len);
         *encoding = chunk_to_base64(pubkey, NULL);
         chunk_free(&pubkey);
         return TRUE;
     }
     return FALSE;
 }