strongSwan: eap_simaka_reauth_card.c File Reference
eap_simaka_reauth_card.c File Reference
#include "eap_simaka_reauth_card.h"
#include <daemon.h>
#include <collections/hashtable.h>
Classes
struct private_eap_simaka_reauth_card_t
struct reauth_data_t
Typedefs
typedef struct
private_eap_simaka_reauth_card_t private_eap_simaka_reauth_card_t
Functions
static u_int hash (identification_t *key)
static bool equals (identification_t *key1, identification_t *key2)
METHOD (simaka_card_t, get_reauth, identification_t *, private_eap_simaka_reauth_card_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
METHOD (simaka_card_t, set_reauth, void, private_eap_simaka_reauth_card_t *this, identification_t *id, identification_t *next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
METHOD (simaka_card_t, get_quintuplet, status_t, private_eap_simaka_reauth_card_t *this, identification_t *id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int *res_len)
METHOD (eap_simaka_reauth_card_t, destroy, void, private_eap_simaka_reauth_card_t *this)
eap_simaka_reauth_card_t * eap_simaka_reauth_card_create ()
Typedef Documentation
typedef struct private_eap_simaka_reauth_card_t private_eap_simaka_reauth_card_t
Definition at line 21 of file eap_simaka_reauth_card.c.
Function Documentation
static bool equals (identification_t * key1, identification_t * key2) static
hashtable equals function
Definition at line 64 of file eap_simaka_reauth_card.c.
References identification_t::equals.
Referenced by eap_simaka_reauth_card_create().
 {
     return key1->equals(key1, key2);
 }
static u_int hash (identification_t * key) static
hashtable hash function
Definition at line 56 of file eap_simaka_reauth_card.c.
References chunk_hash(), and identification_t::get_encoding.
Referenced by eap_simaka_reauth_card_create().
 {
     return chunk_hash(key->get_encoding(key));
 }
METHOD (simaka_card_t , get_reauth , identification_t * , private_eap_simaka_reauth_card_t * this, identification_t * id, char mk[HASH_SIZE_SHA1], u_int16_t * counter)
Definition at line 69 of file eap_simaka_reauth_card.c.
References reauth_data_t::counter, data, identification_t::destroy, free(), reauth_data_t::id, memcpy, reauth_data_t::mk, reauth_data_t::permanent, and reauth().
 {
     reauth_data_t *data;
     identification_t *reauth;
     /* look up reauthentication data */
     data = this->reauth->remove(this->reauth, id);
     if (!data)
     {
         return NULL;
     }
     *counter = ++data->counter;
     memcpy(mk, data->mk, HASH_SIZE_SHA1);
     reauth = data->id;
     data->permanent->destroy(data->permanent);
     free(data);
     return reauth;
 }
METHOD (simaka_card_t , set_reauth , void , private_eap_simaka_reauth_card_t * this, identification_t * id, identification_t * next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
Definition at line 90 of file eap_simaka_reauth_card.c.
References identification_t::clone, reauth_data_t::counter, data, identification_t::destroy, reauth_data_t::id, malloc_thing, memcpy, reauth_data_t::mk, reauth_data_t::permanent, and reauth().
 {
     reauth_data_t *data;
     data = this->reauth->get(this->reauth, id);
     if (data)
     {
         data->id->destroy(data->id);
     }
     else
     {
         data = malloc_thing(reauth_data_t);
         data->permanent = id->clone(id);
         this->reauth->put(this->reauth, data->permanent, data);
     }
     data->counter = counter;
     data->id = next->clone(next);
     memcpy(data->mk, mk, HASH_SIZE_SHA1);
 }
METHOD (simaka_card_t , get_quintuplet , status_t , private_eap_simaka_reauth_card_t * this, identification_t * id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int * res_len)
Definition at line 112 of file eap_simaka_reauth_card.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (eap_simaka_reauth_card_t , destroy , void , private_eap_simaka_reauth_card_t * this)
Definition at line 120 of file eap_simaka_reauth_card.c.
References data, enumerator_t::destroy, identification_t::destroy, enumerator_t::enumerate, free(), reauth_data_t::id, key, reauth_data_t::permanent, and reauth().
 {
     enumerator_t *enumerator;
     reauth_data_t *data;
     void *key;
     enumerator = this->reauth->create_enumerator(this->reauth);
     while (enumerator->enumerate(enumerator, &key, &data))
     {
         data->id->destroy(data->id);
         data->permanent->destroy(data->permanent);
         free(data);
     }
     enumerator->destroy(enumerator);
     this->reauth->destroy(this->reauth);
     free(this);
 }