strongSwan: malloc_speed.c File Reference
malloc_speed.c File Reference
#include <stdio.h>
#include <time.h>
#include <library.h>
#include <utils/debug.h>
Macros
#define ALLOCS 1024
#define ROUNDS 2048
Functions
static void start_timing (struct timespec *start)
static double end_timing (struct timespec *start)
static void print_mallinfo ()
int main (int argc, char *argv[])
Macro Definition Documentation
#define ALLOCS 1024
Definition at line 49 of file malloc_speed.c.
Referenced by main().
#define ROUNDS 2048
Definition at line 50 of file malloc_speed.c.
Referenced by main().
Function Documentation
static double end_timing (struct timespec * start) static
Definition at line 30 of file malloc_speed.c.
Referenced by main().
 {
     struct timespec end;
     clock_gettime(CLOCK_THREAD_CPUTIME_ID, &end);
     return (end.tv_nsec - start->tv_nsec) / 1000000000.0 +
             (end.tv_sec - start->tv_sec) * 1.0;
 }
int main (int argc, char * argv[])
Definition at line 52 of file malloc_speed.c.
References ALLOCS, countof, end_timing(), free(), library_deinit(), library_init(), m, malloc(), print_mallinfo(), printf, ROUNDS, and start_timing().
 {
     struct timespec timing;
     int i, round;
     void *m[ALLOCS];
     /* a random set of allocations we test */
     int sizes[16] = { 1, 13, 100, 1000, 16, 10000, 50, 17,
                       123, 32, 8, 64, 8096, 1024, 123, 9 };
     library_init(NULL, "malloc_speed");
     atexit(library_deinit);
     print_mallinfo();
     start_timing(&timing);
     for (round = 0; round < ROUNDS; round++)
     {
         for (i = 0; i < ALLOCS; i++)
         {
             m[i] = malloc(sizes[(round + i) % countof(sizes)]);
         }
         for (i = 0; i < ALLOCS; i++)
         {
             free(m[i]);
         }
     }
     printf("time for %d malloc/frees, repeating %d rounds: %.4fs\n",
            ALLOCS, ROUNDS, end_timing(&timing));
     print_mallinfo();
     return 0;
 }
static void print_mallinfo () static
Definition at line 39 of file malloc_speed.c.
References printf.
Referenced by main().
 {
 #ifdef HAVE_MALLINFO
     struct mallinfo mi = mallinfo();
     printf("malloc: sbrk %d, mmap %d, used %d, free %d\n",
            mi.arena, mi.hblkhd, mi.uordblks, mi.fordblks);
 #endif /* HAVE_MALLINFO */
 }
static void start_timing (struct timespec * start) static
Definition at line 25 of file malloc_speed.c.
Referenced by main().
 {
     clock_gettime(CLOCK_THREAD_CPUTIME_ID, start);
 }