strongSwan: tls_crypto
tls_crypto
libtls
Classes
struct tls_crypto_t
Typedefs
typedef struct tls_crypto_t tls_crypto_t
typedef enum tls_cipher_suite_t tls_cipher_suite_t
typedef enum tls_hash_algorithm_t tls_hash_algorithm_t
typedef enum
tls_signature_algorithm_t tls_signature_algorithm_t
typedef enum
tls_client_certificate_type_t tls_client_certificate_type_t
typedef enum tls_ecc_curve_type_t tls_ecc_curve_type_t
typedef enum tls_named_curve_t tls_named_curve_t
typedef enum
tls_ansi_point_format_t tls_ansi_point_format_t
typedef enum tls_ec_point_format_t tls_ec_point_format_t
Enumerations
enum tls_cipher_suite_t {
TLS_NULL_WITH_NULL_NULL = 0x0000, TLS_RSA_WITH_NULL_MD5 = 0x0001, TLS_RSA_WITH_NULL_SHA = 0x0002, TLS_RSA_EXPORT_WITH_RC4_40_MD5 = 0x0003,
TLS_RSA_WITH_RC4_128_MD5 = 0x0004, TLS_RSA_WITH_RC4_128_SHA = 0x0005, TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = 0x0006, TLS_RSA_WITH_IDEA_CBC_SHA = 0x0007,
TLS_RSA_EXPORT_WITH_DES40_CBC_SHA = 0x0008, TLS_RSA_WITH_DES_CBC_SHA = 0x0009, TLS_RSA_WITH_3DES_EDE_CBC_SHA = 0x000A, TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = 0x000B,
TLS_DH_DSS_WITH_DES_CBC_SHA = 0x000C, TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = 0x000D, TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = 0x000E, TLS_DH_RSA_WITH_DES_CBC_SHA = 0x000F,
TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = 0x0010, TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = 0x0011, TLS_DHE_DSS_WITH_DES_CBC_SHA = 0x0012, TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 0x0013,
TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = 0x0014, TLS_DHE_RSA_WITH_DES_CBC_SHA = 0x0015, TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 0x0016, TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 = 0x0017,
TLS_DH_anon_WITH_RC4_128_MD5 = 0x0018, TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA = 0x0019, TLS_DH_anon_WITH_DES_CBC_SHA = 0x001A, TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = 0x001B,
TLS_KRB5_WITH_DES_CBC_SHA = 0x001E, TLS_KRB5_WITH_3DES_EDE_CBC_SHA = 0x001F, TLS_KRB5_WITH_RC4_128_SHA = 0x0020, TLS_KRB5_WITH_IDEA_CBC_SHA = 0x0021,
TLS_KRB5_WITH_DES_CBC_MD5 = 0x0022, TLS_KRB5_WITH_3DES_EDE_CBC_MD5 = 0x0023, TLS_KRB5_WITH_RC4_128_MD5 = 0x0024, TLS_KRB5_WITH_IDEA_CBC_MD5 = 0x0025,
TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA = 0x0026, TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA = 0x0027, TLS_KRB5_EXPORT_WITH_RC4_40_SHA = 0x0028, TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5 = 0x0029,
TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5 = 0x002A, TLS_KRB5_EXPORT_WITH_RC4_40_MD5 = 0x002B, TLS_PSK_WITH_NULL_SHA = 0x002C, TLS_DHE_PSK_WITH_NULL_SHA = 0x002D,
TLS_RSA_PSK_WITH_NULL_SHA = 0x002E, TLS_RSA_WITH_AES_128_CBC_SHA = 0x002F, TLS_DH_DSS_WITH_AES_128_CBC_SHA = 0x0030, TLS_DH_RSA_WITH_AES_128_CBC_SHA = 0x0031,
TLS_DHE_DSS_WITH_AES_128_CBC_SHA = 0x0032, TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 0x0033, TLS_DH_anon_WITH_AES_128_CBC_SHA = 0x0034, TLS_RSA_WITH_AES_256_CBC_SHA = 0x0035,
TLS_DH_DSS_WITH_AES_256_CBC_SHA = 0x0036, TLS_DH_RSA_WITH_AES_256_CBC_SHA = 0x0037, TLS_DHE_DSS_WITH_AES_256_CBC_SHA = 0x0038, TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 0x0039,
TLS_DH_anon_WITH_AES_256_CBC_SHA = 0x003A, TLS_RSA_WITH_NULL_SHA256 = 0x003B, TLS_RSA_WITH_AES_128_CBC_SHA256 = 0x003C, TLS_RSA_WITH_AES_256_CBC_SHA256 = 0x003D,
TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = 0x003E, TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = 0x003F, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = 0x0040, TLS_RSA_WITH_CAMELLIA_128_CBC_SHA = 0x0041,
TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA = 0x0042, TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA = 0x0043, TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA = 0x0044, TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA = 0x0045,
TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA = 0x0046, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 0x0067, TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = 0x0068, TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = 0x0069,
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = 0x006A, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 0x006B, TLS_DH_anon_WITH_AES_128_CBC_SHA256 = 0x006C, TLS_DH_anon_WITH_AES_256_CBC_SHA256 = 0x006D,
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA = 0x0084, TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA = 0x0085, TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA = 0x0086, TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA = 0x0087,
TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA = 0x0088, TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA = 0x0089, TLS_PSK_WITH_RC4_128_SHA = 0x008A, TLS_PSK_WITH_3DES_EDE_CBC_SHA = 0x008B,
TLS_PSK_WITH_AES_128_CBC_SHA = 0x008C, TLS_PSK_WITH_AES_256_CBC_SHA = 0x008D, TLS_DHE_PSK_WITH_RC4_128_SHA = 0x008E, TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA = 0x008F,
TLS_DHE_PSK_WITH_AES_128_CBC_SHA = 0x0090, TLS_DHE_PSK_WITH_AES_256_CBC_SHA = 0x0091, TLS_RSA_PSK_WITH_RC4_128_SHA = 0x0092, TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA = 0x0093,
TLS_RSA_PSK_WITH_AES_128_CBC_SHA = 0x0094, TLS_RSA_PSK_WITH_AES_256_CBC_SHA = 0x0095, TLS_RSA_WITH_SEED_CBC_SHA = 0x0096, TLS_DH_DSS_WITH_SEED_CBC_SHA = 0x0097,
TLS_DH_RSA_WITH_SEED_CBC_SHA = 0x0098, TLS_DHE_DSS_WITH_SEED_CBC_SHA = 0x0099, TLS_DHE_RSA_WITH_SEED_CBC_SHA = 0x009A, TLS_DH_anon_WITH_SEED_CBC_SHA = 0x009B,
TLS_RSA_WITH_AES_128_GCM_SHA256 = 0x009C, TLS_RSA_WITH_AES_256_GCM_SHA384 = 0x009D, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 0x009E, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 0x009F,
TLS_DH_RSA_WITH_AES_128_GCM_SHA256 = 0x00A0, TLS_DH_RSA_WITH_AES_256_GCM_SHA384 = 0x00A1, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = 0x00A2, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = 0x00A3,
TLS_DH_DSS_WITH_AES_128_GCM_SHA256 = 0x00A4, TLS_DH_DSS_WITH_AES_256_GCM_SHA384 = 0x00A5, TLS_DH_anon_WITH_AES_128_GCM_SHA256 = 0x00A6, TLS_DH_anon_WITH_AES_256_GCM_SHA384 = 0x00A7,
TLS_PSK_WITH_AES_128_GCM_SHA256 = 0x00A8, TLS_PSK_WITH_AES_256_GCM_SHA384 = 0x00A9, TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 = 0x00AA, TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 = 0x00AB,
TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 = 0x00AC, TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 = 0x00AD, TLS_PSK_WITH_AES_128_CBC_SHA256 = 0x00AE, TLS_PSK_WITH_AES_256_CBC_SHA384 = 0x00AF,
TLS_PSK_WITH_NULL_SHA256 = 0x00B0, TLS_PSK_WITH_NULL_SHA384 = 0x00B1, TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 = 0x00B2, TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 = 0x00B3,
TLS_DHE_PSK_WITH_NULL_SHA256 = 0x00B4, TLS_DHE_PSK_WITH_NULL_SHA384 = 0x00B5, TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 = 0x00B6, TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 = 0x00B7,
TLS_RSA_PSK_WITH_NULL_SHA256 = 0x00B8, TLS_RSA_PSK_WITH_NULL_SHA384 = 0x00B9, TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 0x00BA, TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 0x00BB,
TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 0x00BC, TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 0x00BD, TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 0x00BE, TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256 = 0x00BF,
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 0x00C0, TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 0x00C1, TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 0x00C2, TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 0x00C3,
TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 0x00C4, TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 = 0x00C5, TLS_EMPTY_RENEGOTIATION_INFO_SCSV = 0x00FF, TLS_ECDH_ECDSA_WITH_NULL_SHA = 0xC001,
TLS_ECDH_ECDSA_WITH_RC4_128_SHA = 0xC002, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = 0xC003, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = 0xC004, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = 0xC005,
TLS_ECDHE_ECDSA_WITH_NULL_SHA = 0xC006, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = 0xC007, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = 0xC008, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 0xC009,
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 0xC00A, TLS_ECDH_RSA_WITH_NULL_SHA = 0xC00B, TLS_ECDH_RSA_WITH_RC4_128_SHA = 0xC00C, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = 0xC00D,
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = 0xC00E, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = 0xC00F, TLS_ECDHE_RSA_WITH_NULL_SHA = 0xC010, TLS_ECDHE_RSA_WITH_RC4_128_SHA = 0xC011,
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = 0xC012, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 0xC013, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 0xC014, TLS_ECDH_anon_WITH_NULL_SHA = 0xC015,
TLS_ECDH_anon_WITH_RC4_128_SHA = 0xC016, TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = 0xC017, TLS_ECDH_anon_WITH_AES_128_CBC_SHA = 0xC018, TLS_ECDH_anon_WITH_AES_256_CBC_SHA = 0xC019,
TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA = 0xC01A, TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA = 0xC01B, TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA = 0xC01C, TLS_SRP_SHA_WITH_AES_128_CBC_SHA = 0xC01D,
TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA = 0xC01E, TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA = 0xC01F, TLS_SRP_SHA_WITH_AES_256_CBC_SHA = 0xC020, TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA = 0xC021,
TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA = 0xC022, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 0xC023, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 0xC024, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = 0xC025,
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = 0xC026, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 0xC027, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 0xC028, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = 0xC029,
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = 0xC02A, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 0xC02B, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 0xC02C, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = 0xC02D,
TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = 0xC02E, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 0xC02F, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 0xC030, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = 0xC031,
TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = 0xC032, TLS_ECDHE_PSK_WITH_RC4_128_SHA = 0xC033, TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA = 0xC034, TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA = 0xC035,
TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA = 0xC036, TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256 = 0xC037, TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384 = 0xC038, TLS_ECDHE_PSK_WITH_NULL_SHA = 0xC039,
TLS_ECDHE_PSK_WITH_NULL_SHA256 = 0xC03A, TLS_ECDHE_PSK_WITH_NULL_SHA384 = 0xC03B
}
enum tls_hash_algorithm_t {
TLS_HASH_NONE = 0, TLS_HASH_MD5 = 1, TLS_HASH_SHA1 = 2, TLS_HASH_SHA224 = 3,
TLS_HASH_SHA256 = 4, TLS_HASH_SHA384 = 5, TLS_HASH_SHA512 = 6
}
enum tls_signature_algorithm_t { TLS_SIG_RSA = 1, TLS_SIG_DSA = 2, TLS_SIG_ECDSA = 3 }
enum tls_client_certificate_type_t {
TLS_RSA_SIGN = 1, TLS_DSA_SIGN = 2, TLS_RSA_FIXED_DH = 3, TLS_DSS_FIXED_DH = 4,
TLS_RSA_EPHEMERAL_DH = 5, TLS_DSS_EPHEMERAL_DH = 6, TLS_FORTEZZA_DMS = 20, TLS_ECDSA_SIGN = 64,
TLS_RSA_FIXED_ECDH = 65, TLS_ECDSA_FIXED_ECDH = 66
}
enum tls_ecc_curve_type_t { TLS_ECC_EXPLICIT_PRIME = 1, TLS_ECC_EXPLICIT_CHAR2 = 2, TLS_ECC_NAMED_CURVE = 3 }
enum tls_named_curve_t {
TLS_SECT163K1 = 1, TLS_SECT163R1 = 2, TLS_SECT163R2 = 3, TLS_SECT193R1 = 4,
TLS_SECT193R2 = 5, TLS_SECT233K1 = 6, TLS_SECT233R1 = 7, TLS_SECT239K1 = 8,
TLS_SECT283K1 = 9, TLS_SECT283R1 = 10, TLS_SECT409K1 = 11, TLS_SECT409R1 = 12,
TLS_SECT571K1 = 13, TLS_SECT571R1 = 14, TLS_SECP160K1 = 15, TLS_SECP160R1 = 16,
TLS_SECP160R2 = 17, TLS_SECP192K1 = 18, TLS_SECP192R1 = 19, TLS_SECP224K1 = 20,
TLS_SECP224R1 = 21, TLS_SECP256K1 = 22, TLS_SECP256R1 = 23, TLS_SECP384R1 = 24,
TLS_SECP521R1 = 25
}
enum tls_ansi_point_format_t {
TLS_ANSI_COMPRESSED = 2, TLS_ANSI_COMPRESSED_Y = 3, TLS_ANSI_UNCOMPRESSED = 4, TLS_ANSI_HYBRID = 6,
TLS_ANSI_HYBRID_Y = 7
}
enum tls_ec_point_format_t { TLS_EC_POINT_UNCOMPRESSED = 0, TLS_EC_POINT_ANSIX962_COMPRESSED_PRIME = 1, TLS_EC_POINT_ANSIX962_COMPRESSED_CHAR2 = 2 }
Functions
tls_crypto_t * tls_crypto_create (tls_t *tls, tls_cache_t *cache)
int tls_crypto_get_supported_suites (bool null, tls_cipher_suite_t **suites)
Variables
enum_name_t * tls_cipher_suite_names
enum_name_t * tls_hash_algorithm_names
enum_name_t * tls_signature_algorithm_names
enum_name_t * tls_client_certificate_type_names
enum_name_t * tls_ecc_curve_type_names
enum_name_t * tls_named_curve_names
enum_name_t * tls_ansi_point_format_names
enum_name_t * tls_ec_point_format_names
Detailed Description
Typedef Documentation
typedef enum tls_ansi_point_format_t tls_ansi_point_format_t
Definition at line 31 of file tls_crypto.h.
typedef enum tls_cipher_suite_t tls_cipher_suite_t
Definition at line 25 of file tls_crypto.h.
typedef enum tls_client_certificate_type_t tls_client_certificate_type_t
Definition at line 28 of file tls_crypto.h.
typedef struct tls_crypto_t tls_crypto_t
Definition at line 24 of file tls_crypto.h.
typedef enum tls_ec_point_format_t tls_ec_point_format_t
Definition at line 32 of file tls_crypto.h.
typedef enum tls_ecc_curve_type_t tls_ecc_curve_type_t
Definition at line 29 of file tls_crypto.h.
typedef enum tls_hash_algorithm_t tls_hash_algorithm_t
Definition at line 26 of file tls_crypto.h.
typedef enum tls_named_curve_t tls_named_curve_t
Definition at line 30 of file tls_crypto.h.
typedef enum tls_signature_algorithm_t tls_signature_algorithm_t
Definition at line 27 of file tls_crypto.h.
Enumeration Type Documentation
enum tls_ansi_point_format_t
EC Point format, ANSI X9.62.
Enumerator
TLS_ANSI_COMPRESSED
TLS_ANSI_COMPRESSED_Y
TLS_ANSI_UNCOMPRESSED
TLS_ANSI_HYBRID
TLS_ANSI_HYBRID_Y
Definition at line 366 of file tls_crypto.h.
{
     TLS_ANSI_COMPRESSED =   2,
     TLS_ANSI_COMPRESSED_Y = 3,
     TLS_ANSI_UNCOMPRESSED = 4,
     TLS_ANSI_HYBRID =       6,
     TLS_ANSI_HYBRID_Y =     7,
 };
enum tls_cipher_suite_t
TLS cipher suites
Enumerator
TLS_NULL_WITH_NULL_NULL
TLS_RSA_WITH_NULL_MD5
TLS_RSA_WITH_NULL_SHA
TLS_RSA_EXPORT_WITH_RC4_40_MD5
TLS_RSA_WITH_RC4_128_MD5
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5
TLS_RSA_WITH_IDEA_CBC_SHA
TLS_RSA_EXPORT_WITH_DES40_CBC_SHA
TLS_RSA_WITH_DES_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA
TLS_DH_DSS_WITH_DES_CBC_SHA
TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA
TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA
TLS_DH_RSA_WITH_DES_CBC_SHA
TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA
TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
TLS_DHE_DSS_WITH_DES_CBC_SHA
TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA
TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
TLS_DHE_RSA_WITH_DES_CBC_SHA
TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_DH_anon_EXPORT_WITH_RC4_40_MD5
TLS_DH_anon_WITH_RC4_128_MD5
TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA
TLS_DH_anon_WITH_DES_CBC_SHA
TLS_DH_anon_WITH_3DES_EDE_CBC_SHA
TLS_KRB5_WITH_DES_CBC_SHA
TLS_KRB5_WITH_3DES_EDE_CBC_SHA
TLS_KRB5_WITH_RC4_128_SHA
TLS_KRB5_WITH_IDEA_CBC_SHA
TLS_KRB5_WITH_DES_CBC_MD5
TLS_KRB5_WITH_3DES_EDE_CBC_MD5
TLS_KRB5_WITH_RC4_128_MD5
TLS_KRB5_WITH_IDEA_CBC_MD5
TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA
TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA
TLS_KRB5_EXPORT_WITH_RC4_40_SHA
TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5
TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5
TLS_KRB5_EXPORT_WITH_RC4_40_MD5
TLS_PSK_WITH_NULL_SHA
TLS_DHE_PSK_WITH_NULL_SHA
TLS_RSA_PSK_WITH_NULL_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_DH_DSS_WITH_AES_128_CBC_SHA
TLS_DH_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DH_anon_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_DH_DSS_WITH_AES_256_CBC_SHA
TLS_DH_RSA_WITH_AES_256_CBC_SHA
TLS_DHE_DSS_WITH_AES_256_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_DH_anon_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_NULL_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_DH_DSS_WITH_AES_128_CBC_SHA256
TLS_DH_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA
TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA
TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA
TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA
TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DH_DSS_WITH_AES_256_CBC_SHA256
TLS_DH_RSA_WITH_AES_256_CBC_SHA256
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
TLS_DH_anon_WITH_AES_128_CBC_SHA256
TLS_DH_anon_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA
TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA
TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA
TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA
TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA
TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA
TLS_PSK_WITH_RC4_128_SHA
TLS_PSK_WITH_3DES_EDE_CBC_SHA
TLS_PSK_WITH_AES_128_CBC_SHA
TLS_PSK_WITH_AES_256_CBC_SHA
TLS_DHE_PSK_WITH_RC4_128_SHA
TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA
TLS_DHE_PSK_WITH_AES_128_CBC_SHA
TLS_DHE_PSK_WITH_AES_256_CBC_SHA
TLS_RSA_PSK_WITH_RC4_128_SHA
TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA
TLS_RSA_PSK_WITH_AES_128_CBC_SHA
TLS_RSA_PSK_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_SEED_CBC_SHA
TLS_DH_DSS_WITH_SEED_CBC_SHA
TLS_DH_RSA_WITH_SEED_CBC_SHA
TLS_DHE_DSS_WITH_SEED_CBC_SHA
TLS_DHE_RSA_WITH_SEED_CBC_SHA
TLS_DH_anon_WITH_SEED_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DH_RSA_WITH_AES_128_GCM_SHA256
TLS_DH_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
TLS_DH_DSS_WITH_AES_128_GCM_SHA256
TLS_DH_DSS_WITH_AES_256_GCM_SHA384
TLS_DH_anon_WITH_AES_128_GCM_SHA256
TLS_DH_anon_WITH_AES_256_GCM_SHA384
TLS_PSK_WITH_AES_128_GCM_SHA256
TLS_PSK_WITH_AES_256_GCM_SHA384
TLS_DHE_PSK_WITH_AES_128_GCM_SHA256
TLS_DHE_PSK_WITH_AES_256_GCM_SHA384
TLS_RSA_PSK_WITH_AES_128_GCM_SHA256
TLS_RSA_PSK_WITH_AES_256_GCM_SHA384
TLS_PSK_WITH_AES_128_CBC_SHA256
TLS_PSK_WITH_AES_256_CBC_SHA384
TLS_PSK_WITH_NULL_SHA256
TLS_PSK_WITH_NULL_SHA384
TLS_DHE_PSK_WITH_AES_128_CBC_SHA256
TLS_DHE_PSK_WITH_AES_256_CBC_SHA384
TLS_DHE_PSK_WITH_NULL_SHA256
TLS_DHE_PSK_WITH_NULL_SHA384
TLS_RSA_PSK_WITH_AES_128_CBC_SHA256
TLS_RSA_PSK_WITH_AES_256_CBC_SHA384
TLS_RSA_PSK_WITH_NULL_SHA256
TLS_RSA_PSK_WITH_NULL_SHA384
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256
TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256
TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256
TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256
TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256
TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256
TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256
TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256
TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256
TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256
TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256
TLS_EMPTY_RENEGOTIATION_INFO_SCSV
TLS_ECDH_ECDSA_WITH_NULL_SHA
TLS_ECDH_ECDSA_WITH_RC4_128_SHA
TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_NULL_SHA
TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDH_RSA_WITH_NULL_SHA
TLS_ECDH_RSA_WITH_RC4_128_SHA
TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_NULL_SHA
TLS_ECDHE_RSA_WITH_RC4_128_SHA
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDH_anon_WITH_NULL_SHA
TLS_ECDH_anon_WITH_RC4_128_SHA
TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_anon_WITH_AES_128_CBC_SHA
TLS_ECDH_anon_WITH_AES_256_CBC_SHA
TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA
TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA
TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA
TLS_SRP_SHA_WITH_AES_128_CBC_SHA
TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA
TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA
TLS_SRP_SHA_WITH_AES_256_CBC_SHA
TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA
TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_PSK_WITH_RC4_128_SHA
TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA
TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA
TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA
TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256
TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384
TLS_ECDHE_PSK_WITH_NULL_SHA
TLS_ECDHE_PSK_WITH_NULL_SHA256
TLS_ECDHE_PSK_WITH_NULL_SHA384
Definition at line 45 of file tls_crypto.h.
{
     TLS_NULL_WITH_NULL_NULL =                   0x0000,
     TLS_RSA_WITH_NULL_MD5 =                     0x0001,
     TLS_RSA_WITH_NULL_SHA =                     0x0002,
     TLS_RSA_EXPORT_WITH_RC4_40_MD5 =            0x0003,
     TLS_RSA_WITH_RC4_128_MD5 =                  0x0004,
     TLS_RSA_WITH_RC4_128_SHA =                  0x0005,
     TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 =        0x0006,
     TLS_RSA_WITH_IDEA_CBC_SHA =                 0x0007,
     TLS_RSA_EXPORT_WITH_DES40_CBC_SHA =         0x0008,
     TLS_RSA_WITH_DES_CBC_SHA =                  0x0009,
     TLS_RSA_WITH_3DES_EDE_CBC_SHA =             0x000A,
     TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA =      0x000B,
     TLS_DH_DSS_WITH_DES_CBC_SHA =               0x000C,
     TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA =          0x000D,
     TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA =      0x000E,
     TLS_DH_RSA_WITH_DES_CBC_SHA =               0x000F,
     TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA =          0x0010,
     TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA =     0x0011,
     TLS_DHE_DSS_WITH_DES_CBC_SHA =              0x0012,
     TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA =         0x0013,
     TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA =     0x0014,
     TLS_DHE_RSA_WITH_DES_CBC_SHA =              0x0015,
     TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA =         0x0016,
     TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 =        0x0017,
     TLS_DH_anon_WITH_RC4_128_MD5 =              0x0018,
     TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA =     0x0019,
     TLS_DH_anon_WITH_DES_CBC_SHA =              0x001A,
     TLS_DH_anon_WITH_3DES_EDE_CBC_SHA =         0x001B,
     TLS_KRB5_WITH_DES_CBC_SHA =                 0x001E,
     TLS_KRB5_WITH_3DES_EDE_CBC_SHA =            0x001F,
     TLS_KRB5_WITH_RC4_128_SHA =                 0x0020,
     TLS_KRB5_WITH_IDEA_CBC_SHA =                0x0021,
     TLS_KRB5_WITH_DES_CBC_MD5 =                 0x0022,
     TLS_KRB5_WITH_3DES_EDE_CBC_MD5 =            0x0023,
     TLS_KRB5_WITH_RC4_128_MD5 =                 0x0024,
     TLS_KRB5_WITH_IDEA_CBC_MD5 =                0x0025,
     TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA =       0x0026,
     TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA =       0x0027,
     TLS_KRB5_EXPORT_WITH_RC4_40_SHA =           0x0028,
     TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5 =       0x0029,
     TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5 =       0x002A,
     TLS_KRB5_EXPORT_WITH_RC4_40_MD5 =           0x002B,
     TLS_PSK_WITH_NULL_SHA =                     0x002C,
     TLS_DHE_PSK_WITH_NULL_SHA =                 0x002D,
     TLS_RSA_PSK_WITH_NULL_SHA =                 0x002E,
     TLS_RSA_WITH_AES_128_CBC_SHA =              0x002F,
     TLS_DH_DSS_WITH_AES_128_CBC_SHA =           0x0030,
     TLS_DH_RSA_WITH_AES_128_CBC_SHA =           0x0031,
     TLS_DHE_DSS_WITH_AES_128_CBC_SHA =          0x0032,
     TLS_DHE_RSA_WITH_AES_128_CBC_SHA =          0x0033,
     TLS_DH_anon_WITH_AES_128_CBC_SHA =          0x0034,
     TLS_RSA_WITH_AES_256_CBC_SHA =              0x0035,
     TLS_DH_DSS_WITH_AES_256_CBC_SHA =           0x0036,
     TLS_DH_RSA_WITH_AES_256_CBC_SHA =           0x0037,
     TLS_DHE_DSS_WITH_AES_256_CBC_SHA =          0x0038,
     TLS_DHE_RSA_WITH_AES_256_CBC_SHA =          0x0039,
     TLS_DH_anon_WITH_AES_256_CBC_SHA =          0x003A,
     TLS_RSA_WITH_NULL_SHA256 =                  0x003B,
     TLS_RSA_WITH_AES_128_CBC_SHA256 =           0x003C,
     TLS_RSA_WITH_AES_256_CBC_SHA256 =           0x003D,
     TLS_DH_DSS_WITH_AES_128_CBC_SHA256 =        0x003E,
     TLS_DH_RSA_WITH_AES_128_CBC_SHA256 =        0x003F,
     TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 =       0x0040,
     TLS_RSA_WITH_CAMELLIA_128_CBC_SHA =         0x0041,
     TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA =      0x0042,
     TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA =      0x0043,
     TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA =     0x0044,
     TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA =     0x0045,
     TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA =     0x0046,
     TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 =       0x0067,
     TLS_DH_DSS_WITH_AES_256_CBC_SHA256 =        0x0068,
     TLS_DH_RSA_WITH_AES_256_CBC_SHA256 =        0x0069,
     TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 =       0x006A,
     TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 =       0x006B,
     TLS_DH_anon_WITH_AES_128_CBC_SHA256 =       0x006C,
     TLS_DH_anon_WITH_AES_256_CBC_SHA256 =       0x006D,
     TLS_RSA_WITH_CAMELLIA_256_CBC_SHA =         0x0084,
     TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA =      0x0085,
     TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA =      0x0086,
     TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA =     0x0087,
     TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA =     0x0088,
     TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA =     0x0089,
     TLS_PSK_WITH_RC4_128_SHA =                  0x008A,
     TLS_PSK_WITH_3DES_EDE_CBC_SHA =             0x008B,
     TLS_PSK_WITH_AES_128_CBC_SHA =              0x008C,
     TLS_PSK_WITH_AES_256_CBC_SHA =              0x008D,
     TLS_DHE_PSK_WITH_RC4_128_SHA =              0x008E,
     TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA =         0x008F,
     TLS_DHE_PSK_WITH_AES_128_CBC_SHA =          0x0090,
     TLS_DHE_PSK_WITH_AES_256_CBC_SHA =          0x0091,
     TLS_RSA_PSK_WITH_RC4_128_SHA =              0x0092,
     TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA =         0x0093,
     TLS_RSA_PSK_WITH_AES_128_CBC_SHA =          0x0094,
     TLS_RSA_PSK_WITH_AES_256_CBC_SHA =          0x0095,
     TLS_RSA_WITH_SEED_CBC_SHA =                 0x0096,
     TLS_DH_DSS_WITH_SEED_CBC_SHA =              0x0097,
     TLS_DH_RSA_WITH_SEED_CBC_SHA =              0x0098,
     TLS_DHE_DSS_WITH_SEED_CBC_SHA =             0x0099,
     TLS_DHE_RSA_WITH_SEED_CBC_SHA =             0x009A,
     TLS_DH_anon_WITH_SEED_CBC_SHA =             0x009B,
     TLS_RSA_WITH_AES_128_GCM_SHA256 =           0x009C,
     TLS_RSA_WITH_AES_256_GCM_SHA384 =           0x009D,
     TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 =       0x009E,
     TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 =       0x009F,
     TLS_DH_RSA_WITH_AES_128_GCM_SHA256 =        0x00A0,
     TLS_DH_RSA_WITH_AES_256_GCM_SHA384 =        0x00A1,
     TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 =       0x00A2,
     TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 =       0x00A3,
     TLS_DH_DSS_WITH_AES_128_GCM_SHA256 =        0x00A4,
     TLS_DH_DSS_WITH_AES_256_GCM_SHA384 =        0x00A5,
     TLS_DH_anon_WITH_AES_128_GCM_SHA256 =       0x00A6,
     TLS_DH_anon_WITH_AES_256_GCM_SHA384 =       0x00A7,
     TLS_PSK_WITH_AES_128_GCM_SHA256 =           0x00A8,
     TLS_PSK_WITH_AES_256_GCM_SHA384 =           0x00A9,
     TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 =       0x00AA,
     TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 =       0x00AB,
     TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 =       0x00AC,
     TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 =       0x00AD,
     TLS_PSK_WITH_AES_128_CBC_SHA256 =           0x00AE,
     TLS_PSK_WITH_AES_256_CBC_SHA384 =           0x00AF,
     TLS_PSK_WITH_NULL_SHA256 =                  0x00B0,
     TLS_PSK_WITH_NULL_SHA384 =                  0x00B1,
     TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 =       0x00B2,
     TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 =       0x00B3,
     TLS_DHE_PSK_WITH_NULL_SHA256 =              0x00B4,
     TLS_DHE_PSK_WITH_NULL_SHA384 =              0x00B5,
     TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 =       0x00B6,
     TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 =       0x00B7,
     TLS_RSA_PSK_WITH_NULL_SHA256 =              0x00B8,
     TLS_RSA_PSK_WITH_NULL_SHA384 =              0x00B9,
     TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256 =      0x00BA,
     TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256 =   0x00BB,
     TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256 =   0x00BC,
     TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256 =  0x00BD,
     TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 =  0x00BE,
     TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256 =  0x00BF,
     TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256 =      0x00C0,
     TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256 =   0x00C1,
     TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256 =   0x00C2,
     TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256 =  0x00C3,
     TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256 =  0x00C4,
     TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 =  0x00C5,
     TLS_EMPTY_RENEGOTIATION_INFO_SCSV =         0x00FF,
     TLS_ECDH_ECDSA_WITH_NULL_SHA =              0xC001,
     TLS_ECDH_ECDSA_WITH_RC4_128_SHA =           0xC002,
     TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA =      0xC003,
     TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA =       0xC004,
     TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA =       0xC005,
     TLS_ECDHE_ECDSA_WITH_NULL_SHA =             0xC006,
     TLS_ECDHE_ECDSA_WITH_RC4_128_SHA =          0xC007,
     TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA =     0xC008,
     TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA =      0xC009,
     TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA =      0xC00A,
     TLS_ECDH_RSA_WITH_NULL_SHA =                0xC00B,
     TLS_ECDH_RSA_WITH_RC4_128_SHA =             0xC00C,
     TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA =        0xC00D,
     TLS_ECDH_RSA_WITH_AES_128_CBC_SHA =         0xC00E,
     TLS_ECDH_RSA_WITH_AES_256_CBC_SHA =         0xC00F,
     TLS_ECDHE_RSA_WITH_NULL_SHA =               0xC010,
     TLS_ECDHE_RSA_WITH_RC4_128_SHA =            0xC011,
     TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA =       0xC012,
     TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA =        0xC013,
     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA =        0xC014,
     TLS_ECDH_anon_WITH_NULL_SHA =               0xC015,
     TLS_ECDH_anon_WITH_RC4_128_SHA =            0xC016,
     TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA =       0xC017,
     TLS_ECDH_anon_WITH_AES_128_CBC_SHA =        0xC018,
     TLS_ECDH_anon_WITH_AES_256_CBC_SHA =        0xC019,
     TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA =         0xC01A,
     TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA =     0xC01B,
     TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA =     0xC01C,
     TLS_SRP_SHA_WITH_AES_128_CBC_SHA =          0xC01D,
     TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA =      0xC01E,
     TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA =      0xC01F,
     TLS_SRP_SHA_WITH_AES_256_CBC_SHA =          0xC020,
     TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA =      0xC021,
     TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA =      0xC022,
     TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 =   0xC023,
     TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 =   0xC024,
     TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 =    0xC025,
     TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 =    0xC026,
     TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 =     0xC027,
     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 =     0xC028,
     TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 =      0xC029,
     TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 =      0xC02A,
     TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 =   0xC02B,
     TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 =   0xC02C,
     TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 =    0xC02D,
     TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 =    0xC02E,
     TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 =     0xC02F,
     TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 =     0xC030,
     TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 =      0xC031,
     TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 =      0xC032,
     TLS_ECDHE_PSK_WITH_RC4_128_SHA =            0xC033,
     TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA =       0xC034,
     TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA =        0xC035,
     TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA =        0xC036,
     TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256 =     0xC037,
     TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384 =     0xC038,
     TLS_ECDHE_PSK_WITH_NULL_SHA =               0xC039,
     TLS_ECDHE_PSK_WITH_NULL_SHA256 =            0xC03A,
     TLS_ECDHE_PSK_WITH_NULL_SHA384 =            0xC03B
 };
enum tls_client_certificate_type_t
TLS ClientCertificateType
Enumerator
TLS_RSA_SIGN
TLS_DSA_SIGN
TLS_RSA_FIXED_DH
TLS_DSS_FIXED_DH
TLS_RSA_EPHEMERAL_DH
TLS_DSS_EPHEMERAL_DH
TLS_FORTEZZA_DMS
TLS_ECDSA_SIGN
TLS_RSA_FIXED_ECDH
TLS_ECDSA_FIXED_ECDH
Definition at line 295 of file tls_crypto.h.
{
     TLS_RSA_SIGN =          1,
     TLS_DSA_SIGN =          2,
     TLS_RSA_FIXED_DH =      3,
     TLS_DSS_FIXED_DH =      4,
     TLS_RSA_EPHEMERAL_DH =  5,
     TLS_DSS_EPHEMERAL_DH =  6,
     TLS_FORTEZZA_DMS =      20,
     TLS_ECDSA_SIGN =        64,
     TLS_RSA_FIXED_ECDH =    65,
     TLS_ECDSA_FIXED_ECDH =  66,
 };
enum tls_ec_point_format_t
EC Point format, TLS specific identifiers.
Enumerator
TLS_EC_POINT_UNCOMPRESSED
TLS_EC_POINT_ANSIX962_COMPRESSED_PRIME
TLS_EC_POINT_ANSIX962_COMPRESSED_CHAR2
Definition at line 382 of file tls_crypto.h.
{
     TLS_EC_POINT_UNCOMPRESSED = 0,
     TLS_EC_POINT_ANSIX962_COMPRESSED_PRIME = 1,
     TLS_EC_POINT_ANSIX962_COMPRESSED_CHAR2 = 2,
 };
enum tls_ecc_curve_type_t
TLS EccCurveType
Enumerator
TLS_ECC_EXPLICIT_PRIME
TLS_ECC_EXPLICIT_CHAR2
TLS_ECC_NAMED_CURVE
Definition at line 316 of file tls_crypto.h.
{
     TLS_ECC_EXPLICIT_PRIME =    1,
     TLS_ECC_EXPLICIT_CHAR2 =    2,
     TLS_ECC_NAMED_CURVE =       3,
 };
enum tls_hash_algorithm_t
TLS HashAlgorithm identifiers
Enumerator
TLS_HASH_NONE
TLS_HASH_MD5
TLS_HASH_SHA1
TLS_HASH_SHA224
TLS_HASH_SHA256
TLS_HASH_SHA384
TLS_HASH_SHA512
Definition at line 263 of file tls_crypto.h.
{
     TLS_HASH_NONE =     0,
     TLS_HASH_MD5 =      1,
     TLS_HASH_SHA1 =     2,
     TLS_HASH_SHA224 =   3,
     TLS_HASH_SHA256 =   4,
     TLS_HASH_SHA384 =   5,
     TLS_HASH_SHA512 =   6,
 };
enum tls_named_curve_t
TLS Named Curve identifiers
Enumerator
TLS_SECT163K1
TLS_SECT163R1
TLS_SECT163R2
TLS_SECT193R1
TLS_SECT193R2
TLS_SECT233K1
TLS_SECT233R1
TLS_SECT239K1
TLS_SECT283K1
TLS_SECT283R1
TLS_SECT409K1
TLS_SECT409R1
TLS_SECT571K1
TLS_SECT571R1
TLS_SECP160K1
TLS_SECP160R1
TLS_SECP160R2
TLS_SECP192K1
TLS_SECP192R1
TLS_SECP224K1
TLS_SECP224R1
TLS_SECP256K1
TLS_SECP256R1
TLS_SECP384R1
TLS_SECP521R1
Definition at line 330 of file tls_crypto.h.
{
     TLS_SECT163K1 =      1,
     TLS_SECT163R1 =      2,
     TLS_SECT163R2 =      3,
     TLS_SECT193R1 =      4,
     TLS_SECT193R2 =      5,
     TLS_SECT233K1 =      6,
     TLS_SECT233R1 =      7,
     TLS_SECT239K1 =      8,
     TLS_SECT283K1 =      9,
     TLS_SECT283R1 =     10,
     TLS_SECT409K1 =     11,
     TLS_SECT409R1 =     12,
     TLS_SECT571K1 =     13,
     TLS_SECT571R1 =     14,
     TLS_SECP160K1 =     15,
     TLS_SECP160R1 =     16,
     TLS_SECP160R2 =     17,
     TLS_SECP192K1 =     18,
     TLS_SECP192R1 =     19,
     TLS_SECP224K1 =     20,
     TLS_SECP224R1 =     21,
     TLS_SECP256K1 =     22,
     TLS_SECP256R1 =     23,
     TLS_SECP384R1 =     24,
     TLS_SECP521R1 =     25,
 };
enum tls_signature_algorithm_t
TLS SignatureAlgorithm identifiers
Enumerator
TLS_SIG_RSA
TLS_SIG_DSA
TLS_SIG_ECDSA
Definition at line 281 of file tls_crypto.h.
{
     TLS_SIG_RSA =       1,
     TLS_SIG_DSA =       2,
     TLS_SIG_ECDSA =     3,
 };
Function Documentation
tls_crypto_t* tls_crypto_create (tls_t * tls, tls_cache_t * cache)
Create a tls_crypto instance.
Parameters
tls TLS stack
cache TLS session cache
Returns
TLS crypto helper
See header
Definition at line 1778 of file tls_crypto.c.
References build_cipher_suite_list(), cache(), credential_factory_t::create_builder_enumerator, CRED_PUBLIC_KEY, library_t::creds, ecdsa, FALSE, tls_t::get_purpose, INIT, KEY_ECDSA, KEY_RSA, lib, rsa, subtype, tls, TLS_PURPOSE_EAP_PEAP, TLS_PURPOSE_EAP_TLS, TLS_PURPOSE_EAP_TTLS, TLS_PURPOSE_GENERIC, TLS_PURPOSE_GENERIC_NULLOK, TRUE, and type.
Referenced by tls_create().
 {
     private_tls_crypto_t *this;
     enumerator_t *enumerator;
     credential_type_t type;
     int subtype;
     INIT(this,
         .public = {
             .get_cipher_suites = _get_cipher_suites,
             .select_cipher_suite = _select_cipher_suite,
             .get_dh_group = _get_dh_group,
             .get_signature_algorithms = _get_signature_algorithms,
             .create_ec_enumerator = _create_ec_enumerator,
             .set_protection = _set_protection,
             .append_handshake = _append_handshake,
             .sign = _sign,
             .verify = _verify,
             .sign_handshake = _sign_handshake,
             .verify_handshake = _verify_handshake,
             .calculate_finished = _calculate_finished,
             .derive_secrets = _derive_secrets,
             .resume_session = _resume_session,
             .get_session = _get_session,
             .change_cipher = _change_cipher,
             .get_eap_msk = _get_eap_msk,
             .destroy = _destroy,
         },
         .tls = tls,
         .cache = cache,
     );
     enumerator = lib->creds->create_builder_enumerator(lib->creds);
     while (enumerator->enumerate(enumerator, &type, &subtype))
     {
         if (type == CRED_PUBLIC_KEY)
         {
             switch (subtype)
             {
                 case KEY_RSA:
                     this->rsa = TRUE;
                     break;
                 case KEY_ECDSA:
                     this->ecdsa = TRUE;
                     break;
                 default:
                     break;
             }
         }
     }
     enumerator->destroy(enumerator);
     switch (tls->get_purpose(tls))
     {
         case TLS_PURPOSE_EAP_TLS:
             /* MSK PRF ASCII constant label according to EAP-TLS RFC 5216 */
             this->msk_label = "client EAP encryption";
             build_cipher_suite_list(this, FALSE);
             break;
         case TLS_PURPOSE_EAP_PEAP:
             this->msk_label = "client EAP encryption";
             build_cipher_suite_list(this, TRUE);
             break;
         case TLS_PURPOSE_EAP_TTLS:
             /* MSK PRF ASCII constant label according to EAP-TTLS RFC 5281 */
             this->msk_label = "ttls keying material";
             build_cipher_suite_list(this, TRUE);
             break;
         case TLS_PURPOSE_GENERIC:
             build_cipher_suite_list(this, TRUE);
             break;
         case TLS_PURPOSE_GENERIC_NULLOK:
             build_cipher_suite_list(this, FALSE);
             break;
         default:
             break;
     }
     return &this->public;
 }
int tls_crypto_get_supported_suites (bool null, tls_cipher_suite_t ** out)
Get a list of all supported TLS cipher suites.
Parameters
null include supported NULL encryption suites
suites pointer to allocated suites array, to free(), or NULL
Returns
number of suites supported
See header.
Definition at line 1861 of file tls_crypto.c.
References count, countof, filter_null_suites(), filter_unsupported_suites(), and suite_algs_t::suite.
Referenced by socket_suite_create(), and test_tls().
 {
     suite_algs_t suites[countof(suite_algs)];
     int count = countof(suite_algs), i;
     /* initialize copy of suite list */
     for (i = 0; i < count; i++)
     {
         suites[i] = suite_algs[i];
     }
     filter_unsupported_suites(suites, &count);
     if (!null)
     {
         filter_null_suites(suites, &count);
     }
     if (out)
     {
         *out = calloc(count, sizeof(tls_cipher_suite_t));
         for (i = 0; i < count; i++)
         {
             (*out)[i] = suites[i].suite;
         }
     }
     return count;
 }
Variable Documentation
enum_name_t* tls_ansi_point_format_names
Enum names for tls_ansi_point_format_t.
Referenced by process_ec_key_exchange(), and process_key_exchange_dhe().
enum_name_t* tls_cipher_suite_names
Enum names for tls_cipher_suite_t
Referenced by build_cipher_suite_list(), filter_specific_config_suites(), process_client_hello(), process_server_hello(), and test_tls().
enum_name_t* tls_client_certificate_type_names
Enum names for tls_client_certificate_type_t
enum_name_t* tls_ec_point_format_names
Enum names for tls_ec_point_format_t.
enum_name_t* tls_ecc_curve_type_names
Enum names for tls_ecc_curve_type_t
Referenced by process_ec_key_exchange().
enum_name_t* tls_hash_algorithm_names
Enum names for tls_hash_algorithm_t
Referenced by METHOD().
enum_name_t* tls_named_curve_names
Enum names for tls_named_curve_t
Referenced by process_ec_key_exchange(), and send_server_key_exchange().
enum_name_t* tls_signature_algorithm_names
Enum names for tls_signature_algorithm_t
Referenced by METHOD().