strongSwan: dnscert_t Struct Reference
dnscert_t Struct Reference
dnscert
#include "dnscert.h"
Public Attributes
dnscert_type_t(* get_cert_type)(dnscert_t *this)
u_int16_t(* get_key_tag)(dnscert_t *this)
dnscert_algorithm_t(* get_algorithm)(dnscert_t *this)
chunk_t(* get_certificate)(dnscert_t *this)
void(* destroy)(dnscert_t *this)
Detailed Description
DNS CERT RR as defined in RFC 4398.
The CERT resource record (RR) has the structure given below. Its RR type code is 37.
                 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | type | key tag | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | algorithm | / +------------—+ certificate or CRL / / / +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-|
Definition at line 105 of file dnscert.h.
Member Data Documentation
void(* dnscert_t::destroy)(dnscert_t *this)
Destroy the DNSCERT.
Definition at line 149 of file dnscert.h.
Referenced by METHOD().
dnscert_algorithm_t(* dnscert_t::get_algorithm)(dnscert_t *this)
Get the algorithm.
The "algorithm" determines the format of the public key field of the DNS CERT.
Returns
algorithm
Definition at line 132 of file dnscert.h.
dnscert_type_t(* dnscert_t::get_cert_type)(dnscert_t *this)
Get the type of the certificate body.
The certificate "type" determines the format of the body of the CERT data.
Returns
certificate type
Definition at line 115 of file dnscert.h.
Referenced by METHOD().
chunk_t(* dnscert_t::get_certificate)(dnscert_t *this)
Get the content of the certificate field as chunk.
The format of the certificate depends on the type.
The data pointed by the chunk is still owned by the DNSCERT. Clone it if necessary.
Returns
certificate field as chunk
Definition at line 144 of file dnscert.h.
Referenced by METHOD().
u_int16_t(* dnscert_t::get_key_tag)(dnscert_t *this)
Get the tag of the key part of the CERT.
Returns
keytag
Definition at line 122 of file dnscert.h.
The documentation for this struct was generated from the following file:
dnscert.h