strongSwan: sa_payload_t Struct Reference
sa_payload_t Struct Reference
sa_payload
#include "sa_payload.h"
Public Attributes
payload_t payload_interface
linked_list_t *(* get_proposals)(sa_payload_t *this)
linked_list_t *(* get_ipcomp_proposals)(sa_payload_t *this, u_int16_t *cpi)
u_int32_t(* get_lifetime)(sa_payload_t *this)
u_int64_t(* get_lifebytes)(sa_payload_t *this)
auth_method_t(* get_auth_method)(sa_payload_t *this)
ipsec_mode_t(* get_encap_mode)(sa_payload_t *this, bool *udp)
enumerator_t *(* create_substructure_enumerator)(sa_payload_t *this)
void(* destroy)(sa_payload_t *this)
Detailed Description
Class representing an IKEv1 or IKEv2 SA Payload.
The SA Payload format is described in RFC section 3.3.
Definition at line 39 of file sa_payload.h.
Member Data Documentation
enumerator_t*(* sa_payload_t::create_substructure_enumerator)(sa_payload_t *this)
Create an enumerator over all proposal substructures.
Returns
enumerator over proposal_substructure_t
Definition at line 96 of file sa_payload.h.
Referenced by set_byte().
void(* sa_payload_t::destroy)(sa_payload_t *this)
Destroys an sa_payload_t object.
Definition at line 101 of file sa_payload.h.
Referenced by METHOD().
auth_method_t(* sa_payload_t::get_auth_method)(sa_payload_t *this)
Get the first authentication method from the proposal (IKEv1 only).
Returns
auth method, or AUTH_NONE
Definition at line 81 of file sa_payload.h.
Referenced by METHOD(), and use_certs().
ipsec_mode_t(* sa_payload_t::get_encap_mode)(sa_payload_t *this, bool *udp)
Get the (first) encapsulation mode from a proposal (IKEv1 only).
Parameters
udp set to TRUE if UDP encapsulation used
Returns
ipsec encapsulation mode
Definition at line 89 of file sa_payload.h.
Referenced by METHOD().
linked_list_t*(* sa_payload_t::get_ipcomp_proposals)(sa_payload_t *this, u_int16_t *cpi)
Gets the proposals from the first proposal in this payload with IPComp enabled (IKEv1 only).
Parameters
cpi the CPI of the first IPComp (sub)proposal
Returns
a list containing proposal_ts
Definition at line 60 of file sa_payload.h.
Referenced by METHOD().
u_int64_t(* sa_payload_t::get_lifebytes)(sa_payload_t *this)
Get the (shortest) life duration of a proposal (IKEv1 only).
Returns
life duration, in bytes
Definition at line 74 of file sa_payload.h.
Referenced by apply_lifetimes().
u_int32_t(* sa_payload_t::get_lifetime)(sa_payload_t *this)
Get the (shortest) lifetime of a proposal (IKEv1 only).
Returns
lifetime, in seconds
Definition at line 67 of file sa_payload.h.
Referenced by apply_lifetimes(), and METHOD().
linked_list_t*(* sa_payload_t::get_proposals)(sa_payload_t *this)
Gets the proposals in this payload as a list.
Returns
a list containing proposal_ts
Definition at line 51 of file sa_payload.h.
Referenced by METHOD(), process_auth_request(), and process_payloads().
payload_t sa_payload_t::payload_interface
The payload_t interface.
Definition at line 44 of file sa_payload.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
sa_payload.h