strongSwan: vendor_id_payload
vendor_id_payload
payloads
Classes
struct vendor_id_payload_t
Typedefs
typedef struct vendor_id_payload_t vendor_id_payload_t
Functions
vendor_id_payload_t * vendor_id_payload_create (payload_type_t type)
vendor_id_payload_t * vendor_id_payload_create_data (payload_type_t type, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct vendor_id_payload_t vendor_id_payload_t
Definition at line 25 of file vendor_id_payload.h.
Function Documentation
vendor_id_payload_t* vendor_id_payload_create (payload_type_t type)
Creates an empty Vendor ID payload for IKEv1 or IKEv2.
@param type PLV2_VENDOR_ID or PLV1_VENDOR_ID
Returns
vendor ID payload
Definition at line 192 of file vendor_id_payload.c.
References chunk_empty, and vendor_id_payload_create_data().
Referenced by payload_create().
 {
     return vendor_id_payload_create_data(type, chunk_empty);
 }
vendor_id_payload_t* vendor_id_payload_create_data (payload_type_t type, chunk_t data)
Creates a vendor ID payload using a chunk of data
Parameters
type PLV2_VENDOR_ID or PLV1_VENDOR_ID
data data to use in vendor ID payload, gets owned by payload
Returns
vendor ID payload
Definition at line 161 of file vendor_id_payload.c.
References data, INIT, chunk_t::len, PL_NONE, and type.
Referenced by build(), METHOD(), and vendor_id_payload_create().
 {
     private_vendor_id_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_data = _get_data,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this) + data.len,
         .data = data,
         .type = type,
     );
     return &this->public;
 }