strongSwan: certexpire_listener.c File Reference
certexpire_listener.c File Reference
#include "certexpire_listener.h"
#include <daemon.h>
Classes
struct private_certexpire_listener_t
Typedefs
typedef struct
private_certexpire_listener_t private_certexpire_listener_t
Functions
METHOD (listener_t, authorize, bool, private_certexpire_listener_t *this, ike_sa_t *ike_sa, bool final, bool *success)
METHOD (certexpire_listener_t, destroy, void, private_certexpire_listener_t *this)
certexpire_listener_t * certexpire_listener_create (certexpire_export_t *export)
Typedef Documentation
typedef struct private_certexpire_listener_t private_certexpire_listener_t
Definition at line 20 of file certexpire_listener.c.
Function Documentation
METHOD (listener_t , authorize , bool , private_certexpire_listener_t * this, ike_sa_t * ike_sa, bool final, bool * success)
Definition at line 38 of file certexpire_listener.c.
References AUTH_RULE_CA_CERT, AUTH_RULE_IM_CERT, AUTH_RULE_SUBJECT_CERT, cert, ike_sa_t::create_auth_cfg_enumerator, auth_cfg_t::create_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, export(), FALSE, auth_cfg_t::get, linked_list_t::insert_last, linked_list_create(), and TRUE.
 {
     enumerator_t *rounds, *enumerator;
     certificate_t *cert, *ca = NULL;
     linked_list_t *trustchain;
     auth_cfg_t *auth;
     auth_rule_t rule;
     /* Check all rounds in final hook, as local authentication data are
      * not completely available after round-invocation. */
     if (!final)
     {
         return TRUE;
     }
     /* collect local certificates */
     trustchain = linked_list_create();
     rounds = ike_sa->create_auth_cfg_enumerator(ike_sa, TRUE);
     while (rounds->enumerate(rounds, &auth))
     {
         cert = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
         if (cert)
         {
             trustchain->insert_last(trustchain, cert);
             enumerator = auth->create_enumerator(auth);
             while (enumerator->enumerate(enumerator, &rule, &cert))
             {
                 if (rule == AUTH_RULE_IM_CERT)
                 {
                     trustchain->insert_last(trustchain, cert);
                 }
                 if (rule == AUTH_RULE_CA_CERT)
                 {
                     /* the last CA cert is the one used in the trustchain.
                      * Previous CA certificates have been received as cert
                      * requests. */
                     ca = cert;
                 }
             }
             enumerator->destroy(enumerator);
             if (ca)
             {
                 trustchain->insert_last(trustchain, ca);
             }
         }
     }
     rounds->destroy(rounds);
     this->export->add(this->export, trustchain, TRUE);
     trustchain->destroy(trustchain);
     /* collect remote certificates */
     trustchain = linked_list_create();
     rounds = ike_sa->create_auth_cfg_enumerator(ike_sa, FALSE);
     while (rounds->enumerate(rounds, &auth))
     {
         cert = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
         if (cert)
         {
             trustchain->insert_last(trustchain, cert);
             enumerator = auth->create_enumerator(auth);
             while (enumerator->enumerate(enumerator, &rule, &cert))
             {
                 if (rule == AUTH_RULE_IM_CERT)
                 {
                     trustchain->insert_last(trustchain, cert);
                 }
             }
             enumerator->destroy(enumerator);
             cert = auth->get(auth, AUTH_RULE_CA_CERT);
             if (cert)
             {
                 trustchain->insert_last(trustchain, cert);
             }
         }
     }
     rounds->destroy(rounds);
     this->export->add(this->export, trustchain, FALSE);
     trustchain->destroy(trustchain);
     return TRUE;
 }
METHOD (certexpire_listener_t , destroy , void , private_certexpire_listener_t * this)
Definition at line 124 of file certexpire_listener.c.
References free().
 {
     free(this);
 }