strongSwan: aesni_key
aesni_key
aesni
Classes
struct aesni_key_t
Macros
#define AES_BLOCK_SIZE 16
Typedefs
typedef struct aesni_key_t aesni_key_t
Functions
aesni_key_t * aesni_key_create (bool encrypt, chunk_t key)
Detailed Description
Macro Definition Documentation
#define AES_BLOCK_SIZE 16
AES block size, in bytes
Definition at line 31 of file aesni_key.h.
Typedef Documentation
typedef struct aesni_key_t aesni_key_t
Definition at line 33 of file aesni_key.h.
Function Documentation
aesni_key_t* aesni_key_create (bool encrypt, chunk_t key)
Create a AESNI key schedule instance.
Parameters
encrypt TRUE for encryption schedule, FALSE for decryption
key non-expanded crypto key, 16, 24 or 32 bytes
Returns
key schedule, NULL on invalid key size
See header
Definition at line 253 of file aesni_key.c.
References AES128_ROUNDS, AES192_ROUNDS, AES256_ROUNDS, AES_BLOCK_SIZE, expand128(), expand192(), expand256(), INIT_EXTRA_ALIGN, chunk_t::len, chunk_t::ptr, and reverse_key().
Referenced by METHOD().
 {
     private_aesni_key_t *this;
     int rounds;
     switch (key.len)
     {
         case 16:
             rounds = AES128_ROUNDS;
             break;
         case 24:
             rounds = AES192_ROUNDS;
             break;
         case 32:
             rounds = AES256_ROUNDS;
             break;
         default:
             return NULL;
     }
     INIT_EXTRA_ALIGN(this, (rounds + 1) * AES_BLOCK_SIZE, sizeof(__m128i),
         .public = {
             .destroy = _destroy,
             .rounds = rounds,
         },
     );
     switch (key.len)
     {
         case 16:
             expand128((__m128i*)key.ptr, this->public.schedule);
             break;
         case 24:
             expand192((__m128i*)key.ptr, this->public.schedule);
             break;
         case 32:
             expand256((__m128i*)key.ptr, this->public.schedule);
             break;
         default:
             break;
     }
     if (!encrypt)
     {
         reverse_key(&this->public);
     }
     return &this->public;
 }