strongSwan: kernel_pfkey_ipsec.c File Reference
kernel_pfkey_ipsec.c File Reference
#include <stdint.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <linux/pfkeyv2.h>
#include <linux/ipsec.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include "kernel_pfkey_ipsec.h"
#include <hydra.h>
#include <utils/debug.h>
#include <networking/host.h>
#include <collections/linked_list.h>
#include <collections/hashtable.h>
#include <threading/mutex.h>
Classes
struct private_kernel_pfkey_ipsec_t
struct exclude_route_t
struct route_entry_t
struct ipsec_sa_t
struct policy_sa_t
struct policy_sa_in_t
struct policy_entry_t
struct pfkey_msg_t
struct kernel_algorithm_t
Macros
#define SADB_X_AALG_SHA2_256HMAC SADB_X_AALG_SHA2_256
#define SADB_X_AALG_SHA2_384HMAC SADB_X_AALG_SHA2_384
#define SADB_X_AALG_SHA2_512HMAC SADB_X_AALG_SHA2_512
#define SADB_X_EALG_AESCBC SADB_X_EALG_AES
#define SADB_X_EALG_CASTCBC SADB_X_EALG_CAST128CBC
#define SOL_IP IPPROTO_IP
#define SOL_IPV6 IPPROTO_IPV6
#define IP_IPSEC_POLICY 16
#define IPV6_IPSEC_POLICY 34
#define UDP_ENCAP 100
#define UDP_ENCAP_ESPINUDP 2
#define SOL_UDP IPPROTO_UDP
#define PRIO_BASE 384
#define PFKEY_BUFFER_SIZE 4096
#define PFKEY_ALIGNMENT 8
#define PFKEY_ALIGN(len) (((len) + PFKEY_ALIGNMENT - 1) & ~(PFKEY_ALIGNMENT - 1))
#define PFKEY_LEN(len) ((PFKEY_ALIGN(len) / PFKEY_ALIGNMENT))
#define PFKEY_USER_LEN(len) ((len) * PFKEY_ALIGNMENT)
#define PFKEY_EXT_ADD(msg, ext) ((msg)->sadb_msg_len += ((struct sadb_ext*)ext)->sadb_ext_len)
#define PFKEY_EXT_ADD_NEXT(msg) ((struct sadb_ext*)(((char*)(msg)) + PFKEY_USER_LEN((msg)->sadb_msg_len)))
#define PFKEY_EXT_COPY(msg, ext) (PFKEY_EXT_ADD(msg, memcpy(PFKEY_EXT_ADD_NEXT(msg), ext, PFKEY_USER_LEN(((struct sadb_ext*)ext)->sadb_ext_len))))
#define PFKEY_EXT_NEXT(ext) ((struct sadb_ext*)(((char*)(ext)) + PFKEY_USER_LEN(((struct sadb_ext*)ext)->sadb_ext_len)))
#define PFKEY_EXT_NEXT_LEN(ext, len) ((len) -= (ext)->sadb_ext_len, PFKEY_EXT_NEXT(ext))
#define PFKEY_EXT_OK(ext, len)
#define END_OF_LIST -1
Typedefs
typedef struct
private_kernel_pfkey_ipsec_t private_kernel_pfkey_ipsec_t
typedef struct exclude_route_t exclude_route_t
typedef struct route_entry_t route_entry_t
typedef struct ipsec_sa_t ipsec_sa_t
typedef struct policy_sa_t policy_sa_t
typedef struct policy_sa_in_t policy_sa_in_t
typedef struct policy_entry_t policy_entry_t
typedef struct pfkey_msg_t pfkey_msg_t
typedef struct kernel_algorithm_t kernel_algorithm_t
Functions
static void exclude_route_destroy (exclude_route_t *this)
static void route_entry_destroy (route_entry_t *this)
static bool route_entry_equals (route_entry_t *a, route_entry_t *b)
static u_int ipsec_sa_hash (ipsec_sa_t *sa)
static bool ipsec_sa_equals (ipsec_sa_t *sa, ipsec_sa_t *other_sa)
static ipsec_sa_t * ipsec_sa_create (private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, ipsec_sa_cfg_t *cfg)
static void ipsec_sa_destroy (private_kernel_pfkey_ipsec_t *this, ipsec_sa_t *sa)
static policy_sa_t * policy_sa_create (private_kernel_pfkey_ipsec_t *this, policy_dir_t dir, policy_type_t type, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, ipsec_sa_cfg_t *cfg)
static void policy_sa_destroy (policy_sa_t *policy, policy_dir_t *dir, private_kernel_pfkey_ipsec_t *this)
static policy_entry_t * create_policy_entry (traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t dir)
static void policy_entry_destroy (policy_entry_t *policy, private_kernel_pfkey_ipsec_t *this)
static bool policy_entry_equals (policy_entry_t *current, policy_entry_t *policy)
static bool policy_entry_match_byindex (policy_entry_t *current, u_int32_t *index)
static u_int32_t get_priority (policy_entry_t *policy, policy_priority_t prio)
ENUM (sadb_ext_type_names, SADB_EXT_RESERVED, SADB_EXT_MAX,"SADB_EXT_RESERVED","SADB_EXT_SA","SADB_EXT_LIFETIME_CURRENT","SADB_EXT_LIFETIME_HARD","SADB_EXT_LIFETIME_SOFT","SADB_EXT_ADDRESS_SRC","SADB_EXT_ADDRESS_DST","SADB_EXT_ADDRESS_PROXY","SADB_EXT_KEY_AUTH","SADB_EXT_KEY_ENCRYPT","SADB_EXT_IDENTITY_SRC","SADB_EXT_IDENTITY_DST","SADB_EXT_SENSITIVITY","SADB_EXT_PROPOSAL","SADB_EXT_SUPPORTED_AUTH","SADB_EXT_SUPPORTED_ENCRYPT","SADB_EXT_SPIRANGE","SADB_X_EXT_KMPRIVATE","SADB_X_EXT_POLICY","SADB_X_EXT_SA2","SADB_X_EXT_NAT_T_TYPE","SADB_X_EXT_NAT_T_SPORT","SADB_X_EXT_NAT_T_DPORT","SADB_X_EXT_NAT_T_OA","SADB_X_EXT_SEC_CTX","SADB_X_EXT_KMADDRESS")
static u_int8_t proto2satype (u_int8_t proto)
static u_int8_t satype2proto (u_int8_t satype)
static u_int8_t mode2kernel (ipsec_mode_t mode)
static u_int8_t dir2kernel (policy_dir_t dir)
static u_int16_t type2kernel (policy_type_t type)
static int lookup_algorithm (transform_type_t type, int ikev2)
static void set_port (sockaddr_t *addr, u_int16_t port)
static size_t hostcpy (void *dest, host_t *host, bool include_port)
static void add_addr_ext (struct sadb_msg *msg, host_t *host, u_int16_t type, u_int8_t proto, u_int8_t prefixlen, bool include_port)
static void add_anyaddr_ext (struct sadb_msg *msg, int family, u_int8_t type)
static traffic_selector_t * sadb_address2ts (struct sadb_address *address)
static status_t parse_pfkey_message (struct sadb_msg *msg, pfkey_msg_t *out)
static status_t pfkey_send_socket (private_kernel_pfkey_ipsec_t *this, int socket, struct sadb_msg *in, struct sadb_msg **out, size_t *out_len)
static status_t pfkey_send (private_kernel_pfkey_ipsec_t *this, struct sadb_msg *in, struct sadb_msg **out, size_t *out_len)
static void process_acquire (private_kernel_pfkey_ipsec_t *this, struct sadb_msg *msg)
static void process_expire (private_kernel_pfkey_ipsec_t *this, struct sadb_msg *msg)
static bool receive_events (private_kernel_pfkey_ipsec_t *this, int fd, watcher_event_t event)
static status_t get_spi_internal (private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, u_int8_t proto, u_int32_t min, u_int32_t max, u_int32_t *spi)
METHOD (kernel_ipsec_t, get_spi, status_t, private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
METHOD (kernel_ipsec_t, get_cpi, status_t, private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, u_int16_t *cpi)
METHOD (kernel_ipsec_t, add_sa, status_t, private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t *src_ts, linked_list_t *dst_ts)
METHOD (kernel_ipsec_t, update_sa, status_t, private_kernel_pfkey_ipsec_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
METHOD (kernel_ipsec_t, query_sa, status_t, private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
METHOD (kernel_ipsec_t, del_sa, status_t, private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
METHOD (kernel_ipsec_t, flush_sas, status_t, private_kernel_pfkey_ipsec_t *this)
static void add_exclude_route (private_kernel_pfkey_ipsec_t *this, route_entry_t *route, host_t *src, host_t *dst)
static void remove_exclude_route (private_kernel_pfkey_ipsec_t *this, route_entry_t *route)
static bool install_route (private_kernel_pfkey_ipsec_t *this, policy_entry_t *policy, policy_sa_in_t *in)
static status_t add_policy_internal (private_kernel_pfkey_ipsec_t *this, policy_entry_t *policy, policy_sa_t *mapping, bool update)
METHOD (kernel_ipsec_t, add_policy, status_t, private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_ipsec_t, query_policy, status_t, private_kernel_pfkey_ipsec_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, mark_t mark, time_t *use_time)
METHOD (kernel_ipsec_t, del_policy, status_t, private_kernel_pfkey_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t prio)
METHOD (kernel_ipsec_t, flush_policies, status_t, private_kernel_pfkey_ipsec_t *this)
static status_t register_pfkey_socket (private_kernel_pfkey_ipsec_t *this, u_int8_t satype)
METHOD (kernel_ipsec_t, bypass_socket, bool, private_kernel_pfkey_ipsec_t *this, int fd, int family)
METHOD (kernel_ipsec_t, enable_udp_decap, bool, private_kernel_pfkey_ipsec_t *this, int fd, int family, u_int16_t port)
METHOD (kernel_ipsec_t, destroy, void, private_kernel_pfkey_ipsec_t *this)
kernel_pfkey_ipsec_t * kernel_pfkey_ipsec_create ()
Variables
struct sadb_ext * reserved
struct sadb_sa * sa
struct sadb_lifetime * lft_current
struct sadb_lifetime * lft_hard
struct sadb_lifetime * lft_soft
struct sadb_address * src
struct sadb_address * dst
struct sadb_address * proxy
struct sadb_key * key_auth
struct sadb_key * key_encr
struct sadb_ident * id_src
struct sadb_ident * id_dst
struct sadb_sens * sensitivity
struct sadb_prop * proposal
struct sadb_supported * supported_auth
struct sadb_supported * supported_encr
struct sadb_spirange * spirange
struct sadb_x_kmprivate * x_kmprivate
struct sadb_x_policy * x_policy
struct sadb_x_sa2 * x_sa2
struct sadb_x_nat_t_type * x_natt_type
struct sadb_x_nat_t_port * x_natt_sport
struct sadb_x_nat_t_port * x_natt_dport
struct sadb_address * x_natt_oa
struct sadb_x_sec_ctx * x_sec_ctx
struct sadb_x_kmaddress * x_kmaddress
static kernel_algorithm_t encryption_algs []
static kernel_algorithm_t integrity_algs []
static kernel_algorithm_t compression_algs []
Macro Definition Documentation
#define END_OF_LIST -1
Definition at line 829 of file kernel_pfkey_ipsec.c.
Referenced by lookup_algorithm().
#define IP_IPSEC_POLICY 16
from linux/in.h
Definition at line 122 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
#define IPV6_IPSEC_POLICY 34
missing on uclibc
Definition at line 127 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
#define PFKEY_ALIGN (len) (((len) + PFKEY_ALIGNMENT - 1) & ~(PFKEY_ALIGNMENT - 1))
aligns len to 64 bits
Definition at line 164 of file kernel_pfkey_ipsec.c.
#define PFKEY_ALIGNMENT 8
PF_KEY messages are 64 bit aligned
Definition at line 162 of file kernel_pfkey_ipsec.c.
Referenced by pfkey_send_socket(), and receive_events().
#define PFKEY_BUFFER_SIZE 4096
buffer size for PF_KEY messages
Definition at line 159 of file kernel_pfkey_ipsec.c.
Referenced by add_policy_internal(), get_spi_internal(), METHOD(), pfkey_send_socket(), receive_events(), and register_pfkey_socket().
#define PFKEY_EXT_ADD (msg, ext) ((msg)->sadb_msg_len += ((struct sadb_ext*)ext)->sadb_ext_len)
given a PF_KEY message header and an extension this updates the length in the header
Definition at line 171 of file kernel_pfkey_ipsec.c.
Referenced by add_addr_ext(), add_anyaddr_ext(), add_policy_internal(), get_spi_internal(), and METHOD().
#define PFKEY_EXT_ADD_NEXT (msg) ((struct sadb_ext*)(((char*)(msg)) + PFKEY_USER_LEN((msg)->sadb_msg_len)))
given a PF_KEY message header this returns a pointer to the next extension
Definition at line 173 of file kernel_pfkey_ipsec.c.
Referenced by add_addr_ext(), add_anyaddr_ext(), add_policy_internal(), get_spi_internal(), and METHOD().
#define PFKEY_EXT_COPY (msg, ext) (PFKEY_EXT_ADD(msg, memcpy(PFKEY_EXT_ADD_NEXT(msg), ext, PFKEY_USER_LEN(((struct sadb_ext*)ext)->sadb_ext_len))))
copy an extension and append it to a PF_KEY message
Definition at line 175 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
#define PFKEY_EXT_NEXT (ext) ((struct sadb_ext*)(((char*)(ext)) + PFKEY_USER_LEN(((struct sadb_ext*)ext)->sadb_ext_len)))
given a PF_KEY extension this returns a pointer to the next extension
Definition at line 177 of file kernel_pfkey_ipsec.c.
#define PFKEY_EXT_NEXT_LEN (ext, len) ((len) -= (ext)->sadb_ext_len, PFKEY_EXT_NEXT(ext))
given a PF_KEY extension this returns a pointer to the next extension also updates len (len in 64 bit words)
Definition at line 179 of file kernel_pfkey_ipsec.c.
Referenced by parse_pfkey_message().
#define PFKEY_EXT_OK (ext, len)
Value:
((len) >= PFKEY_LEN(sizeof(struct sadb_ext)) && \
                (ext)->sadb_ext_len >= PFKEY_LEN(sizeof(struct sadb_ext)) && \
                (ext)->sadb_ext_len <= (len))
true if ext has a valid length and len is large enough to contain ext (assuming len in 64 bit words)
Definition at line 181 of file kernel_pfkey_ipsec.c.
#define PFKEY_LEN (len) ((PFKEY_ALIGN(len) / PFKEY_ALIGNMENT))
calculates the properly padded length in 64 bit chunks
Definition at line 166 of file kernel_pfkey_ipsec.c.
Referenced by add_addr_ext(), add_anyaddr_ext(), add_policy_internal(), get_spi_internal(), METHOD(), parse_pfkey_message(), pfkey_send_socket(), receive_events(), and register_pfkey_socket().
#define PFKEY_USER_LEN (len) ((len) * PFKEY_ALIGNMENT)
calculates user mode length i.e. in bytes
Definition at line 168 of file kernel_pfkey_ipsec.c.
Referenced by pfkey_send_socket().
#define PRIO_BASE 384
base priority for installed policies
Definition at line 145 of file kernel_pfkey_ipsec.c.
Referenced by get_priority().
#define SADB_X_AALG_SHA2_256HMAC SADB_X_AALG_SHA2_256
non linux specific
Definition at line 96 of file kernel_pfkey_ipsec.c.
#define SADB_X_AALG_SHA2_384HMAC SADB_X_AALG_SHA2_384
Definition at line 97 of file kernel_pfkey_ipsec.c.
#define SADB_X_AALG_SHA2_512HMAC SADB_X_AALG_SHA2_512
Definition at line 98 of file kernel_pfkey_ipsec.c.
#define SADB_X_EALG_AESCBC SADB_X_EALG_AES
Definition at line 102 of file kernel_pfkey_ipsec.c.
#define SADB_X_EALG_CASTCBC SADB_X_EALG_CAST128CBC
Definition at line 106 of file kernel_pfkey_ipsec.c.
#define SOL_IP IPPROTO_IP
Definition at line 116 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
#define SOL_IPV6 IPPROTO_IPV6
Definition at line 117 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
#define SOL_UDP IPPROTO_UDP
Definition at line 141 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
#define UDP_ENCAP 100
Definition at line 132 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
#define UDP_ENCAP_ESPINUDP 2
Definition at line 136 of file kernel_pfkey_ipsec.c.
Referenced by METHOD().
Typedef Documentation
typedef struct exclude_route_t exclude_route_t
Definition at line 243 of file kernel_pfkey_ipsec.c.
typedef struct ipsec_sa_t ipsec_sa_t
Definition at line 319 of file kernel_pfkey_ipsec.c.
typedef struct kernel_algorithm_t kernel_algorithm_t
Definition at line 812 of file kernel_pfkey_ipsec.c.
typedef struct pfkey_msg_t pfkey_msg_t
Definition at line 623 of file kernel_pfkey_ipsec.c.
typedef struct policy_entry_t policy_entry_t
Definition at line 477 of file kernel_pfkey_ipsec.c.
typedef struct policy_sa_in_t policy_sa_in_t
Definition at line 403 of file kernel_pfkey_ipsec.c.
typedef struct policy_sa_t policy_sa_t
Definition at line 402 of file kernel_pfkey_ipsec.c.
typedef struct private_kernel_pfkey_ipsec_t private_kernel_pfkey_ipsec_t
Definition at line 185 of file kernel_pfkey_ipsec.c.
typedef struct route_entry_t route_entry_t
Definition at line 270 of file kernel_pfkey_ipsec.c.
Function Documentation
static void add_addr_ext (struct sadb_msg * msg, host_t * host, u_int16_t type, u_int8_t proto, u_int8_t prefixlen, bool include_port) static
add a host to the given sadb_msg
Definition at line 975 of file kernel_pfkey_ipsec.c.
References addr, hostcpy(), len, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, proto, sadb_address::sadb_address_exttype, sadb_address::sadb_address_len, sadb_address::sadb_address_prefixlen, sadb_address::sadb_address_proto, and type.
Referenced by add_policy_internal(), get_spi_internal(), and METHOD().
 {
     struct sadb_address *addr = (struct sadb_address*)PFKEY_EXT_ADD_NEXT(msg);
     size_t len;
     addr->sadb_address_exttype = type;
     addr->sadb_address_proto = proto;
     addr->sadb_address_prefixlen = prefixlen;
     len = hostcpy(addr + 1, host, include_port);
     addr->sadb_address_len = PFKEY_LEN(sizeof(*addr) + len);
     PFKEY_EXT_ADD(msg, addr);
 }
static void add_anyaddr_ext (struct sadb_msg * msg, int family, u_int8_t type) static
adds an empty address extension to the given sadb_msg
Definition at line 992 of file kernel_pfkey_ipsec.c.
References addr, family, len, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, sadb_address::sadb_address_exttype, sadb_address::sadb_address_len, and type.
Referenced by METHOD().
 {
     socklen_t len = (family == AF_INET) ? sizeof(struct sockaddr_in) :
                                           sizeof(struct sockaddr_in6);
     struct sadb_address *addr = (struct sadb_address*)PFKEY_EXT_ADD_NEXT(msg);
     addr->sadb_address_exttype = type;
     sockaddr_t *saddr = (sockaddr_t*)(addr + 1);
     saddr->sa_family = family;
 #ifdef HAVE_STRUCT_SOCKADDR_SA_LEN
     saddr->sa_len = len;
 #endif
     addr->sadb_address_len = PFKEY_LEN(sizeof(*addr) + len);
     PFKEY_EXT_ADD(msg, addr);
 }
static void add_exclude_route (private_kernel_pfkey_ipsec_t * this, route_entry_t * route, host_t * src, host_t * dst) static
Add an explicit exclude route to a routing entry
Definition at line 2124 of file kernel_pfkey_ipsec.c.
References kernel_interface_t::add_route, host_t::clone, DBG1, DBG2, DBG_KNL, enumerator_t::destroy, host_t::destroy, exclude_route_t::dst, enumerator_t::enumerate, route_entry_t::exclude, free(), host_t::get_address, host_t::get_family, kernel_interface_t::get_interface, kernel_interface_t::get_nexthop, hydra, INIT, host_t::ip_equals, hydra_t::kernel_interface, exclude_route_t::refs, src, and SUCCESS.
Referenced by install_route().
 {
     enumerator_t *enumerator;
     exclude_route_t *exclude;
     host_t *gtw;
     enumerator = this->excludes->create_enumerator(this->excludes);
     while (enumerator->enumerate(enumerator, &exclude))
     {
         if (dst->ip_equals(dst, exclude->dst))
         {
             route->exclude = exclude;
             exclude->refs++;
         }
     }
     enumerator->destroy(enumerator);
     if (!route->exclude)
     {
         DBG2(DBG_KNL, "installing new exclude route for %H src %H", dst, src);
         gtw = hydra->kernel_interface->get_nexthop(hydra->kernel_interface,
                                                    dst, -1, NULL);
         if (gtw)
         {
             char *if_name = NULL;
             if (hydra->kernel_interface->get_interface(
                                     hydra->kernel_interface, src, &if_name) &&
                 hydra->kernel_interface->add_route(hydra->kernel_interface,
                                     dst->get_address(dst),
                                     dst->get_family(dst) == AF_INET ? 32 : 128,
                                     gtw, src, if_name) == SUCCESS)
             {
                 INIT(exclude,
                     .dst = dst->clone(dst),
                     .src = src->clone(src),
                     .gtw = gtw->clone(gtw),
                     .refs = 1,
                 );
                 route->exclude = exclude;
                 this->excludes->insert_last(this->excludes, exclude);
             }
             else
             {
                 DBG1(DBG_KNL, "installing exclude route for %H failed", dst);
             }
             gtw->destroy(gtw);
             free(if_name);
         }
         else
         {
             DBG1(DBG_KNL, "gateway lookup for for %H failed", dst);
         }
     }
 }
static status_t add_policy_internal (private_kernel_pfkey_ipsec_t * this, policy_entry_t * policy, policy_sa_t * mapping, bool update) static
Add or update a policy in the kernel.
Note: The mutex has to be locked when entering this function.
Definition at line 2361 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), ipsec_sa_t::cfg, DBG1, DBG2, DBG_KNL, dir2kernel(), policy_entry_t::direction, policy_entry_t::dst, ipsec_sa_t::dst, ipsec_sa_cfg_t::esp, FAILED, FALSE, free(), hostcpy(), policy_entry_t::index, install_route(), ipsec_sa_cfg_t::ipcomp, IPCOMP_NONE, ipsec, IPSEC_LEVEL_UNIQUE, IPSEC_LEVEL_USE, len, mutex_t::lock, policy_entry_t::mask, memset, ipsec_sa_cfg_t::mode, mode2kernel(), MODE_TRANSPORT, MODE_TUNNEL, msg, mutex, policy_entry_t::net, out, parse_pfkey_message(), PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, pfkey_send(), POLICY_IN, POLICY_IPSEC, POLICY_OUT, policy_sa_t::priority, policy_entry_t::proto, req(), ipsec_sa_cfg_t::reqid, request(), response, policy_sa_t::sa, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, SADB_EXT_LIFETIME_HARD, sadb_lifetime::sadb_lifetime_addtime, sadb_lifetime::sadb_lifetime_exttype, sadb_lifetime::sadb_lifetime_len, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, SADB_X_EXT_POLICY, sadb_x_ipsecrequest::sadb_x_ipsecrequest_len, sadb_x_ipsecrequest::sadb_x_ipsecrequest_level, sadb_x_ipsecrequest::sadb_x_ipsecrequest_mode, sadb_x_ipsecrequest::sadb_x_ipsecrequest_proto, sadb_x_ipsecrequest::sadb_x_ipsecrequest_reqid, sadb_x_policy::sadb_x_policy_dir, sadb_x_policy::sadb_x_policy_exttype, sadb_x_policy::sadb_x_policy_id, sadb_x_policy::sadb_x_policy_len, sadb_x_policy::sadb_x_policy_priority, sadb_x_policy::sadb_x_policy_type, SADB_X_SPDADD, SADB_X_SPDUPDATE, policy_entry_t::src, ipsec_sa_t::src, status, strerror, SUCCESS, ipsec_sa_cfg_t::transform, TRUE, policy_sa_t::type, type2kernel(), mutex_t::unlock, ipsec_sa_cfg_t::use, and pfkey_msg_t::x_policy.
Referenced by METHOD().
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_x_policy *pol;
     struct sadb_x_ipsecrequest *req;
     ipsec_sa_t *ipsec = mapping->sa;
     pfkey_msg_t response;
     size_t len;
     ipsec_mode_t proto_mode;
     status_t status;
     memset(&request, 0, sizeof(request));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = update ? SADB_X_SPDUPDATE : SADB_X_SPDADD;
     msg->sadb_msg_satype = 0;
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     pol = (struct sadb_x_policy*)PFKEY_EXT_ADD_NEXT(msg);
     pol->sadb_x_policy_exttype = SADB_X_EXT_POLICY;
     pol->sadb_x_policy_len = PFKEY_LEN(sizeof(struct sadb_x_policy));
     pol->sadb_x_policy_id = 0;
     pol->sadb_x_policy_dir = dir2kernel(policy->direction);
     pol->sadb_x_policy_type = type2kernel(mapping->type);
 #ifdef HAVE_STRUCT_SADB_X_POLICY_SADB_X_POLICY_PRIORITY
     pol->sadb_x_policy_priority = mapping->priority;
 #endif
     /* one or more sadb_x_ipsecrequest extensions are added to the
      * sadb_x_policy extension */
     proto_mode = ipsec->cfg.mode;
     req = (struct sadb_x_ipsecrequest*)(pol + 1);
     if (ipsec->cfg.ipcomp.transform != IPCOMP_NONE)
     {
         req->sadb_x_ipsecrequest_proto = IPPROTO_COMP;
         /* !!! the length here MUST be in octets instead of 64 bit words */
         req->sadb_x_ipsecrequest_len = sizeof(struct sadb_x_ipsecrequest);
         req->sadb_x_ipsecrequest_mode = mode2kernel(ipsec->cfg.mode);
         req->sadb_x_ipsecrequest_reqid = ipsec->cfg.reqid;
         req->sadb_x_ipsecrequest_level = (policy->direction == POLICY_OUT) ?
                                           IPSEC_LEVEL_UNIQUE : IPSEC_LEVEL_USE;
         if (ipsec->cfg.mode == MODE_TUNNEL)
         {
             len = hostcpy(req + 1, ipsec->src, FALSE);
             req->sadb_x_ipsecrequest_len += len;
             len = hostcpy((char*)(req + 1) + len, ipsec->dst, FALSE);
             req->sadb_x_ipsecrequest_len += len;
             /* use transport mode for other SAs */
             proto_mode = MODE_TRANSPORT;
         }
         pol->sadb_x_policy_len += PFKEY_LEN(req->sadb_x_ipsecrequest_len);
         req = (struct sadb_x_ipsecrequest*)((char*)(req) +
                                             req->sadb_x_ipsecrequest_len);
     }
     req->sadb_x_ipsecrequest_proto = ipsec->cfg.esp.use ? IPPROTO_ESP
                                                         : IPPROTO_AH;
     /* !!! the length here MUST be in octets instead of 64 bit words */
     req->sadb_x_ipsecrequest_len = sizeof(struct sadb_x_ipsecrequest);
     req->sadb_x_ipsecrequest_mode = mode2kernel(proto_mode);
     req->sadb_x_ipsecrequest_reqid = ipsec->cfg.reqid;
     req->sadb_x_ipsecrequest_level = IPSEC_LEVEL_UNIQUE;
     if (proto_mode == MODE_TUNNEL)
     {
         len = hostcpy(req + 1, ipsec->src, FALSE);
         req->sadb_x_ipsecrequest_len += len;
         len = hostcpy((char*)(req + 1) + len, ipsec->dst, FALSE);
         req->sadb_x_ipsecrequest_len += len;
     }
     pol->sadb_x_policy_len += PFKEY_LEN(req->sadb_x_ipsecrequest_len);
     PFKEY_EXT_ADD(msg, pol);
     add_addr_ext(msg, policy->src.net, SADB_EXT_ADDRESS_SRC, policy->src.proto,
                  policy->src.mask, TRUE);
     add_addr_ext(msg, policy->dst.net, SADB_EXT_ADDRESS_DST, policy->dst.proto,
                  policy->dst.mask, TRUE);
 #ifdef __FreeBSD__
     {   /* on FreeBSD a lifetime has to be defined to be able to later query
          * the current use time. */
         struct sadb_lifetime *lft;
         lft = (struct sadb_lifetime*)PFKEY_EXT_ADD_NEXT(msg);
         lft->sadb_lifetime_exttype = SADB_EXT_LIFETIME_HARD;
         lft->sadb_lifetime_len = PFKEY_LEN(sizeof(struct sadb_lifetime));
         lft->sadb_lifetime_addtime = LONG_MAX;
         PFKEY_EXT_ADD(msg, lft);
     }
 #endif
     this->mutex->unlock(this->mutex);
     status = pfkey_send(this, msg, &out, &len);
     if (status == SUCCESS && !update && out->sadb_msg_errno == EEXIST)
     {
         DBG1(DBG_KNL, "policy already exists, try to update it");
         free(out);
         msg->sadb_msg_type = SADB_X_SPDUPDATE;
         status = pfkey_send(this, msg, &out, &len);
     }
     if (status != SUCCESS)
     {
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to %s policy: %s (%d)",
                        update ? "update" : "add", strerror(out->sadb_msg_errno),
                        out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     else if (parse_pfkey_message(out, &response) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to %s policy: parsing response from kernel "
                       "failed", update ? "update" : "add");
         free(out);
         return FAILED;
     }
     /* we try to find the policy again and update the kernel index */
     this->mutex->lock(this->mutex);
     if (this->policies->find_first(this->policies, NULL,
                                   (void**)&policy) != SUCCESS)
     {
         DBG2(DBG_KNL, "unable to update index, the policy is already gone, "
                       "ignoring");
         this->mutex->unlock(this->mutex);
         free(out);
         return SUCCESS;
     }
     policy->index = response.x_policy->sadb_x_policy_id;
     free(out);
     /* install a route, if:
      * - this is an inbound policy (to just get one for each child)
      * - we are in tunnel mode or install a bypass policy
      * - routing is not disabled via strongswan.conf
      */
     if (policy->direction == POLICY_IN && this->install_routes &&
         (mapping->type != POLICY_IPSEC || ipsec->cfg.mode != MODE_TRANSPORT))
     {
         install_route(this, policy, (policy_sa_in_t*)mapping);
     }
     this->mutex->unlock(this->mutex);
     return SUCCESS;
 }
static policy_entry_t* create_policy_entry (traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t dir) static
Create a policy_entry_t object
Definition at line 509 of file kernel_pfkey_ipsec.c.
References policy_entry_t::dst, host_t::get_port, traffic_selector_t::get_protocol, INIT, IPSEC_PROTO_ANY, policy_entry_t::mask, max, policy_entry_t::net, port, policy_entry_t::proto, proto, host_t::set_port, policy_entry_t::src, traffic_selector_t::to_subnet, traffic_selector_icmp_code(), and traffic_selector_icmp_type().
Referenced by METHOD().
 {
     policy_entry_t *policy;
     INIT(policy,
         .direction = dir,
     );
     u_int16_t port;
     u_int8_t proto;
     src_ts->to_subnet(src_ts, &policy->src.net, &policy->src.mask);
     dst_ts->to_subnet(dst_ts, &policy->dst.net, &policy->dst.mask);
     /* src or dest proto may be "any" (0), use more restrictive one */
     proto = max(src_ts->get_protocol(src_ts), dst_ts->get_protocol(dst_ts));
     /* map the ports to ICMP type/code how the Linux kernel expects them, that
      * is, type in src, code in dst */
     if (proto == IPPROTO_ICMP || proto == IPPROTO_ICMPV6)
     {
         port = max(policy->src.net->get_port(policy->src.net),
                    policy->dst.net->get_port(policy->dst.net));
         policy->src.net->set_port(policy->src.net,
                                   traffic_selector_icmp_type(port));
         policy->dst.net->set_port(policy->dst.net,
                                   traffic_selector_icmp_code(port));
     }
     else if (!proto)
     {
         proto = IPSEC_PROTO_ANY;
     }
     policy->src.proto = policy->dst.proto = proto;
     return policy;
 }
static u_int8_t dir2kernel (policy_dir_t dir) static
convert the general policy direction to the one defined in ipsec.h
Definition at line 756 of file kernel_pfkey_ipsec.c.
References IPSEC_DIR_FWD, IPSEC_DIR_INBOUND, IPSEC_DIR_INVALID, IPSEC_DIR_OUTBOUND, POLICY_FWD, POLICY_IN, and POLICY_OUT.
Referenced by add_policy_internal(), and METHOD().
 {
     switch (dir)
     {
         case POLICY_IN:
             return IPSEC_DIR_INBOUND;
         case POLICY_OUT:
             return IPSEC_DIR_OUTBOUND;
 #ifdef HAVE_IPSEC_DIR_FWD
         case POLICY_FWD:
             return IPSEC_DIR_FWD;
 #endif
         default:
             return IPSEC_DIR_INVALID;
     }
 }
ENUM (sadb_ext_type_names , SADB_EXT_RESERVED , SADB_EXT_MAX , "SADB_EXT_RESERVED" , "SADB_EXT_SA" , "SADB_EXT_LIFETIME_CURRENT" , "SADB_EXT_LIFETIME_HARD" , "SADB_EXT_LIFETIME_SOFT" , "SADB_EXT_ADDRESS_SRC" , "SADB_EXT_ADDRESS_DST" , "SADB_EXT_ADDRESS_PROXY" , "SADB_EXT_KEY_AUTH" , "SADB_EXT_KEY_ENCRYPT" , "SADB_EXT_IDENTITY_SRC" , "SADB_EXT_IDENTITY_DST" , "SADB_EXT_SENSITIVITY" , "SADB_EXT_PROPOSAL" , "SADB_EXT_SUPPORTED_AUTH" , "SADB_EXT_SUPPORTED_ENCRYPT" , "SADB_EXT_SPIRANGE" , "SADB_X_EXT_KMPRIVATE" , "SADB_X_EXT_POLICY" , "SADB_X_EXT_SA2" , "SADB_X_EXT_NAT_T_TYPE" , "SADB_X_EXT_NAT_T_SPORT" , "SADB_X_EXT_NAT_T_DPORT" , "SADB_X_EXT_NAT_T_OA" , "SADB_X_EXT_SEC_CTX" , "SADB_X_EXT_KMADDRESS")
static void exclude_route_destroy (exclude_route_t * this) static
clean up a route exclude entry
Definition at line 262 of file kernel_pfkey_ipsec.c.
References dst, free(), and src.
Referenced by remove_exclude_route().
 {
     this->dst->destroy(this->dst);
     this->src->destroy(this->src);
     this->gtw->destroy(this->gtw);
     free(this);
 }
static u_int32_t get_priority (policy_entry_t * policy, policy_priority_t prio) inline static
Calculate the priority of a policy
Definition at line 594 of file kernel_pfkey_ipsec.c.
References policy_entry_t::dst, host_t::get_port, IPSEC_PROTO_ANY, policy_entry_t::mask, policy_entry_t::net, POLICY_PRIORITY_DEFAULT, POLICY_PRIORITY_FALLBACK, POLICY_PRIORITY_PASS, POLICY_PRIORITY_ROUTED, PRIO_BASE, policy_entry_t::proto, and policy_entry_t::src.
Referenced by METHOD().
 {
     u_int32_t priority = PRIO_BASE;
     switch (prio)
     {
         case POLICY_PRIORITY_FALLBACK:
             priority <<= 1;
             /* fall-through */
         case POLICY_PRIORITY_ROUTED:
             priority <<= 1;
             /* fall-through */
         case POLICY_PRIORITY_DEFAULT:
             priority <<= 1;
             /* fall-trough */
         case POLICY_PRIORITY_PASS:
             break;
     }
     /* calculate priority based on selector size, small size = high prio */
     priority -= policy->src.mask;
     priority -= policy->dst.mask;
     priority <<= 2; /* make some room for the two flags */
     priority += policy->src.net->get_port(policy->src.net) ||
                 policy->dst.net->get_port(policy->dst.net) ?
                 0 : 2;
     priority += policy->src.proto != IPSEC_PROTO_ANY ? 0 : 1;
     return priority;
 }
static status_t get_spi_internal (private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, u_int8_t proto, u_int32_t min, u_int32_t max, u_int32_t * spi) static
Get an SPI for a specific protocol from the kernel.
Definition at line 1523 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), DBG1, DBG_KNL, FAILED, FALSE, free(), len, max, memset, min, msg, out, parse_pfkey_message(), PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, pfkey_send(), proto2satype(), request(), response, pfkey_msg_t::sa, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, SADB_EXT_SPIRANGE, SADB_GETSPI, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, sadb_sa::sadb_sa_spi, sadb_spirange::sadb_spirange_exttype, sadb_spirange::sadb_spirange_len, sadb_spirange::sadb_spirange_max, sadb_spirange::sadb_spirange_min, strerror, and SUCCESS.
Referenced by METHOD().
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_spirange *range;
     pfkey_msg_t response;
     u_int32_t received_spi = 0;
     size_t len;
     memset(&request, 0, sizeof(request));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_GETSPI;
     msg->sadb_msg_satype = proto2satype(proto);
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     add_addr_ext(msg, src, SADB_EXT_ADDRESS_SRC, 0, 0, FALSE);
     add_addr_ext(msg, dst, SADB_EXT_ADDRESS_DST, 0, 0, FALSE);
     range = (struct sadb_spirange*)PFKEY_EXT_ADD_NEXT(msg);
     range->sadb_spirange_exttype = SADB_EXT_SPIRANGE;
     range->sadb_spirange_len = PFKEY_LEN(sizeof(struct sadb_spirange));
     range->sadb_spirange_min = min;
     range->sadb_spirange_max = max;
     PFKEY_EXT_ADD(msg, range);
     if (pfkey_send(this, msg, &out, &len) == SUCCESS)
     {
         if (out->sadb_msg_errno)
         {
             DBG1(DBG_KNL, "allocating SPI failed: %s (%d)",
                            strerror(out->sadb_msg_errno), out->sadb_msg_errno);
         }
         else if (parse_pfkey_message(out, &response) == SUCCESS)
         {
             received_spi = response.sa->sadb_sa_spi;
         }
         free(out);
     }
     if (received_spi == 0)
     {
         return FAILED;
     }
     *spi = received_spi;
     return SUCCESS;
 }
static size_t hostcpy (void * dest, host_t * host, bool include_port) static
Copy a host_t as sockaddr_t to the given memory location.
Returns
the number of bytes copied
Definition at line 956 of file kernel_pfkey_ipsec.c.
References addr, dest, host_t::get_sockaddr, host_t::get_sockaddr_len, len, memcpy, and set_port().
Referenced by add_addr_ext(), and add_policy_internal().
 {
     sockaddr_t *addr = host->get_sockaddr(host), *dest_addr = dest;
     socklen_t *len = host->get_sockaddr_len(host);
     memcpy(dest, addr, *len);
 #ifdef HAVE_STRUCT_SOCKADDR_SA_LEN
     dest_addr->sa_len = *len;
 #endif
     if (!include_port)
     {
         set_port(dest_addr, 0);
     }
     return *len;
 }
static bool install_route (private_kernel_pfkey_ipsec_t * this, policy_entry_t * policy, policy_sa_in_t * in) static
Try to install a route to the given inbound policy
Definition at line 2237 of file kernel_pfkey_ipsec.c.
References add_exclude_route(), kernel_interface_t::add_route, ALREADY_DONE, chunk_clone, DBG1, DBG2, DBG_KNL, kernel_interface_t::del_route, policy_entry_t::direction, ipsec_sa_t::dst, dst, route_entry_t::dst_net, policy_sa_in_t::dst_ts, FALSE, route_entry_t::gateway, policy_sa_in_t::generic, host_t::get_address, kernel_interface_t::get_address_by_ts, kernel_interface_t::get_features, kernel_interface_t::get_interface, kernel_interface_t::get_nexthop, host, hydra, route_entry_t::if_name, traffic_selector_t::includes, INIT, host_t::is_anyaddr, traffic_selector_t::is_host, hydra_t::kernel_interface, KERNEL_REQUIRE_EXCLUDE_ROUTE, policy_entry_t::mask, policy_entry_t::net, policy_dir_names, route_entry_t::prefixlen, remove_exclude_route(), policy_entry_t::route, route_entry_destroy(), route_entry_equals(), policy_sa_t::sa, policy_entry_t::src, ipsec_sa_t::src, src, route_entry_t::src_ip, policy_sa_in_t::src_ts, SUCCESS, and TRUE.
Referenced by add_policy_internal().
 {
     route_entry_t *route, *old;
     host_t *host, *src, *dst;
     bool is_virtual;
     if (hydra->kernel_interface->get_address_by_ts(hydra->kernel_interface,
                                     in->dst_ts, &host, &is_virtual) != SUCCESS)
     {
         return FALSE;
     }
     /* switch src/dst, as we handle an IN policy */
     src = in->generic.sa->dst;
     dst = in->generic.sa->src;
     INIT(route,
         .prefixlen = policy->src.mask,
         .src_ip = host,
         .dst_net = chunk_clone(policy->src.net->get_address(policy->src.net)),
     );
     if (!dst->is_anyaddr(dst))
     {
         route->gateway = hydra->kernel_interface->get_nexthop(
                                     hydra->kernel_interface, dst, -1, src);
         /* if the IP is virtual, we install the route over the interface it has
          * been installed on. Otherwise we use the interface we use for IKE, as
          * this is required for example on Linux. */
         if (is_virtual)
         {
             src = route->src_ip;
         }
     }
     else
     {   /* for shunt policies */
         route->gateway = hydra->kernel_interface->get_nexthop(
                                     hydra->kernel_interface, policy->src.net,
                                     policy->src.mask, route->src_ip);
         /* we don't have a source address, use the address we found */
         src = route->src_ip;
     }
     /* get interface for route, using source address */
     if (!hydra->kernel_interface->get_interface(hydra->kernel_interface,
                                                 src, &route->if_name))
     {
         route_entry_destroy(route);
         return FALSE;
     }
     if (policy->route)
     {
         old = policy->route;
         if (route_entry_equals(old, route))
         {   /* such a route already exists */
             route_entry_destroy(route);
             return TRUE;
         }
         /* uninstall previously installed route */
         if (hydra->kernel_interface->del_route(hydra->kernel_interface,
                                     old->dst_net, old->prefixlen, old->gateway,
                                     old->src_ip, old->if_name) != SUCCESS)
         {
             DBG1(DBG_KNL, "error uninstalling route installed with policy "
                  "%R === %R %N", in->src_ts, in->dst_ts,
                 policy_dir_names, policy->direction);
         }
         route_entry_destroy(old);
         policy->route = NULL;
     }
     /* if remote traffic selector covers the IKE peer, add an exclude route */
     if (hydra->kernel_interface->get_features(
                     hydra->kernel_interface) & KERNEL_REQUIRE_EXCLUDE_ROUTE)
     {
         if (in->src_ts->is_host(in->src_ts, dst))
         {
             DBG1(DBG_KNL, "can't install route for %R === %R %N, conflicts "
                  "with IKE traffic", in->src_ts, in->dst_ts, policy_dir_names,
                  policy->direction);
             route_entry_destroy(route);
             return FALSE;
         }
         if (in->src_ts->includes(in->src_ts, dst))
         {
             add_exclude_route(this, route, in->generic.sa->dst, dst);
         }
     }
     DBG2(DBG_KNL, "installing route: %R via %H src %H dev %s",
          in->src_ts, route->gateway, route->src_ip, route->if_name);
     switch (hydra->kernel_interface->add_route(hydra->kernel_interface,
                             route->dst_net, route->prefixlen, route->gateway,
                             route->src_ip, route->if_name))
     {
         case ALREADY_DONE:
             /* route exists, do not uninstall */
             remove_exclude_route(this, route);
             route_entry_destroy(route);
             return TRUE;
         case SUCCESS:
             /* cache the installed route */
             policy->route = route;
             return TRUE;
         default:
             DBG1(DBG_KNL, "installing route failed: %R via %H src %H dev %s",
                  in->src_ts, route->gateway, route->src_ip, route->if_name);
             remove_exclude_route(this, route);
             route_entry_destroy(route);
             return FALSE;
     }
 }
static ipsec_sa_t* ipsec_sa_create (private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, ipsec_sa_cfg_t * cfg) static
Allocate or reference an IPsec SA object
Definition at line 361 of file kernel_pfkey_ipsec.c.
References host_t::clone, ipsec_sa_t::dst, found, free(), INIT, ref_get(), ipsec_sa_t::refcount, sa, and ipsec_sa_t::src.
Referenced by policy_sa_create().
 {
     ipsec_sa_t *sa, *found;
     INIT(sa,
         .src = src,
         .dst = dst,
         .cfg = *cfg,
     );
     found = this->sas->get(this->sas, sa);
     if (!found)
     {
         sa->src = src->clone(src);
         sa->dst = dst->clone(dst);
         this->sas->put(this->sas, sa, sa);
     }
     else
     {
         free(sa);
         sa = found;
     }
     ref_get(&sa->refcount);
     return sa;
 }
static void ipsec_sa_destroy (private_kernel_pfkey_ipsec_t * this, ipsec_sa_t * sa) static
Release and destroy an IPsec SA object
Definition at line 390 of file kernel_pfkey_ipsec.c.
References DESTROY_IF, ipsec_sa_t::dst, free(), ref_put(), ipsec_sa_t::refcount, and ipsec_sa_t::src.
Referenced by policy_sa_destroy().
 {
     if (ref_put(&sa->refcount))
     {
         this->sas->remove(this->sas, sa);
         DESTROY_IF(sa->src);
         DESTROY_IF(sa->dst);
         free(sa);
     }
 }
static bool ipsec_sa_equals (ipsec_sa_t * sa, ipsec_sa_t * other_sa) static
Equality function for ipsec_sa_t objects
Definition at line 351 of file kernel_pfkey_ipsec.c.
References ipsec_sa_t::cfg, ipsec_sa_t::dst, host_t::ip_equals, memeq(), and ipsec_sa_t::src.
Referenced by kernel_pfkey_ipsec_create(), and METHOD().
 {
     return sa->src->ip_equals(sa->src, other_sa->src) &&
            sa->dst->ip_equals(sa->dst, other_sa->dst) &&
            memeq(&sa->cfg, &other_sa->cfg, sizeof(ipsec_sa_cfg_t));
 }
static u_int ipsec_sa_hash (ipsec_sa_t * sa) static
Hash function for ipsec_sa_t objects
Definition at line 341 of file kernel_pfkey_ipsec.c.
References ipsec_sa_t::cfg, chunk_from_thing, chunk_hash(), chunk_hash_inc(), ipsec_sa_t::dst, host_t::get_address, and ipsec_sa_t::src.
Referenced by kernel_pfkey_ipsec_create().
 {
     return chunk_hash_inc(sa->src->get_address(sa->src),
                           chunk_hash_inc(sa->dst->get_address(sa->dst),
                           chunk_hash(chunk_from_thing(sa->cfg))));
 }
static int lookup_algorithm (transform_type_t type, int ikev2) static
Look up a kernel algorithm ID and its key size
Definition at line 898 of file kernel_pfkey_ipsec.c.
References alg, COMPRESSION_ALGORITHM, compression_algs, ENCRYPTION_ALGORITHM, encryption_algs, END_OF_LIST, hydra, kernel_algorithm_t::ikev2, INTEGRITY_ALGORITHM, integrity_algs, kernel_algorithm_t::kernel, hydra_t::kernel_interface, list, and kernel_interface_t::lookup_algorithm.
Referenced by METHOD().
 {
     kernel_algorithm_t *list;
     u_int16_t alg = 0;
     switch (type)
     {
         case ENCRYPTION_ALGORITHM:
             list = encryption_algs;
             break;
         case INTEGRITY_ALGORITHM:
             list = integrity_algs;
             break;
         case COMPRESSION_ALGORITHM:
             list = compression_algs;
             break;
         default:
             return 0;
     }
     while (list->ikev2 != END_OF_LIST)
     {
         if (ikev2 == list->ikev2)
         {
             return list->kernel;
         }
         list++;
     }
     hydra->kernel_interface->lookup_algorithm(hydra->kernel_interface, ikev2,
                                               type, &alg, NULL);
     return alg;
 }
METHOD (kernel_ipsec_t , get_spi , status_t , private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, u_int8_t protocol, u_int32_t * spi)
Definition at line 1575 of file kernel_pfkey_ipsec.c.
References DBG1, DBG2, DBG_KNL, FAILED, get_spi_internal(), and SUCCESS.
 {
     if (get_spi_internal(this, src, dst, protocol,
                          0xc0000000, 0xcFFFFFFF, spi) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to get SPI");
         return FAILED;
     }
     DBG2(DBG_KNL, "got SPI %.8x", ntohl(*spi));
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , get_cpi , status_t , private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, u_int16_t * cpi)
Definition at line 1590 of file kernel_pfkey_ipsec.c.
References DBG1, DBG2, DBG_KNL, FAILED, get_spi_internal(), and SUCCESS.
 {
     u_int32_t received_spi = 0;
     DBG2(DBG_KNL, "getting CPI");
     if (get_spi_internal(this, src, dst, IPPROTO_COMP,
                          0x100, 0xEFFF, &received_spi) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to get CPI");
         return FAILED;
     }
     *cpi = htons((u_int16_t)ntohl(received_spi));
     DBG2(DBG_KNL, "got CPI %.4x", ntohs(*cpi));
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , add_sa , status_t , private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t * lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t * src_ts, linked_list_t * dst_ts)
Definition at line 1611 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), AUTH_UNDEFINED, lifetime_cfg_t::bytes, chunk_empty, COMPRESSION_ALGORITHM, DBG1, DBG2, DBG_KNL, ENCR_UNDEFINED, ENCRYPTION_ALGORITHM, encryption_algorithm_names, FAILED, FALSE, free(), host_t::get_port, INTEGRITY_ALGORITHM, integrity_algorithm_names, IPCOMP_NONE, key, chunk_t::len, len, lifetime_cfg_t::life, lookup_algorithm(), memcpy, memset, min, mode2kernel(), MODE_TRANSPORT, msg, out, lifetime_cfg_t::packets, PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, pfkey_send(), proto2satype(), chunk_t::ptr, lifetime_cfg_t::rekey, request(), sa, SADB_ADD, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, SADB_EXT_KEY_AUTH, SADB_EXT_KEY_ENCRYPT, SADB_EXT_LIFETIME_HARD, SADB_EXT_LIFETIME_SOFT, SADB_EXT_SA, sadb_key::sadb_key_bits, sadb_key::sadb_key_exttype, sadb_key::sadb_key_len, sadb_lifetime::sadb_lifetime_addtime, sadb_lifetime::sadb_lifetime_allocations, sadb_lifetime::sadb_lifetime_bytes, sadb_lifetime::sadb_lifetime_exttype, sadb_lifetime::sadb_lifetime_len, sadb_lifetime::sadb_lifetime_usetime, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, sadb_sa::sadb_sa_auth, sadb_sa::sadb_sa_encrypt, sadb_sa::sadb_sa_exttype, sadb_sa::sadb_sa_flags, sadb_sa::sadb_sa_len, sadb_sa::sadb_sa_replay, sadb_sa::sadb_sa_spi, SADB_X_EXT_SA2, sadb_x_sa2::sadb_x_sa2_exttype, sadb_x_sa2::sadb_x_sa2_len, sadb_x_sa2::sadb_x_sa2_mode, sadb_x_sa2::sadb_x_sa2_reqid, strerror, SUCCESS, and lifetime_cfg_t::time.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_sa *sa;
     struct sadb_x_sa2 *sa2;
     struct sadb_lifetime *lft;
     struct sadb_key *key;
     size_t len;
     /* if IPComp is used, we install an additional IPComp SA. if the cpi is 0
      * we are in the recursive call below */
     if (ipcomp != IPCOMP_NONE && cpi != 0)
     {
         lifetime_cfg_t lft = {{0,0,0},{0,0,0},{0,0,0}};
         add_sa(this, src, dst, htonl(ntohs(cpi)), IPPROTO_COMP, reqid, mark,
                tfc, &lft, ENCR_UNDEFINED, chunk_empty, AUTH_UNDEFINED,
                chunk_empty, mode, ipcomp, 0, 0, FALSE, FALSE, FALSE, inbound,
                update, NULL, NULL);
         ipcomp = IPCOMP_NONE;
         /* use transport mode ESP SA, IPComp uses tunnel mode */
         mode = MODE_TRANSPORT;
     }
     if (update)
     {
         /* As we didn't know the reqid during SPI allocation, we used reqid
          * zero. Unfortunately we can't SADB_UPDATE to the new reqid, hence we
          * have to delete the SPI allocation state manually. The reqid
          * selector does not count for that, therefore we have to delete
          * that state before installing the new SA to avoid deleting the
          * the new state after installing it. */
         mark_t zeromark = {0, 0};
         if (this->public.interface.del_sa(&this->public.interface,
                     src, dst, spi, protocol, 0, zeromark) != SUCCESS)
         {
             DBG1(DBG_KNL, "deleting SPI allocation SA failed");
         }
     }
     memset(&request, 0, sizeof(request));
     DBG2(DBG_KNL, "adding SAD entry with SPI %.8x and reqid {%u}",
                    ntohl(spi), reqid);
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_ADD;
     msg->sadb_msg_satype = proto2satype(protocol);
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
 #ifdef __APPLE__
     if (encap)
     {
         struct sadb_sa_2 *sa_2;
         sa_2 = (struct sadb_sa_2*)PFKEY_EXT_ADD_NEXT(msg);
         sa_2->sadb_sa_natt_port = dst->get_port(dst);
         sa = &sa_2->sa;
         sa->sadb_sa_flags |= SADB_X_EXT_NATT;
         len = sizeof(struct sadb_sa_2);
     }
     else
 #endif
     {
         sa = (struct sadb_sa*)PFKEY_EXT_ADD_NEXT(msg);
         len = sizeof(struct sadb_sa);
     }
     sa->sadb_sa_exttype = SADB_EXT_SA;
     sa->sadb_sa_len = PFKEY_LEN(len);
     sa->sadb_sa_spi = spi;
     if (protocol == IPPROTO_COMP)
     {
         sa->sadb_sa_encrypt = lookup_algorithm(COMPRESSION_ALGORITHM, ipcomp);
     }
     else
     {
         /* Linux interprets sadb_sa_replay as number of packets/bits in the
          * replay window, whereas on BSD it's the size of the window in bytes */
 #ifdef __linux__
         sa->sadb_sa_replay = min(replay_window, 32);
 #else
         sa->sadb_sa_replay = (replay_window + 7) / 8;
 #endif
         sa->sadb_sa_auth = lookup_algorithm(INTEGRITY_ALGORITHM, int_alg);
         sa->sadb_sa_encrypt = lookup_algorithm(ENCRYPTION_ALGORITHM, enc_alg);
     }
     PFKEY_EXT_ADD(msg, sa);
     sa2 = (struct sadb_x_sa2*)PFKEY_EXT_ADD_NEXT(msg);
     sa2->sadb_x_sa2_exttype = SADB_X_EXT_SA2;
     sa2->sadb_x_sa2_len = PFKEY_LEN(sizeof(struct sadb_spirange));
     sa2->sadb_x_sa2_mode = mode2kernel(mode);
     sa2->sadb_x_sa2_reqid = reqid;
     PFKEY_EXT_ADD(msg, sa2);
     add_addr_ext(msg, src, SADB_EXT_ADDRESS_SRC, 0, 0, FALSE);
     add_addr_ext(msg, dst, SADB_EXT_ADDRESS_DST, 0, 0, FALSE);
     lft = (struct sadb_lifetime*)PFKEY_EXT_ADD_NEXT(msg);
     lft->sadb_lifetime_exttype = SADB_EXT_LIFETIME_SOFT;
     lft->sadb_lifetime_len = PFKEY_LEN(sizeof(struct sadb_lifetime));
     lft->sadb_lifetime_allocations = lifetime->packets.rekey;
     lft->sadb_lifetime_bytes = lifetime->bytes.rekey;
     lft->sadb_lifetime_addtime = lifetime->time.rekey;
     lft->sadb_lifetime_usetime = 0; /* we only use addtime */
     PFKEY_EXT_ADD(msg, lft);
     lft = (struct sadb_lifetime*)PFKEY_EXT_ADD_NEXT(msg);
     lft->sadb_lifetime_exttype = SADB_EXT_LIFETIME_HARD;
     lft->sadb_lifetime_len = PFKEY_LEN(sizeof(struct sadb_lifetime));
     lft->sadb_lifetime_allocations = lifetime->packets.life;
     lft->sadb_lifetime_bytes = lifetime->bytes.life;
     lft->sadb_lifetime_addtime = lifetime->time.life;
     lft->sadb_lifetime_usetime = 0; /* we only use addtime */
     PFKEY_EXT_ADD(msg, lft);
     if (enc_alg != ENCR_UNDEFINED)
     {
         if (!sa->sadb_sa_encrypt)
         {
             DBG1(DBG_KNL, "algorithm %N not supported by kernel!",
                            encryption_algorithm_names, enc_alg);
             return FAILED;
         }
         DBG2(DBG_KNL, "  using encryption algorithm %N with key size %d",
                          encryption_algorithm_names, enc_alg, enc_key.len * 8);
         key = (struct sadb_key*)PFKEY_EXT_ADD_NEXT(msg);
         key->sadb_key_exttype = SADB_EXT_KEY_ENCRYPT;
         key->sadb_key_bits = enc_key.len * 8;
         key->sadb_key_len = PFKEY_LEN(sizeof(struct sadb_key) + enc_key.len);
         memcpy(key + 1, enc_key.ptr, enc_key.len);
         PFKEY_EXT_ADD(msg, key);
     }
     if (int_alg != AUTH_UNDEFINED)
     {
         if (!sa->sadb_sa_auth)
         {
             DBG1(DBG_KNL, "algorithm %N not supported by kernel!",
                            integrity_algorithm_names, int_alg);
             return FAILED;
         }
         DBG2(DBG_KNL, "  using integrity algorithm %N with key size %d",
                          integrity_algorithm_names, int_alg, int_key.len * 8);
         key = (struct sadb_key*)PFKEY_EXT_ADD_NEXT(msg);
         key->sadb_key_exttype = SADB_EXT_KEY_AUTH;
         key->sadb_key_bits = int_key.len * 8;
         key->sadb_key_len = PFKEY_LEN(sizeof(struct sadb_key) + int_key.len);
         memcpy(key + 1, int_key.ptr, int_key.len);
         PFKEY_EXT_ADD(msg, key);
     }
 #ifdef HAVE_NATT
     if (encap)
     {
         add_encap_ext(msg, src, dst);
     }
 #endif /*HAVE_NATT*/
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to add SAD entry with SPI %.8x", ntohl(spi));
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to add SAD entry with SPI %.8x: %s (%d)",
                 ntohl(spi), strerror(out->sadb_msg_errno), out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     free(out);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , update_sa , status_t , private_kernel_pfkey_ipsec_t * this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t * src, host_t * dst, host_t * new_src, host_t * new_dst, bool encap, bool new_encap, mark_t mark)
Definition at line 1799 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), add_anyaddr_ext(), DBG1, DBG2, DBG_KNL, pfkey_msg_t::dst, FAILED, FALSE, free(), host_t::get_family, host_t::get_port, host_t::ip_equals, pfkey_msg_t::key_auth, pfkey_msg_t::key_encr, len, pfkey_msg_t::lft_hard, pfkey_msg_t::lft_soft, memcpy, memset, msg, NOT_SUPPORTED, out, parse_pfkey_message(), PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_EXT_COPY, PFKEY_LEN, pfkey_send(), proto2satype(), request(), response, sa, pfkey_msg_t::sa, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, SADB_EXT_SA, SADB_GET, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, sadb_sa::sadb_sa_exttype, sadb_sa::sadb_sa_len, sadb_sa::sadb_sa_spi, SADB_UPDATE, pfkey_msg_t::src, strerror, SUCCESS, update_sa(), and pfkey_msg_t::x_sa2.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_sa *sa;
     pfkey_msg_t response;
     size_t len;
     /* we can't update the SA if any of the ip addresses have changed.
      * that's because we can't use SADB_UPDATE and by deleting and readding the
      * SA the sequence numbers would get lost */
     if (!src->ip_equals(src, new_src) ||
         !dst->ip_equals(dst, new_dst))
     {
         DBG1(DBG_KNL, "unable to update SAD entry with SPI %.8x: address "
                       "changes are not supported", ntohl(spi));
         return NOT_SUPPORTED;
     }
     /* if IPComp is used, we first update the IPComp SA */
     if (cpi)
     {
         update_sa(this, htonl(ntohs(cpi)), IPPROTO_COMP, 0,
                   src, dst, new_src, new_dst, FALSE, FALSE, mark);
     }
     memset(&request, 0, sizeof(request));
     DBG2(DBG_KNL, "querying SAD entry with SPI %.8x", ntohl(spi));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_GET;
     msg->sadb_msg_satype = proto2satype(protocol);
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     sa = (struct sadb_sa*)PFKEY_EXT_ADD_NEXT(msg);
     sa->sadb_sa_exttype = SADB_EXT_SA;
     sa->sadb_sa_len = PFKEY_LEN(sizeof(struct sadb_sa));
     sa->sadb_sa_spi = spi;
     PFKEY_EXT_ADD(msg, sa);
     /* the kernel wants a SADB_EXT_ADDRESS_SRC to be present even though
      * it is not used for anything. */
     add_anyaddr_ext(msg, dst->get_family(dst), SADB_EXT_ADDRESS_SRC);
     add_addr_ext(msg, dst, SADB_EXT_ADDRESS_DST, 0, 0, FALSE);
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to query SAD entry with SPI %.8x", ntohl(spi));
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to query SAD entry with SPI %.8x: %s (%d)",
                        ntohl(spi), strerror(out->sadb_msg_errno),
                        out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     else if (parse_pfkey_message(out, &response) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to query SAD entry with SPI %.8x: parsing "
                       "response from kernel failed", ntohl(spi));
         free(out);
         return FAILED;
     }
     DBG2(DBG_KNL, "updating SAD entry with SPI %.8x from %#H..%#H to %#H..%#H",
                    ntohl(spi), src, dst, new_src, new_dst);
     memset(&request, 0, sizeof(request));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_UPDATE;
     msg->sadb_msg_satype = proto2satype(protocol);
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
 #ifdef __APPLE__
     {
         struct sadb_sa_2 *sa_2;
         sa_2 = (struct sadb_sa_2*)PFKEY_EXT_ADD_NEXT(msg);
         sa_2->sa.sadb_sa_len = PFKEY_LEN(sizeof(struct sadb_sa_2));
         memcpy(&sa_2->sa, response.sa, sizeof(struct sadb_sa));
         if (encap)
         {
             sa_2->sadb_sa_natt_port = new_dst->get_port(new_dst);
             sa_2->sa.sadb_sa_flags |= SADB_X_EXT_NATT;
         }
     }
 #else
     PFKEY_EXT_COPY(msg, response.sa);
 #endif
     PFKEY_EXT_COPY(msg, response.x_sa2);
     PFKEY_EXT_COPY(msg, response.src);
     PFKEY_EXT_COPY(msg, response.dst);
     PFKEY_EXT_COPY(msg, response.lft_soft);
     PFKEY_EXT_COPY(msg, response.lft_hard);
     if (response.key_encr)
     {
         PFKEY_EXT_COPY(msg, response.key_encr);
     }
     if (response.key_auth)
     {
         PFKEY_EXT_COPY(msg, response.key_auth);
     }
 #ifdef HAVE_NATT
     if (new_encap)
     {
         add_encap_ext(msg, new_src, new_dst);
     }
 #endif /*HAVE_NATT*/
     free(out);
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to update SAD entry with SPI %.8x", ntohl(spi));
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to update SAD entry with SPI %.8x: %s (%d)",
                        ntohl(spi), strerror(out->sadb_msg_errno),
                        out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     free(out);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , query_sa , status_t , private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t * bytes, u_int64_t * packets, time_t * time)
Definition at line 1941 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), DBG1, DBG2, DBG_KNL, FAILED, FALSE, free(), len, pfkey_msg_t::lft_current, memset, msg, out, parse_pfkey_message(), PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, pfkey_send(), proto2satype(), request(), response, sa, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, SADB_EXT_SA, SADB_GET, sadb_lifetime::sadb_lifetime_allocations, sadb_lifetime::sadb_lifetime_bytes, sadb_lifetime::sadb_lifetime_usetime, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, sadb_sa::sadb_sa_exttype, sadb_sa::sadb_sa_len, sadb_sa::sadb_sa_spi, strerror, and SUCCESS.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_sa *sa;
     pfkey_msg_t response;
     size_t len;
     memset(&request, 0, sizeof(request));
     DBG2(DBG_KNL, "querying SAD entry with SPI %.8x", ntohl(spi));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_GET;
     msg->sadb_msg_satype = proto2satype(protocol);
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     sa = (struct sadb_sa*)PFKEY_EXT_ADD_NEXT(msg);
     sa->sadb_sa_exttype = SADB_EXT_SA;
     sa->sadb_sa_len = PFKEY_LEN(sizeof(struct sadb_sa));
     sa->sadb_sa_spi = spi;
     PFKEY_EXT_ADD(msg, sa);
     /* the Linux Kernel doesn't care for the src address, but other systems do
      * (e.g. FreeBSD)
      */
     add_addr_ext(msg, src, SADB_EXT_ADDRESS_SRC, 0, 0, FALSE);
     add_addr_ext(msg, dst, SADB_EXT_ADDRESS_DST, 0, 0, FALSE);
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to query SAD entry with SPI %.8x", ntohl(spi));
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to query SAD entry with SPI %.8x: %s (%d)",
                        ntohl(spi), strerror(out->sadb_msg_errno),
                        out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     else if (parse_pfkey_message(out, &response) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to query SAD entry with SPI %.8x", ntohl(spi));
         free(out);
         return FAILED;
     }
     if (bytes)
     {
         *bytes = response.lft_current->sadb_lifetime_bytes;
     }
     if (packets)
     {
         /* at least on Linux and FreeBSD this contains the number of packets */
         *packets = response.lft_current->sadb_lifetime_allocations;
     }
     if (time)
     {
 #ifdef __APPLE__
         /* OS X uses the "last" time of use in usetime */
         *time = response.lft_current->sadb_lifetime_usetime;
 #else /* !__APPLE__ */
         /* on Linux, sadb_lifetime_usetime is set to the "first" time of use,
          * which is actually correct according to PF_KEY. We have to query
          * policies for the last usetime. */
         *time = 0;
 #endif /* !__APPLE__ */
     }
     free(out);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , del_sa , status_t , private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Definition at line 2019 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), DBG1, DBG2, DBG_KNL, FAILED, FALSE, free(), len, memset, msg, out, PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, pfkey_send(), proto2satype(), request(), sa, SADB_DELETE, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, SADB_EXT_SA, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, sadb_sa::sadb_sa_exttype, sadb_sa::sadb_sa_len, sadb_sa::sadb_sa_spi, strerror, and SUCCESS.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_sa *sa;
     size_t len;
     /* if IPComp was used, we first delete the additional IPComp SA */
     if (cpi)
     {
         del_sa(this, src, dst, htonl(ntohs(cpi)), IPPROTO_COMP, 0, mark);
     }
     memset(&request, 0, sizeof(request));
     DBG2(DBG_KNL, "deleting SAD entry with SPI %.8x", ntohl(spi));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_DELETE;
     msg->sadb_msg_satype = proto2satype(protocol);
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     sa = (struct sadb_sa*)PFKEY_EXT_ADD_NEXT(msg);
     sa->sadb_sa_exttype = SADB_EXT_SA;
     sa->sadb_sa_len = PFKEY_LEN(sizeof(struct sadb_sa));
     sa->sadb_sa_spi = spi;
     PFKEY_EXT_ADD(msg, sa);
     /* the Linux Kernel doesn't care for the src address, but other systems do
      * (e.g. FreeBSD)
      */
     add_addr_ext(msg, src, SADB_EXT_ADDRESS_SRC, 0, 0, FALSE);
     add_addr_ext(msg, dst, SADB_EXT_ADDRESS_DST, 0, 0, FALSE);
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to delete SAD entry with SPI %.8x", ntohl(spi));
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to delete SAD entry with SPI %.8x: %s (%d)",
                        ntohl(spi), strerror(out->sadb_msg_errno),
                        out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     DBG2(DBG_KNL, "deleted SAD entry with SPI %.8x", ntohl(spi));
     free(out);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , flush_sas , status_t , private_kernel_pfkey_ipsec_t * this)
Definition at line 2075 of file kernel_pfkey_ipsec.c.
References countof, DBG1, DBG2, DBG_KNL, FAILED, free(), len, memset, msg, name, out, PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_LEN, pfkey_send(), proto, request(), SADB_FLUSH, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, SADB_SATYPE_AH, SADB_SATYPE_ESP, SADB_X_SATYPE_IPCOMP, strerror, and SUCCESS.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct {
         u_int8_t proto;
         char *name;
     } protos[] = {
         { SADB_SATYPE_AH, "AH" },
         { SADB_SATYPE_ESP, "ESP" },
         { SADB_X_SATYPE_IPCOMP, "IPComp" },
     };
     size_t len;
     int i;
     memset(&request, 0, sizeof(request));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_FLUSH;
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     for (i = 0; i < countof(protos); i++)
     {
         DBG2(DBG_KNL, "flushing all %s SAD entries", protos[i].name);
         msg->sadb_msg_satype = protos[i].proto;
         if (pfkey_send(this, msg, &out, &len) != SUCCESS)
         {
             DBG1(DBG_KNL, "unable to flush %s SAD entries", protos[i].name);
             return FAILED;
         }
         else if (out->sadb_msg_errno)
         {
             DBG1(DBG_KNL, "unable to flush %s SAD entries: %s (%d)",
                  protos[i].name, strerror(out->sadb_msg_errno),
                  out->sadb_msg_errno);
             free(out);
             return FAILED;
         }
         free(out);
     }
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , add_policy , status_t , private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 2516 of file kernel_pfkey_ipsec.c.
References add_policy_internal(), linked_list_t::create_enumerator, create_policy_entry(), DBG1, DBG2, DBG_KNL, enumerator_t::destroy, dir2kernel(), enumerator_t::enumerate, FAILED, FALSE, found, get_priority(), linked_list_t::insert_before, IPSEC_DIR_INVALID, linked_list_create(), mutex_t::lock, mutex, policy_dir_names, policy_entry_destroy(), policy_entry_equals(), policy_sa_create(), policy_sa_t::priority, SUCCESS, TRUE, mutex_t::unlock, update(), and policy_entry_t::used_by.
 {
     policy_entry_t *policy, *found = NULL;
     policy_sa_t *assigned_sa, *current_sa;
     enumerator_t *enumerator;
     bool update = TRUE;
     if (dir2kernel(direction) == IPSEC_DIR_INVALID)
     {   /* FWD policies are not supported on all platforms */
         return SUCCESS;
     }
     /* create a policy */
     policy = create_policy_entry(src_ts, dst_ts, direction);
     /* find a matching policy */
     this->mutex->lock(this->mutex);
     if (this->policies->find_first(this->policies,
                                   (linked_list_match_t)policy_entry_equals,
                                   (void**)&found, policy) == SUCCESS)
     {   /* use existing policy */
         DBG2(DBG_KNL, "policy %R === %R %N already exists, increasing "
                       "refcount", src_ts, dst_ts, policy_dir_names, direction);
         policy_entry_destroy(policy, this);
         policy = found;
     }
     else
     {   /* use the new one, if we have no such policy */
         this->policies->insert_first(this->policies, policy);
         policy->used_by = linked_list_create();
     }
     /* cache the assigned IPsec SA */
     assigned_sa = policy_sa_create(this, direction, type, src, dst, src_ts,
                                    dst_ts, sa);
     assigned_sa->priority = get_priority(policy, priority);
     /* insert the SA according to its priority */
     enumerator = policy->used_by->create_enumerator(policy->used_by);
     while (enumerator->enumerate(enumerator, (void**)&current_sa))
     {
         if (current_sa->priority >= assigned_sa->priority)
         {
             break;
         }
         update = FALSE;
     }
     policy->used_by->insert_before(policy->used_by, enumerator, assigned_sa);
     enumerator->destroy(enumerator);
     if (!update)
     {   /* we don't update the policy if the priority is lower than that of the
          * currently installed one */
         this->mutex->unlock(this->mutex);
         return SUCCESS;
     }
     DBG2(DBG_KNL, "%s policy %R === %R %N",
                    found ? "updating" : "adding", src_ts, dst_ts,
                    policy_dir_names, direction);
     if (add_policy_internal(this, policy, assigned_sa, found) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to %s policy %R === %R %N",
                        found ? "update" : "add", src_ts, dst_ts,
                        policy_dir_names, direction);
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , query_policy , status_t , private_kernel_pfkey_ipsec_t * this, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, mark_t mark, time_t * use_time)
Definition at line 2591 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), create_policy_entry(), DBG1, DBG2, DBG_KNL, dir2kernel(), policy_entry_t::dst, FAILED, found, free(), policy_entry_t::index, IPSEC_DIR_INVALID, IPSEC_POLICY_IPSEC, len, pfkey_msg_t::lft_current, mutex_t::lock, policy_entry_t::mask, memset, msg, mutex, policy_entry_t::net, NOT_FOUND, out, parse_pfkey_message(), PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, pfkey_send(), policy_dir_names, policy_entry_destroy(), policy_entry_equals(), policy_entry_t::proto, request(), response, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, sadb_lifetime::sadb_lifetime_usetime, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, SADB_X_EXT_POLICY, sadb_x_policy::sadb_x_policy_dir, sadb_x_policy::sadb_x_policy_exttype, sadb_x_policy::sadb_x_policy_id, sadb_x_policy::sadb_x_policy_len, sadb_x_policy::sadb_x_policy_type, SADB_X_SPDGET, policy_entry_t::src, strerror, SUCCESS, time_monotonic(), TRUE, and mutex_t::unlock.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_x_policy *pol;
     policy_entry_t *policy, *found = NULL;
     pfkey_msg_t response;
     size_t len;
     if (dir2kernel(direction) == IPSEC_DIR_INVALID)
     {   /* FWD policies are not supported on all platforms */
         return NOT_FOUND;
     }
     DBG2(DBG_KNL, "querying policy %R === %R %N", src_ts, dst_ts,
                    policy_dir_names, direction);
     /* create a policy */
     policy = create_policy_entry(src_ts, dst_ts, direction);
     /* find a matching policy */
     this->mutex->lock(this->mutex);
     if (this->policies->find_first(this->policies,
                                   (linked_list_match_t)policy_entry_equals,
                                   (void**)&found, policy) != SUCCESS)
     {
         DBG1(DBG_KNL, "querying policy %R === %R %N failed, not found", src_ts,
                        dst_ts, policy_dir_names, direction);
         policy_entry_destroy(policy, this);
         this->mutex->unlock(this->mutex);
         return NOT_FOUND;
     }
     policy_entry_destroy(policy, this);
     policy = found;
     memset(&request, 0, sizeof(request));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_X_SPDGET;
     msg->sadb_msg_satype = 0;
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     pol = (struct sadb_x_policy*)PFKEY_EXT_ADD_NEXT(msg);
     pol->sadb_x_policy_exttype = SADB_X_EXT_POLICY;
     pol->sadb_x_policy_id = policy->index;
     pol->sadb_x_policy_len = PFKEY_LEN(sizeof(struct sadb_x_policy));
     pol->sadb_x_policy_dir = dir2kernel(direction);
     pol->sadb_x_policy_type = IPSEC_POLICY_IPSEC;
     PFKEY_EXT_ADD(msg, pol);
     add_addr_ext(msg, policy->src.net, SADB_EXT_ADDRESS_SRC, policy->src.proto,
                  policy->src.mask, TRUE);
     add_addr_ext(msg, policy->dst.net, SADB_EXT_ADDRESS_DST, policy->dst.proto,
                  policy->dst.mask, TRUE);
     this->mutex->unlock(this->mutex);
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to query policy %R === %R %N", src_ts, dst_ts,
                        policy_dir_names, direction);
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to query policy %R === %R %N: %s (%d)", src_ts,
                        dst_ts, policy_dir_names, direction,
                        strerror(out->sadb_msg_errno), out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     else if (parse_pfkey_message(out, &response) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to query policy %R === %R %N: parsing response "
                       "from kernel failed", src_ts, dst_ts, policy_dir_names,
                        direction);
         free(out);
         return FAILED;
     }
     else if (response.lft_current == NULL)
     {
         DBG2(DBG_KNL, "unable to query policy %R === %R %N: kernel reports no "
                       "use time", src_ts, dst_ts, policy_dir_names, direction);
         free(out);
         return FAILED;
     }
     /* we need the monotonic time, but the kernel returns system time. */
     if (response.lft_current->sadb_lifetime_usetime)
     {
         *use_time = time_monotonic(NULL) -
                     (time(NULL) - response.lft_current->sadb_lifetime_usetime);
     }
     else
     {
         *use_time = 0;
     }
     free(out);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , del_policy , status_t , private_kernel_pfkey_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t prio)
Definition at line 2696 of file kernel_pfkey_ipsec.c.
References add_addr_ext(), add_policy_internal(), linked_list_t::create_enumerator, create_policy_entry(), DBG1, DBG2, DBG_KNL, kernel_interface_t::del_route, enumerator_t::destroy, dir2kernel(), policy_entry_t::dst, dst, route_entry_t::dst_net, enumerator_t::enumerate, FAILED, FALSE, found, free(), route_entry_t::gateway, linked_list_t::get_count, linked_list_t::get_first, get_priority(), hydra, route_entry_t::if_name, IPSEC_DIR_INVALID, ipsec_sa_equals(), hydra_t::kernel_interface, len, mutex_t::lock, policy_entry_t::mask, memset, msg, mutex, policy_entry_t::net, NOT_FOUND, out, PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_EXT_ADD, PFKEY_EXT_ADD_NEXT, PFKEY_LEN, pfkey_send(), policy_dir_names, policy_entry_destroy(), policy_entry_equals(), policy_sa_destroy(), route_entry_t::prefixlen, policy_sa_t::priority, policy_entry_t::proto, linked_list_t::remove, remove_exclude_route(), request(), policy_entry_t::route, policy_sa_t::sa, sa, SADB_EXT_ADDRESS_DST, SADB_EXT_ADDRESS_SRC, sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, SADB_X_EXT_POLICY, sadb_x_policy::sadb_x_policy_dir, sadb_x_policy::sadb_x_policy_exttype, sadb_x_policy::sadb_x_policy_len, sadb_x_policy::sadb_x_policy_type, SADB_X_SPDDELETE, policy_entry_t::src, ipsec_sa_t::src, src, route_entry_t::src_ip, strerror, SUCCESS, TRUE, policy_sa_t::type, type2kernel(), mutex_t::unlock, and policy_entry_t::used_by.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     struct sadb_x_policy *pol;
     policy_entry_t *policy, *found = NULL;
     policy_sa_t *mapping, *to_remove = NULL;
     enumerator_t *enumerator;
     bool first = TRUE, is_installed = TRUE;
     u_int32_t priority;
     size_t len;
     ipsec_sa_t assigned_sa = {
         .src = src,
         .dst = dst,
         .cfg = *sa,
     };
     if (dir2kernel(direction) == IPSEC_DIR_INVALID)
     {   /* FWD policies are not supported on all platforms */
         return SUCCESS;
     }
     DBG2(DBG_KNL, "deleting policy %R === %R %N", src_ts, dst_ts,
                    policy_dir_names, direction);
     /* create a policy */
     policy = create_policy_entry(src_ts, dst_ts, direction);
     /* find a matching policy */
     this->mutex->lock(this->mutex);
     if (this->policies->find_first(this->policies,
                                   (linked_list_match_t)policy_entry_equals,
                                   (void**)&found, policy) != SUCCESS)
     {
         DBG1(DBG_KNL, "deleting policy %R === %R %N failed, not found", src_ts,
                        dst_ts, policy_dir_names, direction);
         policy_entry_destroy(policy, this);
         this->mutex->unlock(this->mutex);
         return NOT_FOUND;
     }
     policy_entry_destroy(policy, this);
     policy = found;
     /* remove mapping to SA by reqid and priority, if multiple match, which
      * could happen when rekeying due to an address change, remove the oldest */
     priority = get_priority(policy, prio);
     enumerator = policy->used_by->create_enumerator(policy->used_by);
     while (enumerator->enumerate(enumerator, (void**)&mapping))
     {
         if (priority == mapping->priority &&
             ipsec_sa_equals(mapping->sa, &assigned_sa))
         {
             to_remove = mapping;
             is_installed = first;
         }
         else if (priority < mapping->priority)
         {
             break;
         }
         first = FALSE;
     }
     enumerator->destroy(enumerator);
     if (!to_remove)
     {   /* sanity check */
         this->mutex->unlock(this->mutex);
         return SUCCESS;
     }
     policy->used_by->remove(policy->used_by, to_remove, NULL);
     mapping = to_remove;
     if (policy->used_by->get_count(policy->used_by) > 0)
     {   /* policy is used by more SAs, keep in kernel */
         DBG2(DBG_KNL, "policy still used by another CHILD_SA, not removed");
         policy_sa_destroy(mapping, &direction, this);
         if (!is_installed)
         {   /* no need to update as the policy was not installed for this SA */
             this->mutex->unlock(this->mutex);
             return SUCCESS;
         }
         DBG2(DBG_KNL, "updating policy %R === %R %N", src_ts, dst_ts,
                        policy_dir_names, direction);
         policy->used_by->get_first(policy->used_by, (void**)&mapping);
         if (add_policy_internal(this, policy, mapping, TRUE) != SUCCESS)
         {
             DBG1(DBG_KNL, "unable to update policy %R === %R %N",
                            src_ts, dst_ts, policy_dir_names, direction);
             return FAILED;
         }
         return SUCCESS;
     }
     memset(&request, 0, sizeof(request));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_X_SPDDELETE;
     msg->sadb_msg_satype = 0;
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     pol = (struct sadb_x_policy*)PFKEY_EXT_ADD_NEXT(msg);
     pol->sadb_x_policy_exttype = SADB_X_EXT_POLICY;
     pol->sadb_x_policy_len = PFKEY_LEN(sizeof(struct sadb_x_policy));
     pol->sadb_x_policy_dir = dir2kernel(direction);
     pol->sadb_x_policy_type = type2kernel(mapping->type);
     PFKEY_EXT_ADD(msg, pol);
     add_addr_ext(msg, policy->src.net, SADB_EXT_ADDRESS_SRC, policy->src.proto,
                  policy->src.mask, TRUE);
     add_addr_ext(msg, policy->dst.net, SADB_EXT_ADDRESS_DST, policy->dst.proto,
                  policy->dst.mask, TRUE);
     if (policy->route)
     {
         route_entry_t *route = policy->route;
         if (hydra->kernel_interface->del_route(hydra->kernel_interface,
                 route->dst_net, route->prefixlen, route->gateway,
                 route->src_ip, route->if_name) != SUCCESS)
         {
             DBG1(DBG_KNL, "error uninstalling route installed with "
                           "policy %R === %R %N", src_ts, dst_ts,
                            policy_dir_names, direction);
         }
         remove_exclude_route(this, route);
     }
     this->policies->remove(this->policies, found, NULL);
     policy_sa_destroy(mapping, &direction, this);
     policy_entry_destroy(policy, this);
     this->mutex->unlock(this->mutex);
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to delete policy %R === %R %N", src_ts, dst_ts,
                        policy_dir_names, direction);
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to delete policy %R === %R %N: %s (%d)", src_ts,
                        dst_ts, policy_dir_names, direction,
                        strerror(out->sadb_msg_errno), out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     free(out);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , flush_policies , status_t , private_kernel_pfkey_ipsec_t * this)
Definition at line 2850 of file kernel_pfkey_ipsec.c.
References DBG1, DBG2, DBG_KNL, FAILED, free(), len, memset, msg, out, PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_LEN, pfkey_send(), request(), sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, SADB_SATYPE_UNSPEC, SADB_X_SPDFLUSH, strerror, and SUCCESS.
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     size_t len;
     memset(&request, 0, sizeof(request));
     DBG2(DBG_KNL, "flushing all policies from SPD");
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_X_SPDFLUSH;
     msg->sadb_msg_satype = SADB_SATYPE_UNSPEC;
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     if (pfkey_send(this, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to flush SPD entries");
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to flush SPD entries: %s (%d)",
                        strerror(out->sadb_msg_errno), out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     free(out);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , bypass_socket , bool , private_kernel_pfkey_ipsec_t * this, int fd, int family)
Definition at line 2917 of file kernel_pfkey_ipsec.c.
References DBG1, DBG_KNL, FALSE, IP_IPSEC_POLICY, IPSEC_DIR_INBOUND, IPSEC_DIR_OUTBOUND, IPSEC_POLICY_BYPASS, IPV6_IPSEC_POLICY, memset, SADB_X_EXT_POLICY, sadb_x_policy::sadb_x_policy_dir, sadb_x_policy::sadb_x_policy_exttype, sadb_x_policy::sadb_x_policy_len, sadb_x_policy::sadb_x_policy_type, setsockopt, SOL_IP, SOL_IPV6, strerror, and TRUE.
 {
     struct sadb_x_policy policy;
     u_int sol, ipsec_policy;
     switch (family)
     {
         case AF_INET:
         {
             sol = SOL_IP;
             ipsec_policy = IP_IPSEC_POLICY;
             break;
         }
         case AF_INET6:
         {
             sol = SOL_IPV6;
             ipsec_policy = IPV6_IPSEC_POLICY;
             break;
         }
         default:
             return FALSE;
     }
     memset(&policy, 0, sizeof(policy));
     policy.sadb_x_policy_len = sizeof(policy) / sizeof(u_int64_t);
     policy.sadb_x_policy_exttype = SADB_X_EXT_POLICY;
     policy.sadb_x_policy_type = IPSEC_POLICY_BYPASS;
     policy.sadb_x_policy_dir = IPSEC_DIR_OUTBOUND;
     if (setsockopt(fd, sol, ipsec_policy, &policy, sizeof(policy)) < 0)
     {
         DBG1(DBG_KNL, "unable to set IPSEC_POLICY on socket: %s",
                        strerror(errno));
         return FALSE;
     }
     policy.sadb_x_policy_dir = IPSEC_DIR_INBOUND;
     if (setsockopt(fd, sol, ipsec_policy, &policy, sizeof(policy)) < 0)
     {
         DBG1(DBG_KNL, "unable to set IPSEC_POLICY on socket: %s",
                        strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
METHOD (kernel_ipsec_t , enable_udp_decap , bool , private_kernel_pfkey_ipsec_t * this, int fd, int family, u_int16_t port)
Definition at line 2963 of file kernel_pfkey_ipsec.c.
References DBG1, DBG_KNL, FALSE, port, setsockopt, SOL_UDP, strerror, TRUE, type, UDP_ENCAP, and UDP_ENCAP_ESPINUDP.
 {
 #ifndef __APPLE__
     int type = UDP_ENCAP_ESPINUDP;
     if (setsockopt(fd, SOL_UDP, UDP_ENCAP, &type, sizeof(type)) < 0)
     {
         DBG1(DBG_KNL, "unable to set UDP_ENCAP: %s", strerror(errno));
         return FALSE;
     }
 #else /* __APPLE__ */
     int intport = port;
     if (sysctlbyname("net.inet.ipsec.esp_port", NULL, NULL, &intport,
                      sizeof(intport)) != 0)
     {
         DBG1(DBG_KNL, "could not set net.inet.ipsec.esp_port to %d: %s",
              port, strerror(errno));
         return FALSE;
     }
 #endif /* __APPLE__ */
     return TRUE;
 }
METHOD (kernel_ipsec_t , destroy , void , private_kernel_pfkey_ipsec_t * this)
Definition at line 2989 of file kernel_pfkey_ipsec.c.
References close, mutex_t::destroy, free(), lib, mutex, policy_entry_destroy(), watcher_t::remove, socket, and library_t::watcher.
 {
     if (this->socket > 0)
     {
         close(this->socket);
     }
     if (this->socket_events > 0)
     {
         lib->watcher->remove(lib->watcher, this->socket_events);
         close(this->socket_events);
     }
     this->policies->invoke_function(this->policies,
                                    (linked_list_invoke_t)policy_entry_destroy,
                                     this);
     this->policies->destroy(this->policies);
     this->excludes->destroy(this->excludes);
     this->sas->destroy(this->sas);
     this->mutex->destroy(this->mutex);
     this->mutex_pfkey->destroy(this->mutex_pfkey);
     free(this);
 }
static u_int8_t mode2kernel (ipsec_mode_t mode) static
convert the general ipsec mode to the one defined in ipsec.h
Definition at line 736 of file kernel_pfkey_ipsec.c.
References IPSEC_MODE_BEET, IPSEC_MODE_TRANSPORT, IPSEC_MODE_TUNNEL, MODE_BEET, MODE_TRANSPORT, and MODE_TUNNEL.
Referenced by add_policy_internal(), and METHOD().
 {
     switch (mode)
     {
         case MODE_TRANSPORT:
             return IPSEC_MODE_TRANSPORT;
         case MODE_TUNNEL:
             return IPSEC_MODE_TUNNEL;
 #ifdef HAVE_IPSEC_MODE_BEET
         case MODE_BEET:
             return IPSEC_MODE_BEET;
 #endif
         default:
             return mode;
     }
 }
static status_t parse_pfkey_message (struct sadb_msg * msg, pfkey_msg_t * out) static
Parses a pfkey message received from the kernel
Definition at line 1062 of file kernel_pfkey_ipsec.c.
References DBG1, DBG3, DBG_KNL, pfkey_msg_t::ext, FAILED, len, memset, msg, pfkey_msg_t::msg, PFKEY_EXT_NEXT_LEN, PFKEY_LEN, sadb_ext::sadb_ext_len, SADB_EXT_MAX, sadb_ext::sadb_ext_type, sadb_msg::sadb_msg_len, and SUCCESS.
Referenced by add_policy_internal(), get_spi_internal(), METHOD(), process_acquire(), and process_expire().
 {
     struct sadb_ext* ext;
     size_t len;
     memset(out, 0, sizeof(pfkey_msg_t));
     out->msg = msg;
     len = msg->sadb_msg_len;
     len -= PFKEY_LEN(sizeof(struct sadb_msg));
     ext = (struct sadb_ext*)(((char*)msg) + sizeof(struct sadb_msg));
     while (len >= PFKEY_LEN(sizeof(struct sadb_ext)))
     {
         DBG3(DBG_KNL, "  %N", sadb_ext_type_names, ext->sadb_ext_type);
         if (ext->sadb_ext_len < PFKEY_LEN(sizeof(struct sadb_ext)) ||
             ext->sadb_ext_len > len)
         {
             DBG1(DBG_KNL, "length of %N extension is invalid",
                            sadb_ext_type_names, ext->sadb_ext_type);
             break;
         }
         if ((ext->sadb_ext_type > SADB_EXT_MAX) || (!ext->sadb_ext_type))
         {
             DBG1(DBG_KNL, "type of PF_KEY extension (%d) is invalid",
                            ext->sadb_ext_type);
             break;
         }
         if (out->ext[ext->sadb_ext_type])
         {
             DBG1(DBG_KNL, "duplicate %N extension",
                            sadb_ext_type_names, ext->sadb_ext_type);
             break;
         }
         out->ext[ext->sadb_ext_type] = ext;
         ext = PFKEY_EXT_NEXT_LEN(ext, len);
     }
     if (len)
     {
         DBG1(DBG_KNL, "PF_KEY message length is invalid");
         return FAILED;
     }
     return SUCCESS;
 }
static status_t pfkey_send (private_kernel_pfkey_ipsec_t * this, struct sadb_msg * in, struct sadb_msg ** out, size_t * out_len) static
Send a message to the default PF_KEY socket and handle the response.
Definition at line 1230 of file kernel_pfkey_ipsec.c.
References pfkey_send_socket(), and socket.
Referenced by add_policy_internal(), get_spi_internal(), and METHOD().
 {
     return pfkey_send_socket(this, this->socket, in, out, out_len);
 }
static status_t pfkey_send_socket (private_kernel_pfkey_ipsec_t * this, int socket, struct sadb_msg * in, struct sadb_msg ** out, size_t * out_len) static
Send a message to a specific PF_KEY socket and handle the response.
Definition at line 1116 of file kernel_pfkey_ipsec.c.
References DBG1, DBG2, DBG_KNL, FAILED, len, malloc(), memcpy, msg, PFKEY_ALIGNMENT, PFKEY_BUFFER_SIZE, PFKEY_LEN, PFKEY_USER_LEN, recv, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_pid, sadb_msg::sadb_msg_seq, sadb_msg::sadb_msg_type, send, seq, strerror, SUCCESS, and TRUE.
Referenced by pfkey_send(), and register_pfkey_socket().
 {
     unsigned char buf[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg;
     int in_len, len;
     this->mutex_pfkey->lock(this->mutex_pfkey);
     /* FIXME: our usage of sequence numbers is probably wrong. check RFC 2367,
      * in particular the behavior in response to an SADB_ACQUIRE. */
     in->sadb_msg_seq = ++this->seq;
     in->sadb_msg_pid = getpid();
     in_len = PFKEY_USER_LEN(in->sadb_msg_len);
     while (TRUE)
     {
         len = send(socket, in, in_len, 0);
         if (len != in_len)
         {
             if (errno == EINTR)
             {
                 /* interrupted, try again */
                 continue;
             }
             this->mutex_pfkey->unlock(this->mutex_pfkey);
             DBG1(DBG_KNL, "error sending to PF_KEY socket: %s",
                            strerror(errno));
             return FAILED;
         }
         break;
     }
     while (TRUE)
     {
         msg = (struct sadb_msg*)buf;
         len = recv(socket, buf, sizeof(buf), 0);
         if (len < 0)
         {
             if (errno == EINTR)
             {
                 DBG1(DBG_KNL, "got interrupted");
                 /* interrupted, try again */
                 continue;
             }
             DBG1(DBG_KNL, "error reading from PF_KEY socket: %s",
                            strerror(errno));
             this->mutex_pfkey->unlock(this->mutex_pfkey);
             return FAILED;
         }
         if (len < sizeof(struct sadb_msg) ||
             msg->sadb_msg_len < PFKEY_LEN(sizeof(struct sadb_msg)))
         {
             DBG1(DBG_KNL, "received corrupted PF_KEY message");
             this->mutex_pfkey->unlock(this->mutex_pfkey);
             return FAILED;
         }
         if (msg->sadb_msg_len > len / PFKEY_ALIGNMENT)
         {
             DBG1(DBG_KNL, "buffer was too small to receive the complete PF_KEY "
                           "message");
             this->mutex_pfkey->unlock(this->mutex_pfkey);
             return FAILED;
         }
         if (msg->sadb_msg_pid != in->sadb_msg_pid)
         {
             DBG2(DBG_KNL, "received PF_KEY message is not intended for us");
             continue;
         }
         if (msg->sadb_msg_seq != this->seq)
         {
             DBG2(DBG_KNL, "received PF_KEY message with unexpected sequence "
                           "number, was %d expected %d", msg->sadb_msg_seq,
                           this->seq);
             if (msg->sadb_msg_seq == 0)
             {
                 /* FreeBSD and Mac OS X do this for the response to
                  * SADB_X_SPDGET (but not for the response to SADB_GET).
                  * FreeBSD: 'key_spdget' in /usr/src/sys/netipsec/key.c. */
             }
             else if (msg->sadb_msg_seq < this->seq)
             {
                 continue;
             }
             else
             {
                 this->mutex_pfkey->unlock(this->mutex_pfkey);
                 return FAILED;
             }
         }
         if (msg->sadb_msg_type != in->sadb_msg_type)
         {
             DBG2(DBG_KNL, "received PF_KEY message of wrong type, "
                           "was %d expected %d, ignoring", msg->sadb_msg_type,
                            in->sadb_msg_type);
         }
         break;
     }
     *out_len = len;
     *out = (struct sadb_msg*)malloc(len);
     memcpy(*out, buf, len);
     this->mutex_pfkey->unlock(this->mutex_pfkey);
     return SUCCESS;
 }
static void policy_entry_destroy (policy_entry_t * policy, private_kernel_pfkey_ipsec_t * this) static
Destroy a policy_entry_t object
Definition at line 548 of file kernel_pfkey_ipsec.c.
References linked_list_t::destroy, DESTROY_IF, policy_entry_t::direction, policy_entry_t::dst, free(), linked_list_t::invoke_function, policy_entry_t::net, policy_sa_destroy(), policy_entry_t::route, route_entry_destroy(), policy_entry_t::src, and policy_entry_t::used_by.
Referenced by METHOD().
 {
     if (policy->route)
     {
         route_entry_destroy(policy->route);
     }
     if (policy->used_by)
     {
         policy->used_by->invoke_function(policy->used_by,
                                         (linked_list_invoke_t)policy_sa_destroy,
                                          &policy->direction, this);
         policy->used_by->destroy(policy->used_by);
     }
     DESTROY_IF(policy->src.net);
     DESTROY_IF(policy->dst.net);
     free(policy);
 }
static bool policy_entry_equals (policy_entry_t * current, policy_entry_t * policy) inline static
compares two policy_entry_t
Definition at line 570 of file kernel_pfkey_ipsec.c.
References policy_entry_t::direction, policy_entry_t::dst, host_t::equals, policy_entry_t::mask, policy_entry_t::net, policy_entry_t::proto, and policy_entry_t::src.
Referenced by METHOD().
 {
     return current->direction == policy->direction &&
            current->src.proto == policy->src.proto &&
            current->dst.proto == policy->dst.proto &&
            current->src.mask == policy->src.mask &&
            current->dst.mask == policy->dst.mask &&
            current->src.net->equals(current->src.net, policy->src.net) &&
            current->dst.net->equals(current->dst.net, policy->dst.net);
 }
static bool policy_entry_match_byindex (policy_entry_t * current, u_int32_t * index) inline static
compare the given kernel index with that of a policy
Definition at line 585 of file kernel_pfkey_ipsec.c.
References policy_entry_t::index.
Referenced by process_acquire().
 {
     return current->index == *index;
 }
static policy_sa_t* policy_sa_create (private_kernel_pfkey_ipsec_t * this, policy_dir_t dir, policy_type_t type, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, ipsec_sa_cfg_t * cfg) static
Create a policy_sa(_in)_t object
Definition at line 437 of file kernel_pfkey_ipsec.c.
References traffic_selector_t::clone, policy_sa_in_t::generic, in, INIT, ipsec_sa_create(), POLICY_IN, policy_sa_t::sa, type, and policy_sa_t::type.
Referenced by METHOD().
 {
     policy_sa_t *policy;
     if (dir == POLICY_IN)
     {
         policy_sa_in_t *in;
         INIT(in,
             .src_ts = src_ts->clone(src_ts),
             .dst_ts = dst_ts->clone(dst_ts),
         );
         policy = &in->generic;
     }
     else
     {
         INIT(policy, .priority = 0);
     }
     policy->type = type;
     policy->sa = ipsec_sa_create(this, src, dst, cfg);
     return policy;
 }
static void policy_sa_destroy (policy_sa_t * policy, policy_dir_t * dir, private_kernel_pfkey_ipsec_t * this) static
Destroy a policy_sa(_in)_t object
Definition at line 464 of file kernel_pfkey_ipsec.c.
References traffic_selector_t::destroy, policy_sa_in_t::dst_ts, free(), in, ipsec_sa_destroy(), POLICY_IN, policy_sa_t::sa, and policy_sa_in_t::src_ts.
Referenced by METHOD(), and policy_entry_destroy().
 {
     if (*dir == POLICY_IN)
     {
         policy_sa_in_t *in = (policy_sa_in_t*)policy;
         in->src_ts->destroy(in->src_ts);
         in->dst_ts->destroy(in->dst_ts);
     }
     ipsec_sa_destroy(this, policy->sa);
     free(policy);
 }
static void process_acquire (private_kernel_pfkey_ipsec_t * this, struct sadb_msg * msg) static
Process a SADB_ACQUIRE message from the kernel
Definition at line 1240 of file kernel_pfkey_ipsec.c.
References kernel_interface_t::acquire, ipsec_sa_t::cfg, DBG1, DBG2, DBG_KNL, pfkey_msg_t::dst, linked_list_t::get_first, hydra, hydra_t::kernel_interface, mutex_t::lock, mutex, parse_pfkey_message(), policy_entry_match_byindex(), ipsec_sa_cfg_t::reqid, response, policy_sa_t::sa, sa, sadb_address2ts(), sadb_msg::sadb_msg_satype, SADB_SATYPE_AH, SADB_SATYPE_ESP, SADB_SATYPE_UNSPEC, sadb_x_policy::sadb_x_policy_id, pfkey_msg_t::src, SUCCESS, mutex_t::unlock, policy_entry_t::used_by, and pfkey_msg_t::x_policy.
Referenced by receive_events().
 {
     pfkey_msg_t response;
     u_int32_t index, reqid = 0;
     traffic_selector_t *src_ts, *dst_ts;
     policy_entry_t *policy;
     policy_sa_t *sa;
     switch (msg->sadb_msg_satype)
     {
         case SADB_SATYPE_UNSPEC:
         case SADB_SATYPE_ESP:
         case SADB_SATYPE_AH:
             break;
         default:
             /* acquire for AH/ESP only */
             return;
     }
     DBG2(DBG_KNL, "received an SADB_ACQUIRE");
     if (parse_pfkey_message(msg, &response) != SUCCESS)
     {
         DBG1(DBG_KNL, "parsing SADB_ACQUIRE from kernel failed");
         return;
     }
     index = response.x_policy->sadb_x_policy_id;
     this->mutex->lock(this->mutex);
     if (this->policies->find_first(this->policies,
                                 (linked_list_match_t)policy_entry_match_byindex,
                                 (void**)&policy, &index) == SUCCESS &&
         policy->used_by->get_first(policy->used_by, (void**)&sa) == SUCCESS)
     {
         reqid = sa->sa->cfg.reqid;
     }
     else
     {
         DBG1(DBG_KNL, "received an SADB_ACQUIRE with policy id %d but no "
                       "matching policy found", index);
     }
     this->mutex->unlock(this->mutex);
     src_ts = sadb_address2ts(response.src);
     dst_ts = sadb_address2ts(response.dst);
     hydra->kernel_interface->acquire(hydra->kernel_interface, reqid, src_ts,
                                      dst_ts);
 }
static void process_expire (private_kernel_pfkey_ipsec_t * this, struct sadb_msg * msg) static
Process a SADB_EXPIRE message from the kernel
Definition at line 1293 of file kernel_pfkey_ipsec.c.
References DBG1, DBG2, DBG_KNL, host_t::destroy, dst, pfkey_msg_t::dst, kernel_interface_t::expire, host_create_from_sockaddr(), hydra, hydra_t::kernel_interface, pfkey_msg_t::lft_hard, parse_pfkey_message(), protocol, response, pfkey_msg_t::sa, sadb_msg::sadb_msg_satype, sadb_sa::sadb_sa_spi, satype2proto(), and SUCCESS.
Referenced by receive_events().
 {
     pfkey_msg_t response;
     u_int8_t protocol;
     u_int32_t spi;
     host_t *dst;
     bool hard;
     DBG2(DBG_KNL, "received an SADB_EXPIRE");
     if (parse_pfkey_message(msg, &response) != SUCCESS)
     {
         DBG1(DBG_KNL, "parsing SADB_EXPIRE from kernel failed");
         return;
     }
     protocol = satype2proto(msg->sadb_msg_satype);
     spi = response.sa->sadb_sa_spi;
     hard = response.lft_hard != NULL;
     if (protocol == IPPROTO_ESP || protocol == IPPROTO_AH)
     {
         dst = host_create_from_sockaddr((sockaddr_t*)(response.dst + 1));
         if (dst)
         {
             hydra->kernel_interface->expire(hydra->kernel_interface, protocol,
                                             spi, dst, hard);
             dst->destroy(dst);
         }
     }
 }
static u_int8_t proto2satype (u_int8_t proto) static
convert a protocol identifier to the PF_KEY sa type
Definition at line 700 of file kernel_pfkey_ipsec.c.
References proto, SADB_SATYPE_AH, SADB_SATYPE_ESP, and SADB_X_SATYPE_IPCOMP.
Referenced by get_spi_internal(), and METHOD().
 {
     switch (proto)
     {
         case IPPROTO_ESP:
             return SADB_SATYPE_ESP;
         case IPPROTO_AH:
             return SADB_SATYPE_AH;
         case IPPROTO_COMP:
             return SADB_X_SATYPE_IPCOMP;
         default:
             return proto;
     }
 }
static bool receive_events (private_kernel_pfkey_ipsec_t * this, int fd, watcher_event_t event) static
Receives events from kernel
Definition at line 1452 of file kernel_pfkey_ipsec.c.
References DBG1, DBG2, DBG_KNL, len, MSG_DONTWAIT, PFKEY_ALIGNMENT, PFKEY_BUFFER_SIZE, PFKEY_LEN, process_acquire(), process_expire(), process_mapping(), process_migrate(), recvfrom, SADB_ACQUIRE, SADB_EXPIRE, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_pid, sadb_msg::sadb_msg_type, SADB_X_MIGRATE, SADB_X_NAT_T_NEW_MAPPING, sleep, and TRUE.
Referenced by kernel_pfkey_ipsec_create().
 {
     unsigned char buf[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg = (struct sadb_msg*)buf;
     int len;
     len = recvfrom(this->socket_events, buf, sizeof(buf), MSG_DONTWAIT, NULL, 0);
     if (len < 0)
     {
         switch (errno)
         {
             case EINTR:
                 /* interrupted, try again */
                 return TRUE;
             case EAGAIN:
                 /* no data ready, select again */
                 return TRUE;
             default:
                 DBG1(DBG_KNL, "unable to receive from PF_KEY event socket");
                 sleep(1);
                 return TRUE;
         }
     }
     if (len < sizeof(struct sadb_msg) ||
         msg->sadb_msg_len < PFKEY_LEN(sizeof(struct sadb_msg)))
     {
         DBG2(DBG_KNL, "received corrupted PF_KEY message");
         return TRUE;
     }
     if (msg->sadb_msg_pid != 0)
     {   /* not from kernel. not interested, try another one */
         return TRUE;
     }
     if (msg->sadb_msg_len > len / PFKEY_ALIGNMENT)
     {
         DBG1(DBG_KNL, "buffer was too small to receive the complete "
                       "PF_KEY message");
         return TRUE;
     }
     switch (msg->sadb_msg_type)
     {
         case SADB_ACQUIRE:
             process_acquire(this, msg);
             break;
         case SADB_EXPIRE:
             process_expire(this, msg);
             break;
 #ifdef SADB_X_MIGRATE
         case SADB_X_MIGRATE:
             process_migrate(this, msg);
             break;
 #endif /*SADB_X_MIGRATE*/
 #ifdef SADB_X_NAT_T_NEW_MAPPING
         case SADB_X_NAT_T_NEW_MAPPING:
             process_mapping(this, msg);
             break;
 #endif /*SADB_X_NAT_T_NEW_MAPPING*/
         default:
             break;
     }
     return TRUE;
 }
static status_t register_pfkey_socket (private_kernel_pfkey_ipsec_t * this, u_int8_t satype) static
Register a socket for ACQUIRE/EXPIRE messages
Definition at line 2886 of file kernel_pfkey_ipsec.c.
References DBG1, DBG_KNL, FAILED, free(), len, memset, msg, out, PF_KEY_V2, PFKEY_BUFFER_SIZE, PFKEY_LEN, pfkey_send_socket(), request(), sadb_msg::sadb_msg_errno, sadb_msg::sadb_msg_len, sadb_msg::sadb_msg_satype, sadb_msg::sadb_msg_type, sadb_msg::sadb_msg_version, SADB_REGISTER, strerror, and SUCCESS.
Referenced by kernel_pfkey_ipsec_create().
 {
     unsigned char request[PFKEY_BUFFER_SIZE];
     struct sadb_msg *msg, *out;
     size_t len;
     memset(&request, 0, sizeof(request));
     msg = (struct sadb_msg*)request;
     msg->sadb_msg_version = PF_KEY_V2;
     msg->sadb_msg_type = SADB_REGISTER;
     msg->sadb_msg_satype = satype;
     msg->sadb_msg_len = PFKEY_LEN(sizeof(struct sadb_msg));
     if (pfkey_send_socket(this, this->socket_events, msg, &out, &len) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to register PF_KEY socket");
         return FAILED;
     }
     else if (out->sadb_msg_errno)
     {
         DBG1(DBG_KNL, "unable to register PF_KEY socket: %s (%d)",
                        strerror(out->sadb_msg_errno), out->sadb_msg_errno);
         free(out);
         return FAILED;
     }
     free(out);
     return SUCCESS;
 }
static void remove_exclude_route (private_kernel_pfkey_ipsec_t * this, route_entry_t * route) static
Remove an exclude route attached to a routing entry
Definition at line 2184 of file kernel_pfkey_ipsec.c.
References DBG1, DBG2, DBG_KNL, kernel_interface_t::del_route, enumerator_t::destroy, exclude_route_t::dst, dst, enumerator_t::enumerate, route_entry_t::exclude, exclude_route_destroy(), FALSE, free(), host_t::get_address, host_t::get_family, kernel_interface_t::get_interface, exclude_route_t::gtw, hydra, hydra_t::kernel_interface, exclude_route_t::refs, exclude_route_t::src, SUCCESS, and TRUE.
Referenced by install_route(), and METHOD().
 {
     if (route->exclude)
     {
         enumerator_t *enumerator;
         exclude_route_t *exclude;
         bool removed = FALSE;
         host_t *dst;
         enumerator = this->excludes->create_enumerator(this->excludes);
         while (enumerator->enumerate(enumerator, &exclude))
         {
             if (route->exclude == exclude)
             {
                 if (--exclude->refs == 0)
                 {
                     this->excludes->remove_at(this->excludes, enumerator);
                     removed = TRUE;
                     break;
                 }
             }
         }
         enumerator->destroy(enumerator);
         if (removed)
         {
             char *if_name = NULL;
             dst = route->exclude->dst;
             DBG2(DBG_KNL, "uninstalling exclude route for %H src %H",
                  dst, route->exclude->src);
             if (hydra->kernel_interface->get_interface(
                                     hydra->kernel_interface,
                                     route->exclude->src, &if_name) &&
                 hydra->kernel_interface->del_route(hydra->kernel_interface,
                                     dst->get_address(dst),
                                     dst->get_family(dst) == AF_INET ? 32 : 128,
                                     route->exclude->gtw, route->exclude->src,
                                     if_name) != SUCCESS)
             {
                 DBG1(DBG_KNL, "uninstalling exclude route for %H failed", dst);
             }
             exclude_route_destroy(route->exclude);
             free(if_name);
         }
         route->exclude = NULL;
     }
 }
static void route_entry_destroy (route_entry_t * this) static
destroy an route_entry_t object
Definition at line 298 of file kernel_pfkey_ipsec.c.
References chunk_free(), DESTROY_IF, and free().
Referenced by install_route(), and policy_entry_destroy().
 {
     free(this->if_name);
     DESTROY_IF(this->src_ip);
     DESTROY_IF(this->gateway);
     chunk_free(&this->dst_net);
     free(this);
 }
static bool route_entry_equals (route_entry_t * a, route_entry_t * b) static
compare two route_entry_t objects
Definition at line 310 of file kernel_pfkey_ipsec.c.
References chunk_equals(), route_entry_t::dst_net, route_entry_t::gateway, route_entry_t::if_name, host_t::ip_equals, route_entry_t::prefixlen, route_entry_t::src_ip, and streq().
Referenced by install_route().
 {
     return a->if_name && b->if_name && streq(a->if_name, b->if_name) &&
            a->src_ip->ip_equals(a->src_ip, b->src_ip) &&
            a->gateway && b->gateway &&
            a->gateway->ip_equals(a->gateway, b->gateway) &&
            chunk_equals(a->dst_net, b->dst_net) && a->prefixlen == b->prefixlen;
 }
static traffic_selector_t* sadb_address2ts (struct sadb_address * address) static
Convert a sadb_address to a traffic_selector
Definition at line 1039 of file kernel_pfkey_ipsec.c.
References host_t::get_port, host, host_create_from_sockaddr(), IPSEC_PROTO_ANY, proto, sadb_address::sadb_address_prefixlen, sadb_address::sadb_address_proto, and traffic_selector_create_from_subnet().
Referenced by process_acquire().
 {
     traffic_selector_t *ts;
     host_t *host;
     u_int8_t proto;
     proto = address->sadb_address_proto;
     proto = proto == IPSEC_PROTO_ANY ? 0 : proto;
     /* The Linux 2.6 kernel does not set the protocol and port information
      * in the src and dst sadb_address extensions of the SADB_ACQUIRE message.
      */
     host = host_create_from_sockaddr((sockaddr_t*)&address[1]);
     ts = traffic_selector_create_from_subnet(host,
                                              address->sadb_address_prefixlen,
                                              proto, host->get_port(host),
                                              host->get_port(host) ?: 65535);
     return ts;
 }
static u_int8_t satype2proto (u_int8_t satype) static
convert a PF_KEY sa type to a protocol identifier
Definition at line 718 of file kernel_pfkey_ipsec.c.
References SADB_SATYPE_AH, SADB_SATYPE_ESP, and SADB_X_SATYPE_IPCOMP.
Referenced by process_expire().
 {
     switch (satype)
     {
         case SADB_SATYPE_ESP:
             return IPPROTO_ESP;
         case SADB_SATYPE_AH:
             return IPPROTO_AH;
         case SADB_X_SATYPE_IPCOMP:
             return IPPROTO_COMP;
         default:
             return satype;
     }
 }
static void set_port (sockaddr_t * addr, u_int16_t port) static
Helper to set a port in a sockaddr_t, the port has to be in host order
Definition at line 933 of file kernel_pfkey_ipsec.c.
Referenced by host_create_any_port(), host_create_from_dns(), and hostcpy().
 {
     switch (addr->sa_family)
     {
         case AF_INET:
         {
             struct sockaddr_in *sin = (struct sockaddr_in*)addr;
             sin->sin_port = htons(port);
             break;
         }
         case AF_INET6:
         {
             struct sockaddr_in6 *sin6 = (struct sockaddr_in6*)addr;
             sin6->sin6_port = htons(port);
             break;
         }
     }
 }
static u_int16_t type2kernel (policy_type_t type) inline static
convert the policy type to the one defined in ipsec.h
Definition at line 776 of file kernel_pfkey_ipsec.c.
References IPSEC_POLICY_DISCARD, IPSEC_POLICY_IPSEC, IPSEC_POLICY_NONE, POLICY_DROP, POLICY_IPSEC, POLICY_PASS, and type.
Referenced by add_policy_internal(), and METHOD().
 {
     switch (type)
     {
         case POLICY_IPSEC:
             return IPSEC_POLICY_IPSEC;
         case POLICY_PASS:
             return IPSEC_POLICY_NONE;
         case POLICY_DROP:
             return IPSEC_POLICY_DISCARD;
     }
     return type;
 }
Variable Documentation
kernel_algorithm_t compression_algs[] static
Initial value:
= {
    {IPCOMP_DEFLATE,            SADB_X_CALG_DEFLATE         },
    {END_OF_LIST,               0                           },
}
Algorithms for IPComp, unused yet
Definition at line 883 of file kernel_pfkey_ipsec.c.
Referenced by lookup_algorithm().
struct sadb_address* dst
Definition at line 643 of file kernel_pfkey_ipsec.c.
Referenced by add_nat_oa_payloads(), CALLBACK(), charon_esa_expire(), check_destroy(), clone_message(), create_policy_entry(), destroy_acquire(), destroy_route(), destroy_trap(), dhcp_socket_create(), discover(), do_memxor(), exclude_route_destroy(), host2address6(), install_route(), ip_packet_create(), manage_route(), memcpy_noop(), memmove_noop(), merge_fragments(), METHOD(), packet_create_from_data(), pem_to_bin(), policy_entry_destroy(), prepare_dhcp(), process_expire(), process_mapping(), process_outbound(), pseudo_header_checksum(), receive_casts(), receive_packets(), rekey_child(), remove_exclude_route(), send_dhcp(), send_notify(), send_peer(), START_TEST(), strdup_windows(), strndup(), strreplace(), and uninstall_route().
kernel_algorithm_t encryption_algs[] static
Initial value:
= {
    {ENCR_DES,                  SADB_EALG_DESCBC            },
    {ENCR_3DES,                 SADB_EALG_3DESCBC           },
    {ENCR_CAST,                 SADB_X_EALG_CASTCBC         },
    {ENCR_BLOWFISH,             SADB_X_EALG_BLOWFISHCBC     },
    {ENCR_NULL,                 SADB_EALG_NULL              },
    {ENCR_AES_CBC,              SADB_X_EALG_AESCBC          },
    {END_OF_LIST,               0                           },
}
Algorithms for encryption
Definition at line 834 of file kernel_pfkey_ipsec.c.
Referenced by lookup_algorithm().
struct sadb_ident* id_dst
Definition at line 648 of file kernel_pfkey_ipsec.c.
struct sadb_ident* id_src
Definition at line 647 of file kernel_pfkey_ipsec.c.
kernel_algorithm_t integrity_algs[] static
Initial value:
= {
    {AUTH_HMAC_MD5_96,          SADB_AALG_MD5HMAC           },
    {AUTH_HMAC_SHA1_96,         SADB_AALG_SHA1HMAC          },
    {AUTH_HMAC_SHA2_256_128,    SADB_X_AALG_SHA2_256HMAC    },
    {AUTH_HMAC_SHA2_384_192,    SADB_X_AALG_SHA2_384HMAC    },
    {AUTH_HMAC_SHA2_512_256,    SADB_X_AALG_SHA2_512HMAC    },
    {END_OF_LIST,               0,                          },
}
Algorithms for integrity protection
Definition at line 866 of file kernel_pfkey_ipsec.c.
Referenced by lookup_algorithm().
struct sadb_key* key_auth
Definition at line 645 of file kernel_pfkey_ipsec.c.
struct sadb_key* key_encr
Definition at line 646 of file kernel_pfkey_ipsec.c.
struct sadb_lifetime* lft_current
Definition at line 639 of file kernel_pfkey_ipsec.c.
struct sadb_lifetime* lft_hard
Definition at line 640 of file kernel_pfkey_ipsec.c.
struct sadb_lifetime* lft_soft
Definition at line 641 of file kernel_pfkey_ipsec.c.
struct sadb_prop* proposal
Definition at line 650 of file kernel_pfkey_ipsec.c.
Referenced by add_esp_proposals(), add_ike_proposals(), add_proposals(), add_tunnel_provider(), allocate_spi(), build_payloads(), CALLBACK(), check_for_rekeyed_child(), create_child_cfg(), create_peer_cfg(), create_proposal(), derive_keys(), generate_config(), get_proposals(), install(), library_deinit(), list_child(), list_ike(), load_child_config(), load_ike_config(), load_proposals(), load_tester_config_create(), log_child_sa(), METHOD(), parse_proposal(), process_auth_request(), process_auth_response(), process_child_add(), process_ike_add(), process_payloads(), proposal_substructure_create_from_proposals_v1(), sa_payload_create_from_proposals_v2(), select_and_install(), set_byte(), and START_TEST().
struct sadb_address* proxy
Definition at line 644 of file kernel_pfkey_ipsec.c.
struct sadb_ext* reserved
Definition at line 637 of file kernel_pfkey_ipsec.c.
struct sadb_sa* sa
Definition at line 638 of file kernel_pfkey_ipsec.c.
Referenced by add_port_bypass(), cleanup_sas(), collect_stats(), initiate_mediated(), install_shunt_policy(), ipsec_sa_create(), is_address_better(), match_entry_by_sa_ptr(), METHOD(), process_acquire(), process_auth_request(), process_inbound(), process_outbound(), remove_first(), send_interim(), send_stop(), set_byte(), setting_sort(), settings_section_sort(), uninstall_shunt_policy(), and update_sa().
struct sadb_sens* sensitivity
Definition at line 649 of file kernel_pfkey_ipsec.c.
struct sadb_spirange* spirange
Definition at line 653 of file kernel_pfkey_ipsec.c.
struct sadb_address* src
Definition at line 642 of file kernel_pfkey_ipsec.c.
Referenced by add_exclude_route(), add_nat_oa_payloads(), atodn(), check_destroy(), clone_message(), create_policy_entry(), destroy_route(), destroy_trap(), exclude_route_destroy(), fetchline(), get_init_hash(), get_route(), host2address6(), install_route(), ip_packet_create(), is_any_path_valid(), is_current_path_valid(), load_imcvs_from_config(), load_secrets(), manage_route(), merge_fragments(), METHOD(), packet_create_from_data(), padlock_crypt(), pem_to_bin(), policy_entry_destroy(), prepare_dhcp(), process_outbound(), pseudo_header_checksum(), radius_receive(), receive_casts(), receive_packet(), receive_packets(), send_notify(), START_TEST(), and uninstall_route().
struct sadb_supported* supported_auth
Definition at line 651 of file kernel_pfkey_ipsec.c.
struct sadb_supported* supported_encr
Definition at line 652 of file kernel_pfkey_ipsec.c.
struct sadb_x_kmaddress* x_kmaddress
Definition at line 662 of file kernel_pfkey_ipsec.c.
struct sadb_x_kmprivate* x_kmprivate
Definition at line 654 of file kernel_pfkey_ipsec.c.
struct sadb_x_nat_t_port* x_natt_dport
Definition at line 659 of file kernel_pfkey_ipsec.c.
struct sadb_address* x_natt_oa
Definition at line 660 of file kernel_pfkey_ipsec.c.
struct sadb_x_nat_t_port* x_natt_sport
Definition at line 658 of file kernel_pfkey_ipsec.c.
struct sadb_x_nat_t_type* x_natt_type
Definition at line 657 of file kernel_pfkey_ipsec.c.
struct sadb_x_policy* x_policy
Definition at line 655 of file kernel_pfkey_ipsec.c.
struct sadb_x_sa2* x_sa2
Definition at line 656 of file kernel_pfkey_ipsec.c.
struct sadb_x_sec_ctx* x_sec_ctx
Definition at line 661 of file kernel_pfkey_ipsec.c.