strongSwan: fragment_payload
fragment_payload
payloads
Classes
struct fragment_payload_t
Typedefs
typedef struct fragment_payload_t fragment_payload_t
Functions
fragment_payload_t * fragment_payload_create ()
fragment_payload_t * fragment_payload_create_from_data (u_int8_t num, bool last, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct fragment_payload_t fragment_payload_t
Definition at line 24 of file fragment_payload.h.
Function Documentation
fragment_payload_t* fragment_payload_create ()
Creates an empty fragment_payload_t object.
Returns
fragment_payload_t object
Definition at line 182 of file fragment_payload.c.
References INIT, and PL_NONE.
Referenced by fragment_payload_create_from_data(), and payload_create().
 {
     private_fragment_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_id = _get_id,
             .get_number = _get_number,
             .is_last = _is_last,
             .get_data = _get_data,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
     );
     this->payload_length = get_header_length(this);
     return &this->public;
 }
fragment_payload_t* fragment_payload_create_from_data (u_int8_t num, bool last, chunk_t data)
Creates a fragment payload from the given data. All fragments currently have the same fragment ID (1), which seems what other implementations are doing.
Parameters
num fragment number (first one should be 1)
last TRUE to indicate that this is the last fragment
data fragment data (gets cloned)
Returns
fragment_payload_t object
Definition at line 213 of file fragment_payload.c.
References chunk_clone, flags, fragment_payload_create(), LAST_FRAGMENT, and chunk_t::len.
Referenced by create_fragment().
 {
     private_fragment_payload_t *this;
     this = (private_fragment_payload_t*)fragment_payload_create();
     this->fragment_id = 1;
     this->fragment_number = num;
     this->flags |= (last ? LAST_FRAGMENT : 0);
     this->data = chunk_clone(data);
     this->payload_length = get_header_length(this) + data.len;
     return &this->public;
 }