strongSwan: mconsole.c File Reference
mconsole.c File Reference
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/socket.h>
#include <errno.h>
#include <sys/un.h>
#include <utils/debug.h>
#include "mconsole.h"
Classes
struct private_mconsole_t
struct mconsole_request
struct mconsole_reply
struct mconsole_notify
Macros
#define _GNU_SOURCE
#define MCONSOLE_MAGIC 0xcafebabe
#define MCONSOLE_VERSION 2
#define MCONSOLE_MAX_DATA 512
Typedefs
typedef struct private_mconsole_t private_mconsole_t
typedef struct mconsole_request mconsole_request
typedef struct mconsole_reply mconsole_reply
typedef struct mconsole_notify mconsole_notify
Functions
static int request (private_mconsole_t *this, void(*cb)(void *, char *, size_t), void *data, char *command,...)
static void ignore (void *data, char *buf, size_t len)
METHOD (mconsole_t, add_iface, bool, private_mconsole_t *this, char *guest, char *host)
METHOD (mconsole_t, del_iface, bool, private_mconsole_t *this, char *guest)
METHOD (mconsole_t, exec, int, private_mconsole_t *this, void(*cb)(void *, char *, size_t), void *data, char *cmd)
static void wait_bootup (private_mconsole_t *this)
METHOD (mconsole_t, destroy, void, private_mconsole_t *this)
static bool wait_for_notify (private_mconsole_t *this, char *nsock)
static bool setup_console (private_mconsole_t *this)
mconsole_t * mconsole_create (char *notify, void(*idle)(void))
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 19 of file mconsole.c.
#define MCONSOLE_MAGIC 0xcafebabe
Definition at line 32 of file mconsole.c.
Referenced by request(), and wait_for_notify().
#define MCONSOLE_MAX_DATA 512
Definition at line 34 of file mconsole.c.
#define MCONSOLE_VERSION 2
Definition at line 33 of file mconsole.c.
Referenced by request(), and wait_for_notify().
Typedef Documentation
typedef struct mconsole_notify mconsole_notify
Definition at line 73 of file mconsole.c.
typedef struct mconsole_reply mconsole_reply
Definition at line 64 of file mconsole.c.
typedef struct mconsole_request mconsole_request
mconsole message format from "arch/um/include/mconsole.h"
Definition at line 54 of file mconsole.c.
typedef struct private_mconsole_t private_mconsole_t
Definition at line 36 of file mconsole.c.
Function Documentation
static void ignore (void * data, char * buf, size_t len) static
ignore error message
Definition at line 167 of file mconsole.c.
Referenced by install_route(), METHOD(), and wait_bootup().
 {
 }
mconsole_t* mconsole_create (char * notify, void(*)(void) idle)
create the mconsole instance
Definition at line 320 of file mconsole.c.
References close, free(), idle(), INIT, setup_console(), wait_bootup(), and wait_for_notify().
Referenced by METHOD().
 {
     private_mconsole_t *this;
     INIT(this,
         .public = {
             .add_iface = _add_iface,
             .del_iface = _del_iface,
             .exec = _exec,
             .destroy = _destroy,
         },
         .idle = idle,
     );
     if (!wait_for_notify(this, notify))
     {
         free(this);
         return NULL;
     }
     if (!setup_console(this))
     {
         close(this->notify);
         unlink(notify);
         free(this);
         return NULL;
     }
     unlink(notify);
     wait_bootup(this);
     return &this->public;
 }
METHOD (mconsole_t , add_iface , bool , private_mconsole_t * this, char * guest, char * host)
Definition at line 171 of file mconsole.c.
References FALSE, ignore(), request(), TRUE, and usleep().
 {
     int tries = 0;
     while (tries++ < 5)
     {
         if (request(this, ignore, NULL, "config %s=tuntap,%s", guest, host) == 0)
         {
             return TRUE;
         }
         usleep(10000 * tries * tries);
     }
     return FALSE;
 }
METHOD (mconsole_t , del_iface , bool , private_mconsole_t * this, char * guest)
Definition at line 187 of file mconsole.c.
References FALSE, request(), and TRUE.
 {
     if (request(this, NULL, NULL, "remove %s", guest) != 0)
     {
         return FALSE;
     }
     return TRUE;
 }
METHOD (mconsole_t , exec , int , private_mconsole_t * this, void(*)(void *, char *, size_t) cb, void * data, char * cmd)
Definition at line 197 of file mconsole.c.
References cb(), and request().
 {
     return request(this, cb, data, "%s", cmd);
 }
METHOD (mconsole_t , destroy , void , private_mconsole_t * this)
Definition at line 220 of file mconsole.c.
References close, free(), and notify().
 {
     close(this->console);
     close(this->notify);
     free(this);
 }
static int request (private_mconsole_t * this, void(*)(void *, char *, size_t) cb, void * data, char * command, ...) static
send a request to UML using mconsole
Definition at line 91 of file mconsole.c.
References cb(), mconsole_request::data, mconsole_reply::data, DBG1, DBG_LIB, mconsole_reply::err, flags, idle(), len, mconsole_request::len, mconsole_reply::len, mconsole_request::magic, MCONSOLE_MAGIC, MCONSOLE_VERSION, memset, mconsole_reply::more, MSG_DONTWAIT, recv, sendto, mconsole_request::version, and vsnprintf.
Referenced by add_policy_internal(), build_requestList(), CALLBACK(), create_publish_request(), dispatch(), fetch_ocsp(), get_replay_state(), get_route(), get_spi_internal(), init_address_list(), manage_bypass(), manage_ipaddr(), manage_rule(), manage_srcroute(), METHOD(), radius_receive(), receive(), register_pfkey_socket(), scep_build_request(), START_TEST(), verify_eap(), verify_radius(), and wait_bootup().
 {
     mconsole_request request;
     mconsole_reply reply;
     int len, flags = 0;
     va_list args;
     memset(&request, 0, sizeof(request));
     request.magic = MCONSOLE_MAGIC;
     request.version = MCONSOLE_VERSION;
     va_start(args, command);
     request.len = vsnprintf(request.data, sizeof(request.data), command, args);
     va_end(args);
     if (this->idle)
     {
         flags = MSG_DONTWAIT;
     }
     do
     {
         if (this->idle)
         {
             this->idle();
         }
         len = sendto(this->console, &request, sizeof(request), flags,
                      (struct sockaddr*)&this->uml, sizeof(this->uml));
     }
     while (len < 0 && (errno == EINTR || errno == EAGAIN));
     if (len < 0)
     {
         DBG1(DBG_LIB, "sending mconsole command to UML failed: %m");
         return -1;
     }
     do
     {
         len = recv(this->console, &reply, sizeof(reply), flags);
         if (len < 0 && (errno == EINTR || errno == EAGAIN))
         {
             if (this->idle)
             {
                 this->idle();
             }
             continue;
         }
         if (len < 0)
         {
             DBG1(DBG_LIB, "receiving from mconsole failed: %m");
             return -1;
         }
         if (len > 0)
         {
             if (cb)
             {
                 cb(data, reply.data, reply.len);
             }
             else if (reply.err)
             {
                 if (reply.len && *reply.data)
                 {
                     DBG1(DBG_LIB, "received mconsole error %d: %.*s",
                          reply.err, (int)reply.len, reply.data);
                 }
                 break;
             }
         }
     }
     while (reply.more);
     return reply.err;
 }
static bool setup_console (private_mconsole_t * this) static
setup the mconsole console connection
Definition at line 293 of file mconsole.c.
References bind, close, DBG1, DBG_LIB, FALSE, memset, snprintf, socket, and TRUE.
Referenced by mconsole_create().
 {
     struct sockaddr_un addr;
     this->console = socket(AF_UNIX, SOCK_DGRAM, 0);
     if (this->console < 0)
     {
         DBG1(DBG_LIB, "opening mconsole socket failed: %m");
         return FALSE;
     }
     memset(&addr, 0, sizeof(addr));
     addr.sun_family = AF_UNIX;
     snprintf(&addr.sun_path[1], sizeof(addr.sun_path)-1, "%5d-%d",
              getpid(), this->console);
     if (bind(this->console, (struct sockaddr*)&addr, sizeof(addr)) < 0)
     {
         DBG1(DBG_LIB, "binding mconsole socket to '%s' failed: %m",
              &addr.sun_path[1]);
         close(this->console);
         return FALSE;
     }
     return TRUE;
 }
static void wait_bootup (private_mconsole_t * this) static
Poll until guest is ready
Definition at line 207 of file mconsole.c.
References idle(), ignore(), request(), and usleep().
Referenced by mconsole_create().
 {
     /* wait for init process to appear */
     while (request(this, ignore, NULL, "exec ps -p 1 > /dev/null"))
     {
         if (this->idle)
         {
             this->idle();
         }
         usleep(100000);
     }
 }
static bool wait_for_notify (private_mconsole_t * this, char * nsock) static
setup the mconsole notify connection and wait for its readiness
Definition at line 231 of file mconsole.c.
References bind, close, DBG1, DBG_LIB, FALSE, flags, idle(), len, MCONSOLE_MAGIC, MCONSOLE_VERSION, memset, MSG_DONTWAIT, notify(), recvfrom, socket, and TRUE.
Referenced by mconsole_create().
 {
     struct sockaddr_un addr;
     mconsole_notify notify;
     int len, flags = 0;
     this->notify = socket(AF_UNIX, SOCK_DGRAM, 0);
     if (this->notify < 0)
     {
         DBG1(DBG_LIB, "opening mconsole notify socket failed: %m");
         return FALSE;
     }
     memset(&addr, 0, sizeof(addr));
     addr.sun_family = AF_UNIX;
     strncpy(addr.sun_path, nsock, sizeof(addr.sun_path));
     if (bind(this->notify, (struct sockaddr*)&addr, sizeof(addr)) < 0)
     {
         DBG1(DBG_LIB, "binding mconsole notify socket to '%s' failed: %m",
              nsock);
         close(this->notify);
         return FALSE;
     }
     if (this->idle)
     {
         flags = MSG_DONTWAIT;
     }
     do
     {
         if (this->idle)
         {
             this->idle();
         }
         len = recvfrom(this->notify, &notify, sizeof(notify), flags, NULL, 0);
     }
     while (len < 0 && (errno == EINTR || errno == EAGAIN));
     if (len < 0 || len >= sizeof(notify))
     {
         DBG1(DBG_LIB, "reading from mconsole notify socket failed: %m");
         close(this->notify);
         unlink(nsock);
         return FALSE;
     }
     if (notify.magic != MCONSOLE_MAGIC ||
         notify.version != MCONSOLE_VERSION ||
         notify.type != MCONSOLE_SOCKET)
     {
         DBG1(DBG_LIB, "received unexpected message from mconsole notify"
              " socket: %b", &notify, sizeof(notify));
         close(this->notify);
         unlink(nsock);
         return FALSE;
     }
     memset(&this->uml, 0, sizeof(this->uml));
     this->uml.sun_family = AF_UNIX;
     strncpy(this->uml.sun_path, (char*)&notify.data, sizeof(this->uml.sun_path));
     return TRUE;
 }