strongSwan: id_payload_t Struct Reference
id_payload_t Struct Reference
id_payload
#include "id_payload.h"
Public Attributes
payload_t payload_interface
identification_t *(* get_identification)(id_payload_t *this)
traffic_selector_t *(* get_ts)(id_payload_t *this)
chunk_t(* get_encoded)(id_payload_t *this)
void(* destroy)(id_payload_t *this)
Detailed Description
Object representing an IKEv1 or an IKEv2 ID payload.
Definition at line 36 of file id_payload.h.
Member Data Documentation
void(* id_payload_t::destroy)(id_payload_t *this)
Destroys an id_payload_t object.
Definition at line 67 of file id_payload.h.
chunk_t(* id_payload_t::get_encoded)(id_payload_t *this)
Get encoded payload without fixed payload header (used for IKEv1).
Returns
encoded payload (gets allocated)
Definition at line 62 of file id_payload.h.
Referenced by METHOD().
identification_t*(* id_payload_t::get_identification)(id_payload_t *this)
Creates an identification object of this id payload.
Returns
identification_t object
Definition at line 48 of file id_payload.h.
Referenced by METHOD().
traffic_selector_t*(* id_payload_t::get_ts)(id_payload_t *this)
Creates a traffic selector form a ID_ADDR_SUBNET/RANGE identity.
Returns
traffic selector, NULL on failure
Definition at line 55 of file id_payload.h.
Referenced by get_ts(), and METHOD().
payload_t id_payload_t::payload_interface
The payload_t interface.
Definition at line 41 of file id_payload.h.
Referenced by add_ts(), get_reserved_id_bytes(), and METHOD().
The documentation for this struct was generated from the following file:
id_payload.h