strongSwan: ietf_attr_product_info.c File Reference
ietf_attr_product_info.c File Reference
#include "ietf_attr_product_info.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_product_info_t
Macros
#define PRODUCT_INFO_MIN_SIZE 5
Typedefs
typedef struct
private_ietf_attr_product_info_t private_ietf_attr_product_info_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_product_info_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_product_info_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_product_info_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_product_info_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_product_info_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_product_info_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_product_info_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_product_info_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_product_info_t *this)
METHOD (ietf_attr_product_info_t, get_info, chunk_t, private_ietf_attr_product_info_t *this, pen_t *vendor_id, u_int16_t *id)
pa_tnc_attr_t * ietf_attr_product_info_create (pen_t vendor_id, u_int16_t id, chunk_t name)
pa_tnc_attr_t * ietf_attr_product_info_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define PRODUCT_INFO_MIN_SIZE 5
PA-TNC Product Information type (see section 4.2.2 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Product Vendor ID | Product ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Product ID | Product Name (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 37 of file ietf_attr_product_info.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_product_info_t private_ietf_attr_product_info_t
Definition at line 23 of file ietf_attr_product_info.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_product_info_t * this)
Definition at line 90 of file ietf_attr_product_info.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_product_info_t * this)
Definition at line 96 of file ietf_attr_product_info.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_product_info_t * this)
Definition at line 102 of file ietf_attr_product_info.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_product_info_t * this, bool noskip)
Definition at line 108 of file ietf_attr_product_info.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_product_info_t * this)
Definition at line 114 of file ietf_attr_product_info.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, PRODUCT_INFO_MIN_SIZE, value, bio_writer_t::write_data, bio_writer_t::write_uint16, and bio_writer_t::write_uint24.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PRODUCT_INFO_MIN_SIZE);
     writer->write_uint24(writer, this->product_vendor_id);
     writer->write_uint16(writer, this->product_id);
     writer->write_data  (writer, this->product_name);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_product_info_t * this, u_int32_t * offset)
Definition at line 133 of file ietf_attr_product_info.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, PRODUCT_INFO_MIN_SIZE, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint24, bio_reader_t::remaining, SUCCESS, and value.
 {
     bio_reader_t *reader;
     chunk_t product_name;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PRODUCT_INFO_MIN_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for IETF product information");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint24(reader, &this->product_vendor_id);
     reader->read_uint16(reader, &this->product_id);
     reader->read_data  (reader, reader->remaining(reader), &product_name);
     reader->destroy(reader);
     if (!this->product_vendor_id && this->product_id)
     {
         DBG1(DBG_TNC, "IETF product information vendor ID is 0 "
                       "but product ID is not 0");
         *offset = 3;
         return FAILED;
     }
     this->product_name = chunk_clone(product_name);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_product_info_t * this, chunk_t segment)
Definition at line 168 of file ietf_attr_product_info.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_product_info_t * this)
Definition at line 174 of file ietf_attr_product_info.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_product_info_t * this)
Definition at line 181 of file ietf_attr_product_info.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->product_name.ptr);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_product_info_t , get_info , chunk_t , private_ietf_attr_product_info_t * this, pen_t * vendor_id, u_int16_t * id)
Definition at line 192 of file ietf_attr_product_info.c.
 {
     if (vendor_id)
     {
         *vendor_id = this->product_vendor_id;
     }
     if (id)
     {
         *id = this->product_id;
     }
     return this->product_name;
 }