strongSwan: connmark_listener.c File Reference
connmark_listener.c File Reference
#include "connmark_listener.h"
#include <daemon.h>
#include <errno.h>
#include <libiptc/libiptc.h>
#include <linux/netfilter/xt_esp.h>
#include <linux/netfilter/xt_tcpudp.h>
#include <linux/netfilter/xt_MARK.h>
#include <linux/netfilter/xt_policy.h>
#include <linux/netfilter/xt_CONNMARK.h>
Classes
struct private_connmark_listener_t
Typedefs
typedef struct
private_connmark_listener_t private_connmark_listener_t
Functions
static bool ts2in (traffic_selector_t *ts, struct in_addr *addr, struct in_addr *mask)
static bool host2in (host_t *host, struct in_addr *addr, struct in_addr *mask)
static bool manage_rule (struct iptc_handle *ipth, const char *chain, bool add, struct ipt_entry *e)
static bool manage_pre_esp_in_udp (private_connmark_listener_t *this, struct iptc_handle *ipth, bool add, u_int mark, u_int32_t spi, host_t *dst, host_t *src)
static bool manage_pre_esp (private_connmark_listener_t *this, struct iptc_handle *ipth, bool add, u_int mark, u_int32_t spi, host_t *dst, host_t *src)
static bool manage_pre (private_connmark_listener_t *this, struct iptc_handle *ipth, bool add, u_int mark, u_int32_t spi, bool encap, host_t *dst, host_t *src)
static bool manage_in (private_connmark_listener_t *this, struct iptc_handle *ipth, bool add, u_int mark, u_int32_t spi, traffic_selector_t *dst, traffic_selector_t *src)
static bool manage_out (private_connmark_listener_t *this, struct iptc_handle *ipth, bool add, traffic_selector_t *dst, traffic_selector_t *src)
static struct iptc_handle * init_handle ()
static bool commit_handle (struct iptc_handle *ipth)
static bool manage_policies (private_connmark_listener_t *this, struct iptc_handle *ipth, host_t *dst, host_t *src, bool encap, child_sa_t *child_sa, bool add)
static bool handle_sa (child_sa_t *child_sa)
METHOD (listener_t, child_updown, bool, private_connmark_listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool up)
METHOD (listener_t, child_rekey, bool, private_connmark_listener_t *this, ike_sa_t *ike_sa, child_sa_t *old, child_sa_t *new)
METHOD (listener_t, ike_update, bool, private_connmark_listener_t *this, ike_sa_t *ike_sa, bool local, host_t *new)
METHOD (connmark_listener_t, destroy, void, private_connmark_listener_t *this)
connmark_listener_t * connmark_listener_create ()
Typedef Documentation
typedef struct private_connmark_listener_t private_connmark_listener_t
Definition at line 29 of file connmark_listener.c.
Function Documentation
static bool commit_handle (struct iptc_handle * ipth) static
Commit iptables rules, log error
Definition at line 355 of file connmark_listener.c.
References DBG1, DBG_CFG, FALSE, and TRUE.
Referenced by METHOD().
 {
     if (iptc_commit(ipth))
     {
         return TRUE;
     }
     DBG1(DBG_CFG, "forecast iptables commit failed: %s", iptc_strerror(errno));
     return FALSE;
 }
static bool handle_sa (child_sa_t * child_sa) static
Check if rules should be installed for given CHILD_SA
Definition at line 400 of file connmark_listener.c.
References FALSE, child_sa_t::get_mark, child_sa_t::get_mode, child_sa_t::get_protocol, MODE_TRANSPORT, PROTO_ESP, TRUE, and mark_t::value.
Referenced by METHOD().
 {
     return child_sa->get_mark(child_sa, TRUE).value &&
            child_sa->get_mark(child_sa, FALSE).value &&
            child_sa->get_mode(child_sa) == MODE_TRANSPORT &&
            child_sa->get_protocol(child_sa) == PROTO_ESP;
 }
static bool host2in (host_t * host, struct in_addr * addr, struct in_addr * mask) static
Convert an (IPv4) host to an address with mask
Definition at line 65 of file connmark_listener.c.
References FALSE, host_t::get_address, host_t::get_family, memcpy, chunk_t::ptr, and TRUE.
Referenced by manage_pre_esp(), and manage_pre_esp_in_udp().
 {
     if (host->get_family(host) == AF_INET)
     {
         memcpy(&addr->s_addr, host->get_address(host).ptr, 4);
         mask->s_addr = ~0;
         return TRUE;
     }
     return FALSE;
 }
static struct iptc_handle* init_handle () static
Initialize iptables handle, log error
Definition at line 339 of file connmark_listener.c.
References DBG1, and DBG_CFG.
Referenced by METHOD().
 {
     struct iptc_handle *ipth;
     ipth = iptc_init("mangle");
     if (ipth)
     {
         return ipth;
     }
     DBG1(DBG_CFG, "initializing iptables failed: %s", iptc_strerror(errno));
     return NULL;
 }
static bool manage_in (private_connmark_listener_t * this, struct iptc_handle * ipth, bool add, u_int mark, u_int32_t spi, traffic_selector_t * dst, traffic_selector_t * src) static
Add inbound rule applying CONNMARK to matching traffic
Definition at line 236 of file connmark_listener.c.
References FALSE, m, manage_rule(), and ts2in().
Referenced by manage_policies().
 {
     struct {
         struct ipt_entry e;
         struct ipt_entry_match m;
         struct xt_policy_info p;
         struct ipt_entry_target t;
         struct xt_connmark_tginfo1 cm;
     } ipt = {
         .e  = {
             .target_offset = XT_ALIGN(sizeof(ipt.e) + sizeof(ipt.m) +
                                       sizeof(ipt.p)),
             .next_offset = sizeof(ipt),
         },
         .m = {
             .u = {
                 .user = {
                     .match_size = XT_ALIGN(sizeof(ipt.m) + sizeof(ipt.p)),
                     .name = "policy",
                 },
             },
         },
         .p = {
             .pol = {
                 {
                     .spi = spi,
                     .match.spi = 1,
                 },
             },
             .len = 1,
             .flags = XT_POLICY_MATCH_IN,
         },
         .t = {
             .u = {
                 .user = {
                     .target_size = XT_ALIGN(sizeof(ipt.t) + sizeof(ipt.cm)),
                     .name = "CONNMARK",
                     .revision = 1,
                 },
             },
         },
         .cm = {
             .ctmark = mark,
             .ctmask = ~0,
             .nfmask = ~0,
             .mode = XT_CONNMARK_SET,
         },
     };
     if (!ts2in(dst, &ipt.e.ip.dst, &ipt.e.ip.dmsk) ||
         !ts2in(src, &ipt.e.ip.src, &ipt.e.ip.smsk))
     {
         return FALSE;
     }
     return manage_rule(ipth, "INPUT", add, &ipt.e);
 }
static bool manage_out (private_connmark_listener_t * this, struct iptc_handle * ipth, bool add, traffic_selector_t * dst, traffic_selector_t * src) static
Add outbund rule restoring CONNMARK on matching traffic
Definition at line 299 of file connmark_listener.c.
References FALSE, manage_rule(), and ts2in().
Referenced by manage_policies().
 {
     struct {
         struct ipt_entry e;
         struct ipt_entry_target t;
         struct xt_connmark_tginfo1 cm;
     } ipt = {
         .e  = {
             .target_offset = XT_ALIGN(sizeof(ipt.e)),
             .next_offset = sizeof(ipt),
         },
         .t = {
             .u = {
                 .user = {
                     .target_size = XT_ALIGN(sizeof(ipt.t) + sizeof(ipt.cm)),
                     .name = "CONNMARK",
                     .revision = 1,
                 },
             },
         },
         .cm = {
             .ctmask = ~0,
             .nfmask = ~0,
             .mode = XT_CONNMARK_RESTORE,
         },
     };
     if (!ts2in(dst, &ipt.e.ip.dst, &ipt.e.ip.dmsk) ||
         !ts2in(src, &ipt.e.ip.src, &ipt.e.ip.smsk))
     {
         return FALSE;
     }
     return manage_rule(ipth, "OUTPUT", add, &ipt.e);
 }
static bool manage_policies (private_connmark_listener_t * this, struct iptc_handle * ipth, host_t * dst, host_t * src, bool encap, child_sa_t * child_sa, bool add) static
Add/Remove policies for a CHILD_SA using a iptables handle
Definition at line 368 of file connmark_listener.c.
References child_sa_t::create_policy_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, child_sa_t::get_mark, child_sa_t::get_spi, manage_in(), manage_out(), manage_pre(), TRUE, and mark_t::value.
Referenced by METHOD().
 {
     traffic_selector_t *local, *remote;
     enumerator_t *enumerator;
     u_int32_t spi;
     u_int mark;
     bool done = TRUE;
     spi = child_sa->get_spi(child_sa, TRUE);
     mark = child_sa->get_mark(child_sa, TRUE).value;
     enumerator = child_sa->create_policy_enumerator(child_sa);
     while (enumerator->enumerate(enumerator, &local, &remote))
     {
         if (!manage_pre(this, ipth, add, mark, spi, encap, dst, src) ||
             !manage_in(this, ipth, add, mark, spi, local, remote) ||
             !manage_out(this, ipth, add, remote, local))
         {
             done = FALSE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return done;
 }
static bool manage_pre (private_connmark_listener_t * this, struct iptc_handle * ipth, bool add, u_int mark, u_int32_t spi, bool encap, host_t * dst, host_t * src) static
Add rule marking ESP packets to match the correct policy
Definition at line 221 of file connmark_listener.c.
References manage_pre_esp(), and manage_pre_esp_in_udp().
Referenced by manage_policies().
 {
     if (encap)
     {
         return manage_pre_esp_in_udp(this, ipth, add, mark, spi, dst, src);
     }
     return manage_pre_esp(this, ipth, add, mark, spi, dst, src);
 }
static bool manage_pre_esp (private_connmark_listener_t * this, struct iptc_handle * ipth, bool add, u_int mark, u_int32_t spi, host_t * dst, host_t * src) static
Add rule marking non-encapsulated ESP packets to match the correct policy
Definition at line 164 of file connmark_listener.c.
References FALSE, host2in(), ip, and manage_rule().
Referenced by manage_pre().
 {
     struct {
         struct ipt_entry e;
         struct ipt_entry_match m;
         struct xt_esp esp;
         struct ipt_entry_target t;
         struct xt_mark_tginfo2 tm;
     } ipt = {
         .e  = {
             .target_offset = XT_ALIGN(sizeof(ipt.e) + sizeof(ipt.m) +
                                       sizeof(ipt.esp)),
             .next_offset = sizeof(ipt),
             .ip = {
                 .proto = IPPROTO_ESP,
             },
         },
         .m = {
             .u = {
                 .user = {
                     .match_size = XT_ALIGN(sizeof(ipt.m) + sizeof(ipt.esp)),
                     .name = "esp",
                 },
             },
         },
         .esp = {
             .spis = { htonl(spi), htonl(spi) },
         },
         .t = {
             .u = {
                 .user = {
                     .target_size = XT_ALIGN(sizeof(ipt.t) + sizeof(ipt.tm)),
                     .name = "MARK",
                     .revision = 2,
                 },
             },
         },
         .tm = {
             .mark = mark,
             .mask = ~0,
         },
     };
     if (!host2in(dst, &ipt.e.ip.dst, &ipt.e.ip.dmsk) ||
         !host2in(src, &ipt.e.ip.src, &ipt.e.ip.smsk))
     {
         return FALSE;
     }
     return manage_rule(ipth, "PREROUTING", add, &ipt.e);
 }
static bool manage_pre_esp_in_udp (private_connmark_listener_t * this, struct iptc_handle * ipth, bool add, u_int mark, u_int32_t spi, host_t * dst, host_t * src) static
Add rule marking UDP-encapsulated ESP packets to match the correct policy
Definition at line 106 of file connmark_listener.c.
References FALSE, host_t::get_port, host2in(), ip, and manage_rule().
Referenced by manage_pre().
 {
     struct {
         struct ipt_entry e;
         struct ipt_entry_match m;
         struct xt_udp udp;
         struct ipt_entry_target t;
         struct xt_mark_tginfo2 tm;
     } ipt = {
         .e  = {
             .target_offset = XT_ALIGN(sizeof(ipt.e) + sizeof(ipt.m) +
                                       sizeof(ipt.udp)),
             .next_offset = sizeof(ipt),
             .ip = {
                 .proto = IPPROTO_UDP,
             },
         },
         .m = {
             .u = {
                 .user = {
                     .match_size = XT_ALIGN(sizeof(ipt.m) + sizeof(ipt.udp)),
                     .name = "udp",
                 },
             },
         },
         .udp = {
             .spts = { src->get_port(src), src->get_port(src) },
             .dpts = { dst->get_port(dst), dst->get_port(dst) },
         },
         .t = {
             .u = {
                 .user = {
                     .target_size = XT_ALIGN(sizeof(ipt.t) + sizeof(ipt.tm)),
                     .name = "MARK",
                     .revision = 2,
                 },
             },
         },
         .tm = {
             .mark = mark,
             .mask = ~0,
         },
     };
     if (!host2in(dst, &ipt.e.ip.dst, &ipt.e.ip.dmsk) ||
         !host2in(src, &ipt.e.ip.src, &ipt.e.ip.smsk))
     {
         return FALSE;
     }
     return manage_rule(ipth, "PREROUTING", add, &ipt.e);
 }
static bool manage_rule (struct iptc_handle * ipth, const char * chain, bool add, struct ipt_entry * e) static
Add or remove a rule to/from the specified chain
Definition at line 79 of file connmark_listener.c.
References DBG1, DBG_CFG, FALSE, and TRUE.
Referenced by manage_in(), manage_out(), manage_pre_esp(), and manage_pre_esp_in_udp().
 {
     if (add)
     {
         if (!iptc_insert_entry(chain, e, 0, ipth))
         {
             DBG1(DBG_CFG, "appending %s rule failed: %s",
                  chain, iptc_strerror(errno));
             return FALSE;
         }
     }
     else
     {
         if (!iptc_delete_entry(chain, e, "", ipth))
         {
             DBG1(DBG_CFG, "deleting %s rule failed: %s",
                  chain, iptc_strerror(errno));
             return FALSE;
         }
     }
     return TRUE;
 }
METHOD (listener_t , child_updown , bool , private_connmark_listener_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, bool up)
Definition at line 408 of file connmark_listener.c.
References commit_handle(), dst, ike_sa_t::get_my_host, ike_sa_t::get_other_host, handle_sa(), child_sa_t::has_encap, init_handle(), manage_policies(), src, and TRUE.
 {
     struct iptc_handle *ipth;
     host_t *dst, *src;
     bool encap;
     dst = ike_sa->get_my_host(ike_sa);
     src = ike_sa->get_other_host(ike_sa);
     encap = child_sa->has_encap(child_sa);
     if (handle_sa(child_sa))
     {
         ipth = init_handle();
         if (ipth)
         {
             if (manage_policies(this, ipth, dst, src, encap, child_sa, up))
             {
                 commit_handle(ipth);
             }
             iptc_free(ipth);
         }
     }
     return TRUE;
 }
METHOD (listener_t , child_rekey , bool , private_connmark_listener_t * this, ike_sa_t * ike_sa, child_sa_t * old, child_sa_t * new)
Definition at line 435 of file connmark_listener.c.
References commit_handle(), dst, FALSE, ike_sa_t::get_my_host, ike_sa_t::get_other_host, handle_sa(), child_sa_t::has_encap, init_handle(), manage_policies(), src, and TRUE.
 {
     struct iptc_handle *ipth;
     host_t *dst, *src;
     bool oldencap, newencap;
     dst = ike_sa->get_my_host(ike_sa);
     src = ike_sa->get_other_host(ike_sa);
     oldencap = old->has_encap(old);
     newencap = new->has_encap(new);
     if (handle_sa(old))
     {
         ipth = init_handle();
         if (ipth)
         {
             if (manage_policies(this, ipth, dst, src, oldencap, old, FALSE) &&
                 manage_policies(this, ipth, dst, src, newencap, new, TRUE))
             {
                 commit_handle(ipth);
             }
             iptc_free(ipth);
         }
     }
     return TRUE;
 }
METHOD (listener_t , ike_update , bool , private_connmark_listener_t * this, ike_sa_t * ike_sa, bool local, host_t * new)
Definition at line 464 of file connmark_listener.c.
References commit_handle(), COND_NAT_ANY, ike_sa_t::create_child_sa_enumerator, enumerator_t::destroy, dst, enumerator_t::enumerate, FALSE, ike_sa_t::get_my_host, ike_sa_t::get_other_host, handle_sa(), ike_sa_t::has_condition, child_sa_t::has_encap, init_handle(), manage_policies(), src, and TRUE.
 {
     struct iptc_handle *ipth;
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     host_t *dst, *src;
     bool oldencap, newencap;
     if (local)
     {
         dst = new;
         src = ike_sa->get_other_host(ike_sa);
     }
     else
     {
         dst = ike_sa->get_my_host(ike_sa);
         src = new;
     }
     /* during ike_update(), has_encap() on the CHILD_SA has not yet been
      * updated, but shows the old state. */
     newencap = ike_sa->has_condition(ike_sa, COND_NAT_ANY);
     enumerator = ike_sa->create_child_sa_enumerator(ike_sa);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         if (handle_sa(child_sa))
         {
             oldencap = child_sa->has_encap(child_sa);
             ipth = init_handle();
             if (ipth)
             {
                 if (manage_policies(this, ipth, dst, src, oldencap,
                                     child_sa, FALSE) &&
                     manage_policies(this, ipth, dst, src, newencap,
                                     child_sa, TRUE))
                 {
                     commit_handle(ipth);
                 }
                 iptc_free(ipth);
             }
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 }
METHOD (connmark_listener_t , destroy , void , private_connmark_listener_t * this)
Definition at line 513 of file connmark_listener.c.
References free().
 {
     free(this);
 }
static bool ts2in (traffic_selector_t * ts, struct in_addr * addr, struct in_addr * mask) static
Convert an (IPv4) traffic selector to an address and mask
Definition at line 45 of file connmark_listener.c.
References bits, host_t::destroy, FALSE, host_t::get_address, traffic_selector_t::get_type, memcpy, net, chunk_t::ptr, traffic_selector_t::to_subnet, TRUE, and TS_IPV4_ADDR_RANGE.
Referenced by manage_in(), and manage_out().
 {
     u_int8_t bits;
     host_t *net;
     if (ts->get_type(ts) == TS_IPV4_ADDR_RANGE &&
         ts->to_subnet(ts, &net, &bits))
     {
         memcpy(&addr->s_addr, net->get_address(net).ptr, 4);
         net->destroy(net);
         mask->s_addr = htonl(0xffffffffU << (32 - bits));
         return TRUE;
     }
     return FALSE;
 }