strongSwan: tnccs_20_server
tnccs_20_server
tnccs_20
Classes
struct tnccs_20_server_t
Typedefs
typedef struct tnccs_20_server_t tnccs_20_server_t
Functions
tnccs_20_handler_t * tnccs_20_server_create (tnccs_t *tnccs, tnccs_send_message_t send_msg, size_t max_batch_len, size_t max_msg_len, bool eap_transport)
Detailed Description
Typedef Documentation
typedef struct tnccs_20_server_t tnccs_20_server_t
Definition at line 30 of file tnccs_20_server.h.
Function Documentation
tnccs_20_handler_t* tnccs_20_server_create (tnccs_t * tnccs, tnccs_send_message_t send_msg, size_t max_batch_len, size_t max_msg_len, bool eap_transport)
Create an instance of the TNC IF-TNCCS 2.0 server-side protocol handler.
Parameters
tnccs TNC IF-TNCCS 2.0 stack
send_msg TNF IF-TNCCS 2.0 send message callback function
max_batch_len Maximum PB-TNC batch size
max_msg_len Maximum PA-TNC message size
eap_transport TRUE if IF-T for EAP methods
See header
Definition at line 649 of file tnccs_20_server.c.
References tnccs_manager_t::create_connection, destroy(), tnc_t::imvs, INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, imv_manager_t::notify_connection_change, PB_BATCH_SDATA, pb_tnc_state_machine_create(), tnc, TNC_CONNECTION_STATE_CREATE, tnc_t::tnccs, TNCCS_2_0, and TRUE.
Referenced by METHOD().
 {
     private_tnccs_20_server_t *this;
     INIT(this,
         .public = {
             .handler = {
                 .process = _process,
                 .build = _build,
                 .begin_handshake = _begin_handshake,
                 .get_send_flag = _get_send_flag,
                 .get_mutual = _get_mutual,
                 .get_state = _get_state,
                 .add_msg = _add_msg,
                 .handle_errors = _handle_errors,
                 .destroy = _destroy,
             },
             .have_recommendation = _have_recommendation,
         },
         .state_machine = pb_tnc_state_machine_create(TRUE),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .messages = linked_list_create(),
         .batch_type = PB_BATCH_SDATA,
         .max_batch_len = max_batch_len,
         .eap_transport = eap_transport,
     );
     this->connection_id = tnc->tnccs->create_connection(tnc->tnccs,
                                             TNCCS_2_0, tnccs, send_msg,
                                             &this->request_handshake_retry,
                                             max_msg_len, &this->recs);
     if (!this->connection_id)
     {
         destroy(this);
         return NULL;
     }
     tnc->imvs->notify_connection_change(tnc->imvs, this->connection_id,
                                         TNC_CONNECTION_STATE_CREATE);
     return &this->public.handler;
 }