strongSwan: gateway_t Struct Reference
gateway_t Struct Reference
gateway
#include "gateway.h"
Public Attributes
char *(* request)(gateway_t *this, char *xml,...)
enumerator_t *(* query_ikesalist)(gateway_t *this)
enumerator_t *(* query_configlist)(gateway_t *this)
enumerator_t *(* terminate)(gateway_t *this, bool ike, u_int32_t id)
enumerator_t *(* initiate)(gateway_t *this, bool ike, char *name)
void(* destroy)(gateway_t *this)
Detailed Description
A connection to a gateway.
Definition at line 32 of file gateway.h.
Member Data Documentation
void(* gateway_t::destroy)(gateway_t *this)
Destroy a gateway instance.
Definition at line 78 of file gateway.h.
enumerator_t*(* gateway_t::initiate)(gateway_t *this, bool ike, char *name)
Initiate an IKE or a CHILD SA.
Parameters
ike TRUE for IKE-, FALSE for CHILD-SA
name name of the peer/child config
Returns
enumerator over control response XML children
Definition at line 73 of file gateway.h.
Referenced by initiate().
enumerator_t*(* gateway_t::query_configlist)(gateway_t *this)
Query the list of peer configs and its subconfigs.
Returns
enumerator over peerconfig XML elements
Definition at line 55 of file gateway.h.
Referenced by list().
enumerator_t*(* gateway_t::query_ikesalist)(gateway_t *this)
Query the list of IKE_SAs and all its children.
Returns
enumerator over ikesa XML elements
Definition at line 48 of file gateway.h.
Referenced by list().
char*(* gateway_t::request)(gateway_t *this, char *xml,...)
Send an XML request to the gateway.
Parameters
xml xml request string
... printf style argument list for xml request string
Returns
allocated xml response string
Definition at line 41 of file gateway.h.
enumerator_t*(* gateway_t::terminate)(gateway_t *this, bool ike, u_int32_t id)
Terminate an IKE or a CHILD SA.
Parameters
ike TRUE for IKE-, FALSE for a CHILD-SA
id ID of the SA to terminate
Returns
enumerator over control response XML children
Definition at line 64 of file gateway.h.
Referenced by terminate().
The documentation for this struct was generated from the following file:
gateway.h