strongSwan: child_sa
child_sa
sa
Classes
struct child_sa_t
Typedefs
typedef enum child_sa_state_t child_sa_state_t
typedef struct child_sa_t child_sa_t
Enumerations
enum child_sa_state_t {
CHILD_CREATED, CHILD_ROUTED, CHILD_INSTALLING, CHILD_INSTALLED,
CHILD_UPDATING, CHILD_REKEYING, CHILD_REKEYED, CHILD_RETRYING,
CHILD_DELETING, CHILD_DESTROYING
}
Functions
child_sa_t * child_sa_create (host_t *me, host_t *other, child_cfg_t *config, u_int32_t reqid, bool encap, u_int mark_in, u_int mark_out)
Variables
enum_name_t * child_sa_state_names
Detailed Description
Typedef Documentation
typedef enum child_sa_state_t child_sa_state_t
Definition at line 26 of file child_sa.h.
typedef struct child_sa_t child_sa_t
Definition at line 27 of file child_sa.h.
Enumeration Type Documentation
enum child_sa_state_t
States of a CHILD_SA
Enumerator
CHILD_CREATED
Just created, uninstalled CHILD_SA
CHILD_ROUTED
Installed SPD, but no SAD entries
CHILD_INSTALLING
Installing an in-use CHILD_SA
CHILD_INSTALLED
Installed an in-use CHILD_SA
CHILD_UPDATING
While updating hosts, in update_hosts()
CHILD_REKEYING
CHILD_SA which is rekeying
CHILD_REKEYED
CHILD_SA that was rekeyed, but stays installed
CHILD_RETRYING
CHILD_SA negotiation failed, but gets retried
CHILD_DELETING
CHILD_SA in progress of delete
CHILD_DESTROYING
CHILD_SA object gets destroyed
Definition at line 38 of file child_sa.h.
                       {
     CHILD_CREATED,
     CHILD_ROUTED,
     CHILD_INSTALLING,
     CHILD_INSTALLED,
     CHILD_UPDATING,
     CHILD_REKEYING,
     CHILD_REKEYED,
     CHILD_RETRYING,
     CHILD_DELETING,
     CHILD_DESTROYING,
 };
Function Documentation
child_sa_t* child_sa_create (host_t * me, host_t * other, child_cfg_t * config, u_int32_t rekey, bool encap, u_int mark_in, u_int mark_out)
Constructor to create a child SA negotiated with IKE.
Parameters
me own address
other remote address
config config to use for this CHILD_SA
reqid reqid of old CHILD_SA when rekeying, 0 otherwise
encap TRUE to enable UDP encapsulation (NAT traversal)
mark_in explicit inbound mark value to use, 0 for config
mark_out explicit outbound mark value to use, 0 for config
Returns
child_sa_t object
Described in header.
Definition at line 1215 of file child_sa.c.
References array_create(), charon, CHILD_CREATED, host_t::clone, FALSE, trap_manager_t::find_reqid, child_cfg_t::get_close_action, child_cfg_t::get_dpd_action, child_cfg_t::get_mark, get_proxy_addr(), child_cfg_t::get_ref, child_cfg_t::get_reqid, INIT, IPCOMP_NONE, MARK_UNIQUE, MODE_TRANSPORT, MODE_TUNNEL, PROTO_NONE, ref_get(), time_monotonic(), daemon_t::traps, TRUE, and unique_id.
Referenced by METHOD(), and process_child_add().
 {
     private_child_sa_t *this;
     static refcount_t unique_id = 0, unique_mark = 0, mark;
     INIT(this,
         .public = {
             .get_name = _get_name,
             .get_reqid = _get_reqid,
             .get_unique_id = _get_unique_id,
             .get_config = _get_config,
             .get_state = _get_state,
             .set_state = _set_state,
             .get_spi = _get_spi,
             .get_cpi = _get_cpi,
             .get_protocol = _get_protocol,
             .set_protocol = _set_protocol,
             .get_mode = _get_mode,
             .set_mode = _set_mode,
             .get_proposal = _get_proposal,
             .set_proposal = _set_proposal,
             .get_lifetime = _get_lifetime,
             .get_installtime = _get_installtime,
             .get_usestats = _get_usestats,
             .get_mark = _get_mark,
             .has_encap = _has_encap,
             .get_ipcomp = _get_ipcomp,
             .set_ipcomp = _set_ipcomp,
             .get_close_action = _get_close_action,
             .set_close_action = _set_close_action,
             .get_dpd_action = _get_dpd_action,
             .set_dpd_action = _set_dpd_action,
             .alloc_spi = _alloc_spi,
             .alloc_cpi = _alloc_cpi,
             .install = _install,
             .update = _update,
             .add_policies = _add_policies,
             .create_ts_enumerator = _create_ts_enumerator,
             .create_policy_enumerator = _create_policy_enumerator,
             .destroy = _destroy,
         },
         .encap = encap,
         .ipcomp = IPCOMP_NONE,
         .state = CHILD_CREATED,
         .my_ts = array_create(0, 0),
         .other_ts = array_create(0, 0),
         .protocol = PROTO_NONE,
         .mode = MODE_TUNNEL,
         .close_action = config->get_close_action(config),
         .dpd_action = config->get_dpd_action(config),
         .reqid = config->get_reqid(config),
         .unique_id = ref_get(&unique_id),
         .mark_in = config->get_mark(config, TRUE),
         .mark_out = config->get_mark(config, FALSE),
         .install_time = time_monotonic(NULL),
     );
     this->config = config;
     config->get_ref(config);
     if (mark_in)
     {
         this->mark_in.value = mark_in;
     }
     if (mark_out)
     {
         this->mark_out.value = mark_out;
     }
     if (this->mark_in.value == MARK_UNIQUE ||
         this->mark_out.value == MARK_UNIQUE)
     {
         mark = ref_get(&unique_mark);
         if (this->mark_in.value == MARK_UNIQUE)
         {
             this->mark_in.value = mark;
         }
         if (this->mark_out.value == MARK_UNIQUE)
         {
             this->mark_out.value = mark;
         }
     }
     if (!this->reqid)
     {
         /* reuse old reqid if we are rekeying an existing CHILD_SA. While the
          * reqid cache would find the same reqid for our selectors, this does
          * not work in a special case: If an SA is triggered by a trap policy,
          * but the negotiated SA gets narrowed, we still must reuse the same
          * reqid to successfully "trigger" the SA on the kernel level. Rekeying
          * such an SA requires an explicit reqid, as the cache currently knows
          * the original selectors only for that reqid. */
         if (rekey)
         {
             this->reqid = rekey;
         }
         else
         {
             this->reqid = charon->traps->find_reqid(charon->traps, config);
         }
     }
     else
     {
         this->static_reqid = TRUE;
     }
     /* MIPv6 proxy transport mode sets SA endpoints to TS hosts */
     if (config->get_mode(config) == MODE_TRANSPORT &&
         config->use_proxy_mode(config))
     {
         this->mode = MODE_TRANSPORT;
         this->my_addr = get_proxy_addr(config, me, TRUE);
         this->other_addr = get_proxy_addr(config, other, FALSE);
     }
     else
     {
         this->my_addr = me->clone(me);
         this->other_addr = other->clone(other);
     }
     return &this->public;
 }
Variable Documentation
enum_name_t* child_sa_state_names
enum strings for child_sa_state_t.
Referenced by get_retry_delay(), list_child(), and log_child_sa().