strongSwan: load_tester_config
load_tester_config
load_tester
Classes
struct load_tester_config_t
Typedefs
typedef struct load_tester_config_t load_tester_config_t
Functions
load_tester_config_t * load_tester_config_create ()
Detailed Description
Typedef Documentation
typedef struct load_tester_config_t load_tester_config_t
Definition at line 26 of file load_tester_config.h.
Function Documentation
load_tester_config_t* load_tester_config_create ()
Create a configuration backend for load testing.
Returns
configuration backend
Described in header.
Definition at line 919 of file load_tester_config.c.
References equals(), FALSE, generate_config(), settings_t::get_bool, settings_t::get_int, settings_t::get_str, hash(), hashtable_create(), host_create_from_string(), IKE_ANY, ike_rekey(), INIT, initiator, lib, linked_list_create(), load_addrs(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, port, proposal, proposal_create_from_string(), PROTO_ESP, PROTO_IKE, library_t::settings, UNIQUE_PORT_START, version, and vip.
Referenced by register_load_tester().
 {
     private_load_tester_config_t *this;
     INIT(this,
         .public = {
             .backend = {
                 .create_peer_cfg_enumerator = _create_peer_cfg_enumerator,
                 .create_ike_cfg_enumerator = _create_ike_cfg_enumerator,
                 .get_peer_cfg_by_name = _get_peer_cfg_by_name,
             },
             .delete_ip = _delete_ip,
             .destroy = _destroy,
         },
         .pools = linked_list_create(),
         .leases = hashtable_create((hashtable_hash_t)hash,
                                    (hashtable_equals_t)equals, 256),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .num = 1,
         .unique_port = UNIQUE_PORT_START,
     );
     if (lib->settings->get_bool(lib->settings,
                 "%s.plugins.load-tester.request_virtual_ip", FALSE, lib->ns))
     {
         this->vip = host_create_from_string("0.0.0.0", 0);
     }
     this->pool = lib->settings->get_str(lib->settings,
                     "%s.plugins.load-tester.pool", NULL, lib->ns);
     this->initiator = lib->settings->get_str(lib->settings,
                     "%s.plugins.load-tester.initiator", "0.0.0.0", lib->ns);
     this->responder = lib->settings->get_str(lib->settings,
                     "%s.plugins.load-tester.responder", "127.0.0.1", lib->ns);
     this->proposal = proposal_create_from_string(PROTO_IKE,
                 lib->settings->get_str(lib->settings,
                     "%s.plugins.load-tester.proposal", "aes128-sha1-modp768",
                     lib->ns));
     if (!this->proposal)
     {   /* fallback */
         this->proposal = proposal_create_from_string(PROTO_IKE,
                                                      "aes128-sha1-modp768");
     }
     this->esp = proposal_create_from_string(PROTO_ESP,
                 lib->settings->get_str(lib->settings,
                     "%s.plugins.load-tester.esp", "aes128-sha1", lib->ns));
     if (!this->esp)
     {   /* fallback */
         this->esp = proposal_create_from_string(PROTO_ESP, "aes128-sha1");
     }
     this->ike_rekey = lib->settings->get_int(lib->settings,
                 "%s.plugins.load-tester.ike_rekey", 0, lib->ns);
     this->child_rekey = lib->settings->get_int(lib->settings,
                 "%s.plugins.load-tester.child_rekey", 600, lib->ns);
     this->dpd_delay = lib->settings->get_int(lib->settings,
                 "%s.plugins.load-tester.dpd_delay", 0, lib->ns);
     this->dpd_timeout = lib->settings->get_int(lib->settings,
                 "%s.plugins.load-tester.dpd_timeout", 0, lib->ns);
     this->initiator_auth = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.initiator_auth", "pubkey", lib->ns);
     this->responder_auth = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.responder_auth", "pubkey", lib->ns);
     this->initiator_id = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.initiator_id", NULL, lib->ns);
     this->initiator_match = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.initiator_match", NULL, lib->ns);
     this->responder_id = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.responder_id", NULL, lib->ns);
     this->mode = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.mode", NULL, lib->ns);
     this->initiator_tsi = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.initiator_tsi", NULL, lib->ns);
     this->responder_tsi =lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.responder_tsi",
                 this->initiator_tsi, lib->ns);
     this->initiator_tsr = lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.initiator_tsr", NULL, lib->ns);
     this->responder_tsr =lib->settings->get_str(lib->settings,
                 "%s.plugins.load-tester.responder_tsr",
                 this->initiator_tsr, lib->ns);
     this->port = lib->settings->get_int(lib->settings,
                 "%s.plugins.load-tester.dynamic_port", 0, lib->ns);
     this->version = lib->settings->get_int(lib->settings,
                 "%s.plugins.load-tester.version", IKE_ANY, lib->ns);
     load_addrs(this);
     this->peer_cfg = generate_config(this, 0);
     return &this->public;
 }