strongSwan: child_rekey
child_rekey
tasks
Classes
struct child_rekey_t
Typedefs
typedef struct child_rekey_t child_rekey_t
Functions
child_rekey_t * child_rekey_create (ike_sa_t *ike_sa, protocol_id_t protocol, u_int32_t spi)
Detailed Description
Typedef Documentation
typedef struct child_rekey_t child_rekey_t
Definition at line 24 of file child_rekey.h.
Function Documentation
child_rekey_t* child_rekey_create (ike_sa_t * ike_sa, protocol_id_t protocol, u_int32_t spi)
Create a new TASK_CHILD_REKEY task.
Parameters
ike_sa IKE_SA this task works for
protocol protocol of CHILD_SA to rekey, PROTO_NONE as responder
spi inbound SPI of CHILD_SA to rekey
Returns
child_rekey task to handle by the task_manager
Definition at line 478 of file child_rekey.c.
References child_create_create(), FALSE, INIT, initiator, PROTO_NONE, protocol, and TRUE.
Referenced by METHOD(), and process_request().
 {
     private_child_rekey_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
             .collide = _collide,
         },
         .ike_sa = ike_sa,
         .protocol = protocol,
         .spi = spi,
     );
     if (protocol != PROTO_NONE)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
         this->initiator = TRUE;
         this->child_create = NULL;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
         this->initiator = FALSE;
         this->child_create = child_create_create(ike_sa, NULL, TRUE, NULL, NULL);
     }
     return &this->public;
 }