strongSwan: bridge.h File Reference
bridge.h File Reference
#include <library.h>
#include <collections/enumerator.h>
#include "iface.h"
Classes
struct bridge_t
Typedefs
typedef struct bridge_t bridge_t
Functions
bridge_t * bridge_create (char *name)
Typedef Documentation
typedef struct bridge_t bridge_t
Definition at line 22 of file bridge.h.
Function Documentation
bridge_t* bridge_create (char * name)
Create a new bridge.
Parameters
name name of the bridge to create
Returns
bridge, NULL if failed
create the bridge instance
Definition at line 142 of file bridge.c.
References DBG1, DBG_LIB, free(), iface_control(), INIT, instances, linked_list_create(), strdup, and TRUE.
Referenced by METHOD().
 {
     private_bridge_t *this;
     if (instances == 0)
     {
         if (br_init() != 0)
         {
             DBG1(DBG_LIB, "libbridge initialization failed: %m");
             return NULL;
         }
     }
     INIT(this,
         .public = {
             .get_name = _get_name,
             .create_iface_enumerator = _create_iface_enumerator,
             .disconnect_iface = _disconnect_iface,
             .connect_iface = _connect_iface,
             .destroy = _destroy,
         }
     );
     if (br_add_bridge(name) != 0)
     {
         DBG1(DBG_LIB, "creating bridge '%s' failed: %m", name);
         free(this);
         return NULL;
     }
     if (!iface_control(name, TRUE))
     {
         DBG1(DBG_LIB, "bringing bridge '%s' up failed: %m", name);
     }
     this->name = strdup(name);
     this->ifaces = linked_list_create();
     instances++;
     return &this->public;
 }