strongSwan: certexpire_plugin.c File Reference
certexpire_plugin.c File Reference
#include "certexpire_plugin.h"
#include "certexpire_listener.h"
#include "certexpire_export.h"
#include <daemon.h>
Classes
struct private_certexpire_plugin_t
Typedefs
typedef struct
private_certexpire_plugin_t private_certexpire_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_certexpire_plugin_t *this)
static bool plugin_cb (private_certexpire_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_certexpire_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_certexpire_plugin_t *this)
plugin_t * certexpire_plugin_create ()
Typedef Documentation
typedef struct private_certexpire_plugin_t private_certexpire_plugin_t
Definition at line 23 of file certexpire_plugin.c.
Function Documentation
plugin_t* certexpire_plugin_create ()
Plugin constructor
Definition at line 91 of file certexpire_plugin.c.
References certexpire_export_create(), certexpire_listener_create(), export(), INIT, and listener.
 {
     private_certexpire_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .export = certexpire_export_create(),
     );
     this->listener = certexpire_listener_create(this->export);
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_certexpire_plugin_t * this)
Definition at line 46 of file certexpire_plugin.c.
 {
     return "certexpire";
 }
METHOD (plugin_t , get_features , int , private_certexpire_plugin_t * this, plugin_feature_t * features[])
Definition at line 69 of file certexpire_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "certexpire"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_certexpire_plugin_t * this)
Definition at line 80 of file certexpire_plugin.c.
References tkm_listener_t::destroy, export(), free(), and listener.
 {
     this->listener->destroy(this->listener);
     this->export->destroy(this->export);
     free(this);
 }
static bool plugin_cb (private_certexpire_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 55 of file certexpire_plugin.c.
References bus_t::add_listener, daemon_t::bus, charon, bus_t::remove_listener, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
     }
     return TRUE;
 }