strongSwan: bliss_sampler
bliss_sampler
bliss
Classes
struct bliss_sampler_t
Typedefs
typedef struct bliss_sampler_t bliss_sampler_t
Functions
bliss_sampler_t * bliss_sampler_create (hash_algorithm_t alg, chunk_t seed, bliss_param_set_t *set)
Detailed Description
Typedef Documentation
typedef struct bliss_sampler_t bliss_sampler_t
Definition at line 24 of file bliss_sampler.h.
Function Documentation
bliss_sampler_t* bliss_sampler_create (hash_algorithm_t alg, chunk_t seed, bliss_param_set_t * set)
Create a bliss_sampler_t object.
Parameters
alg Hash algorithm to be used for the internal bitspender
seed Seed used to initialize the internal bitspender
set BLISS parameter set to be used
See header.
Definition at line 224 of file bliss_sampler.c.
References FALSE, INIT, and mgf1_bitspender_create().
Referenced by sign_bliss(), and START_TEST().
 {
     private_bliss_sampler_t *this;
     mgf1_bitspender_t *bitspender;
     bitspender = mgf1_bitspender_create(alg, seed, FALSE);
     if (!bitspender)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .bernoulli_exp = _bernoulli_exp,
             .bernoulli_cosh = _bernoulli_cosh,
             .pos_binary = _pos_binary,
             .gaussian = _gaussian,
             .sign = _sign,
             .destroy = _destroy,
         },
         .set = set,
         .bitspender = bitspender,
     );
     return &this->public;
 }