strongSwan: imv_os_state
imv_os_state
imv_os
Classes
struct imv_os_state_t
Typedefs
typedef struct imv_os_state_t imv_os_state_t
typedef enum
imv_os_handshake_state_t imv_os_handshake_state_t
typedef enum os_settings_t os_settings_t
Enumerations
enum imv_os_handshake_state_t {
IMV_OS_STATE_INIT, IMV_OS_STATE_ATTR_REQ, IMV_OS_STATE_POLICY_START, IMV_OS_STATE_WORKITEMS,
IMV_OS_STATE_END
}
enum os_settings_t { OS_SETTINGS_FWD_ENABLED = (1<<0), OS_SETTINGS_DEFAULT_PWD_ENABLED = (1<<1), OS_SETTINGS_UNKNOWN_SOURCE = (1<<2) }
Functions
imv_state_t * imv_os_state_create (TNC_ConnectionID id)
Detailed Description
Typedef Documentation
typedef enum imv_os_handshake_state_t imv_os_handshake_state_t
Definition at line 32 of file imv_os_state.h.
typedef struct imv_os_state_t imv_os_state_t
Definition at line 31 of file imv_os_state.h.
typedef enum os_settings_t os_settings_t
Definition at line 33 of file imv_os_state.h.
Enumeration Type Documentation
enum imv_os_handshake_state_t
IMV OS Handshake States (state machine)
Enumerator
IMV_OS_STATE_INIT
IMV_OS_STATE_ATTR_REQ
IMV_OS_STATE_POLICY_START
IMV_OS_STATE_WORKITEMS
IMV_OS_STATE_END
Definition at line 38 of file imv_os_state.h.
{
     IMV_OS_STATE_INIT,
     IMV_OS_STATE_ATTR_REQ,
     IMV_OS_STATE_POLICY_START,
     IMV_OS_STATE_WORKITEMS,
     IMV_OS_STATE_END
 };
enum os_settings_t
Flags for detected OS Settings
Enumerator
OS_SETTINGS_FWD_ENABLED
OS_SETTINGS_DEFAULT_PWD_ENABLED
OS_SETTINGS_UNKNOWN_SOURCE
Definition at line 49 of file imv_os_state.h.
                    {
     OS_SETTINGS_FWD_ENABLED =         (1<<0),
     OS_SETTINGS_DEFAULT_PWD_ENABLED = (1<<1),
     OS_SETTINGS_UNKNOWN_SOURCE =      (1<<2)
 };
Function Documentation
imv_state_t* imv_os_state_create (TNC_ConnectionID connection_id)
Create an imv_os_state_t instance
Parameters
id connection ID
Described in header.
Definition at line 569 of file imv_os_state.c.
References INIT, linked_list_create(), seg_contract_manager_create(), TNC_CONNECTION_STATE_CREATE, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TNC_IMV_EVALUATION_RESULT_DONT_KNOW.
Referenced by METHOD().
 {
     private_imv_os_state_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_connection_id = _get_connection_id,
                 .has_long = _has_long,
                 .has_excl = _has_excl,
                 .set_flags = _set_flags,
                 .set_max_msg_len = _set_max_msg_len,
                 .get_max_msg_len = _get_max_msg_len,
                 .set_action_flags = _set_action_flags,
                 .get_action_flags = _get_action_flags,
                 .set_session = _set_session,
                 .get_session = _get_session,
                 .get_contracts = _get_contracts,
                 .change_state = _change_state,
                 .get_recommendation = _get_recommendation,
                 .set_recommendation = _set_recommendation,
                 .update_recommendation = _update_recommendation,
                 .get_reason_string = _get_reason_string,
                 .get_remediation_instructions = _get_remediation_instructions,
                 .destroy = _destroy,
             },
             .set_handshake_state = _set_handshake_state,
             .get_handshake_state = _get_handshake_state,
             .set_count = _set_count,
             .get_count = _get_count,
             .set_os_settings = _set_os_settings,
             .get_os_settings = _get_os_settings,
             .set_missing = _set_missing,
             .get_missing = _get_missing,
             .add_bad_package = _add_bad_package,
         },
         .state = TNC_CONNECTION_STATE_CREATE,
         .rec = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION,
         .eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW,
         .connection_id = connection_id,
         .contracts = seg_contract_manager_create(),
         .update_packages = linked_list_create(),
         .remove_packages = linked_list_create(),
     );
     return &this->public.interface;
 }