strongSwan: unity_handler.c File Reference
unity_handler.c File Reference
#include "unity_handler.h"
#include <daemon.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_unity_handler_t
struct entry_t
struct attribute_enumerator_t
struct include_filter_t
Typedefs
typedef struct
private_unity_handler_t private_unity_handler_t
Functions
static void entry_destroy (entry_t *this)
static traffic_selector_t * create_ts (chunk_t subnet)
static linked_list_t * parse_subnets (chunk_t data)
static bool add_include (private_unity_handler_t *this, chunk_t data)
static bool remove_include (private_unity_handler_t *this, chunk_t data)
static void create_shunt_name (ike_sa_t *ike_sa, traffic_selector_t *ts, char *buf, size_t len)
static job_requeue_t add_exclude_async (entry_t *entry)
static bool add_exclude (private_unity_handler_t *this, chunk_t data)
static bool remove_exclude (private_unity_handler_t *this, chunk_t data)
METHOD (attribute_handler_t, handle, bool, private_unity_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (attribute_handler_t, release, void, private_unity_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (enumerator_t, enumerate_attributes, bool, attribute_enumerator_t *this, configuration_attribute_type_t *type, chunk_t *data)
METHOD (attribute_handler_t, create_attribute_enumerator, enumerator_t *, unity_handler_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
static bool include_filter (include_filter_t *data, entry_t **entry, traffic_selector_t **ts)
static void destroy_filter (include_filter_t *data)
METHOD (unity_handler_t, create_include_enumerator, enumerator_t *, private_unity_handler_t *this, ike_sa_id_t *id)
METHOD (unity_handler_t, destroy, void, private_unity_handler_t *this)
unity_handler_t * unity_handler_create ()
Variables
static
configuration_attribute_type_t attributes []
Typedef Documentation
typedef struct private_unity_handler_t private_unity_handler_t
Definition at line 26 of file unity_handler.c.
Function Documentation
static bool add_exclude (private_unity_handler_t * this, chunk_t data) static
Add a bypass policy for a given subnet
Definition at line 250 of file unity_handler.c.
References add_exclude_async(), daemon_t::bus, callback_job_create(), charon, identification_t::clone, linked_list_t::destroy, entry_destroy(), FALSE, ike_sa_t::get_id, bus_t::get_sa, entry_t::id, INIT, lib, list, parse_subnets(), library_t::processor, processor_t::queue_job, linked_list_t::remove_first, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     linked_list_t *list;
     ike_sa_t *ike_sa;
     entry_t *entry;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (!ike_sa)
     {
         return FALSE;
     }
     list = parse_subnets(data);
     if (!list)
     {
         return FALSE;
     }
     while (list->remove_first(list, (void**)&ts) == SUCCESS)
     {
         INIT(entry,
             .id = ike_sa->get_id(ike_sa),
             .ts = ts,
         );
         entry->id = entry->id->clone(entry->id);
         /* we can't install the shunt policy yet, as we don't know the virtual IP.
          * Defer installation using an async callback. */
         lib->processor->queue_job(lib->processor, (job_t*)
                             callback_job_create((void*)add_exclude_async, entry,
                                                 (void*)entry_destroy, NULL));
     }
     list->destroy(list);
     return TRUE;
 }
static job_requeue_t add_exclude_async (entry_t * entry) static
Install entry as a shunt policy
Definition at line 205 of file unity_handler.c.
References ACTION_NONE, child_cfg_t::add_traffic_selector, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkout, child_cfg_create(), host_t::clone, traffic_selector_t::clone, configuration_attribute_type_names, create_shunt_name(), ike_sa_t::create_virtual_ip_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, child_cfg_t::destroy, enumerator_t::enumerate, FALSE, ike_sa_t::get_my_host, host, entry_t::id, daemon_t::ike_sa_manager, shunt_manager_t::install, JOB_REQUEUE_NONE, lifetime_cfg_t::life, MODE_PASS, name, daemon_t::shunts, lifetime_cfg_t::time, traffic_selector_create_from_subnet(), TRUE, entry_t::ts, and UNITY_LOCAL_LAN.
Referenced by add_exclude().
 {
     enumerator_t *enumerator;
     child_cfg_t *child_cfg;
     lifetime_cfg_t lft = { .time = { .life = 0 } };
     ike_sa_t *ike_sa;
     char name[128];
     host_t *host;
     ike_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager, entry->id);
     if (ike_sa)
     {
         create_shunt_name(ike_sa, entry->ts, name, sizeof(name));
         child_cfg = child_cfg_create(name, &lft, NULL, TRUE, MODE_PASS,
                                      ACTION_NONE, ACTION_NONE, ACTION_NONE,
                                      FALSE, 0, 0, NULL, NULL, FALSE);
         child_cfg->add_traffic_selector(child_cfg, FALSE,
                                         entry->ts->clone(entry->ts));
         host = ike_sa->get_my_host(ike_sa);
         child_cfg->add_traffic_selector(child_cfg, TRUE,
                 traffic_selector_create_from_subnet(host->clone(host),
                                                     32, 0, 0, 65535));
         enumerator = ike_sa->create_virtual_ip_enumerator(ike_sa, TRUE);
         while (enumerator->enumerate(enumerator, &host))
         {
             child_cfg->add_traffic_selector(child_cfg, TRUE,
                 traffic_selector_create_from_subnet(host->clone(host),
                                                     32, 0, 0, 65535));
         }
         enumerator->destroy(enumerator);
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
         charon->shunts->install(charon->shunts, child_cfg);
         child_cfg->destroy(child_cfg);
         DBG1(DBG_IKE, "installed %N bypass policy for %R",
              configuration_attribute_type_names, UNITY_LOCAL_LAN, entry->ts);
     }
     return JOB_REQUEUE_NONE;
 }
static bool add_include (private_unity_handler_t * this, chunk_t data) static
Store a list of subnets to include in tunnels under this IKE_SA
Definition at line 115 of file unity_handler.c.
References daemon_t::bus, charon, identification_t::clone, linked_list_t::destroy, FALSE, ike_sa_t::get_id, bus_t::get_sa, entry_t::id, INIT, list, mutex_t::lock, mutex, parse_subnets(), linked_list_t::remove_first, SUCCESS, TRUE, and mutex_t::unlock.
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     linked_list_t *list;
     ike_sa_t *ike_sa;
     entry_t *entry;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (!ike_sa)
     {
         return FALSE;
     }
     list = parse_subnets(data);
     if (!list)
     {
         return FALSE;
     }
     while (list->remove_first(list, (void**)&ts) == SUCCESS)
     {
         INIT(entry,
             .id = ike_sa->get_id(ike_sa),
             .ts = ts,
         );
         entry->id = entry->id->clone(entry->id);
         this->mutex->lock(this->mutex);
         this->include->insert_last(this->include, entry);
         this->mutex->unlock(this->mutex);
     }
     list->destroy(list);
     return TRUE;
 }
static void create_shunt_name (ike_sa_t * ike_sa, traffic_selector_t * ts, char * buf, size_t len) static
Create a unique shunt name for a bypass policy
Definition at line 195 of file unity_handler.c.
References ike_sa_t::get_name, ike_sa_t::get_unique_id, and snprintf.
Referenced by add_exclude_async(), and remove_exclude().
 {
     snprintf(buf, len, "Unity (%s[%u]: %R)", ike_sa->get_name(ike_sa),
              ike_sa->get_unique_id(ike_sa), ts);
 }
static traffic_selector_t* create_ts (chunk_t subnet) static
Create a traffic selector from a unity subnet definition
Definition at line 72 of file unity_handler.c.
References chunk_clonea, chunk_create(), chunk_t::len, mask, net, chunk_t::ptr, traffic_selector_create_from_bytes(), and TS_IPV4_ADDR_RANGE.
Referenced by parse_subnets().
 {
     chunk_t net, mask;
     int i;
     net = chunk_create(subnet.ptr, 4);
     mask = chunk_clonea(chunk_create(subnet.ptr + 4, 4));
     for (i = 0; i < net.len; i++)
     {
         mask.ptr[i] = (mask.ptr[i] ^ 0xFF) | net.ptr[i];
     }
     return traffic_selector_create_from_bytes(0, TS_IPV4_ADDR_RANGE,
                                               net, 0, mask, 65535);
 }
static void destroy_filter (include_filter_t * data) static
Destroy include filter data, unlock mutex
Definition at line 426 of file unity_handler.c.
References free(), include_filter_t::mutex, and mutex_t::unlock.
Referenced by METHOD().
 {
     data->mutex->unlock(data->mutex);
     free(data);
 }
static void entry_destroy (entry_t * this) static
Clean up an entry
Definition at line 62 of file unity_handler.c.
References free().
Referenced by add_exclude(), and remove_include().
 {
     this->id->destroy(this->id);
     this->ts->destroy(this->ts);
     free(this);
 }
static bool include_filter (include_filter_t * data, entry_t ** entry, traffic_selector_t ** ts) static
Include enumerator filter function
Definition at line 412 of file unity_handler.c.
References ike_sa_id_t::equals, FALSE, include_filter_t::id, and TRUE.
Referenced by METHOD().
 {
     if (data->id->equals(data->id, (*entry)->id))
     {
         *ts = (*entry)->ts;
         return TRUE;
     }
     return FALSE;
 }
METHOD (attribute_handler_t , handle , bool , private_unity_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 319 of file unity_handler.c.
References add_exclude(), add_include(), FALSE, UNITY_LOCAL_LAN, and UNITY_SPLIT_INCLUDE.
 {
     switch (type)
     {
         case UNITY_SPLIT_INCLUDE:
             return add_include(this, data);
         case UNITY_LOCAL_LAN:
             return add_exclude(this, data);
         default:
             return FALSE;
     }
 }
METHOD (attribute_handler_t , release , void , private_unity_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 334 of file unity_handler.c.
References remove_exclude(), remove_include(), UNITY_LOCAL_LAN, and UNITY_SPLIT_INCLUDE.
 {
     switch (type)
     {
         case UNITY_SPLIT_INCLUDE:
             remove_include(this, data);
             break;
         case UNITY_LOCAL_LAN:
             remove_exclude(this, data);
             break;
         default:
             break;
     }
 }
METHOD (enumerator_t , enumerate_attributes , bool , attribute_enumerator_t * this, configuration_attribute_type_t * type, chunk_t * data)
Definition at line 369 of file unity_handler.c.
References attributes, chunk_empty, countof, FALSE, and TRUE.
 {
     if (this->i < countof(attributes))
     {
         *type = attributes[this->i++];
         *data = chunk_empty;
         return TRUE;
     }
     return FALSE;
 }
METHOD (attribute_handler_t , create_attribute_enumerator , enumerator_t * , unity_handler_t * this, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 382 of file unity_handler.c.
References daemon_t::bus, charon, destroy(), enumerator_create_empty(), EXT_CISCO_UNITY, free(), bus_t::get_sa, ike_sa_t::get_version, IKEV1, INIT, attribute_enumerator_t::public, and ike_sa_t::supports_extension.
 {
     attribute_enumerator_t *enumerator;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (!ike_sa || ike_sa->get_version(ike_sa) != IKEV1 ||
         !ike_sa->supports_extension(ike_sa, EXT_CISCO_UNITY))
     {
         return enumerator_create_empty();
     }
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_enumerate_attributes,
             .destroy = (void*)free,
         },
     );
     return &enumerator->public;
 }
METHOD (unity_handler_t , create_include_enumerator , enumerator_t * , private_unity_handler_t * this, ike_sa_id_t * id)
Definition at line 432 of file unity_handler.c.
References data, destroy_filter(), enumerator_create_filter(), include_filter(), INIT, mutex_t::lock, mutex, and include_filter_t::mutex.
 {
     include_filter_t *data;
     INIT(data,
         .mutex = this->mutex,
         .id = id,
     );
     data->mutex->lock(data->mutex);
     return enumerator_create_filter(
                     this->include->create_enumerator(this->include),
                     (void*)include_filter, data, (void*)destroy_filter);
 }
METHOD (unity_handler_t , destroy , void , private_unity_handler_t * this)
Definition at line 447 of file unity_handler.c.
References mutex_t::destroy, free(), and mutex.
 {
     this->include->destroy(this->include);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static linked_list_t* parse_subnets (chunk_t data) static
Parse a unity attribute and extract all subnets as traffic selectors
Definition at line 90 of file unity_handler.c.
References chunk_skip(), create_ts(), linked_list_t::insert_last, chunk_t::len, linked_list_create(), and list.
Referenced by add_exclude(), add_include(), remove_exclude(), and remove_include().
 {
     linked_list_t *list = NULL;
     traffic_selector_t *ts;
     while (data.len >= 8)
     {   /* the padding is optional */
         ts = create_ts(data);
         if (ts)
         {
             if (!list)
             {
                 list = linked_list_create();
             }
             list->insert_last(list, ts);
         }
         /* skip address, mask and 6 bytes of padding */
         data = chunk_skip(data, 14);
     }
     return list;
 }
static bool remove_exclude (private_unity_handler_t * this, chunk_t data) static
Remove a bypass policy for a given subnet
Definition at line 289 of file unity_handler.c.
References daemon_t::bus, charon, configuration_attribute_type_names, create_shunt_name(), DBG1, DBG_IKE, linked_list_t::destroy, traffic_selector_t::destroy, FALSE, bus_t::get_sa, list, name, parse_subnets(), linked_list_t::remove_first, daemon_t::shunts, SUCCESS, TRUE, shunt_manager_t::uninstall, and UNITY_LOCAL_LAN.
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     linked_list_t *list;
     ike_sa_t *ike_sa;
     char name[128];
     bool success = TRUE;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (!ike_sa)
     {
         return FALSE;
     }
     list = parse_subnets(data);
     if (!list)
     {
         return FALSE;
     }
     while (list->remove_first(list, (void**)&ts) == SUCCESS)
     {
         create_shunt_name(ike_sa, ts, name, sizeof(name));
         DBG1(DBG_IKE, "uninstalling %N bypass policy for %R",
              configuration_attribute_type_names, UNITY_LOCAL_LAN, ts);
         ts->destroy(ts);
         success = charon->shunts->uninstall(charon->shunts, name) && success;
     }
     list->destroy(list);
     return success;
 }
static bool remove_include (private_unity_handler_t * this, chunk_t data) static
Remove a list of subnets from the inclusion list for this IKE_SA
Definition at line 151 of file unity_handler.c.
References daemon_t::bus, charon, enumerator_t::destroy, linked_list_t::destroy, traffic_selector_t::destroy, entry_destroy(), enumerator_t::enumerate, traffic_selector_t::equals, identification_t::equals, FALSE, ike_sa_t::get_id, bus_t::get_sa, entry_t::id, list, mutex_t::lock, mutex, parse_subnets(), linked_list_t::remove_first, SUCCESS, TRUE, entry_t::ts, and mutex_t::unlock.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     linked_list_t *list;
     ike_sa_t *ike_sa;
     entry_t *entry;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (!ike_sa)
     {
         return FALSE;
     }
     list = parse_subnets(data);
     if (!list)
     {
         return FALSE;
     }
     this->mutex->lock(this->mutex);
     while (list->remove_first(list, (void**)&ts) == SUCCESS)
     {
         enumerator = this->include->create_enumerator(this->include);
         while (enumerator->enumerate(enumerator, &entry))
         {
             if (entry->id->equals(entry->id, ike_sa->get_id(ike_sa)) &&
                 ts->equals(ts, entry->ts))
             {
                 this->include->remove_at(this->include, enumerator);
                 entry_destroy(entry);
                 break;
             }
         }
         enumerator->destroy(enumerator);
         ts->destroy(ts);
     }
     this->mutex->unlock(this->mutex);
     list->destroy(list);
     return TRUE;
 }
Variable Documentation
configuration_attribute_type_t attributes[] static
Initial value:
= {
    UNITY_SPLIT_INCLUDE,
    UNITY_LOCAL_LAN,
}
Configuration attributes to request
Definition at line 354 of file unity_handler.c.
Referenced by METHOD().