strongSwan: pb_pa_msg.c File Reference
pb_pa_msg.c File Reference
#include "pb_pa_msg.h"
#include <tnc/tnccs/tnccs.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_pb_pa_msg_t
Macros
#define PA_FLAG_NONE 0x00
#define PA_FLAG_EXCL (1<<7)
#define PA_RESERVED_SUBTYPE 0xffffffff
Typedefs
typedef struct private_pb_pa_msg_t private_pb_pa_msg_t
Functions
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_pa_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_pa_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_pa_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_pa_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_pa_msg_t *this)
METHOD (pb_pa_msg_t, get_subtype, pen_type_t, private_pb_pa_msg_t *this)
METHOD (pb_pa_msg_t, get_collector_id, u_int16_t, private_pb_pa_msg_t *this)
METHOD (pb_pa_msg_t, get_validator_id, u_int16_t, private_pb_pa_msg_t *this)
METHOD (pb_pa_msg_t, get_body, chunk_t, private_pb_pa_msg_t *this)
METHOD (pb_pa_msg_t, get_exclusive_flag, bool, private_pb_pa_msg_t *this)
pb_tnc_msg_t * pb_pa_msg_create_from_data (chunk_t data)
pb_tnc_msg_t * pb_pa_msg_create (u_int32_t vendor_id, u_int32_t subtype, u_int16_t collector_id, u_int16_t validator_id, bool excl, chunk_t msg_body)
Macro Definition Documentation
#define PA_FLAG_EXCL (1<<7)
Definition at line 46 of file pb_pa_msg.c.
Referenced by METHOD().
#define PA_FLAG_NONE 0x00
PB-PA message
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | PA Message Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PA Subtype | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Posture Collector Identifier | Posture Validator Identifier | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PA Message Body (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 45 of file pb_pa_msg.c.
Referenced by METHOD().
#define PA_RESERVED_SUBTYPE 0xffffffff
Definition at line 47 of file pb_pa_msg.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pb_pa_msg_t private_pb_pa_msg_t
Definition at line 27 of file pb_pa_msg.c.
Function Documentation
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_pa_msg_t * this)
Definition at line 96 of file pb_pa_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_pa_msg_t * this)
Definition at line 102 of file pb_pa_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_pa_msg_t * this)
Definition at line 108 of file pb_pa_msg.c.
References bio_writer_create(), chunk_cat, bio_writer_t::destroy, encoding, bio_writer_t::get_buf, PA_FLAG_EXCL, PA_FLAG_NONE, PB_PA_MSG_HEADER_SIZE, subtype, bio_writer_t::write_uint16, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     chunk_t msg_header;
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     /* build message header */
     writer = bio_writer_create(PB_PA_MSG_HEADER_SIZE);
     writer->write_uint8 (writer, this->excl ? PA_FLAG_EXCL : PA_FLAG_NONE);
     writer->write_uint24(writer, this->subtype.vendor_id);
     writer->write_uint32(writer, this->subtype.type);
     writer->write_uint16(writer, this->collector_id);
     writer->write_uint16(writer, this->validator_id);
     msg_header = writer->get_buf(writer);
     /* create encoding by concatenating message header and message body */
     this->encoding = chunk_cat("cc", msg_header, this->msg_body);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_pa_msg_t * this, u_int32_t * offset)
Definition at line 133 of file pb_pa_msg.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, encoding, FAILED, flags, PA_FLAG_EXCL, PA_FLAG_NONE, PA_RESERVED_SUBTYPE, PEN_RESERVED, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, subtype, and SUCCESS.
 {
     u_int8_t flags;
     size_t msg_body_len;
     bio_reader_t *reader;
     /* process message header */
     reader = bio_reader_create(this->encoding);
     reader->read_uint8 (reader, &flags);
     reader->read_uint24(reader, &this->subtype.vendor_id);
     reader->read_uint32(reader, &this->subtype.type);
     reader->read_uint16(reader, &this->collector_id);
     reader->read_uint16(reader, &this->validator_id);
     this->excl = ((flags & PA_FLAG_EXCL) != PA_FLAG_NONE);
     /* process message body */
     msg_body_len = reader->remaining(reader);
     if (msg_body_len)
     {
         reader->read_data(reader, msg_body_len, &this->msg_body);
         this->msg_body = chunk_clone(this->msg_body);
     }
     reader->destroy(reader);
     if (this->subtype.vendor_id == PEN_RESERVED)
     {
         DBG1(DBG_TNC, "Vendor ID 0x%06x is reserved", PEN_RESERVED);
         *offset = 1;
         return FAILED;
     }
     if (this->subtype.type == PA_RESERVED_SUBTYPE)
     {
         DBG1(DBG_TNC, "PA Subtype 0x%08x is reserved", PA_RESERVED_SUBTYPE);
         *offset = 4;
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_pa_msg_t * this)
Definition at line 175 of file pb_pa_msg.c.
References encoding, and free().
 {
     free(this->encoding.ptr);
     free(this->msg_body.ptr);
     free(this);
 }
METHOD (pb_pa_msg_t , get_subtype , pen_type_t , private_pb_pa_msg_t * this)
Definition at line 183 of file pb_pa_msg.c.
References subtype.
 {
     return this->subtype;
 }
METHOD (pb_pa_msg_t , get_collector_id , u_int16_t , private_pb_pa_msg_t * this)
Definition at line 189 of file pb_pa_msg.c.
 {
     return this->collector_id;
 }
METHOD (pb_pa_msg_t , get_validator_id , u_int16_t , private_pb_pa_msg_t * this)
Definition at line 195 of file pb_pa_msg.c.
 {
     return this->validator_id;
 }
METHOD (pb_pa_msg_t , get_body , chunk_t , private_pb_pa_msg_t * this)
Definition at line 201 of file pb_pa_msg.c.
 {
     return this->msg_body;
 }
METHOD (pb_pa_msg_t , get_exclusive_flag , bool , private_pb_pa_msg_t * this)
Definition at line 207 of file pb_pa_msg.c.
 {
     return this->excl;
 }