strongSwan: openssl_ec_private_key
openssl_ec_private_key
openssl
Classes
struct openssl_ec_private_key_t
Typedefs
typedef struct
openssl_ec_private_key_t openssl_ec_private_key_t
Functions
openssl_ec_private_key_t * openssl_ec_private_key_gen (key_type_t type, va_list args)
openssl_ec_private_key_t * openssl_ec_private_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct openssl_ec_private_key_t openssl_ec_private_key_t
Definition at line 27 of file openssl_ec_private_key.h.
Function Documentation
openssl_ec_private_key_t* openssl_ec_private_key_gen (key_type_t type, va_list args)
Generate a ECDSA private key using OpenSSL.
Accepts the BUILD_KEY_SIZE argument.
Parameters
type type of the key, must be KEY_ECDSA
args builder_part_t argument list
Returns
generated key, NULL on failure
See header.
Definition at line 304 of file openssl_ec_private_key.c.
References BUILD_END, BUILD_KEY_SIZE, create_empty(), DBG1, DBG_LIB, destroy(), key_size, and TRUE.
Referenced by METHOD().
 {
     private_openssl_ec_private_key_t *this;
     u_int key_size = 0;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_KEY_SIZE:
                 key_size = va_arg(args, u_int);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!key_size)
     {
         return NULL;
     }
     this = create_empty();
     switch (key_size)
     {
         case 256:
             this->ec = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
             break;
         case 384:
             this->ec = EC_KEY_new_by_curve_name(NID_secp384r1);
             break;
         case 521:
             this->ec = EC_KEY_new_by_curve_name(NID_secp521r1);
             break;
         default:
             DBG1(DBG_LIB, "EC private key size %d not supported", key_size);
             destroy(this);
             return NULL;
     }
     if (EC_KEY_generate_key(this->ec) != 1)
     {
         DBG1(DBG_LIB, "EC private key generation failed", key_size);
         destroy(this);
         return NULL;
     }
     /* encode as a named curve key (no parameters), uncompressed public key */
     EC_KEY_set_asn1_flag(this->ec, OPENSSL_EC_NAMED_CURVE);
     EC_KEY_set_conv_form(this->ec, POINT_CONVERSION_UNCOMPRESSED);
     return &this->public;
 }
openssl_ec_private_key_t* openssl_ec_private_key_load (key_type_t type, va_list args)
Load a ECDSA private key using OpenSSL.
Accepts a BUILD_BLOB_ASN1_DER argument.
Parameters
type type of the key, must be KEY_ECDSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 360 of file openssl_ec_private_key.c.
References BUILD_BLOB_ALGID_PARAMS, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, create_empty(), destroy(), key, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     private_openssl_ec_private_key_t *this;
     chunk_t par = chunk_empty, key = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ALGID_PARAMS:
                 par = va_arg(args, chunk_t);
                 continue;
             case BUILD_BLOB_ASN1_DER:
                 key = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     this = create_empty();
     if (par.ptr)
     {
         this->ec = d2i_ECParameters(NULL, (const u_char**)&par.ptr, par.len);
         if (!this->ec)
         {
             goto error;
         }
         if (!d2i_ECPrivateKey(&this->ec, (const u_char**)&key.ptr, key.len))
         {
             goto error;
         }
     }
     else
     {
         this->ec = d2i_ECPrivateKey(NULL, (const u_char**)&key.ptr, key.len);
         if (!this->ec)
         {
             goto error;
         }
     }
     if (!EC_KEY_check_key(this->ec))
     {
         goto error;
     }
     return &this->public;
 error:
     destroy(this);
     return NULL;
 }