strongSwan: tcg_pts_attr_req_file_meta.c File Reference
tcg_pts_attr_req_file_meta.c File Reference
#include <string.h>
#include "tcg_pts_attr_req_file_meta.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_req_file_meta_t
Macros
#define _GNU_SOURCE /* for stdndup() */
#define PTS_REQ_FILE_META_SIZE 4
#define PTS_REQ_FILE_META_RESERVED 0x00
#define PTS_REQ_FILE_META_NO_FLAGS 0x00
#define DIRECTORY_CONTENTS_FLAG (1<<7)
Typedefs
typedef struct
private_tcg_pts_attr_req_file_meta_t private_tcg_pts_attr_req_file_meta_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_req_file_meta_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_req_file_meta_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_req_file_meta_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (tcg_pts_attr_req_file_meta_t, get_directory_flag, bool, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (tcg_pts_attr_req_file_meta_t, get_delimiter, u_int8_t, private_tcg_pts_attr_req_file_meta_t *this)
METHOD (tcg_pts_attr_req_file_meta_t, get_pathname, char *, private_tcg_pts_attr_req_file_meta_t *this)
pa_tnc_attr_t * tcg_pts_attr_req_file_meta_create (bool directory_flag, u_int8_t delimiter, char *pathname)
pa_tnc_attr_t * tcg_pts_attr_req_file_meta_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 17 of file tcg_pts_attr_req_file_meta.c.
#define DIRECTORY_CONTENTS_FLAG (1<<7)
Definition at line 46 of file tcg_pts_attr_req_file_meta.c.
Referenced by METHOD().
#define PTS_REQ_FILE_META_NO_FLAGS 0x00
Definition at line 44 of file tcg_pts_attr_req_file_meta.c.
Referenced by METHOD().
#define PTS_REQ_FILE_META_RESERVED 0x00
Definition at line 43 of file tcg_pts_attr_req_file_meta.c.
Referenced by METHOD().
#define PTS_REQ_FILE_META_SIZE 4
Request File Metadata see section 3.17.1 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | Delimiter | Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Fully Qualified File Pathname (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 42 of file tcg_pts_attr_req_file_meta.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_req_file_meta_t private_tcg_pts_attr_req_file_meta_t
Definition at line 27 of file tcg_pts_attr_req_file_meta.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 99 of file tcg_pts_attr_req_file_meta.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 105 of file tcg_pts_attr_req_file_meta.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 111 of file tcg_pts_attr_req_file_meta.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_req_file_meta_t * this, bool noskip)
Definition at line 117 of file tcg_pts_attr_req_file_meta.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 123 of file tcg_pts_attr_req_file_meta.c.
References bio_writer_create(), chunk_create(), bio_writer_t::destroy, DIRECTORY_CONTENTS_FLAG, bio_writer_t::extract_buf, flags, length, PTS_REQ_FILE_META_NO_FLAGS, PTS_REQ_FILE_META_RESERVED, PTS_REQ_FILE_META_SIZE, value, bio_writer_t::write_data, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
 {
     u_int8_t flags = PTS_REQ_FILE_META_NO_FLAGS;
     chunk_t pathname;
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     if (this->directory_flag)
     {
         flags |= DIRECTORY_CONTENTS_FLAG;
     }
     pathname = chunk_create(this->pathname, strlen(this->pathname));
     writer = bio_writer_create(PTS_REQ_FILE_META_SIZE);
     writer->write_uint8 (writer, flags);
     writer->write_uint8 (writer, this->delimiter);
     writer->write_uint16(writer, PTS_REQ_FILE_META_RESERVED);
     writer->write_data  (writer, pathname);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_req_file_meta_t * this, u_int32_t * offset)
Definition at line 151 of file tcg_pts_attr_req_file_meta.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, DIRECTORY_CONTENTS_FLAG, flags, chunk_t::len, NEED_MORE, chunk_t::ptr, PTS_REQ_FILE_META_NO_FLAGS, PTS_REQ_FILE_META_SIZE, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, strndup(), SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int8_t flags;
     u_int16_t reserved;
     chunk_t pathname;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_REQ_FILE_META_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for Request File Metadata");
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &flags);
     reader->read_uint8 (reader, &this->delimiter);
     reader->read_uint16(reader, &reserved);
     reader->read_data  (reader, reader->remaining(reader), &pathname);
     this->directory_flag = (flags & DIRECTORY_CONTENTS_FLAG) !=
                             PTS_REQ_FILE_META_NO_FLAGS;
     this->pathname = strndup(pathname.ptr, pathname.len);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_req_file_meta_t * this, chunk_t segment)
Definition at line 185 of file tcg_pts_attr_req_file_meta.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 191 of file tcg_pts_attr_req_file_meta.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 198 of file tcg_pts_attr_req_file_meta.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->pathname);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_req_file_meta_t , get_directory_flag , bool , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 209 of file tcg_pts_attr_req_file_meta.c.
 {
     return this->directory_flag;
 }
METHOD (tcg_pts_attr_req_file_meta_t , get_delimiter , u_int8_t , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 215 of file tcg_pts_attr_req_file_meta.c.
 {
     return this->delimiter;
 }
METHOD (tcg_pts_attr_req_file_meta_t , get_pathname , char * , private_tcg_pts_attr_req_file_meta_t * this)
Definition at line 221 of file tcg_pts_attr_req_file_meta.c.
 {
     return this->pathname;
 }