strongSwan: kernel_wfp_ipsec
kernel_wfp_ipsec
kernel_wfp
Classes
struct kernel_wfp_ipsec_t
Typedefs
typedef struct kernel_wfp_ipsec_t kernel_wfp_ipsec_t
Functions
kernel_wfp_ipsec_t * kernel_wfp_ipsec_create ()
Detailed Description
Typedef Documentation
typedef struct kernel_wfp_ipsec_t kernel_wfp_ipsec_t
Definition at line 27 of file kernel_wfp_ipsec.h.
Function Documentation
kernel_wfp_ipsec_t* kernel_wfp_ipsec_create ()
Create WFP kernel interface instance.
Returns
kernel_wfp_ipsec_t instance
Definition at line 2628 of file kernel_wfp_ipsec.c.
References array_create(), DBG1, DBG_KNL, destroy(), DWORD, equals_route(), equals_sa(), equals_trap(), handle, hash_route(), hash_sa(), hash_trap(), hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), INIT, init_spi(), mutex_create(), MUTEX_TYPE_RECURSIVE, register_events(), and res.
Referenced by METHOD().
 {
     private_kernel_wfp_ipsec_t *this;
     DWORD res;
     FWPM_SESSION0 session = {
         .displayData = {
             .name = L"charon",
             .description = L"strongSwan IKE kernel-wfp backend",
         },
     };
     INIT(this,
         .public = {
             .interface = {
                 .get_features = _get_features,
                 .get_spi = _get_spi,
                 .get_cpi = _get_cpi,
                 .add_sa  = _add_sa,
                 .update_sa = _update_sa,
                 .query_sa = _query_sa,
                 .del_sa = _del_sa,
                 .flush_sas = _flush_sas,
                 .add_policy = _add_policy,
                 .query_policy = _query_policy,
                 .del_policy = _del_policy,
                 .flush_policies = _flush_policies,
                 .bypass_socket = _bypass_socket,
                 .enable_udp_decap = _enable_udp_decap,
                 .destroy = _destroy,
             },
         },
         .provider = {
             .displayData = {
                 .name = L"charon",
                 .description = L"strongSwan IKE kernel-wfp backend",
             },
             .providerKey = { 0x59cdae2e, 0xf6bb, 0x4c09,
                             { 0xa9,0x59,0x9d,0x91,0xac,0xaf,0xf9,0x19 }},
         },
         .mutex = mutex_create(MUTEX_TYPE_RECURSIVE),
         .bypass = array_create(sizeof(UINT64), 2),
         .tsas = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 4),
         .isas = hashtable_create((void*)hash_sa, (void*)equals_sa, 4),
         .osas = hashtable_create((void*)hash_sa, (void*)equals_sa, 4),
         .routes = hashtable_create((void*)hash_route, (void*)equals_route, 4),
         .traps = hashtable_create((void*)hash_trap, (void*)equals_trap, 4),
     );
     if (!init_spi(this))
     {
         destroy(this);
         return NULL;
     }
     res = FwpmEngineOpen0(NULL, RPC_C_AUTHN_WINNT, NULL, &session,
                           &this->handle);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "opening WFP engine failed: 0x%08x", res);
         destroy(this);
         return NULL;
     }
     res = FwpmProviderAdd0(this->handle, &this->provider, NULL);
     if (res != ERROR_SUCCESS && res != FWP_E_ALREADY_EXISTS)
     {
         DBG1(DBG_KNL, "registering WFP provider failed: 0x%08x", res);
         destroy(this);
         return NULL;
     }
     if (!register_events(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }