strongSwan: pb_mutual_capability_msg.c File Reference
pb_mutual_capability_msg.c File Reference
#include "pb_mutual_capability_msg.h"
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pb_mutual_capability_msg_t
Macros
#define MUTUAL_CAPABILITY_HEADER_SIZE 4
Typedefs
typedef struct
private_pb_mutual_capability_msg_t private_pb_mutual_capability_msg_t
Functions
ENUM (pb_tnc_mutual_protocol_type_names, PB_MUTUAL_HALF_DUPLEX, PB_MUTUAL_FULL_DUPLEX,"half duplex","full duplex")
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_mutual_capability_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_mutual_capability_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_mutual_capability_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_mutual_capability_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_mutual_capability_msg_t *this)
METHOD (pb_mutual_capability_msg_t, get_protocols, uint32_t, private_pb_mutual_capability_msg_t *this)
pb_tnc_msg_t * pb_mutual_capability_msg_create (uint32_t protocols)
pb_tnc_msg_t * pb_mutual_capability_msg_create_from_data (chunk_t data)
Macro Definition Documentation
#define MUTUAL_CAPABILITY_HEADER_SIZE 4
PB-Mutual-Capability message
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ |H|F| Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 40 of file pb_mutual_capability_msg.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pb_mutual_capability_msg_t private_pb_mutual_capability_msg_t
Definition at line 28 of file pb_mutual_capability_msg.c.
Function Documentation
ENUM (pb_tnc_mutual_protocol_type_names , PB_MUTUAL_HALF_DUPLEX , PB_MUTUAL_FULL_DUPLEX , "half duplex" , "full duplex")
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_mutual_capability_msg_t * this)
Definition at line 68 of file pb_mutual_capability_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_mutual_capability_msg_t * this)
Definition at line 74 of file pb_mutual_capability_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_mutual_capability_msg_t * this)
Definition at line 80 of file pb_mutual_capability_msg.c.
References bio_writer_create(), chunk_clone, bio_writer_t::destroy, encoding, bio_writer_t::get_buf, MUTUAL_CAPABILITY_HEADER_SIZE, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     writer = bio_writer_create(MUTUAL_CAPABILITY_HEADER_SIZE);
     writer->write_uint32(writer, this->protocols);
     this->encoding = writer->get_buf(writer);
     this->encoding = chunk_clone(this->encoding);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_mutual_capability_msg_t * this, u_int32_t * offset)
Definition at line 97 of file pb_mutual_capability_msg.c.
References bio_reader_create(), bio_reader_t::destroy, encoding, bio_reader_t::read_uint32, and SUCCESS.
 {
     bio_reader_t *reader;
     *offset = 0;
     /* process message */
     reader = bio_reader_create(this->encoding);
     reader->read_uint32(reader, &this->protocols);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_mutual_capability_msg_t * this)
Definition at line 112 of file pb_mutual_capability_msg.c.
References encoding, and free().
 {
     free(this->encoding.ptr);
     free(this);
 }
METHOD (pb_mutual_capability_msg_t , get_protocols , uint32_t , private_pb_mutual_capability_msg_t * this)
Definition at line 119 of file pb_mutual_capability_msg.c.
 {
     return this->protocols;
 }