strongSwan: tnc_imv_manager
tnc_imv_manager
tnc_imv
Functions
imv_manager_t * tnc_imv_manager_create ()
recommendations_t * tnc_imv_recommendations_create ()
Detailed Description
Function Documentation
imv_manager_t* tnc_imv_manager_create (void)
Create an IMV manager instance.
Described in header.
Definition at line 432 of file tnc_imv_manager.c.
References DBG1, DBG_TNC, enum_from_name, settings_t::get_str, INIT, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, RECOMMENDATION_POLICY_DEFAULT, recommendation_policy_names, rwlock_create(), RWLOCK_TYPE_DEFAULT, and library_t::settings.
Referenced by METHOD().
 {
     private_tnc_imv_manager_t *this;
     char *polname;
     INIT(this,
         .public = {
             .add = _add,
             .remove = _remove_, /* avoid name conflict with stdio.h */
             .load = _load,
             .load_from_functions = _load_from_functions,
             .is_registered = _is_registered,
             .reserve_id = _reserve_id,
             .get_recommendation_policy = _get_recommendation_policy,
             .create_recommendations = _create_recommendations,
             .notify_connection_change = _notify_connection_change,
             .set_message_types = _set_message_types,
             .set_message_types_long = _set_message_types_long,
             .solicit_recommendation = _solicit_recommendation,
             .receive_message = _receive_message,
             .batch_ending = _batch_ending,
             .destroy = _destroy,
         },
         .imvs = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .id_mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .next_imv_id = 1,
     );
     polname = lib->settings->get_str(lib->settings,
                 "%s.plugins.tnc-imv.recommendation_policy", "default", lib->ns);
     if (!enum_from_name(recommendation_policy_names, polname, &this->policy))
     {
         this->policy = RECOMMENDATION_POLICY_DEFAULT;
     }
     DBG1(DBG_TNC, "TNC recommendation policy is '%N'",
                    recommendation_policy_names, this->policy);
     return &this->public;
 }
recommendations_t* tnc_imv_recommendations_create ()
Create an IMV empty recommendations instance