strongSwan: pts_component_manager_t Struct Reference
pts_component_manager_t Struct Reference
pts_component_manager
#include "pts_component_manager.h"
Public Attributes
void(* add_vendor)(pts_component_manager_t *this, pen_t vendor_id, enum_name_t *comp_func_names, int qualifier_type_size, char *qualifier_flag_names, enum_name_t *qualifier_type_names)
void(* add_component)(pts_component_manager_t *this, pen_t vendor_id, u_int32_t name, pts_component_create_t create)
void(* remove_vendor)(pts_component_manager_t *this, pen_t vendor_id)
enum_name_t *(* get_comp_func_names)(pts_component_manager_t *this, pen_t vendor_id)
enum_name_t *(* get_qualifier_type_names)(pts_component_manager_t *this, pen_t vendor_id)
u_int8_t(* get_qualifier)(pts_component_manager_t *this, pts_comp_func_name_t *name, char *flags)
pts_component_t *(* create)(pts_component_manager_t *this, pts_comp_func_name_t *name, u_int32_t depth, pts_database_t *pts_db)
void(* destroy)(pts_component_manager_t *this)
Detailed Description
Manages PTS Functional Components
Definition at line 39 of file pts_component_manager.h.
Member Data Documentation
void(* pts_component_manager_t::add_component)(pts_component_manager_t *this, pen_t vendor_id, u_int32_t name, pts_component_create_t create)
Add vendor-specific functional component
Parameters
vendor_id Private Enterprise Number (PEN)
names Component Functional Name
create Functional Component creation method
Definition at line 63 of file pts_component_manager.h.
Referenced by libimcv_init().
void(* pts_component_manager_t::add_vendor)(pts_component_manager_t *this, pen_t vendor_id, enum_name_t *comp_func_names, int qualifier_type_size, char *qualifier_flag_names, enum_name_t *qualifier_type_names)
Add vendor-specific functional component names
Parameters
vendor_id Private Enterprise Number (PEN)
comp_func_names Vendor-specific Component Functional names
qualifier_type_size Vendor-specific Qualifier Type size
qualifier_flag_names Vendor-specific Qualifier Flag names
qualifier_type_names Vendor-specific Qualifier Type names
Definition at line 50 of file pts_component_manager.h.
Referenced by libimcv_init().
pts_component_t*(* pts_component_manager_t::create)(pts_component_manager_t *this, pts_comp_func_name_t *name, u_int32_t depth, pts_database_t *pts_db)
Create a PTS Component object from a Functional Component Name object
Parameters
name Component Functional Name
depth Sub-component Depth
pts_db PTS measurement database
Returns
Component object if supported, NULL else
Definition at line 109 of file pts_component_manager.h.
Referenced by METHOD().
void(* pts_component_manager_t::destroy)(pts_component_manager_t *this)
Destroys a pts_component_manager_t object.
Definition at line 116 of file pts_component_manager.h.
Referenced by libimcv_deinit().
enum_name_t*(* pts_component_manager_t::get_comp_func_names)(pts_component_manager_t *this, pen_t vendor_id)
Return the Functional Component names for a given vendor ID
Parameters
vendor_id Private Enterprise Number (PEN)
Returns
Comp. Func. names if found, NULL else
Definition at line 79 of file pts_component_manager.h.
Referenced by METHOD(), and print_cfn().
u_int8_t(* pts_component_manager_t::get_qualifier)(pts_component_manager_t *this, pts_comp_func_name_t *name, char *flags)
Return the Qualifier Type and Flags
Parameters
name Component Functional Name
flags Qualifier Flags as a string in a char buffer
Returns
Qualifier Type
Definition at line 98 of file pts_component_manager.h.
Referenced by METHOD(), and print_cfn().
enum_name_t*(* pts_component_manager_t::get_qualifier_type_names)(pts_component_manager_t *this, pen_t vendor_id)
Return the Functional Component Qualifier Type names for a given vendor ID
Parameters
vendor_id Private Enterprise Number (PEN)
Returns
Qualifier Type names if found, NULL else
Definition at line 88 of file pts_component_manager.h.
Referenced by METHOD(), and print_cfn().
void(* pts_component_manager_t::remove_vendor)(pts_component_manager_t *this, pen_t vendor_id)
Remove vendor-specific components and associated namespace
Parameters
vendor_id Private Enterprise Number (PEN)
Definition at line 71 of file pts_component_manager.h.
Referenced by libimcv_deinit().
The documentation for this struct was generated from the following file:
pts_component_manager.h