strongSwan: pkcs11_private_key
pkcs11_private_key
pkcs11
Classes
struct pkcs11_private_key_t
Typedefs
typedef struct pkcs11_private_key_t pkcs11_private_key_t
Functions
pkcs11_private_key_t * pkcs11_private_key_connect (key_type_t type, va_list args)
CK_MECHANISM_PTR pkcs11_signature_scheme_to_mech (signature_scheme_t scheme, key_type_t type, size_t keylen, hash_algorithm_t *hash)
CK_MECHANISM_PTR pkcs11_encryption_scheme_to_mech (encryption_scheme_t scheme)
Detailed Description
Typedef Documentation
typedef struct pkcs11_private_key_t pkcs11_private_key_t
Definition at line 27 of file pkcs11_private_key.h.
Function Documentation
CK_MECHANISM_PTR pkcs11_encryption_scheme_to_mech (encryption_scheme_t scheme)
Get the Cryptoki mechanism for a encryption scheme.
See header.
Definition at line 166 of file pkcs11_private_key.c.
References CKM_RSA_PKCS, CKM_RSA_PKCS_OAEP, countof, ENCRYPT_RSA_OAEP_SHA1, ENCRYPT_RSA_PKCS1, and scheme.
Referenced by METHOD().
 {
     static struct {
         encryption_scheme_t scheme;
         CK_MECHANISM mechanism;
     } mappings[] = {
         {ENCRYPT_RSA_PKCS1,         {CKM_RSA_PKCS,              NULL, 0}},
         {ENCRYPT_RSA_OAEP_SHA1,     {CKM_RSA_PKCS_OAEP,         NULL, 0}},
     };
     int i;
     for (i = 0; i < countof(mappings); i++)
     {
         if (mappings[i].scheme == scheme)
         {
             return &mappings[i].mechanism;
         }
     }
     return NULL;
 }
pkcs11_private_key_t* pkcs11_private_key_connect (key_type_t type, va_list args)
Open a private key on a PKCS#11 device.
Accepts the BUILD_SMARTCARD_KEYID and the BUILD_SMARTCARD_PIN arguments.
Parameters
type type of the key
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 638 of file pkcs11_private_key.c.
References BUILD_END, BUILD_PKCS11_KEYID, BUILD_PKCS11_MODULE, BUILD_PKCS11_SLOT, chunk_empty, ck_rv_names, CKF_SERIAL_SESSION, CKO_CERTIFICATE, CKO_PUBLIC_KEY, CKR_OK, DBG1, DBG_CFG, destroy(), find_key(), find_lib(), find_lib_by_keyid(), find_pubkey_in_certs(), free(), ID_KEY_ID, identification_create_from_encoding(), INIT, chunk_t::len, lib, login(), pkcs11_public_key_connect(), private_key_belongs_to(), private_key_equals(), private_key_has_fingerprint(), and TRUE.
Referenced by METHOD().
 {
     private_pkcs11_private_key_t *this;
     char *module = NULL;
     chunk_t keyid = chunk_empty;
     int slot = -1;
     CK_RV rv;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_PKCS11_KEYID:
                 keyid = va_arg(args, chunk_t);
                 continue;
             case BUILD_PKCS11_SLOT:
                 slot = va_arg(args, int);
                 continue;
             case BUILD_PKCS11_MODULE:
                 module = va_arg(args, char*);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!keyid.len)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .sign = _sign,
                 .decrypt = _decrypt,
                 .get_keysize = _get_keysize,
                 .get_public_key = _get_public_key,
                 .equals = private_key_equals,
                 .belongs_to = private_key_belongs_to,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = private_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     if (module && slot != -1)
     {
         this->lib = find_lib(module);
         if (!this->lib)
         {
             DBG1(DBG_CFG, "PKCS#11 module '%s' not found", module);
             free(this);
             return NULL;
         }
     }
     else
     {
         this->lib = find_lib_by_keyid(keyid, &slot, CKO_PUBLIC_KEY);
         if (!this->lib)
         {
             this->lib = find_lib_by_keyid(keyid, &slot, CKO_CERTIFICATE);
         }
         if (!this->lib)
         {
             DBG1(DBG_CFG, "no PKCS#11 module found having a keyid %#B", &keyid);
             free(this);
             return NULL;
         }
     }
     rv = this->lib->f->C_OpenSession(slot, CKF_SERIAL_SESSION,
                                      NULL, NULL, &this->session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "opening private key session on '%s':%d failed: %N",
              module, slot, ck_rv_names, rv);
         free(this);
         return NULL;
     }
     this->slot = slot;
     this->keyid = identification_create_from_encoding(ID_KEY_ID, keyid);
     if (!login(this, slot))
     {
         destroy(this);
         return NULL;
     }
     if (!find_key(this, keyid))
     {
         destroy(this);
         return NULL;
     }
     this->pubkey = pkcs11_public_key_connect(this->lib, slot, this->type, keyid);
     if (!this->pubkey)
     {
         this->pubkey = find_pubkey_in_certs(this, keyid);
         if (!this->pubkey)
         {
             DBG1(DBG_CFG, "no public key or certificate found for private key "
                  "on '%s':%d", module, slot);
             destroy(this);
             return NULL;
         }
     }
     return &this->public;
 }
CK_MECHANISM_PTR pkcs11_signature_scheme_to_mech (signature_scheme_t scheme, key_type_t type, size_t keylen, hash_algorithm_t * hash)
Get the Cryptoki mechanism for a signature scheme.
Verifies that the given key is usable for this scheme.
Parameters
scheme signature scheme
type key type
keylen key length in bits
hash hash algorithm to apply first (HASH_UNKNOWN if none)
See header.
Definition at line 102 of file pkcs11_private_key.c.
References CKM_ECDSA, CKM_ECDSA_SHA1, CKM_MD5_RSA_PKCS, CKM_RSA_PKCS, CKM_SHA1_RSA_PKCS, CKM_SHA256_RSA_PKCS, CKM_SHA384_RSA_PKCS, CKM_SHA512_RSA_PKCS, countof, hash, HASH_SHA256, HASH_SHA384, HASH_SHA512, HASH_UNKNOWN, KEY_ECDSA, KEY_RSA, len, scheme, SIGN_ECDSA_256, SIGN_ECDSA_384, SIGN_ECDSA_521, SIGN_ECDSA_WITH_NULL, SIGN_ECDSA_WITH_SHA1_DER, SIGN_ECDSA_WITH_SHA256_DER, SIGN_ECDSA_WITH_SHA384_DER, SIGN_ECDSA_WITH_SHA512_DER, SIGN_RSA_EMSA_PKCS1_MD5, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_RSA_EMSA_PKCS1_SHA1, SIGN_RSA_EMSA_PKCS1_SHA256, SIGN_RSA_EMSA_PKCS1_SHA384, SIGN_RSA_EMSA_PKCS1_SHA512, and type.
Referenced by METHOD().
 {
     static struct {
         signature_scheme_t scheme;
         CK_MECHANISM mechanism;
         key_type_t type;
         size_t keylen;
         hash_algorithm_t hash;
     } mappings[] = {
         {SIGN_RSA_EMSA_PKCS1_NULL,      {CKM_RSA_PKCS,          NULL, 0},
          KEY_RSA, 0,                                       HASH_UNKNOWN},
         {SIGN_RSA_EMSA_PKCS1_SHA1,      {CKM_SHA1_RSA_PKCS,     NULL, 0},
          KEY_RSA, 0,                                       HASH_UNKNOWN},
         {SIGN_RSA_EMSA_PKCS1_SHA256,    {CKM_SHA256_RSA_PKCS,   NULL, 0},
          KEY_RSA, 0,                                       HASH_UNKNOWN},
         {SIGN_RSA_EMSA_PKCS1_SHA384,    {CKM_SHA384_RSA_PKCS,   NULL, 0},
          KEY_RSA, 0,                                       HASH_UNKNOWN},
         {SIGN_RSA_EMSA_PKCS1_SHA512,    {CKM_SHA512_RSA_PKCS,   NULL, 0},
          KEY_RSA, 0,                                       HASH_UNKNOWN},
         {SIGN_RSA_EMSA_PKCS1_MD5,       {CKM_MD5_RSA_PKCS,      NULL, 0},
          KEY_RSA, 0,                                       HASH_UNKNOWN},
         {SIGN_ECDSA_WITH_NULL,          {CKM_ECDSA,             NULL, 0},
          KEY_ECDSA, 0,                                     HASH_UNKNOWN},
         {SIGN_ECDSA_WITH_SHA1_DER,      {CKM_ECDSA_SHA1,        NULL, 0},
          KEY_ECDSA, 0,                                     HASH_UNKNOWN},
         {SIGN_ECDSA_WITH_SHA256_DER,    {CKM_ECDSA,             NULL, 0},
          KEY_ECDSA, 0,                                      HASH_SHA256},
         {SIGN_ECDSA_WITH_SHA384_DER,    {CKM_ECDSA,             NULL, 0},
          KEY_ECDSA, 0,                                      HASH_SHA384},
         {SIGN_ECDSA_WITH_SHA512_DER,    {CKM_ECDSA,             NULL, 0},
          KEY_ECDSA, 0,                                      HASH_SHA512},
         {SIGN_ECDSA_256,                {CKM_ECDSA,             NULL, 0},
          KEY_ECDSA, 256,                                    HASH_SHA256},
         {SIGN_ECDSA_384,                {CKM_ECDSA,             NULL, 0},
          KEY_ECDSA, 384,                                    HASH_SHA384},
         {SIGN_ECDSA_521,                {CKM_ECDSA,             NULL, 0},
          KEY_ECDSA, 521,                                    HASH_SHA512},
     };
     int i;
     for (i = 0; i < countof(mappings); i++)
     {
         if (mappings[i].scheme == scheme)
         {
             size_t len = mappings[i].keylen;
             if (mappings[i].type != type || (len && keylen != len))
             {
                 return NULL;
             }
             if (hash)
             {
                 *hash = mappings[i].hash;
             }
             return &mappings[i].mechanism;
         }
     }
     return NULL;
 }