strongSwan: radius_socket.c File Reference
radius_socket.c File Reference
#include "radius_socket.h"
#include "radius_mppe.h"
#include <errno.h>
#include <unistd.h>
#include <math.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_radius_socket_t
Typedefs
typedef struct
private_radius_socket_t private_radius_socket_t
Functions
static bool check_connection (private_radius_socket_t *this, int *fd, u_int16_t port)
static status_t receive_response (int fd, int timeout, u_int8_t id, radius_message_t **response)
METHOD (radius_socket_t, request, radius_message_t *, private_radius_socket_t *this, radius_message_t *request)
static chunk_t decrypt_mppe_key (private_radius_socket_t *this, u_int16_t salt, chunk_t C, radius_message_t *request)
METHOD (radius_socket_t, decrypt_msk, chunk_t, private_radius_socket_t *this, radius_message_t *request, radius_message_t *response)
METHOD (radius_socket_t, destroy, void, private_radius_socket_t *this)
radius_socket_t * radius_socket_create (char *address, u_int16_t auth_port, u_int16_t acct_port, chunk_t secret, u_int tries, double timeout, double base)
Variables
struct private_radius_socket_t __attribute__
Typedef Documentation
typedef struct private_radius_socket_t private_radius_socket_t
Definition at line 48 of file radius_socket.c.
Function Documentation
static bool check_connection (private_radius_socket_t * this, int * fd, u_int16_t port) static
Check or establish RADIUS connection
Definition at line 129 of file radius_socket.c.
References close, connect, DBG1, DBG_CFG, host_t::destroy, FALSE, host_t::get_family, host_t::get_sockaddr, host_t::get_sockaddr_len, host_create_from_dns(), server, socket, strerror, and TRUE.
Referenced by METHOD().
 {
     if (*fd == -1)
     {
         host_t *server;
         server = host_create_from_dns(this->address, AF_UNSPEC, port);
         if (!server)
         {
             DBG1(DBG_CFG, "resolving RADIUS server address '%s' failed",
                  this->address);
             return FALSE;
         }
         *fd = socket(server->get_family(server), SOCK_DGRAM, IPPROTO_UDP);
         if (*fd == -1)
         {
             DBG1(DBG_CFG, "opening RADIUS socket for %#H failed: %s",
                  server, strerror(errno));
             server->destroy(server);
             return FALSE;
         }
         if (connect(*fd, server->get_sockaddr(server),
                     *server->get_sockaddr_len(server)) < 0)
         {
             DBG1(DBG_CFG, "connecting RADIUS socket to %#H failed: %s",
                  server, strerror(errno));
             server->destroy(server);
             close(*fd);
             *fd = -1;
             return FALSE;
         }
         server->destroy(server);
     }
     return TRUE;
 }
static chunk_t decrypt_mppe_key (private_radius_socket_t * this, u_int16_t salt, chunk_t C, radius_message_t * request) static
Decrypt a MS-MPPE-Send/Recv-Key
Definition at line 302 of file radius_socket.c.
References chunk_alloca, chunk_clone, chunk_create(), chunk_empty, chunk_from_thing, radius_message_t::crypt, hasher, chunk_t::len, and chunk_t::ptr.
Referenced by METHOD().
 {
     chunk_t decrypted;
     decrypted = chunk_alloca(C.len);
     if (!request->crypt(request, chunk_from_thing(salt), C, decrypted,
                         this->secret, this->hasher) ||
         decrypted.ptr[0] >= decrypted.len)
     {   /* decryption failed? */
         return chunk_empty;
     }
     /* remove truncation, first byte is key length */
     return chunk_clone(chunk_create(decrypted.ptr + 1, decrypted.ptr[0]));
 }
METHOD (radius_socket_t , request , radius_message_t * , private_radius_socket_t * this, radius_message_t * request)
Definition at line 221 of file radius_socket.c.
References check_connection(), data, DBG1, DBG3, DBG_CFG, radius_message_t::destroy, pollfd::fd, radius_message_t::get_authenticator, radius_message_t::get_code, radius_message_t::get_encoding, radius_message_t::get_identifier, hasher, identifier, chunk_t::len, OUT_OF_RES, port, chunk_t::ptr, radius_message_code_names, receive_response(), response, retransmit(), RMC_ACCOUNTING_REQUEST, rng, send, radius_message_t::set_identifier, radius_message_t::sign, signer, strerror, SUCCESS, and radius_message_t::verify.
 {
     radius_message_t *response;
     chunk_t data;
     int *fd, retransmit = 0, timeout;
     u_int16_t port;
     rng_t *rng = NULL;
     if (request->get_code(request) == RMC_ACCOUNTING_REQUEST)
     {
         fd = &this->acct_fd;
         port = this->acct_port;
     }
     else
     {
         fd = &this->auth_fd;
         port = this->auth_port;
         rng = this->rng;
     }
     /* set Message Identifier */
     request->set_identifier(request, this->identifier++);
     /* sign the request */
     if (!request->sign(request, NULL, this->secret, this->hasher, this->signer,
                        rng, rng != NULL))
     {
         return NULL;
     }
     if (!check_connection(this, fd, port))
     {
         return NULL;
     }
     data = request->get_encoding(request);
     DBG3(DBG_CFG, "%B", &data);
     while (retransmit < this->retransmit_tries)
     {
         timeout = (int)(this->retransmit_timeout * 1000.0 *
                         pow(this->retransmit_base, retransmit));
         if (retransmit)
         {
             DBG1(DBG_CFG, "retransmit %d of RADIUS %N (timeout: %.1fs)",
                  retransmit, radius_message_code_names,
                  request->get_code(request), timeout/1000.0);
         }
         if (send(*fd, data.ptr, data.len, 0) != data.len)
         {
             DBG1(DBG_CFG, "sending RADIUS message failed: %s", strerror(errno));
             return NULL;
         }
         switch (receive_response(*fd, timeout, request->get_identifier(request),
                                  &response))
         {
             case SUCCESS:
                 break;
             case OUT_OF_RES:
                 retransmit++;
                 continue;
             default:
                 return NULL;
         }
         if (response->verify(response, request->get_authenticator(request),
                              this->secret, this->hasher, this->signer))
         {
             return response;
         }
         response->destroy(response);
         return NULL;
     }
     DBG1(DBG_CFG, "RADIUS %N timed out after %d attempts",
          radius_message_code_names, request->get_code(request), retransmit);
     return NULL;
 }
METHOD (radius_socket_t , decrypt_msk , chunk_t , private_radius_socket_t * this, radius_message_t * request, radius_message_t * response)
Definition at line 318 of file radius_socket.c.
References chunk_cat, chunk_clear(), chunk_create(), chunk_empty, radius_message_t::create_enumerator, data, decrypt_mppe_key(), enumerator_t::destroy, enumerator_t::enumerate, mppe_key_t::id, if(), mppe_key_t::key, chunk_t::len, mppe_key_t::length, MS_MPPE_RECV_KEY, MS_MPPE_SEND_KEY, PEN_MICROSOFT, chunk_t::ptr, RAT_VENDOR_SPECIFIC, recv, mppe_key_t::salt, send, mppe_key_t::type, and type.
 {
     mppe_key_t *mppe_key;
     enumerator_t *enumerator;
     chunk_t data, send = chunk_empty, recv = chunk_empty;
     int type;
     enumerator = response->create_enumerator(response);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (type == RAT_VENDOR_SPECIFIC && data.len > sizeof(mppe_key_t))
         {
             mppe_key = (mppe_key_t*)data.ptr;
             if (ntohl(mppe_key->id) == PEN_MICROSOFT &&
                 mppe_key->length == data.len - sizeof(mppe_key->id))
             {
                 data = chunk_create(mppe_key->key, data.len - sizeof(mppe_key_t));
                 if (mppe_key->type == MS_MPPE_SEND_KEY)
                 {
                     send = decrypt_mppe_key(this, mppe_key->salt, data, request);
                 }
                 if (mppe_key->type == MS_MPPE_RECV_KEY)
                 {
                     recv = decrypt_mppe_key(this, mppe_key->salt, data, request);
                 }
             }
         }
     }
     enumerator->destroy(enumerator);
     if (send.ptr && recv.ptr)
     {
         return chunk_cat("mm", recv, send);
     }
     chunk_clear(&send);
     chunk_clear(&recv);
     return chunk_empty;
 }
METHOD (radius_socket_t , destroy , void , private_radius_socket_t * this)
Definition at line 358 of file radius_socket.c.
References close, DESTROY_IF, free(), hasher, rng, and signer.
 {
     DESTROY_IF(this->hasher);
     DESTROY_IF(this->signer);
     DESTROY_IF(this->rng);
     if (this->auth_fd != -1)
     {
         close(this->auth_fd);
     };
     if (this->acct_fd != -1)
     {
         close(this->acct_fd);
     }
     free(this);
 }
static status_t receive_response (int fd, int timeout, u_int8_t id, radius_message_t ** response) static
Receive the response to the message with the given ID
Definition at line 169 of file radius_socket.c.
References chunk_create(), DBG1, DBG_CFG, radius_message_t::destroy, FAILED, pollfd::fd, radius_message_t::get_identifier, id, msg, MSG_DONTWAIT, OUT_OF_RES, poll, POLLIN, radius_message_parse(), recv, res, strerror, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     radius_message_t *msg;
     char buf[4096];
     int res;
     struct pollfd pfd = {
         .fd = fd,
         .events = POLLIN,
     };
     while (TRUE)
     {
         res = poll(&pfd, 1, timeout);
         if (res < 0)
         {
             DBG1(DBG_CFG, "waiting for RADIUS message failed: %s",
                  strerror(errno));
             return FAILED;
         }
         if (res == 0)
         {   /* timeout */
             return OUT_OF_RES;
         }
         res = recv(fd, buf, sizeof(buf), MSG_DONTWAIT);
         if (res <= 0)
         {
             DBG1(DBG_CFG, "receiving RADIUS message failed: %s",
                  strerror(errno));
             return FAILED;
         }
         msg = radius_message_parse(chunk_create(buf, res));
         if (!msg)
         {
             DBG1(DBG_CFG, "received invalid RADIUS message, ignored");
             return FAILED;
         }
         if (id != msg->get_identifier(msg))
         {
             /* we haven't received the response to our current request, but
              * perhaps one for an earlier request for which we didn't wait
              * long enough */
             DBG1(DBG_CFG, "received RADIUS message with unexpected ID %d "
                  "[%d expected], ignored", msg->get_identifier(msg), id);
             msg->destroy(msg);
             continue;
         }
         *response = msg;
         return SUCCESS;
     }
 }
Variable Documentation
struct private_radius_socket_t __attribute__