strongSwan: imv_session_manager
imv_session_manager
imv
Classes
struct imv_session_manager_t
Typedefs
typedef struct
imv_session_manager_t imv_session_manager_t
Functions
imv_session_manager_t * imv_session_manager_create ()
Detailed Description
Typedef Documentation
typedef struct imv_session_manager_t imv_session_manager_t
Definition at line 31 of file imv_session_manager.h.
Function Documentation
imv_session_manager_t* imv_session_manager_create (void)
Create an imv_session_manager_t instance
See header
Definition at line 149 of file imv_session_manager.c.
References INIT, linked_list_create(), mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by libimcv_init().
 {
     private_imv_session_manager_t *this;
     INIT(this,
         .public = {
             .add_session = _add_session,
             .remove_session = _remove_session,
             .destroy = _destroy,
         },
         .sessions = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     return &this->public;
 }