strongSwan: linked_list.c File Reference
linked_list.c File Reference
#include <stdlib.h>
#include <stdarg.h>
#include "linked_list.h"
Classes
struct element_t
struct private_linked_list_t
struct private_enumerator_t
Typedefs
typedef struct element_t element_t
typedef struct
private_linked_list_t private_linked_list_t
typedef struct private_enumerator_t private_enumerator_t
Functions
element_t * element_create (void *value)
METHOD (enumerator_t, enumerate, bool, private_enumerator_t *this, void **item)
METHOD (linked_list_t, create_enumerator, enumerator_t *, private_linked_list_t *this)
METHOD (linked_list_t, reset_enumerator, void, private_linked_list_t *this, private_enumerator_t *enumerator)
METHOD (linked_list_t, get_count, int, private_linked_list_t *this)
METHOD (linked_list_t, insert_first, void, private_linked_list_t *this, void *item)
static element_t * remove_element (private_linked_list_t *this, element_t *element)
METHOD (linked_list_t, get_first, status_t, private_linked_list_t *this, void **item)
METHOD (linked_list_t, remove_first, status_t, private_linked_list_t *this, void **item)
METHOD (linked_list_t, insert_last, void, private_linked_list_t *this, void *item)
METHOD (linked_list_t, insert_before, void, private_linked_list_t *this, private_enumerator_t *enumerator, void *item)
METHOD (linked_list_t, get_last, status_t, private_linked_list_t *this, void **item)
METHOD (linked_list_t, remove_last, status_t, private_linked_list_t *this, void **item)
METHOD (linked_list_t, remove_, int, private_linked_list_t *this, void *item, bool(*compare)(void *, void *))
METHOD (linked_list_t, remove_at, void, private_linked_list_t *this, private_enumerator_t *enumerator)
METHOD (linked_list_t, find_first, status_t, private_linked_list_t *this, linked_list_match_t match, void **item, void *d1, void *d2, void *d3, void *d4, void *d5)
METHOD (linked_list_t, invoke_offset, void, private_linked_list_t *this, size_t offset, void *d1, void *d2, void *d3, void *d4, void *d5)
METHOD (linked_list_t, invoke_function, void, private_linked_list_t *this, linked_list_invoke_t fn, void *d1, void *d2, void *d3, void *d4, void *d5)
METHOD (linked_list_t, clone_offset, linked_list_t *, private_linked_list_t *this, size_t offset)
METHOD (linked_list_t, destroy, void, private_linked_list_t *this)
METHOD (linked_list_t, destroy_offset, void, private_linked_list_t *this, size_t offset)
METHOD (linked_list_t, destroy_function, void, private_linked_list_t *this, void(*fn)(void *))
linked_list_t * linked_list_create ()
linked_list_t * linked_list_create_from_enumerator (enumerator_t *enumerator)
linked_list_t * linked_list_create_with_items (void *item,...)
Typedef Documentation
typedef struct element_t element_t
Definition at line 23 of file linked_list.c.
typedef struct private_enumerator_t private_enumerator_t
Definition at line 93 of file linked_list.c.
typedef struct private_linked_list_t private_linked_list_t
Definition at line 63 of file linked_list.c.
Function Documentation
element_t* element_create (void * value)
Creates an empty linked list object.
Definition at line 53 of file linked_list.c.
References INIT.
Referenced by METHOD().
 {
     element_t *this;
     INIT(this,
         .value = value,
     );
     return this;
 }
METHOD (enumerator_t , enumerate , bool , private_enumerator_t * this, void ** item)
Definition at line 121 of file linked_list.c.
References FALSE, list, and TRUE.
 {
     if (this->finished)
     {
         return FALSE;
     }
     if (!this->current)
     {
         this->current = this->list->first;
     }
     else
     {
         this->current = this->current->next;
     }
     if (!this->current)
     {
         this->finished = TRUE;
         return FALSE;
     }
     if (item)
     {
         *item = this->current->value;
     }
     return TRUE;
 }
METHOD (linked_list_t , create_enumerator , enumerator_t * , private_linked_list_t * this)
Definition at line 148 of file linked_list.c.
References destroy(), private_enumerator_t::enumerator, free(), and INIT.
 {
     private_enumerator_t *enumerator;
     INIT(enumerator,
         .enumerator = {
             .enumerate = (void*)_enumerate,
             .destroy = (void*)free,
         },
         .list = this,
     );
     return &enumerator->enumerator;
 }
METHOD (linked_list_t , reset_enumerator , void , private_linked_list_t * this, private_enumerator_t * enumerator)
Definition at line 164 of file linked_list.c.
References private_enumerator_t::current, FALSE, and private_enumerator_t::finished.
 {
     enumerator->current = NULL;
     enumerator->finished = FALSE;
 }
METHOD (linked_list_t , get_count , int , private_linked_list_t * this)
Definition at line 171 of file linked_list.c.
References count.
 {
     return this->count;
 }
METHOD (linked_list_t , insert_first , void , private_linked_list_t * this, void * item)
Definition at line 177 of file linked_list.c.
References count, element_create(), element_t::next, and element_t::previous.
 {
     element_t *element;
     element = element_create(item);
     if (this->count == 0)
     {
         /* first entry in list */
         this->first = element;
         this->last = element;
     }
     else
     {
         element->next = this->first;
         this->first->previous = element;
         this->first = element;
     }
     this->count++;
 }
METHOD (linked_list_t , get_first , status_t , private_linked_list_t * this, void ** item)
Definition at line 233 of file linked_list.c.
References count, NOT_FOUND, and SUCCESS.
 {
     if (this->count == 0)
     {
         return NOT_FOUND;
     }
     *item = this->first->value;
     return SUCCESS;
 }
METHOD (linked_list_t , remove_first , status_t , private_linked_list_t * this, void ** item)
Definition at line 244 of file linked_list.c.
References NOT_FOUND, remove_element(), and SUCCESS.
 {
     if (get_first(this, item) == SUCCESS)
     {
         remove_element(this, this->first);
         return SUCCESS;
     }
     return NOT_FOUND;
 }
METHOD (linked_list_t , insert_last , void , private_linked_list_t * this, void * item)
Definition at line 255 of file linked_list.c.
References count, element_create(), element_t::next, and element_t::previous.
 {
     element_t *element;
     element = element_create(item);
     if (this->count == 0)
     {
         /* first entry in list */
         this->first = element;
         this->last = element;
     }
     else
     {
         element->previous = this->last;
         this->last->next = element;
         this->last = element;
     }
     this->count++;
 }
METHOD (linked_list_t , insert_before , void , private_linked_list_t * this, private_enumerator_t * enumerator, void * item)
Definition at line 276 of file linked_list.c.
References count, private_enumerator_t::current, element_create(), private_enumerator_t::finished, element_t::next, and element_t::previous.
 {
     element_t *current, *element;
     current = enumerator->current;
     if (!current)
     {
         if (enumerator->finished)
         {
             this->public.insert_last(&this->public, item);
         }
         else
         {
             this->public.insert_first(&this->public, item);
         }
         return;
     }
     element = element_create(item);
     if (current->previous)
     {
         current->previous->next = element;
         element->previous = current->previous;
         current->previous = element;
         element->next = current;
     }
     else
     {
         current->previous = element;
         element->next = current;
         this->first = element;
     }
     this->count++;
 }
METHOD (linked_list_t , get_last , status_t , private_linked_list_t * this, void ** item)
Definition at line 312 of file linked_list.c.
References count, NOT_FOUND, and SUCCESS.
 {
     if (this->count == 0)
     {
         return NOT_FOUND;
     }
     *item = this->last->value;
     return SUCCESS;
 }
METHOD (linked_list_t , remove_last , status_t , private_linked_list_t * this, void ** item)
Definition at line 323 of file linked_list.c.
References NOT_FOUND, remove_element(), and SUCCESS.
 {
     if (get_last(this, item) == SUCCESS)
     {
         remove_element(this, this->last);
         return SUCCESS;
     }
     return NOT_FOUND;
 }
METHOD (linked_list_t , remove_ , int , private_linked_list_t * this, void * item, bool(*)(void *, void *) compare)
Definition at line 334 of file linked_list.c.
References compare(), element_t::next, remove_element(), and element_t::value.
 {
     element_t *current = this->first;
     int removed = 0;
     while (current)
     {
         if ((compare && compare(current->value, item)) ||
             (!compare && current->value == item))
         {
             removed++;
             current = remove_element(this, current);
         }
         else
         {
             current = current->next;
         }
     }
     return removed;
 }
METHOD (linked_list_t , remove_at , void , private_linked_list_t * this, private_enumerator_t * enumerator)
Definition at line 356 of file linked_list.c.
References private_enumerator_t::current, element_t::previous, and remove_element().
 {
     element_t *current;
     if (enumerator->current)
     {
         current = enumerator->current;
         enumerator->current = current->previous;
         remove_element(this, current);
     }
 }
METHOD (linked_list_t , find_first , status_t , private_linked_list_t * this, linked_list_match_t match, void ** item, void * d1, void * d2, void * d3, void * d4, void * d5)
Definition at line 369 of file linked_list.c.
References match(), element_t::next, NOT_FOUND, SUCCESS, and element_t::value.
 {
     element_t *current = this->first;
     while (current)
     {
         if ((match && match(current->value, d1, d2, d3, d4, d5)) ||
             (!match && item && current->value == *item))
         {
             if (item != NULL)
             {
                 *item = current->value;
             }
             return SUCCESS;
         }
         current = current->next;
     }
     return NOT_FOUND;
 }
METHOD (linked_list_t , invoke_offset , void , private_linked_list_t * this, size_t offset, void * d1, void * d2, void * d3, void * d4, void * d5)
Definition at line 391 of file linked_list.c.
References element_t::next, offset, and element_t::value.
 {
     element_t *current = this->first;
     linked_list_invoke_t *method;
     while (current)
     {
         method = current->value + offset;
         (*method)(current->value, d1, d2, d3, d4, d5);
         current = current->next;
     }
 }
METHOD (linked_list_t , invoke_function , void , private_linked_list_t * this, linked_list_invoke_t fn, void * d1, void * d2, void * d3, void * d4, void * d5)
Definition at line 406 of file linked_list.c.
References fn, element_t::next, and element_t::value.
 {
     element_t *current = this->first;
     while (current)
     {
         fn(current->value, d1, d2, d3, d4, d5);
         current = current->next;
     }
 }
METHOD (linked_list_t , clone_offset , linked_list_t * , private_linked_list_t * this, size_t offset)
Definition at line 419 of file linked_list.c.
References linked_list_t::insert_last, linked_list_create(), element_t::next, and element_t::value.
 {
     element_t *current = this->first;
     linked_list_t *clone;
     clone = linked_list_create();
     while (current)
     {
         void* (**method)(void*) = current->value + offset;
         clone->insert_last(clone, (*method)(current->value));
         current = current->next;
     }
     return clone;
 }
METHOD (linked_list_t , destroy , void , private_linked_list_t * this)
Definition at line 436 of file linked_list.c.
References free(), remove_first(), SUCCESS, and value.
 {
     void *value;
     /* Remove all list items before destroying list */
     while (remove_first(this, &value) == SUCCESS)
     {
         /* values are not destroyed so memory leaks are possible
          * if list is not empty when deleting */
     }
     free(this);
 }
METHOD (linked_list_t , destroy_offset , void , private_linked_list_t * this, size_t offset)
Definition at line 450 of file linked_list.c.
References free(), element_t::next, next, and element_t::value.
 {
     element_t *current = this->first, *next;
     while (current)
     {
         void (**method)(void*) = current->value + offset;
         (*method)(current->value);
         next = current->next;
         free(current);
         current = next;
     }
     free(this);
 }
METHOD (linked_list_t , destroy_function , void , private_linked_list_t * this, void(*)(void *) fn)
Definition at line 466 of file linked_list.c.
References fn, free(), element_t::next, next, and element_t::value.
 {
     element_t *current = this->first, *next;
     while (current)
     {
         fn(current->value);
         next = current->next;
         free(current);
         current = next;
     }
     free(this);
 }
static element_t* remove_element (private_linked_list_t * this, element_t * element) static
unlink an element form the list, returns following element
Definition at line 201 of file linked_list.c.
References count, free(), element_t::next, next, element_t::previous, and previous.
Referenced by METHOD().
 {
     element_t *next, *previous;
     next = element->next;
     previous = element->previous;
     free(element);
     if (next)
     {
         next->previous = previous;
     }
     else
     {
         this->last = previous;
     }
     if (previous)
     {
         previous->next = next;
     }
     else
     {
         this->first = next;
     }
     if (--this->count == 0)
     {
         this->first = NULL;
         this->last = NULL;
     }
     return next;
 }