strongSwan: bliss_bitpacker.c File Reference
bliss_bitpacker.c File Reference
#include "bliss_bitpacker.h"
Classes
struct private_bliss_bitpacker_t
Typedefs
typedef struct
private_bliss_bitpacker_t private_bliss_bitpacker_t
Functions
METHOD (bliss_bitpacker_t, get_bits, size_t, private_bliss_bitpacker_t *this)
METHOD (bliss_bitpacker_t, write_bits, bool, private_bliss_bitpacker_t *this, uint32_t value, size_t bits)
METHOD (bliss_bitpacker_t, read_bits, bool, private_bliss_bitpacker_t *this, uint32_t *value, size_t bits)
METHOD (bliss_bitpacker_t, extract_buf, chunk_t, private_bliss_bitpacker_t *this)
METHOD (bliss_bitpacker_t, destroy, void, private_bliss_bitpacker_t *this)
bliss_bitpacker_t * bliss_bitpacker_create (uint16_t max_bits)
bliss_bitpacker_t * bliss_bitpacker_create_from_data (chunk_t data)
Typedef Documentation
typedef struct private_bliss_bitpacker_t private_bliss_bitpacker_t
Definition at line 18 of file bliss_bitpacker.c.
Function Documentation
METHOD (bliss_bitpacker_t , get_bits , size_t , private_bliss_bitpacker_t * this)
Definition at line 56 of file bliss_bitpacker.c.
References bits.
 {
     return this->bits;
 }
METHOD (bliss_bitpacker_t , write_bits , bool , private_bliss_bitpacker_t * this, uint32_t value, size_t bits)
Definition at line 62 of file bliss_bitpacker.c.
References bits, chunk_skip(), FALSE, htoun32(), and TRUE.
 {
     if (bits == 0)
     {
         return TRUE;
     }
     if (bits > 32)
     {
         return FALSE;
     }
     if (bits < 32)
     {
         value &= (1 << bits) - 1;
     }
     this->bits += bits;
     while (TRUE)
     {
         if (bits <= this->bits_left)
         {
             this->bits_buf |= value << (this->bits_left - bits);
             this->bits_left -= bits;
             return TRUE;
         }
         this->bits_buf |= value >> (bits - this->bits_left);
         value &= (1 << (bits - this->bits_left)) - 1;
         bits -= this->bits_left;
         if (this->pos.len < 8)
         {
             return FALSE;
         }
         htoun32(this->pos.ptr, this->bits_buf);
         this->pos = chunk_skip(this->pos, 4);
         this->bits_buf = 0;
         this->bits_left = 32;
     }
 }
METHOD (bliss_bitpacker_t , read_bits , bool , private_bliss_bitpacker_t * this, uint32_t * value, size_t bits)
Definition at line 103 of file bliss_bitpacker.c.
References bits, chunk_skip(), FALSE, TRUE, and untoh32().
 {
     if (bits > 32)
     {
         return FALSE;
     }
     *value = 0;
     while (TRUE)
     {
         if (this->bits_left == 0)
         {
             if (this->pos.len < 4)
             {
                 return FALSE;
             }
             this->bits_buf = untoh32(this->pos.ptr);
             this->pos = chunk_skip(this->pos, 4);
             this->bits_left = 32;
         }
         if (bits <= this->bits_left)
         {
             *value |= this->bits_buf >> (this->bits_left - bits);
             this->bits_buf &= (1 << (this->bits_left - bits)) - 1;
             this->bits_left -= bits;
             return TRUE;
         }
         *value |= this->bits_buf << (bits - this->bits_left);
         bits -= this->bits_left;
         this->bits_left = 0;
     }
 }
METHOD (bliss_bitpacker_t , extract_buf , chunk_t , private_bliss_bitpacker_t * this)
Definition at line 138 of file bliss_bitpacker.c.
References chunk_empty, htoun32(), and chunk_t::len.
 {
     chunk_t buf;
     htoun32(this->pos.ptr, this->bits_buf);
     this->pos.len -= 4;
     buf = this->buf;
     buf.len = this->buf.len - this->pos.len - this->bits_left/8;
     this->buf = this->pos = chunk_empty;
     return buf;
 }
METHOD (bliss_bitpacker_t , destroy , void , private_bliss_bitpacker_t * this)
Definition at line 152 of file bliss_bitpacker.c.
References free().
 {
     free(this->buf.ptr);
     free(this);
 }