strongSwan: ike_natd
ike_natd
tasks
Classes
struct ike_natd_t
Typedefs
typedef struct ike_natd_t ike_natd_t
Functions
ike_natd_t * ike_natd_create (ike_sa_t *ike_sa, bool initiator)
Detailed Description
Typedef Documentation
typedef struct ike_natd_t ike_natd_t
Definition at line 24 of file ike_natd.h.
Function Documentation
ike_natd_t* ike_natd_create (ike_sa_t * ike_sa, bool initiator)
Create a new ike_natd task.
Parameters
ike_sa IKE_SA this task works for
initiator TRUE if task is the original initiator
Returns
ike_natd task to handle by the task_manager
Definition at line 443 of file ike_natd.c.
References crypto_factory_t::create_hasher, library_t::crypto, HASH_SHA1, INIT, initiator, and lib.
Referenced by METHOD(), process_payloads(), and process_request().
 {
     private_ike_natd_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
             .has_mapping_changed = _has_mapping_changed,
         },
         .ike_sa = ike_sa,
         .initiator = initiator,
         .hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1),
     );
     if (initiator)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
     }
     return &this->public;
 }