strongSwan: ha_message
ha_message
ha
Classes
union ha_message_value_t
struct ha_message_t
Macros
#define HA_MESSAGE_VERSION 3
Typedefs
typedef struct ha_message_t ha_message_t
typedef enum ha_message_type_t ha_message_type_t
typedef enum ha_message_attribute_t ha_message_attribute_t
typedef union ha_message_value_t ha_message_value_t
Enumerations
enum ha_message_type_t {
HA_IKE_ADD = 1, HA_IKE_UPDATE, HA_IKE_MID_INITIATOR, HA_IKE_MID_RESPONDER,
HA_IKE_DELETE, HA_CHILD_ADD, HA_CHILD_DELETE, HA_SEGMENT_DROP,
HA_SEGMENT_TAKE, HA_STATUS, HA_RESYNC, HA_IKE_IV
}
enum ha_message_attribute_t {
HA_IKE_ID = 1, HA_IKE_REKEY_ID, HA_LOCAL_ID, HA_REMOTE_ID,
HA_REMOTE_EAP_ID, HA_LOCAL_ADDR, HA_REMOTE_ADDR, HA_CONFIG_NAME,
HA_CONDITIONS, HA_EXTENSIONS, HA_LOCAL_VIP, HA_REMOTE_VIP,
HA_PEER_ADDR, HA_INITIATOR, HA_NONCE_I, HA_NONCE_R,
HA_SECRET, HA_OLD_SKD, HA_ALG_PRF, HA_ALG_OLD_PRF,
HA_ALG_ENCR, HA_ALG_ENCR_LEN, HA_ALG_INTEG, HA_IPSEC_MODE,
HA_IPCOMP, HA_INBOUND_SPI, HA_OUTBOUND_SPI, HA_INBOUND_CPI,
HA_OUTBOUND_CPI, HA_LOCAL_TS, HA_REMOTE_TS, HA_MID,
HA_SEGMENT, HA_ESN, HA_IKE_VERSION, HA_LOCAL_DH,
HA_REMOTE_DH, HA_PSK, HA_IV
}
Functions
ha_message_t * ha_message_create (ha_message_type_t type)
ha_message_t * ha_message_parse (chunk_t data)
Variables
enum_name_t * ha_message_type_names
Detailed Description
Macro Definition Documentation
#define HA_MESSAGE_VERSION 3
Protocol version of this implementation
Definition at line 33 of file ha_message.h.
Referenced by ha_message_create(), and ha_message_parse().
Typedef Documentation
typedef enum ha_message_attribute_t ha_message_attribute_t
Definition at line 37 of file ha_message.h.
typedef struct ha_message_t ha_message_t
Definition at line 35 of file ha_message.h.
typedef enum ha_message_type_t ha_message_type_t
Definition at line 36 of file ha_message.h.
typedef union ha_message_value_t ha_message_value_t
Definition at line 38 of file ha_message.h.
Enumeration Type Documentation
enum ha_message_attribute_t
Type of attributes contained in a message
Enumerator
HA_IKE_ID
ike_sa_id_t*, to identify IKE_SA
HA_IKE_REKEY_ID
ike_sa_id_t*, identifies IKE_SA which gets rekeyed
HA_LOCAL_ID
identification_t*, local identity
HA_REMOTE_ID
identification_t*, remote identity
HA_REMOTE_EAP_ID
identification_t*, remote EAP identity
HA_LOCAL_ADDR
host_t*, local address
HA_REMOTE_ADDR
host_t*, remote address
HA_CONFIG_NAME
char*, name of configuration
HA_CONDITIONS
u_int32_t, bitset of ike_condition_t
HA_EXTENSIONS
u_int32_t, bitset of ike_extension_t
HA_LOCAL_VIP
host_t*, local virtual IP
HA_REMOTE_VIP
host_t*, remote virtual IP
HA_PEER_ADDR
host_t*, known peer addresses (used for MOBIKE)
HA_INITIATOR
u_int8_t, initiator of an exchange, TRUE for local
HA_NONCE_I
chunk_t, initiators nonce
HA_NONCE_R
chunk_t, responders nonce
HA_SECRET
chunk_t, diffie hellman shared secret
HA_OLD_SKD
chunk_t, SKd of old SA if rekeying
HA_ALG_PRF
u_int16_t, pseudo random function
HA_ALG_OLD_PRF
u_int16_t, old pseudo random function if rekeying
HA_ALG_ENCR
u_int16_t, encryption algorithm
HA_ALG_ENCR_LEN
u_int16_t, encryption key size in bytes
HA_ALG_INTEG
u_int16_t, integrity protection algorithm
HA_IPSEC_MODE
u_int8_t, IPsec mode, TUNNEL|TRANSPORT|...
HA_IPCOMP
u_int8_t, IPComp protocol
HA_INBOUND_SPI
u_int32_t, inbound security parameter index
HA_OUTBOUND_SPI
u_int32_t, outbound security parameter index
HA_INBOUND_CPI
u_int16_t, inbound security parameter index
HA_OUTBOUND_CPI
u_int16_t, outbound security parameter index
HA_LOCAL_TS
traffic_selector_t*, local traffic selector
HA_REMOTE_TS
traffic_selector_t*, remote traffic selector
HA_MID
u_int32_t, message ID
HA_SEGMENT
u_int16_t, HA segment
HA_ESN
u_int16_t, Extended Sequence numbers
HA_IKE_VERSION
u_int8_t, IKE version
HA_LOCAL_DH
chunk_t, own DH public value
HA_REMOTE_DH
chunk_t, remote DH public value
HA_PSK
chunk_t, shared secret for IKEv1 key derivation
HA_IV
chunk_t, IV for next IKEv1 message
Definition at line 78 of file ha_message.h.
{
     HA_IKE_ID = 1,
     HA_IKE_REKEY_ID,
     HA_LOCAL_ID,
     HA_REMOTE_ID,
     HA_REMOTE_EAP_ID,
     HA_LOCAL_ADDR,
     HA_REMOTE_ADDR,
     HA_CONFIG_NAME,
     HA_CONDITIONS,
     HA_EXTENSIONS,
     HA_LOCAL_VIP,
     HA_REMOTE_VIP,
     HA_PEER_ADDR,
     HA_INITIATOR,
     HA_NONCE_I,
     HA_NONCE_R,
     HA_SECRET,
     HA_OLD_SKD,
     HA_ALG_PRF,
     HA_ALG_OLD_PRF,
     HA_ALG_ENCR,
     HA_ALG_ENCR_LEN,
     HA_ALG_INTEG,
     HA_IPSEC_MODE,
     HA_IPCOMP,
     HA_INBOUND_SPI,
     HA_OUTBOUND_SPI,
     HA_INBOUND_CPI,
     HA_OUTBOUND_CPI,
     HA_LOCAL_TS,
     HA_REMOTE_TS,
     HA_MID,
     HA_SEGMENT,
     HA_ESN,
     HA_IKE_VERSION,
     HA_LOCAL_DH,
     HA_REMOTE_DH,
     HA_PSK,
     HA_IV,
 };
enum ha_message_type_t
Type of a HA message
Enumerator
HA_IKE_ADD
add a completely new IKE_SA
HA_IKE_UPDATE
update an existing IKE_SA (identities, address update, ...)
HA_IKE_MID_INITIATOR
update initiator message id
HA_IKE_MID_RESPONDER
update responder message id
HA_IKE_DELETE
delete an existing IKE_SA
HA_CHILD_ADD
add a new CHILD_SA
HA_CHILD_DELETE
delete an existing CHILD_SA
HA_SEGMENT_DROP
segments the sending node is giving up
HA_SEGMENT_TAKE
segments the sending node is taking over
HA_STATUS
status with the segments the sending node is currently serving
HA_RESYNC
segments the receiving node is requested to resync
HA_IKE_IV
IV synchronization for IKEv1 Main/Aggressive mode
Definition at line 43 of file ha_message.h.
{
     HA_IKE_ADD = 1,
     HA_IKE_UPDATE,
     HA_IKE_MID_INITIATOR,
     HA_IKE_MID_RESPONDER,
     HA_IKE_DELETE,
     HA_CHILD_ADD,
     HA_CHILD_DELETE,
     HA_SEGMENT_DROP,
     HA_SEGMENT_TAKE,
     HA_STATUS,
     HA_RESYNC,
     HA_IKE_IV,
 };
Function Documentation
ha_message_t* ha_message_create (ha_message_type_t type)
Create a new ha_message instance, ready for adding attributes
Parameters
type type of the message
See header
Definition at line 645 of file ha_message.c.
References allocated, ALLOCATION_BLOCK, ha_message_create_generic(), HA_MESSAGE_VERSION, malloc(), and type.
Referenced by enable_disable(), METHOD(), request_resync(), send_status(), and sync_vips().
 {
     private_ha_message_t *this = ha_message_create_generic();
     this->allocated = ALLOCATION_BLOCK;
     this->buf.ptr = malloc(this->allocated);
     this->buf.len = 2;
     this->buf.ptr[0] = HA_MESSAGE_VERSION;
     this->buf.ptr[1] = type;
     return &this->public;
 }
ha_message_t* ha_message_parse (chunk_t data)
Create a ha_message from encoded data.
Parameters
data encoded message data
See header
Definition at line 661 of file ha_message.c.
References allocated, chunk_clone, DBG1, DBG_CFG, ha_message_create_generic(), HA_MESSAGE_VERSION, chunk_t::len, and chunk_t::ptr.
Referenced by METHOD().
 {
     private_ha_message_t *this;
     if (data.len < 2)
     {
         DBG1(DBG_CFG, "HA message too short");
         return NULL;
     }
     if (data.ptr[0] != HA_MESSAGE_VERSION)
     {
         DBG1(DBG_CFG, "HA message has version %d, expected %d",
              data.ptr[0], HA_MESSAGE_VERSION);
         return NULL;
     }
     this = ha_message_create_generic();
     this->buf = chunk_clone(data);
     this->allocated = this->buf.len;
     return &this->public;
 }
Variable Documentation
enum_name_t* ha_message_type_names
Enum names for message types
Referenced by dispatch().