strongSwan: mgf1_t Struct Reference
mgf1_t Struct Reference
mgf1
#include "mgf1.h"
Public Attributes
size_t(* get_hash_size)(mgf1_t *this)
bool(* get_mask)(mgf1_t *this, size_t mask_len, u_char *mask)
bool(* allocate_mask)(mgf1_t *this, size_t mask_len, chunk_t *mask)
void(* destroy)(mgf1_t *this)
Detailed Description
Implements the PKCS#1 MGF1 Mask Generation Function based on a hash function defined in section 10.2.1 of RFC 2437
Definition at line 32 of file mgf1.h.
Member Data Documentation
bool(* mgf1_t::allocate_mask)(mgf1_t *this, size_t mask_len, chunk_t *mask)
Generate a mask pattern and return it in an allocated chunk
Parameters
mask_len number of mask bytes to generate
mask chunk containing generated mask
Returns
TRUE if successful
Definition at line 58 of file mgf1.h.
Referenced by START_TEST().
void(* mgf1_t::destroy)(mgf1_t *this)
Destroy the MGF1 object
Definition at line 63 of file mgf1.h.
Referenced by START_TEST().
size_t(* mgf1_t::get_hash_size)(mgf1_t *this)
Get the hash size of the underlying hash function
Returns
hash size in bytes
Definition at line 39 of file mgf1.h.
Referenced by mgf1_bitspender_create(), and START_TEST().
bool(* mgf1_t::get_mask)(mgf1_t *this, size_t mask_len, u_char *mask)
Generate a mask pattern and copy it to an output buffer If the maximum number of requests has been reached, reseeding occurs
Parameters
mask_len number of mask bytes to generate
mask output buffer of minimum size mask_len
Returns
TRUE if successful
Definition at line 49 of file mgf1.h.
Referenced by START_TEST().
The documentation for this struct was generated from the following file:
mgf1.h