strongSwan: eap_simaka_pseudonym_card.c File Reference
eap_simaka_pseudonym_card.c File Reference
#include "eap_simaka_pseudonym_card.h"
#include <daemon.h>
#include <collections/hashtable.h>
Classes
struct private_eap_simaka_pseudonym_card_t
Typedefs
typedef struct
private_eap_simaka_pseudonym_card_t private_eap_simaka_pseudonym_card_t
Functions
static u_int hash (identification_t *key)
static bool equals (identification_t *key1, identification_t *key2)
METHOD (simaka_card_t, get_pseudonym, identification_t *, private_eap_simaka_pseudonym_card_t *this, identification_t *id)
METHOD (simaka_card_t, set_pseudonym, void, private_eap_simaka_pseudonym_card_t *this, identification_t *id, identification_t *pseudonym)
METHOD (simaka_card_t, get_quintuplet, status_t, private_eap_simaka_pseudonym_card_t *this, identification_t *id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int *res_len)
METHOD (eap_simaka_pseudonym_card_t, destroy, void, private_eap_simaka_pseudonym_card_t *this)
eap_simaka_pseudonym_card_t * eap_simaka_pseudonym_card_create ()
Typedef Documentation
typedef struct private_eap_simaka_pseudonym_card_t private_eap_simaka_pseudonym_card_t
Definition at line 21 of file eap_simaka_pseudonym_card.c.
Function Documentation
static bool equals (identification_t * key1, identification_t * key2) static
hashtable equals function
Definition at line 55 of file eap_simaka_pseudonym_card.c.
References identification_t::equals.
Referenced by eap_simaka_pseudonym_card_create().
 {
     return key1->equals(key1, key2);
 }
static u_int hash (identification_t * key) static
hashtable hash function
Definition at line 47 of file eap_simaka_pseudonym_card.c.
References chunk_hash(), and identification_t::get_encoding.
Referenced by eap_simaka_pseudonym_card_create().
 {
     return chunk_hash(key->get_encoding(key));
 }
METHOD (simaka_card_t , get_pseudonym , identification_t * , private_eap_simaka_pseudonym_card_t * this, identification_t * id)
Definition at line 60 of file eap_simaka_pseudonym_card.c.
References identification_t::clone.
 {
     identification_t *pseudonym;
     pseudonym = this->pseudonym->get(this->pseudonym, id);
     if (pseudonym)
     {
         return pseudonym->clone(pseudonym);
     }
     return NULL;
 }
METHOD (simaka_card_t , set_pseudonym , void , private_eap_simaka_pseudonym_card_t * this, identification_t * id, identification_t * pseudonym)
Definition at line 73 of file eap_simaka_pseudonym_card.c.
References identification_t::clone, and DESTROY_IF.
 {
     identification_t *permanent;
     /* create new entries */
     id = id->clone(id);
     pseudonym = pseudonym->clone(pseudonym);
     permanent = this->permanent->put(this->permanent, pseudonym, id);
     pseudonym = this->pseudonym->put(this->pseudonym, id, pseudonym);
     /* delete old entries */
     DESTROY_IF(permanent);
     DESTROY_IF(pseudonym);
 }
METHOD (simaka_card_t , get_quintuplet , status_t , private_eap_simaka_pseudonym_card_t * this, identification_t * id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int * res_len)
Definition at line 90 of file eap_simaka_pseudonym_card.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (eap_simaka_pseudonym_card_t , destroy , void , private_eap_simaka_pseudonym_card_t * this)
Definition at line 98 of file eap_simaka_pseudonym_card.c.
References enumerator_t::destroy, enumerator_t::enumerate, free(), id, and key.
 {
     enumerator_t *enumerator;
     identification_t *id;
     void *key;
     enumerator = this->pseudonym->create_enumerator(this->pseudonym);
     while (enumerator->enumerate(enumerator, &key, &id))
     {
         id->destroy(id);
     }
     enumerator->destroy(enumerator);
     enumerator = this->permanent->create_enumerator(this->permanent);
     while (enumerator->enumerate(enumerator, &key, &id))
     {
         id->destroy(id);
     }
     enumerator->destroy(enumerator);
     this->pseudonym->destroy(this->pseudonym);
     this->permanent->destroy(this->permanent);
     free(this);
 }