strongSwan: proposal_t Struct Reference
proposal_t Struct Reference
proposal
#include "proposal.h"
Public Attributes
void(* add_algorithm)(proposal_t *this, transform_type_t type, u_int16_t alg, u_int16_t key_size)
enumerator_t *(* create_enumerator)(proposal_t *this, transform_type_t type)
bool(* get_algorithm)(proposal_t *this, transform_type_t type, u_int16_t *alg, u_int16_t *key_size)
bool(* has_dh_group)(proposal_t *this, diffie_hellman_group_t group)
void(* strip_dh)(proposal_t *this, diffie_hellman_group_t keep)
proposal_t *(* select)(proposal_t *this, proposal_t *other, bool private)
protocol_id_t(* get_protocol)(proposal_t *this)
u_int64_t(* get_spi)(proposal_t *this)
void(* set_spi)(proposal_t *this, u_int64_t spi)
u_int(* get_number)(proposal_t *this)
bool(* equals)(proposal_t *this, proposal_t *other)
proposal_t *(* clone)(proposal_t *this)
void(* destroy)(proposal_t *this)
Detailed Description
Stores a set of algorithms used for an SA.
A proposal stores algorithms for a specific protocol. It can store algorithms for one protocol. Proposals with multiple protocols are not supported, as it's not specified in RFC4301 anymore.
Definition at line 62 of file proposal.h.
Member Data Documentation
void(* proposal_t::add_algorithm)(proposal_t *this, transform_type_t type, u_int16_t alg, u_int16_t key_size)
Add an algorithm to the proposal.
The algorithms are stored by priority, first added is the most preferred. Key size is only needed for encryption algorithms with variable key size (such as AES). Must be set to zero if key size is not specified. The alg parameter accepts encryption_algorithm_t, integrity_algorithm_t, dh_group_number_t and extended_sequence_numbers_t.
Parameters
type kind of algorithm
alg identifier for algorithm
key_size key size to use
Definition at line 80 of file proposal.h.
Referenced by add_to_proposal_v1(), add_to_proposal_v1_ike(), add_to_proposal_v2(), copy_proposal_algs(), load_proposals(), process_child_add(), process_ike_add(), and select_algo().
proposal_t*(* proposal_t::clone)(proposal_t *this)
Clone a proposal.
Returns
clone of proposal
Definition at line 173 of file proposal.h.
Referenced by METHOD().
enumerator_t*(* proposal_t::create_enumerator)(proposal_t *this, transform_type_t type)
Get an enumerator over algorithms for a specifc algo type.
Parameters
type kind of algorithm
Returns
enumerator over u_int16_t alg, u_int16_t key_size
Definition at line 89 of file proposal.h.
Referenced by algo_list_equals(), copy_proposal_algs(), select_algo(), set_from_proposal_v1(), set_from_proposal_v1_ike(), and set_from_proposal_v2().
void(* proposal_t::destroy)(proposal_t *this)
Destroys the proposal object.
Definition at line 178 of file proposal.h.
Referenced by get_proposals(), METHOD(), process_child_add(), process_ike_add(), and START_TEST().
bool(* proposal_t::equals)(proposal_t *this, proposal_t *other)
Check for the eqality of two proposals.
Parameters
other other proposal to check for equality
Returns
TRUE if other equal to this
Definition at line 166 of file proposal.h.
Referenced by check_for_rekeyed_child(), match_proposal(), and METHOD().
bool(* proposal_t::get_algorithm)(proposal_t *this, transform_type_t type, u_int16_t *alg, u_int16_t *key_size)
Get the algorithm for a type to use.
If there are multiple algorithms, only the first is returned.
Parameters
type kind of algorithm
alg pointer which receives algorithm
key_size pointer which receives the key size
Returns
TRUE if algorithm of this kind available
Definition at line 101 of file proposal.h.
Referenced by create_aead(), list_child(), list_ike(), METHOD(), and select_algo().
u_int(* proposal_t::get_number)(proposal_t *this)
Get the proposal number, as encoded in SA payload
Returns
proposal number
Definition at line 158 of file proposal.h.
Referenced by add_proposal_v2(), METHOD(), and set_data().
protocol_id_t(* proposal_t::get_protocol)(proposal_t *this)
Get the protocol ID of the proposal.
Returns
protocol of the proposal
Definition at line 137 of file proposal.h.
Referenced by allocate_spi(), METHOD(), proposal_substructure_create_from_proposal_v1(), proposal_substructure_create_from_proposals_v1(), and set_data().
u_int64_t(* proposal_t::get_spi)(proposal_t *this)
Get the SPI of the proposal.
Returns
spi for proto
Definition at line 144 of file proposal.h.
Referenced by METHOD(), and set_data().
bool(* proposal_t::has_dh_group)(proposal_t *this, diffie_hellman_group_t group)
Check if the proposal has a specific DH group.
Parameters
group group to check for
Returns
TRUE if algorithm included
Definition at line 110 of file proposal.h.
Referenced by get_proposals().
proposal_t*(* proposal_t::select)(proposal_t *this, proposal_t *other, bool private)
Compare two proposal, and select a matching subset.
If the proposals are for the same protocols (AH/ESP), they are compared. If they have at least one algorithm of each type in common, a resulting proposal of this kind is created.
Parameters
other proposal to compare against
private accepts algorithms allocated in a private range
Returns
selected proposal, NULL if proposals don't match
Definition at line 130 of file proposal.h.
Referenced by METHOD().
void(* proposal_t::set_spi)(proposal_t *this, u_int64_t spi)
Set the SPI of the proposal.
Parameters
spi spi to set for proto
Definition at line 151 of file proposal.h.
Referenced by allocate_spi(), build_payloads(), get_proposals(), load_proposals(), METHOD(), and START_TEST().
void(* proposal_t::strip_dh)(proposal_t *this, diffie_hellman_group_t keep)
Strip DH groups from proposal to use it without PFS.
Parameters
keep group to keep (MODP_NONE to remove all)
Definition at line 117 of file proposal.h.
Referenced by get_proposals(), and METHOD().
The documentation for this struct was generated from the following file:
proposal.h