strongSwan: android_dns_handler.c File Reference
android_dns_handler.c File Reference
#include "android_dns_handler.h"
#include <networking/host.h>
#include <collections/linked_list.h>
#include <cutils/properties.h>
Classes
struct private_android_dns_handler_t
struct dns_pair_t
Macros
#define DNS_PREFIX_DEFAULT "net"
Typedefs
typedef struct
private_android_dns_handler_t private_android_dns_handler_t
Functions
static void destroy_dns_pair (dns_pair_t *this)
static bool filter_dns_pair (void *data, dns_pair_t **in, host_t **out)
static host_t * get_dns_server (private_android_dns_handler_t *this, int index)
static bool set_dns_server (private_android_dns_handler_t *this, int index, host_t *dns)
METHOD (attribute_handler_t, handle, bool, private_android_dns_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (attribute_handler_t, release, void, private_android_dns_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (enumerator_t, enumerate_dns, bool, enumerator_t *this, configuration_attribute_type_t *type, chunk_t *data)
METHOD (attribute_handler_t, create_attribute_enumerator, enumerator_t *, private_android_dns_handler_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (android_dns_handler_t, destroy, void, private_android_dns_handler_t *this)
android_dns_handler_t * android_dns_handler_create ()
Macro Definition Documentation
#define DNS_PREFIX_DEFAULT "net"
Prefix to be used when installing DNS servers
Definition at line 45 of file android_dns_handler.c.
Referenced by get_dns_server(), and set_dns_server().
Typedef Documentation
typedef struct private_android_dns_handler_t private_android_dns_handler_t
Definition at line 24 of file android_dns_handler.c.
Function Documentation
static void destroy_dns_pair (dns_pair_t * this) static
Destroy a pair of old and installed DNS servers
Definition at line 60 of file android_dns_handler.c.
References DESTROY_IF, and free().
Referenced by METHOD().
 {
     DESTROY_IF(this->dns);
     DESTROY_IF(this->old);
     free(this);
 }
static bool filter_dns_pair (void * data, dns_pair_t ** in, host_t ** out) static
Filter pairs of DNS servers
Definition at line 70 of file android_dns_handler.c.
References TRUE.
 {
     *out = (*in)->dns;
     return TRUE;
 }
static host_t* get_dns_server (private_android_dns_handler_t * this, int index) static
Read DNS server property with a given index
Definition at line 79 of file android_dns_handler.c.
References DNS_PREFIX_DEFAULT, host_create_from_string(), key, prefix, snprintf, and value.
Referenced by METHOD().
 {
     host_t *dns = NULL;
     char key[10], value[PROPERTY_VALUE_MAX],
          *prefix = DNS_PREFIX_DEFAULT;
     if (snprintf(key, sizeof(key), "%s.dns%d", prefix, index) >= sizeof(key))
     {
         return NULL;
     }
     if (property_get(key, value, NULL) > 0)
     {
         dns = host_create_from_string(value, 0);
     }
     return dns;
 }
METHOD (attribute_handler_t , handle , bool , private_android_dns_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 130 of file android_dns_handler.c.
References dns_pair_t::dns, FALSE, get_dns_server(), host_create_from_chunk(), INTERNAL_IP4_DNS, malloc_thing, dns_pair_t::old, set_dns_server(), and TRUE.
 {
     switch (type)
     {
         case INTERNAL_IP4_DNS:
         {
             host_t *dns;
             dns_pair_t *pair;
             int index;
             dns = host_create_from_chunk(AF_INET, data, 0);
             if (dns)
             {
                 pair = malloc_thing(dns_pair_t);
                 pair->dns = dns;
                 index = this->dns->get_count(this->dns) + 1;
                 pair->old = get_dns_server(this, index);
                 set_dns_server(this, index, dns);
                 this->dns->insert_last(this->dns, pair);
                 return TRUE;
             }
             return FALSE;
         }
         default:
             return FALSE;
     }
 }
METHOD (attribute_handler_t , release , void , private_android_dns_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 160 of file android_dns_handler.c.
References chunk_equals(), data, enumerator_t::destroy, destroy_dns_pair(), dns_pair_t::dns, enumerator_t::enumerate, host_t::get_address, INTERNAL_IP4_DNS, dns_pair_t::old, and set_dns_server().
 {
     if (type == INTERNAL_IP4_DNS)
     {
         enumerator_t *enumerator;
         dns_pair_t *pair;
         int index;
         enumerator = this->dns->create_enumerator(this->dns);
         for (index = 1; enumerator->enumerate(enumerator, &pair); index++)
         {
             if (chunk_equals(pair->dns->get_address(pair->dns), data))
             {
                 this->dns->remove_at(this->dns, enumerator);
                 set_dns_server(this, index, pair->old);
                 destroy_dns_pair(pair);
             }
         }
         enumerator->destroy(enumerator);
     }
 }
METHOD (enumerator_t , enumerate_dns , bool , enumerator_t * this, configuration_attribute_type_t * type, chunk_t * data)
Definition at line 184 of file android_dns_handler.c.
References chunk_empty, enumerate(), INTERNAL_IP4_DNS, return_false(), and TRUE.
 {
     *type = INTERNAL_IP4_DNS;
     *data = chunk_empty;
     /* stop enumeration */
     this->enumerate = (void*)return_false;
     return TRUE;
 }
METHOD (attribute_handler_t , create_attribute_enumerator , enumerator_t * , private_android_dns_handler_t * this, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 194 of file android_dns_handler.c.
References destroy(), enumerate(), free(), and INIT.
 {
     enumerator_t *enumerator;
     INIT(enumerator,
         .enumerate = (void*)_enumerate_dns,
         .destroy = (void*)free,
     );
     return enumerator;
 }
METHOD (android_dns_handler_t , destroy , void , private_android_dns_handler_t * this)
Definition at line 207 of file android_dns_handler.c.
References destroy_dns_pair(), and free().
 {
     this->dns->destroy_function(this->dns, (void*)destroy_dns_pair);
     free(this);
 }
static bool set_dns_server (private_android_dns_handler_t * this, int index, host_t * dns) static
Set DNS server property with a given index
Definition at line 100 of file android_dns_handler.c.
References DNS_PREFIX_DEFAULT, FALSE, key, prefix, snprintf, TRUE, and value.
Referenced by METHOD().
 {
     char key[10], value[PROPERTY_VALUE_MAX],
          *prefix = DNS_PREFIX_DEFAULT;
     if (snprintf(key, sizeof(key), "%s.dns%d", prefix, index) >= sizeof(key))
     {
         return FALSE;
     }
     if (dns)
     {
         if (snprintf(value, sizeof(value), "%H", dns) >= sizeof(value))
         {
             return FALSE;
         }
     }
     else
     {
         value[0] = '\0';
     }
     if (property_set(key, value) != 0)
     {
         return FALSE;
     }
     return TRUE;
 }