strongSwan: socket_manager.c File Reference
socket_manager.c File Reference
#include "socket_manager.h"
#include <daemon.h>
#include <threading/thread.h>
#include <threading/rwlock.h>
#include <collections/linked_list.h>
Classes
struct private_socket_manager_t
Typedefs
typedef struct
private_socket_manager_t private_socket_manager_t
Functions
METHOD (socket_manager_t, receiver, status_t, private_socket_manager_t *this, packet_t **packet)
METHOD (socket_manager_t, sender, status_t, private_socket_manager_t *this, packet_t *packet)
METHOD (socket_manager_t, get_port, u_int16_t, private_socket_manager_t *this, bool nat_t)
METHOD (socket_manager_t, supported_families, socket_family_t, private_socket_manager_t *this)
static void create_socket (private_socket_manager_t *this)
METHOD (socket_manager_t, add_socket, void, private_socket_manager_t *this, socket_constructor_t create)
METHOD (socket_manager_t, remove_socket, void, private_socket_manager_t *this, socket_constructor_t create)
METHOD (socket_manager_t, destroy, void, private_socket_manager_t *this)
socket_manager_t * socket_manager_create ()
Typedef Documentation
typedef struct private_socket_manager_t private_socket_manager_t
Definition at line 25 of file socket_manager.c.
Function Documentation
static void create_socket (private_socket_manager_t * this) static
Definition at line 118 of file socket_manager.c.
References create, socket, and SUCCESS.
Referenced by METHOD().
 {
     socket_constructor_t create;
     /* remove constructors in order to avoid trying to create broken ones
      * multiple times */
     while (this->sockets->remove_first(this->sockets,
                                        (void**)&create) == SUCCESS)
     {
         this->socket = create();
         if (this->socket)
         {
             this->create = create;
             break;
         }
     }
 }
METHOD (socket_manager_t , receiver , status_t , private_socket_manager_t * this, packet_t ** packet)
Definition at line 58 of file socket_manager.c.
References DBG1, DBG_NET, lock, NOT_SUPPORTED, socket, status, thread_cleanup_pop(), thread_cleanup_push(), TRUE, and spinlock_t::unlock.
 {
     status_t status;
     this->lock->read_lock(this->lock);
     if (!this->socket)
     {
         DBG1(DBG_NET, "no socket implementation registered, receiving failed");
         this->lock->unlock(this->lock);
         return NOT_SUPPORTED;
     }
     /* receive is blocking and the thread can be cancelled */
     thread_cleanup_push((thread_cleanup_t)this->lock->unlock, this->lock);
     status = this->socket->receive(this->socket, packet);
     thread_cleanup_pop(TRUE);
     return status;
 }
METHOD (socket_manager_t , sender , status_t , private_socket_manager_t * this, packet_t * packet)
Definition at line 76 of file socket_manager.c.
References DBG1, DBG_NET, lock, NOT_SUPPORTED, socket, status, and spinlock_t::unlock.
 {
     status_t status;
     this->lock->read_lock(this->lock);
     if (!this->socket)
     {
         DBG1(DBG_NET, "no socket implementation registered, sending failed");
         this->lock->unlock(this->lock);
         return NOT_SUPPORTED;
     }
     status = this->socket->send(this->socket, packet);
     this->lock->unlock(this->lock);
     return status;
 }
METHOD (socket_manager_t , get_port , u_int16_t , private_socket_manager_t * this, bool nat_t)
Definition at line 92 of file socket_manager.c.
References lock, port, socket, and spinlock_t::unlock.
 {
     u_int16_t port = 0;
     this->lock->read_lock(this->lock);
     if (this->socket)
     {
         port = this->socket->get_port(this->socket, nat_t);
     }
     this->lock->unlock(this->lock);
     return port;
 }
METHOD (socket_manager_t , supported_families , socket_family_t , private_socket_manager_t * this)
Definition at line 105 of file socket_manager.c.
References lock, socket, SOCKET_FAMILY_NONE, and spinlock_t::unlock.
 {
     socket_family_t families = SOCKET_FAMILY_NONE;
     this->lock->read_lock(this->lock);
     if (this->socket)
     {
         families = this->socket->supported_families(this->socket);
     }
     this->lock->unlock(this->lock);
     return families;
 }
METHOD (socket_manager_t , add_socket , void , private_socket_manager_t * this, socket_constructor_t create)
Definition at line 135 of file socket_manager.c.
References create_socket(), lock, socket, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->sockets->insert_last(this->sockets, create);
     if (!this->socket)
     {
         create_socket(this);
     }
     this->lock->unlock(this->lock);
 }
METHOD (socket_manager_t , remove_socket , void , private_socket_manager_t * this, socket_constructor_t create)
Definition at line 147 of file socket_manager.c.
References create_socket(), lock, socket, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->sockets->remove(this->sockets, create, NULL);
     if (this->create == create)
     {
         this->socket->destroy(this->socket);
         this->socket = NULL;
         this->create = NULL;
         create_socket(this);
     }
     this->lock->unlock(this->lock);
 }
METHOD (socket_manager_t , destroy , void , private_socket_manager_t * this)
Definition at line 162 of file socket_manager.c.
References spinlock_t::destroy, DESTROY_IF, free(), lock, and socket.
 {
     DESTROY_IF(this->socket);
     this->sockets->destroy(this->sockets);
     this->lock->destroy(this->lock);
     free(this);
 }