strongSwan: eap_radius_plugin
eap_radius_plugin
eap_radius
Classes
struct eap_radius_plugin_t
Typedefs
typedef struct eap_radius_plugin_t eap_radius_plugin_t
Functions
radius_client_t * eap_radius_create_client ()
void eap_radius_handle_timeout (ike_sa_id_t *id)
Detailed Description
Typedef Documentation
typedef struct eap_radius_plugin_t eap_radius_plugin_t
Definition at line 32 of file eap_radius_plugin.h.
Function Documentation
radius_client_t* eap_radius_create_client ()
Get a RADIUS client instance to connect to servers.
Returns
RADIUS client
See header
Definition at line 365 of file eap_radius_plugin.c.
References private_eap_radius_plugin_t::configs, linked_list_t::create_enumerator, DBG2, DBG_CFG, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, radius_config_t::get_name, radius_config_t::get_preference, radius_config_t::get_ref, private_eap_radius_plugin_t::lock, radius_client_create(), random, rwlock_t::read_lock, and rwlock_t::unlock.
Referenced by eap_radius_create(), eap_radius_xauth_create_server(), and send_message().
 {
     if (instance)
     {
         enumerator_t *enumerator;
         radius_config_t *config, *selected = NULL;
         int current, best = -1;
         instance->lock->read_lock(instance->lock);
         enumerator = instance->configs->create_enumerator(instance->configs);
         while (enumerator->enumerate(enumerator, &config))
         {
             current = config->get_preference(config);
             if (current > best ||
                 /* for two with equal preference, 50-50 chance */
                 (current == best && random() % 2 == 0))
             {
                 DBG2(DBG_CFG, "RADIUS server '%s' is candidate: %d",
                      config->get_name(config), current);
                 best = current;
                 DESTROY_IF(selected);
                 selected = config->get_ref(config);
             }
             else
             {
                 DBG2(DBG_CFG, "RADIUS server '%s' skipped: %d",
                      config->get_name(config), current);
             }
         }
         enumerator->destroy(enumerator);
         instance->lock->unlock(instance->lock);
         if (selected)
         {
             return radius_client_create(selected);
         }
     }
     return NULL;
 }
void eap_radius_handle_timeout (ike_sa_id_t * id)
Handle a RADIUS request timeout.
If an IKE_SA is given, it gets deleted (unless the policy says to delete any established IKE_SA).
Parameters
id associated IKE_SA where timeout happened, or NULL
See header.
Definition at line 428 of file eap_radius_plugin.c.
References bus_t::alert, ALERT_RADIUS_NOT_RESPONDING, daemon_t::bus, callback_job_create_with_prio(), charon, DBG1, DBG_CFG, delete_all_async(), delete_ike_sa_job_create(), FALSE, settings_t::get_bool, JOB_PRIO_CRITICAL, lib, library_t::ns, library_t::processor, processor_t::queue_job, return_false(), library_t::settings, and TRUE.
Referenced by METHOD(), send_interim(), send_start(), send_stop(), and verify_radius().
 {
     charon->bus->alert(charon->bus, ALERT_RADIUS_NOT_RESPONDING);
     if (lib->settings->get_bool(lib->settings,
                                 "%s.plugins.eap-radius.close_all_on_timeout",
                                 FALSE, lib->ns))
     {
         DBG1(DBG_CFG, "deleting all IKE_SAs after RADIUS timeout");
         lib->processor->queue_job(lib->processor,
                 (job_t*)callback_job_create_with_prio(
                         (callback_job_cb_t)delete_all_async, NULL, NULL,
                         (callback_job_cancel_t)return_false, JOB_PRIO_CRITICAL));
     }
     else if (id)
     {
         DBG1(DBG_CFG, "deleting IKE_SA after RADIUS timeout");
         lib->processor->queue_job(lib->processor,
                 (job_t*)delete_ike_sa_job_create(id, TRUE));
     }
 }