strongSwan: xcbc.c File Reference
xcbc.c File Reference
#include <string.h>
#include "xcbc.h"
#include <utils/debug.h>
#include <crypto/mac.h>
#include <crypto/prfs/mac_prf.h>
#include <crypto/signers/mac_signer.h>
Classes
struct private_mac_t
Typedefs
typedef struct private_mac_t private_mac_t
Functions
static bool update (private_mac_t *this, chunk_t data)
static bool final (private_mac_t *this, u_int8_t *out)
METHOD (mac_t, get_mac, bool, private_mac_t *this, chunk_t data, u_int8_t *out)
METHOD (mac_t, get_mac_size, size_t, private_mac_t *this)
METHOD (mac_t, set_key, bool, private_mac_t *this, chunk_t key)
METHOD (mac_t, destroy, void, private_mac_t *this)
static mac_t * xcbc_create (encryption_algorithm_t algo, size_t key_size)
prf_t * xcbc_prf_create (pseudo_random_function_t algo)
signer_t * xcbc_signer_create (integrity_algorithm_t algo)
Typedef Documentation
typedef struct private_mac_t private_mac_t
Definition at line 26 of file xcbc.c.
Function Documentation
static bool final (private_mac_t * this, u_int8_t * out) static
run last round, data is in this->e
Definition at line 141 of file xcbc.c.
References b, chunk_alloca, chunk_create(), FALSE, chunk_t::len, memcpy, memset, memxor(), out, chunk_t::ptr, and TRUE.
 {
     chunk_t iv;
     iv = chunk_alloca(this->b);
     memset(iv.ptr, 0, iv.len);
     /* (4) For block M[n]: */
     if (this->remaining_bytes == this->b && !this->zero)
     {
         /* a) If the blocksize of M[n] is 128 bits:
          *    XOR M[n] with E[n-1] and Key K2, then encrypt the result with
          *    Key K1, yielding E[n].
          */
         memxor(this->e, this->remaining, this->b);
         memxor(this->e, this->k2, this->b);
     }
     else
     {
         /* b) If the blocksize of M[n] is less than 128 bits:
          *
          *  i) Pad M[n] with a single "1" bit, followed by the number of
          *     "0" bits (possibly none) required to increase M[n]'s
          *     blocksize to 128 bits.
          */
         if (this->remaining_bytes < this->b)
         {
             this->remaining[this->remaining_bytes] = 0x80;
             while (++this->remaining_bytes < this->b)
             {
                 this->remaining[this->remaining_bytes] = 0x00;
             }
         }
         /*  ii) XOR M[n] with E[n-1] and Key K3, then encrypt the result
          *      with Key K1, yielding E[n].
          */
         memxor(this->e, this->remaining, this->b);
         memxor(this->e, this->k3, this->b);
     }
     if (!this->k1->encrypt(this->k1, chunk_create(this->e, this->b), iv, NULL))
     {
         return FALSE;
     }
     memcpy(out, this->e, this->b);
     /* (2) Define E[0] = 0x00000000000000000000000000000000 */
     memset(this->e, 0, this->b);
     this->remaining_bytes = 0;
     this->zero = TRUE;
     return TRUE;
 }
METHOD (mac_t , get_mac , bool , private_mac_t * this, chunk_t data, u_int8_t * out)
Definition at line 195 of file xcbc.c.
References FALSE, out, TRUE, and update().
 {
     /* update E, do not process last block */
     if (!update(this, data))
     {
         return FALSE;
     }
     if (out)
     {   /* if not in append mode, process last block and output result */
         return final(this, out);
     }
     return TRUE;
 }
METHOD (mac_t , get_mac_size , size_t , private_mac_t * this)
Definition at line 211 of file xcbc.c.
References b.
 {
     return this->b;
 }
METHOD (mac_t , set_key , bool , private_mac_t * this, chunk_t key)
Definition at line 217 of file xcbc.c.
References b, chunk_alloca, chunk_create(), FALSE, key, chunk_t::len, memcpy, memset, memwipe(), chunk_t::ptr, and TRUE.
 {
     chunk_t iv, k1, lengthened;
     memset(this->e, 0, this->b);
     this->remaining_bytes = 0;
     this->zero = TRUE;
     /* we support variable keys from RFC4434 */
     if (key.len == this->b)
     {
         lengthened = key;
     }
     else if (key.len < this->b)
     {   /* pad short keys */
         lengthened = chunk_alloca(this->b);
         memset(lengthened.ptr, 0, lengthened.len);
         memcpy(lengthened.ptr, key.ptr, key.len);
     }
     else
     {   /* shorten key using xcbc */
         lengthened = chunk_alloca(this->b);
         memset(lengthened.ptr, 0, lengthened.len);
         if (!set_key(this, lengthened) ||
             !get_mac(this, key, lengthened.ptr))
         {
             return FALSE;
         }
     }
     k1 = chunk_alloca(this->b);
     iv = chunk_alloca(this->b);
     memset(iv.ptr, 0, iv.len);
     /*
      * (1) Derive 3 128-bit keys (K1, K2 and K3) from the 128-bit secret
      *     key K, as follows:
      *     K1 = 0x01010101010101010101010101010101 encrypted with Key K
      *     K2 = 0x02020202020202020202020202020202 encrypted with Key K
      *     K3 = 0x03030303030303030303030303030303 encrypted with Key K
      */
     memset(k1.ptr, 0x01, this->b);
     memset(this->k2, 0x02, this->b);
     memset(this->k3, 0x03, this->b);
     if (!this->k1->set_key(this->k1, lengthened) ||
         !this->k1->encrypt(this->k1, chunk_create(this->k2, this->b), iv, NULL) ||
         !this->k1->encrypt(this->k1, chunk_create(this->k3, this->b), iv, NULL) ||
         !this->k1->encrypt(this->k1, k1, iv, NULL) ||
         !this->k1->set_key(this->k1, k1))
     {
         memwipe(k1.ptr, k1.len);
         return FALSE;
     }
     memwipe(k1.ptr, k1.len);
     return TRUE;
 }
METHOD (mac_t , destroy , void , private_mac_t * this)
Definition at line 277 of file xcbc.c.
References b, free(), and memwipe().
 {
     this->k1->destroy(this->k1);
     memwipe(this->k2, this->b);
     free(this->k2);
     memwipe(this->k3, this->b);
     free(this->k3);
     free(this->e);
     free(this->remaining);
     free(this);
 }
static bool update (private_mac_t * this, chunk_t data) static
xcbc supplied data, but do not run final operation
Definition at line 84 of file xcbc.c.
References b, chunk_alloca, chunk_create(), chunk_skip(), FALSE, chunk_t::len, memcpy, memset, memxor(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     chunk_t iv;
     if (data.len)
     {
         this->zero = FALSE;
     }
     if (this->remaining_bytes + data.len <= this->b)
     {   /* no complete block, just copy into remaining */
         memcpy(this->remaining + this->remaining_bytes, data.ptr, data.len);
         this->remaining_bytes += data.len;
         return TRUE;
     }
     iv = chunk_alloca(this->b);
     memset(iv.ptr, 0, iv.len);
     /* (3) For each block M[i], where i = 1 ... n-1:
      *     XOR M[i] with E[i-1], then encrypt the result with Key K1,
      *     yielding E[i].
      */
     /* append data to remaining bytes, process block M[1] */
     memcpy(this->remaining + this->remaining_bytes, data.ptr,
            this->b - this->remaining_bytes);
     data = chunk_skip(data, this->b - this->remaining_bytes);
     memxor(this->e, this->remaining, this->b);
     if (!this->k1->encrypt(this->k1, chunk_create(this->e, this->b), iv, NULL))
     {
         return FALSE;
     }
     /* process blocks M[2] ... M[n-1] */
     while (data.len > this->b)
     {
         memcpy(this->remaining, data.ptr, this->b);
         data = chunk_skip(data, this->b);
         memxor(this->e, this->remaining, this->b);
         if (!this->k1->encrypt(this->k1, chunk_create(this->e, this->b),
                                iv, NULL))
         {
             return FALSE;
         }
     }
     /* store remaining bytes of block M[n] */
     memcpy(this->remaining, data.ptr, data.len);
     this->remaining_bytes = data.len;
     return TRUE;
 }
static mac_t* xcbc_create (encryption_algorithm_t algo, size_t key_size) static
Definition at line 293 of file xcbc.c.
References b, crypto_factory_t::create_crypter, crypter, library_t::crypto, crypter_t::destroy, crypter_t::get_block_size, INIT, lib, malloc(), memset, and TRUE.
Referenced by xcbc_prf_create(), and xcbc_signer_create().
 {
     private_mac_t *this;
     crypter_t *crypter;
     u_int8_t b;
     crypter = lib->crypto->create_crypter(lib->crypto, algo, key_size);
     if (!crypter)
     {
         return NULL;
     }
     b = crypter->get_block_size(crypter);
     /* input and output of crypter must be equal for xcbc */
     if (b != key_size)
     {
         crypter->destroy(crypter);
         return NULL;
     }
     INIT(this,
         .public = {
             .get_mac = _get_mac,
             .get_mac_size = _get_mac_size,
             .set_key = _set_key,
             .destroy = _destroy,
         },
         .b = b,
         .k1 = crypter,
         .k2 = malloc(b),
         .k3 = malloc(b),
         .e = malloc(b),
         .remaining = malloc(b),
         .zero = TRUE,
     );
     memset(this->e, 0, b);
     return &this->public;
 }