strongSwan: sa_payload.c File Reference
sa_payload.c File Reference
#include <stddef.h>
#include "sa_payload.h"
#include <encoding/payloads/encodings.h>
#include <collections/linked_list.h>
#include <daemon.h>
Classes
struct private_sa_payload_t
Macros
#define SIT_IDENTITY_ONLY 1
Typedefs
typedef struct private_sa_payload_t private_sa_payload_t
Functions
METHOD (payload_t, verify, status_t, private_sa_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_sa_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_sa_payload_t *this)
METHOD (payload_t, get_type, payload_type_t, private_sa_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_sa_payload_t *this)
METHOD (payload_t, set_next_type, void, private_sa_payload_t *this, payload_type_t type)
static void compute_length (private_sa_payload_t *this)
METHOD (payload_t, get_length, size_t, private_sa_payload_t *this)
static void add_proposal_v2 (private_sa_payload_t *this, proposal_t *proposal)
METHOD (sa_payload_t, get_proposals, linked_list_t *, private_sa_payload_t *this)
METHOD (sa_payload_t, get_ipcomp_proposals, linked_list_t *, private_sa_payload_t *this, u_int16_t *cpi)
METHOD (sa_payload_t, create_substructure_enumerator, enumerator_t *, private_sa_payload_t *this)
METHOD (sa_payload_t, get_lifetime, u_int32_t, private_sa_payload_t *this)
METHOD (sa_payload_t, get_lifebytes, u_int64_t, private_sa_payload_t *this)
METHOD (sa_payload_t, get_auth_method, auth_method_t, private_sa_payload_t *this)
METHOD (sa_payload_t, get_encap_mode, ipsec_mode_t, private_sa_payload_t *this, bool *udp)
METHOD2 (payload_t, sa_payload_t, destroy, void, private_sa_payload_t *this)
sa_payload_t * sa_payload_create (payload_type_t type)
sa_payload_t * sa_payload_create_from_proposals_v2 (linked_list_t *proposals)
sa_payload_t * sa_payload_create_from_proposal_v2 (proposal_t *proposal)
sa_payload_t * sa_payload_create_from_proposals_v1 (linked_list_t *proposals, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp, u_int16_t cpi)
sa_payload_t * sa_payload_create_from_proposal_v1 (proposal_t *proposal, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp, u_int16_t cpi)
Variables
static encoding_rule_t encodings_v1 []
static encoding_rule_t encodings_v2 []
Macro Definition Documentation
#define SIT_IDENTITY_ONLY 1
Definition at line 27 of file sa_payload.c.
Referenced by sa_payload_create().
Typedef Documentation
typedef struct private_sa_payload_t private_sa_payload_t
Definition at line 29 of file sa_payload.c.
Function Documentation
static void add_proposal_v2 (private_sa_payload_t * this, proposal_t * proposal) static
Create a transform substructure from a proposal, add to payload
Definition at line 263 of file sa_payload.c.
References compute_length(), count, FALSE, proposal_t::get_number, proposal_substructure_create_from_proposal_v2(), proposal_substructure_t::set_is_last_proposal, proposal_substructure_t::set_proposal_number, and TRUE.
Referenced by sa_payload_create_from_proposal_v2(), and sa_payload_create_from_proposals_v2().
 {
     proposal_substructure_t *substruct, *last;
     u_int count;
     substruct = proposal_substructure_create_from_proposal_v2(proposal);
     count = this->proposals->get_count(this->proposals);
     if (count > 0)
     {
         this->proposals->get_last(this->proposals, (void**)&last);
         /* last transform is now not anymore last one */
         last->set_is_last_proposal(last, FALSE);
     }
     substruct->set_is_last_proposal(substruct, TRUE);
     if (proposal->get_number(proposal))
     {   /* use the selected proposals number, if any */
         substruct->set_proposal_number(substruct, proposal->get_number(proposal));
     }
     else
     {
         substruct->set_proposal_number(substruct, count + 1);
     }
     this->proposals->insert_last(this->proposals, substruct);
     compute_length(this);
 }
static void compute_length (private_sa_payload_t * this) static
recompute length of the payload.
Definition at line 239 of file sa_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, and payload_t::get_length.
Referenced by add_proposal_v2(), sa_payload_create(), and sa_payload_create_from_proposals_v1().
 {
     enumerator_t *enumerator;
     payload_t *current;
     this->payload_length = get_header_length(this);
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, (void **)&current))
     {
         this->payload_length += current->get_length(current);
     }
     enumerator->destroy(enumerator);
 }
METHOD (payload_t , verify , status_t , private_sa_payload_t * this)
Definition at line 159 of file sa_payload.c.
References DBG1, DBG_ENC, enumerator_t::destroy, enumerator_t::enumerate, FAILED, proposal_substructure_t::get_proposal_number, proposal_substructure_t::payload_interface, PLV2_SECURITY_ASSOCIATION, status, SUCCESS, type, and payload_t::verify.
 {
     int expected_number = 0, current_number;
     status_t status = SUCCESS;
     enumerator_t *enumerator;
     proposal_substructure_t *substruct;
     if (this->type == PLV2_SECURITY_ASSOCIATION)
     {
         expected_number = 1;
     }
     /* check proposal numbering */
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, (void**)&substruct))
     {
         current_number = substruct->get_proposal_number(substruct);
         if (current_number < expected_number)
         {
             DBG1(DBG_ENC, "proposal number smaller than previous");
             status = FAILED;
             break;
         }
         status = substruct->payload_interface.verify(&substruct->payload_interface);
         if (status != SUCCESS)
         {
             DBG1(DBG_ENC, "PROPOSAL_SUBSTRUCTURE verification failed");
             break;
         }
         expected_number = current_number;
     }
     enumerator->destroy(enumerator);
     return status;
 }
METHOD (payload_t , get_encoding_rules , int , private_sa_payload_t * this, encoding_rule_t ** rules)
Definition at line 196 of file sa_payload.c.
References countof, encodings_v1, encodings_v2, PLV1_SECURITY_ASSOCIATION, and type.
 {
     if (this->type == PLV1_SECURITY_ASSOCIATION)
     {
         *rules = encodings_v1;
         return countof(encodings_v1);
     }
     *rules = encodings_v2;
     return countof(encodings_v2);
 }
METHOD (payload_t , get_header_length , int , private_sa_payload_t * this)
Definition at line 208 of file sa_payload.c.
References PLV1_SECURITY_ASSOCIATION, and type.
 {
     if (this->type == PLV1_SECURITY_ASSOCIATION)
     {
         return 12;
     }
     return 4;
 }
METHOD (payload_t , get_type , payload_type_t , private_sa_payload_t * this)
Definition at line 218 of file sa_payload.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_sa_payload_t * this)
Definition at line 224 of file sa_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_sa_payload_t * this, payload_type_t type)
Definition at line 230 of file sa_payload.c.
References type.
 {
     this->next_payload = type;
 }
METHOD (payload_t , get_length , size_t , private_sa_payload_t * this)
Definition at line 254 of file sa_payload.c.
 {
     return this->payload_length;
 }
METHOD (sa_payload_t , get_proposals , linked_list_t * , private_sa_payload_t * this)
Definition at line 289 of file sa_payload.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, proposal_substructure_t::get_proposal_number, proposal_substructure_t::get_proposals, linked_list_t::insert_last, linked_list_create(), list, PLV1_SECURITY_ASSOCIATION, linked_list_t::remove_last, and type.
 {
     int struct_number = 0;
     int ignore_struct_number = 0;
     enumerator_t *enumerator;
     proposal_substructure_t *substruct;
     linked_list_t *substructs, *list;
     if (this->type == PLV1_SECURITY_ASSOCIATION)
     {   /* IKEv1 proposals may start with 0 or 1 (or any other number really) */
         struct_number = ignore_struct_number = -1;
     }
     /* we do not support proposals split up to two proposal substructures, as
      * AH+ESP bundles are not supported in RFC4301 anymore.
      * To handle such structures safely, we just skip proposals with multiple
      * protocols.
      */
     substructs = linked_list_create();
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, &substruct))
     {
         int current_number = substruct->get_proposal_number(substruct);
         /* check if a proposal has a single protocol */
         if (current_number == struct_number)
         {
             if (ignore_struct_number < struct_number)
             {   /* remove an already added substruct, if first of series */
                 substructs->remove_last(substructs, (void**)&substruct);
                 ignore_struct_number = struct_number;
             }
             continue;
         }
         /* for IKEv1 the numbers don't have to be consecutive, for IKEv2 they do
          * but since we don't really care for the actual number we accept them
          * anyway. we already verified that they increase monotonically. */
         struct_number = current_number;
         substructs->insert_last(substructs, substruct);
     }
     enumerator->destroy(enumerator);
     /* generate proposals from substructs */
     list = linked_list_create();
     enumerator = substructs->create_enumerator(substructs);
     while (enumerator->enumerate(enumerator, &substruct))
     {
         substruct->get_proposals(substruct, list);
     }
     enumerator->destroy(enumerator);
     substructs->destroy(substructs);
     return list;
 }
METHOD (sa_payload_t , get_ipcomp_proposals , linked_list_t * , private_sa_payload_t * this, u_int16_t * cpi)
Definition at line 344 of file sa_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, proposal_substructure_t::get_cpi, proposal_substructure_t::get_proposal_number, proposal_substructure_t::get_proposals, proposal_substructure_t::get_protocol_id, linked_list_create(), list, PROTO_AH, PROTO_ESP, and PROTO_IPCOMP.
 {
     int current_proposal = -1, unsupported_proposal = -1;
     enumerator_t *enumerator;
     proposal_substructure_t *substruct, *espah = NULL, *ipcomp = NULL;
     linked_list_t *list;
     /* we currently only support the combination ESP|AH+IPComp, find the first */
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, &substruct))
     {
         u_int8_t proposal_number = substruct->get_proposal_number(substruct);
         u_int8_t protocol_id = substruct->get_protocol_id(substruct);
         if (proposal_number == unsupported_proposal)
         {
             continue;
         }
         if (protocol_id != PROTO_ESP && protocol_id != PROTO_AH &&
             protocol_id != PROTO_IPCOMP)
         {   /* unsupported combination */
             espah = ipcomp = NULL;
             unsupported_proposal = current_proposal;
             continue;
         }
         if (proposal_number != current_proposal)
         {   /* start of a new proposal */
             if (espah && ipcomp && ipcomp->get_cpi(ipcomp, NULL))
             {   /* previous proposal is valid */
                 break;
             }
             espah = ipcomp = NULL;
             current_proposal = proposal_number;
         }
         switch (protocol_id)
         {
             case PROTO_ESP:
             case PROTO_AH:
                 espah = substruct;
                 break;
             case PROTO_IPCOMP:
                 ipcomp = substruct;
                 break;
         }
     }
     enumerator->destroy(enumerator);
     list = linked_list_create();
     if (espah && ipcomp && ipcomp->get_cpi(ipcomp, cpi))
     {
         espah->get_proposals(espah, list);
     }
     return list;
 }
METHOD (sa_payload_t , create_substructure_enumerator , enumerator_t * , private_sa_payload_t * this)
Definition at line 400 of file sa_payload.c.
 {
     return this->proposals->create_enumerator(this->proposals);
 }
METHOD (sa_payload_t , get_lifetime , u_int32_t , private_sa_payload_t * this)
Definition at line 406 of file sa_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, and proposal_substructure_t::get_lifetime.
 {
     proposal_substructure_t *substruct;
     enumerator_t *enumerator;
     u_int32_t lifetime = 0;
     enumerator = this->proposals->create_enumerator(this->proposals);
     if (enumerator->enumerate(enumerator, &substruct))
     {
         lifetime = substruct->get_lifetime(substruct);
     }
     enumerator->destroy(enumerator);
     return lifetime;
 }
METHOD (sa_payload_t , get_lifebytes , u_int64_t , private_sa_payload_t * this)
Definition at line 423 of file sa_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, and proposal_substructure_t::get_lifebytes.
 {
     proposal_substructure_t *substruct;
     enumerator_t *enumerator;
     u_int64_t lifebytes = 0;
     enumerator = this->proposals->create_enumerator(this->proposals);
     if (enumerator->enumerate(enumerator, &substruct))
     {
         lifebytes = substruct->get_lifebytes(substruct);
     }
     enumerator->destroy(enumerator);
     return lifebytes;
 }
METHOD (sa_payload_t , get_auth_method , auth_method_t , private_sa_payload_t * this)
Definition at line 440 of file sa_payload.c.
References AUTH_NONE, enumerator_t::destroy, enumerator_t::enumerate, and proposal_substructure_t::get_auth_method.
 {
     proposal_substructure_t *substruct;
     enumerator_t *enumerator;
     auth_method_t method = AUTH_NONE;
     enumerator = this->proposals->create_enumerator(this->proposals);
     if (enumerator->enumerate(enumerator, &substruct))
     {
         method = substruct->get_auth_method(substruct);
     }
     enumerator->destroy(enumerator);
     return method;
 }
METHOD (sa_payload_t , get_encap_mode , ipsec_mode_t , private_sa_payload_t * this, bool * udp)
Definition at line 457 of file sa_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, proposal_substructure_t::get_encap_mode, and MODE_NONE.
 {
     proposal_substructure_t *substruct;
     enumerator_t *enumerator;
     ipsec_mode_t mode = MODE_NONE;
     enumerator = this->proposals->create_enumerator(this->proposals);
     if (enumerator->enumerate(enumerator, &substruct))
     {
         mode = substruct->get_encap_mode(substruct, udp);
     }
     enumerator->destroy(enumerator);
     return mode;
 }
METHOD2 (payload_t , sa_payload_t , destroy , void , private_sa_payload_t * this)
Definition at line 474 of file sa_payload.c.
References destroy(), and free().
 {
     this->proposals->destroy_offset(this->proposals,
                                     offsetof(payload_t, destroy));
     free(this);
 }
Variable Documentation
encoding_rule_t encodings_v1[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_sa_payload_t, next_payload)    },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[0])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[1])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[2])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[3])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[4])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[5])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[6])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[7])         },
    { PAYLOAD_LENGTH,   offsetof(private_sa_payload_t, payload_length)  },
    { U_INT_32,         offsetof(private_sa_payload_t, doi)             },
    { U_INT_32,         offsetof(private_sa_payload_t, situation)       },
    { PAYLOAD_LIST + PLV1_PROPOSAL_SUBSTRUCTURE,
                        offsetof(private_sa_payload_t, proposals)       },
}
Encoding rules for IKEv1 SA payload
Definition at line 85 of file sa_payload.c.
Referenced by METHOD().
encoding_rule_t encodings_v2[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_sa_payload_t, next_payload)        },
    { FLAG,             offsetof(private_sa_payload_t, critical)            },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[0])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[1])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[2])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[3])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[4])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[5])         },
    { RESERVED_BIT,     offsetof(private_sa_payload_t, reserved[6])         },
    { PAYLOAD_LENGTH,   offsetof(private_sa_payload_t, payload_length)      },
    { PAYLOAD_LIST + PLV2_PROPOSAL_SUBSTRUCTURE,
                        offsetof(private_sa_payload_t, proposals)           },
}
Encoding rules for IKEv2 SA payload
Definition at line 127 of file sa_payload.c.
Referenced by METHOD().