strongSwan: simaka_manager_t Struct Reference
simaka_manager_t Struct Reference
simaka_manager
#include "simaka_manager.h"
Public Attributes
void(* add_card)(simaka_manager_t *this, simaka_card_t *card)
void(* remove_card)(simaka_manager_t *this, simaka_card_t *card)
bool(* card_get_triplet)(simaka_manager_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
status_t(* card_get_quintuplet)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int *res_len)
bool(* card_resync)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
void(* card_set_pseudonym)(simaka_manager_t *this, identification_t *id, identification_t *pseudonym)
identification_t *(* card_get_pseudonym)(simaka_manager_t *this, identification_t *id)
void(* card_set_reauth)(simaka_manager_t *this, identification_t *id, identification_t *next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
identification_t *(* card_get_reauth)(simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
void(* add_provider)(simaka_manager_t *this, simaka_provider_t *provider)
void(* remove_provider)(simaka_manager_t *this, simaka_provider_t *provider)
bool(* provider_get_triplet)(simaka_manager_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
bool(* provider_get_quintuplet)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int *xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
bool(* provider_resync)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
identification_t *(* provider_is_pseudonym)(simaka_manager_t *this, identification_t *id)
identification_t *(* provider_gen_pseudonym)(simaka_manager_t *this, identification_t *id)
identification_t *(* provider_is_reauth)(simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
identification_t *(* provider_gen_reauth)(simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1])
void(* add_hooks)(simaka_manager_t *this, simaka_hooks_t *hooks)
void(* remove_hooks)(simaka_manager_t *this, simaka_hooks_t *hooks)
void(* message_hook)(simaka_manager_t *this, simaka_message_t *message, bool inbound, bool decrypted)
void(* key_hook)(simaka_manager_t *this, chunk_t k_encr, chunk_t k_auth)
void(* destroy)(simaka_manager_t *this)
Detailed Description
The SIM manager handles multiple (U)SIM cards/providers and hooks.
Definition at line 49 of file simaka_manager.h.
Member Data Documentation
void(* simaka_manager_t::add_card)(simaka_manager_t *this, simaka_card_t *card)
Register a SIM card (client) at the manager.
Parameters
card sim card to register
Definition at line 56 of file simaka_manager.h.
Referenced by register_card().
void(* simaka_manager_t::add_hooks)(simaka_manager_t *this, simaka_hooks_t *hooks)
Register a set of hooks to the manager.
Parameters
hooks hook interface implementation to register
Definition at line 248 of file simaka_manager.h.
void(* simaka_manager_t::add_provider)(simaka_manager_t *this, simaka_provider_t *provider)
Register a triplet provider (server) at the manager.
Parameters
card sim card to register
Definition at line 153 of file simaka_manager.h.
Referenced by register_provider().
identification_t*(* simaka_manager_t::card_get_pseudonym)(simaka_manager_t *this, identification_t *id)
Get a stored pseudonym from one of the registered SIM cards.
Parameters
id permanent identity of the peer
Returns
associated pseudonym identity, NULL if none found
Definition at line 121 of file simaka_manager.h.
status_t(* simaka_manager_t::card_get_quintuplet)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int *res_len)
Calculate AKA quitpulets on one of the registered SIM cards.
Parameters
id permanent identity to request quintuplet for
rand random value rand
autn authentication token autn
ck buffer receiving encryption key ck
ik buffer receiving integrity key ik
res buffer receiving authentication result res
res_len nubmer of bytes written to res buffer
Returns
SUCCESS, FAILED, or INVALID_STATE if out of sync
Definition at line 90 of file simaka_manager.h.
identification_t*(* simaka_manager_t::card_get_reauth)(simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
Retrieve fast reauthentication parameters from one of the registered cards.
Parameters
id permanent identity of the peer
mk buffer receiving master key MK
counter pointer receiving counter value, in host order
Returns
fast reauthentication identity, NULL if none found
Definition at line 144 of file simaka_manager.h.
bool(* simaka_manager_t::card_get_triplet)(simaka_manager_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
Calculate SIM triplets on one of the registered SIM cards.
Parameters
id permanent identity to get a triplet for
rand RAND input buffer, fixed size 16 bytes
sres SRES output buffer, fixed size 4 byte
kc KC output buffer, fixed size 8 bytes
Returns
TRUE if calculated, FALSE if no matching card found
Definition at line 74 of file simaka_manager.h.
bool(* simaka_manager_t::card_resync)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
Calculate resynchronization data on one of the registered SIM cards.
Parameters
id permanent identity to request quintuplet for
rand random value rand
auts resynchronization parameter auts
Returns
TRUE if calculated, FALSE if no matcing card found
Definition at line 103 of file simaka_manager.h.
void(* simaka_manager_t::card_set_pseudonym)(simaka_manager_t *this, identification_t *id, identification_t *pseudonym)
Store a received pseudonym on one of the registered SIM cards.
Parameters
id permanent identity of the peer
pseudonym pseudonym identity received from the server
Definition at line 112 of file simaka_manager.h.
void(* simaka_manager_t::card_set_reauth)(simaka_manager_t *this, identification_t *id, identification_t *next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
Store fast reauthentication parameters on one of the registered cards.
Parameters
id permanent identity of the peer
next next fast reauthentication identity to use
mk master key MK to store for reauthentication
counter counter value to store, host order
Definition at line 132 of file simaka_manager.h.
void(* simaka_manager_t::destroy)(simaka_manager_t *this)
Destroy a manager instance.
Definition at line 278 of file simaka_manager.h.
void(* simaka_manager_t::key_hook)(simaka_manager_t *this, chunk_t k_encr, chunk_t k_auth)
Invoke SIM/AKA key hook.
Parameters
k_encr SIM/AKA encryption key k_encr
k_auth SIM/AKA authentication key k_auth
Definition at line 273 of file simaka_manager.h.
Referenced by call_hook().
void(* simaka_manager_t::message_hook)(simaka_manager_t *this, simaka_message_t *message, bool inbound, bool decrypted)
Invoke SIM/AKA message hook.
Parameters
message SIM message
inbound TRUE for incoming messages, FALSE for outgoing
decrypted TRUE if AT_ENCR_DATA has been decrypted
Definition at line 264 of file simaka_manager.h.
identification_t*(* simaka_manager_t::provider_gen_pseudonym)(simaka_manager_t *this, identification_t *id)
Generate a new pseudonym using one of the registered providers.
Parameters
id permanent identity to generate a pseudonym for
Returns
generated pseudonym, NULL to not use a pseudonym identity
Definition at line 218 of file simaka_manager.h.
identification_t*(* simaka_manager_t::provider_gen_reauth)(simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1])
Generate a fast reauth id using one of the registered providers.
Parameters
id permanent peer identity
mk master key to store along with generated identity
Returns
fast reauthentication identity, NULL to not use reauth
Definition at line 240 of file simaka_manager.h.
bool(* simaka_manager_t::provider_get_quintuplet)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int *xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
Get a AKA quintuplet from one of the registered providers.
Parameters
id permanent identity of peer to create challenge for
rand buffer receiving random value rand
xres buffer receiving expected authentication result xres
ck buffer receiving encryption key ck
ik buffer receiving integrity key ik
autn authentication token autn
Returns
TRUE if quintuplet received, FALSE if no match found
Definition at line 186 of file simaka_manager.h.
bool(* simaka_manager_t::provider_get_triplet)(simaka_manager_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
Get a SIM triplet from one of the registered providers.
Parameters
id permanent identity of peer to gen triplet for
rand RAND output buffer, fixed size 16 bytes
sres SRES output buffer, fixed size 4 byte
kc KC output buffer, fixed size 8 bytes
Returns
TRUE if triplet received, FALSE if no match found
Definition at line 171 of file simaka_manager.h.
identification_t*(* simaka_manager_t::provider_is_pseudonym)(simaka_manager_t *this, identification_t *id)
Check if a peer uses a pseudonym using one of the registered providers.
Parameters
id pseudonym identity candidate
Returns
permanent identity, NULL if id not a pseudonym
Definition at line 209 of file simaka_manager.h.
identification_t*(* simaka_manager_t::provider_is_reauth)(simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
Check if a peer uses a reauth id using one of the registered providers.
Parameters
id reauthentication identity (candidate)
mk buffer receiving master key MK
counter pointer receiving current counter value, host order
Returns
permanent identity, NULL if not a known reauth identity
Definition at line 229 of file simaka_manager.h.
bool(* simaka_manager_t::provider_resync)(simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
Pass AKA resynchronization data to one of the registered providers.
Parameters
id permanent identity of peer requesting resynchronisation
rand random value rand
auts synchronization parameter auts
Returns
TRUE if resynchronized, FALSE if not handled
Definition at line 200 of file simaka_manager.h.
void(* simaka_manager_t::remove_card)(simaka_manager_t *this, simaka_card_t *card)
Unregister a previously registered card from the manager.
Parameters
card sim card to unregister
Definition at line 63 of file simaka_manager.h.
Referenced by register_card().
void(* simaka_manager_t::remove_hooks)(simaka_manager_t *this, simaka_hooks_t *hooks)
Unregister a set of hooks from the manager.
Parameters
hooks hook interface implementation to unregister
Definition at line 255 of file simaka_manager.h.
void(* simaka_manager_t::remove_provider)(simaka_manager_t *this, simaka_provider_t *provider)
Unregister a previously registered provider from the manager.
Parameters
card sim card to unregister
Definition at line 160 of file simaka_manager.h.
Referenced by register_provider().
The documentation for this struct was generated from the following file:
simaka_manager.h