strongSwan: tcg_swid_attr_req
tcg_swid_attr_req
tcg_attr
Classes
struct tcg_swid_attr_req_t
Macros
#define TCG_SWID_REQ_MIN_SIZE 12
Typedefs
typedef struct tcg_swid_attr_req_t tcg_swid_attr_req_t
typedef enum
tcg_swid_attr_req_flag_t tcg_swid_attr_req_flag_t
Enumerations
enum tcg_swid_attr_req_flag_t { TCG_SWID_ATTR_REQ_FLAG_NONE = 0, TCG_SWID_ATTR_REQ_FLAG_R = (1 << 7), TCG_SWID_ATTR_REQ_FLAG_S = (1 << 6), TCG_SWID_ATTR_REQ_FLAG_C = (1 << 5) }
Functions
pa_tnc_attr_t * tcg_swid_attr_req_create (u_int8_t flags, u_int32_t request_id, u_int32_t eid)
pa_tnc_attr_t * tcg_swid_attr_req_create_from_data (size_t length, chunk_t value)
Detailed Description
Macro Definition Documentation
#define TCG_SWID_REQ_MIN_SIZE 12
Definition at line 24 of file tcg_swid_attr_req.h.
Referenced by METHOD().
Typedef Documentation
typedef enum tcg_swid_attr_req_flag_t tcg_swid_attr_req_flag_t
Definition at line 27 of file tcg_swid_attr_req.h.
typedef struct tcg_swid_attr_req_t tcg_swid_attr_req_t
Definition at line 26 of file tcg_swid_attr_req.h.
Enumeration Type Documentation
enum tcg_swid_attr_req_flag_t
Enumerator
TCG_SWID_ATTR_REQ_FLAG_NONE
TCG_SWID_ATTR_REQ_FLAG_R
TCG_SWID_ATTR_REQ_FLAG_S
TCG_SWID_ATTR_REQ_FLAG_C
Definition at line 29 of file tcg_swid_attr_req.h.
{
     TCG_SWID_ATTR_REQ_FLAG_NONE = 0,
     TCG_SWID_ATTR_REQ_FLAG_R =   (1 << 7),
     TCG_SWID_ATTR_REQ_FLAG_S =   (1 << 6),
     TCG_SWID_ATTR_REQ_FLAG_C =   (1 << 5)
 };
Function Documentation
pa_tnc_attr_t* tcg_swid_attr_req_create (u_int8_t flags, u_int32_t request_id, u_int32_t eid)
Creates an tcg_swid_attr_req_t object
Parameters
flags Sets the C|S|R flags
request_id Request ID
eid Earliest Event ID
Described in header.
Definition at line 280 of file tcg_swid_attr_req.c.
References FALSE, INIT, PEN_TCG, swid_inventory_create(), SWID_REQ_RESERVED_MASK, and TCG_SWID_REQUEST.
Referenced by METHOD().
 {
     private_tcg_swid_attr_req_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_flags = _get_flags,
             .get_request_id = _get_request_id,
             .get_earliest_eid = _get_earliest_eid,
             .add_target = _add_target,
             .get_targets = _get_targets,
         },
         .type = { PEN_TCG, TCG_SWID_REQUEST },
         .flags = flags & SWID_REQ_RESERVED_MASK,
         .request_id = request_id,
         .earliest_eid = eid,
         .targets = swid_inventory_create(FALSE),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* tcg_swid_attr_req_create_from_data (size_t length, chunk_t data)
Creates an tcg_swid_attr_req_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 318 of file tcg_swid_attr_req.c.
References chunk_clone, FALSE, INIT, length, PEN_TCG, swid_inventory_create(), and TCG_SWID_REQUEST.
Referenced by tcg_attr_create_from_data().
 {
     private_tcg_swid_attr_req_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_flags = _get_flags,
             .get_request_id = _get_request_id,
             .get_earliest_eid = _get_earliest_eid,
             .add_target = _add_target,
             .get_targets = _get_targets,
         },
         .type = { PEN_TCG, TCG_SWID_REQUEST },
         .length = length,
         .value = chunk_clone(data),
         .targets = swid_inventory_create(FALSE),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }