strongSwan: tun_device_t Struct Reference
tun_device_t Struct Reference
tun_device
#include "tun_device.h"
Public Attributes
bool(* read_packet)(tun_device_t *this, chunk_t *packet)
bool(* write_packet)(tun_device_t *this, chunk_t packet)
bool(* set_address)(tun_device_t *this, host_t *addr, u_int8_t netmask)
host_t *(* get_address)(tun_device_t *this, u_int8_t *netmask)
bool(* up)(tun_device_t *this)
bool(* set_mtu)(tun_device_t *this, int mtu)
int(* get_mtu)(tun_device_t *this)
char *(* get_name)(tun_device_t *this)
int(* get_fd)(tun_device_t *this)
void(* destroy)(tun_device_t *this)
Detailed Description
Class to create TUN devices
Creating such a device requires the CAP_NET_ADMIN capability.
Definition at line 35 of file tun_device.h.
Member Data Documentation
void(* tun_device_t::destroy)(tun_device_t *this)
Destroy a tun_device_t
Definition at line 112 of file tun_device.h.
Referenced by METHOD(), and nm_strongswan_plugin_dispose().
host_t*(* tun_device_t::get_address)(tun_device_t *this, u_int8_t *netmask)
Get the IP address previously assigned to using set_address().
Parameters
netmask pointer receiving the configured netmask, or NULL
Returns
address previously set, NULL if none
Definition at line 71 of file tun_device.h.
Referenced by METHOD().
int(* tun_device_t::get_fd)(tun_device_t *this)
Get the underlying tun file descriptor.
Returns
file descriptor of this tun device
Definition at line 107 of file tun_device.h.
Referenced by METHOD().
int(* tun_device_t::get_mtu)(tun_device_t *this)
Get the current MTU for this TUN device
Returns
current MTU
Definition at line 93 of file tun_device.h.
char*(* tun_device_t::get_name)(tun_device_t *this)
Get the interface name of this device
Returns
interface name
Definition at line 100 of file tun_device.h.
Referenced by METHOD(), and signal_ipv4_config().
bool(* tun_device_t::read_packet)(tun_device_t *this, chunk_t *packet)
Read a packet from the TUN device
Note
This call blocks until a packet is available. It is a thread cancellation point.
Parameters
packet the packet read from the device, allocated
Returns
TRUE if successful
Definition at line 46 of file tun_device.h.
Referenced by process_plain().
bool(* tun_device_t::set_address)(tun_device_t *this, host_t *addr, u_int8_t netmask)
Set the IP address of the device
Parameters
addr the desired interface address
netmask the netmask to use
Returns
TRUE if operation successful
Definition at line 63 of file tun_device.h.
Referenced by METHOD().
bool(* tun_device_t::set_mtu)(tun_device_t *this, int mtu)
Set the MTU for this TUN device
Parameters
mtu new MTU
Returns
TRUE if operation successful
Definition at line 86 of file tun_device.h.
bool(* tun_device_t::up)(tun_device_t *this)
Bring the TUN device up
Returns
TRUE if operation successful
Definition at line 78 of file tun_device.h.
Referenced by METHOD().
bool(* tun_device_t::write_packet)(tun_device_t *this, chunk_t packet)
Write a packet to the TUN device
Parameters
packet the packet to write to the TUN device
Returns
TRUE if successful
Definition at line 54 of file tun_device.h.
Referenced by deliver_plain().
The documentation for this struct was generated from the following file:
tun_device.h