strongSwan: cmp.c File Reference
cmp.c File Reference
#include <string.h>
#include "confread.h"
#include "args.h"
#include "cmp.h"
Macros
#define VARCMP(obj) if (c1->obj != c2->obj) return FALSE
#define STRCMP(obj) if (strcmp(c1->obj,c2->obj)) return FALSE
Functions
static bool starter_cmp_end (starter_end_t *c1, starter_end_t *c2)
bool starter_cmp_conn (starter_conn_t *c1, starter_conn_t *c2)
bool starter_cmp_ca (starter_ca_t *c1, starter_ca_t *c2)
Macro Definition Documentation
#define STRCMP (obj) if (strcmp(c1->obj,c2->obj)) return FALSE
Definition at line 22 of file cmp.c.
#define VARCMP (obj) if (c1->obj != c2->obj) return FALSE
Definition at line 21 of file cmp.c.
Referenced by starter_cmp_conn(), and starter_cmp_end().
Function Documentation
bool starter_cmp_ca (starter_ca_t * c1, starter_ca_t * c2)
Definition at line 60 of file cmp.c.
References cmp_args(), FALSE, KW_CA_LAST, and KW_CA_NAME.
Referenced by main().
 {
     if (c1 ==  NULL || c2 == NULL)
         return FALSE;
     return cmp_args(KW_CA_NAME, KW_CA_LAST, (char *)c1, (char *)c2);
 }
bool starter_cmp_conn (starter_conn_t * c1, starter_conn_t * c2)
Definition at line 37 of file cmp.c.
References cmp_args(), FALSE, KW_CONN_LAST, KW_CONN_NAME, starter_conn::left, format-options::options, starter_conn::right, starter_cmp_end(), and VARCMP.
Referenced by main().
 {
     if ((c1 == NULL) || (c2 == NULL))
         return FALSE;
     VARCMP(mode);
     VARCMP(proxy_mode);
     VARCMP(options);
     VARCMP(mark_in.value);
     VARCMP(mark_in.mask);
     VARCMP(mark_out.value);
     VARCMP(mark_out.mask);
     VARCMP(tfc);
     VARCMP(sa_keying_tries);
     if (!starter_cmp_end(&c1->left, &c2->left))
         return FALSE;
     if (!starter_cmp_end(&c1->right, &c2->right))
         return FALSE;
     return cmp_args(KW_CONN_NAME, KW_CONN_LAST, (char *)c1, (char *)c2);
 }
static bool starter_cmp_end (starter_end_t * c1, starter_end_t * c2) static
Definition at line 24 of file cmp.c.
References cmp_args(), FALSE, from_port, KW_END_FIRST, KW_END_LAST, protocol, to_port, and VARCMP.
Referenced by starter_cmp_conn().
 {
     if ((c1 == NULL) || (c2 == NULL))
         return FALSE;
     VARCMP(modecfg);
     VARCMP(from_port);
     VARCMP(to_port);
     VARCMP(protocol);
     return cmp_args(KW_END_FIRST, KW_END_LAST, (char *)c1, (char *)c2);
 }