strongSwan: pts_comp_func_name
pts_comp_func_name
pts
Classes
struct pts_comp_func_name_t
Macros
#define PTS_QUALIFIER_UNKNOWN 0x00
#define PTS_QUALIFIER_WILDCARD 0x3F
Typedefs
typedef struct pts_comp_func_name_t pts_comp_func_name_t
Functions
pts_comp_func_name_t * pts_comp_func_name_create (u_int32_t vid, u_int32_t name, u_int8_t qualifier)
Detailed Description
Macro Definition Documentation
#define PTS_QUALIFIER_UNKNOWN 0x00
Definition at line 28 of file pts_comp_func_name.h.
Referenced by equals(), METHOD(), and pts_ita_comp_ima_create().
#define PTS_QUALIFIER_WILDCARD 0x3F
Definition at line 29 of file pts_comp_func_name.h.
Typedef Documentation
typedef struct pts_comp_func_name_t pts_comp_func_name_t
Definition at line 24 of file pts_comp_func_name.h.
Function Documentation
pts_comp_func_name_t* pts_comp_func_name_create (u_int32_t vid, u_int32_t name, u_int8_t qualifier)
Create a PTS Component Functional Name object
Parameters
vid PTS Component Functional Name Vendor ID
name PTS Component Functional Name
qualifier PTS Component Functional Name Qualifier
See header
Definition at line 139 of file pts_comp_func_name.c.
References bool, equals(), INIT, and name.
Referenced by METHOD(), pts_ita_comp_ima_create(), pts_ita_comp_tboot_create(), and pts_ita_comp_tgrub_create().
 {
     private_pts_comp_func_name_t *this;
     INIT(this,
         .public = {
             .get_vendor_id = _get_vendor_id,
             .get_name = _get_name,
             .get_qualifier = _get_qualifier,
             .set_qualifier = _set_qualifier,
             .equals = (bool(*)(pts_comp_func_name_t*,pts_comp_func_name_t*))equals,
             .clone = _clone_,
             .log = _log_,
             .destroy = _destroy,
         },
         .vid = vid,
         .name = name,
         .qualifier = qualifier,
     );
     return &this->public;
 }