strongSwan: pkcs11_manager.c File Reference
pkcs11_manager.c File Reference
#include "pkcs11_manager.h"
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <threading/thread.h>
#include "pkcs11_library.h"
#include <processing/jobs/callback_job.h>
Classes
struct private_pkcs11_manager_t
struct lib_entry_t
struct token_enumerator_t
Typedefs
typedef struct
private_pkcs11_manager_t private_pkcs11_manager_t
Functions
static void lib_entry_destroy (lib_entry_t *entry)
static void print_mechs (lib_entry_t *entry, CK_SLOT_ID slot)
static void handle_token (lib_entry_t *entry, CK_SLOT_ID slot)
static void handle_slot (lib_entry_t *entry, CK_SLOT_ID slot, bool hot)
static job_requeue_t dispatch_slot_events (lib_entry_t *entry)
static CK_SLOT_ID_PTR get_slot_list (pkcs11_library_t *p11, CK_ULONG *out)
static void query_slots (lib_entry_t *entry)
METHOD (enumerator_t, enumerate_token, bool, token_enumerator_t *this, pkcs11_library_t **out, CK_SLOT_ID *slot)
METHOD (enumerator_t, destroy_token, void, token_enumerator_t *this)
METHOD (pkcs11_manager_t, create_token_enumerator, enumerator_t *, private_pkcs11_manager_t *this)
METHOD (pkcs11_manager_t, destroy, void, private_pkcs11_manager_t *this)
pkcs11_manager_t * pkcs11_manager_create (pkcs11_manager_token_event_t cb, void *data)
Typedef Documentation
typedef struct private_pkcs11_manager_t private_pkcs11_manager_t
Definition at line 26 of file pkcs11_manager.c.
Function Documentation
static job_requeue_t dispatch_slot_events (lib_entry_t * entry) static
Dispatch slot events
Definition at line 170 of file pkcs11_manager.c.
References ck_function_list::C_WaitForSlotEvent, ck_rv_names, CKR_CRYPTOKI_NOT_INITIALIZED, CKR_FUNCTION_NOT_SUPPORTED, CKR_NO_EVENT, CKR_OK, DBG1, DBG_CFG, pkcs11_library_t::f, pkcs11_library_t::get_name, handle_slot(), JOB_REQUEUE_DIRECT, JOB_REQUEUE_NONE, lib_entry_t::lib, thread_cancelability(), and TRUE.
Referenced by pkcs11_manager_create().
 {
     CK_SLOT_ID slot;
     CK_RV rv;
     bool old;
     old = thread_cancelability(TRUE);
     rv = entry->lib->f->C_WaitForSlotEvent(0, &slot, NULL);
     thread_cancelability(old);
     if (rv == CKR_FUNCTION_NOT_SUPPORTED || rv == CKR_NO_EVENT)
     {
         DBG1(DBG_CFG, "module '%s' does not support hot-plugging, cancelled",
              entry->lib->get_name(entry->lib));
         return JOB_REQUEUE_NONE;
     }
     if (rv == CKR_CRYPTOKI_NOT_INITIALIZED)
     {   /* C_Finalize called, abort */
         return JOB_REQUEUE_NONE;
     }
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "error in C_WaitForSlotEvent: %N", ck_rv_names, rv);
     }
     handle_slot(entry, slot, TRUE);
     return JOB_REQUEUE_DIRECT;
 }
static CK_SLOT_ID_PTR get_slot_list (pkcs11_library_t * p11, CK_ULONG * out) static
Get the slot list of a library
Definition at line 201 of file pkcs11_manager.c.
References ck_function_list::C_GetSlotList, ck_rv_names, CKR_OK, count, DBG1, DBG_CFG, pkcs11_library_t::f, free(), malloc(), and TRUE.
Referenced by METHOD(), and query_slots().
 {
     CK_SLOT_ID_PTR slots;
     CK_ULONG count;
     CK_RV rv;
     rv = p11->f->C_GetSlotList(TRUE, NULL, &count);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_GetSlotList() failed: %N", ck_rv_names, rv);
         return NULL;
     }
     if (count == 0)
     {
         return NULL;
     }
     slots = malloc(sizeof(CK_SLOT_ID) * count);
     rv = p11->f->C_GetSlotList(TRUE, slots, &count);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_GetSlotList() failed: %N", ck_rv_names, rv);
         free(slots);
         return NULL;
     }
     *out = count;
     return slots;
 }
static void handle_slot (lib_entry_t * entry, CK_SLOT_ID slot, bool hot) static
Handle slot changes
Definition at line 133 of file pkcs11_manager.c.
References ck_function_list::C_GetSlotInfo, private_pkcs11_manager_t::cb, ck_rv_names, CKF_TOKEN_PRESENT, CKR_OK, private_pkcs11_manager_t::data, DBG1, DBG_CFG, pkcs11_library_t::f, FALSE, ck_slot_info::flags, pkcs11_library_t::get_name, handle_token(), lib_entry_t::lib, pkcs11_library_trim(), lib_entry_t::this, and TRUE.
Referenced by dispatch_slot_events(), and query_slots().
 {
     CK_SLOT_INFO info;
     CK_RV rv;
     rv = entry->lib->f->C_GetSlotInfo(slot, &info);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_GetSlotInfo failed: %N", ck_rv_names, rv);
         return;
     }
     pkcs11_library_trim(info.slotDescription, sizeof(info.slotDescription));
     if (info.flags & CKF_TOKEN_PRESENT)
     {
         DBG1(DBG_CFG, "  found token in slot '%s':%lu (%s)",
              entry->lib->get_name(entry->lib), slot, info.slotDescription);
         handle_token(entry, slot);
         if (hot)
         {
             entry->this->cb(entry->this->data, entry->lib, slot, TRUE);
         }
     }
     else
     {
         DBG1(DBG_CFG, "token removed from slot '%s':%lu (%s)",
              entry->lib->get_name(entry->lib), slot, info.slotDescription);
         if (hot)
         {
             entry->this->cb(entry->this->data, entry->lib, slot, FALSE);
         }
     }
 }
static void handle_token (lib_entry_t * entry, CK_SLOT_ID slot) static
Handle a token
Definition at line 110 of file pkcs11_manager.c.
References ck_function_list::C_GetTokenInfo, ck_rv_names, CKR_OK, DBG1, DBG_CFG, pkcs11_library_t::f, ck_token_info::label, lib_entry_t::lib, ck_token_info::model, pkcs11_library_trim(), and print_mechs().
Referenced by handle_slot().
 {
     CK_TOKEN_INFO info;
     CK_RV rv;
     rv = entry->lib->f->C_GetTokenInfo(slot, &info);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "C_GetTokenInfo failed: %N", ck_rv_names, rv);
         return;
     }
     pkcs11_library_trim(info.label, sizeof(info.label));
     pkcs11_library_trim(info.manufacturerID, sizeof(info.manufacturerID));
     pkcs11_library_trim(info.model, sizeof(info.model));
     DBG1(DBG_CFG, "    %s (%s: %s)",
          info.label, info.manufacturerID, info.model);
     print_mechs(entry, slot);
 }
static void lib_entry_destroy (lib_entry_t * entry) static
Destroy a lib_entry_t
Definition at line 69 of file pkcs11_manager.c.
References pkcs11_library_t::destroy, free(), and lib_entry_t::lib.
Referenced by METHOD().
 {
     entry->lib->destroy(entry->lib);
     free(entry);
 }
METHOD (enumerator_t , enumerate_token , bool , token_enumerator_t * this, pkcs11_library_t ** out, CK_SLOT_ID * slot)
Definition at line 267 of file pkcs11_manager.c.
References count, FALSE, free(), get_slot_list(), and TRUE.
 {
     if (this->current >= this->count)
     {
         free(this->slots);
         this->slots = NULL;
         this->current = 0;
     }
     while (!this->slots)
     {
         if (!this->inner->enumerate(this->inner, &this->entry))
         {
             return FALSE;
         }
         this->slots = get_slot_list(this->entry->lib, &this->count);
     }
     *out = this->entry->lib;
     *slot = this->slots[this->current++];
     return TRUE;
 }
METHOD (enumerator_t , destroy_token , void , token_enumerator_t * this)
Definition at line 289 of file pkcs11_manager.c.
References free().
 {
     this->inner->destroy(this->inner);
     free(this->slots);
     free(this);
 }
METHOD (pkcs11_manager_t , create_token_enumerator , enumerator_t * , private_pkcs11_manager_t * this)
Definition at line 297 of file pkcs11_manager.c.
References destroy(), INIT, and token_enumerator_t::public.
 {
     token_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_enumerate_token,
             .destroy = _destroy_token,
         },
         .inner = this->libs->create_enumerator(this->libs),
     );
     return &enumerator->public;
 }
METHOD (pkcs11_manager_t , destroy , void , private_pkcs11_manager_t * this)
Definition at line 312 of file pkcs11_manager.c.
References free(), and lib_entry_destroy().
 {
     this->libs->destroy_function(this->libs, (void*)lib_entry_destroy);
     free(this);
 }
static void print_mechs (lib_entry_t * entry, CK_SLOT_ID slot) static
Print supported mechanisms of a token in a slot
Definition at line 78 of file pkcs11_manager.c.
References ck_mech_names, CKF_DECRYPT, CKF_DERIVE, CKF_DIGEST, CKF_ENCRYPT, CKF_GENERATE, CKF_GENERATE_KEY_PAIR, CKF_HW, CKF_SIGN, CKF_SIGN_RECOVER, CKF_UNWRAP, CKF_VERIFY, CKF_VERIFY_RECOVER, CKF_WRAP, pkcs11_library_t::create_mechanism_enumerator, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, ck_mechanism_info::flags, lib_entry_t::lib, and type.
Referenced by handle_token().
 {
     enumerator_t *enumerator;
     CK_MECHANISM_TYPE type;
     CK_MECHANISM_INFO info;
     enumerator = entry->lib->create_mechanism_enumerator(entry->lib, slot);
     while (enumerator->enumerate(enumerator, &type, &info))
     {
         DBG2(DBG_CFG, "      %N %lu-%lu [ %s%s%s%s%s%s%s%s%s%s%s%s%s]",
             ck_mech_names, type,
             info.ulMinKeySize, info.ulMaxKeySize,
             info.flags & CKF_HW ? "HW " : "",
             info.flags & CKF_ENCRYPT ? "ENCR " : "",
             info.flags & CKF_DECRYPT ? "DECR " : "",
             info.flags & CKF_DIGEST ? "DGST " : "",
             info.flags & CKF_SIGN ? "SIGN " : "",
             info.flags & CKF_SIGN_RECOVER ? "SIGN_RCVR " : "",
             info.flags & CKF_VERIFY ? "VRFY " : "",
             info.flags & CKF_VERIFY_RECOVER ? "VRFY_RCVR " : "",
             info.flags & CKF_GENERATE ? "GEN " : "",
             info.flags & CKF_GENERATE_KEY_PAIR ? "GEN_KEY_PAIR " : "",
             info.flags & CKF_WRAP ? "WRAP " : "",
             info.flags & CKF_UNWRAP ? "UNWRAP " : "",
             info.flags & CKF_DERIVE ? "DERIVE " : "");
     }
     enumerator->destroy(enumerator);
 }
static void query_slots (lib_entry_t * entry) static
Query the slots for tokens
Definition at line 232 of file pkcs11_manager.c.
References count, FALSE, free(), get_slot_list(), handle_slot(), and lib_entry_t::lib.
Referenced by pkcs11_manager_create().
 {
     CK_ULONG count;
     CK_SLOT_ID_PTR slots;
     int i;
     slots = get_slot_list(entry->lib, &count);
     if (slots)
     {
         for (i = 0; i < count; i++)
         {
             handle_slot(entry, slots[i], FALSE);
         }
         free(slots);
     }
 }