strongSwan: cert_cache.c File Reference
cert_cache.c File Reference
#include "cert_cache.h"
#include <time.h>
#include <library.h>
#include <threading/rwlock.h>
#include <collections/linked_list.h>
Classes
struct relation_t
struct private_cert_cache_t
struct cert_enumerator_t
Macros
#define CACHE_SIZE 32
#define REPLACE_TRIES 5
Typedefs
typedef struct private_cert_cache_t private_cert_cache_t
typedef struct relation_t relation_t
Functions
static void cache (private_cert_cache_t *this, certificate_t *subject, certificate_t *issuer, signature_scheme_t scheme)
METHOD (cert_cache_t, issued_by, bool, private_cert_cache_t *this, certificate_t *subject, certificate_t *issuer, signature_scheme_t *schemep)
static bool cert_enumerate (cert_enumerator_t *this, certificate_t **out)
static void cert_enumerator_destroy (cert_enumerator_t *this)
METHOD (credential_set_t, create_enumerator, enumerator_t *, private_cert_cache_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (cert_cache_t, flush, void, private_cert_cache_t *this, certificate_type_t type)
METHOD (cert_cache_t, destroy, void, private_cert_cache_t *this)
cert_cache_t * cert_cache_create ()
Macro Definition Documentation
#define CACHE_SIZE 32
cache size, a power of 2 for fast modulo
Definition at line 25 of file cert_cache.c.
Referenced by cache(), cert_cache_create(), cert_enumerate(), and METHOD().
#define REPLACE_TRIES 5
attempts to acquire a cache lock
Definition at line 28 of file cert_cache.c.
Referenced by cache().
Typedef Documentation
typedef struct private_cert_cache_t private_cert_cache_t
Definition at line 30 of file cert_cache.c.
typedef struct relation_t relation_t
Definition at line 31 of file cert_cache.c.
Function Documentation
static void cache (private_cert_cache_t * this, certificate_t * subject, certificate_t * issuer, signature_scheme_t scheme) static
Cache relation in a free slot/replace an other
Definition at line 83 of file cert_cache.c.
References CACHE_SIZE, certificate_t::destroy, certificate_t::get_ref, relation_t::hits, relation_t::issuer, relation_t::lock, offset, random, rel(), REPLACE_TRIES, sched_yield(), relation_t::scheme, scheme, relation_t::subject, rwlock_t::try_write_lock, and rwlock_t::unlock.
Referenced by cred_encoding_create(), credential_manager_create(), derive_master(), dispatch_fifo(), ha_ctl_create(), ha_dispatcher_create(), ha_ike_create(), initialize_plugin(), main(), METHOD(), process_ike_add(), process_ike_delete(), process_ike_iv(), process_ike_mid(), process_ike_update(), process_resync(), sync_vips(), and tls_crypto_create().
 {
     relation_t *rel;
     int i, offset, try;
     u_int total_hits = 0;
     /* check for a unused relation slot first */
     for (i = 0; i < CACHE_SIZE; i++)
     {
         rel = &this->relations[i];
         if (!rel->subject && rel->lock->try_write_lock(rel->lock))
         {
             /* double-check having lock */
             if (!rel->subject)
             {
                 rel->subject = subject->get_ref(subject);
                 rel->issuer = issuer->get_ref(issuer);
                 rel->scheme = scheme;
                 return rel->lock->unlock(rel->lock);
             }
             rel->lock->unlock(rel->lock);
         }
         total_hits += rel->hits;
     }
     /* run several attempts to replace a random slot, never block. */
     for (try = 0; try < REPLACE_TRIES; try++)
     {
         /* replace a random relation */
         offset = random();
         for (i = 0; i < CACHE_SIZE; i++)
         {
             rel = &this->relations[(i + offset) % CACHE_SIZE];
             if (rel->hits > total_hits / CACHE_SIZE)
             {   /* skip often used slots */
                 continue;
             }
             if (rel->lock->try_write_lock(rel->lock))
             {
                 if (rel->subject)
                 {
                     rel->subject->destroy(rel->subject);
                     rel->issuer->destroy(rel->issuer);
                 }
                 rel->subject = subject->get_ref(subject);
                 rel->issuer = issuer->get_ref(issuer);
                 rel->scheme = scheme;
                 rel->hits = 0;
                 return rel->lock->unlock(rel->lock);
             }
         }
         /* give other threads a chance to release locks */
         sched_yield();
     }
 }
static bool cert_enumerate (cert_enumerator_t * this, certificate_t ** out) static
filter function for certs enumerator
Definition at line 219 of file cert_cache.c.
References CACHE_SIZE, cert, CERT_ANY, CERT_X509_CRL, public_key_t::destroy, FALSE, certificate_t::get_public_key, certificate_t::get_type, certificate_t::has_issuer, certificate_t::has_subject, key, KEY_ANY, relation_t::lock, public, rwlock_t::read_lock, rel(), relation_t::subject, TRUE, and rwlock_t::unlock.
Referenced by METHOD().
 {
     public_key_t *public;
     relation_t *rel;
     if (this->locked >= 0)
     {
         rel = &this->relations[this->locked];
         rel->lock->unlock(rel->lock);
         this->locked = -1;
     }
     while (++this->index < CACHE_SIZE)
     {
         rel = &this->relations[this->index];
         rel->lock->read_lock(rel->lock);
         this->locked = this->index;
         if (rel->subject)
         {
             /* CRL lookup is done using issuer/authkeyidentifier */
             if (this->key == KEY_ANY && this->id &&
                 (this->cert == CERT_ANY || this->cert == CERT_X509_CRL) &&
                 rel->subject->get_type(rel->subject) == CERT_X509_CRL &&
                 rel->subject->has_issuer(rel->subject, this->id))
             {
                 *out = rel->subject;
                 return TRUE;
             }
             if ((this->cert == CERT_ANY ||
                  rel->subject->get_type(rel->subject) == this->cert) &&
                 (!this->id || rel->subject->has_subject(rel->subject, this->id)))
             {
                 if (this->key == KEY_ANY)
                 {
                     *out = rel->subject;
                     return TRUE;
                 }
                 public = rel->subject->get_public_key(rel->subject);
                 if (public)
                 {
                     if (public->get_type(public) == this->key)
                     {
                         public->destroy(public);
                         *out = rel->subject;
                         return TRUE;
                     }
                     public->destroy(public);
                 }
             }
         }
         this->locked = -1;
         rel->lock->unlock(rel->lock);
     }
     return FALSE;
 }
static void cert_enumerator_destroy (cert_enumerator_t * this) static
clean up enumeration data
Definition at line 278 of file cert_cache.c.
References free(), relation_t::lock, rel(), and rwlock_t::unlock.
Referenced by METHOD().
 {
     relation_t *rel;
     if (this->locked >= 0)
     {
         rel = &this->relations[this->locked];
         rel->lock->unlock(rel->lock);
     }
     free(this);
 }
METHOD (cert_cache_t , issued_by , bool , private_cert_cache_t * this, certificate_t * subject, certificate_t * issuer, signature_scheme_t * schemep)
Definition at line 142 of file cert_cache.c.
References cache(), CACHE_SIZE, DESTROY_IF, certificate_t::equals, FALSE, found, certificate_t::get_ref, certificate_t::issued_by, relation_t::scheme, scheme, and TRUE.
 {
     certificate_t *cached_issuer = NULL;
     relation_t *found = NULL, *current;
     signature_scheme_t scheme;
     int i;
     for (i = 0; i < CACHE_SIZE; i++)
     {
         current = &this->relations[i];
         current->lock->read_lock(current->lock);
         if (current->subject)
         {
             if (issuer->equals(issuer, current->issuer))
             {
                 if (subject->equals(subject, current->subject))
                 {
                     current->hits++;
                     found = current;
                     if (schemep)
                     {
                         *schemep = current->scheme;
                     }
                 }
                 else if (!cached_issuer)
                 {
                     cached_issuer = current->issuer->get_ref(current->issuer);
                 }
             }
         }
         current->lock->unlock(current->lock);
         if (found)
         {
             DESTROY_IF(cached_issuer);
             return TRUE;
         }
     }
     if (subject->issued_by(subject, issuer, &scheme))
     {
         cache(this, subject, cached_issuer ?: issuer, scheme);
         if (schemep)
         {
             *schemep = scheme;
         }
         DESTROY_IF(cached_issuer);
         return TRUE;
     }
     DESTROY_IF(cached_issuer);
     return FALSE;
 }
METHOD (credential_set_t , create_enumerator , enumerator_t * , private_cert_cache_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 290 of file cert_cache.c.
References cert, cert_enumerator_t::cert, cert_enumerate(), cert_enumerator_destroy(), enumerator_t::destroy, enumerator_t::enumerate, id, cert_enumerator_t::id, cert_enumerator_t::index, cert_enumerator_t::key, key, cert_enumerator_t::locked, malloc_thing, cert_enumerator_t::public, and cert_enumerator_t::relations.
 {
     cert_enumerator_t *enumerator;
     if (trusted)
     {
         return NULL;
     }
     enumerator = malloc_thing(cert_enumerator_t);
     enumerator->public.enumerate = (void*)cert_enumerate;
     enumerator->public.destroy = (void*)cert_enumerator_destroy;
     enumerator->cert = cert;
     enumerator->key = key;
     enumerator->id = id;
     enumerator->relations = this->relations;
     enumerator->index = -1;
     enumerator->locked = -1;
     return &enumerator->public;
 }
METHOD (cert_cache_t , flush , void , private_cert_cache_t * this, certificate_type_t type)
Definition at line 313 of file cert_cache.c.
References CACHE_SIZE, CERT_ANY, certificate_t::destroy, certificate_t::get_type, relation_t::hits, relation_t::issuer, relation_t::lock, rwlock_t::read_lock, rel(), relation_t::subject, rwlock_t::unlock, and rwlock_t::write_lock.
 {
     relation_t *rel;
     int i;
     for (i = 0; i < CACHE_SIZE; i++)
     {
         rel = &this->relations[i];
         if (!rel->subject)
         {
             continue;
         }
         /* check with cheap read lock first */
         if (type != CERT_ANY)
         {
             rel->lock->read_lock(rel->lock);
             if (!rel->subject || type != rel->subject->get_type(rel->subject))
             {
                 rel->lock->unlock(rel->lock);
                 continue;
             }
             rel->lock->unlock(rel->lock);
         }
         /* double check in write lock */
         rel->lock->write_lock(rel->lock);
         if (rel->subject)
         {
             if (type == CERT_ANY || type == rel->subject->get_type(rel->subject))
             {
                 rel->subject->destroy(rel->subject);
                 rel->issuer->destroy(rel->issuer);
                 rel->subject = NULL;
                 rel->issuer = NULL;
                 rel->hits = 0;
             }
         }
         rel->lock->unlock(rel->lock);
     }
 }
METHOD (cert_cache_t , destroy , void , private_cert_cache_t * this)
Definition at line 354 of file cert_cache.c.
References CACHE_SIZE, rwlock_t::destroy, certificate_t::destroy, free(), relation_t::issuer, relation_t::lock, rel(), and relation_t::subject.
 {
     relation_t *rel;
     int i;
     for (i = 0; i < CACHE_SIZE; i++)
     {
         rel = &this->relations[i];
         if (rel->subject)
         {
             rel->subject->destroy(rel->subject);
             rel->issuer->destroy(rel->issuer);
         }
         rel->lock->destroy(rel->lock);
     }
     free(this);
 }