strongSwan: ietf_attr_numeric_version.c File Reference
ietf_attr_numeric_version.c File Reference
#include "ietf_attr_numeric_version.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_numeric_version_t
Macros
#define NUMERIC_VERSION_SIZE 16
Typedefs
typedef struct
private_ietf_attr_numeric_version_t private_ietf_attr_numeric_version_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_numeric_version_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_numeric_version_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_numeric_version_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_numeric_version_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_numeric_version_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_numeric_version_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_numeric_version_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_numeric_version_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_numeric_version_t *this)
METHOD (ietf_attr_numeric_version_t, get_version, void, private_ietf_attr_numeric_version_t *this, u_int32_t *major, u_int32_t *minor)
METHOD (ietf_attr_numeric_version_t, get_build, u_int32_t, private_ietf_attr_numeric_version_t *this)
METHOD (ietf_attr_numeric_version_t, get_service_pack, void, private_ietf_attr_numeric_version_t *this, u_int16_t *major, u_int16_t *minor)
pa_tnc_attr_t * ietf_attr_numeric_version_create (u_int32_t major, u_int32_t minor, u_int32_t build, u_int16_t service_pack_major, u_int16_t service_pack_minor)
pa_tnc_attr_t * ietf_attr_numeric_version_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define NUMERIC_VERSION_SIZE 16
PA-TNC Numeric Version type (see section 4.2.3 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Major Version Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Minor Version Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Build Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Service Pack Major | Service Pack Minor | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 41 of file ietf_attr_numeric_version.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_numeric_version_t private_ietf_attr_numeric_version_t
Definition at line 23 of file ietf_attr_numeric_version.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_numeric_version_t * this)
Definition at line 104 of file ietf_attr_numeric_version.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_numeric_version_t * this)
Definition at line 110 of file ietf_attr_numeric_version.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_numeric_version_t * this)
Definition at line 116 of file ietf_attr_numeric_version.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_numeric_version_t * this, bool noskip)
Definition at line 122 of file ietf_attr_numeric_version.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_numeric_version_t * this)
Definition at line 128 of file ietf_attr_numeric_version.c.
References bio_writer_create(), build(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, NUMERIC_VERSION_SIZE, value, bio_writer_t::write_uint16, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(NUMERIC_VERSION_SIZE);
     writer->write_uint32(writer, this->major_version);
     writer->write_uint32(writer, this->minor_version);
     writer->write_uint32(writer, this->build);
     writer->write_uint16(writer, this->service_pack_major);
     writer->write_uint16(writer, this->service_pack_minor);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_numeric_version_t * this, u_int32_t * offset)
Definition at line 150 of file ietf_attr_numeric_version.c.
References bio_reader_create(), build(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, NUMERIC_VERSION_SIZE, bio_reader_t::read_uint16, bio_reader_t::read_uint32, SUCCESS, and value.
 {
     bio_reader_t *reader;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < NUMERIC_VERSION_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for IETF numeric version");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint32(reader, &this->major_version);
     reader->read_uint32(reader, &this->minor_version);
     reader->read_uint32(reader, &this->build);
     reader->read_uint16(reader, &this->service_pack_major);
     reader->read_uint16(reader, &this->service_pack_minor);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_numeric_version_t * this, chunk_t segment)
Definition at line 177 of file ietf_attr_numeric_version.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_numeric_version_t * this)
Definition at line 183 of file ietf_attr_numeric_version.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_numeric_version_t * this)
Definition at line 190 of file ietf_attr_numeric_version.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_numeric_version_t , get_version , void , private_ietf_attr_numeric_version_t * this, u_int32_t * major, u_int32_t * minor)
Definition at line 200 of file ietf_attr_numeric_version.c.
 {
     if (major)
     {
         *major = this->major_version;
     }
     if (minor)
     {
         *minor = this->minor_version;
     }
 }
METHOD (ietf_attr_numeric_version_t , get_build , u_int32_t , private_ietf_attr_numeric_version_t * this)
Definition at line 213 of file ietf_attr_numeric_version.c.
References build().
 {
     return this->build;
 }
METHOD (ietf_attr_numeric_version_t , get_service_pack , void , private_ietf_attr_numeric_version_t * this, u_int16_t * major, u_int16_t * minor)
Definition at line 219 of file ietf_attr_numeric_version.c.
 {
     if (major)
     {
         *major = this->service_pack_major;
     }
     if (minor)
     {
         *minor = this->service_pack_minor;
     }
 }