strongSwan: pkcs7_plugin.c File Reference
pkcs7_plugin.c File Reference
#include "pkcs7_plugin.h"
#include "pkcs7_generic.h"
#include "pkcs7_data.h"
#include "pkcs7_signed_data.h"
#include "pkcs7_enveloped_data.h"
#include <library.h>
Classes
struct private_pkcs7_plugin_t
Typedefs
typedef struct
private_pkcs7_plugin_t private_pkcs7_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_pkcs7_plugin_t *this)
METHOD (plugin_t, get_features, int, private_pkcs7_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_pkcs7_plugin_t *this)
plugin_t * pkcs7_plugin_create ()
Typedef Documentation
typedef struct private_pkcs7_plugin_t private_pkcs7_plugin_t
Definition at line 24 of file pkcs7_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_pkcs7_plugin_t * this)
Definition at line 37 of file pkcs7_plugin.c.
 {
     return "pkcs7";
 }
METHOD (plugin_t , get_features , int , private_pkcs7_plugin_t * this, plugin_feature_t * features[])
Definition at line 43 of file pkcs7_plugin.c.
References CONTAINER_PKCS7, CONTAINER_PKCS7_DATA, CONTAINER_PKCS7_ENVELOPED_DATA, CONTAINER_PKCS7_SIGNED_DATA, countof, pkcs7_data_gen(), pkcs7_enveloped_data_gen(), pkcs7_generic_load(), pkcs7_signed_data_gen(), PLUGIN_PROVIDE, PLUGIN_REGISTER, and TRUE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_REGISTER(CONTAINER_DECODE, pkcs7_generic_load, TRUE),
             PLUGIN_PROVIDE(CONTAINER_DECODE, CONTAINER_PKCS7),
         PLUGIN_REGISTER(CONTAINER_ENCODE, pkcs7_data_gen, TRUE),
             PLUGIN_PROVIDE(CONTAINER_ENCODE, CONTAINER_PKCS7_DATA),
         PLUGIN_REGISTER(CONTAINER_ENCODE, pkcs7_signed_data_gen, TRUE),
             PLUGIN_PROVIDE(CONTAINER_ENCODE, CONTAINER_PKCS7_SIGNED_DATA),
         PLUGIN_REGISTER(CONTAINER_ENCODE, pkcs7_enveloped_data_gen, TRUE),
             PLUGIN_PROVIDE(CONTAINER_ENCODE, CONTAINER_PKCS7_ENVELOPED_DATA),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_pkcs7_plugin_t * this)
Definition at line 60 of file pkcs7_plugin.c.
References free().
 {
     free(this);
 }
plugin_t* pkcs7_plugin_create ()
Definition at line 69 of file pkcs7_plugin.c.
References INIT.
 {
     private_pkcs7_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }