strongSwan: sqlite_database.c File Reference
sqlite_database.c File Reference
#include "sqlite_database.h"
#include <sqlite3.h>
#include <unistd.h>
#include <library.h>
#include <utils/debug.h>
#include <threading/mutex.h>
#include <threading/thread_value.h>
Classes
struct private_sqlite_database_t
struct transaction_t
struct sqlite_enumerator_t
Typedefs
typedef struct
private_sqlite_database_t private_sqlite_database_t
Functions
static bool is_threadsave ()
static sqlite3_stmt * run (private_sqlite_database_t *this, char *sql, va_list *args)
static void sqlite_enumerator_destroy (sqlite_enumerator_t *this)
static bool sqlite_enumerator_enumerate (sqlite_enumerator_t *this,...)
METHOD (database_t, query, enumerator_t *, private_sqlite_database_t *this, char *sql,...)
METHOD (database_t, execute, int, private_sqlite_database_t *this, int *rowid, char *sql,...)
METHOD (database_t, transaction, bool, private_sqlite_database_t *this, bool serializable)
static bool finalize_transaction (private_sqlite_database_t *this, bool rollback)
METHOD (database_t, commit_, bool, private_sqlite_database_t *this)
METHOD (database_t, rollback, bool, private_sqlite_database_t *this)
METHOD (database_t, get_driver, db_driver_t, private_sqlite_database_t *this)
static int busy_handler (private_sqlite_database_t *this, int count)
METHOD (database_t, destroy, void, private_sqlite_database_t *this)
sqlite_database_t * sqlite_database_create (char *uri)
Typedef Documentation
typedef struct private_sqlite_database_t private_sqlite_database_t
Definition at line 26 of file sqlite_database.c.
Function Documentation
static int busy_handler (private_sqlite_database_t * this, int count) static
Busy handler implementation
Definition at line 404 of file sqlite_database.c.
References usleep().
Referenced by sqlite_database_create().
 {
     /* add a backoff time, quadratically increasing with every try */
     usleep(count * count * 1000);
     /* always retry */
     return 1;
 }
static bool finalize_transaction (private_sqlite_database_t * this, bool rollback) static
Finalize a transaction depending on the reference count and if it should be rolled back.
Definition at line 350 of file sqlite_database.c.
References command, DBG1, DBG_LIB, FALSE, free(), ref_put(), transaction_t::refs, transaction_t::rollback, and TRUE.
Referenced by METHOD().
 {
     transaction_t *trans;
     char *command = "COMMIT TRANSACTION";
     bool success;
     trans = this->transaction->get(this->transaction);
     if (!trans)
     {
         DBG1(DBG_LIB, "no database transaction found");
         return FALSE;
     }
     if (ref_put(&trans->refs))
     {
         if (trans->rollback)
         {
             command = "ROLLBACK TRANSACTION";
         }
         success = execute(this, NULL, command) != -1;
         this->transaction->set(this->transaction, NULL);
         free(trans);
         return success;
     }
     else
     {   /* set flag, can't be unset */
         trans->rollback |= rollback;
     }
     return TRUE;
 }
static bool is_threadsave () static
Check if the SQLite library is thread safe
Definition at line 74 of file sqlite_database.c.
References FALSE.
Referenced by METHOD(), and sqlite_enumerator_destroy().
 {
 #if SQLITE_VERSION_NUMBER >= 3005000
     return sqlite3_threadsafe() > 0;
 #endif
     /* sqlite connections prior to 3.5 may be used by a single thread only */
     return FALSE;
 }
METHOD (database_t , query , enumerator_t * , private_sqlite_database_t * this, char * sql, ...)
Definition at line 256 of file sqlite_database.c.
References sqlite_enumerator_t::columns, sqlite_enumerator_t::count, sqlite_enumerator_t::database, enumerator_t::destroy, enumerator_t::enumerate, is_threadsave(), mutex_t::lock, malloc(), malloc_thing, mutex, sqlite_enumerator_t::public, run(), sqlite_enumerator_destroy(), sqlite_enumerator_enumerate(), and sqlite_enumerator_t::stmt.
 {
     sqlite3_stmt *stmt;
     va_list args;
     sqlite_enumerator_t *enumerator = NULL;
     int i;
     if (!is_threadsave())
     {
         this->mutex->lock(this->mutex);
     }
     va_start(args, sql);
     stmt = run(this, sql, &args);
     if (stmt)
     {
         enumerator = malloc_thing(sqlite_enumerator_t);
         enumerator->public.enumerate = (void*)sqlite_enumerator_enumerate;
         enumerator->public.destroy = (void*)sqlite_enumerator_destroy;
         enumerator->stmt = stmt;
         enumerator->count = sqlite3_column_count(stmt);
         enumerator->columns = malloc(sizeof(db_type_t) * enumerator->count);
         enumerator->database = this;
         for (i = 0; i < enumerator->count; i++)
         {
             enumerator->columns[i] = va_arg(args, db_type_t);
         }
     }
     va_end(args);
     return (enumerator_t*)enumerator;
 }
METHOD (database_t , execute , int , private_sqlite_database_t * this, int * rowid, char * sql, ...)
Definition at line 289 of file sqlite_database.c.
References db, DBG1, DBG_LIB, mutex_t::lock, mutex, run(), and mutex_t::unlock.
 {
     sqlite3_stmt *stmt;
     int affected = -1;
     va_list args;
     /* we need a lock to get our rowid/changes correctly */
     this->mutex->lock(this->mutex);
     va_start(args, sql);
     stmt = run(this, sql, &args);
     va_end(args);
     if (stmt)
     {
         if (sqlite3_step(stmt) == SQLITE_DONE)
         {
             if (rowid)
             {
                 *rowid = sqlite3_last_insert_rowid(this->db);
             }
             affected = sqlite3_changes(this->db);
         }
         else
         {
             DBG1(DBG_LIB, "sqlite execute failed: %s",
                  sqlite3_errmsg(this->db));
         }
         sqlite3_finalize(stmt);
     }
     this->mutex->unlock(this->mutex);
     return affected;
 }
METHOD (database_t , transaction , bool , private_sqlite_database_t * this, bool serializable)
Definition at line 322 of file sqlite_database.c.
References cmd, FALSE, INIT, ref_get(), transaction_t::refs, and TRUE.
 {
     transaction_t *trans;
     char *cmd = serializable ? "BEGIN EXCLUSIVE TRANSACTION"
                              : "BEGIN TRANSACTION";
     trans = this->transaction->get(this->transaction);
     if (trans)
     {
         ref_get(&trans->refs);
         return TRUE;
     }
     if (execute(this, NULL, cmd) == -1)
     {
         return FALSE;
     }
     INIT(trans,
         .refs = 1,
     );
     this->transaction->set(this->transaction, trans);
     return TRUE;
 }
METHOD (database_t , commit_ , bool , private_sqlite_database_t * this)
Definition at line 383 of file sqlite_database.c.
References FALSE, and finalize_transaction().
 {
     return finalize_transaction(this, FALSE);
 }
METHOD (database_t , rollback , bool , private_sqlite_database_t * this)
Definition at line 389 of file sqlite_database.c.
References finalize_transaction(), and TRUE.
 {
     return finalize_transaction(this, TRUE);
 }
METHOD (database_t , get_driver , db_driver_t , private_sqlite_database_t * this)
Definition at line 395 of file sqlite_database.c.
References DB_SQLITE.
 {
     return DB_SQLITE;
 }
METHOD (database_t , destroy , void , private_sqlite_database_t * this)
Definition at line 412 of file sqlite_database.c.
References db, DBG1, DBG_LIB, mutex_t::destroy, free(), and mutex.
 {
     if (sqlite3_close(this->db) == SQLITE_BUSY)
     {
         DBG1(DBG_LIB, "sqlite close failed because database is busy");
     }
     this->transaction->destroy(this->transaction);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static sqlite3_stmt* run (private_sqlite_database_t * this, char * sql, va_list * args) static
Create and run a sqlite stmt using a sql string and args
Definition at line 86 of file sqlite_database.c.
References c, db, DB_BLOB, DB_DOUBLE, DB_INT, DB_NULL, DB_TEXT, DB_UINT, DBG1, DBG_LIB, chunk_t::len, params, chunk_t::ptr, and res.
Referenced by METHOD().
 {
     sqlite3_stmt *stmt = NULL;
     int params, i, res = SQLITE_OK;
 #ifdef HAVE_SQLITE3_PREPARE_V2
     if (sqlite3_prepare_v2(this->db, sql, -1, &stmt, NULL) == SQLITE_OK)
 #else
     if (sqlite3_prepare(this->db, sql, -1, &stmt, NULL) == SQLITE_OK)
 #endif
     {
         params = sqlite3_bind_parameter_count(stmt);
         for (i = 1; i <= params; i++)
         {
             switch (va_arg(*args, db_type_t))
             {
                 case DB_INT:
                 {
                     res = sqlite3_bind_int(stmt, i, va_arg(*args, int));
                     break;
                 }
                 case DB_UINT:
                 {
                     res = sqlite3_bind_int64(stmt, i, va_arg(*args, u_int));
                     break;
                 }
                 case DB_TEXT:
                 {
                     const char *text = va_arg(*args, const char*);
                     res = sqlite3_bind_text(stmt, i, text, -1,
                                             SQLITE_TRANSIENT);
                     break;
                 }
                 case DB_BLOB:
                 {
                     chunk_t c = va_arg(*args, chunk_t);
                     res = sqlite3_bind_blob(stmt, i, c.ptr, c.len,
                                             SQLITE_TRANSIENT);
                     break;
                 }
                 case DB_DOUBLE:
                 {
                     res = sqlite3_bind_double(stmt, i, va_arg(*args, double));
                     break;
                 }
                 case DB_NULL:
                 {
                     res = sqlite3_bind_null(stmt, i);
                     break;
                 }
                 default:
                 {
                     res = SQLITE_MISUSE;
                     break;
                 }
             }
             if (res != SQLITE_OK)
             {
                 break;
             }
         }
     }
     else
     {
         DBG1(DBG_LIB, "preparing sqlite statement failed: %s",
              sqlite3_errmsg(this->db));
     }
     if (res != SQLITE_OK)
     {
         DBG1(DBG_LIB, "binding sqlite statement failed: %s",
              sqlite3_errmsg(this->db));
         sqlite3_finalize(stmt);
         return NULL;
     }
     return stmt;
 }
static void sqlite_enumerator_destroy (sqlite_enumerator_t * this) static
destroy a sqlite enumerator
Definition at line 180 of file sqlite_database.c.
References free(), and is_threadsave().
Referenced by METHOD().
 {
     sqlite3_finalize(this->stmt);
     if (!is_threadsave())
     {
         this->database->mutex->unlock(this->database->mutex);
     }
     free(this->columns);
     free(this);
 }
static bool sqlite_enumerator_enumerate (sqlite_enumerator_t * this, ...) static
Implementation of database.query().enumerate
Definition at line 194 of file sqlite_database.c.
References count, DB_BLOB, DB_DOUBLE, DB_INT, DB_TEXT, DB_UINT, DBG1, DBG_LIB, FALSE, chunk_t::len, chunk_t::ptr, TRUE, and value.
Referenced by METHOD().
 {
     int i;
     va_list args;
     switch (sqlite3_step(this->stmt))
     {
         case SQLITE_ROW:
             break;
         default:
             DBG1(DBG_LIB, "stepping sqlite statement failed: %s",
                  sqlite3_errmsg(this->database->db));
             /* fall */
         case SQLITE_DONE:
             return FALSE;
     }
     va_start(args, this);
     for (i = 0; i < this->count; i++)
     {
         switch (this->columns[i])
         {
             case DB_INT:
             {
                 int *value = va_arg(args, int*);
                 *value = sqlite3_column_int(this->stmt, i);
                 break;
             }
             case DB_UINT:
             {
                 u_int *value = va_arg(args, u_int*);
                 *value = (u_int)sqlite3_column_int64(this->stmt, i);
                 break;
             }
             case DB_TEXT:
             {
                 const unsigned char **value = va_arg(args, const unsigned char**);
                 *value = sqlite3_column_text(this->stmt, i);
                 break;
             }
             case DB_BLOB:
             {
                 chunk_t *chunk = va_arg(args, chunk_t*);
                 chunk->len = sqlite3_column_bytes(this->stmt, i);
                 chunk->ptr = (u_char*)sqlite3_column_blob(this->stmt, i);
                 break;
             }
             case DB_DOUBLE:
             {
                 double *value = va_arg(args, double*);
                 *value = sqlite3_column_double(this->stmt, i);
                 break;
             }
             default:
                 DBG1(DBG_LIB, "invalid result type supplied");
                 va_end(args);
                 return FALSE;
         }
     }
     va_end(args);
     return TRUE;
 }