strongSwan: coupling_plugin.c File Reference
coupling_plugin.c File Reference
#include "coupling_plugin.h"
#include "coupling_validator.h"
#include <daemon.h>
Classes
struct private_coupling_plugin_t
Typedefs
typedef struct
private_coupling_plugin_t private_coupling_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_coupling_plugin_t *this)
static bool plugin_cb (private_coupling_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_coupling_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_coupling_plugin_t *this)
plugin_t * coupling_plugin_create ()
Typedef Documentation
typedef struct private_coupling_plugin_t private_coupling_plugin_t
Definition at line 22 of file coupling_plugin.c.
Function Documentation
plugin_t* coupling_plugin_create ()
Plugin constructor
Definition at line 94 of file coupling_plugin.c.
References INIT.
 {
     private_coupling_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_coupling_plugin_t * this)
Definition at line 40 of file coupling_plugin.c.
 {
     return "coupling";
 }
METHOD (plugin_t , get_features , int , private_coupling_plugin_t * this, plugin_feature_t * features[])
Definition at line 73 of file coupling_plugin.c.
References countof, HASH_SHA1, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_PROVIDE, and PLUGIN_SDEPEND.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "coupling"),
                 PLUGIN_SDEPEND(HASHER, HASH_SHA1),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_coupling_plugin_t * this)
Definition at line 85 of file coupling_plugin.c.
References free().
 {
     free(this);
 }
static bool plugin_cb (private_coupling_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Since the validator instantiates a hasher we create it as plugin feature. The default is SHA1 which we soft depend but depending on the plugin order there is no guarantee that the configured algorithm is registered.
Definition at line 51 of file coupling_plugin.c.
References credential_manager_t::add_validator, coupling_validator_create(), library_t::credmgr, FALSE, lib, credential_manager_t::remove_validator, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->validator = coupling_validator_create();
         if (!this->validator)
         {
             return FALSE;
         }
         lib->credmgr->add_validator(lib->credmgr, &this->validator->validator);
     }
     else
     {
         lib->credmgr->remove_validator(lib->credmgr,
                                        &this->validator->validator);
         this->validator->destroy(this->validator);
     }
     return TRUE;
 }