strongSwan: vici_dispatcher
vici_dispatcher
vici
Classes
struct vici_dispatcher_t
Macros
#define VICI_DEFAULT_URI "unix://" IPSEC_PIDDIR "/charon.vici"
Typedefs
typedef struct vici_dispatcher_t vici_dispatcher_t
typedef enum vici_operation_t vici_operation_t
typedef vici_message_t *(* vici_command_cb_t)(void *user, char *name, u_int id, vici_message_t *request)
Enumerations
enum vici_operation_t {
VICI_CMD_REQUEST, VICI_CMD_RESPONSE, VICI_CMD_UNKNOWN, VICI_EVENT_REGISTER,
VICI_EVENT_UNREGISTER, VICI_EVENT_CONFIRM, VICI_EVENT_UNKNOWN, VICI_EVENT
}
Functions
vici_dispatcher_t * vici_dispatcher_create (char *uri)
Detailed Description
Macro Definition Documentation
#define VICI_DEFAULT_URI "unix://" IPSEC_PIDDIR "/charon.vici"
Default socket URI of vici service
Definition at line 57 of file vici_dispatcher.h.
Referenced by register_vici(), and vici_connect().
Typedef Documentation
typedef vici_message_t*(* vici_command_cb_t)(void *user, char *name, u_int id, vici_message_t *request)
Vici command callback function
Parameters
user user data, as supplied during registration
name name of the command it has been registered under
id client connection identifier
request request message data
Returns
response message
Definition at line 91 of file vici_dispatcher.h.
typedef struct vici_dispatcher_t vici_dispatcher_t
Definition at line 48 of file vici_dispatcher.h.
typedef enum vici_operation_t vici_operation_t
Definition at line 49 of file vici_dispatcher.h.
Enumeration Type Documentation
enum vici_operation_t
Kind of vici operation
Enumerator
VICI_CMD_REQUEST
a named request message
VICI_CMD_RESPONSE
an unnamed response message to a request
VICI_CMD_UNKNOWN
unnamed response if requested command is unknown
VICI_EVENT_REGISTER
a named event registration request
VICI_EVENT_UNREGISTER
a named event unregistration request
VICI_EVENT_CONFIRM
unnamed response for successful event (un-)registration
VICI_EVENT_UNKNOWN
unnamed response if event (un-)registration failed
VICI_EVENT
a named event message
Definition at line 63 of file vici_dispatcher.h.
                       {
     VICI_CMD_REQUEST,
     VICI_CMD_RESPONSE,
     VICI_CMD_UNKNOWN,
     VICI_EVENT_REGISTER,
     VICI_EVENT_UNREGISTER,
     VICI_EVENT_CONFIRM,
     VICI_EVENT_UNKNOWN,
     VICI_EVENT,
 };
Function Documentation
vici_dispatcher_t* vici_dispatcher_create (char * uri)
Create a vici_dispatcher instance.
Parameters
uri uri for listening stream service
Returns
dispatcher instance
See header
Definition at line 539 of file vici_dispatcher.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, connect_(), destroy(), disconnect(), hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), INIT, mutex_create(), MUTEX_TYPE_DEFAULT, socket, and vici_socket_create().
Referenced by register_vici(), and START_TEST().
 {
     private_vici_dispatcher_t *this;
     INIT(this,
         .public = {
             .manage_command = _manage_command,
             .manage_event = _manage_event,
             .has_event_listeners = _has_event_listeners,
             .raise_event = _raise_event,
             .destroy = _destroy,
         },
         .cmds = hashtable_create(hashtable_hash_str, hashtable_equals_str, 1),
         .events = hashtable_create(hashtable_hash_str, hashtable_equals_str, 1),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .cond = condvar_create(CONDVAR_TYPE_DEFAULT),
     );
     this->socket = vici_socket_create(uri, inbound, connect_, disconnect, this);
     if (!this->socket)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }