strongSwan: acert_validator.c File Reference
acert_validator.c File Reference
#include <library.h>
#include "acert_validator.h"
#include <credentials/certificates/x509.h>
#include <credentials/certificates/ac.h>
Classes
struct private_acert_validator_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_acert_validator_t private_acert_validator_t
Functions
static bool verify (private_acert_validator_t *this, certificate_t *ac)
static void apply (private_acert_validator_t *this, ac_t *ac, auth_cfg_t *auth)
METHOD (cert_validator_t, validate, bool, private_acert_validator_t *this, certificate_t *subject, certificate_t *issuer, bool online, u_int pathlen, bool anchor, auth_cfg_t *auth)
METHOD (acert_validator_t, destroy, void, private_acert_validator_t *this)
acert_validator_t * acert_validator_create ()
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file acert_validator.c.
Typedef Documentation
typedef struct private_acert_validator_t private_acert_validator_t
Definition at line 24 of file acert_validator.c.
Function Documentation
static void apply (private_acert_validator_t * this, ac_t * ac, auth_cfg_t * auth) static
Apply AC group membership to auth config
Definition at line 73 of file acert_validator.c.
References AC_GROUP_TYPE_STRING, auth_cfg_t::add, AUTH_RULE_GROUP, ac_t::create_group_enumerator, enumerator_t::destroy, enumerator_t::enumerate, identification_create_from_data(), and type.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     ac_group_type_t type;
     chunk_t chunk;
     enumerator = ac->create_group_enumerator(ac);
     while (enumerator->enumerate(enumerator, &type, &chunk))
     {
         if (type == AC_GROUP_TYPE_STRING)
         {
             auth->add(auth, AUTH_RULE_GROUP,
                       identification_create_from_data(chunk));
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (cert_validator_t , validate , bool , private_acert_validator_t * this, certificate_t * subject, certificate_t * issuer, bool online, u_int pathlen, bool anchor, auth_cfg_t * auth)
Definition at line 91 of file acert_validator.c.
References apply(), CERT_X509, CERT_X509_AC, ac_t::certificate, credential_manager_t::create_cert_enumerator, library_t::credmgr, identification_t::destroy, identification_t::equals, FALSE, ac_t::get_holderIssuer, certificate_t::get_issuer, x509_t::get_serial, certificate_t::get_type, id, ID_KEY_ID, identification_create_from_encoding(), KEY_ANY, lib, TRUE, and verify().
 {
     /* for X.509 end entity certs only */
     if (pathlen == 0 && subject->get_type(subject) == CERT_X509)
     {
         x509_t *x509 = (x509_t*)subject;
         enumerator_t *enumerator;
         identification_t *id, *serial;
         ac_t *ac;
         /* find attribute certificates by serial and issuer. A lookup by
          * the holder DN would work as well, but RFC 5755 recommends the use
          * of baseCertificateID. */
         serial = identification_create_from_encoding(ID_KEY_ID,
                                                      x509->get_serial(x509));
         enumerator = lib->credmgr->create_cert_enumerator(lib->credmgr,
                                         CERT_X509_AC, KEY_ANY, serial, FALSE);
         while (enumerator->enumerate(enumerator, &ac))
         {
             id = ac->get_holderIssuer(ac);
             if (id && id->equals(id, subject->get_issuer(subject)))
             {
                 if (verify(this, &ac->certificate))
                 {
                     apply(this, ac, auth);
                 }
             }
         }
         enumerator->destroy(enumerator);
         serial->destroy(serial);
     }
     return TRUE;
 }
METHOD (acert_validator_t , destroy , void , private_acert_validator_t * this)
Definition at line 128 of file acert_validator.c.
References free().
 {
     free(this);
 }
static bool verify (private_acert_validator_t * this, certificate_t * ac) static
Check if an AC can be trusted
Definition at line 40 of file acert_validator.c.
References credential_manager_t::create_trusted_enumerator, library_t::credmgr, DBG1, DBG_CFG, FALSE, certificate_t::get_issuer, certificate_t::get_validity, credential_manager_t::issued_by, KEY_ANY, lib, and TRUE.
Referenced by METHOD().
 {
     certificate_t *issuer;
     enumerator_t *enumerator;
     bool verified = FALSE;
     if (!ac->get_validity(ac, NULL, NULL, NULL))
     {
         return FALSE;
     }
     DBG1(DBG_CFG, "verifying attribute certificate issued by \"%Y\"",
          ac->get_issuer(ac));
     enumerator = lib->credmgr->create_trusted_enumerator(lib->credmgr, KEY_ANY,
                                                     ac->get_issuer(ac), TRUE);
     while (enumerator->enumerate(enumerator, &issuer, NULL))
     {
         if (issuer->get_validity(issuer, NULL, NULL, NULL))
         {
             if (lib->credmgr->issued_by(lib->credmgr, ac, issuer, NULL))
             {
                 verified = TRUE;
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     return verified;
 }