strongSwan: blowfish_crypter.c File Reference
blowfish_crypter.c File Reference
#include "blowfish.h"
#include "blowfish_crypter.h"
Classes
struct private_blowfish_crypter_t
Typedefs
typedef struct
private_blowfish_crypter_t private_blowfish_crypter_t
Functions
METHOD (crypter_t, decrypt, bool, private_blowfish_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *decrypted)
METHOD (crypter_t, encrypt, bool, private_blowfish_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *encrypted)
METHOD (crypter_t, get_block_size, size_t, private_blowfish_crypter_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_blowfish_crypter_t *this)
METHOD (crypter_t, get_key_size, size_t, private_blowfish_crypter_t *this)
METHOD (crypter_t, set_key, bool, private_blowfish_crypter_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_blowfish_crypter_t *this)
blowfish_crypter_t * blowfish_crypter_create (encryption_algorithm_t algo, size_t key_size)
Typedef Documentation
typedef struct private_blowfish_crypter_t private_blowfish_crypter_t
Definition at line 67 of file blowfish_crypter.c.
Function Documentation
METHOD (crypter_t , decrypt , bool , private_blowfish_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * decrypted)
Definition at line 90 of file blowfish_crypter.c.
References BF_cbc_encrypt(), chunk_alloc, chunk_clone, free(), in, chunk_t::len, out, chunk_t::ptr, and TRUE.
 {
     u_int8_t *in, *out;
     if (decrypted)
     {
         *decrypted = chunk_alloc(data.len);
         out = decrypted->ptr;
     }
     else
     {
         out = data.ptr;
     }
     in = data.ptr;
     iv = chunk_clone(iv);
     BF_cbc_encrypt(in, out, data.len, &this->schedule, iv.ptr, 0);
     free(iv.ptr);
     return TRUE;
 }
METHOD (crypter_t , encrypt , bool , private_blowfish_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * encrypted)
Definition at line 115 of file blowfish_crypter.c.
References BF_cbc_encrypt(), chunk_alloc, chunk_clone, free(), in, chunk_t::len, out, chunk_t::ptr, and TRUE.
 {
     u_int8_t *in, *out;
     if (encrypted)
     {
         *encrypted = chunk_alloc(data.len);
         out = encrypted->ptr;
     }
     else
     {
         out = data.ptr;
     }
     in = data.ptr;
     iv = chunk_clone(iv);
     BF_cbc_encrypt(in, out, data.len, &this->schedule, iv.ptr, 1);
     free(iv.ptr);
     return TRUE;
 }
METHOD (crypter_t , get_block_size , size_t , private_blowfish_crypter_t * this)
Definition at line 140 of file blowfish_crypter.c.
References BLOWFISH_BLOCK_SIZE.
 {
     return BLOWFISH_BLOCK_SIZE;
 }
METHOD (crypter_t , get_iv_size , size_t , private_blowfish_crypter_t * this)
Definition at line 146 of file blowfish_crypter.c.
References BLOWFISH_BLOCK_SIZE.
 {
     return BLOWFISH_BLOCK_SIZE;
 }
METHOD (crypter_t , get_key_size , size_t , private_blowfish_crypter_t * this)
Definition at line 152 of file blowfish_crypter.c.
References key_size.
 {
     return this->key_size;
 }
METHOD (crypter_t , set_key , bool , private_blowfish_crypter_t * this, chunk_t key)
Definition at line 158 of file blowfish_crypter.c.
References BF_set_key(), chunk_t::len, chunk_t::ptr, schedule(), and TRUE.
 {
     BF_set_key(&this->schedule, key.len , key.ptr);
     return TRUE;
 }
METHOD (crypter_t , destroy , void , private_blowfish_crypter_t * this)
Definition at line 165 of file blowfish_crypter.c.
References free(), and memwipe().
 {
     memwipe(this, sizeof(*this));
     free(this);
 }