strongSwan: pkcs11_creds.c File Reference
pkcs11_creds.c File Reference
#include "pkcs11_creds.h"
#include "pkcs11_manager.h"
#include <utils/debug.h>
#include <collections/linked_list.h>
Classes
struct private_pkcs11_creds_t
Typedefs
typedef struct
private_pkcs11_creds_t private_pkcs11_creds_t
Functions
static void find_certificates (private_pkcs11_creds_t *this, CK_SESSION_HANDLE session)
static bool load_certificates (private_pkcs11_creds_t *this)
static bool certs_filter (identification_t *id, certificate_t **in, certificate_t **out)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_pkcs11_creds_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (pkcs11_creds_t, get_library, pkcs11_library_t *, private_pkcs11_creds_t *this)
METHOD (pkcs11_creds_t, get_slot, CK_SLOT_ID, private_pkcs11_creds_t *this)
METHOD (pkcs11_creds_t, destroy, void, private_pkcs11_creds_t *this)
pkcs11_creds_t * pkcs11_creds_create (pkcs11_library_t *p11, CK_SLOT_ID slot)
certificate_t * pkcs11_creds_load (certificate_type_t type, va_list args)
Typedef Documentation
typedef struct private_pkcs11_creds_t private_pkcs11_creds_t
Definition at line 22 of file pkcs11_creds.c.
Function Documentation
static bool certs_filter (identification_t * id, certificate_t ** in, certificate_t ** out) static
filter function for certs enumerator
Definition at line 159 of file pkcs11_creds.c.
References cert, public_key_t::destroy, FALSE, identification_t::get_encoding, certificate_t::get_public_key, certificate_t::has_subject, in, public, and TRUE.
Referenced by METHOD().
 {
     public_key_t *public;
     certificate_t *cert = *in;
     if (id == NULL || cert->has_subject(cert, id))
     {
         *out = *in;
         return TRUE;
     }
     public = cert->get_public_key(cert);
     if (public)
     {
         if (public->has_fingerprint(public, id->get_encoding(id)))
         {
             public->destroy(public);
             *out = *in;
             return TRUE;
         }
         public->destroy(public);
     }
     return FALSE;
 }
static void find_certificates (private_pkcs11_creds_t * this, CK_SESSION_HANDLE session) static
Find certificates, optionally trusted
Definition at line 58 of file pkcs11_creds.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, chunk_clone, chunk_create(), CKA_CERTIFICATE_TYPE, CKA_CLASS, CKA_LABEL, CKA_TRUSTED, CKA_VALUE, CKC_X_509, CKO_CERTIFICATE, count, countof, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_CFG, linked_list_t::destroy, free(), certificate_t::get_ref, linked_list_t::insert_last, lib, linked_list_create(), malloc(), PKCS11_TRUSTED_CERTS, linked_list_t::remove_first, SUCCESS, TRUE, type, and value.
Referenced by load_certificates().
 {
     CK_OBJECT_CLASS class = CKO_CERTIFICATE;
     CK_CERTIFICATE_TYPE type = CKC_X_509;
     CK_BBOOL trusted = TRUE;
     CK_ATTRIBUTE tmpl[] = {
         {CKA_CLASS, &class, sizeof(class)},
         {CKA_CERTIFICATE_TYPE, &type, sizeof(type)},
     };
     CK_OBJECT_HANDLE object;
     CK_ATTRIBUTE attr[] = {
         {CKA_VALUE, NULL, 0},
         {CKA_LABEL, NULL, 0},
         {CKA_TRUSTED, &trusted, sizeof(trusted)}
     };
     enumerator_t *enumerator;
     linked_list_t *raw;
     certificate_t *cert;
     struct {
         chunk_t value;
         chunk_t label;
         bool trusted;
     } *entry;
     int count = countof(attr);
     /* store result in a temporary list, avoid recursive operation */
     raw = linked_list_create();
     /* do not use trusted argument if not supported */
     if (!(this->lib->get_features(this->lib) & PKCS11_TRUSTED_CERTS))
     {
         count--;
     }
     enumerator = this->lib->create_object_enumerator(this->lib,
                                     session, tmpl, countof(tmpl), attr, count);
     while (enumerator->enumerate(enumerator, &object))
     {
         entry = malloc(sizeof(*entry));
         entry->value = chunk_clone(
                             chunk_create(attr[0].pValue, attr[0].ulValueLen));
         entry->label = chunk_clone(
                             chunk_create(attr[1].pValue, attr[1].ulValueLen));
         entry->trusted = trusted;
         raw->insert_last(raw, entry);
     }
     enumerator->destroy(enumerator);
     while (raw->remove_first(raw, (void**)&entry) == SUCCESS)
     {
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                             BUILD_BLOB_ASN1_DER, entry->value,
                             BUILD_END);
         if (cert)
         {
             DBG1(DBG_CFG, "    loaded %strusted cert '%.*s'",
                  entry->trusted ? "" : "un", (int)entry->label.len,
                  entry->label.ptr);
             /* trusted certificates are also returned as untrusted */
             this->untrusted->insert_last(this->untrusted, cert);
             if (entry->trusted)
             {
                 this->trusted->insert_last(this->trusted, cert->get_ref(cert));
             }
         }
         else
         {
             DBG1(DBG_CFG, "    loading cert '%.*s' failed",
                 (int)entry->label.len, entry->label.ptr);
         }
         free(entry->value.ptr);
         free(entry->label.ptr);
         free(entry);
     }
     raw->destroy(raw);
 }
static bool load_certificates (private_pkcs11_creds_t * this) static
Load in the certificates from the token
Definition at line 137 of file pkcs11_creds.c.
References ck_rv_names, CKF_SERIAL_SESSION, CKR_OK, DBG1, DBG_CFG, FALSE, find_certificates(), lib, and TRUE.
Referenced by pkcs11_creds_create().
 {
     CK_SESSION_HANDLE session;
     CK_RV rv;
     rv = this->lib->f->C_OpenSession(this->slot, CKF_SERIAL_SESSION,
                                      NULL, NULL, &session);
     if (rv != CKR_OK)
     {
         DBG1(DBG_CFG, "opening session failed: %N", ck_rv_names, rv);
         return FALSE;
     }
     find_certificates(this, session);
     this->lib->f->C_CloseSession(session);
     return TRUE;
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_pkcs11_creds_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 184 of file pkcs11_creds.c.
References CERT_ANY, CERT_X509, certs_filter(), and enumerator_create_filter().
 {
     enumerator_t *inner;
     if (cert != CERT_X509 && cert != CERT_ANY)
     {
         return NULL;
     }
     if (trusted)
     {
         inner = this->trusted->create_enumerator(this->trusted);
     }
     else
     {
         inner = this->untrusted->create_enumerator(this->untrusted);
     }
     return enumerator_create_filter(inner, (void*)certs_filter, id, NULL);
 }
METHOD (pkcs11_creds_t , get_library , pkcs11_library_t * , private_pkcs11_creds_t * this)
Definition at line 205 of file pkcs11_creds.c.
References lib.
 {
     return this->lib;
 }
METHOD (pkcs11_creds_t , get_slot , CK_SLOT_ID , private_pkcs11_creds_t * this)
Definition at line 211 of file pkcs11_creds.c.
 {
     return this->slot;
 }
METHOD (pkcs11_creds_t , destroy , void , private_pkcs11_creds_t * this)
Definition at line 217 of file pkcs11_creds.c.
References destroy(), and free().
 {
     this->trusted->destroy_offset(this->trusted,
                                 offsetof(certificate_t, destroy));
     this->untrusted->destroy_offset(this->untrusted,
                                 offsetof(certificate_t, destroy));
     free(this);
 }