strongSwan: test_asn1_parser.c File Reference
test_asn1_parser.c File Reference
#include "test_suite.h"
#include <asn1/asn1_parser.h>
#include <utils/chunk.h>
Classes
struct asn1_test_t
struct default_opt_test_t
Functions
static void run_parser_test (const asn1Object_t *objects, int id, asn1_test_t *test)
START_TEST (test_asn1_parser_length)
START_TEST (test_asn1_parser_loop)
START_TEST (test_asn1_parser_default)
START_TEST (test_asn1_parser_option)
END_TEST Suite * asn1_parser_suite_create ()
Variables
static const asn1Object_t octetStringObjects []
asn1_test_t length_tests []
static END_TEST const asn1Object_t loopObjects []
asn1_test_t loop_tests []
static const asn1Object_t defaultObjects []
default_opt_test_t default_tests []
static END_TEST const asn1Object_t optionObjects []
default_opt_test_t option_tests []
Function Documentation
END_TEST Suite* asn1_parser_suite_create ()
Definition at line 267 of file test_asn1_parser.c.
References countof, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("asn1_parser");
     tc = tcase_create("length");
     tcase_add_loop_test(tc, test_asn1_parser_length, 0, countof(length_tests));
     suite_add_tcase(s, tc);
     tc = tcase_create("loop");
     tcase_add_loop_test(tc, test_asn1_parser_loop, 0, countof(loop_tests));
     suite_add_tcase(s, tc);
     tc = tcase_create("default");
     tcase_add_loop_test(tc, test_asn1_parser_default, 0, countof(default_tests));
     suite_add_tcase(s, tc);
     tc = tcase_create("option");
     tcase_add_loop_test(tc, test_asn1_parser_option, 0, countof(option_tests));
     suite_add_tcase(s, tc);
     return s;
 }
static void run_parser_test (const asn1Object_t * objects, int id, asn1_test_t * test) static
Definition at line 31 of file test_asn1_parser.c.
References asn1_parser_create(), asn1_test_t::blob, ck_assert, count, asn1_test_t::count, asn1_parser_t::destroy, asn1_parser_t::iterate, parser, asn1_test_t::success, and asn1_parser_t::success.
Referenced by START_TEST().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID, count = 0;
     bool success;
     parser = asn1_parser_create(objects, test->blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         if (objectID == id)
         {
             count++;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     ck_assert(success == test->success && count == test->count);
 }
START_TEST (test_asn1_parser_length)
Definition at line 81 of file test_asn1_parser.c.
References run_parser_test().
 {
     run_parser_test(octetStringObjects, 0, &length_tests[_i]);
 }
START_TEST (test_asn1_parser_loop)
Definition at line 108 of file test_asn1_parser.c.
References run_parser_test().
 {
     run_parser_test(loopObjects, 1, &loop_tests[_i]);
 }
START_TEST (test_asn1_parser_default)
Definition at line 157 of file test_asn1_parser.c.
References asn1_parser_create(), blob, ck_assert, asn1_parser_t::destroy, asn1_parser_t::iterate, parser, and asn1_parser_t::success.
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID, i1 = 0, i2 = 0, i3 = 0;
     bool success;
     parser = asn1_parser_create(defaultObjects, default_tests[_i].blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case 2:
                 i1 = object.len ? *object.ptr : -1;
                 break;
             case 3:
                 i2 = object.len ? *object.ptr : -2;
                 break;
             case 4:
                 i3 = object.len ? *object.ptr : -3;
                 break;
             default:
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     ck_assert(success == (default_tests[_i].i1 &&
                           default_tests[_i].i2 &&
                           default_tests[_i].i3));
     ck_assert(i1 == default_tests[_i].i1 &&
               i2 == default_tests[_i].i2 &&
               i3 == default_tests[_i].i3);
 }
START_TEST (test_asn1_parser_option)
Definition at line 231 of file test_asn1_parser.c.
References asn1_parser_create(), blob, ck_assert, asn1_parser_t::destroy, asn1_parser_t::iterate, parser, and asn1_parser_t::success.
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID, i1 = 0, i2 = 0, i3 = 0;
     bool success;
     parser = asn1_parser_create(optionObjects, option_tests[_i].blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case 2:
                 i1 = *object.ptr;
                 break;
             case 5:
                 i2 = *object.ptr;
                 break;
             case 7:
                 i3 = *object.ptr;
                 break;
             default:
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     ck_assert(success);
     ck_assert(i1 == option_tests[_i].i1 &&
               i2 == option_tests[_i].i2 &&
               i3 == option_tests[_i].i3);
 }
Variable Documentation
default_opt_test_t default_tests[]
Initial value:
= {
    { -1, -2, -3, chunk_from_chars(0x30, 0x00) },
    {  1, -2, -3, chunk_from_chars(0x30, 0x05, 0xa1, 0x03, 0x02, 0x01, 0x01) },
    { -1,  2, -3, chunk_from_chars(0x30, 0x03, 0x02, 0x01, 0x02) },
    { -1, -2,  3, chunk_from_chars(0x30, 0x03, 0x83, 0x01, 0x03) },
    {  1,  2, -3, chunk_from_chars(0x30, 0x08, 0xa1, 0x03, 0x02, 0x01, 0x01,
                                               0x02, 0x01, 0x02) },
    {  1, -2,  3, chunk_from_chars(0x30, 0x08, 0xa1, 0x03, 0x02, 0x01, 0x01,
                                               0x83, 0x01, 0x03) },
    { -1,  2,  3, chunk_from_chars(0x30, 0x06, 0x02, 0x01, 0x02,
                                               0x83, 0x01, 0x03) },
    {  1,  2,  3, chunk_from_chars(0x30, 0x0b, 0xa1, 0x03, 0x02, 0x01, 0x01,
                                               0x02, 0x01, 0x02,
                                               0x83, 0x01, 0x03) },
    {  0,  0,  0, chunk_from_chars(0x30, 0x0b, 0xa1, 0x03, 0x04, 0x01, 0xaa,
                                               0x02, 0x01, 0x02,
                                               0x83, 0x01, 0x03) },
    {  1,  0,  0, chunk_from_chars(0x30, 0x0b, 0xa1, 0x03, 0x02, 0x01, 0x01,
                                               0x02, 0x05, 0x02,
                                               0x83, 0x01, 0x03) },
    {  1,  2,  0, chunk_from_chars(0x30, 0x0b, 0xa1, 0x03, 0x02, 0x01, 0x01,
                                               0x02, 0x01, 0x02,
                                               0x83, 0x02, 0x03) },
}
Definition at line 132 of file test_asn1_parser.c.
const asn1Object_t defaultObjects[] static
Initial value:
= {
    { 0, "defaultObjects",  ASN1_SEQUENCE,      ASN1_OBJ            },
    { 1,   "explicit int1", ASN1_CONTEXT_C_1,   ASN1_DEF            },
    { 2,     "int1",        ASN1_INTEGER,       ASN1_BODY           },
    { 1,   "int2",          ASN1_INTEGER,       ASN1_DEF|ASN1_BODY  },
    { 1,   "implicit int3", ASN1_CONTEXT_S_3,   ASN1_DEF|ASN1_BODY  },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT           }
}
Definition at line 123 of file test_asn1_parser.c.
asn1_test_t length_tests[]
Initial value:
= {
    { FALSE, 0, { NULL, 0 } },
    { FALSE, 0, chunk_from_chars(0x04) },
    { TRUE,  1, chunk_from_chars(0x04, 0x00) },
    { TRUE,  1, chunk_from_chars(0x04, 0x01, 0xaa) },
    { FALSE, 0, chunk_from_chars(0x04, 0x7f) },
    { FALSE, 0, chunk_from_chars(0x04, 0x80) },
    { FALSE, 0, chunk_from_chars(0x04, 0x81) },
    { TRUE,  1, chunk_from_chars(0x04, 0x81, 0x00) },
    { FALSE, 0, chunk_from_chars(0x04, 0x81, 0x01) },
    { TRUE,  1, chunk_from_chars(0x04, 0x81, 0x01, 0xaa) },
    { FALSE, 0, chunk_from_chars(0x04, 0x82, 0x00, 0x01) },
    { TRUE,  1, chunk_from_chars(0x04, 0x82, 0x00, 0x01, 0xaa) },
    { FALSE, 0, chunk_from_chars(0x04, 0x83, 0x00, 0x00, 0x01) },
    { TRUE,  1, chunk_from_chars(0x04, 0x83, 0x00, 0x00, 0x01, 0xaa) },
    { FALSE, 0, chunk_from_chars(0x04, 0x84, 0x00, 0x00, 0x00, 0x01) },
    { TRUE,  1, chunk_from_chars(0x04, 0x84, 0x00, 0x00, 0x00, 0x01, 0xaa) },
}
Definition at line 62 of file test_asn1_parser.c.
asn1_test_t loop_tests[]
Initial value:
= {
    { TRUE,  0, chunk_from_chars(0x30, 0x00) },
    { FALSE, 0, chunk_from_chars(0x30, 0x02, 0x04, 0x01) },
    { TRUE,  1, chunk_from_chars(0x30, 0x03, 0x04, 0x01, 0xaa) },
    { TRUE,  2, chunk_from_chars(0x30, 0x05, 0x04, 0x01, 0xaa, 0x04, 0x00) },
    { FALSE, 1, chunk_from_chars(0x30, 0x05, 0x04, 0x01, 0xaa, 0x05, 0x00) },
    { TRUE,  3, chunk_from_chars(0x30, 0x09, 0x04, 0x01, 0xaa, 0x04, 0x00,
                                             0x04, 0x02, 0xbb, 0xcc) },
}
Definition at line 98 of file test_asn1_parser.c.
END_TEST const asn1Object_t loopObjects[] static
Initial value:
= {
    { 0, "loopObjects",     ASN1_SEQUENCE,      ASN1_LOOP },
    { 1,   "octetString",   ASN1_OCTET_STRING,  ASN1_BODY },
    { 0, "end loop",        ASN1_EOC,           ASN1_END  },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT }
}
Definition at line 91 of file test_asn1_parser.c.
const asn1Object_t octetStringObjects[] static
Initial value:
= {
    { 0, "octetString", ASN1_OCTET_STRING,  ASN1_BODY },
    { 0, "exit",        ASN1_EOC,           ASN1_EXIT }
}
Definition at line 57 of file test_asn1_parser.c.
default_opt_test_t option_tests[]
Initial value:
= {
    { 0, 0, 0, chunk_from_chars(0x30, 0x00) },
    { 1, 0, 0, chunk_from_chars(0x30, 0x05, 0x30, 0x03, 0x02, 0x01, 0x01) },
    { 0, 2, 0, chunk_from_chars(0x30, 0x03, 0x02, 0x01, 0x02) },
    { 0, 0, 3, chunk_from_chars(0x30, 0x03, 0x83, 0x01, 0x03) },
    { 1, 2, 0, chunk_from_chars(0x30, 0x08, 0x30, 0x03, 0x02, 0x01, 0x01,
                                            0x02, 0x01, 0x02) },
    { 1, 0, 3, chunk_from_chars(0x30, 0x08, 0x30, 0x03, 0x02, 0x01, 0x01,
                                            0x83, 0x01, 0x03) },
    { 0, 2, 3, chunk_from_chars(0x30, 0x06, 0x02, 0x01, 0x02,
                                            0x83, 0x01, 0x03) },
    { 1, 2, 3, chunk_from_chars(0x30, 0x0b, 0x30, 0x03, 0x02, 0x01, 0x01,
                                            0x02, 0x01, 0x02,
                                            0x83, 0x01, 0x03) },
    { 0, 2, 3, chunk_from_chars(0x30, 0x08, 0x30, 0x00,
                                            0x02, 0x01, 0x02,
                                            0x83, 0x01, 0x03) },
}
Definition at line 212 of file test_asn1_parser.c.
END_TEST const asn1Object_t optionObjects[] static
Initial value:
= {
    { 0, "optionalObjects", ASN1_SEQUENCE,      ASN1_OBJ            },
    { 1,   "sequence int1", ASN1_SEQUENCE,      ASN1_OPT            },
    { 2,     "int1",        ASN1_INTEGER,       ASN1_OPT|ASN1_BODY  },
    { 2,     "end opt",     ASN1_EOC,           ASN1_END            },
    { 1,   "end opt",       ASN1_EOC,           ASN1_END            },
    { 1,   "int2",          ASN1_INTEGER,       ASN1_OPT|ASN1_BODY  },
    { 1,   "end opt",       ASN1_EOC,           ASN1_END            },
    { 1,   "implicit int3", ASN1_CONTEXT_S_3,   ASN1_OPT|ASN1_BODY  },
    { 1,   "end opt",       ASN1_EOC,           ASN1_END            },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT           }
}
Definition at line 199 of file test_asn1_parser.c.