strongSwan: coupling_validator
coupling_validator
coupling
Classes
struct coupling_validator_t
Typedefs
typedef struct coupling_validator_t coupling_validator_t
Functions
coupling_validator_t * coupling_validator_create ()
Detailed Description
Typedef Documentation
typedef struct coupling_validator_t coupling_validator_t
Definition at line 26 of file coupling_validator.h.
Function Documentation
coupling_validator_t* coupling_validator_create ()
Create a coupling_validator instance.
See header
Definition at line 202 of file coupling_validator.c.
References alg, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_CFG, destroy(), enum_from_name, settings_t::get_int, settings_t::get_str, hash, hash_algorithm_short_names, hasher, INIT, lib, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, path, library_t::settings, and strerror.
Referenced by plugin_cb().
 {
     private_coupling_validator_t *this;
     hash_algorithm_t alg;
     char *path, *hash;
     INIT(this,
         .public = {
             .validator = {
                 .validate = _validate,
             },
             .destroy = _destroy,
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .max_couplings = lib->settings->get_int(lib->settings,
                                                 "%s.plugins.coupling.max", 1,
                                                 lib->ns),
     );
     hash = lib->settings->get_str(lib->settings,
                                   "%s.plugins.coupling.hash", "sha1", lib->ns);
     if (!enum_from_name(hash_algorithm_short_names, hash, &alg))
     {
         DBG1(DBG_CFG, "unknown coupling hash algorithm: %s", hash);
         destroy(this);
         return NULL;
     }
     this->hasher = lib->crypto->create_hasher(lib->crypto, alg);
     if (!this->hasher)
     {
         DBG1(DBG_CFG, "unsupported coupling hash algorithm: %s", hash);
         destroy(this);
         return NULL;
     }
     path = lib->settings->get_str(lib->settings,
                                   "%s.plugins.coupling.file", NULL, lib->ns);
     if (!path)
     {
         DBG1(DBG_CFG, "coupling file path unspecified");
         destroy(this);
         return NULL;
     }
     this->f = fopen(path, "a+");
     if (!this->f)
     {
         DBG1(DBG_CFG, "opening coupling file '%s' failed: %s",
              path, strerror(errno));
         destroy(this);
         return NULL;
     }
     setlinebuf(this->f);
     return &this->public;
 }