strongSwan: shared_key
shared_key
keys
Classes
struct shared_key_t
Typedefs
typedef struct shared_key_t shared_key_t
typedef enum shared_key_type_t shared_key_type_t
Enumerations
enum shared_key_type_t {
SHARED_ANY, SHARED_IKE, SHARED_EAP, SHARED_PRIVATE_KEY_PASS,
SHARED_PIN, SHARED_NT_HASH
}
Functions
shared_key_t * shared_key_create (shared_key_type_t type, chunk_t key)
Variables
enum_name_t * shared_key_type_names
Detailed Description
Typedef Documentation
typedef struct shared_key_t shared_key_t
Definition at line 27 of file shared_key.h.
typedef enum shared_key_type_t shared_key_type_t
Definition at line 28 of file shared_key.h.
Enumeration Type Documentation
enum shared_key_type_t
Type of a shared key.
Enumerator
SHARED_ANY
wildcard for all keys
SHARED_IKE
PSK for IKE authentication
SHARED_EAP
key for a EAP authentication method
SHARED_PRIVATE_KEY_PASS
key to decrypt encrypted private keys
SHARED_PIN
PIN to unlock a smartcard
SHARED_NT_HASH
Calculated NT Hash = MD4(UTF-16LE(password))
Definition at line 33 of file shared_key.h.
{
     SHARED_ANY,
     SHARED_IKE,
     SHARED_EAP,
     SHARED_PRIVATE_KEY_PASS,
     SHARED_PIN,
     SHARED_NT_HASH,
 };
Function Documentation
shared_key_t* shared_key_create (shared_key_type_t type, chunk_t key)
A simple private key implementation
Parameters
type type of the shared key
key key data, gets owned by instance
Returns
simple shared key instance
Definition at line 86 of file shared_key.c.
References INIT, key, and type.
Referenced by CALLBACK(), callback_shared(), cb(), decrypt_with_config(), initiate_connection(), load_from_file(), load_pin(), load_shared(), load_tester_creds_create(), main(), METHOD(), passphrase_cb(), pin_cb(), process_ike_add(), setup_tunnel(), and shared_cb().
 {
     private_shared_key_t *this;
     INIT(this,
         .public = {
             .get_type = _get_type,
             .get_key = _get_key,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .type = type,
         .key = key,
         .ref = 1,
     );
     return &this->public;
 }
Variable Documentation
enum_name_t* shared_key_type_names
enum names for shared_key_type_t
Referenced by CALLBACK(), load_shared(), and METHOD().