strongSwan: imv_lang_string
imv_lang_string
imv
Classes
struct imv_lang_string_t
Typedefs
typedef struct imv_lang_string_t imv_lang_string_t
Functions
char * imv_lang_string_select_lang (enumerator_t *language_enumerator, char *languages[], int lang_count)
char * imv_lang_string_select_string (imv_lang_string_t lang_string[], char *lang)
Detailed Description
Typedef Documentation
typedef struct imv_lang_string_t imv_lang_string_t
Definition at line 28 of file imv_lang_string.h.
Function Documentation
char* imv_lang_string_select_lang (enumerator_t * language_enumerator, char * languages[], int lang_count)
Select the preferred language
Parameters
language_enumerator enumerator over user preferred languages
languages string array of available languages
lang_count number of available languages
Returns
selected language as a language code
Described in header.
Definition at line 23 of file imv_lang_string.c.
References enumerator_t::enumerate, FALSE, match(), streq(), and TRUE.
Referenced by METHOD().
 {
     bool match = FALSE;
     char *lang;
     int i, i_chosen = 0;
     while (language_enumerator->enumerate(language_enumerator, &lang))
     {
         for (i = 0; i < lang_count; i++)
         {
             if (streq(lang, languages[i]))
             {
                 match = TRUE;
                 i_chosen = i;
                 break;
             }
         }
         if (match)
         {
             break;
         }
     }
     return languages[i_chosen];
 }
char* imv_lang_string_select_string (imv_lang_string_t lang_string[], char * lang)
Select the preferred language string
Parameters
lang_string multi-lingual array of strings
lang language code of preferred language
Returns
selected string
Described in header.
Definition at line 52 of file imv_lang_string.c.
References streq(), string, and string.
Referenced by METHOD().
 {
     char *string;
     int i = 0;
     if (!lang_string)
     {
         return NULL;
     }
     string = lang_string[0].string;
     while (lang_string[i].lang)
     {
         if (streq(lang, lang_string[i].lang))
         {
             string = lang_string[i].string;
             break;
         }
         i++;
     }
     return string;
 }