strongSwan: pgp_utils.c File Reference
pgp_utils.c File Reference
#include "pgp_utils.h"
#include <utils/debug.h>
Functions
ENUM_BEGIN (pgp_pubkey_alg_names, PGP_PUBKEY_ALG_RSA, PGP_PUBKEY_ALG_RSA_SIGN_ONLY,"RSA","RSA_ENC_ONLY","RSA_SIGN_ONLY")
ENUM_NEXT (pgp_pubkey_alg_names, PGP_PUBKEY_ALG_ELGAMAL_ENC_ONLY, PGP_PUBKEY_ALG_DIFFIE_HELLMAN, PGP_PUBKEY_ALG_RSA_SIGN_ONLY,"ELGAMAL_ENC_ONLY","DSA","ECC","ECDSA","ELGAMAL","DIFFIE_HELLMAN")
ENUM_END (pgp_pubkey_alg_names, PGP_PUBKEY_ALG_DIFFIE_HELLMAN)
ENUM (pgp_sym_alg_names, PGP_SYM_ALG_PLAIN, PGP_SYM_ALG_TWOFISH,"PLAINTEXT","IDEA","3DES","CAST5","BLOWFISH","SAFER","DES","AES_128","AES_192","AES_256","TWOFISH")
ENUM_BEGIN (pgp_packet_tag_names, PGP_PKT_RESERVED, PGP_PKT_PUBLIC_SUBKEY,"Reserved","Public-Key Encrypted Session Key Packet","Signature Packet","Symmetric-Key Encrypted Session Key Packet","One-Pass Signature Packet","Secret Key Packet","Public Key Packet","Secret Subkey Packet","Compressed Data Packet","Symmetrically Encrypted Data Packet","Marker Packet","Literal Data Packet","Trust Packet","User ID Packet","Public Subkey Packet")
ENUM_NEXT (pgp_packet_tag_names, PGP_PKT_USER_ATTRIBUTE, PGP_PKT_MOD_DETECT_CODE, PGP_PKT_PUBLIC_SUBKEY,"User Attribute Packet","Sym. Encrypted and Integrity Protected Data Packet","Modification Detection Code Packet")
ENUM_END (pgp_packet_tag_names, PGP_PKT_MOD_DETECT_CODE)
bool pgp_read_scalar (chunk_t *blob, size_t bytes, u_int32_t *scalar)
bool pgp_read_mpi (chunk_t *blob, chunk_t *mpi)
static bool pgp_old_packet_length (chunk_t *blob, u_int32_t *length)
bool pgp_read_packet (chunk_t *blob, chunk_t *data, pgp_packet_tag_t *tag)
Function Documentation
ENUM (pgp_sym_alg_names , PGP_SYM_ALG_PLAIN , PGP_SYM_ALG_TWOFISH , "PLAINTEXT" , "IDEA" , "3DES" , "CAST5" , "BLOWFISH" , "SAFER" , "DES" , "AES_128" , "AES_192" , "AES_256" , "TWOFISH")
ENUM_BEGIN (pgp_pubkey_alg_names , PGP_PUBKEY_ALG_RSA , PGP_PUBKEY_ALG_RSA_SIGN_ONLY , "RSA" , "RSA_ENC_ONLY" , "RSA_SIGN_ONLY")
ENUM_BEGIN (pgp_packet_tag_names , PGP_PKT_RESERVED , PGP_PKT_PUBLIC_SUBKEY , "Reserved" , "Public-Key Encrypted Session Key Packet" , "Signature Packet" , "Symmetric-Key Encrypted Session Key Packet" , "One-Pass Signature Packet" , "Secret Key Packet" , "Public Key Packet" , "Secret Subkey Packet" , "Compressed Data Packet" , "Symmetrically Encrypted Data Packet" , "Marker Packet" , "Literal Data Packet" , "Trust Packet" , "User ID Packet" , "Public Subkey Packet")
ENUM_END (pgp_pubkey_alg_names , PGP_PUBKEY_ALG_DIFFIE_HELLMAN)
ENUM_END (pgp_packet_tag_names , PGP_PKT_MOD_DETECT_CODE)
ENUM_NEXT (pgp_pubkey_alg_names , PGP_PUBKEY_ALG_ELGAMAL_ENC_ONLY , PGP_PUBKEY_ALG_DIFFIE_HELLMAN , PGP_PUBKEY_ALG_RSA_SIGN_ONLY , "ELGAMAL_ENC_ONLY" , "DSA" , "ECC" , "ECDSA" , "ELGAMAL" , "DIFFIE_HELLMAN")
ENUM_NEXT (pgp_packet_tag_names , PGP_PKT_USER_ATTRIBUTE , PGP_PKT_MOD_DETECT_CODE , PGP_PKT_PUBLIC_SUBKEY , "User Attribute Packet" , "Sym. Encrypted and Integrity Protected Data Packet" , "Modification Detection Code Packet")
static bool pgp_old_packet_length (chunk_t * blob, u_int32_t * length) static
Read length of an PGP old packet length encoding
Definition at line 120 of file pgp_utils.c.
References chunk_skip(), FALSE, chunk_t::len, pgp_read_scalar(), chunk_t::ptr, and type.
Referenced by pgp_read_packet().
 {
     /* bits 0 and 1 define the packet length type */
     u_char type;
     if (!blob->len)
     {
         return FALSE;
     }
     type = 0x03 & blob->ptr[0];
     *blob = chunk_skip(*blob, 1);
     if (type > 2)
     {
         return FALSE;
     }
     return pgp_read_scalar(blob, type == 0 ? 1 : type * 2, length);
 }