strongSwan: dnskey_encoder
dnskey_encoder
dnskey
Functions
bool dnskey_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Detailed Description
Function Documentation
bool dnskey_encoder_encode (cred_encoding_type_t type, chunk_t * encoding, va_list args)
Encoding function for DNSKEY (RFC 3110) public key format.
See header.
Definition at line 79 of file dnskey_encoder.c.
References build_pub(), FALSE, and PUBKEY_DNSKEY.
Referenced by dnskey_plugin_create(), and METHOD().
 {
     switch (type)
     {
         case PUBKEY_DNSKEY:
             return build_pub(encoding, args);
         default:
             return FALSE;
     }
 }