strongSwan: printf_hook_vstr.c File Reference
printf_hook_vstr.c File Reference
#include "printf_hook.h"
#include <utils/utils.h>
#include <utils/debug.h>
#include <threading/thread_value.h>
#include <vstr.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
Classes
struct private_printf_hook_t
struct printf_hook_handler_t
struct printf_hook_data_t
Macros
#define PRINTF_BUF_LEN 8192
#define ARGS_MAX 3
#define SPEC_TO_INDEX(spec) ((int)(spec) - (int)'A')
Typedefs
typedef struct
private_printf_hook_t private_printf_hook_t
typedef struct
printf_hook_handler_t printf_hook_handler_t
Functions
size_t print_in_hook (printf_hook_data_t *data, char *fmt,...)
static int custom_fmt_cb (Vstr_base *base, size_t pos, Vstr_fmt_spec *fmt_spec)
static void vstr_fmt_add_handler (Vstr_conf *conf, printf_hook_handler_t *handler)
static Vstr_conf * create_vstr_conf ()
static Vstr_conf * get_vstr_conf ()
int vstr_wrapper_printf (const char *format,...)
int vstr_wrapper_fprintf (FILE *stream, const char *format,...)
int vstr_wrapper_sprintf (char *str, const char *format,...)
int vstr_wrapper_snprintf (char *str, size_t size, const char *format,...)
int vstr_wrapper_asprintf (char **str, const char *format,...)
static int vstr_wrapper_vprintf_internal (Vstr_conf *conf, FILE *stream, const char *format, va_list args)
int vstr_wrapper_vprintf (const char *format, va_list args)
int vstr_wrapper_vfprintf (FILE *stream, const char *format, va_list args)
static int vstr_wrapper_vsnprintf_internal (char *str, size_t size, const char *format, va_list args)
int vstr_wrapper_vsprintf (char *str, const char *format, va_list args)
int vstr_wrapper_vsnprintf (char *str, size_t size, const char *format, va_list args)
int vstr_wrapper_vasprintf (char **str, const char *format, va_list args)
METHOD (printf_hook_t, add_handler, void, private_printf_hook_t *this, char spec, printf_hook_function_t hook,...)
METHOD (printf_hook_t, destroy, void, private_printf_hook_t *this)
printf_hook_t * printf_hook_create ()
Variables
static printf_hook_handler_t * printf_hooks [58]
static thread_value_t * vstr_conf = NULL
Macro Definition Documentation
#define ARGS_MAX 3
Definition at line 32 of file printf_hook_vstr.c.
Referenced by custom_fmt_cb(), and METHOD().
#define PRINTF_BUF_LEN 8192
Definition at line 31 of file printf_hook_vstr.c.
Referenced by create_vstr_conf().
#define SPEC_TO_INDEX (spec) ((int)(spec) - (int)'A')
Definition at line 90 of file printf_hook_vstr.c.
Referenced by custom_fmt_cb(), and METHOD().
Typedef Documentation
typedef struct printf_hook_handler_t printf_hook_handler_t
Definition at line 29 of file printf_hook_vstr.c.
typedef struct private_printf_hook_t private_printf_hook_t
Definition at line 28 of file printf_hook_vstr.c.
Function Documentation
static Vstr_conf* create_vstr_conf () static
Create vstr config for current thread
Definition at line 187 of file printf_hook_vstr.c.
References conf, countof, PRINTF_BUF_LEN, and vstr_fmt_add_handler().
Referenced by get_vstr_conf().
 {
     Vstr_conf *conf;
     int i;
     conf = vstr_make_conf();
     vstr_cntl_conf(conf, VSTR_CNTL_CONF_SET_FMT_CHAR_ESC, '%');
     vstr_cntl_conf(conf, VSTR_CNTL_CONF_SET_TYPE_GRPALLOC_CACHE,
                          VSTR_TYPE_CNTL_CONF_GRPALLOC_CSTR);
     vstr_cntl_conf(conf, VSTR_CNTL_CONF_SET_NUM_BUF_SZ, PRINTF_BUF_LEN);
     for (i = 0; i < countof(printf_hooks); i++)
     {
         if (printf_hooks[i])
         {
             vstr_fmt_add_handler(conf, printf_hooks[i]);
         }
     }
     return conf;
 }
static int custom_fmt_cb (Vstr_base * base, size_t pos, Vstr_fmt_spec * fmt_spec) static
Vstr custom format specifier callback function.
Definition at line 119 of file printf_hook_vstr.c.
References ARGS_MAX, printf_hook_handler_t::argtypes, base, data, printf_hook_spec_t::hash, printf_hook_handler_t::hook, printf_hook_spec_t::minus, printf_hook_handler_t::numargs, printf_hook_spec_t::plus, SPEC_TO_INDEX, and printf_hook_spec_t::width.
Referenced by vstr_fmt_add_handler().
 {
     int i;
     const void *args[ARGS_MAX];
     printf_hook_spec_t spec;
     printf_hook_handler_t *handler;
     printf_hook_data_t data = {
         .base = base,
         .pos = pos,
     };
     handler = printf_hooks[SPEC_TO_INDEX(fmt_spec->name[0])];
     for (i = 0; i < handler->numargs; i++)
     {
         switch (handler->argtypes[i])
         {
             case VSTR_TYPE_FMT_INT:
                 args[i] = VSTR_FMT_CB_ARG_PTR(fmt_spec, i);
                 break;
             case VSTR_TYPE_FMT_PTR_VOID:
                 args[i] = &VSTR_FMT_CB_ARG_PTR(fmt_spec, i);
                 break;
         }
     }
     spec.hash = fmt_spec->fmt_hash;
     spec.plus = fmt_spec->fmt_plus;
     spec.minus = fmt_spec->fmt_minus;
     spec.width = fmt_spec->obj_field_width;
     handler->hook(&data, &spec, args);
     return 1;
 }
static Vstr_conf* get_vstr_conf () inline static
Get vstr config of current thread
Definition at line 211 of file printf_hook_vstr.c.
References conf, create_vstr_conf(), thread_value_t::get, and thread_value_t::set.
Referenced by METHOD(), vstr_wrapper_vfprintf(), vstr_wrapper_vprintf(), and vstr_wrapper_vsnprintf_internal().
 {
     Vstr_conf *conf = NULL;
     if (vstr_conf)
     {
         conf = (Vstr_conf*)vstr_conf->get(vstr_conf);
         if (!conf)
         {
             conf = create_vstr_conf();
             vstr_conf->set(vstr_conf, conf);
         }
     }
     return conf;
 }
METHOD (printf_hook_t , add_handler , void , private_printf_hook_t * this, char spec, printf_hook_function_t hook, ...)
Definition at line 387 of file printf_hook_vstr.c.
References ARGS_MAX, printf_hook_handler_t::argtypes, conf, countof, DBG1, DBG_LIB, FALSE, free(), get_vstr_conf(), INIT, malloc(), printf_hook_handler_t::name, printf_hook_handler_t::numargs, PRINTF_HOOK_ARGTYPE_END, PRINTF_HOOK_ARGTYPE_INT, PRINTF_HOOK_ARGTYPE_POINTER, SPEC_TO_INDEX, TRUE, and vstr_fmt_add_handler().
 {
     int i = -1;
     bool failed = FALSE;
     printf_hook_handler_t *handler;
     printf_hook_argtype_t argtype;
     va_list args;
     if (SPEC_TO_INDEX(spec) <= -1 ||
         SPEC_TO_INDEX(spec) >= countof(printf_hooks))
     {
         DBG1(DBG_LIB, "'%c' is not a valid printf hook specifier, "
              "not registered!", spec);
         return;
     }
     INIT(handler,
         .hook = hook,
     );
     va_start(args, hook);
     while (!failed)
     {
         argtype = va_arg(args, printf_hook_argtype_t);
         if (argtype == PRINTF_HOOK_ARGTYPE_END)
         {
             break;
         }
         if (++i >= ARGS_MAX)
         {
             DBG1(DBG_LIB, "Too many arguments for printf hook with "
                  "specifier '%c', not registered!", spec);
             failed = TRUE;
             break;
         }
         switch (argtype)
         {
             case PRINTF_HOOK_ARGTYPE_INT:
                 handler->argtypes[i] = VSTR_TYPE_FMT_INT;
                 break;
             case PRINTF_HOOK_ARGTYPE_POINTER:
                 handler->argtypes[i] = VSTR_TYPE_FMT_PTR_VOID;
                 break;
             default:
                 DBG1(DBG_LIB, "Invalid printf hook arg type for '%c'", spec);
                 failed = TRUE;
                 break;
         }
     }
     va_end(args);
     handler->numargs = i + 1;
     if (!failed && handler->numargs > 0)
     {
         Vstr_conf *conf = get_vstr_conf();
         handler->name = malloc(2);
         handler->name[0] = spec;
         handler->name[1] = '\0';
         vstr_fmt_add_handler(conf, handler);
         printf_hooks[SPEC_TO_INDEX(spec)] = handler;
     }
     else
     {
         free(handler);
     }
 }
METHOD (printf_hook_t , destroy , void , private_printf_hook_t * this)
Definition at line 456 of file printf_hook_vstr.c.
References conf, countof, thread_value_t::destroy, free(), get_vstr_conf(), and printf_hook_handler_t::name.
 {
     int i;
     Vstr_conf *conf;
     printf_hook_handler_t *handler;
     conf = get_vstr_conf();
     for (i = 0; i < countof(printf_hooks); ++i)
     {
         handler = printf_hooks[i];
         if (handler)
         {
             vstr_fmt_del(conf, handler->name);
             free(handler->name);
             free(handler);
         }
     }
     /* freeing the Vstr_conf of the main thread */
     vstr_conf->destroy(vstr_conf);
     vstr_conf = NULL;
     vstr_exit();
     free(this);
 }
static void vstr_fmt_add_handler (Vstr_conf * conf, printf_hook_handler_t * handler) static
Add a custom format handler to the given Vstr_conf object
Definition at line 157 of file printf_hook_vstr.c.
References printf_hook_handler_t::argtypes, custom_fmt_cb(), printf_hook_handler_t::name, and printf_hook_handler_t::numargs.
Referenced by create_vstr_conf(), and METHOD().
 {
     int *at;
     at = handler->argtypes;
     switch (handler->numargs)
     {
         case 1:
             vstr_fmt_add(conf, handler->name, custom_fmt_cb, at[0],
                          VSTR_TYPE_FMT_END);
             break;
         case 2:
             vstr_fmt_add(conf, handler->name, custom_fmt_cb, at[0],
                          at[1], VSTR_TYPE_FMT_END);
             break;
         case 3:
             vstr_fmt_add(conf, handler->name, custom_fmt_cb, at[0],
                          at[1], at[2], VSTR_TYPE_FMT_END);
             break;
     }
 }
static int vstr_wrapper_vprintf_internal (Vstr_conf * conf, FILE * stream, const char * format, va_list args) inline static
Definition at line 280 of file printf_hook_vstr.c.
References s.
Referenced by vstr_wrapper_vfprintf(), and vstr_wrapper_vprintf().
 {
     struct iovec *iov;
     int iovcnt, written = 0;
     Vstr_base *s;
     s = vstr_make_base(conf);
     vstr_add_vfmt(s, 0, format, args);
     if (vstr_export_iovec_ptr_all(s, &iov, &iovcnt))
     {
         while (iovcnt--)
         {
             if (iov->iov_base)
             {
                 written += fwrite(iov->iov_base, 1, iov->iov_len, stream);
             }
             iov++;
         }
     }
     vstr_free_base(s);
     return written;
 }
static int vstr_wrapper_vsnprintf_internal (char * str, size_t size, const char * format, va_list args) inline static
Definition at line 329 of file printf_hook_vstr.c.
References conf, get_vstr_conf(), s, and vsnprintf.
Referenced by vstr_wrapper_vasprintf(), vstr_wrapper_vsnprintf(), and vstr_wrapper_vsprintf().
 {
     Vstr_conf *conf;
     Vstr_base *s;
     int written;
     conf = get_vstr_conf();
     if (conf)
     {
         s = vstr_make_base(conf);
         vstr_add_vfmt(s, 0, format, args);
         written = s->len;
         vstr_export_cstr_buf(s, 1, s->len, str, (size > 0) ? size : s->len + 1);
         vstr_free_base(s);
         return written;
     }
     return vsnprintf(str, size, format, args);
 }
Variable Documentation
printf_hook_handler_t* printf_hooks[58] static
Definition at line 88 of file printf_hook_vstr.c.
thread_value_t* vstr_conf = NULL static
Thread specific vstr config
Definition at line 182 of file printf_hook_vstr.c.