strongSwan: tnc_ifmap_listener
tnc_ifmap_listener
tnc_ifmap
Classes
struct tnc_ifmap_listener_t
Typedefs
typedef struct tnc_ifmap_listener_t tnc_ifmap_listener_t
Functions
tnc_ifmap_listener_t * tnc_ifmap_listener_create (bool reload)
Detailed Description
Typedef Documentation
typedef struct tnc_ifmap_listener_t tnc_ifmap_listener_t
Definition at line 26 of file tnc_ifmap_listener.h.
Function Documentation
tnc_ifmap_listener_t* tnc_ifmap_listener_create (bool reload)
Create a tnc_ifmap_listener instance.
Parameters
reload reload all IKE_SA metadata
See header
Definition at line 145 of file tnc_ifmap_listener.c.
References destroy(), settings_t::get_int, IFMAP_RENEW_SESSION_INTERVAL, INIT, lib, library_t::ns, publish_device_ip_addresses(), reload_metadata(), scheduler_t::schedule_job, library_t::scheduler, library_t::settings, tnc_ifmap_renew_session_job_create(), and tnc_ifmap_soap_create().
Referenced by METHOD(), and register_tnc_ifmap().
 {
     private_tnc_ifmap_listener_t *this;
     job_t *job;
     u_int32_t reschedule;
     INIT(this,
         .public = {
             .listener = {
                 .ike_updown = _ike_updown,
                 .assign_vips = _assign_vips,
                 .alert = _alert,
             },
             .destroy = _destroy,
         },
         .ifmap = tnc_ifmap_soap_create(),
     );
     if (!this->ifmap)
     {
         destroy(this);
         return NULL;
     }
     if (!this->ifmap->newSession(this->ifmap))
     {
         destroy(this);
         return NULL;
     }
     if (!this->ifmap->purgePublisher(this->ifmap))
     {
         destroy(this);
         return NULL;
     }
     if (!publish_device_ip_addresses(this))
     {
         destroy(this);
         return NULL;
     }
     if (reload)
     {
         if (!reload_metadata(this))
         {
             destroy(this);
             return NULL;
         }
     }
     /* schedule periodic transmission of IF-MAP renewSession request */
     reschedule =  lib->settings->get_int(lib->settings,
                                 "%s.plugins.tnc-ifmap.renew_session_interval",
                                  IFMAP_RENEW_SESSION_INTERVAL, lib->ns);
     job = (job_t*)tnc_ifmap_renew_session_job_create(
                         this->ifmap->get_ref(this->ifmap), reschedule);
     lib->scheduler->schedule_job(lib->scheduler, job, reschedule);
     return &this->public;
 }