strongSwan: pts_creds.c File Reference
pts_creds.c File Reference
#include "pts_creds.h"
#include <utils/debug.h>
#include <credentials/certificates/x509.h>
#include <credentials/sets/mem_cred.h>
#include <sys/stat.h>
Classes
struct private_pts_creds_t
Typedefs
typedef struct private_pts_creds_t private_pts_creds_t
Functions
METHOD (pts_creds_t, get_set, credential_set_t *, private_pts_creds_t *this)
METHOD (pts_creds_t, destroy, void, private_pts_creds_t *this)
static void load_cacerts (private_pts_creds_t *this, char *path)
pts_creds_t * pts_creds_create (char *path)
Typedef Documentation
typedef struct private_pts_creds_t private_pts_creds_t
Definition at line 24 of file pts_creds.c.
Function Documentation
static void load_cacerts (private_pts_creds_t * this, char * path) static
Load trusted PTS CA certificates from a directory
Definition at line 61 of file pts_creds.c.
References mem_cred_t::add_cert, BUILD_END, BUILD_FROM_FILE, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, creds, library_t::creds, DBG1, DBG_PTS, enumerator_t::destroy, certificate_t::destroy, enumerator_t::enumerate, enumerator_create_directory(), x509_t::get_flags, certificate_t::get_subject, lib, TRUE, and X509_CA.
Referenced by pts_creds_create().
 {
     enumerator_t *enumerator;
     struct stat st;
     char *file;
     DBG1(DBG_PTS, "loading PTS ca certificates from '%s'", path);
     enumerator = enumerator_create_directory(path);
     if (!enumerator)
     {
         return;
     }
     while (enumerator->enumerate(enumerator, NULL, &file, &st))
     {
         certificate_t *cert;
         if (!S_ISREG(st.st_mode))
         {
             /* skip special file */
             continue;
         }
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_FROM_FILE, file, BUILD_END);
         if (cert)
         {
             x509_t *x509 = (x509_t*)cert;
             if (!(x509->get_flags(x509) & X509_CA))
             {
                 DBG1(DBG_PTS, "  ca certificate \"%Y\" lacks ca basic constraint"
                               ", discarded", cert->get_subject(cert));
                 cert->destroy(cert);
             }
             else
             {
                 DBG1(DBG_PTS, "  loaded ca certificate \"%Y\" from '%s'",
                               cert->get_subject(cert), file);
                 this->creds->add_cert(this->creds, TRUE, cert);
             }
         }
         else
         {
             DBG1(DBG_PTS, "  loading ca certificate from '%s' failed", file);
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (pts_creds_t , get_set , credential_set_t * , private_pts_creds_t * this)
Definition at line 44 of file pts_creds.c.
References creds, and mem_cred_t::set.
 {
     return &this->creds->set;
 }
METHOD (pts_creds_t , destroy , void , private_pts_creds_t * this)
Definition at line 51 of file pts_creds.c.
References creds, mem_cred_t::destroy, and free().
 {
     this->creds->destroy(this->creds);
     free(this);
 }