strongSwan: encrypted_fragment_payload
encrypted_fragment_payload
payloads
Classes
struct encrypted_fragment_payload_t
Typedefs
typedef struct
encrypted_fragment_payload_t encrypted_fragment_payload_t
Functions
encrypted_fragment_payload_t * encrypted_fragment_payload_create ()
encrypted_fragment_payload_t * encrypted_fragment_payload_create_from_data (u_int16_t num, u_int16_t total, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct encrypted_fragment_payload_t encrypted_fragment_payload_t
Definition at line 24 of file encrypted_fragment_payload.h.
Function Documentation
encrypted_fragment_payload_t* encrypted_fragment_payload_create ()
Creates an empty encrypted_fragment_payload_t object.
Returns
encrypted_fragment_payload_t object
Definition at line 977 of file encrypted_payload.c.
References decrypt, destroy(), encrypt(), INIT, nop(), PL_NONE, and return_null().
Referenced by encrypted_fragment_payload_create_from_data(), and payload_create().
 {
     private_encrypted_fragment_payload_t *this;
     INIT(this,
         .public = {
             .encrypted = {
                 .payload_interface = {
                     .verify = _frag_verify,
                     .get_encoding_rules = _frag_get_encoding_rules,
                     .get_header_length = _frag_get_header_length,
                     .get_length = _frag_get_length,
                     .get_next_type = _frag_get_next_type,
                     .set_next_type = _frag_set_next_type,
                     .get_type = _frag_get_type,
                     .destroy = _frag_destroy,
                 },
                 .get_length = _frag_get_length,
                 .add_payload = _frag_add_payload,
                 .remove_payload = (void*)return_null,
                 .generate_payloads = nop,
                 .set_transform = _frag_set_transform,
                 .encrypt = _frag_encrypt,
                 .decrypt = _frag_decrypt,
                 .destroy = _frag_destroy,
             },
             .get_fragment_number = _get_fragment_number,
             .get_total_fragments = _get_total_fragments,
             .get_content = _frag_get_content,
         },
         .next_payload = PL_NONE,
     );
     this->payload_length = frag_get_header_length(this);
     return &this->public;
 }
encrypted_fragment_payload_t* encrypted_fragment_payload_create_from_data (u_int16_t num, u_int16_t total, chunk_t data)
Creates an encrypted fragment payload from the given data.
Parameters
num fragment number (first one should be 1)
total total number of fragments
data fragment data (gets cloned)
Returns
encrypted_fragment_payload_t object
Definition at line 1017 of file encrypted_payload.c.
References chunk_clone, and encrypted_fragment_payload_create().
Referenced by create_fragment().
 {
     private_encrypted_fragment_payload_t *this;
     this = (private_encrypted_fragment_payload_t*)encrypted_fragment_payload_create();
     this->fragment_number = num;
     this->total_fragments = total;
     this->plain = chunk_clone(plain);
     return &this->public;
 }