strongSwan: pb_tnc_msg
pb_tnc_msg
tnccs_20
Classes
struct pb_tnc_msg_info_t
struct pb_tnc_msg_t
Macros
#define PB_TNC_VERSION 2
#define TRUE_OR_FALSE 2
Typedefs
typedef enum pb_tnc_msg_type_t pb_tnc_msg_type_t
typedef struct pb_tnc_msg_info_t pb_tnc_msg_info_t
typedef struct pb_tnc_msg_t pb_tnc_msg_t
Enumerations
enum pb_tnc_msg_type_t {
PB_MSG_EXPERIMENTAL = 0, PB_MSG_PA = 1, PB_MSG_ASSESSMENT_RESULT = 2, PB_MSG_ACCESS_RECOMMENDATION = 3,
PB_MSG_REMEDIATION_PARAMETERS = 4, PB_MSG_ERROR = 5, PB_MSG_LANGUAGE_PREFERENCE = 6, PB_MSG_REASON_STRING = 7,
PB_MSG_ROOF = 7
}
enum pb_tnc_tcg_msg_type_t { PB_TCG_MSG_RESERVED = 0, PB_TCG_MSG_PDP_REFERRAL = 1, PB_TCG_MSG_ROOF = 1 }
enum pb_tnc_ita_msg_type_t { PB_ITA_MSG_NOSKIP_TEST = 0, PB_ITA_MSG_MUTUAL_CAPABILITY = 1, PB_ITA_MSG_ROOF = 1 }
Functions
pb_tnc_msg_t * pb_tnc_msg_create_from_data (pen_type_t msg_type, chunk_t value)
Variables
enum_name_t * pb_tnc_msg_type_names
enum_name_t * pb_tnc_tcg_msg_type_names
enum_name_t * pb_tnc_ita_msg_type_names
pb_tnc_msg_info_t pb_tnc_msg_infos []
pb_tnc_msg_info_t pb_tnc_tcg_msg_infos []
pb_tnc_msg_info_t pb_tnc_ita_msg_infos []
Detailed Description
Macro Definition Documentation
#define PB_TNC_VERSION 2
Definition at line 31 of file pb_tnc_msg.h.
Referenced by METHOD().
#define TRUE_OR_FALSE 2
Definition at line 91 of file pb_tnc_msg.h.
Referenced by process_tnc_msg().
Typedef Documentation
typedef struct pb_tnc_msg_info_t pb_tnc_msg_info_t
Definition at line 25 of file pb_tnc_msg.h.
typedef struct pb_tnc_msg_t pb_tnc_msg_t
Definition at line 26 of file pb_tnc_msg.h.
typedef enum pb_tnc_msg_type_t pb_tnc_msg_type_t
Definition at line 24 of file pb_tnc_msg.h.
Enumeration Type Documentation
enum pb_tnc_ita_msg_type_t
PB-TNC Message Type defined in the ITA namespace
Enumerator
PB_ITA_MSG_NOSKIP_TEST
PB_ITA_MSG_MUTUAL_CAPABILITY
PB_ITA_MSG_ROOF
Definition at line 70 of file pb_tnc_msg.h.
{
     PB_ITA_MSG_NOSKIP_TEST =            0,
     PB_ITA_MSG_MUTUAL_CAPABILITY =      1,
     PB_ITA_MSG_ROOF =                   1
 };
enum pb_tnc_msg_type_t
PB-TNC Message Types as defined in section 4.3 of RFC 5793
Enumerator
PB_MSG_EXPERIMENTAL
PB_MSG_PA
PB_MSG_ASSESSMENT_RESULT
PB_MSG_ACCESS_RECOMMENDATION
PB_MSG_REMEDIATION_PARAMETERS
PB_MSG_ERROR
PB_MSG_LANGUAGE_PREFERENCE
PB_MSG_REASON_STRING
PB_MSG_ROOF
Definition at line 36 of file pb_tnc_msg.h.
{
     PB_MSG_EXPERIMENTAL =               0,
     PB_MSG_PA =                         1,
     PB_MSG_ASSESSMENT_RESULT =          2,
     PB_MSG_ACCESS_RECOMMENDATION =      3,
     PB_MSG_REMEDIATION_PARAMETERS =     4,
     PB_MSG_ERROR =                      5,
     PB_MSG_LANGUAGE_PREFERENCE =        6,
     PB_MSG_REASON_STRING =              7,
     PB_MSG_ROOF =                       7
 };
enum pb_tnc_tcg_msg_type_t
PB-TNC Message Type defined in the TCG namespace
Enumerator
PB_TCG_MSG_RESERVED
PB_TCG_MSG_PDP_REFERRAL
PB_TCG_MSG_ROOF
Definition at line 56 of file pb_tnc_msg.h.
{
     PB_TCG_MSG_RESERVED =               0,
     PB_TCG_MSG_PDP_REFERRAL =           1,
     PB_TCG_MSG_ROOF =                   1
 };
Function Documentation
pb_tnc_msg_t* pb_tnc_msg_create_from_data (pen_type_t msg_type, chunk_t value)
Create an unprocessed PB-TNC message
Useful for the parser which wants a generic constructor for all pb_tnc_message_t types.
Parameters
msg_type PB-TNC message type
value PB-TNC message value
See header
Definition at line 76 of file pb_tnc_msg.c.
References pb_access_recommendation_msg_create_from_data(), pb_assessment_result_msg_create_from_data(), pb_error_msg_create_from_data(), pb_experimental_msg_create_from_data(), PB_ITA_MSG_MUTUAL_CAPABILITY, pb_language_preference_msg_create_from_data(), PB_MSG_ACCESS_RECOMMENDATION, PB_MSG_ASSESSMENT_RESULT, PB_MSG_ERROR, PB_MSG_EXPERIMENTAL, PB_MSG_LANGUAGE_PREFERENCE, PB_MSG_PA, PB_MSG_REASON_STRING, PB_MSG_REMEDIATION_PARAMETERS, pb_mutual_capability_msg_create_from_data(), pb_pa_msg_create_from_data(), pb_pdp_referral_msg_create_from_data(), pb_reason_string_msg_create_from_data(), pb_remediation_parameters_msg_create_from_data(), PB_TCG_MSG_PDP_REFERRAL, PEN_IETF, PEN_ITA, PEN_TCG, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by process_tnc_msg().
 {
     if (msg_type.vendor_id == PEN_IETF)
     {
         switch (msg_type.type)
         {
             case PB_MSG_PA:
                 return pb_pa_msg_create_from_data(value);
             case PB_MSG_ERROR:
                 return pb_error_msg_create_from_data(value);
             case PB_MSG_EXPERIMENTAL:
                 return pb_experimental_msg_create_from_data(value);
             case PB_MSG_LANGUAGE_PREFERENCE:
                 return pb_language_preference_msg_create_from_data(value);
             case PB_MSG_ASSESSMENT_RESULT:
                 return pb_assessment_result_msg_create_from_data(value);
             case PB_MSG_ACCESS_RECOMMENDATION:
                 return pb_access_recommendation_msg_create_from_data(value);
             case PB_MSG_REMEDIATION_PARAMETERS:
                 return pb_remediation_parameters_msg_create_from_data(value);
             case PB_MSG_REASON_STRING:
                 return pb_reason_string_msg_create_from_data(value);
         }
     }
     else if (msg_type.vendor_id == PEN_TCG)
     {
         if (msg_type.type == PB_TCG_MSG_PDP_REFERRAL)
         {
             return pb_pdp_referral_msg_create_from_data(value);
         }
     }
     else if (msg_type.vendor_id == PEN_ITA)
     {
         if (msg_type.type == PB_ITA_MSG_MUTUAL_CAPABILITY)
         {
             return pb_mutual_capability_msg_create_from_data(value);
         }
     }
     return NULL;
 }
Variable Documentation
pb_tnc_msg_info_t pb_tnc_ita_msg_infos[]
Information on PB-TNC ITA Message Types
Definition at line 68 of file pb_tnc_msg.c.
Referenced by METHOD(), and process_tnc_msg().
enum_name_t* pb_tnc_ita_msg_type_names
enum name for pb_tnc_tcg_msg_type_t.
Referenced by METHOD(), and process_tnc_msg().
pb_tnc_msg_info_t pb_tnc_msg_infos[]
Information on PB-TNC Message Types
Definition at line 52 of file pb_tnc_msg.c.
Referenced by METHOD(), and process_tnc_msg().
enum_name_t* pb_tnc_msg_type_names
enum name for pb_tnc_msg_type_t.
Referenced by METHOD(), and process_tnc_msg().
pb_tnc_msg_info_t pb_tnc_tcg_msg_infos[]
Information on PB-TNC TCG Message Types
Definition at line 63 of file pb_tnc_msg.c.
Referenced by METHOD(), and process_tnc_msg().
enum_name_t* pb_tnc_tcg_msg_type_names
enum name for pb_tnc_tcg_msg_type_t.
Referenced by METHOD(), and process_tnc_msg().