strongSwan: gmp_rsa_public_key
gmp_rsa_public_key
gmp
Classes
struct gmp_rsa_public_key_t
Typedefs
typedef struct gmp_rsa_public_key_t gmp_rsa_public_key_t
Functions
gmp_rsa_public_key_t * gmp_rsa_public_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct gmp_rsa_public_key_t gmp_rsa_public_key_t
Definition at line 28 of file gmp_rsa_public_key.h.
Function Documentation
gmp_rsa_public_key_t* gmp_rsa_public_key_load (key_type_t type, va_list args)
Load a RSA public key using libgmp.
Accepts BUILD_RSA_* components.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 447 of file gmp_rsa_public_key.c.
References BITS_PER_BYTE, BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_empty, INIT, chunk_t::len, n, chunk_t::ptr, public_key_equals(), public_key_has_fingerprint(), and TRUE.
Referenced by METHOD().
 {
     private_gmp_rsa_public_key_t *this;
     chunk_t n, e;
     n = e = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_RSA_MODULUS:
                 n = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PUB_EXP:
                 e = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!e.ptr || !n.ptr)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .verify = _verify,
                 .encrypt = _encrypt_,
                 .equals = public_key_equals,
                 .get_keysize = _get_keysize,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = public_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     mpz_init(this->n);
     mpz_init(this->e);
     mpz_import(this->n, n.len, 1, 1, 1, 0, n.ptr);
     mpz_import(this->e, e.len, 1, 1, 1, 0, e.ptr);
     this->k = (mpz_sizeinbase(this->n, 2) + 7) / BITS_PER_BYTE;
     return &this->public;
 }