strongSwan: openssl_hmac.c File Reference
openssl_hmac.c File Reference
#include <openssl/opensslconf.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include "openssl_hmac.h"
#include <crypto/mac.h>
#include <crypto/prfs/mac_prf.h>
#include <crypto/signers/mac_signer.h>
Classes
struct private_mac_t
Typedefs
typedef struct private_mac_t private_mac_t
Functions
METHOD (mac_t, set_key, bool, private_mac_t *this, chunk_t key)
METHOD (mac_t, get_mac, bool, private_mac_t *this, chunk_t data, u_int8_t *out)
METHOD (mac_t, get_mac_size, size_t, private_mac_t *this)
METHOD (mac_t, destroy, void, private_mac_t *this)
static mac_t * hmac_create (hash_algorithm_t algo)
prf_t * openssl_hmac_prf_create (pseudo_random_function_t algo)
signer_t * openssl_hmac_signer_create (integrity_algorithm_t algo)
Typedef Documentation
typedef struct private_mac_t private_mac_t
Definition at line 51 of file openssl_hmac.c.
Function Documentation
static mac_t* hmac_create (hash_algorithm_t algo) static
Definition at line 143 of file openssl_hmac.c.
References enum_to_name(), free(), hash_algorithm_short_names, hasher, INIT, and name.
Referenced by openssl_hmac_prf_create(), and openssl_hmac_signer_create().
 {
     private_mac_t *this;
     char *name;
     name = enum_to_name(hash_algorithm_short_names, algo);
     if (!name)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .get_mac = _get_mac,
             .get_mac_size = _get_mac_size,
             .set_key = _set_key,
             .destroy = _destroy,
         },
         .hasher = EVP_get_digestbyname(name),
     );
     if (!this->hasher)
     {
         free(this);
         return NULL;
     }
     HMAC_CTX_init(&this->hmac);
     return &this->public;
 }
METHOD (mac_t , set_key , bool , private_mac_t * this, chunk_t key)
Definition at line 79 of file openssl_hmac.c.
References FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
 {
 #if OPENSSL_VERSION_NUMBER >= 0x10000000L
     if (HMAC_Init_ex(&this->hmac, key.ptr, key.len, this->hasher, NULL))
     {
         this->key_set = TRUE;
         return TRUE;
     }
     return FALSE;
 #else /* OPENSSL_VERSION_NUMBER < 1.0 */
     HMAC_Init_ex(&this->hmac, key.ptr, key.len, this->hasher, NULL);
     this->key_set = TRUE;
     return TRUE;
 #endif
 }
METHOD (mac_t , get_mac , bool , private_mac_t * this, chunk_t data, u_int8_t * out)
Definition at line 96 of file openssl_hmac.c.
References chunk_empty, FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
 {
     if (!this->key_set)
     {
         return FALSE;
     }
 #if OPENSSL_VERSION_NUMBER >= 0x10000000L
     if (!HMAC_Update(&this->hmac, data.ptr, data.len))
     {
         return FALSE;
     }
     if (out == NULL)
     {
         return TRUE;
     }
     if (!HMAC_Final(&this->hmac, out, NULL))
     {
         return FALSE;
     }
 #else /* OPENSSL_VERSION_NUMBER < 1.0 */
     HMAC_Update(&this->hmac, data.ptr, data.len);
     if (out == NULL)
     {
         return TRUE;
     }
     HMAC_Final(&this->hmac, out, NULL);
 #endif
     return set_key(this, chunk_empty);
 }
METHOD (mac_t , get_mac_size , size_t , private_mac_t * this)
Definition at line 127 of file openssl_hmac.c.
References hasher.
 {
     return EVP_MD_size(this->hasher);
 }
METHOD (mac_t , destroy , void , private_mac_t * this)
Definition at line 133 of file openssl_hmac.c.
References free().
 {
     HMAC_CTX_cleanup(&this->hmac);
     free(this);
 }