strongSwan: keymat_v2_t Struct Reference
keymat_v2_t Struct Reference
keymat_v2
#include "keymat_v2.h"
Public Attributes
keymat_t keymat
bool(* derive_ike_keys)(keymat_v2_t *this, proposal_t *proposal, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r, ike_sa_id_t *id, pseudo_random_function_t rekey_function, chunk_t rekey_skd)
bool(* derive_child_keys)(keymat_v2_t *this, proposal_t *proposal, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r, chunk_t *encr_i, chunk_t *integ_i, chunk_t *encr_r, chunk_t *integ_r)
pseudo_random_function_t(* get_skd)(keymat_v2_t *this, chunk_t *skd)
bool(* get_auth_octets)(keymat_v2_t *this, bool verify, chunk_t ike_sa_init, chunk_t nonce, identification_t *id, char reserved[3], chunk_t *octets)
bool(* get_psk_sig)(keymat_v2_t *this, bool verify, chunk_t ike_sa_init, chunk_t nonce, chunk_t secret, identification_t *id, char reserved[3], chunk_t *sig)
void(* add_hash_algorithm)(keymat_v2_t *this, hash_algorithm_t hash)
bool(* hash_algorithm_supported)(keymat_v2_t *this, hash_algorithm_t hash)
Detailed Description
Derivation and management of sensitive keying material, IKEv2 variant.
Definition at line 31 of file keymat_v2.h.
Member Data Documentation
void(* keymat_v2_t::add_hash_algorithm)(keymat_v2_t *this, hash_algorithm_t hash)
Add a hash algorithm supported by the peer for signature authentication.
Parameters
hash hash algorithm
Definition at line 133 of file keymat_v2.h.
bool(* keymat_v2_t::derive_child_keys)(keymat_v2_t *this, proposal_t *proposal, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r, chunk_t *encr_i, chunk_t *integ_i, chunk_t *encr_r, chunk_t *integ_r)
Derive keys for a CHILD_SA.
The keys for the CHILD_SA are allocated in the integ and encr chunks. An implementation might hand out encrypted keys only, which are decrypted in the kernel before use. If no PFS is used for the CHILD_SA, dh can be NULL.
Parameters
proposal selected algorithms
dh diffie hellman key allocated by create_dh(), or NULL
nonce_i initiators nonce value
nonce_r responders nonce value
encr_i chunk to write initiators encryption key to
integ_i chunk to write initiators integrity key to
encr_r chunk to write responders encryption key to
integ_r chunk to write responders integrity key to
Returns
TRUE on success
Definition at line 77 of file keymat_v2.h.
Referenced by process_child_add(), and START_TEST().
bool(* keymat_v2_t::derive_ike_keys)(keymat_v2_t *this, proposal_t *proposal, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r, ike_sa_id_t *id, pseudo_random_function_t rekey_function, chunk_t rekey_skd)
Derive keys for the IKE_SA.
These keys are not handed out, but are used by the associated signers, crypters and authentication functions.
Parameters
proposal selected algorithms
dh diffie hellman key allocated by create_dh()
nonce_i initiators nonce value
nonce_r responders nonce value
id IKE_SA identifier
rekey_prf PRF of old SA if rekeying, PRF_UNDEFINED otherwise
rekey_sdk SKd of old SA if rekeying
Returns
TRUE on success
Definition at line 53 of file keymat_v2.h.
Referenced by process_ike_add(), and START_TEST().
bool(* keymat_v2_t::get_auth_octets)(keymat_v2_t *this, bool verify, chunk_t ike_sa_init, chunk_t nonce, identification_t *id, char reserved[3], chunk_t *octets)
Generate octets to use for authentication procedure (RFC4306 2.15).
This method creates the plain octets and is usually signed by a private key. PSK and EAP authentication include a secret into the data, use the get_psk_sig() method instead.
Parameters
verify TRUE to create for verfification, FALSE to sign
ike_sa_init encoded ike_sa_init message
nonce nonce value
id identity
reserved reserved bytes of id_payload
octests chunk receiving allocated auth octets
Returns
TRUE if octets created successfully
Definition at line 105 of file keymat_v2.h.
Referenced by build_auth(), METHOD(), rebuild_auth(), sign_classic(), and sign_signature_auth().
bool(* keymat_v2_t::get_psk_sig)(keymat_v2_t *this, bool verify, chunk_t ike_sa_init, chunk_t nonce, chunk_t secret, identification_t *id, char reserved[3], chunk_t *sig)
Build the shared secret signature used for PSK and EAP authentication.
This method wraps the get_auth_octets() method and additionally includes the secret into the signature. If no secret is given, SK_p is used as secret (used for EAP methods without MSK).
Parameters
verify TRUE to create for verfification, FALSE to sign
ike_sa_init encoded ike_sa_init message
nonce nonce value
secret optional secret to include into signature
id identity
reserved reserved bytes of id_payload
sign chunk receiving allocated signature octets
Returns
TRUE if signature created successfully
Definition at line 124 of file keymat_v2.h.
Referenced by build_auth(), METHOD(), and verify_auth().
pseudo_random_function_t(* keymat_v2_t::get_skd)(keymat_v2_t *this, chunk_t *skd)
Get SKd to pass to derive_ikey_keys() during rekeying.
Parameters
skd chunk to write SKd to (internal data)
Returns
PRF function to derive keymat
Definition at line 88 of file keymat_v2.h.
Referenced by derive_keys(), and METHOD().
bool(* keymat_v2_t::hash_algorithm_supported)(keymat_v2_t *this, hash_algorithm_t hash)
Check if a given hash algorithm is supported by the peer for signature authentication.
Parameters
hash hash algorithm
Returns
TRUE if supported, FALSE otherwise
Definition at line 142 of file keymat_v2.h.
Referenced by select_signature_schemes().
keymat_t keymat_v2_t::keymat
Implements keymat_t.
Definition at line 36 of file keymat_v2.h.
Referenced by keymat_create(), and START_TEST().
The documentation for this struct was generated from the following file:
keymat_v2.h