strongSwan: enumerator.c File Reference
enumerator.c File Reference
#include "enumerator.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <limits.h>
#include <stdio.h>
#include <dirent.h>
#include <errno.h>
#include <string.h>
#include <utils/debug.h>
Classes
struct dir_enum_t
struct token_enum_t
struct nested_enumerator_t
struct filter_enumerator_t
struct cleaner_enumerator_t
struct single_enumerator_t
Functions
static bool enumerate_empty (enumerator_t *enumerator,...)
enumerator_t * enumerator_create_empty ()
static void destroy_dir_enum (dir_enum_t *this)
static bool enumerate_dir_enum (dir_enum_t *this, char **relative, char **absolute, struct stat *st)
enumerator_t * enumerator_create_directory (const char *path)
enumerator_t * enumerator_create_glob (const char *pattern)
static void destroy_token_enum (token_enum_t *this)
static bool enumerate_token_enum (token_enum_t *this, char **token)
enumerator_t * enumerator_create_token (const char *string, const char *sep, const char *trim)
static bool enumerate_nested (nested_enumerator_t *this, void *v1, void *v2, void *v3, void *v4, void *v5)
static void destroy_nested (nested_enumerator_t *this)
enumerator_t * enumerator_create_nested (enumerator_t *outer, enumerator_t *(inner_constructor)(void *outer, void *data), void *data, void(*destroy_data)(void *data))
static void destroy_filter (filter_enumerator_t *this)
static bool enumerate_filter (filter_enumerator_t *this, void *o1, void *o2, void *o3, void *o4, void *o5)
enumerator_t * enumerator_create_filter (enumerator_t *unfiltered, bool(*filter)(void *data,...), void *data, void(*destructor)(void *data))
static void destroy_cleaner (cleaner_enumerator_t *this)
static bool enumerate_cleaner (cleaner_enumerator_t *this, void *v1, void *v2, void *v3, void *v4, void *v5)
enumerator_t * enumerator_create_cleaner (enumerator_t *wrapped, void(*cleanup)(void *data), void *data)
static void destroy_single (single_enumerator_t *this)
static bool enumerate_single (single_enumerator_t *this, void **item)
enumerator_t * enumerator_create_single (void *item, void(*cleanup)(void *item))
Function Documentation
static void destroy_cleaner (cleaner_enumerator_t * this) static
Implementation of enumerator_create_cleanup().destroy
Definition at line 565 of file enumerator.c.
References cleanup, and free().
Referenced by enumerator_create_cleaner().
 {
     this->cleanup(this->data);
     this->wrapped->destroy(this->wrapped);
     free(this);
 }
static void destroy_dir_enum (dir_enum_t * this) static
Implementation of enumerator_create_directory().destroy
Definition at line 70 of file enumerator.c.
References dir, and free().
Referenced by enumerator_create_directory().
 {
     closedir(this->dir);
     free(this);
 }
static void destroy_filter (filter_enumerator_t * this) static
Implementation of enumerator_create_filter().destroy
Definition at line 505 of file enumerator.c.
References free().
Referenced by enumerator_create_filter().
 {
     if (this->destructor)
     {
         this->destructor(this->data);
     }
     this->unfiltered->destroy(this->unfiltered);
     free(this);
 }
static void destroy_nested (nested_enumerator_t * this) static
Implementation of enumerator_create_nested().destroy()
Definition at line 460 of file enumerator.c.
References data, destroy_data(), DESTROY_IF, and free().
Referenced by enumerator_create_nested().
 {
     if (this->destroy_data)
     {
         this->destroy_data(this->data);
     }
     DESTROY_IF(this->inner);
     this->outer->destroy(this->outer);
     free(this);
 }
static void destroy_single (single_enumerator_t * this) static
Implementation of enumerator_create_single().destroy
Definition at line 611 of file enumerator.c.
References cleanup, and free().
Referenced by enumerator_create_single().
 {
     if (this->cleanup)
     {
         this->cleanup(this->item);
     }
     free(this);
 }
static void destroy_token_enum (token_enum_t * this) static
Implementation of enumerator_create_token().destroy
Definition at line 278 of file enumerator.c.
References free().
Referenced by enumerator_create_token().
 {
     free(this->string);
     free(this);
 }
static bool enumerate_cleaner (cleaner_enumerator_t * this, void * v1, void * v2, void * v3, void * v4, void * v5) static
Implementation of enumerator_create_cleaner().enumerate
Definition at line 575 of file enumerator.c.
Referenced by enumerator_create_cleaner().
 {
     return this->wrapped->enumerate(this->wrapped, v1, v2, v3, v4, v5);
 }
static bool enumerate_dir_enum (dir_enum_t * this, char ** relative, char ** absolute, struct stat * st) static
Implementation of enumerator_create_directory().enumerate
Definition at line 79 of file enumerator.c.
References DBG1, DBG_LIB, dir, FALSE, len, snprintf, streq(), strerror, and TRUE.
Referenced by enumerator_create_directory().
 {
     struct dirent *entry = readdir(this->dir);
     size_t remaining;
     int len;
     if (!entry)
     {
         return FALSE;
     }
     if (streq(entry->d_name, ".") || streq(entry->d_name, ".."))
     {
         return enumerate_dir_enum(this, relative, absolute, st);
     }
     if (relative)
     {
         *relative = entry->d_name;
     }
     if (absolute || st)
     {
         remaining = sizeof(this->full) - (this->full_end - this->full);
         len = snprintf(this->full_end, remaining, "%s", entry->d_name);
         if (len < 0 || len >= remaining)
         {
             DBG1(DBG_LIB, "buffer too small to enumerate file '%s'",
                  entry->d_name);
             return FALSE;
         }
         if (absolute)
         {
             *absolute = this->full;
         }
         if (st)
         {
             if (stat(this->full, st))
             {
                 DBG1(DBG_LIB, "stat() on '%s' failed: %s", this->full,
                      strerror(errno));
                 return FALSE;
             }
         }
     }
     return TRUE;
 }
static bool enumerate_empty (enumerator_t * enumerator, ...) static
Implementation of enumerator_create_empty().enumerate
Definition at line 37 of file enumerator.c.
References FALSE.
Referenced by enumerator_create_empty().
 {
     return FALSE;
 }
static bool enumerate_filter (filter_enumerator_t * this, void * o1, void * o2, void * o3, void * o4, void * o5) static
Implementation of enumerator_create_filter().enumerate
Definition at line 518 of file enumerator.c.
References FALSE, filter(), and TRUE.
Referenced by enumerator_create_filter().
 {
     void *i1, *i2, *i3, *i4, *i5;
     while (this->unfiltered->enumerate(this->unfiltered, &i1, &i2, &i3, &i4, &i5))
     {
         if (this->filter(this->data, &i1, o1, &i2, o2, &i3, o3, &i4, o4, &i5, o5))
         {
             return TRUE;
         }
     }
     return FALSE;
 }
static bool enumerate_nested (nested_enumerator_t * this, void * v1, void * v2, void * v3, void * v4, void * v5) static
Implementation of enumerator_create_nested().enumerate()
Definition at line 433 of file enumerator.c.
References create_inner(), data, FALSE, and TRUE.
Referenced by enumerator_create_nested().
 {
     while (TRUE)
     {
         while (this->inner == NULL)
         {
             void *outer;
             if (!this->outer->enumerate(this->outer, &outer))
             {
                 return FALSE;
             }
             this->inner = this->create_inner(outer, this->data);
         }
         if (this->inner->enumerate(this->inner, v1, v2, v3, v4, v5))
         {
             return TRUE;
         }
         this->inner->destroy(this->inner);
         this->inner = NULL;
     }
 }
static bool enumerate_single (single_enumerator_t * this, void ** item) static
Implementation of enumerator_create_single().enumerate
Definition at line 623 of file enumerator.c.
References FALSE, and TRUE.
Referenced by enumerator_create_single().
 {
     if (this->done)
     {
         return FALSE;
     }
     *item = this->item;
     this->done = TRUE;
     return TRUE;
 }
static bool enumerate_token_enum (token_enum_t * this, char ** token) static
Implementation of enumerator_create_token().enumerate
Definition at line 287 of file enumerator.c.
References FALSE, sep, trim, and TRUE.
Referenced by enumerator_create_token().
 {
     const char *sep, *trim;
     char *pos = NULL, *tmp;
     bool last = FALSE;
     /* trim leading characters/separators */
     while (*this->pos)
     {
         trim = this->trim;
         while (*trim)
         {
             if (*trim == *this->pos)
             {
                 this->pos++;
                 break;
             }
             trim++;
         }
         sep = this->sep;
         while (*sep)
         {
             if (*sep == *this->pos)
             {
                 this->pos++;
                 break;
             }
             sep++;
         }
         if (!*trim && !*sep)
         {
             break;
         }
     }
     switch (*this->pos)
     {
         case '"':
         case '\'':
         {
             /* read quoted token */
             tmp = strchr(this->pos + 1, *this->pos);
             if (tmp)
             {
                 *token = this->pos + 1;
                 *tmp = '\0';
                 this->pos = tmp + 1;
                 return TRUE;
             }
             /* unterminated string, FALL-THROUGH */
         }
         default:
         {
             /* find nearest separator */
             sep = this->sep;
             while (*sep)
             {
                 tmp = strchr(this->pos, *sep);
                 if (tmp && (pos == NULL || tmp < pos))
                 {
                     pos = tmp;
                 }
                 sep++;
             }
             *token = this->pos;
             if (pos)
             {
                 *pos = '\0';
                 this->pos = pos + 1;
             }
             else
             {
                 last = TRUE;
                 pos = this->pos = strchr(this->pos, '\0');
             }
             break;
         }
     }
     /* trim trailing characters */
     pos--;
     while (pos >= *token)
     {
         trim = this->trim;
         while (*trim)
         {
             if (*trim == *pos)
             {
                 *(pos--) = '\0';
                 break;
             }
             trim++;
         }
         if (!*trim)
         {
             break;
         }
     }
     if (!last || pos >= *token)
     {
         return TRUE;
     }
     return FALSE;
 }
enumerator_t* enumerator_create_nested (enumerator_t * outer, enumerator_t * inner_constructor)(void *outer, void *data, void * data, void(*)(void *data) destroy_data)
See header
Definition at line 474 of file enumerator.c.
References nested_enumerator_t::create_inner, data, nested_enumerator_t::data, enumerator_t::destroy, destroy_data(), nested_enumerator_t::destroy_data, destroy_nested(), enumerator_t::enumerate, enumerate_nested(), nested_enumerator_t::inner, malloc_thing, nested_enumerator_t::outer, and nested_enumerator_t::public.
Referenced by create_private_enumerator(), METHOD(), and START_TEST().
 {
     nested_enumerator_t *enumerator = malloc_thing(nested_enumerator_t);
     enumerator->public.enumerate = (void*)enumerate_nested;
     enumerator->public.destroy = (void*)destroy_nested;
     enumerator->outer = outer;
     enumerator->inner = NULL;
     enumerator->create_inner = (void*)inner_constructor;
     enumerator->data = data;
     enumerator->destroy_data = destroy_data;
     return &enumerator->public;
 }