strongSwan: plugin_t Struct Reference
plugin_t Struct Reference
plugin
#include "plugin.h"
Public Attributes
char *(* get_name)(plugin_t *this)
int(* get_features)(plugin_t *this, plugin_feature_t *features[])
bool(* reload)(plugin_t *this)
void(* destroy)(plugin_t *this)
Detailed Description
Interface definition of a plugin.
Definition at line 32 of file plugin.h.
Member Data Documentation
void(* plugin_t::destroy)(plugin_t *this)
Destroy a plugin instance.
Definition at line 62 of file plugin.h.
int(* plugin_t::get_features)(plugin_t *this, plugin_feature_t *features[])
Get plugin features with dependencies.
The returned array contains features provided by the plugin and dependencies for that feature. See plugin_feature_t for details.
Parameters
features pointer receiving plugin features
Returns
number of features
Definition at line 50 of file plugin.h.
Referenced by list_plugins(), purge_plugins(), and register_features().
char*(* plugin_t::get_name)(plugin_t *this)
Get the name of the plugin.
Returns
plugin name
Definition at line 39 of file plugin.h.
Referenced by CALLBACK(), list_plugins(), load_dependencies(), load_feature(), load_provided(), loaded_plugins_list(), plugin_feature_load(), plugin_loaded(), purge_plugins(), register_features(), and reload_by_name().
bool(* plugin_t::reload)(plugin_t *this)
Try to reload plugin configuration.
Returns
TRUE if reloaded, FALSE if reloading not supporty by plugin
Definition at line 57 of file plugin.h.
Referenced by reload_by_name().
The documentation for this struct was generated from the following file:
plugin.h