strongSwan: transform_attribute
transform_attribute
payloads
Classes
struct transform_attribute_t
Typedefs
typedef enum
transform_attribute_type_t transform_attribute_type_t
typedef struct
transform_attribute_t transform_attribute_t
Enumerations
enum transform_attribute_type_t {
TATTR_PH1_ENCRYPTION_ALGORITHM = 1, TATTR_PH1_HASH_ALGORITHM = 2, TATTR_PH1_AUTH_METHOD = 3, TATTR_PH1_GROUP = 4,
TATTR_PH1_GROUP_TYPE = 5, TATTR_PH1_GROUP_PRIME = 6, TATTR_PH1_GROUP_GENONE = 7, TATTR_PH1_GROUP_GENTWO = 8,
TATTR_PH1_GROUP_CURVE_A = 9, TATTR_PH1_GROUP_CURVE_B = 10, TATTR_PH1_LIFE_TYPE = 11, TATTR_PH1_LIFE_DURATION = 12,
TATTR_PH1_PRF = 13, TATTR_PH1_KEY_LENGTH = 14, TATTR_PH1_FIELD_SIZE = 15, TATTR_PH1_GROUP_ORDER = 16,
TATTR_PH2_SA_LIFE_TYPE = 1, TATTR_PH2_SA_LIFE_DURATION = 2, TATTR_PH2_GROUP = 3, TATTR_PH2_ENCAP_MODE = 4,
TATTR_PH2_AUTH_ALGORITHM = 5, TATTR_PH2_KEY_LENGTH = 6, TATTR_PH2_KEY_ROUNDS = 7, TATTR_PH2_COMP_DICT_SIZE = 8,
TATTR_PH2_COMP_PRIV_ALGORITHM = 9, TATTR_PH2_ECN_TUNNEL = 10, TATTR_PH2_EXT_SEQ_NUMBER = 11, TATTR_IKEV2_KEY_LENGTH = 14,
TATTR_UNDEFINED = 16384
}
Functions
transform_attribute_t * transform_attribute_create (payload_type_t type)
transform_attribute_t * transform_attribute_create_value (payload_type_t type, transform_attribute_type_t kind, u_int64_t value)
Variables
enum_name_t * tattr_ph1_names
enum_name_t * tattr_ph2_names
enum_name_t * tattr_ikev2_names
Detailed Description
Typedef Documentation
typedef struct transform_attribute_t transform_attribute_t
Definition at line 26 of file transform_attribute.h.
typedef enum transform_attribute_type_t transform_attribute_type_t
Definition at line 25 of file transform_attribute.h.
Enumeration Type Documentation
enum transform_attribute_type_t
Type of the attribute.
Enumerator
TATTR_PH1_ENCRYPTION_ALGORITHM
IKEv1 Phase 1 attributes
TATTR_PH1_HASH_ALGORITHM
TATTR_PH1_AUTH_METHOD
TATTR_PH1_GROUP
TATTR_PH1_GROUP_TYPE
TATTR_PH1_GROUP_PRIME
TATTR_PH1_GROUP_GENONE
TATTR_PH1_GROUP_GENTWO
TATTR_PH1_GROUP_CURVE_A
TATTR_PH1_GROUP_CURVE_B
TATTR_PH1_LIFE_TYPE
TATTR_PH1_LIFE_DURATION
TATTR_PH1_PRF
TATTR_PH1_KEY_LENGTH
TATTR_PH1_FIELD_SIZE
TATTR_PH1_GROUP_ORDER
TATTR_PH2_SA_LIFE_TYPE
IKEv1 Phase 2 attributes
TATTR_PH2_SA_LIFE_DURATION
TATTR_PH2_GROUP
TATTR_PH2_ENCAP_MODE
TATTR_PH2_AUTH_ALGORITHM
TATTR_PH2_KEY_LENGTH
TATTR_PH2_KEY_ROUNDS
TATTR_PH2_COMP_DICT_SIZE
TATTR_PH2_COMP_PRIV_ALGORITHM
TATTR_PH2_ECN_TUNNEL
TATTR_PH2_EXT_SEQ_NUMBER
TATTR_IKEV2_KEY_LENGTH
TATTR_UNDEFINED
Definition at line 34 of file transform_attribute.h.
{
     TATTR_PH1_ENCRYPTION_ALGORITHM = 1,
     TATTR_PH1_HASH_ALGORITHM = 2,
     TATTR_PH1_AUTH_METHOD = 3,
     TATTR_PH1_GROUP = 4,
     TATTR_PH1_GROUP_TYPE = 5,
     TATTR_PH1_GROUP_PRIME = 6,
     TATTR_PH1_GROUP_GENONE = 7,
     TATTR_PH1_GROUP_GENTWO = 8,
     TATTR_PH1_GROUP_CURVE_A = 9,
     TATTR_PH1_GROUP_CURVE_B = 10,
     TATTR_PH1_LIFE_TYPE = 11,
     TATTR_PH1_LIFE_DURATION = 12,
     TATTR_PH1_PRF = 13,
     TATTR_PH1_KEY_LENGTH = 14,
     TATTR_PH1_FIELD_SIZE = 15,
     TATTR_PH1_GROUP_ORDER = 16,
     TATTR_PH2_SA_LIFE_TYPE = 1,
     TATTR_PH2_SA_LIFE_DURATION = 2,
     TATTR_PH2_GROUP = 3,
     TATTR_PH2_ENCAP_MODE = 4,
     TATTR_PH2_AUTH_ALGORITHM = 5,
     TATTR_PH2_KEY_LENGTH = 6,
     TATTR_PH2_KEY_ROUNDS = 7,
     TATTR_PH2_COMP_DICT_SIZE = 8,
     TATTR_PH2_COMP_PRIV_ALGORITHM = 9,
     TATTR_PH2_ECN_TUNNEL = 10,
     TATTR_PH2_EXT_SEQ_NUMBER = 11,
     /* IKEv2 key length attribute */
     TATTR_IKEV2_KEY_LENGTH = 14,
     /* undefined, private use attribute */
     TATTR_UNDEFINED = 16384,
 };
Function Documentation
transform_attribute_t* transform_attribute_create (payload_type_t type)
Creates an empty transform_attribute_t object.
Parameters
type PLV2_TRANSFORM_ATTRIBUTE or PLV1_TRANSFORM_ATTRIBUTE
Returns
transform_attribute_t object
Definition at line 222 of file transform_attribute.c.
References FALSE, INIT, and type.
Referenced by payload_create(), and transform_attribute_create_value().
 {
     private_transform_attribute_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_value_chunk = _get_value_chunk,
             .get_value = _get_value,
             .get_attribute_type = _get_attribute_type,
             .destroy = _destroy,
         },
         .attribute_format = FALSE,
         .type = type,
     );
     return &this->public;
 }
transform_attribute_t* transform_attribute_create_value (payload_type_t type, transform_attribute_type_t kind, u_int64_t value)
Creates a two byte value or a larger attribute for a given attribute kind.
Parameters
type PLV2_TRANSFORM_ATTRIBUTE or PLV1_TRANSFORM_ATTRIBUTE
kind attribute kind
value fixed two byte value
Returns
transform_attribute_t object
Definition at line 252 of file transform_attribute.c.
References chunk_clone, chunk_from_thing, htoun64(), transform_attribute_create(), TRUE, UINT16_MAX, UINT32_MAX, and value.
Referenced by proposal_substructure_create_for_ipcomp_v1(), set_from_proposal_v1(), set_from_proposal_v1_ike(), and set_from_proposal_v2().
 {
     private_transform_attribute_t *this;
     this = (private_transform_attribute_t*)transform_attribute_create(type);
     this->attribute_type = kind & 0x7FFF;
     if (value <= UINT16_MAX)
     {
         this->attribute_length_or_value = value;
         this->attribute_format = TRUE;
     }
     else if (value <= UINT32_MAX)
     {
         u_int32_t val32;
         val32 = htonl(value);
         this->attribute_value = chunk_clone(chunk_from_thing(val32));
         this->attribute_length_or_value = sizeof(val32);
     }
     else
     {
         htoun64(&value, value);
         this->attribute_value = chunk_clone(chunk_from_thing(value));
         this->attribute_length_or_value = sizeof(value);
     }
     return &this->public;
 }
Variable Documentation
enum_name_t* tattr_ikev2_names
Enum names for IKEv2 transform_attribute_type_t.
enum_name_t* tattr_ph1_names
Enum names for IKEv1 Phase 1 transform_attribute_type_t.
enum_name_t* tattr_ph2_names
Enum names for IKEv1 Phase 2 transform_attribute_type_t.