strongSwan: ipsec_event_relay.c File Reference
ipsec_event_relay.c File Reference
#include "ipsec_event_relay.h"
#include <library.h>
#include <utils/debug.h>
#include <threading/rwlock.h>
#include <collections/linked_list.h>
#include <collections/blocking_queue.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_ipsec_event_relay_t
struct ipsec_event_t
Typedefs
typedef struct
private_ipsec_event_relay_t private_ipsec_event_relay_t
Functions
static void ipsec_event_destroy (ipsec_event_t *event)
static job_requeue_t handle_events (private_ipsec_event_relay_t *this)
METHOD (ipsec_event_relay_t, expire, void, private_ipsec_event_relay_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, bool hard)
METHOD (ipsec_event_relay_t, register_listener, void, private_ipsec_event_relay_t *this, ipsec_event_listener_t *listener)
METHOD (ipsec_event_relay_t, unregister_listener, void, private_ipsec_event_relay_t *this, ipsec_event_listener_t *listener)
METHOD (ipsec_event_relay_t, destroy, void, private_ipsec_event_relay_t *this)
ipsec_event_relay_t * ipsec_event_relay_create ()
Typedef Documentation
typedef struct private_ipsec_event_relay_t private_ipsec_event_relay_t
Definition at line 27 of file ipsec_event_relay.c.
Function Documentation
static job_requeue_t handle_events (private_ipsec_event_relay_t * this) static
Dequeue events and relay them to listeners
Definition at line 108 of file ipsec_event_relay.c.
References ipsec_event_t::data, enumerator_t::destroy, ipsec_event_t::dst, enumerator_t::enumerate, event, ipsec_event_listener_t::expire, ipsec_event_t::expire, ipsec_event_destroy(), JOB_REQUEUE_DIRECT, lock, ipsec_event_t::protocol, queue(), ipsec_event_t::spi, ipsec_event_t::type, and spinlock_t::unlock.
Referenced by handle_certs(), ipsec_event_relay_create(), and token_event_cb().
 {
     enumerator_t *enumerator;
     ipsec_event_listener_t *current;
     ipsec_event_t *event;
     event = this->queue->dequeue(this->queue);
     this->lock->read_lock(this->lock);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         switch (event->type)
         {
             case IPSEC_EVENT_EXPIRE:
                 if (current->expire)
                 {
                     current->expire(event->protocol, event->spi, event->dst,
                                     event->data.expire.hard);
                 }
                 break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     ipsec_event_destroy(event);
     return JOB_REQUEUE_DIRECT;
 }
static void ipsec_event_destroy (ipsec_event_t * event) static
Destroy IPsec event data
Definition at line 99 of file ipsec_event_relay.c.
References ipsec_event_t::dst, and free().
Referenced by handle_events().
 {
     event->dst->destroy(event->dst);
     free(event);
 }
METHOD (ipsec_event_relay_t , expire , void , private_ipsec_event_relay_t * this, u_int8_t protocol, u_int32_t spi, host_t * dst, bool hard)
Definition at line 137 of file ipsec_event_relay.c.
References host_t::clone, event, INIT, queue(), and type.
 {
     ipsec_event_t *event;
     INIT(event,
         .type = IPSEC_EVENT_EXPIRE,
         .protocol = protocol,
         .spi = spi,
         .dst = dst->clone(dst),
         .data = {
             .expire = {
                 .hard = hard,
             },
         },
     );
     this->queue->enqueue(this->queue, event);
 }
METHOD (ipsec_event_relay_t , register_listener , void , private_ipsec_event_relay_t * this, ipsec_event_listener_t * listener)
Definition at line 157 of file ipsec_event_relay.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->listeners->insert_last(this->listeners, listener);
     this->lock->unlock(this->lock);
 }
METHOD (ipsec_event_relay_t , unregister_listener , void , private_ipsec_event_relay_t * this, ipsec_event_listener_t * listener)
Definition at line 165 of file ipsec_event_relay.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->listeners->remove(this->listeners, listener, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (ipsec_event_relay_t , destroy , void , private_ipsec_event_relay_t * this)
Definition at line 173 of file ipsec_event_relay.c.
References spinlock_t::destroy, free(), lock, and queue().
 {
     this->queue->destroy_function(this->queue, free);
     this->listeners->destroy(this->listeners);
     this->lock->destroy(this->lock);
     free(this);
 }