strongSwan: fast_session.c File Reference
fast_session.c File Reference
#include "fast_session.h"
#include <string.h>
#include <fcgiapp.h>
#include <stdio.h>
#include <collections/linked_list.h>
Classes
struct private_fast_session_t
Macros
#define _GNU_SOURCE
#define COOKIE_LEN 16
Typedefs
typedef struct
private_fast_session_t private_fast_session_t
Functions
METHOD (fast_session_t, add_controller, void, private_fast_session_t *this, fast_controller_t *controller)
METHOD (fast_session_t, add_filter, void, private_fast_session_t *this, fast_filter_t *filter)
static bool create_sid (private_fast_session_t *this)
static bool run_filter (private_fast_session_t *this, fast_request_t *request, char *p0, char *p1, char *p2, char *p3, char *p4, char *p5)
METHOD (fast_session_t, process, void, private_fast_session_t *this, fast_request_t *request)
METHOD (fast_session_t, get_sid, char *, private_fast_session_t *this)
METHOD (fast_session_t, destroy, void, private_fast_session_t *this)
fast_session_t * fast_session_create (fast_context_t *context)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file fast_session.c.
#define COOKIE_LEN 16
Definition at line 26 of file fast_session.c.
Referenced by create_sid().
Typedef Documentation
typedef struct private_fast_session_t private_fast_session_t
Definition at line 28 of file fast_session.c.
Function Documentation
static bool create_sid (private_fast_session_t * this) static
Create a session ID and a cookie
Definition at line 81 of file fast_session.c.
References chunk_create(), chunk_to_hex(), COOKIE_LEN, crypto_factory_t::create_rng, library_t::crypto, rng_t::destroy, FALSE, rng_t::get_bytes, lib, rng, RNG_WEAK, and TRUE.
Referenced by fast_session_create().
 {
     char buf[COOKIE_LEN];
     rng_t *rng;
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng)
     {
         return FALSE;
     }
     if (!rng->get_bytes(rng, sizeof(buf), buf))
     {
         rng->destroy(rng);
         return FALSE;
     }
     rng->destroy(rng);
     chunk_to_hex(chunk_create(buf, sizeof(buf)), this->sid, FALSE);
     return TRUE;
 }
METHOD (fast_session_t , add_controller , void , private_fast_session_t * this, fast_controller_t * controller)
Definition at line 66 of file fast_session.c.
 {
     this->controllers->insert_last(this->controllers, controller);
 }
METHOD (fast_session_t , add_filter , void , private_fast_session_t * this, fast_filter_t * filter)
Definition at line 72 of file fast_session.c.
 {
     this->filters->insert_last(this->filters, filter);
 }
METHOD (fast_session_t , process , void , private_fast_session_t * this, fast_request_t * request)
Definition at line 123 of file fast_session.c.
References fast_request_t::add_cookie, enumerator_t::destroy, enumerator_t::enumerate, FALSE, fast_request_t::get_base, fast_controller_t::get_name, fast_request_t::get_path, fast_controller_t::handle, run_filter(), start, fast_request_t::streamf, streq(), SUCCESS, and TRUE.
 {
     char *pos, *start, *param[6] = {NULL, NULL, NULL, NULL, NULL, NULL};
     enumerator_t *enumerator;
     bool handled = FALSE;
     fast_controller_t *current;
     int i = 0;
     if (!this->cookie_sent)
     {
         request->add_cookie(request, "SID", this->sid);
         this->cookie_sent = TRUE;
     }
     start = request->get_path(request);
     if (start)
     {
         if (*start == '/')
         {
             start++;
         }
         while ((pos = strchr(start, '/')) != NULL && i < 5)
         {
             param[i++] = strndupa(start, pos - start);
             start = pos + 1;
         }
         param[i] = strdupa(start);
         if (run_filter(this, request, param[0], param[1], param[2], param[3],
                         param[4], param[5]))
         {
             enumerator = this->controllers->create_enumerator(this->controllers);
             while (enumerator->enumerate(enumerator, &current))
             {
                 if (streq(current->get_name(current), param[0]))
                 {
                     current->handle(current, request, param[1], param[2],
                                     param[3], param[4], param[5]);
                     handled = TRUE;
                     break;
                 }
             }
             enumerator->destroy(enumerator);
         }
         else
         {
             handled = TRUE;
         }
     }
     if (!handled)
     {
         if (this->controllers->get_first(this->controllers,
                                          (void**)&current) == SUCCESS)
         {
             request->streamf(request,
                 "Status: 301 Moved permanently\nLocation: %s/%s\n\n",
                 request->get_base(request), current->get_name(current));
         }
     }
 }
METHOD (fast_session_t , get_sid , char * , private_fast_session_t * this)
Definition at line 185 of file fast_session.c.
 {
     return this->sid;
 }
METHOD (fast_session_t , destroy , void , private_fast_session_t * this)
Definition at line 191 of file fast_session.c.
References context, destroy(), DESTROY_IF, and free().
 {
     this->controllers->destroy_offset(this->controllers,
                                       offsetof(fast_controller_t, destroy));
     this->filters->destroy_offset(this->filters,
                                       offsetof(fast_filter_t, destroy));
     DESTROY_IF(this->context);
     free(this);
 }
static bool run_filter (private_fast_session_t * this, fast_request_t * request, char * p0, char * p1, char * p2, char * p3, char * p4, char * p5) static
run all registered filters
Definition at line 104 of file fast_session.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, filter(), fast_filter_t::run, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     fast_filter_t *filter;
     enumerator = this->filters->create_enumerator(this->filters);
     while (enumerator->enumerate(enumerator, &filter))
     {
         if (!filter->run(filter, request, p0, p1, p2, p3, p4, p5))
         {
             enumerator->destroy(enumerator);
             return FALSE;
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 }