strongSwan: load_pools.h File Reference
load_pools.h File Reference
#include "command.h"
Functions
int load_pools_cfg (vici_conn_t *conn, command_format_options_t format, settings_t *cfg)
Function Documentation
int load_pools_cfg (vici_conn_t * conn, command_format_options_t format, settings_t * cfg)
Load all pool definitions from configuration file
Parameters
conn vici connection to load to
format output format
cfg configuration to load from
See header.
Definition at line 199 of file load_pools.c.
References COMMAND_FORMAT_RAW, settings_t::create_section_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, found, fprintf, free(), list_pools(), load_pool(), printf, linked_list_t::remove_first, remove_from_list(), section, SUCCESS, and unload_pool().
Referenced by load_all(), and load_pools().
 {
     u_int found = 0, loaded = 0, unloaded = 0;
     char *section;
     enumerator_t *enumerator;
     linked_list_t *pools;
     pools = list_pools(conn, format);
     enumerator = cfg->create_section_enumerator(cfg, "pools");
     while (enumerator->enumerate(enumerator, &section))
     {
         remove_from_list(pools, section);
         found++;
         if (load_pool(conn, cfg, section, format))
         {
             loaded++;
         }
     }
     enumerator->destroy(enumerator);
     /* unload all pools in daemon, but not in file */
     while (pools->remove_first(pools, (void**)&section) == SUCCESS)
     {
         if (unload_pool(conn, section, format))
         {
             unloaded++;
         }
         free(section);
     }
     pools->destroy(pools);
     if (format & COMMAND_FORMAT_RAW)
     {
         return 0;
     }
     if (found == 0)
     {
         printf("no pools found, %u unloaded\n", unloaded);
         return 0;
     }
     if (loaded == found)
     {
         printf("successfully loaded %u pools, %u unloaded\n",
                loaded, unloaded);
         return 0;
     }
     fprintf(stderr, "loaded %u of %u pools, %u failed to load, "
             "%u unloaded\n", loaded, found, found - loaded, unloaded);
     return EINVAL;
 }