strongSwan: gcrypt_dh.c File Reference
gcrypt_dh.c File Reference
#include <gcrypt.h>
#include "gcrypt_dh.h"
#include <utils/debug.h>
Classes
struct private_gcrypt_dh_t
Typedefs
typedef struct private_gcrypt_dh_t private_gcrypt_dh_t
Functions
METHOD (diffie_hellman_t, set_other_public_value, bool, private_gcrypt_dh_t *this, chunk_t value)
static chunk_t export_mpi (gcry_mpi_t value, size_t len)
METHOD (diffie_hellman_t, get_my_public_value, bool, private_gcrypt_dh_t *this, chunk_t *value)
METHOD (diffie_hellman_t, set_private_value, bool, private_gcrypt_dh_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_shared_secret, bool, private_gcrypt_dh_t *this, chunk_t *secret)
METHOD (diffie_hellman_t, get_dh_group, diffie_hellman_group_t, private_gcrypt_dh_t *this)
METHOD (diffie_hellman_t, destroy, void, private_gcrypt_dh_t *this)
gcrypt_dh_t * create_generic (diffie_hellman_group_t group, size_t exp_len, chunk_t g, chunk_t p)
gcrypt_dh_t * gcrypt_dh_create (diffie_hellman_group_t group)
gcrypt_dh_t * gcrypt_dh_create_custom (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Typedef Documentation
typedef struct private_gcrypt_dh_t private_gcrypt_dh_t
Definition at line 23 of file gcrypt_dh.c.
Function Documentation
gcrypt_dh_t* create_generic (diffie_hellman_group_t group, size_t exp_len, chunk_t g, chunk_t p)
Definition at line 198 of file gcrypt_dh.c.
References rng_t::allocate_bytes, chunk_clear(), crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_LIB, rng_t::destroy, DESTROY_IF, free(), group, INIT, chunk_t::len, lib, chunk_t::ptr, random, rng, and RNG_STRONG.
Referenced by gcrypt_dh_create(), and gcrypt_dh_create_custom().
 {
     private_gcrypt_dh_t *this;
     gcry_error_t err;
     chunk_t random;
     rng_t *rng;
     INIT(this,
         .public = {
             .dh = {
                 .get_shared_secret = _get_shared_secret,
                 .set_other_public_value = _set_other_public_value,
                 .get_my_public_value = _get_my_public_value,
                 .set_private_value = _set_private_value,
                 .get_dh_group = _get_dh_group,
                 .destroy = _destroy,
             },
         },
         .group = group,
         .p_len = p.len,
     );
     err = gcry_mpi_scan(&this->p, GCRYMPI_FMT_USG, p.ptr, p.len, NULL);
     if (err)
     {
         DBG1(DBG_LIB, "importing mpi modulus failed: %s", gpg_strerror(err));
         free(this);
         return NULL;
     }
     err = gcry_mpi_scan(&this->g, GCRYMPI_FMT_USG, g.ptr, g.len, NULL);
     if (err)
     {
         DBG1(DBG_LIB, "importing mpi generator failed: %s", gpg_strerror(err));
         gcry_mpi_release(this->p);
         free(this);
         return NULL;
     }
     rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
     if (rng && rng->allocate_bytes(rng, exp_len, &random))
     {   /* prefer external randomizer */
         rng->destroy(rng);
         err = gcry_mpi_scan(&this->xa, GCRYMPI_FMT_USG,
                             random.ptr, random.len, NULL);
         chunk_clear(&random);
         if (err)
         {
             DBG1(DBG_LIB, "importing mpi xa failed: %s", gpg_strerror(err));
             gcry_mpi_release(this->p);
             gcry_mpi_release(this->g);
             free(this);
             return NULL;
         }
     }
     else
     {   /* fallback to gcrypt internal randomizer, shouldn't ever happen */
         DESTROY_IF(rng);
         this->xa = gcry_mpi_new(exp_len * 8);
         gcry_mpi_randomize(this->xa, exp_len * 8, GCRY_STRONG_RANDOM);
     }
     if (exp_len == this->p_len)
     {
         /* achieve bitsof(p)-1 by setting MSB to 0 */
         gcry_mpi_clear_bit(this->xa, exp_len * 8 - 1);
     }
     this->ya = gcry_mpi_new(this->p_len * 8);
     gcry_mpi_powm(this->ya, this->g, this->xa, this->p);
     return &this->public;
 }
static chunk_t export_mpi (gcry_mpi_t value, size_t len) static
export a gcry_mpi to an allocated chunk of len bytes
Definition at line 126 of file gcrypt_dh.c.
References chunk_alloc, chunk_t::len, memmove, memset, and chunk_t::ptr.
Referenced by METHOD().
 {
     chunk_t chunk;
     size_t written;
     chunk = chunk_alloc(len);
     gcry_mpi_print(GCRYMPI_FMT_USG, chunk.ptr, chunk.len, &written, value);
     if (written < len)
     {   /* right-align number of written bytes in chunk */
         memmove(chunk.ptr + (len - written), chunk.ptr, written);
         memset(chunk.ptr, 0, len - written);
     }
     return chunk;
 }
METHOD (diffie_hellman_t , set_other_public_value , bool , private_gcrypt_dh_t * this, chunk_t value)
Definition at line 76 of file gcrypt_dh.c.
References DBG1, DBG_LIB, diffie_hellman_verify_value(), FALSE, group, chunk_t::len, and chunk_t::ptr.
 {
     gcry_mpi_t p_min_1;
     gcry_error_t err;
     if (!diffie_hellman_verify_value(this->group, value))
     {
         return FALSE;
     }
     if (this->yb)
     {
         gcry_mpi_release(this->yb);
         this->yb = NULL;
     }
     err = gcry_mpi_scan(&this->yb, GCRYMPI_FMT_USG, value.ptr, value.len, NULL);
     if (err)
     {
         DBG1(DBG_LIB, "importing mpi yb failed: %s", gpg_strerror(err));
         return FALSE;
     }
     p_min_1 = gcry_mpi_new(this->p_len * 8);
     gcry_mpi_sub_ui(p_min_1, this->p, 1);
     /* check public value:
      * 1. 0 or 1 is invalid as 0^a = 0 and 1^a = 1
      * 2. a public value larger or equal the modulus is invalid */
     if (gcry_mpi_cmp_ui(this->yb, 1) > 0 &&
         gcry_mpi_cmp(this->yb, p_min_1) < 0)
     {
         if (!this->zz)
         {
             this->zz = gcry_mpi_new(this->p_len * 8);
         }
         gcry_mpi_powm(this->zz, this->yb, this->xa, this->p);
     }
     else
     {
         DBG1(DBG_LIB, "public DH value verification failed:"
              " y < 2 || y > p - 1 ");
     }
     gcry_mpi_release(p_min_1);
     return this->zz != NULL;
 }
METHOD (diffie_hellman_t , get_my_public_value , bool , private_gcrypt_dh_t * this, chunk_t * value)
Definition at line 141 of file gcrypt_dh.c.
References export_mpi(), and TRUE.
 {
     *value = export_mpi(this->ya, this->p_len);
     return TRUE;
 }
METHOD (diffie_hellman_t , set_private_value , bool , private_gcrypt_dh_t * this, chunk_t value)
Definition at line 148 of file gcrypt_dh.c.
References g, chunk_t::len, and chunk_t::ptr.
 {
     gcry_error_t err;
     gcry_mpi_t xa;
     err = gcry_mpi_scan(&xa, GCRYMPI_FMT_USG, value.ptr, value.len, NULL);
     if (!err)
     {
         gcry_mpi_release(this->xa);
         this->xa = xa;
         gcry_mpi_powm(this->ya, this->g, this->xa, this->p);
         gcry_mpi_release(this->zz);
         this->zz = NULL;
     }
     return !err;
 }
METHOD (diffie_hellman_t , get_shared_secret , bool , private_gcrypt_dh_t * this, chunk_t * secret)
Definition at line 166 of file gcrypt_dh.c.
References export_mpi(), FALSE, and TRUE.
 {
     if (!this->zz)
     {
         return FALSE;
     }
     *secret = export_mpi(this->zz, this->p_len);
     return TRUE;
 }
METHOD (diffie_hellman_t , get_dh_group , diffie_hellman_group_t , private_gcrypt_dh_t * this)
Definition at line 177 of file gcrypt_dh.c.
References group.
 {
     return this->group;
 }
METHOD (diffie_hellman_t , destroy , void , private_gcrypt_dh_t * this)
Definition at line 183 of file gcrypt_dh.c.
References free(), and g.
 {
     gcry_mpi_release(this->p);
     gcry_mpi_release(this->xa);
     gcry_mpi_release(this->ya);
     gcry_mpi_release(this->g);
     gcry_mpi_release(this->yb);
     gcry_mpi_release(this->zz);
     free(this);
 }