strongSwan: uci_creds.c File Reference
uci_creds.c File Reference
#include "uci_creds.h"
#include <daemon.h>
#include <credentials/keys/shared_key.h>
#include <utils/identification.h>
Classes
struct private_uci_creds_t
struct shared_enumerator_t
Typedefs
typedef struct private_uci_creds_t private_uci_creds_t
Functions
METHOD (enumerator_t, shared_enumerator_enumerate, bool, shared_enumerator_t *this, shared_key_t **key, id_match_t *me, id_match_t *other)
METHOD (enumerator_t, shared_enumerator_destroy, void, shared_enumerator_t *this)
METHOD (credential_set_t, create_shared_enumerator, enumerator_t *, private_uci_creds_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
METHOD (uci_creds_t, destroy, void, private_uci_creds_t *this)
uci_creds_t * uci_creds_create (uci_parser_t *parser)
Typedef Documentation
typedef struct private_uci_creds_t private_uci_creds_t
Definition at line 24 of file uci_creds.c.
Function Documentation
METHOD (enumerator_t , shared_enumerator_enumerate , bool , shared_enumerator_t * this, shared_key_t ** key, id_match_t * me, id_match_t * other)
Definition at line 54 of file uci_creds.c.
References chunk_clone, chunk_create(), identification_t::destroy, DESTROY_IF, FALSE, ID_MATCH_ANY, identification_create_from_string(), SHARED_IKE, shared_key_create(), and TRUE.
 {
     char *local_id, *remote_id, *psk;
     identification_t *local, *remote;
     while (TRUE)
     {
         /* defaults */
         local_id = "%any";
         remote_id = "%any";
         psk = NULL;
         if (!this->inner->enumerate(this->inner, NULL,
                                     &local_id, &remote_id, &psk))
         {
             return FALSE;
         }
         if (psk == NULL)
         {
             continue;
         }
         if (me)
         {
             local = identification_create_from_string(local_id);
             *me = this->me ? this->me->matches(this->me, local)
                            : ID_MATCH_ANY;
             local->destroy(local);
             if (!*me)
             {
                 continue;
             }
         }
         if (other)
         {
             remote = identification_create_from_string(remote_id);
             *other = this->other ? this->other->matches(this->other, remote)
                                  : ID_MATCH_ANY;
             remote->destroy(remote);
             if (!*other)
             {
                 continue;
             }
         }
         break;
     }
     DESTROY_IF(this->current);
     this->current = shared_key_create(SHARED_IKE,
                                 chunk_clone(chunk_create(psk, strlen(psk))));
     *key = this->current;
     return TRUE;
 }
METHOD (enumerator_t , shared_enumerator_destroy , void , shared_enumerator_t * this)
Definition at line 108 of file uci_creds.c.
References DESTROY_IF, and free().
 {
     this->inner->destroy(this->inner);
     DESTROY_IF(this->current);
     free(this);
 }
METHOD (credential_set_t , create_shared_enumerator , enumerator_t * , private_uci_creds_t * this, shared_key_type_t type, identification_t * me, identification_t * other)
Definition at line 116 of file uci_creds.c.
References destroy(), free(), INIT, shared_enumerator_t::inner, parser, shared_enumerator_t::public, and SHARED_IKE.
 {
     shared_enumerator_t *e;
     if (type != SHARED_IKE)
     {
         return NULL;
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_shared_enumerator_enumerate,
             .destroy = _shared_enumerator_destroy,
         },
         .me = me,
         .other = other,
         .inner = this->parser->create_section_enumerator(this->parser,
                                 "local_id", "remote_id", "psk", NULL),
     );
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (uci_creds_t , destroy , void , private_uci_creds_t * this)
Definition at line 145 of file uci_creds.c.
References free().
 {
     free(this);
 }