strongSwan: tcg_pts_attr_req_func_comp_evid.c File Reference
tcg_pts_attr_req_func_comp_evid.c File Reference
#include "tcg_pts_attr_req_func_comp_evid.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_req_func_comp_evid_t
struct entry_t
Macros
#define PTS_REQ_FUNC_COMP_EVID_SIZE 12
#define PTS_REQ_FUNC_COMP_FAMILY_MASK 0xC0
Typedefs
typedef struct
private_tcg_pts_attr_req_func_comp_evid_t private_tcg_pts_attr_req_func_comp_evid_t
typedef struct entry_t entry_t
Functions
static bool entry_filter (void *null, entry_t **entry, u_int8_t *flags, void *i2, u_int32_t *depth, void *i3, pts_comp_func_name_t **name)
static void free_entry (entry_t *this)
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_req_func_comp_evid_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_req_func_comp_evid_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_req_func_comp_evid_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_req_func_comp_evid_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_req_func_comp_evid_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_req_func_comp_evid_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_req_func_comp_evid_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_req_func_comp_evid_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_req_func_comp_evid_t *this)
METHOD (tcg_pts_attr_req_func_comp_evid_t, add_component, void, private_tcg_pts_attr_req_func_comp_evid_t *this, u_int8_t flags, u_int32_t depth, pts_comp_func_name_t *name)
METHOD (tcg_pts_attr_req_func_comp_evid_t, get_count, int, private_tcg_pts_attr_req_func_comp_evid_t *this)
METHOD (tcg_pts_attr_req_func_comp_evid_t, create_enumerator, enumerator_t *, private_tcg_pts_attr_req_func_comp_evid_t *this)
pa_tnc_attr_t * tcg_pts_attr_req_func_comp_evid_create (void)
pa_tnc_attr_t * tcg_pts_attr_req_func_comp_evid_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define PTS_REQ_FUNC_COMP_EVID_SIZE 12
Request Functional Component Evidence see section 3.14.1 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | Sub-component Depth (for Component #1) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Component Functional Name #1 | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Component Functional Name #1 | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | ........ | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | Sub-component Depth (for Component N) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Component Functional Name N | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Component Functional Name N | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ Component Functional Name Structure (see section 5.1 of PTS Protocol: Binding to TNC IF-M Specification)
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Component Functional Name Vendor ID |Fam| Qualifier | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Component Functional Name | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 63 of file tcg_pts_attr_req_func_comp_evid.c.
Referenced by METHOD().
#define PTS_REQ_FUNC_COMP_FAMILY_MASK 0xC0
Definition at line 64 of file tcg_pts_attr_req_func_comp_evid.c.
Referenced by METHOD().
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 107 of file tcg_pts_attr_req_func_comp_evid.c.
typedef struct private_tcg_pts_attr_req_func_comp_evid_t private_tcg_pts_attr_req_func_comp_evid_t
Definition at line 25 of file tcg_pts_attr_req_func_comp_evid.c.
Function Documentation
static bool entry_filter (void * null, entry_t ** entry, u_int8_t * flags, void * i2, u_int32_t * depth, void * i3, pts_comp_func_name_t ** name) static
Enumerate functional component entries
Definition at line 121 of file tcg_pts_attr_req_func_comp_evid.c.
References TRUE.
Referenced by METHOD().
 {
     *flags = (*entry)->flags;
     *depth = (*entry)->depth;
     *name  = (*entry)->name;
     return TRUE;
 }
static void free_entry (entry_t * this) static
Free an entry_t object
Definition at line 135 of file tcg_pts_attr_req_func_comp_evid.c.
References free(), and name.
Referenced by METHOD().
 {
     if (this)
     {
         this->name->destroy(this->name);
         free(this);
     }
 }
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 144 of file tcg_pts_attr_req_func_comp_evid.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 150 of file tcg_pts_attr_req_func_comp_evid.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 156 of file tcg_pts_attr_req_func_comp_evid.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_req_func_comp_evid_t * this, bool noskip)
Definition at line 162 of file tcg_pts_attr_req_func_comp_evid.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 168 of file tcg_pts_attr_req_func_comp_evid.c.
References bio_writer_create(), linked_list_t::create_enumerator, entry_t::depth, enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::extract_buf, entry_t::flags, length, list, entry_t::name, PTS_REQ_FUNC_COMP_EVID_SIZE, value, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     entry_t *entry;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PTS_REQ_FUNC_COMP_EVID_SIZE);
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         writer->write_uint8 (writer, entry->flags);
         writer->write_uint24(writer, entry->depth);
         writer->write_uint24(writer, entry->name->get_vendor_id(entry->name));
         writer->write_uint8 (writer, entry->name->get_qualifier(entry->name));
         writer->write_uint32(writer, entry->name->get_name(entry->name));
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_req_func_comp_evid_t * this, u_int32_t * offset)
Definition at line 197 of file tcg_pts_attr_req_func_comp_evid.c.
References bio_reader_create(), DBG1, DBG_TNC, entry_t::depth, bio_reader_t::destroy, end, FAILED, entry_t::flags, flags, linked_list_t::insert_last, list, malloc_thing, name, entry_t::name, NEED_MORE, pts_comp_func_name_create(), PTS_REQ_FUNC_COMP_EVID_SIZE, PTS_REQ_FUNC_COMP_FAMILY_MASK, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, status, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int32_t depth, vendor_id, name;
     u_int8_t flags, fam_and_qualifier, qualifier;
     status_t status = FAILED;
     entry_t *entry = NULL;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_REQ_FUNC_COMP_EVID_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for Request Functional "
                       "Component Evidence");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     while (reader->remaining(reader))
     {
         if (!reader->read_uint8(reader, &flags))
         {
             DBG1(DBG_TNC, "insufficient data for PTS Request Functional "
                           "Component Evidence Flags");
             goto end;
         }
         if (!reader->read_uint24(reader, &depth))
         {
             DBG1(DBG_TNC, "insufficient data for PTS Request Functional "
                           "Component Evidence Sub Component Depth");
             goto end;
         }
         if (!reader->read_uint24(reader, &vendor_id))
         {
             DBG1(DBG_TNC, "insufficient data for PTS Request Functional "
                           "Component Evidence Component Name Vendor ID");
             goto end;
         }
         if (!reader->read_uint8(reader, &fam_and_qualifier))
         {
             DBG1(DBG_TNC, "insufficient data for PTS Request Functional "
                           "Component Evidence Family and Qualifier");
             goto end;
         }
         if (fam_and_qualifier & PTS_REQ_FUNC_COMP_FAMILY_MASK)
         {
             DBG1(DBG_TNC, "the Functional Name Encoding Family "
                           "is not Binary Enumeration");
             goto end;
         }
         if (!reader->read_uint32(reader, &name))
         {
             DBG1(DBG_TNC, "insufficient data for PTS Request Functional "
                           "Component Evidence Component Functional Name");
             goto end;
         }
         qualifier = fam_and_qualifier & ~PTS_REQ_FUNC_COMP_FAMILY_MASK;
         entry = malloc_thing(entry_t);
         entry->flags = flags;
         entry->depth = depth;
         entry->name = pts_comp_func_name_create(vendor_id, name, qualifier);
         this->list->insert_last(this->list, entry);
     }
     status = SUCCESS;
 end:
     reader->destroy(reader);
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_req_func_comp_evid_t * this, chunk_t segment)
Definition at line 274 of file tcg_pts_attr_req_func_comp_evid.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 280 of file tcg_pts_attr_req_func_comp_evid.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 287 of file tcg_pts_attr_req_func_comp_evid.c.
References linked_list_t::destroy_function, free(), free_entry(), list, ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         this->list->destroy_function(this->list, (void *)free_entry);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_req_func_comp_evid_t , add_component , void , private_tcg_pts_attr_req_func_comp_evid_t * this, u_int8_t flags, u_int32_t depth, pts_comp_func_name_t * name)
Definition at line 298 of file tcg_pts_attr_req_func_comp_evid.c.
References pts_comp_func_name_t::clone, entry_t::depth, entry_t::flags, flags, linked_list_t::insert_last, list, malloc_thing, and entry_t::name.
 {
     entry_t *entry;
     entry = malloc_thing(entry_t);
     entry->flags = flags;
     entry->depth = depth;
     entry->name = name->clone(name);
     this->list->insert_last(this->list, entry);
 }
METHOD (tcg_pts_attr_req_func_comp_evid_t , get_count , int , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 311 of file tcg_pts_attr_req_func_comp_evid.c.
References linked_list_t::get_count, and list.
 {
     return this->list->get_count(this->list);
 }
METHOD (tcg_pts_attr_req_func_comp_evid_t , create_enumerator , enumerator_t * , private_tcg_pts_attr_req_func_comp_evid_t * this)
Definition at line 317 of file tcg_pts_attr_req_func_comp_evid.c.
References linked_list_t::create_enumerator, entry_filter(), enumerator_create_filter(), and list.
 {
     return enumerator_create_filter(this->list->create_enumerator(this->list),
                                    (void*)entry_filter, NULL, NULL);
 }