strongSwan: psk_v1_authenticator.c File Reference
psk_v1_authenticator.c File Reference
#include "psk_v1_authenticator.h"
#include <daemon.h>
#include <sa/ikev1/keymat_v1.h>
#include <encoding/payloads/hash_payload.h>
Classes
struct private_psk_v1_authenticator_t
Typedefs
typedef struct
private_psk_v1_authenticator_t private_psk_v1_authenticator_t
Functions
METHOD (authenticator_t, build, status_t, private_psk_v1_authenticator_t *this, message_t *message)
METHOD (authenticator_t, process, status_t, private_psk_v1_authenticator_t *this, message_t *message)
METHOD (authenticator_t, destroy, void, private_psk_v1_authenticator_t *this)
psk_v1_authenticator_t * psk_v1_authenticator_create (ike_sa_t *ike_sa, bool initiator, diffie_hellman_t *dh, chunk_t dh_value, chunk_t sa_payload, chunk_t id_payload, bool hybrid)
Typedef Documentation
typedef struct private_psk_v1_authenticator_t private_psk_v1_authenticator_t
Definition at line 22 of file psk_v1_authenticator.c.
Function Documentation
METHOD (authenticator_t , build , status_t , private_psk_v1_authenticator_t * this, message_t * message)
Definition at line 70 of file psk_v1_authenticator.c.
References message_t::add_payload, dh, FAILED, free(), keymat_v1_t::get_hash, hash, hash_payload_create(), hash_payload_t::payload_interface, PLV1_HASH, chunk_t::ptr, hash_payload_t::set_hash, and SUCCESS.
 {
     hash_payload_t *hash_payload;
     keymat_v1_t *keymat;
     chunk_t hash, dh;
     if (!this->dh->get_my_public_value(this->dh, &dh))
     {
         return FAILED;
     }
     keymat = (keymat_v1_t*)this->ike_sa->get_keymat(this->ike_sa);
     if (!keymat->get_hash(keymat, this->initiator, dh, this->dh_value,
                     this->ike_sa->get_id(this->ike_sa), this->sa_payload,
                     this->id_payload, &hash))
     {
         free(dh.ptr);
         return FAILED;
     }
     free(dh.ptr);
     hash_payload = hash_payload_create(PLV1_HASH);
     hash_payload->set_hash(hash_payload, hash);
     message->add_payload(message, &hash_payload->payload_interface);
     free(hash.ptr);
     return SUCCESS;
 }
METHOD (authenticator_t , process , status_t , private_psk_v1_authenticator_t * this, message_t * message)
Definition at line 99 of file psk_v1_authenticator.c.
References auth_cfg_t::add, AUTH_CLASS_PSK, AUTH_RULE_AUTH_CLASS, chunk_equals_const(), DBG1, DBG_IKE, dh, FAILED, FALSE, free(), hash_payload_t::get_hash, keymat_v1_t::get_hash, message_t::get_payload, hash, PLV1_HASH, chunk_t::ptr, and SUCCESS.
 {
     hash_payload_t *hash_payload;
     keymat_v1_t *keymat;
     chunk_t hash, dh;
     auth_cfg_t *auth;
     hash_payload = (hash_payload_t*)message->get_payload(message, PLV1_HASH);
     if (!hash_payload)
     {
         DBG1(DBG_IKE, "HASH payload missing in message");
         return FAILED;
     }
     if (!this->dh->get_my_public_value(this->dh, &dh))
     {
         return FAILED;
     }
     keymat = (keymat_v1_t*)this->ike_sa->get_keymat(this->ike_sa);
     if (!keymat->get_hash(keymat, !this->initiator, this->dh_value, dh,
                     this->ike_sa->get_id(this->ike_sa), this->sa_payload,
                     this->id_payload, &hash))
     {
         free(dh.ptr);
         return FAILED;
     }
     free(dh.ptr);
     if (chunk_equals_const(hash, hash_payload->get_hash(hash_payload)))
     {
         free(hash.ptr);
         if (!this->hybrid)
         {
             auth = this->ike_sa->get_auth_cfg(this->ike_sa, FALSE);
             auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PSK);
         }
         return SUCCESS;
     }
     free(hash.ptr);
     DBG1(DBG_IKE, "calculated HASH does not match HASH payload");
     return FAILED;
 }
METHOD (authenticator_t , destroy , void , private_psk_v1_authenticator_t * this)
Definition at line 142 of file psk_v1_authenticator.c.
References chunk_free(), and free().
 {
     chunk_free(&this->id_payload);
     free(this);
 }