strongSwan: bliss_public_key.c File Reference
bliss_public_key.c File Reference
#include "bliss_public_key.h"
#include "bliss_signature.h"
#include "bliss_bitpacker.h"
#include "bliss_fft.h"
#include "bliss_utils.h"
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <asn1/oid.h>
Classes
struct private_bliss_public_key_t
Macros
#define BLISS_SUBJECT_PUBLIC_KEY_ALGORITHM 1
#define BLISS_SUBJECT_PUBLIC_KEY 2
Typedefs
typedef struct
private_bliss_public_key_t private_bliss_public_key_t
Functions
METHOD (public_key_t, get_type, key_type_t, private_bliss_public_key_t *this)
static bool verify_bliss (private_bliss_public_key_t *this, hash_algorithm_t alg, chunk_t data, chunk_t signature)
METHOD (public_key_t, verify, bool, private_bliss_public_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
METHOD (public_key_t, encrypt_, bool, private_bliss_public_key_t *this, encryption_scheme_t scheme, chunk_t plain, chunk_t *crypto)
METHOD (public_key_t, get_keysize, int, private_bliss_public_key_t *this)
METHOD (public_key_t, get_encoding, bool, private_bliss_public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (public_key_t, get_fingerprint, bool, private_bliss_public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (public_key_t, get_ref, public_key_t *, private_bliss_public_key_t *this)
METHOD (public_key_t, destroy, void, private_bliss_public_key_t *this)
bliss_public_key_t * bliss_public_key_load (key_type_t type, va_list args)
bool bliss_public_key_from_asn1 (chunk_t object, bliss_param_set_t *set, uint32_t **pubkey)
chunk_t bliss_public_key_encode (uint32_t *pubkey, bliss_param_set_t *set)
chunk_t bliss_public_key_info_encode (int oid, uint32_t *pubkey, bliss_param_set_t *set)
bool bliss_public_key_fingerprint (int oid, uint32_t *pubkey, bliss_param_set_t *set, cred_encoding_type_t type, chunk_t *fp)
Variables
static const asn1Object_t pubkeyObjects []
Macro Definition Documentation
#define BLISS_SUBJECT_PUBLIC_KEY 2
Definition at line 296 of file bliss_public_key.c.
Referenced by bliss_public_key_load().
#define BLISS_SUBJECT_PUBLIC_KEY_ALGORITHM 1
Definition at line 295 of file bliss_public_key.c.
Referenced by bliss_public_key_load().
Typedef Documentation
typedef struct private_bliss_public_key_t private_bliss_public_key_t
Definition at line 26 of file bliss_public_key.c.
Function Documentation
METHOD (public_key_t , get_type , key_type_t , private_bliss_public_key_t * this)
Definition at line 53 of file bliss_public_key.c.
References KEY_BLISS.
 {
     return KEY_BLISS;
 }
METHOD (public_key_t , verify , bool , private_bliss_public_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
Definition at line 190 of file bliss_public_key.c.
References DBG1, DBG_LIB, FALSE, HASH_SHA256, HASH_SHA384, HASH_SHA3_256, HASH_SHA3_384, HASH_SHA3_512, HASH_SHA512, SIGN_BLISS_WITH_SHA2_256, SIGN_BLISS_WITH_SHA2_384, SIGN_BLISS_WITH_SHA2_512, SIGN_BLISS_WITH_SHA3_256, SIGN_BLISS_WITH_SHA3_384, SIGN_BLISS_WITH_SHA3_512, signature_scheme_names, and verify_bliss().
 {
     switch (scheme)
     {
         case SIGN_BLISS_WITH_SHA2_256:
             return verify_bliss(this, HASH_SHA256, data, signature);
         case SIGN_BLISS_WITH_SHA2_384:
             return verify_bliss(this, HASH_SHA384, data, signature);
         case SIGN_BLISS_WITH_SHA2_512:
             return verify_bliss(this, HASH_SHA512, data, signature);
         case SIGN_BLISS_WITH_SHA3_256:
             return verify_bliss(this, HASH_SHA3_256, data, signature);
         case SIGN_BLISS_WITH_SHA3_384:
             return verify_bliss(this, HASH_SHA3_384, data, signature);
         case SIGN_BLISS_WITH_SHA3_512:
             return verify_bliss(this, HASH_SHA3_512, data, signature);
         default:
             DBG1(DBG_LIB, "signature scheme %N not supported by BLISS",
                  signature_scheme_names, scheme);
             return FALSE;
     }
 }
METHOD (public_key_t , encrypt_ , bool , private_bliss_public_key_t * this, encryption_scheme_t scheme, chunk_t plain, chunk_t * crypto)
Definition at line 215 of file bliss_public_key.c.
References DBG1, DBG_LIB, encryption_scheme_names, and FALSE.
 {
     DBG1(DBG_LIB, "encryption scheme %N not supported",
                    encryption_scheme_names, scheme);
     return FALSE;
 }
METHOD (public_key_t , get_keysize , int , private_bliss_public_key_t * this)
Definition at line 224 of file bliss_public_key.c.
 {
     return this->set->strength;
 }
METHOD (public_key_t , get_encoding , bool , private_bliss_public_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 230 of file bliss_public_key.c.
References bliss_public_key_info_encode(), chunk_clear(), CRED_PART_BLISS_PUB_ASN1_DER, CRED_PART_END, cred_encoding_t::encode, encoding, library_t::encoding, lib, PUBKEY_SPKI_ASN1_DER, and TRUE.
 {
     bool success = TRUE;
     *encoding = bliss_public_key_info_encode(this->set->oid, this->A, this->set);
     if (type != PUBKEY_SPKI_ASN1_DER)
     {
         chunk_t asn1_encoding = *encoding;
         success = lib->encoding->encode(lib->encoding, type,
                         NULL, encoding, CRED_PART_BLISS_PUB_ASN1_DER,
                         asn1_encoding, CRED_PART_END);
         chunk_clear(&asn1_encoding);
     }
     return success;
 }
METHOD (public_key_t , get_fingerprint , bool , private_bliss_public_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 250 of file bliss_public_key.c.
References bliss_public_key_fingerprint(), cred_encoding_t::cache, library_t::encoding, cred_encoding_t::get_cache, lib, and TRUE.
 {
     bool success;
     if (lib->encoding->get_cache(lib->encoding, type, this, fp))
     {
         return TRUE;
     }
     success = bliss_public_key_fingerprint(this->set->oid, this->A,
                                            this->set, type, fp);
     if (success)
     {
         lib->encoding->cache(lib->encoding, type, this, *fp);
     }
     return success;
 }
METHOD (public_key_t , get_ref , public_key_t * , private_bliss_public_key_t * this)
Definition at line 268 of file bliss_public_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (public_key_t , destroy , void , private_bliss_public_key_t * this)
Definition at line 275 of file bliss_public_key.c.
References cred_encoding_t::clear_cache, library_t::encoding, free(), lib, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         lib->encoding->clear_cache(lib->encoding, this);
         free(this->A);
         free(this);
     }
 }
static bool verify_bliss (private_bliss_public_key_t * this, hash_algorithm_t alg, chunk_t data, chunk_t signature) static
Verify a BLISS signature based on a SHA-512 hash
Definition at line 62 of file bliss_public_key.c.
References bliss_fft_create(), bliss_signature_create_from_data(), bliss_utils_check_norms(), bliss_utils_generate_c(), bliss_utils_round_and_drop(), chunk_create(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG3, DBG_LIB, bliss_signature_t::destroy, bliss_fft_t::destroy, hasher_t::destroy, end, FALSE, free(), hasher_t::get_hash, hasher_t::get_hash_size, bliss_signature_t::get_parameters, HASH_SHA512, HASH_SIZE_SHA512, hasher, lib, malloc(), n, q, sig, bliss_fft_t::transform, and TRUE.
Referenced by METHOD().
 {
     int i, n;
     int32_t *z1, *u;
     int16_t *ud, *z2d;
     uint16_t q, q2, p, *c_indices, *indices;
     uint32_t *az;
     uint8_t data_hash_buf[HASH_SIZE_SHA512];
     chunk_t data_hash;
     hasher_t *hasher;
     hash_algorithm_t oracle_alg;
     bliss_fft_t *fft;
     bliss_signature_t *sig;
     bool success = FALSE;
     /* Create data hash using configurable hash algorithm */
     hasher = lib->crypto->create_hasher(lib->crypto, alg);
     if (!hasher )
     {
         return FALSE;
     }
     data_hash = chunk_create(data_hash_buf, hasher->get_hash_size(hasher));
     if (!hasher->get_hash(hasher, data, data_hash_buf))
     {
         hasher->destroy(hasher);
         return FALSE;
     }
     hasher->destroy(hasher);
     sig = bliss_signature_create_from_data(this->set, signature);
     if (!sig)
     {
         return FALSE;
     }
     sig->get_parameters(sig, &z1, &z2d, &c_indices);
     if (!bliss_utils_check_norms(this->set, z1, z2d))
     {
         sig->destroy(sig);
         return FALSE;
     }
     /* MGF1 hash algorithm to be used for random oracle */
     oracle_alg = HASH_SHA512;
     /* Initialize a couple of needed variables */
     n  = this->set->n;
     q  = this->set->q;
     p  = this->set->p;
     q2 = 2 * q;
     az  = malloc(n * sizeof(uint32_t));
     u   = malloc(n * sizeof(int32_t));
     ud  = malloc(n * sizeof(int16_t));
     indices   = malloc(this->set->kappa * sizeof(uint16_t));
     for (i = 0; i < n; i++)
     {
         az[i] = z1[i] < 0 ? q + z1[i] : z1[i];
     }
     fft = bliss_fft_create(this->set->fft_params);
     fft->transform(fft, az, az, FALSE);
     for (i = 0; i < n; i++)
     {
         az[i] = (this->A[i] * az[i]) % q;
     }
     fft->transform(fft, az, az, TRUE);
     for (i = 0; i < n; i++)
     {
         u[i] = (2 * this->set->q2_inv * az[i]) % q2;
     }
     for (i = 0; i < this->set->kappa; i++)
     {
         u[c_indices[i]] = (u[c_indices[i]] + q * this->set->q2_inv) % q2;
     }
     bliss_utils_round_and_drop(this->set, u, ud);
     for (i = 0; i < n; i++)
     {
         ud[i] += z2d[i];
         if (ud[i] < 0)
         {
             ud[i] += p;
         }
         else if (ud[i] >= p)
         {
             ud[i] -= p;
         }
     }
     /* Detailed debugging information */
     DBG3(DBG_LIB, "  i    u[i]  ud[i] z2d[i]");
     for (i = 0; i < n; i++)
     {
         DBG3(DBG_LIB, "%3d  %6d   %4d  %4d", i, u[i], ud[i], z2d[i]);
     }
     if (!bliss_utils_generate_c(oracle_alg, data_hash, ud, this->set, indices))
     {
         goto end;
     }
     for (i = 0; i < this->set->kappa; i++)
     {
         if (indices[i] != c_indices[i])
         {
             DBG1(DBG_LIB, "signature verification failed");
             goto end;
         }
     }
     success = TRUE;
 end:
     /* cleanup */
     sig->destroy(sig);
     fft->destroy(fft);
     free(az);
     free(u);
     free(ud);
     free(indices);
     return success;
 }
Variable Documentation
const asn1Object_t pubkeyObjects[] static
Initial value:
= {
    { 0, "subjectPublicKeyInfo",ASN1_SEQUENCE,      ASN1_OBJ  },
    { 1,   "algorithm",         ASN1_EOC,           ASN1_RAW  },
    { 1,   "subjectPublicKey",  ASN1_BIT_STRING,    ASN1_BODY },
    { 0, "exit",                ASN1_EOC,           ASN1_EXIT }
}
ASN.1 definition of a BLISS public key
Definition at line 289 of file bliss_public_key.c.