strongSwan: x509_cert
x509_cert
x509
Classes
struct x509_cert_t
Typedefs
typedef struct x509_cert_t x509_cert_t
Functions
x509_cert_t * x509_cert_load (certificate_type_t type, va_list args)
x509_cert_t * x509_cert_gen (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct x509_cert_t x509_cert_t
Definition at line 24 of file x509_cert.h.
Function Documentation
x509_cert_t* x509_cert_gen (certificate_type_t type, va_list args)
Generate a X.509 certificate.
To issue a self-signed certificate, the function takes: BUILD_SUBJECT, BUILD_SUBJECT_ALTNAMES, BUILD_SIGNING_KEY, BUILD_X509_FLAG, BUILD_NOT_BEFORE_TIME, BUILD_NOT_AFTER_TIME, BUILD_SERIAL, BUILD_DIGEST_ALG. To issue certificates from a CA, additionally pass: BUILD_SIGNING_CERT and BUILD_PUBLIC_KEY.
Parameters
type certificate type, CERT_X509 only
args builder_part_t argument list
Returns
X.509 certificate, NULL on failure
See header.
Definition at line 2410 of file x509_cert.c.
References BUILD_CERTIFICATE_POLICIES, BUILD_CRL_DISTRIBUTION_POINTS, BUILD_DIGEST_ALG, BUILD_END, BUILD_EXCLUDED_NAME_CONSTRAINTS, BUILD_NOT_AFTER_TIME, BUILD_NOT_BEFORE_TIME, BUILD_OCSP_ACCESS_LOCATIONS, BUILD_PATHLEN, BUILD_PERMITTED_NAME_CONSTRAINTS, BUILD_POLICY_INHIBIT_ANY, BUILD_POLICY_INHIBIT_MAPPING, BUILD_POLICY_MAPPINGS, BUILD_POLICY_REQUIRE_EXPLICIT, BUILD_PUBLIC_KEY, BUILD_SERIAL, BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, BUILD_SUBJECT, BUILD_SUBJECT_ALTNAMES, BUILD_X509_FLAG, cert, private_x509_cert_t::cert_policies, chunk_clone, identification_t::clone, constraint, x509_cert_policy_t::cps_uri, create_empty(), linked_list_t::create_enumerator, private_x509_cert_t::crl_uris, enumerator_t::destroy, destroy(), enumerator_t::enumerate, private_x509_cert_t::excluded_names, private_x509_cert_t::flags, generate(), public_key_t::get_ref, HASH_SHA1, id, in, private_x509_cert_t::inhibit_any, private_x509_cert_t::inhibit_mapping, INIT, linked_list_t::insert_last, x509_policy_mapping_t::issuer, x509_cdp_t::issuer, list, private_x509_cert_t::notAfter, private_x509_cert_t::notBefore, private_x509_cert_t::ocsp_uris, x509_cert_policy_t::oid, private_x509_cert_t::pathLenConstraint, private_x509_cert_t::permitted_names, private_x509_cert_t::policy_mappings, private_x509_cert_t::public, private_x509_cert_t::public_key, private_x509_cert_t::require_explicit, private_x509_cert_t::serialNumber, strdup, strdupnull(), x509_policy_mapping_t::subject, private_x509_cert_t::subject, private_x509_cert_t::subjectAltNames, TRUE, x509_cert_policy_t::unotice_text, uri, x509_cdp_t::uri, and X509_NO_CONSTRAINT.
Referenced by METHOD().
 {
     private_x509_cert_t *cert;
     certificate_t *sign_cert = NULL;
     private_key_t *sign_key = NULL;
     hash_algorithm_t digest_alg = HASH_SHA1;
     u_int constraint;
     cert = create_empty();
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_X509_FLAG:
                 cert->flags |= va_arg(args, x509_flag_t);
                 continue;
             case BUILD_SIGNING_KEY:
                 sign_key = va_arg(args, private_key_t*);
                 continue;
             case BUILD_SIGNING_CERT:
                 sign_cert = va_arg(args, certificate_t*);
                 continue;
             case BUILD_PUBLIC_KEY:
                 cert->public_key = va_arg(args, public_key_t*);
                 cert->public_key->get_ref(cert->public_key);
                 continue;
             case BUILD_SUBJECT:
                 cert->subject = va_arg(args, identification_t*);
                 cert->subject = cert->subject->clone(cert->subject);
                 continue;
             case BUILD_SUBJECT_ALTNAMES:
             {
                 enumerator_t *enumerator;
                 identification_t *id;
                 linked_list_t *list;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &id))
                 {
                     cert->subjectAltNames->insert_last(cert->subjectAltNames,
                                                     id->clone(id));
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_CRL_DISTRIBUTION_POINTS:
             {
                 enumerator_t *enumerator;
                 linked_list_t *list;
                 x509_cdp_t *in, *cdp;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &in))
                 {
                     INIT(cdp,
                         .uri = strdup(in->uri),
                         .issuer = in->issuer ? in->issuer->clone(in->issuer) : NULL,
                     );
                     cert->crl_uris->insert_last(cert->crl_uris, cdp);
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_OCSP_ACCESS_LOCATIONS:
             {
                 enumerator_t *enumerator;
                 linked_list_t *list;
                 char *uri;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &uri))
                 {
                     cert->ocsp_uris->insert_last(cert->ocsp_uris, strdup(uri));
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_PATHLEN:
                 constraint = va_arg(args, u_int);
                 cert->pathLenConstraint = (constraint < 128) ?
                                            constraint : X509_NO_CONSTRAINT;
                 continue;
             case BUILD_PERMITTED_NAME_CONSTRAINTS:
             {
                 enumerator_t *enumerator;
                 linked_list_t *list;
                 identification_t *constraint;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &constraint))
                 {
                     cert->permitted_names->insert_last(cert->permitted_names,
                                                 constraint->clone(constraint));
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_EXCLUDED_NAME_CONSTRAINTS:
             {
                 enumerator_t *enumerator;
                 linked_list_t *list;
                 identification_t *constraint;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &constraint))
                 {
                     cert->excluded_names->insert_last(cert->excluded_names,
                                                 constraint->clone(constraint));
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_CERTIFICATE_POLICIES:
             {
                 enumerator_t *enumerator;
                 linked_list_t *list;
                 x509_cert_policy_t *policy, *in;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &in))
                 {
                     INIT(policy,
                         .oid = chunk_clone(in->oid),
                         .cps_uri = strdupnull(in->cps_uri),
                         .unotice_text = strdupnull(in->unotice_text),
                     );
                     cert->cert_policies->insert_last(cert->cert_policies, policy);
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_POLICY_MAPPINGS:
             {
                 enumerator_t *enumerator;
                 linked_list_t *list;
                 x509_policy_mapping_t* mapping, *in;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &in))
                 {
                     INIT(mapping,
                         .issuer = chunk_clone(in->issuer),
                         .subject = chunk_clone(in->subject),
                     );
                     cert->policy_mappings->insert_last(cert->policy_mappings,
                                                        mapping);
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_POLICY_REQUIRE_EXPLICIT:
                 constraint = va_arg(args, u_int);
                 cert->require_explicit = (constraint < 128) ?
                                           constraint : X509_NO_CONSTRAINT;
                 continue;
             case BUILD_POLICY_INHIBIT_MAPPING:
                 constraint = va_arg(args, u_int);
                 cert->inhibit_mapping = (constraint < 128) ?
                                          constraint : X509_NO_CONSTRAINT;
                 continue;
             case BUILD_POLICY_INHIBIT_ANY:
                 constraint = va_arg(args, u_int);
                 cert->inhibit_any = (constraint < 128) ?
                                      constraint : X509_NO_CONSTRAINT;
                 continue;
             case BUILD_NOT_BEFORE_TIME:
                 cert->notBefore = va_arg(args, time_t);
                 continue;
             case BUILD_NOT_AFTER_TIME:
                 cert->notAfter = va_arg(args, time_t);
                 continue;
             case BUILD_SERIAL:
                 cert->serialNumber = chunk_clone(va_arg(args, chunk_t));
                 continue;
             case BUILD_DIGEST_ALG:
                 digest_alg = va_arg(args, int);
                 continue;
             case BUILD_END:
                 break;
             default:
                 destroy(cert);
                 return NULL;
         }
         break;
     }
     if (sign_key && generate(cert, sign_cert, sign_key, digest_alg))
     {
         return &cert->public;
     }
     destroy(cert);
     return NULL;
 }
x509_cert_t* x509_cert_load (certificate_type_t type, va_list args)
Load a X.509 certificate.
This function takes a BUILD_BLOB_ASN1_DER.
Parameters
type certificate type, CERT_X509 only
args builder_part_t argument list
Returns
X.509 certificate, NULL on failure
See header.
Definition at line 2368 of file x509_cert.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_X509_FLAG, cert, chunk_clone, chunk_empty, create_empty(), destroy(), private_x509_cert_t::encoding, flags, private_x509_cert_t::flags, parse_certificate(), private_x509_cert_t::parsed, chunk_t::ptr, private_x509_cert_t::public, and TRUE.
Referenced by METHOD().
 {
     x509_flag_t flags = 0;
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_X509_FLAG:
                 flags |= va_arg(args, x509_flag_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.ptr)
     {
         private_x509_cert_t *cert = create_empty();
         cert->encoding = chunk_clone(blob);
         cert->parsed = TRUE;
         if (parse_certificate(cert))
         {
             cert->flags |= flags;
             return &cert->public;
         }
         destroy(cert);
     }
     return NULL;
 }