strongSwan: bus_t Struct Reference
bus_t Struct Reference
bus
#include "bus.h"
Public Attributes
void(* add_listener)(bus_t *this, listener_t *listener)
void(* remove_listener)(bus_t *this, listener_t *listener)
void(* add_logger)(bus_t *this, logger_t *logger)
void(* remove_logger)(bus_t *this, logger_t *logger)
void(* set_sa)(bus_t *this, ike_sa_t *ike_sa)
ike_sa_t *(* get_sa)(bus_t *this)
void(* log)(bus_t *this, debug_t group, level_t level, char *format,...)
void(* vlog)(bus_t *this, debug_t group, level_t level, char *format, va_list args)
void(* alert)(bus_t *this, alert_t alert,...)
void(* ike_state_change)(bus_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
void(* child_state_change)(bus_t *this, child_sa_t *child_sa, child_sa_state_t state)
void(* message)(bus_t *this, message_t *message, bool incoming, bool plain)
bool(* authorize)(bus_t *this, bool final)
void(* narrow)(bus_t *this, child_sa_t *child_sa, narrow_hook_t type, linked_list_t *local, linked_list_t *remote)
void(* ike_keys)(bus_t *this, ike_sa_t *ike_sa, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_t *rekey, shared_key_t *shared)
void(* child_keys)(bus_t *this, child_sa_t *child_sa, bool initiator, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r)
void(* ike_updown)(bus_t *this, ike_sa_t *ike_sa, bool up)
void(* ike_rekey)(bus_t *this, ike_sa_t *old, ike_sa_t *new)
void(* ike_update)(bus_t *this, ike_sa_t *ike_sa, bool local, host_t *new)
void(* ike_reestablish_pre)(bus_t *this, ike_sa_t *old, ike_sa_t *new)
void(* ike_reestablish_post)(bus_t *this, ike_sa_t *old, ike_sa_t *new, bool initiated)
void(* child_updown)(bus_t *this, child_sa_t *child_sa, bool up)
void(* child_rekey)(bus_t *this, child_sa_t *old, child_sa_t *new)
void(* children_migrate)(bus_t *this, ike_sa_id_t *new, u_int32_t unique)
void(* assign_vips)(bus_t *this, ike_sa_t *ike_sa, bool assign)
void(* handle_vips)(bus_t *this, ike_sa_t *ike_sa, bool handle)
void(* destroy)(bus_t *this)
Detailed Description
The bus receives events and sends them to all registered listeners.
Loggers are handled separately.
Definition at line 190 of file bus.h.
Member Data Documentation
void(* bus_t::add_listener)(bus_t *this, listener_t *listener)
Register a listener to the bus.
A registered listener receives all events which are sent to the bus. The listener is passive; the thread which emitted the event processes the listener routine.
Parameters
listener listener to register.
Definition at line 201 of file bus.h.
Referenced by connect_(), eap_radius_accounting_create(), eap_radius_provider_create(), initiate_connection(), load_hooks(), main(), METHOD(), on_accept(), open_database(), plugin_cb(), register_forecast(), register_listener(), register_load_tester(), register_tnc_ifmap(), register_vici(), stroke_socket_create(), trap_manager_create(), and wait_for_listener().
void(* bus_t::add_logger)(bus_t *this, logger_t *logger)
Register a logger with the bus.
The logger is passive; the thread which emitted the event processes the logger routine. This routine may be called concurrently by multiple threads. Recursive calls are not prevented, so logger that may cause recursive calls are responsible to avoid infinite loops.
During registration get_level() is called for all log groups and the logger is registered to receive log messages for groups for which the requested log level is > LEVEL_SILENT and whose level is lower or equal than the requested level.
To update the registered log levels call add_logger again with the same logger and return the new levels from get_level().
Parameters
logger logger to register.
Definition at line 228 of file bus.h.
Referenced by android_log_plugin_create(), CALLBACK(), load_file_logger(), load_loggers(), load_sys_logger(), main(), METHOD(), open_database(), register_vici(), and wait_for_listener().
void(* bus_t::alert)(bus_t *this, alert_t alert,...)
Raise an alert over the bus.
Parameters
alert kind of alert
... alert specific arguments
Definition at line 293 of file bus.h.
Referenced by console_handler(), eap_radius_handle_timeout(), enforce_replace(), handle_child_sa_failure(), METHOD(), parse_message(), process_payloads(), raise_alerts(), receive_packets(), retransmit_packet(), run(), select_and_install(), and service_handler().
void(* bus_t::assign_vips)(bus_t *this, ike_sa_t *ike_sa, bool assign)
Virtual IP assignment hook.
Parameters
ike_sa IKE_SA the VIPs are assigned to
assign TRUE if assigned to IKE_SA, FALSE if released
Definition at line 443 of file bus.h.
Referenced by adopt_children_and_vips(), build_reply(), build_set(), and METHOD().
bool(* bus_t::authorize)(bus_t *this, bool final)
IKE_SA authorization hook.
Parameters
final TRUE if this is the final invocation
Returns
TRUE to establish IKE_SA, FALSE to send AUTH_FAILED
Definition at line 329 of file bus.h.
Referenced by allowed(), establish(), and METHOD().
void(* bus_t::child_keys)(bus_t *this, child_sa_t *child_sa, bool initiator, diffie_hellman_t *dh, chunk_t nonce_i, chunk_t nonce_r)
CHILD_SA keymat hook.
Parameters
child_sa CHILD_SA this keymat is used for
initiator initiator of the CREATE_CHILD_SA exchange
dh diffie hellman shared secret
nonce_i initiators nonce
nonce_r responders nonce
Definition at line 366 of file bus.h.
Referenced by install(), and select_and_install().
void(* bus_t::child_rekey)(bus_t *this, child_sa_t *old, child_sa_t *new)
CHILD_SA rekeying hook.
Parameters
old rekeyed and obsolete CHILD_SA
new new CHILD_SA replacing old
Definition at line 427 of file bus.h.
Referenced by install(), and METHOD().
void(* bus_t::child_state_change)(bus_t *this, child_sa_t *child_sa, child_sa_state_t state)
Send a CHILD_SA state change event to the bus.
Parameters
child_sa CHILD_SA which changes its state
state new state CHILD_SA changes to
Definition at line 309 of file bus.h.
Referenced by METHOD().
void(* bus_t::child_updown)(bus_t *this, child_sa_t *child_sa, bool up)
CHILD_SA up/down hook.
Parameters
child_sa CHILD_SA coming up/going down
up TRUE for an up event, FALSE for a down event
Definition at line 419 of file bus.h.
Referenced by delete_child(), destroy_and_reestablish(), install(), and METHOD().
void(* bus_t::children_migrate)(bus_t *this, ike_sa_id_t *new, u_int32_t unique)
CHILD_SA migration hook.
Parameters
new ID of new SA when called for the old, NULL otherwise
uniue unique ID of new SA when called for the old, 0 otherwise
Definition at line 435 of file bus.h.
Referenced by adopt_children_and_vips(), and METHOD().
void(* bus_t::destroy)(bus_t *this)
Destroy the event bus.
Definition at line 456 of file bus.h.
ike_sa_t*(* bus_t::get_sa)(bus_t *this)
Get the IKE_SA the calling thread is currently using.
If a thread currently does not know what IKE_SA it is processing, it can call get_sa() to look up the SA set during checkout via set_sa().
Returns
registered ike_sa, NULL if none registered
Definition at line 258 of file bus.h.
Referenced by add_exclude(), add_include(), cleanup(), create_fragment(), eap_radius_build_attributes(), eap_tnc_create(), enforce_recommendation(), lookup_queue(), METHOD(), process_cfg_attributes(), process_class(), process_filter_id(), process_timeout(), remove_exclude(), and remove_include().
void(* bus_t::handle_vips)(bus_t *this, ike_sa_t *ike_sa, bool handle)
Virtual IP handler hook.
Parameters
ike_sa IKE_SA the VIPs/attributes got handled on
assign TRUE after installing attributes, FALSE on release
Definition at line 451 of file bus.h.
Referenced by install_vips(), and METHOD().
void(* bus_t::ike_keys)(bus_t *this, ike_sa_t *ike_sa, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_t *rekey, shared_key_t *shared)
IKE_SA keymat hook.
Parameters
ike_sa IKE_SA this keymat belongs to
dh diffie hellman shared secret
dh_other others DH public value (IKEv1 only)
nonce_i initiators nonce
nonce_r responders nonce
rekey IKE_SA we are rekeying, if any (IKEv2 only)
shared shared key used for key derivation (IKEv1-PSK only)
Definition at line 353 of file bus.h.
Referenced by derive_keys(), and METHOD().
void(* bus_t::ike_reestablish_post)(bus_t *this, ike_sa_t *old, ike_sa_t *new, bool initiated)
IKE_SA reestablishing hook (after configuring and initiating the new IKE_SA).
Parameters
old reestablished and obsolete IKE_SA
new new IKE_SA replacing old
initiated TRUE if initiated successfully, FALSE otherwise
Definition at line 410 of file bus.h.
Referenced by METHOD().
void(* bus_t::ike_reestablish_pre)(bus_t *this, ike_sa_t *old, ike_sa_t *new)
IKE_SA reestablishing hook (before resolving hosts).
Parameters
old reestablished and obsolete IKE_SA
new new IKE_SA replacing old
Definition at line 400 of file bus.h.
Referenced by METHOD().
void(* bus_t::ike_rekey)(bus_t *this, ike_sa_t *old, ike_sa_t *new)
IKE_SA rekeying hook.
Parameters
old rekeyed and obsolete IKE_SA
new new IKE_SA replacing old
Definition at line 383 of file bus.h.
Referenced by establish_new().
void(* bus_t::ike_state_change)(bus_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
Send a IKE_SA state change event to the bus.
Parameters
ike_sa IKE_SA which changes its state
state new state IKE_SA changes to
Definition at line 301 of file bus.h.
Referenced by METHOD().
void(* bus_t::ike_update)(bus_t *this, ike_sa_t *ike_sa, bool local, host_t *new)
IKE_SA peer endpoint update hook.
Parameters
ike_sa updated IKE_SA, having old endpoints set
local TRUE if local endpoint gets updated, FALSE for remote
new new endpoint address and port
Definition at line 392 of file bus.h.
Referenced by METHOD().
void(* bus_t::ike_updown)(bus_t *this, ike_sa_t *ike_sa, bool up)
IKE_SA up/down hook.
Parameters
ike_sa IKE_SA coming up/going down
up TRUE for an up event, FALSE for a down event
Definition at line 375 of file bus.h.
Referenced by build_response(), establish(), METHOD(), process_request(), and process_response().
void(* bus_t::log)(bus_t *this, debug_t group, level_t level, char *format,...)
Send a log message to the bus.
The format string specifies an additional informational or error message with a printf() like variable argument list. Use the DBG() macros.
Parameters
group debugging group
level verbosity level of the signal
format printf() style format string
... printf() style argument list
Definition at line 272 of file bus.h.
void(* bus_t::message)(bus_t *this, message_t *message, bool incoming, bool plain)
Message send/receive hook.
The hook is invoked twice for each message: Once with plain, parsed data and once encoded and encrypted.
Parameters
message message to send/receive
incoming TRUE for incoming messages, FALSE for outgoing
plain TRUE if message is parsed and decrypted, FALSE it not
Definition at line 321 of file bus.h.
Referenced by METHOD().
void(* bus_t::narrow)(bus_t *this, child_sa_t *child_sa, narrow_hook_t type, linked_list_t *local, linked_list_t *remote)
CHILD_SA traffic selector narrowing hook.
Parameters
child_sa CHILD_SA set up with these traffic selectors
type type of hook getting invoked
local list of local traffic selectors to narrow
remote list of remote traffic selectors to narrow
Definition at line 339 of file bus.h.
Referenced by install(), METHOD(), and select_and_install().
void(* bus_t::remove_listener)(bus_t *this, listener_t *listener)
Unregister a listener from the bus.
Parameters
listener listener to unregister.
Definition at line 208 of file bus.h.
Referenced by cleanup(), connect_(), disconnect(), initiate_connection(), listener_unregister(), main(), METHOD(), on_accept(), open_database(), plugin_cb(), register_forecast(), register_listener(), register_load_tester(), register_tnc_ifmap(), and register_vici().
void(* bus_t::remove_logger)(bus_t *this, logger_t *logger)
Unregister a logger from the bus.
Parameters
logger logger to unregister.
Definition at line 235 of file bus.h.
Referenced by cleanup(), journal_register(), listener_unregister(), logger_entry_unregister_destroy(), METHOD(), open_database(), and register_vici().
void(* bus_t::set_sa)(bus_t *this, ike_sa_t *ike_sa)
Set the IKE_SA the calling thread is using.
To associate a received log message with an IKE_SA without passing it as parameter each time, the thread registers the currently used IKE_SA during check-out. Before check-in, the thread unregisters the IKE_SA. This IKE_SA is stored per-thread, so each thread has its own IKE_SA registered.
Parameters
ike_sa ike_sa to register, or NULL to unregister
Definition at line 248 of file bus.h.
Referenced by adopt_children_and_vips(), cleanup(), enumerator_filter_skip(), enumerator_filter_wait(), establish_new(), METHOD(), process_eap(), process_ike_add(), reset_sa(), and trigger_mbb_reauth().
void(* bus_t::vlog)(bus_t *this, debug_t group, level_t level, char *format, va_list args)
Send a log message to the bus using va_list arguments.
Same as bus_t.log(), but uses va_list argument list.
Parameters
group kind of the signal (up, down, rekeyed, ...)
level verbosity level of the signal
format printf() style format string
args va_list arguments
Definition at line 284 of file bus.h.
Referenced by dbg_bus().
The documentation for this struct was generated from the following file:
bus.h