strongSwan: soup_fetcher.c File Reference
soup_fetcher.c File Reference
#include "soup_fetcher.h"
#include <libsoup/soup.h>
#include <library.h>
#include <utils/debug.h>
Classes
struct private_soup_fetcher_t
struct cb_data_t
Macros
#define DEFAULT_TIMEOUT 10
Typedefs
typedef struct
private_soup_fetcher_t private_soup_fetcher_t
Functions
static void soup_cb (SoupMessage *message, SoupBuffer *chunk, cb_data_t *data)
METHOD (fetcher_t, fetch, status_t, private_soup_fetcher_t *this, char *uri, void *userdata)
METHOD (fetcher_t, set_option, bool, private_soup_fetcher_t *this, fetcher_option_t option,...)
METHOD (fetcher_t, destroy, void, private_soup_fetcher_t *this)
soup_fetcher_t * soup_fetcher_create ()
Macro Definition Documentation
#define DEFAULT_TIMEOUT 10
Definition at line 23 of file soup_fetcher.c.
Referenced by soup_fetcher_create().
Typedef Documentation
typedef struct private_soup_fetcher_t private_soup_fetcher_t
Definition at line 25 of file soup_fetcher.c.
Function Documentation
METHOD (fetcher_t , fetch , status_t , private_soup_fetcher_t * this, char * uri, void * userdata)
Definition at line 94 of file soup_fetcher.c.
References cb(), chunk_empty, data, DBG1, DBG2, DBG_LIB, FAILED, FALSE, fetcher_default_callback(), NOT_SUPPORTED, result, cb_data_t::session, soup_cb(), status, SUCCESS, type, and version.
 {
     SoupMessage *message;
     status_t status = FAILED;
     cb_data_t data = {
         .cb = this->cb,
         .user = userdata,
     };
     message = soup_message_new(this->method, uri);
     if (!message)
     {
         return NOT_SUPPORTED;
     }
     if (this->cb == fetcher_default_callback)
     {
         *(chunk_t*)userdata = chunk_empty;
     }
     if (this->type)
     {
         soup_message_set_request(message, this->type, SOUP_MEMORY_STATIC,
                                  this->data.ptr, this->data.len);
     }
     soup_message_set_http_version(message, this->version);
     soup_message_body_set_accumulate(message->response_body, FALSE);
     g_signal_connect(message, "got-chunk", G_CALLBACK(soup_cb), &data);
     data.session = soup_session_sync_new();
     g_object_set(G_OBJECT(data.session),
                  SOUP_SESSION_TIMEOUT, (guint)this->timeout, NULL);
     DBG2(DBG_LIB, "sending http request to '%s'...", uri);
     soup_session_send_message(data.session, message);
     if (this->result)
     {
         *this->result = message->status_code;
     }
     if (SOUP_STATUS_IS_SUCCESSFUL(message->status_code))
     {
         status = SUCCESS;
     }
     else if (!this->result)
     {   /* only log an error if the code is not returned */
         DBG1(DBG_LIB, "HTTP request failed: %s", message->reason_phrase);
     }
     g_object_unref(G_OBJECT(message));
     g_object_unref(G_OBJECT(data.session));
     return status;
 }
METHOD (fetcher_t , set_option , bool , private_soup_fetcher_t * this, fetcher_option_t option, ...)
Definition at line 144 of file soup_fetcher.c.
References cb(), data, FALSE, FETCH_CALLBACK, FETCH_HTTP_VERSION_1_0, FETCH_REQUEST_DATA, FETCH_REQUEST_TYPE, FETCH_RESPONSE_CODE, FETCH_TIMEOUT, result, TRUE, type, and version.
 {
     bool supported = TRUE;
     va_list args;
     va_start(args, option);
     switch (option)
     {
         case FETCH_REQUEST_DATA:
             this->method = SOUP_METHOD_POST;
             this->data = va_arg(args, chunk_t);
             break;
         case FETCH_REQUEST_TYPE:
             this->type = va_arg(args, char*);
             break;
         case FETCH_HTTP_VERSION_1_0:
             this->version = SOUP_HTTP_1_0;
             break;
         case FETCH_TIMEOUT:
             this->timeout = va_arg(args, u_int);
             break;
         case FETCH_CALLBACK:
             this->cb = va_arg(args, fetcher_callback_t);
             break;
         case FETCH_RESPONSE_CODE:
             this->result = va_arg(args, u_int*);
             break;
         default:
             supported = FALSE;
             break;
     }
     va_end(args);
     return supported;
 }
METHOD (fetcher_t , destroy , void , private_soup_fetcher_t * this)
Definition at line 180 of file soup_fetcher.c.
References free().
 {
     free(this);
 }
static void soup_cb (SoupMessage * message, SoupBuffer * chunk, cb_data_t * data) static
Soup callback invoking our callback
Definition at line 85 of file soup_fetcher.c.
References cb_data_t::cb, chunk_create(), cb_data_t::session, and cb_data_t::user.
Referenced by METHOD().
 {
     if (!data->cb(data->user, chunk_create((u_char*)chunk->data, chunk->length)))
     {
         soup_session_cancel_message(data->session, message,
                                     SOUP_STATUS_CANCELLED);
     }
 }