strongSwan: ha_segments
ha_segments
ha
Classes
struct ha_segments_t
Macros
#define SEGMENTS_MAX (sizeof(segment_mask_t)*8)
#define SEGMENTS_BIT(segment) (0x01 << (segment - 1))
Typedefs
typedef struct ha_segments_t ha_segments_t
typedef u_int16_t segment_mask_t
Functions
ha_segments_t * ha_segments_create (ha_socket_t *socket, ha_kernel_t *kernel, ha_tunnel_t *tunnel, u_int count, u_int node, bool monitor)
Detailed Description
Macro Definition Documentation
#define SEGMENTS_BIT (segment) (0x01 << (segment - 1))
Get the bit in the mask of a segment
Definition at line 38 of file ha_segments.h.
Referenced by autobalance(), disable_all(), enable_disable(), get_active(), log_segments(), METHOD(), process_status(), and send_status().
#define SEGMENTS_MAX (sizeof(segment_mask_t)*8)
maximum number of segments
Definition at line 33 of file ha_segments.h.
Referenced by initialize_plugin().
Typedef Documentation
typedef struct ha_segments_t ha_segments_t
Definition at line 26 of file ha_segments.h.
typedef u_int16_t segment_mask_t
Definition at line 28 of file ha_segments.h.
Function Documentation
ha_segments_t* ha_segments_create (ha_socket_t * socket, ha_kernel_t * kernel, ha_tunnel_t * tunnel, u_int count, u_int node, bool monitor)
Create a ha_segments instance.
Parameters
socket socket to communicate segment (de-)activation
kernel interface to control segments at kernel level
tunnel HA tunnel
count number of segments the cluster uses
node node, currently 1 or 0
monitor should we use monitoring functionality
Returns
segment object
See header
Definition at line 447 of file ha_segments.c.
References autobalance(), condvar_create(), CONDVAR_TYPE_DEFAULT, count, DBG1, DBG_CFG, DEFAULT_HEARTBEAT_DELAY, DEFAULT_HEARTBEAT_TIMEOUT, settings_t::get_int, INIT, lib, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, library_t::settings, socket, start_autobalance(), start_heartbeat(), and start_watchdog().
Referenced by initialize_plugin().
 {
     private_ha_segments_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .alert = _alert_hook,
             },
             .activate = _activate,
             .deactivate = _deactivate,
             .handle_status = _handle_status,
             .is_active = _is_active,
             .destroy = _destroy,
         },
         .socket = socket,
         .tunnel = tunnel,
         .kernel = kernel,
         .count = count,
         .node = node,
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .heartbeat_delay = lib->settings->get_int(lib->settings,
                 "%s.plugins.ha.heartbeat_delay", DEFAULT_HEARTBEAT_DELAY,
                 lib->ns),
         .heartbeat_timeout = lib->settings->get_int(lib->settings,
                 "%s.plugins.ha.heartbeat_timeout", DEFAULT_HEARTBEAT_TIMEOUT,
                 lib->ns),
         .autobalance = lib->settings->get_int(lib->settings,
                 "%s.plugins.ha.autobalance", 0, lib->ns),
     );
     if (monitor)
     {
         DBG1(DBG_CFG, "starting HA heartbeat, delay %dms, timeout %dms",
              this->heartbeat_delay, this->heartbeat_timeout);
         start_heartbeat(this);
         start_watchdog(this);
     }
     if (this->autobalance)
     {
         start_autobalance(this);
     }
     return &this->public;
 }