strongSwan: pkcs11_rng
pkcs11_rng
pkcs11
Classes
struct pkcs11_rng_t
Typedefs
typedef struct pkcs11_rng_t pkcs11_rng_t
Functions
pkcs11_rng_t * pkcs11_rng_create (rng_quality_t quality)
Detailed Description
Typedef Documentation
typedef struct pkcs11_rng_t pkcs11_rng_t
Definition at line 24 of file pkcs11_rng.h.
Function Documentation
pkcs11_rng_t* pkcs11_rng_create (rng_quality_t quality)
Creates a pkcs11_rng_t instance.
Parameters
quality required quality of randomness
Returns
created pkcs11_rng_t
Definition at line 120 of file pkcs11_rng.c.
References find_token(), free(), INIT, and lib.
Referenced by METHOD().
 {
     private_pkcs11_rng_t *this;
     INIT(this,
         .public = {
             .rng = {
                 .get_bytes = _get_bytes,
                 .allocate_bytes = _allocate_bytes,
                 .destroy = _destroy,
             },
         },
     );
     this->lib = find_token(&this->session);
     if (!this->lib)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }