strongSwan: tty
tty
utils
Typedefs
typedef enum tty_escape_t tty_escape_t
Enumerations
enum tty_escape_t {
TTY_RESET, TTY_BOLD, TTY_UNDERLINE, TTY_BLINKING,
TTY_FG_BLACK, TTY_FG_RED, TTY_FG_GREEN, TTY_FG_YELLOW,
TTY_FG_BLUE, TTY_FG_MAGENTA, TTY_FG_CYAN, TTY_FG_WHITE,
TTY_FG_DEF, TTY_BG_BLACK, TTY_BG_RED, TTY_BG_GREEN,
TTY_BG_YELLOW, TTY_BG_BLUE, TTY_BG_MAGENTA, TTY_BG_CYAN,
TTY_BG_WHITE, TTY_BG_DEF
}
Functions
char * tty_escape_get (int fd, tty_escape_t escape)
Detailed Description
Typedef Documentation
typedef enum tty_escape_t tty_escape_t
Definition at line 25 of file tty.h.
Enumeration Type Documentation
enum tty_escape_t
Excape codes for tty colors
Enumerator
TTY_RESET
text properties
TTY_BOLD
TTY_UNDERLINE
TTY_BLINKING
TTY_FG_BLACK
foreground colors
TTY_FG_RED
TTY_FG_GREEN
TTY_FG_YELLOW
TTY_FG_BLUE
TTY_FG_MAGENTA
TTY_FG_CYAN
TTY_FG_WHITE
TTY_FG_DEF
TTY_BG_BLACK
background colors
TTY_BG_RED
TTY_BG_GREEN
TTY_BG_YELLOW
TTY_BG_BLUE
TTY_BG_MAGENTA
TTY_BG_CYAN
TTY_BG_WHITE
TTY_BG_DEF
Definition at line 30 of file tty.h.
                   {
     TTY_RESET,
     TTY_BOLD,
     TTY_UNDERLINE,
     TTY_BLINKING,
     TTY_FG_BLACK,
     TTY_FG_RED,
     TTY_FG_GREEN,
     TTY_FG_YELLOW,
     TTY_FG_BLUE,
     TTY_FG_MAGENTA,
     TTY_FG_CYAN,
     TTY_FG_WHITE,
     TTY_FG_DEF,
     TTY_BG_BLACK,
     TTY_BG_RED,
     TTY_BG_GREEN,
     TTY_BG_YELLOW,
     TTY_BG_BLUE,
     TTY_BG_MAGENTA,
     TTY_BG_CYAN,
     TTY_BG_WHITE,
     TTY_BG_DEF,
 };
Function Documentation
char* tty_escape_get (int fd, tty_escape_t escape)
Get the escape string for a given TTY color, empty string on non-tty fd
Get the escape string for a given TTY color, empty string on non-tty FILE
Definition at line 49 of file tty.c.
References enum_to_name(), isatty(), TTY_BG_BLACK, TTY_BG_BLUE, TTY_BG_CYAN, TTY_BG_DEF, TTY_BG_GREEN, TTY_BG_MAGENTA, TTY_BG_RED, TTY_BG_WHITE, TTY_BG_YELLOW, TTY_BLINKING, TTY_BOLD, TTY_FG_BLACK, TTY_FG_BLUE, TTY_FG_CYAN, TTY_FG_DEF, TTY_FG_GREEN, TTY_FG_MAGENTA, TTY_FG_RED, TTY_FG_WHITE, TTY_FG_YELLOW, TTY_RESET, and TTY_UNDERLINE.
Referenced by esc().
 {
     if (!isatty(fd))
     {
         return "";
     }
     switch (escape)
     {
         case TTY_RESET:
         case TTY_BOLD:
         case TTY_UNDERLINE:
         case TTY_BLINKING:
 #ifdef WIN32
             return "";
 #endif
         case TTY_FG_BLACK:
         case TTY_FG_RED:
         case TTY_FG_GREEN:
         case TTY_FG_YELLOW:
         case TTY_FG_BLUE:
         case TTY_FG_MAGENTA:
         case TTY_FG_CYAN:
         case TTY_FG_WHITE:
         case TTY_FG_DEF:
         case TTY_BG_BLACK:
         case TTY_BG_RED:
         case TTY_BG_GREEN:
         case TTY_BG_YELLOW:
         case TTY_BG_BLUE:
         case TTY_BG_MAGENTA:
         case TTY_BG_CYAN:
         case TTY_BG_WHITE:
         case TTY_BG_DEF:
             return enum_to_name(tty_color_names, escape);
         /* warn if a escape code is missing */
     }
     return "";
 }