strongSwan: pkcs11_public_key
pkcs11_public_key
pkcs11
Classes
struct pkcs11_public_key_t
Typedefs
typedef struct pkcs11_public_key_t pkcs11_public_key_t
Functions
pkcs11_public_key_t * pkcs11_public_key_load (key_type_t type, va_list args)
public_key_t * pkcs11_public_key_connect (pkcs11_library_t *p11, int slot, key_type_t type, chunk_t keyid)
Detailed Description
Typedef Documentation
typedef struct pkcs11_public_key_t pkcs11_public_key_t
Definition at line 24 of file pkcs11_public_key.h.
Function Documentation
public_key_t* pkcs11_public_key_connect (pkcs11_library_t * p11, int slot, key_type_t type, chunk_t keyid)
Find a public key on the given token with a specific keyid.
Parameters
p11 PKCS#11 module
slot slot id
type type of the key
keyid key id
See header.
Definition at line 924 of file pkcs11_public_key.c.
References find_key_by_keyid().
Referenced by pkcs11_private_key_connect().
 {
     private_pkcs11_public_key_t *this;
     this = find_key_by_keyid(p11, slot, type, keyid);
     if (!this)
     {
         return NULL;
     }
     return &this->public.key;
 }
pkcs11_public_key_t* pkcs11_public_key_load (key_type_t type, va_list args)
Create a public key in a PKCS#11 session.
Parameters
type type of the key
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header
Definition at line 764 of file pkcs11_public_key.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_empty, chunk_free(), chunk_skip(), create_ecdsa_key(), create_rsa_key(), find_ecdsa_key(), find_rsa_key(), KEY_ECDSA, KEY_RSA, chunk_t::len, n, parse_ecdsa_public_key(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     private_pkcs11_public_key_t *this;
     chunk_t n, e, blob;
     size_t keylen = 0;
     n = e = blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_MODULUS:
                 n = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PUB_EXP:
                 e = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (type == KEY_RSA && e.ptr && n.ptr)
     {
         if (n.len && n.ptr[0] == 0)
         {   /* trim leading zero byte in modulus */
             n = chunk_skip(n, 1);
         }
         keylen = n.len * 8;
         this = find_rsa_key(n, e, keylen);
         if (this)
         {
             return &this->public;
         }
         this = create_rsa_key(n, e, keylen);
         if (this)
         {
             return &this->public;
         }
     }
     else if (type == KEY_ECDSA && blob.ptr)
     {
         chunk_t ecparams, ecpoint;
         ecparams = ecpoint = chunk_empty;
         if (parse_ecdsa_public_key(blob, &ecparams, &ecpoint, &keylen))
         {
             this = find_ecdsa_key(ecparams, ecpoint, keylen);
             if (!this)
             {
                 this = create_ecdsa_key(ecparams, ecpoint, keylen);
             }
             chunk_free(&ecpoint);
             if (this)
             {
                 return &this->public;
             }
         }
     }
     return NULL;
 }