strongSwan: settings_lexer.c File Reference
settings_lexer.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <utils/parser_helper.h>
#include "settings_parser.h"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Macros
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define YY_TYPEDEF_YY_SCANNER_T
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE settings_parser_restart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_TYPEDEF_YY_SIZE_T
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER settings_parser__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer settings_parser__create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define settings_parser_wrap(n) 1
#define YY_SKIP_YYWRAP
#define FLEX_DEBUG
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_NO_INPUT 1
#define INITIAL 0
#define inc 1
#define str 2
#define YY_EXTRA_TYPE parser_helper_t*
#define yylval yyg->yylval_r
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_DECL_IS_OURS 1
#define YY_DECL
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void settings_parser_restart (FILE *input_file, yyscan_t yyscanner)
void settings_parser__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
YY_BUFFER_STATE settings_parser__create_buffer (FILE *file, int size, yyscan_t yyscanner)
void settings_parser__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void settings_parser__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void settings_parser_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
void settings_parser_pop_buffer_state (yyscan_t yyscanner)
static void settings_parser_ensure_buffer_stack (yyscan_t yyscanner)
static void settings_parser__load_buffer_state (yyscan_t yyscanner)
static void settings_parser__init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
YY_BUFFER_STATE settings_parser__scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
YY_BUFFER_STATE settings_parser__scan_string (yyconst char *yy_str, yyscan_t yyscanner)
YY_BUFFER_STATE settings_parser__scan_bytes (yyconst char *bytes, int len, yyscan_t yyscanner)
void * settings_parser_alloc (yy_size_t, yyscan_t yyscanner)
void * settings_parser_realloc (void *, yy_size_t, yyscan_t yyscanner)
void settings_parser_free (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner)
bool settings_parser_open_next_file (parser_helper_t *ctx)
static void include_files (parser_helper_t *ctx)
static int yy_init_globals (yyscan_t yyscanner)
int settings_parser_lex_init (yyscan_t *scanner)
int settings_parser_lex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t *scanner)
int settings_parser_lex_destroy (yyscan_t yyscanner)
int settings_parser_get_debug (yyscan_t yyscanner)
void settings_parser_set_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE settings_parser_get_extra (yyscan_t yyscanner)
void settings_parser_set_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
FILE * settings_parser_get_in (yyscan_t yyscanner)
void settings_parser_set_in (FILE *in_str, yyscan_t yyscanner)
FILE * settings_parser_get_out (yyscan_t yyscanner)
void settings_parser_set_out (FILE *out_str, yyscan_t yyscanner)
int settings_parser_get_leng (yyscan_t yyscanner)
char * settings_parser_get_text (yyscan_t yyscanner)
int settings_parser_get_lineno (yyscan_t yyscanner)
void settings_parser_set_lineno (int line_number, yyscan_t yyscanner)
YYSTYPE * settings_parser_get_lval (yyscan_t yyscanner)
void settings_parser_set_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
static void yyunput (int c, char *buf_ptr, yyscan_t yyscanner)
static void yy_push_state (int new_state, yyscan_t yyscanner)
static void yy_pop_state (yyscan_t yyscanner)
static int yy_top_state (yyscan_t yyscanner)
int settings_parser_lex (YYSTYPE *yylval_param, yyscan_t yyscanner)
if (!yyg->yy_init)
while (1)
static void yyunput (int c, register char *yy_bp, yyscan_t yyscanner)
int isatty (int)
static void yy_fatal_error (yyconst char *msg, yyscan_t yyscanner)
int settings_parser_get_column (yyscan_t yyscanner)
void settings_parser_set_column (int column_no, yyscan_t yyscanner)
void settings_parser_load_string (parser_helper_t *ctx, const char *content)
Variables
static yyconst flex_int16_t yy_accept [49]
static yyconst flex_int32_t yy_ec [256]
static yyconst flex_int32_t yy_meta [21]
static yyconst flex_int16_t yy_base [60]
static yyconst flex_int16_t yy_def [60]
static yyconst flex_int16_t yy_nxt [182]
static yyconst flex_int16_t yy_chk [182]
static yyconst flex_int32_t yy_rule_can_match_eol [24]
static yyconst flex_int16_t yy_rule_linenum [23]
YY_DECL
register char * yy_cp
register char * yy_bp
register int yy_act
struct yyguts_t * yyg = (struct yyguts_t*)yyscanner
yylval = yylval_param
Macro Definition Documentation
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 185 of file settings_lexer.c.
Referenced by yy_pop_state(), and yy_push_state().
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
Definition at line 825 of file settings_lexer.c.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 232 of file settings_lexer.c.
Referenced by while(), and yy_get_next_buffer().
#define EOB_ACT_END_OF_FILE 1
Definition at line 233 of file settings_lexer.c.
Referenced by while(), and yy_get_next_buffer().
#define EOB_ACT_LAST_MATCH 2
Definition at line 234 of file settings_lexer.c.
Referenced by while(), and yy_get_next_buffer().
#define FLEX_BETA
Definition at line 22 of file settings_lexer.c.
#define FLEX_DEBUG
Definition at line 429 of file settings_lexer.c.
#define FLEX_SCANNER
Definition at line 17 of file settings_lexer.c.
#define FLEXINT_H
Definition at line 54 of file settings_lexer.c.
#define inc 1
Definition at line 644 of file settings_lexer.c.
Referenced by while().
#define INITIAL 0
Definition at line 643 of file settings_lexer.c.
Referenced by while().
#define INT16_MAX (32767)
Definition at line 96 of file settings_lexer.c.
#define INT16_MIN (-32767-1)
Definition at line 87 of file settings_lexer.c.
#define INT32_MAX (2147483647)
Definition at line 99 of file settings_lexer.c.
#define INT32_MIN (-2147483647-1)
Definition at line 90 of file settings_lexer.c.
#define INT8_MAX (127)
Definition at line 93 of file settings_lexer.c.
#define INT8_MIN (-128)
Definition at line 84 of file settings_lexer.c.
#define REJECT reject_used_but_not_detected
Definition at line 599 of file settings_lexer.c.
#define settings_parser_wrap (n) 1
Definition at line 426 of file settings_lexer.c.
Referenced by while().
#define str 2
Definition at line 645 of file settings_lexer.c.
Referenced by add_legacy_entry(), build_auth_cfgs(), CALLBACK(), connect_(), create_from_string_with_prefix_type(), decode_list(), decode_section(), free_hashtable(), generate_message(), ike_cfg_get_family(), list_plugins(), load_validator(), log_auth(), match(), METHOD(), parse_map(), parse_rounds(), plugin_feature_get_string(), print_ac(), push_env(), read_string(), request_control_initiate(), request_control_terminate(), resolve(), sanitize(), vici.protocol.Message::serialize(), stroke_list_acerts(), strreplace(), translate(), vici_find_str(), and while().
#define UINT16_MAX (65535U)
Definition at line 105 of file settings_lexer.c.
Referenced by push_string_impl(), send_stroke_msg(), and transform_attribute_create_value().
#define UINT32_MAX (4294967295U)
Definition at line 108 of file settings_lexer.c.
Referenced by METHOD(), pts_ima_event_list_create(), and transform_attribute_create_value().
#define UINT8_MAX (255U)
Definition at line 102 of file settings_lexer.c.
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 265 of file settings_lexer.c.
Referenced by while().
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 421 of file settings_lexer.c.
#define YY_BREAK break;
Definition at line 931 of file settings_lexer.c.
Referenced by while().
#define YY_BUF_SIZE 16384
Definition at line 211 of file settings_lexer.c.
Referenced by if(), settings_parser_open_next_file(), and settings_parser_restart().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 337 of file settings_lexer.c.
Referenced by yy_get_next_buffer().
#define YY_BUFFER_NEW 0
Definition at line 325 of file settings_lexer.c.
Referenced by settings_parser__flush_buffer(), settings_parser__scan_buffer(), and while().
#define YY_BUFFER_NORMAL 1
Definition at line 326 of file settings_lexer.c.
Referenced by while().
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 357 of file settings_lexer.c.
Referenced by if(), settings_parser__delete_buffer(), settings_parser__flush_buffer(), settings_parser__init_buffer(), settings_parser__switch_to_buffer(), settings_parser_get_column(), settings_parser_get_lineno(), settings_parser_lex_destroy(), settings_parser_pop_buffer_state(), settings_parser_push_buffer_state(), settings_parser_restart(), settings_parser_set_column(), settings_parser_set_lineno(), while(), and yy_get_next_buffer().
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 364 of file settings_lexer.c.
Referenced by if(), settings_parser__delete_buffer(), settings_parser__load_buffer_state(), settings_parser__switch_to_buffer(), settings_parser_lex_destroy(), settings_parser_pop_buffer_state(), settings_parser_push_buffer_state(), settings_parser_restart(), while(), yy_get_next_buffer(), and yyunput().
#define YY_DECL
Value:
int settings_parser_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
Definition at line 915 of file settings_lexer.c.
#define YY_DECL_IS_OURS 1
Definition at line 909 of file settings_lexer.c.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
    yyleng = (size_t) (yy_cp - yy_bp); \
    yyg->yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
    yyg->yy_c_buf_p = yy_cp;
Definition at line 449 of file settings_lexer.c.
Referenced by while().
#define YY_END_OF_BUFFER 24
Definition at line 460 of file settings_lexer.c.
Referenced by while().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 200 of file settings_lexer.c.
Referenced by settings_parser__flush_buffer(), settings_parser__scan_buffer(), settings_parser__scan_bytes(), and yy_get_next_buffer().
#define YY_EXIT_FAILURE 2
Definition at line 2246 of file settings_lexer.c.
Referenced by yy_fatal_error().
#define YY_EXTRA_TYPE parser_helper_t*
Definition at line 659 of file settings_lexer.c.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 886 of file settings_lexer.c.
Referenced by settings_parser__create_buffer(), settings_parser__scan_buffer(), settings_parser__scan_bytes(), settings_parser_ensure_buffer_stack(), while(), yy_get_next_buffer(), yy_pop_state(), yy_push_state(), and yyunput().
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 174 of file settings_lexer.c.
Referenced by settings_parser_get_debug(), settings_parser_set_debug(), and while().
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 18 of file settings_lexer.c.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 19 of file settings_lexer.c.
#define YY_FLEX_SUBMINOR_VERSION 35
Definition at line 20 of file settings_lexer.c.
#define YY_FLUSH_BUFFER settings_parser__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 387 of file settings_lexer.c.
#define YY_INPUT (buf, result, max_size)
Definition at line 835 of file settings_lexer.c.
Referenced by yy_get_next_buffer().
#define YY_INT_ALIGNED short int
Definition at line 5 of file settings_lexer.c.
#define YY_LESS_LINENO (n)
Value:
do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
Definition at line 243 of file settings_lexer.c.
#define YY_MORE_ADJ 0
Definition at line 601 of file settings_lexer.c.
Referenced by while(), yy_get_next_buffer(), and yy_get_previous_state().
#define yy_new_buffer settings_parser__create_buffer
Definition at line 399 of file settings_lexer.c.
#define YY_NEW_FILE settings_parser_restart(yyin ,yyscanner)
Definition at line 198 of file settings_lexer.c.
Referenced by while().
#define YY_NO_INPUT 1
Definition at line 630 of file settings_lexer.c.
#define YY_NULL 0
Definition at line 144 of file settings_lexer.c.
#define YY_NUM_RULES 23
Definition at line 459 of file settings_lexer.c.
#define YY_READ_BUF_SIZE 8192
Definition at line 815 of file settings_lexer.c.
Referenced by yy_get_next_buffer().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 602 of file settings_lexer.c.
Referenced by while().
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 935 of file settings_lexer.c.
Referenced by while().
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 154 of file settings_lexer.c.
Referenced by while(), and yy_get_previous_state().
#define yy_set_bol (at_bol)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){\
        settings_parser_ensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            settings_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
    }
Definition at line 411 of file settings_lexer.c.
Referenced by while().
#define yy_set_interactive (is_interactive)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){ \
        settings_parser_ensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            settings_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
    }
Definition at line 401 of file settings_lexer.c.
#define YY_SKIP_YYWRAP
Definition at line 427 of file settings_lexer.c.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 191 of file settings_lexer.c.
Referenced by while(), and yy_push_state().
#define YY_START_STACK_INCR 25
Definition at line 880 of file settings_lexer.c.
Referenced by yy_push_state().
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 217 of file settings_lexer.c.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 195 of file settings_lexer.c.
Referenced by while().
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 273 of file settings_lexer.c.
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 220 of file settings_lexer.c.
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 161 of file settings_lexer.c.
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 268 of file settings_lexer.c.
#define YY_USER_ACTION
Definition at line 926 of file settings_lexer.c.
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 173 of file settings_lexer.c.
Referenced by settings_parser_get_column(), settings_parser_set_column(), and while().
#define yyconst
Definition at line 138 of file settings_lexer.c.
#define yyextra yyg->yyextra_r
Definition at line 169 of file settings_lexer.c.
Referenced by settings_parser_get_extra(), settings_parser_set_extra(), and while().
#define yyin yyg->yyin_r
Definition at line 167 of file settings_lexer.c.
Referenced by if(), settings_parser__load_buffer_state(), settings_parser_get_in(), settings_parser_restart(), settings_parser_set_in(), while(), yy_get_next_buffer(), and yy_init_globals().
#define yyleng yyg->yyleng_r
Definition at line 170 of file settings_lexer.c.
Referenced by settings_parser_get_leng(), and while().
#define yyless (n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        *yy_cp = yyg->yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )
Definition at line 2262 of file settings_lexer.c.
#define yyless (n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        yytext[yyleng] = yyg->yy_hold_char; \
        yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
        yyg->yy_hold_char = *yyg->yy_c_buf_p; \
        *yyg->yy_c_buf_p = '\0'; \
        yyleng = yyless_macro_arg; \
        } \
    while ( 0 )
Definition at line 2262 of file settings_lexer.c.
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 172 of file settings_lexer.c.
Referenced by settings_parser_get_lineno(), settings_parser_set_lineno(), while(), and yyunput().
#define yylval yyg->yylval_r
Definition at line 710 of file settings_lexer.c.
Referenced by settings_parser_get_lval(), settings_parser_set_lval(), while(), and yyparse().
#define yymore () yymore_used_but_not_detected
Definition at line 600 of file settings_lexer.c.
#define yyout yyg->yyout_r
Definition at line 168 of file settings_lexer.c.
Referenced by if(), settings_parser_get_out(), settings_parser_set_out(), and yy_init_globals().
#define YYSTATE YY_START
Definition at line 192 of file settings_lexer.c.
#define YYTABLES_NAME "yytables"
Definition at line 2633 of file settings_lexer.c.
#define yyterminate () return YY_NULL
Definition at line 875 of file settings_lexer.c.
Referenced by while().
#define yytext yyg->yytext_r
Definition at line 171 of file settings_lexer.c.
Referenced by settings_parser_get_text(), and while().
#define yytext_ptr yytext_r
Definition at line 435 of file settings_lexer.c.
Typedef Documentation
typedef short int flex_int16_t
Definition at line 76 of file settings_lexer.c.
typedef int flex_int32_t
Definition at line 77 of file settings_lexer.c.
typedef signed char flex_int8_t
Definition at line 75 of file settings_lexer.c.
typedef unsigned short int flex_uint16_t
Definition at line 79 of file settings_lexer.c.
typedef unsigned int flex_uint32_t
Definition at line 80 of file settings_lexer.c.
typedef unsigned char flex_uint8_t
Definition at line 78 of file settings_lexer.c.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 221 of file settings_lexer.c.
typedef unsigned char YY_CHAR
Definition at line 431 of file settings_lexer.c.
typedef size_t yy_size_t
Definition at line 269 of file settings_lexer.c.
typedef int yy_state_type
Definition at line 433 of file settings_lexer.c.
typedef void* yyscan_t
Definition at line 162 of file settings_lexer.c.
Function Documentation
if (!yyg-> yy_init)
Definition at line 957 of file settings_lexer.c.
References settings_parser__create_buffer(), settings_parser__load_buffer_state(), settings_parser_ensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_init, yyguts_t::yy_start, yyin, and yyout.
Referenced by chunk_compare(), cookie_verify(), fix_transport_header(), get_route(), host_create_netmask(), manage_srcroute(), METHOD(), parse_public_key(), process_peer_challenge(), process_peer_failure(), process_peer_success(), process_server_response(), request(), selector2ts(), simaka_message_create_data(), and update_addrs().
         {
         yyg->yy_init = 1;
 #ifdef YY_USER_INIT
         YY_USER_INIT;
 #endif
         if ( ! yyg->yy_start )
             yyg->yy_start = 1;  /* first start state */
         if ( ! yyin )
 /* %if-c-only */
             yyin = stdin;
 /* %endif */
 /* %if-c++-only */
 /* %endif */
         if ( ! yyout )
 /* %if-c-only */
             yyout = stdout;
 /* %endif */
 /* %if-c++-only */
 /* %endif */
         if ( ! YY_CURRENT_BUFFER ) {
             settings_parser_ensure_buffer_stack (yyscanner);
             YY_CURRENT_BUFFER_LVALUE =
                 settings_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
         }
         settings_parser__load_buffer_state(yyscanner );
         }
static void include_files (parser_helper_t * ctx) static
Assumes that the file pattern to include is currently stored as string on the helper object.
Definition at line 2666 of file settings_lexer.c.
References parser_helper_t::file_include, free(), settings_parser_open_next_file(), and parser_helper_t::string_get.
Referenced by while().
 {
     char *pattern = ctx->string_get(ctx);
     ctx->file_include(ctx, pattern);
     free(pattern);
     settings_parser_open_next_file(ctx);
 }
int isatty (int)
Referenced by settings_parser__init_buffer(), and tty_escape_get().
YY_BUFFER_STATE settings_parser__create_buffer (FILE * file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
Parameters
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
yyscanner The scanner object.
Returns
the allocated buffer state.
Definition at line 1850 of file settings_lexer.c.
References b, settings_parser__init_buffer(), settings_parser_alloc(), size, yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by if(), settings_parser_open_next_file(), and settings_parser_restart().
 {
     YY_BUFFER_STATE b;
     b = (YY_BUFFER_STATE) settings_parser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
     if ( ! b )
         YY_FATAL_ERROR( "out of dynamic memory in settings_parser__create_buffer()" );
     b->yy_buf_size = size;
     /* yy_ch_buf has to be 2 characters longer than the size given because
      * we need to put in 2 end-of-buffer characters.
      */
     b->yy_ch_buf = (char *) settings_parser_alloc(b->yy_buf_size + 2 ,yyscanner );
     if ( ! b->yy_ch_buf )
         YY_FATAL_ERROR( "out of dynamic memory in settings_parser__create_buffer()" );
     b->yy_is_our_buffer = 1;
     settings_parser__init_buffer(b,file ,yyscanner);
     return b;
 }
void settings_parser__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
Parameters
b a buffer created with settings_parser__create_buffer()
yyscanner The scanner object.
Definition at line 1882 of file settings_lexer.c.
References settings_parser_free(), yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_buffer_state::yy_is_our_buffer.
Referenced by settings_parser_lex_destroy(), and settings_parser_pop_buffer_state().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( ! b )
         return;
     if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
         YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;
     if ( b->yy_is_our_buffer )
         settings_parser_free((void *) b->yy_ch_buf ,yyscanner );
     settings_parser_free((void *) b ,yyscanner );
 }
void settings_parser__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters. On the next scan, YY_INPUT will be called.
Parameters
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 1955 of file settings_lexer.c.
References settings_parser__load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by settings_parser__init_buffer().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( ! b )
         return;
     b->yy_n_chars = 0;
     /* We always need two end-of-buffer characters.  The first causes
      * a transition to the end-of-buffer state.  The second causes
      * a jam in that state.
      */
     b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
     b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
     b->yy_buf_pos = &b->yy_ch_buf[0];
     b->yy_at_bol = 1;
     b->yy_buffer_status = YY_BUFFER_NEW;
     if ( b == YY_CURRENT_BUFFER )
         settings_parser__load_buffer_state(yyscanner );
 }
static void settings_parser__init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) static
Definition at line 1917 of file settings_lexer.c.
References isatty(), settings_parser__flush_buffer(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by settings_parser__create_buffer(), and settings_parser_restart().
 {
     int oerrno = errno;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     settings_parser__flush_buffer(b ,yyscanner);
     b->yy_input_file = file;
     b->yy_fill_buffer = 1;
     /* If b is the current buffer, then settings_parser__init_buffer was _probably_
      * called from settings_parser_restart() or through yy_get_next_buffer.
      * In that case, we don't want to reset the lineno or column.
      */
     if (b != YY_CURRENT_BUFFER){
         b->yy_bs_lineno = 1;
         b->yy_bs_column = 0;
     }
 /* %if-c-only */
         b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
 /* %endif */
 /* %if-c++-only */
 /* %endif */
     errno = oerrno;
 }
static void settings_parser__load_buffer_state (yyscan_t yyscanner) static
Definition at line 1831 of file settings_lexer.c.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yyin.
Referenced by if(), settings_parser__flush_buffer(), settings_parser__switch_to_buffer(), settings_parser_pop_buffer_state(), settings_parser_push_buffer_state(), and settings_parser_restart().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
     yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
     yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
     yyg->yy_hold_char = *yyg->yy_c_buf_p;
 }
YY_BUFFER_STATE settings_parser__scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Definition at line 2108 of file settings_lexer.c.
References b, base, settings_parser__switch_to_buffer(), settings_parser_alloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, and yy_buffer_state::yy_n_chars.
Referenced by settings_parser__scan_bytes().
 {
     YY_BUFFER_STATE b;
     if ( size < 2 ||
          base[size-2] != YY_END_OF_BUFFER_CHAR ||
          base[size-1] != YY_END_OF_BUFFER_CHAR )
         /* They forgot to leave room for the EOB's. */
         return 0;
     b = (YY_BUFFER_STATE) settings_parser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
     if ( ! b )
         YY_FATAL_ERROR( "out of dynamic memory in settings_parser__scan_buffer()" );
     b->yy_buf_size = size - 2;  /* "- 2" to take care of EOB's */
     b->yy_buf_pos = b->yy_ch_buf = base;
     b->yy_is_our_buffer = 0;
     b->yy_input_file = 0;
     b->yy_n_chars = b->yy_buf_size;
     b->yy_is_interactive = 0;
     b->yy_at_bol = 1;
     b->yy_fill_buffer = 0;
     b->yy_buffer_status = YY_BUFFER_NEW;
     settings_parser__switch_to_buffer(b ,yyscanner );
     return b;
 }
YY_BUFFER_STATE settings_parser__scan_bytes (yyconst char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes. The next call to settings_parser_lex() will scan from a copy of bytes.
Parameters
yybytes the byte buffer to scan
_yybytes_len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Definition at line 2162 of file settings_lexer.c.
References b, n, settings_parser__scan_buffer(), settings_parser_alloc(), YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by settings_parser__scan_string().
 {
     YY_BUFFER_STATE b;
     char *buf;
     yy_size_t n;
     int i;
     /* Get memory for full buffer, including space for trailing EOB's. */
     n = _yybytes_len + 2;
     buf = (char *) settings_parser_alloc(n ,yyscanner );
     if ( ! buf )
         YY_FATAL_ERROR( "out of dynamic memory in settings_parser__scan_bytes()" );
     for ( i = 0; i < _yybytes_len; ++i )
         buf[i] = yybytes[i];
     buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;
     b = settings_parser__scan_buffer(buf,n ,yyscanner);
     if ( ! b )
         YY_FATAL_ERROR( "bad buffer in settings_parser__scan_bytes()" );
     /* It's okay to grow etc. this buffer, and we should throw it
      * away when we're done.
      */
     b->yy_is_our_buffer = 1;
     return b;
 }
YY_BUFFER_STATE settings_parser__scan_string (yyconst char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string. The next call to settings_parser_lex() will scan from a copy of str.
Parameters
yystr a NUL-terminated string to scan
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Note
If you want to scan bytes that may contain NUL values, then use settings_parser__scan_bytes() instead.
Definition at line 2147 of file settings_lexer.c.
References settings_parser__scan_bytes().
Referenced by settings_parser_load_string().
 {
     return settings_parser__scan_bytes(yystr,strlen(yystr) ,yyscanner);
 }
void settings_parser__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
Parameters
new_buffer The new input buffer.
yyscanner The scanner object.
Definition at line 1795 of file settings_lexer.c.
References settings_parser__load_buffer_state(), settings_parser_ensure_buffer_stack(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
Referenced by settings_parser__scan_buffer().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     /* TODO. We should be able to replace this entire function body
      * with
      *      settings_parser_pop_buffer_state();
      *      settings_parser_push_buffer_state(new_buffer);
      */
     settings_parser_ensure_buffer_stack (yyscanner);
     if ( YY_CURRENT_BUFFER == new_buffer )
         return;
     if ( YY_CURRENT_BUFFER )
         {
         /* Flush out information for old buffer. */
         *yyg->yy_c_buf_p = yyg->yy_hold_char;
         YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
         }
     YY_CURRENT_BUFFER_LVALUE = new_buffer;
     settings_parser__load_buffer_state(yyscanner );
     /* We don't actually know whether we did this switch during
      * EOF (settings_parser_wrap()) processing, but the only time this flag
      * is looked at is after settings_parser_wrap() is called, so it's safe
      * to go ahead and always set it.
      */
     yyg->yy_did_buffer_switch_on_eof = 1;
 }
void * settings_parser_alloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 2609 of file settings_lexer.c.
References malloc().
Referenced by settings_parser__create_buffer(), settings_parser__scan_buffer(), settings_parser__scan_bytes(), settings_parser_ensure_buffer_stack(), settings_parser_lex_init(), settings_parser_lex_init_extra(), and yy_push_state().
 {
     return (void *) malloc( size );
 }
static void settings_parser_ensure_buffer_stack (yyscan_t yyscanner) static
Definition at line 2053 of file settings_lexer.c.
References memset, settings_parser_alloc(), settings_parser_realloc(), yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, and YY_FATAL_ERROR.
Referenced by if(), settings_parser__switch_to_buffer(), settings_parser_push_buffer_state(), and settings_parser_restart().
 {
     int num_to_alloc;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if (!yyg->yy_buffer_stack) {
         /* First allocation is just for 2 elements, since we don't know if this
          * scanner will even need a stack. We use 2 instead of 1 to avoid an
          * immediate realloc on the next call.
          */
         num_to_alloc = 1;
         yyg->yy_buffer_stack = (struct yy_buffer_state**)settings_parser_alloc
                                 (num_to_alloc * sizeof(struct yy_buffer_state*)
                                 , yyscanner);
         if ( ! yyg->yy_buffer_stack )
             YY_FATAL_ERROR( "out of dynamic memory in settings_parser_ensure_buffer_stack()" );
         memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
         yyg->yy_buffer_stack_max = num_to_alloc;
         yyg->yy_buffer_stack_top = 0;
         return;
     }
     if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){
         /* Increase the buffer to prepare for a possible push. */
         int grow_size = 8 /* arbitrary grow size */;
         num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
         yyg->yy_buffer_stack = (struct yy_buffer_state**)settings_parser_realloc
                                 (yyg->yy_buffer_stack,
                                 num_to_alloc * sizeof(struct yy_buffer_state*)
                                 , yyscanner);
         if ( ! yyg->yy_buffer_stack )
             YY_FATAL_ERROR( "out of dynamic memory in settings_parser_ensure_buffer_stack()" );
         /* zero only the new slots.*/
         memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
         yyg->yy_buffer_stack_max = num_to_alloc;
     }
 }
void settings_parser_free (void * ptr, yyscan_t yyscanner)
Definition at line 2626 of file settings_lexer.c.
References free().
Referenced by settings_parser__delete_buffer(), and settings_parser_lex_destroy().
 {
     free( (char *) ptr );   /* see settings_parser_realloc() for (char *) cast */
 }
int settings_parser_get_column (yyscan_t yyscanner)
Get the current column number.
Parameters
yyscanner The scanner object.
Definition at line 2308 of file settings_lexer.c.
References YY_CURRENT_BUFFER, and yycolumn.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         if (! YY_CURRENT_BUFFER)
             return 0;
     return yycolumn;
 }
int settings_parser_get_debug (yyscan_t yyscanner)
Definition at line 2417 of file settings_lexer.c.
References yy_flex_debug.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yy_flex_debug;
 }
YY_EXTRA_TYPE settings_parser_get_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters
yyscanner The scanner object.
Definition at line 2284 of file settings_lexer.c.
References yyextra.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyextra;
 }
FILE * settings_parser_get_in (yyscan_t yyscanner)
Get the input stream.
Parameters
yyscanner The scanner object.
Definition at line 2321 of file settings_lexer.c.
References yyin.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyin;
 }
int settings_parser_get_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters
yyscanner The scanner object.
Definition at line 2339 of file settings_lexer.c.
References yyleng.
Referenced by settings_parser_error().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyleng;
 }
int settings_parser_get_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters
yyscanner The scanner object.
Definition at line 2295 of file settings_lexer.c.
References YY_CURRENT_BUFFER, and yylineno.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         if (! YY_CURRENT_BUFFER)
             return 0;
     return yylineno;
 }
YYSTYPE * settings_parser_get_lval (yyscan_t yyscanner)
Definition at line 2436 of file settings_lexer.c.
References yylval.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yylval;
 }
FILE * settings_parser_get_out (yyscan_t yyscanner)
Get the output stream.
Parameters
yyscanner The scanner object.
Definition at line 2330 of file settings_lexer.c.
References yyout.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyout;
 }
char * settings_parser_get_text (yyscan_t yyscanner)
Get the current token.
Parameters
yyscanner The scanner object.
Definition at line 2349 of file settings_lexer.c.
References yytext.
Referenced by settings_parser_error().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yytext;
 }
int settings_parser_lex (YYSTYPE * yylval_param, yyscan_t yyscanner)
int settings_parser_lex_destroy (yyscan_t yyscanner)
Definition at line 2553 of file settings_lexer.c.
References settings_parser__delete_buffer(), settings_parser_free(), settings_parser_pop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     /* Pop the buffer stack, destroying each element. */
     while(YY_CURRENT_BUFFER){
         settings_parser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
         YY_CURRENT_BUFFER_LVALUE = NULL;
         settings_parser_pop_buffer_state(yyscanner);
     }
     /* Destroy the stack itself. */
     settings_parser_free(yyg->yy_buffer_stack ,yyscanner);
     yyg->yy_buffer_stack = NULL;
     /* Destroy the start condition stack. */
         settings_parser_free(yyg->yy_start_stack ,yyscanner );
         yyg->yy_start_stack = NULL;
     /* Reset the globals. This is important in a non-reentrant scanner so the next time
      * settings_parser_lex() is called, initialization will occur. */
     yy_init_globals( yyscanner);
 /* %if-reentrant */
     /* Destroy the main struct (reentrant only). */
     settings_parser_free ( yyscanner , yyscanner );
     yyscanner = NULL;
 /* %endif */
     return 0;
 }
int settings_parser_lex_init (yyscan_t * scanner)
Definition at line 2457 of file settings_lexer.c.
References memset, settings_parser_alloc(), and yy_init_globals().
 {
     if (ptr_yy_globals == NULL){
         errno = EINVAL;
         return 1;
     }
     *ptr_yy_globals = (yyscan_t) settings_parser_alloc ( sizeof( struct yyguts_t ), NULL );
     if (*ptr_yy_globals == NULL){
         errno = ENOMEM;
         return 1;
     }
     /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
     memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
     return yy_init_globals ( *ptr_yy_globals );
 }
int settings_parser_lex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t * scanner)
Definition at line 2486 of file settings_lexer.c.
References memset, settings_parser_alloc(), settings_parser_set_extra(), and yy_init_globals().
 {
     struct yyguts_t dummy_yyguts;
     settings_parser_set_extra (yy_user_defined, &dummy_yyguts);
     if (ptr_yy_globals == NULL){
         errno = EINVAL;
         return 1;
     }
     *ptr_yy_globals = (yyscan_t) settings_parser_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
     if (*ptr_yy_globals == NULL){
         errno = ENOMEM;
         return 1;
     }
     /* By setting to 0xAA, we expose bugs in
     yy_init_globals. Leave at 0x00 for releases. */
     memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
     settings_parser_set_extra (yy_user_defined, *ptr_yy_globals);
     return yy_init_globals ( *ptr_yy_globals );
 }
void settings_parser_load_string (parser_helper_t * ctx, const char * content)
Load the given string to be parsed next
Definition at line 2679 of file settings_lexer.c.
References parser_helper_t::scanner, and settings_parser__scan_string().
Referenced by settings_parser_parse_string().
 {
     settings_parser__scan_string(content, ctx->scanner);
 }
bool settings_parser_open_next_file (parser_helper_t * ctx)
Open the next file, if any is queued and readable, otherwise returns FALSE.
Definition at line 2645 of file settings_lexer.c.
References FALSE, parser_helper_t::file_next, parser_helper_t::scanner, settings_parser__create_buffer(), settings_parser_push_buffer_state(), settings_parser_set_in(), TRUE, and YY_BUF_SIZE.
Referenced by include_files(), settings_parser_parse_file(), and while().
 {
     FILE *file;
     file = ctx->file_next(ctx);
     if (!file)
     {
         return FALSE;
     }
     settings_parser_set_in(file, ctx->scanner);
     settings_parser_push_buffer_state(
             settings_parser__create_buffer(file, YY_BUF_SIZE,
                                            ctx->scanner), ctx->scanner);
     return TRUE;
 }
void settings_parser_pop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present. The next element becomes the new top.
Parameters
yyscanner The scanner object.
Definition at line 2027 of file settings_lexer.c.
References settings_parser__delete_buffer(), settings_parser__load_buffer_state(), yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by settings_parser_lex_destroy(), and while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if (!YY_CURRENT_BUFFER)
         return;
     settings_parser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
     YY_CURRENT_BUFFER_LVALUE = NULL;
     if (yyg->yy_buffer_stack_top > 0)
         --yyg->yy_buffer_stack_top;
     if (YY_CURRENT_BUFFER) {
         settings_parser__load_buffer_state(yyscanner );
         yyg->yy_did_buffer_switch_on_eof = 1;
     }
 }
void settings_parser_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack. The new state becomes the current state. This function will allocate the stack if necessary.
Parameters
new_buffer The new state.
yyscanner The scanner object.
Definition at line 1990 of file settings_lexer.c.
References settings_parser__load_buffer_state(), settings_parser_ensure_buffer_stack(), yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
Referenced by settings_parser_open_next_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if (new_buffer == NULL)
         return;
     settings_parser_ensure_buffer_stack(yyscanner);
     /* This block is copied from settings_parser__switch_to_buffer. */
     if ( YY_CURRENT_BUFFER )
         {
         /* Flush out information for old buffer. */
         *yyg->yy_c_buf_p = yyg->yy_hold_char;
         YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
         }
     /* Only push if top exists. Otherwise, replace top. */
     if (YY_CURRENT_BUFFER)
         yyg->yy_buffer_stack_top++;
     YY_CURRENT_BUFFER_LVALUE = new_buffer;
     /* copied from settings_parser__switch_to_buffer. */
     settings_parser__load_buffer_state(yyscanner );
     yyg->yy_did_buffer_switch_on_eof = 1;
 }
void * settings_parser_realloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 2614 of file settings_lexer.c.
Referenced by settings_parser_ensure_buffer_stack(), yy_get_next_buffer(), and yy_push_state().
 {
     /* The cast to (char *) in the following accommodates both
      * implementations that use char* generic pointers, and those
      * that use void* generic pointers.  It works with the latter
      * because both ANSI C and C++ allow castless assignment from
      * any pointer type to void*, and deal with argument conversions
      * as though doing an assignment.
      */
     return (void *) realloc( (char *) ptr, size );
 }
void settings_parser_restart (FILE * input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
Parameters
input_file A readable stream.
yyscanner The scanner object.
Note
This function does not reset the start condition to INITIAL .
Definition at line 1773 of file settings_lexer.c.
References settings_parser__create_buffer(), settings_parser__init_buffer(), settings_parser__load_buffer_state(), settings_parser_ensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyin.
Referenced by yy_get_next_buffer().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( ! YY_CURRENT_BUFFER ){
         settings_parser_ensure_buffer_stack (yyscanner);
         YY_CURRENT_BUFFER_LVALUE =
             settings_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
     }
     settings_parser__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
     settings_parser__load_buffer_state(yyscanner );
 }
void settings_parser_set_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters
line_number
yyscanner The scanner object.
Definition at line 2388 of file settings_lexer.c.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         /* column is only valid if an input buffer exists. */
         if (! YY_CURRENT_BUFFER )
            yy_fatal_error( "settings_parser_set_column called with no buffer" , yyscanner);
     yycolumn = column_no;
 }
void settings_parser_set_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 2423 of file settings_lexer.c.
References yy_flex_debug.
Referenced by settings_parser_parse_file(), and settings_parser_parse_string().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yy_flex_debug = bdebug ;
 }
void settings_parser_set_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data. This data is never touched by the scanner.
Parameters
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 2361 of file settings_lexer.c.
References yyextra.
Referenced by settings_parser_lex_init_extra().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyextra = user_defined ;
 }
void settings_parser_set_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream. This does not discard the current input buffer.
Parameters
in_str A readable stream.
yyscanner The scanner object.
See Also
settings_parser__switch_to_buffer
Definition at line 2405 of file settings_lexer.c.
References yyin.
Referenced by settings_parser_open_next_file().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyin = in_str ;
 }
void settings_parser_set_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters
line_number
yyscanner The scanner object.
Definition at line 2373 of file settings_lexer.c.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
         /* lineno is only valid if an input buffer exists. */
         if (! YY_CURRENT_BUFFER )
            yy_fatal_error( "settings_parser_set_lineno called with no buffer" , yyscanner);
     yylineno = line_number;
 }
void settings_parser_set_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Definition at line 2442 of file settings_lexer.c.
References yylval.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yylval = yylval_param;
 }
void settings_parser_set_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 2411 of file settings_lexer.c.
References yyout.
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yyout = out_str ;
 }
while (1)
Definition at line 991 of file settings_lexer.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, fprintf, inc, include_files(), INITIAL, NAME, NEWLINE, PARSER_DBG1, settings_parser_open_next_file(), settings_parser_pop_buffer_state(), settings_parser_wrap, str, strdup, streq(), STRING, STRING_ERROR, unput, yy_accept, yy_base, YY_BREAK, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_def, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_flex_debug, yy_get_next_buffer(), yy_get_previous_state(), yyguts_t::yy_hold_char, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_nxt, yy_pop_state(), yy_push_state(), YY_RESTORE_YY_MORE_OFFSET, yy_rule_can_match_eol, yy_rule_linenum, YY_RULE_SETUP, YY_SC_TO_UI, yy_set_bol, YY_START, yyguts_t::yy_start, YY_STATE_EOF, yy_top_state(), yy_try_NUL_trans(), yycolumn, yyextra, yyin, yyleng, yylineno, yylval, yyterminate, and yytext.
Referenced by METHOD().
         {
 /* %% [8.0] yymore()-related code goes here */
         yy_cp = yyg->yy_c_buf_p;
         /* Support of yytext. */
         *yy_cp = yyg->yy_hold_char;
         /* yy_bp points to the position in yy_ch_buf of the start of
          * the current run.
          */
         yy_bp = yy_cp;
 /* %% [9.0] code to set up and find next match goes here */
         yy_current_state = yyg->yy_start;
 yy_match:
         do
             {
             register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
             if ( yy_accept[yy_current_state] )
                 {
                 yyg->yy_last_accepting_state = yy_current_state;
                 yyg->yy_last_accepting_cpos = yy_cp;
                 }
             while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                 {
                 yy_current_state = (int) yy_def[yy_current_state];
                 if ( yy_current_state >= 49 )
                     yy_c = yy_meta[(unsigned int) yy_c];
                 }
             yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
             ++yy_cp;
             }
         while ( yy_base[yy_current_state] != 161 );
 yy_find_action:
 /* %% [10.0] code to find the action number goes here */
         yy_act = yy_accept[yy_current_state];
         if ( yy_act == 0 )
             { /* have to back up */
             yy_cp = yyg->yy_last_accepting_cpos;
             yy_current_state = yyg->yy_last_accepting_state;
             yy_act = yy_accept[yy_current_state];
             }
         YY_DO_BEFORE_ACTION;
 /* %% [11.0] code for yylineno update goes here */
         if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
             {
             int yyl;
             for ( yyl = 0; yyl < yyleng; ++yyl )
                 if ( yytext[yyl] == '\n' )
     do{ yylineno++;
         yycolumn=0;
     }while(0)
 ;
             }
 do_action:  /* This label is used only to access EOF actions. */
 /* %% [12.0] debug code goes here */
         if ( yy_flex_debug )
             {
             if ( yy_act == 0 )
                 fprintf( stderr, "--scanner backing up\n" );
             else if ( yy_act < 23 )
                 fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
                          (long)yy_rule_linenum[yy_act], yytext );
             else if ( yy_act == 23 )
                 fprintf( stderr, "--accepting default rule (\"%s\")\n",
                          yytext );
             else if ( yy_act == 24 )
                 fprintf( stderr, "--(end of buffer or a NUL)\n" );
             else
                 fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
             }
         switch ( yy_act )
     { /* beginning of action switch */
 /* %% [13.0] actions go here */
             case 0: /* must back up */
             /* undo the effects of YY_DO_BEFORE_ACTION */
             *yy_cp = yyg->yy_hold_char;
             yy_cp = yyg->yy_last_accepting_cpos;
             yy_current_state = yyg->yy_last_accepting_state;
             goto yy_find_action;
 case 1:
 YY_RULE_SETUP
 #line 59 "settings/settings_lexer.l"
 /* eat comments */
     YY_BREAK
 case 2:
 YY_RULE_SETUP
 #line 60 "settings/settings_lexer.l"
 /* eat whitespace */
     YY_BREAK
 case 3:
 /* rule 3 can match eol */
 YY_RULE_SETUP
 #line 61 "settings/settings_lexer.l"
 return NEWLINE; /* also eats comments at the end of a line */
     YY_BREAK
 case 4:
 #line 64 "settings/settings_lexer.l"
 case 5:
 #line 65 "settings/settings_lexer.l"
 case 6:
 YY_RULE_SETUP
 #line 65 "settings/settings_lexer.l"
 return yytext[0];
     YY_BREAK
 case 7:
 /* rule 7 can match eol */
 *yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
 yyg->yy_c_buf_p = yy_cp -= 1;
 YY_DO_BEFORE_ACTION; /* set up yytext again */
 YY_RULE_SETUP
 #line 67 "settings/settings_lexer.l"
 {
     yyextra->string_init(yyextra);
     yy_push_state(inc, yyscanner);
 }
     YY_BREAK
 case 8:
 YY_RULE_SETUP
 #line 72 "settings/settings_lexer.l"
 {
     yyextra->string_init(yyextra);
     yy_push_state(str, yyscanner);
 }
     YY_BREAK
 case 9:
 YY_RULE_SETUP
 #line 77 "settings/settings_lexer.l"
 {
     yylval->s = strdup(yytext);
     return NAME;
 }
     YY_BREAK
 /* we allow all characters except #, } and spaces, they can be escaped */
 case YY_STATE_EOF(inc):
 #line 84 "settings/settings_lexer.l"
 case 10:
 /* rule 10 can match eol */
 YY_RULE_SETUP
 #line 85 "settings/settings_lexer.l"
 {
         if (*yytext)
         {
             switch (yytext[0])
             {
                 case '\n':
                     /* put the newline back to fix the line numbers */
                     unput('\n');
                     yy_set_bol(0);
                     break;
                 case '#':
                 case '}':
                     /* these are parsed outside of this start condition */
                     unput(yytext[0]);
                     break;
             }
         }
         include_files(yyextra);
         yy_pop_state(yyscanner);
     }
     YY_BREAK
 case 11:
 YY_RULE_SETUP
 #line 105 "settings/settings_lexer.l"
 {   /* string include */
         yy_push_state(str, yyscanner);
     }
     YY_BREAK
 case 12:
 YY_RULE_SETUP
 #line 108 "settings/settings_lexer.l"
 {
         yyextra->string_add(yyextra, yytext);
     }
     YY_BREAK
 case 13:
 YY_RULE_SETUP
 #line 111 "settings/settings_lexer.l"
 {
         yyextra->string_add(yyextra, yytext+1);
     }
     YY_BREAK
 case 14:
 YY_RULE_SETUP
 #line 114 "settings/settings_lexer.l"
 {
         yyextra->string_add(yyextra, yytext);
     }
     YY_BREAK
 case 15:
 #line 121 "settings/settings_lexer.l"
 case YY_STATE_EOF(str):
 #line 121 "settings/settings_lexer.l"
 case 16:
 YY_RULE_SETUP
 #line 122 "settings/settings_lexer.l"
 {
         if (!streq(yytext, "\""))
         {
             PARSER_DBG1(yyextra, "unterminated string detected");
             return STRING_ERROR;
         }
         if (yy_top_state(yyscanner) == inc)
         {   /* string include */
             include_files(yyextra);
             yy_pop_state(yyscanner);
             yy_pop_state(yyscanner);
         }
         else
         {
             yy_pop_state(yyscanner);
             yylval->s = yyextra->string_get(yyextra);
             return STRING;
         }
     }
     YY_BREAK
 case 17:
 YY_RULE_SETUP
 #line 141 "settings/settings_lexer.l"
 yyextra->string_add(yyextra, "\n");
     YY_BREAK
 case 18:
 YY_RULE_SETUP
 #line 142 "settings/settings_lexer.l"
 yyextra->string_add(yyextra, "\r");
     YY_BREAK
 case 19:
 YY_RULE_SETUP
 #line 143 "settings/settings_lexer.l"
 yyextra->string_add(yyextra, "\t");
     YY_BREAK
 case 20:
 /* rule 20 can match eol */
 YY_RULE_SETUP
 #line 144 "settings/settings_lexer.l"
 /* merge lines that end with EOL characters */
     YY_BREAK
 case 21:
 YY_RULE_SETUP
 #line 145 "settings/settings_lexer.l"
 yyextra->string_add(yyextra, yytext+1);
     YY_BREAK
 case 22:
 /* rule 22 can match eol */
 YY_RULE_SETUP
 #line 146 "settings/settings_lexer.l"
 {
         yyextra->string_add(yyextra, yytext);
     }
     YY_BREAK
 case YY_STATE_EOF(INITIAL):
 #line 151 "settings/settings_lexer.l"
 {
     settings_parser_pop_buffer_state(yyscanner);
     if (!settings_parser_open_next_file(yyextra) && !YY_CURRENT_BUFFER)
     {
         yyterminate();
     }
 }
     YY_BREAK
 case 23:
 YY_RULE_SETUP
 #line 159 "settings/settings_lexer.l"
 YY_FATAL_ERROR( "flex scanner jammed" );
     YY_BREAK
 #line 1271 "settings/settings_lexer.c"
     case YY_END_OF_BUFFER:
         {
         /* Amount of text matched not including the EOB char. */
         int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;
         /* Undo the effects of YY_DO_BEFORE_ACTION. */
         *yy_cp = yyg->yy_hold_char;
         YY_RESTORE_YY_MORE_OFFSET
         if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
             {
             /* We're scanning a new file or input source.  It's
              * possible that this happened because the user
              * just pointed yyin at a new source and called
              * settings_parser_lex().  If so, then we have to assure
              * consistency between YY_CURRENT_BUFFER and our
              * globals.  Here is the right place to do so, because
              * this is the first action (other than possibly a
              * back-up) that will match for the new input source.
              */
             yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
             YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
             YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
             }
         /* Note that here we test for yy_c_buf_p "<=" to the position
          * of the first EOB in the buffer, since yy_c_buf_p will
          * already have been incremented past the NUL character
          * (since all states make transitions on EOB to the
          * end-of-buffer state).  Contrast this with the test
          * in input().
          */
         if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
             { /* This was really a NUL. */
             yy_state_type yy_next_state;
             yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;
             yy_current_state = yy_get_previous_state( yyscanner );
             /* Okay, we're now positioned to make the NUL
              * transition.  We couldn't have
              * yy_get_previous_state() go ahead and do it
              * for us because it doesn't know how to deal
              * with the possibility of jamming (and we don't
              * want to build jamming into it because then it
              * will run more slowly).
              */
             yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);
             yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
             if ( yy_next_state )
                 {
                 /* Consume the NUL. */
                 yy_cp = ++yyg->yy_c_buf_p;
                 yy_current_state = yy_next_state;
                 goto yy_match;
                 }
             else
                 {
 /* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
                 yy_cp = yyg->yy_c_buf_p;
                 goto yy_find_action;
                 }
             }
         else switch ( yy_get_next_buffer( yyscanner ) )
             {
             case EOB_ACT_END_OF_FILE:
                 {
                 yyg->yy_did_buffer_switch_on_eof = 0;
                 if ( settings_parser_wrap(yyscanner ) )
                     {
                     /* Note: because we've taken care in
                      * yy_get_next_buffer() to have set up
                      * yytext, we can now set up
                      * yy_c_buf_p so that if some total
                      * hoser (like flex itself) wants to
                      * call the scanner after we return the
                      * YY_NULL, it'll still work - another
                      * YY_NULL will get returned.
                      */
                     yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;
                     yy_act = YY_STATE_EOF(YY_START);
                     goto do_action;
                     }
                 else
                     {
                     if ( ! yyg->yy_did_buffer_switch_on_eof )
                         YY_NEW_FILE;
                     }
                 break;
                 }
             case EOB_ACT_CONTINUE_SCAN:
                 yyg->yy_c_buf_p =
                     yyg->yytext_ptr + yy_amount_of_matched_text;
                 yy_current_state = yy_get_previous_state( yyscanner );
                 yy_cp = yyg->yy_c_buf_p;
                 yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                 goto yy_match;
             case EOB_ACT_LAST_MATCH:
                 yyg->yy_c_buf_p =
                 &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];
                 yy_current_state = yy_get_previous_state( yyscanner );
                 yy_cp = yyg->yy_c_buf_p;
                 yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                 goto yy_find_action;
             }
         break;
         }
     default:
         YY_FATAL_ERROR(
             "fatal flex scanner internal error--no action found" );
     } /* end of action switch */
         } /* end of scanning one token */
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner) static
Referenced by settings_parser_set_column(), and settings_parser_set_lineno().
static void yy_fatal_error (yyconst char * msg, yyscan_t yyscanner) static
Definition at line 2250 of file settings_lexer.c.
References fprintf, and YY_EXIT_FAILURE.
 {
         (void) fprintf( stderr, "%s\n", msg );
     exit( YY_EXIT_FAILURE );
 }
static int yy_get_next_buffer (yyscan_t yyscanner) static
Definition at line 1418 of file settings_lexer.c.
References b, dest, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, settings_parser_realloc(), settings_parser_restart(), source, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_READ_BUF_SIZE, and yyin.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
     register char *source = yyg->yytext_ptr;
     register int number_to_move, i;
     int ret_val;
     if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
         YY_FATAL_ERROR(
         "fatal flex scanner internal error--end of buffer missed" );
     if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
         { /* Don't try to fill the buffer, so this is an EOF. */
         if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
             {
             /* We matched a single character, the EOB, so
              * treat this as a final EOF.
              */
             return EOB_ACT_END_OF_FILE;
             }
         else
             {
             /* We matched some text prior to the EOB, first
              * process it.
              */
             return EOB_ACT_LAST_MATCH;
             }
         }
     /* Try to read more data. */
     /* First move last chars to start of buffer. */
     number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;
     for ( i = 0; i < number_to_move; ++i )
         *(dest++) = *(source++);
     if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
         /* don't do the read, it's not guaranteed to return an EOF,
          * just force an EOF
          */
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;
     else
         {
             int num_to_read =
             YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
         while ( num_to_read <= 0 )
             { /* Not enough room in the buffer - grow it. */
             /* just a shorter name for the current buffer */
             YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
             int yy_c_buf_p_offset =
                 (int) (yyg->yy_c_buf_p - b->yy_ch_buf);
             if ( b->yy_is_our_buffer )
                 {
                 int new_size = b->yy_buf_size * 2;
                 if ( new_size <= 0 )
                     b->yy_buf_size += b->yy_buf_size / 8;
                 else
                     b->yy_buf_size *= 2;
                 b->yy_ch_buf = (char *)
                     /* Include room in for 2 EOB chars. */
                     settings_parser_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
                 }
             else
                 /* Can't grow it, we don't own it. */
                 b->yy_ch_buf = 0;
             if ( ! b->yy_ch_buf )
                 YY_FATAL_ERROR(
                 "fatal error - scanner input buffer overflow" );
             yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
             num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                         number_to_move - 1;
             }
         if ( num_to_read > YY_READ_BUF_SIZE )
             num_to_read = YY_READ_BUF_SIZE;
         /* Read in more data. */
         YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
             yyg->yy_n_chars, (size_t) num_to_read );
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
         }
     if ( yyg->yy_n_chars == 0 )
         {
         if ( number_to_move == YY_MORE_ADJ )
             {
             ret_val = EOB_ACT_END_OF_FILE;
             settings_parser_restart(yyin  ,yyscanner);
             }
         else
             {
             ret_val = EOB_ACT_LAST_MATCH;
             YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
                 YY_BUFFER_EOF_PENDING;
             }
         }
     else
         ret_val = EOB_ACT_CONTINUE_SCAN;
     if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
         /* Extend the array by 50%, plus the number we really need. */
         yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
         YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) settings_parser_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
         if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
             YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
     }
     yyg->yy_n_chars += number_to_move;
     YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
     YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
     yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];
     return ret_val;
 }
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) static
Definition at line 1559 of file settings_lexer.c.
References yy_accept, yy_base, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, yy_def, yy_ec, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_nxt, YY_SC_TO_UI, and yyguts_t::yy_start.
Referenced by while().
 {
     register yy_state_type yy_current_state;
     register char *yy_cp;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
 /* %% [15.0] code to get the start state into yy_current_state goes here */
     yy_current_state = yyg->yy_start;
     for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
         {
 /* %% [16.0] code to find the next state goes here */
         register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
         if ( yy_accept[yy_current_state] )
             {
             yyg->yy_last_accepting_state = yy_current_state;
             yyg->yy_last_accepting_cpos = yy_cp;
             }
         while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
             {
             yy_current_state = (int) yy_def[yy_current_state];
             if ( yy_current_state >= 49 )
                 yy_c = yy_meta[(unsigned int) yy_c];
             }
         yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
         }
     return yy_current_state;
 }
static int yy_init_globals (yyscan_t yyscanner) static
Definition at line 2517 of file settings_lexer.c.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
Referenced by settings_parser_lex_destroy(), settings_parser_lex_init(), and settings_parser_lex_init_extra().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     /* Initialization is the same as for the non-reentrant scanner.
      * This function is called from settings_parser_lex_destroy(), so don't allocate here.
      */
     yyg->yy_buffer_stack = 0;
     yyg->yy_buffer_stack_top = 0;
     yyg->yy_buffer_stack_max = 0;
     yyg->yy_c_buf_p = (char *) 0;
     yyg->yy_init = 0;
     yyg->yy_start = 0;
     yyg->yy_start_stack_ptr = 0;
     yyg->yy_start_stack_depth = 0;
     yyg->yy_start_stack =  NULL;
 /* Defined in main.c */
 #ifdef YY_STDINIT
     yyin = stdin;
     yyout = stdout;
 #else
     yyin = (FILE *) 0;
     yyout = (FILE *) 0;
 #endif
     /* For future reference: Set errno on error, since we are called by
      * settings_parser_lex_init()
      */
     return 0;
 }
static void yy_pop_state (yyscan_t yyscanner) static
Definition at line 2223 of file settings_lexer.c.
References BEGIN, YY_FATAL_ERROR, yyguts_t::yy_start_stack, and yyguts_t::yy_start_stack_ptr.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( --yyg->yy_start_stack_ptr < 0 )
         YY_FATAL_ERROR( "start-condition stack underflow" );
     BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
 }
static void yy_push_state (int new_state, yyscan_t yyscanner) static
Definition at line 2194 of file settings_lexer.c.
References BEGIN, settings_parser_alloc(), settings_parser_realloc(), YY_FATAL_ERROR, YY_START, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, YY_START_STACK_INCR, and yyguts_t::yy_start_stack_ptr.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
         {
         yy_size_t new_size;
         yyg->yy_start_stack_depth += YY_START_STACK_INCR;
         new_size = yyg->yy_start_stack_depth * sizeof( int );
         if ( ! yyg->yy_start_stack )
             yyg->yy_start_stack = (int *) settings_parser_alloc(new_size ,yyscanner );
         else
             yyg->yy_start_stack = (int *) settings_parser_realloc((void *) yyg->yy_start_stack,new_size ,yyscanner );
         if ( ! yyg->yy_start_stack )
             YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
         }
     yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;
     BEGIN(new_state);
 }
static int yy_top_state (yyscan_t yyscanner) static
Definition at line 2236 of file settings_lexer.c.
References yyguts_t::yy_start_stack, and yyguts_t::yy_start_stack_ptr.
Referenced by while().
 {
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     return yyg->yy_start_stack[yyg->yy_start_stack_ptr - 1];
 }
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) static
Definition at line 1598 of file settings_lexer.c.
References yy_accept, yy_base, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, yy_def, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, and yy_nxt.
Referenced by while().
 {
     register int yy_is_jam;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
 /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
     register char *yy_cp = yyg->yy_c_buf_p;
     register YY_CHAR yy_c = 1;
     if ( yy_accept[yy_current_state] )
         {
         yyg->yy_last_accepting_state = yy_current_state;
         yyg->yy_last_accepting_cpos = yy_cp;
         }
     while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
         {
         yy_current_state = (int) yy_def[yy_current_state];
         if ( yy_current_state >= 49 )
             yy_c = yy_meta[(unsigned int) yy_c];
         }
     yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
     yy_is_jam = (yy_current_state == 48);
     return yy_is_jam ? 0 : yy_current_state;
 }
static void yyunput (int c, char * buf_ptr, yyscan_t yyscanner) static
static void yyunput (int c, register char * yy_bp, yyscan_t yyscanner) static
Definition at line 1628 of file settings_lexer.c.
References dest, source, yy_bp, yyguts_t::yy_c_buf_p, yy_cp, YY_CURRENT_BUFFER_LVALUE, YY_FATAL_ERROR, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yylineno.
 {
     register char *yy_cp;
     struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
     yy_cp = yyg->yy_c_buf_p;
     /* undo effects of setting up yytext */
     *yy_cp = yyg->yy_hold_char;
     if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
         { /* need to shift things up to make room */
         /* +2 for EOB chars. */
         register int number_to_move = yyg->yy_n_chars + 2;
         register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
                     YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
         register char *source =
                 &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];
         while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
             *--dest = *--source;
         yy_cp += (int) (dest - source);
         yy_bp += (int) (dest - source);
         YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
             yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;
         if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
             YY_FATAL_ERROR( "flex scanner push-back overflow" );
         }
     *--yy_cp = (char) c;
 /* %% [18.0] update yylineno here */
     if ( c == '\n' ){
         --yylineno;
     }
     yyg->yytext_ptr = yy_bp;
     yyg->yy_hold_char = *yy_cp;
     yyg->yy_c_buf_p = yy_cp;
 }
Variable Documentation
yyconst flex_int16_t yy_accept[49] static
Initial value:
=
    {   0,
        0,    0,    0,    0,    0,    0,   24,    9,    2,    3,
        8,    1,    6,    9,    4,    5,   14,   10,   11,   12,
       22,   15,   16,    9,    2,    1,    1,    3,    9,   14,
       13,   22,   21,   20,   21,   17,   18,   19,    1,    9,
        9,    9,    9,    9,    0,    7,    7,    0
    }
Definition at line 468 of file settings_lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register int yy_act
Definition at line 946 of file settings_lexer.c.
yyconst flex_int16_t yy_base[60] static
Initial value:
=
    {   0,
        0,    0,   19,   38,   21,   23,   55,    0,   47,  161,
      161,   50,  161,   37,  161,  161,    0,  161,  161,    0,
        0,  161,   56,    0,   44,    0,   47,  161,   39,    0,
      161,    0,  161,  161,   45,  161,  161,  161,    0,   32,
       24,   26,   11,   29,   31,  161,   33,  161,   73,   82,
       91,   97,  101,  110,  115,  124,  133,  142,  151
    }
Definition at line 515 of file settings_lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register char * yy_bp
Definition at line 945 of file settings_lexer.c.
Referenced by yyunput().
yyconst flex_int16_t yy_chk[182] static
Initial value:
=
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,   43,    3,    3,    3,    5,    3,    6,    5,
       44,    6,   45,   44,   47,   45,   42,   47,    3,    4,
        4,   41,    4,    4,    4,   40,    4,   35,   29,   27,
       25,   14,   12,    9,    7,    0,    0,    4,   23,   23,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,   23,   23,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   51,    0,    0,    0,    0,    0,   51,   52,    0,
       52,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       54,    0,    0,    0,    0,   54,    0,   54,   55,   55,
        0,    0,    0,   55,   56,   56,   56,   56,    0,   56,
        0,   56,   56,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   58,   58,    0,   58,   58,   58,   58,   58,
       58,   59,   59,   59,   59,   59,    0,   59,   59,   59,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48
    }
Definition at line 559 of file settings_lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register char* yy_cp
Definition at line 945 of file settings_lexer.c.
Referenced by while(), yy_get_previous_state(), yy_try_NUL_trans(), and yyunput().
YY_DECL
Initial value:
{
    register yy_state_type yy_current_state
The main scanner function which does all the work.
Definition at line 943 of file settings_lexer.c.
yyconst flex_int16_t yy_def[60] static
Initial value:
=
    {   0,
       48,    1,   49,   49,   50,   50,   48,   51,   52,   48,
       48,   53,   48,   51,   48,   48,   54,   48,   48,   55,
       56,   48,   57,   51,   52,   58,   53,   48,   51,   54,
       48,   56,   48,   48,   48,   48,   48,   48,   58,   51,
       51,   51,   51,   51,   59,   48,   59,    0,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48
    }
Definition at line 525 of file settings_lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int32_t yy_ec[256] static
Definition at line 477 of file settings_lexer.c.
Referenced by while(), and yy_get_previous_state().
yyconst flex_int32_t yy_meta[21] static
Initial value:
=
    {   0,
        1,    2,    3,    1,    4,    5,    4,    6,    7,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,    9
    }
Definition at line 509 of file settings_lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int16_t yy_nxt[182] static
Initial value:
=
    {   0,
        8,    9,   10,    8,    9,   11,   12,   13,    8,    8,
        8,    8,   14,    8,    8,    8,    8,    8,   15,   16,
       18,   18,   44,   18,   19,   18,   22,   20,   22,   23,
       45,   23,   47,   45,   47,   47,   43,   47,   18,   18,
       18,   42,   18,   19,   18,   41,   20,   34,   40,   28,
       26,   29,   28,   26,   48,   48,   48,   18,   34,   35,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       36,   37,   38,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   24,   48,   48,   48,   48,   48,   24,   25,   48,
       25,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       30,   48,   48,   48,   48,   30,   48,   30,   31,   31,
       48,   48,   48,   31,   32,   32,   32,   32,   48,   32,
       48,   32,   32,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   39,   39,   48,   39,   39,   39,   39,   39,
       39,   46,   46,   46,   46,   46,   48,   46,   46,   46,
        7,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48
    }
Definition at line 535 of file settings_lexer.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int32_t yy_rule_can_match_eol[24] static
Initial value:
=
    {   0,
0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 0, 1, 0,     }
Definition at line 584 of file settings_lexer.c.
Referenced by while().
yyconst flex_int16_t yy_rule_linenum[23] static
Initial value:
=
    {   0,
       59,   60,   61,   63,   64,   65,   67,   72,   77,   85,
      105,  108,  111,  114,  120,  122,  141,  142,  143,  144,
      145,  146
    }
Definition at line 589 of file settings_lexer.c.
Referenced by while().
struct yyguts_t* yyg = (struct yyguts_t*)yyscanner
Definition at line 947 of file settings_lexer.c.
yylval = yylval_param
Definition at line 955 of file settings_lexer.c.