strongSwan: crypter_t Struct Reference
crypter_t Struct Reference
crypter
#include "crypter.h"
Public Attributes
bool(* encrypt)(crypter_t *this, chunk_t data, chunk_t iv, chunk_t *encrypted) __attribute__((warn_unused_result))
bool(* decrypt)(crypter_t *this, chunk_t data, chunk_t iv, chunk_t *decrypted) __attribute__((warn_unused_result))
size_t(* get_block_size)(crypter_t *this)
size_t(* get_iv_size)(crypter_t *this)
size_t(* get_key_size)(crypter_t *this)
bool(* set_key)(crypter_t *this, chunk_t key) __attribute__((warn_unused_result))
void(* destroy)(crypter_t *this)
Detailed Description
Generic interface for symmetric encryption algorithms.
Definition at line 93 of file crypter.h.
Member Data Documentation
bool(* crypter_t::decrypt)(crypter_t *this, chunk_t data, chunk_t iv, chunk_t *decrypted) __attribute__((warn_unused_result))
Decrypt a chunk of data and allocate space for the decrypted value.
The length of the iv must equal to get_iv_size(), while the length of data must be a multiple of get_block_size(). If decrpyted is NULL, the encryption is done in-place (overwriting data).
Parameters
data data to decrypt
iv initializing vector
encrypted chunk to allocate decrypted data, or NULL
Returns
TRUE if decryption successful
Definition at line 122 of file crypter.h.
Referenced by bench_crypter(), burn_crypter(), decrypt(), do_crypt(), METHOD(), and pem_decrypt().
void(* crypter_t::destroy)(crypter_t *this)
Destroys a crypter_t object.
Definition at line 168 of file crypter.h.
Referenced by bench_crypter(), burn_crypter(), ChallengeResponse(), cmac_create(), decrypt(), do_test_cbc(), do_test_mct(), generate(), METHOD(), pem_decrypt(), rdrand_mixed(), and xcbc_create().
bool(* crypter_t::encrypt)(crypter_t *this, chunk_t data, chunk_t iv, chunk_t *encrypted) __attribute__((warn_unused_result))
Encrypt a chunk of data and allocate space for the encrypted value.
The length of the iv must equal to get_iv_size(), while the length of data must be a multiple of get_block_size(). If encrypted is NULL, the encryption is done in-place (overwriting data).
Parameters
data data to encrypt
iv initializing vector
encrypted chunk to allocate encrypted data, or NULL
Returns
TRUE if encryption successful
Definition at line 107 of file crypter.h.
Referenced by bench_crypter(), burn_crypter(), ChallengeResponse(), crypt_ctr(), do_crypt(), generate(), METHOD(), and rdrand_mixed().
size_t(* crypter_t::get_block_size)(crypter_t *this)
Get the block size of the crypto algorithm.
get_block_size() returns the smallest block the crypter can handle, not the block size of the underlying crypto algorithm. For counter mode, it is usually 1.
Returns
block size in bytes
Definition at line 134 of file crypter.h.
Referenced by burn_crypter(), cmac_create(), decrypt(), do_test_mct(), generate(), METHOD(), pem_decrypt(), verify_padding(), and xcbc_create().
size_t(* crypter_t::get_iv_size)(crypter_t *this)
Get the IV size of the crypto algorithm.
Returns
initialization vector size in bytes
Definition at line 141 of file crypter.h.
Referenced by bench_crypter(), burn_crypter(), crypt_ctr(), decrypt(), generate(), METHOD(), and pem_decrypt().
size_t(* crypter_t::get_key_size)(crypter_t *this)
Get the key size of the crypto algorithm.
get_key_size() might return a key length different from the key size passed to the factory constructor. For Counter Mode, the nonce is handled as a part of the key material and is passed to set_key().
Returns
key size in bytes
Definition at line 152 of file crypter.h.
Referenced by bench_crypter(), burn_crypter(), create_aead(), decrypt(), derive_ike_traditional(), generate(), and METHOD().
bool(* crypter_t::set_key)(crypter_t *this, chunk_t key) __attribute__((warn_unused_result))
Set the key.
The length of the key must match get_key_size().
Parameters
key key to set
Returns
TRUE if key set successfully
Definition at line 162 of file crypter.h.
Referenced by aead_create_from_keys(), bench_crypter(), burn_crypter(), ChallengeResponse(), create_aead(), create_traditional(), decrypt(), derive_ike_traditional(), do_test_cbc(), do_test_mct(), generate(), METHOD(), pem_decrypt(), and rdrand_mixed().
The documentation for this struct was generated from the following file:
crypter.h