strongSwan: proposal_keywords.c File Reference
proposal_keywords.c File Reference
#include "proposal_keywords.h"
#include "proposal_keywords_static.h"
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_proposal_keywords_t
Typedefs
typedef struct
private_proposal_keywords_t private_proposal_keywords_t
Functions
static const proposal_token_t * find_token (private_proposal_keywords_t *this, const char *str)
static const proposal_token_t * parse_token (private_proposal_keywords_t *this, const char *str)
METHOD (proposal_keywords_t, get_token, const proposal_token_t *, private_proposal_keywords_t *this, const char *str)
METHOD (proposal_keywords_t, register_token, void, private_proposal_keywords_t *this, const char *name, transform_type_t type, u_int16_t algorithm, u_int16_t keysize)
METHOD (proposal_keywords_t, register_algname_parser, void, private_proposal_keywords_t *this, proposal_algname_parser_t parser)
METHOD (proposal_keywords_t, destroy, void, private_proposal_keywords_t *this)
proposal_keywords_t * proposal_keywords_create ()
Typedef Documentation
typedef struct private_proposal_keywords_t private_proposal_keywords_t
Definition at line 44 of file proposal_keywords.c.
Function Documentation
static const proposal_token_t* find_token (private_proposal_keywords_t * this, const char * str) static
Find the token object for the algorithm specified.
Definition at line 72 of file proposal_keywords.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, lock, proposal_token_t::name, streq(), and spinlock_t::unlock.
Referenced by METHOD().
 {
     proposal_token_t *token, *found = NULL;
     enumerator_t *enumerator;
     this->lock->read_lock(this->lock);
     enumerator = this->tokens->create_enumerator(this->tokens);
     while (enumerator->enumerate(enumerator, &token))
     {
         if (streq(token->name, str))
         {
             found = token;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (proposal_keywords_t , get_token , const proposal_token_t * , private_proposal_keywords_t * this, const char * str)
Definition at line 118 of file proposal_keywords.c.
References find_token(), parse_token(), and proposal_get_token_static().
 {
     const proposal_token_t *token;
     token = proposal_get_token_static(str, strlen(str));
     if (!token)
     {
         token = find_token(this, str);
     }
     if (!token)
     {
         token = parse_token(this, str);
     }
     return token;
 }
METHOD (proposal_keywords_t , register_token , void , private_proposal_keywords_t * this, const char * name, transform_type_t type, u_int16_t algorithm, u_int16_t keysize)
Definition at line 135 of file proposal_keywords.c.
References INIT, lock, strdup, and spinlock_t::unlock.
 {
     proposal_token_t *token;
     INIT(token,
         .name = strdup(name),
         .type = type,
         .algorithm = algorithm,
         .keysize = keysize,
     );
     this->lock->write_lock(this->lock);
     this->tokens->insert_first(this->tokens, token);
     this->lock->unlock(this->lock);
 }
METHOD (proposal_keywords_t , register_algname_parser , void , private_proposal_keywords_t * this, proposal_algname_parser_t parser)
Definition at line 153 of file proposal_keywords.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->tokens->insert_first(this->parsers, parser);
     this->lock->unlock(this->lock);
 }
METHOD (proposal_keywords_t , destroy , void , private_proposal_keywords_t * this)
Definition at line 161 of file proposal_keywords.c.
References spinlock_t::destroy, free(), lock, proposal_token_t::name, and SUCCESS.
 {
     proposal_token_t *token;
     while (this->tokens->remove_first(this->tokens, (void**)&token) == SUCCESS)
     {
         free(token->name);
         free(token);
     }
     this->tokens->destroy(this->tokens);
     this->parsers->destroy(this->parsers);
     this->lock->destroy(this->lock);
     free(this);
 }
static const proposal_token_t* parse_token (private_proposal_keywords_t * this, const char * str) static
Parse the given algorithm into a token with user defined parser functions.
Definition at line 96 of file proposal_keywords.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, lock, parser, and spinlock_t::unlock.
Referenced by METHOD().
 {
     proposal_algname_parser_t parser;
     enumerator_t *enumerator;
     proposal_token_t *found = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->parsers->create_enumerator(this->parsers);
     while (enumerator->enumerate(enumerator, &parser))
     {
         found = parser(str);
         if (found)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }