strongSwan: pgp_utils
pgp_utils
pgp
Typedefs
typedef enum pgp_pubkey_alg_t pgp_pubkey_alg_t
typedef enum pgp_sym_alg_t pgp_sym_alg_t
typedef enum pgp_packet_tag_t pgp_packet_tag_t
Enumerations
enum pgp_pubkey_alg_t {
PGP_PUBKEY_ALG_RSA = 1, PGP_PUBKEY_ALG_RSA_ENC_ONLY = 2, PGP_PUBKEY_ALG_RSA_SIGN_ONLY = 3, PGP_PUBKEY_ALG_ELGAMAL_ENC_ONLY = 16,
PGP_PUBKEY_ALG_DSA = 17, PGP_PUBKEY_ALG_ECC = 18, PGP_PUBKEY_ALG_ECDSA = 19, PGP_PUBKEY_ALG_ELGAMAL = 20,
PGP_PUBKEY_ALG_DIFFIE_HELLMAN = 21
}
enum pgp_sym_alg_t {
PGP_SYM_ALG_PLAIN = 0, PGP_SYM_ALG_IDEA = 1, PGP_SYM_ALG_3DES = 2, PGP_SYM_ALG_CAST5 = 3,
PGP_SYM_ALG_BLOWFISH = 4, PGP_SYM_ALG_SAFER = 5, PGP_SYM_ALG_DES = 6, PGP_SYM_ALG_AES_128 = 7,
PGP_SYM_ALG_AES_192 = 8, PGP_SYM_ALG_AES_256 = 9, PGP_SYM_ALG_TWOFISH = 10
}
enum pgp_packet_tag_t {
PGP_PKT_RESERVED = 0, PGP_PKT_PUBKEY_ENC_SESSION_KEY = 1, PGP_PKT_SIGNATURE = 2, PGP_PKT_SYMKEY_ENC_SESSION_KEY = 3,
PGP_PKT_ONE_PASS_SIGNATURE_PKT = 4, PGP_PKT_SECRET_KEY = 5, PGP_PKT_PUBLIC_KEY = 6, PGP_PKT_SECRET_SUBKEY = 7,
PGP_PKT_COMPRESSED_DATA = 8, PGP_PKT_SYMKEY_ENC_DATA = 9, PGP_PKT_MARKER = 10, PGP_PKT_LITERAL_DATA = 11,
PGP_PKT_TRUST = 12, PGP_PKT_USER_ID = 13, PGP_PKT_PUBLIC_SUBKEY = 14, PGP_PKT_USER_ATTRIBUTE = 17,
PGP_PKT_SYM_ENC_INT_PROT_DATA = 18, PGP_PKT_MOD_DETECT_CODE = 19
}
Functions
bool pgp_read_mpi (chunk_t *blob, chunk_t *mpi)
bool pgp_read_scalar (chunk_t *blob, size_t bytes, u_int32_t *scalar)
bool pgp_read_packet (chunk_t *blob, chunk_t *data, pgp_packet_tag_t *tag)
Variables
enum_name_t * pgp_pubkey_alg_names
enum_name_t * pgp_sym_alg_names
enum_name_t * pgp_packet_tag_names
Detailed Description
Typedef Documentation
typedef enum pgp_packet_tag_t pgp_packet_tag_t
Definition at line 28 of file pgp_utils.h.
typedef enum pgp_pubkey_alg_t pgp_pubkey_alg_t
Definition at line 26 of file pgp_utils.h.
typedef enum pgp_sym_alg_t pgp_sym_alg_t
Definition at line 27 of file pgp_utils.h.
Enumeration Type Documentation
enum pgp_packet_tag_t
OpenPGP packet tags as defined in section 4.3 of RFC 4880
Enumerator
PGP_PKT_RESERVED
PGP_PKT_PUBKEY_ENC_SESSION_KEY
PGP_PKT_SIGNATURE
PGP_PKT_SYMKEY_ENC_SESSION_KEY
PGP_PKT_ONE_PASS_SIGNATURE_PKT
PGP_PKT_SECRET_KEY
PGP_PKT_PUBLIC_KEY
PGP_PKT_SECRET_SUBKEY
PGP_PKT_COMPRESSED_DATA
PGP_PKT_SYMKEY_ENC_DATA
PGP_PKT_MARKER
PGP_PKT_LITERAL_DATA
PGP_PKT_TRUST
PGP_PKT_USER_ID
PGP_PKT_PUBLIC_SUBKEY
PGP_PKT_USER_ATTRIBUTE
PGP_PKT_SYM_ENC_INT_PROT_DATA
PGP_PKT_MOD_DETECT_CODE
Definition at line 75 of file pgp_utils.h.
                       {
     PGP_PKT_RESERVED               =  0,
     PGP_PKT_PUBKEY_ENC_SESSION_KEY =  1,
     PGP_PKT_SIGNATURE              =  2,
     PGP_PKT_SYMKEY_ENC_SESSION_KEY =  3,
     PGP_PKT_ONE_PASS_SIGNATURE_PKT =  4,
     PGP_PKT_SECRET_KEY             =  5,
     PGP_PKT_PUBLIC_KEY             =  6,
     PGP_PKT_SECRET_SUBKEY          =  7,
     PGP_PKT_COMPRESSED_DATA        =  8,
     PGP_PKT_SYMKEY_ENC_DATA        =  9,
     PGP_PKT_MARKER                 = 10,
     PGP_PKT_LITERAL_DATA           = 11,
     PGP_PKT_TRUST                  = 12,
     PGP_PKT_USER_ID                = 13,
     PGP_PKT_PUBLIC_SUBKEY          = 14,
     PGP_PKT_USER_ATTRIBUTE         = 17,
     PGP_PKT_SYM_ENC_INT_PROT_DATA  = 18,
     PGP_PKT_MOD_DETECT_CODE        = 19
 };
enum pgp_pubkey_alg_t
OpenPGP public key algorithms as defined in section 9.1 of RFC 4880
Enumerator
PGP_PUBKEY_ALG_RSA
PGP_PUBKEY_ALG_RSA_ENC_ONLY
PGP_PUBKEY_ALG_RSA_SIGN_ONLY
PGP_PUBKEY_ALG_ELGAMAL_ENC_ONLY
PGP_PUBKEY_ALG_DSA
PGP_PUBKEY_ALG_ECC
PGP_PUBKEY_ALG_ECDSA
PGP_PUBKEY_ALG_ELGAMAL
PGP_PUBKEY_ALG_DIFFIE_HELLMAN
Definition at line 33 of file pgp_utils.h.
                       {
     PGP_PUBKEY_ALG_RSA              =  1,
     PGP_PUBKEY_ALG_RSA_ENC_ONLY     =  2,
     PGP_PUBKEY_ALG_RSA_SIGN_ONLY    =  3,
     PGP_PUBKEY_ALG_ELGAMAL_ENC_ONLY = 16,
     PGP_PUBKEY_ALG_DSA              = 17,
     PGP_PUBKEY_ALG_ECC              = 18,
     PGP_PUBKEY_ALG_ECDSA            = 19,
     PGP_PUBKEY_ALG_ELGAMAL          = 20,
     PGP_PUBKEY_ALG_DIFFIE_HELLMAN   = 21,
 };
enum pgp_sym_alg_t
OpenPGP symmetric key algorithms as defined in section 9.2 of RFC 4880
Enumerator
PGP_SYM_ALG_PLAIN
PGP_SYM_ALG_IDEA
PGP_SYM_ALG_3DES
PGP_SYM_ALG_CAST5
PGP_SYM_ALG_BLOWFISH
PGP_SYM_ALG_SAFER
PGP_SYM_ALG_DES
PGP_SYM_ALG_AES_128
PGP_SYM_ALG_AES_192
PGP_SYM_ALG_AES_256
PGP_SYM_ALG_TWOFISH
Definition at line 53 of file pgp_utils.h.
                    {
     PGP_SYM_ALG_PLAIN    =  0,
     PGP_SYM_ALG_IDEA     =  1,
     PGP_SYM_ALG_3DES     =  2,
     PGP_SYM_ALG_CAST5    =  3,
     PGP_SYM_ALG_BLOWFISH =  4,
     PGP_SYM_ALG_SAFER    =  5,
     PGP_SYM_ALG_DES      =  6,
     PGP_SYM_ALG_AES_128  =  7,
     PGP_SYM_ALG_AES_192  =  8,
     PGP_SYM_ALG_AES_256  =  9,
     PGP_SYM_ALG_TWOFISH  = 10
 };
Function Documentation
bool pgp_read_mpi (chunk_t * blob, chunk_t * mpi)
Parse a PGP encoded MPI.
Parameters
blob blob to read from, gets advanced
mpi parsed MPI value
Returns
TRUE if MPI parsed successfully
Read a PGP MPI, advance blob
Definition at line 97 of file pgp_utils.c.
References bits, bytes, chunk_create(), chunk_skip(), DBG1, DBG_ASN, FALSE, chunk_t::len, pgp_read_scalar(), chunk_t::ptr, and TRUE.
Referenced by parse_rsa_private_key(), and parse_rsa_public_key().
 {
     u_int32_t bits, bytes;
     if (!pgp_read_scalar(blob, 2, &bits))
     {
         DBG1(DBG_ASN, "PGP data too short to read MPI length");
         return FALSE;
     }
     bytes = (bits + 7) / 8;
     if (bytes > blob->len)
     {
         DBG1(DBG_ASN, "PGP data too short to read %d byte MPI", bytes);
         return FALSE;
     }
     *mpi = chunk_create(blob->ptr, bytes);
     *blob = chunk_skip(*blob, bytes);
     return TRUE;
 }
bool pgp_read_packet (chunk_t * blob, chunk_t * data, pgp_packet_tag_t * tag)
Parse a PGP packet.
Parameters
blob blob to read from, gets advanced
data contained packet data
tag tag of the parsed PGP packet
Returns
TRUE if packet parsed successfully
See header.
Definition at line 142 of file pgp_utils.c.
References chunk_create(), chunk_skip(), DBG1, DBG2, DBG3, DBG_ASN, FALSE, chunk_t::len, len, pgp_old_packet_length(), pgp_packet_tag_names, chunk_t::ptr, and TRUE.
Referenced by parse_private_key(), and pgp_cert_load().
 {
     u_int32_t len;
     u_char t;
     if (!blob->len)
     {
         DBG1(DBG_ASN, "missing input");
         return FALSE;
     }
     t = blob->ptr[0];
     /* bit 7 must be set */
     if (!(t & 0x80))
     {
         DBG1(DBG_ASN, "invalid packet tag");
         return FALSE;
     }
     /* bit 6 set defines new packet format */
     if (t & 0x40)
     {
         DBG1(DBG_ASN, "new PGP packet format not supported");
         return FALSE;
     }
     t = (t & 0x3C) >> 2;
     if (!pgp_old_packet_length(blob, &len) || len > blob->len)
     {
         DBG1(DBG_ASN, "invalid packet length");
         return FALSE;
     }
     *data = chunk_create(blob->ptr, len);
     *blob = chunk_skip(*blob, len);
     *tag = t;
     DBG2(DBG_ASN, "L1 - PGP %N (%u bytes)", pgp_packet_tag_names, t, len);
     DBG3(DBG_ASN, "%B", data);
     return TRUE;
 }
bool pgp_read_scalar (chunk_t * blob, size_t bytes, u_int32_t * scalar)
Parse a PGP encoded Scalar.
Parameters
blob blob to read from, gets advanced
bytes number of bytes the scalar uses for encoding
scalar resultin scalar
Returns
TRUE if scalar parsed successfully
Read a PGP scalar of bytes length, advance blob
Definition at line 76 of file pgp_utils.c.
References chunk_skip(), DBG1, DBG_ASN, FALSE, chunk_t::len, chunk_t::ptr, res, and TRUE.
Referenced by parse_private_key(), parse_public_key(), parse_rsa_private_key(), parse_signature(), pgp_old_packet_length(), and pgp_read_mpi().
 {
     u_int32_t res = 0;
     if (bytes > blob->len)
     {
         DBG1(DBG_ASN, "PGP data too short to read %d byte scalar", bytes);
         return FALSE;
     }
     while (bytes-- > 0)
     {
         res = 256 * res + blob->ptr[0];
         *blob = chunk_skip(*blob, 1);
     }
     *scalar = res;
     return TRUE;
 }
Variable Documentation
enum_name_t* pgp_packet_tag_names
Enum names of pgp_packet_tag_t
Referenced by pgp_cert_load(), and pgp_read_packet().
enum_name_t* pgp_pubkey_alg_names
Enum names of pgp_pubkey_alg_t
Referenced by parse_public_key().
enum_name_t* pgp_sym_alg_names
Enum names of pgp_sym_alg_t
Referenced by parse_rsa_private_key().