strongSwan: diffie hellman
diffie hellman
tkm
Classes
struct tkm_diffie_hellman_t
Typedefs
typedef struct tkm_diffie_hellman_t tkm_diffie_hellman_t
Functions
int register_dh_mapping ()
void destroy_dh_mapping ()
tkm_diffie_hellman_t * tkm_diffie_hellman_create (diffie_hellman_group_t group)
Detailed Description
Typedef Documentation
typedef struct tkm_diffie_hellman_t tkm_diffie_hellman_t
Definition at line 25 of file tkm_diffie_hellman.h.
Function Documentation
void destroy_dh_mapping ()
Destroy IANA DH group identifier to TKM id mapping.
Definition at line 179 of file tkm_diffie_hellman.c.
References hashtable_t::create_enumerator, enumerator_t::destroy, hashtable_t::destroy, enumerator_t::enumerate, free(), key, and value.
Referenced by main(), and test_runner_init().
 {
     enumerator_t *enumerator;
     char *key, *value;
     if (group_map)
     {
         enumerator = group_map->create_enumerator(group_map);
         while (enumerator->enumerate(enumerator, &key, &value))
         {
             free(key);
             free(value);
         }
         enumerator->destroy(enumerator);
         group_map->destroy(group_map);
     }
 }
int register_dh_mapping ()
Loads IANA DH group identifier to TKM id mapping from config and registers the corresponding DH features.
Returns
number of registered mappings
Definition at line 121 of file tkm_diffie_hellman.c.
References plugin_loader_t::add_static_features, count, countof, hashtable_t::create_enumerator, settings_t::create_key_value_enumerator, enumerator_t::destroy, hashtable_t::destroy, enumerator_t::enumerate, equals(), hashtable_t::get_count, hash(), hashtable_create(), lib, malloc_thing, library_t::ns, PLUGIN_PROVIDE, PLUGIN_REGISTER, library_t::plugins, hashtable_t::put, library_t::settings, settings_value_as_int(), tkm_diffie_hellman_create(), and TRUE.
Referenced by main(), and test_runner_init().
 {
     int count, i;
     char *iana_id_str, *tkm_id_str;
     diffie_hellman_group_t *iana_id;
     u_int64_t *tkm_id;
     hashtable_t *map;
     enumerator_t *enumerator;
     map = hashtable_create((hashtable_hash_t)hash,
                            (hashtable_equals_t)equals, 16);
     enumerator = lib->settings->create_key_value_enumerator(lib->settings,
                                                             "%s.dh_mapping",
                                                             lib->ns);
     while (enumerator->enumerate(enumerator, &iana_id_str, &tkm_id_str))
     {
         iana_id = malloc_thing(diffie_hellman_group_t);
         *iana_id = settings_value_as_int(iana_id_str, 0);
         tkm_id = malloc_thing(u_int64_t);
         *tkm_id = settings_value_as_int(tkm_id_str, 0);
         map->put(map, iana_id, tkm_id);
     }
     enumerator->destroy(enumerator);
     count = map->get_count(map);
     plugin_feature_t f[count + 1];
     f[0] = PLUGIN_REGISTER(DH, tkm_diffie_hellman_create);
     i = 1;
     enumerator = map->create_enumerator(map);
     while (enumerator->enumerate(enumerator, &iana_id, &tkm_id))
     {
         f[i] = PLUGIN_PROVIDE(DH, *iana_id);
         i++;
     }
     enumerator->destroy(enumerator);
     lib->plugins->add_static_features(lib->plugins, "tkm-dh", f, countof(f),
                                       TRUE, NULL, NULL);
     if (count > 0)
     {
         group_map = map;
     }
     else
     {
         map->destroy(map);
     }
     return count;
 }
tkm_diffie_hellman_t* tkm_diffie_hellman_create (diffie_hellman_group_t group)
Creates a new tkm_diffie_hellman_t object.
Parameters
group Diffie Hellman group number to use
Returns
tkm_diffie_hellman_t object, NULL if not supported
Definition at line 200 of file tkm_diffie_hellman.c.
References tkm_id_manager_t::acquire_id, free(), hashtable_t::get, group, tkm_t::idmgr, INIT, tkm, and TKM_CTX_DH.
Referenced by register_dh_mapping(), and START_TEST().
 {
     private_tkm_diffie_hellman_t *this;
     if (!group_map)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .dh = {
                 .get_shared_secret = _get_shared_secret,
                 .set_other_public_value = _set_other_public_value,
                 .get_my_public_value = _get_my_public_value,
                 .get_dh_group = _get_dh_group,
                 .destroy = _destroy,
             },
             .get_id = _get_id,
         },
         .group = group,
         .context_id = tkm->idmgr->acquire_id(tkm->idmgr, TKM_CTX_DH),
     );
     if (!this->context_id)
     {
         free(this);
         return NULL;
     }
     u_int64_t *dha_id = group_map->get(group_map, &group);
     if (!dha_id)
     {
         free(this);
         return NULL;
     }
     if (ike_dh_create(this->context_id, *dha_id, &this->pubvalue) != TKM_OK)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }