strongSwan: imc_agent
imc_agent
imc
Classes
struct imc_agent_t
Typedefs
typedef struct imc_agent_t imc_agent_t
Functions
imc_agent_t * imc_agent_create (const char *name, pen_type_t *supported_types, u_int32_t type_count, TNC_IMCID id, TNC_Version *actual_version)
Detailed Description
Typedef Documentation
typedef struct imc_agent_t imc_agent_t
Definition at line 34 of file imc_agent.h.
Function Documentation
imc_agent_t* imc_agent_create (const char * name, pen_type_t * supported_types, u_int32_t type_count, TNC_IMCID id, TNC_Version * actual_version)
Create an imc_agent_t object
Parameters
name name of the IMC
supported_types list of message types registered by the IMC
type_count number of registered message types
id ID of the IMC as assigned by the TNCS
actual_version actual version of the IF-IMC API
Described in header.
Definition at line 552 of file imc_agent.c.
References DBG1, DBG_IMC, FALSE, id, INIT, libimcv_init(), linked_list_create(), name, rwlock_create(), RWLOCK_TYPE_DEFAULT, and TNC_IFIMC_VERSION_1.
Referenced by TNC_IMC_Initialize().
 {
     private_imc_agent_t *this;
     /* initialize  or increase the reference count */
     if (!libimcv_init(FALSE))
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .bind_functions = _bind_functions,
             .create_state = _create_state,
             .delete_state = _delete_state,
             .change_state = _change_state,
             .get_state = _get_state,
             .get_name = _get_name,
             .get_id = _get_id,
             .reserve_additional_ids = _reserve_additional_ids,
             .count_additional_ids = _count_additional_ids,
             .create_id_enumerator = _create_id_enumerator,
             .add_non_fatal_attr_type = _add_non_fatal_attr_type,
             .get_non_fatal_attr_types = _get_non_fatal_attr_types,
             .destroy = _destroy,
         },
         .name = name,
         .supported_types = supported_types,
         .type_count = type_count,
         .id = id,
         .additional_ids = linked_list_create(),
         .non_fatal_attr_types = linked_list_create(),
         .connections = linked_list_create(),
         .connection_lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     *actual_version = TNC_IFIMC_VERSION_1;
     DBG1(DBG_IMC, "IMC %u \"%s\" initialized", this->id, this->name);
     return &this->public;
 }