strongSwan: test_rng.c File Reference
test_rng.c File Reference
#include "test_rng.h"
Classes
struct private_rng_t
Typedefs
typedef struct private_rng_t private_rng_t
Functions
METHOD (rng_t, get_bytes, bool, private_rng_t *this, size_t bytes, u_int8_t *buffer)
METHOD (rng_t, allocate_bytes, bool, private_rng_t *this, size_t bytes, chunk_t *chunk)
METHOD (rng_t, destroy, void, private_rng_t *this)
rng_t * test_rng_create (chunk_t entropy)
Typedef Documentation
typedef struct private_rng_t private_rng_t
Definition at line 18 of file test_rng.c.
Function Documentation
METHOD (rng_t , get_bytes , bool , private_rng_t * this, size_t bytes, u_int8_t * buffer)
Definition at line 36 of file test_rng.c.
References chunk_skip(), FALSE, memcpy, and TRUE.
 {
     if (bytes > this->entropy.len)
     {
         return FALSE;
     }
     memcpy(buffer, this->entropy.ptr, bytes);
     this->entropy = chunk_skip(this->entropy, bytes);
     return TRUE;
 }
METHOD (rng_t , allocate_bytes , bool , private_rng_t * this, size_t bytes, chunk_t * chunk)
Definition at line 48 of file test_rng.c.
References chunk_alloc, chunk_empty, chunk_skip(), FALSE, memcpy, chunk_t::ptr, and TRUE.
 {
     if (bytes > this->entropy.len)
     {
         *chunk = chunk_empty;
         return FALSE;
     }
     *chunk = chunk_alloc(bytes);
     memcpy(chunk->ptr, this->entropy.ptr, bytes);
     this->entropy = chunk_skip(this->entropy, bytes);
     return TRUE;
 }
METHOD (rng_t , destroy , void , private_rng_t * this)
Definition at line 63 of file test_rng.c.
References free().
 {
     free(this);
 }