strongSwan: simaka_message_t Struct Reference
simaka_message_t Struct Reference
simaka_message
#include "simaka_message.h"
Public Attributes
bool(* is_request)(simaka_message_t *this)
u_int8_t(* get_identifier)(simaka_message_t *this)
eap_type_t(* get_type)(simaka_message_t *this)
simaka_subtype_t(* get_subtype)(simaka_message_t *this)
enumerator_t *(* create_attribute_enumerator)(simaka_message_t *this)
void(* add_attribute)(simaka_message_t *this, simaka_attribute_t type, chunk_t data)
bool(* parse)(simaka_message_t *this)
bool(* verify)(simaka_message_t *this, chunk_t sigdata)
bool(* generate)(simaka_message_t *this, chunk_t sigdata, chunk_t *gen)
void(* destroy)(simaka_message_t *this)
Detailed Description
EAP-SIM and EAP-AKA message abstraction.
Messages for EAP-SIM and EAP-AKA share a common format, this class abstracts such a message and provides encoding/encryption/signing functionality.
Definition at line 165 of file simaka_message.h.
Member Data Documentation
void(* simaka_message_t::add_attribute)(simaka_message_t *this, simaka_attribute_t type, chunk_t data)
Append an attribute to the EAP-SIM message.
Make sure to pass only data of correct length for the given attribute.
Parameters
type type of attribute to add to message
data unpadded attribute data to add
Definition at line 210 of file simaka_message.h.
Referenced by challenge(), create_client_error(), identity(), METHOD(), process_challenge(), process_identity(), process_reauthentication(), process_start(), and reauthenticate().
enumerator_t*(* simaka_message_t::create_attribute_enumerator)(simaka_message_t *this)
Create an enumerator over message attributes.
Returns
enumerator over (simaka_attribute_t, chunk_t)
Definition at line 200 of file simaka_message.h.
Referenced by process_challenge(), process_client_error(), process_identity(), process_notification(), process_reauthentication(), process_start(), and process_synchronize().
void(* simaka_message_t::destroy)(simaka_message_t *this)
Destroy a simaka_message_t.
Definition at line 247 of file simaka_message.h.
Referenced by generate_payload(), METHOD(), and process_reauthentication().
bool(* simaka_message_t::generate)(simaka_message_t *this, chunk_t sigdata, chunk_t *gen)
Generate a message, optionally encrypt attributes and create a MAC.
Parameters
sigdata additional data to include in signature, if any
gen allocated generated data, if successful
Returns
TRUE if successful
Definition at line 242 of file simaka_message.h.
Referenced by generate_payload().
u_int8_t(* simaka_message_t::get_identifier)(simaka_message_t *this)
Get the EAP message identifier.
Returns
EAP message identifier
Definition at line 179 of file simaka_message.h.
Referenced by process_challenge(), and process_reauthentication().
simaka_subtype_t(* simaka_message_t::get_subtype)(simaka_message_t *this)
Get the subtype of an EAP-SIM message.
Returns
subtype of message
Definition at line 193 of file simaka_message.h.
Referenced by METHOD(), and process_authentication_reject().
eap_type_t(* simaka_message_t::get_type)(simaka_message_t *this)
Get the EAP type of the message.
Returns
EAP type: EAP-SIM or EAP-AKA
Definition at line 186 of file simaka_message.h.
bool(* simaka_message_t::is_request)(simaka_message_t *this)
Check if the given message is a request or response.
Returns
TRUE if request, FALSE if response
Definition at line 172 of file simaka_message.h.
bool(* simaka_message_t::parse)(simaka_message_t *this)
Parse a message, with optional attribute decryption.
This method does not verify message integrity, as the key is available only after the payload has been parsed. It might be necessary to call parse twice, as key derivation data in EAP-SIM/AKA is in the same packet as encrypted data.
Parameters
crypto EAP-SIM/AKA crypto helper
Returns
TRUE if message parsed successfully
Definition at line 224 of file simaka_message.h.
Referenced by METHOD(), process_challenge(), and process_reauthentication().
bool(* simaka_message_t::verify)(simaka_message_t *this, chunk_t sigdata)
Verify the message integrity of a parsed message.
Parameters
crypto EAP-SIM/AKA crypto helper
sigdata additional data to include in signature, if any
Returns
TRUE if message integrity check successful
Definition at line 233 of file simaka_message.h.
Referenced by process_challenge(), and process_reauthentication().
The documentation for this struct was generated from the following file:
simaka_message.h