strongSwan: eap_manager_t Struct Reference
eap_manager_t Struct Reference
eap_manager
#include "eap_manager.h"
Public Attributes
void(* add_method)(eap_manager_t *this, eap_type_t type, u_int32_t vendor, eap_role_t role, eap_constructor_t constructor)
void(* remove_method)(eap_manager_t *this, eap_constructor_t constructor)
enumerator_t *(* create_enumerator)(eap_manager_t *this, eap_role_t role)
eap_method_t *(* create_instance)(eap_manager_t *this, eap_type_t type, u_int32_t vendor, eap_role_t role, identification_t *server, identification_t *peer)
void(* destroy)(eap_manager_t *this)
Detailed Description
The EAP manager manages all EAP implementations and creates instances.
A plugin registers it's implemented EAP method at the manager by providing type and a contructor function. The manager then instanciates eap_method_t instances through the provided constructor to handle EAP authentication.
Definition at line 37 of file eap_manager.h.
Member Data Documentation
void(* eap_manager_t::add_method)(eap_manager_t *this, eap_type_t type, u_int32_t vendor, eap_role_t role, eap_constructor_t constructor)
Register a EAP method implementation.
Parameters
method vendor specific method, if vendor != 0
vendor vendor ID, 0 for non-vendor (default) EAP methods
role EAP role of the registered method
constructor constructor function, returns an eap_method_t
Definition at line 47 of file eap_manager.h.
Referenced by eap_method_register().
enumerator_t*(* eap_manager_t::create_enumerator)(eap_manager_t *this, eap_role_t role)
Enumerate the registered EAP authentication methods for the given role.
Note
Only authentication types are enumerated (e.g. EAP-Identity is not even though it is registered as method with this manager).
Parameters
role EAP role of methods to enumerate
Returns
enumerator over (eap_type_t type, u_int32_t vendor)
Definition at line 66 of file eap_manager.h.
Referenced by eap_payload_create_nak(), and get_supported_eap_types().
eap_method_t*(* eap_manager_t::create_instance)(eap_manager_t *this, eap_type_t type, u_int32_t vendor, eap_role_t role, identification_t *server, identification_t *peer)
Create a new EAP method instance.
Parameters
type type of the EAP method
vendor vendor ID, 0 for non-vendor (default) EAP methods
role role of EAP method, either EAP_SERVER or EAP_PEER
server identity of the server
peer identity of the peer (client)
Returns
EAP method instance, NULL if no constructor found
Definition at line 78 of file eap_manager.h.
Referenced by load_method(), METHOD(), process_eap(), start_phase2_auth(), start_phase2_tnc(), and verify_eap().
void(* eap_manager_t::destroy)(eap_manager_t *this)
Destroy a eap_manager instance.
Definition at line 86 of file eap_manager.h.
void(* eap_manager_t::remove_method)(eap_manager_t *this, eap_constructor_t constructor)
Unregister a EAP method implementation using it's constructor.
Parameters
constructor constructor function to remove, as added in add_method
Definition at line 55 of file eap_manager.h.
Referenced by eap_method_register().
The documentation for this struct was generated from the following file:
eap_manager.h