strongSwan: nm_backend.c File Reference
nm_backend.c File Reference
#include "nm_service.h"
#include "nm_creds.h"
#include "nm_handler.h"
#include <daemon.h>
#include <processing/jobs/callback_job.h>
Classes
struct nm_backend_t
Typedefs
typedef struct nm_backend_t nm_backend_t
Functions
static job_requeue_t run (nm_backend_t *this)
static bool cancel (nm_backend_t *this)
static void nm_backend_deinit ()
static bool nm_backend_init ()
static bool nm_backend_cb (void *plugin, plugin_feature_t *feature, bool reg, void *data)
void nm_backend_register ()
Variables
static nm_backend_t * nm_backend = NULL
Typedef Documentation
typedef struct nm_backend_t nm_backend_t
Definition at line 24 of file nm_backend.c.
Function Documentation
static bool cancel (nm_backend_t * this) static
Cancel the GLib Main Event Loop
Definition at line 70 of file nm_backend.c.
References TRUE.
Referenced by callback_job_create_with_prio(), METHOD(), nm_backend_init(), tcg_seg_attr_next_seg_create(), thread_cancelability(), and thread_cb().
 {
     if (this->loop)
     {
         if (g_main_loop_is_running(this->loop))
         {
             g_main_loop_quit(this->loop);
         }
         g_main_loop_unref(this->loop);
     }
     return TRUE;
 }
static bool nm_backend_cb (void * plugin, plugin_feature_t * feature, bool reg, void * data) static
Initialize/deinitialize NetworkManager backend
Definition at line 151 of file nm_backend.c.
References nm_backend_deinit(), nm_backend_init(), and TRUE.
Referenced by nm_backend_register().
 {
     if (reg)
     {
         return nm_backend_init();
     }
     nm_backend_deinit();
     return TRUE;
 }
static void nm_backend_deinit () static
Deinitialize NetworkManager backend
Definition at line 86 of file nm_backend.c.
References daemon_t::attributes, charon, library_t::credmgr, creds, mem_cred_t::destroy, free(), lib, nm_backend, plugin, attribute_manager_t::remove_handler, and credential_manager_t::remove_set.
Referenced by nm_backend_cb(), and nm_backend_init().
 {
     nm_backend_t *this = nm_backend;
     if (!this)
     {
         return;
     }
     if (this->plugin)
     {
         g_object_unref(this->plugin);
     }
     lib->credmgr->remove_set(lib->credmgr, &this->creds->set);
     charon->attributes->remove_handler(charon->attributes,
                                        &this->handler->handler);
     this->creds->destroy(this->creds);
     this->handler->destroy(this->handler);
     free(this);
     nm_backend = NULL;
 }
static bool nm_backend_init () static
Initialize NetworkManager backend
Definition at line 111 of file nm_backend.c.
References attribute_manager_t::add_handler, credential_manager_t::add_set, daemon_t::attributes, callback_job_create_with_prio(), cancel(), charon, library_t::credmgr, creds, DBG1, DBG_CFG, FALSE, INIT, JOB_PRIO_CRITICAL, lib, nm_backend_deinit(), nm_creds_create(), nm_handler_create(), nm_strongswan_plugin_new(), plugin, library_t::processor, processor_t::queue_job, run(), and TRUE.
Referenced by nm_backend_cb().
 {
     nm_backend_t *this;
 #if !GLIB_CHECK_VERSION(2,36,0)
     g_type_init ();
 #endif
 #if !GLIB_CHECK_VERSION(2,23,0)
     if (!g_thread_supported())
     {
         g_thread_init(NULL);
     }
 #endif
     INIT(this,
         .creds = nm_creds_create(),
         .handler = nm_handler_create(),
     );
     this->plugin = nm_strongswan_plugin_new(this->creds, this->handler);
     nm_backend = this;
     charon->attributes->add_handler(charon->attributes, &this->handler->handler);
     lib->credmgr->add_set(lib->credmgr, &this->creds->set);
     if (!this->plugin)
     {
         DBG1(DBG_CFG, "DBUS binding failed");
         nm_backend_deinit();
         return FALSE;
     }
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create_with_prio((callback_job_cb_t)run, this,
                 NULL, (callback_job_cancel_t)cancel, JOB_PRIO_CRITICAL));
     return TRUE;
 }
static job_requeue_t run (nm_backend_t * this) static
NM plugin processing routine, creates and handles NMVPNPlugin
Definition at line 60 of file nm_backend.c.
References FALSE, and JOB_REQUEUE_NONE.
Referenced by nm_backend_init().
 {
     this->loop = g_main_loop_new(NULL, FALSE);
     g_main_loop_run(this->loop);
     return JOB_REQUEUE_NONE;
 }
Variable Documentation
nm_backend_t* nm_backend = NULL static
Global (but private) instance of the NM backend.
Definition at line 55 of file nm_backend.c.
Referenced by nm_backend_deinit().