strongSwan: tcg_seg_attr_max_size
tcg_seg_attr_max_size
tcg_attr
Classes
struct tcg_seg_attr_max_size_t
Macros
#define TCG_SEG_ATTR_MAX_SIZE_SIZE 8
Typedefs
typedef struct
tcg_seg_attr_max_size_t tcg_seg_attr_max_size_t
Functions
pa_tnc_attr_t * tcg_seg_attr_max_size_create (uint32_t max_attr_size, uint32_t max_seg_size, bool request)
pa_tnc_attr_t * tcg_seg_attr_max_size_create_from_data (size_t length, chunk_t value, bool request)
Detailed Description
Macro Definition Documentation
#define TCG_SEG_ATTR_MAX_SIZE_SIZE 8
Definition at line 28 of file tcg_seg_attr_max_size.h.
Referenced by METHOD().
Typedef Documentation
typedef struct tcg_seg_attr_max_size_t tcg_seg_attr_max_size_t
Definition at line 24 of file tcg_seg_attr_max_size.h.
Function Documentation
pa_tnc_attr_t* tcg_seg_attr_max_size_create (uint32_t max_attr_size, uint32_t max_seg_size, bool request)
Creates an tcg_seg_attr_max_size_t object
Parameters
max_attr_size Maximum IF-M attribute size in octets
max_seg_size Maximum IF-M attribute segment size in octets
request TRUE for a request, FALSE for a response
Described in header.
Definition at line 191 of file tcg_seg_attr_max_size.c.
References INIT, max_seg_size, PEN_TCG, TCG_SEG_MAX_ATTR_SIZE_REQ, and TCG_SEG_MAX_ATTR_SIZE_RESP.
Referenced by METHOD(), and TNC_IMC_BeginHandshake().
 {
     private_tcg_seg_attr_max_size_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_attr_size = _get_attr_size,
         },
         .type = { PEN_TCG, request ? TCG_SEG_MAX_ATTR_SIZE_REQ :
                                      TCG_SEG_MAX_ATTR_SIZE_RESP },
         .max_attr_size = max_attr_size,
         .max_seg_size = max_seg_size,
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* tcg_seg_attr_max_size_create_from_data (size_t length, chunk_t data, bool request)
Creates an tcg_seg_attr_max_size_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
request TRUE for a request, FALSE for a response
Described in header.
Definition at line 225 of file tcg_seg_attr_max_size.c.
References chunk_clone, INIT, length, PEN_TCG, TCG_SEG_MAX_ATTR_SIZE_REQ, and TCG_SEG_MAX_ATTR_SIZE_RESP.
Referenced by tcg_attr_create_from_data().
 {
     private_tcg_seg_attr_max_size_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_attr_size = _get_attr_size,
         },
         .type = { PEN_TCG, request ? TCG_SEG_MAX_ATTR_SIZE_REQ :
                                      TCG_SEG_MAX_ATTR_SIZE_RESP },
         .length = length,
         .value = chunk_clone(data),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }