strongSwan: linked_list
linked_list
collections
Classes
struct linked_list_t
Typedefs
typedef struct linked_list_t linked_list_t
typedef bool(* linked_list_match_t)(void *item,...)
typedef void(* linked_list_invoke_t)(void *item,...)
Functions
linked_list_t * linked_list_create (void)
linked_list_t * linked_list_create_from_enumerator (enumerator_t *enumerator)
linked_list_t * linked_list_create_with_items (void *first,...)
Detailed Description
Typedef Documentation
typedef void(* linked_list_invoke_t)(void *item,...)
Method to be invoked on elements in a linked list (used in invoke_* functions)
Parameters
item current list item
... user supplied data (only pointers, at most 5)
Definition at line 47 of file linked_list.h.
typedef bool(* linked_list_match_t)(void *item,...)
Method to match elements in a linked list (used in find_* functions)
Parameters
item current list item
... user supplied data (only pointers, at most 5)
Returns
TRUE, if the item matched
FALSE, otherwise
Definition at line 39 of file linked_list.h.
typedef struct linked_list_t linked_list_t
Definition at line 26 of file linked_list.h.
Function Documentation
linked_list_t* linked_list_create (void)
Creates an empty linked list object.
Returns
linked_list_t object.
Definition at line 484 of file linked_list.c.
References ike_sa_id_t::destroy, INIT, and remove_first().
Referenced by acert(), add_interface(), add_local_certs(), android_dns_handler_create(), attr_provider_create(), attribute_manager_create(), authority_create(), backend_manager_create(), blocking_queue_create(), bridge_create(), bridge_each(), bridge_each_iface(), build_reply(), build_request(), bus_create(), ca_section_create(), CALLBACK(), check_list_create(), check_policy_constraints(), child_cfg_create(), child_delete_create(), cleanup_sessions(), cmd_connection_create(), config_create(), connect_manager_create(), cowfs_create(), cp_payload_create_type(), create_cert(), create_cert_ext(), create_empty(), create_enumerator(), create_plugin(), create_unique_cert_list(), cred_encoding_create(), credential_factory_create(), credential_manager_create(), crypto_factory_create(), crypto_tester_create(), daemon_create(), database_factory_create(), dhcp_socket_create(), dhcp_transaction_create(), dumm_create(), duplicheck_notify_create(), eap_dynamic_create(), eap_manager_create(), eap_radius_dae_create(), eap_radius_plugin_create(), eap_sim_file_triplets_create(), encrypted_payload_create(), entry_create(), error_notify_socket_create(), farp_listener_create(), fast_dispatcher_create(), fast_session_create(), fetcher_manager_create(), find_certificates(), forecast_listener_create(), get_dynamic_hosts(), get_identity_attribute(), get_matching_ike_sas(), get_or_create_entry(), get_port_list(), get_route(), get_transport_nat_ts(), guest_create_generic(), guest_each_iface(), ha_attribute_create(), handle_event(), handle_preferred_eap_types(), host_resolver_create(), ietf_attr_attr_request_create(), ietf_attr_attr_request_create_from_data(), ietf_attr_installed_packages_create(), ietf_attr_installed_packages_create_from_data(), ietf_attr_port_filter_create(), ietf_attr_port_filter_create_from_data(), iface_each_addr(), ike_auth_create(), ike_cfg_create(), ike_config_create(), ike_me_create(), imc_agent_create(), imc_attestation_state_create(), imc_msg_create(), imc_test_state_create(), imv_agent_create(), imv_attestation_state_create(), imv_msg_create(), imv_os_state_create(), imv_scanner_state_create(), imv_session_create(), imv_session_manager_create(), imv_test_state_create(), init_address_list(), initiated_create(), ipsec_event_relay_create(), ipsec_policy_mgr_create(), ipsec_sa_mgr_create(), issue(), ita_attr_get_settings_create(), ita_attr_get_settings_create_from_data(), ita_attr_settings_create(), ita_attr_settings_create_from_data(), kernel_interface_create(), kernel_iph_net_create(), kernel_libipsec_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), keymat_v1_create(), linked_list_create_from_enumerator(), linked_list_create_with_items(), list(), list_authorities(), list_conns(), list_pools(), load(), load_proposals(), load_shared(), load_tester_config_create(), load_tester_creds_create(), lookip_listener_create(), lookip_socket_create(), lookup_queue(), main(), mediation_manager_create(), mem_cred_create(), message_create_from_packet(), METHOD(), mode_config_create(), mysql_database_create(), narrow_ts(), nm_creds_create(), nm_handler_create(), order_payloads(), pa_tnc_attr_manager_create(), pa_tnc_msg_create(), pa_tnc_msg_create_from_data(), parse_directoryName(), parse_selector(), parse_subnets(), pb_tnc_batch_create(), pb_tnc_batch_create_from_data(), peer_cfg_create(), peer_create(), phase1_create(), pkcs11_creds_create(), pkcs11_manager_create(), pkcs11_plugin_create(), pkcs7_attributes_create(), plugin_loader_create(), print_all(), process_child_add(), process_link(), processor_create(), proposal_keywords_create(), proposal_substructure_create(), pts_component_manager_create(), pts_file_meas_create(), pts_file_meta_create(), pts_ima_bios_list_create(), pts_ima_event_list_create(), put(), put_connected_peers(), radius_config_create(), register_features(), rekey_children(), rekey_segment(), req(), reset_certs(), reset_secrets(), sa_payload_create(), sa_payload_create_from_proposal_v1(), seg_contract_create(), seg_contract_manager_create(), self(), sender_create(), shunt_manager_create(), sign_crl(), simaka_manager_create(), simaka_message_create_data(), socket_manager_create(), START_SETUP(), START_TEST(), stream_manager_create(), stroke_attribute_create(), stroke_ca_create(), stroke_config_create(), stroke_handler_create(), swid_inventory_create(), task_manager_v1_create(), tcg_pts_attr_req_func_comp_evid_create(), tcg_pts_attr_req_func_comp_evid_create_from_data(), thread_create_internal(), tkm_kernel_sad_create(), tls_alert_create(), tls_cache_create(), tnc_imc_create_empty(), tnc_imc_manager_create(), tnc_imv_create_empty(), tnc_imv_manager_create(), tnc_imv_recommendations_create(), tnc_pdp_connections_create(), tnc_pdp_create(), tnc_tnccs_manager_create(), tnccs_20_client_create(), tnccs_20_server_create(), tnccs_batch_create(), tnccs_batch_create_from_data(), transform_substructure_create(), trap_manager_create(), ts_payload_create(), unbound_response_create_frm_libub_response(), unity_handler_create(), update_addrs(), update_children(), updown_handler_create(), updown_listener_create(), vici_authority_create(), vici_config_create(), vici_logger_create(), vici_message_create_from_data(), vici_socket_create(), vici_submit(), watcher_create(), winhttp_fetcher_create(), wrap_payloads(), x509_parse_crlDistributionPoints(), and xauth_manager_create().
 {
     private_linked_list_t *this;
     INIT(this,
         .public = {
             .get_count = _get_count,
             .create_enumerator = _create_enumerator,
             .reset_enumerator = (void*)_reset_enumerator,
             .get_first = _get_first,
             .get_last = _get_last,
             .find_first = (void*)_find_first,
             .insert_first = _insert_first,
             .insert_last = _insert_last,
             .insert_before = (void*)_insert_before,
             .remove_first = _remove_first,
             .remove_last = _remove_last,
             .remove = _remove_,
             .remove_at = (void*)_remove_at,
             .invoke_offset = (void*)_invoke_offset,
             .invoke_function = (void*)_invoke_function,
             .clone_offset = _clone_offset,
             .destroy = _destroy,
             .destroy_offset = _destroy_offset,
             .destroy_function = _destroy_function,
         },
     );
     return &this->public;
 }
linked_list_t* linked_list_create_from_enumerator (enumerator_t * enumerator)
Creates a linked list from an enumerator.
Parameters
enumerator enumerator over void*, gets destroyed
Returns
linked_list_t object, containing enumerated values
Definition at line 518 of file linked_list.c.
References enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, linked_list_create(), and list.
Referenced by build_reply(), build_set(), delete_child(), install(), log_child_sa(), log_children(), METHOD(), plugin_filter(), select_and_install(), START_TEST(), status(), and write_childend().
 {
     linked_list_t *list;
     void *item;
     list = linked_list_create();
     while (enumerator->enumerate(enumerator, &item))
     {
         list->insert_last(list, item);
     }
     enumerator->destroy(enumerator);
     return list;
 }
linked_list_t* linked_list_create_with_items (void * first, ...)
Creates a linked list from a NULL terminated vararg list of items.
Parameters
first first item
... subsequent items, terminated by NULL
Returns
linked_list_t object, containing passed items
Definition at line 537 of file linked_list.c.
References linked_list_t::insert_last, linked_list_create(), and list.
Referenced by build_set(), get_proxy_addr(), install(), install_shunt_policy(), METHOD(), START_SETUP(), START_TEST(), and uninstall_shunt_policy().
 {
     linked_list_t *list;
     va_list args;
     list = linked_list_create();
     va_start(args, item);
     while (item)
     {
         list->insert_last(list, item);
         item = va_arg(args, void*);
     }
     va_end(args);
     return list;
 }