strongSwan: fast_dispatcher.c File Reference
fast_dispatcher.c File Reference
#include "fast_dispatcher.h"
#include "fast_request.h"
#include "fast_session.h"
#include <fcgiapp.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <utils/debug.h>
#include <threading/thread.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include <collections/hashtable.h>
Classes
struct private_fast_dispatcher_t
struct controller_entry_t
struct filter_entry_t
struct session_entry_t
Macros
#define CLEANUP_INTERVAL 30
Typedefs
typedef struct
private_fast_dispatcher_t private_fast_dispatcher_t
Functions
static fast_session_t * load_session (private_fast_dispatcher_t *this)
static session_entry_t * session_entry_create (private_fast_dispatcher_t *this, char *host)
static void session_entry_destroy (session_entry_t *entry)
METHOD (fast_dispatcher_t, add_controller, void, private_fast_dispatcher_t *this, fast_controller_constructor_t constructor, void *param)
METHOD (fast_dispatcher_t, add_filter, void, private_fast_dispatcher_t *this, fast_filter_constructor_t constructor, void *param)
static u_int session_hash (char *sid)
static bool session_equals (char *sid1, char *sid2)
static void cleanup_sessions (private_fast_dispatcher_t *this, time_t now)
static void dispatch (private_fast_dispatcher_t *this)
METHOD (fast_dispatcher_t, run, void, private_fast_dispatcher_t *this, int threads)
METHOD (fast_dispatcher_t, waitsignal, void, private_fast_dispatcher_t *this)
METHOD (fast_dispatcher_t, destroy, void, private_fast_dispatcher_t *this)
fast_dispatcher_t * fast_dispatcher_create (char *socket, bool debug, int timeout, fast_context_constructor_t constructor, void *param)
Macro Definition Documentation
#define CLEANUP_INTERVAL 30
Intervall to check for expired sessions, in seconds
Definition at line 34 of file fast_dispatcher.c.
Referenced by cleanup_sessions().
Typedef Documentation
typedef struct private_fast_dispatcher_t private_fast_dispatcher_t
Definition at line 36 of file fast_dispatcher.c.
Function Documentation
static void cleanup_sessions (private_fast_dispatcher_t * this, time_t now) static
Cleanup unused sessions
Definition at line 259 of file fast_dispatcher.c.
References CLEANUP_INTERVAL, session_entry_t::closed, enumerator_t::destroy, enumerator_t::enumerate, session_entry_t::in_use, linked_list_create(), session_entry_destroy(), SUCCESS, and session_entry_t::used.
Referenced by dispatch().
 {
     if (this->last_cleanup < now - CLEANUP_INTERVAL)
     {
         char *sid;
         session_entry_t *entry;
         enumerator_t *enumerator;
         linked_list_t *remove;
         this->last_cleanup = now;
         remove = linked_list_create();
         enumerator = this->sessions->create_enumerator(this->sessions);
         while (enumerator->enumerate(enumerator, &sid, &entry))
         {
             /* check all sessions for timeout or close flag */
             if (!entry->in_use &&
                 (entry->used < now - this->timeout || entry->closed))
             {
                 remove->insert_last(remove, sid);
             }
         }
         enumerator->destroy(enumerator);
         while (remove->remove_last(remove, (void**)&sid) == SUCCESS)
         {
             entry = this->sessions->remove(this->sessions, sid);
             if (entry)
             {
                 session_entry_destroy(entry);
             }
         }
         remove->destroy(remove);
     }
 }
static void dispatch (private_fast_dispatcher_t * this) static
Actual dispatching code
Definition at line 297 of file fast_dispatcher.c.
References cleanup_sessions(), session_entry_t::closed, session_entry_t::cond, fast_request_t::destroy, FALSE, fast_request_create(), found, fast_request_t::get_cookie, fast_request_t::get_host, fast_session_t::get_sid, session_entry_t::host, session_entry_t::in_use, mutex_t::lock, mutex, fast_session_t::process, request(), session_entry_t::session, fast_request_t::session_closed, session_entry_create(), condvar_t::signal, streq(), thread_cancelability(), time_monotonic(), TRUE, mutex_t::unlock, session_entry_t::used, and condvar_t::wait.
Referenced by METHOD().
 {
     thread_cancelability(FALSE);
     while (TRUE)
     {
         fast_request_t *request;
         session_entry_t *found = NULL;
         time_t now;
         char *sid;
         thread_cancelability(TRUE);
         request = fast_request_create(this->fd, this->debug);
         thread_cancelability(FALSE);
         if (request == NULL)
         {
             break;
         }
         now = time_monotonic(NULL);
         sid = request->get_cookie(request, "SID");
         this->mutex->lock(this->mutex);
         if (sid)
         {
             found = this->sessions->get(this->sessions, sid);
         }
         if (found && !streq(found->host, request->get_host(request)))
         {
             found = NULL;
         }
         if (found)
         {
             /* wait until session is unused */
             while (found->in_use)
             {
                 found->cond->wait(found->cond, this->mutex);
             }
         }
         else
         {   /* create a new session if not found */
             found = session_entry_create(this, request->get_host(request));
             if (!found)
             {
                 request->destroy(request);
                 this->mutex->unlock(this->mutex);
                 continue;
             }
             sid = found->session->get_sid(found->session);
             this->sessions->put(this->sessions, sid, found);
         }
         found->in_use = TRUE;
         this->mutex->unlock(this->mutex);
         /* start processing */
         found->session->process(found->session, request);
         found->used = time_monotonic(NULL);
         /* release session */
         this->mutex->lock(this->mutex);
         found->in_use = FALSE;
         found->closed = request->session_closed(request);
         found->cond->signal(found->cond);
         cleanup_sessions(this, now);
         this->mutex->unlock(this->mutex);
         request->destroy(request);
     }
 }
static fast_session_t* load_session (private_fast_dispatcher_t * this) static
create a session and instanciate controllers
Definition at line 141 of file fast_dispatcher.c.
References fast_session_t::add_controller, fast_session_t::add_filter, controller_entry_t::constructor, filter_entry_t::constructor, context, enumerator_t::destroy, enumerator_t::enumerate, fast_session_create(), filter(), controller_entry_t::param, and filter_entry_t::param.
Referenced by session_entry_create().
 {
     enumerator_t *enumerator;
     controller_entry_t *centry;
     filter_entry_t *fentry;
     fast_session_t *session;
     fast_context_t *context = NULL;
     fast_controller_t *controller;
     fast_filter_t *filter;
     if (this->context_constructor)
     {
         context = this->context_constructor(this->param);
     }
     session = fast_session_create(context);
     if (!session)
     {
         return NULL;
     }
     enumerator = this->controllers->create_enumerator(this->controllers);
     while (enumerator->enumerate(enumerator, &centry))
     {
         controller = centry->constructor(context, centry->param);
         session->add_controller(session, controller);
     }
     enumerator->destroy(enumerator);
     enumerator = this->filters->create_enumerator(this->filters);
     while (enumerator->enumerate(enumerator, &fentry))
     {
         filter = fentry->constructor(context, fentry->param);
         session->add_filter(session, filter);
     }
     enumerator->destroy(enumerator);
     return session;
 }
METHOD (fast_dispatcher_t , add_controller , void , private_fast_dispatcher_t * this, fast_controller_constructor_t constructor, void * param)
Definition at line 214 of file fast_dispatcher.c.
References INIT.
 {
     controller_entry_t *entry;
     INIT(entry,
         .constructor = constructor,
         .param = param,
     );
     this->controllers->insert_last(this->controllers, entry);
 }
METHOD (fast_dispatcher_t , add_filter , void , private_fast_dispatcher_t * this, fast_filter_constructor_t constructor, void * param)
Definition at line 227 of file fast_dispatcher.c.
References INIT.
 {
     filter_entry_t *entry;
     INIT(entry,
         .constructor = constructor,
         .param = param,
     );
     this->filters->insert_last(this->filters, entry);
 }
METHOD (fast_dispatcher_t , run , void , private_fast_dispatcher_t * this, int threads)
Definition at line 367 of file fast_dispatcher.c.
References dispatch(), malloc(), thread_create, and threads.
 {
     this->thread_count = threads;
     this->threads = malloc(sizeof(thread_t*) * threads);
     while (threads)
     {
         this->threads[threads - 1] = thread_create((thread_main_t)dispatch,
                                                    this);
         if (this->threads[threads - 1])
         {
             threads--;
         }
     }
 }
METHOD (fast_dispatcher_t , waitsignal , void , private_fast_dispatcher_t * this)
Definition at line 383 of file fast_dispatcher.c.
References sigwaitinfo().
 {
     sigset_t set;
     sigemptyset(&set);
     sigaddset(&set, SIGINT);
     sigaddset(&set, SIGTERM);
     sigaddset(&set, SIGHUP);
     sigprocmask(SIG_BLOCK, &set, NULL);
     while (sigwaitinfo(&set, NULL) == -1 && errno == EINTR)
     {
         /* wait for signal */
     }
 }
METHOD (fast_dispatcher_t , destroy , void , private_fast_dispatcher_t * this)
Definition at line 399 of file fast_dispatcher.c.
References thread_t::cancel, enumerator_t::destroy, mutex_t::destroy, enumerator_t::enumerate, free(), thread_t::join, mutex, session_entry_destroy(), and threads.
 {
     char *sid;
     session_entry_t *entry;
     enumerator_t *enumerator;
     FCGX_ShutdownPending();
     while (this->thread_count--)
     {
         thread_t *thread = this->threads[this->thread_count];
         thread->cancel(thread);
         thread->join(thread);
     }
     enumerator = this->sessions->create_enumerator(this->sessions);
     while (enumerator->enumerate(enumerator, &sid, &entry))
     {
         session_entry_destroy(entry);
     }
     enumerator->destroy(enumerator);
     this->sessions->destroy(this->sessions);
     this->controllers->destroy_function(this->controllers, free);
     this->filters->destroy_function(this->filters, free);
     this->mutex->destroy(this->mutex);
     free(this->threads);
     free(this);
 }
static session_entry_t* session_entry_create (private_fast_dispatcher_t * this, char * host) static
create a new session entry
Definition at line 183 of file fast_dispatcher.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, INIT, load_session(), strdup, and time_monotonic().
Referenced by dispatch().
 {
     session_entry_t *entry;
     fast_session_t *session;
     session = load_session(this);
     if (!session)
     {
         return NULL;
     }
     INIT(entry,
         .cond = condvar_create(CONDVAR_TYPE_DEFAULT),
         .session = session,
         .host = strdup(host),
         .used = time_monotonic(NULL),
     );
     return entry;
 }
static void session_entry_destroy (session_entry_t * entry) static
destroy a session
Definition at line 206 of file fast_dispatcher.c.
References session_entry_t::cond, fast_session_t::destroy, condvar_t::destroy, free(), session_entry_t::host, and session_entry_t::session.
Referenced by cleanup_sessions(), and METHOD().
 {
     entry->session->destroy(entry->session);
     entry->cond->destroy(entry->cond);
     free(entry->host);
     free(entry);
 }
static bool session_equals (char * sid1, char * sid2) static
Hashtable equals function
Definition at line 251 of file fast_dispatcher.c.
References streq().
Referenced by fast_dispatcher_create().
 {
     return streq(sid1, sid2);
 }
static u_int session_hash (char * sid) static
Hashtable hash function
Definition at line 243 of file fast_dispatcher.c.
References chunk_create(), and chunk_hash().
Referenced by fast_dispatcher_create().
 {
     return chunk_hash(chunk_create(sid, strlen(sid)));
 }