strongSwan: checksum_builder.c File Reference
checksum_builder.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <dlfcn.h>
#include <library.h>
#include <hydra.h>
#include <daemon.h>
#include <collections/enumerator.h>
Macros
#define _GNU_SOURCE
Functions
static void build_checksum (char *path, char *name, char *sname)
static void build_plugin_checksums (char *plugins)
static void build_binary_checksum (char *path)
int main (int argc, char *argv[])
Variables
integrity_checker_t * integrity
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file checksum_builder.c.
Function Documentation
static void build_binary_checksum (char * path) static
Build checksums for a binary/library found at path
Definition at line 95 of file checksum_builder.c.
References build_checksum(), name, snprintf, and streq().
Referenced by main().
 {
     char *binary, *pos, name[128], sname[128];
     binary = strrchr(path, '/');
     if (binary)
     {
         binary++;
         pos = strrchr(binary, '.');
         if (pos && streq(pos, ".so"))
         {
             snprintf(name, sizeof(name), "%.*s\",", (int)(pos - binary),
                      binary);
             if (streq(name, "libstrongswan\","))
             {
                 snprintf(sname, sizeof(sname), "%s", "library_init");
             }
             else
             {
                 snprintf(sname, sizeof(sname), "%.*s_init", (int)(pos - binary),
                          binary);
             }
             build_checksum(path, name, sname);
         }
         else
         {
             snprintf(name, sizeof(name), "%s\",", binary);
             build_checksum(path, name, NULL);
         }
     }
 }
static void build_checksum (char * path, char * name, char * sname) static
Create the checksum of a binary, using name and a symbol name
Definition at line 34 of file checksum_builder.c.
References integrity_checker_t::build_file, integrity_checker_t::build_segment, dlclose(), dlerror(), dlopen(), dlsym(), fprintf, handle, printf, and RTLD_LAZY.
Referenced by build_binary_checksum(), and build_plugin_checksums().
 {
     void *handle, *symbol;
     u_int32_t fsum, ssum;
     size_t fsize = 0;
     size_t ssize = 0;
     fsum = integrity->build_file(integrity, path, &fsize);
     ssum = 0;
     if (sname)
     {
         handle = dlopen(path, RTLD_LAZY);
         if (handle)
         {
             symbol = dlsym(handle, sname);
             if (symbol)
             {
                 ssum = integrity->build_segment(integrity, symbol, &ssize);
             }
             else
             {
                 fprintf(stderr, "symbol lookup failed: %s\n", dlerror());
             }
             dlclose(handle);
         }
         else
         {
             fprintf(stderr, "dlopen failed: %s\n", dlerror());
         }
     }
     printf("\t{\"%-25s%7u, 0x%08x, %6u, 0x%08x},\n",
            name, fsize, fsum, ssize, ssum);
     fprintf(stderr, "\"%-25s%7u / 0x%08x       %6u / 0x%08x\n",
             name, fsize, fsum, ssize, ssum);
 }
static void build_plugin_checksums (char * plugins) static
Build checksums for a set of plugins
Definition at line 73 of file checksum_builder.c.
References build_checksum(), enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), name, path, plugin, snprintf, and translate().
Referenced by main().
 {
     enumerator_t *enumerator;
     char *plugin, path[256], under[128], sname[128], name[128];
     enumerator = enumerator_create_token(plugins, " ", " ");
     while (enumerator->enumerate(enumerator, &plugin))
     {
         snprintf(under, sizeof(under), "%s", plugin);
         translate(under, "-", "_");
         snprintf(path, sizeof(path), "%s/libstrongswan-%s.so",
                  PLUGINDIR, plugin);
         snprintf(sname, sizeof(sname), "%s_plugin_create", under);
         snprintf(name, sizeof(name), "%s\",", plugin);
         build_checksum(path, name, sname);
     }
     enumerator->destroy(enumerator);
 }
int main (int argc, char * argv[])
Definition at line 127 of file checksum_builder.c.
References argc, build_binary_checksum(), build_plugin_checksums(), charon, integrity_checker_t::destroy, fprintf, hydra, integrity_checker_create(), library_deinit(), library_init(), printf, and setenv().
 {
     int i;
     /* forces link against libhydra/libcharon, imports symbols needed to
      * dlopen plugins */
     hydra = NULL;
     charon = NULL;
     /* avoid confusing leak reports in build process */
     setenv("LEAK_DETECTIVE_DISABLE", "1", 0);
     /* don't use a strongswan.conf, forces integrity check to disabled */
     library_init("", "checksum_builder");
     atexit(library_deinit);
     integrity = integrity_checker_create(NULL);
     printf("/**\n");
     printf(" * checksums of files and loaded code segments.\n");
     printf(" * created by %s\n", argv[0]);
     printf(" */\n");
     printf("\n");
     printf("#include <library.h>\n");
     printf("\n");
     printf("integrity_checksum_t checksums[] = {\n");
     fprintf(stderr, "integrity test data:\n");
     fprintf(stderr, "module name,            file size / checksum   "
                     "segment size / checksum\n");
     for (i = 1; i < argc; i++)
     {
         build_binary_checksum(argv[i]);
     }
 #ifdef S_PLUGINS
     build_plugin_checksums(S_PLUGINS);
 #endif
 #ifdef H_PLUGINS
     build_plugin_checksums(H_PLUGINS);
 #endif
 #ifdef T_PLUGINS
     build_plugin_checksums(T_PLUGINS);
 #endif
 #ifdef C_PLUGINS
     build_plugin_checksums(C_PLUGINS);
 #endif
     printf("};\n");
     printf("\n");
     printf("int checksum_count = countof(checksums);\n");
     printf("\n");
     integrity->destroy(integrity);
     exit(0);
 }
Variable Documentation
integrity_checker_t* integrity
Integrity checker
Definition at line 29 of file checksum_builder.c.
Referenced by library_deinit(), list_algs(), and proposal_add_supported_ike().