strongSwan: bliss_signature.c File Reference
bliss_signature.c File Reference
#include "bliss_signature.h"
#include "bliss_bitpacker.h"
#include "bliss_huffman_coder.h"
Classes
struct private_bliss_signature_t
Typedefs
typedef struct
private_bliss_signature_t private_bliss_signature_t
Functions
METHOD (bliss_signature_t, get_encoding, chunk_t, private_bliss_signature_t *this)
METHOD (bliss_signature_t, get_parameters, void, private_bliss_signature_t *this, int32_t **z1, int16_t **z2d, uint16_t **c_indices)
METHOD (bliss_signature_t, destroy, void, private_bliss_signature_t *this)
bliss_signature_t * bliss_signature_create (bliss_param_set_t *set)
bliss_signature_t * bliss_signature_create_from_data (bliss_param_set_t *set, chunk_t encoding)
Typedef Documentation
typedef struct private_bliss_signature_t private_bliss_signature_t
Definition at line 21 of file bliss_signature.c.
Function Documentation
METHOD (bliss_signature_t , get_encoding , chunk_t , private_bliss_signature_t * this)
Definition at line 54 of file bliss_signature.c.
References bliss_bitpacker_create(), bliss_huffman_code_get_by_id(), bliss_huffman_coder_create(), bliss_param_set_id_names, chunk_empty, code, DBG1, DBG2, DBG_LIB, bliss_huffman_coder_t::destroy, bliss_bitpacker_t::destroy, bliss_huffman_coder_t::encode, encoding, end, bliss_bitpacker_t::extract_buf, bliss_bitpacker_t::get_bits, bliss_huffman_coder_t::get_bits, chunk_t::len, and bliss_bitpacker_t::write_bits.
 {
     bliss_bitpacker_t *packer;
     bliss_huffman_coder_t *coder;
     bliss_huffman_code_t *code;
     int32_t z1;
     uint32_t z1_sign;
     uint16_t z2d_bits;
     chunk_t encoding = chunk_empty;
     int i;
     z2d_bits = this->set->z1_bits - this->set->d;
     /* Get Huffman code for this BLISS parameter set */
     code = bliss_huffman_code_get_by_id(this->set->id);
     if (!code)
     {
         DBG1(DBG_LIB, "no Huffman code found for parameter set %N",
              bliss_param_set_id_names, this->set->id);
         return chunk_empty;
     }
     packer = bliss_bitpacker_create(this->set->n * this->set->z1_bits +
                                     this->set->n * z2d_bits +
                                     this->set->kappa * this->set->n_bits);
     coder = bliss_huffman_coder_create(code, packer);
     for (i = 0; i < this->set->n; i++)
     {
         /* determine and remove the sign of z1[i]*/
         z1_sign = this->z1[i] < 0;
         z1 = z1_sign ? -this->z1[i] : this->z1[i];
         if (!packer->write_bits(packer, z1_sign, 1) ||
             !packer->write_bits(packer, z1 & 0xff, 8) ||
             !coder->encode(coder, z1 >> 8, this->z2d[i]))
         {
             goto end;
         }
     }
     for (i = 0; i < this->set->kappa; i++)
     {
         if (!packer->write_bits(packer, this->c_indices[i], this->set->n_bits))
         {
             goto end;
         }
     }
     encoding = packer->extract_buf(packer);
     DBG2(DBG_LIB, "efficiency of Huffman coder is %6.4f bits/tuple (%u bits)",
                    coder->get_bits(coder)/(double)(this->set->n),
                    coder->get_bits(coder));
     DBG2(DBG_LIB, "generated BLISS signature (%u bits encoded in %u bytes)",
                    packer->get_bits(packer), encoding.len);
     end:
     coder->destroy(coder);
     packer->destroy(packer);
     return encoding;
 }
METHOD (bliss_signature_t , get_parameters , void , private_bliss_signature_t * this, int32_t ** z1, int16_t ** z2d, uint16_t ** c_indices)
Definition at line 116 of file bliss_signature.c.
 {
     *z1 = this->z1;
     *z2d = this->z2d;
     *c_indices = this->c_indices;
 }
METHOD (bliss_signature_t , destroy , void , private_bliss_signature_t * this)
Definition at line 125 of file bliss_signature.c.
References free().
 {
     free(this->z1);
     free(this->z2d);
     free(this->c_indices);
     free(this);
 }