strongSwan: whitelist_control.c File Reference
whitelist_control.c File Reference
#include "whitelist_control.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <errno.h>
#include <daemon.h>
#include <collections/linked_list.h>
#include "whitelist_msg.h"
Classes
struct private_whitelist_control_t
Typedefs
typedef struct
private_whitelist_control_t private_whitelist_control_t
Functions
static void list (private_whitelist_control_t *this, stream_t *stream, identification_t *id)
static bool on_accept (private_whitelist_control_t *this, stream_t *stream)
METHOD (whitelist_control_t, destroy, void, private_whitelist_control_t *this)
whitelist_control_t * whitelist_control_create (whitelist_listener_t *listener)
Typedef Documentation
typedef struct private_whitelist_control_t private_whitelist_control_t
Definition at line 30 of file whitelist_control.c.
Function Documentation
static void list (private_whitelist_control_t * this, stream_t * stream, identification_t * id) static
Definition at line 56 of file whitelist_control.c.
References identification_t::clone, DBG1, DBG_CFG, enumerator_t::destroy, identification_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, whitelist_msg_t::id, linked_list_t::insert_last, linked_list_create(), listener, identification_t::matches, memset, msg, linked_list_t::remove_first, snprintf, strerror, SUCCESS, whitelist_msg_t::type, WHITELIST_END, WHITELIST_LIST, and stream_t::write_all.
Referenced by on_accept().
 {
     identification_t *current;
     enumerator_t *enumerator;
     linked_list_t *list;
     whitelist_msg_t msg = {
         .type = htonl(WHITELIST_LIST),
     };
     list = linked_list_create();
     enumerator = this->listener->create_enumerator(this->listener);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current->matches(current, id))
         {
             list->insert_last(list, current->clone(current));
         }
     }
     enumerator->destroy(enumerator);
     while (list->remove_first(list, (void**)&current) == SUCCESS)
     {
         snprintf(msg.id, sizeof(msg.id), "%Y", current);
         current->destroy(current);
         if (!stream->write_all(stream, &msg, sizeof(msg)))
         {
             DBG1(DBG_CFG, "listing whitelist failed: %s", strerror(errno));
             break;
         }
     }
     list->destroy_offset(list, offsetof(identification_t, destroy));
     msg.type = htonl(WHITELIST_END);
     memset(msg.id, 0, sizeof(msg.id));
     stream->write_all(stream, &msg, sizeof(msg));
 }
METHOD (whitelist_control_t , destroy , void , private_whitelist_control_t * this)
Definition at line 136 of file whitelist_control.c.
References free().
 {
     this->service->destroy(this->service);
     free(this);
 }
static bool on_accept (private_whitelist_control_t * this, stream_t * stream) static
Dispatch a received message
Definition at line 97 of file whitelist_control.c.
References DBG1, DBG_CFG, FALSE, id, whitelist_msg_t::id, identification_create_from_string(), list(), listener, msg, stream_t::read_all, TRUE, whitelist_msg_t::type, WHITELIST_ADD, WHITELIST_DISABLE, WHITELIST_ENABLE, WHITELIST_FLUSH, WHITELIST_LIST, and WHITELIST_REMOVE.
Referenced by whitelist_control_create().
 {
     identification_t *id;
     whitelist_msg_t msg;
     while (stream->read_all(stream, &msg, sizeof(msg)))
     {
         msg.id[sizeof(msg.id) - 1] = 0;
         id = identification_create_from_string(msg.id);
         switch (ntohl(msg.type))
         {
             case WHITELIST_ADD:
                 this->listener->add(this->listener, id);
                 break;
             case WHITELIST_REMOVE:
                 this->listener->remove(this->listener, id);
                 break;
             case WHITELIST_LIST:
                 list(this, stream, id);
                 break;
             case WHITELIST_FLUSH:
                 this->listener->flush(this->listener, id);
                 break;
             case WHITELIST_ENABLE:
                 this->listener->set_active(this->listener, TRUE);
                 break;
             case WHITELIST_DISABLE:
                 this->listener->set_active(this->listener, FALSE);
                 break;
             default:
                 DBG1(DBG_CFG, "received unknown whitelist command");
                 break;
         }
         id->destroy(id);
     }
     return FALSE;
 }