strongSwan: daemon.c File Reference
daemon.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include "daemon.h"
#include <library.h>
#include <bus/listeners/sys_logger.h>
#include <bus/listeners/file_logger.h>
#include <config/proposal.h>
#include <plugins/plugin_feature.h>
#include <kernel/kernel_handler.h>
#include <processing/jobs/start_action_job.h>
#include <threading/mutex.h>
Classes
struct private_daemon_t
struct logger_entry_t
Macros
#define LOG_AUTHPRIV LOG_AUTH
Typedefs
typedef struct private_daemon_t private_daemon_t
Functions
static void dbg_bus (debug_t group, level_t level, char *fmt,...)
static void logger_entry_destroy (logger_entry_t *this)
static void logger_entry_unregister_destroy (logger_entry_t *this)
static bool logger_entry_match (logger_entry_t *this, char *target, bool *file)
static void handle_syslog_identifier (private_daemon_t *this)
static int get_syslog_facility (char *facility)
static logger_entry_t * get_logger_entry (char *target, bool is_file_logger, linked_list_t *existing)
static sys_logger_t * add_sys_logger (private_daemon_t *this, char *facility, linked_list_t *current_loggers)
static file_logger_t * add_file_logger (private_daemon_t *this, char *filename, linked_list_t *current_loggers)
static void load_sys_logger (private_daemon_t *this, char *facility, linked_list_t *current_loggers)
static void load_file_logger (private_daemon_t *this, char *filename, linked_list_t *current_loggers)
METHOD (daemon_t, load_loggers, void, private_daemon_t *this, level_t levels[DBG_MAX], bool to_stderr)
METHOD (daemon_t, set_level, void, private_daemon_t *this, debug_t group, level_t level)
static void destroy (private_daemon_t *this)
static void run_scripts (private_daemon_t *this, char *verb)
METHOD (daemon_t, start, void, private_daemon_t *this)
static bool sender_receiver_cb (void *plugin, plugin_feature_t *feature, bool reg, private_daemon_t *this)
static bool sa_managers_cb (void *plugin, plugin_feature_t *feature, bool reg, private_daemon_t *this)
METHOD (daemon_t, initialize, bool, private_daemon_t *this, char *plugins)
private_daemon_t * daemon_create ()
void libcharon_deinit ()
bool libcharon_init ()
Variables
daemon_t * charon
void(* dbg)(debug_t group, level_t level, char *fmt,...)
static void(* dbg_old)(debug_t group, level_t level, char *fmt,...)
Macro Definition Documentation
#define LOG_AUTHPRIV LOG_AUTH
Definition at line 41 of file daemon.c.
Referenced by get_syslog_facility(), and init_log().
Typedef Documentation
typedef struct private_daemon_t private_daemon_t
Definition at line 44 of file daemon.c.
Function Documentation
static file_logger_t* add_file_logger (private_daemon_t * this, char * filename, linked_list_t * current_loggers) static
Create or reuse a file logger
Definition at line 277 of file daemon.c.
References logger_entry_t::file, get_logger_entry(), logger_entry_t::logger, and TRUE.
Referenced by load_file_logger(), and METHOD().
 {
     logger_entry_t *entry;
     entry = get_logger_entry(filename, TRUE, current_loggers);
     this->loggers->insert_last(this->loggers, entry);
     return entry->logger.file;
 }
static sys_logger_t* add_sys_logger (private_daemon_t * this, char * facility, linked_list_t * current_loggers) static
Create or reuse a syslog logger
Definition at line 264 of file daemon.c.
References FALSE, get_logger_entry(), logger_entry_t::logger, and logger_entry_t::sys.
Referenced by load_sys_logger(), and METHOD().
 {
     logger_entry_t *entry;
     entry = get_logger_entry(facility, FALSE, current_loggers);
     this->loggers->insert_last(this->loggers, entry);
     return entry->logger.sys;
 }
private_daemon_t* daemon_create ()
Create the daemon.
Definition at line 656 of file daemon.c.
References attribute_manager_create(), daemon_t::attributes, backend_manager_create(), bus_create(), controller_create(), eap_manager_create(), INIT, kernel_handler_create(), linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, shunt_manager_create(), socket_manager_create(), trap_manager_create(), and xauth_manager_create().
Referenced by libcharon_init().
 {
     private_daemon_t *this;
     INIT(this,
         .public = {
             .initialize = _initialize,
             .start = _start,
             .load_loggers = _load_loggers,
             .set_level = _set_level,
             .bus = bus_create(),
         },
         .loggers = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .ref = 1,
     );
     charon = &this->public;
     this->public.attributes = attribute_manager_create();
     this->public.controller = controller_create();
     this->public.eap = eap_manager_create();
     this->public.xauth = xauth_manager_create();
     this->public.backends = backend_manager_create();
     this->public.socket = socket_manager_create();
     this->public.traps = trap_manager_create();
     this->public.shunts = shunt_manager_create();
     this->kernel_handler = kernel_handler_create();
     return this;
 }
static void dbg_bus (debug_t group, level_t level, char * fmt, ...) static
Logging hook for library logs, spreads debug message over bus
Definition at line 104 of file daemon.c.
References daemon_t::bus, and bus_t::vlog.
Referenced by libcharon_init().
 {
     va_list args;
     va_start(args, fmt);
     charon->bus->vlog(charon->bus, group, level, fmt, args);
     va_end(args);
 }
static void destroy (private_daemon_t * this) static
Clean up all daemon resources
Definition at line 452 of file daemon.c.
References attributes, processor_t::cancel, CERT_ANY, library_t::credmgr, dbg, dbg_old, mutex_t::destroy, DESTROY_IF, host_resolver_t::flush, scheduler_t::flush, credential_manager_t::flush_cache, free(), library_t::hosts, lib, logger_entry_destroy(), mutex, library_t::plugins, library_t::processor, library_t::scheduler, sender(), processor_t::set_threads, socket, and plugin_loader_t::unload.
Referenced by add_local_certs(), aesni_plugin_create(), af_alg_ops_create(), agent_private_key_open(), array_create_enumerator(), attest_db_create(), attributes_destroy(), auth_cfg_wrapper_create(), authority_destroy(), bliss_private_key_gen(), bliss_private_key_load(), bliss_public_key_load(), bliss_signature_create_from_data(), build_payloads(), build_reply(), ca_section_destroy(), CALLBACK(), check_list_destroy(), clear_fragments(), condvar_create(), connect_manager_create(), coupling_validator_create(), create_cert(), create_empty(), create_generic(), create_rdn_enumerator(), create_rt_enumerator(), create_sets_enumerator(), create_table_enumerator(), cred_encoding_create(), curl_plugin_create(), destroy_address_list(), destroy_entry(), dhcp_socket_create(), dumm_create(), duplicheck_notify_create(), eap_aka_3gpp2_card_create(), eap_aka_3gpp2_provider_create(), eap_radius_dae_create(), eap_radius_forward_create(), eap_radius_xauth_create_server(), eap_sim_file_card_create(), eap_sim_file_triplets_create(), eap_sim_pcsc_card_create(), eap_simaka_pseudonym_provider_create(), eap_simaka_reauth_provider_create(), eap_simaka_sql_card_create(), eap_simaka_sql_provider_create(), encrypted_fragment_payload_create(), endecode_create_enumerator(), endpoint_notify_create_from_payload(), entry_destroy(), enumerator_create_empty(), error_notify_socket_create(), esp_context_create(), exit_scepclient(), farp_plugin_create(), fast_session_create(), forecast_forwarder_create(), forecast_plugin_create(), free_child_data(), free_peer_data(), gcrypt_rsa_private_key_load(), get_proxy_addr(), get_ts_match(), gmp_rsa_private_key_gen(), gmp_rsa_private_key_load(), guest_create(), guest_load(), ha_socket_create(), hashtable_create(), hybrid_authenticator_create(), id_enumerator_cleanup(), iface_destroy(), ike_sa_create(), imv_attestation_agent_create(), imv_database_create(), initiated_destroy(), install(), install_shunt_policy(), ipsec_sa_create(), issue(), kernel_iph_net_create(), kernel_libipsec_plugin_create(), kernel_netlink_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), kernel_wfp_ipsec_create(), libcharon_deinit(), list(), load(), load_shared(), load_tester_plugin_create(), lookip_plugin_create(), lookip_socket_create(), maemo_service_create(), medcli_creds_create(), mem_cred_create(), METHOD(), METHOD2(), mgf1_create(), mysql_database_create(), narrow_ts(), netlink_socket_create(), nonce_nonceg_create(), ntru_drbg_create(), ntru_poly_create_from_seed(), ntru_private_key_create(), ntru_trits_create(), openssl_crl_load(), openssl_diffie_hellman_create(), openssl_ec_diffie_hellman_create(), openssl_ec_private_key_gen(), openssl_ec_private_key_load(), openssl_ec_public_key_load(), openssl_hasher_create(), openssl_plugin_create(), openssl_rsa_private_key_connect(), openssl_rsa_private_key_load(), openssl_rsa_public_key_load(), openssl_x509_load(), parse(), peer_destroy(), pgp_cert_load(), pkcs11_creds_create(), pkcs11_private_key_connect(), pkcs12_create(), pkcs12_decode(), pkcs5_from_algorithmIdentifier(), pkcs7_attributes_create_from_chunk(), pkcs7_encrypted_data_load(), pkcs7_enveloped_data_gen(), pkcs7_enveloped_data_load(), pkcs7_signed_data_gen(), pkcs7_signed_data_load(), prf_plus_create(), process_auth_request(), process_child_add(), process_coa(), process_disconnect(), process_payloads(), proposal_create_default(), proposal_create_default_aead(), proposal_create_from_string(), psk_v1_authenticator_create(), pt_tls_dispatcher_create(), pt_tls_receive_more(), pts_file_meas_create_from_path(), pts_ima_bios_list_create(), pts_ima_event_list_create(), pubkey_v1_authenticator_create(), radius_config_create(), radius_message_parse(), radius_socket_create(), raise_alerts(), raise_policy_cfg(), random_plugin_create(), rdrand_plugin_create(), receiver_create(), req(), reqid_entry_destroy(), request_query_config(), reset_certs(), reset_secrets(), sasl_mechanism_create_enumerator(), seg_env_create_from_data(), select_and_install(), select_child_cfg(), select_ts(), self(), shared_entry_destroy(), signature_schemes_for_key(), simaka_crypto_create(), socket_default_socket_create(), socket_win_socket_create(), sqlite_database_create(), START_TEST(), stroke_ca_create(), stroke_cred_create(), stroke_plugin_create(), stroke_socket_create(), task_manager_v1_create(), tkm_private_key_init(), tls_aead_create_aead(), tls_aead_create_explicit(), tls_aead_create_implicit(), tnc_ifmap_listener_create(), tnc_ifmap_soap_create(), tnc_imc_create(), tnc_imv_create(), tnc_pdp_create(), tnccs_20_client_create(), tnccs_20_server_create(), tnccs_reason_strings_msg_create_from_node(), tnccs_recommendation_msg_create_from_node(), unbound_resolver_create(), unbound_response_create_frm_libub_response(), uninstall_shunt_policy(), verify_list(), vici_dispatcher_create(), vici_plugin_create(), vici_socket_create(), whitelist_plugin_create(), x509_ac_gen(), x509_ac_load(), x509_cert_gen(), x509_cert_load(), x509_crl_gen(), x509_crl_load(), x509_ocsp_request_gen(), x509_pkcs10_gen(), and x509_pkcs10_load().
 {
     /* terminate all idle threads */
     lib->processor->set_threads(lib->processor, 0);
     /* make sure nobody waits for a DNS query */
     lib->hosts->flush(lib->hosts);
     /* close all IKE_SAs */
     if (this->public.ike_sa_manager)
     {
         this->public.ike_sa_manager->flush(this->public.ike_sa_manager);
     }
     if (this->public.traps)
     {
         this->public.traps->flush(this->public.traps);
     }
     if (this->public.shunts)
     {
         this->public.shunts->flush(this->public.shunts);
     }
     if (this->public.sender)
     {
         this->public.sender->flush(this->public.sender);
     }
     /* cancel all threads and wait for their termination */
     lib->processor->cancel(lib->processor);
 #ifdef ME
     DESTROY_IF(this->public.connect_manager);
     DESTROY_IF(this->public.mediation_manager);
 #endif /* ME */
     /* make sure the cache and scheduler are clear before unloading plugins */
     lib->credmgr->flush_cache(lib->credmgr, CERT_ANY);
     lib->scheduler->flush(lib->scheduler);
     lib->plugins->unload(lib->plugins);
     DESTROY_IF(this->public.attributes);
     DESTROY_IF(this->kernel_handler);
     DESTROY_IF(this->public.traps);
     DESTROY_IF(this->public.shunts);
     DESTROY_IF(this->public.controller);
     DESTROY_IF(this->public.eap);
     DESTROY_IF(this->public.xauth);
     DESTROY_IF(this->public.backends);
     DESTROY_IF(this->public.socket);
     /* rehook library logging, shutdown logging */
     dbg = dbg_old;
     DESTROY_IF(this->public.bus);
     this->loggers->destroy_function(this->loggers, (void*)logger_entry_destroy);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static logger_entry_t* get_logger_entry (char * target, bool is_file_logger, linked_list_t * existing) static
Returns an existing or newly created logger entry (if found, it is removed from the given linked list of existing loggers)
Definition at line 231 of file daemon.c.
References logger_entry_t::file, file_logger_create(), linked_list_t::find_first, get_syslog_facility(), INIT, logger_entry_t::logger, logger_entry_match(), linked_list_t::remove, strdup, SUCCESS, logger_entry_t::sys, and sys_logger_create().
Referenced by add_file_logger(), and add_sys_logger().
 {
     logger_entry_t *entry;
     if (existing->find_first(existing, (void*)logger_entry_match,
                             (void**)&entry, target, &is_file_logger) != SUCCESS)
     {
         INIT(entry,
             .target = strdup(target),
             .file = is_file_logger,
         );
         if (is_file_logger)
         {
             entry->logger.file = file_logger_create(target);
         }
 #ifdef HAVE_SYSLOG
         else
         {
             entry->logger.sys = sys_logger_create(get_syslog_facility(target));
         }
 #endif /* HAVE_SYSLOG */
     }
     else
     {
         existing->remove(existing, entry, NULL);
     }
     return entry;
 }
static int get_syslog_facility (char * facility) static
Convert the given string into a syslog facility, returns -1 if the facility is not supported
Definition at line 212 of file daemon.c.
References LOG_AUTHPRIV, and streq().
Referenced by get_logger_entry(), and load_sys_logger().
 {
 #ifdef HAVE_SYSLOG
     if (streq(facility, "daemon"))
     {
         return LOG_DAEMON;
     }
     else if (streq(facility, "auth"))
     {
         return LOG_AUTHPRIV;
     }
 #endif /* HAVE_SYSLOG */
     return -1;
 }
static void handle_syslog_identifier (private_daemon_t * this) static
Handle configured syslog identifier
mutex must be locked when calling this function
Definition at line 183 of file daemon.c.
References settings_t::get_str, identifier, lib, library_t::ns, library_t::settings, and streq().
Referenced by METHOD().
 {
 #ifdef HAVE_SYSLOG
     char *identifier;
     identifier = lib->settings->get_str(lib->settings, "%s.syslog.identifier",
                                         NULL, lib->ns);
     if (identifier)
     {   /* set identifier, which is prepended to each log line */
         if (!this->syslog_identifier ||
             !streq(identifier, this->syslog_identifier))
         {
             closelog();
             this->syslog_identifier = identifier;
             openlog(this->syslog_identifier, 0, 0);
         }
     }
     else if (this->syslog_identifier)
     {
         closelog();
         this->syslog_identifier = NULL;
     }
 #endif /* HAVE_SYSLOG */
 }
static void load_file_logger (private_daemon_t * this, char * filename, linked_list_t * current_loggers) static
Load the given file logger configured in strongswan.conf
Definition at line 321 of file daemon.c.
References add_file_logger(), bus_t::add_logger, daemon_t::bus, DBG_MAX, debug_lower_names, FALSE, settings_t::get_bool, settings_t::get_int, settings_t::get_str, group, lib, file_logger_t::logger, library_t::ns, file_logger_t::open, file_logger_t::set_level, file_logger_t::set_options, library_t::settings, and TRUE.
Referenced by METHOD().
 {
     file_logger_t *file_logger;
     debug_t group;
     level_t def;
     bool add_ms, ike_name, flush_line, append;
     char *time_format;
     time_format = lib->settings->get_str(lib->settings,
                         "%s.filelog.%s.time_format", NULL, lib->ns, filename);
     add_ms = lib->settings->get_bool(lib->settings,
                         "%s.filelog.%s.time_add_ms", FALSE, lib->ns, filename);
     ike_name = lib->settings->get_bool(lib->settings,
                         "%s.filelog.%s.ike_name", FALSE, lib->ns, filename);
     flush_line = lib->settings->get_bool(lib->settings,
                         "%s.filelog.%s.flush_line", FALSE, lib->ns, filename);
     append = lib->settings->get_bool(lib->settings,
                         "%s.filelog.%s.append", TRUE, lib->ns, filename);
     file_logger = add_file_logger(this, filename, current_loggers);
     file_logger->set_options(file_logger, time_format, add_ms, ike_name);
     file_logger->open(file_logger, flush_line, append);
     def = lib->settings->get_int(lib->settings, "%s.filelog.%s.default", 1,
                                  lib->ns, filename);
     for (group = 0; group < DBG_MAX; group++)
     {
         file_logger->set_level(file_logger, group,
                 lib->settings->get_int(lib->settings, "%s.filelog.%s.%N", def,
                             lib->ns, filename, debug_lower_names, group));
     }
     charon->bus->add_logger(charon->bus, &file_logger->logger);
 }
static void load_sys_logger (private_daemon_t * this, char * facility, linked_list_t * current_loggers) static
Load the given syslog logger configured in strongswan.conf
Definition at line 290 of file daemon.c.
References bus_t::add_logger, add_sys_logger(), daemon_t::bus, DBG_MAX, debug_lower_names, FALSE, settings_t::get_bool, settings_t::get_int, get_syslog_facility(), group, lib, sys_logger_t::logger, library_t::ns, sys_logger_t::set_level, sys_logger_t::set_options, and library_t::settings.
Referenced by METHOD().
 {
     sys_logger_t *sys_logger;
     debug_t group;
     level_t def;
     if (get_syslog_facility(facility) == -1)
     {
         return;
     }
     sys_logger = add_sys_logger(this, facility, current_loggers);
     sys_logger->set_options(sys_logger,
                 lib->settings->get_bool(lib->settings, "%s.syslog.%s.ike_name",
                                         FALSE, lib->ns, facility));
     def = lib->settings->get_int(lib->settings, "%s.syslog.%s.default", 1,
                                  lib->ns, facility);
     for (group = 0; group < DBG_MAX; group++)
     {
         sys_logger->set_level(sys_logger, group,
                 lib->settings->get_int(lib->settings, "%s.syslog.%s.%N", def,
                             lib->ns, facility, debug_lower_names, group));
     }
     charon->bus->add_logger(charon->bus, &sys_logger->logger);
 }
static void logger_entry_destroy (logger_entry_t * this) static
Destroy a logger entry
Definition at line 140 of file daemon.c.
References DESTROY_IF, and free().
Referenced by destroy(), and logger_entry_unregister_destroy().
 {
     if (this->file)
     {
         DESTROY_IF(this->logger.file);
     }
     else
     {
         DESTROY_IF(this->logger.sys);
     }
     free(this->target);
     free(this);
 }
static bool logger_entry_match (logger_entry_t * this, char * target, bool * file) static
Match a logger entry by target and whether it is a file or syslog logger
Definition at line 173 of file daemon.c.
References streq().
Referenced by get_logger_entry().
 {
     return this->file == *file && streq(this->target, target);
 }
static void logger_entry_unregister_destroy (logger_entry_t * this) static
Unregister and destroy a logger entry
Definition at line 157 of file daemon.c.
References daemon_t::bus, logger_entry_destroy(), and bus_t::remove_logger.
Referenced by METHOD().
 {
     if (this->file)
     {
         charon->bus->remove_logger(charon->bus, &this->logger.file->logger);
     }
     else
     {
         charon->bus->remove_logger(charon->bus, &this->logger.sys->logger);
     }
     logger_entry_destroy(this);
 }
METHOD (daemon_t , load_loggers , void , private_daemon_t * this, level_t levels[DBG_MAX], bool to_stderr)
Definition at line 356 of file daemon.c.
References add_file_logger(), bus_t::add_logger, add_sys_logger(), daemon_t::bus, settings_t::create_section_enumerator, DBG_ANY, DBG_MAX, enumerator_t::destroy, linked_list_t::destroy_function, enumerator_t::enumerate, FALSE, group, handle_syslog_identifier(), LEVEL_AUDIT, levels, lib, linked_list_create(), load_file_logger(), load_sys_logger(), mutex_t::lock, file_logger_t::logger, sys_logger_t::logger, logger_entry_unregister_destroy(), mutex, library_t::ns, file_logger_t::open, sys_logger_t::set_level, file_logger_t::set_level, library_t::settings, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     linked_list_t *current_loggers;
     char *target;
     this->mutex->lock(this->mutex);
     handle_syslog_identifier(this);
     current_loggers = this->loggers;
     this->loggers = linked_list_create();
     enumerator = lib->settings->create_section_enumerator(lib->settings,
                                                         "%s.syslog", lib->ns);
     while (enumerator->enumerate(enumerator, &target))
     {
         load_sys_logger(this, target, current_loggers);
     }
     enumerator->destroy(enumerator);
     enumerator = lib->settings->create_section_enumerator(lib->settings,
                                                         "%s.filelog", lib->ns);
     while (enumerator->enumerate(enumerator, &target))
     {
         load_file_logger(this, target, current_loggers);
     }
     enumerator->destroy(enumerator);
     if (!this->loggers->get_count(this->loggers) && levels)
     {   /* setup legacy style default loggers configured via command-line */
         file_logger_t *file_logger;
         sys_logger_t *sys_logger;
         debug_t group;
         sys_logger = add_sys_logger(this, "daemon", current_loggers);
         file_logger = add_file_logger(this, "stdout", current_loggers);
         file_logger->open(file_logger, FALSE, FALSE);
         for (group = 0; group < DBG_MAX; group++)
         {
             if (sys_logger)
             {
                 sys_logger->set_level(sys_logger, group, levels[group]);
             }
             if (to_stderr)
             {
                 file_logger->set_level(file_logger, group, levels[group]);
             }
         }
         if (sys_logger)
         {
             charon->bus->add_logger(charon->bus, &sys_logger->logger);
         }
         charon->bus->add_logger(charon->bus, &file_logger->logger);
         sys_logger = add_sys_logger(this, "auth", current_loggers);
         if (sys_logger)
         {
             sys_logger->set_level(sys_logger, DBG_ANY, LEVEL_AUDIT);
             charon->bus->add_logger(charon->bus, &sys_logger->logger);
         }
     }
     /* unregister and destroy any unused remaining loggers */
     current_loggers->destroy_function(current_loggers,
                                      (void*)logger_entry_unregister_destroy);
     this->mutex->unlock(this->mutex);
 }
METHOD (daemon_t , set_level , void , private_daemon_t * this, debug_t group, level_t level)
Definition at line 423 of file daemon.c.
References bus_t::add_logger, daemon_t::bus, enumerator_t::destroy, enumerator_t::enumerate, logger_entry_t::file, mutex_t::lock, sys_logger_t::logger, logger_entry_t::logger, mutex, sys_logger_t::set_level, logger_entry_t::sys, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     logger_entry_t *entry;
     /* we set the loglevel on ALL sys- and file-loggers */
     this->mutex->lock(this->mutex);
     enumerator = this->loggers->create_enumerator(this->loggers);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->file)
         {
             entry->logger.file->set_level(entry->logger.file, group, level);
             charon->bus->add_logger(charon->bus, &entry->logger.file->logger);
         }
         else
         {
             entry->logger.sys->set_level(entry->logger.sys, group, level);
             charon->bus->add_logger(charon->bus, &entry->logger.sys->logger);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (daemon_t , start , void , private_daemon_t * this)
Definition at line 552 of file daemon.c.
References DEFAULT_THREADS, settings_t::get_int, lib, library_t::ns, library_t::processor, run_scripts(), processor_t::set_threads, and library_t::settings.
 {
     /* start the engine, go multithreaded */
     lib->processor->set_threads(lib->processor,
                         lib->settings->get_int(lib->settings, "%s.threads",
                                                DEFAULT_THREADS, lib->ns));
     run_scripts(this, "start");
 }
METHOD (daemon_t , initialize , bool , private_daemon_t * this, char * plugins)
Definition at line 609 of file daemon.c.
References plugin_loader_t::add_static_features, connect_manager_create(), countof, FALSE, features, HASH_SHA1, lib, plugin_loader_t::load, mediation_manager_create(), library_t::ns, PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, library_t::plugins, library_t::processor, processor_t::queue_job, RNG_STRONG, RNG_WEAK, sa_managers_cb(), sender_receiver_cb(), start_action_job_create(), and TRUE.
 {
     plugin_feature_t features[] = {
         PLUGIN_PROVIDE(CUSTOM, "libcharon"),
             PLUGIN_DEPENDS(NONCE_GEN),
             PLUGIN_DEPENDS(CUSTOM, "libcharon-sa-managers"),
             PLUGIN_DEPENDS(CUSTOM, "libcharon-receiver"),
             PLUGIN_DEPENDS(CUSTOM, "kernel-ipsec"),
             PLUGIN_DEPENDS(CUSTOM, "kernel-net"),
         PLUGIN_CALLBACK((plugin_feature_callback_t)sender_receiver_cb, this),
             PLUGIN_PROVIDE(CUSTOM, "libcharon-receiver"),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(RNG, RNG_STRONG),
                 PLUGIN_DEPENDS(CUSTOM, "socket"),
         PLUGIN_CALLBACK((plugin_feature_callback_t)sa_managers_cb, this),
             PLUGIN_PROVIDE(CUSTOM, "libcharon-sa-managers"),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
     };
     lib->plugins->add_static_features(lib->plugins, lib->ns, features,
                                       countof(features), TRUE, NULL, NULL);
     /* load plugins, further infrastructure may need it */
     if (!lib->plugins->load(lib->plugins, plugins))
     {
         return FALSE;
     }
     /* Queue start_action job */
     lib->processor->queue_job(lib->processor, (job_t*)start_action_job_create());
 #ifdef ME
     this->public.connect_manager = connect_manager_create();
     if (this->public.connect_manager == NULL)
     {
         return FALSE;
     }
     this->public.mediation_manager = mediation_manager_create();
 #endif /* ME */
     return TRUE;
 }
static void run_scripts (private_daemon_t * this, char * verb) static
Run a set of configured scripts
Definition at line 508 of file daemon.c.
References cmd, settings_t::create_key_value_enumerator, DBG1, DBG_DMN, enumerator_t::destroy, enumerator_t::enumerate, key, lib, library_t::ns, library_t::settings, strerror, TRUE, and value.
Referenced by libcharon_deinit(), and METHOD().
 {
     enumerator_t *enumerator;
     char *key, *value, *pos, buf[1024];
     FILE *cmd;
     enumerator = lib->settings->create_key_value_enumerator(lib->settings,
                                                 "%s.%s-scripts", lib->ns, verb);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         DBG1(DBG_DMN, "executing %s script '%s' (%s):", verb, key, value);
         cmd = popen(value, "r");
         if (!cmd)
         {
             DBG1(DBG_DMN, "executing %s script '%s' (%s) failed: %s",
                  verb, key, value, strerror(errno));
             continue;
         }
         while (TRUE)
         {
             if (!fgets(buf, sizeof(buf), cmd))
             {
                 if (ferror(cmd))
                 {
                     DBG1(DBG_DMN, "reading from %s script '%s' (%s) failed",
                          verb, key, value);
                 }
                 break;
             }
             else
             {
                 pos = buf + strlen(buf);
                 if (pos > buf && pos[-1] == '\n')
                 {
                     pos[-1] = '\0';
                 }
                 DBG1(DBG_DMN, "%s: %s", key, buf);
             }
         }
         pclose(cmd);
     }
     enumerator->destroy(enumerator);
 }
static bool sa_managers_cb (void * plugin, plugin_feature_t * feature, bool reg, private_daemon_t * this) static
Initialize/deinitialize IKE_SA/CHILD_SA managers
Definition at line 589 of file daemon.c.
References child_sa_manager_create(), DESTROY_IF, FALSE, ike_sa_manager_create(), and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->public.ike_sa_manager = ike_sa_manager_create();
         if (!this->public.ike_sa_manager)
         {
             return FALSE;
         }
         this->public.child_sa_manager = child_sa_manager_create();
     }
     else
     {
         DESTROY_IF(this->public.ike_sa_manager);
         DESTROY_IF(this->public.child_sa_manager);
     }
     return TRUE;
 }
static bool sender_receiver_cb (void * plugin, plugin_feature_t * feature, bool reg, private_daemon_t * this) static
Initialize/deinitialize sender and receiver
Definition at line 566 of file daemon.c.
References DESTROY_IF, FALSE, receiver_create(), sender(), sender_create(), and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->public.receiver = receiver_create();
         if (!this->public.receiver)
         {
             return FALSE;
         }
         this->public.sender = sender_create();
     }
     else
     {
         DESTROY_IF(this->public.receiver);
         DESTROY_IF(this->public.sender);
     }
     return TRUE;
 }
Variable Documentation
void(* dbg)(debug_t group, level_t level, char *fmt,...)
hook in library for debugging messages
The registered debug hook.
Definition at line 111 of file debug.c.
Referenced by destroy(), and libcharon_init().
void(* dbg_old)(debug_t group, level_t level, char *fmt,...) static
we store the previous debug function so we can reset it
Definition at line 99 of file daemon.c.
Referenced by destroy(), and libcharon_init().