strongSwan: generator
generator
encoding
Classes
struct generator_t
Typedefs
typedef struct generator_t generator_t
Functions
generator_t * generator_create (void)
generator_t * generator_create_no_dbg (void)
Detailed Description
Typedef Documentation
typedef struct generator_t generator_t
Definition at line 25 of file generator.h.
Function Documentation
generator_t* generator_create (void)
Constructor to create a generator.
Returns
generator_t object.
Definition at line 582 of file generator.c.
References GENERATOR_DATA_BUFFER_SIZE, INIT, malloc(), and TRUE.
Referenced by generate_message(), generator_create_no_dbg(), METHOD(), and rebuild_auth().
 {
     private_generator_t *this;
     INIT(this,
         .public = {
             .get_chunk = _get_chunk,
             .generate_payload = _generate_payload,
             .destroy = _destroy,
         },
         .buffer = malloc(GENERATOR_DATA_BUFFER_SIZE),
         .debug = TRUE,
     );
     this->out_position = this->buffer;
     this->roof_position = this->buffer + GENERATOR_DATA_BUFFER_SIZE;
     return &this->public;
 }
generator_t* generator_create_no_dbg (void)
Constructor to create a generator that does not log any debug messages > 1.
Returns
generator_t object.
Definition at line 605 of file generator.c.
References FALSE, and generator_create().
Referenced by METHOD().
 {
     private_generator_t *this = (private_generator_t*)generator_create();
     this->debug = FALSE;
     return &this->public;
 }