strongSwan: eap_sim_file_plugin.c File Reference
eap_sim_file_plugin.c File Reference
#include "eap_sim_file_plugin.h"
#include "eap_sim_file_card.h"
#include "eap_sim_file_provider.h"
#include "eap_sim_file_triplets.h"
#include <daemon.h>
Classes
struct private_eap_sim_file_t
Macros
#define TRIPLET_FILE IPSEC_CONFDIR "/ipsec.d/triplets.dat"
Typedefs
typedef struct
private_eap_sim_file_t private_eap_sim_file_t
Functions
METHOD (plugin_t, get_name, char *, private_eap_sim_file_t *this)
static bool load_triplets (private_eap_sim_file_t *this, plugin_feature_t *feature, bool reg, void *data)
static simaka_card_t * get_card (private_eap_sim_file_t *this)
static simaka_provider_t * get_provider (private_eap_sim_file_t *this)
METHOD (plugin_t, get_features, int, private_eap_sim_file_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_eap_sim_file_t *this)
plugin_t * eap_sim_file_plugin_create ()
Macro Definition Documentation
#define TRIPLET_FILE IPSEC_CONFDIR "/ipsec.d/triplets.dat"
Definition at line 23 of file eap_sim_file_plugin.c.
Referenced by load_triplets().
Typedef Documentation
typedef struct private_eap_sim_file_t private_eap_sim_file_t
Definition at line 25 of file eap_sim_file_plugin.c.
Function Documentation
plugin_t* eap_sim_file_plugin_create ()
See header
Definition at line 129 of file eap_sim_file_plugin.c.
References INIT.
 {
     private_eap_sim_file_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
static simaka_card_t* get_card (private_eap_sim_file_t * this) static
Callback providing our card to register
Definition at line 88 of file eap_sim_file_plugin.c.
Referenced by METHOD().
 {
     return &this->card->card;
 }
static simaka_provider_t* get_provider (private_eap_sim_file_t * this) static
Callback providing our provider to register
Definition at line 96 of file eap_sim_file_plugin.c.
Referenced by METHOD().
 {
     return &this->provider->provider;
 }
static bool load_triplets (private_eap_sim_file_t * this, plugin_feature_t * feature, bool reg, void * data) static
Load triplet file
Definition at line 62 of file eap_sim_file_plugin.c.
References eap_sim_file_card_create(), eap_sim_file_provider_create(), eap_sim_file_triplets_create(), FALSE, TRIPLET_FILE, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->triplets = eap_sim_file_triplets_create(TRIPLET_FILE);
         if (!this->triplets)
         {
             return FALSE;
         }
         this->provider = eap_sim_file_provider_create(this->triplets);
         this->card = eap_sim_file_card_create(this->triplets);
         return TRUE;
     }
     this->card->destroy(this->card);
     this->provider->destroy(this->provider);
     this->triplets->destroy(this->triplets);
     this->card = NULL;
     this->provider = NULL;
     this->triplets = NULL;
     return TRUE;
 }
METHOD (plugin_t , get_name , char * , private_eap_sim_file_t * this)
Definition at line 53 of file eap_sim_file_plugin.c.
 {
     return "eap-sim-file";
 }
METHOD (plugin_t , get_features , int , private_eap_sim_file_t * this, plugin_feature_t * features[])
Definition at line 101 of file eap_sim_file_plugin.c.
References countof, get_card(), get_provider(), load_triplets(), PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, and simaka_manager_register().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((void*)load_triplets, NULL),
             PLUGIN_PROVIDE(CUSTOM, "eap-sim-file-triplets"),
         PLUGIN_CALLBACK(simaka_manager_register, get_card),
             PLUGIN_PROVIDE(CUSTOM, "sim-card"),
                 PLUGIN_DEPENDS(CUSTOM, "sim-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-sim-file-triplets"),
         PLUGIN_CALLBACK(simaka_manager_register, get_provider),
             PLUGIN_PROVIDE(CUSTOM, "sim-provider"),
                 PLUGIN_DEPENDS(CUSTOM, "sim-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-sim-file-triplets"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_eap_sim_file_t * this)
Definition at line 120 of file eap_sim_file_plugin.c.
References free().
 {
     free(this);
 }