strongSwan: leak_detective
leak_detective
utils
Classes
struct leak_detective_t
Typedefs
typedef struct leak_detective_t leak_detective_t
typedef void(* leak_detective_report_cb_t)(void *user, int count, size_t bytes, backtrace_t *bt, bool detailed)
typedef void(* leak_detective_summary_cb_t)(void *user, int count, size_t bytes, int whitelisted)
Functions
leak_detective_t * leak_detective_create ()
Variables
struct leak_detective_t __attribute__
Detailed Description
Typedef Documentation
typedef void(* leak_detective_report_cb_t)(void *user, int count, size_t bytes, backtrace_t *bt, bool detailed)
Callback function to report leak/usage information
Parameters
user user specific data
count number of allocations
bytes total size of allocations
bt backtrace of allocation
detailed TRUE to show a detailed backtrace
Definition at line 38 of file leak_detective.h.
typedef void(* leak_detective_summary_cb_t)(void *user, int count, size_t bytes, int whitelisted)
Callback function to report leak/usage summary information
Parameters
user user specific data
count total number of allocations
bytes total size of all reported allocations
whitelisted number of allocations suppressed by whitelist
Definition at line 49 of file leak_detective.h.
typedef struct leak_detective_t leak_detective_t
Definition at line 24 of file leak_detective.h.
Function Documentation
leak_detective_t* leak_detective_create ()
Create a leak_detective instance, unless the LEAK_DETECTIVE_DISABLE environment variable is set.
Returns
leak detective instance
Definition at line 962 of file leak_detective.c.
References enable_leak_detective(), free(), INIT, init_static_allocations(), register_hooks(), spinlock_create(), and thread_value_create().
Referenced by library_init().
 {
     private_leak_detective_t *this;
     INIT(this,
         .public = {
             .report = _report,
             .set_report_cb = _set_report_cb,
             .usage = _usage,
             .leaks = _leaks,
             .set_state = _set_state,
             .destroy = _destroy,
         },
     );
     if (getenv("LEAK_DETECTIVE_DISABLE") != NULL)
     {
         free(this);
         return NULL;
     }
     lock = spinlock_create();
     thread_disabled = thread_value_create(NULL);
     init_static_allocations();
     if (register_hooks())
     {
         enable_leak_detective();
     }
     return &this->public;
 }
Variable Documentation
struct leak_detective_t __attribute__