strongSwan: mediation_job
mediation_job
jobs
Classes
struct mediation_job_t
Typedefs
typedef struct mediation_job_t mediation_job_t
Functions
mediation_job_t * mediation_job_create (identification_t *peer_id, identification_t *requester, chunk_t connect_id, chunk_t connect_key, linked_list_t *endpoints, bool response)
mediation_job_t * mediation_callback_job_create (identification_t *requester, identification_t *peer_id)
Detailed Description
Typedef Documentation
typedef struct mediation_job_t mediation_job_t
Definition at line 24 of file mediation_job.h.
Function Documentation
mediation_job_t* mediation_callback_job_create (identification_t * requester, identification_t * peer_id)
Creates a special job of type MEDIATION that is used to send a callback notification to a peer.
Parameters get cloned.
Parameters
requester ID of the waiting peer
peer_id ID of the requested peer
Returns
job object
Definition at line 180 of file mediation_job.c.
References callback, identification_t::clone, mediation_job_create_empty(), source, and TRUE.
Referenced by METHOD().
 {
     private_mediation_job_t *this = mediation_job_create_empty();
     this->target = requester->clone(requester);
     this->source = peer_id->clone(peer_id);
     this->callback = TRUE;
     return &this->public;
 }
mediation_job_t* mediation_job_create (identification_t * peer_id, identification_t * requester, chunk_t connect_id, chunk_t connect_key, linked_list_t * endpoints, bool response)
Creates a job of type MEDIATION.
Parameters get cloned.
Parameters
peer_id ID of the requested peer
requester ID of the requesting peer
connect_id content of ME_CONNECTID (could be NULL)
connect_key content of ME_CONNECTKEY
endpoints list of submitted endpoints
response TRUE if this is a response
Returns
job object
Definition at line 161 of file mediation_job.c.
References chunk_clone, identification_t::clone, linked_list_t::clone_offset, mediation_job_create_empty(), response, and source.
Referenced by METHOD().
 {
     private_mediation_job_t *this = mediation_job_create_empty();
     this->target = peer_id->clone(peer_id);
     this->source = requester->clone(requester);
     this->connect_id = chunk_clone(connect_id);
     this->connect_key = chunk_clone(connect_key);
     this->endpoints = endpoints->clone_offset(endpoints, offsetof(endpoint_notify_t, clone));
     this->response = response;
     return &this->public;
 }