strongSwan: utils
utils
tkm
Functions
void sequence_to_chunk (const byte_t *const first, const uint32_t len, chunk_t *const chunk)
void chunk_to_sequence (const chunk_t *const chunk, void *sequence, const uint32_t typelen)
Detailed Description
Function Documentation
void chunk_to_sequence (const chunk_t *const chunk, void * sequence, const uint32_t typelen)
Convert chunk to variable-length byte sequence.
Parameters
chunk pointer to chunk struct
sequence pointer to variable-length sequence
typelen length of sequence type
Definition at line 35 of file tkm_utils.c.
References DBG1, DBG_LIB, chunk_t::len, memcpy, memset, chunk_t::ptr, and seq.
Referenced by build_cert_chain(), METHOD(), and START_TEST().
 {
     const uint32_t seqlenmax = typelen - sizeof(uint32_t);
     sequence_type *seq = sequence;
     memset(sequence, 0, typelen);
     if (chunk->len > seqlenmax)
     {
         DBG1(DBG_LIB, "chunk too large to fit into sequence %d > %d, limiting"
              " to %d bytes", chunk->len, seqlenmax, seqlenmax);
         seq->size = seqlenmax;
     }
     else
     {
         seq->size = chunk->len;
     }
     memcpy(seq->data, chunk->ptr, seq->size);
 }
void sequence_to_chunk (const byte_t *const first, const uint32_t len, chunk_t *const chunk)
Convert byte sequence to chunk.
Parameters
first pointer to first byte of sequence
len length of byte sequence
chunk pointer to chunk struct
Definition at line 28 of file tkm_utils.c.
References chunk_alloc, memcpy, and chunk_t::ptr.
Referenced by METHOD(), and START_TEST().
 {
     *chunk = chunk_alloc(len);
     memcpy(chunk->ptr, first, len);
 }