strongSwan: whitelist.c File Reference
whitelist.c File Reference
#include "whitelist_msg.h"
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <arpa/inet.h>
#include <netinet/in.h>
Functions
static int make_connection ()
static int read_all (int fd, void *buf, size_t len)
static int write_all (int fd, void *buf, size_t len)
static int send_msg (int type, char *id)
static int send_batch (int type, char *file)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 212 of file whitelist.c.
References fprintf, send_batch(), send_msg(), WHITELIST_ADD, WHITELIST_DISABLE, WHITELIST_ENABLE, WHITELIST_FLUSH, WHITELIST_LIST, and WHITELIST_REMOVE.
 {
     if (argc == 3 && strcmp(argv[1], "add") == 0)
     {
         return send_msg(WHITELIST_ADD, argv[2]);
     }
     if (argc == 3 && strcmp(argv[1], "remove") == 0)
     {
         return send_msg(WHITELIST_REMOVE, argv[2]);
     }
     if ((argc == 2 || argc == 3) && strcmp(argv[1], "add-from") == 0)
     {
         return send_batch(WHITELIST_ADD, argc == 3 ? argv[2] : NULL);
     }
     if ((argc == 2 || argc == 3) && strcmp(argv[1], "remove-from") == 0)
     {
         return send_batch(WHITELIST_REMOVE, argc == 3 ? argv[2] : NULL);
     }
     if ((argc == 2 || argc == 3) && strcmp(argv[1], "flush") == 0)
     {
         return send_msg(WHITELIST_FLUSH, argc == 3 ? argv[2] : "%any");
     }
     if ((argc == 2 || argc == 3) && strcmp(argv[1], "list") == 0)
     {
         return send_msg(WHITELIST_LIST, argc == 3 ? argv[2] : "%any");
     }
     if (argc == 2 && strcmp(argv[1], "enable") == 0)
     {
         return send_msg(WHITELIST_ENABLE, "");
     }
     if (argc == 2 && strcmp(argv[1], "disable") == 0)
     {
         return send_msg(WHITELIST_DISABLE, "");
     }
     fprintf(stderr, "Usage:\n");
     fprintf(stderr, "  %s add <identity>\n", argv[0]);
     fprintf(stderr, "  %s remove <identity>\n", argv[0]);
     fprintf(stderr, "  %s add-from <file>\n", argv[0]);
     fprintf(stderr, "  %s remove-from <file>\n", argv[0]);
     fprintf(stderr, "  %s flush [<pattern>]\n", argv[0]);
     fprintf(stderr, "  %s list [<pattern>]\n", argv[0]);
     fprintf(stderr, "  %s enable\n", argv[0]);
     fprintf(stderr, "  %s disable\n", argv[0]);
     return 1;
 }
static int make_connection () static
Connect to the daemon, return FD
Definition at line 32 of file whitelist.c.
References addr, close, connect, fprintf, len, socket, strerror, and WHITELIST_SOCKET.
Referenced by send_batch(), and send_msg().
 {
     union {
         struct sockaddr_un un;
         struct sockaddr_in in;
         struct sockaddr sa;
     } addr;
     int fd, len;
     if (getenv("TCP_PORT"))
     {
         addr.in.sin_family = AF_INET;
         addr.in.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
         addr.in.sin_port = htons(atoi(getenv("TCP_PORT")));
         len = sizeof(addr.in);
     }
     else
     {
         addr.un.sun_family = AF_UNIX;
         strcpy(addr.un.sun_path, WHITELIST_SOCKET);
         len = offsetof(struct sockaddr_un, sun_path) + strlen(addr.un.sun_path);
     }
     fd = socket(addr.sa.sa_family, SOCK_STREAM, 0);
     if (fd < 0)
     {
         fprintf(stderr, "opening socket failed: %s\n", strerror(errno));
         return -1;
     }
     if (connect(fd, &addr.sa, len) < 0)
     {
         fprintf(stderr, "connecting failed: %s\n", strerror(errno));
         close(fd);
         return -1;
     }
     return fd;
 }
static int read_all (int fd, void * buf, size_t len) static
Definition at line 70 of file whitelist.c.
References len, and read.
Referenced by send_msg().
 {
     ssize_t ret, done = 0;
     while (done < len)
     {
         ret = read(fd, buf, len - done);
         if (ret == -1 && errno == EINTR)
         {   /* interrupted, try again */
             continue;
         }
         if (ret < 0)
         {
             return -1;
         }
         done += ret;
         buf += ret;
     }
     return len;
 }
static int send_batch (int type, char * file) static
Send a batch of messages, reading identities from a file
Definition at line 159 of file whitelist.c.
References close, fprintf, whitelist_msg_t::id, len, make_connection(), msg, strerror, and write_all().
Referenced by main().
 {
     whitelist_msg_t msg = {
         .type = htonl(type),
     };
     FILE *f = stdin;
     int fd, len;
     fd = make_connection();
     if (fd == -1)
     {
         return 2;
     }
     if (file)
     {
         f = fopen(file, "r");
         if (f == NULL)
         {
             fprintf(stderr, "opening %s failed: %s\n", file, strerror(errno));
             close(fd);
             return 3;
         }
     }
     while (fgets(msg.id, sizeof(msg.id), f))
     {
         len = strlen(msg.id);
         if (len == 0)
         {
             continue;
         }
         if (msg.id[len-1] == '\n')
         {
             msg.id[len-1] = '\0';
         }
         if (write_all(fd, &msg, sizeof(msg)) != sizeof(msg))
         {
             fprintf(stderr, "writing to socket failed: %s\n", strerror(errno));
             if (f != stdin)
             {
                 fclose(f);
             }
             close(fd);
             return 2;
         }
     }
     if (f != stdin)
     {
         fclose(f);
     }
     close(fd);
     return 0;
 }
static int send_msg (int type, char * id) static
Send a single message
Definition at line 115 of file whitelist.c.
References close, fprintf, whitelist_msg_t::id, make_connection(), msg, printf, read_all(), snprintf, strerror, whitelist_msg_t::type, WHITELIST_LIST, and write_all().
Referenced by handle_ietf_message(), handle_message(), main(), and METHOD().
 {
     whitelist_msg_t msg = {
         .type = htonl(type),
     };
     int fd;
     fd = make_connection();
     if (fd == -1)
     {
         return 2;
     }
     snprintf(msg.id, sizeof(msg.id), "%s", id);
     if (write_all(fd, &msg, sizeof(msg)) != sizeof(msg))
     {
         fprintf(stderr, "writing to socket failed: %s\n", strerror(errno));
         close(fd);
         return 2;
     }
     if (type == WHITELIST_LIST)
     {
         while (1)
         {
             if (read_all(fd, &msg, sizeof(msg)) != sizeof(msg))
             {
                 fprintf(stderr, "reading failed: %s\n", strerror(errno));
                 close(fd);
                 return 2;
             }
             if (ntohl(msg.type) != WHITELIST_LIST)
             {
                 break;
             }
             msg.id[sizeof(msg.id) - 1] = '\0';
             printf("%s\n", msg.id);
         }
     }
     close(fd);
     return 0;
 }
static int write_all (int fd, void * buf, size_t len) static
Definition at line 91 of file whitelist.c.
References len, and write.
Referenced by send_batch(), and send_msg().
 {
     ssize_t ret, done = 0;
     while (done < len)
     {
         ret = write(fd, buf, len - done);
         if (ret == -1 && errno == EINTR)
         {   /* interrupted, try again */
             continue;
         }
         if (ret < 0)
         {
             return -1;
         }
         done += ret;
         buf += ret;
     }
     return len;
 }