strongSwan: updown_handler.c File Reference
updown_handler.c File Reference
#include "updown_handler.h"
#include <daemon.h>
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_updown_handler_t
struct attributes_t
Typedefs
typedef struct
private_updown_handler_t private_updown_handler_t
Functions
static void attributes_destroy (attributes_t *this)
METHOD (attribute_handler_t, handle, bool, private_updown_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (attribute_handler_t, release, void, private_updown_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (updown_handler_t, create_dns_enumerator, enumerator_t *, private_updown_handler_t *this, u_int id)
METHOD (updown_handler_t, destroy, void, private_updown_handler_t *this)
updown_handler_t * updown_handler_create ()
Typedef Documentation
typedef struct private_updown_handler_t private_updown_handler_t
Definition at line 22 of file updown_handler.c.
Function Documentation
static void attributes_destroy (attributes_t * this) static
Destroy an attributes_t entry
Definition at line 58 of file updown_handler.c.
References destroy(), and free().
Referenced by METHOD().
 {
     this->dns->destroy_offset(this->dns, offsetof(host_t, destroy));
     free(this);
 }
METHOD (attribute_handler_t , handle , bool , private_updown_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 64 of file updown_handler.c.
References enumerator_t::destroy, attributes_t::dns, enumerator_t::enumerate, FALSE, ike_sa_t::get_unique_id, host, host_create_from_chunk(), attributes_t::id, INIT, linked_list_t::insert_last, INTERNAL_IP4_DNS, INTERNAL_IP6_DNS, linked_list_create(), lock, TRUE, and spinlock_t::unlock.
 {
     attributes_t *current, *attr = NULL;
     enumerator_t *enumerator;
     host_t *host;
     switch (type)
     {
         case INTERNAL_IP4_DNS:
             host = host_create_from_chunk(AF_INET, data, 0);
             break;
         case INTERNAL_IP6_DNS:
             host = host_create_from_chunk(AF_INET6, data, 0);
             break;
         default:
             return FALSE;
     }
     if (!host)
     {
         return FALSE;
     }
     this->lock->write_lock(this->lock);
     enumerator = this->attrs->create_enumerator(this->attrs);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current->id == ike_sa->get_unique_id(ike_sa))
         {
             attr = current;
         }
     }
     enumerator->destroy(enumerator);
     if (!attr)
     {
         INIT(attr,
             .id = ike_sa->get_unique_id(ike_sa),
             .dns = linked_list_create(),
         );
         this->attrs->insert_last(this->attrs, attr);
     }
     attr->dns->insert_last(attr->dns, host);
     this->lock->unlock(this->lock);
     return TRUE;
 }
METHOD (attribute_handler_t , release , void , private_updown_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 113 of file updown_handler.c.
References attributes_destroy(), chunk_equals(), linked_list_t::create_enumerator, enumerator_t::destroy, host_t::destroy, attributes_t::dns, enumerator_t::enumerate, FALSE, family, found, host_t::get_address, linked_list_t::get_count, host_t::get_family, ike_sa_t::get_unique_id, host, attributes_t::id, INTERNAL_IP4_DNS, INTERNAL_IP6_DNS, lock, linked_list_t::remove_at, TRUE, and spinlock_t::unlock.
 {
     attributes_t *attr;
     enumerator_t *enumerator, *servers;
     host_t *host;
     bool found = FALSE;
     int family;
     switch (type)
     {
         case INTERNAL_IP4_DNS:
             family = AF_INET;
             break;
         case INTERNAL_IP6_DNS:
             family = AF_INET6;
             break;
         default:
             return;
     }
     this->lock->write_lock(this->lock);
     enumerator = this->attrs->create_enumerator(this->attrs);
     while (enumerator->enumerate(enumerator, &attr))
     {
         if (attr->id == ike_sa->get_unique_id(ike_sa))
         {
             servers = attr->dns->create_enumerator(attr->dns);
             while (servers->enumerate(servers, &host))
             {
                 if (host->get_family(host) == family &&
                     chunk_equals(data, host->get_address(host)))
                 {
                     attr->dns->remove_at(attr->dns, servers);
                     host->destroy(host);
                     found = TRUE;
                     break;
                 }
             }
             servers->destroy(servers);
             if (attr->dns->get_count(attr->dns) == 0)
             {
                 this->attrs->remove_at(this->attrs, enumerator);
                 attributes_destroy(attr);
                 break;
             }
         }
         if (found)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (updown_handler_t , create_dns_enumerator , enumerator_t * , private_updown_handler_t * this, u_int id)
Definition at line 170 of file updown_handler.c.
References daemon_t::bus, charon, linked_list_t::create_enumerator, enumerator_t::destroy, attributes_t::dns, enumerator_t::enumerate, enumerator_create_cleaner(), enumerator_create_empty(), bus_t::get_sa, ike_sa_t::get_unique_id, attributes_t::id, lock, and spinlock_t::unlock.
 {
     attributes_t *attr;
     enumerator_t *enumerator;
     ike_sa_t *ike_sa;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (!ike_sa)
     {
         return enumerator_create_empty();
     }
     this->lock->read_lock(this->lock);
     enumerator = this->attrs->create_enumerator(this->attrs);
     while (enumerator->enumerate(enumerator, &attr))
     {
         if (attr->id == ike_sa->get_unique_id(ike_sa))
         {
             enumerator->destroy(enumerator);
             return enumerator_create_cleaner(
                                         attr->dns->create_enumerator(attr->dns),
                                         (void*)this->lock->unlock, this->lock);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return enumerator_create_empty();
 }
METHOD (updown_handler_t , destroy , void , private_updown_handler_t * this)
Definition at line 202 of file updown_handler.c.
References attributes_destroy(), spinlock_t::destroy, free(), and lock.
 {
     this->lock->destroy(this->lock);
     this->attrs->destroy_function(this->attrs, (void*)attributes_destroy);
     free(this);
 }