strongSwan: ietf_attr_string_version.c File Reference
ietf_attr_string_version.c File Reference
#include "ietf_attr_string_version.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_string_version_t
Macros
#define STRING_VERSION_MIN_SIZE 3
Typedefs
typedef struct
private_ietf_attr_string_version_t private_ietf_attr_string_version_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_string_version_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_string_version_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_string_version_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_string_version_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_string_version_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_string_version_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_string_version_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_string_version_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_string_version_t *this)
METHOD (ietf_attr_string_version_t, get_version, chunk_t, private_ietf_attr_string_version_t *this, chunk_t *build, chunk_t *config)
pa_tnc_attr_t * ietf_attr_string_version_create (chunk_t version, chunk_t build, chunk_t config)
pa_tnc_attr_t * ietf_attr_string_version_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define STRING_VERSION_MIN_SIZE 3
PA-TNC String Version type (see section 4.2.4 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Version Len | Product Version Number (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Build Num Len | Internal Build Number (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Config. Len | Configuration Version Number (Variable Length)| +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 39 of file ietf_attr_string_version.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_string_version_t private_ietf_attr_string_version_t
Definition at line 23 of file ietf_attr_string_version.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_string_version_t * this)
Definition at line 92 of file ietf_attr_string_version.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_string_version_t * this)
Definition at line 98 of file ietf_attr_string_version.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_string_version_t * this)
Definition at line 104 of file ietf_attr_string_version.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_string_version_t * this, bool noskip)
Definition at line 110 of file ietf_attr_string_version.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_string_version_t * this)
Definition at line 116 of file ietf_attr_string_version.c.
References bio_writer_create(), build(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, STRING_VERSION_MIN_SIZE, value, version, and bio_writer_t::write_data8.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(STRING_VERSION_MIN_SIZE);
     writer->write_data8(writer, this->version);
     writer->write_data8(writer, this->build);
     writer->write_data8(writer, this->config);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_string_version_t * this, u_int32_t * offset)
Definition at line 136 of file ietf_attr_string_version.c.
References bio_reader_create(), build(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, end, FAILED, chunk_t::len, NEED_MORE, chunk_t::ptr, bio_reader_t::read_data8, status, STRING_VERSION_MIN_SIZE, SUCCESS, value, and version.
 {
     bio_reader_t *reader;
     status_t status = FAILED;
     chunk_t version, build, config;
     u_char *pos;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < STRING_VERSION_MIN_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for IETF string version");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     if (!reader->read_data8(reader, &version))
     {
         DBG1(DBG_TNC, "insufficient data for IETF product version number");
         goto end;
     }
     pos = memchr(version.ptr, '\0', version.len);
     if (pos)
     {
         DBG1(DBG_TNC, "nul termination in IETF product version number");
         *offset += 1 + (pos - version.ptr);
         goto end;
     }
     *offset += 1 + version.len;
     if (!reader->read_data8(reader, &build))
     {
         DBG1(DBG_TNC, "insufficient data for IETF internal build number");
         goto end;
     }
     pos = memchr(build.ptr, '\0', build.len);
     if (pos)
     {
         DBG1(DBG_TNC, "nul termination in IETF internal build number");
         *offset += 1 + (pos - build.ptr);
         goto end;
     }
     *offset += 1 + build.len;
     if (!reader->read_data8(reader, &config))
     {
         DBG1(DBG_TNC, "insufficient data for IETF configuration version number");
         goto end;
     }
     pos = memchr(config.ptr, '\0', config.len);
     if (pos)
     {
         DBG1(DBG_TNC, "nul termination in IETF configuration version number");
         *offset += 1 + (pos - config.ptr);
         goto end;
     }
     this->version = chunk_clone(version);
     this->build = chunk_clone(build);
     this->config = chunk_clone(config);
     status = SUCCESS;
 end:
     reader->destroy(reader);
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_string_version_t * this, chunk_t segment)
Definition at line 211 of file ietf_attr_string_version.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_string_version_t * this)
Definition at line 217 of file ietf_attr_string_version.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_string_version_t * this)
Definition at line 224 of file ietf_attr_string_version.c.
References build(), free(), chunk_t::ptr, ref_put(), value, and version.
 {
     if (ref_put(&this->ref))
     {
         free(this->version.ptr);
         free(this->build.ptr);
         free(this->config.ptr);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_string_version_t , get_version , chunk_t , private_ietf_attr_string_version_t * this, chunk_t * build, chunk_t * config)
Definition at line 237 of file ietf_attr_string_version.c.
References build(), and version.
 {
     if (build)
     {
         *build = this->build;
     }
     if (config)
     {
         *config = this->config;
     }
     return this->version;
 }