strongSwan: imv_scanner_state
imv_scanner_state
imv_scanner
Classes
struct imv_scanner_state_t
Typedefs
typedef struct imv_scanner_state_t imv_scanner_state_t
typedef enum
imv_scanner_handshake_state_t imv_scanner_handshake_state_t
Enumerations
enum imv_scanner_handshake_state_t { IMV_SCANNER_STATE_INIT, IMV_SCANNER_STATE_ATTR_REQ, IMV_SCANNER_STATE_WORKITEMS, IMV_SCANNER_STATE_END }
Functions
imv_state_t * imv_scanner_state_create (TNC_ConnectionID id)
Detailed Description
Typedef Documentation
typedef enum imv_scanner_handshake_state_t imv_scanner_handshake_state_t
Definition at line 33 of file imv_scanner_state.h.
typedef struct imv_scanner_state_t imv_scanner_state_t
Definition at line 32 of file imv_scanner_state.h.
Enumeration Type Documentation
enum imv_scanner_handshake_state_t
IMV Scanner Handshake States (state machine)
Enumerator
IMV_SCANNER_STATE_INIT
IMV_SCANNER_STATE_ATTR_REQ
IMV_SCANNER_STATE_WORKITEMS
IMV_SCANNER_STATE_END
Definition at line 38 of file imv_scanner_state.h.
{
     IMV_SCANNER_STATE_INIT,
     IMV_SCANNER_STATE_ATTR_REQ,
     IMV_SCANNER_STATE_WORKITEMS,
     IMV_SCANNER_STATE_END
 };
Function Documentation
imv_state_t* imv_scanner_state_create (TNC_ConnectionID connection_id)
Create an imv_scanner_state_t instance
Parameters
id connection ID
Described in header.
Definition at line 352 of file imv_scanner_state.c.
References INIT, linked_list_create(), seg_contract_manager_create(), TNC_CONNECTION_STATE_CREATE, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TNC_IMV_EVALUATION_RESULT_DONT_KNOW.
Referenced by METHOD().
 {
     private_imv_scanner_state_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_connection_id = _get_connection_id,
                 .has_long = _has_long,
                 .has_excl = _has_excl,
                 .set_flags = _set_flags,
                 .set_max_msg_len = _set_max_msg_len,
                 .get_max_msg_len = _get_max_msg_len,
                 .set_action_flags = _set_action_flags,
                 .get_action_flags = _get_action_flags,
                 .set_session = _set_session,
                 .get_session= _get_session,
                 .get_contracts = _get_contracts,
                 .change_state = _change_state,
                 .get_recommendation = _get_recommendation,
                 .set_recommendation = _set_recommendation,
                 .update_recommendation = _update_recommendation,
                 .get_reason_string = _get_reason_string,
                 .get_remediation_instructions = _get_remediation_instructions,
                 .destroy = _destroy,
             },
             .set_handshake_state = _set_handshake_state,
             .get_handshake_state = _get_handshake_state,
             .set_port_filter_attr = _set_port_filter_attr,
             .get_port_filter_attr = _get_port_filter_attr,
             .add_violating_port = _add_violating_port,
         },
         .state = TNC_CONNECTION_STATE_CREATE,
         .rec = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION,
         .eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW,
         .connection_id = connection_id,
         .contracts = seg_contract_manager_create(),
         .violating_ports = linked_list_create(),
     );
     return &this->public.interface;
 }