strongSwan: farp_spoofer
farp_spoofer
farp
Classes
struct farp_spoofer_t
Typedefs
typedef struct farp_spoofer_t farp_spoofer_t
Functions
farp_spoofer_t * farp_spoofer_create (farp_listener_t *listener)
Detailed Description
Typedef Documentation
typedef struct farp_spoofer_t farp_spoofer_t
Definition at line 26 of file farp_spoofer.h.
Function Documentation
farp_spoofer_t* farp_spoofer_create (farp_listener_t * listener)
Create a farp_spoofer instance.
Parameters
listener listener to check for addresses to spoof
Returns
spoofer instance
See header
Definition at line 137 of file farp_spoofer.c.
References watcher_t::add, arp_t, close, DBG1, DBG_NET, free(), INIT, lib, listener, opcode, receive_arp(), setsockopt, socket, strerror, library_t::watcher, and WATCHER_READ.
Referenced by farp_plugin_create().
 {
     private_farp_spoofer_t *this;
     struct sock_filter arp_request_filter_code[] = {
         BPF_STMT(BPF_LD+BPF_H+BPF_ABS, offsetof(arp_t, protocol_type)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, ETH_P_IP, 0, 9),
         BPF_STMT(BPF_LD+BPF_B+BPF_ABS, offsetof(arp_t, hardware_size)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, 6, 0, 7),
         BPF_STMT(BPF_LD+BPF_B+BPF_ABS, offsetof(arp_t, protocol_size)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, 4, 0, 4),
         BPF_STMT(BPF_LD+BPF_H+BPF_ABS, offsetof(arp_t, opcode)),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, ARPOP_REQUEST, 0, 3),
         BPF_STMT(BPF_LD+BPF_W+BPF_LEN, 0),
         BPF_JUMP(BPF_JMP+BPF_JGE+BPF_K, sizeof(arp_t), 0, 1),
         BPF_STMT(BPF_RET+BPF_K, sizeof(arp_t)),
         BPF_STMT(BPF_RET+BPF_K, 0),
     };
     struct sock_fprog arp_request_filter = {
         sizeof(arp_request_filter_code) / sizeof(struct sock_filter),
         arp_request_filter_code,
     };
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
         .listener = listener,
     );
     this->skt = socket(AF_PACKET, SOCK_DGRAM, htons(ETH_P_ARP));
     if (this->skt == -1)
     {
         DBG1(DBG_NET, "opening ARP packet socket failed: %s", strerror(errno));
         free(this);
         return NULL;
     }
     if (setsockopt(this->skt, SOL_SOCKET, SO_ATTACH_FILTER,
                    &arp_request_filter, sizeof(arp_request_filter)) < 0)
     {
         DBG1(DBG_NET, "installing ARP packet filter failed: %s", strerror(errno));
         close(this->skt);
         free(this);
         return NULL;
     }
     lib->watcher->add(lib->watcher, this->skt, WATCHER_READ,
                       (watcher_cb_t)receive_arp, this);
     return &this->public;
 }