strongSwan: capabilities_t Struct Reference
capabilities_t Struct Reference
capabilities
#include "capabilities.h"
Public Attributes
bool(* keep)(capabilities_t *this, u_int cap) __attribute__((warn_unused_result))
bool(* check)(capabilities_t *this, u_int cap)
uid_t(* get_uid)(capabilities_t *this)
gid_t(* get_gid)(capabilities_t *this)
void(* set_uid)(capabilities_t *this, uid_t uid)
void(* set_gid)(capabilities_t *this, gid_t gid)
bool(* resolve_uid)(capabilities_t *this, char *username)
bool(* resolve_gid)(capabilities_t *this, char *groupname)
bool(* drop)(capabilities_t *this)
void(* destroy)(capabilities_t *this)
Detailed Description
POSIX capability dropping abstraction layer.
Definition at line 54 of file capabilities.h.
Member Data Documentation
bool(* capabilities_t::check)(capabilities_t *this, u_int cap)
Check if the given capability is currently held.
Note
CAP_CHOWN is handled specially as it might not be required.
Parameters
cap capability to check
Returns
TRUE if the capability is currently held
Definition at line 76 of file capabilities.h.
Referenced by dhcp_plugin_create(), kernel_libipsec_plugin_create(), kernel_pfkey_plugin_create(), smp_plugin_create(), socket_default_socket_create(), and stream_service_create_unix().
void(* capabilities_t::destroy)(capabilities_t *this)
Destroy a capabilities_t.
Definition at line 132 of file capabilities.h.
bool(* capabilities_t::drop)(capabilities_t *this)
Drop all capabilities not previously passed to keep(), switch to UID/GID.
Returns
TRUE if capability drop successful
Definition at line 127 of file capabilities.h.
Referenced by main().
gid_t(* capabilities_t::get_gid)(capabilities_t *this)
Get the group ID set through set_gid/resolve_gid.
Returns
currently set group ID
Definition at line 90 of file capabilities.h.
Referenced by change_fifo_permissions(), check_pidfile(), disable_all(), smp_plugin_create(), and stream_service_create_unix().
uid_t(* capabilities_t::get_uid)(capabilities_t *this)
Get the user ID set through set_uid/resolve_uid.
Returns
currently set user ID
Definition at line 83 of file capabilities.h.
Referenced by change_fifo_permissions(), check_pidfile(), disable_all(), smp_plugin_create(), and stream_service_create_unix().
bool(* capabilities_t::keep)(capabilities_t *this, u_int cap) __attribute__((warn_unused_result))
Register a capability to keep while calling drop(). Verifies that the capability is currently held.
Note
CAP_CHOWN is handled specially as it might not be required.
Parameters
cap capability to keep
Returns
FALSE if the capability is currently not held
Definition at line 65 of file capabilities.h.
Referenced by agent_plugin_create(), connmark_plugin_create(), dhcp_plugin_create(), farp_plugin_create(), forecast_plugin_create(), ha_plugin_create(), kernel_netlink_plugin_create(), and xauth_pam_plugin_create().
bool(* capabilities_t::resolve_gid)(capabilities_t *this, char *groupname)
Resolve a groupname and set the group ID accordingly.
Parameters
groupname groupname to get the gid for
Returns
TRUE if groupname resolved and gid set
Definition at line 120 of file capabilities.h.
Referenced by lookup_uid_gid().
bool(* capabilities_t::resolve_uid)(capabilities_t *this, char *username)
Resolve a username and set the user ID accordingly.
Parameters
username username get the uid for
Returns
TRUE if username resolved and uid set
Definition at line 112 of file capabilities.h.
Referenced by lookup_uid_gid().
void(* capabilities_t::set_gid)(capabilities_t *this, gid_t gid)
Set the numerical group ID to use during rights dropping.
Parameters
gid group ID to use
Definition at line 104 of file capabilities.h.
void(* capabilities_t::set_uid)(capabilities_t *this, uid_t uid)
Set the numerical user ID to use during rights dropping.
Parameters
uid user ID to use
Definition at line 97 of file capabilities.h.
Referenced by lookup_uid_gid().
The documentation for this struct was generated from the following file:
capabilities.h