strongSwan: ntru_poly
ntru_poly
ntru
Classes
struct ntru_poly_t
Typedefs
typedef struct ntru_poly_t ntru_poly_t
Functions
ntru_poly_t * ntru_poly_create_from_seed (hash_algorithm_t alg, chunk_t seed, uint8_t c_bits, uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form)
ntru_poly_t * ntru_poly_create_from_data (uint16_t *data, uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form)
Detailed Description
Typedef Documentation
typedef struct ntru_poly_t ntru_poly_t
Definition at line 24 of file ntru_poly.h.
Function Documentation
ntru_poly_t* ntru_poly_create_from_data (uint16_t * data, uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form)
Create a trits polynomial from an array of indices of non-zero coefficients
Parameters
data array of indices of non-zero coefficients
N ring dimension, number of polynomial coefficients
q large modulus
indices_len_p number of indices for +1 coefficients
indices_len_m number of indices for -1 coefficients
is_product_form generate multiple polynomials
Definition at line 356 of file ntru_poly.c.
References ntru_poly_create().
 {
     private_ntru_poly_t *this;
     int i;
     this = ntru_poly_create(N, q, indices_len_p, indices_len_m, is_product_form);
     for (i = 0; i < this->num_indices; i++)
     {
         this->indices[i] = data[i];
     }
     return &this->public;
 }
ntru_poly_t* ntru_poly_create_from_seed (hash_algorithm_t alg, chunk_t seed, uint8_t c_bits, uint16_t N, uint16_t q, uint32_t indices_len_p, uint32_t indices_len_m, bool is_product_form)
Create a trits polynomial from a seed using MGF1 with a base hash function
Parameters
alg hash algorithm to be used by MGF1
seed seed used by MGF1 to generate trits from
N ring dimension, number of polynomial coefficients
q large modulus
c_bits number of bits for candidate index
indices_len_p number of indices for +1 coefficients
indices_len_m number of indices for -1 coefficients
is_product_form generate multiple polynomials
Definition at line 293 of file ntru_poly.c.
References mgf1_bitspender_t::destroy, destroy(), free(), mgf1_bitspender_t::get_bits, malloc(), memset, mgf1_bitspender_create(), N, n, ntru_poly_create(), and TRUE.
Referenced by METHOD(), ntru_private_key_create(), and START_TEST().
 {
     private_ntru_poly_t *this;
     int n, num_indices, index_i = 0;
     uint32_t index, limit;
     uint8_t *used;
     mgf1_bitspender_t *bitspender;
     bitspender = mgf1_bitspender_create(alg, seed, TRUE);
     if (!bitspender)
     {
         return NULL;
     }
     this = ntru_poly_create(N, q, indices_len_p, indices_len_m, is_product_form);
     used = malloc(N);
     limit = N * ((1 << c_bits) / N);
     /* generate indices for all polynomials */
     for (n = 0; n < this->num_polynomials; n++)
     {
         memset(used, 0, N);
         num_indices = this->indices_len[n].p + this->indices_len[n].m;
         /* generate indices for a single polynomial */
         while (num_indices)
         {
             /* generate a random candidate index with a size of c_bits */
             do
             {
                 if (!bitspender->get_bits(bitspender, c_bits, &index))
                 {
                     bitspender->destroy(bitspender);
                     destroy(this);
                     free(used);
                     return NULL;
                 }
             }
             while (index >= limit);
             /* form index and check if unique */
             index %= N;
             if (!used[index])
             {
                 used[index] = 1;
                 this->indices[index_i++] = index;
                 num_indices--;
             }
         }
     }
     bitspender->destroy(bitspender);
     free(used);
     return &this->public;
 }