strongSwan: pts_file_meas
pts_file_meas
pts
Classes
struct pts_file_meas_t
Typedefs
typedef struct pts_file_meas_t pts_file_meas_t
Functions
pts_file_meas_t * pts_file_meas_create (u_int16_t request_id)
pts_file_meas_t * pts_file_meas_create_from_path (u_int16_t request_id, char *pathname, bool is_dir, bool use_rel_name, pts_meas_algorithms_t alg)
Detailed Description
Typedef Documentation
typedef struct pts_file_meas_t pts_file_meas_t
Definition at line 29 of file pts_file_meas.h.
Function Documentation
pts_file_meas_t* pts_file_meas_create (u_int16_t request_id)
Creates a pts_file_meas_t object
Parameters
request_id ID of PTS File Measurement Request
See header
Definition at line 269 of file pts_file_meas.c.
References INIT, and linked_list_create().
Referenced by METHOD(), and pts_file_meas_create_from_path().
 {
     private_pts_file_meas_t *this;
     INIT(this,
         .public = {
             .get_request_id = _get_request_id,
             .get_file_count = _get_file_count,
             .add = _add,
             .create_enumerator = _create_enumerator,
             .check = _check,
             .verify = _verify,
             .destroy = _destroy,
         },
         .request_id = request_id,
         .list = linked_list_create(),
     );
     return &this->public;
 }
pts_file_meas_t* pts_file_meas_create_from_path (u_int16_t request_id, char * pathname, bool is_dir, bool use_rel_name, pts_meas_algorithms_t alg)
Creates a pts_file_meas_t object measuring a file/directory
Parameters
request_id ID of PTS File Measurement Request
pathname Absolute file or directory pathname
is_dir TRUE if directory path
use_rel_name TRUE if relative filenames are to be used
alg PTS hash measurement algorithm to be used
See header
Definition at line 337 of file pts_file_meas.c.
References add(), chunk_create(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG2, DBG_PTS, hasher_t::destroy, destroy(), end, enumerator_create_directory(), FALSE, free(), hasher_t::get_hash_size, hash, hash_algorithm_names, hash_file(), HASH_SIZE_SHA384, hasher, lib, path_basename(), pts_file_meas_create(), pts_meas_algo_to_hash(), strdup, strerror, and TRUE.
Referenced by add_hash(), and imc_attestation_process().
 {
     private_pts_file_meas_t *this;
     hash_algorithm_t hash_alg;
     hasher_t *hasher;
     u_char hash[HASH_SIZE_SHA384];
     chunk_t measurement;
     char* filename;
     bool success = TRUE;
     /* Create a hasher and a hash measurement buffer */
     hash_alg = pts_meas_algo_to_hash(alg);
     hasher = lib->crypto->create_hasher(lib->crypto, hash_alg);
     if (!hasher)
     {
         DBG1(DBG_PTS, "hasher %N not available", hash_algorithm_names, hash_alg);
         return NULL;
     }
     measurement = chunk_create(hash, hasher->get_hash_size(hasher));
     this = (private_pts_file_meas_t*)pts_file_meas_create(request_id);
     if (is_dir)
     {
         enumerator_t *enumerator;
         char *rel_name, *abs_name;
         struct stat st;
         enumerator = enumerator_create_directory(pathname);
         if (!enumerator)
         {
             DBG1(DBG_PTS, "  directory '%s' can not be opened, %s", pathname,
                  strerror(errno));
             success = FALSE;
             goto end;
         }
         while (enumerator->enumerate(enumerator, &rel_name, &abs_name, &st))
         {
             /* measure regular files only */
             if (S_ISREG(st.st_mode) && *rel_name != '.')
             {
                 if (!hash_file(hasher, abs_name, hash))
                 {
                     continue;
                 }
                 filename = use_rel_name ? rel_name : abs_name;
                 DBG2(DBG_PTS, "  %#B for '%s'", &measurement, filename);
                 add(this, filename, measurement);
             }
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         if (!hash_file(hasher, pathname, hash))
         {
             success = FALSE;
             goto end;
         }
         filename = use_rel_name ? path_basename(pathname) : strdup(pathname);
         DBG2(DBG_PTS, "  %#B for '%s'", &measurement, filename);
         add(this, filename, measurement);
         free(filename);
     }
 end:
     hasher->destroy(hasher);
     if (success)
     {
         return &this->public;
     }
     else
     {
         destroy(this);
         return NULL;
     }
 }