strongSwan: dumm_t Struct Reference
dumm_t Struct Reference
#include "dumm.h"
Public Attributes
guest_t *(* create_guest)(dumm_t *this, char *name, char *kernel, char *master, char *args)
enumerator_t *(* create_guest_enumerator)(dumm_t *this)
void(* delete_guest)(dumm_t *this, guest_t *guest)
bridge_t *(* create_bridge)(dumm_t *this, char *name)
enumerator_t *(* create_bridge_enumerator)(dumm_t *this)
void(* delete_bridge)(dumm_t *this, bridge_t *bridge)
bool(* add_overlay)(dumm_t *this, char *dir)
bool(* del_overlay)(dumm_t *this, char *dir)
bool(* pop_overlay)(dumm_t *this)
bool(* load_template)(dumm_t *this, char *name)
enumerator_t *(* create_template_enumerator)(dumm_t *this)
void(* destroy)(dumm_t *this)
Detailed Description
dumm - Dynamic Uml Mesh Modeler
Controls a group of UML guests and their networks.
Definition at line 35 of file dumm.h.
Member Data Documentation
bool(* dumm_t::add_overlay)(dumm_t *this, char *dir)
Add an overlay to all guests.
Directories named after the guests are created, if they do not exist in the given overlay directory.
If adding the overlay on at lest one guest fails, FALSE is returned and the overlay is again removed from all guests.
Parameters
dir dir to the overlay
Returns
FALSE, on failure
Definition at line 97 of file dumm.h.
Referenced by dumm_add_overlay().
bridge_t*(* dumm_t::create_bridge)(dumm_t *this, char *name)
Create a new bridge.
Parameters
name name of the bridge to create
Returns
created bridge
Definition at line 69 of file dumm.h.
Referenced by bridge_new(), and create_switch().
enumerator_t*(* dumm_t::create_bridge_enumerator)(dumm_t *this)
Create an enumerator over all bridges.
Returns
enumerator over bridge_t's
Definition at line 76 of file dumm.h.
Referenced by bridge_each(), bridge_find(), and connect_guest().
guest_t*(* dumm_t::create_guest)(dumm_t *this, char *name, char *kernel, char *master, char *args)
Starts a new UML guest
Parameters
name name of the guest
kernel UML kernel to use for guest
master mounted read only master filesystem
args additional args to pass to kernel
Returns
guest if started, NULL if failed
Definition at line 46 of file dumm.h.
Referenced by create_guest(), and guest_new().
enumerator_t*(* dumm_t::create_guest_enumerator)(dumm_t *this)
Create an enumerator over all guests.
Returns
enumerator over guest_t's
Definition at line 54 of file dumm.h.
Referenced by guest_hash_create(), main(), and sigchld_handler().
enumerator_t*(* dumm_t::create_template_enumerator)(dumm_t *this)
Create an enumerator over all available templates.
Returns
enumerator over char*
Definition at line 133 of file dumm.h.
Referenced by template_each().
bool(* dumm_t::del_overlay)(dumm_t *this, char *dir)
Removes an overlay from all guests.
Parameters
dir dir to the overlay
Returns
FALSE, if the overlay was not found on any guest
Definition at line 105 of file dumm.h.
Referenced by dumm_del_overlay().
void(* dumm_t::delete_bridge)(dumm_t *this, bridge_t *bridge)
Delete a bridge.
Parameters
bridge bridge to destroy
Definition at line 83 of file dumm.h.
Referenced by bridge_delete().
void(* dumm_t::delete_guest)(dumm_t *this, guest_t *guest)
Delete a guest from disk.
Parameters
guest guest to destroy
Definition at line 61 of file dumm.h.
Referenced by delete_guest(), and guest_delete().
void(* dumm_t::destroy)(dumm_t *this)
stop all guests and destroy the modeler
Definition at line 138 of file dumm.h.
Referenced by Final_dumm(), and main().
bool(* dumm_t::load_template)(dumm_t *this, char *name)
Loads a template, create a new one if it does not exist.
This is basically a wrapper around add/del_overlay to simplify working with overlays. Templates are located in a predefined directory, so that only a name for the template has to be specified here. Only one template can be loaded at any one time (but other overlays can be added on top or below a template).
Parameters
name name of the template to load, NULL to unload
Returns
FALSE if load/create failed
Definition at line 126 of file dumm.h.
Referenced by quit(), template_load(), and template_unload().
bool(* dumm_t::pop_overlay)(dumm_t *this)
Remove the latest overlay from all guests.
Returns
FALSE, if no overlay was found on any guest
Definition at line 112 of file dumm.h.
Referenced by dumm_pop_overlay().
The documentation for this struct was generated from the following file:
dumm.h