strongSwan: spinlock
spinlock
threading
Classes
struct spinlock_t
Typedefs
typedef struct spinlock_t spinlock_t
Functions
spinlock_t * spinlock_create ()
Detailed Description
Typedef Documentation
typedef struct spinlock_t spinlock_t
Definition at line 24 of file spinlock.h.
Function Documentation
spinlock_t* spinlock_create ()
Create a spin lock instance.
Returns
unlocked instance
Definition at line 108 of file spinlock.c.
References INIT, mutex, mutex_create(), MUTEX_TYPE_DEFAULT, profiler_init, and spinlock.
Referenced by _cas_impl(), kernel_netlink_net_create(), kernel_pfroute_net_create(), leak_detective_create(), METHOD(), START_TEST(), strerror_init(), stroke_counter_create(), and threads_init().
 {
     private_spinlock_t *this;
     INIT(this,
         .public = {
             .lock = _lock,
             .unlock = _unlock,
             .destroy = _destroy,
         },
     );
 #ifdef HAVE_PTHREAD_SPIN_INIT
     pthread_spin_init(&this->spinlock, PTHREAD_PROCESS_PRIVATE);
     profiler_init(&this->profile);
 #else
     this->mutex = mutex_create(MUTEX_TYPE_DEFAULT);
 #endif
     return &this->public;
 }