strongSwan: imv_os_info.c File Reference
imv_os_info.c File Reference
#include "imv_os_info.h"
Classes
struct private_imv_os_info_t
Typedefs
typedef struct
private_imv_os_info_t private_imv_os_info_t
Functions
METHOD (imv_os_info_t, get_type, os_type_t, private_imv_os_info_t *this)
METHOD (imv_os_info_t, set_name, void, private_imv_os_info_t *this, chunk_t name)
METHOD (imv_os_info_t, get_name, chunk_t, private_imv_os_info_t *this)
METHOD (imv_os_info_t, set_version, void, private_imv_os_info_t *this, chunk_t version)
METHOD (imv_os_info_t, get_version, chunk_t, private_imv_os_info_t *this)
METHOD (imv_os_info_t, get_info, char *, private_imv_os_info_t *this)
METHOD (imv_os_info_t, destroy, void, private_imv_os_info_t *this)
imv_os_info_t * imv_os_info_create (void)
Typedef Documentation
typedef struct private_imv_os_info_t private_imv_os_info_t
Definition at line 18 of file imv_os_info.c.
Function Documentation
METHOD (imv_os_info_t , get_type , os_type_t , private_imv_os_info_t * this)
Definition at line 58 of file imv_os_info.c.
References type.
 {
     return this->type;
 }
METHOD (imv_os_info_t , set_name , void , private_imv_os_info_t * this, chunk_t name)
Definition at line 64 of file imv_os_info.c.
References chunk_clone, chunk_equals(), free(), chunk_t::len, os_type_from_name(), chunk_t::ptr, and type.
 {
     /* Has the OS name already been set? */
     if (this->name.len)
     {
         if (chunk_equals(name, this->name))
         {
             return;
         }
         free(this->name.ptr);
         /* Also clear the OS info string */
         free(this->info);
         this->info = NULL;
     }
     this->name = chunk_clone(name);
     this->type = os_type_from_name(name);
 }
METHOD (imv_os_info_t , get_name , chunk_t , private_imv_os_info_t * this)
Definition at line 84 of file imv_os_info.c.
References name.
 {
     return this->name;
 }
METHOD (imv_os_info_t , set_version , void , private_imv_os_info_t * this, chunk_t version)
Definition at line 90 of file imv_os_info.c.
References chunk_clone, chunk_equals(), free(), chunk_t::ptr, and TRUE.
 {
     /* Has the OS version already been set? */
     if (this->version_is_set)
     {
         if (chunk_equals(version, this->version))
         {
             return;
         }
         free(this->version.ptr);
         /* Also clear the OS info string */
         free(this->info);
         this->info = NULL;
     }
     this->version = chunk_clone(version);
     this->version_is_set = TRUE;
 }
METHOD (imv_os_info_t , get_version , chunk_t , private_imv_os_info_t * this)
Definition at line 110 of file imv_os_info.c.
References version.
 {
     return this->version;
 }
METHOD (imv_os_info_t , get_info , char * , private_imv_os_info_t * this)
Definition at line 116 of file imv_os_info.c.
References chunk_t::len, len, malloc(), name, snprintf, and version.
 {
     int len;
     if (!this->info)
     {
         /* Have both OS name and OS version been set? */
         if (this->name.len == 0 || !this->version_is_set)
         {
             return NULL;
         }
         /* OS info is a concatenation of OS name and OS version */
         len = this->name.len + 1 + this->version.len + 1;
         this->info = malloc(len);
         snprintf(this->info, len, "%.*s %.*s",
                 (int)this->name.len, this->name.ptr,
                 (int)this->version.len, this->version.ptr);
     }
     return this->info;
 }
METHOD (imv_os_info_t , destroy , void , private_imv_os_info_t * this)
Definition at line 139 of file imv_os_info.c.
References free(), name, chunk_t::ptr, and version.
 {
     free(this->name.ptr);
     free(this->version.ptr);
     free(this->info);
     free(this);
 }