strongSwan: tkm_kernel_sad_t Struct Reference
tkm_kernel_sad_t Struct Reference
kernel sad
#include "tkm_kernel_sad.h"
Public Attributes
bool(* insert)(tkm_kernel_sad_t *const this, const esa_id_type esa_id, const u_int32_t reqid, const host_t *const src, const host_t *const dst, const u_int32_t spi_loc, const u_int32_t spi_rem, const u_int8_t proto)
esa_id_type(* get_esa_id)(tkm_kernel_sad_t *const this, const host_t *const src, const host_t *const dst, const u_int32_t spi, const u_int8_t proto)
esa_id_type(* get_other_esa_id)(tkm_kernel_sad_t *const this, const esa_id_type esa_id)
host_t *(* get_dst_host)(tkm_kernel_sad_t *const this, const u_int32_t reqid, const u_int32_t spi, const u_int8_t proto)
bool(* remove)(tkm_kernel_sad_t *const this, const esa_id_type esa_id)
void(* destroy)(tkm_kernel_sad_t *this)
Detailed Description
The TKM kernel SAD (security association database) stores information about CHILD SAs.
Definition at line 34 of file tkm_kernel_sad.h.
Member Data Documentation
void(* tkm_kernel_sad_t::destroy)(tkm_kernel_sad_t *this)
Destroy a tkm_kernel_sad instance.
Definition at line 98 of file tkm_kernel_sad.h.
Referenced by START_TEST().
host_t*(* tkm_kernel_sad_t::get_dst_host)(tkm_kernel_sad_t *const this, const u_int32_t reqid, const u_int32_t spi, const u_int8_t proto)
Get destination host for entry with given parameters.
Parameters
reqid reqid of CHILD SA
spi Remote SPI of CHILD SA
proto protocol of CHILD SA (ESP/AH)
Returns
destination host of entry if found, NULL otherwise
Definition at line 84 of file tkm_kernel_sad.h.
Referenced by charon_esa_expire(), and START_TEST().
esa_id_type(* tkm_kernel_sad_t::get_esa_id)(tkm_kernel_sad_t *const this, const host_t *const src, const host_t *const dst, const u_int32_t spi, const u_int8_t proto)
Get ESA id for entry with given parameters.
Parameters
src source address of CHILD SA
dst destination address of CHILD SA
spi Remote SPI of CHILD SA
proto protocol of CHILD SA (ESP/AH)
Returns
ESA id of entry if found, 0 otherwise
Definition at line 62 of file tkm_kernel_sad.h.
Referenced by METHOD(), and START_TEST().
esa_id_type(* tkm_kernel_sad_t::get_other_esa_id)(tkm_kernel_sad_t *const this, const esa_id_type esa_id)
Get ESA id for entry associated with same security policy as the specified ESA.
Parameters
esa_id id of ESA identifying the security policy
Returns
ESA id of entry if found, 0 otherwise
Definition at line 73 of file tkm_kernel_sad.h.
Referenced by METHOD(), and START_TEST().
bool(* tkm_kernel_sad_t::insert)(tkm_kernel_sad_t *const this, const esa_id_type esa_id, const u_int32_t reqid, const host_t *const src, const host_t *const dst, const u_int32_t spi_loc, const u_int32_t spi_rem, const u_int8_t proto)
Insert new SAD entry with specified parameters.
Parameters
esa_id ESP SA context identifier
reqid reqid of the SA
src source address of CHILD SA
dst destination address of CHILD SA
spi_loc Local SPI of CHILD SA
spi_rem Remote SPI of CHILD SA
proto protocol of CHILD SA (ESP/AH)
Returns
TRUE if entry was inserted, FALSE otherwise
Definition at line 48 of file tkm_kernel_sad.h.
Referenced by METHOD(), and START_TEST().
bool(* tkm_kernel_sad_t::remove)(tkm_kernel_sad_t *const this, const esa_id_type esa_id)
Remove entry with given ESA id from SAD.
Parameters
esa_id ESA identifier of entry to remove
Returns
TRUE if entry was removed, FALSE otherwise
Definition at line 93 of file tkm_kernel_sad.h.
Referenced by METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
tkm_kernel_sad.h