strongSwan: traffic_selector_substructure
traffic_selector_substructure
payloads
Classes
struct traffic_selector_substructure_t
Typedefs
typedef struct
traffic_selector_substructure_t traffic_selector_substructure_t
Functions
traffic_selector_substructure_t * traffic_selector_substructure_create (void)
traffic_selector_substructure_t * traffic_selector_substructure_create_from_traffic_selector (traffic_selector_t *traffic_selector)
Detailed Description
Typedef Documentation
typedef struct traffic_selector_substructure_t traffic_selector_substructure_t
Definition at line 25 of file traffic_selector_substructure.h.
Function Documentation
traffic_selector_substructure_t* traffic_selector_substructure_create (void)
Creates an empty traffic_selector_substructure_t object.
TS type is set to default TS_IPV4_ADDR_RANGE!
Returns
traffic_selector_substructure_t object
Definition at line 211 of file traffic_selector_substructure.c.
References INIT, and TS_IPV4_ADDR_RANGE.
Referenced by payload_create(), and traffic_selector_substructure_create_from_traffic_selector().
 {
     private_traffic_selector_substructure_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_traffic_selector = _get_traffic_selector,
             .destroy = _destroy,
         },
         .payload_length = get_header_length(this),
         /* must be set to be valid */
         .ts_type = TS_IPV4_ADDR_RANGE,
     );
     return &this->public;
 }
traffic_selector_substructure_t* traffic_selector_substructure_create_from_traffic_selector (traffic_selector_t * traffic_selector)
Creates an initialized traffif selector substructure using the values from a traffic_selector_t.
Parameters
traffic_selector traffic_selector_t to use for initialization
Returns
traffic_selector_substructure_t object
Definition at line 240 of file traffic_selector_substructure.c.
References chunk_clone, traffic_selector_t::get_from_address, traffic_selector_t::get_from_port, traffic_selector_t::get_protocol, traffic_selector_t::get_to_address, traffic_selector_t::get_to_port, traffic_selector_t::get_type, and traffic_selector_substructure_create().
Referenced by ts_payload_create_from_traffic_selectors().
 {
     private_traffic_selector_substructure_t *this;
     this = (private_traffic_selector_substructure_t*)traffic_selector_substructure_create();
     this->ts_type = ts->get_type(ts);
     this->ip_protocol_id = ts->get_protocol(ts);
     this->start_port = ts->get_from_port(ts);
     this->end_port = ts->get_to_port(ts);
     this->starting_address = chunk_clone(ts->get_from_address(ts));
     this->ending_address = chunk_clone(ts->get_to_address(ts));
     this->payload_length = get_header_length(this) +
                         this->ending_address.len + this->starting_address.len;
     return &this->public;
 }