strongSwan: random_plugin
random_plugin
random
Classes
struct random_plugin_t
Typedefs
typedef struct random_plugin_t random_plugin_t
Functions
int random_plugin_get_dev_random ()
int random_plugin_get_dev_urandom ()
bool random_plugin_get_strong_equals_true ()
Detailed Description
Typedef Documentation
typedef struct random_plugin_t random_plugin_t
Definition at line 29 of file random_plugin.h.
Function Documentation
int random_plugin_get_dev_random ()
Get the /dev/random file descriptor
See header.
Definition at line 60 of file random_plugin.c.
References dev_random.
Referenced by random_rng_create().
 {
     return dev_random;
 }
int random_plugin_get_dev_urandom ()
Get the /dev/urandom file descriptor
See header.
Definition at line 68 of file random_plugin.c.
References dev_urandom.
Referenced by random_rng_create().
 {
     return dev_urandom;
 }
bool random_plugin_get_strong_equals_true ()
Must strong randomness be equivalent to true randomness?
See header.
Definition at line 76 of file random_plugin.c.
References strong_equals_true.
Referenced by random_rng_create().
 {
     return strong_equals_true;
 }