strongSwan: tls.c File Reference
tls.c File Reference
#include "tls.h"
#include <utils/debug.h>
#include "tls_protection.h"
#include "tls_compression.h"
#include "tls_fragmentation.h"
#include "tls_crypto.h"
#include "tls_server.h"
#include "tls_peer.h"
Classes
struct private_tls_t
Typedefs
typedef struct private_tls_t private_tls_t
Functions
ENUM_BEGIN (tls_version_names, SSL_2_0, SSL_2_0,"SSLv2")
ENUM_NEXT (tls_version_names, SSL_3_0, TLS_1_2, SSL_2_0,"SSLv3","TLS 1.0","TLS 1.1","TLS 1.2")
ENUM_END (tls_version_names, TLS_1_2)
ENUM (tls_content_type_names, TLS_CHANGE_CIPHER_SPEC, TLS_APPLICATION_DATA,"ChangeCipherSpec","Alert","Handshake","ApplicationData",)
ENUM_BEGIN (tls_handshake_type_names, TLS_HELLO_REQUEST, TLS_SERVER_HELLO,"HelloRequest","ClientHello","ServerHello")
ENUM_NEXT (tls_handshake_type_names, TLS_CERTIFICATE, TLS_CLIENT_KEY_EXCHANGE, TLS_SERVER_HELLO,"Certificate","ServerKeyExchange","CertificateRequest","ServerHelloDone","CertificateVerify","ClientKeyExchange")
ENUM_NEXT (tls_handshake_type_names, TLS_FINISHED, TLS_FINISHED, TLS_CLIENT_KEY_EXCHANGE,"Finished")
ENUM_END (tls_handshake_type_names, TLS_FINISHED)
ENUM_BEGIN (tls_extension_names, TLS_EXT_SERVER_NAME, TLS_EXT_STATUS_REQUEST,"server name","max fragment length","client certificate url","trusted ca keys","truncated hmac","status request")
ENUM_NEXT (tls_extension_names, TLS_EXT_ELLIPTIC_CURVES, TLS_EXT_EC_POINT_FORMATS, TLS_EXT_STATUS_REQUEST,"elliptic curves","ec point formats")
ENUM_NEXT (tls_extension_names, TLS_EXT_SIGNATURE_ALGORITHMS, TLS_EXT_SIGNATURE_ALGORITHMS, TLS_EXT_EC_POINT_FORMATS,"signature algorithms")
ENUM_NEXT (tls_extension_names, TLS_EXT_RENEGOTIATION_INFO, TLS_EXT_RENEGOTIATION_INFO, TLS_EXT_SIGNATURE_ALGORITHMS,"renegotiation info")
ENUM_END (tls_extension_names, TLS_EXT_RENEGOTIATION_INFO)
struct __attribute__ ((packed))
void libtls_init (void)
METHOD (tls_t, process, status_t, private_tls_t *this, void *buf, size_t buflen)
METHOD (tls_t, build, status_t, private_tls_t *this, void *buf, size_t *buflen, size_t *msglen)
METHOD (tls_t, is_server, bool, private_tls_t *this)
METHOD (tls_t, get_server_id, identification_t *, private_tls_t *this)
METHOD (tls_t, get_peer_id, identification_t *, private_tls_t *this)
METHOD (tls_t, get_version, tls_version_t, private_tls_t *this)
METHOD (tls_t, set_version, bool, private_tls_t *this, tls_version_t version)
METHOD (tls_t, get_purpose, tls_purpose_t, private_tls_t *this)
METHOD (tls_t, is_complete, bool, private_tls_t *this)
METHOD (tls_t, get_eap_msk, chunk_t, private_tls_t *this)
METHOD (tls_t, get_auth, auth_cfg_t *, private_tls_t *this)
METHOD (tls_t, destroy, void, private_tls_t *this)
tls_t * tls_create (bool is_server, identification_t *server, identification_t *peer, tls_purpose_t purpose, tls_application_t *application, tls_cache_t *cache)
Variables
tls_record_t
Typedef Documentation
typedef struct private_tls_t private_tls_t
Definition at line 92 of file tls.c.
Function Documentation
ENUM (tls_content_type_names , TLS_CHANGE_CIPHER_SPEC , TLS_APPLICATION_DATA , "ChangeCipherSpec" , "Alert" , "Handshake" , "ApplicationData")
ENUM_BEGIN (tls_version_names , SSL_2_0 , SSL_2_0 , "SSLv2")
ENUM_BEGIN (tls_handshake_type_names , TLS_HELLO_REQUEST , TLS_SERVER_HELLO , "HelloRequest" , "ClientHello" , "ServerHello")
ENUM_BEGIN (tls_extension_names , TLS_EXT_SERVER_NAME , TLS_EXT_STATUS_REQUEST , "server name" , "max fragment length" , "client certificate url" , "trusted ca keys" , "truncated hmac" , "status request")
ENUM_END (tls_version_names , TLS_1_2)
ENUM_END (tls_handshake_type_names , TLS_FINISHED)
ENUM_END (tls_extension_names , TLS_EXT_RENEGOTIATION_INFO)
ENUM_NEXT (tls_version_names , SSL_3_0 , TLS_1_2 , SSL_2_0 , "SSLv3" , "TLS 1.0" , "TLS 1.1" , "TLS 1.2")
ENUM_NEXT (tls_handshake_type_names , TLS_CERTIFICATE , TLS_CLIENT_KEY_EXCHANGE , TLS_SERVER_HELLO , "Certificate" , "ServerKeyExchange" , "CertificateRequest" , "ServerHelloDone" , "CertificateVerify" , "ClientKeyExchange")
ENUM_NEXT (tls_handshake_type_names , TLS_FINISHED , TLS_FINISHED , TLS_CLIENT_KEY_EXCHANGE , "Finished")
ENUM_NEXT (tls_extension_names , TLS_EXT_ELLIPTIC_CURVES , TLS_EXT_EC_POINT_FORMATS , TLS_EXT_STATUS_REQUEST , "elliptic curves" , "ec point formats")
ENUM_NEXT (tls_extension_names , TLS_EXT_SIGNATURE_ALGORITHMS , TLS_EXT_SIGNATURE_ALGORITHMS , TLS_EXT_EC_POINT_FORMATS , "signature algorithms")
ENUM_NEXT (tls_extension_names , TLS_EXT_RENEGOTIATION_INFO , TLS_EXT_RENEGOTIATION_INFO , TLS_EXT_SIGNATURE_ALGORITHMS , "renegotiation info")
METHOD (tls_t , process , status_t , private_tls_t * this, void * buf, size_t buflen)
Definition at line 193 of file tls.c.
References chunk_alloc, chunk_create(), chunk_free(), DBG2, DBG_TLS, len, memcpy, min, NEED_MORE, status, tls_content_type_names, tls_record_t, and untoh16().
 {
     tls_record_t *record;
     status_t status;
     u_int len;
     if (this->headpos)
     {   /* have a partial TLS record header, try to complete it */
         len = min(buflen, sizeof(this->head) - this->headpos);
         memcpy(((char*)&this->head) + this->headpos, buf, len);
         this->headpos += len;
         buflen -= len;
         buf += len;
         if (this->headpos == sizeof(this->head))
         {   /* header complete, allocate space with new header */
             len = untoh16(&this->head.length);
             this->input = chunk_alloc(len + sizeof(tls_record_t));
             memcpy(this->input.ptr, &this->head, sizeof(this->head));
             this->inpos = sizeof(this->head);
             this->headpos = 0;
         }
     }
     while (buflen)
     {
         if (this->input.len == 0)
         {
             while (buflen >= sizeof(tls_record_t))
             {
                 /* try to process records inline */
                 record = buf;
                 len = untoh16(&record->length);
                 if (len + sizeof(tls_record_t) > buflen)
                 {   /* not a full record, read to buffer */
                     this->input = chunk_alloc(len + sizeof(tls_record_t));
                     this->inpos = 0;
                     break;
                 }
                 DBG2(DBG_TLS, "processing TLS %N record (%d bytes)",
                      tls_content_type_names, record->type, len);
                 status = this->protection->process(this->protection,
                                 record->type, chunk_create(record->data, len));
                 if (status != NEED_MORE)
                 {
                     return status;
                 }
                 buf += len + sizeof(tls_record_t);
                 buflen -= len + sizeof(tls_record_t);
                 if (buflen == 0)
                 {
                     return NEED_MORE;
                 }
             }
             if (buflen < sizeof(tls_record_t))
             {
                 DBG2(DBG_TLS, "received incomplete TLS record header");
                 memcpy(&this->head, buf, buflen);
                 this->headpos = buflen;
                 break;
             }
         }
         len = min(buflen, this->input.len - this->inpos);
         memcpy(this->input.ptr + this->inpos, buf, len);
         buf += len;
         buflen -= len;
         this->inpos += len;
         DBG2(DBG_TLS, "buffering %d bytes, %d bytes of %d byte TLS record received",
              len, this->inpos, this->input.len);
         if (this->input.len == this->inpos)
         {
             record = (tls_record_t*)this->input.ptr;
             len = untoh16(&record->length);
             DBG2(DBG_TLS, "processing buffered TLS %N record (%d bytes)",
                  tls_content_type_names, record->type, len);
             status = this->protection->process(this->protection,
                                 record->type, chunk_create(record->data, len));
             chunk_free(&this->input);
             this->inpos = 0;
             if (status != NEED_MORE)
             {
                 return status;
             }
         }
     }
     return NEED_MORE;
 }
METHOD (tls_t , build , status_t , private_tls_t * this, void * buf, size_t * buflen, size_t * msglen)
Definition at line 283 of file tls.c.
References ALREADY_DONE, chunk_cat, chunk_free(), chunk_from_thing, data, DBG2, DBG_TLS, htoun16(), INVALID_STATE, chunk_t::len, len, memcpy, min, NEED_MORE, status, tls_content_type_names, tls_record_t, TRUE, and type.
 {
     tls_content_type_t type;
     tls_record_t record;
     status_t status;
     chunk_t data;
     size_t len;
     len = *buflen;
     if (this->output.len == 0)
     {
         /* query upper layers for new records, as many as we can get */
         while (TRUE)
         {
             status = this->protection->build(this->protection, &type, &data);
             switch (status)
             {
                 case NEED_MORE:
                     record.type = type;
                     htoun16(&record.version, this->version);
                     htoun16(&record.length, data.len);
                     this->output = chunk_cat("mcm", this->output,
                                              chunk_from_thing(record), data);
                     DBG2(DBG_TLS, "sending TLS %N record (%d bytes)",
                          tls_content_type_names, type, data.len);
                     continue;
                 case INVALID_STATE:
                     if (this->output.len == 0)
                     {
                         return INVALID_STATE;
                     }
                     break;
                 default:
                     return status;
             }
             break;
         }
         if (msglen)
         {
             *msglen = this->output.len;
         }
     }
     else
     {
         if (msglen)
         {
             *msglen = 0;
         }
     }
     len = min(len, this->output.len - this->outpos);
     memcpy(buf, this->output.ptr + this->outpos, len);
     this->outpos += len;
     *buflen = len;
     if (this->outpos == this->output.len)
     {
         chunk_free(&this->output);
         this->outpos = 0;
         return ALREADY_DONE;
     }
     return NEED_MORE;
 }
METHOD (tls_t , is_server , bool , private_tls_t * this)
Definition at line 346 of file tls.c.
 {
     return this->is_server;
 }
METHOD (tls_t , get_server_id , identification_t * , private_tls_t * this)
Definition at line 352 of file tls.c.
 {
     return this->handshake->get_server_id(this->handshake);
 }
METHOD (tls_t , get_peer_id , identification_t * , private_tls_t * this)
Definition at line 358 of file tls.c.
 {
     return this->handshake->get_peer_id(this->handshake);
 }
METHOD (tls_t , get_version , tls_version_t , private_tls_t * this)
Definition at line 364 of file tls.c.
References version.
 {
     return this->version;
 }
METHOD (tls_t , set_version , bool , private_tls_t * this, tls_version_t version)
Definition at line 370 of file tls.c.
References FALSE, SSL_2_0, SSL_3_0, TLS_1_0, TLS_1_1, TLS_1_2, TRUE, and version.
 {
     if (version > this->version)
     {
         return FALSE;
     }
     switch (version)
     {
         case TLS_1_0:
         case TLS_1_1:
         case TLS_1_2:
             this->version = version;
             this->protection->set_version(this->protection, version);
             return TRUE;
         case SSL_2_0:
         case SSL_3_0:
         default:
             return FALSE;
     }
 }
METHOD (tls_t , get_purpose , tls_purpose_t , private_tls_t * this)
Definition at line 392 of file tls.c.
 {
     return this->purpose;
 }
METHOD (tls_t , is_complete , bool , private_tls_t * this)
Definition at line 398 of file tls.c.
References FALSE, and TRUE.
 {
     if (this->handshake->finished(this->handshake))
     {
         if (!this->application)
         {
             return TRUE;
         }
         return this->fragmentation->application_finished(this->fragmentation);
     }
     return FALSE;
 }
METHOD (tls_t , get_eap_msk , chunk_t , private_tls_t * this)
Definition at line 412 of file tls.c.
 {
     return this->crypto->get_eap_msk(this->crypto);
 }
METHOD (tls_t , get_auth , auth_cfg_t * , private_tls_t * this)
Definition at line 418 of file tls.c.
 {
     return this->handshake->get_auth(this->handshake);
 }
METHOD (tls_t , destroy , void , private_tls_t * this)
Definition at line 424 of file tls.c.
References DESTROY_IF, and free().
 {
     this->protection->destroy(this->protection);
     this->compression->destroy(this->compression);
     this->fragmentation->destroy(this->fragmentation);
     this->crypto->destroy(this->crypto);
     this->handshake->destroy(this->handshake);
     DESTROY_IF(this->application);
     this->alert->destroy(this->alert);
     free(this->input.ptr);
     free(this->output.ptr);
     free(this);
 }
Variable Documentation
tls_record_t
Definition at line 90 of file tls.c.
Referenced by METHOD().