strongSwan: auth_filter.c File Reference
auth_filter.c File Reference
#include "auth_filter.h"
#include <utils/debug.h>
Classes
struct private_auth_filter_t
Typedefs
typedef struct
private_auth_filter_t private_auth_filter_t
Functions
METHOD (fast_filter_t, run, bool, private_auth_filter_t *this, fast_request_t *request, char *controller, char *action, char *p2, char *p3, char *p4, char *p5)
METHOD (fast_filter_t, destroy, void, private_auth_filter_t *this)
fast_filter_t * auth_filter_create (user_t *user, database_t *db)
Typedef Documentation
typedef struct private_auth_filter_t private_auth_filter_t
Definition at line 21 of file auth_filter.c.
Function Documentation
METHOD (fast_filter_t , run , bool , private_auth_filter_t * this, fast_request_t * request, char * controller, char * action, char * p2, char * p3, char * p4, char * p5)
Definition at line 43 of file auth_filter.c.
References db, DB_INT, DB_TEXT, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, FALSE, login(), database_t::query, query(), fast_request_t::redirect, fast_request_t::set, streq(), and TRUE.
 {
     if (this->user->get_user(this->user))
     {
         enumerator_t *query;
         char *login;
         query = this->db->query(this->db, "SELECT login FROM user WHERE id = ?",
                                 DB_INT, this->user->get_user(this->user),
                                 DB_TEXT);
         if (query && query->enumerate(query, &login))
         {
             request->set(request, "login", login);
             query->destroy(query);
             return TRUE;
         }
         DESTROY_IF(query);
         this->user->set_user(this->user, 0);
     }
     if (controller && streq(controller, "user") && action &&
         (streq(action, "add") || streq(action, "login") || streq(action, "help")))
     {   /* add/login allowed */
         return TRUE;
     }
     request->redirect(request, "user/login");
     return FALSE;
 }
METHOD (fast_filter_t , destroy , void , private_auth_filter_t * this)
Definition at line 73 of file auth_filter.c.
References free().
 {
     free(this);
 }