strongSwan: ike_config
ike_config
tasks
Classes
struct ike_config_t
Typedefs
typedef struct ike_config_t ike_config_t
Functions
ike_config_t * ike_config_create (ike_sa_t *ike_sa, bool initiator)
Detailed Description
Typedef Documentation
typedef struct ike_config_t ike_config_t
Definition at line 24 of file ike_config.h.
Function Documentation
ike_config_t* ike_config_create (ike_sa_t * ike_sa, bool initiator)
Create a new ike_config task.
Parameters
ike_sa IKE_SA this task works for
initiator TRUE for initiator
Returns
ike_config task to handle by the task_manager
Definition at line 480 of file ike_config.c.
References INIT, initiator, and linked_list_create().
Referenced by METHOD(), and process_request().
 {
     private_ike_config_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
         },
         .initiator = initiator,
         .ike_sa = ike_sa,
         .vips = linked_list_create(),
         .requested = linked_list_create(),
     );
     if (initiator)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
     }
     return &this->public;
 }