strongSwan: kernel_wfp_ipsec.c File Reference
kernel_wfp_ipsec.c File Reference
#include "kernel_wfp_compat.h"
#include "kernel_wfp_ipsec.h"
#include <daemon.h>
#include <hydra.h>
#include <threading/mutex.h>
#include <collections/array.h>
#include <collections/hashtable.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_kernel_wfp_ipsec_t
struct sa_entry_t
struct sp_entry_t
struct entry_t
struct route_t
struct trap_t
struct expire_data_t
Macros
#define _WIN32_WINNT 0x0601
#define IPPROTO_IPIP 4
#define IPPROTO_IPV6 41
Typedefs
typedef struct
private_kernel_wfp_ipsec_t private_kernel_wfp_ipsec_t
Functions
static u_int hash_sa (sa_entry_t *key)
static bool equals_sa (sa_entry_t *a, sa_entry_t *b)
static void sp_entry_destroy (sp_entry_t *sp)
static void destroy_route (route_t *this)
static bool equals_route (route_t *a, route_t *b)
static u_int hash_route (route_t *route)
static bool manage_routes (private_kernel_wfp_ipsec_t *this, entry_t *entry, bool add)
static void cleanup_policies (private_kernel_wfp_ipsec_t *this, entry_t *entry)
static void entry_destroy (private_kernel_wfp_ipsec_t *this, entry_t *entry)
static FWPM_FILTER_CONDITION0 * append_condition (FWPM_FILTER_CONDITION0 *conds[], int *count)
static u_int32_t prefix2mask (u_int8_t prefix)
static void range2cond (FWPM_FILTER_CONDITION0 *cond, u_int16_t from, u_int16_t to)
static bool ts2condition (traffic_selector_t *ts, const GUID *target, FWPM_FILTER_CONDITION0 *conds[], int *count)
static void free_condition (FWP_DATA_TYPE type, void *value)
static void free_conditions (FWPM_FILTER_CONDITION0 *conds, int count)
static bool find_callout (bool tunnel, bool v6, bool inbound, bool forward, bool ale, GUID *layer, GUID *sublayer, GUID *callout)
static bool install_sp (private_kernel_wfp_ipsec_t *this, sp_entry_t *sp, GUID *context, bool inbound, bool fwd, UINT64 *filter_id)
static bool install_ipip_ale (private_kernel_wfp_ipsec_t *this, host_t *local, host_t *remote, GUID *context, bool inbound, int proto, u_int64_t *filter_id)
static bool install_sps (private_kernel_wfp_ipsec_t *this, entry_t *entry, GUID *context)
static FWP_BYTE_BLOB chunk2blob (chunk_t chunk)
static bool alg2auth (integrity_algorithm_t alg, IPSEC_SA_AUTH_INFORMATION0 *info)
static bool alg2cipher (encryption_algorithm_t alg, int keylen, IPSEC_SA_CIPHER_INFORMATION0 *info)
static integrity_algorithm_t encr2integ (encryption_algorithm_t encr, int keylen)
static bool install_sa (private_kernel_wfp_ipsec_t *this, entry_t *entry, bool inbound, sa_entry_t *sa, FWP_IP_VERSION version)
static void host2address6 (host_t *host, void *out)
static bool hosts2traffic (private_kernel_wfp_ipsec_t *this, host_t *l, host_t *r, IPSEC_TRAFFIC1 *traffic)
static bool install_sas (private_kernel_wfp_ipsec_t *this, entry_t *entry, IPSEC_TRAFFIC_TYPE type)
static bool install_transport (private_kernel_wfp_ipsec_t *this, entry_t *entry)
static bool generate_guid (private_kernel_wfp_ipsec_t *this, GUID *guid)
static bool add_tunnel_provider (private_kernel_wfp_ipsec_t *this, entry_t *entry, GUID *guid, UINT64 *luid)
static bool install_tunnel_sps (private_kernel_wfp_ipsec_t *this, entry_t *entry)
static bool uninstall_route (private_kernel_wfp_ipsec_t *this, host_t *dst, u_int8_t mask, host_t *src, host_t *gtw)
static bool install_route (private_kernel_wfp_ipsec_t *this, host_t *dst, u_int8_t mask, host_t *src, host_t *gtw)
static bool manage_route (private_kernel_wfp_ipsec_t *this, host_t *local, host_t *remote, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, bool add)
static bool install_tunnel (private_kernel_wfp_ipsec_t *this, entry_t *entry)
static bool install (private_kernel_wfp_ipsec_t *this, entry_t *entry)
static void destroy_trap (trap_t *this)
static bool equals_trap (trap_t *a, trap_t *b)
static u_int hash_trap (trap_t *trap)
static void acquire (private_kernel_wfp_ipsec_t *this, UINT64 filter_id, traffic_selector_t *src, traffic_selector_t *dst)
static traffic_selector_t * addr2ts (FWP_IP_VERSION version, void *data, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
static void WINAPI event_callback (void *user, const FWPM_NET_EVENT1 *event)
static bool register_events (private_kernel_wfp_ipsec_t *this)
static bool install_trap (private_kernel_wfp_ipsec_t *this, trap_t *trap)
static bool uninstall_trap (private_kernel_wfp_ipsec_t *this, trap_t *trap)
static bool add_trap (private_kernel_wfp_ipsec_t *this, u_int32_t reqid, bool fwd, host_t *local, host_t *remote, traffic_selector_t *src, traffic_selector_t *dst)
static bool remove_trap (private_kernel_wfp_ipsec_t *this, u_int32_t reqid, bool fwd, traffic_selector_t *src, traffic_selector_t *dst)
METHOD (kernel_ipsec_t, get_features, kernel_feature_t, private_kernel_wfp_ipsec_t *this)
static bool init_spi (private_kernel_wfp_ipsec_t *this)
static u_int permute (u_int x, u_int p)
METHOD (kernel_ipsec_t, get_spi, status_t, private_kernel_wfp_ipsec_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
METHOD (kernel_ipsec_t, get_cpi, status_t, private_kernel_wfp_ipsec_t *this, host_t *src, host_t *dst, u_int16_t *cpi)
static void expire_data_destroy (expire_data_t *data)
static job_requeue_t expire_job (expire_data_t *data)
static void schedule_expire (private_kernel_wfp_ipsec_t *this, u_int32_t spi, host_t *dst, u_int32_t lifetime, bool hard)
METHOD (kernel_ipsec_t, add_sa, status_t, private_kernel_wfp_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t *src_ts, linked_list_t *dst_ts)
METHOD (kernel_ipsec_t, update_sa, status_t, private_kernel_wfp_ipsec_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
METHOD (kernel_ipsec_t, query_sa, status_t, private_kernel_wfp_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
METHOD (kernel_ipsec_t, del_sa, status_t, private_kernel_wfp_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
METHOD (kernel_ipsec_t, flush_sas, status_t, private_kernel_wfp_ipsec_t *this)
METHOD (kernel_ipsec_t, add_policy, status_t, private_kernel_wfp_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_ipsec_t, query_policy, status_t, private_kernel_wfp_ipsec_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, mark_t mark, time_t *use_time)
METHOD (kernel_ipsec_t, del_policy, status_t, private_kernel_wfp_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_ipsec_t, flush_policies, status_t, private_kernel_wfp_ipsec_t *this)
static bool add_bypass (private_kernel_wfp_ipsec_t *this, int family, u_int16_t port, bool inbound, UINT64 *luid)
METHOD (kernel_ipsec_t, bypass_socket, bool, private_kernel_wfp_ipsec_t *this, int fd, int family)
METHOD (kernel_ipsec_t, enable_udp_decap, bool, private_kernel_wfp_ipsec_t *this, int fd, int family, u_int16_t port)
METHOD (kernel_ipsec_t, destroy, void, private_kernel_wfp_ipsec_t *this)
kernel_wfp_ipsec_t * kernel_wfp_ipsec_create ()
Macro Definition Documentation
#define _WIN32_WINNT 0x0601
Definition at line 17 of file kernel_wfp_ipsec.c.
#define IPPROTO_IPIP 4
Definition at line 29 of file kernel_wfp_ipsec.c.
Referenced by esp_packet_create_from_payload(), install_sps(), and process_inbound().
#define IPPROTO_IPV6 41
Definition at line 30 of file kernel_wfp_ipsec.c.
Referenced by esp_packet_create_from_payload(), install_sps(), METHOD(), open_socket(), open_tcp_socket(), open_udp_socket(), and process_inbound().
Typedef Documentation
typedef struct private_kernel_wfp_ipsec_t private_kernel_wfp_ipsec_t
Definition at line 32 of file kernel_wfp_ipsec.c.
Function Documentation
static void acquire (private_kernel_wfp_ipsec_t * this, UINT64 filter_id, traffic_selector_t * src, traffic_selector_t * dst) static
Send an acquire for an installed trap filter
Definition at line 1633 of file kernel_wfp_ipsec.c.
References kernel_interface_t::acquire, traffic_selector_t::clone, hydra, hydra_t::kernel_interface, key, mutex_t::lock, mutex, trap_t::reqid, and mutex_t::unlock.
Referenced by complete(), event_callback(), METHOD(), and process_acquire().
 {
     u_int32_t reqid = 0;
     trap_t *trap, key = {
         .filter_id = filter_id,
     };
     this->mutex->lock(this->mutex);
     trap = this->traps->get(this->traps, &key);
     if (trap)
     {
         reqid = trap->reqid;
     }
     this->mutex->unlock(this->mutex);
     if (reqid)
     {
         src = src ? src->clone(src) : NULL;
         dst = dst ? dst->clone(dst) : NULL;
         hydra->kernel_interface->acquire(hydra->kernel_interface, reqid,
                                          src, dst);
     }
 }
static bool add_bypass (private_kernel_wfp_ipsec_t * this, int family, u_int16_t port, bool inbound, UINT64 * luid) static
Add a bypass policy for a specific UDP port
Definition at line 2486 of file kernel_wfp_ipsec.c.
References append_condition(), count, DBG1, DBG_KNL, DWORD, FALSE, filter(), free_conditions(), FWPM_CONDITION_IP_LOCAL_PORT, FWPM_CONDITION_IP_PROTOCOL, FWPM_LAYER_INBOUND_TRANSPORT_V4, FWPM_LAYER_INBOUND_TRANSPORT_V6, FWPM_LAYER_OUTBOUND_TRANSPORT_V4, FWPM_LAYER_OUTBOUND_TRANSPORT_V6, handle, port, res, and TRUE.
Referenced by METHOD().
 {
     FWPM_FILTER_CONDITION0 *cond, *conds = NULL;
     int count = 0;
     DWORD res;
     UINT64 weight = 0xff00000000000000;
     FWPM_FILTER0 filter = {
         .displayData = {
             .name = L"charon IKE bypass",
         },
         .action = {
             .type = FWP_ACTION_PERMIT,
         },
         .weight = {
             .type = FWP_UINT64,
             .uint64 = &weight,
         },
     };
     switch (family)
     {
         case AF_INET:
             filter.layerKey = inbound ? FWPM_LAYER_INBOUND_TRANSPORT_V4
                                       : FWPM_LAYER_OUTBOUND_TRANSPORT_V4;
             break;
         case AF_INET6:
             filter.layerKey = inbound ? FWPM_LAYER_INBOUND_TRANSPORT_V6
                                       : FWPM_LAYER_OUTBOUND_TRANSPORT_V6;
             break;
         default:
             return FALSE;
     }
     cond = append_condition(&conds, &count);
     cond->fieldKey = FWPM_CONDITION_IP_PROTOCOL;
     cond->matchType = FWP_MATCH_EQUAL;
     cond->conditionValue.type = FWP_UINT8;
     cond->conditionValue.uint8 = IPPROTO_UDP;
     cond = append_condition(&conds, &count);
     cond->fieldKey = FWPM_CONDITION_IP_LOCAL_PORT;
     cond->matchType = FWP_MATCH_EQUAL;
     cond->conditionValue.type = FWP_UINT16;
     cond->conditionValue.uint16 = port;
     filter.numFilterConditions = count;
     filter.filterCondition = conds;
     res = FwpmFilterAdd0(this->handle, &filter, NULL, luid);
     free_conditions(conds, count);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "installing WFP bypass filter failed: 0x%08x", res);
         return FALSE;
     }
     return TRUE;
 }
static bool add_trap (private_kernel_wfp_ipsec_t * this, u_int32_t reqid, bool fwd, host_t * local, host_t * remote, traffic_selector_t * src, traffic_selector_t * dst) static
Create and install a new trap entry
Definition at line 1868 of file kernel_wfp_ipsec.c.
References host_t::clone, traffic_selector_t::clone, destroy_trap(), FALSE, INIT, install_trap(), mutex_t::lock, manage_route(), mutex, trap_t::route, TRUE, and mutex_t::unlock.
Referenced by METHOD().
 {
     trap_t *trap;
     INIT(trap,
         .reqid = reqid,
         .fwd = fwd,
         .src = src->clone(src),
         .dst = dst->clone(dst),
         .local = local->clone(local),
         .remote = remote->clone(remote),
     );
     if (!install_trap(this, trap))
     {
         destroy_trap(trap);
         return FALSE;
     }
     trap->route = manage_route(this, local, remote, src, dst, TRUE);
     this->mutex->lock(this->mutex);
     this->traps->put(this->traps, trap, trap);
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
static bool add_tunnel_provider (private_kernel_wfp_ipsec_t * this, entry_t * entry, GUID * guid, UINT64 * luid) static
Register a dummy tunnel provider to associate tunnel filters to
Definition at line 1285 of file kernel_wfp_ipsec.c.
References DBG1, DBG_KNL, DWORD, FALSE, generate_guid(), handle, host2address6(), IPSEC_AUTH_TRANSFORM_ID_HMAC_SHA_1_96, IPSEC_TRANSFORM_ESP_AUTH, entry_t::local, proposal, entry_t::remote, res, TRUE, and untoh32().
Referenced by install_tunnel_sps().
 {
     DWORD res;
     IPSEC_AUTH_TRANSFORM0 transform = {
         /* Create any valid proposal. This is actually not used, as we
          * don't create an SA from this information. */
         .authTransformId = IPSEC_AUTH_TRANSFORM_ID_HMAC_SHA_1_96,
     };
     IPSEC_SA_TRANSFORM0 transforms = {
         .ipsecTransformType = IPSEC_TRANSFORM_ESP_AUTH,
         .espAuthTransform = &transform,
     };
     IPSEC_PROPOSAL0 proposal = {
         .lifetime = {
             /* We need a valid lifetime, even if we don't create any SA
              * from these values. Pick some values accepted. */
             .lifetimeSeconds = 0xFFFF,
             .lifetimeKilobytes = 0xFFFFFFFF,
             .lifetimePackets = 0xFFFFFFFF,
         },
         .numSaTransforms = 1,
         .saTransforms = &transforms,
     };
     IPSEC_TUNNEL_POLICY0 policy = {
         .numIpsecProposals = 1,
         .ipsecProposals = &proposal,
         .saIdleTimeout = {
             /* not used, set to lifetime for maximum */
             .idleTimeoutSeconds = proposal.lifetime.lifetimeSeconds,
             .idleTimeoutSecondsFailOver = proposal.lifetime.lifetimeSeconds,
         },
     };
     FWPM_PROVIDER_CONTEXT0 qm = {
         .displayData = {
             .name = L"charon tunnel provider",
         },
         .providerKey = (GUID*)&this->provider.providerKey,
         .type = FWPM_IPSEC_IKE_QM_TUNNEL_CONTEXT,
         .ikeQmTunnelPolicy = &policy,
     };
     switch (entry->local->get_family(entry->local))
     {
         case AF_INET:
             policy.tunnelEndpoints.ipVersion = FWP_IP_VERSION_V4;
             policy.tunnelEndpoints.localV4Address =
                         untoh32(entry->local->get_address(entry->local).ptr);
             policy.tunnelEndpoints.remoteV4Address =
                         untoh32(entry->remote->get_address(entry->remote).ptr);
             break;
         case AF_INET6:
             policy.tunnelEndpoints.ipVersion = FWP_IP_VERSION_V6;
             host2address6(entry->local, &policy.tunnelEndpoints.localV6Address);
             host2address6(entry->remote, &policy.tunnelEndpoints.remoteV6Address);
             break;
         default:
             return FALSE;
     }
     if (!generate_guid(this, &qm.providerContextKey))
     {
         return FALSE;
     }
     res = FwpmProviderContextAdd0(this->handle, &qm, NULL, luid);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "adding provider context failed: 0x%08x", res);
         return FALSE;
     }
     *guid = qm.providerContextKey;
     return TRUE;
 }
static traffic_selector_t* addr2ts (FWP_IP_VERSION version, void * data, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port) static
Create a single host traffic selector from an FWP address definition
Definition at line 1661 of file kernel_wfp_ipsec.c.
References addr, chunk_from_thing, traffic_selector_create_from_bytes(), TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, type, and untoh32().
Referenced by event_callback().
 {
     ts_type_t type;
     UINT32 ints[4];
     chunk_t addr;
     switch (version)
     {
         case FWP_IP_VERSION_V4:
             ints[0] = untoh32(data);
             addr = chunk_from_thing(ints[0]);
             type = TS_IPV4_ADDR_RANGE;
             break;
         case FWP_IP_VERSION_V6:
             ints[3] = untoh32(data);
             ints[2] = untoh32(data + 4);
             ints[1] = untoh32(data + 8);
             ints[0] = untoh32(data + 12);
             addr = chunk_from_thing(ints);
             type = TS_IPV6_ADDR_RANGE;
             break;
         default:
             return NULL;
     }
     return traffic_selector_create_from_bytes(protocol, type, addr, from_port,
                                               addr, to_port);
 }
static bool alg2auth (integrity_algorithm_t alg, IPSEC_SA_AUTH_INFORMATION0 * info) static
Convert an integrity_algorithm_t to a WFP IPSEC_AUTH_TRANFORM_ID0
Definition at line 908 of file kernel_wfp_ipsec.c.
References alg, AUTH_AES_128_GMAC, AUTH_AES_192_GMAC, AUTH_AES_256_GMAC, AUTH_HMAC_MD5_96, AUTH_HMAC_SHA1_96, AUTH_HMAC_SHA2_256_128, countof, FALSE, IPSEC_AUTH_TRANSFORM_ID_GCM_AES_128, IPSEC_AUTH_TRANSFORM_ID_GCM_AES_192, IPSEC_AUTH_TRANSFORM_ID_GCM_AES_256, IPSEC_AUTH_TRANSFORM_ID_HMAC_MD5_96, IPSEC_AUTH_TRANSFORM_ID_HMAC_SHA_1_96, IPSEC_AUTH_TRANSFORM_ID_HMAC_SHA_256_128, and TRUE.
Referenced by install_sa().
 {
     struct {
         integrity_algorithm_t alg;
         IPSEC_AUTH_TRANSFORM_ID0 transform;
     } map[] = {
         { AUTH_HMAC_MD5_96,         IPSEC_AUTH_TRANSFORM_ID_HMAC_MD5_96     },
         { AUTH_HMAC_SHA1_96,        IPSEC_AUTH_TRANSFORM_ID_HMAC_SHA_1_96   },
         { AUTH_HMAC_SHA2_256_128,   IPSEC_AUTH_TRANSFORM_ID_HMAC_SHA_256_128},
         { AUTH_AES_128_GMAC,        IPSEC_AUTH_TRANSFORM_ID_GCM_AES_128     },
         { AUTH_AES_192_GMAC,        IPSEC_AUTH_TRANSFORM_ID_GCM_AES_192     },
         { AUTH_AES_256_GMAC,        IPSEC_AUTH_TRANSFORM_ID_GCM_AES_256     },
     };
     int i;
     for (i = 0; i < countof(map); i++)
     {
         if (map[i].alg == alg)
         {
             info->authTransform.authTransformId = map[i].transform;
             return TRUE;
         }
     }
     return FALSE;
 }
static bool alg2cipher (encryption_algorithm_t alg, int keylen, IPSEC_SA_CIPHER_INFORMATION0 * info) static
Convert an encryption_algorithm_t to a WFP IPSEC_CIPHER_TRANFORM_ID0
Definition at line 938 of file kernel_wfp_ipsec.c.
References alg, countof, ENCR_3DES, ENCR_AES_CBC, ENCR_AES_GCM_ICV16, ENCR_DES, FALSE, IPSEC_CIPHER_TRANSFORM_ID_AES_128, IPSEC_CIPHER_TRANSFORM_ID_AES_192, IPSEC_CIPHER_TRANSFORM_ID_AES_256, IPSEC_CIPHER_TRANSFORM_ID_CBC_3DES, IPSEC_CIPHER_TRANSFORM_ID_CBC_DES, IPSEC_CIPHER_TRANSFORM_ID_GCM_AES_128, IPSEC_CIPHER_TRANSFORM_ID_GCM_AES_192, IPSEC_CIPHER_TRANSFORM_ID_GCM_AES_256, and TRUE.
Referenced by install_sa().
 {
     struct {
         encryption_algorithm_t alg;
         int keylen;
         IPSEC_CIPHER_TRANSFORM_ID0 transform;
     } map[] = {
         { ENCR_DES,              8, IPSEC_CIPHER_TRANSFORM_ID_CBC_DES       },
         { ENCR_3DES,            24, IPSEC_CIPHER_TRANSFORM_ID_CBC_3DES      },
         { ENCR_AES_CBC,         16, IPSEC_CIPHER_TRANSFORM_ID_AES_128       },
         { ENCR_AES_CBC,         24, IPSEC_CIPHER_TRANSFORM_ID_AES_192       },
         { ENCR_AES_CBC,         32, IPSEC_CIPHER_TRANSFORM_ID_AES_256       },
         { ENCR_AES_GCM_ICV16,   20, IPSEC_CIPHER_TRANSFORM_ID_GCM_AES_128   },
         { ENCR_AES_GCM_ICV16,   28, IPSEC_CIPHER_TRANSFORM_ID_GCM_AES_192   },
         { ENCR_AES_GCM_ICV16,   36, IPSEC_CIPHER_TRANSFORM_ID_GCM_AES_256   },
     };
     int i;
     for (i = 0; i < countof(map); i++)
     {
         if (map[i].alg == alg && map[i].keylen == keylen)
         {
             info->cipherTransform.cipherTransformId = map[i].transform;
             return TRUE;
         }
     }
     return FALSE;
 }
static FWPM_FILTER_CONDITION0* append_condition (FWPM_FILTER_CONDITION0 * conds[], int * count) static
Append/Realloc a filter condition to an existing condition set
Definition at line 336 of file kernel_wfp_ipsec.c.
References memset.
Referenced by add_bypass(), and ts2condition().
 {
     FWPM_FILTER_CONDITION0 *cond;
     (*count)++;
     *conds = realloc(*conds, *count * sizeof(*cond));
     cond = *conds + *count - 1;
     memset(cond, 0, sizeof(*cond));
     return cond;
 }
static FWP_BYTE_BLOB chunk2blob (chunk_t chunk) inline static
Convert a chunk_t to a WFP FWP_BYTE_BLOB
Definition at line 897 of file kernel_wfp_ipsec.c.
References chunk_t::len, and chunk_t::ptr.
Referenced by install_sa().
 {
     return (FWP_BYTE_BLOB){
         .size = chunk.len,
         .data = chunk.ptr,
     };
 }
static void cleanup_policies (private_kernel_wfp_ipsec_t * this, entry_t * entry) static
Remove policies associated to an entry from kernel
Definition at line 256 of file kernel_wfp_ipsec.c.
References array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, handle, manage_routes(), entry_t::mode, MODE_TUNNEL, sp_entry_t::policy_fwd_in, sp_entry_t::policy_fwd_out, sp_entry_t::policy_in, sp_entry_t::policy_out, and entry_t::sps.
Referenced by entry_destroy(), install_transport(), and install_tunnel().
 {
     enumerator_t *enumerator;
     sp_entry_t *sp;
     if (entry->mode == MODE_TUNNEL)
     {
         manage_routes(this, entry, FALSE);
     }
     enumerator = array_create_enumerator(entry->sps);
     while (enumerator->enumerate(enumerator, &sp))
     {
         if (sp->policy_in)
         {
             FwpmFilterDeleteById0(this->handle, sp->policy_in);
             sp->policy_in = 0;
         }
         if (sp->policy_out)
         {
             FwpmFilterDeleteById0(this->handle, sp->policy_out);
             sp->policy_out = 0;
         }
         if (sp->policy_fwd_in)
         {
             FwpmFilterDeleteById0(this->handle, sp->policy_fwd_in);
             sp->policy_fwd_in = 0;
         }
         if (sp->policy_fwd_out)
         {
             FwpmFilterDeleteById0(this->handle, sp->policy_fwd_out);
             sp->policy_fwd_out = 0;
         }
     }
     enumerator->destroy(enumerator);
 }
static void destroy_route (route_t * this) static
Destroy a route_t
Definition at line 222 of file kernel_wfp_ipsec.c.
References DESTROY_IF, dst, free(), and src.
Referenced by install_route(), and uninstall_route().
 {
     this->dst->destroy(this->dst);
     this->src->destroy(this->src);
     DESTROY_IF(this->gtw);
     free(this);
 }
static void destroy_trap (trap_t * this) static
Destroy a trap entry
Definition at line 1605 of file kernel_wfp_ipsec.c.
References dst, free(), and src.
Referenced by add_trap(), and remove_trap().
 {
     this->local->destroy(this->local);
     this->remote->destroy(this->remote);
     this->src->destroy(this->src);
     this->dst->destroy(this->dst);
     free(this);
 }
static integrity_algorithm_t encr2integ (encryption_algorithm_t encr, int keylen) static
Get the integrity algorithm used for an AEAD transform
Definition at line 971 of file kernel_wfp_ipsec.c.
References AUTH_AES_128_GMAC, AUTH_AES_192_GMAC, AUTH_AES_256_GMAC, AUTH_UNDEFINED, countof, ENCR_AES_GCM_ICV16, ENCR_NULL_AUTH_AES_GMAC, and integ.
Referenced by install_sa().
 {
     struct {
         encryption_algorithm_t encr;
         int keylen;
         integrity_algorithm_t integ;
     } map[] = {
         { ENCR_NULL_AUTH_AES_GMAC,      20, AUTH_AES_128_GMAC               },
         { ENCR_NULL_AUTH_AES_GMAC,      28, AUTH_AES_192_GMAC               },
         { ENCR_NULL_AUTH_AES_GMAC,      36, AUTH_AES_256_GMAC               },
         { ENCR_AES_GCM_ICV16,           20, AUTH_AES_128_GMAC               },
         { ENCR_AES_GCM_ICV16,           28, AUTH_AES_192_GMAC               },
         { ENCR_AES_GCM_ICV16,           36, AUTH_AES_256_GMAC               },
     };
     int i;
     for (i = 0; i < countof(map); i++)
     {
         if (map[i].encr == encr && map[i].keylen == keylen)
         {
             return map[i].integ;
         }
     }
     return AUTH_UNDEFINED;
 }
static void entry_destroy (private_kernel_wfp_ipsec_t * this, entry_t * entry) static
Destroy a SA/SP entry set
Definition at line 296 of file kernel_wfp_ipsec.c.
References array_destroy_function(), chunk_clear(), cleanup_policies(), linked_list_t::destroy, sa_entry_t::encr, free(), handle, sa_entry_t::integ, entry_t::ip_ipv4_in, entry_t::ip_ipv4_out, entry_t::ip_ipv6_in, entry_t::ip_ipv6_out, entry_t::isa, sa_entry_t::key, entry_t::local, entry_t::osa, entry_t::provider, entry_t::remote, entry_t::sa_id, sp_entry_destroy(), and entry_t::sps.
Referenced by expire_job(), and METHOD().
 {
     if (entry->ip_ipv4_in)
     {
         FwpmFilterDeleteById0(this->handle, entry->ip_ipv4_in);
     }
     if (entry->ip_ipv4_out)
     {
         FwpmFilterDeleteById0(this->handle, entry->ip_ipv4_out);
     }
     if (entry->ip_ipv6_in)
     {
         FwpmFilterDeleteById0(this->handle, entry->ip_ipv6_in);
     }
     if (entry->ip_ipv6_out)
     {
         FwpmFilterDeleteById0(this->handle, entry->ip_ipv6_out);
     }
     if (entry->sa_id)
     {
         IPsecSaContextDeleteById0(this->handle, entry->sa_id);
     }
     if (entry->provider)
     {
         FwpmProviderContextDeleteById0(this->handle, entry->provider);
     }
     cleanup_policies(this, entry);
     array_destroy_function(entry->sps, (void*)sp_entry_destroy, NULL);
     entry->local->destroy(entry->local);
     entry->remote->destroy(entry->remote);
     chunk_clear(&entry->isa.integ.key);
     chunk_clear(&entry->isa.encr.key);
     chunk_clear(&entry->osa.integ.key);
     chunk_clear(&entry->osa.encr.key);
     free(entry);
 }
static bool equals_route (route_t * a, route_t * b) static
Hashtable equals function for routes
Definition at line 233 of file kernel_wfp_ipsec.c.
References route_t::dst, host_t::ip_equals, route_t::mask, and route_t::src.
Referenced by kernel_wfp_ipsec_create().
 {
     return a->mask == b->mask &&
            a->dst->ip_equals(a->dst, b->dst) &&
            a->src->ip_equals(a->src, b->src);
 }
static bool equals_sa (sa_entry_t * a, sa_entry_t * b) static
equals function for sas lookup table
Definition at line 134 of file kernel_wfp_ipsec.c.
References sa_entry_t::dst, host_t::ip_equals, and sa_entry_t::spi.
Referenced by kernel_wfp_ipsec_create().
 {
     return a->spi == b->spi && a->dst->ip_equals(a->dst, b->dst);
 }
static bool equals_trap (trap_t * a, trap_t * b) static
Hashtable equals function for traps
Definition at line 1617 of file kernel_wfp_ipsec.c.
References trap_t::filter_id.
Referenced by kernel_wfp_ipsec_create().
 {
     return a->filter_id == b->filter_id;
 }
static void WINAPI event_callback (void * user, const FWPM_NET_EVENT1 * event) static
FwpmNetEventSubscribe0() callback
Definition at line 1693 of file kernel_wfp_ipsec.c.
References acquire(), addr2ts(), DBG1, DBG_KNL, DESTROY_IF, FWPM_NET_EVENT_FLAG_IP_PROTOCOL_SET, FWPM_NET_EVENT_FLAG_LOCAL_ADDR_SET, FWPM_NET_EVENT_FLAG_LOCAL_PORT_SET, FWPM_NET_EVENT_FLAG_REMOTE_ADDR_SET, and protocol.
Referenced by register_events().
 {
     private_kernel_wfp_ipsec_t *this = user;
     traffic_selector_t *local = NULL, *remote = NULL;
     u_int8_t protocol = 0;
     u_int16_t from_local = 0, to_local = 65535;
     u_int16_t from_remote = 0, to_remote = 65535;
     if ((event->header.flags & FWPM_NET_EVENT_FLAG_LOCAL_ADDR_SET) &&
         (event->header.flags & FWPM_NET_EVENT_FLAG_REMOTE_ADDR_SET))
     {
         if (event->header.flags & FWPM_NET_EVENT_FLAG_LOCAL_PORT_SET)
         {
             from_local = to_local = event->header.localPort;
         }
         if (event->header.flags & FWPM_NET_EVENT_FLAG_LOCAL_PORT_SET)
         {
             from_remote = to_remote = event->header.remotePort;
         }
         if (event->header.flags & FWPM_NET_EVENT_FLAG_IP_PROTOCOL_SET)
         {
             protocol = event->header.ipProtocol;
         }
         local = addr2ts(event->header.ipVersion,
                         (void*)&event->header.localAddrV6,
                         protocol, from_local, to_local);
         remote = addr2ts(event->header.ipVersion,
                         (void*)&event->header.remoteAddrV6,
                         protocol, from_remote, to_remote);
     }
     switch (event->type)
     {
         case FWPM_NET_EVENT_TYPE_CLASSIFY_DROP:
             acquire(this, event->classifyDrop->filterId, local, remote);
             break;
         case FWPM_NET_EVENT_TYPE_IKEEXT_MM_FAILURE:
             DBG1(DBG_KNL, "WFP MM failure: %R === %R, 0x%08x, filterId %llu",
                  local, remote, event->ikeMmFailure->failureErrorCode,
                  event->ikeMmFailure->mmFilterId);
             break;
         case FWPM_NET_EVENT_TYPE_IKEEXT_QM_FAILURE:
             DBG1(DBG_KNL, "WFP QM failure: %R === %R, 0x%08x, filterId %llu",
                  local, remote, event->ikeQmFailure->failureErrorCode,
                  event->ikeQmFailure->qmFilterId);
             break;
         case FWPM_NET_EVENT_TYPE_IKEEXT_EM_FAILURE:
             DBG1(DBG_KNL, "WFP EM failure: %R === %R, 0x%08x, filterId %llu",
                  local, remote, event->ikeEmFailure->failureErrorCode,
                  event->ikeEmFailure->qmFilterId);
             break;
         case FWPM_NET_EVENT_TYPE_IPSEC_KERNEL_DROP:
             DBG1(DBG_KNL, "IPsec kernel drop: %R === %R, error 0x%08x, "
                  "SPI 0x%08x, %s filterId %llu", local, remote,
                  event->ipsecDrop->failureStatus, event->ipsecDrop->spi,
                  event->ipsecDrop->direction ? "in" : "out",
                  event->ipsecDrop->filterId);
             break;
         case FWPM_NET_EVENT_TYPE_IPSEC_DOSP_DROP:
         default:
             break;
     }
     DESTROY_IF(local);
     DESTROY_IF(remote);
 }
static void expire_data_destroy (expire_data_t * data) static
Clean up expire data
Definition at line 2023 of file kernel_wfp_ipsec.c.
References host_t::destroy, expire_data_t::dst, and free().
Referenced by schedule_expire().
 {
     data->dst->destroy(data->dst);
     free(data);
 }
static job_requeue_t expire_job (expire_data_t * data) static
Callback job for SA expiration
Definition at line 2032 of file kernel_wfp_ipsec.c.
References sa_entry_t::dst, expire_data_t::dst, entry_destroy(), kernel_interface_t::expire, expire_data_t::hard, hydra, entry_t::isa, JOB_REQUEUE_NONE, hydra_t::kernel_interface, key, mutex_t::lock, mutex, entry_t::osa, protocol, sa_entry_t::protocol, sa_entry_t::spi, expire_data_t::spi, expire_data_t::this, and mutex_t::unlock.
Referenced by schedule_expire().
 {
     private_kernel_wfp_ipsec_t *this = data->this;
     u_int8_t protocol;
     entry_t *entry = NULL;
     sa_entry_t key = {
         .spi = data->spi,
         .dst = data->dst,
     };
     if (data->hard)
     {
         this->mutex->lock(this->mutex);
         entry = this->isas->remove(this->isas, &key);
         this->mutex->unlock(this->mutex);
         if (entry)
         {
             protocol = entry->isa.protocol;
             if (entry->osa.dst)
             {
                 key.dst = entry->osa.dst;
                 key.spi = entry->osa.spi;
                 this->osas->remove(this->osas, &key);
             }
             entry_destroy(this, entry);
         }
     }
     else
     {
         this->mutex->lock(this->mutex);
         entry = this->isas->get(this->isas, &key);
         if (entry)
         {
             protocol = entry->isa.protocol;
         }
         this->mutex->unlock(this->mutex);
     }
     if (entry)
     {
         hydra->kernel_interface->expire(hydra->kernel_interface, protocol,
                                         data->spi, data->dst, data->hard);
     }
     return JOB_REQUEUE_NONE;
 }
static bool find_callout (bool tunnel, bool v6, bool inbound, bool forward, bool ale, GUID * layer, GUID * sublayer, GUID * callout) static
Find the callout GUID for given parameters
Definition at line 581 of file kernel_wfp_ipsec.c.
References countof, FALSE, FWPM_CALLOUT_IPSEC_ALE_CONNECT_V4, FWPM_CALLOUT_IPSEC_ALE_CONNECT_V6, FWPM_CALLOUT_IPSEC_FORWARD_INBOUND_TUNNEL_V4, FWPM_CALLOUT_IPSEC_FORWARD_INBOUND_TUNNEL_V6, FWPM_CALLOUT_IPSEC_FORWARD_OUTBOUND_TUNNEL_V4, FWPM_CALLOUT_IPSEC_FORWARD_OUTBOUND_TUNNEL_V6, FWPM_CALLOUT_IPSEC_INBOUND_TRANSPORT_V4, FWPM_CALLOUT_IPSEC_INBOUND_TRANSPORT_V6, FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_ALE_ACCEPT_V4, FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_ALE_ACCEPT_V6, FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_V4, FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_V6, FWPM_CALLOUT_IPSEC_OUTBOUND_TRANSPORT_V4, FWPM_CALLOUT_IPSEC_OUTBOUND_TRANSPORT_V6, FWPM_CALLOUT_IPSEC_OUTBOUND_TUNNEL_V4, FWPM_CALLOUT_IPSEC_OUTBOUND_TUNNEL_V6, FWPM_LAYER_ALE_AUTH_CONNECT_V4, FWPM_LAYER_ALE_AUTH_CONNECT_V6, FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4, FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V6, FWPM_LAYER_INBOUND_TRANSPORT_V4, FWPM_LAYER_INBOUND_TRANSPORT_V6, FWPM_LAYER_IPFORWARD_V4, FWPM_LAYER_IPFORWARD_V6, FWPM_LAYER_OUTBOUND_TRANSPORT_V4, FWPM_LAYER_OUTBOUND_TRANSPORT_V6, FWPM_SUBLAYER_IPSEC_FORWARD_OUTBOUND_TUNNEL, FWPM_SUBLAYER_IPSEC_TUNNEL, and TRUE.
Referenced by install_ipip_ale(), and install_sp().
 {
     struct {
         bool tunnel;
         bool v6;
         bool inbound;
         bool forward;
         bool ale;
         const GUID *layer;
         const GUID *sublayer;
         const GUID *callout;
     } map[] = {
         { 0, 0, 0, 0, 0,    &FWPM_LAYER_OUTBOUND_TRANSPORT_V4, NULL,
                             &FWPM_CALLOUT_IPSEC_OUTBOUND_TRANSPORT_V4       },
         { 0, 0, 1, 0, 0,    &FWPM_LAYER_INBOUND_TRANSPORT_V4, NULL,
                             &FWPM_CALLOUT_IPSEC_INBOUND_TRANSPORT_V4        },
         { 0, 1, 0, 0, 0,    &FWPM_LAYER_OUTBOUND_TRANSPORT_V6, NULL,
                             &FWPM_CALLOUT_IPSEC_OUTBOUND_TRANSPORT_V6       },
         { 0, 1, 1, 0, 0,    &FWPM_LAYER_INBOUND_TRANSPORT_V6, NULL,
                             &FWPM_CALLOUT_IPSEC_INBOUND_TRANSPORT_V6        },
         { 1, 0, 0, 0, 0,    &FWPM_LAYER_OUTBOUND_TRANSPORT_V4,
                             &FWPM_SUBLAYER_IPSEC_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_OUTBOUND_TUNNEL_V4          },
         { 1, 0, 0, 1, 0,    &FWPM_LAYER_IPFORWARD_V4,
                             &FWPM_SUBLAYER_IPSEC_FORWARD_OUTBOUND_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_FORWARD_OUTBOUND_TUNNEL_V4  },
         { 1, 0, 1, 0, 0,    &FWPM_LAYER_INBOUND_TRANSPORT_V4,
                             &FWPM_SUBLAYER_IPSEC_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_V4           },
         { 1, 0, 1, 1, 0,    &FWPM_LAYER_IPFORWARD_V4,
                             &FWPM_SUBLAYER_IPSEC_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_FORWARD_INBOUND_TUNNEL_V4   },
         { 1, 0, 0, 0, 1,    &FWPM_LAYER_ALE_AUTH_CONNECT_V4, NULL,
                             &FWPM_CALLOUT_IPSEC_ALE_CONNECT_V4              },
         { 1, 0, 1, 0, 1,    &FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4, NULL,
                             &FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_ALE_ACCEPT_V4},
         { 1, 1, 0, 0, 0,    &FWPM_LAYER_OUTBOUND_TRANSPORT_V6,
                             &FWPM_SUBLAYER_IPSEC_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_OUTBOUND_TUNNEL_V6          },
         { 1, 1, 0, 1, 0,    &FWPM_LAYER_IPFORWARD_V6,
                             &FWPM_SUBLAYER_IPSEC_FORWARD_OUTBOUND_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_FORWARD_OUTBOUND_TUNNEL_V6  },
         { 1, 1, 1, 0, 0,    &FWPM_LAYER_INBOUND_TRANSPORT_V6,
                             &FWPM_SUBLAYER_IPSEC_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_V6           },
         { 1, 1, 1, 1, 0,    &FWPM_LAYER_IPFORWARD_V6,
                             &FWPM_SUBLAYER_IPSEC_TUNNEL,
                             &FWPM_CALLOUT_IPSEC_FORWARD_INBOUND_TUNNEL_V6   },
         { 1, 1, 0, 0, 1,    &FWPM_LAYER_ALE_AUTH_CONNECT_V6, NULL,
                             &FWPM_CALLOUT_IPSEC_ALE_CONNECT_V6              },
         { 1, 1, 1, 0, 1,    &FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V6, NULL,
                             &FWPM_CALLOUT_IPSEC_INBOUND_TUNNEL_ALE_ACCEPT_V6},
     };
     int i;
     for (i = 0; i < countof(map); i++)
     {
         if (tunnel == map[i].tunnel &&
             v6 == map[i].v6 &&
             inbound == map[i].inbound &&
             forward == map[i].forward &&
             ale == map[i].ale)
         {
             *callout = *map[i].callout;
             *layer = *map[i].layer;
             if (map[i].sublayer)
             {
                 *sublayer = *map[i].sublayer;
             }
             return TRUE;
         }
     }
     return FALSE;
 }
static void free_condition (FWP_DATA_TYPE type, void * value) static
Free memory associated to a single condition
Definition at line 542 of file kernel_wfp_ipsec.c.
References free(), and value.
Referenced by free_conditions().
 {
     FWP_RANGE0 *range;
     switch (type)
     {
         case FWP_BYTE_ARRAY16_TYPE:
         case FWP_V4_ADDR_MASK:
         case FWP_V6_ADDR_MASK:
             free(value);
             break;
         case FWP_RANGE_TYPE:
             range = value;
             free_condition(range->valueLow.type, range->valueLow.sd);
             free_condition(range->valueHigh.type, range->valueHigh.sd);
             free(range);
             break;
         default:
             break;
     }
 }
static void free_conditions (FWPM_FILTER_CONDITION0 * conds, int count) static
Free memory used by a set of conditions
Definition at line 567 of file kernel_wfp_ipsec.c.
References count, free(), and free_condition().
Referenced by add_bypass(), install_ipip_ale(), install_sp(), and install_trap().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         free_condition(conds[i].conditionValue.type, conds[i].conditionValue.sd);
     }
     free(conds);
 }
static bool generate_guid (private_kernel_wfp_ipsec_t * this, GUID * guid) static
Generate a new GUID, random
Definition at line 1267 of file kernel_wfp_ipsec.c.
References crypto_factory_t::create_rng, library_t::crypto, rng_t::destroy, FALSE, rng_t::get_bytes, lib, ok, rng, and RNG_WEAK.
Referenced by add_tunnel_provider().
 {
     bool ok;
     rng_t *rng;
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng)
     {
         return FALSE;
     }
     ok = rng->get_bytes(rng, sizeof(GUID), (u_int8_t*)guid);
     rng->destroy(rng);
     return ok;
 }
static u_int hash_route (route_t * route) static
Hashtable hash function for routes
Definition at line 243 of file kernel_wfp_ipsec.c.
References chunk_hash_inc(), route_t::dst, host_t::get_address, route_t::mask, and route_t::src.
Referenced by kernel_wfp_ipsec_create().
 {
     return chunk_hash_inc(route->src->get_address(route->src),
             chunk_hash_inc(route->dst->get_address(route->dst), route->mask));
 }
static u_int hash_sa (sa_entry_t * key) static
Hash function for sas lookup table
Definition at line 125 of file kernel_wfp_ipsec.c.
References chunk_from_thing, chunk_hash(), chunk_hash_inc(), sa_entry_t::dst, host_t::get_address, and sa_entry_t::spi.
Referenced by kernel_wfp_ipsec_create().
 {
     return chunk_hash_inc(chunk_from_thing(key->spi),
                           chunk_hash(key->dst->get_address(key->dst)));
 }
static u_int hash_trap (trap_t * trap) static
Hashtable hash function for traps
Definition at line 1625 of file kernel_wfp_ipsec.c.
References chunk_from_thing, chunk_hash(), and trap_t::filter_id.
Referenced by kernel_wfp_ipsec_create().
 {
     return chunk_hash(chunk_from_thing(trap->filter_id));
 }
static void host2address6 (host_t * host, void * out) static
Convert an IPv6 host address to WFP representation
Definition at line 1101 of file kernel_wfp_ipsec.c.
References dst, host_t::get_address, out, chunk_t::ptr, src, and untoh32().
Referenced by add_tunnel_provider(), and hosts2traffic().
 {
     u_int32_t *src, *dst = out;
     src = (u_int32_t*)host->get_address(host).ptr;
     dst[0] = untoh32(&src[3]);
     dst[1] = untoh32(&src[2]);
     dst[2] = untoh32(&src[1]);
     dst[3] = untoh32(&src[0]);
 }
static bool hosts2traffic (private_kernel_wfp_ipsec_t * this, host_t * l, host_t * r, IPSEC_TRAFFIC1 * traffic) static
Fill in traffic structure from entry addresses
Definition at line 1116 of file kernel_wfp_ipsec.c.
References FALSE, host_t::get_address, host_t::get_family, host2address6(), chunk_t::ptr, TRUE, and untoh32().
Referenced by install_sas(), and METHOD().
 {
     if (l->get_family(l) != r->get_family(r))
     {
         return FALSE;
     }
     switch (l->get_family(l))
     {
         case AF_INET:
             traffic->ipVersion = FWP_IP_VERSION_V4;
             traffic->localV4Address = untoh32(l->get_address(l).ptr);
             traffic->remoteV4Address = untoh32(r->get_address(r).ptr);
             return TRUE;
         case AF_INET6:
             traffic->ipVersion = FWP_IP_VERSION_V6;
             host2address6(l, &traffic->localV6Address);
             host2address6(r, &traffic->remoteV6Address);
             return TRUE;
         default:
             return FALSE;
     }
 }
static bool init_spi (private_kernel_wfp_ipsec_t * this) static
Initialize seeds for SPI generation
Definition at line 1947 of file kernel_wfp_ipsec.c.
References crypto_factory_t::create_rng, library_t::crypto, rng_t::destroy, FALSE, rng_t::get_bytes, lib, ok, rng, RNG_STRONG, and TRUE.
Referenced by kernel_wfp_ipsec_create().
 {
     bool ok = TRUE;
     rng_t *rng;
     rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
     if (!rng)
     {
         return FALSE;
     }
     ok = rng->get_bytes(rng, sizeof(this->nextspi), (u_int8_t*)&this->nextspi);
     if (ok)
     {
         ok = rng->get_bytes(rng, sizeof(this->mixspi), (u_int8_t*)&this->mixspi);
     }
     rng->destroy(rng);
     return ok;
 }
static bool install (private_kernel_wfp_ipsec_t * this, entry_t * entry) static
Install a SA/SP set to the kernel
Definition at line 1566 of file kernel_wfp_ipsec.c.
References FALSE, install_transport(), install_tunnel(), entry_t::mode, MODE_BEET, MODE_TRANSPORT, and MODE_TUNNEL.
Referenced by manage_commands(), and METHOD().
 {
     switch (entry->mode)
     {
         case MODE_TRANSPORT:
             return install_transport(this, entry);
         case MODE_TUNNEL:
             return install_tunnel(this, entry);
         case MODE_BEET:
         default:
             return FALSE;
     }
 }
static bool install_ipip_ale (private_kernel_wfp_ipsec_t * this, host_t * local, host_t * remote, GUID * context, bool inbound, int proto, u_int64_t * filter_id) static
Install an IP-IP allow filter for SA specific hosts
Definition at line 738 of file kernel_wfp_ipsec.c.
References host_t::clone, count, DBG1, DBG_KNL, traffic_selector_t::destroy, DWORD, FALSE, filter(), find_callout(), free_conditions(), FWPM_CONDITION_IP_LOCAL_ADDRESS, FWPM_CONDITION_IP_REMOTE_ADDRESS, FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT, host_t::get_family, handle, proto, res, traffic_selector_create_from_subnet(), TRUE, and ts2condition().
Referenced by install_sps().
 {
     traffic_selector_t *lts, *rts;
     FWPM_FILTER_CONDITION0 *conds = NULL;
     int count = 0;
     bool v6;
     DWORD res;
     FWPM_FILTER0 filter = {
         .displayData = {
             .name = L"charon IPsec IP-in-IP ALE policy",
         },
         .action = {
             .type = FWP_ACTION_CALLOUT_TERMINATING,
         },
     };
     if (context)
     {
         filter.flags |= FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT;
         filter.providerKey = (GUID*)&this->provider.providerKey;
         filter.providerContextKey = *context;
     }
     v6 = local->get_family(local) == AF_INET6;
     if (!find_callout(TRUE, v6, inbound, FALSE, TRUE, &filter.layerKey,
                       &filter.subLayerKey, &filter.action.calloutKey))
     {
         return FALSE;
     }
     lts = traffic_selector_create_from_subnet(local->clone(local),
                                             v6 ? 128 : 32 , proto, 0, 65535);
     rts = traffic_selector_create_from_subnet(remote->clone(remote),
                                             v6 ? 128 : 32 , proto, 0, 65535);
     if (!ts2condition(lts, &FWPM_CONDITION_IP_LOCAL_ADDRESS, &conds, &count) ||
         !ts2condition(rts, &FWPM_CONDITION_IP_REMOTE_ADDRESS, &conds, &count))
     {
         free_conditions(conds, count);
         lts->destroy(lts);
         rts->destroy(rts);
         return FALSE;
     }
     lts->destroy(lts);
     rts->destroy(rts);
     filter.numFilterConditions = count;
     filter.filterCondition = conds;
     res = FwpmFilterAdd0(this->handle, &filter, NULL, filter_id);
     free_conditions(conds, count);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "installing IP-IPv%d %s ALE WFP filter failed: 0x%08x",
              v6 ? 6 : 4, inbound ? "inbound" : "outbound", res);
         return FALSE;
     }
     return TRUE;
 }
static bool install_route (private_kernel_wfp_ipsec_t * this, host_t * dst, u_int8_t mask, host_t * src, host_t * gtw) static
Install a single route, or refcount if exists
Definition at line 1425 of file kernel_wfp_ipsec.c.
References kernel_interface_t::add_route, host_t::clone, destroy_route(), dst, FALSE, free(), host_t::get_address, kernel_interface_t::get_interface, hydra, INIT, hydra_t::kernel_interface, key, mutex_t::lock, mask, mutex, name, route_t::refs, res, src, SUCCESS, TRUE, and mutex_t::unlock.
Referenced by manage_route().
 {
     route_t *route, key = {
         .dst = dst,
         .mask = mask,
         .src = src,
     };
     char *name;
     bool res = FALSE;
     this->mutex->lock(this->mutex);
     route = this->routes->get(this->routes, &key);
     if (route)
     {
         route->refs++;
         res = TRUE;
     }
     else
     {
         if (hydra->kernel_interface->get_interface(hydra->kernel_interface,
                                                    src, &name))
         {
             if (hydra->kernel_interface->add_route(hydra->kernel_interface,
                         dst->get_address(dst), mask, gtw, src, name) == SUCCESS)
             {
                 INIT(route,
                     .dst = dst->clone(dst),
                     .mask = mask,
                     .src = src->clone(src),
                     .gtw = gtw ? gtw->clone(gtw) : NULL,
                     .refs = 1,
                 );
                 route = this->routes->put(this->routes, route, route);
                 if (route)
                 {
                     destroy_route(route);
                 }
                 res = TRUE;
             }
             free(name);
         }
     }
     this->mutex->unlock(this->mutex);
     return res;
 }
static bool install_sa (private_kernel_wfp_ipsec_t * this, entry_t * entry, bool inbound, sa_entry_t * sa, FWP_IP_VERSION version) static
Install a single SA
Definition at line 1000 of file kernel_wfp_ipsec.c.
References alg, sa_entry_t::alg, alg2auth(), alg2cipher(), chunk2blob(), DBG1, DBG_KNL, DWORD, sa_entry_t::encr, encr2integ(), ENCR_NULL, ENCR_NULL_AUTH_AES_GMAC, encryption_algorithm_is_aead(), encryption_algorithm_names, FALSE, handle, sa_entry_t::integ, integ, integrity_algorithm_names, ipsec, IPSEC_SA_BUNDLE_FLAG_ASSUME_UDP_CONTEXT_OUTBOUND, IPSEC_TRANSFORM_AH, IPSEC_TRANSFORM_ESP_AUTH, IPSEC_TRANSFORM_ESP_AUTH_AND_CIPHER, entry_t::isa, sa_entry_t::key, key, chunk_t::len, sa_entry_t::lifetime, entry_t::osa, sa_entry_t::protocol, res, entry_t::sa_id, sa_entry_t::spi, TRUE, and version.
Referenced by install_sas().
 {
     IPSEC_SA_AUTH_AND_CIPHER_INFORMATION0 info = {};
     IPSEC_SA0 ipsec = {
         .spi = ntohl(sa->spi),
     };
     IPSEC_SA_BUNDLE0 bundle = {
         .lifetime = {
             .lifetimeSeconds = inbound ? entry->isa.lifetime
                                        : entry->osa.lifetime,
         },
         .saList = &ipsec,
         .numSAs = 1,
         .ipVersion = version,
     };
     struct {
         u_int16_t alg;
         chunk_t key;
     } integ = {}, encr = {};
     DWORD res;
     switch (sa->protocol)
     {
         case IPPROTO_AH:
             ipsec.saTransformType = IPSEC_TRANSFORM_AH;
             ipsec.ahInformation = &info.saAuthInformation;
             integ.key = sa->integ.key;
             integ.alg = sa->integ.alg;
             break;
         case IPPROTO_ESP:
             if (sa->encr.alg == ENCR_NULL ||
                 sa->encr.alg == ENCR_NULL_AUTH_AES_GMAC)
             {
                 ipsec.saTransformType = IPSEC_TRANSFORM_ESP_AUTH;
                 ipsec.espAuthInformation = &info.saAuthInformation;
             }
             else
             {
                 ipsec.saTransformType = IPSEC_TRANSFORM_ESP_AUTH_AND_CIPHER;
                 ipsec.espAuthAndCipherInformation = &info;
                 encr.key = sa->encr.key;
                 encr.alg = sa->encr.alg;
             }
             if (encryption_algorithm_is_aead(sa->encr.alg))
             {
                 integ.alg = encr2integ(sa->encr.alg, sa->encr.key.len);
                 integ.key = sa->encr.key;
             }
             else
             {
                 integ.alg = sa->integ.alg;
                 integ.key = sa->integ.key;
             }
             break;
         default:
             return FALSE;
     }
     if (integ.alg)
     {
         info.saAuthInformation.authKey = chunk2blob(integ.key);
         if (!alg2auth(integ.alg, &info.saAuthInformation))
         {
             DBG1(DBG_KNL, "integrity algorithm %N not supported by WFP",
                  integrity_algorithm_names, integ.alg);
             return FALSE;
         }
     }
     if (encr.alg)
     {
         info.saCipherInformation.cipherKey = chunk2blob(encr.key);
         if (!alg2cipher(encr.alg, encr.key.len, &info.saCipherInformation))
         {
             DBG1(DBG_KNL, "encryption algorithm %N not supported by WFP",
                  encryption_algorithm_names, encr.alg);
             return FALSE;
         }
     }
     if (inbound)
     {
         res = IPsecSaContextAddInbound0(this->handle, entry->sa_id, &bundle);
     }
     else
     {
         bundle.flags |= IPSEC_SA_BUNDLE_FLAG_ASSUME_UDP_CONTEXT_OUTBOUND;
         res = IPsecSaContextAddOutbound0(this->handle, entry->sa_id, &bundle);
     }
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "adding %sbound WFP SA failed: 0x%08x",
              inbound ? "in" : "out", res);
         return FALSE;
     }
     return TRUE;
 }
static bool install_sas (private_kernel_wfp_ipsec_t * this, entry_t * entry, IPSEC_TRAFFIC_TYPE type) static
Install SAs to the kernel
Definition at line 1143 of file kernel_wfp_ipsec.c.
References array_create_enumerator(), ctx, DBG1, DBG_KNL, enumerator_t::destroy, DWORD, entry_t::encap, enumerator_t::enumerate, FALSE, handle, hosts2traffic(), install_sa(), IPSEC_SA_DETAILS_UPDATE_UDP_ENCAPSULATION, IPsecSaContextSetSpi0, IPsecSaContextUpdate0, entry_t::isa, entry_t::local, memcpy, entry_t::osa, sp_entry_t::policy_in, sp_entry_t::policy_out, entry_t::provider, entry_t::remote, res, entry_t::sa_id, sa_entry_t::spi, entry_t::sps, TRUE, and type.
Referenced by install_transport(), and install_tunnel().
 {
     IPSEC_TRAFFIC1 traffic = {
         .trafficType = type,
     };
     IPSEC_GETSPI1 spi = {
         .inboundIpsecTraffic = {
             .trafficType = type,
         },
     };
     enumerator_t *enumerator;
     sp_entry_t *sp;
     DWORD res;
     if (type == IPSEC_TRAFFIC_TYPE_TRANSPORT)
     {
         enumerator = array_create_enumerator(entry->sps);
         if (enumerator->enumerate(enumerator, &sp))
         {
             traffic.ipsecFilterId = sp->policy_out;
             spi.inboundIpsecTraffic.ipsecFilterId = sp->policy_in;
         }
         else
         {
             enumerator->destroy(enumerator);
             return FALSE;
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         traffic.tunnelPolicyId = entry->provider;
         spi.inboundIpsecTraffic.tunnelPolicyId = entry->provider;
     }
     if (!hosts2traffic(this, entry->local, entry->remote, &traffic))
     {
         return FALSE;
     }
     res = IPsecSaContextCreate1(this->handle, &traffic, NULL, NULL,
                                 &entry->sa_id);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "creating WFP SA context failed: 0x%08x", res);
         return FALSE;
     }
     memcpy(spi.inboundIpsecTraffic.localV6Address, traffic.localV6Address,
            sizeof(traffic.localV6Address));
     memcpy(spi.inboundIpsecTraffic.remoteV6Address, traffic.remoteV6Address,
            sizeof(traffic.remoteV6Address));
     spi.ipVersion = traffic.ipVersion;
     res = IPsecSaContextSetSpi0(this->handle, entry->sa_id, &spi,
                                 ntohl(entry->isa.spi));
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "setting WFP SA SPI failed: 0x%08x", res);
         IPsecSaContextDeleteById0(this->handle, entry->sa_id);
         entry->sa_id = 0;
         return FALSE;
     }
     if (!install_sa(this, entry, TRUE, &entry->isa, spi.ipVersion) ||
         !install_sa(this, entry, FALSE, &entry->osa, spi.ipVersion))
     {
         IPsecSaContextDeleteById0(this->handle, entry->sa_id);
         entry->sa_id = 0;
         return FALSE;
     }
     if (entry->encap)
     {
         IPSEC_V4_UDP_ENCAPSULATION0 encap = {
             .localUdpEncapPort = entry->local->get_port(entry->local),
             .remoteUdpEncapPort = entry->remote->get_port(entry->remote),
         };
         IPSEC_SA_CONTEXT1 *ctx;
         res = IPsecSaContextGetById1(this->handle, entry->sa_id, &ctx);
         if (res != ERROR_SUCCESS)
         {
             DBG1(DBG_KNL, "getting WFP SA for UDP encap failed: 0x%08x", res);
             IPsecSaContextDeleteById0(this->handle, entry->sa_id);
             entry->sa_id = 0;
             return FALSE;
         }
         ctx->inboundSa->udpEncapsulation = &encap;
         ctx->outboundSa->udpEncapsulation = &encap;
         res = IPsecSaContextUpdate0(this->handle,
                                 IPSEC_SA_DETAILS_UPDATE_UDP_ENCAPSULATION, ctx);
         FwpmFreeMemory0((void**)&ctx);
         if (res != ERROR_SUCCESS)
         {
             DBG1(DBG_KNL, "enable WFP UDP encap failed: 0x%08x", res);
             IPsecSaContextDeleteById0(this->handle, entry->sa_id);
             entry->sa_id = 0;
             return FALSE;
         }
     }
     return TRUE;
 }
static bool install_sp (private_kernel_wfp_ipsec_t * this, sp_entry_t * sp, GUID * context, bool inbound, bool fwd, UINT64 * filter_id) static
Install a single policy in to the kernel
Definition at line 660 of file kernel_wfp_ipsec.c.
References count, DBG1, DBG_KNL, sp_entry_t::dst, DWORD, FALSE, filter(), find_callout(), free_conditions(), FWPM_CONDITION_IP_DESTINATION_ADDRESS, FWPM_CONDITION_IP_LOCAL_ADDRESS, FWPM_CONDITION_IP_REMOTE_ADDRESS, FWPM_CONDITION_IP_SOURCE_ADDRESS, FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT, traffic_selector_t::get_type, handle, res, sp_entry_t::src, TRUE, ts2condition(), and TS_IPV6_ADDR_RANGE.
Referenced by install_sps().
 {
     FWPM_FILTER_CONDITION0 *conds = NULL;
     traffic_selector_t *local, *remote;
     const GUID *ltarget, *rtarget;
     int count = 0;
     bool v6;
     DWORD res;
     FWPM_FILTER0 filter = {
         .displayData = {
             .name = L"charon IPsec policy",
         },
         .action = {
             .type = FWP_ACTION_CALLOUT_TERMINATING,
         },
     };
     if (context)
     {
         filter.flags |= FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT;
         filter.providerKey = (GUID*)&this->provider.providerKey;
         filter.providerContextKey = *context;
     }
     v6 = sp->src->get_type(sp->src) == TS_IPV6_ADDR_RANGE;
     if (!find_callout(context != NULL, v6, inbound, fwd, FALSE,
                       &filter.layerKey, &filter.subLayerKey,
                       &filter.action.calloutKey))
     {
         return FALSE;
     }
     if (inbound && fwd)
     {
         local = sp->dst;
         remote = sp->src;
     }
     else
     {
         local = sp->src;
         remote = sp->dst;
     }
     if (fwd)
     {
         ltarget = &FWPM_CONDITION_IP_SOURCE_ADDRESS;
         rtarget = &FWPM_CONDITION_IP_DESTINATION_ADDRESS;
     }
     else
     {
         ltarget = &FWPM_CONDITION_IP_LOCAL_ADDRESS;
         rtarget = &FWPM_CONDITION_IP_REMOTE_ADDRESS;
     }
     if (!ts2condition(local, ltarget, &conds, &count) ||
         !ts2condition(remote, rtarget, &conds, &count))
     {
         free_conditions(conds, count);
         return FALSE;
     }
     filter.numFilterConditions = count;
     filter.filterCondition = conds;
     res = FwpmFilterAdd0(this->handle, &filter, NULL, filter_id);
     free_conditions(conds, count);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "installing IPv%d %s%sbound %s WFP filter failed: 0x%08x",
              v6 ? 6 : 4, fwd ? "forward " : "", inbound ? "in" : "out",
              context ? "tunnel" : "transport", res);
         return FALSE;
     }
     return TRUE;
 }
static bool install_sps (private_kernel_wfp_ipsec_t * this, entry_t * entry, GUID * context) static
Install a set of policies in to the kernel
Definition at line 802 of file kernel_wfp_ipsec.c.
References array_create_enumerator(), enumerator_t::destroy, sp_entry_t::dst, enumerator_t::enumerate, FALSE, traffic_selector_t::get_type, install_ipip_ale(), install_sp(), entry_t::ip_ipv4_in, entry_t::ip_ipv4_out, entry_t::ip_ipv6_in, entry_t::ip_ipv6_out, IPPROTO_IPIP, IPPROTO_IPV6, traffic_selector_t::is_host, entry_t::local, sp_entry_t::policy_fwd_in, sp_entry_t::policy_fwd_out, sp_entry_t::policy_in, sp_entry_t::policy_out, entry_t::remote, entry_t::sps, sp_entry_t::src, TRUE, TS_IPV4_ADDR_RANGE, and TS_IPV6_ADDR_RANGE.
Referenced by install_transport(), and install_tunnel_sps().
 {
     enumerator_t *enumerator;
     sp_entry_t *sp;
     bool has_v4 = FALSE, has_v6 = FALSE;
     enumerator = array_create_enumerator(entry->sps);
     while (enumerator->enumerate(enumerator, &sp))
     {
         switch (sp->src->get_type(sp->src))
         {
             case TS_IPV4_ADDR_RANGE:
                 has_v4 = TRUE;
                 break;
             case TS_IPV6_ADDR_RANGE:
                 has_v6 = TRUE;
                 break;
         }
         /* inbound policy */
         if (!install_sp(this, sp, context, TRUE, FALSE, &sp->policy_in))
         {
             enumerator->destroy(enumerator);
             return FALSE;
         }
         /* outbound policy */
         if (!install_sp(this, sp, context, FALSE, FALSE, &sp->policy_out))
         {
             enumerator->destroy(enumerator);
             return FALSE;
         }
         if (context)
         {
             if (!sp->src->is_host(sp->src, entry->local) ||
                 !sp->dst->is_host(sp->dst, entry->remote))
             {
                 /* inbound forward policy, from decapsulation */
                 if (!install_sp(this, sp, context, TRUE, TRUE,
                                 &sp->policy_fwd_in))
                 {
                     enumerator->destroy(enumerator);
                     return FALSE;
                 }
                 /* outbound forward policy, to encapsulate */
                 if (!install_sp(this, sp, context, FALSE, TRUE,
                                 &sp->policy_fwd_out))
                 {
                     enumerator->destroy(enumerator);
                     return FALSE;
                 }
             }
         }
     }
     enumerator->destroy(enumerator);
     if (context)
     {
         /* In tunnel mode, Windows does firewall filtering on decrypted but
          * non-unwrapped packets: It sees them as IP-in-IP packets. When using
          * a default-drop policy, we need to allow such packets explicitly. */
         if (has_v4)
         {
             if (!install_ipip_ale(this, entry->local, entry->remote, context,
                                   TRUE, IPPROTO_IPIP, &entry->ip_ipv4_in))
             {
                 return FALSE;
             }
             if (!install_ipip_ale(this, entry->local, entry->remote, NULL,
                                   FALSE, IPPROTO_IPIP, &entry->ip_ipv4_out))
             {
                 return FALSE;
             }
         }
         if (has_v6)
         {
             if (!install_ipip_ale(this, entry->local, entry->remote, context,
                                   TRUE, IPPROTO_IPV6, &entry->ip_ipv6_in))
             {
                 return FALSE;
             }
             if (!install_ipip_ale(this, entry->local, entry->remote, NULL,
                                   FALSE, IPPROTO_IPV6, &entry->ip_ipv6_out))
             {
                 return FALSE;
             }
         }
     }
     return TRUE;
 }
static bool install_transport (private_kernel_wfp_ipsec_t * this, entry_t * entry) static
Install a transport mode SA/SP set to the kernel
Definition at line 1253 of file kernel_wfp_ipsec.c.
References cleanup_policies(), FALSE, install_sas(), install_sps(), and TRUE.
Referenced by install().
 {
     if (install_sps(this, entry, NULL) &&
         install_sas(this, entry, IPSEC_TRAFFIC_TYPE_TRANSPORT))
     {
         return TRUE;
     }
     cleanup_policies(this, entry);
     return FALSE;
 }
static bool install_trap (private_kernel_wfp_ipsec_t * this, trap_t * trap) static
Install a trap policy to kernel
Definition at line 1782 of file kernel_wfp_ipsec.c.
References count, DBG1, DBG_KNL, trap_t::dst, DWORD, FALSE, filter(), trap_t::filter_id, free_conditions(), trap_t::fwd, FWPM_CONDITION_IP_DESTINATION_ADDRESS, FWPM_CONDITION_IP_LOCAL_ADDRESS, FWPM_CONDITION_IP_REMOTE_ADDRESS, FWPM_CONDITION_IP_SOURCE_ADDRESS, FWPM_LAYER_IPFORWARD_V4, FWPM_LAYER_IPFORWARD_V6, FWPM_LAYER_OUTBOUND_TRANSPORT_V4, FWPM_LAYER_OUTBOUND_TRANSPORT_V6, traffic_selector_t::get_type, handle, res, trap_t::src, TRUE, ts2condition(), and TS_IPV4_ADDR_RANGE.
Referenced by add_trap().
 {
     FWPM_FILTER_CONDITION0 *conds = NULL;
     int count = 0;
     DWORD res;
     const GUID *starget, *dtarget;
     UINT64 weight = 0x000000000000ff00;
     FWPM_FILTER0 filter = {
         .displayData = {
             .name = L"charon IPsec trap",
         },
         .action = {
             .type = FWP_ACTION_BLOCK,
         },
         .weight = {
             .type = FWP_UINT64,
             .uint64 = &weight,
         },
     };
     if (trap->fwd)
     {
         if (trap->src->get_type(trap->src) == TS_IPV4_ADDR_RANGE)
         {
             filter.layerKey = FWPM_LAYER_IPFORWARD_V4;
         }
         else
         {
             filter.layerKey = FWPM_LAYER_IPFORWARD_V6;
         }
         starget = &FWPM_CONDITION_IP_SOURCE_ADDRESS;
         dtarget = &FWPM_CONDITION_IP_DESTINATION_ADDRESS;
     }
     else
     {
         if (trap->src->get_type(trap->src) == TS_IPV4_ADDR_RANGE)
         {
             filter.layerKey = FWPM_LAYER_OUTBOUND_TRANSPORT_V4;
         }
         else
         {
             filter.layerKey = FWPM_LAYER_OUTBOUND_TRANSPORT_V6;
         }
         starget = &FWPM_CONDITION_IP_LOCAL_ADDRESS;
         dtarget = &FWPM_CONDITION_IP_REMOTE_ADDRESS;
     }
     if (!ts2condition(trap->src, starget, &conds, &count) ||
         !ts2condition(trap->dst, dtarget, &conds, &count))
     {
         free_conditions(conds, count);
         return FALSE;
     }
     filter.numFilterConditions = count;
     filter.filterCondition = conds;
     res = FwpmFilterAdd0(this->handle, &filter, NULL, &trap->filter_id);
     free_conditions(conds, count);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "installing WFP trap filter failed: 0x%08x", res);
         return FALSE;
     }
     return TRUE;
 }
static bool install_tunnel (private_kernel_wfp_ipsec_t * this, entry_t * entry) static
Install a tunnel mode SA/SP set to the kernel
Definition at line 1551 of file kernel_wfp_ipsec.c.
References cleanup_policies(), FALSE, install_sas(), install_tunnel_sps(), manage_routes(), and TRUE.
Referenced by install().
 {
     if (install_tunnel_sps(this, entry) &&
         manage_routes(this, entry, TRUE) &&
         install_sas(this, entry, IPSEC_TRAFFIC_TYPE_TUNNEL))
     {
         return TRUE;
     }
     cleanup_policies(this, entry);
     return FALSE;
 }
static bool install_tunnel_sps (private_kernel_wfp_ipsec_t * this, entry_t * entry) static
Install tunnel mode SPs to the kernel
Definition at line 1364 of file kernel_wfp_ipsec.c.
References add_tunnel_provider(), FALSE, install_sps(), entry_t::provider, and TRUE.
Referenced by install_tunnel().
 {
     GUID guid;
     if (!add_tunnel_provider(this, entry, &guid, &entry->provider))
     {
         return FALSE;
     }
     if (!install_sps(this, entry, &guid))
     {
         return FALSE;
     }
     return TRUE;
 }
static bool manage_route (private_kernel_wfp_ipsec_t * this, host_t * local, host_t * remote, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, bool add) static
(Un)-install a single route
Definition at line 1476 of file kernel_wfp_ipsec.c.
References DBG1, DBG_KNL, host_t::destroy, DESTROY_IF, dst, FALSE, kernel_interface_t::get_address_by_ts, kernel_interface_t::get_nexthop, hydra, install_route(), hydra_t::kernel_interface, mask, src, SUCCESS, traffic_selector_t::to_subnet, and uninstall_route().
Referenced by add_trap(), manage_routes(), and remove_trap().
 {
     host_t *src, *dst, *gtw;
     u_int8_t mask;
     bool done;
     if (!dst_ts->to_subnet(dst_ts, &dst, &mask))
     {
         return FALSE;
     }
     if (hydra->kernel_interface->get_address_by_ts(hydra->kernel_interface,
                                                 src_ts, &src, NULL) != SUCCESS)
     {
         dst->destroy(dst);
         return FALSE;
     }
     gtw = hydra->kernel_interface->get_nexthop(hydra->kernel_interface,
                                                remote, -1, local);
     if (add)
     {
         done = install_route(this, dst, mask, src, gtw);
     }
     else
     {
         done = uninstall_route(this, dst, mask, src, gtw);
     }
     dst->destroy(dst);
     src->destroy(src);
     DESTROY_IF(gtw);
     if (!done)
     {
         DBG1(DBG_KNL, "%sinstalling route for policy %R === %R failed",
              add ? "" : "un", src_ts, dst_ts);
     }
     return done;
 }
static bool manage_routes (private_kernel_wfp_ipsec_t * this, entry_t * entry, bool add) static
forward declaration
(Un)-install routes for IPsec policies
Definition at line 1520 of file kernel_wfp_ipsec.c.
References add(), array_create_enumerator(), enumerator_t::destroy, sp_entry_t::dst, enumerator_t::enumerate, entry_t::local, manage_route(), entry_t::remote, sp_entry_t::route, entry_t::sps, sp_entry_t::src, and TRUE.
Referenced by cleanup_policies(), install_tunnel(), and METHOD().
 {
     enumerator_t *enumerator;
     sp_entry_t *sp;
     enumerator = array_create_enumerator(entry->sps);
     while (enumerator->enumerate(enumerator, &sp))
     {
         if (add && sp->route)
         {
             continue;
         }
         if (!add && !sp->route)
         {
             continue;
         }
         if (manage_route(this, entry->local, entry->remote,
                          sp->src, sp->dst, add))
         {
             sp->route = add;
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 }
METHOD (kernel_ipsec_t , get_features , kernel_feature_t , private_kernel_wfp_ipsec_t * this)
Definition at line 1938 of file kernel_wfp_ipsec.c.
References KERNEL_ESP_V3_TFC, and KERNEL_NO_POLICY_UPDATES.
 {
     return KERNEL_ESP_V3_TFC | KERNEL_NO_POLICY_UPDATES;
 }
METHOD (kernel_ipsec_t , get_spi , status_t , private_kernel_wfp_ipsec_t * this, host_t * src, host_t * dst, u_int8_t protocol, u_int32_t * spi)
Definition at line 1982 of file kernel_wfp_ipsec.c.
References offset, permute(), ref_get(), and SUCCESS.
 {
     /* To avoid sequencial SPIs, we use a one-to-one permuation function on
      * an incrementing counter, that is a full period PRNG for the range we
      * allocate SPIs in. We add some randomness using a fixed XOR and start
      * the counter at random position. This is not cryptographically safe,
      * but that is actually not required.
      * The selected prime should be smaller than the range we allocate SPIs
      * in, and it must satisfy p % 4 == 3 to map x > p/2 using p - qr. */
     static const u_int p = 268435399, offset = 0xc0000000;
     *spi = htonl(offset + permute(ref_get(&this->nextspi) ^ this->mixspi, p));
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , get_cpi , status_t , private_kernel_wfp_ipsec_t * this, host_t * src, host_t * dst, u_int16_t * cpi)
Definition at line 1999 of file kernel_wfp_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , add_sa , status_t , private_kernel_wfp_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t * lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t * src_ts, linked_list_t * dst_ts)
Definition at line 2100 of file kernel_wfp_ipsec.c.
References array_create(), chunk_clone, host_t::clone, DBG1, DBG_KNL, FALSE, INIT, entry_t::isa, lifetime_cfg_t::life, mutex_t::lock, mutex, NOT_FOUND, entry_t::osa, protocol, lifetime_cfg_t::rekey, entry_t::remote, schedule_expire(), entry_t::spi, sa_entry_t::spi, SUCCESS, lifetime_cfg_t::time, TRUE, and mutex_t::unlock.
 {
     host_t *local, *remote;
     entry_t *entry;
     if (inbound)
     {
         /* comes first, create new entry */
         local = dst->clone(dst);
         remote = src->clone(src);
         INIT(entry,
             .reqid = reqid,
             .isa = {
                 .spi = spi,
                 .dst = local,
                 .protocol = protocol,
                 .lifetime = lifetime->time.life,
                 .encr = {
                     .alg = enc_alg,
                     .key = chunk_clone(enc_key),
                 },
                 .integ = {
                     .alg = int_alg,
                     .key = chunk_clone(int_key),
                 },
             },
             .sps = array_create(0, 0),
             .local = local,
             .remote = remote,
             .mode = mode,
             .encap = encap,
         );
         if (lifetime->time.life)
         {
             schedule_expire(this, spi, local, lifetime->time.life, TRUE);
         }
         if (lifetime->time.rekey && lifetime->time.rekey != lifetime->time.life)
         {
             schedule_expire(this, spi, local, lifetime->time.rekey, FALSE);
         }
         this->mutex->lock(this->mutex);
         this->tsas->put(this->tsas, (void*)(uintptr_t)reqid, entry);
         this->isas->put(this->isas, &entry->isa, entry);
         this->mutex->unlock(this->mutex);
     }
     else
     {
         /* comes after inbound, update entry */
         this->mutex->lock(this->mutex);
         entry = this->tsas->remove(this->tsas, (void*)(uintptr_t)reqid);
         this->mutex->unlock(this->mutex);
         if (!entry)
         {
             DBG1(DBG_KNL, "adding outbound SA failed, no inbound SA found "
                  "for reqid %u ", reqid);
             return NOT_FOUND;
         }
         /* TODO: should we check for local/remote, mode etc.? */
         entry->osa = (sa_entry_t){
             .spi = spi,
             .dst = entry->remote,
             .protocol = protocol,
             .lifetime = lifetime->time.life,
             .encr = {
                 .alg = enc_alg,
                 .key = chunk_clone(enc_key),
             },
             .integ = {
                 .alg = int_alg,
                 .key = chunk_clone(int_key),
             },
         };
         this->mutex->lock(this->mutex);
         this->osas->put(this->osas, &entry->osa, entry);
         this->mutex->unlock(this->mutex);
     }
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , update_sa , status_t , private_kernel_wfp_ipsec_t * this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t * src, host_t * dst, host_t * new_src, host_t * new_dst, bool encap, bool new_encap, mark_t mark)
Definition at line 2193 of file kernel_wfp_ipsec.c.
References host_t::clone, ctx, DBG1, DBG_KNL, linked_list_t::destroy, sa_entry_t::dst, dst, DWORD, FAILED, FALSE, flags, handle, hosts2traffic(), IPSEC_SA_DETAILS_UPDATE_TRAFFIC, IPSEC_SA_DETAILS_UPDATE_UDP_ENCAPSULATION, IPsecSaContextUpdate0, entry_t::isa, key, entry_t::local, mutex_t::lock, manage_routes(), mutex, NOT_FOUND, entry_t::osa, entry_t::remote, res, entry_t::sa_id, sa_entry_t::spi, SUCCESS, TRUE, and mutex_t::unlock.
 {
     entry_t *entry;
     sa_entry_t key = {
         .dst = dst,
         .spi = spi,
     };
     UINT64 sa_id = 0;
     IPSEC_SA_CONTEXT1 *ctx;
     IPSEC_V4_UDP_ENCAPSULATION0 ports;
     UINT32 flags = IPSEC_SA_DETAILS_UPDATE_TRAFFIC;
     DWORD res;
     this->mutex->lock(this->mutex);
     entry = this->osas->get(this->osas, &key);
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         /* outbound entry, nothing to do */
         return SUCCESS;
     }
     this->mutex->lock(this->mutex);
     entry = this->isas->get(this->isas, &key);
     if (entry)
     {
         /* inbound entry, do update */
         sa_id = entry->sa_id;
         ports.localUdpEncapPort = entry->local->get_port(entry->local);
         ports.remoteUdpEncapPort = entry->remote->get_port(entry->remote);
     }
     this->mutex->unlock(this->mutex);
     if (!sa_id)
     {
         return NOT_FOUND;
     }
     res = IPsecSaContextGetById1(this->handle, sa_id, &ctx);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "getting WFP SA context for updated failed: 0x%08x", res);
         return FAILED;
     }
     if (!hosts2traffic(this, new_dst, new_src, &ctx->inboundSa->traffic) ||
         !hosts2traffic(this, new_dst, new_src, &ctx->outboundSa->traffic))
     {
         FwpmFreeMemory0((void**)&ctx);
         return FAILED;
     }
     if (new_encap != encap)
     {
         if (new_encap)
         {
             ctx->inboundSa->udpEncapsulation = &ports;
             ctx->outboundSa->udpEncapsulation = &ports;
         }
         else
         {
             ctx->inboundSa->udpEncapsulation = NULL;
             ctx->outboundSa->udpEncapsulation = NULL;
         }
         flags |= IPSEC_SA_DETAILS_UPDATE_UDP_ENCAPSULATION;
     }
     res = IPsecSaContextUpdate0(this->handle, flags, ctx);
     FwpmFreeMemory0((void**)&ctx);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "updating WFP SA context failed: 0x%08x", res);
         return FAILED;
     }
     this->mutex->lock(this->mutex);
     entry = this->isas->remove(this->isas, &key);
     if (entry)
     {
         key.spi = entry->osa.spi;
         key.dst = entry->osa.dst;
         this->osas->remove(this->osas, &key);
         entry->local->destroy(entry->local);
         entry->remote->destroy(entry->remote);
         entry->local = new_dst->clone(new_dst);
         entry->remote = new_src->clone(new_src);
         entry->isa.dst = entry->local;
         entry->osa.dst = entry->remote;
         this->isas->put(this->isas, &entry->isa, entry);
         this->osas->put(this->osas, &entry->osa, entry);
         manage_routes(this, entry, FALSE);
         manage_routes(this, entry, TRUE);
     }
     this->mutex->unlock(this->mutex);
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , query_sa , status_t , private_kernel_wfp_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t * bytes, u_int64_t * packets, time_t * time)
Definition at line 2297 of file kernel_wfp_ipsec.c.
References NOT_SUPPORTED.
 {
     /* It does not seem that WFP provides any means of getting per-SA traffic
      * statistics. IPsecGetStatistics0/1() provides global stats, and
      * IPsecSaContextEnum0/1() and IPsecSaEnum0/1() return the configured
      * values only. */
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , del_sa , status_t , private_kernel_wfp_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Definition at line 2309 of file kernel_wfp_ipsec.c.
References dst, entry_destroy(), key, mutex_t::lock, mutex, NOT_FOUND, SUCCESS, and mutex_t::unlock.
 {
     entry_t *entry;
     sa_entry_t key = {
         .dst = dst,
         .spi = spi,
     };
     this->mutex->lock(this->mutex);
     entry = this->isas->remove(this->isas, &key);
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         /* keep entry until removal of outbound */
         return SUCCESS;
     }
     this->mutex->lock(this->mutex);
     entry = this->osas->remove(this->osas, &key);
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         entry_destroy(this, entry);
         return SUCCESS;
     }
     return NOT_FOUND;
 }
METHOD (kernel_ipsec_t , flush_sas , status_t , private_kernel_wfp_ipsec_t * this)
Definition at line 2342 of file kernel_wfp_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , add_policy , status_t , private_kernel_wfp_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 2348 of file kernel_wfp_ipsec.c.
References add_trap(), ipsec_sa_cfg_t::ah, array_count(), array_insert(), traffic_selector_t::clone, DBG1, DBG_KNL, dst, ipsec_sa_cfg_t::esp, FAILED, FALSE, INIT, install(), key, mutex_t::lock, ipsec_sa_cfg_t::mode, MODE_TUNNEL, mutex, NOT_SUPPORTED, ipsec_sa_cfg_t::policy_count, POLICY_DROP, POLICY_FWD, POLICY_IN, POLICY_IPSEC, POLICY_OUT, POLICY_PASS, POLICY_PRIORITY_DEFAULT, POLICY_PRIORITY_FALLBACK, POLICY_PRIORITY_ROUTED, ipsec_sa_cfg_t::reqid, sa_entry_t::spi, ipsec_sa_cfg_t::spi, entry_t::sps, status, SUCCESS, TRUE, mutex_t::unlock, and ipsec_sa_cfg_t::use.
 {
     status_t status = SUCCESS;
     entry_t *entry;
     sp_entry_t *sp;
     sa_entry_t key = {
         .spi = sa->esp.use ? sa->esp.spi : sa->ah.spi,
         .dst = dst,
     };
     if (sa->esp.use && sa->ah.use)
     {
         return NOT_SUPPORTED;
     }
     switch (type)
     {
         case POLICY_IPSEC:
             break;
         case POLICY_PASS:
         case POLICY_DROP:
             return NOT_SUPPORTED;
     }
     switch (direction)
     {
         case POLICY_OUT:
             break;
         case POLICY_IN:
         case POLICY_FWD:
             /* not required */
             return SUCCESS;
         default:
             return NOT_SUPPORTED;
     }
     switch (priority)
     {
         case POLICY_PRIORITY_DEFAULT:
             break;
         case POLICY_PRIORITY_ROUTED:
             if (!add_trap(this, sa->reqid, FALSE, src, dst, src_ts, dst_ts))
             {
                 return FAILED;
             }
             if (sa->mode == MODE_TUNNEL)
             {
                 if (!add_trap(this, sa->reqid, TRUE, src, dst, src_ts, dst_ts))
                 {
                     return FAILED;
                 }
             }
             return SUCCESS;
         case POLICY_PRIORITY_FALLBACK:
         default:
             return NOT_SUPPORTED;
     }
     this->mutex->lock(this->mutex);
     entry = this->osas->get(this->osas, &key);
     if (entry)
     {
         if (sa->mode == MODE_TUNNEL || array_count(entry->sps) == 0)
         {
             INIT(sp,
                 .src = src_ts->clone(src_ts),
                 .dst = dst_ts->clone(dst_ts),
             );
             array_insert(entry->sps, -1, sp);
             if (array_count(entry->sps) == sa->policy_count)
             {
                 if (!install(this, entry))
                 {
                     status = FAILED;
                 }
             }
         }
         else
         {
             /* TODO: reinstall with a filter using multiple TS?
              * Filters are ANDed for a match, but we could install a filter
              * with the inverse TS set using NOT-matches... */
             DBG1(DBG_KNL, "multiple transport mode traffic selectors not "
                  "supported by WFP");
             status = NOT_SUPPORTED;
         }
     }
     else
     {
         DBG1(DBG_KNL, "adding SP failed, no SA found for SPI 0x%08x", key.spi);
         status = FAILED;
     }
     this->mutex->unlock(this->mutex);
     return status;
 }
METHOD (kernel_ipsec_t , query_policy , status_t , private_kernel_wfp_ipsec_t * this, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, mark_t mark, time_t * use_time)
Definition at line 2449 of file kernel_wfp_ipsec.c.
References NOT_SUPPORTED.
 {
     /* see query_sa() for some notes */
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , del_policy , status_t , private_kernel_wfp_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 2458 of file kernel_wfp_ipsec.c.
References FALSE, NOT_FOUND, POLICY_OUT, POLICY_PRIORITY_ROUTED, remove_trap(), ipsec_sa_cfg_t::reqid, SUCCESS, and TRUE.
 {
     if (direction == POLICY_OUT && priority == POLICY_PRIORITY_ROUTED)
     {
         if (remove_trap(this, sa->reqid, FALSE, src_ts, dst_ts))
         {
             remove_trap(this, sa->reqid, TRUE, src_ts, dst_ts);
             return SUCCESS;
         }
         return NOT_FOUND;
     }
     /* not required, as we delete the whole SA/SP set during del_sa() */
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , flush_policies , status_t , private_kernel_wfp_ipsec_t * this)
Definition at line 2477 of file kernel_wfp_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , bypass_socket , bool , private_kernel_wfp_ipsec_t * this, int fd, int family)
Definition at line 2545 of file kernel_wfp_ipsec.c.
References add_bypass(), array_insert(), ARRAY_TAIL, FALSE, getsockname, handle, in, mutex_t::lock, mutex, port, TRUE, and mutex_t::unlock.
 {
     union {
         struct sockaddr sa;
         SOCKADDR_IN in;
         SOCKADDR_IN6 in6;
     } saddr;
     int addrlen = sizeof(saddr);
     UINT64 filter_out, filter_in = 0;
     u_int16_t port;
     if (getsockname(fd, &saddr.sa, &addrlen) == SOCKET_ERROR)
     {
         return FALSE;
     }
     switch (family)
     {
         case AF_INET:
             port = ntohs(saddr.in.sin_port);
             break;
         case AF_INET6:
             port = ntohs(saddr.in6.sin6_port);
             break;
         default:
             return FALSE;
     }
     if (!add_bypass(this, family, port, TRUE, &filter_in) ||
         !add_bypass(this, family, port, FALSE, &filter_out))
     {
         if (filter_in)
         {
             FwpmFilterDeleteById0(this->handle, filter_in);
         }
         return FALSE;
     }
     this->mutex->lock(this->mutex);
     array_insert(this->bypass, ARRAY_TAIL, &filter_in);
     array_insert(this->bypass, ARRAY_TAIL, &filter_out);
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
METHOD (kernel_ipsec_t , enable_udp_decap , bool , private_kernel_wfp_ipsec_t * this, int fd, int family, u_int16_t port)
Definition at line 2591 of file kernel_wfp_ipsec.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (kernel_ipsec_t , destroy , void , private_kernel_wfp_ipsec_t * this)
Definition at line 2597 of file kernel_wfp_ipsec.c.
References array_destroy(), array_remove(), ARRAY_TAIL, mutex_t::destroy, event, filter(), free(), handle, and mutex.
 {
     UINT64 filter;
     while (array_remove(this->bypass, ARRAY_TAIL, &filter))
     {
         FwpmFilterDeleteById0(this->handle, filter);
     }
     if (this->handle)
     {
         if (this->event)
         {
             FwpmNetEventUnsubscribe0(this->handle, this->event);
         }
         FwpmProviderDeleteByKey0(this->handle, &this->provider.providerKey);
         FwpmEngineClose0(this->handle);
     }
     array_destroy(this->bypass);
     this->tsas->destroy(this->tsas);
     this->isas->destroy(this->isas);
     this->osas->destroy(this->osas);
     this->routes->destroy(this->routes);
     this->traps->destroy(this->traps);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static u_int permute (u_int x, u_int p) static
Map an integer x with a one-to-one function using quadratic residues.
Definition at line 1969 of file kernel_wfp_ipsec.c.
Referenced by METHOD().
 {
     u_int qr;
     x = x % p;
     qr = ((u_int64_t)x * x) % p;
     if (x <= p / 2)
     {
         return qr;
     }
     return p - qr;
 }
static u_int32_t prefix2mask (u_int8_t prefix) static
Convert an IPv4 prefix to a host order subnet mask
Definition at line 352 of file kernel_wfp_ipsec.c.
References prefix, and untoh32().
Referenced by ts2condition().
 {
     u_int8_t netmask[4] = {};
     int i;
     for (i = 0; i < sizeof(netmask); i++)
     {
         if (prefix < 8)
         {
             netmask[i] = 0xFF << (8 - prefix);
             break;
         }
         netmask[i] = 0xFF;
         prefix -= 8;
     }
     return untoh32(netmask);
 }
static void range2cond (FWPM_FILTER_CONDITION0 * cond, u_int16_t from, u_int16_t to) static
Convert a 16-bit range to a WFP condition
Definition at line 373 of file kernel_wfp_ipsec.c.
References from, and to.
Referenced by ts2condition().
 {
     if (from == to)
     {
         cond->matchType = FWP_MATCH_EQUAL;
         cond->conditionValue.type = FWP_UINT16;
         cond->conditionValue.uint16 = from;
     }
     else
     {
         cond->matchType = FWP_MATCH_RANGE;
         cond->conditionValue.type = FWP_RANGE_TYPE;
         cond->conditionValue.rangeValue = calloc(1, sizeof(FWP_RANGE0));
         cond->conditionValue.rangeValue->valueLow.type = FWP_UINT16;
         cond->conditionValue.rangeValue->valueLow.uint16 = from;
         cond->conditionValue.rangeValue->valueHigh.type = FWP_UINT16;
         cond->conditionValue.rangeValue->valueHigh.uint16 = to;
     }
 }
static bool register_events (private_kernel_wfp_ipsec_t * this) static
Register for net events
Definition at line 1764 of file kernel_wfp_ipsec.c.
References DBG1, DBG_KNL, DWORD, event, event_callback(), FALSE, FwpmNetEventSubscribe0, handle, res, subscription, and TRUE.
Referenced by kernel_wfp_ipsec_create().
 {
     FWPM_NET_EVENT_SUBSCRIPTION0 subscription = {};
     DWORD res;
     res = FwpmNetEventSubscribe0(this->handle, &subscription,
                                  event_callback, this, &this->event);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "registering for WFP events failed: 0x%08x", res);
         return FALSE;
     }
     return TRUE;
 }
static bool remove_trap (private_kernel_wfp_ipsec_t * this, u_int32_t reqid, bool fwd, traffic_selector_t * src, traffic_selector_t * dst) static
Uninstall and remove a new trap entry
Definition at line 1900 of file kernel_wfp_ipsec.c.
References enumerator_t::destroy, destroy_trap(), trap_t::dst, enumerator_t::enumerate, traffic_selector_t::equals, FALSE, found, trap_t::fwd, trap_t::local, mutex_t::lock, manage_route(), mutex, trap_t::remote, trap_t::reqid, trap_t::route, trap_t::src, TRUE, uninstall_trap(), and mutex_t::unlock.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     trap_t *trap, *found = NULL;
     this->mutex->lock(this->mutex);
     enumerator = this->traps->create_enumerator(this->traps);
     while (enumerator->enumerate(enumerator, NULL, &trap))
     {
         if (reqid == trap->reqid &&
             fwd == trap->fwd &&
             src->equals(src, trap->src) &&
             dst->equals(dst, trap->dst))
         {
             this->traps->remove_at(this->traps, enumerator);
             found = trap;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     if (found)
     {
         if (trap->route)
         {
             trap->route = !manage_route(this, trap->local, trap->remote,
                                         src, dst, FALSE);
         }
         uninstall_trap(this, found);
         destroy_trap(found);
         return TRUE;
     }
     return FALSE;
 }
static void schedule_expire (private_kernel_wfp_ipsec_t * this, u_int32_t spi, host_t * dst, u_int32_t lifetime, bool hard) static
Schedule an expire event for an SA
Definition at line 2082 of file kernel_wfp_ipsec.c.
References callback_job_create(), host_t::clone, data, expire_data_destroy(), expire_job(), INIT, lib, scheduler_t::schedule_job, and library_t::scheduler.
Referenced by METHOD().
 {
     expire_data_t *data;
     INIT(data,
         .this = this,
         .spi = spi,
         .dst = dst->clone(dst),
         .hard = hard,
     );
     lib->scheduler->schedule_job(lib->scheduler, (job_t*)
                         callback_job_create((void*)expire_job, data,
                                             (void*)expire_data_destroy, NULL),
                         lifetime);
 }
static void sp_entry_destroy (sp_entry_t * sp) static
Destroy an SP entry
Definition at line 162 of file kernel_wfp_ipsec.c.
References traffic_selector_t::destroy, sp_entry_t::dst, free(), and sp_entry_t::src.
Referenced by entry_destroy().
 {
     sp->src->destroy(sp->src);
     sp->dst->destroy(sp->dst);
     free(sp);
 }
static bool ts2condition (traffic_selector_t * ts, const GUID * target, FWPM_FILTER_CONDITION0 * conds[], int * count) static
(Re-)allocate filter conditions for given local or remote traffic selector
Definition at line 397 of file kernel_wfp_ipsec.c.
References addr, append_condition(), host_t::destroy, FALSE, from, from_code, from_port, from_type, FWPM_CONDITION_ICMP_CODE, FWPM_CONDITION_ICMP_TYPE, FWPM_CONDITION_IP_LOCAL_ADDRESS, FWPM_CONDITION_IP_LOCAL_PORT, FWPM_CONDITION_IP_PROTOCOL, FWPM_CONDITION_IP_REMOTE_ADDRESS, FWPM_CONDITION_IP_REMOTE_PORT, host_t::get_family, traffic_selector_t::get_from_address, traffic_selector_t::get_from_port, traffic_selector_t::get_protocol, traffic_selector_t::get_to_address, traffic_selector_t::get_to_port, traffic_selector_t::get_type, traffic_selector_t::is_host, malloc(), memcpy, net, prefix, prefix2mask(), proto, chunk_t::ptr, range2cond(), to, to_code, to_port, traffic_selector_t::to_subnet, to_type, traffic_selector_icmp_code(), traffic_selector_icmp_type(), TRUE, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and untoh32().
Referenced by install_ipip_ale(), install_sp(), and install_trap().
 {
     FWPM_FILTER_CONDITION0 *cond;
     FWP_BYTE_ARRAY16 *addr;
     FWP_RANGE0 *range;
     u_int16_t from_port, to_port;
     void *from, *to;
     u_int8_t proto;
     host_t *net;
     u_int8_t prefix;
     from = ts->get_from_address(ts).ptr;
     to = ts->get_to_address(ts).ptr;
     from_port = ts->get_from_port(ts);
     to_port = ts->get_to_port(ts);
     cond = append_condition(conds, count);
     cond->fieldKey = *target;
     if (ts->is_host(ts, NULL))
     {
         cond->matchType = FWP_MATCH_EQUAL;
         switch (ts->get_type(ts))
         {
             case TS_IPV4_ADDR_RANGE:
                 cond->conditionValue.type = FWP_UINT32;
                 cond->conditionValue.uint32 = untoh32(from);
                 break;
             case TS_IPV6_ADDR_RANGE:
                 cond->conditionValue.type = FWP_BYTE_ARRAY16_TYPE;
                 cond->conditionValue.byteArray16 = addr = malloc(sizeof(*addr));
                 memcpy(addr, from, sizeof(*addr));
                 break;
             default:
                 return FALSE;
         }
     }
     else if (ts->to_subnet(ts, &net, &prefix))
     {
         FWP_V6_ADDR_AND_MASK *m6;
         FWP_V4_ADDR_AND_MASK *m4;
         cond->matchType = FWP_MATCH_EQUAL;
         switch (net->get_family(net))
         {
             case AF_INET:
                 cond->conditionValue.type = FWP_V4_ADDR_MASK;
                 cond->conditionValue.v4AddrMask = m4 = calloc(1, sizeof(*m4));
                 m4->addr = untoh32(from);
                 m4->mask = prefix2mask(prefix);
                 break;
             case AF_INET6:
                 cond->conditionValue.type = FWP_V6_ADDR_MASK;
                 cond->conditionValue.v6AddrMask = m6 = calloc(1, sizeof(*m6));
                 memcpy(m6->addr, from, sizeof(m6->addr));
                 m6->prefixLength = prefix;
                 break;
             default:
                 net->destroy(net);
                 return FALSE;
         }
         net->destroy(net);
     }
     else
     {
         cond->matchType = FWP_MATCH_RANGE;
         cond->conditionValue.type = FWP_RANGE_TYPE;
         cond->conditionValue.rangeValue = range = calloc(1, sizeof(*range));
         switch (ts->get_type(ts))
         {
             case TS_IPV4_ADDR_RANGE:
                 range->valueLow.type = FWP_UINT32;
                 range->valueLow.uint32 = untoh32(from);
                 range->valueHigh.type = FWP_UINT32;
                 range->valueHigh.uint32 = untoh32(to);
                 break;
             case TS_IPV6_ADDR_RANGE:
                 range->valueLow.type = FWP_BYTE_ARRAY16_TYPE;
                 range->valueLow.byteArray16 = addr = malloc(sizeof(*addr));
                 memcpy(addr, from, sizeof(*addr));
                 range->valueHigh.type = FWP_BYTE_ARRAY16_TYPE;
                 range->valueHigh.byteArray16 = addr = malloc(sizeof(*addr));
                 memcpy(addr, to, sizeof(*addr));
                 break;
             default:
                 return FALSE;
         }
     }
     proto = ts->get_protocol(ts);
     if (proto && target == &FWPM_CONDITION_IP_LOCAL_ADDRESS)
     {
         cond = append_condition(conds, count);
         cond->fieldKey = FWPM_CONDITION_IP_PROTOCOL;
         cond->matchType = FWP_MATCH_EQUAL;
         cond->conditionValue.type = FWP_UINT8;
         cond->conditionValue.uint8 = proto;
     }
     if (proto == IPPROTO_ICMP)
     {
         if (target == &FWPM_CONDITION_IP_LOCAL_ADDRESS)
         {
             u_int8_t from_type, to_type, from_code, to_code;
             from_type = traffic_selector_icmp_type(from_port);
             to_type = traffic_selector_icmp_type(to_port);
             from_code = traffic_selector_icmp_code(from_port);
             to_code = traffic_selector_icmp_code(to_port);
             if (from_type != 0 || to_type != 0xFF)
             {
                 cond = append_condition(conds, count);
                 cond->fieldKey = FWPM_CONDITION_ICMP_TYPE;
                 range2cond(cond, from_type, to_type);
             }
             if (from_code != 0 || to_code != 0xFF)
             {
                 cond = append_condition(conds, count);
                 cond->fieldKey = FWPM_CONDITION_ICMP_CODE;
                 range2cond(cond, from_code, to_code);
             }
         }
     }
     else if (from_port != 0 || to_port != 0xFFFF)
     {
         if (target == &FWPM_CONDITION_IP_LOCAL_ADDRESS)
         {
             cond = append_condition(conds, count);
             cond->fieldKey = FWPM_CONDITION_IP_LOCAL_PORT;
             range2cond(cond, from_port, to_port);
         }
         if (target == &FWPM_CONDITION_IP_REMOTE_ADDRESS)
         {
             cond = append_condition(conds, count);
             cond->fieldKey = FWPM_CONDITION_IP_REMOTE_PORT;
             range2cond(cond, from_port, to_port);
         }
     }
     return TRUE;
 }
static bool uninstall_route (private_kernel_wfp_ipsec_t * this, host_t * dst, u_int8_t mask, host_t * src, host_t * gtw) static
Reduce refcount, or uninstall a route if all refs gone
Definition at line 1382 of file kernel_wfp_ipsec.c.
References kernel_interface_t::del_route, destroy_route(), dst, FALSE, free(), host_t::get_address, kernel_interface_t::get_interface, hydra, hydra_t::kernel_interface, key, mutex_t::lock, mask, mutex, name, route_t::refs, res, src, SUCCESS, TRUE, and mutex_t::unlock.
Referenced by manage_route().
 {
     route_t *route, key = {
         .dst = dst,
         .mask = mask,
         .src = src,
     };
     char *name;
     bool res = FALSE;
     this->mutex->lock(this->mutex);
     route = this->routes->get(this->routes, &key);
     if (route)
     {
         if (--route->refs == 0)
         {
             if (hydra->kernel_interface->get_interface(hydra->kernel_interface,
                                                        src, &name))
             {
                 res = hydra->kernel_interface->del_route(hydra->kernel_interface,
                         dst->get_address(dst), mask, gtw, src, name) == SUCCESS;
                 free(name);
             }
             route = this->routes->remove(this->routes, route);
             if (route)
             {
                 destroy_route(route);
             }
         }
         else
         {
             res = TRUE;
         }
     }
     this->mutex->unlock(this->mutex);
     return res;
 }
static bool uninstall_trap (private_kernel_wfp_ipsec_t * this, trap_t * trap) static
Uninstall a trap policy from kernel
Definition at line 1852 of file kernel_wfp_ipsec.c.
References DBG1, DBG_KNL, DWORD, FALSE, trap_t::filter_id, handle, res, and TRUE.
Referenced by remove_trap().
 {
     DWORD res;
     res = FwpmFilterDeleteById0(this->handle, trap->filter_id);
     if (res != ERROR_SUCCESS)
     {
         DBG1(DBG_KNL, "uninstalling WFP trap filter failed: 0x%08x", res);
         return FALSE;
     }
     return TRUE;
 }