strongSwan: initiate_mediation_job
initiate_mediation_job
jobs
Classes
struct initiate_mediation_job_t
Typedefs
typedef struct
initiate_mediation_job_t initiate_mediation_job_t
Functions
initiate_mediation_job_t * initiate_mediation_job_create (ike_sa_id_t *ike_sa_id)
initiate_mediation_job_t * reinitiate_mediation_job_create (ike_sa_id_t *mediation_sa_id, ike_sa_id_t *mediated_sa_id)
Detailed Description
Typedef Documentation
typedef struct initiate_mediation_job_t initiate_mediation_job_t
Definition at line 24 of file initiate_mediation_job.h.
Function Documentation
initiate_mediation_job_t* initiate_mediation_job_create (ike_sa_id_t * ike_sa_id)
Creates a job of type INITIATE_MEDIATION.
Parameters
ike_sa_id identification of the ike_sa as ike_sa_id_t object (gets cloned)
Returns
job object
Definition at line 245 of file initiate_mediation_job.c.
References ike_sa_id_t::clone, and initiate_mediation_job_create_empty().
Referenced by METHOD().
 {
     private_initiate_mediation_job_t *this = initiate_mediation_job_create_empty();
     this->public.job_interface.execute = _initiate;
     this->mediated_sa_id = ike_sa_id->clone(ike_sa_id);
     return &this->public;
 }
initiate_mediation_job_t* reinitiate_mediation_job_create (ike_sa_id_t * mediation_sa_id, ike_sa_id_t * mediated_sa_id)
Creates a special job of type INITIATE_MEDIATION that reinitiates a specific connection.
Parameters
mediation_sa_id identification of the mediation sa (gets cloned)
mediated_sa_id identification of the mediated sa (gets cloned)
Returns
job object
Definition at line 258 of file initiate_mediation_job.c.
References ike_sa_id_t::clone, and initiate_mediation_job_create_empty().
Referenced by METHOD().
 {
     private_initiate_mediation_job_t *this = initiate_mediation_job_create_empty();
     this->public.job_interface.execute = _reinitiate;
     this->mediation_sa_id = mediation_sa_id->clone(mediation_sa_id);
     this->mediated_sa_id = mediated_sa_id->clone(mediated_sa_id);
     return &this->public;
 }