strongSwan: pkcs12_decode
pkcs12_decode
pkcs12
Functions
pkcs12_t * pkcs12_decode (container_type_t type, va_list args)
Detailed Description
Function Documentation
pkcs12_t* pkcs12_decode (container_type_t type, va_list args)
Load a PKCS#12 container.
The argument list must contain a single BUILD_BLOB_ASN1_DER argument.
Parameters
type type of the container, CONTAINER_PKCS12
args builder_part_t argument list
Returns
container, NULL on failure
See header.
Definition at line 546 of file pkcs12_decode.c.
References ASN1_SEQUENCE, blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, destroy(), chunk_t::len, parse_PFX(), pkcs12_create(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     private_pkcs12_t *this;
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.len)
     {
         if (blob.len >= 2 &&
             blob.ptr[0] == ASN1_SEQUENCE && blob.ptr[1] == 0x80)
         {   /* looks like infinite length BER encoding, but we can't handle it.
              */
             return NULL;
         }
         this = pkcs12_create();
         if (parse_PFX(this, blob))
         {
             return &this->public;
         }
         destroy(this);
     }
     return NULL;
 }