strongSwan: pkcs7_signed_data.c File Reference
pkcs7_signed_data.c File Reference
#include "pkcs7_signed_data.h"
#include "pkcs7_attributes.h"
#include <time.h>
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <credentials/sets/mem_cred.h>
#include <credentials/certificates/x509.h>
#include <credentials/keys/private_key.h>
Classes
struct private_pkcs7_signed_data_t
struct signerinfo_t
struct signature_enumerator_t
Macros
#define PKCS7_VERSION 1
#define PKCS7_DIGEST_ALG 3
#define PKCS7_CONTENT_INFO 5
#define PKCS7_CERT 7
#define PKCS7_SIGNER_INFO 13
#define PKCS7_SIGNER_INFO_VERSION 14
#define PKCS7_ISSUER 16
#define PKCS7_SERIAL_NUMBER 17
#define PKCS7_DIGEST_ALGORITHM 18
#define PKCS7_AUTH_ATTRIBUTES 19
#define PKCS7_DIGEST_ENC_ALGORITHM 21
#define PKCS7_ENCRYPTED_DIGEST 22
Typedefs
typedef struct
private_pkcs7_signed_data_t private_pkcs7_signed_data_t
Functions
void signerinfo_destroy (signerinfo_t *this)
METHOD (container_t, get_type, container_type_t, private_pkcs7_signed_data_t *this)
METHOD (enumerator_t, enumerate, bool, signature_enumerator_t *this, auth_cfg_t **out)
METHOD (enumerator_t, enumerator_destroy, void, signature_enumerator_t *this)
METHOD (container_t, create_signature_enumerator, enumerator_t *, private_pkcs7_signed_data_t *this)
METHOD (pkcs7_t, get_attribute, bool, private_pkcs7_signed_data_t *this, int oid, enumerator_t *enumerator, chunk_t *value)
METHOD (pkcs7_t, create_cert_enumerator, enumerator_t *, private_pkcs7_signed_data_t *this)
METHOD (container_t, get_data, bool, private_pkcs7_signed_data_t *this, chunk_t *data)
METHOD (container_t, get_encoding, bool, private_pkcs7_signed_data_t *this, chunk_t *data)
METHOD (container_t, destroy, void, private_pkcs7_signed_data_t *this)
static
private_pkcs7_signed_data_t * create_empty ()
static bool parse (private_pkcs7_signed_data_t *this, chunk_t content)
pkcs7_t * pkcs7_signed_data_load (chunk_t encoding, chunk_t content)
static chunk_t build_issuerAndSerialNumber (certificate_t *cert)
static bool generate (private_pkcs7_signed_data_t *this, private_key_t *key, certificate_t *cert, hash_algorithm_t alg, pkcs7_attributes_t *pkcs9)
pkcs7_t * pkcs7_signed_data_gen (container_type_t type, va_list args)
Variables
static const asn1Object_t signedDataObjects []
Macro Definition Documentation
#define PKCS7_AUTH_ATTRIBUTES 19
Definition at line 155 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_CERT 7
Definition at line 149 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_CONTENT_INFO 5
Definition at line 148 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_DIGEST_ALG 3
Definition at line 147 of file pkcs7_signed_data.c.
#define PKCS7_DIGEST_ALGORITHM 18
Definition at line 154 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_DIGEST_ENC_ALGORITHM 21
Definition at line 156 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_ENCRYPTED_DIGEST 22
Definition at line 157 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_ISSUER 16
Definition at line 152 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_SERIAL_NUMBER 17
Definition at line 153 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_SIGNER_INFO 13
Definition at line 150 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_SIGNER_INFO_VERSION 14
Definition at line 151 of file pkcs7_signed_data.c.
Referenced by parse().
#define PKCS7_VERSION 1
Definition at line 146 of file pkcs7_signed_data.c.
Referenced by parse().
Typedef Documentation
typedef struct private_pkcs7_signed_data_t private_pkcs7_signed_data_t
Definition at line 29 of file pkcs7_signed_data.c.
Function Documentation
static chunk_t build_issuerAndSerialNumber (certificate_t * cert) static
build a DER-encoded issuerAndSerialNumber object
Definition at line 500 of file pkcs7_signed_data.c.
References asn1_integer(), ASN1_SEQUENCE, asn1_wrap(), CERT_X509, chunk_empty, identification_t::get_encoding, certificate_t::get_issuer, x509_t::get_serial, and certificate_t::get_type.
Referenced by generate().
 {
     identification_t *issuer = cert->get_issuer(cert);
     chunk_t serial = chunk_empty;
     if (cert->get_type(cert) == CERT_X509)
     {
         x509_t *x509 = (x509_t*)cert;
         serial = x509->get_serial(x509);
     }
     return asn1_wrap(ASN1_SEQUENCE, "cm",
                      issuer->get_encoding(issuer),
                      asn1_integer("c", serial));
 }
static private_pkcs7_signed_data_t* create_empty (void) static
Create an empty PKCS#7 signed-data container.
Definition at line 371 of file pkcs7_signed_data.c.
References INIT, linked_list_create(), and mem_cred_create().
Referenced by pkcs7_signed_data_gen(), and pkcs7_signed_data_load().
 {
     private_pkcs7_signed_data_t *this;
     INIT(this,
         .public = {
             .container = {
                 .get_type = _get_type,
                 .create_signature_enumerator = _create_signature_enumerator,
                 .get_data = _get_data,
                 .get_encoding = _get_encoding,
                 .destroy = _destroy,
             },
             .get_attribute = _get_attribute,
             .create_cert_enumerator = _create_cert_enumerator,
         },
         .creds = mem_cred_create(),
         .signerinfos = linked_list_create(),
     );
     return this;
 }
static bool generate (private_pkcs7_signed_data_t * this, private_key_t * key, certificate_t * cert, hash_algorithm_t alg, pkcs7_attributes_t * pkcs9) static
Generate a new PKCS#7 signed-data container
Definition at line 519 of file pkcs7_signed_data.c.
References pkcs7_attributes_t::add_attribute, hasher_t::allocate_hash, asn1_algorithmIdentifier(), asn1_build_known_oid(), ASN1_CONTEXT_C_0, asn1_from_time(), ASN1_INTEGER_1, ASN1_OCTET_STRING, ASN1_SEQUENCE, ASN1_SET, ASN1_UTCTIME, asn1_wrap(), attributes, build_issuerAndSerialNumber(), CERT_ASN1_DER, chunk_clone, chunk_empty, crypto_factory_t::create_hasher, library_t::crypto, data, DBG1, DBG_LIB, pkcs7_attributes_t::destroy, hasher_t::destroy, DESTROY_IF, encoding, FALSE, free(), pkcs7_attributes_t::get_encoding, certificate_t::get_encoding, hash_algorithm_names, hasher, hasher_algorithm_to_oid(), lib, OID_PKCS7_DATA, OID_PKCS7_SIGNED_DATA, OID_PKCS9_CONTENT_TYPE, OID_PKCS9_MESSAGE_DIGEST, OID_PKCS9_SIGNING_TIME, OID_RSA_ENCRYPTION, chunk_t::ptr, scheme, private_key_t::sign, signature_scheme_from_oid(), and TRUE.
Referenced by pkcs7_signed_data_gen().
 {
     chunk_t authenticatedAttributes = chunk_empty;
     chunk_t encryptedDigest = chunk_empty;
     chunk_t data, signerInfo, encoding = chunk_empty;
     chunk_t messageDigest, signingTime, attributes;
     signature_scheme_t scheme;
     hasher_t *hasher;
     time_t now;
     int digest_oid;
     digest_oid = hasher_algorithm_to_oid(alg);
     scheme = signature_scheme_from_oid(digest_oid);
     if (!this->content->get_data(this->content, &data))
     {
         return FALSE;
     }
     hasher = lib->crypto->create_hasher(lib->crypto, alg);
     if (!hasher || !hasher->allocate_hash(hasher, data, &messageDigest))
     {
         DESTROY_IF(hasher);
         DBG1(DBG_LIB, "  hash algorithm %N not support",
              hash_algorithm_names, alg);
         free(data.ptr);
         return FALSE;
     }
     hasher->destroy(hasher);
     pkcs9->add_attribute(pkcs9,
                     OID_PKCS9_MESSAGE_DIGEST,
                     asn1_wrap(ASN1_OCTET_STRING, "m", messageDigest));
     /* take the current time as signingTime */
     now = time(NULL);
     signingTime = asn1_from_time(&now, ASN1_UTCTIME);
     pkcs9->add_attribute(pkcs9, OID_PKCS9_SIGNING_TIME, signingTime);
     pkcs9->add_attribute(pkcs9, OID_PKCS9_CONTENT_TYPE,
                          asn1_build_known_oid(OID_PKCS7_DATA));
     attributes = pkcs9->get_encoding(pkcs9);
     if (!key->sign(key, scheme, attributes, &encryptedDigest))
     {
         free(data.ptr);
         return FALSE;
     }
     authenticatedAttributes = chunk_clone(attributes);
     *authenticatedAttributes.ptr = ASN1_CONTEXT_C_0;
     free(data.ptr);
     if (encryptedDigest.ptr)
     {
         encryptedDigest = asn1_wrap(ASN1_OCTET_STRING, "m", encryptedDigest);
     }
     signerInfo = asn1_wrap(ASN1_SEQUENCE, "cmmmmm",
                     ASN1_INTEGER_1,
                     build_issuerAndSerialNumber(cert),
                     asn1_algorithmIdentifier(digest_oid),
                     authenticatedAttributes,
                     asn1_algorithmIdentifier(OID_RSA_ENCRYPTION),
                     encryptedDigest);
     if (!cert->get_encoding(cert, CERT_ASN1_DER, &encoding))
     {
         free(signerInfo.ptr);
         return FALSE;
     }
     if (!this->content->get_encoding(this->content, &data))
     {
         free(encoding.ptr);
         free(signerInfo.ptr);
         return FALSE;
     }
     this->encoding = asn1_wrap(ASN1_SEQUENCE, "mm",
         asn1_build_known_oid(OID_PKCS7_SIGNED_DATA),
         asn1_wrap(ASN1_CONTEXT_C_0, "m",
             asn1_wrap(ASN1_SEQUENCE, "cmmmm",
                 ASN1_INTEGER_1,
                 asn1_wrap(ASN1_SET, "m", asn1_algorithmIdentifier(digest_oid)),
                 data,
                 asn1_wrap(ASN1_CONTEXT_C_0, "m", encoding),
                 asn1_wrap(ASN1_SET, "m", signerInfo))));
     pkcs9->destroy(pkcs9);
     /* TODO: create signerInfos entry */
     return TRUE;
 }
METHOD (container_t , get_type , container_type_t , private_pkcs7_signed_data_t * this)
Definition at line 159 of file pkcs7_signed_data.c.
References CONTAINER_PKCS7_SIGNED_DATA.
 {
     return CONTAINER_PKCS7_SIGNED_DATA;
 }
METHOD (enumerator_t , enumerate , bool , signature_enumerator_t * this, auth_cfg_t ** out)
Definition at line 181 of file pkcs7_signed_data.c.
References algorithm, hasher_t::allocate_hash, signerinfo_t::attributes, cert, chunk_equals_const(), auth_cfg_t::clone, crypto_factory_t::create_hasher, credential_manager_t::create_trusted_enumerator, library_t::credmgr, library_t::crypto, DBG1, DBG3, DBG_LIB, enumerator_t::destroy, hasher_t::destroy, public_key_t::destroy, DESTROY_IF, signerinfo_t::digest_alg, signerinfo_t::enc_alg, signerinfo_t::encrypted_digest, enumerator_t::enumerate, identification_t::equals, FALSE, free(), pkcs7_attributes_t::get_attribute, pkcs7_attributes_t::get_encoding, certificate_t::get_issuer, certificate_t::get_public_key, hash, hash_algorithm_names, hasher, hasher_algorithm_from_oid(), signerinfo_t::issuer, key, KEY_RSA, chunk_t::len, lib, OID_PKCS9_MESSAGE_DIGEST, OID_RSA_ENCRYPTION, chunk_t::ptr, scheme, signerinfo_t::serial, SIGN_UNKNOWN, signature_scheme_from_oid(), TRUE, valid, and public_key_t::verify.
 {
     signerinfo_t *info;
     signature_scheme_t scheme;
     hash_algorithm_t algorithm;
     enumerator_t *enumerator;
     certificate_t *cert;
     public_key_t *key;
     auth_cfg_t *auth;
     chunk_t chunk, hash, content;
     hasher_t *hasher;
     bool valid;
     while (this->inner->enumerate(this->inner, &info))
     {
         /* clean up previous round */
         DESTROY_IF(this->auth);
         this->auth = NULL;
         scheme = signature_scheme_from_oid(info->digest_alg);
         if (scheme == SIGN_UNKNOWN)
         {
             DBG1(DBG_LIB, "unsupported signature scheme");
             continue;
         }
         if (!info->attributes)
         {
             DBG1(DBG_LIB, "no authenticatedAttributes object found");
             continue;
         }
         if (info->enc_alg != OID_RSA_ENCRYPTION)
         {
             DBG1(DBG_LIB, "only RSA digest encryption supported");
             continue;
         }
         enumerator = lib->credmgr->create_trusted_enumerator(lib->credmgr,
                                                 KEY_RSA, info->serial, FALSE);
         while (enumerator->enumerate(enumerator, &cert, &auth))
         {
             if (info->issuer->equals(info->issuer, cert->get_issuer(cert)))
             {
                 key = cert->get_public_key(cert);
                 if (key)
                 {
                     chunk = info->attributes->get_encoding(info->attributes);
                     if (key->verify(key, scheme, chunk, info->encrypted_digest))
                     {
                         this->auth = auth->clone(auth);
                         key->destroy(key);
                         break;
                     }
                     key->destroy(key);
                 }
             }
         }
         enumerator->destroy(enumerator);
         if (!this->auth)
         {
             DBG1(DBG_LIB, "unable to verify pkcs7 attributes signature");
             continue;
         }
         chunk = info->attributes->get_attribute(info->attributes,
                                                 OID_PKCS9_MESSAGE_DIGEST);
         if (!chunk.len)
         {
             DBG1(DBG_LIB, "messageDigest attribute not found");
             continue;
         }
         if (!this->this->content->get_data(this->this->content, &content))
         {
             continue;
         }
         algorithm = hasher_algorithm_from_oid(info->digest_alg);
         hasher = lib->crypto->create_hasher(lib->crypto, algorithm);
         if (!hasher || !hasher->allocate_hash(hasher, content, &hash))
         {
             free(content.ptr);
             DESTROY_IF(hasher);
             DBG1(DBG_LIB, "hash algorithm %N not supported",
                  hash_algorithm_names, algorithm);
             continue;
         }
         free(content.ptr);
         hasher->destroy(hasher);
         DBG3(DBG_LIB, "hash: %B", &hash);
         valid = chunk_equals_const(chunk, hash);
         free(hash.ptr);
         if (!valid)
         {
             DBG1(DBG_LIB, "invalid messageDigest");
             continue;
         }
         *out = this->auth;
         this->info = info;
         return TRUE;
     }
     this->info = NULL;
     return FALSE;
 }
METHOD (enumerator_t , enumerator_destroy , void , signature_enumerator_t * this)
Definition at line 287 of file pkcs7_signed_data.c.
References library_t::credmgr, DESTROY_IF, free(), lib, and credential_manager_t::remove_local_set.
 {
     lib->credmgr->remove_local_set(lib->credmgr, &this->this->creds->set);
     this->inner->destroy(this->inner);
     DESTROY_IF(this->auth);
     free(this);
 }
METHOD (container_t , create_signature_enumerator , enumerator_t * , private_pkcs7_signed_data_t * this)
Definition at line 296 of file pkcs7_signed_data.c.
References credential_manager_t::add_local_set, library_t::credmgr, destroy(), FALSE, INIT, lib, and signature_enumerator_t::public.
 {
     signature_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_enumerate,
             .destroy = _enumerator_destroy,
         },
         .inner = this->signerinfos->create_enumerator(this->signerinfos),
         .this = this,
     );
     lib->credmgr->add_local_set(lib->credmgr, &this->creds->set, FALSE);
     return &enumerator->public;
 }
METHOD (pkcs7_t , get_attribute , bool , private_pkcs7_signed_data_t * this, int oid, enumerator_t * enumerator, chunk_t * value)
Definition at line 314 of file pkcs7_signed_data.c.
References signerinfo_t::attributes, chunk_clone, FALSE, pkcs7_attributes_t::get_attribute, signature_enumerator_t::info, chunk_t::len, and TRUE.
 {
     signature_enumerator_t *e;
     chunk_t chunk;
     e = (signature_enumerator_t*)enumerator;
     if (e->info)
     {
         chunk = e->info->attributes->get_attribute(e->info->attributes, oid);
         if (chunk.len)
         {
             *value = chunk_clone(chunk);
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (pkcs7_t , create_cert_enumerator , enumerator_t * , private_pkcs7_signed_data_t * this)
Definition at line 333 of file pkcs7_signed_data.c.
References CERT_ANY, credential_set_t::create_cert_enumerator, creds, FALSE, KEY_ANY, and mem_cred_t::set.
 {
     return this->creds->set.create_cert_enumerator(&this->creds->set,
                                             CERT_ANY, KEY_ANY, NULL, FALSE);
 }
METHOD (container_t , get_data , bool , private_pkcs7_signed_data_t * this, chunk_t * data)
Definition at line 340 of file pkcs7_signed_data.c.
References FALSE.
 {
     if (this->content)
     {
         return this->content->get_data(this->content, data);
     }
     return FALSE;
 }
METHOD (container_t , get_encoding , bool , private_pkcs7_signed_data_t * this, chunk_t * data)
Definition at line 350 of file pkcs7_signed_data.c.
References chunk_clone, encoding, and TRUE.
 {
     *data = chunk_clone(this->encoding);
     return TRUE;
 }
METHOD (container_t , destroy , void , private_pkcs7_signed_data_t * this)
Definition at line 357 of file pkcs7_signed_data.c.
References creds, mem_cred_t::destroy, DESTROY_IF, encoding, free(), and signerinfo_destroy().
 {
     this->creds->destroy(this->creds);
     this->signerinfos->destroy_function(this->signerinfos,
                                         (void*)signerinfo_destroy);
     DESTROY_IF(this->content);
     free(this->encoding.ptr);
     free(this);
 }
static bool parse (private_pkcs7_signed_data_t * this, chunk_t content) static
Parse PKCS#7 signed data
Definition at line 397 of file pkcs7_signed_data.c.
References mem_cred_t::add_cert, ASN1_CONTEXT_C_0, asn1_parse_algorithmIdentifier(), asn1_parser_create(), ASN1_SET, signerinfo_t::attributes, BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, chunk_clone, CONTAINER_PKCS7, credential_factory_t::create, CRED_CERTIFICATE, CRED_CONTAINER, creds, library_t::creds, DBG2, DBG_LIB, asn1_parser_t::destroy, signerinfo_t::digest_alg, signerinfo_t::enc_alg, signerinfo_t::encrypted_digest, FALSE, asn1_parser_t::get_level, ID_DER_ASN1_DN, ID_KEY_ID, identification_create_from_encoding(), INIT, signerinfo_t::issuer, asn1_parser_t::iterate, lib, OID_UNKNOWN, parser, pkcs7_attributes_create_from_chunk(), PKCS7_AUTH_ATTRIBUTES, PKCS7_CERT, PKCS7_CONTENT_INFO, PKCS7_DIGEST_ALGORITHM, PKCS7_DIGEST_ENC_ALGORITHM, PKCS7_ENCRYPTED_DIGEST, PKCS7_ISSUER, PKCS7_SERIAL_NUMBER, PKCS7_SIGNER_INFO, PKCS7_SIGNER_INFO_VERSION, PKCS7_VERSION, signerinfo_t::serial, asn1_parser_t::set_top_level, asn1_parser_t::success, and version.
Referenced by pkcs7_signed_data_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID, version;
     signerinfo_t *info = NULL;
     bool success = FALSE;
     parser = asn1_parser_create(signedDataObjects, content);
     parser->set_top_level(parser, 0);
     while (parser->iterate(parser, &objectID, &object))
     {
         u_int level = parser->get_level(parser);
         switch (objectID)
         {
             case PKCS7_VERSION:
                 version = object.len ? (int)*object.ptr : 0;
                 DBG2(DBG_LIB, "  v%d", version);
                 break;
             case PKCS7_CONTENT_INFO:
                 this->content = lib->creds->create(lib->creds,
                                         CRED_CONTAINER, CONTAINER_PKCS7,
                                         BUILD_BLOB_ASN1_DER, object, BUILD_END);
                 break;
             case PKCS7_CERT:
             {
                 certificate_t *cert;
                 DBG2(DBG_LIB, "  parsing pkcs7-wrapped certificate");
                 cert = lib->creds->create(lib->creds,
                                           CRED_CERTIFICATE, CERT_X509,
                                           BUILD_BLOB_ASN1_DER, object,
                                           BUILD_END);
                 if (cert)
                 {
                     this->creds->add_cert(this->creds, FALSE, cert);
                 }
                 break;
             }
             case PKCS7_SIGNER_INFO:
                 INIT(info,
                     .digest_alg = OID_UNKNOWN,
                     .enc_alg = OID_UNKNOWN,
                 );
                 this->signerinfos->insert_last(this->signerinfos, info);
                 break;
             case PKCS7_SIGNER_INFO_VERSION:
                 version = object.len ? (int)*object.ptr : 0;
                 DBG2(DBG_LIB, "  v%d", version);
                 break;
             case PKCS7_ISSUER:
                 info->issuer = identification_create_from_encoding(
                                                         ID_DER_ASN1_DN, object);
                 break;
             case PKCS7_SERIAL_NUMBER:
                 info->serial = identification_create_from_encoding(
                                                         ID_KEY_ID, object);
                 break;
             case PKCS7_AUTH_ATTRIBUTES:
                 *object.ptr = ASN1_SET;
                 info->attributes = pkcs7_attributes_create_from_chunk(
                                                         object, level+1);
                 *object.ptr = ASN1_CONTEXT_C_0;
                 break;
             case PKCS7_DIGEST_ALGORITHM:
                 info->digest_alg = asn1_parse_algorithmIdentifier(object,
                                                         level, NULL);
                 break;
             case PKCS7_DIGEST_ENC_ALGORITHM:
                 info->enc_alg = asn1_parse_algorithmIdentifier(object,
                                                         level, NULL);
                 break;
             case PKCS7_ENCRYPTED_DIGEST:
                 info->encrypted_digest = chunk_clone(object);
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     return success;
 }
void signerinfo_destroy (signerinfo_t * this)
Destroy a signerinfo_t entry
Definition at line 102 of file pkcs7_signed_data.c.
References attributes, DESTROY_IF, and free().
Referenced by METHOD().
 {
     DESTROY_IF(this->attributes);
     DESTROY_IF(this->serial);
     DESTROY_IF(this->issuer);
     free(this->encrypted_digest.ptr);
     free(this);
 }
Variable Documentation
const asn1Object_t signedDataObjects[] static
ASN.1 definition of the PKCS#7 signedData type
Definition at line 114 of file pkcs7_signed_data.c.