strongSwan: pubkey_cert.c File Reference
pubkey_cert.c File Reference
#include "pubkey_cert.h"
#include <time.h>
#include <utils/debug.h>
Classes
struct private_pubkey_cert_t
Typedefs
typedef struct
private_pubkey_cert_t private_pubkey_cert_t
Functions
METHOD (certificate_t, get_type, certificate_type_t, private_pubkey_cert_t *this)
METHOD (certificate_t, get_subject, identification_t *, private_pubkey_cert_t *this)
METHOD (certificate_t, get_issuer, identification_t *, private_pubkey_cert_t *this)
METHOD (certificate_t, has_subject, id_match_t, private_pubkey_cert_t *this, identification_t *subject)
METHOD (certificate_t, has_issuer, id_match_t, private_pubkey_cert_t *this, identification_t *issuer)
METHOD (certificate_t, equals, bool, private_pubkey_cert_t *this, certificate_t *other)
METHOD (certificate_t, issued_by, bool, private_pubkey_cert_t *this, certificate_t *issuer, signature_scheme_t *scheme)
METHOD (certificate_t, get_public_key, public_key_t *, private_pubkey_cert_t *this)
METHOD (certificate_t, get_validity, bool, private_pubkey_cert_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_pubkey_cert_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, get_ref, certificate_t *, private_pubkey_cert_t *this)
METHOD (certificate_t, destroy, void, private_pubkey_cert_t *this)
static pubkey_cert_t * pubkey_cert_create (public_key_t *key, time_t notBefore, time_t notAfter, identification_t *subject)
pubkey_cert_t * pubkey_cert_wrap (certificate_type_t type, va_list args)
Typedef Documentation
typedef struct private_pubkey_cert_t private_pubkey_cert_t
Definition at line 22 of file pubkey_cert.c.
Function Documentation
METHOD (certificate_t , get_type , certificate_type_t , private_pubkey_cert_t * this)
Definition at line 65 of file pubkey_cert.c.
References CERT_TRUSTED_PUBKEY.
 {
     return CERT_TRUSTED_PUBKEY;
 }
METHOD (certificate_t , get_subject , identification_t * , private_pubkey_cert_t * this)
Definition at line 71 of file pubkey_cert.c.
References subject.
 {
     return this->subject;
 }
METHOD (certificate_t , get_issuer , identification_t * , private_pubkey_cert_t * this)
Definition at line 77 of file pubkey_cert.c.
 {
     return this->issuer;
 }
METHOD (certificate_t , has_subject , id_match_t , private_pubkey_cert_t * this, identification_t * subject)
Definition at line 83 of file pubkey_cert.c.
References chunk_equals(), CRED_ENCODING_MAX, fingerprint, identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, ID_MATCH_PERFECT, key, identification_t::matches, and type.
 {
     if (subject->get_type(subject) == ID_KEY_ID)
     {
         cred_encoding_type_t type;
         chunk_t fingerprint;
         for (type = 0; type < CRED_ENCODING_MAX; type++)
         {
             if (this->key->get_fingerprint(this->key, type, &fingerprint) &&
                 chunk_equals(fingerprint, subject->get_encoding(subject)))
             {
                 return ID_MATCH_PERFECT;
             }
         }
     }
     return this->subject->matches(this->subject, subject);
 }
METHOD (certificate_t , has_issuer , id_match_t , private_pubkey_cert_t * this, identification_t * issuer)
Definition at line 104 of file pubkey_cert.c.
References ID_MATCH_NONE.
 {
     return ID_MATCH_NONE;
 }
METHOD (certificate_t , equals , bool , private_pubkey_cert_t * this, certificate_t * other)
Definition at line 110 of file pubkey_cert.c.
References CERT_TRUSTED_PUBKEY, public_key_t::destroy, identification_t::equals, FALSE, certificate_t::get_public_key, certificate_t::get_subject, certificate_t::get_type, key, public_key_equals(), subject, and TRUE.
 {
     identification_t *other_subject;
     public_key_t *other_key;
     if (this == (private_pubkey_cert_t*)other)
     {
         return TRUE;
     }
     if (other->get_type(other) != CERT_TRUSTED_PUBKEY)
     {
         return FALSE;
     }
     other_key = other->get_public_key(other);
     if (other_key)
     {
         if (public_key_equals(this->key, other_key))
         {
             other_key->destroy(other_key);
             other_subject = other->get_subject(other);
             return other_subject->equals(other_subject, this->subject);
         }
         other_key->destroy(other_key);
     }
     return FALSE;
 }
METHOD (certificate_t , issued_by , bool , private_pubkey_cert_t * this, certificate_t * issuer, signature_scheme_t * scheme)
Definition at line 138 of file pubkey_cert.c.
References equals(), and SIGN_UNKNOWN.
 {
     if (scheme)
     {
         *scheme = SIGN_UNKNOWN;
     }
     return equals(this, issuer);
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_pubkey_cert_t * this)
Definition at line 149 of file pubkey_cert.c.
References key.
 {
     this->key->get_ref(this->key);
     return this->key;
 }
METHOD (certificate_t , get_validity , bool , private_pubkey_cert_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 156 of file pubkey_cert.c.
References UNDEFINED_TIME.
 {
     time_t t = when ? *when : time(NULL);
     if (not_before)
     {
         *not_before = this->notBefore;
     }
     if (not_after)
     {
         *not_after = this->notAfter;
     }
     return ((this->notBefore == UNDEFINED_TIME || t >= this->notBefore) &&
             (this->notAfter  == UNDEFINED_TIME || t <= this->notAfter));
 }
METHOD (certificate_t , get_encoding , bool , private_pubkey_cert_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 174 of file pubkey_cert.c.
References key.
 {
     return this->key->get_encoding(this->key, type, encoding);
 }
METHOD (certificate_t , get_ref , certificate_t * , private_pubkey_cert_t * this)
Definition at line 180 of file pubkey_cert.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.interface;
 }
METHOD (certificate_t , destroy , void , private_pubkey_cert_t * this)
Definition at line 187 of file pubkey_cert.c.
References free(), key, ref_put(), and subject.
 {
     if (ref_put(&this->ref))
     {
         this->subject->destroy(this->subject);
         this->issuer->destroy(this->issuer);
         this->key->destroy(this->key);
         free(this);
     }
 }
static pubkey_cert_t* pubkey_cert_create (public_key_t * key, time_t notBefore, time_t notAfter, identification_t * subject) static
Definition at line 202 of file pubkey_cert.c.
References chunk_empty, identification_t::clone, fingerprint, public_key_t::get_fingerprint, ID_ANY, ID_KEY_ID, identification_create_from_encoding(), INIT, key, and KEYID_PUBKEY_INFO_SHA1.
Referenced by pubkey_cert_wrap().
 {
     private_pubkey_cert_t *this;
     chunk_t fingerprint;
     INIT(this,
         .public = {
             .interface = {
                 .get_type = _get_type,
                 .get_subject = _get_subject,
                 .get_issuer = _get_issuer,
                 .has_subject = _has_subject,
                 .has_issuer = _has_issuer,
                 .issued_by = _issued_by,
                 .get_public_key = _get_public_key,
                 .get_validity = _get_validity,
                 .get_encoding = _get_encoding,
                 .equals = _equals,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
         .key = key,
         .notBefore = notBefore,
         .notAfter = notAfter,
         .issuer = identification_create_from_encoding(ID_ANY, chunk_empty),
     );
     if (subject)
     {
         this->subject = subject->clone(subject);
     }
     else if (key->get_fingerprint(key, KEYID_PUBKEY_INFO_SHA1, &fingerprint))
     {
         this->subject = identification_create_from_encoding(ID_KEY_ID, fingerprint);
     }
     else
     {
         this->subject = identification_create_from_encoding(ID_ANY, chunk_empty);
     }
     return &this->public;
 }