strongSwan: ietf_attr
ietf_attr
libimcv
Modules
ietf_attr_assess_result
ietf_attr_attr_request
ietf_attr_fwd_enabled
ietf_attr_installed_packages
ietf_attr_numeric_version
ietf_attr_op_status
ietf_attr_pa_tnc_error
ietf_attr_port_filter
ietf_attr_product_info
ietf_attr_remediation_instr
ietf_attr_string_version
pwg_attr_vendor_smi_code
Typedefs
typedef enum ietf_attr_t ietf_attr_t
Enumerations
enum ietf_attr_t {
IETF_ATTR_TESTING = 0, IETF_ATTR_ATTRIBUTE_REQUEST = 1, IETF_ATTR_PRODUCT_INFORMATION = 2, IETF_ATTR_NUMERIC_VERSION = 3,
IETF_ATTR_STRING_VERSION = 4, IETF_ATTR_OPERATIONAL_STATUS = 5, IETF_ATTR_PORT_FILTER = 6, IETF_ATTR_INSTALLED_PACKAGES = 7,
IETF_ATTR_PA_TNC_ERROR = 8, IETF_ATTR_ASSESSMENT_RESULT = 9, IETF_ATTR_REMEDIATION_INSTRUCTIONS = 10, IETF_ATTR_FORWARDING_ENABLED = 11,
IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED = 12, IETF_ATTR_RESERVED = 0xffffffff
}
Functions
pa_tnc_attr_t * ietf_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Variables
enum_name_t * ietf_attr_names
Detailed Description
Typedef Documentation
typedef enum ietf_attr_t ietf_attr_t
Definition at line 28 of file ietf_attr.h.
Enumeration Type Documentation
enum ietf_attr_t
IETF standard PA-TNC attribute types defined by RFC 5792
Enumerator
IETF_ATTR_TESTING
IETF_ATTR_ATTRIBUTE_REQUEST
IETF_ATTR_PRODUCT_INFORMATION
IETF_ATTR_NUMERIC_VERSION
IETF_ATTR_STRING_VERSION
IETF_ATTR_OPERATIONAL_STATUS
IETF_ATTR_PORT_FILTER
IETF_ATTR_INSTALLED_PACKAGES
IETF_ATTR_PA_TNC_ERROR
IETF_ATTR_ASSESSMENT_RESULT
IETF_ATTR_REMEDIATION_INSTRUCTIONS
IETF_ATTR_FORWARDING_ENABLED
IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED
IETF_ATTR_RESERVED
Definition at line 33 of file ietf_attr.h.
                  {
     IETF_ATTR_TESTING =                            0,
     IETF_ATTR_ATTRIBUTE_REQUEST =                  1,
     IETF_ATTR_PRODUCT_INFORMATION =                2,
     IETF_ATTR_NUMERIC_VERSION =                    3,
     IETF_ATTR_STRING_VERSION =                     4,
     IETF_ATTR_OPERATIONAL_STATUS =                 5,
     IETF_ATTR_PORT_FILTER =                        6,
     IETF_ATTR_INSTALLED_PACKAGES =                 7,
     IETF_ATTR_PA_TNC_ERROR =                       8,
     IETF_ATTR_ASSESSMENT_RESULT =                  9,
     IETF_ATTR_REMEDIATION_INSTRUCTIONS =          10,
     IETF_ATTR_FORWARDING_ENABLED =                11,
     IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED =       12,
     IETF_ATTR_RESERVED =                  0xffffffff,
 };
Function Documentation
pa_tnc_attr_t* ietf_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Create an IETF PA-TNC attribute from data
Parameters
type attribute type
length attribute length
value attribute value or segment
See header
Definition at line 50 of file ietf_attr.c.
References generic_attr_bool_create_from_data(), ietf_attr_assess_result_create_from_data(), IETF_ATTR_ASSESSMENT_RESULT, ietf_attr_attr_request_create_from_data(), IETF_ATTR_ATTRIBUTE_REQUEST, IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED, IETF_ATTR_FORWARDING_ENABLED, ietf_attr_fwd_enabled_create_from_data(), IETF_ATTR_INSTALLED_PACKAGES, ietf_attr_installed_packages_create_from_data(), IETF_ATTR_NUMERIC_VERSION, ietf_attr_numeric_version_create_from_data(), ietf_attr_op_status_create_from_data(), IETF_ATTR_OPERATIONAL_STATUS, IETF_ATTR_PA_TNC_ERROR, ietf_attr_pa_tnc_error_create_from_data(), IETF_ATTR_PORT_FILTER, ietf_attr_port_filter_create_from_data(), ietf_attr_product_info_create_from_data(), IETF_ATTR_PRODUCT_INFORMATION, ietf_attr_remediation_instr_create_from_data(), IETF_ATTR_REMEDIATION_INSTRUCTIONS, IETF_ATTR_RESERVED, IETF_ATTR_STRING_VERSION, ietf_attr_string_version_create_from_data(), IETF_ATTR_TESTING, PEN_IETF, and pen_type_create().
Referenced by libimcv_init().
 {
     switch (type)
     {
         case IETF_ATTR_ATTRIBUTE_REQUEST:
             return ietf_attr_attr_request_create_from_data(length, value);
         case IETF_ATTR_PRODUCT_INFORMATION:
             return ietf_attr_product_info_create_from_data(length, value);
         case IETF_ATTR_NUMERIC_VERSION:
             return ietf_attr_numeric_version_create_from_data(length, value);
         case IETF_ATTR_STRING_VERSION:
             return ietf_attr_string_version_create_from_data(length, value);
         case IETF_ATTR_OPERATIONAL_STATUS:
             return ietf_attr_op_status_create_from_data(length, value);
         case IETF_ATTR_PORT_FILTER:
             return ietf_attr_port_filter_create_from_data(length, value,
                                     pen_type_create(PEN_IETF, type));
         case IETF_ATTR_INSTALLED_PACKAGES:
             return ietf_attr_installed_packages_create_from_data(length, value);
         case IETF_ATTR_PA_TNC_ERROR:
             return ietf_attr_pa_tnc_error_create_from_data(length, value);
         case IETF_ATTR_ASSESSMENT_RESULT:
             return ietf_attr_assess_result_create_from_data(length, value);
         case IETF_ATTR_REMEDIATION_INSTRUCTIONS:
             return ietf_attr_remediation_instr_create_from_data(length, value);
         case IETF_ATTR_FORWARDING_ENABLED:
             return ietf_attr_fwd_enabled_create_from_data(length, value,
                                     pen_type_create(PEN_IETF, type));
         case IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED:
             return generic_attr_bool_create_from_data(length, value,
                                     pen_type_create(PEN_IETF, type));
         case IETF_ATTR_TESTING:
         case IETF_ATTR_RESERVED:
         default:
             return NULL;
     }
 }
Variable Documentation
enum_name_t* ietf_attr_names
enum name for ietf_attr_t.
Referenced by libimcv_init(), METHOD(), and receive_msg().