strongSwan: public key
public key
tkm
Classes
struct tkm_public_key_t
Typedefs
typedef struct tkm_public_key_t tkm_public_key_t
Functions
tkm_public_key_t * tkm_public_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct tkm_public_key_t tkm_public_key_t
Definition at line 27 of file tkm_public_key.h.
Function Documentation
tkm_public_key_t* tkm_public_key_load (key_type_t type, va_list args)
Load a TKM public key.
Parameters
type type of the key
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 123 of file tkm_public_key.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_clone, chunk_empty, INIT, chunk_t::ptr, public_key_equals(), public_key_has_fingerprint(), TRUE, and type.
Referenced by main().
 {
     private_tkm_public_key_t *this;
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!blob.ptr)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .verify = _verify,
                 .encrypt = _encrypt_,
                 .equals = public_key_equals,
                 .get_keysize = _get_keysize,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = public_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
         .asn_blob = chunk_clone(blob),
         .key_type = type,
     );
     return &this->public;
 }