strongSwan: certexpire_cron.c File Reference
certexpire_cron.c File Reference
#include "certexpire_cron.h"
#include <time.h>
#include <utils/debug.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_certexpire_cron_t
Typedefs
typedef struct
private_certexpire_cron_t private_certexpire_cron_t
Functions
static job_requeue_t check_cron (private_certexpire_cron_t *this)
static void parse_ranges (bool *fields, char *label, int mi, int ma, char *range)
static void start_cron (private_certexpire_cron_t *this, char *cron)
METHOD (certexpire_cron_t, destroy, void, private_certexpire_cron_t *this)
certexpire_cron_t * certexpire_cron_create (char *cron, certexpire_cron_job_t job, void *data)
Typedef Documentation
typedef struct private_certexpire_cron_t private_certexpire_cron_t
Definition at line 23 of file certexpire_cron.c.
Function Documentation
static job_requeue_t check_cron (private_certexpire_cron_t * this) static
Check if we should execute the export job
Definition at line 60 of file certexpire_cron.c.
References callback_job_create_with_prio(), data, JOB_PRIO_CRITICAL, JOB_REQUEUE_NONE, lib, localtime_r(), scheduler_t::schedule_job, and library_t::scheduler.
Referenced by start_cron().
 {
     struct tm tm;
     time_t t;
     t = time(NULL);
     localtime_r(&t, &tm);
     /* recheck every minute at second 0 */
     lib->scheduler->schedule_job(lib->scheduler,
             (job_t*)callback_job_create_with_prio((callback_job_cb_t)check_cron,
             this, NULL, NULL, JOB_PRIO_CRITICAL), 60 - tm.tm_sec);
     /* skip this minute if we had a large negative time shift */
     if (tm.tm_sec <= 30)
     {
         if (this->cron.m[tm.tm_min] &&
             this->cron.h[tm.tm_hour] &&
             this->cron.d[tm.tm_mday] &&
             this->cron.my[tm.tm_mon + 1] &&
             (this->cron.dw[tm.tm_wday] ||
              (this->cron.dw[7] && tm.tm_wday == 0)))
         {
             this->job(this->data);
         }
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (certexpire_cron_t , destroy , void , private_certexpire_cron_t * this)
Definition at line 202 of file certexpire_cron.c.
References free().
 {
     free(this);
 }
static void parse_ranges (bool * fields, char * label, int mi, int ma, char * range) static
Parse a cron range component into boolean fields
Definition at line 92 of file certexpire_cron.c.
References DBG1, DBG3, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), from, streq(), to, and TRUE.
Referenced by start_cron().
 {
     enumerator_t *enumerator;
     int from, to, i;
     if (streq(range, "*"))
     {
         for (i = mi; i <= ma; i++)
         {
             fields[i] = TRUE;
         }
     }
     else
     {
         enumerator = enumerator_create_token(range, ",", "");
         while (enumerator->enumerate(enumerator, &range))
         {
             switch (sscanf(range, "%d-%d", &from, &to))
             {
                 case 1: /* single value */
                     if (from >= mi && from <= ma)
                     {
                         fields[from] = TRUE;
                     }
                     else
                     {
                         DBG1(DBG_CFG, "ignoring cron %s %d, out of range",
                              label, from);
                     }
                     break;
                 case 2: /* range */
                     if (from < mi)
                     {
                         DBG1(DBG_CFG, "cron %s out of range, shortening start "
                              "from %d to %d", label, from, mi);
                         from = mi;
                     }
                     if (to > ma)
                     {
                         DBG1(DBG_CFG, "cron %s out of range, shortening end "
                              "from %d to %d", label, to, ma);
                         to = ma;
                     }
                     for (i = from; i <= to; i++)
                     {
                         fields[i] = TRUE;
                     }
                     break;
                 default:
                     break;
             }
         }
         enumerator->destroy(enumerator);
     }
     DBG3(DBG_CFG, "cron job with enabled %ss:", label);
     for (i = mi; i <= ma; i++)
     {
         if (fields[i])
         {
             DBG3(DBG_CFG, "  %d", i);
         }
     }
 }
static void start_cron (private_certexpire_cron_t * this, char * cron) static
Start cron processing, if configured
Definition at line 159 of file certexpire_cron.c.
References check_cron(), DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), and parse_ranges().
Referenced by certexpire_cron_create().
 {
     enumerator_t *enumerator;
     int i = 0;
     enumerator = enumerator_create_token(cron, " ", " ");
     for (i = 0; i < 5; i++)
     {
         if (!enumerator->enumerate(enumerator, &cron))
         {
             DBG1(DBG_CFG, "cron misses a field, using '*'");
             cron = "*";
         }
         switch (i)
         {
             case 0:
                 parse_ranges(this->cron.m, "minute", 0, 59, cron);
                 break;
             case 1:
                 parse_ranges(this->cron.h, "hour", 0, 23, cron);
                 break;
             case 2:
                 parse_ranges(this->cron.d, "day", 1, 31, cron);
                 break;
             case 3:
                 parse_ranges(this->cron.my, "month", 1, 12, cron);
                 break;
             case 4:
                 parse_ranges(this->cron.dw, "weekday", 0, 7, cron);
                 break;
             default:
                 break;
         }
     }
     if (enumerator->enumerate(enumerator, &cron))
     {
         DBG1(DBG_CFG, "ignoring extra fields in cron");
     }
     enumerator->destroy(enumerator);
     check_cron(this);
 }