strongSwan: bio_writer
bio_writer
bio
Classes
struct bio_writer_t
Typedefs
typedef struct bio_writer_t bio_writer_t
Functions
bio_writer_t * bio_writer_create (u_int32_t bufsize)
Detailed Description
Typedef Documentation
typedef struct bio_writer_t bio_writer_t
Definition at line 27 of file bio_writer.h.
Function Documentation
bio_writer_t* bio_writer_create (u_int32_t bufsize)
Create a bio_writer instance.
The size of the internal buffer is increased automatically by bufsize (or a default if not given) if the initial size does not suffice.
Parameters
bufsize initially allocated buffer size
See header
Definition at line 224 of file bio_writer.c.
References chunk_alloc, INIT, and max.
Referenced by add_unity_split_attribute(), build_application(), build_handshake(), build_public_key(), check_alerts(), do_sasl(), eap_payload_create_nak(), identity_attribute(), ietf_attr_remediation_instr_create_from_string(), imv_attestation_process(), merge_fragments(), METHOD(), negotiate_version(), parser_helper_create(), pb_pdp_referral_msg_create_from_fqdn(), pb_remediation_parameters_msg_create_from_string(), process_sasl(), pt_tls_write(), pts_dh_group_error_create(), pts_dh_nonce_error_create(), pts_hash_alg_error_create(), read_swid_tags(), send_certificate(), send_certificate_request(), send_client_hello(), send_op(), send_sasl_mechs(), send_supported_hash_algorithms(), START_TEST(), swid_error_create(), vici_builder_create(), and write_sasl().
 {
     private_bio_writer_t *this;
     INIT(this,
         .public = {
             .write_uint8 = _write_uint8,
             .write_uint16 = _write_uint16,
             .write_uint24 = _write_uint24,
             .write_uint32 = _write_uint32,
             .write_uint64 = _write_uint64,
             .write_data = _write_data,
             .write_data8 = _write_data8,
             .write_data16 = _write_data16,
             .write_data24 = _write_data24,
             .write_data32 = _write_data32,
             .wrap8 = _wrap8,
             .wrap16 = _wrap16,
             .wrap24 = _wrap24,
             .wrap32 = _wrap32,
             .skip = _skip,
             .get_buf = _get_buf,
             .extract_buf = _extract_buf,
             .destroy = _destroy,
         },
         .increase = bufsize ? max(bufsize, 4) : 32,
     );
     if (bufsize)
     {
         this->buf = chunk_alloc(bufsize);
     }
     return &this->public;
 }