strongSwan: certreq_payload.c File Reference
certreq_payload.c File Reference
#include <stddef.h>
#include <daemon.h>
#include <crypto/hashers/hasher.h>
#include <encoding/payloads/cert_payload.h>
#include "certreq_payload.h"
Classes
struct private_certreq_payload_t
struct keyid_enumerator_t
Typedefs
typedef struct
private_certreq_payload_t private_certreq_payload_t
typedef struct keyid_enumerator_t keyid_enumerator_t
Functions
METHOD (payload_t, verify, status_t, private_certreq_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_certreq_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_certreq_payload_t *this)
METHOD (payload_t, get_type, payload_type_t, private_certreq_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_certreq_payload_t *this)
METHOD (payload_t, set_next_type, void, private_certreq_payload_t *this, payload_type_t type)
METHOD (payload_t, get_length, size_t, private_certreq_payload_t *this)
METHOD (certreq_payload_t, get_dn, identification_t *, private_certreq_payload_t *this)
METHOD (certreq_payload_t, add_keyid, void, private_certreq_payload_t *this, chunk_t keyid)
METHOD (enumerator_t, keyid_enumerate, bool, keyid_enumerator_t *this, chunk_t *chunk)
METHOD (certreq_payload_t, create_keyid_enumerator, enumerator_t *, private_certreq_payload_t *this)
METHOD (certreq_payload_t, get_cert_type, certificate_type_t, private_certreq_payload_t *this)
METHOD2 (payload_t, certreq_payload_t, destroy, void, private_certreq_payload_t *this)
certreq_payload_t * certreq_payload_create (payload_type_t type)
certreq_payload_t * certreq_payload_create_type (certificate_type_t type)
certreq_payload_t * certreq_payload_create_dn (identification_t *id)
Variables
static encoding_rule_t encodings []
Typedef Documentation
typedef struct keyid_enumerator_t keyid_enumerator_t
Definition at line 181 of file certreq_payload.c.
typedef struct private_certreq_payload_t private_certreq_payload_t
Definition at line 26 of file certreq_payload.c.
Function Documentation
METHOD (payload_t , verify , status_t , private_certreq_payload_t * this)
Definition at line 111 of file certreq_payload.c.
References data, DBG1, DBG_ENC, ENC_X509_SIGNATURE, encoding, FAILED, HASH_SIZE_SHA1, PLV2_CERTREQ, SUCCESS, and type.
 {
     if (this->type == PLV2_CERTREQ &&
         this->encoding == ENC_X509_SIGNATURE)
     {
         if (this->data.len % HASH_SIZE_SHA1)
         {
             DBG1(DBG_ENC, "invalid X509 hash length (%d) in certreq",
                  this->data.len);
             return FAILED;
         }
     }
     return SUCCESS;
 }
METHOD (payload_t , get_encoding_rules , int , private_certreq_payload_t * this, encoding_rule_t ** rules)
Definition at line 127 of file certreq_payload.c.
References countof, and encodings.
 {
     *rules = encodings;
     return countof(encodings);
 }
METHOD (payload_t , get_header_length , int , private_certreq_payload_t * this)
Definition at line 134 of file certreq_payload.c.
 {
     return 5;
 }
METHOD (payload_t , get_type , payload_type_t , private_certreq_payload_t * this)
Definition at line 140 of file certreq_payload.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_certreq_payload_t * this)
Definition at line 146 of file certreq_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_certreq_payload_t * this, payload_type_t type)
Definition at line 152 of file certreq_payload.c.
References type.
 {
     this->next_payload = type;
 }
METHOD (payload_t , get_length , size_t , private_certreq_payload_t * this)
Definition at line 158 of file certreq_payload.c.
 {
     return this->payload_length;
 }
METHOD (certreq_payload_t , get_dn , identification_t * , private_certreq_payload_t * this)
Definition at line 164 of file certreq_payload.c.
References data, ID_DER_ASN1_DN, and identification_create_from_encoding().
 {
     if (this->data.len)
     {
         return identification_create_from_encoding(ID_DER_ASN1_DN, this->data);
     }
     return NULL;
 }
METHOD (certreq_payload_t , add_keyid , void , private_certreq_payload_t * this, chunk_t keyid)
Definition at line 174 of file certreq_payload.c.
References chunk_cat, data, and chunk_t::len.
 {
     this->data = chunk_cat("mc", this->data, keyid);
     this->payload_length += keyid.len;
 }
METHOD (enumerator_t , keyid_enumerate , bool , keyid_enumerator_t * this, chunk_t * chunk)
Definition at line 192 of file certreq_payload.c.
References FALSE, HASH_SIZE_SHA1, chunk_t::len, chunk_t::ptr, and TRUE.
 {
     if (this->pos == NULL)
     {
         this->pos = this->full.ptr;
     }
     else
     {
         this->pos += HASH_SIZE_SHA1;
         if (this->pos > (this->full.ptr + this->full.len - HASH_SIZE_SHA1))
         {
             this->pos = NULL;
         }
     }
     if (this->pos)
     {
         chunk->ptr = this->pos;
         chunk->len = HASH_SIZE_SHA1;
         return TRUE;
     }
     return FALSE;
 }
METHOD (certreq_payload_t , create_keyid_enumerator , enumerator_t * , private_certreq_payload_t * this)
Definition at line 216 of file certreq_payload.c.
References data, destroy(), enumerator_create_empty(), free(), INIT, PLV1_CERTREQ, keyid_enumerator_t::public, and type.
 {
     keyid_enumerator_t *enumerator;
     if (this->type == PLV1_CERTREQ)
     {
         return enumerator_create_empty();
     }
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_keyid_enumerate,
             .destroy = (void*)free,
         },
         .full = this->data,
     );
     return &enumerator->public;
 }
METHOD (certreq_payload_t , get_cert_type , certificate_type_t , private_certreq_payload_t * this)
Definition at line 235 of file certreq_payload.c.
References CERT_ANY, CERT_X509, ENC_X509_SIGNATURE, and encoding.
 {
     switch (this->encoding)
     {
         case ENC_X509_SIGNATURE:
             return CERT_X509;
         default:
             return CERT_ANY;
     }
 }
METHOD2 (payload_t , certreq_payload_t , destroy , void , private_certreq_payload_t * this)
Definition at line 247 of file certreq_payload.c.
References chunk_free(), data, and free().
 {
     chunk_free(&this->data);
     free(this);
 }
Variable Documentation
encoding_rule_t encodings[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_certreq_payload_t, next_payload)   },
    { FLAG,             offsetof(private_certreq_payload_t, critical)       },
    { RESERVED_BIT,     offsetof(private_certreq_payload_t, reserved[0])    },
    { RESERVED_BIT,     offsetof(private_certreq_payload_t, reserved[1])    },
    { RESERVED_BIT,     offsetof(private_certreq_payload_t, reserved[2])    },
    { RESERVED_BIT,     offsetof(private_certreq_payload_t, reserved[3])    },
    { RESERVED_BIT,     offsetof(private_certreq_payload_t, reserved[4])    },
    { RESERVED_BIT,     offsetof(private_certreq_payload_t, reserved[5])    },
    { RESERVED_BIT,     offsetof(private_certreq_payload_t, reserved[6])    },
    { PAYLOAD_LENGTH,   offsetof(private_certreq_payload_t, payload_length) },
    { U_INT_8,          offsetof(private_certreq_payload_t, encoding)       },
    { CHUNK_DATA,       offsetof(private_certreq_payload_t, data)           }
}
Encoding rules for CERTREQ payload.
Definition at line 77 of file certreq_payload.c.
Referenced by METHOD().