strongSwan: pkcs11_library_t Struct Reference
pkcs11_library_t Struct Reference
pkcs11_library
#include "pkcs11_library.h"
Public Attributes
CK_FUNCTION_LIST_PTR f
char *(* get_name)(pkcs11_library_t *this)
pkcs11_feature_t(* get_features)(pkcs11_library_t *this)
enumerator_t *(* create_object_enumerator)(pkcs11_library_t *this, CK_SESSION_HANDLE session, CK_ATTRIBUTE_PTR tmpl, CK_ULONG tcount, CK_ATTRIBUTE_PTR attr, CK_ULONG acount)
enumerator_t *(* create_object_attr_enumerator)(pkcs11_library_t *this, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE object, CK_ATTRIBUTE_PTR attr, CK_ULONG count)
enumerator_t *(* create_mechanism_enumerator)(pkcs11_library_t *this, CK_SLOT_ID slot)
bool(* get_ck_attribute)(pkcs11_library_t *this, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE obj, CK_ATTRIBUTE_TYPE type, chunk_t *data)
void(* destroy)(pkcs11_library_t *this)
Detailed Description
A loaded and initialized PKCS#11 library.
Definition at line 49 of file pkcs11_library.h.
Member Data Documentation
enumerator_t*(* pkcs11_library_t::create_mechanism_enumerator)(pkcs11_library_t *this, CK_SLOT_ID slot)
Create an enumerator over supported mechanisms of a token.
The resulting enumerator enumerates over the mechanism type, and if a non-NULL pointer is given, over the mechanism info details.
Parameters
slot slot of the token
Returns
enumerator over (CK_MECHANISM_TYPE, CK_MECHANISM_INFO)
Definition at line 114 of file pkcs11_library.h.
Referenced by create_key(), find_token(), and print_mechs().
enumerator_t*(* pkcs11_library_t::create_object_attr_enumerator)(pkcs11_library_t *this, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE object, CK_ATTRIBUTE_PTR attr, CK_ULONG count)
This is very similar to the object enumerator but is only used to easily retrieve multiple attributes from a single object for which a handle is already known.
The given attribute array is automatically filled in with the associated attributes. If the value of an output attribute is NULL, the required memory gets allocated/freed during enumeration.
Parameters
session session to use
object object handle
attr attributes to read from object
count number of attributes to read
Definition at line 101 of file pkcs11_library.h.
enumerator_t*(* pkcs11_library_t::create_object_enumerator)(pkcs11_library_t *this, CK_SESSION_HANDLE session, CK_ATTRIBUTE_PTR tmpl, CK_ULONG tcount, CK_ATTRIBUTE_PTR attr, CK_ULONG acount)
Create an enumerator over CK_OBJECT_HANDLE using a search template.
An optional attribute array is automatically filled in with the objects associated attributes. If the value of an output attribute is NULL, the value gets allocated/freed during enumeration.
Parameters
session session to use
tmpl search template
tcount number of attributes in the search template
attr attributes to read from object
acount number of attributes to read
Definition at line 83 of file pkcs11_library.h.
Referenced by find_key(), find_key_by_keyid(), find_lib_by_keyid(), and pkcs11_creds_load().
void(* pkcs11_library_t::destroy)(pkcs11_library_t *this)
Destroy a pkcs11_library_t.
Definition at line 135 of file pkcs11_library.h.
Referenced by lib_entry_destroy().
CK_FUNCTION_LIST_PTR pkcs11_library_t::f
PKCS#11 function list, as returned by C_GetFunctionList
Definition at line 54 of file pkcs11_library.h.
Referenced by create_key(), dispatch_slot_events(), find_key(), find_key_by_keyid(), find_lib_by_keyid(), find_token(), get_slot_list(), handle_slot(), handle_token(), METHOD(), and pkcs11_creds_load().
bool(* pkcs11_library_t::get_ck_attribute)(pkcs11_library_t *this, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE obj, CK_ATTRIBUTE_TYPE type, chunk_t *data)
Retrieve a single attribute from the given object.
Memory for the data is allocated.
Parameters
session session with the PKCS#11 library
obj object handle
type attribute type to extract
data extracted data
Returns
TRUE if successful
Definition at line 128 of file pkcs11_library.h.
Referenced by find_key_by_keyid().
pkcs11_feature_t(* pkcs11_library_t::get_features)(pkcs11_library_t *this)
Get the feature set supported by this library.
Returns
ORed set of features supported
Definition at line 68 of file pkcs11_library.h.
char*(* pkcs11_library_t::get_name)(pkcs11_library_t *this)
Get the name this instance was created with.
Returns
name, as passed to constructor
Definition at line 61 of file pkcs11_library.h.
Referenced by create_key(), dispatch_slot_events(), find_key_by_keyid(), find_lib(), find_lib_by_keyid(), handle_slot(), pkcs11_creds_load(), and token_event_cb().
The documentation for this struct was generated from the following file:
pkcs11_library.h