strongSwan: pkcs11_dh
pkcs11_dh
pkcs11
Classes
struct pkcs11_dh_t
Typedefs
typedef struct pkcs11_dh_t pkcs11_dh_t
Functions
pkcs11_dh_t * pkcs11_dh_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Detailed Description
Typedef Documentation
typedef struct pkcs11_dh_t pkcs11_dh_t
Definition at line 24 of file pkcs11_dh.h.
Function Documentation
pkcs11_dh_t* pkcs11_dh_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Creates a new pkcs11_dh_t object.
Parameters
group Diffie Hellman group number to use
g generator in case group is MODP_CUSTOM
p prime in case group is MODP_CUSTOM
Returns
pkcs11_dh_t object, NULL if not supported
Described in header.
Definition at line 418 of file pkcs11_dh.c.
References create_ecp(), create_modp(), diffie_hellman_get_params(), ECP_192_BIT, ECP_224_BIT, ECP_256_BIT, ECP_384_BIT, ECP_521_BIT, ecparams_lookup(), diffie_hellman_params_t::exp_len, diffie_hellman_params_t::generator, chunk_t::len, MODP_CUSTOM, params, diffie_hellman_params_t::prime, and chunk_t::ptr.
Referenced by METHOD().
 {
     switch (group)
     {
         case MODP_CUSTOM:
         {
             return create_modp(group, p.len, g, p);
         }
         case ECP_192_BIT:
         case ECP_224_BIT:
         case ECP_256_BIT:
         case ECP_384_BIT:
         case ECP_521_BIT:
         {
             chunk_t params = ecparams_lookup(group);
             if (params.ptr)
             {
                 return create_ecp(group, params);
             }
             break;
         }
         default:
         {
             diffie_hellman_params_t *params = diffie_hellman_get_params(group);
             if (params)
             {
                 return create_modp(group, params->exp_len, params->generator,
                                    params->prime);
             }
             break;
         }
     }
     return NULL;
 }