strongSwan: pgp_encoder
pgp_encoder
pgp
Functions
bool pgp_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Detailed Description
Function Documentation
bool pgp_encoder_encode (cred_encoding_type_t type, chunk_t * encoding, va_list args)
Encoding function for PGP fingerprints.
See header.
Definition at line 62 of file pgp_encoder.c.
References build_v3_fingerprint(), FALSE, and KEYID_PGPV3.
Referenced by METHOD(), and pgp_plugin_create().
 {
     switch (type)
     {
         case KEYID_PGPV3:
             return build_v3_fingerprint(encoding, args);
         default:
             return FALSE;
     }
 }