strongSwan: addrblock_narrow.c File Reference
addrblock_narrow.c File Reference
#include "addrblock_narrow.h"
#include <daemon.h>
#include <credentials/certificates/x509.h>
Classes
struct private_addrblock_narrow_t
Typedefs
typedef struct
private_addrblock_narrow_t private_addrblock_narrow_t
Functions
static bool check_constraints (ike_sa_t *ike_sa, linked_list_t *list)
static void flush_ts_list (linked_list_t *list)
METHOD (listener_t, narrow, bool, private_addrblock_narrow_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, narrow_hook_t type, linked_list_t *local, linked_list_t *remote)
METHOD (addrblock_narrow_t, destroy, void, private_addrblock_narrow_t *this)
addrblock_narrow_t * addrblock_narrow_create ()
Typedef Documentation
typedef struct private_addrblock_narrow_t private_addrblock_narrow_t
Definition at line 23 of file addrblock_narrow.c.
Function Documentation
static bool check_constraints (ike_sa_t * ike_sa, linked_list_t * list) static
Check if the negotiated TS list is acceptable by X509 ipAddrBlock constraints
Definition at line 39 of file addrblock_narrow.c.
References AUTH_HELPER_SUBJECT_CERT, cert, CERT_X509, contained, ike_sa_t::create_auth_cfg_enumerator, linked_list_t::create_enumerator, x509_t::create_ipAddrBlock_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, auth_cfg_t::get, x509_t::get_flags, certificate_t::get_type, traffic_selector_t::is_contained_in, TRUE, and X509_IP_ADDR_BLOCKS.
Referenced by METHOD().
 {
     auth_cfg_t *auth;
     enumerator_t *auth_enum;
     certificate_t *cert = NULL;
     auth_enum = ike_sa->create_auth_cfg_enumerator(ike_sa, FALSE);
     while (auth_enum->enumerate(auth_enum, &auth))
     {
         cert = auth->get(auth, AUTH_HELPER_SUBJECT_CERT);
         if (cert)
         {
             break;
         }
     }
     auth_enum->destroy(auth_enum);
     if (cert && cert->get_type(cert) == CERT_X509)
     {
         x509_t *x509 = (x509_t*)cert;
         if (x509->get_flags(x509) & X509_IP_ADDR_BLOCKS)
         {
             enumerator_t *enumerator, *block_enum;
             traffic_selector_t *ts, *block_ts;
             DBG1(DBG_IKE, "checking certificate-based traffic selector "
                           "constraints [RFC 3779]");
             enumerator = list->create_enumerator(list);
             while (enumerator->enumerate(enumerator, &ts))
             {
                 bool contained = FALSE;
                 block_enum = x509->create_ipAddrBlock_enumerator(x509);
                 while (block_enum->enumerate(block_enum, &block_ts))
                 {
                     if (ts->is_contained_in(ts, block_ts))
                     {
                         DBG1(DBG_IKE, "  TS %R is contained in address block"
                                       " constraint %R", ts, block_ts);
                         contained = TRUE;
                         break;
                     }
                 }
                 block_enum->destroy(block_enum);
                 if (!contained)
                 {
                     DBG1(DBG_IKE, "  TS %R is not contained in any"
                                   " address block constraint", ts);
                     enumerator->destroy(enumerator);
                     return FALSE;
                 }
             }
             enumerator->destroy(enumerator);
         }
     }
     return TRUE;
 }
static void flush_ts_list (linked_list_t * list) static
Delete all traffic selectors in a list
Definition at line 102 of file addrblock_narrow.c.
References traffic_selector_t::destroy, linked_list_t::remove_last, and SUCCESS.
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     while (list->remove_last(list, (void**)&ts) == SUCCESS)
     {
         ts->destroy(ts);
     }
 }
METHOD (listener_t , narrow , bool , private_addrblock_narrow_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, narrow_hook_t type, linked_list_t * local, linked_list_t * remote)
Definition at line 112 of file addrblock_narrow.c.
References check_constraints(), flush_ts_list(), NARROW_INITIATOR_POST_AUTH, NARROW_INITIATOR_POST_NOAUTH, NARROW_RESPONDER, and TRUE.
 {
     switch (type)
     {
         case NARROW_RESPONDER:
         case NARROW_INITIATOR_POST_AUTH:
         case NARROW_INITIATOR_POST_NOAUTH:
             if (!check_constraints(ike_sa, remote))
             {
                 flush_ts_list(local);
                 flush_ts_list(remote);
             }
             break;
         default:
             break;
     }
     return TRUE;
 }
METHOD (addrblock_narrow_t , destroy , void , private_addrblock_narrow_t * this)
Definition at line 133 of file addrblock_narrow.c.
References free().
 {
     free(this);
 }