strongSwan: mem_pool.c File Reference
mem_pool.c File Reference
#include "mem_pool.h"
#include <library.h>
#include <hydra.h>
#include <utils/debug.h>
#include <collections/hashtable.h>
#include <collections/array.h>
#include <threading/mutex.h>
Classes
struct private_mem_pool_t
struct unique_lease_t
struct entry_t
struct lease_enumerator_t
Macros
#define POOL_LIMIT (sizeof(u_int)*8 - 1)
Typedefs
typedef struct private_mem_pool_t private_mem_pool_t
Functions
static entry_t * entry_create (identification_t *id)
static void entry_destroy (entry_t *this)
static u_int id_hash (identification_t *id)
static bool id_equals (identification_t *a, identification_t *b)
static host_t * offset2host (private_mem_pool_t *pool, int offset)
static int host2offset (private_mem_pool_t *pool, host_t *addr)
METHOD (mem_pool_t, get_name, const char *, private_mem_pool_t *this)
METHOD (mem_pool_t, get_base, host_t *, private_mem_pool_t *this)
METHOD (mem_pool_t, get_size, u_int, private_mem_pool_t *this)
METHOD (mem_pool_t, get_online, u_int, private_mem_pool_t *this)
METHOD (mem_pool_t, get_offline, u_int, private_mem_pool_t *this)
static u_int hash_addr (host_t *addr)
static int get_existing (private_mem_pool_t *this, identification_t *id, host_t *requested, host_t *peer)
static int get_new (private_mem_pool_t *this, identification_t *id, host_t *peer)
static int get_reassigned (private_mem_pool_t *this, identification_t *id, host_t *peer)
METHOD (mem_pool_t, acquire_address, host_t *, private_mem_pool_t *this, identification_t *id, host_t *requested, mem_pool_op_t operation, host_t *peer)
METHOD (mem_pool_t, release_address, bool, private_mem_pool_t *this, host_t *address, identification_t *id)
METHOD (enumerator_t, lease_enumerate, bool, lease_enumerator_t *this, identification_t **id, host_t **addr, bool *online)
METHOD (enumerator_t, lease_enumerator_destroy, void, lease_enumerator_t *this)
METHOD (mem_pool_t, create_lease_enumerator, enumerator_t *, private_mem_pool_t *this)
METHOD (mem_pool_t, destroy, void, private_mem_pool_t *this)
static private_mem_pool_t * create_generic (char *name)
static u_int network_id_diff (host_t *host, int hostbits)
mem_pool_t * mem_pool_create (char *name, host_t *base, int bits)
mem_pool_t * mem_pool_create_range (char *name, host_t *from, host_t *to)
Macro Definition Documentation
#define POOL_LIMIT (sizeof(u_int)*8 - 1)
Definition at line 26 of file mem_pool.c.
Referenced by mem_pool_create().
Typedef Documentation
typedef struct private_mem_pool_t private_mem_pool_t
Definition at line 28 of file mem_pool.c.
Function Documentation
static private_mem_pool_t* create_generic (char * name) static
Generic constructor
Definition at line 606 of file mem_pool.c.
References hashtable_create(), id_equals(), id_hash(), INIT, mutex_create(), MUTEX_TYPE_DEFAULT, and strdup.
Referenced by mem_pool_create(), and mem_pool_create_range().
 {
     private_mem_pool_t *this;
     INIT(this,
         .public = {
             .get_name = _get_name,
             .get_base = _get_base,
             .get_size = _get_size,
             .get_online = _get_online,
             .get_offline = _get_offline,
             .acquire_address = _acquire_address,
             .release_address = _release_address,
             .create_lease_enumerator = _create_lease_enumerator,
             .destroy = _destroy,
         },
         .name = strdup(name),
         .leases = hashtable_create((hashtable_hash_t)id_hash,
                                    (hashtable_equals_t)id_equals, 16),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     return this;
 }
static entry_t* entry_create (identification_t * id) static
Create a new entry
Definition at line 100 of file mem_pool.c.
References array_create(), identification_t::clone, and INIT.
Referenced by get_new(), and get_reassigned().
 {
     entry_t *entry;
     INIT(entry,
         .id = id->clone(id),
         .online = array_create(sizeof(unique_lease_t), 0),
         .offline = array_create(sizeof(u_int), 0),
     );
     return entry;
 }
static void entry_destroy (entry_t * this) static
Destroy an entry
Definition at line 115 of file mem_pool.c.
References array_destroy(), and free().
Referenced by get_reassigned(), and METHOD().
 {
     this->id->destroy(this->id);
     array_destroy(this->online);
     array_destroy(this->offline);
     free(this);
 }
static int get_existing (private_mem_pool_t * this, identification_t * id, host_t * requested, host_t * peer) static
Get an existing lease for id
Definition at line 273 of file mem_pool.c.
References array_create_enumerator(), array_insert(), array_remove_at(), ARRAY_TAIL, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, unique_lease_t::hash, hash_addr(), host2offset(), leases(), entry_t::offline, unique_lease_t::offset, offset, and entry_t::online.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     unique_lease_t *lease, reassign;
     u_int *current;
     entry_t *entry;
     int offset = 0;
     entry = this->leases->get(this->leases, id);
     if (!entry)
     {
         return 0;
     }
     /* check for a valid offline lease, refresh */
     enumerator = array_create_enumerator(entry->offline);
     if (enumerator->enumerate(enumerator, &current))
     {
         reassign.offset = offset = *current;
         reassign.hash = hash_addr(peer);
         array_insert(entry->online, ARRAY_TAIL, &reassign);
         array_remove_at(entry->offline, enumerator);
     }
     enumerator->destroy(enumerator);
     if (offset)
     {
         DBG1(DBG_CFG, "reassigning offline lease to '%Y'", id);
         return offset;
     }
     if (!peer)
     {
         return 0;
     }
     /* check for a valid online lease to reassign */
     enumerator = array_create_enumerator(entry->online);
     while (enumerator->enumerate(enumerator, &lease))
     {
         if (lease->offset == host2offset(this, requested) &&
             lease->hash == hash_addr(peer))
         {
             offset = lease->offset;
             /* add an additional "online" entry */
             array_insert(entry->online, ARRAY_TAIL, lease);
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (offset)
     {
         DBG1(DBG_CFG, "reassigning online lease to '%Y'", id);
     }
     return offset;
 }
static int get_new (private_mem_pool_t * this, identification_t * id, host_t * peer) static
Get a new lease for id
Definition at line 331 of file mem_pool.c.
References array_insert(), ARRAY_TAIL, DBG1, DBG_CFG, entry_create(), unique_lease_t::hash, hash_addr(), entry_t::id, leases(), unique_lease_t::offset, entry_t::online, size, and unused.
Referenced by METHOD().
 {
     entry_t *entry;
     unique_lease_t lease = {};
     if (this->unused < this->size)
     {
         entry = this->leases->get(this->leases, id);
         if (!entry)
         {
             entry = entry_create(id);
             this->leases->put(this->leases, entry->id, entry);
         }
         /* assigning offset, starting by 1 */
         lease.offset = ++this->unused + (this->base_is_network_id ? 1 : 0);
         lease.hash = hash_addr(peer);
         array_insert(entry->online, ARRAY_TAIL, &lease);
         DBG1(DBG_CFG, "assigning new lease to '%Y'", id);
     }
     return lease.offset;
 }
static int get_reassigned (private_mem_pool_t * this, identification_t * id, host_t * peer) static
Get a reassigned lease for id in case the pool is full
Definition at line 356 of file mem_pool.c.
References array_count(), ARRAY_HEAD, array_insert(), array_remove(), ARRAY_TAIL, DBG1, DBG_CFG, enumerator_t::destroy, entry_create(), entry_destroy(), enumerator_t::enumerate, unique_lease_t::hash, hash_addr(), entry_t::id, leases(), entry_t::offline, unique_lease_t::offset, and entry_t::online.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     u_int current;
     unique_lease_t lease = {};
     enumerator = this->leases->create_enumerator(this->leases);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         if (array_remove(entry->offline, ARRAY_HEAD, &current))
         {
             lease.offset = current;
             DBG1(DBG_CFG, "reassigning existing offline lease by '%Y' "
                  "to '%Y'", entry->id, id);
         }
         if (!array_count(entry->online) && !array_count(entry->offline))
         {
             this->leases->remove_at(this->leases, enumerator);
             entry_destroy(entry);
         }
         if (lease.offset)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (lease.offset)
     {
         entry = this->leases->get(this->leases, id);
         if (!entry)
         {
             entry = entry_create(id);
             this->leases->put(this->leases, entry->id, entry);
         }
         lease.hash = hash_addr(peer);
         array_insert(entry->online, ARRAY_TAIL, &lease);
     }
     return lease.offset;
 }
static u_int hash_addr (host_t * addr) static
Create a unique hash for a remote address
Definition at line 261 of file mem_pool.c.
References chunk_hash_inc(), host_t::get_address, and host_t::get_port.
Referenced by get_existing(), get_new(), and get_reassigned().
 {
     if (addr)
     {
         return chunk_hash_inc(addr->get_address(addr), addr->get_port(addr));
     }
     return 0;
 }
static int host2offset (private_mem_pool_t * pool, host_t * addr) static
convert a host to a pool offset
Definition at line 172 of file mem_pool.c.
References private_mem_pool_t::base, base, chunk_skip(), host_t::get_address, host_t::get_family, host, memeq(), chunk_t::ptr, and private_mem_pool_t::size.
Referenced by get_existing(), and METHOD().
 {
     chunk_t host, base;
     u_int32_t hosti, basei;
     if (addr->get_family(addr) != pool->base->get_family(pool->base))
     {
         return -1;
     }
     host = addr->get_address(addr);
     base = pool->base->get_address(pool->base);
     if (addr->get_family(addr) == AF_INET6)
     {
         /* only look at last /32 block */
         if (!memeq(host.ptr, base.ptr, 12))
         {
             return -1;
         }
         host = chunk_skip(host, 12);
         base = chunk_skip(base, 12);
     }
     hosti = ntohl(*(u_int32_t*)(host.ptr));
     basei = ntohl(*(u_int32_t*)(base.ptr));
     if (hosti > basei + pool->size)
     {
         return -1;
     }
     return hosti - basei + 1;
 }
static bool id_equals (identification_t * a, identification_t * b) static
hashtable equals function for identities
Definition at line 134 of file mem_pool.c.
References identification_t::equals.
Referenced by create_generic().
 {
     return a->equals(a, b);
 }
static u_int id_hash (identification_t * id) static
hashtable hash function for identities
Definition at line 126 of file mem_pool.c.
References chunk_hash(), and identification_t::get_encoding.
Referenced by create_generic().
 {
     return chunk_hash(id->get_encoding(id));
 }
METHOD (mem_pool_t , get_name , const char * , private_mem_pool_t * this)
Definition at line 202 of file mem_pool.c.
References name.
 {
     return this->name;
 }
METHOD (mem_pool_t , get_base , host_t * , private_mem_pool_t * this)
Definition at line 208 of file mem_pool.c.
References base.
 {
     return this->base;
 }
METHOD (mem_pool_t , get_size , u_int , private_mem_pool_t * this)
Definition at line 214 of file mem_pool.c.
References size.
 {
     return this->size;
 }
METHOD (mem_pool_t , get_online , u_int , private_mem_pool_t * this)
Definition at line 220 of file mem_pool.c.
References array_count(), count, enumerator_t::destroy, enumerator_t::enumerate, leases(), mutex_t::lock, mutex, entry_t::online, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     u_int count = 0;
     this->mutex->lock(this->mutex);
     enumerator = this->leases->create_enumerator(this->leases);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         count += array_count(entry->online);
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     return count;
 }
METHOD (mem_pool_t , get_offline , u_int , private_mem_pool_t * this)
Definition at line 239 of file mem_pool.c.
References array_count(), count, enumerator_t::destroy, enumerator_t::enumerate, leases(), mutex_t::lock, mutex, entry_t::offline, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     u_int count = 0;
     this->mutex->lock(this->mutex);
     enumerator = this->leases->create_enumerator(this->leases);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         count += array_count(entry->offline);
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     return count;
 }
METHOD (mem_pool_t , acquire_address , host_t * , private_mem_pool_t * this, identification_t * id, host_t * requested, mem_pool_op_t operation, host_t * peer)
Definition at line 399 of file mem_pool.c.
References base, host_t::clone, DBG1, DBG_CFG, get_existing(), host_t::get_family, get_new(), get_reassigned(), mutex_t::lock, MEM_POOL_EXISTING, MEM_POOL_NEW, MEM_POOL_REASSIGN, mutex, name, offset, offset2host(), size, and mutex_t::unlock.
 {
     int offset = 0;
     /* if the pool is empty (e.g. in the %config case) we simply return the
      * requested address */
     if (this->size == 0)
     {
         return requested->clone(requested);
     }
     if (requested->get_family(requested) !=
         this->base->get_family(this->base))
     {
         return NULL;
     }
     this->mutex->lock(this->mutex);
     switch (operation)
     {
         case MEM_POOL_EXISTING:
             offset = get_existing(this, id, requested, peer);
             break;
         case MEM_POOL_NEW:
             offset = get_new(this, id, peer);
             break;
         case MEM_POOL_REASSIGN:
             offset = get_reassigned(this, id, peer);
             if (!offset)
             {
                 DBG1(DBG_CFG, "pool '%s' is full, unable to assign address",
                      this->name);
             }
             break;
         default:
             break;
     }
     this->mutex->unlock(this->mutex);
     if (offset)
     {
         return offset2host(this, offset);
     }
     return NULL;
 }
METHOD (mem_pool_t , release_address , bool , private_mem_pool_t * this, host_t * address, identification_t * id)
Definition at line 447 of file mem_pool.c.
References array_create_enumerator(), array_insert(), array_remove_at(), ARRAY_TAIL, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, host2offset(), leases(), mutex_t::lock, mutex, entry_t::offline, unique_lease_t::offset, offset, entry_t::online, size, TRUE, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     bool found = FALSE, more = FALSE;
     entry_t *entry;
     u_int offset;
     unique_lease_t *current;
     if (this->size != 0)
     {
         this->mutex->lock(this->mutex);
         entry = this->leases->get(this->leases, id);
         if (entry)
         {
             offset = host2offset(this, address);
             enumerator = array_create_enumerator(entry->online);
             while (enumerator->enumerate(enumerator, &current))
             {
                 if (current->offset == offset)
                 {
                     if (!found)
                     {   /* remove the first entry only */
                         array_remove_at(entry->online, enumerator);
                         found = TRUE;
                     }
                     else
                     {   /* but check for more entries */
                         more = TRUE;
                         break;
                     }
                 }
             }
             enumerator->destroy(enumerator);
             if (found && !more)
             {
                 /* no tunnels are online anymore for this lease, make offline */
                 array_insert(entry->offline, ARRAY_TAIL, &offset);
                 DBG1(DBG_CFG, "lease %H by '%Y' went offline", address, id);
             }
         }
         this->mutex->unlock(this->mutex);
     }
     return found;
 }
METHOD (enumerator_t , lease_enumerate , bool , lease_enumerator_t * this, identification_t ** id, host_t ** addr, bool * online)
Definition at line 515 of file mem_pool.c.
References array_create_enumerator(), DESTROY_IF, FALSE, unique_lease_t::offset, offset, offset2host(), and TRUE.
 {
     u_int *offset;
     unique_lease_t *lease;
     DESTROY_IF(this->addr);
     this->addr = NULL;
     while (TRUE)
     {
         if (this->entry)
         {
             if (this->online->enumerate(this->online, &lease))
             {
                 *id = this->entry->id;
                 *addr = this->addr = offset2host(this->pool, lease->offset);
                 *online = TRUE;
                 return TRUE;
             }
             if (this->offline->enumerate(this->offline, &offset))
             {
                 *id = this->entry->id;
                 *addr = this->addr = offset2host(this->pool, *offset);
                 *online = FALSE;
                 return TRUE;
             }
             this->online->destroy(this->online);
             this->offline->destroy(this->offline);
             this->online = this->offline = NULL;
         }
         if (!this->entries->enumerate(this->entries, NULL, &this->entry))
         {
             return FALSE;
         }
         this->online = array_create_enumerator(this->entry->online);
         this->offline = array_create_enumerator(this->entry->offline);
     }
 }
METHOD (enumerator_t , lease_enumerator_destroy , void , lease_enumerator_t * this)
Definition at line 555 of file mem_pool.c.
References addr, DESTROY_IF, and free().
 {
     DESTROY_IF(this->addr);
     DESTROY_IF(this->online);
     DESTROY_IF(this->offline);
     this->entries->destroy(this->entries);
     this->pool->mutex->unlock(this->pool->mutex);
     free(this);
 }
METHOD (mem_pool_t , create_lease_enumerator , enumerator_t * , private_mem_pool_t * this)
Definition at line 566 of file mem_pool.c.
References destroy(), INIT, leases(), mutex_t::lock, mutex, and lease_enumerator_t::public.
 {
     lease_enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_lease_enumerate,
             .destroy = _lease_enumerator_destroy,
         },
         .pool = this,
         .entries = this->leases->create_enumerator(this->leases),
     );
     return &enumerator->public;
 }
METHOD (mem_pool_t , destroy , void , private_mem_pool_t * this)
Definition at line 583 of file mem_pool.c.
References base, enumerator_t::destroy, mutex_t::destroy, DESTROY_IF, entry_destroy(), enumerator_t::enumerate, free(), leases(), mutex, and name.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     enumerator = this->leases->create_enumerator(this->leases);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         entry_destroy(entry);
     }
     enumerator->destroy(enumerator);
     this->leases->destroy(this->leases);
     this->mutex->destroy(this->mutex);
     DESTROY_IF(this->base);
     free(this->name);
     free(this);
 }
static u_int network_id_diff (host_t * host, int hostbits) static
Check if the given host is the network ID of a subnet, that is, if hostbits are zero. Since we limit pools to 2^31 addresses we only have to check the last 4 bytes.
Definition at line 636 of file mem_pool.c.
References addr, host_t::get_address, chunk_t::len, chunk_t::ptr, and untoh32().
Referenced by mem_pool_create().
 {
     u_int32_t last;
     chunk_t addr;
     if (!hostbits)
     {
         return 0;
     }
     addr = host->get_address(host);
     last = untoh32(addr.ptr + addr.len - sizeof(last));
     hostbits = sizeof(last) * 8 - hostbits;
     return (last << hostbits) >> hostbits;
 }
static host_t* offset2host (private_mem_pool_t * pool, int offset) static
convert a pool offset to an address
Definition at line 142 of file mem_pool.c.
References addr, private_mem_pool_t::base, chunk_clone, free(), host_t::get_address, host_t::get_family, host, host_create_from_chunk(), chunk_t::ptr, and private_mem_pool_t::size.
Referenced by METHOD().
 {
     chunk_t addr;
     host_t *host;
     u_int32_t *pos;
     offset--;
     if (offset > pool->size)
     {
         return NULL;
     }
     addr = chunk_clone(pool->base->get_address(pool->base));
     if (pool->base->get_family(pool->base) == AF_INET6)
     {
         pos = (u_int32_t*)(addr.ptr + 12);
     }
     else
     {
         pos = (u_int32_t*)addr.ptr;
     }
     *pos = htonl(offset + ntohl(*pos));
     host = host_create_from_chunk(pool->base->get_family(pool->base), addr, 0);
     free(addr.ptr);
     return host;
 }