strongSwan: tcg_seg_attr_next_seg.c File Reference
tcg_seg_attr_next_seg.c File Reference
#include "tcg_seg_attr_next_seg.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_seg_attr_next_seg_t
Typedefs
typedef struct
private_tcg_seg_attr_next_seg_t private_tcg_seg_attr_next_seg_t
Enumerations
enum next_seg_flags_t { NEXT_SEG_FLAG_NONE = 0, NEXT_SEG_FLAG_CANCEL = 1 }
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_seg_attr_next_seg_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_seg_attr_next_seg_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_seg_attr_next_seg_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_seg_attr_next_seg_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_seg_attr_next_seg_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_seg_attr_next_seg_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_seg_attr_next_seg_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_seg_attr_next_seg_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_seg_attr_next_seg_t *this)
METHOD (tcg_seg_attr_next_seg_t, get_base_attr_id, uint32_t, private_tcg_seg_attr_next_seg_t *this)
METHOD (tcg_seg_attr_next_seg_t, get_cancel_flag, bool, private_tcg_seg_attr_next_seg_t *this)
pa_tnc_attr_t * tcg_seg_attr_next_seg_create (uint32_t base_attr_id, bool cancel)
pa_tnc_attr_t * tcg_seg_attr_next_seg_create_from_data (size_t length, chunk_t data)
Typedef Documentation
typedef struct private_tcg_seg_attr_next_seg_t private_tcg_seg_attr_next_seg_t
Definition at line 23 of file tcg_seg_attr_next_seg.c.
Enumeration Type Documentation
enum next_seg_flags_t
Enumerator
NEXT_SEG_FLAG_NONE
NEXT_SEG_FLAG_CANCEL
Definition at line 25 of file tcg_seg_attr_next_seg.c.
              {
     NEXT_SEG_FLAG_NONE =    0,
     NEXT_SEG_FLAG_CANCEL =  1
 } next_seg_flags_t;
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_seg_attr_next_seg_t * this)
Definition at line 87 of file tcg_seg_attr_next_seg.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_seg_attr_next_seg_t * this)
Definition at line 93 of file tcg_seg_attr_next_seg.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_seg_attr_next_seg_t * this)
Definition at line 99 of file tcg_seg_attr_next_seg.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_seg_attr_next_seg_t * this, bool noskip)
Definition at line 105 of file tcg_seg_attr_next_seg.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_seg_attr_next_seg_t * this)
Definition at line 111 of file tcg_seg_attr_next_seg.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, NEXT_SEG_FLAG_CANCEL, NEXT_SEG_FLAG_NONE, TCG_SEG_ATTR_NEXT_SEG_SIZE, value, bio_writer_t::write_uint24, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(TCG_SEG_ATTR_NEXT_SEG_SIZE);
     writer->write_uint8 (writer, this->cancel_flag ? NEXT_SEG_FLAG_CANCEL :
                                                      NEXT_SEG_FLAG_NONE);
     writer->write_uint24(writer, this->base_attr_id);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_seg_attr_next_seg_t * this, u_int32_t * offset)
Definition at line 130 of file tcg_seg_attr_next_seg.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, flags, NEXT_SEG_FLAG_CANCEL, bio_reader_t::read_uint24, bio_reader_t::read_uint8, SUCCESS, tcg_attr_names, TCG_SEG_ATTR_NEXT_SEG_SIZE, type, and value.
 {
     bio_reader_t *reader;
     uint8_t flags;
     *offset = 0;
     if (this->value.len < this->length)
     {
         DBG1(DBG_TNC, "segmentation not allowed for %N", tcg_attr_names,
                                                          this->type.type);
         return FAILED;
     }
     if (this->value.len < TCG_SEG_ATTR_NEXT_SEG_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for %N", tcg_attr_names,
                                                   this->type.type);
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &flags);
     reader->read_uint24(reader, &this->base_attr_id);
     reader->destroy(reader);
     this->cancel_flag = (flags & NEXT_SEG_FLAG_CANCEL);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_seg_attr_next_seg_t * this, chunk_t segment)
Definition at line 160 of file tcg_seg_attr_next_seg.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_seg_attr_next_seg_t * this)
Definition at line 166 of file tcg_seg_attr_next_seg.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_seg_attr_next_seg_t * this)
Definition at line 173 of file tcg_seg_attr_next_seg.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_seg_attr_next_seg_t , get_base_attr_id , uint32_t , private_tcg_seg_attr_next_seg_t * this)
Definition at line 183 of file tcg_seg_attr_next_seg.c.
 {
     return this->base_attr_id;
 }
METHOD (tcg_seg_attr_next_seg_t , get_cancel_flag , bool , private_tcg_seg_attr_next_seg_t * this)
Definition at line 189 of file tcg_seg_attr_next_seg.c.
 {
     return this->cancel_flag;
 }