strongSwan: aesni_xcbc
aesni_xcbc
aesni
Functions
mac_t * aesni_cmac_create (encryption_algorithm_t algo, size_t key_size)
prf_t * aesni_cmac_prf_create (pseudo_random_function_t algo)
signer_t * aesni_cmac_signer_create (integrity_algorithm_t algo)
mac_t * aesni_xcbc_create (encryption_algorithm_t algo, size_t key_size)
prf_t * aesni_xcbc_prf_create (pseudo_random_function_t algo)
signer_t * aesni_xcbc_signer_create (integrity_algorithm_t algo)
Detailed Description
Function Documentation
mac_t* aesni_cmac_create (encryption_algorithm_t algo, size_t key_size)
Create a generic mac_t object using AESNI CMAC.
Parameters
algo underlying encryption algorithm
key_size size of encryption key, in bytes
Definition at line 311 of file aesni_cmac.c.
References INIT_ALIGN.
Referenced by aesni_cmac_prf_create(), and aesni_cmac_signer_create().
 {
     private_mac_t *this;
     INIT_ALIGN(this, sizeof(__m128i),
         .public = {
             .get_mac = _get_mac,
             .get_mac_size = _get_mac_size,
             .set_key = _set_key,
             .destroy = _destroy,
         },
     );
     return &this->public;
 }
prf_t* aesni_cmac_prf_create (pseudo_random_function_t algo)
Creates a new prf_t object based AESNI CMAC.
Parameters
algo algorithm to implement
Returns
prf_t object, NULL if not supported
Definition at line 330 of file aesni_cmac.c.
References aesni_cmac_create(), ENCR_AES_CBC, mac_prf_create(), and PRF_AES128_CMAC.
Referenced by METHOD().
 {
     mac_t *cmac;
     switch (algo)
     {
         case PRF_AES128_CMAC:
             cmac = aesni_cmac_create(ENCR_AES_CBC, 16);
             break;
         default:
             return NULL;
     }
     if (cmac)
     {
         return mac_prf_create(cmac);
     }
     return NULL;
 }
signer_t* aesni_cmac_signer_create (integrity_algorithm_t algo)
Creates a new signer_t object based on AESNI CMAC.
Parameters
algo algorithm to implement
Returns
signer_t, NULL if not supported
Definition at line 352 of file aesni_cmac.c.
References aesni_cmac_create(), AUTH_AES_CMAC_96, ENCR_AES_CBC, and mac_signer_create().
Referenced by METHOD().
 {
     size_t truncation;
     mac_t *cmac;
     switch (algo)
     {
         case AUTH_AES_CMAC_96:
             cmac = aesni_cmac_create(ENCR_AES_CBC, 16);
             truncation = 12;
             break;
         default:
             return NULL;
     }
     if (cmac)
     {
         return mac_signer_create(cmac, truncation);
     }
     return NULL;
 }
mac_t* aesni_xcbc_create (encryption_algorithm_t algo, size_t key_size)
Create a generic mac_t object using AESNI XCBC
Parameters
algo underlying encryption algorithm
key_size size of encryption key, in bytes
Definition at line 307 of file aesni_xcbc.c.
References INIT_ALIGN.
Referenced by aesni_xcbc_prf_create(), and aesni_xcbc_signer_create().
 {
     private_aesni_mac_t *this;
     INIT_ALIGN(this, sizeof(__m128i),
         .public = {
             .get_mac = _get_mac,
             .get_mac_size = _get_mac_size,
             .set_key = _set_key,
             .destroy = _destroy,
         },
     );
     return &this->public;
 }
prf_t* aesni_xcbc_prf_create (pseudo_random_function_t algo)
Creates a new prf_t object based AESNI XCBC.
Parameters
algo algorithm to implement
Returns
prf_t object, NULL if not supported
Definition at line 326 of file aesni_xcbc.c.
References aesni_xcbc_create(), ENCR_AES_CBC, mac_prf_create(), PRF_AES128_XCBC, and xcbc.
Referenced by METHOD().
 {
     mac_t *xcbc;
     switch (algo)
     {
         case PRF_AES128_XCBC:
             xcbc = aesni_xcbc_create(ENCR_AES_CBC, 16);
             break;
         default:
             return NULL;
     }
     if (xcbc)
     {
         return mac_prf_create(xcbc);
     }
     return NULL;
 }
signer_t* aesni_xcbc_signer_create (integrity_algorithm_t algo)
Creates a new signer_t object based on AESNI XCBC.
Parameters
algo algorithm to implement
Returns
signer_t, NULL if not supported
Definition at line 348 of file aesni_xcbc.c.
References aesni_xcbc_create(), AUTH_AES_XCBC_96, ENCR_AES_CBC, mac_signer_create(), and xcbc.
Referenced by METHOD().
 {
     size_t trunc;
     mac_t *xcbc;
     switch (algo)
     {
         case AUTH_AES_XCBC_96:
             xcbc = aesni_xcbc_create(ENCR_AES_CBC, 16);
             trunc = 12;
             break;
         default:
             return NULL;
     }
     if (xcbc)
     {
         return mac_signer_create(xcbc, trunc);
     }
     return NULL;
 }