strongSwan: pgp_cert
pgp_cert
pgp
Classes
struct pgp_cert_t
Typedefs
typedef struct pgp_cert_t pgp_cert_t
Functions
pgp_cert_t * pgp_cert_load (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct pgp_cert_t pgp_cert_t
Definition at line 26 of file pgp_cert.h.
Function Documentation
pgp_cert_t* pgp_cert_load (certificate_type_t type, va_list args)
Load a PGP certificate.
Parameters
type type of the certificate, CERT_GPG
args builder_part_t argument list
Returns
builder instance
See header.
Definition at line 405 of file pgp_cert.c.
References blob, BUILD_BLOB_PGP, BUILD_END, chunk_clone, chunk_empty, create_empty(), DBG1, DBG_LIB, destroy(), encoding, key, chunk_t::len, parse_public_key(), parse_signature(), parse_user_id(), pgp_packet_tag_names, PGP_PKT_PUBLIC_KEY, PGP_PKT_SIGNATURE, PGP_PKT_USER_ID, pgp_read_packet(), and TRUE.
Referenced by METHOD().
 {
     chunk_t packet, blob = chunk_empty;
     pgp_packet_tag_t tag;
     private_pgp_cert_t *this;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_PGP:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     this = create_empty();
     this->encoding = chunk_clone(blob);
     while (blob.len)
     {
         if (!pgp_read_packet(&blob, &packet, &tag))
         {
             destroy(this);
             return NULL;
         }
         switch (tag)
         {
             case PGP_PKT_PUBLIC_KEY:
                 if (!parse_public_key(this, packet))
                 {
                     destroy(this);
                     return NULL;
                 }
                 break;
             case PGP_PKT_SIGNATURE:
                 if (!parse_signature(this, packet))
                 {
                     destroy(this);
                     return NULL;
                 }
                 break;
             case PGP_PKT_USER_ID:
                 if (!parse_user_id(this, packet))
                 {
                     destroy(this);
                     return NULL;
                 }
                 break;
             default:
                 DBG1(DBG_LIB, "ignoring %N packet in PGP certificate",
                      pgp_packet_tag_names, tag);
                 break;
         }
     }
     if (this->key)
     {
         return &this->public;
     }
     destroy(this);
     return NULL;
 }