strongSwan: whitelist_control
whitelist_control
whitelist
Classes
struct whitelist_control_t
Typedefs
typedef struct whitelist_control_t whitelist_control_t
Functions
whitelist_control_t * whitelist_control_create (whitelist_listener_t *listener)
Detailed Description
Typedef Documentation
typedef struct whitelist_control_t whitelist_control_t
Definition at line 26 of file whitelist_control.h.
Function Documentation
whitelist_control_t* whitelist_control_create (whitelist_listener_t * listener)
Create a whitelist_control instance.
See header
Definition at line 146 of file whitelist_control.c.
References stream_manager_t::create_service, DBG1, DBG_CFG, free(), settings_t::get_str, INIT, JOB_PRIO_CRITICAL, lib, listener, library_t::ns, on_accept(), library_t::settings, library_t::streams, uri, and WHITELIST_SOCKET.
Referenced by whitelist_plugin_create().
 {
     private_whitelist_control_t *this;
     char *uri;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
         .listener = listener,
     );
     uri = lib->settings->get_str(lib->settings,
                 "%s.plugins.whitelist.socket", "unix://" WHITELIST_SOCKET,
                 lib->ns);
     this->service = lib->streams->create_service(lib->streams, uri, 10);
     if (!this->service)
     {
         DBG1(DBG_CFG, "creating whitelist socket failed");
         free(this);
         return NULL;
     }
     this->service->on_accept(this->service, (stream_service_cb_t)on_accept,
                              this, JOB_PRIO_CRITICAL, 0);
     return &this->public;
 }