strongSwan: gmp_rsa_private_key
gmp_rsa_private_key
gmp
Classes
struct gmp_rsa_private_key_t
Typedefs
typedef struct
gmp_rsa_private_key_t gmp_rsa_private_key_t
Functions
gmp_rsa_private_key_t * gmp_rsa_private_key_gen (key_type_t type, va_list args)
gmp_rsa_private_key_t * gmp_rsa_private_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct gmp_rsa_private_key_t gmp_rsa_private_key_t
Definition at line 27 of file gmp_rsa_private_key.h.
Function Documentation
gmp_rsa_private_key_t* gmp_rsa_private_key_gen (key_type_t type, va_list args)
Generated a RSA private keys using libgmp.
Accepts the BUILD_KEY_SIZE argument.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
generated key, NULL on failure
See header.
Definition at line 653 of file gmp_rsa_private_key.c.
References rng_t::allocate_bytes, BITS_PER_BYTE, BUILD_END, BUILD_KEY_SIZE, BUILD_SAFE_PRIMES, BUILD_SHARES, BUILD_THRESHOLD, chunk_clear(), chunk_free(), compute_prime(), crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_LIB, rng_t::destroy, destroy(), FALSE, gmp_rsa_private_key_create_empty(), key_size, chunk_t::len, lib, m, malloc(), mpz_clear_sensitive(), n, chunk_t::ptr, PUBLIC_EXPONENT, q, rng, RNG_TRUE, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     private_gmp_rsa_private_key_t *this;
     u_int key_size = 0, shares = 0, threshold = 1;
     bool safe_prime = FALSE, rng_failed = FALSE, invert_failed = FALSE;
     mpz_t p, q, p1, q1, d;
 ;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_KEY_SIZE:
                 key_size = va_arg(args, u_int);
                 continue;
             case BUILD_SAFE_PRIMES:
                 safe_prime = TRUE;
                 continue;
             case BUILD_SHARES:
                 shares = va_arg(args, u_int);
                 continue;
             case BUILD_THRESHOLD:
                 threshold = va_arg(args, u_int);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!key_size)
     {
         return NULL;
     }
     key_size = key_size / BITS_PER_BYTE;
     /* Get values of primes p and q  */
     if (compute_prime(key_size/2, safe_prime, &p, &p1) != SUCCESS)
     {
         return NULL;
     }
     if (compute_prime(key_size/2, safe_prime, &q, &q1) != SUCCESS)
     {
         mpz_clear(p);
         mpz_clear(p1);
         return NULL;
     }
     /* Swapping Primes so p is larger then q */
     if (mpz_cmp(p, q) < 0)
     {
         mpz_swap(p, q);
         mpz_swap(p1, q1);
     }
     /* Create and initialize RSA private key object */
     this = gmp_rsa_private_key_create_empty();
     this->shares = shares;
     this->threshold = threshold;
     this->d = malloc(threshold * sizeof(mpz_t));
     *this->p = *p;
     *this->q = *q;
     mpz_init_set_ui(this->e, PUBLIC_EXPONENT);
     mpz_init(this->n);
     mpz_init(this->m);
     mpz_init(this->exp1);
     mpz_init(this->exp2);
     mpz_init(this->coeff);
     mpz_init(this->v);
     mpz_init(d);
     mpz_mul(this->n, p, q);                 /* n = p*q */
     mpz_lcm(this->m, p1, q1);               /* m = lcm(p-1,q-1) */
     mpz_invert(d, this->e, this->m);        /* e has an inverse mod m */
     mpz_mod(this->exp1, d, p1);             /* exp1 = d mod p-1 */
     mpz_mod(this->exp2, d, q1);             /* exp2 = d mod q-1 */
     mpz_invert(this->coeff, q, p);          /* coeff = q^-1 mod p */
     invert_failed = mpz_cmp_ui(this->m, 0) == 0 ||
                     mpz_cmp_ui(this->coeff, 0) == 0;
     /* store secret exponent d */
     (*this->d)[0] = *d;
     /* generate and store random coefficients of secret sharing polynomial */
     if (threshold > 1)
     {
         rng_t *rng;
         chunk_t random_bytes;
         mpz_t u;
         int i;
         rng = lib->crypto->create_rng(lib->crypto, RNG_TRUE);
         mpz_init(u);
         for (i = 1; i < threshold; i++)
         {
             mpz_init(d);
             if (!rng->allocate_bytes(rng, key_size, &random_bytes))
             {
                 rng_failed = TRUE;
                 continue;
             }
             mpz_import(d, random_bytes.len, 1, 1, 1, 0, random_bytes.ptr);
             mpz_mod(d, d, this->m);
             (*this->d)[i] = *d;
             chunk_clear(&random_bytes);
         }
         /* generate verification key v as a square number */
         do
         {
             if (!rng->allocate_bytes(rng, key_size, &random_bytes))
             {
                 rng_failed = TRUE;
                 break;
             }
             mpz_import(this->v, random_bytes.len, 1, 1, 1, 0, random_bytes.ptr);
             mpz_mul(this->v, this->v, this->v);
             mpz_mod(this->v, this->v, this->n);
             mpz_gcd(u, this->v, this->n);
             chunk_free(&random_bytes);
         }
         while (mpz_cmp_ui(u, 1) != 0);
         mpz_clear(u);
         rng->destroy(rng);
     }
     mpz_clear_sensitive(p1);
     mpz_clear_sensitive(q1);
     if (rng_failed || invert_failed)
     {
         DBG1(DBG_LIB, "rsa key generation failed");
         destroy(this);
         return NULL;
     }
     /* set key size in bytes */
     this->k = key_size;
     return &this->public;
 }
gmp_rsa_private_key_t* gmp_rsa_private_key_load (key_type_t type, va_list args)
Loaded a RSA private keys using libgmp.
Accepts BUILD_RSA_* components.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 804 of file gmp_rsa_private_key.c.
References BITS_PER_BYTE, BUILD_END, BUILD_RSA_COEFF, BUILD_RSA_EXP1, BUILD_RSA_EXP2, BUILD_RSA_MODULUS, BUILD_RSA_PRIME1, BUILD_RSA_PRIME2, BUILD_RSA_PRIV_EXP, BUILD_RSA_PUB_EXP, check(), chunk_empty, destroy(), gmp_rsa_private_key_create_empty(), chunk_t::len, m, malloc(), n, chunk_t::ptr, q, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     private_gmp_rsa_private_key_t *this;
     chunk_t n, e, d, p, q, exp1, exp2, coeff;
     n = e = d = p = q = exp1 = exp2 = coeff = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_RSA_MODULUS:
                 n = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PUB_EXP:
                 e = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIV_EXP:
                 d = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIME1:
                 p = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PRIME2:
                 q = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_EXP1:
                 exp1 = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_EXP2:
                 exp2 = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_COEFF:
                 coeff = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     this = gmp_rsa_private_key_create_empty();
     this->d = malloc(sizeof(mpz_t));
     mpz_init(this->n);
     mpz_init(this->e);
     mpz_init(*this->d);
     mpz_init(this->p);
     mpz_init(this->q);
     mpz_init(this->m);
     mpz_init(this->exp1);
     mpz_init(this->exp2);
     mpz_init(this->coeff);
     mpz_init(this->v);
     mpz_import(this->n, n.len, 1, 1, 1, 0, n.ptr);
     mpz_import(this->e, e.len, 1, 1, 1, 0, e.ptr);
     mpz_import(*this->d, d.len, 1, 1, 1, 0, d.ptr);
     mpz_import(this->p, p.len, 1, 1, 1, 0, p.ptr);
     mpz_import(this->q, q.len, 1, 1, 1, 0, q.ptr);
     mpz_import(this->coeff, coeff.len, 1, 1, 1, 0, coeff.ptr);
     if (!exp1.len)
     {   /* exp1 missing in key, recalculate: exp1 = d mod (p-1) */
         mpz_sub_ui(this->exp1, this->p, 1);
         mpz_mod(this->exp1, *this->d, this->exp1);
     }
     else
     {
         mpz_import(this->exp1, exp1.len, 1, 1, 1, 0, exp1.ptr);
     }
     if (!exp2.len)
     {   /* exp2 missing in key, recalculate: exp2 = d mod (q-1) */
         mpz_sub_ui(this->exp2, this->q, 1);
         mpz_mod(this->exp2, *this->d, this->exp2);
     }
     else
     {
         mpz_import(this->exp2, exp2.len, 1, 1, 1, 0, exp2.ptr);
     }
     this->k = (mpz_sizeinbase(this->n, 2) + 7) / BITS_PER_BYTE;
     if (check(this) != SUCCESS)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }