strongSwan: mem_cred
mem_cred
sets
Classes
struct mem_cred_t
Typedefs
typedef struct mem_cred_t mem_cred_t
Functions
mem_cred_t * mem_cred_create ()
Detailed Description
Typedef Documentation
typedef struct mem_cred_t mem_cred_t
Definition at line 26 of file mem_cred.h.
Function Documentation
mem_cred_t* mem_cred_create ()
Create a mem_cred instance.
See header
Definition at line 779 of file mem_cred.c.
References add_cert(), add_key(), destroy(), INIT, linked_list_create(), nop(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by add_callback(), cmd_creds_create(), create_empty(), decrypt(), decrypt_with_config(), init(), load_certs(), load_from_file(), load_pin(), load_secrets(), maemo_service_create(), main(), METHOD(), parse(), pkcs12_create(), pkcs7(), pts_creds_create(), START_SETUP(), stroke_cred_create(), tkm_cred_create(), tnc_ifmap_soap_create(), verify(), and vici_cred_create().
 {
     private_mem_cred_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_shared_enumerator = _create_shared_enumerator,
                 .create_private_enumerator = _create_private_enumerator,
                 .create_cert_enumerator = _create_cert_enumerator,
                 .create_cdp_enumerator  = _create_cdp_enumerator,
                 .cache_cert = (void*)nop,
             },
             .add_cert = _add_cert,
             .add_cert_ref = _add_cert_ref,
             .get_cert_ref = _get_cert_ref,
             .add_crl = _add_crl,
             .add_key = _add_key,
             .add_shared = _add_shared,
             .add_shared_list = _add_shared_list,
             .add_cdp = _add_cdp,
             .replace_certs = _replace_certs,
             .replace_secrets = _replace_secrets,
             .clear = _clear_,
             .clear_secrets = _clear_secrets,
             .destroy = _destroy,
         },
         .trusted = linked_list_create(),
         .untrusted = linked_list_create(),
         .keys = linked_list_create(),
         .shared = linked_list_create(),
         .cdps = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return &this->public;
 }