strongSwan: tcg_pts_attr_dh_nonce_finish.c File Reference
tcg_pts_attr_dh_nonce_finish.c File Reference
#include "tcg_pts_attr_dh_nonce_finish.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_dh_nonce_finish_t
Macros
#define PTS_DH_NONCE_FINISH_SIZE 12
#define PTS_DH_NONCE_FINISH_RESERVED 0x00
Typedefs
typedef struct
private_tcg_pts_attr_dh_nonce_finish_t private_tcg_pts_attr_dh_nonce_finish_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_dh_nonce_finish_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_dh_nonce_finish_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_dh_nonce_finish_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (tcg_pts_attr_dh_nonce_finish_t, get_hash_algo, pts_meas_algorithms_t, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (tcg_pts_attr_dh_nonce_finish_t, get_initiator_value, chunk_t, private_tcg_pts_attr_dh_nonce_finish_t *this)
METHOD (tcg_pts_attr_dh_nonce_finish_t, get_initiator_nonce, chunk_t, private_tcg_pts_attr_dh_nonce_finish_t *this)
pa_tnc_attr_t * tcg_pts_attr_dh_nonce_finish_create (pts_meas_algorithms_t hash_algo, chunk_t initiator_value, chunk_t initiator_nonce)
pa_tnc_attr_t * tcg_pts_attr_dh_nonce_finish_create_from_data (size_t length, chunk_t value)
Macro Definition Documentation
#define PTS_DH_NONCE_FINISH_RESERVED 0x00
Definition at line 44 of file tcg_pts_attr_dh_nonce_finish.c.
Referenced by METHOD().
#define PTS_DH_NONCE_FINISH_SIZE 12
PTS DH Nonce Finish see section 3.8.3 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Nonce Len | Selected Hash Algorithm | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | D-H Initiator Public Value ... | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | D-H Initiator Nonce ... | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 43 of file tcg_pts_attr_dh_nonce_finish.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_dh_nonce_finish_t private_tcg_pts_attr_dh_nonce_finish_t
Definition at line 24 of file tcg_pts_attr_dh_nonce_finish.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 97 of file tcg_pts_attr_dh_nonce_finish.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 103 of file tcg_pts_attr_dh_nonce_finish.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 109 of file tcg_pts_attr_dh_nonce_finish.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_dh_nonce_finish_t * this, bool noskip)
Definition at line 115 of file tcg_pts_attr_dh_nonce_finish.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 121 of file tcg_pts_attr_dh_nonce_finish.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, PTS_DH_NONCE_FINISH_RESERVED, PTS_DH_NONCE_FINISH_SIZE, value, bio_writer_t::write_data, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PTS_DH_NONCE_FINISH_SIZE);
     writer->write_uint8 (writer, PTS_DH_NONCE_FINISH_RESERVED);
     writer->write_uint8 (writer, this->initiator_nonce.len);
     writer->write_uint16(writer, this->hash_algo);
     writer->write_data  (writer, this->initiator_value);
     writer->write_data  (writer, this->initiator_nonce);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_dh_nonce_finish_t * this, u_int32_t * offset)
Definition at line 142 of file tcg_pts_attr_dh_nonce_finish.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, PTS_DH_NONCE_FINISH_SIZE, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int8_t reserved, nonce_len;
     u_int16_t hash_algo;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_DH_NONCE_FINISH_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for PTS DH Nonce Finish");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &reserved);
     reader->read_uint8 (reader, &nonce_len);
     reader->read_uint16(reader, &hash_algo);
     reader->read_data(reader, reader->remaining(reader) - nonce_len,
                               &this->initiator_value);
     reader->read_data(reader, nonce_len, &this->initiator_nonce);
     this->hash_algo = hash_algo;
     this->initiator_value = chunk_clone(this->initiator_value);
     this->initiator_nonce = chunk_clone(this->initiator_nonce);
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_dh_nonce_finish_t * this, chunk_t segment)
Definition at line 175 of file tcg_pts_attr_dh_nonce_finish.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 181 of file tcg_pts_attr_dh_nonce_finish.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 188 of file tcg_pts_attr_dh_nonce_finish.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this->initiator_value.ptr);
         free(this->initiator_nonce.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_dh_nonce_finish_t , get_hash_algo , pts_meas_algorithms_t , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 200 of file tcg_pts_attr_dh_nonce_finish.c.
 {
     return this->hash_algo;
 }
METHOD (tcg_pts_attr_dh_nonce_finish_t , get_initiator_value , chunk_t , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 206 of file tcg_pts_attr_dh_nonce_finish.c.
 {
     return this->initiator_value;
 }
METHOD (tcg_pts_attr_dh_nonce_finish_t , get_initiator_nonce , chunk_t , private_tcg_pts_attr_dh_nonce_finish_t * this)
Definition at line 212 of file tcg_pts_attr_dh_nonce_finish.c.
 {
     return this->initiator_nonce;
 }