strongSwan: imv_session_manager.c File Reference
imv_session_manager.c File Reference
#include "imv_session_manager.h"
#include <tncif_names.h>
#include <tncif_identity.h>
#include <threading/mutex.h>
Classes
struct private_imv_session_manager_t
Typedefs
typedef struct
private_imv_session_manager_t private_imv_session_manager_t
Functions
METHOD (imv_session_manager_t, add_session, imv_session_t *, private_imv_session_manager_t *this, TNC_ConnectionID conn_id, linked_list_t *ar_identities)
METHOD (imv_session_manager_t, remove_session, void, private_imv_session_manager_t *this, imv_session_t *session)
METHOD (imv_session_manager_t, destroy, void, private_imv_session_manager_t *this)
imv_session_manager_t * imv_session_manager_create (void)
Typedef Documentation
typedef struct private_imv_session_manager_t private_imv_session_manager_t
Definition at line 23 of file imv_session_manager.c.
Function Documentation
METHOD (imv_session_manager_t , add_session , imv_session_t * , private_imv_session_manager_t * this, TNC_ConnectionID conn_id, linked_list_t * ar_identities)
Definition at line 47 of file imv_session_manager.c.
References linked_list_t::create_enumerator, DBG2, DBG_IMV, enumerator_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, tncif_identity_t::get_auth_type, imv_session_t::get_connection_id, tncif_identity_t::get_identity_type, tncif_identity_t::get_identity_value, imv_session_t::get_ref, tncif_identity_t::get_subject_type, imv_session_create(), chunk_t::len, mutex_t::lock, mutex, PEN_TCG, chunk_t::ptr, TNC_AUTH_UNKNOWN, TNC_Authentication_names, TNC_Identity_names, TNC_Subject_names, TNC_SUBJECT_UNKNOWN, pen_type_t::type, mutex_t::unlock, and pen_type_t::vendor_id.
 {
     enumerator_t *enumerator;
     tncif_identity_t *tnc_id;
     imv_session_t *current, *session = NULL;
     time_t created;
     this->mutex->lock(this->mutex);
     /* check if a session has already been assigned */
     enumerator = this->sessions->create_enumerator(this->sessions);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (conn_id == current->get_connection_id(current))
         {
             session = current;
             break;
         }
     }
     enumerator->destroy(enumerator);
     /* session already exists */
     if (session)
     {
         ar_identities->destroy_offset(ar_identities,
                                offsetof(tncif_identity_t, destroy));
         this->mutex->unlock(this->mutex);
         return session->get_ref(session);
     }
     /* Output list of Access Requestor identities */
     enumerator = ar_identities->create_enumerator(ar_identities);
     while (enumerator->enumerate(enumerator, &tnc_id))
     {
         pen_type_t id_type, subject_type, auth_type;
         uint32_t tcg_id_type, tcg_subject_type, tcg_auth_type;
         chunk_t id_value;
         id_type = tnc_id->get_identity_type(tnc_id);
         id_value = tnc_id->get_identity_value(tnc_id);
         subject_type = tnc_id->get_subject_type(tnc_id);
         auth_type = tnc_id->get_auth_type(tnc_id);
         tcg_id_type = (subject_type.vendor_id == PEN_TCG) ?
                             id_type.type : TNC_SUBJECT_UNKNOWN;
         tcg_subject_type = (subject_type.vendor_id == PEN_TCG) ?
                             subject_type.type : TNC_SUBJECT_UNKNOWN;
         tcg_auth_type =    (auth_type.vendor_id == PEN_TCG) ?
                             auth_type.type : TNC_AUTH_UNKNOWN;
         DBG2(DBG_IMV, "  %N AR identity '%.*s' of type %N authenticated by %N",
              TNC_Subject_names, tcg_subject_type,
              id_value.len, id_value.ptr,
              TNC_Identity_names, tcg_id_type,
              TNC_Authentication_names, tcg_auth_type);
     }
     enumerator->destroy(enumerator);
     /* create a new session entry */
     created = time(NULL);
     session = imv_session_create(conn_id, created, ar_identities);
     this->sessions->insert_last(this->sessions, session);
     this->mutex->unlock(this->mutex);
     return session;
 }
METHOD (imv_session_manager_t , remove_session , void , private_imv_session_manager_t * this, imv_session_t * session)
Definition at line 117 of file imv_session_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     imv_session_t *current;
     this->mutex->lock(this->mutex);
     enumerator = this->sessions->create_enumerator(this->sessions);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (current == session)
         {
             this->sessions->remove_at(this->sessions, enumerator);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (imv_session_manager_t , destroy , void , private_imv_session_manager_t * this)
Definition at line 137 of file imv_session_manager.c.
References mutex_t::destroy, destroy(), free(), and mutex.
 {
     this->sessions->destroy_offset(this->sessions,
                             offsetof(imv_session_t, destroy));
     this->mutex->destroy(this->mutex);
     free(this);
 }