strongSwan: traffic_selector.c File Reference
traffic_selector.c File Reference
#include <string.h>
#include <stdio.h>
#include "traffic_selector.h"
#include <utils/debug.h>
#include <utils/utils.h>
#include <utils/identification.h>
#include <collections/linked_list.h>
Classes
struct private_traffic_selector_t
Macros
#define NON_SUBNET_ADDRESS_RANGE 255
Typedefs
typedef struct
private_traffic_selector_t private_traffic_selector_t
Functions
ENUM (ts_type_name, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE,"TS_IPV4_ADDR_RANGE","TS_IPV6_ADDR_RANGE",)
static void calc_range (private_traffic_selector_t *this, u_int8_t netbits)
static u_int8_t calc_netbits (private_traffic_selector_t *this)
static private_traffic_selector_t * traffic_selector_create (u_int8_t protocol, ts_type_t type, u_int16_t from_port, u_int16_t to_port)
static bool is_opaque (private_traffic_selector_t *this)
static bool is_any (private_traffic_selector_t *this)
static int print_icmp (printf_hook_data_t *data, u_int16_t port)
int traffic_selector_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
METHOD (traffic_selector_t, get_subset, traffic_selector_t *, private_traffic_selector_t *this, traffic_selector_t *other_public)
METHOD (traffic_selector_t, equals, bool, private_traffic_selector_t *this, traffic_selector_t *other)
METHOD (traffic_selector_t, get_from_address, chunk_t, private_traffic_selector_t *this)
METHOD (traffic_selector_t, get_to_address, chunk_t, private_traffic_selector_t *this)
METHOD (traffic_selector_t, get_from_port, u_int16_t, private_traffic_selector_t *this)
METHOD (traffic_selector_t, get_to_port, u_int16_t, private_traffic_selector_t *this)
METHOD (traffic_selector_t, get_type, ts_type_t, private_traffic_selector_t *this)
METHOD (traffic_selector_t, get_protocol, u_int8_t, private_traffic_selector_t *this)
METHOD (traffic_selector_t, is_host, bool, private_traffic_selector_t *this, host_t *host)
METHOD (traffic_selector_t, is_dynamic, bool, private_traffic_selector_t *this)
METHOD (traffic_selector_t, set_address, void, private_traffic_selector_t *this, host_t *host)
METHOD (traffic_selector_t, is_contained_in, bool, private_traffic_selector_t *this, traffic_selector_t *other)
METHOD (traffic_selector_t, includes, bool, private_traffic_selector_t *this, host_t *host)
METHOD (traffic_selector_t, to_subnet, bool, private_traffic_selector_t *this, host_t **net, u_int8_t *mask)
METHOD (traffic_selector_t, clone_, traffic_selector_t *, private_traffic_selector_t *this)
METHOD (traffic_selector_t, hash, u_int, private_traffic_selector_t *this, u_int hash)
METHOD (traffic_selector_t, destroy, void, private_traffic_selector_t *this)
static int compare_int (int a, int b)
int traffic_selector_cmp (traffic_selector_t *a_pub, traffic_selector_t *b_pub, void *opts)
traffic_selector_t * traffic_selector_create_from_bytes (u_int8_t protocol, ts_type_t type, chunk_t from, u_int16_t from_port, chunk_t to, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_from_rfc3779_format (ts_type_t type, chunk_t from, chunk_t to)
traffic_selector_t * traffic_selector_create_from_subnet (host_t *net, u_int8_t netbits, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_from_string (u_int8_t protocol, ts_type_t type, char *from_addr, u_int16_t from_port, char *to_addr, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_from_cidr (char *string, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_dynamic (u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
Macro Definition Documentation
#define NON_SUBNET_ADDRESS_RANGE 255
Definition at line 28 of file traffic_selector.c.
Referenced by calc_netbits(), METHOD(), and traffic_selector_printf_hook().
Typedef Documentation
typedef struct private_traffic_selector_t private_traffic_selector_t
Definition at line 35 of file traffic_selector.c.
Function Documentation
static u_int8_t calc_netbits (private_traffic_selector_t * this) static
calculate the subnet size from the "to" and "from" addresses
Definition at line 129 of file traffic_selector.c.
References FALSE, from, NON_SUBNET_ADDRESS_RANGE, prefix, size, to, TRUE, TS_IPV4_ADDR_RANGE, and type.
Referenced by METHOD(), traffic_selector_create_from_bytes(), traffic_selector_create_from_rfc3779_format(), and traffic_selector_create_from_string().
 {
     int byte, bit;
     u_int8_t netbits;
     size_t size = (this->type == TS_IPV4_ADDR_RANGE) ? 4 : 16;
     bool prefix = TRUE;
     /* a perfect match results in a single address with a /32 or /128 netmask */
     netbits = (size * 8);
     this->netbits = netbits;
     /* go through all bits of the addresses, beginning in the front.
      * as long as they are equal, the subnet gets larger
      */
     for (byte = 0; byte < size; byte++)
     {
         for (bit = 7; bit >= 0; bit--)
         {
             u_int8_t bitmask = 1 << bit;
             if (prefix)
             {
                 if ((bitmask & this->from[byte]) != (bitmask & this->to[byte]))
                 {
                     /* store the common prefix which might be a true subnet */
                     netbits = (7 - bit) + (byte * 8);
                     this->netbits = netbits;
                     prefix = FALSE;
                 }
             }
             else
             {
                 if ((bitmask & this->from[byte]) || !(bitmask & this->to[byte]))
                 {
                     this->netbits = NON_SUBNET_ADDRESS_RANGE;
                     return netbits;  /* return a pseudo subnet */
                 }
             }
         }
     }
     return netbits;  /* return a true subnet */
 }
static void calc_range (private_traffic_selector_t * this, u_int8_t netbits) static
calculate the "to"-address for the "from" address and a subnet size
Definition at line 106 of file traffic_selector.c.
References bits, bytes, from, len, mask, memcpy, memset, to, TS_IPV4_ADDR_RANGE, and type.
Referenced by traffic_selector_create_from_subnet().
 {
     size_t len;
     int bytes, bits;
     u_int8_t mask;
     this->netbits = netbits;
     len   = (this->type == TS_IPV4_ADDR_RANGE) ? 4 : 16;
     bytes = (netbits + 7)/8;
     bits  = (bytes * 8) - netbits;
     mask  = bits ? (1 << bits) - 1 : 0;
     memcpy(this->to, this->from, bytes);
     memset(this->from + bytes, 0x00, len - bytes);
     memset(this->to   + bytes, 0xff, len - bytes);
     this->from[bytes-1] &= ~mask;
     this->to[bytes-1]   |=  mask;
 }
static int compare_int (int a, int b) static
Compare two integers
Definition at line 707 of file traffic_selector.c.
References b.
Referenced by traffic_selector_cmp().
 {
     return a - b;
 }
ENUM (ts_type_name , TS_IPV4_ADDR_RANGE , TS_IPV6_ADDR_RANGE , "TS_IPV4_ADDR_RANGE" , "TS_IPV6_ADDR_RANGE")
static bool is_any (private_traffic_selector_t * this) static
Check if TS contains "any" ports
Definition at line 190 of file traffic_selector.c.
References from_port, and to_port.
Referenced by METHOD(), and traffic_selector_printf_hook().
 {
     return this->from_port == 0 && this->to_port == 0xffff;
 }
static bool is_opaque (private_traffic_selector_t * this) static
Check if TS contains "opaque" ports
Definition at line 182 of file traffic_selector.c.
References from_port, and to_port.
Referenced by METHOD(), and traffic_selector_printf_hook().
 {
     return this->from_port == 0xffff && this->to_port == 0;
 }
METHOD (traffic_selector_t , get_subset , traffic_selector_t * , private_traffic_selector_t * this, traffic_selector_t * other_public)
Definition at line 360 of file traffic_selector.c.
References calc_netbits(), dynamic, private_traffic_selector_t::dynamic, private_traffic_selector_t::from, from, from_port, private_traffic_selector_t::from_port, is_any(), is_opaque(), max, memcpy, min, protocol, private_traffic_selector_t::protocol, private_traffic_selector_t::public, size, private_traffic_selector_t::to, to, to_port, private_traffic_selector_t::to_port, traffic_selector_create(), TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, type, and private_traffic_selector_t::type.
 {
     private_traffic_selector_t *other, *subset;
     u_int16_t from_port, to_port;
     u_char *from, *to;
     u_int8_t protocol;
     size_t size;
     other = (private_traffic_selector_t*)other_public;
     if (this->dynamic || other->dynamic)
     {   /* no set_address() applied, TS has no subset */
         return NULL;
     }
     if (this->type != other->type)
     {
         return NULL;
     }
     switch (this->type)
     {
         case TS_IPV4_ADDR_RANGE:
             size = sizeof(this->from4);
             break;
         case TS_IPV6_ADDR_RANGE:
             size = sizeof(this->from6);
             break;
         default:
             return NULL;
     }
     if (this->protocol != other->protocol &&
         this->protocol != 0 && other->protocol != 0)
     {
         return NULL;
     }
     /* select protocol, which is not zero */
     protocol = max(this->protocol, other->protocol);
     if ((is_opaque(this) && is_opaque(other)) ||
         (is_opaque(this) && is_any(other)) ||
         (is_opaque(other) && is_any(this)))
     {
         from_port = 0xffff;
         to_port = 0;
     }
     else
     {
         /* calculate the maximum port range allowed for both */
         from_port = max(this->from_port, other->from_port);
         to_port = min(this->to_port, other->to_port);
         if (from_port > to_port)
         {
             return NULL;
         }
     }
     /* get higher from-address */
     if (memcmp(this->from, other->from, size) > 0)
     {
         from = this->from;
     }
     else
     {
         from = other->from;
     }
     /* get lower to-address */
     if (memcmp(this->to, other->to, size) > 0)
     {
         to = other->to;
     }
     else
     {
         to = this->to;
     }
     /* if "from" > "to", we don't have a match */
     if (memcmp(from, to, size) > 0)
     {
         return NULL;
     }
     /* we have a match in protocol, port, and address: return it... */
     subset = traffic_selector_create(protocol, this->type, from_port, to_port);
     memcpy(subset->from, from, size);
     memcpy(subset->to, to, size);
     calc_netbits(subset);
     return &subset->public;
 }
METHOD (traffic_selector_t , equals , bool , private_traffic_selector_t * this, traffic_selector_t * other)
Definition at line 450 of file traffic_selector.c.
References traffic_selector_cmp().
 {
     return traffic_selector_cmp(&this->public, other, NULL) == 0;
 }
METHOD (traffic_selector_t , get_from_address , chunk_t , private_traffic_selector_t * this)
Definition at line 456 of file traffic_selector.c.
References chunk_create(), chunk_empty, from, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
 {
     switch (this->type)
     {
         case TS_IPV4_ADDR_RANGE:
             return chunk_create(this->from, sizeof(this->from4));
         case TS_IPV6_ADDR_RANGE:
             return chunk_create(this->from, sizeof(this->from6));
         default:
             return chunk_empty;
     }
 }
METHOD (traffic_selector_t , get_to_address , chunk_t , private_traffic_selector_t * this)
Definition at line 470 of file traffic_selector.c.
References chunk_create(), chunk_empty, to, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
 {
     switch (this->type)
     {
         case TS_IPV4_ADDR_RANGE:
             return chunk_create(this->to, sizeof(this->to4));
         case TS_IPV6_ADDR_RANGE:
             return chunk_create(this->to, sizeof(this->to6));
         default:
             return chunk_empty;
     }
 }
METHOD (traffic_selector_t , get_from_port , u_int16_t , private_traffic_selector_t * this)
Definition at line 484 of file traffic_selector.c.
References from_port.
 {
     return this->from_port;
 }
METHOD (traffic_selector_t , get_to_port , u_int16_t , private_traffic_selector_t * this)
Definition at line 490 of file traffic_selector.c.
References to_port.
 {
     return this->to_port;
 }
METHOD (traffic_selector_t , get_type , ts_type_t , private_traffic_selector_t * this)
Definition at line 496 of file traffic_selector.c.
References type.
 {
     return this->type;
 }
METHOD (traffic_selector_t , get_protocol , u_int8_t , private_traffic_selector_t * this)
Definition at line 502 of file traffic_selector.c.
References protocol.
 {
     return this->protocol;
 }
METHOD (traffic_selector_t , is_host , bool , private_traffic_selector_t * this, host_t * host)
Definition at line 508 of file traffic_selector.c.
References addr, dynamic, FALSE, family, from, host_t::get_address, host_t::get_family, chunk_t::len, length, memeq(), chunk_t::ptr, to, TRUE, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
 {
     if (host)
     {
         chunk_t addr;
         int family = host->get_family(host);
         if ((family == AF_INET && this->type == TS_IPV4_ADDR_RANGE) ||
             (family == AF_INET6 && this->type == TS_IPV6_ADDR_RANGE))
         {
             addr = host->get_address(host);
             if (memeq(addr.ptr, this->from, addr.len) &&
                 memeq(addr.ptr, this->to, addr.len))
             {
                 return TRUE;
             }
         }
     }
     else
     {
         size_t length = (this->type == TS_IPV4_ADDR_RANGE) ? 4 : 16;
         if (this->dynamic)
         {
             return TRUE;
         }
         if (memeq(this->from, this->to, length))
         {
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (traffic_selector_t , is_dynamic , bool , private_traffic_selector_t * this)
Definition at line 544 of file traffic_selector.c.
References dynamic.
 {
     return this->dynamic;
 }
METHOD (traffic_selector_t , set_address , void , private_traffic_selector_t * this, host_t * host)
Definition at line 550 of file traffic_selector.c.
References dynamic, FALSE, from, host_t::get_address, host_t::get_family, host_t::is_anyaddr, is_host, chunk_t::len, memcpy, memset, chunk_t::ptr, to, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
 {
     if (is_host(this, NULL))
     {
         this->type = host->get_family(host) == AF_INET ?
                 TS_IPV4_ADDR_RANGE : TS_IPV6_ADDR_RANGE;
         if (host->is_anyaddr(host))
         {
             memset(this->from6, 0x00, sizeof(this->from6));
             memset(this->to6, 0xFF, sizeof(this->to6));
             this->netbits = 0;
         }
         else
         {
             chunk_t from = host->get_address(host);
             memcpy(this->from, from.ptr, from.len);
             memcpy(this->to, from.ptr, from.len);
             this->netbits = from.len * 8;
         }
         this->dynamic = FALSE;
     }
 }
METHOD (traffic_selector_t , is_contained_in , bool , private_traffic_selector_t * this, traffic_selector_t * other)
Definition at line 575 of file traffic_selector.c.
References equals(), FALSE, free(), and TRUE.
 {
     private_traffic_selector_t *subset;
     bool contained_in = FALSE;
     subset = (private_traffic_selector_t*)get_subset(this, other);
     if (subset)
     {
         if (equals(subset, &this->public))
         {
             contained_in = TRUE;
         }
         free(subset);
     }
     return contained_in;
 }
METHOD (traffic_selector_t , includes , bool , private_traffic_selector_t * this, host_t * host)
Definition at line 594 of file traffic_selector.c.
References addr, FALSE, family, from, host_t::get_address, host_t::get_family, chunk_t::len, chunk_t::ptr, to, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
 {
     chunk_t addr;
     int family = host->get_family(host);
     if ((family == AF_INET && this->type == TS_IPV4_ADDR_RANGE) ||
         (family == AF_INET6 && this->type == TS_IPV6_ADDR_RANGE))
     {
         addr = host->get_address(host);
         return memcmp(this->from, addr.ptr, addr.len) <= 0 &&
                 memcmp(this->to, addr.ptr, addr.len) >= 0;
     }
     return FALSE;
 }
METHOD (traffic_selector_t , to_subnet , bool , private_traffic_selector_t * this, host_t ** net, u_int8_t * mask)
Definition at line 612 of file traffic_selector.c.
References calc_netbits(), chunk_free(), FALSE, family, from_port, host_create_from_chunk(), chunk_t::len, malloc(), mask, memcpy, memset, NON_SUBNET_ADDRESS_RANGE, port, chunk_t::ptr, to_port, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
 {
     /* there is no way to do this cleanly, as the address range may
      * be anything else but a subnet. We use from_addr as subnet
      * and try to calculate a usable subnet mask.
      */
     int family, non_zero_bytes;
     u_int16_t port = 0;
     chunk_t net_chunk;
     *mask = (this->netbits == NON_SUBNET_ADDRESS_RANGE) ? calc_netbits(this)
                                                         : this->netbits;
     switch (this->type)
     {
         case TS_IPV4_ADDR_RANGE:
             family = AF_INET;
             net_chunk.len = sizeof(this->from4);
             break;
         case TS_IPV6_ADDR_RANGE:
             family = AF_INET6;
             net_chunk.len = sizeof(this->from6);
             break;
         default:
             /* unreachable */
             return FALSE;
     }
     net_chunk.ptr = malloc(net_chunk.len);
     memset(net_chunk.ptr, 0x00, net_chunk.len);
     if (*mask)
     {
         non_zero_bytes = (*mask + 7) / 8;
         memcpy(net_chunk.ptr, this->from, non_zero_bytes);
         net_chunk.ptr[non_zero_bytes-1] &= 0xFF << (8 * non_zero_bytes - *mask);
     }
     if (this->to_port == this->from_port)
     {
         port = this->to_port;
     }
     *net = host_create_from_chunk(family, net_chunk, port);
     chunk_free(&net_chunk);
     return this->netbits != NON_SUBNET_ADDRESS_RANGE;
 }
METHOD (traffic_selector_t , clone_ , traffic_selector_t * , private_traffic_selector_t * this)
Definition at line 661 of file traffic_selector.c.
References dynamic, private_traffic_selector_t::dynamic, private_traffic_selector_t::from4, private_traffic_selector_t::from6, from_port, memcpy, private_traffic_selector_t::netbits, protocol, private_traffic_selector_t::public, private_traffic_selector_t::to4, private_traffic_selector_t::to6, to_port, traffic_selector_create(), TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, type, and private_traffic_selector_t::type.
 {
     private_traffic_selector_t *clone;
     clone = traffic_selector_create(this->protocol, this->type,
                                     this->from_port, this->to_port);
     clone->netbits = this->netbits;
     clone->dynamic = this->dynamic;
     switch (clone->type)
     {
         case TS_IPV4_ADDR_RANGE:
             memcpy(clone->from4, this->from4, sizeof(this->from4));
             memcpy(clone->to4, this->to4, sizeof(this->to4));
             return &clone->public;
         case TS_IPV6_ADDR_RANGE:
             memcpy(clone->from6, this->from6, sizeof(this->from6));
             memcpy(clone->to6, this->to6, sizeof(this->to6));
             return &clone->public;
         default:
             /* unreachable */
             return &clone->public;
     }
 }
METHOD (traffic_selector_t , hash , u_int , private_traffic_selector_t * this, u_int hash)
Definition at line 687 of file traffic_selector.c.
References chunk_from_thing, chunk_hash_inc(), from_port, protocol, and to_port.
 {
     return chunk_hash_inc(get_from_address(this),
             chunk_hash_inc(get_to_address(this),
              chunk_hash_inc(chunk_from_thing(this->from_port),
               chunk_hash_inc(chunk_from_thing(this->to_port),
                chunk_hash_inc(chunk_from_thing(this->protocol),
                 hash)))));
 }
METHOD (traffic_selector_t , destroy , void , private_traffic_selector_t * this)
Definition at line 698 of file traffic_selector.c.
References free().
 {
     free(this);
 }
static int print_icmp (printf_hook_data_t * data, u_int16_t port) static
Print ICMP/ICMPv6 type and code
Definition at line 198 of file traffic_selector.c.
References code, print_in_hook(), traffic_selector_icmp_code(), traffic_selector_icmp_type(), and type.
Referenced by traffic_selector_printf_hook().
 {
     u_int8_t type, code;
     type = traffic_selector_icmp_type(port);
     code = traffic_selector_icmp_code(port);
     if (code)
     {
         return print_in_hook(data, "%d(%d)", type, code);
     }
     return print_in_hook(data, "%d", type);
 }
static private_traffic_selector_t * traffic_selector_create (u_int8_t protocol, ts_type_t type, u_int16_t from_port, u_int16_t to_port) static
internal generic constructor
Definition at line 964 of file traffic_selector.c.
References from_port, INIT, protocol, to_port, and type.
Referenced by METHOD(), traffic_selector_create_dynamic(), traffic_selector_create_from_bytes(), traffic_selector_create_from_rfc3779_format(), traffic_selector_create_from_string(), and traffic_selector_create_from_subnet().
 {
     private_traffic_selector_t *this;
     INIT(this,
         .public = {
             .get_subset = _get_subset,
             .equals = _equals,
             .get_from_address = _get_from_address,
             .get_to_address = _get_to_address,
             .get_from_port = _get_from_port,
             .get_to_port = _get_to_port,
             .get_type = _get_type,
             .get_protocol = _get_protocol,
             .is_host = _is_host,
             .is_dynamic = _is_dynamic,
             .is_contained_in = _is_contained_in,
             .includes = _includes,
             .set_address = _set_address,
             .to_subnet = _to_subnet,
             .clone = _clone_,
             .hash = _hash,
             .destroy = _destroy,
         },
         .from_port = from_port,
         .to_port = to_port,
         .protocol = protocol,
         .type = type,
     );
     if (protocol == IPPROTO_ICMP || protocol == IPPROTO_ICMPV6)
     {
         this->from_port = from_port < 256 ? from_port << 8 : from_port;
         this->to_port = to_port < 256 ? to_port << 8 : to_port;
     }
     return this;
 }