strongSwan: plugin_loader_t Struct Reference
plugin_loader_t Struct Reference
plugin_loader
#include "plugin_loader.h"
Public Attributes
void(* add_static_features)(plugin_loader_t *this, const char *name, struct plugin_feature_t *features, int count, bool critical, bool(*reload)(void *), void *reload_data)
bool(* load)(plugin_loader_t *this, char *list)
void(* add_path)(plugin_loader_t *this, char *path)
u_int(* reload)(plugin_loader_t *this, char *list)
void(* unload)(plugin_loader_t *this)
enumerator_t *(* create_plugin_enumerator)(plugin_loader_t *this)
bool(* has_feature)(plugin_loader_t *this, struct plugin_feature_t feature)
char *(* loaded_plugins)(plugin_loader_t *this)
void(* status)(plugin_loader_t *this, level_t level)
void(* destroy)(plugin_loader_t *this)
Detailed Description
The plugin_loader loads plugins from a directory and initializes them
Definition at line 36 of file plugin_loader.h.
Member Data Documentation
void(* plugin_loader_t::add_path)(plugin_loader_t *this, char *path)
Add an additional search path for plugins.
These will be searched in the order they were added.
Parameters
path path containing loadable plugins
Definition at line 99 of file plugin_loader.h.
Referenced by plugin_loader_add_plugindirs().
void(* plugin_loader_t::add_static_features)(plugin_loader_t *this, const char *name, struct plugin_feature_t *features, int count, bool critical, bool(*reload)(void *), void *reload_data)
Add static plugin features, not loaded via plugins.
Similar to features provided by plugins they are evaluated during load(), and unloaded when unload() is called.
If critical is TRUE load() will fail if any of the added features could not be loaded.
If a reload callback function is given, it gets invoked for the registered feature set when reload() is invoked on the plugin_loader.
Note
The name should be unique otherwise a plugin with the same name is not loaded.
Parameters
name name of the component adding the features
features array of plugin features
count number of features in the array
critical TRUE if the features are critical
reload feature reload callback, or NULL
reload_data user data to pass to reload callback
Definition at line 60 of file plugin_loader.h.
Referenced by init(), main(), METHOD(), nm_backend_register(), register_dh_mapping(), and test_runner_init().
enumerator_t*(* plugin_loader_t::create_plugin_enumerator)(plugin_loader_t *this)
Create an enumerator over all loaded plugins.
In addition to the plugin, the enumerator optionally provides a list of pointers to plugin features currently loaded. This list has to be destroyed.
Returns
enumerator over plugin_t*, linked_list_t*
Definition at line 123 of file plugin_loader.h.
Referenced by CALLBACK(), and list_plugins().
void(* plugin_loader_t::destroy)(plugin_loader_t *this)
Unload loaded plugins, destroy plugin_loader instance.
Definition at line 152 of file plugin_loader.h.
bool(* plugin_loader_t::has_feature)(plugin_loader_t *this, struct plugin_feature_t feature)
Check if the given feature is available and loaded.
Parameters
feature feature to check
Returns
TRUE if feature available
Definition at line 131 of file plugin_loader.h.
Referenced by load_suites(), METHOD(), test_bad_sigs(), and test_good_sig().
bool(* plugin_loader_t::load)(plugin_loader_t *this, char *list)
Load a list of plugins.
Each plugin in list may have an ending exclamation mark (!) to mark it as a critical plugin. If loading a critical plugin fails, plugin loading is aborted and FALSE is returned.
Additional paths can be added with add_path(), these will be searched for the plugins first, in the order they were added, then the default path follows.
If <ns>.load_modular is enabled (where <ns> is lib->ns) the plugins to load are determined via a load option in their respective plugin config section e.g. <ns>.plugins.<plugin>.load = <priority|bool>. The oder is determined by the configured priority. If two plugins have the same priority the order as seen in list is preserved. Plugins not found in list are loaded first, in alphabetical order.
Note
Even though this method could be called multiple times this is currently not really supported in regards to plugin features and their dependencies (in particular soft dependencies).
Parameters
list space separated list of plugins to load
Returns
TRUE if all critical plugins loaded successfully
Definition at line 90 of file plugin_loader.h.
Referenced by init(), libimcv_init(), main(), METHOD(), and test_runner_init().
char*(* plugin_loader_t::loaded_plugins)(plugin_loader_t *this)
Get a simple list the names of all loaded plugins.
The function returns internal data, do not free.
Returns
list of the names of all loaded plugins
Definition at line 140 of file plugin_loader.h.
Referenced by command_usage(), main(), and METHOD().
u_int(* plugin_loader_t::reload)(plugin_loader_t *this, char *list)
Reload the configuration of one or multiple plugins.
Parameters
space separated plugin names to reload, NULL for all
Returns
number of plugins that did support reloading
Definition at line 107 of file plugin_loader.h.
Referenced by CALLBACK(), and run().
void(* plugin_loader_t::status)(plugin_loader_t *this, level_t level)
Log status about loaded plugins and features.
Parameters
level log level to use
Definition at line 147 of file plugin_loader.h.
Referenced by init(), init_and_run(), load_suites(), and main().
void(* plugin_loader_t::unload)(plugin_loader_t *this)
Unload all loaded plugins.
Definition at line 112 of file plugin_loader.h.
Referenced by destroy(), and test_runner_init().
The documentation for this struct was generated from the following file:
plugin_loader.h