strongSwan: imc_msg_t Struct Reference
imc_msg_t Struct Reference
imc_msg
#include "imc_msg.h"
Public Attributes
TNC_UInt32(* get_src_id)(imc_msg_t *this)
TNC_UInt32(* get_dst_id)(imc_msg_t *this)
pen_type_t(* get_msg_type)(imc_msg_t *this)
TNC_Result(* send)(imc_msg_t *this, bool excl)
TNC_Result(* receive)(imc_msg_t *this, imc_msg_t *out_msg, bool *fatal_error)
void(* add_attribute)(imc_msg_t *this, pa_tnc_attr_t *attr)
enumerator_t *(* create_attribute_enumerator)(imc_msg_t *this)
chunk_t(* get_encoding)(imc_msg_t *this)
void(* destroy)(imc_msg_t *this)
Detailed Description
Interface for a PA-TNC message handled by an IMC.
Definition at line 34 of file imc_msg.h.
Member Data Documentation
void(* imc_msg_t::add_attribute)(imc_msg_t *this, pa_tnc_attr_t *attr)
Add a PA-TNC attribute to the send queue
Parameters
attr PA-TNC attribute to be added
Definition at line 80 of file imc_msg.h.
Referenced by add_attrs_natural_lang(), add_certification_state(), add_configuration_state(), add_default_pwd_enabled(), add_device_id(), add_forwarding_enabled(), add_fwd_enabled(), add_installed_packages(), add_machine_type_model(), add_numeric_version(), add_op_status(), add_port_filter(), add_product_info(), add_pstn_fax_enabled(), add_quadruple(), add_settings(), add_string_version(), add_swid_inventory(), add_time_source(), add_user_app_enabled(), add_user_app_persist_enabled(), add_vendor_name(), add_vendor_smi_code(), create_message(), imc_attestation_process(), METHOD(), receive_message(), and TNC_IMC_BeginHandshake().
enumerator_t*(* imc_msg_t::create_attribute_enumerator)(imc_msg_t *this)
Enumerator over PA-TNC attributes contained in the PA-TNC message
Returns
PA-TNC attribute enumerator
Definition at line 87 of file imc_msg.h.
Referenced by receive_message().
void(* imc_msg_t::destroy)(imc_msg_t *this)
Destroys a imc_msg_t object.
Definition at line 99 of file imc_msg.h.
Referenced by receive_message(), TNC_IMC_BeginHandshake(), TNC_IMC_ReceiveMessage(), and TNC_IMC_ReceiveMessageLong().
TNC_UInt32(* imc_msg_t::get_dst_id)(imc_msg_t *this)
Get destination ID of PA-TNC message
Returns
destination ID
Definition at line 48 of file imc_msg.h.
Referenced by receive_message().
chunk_t(* imc_msg_t::get_encoding)(imc_msg_t *this)
Get the encoding of the IMC message.
Returns
message encoding, internal data
Definition at line 94 of file imc_msg.h.
pen_type_t(* imc_msg_t::get_msg_type)(imc_msg_t *this)
Get the PA-TNC message type.
Returns
message type
Definition at line 55 of file imc_msg.h.
Referenced by receive_message().
TNC_UInt32(* imc_msg_t::get_src_id)(imc_msg_t *this)
Get source ID of PA-TNC message
Returns
src ID
Definition at line 41 of file imc_msg.h.
TNC_Result(* imc_msg_t::receive)(imc_msg_t *this, imc_msg_t *out_msg, bool *fatal_error)
Processes a received PA-TNC message
Parameters
out_msg outgoing PA-TN message
fatal_error TRUE if IMV sent a fatal error message
Returns
TNC result code
Definition at line 72 of file imc_msg.h.
Referenced by receive_message().
TNC_Result(* imc_msg_t::send)(imc_msg_t *this, bool excl)
Sends one or multiple PA-TNC messages
Parameters
excl set the excl message flag if supported
Returns
TNC result code
Definition at line 63 of file imc_msg.h.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
The documentation for this struct was generated from the following file:
imc_msg.h