strongSwan: tnc_imc_plugin.c File Reference
tnc_imc_plugin.c File Reference
#include "tnc_imc_plugin.h"
#include "tnc_imc_manager.h"
#include <tnc/tnc.h>
Classes
struct private_tnc_imc_plugin_t
Typedefs
typedef struct
private_tnc_imc_plugin_t private_tnc_imc_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_tnc_imc_plugin_t *this)
METHOD (plugin_t, get_features, int, private_tnc_imc_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_tnc_imc_plugin_t *this)
plugin_t * tnc_imc_plugin_create (void)
Typedef Documentation
typedef struct private_tnc_imc_plugin_t private_tnc_imc_plugin_t
Definition at line 21 of file tnc_imc_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_tnc_imc_plugin_t * this)
Definition at line 34 of file tnc_imc_plugin.c.
 {
     return "tnc-imc";
 }
METHOD (plugin_t , get_features , int , private_tnc_imc_plugin_t * this, plugin_feature_t * features[])
Definition at line 40 of file tnc_imc_plugin.c.
References CERT_TRUSTED_PUBKEY, CERT_X509, countof, PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, PLUGIN_SDEPEND, tnc_imc_manager_create(), and tnc_manager_register().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(tnc_manager_register, tnc_imc_manager_create),
             PLUGIN_PROVIDE(CUSTOM, "imc-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "tnccs-manager"),
                 PLUGIN_SDEPEND(CUSTOM, "imv-manager"),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_TRUSTED_PUBKEY),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_tnc_imc_plugin_t * this)
Definition at line 55 of file tnc_imc_plugin.c.
References free().
 {
     free(this);
 }
plugin_t* tnc_imc_plugin_create (void)
Definition at line 64 of file tnc_imc_plugin.c.
References INIT.
 {
     private_tnc_imc_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }