strongSwan: ike_natd.c File Reference
ike_natd.c File Reference
#include "ike_natd.h"
#include <string.h>
#include <hydra.h>
#include <daemon.h>
#include <config/peer_cfg.h>
#include <crypto/hashers/hasher.h>
#include <encoding/payloads/notify_payload.h>
Classes
struct private_ike_natd_t
Typedefs
typedef struct private_ike_natd_t private_ike_natd_t
Functions
static bool force_encap (ike_cfg_t *ike_cfg)
static chunk_t generate_natd_hash (private_ike_natd_t *this, ike_sa_id_t *ike_sa_id, host_t *host)
static notify_payload_t * build_natd_payload (private_ike_natd_t *this, notify_type_t type, host_t *host)
static void process_payloads (private_ike_natd_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_ike_natd_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_ike_natd_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_ike_natd_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_ike_natd_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_ike_natd_t *this)
METHOD (task_t, migrate, void, private_ike_natd_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_ike_natd_t *this)
METHOD (ike_natd_t, has_mapping_changed, bool, private_ike_natd_t *this)
ike_natd_t * ike_natd_create (ike_sa_t *ike_sa, bool initiator)
Typedef Documentation
typedef struct private_ike_natd_t private_ike_natd_t
Definition at line 28 of file ike_natd.c.
Function Documentation
static notify_payload_t* build_natd_payload (private_ike_natd_t * this, notify_type_t type, host_t * host) static
Build a NAT detection notify payload.
Definition at line 134 of file ike_natd.c.
References addr, chunk_free(), chunk_from_chars, chunk_from_thing, chunk_hash(), host_t::destroy, force_encap(), generate_natd_hash(), hash, host_create_from_chunk(), chunk_t::len, NAT_DETECTION_SOURCE_IP, notify(), notify_payload_create(), PLV2_NOTIFY, notify_payload_t::set_notification_data, and notify_payload_t::set_notify_type.
Referenced by METHOD().
 {
     chunk_t hash;
     notify_payload_t *notify;
     ike_sa_id_t *ike_sa_id;
     ike_cfg_t *config;
     ike_sa_id = this->ike_sa->get_id(this->ike_sa);
     config = this->ike_sa->get_ike_cfg(this->ike_sa);
     if (force_encap(config) && type == NAT_DETECTION_SOURCE_IP)
     {
         u_int32_t addr;
         /* chunk_hash() is randomly keyed so this produces a random IPv4 address
          * that changes with every restart but otherwise stays the same */
         addr = chunk_hash(chunk_from_chars(0x00, 0x00, 0x00, 0x00));
         host = host_create_from_chunk(AF_INET, chunk_from_thing(addr), 0);
         hash = generate_natd_hash(this, ike_sa_id, host);
         host->destroy(host);
     }
     else
     {
         hash = generate_natd_hash(this, ike_sa_id, host);
     }
     if (!hash.len)
     {
         return NULL;
     }
     notify = notify_payload_create(PLV2_NOTIFY);
     notify->set_notify_type(notify, type);
     notify->set_notification_data(notify, hash);
     chunk_free(&hash);
     return notify;
 }
static bool force_encap (ike_cfg_t * ike_cfg) static
Check if UDP encapsulation has to be forced either by config or required by the kernel interface
Definition at line 85 of file ike_natd.c.
References ike_cfg_t::force_encap, kernel_interface_t::get_features, hydra, hydra_t::kernel_interface, KERNEL_REQUIRE_UDP_ENCAPSULATION, and TRUE.
Referenced by build_natd_payload(), METHOD(), and process_payloads().
 {
     if (!ike_cfg->force_encap(ike_cfg))
     {
         return hydra->kernel_interface->get_features(hydra->kernel_interface) &
                     KERNEL_REQUIRE_UDP_ENCAPSULATION;
     }
     return TRUE;
 }
static chunk_t generate_natd_hash (private_ike_natd_t * this, ike_sa_id_t * ike_sa_id, host_t * host) static
Build NAT detection hash for a host
Definition at line 98 of file ike_natd.c.
References chunk_cat, chunk_empty, chunk_free(), DBG3, DBG_IKE, host_t::get_address, ike_sa_id_t::get_initiator_spi, host_t::get_port, ike_sa_id_t::get_responder_spi, hasher, chunk_t::len, port, and chunk_t::ptr.
Referenced by build_natd_payload(), and process_payloads().
 {
     chunk_t natd_chunk, spi_i_chunk, spi_r_chunk, addr_chunk, port_chunk;
     chunk_t natd_hash;
     u_int64_t spi_i, spi_r;
     u_int16_t port;
     /* prepare all required chunks */
     spi_i = ike_sa_id->get_initiator_spi(ike_sa_id);
     spi_r = ike_sa_id->get_responder_spi(ike_sa_id);
     spi_i_chunk.ptr = (void*)&spi_i;
     spi_i_chunk.len = sizeof(spi_i);
     spi_r_chunk.ptr = (void*)&spi_r;
     spi_r_chunk.len = sizeof(spi_r);
     port = htons(host->get_port(host));
     port_chunk.ptr = (void*)&port;
     port_chunk.len = sizeof(port);
     addr_chunk = host->get_address(host);
     /*  natd_hash = SHA1( spi_i | spi_r | address | port ) */
     natd_chunk = chunk_cat("cccc", spi_i_chunk, spi_r_chunk, addr_chunk, port_chunk);
     if (!this->hasher->allocate_hash(this->hasher, natd_chunk, &natd_hash))
     {
         natd_hash = chunk_empty;
     }
     DBG3(DBG_IKE, "natd_chunk %B", &natd_chunk);
     DBG3(DBG_IKE, "natd_hash %B", &natd_hash);
     chunk_free(&natd_chunk);
     return natd_hash;
 }
METHOD (task_t , process_i , status_t , private_ike_natd_t * this, message_t * message)
Definition at line 267 of file ike_natd.c.
References COND_NAT_ANY, EXT_NATT, message_t::get_exchange_type, IKE_SA_INIT, process_payloads(), SUCCESS, and peer_cfg_t::use_mobike.
 {
     process_payloads(this, message);
     if (message->get_exchange_type(message) == IKE_SA_INIT)
     {
         peer_cfg_t *peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
         if (this->ike_sa->has_condition(this->ike_sa, COND_NAT_ANY) ||
             /* if peer supports NAT-T, we switch to port 4500 even
              * if no NAT is detected. can't be done later (when we would know
              * whether the peer supports MOBIKE) because there would be no
              * exchange to actually do the switch (other than a forced DPD). */
             (peer_cfg->use_mobike(peer_cfg) &&
              this->ike_sa->supports_extension(this->ike_sa, EXT_NATT)))
         {
             this->ike_sa->float_ports(this->ike_sa);
         }
     }
     return SUCCESS;
 }
METHOD (task_t , build_i , status_t , private_ike_natd_t * this, message_t * message)
Definition at line 290 of file ike_natd.c.
References message_t::add_payload, ADDR_TYPE_REGULAR, build_natd_payload(), host_t::clone, kernel_interface_t::create_address_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, host_t::destroy, enumerator_t::enumerate, force_encap(), message_t::get_destination, ike_cfg_t::get_my_port, message_t::get_source, kernel_interface_t::get_source_addr, hasher, host, hydra, host_t::is_anyaddr, hydra_t::kernel_interface, NAT_DETECTION_DESTINATION_IP, NAT_DETECTION_SOURCE_IP, NEED_MORE, notify(), and host_t::set_port.
 {
     notify_payload_t *notify;
     enumerator_t *enumerator;
     ike_cfg_t *ike_cfg;
     host_t *host;
     if (this->hasher == NULL)
     {
         DBG1(DBG_IKE, "unable to build NATD payloads, SHA1 not supported");
         return NEED_MORE;
     }
     ike_cfg = this->ike_sa->get_ike_cfg(this->ike_sa);
     /* destination is always set */
     host = message->get_destination(message);
     notify = build_natd_payload(this, NAT_DETECTION_DESTINATION_IP, host);
     if (notify)
     {
         message->add_payload(message, (payload_t*)notify);
     }
     /* source may be any, we have 3 possibilities to get our source address:
      * 1. It is defined in the config => use the one of the IKE_SA
      * 2. We do a routing lookup in the kernel interface
      * 3. Include all possbile addresses
      */
     host = message->get_source(message);
     if (!host->is_anyaddr(host) || force_encap(ike_cfg))
     {   /* 1. or if we force UDP encap, as it doesn't matter if it's %any */
         notify = build_natd_payload(this, NAT_DETECTION_SOURCE_IP, host);
         if (notify)
         {
             message->add_payload(message, (payload_t*)notify);
         }
     }
     else
     {
         host = hydra->kernel_interface->get_source_addr(hydra->kernel_interface,
                             this->ike_sa->get_other_host(this->ike_sa), NULL);
         if (host)
         {   /* 2. */
             host->set_port(host, ike_cfg->get_my_port(ike_cfg));
             notify = build_natd_payload(this, NAT_DETECTION_SOURCE_IP, host);
             if (notify)
             {
                 message->add_payload(message, (payload_t*)notify);
             }
             host->destroy(host);
         }
         else
         {   /* 3. */
             enumerator = hydra->kernel_interface->create_address_enumerator(
                                     hydra->kernel_interface, ADDR_TYPE_REGULAR);
             while (enumerator->enumerate(enumerator, (void**)&host))
             {
                 /* apply port 500 to host, but work on a copy */
                 host = host->clone(host);
                 host->set_port(host, ike_cfg->get_my_port(ike_cfg));
                 notify = build_natd_payload(this, NAT_DETECTION_SOURCE_IP, host);
                 host->destroy(host);
                 if (notify)
                 {
                     message->add_payload(message, (payload_t*)notify);
                 }
             }
             enumerator->destroy(enumerator);
         }
     }
     return NEED_MORE;
 }
METHOD (task_t , build_r , status_t , private_ike_natd_t * this, message_t * message)
Definition at line 364 of file ike_natd.c.
References message_t::add_payload, build_natd_payload(), DBG1, DBG_IKE, message_t::get_destination, message_t::get_exchange_type, message_t::get_payload, message_t::get_source, hasher, IKE_SA_INIT, me, NAT_DETECTION_DESTINATION_IP, NAT_DETECTION_SOURCE_IP, notify(), PLV2_SECURITY_ASSOCIATION, and SUCCESS.
 {
     notify_payload_t *notify;
     host_t *me, *other;
     /* only add notifies on successful responses. */
     if (message->get_exchange_type(message) == IKE_SA_INIT &&
         message->get_payload(message, PLV2_SECURITY_ASSOCIATION) == NULL)
     {
         return SUCCESS;
     }
     if (this->src_seen && this->dst_seen)
     {
         if (this->hasher == NULL)
         {
             DBG1(DBG_IKE, "unable to build NATD payloads, SHA1 not supported");
             return SUCCESS;
         }
         /* initiator seems to support NAT detection, add response */
         me = message->get_source(message);
         notify = build_natd_payload(this, NAT_DETECTION_SOURCE_IP, me);
         if (notify)
         {
             message->add_payload(message, (payload_t*)notify);
         }
         other = message->get_destination(message);
         notify = build_natd_payload(this, NAT_DETECTION_DESTINATION_IP, other);
         if (notify)
         {
             message->add_payload(message, (payload_t*)notify);
         }
     }
     return SUCCESS;
 }
METHOD (task_t , process_r , status_t , private_ike_natd_t * this, message_t * message)
Definition at line 402 of file ike_natd.c.
References NEED_MORE, and process_payloads().
 {
     process_payloads(this, message);
     return NEED_MORE;
 }
METHOD (task_t , get_type , task_type_t , private_ike_natd_t * this)
Definition at line 410 of file ike_natd.c.
References TASK_IKE_NATD.
 {
     return TASK_IKE_NATD;
 }
METHOD (task_t , migrate , void , private_ike_natd_t * this, ike_sa_t * ike_sa)
Definition at line 416 of file ike_natd.c.
References FALSE.
 {
     this->ike_sa = ike_sa;
     this->src_seen = FALSE;
     this->dst_seen = FALSE;
     this->src_matched = FALSE;
     this->dst_matched = FALSE;
     this->mapping_changed = FALSE;
 }
METHOD (task_t , destroy , void , private_ike_natd_t * this)
Definition at line 427 of file ike_natd.c.
References DESTROY_IF, free(), and hasher.
 {
     DESTROY_IF(this->hasher);
     free(this);
 }
METHOD (ike_natd_t , has_mapping_changed , bool , private_ike_natd_t * this)
Definition at line 434 of file ike_natd.c.
 {
     return this->mapping_changed;
 }
static void process_payloads (private_ike_natd_t * this, message_t * message) static
read notifys from message and evaluate them
Definition at line 174 of file ike_natd.c.
References chunk_equals(), chunk_free(), COND_NAT_FAKE, COND_NAT_HERE, COND_NAT_THERE, message_t::create_payload_enumerator, DBG3, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, EXT_NATT, force_encap(), generate_natd_hash(), message_t::get_destination, message_t::get_exchange_type, message_t::get_ike_sa_id, notify_payload_t::get_notification_data, notify_payload_t::get_notify_type, message_t::get_source, payload_t::get_type, hash, INFORMATIONAL, initiator, me, NAT_DETECTION_DESTINATION_IP, NAT_DETECTION_SOURCE_IP, notify(), PLV2_NOTIFY, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     notify_payload_t *notify;
     chunk_t hash, src_hash, dst_hash;
     ike_sa_id_t *ike_sa_id;
     host_t *me, *other;
     ike_cfg_t *config;
     /* Precompute NAT-D hashes for incoming NAT notify comparison */
     ike_sa_id = message->get_ike_sa_id(message);
     me = message->get_destination(message);
     other = message->get_source(message);
     dst_hash = generate_natd_hash(this, ike_sa_id, me);
     src_hash = generate_natd_hash(this, ike_sa_id, other);
     DBG3(DBG_IKE, "precalculated src_hash %B", &src_hash);
     DBG3(DBG_IKE, "precalculated dst_hash %B", &dst_hash);
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) != PLV2_NOTIFY)
         {
             continue;
         }
         notify = (notify_payload_t*)payload;
         switch (notify->get_notify_type(notify))
         {
             case NAT_DETECTION_DESTINATION_IP:
             {
                 this->dst_seen = TRUE;
                 hash = notify->get_notification_data(notify);
                 if (!this->dst_matched)
                 {
                     DBG3(DBG_IKE, "received dst_hash %B", &hash);
                     if (chunk_equals(hash, dst_hash))
                     {
                         this->dst_matched = TRUE;
                     }
                 }
                 /* RFC4555 says we should also compare against IKE_SA_INIT
                  * NATD payloads, but this does not work: We are running
                  * there at port 500, but use 4500 afterwards... */
                 if (message->get_exchange_type(message) == INFORMATIONAL &&
                     this->initiator && !this->dst_matched)
                 {
                     this->mapping_changed = this->ike_sa->has_mapping_changed(
                                                             this->ike_sa, hash);
                 }
                 break;
             }
             case NAT_DETECTION_SOURCE_IP:
             {
                 this->src_seen = TRUE;
                 if (!this->src_matched)
                 {
                     hash = notify->get_notification_data(notify);
                     DBG3(DBG_IKE, "received src_hash %B", &hash);
                     if (chunk_equals(hash, src_hash))
                     {
                         this->src_matched = TRUE;
                     }
                 }
                 break;
             }
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     chunk_free(&src_hash);
     chunk_free(&dst_hash);
     if (this->src_seen && this->dst_seen)
     {
         this->ike_sa->enable_extension(this->ike_sa, EXT_NATT);
         this->ike_sa->set_condition(this->ike_sa, COND_NAT_HERE,
                                     !this->dst_matched);
         this->ike_sa->set_condition(this->ike_sa, COND_NAT_THERE,
                                     !this->src_matched);
         config = this->ike_sa->get_ike_cfg(this->ike_sa);
         if (this->dst_matched && this->src_matched &&
             force_encap(config))
         {
             this->ike_sa->set_condition(this->ike_sa, COND_NAT_FAKE, TRUE);
         }
     }
 }