strongSwan: hash_algorithm_set
hash_algorithm_set
crypto
Classes
struct hash_algorithm_set_t
Typedefs
typedef struct hash_algorithm_set_t hash_algorithm_set_t
Functions
hash_algorithm_set_t * hash_algorithm_set_create ()
Detailed Description
Typedef Documentation
typedef struct hash_algorithm_set_t hash_algorithm_set_t
Definition at line 24 of file hash_algorithm_set.h.
Function Documentation
hash_algorithm_set_t* hash_algorithm_set_create ()
Create a set of hash algorithms.
Returns
hash_algorithm_set_t instance
Described in header
Definition at line 97 of file hash_algorithm_set.c.
References array_create(), and INIT.
Referenced by METHOD(), and send_supported_hash_algorithms().
 {
     private_hash_algorithm_set_t *this;
     INIT(this,
         .public = {
             .add = _add,
             .contains = _contains,
             .count = _count,
             .create_enumerator = _create_enumerator,
             .destroy = _destroy,
         },
         .algorithms = array_create(sizeof(hash_algorithm_t), 0),
     );
     return &this->public;
 }