strongSwan: keymat
keymat
tkm
Classes
struct tkm_keymat_t
Typedefs
typedef struct tkm_keymat_t tkm_keymat_t
Functions
tkm_keymat_t * tkm_keymat_create (bool initiator)
Detailed Description
Typedef Documentation
typedef struct tkm_keymat_t tkm_keymat_t
Definition at line 27 of file tkm_keymat.h.
Function Documentation
tkm_keymat_t* tkm_keymat_create (bool initiator)
Create TKM keymat instance.
Parameters
initiator TRUE if we are the initiator
Returns
keymat instance
See header.
Definition at line 506 of file tkm_keymat.c.
References tkm_id_manager_t::acquire_id, chunk_empty, free(), tkm_t::idmgr, INIT, initiator, tkm, and TKM_CTX_ISA.
Referenced by main(), and START_TEST().
 {
     private_tkm_keymat_t *this;
     INIT(this,
         .public = {
             .keymat_v2 = {
                 .keymat = {
                     .get_version = _get_version,
                     .create_dh = _create_dh,
                     .create_nonce_gen = _create_nonce_gen,
                     .get_aead = _get_aead,
                     .destroy = _destroy,
                 },
                 .derive_ike_keys = _derive_ike_keys,
                 .derive_child_keys = _derive_child_keys,
                 .get_skd = _get_skd,
                 .get_auth_octets = _get_auth_octets,
                 .get_psk_sig = _get_psk_sig,
                 .add_hash_algorithm = _add_hash_algorithm,
                 .hash_algorithm_supported = _hash_algorithm_supported,
             },
             .get_isa_id = _get_isa_id,
             .set_auth_payload = _set_auth_payload,
             .get_auth_payload = _get_auth_payload,
             .get_peer_init_msg = _get_peer_init_msg,
         },
         .initiator = initiator,
         .isa_ctx_id = tkm->idmgr->acquire_id(tkm->idmgr, TKM_CTX_ISA),
         .ae_ctx_id = 0,
         .auth_payload = chunk_empty,
         .other_init_msg = chunk_empty,
     );
     if (!this->isa_ctx_id)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }