strongSwan: credential_factory_t Struct Reference
credential_factory_t Struct Reference
credential_factory
#include "credential_factory.h"
Public Attributes
void *(* create)(credential_factory_t *this, credential_type_t type, int subtype,...)
void(* add_builder)(credential_factory_t *this, credential_type_t type, int subtype, bool final, builder_function_t constructor)
void(* remove_builder)(credential_factory_t *this, builder_function_t constructor)
enumerator_t *(* create_builder_enumerator)(credential_factory_t *this)
void(* destroy)(credential_factory_t *this)
Detailed Description
Manages credential construction functions and creates instances.
Definition at line 54 of file credential_factory.h.
Member Data Documentation
void(* credential_factory_t::add_builder)(credential_factory_t *this, credential_type_t type, int subtype, bool final, builder_function_t constructor)
Register a credential builder function.
The final flag indicates if the registered builder can build such a credential itself the most common encoding, without the need for an additional builder.
Parameters
type type of credential the builder creates
subtype subtype of the credential, type specific
final TRUE if this build does not invoke other builders
constructor builder constructor function to register
Definition at line 85 of file credential_factory.h.
Referenced by handle_certs(), and plugin_feature_load().
void*(* credential_factory_t::create)(credential_factory_t *this, credential_type_t type, int subtype,...)
Create a credential using a list of builder_part_t's.
The variable argument list takes builder_part_t types followed by the type specific value. The list must be terminated using BUILD_END. All passed parts get cloned/refcounted by the builder functions, so free up allocated resources after successful and unsuccessful invocations.
Parameters
type credential type to build
subtype subtype specific for type of the credential
... build_part_t arguments, BUILD_END terminated.
Returns
type specific credential, NULL if failed
Definition at line 70 of file credential_factory.h.
Referenced by acert(), add_cert(), add_certificate(), add_device_id(), add_key(), CALLBACK(), connect_(), create_cert(), create_cert_ext(), decrypt(), decrypt_with_config(), dn(), do_args(), encrypt(), fetch_cert(), fetch_crl(), fetch_ocsp(), find_certificates(), find_pubkey_in_certs(), find_smartcard_key(), gen(), initiate_connection(), issue(), keyid(), load_agent(), load_aik(), load_ca_cert(), load_ca_certs(), load_ca_dir(), load_ca_file(), load_cacerts(), load_cdps(), load_cert(), load_certificate(), load_certs(), load_from_blob(), load_from_file(), load_from_smartcard(), load_issuer_cert(), load_issuer_key(), load_key(), load_keys(), load_pkcs12(), load_x509(), load_x509_aa(), load_x509_ac(), load_x509_crl(), main(), METHOD(), need_secrets(), parse(), parse_authenticated_safe(), parse_basicOCSPResponse(), parse_cert(), parse_certificate(), parse_certificate_request(), parse_PFX(), parse_private_key(), parse_public_key(), parse_rsa_private_key(), parse_rsa_public_key(), parse_safe_contents(), pkcs11_creds_load(), pkcs12(), pkcs7(), pkcs7_signed_data_gen(), print(), process_certificate(), pub(), pubkey_cert_wrap(), read_key(), read_serial(), req(), scep_build_request(), scep_parse_response(), self(), show(), sign(), sign_crl(), soap_init(), sshkey_certificate_load(), START_SETUP(), START_TEST(), and verify().
enumerator_t*(* credential_factory_t::create_builder_enumerator)(credential_factory_t *this)
Create an enumerator over registered builder types.
The enumerator returns only builder types registered with the final flag set.
Returns
enumerator (credential_type_t, int subtype)
Definition at line 104 of file credential_factory.h.
Referenced by tls_crypto_create().
void(* credential_factory_t::destroy)(credential_factory_t *this)
Destroy a credential_factory instance.
Definition at line 109 of file credential_factory.h.
void(* credential_factory_t::remove_builder)(credential_factory_t *this, builder_function_t constructor)
Unregister a credential builder function.
Parameters
constructor constructor function to unregister.
Definition at line 93 of file credential_factory.h.
Referenced by handle_certs(), and plugin_feature_unload().
The documentation for this struct was generated from the following file:
credential_factory.h