strongSwan: imv_t Struct Reference
imv_t Struct Reference
imv
#include "imv.h"
Public Attributes
TNC_Result(* initialize)(TNC_IMVID imvID, TNC_Version minVersion, TNC_Version maxVersion, TNC_Version *OutActualVersion)
TNC_Result(* notify_connection_change)(TNC_IMVID imvID, TNC_ConnectionID connectionID, TNC_ConnectionState newState)
TNC_Result(* solicit_recommendation)(TNC_IMVID imvID, TNC_ConnectionID connectionID)
TNC_Result(* receive_message)(TNC_IMVID imvID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
TNC_Result(* receive_message_long)(TNC_IMVID imvID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 sourceIMCID, TNC_UInt32 destinationIMVID)
TNC_Result(* batch_ending)(TNC_IMVID imvID, TNC_ConnectionID connectionID)
TNC_Result(* terminate)(TNC_IMVID imvID)
TNC_Result(* provide_bind_function)(TNC_IMVID imvID, TNC_TNCS_BindFunctionPointer bindFunction)
void(* set_id)(imv_t *this, TNC_IMVID id)
TNC_IMVID(* get_id)(imv_t *this)
void(* add_id)(imv_t *this, TNC_IMVID id)
bool(* has_id)(imv_t *this, TNC_IMVID id)
char *(* get_name)(imv_t *this)
void(* set_message_types)(imv_t *this, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
void(* set_message_types_long)(imv_t *this, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
bool(* type_supported)(imv_t *this, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
void(* destroy)(imv_t *this)
Detailed Description
Controls a single Integrity Measurement Verifier (IMV)
Definition at line 36 of file imv.h.
Member Data Documentation
void(* imv_t::add_id)(imv_t *this, TNC_IMVID id)
Assign an additional ID to an imv_t object.
Parameters
id additional IMV ID to be assigned
Definition at line 178 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::batch_ending)(TNC_IMVID imvID, TNC_ConnectionID connectionID)
The TNC Server calls this function to notify IMVs that all IMC messages received in a batch have been delivered and this is the IMV’s last chance to send a message in the batch of IMV messages currently being collected.
Parameters
imvID IMV ID assigned by TNCS
connectionID network connection ID assigned by TNCS
Returns
TNC result code
Definition at line 134 of file imv.h.
Referenced by METHOD().
void(* imv_t::destroy)(imv_t *this)
Destroys an imv_t object.
Definition at line 227 of file imv.h.
Referenced by METHOD().
TNC_IMVID(* imv_t::get_id)(imv_t *this)
Returns the ID of an imv_t object.
Returns
IMV ID assigned by TNCS
Definition at line 171 of file imv.h.
Referenced by METHOD(), and tnc_imv_recommendations_create().
char*(* imv_t::get_name)(imv_t *this)
Returns the name of an imv_t object.
Returns
name of IMV
Definition at line 192 of file imv.h.
Referenced by METHOD().
bool(* imv_t::has_id)(imv_t *this, TNC_IMVID id)
Checks if the ID is assigned to the imv_t object.
Returns
TRUE if IMV ID is assigned to imv_t object
Definition at line 185 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::initialize)(TNC_IMVID imvID, TNC_Version minVersion, TNC_Version maxVersion, TNC_Version *OutActualVersion)
The TNC Server calls this function to initialize the IMV and agree on the API version number to be used. It also supplies the IMV ID, an IMV identifier that the IMV must use when calling TNC Server callback functions.
Parameters
imvID IMV ID assigned by TNCS
minVersion minimum API version supported
maxVersion maximum API version supported by TNCS
OutActualVersion mutually supported API version number
Returns
TNC result code
Definition at line 49 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::notify_connection_change)(TNC_IMVID imvID, TNC_ConnectionID connectionID, TNC_ConnectionState newState)
The TNC Server calls this function to inform the IMV that the state of the network connection identified by connectionID has changed to newState.
Parameters
imvID IMV ID assigned by TNCS
connectionID network connection ID assigned by TNCS
newState new network connection state
Returns
TNC result code
Definition at line 63 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::provide_bind_function)(TNC_IMVID imvID, TNC_TNCS_BindFunctionPointer bindFunction)
IMVs implementing the UNIX/Linux Dynamic Linkage platform binding MUST define this additional function. The TNC Server MUST call the function immediately after calling TNC_IMV_Initialize to provide a pointer to the TNCS bind function. The IMV can then use the TNCS bind function to obtain pointers to any other TNCS functions.
Parameters
imvID IMV ID assigned by TNCS
bindFunction pointer to TNC_TNCS_BindFunction
Returns
TNC result code
Definition at line 156 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::receive_message)(TNC_IMVID imvID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
The TNC Server calls this function to deliver a message to the IMV. The message is contained in the buffer referenced by message and contains the number of octets indicated by messageLength. The type of the message is indicated by messageType.
Parameters
imvID IMV ID assigned by TNCS
connectionID network connection ID assigned by TNCS
message reference to buffer containing message
messageLength number of octets in message
messageType message type of message
Returns
TNC result code
Definition at line 92 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::receive_message_long)(TNC_IMVID imvID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 sourceIMCID, TNC_UInt32 destinationIMVID)
The TNC Server calls this function to deliver a message to the IMV. The message is contained in the buffer referenced by message and contains the number of octets indicated by messageLength. The type of the message is indicated by the message Vendor ID and message subtype.
Parameters
imvID IMV ID assigned by TNCS
connectionID network connection ID assigned by TNCS
messageFlags message flags
message reference to buffer containing message
messageLength number of octets in message
messageVendorID message Vendor ID
messageSubtype message subtype
sourceIMCID source IMC ID
destinationIMVID destination IMV ID
Returns
TNC result code
Definition at line 115 of file imv.h.
Referenced by METHOD().
void(* imv_t::set_id)(imv_t *this, TNC_IMVID id)
Sets the ID of an imv_t object.
Parameters
id IMV ID to be assigned
Definition at line 164 of file imv.h.
Referenced by METHOD().
void(* imv_t::set_message_types)(imv_t *this, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
Sets the supported message types of an imv_t object.
Parameters
supported_types list of messages type supported by IMV
type_count number of supported message types
Definition at line 200 of file imv.h.
Referenced by METHOD().
void(* imv_t::set_message_types_long)(imv_t *this, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
Sets the supported long message types of an imv_t object.
Parameters
supported_vids list of vendor IDs supported by IMC
supported_subtypes list of messages type supported by IMC
type_count number of supported message types
Definition at line 210 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::solicit_recommendation)(TNC_IMVID imvID, TNC_ConnectionID connectionID)
The TNC Server calls this function at the end of an Integrity Check Handshake (after all IMC-IMV messages have been delivered) to solicit recommendations from IMVs that have not yet provided a recommendation.
Parameters
imvID IMV ID assigned by TNCS
connectionID network connection ID assigned by TNCS
Returns
TNC result code
Definition at line 76 of file imv.h.
Referenced by METHOD().
TNC_Result(* imv_t::terminate)(TNC_IMVID imvID)
The TNC Server calls this function to close down the IMV.
Parameters
imvID IMV ID assigned by TNCS
Returns
TNC result code
Definition at line 143 of file imv.h.
Referenced by METHOD().
bool(* imv_t::type_supported)(imv_t *this, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
Check if the IMV supports a given message type.
Parameters
msg_vid message vendor ID
msg_subtype message subtype
Returns
TRUE if supported
Definition at line 221 of file imv.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
imv.h