strongSwan: integrity_checker
integrity_checker
utils
Classes
struct integrity_checksum_t
struct integrity_checker_t
Typedefs
typedef struct integrity_checker_t integrity_checker_t
typedef struct integrity_checksum_t integrity_checksum_t
Functions
integrity_checker_t * integrity_checker_create (char *checksum_library)
Detailed Description
Typedef Documentation
typedef struct integrity_checker_t integrity_checker_t
Definition at line 26 of file integrity_checker.h.
typedef struct integrity_checksum_t integrity_checksum_t
Definition at line 27 of file integrity_checker.h.
Function Documentation
integrity_checker_t* integrity_checker_create (char * checksum_library)
Create a integrity_checker instance.
Parameters
checksum_library library containing checksums
See header
Definition at line 255 of file integrity_checker.c.
References DBG1, DBG_LIB, dlopen(), dlsym(), handle, INIT, and RTLD_LAZY.
Referenced by library_init(), and main().
 {
     private_integrity_checker_t *this;
     INIT(this,
         .public = {
             .check_file = _check_file,
             .build_file = _build_file,
             .check_segment = _check_segment,
             .build_segment = _build_segment,
             .check = _check,
             .destroy = _destroy,
         },
     );
     if (checksum_library)
     {
         this->handle = dlopen(checksum_library, RTLD_LAZY);
         if (this->handle)
         {
             int *checksum_count;
             this->checksums = dlsym(this->handle, "checksums");
             checksum_count = dlsym(this->handle, "checksum_count");
             if (this->checksums && checksum_count)
             {
                 this->checksum_count = *checksum_count;
             }
             else
             {
                 DBG1(DBG_LIB, "checksum library '%s' invalid",
                      checksum_library);
             }
         }
         else
         {
             DBG1(DBG_LIB, "loading checksum library '%s' failed",
                  checksum_library);
         }
     }
     return &this->public;
 }