strongSwan: ietf_attr_installed_packages.c File Reference
ietf_attr_installed_packages.c File Reference
#include "ietf_attr_installed_packages.h"
#include <string.h>
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_installed_packages_t
struct package_entry_t
Typedefs
typedef struct
private_ietf_attr_installed_packages_t private_ietf_attr_installed_packages_t
typedef struct package_entry_t package_entry_t
Functions
static void free_package_entry (package_entry_t *entry)
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_installed_packages_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_installed_packages_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_installed_packages_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_installed_packages_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_installed_packages_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_installed_packages_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_installed_packages_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_installed_packages_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_installed_packages_t *this)
METHOD (ietf_attr_installed_packages_t, add, void, private_ietf_attr_installed_packages_t *this, chunk_t name, chunk_t version)
static bool package_filter (void *null, package_entry_t **entry, chunk_t *name, void *i2, chunk_t *version)
METHOD (ietf_attr_installed_packages_t, create_enumerator, enumerator_t *, private_ietf_attr_installed_packages_t *this)
METHOD (ietf_attr_installed_packages_t, get_count, uint16_t, private_ietf_attr_installed_packages_t *this)
METHOD (ietf_attr_installed_packages_t, clear_packages, void, private_ietf_attr_installed_packages_t *this)
pa_tnc_attr_t * ietf_attr_installed_packages_create (void)
pa_tnc_attr_t * ietf_attr_installed_packages_create_from_data (size_t length, chunk_t data)
Typedef Documentation
typedef struct package_entry_t package_entry_t
Definition at line 28 of file ietf_attr_installed_packages.c.
typedef struct private_ietf_attr_installed_packages_t private_ietf_attr_installed_packages_t
Definition at line 27 of file ietf_attr_installed_packages.c.
Function Documentation
static void free_package_entry (package_entry_t * entry) static
Free a package entry
Definition at line 111 of file ietf_attr_installed_packages.c.
References free(), package_entry_t::name, chunk_t::ptr, and package_entry_t::version.
Referenced by METHOD().
 {
     free(entry->name.ptr);
     free(entry->version.ptr);
     free(entry);
 }
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_installed_packages_t * this)
Definition at line 118 of file ietf_attr_installed_packages.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_installed_packages_t * this)
Definition at line 124 of file ietf_attr_installed_packages.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_installed_packages_t * this)
Definition at line 130 of file ietf_attr_installed_packages.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_installed_packages_t * this, bool noskip)
Definition at line 136 of file ietf_attr_installed_packages.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_installed_packages_t * this)
Definition at line 142 of file ietf_attr_installed_packages.c.
References bio_writer_create(), enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::extract_buf, IETF_INSTALLED_PACKAGES_MIN_SIZE, length, package_entry_t::name, segment, value, package_entry_t::version, bio_writer_t::write_data8, and bio_writer_t::write_uint16.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     package_entry_t *entry;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(IETF_INSTALLED_PACKAGES_MIN_SIZE);
     writer->write_uint16(writer, 0x0000);
     writer->write_uint16(writer, this->packages->get_count(this->packages));
     enumerator = this->packages->create_enumerator(this->packages);
     while (enumerator->enumerate(enumerator, &entry))
     {
         writer->write_data8(writer, entry->name);
         writer->write_data8(writer, entry->version);
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->segment = this->value;
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_installed_packages_t * this, u_int32_t * offset)
Definition at line 171 of file ietf_attr_installed_packages.c.
References bio_reader_create(), chunk_clone, count, DBG1, DBG_TNC, bio_reader_t::destroy, end, FAILED, ietf_attr_names, IETF_INSTALLED_PACKAGES_MIN_SIZE, chunk_t::len, length, malloc_thing, name, package_entry_t::name, NEED_MORE, offset, bio_reader_t::peek, PEN_IETF, pen_names, chunk_t::ptr, bio_reader_t::read_data8, bio_reader_t::read_uint16, bio_reader_t::remaining, reserved, status, SUCCESS, type, value, package_entry_t::version, and version.
 {
     bio_reader_t *reader;
     package_entry_t *entry;
     status_t status = NEED_MORE;
     chunk_t name, version;
     u_int16_t reserved;
     u_char *pos;
     if (this->offset == 0)
     {
         if (this->length < IETF_INSTALLED_PACKAGES_MIN_SIZE)
         {
             DBG1(DBG_TNC, "insufficient data for %N/%N", pen_names, PEN_IETF,
                            ietf_attr_names, this->type.type);
             *offset = this->offset;
             return FAILED;
         }
         if (this->value.len < IETF_INSTALLED_PACKAGES_MIN_SIZE)
         {
             return NEED_MORE;
         }
         reader = bio_reader_create(this->value);
         reader->read_uint16(reader, &reserved);
         reader->read_uint16(reader, &this->count);
         this->offset = IETF_INSTALLED_PACKAGES_MIN_SIZE;
         this->value = reader->peek(reader);
         reader->destroy(reader);
     }
     reader = bio_reader_create(this->value);
     while (this->count)
     {
         if (!reader->read_data8(reader, &name) ||
             !reader->read_data8(reader, &version))
         {
             goto end;
         }
         pos = memchr(name.ptr, '\0', name.len);
         if (pos)
         {
             DBG1(DBG_TNC, "nul termination in IETF installed package name");
             *offset = this->offset + 1 + (pos - name.ptr);
             status = FAILED;
             goto end;
         }
         pos = memchr(version.ptr, '\0', version.len);
         if (pos)
         {
             DBG1(DBG_TNC, "nul termination in IETF installed package version");
             *offset = this->offset + 1 + name.len + 1 + (pos - version.ptr);
             status = FAILED;
             goto end;
         }
         this->offset += this->value.len - reader->remaining(reader);
         this->value = reader->peek(reader);
         entry = malloc_thing(package_entry_t);
         entry->name = chunk_clone(name);
         entry->version = chunk_clone(version);
         this->packages->insert_last(this->packages, entry);
         /* at least one tag ID was processed */
         status = SUCCESS;
         this->count--;
     }
     if (this->length != this->offset)
     {
         DBG1(DBG_TNC, "inconsistent length for %N/%N", pen_names, PEN_IETF,
                        ietf_attr_names, this->type.type);
         *offset = this->offset;
         status = FAILED;
     }
 end:
     reader->destroy(reader);
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_installed_packages_t * this, chunk_t segment)
Definition at line 253 of file ietf_attr_installed_packages.c.
References chunk_cat, chunk_free(), and value.
 {
     this->value = chunk_cat("cc", this->value, segment);
     chunk_free(&this->segment);
     this->segment = this->value;
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_installed_packages_t * this)
Definition at line 261 of file ietf_attr_installed_packages.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_installed_packages_t * this)
Definition at line 268 of file ietf_attr_installed_packages.c.
References free(), free_package_entry(), chunk_t::ptr, ref_put(), and segment.
 {
     if (ref_put(&this->ref))
     {
         this->packages->destroy_function(this->packages, (void*)free_package_entry);
         free(this->segment.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_installed_packages_t , add , void , private_ietf_attr_installed_packages_t * this, chunk_t name, chunk_t version)
Definition at line 279 of file ietf_attr_installed_packages.c.
References chunk_clone, chunk_t::len, malloc_thing, min, package_entry_t::name, and package_entry_t::version.
 {
     package_entry_t *entry;
     /* restrict package name and package version number fields to 255 octets */
     name.len = min(255, name.len);
     version.len = min(255, version.len);
     entry = malloc_thing(package_entry_t);
     entry->name = chunk_clone(name);
     entry->version = chunk_clone(version);
     this->packages->insert_last(this->packages, entry);
 }
METHOD (ietf_attr_installed_packages_t , create_enumerator , enumerator_t * , private_ietf_attr_installed_packages_t * this)
Definition at line 305 of file ietf_attr_installed_packages.c.
References enumerator_create_filter(), and package_filter().
 {
     return enumerator_create_filter(
                         this->packages->create_enumerator(this->packages),
                         (void*)package_filter, NULL, NULL);
 }
METHOD (ietf_attr_installed_packages_t , get_count , uint16_t , private_ietf_attr_installed_packages_t * this)
Definition at line 313 of file ietf_attr_installed_packages.c.
References count.
 {
     return this->count;
 }
METHOD (ietf_attr_installed_packages_t , clear_packages , void , private_ietf_attr_installed_packages_t * this)
Definition at line 319 of file ietf_attr_installed_packages.c.
References free_package_entry(), and SUCCESS.
 {
     package_entry_t *entry;
     while (this->packages->remove_first(this->packages,(void**)&entry) == SUCCESS)
     {
         free_package_entry(entry);
     }
 }
static bool package_filter (void * null, package_entry_t ** entry, chunk_t * name, void * i2, chunk_t * version) static
Enumerate package filter entries
Definition at line 297 of file ietf_attr_installed_packages.c.
References TRUE.
Referenced by METHOD().
 {
     *name = (*entry)->name;
     *version = (*entry)->version;
     return TRUE;
 }