strongSwan: seg_contract_manager_t Struct Reference
seg_contract_manager_t Struct Reference
seg_contract_manager
#include "seg_contract_manager.h"
Public Attributes
void(* add_contract)(seg_contract_manager_t *this, seg_contract_t *contract)
seg_contract_t *(* get_contract)(seg_contract_manager_t *this, pen_type_t msg_type, bool is_issuer, TNC_UInt32 id)
void(* destroy)(seg_contract_manager_t *this)
Detailed Description
Interface for a PA-TNC attribute segmentation contract manager
Definition at line 32 of file seg_contract_manager.h.
Member Data Documentation
void(* seg_contract_manager_t::add_contract)(seg_contract_manager_t *this, seg_contract_t *contract)
Add segmentation contract
Parameters
contract Segmentation contract to be added
Definition at line 39 of file seg_contract_manager.h.
Referenced by METHOD(), START_TEST(), and TNC_IMC_BeginHandshake().
void(* seg_contract_manager_t::destroy)(seg_contract_manager_t *this)
Destroys a seg_contract_manager_t object.
Definition at line 55 of file seg_contract_manager.h.
Referenced by START_TEST().
seg_contract_t*(* seg_contract_manager_t::get_contract)(seg_contract_manager_t *this, pen_type_t msg_type, bool is_issuer, TNC_UInt32 id)
Get segmentation contract
Parameters
msg_type PA-TNC message type governed by contract
is_issuer If TRUE get only issuer contracts
id Match either issuer or responder ID
Definition at line 48 of file seg_contract_manager.h.
Referenced by METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
seg_contract_manager.h