strongSwan: eap_peap_avp.c File Reference
eap_peap_avp.c File Reference
#include "eap_peap_avp.h"
#include <eap/eap.h>
#include <utils/debug.h>
Classes
struct private_eap_peap_avp_t
Typedefs
typedef struct
private_eap_peap_avp_t private_eap_peap_avp_t
Functions
METHOD (eap_peap_avp_t, build, void, private_eap_peap_avp_t *this, bio_writer_t *writer, chunk_t data)
METHOD (eap_peap_avp_t, process, status_t, private_eap_peap_avp_t *this, bio_reader_t *reader, chunk_t *data, u_int8_t identifier)
METHOD (eap_peap_avp_t, destroy, void, private_eap_peap_avp_t *this)
eap_peap_avp_t * eap_peap_avp_create (bool is_server)
Variables
static const chunk_t MS_AVP_Success
static const chunk_t MS_AVP_Failure
Typedef Documentation
typedef struct private_eap_peap_avp_t private_eap_peap_avp_t
Definition at line 29 of file eap_peap_avp.c.
Function Documentation
METHOD (eap_peap_avp_t , build , void , private_eap_peap_avp_t * this, bio_writer_t * writer, chunk_t data)
Definition at line 47 of file eap_peap_avp.c.
References chunk_skip(), code, EAP_FAILURE, EAP_MSTLV, eap_packet_t, EAP_REQUEST, EAP_RESPONSE, EAP_SUCCESS, if(), chunk_t::ptr, bio_writer_t::write_data, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
 {
     u_int8_t code;
     eap_packet_t *pkt;
     chunk_t avp_data;
     pkt = (eap_packet_t*)data.ptr;
     if (pkt->code == EAP_SUCCESS || pkt->code == EAP_FAILURE)
     {
         code = (this->is_server) ? EAP_REQUEST : EAP_RESPONSE;
         writer->write_uint8(writer, code);
         writer->write_uint8(writer, pkt->identifier);
         writer->write_uint16(writer, 11);
         writer->write_uint8(writer, EAP_MSTLV);
         avp_data = (pkt->code == EAP_SUCCESS) ? MS_AVP_Success : MS_AVP_Failure;
     }
     else
     {
         avp_data = chunk_skip(data, 4);
     }
     writer->write_data(writer, avp_data);
 }
METHOD (eap_peap_avp_t , process , status_t , private_eap_peap_avp_t * this, bio_reader_t * reader, chunk_t * data, u_int8_t identifier)
Definition at line 72 of file eap_peap_avp.c.
References chunk_alloc, chunk_clone, code, DBG1, DBG2, DBG_IKE, EAP_FAILURE, EAP_IDENTITY, EAP_MSTLV, eap_packet_t, EAP_REQUEST, EAP_RESPONSE, EAP_SUCCESS, FAILED, htoun16(), if(), chunk_t::len, len, memcpy, memeq(), chunk_t::ptr, bio_reader_t::read_data, bio_reader_t::remaining, SUCCESS, and untoh16().
 {
     u_int8_t code;
     u_int16_t len;
     eap_packet_t *pkt;
     chunk_t avp_data;
     code = (this->is_server) ? EAP_RESPONSE : EAP_REQUEST;
     len = reader->remaining(reader);
     if (!reader->read_data(reader, len, &avp_data))
     {
         return FAILED;
     }
     pkt = (eap_packet_t*)avp_data.ptr;
     if (len > 4 && pkt->code == code && untoh16(&pkt->length) == len)
     {
         if (len == 5 && pkt->type == EAP_IDENTITY)
         {
             DBG2(DBG_IKE, "uncompressed EAP Identity request");
             *data = chunk_clone(avp_data);
             return SUCCESS;
         }
         else if (len == 11 && pkt->type == EAP_MSTLV)
         {
             if (memeq(&pkt->data, MS_AVP_Success.ptr, MS_AVP_Success.len))
             {
                 DBG2(DBG_IKE, "MS Success Result AVP");
                 code = EAP_SUCCESS;
             }
             else if (memeq(&pkt->data, MS_AVP_Failure.ptr, MS_AVP_Failure.len))
             {
                 DBG2(DBG_IKE, "MS Failure Result AVP");
                 code = EAP_FAILURE;
             }
             else
             {
                 DBG1(DBG_IKE, "unknown MS AVP message");
                 return FAILED;
             }
             identifier = pkt->identifier;
             len = 0;
         }
     }
     *data = chunk_alloc(4 + len);
     pkt = (eap_packet_t*)data->ptr;
     pkt->code = code;
     pkt->identifier = identifier;
     htoun16(&pkt->length, data->len);
     memcpy(data->ptr + 4, avp_data.ptr, len);
     return SUCCESS;
 }
METHOD (eap_peap_avp_t , destroy , void , private_eap_peap_avp_t * this)
Definition at line 129 of file eap_peap_avp.c.
References free().
 {
     free(this);
 }
Variable Documentation
const chunk_t MS_AVP_Failure static
Initial value:
= chunk_from_chars(
                                            0x80, 0x03, 0x00, 0x02, 0x00, 0x02)
Definition at line 26 of file eap_peap_avp.c.
const chunk_t MS_AVP_Success static
Initial value:
= chunk_from_chars(
                                            0x80, 0x03, 0x00, 0x02, 0x00, 0x01)
Microsoft Success and Failure Result AVPs
Definition at line 24 of file eap_peap_avp.c.