strongSwan: imv_test_state.c File Reference
imv_test_state.c File Reference
#include "imv_test_state.h"
#include "imv/imv_lang_string.h"
#include "imv/imv_reason_string.h"
#include <tncif_policy.h>
#include <utils/lexparser.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_imv_test_state_t
struct imc_entry_t
Typedefs
typedef struct
private_imv_test_state_t private_imv_test_state_t
typedef struct imc_entry_t imc_entry_t
Functions
METHOD (imv_state_t, get_connection_id, TNC_ConnectionID, private_imv_test_state_t *this)
METHOD (imv_state_t, has_long, bool, private_imv_test_state_t *this)
METHOD (imv_state_t, has_excl, bool, private_imv_test_state_t *this)
METHOD (imv_state_t, set_flags, void, private_imv_test_state_t *this, bool has_long, bool has_excl)
METHOD (imv_state_t, set_max_msg_len, void, private_imv_test_state_t *this, uint32_t max_msg_len)
METHOD (imv_state_t, get_max_msg_len, uint32_t, private_imv_test_state_t *this)
METHOD (imv_state_t, set_session, void, private_imv_test_state_t *this, imv_session_t *session)
METHOD (imv_state_t, get_session, imv_session_t *, private_imv_test_state_t *this)
METHOD (imv_state_t, get_contracts, seg_contract_manager_t *, private_imv_test_state_t *this)
METHOD (imv_state_t, change_state, void, private_imv_test_state_t *this, TNC_ConnectionState new_state)
METHOD (imv_state_t, get_recommendation, void, private_imv_test_state_t *this, TNC_IMV_Action_Recommendation *rec, TNC_IMV_Evaluation_Result *eval)
METHOD (imv_state_t, set_recommendation, void, private_imv_test_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, update_recommendation, void, private_imv_test_state_t *this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
METHOD (imv_state_t, get_reason_string, bool, private_imv_test_state_t *this, enumerator_t *language_enumerator, chunk_t *reason_string, char **reason_language)
METHOD (imv_state_t, get_remediation_instructions, bool, private_imv_test_state_t *this, enumerator_t *language_enumerator, chunk_t *string, char **lang_code, char **uri)
METHOD (imv_state_t, destroy, void, private_imv_test_state_t *this)
METHOD (imv_test_state_t, add_imc, void, private_imv_test_state_t *this, TNC_UInt32 imc_id, int rounds)
METHOD (imv_test_state_t, set_rounds, void, private_imv_test_state_t *this, int rounds)
METHOD (imv_test_state_t, another_round, bool, private_imv_test_state_t *this, TNC_UInt32 imc_id)
imv_state_t * imv_test_state_create (TNC_ConnectionID connection_id)
Variables
static char * languages [] = { "en", "de", "fr", "pl" }
static imv_lang_string_t reasons []
Typedef Documentation
typedef struct imc_entry_t imc_entry_t
Definition at line 95 of file imv_test_state.c.
typedef struct private_imv_test_state_t private_imv_test_state_t
Definition at line 26 of file imv_test_state.c.
Function Documentation
METHOD (imv_state_t , get_connection_id , TNC_ConnectionID , private_imv_test_state_t * this)
Definition at line 121 of file imv_test_state.c.
 {
     return this->connection_id;
 }
METHOD (imv_state_t , has_long , bool , private_imv_test_state_t * this)
Definition at line 127 of file imv_test_state.c.
 {
     return this->has_long;
 }
METHOD (imv_state_t , has_excl , bool , private_imv_test_state_t * this)
Definition at line 133 of file imv_test_state.c.
 {
     return this->has_excl;
 }
METHOD (imv_state_t , set_flags , void , private_imv_test_state_t * this, bool has_long, bool has_excl)
Definition at line 139 of file imv_test_state.c.
 {
     this->has_long = has_long;
     this->has_excl = has_excl;
 }
METHOD (imv_state_t , set_max_msg_len , void , private_imv_test_state_t * this, uint32_t max_msg_len)
Definition at line 146 of file imv_test_state.c.
 {
     this->max_msg_len = max_msg_len;
 }
METHOD (imv_state_t , get_max_msg_len , uint32_t , private_imv_test_state_t * this)
Definition at line 152 of file imv_test_state.c.
 {
     return this->max_msg_len;
 }
METHOD (imv_state_t , set_session , void , private_imv_test_state_t * this, imv_session_t * session)
Definition at line 158 of file imv_test_state.c.
 {
     this->session = session;
 }
METHOD (imv_state_t , get_session , imv_session_t * , private_imv_test_state_t * this)
Definition at line 164 of file imv_test_state.c.
 {
     return this->session;
 }
METHOD (imv_state_t , get_contracts , seg_contract_manager_t * , private_imv_test_state_t * this)
Definition at line 170 of file imv_test_state.c.
 {
     return this->contracts;
 }
METHOD (imv_state_t , change_state , void , private_imv_test_state_t * this, TNC_ConnectionState new_state)
Definition at line 176 of file imv_test_state.c.
 {
     this->state = new_state;
 }
METHOD (imv_state_t , get_recommendation , void , private_imv_test_state_t * this, TNC_IMV_Action_Recommendation * rec, TNC_IMV_Evaluation_Result * eval)
Definition at line 182 of file imv_test_state.c.
 {
     *rec = this->rec;
     *eval = this->eval;
 }
METHOD (imv_state_t , set_recommendation , void , private_imv_test_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 190 of file imv_test_state.c.
 {
     this->rec = rec;
     this->eval = eval;
 }
METHOD (imv_state_t , update_recommendation , void , private_imv_test_state_t * this, TNC_IMV_Action_Recommendation rec, TNC_IMV_Evaluation_Result eval)
Definition at line 198 of file imv_test_state.c.
References tncif_policy_update_evaluation(), and tncif_policy_update_recommendation().
 {
     this->rec  = tncif_policy_update_recommendation(this->rec, rec);
     this->eval = tncif_policy_update_evaluation(this->eval, eval);
 }
METHOD (imv_state_t , get_reason_string , bool , private_imv_test_state_t * this, enumerator_t * language_enumerator, chunk_t * reason_string, char ** reason_language)
Definition at line 206 of file imv_test_state.c.
References countof, DESTROY_IF, imv_lang_string_select_lang(), imv_reason_string_create(), languages, and TRUE.
 {
     *reason_language = imv_lang_string_select_lang(language_enumerator,
                                               languages, countof(languages));
     /* Instantiate a TNC Reason String object */
     DESTROY_IF(this->reason_string);
     this->reason_string = imv_reason_string_create(*reason_language, "\n");
     this->reason_string->add_reason(this->reason_string, reasons);
     *reason_string = this->reason_string->get_encoding(this->reason_string);
     return TRUE;
 }
METHOD (imv_state_t , get_remediation_instructions , bool , private_imv_test_state_t * this, enumerator_t * language_enumerator, chunk_t * string, char ** lang_code, char ** uri)
Definition at line 222 of file imv_test_state.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (imv_state_t , destroy , void , private_imv_test_state_t * this)
Definition at line 229 of file imv_test_state.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->session);
     DESTROY_IF(this->reason_string);
     this->contracts->destroy(this->contracts);
     this->imcs->destroy_function(this->imcs, free);
     free(this);
 }
METHOD (imv_test_state_t , add_imc , void , private_imv_test_state_t * this, TNC_UInt32 imc_id, int rounds)
Definition at line 239 of file imv_test_state.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, imc_entry_t::imc_id, malloc_thing, imc_entry_t::rounds, and TRUE.
 {
     enumerator_t *enumerator;
     imc_entry_t *imc_entry;
     bool found = FALSE;
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc_entry))
     {
         if (imc_entry->imc_id == imc_id)
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         imc_entry = malloc_thing(imc_entry_t);
         imc_entry->imc_id = imc_id;
         imc_entry->rounds = rounds;
         this->imcs->insert_last(this->imcs, imc_entry);
     }
 }
METHOD (imv_test_state_t , set_rounds , void , private_imv_test_state_t * this, int rounds)
Definition at line 266 of file imv_test_state.c.
References enumerator_t::destroy, enumerator_t::enumerate, and imc_entry_t::rounds.
 {
     enumerator_t *enumerator;
     imc_entry_t *imc_entry;
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc_entry))
     {
         imc_entry->rounds = rounds;
     }
     enumerator->destroy(enumerator);
 }
METHOD (imv_test_state_t , another_round , bool , private_imv_test_state_t * this, TNC_UInt32 imc_id)
Definition at line 280 of file imv_test_state.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, imc_entry_t::imc_id, imc_entry_t::rounds, and TRUE.
 {
     enumerator_t *enumerator;
     imc_entry_t *imc_entry;
     bool not_finished = FALSE;
     enumerator = this->imcs->create_enumerator(this->imcs);
     while (enumerator->enumerate(enumerator, &imc_entry))
     {
         if (imc_entry->rounds > 0)
         {
             not_finished = TRUE;
         }
         if (imc_entry->imc_id == imc_id)
         {
             imc_entry->rounds--;
         }
     }
     enumerator->destroy(enumerator);
     return not_finished;
 }
Variable Documentation
char* languages[] = { "en", "de", "fr", "pl" } static
Supported languages
Definition at line 108 of file imv_test_state.c.
Referenced by METHOD().
imv_lang_string_t reasons[] static
Initial value:
= {
    { "en", "IMC Test was not configured with \"command = allow\"" },
    { "de", "IMC Test wurde nicht mit \"command = allow\" konfiguriert" },
    { "fr", "IMC Test n'etait pas configur avec \"command = allow\"" },
    { "pl", "IMC Test nie zostao skonfigurowany z \"command = allow\"" },
    { NULL, NULL }
}
Table of reason strings
Definition at line 113 of file imv_test_state.c.