strongSwan: enumerator
enumerator
collections
Classes
struct enumerator_t
Typedefs
typedef struct enumerator_t enumerator_t
Functions
enumerator_t * enumerator_create_empty ()
enumerator_t * enumerator_create_single (void *item, void(*cleanup)(void *item))
enumerator_t * enumerator_create_directory (const char *path)
enumerator_t * enumerator_create_glob (const char *pattern)
enumerator_t * enumerator_create_token (const char *string, const char *sep, const char *trim)
enumerator_t * enumerator_create_nested (enumerator_t *outer, enumerator_t *(*inner_constructor)(void *outer, void *data), void *data, void(*destroy_data)(void *data))
enumerator_t * enumerator_create_filter (enumerator_t *unfiltered, bool(*filter)(void *data,...), void *data, void(*destructor)(void *data))
enumerator_t * enumerator_create_cleaner (enumerator_t *wrapped, void(*cleanup)(void *data), void *data)
Detailed Description
Typedef Documentation
typedef struct enumerator_t enumerator_t
Definition at line 25 of file enumerator.h.
Function Documentation
enumerator_t* enumerator_create_cleaner (enumerator_t * wrapped, void(*)(void *data) cleanup, void * data)
Create an enumerator wrapper which does a cleanup on destroy.
Parameters
wrapped wrapped enumerator
cleanup cleanup function called on destroy
data user data to supply to cleanup
Returns
the enumerator with cleanup
see header
Definition at line 584 of file enumerator.c.
References cleanup, data, destroy_cleaner(), enumerate_cleaner(), and malloc_thing.
Referenced by create_usercert_enumerator(), METHOD(), and START_TEST().
 {
     cleaner_enumerator_t *this = malloc_thing(cleaner_enumerator_t);
     this->public.enumerate = (void*)enumerate_cleaner;
     this->public.destroy = (void*)destroy_cleaner;
     this->wrapped = wrapped;
     this->cleanup = cleanup;
     this->data = data;
     return &this->public;
 }
enumerator_t* enumerator_create_directory (const char * path)
Create an enumerator over files/subdirectories in a directory.
This enumerator_t.enumerate() function returns a (to the directory) relative filename (as a char*), an absolute filename (as a char*) and a file status (to a struct stat), which all may be NULL. "." and ".." entries are skipped.
Example:
char *rel, *abs;
struct stat st;
enumerator_t *e;
e = enumerator_create_directory("/tmp");
if (e)
{
   while (e->enumerate(e, &rel, &abs, &st))
   {
       if (S_ISDIR(st.st_mode) && *rel != '.')
       {
           printf("%s\n", abs);
       }
   }
   e->destroy(e);
}
Parameters
path path of the directory
Returns
the directory enumerator, NULL on failure
See header
Definition at line 128 of file enumerator.c.
References DBG1, DBG_LIB, destroy_dir_enum(), dir, enumerate_dir_enum(), free(), len, malloc_thing, snprintf, and strerror.
Referenced by collect_tags(), disable_all(), load_ca_certs(), load_ca_dir(), load_cacerts(), load_certdir(), load_certs(), load_containers(), load_keys(), METHOD(), and pts_file_meas_create_from_path().
 {
     int len;
     dir_enum_t *this = malloc_thing(dir_enum_t);
     this->public.enumerate = (void*)enumerate_dir_enum;
     this->public.destroy = (void*)destroy_dir_enum;
     if (*path == '\0')
     {
         path = "./";
     }
     len = snprintf(this->full, sizeof(this->full)-1, "%s", path);
     if (len < 0 || len >= sizeof(this->full)-1)
     {
         DBG1(DBG_LIB, "path string '%s' too long", path);
         free(this);
         return NULL;
     }
     /* append a '/' if not already done */
     if (this->full[len-1] != '/')
     {
         this->full[len++] = '/';
         this->full[len] = '\0';
     }
     this->full_end = &this->full[len];
     this->dir = opendir(path);
     if (this->dir == NULL)
     {
         DBG1(DBG_LIB, "opening directory '%s' failed: %s", path, strerror(errno));
         free(this);
         return NULL;
     }
     return &this->public;
 }
enumerator_t* enumerator_create_empty ()
Create an enumerator which enumerates over nothing
Returns
an enumerator over no values
See header
Definition at line 45 of file enumerator.c.
References destroy(), enumerate(), enumerate_empty(), free(), and malloc_thing.
Referenced by array_create_enumerator(), create_empty(), create_rdn_enumerator(), ha_attribute_create(), METHOD(), parse(), pkcs11_creds_create(), pkcs12_create(), sign_crl(), and updown_handler_create().
 {
     enumerator_t *this = malloc_thing(enumerator_t);
     this->enumerate = enumerate_empty;
     this->destroy = (void*)free;
     return this;
 }
enumerator_t* enumerator_create_filter (enumerator_t * unfiltered, bool(*)(void *data,...) filter, void * data, void(*)(void *data) destructor)
Creates an enumerator which filters output of another enumerator.
The filter function receives the user supplied "data" followed by a unfiltered enumeration item, followed by an output pointer where to write the filtered data. Then the next input/output pair follows. It returns TRUE to deliver the values to the caller of enumerate(), FALSE to filter this enumeration.
The variable argument list of enumeration values is limit to 5.
Parameters
unfiltered unfiltered enumerator to wrap, gets destroyed
filter filter function
data user data to supply to filter
destructor destructor function to clean up data after use
Returns
the filtered enumerator
see header
Definition at line 536 of file enumerator.c.
References data, destroy_filter(), enumerate_filter(), filter(), and malloc_thing.
Referenced by CALLBACK(), create_enumerator(), create_iface_enumerator(), create_inner_local(), create_inner_remote(), create_trusted_cert_enumerator(), kv_enumerator(), METHOD(), plugin_filter(), section_enumerator(), sign_crl(), and START_TEST().
 {
     filter_enumerator_t *this = malloc_thing(filter_enumerator_t);
     this->public.enumerate = (void*)enumerate_filter;
     this->public.destroy = (void*)destroy_filter;
     this->unfiltered = unfiltered;
     this->filter = filter;
     this->data = data;
     this->destructor = destructor;
     return &this->public;
 }
enumerator_t* enumerator_create_glob (const char * pattern)
Create an enumerator over files/directories matching a file pattern.
This enumerator_t.enumerate() function returns the filename (as a char*), and a file status (to a struct stat), which both may be NULL.
Example:
char *file;
struct stat st;
enumerator_t *e;
e = enumerator_create_glob("/etc/ipsec.*.conf");
if (e)
{
   while (e->enumerate(e, &file, &st))
   {
       if (S_ISREG(st.st_mode))
       {
           printf("%s\n", file);
       }
   }
   e->destroy(e);
}
Parameters
pattern file pattern to match
Returns
the enumerator, NULL if not supported
Definition at line 252 of file enumerator.c.
Referenced by METHOD().
 {
     return NULL;
 }
enumerator_t* enumerator_create_nested (enumerator_t * outer, enumerator_t *(*)(void *outer, void *data) inner_constructor, void * data, void(*)(void *data) destroy_data)
Creates an enumerator which enumerates over enumerated enumerators :-).
The variable argument list of enumeration values is limit to 5.
Parameters
outer outer enumerator
inner_constructor constructor to inner enumerator
data data to pass to each inner_constructor call
destroy_data destructor to pass to data
Returns
the nested enumerator
enumerator_t* enumerator_create_single (void * item, void(*)(void *item) cleanup)
Create an enumerator which enumerates over a single item
Parameters
item item to enumerate
cleanup cleanup function called on destroy with the item
Returns
an enumerator over a single value
see header
Definition at line 637 of file enumerator.c.
References cleanup, destroy_single(), enumerate_single(), FALSE, and malloc_thing.
Referenced by create_inner_cdp_hashandurl(), create_usercert_enumerator(), METHOD(), and START_TEST().
 {
     single_enumerator_t *this = malloc_thing(single_enumerator_t);
     this->public.enumerate = (void*)enumerate_single;
     this->public.destroy = (void*)destroy_single;
     this->item = item;
     this->cleanup = cleanup;
     this->done = FALSE;
     return &this->public;
 }
enumerator_t* enumerator_create_token (const char * string, const char * sep, const char * trim)
Create an enumerator over tokens of a string.
Tokens are separated by one of the characters in sep and trimmed by the characters in trim.
Parameters
string string to parse
sep separator characters
trim characters to trim from tokens
Returns
enumerator over char* tokens
See header
Definition at line 396 of file enumerator.c.
References enumerator_t::destroy, destroy_token_enum(), enumerator_t::enumerate, enumerate_token_enum(), malloc_thing, token_enum_t::pos, token_enum_t::public, sep, token_enum_t::sep, strdup, token_enum_t::string, trim, and token_enum_t::trim.
Referenced by add_file_list_key(), add_list_key(), add_ts(), add_unity_split_attribute(), apply_filter(), asn1_oid_from_string(), build_auth_cfg(), build_peer_cfg(), build_plugin_checksums(), CALLBACK(), eap_vendor_type_from_string(), filter_cipher_config_suites(), filter_key_exchange_config_suites(), filter_mac_config_suites(), filter_specific_config_suites(), generate_auth_cfg(), get_active(), get_next_test_vector(), handle_preferred_eap_types(), is_local(), is_reinject_config(), join_groups(), kernel_interface_create(), kernel_netlink_net_create(), load_addrs(), load_child_config(), load_entries(), load_from_stream(), load_ike_config(), METHOD(), modular_pluginlist(), parse_addresses(), parse_pubkey_constraints(), parse_ranges(), parse_selector(), plugin_loader_add_plugindirs(), process(), process_peer_failure(), process_peer_success(), proposal_create_from_string(), read_triplets(), start_cron(), and START_TEST().
 {
     token_enum_t *enumerator = malloc_thing(token_enum_t);
     enumerator->public.enumerate = (void*)enumerate_token_enum;
     enumerator->public.destroy = (void*)destroy_token_enum;
     enumerator->string = strdup(string);
     enumerator->pos = enumerator->string;
     enumerator->sep = sep;
     enumerator->trim = trim;
     return &enumerator->public;
 }