strongSwan: imc_swid.c File Reference
imc_swid.c File Reference
#include "imc_swid_state.h"
#include <imc/imc_agent.h>
#include <imc/imc_msg.h>
#include "tcg/seg/tcg_seg_attr_max_size.h"
#include "tcg/seg/tcg_seg_attr_seg_env.h"
#include "tcg/swid/tcg_swid_attr_req.h"
#include "tcg/swid/tcg_swid_attr_tag_inv.h"
#include "tcg/swid/tcg_swid_attr_tag_id_inv.h"
#include "swid/swid_inventory.h"
#include "swid/swid_error.h"
#include <tncif_pa_subtypes.h>
#include <pen/pen.h>
#include <utils/debug.h>
Macros
#define SWID_GENERATOR "/usr/local/bin/swid_generator"
Functions
TNC_Result TNC_IMC_Initialize (TNC_IMCID imc_id, TNC_Version min_version, TNC_Version max_version, TNC_Version *actual_version)
TNC_Result TNC_IMC_NotifyConnectionChange (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_ConnectionState new_state)
TNC_Result TNC_IMC_BeginHandshake (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
static bool add_swid_inventory (imc_state_t *state, imc_msg_t *msg, uint32_t request_id, bool full_tags, swid_inventory_t *targets)
static TNC_Result receive_message (imc_state_t *state, imc_msg_t *in_msg)
TNC_Result TNC_IMC_ReceiveMessage (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
TNC_Result TNC_IMC_ReceiveMessageLong (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
TNC_Result TNC_IMC_BatchEnding (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
TNC_Result TNC_IMC_Terminate (TNC_IMCID imc_id)
TNC_Result TNC_IMC_ProvideBindFunction (TNC_IMCID imc_id, TNC_TNCC_BindFunctionPointer bind_function)
Variables
static const char imc_name [] = "SWID"
static pen_type_t msg_types []
static imc_agent_t * imc_swid
Macro Definition Documentation
#define SWID_GENERATOR "/usr/local/bin/swid_generator"
Definition at line 33 of file imc_swid.c.
Referenced by add_swid_inventory().
Function Documentation
static bool add_swid_inventory (imc_state_t * state, imc_msg_t * msg, uint32_t request_id, bool full_tags, swid_inventory_t * targets) static
Add one or multiple SWID Inventory attributes to the send queue
Definition at line 161 of file imc_swid.c.
References tcg_swid_attr_tag_inv_t::add, tcg_swid_attr_tag_id_inv_t::add, imc_msg_t::add_attribute, swid_inventory_t::collect, swid_inventory_t::create_enumerator, DBG1, DBG_IMC, enumerator_t::destroy, swid_inventory_t::destroy, enumerator_t::enumerate, FALSE, settings_t::get_bool, swid_inventory_t::get_count, swid_tag_t::get_ref, swid_tag_id_t::get_ref, settings_t::get_str, lib, library_t::ns, library_t::settings, swid_error_create(), SWID_GENERATOR, swid_inventory_create(), tcg_swid_attr_tag_id_inv_create(), tcg_swid_attr_tag_inv_create(), TCG_SWID_ERROR, and TRUE.
Referenced by receive_message().
 {
     pa_tnc_attr_t *attr, *attr_error;
     imc_swid_state_t *swid_state;
     swid_inventory_t *swid_inventory;
     char *swid_directory, *swid_generator;
     uint32_t eid_epoch;
     bool swid_pretty, swid_full;
     enumerator_t *enumerator;
     swid_directory = lib->settings->get_str(lib->settings,
                                 "%s.plugins.imc-swid.swid_directory",
                                  SWID_DIRECTORY, lib->ns);
     swid_generator = lib->settings->get_str(lib->settings,
                                 "%s.plugins.imc-swid.swid_generator",
                                  SWID_GENERATOR, lib->ns);
     swid_pretty = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.imc-swid.swid_pretty",
                                  FALSE, lib->ns);
     swid_full = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.imc-swid.swid_full",
                                  FALSE, lib->ns);
     swid_inventory = swid_inventory_create(full_tags);
     if (!swid_inventory->collect(swid_inventory, swid_directory, swid_generator,
                                  targets, swid_pretty, swid_full))
     {
         swid_inventory->destroy(swid_inventory);
         attr_error = swid_error_create(TCG_SWID_ERROR, request_id,
                                  0, "error in SWID tag collection");
         msg->add_attribute(msg, attr_error);
         return FALSE;
     }
     DBG1(DBG_IMC, "collected %d SWID tag%s%s",
          swid_inventory->get_count(swid_inventory), full_tags ? "" : " ID",
          swid_inventory->get_count(swid_inventory) == 1 ? "" : "s");
     swid_state = (imc_swid_state_t*)state;
     eid_epoch = swid_state->get_eid_epoch(swid_state);
     if (full_tags)
     {
         tcg_swid_attr_tag_inv_t *swid_attr;
         swid_tag_t *tag;
         /* Send a TCG SWID Tag Inventory attribute */
         attr = tcg_swid_attr_tag_inv_create(request_id, eid_epoch, 1);
         swid_attr = (tcg_swid_attr_tag_inv_t*)attr;
         enumerator = swid_inventory->create_enumerator(swid_inventory);
         while (enumerator->enumerate(enumerator, &tag))
         {
             swid_attr->add(swid_attr, tag->get_ref(tag));
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         tcg_swid_attr_tag_id_inv_t *swid_id_attr;
         swid_tag_id_t *tag_id;
         /* Send a TCG SWID Tag ID Inventory attribute */
         attr = tcg_swid_attr_tag_id_inv_create(request_id, eid_epoch, 1);
         swid_id_attr = (tcg_swid_attr_tag_id_inv_t*)attr;
         enumerator = swid_inventory->create_enumerator(swid_inventory);
         while (enumerator->enumerate(enumerator, &tag_id))
         {
             swid_id_attr->add(swid_id_attr, tag_id->get_ref(tag_id));
         }
         enumerator->destroy(enumerator);
     }
     msg->add_attribute(msg, attr);
     swid_inventory->destroy(swid_inventory);
     return TRUE;
 }
static TNC_Result receive_message (imc_state_t * state, imc_msg_t * in_msg) static
Definition at line 242 of file imc_swid.c.
References imc_msg_t::add_attribute, add_swid_inventory(), imc_msg_t::create_attribute_enumerator, enumerator_t::destroy, imc_msg_t::destroy, enumerator_t::enumerate, FALSE, flags, tcg_swid_attr_req_t::get_flags, tcg_swid_attr_req_t::get_request_id, tcg_swid_attr_req_t::get_targets, pa_tnc_attr_t::get_type, imc_msg_create_as_reply(), PEN_TCG, imc_msg_t::receive, result, imc_msg_t::send, swid_error_create(), TCG_SWID_ATTR_REQ_FLAG_C, TCG_SWID_ATTR_REQ_FLAG_R, TCG_SWID_ATTR_REQ_FLAG_S, TCG_SWID_REQUEST, TCG_SWID_SUBSCRIPTION_DENIED, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, TRUE, type, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by TNC_IMC_ReceiveMessage(), and TNC_IMC_ReceiveMessageLong().
 {
     imc_msg_t *out_msg;
     pa_tnc_attr_t *attr;
     enumerator_t *enumerator;
     pen_type_t type;
     TNC_Result result;
     bool fatal_error = FALSE;
     /* generate an outgoing PA-TNC message - we might need it */
     out_msg = imc_msg_create_as_reply(in_msg);
     /* parse received PA-TNC message and handle local and remote errors */
     result = in_msg->receive(in_msg, out_msg, &fatal_error);
     if (result != TNC_RESULT_SUCCESS)
     {
         out_msg->destroy(out_msg);
         return result;
     }
     /* analyze PA-TNC attributes */
     enumerator = in_msg->create_attribute_enumerator(in_msg);
     while (enumerator->enumerate(enumerator, &attr))
     {
         tcg_swid_attr_req_t *attr_req;
         uint8_t flags;
         uint32_t request_id;
         bool full_tags;
         swid_inventory_t *targets;
         type = attr->get_type(attr);
         if (type.vendor_id != PEN_TCG || type.type != TCG_SWID_REQUEST)
         {
             continue;
         }
         attr_req = (tcg_swid_attr_req_t*)attr;
         flags = attr_req->get_flags(attr_req);
         request_id = attr_req->get_request_id(attr_req);
         targets = attr_req->get_targets(attr_req);
         if (flags & (TCG_SWID_ATTR_REQ_FLAG_S | TCG_SWID_ATTR_REQ_FLAG_C))
         {
             attr = swid_error_create(TCG_SWID_SUBSCRIPTION_DENIED, request_id,
                                      0, "no subscription available yet");
             out_msg->add_attribute(out_msg, attr);
             break;
         }
         full_tags = (flags & TCG_SWID_ATTR_REQ_FLAG_R) == 0;
         if (!add_swid_inventory(state, out_msg, request_id, full_tags, targets))
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (fatal_error)
     {
         result = TNC_RESULT_FATAL;
     }
     else
     {
         /* send PA-TNC message with the EXCL flag set */
         result = out_msg->send(out_msg, TRUE);
     }
     out_msg->destroy(out_msg);
     return result;
 }
Variable Documentation
const char imc_name[] = "SWID" static
Definition at line 37 of file imc_swid.c.
Referenced by TNC_IMC_BatchEnding(), TNC_IMC_BeginHandshake(), TNC_IMC_Initialize(), TNC_IMC_NotifyConnectionChange(), TNC_IMC_ProvideBindFunction(), TNC_IMC_ReceiveMessage(), TNC_IMC_ReceiveMessageLong(), and TNC_IMC_Terminate().
imc_agent_t* imc_swid static
Definition at line 43 of file imc_swid.c.
pen_type_t msg_types[] static
Initial value:
= {
    { PEN_TCG, PA_SUBTYPE_TCG_SWID }
}
Definition at line 39 of file imc_swid.c.