strongSwan: utils
utils
utils
Modules
align
atomics
byteorder
memory
object
path
status
strerror
string
time
tty
types
Macros
#define _GNU_SOURCE
#define SS_RC_LIBSTRONGSWAN_INTEGRITY 64
#define SS_RC_DAEMON_INTEGRITY 65
#define SS_RC_INITIALIZATION_FAILED 66
#define SS_RC_FIRST SS_RC_LIBSTRONGSWAN_INTEGRITY
#define SS_RC_LAST SS_RC_INITIALIZATION_FAILED
#define BITS_PER_BYTE 8
#define BUF_LEN 512
#define BUILD_ASSERT(x) (sizeof(char[(x) ? 0 : -1]))
#define BUILD_ASSERT_ARRAY(a) BUILD_ASSERT(!__builtin_types_compatible_p(typeof(a), typeof(&(a)[0])))
#define POS printf("%s, line %d\n", __FILE__, __LINE__)
#define VA_ARGS_NUM(...) _VA_ARGS_NUM(0,##__VA_ARGS__,10,9,8,7,6,5,4,3,2,1,0)
#define _VA_ARGS_NUM(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, NUM,...) NUM
#define VA_ARGS_DISPATCH(func,...) _VA_ARGS_DISPATCH(func, VA_ARGS_NUM(__VA_ARGS__))
#define _VA_ARGS_DISPATCH(func, num) __VA_ARGS_DISPATCH(func, num)
#define __VA_ARGS_DISPATCH(func, num) func ## num
#define malloc_thing(thing) ((thing*)malloc(sizeof(thing)))
#define countof(array)
#define ignore_result(call) { if(call){}; }
Functions
void utils_init ()
void utils_deinit ()
int sigwaitinfo (const sigset_t *set, void *info)
void wait_sigint ()
void closefrom (int lowfd)
void * return_null ()
void nop ()
bool return_true ()
bool return_false ()
Detailed Description
Macro Definition Documentation
#define __VA_ARGS_DISPATCH (func, num) func ## num
Definition at line 137 of file utils.h.
#define _GNU_SOURCE
Definition at line 34 of file utils.h.
#define _VA_ARGS_DISPATCH (func, num) __VA_ARGS_DISPATCH(func, num)
Definition at line 136 of file utils.h.
#define _VA_ARGS_NUM (_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, NUM, ...) NUM
Definition at line 120 of file utils.h.
#define BITS_PER_BYTE 8
Number of bits in a byte
Definition at line 87 of file utils.h.
Referenced by check(), gmp_mpz_to_chunk(), gmp_rsa_private_key_gen(), gmp_rsa_private_key_load(), gmp_rsa_public_key_load(), main(), METHOD(), mpz_clear_sensitive(), ntru_drbg_create(), ntru_private_key_create(), and START_TEST().
#define BUF_LEN 512
Default length for various auxiliary text buffers
Definition at line 92 of file utils.h.
Referenced by asn1_from_time(), create_access_request(), create_capability(), create_delete_filter(), create_identity(), create_ip_address(), do_netstat(), extract_platform_info(), generate_message(), generate_tags(), get_str_attribute(), imv_attestation_process(), load_pin(), log_ike_sa(), main(), METHOD(), print_alg(), print_cfn(), process_packages(), read_swid_tag_ids(), START_TEST(), starter_start_charon(), TNC_IMC_BeginHandshake(), tnccs_msg_create_from_node(), and tnccs_recommendation_msg_create_from_node().
#define BUILD_ASSERT (x) (sizeof(char[(x) ? 0 : -1]))
Build assertion macro for integer expressions, evaluates to 0
Definition at line 97 of file utils.h.
#define BUILD_ASSERT_ARRAY (a) BUILD_ASSERT(!__builtin_types_compatible_p(typeof(a), typeof(&(a)[0])))
Build time check to assert a is an array, evaluates to 0
The address of an array element has a pointer type, which is not compatible to the array type.
Definition at line 105 of file utils.h.
#define countof (array)
Value:
(sizeof(array)/sizeof((array)[0]) \
                        + BUILD_ASSERT_ARRAY(array))
Get the number of elements in an array
Definition at line 147 of file utils.h.
Referenced by __attribute__(), add_policy_internal(), add_product_info(), af_alg_crypter_probe(), af_alg_hasher_probe(), af_alg_prf_probe(), af_alg_signer_probe(), alg2auth(), alg2cipher(), algo_to_mechanism(), asn1_parser_suite_create(), atodn(), attack_chunk(), attack_memeq(), backtrace_create(), bliss_fft_suite_create(), bliss_keys_suite_create(), bliss_param_set_get_by_id(), bliss_param_set_get_by_oid(), bliss_sampler_suite_create(), bliss_sign_suite_create(), build(), build_cipher_suite_list(), CALLBACK(), callout2name(), certnames_suite_create(), chapoly_drv_probe(), check_proposal(), chunk_suite_create(), command_register(), cond2name(), create_ecdsa_key(), create_from_string_with_prefix_type(), create_header(), create_rsa_key(), create_vstr_conf(), crypter_suite_create(), crypto_factory_suite_create(), derive_secret(), determine_credtype(), diffie_hellman_get_params(), diffie_hellman_init(), dlsym_default(), dlsym_next(), eap_type_from_string(), ec_key_new_brainpool(), ecdsa_suite_create(), encode_ecdsa(), encode_rsa(), encr2integ(), enum_suite_create(), enumerator_suite_create(), extract_platform_info(), fetch_http_suite_create(), find_callout(), find_certificates(), find_ecdsa_key(), find_key(), find_key_by_keyid(), find_lib_by_keyid(), find_pubkey_in_certs(), find_rsa_key(), find_suite(), generate_key_pair_ecp(), generate_key_pair_modp(), get_alg_from_ikev1(), get_alg_from_ikev1_auth(), get_alg_from_ikev1_transid(), get_ikev1_auth_from_alg(), get_ikev1_from_alg(), get_ikev1_transid_from_alg(), get_message_rule(), get_reserved_id_bytes(), group_filter(), hasher_suite_create(), hashsig_to_scheme(), host_suite_create(), identification_suite_create(), imcv_seg_suite_create(), imv_attestation_agent_create(), imv_hcd_agent_create(), imv_os_agent_create(), imv_scanner_agent_create(), imv_swid_agent_create(), imv_test_agent_create(), init(), invoke_once(), is_file_list_key(), is_list_key(), keymat_get_keylen_encr(), keymat_get_keylen_integ(), layer2name(), load_action(), load_entries(), load_secret(), lookup_alg(), lookup_algorithm(), main(), message_suite_create(), METHOD(), nm_backend_register(), ntru_param_set_get_by_id(), ntru_param_set_get_by_oid(), ntru_suite_create(), parse_attributes(), parse_pubkey_constraints(), parse_rounds(), parse_uri(), parser_suite_create(), pkcs11_creds_load(), pkcs11_encryption_scheme_to_mech(), pkcs11_signature_scheme_to_mech(), print_global(), print_one(), print_traces(), process(), query_protocols(), receive_message(), register_dh_mapping(), request_suite_create(), rsa_suite_create(), sasl_mechanism_create(), select_signature_schemes(), send_request(), show_attr(), socket_suite_create(), START_TEST(), status_attr(), stream_suite_create(), strerror_s_extended(), test_bad_sigs(), test_good_sig(), test_poker(), test_runner_init(), test_runs(), test_vectors_plugin_create(), threading_suite_create(), timeattack(), tls_cleanup_run(), tls_crypto_get_supported_suites(), tls_run(), TNC_IMC_BeginHandshake(), TNC_IMC_Initialize(), traffic_selector_suite_create(), usage(), utils_suite_create(), vectors_suite_create(), and wserr().
#define ignore_result (call) { if(call){}; }
Ignore result of functions tagged with warn_unused_result attributes
Definition at line 153 of file utils.h.
Referenced by check_pidfile(), concurrency(), detach_exit_run(), detach_run(), find_socket(), invoke_resolvconf(), main(), METHOD(), remove_half_open(), rwlock_run(), starter_klips_cleanup(), starter_klips_init(), starter_netkey_init(), unlink_pidfile(), and write_nameserver().
#define malloc_thing (thing) ((thing*)malloc(sizeof(thing)))
Macro to allocate a sized type.
Definition at line 142 of file utils.h.
Referenced by add_legacy_entry(), allocate_spi(), ca_section_create(), cache_iface(), create_function(), dispatch(), encode(), enumerator_create_cleaner(), enumerator_create_directory(), enumerator_create_empty(), enumerator_create_filter(), enumerator_create_nested(), enumerator_create_single(), enumerator_create_token(), file_metadata(), get_port_list(), METHOD(), parse(), parse_singleResponse(), pts_ima_bios_list_create(), pts_ima_event_list_create(), radius_receive(), read_triplets(), register_dh_mapping(), rng_create(), and tnc_imv_recommendations_create().
#define POS printf("%s, line %d\n", __FILE__, __LINE__)
Debug macro to follow control flow
Definition at line 111 of file utils.h.
#define SS_RC_DAEMON_INTEGRITY 65
Definition at line 78 of file utils.h.
Referenced by main(), and starter_charon_sigchild().
#define SS_RC_FIRST SS_RC_LIBSTRONGSWAN_INTEGRITY
Definition at line 81 of file utils.h.
Referenced by signal_handler().
#define SS_RC_INITIALIZATION_FAILED 66
Definition at line 79 of file utils.h.
Referenced by init(), main(), run(), and starter_charon_sigchild().
#define SS_RC_LAST SS_RC_INITIALIZATION_FAILED
Definition at line 82 of file utils.h.
Referenced by signal_handler().
#define SS_RC_LIBSTRONGSWAN_INTEGRITY 64
strongSwan program return codes
Definition at line 77 of file utils.h.
Referenced by main(), and starter_charon_sigchild().
#define VA_ARGS_DISPATCH (func, ...) _VA_ARGS_DISPATCH(func, VA_ARGS_NUM(__VA_ARGS__))
This macro can be used to dispatch a macro call based on the number of given arguments, for instance:
#define MY_MACRO(...) VA_ARGS_DISPATCH(MY_MACRO, __VA_ARGS__)(__VA_ARGS__)
#define MY_MACRO1(arg) one_arg(arg)
#define MY_MACRO2(arg1,arg2) two_args(arg1,arg2)
MY_MACRO() can now be called with either one or two arguments, which will resolve to one_arg(arg) or two_args(arg1,arg2), respectively.
Definition at line 135 of file utils.h.
#define VA_ARGS_NUM (...) _VA_ARGS_NUM(0,##__VA_ARGS__,10,9,8,7,6,5,4,3,2,1,0)
This macro allows counting the number of arguments passed to a macro. Combined with the VA_ARGS_DISPATCH() macro this can be used to implement macro overloading based on the number of arguments. 0 to 10 arguments are currently supported.
Definition at line 119 of file utils.h.
Function Documentation
void closefrom (int low_fd)
Close open file descriptors greater than or equal to lowfd.
Parameters
lowfd start closing file descriptors from here
Described in header.
Definition at line 158 of file utils.c.
References close, dir, FD_DIR, len, and offset.
Referenced by process_start(), and starter_start_charon().
 {
     int max_fd, dir_fd, fd;
     /* try to close only open file descriptors on Linux... */
 #if defined(__linux__) && defined(HAVE_SYS_SYSCALL_H)
     /* By directly using a syscall we avoid any calls that might be unsafe after
      * fork() (e.g. malloc()). */
     char buffer[sizeof(struct linux_dirent64)];
     struct linux_dirent64 *entry;
     int offset, len;
     dir_fd = open("/proc/self/fd", O_RDONLY);
     if (dir_fd != -1)
     {
         while ((len = syscall(__NR_getdents64, dir_fd, buffer,
                               sizeof(buffer))) > 0)
         {
             for (offset = 0; offset < len; offset += entry->d_reclen)
             {
                 entry = (struct linux_dirent64*)(buffer + offset);
                 if (!isdigit(entry->d_name[0]))
                 {
                     continue;
                 }
                 fd = atoi(entry->d_name);
                 if (fd != dir_fd && fd >= low_fd)
                 {
                     close(fd);
                 }
             }
         }
         close(dir_fd);
         return;
     }
 #else /* !defined(__linux__) || !defined(HAVE_SYS_SYSCALL_H) */
     /* This is potentially unsafe when called after fork() in multi-threaded
      * applications.  In particular opendir() will require an allocation.
      * Depends on how the malloc() implementation handles such situations. */
     DIR *dir;
     struct dirent *entry;
 #ifndef HAVE_DIRFD
     /* if we don't have dirfd() lets close the lowest FD and hope it gets reused
      * by opendir() */
     close(low_fd);
     dir_fd = low_fd++;
 #endif
     dir = opendir(FD_DIR);
     if (dir)
     {
 #ifdef HAVE_DIRFD
         dir_fd = dirfd(dir);
 #endif
         while ((entry = readdir(dir)))
         {
             if (!isdigit(entry->d_name[0]))
             {
                 continue;
             }
             fd = atoi(entry->d_name);
             if (fd != dir_fd && fd >= low_fd)
             {
                 close(fd);
             }
         }
         closedir(dir);
         return;
     }
 #endif /* defined(__linux__) && defined(HAVE_SYS_SYSCALL_H) */
     /* ...fall back to closing all fds otherwise */
 #ifdef WIN32
     max_fd = _getmaxstdio();
 #else
     max_fd = (int)sysconf(_SC_OPEN_MAX);
 #endif
     if (max_fd < 0)
     {
         max_fd = 256;
     }
     for (fd = low_fd; fd < max_fd; fd++)
     {
         close(fd);
     }
 }
void nop ()
No-Operation function
nop operation
Definition at line 274 of file utils.c.
Referenced by auth_cfg_wrapper_create(), cert_cache_create(), create_generic(), dnscert_cred_create(), eap_aka_3gpp2_card_create(), eap_sim_file_card_create(), eap_sim_pcsc_card_create(), eap_simaka_pseudonym_card_create(), eap_simaka_reauth_card_create(), eap_simaka_sql_card_create(), encrypted_fragment_payload_create(), ipseckey_cred_create(), load_tester_creds_create(), medcli_creds_create(), medsrv_creds_create(), mem_cred_create(), nm_creds_create(), nm_handler_create(), ocsp_response_wrapper_create(), pkcs11_creds_create(), setup_tunnel(), START_TEST(), stroke_ca_create(), tkm_cred_create(), tls_socket_create(), uci_creds_create(), and vici_authority_create().
 {
 }
bool return_false ()
returns FALSE
Definition at line 266 of file utils.c.
References FALSE.
Referenced by aesni_plugin_create(), attr_provider_create(), cmd_connection_create(), create_empty(), dispatch(), eap_aka_3gpp2_card_create(), eap_aka_3gpp2_provider_create(), eap_radius_handle_timeout(), eap_sim_file_card_create(), eap_sim_file_provider_create(), eap_sim_pcsc_card_create(), eap_simaka_pseudonym_card_create(), eap_simaka_pseudonym_provider_create(), eap_simaka_reauth_card_create(), eap_simaka_reauth_provider_create(), eap_simaka_sql_card_create(), eap_simaka_sql_provider_create(), enumerate_nbns(), forecast_plugin_create(), ha_ctl_create(), ha_dispatcher_create(), hybrid_authenticator_create(), identification_create(), ipsec_event_relay_create(), ipsec_processor_create(), kernel_libipsec_router_create(), load_tester_plugin_create(), METHOD(), notify(), parse(), pkcs11_manager_create(), psk_authenticator_create_builder(), psk_authenticator_create_verifier(), psk_v1_authenticator_create(), pubkey_authenticator_create_builder(), pubkey_authenticator_create_verifier(), pubkey_v1_authenticator_create(), rdrand_plugin_create(), receiver_create(), schedule_interim(), scheduler_create(), sender_create(), smp_plugin_create(), start_autobalance(), start_heartbeat(), START_TEST(), start_watchdog(), stroke_handler_create(), stroke_plugin_create(), uci_control_create(), unity_provider_create(), vici_plugin_create(), and watch().
 {
     return FALSE;
 }
void* return_null ()
returns null
return null
Definition at line 250 of file utils.c.
Referenced by attr_provider_create(), auth_cfg_wrapper_create(), cert_cache_create(), create_generic(), dnscert_cred_create(), eap_aka_3gpp2_card_create(), eap_aka_3gpp2_provider_create(), eap_sim_file_card_create(), eap_sim_file_provider_create(), eap_sim_pcsc_card_create(), eap_simaka_pseudonym_card_create(), eap_simaka_pseudonym_provider_create(), eap_simaka_reauth_card_create(), eap_simaka_reauth_provider_create(), eap_simaka_sql_card_create(), eap_simaka_sql_provider_create(), encrypted_fragment_payload_create(), ipseckey_cred_create(), load_tester_creds_create(), medcli_creds_create(), medsrv_creds_create(), nm_creds_create(), ocsp_response_wrapper_create(), setup_tunnel(), START_TEST(), stroke_ca_create(), stroke_cred_create(), tkm_cred_create(), uci_creds_create(), unity_provider_create(), and vici_authority_create().
 {
     return NULL;
 }
bool return_true ()
returns TRUE
Definition at line 258 of file utils.c.
References TRUE.
Referenced by identification_create(), load_tester_ipsec_create(), and START_TEST().
 {
     return TRUE;
 }
int sigwaitinfo (const sigset_t * set, void * info)
Block and wait for a set of signals
We don't replicate the functionality of siginfo_t. If info is not NULL -1 is returend and errno is set to EINVAL.
Parameters
set set of signals to wait for
info must be NULL
Definition at line 134 of file utils.c.
References sig.
Referenced by main(), METHOD(), run(), and wait_sigint().
 {
     int sig, err;
     if (info)
     {   /* we don't replicate siginfo_t, fail if anybody tries to use it */
         errno = EINVAL;
         return -1;
     }
     err = sigwait(set, &sig);
     if (err != 0)
     {
         errno = err;
         sig = -1;
     }
     return sig;
 }
void utils_deinit ()
Deinitialize utility functions
See header
Definition at line 293 of file utils.c.
References atomics_deinit(), strerror_deinit(), and windows_deinit().
Referenced by library_deinit().
 {
 #ifdef WIN32
     windows_deinit();
 #endif
     atomics_deinit();
     strerror_deinit();
 }
void utils_init ()
Initialize utility functions
See header
Definition at line 281 of file utils.c.
References atomics_init(), strerror_init(), and windows_init().
Referenced by library_init().
 {
 #ifdef WIN32
     windows_init();
 #endif
     atomics_init();
     strerror_init();
 }
void wait_sigint ()
Portable function to wait for SIGINT/SIGTERM (or equivalent).
Unix variant
Definition at line 118 of file utils.c.
References sigwaitinfo().
Referenced by logcmd(), and monitor_sas().
 {
     sigset_t set;
     sigemptyset(&set);
     sigaddset(&set, SIGINT);
     sigaddset(&set, SIGTERM);
     sigprocmask(SIG_BLOCK, &set, NULL);
     while (sigwaitinfo(&set, NULL) == -1 && errno == EINTR)
     {
         /* wait for signal */
     }
 }