strongSwan: dhcp_provider.c File Reference
dhcp_provider.c File Reference
#include "dhcp_provider.h"
#include <collections/hashtable.h>
#include <threading/mutex.h>
Classes
struct private_dhcp_provider_t
Typedefs
typedef struct
private_dhcp_provider_t private_dhcp_provider_t
Functions
static uintptr_t hash_id_host (identification_t *id, host_t *host)
static uintptr_t hash_transaction (dhcp_transaction_t *transaction)
METHOD (attribute_provider_t, acquire_address, host_t *, private_dhcp_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
METHOD (attribute_provider_t, release_address, bool, private_dhcp_provider_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
METHOD (attribute_provider_t, create_attribute_enumerator, enumerator_t *, private_dhcp_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (dhcp_provider_t, destroy, void, private_dhcp_provider_t *this)
dhcp_provider_t * dhcp_provider_create (dhcp_socket_t *socket)
Typedef Documentation
typedef struct private_dhcp_provider_t private_dhcp_provider_t
Definition at line 21 of file dhcp_provider.c.
Function Documentation
static uintptr_t hash_id_host (identification_t * id, host_t * host) static
Hash ID and host to a key
Definition at line 52 of file dhcp_provider.c.
References chunk_hash(), chunk_hash_inc(), host_t::get_address, and identification_t::get_encoding.
Referenced by hash_transaction(), and METHOD().
 {
     return chunk_hash_inc(id->get_encoding(id),
                           chunk_hash(host->get_address(host)));
 }
static uintptr_t hash_transaction (dhcp_transaction_t * transaction) static
Hash a DHCP transaction to a key, using address and id
Definition at line 61 of file dhcp_provider.c.
References dhcp_transaction_t::get_address, dhcp_transaction_t::get_identity, and hash_id_host().
Referenced by METHOD().
 {
     return hash_id_host(transaction->get_identity(transaction),
                         transaction->get_address(transaction));
 }
METHOD (attribute_provider_t , acquire_address , host_t * , private_dhcp_provider_t * this, linked_list_t * pools, ike_sa_t * ike_sa, host_t * requested)
Definition at line 67 of file dhcp_provider.c.
References host_t::clone, linked_list_t::create_enumerator, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, dhcp_transaction_t::get_address, host_t::get_family, ike_sa_t::get_other_eap_id, hash_transaction(), id, mutex_t::lock, mutex, socket, streq(), mutex_t::unlock, and vip.
 {
     dhcp_transaction_t *transaction, *old;
     enumerator_t *enumerator;
     identification_t *id;
     char *pool;
     host_t *vip = NULL;
     if (requested->get_family(requested) != AF_INET)
     {
         return NULL;
     }
     id = ike_sa->get_other_eap_id(ike_sa);
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &pool))
     {
         if (!streq(pool, "dhcp"))
         {
             continue;
         }
         transaction = this->socket->enroll(this->socket, id);
         if (!transaction)
         {
             continue;
         }
         vip = transaction->get_address(transaction);
         vip = vip->clone(vip);
         this->mutex->lock(this->mutex);
         old = this->transactions->put(this->transactions,
                             (void*)hash_transaction(transaction), transaction);
         this->mutex->unlock(this->mutex);
         DESTROY_IF(old);
         break;
     }
     enumerator->destroy(enumerator);
     return vip;
 }
METHOD (attribute_provider_t , release_address , bool , private_dhcp_provider_t * this, linked_list_t * pools, host_t * address, ike_sa_t * ike_sa)
Definition at line 107 of file dhcp_provider.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, dhcp_transaction_t::destroy, enumerator_t::enumerate, FALSE, found, host_t::get_family, ike_sa_t::get_other_eap_id, hash_id_host(), id, mutex_t::lock, mutex, socket, streq(), TRUE, and mutex_t::unlock.
 {
     dhcp_transaction_t *transaction;
     enumerator_t *enumerator;
     identification_t *id;
     bool found = FALSE;
     char *pool;
     if (address->get_family(address) != AF_INET)
     {
         return FALSE;
     }
     id = ike_sa->get_other_eap_id(ike_sa);
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &pool))
     {
         if (!streq(pool, "dhcp"))
         {
             continue;
         }
         this->mutex->lock(this->mutex);
         transaction = this->transactions->remove(this->transactions,
                                         (void*)hash_id_host(id, address));
         this->mutex->unlock(this->mutex);
         if (transaction)
         {
             this->socket->release(this->socket, transaction);
             transaction->destroy(transaction);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (attribute_provider_t , create_attribute_enumerator , enumerator_t * , private_dhcp_provider_t * this, linked_list_t * pools, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 145 of file dhcp_provider.c.
References dhcp_transaction_t::create_attribute_enumerator, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_cleaner(), linked_list_t::find_first, ike_sa_t::get_other_eap_id, hash_id_host(), id, mutex_t::lock, mutex, streq(), SUCCESS, mutex_t::unlock, and vip.
 {
     dhcp_transaction_t *transaction = NULL;
     enumerator_t *enumerator;
     identification_t *id;
     host_t *vip;
     if (pools->find_first(pools, (linked_list_match_t)streq,
                           NULL, "dhcp") != SUCCESS)
     {
         return NULL;
     }
     id = ike_sa->get_other_eap_id(ike_sa);
     this->mutex->lock(this->mutex);
     enumerator = vips->create_enumerator(vips);
     while (enumerator->enumerate(enumerator, &vip))
     {
         transaction = this->transactions->get(this->transactions,
                                               (void*)hash_id_host(id, vip));
         if (transaction)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!transaction)
     {
         this->mutex->unlock(this->mutex);
         return NULL;
     }
     return enumerator_create_cleaner(
                         transaction->create_attribute_enumerator(transaction),
                         (void*)this->mutex->unlock, this->mutex);
 }
METHOD (dhcp_provider_t , destroy , void , private_dhcp_provider_t * this)
Definition at line 183 of file dhcp_provider.c.
References enumerator_t::destroy, mutex_t::destroy, dhcp_transaction_t::destroy, enumerator_t::enumerate, free(), key, mutex, and value.
 {
     enumerator_t *enumerator;
     dhcp_transaction_t *value;
     void *key;
     enumerator = this->transactions->create_enumerator(this->transactions);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         value->destroy(value);
     }
     enumerator->destroy(enumerator);
     this->transactions->destroy(this->transactions);
     this->mutex->destroy(this->mutex);
     free(this);
 }