strongSwan: eap_simaka_reauth_card
eap_simaka_reauth_card
eap_simaka_reauth
Classes
struct eap_simaka_reauth_card_t
Typedefs
typedef struct
eap_simaka_reauth_card_t eap_simaka_reauth_card_t
Functions
eap_simaka_reauth_card_t * eap_simaka_reauth_card_create ()
Detailed Description
Typedef Documentation
typedef struct eap_simaka_reauth_card_t eap_simaka_reauth_card_t
Definition at line 26 of file eap_simaka_reauth_card.h.
Function Documentation
eap_simaka_reauth_card_t* eap_simaka_reauth_card_create ()
Create a eap_simaka_reauth_card instance.
See header
Definition at line 143 of file eap_simaka_reauth_card.c.
References equals(), hash(), hashtable_create(), INIT, nop(), return_false(), and return_null().
Referenced by get_card().
 {
     private_eap_simaka_reauth_card_t *this;
     INIT(this,
         .public = {
             .card = {
                 .get_triplet = (void*)return_null,
                 .get_quintuplet = _get_quintuplet,
                 .resync = (void*)return_false,
                 .get_pseudonym = (void*)return_null,
                 .set_pseudonym = (void*)nop,
                 .get_reauth = _get_reauth,
                 .set_reauth = _set_reauth,
             },
             .destroy = _destroy,
         },
         .reauth = hashtable_create((void*)hash, (void*)equals, 0),
     );
     return &this->public;
 }