strongSwan: ipsec_processor
ipsec_processor
libipsec
Classes
struct ipsec_processor_t
Typedefs
typedef struct ipsec_processor_t ipsec_processor_t
typedef void(* ipsec_inbound_cb_t)(void *data, ip_packet_t *packet)
typedef void(* ipsec_outbound_cb_t)(void *data, esp_packet_t *packet)
Functions
ipsec_processor_t * ipsec_processor_create ()
Detailed Description
Typedef Documentation
typedef void(* ipsec_inbound_cb_t)(void *data, ip_packet_t *packet)
Callback called to deliver an inbound plaintext packet.
Parameters
data data supplied during registration of the callback
packet plaintext IP packet to deliver
Definition at line 35 of file ipsec_processor.h.
typedef void(* ipsec_outbound_cb_t)(void *data, esp_packet_t *packet)
Callback called to send an ESP packet.
Note
The ESP packet currently comes without IP header (and without UDP header in case of UDP encapsulation)
Parameters
data data supplied during registration of the callback
packet ESP packet to send
Definition at line 46 of file ipsec_processor.h.
typedef struct ipsec_processor_t ipsec_processor_t
Definition at line 27 of file ipsec_processor.h.
Function Documentation
ipsec_processor_t* ipsec_processor_create ()
Create an ipsec_processor_t instance
Returns
IPsec processor instance
Described in header.
Definition at line 302 of file ipsec_processor.c.
References blocking_queue_create(), callback_job_create(), INIT, lib, process_inbound(), process_outbound(), library_t::processor, processor_t::queue_job, return_false(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by libipsec_init().
 {
     private_ipsec_processor_t *this;
     INIT(this,
         .public = {
             .queue_inbound = _queue_inbound,
             .queue_outbound = _queue_outbound,
             .register_inbound = _register_inbound,
             .unregister_inbound = _unregister_inbound,
             .register_outbound = _register_outbound,
             .unregister_outbound = _unregister_outbound,
             .destroy = _destroy,
         },
         .inbound_queue = blocking_queue_create(),
         .outbound_queue = blocking_queue_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create((callback_job_cb_t)process_inbound, this,
                                     NULL, (callback_job_cancel_t)return_false));
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create((callback_job_cb_t)process_outbound, this,
                                     NULL, (callback_job_cancel_t)return_false));
     return &this->public;
 }