strongSwan: tcg_pts_attr_req_func_comp_evid_t Struct Reference
tcg_pts_attr_req_func_comp_evid_t Struct Reference
tcg_pts_attr_req_func_comp_evid
#include "tcg_pts_attr_req_func_comp_evid.h"
Public Attributes
pa_tnc_attr_t pa_tnc_attribute
void(* add_component)(tcg_pts_attr_req_func_comp_evid_t *this, u_int8_t flags, u_int32_t depth, pts_comp_func_name_t *name)
int(* get_count)(tcg_pts_attr_req_func_comp_evid_t *this)
enumerator_t *(* create_enumerator)(tcg_pts_attr_req_func_comp_evid_t *this)
Detailed Description
Class implementing the TCG PTS Request Functional Component Evidence attribute
Definition at line 35 of file tcg_pts_attr_req_func_comp_evid.h.
Member Data Documentation
void(* tcg_pts_attr_req_func_comp_evid_t::add_component)(tcg_pts_attr_req_func_comp_evid_t *this, u_int8_t flags, u_int32_t depth, pts_comp_func_name_t *name)
Add a component to the Functional Component Evidence Request
Parameters
flags Component Evidence Request Flags
depth Sub-component Depth
name Functional Component Name
Definition at line 49 of file tcg_pts_attr_req_func_comp_evid.h.
Referenced by imv_attestation_build().
enumerator_t*(* tcg_pts_attr_req_func_comp_evid_t::create_enumerator)(tcg_pts_attr_req_func_comp_evid_t *this)
Enumerator over Functional Component entries
Returns
Entry enumerator
Definition at line 65 of file tcg_pts_attr_req_func_comp_evid.h.
Referenced by imc_attestation_process().
int(* tcg_pts_attr_req_func_comp_evid_t::get_count)(tcg_pts_attr_req_func_comp_evid_t *this)
Returns the number of Functional Component entries
Returns
Number of entries
Definition at line 58 of file tcg_pts_attr_req_func_comp_evid.h.
Referenced by imc_attestation_process().
pa_tnc_attr_t tcg_pts_attr_req_func_comp_evid_t::pa_tnc_attribute
Public PA-TNC attribute interface
Definition at line 40 of file tcg_pts_attr_req_func_comp_evid.h.
The documentation for this struct was generated from the following file:
tcg_pts_attr_req_func_comp_evid.h