strongSwan: fetcher_manager_t Struct Reference
fetcher_manager_t Struct Reference
fetcher_manager
#include "fetcher_manager.h"
Public Attributes
status_t(* fetch)(fetcher_manager_t *this, char *url, void *userdata,...)
void(* add_fetcher)(fetcher_manager_t *this, fetcher_constructor_t constructor, char *url)
void(* remove_fetcher)(fetcher_manager_t *this, fetcher_constructor_t constructor)
void(* destroy)(fetcher_manager_t *this)
Detailed Description
Fetches from URIs using registered fetcher_t instances.
Definition at line 31 of file fetcher_manager.h.
Member Data Documentation
void(* fetcher_manager_t::add_fetcher)(fetcher_manager_t *this, fetcher_constructor_t constructor, char *url)
Register a fetcher implementation.
Parameters
constructor fetcher constructor function
url URL type this fetcher fetches, e.g. "http://"
Definition at line 55 of file fetcher_manager.h.
Referenced by plugin_feature_load().
void(* fetcher_manager_t::destroy)(fetcher_manager_t *this)
Destroy a fetcher_manager instance.
Definition at line 69 of file fetcher_manager.h.
status_t(* fetcher_manager_t::fetch)(fetcher_manager_t *this, char *url, void *userdata,...)
Fetch data from URI.
The variable argument list contains fetcher_option_t's, followed by a option specific data argument. If no FETCH_CALLBACK function is given as option, userdata must be a chunk_t*. This chunk gets allocated, accumulated data using the fetcher_default_callback() function.
Parameters
uri URI to fetch from
userdata userdata to pass to callback function.
options FETCH_END terminated fetcher_option_t arguments
Returns
status indicating result of fetch
Definition at line 47 of file fetcher_manager.h.
Referenced by fetch_cert(), fetch_crl(), fetch_ocsp(), main(), METHOD(), scep_http_request(), and START_TEST().
void(* fetcher_manager_t::remove_fetcher)(fetcher_manager_t *this, fetcher_constructor_t constructor)
Unregister a previously registered fetcher implementation.
Parameters
constructor fetcher constructor function to unregister
Definition at line 63 of file fetcher_manager.h.
Referenced by plugin_feature_unload().
The documentation for this struct was generated from the following file:
fetcher_manager.h