strongSwan: packet
packet
networking
Classes
struct packet_t
Macros
#define PACKET_MAX_DEFAULT 10000
Typedefs
typedef struct packet_t packet_t
Functions
packet_t * packet_create ()
packet_t * packet_create_from_data (host_t *src, host_t *dst, chunk_t data)
Detailed Description
Macro Definition Documentation
#define PACKET_MAX_DEFAULT 10000
Maximum packet size we handle by default
Definition at line 34 of file packet.h.
Referenced by message_create_defrag(), socket_default_socket_create(), socket_dynamic_socket_create(), and socket_win_socket_create().
Typedef Documentation
typedef struct packet_t packet_t
Definition at line 26 of file packet.h.
Function Documentation
packet_t* packet_create ()
Create an empty packet
Returns
packet_t object
Definition at line 179 of file packet.c.
References chunk_empty, and packet_create_from_data().
Referenced by message_create(), METHOD(), and receive_packet().
 {
     return packet_create_from_data(NULL, NULL, chunk_empty);
 }
packet_t* packet_create_from_data (host_t * src, host_t * dst, chunk_t data)
Create a packet from the supplied data
Parameters
src source address (gets owned)
dst destination address (gets owned)
data packet data (gets owned)
Returns
packet_t object
Described in header.
Definition at line 149 of file packet.c.
References data, dst, INIT, and src.
Referenced by esp_packet_create_from_payload(), and packet_create().
 {
     private_packet_t *this;
     INIT(this,
         .public = {
             .set_data = _set_data,
             .get_data = _get_data,
             .set_source = _set_source,
             .get_source = _get_source,
             .set_destination = _set_destination,
             .get_destination = _get_destination,
             .get_dscp = _get_dscp,
             .set_dscp = _set_dscp,
             .skip_bytes = _skip_bytes,
             .clone = _clone_,
             .destroy = _destroy,
         },
         .source = src,
         .destination = dst,
         .adjusted_data = data,
         .data = data,
     );
     return &this->public;
 }