strongSwan: manager.c File Reference
manager.c File Reference
#include "manager.h"
#include "gateway.h"
#include <collections/linked_list.h>
Classes
struct private_manager_t
Typedefs
typedef struct private_manager_t private_manager_t
Functions
METHOD (manager_t, create_gateway_enumerator, enumerator_t *, private_manager_t *this)
METHOD (manager_t, select_gateway, gateway_t *, private_manager_t *this, int select_id)
METHOD (manager_t, logged_in, bool, private_manager_t *this)
METHOD (manager_t, login, bool, private_manager_t *this, char *username, char *password)
METHOD (manager_t, logout, void, private_manager_t *this)
METHOD (fast_context_t, destroy, void, private_manager_t *this)
manager_t * manager_create (storage_t *storage)
Typedef Documentation
typedef struct private_manager_t private_manager_t
Definition at line 22 of file manager.c.
Function Documentation
METHOD (manager_t , create_gateway_enumerator , enumerator_t * , private_manager_t * this)
Definition at line 50 of file manager.c.
 {
     return this->store->create_gateway_enumerator(this->store, this->user);
 }
METHOD (manager_t , select_gateway , gateway_t * , private_manager_t * this, int select_id)
Definition at line 56 of file manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, gateway_create_tcp(), gateway_create_unix(), host, host_create_from_string(), id, name, and port.
 {
     if (select_id != 0)
     {
         enumerator_t *enumerator;
         int id, port;
         char *name, *address;
         host_t *host;
         if (this->gateway) this->gateway->destroy(this->gateway);
         this->gateway = NULL;
         enumerator = this->store->create_gateway_enumerator(this->store, this->user);
         while (enumerator->enumerate(enumerator, &id, &name, &port, &address))
         {
             if (select_id == id)
             {
                 if (port == 0)
                 {
                     this->gateway = gateway_create_unix(name);
                 }
                 else
                 {
                     host = host_create_from_string(address, port);
                     if (host)
                     {
                         this->gateway = gateway_create_tcp(name, host);
                     }
                 }
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     return this->gateway;
 }
METHOD (manager_t , logged_in , bool , private_manager_t * this)
Definition at line 94 of file manager.c.
 {
     return this->user != 0;
 }
METHOD (manager_t , login , bool , private_manager_t * this, char * username, char * password)
Definition at line 100 of file manager.c.
 {
     if (!this->user)
     {
         this->user = this->store->login(this->store, username, password);
     }
     return this->user != 0;
 }
METHOD (manager_t , logout , void , private_manager_t * this)
Definition at line 110 of file manager.c.
 {
     if (this->gateway)
     {
         this->gateway->destroy(this->gateway);
         this->gateway = NULL;
     }
     this->user = 0;
 }
METHOD (fast_context_t , destroy , void , private_manager_t * this)
Definition at line 121 of file manager.c.
References free().
 {
     if (this->gateway) this->gateway->destroy(this->gateway);
     free(this);
 }