strongSwan: eap_simaka_pseudonym_provider
eap_simaka_pseudonym_provider
eap_simaka_pseudonym
Classes
struct eap_simaka_pseudonym_provider_t
Typedefs
typedef struct
eap_simaka_pseudonym_provider_t eap_simaka_pseudonym_provider_t
Functions
eap_simaka_pseudonym_provider_t * eap_simaka_pseudonym_provider_create ()
Detailed Description
Typedef Documentation
typedef struct eap_simaka_pseudonym_provider_t eap_simaka_pseudonym_provider_t
Definition at line 26 of file eap_simaka_pseudonym_provider.h.
Function Documentation
eap_simaka_pseudonym_provider_t* eap_simaka_pseudonym_provider_create ()
Create a eap_simaka_pseudonym_provider instance.
See header
Definition at line 157 of file eap_simaka_pseudonym_provider.c.
References crypto_factory_t::create_rng, library_t::crypto, destroy(), equals(), free(), hash(), hashtable_create(), INIT, lib, return_false(), return_null(), rng, and RNG_WEAK.
Referenced by get_provider().
 {
     private_eap_simaka_pseudonym_provider_t *this;
     INIT(this,
         .public = {
             .provider = {
                 .get_triplet = (void*)return_false,
                 .get_quintuplet = (void*)return_false,
                 .resync = (void*)return_false,
                 .is_pseudonym = _is_pseudonym,
                 .gen_pseudonym = _gen_pseudonym,
                 .is_reauth = (void*)return_null,
                 .gen_reauth = (void*)return_null,
             },
             .destroy = _destroy,
         },
         .rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK),
     );
     if (!this->rng)
     {
         free(this);
         return NULL;
     }
     this->pseudonym = hashtable_create((void*)hash, (void*)equals, 0);
     this->permanent = hashtable_create((void*)hash, (void*)equals, 0);
     return &this->public;
 }