strongSwan: imc_os.c File Reference
imc_os.c File Reference
#include "imc_os_state.h"
#include <imc/imc_agent.h>
#include <imc/imc_msg.h>
#include <imc/imc_os_info.h>
#include <generic/generic_attr_bool.h>
#include <generic/generic_attr_string.h>
#include <ietf/ietf_attr.h>
#include <ietf/ietf_attr_attr_request.h>
#include "ietf/ietf_attr_fwd_enabled.h"
#include <ietf/ietf_attr_installed_packages.h>
#include <ietf/ietf_attr_numeric_version.h>
#include <ietf/ietf_attr_op_status.h>
#include <ietf/ietf_attr_product_info.h>
#include <ietf/ietf_attr_string_version.h>
#include <ita/ita_attr.h>
#include <ita/ita_attr_get_settings.h>
#include <ita/ita_attr_settings.h>
#include <tncif_pa_subtypes.h>
#include <pen/pen.h>
#include <utils/debug.h>
Functions
TNC_Result TNC_IMC_API TNC_IMC_Initialize (TNC_IMCID imc_id, TNC_Version min_version, TNC_Version max_version, TNC_Version *actual_version)
TNC_Result TNC_IMC_API TNC_IMC_NotifyConnectionChange (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_ConnectionState new_state)
static void add_product_info (imc_msg_t *msg)
static void add_numeric_version (imc_msg_t *msg)
static void add_string_version (imc_msg_t *msg)
static void add_op_status (imc_msg_t *msg)
static void add_fwd_enabled (imc_msg_t *msg)
static void add_default_pwd_enabled (imc_msg_t *msg)
static void add_device_id (imc_msg_t *msg)
static void add_installed_packages (imc_state_t *state, imc_msg_t *msg)
static void add_settings (enumerator_t *enumerator, imc_msg_t *msg)
TNC_Result TNC_IMC_API TNC_IMC_BeginHandshake (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
static TNC_Result receive_message (imc_state_t *state, imc_msg_t *in_msg)
TNC_Result TNC_IMC_API TNC_IMC_ReceiveMessage (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
TNC_Result TNC_IMC_API TNC_IMC_ReceiveMessageLong (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
TNC_Result TNC_IMC_API TNC_IMC_BatchEnding (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
TNC_Result TNC_IMC_API TNC_IMC_Terminate (TNC_IMCID imc_id)
TNC_Result TNC_IMC_API TNC_IMC_ProvideBindFunction (TNC_IMCID imc_id, TNC_TNCC_BindFunctionPointer bind_function)
Variables
static const char imc_name [] = "OS"
static pen_type_t msg_types []
static imc_agent_t * imc_os
static imc_os_info_t * os
Function Documentation
static void add_default_pwd_enabled (imc_msg_t * msg) static
Add IETF Factory Default Password Enabled attribute to the send queue
Definition at line 224 of file imc_os.c.
References imc_msg_t::add_attribute, DBG1, DBG_IMC, generic_attr_bool_create(), imc_os_info_t::get_default_pwd_status, IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED, PEN_IETF, pen_type_create(), and status.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     bool status;
     status = os->get_default_pwd_status(os);
     DBG1(DBG_IMC, "factory default password is %sabled", status ? "en" : "dis");
     attr = generic_attr_bool_create(status,
             pen_type_create(PEN_IETF, IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED));
     msg->add_attribute(msg, attr);
 }
static void add_device_id (imc_msg_t * msg) static
Add ITA Device ID attribute to the send queue
Definition at line 239 of file imc_os.c.
References imc_msg_t::add_attribute, BUILD_END, BUILD_FROM_FILE, cert, CERT_TRUSTED_PUBKEY, CERT_X509, chunk_clone, chunk_empty, chunk_from_str, chunk_to_hex(), credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG2, DBG_IMC, certificate_t::destroy, public_key_t::destroy, FALSE, free(), generic_attr_string_create(), public_key_t::get_fingerprint, certificate_t::get_public_key, imc_os_info_t::get_setting, settings_t::get_str, imc_os_info_t::get_type, ITA_ATTR_DEVICE_ID, keyid(), KEYID_PUBKEY_INFO_SHA1, chunk_t::len, lib, name, library_t::ns, OS_TYPE_ANDROID, PEN_ITA, pen_type_create(), chunk_t::ptr, library_t::settings, and value.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     chunk_t value = chunk_empty, keyid;
     char *name, *device_id, *cert_path;
     certificate_t *cert = NULL;
     public_key_t *pubkey;
     /* Get the device ID as a character string */
     device_id = lib->settings->get_str(lib->settings,
                         "%s.plugins.imc-os.device_id", NULL, lib->ns);
     if (device_id)
     {
         value = chunk_clone(chunk_from_str(device_id));
     }
     if (value.len == 0)
     {
         /* Derive the device ID from a raw public key */
         cert_path = lib->settings->get_str(lib->settings,
                             "%s.plugins.imc-os.device_pubkey", NULL, lib->ns);
         if (cert_path)
         {
             cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                                       CERT_TRUSTED_PUBKEY, BUILD_FROM_FILE,
                                       cert_path, BUILD_END);
             if (cert)
             {
                 DBG2(DBG_IMC, "loaded device public key from '%s'", cert_path);
             }
             else
             {
                 DBG1(DBG_IMC, "loading device public key from '%s' failed",
                                cert_path);
             }
         }
         if (!cert)
         {
             /* Derive the device ID from the public key contained in a certificate */
             cert_path = lib->settings->get_str(lib->settings,
                                 "%s.plugins.imc-os.device_cert", NULL, lib->ns);
             if (cert_path)
             {
                 cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                                           CERT_X509, BUILD_FROM_FILE,
                                           cert_path, BUILD_END);
                 if (cert)
                 {
                     DBG2(DBG_IMC, "loaded device certificate from '%s'", cert_path);
                 }
                 else
                 {
                     DBG1(DBG_IMC, "loading device certificate from '%s' failed",
                                    cert_path);
                 }
             }
         }
         /* Compute the SHA-1 keyid of the retrieved device public key */
         if (cert)
         {
             pubkey = cert->get_public_key(cert);
             if (pubkey)
             {
                 if (pubkey->get_fingerprint(pubkey, KEYID_PUBKEY_INFO_SHA1,
                                             &keyid))
                 {
                     value = chunk_to_hex(keyid, NULL, FALSE);
                 }
                 pubkey->destroy(pubkey);
             }
             cert->destroy(cert);
         }
     }
     if (value.len == 0)
     {
         /* Derive the device ID from some unique OS settings */
         name = os->get_type(os) == OS_TYPE_ANDROID ?
                       "android_id" : "/var/lib/dbus/machine-id";
         value = os->get_setting(os, name);
         /* Trim trailing newline character */
         if (value.len > 0 && value.ptr[value.len - 1] == '\n')
         {
             value.len--;
         }
     }
     if (value.len == 0)
     {
         DBG1(DBG_IMC, "no device ID available");
         return;
     }
     DBG1(DBG_IMC, "device ID is %.*s", value.len, value.ptr);
     attr = generic_attr_string_create(value, pen_type_create(PEN_ITA,
                                       ITA_ATTR_DEVICE_ID));
     msg->add_attribute(msg, attr);
     free(value.ptr);
 }
static void add_fwd_enabled (imc_msg_t * msg) static
Add IETF Forwarding Enabled attribute to the send queue
Definition at line 209 of file imc_os.c.
References imc_msg_t::add_attribute, DBG1, DBG_IMC, imc_os_info_t::get_fwd_status, IETF_ATTR_FORWARDING_ENABLED, ietf_attr_fwd_enabled_create(), os_fwd_status_names, PEN_IETF, and pen_type_create().
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     os_fwd_status_t fwd_status;
     fwd_status = os->get_fwd_status(os);
     DBG1(DBG_IMC, "IPv4 forwarding is %N", os_fwd_status_names, fwd_status);
     attr = ietf_attr_fwd_enabled_create(fwd_status,
                 pen_type_create(PEN_IETF, IETF_ATTR_FORWARDING_ENABLED));
     msg->add_attribute(msg, attr);
 }
static void add_installed_packages (imc_state_t * state, imc_msg_t * msg) static
Add an IETF Installed Packages attribute to the send queue
Definition at line 345 of file imc_os.c.
References ietf_attr_installed_packages_t::add, imc_msg_t::add_attribute, imc_os_info_t::create_package_enumerator, DBG2, DBG_IMC, enumerator_t::destroy, enumerator_t::enumerate, ietf_attr_installed_packages_create(), chunk_t::len, name, chunk_t::ptr, and version.
Referenced by receive_message().
 {
     pa_tnc_attr_t *attr;
     ietf_attr_installed_packages_t *attr_cast;
     enumerator_t *enumerator;
     chunk_t name, version;
     enumerator = os->create_package_enumerator(os);
     if (!enumerator)
     {
         return;
     }
     attr = ietf_attr_installed_packages_create();
     while (enumerator->enumerate(enumerator, &name, &version))
     {
         DBG2(DBG_IMC, "package '%.*s' (%.*s)",
                        name.len, name.ptr, version.len, version.ptr);
         attr_cast = (ietf_attr_installed_packages_t*)attr;
         attr_cast->add(attr_cast, name, version);
     }
     enumerator->destroy(enumerator);
     msg->add_attribute(msg, attr);
 }
static void add_numeric_version (imc_msg_t * msg) static
Add IETF Numeric Version attribute to the send queue
Definition at line 162 of file imc_os.c.
References imc_msg_t::add_attribute, DBG1, DBG_IMC, imc_os_info_t::get_numeric_version, and ietf_attr_numeric_version_create().
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     u_int32_t major, minor;
     os->get_numeric_version(os, &major, &minor);
     DBG1(DBG_IMC, "operating system numeric version is %d.%d",
                    major, minor);
     attr = ietf_attr_numeric_version_create(major, minor, 0, 0, 0);
     msg->add_attribute(msg, attr);
 }
static void add_op_status (imc_msg_t * msg) static
Add IETF Operational Status attribute to the send queue
Definition at line 190 of file imc_os.c.
References imc_msg_t::add_attribute, DBG1, DBG_IMC, imc_os_info_t::get_uptime, ietf_attr_op_status_create(), OP_RESULT_SUCCESSFUL, OP_STATUS_OPERATIONAL, TRUE, and UNDEFINED_TIME.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     time_t uptime, last_boot;
     uptime = os->get_uptime(os);
     last_boot = uptime ? time(NULL) - uptime : UNDEFINED_TIME;
     if (last_boot != UNDEFINED_TIME)
     {
         DBG1(DBG_IMC, "last boot: %T, %u s ago", &last_boot, TRUE, uptime);
     }
     attr = ietf_attr_op_status_create(OP_STATUS_OPERATIONAL,
                                       OP_RESULT_SUCCESSFUL, last_boot);
     msg->add_attribute(msg, attr);
 }
static void add_product_info (imc_msg_t * msg) static
Add IETF Product Information attribute to the send queue
Definition at line 126 of file imc_os.c.
References imc_msg_t::add_attribute, countof, imc_os_info_t::get_name, imc_os_info_t::get_type, ietf_attr_product_info_create(), OS_TYPE_ANDROID, OS_TYPE_DEBIAN, OS_TYPE_FEDORA, OS_TYPE_REDHAT, OS_TYPE_UBUNTU, PEN_CANONICAL, PEN_DEBIAN, PEN_FEDORA, PEN_GOOGLE, PEN_IETF, and PEN_REDHAT.
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     os_type_t os_type;
     pen_t vendor_id = PEN_IETF;
     int i;
     typedef struct vendor_pen_t {
         os_type_t os_type;
         pen_t pen;
     } vendor_pen_t;
     vendor_pen_t vendor_pens[] = {
         { OS_TYPE_DEBIAN,  PEN_DEBIAN },
         { OS_TYPE_UBUNTU,  PEN_CANONICAL },
         { OS_TYPE_FEDORA,  PEN_FEDORA },
         { OS_TYPE_REDHAT,  PEN_REDHAT },
         { OS_TYPE_ANDROID, PEN_GOOGLE }
     };
     os_type = os->get_type(os);
     for (i = 0; i < countof(vendor_pens); i++)
     {
         if (os_type == vendor_pens[i].os_type)
         {
             vendor_id = vendor_pens[i].pen;
             break;
         }
     }
     attr = ietf_attr_product_info_create(vendor_id, 0, os->get_name(os));
     msg->add_attribute(msg, attr);
 }
static void add_settings (enumerator_t * enumerator, imc_msg_t * msg) static
Add ITA Settings attribute to the send queue
Definition at line 374 of file imc_os.c.
References ita_attr_settings_t::add, imc_msg_t::add_attribute, chunk_free(), DBG1, DBG_IMC, enumerator_t::enumerate, FALSE, imc_os_info_t::get_setting, ita_attr_settings_create(), name, chunk_t::ptr, TRUE, and value.
Referenced by receive_message().
 {
     pa_tnc_attr_t *attr = NULL;
     ita_attr_settings_t *attr_cast;
     chunk_t value;
     char *name;
     bool first = TRUE;
     while (enumerator->enumerate(enumerator, &name))
     {
         DBG1(DBG_IMC, "setting '%s'", name);
         value = os->get_setting(os, name);
         if (!value.ptr)
         {
             continue;
         }
         if (first)
         {
             attr = ita_attr_settings_create();
             first = FALSE;
         }
         attr_cast = (ita_attr_settings_t*)attr;
         attr_cast->add(attr_cast, name, value);
         chunk_free(&value);
     }
     if (attr)
     {
         msg->add_attribute(msg, attr);
     }
 }
static void add_string_version (imc_msg_t * msg) static
Add IETF String Version attribute to the send queue
Definition at line 178 of file imc_os.c.
References imc_msg_t::add_attribute, chunk_empty, imc_os_info_t::get_version, and ietf_attr_string_version_create().
Referenced by receive_message(), and TNC_IMC_BeginHandshake().
 {
     pa_tnc_attr_t *attr;
     attr = ietf_attr_string_version_create(os->get_version(os),
                                            chunk_empty, chunk_empty);
     msg->add_attribute(msg, attr);
 }
static TNC_Result receive_message (imc_state_t * state, imc_msg_t * in_msg) static
Definition at line 447 of file imc_os.c.
References add_default_pwd_enabled(), add_device_id(), add_fwd_enabled(), add_installed_packages(), add_numeric_version(), add_op_status(), add_product_info(), add_settings(), add_string_version(), imc_msg_t::create_attribute_enumerator, ita_attr_get_settings_t::create_enumerator, ietf_attr_attr_request_t::create_enumerator, enumerator_t::destroy, imc_msg_t::destroy, enumerator_t::enumerate, FALSE, pa_tnc_attr_t::get_type, IETF_ATTR_ATTRIBUTE_REQUEST, IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED, IETF_ATTR_FORWARDING_ENABLED, IETF_ATTR_INSTALLED_PACKAGES, IETF_ATTR_NUMERIC_VERSION, IETF_ATTR_OPERATIONAL_STATUS, IETF_ATTR_PRODUCT_INFORMATION, IETF_ATTR_STRING_VERSION, imc_msg_create_as_reply(), ITA_ATTR_DEVICE_ID, ITA_ATTR_GET_SETTINGS, PEN_IETF, PEN_ITA, imc_msg_t::receive, result, imc_msg_t::send, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, TRUE, type, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by TNC_IMC_ReceiveMessage(), and TNC_IMC_ReceiveMessageLong().
 {
     imc_msg_t *out_msg;
     enumerator_t *enumerator;
     pa_tnc_attr_t *attr;
     pen_type_t type;
     TNC_Result result;
     bool fatal_error = FALSE;
     /* generate an outgoing PA-TNC message - we might need it */
     out_msg = imc_msg_create_as_reply(in_msg);
     /* parse received PA-TNC message and handle local and remote errors */
     result = in_msg->receive(in_msg, out_msg, &fatal_error);
     if (result != TNC_RESULT_SUCCESS)
     {
         out_msg->destroy(out_msg);
         return result;
     }
     /* analyze PA-TNC attributes */
     enumerator = in_msg->create_attribute_enumerator(in_msg);
     while (enumerator->enumerate(enumerator, &attr))
     {
         type = attr->get_type(attr);
         if (type.vendor_id == PEN_IETF)
         {
             if (type.type == IETF_ATTR_ATTRIBUTE_REQUEST)
             {
                 ietf_attr_attr_request_t *attr_cast;
                 pen_type_t *entry;
                 enumerator_t *e;
                 attr_cast = (ietf_attr_attr_request_t*)attr;
                 e = attr_cast->create_enumerator(attr_cast);
                 while (e->enumerate(e, &entry))
                 {
                     if (entry->vendor_id == PEN_IETF)
                     {
                         switch (entry->type)
{
                             case IETF_ATTR_PRODUCT_INFORMATION:
                                 add_product_info(out_msg);
                                 break;
                             case IETF_ATTR_STRING_VERSION:
                                 add_string_version(out_msg);
                                 break;
                             case IETF_ATTR_NUMERIC_VERSION:
                                 add_numeric_version(out_msg);
                                 break;
                             case IETF_ATTR_OPERATIONAL_STATUS:
                                 add_op_status(out_msg);
                                 break;
                             case IETF_ATTR_FORWARDING_ENABLED:
                                 add_fwd_enabled(out_msg);
                                 break;
                             case IETF_ATTR_FACTORY_DEFAULT_PWD_ENABLED:
                                 add_default_pwd_enabled(out_msg);
                                 break;
                             case IETF_ATTR_INSTALLED_PACKAGES:
                                 add_installed_packages(state, out_msg);
                                 break;
                             default:
                                 break;
                         }
                     }
                     else if (entry->vendor_id == PEN_ITA)
                     {
                         switch (entry->type)
{
                             case ITA_ATTR_DEVICE_ID:
                                 add_device_id(out_msg);
                                 break;
                             default:
                                 break;
                         }
                     }
                 }
                 e->destroy(e);
             }
         }
         else if (type.vendor_id == PEN_ITA && type.type == ITA_ATTR_GET_SETTINGS)
         {
             ita_attr_get_settings_t *attr_cast;
             enumerator_t *e;
             attr_cast = (ita_attr_get_settings_t*)attr;
             e = attr_cast->create_enumerator(attr_cast);
             add_settings(e, out_msg);
             e->destroy(e);
         }
     }
     enumerator->destroy(enumerator);
     if (fatal_error)
     {
         result = TNC_RESULT_FATAL;
     }
     else
     {
         /* send PA-TNC message with the EXCL flag set */
         result = out_msg->send(out_msg, TRUE);
     }
     out_msg->destroy(out_msg);
     return result;
 }
Variable Documentation
const char imc_name[] = "OS" static
Definition at line 42 of file imc_os.c.
Referenced by TNC_IMC_BatchEnding(), TNC_IMC_BeginHandshake(), TNC_IMC_Initialize(), TNC_IMC_NotifyConnectionChange(), TNC_IMC_ProvideBindFunction(), TNC_IMC_ReceiveMessage(), TNC_IMC_ReceiveMessageLong(), and TNC_IMC_Terminate().
imc_agent_t* imc_os static
Definition at line 48 of file imc_os.c.
pen_type_t msg_types[] static
Initial value:
= {
    { PEN_IETF, PA_SUBTYPE_IETF_OPERATING_SYSTEM }
}
Definition at line 44 of file imc_os.c.
imc_os_info_t* os static
Definition at line 49 of file imc_os.c.