strongSwan: imv_agent.c File Reference
imv_agent.c File Reference
#include "imcv.h"
#include "imv_agent.h"
#include "imv_session.h"
#include "ietf/ietf_attr_assess_result.h"
#include <tncif_names.h>
#include <tncif_identity.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <bio/bio_reader.h>
#include <threading/rwlock.h>
Classes
struct private_imv_agent_t
struct language_enumerator_t
Typedefs
typedef struct private_imv_agent_t private_imv_agent_t
Functions
METHOD (imv_agent_t, bind_functions, TNC_Result, private_imv_agent_t *this, TNC_TNCS_BindFunctionPointer bind_function)
static imv_state_t * find_connection (private_imv_agent_t *this, TNC_ConnectionID id)
static bool delete_connection (private_imv_agent_t *this, TNC_ConnectionID id)
static bool get_bool_attribute (private_imv_agent_t *this, TNC_ConnectionID id, TNC_AttributeID attribute_id)
static char * get_str_attribute (private_imv_agent_t *this, TNC_ConnectionID id, TNC_AttributeID attribute_id)
static uint32_t get_uint_attribute (private_imv_agent_t *this, TNC_ConnectionID id, TNC_AttributeID attribute_id)
static linked_list_t * get_identity_attribute (private_imv_agent_t *this, TNC_ConnectionID id, TNC_AttributeID attribute_id)
METHOD (imv_agent_t, create_state, TNC_Result, private_imv_agent_t *this, imv_state_t *state)
METHOD (imv_agent_t, delete_state, TNC_Result, private_imv_agent_t *this, TNC_ConnectionID connection_id)
METHOD (imv_agent_t, change_state, TNC_Result, private_imv_agent_t *this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imv_state_t **state_p)
METHOD (imv_agent_t, get_state, bool, private_imv_agent_t *this, TNC_ConnectionID connection_id, imv_state_t **state)
METHOD (imv_agent_t, get_name, const char *, private_imv_agent_t *this)
METHOD (imv_agent_t, get_id, TNC_IMVID, private_imv_agent_t *this)
METHOD (imv_agent_t, reserve_additional_ids, TNC_Result, private_imv_agent_t *this, int count)
METHOD (imv_agent_t, count_additional_ids, int, private_imv_agent_t *this)
METHOD (imv_agent_t, create_id_enumerator, enumerator_t *, private_imv_agent_t *this)
static void language_enumerator_destroy (language_enumerator_t *this)
static bool language_enumerator_enumerate (language_enumerator_t *this,...)
METHOD (imv_agent_t, create_language_enumerator, enumerator_t *, private_imv_agent_t *this, imv_state_t *state)
METHOD (imv_agent_t, provide_recommendation, TNC_Result, private_imv_agent_t *this, imv_state_t *state)
METHOD (imv_agent_t, add_non_fatal_attr_type, void, private_imv_agent_t *this, pen_type_t type)
METHOD (imv_agent_t, get_non_fatal_attr_types, linked_list_t *, private_imv_agent_t *this)
METHOD (imv_agent_t, destroy, void, private_imv_agent_t *this)
imv_agent_t * imv_agent_create (const char *name, pen_type_t *supported_types, uint32_t type_count, TNC_IMVID id, TNC_Version *actual_version)
Typedef Documentation
typedef struct private_imv_agent_t private_imv_agent_t
Definition at line 30 of file imv_agent.c.
Function Documentation
static bool delete_connection (private_imv_agent_t * this, TNC_ConnectionID id) static
delete a connection state with a given Connection ID
Definition at line 289 of file imv_agent.c.
References enumerator_t::destroy, imv_state_t::destroy, enumerator_t::enumerate, FALSE, found, imv_state_t::get_connection_id, imv_state_t::get_session, imcv_sessions, imv_session_manager_t::remove_session, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     imv_state_t *state;
     imv_session_t *session;
     bool found = FALSE;
     this->connection_lock->write_lock(this->connection_lock);
     enumerator = this->connections->create_enumerator(this->connections);
     while (enumerator->enumerate(enumerator, &state))
     {
         if (id == state->get_connection_id(state))
         {
             found = TRUE;
             session = state->get_session(state);
             imcv_sessions->remove_session(imcv_sessions, session);
             state->destroy(state);
             this->connections->remove_at(this->connections, enumerator);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->connection_lock->unlock(this->connection_lock);
     return found;
 }
static imv_state_t* find_connection (private_imv_agent_t * this, TNC_ConnectionID id) static
finds a connection state based on its Connection ID
Definition at line 264 of file imv_agent.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, and imv_state_t::get_connection_id.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     imv_state_t *state, *found = NULL;
     this->connection_lock->read_lock(this->connection_lock);
     enumerator = this->connections->create_enumerator(this->connections);
     while (enumerator->enumerate(enumerator, &state))
     {
         if (id == state->get_connection_id(state))
         {
             found = state;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->connection_lock->unlock(this->connection_lock);
     return found;
 }
static bool get_bool_attribute (private_imv_agent_t * this, TNC_ConnectionID id, TNC_AttributeID attribute_id) static
Read a boolean attribute
Definition at line 319 of file imv_agent.c.
References len, and TNC_RESULT_SUCCESS.
Referenced by METHOD().
 {
     TNC_UInt32 len;
     char buf[4];
     return this->get_attribute  &&
            this->get_attribute(this->id, id, attribute_id, 4, buf, &len) ==
                                TNC_RESULT_SUCCESS && len == 1 && *buf == 0x01;
  }
static linked_list_t* get_identity_attribute (private_imv_agent_t * this, TNC_ConnectionID id, TNC_AttributeID attribute_id) static
Read a TNC identity attribute
Definition at line 369 of file imv_agent.c.
References bio_reader_create(), chunk_create(), count, tncif_identity_t::destroy, bio_reader_t::destroy, end, linked_list_t::insert_last, len, linked_list_create(), list, tncif_identity_t::process, bio_reader_t::read_uint32, TNC_RESULT_SUCCESS, and tncif_identity_create_empty().
Referenced by METHOD().
 {
     TNC_UInt32 len;
     char buf[2048];
     uint32_t count;
     tncif_identity_t *tnc_id;
     bio_reader_t *reader;
     linked_list_t *list;
     list = linked_list_create();
     if (!this->get_attribute ||
          this->get_attribute(this->id, id, attribute_id, sizeof(buf), buf, &len)
                 != TNC_RESULT_SUCCESS || len > sizeof(buf))
     {
         return list;
     }
     reader = bio_reader_create(chunk_create(buf, len));
     if (!reader->read_uint32(reader, &count))
     {
             goto end;
     }
     while (count--)
     {
         tnc_id = tncif_identity_create_empty();
         if (!tnc_id->process(tnc_id, reader))
         {
             tnc_id->destroy(tnc_id);
             goto end;
         }
         list->insert_last(list, tnc_id);
     }
 end:
     reader->destroy(reader);
     return list;
  }
static char* get_str_attribute (private_imv_agent_t * this, TNC_ConnectionID id, TNC_AttributeID attribute_id) static
Read a string attribute
Definition at line 333 of file imv_agent.c.
References BUF_LEN, len, strdup, and TNC_RESULT_SUCCESS.
Referenced by METHOD().
 {
     TNC_UInt32 len;
     char buf[BUF_LEN];
     if (this->get_attribute  &&
         this->get_attribute(this->id, id, attribute_id, BUF_LEN, buf, &len) ==
                             TNC_RESULT_SUCCESS && len <= BUF_LEN)
     {
         return strdup(buf);
     }
     return NULL;
  }
static uint32_t get_uint_attribute (private_imv_agent_t * this, TNC_ConnectionID id, TNC_AttributeID attribute_id) static
Read an UInt32 attribute
Definition at line 351 of file imv_agent.c.
References len, TNC_RESULT_SUCCESS, and untoh32().
Referenced by METHOD().
 {
     TNC_UInt32 len;
     char buf[4];
     if (this->get_attribute  &&
         this->get_attribute(this->id, id, attribute_id, 4, buf, &len) ==
                             TNC_RESULT_SUCCESS && len == 4)
     {
         return untoh32(buf);
     }
     return 0;
  }
static void language_enumerator_destroy (language_enumerator_t * this) static
Implementation of language_enumerator.destroy.
Definition at line 632 of file imv_agent.c.
References free().
Referenced by METHOD().
 {
     free(this);
 }
static bool language_enumerator_enumerate (language_enumerator_t * this, ...) static
Implementation of language_enumerator.enumerate
Definition at line 640 of file imv_agent.c.
References FALSE, len, and TRUE.
Referenced by METHOD().
 {
     char *pos, *cur_lang, **lang;
     TNC_UInt32 len;
     va_list args;
     if (!this->lang_len)
     {
         return FALSE;
     }
     cur_lang = this->lang_pos;
     pos = strchr(this->lang_pos, ',');
     if (pos)
     {
         len = pos - this->lang_pos;
         this->lang_pos += len + 1,
         this->lang_len -= len + 1;
     }
     else
     {
         len = this->lang_len;
         pos = this->lang_pos + len;
         this->lang_pos = NULL;
         this->lang_len = 0;
     }
     /* remove preceding whitespace */
     while (*cur_lang == ' ' && len--)
     {
         cur_lang++;
     }
     /* remove trailing whitespace */
     while (len && *(--pos) == ' ')
     {
         len--;
     }
     cur_lang[len] = '\0';
     va_start(args, this);
     lang = va_arg(args, char**);
     *lang = cur_lang;
     va_end(args);
     return TRUE;
 }
METHOD (imv_agent_t , bind_functions , TNC_Result , private_imv_agent_t * this, TNC_TNCS_BindFunctionPointer bind_function)
Definition at line 170 of file imv_agent.c.
References DBG1, DBG_IMV, free(), malloc(), send_message(), TNC_RESULT_INVALID_PARAMETER, TNC_RESULT_SUCCESS, and type.
 {
     if (!bind_function)
     {
         DBG1(DBG_IMV, "TNC server failed to provide bind function");
         return TNC_RESULT_INVALID_PARAMETER;
     }
     if (bind_function(this->id, "TNC_TNCS_ReportMessageTypes",
             (void**)&this->report_message_types) != TNC_RESULT_SUCCESS)
     {
         this->report_message_types = NULL;
     }
     if (bind_function(this->id, "TNC_TNCS_ReportMessageTypesLong",
             (void**)&this->report_message_types_long) != TNC_RESULT_SUCCESS)
     {
         this->report_message_types_long = NULL;
     }
     if (bind_function(this->id, "TNC_TNCS_RequestHandshakeRetry",
             (void**)&this->public.request_handshake_retry) != TNC_RESULT_SUCCESS)
     {
         this->public.request_handshake_retry = NULL;
     }
     if (bind_function(this->id, "TNC_TNCS_SendMessage",
             (void**)&this->public.send_message) != TNC_RESULT_SUCCESS)
     {
         this->public.send_message = NULL;
     }
     if (bind_function(this->id, "TNC_TNCS_SendMessageLong",
             (void**)&this->public.send_message_long) != TNC_RESULT_SUCCESS)
     {
         this->public.send_message_long = NULL;
     }
     if (bind_function(this->id, "TNC_TNCS_ProvideRecommendation",
             (void**)&this->provide_recommendation) != TNC_RESULT_SUCCESS)
     {
         this->provide_recommendation = NULL;
     }
     if (bind_function(this->id, "TNC_TNCS_GetAttribute",
             (void**)&this->get_attribute) != TNC_RESULT_SUCCESS)
     {
         this->get_attribute = NULL;
     }
     if (bind_function(this->id, "TNC_TNCS_SetAttribute",
             (void**)&this->set_attribute) != TNC_RESULT_SUCCESS)
     {
         this->set_attribute = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_ReserveAdditionalIMVID",
             (void**)&this->reserve_additional_id) != TNC_RESULT_SUCCESS)
     {
         this->reserve_additional_id = NULL;
     }
     if (this->report_message_types_long)
     {
         TNC_VendorIDList vendor_id_list;
         TNC_MessageSubtypeList subtype_list;
         int i;
         vendor_id_list = malloc(this->type_count * sizeof(TNC_UInt32));
         subtype_list   = malloc(this->type_count * sizeof(TNC_UInt32));
         for (i = 0; i < this->type_count; i++)
         {
             vendor_id_list[i] = this->supported_types[i].vendor_id;
             subtype_list[i]   = this->supported_types[i].type;
         }
         this->report_message_types_long(this->id, vendor_id_list, subtype_list,
                                         this->type_count);
         free(vendor_id_list);
         free(subtype_list);
     }
     else if (this->report_message_types)
     {
         TNC_MessageTypeList type_list;
         int i;
         type_list = malloc(this->type_count * sizeof(TNC_UInt32));
         for (i = 0; i < this->type_count; i++)
         {
             type_list[i] = (this->supported_types[i].vendor_id << 8) |
                            (this->supported_types[i].type & 0xff);
         }
         this->report_message_types(this->id, type_list, this->type_count);
         free(type_list);
     }
     return TNC_RESULT_SUCCESS;
 }
METHOD (imv_agent_t , create_state , TNC_Result , private_imv_agent_t * this, imv_state_t * state)
Definition at line 410 of file imv_agent.c.
References imv_session_manager_t::add_session, DBG1, DBG2, DBG_IMV, imv_state_t::destroy, FALSE, find_connection(), free(), get_bool_attribute(), imv_state_t::get_connection_id, get_identity_attribute(), get_str_attribute(), get_uint_attribute(), imcv_sessions, name, imv_state_t::set_flags, imv_state_t::set_max_msg_len, imv_state_t::set_session, TNC_ATTRIBUTEID_AR_IDENTITIES, TNC_ATTRIBUTEID_HAS_EXCLUSIVE, TNC_ATTRIBUTEID_HAS_LONG_TYPES, TNC_ATTRIBUTEID_HAS_SOH, TNC_ATTRIBUTEID_IFT_PROTOCOL, TNC_ATTRIBUTEID_IFT_VERSION, TNC_ATTRIBUTEID_IFTNCCS_PROTOCOL, TNC_ATTRIBUTEID_IFTNCCS_VERSION, TNC_ATTRIBUTEID_MAX_MESSAGE_SIZE, TNC_RESULT_OTHER, and TNC_RESULT_SUCCESS.
 {
     TNC_ConnectionID conn_id;
     char *tnccs_p = NULL, *tnccs_v = NULL, *t_p = NULL, *t_v = NULL;
     bool has_long = FALSE, has_excl = FALSE, has_soh = FALSE;
     linked_list_t *ar_identities;
     imv_session_t *session;
     uint32_t max_msg_len;
     conn_id = state->get_connection_id(state);
     if (find_connection(this, conn_id))
     {
         DBG1(DBG_IMV, "IMV %u \"%s\" already created a state for Connection ID %u",
                        this->id, this->name, conn_id);
         state->destroy(state);
         return TNC_RESULT_OTHER;
     }
     /* Get and display attributes from TNCS via IF-IMV */
     has_long = get_bool_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_HAS_LONG_TYPES);
     has_excl = get_bool_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_HAS_EXCLUSIVE);
     has_soh  = get_bool_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_HAS_SOH);
     tnccs_p = get_str_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_IFTNCCS_PROTOCOL);
     tnccs_v = get_str_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_IFTNCCS_VERSION);
     t_p = get_str_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_IFT_PROTOCOL);
     t_v = get_str_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_IFT_VERSION);
     max_msg_len = get_uint_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_MAX_MESSAGE_SIZE);
     ar_identities = get_identity_attribute(this, conn_id,
                                     TNC_ATTRIBUTEID_AR_IDENTITIES);
     state->set_flags(state, has_long, has_excl);
     state->set_max_msg_len(state, max_msg_len);
     DBG2(DBG_IMV, "IMV %u \"%s\" created a state for %s %s Connection ID %u: "
                   "%slong %sexcl %ssoh", this->id, this->name,
                   tnccs_p ? tnccs_p:"?", tnccs_v ? tnccs_v:"?", conn_id,
                   has_long ? "+":"-", has_excl ? "+":"-", has_soh ? "+":"-");
     DBG2(DBG_IMV, "  over %s %s with maximum PA-TNC message size of %u bytes",
                   t_p ? t_p:"?", t_v ? t_v :"?", max_msg_len);
     session = imcv_sessions->add_session(imcv_sessions, conn_id, ar_identities);
     state->set_session(state, session);
     free(tnccs_p);
     free(tnccs_v);
     free(t_p);
     free(t_v);
     /* insert state in connection list */
     this->connection_lock->write_lock(this->connection_lock);
     this->connections->insert_last(this->connections, state);
     this->connection_lock->unlock(this->connection_lock);
     return TNC_RESULT_SUCCESS;
 }
METHOD (imv_agent_t , delete_state , TNC_Result , private_imv_agent_t * this, TNC_ConnectionID connection_id)
Definition at line 475 of file imv_agent.c.
References DBG1, DBG2, DBG_IMV, delete_connection(), name, TNC_RESULT_FATAL, and TNC_RESULT_SUCCESS.
 {
     if (!delete_connection(this, connection_id))
     {
         DBG1(DBG_IMV, "IMV %u \"%s\" has no state for Connection ID %u",
                       this->id, this->name, connection_id);
         return TNC_RESULT_FATAL;
     }
     DBG2(DBG_IMV, "IMV %u \"%s\" deleted the state of Connection ID %u",
                   this->id, this->name, connection_id);
     return TNC_RESULT_SUCCESS;
 }
METHOD (imv_agent_t , change_state , TNC_Result , private_imv_agent_t * this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imv_state_t ** state_p)
Definition at line 489 of file imv_agent.c.
References imv_state_t::change_state, DBG1, DBG2, DBG_IMV, find_connection(), name, TNC_CONNECTION_STATE_ACCESS_ALLOWED, TNC_CONNECTION_STATE_ACCESS_ISOLATED, TNC_CONNECTION_STATE_ACCESS_NONE, TNC_CONNECTION_STATE_CREATE, TNC_CONNECTION_STATE_DELETE, TNC_CONNECTION_STATE_HANDSHAKE, TNC_Connection_State_names, TNC_RESULT_FATAL, TNC_RESULT_INVALID_PARAMETER, and TNC_RESULT_SUCCESS.
 {
     imv_state_t *state;
     switch (new_state)
     {
         case TNC_CONNECTION_STATE_HANDSHAKE:
         case TNC_CONNECTION_STATE_ACCESS_ALLOWED:
         case TNC_CONNECTION_STATE_ACCESS_ISOLATED:
         case TNC_CONNECTION_STATE_ACCESS_NONE:
             state = find_connection(this, connection_id);
             if (!state)
             {
                 DBG1(DBG_IMV, "IMV %u \"%s\" has no state for Connection ID %u",
                               this->id, this->name, connection_id);
                 return TNC_RESULT_FATAL;
             }
             state->change_state(state, new_state);
             DBG2(DBG_IMV, "IMV %u \"%s\" changed state of Connection ID %u to '%N'",
                           this->id, this->name, connection_id,
                           TNC_Connection_State_names, new_state);
             if (state_p)
             {
                 *state_p = state;
             }
             break;
         case TNC_CONNECTION_STATE_CREATE:
             DBG1(DBG_IMV, "state '%N' should be handled by create_state()",
                           TNC_Connection_State_names, new_state);
                 return TNC_RESULT_FATAL;
         case TNC_CONNECTION_STATE_DELETE:
             DBG1(DBG_IMV, "state '%N' should be handled by delete_state()",
                           TNC_Connection_State_names, new_state);
                 return TNC_RESULT_FATAL;
         default:
             DBG1(DBG_IMV, "IMV %u \"%s\" was notified of unknown state %u "
                           "for Connection ID %u",
                           this->id, this->name, new_state, connection_id);
             return TNC_RESULT_INVALID_PARAMETER;
     }
     return TNC_RESULT_SUCCESS;
 }
METHOD (imv_agent_t , get_state , bool , private_imv_agent_t * this, TNC_ConnectionID connection_id, imv_state_t ** state)
Definition at line 535 of file imv_agent.c.
References DBG1, DBG_IMV, FALSE, find_connection(), name, and TRUE.
 {
     *state = find_connection(this, connection_id);
     if (!*state)
     {
         DBG1(DBG_IMV, "IMV %u \"%s\" has no state for Connection ID %u",
                       this->id, this->name, connection_id);
         return FALSE;
     }
     return TRUE;
 }
METHOD (imv_agent_t , get_name , const char * , private_imv_agent_t * this)
Definition at line 549 of file imv_agent.c.
References name.
 {
     return  this->name;
 }
METHOD (imv_agent_t , get_id , TNC_IMVID , private_imv_agent_t * this)
Definition at line 555 of file imv_agent.c.
References id.
 {
     return  this->id;
 }
METHOD (imv_agent_t , reserve_additional_ids , TNC_Result , private_imv_agent_t * this, int count)
Definition at line 561 of file imv_agent.c.
References DBG1, DBG2, DBG_IMV, id, name, result, TNC_RESULT_ILLEGAL_OPERATION, and TNC_RESULT_SUCCESS.
 {
     TNC_Result result;
     TNC_UInt32 id;
     void *pointer;
     if (!this->reserve_additional_id)
     {
         DBG1(DBG_IMV, "IMV %u \"%s\" did not detect the capability to reserve "
                       "additional IMV IDs from the TNCS", this->id, this->name);
         return TNC_RESULT_ILLEGAL_OPERATION;
     }
     while (count > 0)
     {
         result = this->reserve_additional_id(this->id, &id);
         if (result != TNC_RESULT_SUCCESS)
         {
             DBG1(DBG_IMV, "IMV %u \"%s\" failed to reserve %d additional IMV IDs",
                           this->id, this->name, count);
             return result;
         }
         count--;
         /* store the scalar value in the pointer */
         pointer = (void*)(uintptr_t)id;
         this->additional_ids->insert_last(this->additional_ids, pointer);
         DBG2(DBG_IMV, "IMV %u \"%s\" reserved additional ID %u",
                       this->id, this->name, id);
     }
     return TNC_RESULT_SUCCESS;
 }
METHOD (imv_agent_t , count_additional_ids , int , private_imv_agent_t * this)
Definition at line 594 of file imv_agent.c.
 {
     return  this->additional_ids->get_count(this->additional_ids);
 }
METHOD (imv_agent_t , create_id_enumerator , enumerator_t * , private_imv_agent_t * this)
Definition at line 600 of file imv_agent.c.
 {
     return this->additional_ids->create_enumerator(this->additional_ids);
 }
METHOD (imv_agent_t , create_language_enumerator , enumerator_t * , private_imv_agent_t * this, imv_state_t * state)
Definition at line 687 of file imv_agent.c.
References BUF_LEN, enumerator_t::destroy, enumerator_t::enumerate, imv_state_t::get_connection_id, language_enumerator_t::lang_buf, language_enumerator_t::lang_len, language_enumerator_t::lang_pos, language_enumerator_destroy(), language_enumerator_enumerate(), malloc_thing, language_enumerator_t::public, TNC_ATTRIBUTEID_PREFERRED_LANGUAGE, and TNC_RESULT_SUCCESS.
 {
     language_enumerator_t *e;
     /* Create a language enumerator instance */
     e = malloc_thing(language_enumerator_t);
     e->public.enumerate = (void*)language_enumerator_enumerate;
     e->public.destroy = (void*)language_enumerator_destroy;
     if (!this->get_attribute ||
         !this->get_attribute(this->id, state->get_connection_id(state),
                         TNC_ATTRIBUTEID_PREFERRED_LANGUAGE, BUF_LEN,
                         e->lang_buf, &e->lang_len) == TNC_RESULT_SUCCESS ||
         e->lang_len >= BUF_LEN)
     {
         e->lang_len = 0;
     }
     e->lang_buf[e->lang_len] = '\0';
     e->lang_pos = e->lang_buf;
     return (enumerator_t*)e;
 }
METHOD (imv_agent_t , provide_recommendation , TNC_Result , private_imv_agent_t * this, imv_state_t * state)
Definition at line 711 of file imv_agent.c.
References enumerator_t::destroy, imv_state_t::get_connection_id, imv_state_t::get_reason_string, imv_state_t::get_recommendation, chunk_t::len, chunk_t::ptr, TNC_ATTRIBUTEID_REASON_LANGUAGE, TNC_ATTRIBUTEID_REASON_STRING, and TNC_IMV_ACTION_RECOMMENDATION_ALLOW.
 {
     TNC_IMV_Action_Recommendation rec;
     TNC_IMV_Evaluation_Result eval;
     TNC_ConnectionID connection_id;
     chunk_t reason_string;
     char *reason_lang;
     enumerator_t *e;
     state->get_recommendation(state, &rec, &eval);
     connection_id = state->get_connection_id(state);
     /* send a reason string if action recommendation is not allow */
     if (rec != TNC_IMV_ACTION_RECOMMENDATION_ALLOW)
     {
         /* find a reason string for the preferred language and set it */
         if (this->set_attribute)
         {
             e = create_language_enumerator(this, state);
             if (state->get_reason_string(state, e, &reason_string, &reason_lang))
             {
                 this->set_attribute(this->id, connection_id,
                                     TNC_ATTRIBUTEID_REASON_STRING,
                                     reason_string.len, reason_string.ptr);
                 this->set_attribute(this->id, connection_id,
                                     TNC_ATTRIBUTEID_REASON_LANGUAGE,
                                     strlen(reason_lang), reason_lang);
             }
             e->destroy(e);
         }
     }
     return this->provide_recommendation(this->id, connection_id, rec, eval);
 }
METHOD (imv_agent_t , add_non_fatal_attr_type , void , private_imv_agent_t * this, pen_type_t type)
Definition at line 746 of file imv_agent.c.
References malloc_thing, and type.
 {
     pen_type_t *type_p;
     type_p = malloc_thing(pen_type_t);
     *type_p = type;
     this->non_fatal_attr_types->insert_last(this->non_fatal_attr_types, type_p);
 }
METHOD (imv_agent_t , get_non_fatal_attr_types , linked_list_t * , private_imv_agent_t * this)
Definition at line 756 of file imv_agent.c.
 {
     return this->non_fatal_attr_types;
 }
METHOD (imv_agent_t , destroy , void , private_imv_agent_t * this)
Definition at line 762 of file imv_agent.c.
References DBG1, DBG_IMV, destroy(), free(), libimcv_deinit(), and name.
 {
     DBG1(DBG_IMV, "IMV %u \"%s\" terminated", this->id, this->name);
     this->additional_ids->destroy(this->additional_ids);
     this->non_fatal_attr_types->destroy_function(this->non_fatal_attr_types,
                                                  free);
     this->connections->destroy_offset(this->connections,
                                       offsetof(imv_state_t, destroy));
     this->connection_lock->destroy(this->connection_lock);
     free(this);
     /* decrease the reference count or terminate */
     libimcv_deinit();
 }