strongSwan: traffic_selector_t Struct Reference
traffic_selector_t Struct Reference
traffic_selector
#include "traffic_selector.h"
Public Attributes
traffic_selector_t *(* get_subset)(traffic_selector_t *this, traffic_selector_t *other)
traffic_selector_t *(* clone)(traffic_selector_t *this)
chunk_t(* get_from_address)(traffic_selector_t *this)
chunk_t(* get_to_address)(traffic_selector_t *this)
u_int16_t(* get_from_port)(traffic_selector_t *this)
u_int16_t(* get_to_port)(traffic_selector_t *this)
ts_type_t(* get_type)(traffic_selector_t *this)
u_int8_t(* get_protocol)(traffic_selector_t *this)
bool(* is_host)(traffic_selector_t *this, host_t *host)
bool(* is_dynamic)(traffic_selector_t *this)
void(* set_address)(traffic_selector_t *this, host_t *host)
bool(* equals)(traffic_selector_t *this, traffic_selector_t *other)
bool(* is_contained_in)(traffic_selector_t *this, traffic_selector_t *other)
bool(* includes)(traffic_selector_t *this, host_t *host)
bool(* to_subnet)(traffic_selector_t *this, host_t **net, u_int8_t *mask)
u_int(* hash)(traffic_selector_t *this, u_int inc)
void(* destroy)(traffic_selector_t *this)
Detailed Description
Object representing a traffic selector entry.
A traffic selector defines an range of addresses and a range of ports.
If the protocol is ICMP or ICMPv6 the ICMP type and code are stored in the port field as follows: The message type is placed in the most significant 8 bits and the code in the least significant 8 bits. Utility functions are provided to extract the individual values.
Definition at line 72 of file traffic_selector.h.
Member Data Documentation
traffic_selector_t*(* traffic_selector_t::clone)(traffic_selector_t *this)
Clone a traffic selector.
Returns
clone of it
Definition at line 93 of file traffic_selector.h.
Referenced by acquire(), add_entry(), add_exclude_async(), add_trap(), array_from_ts_list(), child_create_create(), get_transport_nat_ts(), ipsec_policy_create(), METHOD(), policy_sa_create(), process_child_add(), quick_mode_create(), select_ts(), and verify_clone().
void(* traffic_selector_t::destroy)(traffic_selector_t *this)
Destroys the ts object
Definition at line 234 of file traffic_selector.h.
Referenced by flush_ts_list(), get_ts(), get_ts_match(), install_ipip_ale(), install_route(), METHOD(), narrow_initiator(), narrow_pre(), narrow_responder_post(), policy_sa_destroy(), remove_exclude(), remove_include(), sp_entry_destroy(), START_TEST(), verify_address(), and verify_clone().
bool(* traffic_selector_t::equals)(traffic_selector_t *this, traffic_selector_t *other)
Compare two traffic selectors for equality.
Parameters
other ts to compare with this
Returns
TRUE if equal, FALSE otherwise
Definition at line 191 of file traffic_selector.h.
Referenced by check_for_rekeyed_child(), get_ts_match(), have_equal_ts(), METHOD(), remove_include(), remove_trap(), START_TEST(), ts_array_equals(), and verify_clone().
chunk_t(* traffic_selector_t::get_from_address)(traffic_selector_t *this)
Get starting address of this ts as a chunk.
Chunk is in network order and points to internal data.
Returns
chunk containing the address
Definition at line 102 of file traffic_selector.h.
Referenced by id_payload_create_from_ts(), METHOD(), traffic_selector_substructure_create_from_traffic_selector(), ts2condition(), verify_address(), and verify_clone().
u_int16_t(* traffic_selector_t::get_from_port)(traffic_selector_t *this)
Get starting port of this ts.
Port is in host order, since the parser converts it.
If the protocol is ICMP/ICMPv6 the ICMP type and code are stored in this field as follows: The message type is placed in the most significant 8 bits and the code in the least significant 8 bits. Use the utility functions to extract them.
Returns
port
Definition at line 125 of file traffic_selector.h.
Referenced by get_port(), id_payload_create_from_ts(), METHOD(), START_TEST(), traffic_selector_substructure_create_from_traffic_selector(), ts2condition(), ts2ports(), and verify_clone().
u_int8_t(* traffic_selector_t::get_protocol)(traffic_selector_t *this)
Get the protocol id of this ts.
Returns
protocol id
Definition at line 153 of file traffic_selector.h.
Referenced by calculate_priority(), create_policy_entry(), get_port(), id_payload_create_from_ts(), install_shunt_policy(), invoke_once(), ipsec_policy_create(), METHOD(), traffic_selector_substructure_create_from_traffic_selector(), ts2condition(), ts2selector(), uninstall_shunt_policy(), and verify_clone().
traffic_selector_t*(* traffic_selector_t::get_subset)(traffic_selector_t *this, traffic_selector_t *other)
Compare two traffic selectors, and create a new one which is the largest subset of both (subnet & port).
Resulting traffic_selector is newly created and must be destroyed.
Parameters
other traffic selector to compare
Returns
created subset of them
or NULL if no match between this and other
Definition at line 85 of file traffic_selector.h.
Referenced by get_ts(), get_ts_match(), METHOD(), and START_TEST().
chunk_t(* traffic_selector_t::get_to_address)(traffic_selector_t *this)
Get ending address of this ts as a chunk.
Chunk is in network order and points to internal data.
Returns
chunk containing the address
Definition at line 111 of file traffic_selector.h.
Referenced by id_payload_create_from_ts(), METHOD(), traffic_selector_substructure_create_from_traffic_selector(), ts2condition(), verify_address(), and verify_clone().
u_int16_t(* traffic_selector_t::get_to_port)(traffic_selector_t *this)
Get ending port of this ts.
Port is in host order, since the parser converts it.
If the protocol is ICMP/ICMPv6 the ICMP type and code are stored in this field as follows: The message type is placed in the most significant 8 bits and the code in the least significant 8 bits. Use the utility functions to extract them.
Returns
port
Definition at line 139 of file traffic_selector.h.
Referenced by METHOD(), START_TEST(), traffic_selector_substructure_create_from_traffic_selector(), ts2condition(), ts2ports(), and verify_clone().
ts_type_t(* traffic_selector_t::get_type)(traffic_selector_t *this)
Get the type of the traffic selector.
Returns
ts_type_t specifying the type
Definition at line 146 of file traffic_selector.h.
Referenced by create_child_cfg(), id_payload_create_from_ts(), install_route(), install_shunt_policy(), install_sp(), install_sps(), install_trap(), invoke_once(), METHOD(), traffic_selector_substructure_create_from_traffic_selector(), ts2condition(), ts2in(), ts2selector(), uninstall_shunt_policy(), use_ts(), verify_clone(), and write_networks().
u_int(* traffic_selector_t::hash)(traffic_selector_t *this, u_int inc)
Create a hash value for the traffic selector.
Parameters
inc optional value for incremental hashing
Returns
calculated hash value for the traffic selector
Definition at line 229 of file traffic_selector.h.
Referenced by hash_ts_array(), and START_TEST().
bool(* traffic_selector_t::includes)(traffic_selector_t *this, host_t *host)
Check if a specific host is included in the address range of this traffic selector.
Parameters
host the host to check
Definition at line 209 of file traffic_selector.h.
Referenced by install_route(), match(), METHOD(), receive_casts(), and START_TEST().
bool(* traffic_selector_t::is_contained_in)(traffic_selector_t *this, traffic_selector_t *other)
Check if a traffic selector is contained completly in another.
contains() allows to check if multiple traffic selectors are redundant.
Parameters
other ts that contains this
Returns
TRUE if other contains this completly, FALSE otherwise
Definition at line 201 of file traffic_selector.h.
Referenced by check_addrblock(), check_constraints(), install_route(), METHOD(), and START_TEST().
bool(* traffic_selector_t::is_dynamic)(traffic_selector_t *this)
Check if a traffic selector has been created by create_dynamic().
Returns
TRUE if TS is dynamic
Definition at line 173 of file traffic_selector.h.
Referenced by METHOD(), START_TEST(), use_ts(), and verify_clone().
bool(* traffic_selector_t::is_host)(traffic_selector_t *this, host_t *host)
Check if the traffic selector is for a single host.
Traffic selector may describe the end of *-to-host tunnel. In this case, the address range is a single address equal to the hosts peer address. If host is NULL, the traffic selector is checked if it is a single host, but not a specific one.
Parameters
host host_t specifying the address range
Definition at line 166 of file traffic_selector.h.
Referenced by get_proxy_addr(), get_transport_nat_ts(), get_ts(), id_payload_create_from_ts(), install_route(), install_sps(), invoke_once(), METHOD(), START_TEST(), ts2condition(), ts_list_is_host(), and verify_clone().
void(* traffic_selector_t::set_address)(traffic_selector_t *this, host_t *host)
Update the address of a traffic selector.
Update the address range of a traffic selector, if it is constructed with the traffic_selector_create_dynamic().
Parameters
host host_t specifying the address
Definition at line 183 of file traffic_selector.h.
Referenced by get_transport_nat_ts(), get_ts(), METHOD(), and START_TEST().
bool(* traffic_selector_t::to_subnet)(traffic_selector_t *this, host_t **net, u_int8_t *mask)
Convert a traffic selector address range to a subnet and its net mask. If from and to ports of this traffic selector are equal, the port of the returned host_t is set to that port.
Parameters
net converted subnet (has to be freed)
mask converted net mask
Returns
TRUE if traffic selector matches exactly to the subnet
Definition at line 221 of file traffic_selector.h.
Referenced by append_ts(), calculate_priority(), create_policy_entry(), get_proxy_addr(), get_transport_nat_ts(), id_payload_create_from_ts(), invoke_once(), manage_route(), match(), METHOD(), START_TEST(), ts2condition(), ts2in(), ts2subnet(), and use_ts().
The documentation for this struct was generated from the following file:
traffic_selector.h