strongSwan: id_manager_tests.c File Reference
id_manager_tests.c File Reference
#include <tests/test_suite.h>
#include "tkm_id_manager.h"
Functions
START_TEST (test_id_mgr_creation)
END_TEST START_TEST (test_acquire_id)
END_TEST START_TEST (test_acquire_id_invalid_kind)
END_TEST START_TEST (test_acquire_id_same)
END_TEST START_TEST (test_release_id)
END_TEST START_TEST (test_release_id_invalid_kind)
END_TEST START_TEST (test_release_id_nonexistent)
END_TEST Suite * make_id_manager_tests ()
Variables
static const tkm_limits_t limits = {125, 100, 55, 30, 200, 42}
Function Documentation
END_TEST Suite* make_id_manager_tests ()
Definition at line 138 of file id_manager_tests.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("context id manager");
     tc = tcase_create("creation");
     tcase_add_test(tc, test_id_mgr_creation);
     suite_add_tcase(s, tc);
     tc = tcase_create("acquire");
     tcase_add_test(tc, test_acquire_id);
     tcase_add_test(tc, test_acquire_id_invalid_kind);
     tcase_add_test(tc, test_acquire_id_same);
     suite_add_tcase(s, tc);
     tc = tcase_create("release");
     tcase_add_test(tc, test_release_id);
     tcase_add_test(tc, test_release_id_invalid_kind);
     tcase_add_test(tc, test_release_id_nonexistent);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_id_mgr_creation)
Definition at line 23 of file id_manager_tests.c.
References tkm_id_manager_t::destroy, fail_if, limits, and tkm_id_manager_create().
 {
     tkm_id_manager_t *idmgr = NULL;
     idmgr = tkm_id_manager_create(limits);
     fail_if(idmgr == NULL, "Error creating tkm id manager");
     idmgr->destroy(idmgr);
 }
END_TEST START_TEST (test_acquire_id)
Definition at line 34 of file id_manager_tests.c.
References tkm_id_manager_t::acquire_id, tkm_id_manager_t::destroy, fail_unless, limits, TKM_CTX_MAX, and tkm_id_manager_create().
 {
     int i, id = 0;
     tkm_id_manager_t *idmgr = tkm_id_manager_create(limits);
     for (i = 0; i < TKM_CTX_MAX; i++)
     {
         id = idmgr->acquire_id(idmgr, i);
         fail_unless(id > 0, "Error acquiring id of context kind %d", i);
         /* Reset test variable */
         id = 0;
     }
     idmgr->destroy(idmgr);
 }
END_TEST START_TEST (test_acquire_id_invalid_kind)
Definition at line 52 of file id_manager_tests.c.
References tkm_id_manager_t::acquire_id, tkm_id_manager_t::destroy, fail_unless, limits, TKM_CTX_MAX, and tkm_id_manager_create().
 {
     int id = 0;
     tkm_id_manager_t *idmgr = tkm_id_manager_create(limits);
     id = idmgr->acquire_id(idmgr, TKM_CTX_MAX);
     fail_unless(id == 0, "Acquired id for invalid context kind %d", TKM_CTX_MAX);
     /* Reset test variable */
     id = 0;
     id = idmgr->acquire_id(idmgr, -1);
     fail_unless(id == 0, "Acquired id for invalid context kind %d", -1);
     idmgr->destroy(idmgr);
 }
END_TEST START_TEST (test_acquire_id_same)
Definition at line 70 of file id_manager_tests.c.
References tkm_id_manager_t::acquire_id, tkm_id_manager_t::destroy, fail_unless, limits, TKM_CTX_NONCE, and tkm_id_manager_create().
 {
     int id1 = 0, id2 = 0;
     tkm_id_manager_t *idmgr = tkm_id_manager_create(limits);
     id1 = idmgr->acquire_id(idmgr, TKM_CTX_NONCE);
     fail_unless(id1 > 0, "Unable to acquire first id");
     /* Acquire another id, must be different than first */
     id2 = idmgr->acquire_id(idmgr, TKM_CTX_NONCE);
     fail_unless(id2 > 0, "Unable to acquire second id");
     fail_unless(id1 != id2, "Same id received twice");
     idmgr->destroy(idmgr);
 }
END_TEST START_TEST (test_release_id)
Definition at line 87 of file id_manager_tests.c.
References tkm_id_manager_t::acquire_id, tkm_id_manager_t::destroy, fail_unless, FALSE, limits, tkm_id_manager_t::release_id, TKM_CTX_MAX, and tkm_id_manager_create().
 {
     int i, id = 0;
     bool released = false;
     tkm_id_manager_t *idmgr = tkm_id_manager_create(limits);
     for (i = 0; i < TKM_CTX_MAX; i++)
     {
         id = idmgr->acquire_id(idmgr, i);
         released = idmgr->release_id(idmgr, i, id);
         fail_unless(released, "Error releasing id of context kind %d", i);
         /* Reset released variable */
         released = FALSE;
     }
     idmgr->destroy(idmgr);
 }
END_TEST START_TEST (test_release_id_invalid_kind)
Definition at line 108 of file id_manager_tests.c.
References tkm_id_manager_t::destroy, fail_if, limits, tkm_id_manager_t::release_id, TKM_CTX_MAX, tkm_id_manager_create(), and TRUE.
 {
     bool released = TRUE;
     tkm_id_manager_t *idmgr = tkm_id_manager_create(limits);
     released = idmgr->release_id(idmgr, TKM_CTX_MAX, 1);
     fail_if(released, "Released id for invalid context kind %d", TKM_CTX_MAX);
     /* Reset test variable */
     released = TRUE;
     released = idmgr->release_id(idmgr, -1, 1);
     fail_if(released, "Released id for invalid context kind %d", -1);
     idmgr->destroy(idmgr);
 }
END_TEST START_TEST (test_release_id_nonexistent)
Definition at line 126 of file id_manager_tests.c.
References tkm_id_manager_t::destroy, fail_unless, FALSE, limits, tkm_id_manager_t::release_id, TKM_CTX_NONCE, and tkm_id_manager_create().
 {
     bool released = FALSE;
     tkm_id_manager_t *idmgr = tkm_id_manager_create(limits);
     released = idmgr->release_id(idmgr, TKM_CTX_NONCE, 1);
     fail_unless(released, "Release of nonexistent id failed");
     idmgr->destroy(idmgr);
 }
Variable Documentation
const tkm_limits_t limits = {125, 100, 55, 30, 200, 42} static
Definition at line 21 of file id_manager_tests.c.
Referenced by CALLBACK(), METHOD(), START_TEST(), and tkm_init().