strongSwan: kernel_netlink_ipsec
kernel_netlink_ipsec
kernel_netlink
Classes
struct kernel_netlink_ipsec_t
Typedefs
typedef struct
kernel_netlink_ipsec_t kernel_netlink_ipsec_t
Functions
kernel_netlink_ipsec_t * kernel_netlink_ipsec_create ()
Detailed Description
Typedef Documentation
typedef struct kernel_netlink_ipsec_t kernel_netlink_ipsec_t
Definition at line 26 of file kernel_netlink_ipsec.h.
Function Documentation
kernel_netlink_ipsec_t* kernel_netlink_ipsec_create ()
Create a netlink kernel ipsec interface instance.
Returns
kernel_netlink_ipsec_t instance
Definition at line 2874 of file kernel_netlink_ipsec.c.
References watcher_t::add, addr, array_create(), bind, DBG1, DBG_KNL, DEFAULT_ACQUIRE_LIFETIME, destroy(), FALSE, fprintf, settings_t::get_bool, settings_t::get_int, hashtable_create(), INIT, ipsec_sa_equals(), ipsec_sa_hash(), lib, memset, mutex_create(), MUTEX_TYPE_DEFAULT, netlink_socket_create(), NETLINK_XFRM, sockaddr_nl::nl_family, sockaddr_nl::nl_groups, library_t::ns, policy_equals(), policy_hash(), receive_events(), library_t::settings, socket, streq(), TRUE, library_t::watcher, WATCHER_READ, and XFRMNLGRP.
Referenced by METHOD().
 {
     private_kernel_netlink_ipsec_t *this;
     bool register_for_events = TRUE;
     FILE *f;
     INIT(this,
         .public = {
             .interface = {
                 .get_features = _get_features,
                 .get_spi = _get_spi,
                 .get_cpi = _get_cpi,
                 .add_sa  = _add_sa,
                 .update_sa = _update_sa,
                 .query_sa = _query_sa,
                 .del_sa = _del_sa,
                 .flush_sas = _flush_sas,
                 .add_policy = _add_policy,
                 .query_policy = _query_policy,
                 .del_policy = _del_policy,
                 .flush_policies = _flush_policies,
                 .bypass_socket = _bypass_socket,
                 .enable_udp_decap = _enable_udp_decap,
                 .destroy = _destroy,
             },
         },
         .policies = hashtable_create((hashtable_hash_t)policy_hash,
                                      (hashtable_equals_t)policy_equals, 32),
         .sas = hashtable_create((hashtable_hash_t)ipsec_sa_hash,
                                 (hashtable_equals_t)ipsec_sa_equals, 32),
         .bypass = array_create(sizeof(bypass_t), 0),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .policy_update = lib->settings->get_bool(lib->settings,
                     "%s.plugins.kernel-netlink.policy_update", FALSE, lib->ns),
         .install_routes = lib->settings->get_bool(lib->settings,
                             "%s.install_routes", TRUE, lib->ns),
         .proto_port_transport = lib->settings->get_bool(lib->settings,
                         "%s.plugins.kernel-netlink.set_proto_port_transport_sa",
                         FALSE, lib->ns),
     );
     if (streq(lib->ns, "starter"))
     {   /* starter has no threads, so we do not register for kernel events */
         register_for_events = FALSE;
     }
     f = fopen("/proc/sys/net/core/xfrm_acq_expires", "w");
     if (f)
     {
         fprintf(f, "%u", lib->settings->get_int(lib->settings,
                                 "%s.plugins.kernel-netlink.xfrm_acq_expires",
                                 DEFAULT_ACQUIRE_LIFETIME, lib->ns));
         fclose(f);
     }
     this->socket_xfrm = netlink_socket_create(NETLINK_XFRM, xfrm_msg_names,
                 lib->settings->get_bool(lib->settings,
                     "%s.plugins.kernel-netlink.parallel_xfrm", FALSE, lib->ns));
     if (!this->socket_xfrm)
     {
         destroy(this);
         return NULL;
     }
     if (register_for_events)
     {
         struct sockaddr_nl addr;
         memset(&addr, 0, sizeof(addr));
         addr.nl_family = AF_NETLINK;
         /* create and bind XFRM socket for ACQUIRE, EXPIRE, MIGRATE & MAPPING */
         this->socket_xfrm_events = socket(AF_NETLINK, SOCK_RAW, NETLINK_XFRM);
         if (this->socket_xfrm_events <= 0)
         {
             DBG1(DBG_KNL, "unable to create XFRM event socket");
             destroy(this);
             return NULL;
         }
         addr.nl_groups = XFRMNLGRP(ACQUIRE) | XFRMNLGRP(EXPIRE) |
                          XFRMNLGRP(MIGRATE) | XFRMNLGRP(MAPPING);
         if (bind(this->socket_xfrm_events, (struct sockaddr*)&addr, sizeof(addr)))
         {
             DBG1(DBG_KNL, "unable to bind XFRM event socket");
             destroy(this);
             return NULL;
         }
         lib->watcher->add(lib->watcher, this->socket_xfrm_events, WATCHER_READ,
                           (watcher_cb_t)receive_events, this);
     }
     return &this->public;
 }