strongSwan: tls_socket
tls_socket
libtls
Classes
struct tls_socket_t
Typedefs
typedef struct tls_socket_t tls_socket_t
Functions
tls_socket_t * tls_socket_create (bool is_server, identification_t *server, identification_t *peer, int fd, tls_cache_t *cache, tls_version_t max_version, bool nullok)
Detailed Description
Typedef Documentation
typedef struct tls_socket_t tls_socket_t
Definition at line 26 of file tls_socket.h.
Function Documentation
tls_socket_t* tls_socket_create (bool is_server, identification_t * server, identification_t * peer, int fd, tls_cache_t * cache, tls_version_t max_version, bool nullok)
Create a tls_socket instance.
Parameters
is_server TRUE to act as TLS server
server server identity
peer client identity, NULL for no client authentication
fd socket to read/write from
cache session cache to use, or NULL
max_version maximun TLS version to negotiate
nullok accept NULL encryption ciphers
Returns
TLS socket wrapper
See header
Definition at line 407 of file tls_socket.c.
References free(), INIT, nop(), tls, tls_create(), TLS_PURPOSE_GENERIC, and TLS_PURPOSE_GENERIC_NULLOK.
Referenced by make_connection(), pt_tls_server_create(), run_client(), run_echo_client(), serve(), serve_echo(), and soap_init().
 {
     private_tls_socket_t *this;
     tls_purpose_t purpose;
     INIT(this,
         .public = {
             .read = _read_,
             .write = _write_,
             .splice = _splice,
             .get_fd = _get_fd,
             .get_server_id = _get_server_id,
             .get_peer_id = _get_peer_id,
             .destroy = _destroy,
         },
         .app = {
             .application = {
                 .build = _build,
                 .process = _process,
                 .destroy = (void*)nop,
             },
         },
         .fd = fd,
     );
     if (nullok)
     {
         purpose = TLS_PURPOSE_GENERIC_NULLOK;
     }
     else
     {
         purpose = TLS_PURPOSE_GENERIC;
     }
     this->tls = tls_create(is_server, server, peer, purpose,
                            &this->app.application, cache);
     if (!this->tls)
     {
         free(this);
         return NULL;
     }
     this->tls->set_version(this->tls, max_version);
     return &this->public;
 }