strongSwan: delete_payload.c File Reference
delete_payload.c File Reference
#include <stddef.h>
#include "delete_payload.h"
Classes
struct private_delete_payload_t
struct spi_enumerator_t
Typedefs
typedef struct
private_delete_payload_t private_delete_payload_t
Functions
METHOD (payload_t, verify, status_t, private_delete_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_delete_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_delete_payload_t *this)
METHOD (payload_t, get_payload_type, payload_type_t, private_delete_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_delete_payload_t *this)
METHOD (payload_t, set_next_type, void, private_delete_payload_t *this, payload_type_t type)
METHOD (payload_t, get_length, size_t, private_delete_payload_t *this)
METHOD (delete_payload_t, get_protocol_id, protocol_id_t, private_delete_payload_t *this)
METHOD (delete_payload_t, add_spi, void, private_delete_payload_t *this, u_int32_t spi)
METHOD (delete_payload_t, set_ike_spi, void, private_delete_payload_t *this, u_int64_t spi_i, u_int64_t spi_r)
METHOD (delete_payload_t, get_ike_spi, bool, private_delete_payload_t *this, u_int64_t *spi_i, u_int64_t *spi_r)
METHOD (enumerator_t, spis_enumerate, bool, spi_enumerator_t *this, u_int32_t *spi)
METHOD (delete_payload_t, create_spi_enumerator, enumerator_t *, private_delete_payload_t *this)
METHOD2 (payload_t, delete_payload_t, destroy, void, private_delete_payload_t *this)
delete_payload_t * delete_payload_create (payload_type_t type, protocol_id_t protocol_id)
Variables
static encoding_rule_t encodings_v2 []
static encoding_rule_t encodings_v1 []
Typedef Documentation
typedef struct private_delete_payload_t private_delete_payload_t
Definition at line 24 of file delete_payload.c.
Function Documentation
METHOD (payload_t , verify , status_t , private_delete_payload_t * this)
Definition at line 168 of file delete_payload.c.
References FAILED, PLV2_DELETE, PROTO_AH, PROTO_ESP, PROTO_IKE, SUCCESS, and type.
 {
     switch (this->protocol_id)
     {
         case PROTO_AH:
         case PROTO_ESP:
             if (this->spi_size != 4)
             {
                 return FAILED;
             }
             break;
         case PROTO_IKE:
         case 0:
             if (this->type == PLV2_DELETE)
             {   /* IKEv2 deletion has no spi assigned! */
                 if (this->spi_size != 0)
                 {
                     return FAILED;
                 }
             }
             else
             {   /* IKEv1 uses the two concatenated ISAKMP cookies as SPI */
                 if (this->spi_size != 16)
                 {
                     return FAILED;
                 }
             }
             break;
         default:
             return FAILED;
     }
     if (this->spis.len != (this->spi_count * this->spi_size))
     {
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (payload_t , get_encoding_rules , int , private_delete_payload_t * this, encoding_rule_t ** rules)
Definition at line 207 of file delete_payload.c.
References countof, encodings_v1, encodings_v2, PLV2_DELETE, and type.
 {
     if (this->type == PLV2_DELETE)
     {
         *rules = encodings_v2;
         return countof(encodings_v2);
     }
     *rules = encodings_v1;
     return countof(encodings_v1);
 }
METHOD (payload_t , get_header_length , int , private_delete_payload_t * this)
Definition at line 219 of file delete_payload.c.
References PLV2_DELETE, and type.
 {
     if (this->type == PLV2_DELETE)
     {
         return 8;
     }
     return 12;
 }
METHOD (payload_t , get_payload_type , payload_type_t , private_delete_payload_t * this)
Definition at line 229 of file delete_payload.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_delete_payload_t * this)
Definition at line 235 of file delete_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_delete_payload_t * this, payload_type_t type)
Definition at line 241 of file delete_payload.c.
References type.
 {
     this->next_payload = type;
 }
METHOD (payload_t , get_length , size_t , private_delete_payload_t * this)
Definition at line 247 of file delete_payload.c.
 {
     return this->payload_length;
 }
METHOD (delete_payload_t , get_protocol_id , protocol_id_t , private_delete_payload_t * this)
Definition at line 253 of file delete_payload.c.
 {
     return this->protocol_id;
 }
METHOD (delete_payload_t , add_spi , void , private_delete_payload_t * this, u_int32_t spi)
Definition at line 259 of file delete_payload.c.
References chunk_cat, chunk_from_thing, PROTO_AH, and PROTO_ESP.
 {
     switch (this->protocol_id)
     {
         case PROTO_AH:
         case PROTO_ESP:
             this->spi_count++;
             this->payload_length += sizeof(spi);
             this->spis = chunk_cat("mc", this->spis, chunk_from_thing(spi));
             break;
         default:
             break;
     }
 }
METHOD (delete_payload_t , set_ike_spi , void , private_delete_payload_t * this, u_int64_t spi_i, u_int64_t spi_r)
Definition at line 275 of file delete_payload.c.
References chunk_cat, chunk_from_thing, and free().
 {
     free(this->spis.ptr);
     this->spis = chunk_cat("cc", chunk_from_thing(spi_i),
                                  chunk_from_thing(spi_r));
     this->spi_count = 1;
     this->payload_length = get_header_length(this) + this->spi_size;
 }
METHOD (delete_payload_t , get_ike_spi , bool , private_delete_payload_t * this, u_int64_t * spi_i, u_int64_t * spi_r)
Definition at line 285 of file delete_payload.c.
References FALSE, memcpy, PROTO_IKE, and TRUE.
 {
     if (this->protocol_id != PROTO_IKE ||
         this->spis.len < 2 * sizeof(u_int64_t))
     {
         return FALSE;
     }
     memcpy(spi_i, this->spis.ptr, sizeof(u_int64_t));
     memcpy(spi_r, this->spis.ptr + sizeof(u_int64_t), sizeof(u_int64_t));
     return TRUE;
 }
METHOD (enumerator_t , spis_enumerate , bool , spi_enumerator_t * this, u_int32_t * spi)
Definition at line 308 of file delete_payload.c.
References chunk_skip(), FALSE, memcpy, and TRUE.
 {
     if (this->spis.len >= sizeof(*spi))
     {
         memcpy(spi, this->spis.ptr, sizeof(*spi));
         this->spis = chunk_skip(this->spis, sizeof(*spi));
         return TRUE;
     }
     return FALSE;
 }
METHOD (delete_payload_t , create_spi_enumerator , enumerator_t * , private_delete_payload_t * this)
Definition at line 320 of file delete_payload.c.
References destroy(), enumerator_create_empty(), free(), INIT, and spi_enumerator_t::public.
 {
     spi_enumerator_t *e;
     if (this->spi_size != sizeof(u_int32_t))
     {
         return enumerator_create_empty();
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_spis_enumerate,
             .destroy = (void*)free,
         },
         .spis = this->spis,
     );
     return &e->public;
 }
METHOD2 (payload_t , delete_payload_t , destroy , void , private_delete_payload_t * this)
Definition at line 339 of file delete_payload.c.
References free().
 {
     free(this->spis.ptr);
     free(this);
 }
Variable Documentation
encoding_rule_t encodings_v1[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_delete_payload_t, next_payload)    },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[0])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[1])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[2])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[3])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[4])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[5])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[6])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[7])     },
    { PAYLOAD_LENGTH,   offsetof(private_delete_payload_t, payload_length)  },
    { U_INT_32,         offsetof(private_delete_payload_t, doi)             },
    { U_INT_8,          offsetof(private_delete_payload_t, protocol_id)     },
    { U_INT_8,          offsetof(private_delete_payload_t, spi_size)        },
    { U_INT_16,         offsetof(private_delete_payload_t, spi_count)       },
    { CHUNK_DATA,       offsetof(private_delete_payload_t, spis)            },
}
Encoding rules for an IKEv1 delete payload.
Definition at line 129 of file delete_payload.c.
Referenced by METHOD().
encoding_rule_t encodings_v2[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_delete_payload_t, next_payload)    },
    { FLAG,             offsetof(private_delete_payload_t, critical)        },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[0])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[1])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[2])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[3])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[4])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[5])     },
    { RESERVED_BIT,     offsetof(private_delete_payload_t, reserved[6])     },
    { PAYLOAD_LENGTH,   offsetof(private_delete_payload_t, payload_length)  },
    { U_INT_8,          offsetof(private_delete_payload_t, protocol_id)     },
    { U_INT_8,          offsetof(private_delete_payload_t, spi_size)        },
    { U_INT_16,         offsetof(private_delete_payload_t, spi_count)       },
    { CHUNK_DATA,       offsetof(private_delete_payload_t, spis)            },
}
Encoding rules for an IKEv2 delete payload.
Definition at line 90 of file delete_payload.c.
Referenced by METHOD().