strongSwan: imv_reason_string.c File Reference
imv_reason_string.c File Reference
#include "imv_reason_string.h"
#include <utils/debug.h>
Classes
struct private_imv_reason_string_t
Typedefs
typedef struct
private_imv_reason_string_t private_imv_reason_string_t
Functions
METHOD (imv_reason_string_t, add_reason, void, private_imv_reason_string_t *this, imv_lang_string_t reason[])
METHOD (imv_reason_string_t, get_encoding, chunk_t, private_imv_reason_string_t *this)
METHOD (imv_reason_string_t, destroy, void, private_imv_reason_string_t *this)
imv_reason_string_t * imv_reason_string_create (char *lang, char *separator)
Typedef Documentation
typedef struct private_imv_reason_string_t private_imv_reason_string_t
Definition at line 20 of file imv_reason_string.c.
Function Documentation
METHOD (imv_reason_string_t , add_reason , void , private_imv_reason_string_t * this, imv_lang_string_t reason[])
Definition at line 49 of file imv_reason_string.c.
References chunk_cat, chunk_clone, chunk_create(), chunk_from_str, imv_lang_string_select_string(), and reasons.
 {
     char *s_reason;
     s_reason = imv_lang_string_select_string(reason, this->lang);
     if (this->reasons.len)
     {
         /* append any further reasons */
         this->reasons = chunk_cat("mcc", this->reasons,
                                   chunk_from_str(this->separator),
                                   chunk_create(s_reason, strlen(s_reason)));
     }
     else
     {
         /* add the first reason */
         this->reasons = chunk_clone(chunk_create(s_reason, strlen(s_reason)));
     }
 }
METHOD (imv_reason_string_t , get_encoding , chunk_t , private_imv_reason_string_t * this)
Definition at line 70 of file imv_reason_string.c.
References reasons.
 {
     return this->reasons;
 }
METHOD (imv_reason_string_t , destroy , void , private_imv_reason_string_t * this)
Definition at line 76 of file imv_reason_string.c.
References free(), and reasons.
 {
     free(this->reasons.ptr);
     free(this);
 }