strongSwan: lookip_listener
lookip_listener
lookip
Classes
struct lookip_listener_t
Typedefs
typedef struct lookip_listener_t lookip_listener_t
typedef bool(* lookip_callback_t)(void *user, bool up, host_t *vip, host_t *other, identification_t *id, char *name, u_int unique_id)
Functions
lookip_listener_t * lookip_listener_create ()
Detailed Description
Typedef Documentation
typedef bool(* lookip_callback_t)(void *user, bool up, host_t *vip, host_t *other, identification_t *id, char *name, u_int unique_id)
Callback function to query virtual IP entries
Parameters
user user supplied pointer
up TRUE if tunnels established, FALSE if closed
vip virtual IP of remote peer
other peer external IP
id peer identity
name associated connection name
unique_id unique IKE_SA identifier
Returns
TRUE to receive more results, FALSE to cancel
Definition at line 40 of file lookip_listener.h.
typedef struct lookip_listener_t lookip_listener_t
Definition at line 26 of file lookip_listener.h.
Function Documentation
lookip_listener_t* lookip_listener_create ()
Create a lookip_listener instance.
See header
Definition at line 325 of file lookip_listener.c.
References equals(), hash(), hashtable_create(), INIT, linked_list_create(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by lookip_plugin_create().
 {
     private_lookip_listener_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .message = _message_hook,
                 .ike_updown = _ike_updown,
                 .ike_rekey = _ike_rekey,
             },
             .lookup = _lookup,
             .add_listener = _add_listener,
             .remove_listener = _remove_listener,
             .destroy = _destroy,
         },
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .entries = hashtable_create((hashtable_hash_t)hash,
                                     (hashtable_equals_t)equals, 32),
         .listeners = linked_list_create(),
     );
     return &this->public;
 }