strongSwan: medsrv_creds.c File Reference
medsrv_creds.c File Reference
#include "medsrv_creds.h"
#include <daemon.h>
#include <library.h>
#include <collections/enumerator.h>
Classes
struct private_medsrv_creds_t
struct cert_enumerator_t
Typedefs
typedef struct
private_medsrv_creds_t private_medsrv_creds_t
Functions
METHOD (enumerator_t, cert_enumerator_enumerate, bool, cert_enumerator_t *this, certificate_t **cert)
METHOD (enumerator_t, cert_enumerator_destroy, void, cert_enumerator_t *this)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_medsrv_creds_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (medsrv_creds_t, destroy, void, private_medsrv_creds_t *this)
medsrv_creds_t * medsrv_creds_create (database_t *db)
Typedef Documentation
typedef struct private_medsrv_creds_t private_medsrv_creds_t
Definition at line 22 of file medsrv_creds.c.
Function Documentation
METHOD (enumerator_t , cert_enumerator_enumerate , bool , cert_enumerator_t * this, certificate_t ** cert)
Definition at line 54 of file medsrv_creds.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_PUBLIC_KEY, CERT_TRUSTED_PUBKEY, credential_factory_t::create, CRED_CERTIFICATE, CRED_PUBLIC_KEY, library_t::creds, DESTROY_IF, FALSE, KEY_ANY, lib, public, TRUE, and type.
 {
     certificate_t *trusted;
     public_key_t *public;
     chunk_t chunk;
     DESTROY_IF(this->current);
     while (this->inner->enumerate(this->inner, &chunk))
     {
         public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_ANY,
                                     BUILD_BLOB_ASN1_DER, chunk,
                                     BUILD_END);
         if (public)
         {
             if (this->type == KEY_ANY || this->type == public->get_type(public))
             {
                 trusted = lib->creds->create(lib->creds,
                                         CRED_CERTIFICATE, CERT_TRUSTED_PUBKEY,
                                         BUILD_PUBLIC_KEY, public, BUILD_END);
                 public->destroy(public);
                 if (trusted)
                 {
                     *cert = this->current = trusted;
                     return TRUE;
                 }
             }
             else
             {
                 public->destroy(public);
             }
         }
     }
     this->current = NULL;
     return FALSE;
 }
METHOD (enumerator_t , cert_enumerator_destroy , void , cert_enumerator_t * this)
Definition at line 91 of file medsrv_creds.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_medsrv_creds_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 99 of file medsrv_creds.c.
References CERT_ANY, CERT_TRUSTED_PUBKEY, db, DB_BLOB, destroy(), free(), identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, INIT, cert_enumerator_t::inner, cert_enumerator_t::public, database_t::query, and type.
 {
     cert_enumerator_t *e;
     if ((cert != CERT_TRUSTED_PUBKEY && cert != CERT_ANY) ||
         id == NULL || id->get_type(id) != ID_KEY_ID)
     {
         return NULL;
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_cert_enumerator_enumerate,
             .destroy = _cert_enumerator_destroy,
         },
         .type = key,
         .inner = this->db->query(this->db,
                                  "SELECT public_key FROM peer WHERE keyid = ?",
                                  DB_BLOB, id->get_encoding(id),
                                  DB_BLOB),
     );
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (medsrv_creds_t , destroy , void , private_medsrv_creds_t * this)
Definition at line 130 of file medsrv_creds.c.
References free().
 {
     free(this);
 }