strongSwan: sshkey_builder.c File Reference
sshkey_builder.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <errno.h>
#include "sshkey_builder.h"
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Macros
#define _GNU_SOURCE /* for fmemopen() */
#define ECDSA_PREFIX "ecdsa-sha2-"
Functions
static chunk_t parse_ec_identifier (chunk_t identifier)
static sshkey_public_key_t * parse_public_key (chunk_t blob)
static sshkey_public_key_t * load_from_stream (FILE *file)
static sshkey_public_key_t * load_from_blob (chunk_t blob)
static sshkey_public_key_t * load_from_file (char *file)
sshkey_public_key_t * sshkey_public_key_load (key_type_t type, va_list args)
certificate_t * sshkey_certificate_load (certificate_type_t type, va_list args)
Macro Definition Documentation
#define _GNU_SOURCE /* for fmemopen() */
Definition at line 16 of file sshkey_builder.c.
#define ECDSA_PREFIX "ecdsa-sha2-"
Definition at line 28 of file sshkey_builder.c.
Referenced by load_from_stream(), and parse_public_key().
Function Documentation
static sshkey_public_key_t* load_from_blob (chunk_t blob) static
Load SSH key from a blob of data (most likely the content of a file)
Definition at line 168 of file sshkey_builder.c.
References chunk_t::len, load_from_stream(), and chunk_t::ptr.
Referenced by sshkey_public_key_load().
 {
     FILE *stream;
     stream = fmemopen(blob.ptr, blob.len, "r");
     if (!stream)
     {
         return NULL;
     }
     return load_from_stream(stream);
 }
static sshkey_public_key_t* load_from_file (char * file) static
Load SSH key from file
Definition at line 183 of file sshkey_builder.c.
References DBG1, DBG_LIB, load_from_stream(), and strerror.
Referenced by sshkey_certificate_load(), and sshkey_public_key_load().
 {
     FILE *stream;
     stream = fopen(file, "r");
     if (!stream)
     {
         DBG1(DBG_LIB, "  opening '%s' failed: %s", file, strerror(errno));
         return NULL;
     }
     return load_from_stream(stream);
 }
static sshkey_public_key_t* load_from_stream (FILE * file) static
Load SSH key from a FILE stream, closes the stream
Definition at line 135 of file sshkey_builder.c.
References blob, chunk_empty, chunk_free(), chunk_from_base64(), chunk_from_str, enumerator_t::destroy, ECDSA_PREFIX, enumerator_t::enumerate, enumerator_create_token(), parse_public_key(), chunk_t::ptr, and strpfx().
Referenced by load_from_blob(), and load_from_file().
 {
     sshkey_public_key_t *public = NULL;
     chunk_t blob = chunk_empty;
     enumerator_t *enumerator;
     char line[1024], *token;
     while (!public && fgets(line, sizeof(line), file))
     {   /* the format is: ssh-rsa|ecdsa-... <key(base64)> <identifier> */
         if (!strpfx(line, "ssh-rsa") && !strpfx(line, ECDSA_PREFIX))
         {
             continue;
         }
         enumerator = enumerator_create_token(line, " ", " ");
         if (enumerator->enumerate(enumerator, &token) &&
             enumerator->enumerate(enumerator, &token))
         {
             blob = chunk_from_base64(chunk_from_str(token), NULL);
         }
         enumerator->destroy(enumerator);
         if (blob.ptr)
         {
             public = parse_public_key(blob);
             chunk_free(&blob);
         }
     }
     fclose(file);
     return public;
 }
static chunk_t parse_ec_identifier (chunk_t identifier) static
Parse an EC domain parameter identifier as defined in RFC 5656
Definition at line 33 of file sshkey_builder.c.
References asn1_build_known_oid(), ASN1_OID, asn1_oid_from_string(), asn1_wrap(), chunk_empty, chunk_equals(), chunk_from_str, chunk_t::len, OID_PRIME256V1, OID_SECT384R1, OID_SECT521R1, chunk_t::ptr, and snprintf.
Referenced by parse_public_key().
 {
     chunk_t oid = chunk_empty;
     if (chunk_equals(identifier, chunk_from_str("nistp256")))
     {
         oid = asn1_build_known_oid(OID_PRIME256V1);
     }
     else if (chunk_equals(identifier, chunk_from_str("nistp384")))
     {
         oid = asn1_build_known_oid(OID_SECT384R1);
     }
     else if (chunk_equals(identifier, chunk_from_str("nistp521")))
     {
         oid = asn1_build_known_oid(OID_SECT521R1);
     }
     else
     {
         char ascii[64];
         if (snprintf(ascii, sizeof(ascii), "%.*s", (int)identifier.len,
                      identifier.ptr) < sizeof(ascii))
         {
             oid = asn1_wrap(ASN1_OID, "m", asn1_oid_from_string(ascii));
         }
     }
     return oid;
 }
static sshkey_public_key_t* parse_public_key (chunk_t blob) static
Load a generic public key from an SSH key blob
Definition at line 65 of file sshkey_builder.c.
References asn1_bitstring(), asn1_build_known_oid(), ASN1_SEQUENCE, asn1_wrap(), bio_reader_create(), BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_equals(), chunk_free(), chunk_from_str, credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, DBG1, DBG_LIB, bio_reader_t::destroy, ECDSA_PREFIX, identifier, key, KEY_ECDSA, KEY_RSA, chunk_t::len, lib, n, OID_EC_PUBLICKEY, parse_ec_identifier(), bio_reader_t::peek, chunk_t::ptr, q, bio_reader_t::read_data32, and strpfx().
Referenced by load_from_stream(), and sshkey_public_key_load().
 {
     bio_reader_t *reader;
     chunk_t format;
     reader = bio_reader_create(blob);
     if (!reader->read_data32(reader, &format))
     {
         DBG1(DBG_LIB, "invalid key format in SSH key");
         reader->destroy(reader);
         return NULL;
     }
     if (chunk_equals(format, chunk_from_str("ssh-rsa")))
     {
         chunk_t n, e;
         if (!reader->read_data32(reader, &e) ||
             !reader->read_data32(reader, &n))
         {
             DBG1(DBG_LIB, "invalid RSA key in SSH key");
             reader->destroy(reader);
             return NULL;
         }
         reader->destroy(reader);
         return lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                         BUILD_RSA_MODULUS, n, BUILD_RSA_PUB_EXP, e, BUILD_END);
     }
     else if (format.len > strlen(ECDSA_PREFIX) &&
              strpfx(format.ptr, ECDSA_PREFIX))
     {
         chunk_t ec_blob, identifier, q, oid, encoded;
         sshkey_public_key_t *key;
         ec_blob = reader->peek(reader);
         reader->destroy(reader);
         reader = bio_reader_create(ec_blob);
         if (!reader->read_data32(reader, &identifier) ||
             !reader->read_data32(reader, &q))
         {
             DBG1(DBG_LIB, "invalid ECDSA key in SSH key");
             reader->destroy(reader);
             return NULL;
         }
         oid = parse_ec_identifier(identifier);
         if (!oid.ptr)
         {
             DBG1(DBG_LIB, "invalid ECDSA key identifier in SSH key");
             reader->destroy(reader);
             return NULL;
         }
         reader->destroy(reader);
         /* build key from subjectPublicKeyInfo */
         encoded = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_wrap(ASN1_SEQUENCE, "mm",
                             asn1_build_known_oid(OID_EC_PUBLICKEY), oid),
                         asn1_bitstring("c", q));
         key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY,
                             KEY_ECDSA, BUILD_BLOB_ASN1_DER, encoded, BUILD_END);
         chunk_free(&encoded);
         return key;
     }
     DBG1(DBG_LIB, "unsupported SSH key format %.*s", (int)format.len,
          format.ptr);
     reader->destroy(reader);
     return NULL;
 }