strongSwan: thread
thread
threading
Classes
struct thread_t
Typedefs
typedef struct thread_t thread_t
typedef void *(* thread_main_t)(void *arg)
typedef void(* thread_cleanup_t)(void *arg)
Functions
thread_t * thread_create (thread_main_t main, void *arg)
thread_t * thread_current ()
u_int thread_current_id ()
void thread_cleanup_push (thread_cleanup_t cleanup, void *arg)
void thread_cleanup_pop (bool execute)
void thread_cleanup_popall ()
bool thread_cancelability (bool enable)
void thread_cancellation_point ()
void thread_exit (void *val)
void threads_init ()
void threads_deinit ()
Detailed Description
Typedef Documentation
typedef void(* thread_cleanup_t)(void *arg)
Cleanup callback function for a thread.
Parameters
arg argument provided to thread_cleanup_push
Definition at line 41 of file thread.h.
typedef void*(* thread_main_t)(void *arg)
Main function of a thread.
Parameters
arg argument provided to constructor
Returns
value provided to threads joining the terminating thread
Definition at line 34 of file thread.h.
typedef struct thread_t thread_t
Definition at line 26 of file thread.h.
Function Documentation
bool thread_cancelability (bool enable)
Enable or disable the cancelability of the current thread. The current value is returned.
Parameters
enable TRUE to enable cancelability
Returns
the current state of the cancelability
Described in header.
Definition at line 422 of file thread.c.
References cancel(), get_current_thread(), and SIG_CANCEL.
Referenced by cancel_onoff_run(), cancel_point_run(), cancellation_accept(), cancellation_cond(), cancellation_poll(), cancellation_read(), cancellation_recv(), cancellation_rwcond(), cancellation_select(), cleanup_cancel_run(), condvar_cancel_run(), dispatch(), dispatch_fifo(), dispatch_slot_events(), handle_plain(), METHOD(), precancellable_poll(), precancellable_select(), process(), process_jobs(), receive(), resolve_hosts(), rwlock_condvar_cancel_run(), schedule(), semaphore_cancel_run(), send_packets(), thread_cancellation_point(), wait_for_listener(), watch(), and watchdog().
 {
 #ifdef HAVE_PTHREAD_CANCEL
     int old;
     pthread_setcancelstate(enable ? PTHREAD_CANCEL_ENABLE
                                   : PTHREAD_CANCEL_DISABLE, &old);
     return old == PTHREAD_CANCEL_ENABLE;
 #else
     sigset_t new, old;
     sigemptyset(&new);
     sigaddset(&new, SIG_CANCEL);
     pthread_sigmask(enable ? SIG_UNBLOCK : SIG_BLOCK, &new, &old);
     return sigismember(&old, SIG_CANCEL) == 0;
 #endif /* HAVE_PTHREAD_CANCEL */
 }
void thread_cancellation_point ()
Force creation of a cancellation point in the calling thread.
This temporarily enables thread cancelability, tests for a pending cancellation request and then disables cancelability again if it was disabled before the call to thread_cancellation_point().
Described in header.
Definition at line 445 of file thread.c.
References thread_cancelability(), and TRUE.
Referenced by cancel_point_run(), METHOD(), precancellable_poll(), and precancellable_select().
 {
     bool old = thread_cancelability(TRUE);
 #ifdef HAVE_PTHREAD_CANCEL
     pthread_testcancel();
 #endif /* HAVE_PTHREAD_CANCEL */
     thread_cancelability(old);
 }
void thread_cleanup_pop (bool execute)
Remove the top function from the current thread's cleanup handler stack and optionally execute it.
Parameters
execute TRUE to execute the function
Described in header.
Described in header
Definition at line 383 of file thread.c.
References cleanup_handler_t::arg, cleanup_t::arg, array_remove(), cleanup_t::cb, cleanup_handler_t::cleanup, cleanup, DBG1, DBG_LIB, FALSE, free(), get_current_thread(), set_leak_detective(), SUCCESS, and thread_current().
Referenced by accept_async(), CALLBACK(), cleanup_pop_run(), condvar_cancel_run(), fast_request_create(), METHOD(), notify_async(), process(), process_job(), process_request(), resolve_hosts(), rwlock_condvar_cancel_run(), schedule(), send_packets(), START_TEST(), wait_for_listener(), watch(), and watchdog().
 {
     private_thread_t *this = (private_thread_t*)thread_current();
     cleanup_handler_t *handler;
     if (this->cleanup_handlers->remove_last(this->cleanup_handlers,
                                             (void**)&handler) != SUCCESS)
     {
         DBG1(DBG_LIB, "!!! THREAD CLEANUP ERROR !!!");
         return;
     }
     if (execute)
     {
         handler->cleanup(handler->arg);
     }
     free(handler);
 }
void thread_cleanup_popall ()
Pop and execute all cleanup handlers in reverse order of registration.
This function is for very special purposes only, where the caller exactly knows which cleanup handlers have been pushed. For regular use, a caller should thread_cleanup_pop() exactly the number of handlers it pushed using thread_cleanup_push().
Described in header.
Definition at line 405 of file thread.c.
References cleanup_handler_t::arg, cleanup_t::arg, array_count(), array_remove(), cleanup_t::cb, cleanup_handler_t::cleanup, cleanup, FALSE, free(), get_current_thread(), set_leak_detective(), and thread_current().
Referenced by call_fixture(), cleanup_popall_run(), post_test(), and run_test().
 {
     private_thread_t *this = (private_thread_t*)thread_current();
     cleanup_handler_t *handler;
     while (this->cleanup_handlers->get_count(this->cleanup_handlers))
     {
         this->cleanup_handlers->remove_last(this->cleanup_handlers,
                                             (void**)&handler);
         handler->cleanup(handler->arg);
         free(handler);
     }
 }
void thread_cleanup_push (thread_cleanup_t cb, void * arg)
Push a function onto the current thread's cleanup handler stack. The callback function is called whenever the thread is cancelled, exits or thread_cleanup_pop is called with TRUE as execute argument.
Parameters
cleanup function called on thread exit
arg argument provided to the callback
Described in header.
Definition at line 367 of file thread.c.
References array_insert(), cb(), cleanup, FALSE, get_current_thread(), INIT, set_leak_detective(), and thread_current().
Referenced by accept_async(), CALLBACK(), cancellation_accept(), cancellation_cond(), cancellation_poll(), cancellation_read(), cancellation_recv(), cancellation_rwcond(), cancellation_select(), cleanup_cancel_run(), cleanup_exit_run(), cleanup_pop_run(), cleanup_popall_run(), cleanup_run(), condvar_cancel_run(), fast_request_create(), METHOD(), notify_async(), process(), process_job(), process_request(), resolve_hosts(), rwlock_condvar_cancel_run(), schedule(), send_packets(), START_TEST(), wait_for_listener(), watch(), and watchdog().
 {
     private_thread_t *this = (private_thread_t*)thread_current();
     cleanup_handler_t *handler;
     INIT(handler,
         .cleanup = cleanup,
         .arg = arg,
     );
     this->cleanup_handlers->insert_last(this->cleanup_handlers, handler);
 }
thread_t* thread_create (thread_main_t main, void * arg)
Create a new thread instance.
Parameters
main thread main function
arg argument provided to the main function
Returns
thread instance
Described in header.
Definition at line 312 of file thread.c.
References create_internal(), DBG1, DBG2, DBG_LIB, destroy(), FALSE, handle, mutex_t::lock, main(), mutex, next_id, put_thread(), thread_cb(), thread_create_internal(), thread_destroy(), thread_main(), and mutex_t::unlock.
 {
     private_thread_t *this = thread_create_internal();
     this->main = main;
     this->arg = arg;
     id_mutex->lock(id_mutex);
     this->id = next_id++;
     id_mutex->unlock(id_mutex);
     if (pthread_create(&this->thread_id, NULL, (void*)thread_main, this) != 0)
     {
         DBG1(DBG_LIB, "failed to create thread!");
         this->mutex->lock(this->mutex);
         thread_destroy(this);
         return NULL;
     }
     return &this->public;
 }
thread_t* thread_current ()
Get a thread object for the current thread.
Returns
thread instance
Described in header.
Definition at line 336 of file thread.c.
References thread_value_t::get, get_current_thread(), mutex_t::lock, next_id, private_thread_t::public, thread_value_t::set, thread_create_internal(), and mutex_t::unlock.
Referenced by METHOD(), resolve_hosts(), thread_cleanup_pop(), thread_cleanup_popall(), thread_cleanup_push(), thread_current_id(), and threads_deinit().
 {
     private_thread_t *this;
     this = (private_thread_t*)current_thread->get(current_thread);
     if (!this)
     {
         this = thread_create_internal();
         id_mutex->lock(id_mutex);
         this->id = next_id++;
         id_mutex->unlock(id_mutex);
         current_thread->set(current_thread, (void*)this);
     }
     return &this->public;
 }
u_int thread_current_id ()
Get the human-readable ID of the current thread.
The IDs are assigned incrementally starting from 1.
Returns
human-readable ID
Described in header.
Definition at line 357 of file thread.c.
References get_current_thread(), thread_current(), and private_thread_t::tid.
Referenced by fatal_signal_handler(), id_function(), METHOD(), process_jobs(), restart(), segv_handler(), and xml_callback().
 {
     private_thread_t *this = (private_thread_t*)thread_current();
     return this ? this->id : 0;
 }
void thread_exit (void * val)
Exit the current thread.
Parameters
val value provided to threads joining the current thread
Described in header.
Definition at line 458 of file thread.c.
References end_thread(), get_current_thread(), and val.
Referenced by cleanup_exit_run(), detach_exit_run(), and exit_join_run().
 {
     pthread_exit(val);
 }
void threads_deinit ()
Called by the main thread to deinitialize the thread management.
Described in header.
Definition at line 498 of file thread.c.
References spinlock_t::destroy, thread_value_t::destroy, mutex_t::destroy, hashtable_t::destroy, destroy(), private_thread_t::detached_or_joined, mutex_t::lock, main_thread, private_thread_t::mutex, hashtable_t::remove, private_thread_t::terminated, thread_current(), thread_destroy(), and TRUE.
Referenced by library_deinit(), and print_failures().
 {
     private_thread_t *main_thread = (private_thread_t*)thread_current();
     dummy1->destroy(dummy1);
     main_thread->mutex->lock(main_thread->mutex);
     main_thread->terminated = TRUE;
     main_thread->detached_or_joined = TRUE;
     thread_destroy(main_thread);
     current_thread->destroy(current_thread);
     id_mutex->destroy(id_mutex);
 }
void threads_init ()
Called by the main thread to initialize the thread management.
Described in header.
Definition at line 472 of file thread.c.
References cancel_signal_handler(), create_internal(), hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), private_thread_t::id, main_thread, mutex_create(), MUTEX_TYPE_DEFAULT, next_id, put_thread(), thread_value_t::set, SIG_CANCEL, spinlock_create(), thread_create_internal(), private_thread_t::thread_id, thread_value_create(), and threads_ids.
Referenced by library_init(), and print_failures().
 {
     private_thread_t *main_thread = thread_create_internal();
     dummy1 = thread_value_create(NULL);
     next_id = 1;
     main_thread->id = 0;
     main_thread->thread_id = pthread_self();
     current_thread = thread_value_create(NULL);
     current_thread->set(current_thread, (void*)main_thread);
     id_mutex = mutex_create(MUTEX_TYPE_DEFAULT);
 #ifndef HAVE_PTHREAD_CANCEL
     {   /* install a signal handler for our custom SIG_CANCEL */
         struct sigaction action = {
             .sa_handler = cancel_signal_handler
         };
         sigaction(SIG_CANCEL, &action, NULL);
     }
 #endif /* HAVE_PTHREAD_CANCEL */
 }