strongSwan: thread
thread
windows
Functions
void thread_set_active_condvar (CONDITION_VARIABLE *condvar)
void * thread_tls_put (void *key, void *value)
void * thread_tls_get (void *key)
void * thread_tls_remove (void *key)
void thread_tls_cleanup (void *value)
Detailed Description
Function Documentation
void thread_set_active_condvar (CONDITION_VARIABLE * condvar)
Set active condvar of a thread before waiting in it.
Parameters
condvar active condition variable, NULL to unset
See header.
Definition at line 334 of file windows/thread.c.
References private_thread_t::condvar, condvar, get_current_thread(), spinlock_t::lock, TRUE, and spinlock_t::unlock.
Referenced by METHOD().
 {
     private_thread_t *thread;
     thread = get_current_thread();
     threads_lock->lock(threads_lock);
     thread->condvar = condvar;
     threads_lock->unlock(threads_lock);
     /* this is a cancellation point, as condvar wait is one */
     SleepEx(0, TRUE);
 }
void thread_tls_cleanup (void * value)
Cleanup function for thread specific value.
This is called whenever a thread exits to clean up thread specific data.
This function is actually implemented in thread_value.c.
Parameters
value value, as passed to thread_tls_put()
See windows/thread.h
Definition at line 60 of file windows/thread_value.c.
References entry_t::cleanup, free(), and entry_t::value.
Referenced by docleanup(), and METHOD().
 {
     entry_t *entry = (entry_t*)value;
     if (entry->cleanup)
     {
         entry->cleanup(entry->value);
     }
     free(entry);
 }
void* thread_tls_get (void * key)
Get a thread specific value from the current thread.
Parameters
key unique key specifying the TLS variable
Returns
value for key, if any
See header.
Definition at line 213 of file windows/thread.c.
References FALSE, hashtable_t::get, get_current_thread(), set_leak_detective(), private_thread_t::tls, and value.
Referenced by METHOD().
 {
     private_thread_t *thread;
     void *value;
     bool old;
     thread = get_current_thread();
     old = set_leak_detective(FALSE);
     value = thread->tls->get(thread->tls, key);
     set_leak_detective(old);
     return value;
 }
void* thread_tls_put (void * key, void * value)
Set a thread specific value on the current thread.
Parameters
key unique key specifying the TLS variable
value value to set
Returns
old value for key, if any
See header.
Definition at line 196 of file windows/thread.c.
References FALSE, get_current_thread(), hashtable_t::put, set_leak_detective(), private_thread_t::tls, and value.
Referenced by METHOD().
 {
     private_thread_t *thread;
     bool old;
     thread = get_current_thread();
     old = set_leak_detective(FALSE);
     value = thread->tls->put(thread->tls, key, value);
     set_leak_detective(old);
     return value;
 }
void* thread_tls_remove (void * key)
Remove a thread specific value from the current thread.
Parameters
key unique key specifying the TLS variable
Returns
value for key, if any
See header.
Definition at line 231 of file windows/thread.c.
References FALSE, get_current_thread(), spinlock_t::lock, hashtable_t::remove, set_leak_detective(), private_thread_t::tls, spinlock_t::unlock, and value.
Referenced by METHOD().
 {
     private_thread_t *thread;
     void *value;
     bool old;
     thread = get_current_thread();
     old = set_leak_detective(FALSE);
     threads_lock->lock(threads_lock);
     value = thread->tls->remove(thread->tls, key);
     threads_lock->unlock(threads_lock);
     set_leak_detective(old);
     return value;
 }