strongSwan: attr_sql_provider.c File Reference
attr_sql_provider.c File Reference
#include <time.h>
#include <utils/debug.h>
#include <library.h>
#include "attr_sql_provider.h"
Classes
struct private_attr_sql_provider_t
Typedefs
typedef struct
private_attr_sql_provider_t private_attr_sql_provider_t
Functions
static u_int get_identity (private_attr_sql_provider_t *this, ike_sa_t *ike_sa)
static u_int get_attr_pool (private_attr_sql_provider_t *this, char *name)
static u_int get_pool (private_attr_sql_provider_t *this, char *name, int family, u_int *timeout)
static host_t * check_lease (private_attr_sql_provider_t *this, char *name, u_int pool, u_int identity)
static host_t * get_lease (private_attr_sql_provider_t *this, char *name, u_int pool, u_int timeout, u_int identity)
METHOD (attribute_provider_t, acquire_address, host_t *, private_attr_sql_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, host_t *requested)
METHOD (attribute_provider_t, release_address, bool, private_attr_sql_provider_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
METHOD (attribute_provider_t, create_attribute_enumerator, enumerator_t *, private_attr_sql_provider_t *this, linked_list_t *pools, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (attr_sql_provider_t, destroy, void, private_attr_sql_provider_t *this)
attr_sql_provider_t * attr_sql_provider_create (database_t *db)
Typedef Documentation
typedef struct private_attr_sql_provider_t private_attr_sql_provider_t
Definition at line 23 of file attr_sql_provider.c.
Function Documentation
static host_t* check_lease (private_attr_sql_provider_t * this, char * name, u_int pool, u_int identity) static
Look up an existing lease
Definition at line 131 of file attr_sql_provider.c.
References chunk_clonea, db, DB_BLOB, DB_UINT, DBG1, DBG_CFG, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, database_t::execute, host, host_create_from_chunk(), id, database_t::query, and TRUE.
Referenced by METHOD().
 {
     while (TRUE)
     {
         u_int id;
         chunk_t address;
         enumerator_t *e;
         time_t now = time(NULL);
         e = this->db->query(this->db,
                 "SELECT id, address FROM addresses "
                 "WHERE pool = ? AND identity = ? AND released != 0 LIMIT 1",
                 DB_UINT, pool, DB_UINT, identity, DB_UINT, DB_BLOB);
         if (!e || !e->enumerate(e, &id, &address))
         {
             DESTROY_IF(e);
             break;
         }
         address = chunk_clonea(address);
         e->destroy(e);
         if (this->db->execute(this->db, NULL,
                 "UPDATE addresses SET acquired = ?, released = 0 "
                 "WHERE id = ? AND identity = ? AND released != 0",
                 DB_UINT, now, DB_UINT, id, DB_UINT, identity) > 0)
         {
             host_t *host;
             host = host_create_from_chunk(AF_UNSPEC, address, 0);
             if (host)
             {
                 DBG1(DBG_CFG, "acquired existing lease for address %H in"
                      " pool '%s'", host, name);
                 return host;
             }
         }
     }
     return NULL;
 }
static u_int get_attr_pool (private_attr_sql_provider_t * this, char * name) static
Lookup an attribute pool by name
Definition at line 85 of file attr_sql_provider.c.
References db, DB_TEXT, DB_UINT, DESTROY_IF, enumerator_t::enumerate, and database_t::query.
Referenced by METHOD().
 {
     enumerator_t *e;
     u_int row = 0;
     e = this->db->query(this->db,
                         "SELECT id FROM attribute_pools WHERE name = ?",
                         DB_TEXT, name, DB_UINT);
     if (e)
     {
         e->enumerate(e, &row);
     }
     DESTROY_IF(e);
     return row;
 }
static u_int get_identity (private_attr_sql_provider_t * this, ike_sa_t * ike_sa) static
lookup/insert an identity
Definition at line 49 of file attr_sql_provider.c.
References database_t::commit, db, DB_BLOB, DB_INT, DB_UINT, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, database_t::execute, ike_sa_t::get_other_eap_id, identification_t::get_type, id, database_t::query, database_t::rollback, database_t::transaction, and TRUE.
Referenced by add_address(), and METHOD().
 {
     identification_t *id;
     enumerator_t *e;
     u_int row;
     id = ike_sa->get_other_eap_id(ike_sa);
     this->db->transaction(this->db, TRUE);
     /* look for peer identity in the identities table */
     e = this->db->query(this->db,
                         "SELECT id FROM identities WHERE type = ? AND data = ?",
                         DB_INT, id->get_type(id), DB_BLOB, id->get_encoding(id),
                         DB_UINT);
     if (e && e->enumerate(e, &row))
     {
         e->destroy(e);
         this->db->commit(this->db);
         return row;
     }
     DESTROY_IF(e);
     /* not found, insert new one */
     if (this->db->execute(this->db, &row,
                   "INSERT INTO identities (type, data) VALUES (?, ?)",
                   DB_INT, id->get_type(id), DB_BLOB, id->get_encoding(id)) == 1)
     {
         this->db->commit(this->db);
         return row;
     }
     this->db->rollback(this->db);
     return 0;
 }
static host_t* get_lease (private_attr_sql_provider_t * this, char * name, u_int pool, u_int timeout, u_int identity) static
We check for unallocated addresses or expired leases. First we select an address as a candidate, but double check later on if it is still available during the update operation. This allows us to work without locking.
Definition at line 177 of file attr_sql_provider.c.
References chunk_clonea, db, DB_BLOB, DB_UINT, DBG1, DBG_CFG, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, database_t::execute, host, host_create_from_chunk(), id, database_t::query, and TRUE.
Referenced by METHOD().
 {
     while (TRUE)
     {
         u_int id;
         chunk_t address;
         enumerator_t *e;
         time_t now = time(NULL);
         int hits;
         if (timeout)
         {
             /* check for an expired lease */
             e = this->db->query(this->db,
                 "SELECT id, address FROM addresses "
                 "WHERE pool = ? AND released != 0 AND released < ? LIMIT 1",
                 DB_UINT, pool, DB_UINT, now - timeout, DB_UINT, DB_BLOB);
         }
         else
         {
             /* with static leases, check for an unallocated address */
             e = this->db->query(this->db,
                 "SELECT id, address FROM addresses "
                 "WHERE pool = ? AND identity = 0 LIMIT 1",
                 DB_UINT, pool, DB_UINT, DB_BLOB);
         }
         if (!e || !e->enumerate(e, &id, &address))
         {
             DESTROY_IF(e);
             break;
         }
         address = chunk_clonea(address);
         e->destroy(e);
         if (timeout)
         {
             hits = this->db->execute(this->db, NULL,
                         "UPDATE addresses SET "
                         "acquired = ?, released = 0, identity = ? "
                         "WHERE id = ? AND released != 0 AND released < ?",
                         DB_UINT, now, DB_UINT, identity,
                         DB_UINT, id, DB_UINT, now - timeout);
         }
         else
         {
             hits = this->db->execute(this->db, NULL,
                         "UPDATE addresses SET "
                         "acquired = ?, released = 0, identity = ? "
                         "WHERE id = ? AND identity = 0",
                         DB_UINT, now, DB_UINT, identity, DB_UINT, id);
         }
         if (hits > 0)
         {
             host_t *host;
             host = host_create_from_chunk(AF_UNSPEC, address, 0);
             if (host)
             {
                 DBG1(DBG_CFG, "acquired new lease for address %H in pool '%s'",
                      host, name);
                 return host;
             }
         }
     }
     DBG1(DBG_CFG, "no available address found in pool '%s'", name);
     return NULL;
 }
static u_int get_pool (private_attr_sql_provider_t * this, char * name, int family, u_int * timeout) static
Lookup pool by name and address family
Definition at line 105 of file attr_sql_provider.c.
References db, DB_BLOB, DB_TEXT, DB_UINT, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, chunk_t::len, database_t::query, and start.
Referenced by METHOD().
 {
     enumerator_t *e;
     chunk_t start;
     u_int pool;
     e = this->db->query(this->db,
                         "SELECT id, start, timeout FROM pools WHERE name = ?",
                         DB_TEXT, name, DB_UINT, DB_BLOB, DB_UINT);
     if (e && e->enumerate(e, &pool, &start, timeout))
     {
         if ((family == AF_INET  && start.len == 4) ||
             (family == AF_INET6 && start.len == 16))
         {
             e->destroy(e);
             return pool;
         }
     }
     DESTROY_IF(e);
     return 0;
 }
METHOD (attribute_provider_t , acquire_address , host_t * , private_attr_sql_provider_t * this, linked_list_t * pools, ike_sa_t * ike_sa, host_t * requested)
Definition at line 248 of file attr_sql_provider.c.
References check_lease(), linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, family, host_t::get_family, get_identity(), get_lease(), get_pool(), identity, and name.
 {
     enumerator_t *enumerator;
     host_t *address = NULL;
     u_int identity, pool, timeout;
     char *name;
     int family;
     identity = get_identity(this, ike_sa);
     if (identity)
     {
         family = requested->get_family(requested);
         /* check for an existing lease in all pools */
         enumerator = pools->create_enumerator(pools);
         while (enumerator->enumerate(enumerator, &name))
         {
             pool = get_pool(this, name, family, &timeout);
             if (pool)
             {
                 address = check_lease(this, name, pool, identity);
                 if (address)
                 {
                     break;
                 }
             }
         }
         enumerator->destroy(enumerator);
         if (!address)
         {
             /* get an unallocated address or expired lease */
             enumerator = pools->create_enumerator(pools);
             while (enumerator->enumerate(enumerator, &name))
             {
                 pool = get_pool(this, name, family, &timeout);
                 if (pool)
                 {
                     address = get_lease(this, name, pool, timeout, identity);
                     if (address)
                     {
                         break;
                     }
                 }
             }
             enumerator->destroy(enumerator);
         }
     }
     return address;
 }
METHOD (attribute_provider_t , release_address , bool , private_attr_sql_provider_t * this, linked_list_t * pools, host_t * address, ike_sa_t * ike_sa)
Definition at line 300 of file attr_sql_provider.c.
References linked_list_t::create_enumerator, db, DB_BLOB, DB_UINT, enumerator_t::destroy, enumerator_t::enumerate, database_t::execute, FALSE, family, found, host_t::get_address, host_t::get_family, get_pool(), name, and TRUE.
 {
     enumerator_t *enumerator;
     u_int pool, timeout;
     time_t now = time(NULL);
     bool found = FALSE;
     char *name;
     int family;
     family = address->get_family(address);
     enumerator = pools->create_enumerator(pools);
     while (enumerator->enumerate(enumerator, &name))
     {
         pool = get_pool(this, name, family, &timeout);
         if (!pool)
         {
             continue;
         }
         if (this->db->execute(this->db, NULL,
                 "UPDATE addresses SET released = ? WHERE "
                 "pool = ? AND address = ?", DB_UINT, time(NULL),
                 DB_UINT, pool, DB_BLOB, address->get_address(address)) > 0)
         {
             if (this->history)
             {
                 this->db->execute(this->db, NULL,
                     "INSERT INTO leases (address, identity, acquired, released)"
                     " SELECT id, identity, acquired, ? FROM addresses "
                     " WHERE pool = ? AND address = ?",
                     DB_UINT, now, DB_UINT, pool,
                     DB_BLOB, address->get_address(address));
             }
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (attribute_provider_t , create_attribute_enumerator , enumerator_t * , private_attr_sql_provider_t * this, linked_list_t * pools, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 343 of file attr_sql_provider.c.
References count, linked_list_t::create_enumerator, db, DB_BLOB, DB_INT, DB_UINT, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, enumerator_create_empty(), get_attr_pool(), linked_list_t::get_count, get_identity(), identity, name, and database_t::query.
 {
     enumerator_t *attr_enumerator = NULL;
     if (vips->get_count(vips))
     {
         enumerator_t *pool_enumerator;
         u_int count;
         char *name;
         /* in a first step check for attributes that match name and id */
         if (ike_sa)
         {
             u_int identity = get_identity(this, ike_sa);
             pool_enumerator = pools->create_enumerator(pools);
             while (pool_enumerator->enumerate(pool_enumerator, &name))
             {
                 u_int attr_pool = get_attr_pool(this, name);
                 if (!attr_pool)
                 {
                     continue;
                 }
                 attr_enumerator = this->db->query(this->db,
                                 "SELECT count(*) FROM attributes "
                                 "WHERE pool = ? AND identity = ?",
                                 DB_UINT, attr_pool, DB_UINT, identity, DB_UINT);
                 if (attr_enumerator &&
                     attr_enumerator->enumerate(attr_enumerator, &count) &&
                     count != 0)
                 {
                     attr_enumerator->destroy(attr_enumerator);
                     attr_enumerator = this->db->query(this->db,
                                 "SELECT type, value FROM attributes "
                                 "WHERE pool = ? AND identity = ?", DB_UINT,
                                 attr_pool, DB_UINT, identity, DB_INT, DB_BLOB);
                     break;
                 }
                 DESTROY_IF(attr_enumerator);
                 attr_enumerator = NULL;
             }
             pool_enumerator->destroy(pool_enumerator);
         }
         /* in a second step check for attributes that match name */
         if (!attr_enumerator)
         {
             pool_enumerator = pools->create_enumerator(pools);
             while (pool_enumerator->enumerate(pool_enumerator, &name))
             {
                 u_int attr_pool = get_attr_pool(this, name);
                 if (!attr_pool)
                 {
                     continue;
                 }
                 attr_enumerator = this->db->query(this->db,
                                     "SELECT count(*) FROM attributes "
                                     "WHERE pool = ? AND identity = 0",
                                     DB_UINT, attr_pool, DB_UINT);
                 if (attr_enumerator &&
                     attr_enumerator->enumerate(attr_enumerator, &count) &&
                     count != 0)
                 {
                     attr_enumerator->destroy(attr_enumerator);
                     attr_enumerator = this->db->query(this->db,
                                     "SELECT type, value FROM attributes "
                                     "WHERE pool = ? AND identity = 0",
                                     DB_UINT, attr_pool, DB_INT, DB_BLOB);
                     break;
                 }
                 DESTROY_IF(attr_enumerator);
                 attr_enumerator = NULL;
             }
             pool_enumerator->destroy(pool_enumerator);
         }
         /* lastly try to find global attributes */
         if (!attr_enumerator)
         {
             attr_enumerator = this->db->query(this->db,
                                     "SELECT type, value FROM attributes "
                                     "WHERE pool = 0 AND identity = 0",
                                     DB_INT, DB_BLOB);
         }
     }
     return (attr_enumerator ? attr_enumerator : enumerator_create_empty());
 }
METHOD (attr_sql_provider_t , destroy , void , private_attr_sql_provider_t * this)
Definition at line 438 of file attr_sql_provider.c.
References free().
 {
     free(this);
 }