strongSwan: x509_crl
x509_crl
x509
Classes
struct x509_crl_t
Typedefs
typedef struct x509_crl_t x509_crl_t
Functions
x509_crl_t * x509_crl_load (certificate_type_t type, va_list args)
x509_crl_t * x509_crl_gen (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct x509_crl_t x509_crl_t
Definition at line 24 of file x509_crl.h.
Function Documentation
x509_crl_t* x509_crl_gen (certificate_type_t type, va_list args)
Generate a X.509 CRL.
Parameters
type certificate type, CERT_X509_CRL only
args builder_part_t argument list
Returns
X.509 CRL, NULL on failure
See header.
Definition at line 802 of file x509_crl.c.
References private_x509_crl_t::baseCrlNumber, BUILD_BASE_CRL, BUILD_CRL_DISTRIBUTION_POINTS, BUILD_DIGEST_ALG, BUILD_END, BUILD_NOT_AFTER_TIME, BUILD_NOT_BEFORE_TIME, BUILD_REVOKED_ENUMERATOR, BUILD_SERIAL, BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, cert, CERT_X509, chunk_clone, identification_t::clone, create_empty(), linked_list_t::create_enumerator, private_x509_crl_t::crl_uris, private_x509_crl_t::crlNumber, enumerator_t::destroy, destroy(), enumerator_t::enumerate, generate(), private_x509_crl_t::generated, certificate_t::get_type, HASH_SHA1, in, INIT, linked_list_t::insert_last, x509_cdp_t::issuer, key, list, private_x509_crl_t::nextUpdate, private_x509_crl_t::public, read_revoked(), strdup, private_x509_crl_t::thisUpdate, TRUE, uri, and x509_cdp_t::uri.
Referenced by METHOD().
 {
     hash_algorithm_t digest_alg = HASH_SHA1;
     private_x509_crl_t *crl;
     certificate_t *cert = NULL;
     private_key_t *key = NULL;
     crl = create_empty();
     crl->generated = TRUE;
     while (TRUE)
     {
         builder_part_t part = va_arg(args, builder_part_t);
         switch (part)
         {
             case BUILD_SIGNING_KEY:
                 key = va_arg(args, private_key_t*);
                 continue;
             case BUILD_SIGNING_CERT:
                 cert = va_arg(args, certificate_t*);
                 continue;
             case BUILD_NOT_BEFORE_TIME:
                 crl->thisUpdate = va_arg(args, time_t);
                 continue;
             case BUILD_NOT_AFTER_TIME:
                 crl->nextUpdate = va_arg(args, time_t);
                 continue;
             case BUILD_SERIAL:
                 crl->crlNumber = va_arg(args, chunk_t);
                 crl->crlNumber = chunk_clone(crl->crlNumber);
                 continue;
             case BUILD_DIGEST_ALG:
                 digest_alg = va_arg(args, int);
                 continue;
             case BUILD_REVOKED_ENUMERATOR:
                 read_revoked(crl, va_arg(args, enumerator_t*));
                 continue;
             case BUILD_BASE_CRL:
                 crl->baseCrlNumber = va_arg(args, chunk_t);
                 crl->baseCrlNumber = chunk_clone(crl->baseCrlNumber);
                 break;
             case BUILD_CRL_DISTRIBUTION_POINTS:
             {
                 enumerator_t *enumerator;
                 linked_list_t *list;
                 x509_cdp_t *in, *cdp;
                 list = va_arg(args, linked_list_t*);
                 enumerator = list->create_enumerator(list);
                 while (enumerator->enumerate(enumerator, &in))
                 {
                     INIT(cdp,
                         .uri = strdup(in->uri),
                         .issuer = in->issuer ? in->issuer->clone(in->issuer) : NULL,
                     );
                     crl->crl_uris->insert_last(crl->crl_uris, cdp);
                 }
                 enumerator->destroy(enumerator);
                 continue;
             }
             case BUILD_END:
                 break;
             default:
                 destroy(crl);
                 return NULL;
         }
         break;
     }
     if (key && cert && cert->get_type(cert) == CERT_X509 &&
         generate(crl, cert, key, digest_alg))
     {
         return &crl->public;
     }
     destroy(crl);
     return NULL;
 }
x509_crl_t* x509_crl_load (certificate_type_t type, va_list args)
Load a X.509 CRL.
Parameters
type certificate type, CERT_X509_CRL only
args builder_part_t argument list
Returns
X.509 CRL, NULL on failure
See header.
Definition at line 648 of file x509_crl.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_clone, chunk_empty, create_empty(), destroy(), private_x509_crl_t::encoding, parse(), chunk_t::ptr, private_x509_crl_t::public, and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.ptr)
     {
         private_x509_crl_t *crl = create_empty();
         crl->encoding = chunk_clone(blob);
         if (parse(crl))
         {
             return &crl->public;
         }
         destroy(crl);
     }
     return NULL;
 };