strongSwan: pkcs7_data.c File Reference
pkcs7_data.c File Reference
#include "pkcs7_data.h"
#include <asn1/asn1.h>
#include <asn1/oid.h>
Classes
struct private_pkcs7_data_t
Typedefs
typedef struct private_pkcs7_data_t private_pkcs7_data_t
Functions
METHOD (container_t, get_type, container_type_t, private_pkcs7_data_t *this)
METHOD (container_t, create_signature_enumerator, enumerator_t *, private_pkcs7_data_t *this)
METHOD (container_t, get_data, bool, private_pkcs7_data_t *this, chunk_t *data)
METHOD (container_t, get_encoding, bool, private_pkcs7_data_t *this, chunk_t *data)
METHOD (container_t, destroy, void, private_pkcs7_data_t *this)
static private_pkcs7_data_t * create_empty ()
pkcs7_t * pkcs7_data_load (chunk_t encoding, chunk_t content)
pkcs7_t * pkcs7_data_gen (container_type_t type, va_list args)
Typedef Documentation
typedef struct private_pkcs7_data_t private_pkcs7_data_t
Definition at line 21 of file pkcs7_data.c.
Function Documentation
static private_pkcs7_data_t* create_empty (void) static
Create an empty container
Definition at line 88 of file pkcs7_data.c.
References enumerator_create_empty(), INIT, and return_false().
Referenced by pkcs7_data_gen(), and pkcs7_data_load().
 {
     private_pkcs7_data_t *this;
     INIT(this,
         .public = {
             .container = {
                 .get_type = _get_type,
                 .create_signature_enumerator = _create_signature_enumerator,
                 .get_data = _get_data,
                 .get_encoding = _get_encoding,
                 .destroy = _destroy,
             },
             .get_attribute = (void*)return_false,
             .create_cert_enumerator = (void*)enumerator_create_empty,
         },
     );
     return this;
 }
METHOD (container_t , get_type , container_type_t , private_pkcs7_data_t * this)
Definition at line 44 of file pkcs7_data.c.
References CONTAINER_PKCS7_DATA.
 {
     return CONTAINER_PKCS7_DATA;
 }
METHOD (container_t , create_signature_enumerator , enumerator_t * , private_pkcs7_data_t * this)
Definition at line 50 of file pkcs7_data.c.
References enumerator_create_empty().
 {
     return enumerator_create_empty();
 }
METHOD (container_t , get_data , bool , private_pkcs7_data_t * this, chunk_t * data)
Definition at line 56 of file pkcs7_data.c.
References ASN1_OCTET_STRING, asn1_unwrap(), chunk_clone, FALSE, and TRUE.
 {
     chunk_t chunk;
     chunk = this->content;
     if (asn1_unwrap(&chunk, &chunk) == ASN1_OCTET_STRING)
     {
         *data = chunk_clone(chunk);
         return TRUE;
     }
     return FALSE;
 }
METHOD (container_t , get_encoding , bool , private_pkcs7_data_t * this, chunk_t * data)
Definition at line 70 of file pkcs7_data.c.
References chunk_clone, encoding, and TRUE.
 {
     *data = chunk_clone(this->encoding);
     return TRUE;
 }
METHOD (container_t , destroy , void , private_pkcs7_data_t * this)
Definition at line 77 of file pkcs7_data.c.
References encoding, and free().
 {
     free(this->content.ptr);
     free(this->encoding.ptr);
     free(this);
 }