strongSwan: eap_sim_pcsc_card
eap_sim_pcsc_card
eap_sim_pcsc
Classes
struct eap_sim_pcsc_card_t
Typedefs
typedef struct eap_sim_pcsc_card_t eap_sim_pcsc_card_t
Functions
eap_sim_pcsc_card_t * eap_sim_pcsc_card_create ()
Detailed Description
Typedef Documentation
typedef struct eap_sim_pcsc_card_t eap_sim_pcsc_card_t
Definition at line 25 of file eap_sim_pcsc_card.h.
Function Documentation
eap_sim_pcsc_card_t* eap_sim_pcsc_card_create ()
Create a eap_sim_pcsc_card instance.
See header
Definition at line 376 of file eap_sim_pcsc_card.c.
References destroy(), INIT, nop(), return_false(), and return_null().
Referenced by eap_sim_pcsc_plugin_create().
 {
     private_eap_sim_pcsc_card_t *this;
     INIT(this,
         .public = {
             .card = {
                 .get_triplet = _get_triplet,
                 .get_quintuplet = _get_quintuplet,
                 .resync = (void*)return_false,
                 .get_pseudonym = (void*)return_null,
                 .set_pseudonym = (void*)nop,
                 .get_reauth = (void*)return_null,
                 .set_reauth = (void*)nop,
             },
             .destroy = _destroy,
         },
     );
     return &this->public;
 }