strongSwan: load_authorities.h File Reference
load_authorities.h File Reference
#include "command.h"
Functions
int load_authorities_cfg (vici_conn_t *conn, command_format_options_t format, settings_t *cfg)
Function Documentation
int load_authorities_cfg (vici_conn_t * conn, command_format_options_t format, settings_t * cfg)
Load all certification authority definitions from configuration file
Parameters
conn vici connection to load to
format output format
cfg configuration to load from
See header.
Definition at line 256 of file load_authorities.c.
References COMMAND_FORMAT_RAW, settings_t::create_section_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, found, fprintf, free(), list_authorities(), load_authority(), printf, linked_list_t::remove_first, remove_from_list(), section, SUCCESS, and unload_authority().
Referenced by load_all(), and load_authorities().
 {
     u_int found = 0, loaded = 0, unloaded = 0;
     char *section;
     enumerator_t *enumerator;
     linked_list_t *authorities;
     authorities = list_authorities(conn, format);
     enumerator = cfg->create_section_enumerator(cfg, "authorities");
     while (enumerator->enumerate(enumerator, &section))
     {
         remove_from_list(authorities, section);
         found++;
         if (load_authority(conn, cfg, section, format))
         {
             loaded++;
         }
     }
     enumerator->destroy(enumerator);
     /* unload all authorities in daemon, but not in file */
     while (authorities->remove_first(authorities, (void**)&section) == SUCCESS)
     {
         if (unload_authority(conn, section, format))
         {
             unloaded++;
         }
         free(section);
     }
     authorities->destroy(authorities);
     if (format & COMMAND_FORMAT_RAW)
     {
         return 0;
     }
     if (found == 0)
     {
         printf("no authorities found, %u unloaded\n", unloaded);
         return 0;
     }
     if (loaded == found)
     {
         printf("successfully loaded %u authorities, %u unloaded\n",
                loaded, unloaded);
         return 0;
     }
     fprintf(stderr, "loaded %u of %u authorities, %u failed to load, "
             "%u unloaded\n", loaded, found, found - loaded, unloaded);
     return EINVAL;
 }