strongSwan: stroke_handler.c File Reference
stroke_handler.c File Reference
#include "stroke_handler.h"
#include <daemon.h>
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_stroke_handler_t
struct attributes_t
Typedefs
typedef struct
private_stroke_handler_t private_stroke_handler_t
Functions
static void attributes_destroy (attributes_t *this)
static bool attr_filter (void *lock, host_t **in, configuration_attribute_type_t *type, void *dummy, chunk_t *data)
METHOD (attribute_handler_t, create_attribute_enumerator, enumerator_t *, private_stroke_handler_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (stroke_handler_t, add_attributes, void, private_stroke_handler_t *this, stroke_msg_t *msg)
METHOD (stroke_handler_t, del_attributes, void, private_stroke_handler_t *this, stroke_msg_t *msg)
METHOD (stroke_handler_t, destroy, void, private_stroke_handler_t *this)
stroke_handler_t * stroke_handler_create ()
Typedef Documentation
typedef struct private_stroke_handler_t private_stroke_handler_t
Definition at line 22 of file stroke_handler.c.
Function Documentation
static bool attr_filter (void * lock, host_t ** in, configuration_attribute_type_t * type, void * dummy, chunk_t * data) static
Filter function to convert host to DNS configuration attributes
Definition at line 68 of file stroke_handler.c.
References chunk_empty, FALSE, host_t::get_address, host_t::get_family, host, in, INTERNAL_IP4_DNS, INTERNAL_IP6_DNS, host_t::is_anyaddr, and TRUE.
Referenced by METHOD().
 {
     host_t *host = *in;
     switch (host->get_family(host))
     {
         case AF_INET:
             *type = INTERNAL_IP4_DNS;
             break;
         case AF_INET6:
             *type = INTERNAL_IP6_DNS;
             break;
         default:
             return FALSE;
     }
     if (host->is_anyaddr(host))
     {
         *data = chunk_empty;
     }
     else
     {
         *data = host->get_address(host);
     }
     return TRUE;
 }
static void attributes_destroy (attributes_t * this) static
Destroy an attributes_t entry
Definition at line 58 of file stroke_handler.c.
References destroy(), free(), and name.
Referenced by METHOD().
 {
     this->dns->destroy_offset(this->dns, offsetof(host_t, destroy));
     free(this->name);
     free(this);
 }
METHOD (attribute_handler_t , create_attribute_enumerator , enumerator_t * , private_stroke_handler_t * this, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 96 of file stroke_handler.c.
References attr_filter(), daemon_t::bus, charon, linked_list_t::create_enumerator, enumerator_t::destroy, attributes_t::dns, enumerator_t::enumerate, enumerator_create_empty(), enumerator_create_filter(), peer_cfg_t::get_name, ike_sa_t::get_peer_cfg, bus_t::get_sa, lock, attributes_t::name, streq(), and spinlock_t::unlock.
 {
     peer_cfg_t *peer_cfg;
     enumerator_t *enumerator;
     attributes_t *attr;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (ike_sa)
     {
         peer_cfg = ike_sa->get_peer_cfg(ike_sa);
         this->lock->read_lock(this->lock);
         enumerator = this->attrs->create_enumerator(this->attrs);
         while (enumerator->enumerate(enumerator, &attr))
         {
             if (streq(attr->name, peer_cfg->get_name(peer_cfg)))
             {
                 enumerator->destroy(enumerator);
                 return enumerator_create_filter(
                                     attr->dns->create_enumerator(attr->dns),
                                     (void*)attr_filter, this->lock,
                                     (void*)this->lock->unlock);
             }
         }
         enumerator->destroy(enumerator);
         this->lock->unlock(this->lock);
     }
     return enumerator_create_empty();
 }
METHOD (stroke_handler_t , add_attributes , void , private_stroke_handler_t * this, stroke_msg_t * msg)
Definition at line 127 of file stroke_handler.c.
References stroke_msg_t::add_conn, DBG1, DBG_CFG, enumerator_t::destroy, attributes_t::dns, enumerator_t::enumerate, enumerator_create_token(), host, host_create_any(), host_create_from_string(), INIT, linked_list_t::insert_last, linked_list_create(), lock, name, strdup, streq(), and spinlock_t::unlock.
 {
     if (msg->add_conn.me.dns)
     {
         enumerator_t *enumerator;
         attributes_t *attr = NULL;
         host_t *host;
         char *token;
         enumerator = enumerator_create_token(msg->add_conn.me.dns, ",", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             if (streq(token, "%config") || streq(token, "%config4"))
             {
                 host = host_create_any(AF_INET);
             }
             else if (streq(token, "%config6"))
             {
                 host = host_create_any(AF_INET6);
             }
             else
             {
                 host = host_create_from_string(token, 0);
             }
             if (host)
             {
                 if (!attr)
                 {
                     INIT(attr,
                         .name = strdup(msg->add_conn.name),
                         .dns = linked_list_create(),
                     );
                 }
                 attr->dns->insert_last(attr->dns, host);
             }
             else
             {
                 DBG1(DBG_CFG, "ignoring invalid DNS address '%s'", token);
             }
         }
         enumerator->destroy(enumerator);
         if (attr)
         {
             this->lock->write_lock(this->lock);
             this->attrs->insert_last(this->attrs, attr);
             this->lock->unlock(this->lock);
         }
     }
 }
METHOD (stroke_handler_t , del_attributes , void , private_stroke_handler_t * this, stroke_msg_t * msg)
Definition at line 178 of file stroke_handler.c.
References attributes_destroy(), stroke_msg_t::del_conn, enumerator_t::destroy, enumerator_t::enumerate, lock, attributes_t::name, streq(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     attributes_t *attr;
     this->lock->write_lock(this->lock);
     enumerator = this->attrs->create_enumerator(this->attrs);
     while (enumerator->enumerate(enumerator, &attr))
     {
         if (streq(msg->del_conn.name, attr->name))
         {
             this->attrs->remove_at(this->attrs, enumerator);
             attributes_destroy(attr);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (stroke_handler_t , destroy , void , private_stroke_handler_t * this)
Definition at line 199 of file stroke_handler.c.
References attributes_destroy(), spinlock_t::destroy, free(), and lock.
 {
     this->lock->destroy(this->lock);
     this->attrs->destroy_function(this->attrs, (void*)attributes_destroy);
     free(this);
 }