strongSwan: openssl_diffie_hellman.c File Reference
openssl_diffie_hellman.c File Reference
#include <openssl/opensslconf.h>
#include <openssl/bn.h>
#include <openssl/dh.h>
#include "openssl_diffie_hellman.h"
#include <utils/debug.h>
Classes
struct private_openssl_diffie_hellman_t
Typedefs
typedef struct
private_openssl_diffie_hellman_t private_openssl_diffie_hellman_t
Functions
METHOD (diffie_hellman_t, get_my_public_value, bool, private_openssl_diffie_hellman_t *this, chunk_t *value)
METHOD (diffie_hellman_t, get_shared_secret, bool, private_openssl_diffie_hellman_t *this, chunk_t *secret)
METHOD (diffie_hellman_t, set_other_public_value, bool, private_openssl_diffie_hellman_t *this, chunk_t value)
METHOD (diffie_hellman_t, set_private_value, bool, private_openssl_diffie_hellman_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_dh_group, diffie_hellman_group_t, private_openssl_diffie_hellman_t *this)
static status_t set_modulus (private_openssl_diffie_hellman_t *this)
METHOD (diffie_hellman_t, destroy, void, private_openssl_diffie_hellman_t *this)
openssl_diffie_hellman_t * openssl_diffie_hellman_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Typedef Documentation
typedef struct private_openssl_diffie_hellman_t private_openssl_diffie_hellman_t
Definition at line 28 of file openssl_diffie_hellman.c.
Function Documentation
METHOD (diffie_hellman_t , get_my_public_value , bool , private_openssl_diffie_hellman_t * this, chunk_t * value)
Definition at line 65 of file openssl_diffie_hellman.c.
References chunk_alloc, dh, chunk_t::len, memset, chunk_t::ptr, and TRUE.
 {
     *value = chunk_alloc(DH_size(this->dh));
     memset(value->ptr, 0, value->len);
     BN_bn2bin(this->dh->pub_key,
               value->ptr + value->len - BN_num_bytes(this->dh->pub_key));
     return TRUE;
 }
METHOD (diffie_hellman_t , get_shared_secret , bool , private_openssl_diffie_hellman_t * this, chunk_t * secret)
Definition at line 75 of file openssl_diffie_hellman.c.
References chunk_alloc, dh, FALSE, chunk_t::len, memcpy, memset, chunk_t::ptr, and TRUE.
 {
     if (!this->computed)
     {
         return FALSE;
     }
     /* shared secret should requires a len according the DH group */
     *secret = chunk_alloc(DH_size(this->dh));
     memset(secret->ptr, 0, secret->len);
     memcpy(secret->ptr + secret->len - this->shared_secret.len,
            this->shared_secret.ptr, this->shared_secret.len);
     return TRUE;
 }
METHOD (diffie_hellman_t , set_other_public_value , bool , private_openssl_diffie_hellman_t * this, chunk_t value)
Definition at line 91 of file openssl_diffie_hellman.c.
References chunk_clear(), DBG1, DBG_LIB, dh, diffie_hellman_verify_value(), FALSE, group, chunk_t::len, len, malloc(), memset, chunk_t::ptr, and TRUE.
 {
     int len;
     if (!diffie_hellman_verify_value(this->group, value))
     {
         return FALSE;
     }
     BN_bin2bn(value.ptr, value.len, this->pub_key);
     chunk_clear(&this->shared_secret);
     this->shared_secret.ptr = malloc(DH_size(this->dh));
     memset(this->shared_secret.ptr, 0xFF, this->shared_secret.len);
     len = DH_compute_key(this->shared_secret.ptr, this->pub_key, this->dh);
     if (len < 0)
     {
         DBG1(DBG_LIB, "DH shared secret computation failed");
         return FALSE;
     }
     this->shared_secret.len = len;
     this->computed = TRUE;
     return TRUE;
 }
METHOD (diffie_hellman_t , set_private_value , bool , private_openssl_diffie_hellman_t * this, chunk_t value)
Definition at line 116 of file openssl_diffie_hellman.c.
References chunk_clear(), dh, FALSE, chunk_t::len, and chunk_t::ptr.
 {
     if (BN_bin2bn(value.ptr, value.len, this->dh->priv_key))
     {
         chunk_clear(&this->shared_secret);
         this->computed = FALSE;
         return DH_generate_key(this->dh);
     }
     return FALSE;
 }
METHOD (diffie_hellman_t , get_dh_group , diffie_hellman_group_t , private_openssl_diffie_hellman_t * this)
Definition at line 128 of file openssl_diffie_hellman.c.
References group.
 {
     return this->group;
 }
METHOD (diffie_hellman_t , destroy , void , private_openssl_diffie_hellman_t * this)
Definition at line 153 of file openssl_diffie_hellman.c.
References chunk_clear(), dh, and free().
 {
     BN_clear_free(this->pub_key);
     DH_free(this->dh);
     chunk_clear(&this->shared_secret);
     free(this);
 }
static status_t set_modulus (private_openssl_diffie_hellman_t * this) static
Lookup the modulus in modulo table
Definition at line 137 of file openssl_diffie_hellman.c.
References dh, diffie_hellman_get_params(), diffie_hellman_params_t::exp_len, diffie_hellman_params_t::generator, group, chunk_t::len, NOT_FOUND, params, diffie_hellman_params_t::prime, chunk_t::ptr, and SUCCESS.
Referenced by openssl_diffie_hellman_create().
 {
     diffie_hellman_params_t *params = diffie_hellman_get_params(this->group);
     if (!params)
     {
         return NOT_FOUND;
     }
     this->dh->p = BN_bin2bn(params->prime.ptr, params->prime.len, NULL);
     this->dh->g = BN_bin2bn(params->generator.ptr, params->generator.len, NULL);
     if (params->exp_len != params->prime.len)
     {
         this->dh->length = params->exp_len * 8;
     }
     return SUCCESS;
 }