strongSwan: imv_session.c File Reference
imv_session.c File Reference
#include "imv_session.h"
#include <tncif_identity.h>
#include <utils/debug.h>
Classes
struct private_imv_session_t
Typedefs
typedef struct
private_imv_session_t private_imv_session_t
Functions
METHOD (imv_session_t, set_session_id, void, private_imv_session_t *this, int session_id, int pid, int did)
METHOD (imv_session_t, get_session_id, int, private_imv_session_t *this, int *pid, int *did)
METHOD (imv_session_t, get_connection_id, TNC_ConnectionID, private_imv_session_t *this)
METHOD (imv_session_t, get_creation_time, time_t, private_imv_session_t *this)
METHOD (imv_session_t, create_ar_identities_enumerator, enumerator_t *, private_imv_session_t *this)
METHOD (imv_session_t, get_os_info, imv_os_info_t *, private_imv_session_t *this)
METHOD (imv_session_t, set_device_id, void, private_imv_session_t *this, chunk_t device_id)
METHOD (imv_session_t, get_device_id, bool, private_imv_session_t *this, chunk_t *device_id)
METHOD (imv_session_t, set_device_trust, void, private_imv_session_t *this, bool trusted)
METHOD (imv_session_t, get_device_trust, bool, private_imv_session_t *this)
METHOD (imv_session_t, set_policy_started, void, private_imv_session_t *this, bool start)
METHOD (imv_session_t, get_policy_started, bool, private_imv_session_t *this)
METHOD (imv_session_t, insert_workitem, void, private_imv_session_t *this, imv_workitem_t *workitem)
METHOD (imv_session_t, remove_workitem, void, private_imv_session_t *this, enumerator_t *enumerator)
METHOD (imv_session_t, create_workitem_enumerator, enumerator_t *, private_imv_session_t *this)
METHOD (imv_session_t, get_workitem_count, int, private_imv_session_t *this, TNC_IMVID imv_id)
METHOD (imv_session_t, get_ref, imv_session_t *, private_imv_session_t *this)
METHOD (imv_session_t, destroy, void, private_imv_session_t *this)
imv_session_t * imv_session_create (TNC_ConnectionID conn_id, time_t created, linked_list_t *ar_identities)
Typedef Documentation
typedef struct private_imv_session_t private_imv_session_t
Definition at line 22 of file imv_session.c.
Function Documentation
METHOD (imv_session_t , set_session_id , void , private_imv_session_t * this, int session_id, int pid, int did)
Definition at line 96 of file imv_session.c.
 {
     this->session_id = session_id;
     this->pid = pid;
     this->did = did;
 }
METHOD (imv_session_t , get_session_id , int , private_imv_session_t * this, int * pid, int * did)
Definition at line 104 of file imv_session.c.
 {
     if (pid)
     {
         *pid = this->pid;
     }
     if (did)
     {
         *did = this->did;
     }
     return this->session_id;
 }
METHOD (imv_session_t , get_connection_id , TNC_ConnectionID , private_imv_session_t * this)
Definition at line 118 of file imv_session.c.
 {
     return this->conn_id;
 }
METHOD (imv_session_t , get_creation_time , time_t , private_imv_session_t * this)
Definition at line 124 of file imv_session.c.
 {
     return this->created;
 }
METHOD (imv_session_t , create_ar_identities_enumerator , enumerator_t * , private_imv_session_t * this)
Definition at line 130 of file imv_session.c.
 {
     return this->ar_identities->create_enumerator(this->ar_identities);
 }
METHOD (imv_session_t , get_os_info , imv_os_info_t * , private_imv_session_t * this)
Definition at line 136 of file imv_session.c.
 {
     return this->os_info;
 }
METHOD (imv_session_t , set_device_id , void , private_imv_session_t * this, chunk_t device_id)
Definition at line 142 of file imv_session.c.
References chunk_clone, chunk_equals(), chunk_from_str, free(), chunk_t::len, and chunk_t::ptr.
 {
     if (device_id.len == 0)
     {
         device_id = chunk_from_str("unknown");
     }
     if (this->device_id.len)
     {
         if (chunk_equals(device_id, this->device_id))
         {
             return;
         }
         free(this->device_id.ptr);
     }
     this->device_id = chunk_clone(device_id);
 }
METHOD (imv_session_t , get_device_id , bool , private_imv_session_t * this, chunk_t * device_id)
Definition at line 160 of file imv_session.c.
References FALSE, chunk_t::len, and TRUE.
 {
     if (this->device_id.len == 0)
     {
         return FALSE;
     }
     if (device_id)
     {
         *device_id = this->device_id;
     }
     return TRUE;
 }
METHOD (imv_session_t , set_device_trust , void , private_imv_session_t * this, bool trusted)
Definition at line 174 of file imv_session.c.
 {
     this->trusted = trusted;
 }
METHOD (imv_session_t , get_device_trust , bool , private_imv_session_t * this)
Definition at line 180 of file imv_session.c.
 {
     return this->trusted;
 }
METHOD (imv_session_t , set_policy_started , void , private_imv_session_t * this, bool start)
Definition at line 186 of file imv_session.c.
References start.
 {
     this->policy_started = start;
 }
METHOD (imv_session_t , get_policy_started , bool , private_imv_session_t * this)
Definition at line 192 of file imv_session.c.
 {
     return this->policy_started;
 }
METHOD (imv_session_t , insert_workitem , void , private_imv_session_t * this, imv_workitem_t * workitem)
Definition at line 198 of file imv_session.c.
 {
     this->workitems->insert_last(this->workitems, workitem);
 }
METHOD (imv_session_t , remove_workitem , void , private_imv_session_t * this, enumerator_t * enumerator)
Definition at line 204 of file imv_session.c.
 {
     this->workitems->remove_at(this->workitems, enumerator);
 }
METHOD (imv_session_t , create_workitem_enumerator , enumerator_t * , private_imv_session_t * this)
Definition at line 210 of file imv_session.c.
 {
     return this->workitems->create_enumerator(this->workitems);
 }
METHOD (imv_session_t , get_workitem_count , int , private_imv_session_t * this, TNC_IMVID imv_id)
Definition at line 216 of file imv_session.c.
References count, enumerator_t::destroy, enumerator_t::enumerate, and imv_workitem_t::get_imv_id.
 {
     enumerator_t *enumerator;
     imv_workitem_t *workitem;
     int count = 0;
     enumerator = this->workitems->create_enumerator(this->workitems);
     while (enumerator->enumerate(enumerator, &workitem))
     {
         if (workitem->get_imv_id(workitem) == imv_id)
         {
             count++;
         }
     }
     enumerator->destroy(enumerator);
     return count;
 }
METHOD (imv_session_t , get_ref , imv_session_t * , private_imv_session_t * this)
Definition at line 236 of file imv_session.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (imv_session_t , destroy , void , private_imv_session_t * this)
Definition at line 244 of file imv_session.c.
References destroy(), free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         this->workitems->destroy_offset(this->workitems,
                                  offsetof(imv_workitem_t, destroy));
         this->os_info->destroy(this->os_info);
         this->ar_identities->destroy_offset(this->ar_identities,
                                      offsetof(tncif_identity_t, destroy));
         free(this->device_id.ptr);
         free(this);
     }
 }