strongSwan: host_resolver.c File Reference
host_resolver.c File Reference
#include <sys/types.h>
#include "host_resolver.h"
#include <library.h>
#include <utils/debug.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
#include <threading/thread.h>
#include <collections/hashtable.h>
#include <collections/linked_list.h>
Classes
struct private_host_resolver_t
struct query_t
Macros
#define MIN_THREADS_DEFAULT 0
#define MAX_THREADS_DEFAULT 3
#define NEW_QUERY_WAIT_TIMEOUT 30
Typedefs
typedef struct
private_host_resolver_t private_host_resolver_t
Functions
static void query_destroy (query_t *this)
static void query_signal_and_destroy (query_t *this)
static u_int query_hash (query_t *this)
static bool query_equals (query_t *this, query_t *other)
static void * resolve_hosts (private_host_resolver_t *this)
METHOD (host_resolver_t, resolve, host_t *, private_host_resolver_t *this, char *name, int family)
METHOD (host_resolver_t, flush, void, private_host_resolver_t *this)
METHOD (host_resolver_t, destroy, void, private_host_resolver_t *this)
host_resolver_t * host_resolver_create ()
Macro Definition Documentation
#define MAX_THREADS_DEFAULT 3
Definition at line 32 of file host_resolver.c.
Referenced by host_resolver_create().
#define MIN_THREADS_DEFAULT 0
Default minimum and maximum number of threads
Definition at line 31 of file host_resolver.c.
Referenced by host_resolver_create().
#define NEW_QUERY_WAIT_TIMEOUT 30
Timeout in seconds to wait for new queries until a thread may be stopped
Definition at line 37 of file host_resolver.c.
Referenced by resolve_hosts().
Typedef Documentation
typedef struct private_host_resolver_t private_host_resolver_t
Definition at line 39 of file host_resolver.c.
Function Documentation
METHOD (host_resolver_t , resolve , host_t * , private_host_resolver_t * this, char * name, int family)
Definition at line 231 of file host_resolver.c.
References host_t::clone, condvar_create(), CONDVAR_TYPE_DEFAULT, query_t::done, family, inet_pton(), INIT, mutex_t::lock, lookup, mutex, name, query(), query_destroy(), queue(), ref_get(), query_t::refcount, resolve_hosts(), result, query_t::result, strdup, thread_create, threads, mutex_t::unlock, and condvar_t::wait.
 {
     query_t *query, lookup = {
         .name = name,
         .family = family,
     };
     host_t *result;
     struct in_addr addr;
     switch (family)
     {
         case AF_INET:
             /* do not try to convert v6 addresses for v4 family */
             if (strchr(name, ':'))
             {
                 return NULL;
             }
             break;
         case AF_INET6:
             /* do not try to convert v4 addresses for v6 family */
             if (inet_pton(AF_INET, name, &addr) == 1)
             {
                 return NULL;
             }
             break;
     }
     this->mutex->lock(this->mutex);
     if (this->disabled)
     {
         this->mutex->unlock(this->mutex);
         return NULL;
     }
     query = this->queries->get(this->queries, &lookup);
     if (!query)
     {
         INIT(query,
             .name = strdup(name),
             .family = family,
             .done = condvar_create(CONDVAR_TYPE_DEFAULT),
             .refcount = 1,
         );
         this->queries->put(this->queries, query, query);
         this->queue->insert_last(this->queue, query);
         this->new_query->signal(this->new_query);
     }
     ref_get(&query->refcount);
     if (this->busy_threads == this->threads &&
         this->threads < this->max_threads)
     {
         thread_t *thread;
         thread = thread_create((thread_main_t)resolve_hosts, this);
         if (thread)
         {
             this->threads++;
             this->pool->insert_last(this->pool, thread);
         }
     }
     query->done->wait(query->done, this->mutex);
     this->mutex->unlock(this->mutex);
     result = query->result ? query->result->clone(query->result) : NULL;
     query_destroy(query);
     return result;
 }
METHOD (host_resolver_t , flush , void , private_host_resolver_t * this)
Definition at line 298 of file host_resolver.c.
References condvar_t::broadcast, enumerator_t::destroy, query_t::done, enumerator_t::enumerate, linked_list_create(), mutex_t::lock, mutex, query(), query_destroy(), queue(), TRUE, and mutex_t::unlock.
 {
     enumerator_t *enumerator;
     query_t *query;
     this->mutex->lock(this->mutex);
     enumerator = this->queries->create_enumerator(this->queries);
     while (enumerator->enumerate(enumerator, &query, NULL))
     {   /* use the hashtable here as we also want to signal dequeued queries */
         this->queries->remove_at(this->queries, enumerator);
         query->done->broadcast(query->done);
     }
     enumerator->destroy(enumerator);
     this->queue->destroy_function(this->queue, (void*)query_destroy);
     this->queue = linked_list_create();
     this->disabled = TRUE;
     /* this will already terminate most idle threads */
     this->new_query->broadcast(this->new_query);
     this->mutex->unlock(this->mutex);
 }
METHOD (host_resolver_t , destroy , void , private_host_resolver_t * this)
Definition at line 320 of file host_resolver.c.
References cancel(), mutex_t::destroy, free(), thread_t::join, mutex, queue(), and SUCCESS.
 {
     thread_t *thread;
     flush(this);
     this->pool->invoke_offset(this->pool, offsetof(thread_t, cancel));
     while (this->pool->remove_first(this->pool, (void**)&thread) == SUCCESS)
     {
         thread->join(thread);
     }
     this->pool->destroy(this->pool);
     this->queue->destroy(this->queue);
     this->queries->destroy(this->queries);
     this->new_query->destroy(this->new_query);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void query_destroy (query_t * this) static
Destroy the given query_t object if refcount is zero
Definition at line 119 of file host_resolver.c.
References DESTROY_IF, free(), name, ref_put(), and result.
Referenced by METHOD(), query_signal_and_destroy(), and resolve_hosts().
 {
     if (ref_put(&this->refcount))
     {
         DESTROY_IF(this->result);
         this->done->destroy(this->done);
         free(this->name);
         free(this);
     }
 }
static bool query_equals (query_t * this, query_t * other) static
Compare two queued queries
Definition at line 151 of file host_resolver.c.
References family, query_t::family, name, query_t::name, and streq().
Referenced by host_resolver_create().
 {
     return this->family == other->family && streq(this->name, other->name);
 }
static u_int query_hash (query_t * this) static
Hash a queued query
Definition at line 142 of file host_resolver.c.
References chunk_create(), chunk_from_thing, chunk_hash(), chunk_hash_inc(), family, and name.
Referenced by host_resolver_create().
 {
     return chunk_hash_inc(chunk_create(this->name, strlen(this->name)),
                           chunk_hash(chunk_from_thing(this->family)));
 }
static void query_signal_and_destroy (query_t * this) static
Signals all waiting threads and destroys the query
Definition at line 133 of file host_resolver.c.
References query_destroy().
Referenced by resolve_hosts().
 {
     this->done->broadcast(this->done);
     query_destroy(this);
 }
static void* resolve_hosts (private_host_resolver_t * this) static
Main function of resolver threads
Definition at line 159 of file host_resolver.c.
References condvar_t::broadcast, DBG1, DBG_LIB, thread_t::detach, query_t::done, FALSE, query_t::family, host_create_from_sockaddr(), mutex_t::lock, memset, mutex, query_t::name, NEW_QUERY_WAIT_TIMEOUT, query(), query_destroy(), query_signal_and_destroy(), queue(), hashtable_t::remove, result, query_t::result, SUCCESS, thread_cancelability(), thread_cleanup_pop(), thread_cleanup_push(), thread_current(), threads, TRUE, and mutex_t::unlock.
Referenced by METHOD().
 {
     struct addrinfo hints, *result;
     query_t *query;
     int error;
     bool old, timed_out;
     /* default resolver threads to non-cancellable */
     thread_cancelability(FALSE);
     while (TRUE)
     {
         this->mutex->lock(this->mutex);
         while (this->queue->remove_first(this->queue,
                                         (void**)&query) != SUCCESS)
         {
             if (this->disabled)
             {
                 this->mutex->unlock(this->mutex);
                 return NULL;
             }
             timed_out = this->new_query->timed_wait(this->new_query,
                                     this->mutex, NEW_QUERY_WAIT_TIMEOUT * 1000);
             if (this->disabled)
             {
                 this->mutex->unlock(this->mutex);
                 return NULL;
             }
             else if (timed_out && (this->threads > this->min_threads))
             {   /* terminate this thread by detaching it */
                 thread_t *thread = thread_current();
                 this->threads--;
                 this->pool->remove(this->pool, thread, NULL);
                 this->mutex->unlock(this->mutex);
                 thread->detach(thread);
                 return NULL;
             }
         }
         this->busy_threads++;
         this->mutex->unlock(this->mutex);
         memset(&hints, 0, sizeof(hints));
         hints.ai_family = query->family;
         hints.ai_socktype = SOCK_DGRAM;
         thread_cleanup_push((thread_cleanup_t)query_signal_and_destroy, query);
         old = thread_cancelability(TRUE);
         error = getaddrinfo(query->name, NULL, &hints, &result);
         thread_cancelability(old);
         thread_cleanup_pop(FALSE);
         this->mutex->lock(this->mutex);
         this->busy_threads--;
         if (error != 0)
         {
             DBG1(DBG_LIB, "resolving '%s' failed: %s", query->name,
                  gai_strerror(error));
         }
         else
         {   /* result is a linked list, but we use only the first address */
             query->result = host_create_from_sockaddr(result->ai_addr);
             freeaddrinfo(result);
         }
         this->queries->remove(this->queries, query);
         query->done->broadcast(query->done);
         this->mutex->unlock(this->mutex);
         query_destroy(query);
     }
     return NULL;
 }