strongSwan: pkcs12.c File Reference
pki/commands/pkcs12.c File Reference
#include <errno.h>
#include "pki.h"
#include <credentials/certificates/x509.h>
#include <credentials/containers/pkcs12.h>
Functions
static int show (pkcs12_t *pkcs12)
static int export (pkcs12_t *pkcs12, int index, char *outform)
static int pkcs12 ()
static void __attribute__ ((constructor))
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 233 of file pki/commands/pkcs12.c.
References command_register(), and pkcs12().
 {
     command_register((command_t) {
         pkcs12, 'u', "pkcs12", "PKCS#12 functions",
         {"--export index|--list [--in file]",
          "[--outform der|pem]"},
         {
             {"help",    'h', 0, "show usage information"},
             {"in",      'i', 1, "input file, default: stdin"},
             {"list",    'l', 0, "list certificates and keys"},
             {"export",  'e', 1, "export the credential with the given index"},
             {"outform", 'f', 1, "encoding of exported credentials, default: der"},
         }
     });
 }
static int export (pkcs12_t * pkcs12, int index, char * outform) static
Definition at line 61 of file pki/commands/pkcs12.c.
References cert, CERT_ASN1_DER, command_usage(), pkcs12_t::create_cert_enumerator, pkcs12_t::create_key_enumerator, CRED_CERTIFICATE, CRED_PRIVATE_KEY, enumerator_t::destroy, encoding, enumerator_t::enumerate, fprintf, free(), private_key_t::get_encoding, certificate_t::get_encoding, get_form(), key, chunk_t::len, PRIVKEY_ASN1_DER, chunk_t::ptr, and set_file_mode().
Referenced by certexpire_listener_create(), certexpire_plugin_create(), METHOD(), and pkcs12().
 {
     cred_encoding_type_t form;
     enumerator_t *enumerator;
     certificate_t *cert;
     private_key_t *key;
     chunk_t encoding;
     int i = 1;
     enumerator = pkcs12->create_cert_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &cert))
     {
         if (i++ == index)
         {
             form = CERT_ASN1_DER;
             if (outform && !get_form(outform, &form, CRED_CERTIFICATE))
             {
                 enumerator->destroy(enumerator);
                 return command_usage("invalid output format");
             }
             if (cert->get_encoding(cert, form, &encoding))
             {
                 set_file_mode(stdout, form);
                 if (fwrite(encoding.ptr, encoding.len, 1, stdout) == 1)
                 {
                     free(encoding.ptr);
                     enumerator->destroy(enumerator);
                     return 0;
                 }
                 free(encoding.ptr);
             }
             fprintf(stderr, "certificate export failed\n");
             enumerator->destroy(enumerator);
             return 1;
         }
     }
     enumerator->destroy(enumerator);
     enumerator = pkcs12->create_key_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &key))
     {
         if (i++ == index)
         {
             form = PRIVKEY_ASN1_DER;
             if (outform && !get_form(outform, &form, CRED_PRIVATE_KEY))
             {
                 enumerator->destroy(enumerator);
                 return command_usage("invalid output format");
             }
             if (key->get_encoding(key, form, &encoding))
             {
                 set_file_mode(stdout, form);
                 if (fwrite(encoding.ptr, encoding.len, 1, stdout) == 1)
                 {
                     free(encoding.ptr);
                     enumerator->destroy(enumerator);
                     return 0;
                 }
                 free(encoding.ptr);
             }
             fprintf(stderr, "private key export failed\n");
             enumerator->destroy(enumerator);
             return 0;
         }
     }
     enumerator->destroy(enumerator);
     fprintf(stderr, "invalid index %d\n", index);
     return 1;
 }
static int pkcs12 () static
Handle PKCs#12 containers
Definition at line 136 of file pki/commands/pkcs12.c.
References BUILD_BLOB, BUILD_END, BUILD_FROM_FILE, CERT_ASN1_DER, chunk_from_fd(), command_getopt(), command_usage(), pkcs12_t::container, CONTAINER_PKCS12, credential_factory_t::create, CRED_CONTAINER, library_t::creds, container_t::destroy, end, export(), fprintf, free(), lib, chunk_t::ptr, res, set_file_mode(), show(), strerror, and TRUE.
Referenced by __attribute__(), and load_pkcs12().
 {
     char *arg, *file = NULL, *outform = NULL;
     pkcs12_t *p12 = NULL;
     int res = 1, index = 0;
     enum {
         OP_NONE,
         OP_LIST,
         OP_EXPORT,
     } op = OP_NONE;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 'i':
                 file = arg;
                 continue;
             case 'l':
                 if (op != OP_NONE)
                 {
                     goto invalid;
                 }
                 op = OP_LIST;
                 continue;
             case 'e':
                 if (op != OP_NONE)
                 {
                     goto invalid;
                 }
                 op = OP_EXPORT;
                 index = atoi(arg);
                 continue;
             case 'f':
                 outform = arg;
                 continue;
             case EOF:
                 break;
             default:
             invalid:
                 return command_usage("invalid --pkcs12 option");
         }
         break;
     }
     if (file)
     {
         p12 = lib->creds->create(lib->creds, CRED_CONTAINER, CONTAINER_PKCS12,
                                   BUILD_FROM_FILE, file, BUILD_END);
     }
     else
     {
         chunk_t chunk;
         set_file_mode(stdin, CERT_ASN1_DER);
         if (!chunk_from_fd(0, &chunk))
         {
             fprintf(stderr, "reading input failed: %s\n", strerror(errno));
             return 1;
         }
         p12 = lib->creds->create(lib->creds, CRED_CONTAINER, CONTAINER_PKCS12,
                                   BUILD_BLOB, chunk, BUILD_END);
         free(chunk.ptr);
     }
     if (!p12)
     {
         fprintf(stderr, "reading input failed!\n");
         goto end;
     }
     switch (op)
     {
         case OP_LIST:
             res = show(p12);
             break;
         case OP_EXPORT:
             res = export(p12, index, outform);
             break;
         default:
             p12->container.destroy(&p12->container);
             return command_usage(NULL);
     }
 end:
     if (p12)
     {
         p12->container.destroy(&p12->container);
     }
     return res;
 }
static int show (pkcs12_t * pkcs12) static
Show info about PKCS#12 container
Definition at line 26 of file pki/commands/pkcs12.c.
References cert, pkcs12_t::create_cert_enumerator, pkcs12_t::create_key_enumerator, enumerator_t::destroy, enumerator_t::enumerate, x509_t::get_flags, private_key_t::get_keysize, certificate_t::get_subject, private_key_t::get_type, key, key_type_names, printf, and X509_CA.
Referenced by pkcs12().
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     private_key_t *key;
     int index = 1;
     printf("Certificates:\n");
     enumerator = pkcs12->create_cert_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &cert))
     {
         x509_t *x509 = (x509_t*)cert;
         if (x509->get_flags(x509) & X509_CA)
         {
             printf("[%2d] \"%Y\" (CA)\n", index++, cert->get_subject(cert));
         }
         else
         {
             printf("[%2d] \"%Y\"\n", index++, cert->get_subject(cert));
         }
     }
     enumerator->destroy(enumerator);
     printf("Private keys:\n");
     enumerator = pkcs12->create_key_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &key))
     {
         printf("[%2d] %N %d bits\n", index++, key_type_names,
                key->get_type(key), key->get_keysize(key));
     }
     enumerator->destroy(enumerator);
     return 0;
 }