strongSwan: ike_sa_t Struct Reference
ike_sa_t Struct Reference
ike_sa
#include "ike_sa.h"
Public Attributes
ike_sa_id_t *(* get_id)(ike_sa_t *this)
ike_version_t(* get_version)(ike_sa_t *this)
u_int32_t(* get_unique_id)(ike_sa_t *this)
ike_sa_state_t(* get_state)(ike_sa_t *this)
void(* set_state)(ike_sa_t *this, ike_sa_state_t state)
char *(* get_name)(ike_sa_t *this)
u_int32_t(* get_statistic)(ike_sa_t *this, statistic_t kind)
void(* set_statistic)(ike_sa_t *this, statistic_t kind, u_int32_t value)
host_t *(* get_my_host)(ike_sa_t *this)
void(* set_my_host)(ike_sa_t *this, host_t *me)
host_t *(* get_other_host)(ike_sa_t *this)
void(* set_other_host)(ike_sa_t *this, host_t *other)
void(* float_ports)(ike_sa_t *this)
void(* update_hosts)(ike_sa_t *this, host_t *me, host_t *other, bool force)
identification_t *(* get_my_id)(ike_sa_t *this)
void(* set_my_id)(ike_sa_t *this, identification_t *me)
identification_t *(* get_other_id)(ike_sa_t *this)
identification_t *(* get_other_eap_id)(ike_sa_t *this)
void(* set_other_id)(ike_sa_t *this, identification_t *other)
ike_cfg_t *(* get_ike_cfg)(ike_sa_t *this)
void(* set_ike_cfg)(ike_sa_t *this, ike_cfg_t *config)
peer_cfg_t *(* get_peer_cfg)(ike_sa_t *this)
void(* set_peer_cfg)(ike_sa_t *this, peer_cfg_t *config)
auth_cfg_t *(* get_auth_cfg)(ike_sa_t *this, bool local)
void(* add_auth_cfg)(ike_sa_t *this, bool local, auth_cfg_t *cfg)
enumerator_t *(* create_auth_cfg_enumerator)(ike_sa_t *this, bool local)
proposal_t *(* get_proposal)(ike_sa_t *this)
void(* set_proposal)(ike_sa_t *this, proposal_t *proposal)
void(* set_message_id)(ike_sa_t *this, bool initiate, u_int32_t mid)
void(* add_peer_address)(ike_sa_t *this, host_t *host)
enumerator_t *(* create_peer_address_enumerator)(ike_sa_t *this)
void(* clear_peer_addresses)(ike_sa_t *this)
bool(* has_mapping_changed)(ike_sa_t *this, chunk_t hash)
void(* enable_extension)(ike_sa_t *this, ike_extension_t extension)
bool(* supports_extension)(ike_sa_t *this, ike_extension_t extension)
void(* set_condition)(ike_sa_t *this, ike_condition_t condition, bool enable)
bool(* has_condition)(ike_sa_t *this, ike_condition_t condition)
u_int32_t(* get_pending_updates)(ike_sa_t *this)
void(* set_pending_updates)(ike_sa_t *this, u_int32_t updates)
status_t(* initiate)(ike_sa_t *this, child_cfg_t *child_cfg, u_int32_t reqid, traffic_selector_t *tsi, traffic_selector_t *tsr)
status_t(* retry_initiate)(ike_sa_t *this)
status_t(* delete)(ike_sa_t *this)
status_t(* roam)(ike_sa_t *this, bool address)
status_t(* process_message)(ike_sa_t *this, message_t *message)
status_t(* generate_message)(ike_sa_t *this, message_t *message, packet_t **packet)
status_t(* generate_message_fragmented)(ike_sa_t *this, message_t *message, enumerator_t **packets)
status_t(* retransmit)(ike_sa_t *this, u_int32_t message_id)
status_t(* send_dpd)(ike_sa_t *this)
void(* send_keepalive)(ike_sa_t *this)
keymat_t *(* get_keymat)(ike_sa_t *this)
void(* add_child_sa)(ike_sa_t *this, child_sa_t *child_sa)
child_sa_t *(* get_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi, bool inbound)
int(* get_child_count)(ike_sa_t *this)
enumerator_t *(* create_child_sa_enumerator)(ike_sa_t *this)
void(* remove_child_sa)(ike_sa_t *this, enumerator_t *enumerator)
status_t(* rekey_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi)
status_t(* delete_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi, bool expired)
status_t(* destroy_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi)
status_t(* rekey)(ike_sa_t *this)
status_t(* reauth)(ike_sa_t *this)
status_t(* reestablish)(ike_sa_t *this)
status_t(* set_auth_lifetime)(ike_sa_t *this, u_int32_t lifetime)
void(* add_virtual_ip)(ike_sa_t *this, bool local, host_t *ip)
void(* clear_virtual_ips)(ike_sa_t *this, bool local)
enumerator_t *(* create_virtual_ip_enumerator)(ike_sa_t *this, bool local)
void(* add_configuration_attribute)(ike_sa_t *this, attribute_handler_t *handler, configuration_attribute_type_t type, chunk_t data)
enumerator_t *(* create_attribute_enumerator)(ike_sa_t *this)
void(* set_kmaddress)(ike_sa_t *this, host_t *local, host_t *remote)
enumerator_t *(* create_task_enumerator)(ike_sa_t *this, task_queue_t queue)
void(* flush_queue)(ike_sa_t *this, task_queue_t queue)
void(* queue_task)(ike_sa_t *this, task_t *task)
void(* inherit_pre)(ike_sa_t *this, ike_sa_t *other)
void(* inherit_post)(ike_sa_t *this, ike_sa_t *other)
void(* reset)(ike_sa_t *this)
void(* destroy)(ike_sa_t *this)
Detailed Description
Class ike_sa_t representing an IKE_SA.
An IKE_SA contains crypto information related to a connection with a peer. It contains multiple IPsec CHILD_SA, for which it is responsible. All traffic is handled by an IKE_SA, using the task manager and its tasks.
Definition at line 310 of file ike_sa.h.
Member Data Documentation
void(* ike_sa_t::add_auth_cfg)(ike_sa_t *this, bool local, auth_cfg_t *cfg)
Insert a completed authentication round.
Parameters
local TRUE for own rules, FALSE for others constraints
cfg auth config to append
Definition at line 494 of file ike_sa.h.
Referenced by process_ike_update().
void(* ike_sa_t::add_child_sa)(ike_sa_t *this, child_sa_t *child_sa)
Associates a child SA to this IKE SA
Parameters
child_sa child_sa to add
Definition at line 855 of file ike_sa.h.
Referenced by METHOD(), and process_child_add().
void(* ike_sa_t::add_configuration_attribute)(ike_sa_t *this, attribute_handler_t *handler, configuration_attribute_type_t type, chunk_t data)
Register a configuration attribute to the IKE_SA.
If an IRAS sends a configuration attribute it is installed and registered at the IKE_SA. Attributes are inherit()ed and get released when the IKE_SA is closed.
Unhandled attributes are passed as well, but with a NULL handler. They do not get released.
Parameters
handler handler installed the attribute, use for release()
type configuration attribute type
data associated attribute data
Definition at line 1012 of file ike_sa.h.
void(* ike_sa_t::add_peer_address)(ike_sa_t *this, host_t *host)
Add an additional address for the peer.
In MOBIKE, a peer may transmit additional addresses where it is reachable. These are stored in the IKE_SA. The own list of addresses is not stored, they are queried from the kernel when required.
Parameters
host host to add to list
Definition at line 539 of file ike_sa.h.
Referenced by process_ike_update().
void(* ike_sa_t::add_virtual_ip)(ike_sa_t *this, bool local, host_t *ip)
Add a virtual IP to use for this IKE_SA and its children.
The virtual IP is assigned per IKE_SA, not per CHILD_SA. It has the same lifetime as the IKE_SA.
Parameters
local TRUE to set local address, FALSE for remote
ip IP to set as virtual IP
Definition at line 981 of file ike_sa.h.
Referenced by METHOD(), and process_ike_update().
void(* ike_sa_t::clear_peer_addresses)(ike_sa_t *this)
Remove all known addresses of the peer.
Definition at line 551 of file ike_sa.h.
Referenced by process_ike_update().
void(* ike_sa_t::clear_virtual_ips)(ike_sa_t *this, bool local)
Clear all virtual IPs stored on this IKE_SA.
Parameters
local TRUE to clear local addresses, FALSE for remote
Definition at line 988 of file ike_sa.h.
Referenced by adopt_children_and_vips(), METHOD(), and process_ike_update().
enumerator_t*(* ike_sa_t::create_attribute_enumerator)(ike_sa_t *this)
Create an enumerator over received configuration attributes.
The resulting enumerator is over the configuration_attribute_type_t type, a value chunk_t followed by a bool flag. The boolean flag indicates if the attribute has been handled by an attribute handler.
Returns
enumerator over type, value and the "handled" flag.
Definition at line 1025 of file ike_sa.h.
enumerator_t*(* ike_sa_t::create_auth_cfg_enumerator)(ike_sa_t *this, bool local)
Create an enumerator over added authentication rounds.
Parameters
local TRUE for own rules, FALSE for others constraints
Returns
enumerator over auth_cfg_t
Definition at line 502 of file ike_sa.h.
Referenced by build_cert_chain(), check_constraints(), has_invalid_certs(), METHOD(), and stroke_export().
enumerator_t*(* ike_sa_t::create_child_sa_enumerator)(ike_sa_t *this)
Create an enumerator over all CHILD_SAs.
Returns
enumerator
Definition at line 880 of file ike_sa.h.
Referenced by adopt_children_and_vips(), CALLBACK(), checkout_ikesa(), cleanup_sas(), clear_start_action(), close_child(), collect_stats(), find_reqid(), get_retry_delay(), METHOD(), rekey_child(), rekey_children(), request_query_ikesa(), and status().
enumerator_t*(* ike_sa_t::create_peer_address_enumerator)(ike_sa_t *this)
Create an enumerator over all known addresses of the peer.
Returns
enumerator over addresses
Definition at line 546 of file ike_sa.h.
Referenced by METHOD().
enumerator_t*(* ike_sa_t::create_task_enumerator)(ike_sa_t *this, task_queue_t queue)
Create enumerator over a task queue of this IKE_SA.
Parameters
queue type to enumerate
Returns
enumerator over task_t
Definition at line 1044 of file ike_sa.h.
Referenced by check_queued_tasks(), list_task_queue(), and log_task_q().
enumerator_t*(* ike_sa_t::create_virtual_ip_enumerator)(ike_sa_t *this, bool local)
Create an enumerator over virtual IPs.
Parameters
local TRUE to get local virtual IP, FALSE for remote
Returns
enumerator over host_t*
Definition at line 996 of file ike_sa.h.
Referenced by add_entry(), add_exclude_async(), add_ike_sa_parameters(), adopt_children_and_vips(), get_dynamic_hosts(), has_vip(), list_vips(), METHOD(), process_ike_update(), push_vip_env(), remove_entry(), signal_ipv4_config(), and sync_vips().
status_t(* ike_sa_t::delete)(ike_sa_t *this)
Initiates the deletion of an IKE_SA.
Sends a delete message to the remote peer and waits for its response. If the response comes in, or a timeout occurs, the IKE SA gets deleted.
Returns
SUCCESS if deletion is initialized
DESTROY_ME, if the IKE_SA is not in an established state and can not be deleted (but destroyed).
Definition at line 747 of file ike_sa.h.
Referenced by enforce_replace(), and METHOD().
status_t(* ike_sa_t::delete_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi, bool expired)
Close the CHILD SA with the specified protocol/SPI.
Looks for a CHILD SA owned by this IKE_SA, deletes it and notify's the remote peer about the delete. The associated states and policies in the kernel get deleted, if they exist.
Parameters
protocol protocol of the SA
spi inbound SPI of the CHILD_SA
expired TRUE if CHILD_SA is expired
Returns
NOT_FOUND, if IKE_SA has no such CHILD_SA
SUCCESS, if delete message sent
Definition at line 916 of file ike_sa.h.
Referenced by METHOD(), and rekey_children().
void(* ike_sa_t::destroy)(ike_sa_t *this)
Destroys a ike_sa_t object.
Definition at line 1088 of file ike_sa.h.
Referenced by checkout_ikesa(), cleanup(), METHOD(), and process_ike_add().
status_t(* ike_sa_t::destroy_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi)
Destroy a CHILD SA with the specified protocol/SPI.
Looks for a CHILD SA owned by this IKE_SA and destroys it.
Parameters
protocol protocol of the SA
spi inbound SPI of the CHILD_SA
Returns
NOT_FOUND, if IKE_SA has no such CHILD_SA
SUCCESS
Definition at line 930 of file ike_sa.h.
Referenced by process_child_delete().
void(* ike_sa_t::enable_extension)(ike_sa_t *this, ike_extension_t extension)
Enable an extension the peer supports.
If support for an IKE extension is detected, this method is called to enable that extension and behave accordingly.
Parameters
extension extension to enable
Definition at line 569 of file ike_sa.h.
Referenced by set_extension().
void(* ike_sa_t::float_ports)(ike_sa_t *this)
Float to port 4500 (e.g. if a NAT is detected).
The port of either endpoint is changed only if it is currently set to the default value of 500.
Definition at line 404 of file ike_sa.h.
void(* ike_sa_t::flush_queue)(ike_sa_t *this, task_queue_t queue)
Flush a task queue, cancelling all tasks in it.
Parameters
queue queue type to flush
Definition at line 1051 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::generate_message)(ike_sa_t *this, message_t *message, packet_t **packet)
Generate an IKE message to send it to the peer.
This method generates all payloads in the message and encrypts/signs the packet.
Parameters
message message to generate
packet generated output packet
Returns
SUCCESS
FAILED
DESTROY_ME if this IKE_SA MUST be deleted
Definition at line 791 of file ike_sa.h.
status_t(* ike_sa_t::generate_message_fragmented)(ike_sa_t *this, message_t *message, enumerator_t **packets)
Generate an IKE message to send it to the peer. If enabled and supported it will be fragmented.
This method generates all payloads in the message and encrypts/signs the packet/fragments.
Parameters
message message to generate
packets enumerator of generated packet_t* (are not destroyed with the enumerator)
Returns
SUCCESS
FAILED
DESTROY_ME if this IKE_SA MUST be deleted
Definition at line 809 of file ike_sa.h.
auth_cfg_t*(* ike_sa_t::get_auth_cfg)(ike_sa_t *this, bool local)
Get the authentication config with rules of the current auth round.
Parameters
local TRUE for local rules, FALSE for remote constraints
Returns
current cfg
Definition at line 486 of file ike_sa.h.
Referenced by add_radius_attribute(), enforce_recommendation(), METHOD(), process_class(), process_eap(), and process_filter_id().
int(* ike_sa_t::get_child_count)(ike_sa_t *this)
Get the number of CHILD_SAs.
Returns
number of CHILD_SAs
Definition at line 873 of file ike_sa.h.
child_sa_t*(* ike_sa_t::get_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi, bool inbound)
Get a CHILD_SA identified by protocol and SPI.
Parameters
protocol protocol of the SA
spi SPI of the CHILD_SA
inbound TRUE if SPI is inbound, FALSE if outbound
Returns
child_sa, or NULL if none found
Definition at line 865 of file ike_sa.h.
Referenced by process_child_delete().
ike_sa_id_t*(* ike_sa_t::get_id)(ike_sa_t *this)
Get the id of the SA.
Returned ike_sa_id_t object is not getting cloned!
Returns
ike_sa's ike_sa_id_t
Definition at line 319 of file ike_sa.h.
Referenced by add_exclude(), add_include(), add_matching_ike_sas(), check_queued_tasks(), check_systime(), delete_all_async(), eap_radius_accounting_start_interim(), enforce_replace(), has_split_includes(), initiate_callback(), list_ike(), liveness(), log_ike_sa(), METHOD(), narrow_initiator(), process_ike_add(), process_ike_update(), rekey_ike(), rekey_segment(), remove_include(), request_query_ikesa(), schedule_timeout(), send_start(), send_stop(), sync_vips(), and update_usage().
ike_cfg_t*(* ike_sa_t::get_ike_cfg)(ike_sa_t *this)
Get the config used to setup this IKE_SA.
Returns
ike_config
Definition at line 457 of file ike_sa.h.
Referenced by METHOD().
keymat_t*(* ike_sa_t::get_keymat)(ike_sa_t *this)
Get the keying material of this IKE_SA.
Returns
per IKE_SA keymat instance
Definition at line 848 of file ike_sa.h.
Referenced by build_auth(), calculate_wire_size(), child_create_create(), ike_init_create(), isakmp_natd_create(), METHOD(), phase1_create(), process_child_add(), process_ike_add(), process_ike_iv(), quick_mode_create(), and rebuild_auth().
host_t*(* ike_sa_t::get_my_host)(ike_sa_t *this)
Get the own host address.
Returns
host address
Definition at line 375 of file ike_sa.h.
Referenced by add_exclude_async(), add_ike_sa_parameters(), eap_radius_build_attributes(), eap_tnc_create(), get_dynamic_hosts(), invoke_once(), list_ike(), log_ike_sa(), METHOD(), process_child_add(), process_ike_update(), rekey_child(), request_query_ikesa(), and signal_ipv4_config().
identification_t*(* ike_sa_t::get_my_id)(ike_sa_t *this)
Get the own identification.
Returns
identification
Definition at line 422 of file ike_sa.h.
Referenced by add_radius_attribute(), invoke_once(), list_ike(), log_ike_sa(), METHOD(), process_ike_update(), and request_query_ikesa().
char*(* ike_sa_t::get_name)(ike_sa_t *this)
Get the name of the connection this IKE_SA uses.
Returns
name
Definition at line 352 of file ike_sa.h.
Referenced by add_entry(), add_ike_sa_parameters(), build_cert_chain(), CALLBACK(), check_systime(), close_ike(), create_shunt_name(), eap_radius_build_attributes(), liveness(), log_ike_sa(), log_task_q(), log_vici(), METHOD(), process_ike_update(), rekey_ike(), request_control_terminate(), request_query_ikesa(), status(), stroke_export(), and terminate().
identification_t*(* ike_sa_t::get_other_eap_id)(ike_sa_t *this)
Get the others peer identity, but prefer an EAP-Identity.
Returns
EAP or IKEv2 identity
Definition at line 443 of file ike_sa.h.
Referenced by add_entry(), add_ike_sa_parameters(), add_matching_ike_sas(), get_identity(), invoke_once(), list_ike(), log_ike_sa(), and METHOD().
host_t*(* ike_sa_t::get_other_host)(ike_sa_t *this)
Get the other peers host address.
Returns
host address
Definition at line 389 of file ike_sa.h.
Referenced by add_entry(), add_ike_sa_parameters(), eap_radius_build_attributes(), eap_tnc_create(), enable_disable(), enforce_replace(), get_dynamic_hosts(), invoke_once(), list_ike(), log_ike_sa(), METHOD(), process_child_add(), process_ike_update(), rekey_segment(), request_query_ikesa(), and status().
identification_t*(* ike_sa_t::get_other_id)(ike_sa_t *this)
Get the other peer's identification.
Returns
identification
Definition at line 436 of file ike_sa.h.
Referenced by enforce_recommendation(), invoke_once(), list_ike(), log_ike_sa(), METHOD(), process_ike_update(), request_query_ikesa(), and status().
peer_cfg_t*(* ike_sa_t::get_peer_cfg)(ike_sa_t *this)
Get the peer config used by this IKE_SA.
Returns
peer_config
Definition at line 471 of file ike_sa.h.
Referenced by build_cert_chain(), connect_(), create_fragment(), find_child_cfg(), get_ike_sa_name(), have_pool(), initiate_connection(), log_ike_sa(), METHOD(), and process_ike_update().
u_int32_t(* ike_sa_t::get_pending_updates)(ike_sa_t *this)
Get the number of queued MOBIKE address updates.
Returns
number of pending updates
Definition at line 600 of file ike_sa.h.
Referenced by METHOD().
proposal_t*(* ike_sa_t::get_proposal)(ike_sa_t *this)
Get the selected proposal of this IKE_SA.
Returns
selected proposal
Definition at line 509 of file ike_sa.h.
Referenced by list_ike(), log_ike_sa(), and METHOD().
ike_sa_state_t(* ike_sa_t::get_state)(ike_sa_t *this)
Get the state of the IKE_SA.
Returns
state of the IKE_SA
Definition at line 338 of file ike_sa.h.
Referenced by enable_disable(), get_retry_delay(), list_ike(), log_ike_sa(), METHOD(), process_ike_update(), rekey_segment(), reload_metadata(), and request_query_ikesa().
u_int32_t(* ike_sa_t::get_statistic)(ike_sa_t *this, statistic_t kind)
Get statistic values from the IKE_SA.
Parameters
kind kind of requested value
Returns
value as integer
Definition at line 360 of file ike_sa.h.
Referenced by list_ike(), log_ike_sa(), and METHOD().
u_int32_t(* ike_sa_t::get_unique_id)(ike_sa_t *this)
Get the numerical ID uniquely defining this IKE_SA.
Returns
unique ID
Definition at line 331 of file ike_sa.h.
Referenced by add_entry(), add_ike_sa_parameters(), CALLBACK(), check_systime(), close_ike(), create_shunt_name(), disconnect(), eap_radius_accounting_start_interim(), eap_radius_build_attributes(), initiate_cb(), invoke_once(), list_ike(), log_ike_sa(), log_task_q(), log_vici(), lookup_queue(), METHOD(), process_cfg_attributes(), push_dns_env(), release_unclaimed(), remove_queue(), request_control_terminate(), request_query_ikesa(), send_start(), and terminate().
ike_version_t(* ike_sa_t::get_version)(ike_sa_t *this)
Gets the IKE version of the SA
Definition at line 324 of file ike_sa.h.
Referenced by list_ike(), log_ike_sa(), METHOD(), process_child_add(), process_ike_add(), process_ike_iv(), process_ike_update(), and task_manager_create().
bool(* ike_sa_t::has_condition)(ike_sa_t *this, ike_condition_t condition)
Check if a condition flag is set.
Parameters
condition condition to check
Returns
TRUE if condition flag set, FALSE otherwise
Definition at line 593 of file ike_sa.h.
Referenced by add_condition(), copy_condition(), ike_me_create(), invoke_once(), METHOD(), process_child_add(), rekey_children(), and request_query_ikesa().
bool(* ike_sa_t::has_mapping_changed)(ike_sa_t *this, chunk_t hash)
Check if mappings have changed on a NAT for our source address.
Parameters
hash received DESTINATION_IP hash
Returns
TRUE if mappings have changed
Definition at line 559 of file ike_sa.h.
void(* ike_sa_t::inherit_post)(ike_sa_t *this, ike_sa_t *other)
Inherit all attributes of other to this after rekeying.
When rekeying is completed, all CHILD_SAs, the virtual IP and all outstanding tasks are moved from other to this.
Parameters
other other IKE SA to inherit from
Definition at line 1078 of file ike_sa.h.
Referenced by process_ike_add().
void(* ike_sa_t::inherit_pre)(ike_sa_t *this, ike_sa_t *other)
Inherit required attributes to new SA before rekeying.
Some properties of the SA must be applied before starting IKE_SA rekeying, such as the configuration or support extensions.
Parameters
other other IKE_SA to inherit from
Definition at line 1068 of file ike_sa.h.
Referenced by process_ike_add().
status_t(* ike_sa_t::initiate)(ike_sa_t *this, child_cfg_t *child_cfg, u_int32_t reqid, traffic_selector_t *tsi, traffic_selector_t *tsr)
Initiate a new connection.
The configs are owned by the IKE_SA after the call. If the initiate is triggered by a packet, traffic selectors of the packet can be added to the CHILD_SA.
Parameters
child_cfg child config to create CHILD from
reqid reqid to use for CHILD_SA, 0 assigne uniquely
tsi source of triggering packet
tsr destination of triggering packet.
Returns
SUCCESS if initialization started
DESTROY_ME if initialization failed
Definition at line 721 of file ike_sa.h.
Referenced by connect_(), initiate_connection(), and METHOD().
status_t(* ike_sa_t::process_message)(ike_sa_t *this, message_t *message)
Processes an incoming IKE message.
Message processing may fail. If a critical failure occurs, process_message() return DESTROY_ME. Then the caller must destroy the IKE_SA immediately, as it is unusable.
Parameters
message message to process
Returns
SUCCESS
FAILED
DESTROY_ME if this IKE_SA MUST be deleted
Definition at line 776 of file ike_sa.h.
Referenced by METHOD().
void(* ike_sa_t::queue_task)(ike_sa_t *this, task_t *task)
Queue a task for initiaton to the task manager.
Parameters
task task to queue
Definition at line 1058 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::reauth)(ike_sa_t *this)
Reauthenticate the IKE_SA.
Triggers a new IKE_SA that replaces this one. IKEv1 implicitly inherits all Quick Modes, while IKEv2 recreates all active and queued CHILD_SAs in the new IKE_SA.
Returns
DESTROY_ME to destroy the IKE_SA
Definition at line 950 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::reestablish)(ike_sa_t *this)
Restablish the IKE_SA.
Reestablish an IKE_SA after it has been closed.
Returns
DESTROY_ME to destroy the IKE_SA
Definition at line 959 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::rekey)(ike_sa_t *this)
Rekey the IKE_SA.
Sets up a new IKE_SA, moves all CHILDs to it and deletes this IKE_SA.
Returns
- SUCCESS, if IKE_SA rekeying initiated
Definition at line 939 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::rekey_child_sa)(ike_sa_t *this, protocol_id_t protocol, u_int32_t spi)
Rekey the CHILD SA with the specified reqid.
Looks for a CHILD SA owned by this IKE_SA, and start the rekeing.
Parameters
protocol protocol of the SA
spi inbound SPI of the CHILD_SA
Returns
NOT_FOUND, if IKE_SA has no such CHILD_SA
SUCCESS, if rekeying initiated
Definition at line 900 of file ike_sa.h.
Referenced by METHOD(), and rekey_children().
void(* ike_sa_t::remove_child_sa)(ike_sa_t *this, enumerator_t *enumerator)
Remove the CHILD_SA the given enumerator points to from this IKE_SA.
Parameters
enumerator enumerator pointing to CHILD_SA
Definition at line 887 of file ike_sa.h.
Referenced by adopt_children_and_vips(), and METHOD().
void(* ike_sa_t::reset)(ike_sa_t *this)
Reset the IKE_SA, useable when initiating fails
Definition at line 1083 of file ike_sa.h.
status_t(* ike_sa_t::retransmit)(ike_sa_t *this, u_int32_t message_id)
Retransmits a request.
Parameters
message_id ID of the request to retransmit
Returns
SUCCESS
NOT_FOUND if request doesn't have to be retransmited
Definition at line 820 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::retry_initiate)(ike_sa_t *this)
Retry initiation of this IKE_SA after it got deferred previously.
Returns
SUCCESS if initiation deferred or started
DESTROY_ME if initiation failed
Definition at line 732 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::roam)(ike_sa_t *this, bool address)
Update IKE_SAs after network interfaces have changed.
Whenever the network interface configuration changes, the kernel interface calls roam() on each IKE_SA. The IKE_SA then checks if the new network config requires changes, and handles appropriate. If MOBIKE is supported, addresses are updated; If not, the tunnel is restarted.
Parameters
address TRUE if address list changed, FALSE otherwise
Returns
SUCCESS, FAILED, DESTROY_ME
Definition at line 761 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::send_dpd)(ike_sa_t *this)
Sends a DPD request to the peer.
To check if a peer is still alive, periodic empty INFORMATIONAL messages are sent if no other traffic was received.
Returns
SUCCESS
DESTROY_ME, if peer did not respond
Definition at line 833 of file ike_sa.h.
Referenced by METHOD().
void(* ike_sa_t::send_keepalive)(ike_sa_t *this)
Sends a keep alive packet.
To refresh NAT tables in a NAT router between the peers, periodic empty UDP packets are sent if no other traffic was sent.
Definition at line 841 of file ike_sa.h.
Referenced by METHOD().
status_t(* ike_sa_t::set_auth_lifetime)(ike_sa_t *this, u_int32_t lifetime)
Set the lifetime limit received/to send in a AUTH_LIFETIME notify.
If the IKE_SA is already ESTABLISHED, an INFORMATIONAL is sent with an AUTH_LIFETIME notify. The call never fails on unestablished SAs.
Parameters
lifetime lifetime in seconds
Returns
DESTROY_ME to destroy the IKE_SA
Definition at line 970 of file ike_sa.h.
Referenced by apply_lifetime(), and process_timeout().
void(* ike_sa_t::set_condition)(ike_sa_t *this, ike_condition_t condition, bool enable)
Enable/disable a condition flag for this IKE_SA.
Parameters
condition condition to enable/disable
enable TRUE to enable condition, FALSE to disable
Definition at line 585 of file ike_sa.h.
Referenced by METHOD(), and set_condition().
void(* ike_sa_t::set_ike_cfg)(ike_sa_t *this, ike_cfg_t *config)
Set the config to setup this IKE_SA.
Parameters
config ike_config to use
Definition at line 464 of file ike_sa.h.
void(* ike_sa_t::set_kmaddress)(ike_sa_t *this, host_t *local, host_t *remote)
Set local and remote host addresses to be used for IKE.
These addresses are communicated via the KMADDRESS field of a MIGRATE message sent via the NETLINK or PF _KEY kernel socket interface.
Parameters
local local kmaddress
remote remote kmaddress
Definition at line 1036 of file ike_sa.h.
Referenced by METHOD().
void(* ike_sa_t::set_message_id)(ike_sa_t *this, bool initiate, u_int32_t mid)
Set the message id of the IKE_SA.
The IKE_SA stores two message IDs, one for initiating exchanges (send) and one to respond to exchanges (expect).
Parameters
initiate TRUE to set message ID for initiating
mid message id to set
Definition at line 527 of file ike_sa.h.
Referenced by process_ike_mid().
void(* ike_sa_t::set_my_host)(ike_sa_t *this, host_t *me)
Set the own host address.
Parameters
me host address
Definition at line 382 of file ike_sa.h.
Referenced by METHOD(), and process_ike_update().
void(* ike_sa_t::set_my_id)(ike_sa_t *this, identification_t *me)
Set the own identification.
Parameters
me identification
Definition at line 429 of file ike_sa.h.
Referenced by process_ike_update().
void(* ike_sa_t::set_other_host)(ike_sa_t *this, host_t *other)
Set the others host address.
Parameters
other host address
Definition at line 396 of file ike_sa.h.
Referenced by METHOD(), process_ike_add(), and process_ike_update().
void(* ike_sa_t::set_other_id)(ike_sa_t *this, identification_t *other)
Set the other peer's identification.
Parameters
other identification
Definition at line 450 of file ike_sa.h.
Referenced by METHOD(), and process_ike_update().
void(* ike_sa_t::set_peer_cfg)(ike_sa_t *this, peer_cfg_t *config)
Set the peer config to use with this IKE_SA.
Parameters
config peer_config to use
Definition at line 478 of file ike_sa.h.
Referenced by connect_(), initiate_connection(), METHOD(), process_ike_update(), and trigger_mbb_reauth().
void(* ike_sa_t::set_pending_updates)(ike_sa_t *this, u_int32_t updates)
Set the number of queued MOBIKE address updates.
Parameters
updates number of pending updates
Definition at line 607 of file ike_sa.h.
Referenced by METHOD().
void(* ike_sa_t::set_proposal)(ike_sa_t *this, proposal_t *proposal)
Set the proposal selected for this IKE_SA.
Parameters
selected proposal
Definition at line 516 of file ike_sa.h.
Referenced by process_ike_add().
void(* ike_sa_t::set_state)(ike_sa_t *this, ike_sa_state_t state)
Set the state of the IKE_SA.
Parameters
state state to set for the IKE_SA
Definition at line 345 of file ike_sa.h.
Referenced by enable_disable(), process_ike_add(), and process_ike_update().
void(* ike_sa_t::set_statistic)(ike_sa_t *this, statistic_t kind, u_int32_t value)
Set statistic value of the IKE_SA.
Parameters
kind kind of value to update
value value as integer
Definition at line 368 of file ike_sa.h.
bool(* ike_sa_t::supports_extension)(ike_sa_t *this, ike_extension_t extension)
Check if the peer supports an extension.
Parameters
extension extension to check for support
Returns
TRUE if peer supports it, FALSE otherwise
Definition at line 577 of file ike_sa.h.
Referenced by copy_extension(), get_encap(), get_nat_d_payload_type(), get_nat_oa_payload_type(), lookup_queue(), METHOD(), process_cfg_attributes(), rekey_children(), and request_query_ikesa().
void(* ike_sa_t::update_hosts)(ike_sa_t *this, host_t *me, host_t *other, bool force)
Update the IKE_SAs host.
Hosts may be NULL to use current host.
Parameters
me new local host address, or NULL
other new remote host address, or NULL
force force update
Definition at line 415 of file ike_sa.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ike_sa.h