strongSwan: gateway_controller.c File Reference
gateway_controller.c File Reference
#include "gateway_controller.h"
#include "../manager.h"
#include "../gateway.h"
#include <library.h>
Classes
struct private_gateway_controller_t
Typedefs
typedef struct
private_gateway_controller_t private_gateway_controller_t
Functions
static void list (private_gateway_controller_t *this, fast_request_t *request)
static void _select (private_gateway_controller_t *this, fast_request_t *request)
METHOD (fast_controller_t, get_name, char *, private_gateway_controller_t *this)
METHOD (fast_controller_t, handle, void, private_gateway_controller_t *this, fast_request_t *request, char *action, char *p2, char *p3, char *p4, char *p5)
METHOD (fast_controller_t, destroy, void, private_gateway_controller_t *this)
fast_controller_t * gateway_controller_create (fast_context_t *context, void *param)
Typedef Documentation
typedef struct private_gateway_controller_t private_gateway_controller_t
Definition at line 23 of file gateway_controller.c.
Function Documentation
static void _select (private_gateway_controller_t * this, fast_request_t * request) static
Definition at line 69 of file gateway_controller.c.
References fast_request_t::get_query_data, id, and fast_request_t::redirect.
Referenced by METHOD().
 {
     char *id;
     id = request->get_query_data(request, "gateway");
     if (id)
     {
         if (this->manager->select_gateway(this->manager, atoi(id)))
         {
             request->redirect(request, "ikesa/list");
             return;
         }
     }
     request->redirect(request, "gateway/list");
 }
static void list (private_gateway_controller_t * this, fast_request_t * request) static
Definition at line 42 of file gateway_controller.c.
References enumerator_t::destroy, enumerator_t::enumerate, id, name, port, fast_request_t::render, fast_request_t::set, and fast_request_t::setf.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     char *name, *address;
     int id, port;
     enumerator = this->manager->create_gateway_enumerator(this->manager);
     while (enumerator->enumerate(enumerator, &id, &name, &port, &address))
     {
         request->setf(request, "gateways.%d.name=%s", id, name);
         if (port)
         {
             request->setf(request, "gateways.%d.address=tcp://%s:%d",
                           id, address, port);
         }
         else
         {
             request->setf(request, "gateways.%d.address=unix://%s",
                           id, IPSEC_PIDDIR"/charon.xml");
         }
     }
     enumerator->destroy(enumerator);
     request->set(request, "action", "select");
     request->set(request, "title", "Choose gateway");
     request->render(request, "templates/gateway/list.cs");
 }
METHOD (fast_controller_t , get_name , char * , private_gateway_controller_t * this)
Definition at line 85 of file gateway_controller.c.
 {
     return "gateway";
 }
METHOD (fast_controller_t , handle , void , private_gateway_controller_t * this, fast_request_t * request, char * action, char * p2, char * p3, char * p4, char * p5)
Definition at line 91 of file gateway_controller.c.
References _select(), list(), fast_request_t::redirect, and streq().
 {
     if (!this->manager->logged_in(this->manager))
     {
         return request->redirect(request, "auth/login");
     }
     if (action)
     {
         if (streq(action, "list"))
         {
             return list(this, request);
         }
         else if (streq(action, "select"))
         {
             return _select(this, request);
         }
     }
     request->redirect(request, "gateway/list");
 }
METHOD (fast_controller_t , destroy , void , private_gateway_controller_t * this)
Definition at line 113 of file gateway_controller.c.
References free().
 {
     free(this);
 }