strongSwan: aesni_key.c File Reference
aesni_key.c File Reference
#include "aesni_key.h"
Classes
struct private_aesni_key_t
Macros
#define AES128_ROUNDS 10
#define AES192_ROUNDS 12
#define AES256_ROUNDS 14
Typedefs
typedef struct private_aesni_key_t private_aesni_key_t
Functions
static void reverse_key (aesni_key_t *this)
static __m128i assist128 (__m128i a, __m128i b)
static void expand128 (__m128i *key, __m128i *schedule)
static __m128i assist192 (__m128i b, __m128i c, __m128i *a)
static __m128i _mm_shuffle_i00 (__m128i a, __m128i b)
static __m128i _mm_shuffle_i01 (__m128i a, __m128i b)
static void expand192 (__m128i *key, __m128i *schedule)
static __m128i assist256_1 (__m128i a, __m128i b)
static __m128i assist256_2 (__m128i a, __m128i b)
static void expand256 (__m128i *key, __m128i *schedule)
METHOD (aesni_key_t, destroy, void, private_aesni_key_t *this)
aesni_key_t * aesni_key_create (bool encrypt, chunk_t key)
Macro Definition Documentation
#define AES128_ROUNDS 10
Rounds used for each AES key size
Definition at line 21 of file aesni_key.c.
Referenced by aesni_key_create().
#define AES192_ROUNDS 12
Definition at line 22 of file aesni_key.c.
Referenced by aesni_key_create().
#define AES256_ROUNDS 14
Definition at line 23 of file aesni_key.c.
Referenced by aesni_key_create().
Typedef Documentation
typedef struct private_aesni_key_t private_aesni_key_t
Definition at line 25 of file aesni_key.c.
Function Documentation
static __m128i _mm_shuffle_i00 (__m128i a, __m128i b) static
return a[63:0] | b[63:0] << 64
Definition at line 125 of file aesni_key.c.
Referenced by expand192().
 {
     return (__m128i)_mm_shuffle_pd((__m128d)a, (__m128d)b, 0);
 }
static __m128i _mm_shuffle_i01 (__m128i a, __m128i b) static
return a[127:64] >> 64 | b[63:0] << 64
Definition at line 133 of file aesni_key.c.
Referenced by expand192().
 {
     return (__m128i)_mm_shuffle_pd((__m128d)a, (__m128d)b, 1);
 }
static __m128i assist128 (__m128i a, __m128i b) static
Assist in creating a 128-bit round key
Definition at line 63 of file aesni_key.c.
References a, and c.
Referenced by expand128().
 {
     __m128i c;
     b = _mm_shuffle_epi32(b ,0xff);
     c = _mm_slli_si128(a, 0x04);
     a = _mm_xor_si128(a, c);
     c = _mm_slli_si128(c, 0x04);
     a = _mm_xor_si128(a, c);
     c = _mm_slli_si128(c, 0x04);
     a = _mm_xor_si128(a, c);
     a = _mm_xor_si128(a, b);
     return a;
 }
static __m128i assist192 (__m128i b, __m128i c, __m128i * a) static
Assist in creating a 192-bit round key
Definition at line 102 of file aesni_key.c.
Referenced by expand192().
 {
     __m128i t;
      b = _mm_shuffle_epi32(b, 0x55);
      t = _mm_slli_si128(*a, 0x04);
     *a = _mm_xor_si128(*a, t);
      t = _mm_slli_si128(t, 0x04);
     *a = _mm_xor_si128(*a, t);
      t = _mm_slli_si128(t, 0x04);
     *a = _mm_xor_si128(*a, t);
     *a = _mm_xor_si128(*a, b);
      b = _mm_shuffle_epi32(*a, 0xff);
      t = _mm_slli_si128(c, 0x04);
      t = _mm_xor_si128(c, t);
      t = _mm_xor_si128(t, b);
     return t;
 }
static __m128i assist256_1 (__m128i a, __m128i b) static
Assist in creating a 256-bit round key
Definition at line 176 of file aesni_key.c.
Referenced by expand256().
 {
     __m128i x, y;
     b = _mm_shuffle_epi32(b, 0xff);
     y = _mm_slli_si128(a, 0x04);
     x = _mm_xor_si128(a, y);
     y = _mm_slli_si128(y, 0x04);
     x = _mm_xor_si128 (x, y);
     y = _mm_slli_si128(y, 0x04);
     x = _mm_xor_si128(x, y);
     x = _mm_xor_si128(x, b);
     return x;
 }
static __m128i assist256_2 (__m128i a, __m128i b) static
Assist in creating a 256-bit round key
Definition at line 195 of file aesni_key.c.
Referenced by expand256().
 {
     __m128i x, y, z;
     y = _mm_aeskeygenassist_si128(a, 0x00);
     z = _mm_shuffle_epi32(y, 0xaa);
     y = _mm_slli_si128(b, 0x04);
     x = _mm_xor_si128(b, y);
     y = _mm_slli_si128(y, 0x04);
     x = _mm_xor_si128(x, y);
     y = _mm_slli_si128(y, 0x04);
     x = _mm_xor_si128(x, y);
     x = _mm_xor_si128(x, z);
     return x;
 }
static void expand128 (__m128i * key, __m128i * schedule) static
Expand a 128-bit key to encryption round keys
Definition at line 82 of file aesni_key.c.
References assist128().
Referenced by aesni_key_create().
 {
     __m128i t;
     schedule[0] = t = _mm_loadu_si128(key);
     schedule[1] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x01));
     schedule[2] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x02));
     schedule[3] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x04));
     schedule[4] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x08));
     schedule[5] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x10));
     schedule[6] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x20));
     schedule[7] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x40));
     schedule[8] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x80));
     schedule[9] = t = assist128(t, _mm_aeskeygenassist_si128(t, 0x1b));
     schedule[10]    = assist128(t, _mm_aeskeygenassist_si128(t, 0x36));
 }
static void expand192 (__m128i * key, __m128i * schedule) static
Expand a 192-bit encryption key to round keys
Definition at line 141 of file aesni_key.c.
References _mm_shuffle_i00(), _mm_shuffle_i01(), and assist192().
Referenced by aesni_key_create().
 {
     __m128i t1, t2, t3;
     schedule[0] = t1 = _mm_loadu_si128(key);
     t2 = t3 = _mm_loadu_si128(key + 1);
     t2 = assist192(_mm_aeskeygenassist_si128(t2, 0x1), t2, &t1);
     schedule[1] = _mm_shuffle_i00(t3, t1);
     schedule[2] = _mm_shuffle_i01(t1, t2);
     t2 = t3 = assist192(_mm_aeskeygenassist_si128(t2, 0x2), t2, &t1);
     schedule[3] = t1;
     t2 = assist192(_mm_aeskeygenassist_si128(t2, 0x4), t2, &t1);
     schedule[4] = _mm_shuffle_i00(t3, t1);
     schedule[5] = _mm_shuffle_i01(t1, t2);
     t2 = t3 = assist192(_mm_aeskeygenassist_si128(t2, 0x8), t2, &t1);
     schedule[6] = t1;
     t2 = assist192(_mm_aeskeygenassist_si128 (t2,0x10), t2, &t1);
     schedule[7] = _mm_shuffle_i00(t3, t1);
     schedule[8] = _mm_shuffle_i01(t1, t2);
     t2 = t3 = assist192(_mm_aeskeygenassist_si128 (t2,0x20), t2, &t1);
     schedule[9] = t1;
     t2 = assist192(_mm_aeskeygenassist_si128(t2, 0x40), t2, &t1);
     schedule[10] = _mm_shuffle_i00(t3, t1);
     schedule[11] = _mm_shuffle_i01(t1, t2);
     assist192(_mm_aeskeygenassist_si128(t2, 0x80), t2, &t1);
     schedule[12] = t1;
 }
static void expand256 (__m128i * key, __m128i * schedule) static
Expand a 256-bit encryption key to round keys
Definition at line 215 of file aesni_key.c.
References assist256_1(), and assist256_2().
Referenced by aesni_key_create().
 {
     __m128i t1, t2;
     schedule[0] = t1 = _mm_loadu_si128(key);
     schedule[1] = t2 = _mm_loadu_si128(key + 1);
     schedule[2] = t1 = assist256_1(t1, _mm_aeskeygenassist_si128(t2, 0x01));
     schedule[3] = t2 = assist256_2(t1, t2);
     schedule[4] = t1 = assist256_1(t1, _mm_aeskeygenassist_si128(t2, 0x02));
     schedule[5] = t2 = assist256_2(t1, t2);
     schedule[6] = t1 = assist256_1(t1, _mm_aeskeygenassist_si128(t2, 0x04));
     schedule[7] = t2 = assist256_2(t1, t2);
     schedule[8] = t1 = assist256_1(t1, _mm_aeskeygenassist_si128(t2, 0x08));
     schedule[9] = t2 = assist256_2(t1, t2);
     schedule[10] = t1 = assist256_1(t1, _mm_aeskeygenassist_si128(t2, 0x10));
     schedule[11] = t2 = assist256_2(t1, t2);
     schedule[12] = t1 = assist256_1(t1, _mm_aeskeygenassist_si128(t2, 0x20));
     schedule[13] = t2 = assist256_2(t1, t2);
     schedule[14] = assist256_1(t1, _mm_aeskeygenassist_si128(t2, 0x40));
 }
METHOD (aesni_key_t , destroy , void , private_aesni_key_t * this)
Definition at line 243 of file aesni_key.c.
References AES_BLOCK_SIZE, free_align(), and memwipe().
 {
     memwipe(this, sizeof(*this) + (this->public.rounds + 1) * AES_BLOCK_SIZE);
     free_align(this);
 }
static void reverse_key (aesni_key_t * this) static
Invert round encryption keys to get a decryption key schedule
Definition at line 41 of file aesni_key.c.
References memwipe(), and schedule().
Referenced by aesni_key_create().
 {
     __m128i t[this->rounds + 1];
     int i;
     for (i = 0; i <= this->rounds; i++)
     {
         t[i] = this->schedule[i];
     }
     this->schedule[this->rounds] = t[0];
     for (i = 1; i < this->rounds; i++)
     {
         this->schedule[this->rounds - i] = _mm_aesimc_si128(t[i]);
     }
     this->schedule[0] = t[this->rounds];
     memwipe(t, sizeof(t));
 }