strongSwan: credential_set_t Struct Reference
credential_set_t Struct Reference
credential_set
#include "credential_set.h"
Public Attributes
enumerator_t *(* create_private_enumerator)(credential_set_t *this, key_type_t type, identification_t *id)
enumerator_t *(* create_cert_enumerator)(credential_set_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
enumerator_t *(* create_shared_enumerator)(credential_set_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
enumerator_t *(* create_cdp_enumerator)(credential_set_t *this, certificate_type_t type, identification_t *id)
void(* cache_cert)(credential_set_t *this, certificate_t *cert)
Detailed Description
A set of credentials.
Contains private keys, shared keys and different kinds of certificates. Enumerators are used because queries might return multiple matches. Filter parameters restrict enumeration over specific items only. See credential_manager_t for an overview of the credential framework.
A credential set enumerator may not block the credential set, i.e. multiple threads must be able to hold multiple enumerators, as the credential manager is higly parallelized. The best way to achieve this is by using shared read locks for the enumerators only. Otherwise deadlocks will occur. The writing cache_cert() routine is called by the manager only if no enumerator is alive, so it is save to use a write lock there.
Definition at line 45 of file credential_set.h.
Member Data Documentation
void(* credential_set_t::cache_cert)(credential_set_t *this, certificate_t *cert)
Cache a certificate in the credential set.
The caching policy is implementation dependent. The sets may cache the certificate in-memory, persistent on disk or not at all.
Parameters
cert certificate to cache
Definition at line 105 of file credential_set.h.
Referenced by cache_queue(), and METHOD().
enumerator_t*(* credential_set_t::create_cdp_enumerator)(credential_set_t *this, certificate_type_t type, identification_t *id)
Create an enumerator over certificate distribution points.
Parameters
type type of the certificate to get a CDP
id identification of the distributed certificate
Returns
an enumerator over CDPs as char*
Definition at line 94 of file credential_set.h.
Referenced by create_cdp().
enumerator_t*(* credential_set_t::create_cert_enumerator)(credential_set_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
Create an enumerator over certificates (certificate_t).
Parameters
cert kind of certificate
key kind of key in certificate
id identity (subject) this certificate belongs to
trusted whether the certificate must be trustworthy
Returns
enumerator as described above
Definition at line 68 of file credential_set.h.
Referenced by create_cert(), and METHOD().
enumerator_t*(* credential_set_t::create_private_enumerator)(credential_set_t *this, key_type_t type, identification_t *id)
Create an enumerator over private keys (private_key_t).
The id is either a key identifier of the requested key, or an identity of the key owner.
Parameters
type type of requested private key
id key identifier/owner
Returns
enumerator over private_key_t's.
Definition at line 57 of file credential_set.h.
Referenced by create_private(), and METHOD().
enumerator_t*(* credential_set_t::create_shared_enumerator)(credential_set_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
Create an enumerator over shared keys (shared_key_t).
The enumerator enumerates over: shared_key_t*, id_match_t me, id_match_t other But must accept NULL values for the id_matches.
Parameters
type kind of requested shared key
me own identity
other other identity who owns that secret
Returns
enumerator as described above
Definition at line 83 of file credential_set.h.
Referenced by create_shared().
The documentation for this struct was generated from the following file:
credential_set.h