strongSwan: callback_cred
callback_cred
sets
Classes
struct callback_cred_t
Typedefs
typedef struct callback_cred_t callback_cred_t
typedef shared_key_t *(* callback_cred_shared_cb_t)(void *data, shared_key_type_t type, identification_t *me, identification_t *other, id_match_t *match_me, id_match_t *match_other)
Functions
callback_cred_t * callback_cred_create_shared (callback_cred_shared_cb_t cb, void *data)
Detailed Description
Typedef Documentation
typedef shared_key_t*(* callback_cred_shared_cb_t)(void *data, shared_key_type_t type, identification_t *me, identification_t *other, id_match_t *match_me, id_match_t *match_other)
Callback function to get shared keys.
Parameters
type type of requested shared key
me own identity
other other identity
match_me match result of own identity
match_other match result of other identity
Definition at line 37 of file callback_cred.h.
typedef struct callback_cred_t callback_cred_t
Definition at line 24 of file callback_cred.h.
Function Documentation
callback_cred_t* callback_cred_create_shared (callback_cred_shared_cb_t cb, void * data)
Create a callback_cred instance, for a shared key.
Parameters
cb callback function
data data to pass to callback
See header
Definition at line 136 of file callback_cred.c.
References create_generic().
Referenced by add_callback(), cmd_creds_create(), decrypt(), load_from_file(), load_pin(), and xauth_eap_create_server().
 {
     private_callback_cred_t *this = create_generic(cb, data);
     this->public.set.create_shared_enumerator = _create_shared_enumerator;
     return &this->public;
 }