strongSwan: tnccs_11
tnccs_11
tnccs_11
Functions
tnccs_t * tnccs_11_create (bool is_server, identification_t *server_id, identification_t *peer_id, host_t *server_ip, host_t *peer_ip, tnc_ift_type_t transport, tnccs_cb_t cb)
Detailed Description
Function Documentation
tnccs_t* tnccs_11_create (bool is_server, identification_t * server_id, identification_t * peer_id, host_t * server_ip, host_t * peer_ip, tnc_ift_type_t transport, tnccs_cb_t cb)
Create an instance of the TNC IF-TNCCS 1.1 protocol handler.
Parameters
is_server TRUE to act as TNC Server, FALSE for TNC Client
server_id Server identity
peer_id Client identity
server_ip Server IP address
peer_ip Client IP address
transport Underlying IF-T transport protocol
cb Callback function if TNC Server, NULL if TNC Client
Returns
TNC_IF_TNCCS 1.1 protocol stack
See header
Definition at line 655 of file tnccs_11.c.
References cb(), host_t::clone, identification_t::clone, settings_t::get_int, INIT, lib, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, and library_t::settings.
Referenced by METHOD().
 {
     private_tnccs_11_t *this;
     INIT(this,
         .public = {
             .tls = {
                 .process = _process,
                 .build = _build,
                 .is_server = _is_server,
                 .get_server_id = _get_server_id,
                 .set_peer_id = _set_peer_id,
                 .get_peer_id = _get_peer_id,
                 .get_purpose = _get_purpose,
                 .is_complete = _is_complete,
                 .get_eap_msk = _get_eap_msk,
                 .destroy = _destroy,
             },
             .get_server_ip = _get_server_ip,
             .get_peer_ip = _get_peer_ip,
             .get_transport = _get_transport,
             .set_transport = _set_transport,
             .get_auth_type = _get_auth_type,
             .set_auth_type = _set_auth_type,
             .get_pdp_server = _get_pdp_server,
             .get_ref = _get_ref,
         },
         .is_server = is_server,
         .server_id = server_id->clone(server_id),
         .peer_id = peer_id->clone(peer_id),
         .server_ip = server_ip->clone(server_ip),
         .peer_ip = peer_ip->clone(peer_ip),
         .transport = transport,
         .callback = cb,
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .max_msg_len = lib->settings->get_int(lib->settings,
                         "%s.plugins.tnccs-11.max_message_size", 45000, lib->ns),
         .ref = 1,
     );
     return &this->public;
 }