strongSwan: tls_fragmentation.c File Reference
tls_fragmentation.c File Reference
#include "tls_fragmentation.h"
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tls_fragmentation_t
Macros
#define TLS_MAX_HANDSHAKE_LEN 65536
Typedefs
typedef struct
private_tls_fragmentation_t private_tls_fragmentation_t
Enumerations
enum alert_state_t { ALERT_NONE, ALERT_SENDING, ALERT_SENT }
Functions
static bool send_close_notify (private_tls_fragmentation_t *this)
static status_t process_alert (private_tls_fragmentation_t *this, bio_reader_t *reader)
static status_t process_handshake (private_tls_fragmentation_t *this, bio_reader_t *reader)
static status_t process_application (private_tls_fragmentation_t *this, bio_reader_t *reader)
METHOD (tls_fragmentation_t, process, status_t, private_tls_fragmentation_t *this, tls_content_type_t type, chunk_t data)
static bool check_alerts (private_tls_fragmentation_t *this, chunk_t *data)
static status_t build_handshake (private_tls_fragmentation_t *this)
static status_t build_application (private_tls_fragmentation_t *this)
METHOD (tls_fragmentation_t, build, status_t, private_tls_fragmentation_t *this, tls_content_type_t *type, chunk_t *data)
METHOD (tls_fragmentation_t, application_finished, bool, private_tls_fragmentation_t *this)
METHOD (tls_fragmentation_t, destroy, void, private_tls_fragmentation_t *this)
tls_fragmentation_t * tls_fragmentation_create (tls_handshake_t *handshake, tls_alert_t *alert, tls_application_t *application, tls_purpose_t purpose)
Macro Definition Documentation
#define TLS_MAX_HANDSHAKE_LEN 65536
Maximum size of a TLS handshake message we accept
Definition at line 24 of file tls_fragmentation.c.
Referenced by process_handshake().
Typedef Documentation
typedef struct private_tls_fragmentation_t private_tls_fragmentation_t
Definition at line 26 of file tls_fragmentation.c.
Enumeration Type Documentation
enum alert_state_t
Alert state
Enumerator
ALERT_NONE
ALERT_SENDING
ALERT_SENT
Definition at line 31 of file tls_fragmentation.c.
              {
     /* no alert received/sent */
     ALERT_NONE,
     /* currently sending an alert */
     ALERT_SENDING,
     /* alert sent and out */
     ALERT_SENT,
 } alert_state_t;
Function Documentation
static status_t build_application (private_tls_fragmentation_t * this) static
Build TLS application data
Definition at line 379 of file tls_fragmentation.c.
References bio_writer_create(), chunk_clone, bio_writer_t::destroy, FAILED, bio_writer_t::get_buf, INVALID_STATE, msg, NEED_MORE, send_close_notify(), status, SUCCESS, TLS_APPLICATION_DATA, TLS_CLOSE_NOTIFY, TLS_FATAL, and TRUE.
Referenced by METHOD().
 {
     bio_writer_t *msg;
     status_t status;
     msg = bio_writer_create(64);
     while (TRUE)
     {
         status = this->application->build(this->application, msg);
         switch (status)
         {
             case NEED_MORE:
                 continue;
             case INVALID_STATE:
                 this->output_type = TLS_APPLICATION_DATA;
                 this->output = chunk_clone(msg->get_buf(msg));
                 break;
             case SUCCESS:
                 this->application_finished = TRUE;
                 if (!send_close_notify(this))
                 {
                     break;
                 }
                 /* FALL */
             case FAILED:
             default:
                 this->alert->add(this->alert, TLS_FATAL, TLS_CLOSE_NOTIFY);
                 break;
         }
         break;
     }
     msg->destroy(msg);
     return status;
 }
static status_t build_handshake (private_tls_fragmentation_t * this) static
Build hanshake message
Definition at line 334 of file tls_fragmentation.c.
References bio_writer_create(), chunk_clone, DBG2, DBG_TLS, bio_writer_t::destroy, FALSE, bio_writer_t::get_buf, INVALID_STATE, chunk_t::len, msg, NEED_MORE, status, TLS_HANDSHAKE, tls_handshake_type_names, TRUE, type, bio_writer_t::write_data24, and bio_writer_t::write_uint8.
Referenced by METHOD().
 {
     bio_writer_t *hs, *msg;
     tls_handshake_type_t type;
     status_t status;
     msg = bio_writer_create(64);
     while (TRUE)
     {
         hs = bio_writer_create(64);
         status = this->handshake->build(this->handshake, &type, hs);
         switch (status)
         {
             case NEED_MORE:
                 if (this->alert->fatal(this->alert))
                 {
                     break;
                 }
                 msg->write_uint8(msg, type);
                 msg->write_data24(msg, hs->get_buf(hs));
                 DBG2(DBG_TLS, "sending TLS %N handshake (%u bytes)",
                      tls_handshake_type_names, type, hs->get_buf(hs).len);
                 if (!this->handshake->cipherspec_changed(this->handshake, FALSE))
                 {
                     hs->destroy(hs);
                     continue;
                 }
                 /* FALL */
             case INVALID_STATE:
                 this->output_type = TLS_HANDSHAKE;
                 this->output = chunk_clone(msg->get_buf(msg));
                 break;
             default:
                 break;
         }
         hs->destroy(hs);
         break;
     }
     msg->destroy(msg);
     return status;
 }
static bool check_alerts (private_tls_fragmentation_t * this, chunk_t * data) static
Check if alerts are pending
Definition at line 311 of file tls_fragmentation.c.
References bio_writer_create(), chunk_clone, desc, bio_writer_t::destroy, FALSE, bio_writer_t::get_buf, TRUE, and bio_writer_t::write_uint8.
Referenced by METHOD().
 {
     tls_alert_level_t level;
     tls_alert_desc_t desc;
     bio_writer_t *writer;
     if (this->alert->get(this->alert, &level, &desc))
     {
         writer = bio_writer_create(2);
         writer->write_uint8(writer, level);
         writer->write_uint8(writer, desc);
         *data = chunk_clone(writer->get_buf(writer));
         writer->destroy(writer);
         return TRUE;
     }
     return FALSE;
 }
METHOD (tls_fragmentation_t , process , status_t , private_tls_fragmentation_t * this, tls_content_type_t type, chunk_t data)
Definition at line 263 of file tls_fragmentation.c.
References ALERT_NONE, ALERT_SENDING, ALERT_SENT, bio_reader_create(), DBG1, DBG_TLS, bio_reader_t::destroy, FAILED, NEED_MORE, process_alert(), process_application(), process_handshake(), status, TLS_ALERT, TLS_APPLICATION_DATA, TLS_CHANGE_CIPHER_SPEC, TLS_HANDSHAKE, and TRUE.
 {
     bio_reader_t *reader;
     status_t status;
     switch (this->state)
     {
         case ALERT_SENDING:
         case ALERT_SENT:
             /* don't accept more input, fatal error occurred */
             return NEED_MORE;
         case ALERT_NONE:
             break;
     }
     reader = bio_reader_create(data);
     switch (type)
     {
         case TLS_CHANGE_CIPHER_SPEC:
             if (this->handshake->cipherspec_changed(this->handshake, TRUE))
             {
                 this->handshake->change_cipherspec(this->handshake, TRUE);
                 status = NEED_MORE;
                 break;
             }
             status = FAILED;
             break;
         case TLS_ALERT:
             status = process_alert(this, reader);
             break;
         case TLS_HANDSHAKE:
             status = process_handshake(this, reader);
             break;
         case TLS_APPLICATION_DATA:
             status = process_application(this, reader);
             break;
         default:
             DBG1(DBG_TLS, "received unknown TLS content type %d, ignored", type);
             status = NEED_MORE;
             break;
     }
     reader->destroy(reader);
     return status;
 }
METHOD (tls_fragmentation_t , build , status_t , private_tls_fragmentation_t * this, tls_content_type_t * type, chunk_t * data)
Definition at line 414 of file tls_fragmentation.c.
References ALERT_NONE, ALERT_SENDING, ALERT_SENT, build_application(), build_handshake(), check_alerts(), chunk_clone, chunk_create(), chunk_empty, chunk_from_chars, chunk_skip(), FAILED, FALSE, INVALID_STATE, NEED_MORE, status, SUCCESS, TLS_ALERT, TLS_CHANGE_CIPHER_SPEC, and TLS_MAX_FRAGMENT_LEN.
 {
     status_t status = INVALID_STATE;
     switch (this->state)
     {
         case ALERT_SENDING:
             this->state = ALERT_SENT;
             return INVALID_STATE;
         case ALERT_SENT:
             if (this->application_finished)
             {
                 return SUCCESS;
             }
             return FAILED;
         case ALERT_NONE:
             break;
     }
     if (check_alerts(this, data))
     {
         this->state = ALERT_SENDING;
         *type = TLS_ALERT;
         return NEED_MORE;
     }
     if (!this->output.len)
     {
         if (this->handshake->cipherspec_changed(this->handshake, FALSE))
         {
             this->handshake->change_cipherspec(this->handshake, FALSE);
             *type = TLS_CHANGE_CIPHER_SPEC;
             *data = chunk_clone(chunk_from_chars(0x01));
             return NEED_MORE;
         }
         if (!this->handshake->finished(this->handshake))
         {
             status = build_handshake(this);
         }
         else if (this->application)
         {
             status = build_application(this);
         }
         if (check_alerts(this, data))
         {
             this->state = ALERT_SENDING;
             *type = TLS_ALERT;
             return NEED_MORE;
         }
     }
     if (this->output.len)
     {
         *type = this->output_type;
         if (this->output.len <= TLS_MAX_FRAGMENT_LEN)
         {
             *data = this->output;
             this->output = chunk_empty;
             return NEED_MORE;
         }
         *data = chunk_create(this->output.ptr, TLS_MAX_FRAGMENT_LEN);
         this->output = chunk_clone(chunk_skip(this->output, TLS_MAX_FRAGMENT_LEN));
         return NEED_MORE;
     }
     return status;
 }
METHOD (tls_fragmentation_t , application_finished , bool , private_tls_fragmentation_t * this)
Definition at line 479 of file tls_fragmentation.c.
 {
     return this->application_finished;
 }
METHOD (tls_fragmentation_t , destroy , void , private_tls_fragmentation_t * this)
Definition at line 485 of file tls_fragmentation.c.
References free().
 {
     free(this->input.ptr);
     free(this->output.ptr);
     free(this);
 }
static status_t process_alert (private_tls_fragmentation_t * this, bio_reader_t * reader) static
Process a TLS alert
Definition at line 127 of file tls_fragmentation.c.
References NEED_MORE, bio_reader_t::read_uint8, TLS_DECODE_ERROR, and TLS_FATAL.
Referenced by METHOD().
 {
     u_int8_t level, description;
     if (!reader->read_uint8(reader, &level) ||
         !reader->read_uint8(reader, &description))
     {
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     return this->alert->process(this->alert, level, description);
 }
static status_t process_application (private_tls_fragmentation_t * this, bio_reader_t * reader) static
Process TLS application data
Definition at line 220 of file tls_fragmentation.c.
References data, DBG1, DBG3, DBG_TLS, FAILED, NEED_MORE, bio_reader_t::peek, bio_reader_t::remaining, send_close_notify(), status, SUCCESS, TLS_CLOSE_NOTIFY, TLS_DECODE_ERROR, TLS_FATAL, TLS_MAX_FRAGMENT_LEN, and TRUE.
Referenced by METHOD().
 {
     if (!this->handshake->finished(this->handshake))
     {
         DBG1(DBG_TLS, "received TLS application data, "
              "but handshake not finished");
         return FAILED;
     }
     while (reader->remaining(reader))
     {
         status_t status;
         chunk_t data;
         if (reader->remaining(reader) > TLS_MAX_FRAGMENT_LEN)
         {
             DBG1(DBG_TLS, "TLS fragment has invalid length");
             this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
             return NEED_MORE;
         }
         data = reader->peek(reader);
         DBG3(DBG_TLS, "%B", &data);
         status = this->application->process(this->application, reader);
         switch (status)
         {
             case NEED_MORE:
                 continue;
             case SUCCESS:
                 this->application_finished = TRUE;
                 if (!send_close_notify(this))
                 {
                     return SUCCESS;
                 }
                 /* FALL */
             case FAILED:
             default:
                 this->alert->add(this->alert, TLS_FATAL, TLS_CLOSE_NOTIFY);
                 return NEED_MORE;
         }
     }
     return NEED_MORE;
 }
static status_t process_handshake (private_tls_fragmentation_t * this, bio_reader_t * reader) static
Process TLS handshake protocol data
Definition at line 144 of file tls_fragmentation.c.
References bio_reader_create(), chunk_alloc, chunk_free(), data, DBG1, DBG2, DBG_TLS, bio_reader_t::destroy, len, memcpy, min, msg, NEED_MORE, chunk_t::ptr, bio_reader_t::read_data, bio_reader_t::read_uint24, bio_reader_t::read_uint8, bio_reader_t::remaining, status, TLS_DECODE_ERROR, TLS_FATAL, tls_handshake_type_names, TLS_MAX_FRAGMENT_LEN, TLS_MAX_HANDSHAKE_LEN, and type.
Referenced by METHOD().
 {
     while (reader->remaining(reader))
     {
         bio_reader_t *msg;
         u_int8_t type;
         u_int32_t len;
         status_t status;
         chunk_t data;
         if (reader->remaining(reader) > TLS_MAX_FRAGMENT_LEN)
         {
             DBG1(DBG_TLS, "TLS fragment has invalid length");
             this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
             return NEED_MORE;
         }
         if (this->input.len == 0)
         {   /* new handshake message */
             if (!reader->read_uint8(reader, &type) ||
                 !reader->read_uint24(reader, &len))
             {
                 DBG1(DBG_TLS, "TLS handshake header invalid");
                 this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
                 return NEED_MORE;
             }
             this->type = type;
             if (len > TLS_MAX_HANDSHAKE_LEN)
             {
                 DBG1(DBG_TLS, "TLS handshake exceeds maximum length");
                 this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
                 return NEED_MORE;
             }
             chunk_free(&this->input);
             this->inpos = 0;
             if (len)
             {
                 this->input = chunk_alloc(len);
             }
         }
         len = min(this->input.len - this->inpos, reader->remaining(reader));
         if (!reader->read_data(reader, len, &data))
         {
             DBG1(DBG_TLS, "TLS fragment has invalid length");
             this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
             return NEED_MORE;
         }
         memcpy(this->input.ptr + this->inpos, data.ptr, len);
         this->inpos += len;
         if (this->input.len == this->inpos)
         {   /* message completely defragmented, process */
             msg = bio_reader_create(this->input);
             DBG2(DBG_TLS, "received TLS %N handshake (%u bytes)",
                  tls_handshake_type_names, this->type, this->input.len);
             status = this->handshake->process(this->handshake, this->type, msg);
             msg->destroy(msg);
             chunk_free(&this->input);
             if (status != NEED_MORE)
             {
                 return status;
             }
         }
         if (this->alert->fatal(this->alert))
         {
             break;
         }
     }
     return NEED_MORE;
 }
static bool send_close_notify (private_tls_fragmentation_t * this) static
Check if we should send a close notify once the application finishes
Definition at line 109 of file tls_fragmentation.c.
References FALSE, TLS_PURPOSE_EAP_PEAP, TLS_PURPOSE_EAP_TLS, TLS_PURPOSE_EAP_TTLS, and TRUE.
Referenced by build_application(), and process_application().
 {
     switch (this->purpose)
     {
         case TLS_PURPOSE_EAP_TLS:
         case TLS_PURPOSE_EAP_TTLS:
         case TLS_PURPOSE_EAP_PEAP:
             /* not for TLS-in-EAP, as we indicate completion with EAP-SUCCCESS.
              * Windows does not like close notifies, and hangs/disconnects. */
             return FALSE;
         default:
             return TRUE;
     }
 }