strongSwan: stream_service
stream_service
streams
Classes
struct stream_service_t
Typedefs
typedef struct stream_service_t stream_service_t
typedef stream_service_t *(* stream_service_constructor_t)(char *uri, int backlog)
typedef bool(* stream_service_cb_t)(void *data, stream_t *stream)
Functions
stream_service_t * stream_service_create_from_fd (int fd)
Detailed Description
Typedef Documentation
typedef bool(* stream_service_cb_t)(void *data, stream_t *stream)
Service callback routine for accepting client connections.
The passed stream gets closed/destroyed by the callback caller, unless TRUE is returned.
Parameters
data user data, as passed during registration
stream accept()ed client connection
Returns
TRUE to keep stream alive, FALSE to destroy it
Definition at line 48 of file stream_service.h.
typedef stream_service_t*(* stream_service_constructor_t)(char *uri, int backlog)
Constructor function prototype for stream_service_t.
Parameters
uri URI to create a stream for
backlog size of the backlog queue, as passed to listen()
Returns
stream instance, NULL on error
Definition at line 36 of file stream_service.h.
typedef struct stream_service_t stream_service_t
Definition at line 24 of file stream_service.h.
Function Documentation
stream_service_t* stream_service_create_from_fd (int fd)
Create a service from a file descriptor.
The file descriptor MUST be a socket.
Parameters
fd file descriptor to wrap into a stream_service_t
Returns
stream_service instance
See header
Definition at line 290 of file stream_service.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, INIT, JOB_PRIO_MEDIUM, mutex_create(), and MUTEX_TYPE_RECURSIVE.
Referenced by stream_service_create_tcp(), and stream_service_create_unix().
 {
     private_stream_service_t *this;
     INIT(this,
         .public = {
             .on_accept = _on_accept,
             .destroy = _destroy,
         },
         .fd = fd,
         .prio = JOB_PRIO_MEDIUM,
         .mutex = mutex_create(MUTEX_TYPE_RECURSIVE),
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .ref = 1,
     );
     return &this->public;
 }