strongSwan: vici_cred.c File Reference
vici_cred.c File Reference
#include "vici_cred.h"
#include "vici_builder.h"
#include <credentials/sets/mem_cred.h>
#include <credentials/certificates/ac.h>
#include <credentials/certificates/crl.h>
#include <credentials/certificates/x509.h>
Classes
struct private_vici_cred_t
Typedefs
typedef struct private_vici_cred_t private_vici_cred_t
Functions
static vici_message_t * create_reply (char *fmt,...)
CALLBACK (load_cert, vici_message_t *, private_vici_cred_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (load_key, vici_message_t *, private_vici_cred_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (shared_owners, bool, linked_list_t *owners, vici_message_t *message, char *name, chunk_t value)
CALLBACK (load_shared, vici_message_t *, private_vici_cred_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (clear_creds, vici_message_t *, private_vici_cred_t *this, char *name, u_int id, vici_message_t *message)
static void manage_command (private_vici_cred_t *this, char *name, vici_command_cb_t cb, bool reg)
static void manage_commands (private_vici_cred_t *this, bool reg)
METHOD (vici_cred_t, add_cert, certificate_t *, private_vici_cred_t *this, certificate_t *cert)
METHOD (vici_cred_t, destroy, void, private_vici_cred_t *this)
vici_cred_t * vici_cred_create (vici_dispatcher_t *dispatcher)
Typedef Documentation
typedef struct private_vici_cred_t private_vici_cred_t
Definition at line 24 of file vici_cred.c.
Function Documentation
CALLBACK (load_cert , vici_message_t * , private_vici_cred_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 66 of file vici_cred.c.
References mem_cred_t::add_cert, mem_cred_t::add_crl, BUILD_BLOB_PEM, BUILD_END, BUILD_X509_FLAG, cert, CERT_X509, CERT_X509_AC, CERT_X509_CRL, certificate_type_names, chunk_empty, credential_factory_t::create, create_reply(), CRED_CERTIFICATE, creds, library_t::creds, data, DBG1, DBG_CFG, certificate_t::destroy, FALSE, x509_t::get_flags, vici_message_t::get_str, certificate_t::get_subject, certificate_t::get_type, vici_message_t::get_value, chunk_t::len, lib, str, strcaseeq(), TRUE, type, X509_AA, and X509_CA.
 {
     certificate_type_t type;
     x509_flag_t required_flags = 0, additional_flags = 0;
     certificate_t *cert;
     x509_t *x509;
     chunk_t data;
     bool trusted = TRUE;
     char *str;
     str = message->get_str(message, NULL, "type");
     if (!str)
     {
         return create_reply("certificate type missing");
     }
     if (strcaseeq(str, "x509"))
     {
         type = CERT_X509;
     }
     else if (strcaseeq(str, "x509ca"))
     {
         type = CERT_X509;
         required_flags = X509_CA;
     }
     else if (strcaseeq(str, "x509aa"))
     {
         type = CERT_X509;
         additional_flags = X509_AA;
     }
     else if (strcaseeq(str, "x509crl"))
     {
         type = CERT_X509_CRL;
     }
     else if (strcaseeq(str, "x509ac"))
     {
         type = CERT_X509_AC;
         trusted = FALSE;
     }
     else
     {
         return create_reply("invalid certificate type: %s", str);
     }
     data = message->get_value(message, chunk_empty, "data");
     if (!data.len)
     {
         return create_reply("certificate data missing");
     }
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, type,
                               BUILD_BLOB_PEM, data,
                               BUILD_X509_FLAG, additional_flags,
                               BUILD_END);
     if (!cert)
     {
         return create_reply("parsing %N certificate failed",
                             certificate_type_names, type);
     }
     if (cert->get_type(cert) == CERT_X509)
     {
         x509 = (x509_t*)cert;
         if ((required_flags & x509->get_flags(x509)) != required_flags)
         {
             cert->destroy(cert);
             return create_reply("certificate misses required flag, rejected");
         }
     }
     DBG1(DBG_CFG, "loaded certificate '%Y'", cert->get_subject(cert));
     if (type == CERT_X509_CRL)
     {
         this->creds->add_crl(this->creds, (crl_t*)cert);
     }
     else
     {
         this->creds->add_cert(this->creds, trusted, cert);
     }
     return create_reply(NULL);
 }
CALLBACK (load_key , vici_message_t * , private_vici_cred_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 147 of file vici_cred.c.
References mem_cred_t::add_key, BUILD_BLOB_PEM, BUILD_END, chunk_empty, credential_factory_t::create, create_reply(), CRED_PRIVATE_KEY, creds, library_t::creds, data, DBG1, DBG_CFG, vici_message_t::get_str, vici_message_t::get_value, key, KEY_ANY, KEY_ECDSA, KEY_RSA, key_type_names, chunk_t::len, lib, str, strcaseeq(), and type.
 {
     key_type_t type;
     private_key_t *key;
     chunk_t data;
     char *str;
     str = message->get_str(message, NULL, "type");
     if (!str)
     {
         return create_reply("key type missing");
     }
     if (strcaseeq(str, "any"))
     {
         type = KEY_ANY;
     }
     else if (strcaseeq(str, "rsa"))
     {
         type = KEY_RSA;
     }
     else if (strcaseeq(str, "ecdsa"))
     {
         type = KEY_ECDSA;
     }
     else
     {
         return create_reply("invalid key type: %s", str);
     }
     data = message->get_value(message, chunk_empty, "data");
     if (!data.len)
     {
         return create_reply("key data missing");
     }
     key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, type,
                              BUILD_BLOB_PEM, data, BUILD_END);
     if (!key)
     {
         return create_reply("parsing %N private key failed",
                             key_type_names, type);
     }
     DBG1(DBG_CFG, "loaded %N private key", key_type_names, type);
     this->creds->add_key(this->creds, key);
     return create_reply(NULL);
 }
CALLBACK (shared_owners , bool , linked_list_t * owners, vici_message_t * message, char * name, chunk_t value)
Definition at line 196 of file vici_cred.c.
References FALSE, identification_create_from_string(), linked_list_t::insert_last, streq(), TRUE, and vici_stringify().
 {
     if (streq(name, "owners"))
     {
         char buf[256];
         if (!vici_stringify(value, buf, sizeof(buf)))
         {
             return FALSE;
         }
         owners->insert_last(owners, identification_create_from_string(buf));
     }
     return TRUE;
 }
CALLBACK (load_shared , vici_message_t * , private_vici_cred_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 212 of file vici_cred.c.
References mem_cred_t::add_shared_list, chunk_clone, chunk_empty, linked_list_t::create_enumerator, create_reply(), creds, data, DBG1, DBG_CFG, enumerator_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, linked_list_t::get_count, vici_message_t::get_str, vici_message_t::get_value, identification_create_from_string(), linked_list_t::insert_last, chunk_t::len, len, linked_list_create(), vici_message_t::parse, SHARED_EAP, SHARED_IKE, shared_key_create(), shared_key_type_names, snprintf, str, strcaseeq(), streq(), and type.
 {
     shared_key_type_t type;
     linked_list_t *owners;
     chunk_t data;
     char *str, buf[512] = "";
     enumerator_t *enumerator;
     identification_t *owner;
     int len;
     str = message->get_str(message, NULL, "type");
     if (!str)
     {
         return create_reply("shared key type missing");
     }
     if (strcaseeq(str, "ike"))
     {
         type = SHARED_IKE;
     }
     else if (strcaseeq(str, "eap") || streq(str, "xauth"))
     {
         type = SHARED_EAP;
     }
     else
     {
         return create_reply("invalid shared key type: %s", str);
     }
     data = message->get_value(message, chunk_empty, "data");
     if (!data.len)
     {
         return create_reply("shared key data missing");
     }
     owners = linked_list_create();
     if (!message->parse(message, NULL, NULL, NULL, shared_owners, owners))
     {
         owners->destroy_offset(owners, offsetof(identification_t, destroy));
         return create_reply("parsing shared key owners failed");
     }
     if (owners->get_count(owners) == 0)
     {
         owners->insert_last(owners, identification_create_from_string("%any"));
     }
     enumerator = owners->create_enumerator(owners);
     while (enumerator->enumerate(enumerator, &owner))
     {
         len = strlen(buf);
         if (len < sizeof(buf))
         {
             snprintf(buf + len, sizeof(buf) - len, "%s'%Y'",
                      len ? ", " : "", owner);
         }
     }
     enumerator->destroy(enumerator);
     DBG1(DBG_CFG, "loaded %N shared key for: %s",
          shared_key_type_names, type, buf);
     this->creds->add_shared_list(this->creds,
                         shared_key_create(type, chunk_clone(data)), owners);
     return create_reply(NULL);
 }
CALLBACK (clear_creds , vici_message_t * , private_vici_cred_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 278 of file vici_cred.c.
References CERT_ANY, mem_cred_t::clear, create_reply(), library_t::credmgr, creds, credential_manager_t::flush_cache, and lib.
 {
     this->creds->clear(this->creds);
     lib->credmgr->flush_cache(lib->credmgr, CERT_ANY);
     return create_reply(NULL);
 }
static vici_message_t* create_reply (char * fmt, ...) static
Create a (error) reply message
Definition at line 50 of file vici_cred.c.
References vici_builder_t::add_kv, vici_builder_t::finalize, vici_builder_t::vadd_kv, and vici_builder_create().
Referenced by CALLBACK().
 {
     vici_builder_t *builder;
     va_list args;
     builder = vici_builder_create();
     builder->add_kv(builder, "success", fmt ? "no" : "yes");
     if (fmt)
     {
         va_start(args, fmt);
         builder->vadd_kv(builder, "errmsg", fmt, args);
         va_end(args);
     }
     return builder->finalize(builder);
 }
static void manage_command (private_vici_cred_t * this, char * name, vici_command_cb_t cb, bool reg) static
Definition at line 287 of file vici_cred.c.
Referenced by manage_commands().
 {
     this->dispatcher->manage_command(this->dispatcher, name,
                                      reg ? cb : NULL, this);
 }
static void manage_commands (private_vici_cred_t * this, bool reg) static
(Un-)register dispatcher functions
Definition at line 297 of file vici_cred.c.
References clear_creds(), load_cert(), load_key(), load_shared(), and manage_command().
Referenced by METHOD(), and vici_cred_create().
 {
     manage_command(this, "clear-creds", clear_creds, reg);
     manage_command(this, "load-cert", load_cert, reg);
     manage_command(this, "load-key", load_key, reg);
     manage_command(this, "load-shared", load_shared, reg);
 }
METHOD (vici_cred_t , add_cert , certificate_t * , private_vici_cred_t * this, certificate_t * cert)
Definition at line 305 of file vici_cred.c.
References creds, and mem_cred_t::get_cert_ref.
 {
     return this->creds->get_cert_ref(this->creds, cert);
 }
METHOD (vici_cred_t , destroy , void , private_vici_cred_t * this)
Definition at line 311 of file vici_cred.c.
References library_t::credmgr, creds, mem_cred_t::destroy, FALSE, free(), lib, manage_commands(), and credential_manager_t::remove_set.
 {
     manage_commands(this, FALSE);
     lib->credmgr->remove_set(lib->credmgr, &this->creds->set);
     this->creds->destroy(this->creds);
     free(this);
 }