strongSwan: stream_unix
stream_unix
streams
Functions
stream_t * stream_create_unix (char *uri)
int stream_parse_uri_unix (char *uri, struct sockaddr_un *addr)
Detailed Description
Function Documentation
stream_t* stream_create_unix (char * uri)
Create a stream for UNIX sockets.
UNIX URIs start with unix://, followed by the socket path. For absolute paths, an URI looks something like:
unix:///path/to/socket
Parameters
uri UNIX socket specific URI, must start with "unix://"
Returns
stream instance, NULL on failure
See header
Definition at line 45 of file stream_unix.c.
References close, connect, DBG1, DBG_NET, len, socket, stream_create_from_fd(), stream_parse_uri_unix(), and strerror.
Referenced by METHOD(), and stream_manager_create().
 {
     struct sockaddr_un addr;
     int len, fd;
     len = stream_parse_uri_unix(uri, &addr);
     if (len == -1)
     {
         DBG1(DBG_NET, "invalid stream URI: '%s'", uri);
         return NULL;
     }
     fd = socket(AF_UNIX, SOCK_STREAM, 0);
     if (fd < 0)
     {
         DBG1(DBG_NET, "opening socket '%s' failed: %s", uri, strerror(errno));
         return NULL;
     }
     if (connect(fd, (struct sockaddr*)&addr, len) < 0)
     {
         DBG1(DBG_NET, "connecting to '%s' failed: %s", uri, strerror(errno));
         close(fd);
         return NULL;
     }
     return stream_create_from_fd(fd);
 }
int stream_parse_uri_unix (char * uri, struct sockaddr_un * addr)
Helper function to parse a unix:// URI to a sockaddr
Parameters
uri URI
addr sockaddr
Returns
length of sockaddr, -1 on error
See header
Definition at line 26 of file stream_unix.c.
References memset, and strpfx().
Referenced by stream_create_unix(), and stream_service_create_unix().
 {
     if (!strpfx(uri, "unix://"))
     {
         return -1;
     }
     uri += strlen("unix://");
     memset(addr, 0, sizeof(*addr));
     addr->sun_family = AF_UNIX;
     strncpy(addr->sun_path, uri, sizeof(addr->sun_path));
     addr->sun_path[sizeof(addr->sun_path)-1] = '\0';
     return offsetof(struct sockaddr_un, sun_path) + strlen(addr->sun_path);
 }