strongSwan: pkcs11_manager
pkcs11_manager
pkcs11
Classes
struct pkcs11_manager_t
Typedefs
typedef struct pkcs11_manager_t pkcs11_manager_t
typedef void(* pkcs11_manager_token_event_t)(void *data, pkcs11_library_t *p11, CK_SLOT_ID slot, bool add)
Functions
pkcs11_manager_t * pkcs11_manager_create (pkcs11_manager_token_event_t cb, void *data)
Detailed Description
Typedef Documentation
typedef struct pkcs11_manager_t pkcs11_manager_t
Definition at line 24 of file pkcs11_manager.h.
typedef void(* pkcs11_manager_token_event_t)(void *data, pkcs11_library_t *p11, CK_SLOT_ID slot, bool add)
Token event callback function.
Parameters
data user supplied data, as passed to pkcs11_manager_create()
p11 loaded PKCS#11 library token belongs to
slot slot number the event occurred in
add TRUE if token was added to the slot, FALSE if removed
Definition at line 38 of file pkcs11_manager.h.
Function Documentation
pkcs11_manager_t* pkcs11_manager_create (pkcs11_manager_token_event_t cb, void * data)
Create a pkcs11_manager instance.
Parameters
cb token event callback function
data user data to pass to token event callback
Returns
instance
See header
Definition at line 322 of file pkcs11_manager.c.
References callback_job_create_with_prio(), cb(), settings_t::create_section_enumerator, data, DBG1, DBG_CFG, dispatch_slot_events(), FALSE, free(), settings_t::get_bool, settings_t::get_str, INIT, JOB_PRIO_CRITICAL, lib_entry_t::lib, lib, linked_list_create(), library_t::ns, lib_entry_t::path, pkcs11_library_create(), library_t::processor, query_slots(), processor_t::queue_job, return_false(), and library_t::settings.
Referenced by pkcs11_plugin_create().
 {
     private_pkcs11_manager_t *this;
     enumerator_t *enumerator;
     lib_entry_t *entry;
     char *module;
     INIT(this,
         .public = {
             .create_token_enumerator = _create_token_enumerator,
             .destroy = _destroy,
         },
         .libs = linked_list_create(),
         .cb = cb,
         .data = data,
     );
     enumerator = lib->settings->create_section_enumerator(lib->settings,
                                         "%s.plugins.pkcs11.modules", lib->ns);
     while (enumerator->enumerate(enumerator, &module))
     {
         INIT(entry,
             .this = this,
         );
         entry->path = lib->settings->get_str(lib->settings,
                 "%s.plugins.pkcs11.modules.%s.path", NULL, lib->ns, module);
         if (!entry->path)
         {
             DBG1(DBG_CFG, "PKCS11 module '%s' lacks library path", module);
             free(entry);
             continue;
         }
         entry->lib = pkcs11_library_create(module, entry->path,
                         lib->settings->get_bool(lib->settings,
                             "%s.plugins.pkcs11.modules.%s.os_locking",
                             FALSE, lib->ns, module));
         if (!entry->lib)
         {
             free(entry);
             continue;
         }
         this->libs->insert_last(this->libs, entry);
     }
     enumerator->destroy(enumerator);
     enumerator = this->libs->create_enumerator(this->libs);
     while (enumerator->enumerate(enumerator, &entry))
     {
         query_slots(entry);
         lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create_with_prio((void*)dispatch_slot_events,
                         entry, NULL, (void*)return_false, JOB_PRIO_CRITICAL));
     }
     enumerator->destroy(enumerator);
     return &this->public;
 }