strongSwan: fast_dispatcher_t Struct Reference
fast_dispatcher_t Struct Reference
fast_dispatcher
#include "fast_dispatcher.h"
Public Attributes
void(* add_controller)(fast_dispatcher_t *this, fast_controller_constructor_t constructor, void *param)
void(* add_filter)(fast_dispatcher_t *this, fast_filter_constructor_t constructor, void *param)
void(* run)(fast_dispatcher_t *this, int threads)
void(* waitsignal)(fast_dispatcher_t *this)
void(* destroy)(fast_dispatcher_t *this)
Detailed Description
Dispatcher, accepts connections using multiple threads.
The dispatcher creates a session for each client (using SID cookies). In each session, a session context is created using the context constructor. Each controller is instanciated in the session using the controller constructor added with add_controller.
Definition at line 78 of file fast_dispatcher.h.
Member Data Documentation
void(* fast_dispatcher_t::add_controller)(fast_dispatcher_t *this, fast_controller_constructor_t constructor, void *param)
Register a controller to the dispatcher.
The first controller added serves as default controller. Client's get redirected to it if no other controller matches.
Parameters
constructor constructor function to the conntroller
param param to pass to constructor
Definition at line 89 of file fast_dispatcher.h.
Referenced by main().
void(* fast_dispatcher_t::add_filter)(fast_dispatcher_t *this, fast_filter_constructor_t constructor, void *param)
Add a filter to the dispatcher.
Parameters
constructor constructor to create filter in session
param param to pass to constructor
Definition at line 99 of file fast_dispatcher.h.
Referenced by main().
void(* fast_dispatcher_t::destroy)(fast_dispatcher_t *this)
Destroy the fast_dispatcher_t.
Definition at line 119 of file fast_dispatcher.h.
Referenced by main().
void(* fast_dispatcher_t::run)(fast_dispatcher_t *this, int threads)
Start with dispatching.
Instanciate a constant thread pool and start dispatching requests.
Parameters
threads number of dispatching threads
Definition at line 109 of file fast_dispatcher.h.
Referenced by main().
void(* fast_dispatcher_t::waitsignal)(fast_dispatcher_t *this)
Wait for a relevant signal action.
Definition at line 114 of file fast_dispatcher.h.
Referenced by main().
The documentation for this struct was generated from the following file:
fast_dispatcher.h