strongSwan: ita_attr_angel.c File Reference
ita_attr_angel.c File Reference
#include "ita_attr.h"
#include "ita_attr_angel.h"
#include <bio/bio_reader.h>
#include <bio/bio_writer.h>
#include <collections/linked_list.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_ita_attr_angel_t
Typedefs
typedef struct
private_ita_attr_angel_t private_ita_attr_angel_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ita_attr_angel_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ita_attr_angel_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ita_attr_angel_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ita_attr_angel_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ita_attr_angel_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ita_attr_angel_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ita_attr_angel_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ita_attr_angel_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ita_attr_angel_t *this)
pa_tnc_attr_t * ita_attr_angel_create (bool start)
pa_tnc_attr_t * ita_attr_angel_create_from_data (bool start)
Typedef Documentation
typedef struct private_ita_attr_angel_t private_ita_attr_angel_t
Definition at line 25 of file ita_attr_angel.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ita_attr_angel_t * this)
Definition at line 53 of file ita_attr_angel.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ita_attr_angel_t * this)
Definition at line 59 of file ita_attr_angel.c.
References chunk_empty.
 {
     return chunk_empty;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ita_attr_angel_t * this)
Definition at line 65 of file ita_attr_angel.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ita_attr_angel_t * this, bool noskip)
Definition at line 71 of file ita_attr_angel.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ita_attr_angel_t * this)
Definition at line 77 of file ita_attr_angel.c.
 {
     /* nothing to build */
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ita_attr_angel_t * this, u_int32_t * offset)
Definition at line 83 of file ita_attr_angel.c.
References SUCCESS.
 {
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ita_attr_angel_t * this, chunk_t segment)
Definition at line 89 of file ita_attr_angel.c.
 {
     /* nothing to add */
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ita_attr_angel_t * this)
Definition at line 95 of file ita_attr_angel.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ita_attr_angel_t * this)
Definition at line 102 of file ita_attr_angel.c.
References free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         free(this);
     }
 }