strongSwan: nm_handler
nm_handler
nm
Classes
struct nm_handler_t
Typedefs
typedef struct nm_handler_t nm_handler_t
Functions
nm_handler_t * nm_handler_create ()
Detailed Description
Typedef Documentation
typedef struct nm_handler_t nm_handler_t
Definition at line 26 of file nm_handler.h.
Function Documentation
nm_handler_t* nm_handler_create ()
Create a nm_handler instance.
See header
Definition at line 167 of file nm_handler.c.
References INIT, linked_list_create(), and nop().
Referenced by nm_backend_init().
 {
     private_nm_handler_t *this;
     INIT(this,
         .public = {
             .handler = {
                 .handle = _handle,
                 .release = nop,
                 .create_attribute_enumerator = _create_attribute_enumerator,
             },
             .create_enumerator = _create_enumerator,
             .reset = _reset,
             .destroy = _destroy,
         },
         .dns = linked_list_create(),
         .nbns = linked_list_create(),
     );
     return &this->public;
 }