strongSwan: peer_cfg
peer_cfg
config
Classes
struct peer_cfg_t
Typedefs
typedef enum cert_policy_t cert_policy_t
typedef enum unique_policy_t unique_policy_t
typedef struct peer_cfg_t peer_cfg_t
Enumerations
enum cert_policy_t { CERT_ALWAYS_SEND = 0, CERT_SEND_IF_ASKED = 1, CERT_NEVER_SEND = 2 }
enum unique_policy_t { UNIQUE_NEVER, UNIQUE_NO, UNIQUE_REPLACE, UNIQUE_KEEP }
Functions
peer_cfg_t * peer_cfg_create (char *name, ike_cfg_t *ike_cfg, cert_policy_t cert_policy, unique_policy_t unique, u_int32_t keyingtries, u_int32_t rekey_time, u_int32_t reauth_time, u_int32_t jitter_time, u_int32_t over_time, bool mobike, bool aggressive, bool pull_mode, u_int32_t dpd, u_int32_t dpd_timeout, bool mediation, peer_cfg_t *mediated_by, identification_t *peer_id)
Variables
enum_name_t * cert_policy_names
enum_name_t * unique_policy_names
Detailed Description
Typedef Documentation
typedef enum cert_policy_t cert_policy_t
Definition at line 26 of file peer_cfg.h.
typedef struct peer_cfg_t peer_cfg_t
Definition at line 28 of file peer_cfg.h.
typedef enum unique_policy_t unique_policy_t
Definition at line 27 of file peer_cfg.h.
Enumeration Type Documentation
enum cert_policy_t
Certificate sending policy. This is also used for certificate requests when using this definition for the other peer. If it is CERT_NEVER_SEND, a certreq is omitted, otherwise its included.
Warning
These definitions must be the same as in pluto/starter, as they are sent over the stroke socket.
Enumerator
CERT_ALWAYS_SEND
always send certificates, even when not requested
CERT_SEND_IF_ASKED
send certificate upon cert request
CERT_NEVER_SEND
never send a certificate, even when requested
Definition at line 48 of file peer_cfg.h.
                    {
     CERT_ALWAYS_SEND =      0,
     CERT_SEND_IF_ASKED =    1,
     CERT_NEVER_SEND =       2,
 };
enum unique_policy_t
Uniqueness of an IKE_SA, used to drop multiple connections with one peer.
Enumerator
UNIQUE_NEVER
never check for client uniqueness
UNIQUE_NO
only check for client uniqueness when receiving an INITIAL_CONTACT
UNIQUE_REPLACE
replace existing IKE_SAs when new ones get established by a client
UNIQUE_KEEP
keep existing IKE_SAs, close the new ones on connection attempt
Definition at line 65 of file peer_cfg.h.
                      {
     UNIQUE_NEVER,
     UNIQUE_NO,
     UNIQUE_REPLACE,
     UNIQUE_KEEP,
 };
Function Documentation
peer_cfg_t* peer_cfg_create (char * name, ike_cfg_t * ike_cfg, cert_policy_t cert_policy, unique_policy_t unique, u_int32_t keyingtries, u_int32_t rekey_time, u_int32_t reauth_time, u_int32_t jitter_time, u_int32_t over_time, bool mobike, bool aggressive, bool pull_mode, u_int32_t dpd, u_int32_t dpd_timeout, bool mediation, peer_cfg_t * mediated_by, identification_t * peer_id)
Create a configuration object for IKE_AUTH and later.
name-string gets cloned, ID's not. Virtual IPs are used if they are != NULL. A any host means the virtual IP should be obtained from the other peer. Lifetimes are in seconds. To prevent to peers to start rekeying at the same time, a jitter may be specified. Rekeying of an SA starts at (rekeylifetime - random(0, jitter)).
Parameters
name name of the peer_cfg
ike_cfg IKE config to use when acting as initiator
cert_policy should we send a certificate payload?
unique uniqueness of an IKE_SA
keyingtries how many keying tries should be done before giving up
rekey_time timeout before starting rekeying
reauth_time timeout before starting reauthentication
jitter_time timerange to randomly subtract from rekey/reauth time
over_time maximum overtime before closing a rekeying/reauth SA
mobike use MOBIKE (RFC4555) if peer supports it
aggressive use/accept aggressive mode with IKEv1
pull_mode TRUE to use modeconfig pull, FALSE for push
dpd DPD check interval, 0 to disable
dpd_timeout DPD timeout interval (IKEv1 only), if 0 default applies
mediation TRUE if this is a mediation connection
mediated_by peer_cfg_t of the mediation connection to mediate through
peer_id ID that identifies our peer at the mediation server
Returns
peer_cfg_t object
Definition at line 649 of file peer_cfg.c.
References add_auth_cfg(), DESTROY_IF, equals(), INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, select_child_cfg(), and strdup.
Referenced by build_peer_cfg(), CALLBACK(), connect_(), create_peer_cfg(), generate_config(), initiate_connection(), load_peer_config(), METHOD(), and setup_tunnel().
 {
     private_peer_cfg_t *this;
     if (rekey_time && jitter_time > rekey_time)
     {
         jitter_time = rekey_time;
     }
     if (reauth_time && jitter_time > reauth_time)
     {
         jitter_time = reauth_time;
     }
     INIT(this,
         .public = {
             .get_name = _get_name,
             .get_ike_version = _get_ike_version,
             .get_ike_cfg = _get_ike_cfg,
             .add_child_cfg = _add_child_cfg,
             .remove_child_cfg = (void*)_remove_child_cfg,
             .create_child_cfg_enumerator = _create_child_cfg_enumerator,
             .select_child_cfg = _select_child_cfg,
             .get_cert_policy = _get_cert_policy,
             .get_unique_policy = _get_unique_policy,
             .get_keyingtries = _get_keyingtries,
             .get_rekey_time = _get_rekey_time,
             .get_reauth_time = _get_reauth_time,
             .get_over_time = _get_over_time,
             .use_mobike = _use_mobike,
             .use_aggressive = _use_aggressive,
             .use_pull_mode = _use_pull_mode,
             .get_dpd = _get_dpd,
             .get_dpd_timeout = _get_dpd_timeout,
             .add_virtual_ip = _add_virtual_ip,
             .create_virtual_ip_enumerator = _create_virtual_ip_enumerator,
             .add_pool = _add_pool,
             .create_pool_enumerator = _create_pool_enumerator,
             .add_auth_cfg = _add_auth_cfg,
             .create_auth_cfg_enumerator = _create_auth_cfg_enumerator,
             .equals = (void*)_equals,
             .get_ref = _get_ref,
             .destroy = _destroy,
 #ifdef ME
             .is_mediation = _is_mediation,
             .get_mediated_by = _get_mediated_by,
             .get_peer_id = _get_peer_id,
 #endif /* ME */
         },
         .name = strdup(name),
         .ike_cfg = ike_cfg,
         .child_cfgs = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .cert_policy = cert_policy,
         .unique = unique,
         .keyingtries = keyingtries,
         .rekey_time = rekey_time,
         .reauth_time = reauth_time,
         .jitter_time = jitter_time,
         .over_time = over_time,
         .use_mobike = mobike,
         .aggressive = aggressive,
         .pull_mode = pull_mode,
         .dpd = dpd,
         .dpd_timeout = dpd_timeout,
         .vips = linked_list_create(),
         .pools = linked_list_create(),
         .local_auth = linked_list_create(),
         .remote_auth = linked_list_create(),
         .refcount = 1,
     );
 #ifdef ME
     this->mediation = mediation;
     this->mediated_by = mediated_by;
     this->peer_id = peer_id;
 #else /* ME */
     DESTROY_IF(mediated_by);
     DESTROY_IF(peer_id);
 #endif /* ME */
     return &this->public;
 }
Variable Documentation
enum_name_t* cert_policy_names
enum strings for cert_policy_t
Referenced by log_peer_data().
enum_name_t* unique_policy_names
enum strings for unique_policy_t
Referenced by log_peer_data().