strongSwan: tnccs_batch.c File Reference
tnccs_batch.c File Reference
#include "tnccs_batch.h"
#include "messages/tnccs_error_msg.h"
#include <tnc/tnccs/tnccs.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
#include <libxml/parser.h>
Classes
struct private_tnccs_batch_t
Macros
#define TNCCS_NS "http://www.trustedcomputinggroup.org/IWG/TNC/1_0/IF_TNCCS#"
#define SCHEMA_NS "http://www.w3.org/2001/XMLSchema-instance"
#define TNCCS_XSD "https://www.trustedcomputinggroup.org/XML/SCHEMA/TNCCS_1.0.xsd"
Typedefs
typedef struct
private_tnccs_batch_t private_tnccs_batch_t
Functions
METHOD (tnccs_batch_t, get_encoding, chunk_t, private_tnccs_batch_t *this)
METHOD (tnccs_batch_t, add_msg, void, private_tnccs_batch_t *this, tnccs_msg_t *msg)
METHOD (tnccs_batch_t, build, void, private_tnccs_batch_t *this)
METHOD (tnccs_batch_t, process, status_t, private_tnccs_batch_t *this)
METHOD (tnccs_batch_t, create_msg_enumerator, enumerator_t *, private_tnccs_batch_t *this)
METHOD (tnccs_batch_t, create_error_enumerator, enumerator_t *, private_tnccs_batch_t *this)
METHOD (tnccs_batch_t, destroy, void, private_tnccs_batch_t *this)
tnccs_batch_t * tnccs_batch_create (bool is_server, int batch_id)
tnccs_batch_t * tnccs_batch_create_from_data (bool is_server, int batch_id, chunk_t data)
Macro Definition Documentation
#define SCHEMA_NS "http://www.w3.org/2001/XMLSchema-instance"
Definition at line 27 of file tnccs_batch.c.
Referenced by tnccs_batch_create().
#define TNCCS_NS "http://www.trustedcomputinggroup.org/IWG/TNC/1_0/IF_TNCCS#"
Definition at line 26 of file tnccs_batch.c.
Referenced by METHOD(), and tnccs_batch_create().
#define TNCCS_XSD "https://www.trustedcomputinggroup.org/XML/SCHEMA/TNCCS_1.0.xsd"
Definition at line 28 of file tnccs_batch.c.
Referenced by tnccs_batch_create().
Typedef Documentation
typedef struct private_tnccs_batch_t private_tnccs_batch_t
Definition at line 30 of file tnccs_batch.c.
Function Documentation
METHOD (tnccs_batch_t , get_encoding , chunk_t , private_tnccs_batch_t * this)
Definition at line 73 of file tnccs_batch.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (tnccs_batch_t , add_msg , void , private_tnccs_batch_t * this, tnccs_msg_t * msg)
Definition at line 79 of file tnccs_batch.c.
References DBG2, DBG_TNC, tnccs_msg_t::get_node, tnccs_msg_t::get_type, format-options::root, and tnccs_msg_type_names.
 {
     xmlNodePtr root;
     DBG2(DBG_TNC, "adding %N message", tnccs_msg_type_names,
                                        msg->get_type(msg));
     this->messages->insert_last(this->messages, msg);
     root = xmlDocGetRootElement(this->doc);
     xmlAddChild(root, msg->get_node(msg));
 }
METHOD (tnccs_batch_t , build , void , private_tnccs_batch_t * this)
Definition at line 91 of file tnccs_batch.c.
References chunk_clone, chunk_create(), and encoding.
 {
     xmlChar *xmlbuf;
     int buf_size;
     xmlDocDumpFormatMemory(this->doc, &xmlbuf, &buf_size, 1);
     this->encoding = chunk_create(xmlbuf, buf_size);
     this->encoding = chunk_clone(this->encoding);
     xmlFree(xmlbuf);
 }
METHOD (tnccs_batch_t , process , status_t , private_tnccs_batch_t * this)
Definition at line 103 of file tnccs_batch.c.
References BUF_LEN, DBG1, DBG2, DBG_TNC, encoding, FAILED, msg, snprintf, streq(), SUCCESS, TNCCS_ERROR_INVALID_BATCH_ID, TNCCS_ERROR_INVALID_RECIPIENT_TYPE, TNCCS_ERROR_MALFORMED_BATCH, tnccs_error_msg_create(), TNCCS_ERROR_OTHER, tnccs_msg_create_from_node(), and TNCCS_NS.
 {
     tnccs_msg_t *tnccs_msg, *msg;
     tnccs_error_type_t error_type = TNCCS_ERROR_OTHER;
     char *error_msg, buf[BUF_LEN];
     xmlNodePtr cur;
     xmlNsPtr ns;
     xmlChar *batchid, *recipient;
     int batch_id;
     this->doc = xmlParseMemory(this->encoding.ptr, this->encoding.len);
     if (!this->doc)
     {
         error_type = TNCCS_ERROR_MALFORMED_BATCH;
         error_msg = "failed to parse XML message";
         goto fatal;
     }
     /* check out the XML document */
     cur = xmlDocGetRootElement(this->doc);
     if (!cur)
     {
         error_type = TNCCS_ERROR_MALFORMED_BATCH;
         error_msg = "empty XML document";
         goto fatal;
     }
     /* check TNCCS namespace */
     ns = xmlSearchNsByHref(this->doc, cur, TNCCS_NS);
     if (!ns)
     {
         error_type = TNCCS_ERROR_MALFORMED_BATCH;
         error_msg = "TNCCS namespace not found";
         goto fatal;
     }
     /* check XML document type */
     if (xmlStrcmp(cur->name, "TNCCS-Batch"))
     {
         error_type = TNCCS_ERROR_MALFORMED_BATCH;
         error_msg = buf;
         snprintf(buf, BUF_LEN, "wrong XML document type '%s', expected TNCCS-Batch",
                                 cur->name);
         goto fatal;
     }
     /* check presence of BatchID property */
     batchid = xmlGetProp(cur, "BatchId");
     if (!batchid)
     {
         error_type = TNCCS_ERROR_INVALID_BATCH_ID;
         error_msg = "BatchId is missing";
         goto fatal;
     }
     /* check BatchID */
     batch_id = atoi((char*)batchid);
     xmlFree(batchid);
     if (batch_id != this->batch_id)
     {
         error_type = TNCCS_ERROR_INVALID_BATCH_ID;
         error_msg = buf;
         snprintf(buf, BUF_LEN, "BatchId %d expected, got %d", this->batch_id,
                                                               batch_id);
         goto fatal;
     }
     /* check presence of Recipient property */
     recipient = xmlGetProp(cur, "Recipient");
     if (!recipient)
     {
         error_type = TNCCS_ERROR_INVALID_RECIPIENT_TYPE;
         error_msg = "Recipient is missing";
         goto fatal;
     }
     /* check recipient */
     if (!streq(recipient, this->is_server ? "TNCS" : "TNCC"))
     {
         error_type = TNCCS_ERROR_INVALID_RECIPIENT_TYPE;
         error_msg = buf;
         snprintf(buf, BUF_LEN, "message recipient expected '%s', got '%s'",
                  this->is_server ? "TNCS" : "TNCC", recipient);
         xmlFree(recipient);
         goto fatal;
     }
     xmlFree(recipient);
     DBG2(DBG_TNC, "processing TNCCS Batch #%d", batch_id);
     /* Now walk the tree, handling message nodes as we go */
     for (cur = cur->xmlChildrenNode; cur != NULL; cur = cur->next)
     {
         /* ignore empty or blank nodes */
         if (xmlIsBlankNode(cur))
         {
             continue;
         }
         /* ignore nodes with wrong namespace */
         if (cur->ns != ns)
         {
             DBG1(DBG_TNC, "ignoring message node '%s' having wrong namespace",
                           cur->name);
             continue;
         }
         tnccs_msg = tnccs_msg_create_from_node(cur, this->errors);
         /* exit if a message parsing error occurred */
         if (this->errors->get_count(this->errors) > 0)
         {
             return FAILED;
         }
         /* ignore unrecognized messages */
         if (!tnccs_msg)
         {
             continue;
         }
         this->messages->insert_last(this->messages, tnccs_msg);
     }
     return SUCCESS;
 fatal:
     msg = tnccs_error_msg_create(error_type, error_msg);
     this->errors->insert_last(this->errors, msg);
     return FAILED;
 }
METHOD (tnccs_batch_t , create_msg_enumerator , enumerator_t * , private_tnccs_batch_t * this)
Definition at line 235 of file tnccs_batch.c.
 {
     return this->messages->create_enumerator(this->messages);
 }
METHOD (tnccs_batch_t , create_error_enumerator , enumerator_t * , private_tnccs_batch_t * this)
Definition at line 241 of file tnccs_batch.c.
 {
     return this->errors->create_enumerator(this->errors);
 }
METHOD (tnccs_batch_t , destroy , void , private_tnccs_batch_t * this)
Definition at line 247 of file tnccs_batch.c.
References destroy(), encoding, and free().
 {
     this->messages->destroy_offset(this->messages,
                                    offsetof(tnccs_msg_t, destroy));
     this->errors->destroy_offset(this->errors,
                                    offsetof(tnccs_msg_t, destroy));
     xmlFreeDoc(this->doc);
     free(this->encoding.ptr);
     free(this);
 }