strongSwan: gcrypt_plugin.c File Reference
gcrypt_plugin.c File Reference
#include "gcrypt_plugin.h"
#include "gcrypt_hasher.h"
#include "gcrypt_crypter.h"
#include "gcrypt_rng.h"
#include "gcrypt_dh.h"
#include "gcrypt_rsa_private_key.h"
#include "gcrypt_rsa_public_key.h"
#include <library.h>
#include <utils/debug.h>
#include <threading/mutex.h>
#include <errno.h>
#include <gcrypt.h>
#include <pthread.h>
Classes
struct private_gcrypt_plugin_t
Typedefs
typedef struct
private_gcrypt_plugin_t private_gcrypt_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_gcrypt_plugin_t *this)
METHOD (plugin_t, get_features, int, private_gcrypt_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_gcrypt_plugin_t *this)
plugin_t * gcrypt_plugin_create ()
Variables
GCRY_THREAD_OPTION_PTHREAD_IMPL
Typedef Documentation
typedef struct private_gcrypt_plugin_t private_gcrypt_plugin_t
Definition at line 33 of file gcrypt_plugin.c.
Function Documentation
plugin_t* gcrypt_plugin_create ()
Definition at line 140 of file gcrypt_plugin.c.
References DBG1, DBG_LIB, FALSE, settings_t::get_bool, INIT, lib, library_t::ns, and library_t::settings.
 {
     private_gcrypt_plugin_t *this;
     gcry_control(GCRYCTL_SET_THREAD_CBS, &gcry_threads_pthread);
     if (!gcry_check_version(GCRYPT_VERSION))
     {
         DBG1(DBG_LIB, "libgcrypt version mismatch");
         return NULL;
     }
     /* we currently do not use secure memory */
     gcry_control(GCRYCTL_DISABLE_SECMEM, 0);
     if (lib->settings->get_bool(lib->settings, "%s.plugins.gcrypt.quick_random",
                                 FALSE, lib->ns))
     {
         gcry_control(GCRYCTL_ENABLE_QUICK_RANDOM, 0);
     }
     gcry_control(GCRYCTL_INITIALIZATION_FINISHED, 0);
     /* initialize static allocations we want to exclude from leak-detective */
     gcry_create_nonce(NULL, 0);
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_gcrypt_plugin_t * this)
Definition at line 51 of file gcrypt_plugin.c.
 {
     return "gcrypt";
 }
METHOD (plugin_t , get_features , int , private_gcrypt_plugin_t * this, plugin_feature_t * features[])
Definition at line 57 of file gcrypt_plugin.c.
References countof, ENCR_3DES, ENCR_AES_CBC, ENCR_AES_CTR, ENCR_BLOWFISH, ENCR_CAMELLIA_CBC, ENCR_CAMELLIA_CTR, ENCR_CAST, ENCR_DES, ENCR_DES_ECB, ENCR_SERPENT_CBC, ENCR_TWOFISH_CBC, FALSE, gcrypt_crypter_create(), gcrypt_dh_create(), gcrypt_dh_create_custom(), gcrypt_hasher_create(), gcrypt_rng_create(), gcrypt_rsa_private_key_gen(), gcrypt_rsa_private_key_load(), gcrypt_rsa_public_key_load(), HASH_MD4, HASH_MD5, HASH_SHA1, HASH_SHA224, HASH_SHA256, HASH_SHA384, HASH_SHA512, KEY_RSA, MODP_1024_160, MODP_1024_BIT, MODP_1536_BIT, MODP_2048_224, MODP_2048_256, MODP_2048_BIT, MODP_3072_BIT, MODP_4096_BIT, MODP_6144_BIT, MODP_768_BIT, MODP_8192_BIT, MODP_CUSTOM, PLUGIN_PROVIDE, PLUGIN_REGISTER, RNG_STRONG, RNG_TRUE, RNG_WEAK, and TRUE.
 {
     static plugin_feature_t f[] = {
         /* we provide threading-safe initialization of libgcrypt */
         PLUGIN_PROVIDE(CUSTOM, "gcrypt-threading"),
         /* crypters */
         PLUGIN_REGISTER(CRYPTER, gcrypt_crypter_create),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CTR, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CTR, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CTR, 32),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CBC, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CBC, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CBC, 32),
             /* gcrypt only supports 128 bit blowfish */
             PLUGIN_PROVIDE(CRYPTER, ENCR_BLOWFISH, 16),
 #ifdef HAVE_GCRY_CIPHER_CAMELLIA
             PLUGIN_PROVIDE(CRYPTER, ENCR_CAMELLIA_CTR, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_CAMELLIA_CTR, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_CAMELLIA_CTR, 32),
             PLUGIN_PROVIDE(CRYPTER, ENCR_CAMELLIA_CBC, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_CAMELLIA_CBC, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_CAMELLIA_CBC, 32),
 #endif
             PLUGIN_PROVIDE(CRYPTER, ENCR_CAST, 0),
             PLUGIN_PROVIDE(CRYPTER, ENCR_3DES, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_DES, 8),
             PLUGIN_PROVIDE(CRYPTER, ENCR_DES_ECB, 8),
             PLUGIN_PROVIDE(CRYPTER, ENCR_SERPENT_CBC, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_SERPENT_CBC, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_SERPENT_CBC, 32),
             PLUGIN_PROVIDE(CRYPTER, ENCR_TWOFISH_CBC, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_TWOFISH_CBC, 32),
         /* hashers */
         PLUGIN_REGISTER(HASHER, gcrypt_hasher_create),
             PLUGIN_PROVIDE(HASHER, HASH_MD4),
             PLUGIN_PROVIDE(HASHER, HASH_MD5),
             PLUGIN_PROVIDE(HASHER, HASH_SHA1),
             PLUGIN_PROVIDE(HASHER, HASH_SHA224),
             PLUGIN_PROVIDE(HASHER, HASH_SHA256),
             PLUGIN_PROVIDE(HASHER, HASH_SHA384),
             PLUGIN_PROVIDE(HASHER, HASH_SHA512),
         /* MODP DH groups */
         PLUGIN_REGISTER(DH, gcrypt_dh_create),
             PLUGIN_PROVIDE(DH, MODP_2048_BIT),
             PLUGIN_PROVIDE(DH, MODP_2048_224),
             PLUGIN_PROVIDE(DH, MODP_2048_256),
             PLUGIN_PROVIDE(DH, MODP_1536_BIT),
             PLUGIN_PROVIDE(DH, MODP_3072_BIT),
             PLUGIN_PROVIDE(DH, MODP_4096_BIT),
             PLUGIN_PROVIDE(DH, MODP_6144_BIT),
             PLUGIN_PROVIDE(DH, MODP_8192_BIT),
             PLUGIN_PROVIDE(DH, MODP_1024_BIT),
             PLUGIN_PROVIDE(DH, MODP_1024_160),
             PLUGIN_PROVIDE(DH, MODP_768_BIT),
         PLUGIN_REGISTER(DH, gcrypt_dh_create_custom),
             PLUGIN_PROVIDE(DH, MODP_CUSTOM),
         /* RSA private/public key loading */
         PLUGIN_REGISTER(PUBKEY, gcrypt_rsa_public_key_load, TRUE),
             PLUGIN_PROVIDE(PUBKEY, KEY_RSA),
         PLUGIN_REGISTER(PRIVKEY, gcrypt_rsa_private_key_load, TRUE),
             PLUGIN_PROVIDE(PRIVKEY, KEY_RSA),
         PLUGIN_REGISTER(PRIVKEY_GEN, gcrypt_rsa_private_key_gen, FALSE),
             PLUGIN_PROVIDE(PRIVKEY_GEN, KEY_RSA),
         /* random numbers */
         PLUGIN_REGISTER(RNG, gcrypt_rng_create),
             PLUGIN_PROVIDE(RNG, RNG_WEAK),
             PLUGIN_PROVIDE(RNG, RNG_STRONG),
             PLUGIN_PROVIDE(RNG, RNG_TRUE),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_gcrypt_plugin_t * this)
Definition at line 131 of file gcrypt_plugin.c.
References free().
 {
     free(this);
 }
Variable Documentation
GCRY_THREAD_OPTION_PTHREAD_IMPL
Define gcrypt multi-threading callbacks as gcry_threads_pthread
Definition at line 49 of file gcrypt_plugin.c.