strongSwan: openssl_crl
openssl_crl
openssl
Classes
struct openssl_crl_t
Typedefs
typedef struct openssl_crl_t openssl_crl_t
Functions
openssl_crl_t * openssl_crl_load (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct openssl_crl_t openssl_crl_t
Definition at line 24 of file openssl_crl.h.
Function Documentation
openssl_crl_t* openssl_crl_load (certificate_type_t type, va_list args)
Load a X.509 CRL using OpenSSL.
Parameters
type certificate type, CERT_X509_CRL only
args builder_part_t argument list
Returns
X.509 CRL, NULL on failure
Load the CRL.
Definition at line 527 of file openssl_crl.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_clone, chunk_empty, create_empty(), destroy(), encoding, parse_crl(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.ptr)
     {
         private_openssl_crl_t *this = create_empty();
         this->encoding = chunk_clone(blob);
         if (parse_crl(this))
         {
             return &this->public;
         }
         destroy(this);
     }
     return NULL;
 }