strongSwan: ts_payload.c File Reference
ts_payload.c File Reference
#include <stddef.h>
#include "ts_payload.h"
#include <encoding/payloads/encodings.h>
#include <collections/linked_list.h>
Classes
struct private_ts_payload_t
Typedefs
typedef struct private_ts_payload_t private_ts_payload_t
Functions
METHOD (payload_t, verify, status_t, private_ts_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_ts_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_ts_payload_t *this)
METHOD (payload_t, get_type, payload_type_t, private_ts_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_ts_payload_t *this)
METHOD (payload_t, set_next_type, void, private_ts_payload_t *this, payload_type_t type)
static void compute_length (private_ts_payload_t *this)
METHOD (payload_t, get_length, size_t, private_ts_payload_t *this)
METHOD (ts_payload_t, get_initiator, bool, private_ts_payload_t *this)
METHOD (ts_payload_t, set_initiator, void, private_ts_payload_t *this, bool is_initiator)
METHOD (ts_payload_t, get_traffic_selectors, linked_list_t *, private_ts_payload_t *this)
METHOD2 (payload_t, ts_payload_t, destroy, void, private_ts_payload_t *this)
ts_payload_t * ts_payload_create (bool is_initiator)
ts_payload_t * ts_payload_create_from_traffic_selectors (bool is_initiator, linked_list_t *traffic_selectors)
Variables
static encoding_rule_t encodings []
Typedef Documentation
typedef struct private_ts_payload_t private_ts_payload_t
Definition at line 25 of file ts_payload.c.
Function Documentation
static void compute_length (private_ts_payload_t * this) static
recompute the length of the payload.
Definition at line 187 of file ts_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, and payload_t::get_length.
Referenced by ts_payload_create_from_traffic_selectors().
 {
     enumerator_t *enumerator;
     payload_t *subst;
     this->payload_length = get_header_length(this);
     this->ts_num = 0;
     enumerator = this->substrs->create_enumerator(this->substrs);
     while (enumerator->enumerate(enumerator, &subst))
     {
         this->payload_length += subst->get_length(subst);
         this->ts_num++;
     }
     enumerator->destroy(enumerator);
 }
METHOD (payload_t , verify , status_t , private_ts_payload_t * this)
Definition at line 124 of file ts_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, FAILED, status, SUCCESS, and payload_t::verify.
 {
     enumerator_t *enumerator;
     payload_t *substr;
     status_t status = SUCCESS;
     if (this->ts_num != this->substrs->get_count(this->substrs))
     {
         return FAILED;
     }
     enumerator = this->substrs->create_enumerator(this->substrs);
     while (enumerator->enumerate(enumerator, &substr))
     {
         status = substr->verify(substr);
         if (status != SUCCESS)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return status;
 }
METHOD (payload_t , get_encoding_rules , int , private_ts_payload_t * this, encoding_rule_t ** rules)
Definition at line 149 of file ts_payload.c.
References countof, and encodings.
 {
     *rules = encodings;
     return countof(encodings);
 }
METHOD (payload_t , get_header_length , int , private_ts_payload_t * this)
Definition at line 156 of file ts_payload.c.
 {
     return 8;
 }
METHOD (payload_t , get_type , payload_type_t , private_ts_payload_t * this)
Definition at line 162 of file ts_payload.c.
References PLV2_TS_INITIATOR, and PLV2_TS_RESPONDER.
 {
     if (this->is_initiator)
     {
         return PLV2_TS_INITIATOR;
     }
     return PLV2_TS_RESPONDER;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_ts_payload_t * this)
Definition at line 172 of file ts_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_ts_payload_t * this, payload_type_t type)
Definition at line 178 of file ts_payload.c.
References type.
 {
     this->next_payload = type;
 }
METHOD (payload_t , get_length , size_t , private_ts_payload_t * this)
Definition at line 203 of file ts_payload.c.
 {
     return this->payload_length;
 }
METHOD (ts_payload_t , get_initiator , bool , private_ts_payload_t * this)
Definition at line 209 of file ts_payload.c.
 {
     return this->is_initiator;
 }
METHOD (ts_payload_t , set_initiator , void , private_ts_payload_t * this, bool is_initiator)
Definition at line 215 of file ts_payload.c.
 {
     this->is_initiator = is_initiator;
 }
METHOD (ts_payload_t , get_traffic_selectors , linked_list_t * , private_ts_payload_t * this)
Definition at line 221 of file ts_payload.c.
References enumerator_t::destroy, enumerator_t::enumerate, traffic_selector_substructure_t::get_traffic_selector, linked_list_t::insert_last, linked_list_create(), and list.
 {
     traffic_selector_t *ts;
     enumerator_t *enumerator;
     traffic_selector_substructure_t *subst;
     linked_list_t *list;
     list = linked_list_create();
     enumerator = this->substrs->create_enumerator(this->substrs);
     while (enumerator->enumerate(enumerator, &subst))
     {
         ts = subst->get_traffic_selector(subst);
         list->insert_last(list, ts);
     }
     enumerator->destroy(enumerator);
     return list;
 }
METHOD2 (payload_t , ts_payload_t , destroy , void , private_ts_payload_t * this)
Definition at line 241 of file ts_payload.c.
References destroy(), and free().
 {
     this->substrs->destroy_offset(this->substrs, offsetof(payload_t, destroy));
     free(this);
 }
Variable Documentation
encoding_rule_t encodings[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_ts_payload_t, next_payload)    },
    { FLAG,             offsetof(private_ts_payload_t, critical)        },
    { RESERVED_BIT,     offsetof(private_ts_payload_t, reserved_bit[0]) },
    { RESERVED_BIT,     offsetof(private_ts_payload_t, reserved_bit[1]) },
    { RESERVED_BIT,     offsetof(private_ts_payload_t, reserved_bit[2]) },
    { RESERVED_BIT,     offsetof(private_ts_payload_t, reserved_bit[3]) },
    { RESERVED_BIT,     offsetof(private_ts_payload_t, reserved_bit[4]) },
    { RESERVED_BIT,     offsetof(private_ts_payload_t, reserved_bit[5]) },
    { RESERVED_BIT,     offsetof(private_ts_payload_t, reserved_bit[6]) },
    { PAYLOAD_LENGTH,   offsetof(private_ts_payload_t, payload_length)  },
    { U_INT_8,          offsetof(private_ts_payload_t, ts_num)          },
    { RESERVED_BYTE,    offsetof(private_ts_payload_t, reserved_byte[0])},
    { RESERVED_BYTE,    offsetof(private_ts_payload_t, reserved_byte[1])},
    { RESERVED_BYTE,    offsetof(private_ts_payload_t, reserved_byte[2])},
    { PAYLOAD_LIST + PLV2_TRAFFIC_SELECTOR_SUBSTRUCTURE,
                        offsetof(private_ts_payload_t, substrs)         },
}
Encoding rules to parse or generate a TS payload
The defined offsets are the positions in a object of type private_ts_payload_t.
Definition at line 84 of file ts_payload.c.
Referenced by METHOD().