strongSwan: fast_request
fast_request
libfast
Classes
struct fast_request_t
Typedefs
typedef struct fast_request_t fast_request_t
Functions
fast_request_t * fast_request_create (int fd, bool debug)
Detailed Description
Typedef Documentation
typedef struct fast_request_t fast_request_t
Definition at line 27 of file fast_request.h.
Function Documentation
fast_request_t* fast_request_create (int fd, bool debug)
Create a request from the fastcgi struct.
Parameters
fd file descripter opened with FCGX_OpenSocket
debug no stripping, no compression, timing information
Definition at line 409 of file fast_request.c.
References FALSE, free(), INIT, init(), once, req(), thread_value_t::set, thread_cleanup_pop(), thread_cleanup_push(), and TRUE.
Referenced by dispatch().
 {
     NEOERR* err;
     private_fast_request_t *this;
     bool failed = FALSE;
     INIT(this,
         .public = {
             .get_path = _get_path,
             .get_base = _get_base,
             .get_host = _get_host,
             .get_user_agent = _get_user_agent,
             .add_cookie = _add_cookie,
             .get_cookie = _get_cookie,
             .get_query_data = _get_query_data,
             .get_env_var = _get_env_var,
             .read_data = _read_data,
             .session_closed = _session_closed,
             .close_session = _close_session,
             .redirect = _redirect,
             .get_referer = _get_referer,
             .to_referer = _to_referer,
             .render = _render,
             .streamf = _streamf,
             .serve = _serve,
             .sendfile = _sendfile,
             .set = _set,
             .setf = _setf,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .ref = 1,
     );
     thread_cleanup_push(free, this);
     if (FCGX_InitRequest(&this->req, fd, 0) != 0 ||
         FCGX_Accept_r(&this->req) != 0)
     {
         failed = TRUE;
     }
     thread_cleanup_pop(failed);
     if (failed)
     {
         return NULL;
     }
     pthread_once(&once, init);
     thread_this->set(thread_this, this);
     while (this->req.envp[this->req_env_len] != NULL)
     {
         this->req_env_len++;
     }
     err = hdf_init(&this->hdf);
     if (!err)
     {
         hdf_set_value(this->hdf, "base", get_base(this));
         hdf_set_value(this->hdf, "Config.NoCache", "true");
         if (!debug)
         {
             hdf_set_value(this->hdf, "Config.TimeFooter", "0");
             hdf_set_value(this->hdf, "Config.CompressionEnabled", "1");
             hdf_set_value(this->hdf, "Config.WhiteSpaceStrip", "2");
         }
         err = cgi_init(&this->cgi, this->hdf);
         if (!err)
         {
             err = cgi_parse(this->cgi);
             if (!err)
             {
                 return &this->public;
             }
             cgi_destroy(&this->cgi);
         }
     }
     nerr_log_error(err);
     FCGX_Finish_r(&this->req);
     free(this);
     return NULL;
 }