strongSwan: pkcs7_generic.c File Reference
pkcs7_generic.c File Reference
#include "pkcs7_generic.h"
#include "pkcs7_data.h"
#include "pkcs7_signed_data.h"
#include "pkcs7_encrypted_data.h"
#include "pkcs7_enveloped_data.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
Macros
#define PKCS7_INFO_TYPE 1
#define PKCS7_INFO_CONTENT 2
Functions
static pkcs7_t * parse_contentInfo (chunk_t blob)
pkcs7_t * pkcs7_generic_load (container_type_t type, va_list args)
Variables
static const asn1Object_t contentInfoObjects []
Macro Definition Documentation
#define PKCS7_INFO_CONTENT 2
Definition at line 43 of file pkcs7_generic.c.
Referenced by parse_contentInfo().
#define PKCS7_INFO_TYPE 1
Definition at line 42 of file pkcs7_generic.c.
Referenced by parse_contentInfo().
Function Documentation
static pkcs7_t* parse_contentInfo (chunk_t blob) static
Parse PKCS#7 contentInfo object
Definition at line 48 of file pkcs7_generic.c.
References asn1_known_oid(), asn1_parser_create(), chunk_empty, DBG1, DBG_ASN, asn1_parser_t::destroy, end, FALSE, asn1_parser_t::iterate, OID_PKCS7_DATA, OID_PKCS7_ENCRYPTED_DATA, OID_PKCS7_ENVELOPED_DATA, OID_PKCS7_SIGNED_DATA, OID_UNKNOWN, parser, pkcs7_data_load(), pkcs7_encrypted_data_load(), pkcs7_enveloped_data_load(), PKCS7_INFO_CONTENT, PKCS7_INFO_TYPE, pkcs7_signed_data_load(), asn1_parser_t::set_top_level, asn1_parser_t::success, and type.
Referenced by pkcs7_generic_load().
 {
     asn1_parser_t *parser;
     chunk_t object, content = chunk_empty;
     int objectID, type = OID_UNKNOWN;
     bool success = FALSE;
     parser = asn1_parser_create(contentInfoObjects, blob);
     parser->set_top_level(parser, 0);
     while (parser->iterate(parser, &objectID, &object))
     {
         if (objectID == PKCS7_INFO_TYPE)
         {
             type = asn1_known_oid(object);
             if (type < OID_PKCS7_DATA || type > OID_PKCS7_ENCRYPTED_DATA)
             {
                 DBG1(DBG_ASN, "unknown pkcs7 content type");
                 goto end;
             }
         }
         else if (objectID == PKCS7_INFO_CONTENT)
         {
             content = object;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     if (success)
     {
         switch (type)
         {
             case OID_PKCS7_DATA:
                 return pkcs7_data_load(blob, content);
             case OID_PKCS7_SIGNED_DATA:
                 return pkcs7_signed_data_load(blob, content);
             case OID_PKCS7_ENVELOPED_DATA:
                 return pkcs7_enveloped_data_load(blob, content);
             case OID_PKCS7_ENCRYPTED_DATA:
                 return pkcs7_encrypted_data_load(blob, content);
             default:
                 DBG1(DBG_ASN, "pkcs7 content type %d not supported", type);
                 return NULL;
         }
     }
     return NULL;
 }
Variable Documentation
const asn1Object_t contentInfoObjects[] static
Initial value:
= {
    { 0, "contentInfo",     ASN1_SEQUENCE,      ASN1_NONE },
    { 1,   "contentType",   ASN1_OID,           ASN1_BODY },
    { 1,   "content",       ASN1_CONTEXT_C_0,   ASN1_OPT |
                                                ASN1_BODY },
    { 1,   "end opt",       ASN1_EOC,           ASN1_END  },
    { 0, "exit",            ASN1_EOC,           ASN1_EXIT }
}
ASN.1 definition of the PKCS#7 ContentInfo type
Definition at line 34 of file pkcs7_generic.c.