strongSwan: printf_hook
printf_hook
utils
Modules
printf_hook_builtin
printf_hook_vstr
Classes
struct printf_hook_spec_t
struct printf_hook_t
Typedefs
typedef struct printf_hook_t printf_hook_t
typedef struct printf_hook_spec_t printf_hook_spec_t
typedef struct printf_hook_data_t printf_hook_data_t
typedef enum printf_hook_argtype_t printf_hook_argtype_t
typedef int(* printf_hook_function_t)(printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Enumerations
enum printf_hook_argtype_t { PRINTF_HOOK_ARGTYPE_END, PRINTF_HOOK_ARGTYPE_INT, PRINTF_HOOK_ARGTYPE_POINTER }
Functions
printf_hook_t * printf_hook_create ()
size_t print_in_hook (printf_hook_data_t *data, char *fmt,...)
Detailed Description
Typedef Documentation
typedef enum printf_hook_argtype_t printf_hook_argtype_t
Definition at line 30 of file printf_hook.h.
typedef struct printf_hook_data_t printf_hook_data_t
Definition at line 29 of file printf_hook.h.
typedef int(* printf_hook_function_t)(printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Callback function type for printf hooks.
Parameters
data hook data, to pass to print_in_hook()
spec format specifier
args arguments array
Returns
number of characters written
Definition at line 55 of file printf_hook.h.
typedef struct printf_hook_spec_t printf_hook_spec_t
Definition at line 28 of file printf_hook.h.
typedef struct printf_hook_t printf_hook_t
Definition at line 27 of file printf_hook.h.
Enumeration Type Documentation
enum printf_hook_argtype_t
Argument types to pass to printf hook.
Enumerator
PRINTF_HOOK_ARGTYPE_END
PRINTF_HOOK_ARGTYPE_INT
PRINTF_HOOK_ARGTYPE_POINTER
Definition at line 41 of file printf_hook.h.
{
     PRINTF_HOOK_ARGTYPE_END,
     PRINTF_HOOK_ARGTYPE_INT,
     PRINTF_HOOK_ARGTYPE_POINTER,
 };
Function Documentation
size_t print_in_hook (printf_hook_data_t * data, char * fmt, ...)
Print with format string within a printf hook.
Parameters
data hook data, as passed to printf hook
fmt printf format string
... arguments to format string
Returns
number of characters written
builtin-printf variant of print_in_hook()
Glibc variant of print_in_hook()
These are used below, whenever the public wrapper functions are called before initialization or after destruction. Vstr variant of print_in_hook()
Definition at line 114 of file printf_hook_builtin.c.
References printf_hook_data_t::base, builtin_vsnprintf(), printf_hook_data_t::n, printf_hook_data_t::pos, printf_hook_data_t::q, printf_hook_data_t::stream, and vfprintf.
Referenced by chunk_printf_hook(), enum_printf_hook(), host_printf_hook(), identification_printf_hook(), mem_printf_hook(), print_alg(), print_icmp(), proposal_printf_hook(), time_delta_printf_hook(), time_printf_hook(), and traffic_selector_printf_hook().
 {
     int written;
     va_list args;
     va_start(args, fmt);
     written = builtin_vsnprintf(data->q, data->n, fmt, args);
     va_end(args);
     if (written > data->n)
     {
         data->q += data->n;
         data->n = 0;
     }
     else
     {
         data->q += written;
         data->n -= written;
     }
     return written;
 }
printf_hook_t* printf_hook_create ()
Create a printf_hook instance.
Definition at line 1277 of file printf_hook_builtin.c.
References DBG1, DBG_LIB, free(), hashtable_create(), hashtable_equals_ptr(), hashtable_hash_ptr(), INIT, memset, and thread_value_create().
Referenced by library_init().
 {
     private_printf_hook_t *this;
     INIT(this,
         .public = {
             .add_handler = _add_handler,
             .destroy = _destroy,
         },
     );
     hooks = hashtable_create(hashtable_hash_ptr, hashtable_equals_ptr, 8);
     return &this->public;
 }