strongSwan: simaka_message.c File Reference
simaka_message.c File Reference
#include "simaka_message.h"
#include "simaka_manager.h"
#include <utils/debug.h>
#include <collections/linked_list.h>
Classes
struct hdr_t
struct attr_hdr_t
struct attr_t
struct private_simaka_message_t
Typedefs
typedef struct
private_simaka_message_t private_simaka_message_t
typedef struct hdr_t hdr_t
typedef struct attr_hdr_t attr_hdr_t
typedef struct attr_t attr_t
Functions
struct hdr_t __attribute__ ((__packed__))
ENUM_BEGIN (simaka_subtype_names, AKA_CHALLENGE, AKA_IDENTITY,"AKA_CHALLENGE","AKA_AUTHENTICATION_REJECT","AKA_3","AKA_SYNCHRONIZATION_FAILURE","AKA_IDENTITY")
ENUM_NEXT (simaka_subtype_names, SIM_START, AKA_CLIENT_ERROR, AKA_IDENTITY,"SIM_START","SIM_CHALLENGE","SIM/AKA_NOTIFICATION","SIM/AKA_REAUTHENTICATION","SIM/AKA_CLIENT_ERROR")
ENUM_END (simaka_subtype_names, AKA_CLIENT_ERROR)
ENUM_BEGIN (simaka_attribute_names, AT_RAND, AT_CLIENT_ERROR_CODE,"AT_RAND","AT_AUTN","AT_RES","AT_AUTS","AT_5","AT_PADDING","AT_NONCE_MT","AT_8","AT_9","AT_PERMANENT_ID_REQ","AT_MAC","AT_NOTIFICATION","AT_ANY_ID_REQ","AT_IDENTITY","AT_VERSION_LIST","AT_SELECTED_VERSION","AT_FULLAUTH_ID_REQ","AT_18","AT_COUNTER","AT_COUNTER_TOO_SMALL","AT_NONCE_S","AT_CLIENT_ERROR_CODE")
ENUM_NEXT (simaka_attribute_names, AT_IV, AT_RESULT_IND, AT_CLIENT_ERROR_CODE,"AT_IV","AT_ENCR_DATA","AT_131","AT_NEXT_PSEUDONYM","AT_NEXT_REAUTH_ID","AT_CHECKCODE","AT_RESULT_IND")
ENUM_END (simaka_attribute_names, AT_RESULT_IND)
ENUM_BEGIN (simaka_notification_names, SIM_GENERAL_FAILURE_AA, SIM_GENERAL_FAILURE_AA,"General failure after authentication")
ENUM_NEXT (simaka_notification_names, SIM_TEMP_DENIED, SIM_TEMP_DENIED, SIM_GENERAL_FAILURE_AA,"User has been temporarily denied access")
ENUM_NEXT (simaka_notification_names, SIM_NOT_SUBSCRIBED, SIM_NOT_SUBSCRIBED, SIM_TEMP_DENIED,"User has not subscribed to the requested service")
ENUM_NEXT (simaka_notification_names, SIM_GENERAL_FAILURE, SIM_GENERAL_FAILURE, SIM_NOT_SUBSCRIBED,"General failure")
ENUM_NEXT (simaka_notification_names, SIM_SUCCESS, SIM_SUCCESS, SIM_GENERAL_FAILURE,"User has been successfully authenticated")
ENUM_END (simaka_notification_names, SIM_SUCCESS)
ENUM (simaka_client_error_names, SIM_UNABLE_TO_PROCESS, SIM_RANDS_NOT_FRESH,"unable to process packet","unsupported version","insufficient number of challenges","RANDs are not fresh",)
bool simaka_attribute_skippable (simaka_attribute_t attribute)
METHOD (simaka_message_t, is_request, bool, private_simaka_message_t *this)
METHOD (simaka_message_t, get_identifier, u_int8_t, private_simaka_message_t *this)
METHOD (simaka_message_t, get_subtype, simaka_subtype_t, private_simaka_message_t *this)
METHOD (simaka_message_t, get_type, eap_type_t, private_simaka_message_t *this)
static bool attr_enum_filter (void *null, attr_t **in, simaka_attribute_t *type, void *dummy, chunk_t *data)
METHOD (simaka_message_t, create_attribute_enumerator, enumerator_t *, private_simaka_message_t *this)
METHOD (simaka_message_t, add_attribute, void, private_simaka_message_t *this, simaka_attribute_t type, chunk_t data)
static bool not_encrypted (simaka_attribute_t type)
static bool invalid_length (simaka_attribute_t type)
static void call_hook (private_simaka_message_t *this, bool inbound, bool decrypted)
static bool parse_attributes (private_simaka_message_t *this, chunk_t in)
static bool decrypt (private_simaka_message_t *this)
METHOD (simaka_message_t, parse, bool, private_simaka_message_t *this)
METHOD (simaka_message_t, verify, bool, private_simaka_message_t *this, chunk_t sigdata)
METHOD (simaka_message_t, generate, bool, private_simaka_message_t *this, chunk_t sigdata, chunk_t *gen)
METHOD (simaka_message_t, destroy, void, private_simaka_message_t *this)
static simaka_message_t * simaka_message_create_data (chunk_t data, simaka_crypto_t *crypto)
simaka_message_t * simaka_message_create_from_payload (chunk_t data, simaka_crypto_t *crypto)
simaka_message_t * simaka_message_create (bool request, u_int8_t identifier, eap_type_t type, simaka_subtype_t subtype, simaka_crypto_t *crypto)
Variables
u_int8_t code
u_int8_t identifier
u_int16_t length
u_int8_t type
u_int8_t subtype
u_int16_t reserved
struct attr_t __attribute__
Typedef Documentation
typedef struct attr_hdr_t attr_hdr_t
Definition at line 25 of file simaka_message.c.
typedef struct attr_t attr_t
Definition at line 26 of file simaka_message.c.
typedef struct hdr_t hdr_t
Definition at line 24 of file simaka_message.c.
typedef struct private_simaka_message_t private_simaka_message_t
Definition at line 23 of file simaka_message.c.
Function Documentation
static bool attr_enum_filter (void * null, attr_t ** in, simaka_attribute_t * type, void * dummy, chunk_t * data) static
convert attr_t to type and data enumeration
Definition at line 228 of file simaka_message.c.
References chunk_create(), attr_t::data, in, attr_t::len, TRUE, and attr_t::type.
Referenced by METHOD().
 {
     attr_t *attr = *in;
     *type = attr->type;
     *data = chunk_create(attr->data, attr->len);
     return TRUE;
 }
static void call_hook (private_simaka_message_t * this, bool inbound, bool decrypted) static
Call SIM/AKA message hooks
Definition at line 280 of file simaka_message.c.
Referenced by METHOD(), and parse_attributes().
 {
     simaka_manager_t *mgr;
     switch (this->hdr->type)
     {
         case EAP_SIM:
             mgr = lib->get(lib, "sim-manager");
             break;
         case EAP_AKA:
             mgr = lib->get(lib, "aka-manager");
             break;
         default:
             return;
     }
     mgr->message_hook(mgr, &this->public, inbound, decrypted);
 }
static bool decrypt (private_simaka_message_t * this) static
Decrypt a message and parse the decrypted attributes
Definition at line 485 of file simaka_message.c.
References crypter, DBG1, DBG_LIB, crypter_t::decrypt, eap_type_names, FALSE, free(), crypter_t::get_block_size, parse_attributes(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     bool success;
     crypter_t *crypter;
     chunk_t plain;
     crypter = this->crypto->get_crypter(this->crypto);
     if (!crypter || !this->iv.len || !this->encr.len || this->encrypted)
     {
         return TRUE;
     }
     if (this->encr.len % crypter->get_block_size(crypter))
     {
         DBG1(DBG_LIB, "%N ENCR_DATA not a multiple of block size",
              eap_type_names, this->hdr->type);
         return FALSE;
     }
     if (!crypter->decrypt(crypter, this->encr, this->iv, &plain))
     {
         return FALSE;
     }
     this->encrypted = TRUE;
     success = parse_attributes(this, plain);
     this->encrypted = FALSE;
     free(plain.ptr);
     return success;
 }
ENUM (simaka_client_error_names , SIM_UNABLE_TO_PROCESS , SIM_RANDS_NOT_FRESH , "unable to process packet" , "unsupported version" , "insufficient number of challenges" , "RANDs are not fresh")
ENUM_BEGIN (simaka_subtype_names , AKA_CHALLENGE , AKA_IDENTITY , "AKA_CHALLENGE" , "AKA_AUTHENTICATION_REJECT" , "AKA_3" , "AKA_SYNCHRONIZATION_FAILURE" , "AKA_IDENTITY")
ENUM_BEGIN (simaka_attribute_names , AT_RAND , AT_CLIENT_ERROR_CODE , "AT_RAND" , "AT_AUTN" , "AT_RES" , "AT_AUTS" , "AT_5" , "AT_PADDING" , "AT_NONCE_MT" , "AT_8" , "AT_9" , "AT_PERMANENT_ID_REQ" , "AT_MAC" , "AT_NOTIFICATION" , "AT_ANY_ID_REQ" , "AT_IDENTITY" , "AT_VERSION_LIST" , "AT_SELECTED_VERSION" , "AT_FULLAUTH_ID_REQ" , "AT_18" , "AT_COUNTER" , "AT_COUNTER_TOO_SMALL" , "AT_NONCE_S" , "AT_CLIENT_ERROR_CODE")
ENUM_BEGIN (simaka_notification_names , SIM_GENERAL_FAILURE_AA , SIM_GENERAL_FAILURE_AA , "General failure after authentication")
ENUM_END (simaka_subtype_names , AKA_CLIENT_ERROR)
ENUM_END (simaka_attribute_names , AT_RESULT_IND)
ENUM_END (simaka_notification_names , SIM_SUCCESS)
ENUM_NEXT (simaka_subtype_names , SIM_START , AKA_CLIENT_ERROR , AKA_IDENTITY , "SIM_START" , "SIM_CHALLENGE" , "SIM/AKA_NOTIFICATION" , "SIM/AKA_REAUTHENTICATION" , "SIM/AKA_CLIENT_ERROR")
ENUM_NEXT (simaka_attribute_names , AT_IV , AT_RESULT_IND , AT_CLIENT_ERROR_CODE , "AT_IV" , "AT_ENCR_DATA" , "AT_131" , "AT_NEXT_PSEUDONYM" , "AT_NEXT_REAUTH_ID" , "AT_CHECKCODE" , "AT_RESULT_IND")
ENUM_NEXT (simaka_notification_names , SIM_TEMP_DENIED , SIM_TEMP_DENIED , SIM_GENERAL_FAILURE_AA , "User has been temporarily denied access")
ENUM_NEXT (simaka_notification_names , SIM_NOT_SUBSCRIBED , SIM_NOT_SUBSCRIBED , SIM_TEMP_DENIED , "User has not subscribed to the requested service")
ENUM_NEXT (simaka_notification_names , SIM_GENERAL_FAILURE , SIM_GENERAL_FAILURE , SIM_NOT_SUBSCRIBED , "General failure")
ENUM_NEXT (simaka_notification_names , SIM_SUCCESS , SIM_SUCCESS , SIM_GENERAL_FAILURE , "User has been successfully authenticated")
static bool invalid_length (simaka_attribute_t type) static
Error handling for invalid length
Definition at line 271 of file simaka_message.c.
References DBG1, DBG_LIB, FALSE, and simaka_attribute_names.
Referenced by parse_attributes().
 {
     DBG1(DBG_LIB, "invalid length of %N", simaka_attribute_names, type);
     return FALSE;
 }
METHOD (simaka_message_t , is_request , bool , private_simaka_message_t * this)
Definition at line 201 of file simaka_message.c.
References EAP_REQUEST.
 {
     return this->hdr->code == EAP_REQUEST;
 }
METHOD (simaka_message_t , get_identifier , u_int8_t , private_simaka_message_t * this)
Definition at line 207 of file simaka_message.c.
 {
     return this->hdr->identifier;
 }
METHOD (simaka_message_t , get_subtype , simaka_subtype_t , private_simaka_message_t * this)
Definition at line 213 of file simaka_message.c.
 {
     return this->hdr->subtype;
 }
METHOD (simaka_message_t , get_type , eap_type_t , private_simaka_message_t * this)
Definition at line 219 of file simaka_message.c.
 {
     return this->hdr->type;
 }
METHOD (simaka_message_t , create_attribute_enumerator , enumerator_t * , private_simaka_message_t * this)
Definition at line 238 of file simaka_message.c.
References attr_enum_filter(), attributes, and enumerator_create_filter().
 {
     return enumerator_create_filter(
                         this->attributes->create_enumerator(this->attributes),
                         (void*)attr_enum_filter, NULL, NULL);
 }
METHOD (simaka_message_t , add_attribute , void , private_simaka_message_t * this, simaka_attribute_t type, chunk_t data)
Definition at line 246 of file simaka_message.c.
References attributes, attr_t::data, chunk_t::len, attr_t::len, malloc(), memcpy, chunk_t::ptr, attr_t::type, and type.
 {
     attr_t *attr;
     attr = malloc(sizeof(attr_t) + data.len);
     attr->len = data.len;
     attr->type = type;
     memcpy(attr->data, data.ptr, data.len);
     this->attributes->insert_last(this->attributes, attr);
 }
METHOD (simaka_message_t , parse , bool , private_simaka_message_t * this)
Definition at line 514 of file simaka_message.c.
References attributes, chunk_create(), chunk_skip(), decrypt(), FALSE, in, and parse_attributes().
 {
     chunk_t in;
     if (this->attributes->get_count(this->attributes))
     {   /* Already parsed. Try to decrypt and parse AT_ENCR_DATA. */
         return decrypt(this);
     }
     in = chunk_create((char*)this->hdr, ntohs(this->hdr->length));
     if (!parse_attributes(this, chunk_skip(in, sizeof(hdr_t))))
     {
         return FALSE;
     }
     /* try to decrypt if we already have keys */
     return decrypt(this);
 }
METHOD (simaka_message_t , verify , bool , private_simaka_message_t * this, chunk_t sigdata)
Definition at line 533 of file simaka_message.c.
References AKA_AUTHENTICATION_REJECT, AKA_CHALLENGE, AKA_IDENTITY, AKA_SYNCHRONIZATION_FAILURE, chunk_cata, chunk_clonea, chunk_create(), data, DBG1, DBG_LIB, eap_type_names, FALSE, chunk_t::len, memset, signer, SIM_CHALLENGE, SIM_CLIENT_ERROR, SIM_NOTIFICATION, SIM_REAUTHENTICATION, SIM_START, simaka_subtype_names, TRUE, and signer_t::verify_signature.
 {
     chunk_t data, backup;
     signer_t *signer;
     signer = this->crypto->get_signer(this->crypto);
     switch (this->hdr->subtype)
     {
         case SIM_START:
         case SIM_CLIENT_ERROR:
           /* AKA_CLIENT_ERROR: */
         case AKA_AUTHENTICATION_REJECT:
         case AKA_SYNCHRONIZATION_FAILURE:
         case AKA_IDENTITY:
             /* skip MAC if available */
             return TRUE;
         case SIM_CHALLENGE:
         case AKA_CHALLENGE:
         case SIM_REAUTHENTICATION:
           /* AKA_REAUTHENTICATION: */
         {
             if (!this->mac.ptr || !signer)
             {   /* require MAC, but not found */
                 DBG1(DBG_LIB, "%N message requires a MAC, but none found",
                      simaka_subtype_names, this->hdr->subtype);
                 return FALSE;
             }
             break;
         }
         case SIM_NOTIFICATION:
           /* AKA_NOTIFICATION: */
         {
             if (this->p_bit)
             {   /* MAC not verified if in Phase 1 */
                 return TRUE;
             }
             if (!this->mac.ptr || !signer)
             {
                 DBG1(DBG_LIB, "%N message has a phase 0 notify, but "
                      "no MAC found", simaka_subtype_names, this->hdr->subtype);
                 return FALSE;
             }
             break;
         }
         default:
             /* unknown message? */
             DBG1(DBG_LIB, "signature rule for %N messages missing",
                  simaka_subtype_names, this->hdr->subtype);
             return FALSE;
     }
     /* zero MAC for verification */
     backup = chunk_clonea(this->mac);
     memset(this->mac.ptr, 0, this->mac.len);
     data = chunk_create((char*)this->hdr, ntohs(this->hdr->length));
     if (sigdata.len)
     {
         data = chunk_cata("cc", data, sigdata);
     }
     if (!signer->verify_signature(signer, data, backup))
     {
         DBG1(DBG_LIB, "%N MAC verification failed",
              eap_type_names, this->hdr->type);
         return FALSE;
     }
     return TRUE;
 }
METHOD (simaka_message_t , generate , bool , private_simaka_message_t * this, chunk_t sigdata, chunk_t * gen)
Definition at line 604 of file simaka_message.c.
References AKA_CHALLENGE, AT_ANY_ID_REQ, AT_AUTN, AT_AUTS, AT_CLIENT_ERROR_CODE, AT_COUNTER, AT_COUNTER_TOO_SMALL, AT_ENCR_DATA, AT_FULLAUTH_ID_REQ, AT_IDENTITY, AT_IV, AT_MAC, AT_NEXT_PSEUDONYM, AT_NEXT_REAUTH_ID, AT_NONCE_MT, AT_NONCE_S, AT_NOTIFICATION, AT_PADDING, AT_PERMANENT_ID_REQ, AT_RAND, AT_RES, AT_SELECTED_VERSION, AT_VERSION_LIST, call_hook(), chunk_cata, chunk_clone, chunk_clonea, chunk_create(), chunk_empty, chunk_skip(), crypter, data, DBG1, DBG_LIB, enumerator_t::destroy, crypter_t::encrypt, enumerator_t::enumerate, FALSE, signer_t::get_block_size, crypter_t::get_block_size, rng_t::get_bytes, crypter_t::get_iv_size, signer_t::get_signature, chunk_t::len, len, attr_hdr_t::length, memcpy, memset, out, padding, chunk_t::ptr, rng, signer, SIM_CHALLENGE, SIM_REAUTHENTICATION, simaka_attribute_names, TRUE, attr_hdr_t::type, and type.
 {
     /* buffers large enough for messages we generate */
     char out_buf[1024], encr_buf[512];
     enumerator_t *enumerator;
     chunk_t out, encr, data, *target, mac = chunk_empty;
     simaka_attribute_t type;
     attr_hdr_t *hdr;
     u_int16_t len;
     signer_t *signer;
     call_hook(this, FALSE, TRUE);
     out = chunk_create(out_buf, sizeof(out_buf));
     encr = chunk_create(encr_buf, sizeof(encr_buf));
     /* copy header */
     memcpy(out.ptr, this->hdr, sizeof(hdr_t));
     out = chunk_skip(out, sizeof(hdr_t));
     /* encode attributes */
     enumerator = create_attribute_enumerator(this);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         /* encrypt this attribute? */
         switch (type)
         {
             case AT_NONCE_S:
             case AT_NEXT_PSEUDONYM:
             case AT_NEXT_REAUTH_ID:
             case AT_COUNTER:
             case AT_COUNTER_TOO_SMALL:
                 target = &encr;
                 break;
             case AT_NOTIFICATION:
                 /* P bit not set, encrypt */
                 if (!(data.ptr[0] & 0x40))
                 {
                     target = &encr;
                     break;
                 }
                 /* FALL */
             default:
                 target = &out;
                 break;
         }
         hdr = (attr_hdr_t*)target->ptr;
         hdr->type = type;
         /* encode type specific */
         switch (type)
         {
             /* attributes without data */
             case AT_COUNTER_TOO_SMALL:
             case AT_ANY_ID_REQ:
             case AT_PERMANENT_ID_REQ:
             case AT_FULLAUTH_ID_REQ:
             {
                 hdr->length = 1;
                 memset(target->ptr + 2, 0, 2);
                 *target = chunk_skip(*target, 4);
                 break;
             }
             /* attributes with two bytes data */
             case AT_COUNTER:
             case AT_CLIENT_ERROR_CODE:
             case AT_SELECTED_VERSION:
             case AT_NOTIFICATION:
             {
                 hdr->length = 1;
                 memcpy(target->ptr + 2, data.ptr, 2);
                 *target = chunk_skip(*target, 4);
                 break;
             }
             /* attributes with an additional actual-length in bits or bytes */
             case AT_NEXT_PSEUDONYM:
             case AT_NEXT_REAUTH_ID:
             case AT_IDENTITY:
             case AT_VERSION_LIST:
             case AT_RES:
             {
                 u_int16_t len, padding;
                 len = htons(data.len);
                 if (type == AT_RES)
                 {   /* AT_RES uses length encoding in bits */
                     len *= 8;
                 }
                 memcpy(target->ptr + 2, &len, sizeof(len));
                 memcpy(target->ptr + 4, data.ptr, data.len);
                 hdr->length = data.len / 4 + 1;
                 padding = (4 - (data.len % 4)) % 4;
                 if (padding)
                 {
                     hdr->length++;
                     memset(target->ptr + 4 + data.len, 0, padding);
                 }
                 *target = chunk_skip(*target, hdr->length * 4);
                 break;
             }
             /* attributes with two reserved bytes, 16 bytes length */
             case AT_NONCE_S:
             case AT_NONCE_MT:
             case AT_AUTN:
             {
                 hdr->length = 5;
                 memset(target->ptr + 2, 0, 2);
                 memcpy(target->ptr + 4, data.ptr, data.len);
                 *target = chunk_skip(*target, 20);
                 break;
             }
             /* attributes with two reserved bytes, variable length */
             case AT_RAND:
             {
                 hdr->length = 1 + data.len / 4;
                 memset(target->ptr + 2, 0, 2);
                 memcpy(target->ptr + 4, data.ptr, data.len);
                 *target = chunk_skip(*target, data.len + 4);
                 break;
             }
             /* attributes with no reserved bytes, 14 bytes length */
             case AT_AUTS:
             {
                 hdr->length = 4;
                 memcpy(target->ptr + 2, data.ptr, data.len);
                 *target = chunk_skip(*target, 16);
                 break;
             }
             default:
             {
                 DBG1(DBG_LIB, "no rule to encode %N, skipped",
                      simaka_attribute_names, type);
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     /* encrypt attributes, if any */
     if (encr.len < sizeof(encr_buf))
     {
         chunk_t iv;
         size_t bs, padding;
         crypter_t *crypter;
         rng_t *rng;
         crypter = this->crypto->get_crypter(this->crypto);
         bs = crypter->get_block_size(crypter);
         iv.len = crypter->get_iv_size(crypter);
         /* add AT_PADDING attribute */
         padding = bs - ((sizeof(encr_buf) - encr.len) % bs);
         if (padding)
         {
             hdr = (attr_hdr_t*)encr.ptr;
             hdr->type = AT_PADDING;
             hdr->length = padding / 4;
             memset(encr.ptr + 2, 0, padding - 2);
             encr = chunk_skip(encr, padding);
         }
         encr = chunk_create(encr_buf, sizeof(encr_buf) - encr.len);
         /* add IV attribute */
         hdr = (attr_hdr_t*)out.ptr;
         hdr->type = AT_IV;
         hdr->length = iv.len / 4 + 1;
         memset(out.ptr + 2, 0, 2);
         out = chunk_skip(out, 4);
         rng = this->crypto->get_rng(this->crypto);
         if (!rng->get_bytes(rng, iv.len, out.ptr))
         {
             return FALSE;
         }
         iv = chunk_clonea(chunk_create(out.ptr, iv.len));
         out = chunk_skip(out, iv.len);
         /* inline encryption */
         if (!crypter->encrypt(crypter, encr, iv, NULL))
         {
             return FALSE;
         }
         /* add ENCR_DATA attribute */
         hdr = (attr_hdr_t*)out.ptr;
         hdr->type = AT_ENCR_DATA;
         hdr->length = encr.len / 4 + 1;
         memset(out.ptr + 2, 0, 2);
         memcpy(out.ptr + 4, encr.ptr, encr.len);
         out = chunk_skip(out, encr.len + 4);
     }
     /* include MAC ? */
     signer = this->crypto->get_signer(this->crypto);
     switch (this->hdr->subtype)
     {
         case SIM_CHALLENGE:
         case AKA_CHALLENGE:
         case SIM_REAUTHENTICATION:
           /* AKA_REAUTHENTICATION: */
         /* TODO: Notifications without P bit */
         {
             size_t bs;
             bs = signer->get_block_size(signer);
             hdr = (attr_hdr_t*)out.ptr;
             hdr->type = AT_MAC;
             hdr->length = bs / 4 + 1;
             memset(out.ptr + 2, 0, 2 + bs);
             mac = chunk_create(out.ptr + 4, bs);
             out = chunk_skip(out, bs + 4);
             break;
         }
         default:
             break;
     }
     /* calculate message length */
     out = chunk_create(out_buf, sizeof(out_buf) - out.len);
     len = htons(out.len);
     memcpy(out.ptr + 2, &len, sizeof(len));
     /* generate MAC */
     if (mac.len)
     {
         data = chunk_cata("cc", out, sigdata);
         if (!signer->get_signature(signer, data, mac.ptr))
         {
             return FALSE;
         }
     }
     call_hook(this, FALSE, FALSE);
     *gen = chunk_clone(out);
     return TRUE;
 }
METHOD (simaka_message_t , destroy , void , private_simaka_message_t * this)
Definition at line 845 of file simaka_message.c.
References attributes, and free().
 {
     this->attributes->destroy_function(this->attributes, free);
     free(this->hdr);
     free(this);
 }
static bool not_encrypted (simaka_attribute_t type) static
Error handling for unencrypted attributes
Definition at line 262 of file simaka_message.c.
References DBG1, DBG_LIB, FALSE, and simaka_attribute_names.
Referenced by parse_attributes().
 {
     DBG1(DBG_LIB, "received unencrypted %N", simaka_attribute_names, type);
     return FALSE;
 }
static bool parse_attributes (private_simaka_message_t * this, chunk_t in) static
Parse attributes from a chunk of data
Definition at line 302 of file simaka_message.c.
References add_attribute(), AT_ANY_ID_REQ, AT_AUTN, AT_AUTS, AT_CLIENT_ERROR_CODE, AT_COUNTER, AT_COUNTER_TOO_SMALL, AT_ENCR_DATA, AT_FULLAUTH_ID_REQ, AT_IDENTITY, AT_IV, AT_MAC, AT_NEXT_PSEUDONYM, AT_NEXT_REAUTH_ID, AT_NONCE_MT, AT_NONCE_S, AT_NOTIFICATION, AT_PADDING, AT_PERMANENT_ID_REQ, AT_RAND, AT_RES, AT_SELECTED_VERSION, AT_VERSION_LIST, call_hook(), chunk_create(), chunk_empty, chunk_skip(), data, DBG1, DBG_LIB, eap_type_names, FALSE, invalid_length(), chunk_t::len, len, attr_hdr_t::length, memcpy, not_encrypted(), chunk_t::ptr, TRUE, and attr_hdr_t::type.
Referenced by decrypt(), and METHOD().
 {
     while (in.len)
     {
         attr_hdr_t *hdr;
         chunk_t data;
         if (in.len < sizeof(attr_hdr_t))
         {
             DBG1(DBG_LIB, "found short %N attribute header",
                  eap_type_names, this->hdr->type);
             return FALSE;
         }
         hdr = (attr_hdr_t*)in.ptr;
         switch (hdr->type)
         {
             /* attributes without data */
             case AT_COUNTER_TOO_SMALL:
                 if (!this->encrypted)
                 {
                     return not_encrypted(hdr->type);
                 }
                 /* FALL */
             case AT_ANY_ID_REQ:
             case AT_PERMANENT_ID_REQ:
             case AT_FULLAUTH_ID_REQ:
             {
                 if (hdr->length != 1 || in.len < 4)
                 {
                     return invalid_length(hdr->type);
                 }
                 data = chunk_empty;
                 in = chunk_skip(in, 4);
                 break;
             }
             /* attributes with two bytes data */
             case AT_COUNTER:
                 if (!this->encrypted)
                 {
                     return not_encrypted(hdr->type);
                 }
                 /* FALL */
             case AT_CLIENT_ERROR_CODE:
             case AT_SELECTED_VERSION:
             case AT_NOTIFICATION:
             {
                 if (hdr->length != 1 || in.len < 4)
                 {
                     return invalid_length(hdr->type);
                 }
                 data = chunk_create(in.ptr + 2, 2);
                 in = chunk_skip(in, 4);
                 break;
             }
             /* attributes with an additional actual-length in bits or bytes */
             case AT_NEXT_PSEUDONYM:
             case AT_NEXT_REAUTH_ID:
                 if (!this->encrypted)
                 {
                     return not_encrypted(hdr->type);
                 }
                 /* FALL */
             case AT_RES:
             case AT_IDENTITY:
             case AT_VERSION_LIST:
             {
                 u_int16_t len;
                 if (hdr->length < 1 || in.len < 4)
                 {
                     return invalid_length(hdr->type);
                 }
                 memcpy(&len, in.ptr + 2, 2);
                 len = ntohs(len);
                 if (hdr->type == AT_RES)
                 {   /* AT_RES uses length encoding in bits */
                     len /= 8;
                 }
                 if (len > hdr->length * 4 || len > in.len)
                 {
                     return invalid_length(hdr->type);
                 }
                 data = chunk_create(in.ptr + 4, len);
                 in = chunk_skip(in, hdr->length * 4);
                 break;
             }
             /* attributes with two reserved bytes, 16 bytes length */
             case AT_NONCE_S:
                 if (!this->encrypted)
                 {
                     return not_encrypted(hdr->type);
                 }
                 /* FALL */
             case AT_AUTN:
             case AT_NONCE_MT:
             case AT_IV:
             case AT_MAC:
             {
                 if (hdr->length != 5 || in.len < 20)
                 {
                     return invalid_length(hdr->type);
                 }
                 data = chunk_create(in.ptr + 4, 16);
                 in = chunk_skip(in, 20);
                 break;
             }
             /* attributes with two reserved bytes, variable length */
             case AT_ENCR_DATA:
             case AT_RAND:
             {
                 if (hdr->length * 4 > in.len || in.len < 4)
                 {
                     return invalid_length(hdr->type);
                 }
                 data = chunk_create(in.ptr + 4, hdr->length * 4 - 4);
                 in = chunk_skip(in, hdr->length * 4);
                 break;
             }
             /* attributes with no reserved bytes, 14 bytes length */
             case AT_AUTS:
             {
                 if (hdr->length != 4 || in.len < 16)
                 {
                     return invalid_length(hdr->type);
                 }
                 data = chunk_create(in.ptr + 2, 14);
                 in = chunk_skip(in, 16);
                 break;
             }
             /* other attributes (with 4n + 2 length) */
             case AT_PADDING:
             default:
             {
                 if (hdr->length * 4 > in.len || in.len < 4)
                 {
                     return invalid_length(hdr->type);
                 }
                 data = chunk_create(in.ptr + 2, hdr->length * 4 - 2);
                 in = chunk_skip(in, hdr->length * 4);
                 break;
             }
         }
         /* handle special attributes */
         switch (hdr->type)
         {
             case AT_MAC:
                 this->mac = data;
                 break;
             case AT_IV:
                 this->iv = data;
                 break;
             case AT_ENCR_DATA:
                 this->encr = data;
                 break;
             case AT_PADDING:
                 break;
             case AT_NOTIFICATION:
                 if (this->p_bit)
                 {   /* remember P bit for MAC verification */
                     this->p_bit = !!(data.ptr[0] & 0x40);
                 }
                 else if (!this->encrypted)
                 {
                     DBG1(DBG_LIB, "found P-bit 0 notify in unencrypted message");
                     return FALSE;
                 }
                 /* FALL */
             default:
                 add_attribute(this, hdr->type, data);
                 break;
         }
     }
     call_hook(this, TRUE, this->encrypted);
     return TRUE;
 }
static simaka_message_t* simaka_message_create_data (chunk_t data, simaka_crypto_t * crypto) static
Generic constructor.
Definition at line 856 of file simaka_message.c.
References hdr_t::code, DBG1, DBG_LIB, EAP_AKA, EAP_REQUEST, EAP_RESPONSE, EAP_SIM, eap_type_names, if(), INIT, chunk_t::len, hdr_t::length, linked_list_create(), malloc(), memcpy, chunk_t::ptr, TRUE, and hdr_t::type.
Referenced by simaka_message_create(), and simaka_message_create_from_payload().
 {
     private_simaka_message_t *this;
     hdr_t *hdr = (hdr_t*)data.ptr;
     if (data.len < sizeof(hdr_t) || hdr->length != htons(data.len))
     {
         DBG1(DBG_LIB, "EAP-SIM/AKA header has invalid length");
         return NULL;
     }
     if (hdr->code != EAP_REQUEST && hdr->code != EAP_RESPONSE)
     {
         DBG1(DBG_LIB, "invalid EAP code in EAP-SIM/AKA message",
              eap_type_names, hdr->type);
         return NULL;
     }
     if (hdr->type != EAP_SIM && hdr->type != EAP_AKA)
     {
         DBG1(DBG_LIB, "invalid EAP type in EAP-SIM/AKA message",
              eap_type_names, hdr->type);
         return NULL;
     }
     INIT(this,
         .public = {
             .is_request = _is_request,
             .get_identifier = _get_identifier,
             .get_type = _get_type,
             .get_subtype = _get_subtype,
             .create_attribute_enumerator = _create_attribute_enumerator,
             .add_attribute = _add_attribute,
             .parse = _parse,
             .verify = _verify,
             .generate = _generate,
             .destroy = _destroy,
         },
         .attributes = linked_list_create(),
         .crypto = crypto,
         .p_bit = TRUE,
         .hdr = malloc(data.len),
     );
     memcpy(this->hdr, hdr, data.len);
     return &this->public;
 }
Variable Documentation
struct attr_t __attribute__
u_int8_t code
EAP code (REQUEST/RESPONSE)
Definition at line 280 of file simaka_message.c.
u_int8_t identifier
unique message identifier
Definition at line 282 of file simaka_message.c.
Referenced by simaka_message_create().
u_int8_t length
length of whole message
attibute length
Definition at line 284 of file simaka_message.c.
u_int16_t reserved
reserved bytes
Definition at line 290 of file simaka_message.c.
u_int8_t subtype
SIM subtype
Definition at line 288 of file simaka_message.c.
Referenced by decrypt(), decrypt_with_config(), determine_credtype(), issue(), keyid(), METHOD(), print(), pub(), simaka_message_create(), tls_crypto_create(), and TNC_IMC_BeginHandshake().
u_int8_t type
EAP type => EAP_SIM/EAP_AKA
attribute type
Definition at line 286 of file simaka_message.c.
Referenced by METHOD(), and simaka_message_create().