strongSwan: esp_packet_t Struct Reference
esp_packet_t Struct Reference
esp_packet
#include "esp_packet.h"
Public Attributes
packet_t packet
host_t *(* get_source)(esp_packet_t *this)
host_t *(* get_destination)(esp_packet_t *this)
bool(* parse_header)(esp_packet_t *this, u_int32_t *spi)
status_t(* decrypt)(esp_packet_t *this, esp_context_t *esp_context)
status_t(* encrypt)(esp_packet_t *this, esp_context_t *esp_context, u_int32_t spi)
u_int8_t(* get_next_header)(esp_packet_t *this)
ip_packet_t *(* get_payload)(esp_packet_t *this)
ip_packet_t *(* extract_payload)(esp_packet_t *this)
void(* destroy)(esp_packet_t *this)
Detailed Description
ESP packet
Definition at line 38 of file esp_packet.h.
Member Data Documentation
status_t(* esp_packet_t::decrypt)(esp_packet_t *this, esp_context_t *esp_context)
Authenticate and decrypt the packet. Also verifies the sequence number using the supplied ESP context and updates the anti-replay window.
Parameters
esp_context ESP context of corresponding inbound IPsec SA
Returns
- SUCCESS if successfully authenticated, decrypted and parsed
PARSE_ERROR if the length of the packet or the padding is invalid
VERIFY_ERROR if the sequence number verification failed
FAILED if the ICV (MAC) check or the actual decryption failed
Definition at line 83 of file esp_packet.h.
Referenced by process_inbound().
void(* esp_packet_t::destroy)(esp_packet_t *this)
Destroy an esp_packet_t
Definition at line 127 of file esp_packet.h.
Referenced by deliver_inbound(), process_inbound(), process_outbound(), send_outbound(), and START_TEST().
status_t(* esp_packet_t::encrypt)(esp_packet_t *this, esp_context_t *esp_context, u_int32_t spi)
Encapsulate and encrypt the packet. The sequence number will be generated using the supplied ESP context.
Parameters
esp_context ESP context of corresponding outbound IPsec SA
spi SPI value to use, in network byte order
Returns
- SUCCESS if encrypted
FAILED if sequence number cycled or any of the cryptographic functions failed
NOT_FOUND if no suitable IV generator provided
Definition at line 96 of file esp_packet.h.
Referenced by process_outbound(), and START_TEST().
ip_packet_t*(* esp_packet_t::extract_payload)(esp_packet_t *this)
Extract the plaintext payload from this packet.
Returns
plaintext payload (has to be destroyed), NULL if not decrypted
Definition at line 122 of file esp_packet.h.
Referenced by deliver_inbound().
host_t*(* esp_packet_t::get_destination)(esp_packet_t *this)
Get the destination address of this packet
Returns
destination host
Definition at line 57 of file esp_packet.h.
Referenced by process_inbound().
u_int8_t(* esp_packet_t::get_next_header)(esp_packet_t *this)
Get the next header field of a packet.
Note
Packet has to be in the decrypted state.
Returns
next header field
Definition at line 106 of file esp_packet.h.
Referenced by process_inbound().
ip_packet_t*(* esp_packet_t::get_payload)(esp_packet_t *this)
Get the plaintext payload of this packet.
Returns
plaintext payload (internal data), NULL if not decrypted
Definition at line 114 of file esp_packet.h.
Referenced by process_inbound().
host_t*(* esp_packet_t::get_source)(esp_packet_t *this)
Get the source address of this packet
Returns
source host
Definition at line 50 of file esp_packet.h.
packet_t esp_packet_t::packet
Implements packet_t interface to access the raw ESP packet
Definition at line 43 of file esp_packet.h.
Referenced by METHOD(), and START_TEST().
bool(* esp_packet_t::parse_header)(esp_packet_t *this, u_int32_t *spi)
Parse the packet header before decryption. Tries to read the SPI from the packet to find a corresponding SA.
Parameters
spi parsed SPI, in network byte order
Returns
TRUE when successful, FALSE otherwise (e.g. when the length of the packet is invalid)
Definition at line 67 of file esp_packet.h.
Referenced by process_inbound().
The documentation for this struct was generated from the following file:
esp_packet.h