strongSwan: ike_sa_manager
ike_sa_manager
sa
Classes
struct ike_sa_manager_t
Typedefs
typedef struct ike_sa_manager_t ike_sa_manager_t
typedef u_int64_t(* spi_cb_t)(void *data)
Functions
ike_sa_manager_t * ike_sa_manager_create (void)
Detailed Description
Typedef Documentation
typedef struct ike_sa_manager_t ike_sa_manager_t
Definition at line 26 of file ike_sa_manager.h.
typedef u_int64_t(* spi_cb_t)(void *data)
Callback called to generate an IKE SPI.
This may be called from multiple threads concurrently.
Parameters
data data supplied during registration of the callback
Returns
allocated SPI, 0 on failure
Definition at line 41 of file ike_sa_manager.h.
Function Documentation
ike_sa_manager_t* ike_sa_manager_create (void)
Create the IKE_SA manager.
Returns
ike_sa_manager_t object, NULL if initialization fails
Definition at line 2201 of file ike_sa_manager.c.
References crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_MGR, DEFAULT_HASHTABLE_SIZE, DEFAULT_SEGMENT_COUNT, free(), settings_t::get_bool, settings_t::get_int, get_nearest_powerof2(), INIT, lib, max, MAX_HASHTABLE_SIZE, min, mutex_create(), MUTEX_TYPE_RECURSIVE, library_t::ns, rng, RNG_WEAK, rwlock_create(), RWLOCK_TYPE_DEFAULT, library_t::settings, and TRUE.
Referenced by sa_managers_cb().
 {
     private_ike_sa_manager_t *this;
     u_int i;
     INIT(this,
         .public = {
             .checkout = _checkout,
             .checkout_new = _checkout_new,
             .checkout_by_message = _checkout_by_message,
             .checkout_by_config = _checkout_by_config,
             .checkout_by_id = _checkout_by_id,
             .checkout_by_name = _checkout_by_name,
             .check_uniqueness = _check_uniqueness,
             .has_contact = _has_contact,
             .create_enumerator = _create_enumerator,
             .create_id_enumerator = _create_id_enumerator,
             .checkin = _checkin,
             .checkin_and_destroy = _checkin_and_destroy,
             .get_count = _get_count,
             .get_half_open_count = _get_half_open_count,
             .flush = _flush,
             .set_spi_cb = _set_spi_cb,
             .destroy = _destroy,
         },
     );
     this->rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (this->rng == NULL)
     {
         DBG1(DBG_MGR, "manager initialization failed, no RNG supported");
         free(this);
         return NULL;
     }
     this->spi_lock = rwlock_create(RWLOCK_TYPE_DEFAULT);
     this->ikesa_limit = lib->settings->get_int(lib->settings,
                                                "%s.ikesa_limit", 0, lib->ns);
     this->table_size = get_nearest_powerof2(lib->settings->get_int(
                                     lib->settings, "%s.ikesa_table_size",
                                     DEFAULT_HASHTABLE_SIZE, lib->ns));
     this->table_size = max(1, min(this->table_size, MAX_HASHTABLE_SIZE));
     this->table_mask = this->table_size - 1;
     this->segment_count = get_nearest_powerof2(lib->settings->get_int(
                                     lib->settings, "%s.ikesa_table_segments",
                                     DEFAULT_SEGMENT_COUNT, lib->ns));
     this->segment_count = max(1, min(this->segment_count, this->table_size));
     this->segment_mask = this->segment_count - 1;
     this->ike_sa_table = calloc(this->table_size, sizeof(table_item_t*));
     this->segments = (segment_t*)calloc(this->segment_count, sizeof(segment_t));
     for (i = 0; i < this->segment_count; i++)
     {
         this->segments[i].mutex = mutex_create(MUTEX_TYPE_RECURSIVE);
         this->segments[i].count = 0;
     }
     /* we use the same table parameters for the table to track half-open SAs */
     this->half_open_table = calloc(this->table_size, sizeof(table_item_t*));
     this->half_open_segments = calloc(this->segment_count, sizeof(shareable_segment_t));
     for (i = 0; i < this->segment_count; i++)
     {
         this->half_open_segments[i].lock = rwlock_create(RWLOCK_TYPE_DEFAULT);
         this->half_open_segments[i].count = 0;
     }
     /* also for the hash table used for duplicate tests */
     this->connected_peers_table = calloc(this->table_size, sizeof(table_item_t*));
     this->connected_peers_segments = calloc(this->segment_count, sizeof(shareable_segment_t));
     for (i = 0; i < this->segment_count; i++)
     {
         this->connected_peers_segments[i].lock = rwlock_create(RWLOCK_TYPE_DEFAULT);
         this->connected_peers_segments[i].count = 0;
     }
     /* and again for the table of hashes of seen initial IKE messages */
     this->init_hashes_table = calloc(this->table_size, sizeof(table_item_t*));
     this->init_hashes_segments = calloc(this->segment_count, sizeof(segment_t));
     for (i = 0; i < this->segment_count; i++)
     {
         this->init_hashes_segments[i].mutex = mutex_create(MUTEX_TYPE_RECURSIVE);
         this->init_hashes_segments[i].count = 0;
     }
     this->reuse_ikesa = lib->settings->get_bool(lib->settings,
                                             "%s.reuse_ikesa", TRUE, lib->ns);
     return &this->public;
 }