strongSwan: mem_cred_t Struct Reference
mem_cred_t Struct Reference
mem_cred
#include "mem_cred.h"
Public Attributes
credential_set_t set
void(* add_cert)(mem_cred_t *this, bool trusted, certificate_t *cert)
certificate_t *(* add_cert_ref)(mem_cred_t *this, bool trusted, certificate_t *cert)
certificate_t *(* get_cert_ref)(mem_cred_t *this, certificate_t *cert)
bool(* add_crl)(mem_cred_t *this, crl_t *crl)
void(* add_key)(mem_cred_t *this, private_key_t *key)
void(* add_shared)(mem_cred_t *this, shared_key_t *shared,...)
void(* add_shared_list)(mem_cred_t *this, shared_key_t *shared, linked_list_t *owners)
void(* add_cdp)(mem_cred_t *this, certificate_type_t type, identification_t *id, char *uri)
void(* replace_certs)(mem_cred_t *this, mem_cred_t *other, bool clone)
void(* replace_secrets)(mem_cred_t *this, mem_cred_t *other, bool clone)
void(* clear)(mem_cred_t *this)
void(* clear_secrets)(mem_cred_t *this)
void(* destroy)(mem_cred_t *this)
Detailed Description
Generic in-memory credential set.
Definition at line 35 of file mem_cred.h.
Member Data Documentation
void(* mem_cred_t::add_cdp)(mem_cred_t *this, certificate_type_t type, identification_t *id, char *uri)
Add a certificate distribution point to the set.
Parameters
type type of the certificate
id certificate ID CDP has a cert for, gets cloned
uri CDP URI, gets strduped
Definition at line 113 of file mem_cred.h.
Referenced by load_cdps().
void(* mem_cred_t::add_cert)(mem_cred_t *this, bool trusted, certificate_t *cert)
Add a certificate to the credential set.
Parameters
trusted TRUE to serve certificate as trusted
cert certificate, reference gets owned by set
Definition at line 48 of file mem_cred.h.
Referenced by add_cert(), add_certificate(), CALLBACK(), initiate_connection(), load_agent(), load_ca_dir(), load_cacerts(), load_cert(), load_certificate(), load_certs(), load_pkcs12(), load_x509(), load_x509_aa(), load_x509_ac(), load_x509_ca(), main(), parse(), pkcs7(), pkcs7_signed_data_gen(), soap_init(), START_SETUP(), START_TEST(), and verify().
certificate_t*(* mem_cred_t::add_cert_ref)(mem_cred_t *this, bool trusted, certificate_t *cert)
Add a certificate to the credential set, returning a reference to it or to a cached duplicate.
Parameters
trusted TRUE to serve certificate as trusted
cert certificate, reference gets owned by set
Returns
reference to cert or a previously cached duplicate
Definition at line 58 of file mem_cred.h.
Referenced by METHOD(), and soap_init().
bool(* mem_cred_t::add_crl)(mem_cred_t *this, crl_t *crl)
Add an X.509 CRL to the credential set.
Parameters
crl CRL, gets owned by set
Returns
TRUE, if the CRL is newer than an existing one (or new at all)
Definition at line 80 of file mem_cred.h.
Referenced by CALLBACK(), load_x509_crl(), and METHOD().
void(* mem_cred_t::add_key)(mem_cred_t *this, private_key_t *key)
Add a private key to the credential set.
Parameters
key key, reference gets owned by set
Definition at line 87 of file mem_cred.h.
Referenced by add_key(), CALLBACK(), load_agent(), load_key(), load_keys(), load_pin(), load_pkcs12(), load_private(), main(), METHOD(), parse_safe_contents(), pkcs7(), soap_init(), and START_SETUP().
void(* mem_cred_t::add_shared)(mem_cred_t *this, shared_key_t *shared,...)
Add a shared key to the credential set.
Parameters
shared shared key to add, gets owned by set
... NULL terminated list of owners (identification_t*)
Definition at line 95 of file mem_cred.h.
Referenced by CALLBACK(), callback_shared(), cb(), decrypt_with_config(), initiate_connection(), load_from_file(), load_pin(), main(), and passphrase_cb().
void(* mem_cred_t::add_shared_list)(mem_cred_t *this, shared_key_t *shared, linked_list_t *owners)
Add a shared key to the credential set.
Parameters
shared shared key to add, gets owned by set
owners list of owners (identification_t*), gets owned
Definition at line 103 of file mem_cred.h.
Referenced by CALLBACK(), load_shared(), and METHOD().
void(* mem_cred_t::clear)(mem_cred_t *this)
Clear all credentials from the credential set.
Definition at line 138 of file mem_cred.h.
Referenced by CALLBACK(), and initiate_connection().
void(* mem_cred_t::clear_secrets)(mem_cred_t *this)
Clear the secrets (private and shared keys, not the certificates) from the credential set.
Definition at line 144 of file mem_cred.h.
void(* mem_cred_t::destroy)(mem_cred_t *this)
Destroy a mem_cred_t.
Definition at line 149 of file mem_cred.h.
Referenced by cleanup(), decrypt(), decrypt_with_config(), exit_scepclient(), load_certs(), load_creds(), load_from_file(), load_pin(), load_secrets(), METHOD(), nm_backend_deinit(), open_database(), pkcs7(), register_load_tester(), remove_callback(), START_TEARDOWN(), and verify().
certificate_t*(* mem_cred_t::get_cert_ref)(mem_cred_t *this, certificate_t *cert)
Get an existing reference to the same certificate.
Searches for the same certficate in the set, and returns a reference to it, destroying the passed certificate. If the passed certificate is not found, it is just returned.
Parameters
cert certificate to look up
Returns
the same certificate, potentially different instance
Definition at line 71 of file mem_cred.h.
Referenced by METHOD().
void(* mem_cred_t::replace_certs)(mem_cred_t *this, mem_cred_t *other, bool clone)
Replace all certificates in this credential set with those of another.
Parameters
other credential set to get certificates from
clone TRUE to clone certs, FALSE to adopt them (they get removed from the other set)
Definition at line 123 of file mem_cred.h.
void(* mem_cred_t::replace_secrets)(mem_cred_t *this, mem_cred_t *other, bool clone)
Replace all secrets (private and shared keys) in this credential set with those of another.
Parameters
other credential set to get secrets from
clone TRUE to clone secrets, FALSE to adopt them (they get removed from the other set)
Definition at line 133 of file mem_cred.h.
Referenced by load_secrets().
credential_set_t mem_cred_t::set
Implements credential_set_t.
Definition at line 40 of file mem_cred.h.
Referenced by add_callback(), cleanup(), decrypt(), decrypt_with_config(), exit_scepclient(), init(), load_from_file(), load_pin(), main(), METHOD(), pkcs7(), remove_callback(), START_SETUP(), START_TEARDOWN(), and verify().
The documentation for this struct was generated from the following file:
mem_cred.h