strongSwan: mem_pool
mem_pool
attributes
Classes
struct mem_pool_t
Typedefs
typedef struct mem_pool_t mem_pool_t
typedef enum mem_pool_op_t mem_pool_op_t
Enumerations
enum mem_pool_op_t { MEM_POOL_EXISTING, MEM_POOL_NEW, MEM_POOL_REASSIGN }
Functions
mem_pool_t * mem_pool_create (char *name, host_t *base, int bits)
mem_pool_t * mem_pool_create_range (char *name, host_t *from, host_t *to)
Detailed Description
Typedef Documentation
typedef enum mem_pool_op_t mem_pool_op_t
Definition at line 25 of file mem_pool.h.
typedef struct mem_pool_t mem_pool_t
Definition at line 24 of file mem_pool.h.
Enumeration Type Documentation
enum mem_pool_op_t
In-memory IP pool acquire operation.
Enumerator
MEM_POOL_EXISTING
Check for an exsiting lease
MEM_POOL_NEW
Get a new lease
MEM_POOL_REASSIGN
Replace an existing offline lease of another ID
Definition at line 33 of file mem_pool.h.
                    {
     MEM_POOL_EXISTING,
     MEM_POOL_NEW,
     MEM_POOL_REASSIGN,
 };
Function Documentation
mem_pool_t* mem_pool_create (char * name, host_t * base, int bits)
Create an in-memory IP address pool.
An empty pool just returns the requested address.
Parameters
name name of this pool
base base address of this pool, NULL to create an empty pool
bits number of non-network bits in base, as in CIDR notation
Returns
memory pool instance
Described in header
Definition at line 654 of file mem_pool.c.
References bits, host_t::clone, create_generic(), DBG1, DBG_CFG, host_t::get_family, max, min, network_id_diff(), POOL_LIMIT, size, and TRUE.
Referenced by build_peer_cfg(), CALLBACK(), load_addrs(), and START_TEST().
 {
     private_mem_pool_t *this;
     u_int diff;
     int addr_bits;
     this = create_generic(name);
     if (base)
     {
         addr_bits = base->get_family(base) == AF_INET ? 32 : 128;
         bits = max(0, min(bits, addr_bits));
         /* net bits -> host bits */
         bits = addr_bits - bits;
         if (bits > POOL_LIMIT)
         {
             bits = POOL_LIMIT;
             DBG1(DBG_CFG, "virtual IP pool too large, limiting to %H/%d",
                  base, addr_bits - bits);
         }
         this->size = 1 << bits;
         this->base = base->clone(base);
         if (this->size > 2)
         {
             /* if base is the network id we later skip the first address,
              * otherwise adjust the size to represent the actual number
              * of assignable addresses */
             diff = network_id_diff(base, bits);
             if (!diff)
             {
                 this->base_is_network_id = TRUE;
                 this->size--;
             }
             else
             {
                 this->size -= diff;
             }
             /* skip the last address (broadcast) of the subnet */
             this->size--;
         }
         else if (network_id_diff(base, bits))
         {   /* only serve the second address of the subnet */
             this->size--;
         }
     }
     return &this->public;
 }
mem_pool_t* mem_pool_create_range (char * name, host_t * from, host_t * to)
Create an in-memory IP address from a range.
Parameters
name name of this pool
from start of ranged pool
to end of ranged pool
Returns
memory pool instance, NULL if range invalid
Described in header
Definition at line 705 of file mem_pool.c.
References base, chunk_create(), chunk_equals(), host_t::clone, create_generic(), DBG1, DBG_CFG, host_t::get_address, host_t::get_family, chunk_t::len, chunk_t::ptr, size, and untoh32().
Referenced by create_pool_range(), load_addrs(), and START_TEST().
 {
     private_mem_pool_t *this;
     chunk_t fromaddr, toaddr;
     u_int32_t diff;
     fromaddr = from->get_address(from);
     toaddr = to->get_address(to);
     if (from->get_family(from) != to->get_family(to) ||
         fromaddr.len != toaddr.len || fromaddr.len < sizeof(diff) ||
         memcmp(fromaddr.ptr, toaddr.ptr, toaddr.len) > 0)
     {
         DBG1(DBG_CFG, "invalid IP address range: %H-%H", from, to);
         return NULL;
     }
     if (fromaddr.len > sizeof(diff) &&
         !chunk_equals(chunk_create(fromaddr.ptr, fromaddr.len - sizeof(diff)),
                       chunk_create(toaddr.ptr, toaddr.len - sizeof(diff))))
     {
         DBG1(DBG_CFG, "IP address range too large: %H-%H", from, to);
         return NULL;
     }
     this = create_generic(name);
     this->base = from->clone(from);
     diff = untoh32(toaddr.ptr + toaddr.len - sizeof(diff)) -
            untoh32(fromaddr.ptr + fromaddr.len - sizeof(diff));
     this->size = diff + 1;
     return &this->public;
 }