strongSwan: kernel_netlink_net
kernel_netlink_net
kernel_netlink
Classes
struct kernel_netlink_net_t
Typedefs
typedef struct kernel_netlink_net_t kernel_netlink_net_t
Functions
kernel_netlink_net_t * kernel_netlink_net_create ()
Detailed Description
Typedef Documentation
typedef struct kernel_netlink_net_t kernel_netlink_net_t
Definition at line 26 of file kernel_netlink_net.h.
Function Documentation
kernel_netlink_net_t* kernel_netlink_net_create ()
Create a netlink kernel network interface instance.
Returns
kernel_netlink_net_t instance
Definition at line 2544 of file kernel_netlink_net.c.
References watcher_t::add, addr_map_entry_equals(), addr_map_entry_hash(), bind, check_kernel_features(), DBG1, DBG_KNL, enumerator_t::destroy, destroy(), enumerator_t::enumerate, enumerator_create_token(), FALSE, settings_t::get_bool, settings_t::get_int, settings_t::get_str, hashtable_create(), INIT, init_address_list(), lib, linked_list_create(), manage_rule(), memset, mutex_create(), MUTEX_TYPE_DEFAULT, net_change_equals(), net_change_hash(), NETLINK_ROUTE, netlink_socket_create(), sockaddr_nl::nl_family, sockaddr_nl::nl_groups, library_t::ns, receive_events(), route_entry_equals(), route_entry_hash(), ROUTING_TABLE, ROUTING_TABLE_PRIO, RTM_NEWRULE, RTMGRP_IPV4_IFADDR, RTMGRP_IPV4_ROUTE, RTMGRP_IPV6_IFADDR, RTMGRP_IPV6_ROUTE, RTMGRP_LINK, rwlock_condvar_create(), rwlock_create(), RWLOCK_TYPE_DEFAULT, library_t::settings, socket, spinlock_create(), streq(), SUCCESS, TRUE, library_t::watcher, and WATCHER_READ.
Referenced by METHOD().
 {
     private_kernel_netlink_net_t *this;
     enumerator_t *enumerator;
     bool register_for_events = TRUE;
     char *exclude;
     INIT(this,
         .public = {
             .interface = {
                 .get_interface = _get_interface_name,
                 .create_address_enumerator = _create_address_enumerator,
                 .get_source_addr = _get_source_addr,
                 .get_nexthop = _get_nexthop,
                 .add_ip = _add_ip,
                 .del_ip = _del_ip,
                 .add_route = _add_route,
                 .del_route = _del_route,
                 .destroy = _destroy,
             },
         },
         .socket = netlink_socket_create(NETLINK_ROUTE, rt_msg_names,
             lib->settings->get_bool(lib->settings,
                 "%s.plugins.kernel-netlink.parallel_route", FALSE, lib->ns)),
         .rt_exclude = linked_list_create(),
         .routes = hashtable_create((hashtable_hash_t)route_entry_hash,
                                    (hashtable_equals_t)route_entry_equals, 16),
         .net_changes = hashtable_create(
                                    (hashtable_hash_t)net_change_hash,
                                    (hashtable_equals_t)net_change_equals, 16),
         .addrs = hashtable_create(
                                 (hashtable_hash_t)addr_map_entry_hash,
                                 (hashtable_equals_t)addr_map_entry_equals, 16),
         .vips = hashtable_create((hashtable_hash_t)addr_map_entry_hash,
                                  (hashtable_equals_t)addr_map_entry_equals, 16),
         .routes_lock = mutex_create(MUTEX_TYPE_DEFAULT),
         .net_changes_lock = mutex_create(MUTEX_TYPE_DEFAULT),
         .ifaces = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .condvar = rwlock_condvar_create(),
         .roam_lock = spinlock_create(),
         .routing_table = lib->settings->get_int(lib->settings,
                         "%s.routing_table", ROUTING_TABLE, lib->ns),
         .routing_table_prio = lib->settings->get_int(lib->settings,
                         "%s.routing_table_prio", ROUTING_TABLE_PRIO, lib->ns),
         .process_route = lib->settings->get_bool(lib->settings,
                         "%s.process_route", TRUE, lib->ns),
         .install_virtual_ip = lib->settings->get_bool(lib->settings,
                         "%s.install_virtual_ip", TRUE, lib->ns),
         .install_virtual_ip_on = lib->settings->get_str(lib->settings,
                         "%s.install_virtual_ip_on", NULL, lib->ns),
         .prefer_temporary_addrs = lib->settings->get_bool(lib->settings,
                         "%s.prefer_temporary_addrs", FALSE, lib->ns),
         .roam_events = lib->settings->get_bool(lib->settings,
                         "%s.plugins.kernel-netlink.roam_events", TRUE, lib->ns),
         .mtu = lib->settings->get_int(lib->settings,
                         "%s.plugins.kernel-netlink.mtu", 0, lib->ns),
         .mss = lib->settings->get_int(lib->settings,
                         "%s.plugins.kernel-netlink.mss", 0, lib->ns),
     );
     timerclear(&this->last_route_reinstall);
     timerclear(&this->next_roam);
     check_kernel_features(this);
     if (streq(lib->ns, "starter"))
     {   /* starter has no threads, so we do not register for kernel events */
         register_for_events = FALSE;
     }
     exclude = lib->settings->get_str(lib->settings,
                                      "%s.ignore_routing_tables", NULL, lib->ns);
     if (exclude)
     {
         char *token;
         uintptr_t table;
         enumerator = enumerator_create_token(exclude, " ", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             errno = 0;
             table = strtoul(token, NULL, 10);
             if (errno == 0)
             {
                 this->rt_exclude->insert_last(this->rt_exclude, (void*)table);
             }
         }
         enumerator->destroy(enumerator);
     }
     if (register_for_events)
     {
         struct sockaddr_nl addr;
         memset(&addr, 0, sizeof(addr));
         addr.nl_family = AF_NETLINK;
         /* create and bind RT socket for events (address/interface/route changes) */
         this->socket_events = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
         if (this->socket_events < 0)
         {
             DBG1(DBG_KNL, "unable to create RT event socket");
             destroy(this);
             return NULL;
         }
         addr.nl_groups = RTMGRP_IPV4_IFADDR | RTMGRP_IPV6_IFADDR |
                          RTMGRP_IPV4_ROUTE | RTMGRP_IPV6_ROUTE | RTMGRP_LINK;
         if (bind(this->socket_events, (struct sockaddr*)&addr, sizeof(addr)))
         {
             DBG1(DBG_KNL, "unable to bind RT event socket");
             destroy(this);
             return NULL;
         }
         lib->watcher->add(lib->watcher, this->socket_events, WATCHER_READ,
                           (watcher_cb_t)receive_events, this);
     }
     if (init_address_list(this) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to get interface list");
         destroy(this);
         return NULL;
     }
     if (this->routing_table)
     {
         if (manage_rule(this, RTM_NEWRULE, AF_INET, this->routing_table,
                         this->routing_table_prio) != SUCCESS)
         {
             DBG1(DBG_KNL, "unable to create IPv4 routing table rule");
         }
         if (manage_rule(this, RTM_NEWRULE, AF_INET6, this->routing_table,
                         this->routing_table_prio) != SUCCESS)
         {
             DBG1(DBG_KNL, "unable to create IPv6 routing table rule");
         }
     }
     return &this->public;
 }