strongSwan: eap_ttls_avp.c File Reference
eap_ttls_avp.c File Reference
#include "eap_ttls_avp.h"
#include <utils/debug.h>
Classes
struct private_eap_ttls_avp_t
Macros
#define AVP_EAP_MESSAGE 79
#define AVP_HEADER_LEN 8
Typedefs
typedef struct
private_eap_ttls_avp_t private_eap_ttls_avp_t
Functions
METHOD (eap_ttls_avp_t, build, void, private_eap_ttls_avp_t *this, bio_writer_t *writer, chunk_t data)
METHOD (eap_ttls_avp_t, process, status_t, private_eap_ttls_avp_t *this, bio_reader_t *reader, chunk_t *data)
METHOD (eap_ttls_avp_t, destroy, void, private_eap_ttls_avp_t *this)
eap_ttls_avp_t * eap_ttls_avp_create (void)
Macro Definition Documentation
#define AVP_EAP_MESSAGE 79
Definition at line 20 of file eap_ttls_avp.c.
Referenced by METHOD().
#define AVP_HEADER_LEN 8
Definition at line 21 of file eap_ttls_avp.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_eap_ttls_avp_t private_eap_ttls_avp_t
Definition at line 23 of file eap_ttls_avp.c.
Function Documentation
METHOD (eap_ttls_avp_t , build , void , private_eap_ttls_avp_t * this, bio_writer_t * writer, chunk_t data)
Definition at line 56 of file eap_ttls_avp.c.
References AVP_EAP_MESSAGE, chunk_create(), chunk_t::len, bio_writer_t::write_data, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     char zero_padding[] = { 0x00, 0x00, 0x00 };
     chunk_t   avp_padding;
     u_int8_t  avp_flags;
     u_int32_t avp_len;
     avp_flags = 0x40;
     avp_len = 8 + data.len;
     avp_padding = chunk_create(zero_padding, (4 - data.len) % 4);
     writer->write_uint32(writer, AVP_EAP_MESSAGE);
     writer->write_uint8(writer, avp_flags);
     writer->write_uint24(writer, avp_len);
     writer->write_data(writer, data);
     writer->write_data(writer, avp_padding);
 }
METHOD (eap_ttls_avp_t , process , status_t , private_eap_ttls_avp_t * this, bio_reader_t * reader, chunk_t * data)
Definition at line 75 of file eap_ttls_avp.c.
References AVP_EAP_MESSAGE, AVP_HEADER_LEN, bio_reader_create(), chunk_alloc, chunk_empty, chunk_free(), DBG1, DBG_IKE, bio_reader_t::destroy, FAILED, FALSE, chunk_t::len, len, memcpy, min, NEED_MORE, process_header(), chunk_t::ptr, bio_reader_t::read_data, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, SUCCESS, and TRUE.
 {
     size_t len;
     chunk_t buf;
     if (this->process_header)
     {
         bio_reader_t *header;
         u_int32_t avp_code;
         u_int8_t  avp_flags;
         u_int32_t avp_len;
         bool success;
         len = min(reader->remaining(reader), AVP_HEADER_LEN - this->inpos);
         if (!reader->read_data(reader, len, &buf))
         {
             return FAILED;
         }
         if (this->input.len == 0)
         {
             /* start of a new AVP header */
             this->input = chunk_alloc(AVP_HEADER_LEN);
             memcpy(this->input.ptr, buf.ptr, len);
             this->inpos = len;
         }
         else
         {
             memcpy(this->input.ptr + this->inpos, buf.ptr, len);
             this->inpos += len;
         }
         if (this->inpos < AVP_HEADER_LEN)
         {
             return NEED_MORE;
         }
         /* parse AVP header */
         header = bio_reader_create(this->input);
         success = header->read_uint32(header, &avp_code) &&
                   header->read_uint8(header, &avp_flags) &&
                   header->read_uint24(header, &avp_len);
         header->destroy(header);
         chunk_free(&this->input);
         this->inpos = 0;
         if (!success)
         {
             DBG1(DBG_IKE, "received invalid AVP header");
             return FAILED;
         }
         if (avp_code != AVP_EAP_MESSAGE)
         {
             DBG1(DBG_IKE, "expected AVP_EAP_MESSAGE but received %u", avp_code);
             return FAILED;
         }
         this->process_header = FALSE;
         this->data_len = avp_len - 8;
         this->input = chunk_alloc(this->data_len + (4 - avp_len) % 4);
     }
     /* process AVP data */
     len = min(reader->remaining(reader), this->input.len - this->inpos);
     if (!reader->read_data(reader, len, &buf))
     {
         return FAILED;
     }
     memcpy(this->input.ptr + this->inpos, buf.ptr, len);
     this->inpos += len;
     if (this->inpos < this->input.len)
     {
         return NEED_MORE;
     }
     *data = this->input;
     data->len = this->data_len;
     /* preparing for next AVP */
     this->input = chunk_empty;
     this->inpos = 0;
     this->process_header = TRUE;
     return SUCCESS;
 }
METHOD (eap_ttls_avp_t , destroy , void , private_eap_ttls_avp_t * this)
Definition at line 160 of file eap_ttls_avp.c.
References chunk_free(), and free().
 {
     chunk_free(&this->input);
     free(this);
 }