strongSwan: lookip_socket.c File Reference
lookip_socket.c File Reference
#include "lookip_socket.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <errno.h>
#include <daemon.h>
#include <threading/thread.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
#include "lookip_msg.h"
Classes
struct private_lookip_socket_t
struct entry_t
struct disconnect_data_t
Typedefs
typedef struct
private_lookip_socket_t private_lookip_socket_t
Functions
static void entry_destroy (entry_t *entry)
static job_requeue_t disconnect_async (disconnect_data_t *data)
static void disconnect (private_lookip_socket_t *this, stream_t *stream)
static bool event_cb (entry_t *entry, bool up, host_t *vip, host_t *other, identification_t *id, char *name, u_int unique_id)
static bool query_cb (stream_t *stream, bool up, host_t *vip, host_t *other, identification_t *id, char *name, u_int unique_id)
static void query (private_lookip_socket_t *this, stream_t *stream, lookip_request_t *req)
static void subscribe (private_lookip_socket_t *this, stream_t *stream, bool up)
static bool subscribed (private_lookip_socket_t *this, stream_t *stream)
static bool on_read (private_lookip_socket_t *this, stream_t *stream)
static bool on_accept (private_lookip_socket_t *this, stream_t *stream)
METHOD (lookip_socket_t, destroy, void, private_lookip_socket_t *this)
lookip_socket_t * lookip_socket_create (lookip_listener_t *listener)
Typedef Documentation
typedef struct private_lookip_socket_t private_lookip_socket_t
Definition at line 33 of file lookip_socket.c.
Function Documentation
static void disconnect (private_lookip_socket_t * this, stream_t * stream) static
Queue async disconnect job
Definition at line 131 of file lookip_socket.c.
References callback_job_create(), data, disconnect_async(), free(), INIT, lib, library_t::processor, and processor_t::queue_job.
Referenced by event_cb(), and on_read().
 {
     disconnect_data_t *data;
     INIT(data,
         .this = this,
         .stream = stream,
     );
     lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create((void*)disconnect_async, data,
                                         free, NULL));
 }
static job_requeue_t disconnect_async (disconnect_data_t * data) static
Disconnect a stream asynchronously, remove connection entry
Definition at line 102 of file lookip_socket.c.
References enumerator_t::destroy, entry_t::down, entry_destroy(), enumerator_t::enumerate, JOB_REQUEUE_NONE, listener, mutex_t::lock, mutex, entry_t::stream, disconnect_data_t::stream, disconnect_data_t::this, mutex_t::unlock, and entry_t::up.
Referenced by disconnect().
 {
     private_lookip_socket_t *this = data->this;
     enumerator_t *enumerator;
     entry_t *entry;
     this->mutex->lock(this->mutex);
     enumerator = this->connected->create_enumerator(this->connected);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->stream == data->stream)
         {
             this->connected->remove_at(this->connected, enumerator);
             if (entry->up || entry->down)
             {
                 this->listener->remove_listener(this->listener, entry);
             }
             entry_destroy(entry);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     return JOB_REQUEUE_NONE;
 }
static void entry_destroy (entry_t * entry) static
Clean up a connection entry
Definition at line 83 of file lookip_socket.c.
References stream_t::destroy, free(), and entry_t::stream.
Referenced by disconnect_async(), and METHOD().
 {
     entry->stream->destroy(entry->stream);
     free(entry);
 }
static bool event_cb (entry_t * entry, bool up, host_t * vip, host_t * other, identification_t * id, char * name, u_int unique_id) static
Callback function for listener up/down events
Definition at line 148 of file lookip_socket.c.
References DBG1, DBG_CFG, disconnect(), entry_t::down, ECONNRESET, FALSE, lookip_response_t::id, lookip_response_t::ip, LOOKIP_NOTIFY_DOWN, LOOKIP_NOTIFY_UP, lookip_response_t::name, snprintf, entry_t::stream, strerror, entry_t::this, TRUE, lookip_response_t::type, lookip_response_t::unique_id, entry_t::up, lookip_response_t::vip, and stream_t::write_all.
Referenced by subscribe().
 {
     lookip_response_t resp = {
         .unique_id = htonl(unique_id),
     };
     if (up)
     {
         if (!entry->up)
         {
             return TRUE;
         }
         resp.type = htonl(LOOKIP_NOTIFY_UP);
     }
     else
     {
         if (!entry->down)
         {
             return TRUE;
         }
         resp.type = htonl(LOOKIP_NOTIFY_DOWN);
     }
     snprintf(resp.vip, sizeof(resp.vip), "%H", vip);
     snprintf(resp.ip, sizeof(resp.ip), "%H", other);
     snprintf(resp.id, sizeof(resp.id), "%Y", id);
     snprintf(resp.name, sizeof(resp.name), "%s", name);
     if (entry->stream->write_all(entry->stream, &resp, sizeof(resp)))
     {
         return TRUE;
     }
     switch (errno)
     {
         case ECONNRESET:
         case EPIPE:
             /* client disconnected, adios */
             break;
         default:
             DBG1(DBG_CFG, "sending lookip event failed: %s", strerror(errno));
             break;
     }
     /* don't unregister, as we return FALSE */
     entry->up = entry->down = FALSE;
     disconnect(entry->this, entry->stream);
     return FALSE;
 }
METHOD (lookip_socket_t , destroy , void , private_lookip_socket_t * this)
Definition at line 398 of file lookip_socket.c.
References mutex_t::destroy, DESTROY_IF, entry_destroy(), free(), and mutex.
 {
     DESTROY_IF(this->service);
     this->connected->destroy_function(this->connected, (void*)entry_destroy);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static bool on_accept (private_lookip_socket_t * this, stream_t * stream) static
Accept client connections, dispatch
Definition at line 380 of file lookip_socket.c.
References INIT, mutex_t::lock, mutex, stream_t::on_read, on_read(), TRUE, and mutex_t::unlock.
Referenced by lookip_socket_create().
 {
     entry_t *entry;
     INIT(entry,
         .stream = stream,
         .this = this,
     );
     this->mutex->lock(this->mutex);
     this->connected->insert_last(this->connected, entry);
     this->mutex->unlock(this->mutex);
     stream->on_read(stream, (void*)on_read, this);
     return TRUE;
 }
static bool on_read (private_lookip_socket_t * this, stream_t * stream) static
Dispatch from a socket, on-read callback
Definition at line 332 of file lookip_socket.c.
References DBG1, DBG_CFG, disconnect(), ECONNRESET, FALSE, LOOKIP_DUMP, LOOKIP_END, LOOKIP_LOOKUP, LOOKIP_REGISTER_DOWN, LOOKIP_REGISTER_UP, query(), stream_t::read_all, req(), strerror, subscribe(), subscribed(), TRUE, and lookip_request_t::type.
Referenced by CALLBACK(), on_accept(), vici_connect(), vici_register(), and vici_submit().
 {
     lookip_request_t req;
     if (stream->read_all(stream, &req, sizeof(req)))
     {
         switch (ntohl(req.type))
         {
             case LOOKIP_LOOKUP:
                 query(this, stream, &req);
                 return TRUE;
             case LOOKIP_DUMP:
                 query(this, stream, NULL);
                 return TRUE;
             case LOOKIP_REGISTER_UP:
                 subscribe(this, stream, TRUE);
                 return TRUE;
             case LOOKIP_REGISTER_DOWN:
                 subscribe(this, stream, FALSE);
                 return TRUE;
             case LOOKIP_END:
                 break;
             default:
                 DBG1(DBG_CFG, "received unknown lookip command");
                 break;
         }
     }
     else
     {
         if (errno != ECONNRESET)
         {
             DBG1(DBG_CFG, "receiving lookip request failed: %s",
                  strerror(errno));
         }
         disconnect(this, stream);
         return FALSE;
     }
     if (subscribed(this, stream))
     {
         return TRUE;
     }
     disconnect(this, stream);
     return FALSE;
 }
static void query (private_lookip_socket_t * this, stream_t * stream, lookip_request_t * req) static
Perform a lookup
Definition at line 233 of file lookip_socket.c.
References DBG1, DBG_CFG, host_t::destroy, host_create_from_string(), listener, LOOKIP_NOT_FOUND, query_cb(), snprintf, strerror, lookip_response_t::type, lookip_request_t::vip, lookip_response_t::vip, vip, and stream_t::write_all.
Referenced by create_lease_query(), del(), del_attr(), edit(), leases(), list(), login(), METHOD(), on_read(), register_vici(), resize(), and resolve_hosts().
 {
     host_t *vip = NULL;
     int matches = 0;
     if (req)
     {   /* lookup */
         req->vip[sizeof(req->vip) - 1] = 0;
         vip = host_create_from_string(req->vip, 0);
         if (vip)
         {
             matches = this->listener->lookup(this->listener, vip,
                                              (void*)query_cb, stream);
             vip->destroy(vip);
         }
         if (matches == 0)
         {
             lookip_response_t resp = {
                 .type = htonl(LOOKIP_NOT_FOUND),
             };
             snprintf(resp.vip, sizeof(resp.vip), "%s", req->vip);
             if (!stream->write_all(stream, &resp, sizeof(resp)))
             {
                 DBG1(DBG_CFG, "sending lookip not-found failed: %s",
                      strerror(errno));
             }
         }
     }
     else
     {   /* dump */
         this->listener->lookup(this->listener, NULL,
                                (void*)query_cb, stream);
     }
 }
static bool query_cb (stream_t * stream, bool up, host_t * vip, host_t * other, identification_t * id, char * name, u_int unique_id) static
Callback function for queries
Definition at line 200 of file lookip_socket.c.
References DBG1, DBG_CFG, ECONNRESET, FALSE, lookip_response_t::id, lookip_response_t::ip, LOOKIP_ENTRY, lookip_response_t::name, snprintf, strerror, TRUE, lookip_response_t::type, lookip_response_t::vip, and stream_t::write_all.
Referenced by query().
 {
     lookip_response_t resp = {
         .type = htonl(LOOKIP_ENTRY),
         .unique_id = htonl(unique_id),
     };
     snprintf(resp.vip, sizeof(resp.vip), "%H", vip);
     snprintf(resp.ip, sizeof(resp.ip), "%H", other);
     snprintf(resp.id, sizeof(resp.id), "%Y", id);
     snprintf(resp.name, sizeof(resp.name), "%s", name);
     if (stream->write_all(stream, &resp, sizeof(resp)))
     {
         return TRUE;
     }
     switch (errno)
     {
         case ECONNRESET:
         case EPIPE:
             /* client disconnected, adios */
             break;
         default:
             DBG1(DBG_CFG, "sending lookip response failed: %s", strerror(errno));
             break;
     }
     return FALSE;
 }
static void subscribe (private_lookip_socket_t * this, stream_t * stream, bool up) static
Subscribe to virtual IP events
Definition at line 274 of file lookip_socket.c.
References enumerator_t::destroy, entry_t::down, enumerator_t::enumerate, event_cb(), listener, mutex_t::lock, mutex, entry_t::stream, TRUE, mutex_t::unlock, and entry_t::up.
Referenced by on_read().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     this->mutex->lock(this->mutex);
     enumerator = this->connected->create_enumerator(this->connected);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->stream == stream)
         {
             if (!entry->up && !entry->down)
             {   /* newly registered */
                 this->listener->add_listener(this->listener,
                                              (void*)event_cb, entry);
             }
             if (up)
             {
                 entry->up = TRUE;
             }
             else
             {
                 entry->down = TRUE;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
static bool subscribed (private_lookip_socket_t * this, stream_t * stream) static
Check if a client is subscribed for notifications
Definition at line 307 of file lookip_socket.c.
References enumerator_t::destroy, entry_t::down, enumerator_t::enumerate, FALSE, mutex_t::lock, mutex, entry_t::stream, mutex_t::unlock, and entry_t::up.
Referenced by on_read().
 {
     enumerator_t *enumerator;
     bool subscribed = FALSE;
     entry_t *entry;
     this->mutex->lock(this->mutex);
     enumerator = this->connected->create_enumerator(this->connected);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->stream == stream)
         {
             subscribed = entry->up || entry->down;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     return subscribed;
 }