strongSwan: socket_default_socket
socket_default_socket
socket_default
Classes
struct socket_default_socket_t
Typedefs
typedef struct
socket_default_socket_t socket_default_socket_t
Functions
socket_default_socket_t * socket_default_socket_create ()
Detailed Description
Typedef Documentation
typedef struct socket_default_socket_t socket_default_socket_t
Definition at line 24 of file socket_default_socket.h.
Function Documentation
socket_default_socket_t* socket_default_socket_create ()
Create a socket_default_socket instance.
Definition at line 813 of file socket_default_socket.c.
References CAP_NET_BIND_SERVICE, library_t::caps, CHARON_NATT_PORT, CHARON_UDP_PORT, capabilities_t::check, DBG1, DBG_NET, destroy(), settings_t::get_bool, settings_t::get_int, INIT, lib, library_t::ns, open_socketpair(), PACKET_MAX_DEFAULT, library_t::settings, and TRUE.
Referenced by METHOD().
 {
     private_socket_default_socket_t *this;
     INIT(this,
         .public = {
             .socket = {
                 .send = _sender,
                 .receive = _receiver,
                 .get_port = _get_port,
                 .supported_families = _supported_families,
                 .destroy = _destroy,
             },
         },
         .port = lib->settings->get_int(lib->settings,
                             "%s.port", CHARON_UDP_PORT, lib->ns),
         .natt = lib->settings->get_int(lib->settings,
                             "%s.port_nat_t", CHARON_NATT_PORT, lib->ns),
         .max_packet = lib->settings->get_int(lib->settings,
                             "%s.max_packet", PACKET_MAX_DEFAULT, lib->ns),
         .set_source = lib->settings->get_bool(lib->settings,
                             "%s.plugins.socket-default.set_source", TRUE,
                             lib->ns),
     );
     if (this->port && this->port == this->natt)
     {
         DBG1(DBG_NET, "IKE ports can't be equal, will allocate NAT-T "
              "port randomly");
         this->natt = 0;
     }
     if ((this->port && this->port < 1024) || (this->natt && this->natt < 1024))
     {
         if (!lib->caps->check(lib->caps, CAP_NET_BIND_SERVICE))
         {
             /* required to bind ports < 1024 */
             DBG1(DBG_NET, "socket-default plugin requires CAP_NET_BIND_SERVICE "
                  "capability");
             destroy(this);
             return NULL;
         }
     }
     /* we allocate IPv6 sockets first as that will reserve randomly allocated
      * ports also for IPv4. On OS X, we have to do it the other way round
      * for the same effect. */
 #ifdef __APPLE__
     open_socketpair(this, AF_INET, &this->ipv4, &this->ipv4_natt, "IPv4");
     open_socketpair(this, AF_INET6, &this->ipv6, &this->ipv6_natt, "IPv6");
 #else /* !__APPLE__ */
     open_socketpair(this, AF_INET6, &this->ipv6, &this->ipv6_natt, "IPv6");
     open_socketpair(this, AF_INET, &this->ipv4, &this->ipv4_natt, "IPv4");
 #endif /* __APPLE__ */
     if (this->ipv4 == -1 && this->ipv6 == -1)
     {
         DBG1(DBG_NET, "could not create any sockets");
         destroy(this);
         return NULL;
     }
     return &this->public;
 }