strongSwan: lookip_socket
lookip_socket
lookip
Classes
struct lookip_socket_t
Typedefs
typedef struct lookip_socket_t lookip_socket_t
Functions
lookip_socket_t * lookip_socket_create (lookip_listener_t *listener)
Detailed Description
Typedef Documentation
typedef struct lookip_socket_t lookip_socket_t
Definition at line 26 of file lookip_socket.h.
Function Documentation
lookip_socket_t* lookip_socket_create (lookip_listener_t * listener)
Create a lookip_socket instance.
See header
Definition at line 410 of file lookip_socket.c.
References stream_manager_t::create_service, DBG1, DBG_CFG, destroy(), settings_t::get_str, INIT, JOB_PRIO_CRITICAL, lib, linked_list_create(), listener, LOOKIP_SOCKET, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, on_accept(), library_t::settings, library_t::streams, and uri.
Referenced by lookip_plugin_create().
 {
     private_lookip_socket_t *this;
     char *uri;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
         .listener = listener,
         .connected = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     uri = lib->settings->get_str(lib->settings,
                             "%s.plugins.lookip.socket", "unix://" LOOKIP_SOCKET,
                             lib->ns);
     this->service = lib->streams->create_service(lib->streams, uri, 10);
     if (!this->service)
     {
         DBG1(DBG_CFG, "creating lookip socket failed");
         destroy(this);
         return NULL;
     }
     this->service->on_accept(this->service, (stream_service_cb_t)on_accept,
                              this, JOB_PRIO_CRITICAL, 1);
     return &this->public;
 }