strongSwan: ipsec_processor_t Struct Reference
ipsec_processor_t Struct Reference
ipsec_processor
#include "ipsec_processor.h"
Public Attributes
void(* queue_inbound)(ipsec_processor_t *this, esp_packet_t *packet)
void(* queue_outbound)(ipsec_processor_t *this, ip_packet_t *packet)
void(* register_inbound)(ipsec_processor_t *this, ipsec_inbound_cb_t cb, void *data)
void(* unregister_inbound)(ipsec_processor_t *this, ipsec_inbound_cb_t cb)
void(* register_outbound)(ipsec_processor_t *this, ipsec_outbound_cb_t cb, void *data)
void(* unregister_outbound)(ipsec_processor_t *this, ipsec_outbound_cb_t cb)
void(* destroy)(ipsec_processor_t *this)
Detailed Description
IPsec processor
Definition at line 51 of file ipsec_processor.h.
Member Data Documentation
void(* ipsec_processor_t::destroy)(ipsec_processor_t *this)
Destroy an ipsec_processor_t.
Definition at line 104 of file ipsec_processor.h.
void(* ipsec_processor_t::queue_inbound)(ipsec_processor_t *this, esp_packet_t *packet)
Queue an inbound ESP packet for processing.
Parameters
packet the ESP packet to process
Definition at line 58 of file ipsec_processor.h.
Referenced by receiver_esp_cb().
void(* ipsec_processor_t::queue_outbound)(ipsec_processor_t *this, ip_packet_t *packet)
Queue an outbound plaintext IP packet for processing.
Parameters
packet the plaintext IP packet
Definition at line 65 of file ipsec_processor.h.
Referenced by process_plain().
void(* ipsec_processor_t::register_inbound)(ipsec_processor_t *this, ipsec_inbound_cb_t cb, void *data)
Register the callback used to deliver inbound plaintext packets.
Parameters
cb the inbound callback function
data optional data provided to callback
Definition at line 73 of file ipsec_processor.h.
Referenced by kernel_libipsec_router_create().
void(* ipsec_processor_t::register_outbound)(ipsec_processor_t *this, ipsec_outbound_cb_t cb, void *data)
Register the callback used to send outbound ESP packets.
Parameters
cb the outbound callback function
data optional data provided to callback
Definition at line 90 of file ipsec_processor.h.
Referenced by kernel_libipsec_router_create().
void(* ipsec_processor_t::unregister_inbound)(ipsec_processor_t *this, ipsec_inbound_cb_t cb)
Unregister a previously registered inbound callback.
Parameters
cb previously registered callback function
Definition at line 81 of file ipsec_processor.h.
Referenced by METHOD().
void(* ipsec_processor_t::unregister_outbound)(ipsec_processor_t *this, ipsec_outbound_cb_t cb)
Unregister a previously registered outbound callback.
Parameters
cb previously registered callback function
Definition at line 98 of file ipsec_processor.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ipsec_processor.h