strongSwan: pts_pcr.c File Reference
pts_pcr.c File Reference
#include "pts_pcr.h"
#include <utils/debug.h>
#include <stdarg.h>
Classes
struct private_pts_pcr_t
struct pcr_enumerator_t
Typedefs
typedef struct private_pts_pcr_t private_pts_pcr_t
Functions
METHOD (pts_pcr_t, get_count, u_int32_t, private_pts_pcr_t *this)
METHOD (pts_pcr_t, select_pcr, bool, private_pts_pcr_t *this, u_int32_t pcr)
METHOD (pts_pcr_t, get_selection_size, size_t, private_pts_pcr_t *this)
static bool pcr_enumerator_enumerate (pcr_enumerator_t *this,...)
METHOD (pts_pcr_t, create_enumerator, enumerator_t *, private_pts_pcr_t *this)
METHOD (pts_pcr_t, get, chunk_t, private_pts_pcr_t *this, u_int32_t pcr)
METHOD (pts_pcr_t, set, bool, private_pts_pcr_t *this, u_int32_t pcr, chunk_t value)
METHOD (pts_pcr_t, extend, chunk_t, private_pts_pcr_t *this, u_int32_t pcr, chunk_t measurement)
METHOD (pts_pcr_t, get_composite, chunk_t, private_pts_pcr_t *this)
METHOD (pts_pcr_t, destroy, void, private_pts_pcr_t *this)
pts_pcr_t * pts_pcr_create (void)
Typedef Documentation
typedef struct private_pts_pcr_t private_pts_pcr_t
Definition at line 22 of file pts_pcr.c.
Function Documentation
METHOD (pts_pcr_t , get_count , u_int32_t , private_pts_pcr_t * this)
Definition at line 62 of file pts_pcr.c.
 {
     return this->pcr_count;
 }
METHOD (pts_pcr_t , select_pcr , bool , private_pts_pcr_t * this, u_int32_t pcr)
Definition at line 68 of file pts_pcr.c.
References DBG1, DBG_PTS, FALSE, max, PTS_PCR_MAX_NUM, and TRUE.
 {
     u_int32_t i, f;
     if (pcr >= PTS_PCR_MAX_NUM)
     {
         DBG1(DBG_PTS, "PCR %2u: number is larger than maximum of %u",
                        pcr, PTS_PCR_MAX_NUM-1);
         return FALSE;
     }
     /* Determine PCR selection flag */
     i = pcr / 8;
     f = 1 << (pcr - 8*i);
     /* Has this PCR already been selected? */
     if (!(this->pcr_select[i] & f))
     {
         this->pcr_select[i] |= f;
         this->pcr_max = max(this->pcr_max, pcr);
         this->pcr_count++;
     }
     return TRUE;
 }
METHOD (pts_pcr_t , get_selection_size , size_t , private_pts_pcr_t * this)
A TPM v1.2 has 24 PCR Registers so the bitmask field length used by TrouSerS is at least 3 bytes
Definition at line 94 of file pts_pcr.c.
References PTS_PCR_MAX_NUM.
 {
     return PTS_PCR_MAX_NUM / 8;
 }
METHOD (pts_pcr_t , create_enumerator , enumerator_t * , private_pts_pcr_t * this)
Definition at line 144 of file pts_pcr.c.
References destroy(), free(), INIT, and pcr_enumerator_enumerate().
 {
     pcr_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)pcr_enumerator_enumerate,
             .destroy = (void*)free,
         },
         .pcrs = this,
     );
     return (enumerator_t*)enumerator;
 }
METHOD (pts_pcr_t , get , chunk_t , private_pts_pcr_t * this, u_int32_t pcr)
Definition at line 160 of file pts_pcr.c.
References chunk_empty, and PTS_PCR_MAX_NUM.
 {
     return (pcr < PTS_PCR_MAX_NUM) ? this->pcrs[pcr] : chunk_empty;
 }
METHOD (pts_pcr_t , set , bool , private_pts_pcr_t * this, u_int32_t pcr, chunk_t value)
Definition at line 166 of file pts_pcr.c.
References DBG1, DBG_PTS, FALSE, chunk_t::len, memcpy, chunk_t::ptr, PTS_PCR_LEN, and TRUE.
 {
     if (value.len != PTS_PCR_LEN)
     {
         DBG1(DBG_PTS, "PCR %2u: value does not fit", pcr);
         return FALSE;
     }
     if (select_pcr(this, pcr))
     {
         memcpy(this->pcrs[pcr].ptr, value.ptr, PTS_PCR_LEN);
         return TRUE;
     }
     return FALSE;
 }
METHOD (pts_pcr_t , extend , chunk_t , private_pts_pcr_t * this, u_int32_t pcr, chunk_t measurement)
Definition at line 182 of file pts_pcr.c.
References chunk_empty, DBG1, DBG_PTS, hasher, chunk_t::len, and PTS_PCR_LEN.
 {
     if (measurement.len != PTS_PCR_LEN)
     {
         DBG1(DBG_PTS, "PCR %2u: measurement does not fit", pcr);
         return chunk_empty;
     }
     if (!select_pcr(this, pcr))
     {
         return chunk_empty;
     }
     if (!this->hasher->get_hash(this->hasher, this->pcrs[pcr] , NULL) ||
         !this->hasher->get_hash(this->hasher, measurement, this->pcrs[pcr].ptr))
     {
         DBG1(DBG_PTS, "PCR %2u: not extended due to hasher problem", pcr);
         return chunk_empty;
     }
     return this->pcrs[pcr];
 }
METHOD (pts_pcr_t , get_composite , chunk_t , private_pts_pcr_t * this)
Definition at line 203 of file pts_pcr.c.
References chunk_alloc, create_enumerator(), DBG3, DBG_PTS, enumerator_t::destroy, enumerator_t::enumerate, htoun16(), htoun32(), memcpy, chunk_t::ptr, and PTS_PCR_LEN.
 {
     chunk_t composite;
     enumerator_t *enumerator;
     u_int16_t selection_size;
     u_int32_t pcr_field_size, pcr;
     u_char *pos;
     selection_size = get_selection_size(this);
     pcr_field_size = this->pcr_count * PTS_PCR_LEN;
     composite = chunk_alloc(2 + selection_size + 4 + pcr_field_size);
     pos = composite.ptr;
     htoun16(pos, selection_size);
     pos += 2;
     memcpy(pos, this->pcr_select, selection_size);
     pos += selection_size;
     htoun32(pos, pcr_field_size);
     pos += 4;
     enumerator = create_enumerator(this);
     while (enumerator->enumerate(enumerator, &pcr))
     {
         memcpy(pos, this->pcrs[pcr].ptr, PTS_PCR_LEN);
         pos += PTS_PCR_LEN;
     }
     enumerator->destroy(enumerator);
     DBG3(DBG_PTS, "constructed PCR Composite: %B", &composite);
     return composite;
 }
METHOD (pts_pcr_t , destroy , void , private_pts_pcr_t * this)
Definition at line 236 of file pts_pcr.c.
References free(), hasher, and PTS_PCR_MAX_NUM.
 {
     u_int32_t i;
     for (i = 0; i < PTS_PCR_MAX_NUM; i++)
     {
         free(this->pcrs[i].ptr);
     }
     this->hasher->destroy(this->hasher);
     free(this);
 }
static bool pcr_enumerator_enumerate (pcr_enumerator_t * this, ...) static
Implementation of enumerator.enumerate
Definition at line 117 of file pts_pcr.c.
References FALSE, and TRUE.
Referenced by METHOD().
 {
     u_int32_t *pcr, i, f;
     va_list args;
     va_start(args, this);
     pcr = va_arg(args, u_int32_t*);
     va_end(args);
     while (this->pcr <= this->pcrs->pcr_max)
     {
         /* Determine PCR selection flag */
         i = this->pcr / 8;
         f = 1 << (this->pcr - 8*i);
         /* Assign current PCR to output argument and increase */
         *pcr = this->pcr++;
         /* return if PCR is selected */
         if (this->pcrs->pcr_select[i] & f)
         {
             return TRUE;
         }
     }
     return FALSE;
 }