strongSwan: vici_config.c File Reference
vici_config.c File Reference
#include "vici_config.h"
#include "vici_builder.h"
#include <daemon.h>
#include <threading/rwlock.h>
#include <collections/array.h>
#include <collections/linked_list.h>
#include <stdio.h>
Classes
struct private_vici_config_t
struct parse_rule_t
struct request_data_t
struct peer_data_t
struct child_data_t
struct auth_data_t
struct enum_map_t
Macros
#define _GNU_SOURCE
#define LFT_UNDEFINED (~(u_int64_t)0)
#define LFT_DEFAULT_IKE_REKEY (4 * 60 * 60)
#define LFT_DEFAULT_CHILD_REKEY (1 * 60 * 60)
#define REPLAY_UNDEFINED (~(u_int32_t)0)
Typedefs
typedef struct
private_vici_config_t private_vici_config_t
Functions
METHOD (backend_t, create_peer_cfg_enumerator, enumerator_t *, private_vici_config_t *this, identification_t *me, identification_t *other)
static bool ike_filter (void *data, peer_cfg_t **in, ike_cfg_t **out)
METHOD (backend_t, create_ike_cfg_enumerator, enumerator_t *, private_vici_config_t *this, host_t *me, host_t *other)
METHOD (backend_t, get_peer_cfg_by_name, peer_cfg_t *, private_vici_config_t *this, char *name)
static vici_message_t * create_reply (char *fmt,...)
static bool parse_rules (parse_rule_t *rules, int count, char *name, chunk_t value, vici_message_t **reply)
static void log_auth (auth_cfg_t *auth)
static void log_peer_data (peer_data_t *data)
static void free_peer_data (peer_data_t *data)
static void log_child_data (child_data_t *data, char *name)
static void free_child_data (child_data_t *data)
static bool parse_proposal (linked_list_t *list, protocol_id_t proto, chunk_t v)
CALLBACK (parse_ike_proposal, bool, linked_list_t *out, chunk_t v)
CALLBACK (parse_esp_proposal, bool, linked_list_t *out, chunk_t v)
CALLBACK (parse_ah_proposal, bool, linked_list_t *out, chunk_t v)
CALLBACK (parse_ts, bool, linked_list_t *out, chunk_t v)
CALLBACK (parse_string, bool, char **out, chunk_t v)
static bool parse_map (enum_map_t *map, int count, int *out, chunk_t v)
CALLBACK (parse_bool, bool, bool *out, chunk_t v)
CALLBACK (parse_mode, bool, ipsec_mode_t *out, chunk_t v)
CALLBACK (parse_action, bool, action_t *out, chunk_t v)
CALLBACK (parse_uint32, bool, u_int32_t *out, chunk_t v)
CALLBACK (parse_uint64, bool, u_int64_t *out, chunk_t v)
CALLBACK (parse_time, bool, u_int64_t *out, chunk_t v)
CALLBACK (parse_bytes, bool, u_int64_t *out, chunk_t v)
CALLBACK (parse_mark, bool, mark_t *out, chunk_t v)
CALLBACK (parse_tfc, bool, u_int32_t *out, chunk_t v)
CALLBACK (parse_auth, bool, auth_cfg_t *cfg, chunk_t v)
static bool parse_id (auth_cfg_t *cfg, auth_rule_t rule, chunk_t v)
CALLBACK (parse_ike_id, bool, auth_cfg_t *cfg, chunk_t v)
CALLBACK (parse_aaa_id, bool, auth_cfg_t *cfg, chunk_t v)
CALLBACK (parse_eap_id, bool, auth_cfg_t *cfg, chunk_t v)
CALLBACK (parse_xauth_id, bool, auth_cfg_t *cfg, chunk_t v)
CALLBACK (parse_group, bool, auth_cfg_t *cfg, chunk_t v)
static bool parse_cert (auth_data_t *auth, auth_rule_t rule, chunk_t v)
CALLBACK (parse_certs, bool, auth_data_t *auth, chunk_t v)
CALLBACK (parse_cacerts, bool, auth_data_t *auth, chunk_t v)
CALLBACK (parse_revocation, bool, auth_cfg_t *cfg, chunk_t v)
CALLBACK (parse_stringlist, bool, char **out, chunk_t v)
CALLBACK (parse_frag, bool, fragmentation_t *out, chunk_t v)
CALLBACK (parse_send_cert, bool, cert_policy_t *out, chunk_t v)
CALLBACK (parse_unique, bool, unique_policy_t *out, chunk_t v)
CALLBACK (parse_hosts, bool, linked_list_t *list, chunk_t v)
CALLBACK (child_li, bool, child_data_t *child, vici_message_t *message, char *name, chunk_t value)
CALLBACK (child_kv, bool, child_data_t *child, vici_message_t *message, char *name, chunk_t value)
CALLBACK (auth_li, bool, auth_data_t *auth, vici_message_t *message, char *name, chunk_t value)
CALLBACK (auth_kv, bool, auth_data_t *auth, vici_message_t *message, char *name, chunk_t value)
CALLBACK (peer_li, bool, peer_data_t *peer, vici_message_t *message, char *name, chunk_t value)
CALLBACK (peer_kv, bool, peer_data_t *peer, vici_message_t *message, char *name, chunk_t value)
CALLBACK (children_sn, bool, peer_data_t *peer, vici_message_t *message, vici_parse_context_t *ctx, char *name)
CALLBACK (peer_sn, bool, peer_data_t *peer, vici_message_t *message, vici_parse_context_t *ctx, char *name)
static u_int32_t find_reqid (child_cfg_t *cfg)
static void run_start_action (private_vici_config_t *this, peer_cfg_t *peer_cfg, child_cfg_t *child_cfg)
static void clear_start_action (private_vici_config_t *this, child_cfg_t *child_cfg)
static void run_start_actions (private_vici_config_t *this, peer_cfg_t *peer_cfg)
static void clear_start_actions (private_vici_config_t *this, peer_cfg_t *peer_cfg)
static void replace_children (private_vici_config_t *this, peer_cfg_t *from, peer_cfg_t *to)
static void merge_config (private_vici_config_t *this, peer_cfg_t *peer_cfg)
CALLBACK (config_sn, bool, request_data_t *request, vici_message_t *message, vici_parse_context_t *ctx, char *name)
CALLBACK (load_conn, vici_message_t *, private_vici_config_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (unload_conn, vici_message_t *, private_vici_config_t *this, char *name, u_int id, vici_message_t *message)
CALLBACK (get_conns, vici_message_t *, private_vici_config_t *this, char *name, u_int id, vici_message_t *message)
static void manage_command (private_vici_config_t *this, char *name, vici_command_cb_t cb, bool reg)
static void manage_commands (private_vici_config_t *this, bool reg)
METHOD (vici_config_t, destroy, void, private_vici_config_t *this)
vici_config_t * vici_config_create (vici_dispatcher_t *dispatcher, vici_authority_t *authority)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 41 of file vici_config.c.
#define LFT_DEFAULT_CHILD_REKEY (1 * 60 * 60)
Default CHILD rekey time
Definition at line 66 of file vici_config.c.
Referenced by CALLBACK().
#define LFT_DEFAULT_IKE_REKEY (4 * 60 * 60)
Default IKE rekey time
Definition at line 61 of file vici_config.c.
Referenced by CALLBACK().
#define LFT_UNDEFINED (~(u_int64_t)0)
Magic value for an undefined lifetime
Definition at line 56 of file vici_config.c.
Referenced by CALLBACK().
#define REPLAY_UNDEFINED (~(u_int32_t)0)
Undefined replay window
Definition at line 71 of file vici_config.c.
Referenced by CALLBACK(), and log_child_data().
Typedef Documentation
typedef struct private_vici_config_t private_vici_config_t
Definition at line 73 of file vici_config.c.
Function Documentation
CALLBACK (parse_ike_proposal , bool , linked_list_t * out, chunk_t v)
Parse IKE proposal
Definition at line 509 of file vici_config.c.
References parse_proposal(), and PROTO_IKE.
 {
     return parse_proposal(out, PROTO_IKE, v);
 }
CALLBACK (parse_esp_proposal , bool , linked_list_t * out, chunk_t v)
Parse ESP proposal
Definition at line 518 of file vici_config.c.
References parse_proposal(), and PROTO_ESP.
 {
     return parse_proposal(out, PROTO_ESP, v);
 }
CALLBACK (parse_ah_proposal , bool , linked_list_t * out, chunk_t v)
Parse AH proposal
Definition at line 527 of file vici_config.c.
References parse_proposal(), and PROTO_AH.
 {
     return parse_proposal(out, PROTO_AH, v);
 }
CALLBACK (parse_ts , bool , linked_list_t * out, chunk_t v)
Parse a traffic selector
Definition at line 536 of file vici_config.c.
References end, FALSE, from, linked_list_t::insert_last, port, proto, sep, streq(), to, traffic_selector_create_dynamic(), traffic_selector_create_from_cidr(), TRUE, and vici_stringify().
 {
     char buf[128], *protoport, *sep, *port = "", *end;
     traffic_selector_t *ts;
     struct protoent *protoent;
     struct servent *svc;
     long int p;
     u_int16_t from = 0, to = 0xffff;
     u_int8_t proto = 0;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     protoport = strchr(buf, '[');
     if (protoport)
     {
         *(protoport++) = '\0';
         sep = strrchr(protoport, ']');
         if (!sep)
         {
             return FALSE;
         }
         *sep = '\0';
         sep = strchr(protoport, '/');
         if (sep)
         {   /* protocol/port */
             *sep = '\0';
             port = sep + 1;
         }
         if (streq(protoport, "any"))
         {
             proto = 0;
         }
         else
         {
             protoent = getprotobyname(protoport);
             if (protoent)
             {
                 proto = protoent->p_proto;
             }
             else
             {
                 p = strtol(protoport, &end, 0);
                 if ((*protoport && *end) || p < 0 || p > 0xff)
                 {
                     return FALSE;
                 }
                 proto = (u_int8_t)p;
             }
         }
         if (streq(port, "opaque"))
         {
             from = 0xffff;
             to = 0;
         }
         else if (*port && !streq(port, "any"))
         {
             svc = getservbyname(port, NULL);
             if (svc)
             {
                 from = to = ntohs(svc->s_port);
             }
             else
             {
                 p = strtol(port, &end, 0);
                 if (p < 0 || p > 0xffff)
                 {
                     return FALSE;
                 }
                 from = p;
                 if (*end == '-')
                 {
                     port = end + 1;
                     p = strtol(port, &end, 0);
                     if (p < 0 || p > 0xffff)
                     {
                         return FALSE;
                     }
                 }
                 to = p;
                 if (*end)
                 {
                     return FALSE;
                 }
             }
         }
     }
     if (streq(buf, "dynamic"))
     {
         ts = traffic_selector_create_dynamic(proto, from, to);
     }
     else
     {
         ts = traffic_selector_create_from_cidr(buf, proto, from, to);
     }
     if (!ts)
     {
         return FALSE;
     }
     out->insert_last(out, ts);
     return TRUE;
 }
CALLBACK (parse_string , bool , char ** out, chunk_t v)
Parse a string
Definition at line 648 of file vici_config.c.
References asprintf(), chunk_printable(), FALSE, free(), chunk_t::len, chunk_t::ptr, and TRUE.
 {
     if (!chunk_printable(v, NULL, ' '))
     {
         return FALSE;
     }
     free(*out);
     *out = NULL;
     if (asprintf(out, "%.*s", (int)v.len, v.ptr) == -1)
     {
         return FALSE;
     }
     return TRUE;
 }
CALLBACK (parse_bool , bool , bool * out, chunk_t v)
Parse a boolean
Definition at line 698 of file vici_config.c.
References countof, FALSE, parse_map(), and TRUE.
 {
     enum_map_t map[] = {
         { "yes",        TRUE    },
         { "true",       TRUE    },
         { "enabled",    TRUE    },
         { "1",          TRUE    },
         { "no",         FALSE   },
         { "false",      FALSE   },
         { "disabled",   FALSE   },
         { "0",          FALSE   },
     };
     int d;
     if (parse_map(map, countof(map), &d, v))
     {
         *out = d;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_mode , bool , ipsec_mode_t * out, chunk_t v)
Parse a ipsec_mode_t
Definition at line 724 of file vici_config.c.
References countof, FALSE, MODE_BEET, MODE_DROP, MODE_PASS, MODE_TRANSPORT, MODE_TUNNEL, parse_map(), and TRUE.
 {
     enum_map_t map[] = {
         { "tunnel",     MODE_TUNNEL     },
         { "transport",  MODE_TRANSPORT  },
         { "beet",       MODE_BEET       },
         { "drop",       MODE_DROP       },
         { "pass",       MODE_PASS       },
     };
     int d;
     if (parse_map(map, countof(map), &d, v))
     {
         *out = d;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_action , bool , action_t * out, chunk_t v)
Parse an action_t
Definition at line 747 of file vici_config.c.
References ACTION_NONE, ACTION_RESTART, ACTION_ROUTE, countof, FALSE, parse_map(), and TRUE.
 {
     enum_map_t map[] = {
         { "start",      ACTION_RESTART  },
         { "restart",    ACTION_RESTART  },
         { "route",      ACTION_ROUTE    },
         { "trap",       ACTION_ROUTE    },
         { "none",       ACTION_NONE     },
         { "clear",      ACTION_NONE     },
     };
     int d;
     if (parse_map(map, countof(map), &d, v))
     {
         *out = d;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_uint32 , bool , u_int32_t * out, chunk_t v)
Parse a u_int32_t
Definition at line 771 of file vici_config.c.
References end, FALSE, TRUE, and vici_stringify().
 {
     char buf[16], *end;
     u_long l;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     l = strtoul(buf, &end, 0);
     if (*end == 0)
     {
         *out = l;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_uint64 , bool , u_int64_t * out, chunk_t v)
Parse a u_int64_t
Definition at line 793 of file vici_config.c.
References end, FALSE, TRUE, and vici_stringify().
 {
     char buf[16], *end;
     unsigned long long l;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     l = strtoull(buf, &end, 0);
     if (*end == 0)
     {
         *out = l;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_time , bool , u_int64_t * out, chunk_t v)
Parse a relative time
Definition at line 815 of file vici_config.c.
References end, FALSE, TRUE, and vici_stringify().
 {
     char buf[16], *end;
     u_long l;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     l = strtoul(buf, &end, 0);
     while (*end == ' ')
     {
         end++;
     }
     switch (*end)
     {
         case 'd':
         case 'D':
             l *= 24;
             /* fall */
         case 'h':
         case 'H':
             l *= 60;
             /* fall */
         case 'm':
         case 'M':
             l *= 60;
             /* fall */
         case 's':
         case 'S':
             end++;
             break;
         case '\0':
             break;
         default:
             return FALSE;
     }
     if (*end)
     {
         return FALSE;
     }
     *out = l;
     return TRUE;
 }
CALLBACK (parse_bytes , bool , u_int64_t * out, chunk_t v)
Parse byte volume
Definition at line 865 of file vici_config.c.
References end, FALSE, TRUE, and vici_stringify().
 {
     char buf[16], *end;
     unsigned long long l;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     l = strtoull(buf, &end, 0);
     while (*end == ' ')
     {
         end++;
     }
     switch (*end)
     {
         case 'g':
         case 'G':
             l *= 1024;
             /* fall */
         case 'm':
         case 'M':
             l *= 1024;
             /* fall */
         case 'k':
         case 'K':
             l *= 1024;
             end++;
             break;
         case '\0':
             break;
         default:
             return FALSE;
     }
     if (*end)
     {
         return FALSE;
     }
     *out = l;
     return TRUE;
 }
CALLBACK (parse_mark , bool , mark_t * out, chunk_t v)
Parse a mark_t
Definition at line 912 of file vici_config.c.
References FALSE, mark_from_string(), and vici_stringify().
 {
     char buf[32];
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     return mark_from_string(buf, out);
 }
CALLBACK (parse_tfc , bool , u_int32_t * out, chunk_t v)
Parse TFC padding option
Definition at line 927 of file vici_config.c.
References chunk_equals(), chunk_from_str, parse_uint32(), and TRUE.
 {
     if (chunk_equals(v, chunk_from_str("mtu")))
     {
         *out = -1;
         return TRUE;
     }
     return parse_uint32(out, v);
 }
CALLBACK (parse_auth , bool , auth_cfg_t * cfg, chunk_t v)
Parse authentication config
Definition at line 941 of file vici_config.c.
References auth_cfg_t::add, AUTH_CLASS_EAP, AUTH_CLASS_PSK, AUTH_CLASS_PUBKEY, AUTH_CLASS_XAUTH, AUTH_RULE_AUTH_CLASS, AUTH_RULE_EAP_TYPE, AUTH_RULE_EAP_VENDOR, AUTH_RULE_XAUTH_BACKEND, eap_vendor_type_from_string(), FALSE, free(), strcaseeq(), strcasepfx(), strdup, TRUE, type, eap_vendor_type_t::type, eap_vendor_type_t::vendor, and vici_stringify().
 {
     char buf[64], *pos;
     eap_vendor_type_t *type;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     if (strcaseeq(buf, "pubkey"))
     {
         cfg->add(cfg, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
         return TRUE;
     }
     if (strcaseeq(buf, "psk"))
     {
         cfg->add(cfg, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PSK);
         return TRUE;
     }
     if (strcasepfx(buf, "xauth"))
     {
         pos = strchr(buf, '-');
         if (pos)
         {
             cfg->add(cfg, AUTH_RULE_XAUTH_BACKEND, strdup(++pos));
         }
         cfg->add(cfg, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_XAUTH);
         return TRUE;
     }
     if (strcasepfx(buf, "eap"))
     {
         cfg->add(cfg, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_EAP);
         type = eap_vendor_type_from_string(buf);
         if (type)
         {
             cfg->add(cfg, AUTH_RULE_EAP_TYPE, type->type);
             if (type->vendor)
             {
                 cfg->add(cfg, AUTH_RULE_EAP_VENDOR, type->vendor);
             }
             free(type);
         }
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_ike_id , bool , auth_cfg_t * cfg, chunk_t v)
Parse IKE identity
Definition at line 1008 of file vici_config.c.
References AUTH_RULE_IDENTITY, and parse_id().
 {
     return parse_id(cfg, AUTH_RULE_IDENTITY, v);
 }
CALLBACK (parse_aaa_id , bool , auth_cfg_t * cfg, chunk_t v)
Parse AAA identity
Definition at line 1017 of file vici_config.c.
References AUTH_RULE_AAA_IDENTITY, and parse_id().
 {
     return parse_id(cfg, AUTH_RULE_AAA_IDENTITY, v);
 }
CALLBACK (parse_eap_id , bool , auth_cfg_t * cfg, chunk_t v)
Parse EAP identity
Definition at line 1026 of file vici_config.c.
References AUTH_RULE_EAP_IDENTITY, and parse_id().
 {
     return parse_id(cfg, AUTH_RULE_EAP_IDENTITY, v);
 }
CALLBACK (parse_xauth_id , bool , auth_cfg_t * cfg, chunk_t v)
Parse XAuth identity
Definition at line 1035 of file vici_config.c.
References AUTH_RULE_XAUTH_IDENTITY, and parse_id().
 {
     return parse_id(cfg, AUTH_RULE_XAUTH_IDENTITY, v);
 }
CALLBACK (parse_group , bool , auth_cfg_t * cfg, chunk_t v)
Parse group membership
Definition at line 1044 of file vici_config.c.
References AUTH_RULE_GROUP, and parse_id().
 {
     return parse_id(cfg, AUTH_RULE_GROUP, v);
 }
CALLBACK (parse_certs , bool , auth_data_t * auth, chunk_t v)
Parse subject certificates
Definition at line 1076 of file vici_config.c.
References AUTH_RULE_SUBJECT_CERT, and parse_cert().
 {
     return parse_cert(auth, AUTH_RULE_SUBJECT_CERT, v);
 }
CALLBACK (parse_cacerts , bool , auth_data_t * auth, chunk_t v)
Parse CA certificates
Definition at line 1085 of file vici_config.c.
References AUTH_RULE_CA_CERT, and parse_cert().
 {
     return parse_cert(auth, AUTH_RULE_CA_CERT, v);
 }
CALLBACK (parse_revocation , bool , auth_cfg_t * cfg, chunk_t v)
Parse revocation status
Definition at line 1094 of file vici_config.c.
References auth_cfg_t::add, AUTH_RULE_CRL_VALIDATION, countof, FALSE, parse_map(), TRUE, VALIDATION_FAILED, VALIDATION_GOOD, and VALIDATION_SKIPPED.
 {
     enum_map_t map[] = {
         { "strict",     VALIDATION_GOOD     },
         { "ifuri",      VALIDATION_SKIPPED  },
         { "relaxed",    VALIDATION_FAILED   },
     };
     int d;
     if (parse_map(map, countof(map), &d, v))
     {
         if (d != VALIDATION_FAILED)
         {
             cfg->add(cfg, AUTH_RULE_CRL_VALIDATION, d);
         }
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_stringlist , bool , char ** out, chunk_t v)
Parse list items to comma separated strings
Definition at line 1118 of file vici_config.c.
References asprintf(), chunk_printable(), FALSE, free(), chunk_t::len, out, chunk_t::ptr, and TRUE.
 {
     char *current;
     if (!chunk_printable(v, NULL, ' '))
     {
         return FALSE;
     }
     current = *out;
     if (current)
     {
         if (asprintf(out, "%s, %.*s", current, (int)v.len, v.ptr) == -1)
         {
             return FALSE;
         }
         free(current);
     }
     else
     {
         if (asprintf(out, "%.*s", (int)v.len, v.ptr) == -1)
         {
             return FALSE;
         }
     }
     return TRUE;
 }
CALLBACK (parse_frag , bool , fragmentation_t * out, chunk_t v)
Parse an fragmentation_t
Definition at line 1149 of file vici_config.c.
References countof, FALSE, FRAGMENTATION_FORCE, FRAGMENTATION_NO, FRAGMENTATION_YES, parse_map(), and TRUE.
 {
     enum_map_t map[] = {
         { "yes",        FRAGMENTATION_YES       },
         { "no",         FRAGMENTATION_NO        },
         { "force",      FRAGMENTATION_FORCE     },
     };
     int d;
     if (parse_map(map, countof(map), &d, v))
     {
         *out = d;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_send_cert , bool , cert_policy_t * out, chunk_t v)
Parse a cert_policy_t
Definition at line 1170 of file vici_config.c.
References CERT_ALWAYS_SEND, CERT_NEVER_SEND, CERT_SEND_IF_ASKED, countof, FALSE, parse_map(), and TRUE.
 {
     enum_map_t map[] = {
         { "ifasked",    CERT_SEND_IF_ASKED  },
         { "always",     CERT_ALWAYS_SEND    },
         { "never",      CERT_NEVER_SEND     },
     };
     int d;
     if (parse_map(map, countof(map), &d, v))
     {
         *out = d;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_unique , bool , unique_policy_t * out, chunk_t v)
Parse a unique_policy_t
Definition at line 1191 of file vici_config.c.
References countof, FALSE, parse_map(), TRUE, UNIQUE_KEEP, UNIQUE_NEVER, UNIQUE_NO, and UNIQUE_REPLACE.
 {
     enum_map_t map[] = {
         { "never",      UNIQUE_NEVER        },
         { "no",         UNIQUE_NO           },
         { "replace",    UNIQUE_REPLACE      },
         { "keep",       UNIQUE_KEEP         },
     };
     int d;
     if (parse_map(map, countof(map), &d, v))
     {
         *out = d;
         return TRUE;
     }
     return FALSE;
 }
CALLBACK (parse_hosts , bool , linked_list_t * list, chunk_t v)
Parse host_t into a list
Definition at line 1213 of file vici_config.c.
References FALSE, host, host_create_from_string(), linked_list_t::insert_last, TRUE, and vici_stringify().
 {
     char buf[64];
     host_t *host;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     host = host_create_from_string(buf, 0);
     if (!host)
     {
         return FALSE;
     }
     list->insert_last(list, host);
     return TRUE;
 }
CALLBACK (child_li , bool , child_data_t * child, vici_message_t * message, char * name, chunk_t value)
Definition at line 1232 of file vici_config.c.
References countof, child_data_t::local_ts, parse_rules(), child_data_t::proposals, child_data_t::remote_ts, request_data_t::reply, and child_data_t::request.
 {
     parse_rule_t rules[] = {
         { "ah_proposals",   parse_ah_proposal,  child->proposals            },
         { "esp_proposals",  parse_esp_proposal, child->proposals            },
         { "local_ts",       parse_ts,           child->local_ts             },
         { "remote_ts",      parse_ts,           child->remote_ts            },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &child->request->reply);
 }
CALLBACK (child_kv , bool , child_data_t * child, vici_message_t * message, char * name, chunk_t value)
Definition at line 1246 of file vici_config.c.
References lifetime_cfg_t::bytes, child_data_t::close_action, countof, child_data_t::dpd_action, child_data_t::hostaccess, child_data_t::inactivity, child_data_t::ipcomp, lifetime_cfg_t::jitter, child_data_t::lft, lifetime_cfg_t::life, child_data_t::mark_in, child_data_t::mark_out, child_data_t::mode, lifetime_cfg_t::packets, parse_bytes(), parse_rules(), parse_uint32(), child_data_t::policies, lifetime_cfg_t::rekey, child_data_t::replay_window, request_data_t::reply, child_data_t::reqid, child_data_t::request, child_data_t::start_action, child_data_t::tfc, lifetime_cfg_t::time, and child_data_t::updown.
 {
     parse_rule_t rules[] = {
         { "updown",         parse_string,       &child->updown              },
         { "hostaccess",     parse_bool,         &child->hostaccess          },
         { "mode",           parse_mode,         &child->mode                },
         { "policies",       parse_bool,         &child->policies            },
         { "replay_window",  parse_uint32,       &child->replay_window       },
         { "rekey_time",     parse_time,         &child->lft.time.rekey      },
         { "life_time",      parse_time,         &child->lft.time.life       },
         { "rand_time",      parse_time,         &child->lft.time.jitter     },
         { "rekey_bytes",    parse_bytes,        &child->lft.bytes.rekey     },
         { "life_bytes",     parse_bytes,        &child->lft.bytes.life      },
         { "rand_bytes",     parse_bytes,        &child->lft.bytes.jitter    },
         { "rekey_packets",  parse_uint64,       &child->lft.packets.rekey   },
         { "life_packets",   parse_uint64,       &child->lft.packets.life    },
         { "rand_packets",   parse_uint64,       &child->lft.packets.jitter  },
         { "dpd_action",     parse_action,       &child->dpd_action          },
         { "start_action",   parse_action,       &child->start_action        },
         { "close_action",   parse_action,       &child->close_action        },
         { "ipcomp",         parse_bool,         &child->ipcomp              },
         { "inactivity",     parse_time,         &child->inactivity          },
         { "reqid",          parse_uint32,       &child->reqid               },
         { "mark_in",        parse_mark,         &child->mark_in             },
         { "mark_out",       parse_mark,         &child->mark_out            },
         { "tfc_padding",    parse_tfc,          &child->tfc                 },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &child->request->reply);
 }
CALLBACK (auth_li , bool , auth_data_t * auth, vici_message_t * message, char * name, chunk_t value)
Definition at line 1279 of file vici_config.c.
References auth_data_t::cfg, countof, parse_rules(), request_data_t::reply, and auth_data_t::request.
 {
     parse_rule_t rules[] = {
         { "groups",         parse_group,        auth->cfg                   },
         { "certs",          parse_certs,        auth                        },
         { "cacerts",        parse_cacerts,      auth                        },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &auth->request->reply);
 }
CALLBACK (auth_kv , bool , auth_data_t * auth, vici_message_t * message, char * name, chunk_t value)
Definition at line 1292 of file vici_config.c.
References auth_data_t::cfg, countof, parse_rules(), request_data_t::reply, and auth_data_t::request.
 {
     parse_rule_t rules[] = {
         { "auth",           parse_auth,         auth->cfg                   },
         { "id",             parse_ike_id,       auth->cfg                   },
         { "aaa_id",         parse_aaa_id,       auth->cfg                   },
         { "eap_id",         parse_eap_id,       auth->cfg                   },
         { "xauth_id",       parse_xauth_id,     auth->cfg                   },
         { "revocation",     parse_revocation,   auth->cfg                   },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &auth->request->reply);
 }
CALLBACK (peer_li , bool , peer_data_t * peer, vici_message_t * message, char * name, chunk_t value)
Definition at line 1308 of file vici_config.c.
References countof, peer_data_t::local_addrs, parse_rules(), peer_data_t::pools, peer_data_t::proposals, peer_data_t::remote_addrs, request_data_t::reply, peer_data_t::request, and peer_data_t::vips.
 {
     parse_rule_t rules[] = {
         { "local_addrs",    parse_stringlist,   &peer->local_addrs          },
         { "remote_addrs",   parse_stringlist,   &peer->remote_addrs         },
         { "proposals",      parse_ike_proposal, peer->proposals             },
         { "vips",           parse_hosts,        peer->vips                  },
         { "pools",          parse_stringlist,   &peer->pools                },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &peer->request->reply);
 }
CALLBACK (peer_kv , bool , peer_data_t * peer, vici_message_t * message, char * name, chunk_t value)
Definition at line 1323 of file vici_config.c.
References peer_data_t::aggressive, countof, peer_data_t::dpd_delay, peer_data_t::dpd_timeout, peer_data_t::encap, peer_data_t::fragmentation, peer_data_t::keyingtries, peer_data_t::local_port, peer_data_t::mobike, peer_data_t::over_time, parse_rules(), parse_uint32(), peer_data_t::pull, peer_data_t::rand_time, peer_data_t::reauth_time, peer_data_t::rekey_time, peer_data_t::remote_port, request_data_t::reply, peer_data_t::request, peer_data_t::send_cert, peer_data_t::send_certreq, peer_data_t::unique, and peer_data_t::version.
 {
     parse_rule_t rules[] = {
         { "version",        parse_uint32,       &peer->version              },
         { "aggressive",     parse_bool,         &peer->aggressive           },
         { "pull",           parse_bool,         &peer->pull                 },
         { "encap",          parse_bool,         &peer->encap                },
         { "mobike",         parse_bool,         &peer->mobike               },
         { "dpd_delay",      parse_time,         &peer->dpd_delay            },
         { "dpd_timeout",    parse_time,         &peer->dpd_timeout          },
         { "fragmentation",  parse_frag,         &peer->fragmentation        },
         { "send_certreq",   parse_bool,         &peer->send_certreq         },
         { "send_cert",      parse_send_cert,    &peer->send_cert            },
         { "keyingtries",    parse_uint32,       &peer->keyingtries          },
         { "unique",         parse_unique,       &peer->unique               },
         { "local_port",     parse_uint32,       &peer->local_port           },
         { "remote_port",    parse_uint32,       &peer->remote_port          },
         { "reauth_time",    parse_time,         &peer->reauth_time          },
         { "rekey_time",     parse_time,         &peer->rekey_time           },
         { "over_time",      parse_time,         &peer->over_time            },
         { "rand_time",      parse_time,         &peer->rand_time            },
     };
     return parse_rules(rules, countof(rules), name, value,
                        &peer->request->reply);
 }
CALLBACK (children_sn , bool , peer_data_t * peer, vici_message_t * message, vici_parse_context_t * ctx, char * name)
Definition at line 1351 of file vici_config.c.
References ACTION_NONE, child_cfg_t::add_proposal, child_cfg_t::add_traffic_selector, lifetime_cfg_t::bytes, child_cfg_create(), peer_data_t::children, child_data_t::close_action, child_data_t::dpd_action, FALSE, free_child_data(), linked_list_t::get_count, child_data_t::hostaccess, child_data_t::inactivity, linked_list_t::insert_last, child_data_t::ipcomp, lifetime_cfg_t::jitter, child_data_t::lft, LFT_DEFAULT_CHILD_REKEY, LFT_UNDEFINED, lifetime_cfg_t::life, linked_list_create(), child_data_t::local_ts, log_child_data(), child_data_t::mark_in, child_data_t::mark_out, min, child_data_t::mode, MODE_TUNNEL, lifetime_cfg_t::packets, vici_message_t::parse, child_data_t::policies, proposal, proposal_create_default(), proposal_create_default_aead(), child_data_t::proposals, PROTO_ESP, lifetime_cfg_t::rekey, child_data_t::remote_ts, linked_list_t::remove_first, REPLAY_UNDEFINED, child_data_t::replay_window, child_data_t::reqid, peer_data_t::request, child_data_t::request, child_cfg_t::set_mipv6_options, child_cfg_t::set_replay_window, child_data_t::start_action, SUCCESS, child_data_t::tfc, lifetime_cfg_t::time, traffic_selector_create_dynamic(), TRUE, and child_data_t::updown.
 {
     child_data_t child = {
         .request = peer->request,
         .proposals = linked_list_create(),
         .local_ts = linked_list_create(),
         .remote_ts = linked_list_create(),
         .mode = MODE_TUNNEL,
         .policies = TRUE,
         .replay_window = REPLAY_UNDEFINED,
         .dpd_action = ACTION_NONE,
         .start_action = ACTION_NONE,
         .close_action = ACTION_NONE,
         .lft = {
             .time = {
                 .rekey = LFT_DEFAULT_CHILD_REKEY,
                 .life = LFT_UNDEFINED,
                 .jitter = LFT_UNDEFINED,
             },
             .bytes = {
                 .rekey = LFT_UNDEFINED,
                 .life = LFT_UNDEFINED,
                 .jitter = LFT_UNDEFINED,
             },
             .packets = {
                 .rekey = LFT_UNDEFINED,
                 .life = LFT_UNDEFINED,
                 .jitter = LFT_UNDEFINED,
             },
         }
     };
     child_cfg_t *cfg;
     proposal_t *proposal;
     traffic_selector_t *ts;
     if (!message->parse(message, ctx, NULL, child_kv, child_li, &child))
     {
         free_child_data(&child);
         return FALSE;
     }
     if (child.local_ts->get_count(child.local_ts) == 0)
     {
         child.local_ts->insert_last(child.local_ts,
                             traffic_selector_create_dynamic(0, 0, 65535));
     }
     if (child.remote_ts->get_count(child.remote_ts) == 0)
     {
         child.remote_ts->insert_last(child.remote_ts,
                             traffic_selector_create_dynamic(0, 0, 65535));
     }
     if (child.proposals->get_count(child.proposals) == 0)
     {
         proposal = proposal_create_default(PROTO_ESP);
         if (proposal)
         {
             child.proposals->insert_last(child.proposals, proposal);
         }
         proposal = proposal_create_default_aead(PROTO_ESP);
         if (proposal)
         {
             child.proposals->insert_last(child.proposals, proposal);
         }
     }
     /* if no hard lifetime specified, add one at soft lifetime + 10% */
     if (child.lft.time.life == LFT_UNDEFINED)
     {
         child.lft.time.life = child.lft.time.rekey * 110 / 100;
     }
     if (child.lft.bytes.life == LFT_UNDEFINED)
     {
         child.lft.bytes.life = child.lft.bytes.rekey * 110 / 100;
     }
     if (child.lft.packets.life == LFT_UNDEFINED)
     {
         child.lft.packets.life = child.lft.packets.rekey * 110 / 100;
     }
     /* if no soft lifetime specified, add one at hard lifetime - 10% */
     if (child.lft.bytes.rekey == LFT_UNDEFINED)
     {
         child.lft.bytes.rekey = child.lft.bytes.life * 90 / 100;
     }
     if (child.lft.packets.rekey == LFT_UNDEFINED)
     {
         child.lft.packets.rekey = child.lft.packets.life * 90 / 100;
     }
     /* if no rand time defined, use difference of hard and soft */
     if (child.lft.time.jitter == LFT_UNDEFINED)
     {
         child.lft.time.jitter = child.lft.time.life -
                         min(child.lft.time.life, child.lft.time.rekey);
     }
     if (child.lft.bytes.jitter == LFT_UNDEFINED)
     {
         child.lft.bytes.jitter = child.lft.bytes.life -
                         min(child.lft.bytes.life, child.lft.bytes.rekey);
     }
     if (child.lft.packets.jitter == LFT_UNDEFINED)
     {
         child.lft.packets.jitter = child.lft.packets.life -
                         min(child.lft.packets.life, child.lft.packets.rekey);
     }
     log_child_data(&child, name);
     cfg = child_cfg_create(name, &child.lft, child.updown,
                         child.hostaccess, child.mode, child.start_action,
                         child.dpd_action, child.close_action, child.ipcomp,
                         child.inactivity, child.reqid, &child.mark_in,
                         &child.mark_out, child.tfc);
     cfg->set_mipv6_options(cfg, FALSE, child.policies);
     if (child.replay_window != REPLAY_UNDEFINED)
     {
         cfg->set_replay_window(cfg, child.replay_window);
     }
     while (child.local_ts->remove_first(child.local_ts,
                                         (void**)&ts) == SUCCESS)
     {
         cfg->add_traffic_selector(cfg, TRUE, ts);
     }
     while (child.remote_ts->remove_first(child.remote_ts,
                                          (void**)&ts) == SUCCESS)
     {
         cfg->add_traffic_selector(cfg, FALSE, ts);
     }
     while (child.proposals->remove_first(child.proposals,
                                          (void**)&proposal) == SUCCESS)
     {
         cfg->add_proposal(cfg, proposal);
     }
     peer->children->insert_last(peer->children, cfg);
     free_child_data(&child);
     return TRUE;
 }
CALLBACK (peer_sn , bool , peer_data_t * peer, vici_message_t * message, vici_parse_context_t * ctx, char * name)
Definition at line 1494 of file vici_config.c.
References auth_cfg_t::add, auth_cfg_create(), AUTH_RULE_IDENTITY, AUTH_RULE_SUBJECT_CERT, cert, auth_data_t::cfg, identification_t::clone, create_reply(), DBG1, DBG_CFG, auth_cfg_t::destroy, FALSE, auth_cfg_t::get, certificate_t::get_subject, id, linked_list_t::insert_last, peer_data_t::local, vici_message_t::parse, peer_data_t::remote, request_data_t::reply, peer_data_t::request, auth_data_t::request, strcaseeq(), strcasepfx(), and TRUE.
 {
     if (strcaseeq(name, "children"))
     {
         return message->parse(message, ctx, children_sn, NULL, NULL, peer);
     }
     if (strcasepfx(name, "local") ||
         strcasepfx(name, "remote"))
     {
         auth_data_t auth = {
             .request = peer->request,
             .cfg = auth_cfg_create(),
         };
         if (!message->parse(message, ctx, NULL, auth_kv, auth_li, &auth))
         {
             auth.cfg->destroy(auth.cfg);
             return FALSE;
         }
         if (!auth.cfg->get(auth.cfg, AUTH_RULE_IDENTITY))
         {
             identification_t *id;
             certificate_t *cert;
             cert = auth.cfg->get(auth.cfg, AUTH_RULE_SUBJECT_CERT);
             if (cert)
             {
                 id = cert->get_subject(cert);
                 DBG1(DBG_CFG, "  id not specified, defaulting to cert id '%Y'",
                      id);
                 auth.cfg->add(auth.cfg, AUTH_RULE_IDENTITY, id->clone(id));
             }
         }
         if (strcasepfx(name, "local"))
         {
             peer->local->insert_last(peer->local, auth.cfg);
         }
         else
         {
             peer->remote->insert_last(peer->remote, auth.cfg);
         }
         return TRUE;
     }
     peer->request->reply = create_reply("invalid section: %s", name);
     return FALSE;
 }
CALLBACK (config_sn , bool , request_data_t * request, vici_message_t * message, vici_parse_context_t * ctx, char * name)
Definition at line 1802 of file vici_config.c.
References peer_cfg_t::add_auth_cfg, peer_cfg_t::add_child_cfg, peer_cfg_t::add_pool, ike_cfg_t::add_proposal, peer_cfg_t::add_virtual_ip, peer_data_t::aggressive, auth_cfg_create(), CERT_SEND_IF_ASKED, charon, peer_data_t::children, create_reply(), DBG2, DBG_CFG, enumerator_t::destroy, peer_data_t::dpd_delay, peer_data_t::dpd_timeout, peer_data_t::encap, enumerator_t::enumerate, enumerator_create_token(), FALSE, peer_data_t::fragmentation, FRAGMENTATION_NO, free_peer_data(), linked_list_t::get_count, socket_manager_t::get_port, host, IKE_ANY, ike_cfg_create(), IKEV2_UDP_PORT, linked_list_t::insert_last, peer_data_t::keyingtries, LFT_DEFAULT_IKE_REKEY, LFT_UNDEFINED, linked_list_create(), peer_data_t::local, peer_data_t::local_addrs, peer_data_t::local_port, log_peer_data(), max, merge_config(), min, peer_data_t::mobike, peer_data_t::over_time, vici_message_t::parse, peer_cfg_create(), peer_data_t::pools, proposal, proposal_create_default(), proposal_create_default_aead(), peer_data_t::proposals, PROTO_IKE, peer_data_t::pull, peer_data_t::rand_time, peer_data_t::reauth_time, peer_data_t::rekey_time, peer_data_t::remote, peer_data_t::remote_addrs, peer_data_t::remote_port, linked_list_t::remove_first, request_data_t::reply, request(), peer_data_t::request, peer_data_t::send_cert, peer_data_t::send_certreq, daemon_t::socket, str, strdup, SUCCESS, request_data_t::this, TRUE, peer_data_t::unique, UNIQUE_NO, peer_data_t::version, and peer_data_t::vips.
 {
     peer_data_t peer = {
         .request = request,
         .local = linked_list_create(),
         .remote = linked_list_create(),
         .vips = linked_list_create(),
         .children = linked_list_create(),
         .proposals = linked_list_create(),
         .mobike = TRUE,
         .send_certreq = TRUE,
         .pull = TRUE,
         .send_cert = CERT_SEND_IF_ASKED,
         .version = IKE_ANY,
         .remote_port = IKEV2_UDP_PORT,
         .fragmentation = FRAGMENTATION_NO,
         .unique = UNIQUE_NO,
         .keyingtries = 1,
         .rekey_time = LFT_UNDEFINED,
         .reauth_time = LFT_UNDEFINED,
         .over_time = LFT_UNDEFINED,
         .rand_time = LFT_UNDEFINED,
     };
     enumerator_t *enumerator;
     peer_cfg_t *peer_cfg;
     ike_cfg_t *ike_cfg;
     child_cfg_t *child_cfg;
     auth_cfg_t *auth_cfg;
     proposal_t *proposal;
     host_t *host;
     char *str;
     DBG2(DBG_CFG, " conn %s:", name);
     if (!message->parse(message, ctx, peer_sn, peer_kv, peer_li, &peer))
     {
         free_peer_data(&peer);
         return FALSE;
     }
     if (peer.local->get_count(peer.local) == 0)
     {
         free_peer_data(&peer);
         peer.request->reply = create_reply("missing local auth config");
         return FALSE;
     }
     if (peer.remote->get_count(peer.remote) == 0)
     {
         auth_cfg = auth_cfg_create();
         peer.remote->insert_last(peer.remote, auth_cfg);
     }
     if (peer.proposals->get_count(peer.proposals) == 0)
     {
         proposal = proposal_create_default(PROTO_IKE);
         if (proposal)
         {
             peer.proposals->insert_last(peer.proposals, proposal);
         }
         proposal = proposal_create_default_aead(PROTO_IKE);
         if (proposal)
         {
             peer.proposals->insert_last(peer.proposals, proposal);
         }
     }
     if (!peer.local_addrs)
     {
         peer.local_addrs = strdup("%any");
     }
     if (!peer.remote_addrs)
     {
         peer.remote_addrs = strdup("%any");
     }
     if (!peer.local_port)
     {
         peer.local_port = charon->socket->get_port(charon->socket, FALSE);
     }
     if (peer.rekey_time == LFT_UNDEFINED && peer.reauth_time == LFT_UNDEFINED)
     {
         /* apply a default rekey time if no rekey/reauth time set */
         peer.rekey_time = LFT_DEFAULT_IKE_REKEY;
         peer.reauth_time = 0;
     }
     if (peer.rekey_time == LFT_UNDEFINED)
     {
         peer.rekey_time = 0;
     }
     if (peer.reauth_time == LFT_UNDEFINED)
     {
         peer.reauth_time = 0;
     }
     if (peer.over_time == LFT_UNDEFINED)
     {
         /* default over_time to 10% of rekey/reauth time if not given */
         peer.over_time = max(peer.rekey_time, peer.reauth_time) / 10;
     }
     if (peer.rand_time == LFT_UNDEFINED)
     {
         /* default rand_time to over_time if not given, but don't make it
          * longer than half of rekey/rauth time */
         if (peer.rekey_time && peer.reauth_time)
         {
             peer.rand_time = min(peer.rekey_time, peer.reauth_time);
         }
         else
         {
             peer.rand_time = max(peer.rekey_time, peer.reauth_time);
         }
         peer.rand_time = min(peer.over_time, peer.rand_time / 2);
     }
     log_peer_data(&peer);
     ike_cfg = ike_cfg_create(peer.version, peer.send_certreq, peer.encap,
                         peer.local_addrs, peer.local_port,
                         peer.remote_addrs, peer.remote_port,
                         peer.fragmentation, 0);
     peer_cfg = peer_cfg_create(name, ike_cfg, peer.send_cert, peer.unique,
                         peer.keyingtries, peer.rekey_time, peer.reauth_time,
                         peer.rand_time, peer.over_time, peer.mobike,
                         peer.aggressive, peer.pull,
                         peer.dpd_delay, peer.dpd_timeout,
                         FALSE, NULL, NULL);
     while (peer.local->remove_first(peer.local,
                                     (void**)&auth_cfg) == SUCCESS)
     {
         peer_cfg->add_auth_cfg(peer_cfg, auth_cfg, TRUE);
     }
     while (peer.remote->remove_first(peer.remote,
                                      (void**)&auth_cfg) == SUCCESS)
     {
         peer_cfg->add_auth_cfg(peer_cfg, auth_cfg, FALSE);
     }
     while (peer.children->remove_first(peer.children,
                                        (void**)&child_cfg) == SUCCESS)
     {
         peer_cfg->add_child_cfg(peer_cfg, child_cfg);
     }
     while (peer.proposals->remove_first(peer.proposals,
                                         (void**)&proposal) == SUCCESS)
     {
         ike_cfg->add_proposal(ike_cfg, proposal);
     }
     while (peer.vips->remove_first(peer.vips, (void**)&host) == SUCCESS)
     {
         peer_cfg->add_virtual_ip(peer_cfg, host);
     }
     if (peer.pools)
     {
         enumerator = enumerator_create_token(peer.pools, ",", " ");
         while (enumerator->enumerate(enumerator, &str))
         {
             peer_cfg->add_pool(peer_cfg, str);
         }
         enumerator->destroy(enumerator);
     }
     free_peer_data(&peer);
     merge_config(request->this, peer_cfg);
     return TRUE;
 }
CALLBACK (load_conn , vici_message_t * , private_vici_config_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 1969 of file vici_config.c.
References create_reply(), vici_message_t::parse, request_data_t::reply, and request().
 {
     request_data_t request = {
         .this = this,
     };
     if (!message->parse(message, NULL, config_sn, NULL, NULL, &request))
     {
         if (request.reply)
         {
             return request.reply;
         }
         return create_reply("parsing request failed");
     }
     return create_reply(NULL);
 }
CALLBACK (unload_conn , vici_message_t * , private_vici_config_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 1987 of file vici_config.c.
References create_reply(), enumerator_t::destroy, peer_cfg_t::destroy, enumerator_t::enumerate, FALSE, found, peer_cfg_t::get_name, vici_message_t::get_str, lock, streq(), TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     peer_cfg_t *cfg;
     char *conn_name;
     bool found = FALSE;
     conn_name = message->get_str(message, NULL, "name");
     if (!conn_name)
     {
         return create_reply("unload: missing connection name");
     }
     this->lock->write_lock(this->lock);
     enumerator = this->conns->create_enumerator(this->conns);
     while (enumerator->enumerate(enumerator, &cfg))
     {
         if (streq(cfg->get_name(cfg), conn_name))
         {
             this->conns->remove_at(this->conns, enumerator);
             cfg->destroy(cfg);
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!found)
     {
         return create_reply("unload: connection '%s' not found", conn_name);
     }
     return create_reply(NULL);
 }
CALLBACK (get_conns , vici_message_t * , private_vici_config_t * this, char * name, u_int id, vici_message_t * message)
Definition at line 2023 of file vici_config.c.
References vici_builder_t::add_li, vici_builder_t::begin_list, enumerator_t::destroy, vici_builder_t::end_list, enumerator_t::enumerate, vici_builder_t::finalize, peer_cfg_t::get_name, lock, spinlock_t::unlock, and vici_builder_create().
 {
     vici_builder_t *builder;
     enumerator_t *enumerator;
     peer_cfg_t *cfg;
     builder = vici_builder_create();
     builder->begin_list(builder, "conns");
     this->lock->read_lock(this->lock);
     enumerator = this->conns->create_enumerator(this->conns);
     while (enumerator->enumerate(enumerator, &cfg))
     {
         builder->add_li(builder, "%s", cfg->get_name(cfg));
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     builder->end_list(builder);
     return builder->finalize(builder);
 }
static void clear_start_action (private_vici_config_t * this, child_cfg_t * child_cfg) static
Undo start actions associated to a child config
Definition at line 1616 of file vici_config.c.
References ACTION_RESTART, ACTION_ROUTE, array_count(), array_destroy(), ARRAY_HEAD, array_insert_create(), array_remove(), ARRAY_TAIL, charon, daemon_t::controller, ike_sa_t::create_child_sa_enumerator, trap_manager_t::create_enumerator, controller_t::create_ike_sa_enumerator, DBG1, DBG_CFG, del(), enumerator_t::destroy, enumerator_t::enumerate, child_cfg_t::get_mode, child_cfg_t::get_name, child_sa_t::get_name, child_sa_t::get_reqid, child_cfg_t::get_start_action, child_sa_t::get_unique_id, MODE_DROP, MODE_PASS, name, daemon_t::shunts, streq(), controller_t::terminate_child, daemon_t::traps, TRUE, shunt_manager_t::uninstall, and trap_manager_t::uninstall.
Referenced by clear_start_actions(), and replace_children().
 {
     enumerator_t *enumerator, *children;
     child_sa_t *child_sa;
     ike_sa_t *ike_sa;
     u_int32_t id = 0, *del;
     array_t *ids = NULL;
     char *name;
     name = child_cfg->get_name(child_cfg);
     switch (child_cfg->get_start_action(child_cfg))
     {
         case ACTION_RESTART:
             enumerator = charon->controller->create_ike_sa_enumerator(
                                                     charon->controller, TRUE);
             while (enumerator->enumerate(enumerator, &ike_sa))
             {
                 children = ike_sa->create_child_sa_enumerator(ike_sa);
                 while (children->enumerate(children, &child_sa))
                 {
                     if (streq(name, child_sa->get_name(child_sa)))
                     {
                         id = child_sa->get_unique_id(child_sa);
                         array_insert_create(&ids, ARRAY_TAIL, &id);
                     }
                 }
                 children->destroy(children);
             }
             enumerator->destroy(enumerator);
             if (array_count(ids))
             {
                 while (array_remove(ids, ARRAY_HEAD, &del))
                 {
                     DBG1(DBG_CFG, "closing '%s' #%u", name, *del);
                     charon->controller->terminate_child(charon->controller,
                                                         *del, NULL, NULL, 0);
                 }
                 array_destroy(ids);
             }
             break;
         case ACTION_ROUTE:
             DBG1(DBG_CFG, "uninstalling '%s'", name);
             switch (child_cfg->get_mode(child_cfg))
             {
                 case MODE_PASS:
                 case MODE_DROP:
                     charon->shunts->uninstall(charon->shunts, name);
                     break;
                 default:
                     enumerator = charon->traps->create_enumerator(charon->traps);
                     while (enumerator->enumerate(enumerator, NULL, &child_sa))
                     {
                         if (streq(name, child_sa->get_name(child_sa)))
{
                             id = child_sa->get_reqid(child_sa);
                             break;
                         }
                     }
                     enumerator->destroy(enumerator);
                     if (id)
                     {
                         charon->traps->uninstall(charon->traps, id);
                     }
                     break;
             }
             break;
         default:
             break;
     }
 }
static void clear_start_actions (private_vici_config_t * this, peer_cfg_t * peer_cfg) static
Undo start actions associated to all child configs of a peer config
Definition at line 1708 of file vici_config.c.
References clear_start_action(), peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, and enumerator_t::enumerate.
Referenced by merge_config().
 {
     enumerator_t *enumerator;
     child_cfg_t *child_cfg;
     enumerator = peer_cfg->create_child_cfg_enumerator(peer_cfg);
     while (enumerator->enumerate(enumerator, &child_cfg))
     {
         clear_start_action(this, child_cfg);
     }
     enumerator->destroy(enumerator);
 }
static vici_message_t* create_reply (char * fmt, ...) static
Create a (error) reply message
Definition at line 159 of file vici_config.c.
References vici_builder_t::add_kv, vici_builder_t::finalize, vici_builder_t::vadd_kv, and vici_builder_create().
Referenced by CALLBACK(), and parse_rules().
 {
     vici_builder_t *builder;
     va_list args;
     builder = vici_builder_create();
     builder->add_kv(builder, "success", fmt ? "no" : "yes");
     if (fmt)
     {
         va_start(args, fmt);
         builder->vadd_kv(builder, "errmsg", fmt, args);
         va_end(args);
     }
     return builder->finalize(builder);
 }
static u_int32_t find_reqid (child_cfg_t * cfg) static
Find reqid of an existing CHILD_SA
Definition at line 1548 of file vici_config.c.
References charon, daemon_t::controller, ike_sa_t::create_child_sa_enumerator, controller_t::create_ike_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, trap_manager_t::find_reqid, child_cfg_t::get_name, child_sa_t::get_name, child_sa_t::get_reqid, streq(), daemon_t::traps, and TRUE.
Referenced by run_start_action().
 {
     enumerator_t *enumerator, *children;
     child_sa_t *child_sa;
     ike_sa_t *ike_sa;
     u_int32_t reqid;
     reqid = charon->traps->find_reqid(charon->traps, cfg);
     if (reqid)
     {   /* already trapped */
         return reqid;
     }
     enumerator = charon->controller->create_ike_sa_enumerator(
                                                     charon->controller, TRUE);
     while (!reqid && enumerator->enumerate(enumerator, &ike_sa))
     {
         children = ike_sa->create_child_sa_enumerator(ike_sa);
         while (children->enumerate(children, &child_sa))
         {
             if (streq(cfg->get_name(cfg), child_sa->get_name(child_sa)))
             {
                 reqid = child_sa->get_reqid(child_sa);
                 break;
             }
         }
         children->destroy(children);
     }
     enumerator->destroy(enumerator);
     return reqid;
 }
static void free_child_data (child_data_t * data) static
Clean up CHILD config data
Definition at line 452 of file vici_config.c.
References destroy(), linked_list_t::destroy_offset, free(), child_data_t::local_ts, child_data_t::proposals, child_data_t::remote_ts, and child_data_t::updown.
Referenced by CALLBACK().
 {
     data->proposals->destroy_offset(data->proposals,
                                     offsetof(proposal_t, destroy));
     data->local_ts->destroy_offset(data->local_ts,
                                     offsetof(traffic_selector_t, destroy));
     data->remote_ts->destroy_offset(data->remote_ts,
                                     offsetof(traffic_selector_t, destroy));
     free(data->updown);
 }
static void free_peer_data (peer_data_t * data) static
Clean up peer config data
Definition at line 369 of file vici_config.c.
References peer_data_t::children, destroy(), linked_list_t::destroy_offset, free(), peer_data_t::local, peer_data_t::local_addrs, peer_data_t::pools, peer_data_t::proposals, peer_data_t::remote, peer_data_t::remote_addrs, and peer_data_t::vips.
Referenced by CALLBACK().
 {
     data->local->destroy_offset(data->local,
                                     offsetof(auth_cfg_t, destroy));
     data->remote->destroy_offset(data->remote,
                                     offsetof(auth_cfg_t, destroy));
     data->children->destroy_offset(data->children,
                                     offsetof(child_cfg_t, destroy));
     data->proposals->destroy_offset(data->proposals,
                                     offsetof(proposal_t, destroy));
     data->vips->destroy_offset(data->vips, offsetof(host_t, destroy));
     free(data->pools);
     free(data->local_addrs);
     free(data->remote_addrs);
 }
static bool ike_filter (void * data, peer_cfg_t ** in, ike_cfg_t ** out) static
Enumerator filter function for ike configs
Definition at line 118 of file vici_config.c.
References TRUE.
Referenced by METHOD().
 {
     *out = (*in)->get_ike_cfg(*in);
     return TRUE;
 }
static void log_auth (auth_cfg_t * auth) static
Log relevant auth config data
Definition at line 256 of file vici_config.c.
References auth_class_names, AUTH_RULE_AAA_IDENTITY, AUTH_RULE_AUTH_CLASS, AUTH_RULE_CRL_VALIDATION, AUTH_RULE_EAP_IDENTITY, AUTH_RULE_EAP_TYPE, AUTH_RULE_EAP_VENDOR, AUTH_RULE_GROUP, AUTH_RULE_IDENTITY, AUTH_RULE_XAUTH_BACKEND, AUTH_RULE_XAUTH_IDENTITY, cert_validation_names, auth_cfg_t::create_enumerator, DBG2, DBG_CFG, enumerator_t::destroy, eap_type_names, enumerator_t::enumerate, id, and str.
Referenced by log_peer_data().
 {
     enumerator_t *enumerator;
     auth_rule_t rule;
     union {
         uintptr_t u;
         identification_t *id;
         char *str;
     } v;
     enumerator = auth->create_enumerator(auth);
     while (enumerator->enumerate(enumerator, &rule, &v))
     {
         switch (rule)
         {
             case AUTH_RULE_AUTH_CLASS:
                 DBG2(DBG_CFG, "   class = %N", auth_class_names, v.u);
                 break;
             case AUTH_RULE_EAP_TYPE:
                 DBG2(DBG_CFG, "   eap-type = %N", eap_type_names, v.u);
                 break;
             case AUTH_RULE_EAP_VENDOR:
                 DBG2(DBG_CFG, "   eap-vendor = %u", v.u);
                 break;
             case AUTH_RULE_XAUTH_BACKEND:
                 DBG2(DBG_CFG, "   xauth = %s", v.str);
                 break;
             case AUTH_RULE_CRL_VALIDATION:
                 DBG2(DBG_CFG, "   revocation = %N", cert_validation_names, v.u);
                 break;
             case AUTH_RULE_IDENTITY:
                 DBG2(DBG_CFG, "   id = %Y", v.id);
                 break;
             case AUTH_RULE_AAA_IDENTITY:
                 DBG2(DBG_CFG, "   aaa_id = %Y", v.id);
                 break;
             case AUTH_RULE_EAP_IDENTITY:
                 DBG2(DBG_CFG, "   eap_id = %Y", v.id);
                 break;
             case AUTH_RULE_XAUTH_IDENTITY:
                 DBG2(DBG_CFG, "   xauth_id = %Y", v.id);
                 break;
             case AUTH_RULE_GROUP:
                 DBG2(DBG_CFG, "   group = %Y", v.id);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
 }
static void log_child_data (child_data_t * data, char * name) static
Log parsed CHILD config data
Definition at line 413 of file vici_config.c.
References action_names, lifetime_cfg_t::bytes, child_data_t::close_action, DBG2, DBG_CFG, child_data_t::dpd_action, child_data_t::hostaccess, child_data_t::inactivity, child_data_t::ipcomp, ipsec_mode_names, lifetime_cfg_t::jitter, child_data_t::lft, lifetime_cfg_t::life, child_data_t::local_ts, child_data_t::mark_in, child_data_t::mark_out, mark_t::mask, child_data_t::mode, lifetime_cfg_t::packets, child_data_t::policies, child_data_t::proposals, lifetime_cfg_t::rekey, child_data_t::remote_ts, REPLAY_UNDEFINED, child_data_t::replay_window, child_data_t::reqid, child_data_t::start_action, child_data_t::tfc, lifetime_cfg_t::time, child_data_t::updown, and mark_t::value.
Referenced by CALLBACK().
 {
     DBG2(DBG_CFG, "  child %s:", name);
     DBG2(DBG_CFG, "   rekey_time = %llu", data->lft.time.rekey);
     DBG2(DBG_CFG, "   life_time = %llu", data->lft.time.life);
     DBG2(DBG_CFG, "   rand_time = %llu", data->lft.time.jitter);
     DBG2(DBG_CFG, "   rekey_bytes = %llu", data->lft.bytes.rekey);
     DBG2(DBG_CFG, "   life_bytes = %llu", data->lft.bytes.life);
     DBG2(DBG_CFG, "   rand_bytes = %llu", data->lft.bytes.jitter);
     DBG2(DBG_CFG, "   rekey_packets = %llu", data->lft.packets.rekey);
     DBG2(DBG_CFG, "   life_packets = %llu", data->lft.packets.life);
     DBG2(DBG_CFG, "   rand_packets = %llu", data->lft.packets.jitter);
     DBG2(DBG_CFG, "   updown = %s", data->updown);
     DBG2(DBG_CFG, "   hostaccess = %u", data->hostaccess);
     DBG2(DBG_CFG, "   ipcomp = %u", data->ipcomp);
     DBG2(DBG_CFG, "   mode = %N", ipsec_mode_names, data->mode);
     DBG2(DBG_CFG, "   policies = %u", data->policies);
     if (data->replay_window != REPLAY_UNDEFINED)
     {
         DBG2(DBG_CFG, "   replay_window = %u", data->replay_window);
     }
     DBG2(DBG_CFG, "   dpd_action = %N", action_names, data->dpd_action);
     DBG2(DBG_CFG, "   start_action = %N", action_names, data->start_action);
     DBG2(DBG_CFG, "   close_action = %N", action_names, data->close_action);
     DBG2(DBG_CFG, "   reqid = %u", data->reqid);
     DBG2(DBG_CFG, "   tfc = %d", data->tfc);
     DBG2(DBG_CFG, "   mark_in = %u/%u",
          data->mark_in.value, data->mark_in.mask);
     DBG2(DBG_CFG, "   mark_out = %u/%u",
          data->mark_out.value, data->mark_out.mask);
     DBG2(DBG_CFG, "   inactivity = %llu", data->inactivity);
     DBG2(DBG_CFG, "   proposals = %#P", data->proposals);
     DBG2(DBG_CFG, "   local_ts = %#R", data->local_ts);
     DBG2(DBG_CFG, "   remote_ts = %#R", data->remote_ts);
 }
static void log_peer_data (peer_data_t * data) static
Log parsed peer data
Definition at line 311 of file vici_config.c.
References peer_data_t::aggressive, cert_policy_names, linked_list_t::create_enumerator, DBG2, DBG_CFG, enumerator_t::destroy, peer_data_t::dpd_delay, peer_data_t::dpd_timeout, peer_data_t::encap, enumerator_t::enumerate, peer_data_t::fragmentation, linked_list_t::get_count, host, peer_data_t::keyingtries, peer_data_t::local, peer_data_t::local_addrs, peer_data_t::local_port, log_auth(), peer_data_t::mobike, peer_data_t::over_time, peer_data_t::proposals, peer_data_t::rand_time, peer_data_t::reauth_time, peer_data_t::rekey_time, peer_data_t::remote, peer_data_t::remote_addrs, peer_data_t::remote_port, peer_data_t::send_cert, peer_data_t::send_certreq, peer_data_t::unique, unique_policy_names, peer_data_t::version, and peer_data_t::vips.
Referenced by CALLBACK().
 {
     enumerator_t *enumerator;
     auth_cfg_t *auth;
     host_t *host;
     DBG2(DBG_CFG, "  version = %u", data->version);
     DBG2(DBG_CFG, "  local_addrs = %s", data->local_addrs);
     DBG2(DBG_CFG, "  remote_addrs = %s", data->remote_addrs);
     DBG2(DBG_CFG, "  local_port = %u", data->local_port);
     DBG2(DBG_CFG, "  remote_port = %u", data->remote_port);
     DBG2(DBG_CFG, "  send_certreq = %u", data->send_certreq);
     DBG2(DBG_CFG, "  send_cert = %N", cert_policy_names, data->send_cert);
     DBG2(DBG_CFG, "  mobike = %u", data->mobike);
     DBG2(DBG_CFG, "  aggressive = %u", data->aggressive);
     DBG2(DBG_CFG, "  encap = %u", data->encap);
     DBG2(DBG_CFG, "  dpd_delay = %llu", data->dpd_delay);
     DBG2(DBG_CFG, "  dpd_timeout = %llu", data->dpd_timeout);
     DBG2(DBG_CFG, "  fragmentation = %u",  data->fragmentation);
     DBG2(DBG_CFG, "  unique = %N", unique_policy_names, data->unique);
     DBG2(DBG_CFG, "  keyingtries = %u", data->keyingtries);
     DBG2(DBG_CFG, "  reauth_time = %llu", data->reauth_time);
     DBG2(DBG_CFG, "  rekey_time = %llu", data->rekey_time);
     DBG2(DBG_CFG, "  over_time = %llu", data->over_time);
     DBG2(DBG_CFG, "  rand_time = %llu", data->rand_time);
     DBG2(DBG_CFG, "  proposals = %#P", data->proposals);
     if (data->vips->get_count(data->vips))
     {
         DBG2(DBG_CFG, "  vips:");
     }
     enumerator = data->vips->create_enumerator(data->vips);
     while (enumerator->enumerate(enumerator, &host))
     {
         DBG2(DBG_CFG, "   %H", host);
     }
     enumerator->destroy(enumerator);
     enumerator = data->local->create_enumerator(data->local);
     while (enumerator->enumerate(enumerator, &auth))
     {
         DBG2(DBG_CFG, "  local:");
         log_auth(auth);
     }
     enumerator->destroy(enumerator);
     enumerator = data->remote->create_enumerator(data->remote);
     while (enumerator->enumerate(enumerator, &auth))
     {
         DBG2(DBG_CFG, "  remote:");
         log_auth(auth);
     }
     enumerator->destroy(enumerator);
 }
static void manage_command (private_vici_config_t * this, char * name, vici_command_cb_t cb, bool reg) static
Definition at line 2047 of file vici_config.c.
Referenced by manage_commands().
 {
     this->dispatcher->manage_command(this->dispatcher, name,
                                      reg ? cb : NULL, this);
 }
static void manage_commands (private_vici_config_t * this, bool reg) static
(Un-)register dispatcher functions
Definition at line 2057 of file vici_config.c.
References load_conn(), manage_command(), and unload_conn().
Referenced by METHOD(), and vici_config_create().
 {
     manage_command(this, "load-conn", load_conn, reg);
     manage_command(this, "unload-conn", unload_conn, reg);
     manage_command(this, "get-conns", get_conns, reg);
 }
static void merge_config (private_vici_config_t * this, peer_cfg_t * peer_cfg) static
Merge/replace a peer config with existing configs
Definition at line 1753 of file vici_config.c.
References clear_start_actions(), DBG1, DBG_CFG, enumerator_t::destroy, peer_cfg_t::destroy, enumerator_t::enumerate, ike_cfg_t::equals, peer_cfg_t::equals, FALSE, peer_cfg_t::get_ike_cfg, peer_cfg_t::get_name, lock, replace_children(), run_start_actions(), streq(), TRUE, and spinlock_t::unlock.
Referenced by CALLBACK().
 {
     enumerator_t *enumerator;
     peer_cfg_t *current;
     ike_cfg_t *ike_cfg;
     bool merged = FALSE;
     this->lock->write_lock(this->lock);
     enumerator = this->conns->create_enumerator(this->conns);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (streq(peer_cfg->get_name(peer_cfg), current->get_name(current)))
         {
             ike_cfg = current->get_ike_cfg(current);
             if (peer_cfg->equals(peer_cfg, current) &&
                 ike_cfg->equals(ike_cfg, peer_cfg->get_ike_cfg(peer_cfg)))
             {
                 DBG1(DBG_CFG, "updated vici connection: %s",
                      peer_cfg->get_name(peer_cfg));
                 replace_children(this, peer_cfg, current);
                 peer_cfg->destroy(peer_cfg);
             }
             else
             {
                 DBG1(DBG_CFG, "replaced vici connection: %s",
                      peer_cfg->get_name(peer_cfg));
                 this->conns->remove_at(this->conns, enumerator);
                 clear_start_actions(this, current);
                 current->destroy(current);
                 this->conns->insert_last(this->conns, peer_cfg);
                 run_start_actions(this, peer_cfg);
             }
             merged = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!merged)
     {
         DBG1(DBG_CFG, "added vici connection: %s", peer_cfg->get_name(peer_cfg));
         this->conns->insert_last(this->conns, peer_cfg);
         run_start_actions(this, peer_cfg);
     }
     this->lock->unlock(this->lock);
 }
METHOD (backend_t , create_peer_cfg_enumerator , enumerator_t * , private_vici_config_t * this, identification_t * me, identification_t * other)
Definition at line 107 of file vici_config.c.
References enumerator_create_cleaner(), lock, and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_cleaner(this->conns->create_enumerator(this->conns),
                                      (void*)this->lock->unlock, this->lock);
 }
METHOD (backend_t , create_ike_cfg_enumerator , enumerator_t * , private_vici_config_t * this, host_t * me, host_t * other)
Definition at line 124 of file vici_config.c.
References enumerator_create_filter(), ike_filter(), lock, and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(this->conns->create_enumerator(this->conns),
                                     (void*)ike_filter, this->lock,
                                     (void*)this->lock->unlock);
 }
METHOD (backend_t , get_peer_cfg_by_name , peer_cfg_t * , private_vici_config_t * this, char * name)
Definition at line 133 of file vici_config.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, peer_cfg_t::get_name, peer_cfg_t::get_ref, lock, name, streq(), and spinlock_t::unlock.
 {
     peer_cfg_t *current, *found = NULL;
     enumerator_t *enumerator;
     this->lock->read_lock(this->lock);
     enumerator = this->conns->create_enumerator(this->conns);
     while (enumerator->enumerate(enumerator, &current))
     {
         if (streq(current->get_name(current), name))
         {
             found = current;
             found->get_ref(found);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (vici_config_t , destroy , void , private_vici_config_t * this)
Definition at line 2064 of file vici_config.c.
References spinlock_t::destroy, destroy(), FALSE, free(), lock, and manage_commands().
 {
     manage_commands(this, FALSE);
     this->conns->destroy_offset(this->conns, offsetof(peer_cfg_t, destroy));
     this->lock->destroy(this->lock);
     free(this);
 }
static bool parse_cert (auth_data_t * auth, auth_rule_t rule, chunk_t v) static
Parse a certificate; add as auth rule to config
Definition at line 1053 of file vici_config.c.
References auth_cfg_t::add, AUTH_RULE_SUBJECT_CERT, BUILD_BLOB_PEM, BUILD_END, cert, CERT_X509, auth_data_t::cfg, vici_authority_t::check_for_hash_and_url, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, FALSE, lib, auth_data_t::request, request_data_t::this, and TRUE.
Referenced by CALLBACK().
 {
     vici_authority_t *authority;
     certificate_t *cert;
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_BLOB_PEM, v, BUILD_END);
     if (cert)
     {
         if (rule == AUTH_RULE_SUBJECT_CERT)
         {
             authority = auth->request->this->authority;
             authority->check_for_hash_and_url(authority, cert);
         }
         auth->cfg->add(auth->cfg, rule, cert);
         return TRUE;
     }
     return FALSE;
 }
static bool parse_id (auth_cfg_t * cfg, auth_rule_t rule, chunk_t v) static
Parse identity; add as auth rule to config
Definition at line 993 of file vici_config.c.
References auth_cfg_t::add, FALSE, identification_create_from_string(), TRUE, and vici_stringify().
Referenced by CALLBACK().
 {
     char buf[256];
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     cfg->add(cfg, rule, identification_create_from_string(buf));
     return TRUE;
 }
static bool parse_map (enum_map_t * map, int count, int * out, chunk_t v) static
Parse a string to an integer mapping
Definition at line 675 of file vici_config.c.
References count, enum_map_t::d, FALSE, str, strcaseeq(), TRUE, and vici_stringify().
Referenced by CALLBACK().
 {
     char buf[128];
     int i;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     for (i = 0; i < count; i++)
     {
         if (strcaseeq(map[i].str, buf))
         {
             *out = map[i].d;
             return TRUE;
         }
     }
     return FALSE;
 }
static bool parse_proposal (linked_list_t * list, protocol_id_t proto, chunk_t v) static
Common proposal parsing
Definition at line 474 of file vici_config.c.
References FALSE, linked_list_t::insert_last, proposal, proposal_create_default(), proposal_create_default_aead(), proposal_create_from_string(), strcaseeq(), TRUE, and vici_stringify().
Referenced by CALLBACK().
 {
     char buf[128];
     proposal_t *proposal;
     if (!vici_stringify(v, buf, sizeof(buf)))
     {
         return FALSE;
     }
     if (strcaseeq("default", buf))
     {
         proposal = proposal_create_default(proto);
         if (proposal)
         {
             list->insert_last(list, proposal);
         }
         proposal = proposal_create_default_aead(proto);
         if (proposal)
         {
             list->insert_last(list, proposal);
         }
         return TRUE;
     }
     proposal = proposal_create_from_string(proto, buf);
     if (proposal)
     {
         list->insert_last(list, proposal);
         return TRUE;
     }
     return FALSE;
 }
static bool parse_rules (parse_rule_t * rules, int count, char * name, chunk_t value, vici_message_t ** reply) static
Parse key/values using a rule-set
Definition at line 190 of file vici_config.c.
References count, create_reply(), FALSE, out, parse(), streq(), and TRUE.
Referenced by CALLBACK().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         if (streq(name, rules[i].name))
         {
             if (rules[i].parse(rules[i].out, value))
             {
                 return TRUE;
             }
             *reply = create_reply("invalid value for: %s, config discarded",
                                   name);
             return FALSE;
         }
     }
     *reply = create_reply("unknown option: %s, config discarded", name);
     return FALSE;
 }
static void replace_children (private_vici_config_t * this, peer_cfg_t * from, peer_cfg_t * to) static
Replace children of a peer config by a new config
Definition at line 1725 of file vici_config.c.
References peer_cfg_t::add_child_cfg, clear_start_action(), peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, child_cfg_t::destroy, enumerator_t::enumerate, peer_cfg_t::remove_child_cfg, and run_start_action().
Referenced by merge_config().
 {
     enumerator_t *enumerator;
     child_cfg_t *child;
     enumerator = to->create_child_cfg_enumerator(to);
     while (enumerator->enumerate(enumerator, &child))
     {
         to->remove_child_cfg(to, enumerator);
         clear_start_action(this, child);
         child->destroy(child);
     }
     enumerator->destroy(enumerator);
     enumerator = from->create_child_cfg_enumerator(from);
     while (enumerator->enumerate(enumerator, &child))
     {
         from->remove_child_cfg(from, enumerator);
         to->add_child_cfg(to, child);
         run_start_action(this, to, child);
     }
     enumerator->destroy(enumerator);
 }
static void run_start_action (private_vici_config_t * this, peer_cfg_t * peer_cfg, child_cfg_t * child_cfg) static
Perform start actions associated to a child config
Definition at line 1583 of file vici_config.c.
References ACTION_RESTART, ACTION_ROUTE, charon, daemon_t::controller, DBG1, DBG_CFG, FALSE, find_reqid(), child_cfg_t::get_mode, child_cfg_t::get_name, child_cfg_t::get_ref, peer_cfg_t::get_ref, child_cfg_t::get_start_action, controller_t::initiate, shunt_manager_t::install, trap_manager_t::install, MODE_DROP, MODE_PASS, daemon_t::shunts, and daemon_t::traps.
Referenced by replace_children(), and run_start_actions().
 {
     switch (child_cfg->get_start_action(child_cfg))
     {
         case ACTION_RESTART:
             DBG1(DBG_CFG, "initiating '%s'", child_cfg->get_name(child_cfg));
             charon->controller->initiate(charon->controller,
                     peer_cfg->get_ref(peer_cfg), child_cfg->get_ref(child_cfg),
                     NULL, NULL, 0, FALSE);
             break;
         case ACTION_ROUTE:
             DBG1(DBG_CFG, "installing '%s'", child_cfg->get_name(child_cfg));
             switch (child_cfg->get_mode(child_cfg))
             {
                 case MODE_PASS:
                 case MODE_DROP:
                     charon->shunts->install(charon->shunts, child_cfg);
                     break;
                 default:
                     charon->traps->install(charon->traps, peer_cfg, child_cfg,
                                            find_reqid(child_cfg));
                     break;
             }
             break;
         default:
             break;
     }
 }
static void run_start_actions (private_vici_config_t * this, peer_cfg_t * peer_cfg) static
Run start actions associated to all child configs of a peer config
Definition at line 1692 of file vici_config.c.
References peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, and run_start_action().
Referenced by merge_config().
 {
     enumerator_t *enumerator;
     child_cfg_t *child_cfg;
     enumerator = peer_cfg->create_child_cfg_enumerator(peer_cfg);
     while (enumerator->enumerate(enumerator, &child_cfg))
     {
         run_start_action(this, peer_cfg, child_cfg);
     }
     enumerator->destroy(enumerator);
 }