strongSwan: integrity_checker.c File Reference
integrity_checker.c File Reference
#include "integrity_checker.h"
#include <dlfcn.h>
#include <link.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include "debug.h"
#include "library.h"
Classes
struct private_integrity_checker_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_integrity_checker_t private_integrity_checker_t
Functions
METHOD (integrity_checker_t, build_file, u_int32_t, private_integrity_checker_t *this, char *file, size_t *len)
static int callback (struct dl_phdr_info *dlpi, size_t size, Dl_info *dli)
METHOD (integrity_checker_t, build_segment, u_int32_t, private_integrity_checker_t *this, void *sym, size_t *len)
static integrity_checksum_t * find_checksum (private_integrity_checker_t *this, char *name)
METHOD (integrity_checker_t, check_file, bool, private_integrity_checker_t *this, char *name, char *file)
METHOD (integrity_checker_t, check_segment, bool, private_integrity_checker_t *this, char *name, void *sym)
METHOD (integrity_checker_t, check, bool, private_integrity_checker_t *this, char *name, void *sym)
METHOD (integrity_checker_t, destroy, void, private_integrity_checker_t *this)
integrity_checker_t * integrity_checker_create (char *checksum_library)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file integrity_checker.c.
Typedef Documentation
typedef struct private_integrity_checker_t private_integrity_checker_t
Definition at line 31 of file integrity_checker.c.
Function Documentation
static int callback (struct dl_phdr_info * dlpi, size_t size, Dl_info * dli) static
dl_iterate_phdr callback function
Definition at line 81 of file integrity_checker.c.
Referenced by METHOD().
 {
     /* We are looking for the dlpi_addr matching the address of our dladdr().
      * dl_iterate_phdr() returns such an address for other (unknown) objects
      * in very rare cases (e.g. in a chrooted gentoo, but only if
      * the checksum_builder is invoked by 'make'). As a workaround, we filter
      * objects by dlpi_name; valid objects have a library name.
      */
     if (dli->dli_fbase == (void*)dlpi->dlpi_addr &&
         dlpi->dlpi_name && *dlpi->dlpi_name)
     {
         int i;
         for (i = 0; i < dlpi->dlpi_phnum; i++)
         {
             const ElfW(Phdr) *sgmt = &dlpi->dlpi_phdr[i];
             /* we are interested in the executable LOAD segment */
             if (sgmt->p_type == PT_LOAD && (sgmt->p_flags & PF_X))
             {
                 /* safe begin of segment in dli_fbase */
                 dli->dli_fbase = (void*)sgmt->p_vaddr + dlpi->dlpi_addr;
                 /* safe end of segment in dli_saddr */
                 dli->dli_saddr = dli->dli_fbase + sgmt->p_memsz;
                 return 1;
             }
         }
     }
     return 0;
 }
static integrity_checksum_t* find_checksum (private_integrity_checker_t * this, char * name) static
Find a checksum by its name
Definition at line 138 of file integrity_checker.c.
References streq().
Referenced by METHOD().
 {
     int i;
     for (i = 0; i < this->checksum_count; i++)
     {
         if (streq(this->checksums[i].name, name))
         {
             return &this->checksums[i];
         }
     }
     return NULL;
 }
METHOD (integrity_checker_t , build_file , u_int32_t , private_integrity_checker_t * this, char * file, size_t * len)
Definition at line 59 of file integrity_checker.c.
References chunk_hash_static(), chunk_map(), chunk_unmap(), DBG1, DBG_LIB, FALSE, chunk_t::len, and strerror.
 {
     u_int32_t checksum;
     chunk_t *contents;
     contents = chunk_map(file, FALSE);
     if (!contents)
     {
         DBG1(DBG_LIB, "  opening '%s' failed: %s", file, strerror(errno));
         return 0;
     }
     *len = contents->len;
     checksum = chunk_hash_static(*contents);
     chunk_unmap(contents);
     return checksum;
 }
METHOD (integrity_checker_t , build_segment , u_int32_t , private_integrity_checker_t * this, void * sym, size_t * len)
Definition at line 112 of file integrity_checker.c.
References callback(), chunk_create(), chunk_hash_static(), DBG1, DBG_LIB, dlerror(), chunk_t::len, and segment.
 {
     chunk_t segment;
     Dl_info dli;
     if (dladdr(sym, &dli) == 0)
     {
         DBG1(DBG_LIB, "  unable to locate symbol: %s", dlerror());
         return 0;
     }
     /* we reuse the Dl_info struct as in/out parameter */
     if (!dl_iterate_phdr((void*)callback, &dli))
     {
         DBG1(DBG_LIB, "  executable section not found");
         return 0;
     }
     segment = chunk_create(dli.dli_fbase, dli.dli_saddr - dli.dli_fbase);
     *len = segment.len;
     return chunk_hash_static(segment);
 }
METHOD (integrity_checker_t , check_file , bool , private_integrity_checker_t * this, char * name, char * file)
Definition at line 153 of file integrity_checker.c.
References DBG1, DBG2, DBG_LIB, FALSE, integrity_checksum_t::file, integrity_checksum_t::file_len, find_checksum(), len, and TRUE.
 {
     integrity_checksum_t *cs;
     u_int32_t sum;
     size_t len = 0;
     cs = find_checksum(this, name);
     if (!cs)
     {
         DBG1(DBG_LIB, "  '%s' file checksum not found", name);
         return FALSE;
     }
     sum = build_file(this, file, &len);
     if (!sum)
     {
         return FALSE;
     }
     if (cs->file_len != len)
     {
         DBG1(DBG_LIB, "  invalid '%s' file size: %u bytes, expected %u bytes",
              name, len, cs->file_len);
         return FALSE;
     }
     if (cs->file != sum)
     {
         DBG1(DBG_LIB, "  invalid '%s' file checksum: %08x, expected %08x",
              name, sum, cs->file);
         return FALSE;
     }
     DBG2(DBG_LIB, "  valid '%s' file checksum: %08x", name, sum);
     return TRUE;
 }
METHOD (integrity_checker_t , check_segment , bool , private_integrity_checker_t * this, char * name, void * sym)
Definition at line 187 of file integrity_checker.c.
References DBG1, DBG2, DBG_LIB, FALSE, find_checksum(), len, integrity_checksum_t::segment, integrity_checksum_t::segment_len, and TRUE.
 {
     integrity_checksum_t *cs;
     u_int32_t sum;
     size_t len = 0;
     cs = find_checksum(this, name);
     if (!cs)
     {
         DBG1(DBG_LIB, "  '%s' segment checksum not found", name);
         return FALSE;
     }
     sum = build_segment(this, sym, &len);
     if (!sum)
     {
         return FALSE;
     }
     if (cs->segment_len != len)
     {
         DBG1(DBG_LIB, "  invalid '%s' segment size: %u bytes,"
              " expected %u bytes", name, len, cs->segment_len);
         return FALSE;
     }
     if (cs->segment != sum)
     {
         DBG1(DBG_LIB, "  invalid '%s' segment checksum: %08x, expected %08x",
              name, sum, cs->segment);
         return FALSE;
     }
     DBG2(DBG_LIB, "  valid '%s' segment checksum: %08x", name, sum);
     return TRUE;
 }
METHOD (integrity_checker_t , check , bool , private_integrity_checker_t * this, char * name, void * sym)
Definition at line 221 of file integrity_checker.c.
References DBG1, DBG_LIB, dlerror(), FALSE, and TRUE.
 {
     Dl_info dli;
     if (dladdr(sym, &dli) == 0)
     {
         DBG1(DBG_LIB, "unable to locate symbol: %s", dlerror());
         return FALSE;
     }
     if (!check_file(this, name, (char*)dli.dli_fname))
     {
         return FALSE;
     }
     if (!check_segment(this, name, sym))
     {
         return FALSE;
     }
     return TRUE;
 }
METHOD (integrity_checker_t , destroy , void , private_integrity_checker_t * this)
Definition at line 242 of file integrity_checker.c.
References dlclose(), free(), and handle.
 {
     if (this->handle)
     {
         dlclose(this->handle);
     }
     free(this);
 }