strongSwan: ietf_attr_pa_tnc_error
ietf_attr_pa_tnc_error
ietf_attr
Classes
struct ietf_attr_pa_tnc_error_t
Typedefs
typedef struct
ietf_attr_pa_tnc_error_t ietf_attr_pa_tnc_error_t
typedef enum pa_tnc_error_code_t pa_tnc_error_code_t
Enumerations
enum pa_tnc_error_code_t { PA_ERROR_RESERVED = 0, PA_ERROR_INVALID_PARAMETER = 1, PA_ERROR_VERSION_NOT_SUPPORTED = 2, PA_ERROR_ATTR_TYPE_NOT_SUPPORTED = 3 }
Functions
pa_tnc_attr_t * ietf_attr_pa_tnc_error_create (pen_type_t error_code, chunk_t header)
pa_tnc_attr_t * ietf_attr_pa_tnc_error_create_with_offset (pen_type_t error_code, chunk_t header, uint32_t error_offset)
pa_tnc_attr_t * ietf_attr_pa_tnc_error_create_from_data (size_t length, chunk_t value)
Variables
enum_name_t * pa_tnc_error_code_names
Detailed Description
Typedef Documentation
typedef struct ietf_attr_pa_tnc_error_t ietf_attr_pa_tnc_error_t
Definition at line 24 of file ietf_attr_pa_tnc_error.h.
typedef enum pa_tnc_error_code_t pa_tnc_error_code_t
Definition at line 25 of file ietf_attr_pa_tnc_error.h.
Enumeration Type Documentation
enum pa_tnc_error_code_t
IETF Standard PA-TNC Error Codes as defined in section 4.2.8 of RFC 5792
Enumerator
PA_ERROR_RESERVED
PA_ERROR_INVALID_PARAMETER
PA_ERROR_VERSION_NOT_SUPPORTED
PA_ERROR_ATTR_TYPE_NOT_SUPPORTED
Definition at line 34 of file ietf_attr_pa_tnc_error.h.
{
     PA_ERROR_RESERVED =                 0,
     PA_ERROR_INVALID_PARAMETER =        1,
     PA_ERROR_VERSION_NOT_SUPPORTED =    2,
     PA_ERROR_ATTR_TYPE_NOT_SUPPORTED =  3,
 };
Function Documentation
pa_tnc_attr_t* ietf_attr_pa_tnc_error_create (pen_type_t error_code, chunk_t msg_info)
Creates an ietf_attr_pa_tnc_error_t object from an error code
Parameters
error_code Vendor-specific PA-TNC error code
header PA-TNC message header (first 8 bytes)
Described in header.
Definition at line 394 of file ietf_attr_pa_tnc_error.c.
References chunk_clone, create_generic(), error_code, chunk_t::len, PA_ERROR_MSG_INFO_MAX_SIZE, PA_ERROR_MSG_INFO_SIZE, PEN_IETF, and pen_type_t::vendor_id.
Referenced by imc_attestation_process(), METHOD(), pts_dh_group_error_create(), pts_dh_nonce_error_create(), pts_hash_alg_error_create(), and swid_error_create().
 {
     private_ietf_attr_pa_tnc_error_t *this;
     if (error_code.vendor_id == PEN_IETF)
     {
         msg_info.len = PA_ERROR_MSG_INFO_SIZE;
     }
     else if (msg_info.len > PA_ERROR_MSG_INFO_MAX_SIZE)
     {
         msg_info.len = PA_ERROR_MSG_INFO_MAX_SIZE;
     }
     this = create_generic();
     this->error_code = error_code;
     this->msg_info = chunk_clone(msg_info);
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ietf_attr_pa_tnc_error_create_from_data (size_t length, chunk_t data)
Creates an ietf_attr_pa_tnc_error_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 438 of file ietf_attr_pa_tnc_error.c.
References chunk_clone, create_generic(), length, and value.
Referenced by ietf_attr_create_from_data().
 {
     private_ietf_attr_pa_tnc_error_t *this;
     this = create_generic();
     this->length = length;
     this->value = chunk_clone(data);
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ietf_attr_pa_tnc_error_create_with_offset (pen_type_t error_code, chunk_t msg_info, uint32_t error_offset)
Creates an ietf_attr_pa_tnc_error_t object from an error code with offset
Parameters
error_code Vendor-specifica PA-TNC error code
header PA-TNC message header (first 8 bytes)
error_offset PA-TNC error offset in bytes
Described in header.
Definition at line 418 of file ietf_attr_pa_tnc_error.c.
References chunk_clone, create_generic(), error_code, chunk_t::len, and PA_ERROR_MSG_INFO_SIZE.
Referenced by METHOD(), and seg_env_create_from_data().
 {
     private_ietf_attr_pa_tnc_error_t *this;
     /* the first 8 bytes of the erroneous PA-TNC message are sent back */
     msg_info.len = PA_ERROR_MSG_INFO_SIZE;
     this = create_generic();
     this->error_code = error_code;
     this->msg_info = chunk_clone(msg_info);
     this->error_offset = error_offset;
     return &this->public.pa_tnc_attribute;
 }
Variable Documentation
enum_name_t* pa_tnc_error_code_names
enum name for pa_tnc_error_code_t.
Referenced by METHOD().