strongSwan: eap_radius_forward.c File Reference
eap_radius_forward.c File Reference
#include "eap_radius_forward.h"
#include <daemon.h>
#include <collections/linked_list.h>
#include <collections/hashtable.h>
#include <threading/mutex.h>
Classes
struct private_eap_radius_forward_t
struct attr_t
Typedefs
typedef struct
private_eap_radius_forward_t private_eap_radius_forward_t
Functions
static void free_attribute (chunk_t *chunk)
static linked_list_t * lookup_queue (private_eap_radius_forward_t *this, hashtable_t *table)
static void remove_queue (private_eap_radius_forward_t *this, hashtable_t *table, ike_sa_t *ike_sa)
static bool is_attribute_selected (linked_list_t *selector, radius_attribute_type_t type, chunk_t data)
static void queue2radius (linked_list_t *queue, radius_message_t *message)
static void radius2queue (radius_message_t *message, linked_list_t *queue, linked_list_t *selector)
static void ike2queue (message_t *message, linked_list_t *queue, linked_list_t *selector)
static void queue2ike (linked_list_t *queue, message_t *message)
void eap_radius_forward_from_ike (radius_message_t *request)
void eap_radius_forward_to_ike (radius_message_t *response)
METHOD (listener_t, message, bool, private_eap_radius_forward_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (listener_t, ike_updown, bool, private_eap_radius_forward_t *this, ike_sa_t *ike_sa, bool up)
static linked_list_t * parse_selector (char *selector)
METHOD (eap_radius_forward_t, destroy, void, private_eap_radius_forward_t *this)
eap_radius_forward_t * eap_radius_forward_create ()
Variables
static
private_eap_radius_forward_t * singleton = NULL
Typedef Documentation
typedef struct private_eap_radius_forward_t private_eap_radius_forward_t
Definition at line 23 of file eap_radius_forward.c.
Function Documentation
static void free_attribute (chunk_t * chunk) static
Free a queue entry
Definition at line 79 of file eap_radius_forward.c.
References free(), and chunk_t::ptr.
Referenced by queue2ike(), queue2radius(), and remove_queue().
 {
     free(chunk->ptr);
     free(chunk);
 }
static void ike2queue (message_t * message, linked_list_t * queue, linked_list_t * selector) static
Copy RADIUS attribute nofifies from IKE message to queue
Definition at line 224 of file eap_radius_forward.c.
References chunk_clone, chunk_skip(), message_t::create_payload_enumerator, data, enumerator_t::destroy, enumerator_t::enumerate, notify_payload_t::get_notification_data, notify_payload_t::get_notify_type, payload_t::get_type, INIT, linked_list_t::insert_last, is_attribute_selected(), chunk_t::len, notify(), PLV1_NOTIFY, PLV2_NOTIFY, chunk_t::ptr, and RADIUS_ATTRIBUTE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     notify_payload_t *notify;
     chunk_t data, *ptr;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV2_NOTIFY ||
             payload->get_type(payload) == PLV1_NOTIFY)
         {
             notify = (notify_payload_t*)payload;
             if (notify->get_notify_type(notify) == RADIUS_ATTRIBUTE)
             {
                 data = notify->get_notification_data(notify);
                 if (data.len >= 2 && is_attribute_selected(selector,
                                         data.ptr[0], chunk_skip(data, 2)))
                 {
                     INIT(ptr);
                     *ptr = chunk_clone(data);
                     queue->insert_last(queue, ptr);
                 }
             }
         }
     }
     enumerator->destroy(enumerator);
 }
static bool is_attribute_selected (linked_list_t * selector, radius_attribute_type_t type, chunk_t data) static
Check if RADIUS attribute is contained in selector
Definition at line 131 of file eap_radius_forward.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, chunk_t::len, chunk_t::ptr, RAT_VENDOR_SPECIFIC, TRUE, attr_t::type, untoh32(), and attr_t::vendor.
Referenced by ike2queue(), and radius2queue().
 {
     enumerator_t *enumerator;
     u_int32_t vendor = 0;
     attr_t *sel;
     bool found = FALSE;
     if (type == RAT_VENDOR_SPECIFIC)
     {
         if (data.len < 4)
         {
             return FALSE;
         }
         vendor = untoh32(data.ptr);
     }
     enumerator = selector->create_enumerator(selector);
     while (!found && enumerator->enumerate(enumerator, &sel))
     {
         if (sel->vendor == vendor)
         {
             if (vendor)
             {
                 if (sel->type == 0)
                 {   /* any of that vendor is fine */
                     found = TRUE;
                 }
                 else if (data.len > 4 && data.ptr[4] == sel->type)
                 {   /* vendor specific type field, as defined in RFC 2865 */
                     found = TRUE;
                 }
             }
             else
             {
                 if (sel->type == type)
                 {
                     found = TRUE;
                 }
             }
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static linked_list_t* lookup_queue (private_eap_radius_forward_t * this, hashtable_t * table) static
Lookup/create an attribute queue from a table
Definition at line 88 of file eap_radius_forward.c.
References daemon_t::bus, charon, EXT_STRONGSWAN, hashtable_t::get, bus_t::get_sa, ike_sa_t::get_unique_id, id, linked_list_create(), mutex_t::lock, mutex, hashtable_t::put, queue(), ike_sa_t::supports_extension, and mutex_t::unlock.
Referenced by eap_radius_forward_from_ike(), eap_radius_forward_to_ike(), and METHOD().
 {
     linked_list_t *queue = NULL;
     ike_sa_t *ike_sa;
     uintptr_t id;
     ike_sa = charon->bus->get_sa(charon->bus);
     if (ike_sa && ike_sa->supports_extension(ike_sa, EXT_STRONGSWAN))
     {
         id = ike_sa->get_unique_id(ike_sa);
         this->mutex->lock(this->mutex);
         queue = table->get(table, (void*)id);
         if (!queue)
         {
             queue = linked_list_create();
             table->put(table, (void*)id, queue);
         }
         this->mutex->unlock(this->mutex);
     }
     return queue;
 }
METHOD (listener_t , message , bool , private_eap_radius_forward_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 305 of file eap_radius_forward.c.
References from, message_t::get_exchange_type, ike2queue(), IKE_AUTH, lookup_queue(), queue(), queue2ike(), to, and TRUE.
 {
     linked_list_t *queue;
     if (plain && message->get_exchange_type(message) == IKE_AUTH)
     {
         if (incoming)
         {
             queue = lookup_queue(this, this->from);
             if (queue)
             {
                 ike2queue(message, queue, this->from_attr);
             }
         }
         else
         {
             queue = lookup_queue(this, this->to);
             if (queue)
             {
                 queue2ike(queue, message);
             }
         }
     }
     return TRUE;
 }
METHOD (listener_t , ike_updown , bool , private_eap_radius_forward_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 333 of file eap_radius_forward.c.
References from, remove_queue(), to, and TRUE.
 {
     /* up or down, we don't need the state anymore */
     remove_queue(this, this->from, ike_sa);
     remove_queue(this, this->to, ike_sa);
     return TRUE;
 }
METHOD (eap_radius_forward_t , destroy , void , private_eap_radius_forward_t * this)
Definition at line 395 of file eap_radius_forward.c.
References mutex_t::destroy, free(), from, mutex, and to.
 {
     this->from_attr->destroy_function(this->from_attr, free);
     this->to_attr->destroy_function(this->to_attr, free);
     this->from->destroy(this->from);
     this->to->destroy(this->to);
     this->mutex->destroy(this->mutex);
     free(this);
     singleton = NULL;
 }
static linked_list_t* parse_selector (char * selector) static
Parse a selector string to a list of attr_t selectors
Definition at line 345 of file eap_radius_forward.c.
References DBG1, DBG_CFG, DBG_IKE, enumerator_t::destroy, enum_from_name, enumerator_t::enumerate, enumerator_create_token(), INIT, linked_list_t::insert_last, linked_list_create(), list, radius_attribute_type_names, and type.
Referenced by eap_radius_forward_create().
 {
     enumerator_t *enumerator;
     linked_list_t *list;
     char *token, *pos;
     list = linked_list_create();
     enumerator = enumerator_create_token(selector, ",", " ");
     while (enumerator->enumerate(enumerator, &token))
     {
         int type, vendor = 0;
         attr_t *attr;
         pos = strchr(token, ':');
         if (pos)
         {
             *(pos++) = 0;
             vendor = atoi(token);
             token = pos;
         }
         if (!enum_from_name(radius_attribute_type_names, token, &type))
         {
             type = atoi(token);
         }
         if (vendor == 0 && type == 0)
         {
             DBG1(DBG_CFG, "ignoring unknown RADIUS attribute type '%s'", token);
         }
         else
         {
             INIT(attr,
                 .type = type,
                 .vendor = vendor,
             );
             list->insert_last(list, attr);
             if (!vendor)
             {
                 DBG1(DBG_IKE, "forwarding RADIUS attribute %N",
                      radius_attribute_type_names, type);
             }
             else
             {
                 DBG1(DBG_IKE, "forwarding RADIUS VSA %d-%d", vendor, type);
             }
         }
     }
     enumerator->destroy(enumerator);
     return list;
 }
static void queue2ike (linked_list_t * queue, message_t * message) static
Copy RADUIS attributes from queue to IKE message notifies
Definition at line 258 of file eap_radius_forward.c.
References message_t::add_notify, data, FALSE, free_attribute(), RADIUS_ATTRIBUTE, linked_list_t::remove_last, and SUCCESS.
Referenced by METHOD().
 {
     chunk_t *data;
     while (queue->remove_last(queue, (void**)&data) == SUCCESS)
     {
         message->add_notify(message, FALSE, RADIUS_ATTRIBUTE, *data);
         free_attribute(data);
     }
 }
static void queue2radius (linked_list_t * queue, radius_message_t * message) static
Copy RADIUS attributes from queue to a RADIUS message
Definition at line 180 of file eap_radius_forward.c.
References radius_message_t::add, chunk_skip(), data, free_attribute(), chunk_t::len, chunk_t::ptr, linked_list_t::remove_last, and SUCCESS.
Referenced by eap_radius_forward_from_ike().
 {
     chunk_t *data;
     while (queue->remove_last(queue, (void**)&data) == SUCCESS)
     {
         if (data->len >= 2)
         {
             message->add(message, data->ptr[0], chunk_skip(*data, 2));
         }
         free_attribute(data);
     }
 }
static void radius2queue (radius_message_t * message, linked_list_t * queue, linked_list_t * selector) static
Copy RADIUS attributes from a RADIUS message to the queue
Definition at line 197 of file eap_radius_forward.c.
References chunk_alloc, chunk_cat, radius_message_t::create_enumerator, data, enumerator_t::destroy, enumerator_t::enumerate, INIT, linked_list_t::insert_last, is_attribute_selected(), chunk_t::len, chunk_t::ptr, and type.
Referenced by eap_radius_forward_to_ike().
 {
     enumerator_t *enumerator;
     int type;
     chunk_t data, hdr, *ptr;
     enumerator = message->create_enumerator(message);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (is_attribute_selected(selector, type, data))
         {
             hdr = chunk_alloc(2);
             hdr.ptr[0] = type;
             hdr.ptr[1] = data.len + 2;
             INIT(ptr);
             *ptr = chunk_cat("mc", hdr, data);
             queue->insert_last(queue, ptr);
         }
     }
     enumerator->destroy(enumerator);
 }
static void remove_queue (private_eap_radius_forward_t * this, hashtable_t * table, ike_sa_t * ike_sa) static
Remove attribute queue from table
Definition at line 114 of file eap_radius_forward.c.
References linked_list_t::destroy_function, free_attribute(), ike_sa_t::get_unique_id, mutex_t::lock, mutex, queue(), hashtable_t::remove, and mutex_t::unlock.
Referenced by METHOD().
 {
     linked_list_t *queue;
     this->mutex->lock(this->mutex);
     queue = table->remove(table, (void*)(uintptr_t)ike_sa->get_unique_id(ike_sa));
     this->mutex->unlock(this->mutex);
     if (queue)
     {
         queue->destroy_function(queue, (void*)free_attribute);
     }
 }
Variable Documentation
private_eap_radius_forward_t* singleton = NULL static
Single instance of this
Definition at line 74 of file eap_radius_forward.c.
Referenced by eap_radius_forward_from_ike(), and eap_radius_forward_to_ike().