strongSwan: payload_t Struct Reference
payload_t Struct Reference
payload
#include "payload.h"
Public Attributes
int(* get_encoding_rules)(payload_t *this, encoding_rule_t **rules)
int(* get_header_length)(payload_t *this)
payload_type_t(* get_type)(payload_t *this)
payload_type_t(* get_next_type)(payload_t *this)
void(* set_next_type)(payload_t *this, payload_type_t type)
size_t(* get_length)(payload_t *this)
status_t(* verify)(payload_t *this)
void(* destroy)(payload_t *this)
Detailed Description
Generic interface for all payload types (incl.header and substructures).
To handle all kinds of payloads on a generic way, this interface must be implemented by every payload. This allows parser_t/generator_t a simple handling of all payloads.
Definition at line 339 of file payload.h.
Member Data Documentation
void(* payload_t::destroy)(payload_t *this)
Destroys a payload and all included substructures.
Definition at line 394 of file payload.h.
Referenced by METHOD(), parse(), parse_payloads(), process_auth_request(), process_auth_response(), and rebuild_auth().
int(* payload_t::get_encoding_rules)(payload_t *this, encoding_rule_t **rules)
Get encoding rules for this payload.
Parameters
rules location to store pointer to rules
Returns
number of rules
Definition at line 347 of file payload.h.
Referenced by METHOD(), and payload_get_field().
int(* payload_t::get_header_length)(payload_t *this)
Get non-variable header length for a variable length payload.
Returns
fixed length of the payload
Definition at line 354 of file payload.h.
Referenced by METHOD().
size_t(* payload_t::get_length)(payload_t *this)
Get length of payload.
Returns
length of this payload
Definition at line 382 of file payload.h.
Referenced by calculate_wire_size(), compute_length(), and METHOD().
payload_type_t(* payload_t::get_next_type)(payload_t *this)
Get type of next payload or PL_NONE (0) if this is the last one.
Returns
type of next payload
Definition at line 368 of file payload.h.
Referenced by METHOD(), parse(), and parse_payloads().
payload_type_t(* payload_t::get_type)(payload_t *this)
Get type of payload.
Returns
type of this payload
Definition at line 361 of file payload.h.
Referenced by create_fragment(), decrypt_and_extract(), decrypt_payloads(), generate(), generate_message(), get_message_data(), get_string(), get_ts(), has_notify_errors(), ike2queue(), is_connectivity_check(), METHOD(), order_payloads(), parse(), parse_message(), parse_payloads(), print_radius_attributes(), process(), process_auth_response(), process_certreqs(), process_certs(), process_payloads(), process_request(), rebuild_auth(), set_bit(), set_byte(), use_certs(), verify(), and wrap_payloads().
void(* payload_t::set_next_type)(payload_t *this, payload_type_t type)
Set type of next payload.
Parameters
type type of next payload
Definition at line 375 of file payload.h.
Referenced by create_fragment(), decrypt_and_extract(), generate(), generate_message(), get_message_data(), METHOD(), and parse_payloads().
status_t(* payload_t::verify)(payload_t *this)
Verifies payload structure and makes consistence check.
Returns
SUCCESS, FAILED if consistence not given
Definition at line 389 of file payload.h.
Referenced by METHOD(), parse(), and parse_payloads().
The documentation for this struct was generated from the following file:
payload.h