strongSwan: eap_ttls_plugin.c File Reference
eap_ttls_plugin.c File Reference
#include "eap_ttls_plugin.h"
#include "eap_ttls.h"
#include <daemon.h>
Functions
METHOD (plugin_t, get_name, char *, eap_ttls_plugin_t *this)
METHOD (plugin_t, get_features, int, eap_ttls_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, eap_ttls_plugin_t *this)
plugin_t * eap_ttls_plugin_create ()
Function Documentation
plugin_t* eap_ttls_plugin_create ()
Definition at line 59 of file eap_ttls_plugin.c.
References INIT, and plugin.
 {
     eap_ttls_plugin_t *this;
     INIT(this,
         .plugin = {
             .get_name = _get_name,
             .get_features = _get_features,
             .destroy = _destroy,
         },
     );
     return &this->plugin;
 }
METHOD (plugin_t , get_name , char * , eap_ttls_plugin_t * this)
Definition at line 22 of file eap_ttls_plugin.c.
 {
     return "eap-ttls";
 }
METHOD (plugin_t , get_features , int , eap_ttls_plugin_t * this, plugin_feature_t * features[])
Definition at line 28 of file eap_ttls_plugin.c.
References countof, EAP_IDENTITY, eap_method_register(), EAP_PEER, EAP_SERVER, EAP_TTLS, eap_ttls_create_peer(), eap_ttls_create_server(), HASH_MD5, HASH_SHA1, PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, RNG_STRONG, and RNG_WEAK.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(eap_method_register, eap_ttls_create_server),
             PLUGIN_PROVIDE(EAP_SERVER, EAP_TTLS),
                 PLUGIN_DEPENDS(EAP_SERVER, EAP_IDENTITY),
                 PLUGIN_DEPENDS(HASHER, HASH_MD5),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
         PLUGIN_CALLBACK(eap_method_register, eap_ttls_create_peer),
             PLUGIN_PROVIDE(EAP_PEER, EAP_TTLS),
                 PLUGIN_DEPENDS(EAP_PEER, EAP_IDENTITY),
                 PLUGIN_DEPENDS(HASHER, HASH_MD5),
                 PLUGIN_DEPENDS(HASHER, HASH_SHA1),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
                 PLUGIN_DEPENDS(RNG, RNG_STRONG),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , eap_ttls_plugin_t * this)
Definition at line 50 of file eap_ttls_plugin.c.
References free().
 {
     free(this);
 }