strongSwan: sasl_plain.c File Reference
sasl_plain.c File Reference
#include "sasl_plain.h"
#include <utils/debug.h>
Classes
struct private_sasl_plain_t
Typedefs
typedef struct private_sasl_plain_t private_sasl_plain_t
Functions
METHOD (sasl_mechanism_t, get_client, identification_t *, private_sasl_plain_t *this)
METHOD (sasl_mechanism_t, get_name, char *, private_sasl_plain_t *this)
METHOD (sasl_mechanism_t, build_server, status_t, private_sasl_plain_t *this, chunk_t *message)
METHOD (sasl_mechanism_t, process_server, status_t, private_sasl_plain_t *this, chunk_t message)
METHOD (sasl_mechanism_t, build_client, status_t, private_sasl_plain_t *this, chunk_t *message)
METHOD (sasl_mechanism_t, process_client, status_t, private_sasl_plain_t *this, chunk_t message)
METHOD (sasl_mechanism_t, destroy, void, private_sasl_plain_t *this)
sasl_plain_t * sasl_plain_create (char *name, identification_t *client)
Typedef Documentation
typedef struct private_sasl_plain_t private_sasl_plain_t
Definition at line 20 of file sasl_plain.c.
Function Documentation
METHOD (sasl_mechanism_t , get_client , identification_t * , private_sasl_plain_t * this)
Definition at line 38 of file sasl_plain.c.
References client().
 {
     return this->client;
 }
METHOD (sasl_mechanism_t , get_name , char * , private_sasl_plain_t * this)
Definition at line 44 of file sasl_plain.c.
 {
     return "PLAIN";
 }
METHOD (sasl_mechanism_t , build_server , status_t , private_sasl_plain_t * this, chunk_t * message)
Definition at line 50 of file sasl_plain.c.
References FAILED.
 {
     /* gets never called */
     return FAILED;
 }
METHOD (sasl_mechanism_t , process_server , status_t , private_sasl_plain_t * this, chunk_t message)
Definition at line 57 of file sasl_plain.c.
References chunk_create(), chunk_equals_const(), chunk_skip(), client(), library_t::credmgr, DBG1, DBG_CFG, shared_key_t::destroy, DESTROY_IF, FAILED, shared_key_t::get_key, credential_manager_t::get_shared, identification_create_from_data(), chunk_t::len, lib, chunk_t::ptr, SHARED_EAP, and SUCCESS.
 {
     chunk_t authz, authi, password;
     shared_key_t *shared;
     u_char *pos;
     pos = memchr(message.ptr, 0, message.len);
     if (!pos)
     {
         DBG1(DBG_CFG, "invalid authz encoding");
         return FAILED;
     }
     authz = chunk_create(message.ptr, pos - message.ptr);
     message = chunk_skip(message, authz.len + 1);
     pos = memchr(message.ptr, 0, message.len);
     if (!pos)
     {
         DBG1(DBG_CFG, "invalid authi encoding");
         return FAILED;
     }
     authi = chunk_create(message.ptr, pos - message.ptr);
     password = chunk_skip(message, authi.len + 1);
     DESTROY_IF(this->client);
     this->client = identification_create_from_data(authi);
     shared = lib->credmgr->get_shared(lib->credmgr, SHARED_EAP, this->client,
                                       NULL);
     if (!shared)
     {
         DBG1(DBG_CFG, "no shared secret found for '%Y'", this->client);
         return FAILED;
     }
     if (!chunk_equals_const(shared->get_key(shared), password))
     {
         DBG1(DBG_CFG, "shared secret for '%Y' does not match", this->client);
         shared->destroy(shared);
         return FAILED;
     }
     shared->destroy(shared);
     return SUCCESS;
 }
METHOD (sasl_mechanism_t , build_client , status_t , private_sasl_plain_t * this, chunk_t * message)
Definition at line 99 of file sasl_plain.c.
References chunk_clone, chunk_create(), client(), library_t::credmgr, DBG1, DBG_CFG, shared_key_t::destroy, FAILED, shared_key_t::get_key, credential_manager_t::get_shared, chunk_t::len, len, lib, NEED_MORE, chunk_t::ptr, SHARED_EAP, and snprintf.
 {
     shared_key_t *shared;
     chunk_t password;
     char buf[256];
     ssize_t len;
     /* we currently use the EAP type of shared secret */
     shared = lib->credmgr->get_shared(lib->credmgr, SHARED_EAP,
                                       this->client, NULL);
     if (!shared)
     {
         DBG1(DBG_CFG, "no shared secret found for %Y", this->client);
         return FAILED;
     }
     password = shared->get_key(shared);
     len = snprintf(buf, sizeof(buf), "%s%c%Y%c%.*s",
                    "", 0, this->client, 0,
                    (int)password.len, password.ptr);
     shared->destroy(shared);
     if (len < 0 || len >= sizeof(buf))
     {
         return FAILED;
     }
     *message = chunk_clone(chunk_create(buf, len));
     return NEED_MORE;
 }
METHOD (sasl_mechanism_t , process_client , status_t , private_sasl_plain_t * this, chunk_t message)
Definition at line 131 of file sasl_plain.c.
References SUCCESS.
 {
     /* if the server sends a result, authentication successful */
     return SUCCESS;
 }
METHOD (sasl_mechanism_t , destroy , void , private_sasl_plain_t * this)
Definition at line 138 of file sasl_plain.c.
References client(), DESTROY_IF, and free().
 {
     DESTROY_IF(this->client);
     free(this);
 }