strongSwan: child_delete
child_delete
tasks
Classes
struct child_delete_t
Typedefs
typedef struct child_delete_t child_delete_t
Functions
child_delete_t * child_delete_create (ike_sa_t *ike_sa, protocol_id_t protocol, u_int32_t spi, bool expired)
Detailed Description
Typedef Documentation
typedef struct child_delete_t child_delete_t
Definition at line 24 of file child_delete.h.
Function Documentation
child_delete_t* child_delete_create (ike_sa_t * ike_sa, protocol_id_t protocol, u_int32_t spi, bool expired)
Create a new child_delete task.
Parameters
ike_sa IKE_SA this task works for
protocol protocol of CHILD_SA to delete, PROTO_NONE as responder
spi inbound SPI of CHILD_SA to delete
expired TRUE if CHILD_SA already expired
Returns
child_delete task to handle by the task_manager
Definition at line 393 of file child_delete.c.
References FALSE, INIT, initiator, linked_list_create(), PROTO_NONE, protocol, and TRUE.
Referenced by METHOD(), and process_request().
 {
     private_child_delete_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
             .get_child = _get_child,
         },
         .ike_sa = ike_sa,
         .child_sas = linked_list_create(),
         .protocol = protocol,
         .spi = spi,
         .expired = expired,
     );
     if (protocol != PROTO_NONE)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
         this->initiator = TRUE;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
         this->initiator = FALSE;
     }
     return &this->public;
 }