strongSwan: medsrv_creds
medsrv_creds
medsrv
Classes
struct medsrv_creds_t
Typedefs
typedef struct medsrv_creds_t medsrv_creds_t
Functions
medsrv_creds_t * medsrv_creds_create (database_t *database)
Detailed Description
Typedef Documentation
typedef struct medsrv_creds_t medsrv_creds_t
Definition at line 27 of file medsrv_creds.h.
Function Documentation
medsrv_creds_t* medsrv_creds_create (database_t * db)
Create the medsrv credentials db.
Parameters
database underlying database
Returns
credential set implementation on that database
Described in header.
Definition at line 139 of file medsrv_creds.c.
References db, INIT, nop(), and return_null().
Referenced by open_database().
 {
     private_medsrv_creds_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_private_enumerator = (void*)return_null,
                 .create_cert_enumerator = _create_cert_enumerator,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .destroy = _destroy,
         },
         .db = db,
     );
     return &this->public;
 }