strongSwan: pt_tls_dispatcher.c File Reference
pt_tls_dispatcher.c File Reference
#include "pt_tls_dispatcher.h"
#include "pt_tls_server.h"
#include <threading/thread.h>
#include <utils/debug.h>
#include <processing/jobs/callback_job.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
Classes
struct private_pt_tls_dispatcher_t
Typedefs
typedef struct
private_pt_tls_dispatcher_t private_pt_tls_dispatcher_t
Functions
static bool open_socket (private_pt_tls_dispatcher_t *this, host_t *host)
static job_requeue_t handle (pt_tls_server_t *connection)
static void cleanup (pt_tls_server_t *connection)
METHOD (pt_tls_dispatcher_t, dispatch, void, private_pt_tls_dispatcher_t *this, pt_tls_tnccs_constructor_t *create)
METHOD (pt_tls_dispatcher_t, destroy, void, private_pt_tls_dispatcher_t *this)
pt_tls_dispatcher_t * pt_tls_dispatcher_create (host_t *address, identification_t *id, pt_tls_auth_t auth)
Typedef Documentation
typedef struct private_pt_tls_dispatcher_t private_pt_tls_dispatcher_t
Definition at line 27 of file pt_tls_dispatcher.c.
Function Documentation
static void cleanup (pt_tls_server_t * connection) static
Clean up connection state
Definition at line 114 of file pt_tls_dispatcher.c.
References close, pt_tls_server_t::destroy, and pt_tls_server_t::get_fd.
Referenced by METHOD().
 {
     int fd;
     fd = connection->get_fd(connection);
     connection->destroy(connection);
     close(fd);
 }
static job_requeue_t handle (pt_tls_server_t * connection) static
Handle a single PT-TLS client connection
Definition at line 93 of file pt_tls_dispatcher.c.
References FAILED, pt_tls_server_t::handle, JOB_REQUEUE_NONE, NEED_MORE, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     while (TRUE)
     {
         switch (connection->handle(connection))
         {
             case NEED_MORE:
                 continue;
             case FAILED:
             case SUCCESS:
             default:
                 break;
         }
         break;
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (pt_tls_dispatcher_t , dispatch , void , private_pt_tls_dispatcher_t * this, pt_tls_tnccs_constructor_t * create)
Definition at line 123 of file pt_tls_dispatcher.c.
References accept, callback_job_create_with_prio(), cleanup(), close, create, DBG1, DBG_TNC, handle(), JOB_PRIO_CRITICAL, lib, library_t::processor, pt_tls_server_create(), processor_t::queue_job, return_false(), server, strerror, thread_cancelability(), and TRUE.
 {
     while (TRUE)
     {
         pt_tls_server_t *connection;
         tnccs_t *tnccs;
         bool old;
         int fd;
         old = thread_cancelability(TRUE);
         fd = accept(this->fd, NULL, NULL);
         thread_cancelability(old);
         if (fd == -1)
         {
             DBG1(DBG_TNC, "accepting PT-TLS failed: %s", strerror(errno));
             continue;
         }
         tnccs = create(this->server, this->peer);
         if (!tnccs)
         {
             close(fd);
             continue;
         }
         connection = pt_tls_server_create(this->server, fd, this->auth, tnccs);
         if (!connection)
         {
             close(fd);
             continue;
         }
         lib->processor->queue_job(lib->processor,
                 (job_t*)callback_job_create_with_prio((callback_job_cb_t)handle,
                                         connection, (void*)cleanup,
                                         (callback_job_cancel_t)return_false,
                                         JOB_PRIO_CRITICAL));
     }
 }
METHOD (pt_tls_dispatcher_t , destroy , void , private_pt_tls_dispatcher_t * this)
Definition at line 163 of file pt_tls_dispatcher.c.
References close, free(), and server.
 {
     if (this->fd != -1)
     {
         close(this->fd);
     }
     this->server->destroy(this->server);
     this->peer->destroy(this->peer);
     free(this);
 }
static bool open_socket (private_pt_tls_dispatcher_t * this, host_t * host) static
Open listening server socket
Definition at line 68 of file pt_tls_dispatcher.c.
References bind, DBG1, DBG_TNC, FALSE, host_t::get_sockaddr, host_t::get_sockaddr_len, socket, strerror, and TRUE.
Referenced by pt_tls_dispatcher_create().
 {
     this->fd = socket(AF_INET, SOCK_STREAM, 0);
     if (this->fd == -1)
     {
         DBG1(DBG_TNC, "opening PT-TLS socket failed: %s", strerror(errno));
         return FALSE;
     }
     if (bind(this->fd, host->get_sockaddr(host),
              *host->get_sockaddr_len(host)) == -1)
     {
         DBG1(DBG_TNC, "binding to PT-TLS socket failed: %s", strerror(errno));
         return FALSE;
     }
     if (listen(this->fd, 5) == -1)
     {
         DBG1(DBG_TNC, "listen on PT-TLS socket failed: %s", strerror(errno));
         return FALSE;
     }
     return TRUE;
 }