strongSwan: fast_dispatcher
fast_dispatcher
libfast
Classes
struct fast_dispatcher_t
Typedefs
typedef struct fast_dispatcher_t fast_dispatcher_t
Functions
fast_dispatcher_t * fast_dispatcher_create (char *socket, bool debug, int timeout, fast_context_constructor_t constructor, void *param)
Detailed Description
Typedef Documentation
typedef struct fast_dispatcher_t fast_dispatcher_t
Definition at line 68 of file fast_dispatcher.h.
Function Documentation
fast_dispatcher_t* fast_dispatcher_create (char * socket, bool debug, int timeout, fast_context_constructor_t constructor, void * param)
Create a dispatcher.
The context constructor is invoked to create a session context for each session.
Parameters
socket FastCGI socket path, NULL for dynamic
debug no stripping, no compression, timing information
timeout session timeout
constructor construction function for session context
param parameter to supply to context constructor
Definition at line 430 of file fast_dispatcher.c.
References hashtable_create(), INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, session_equals(), session_hash(), and time_monotonic().
Referenced by main().
 {
     private_fast_dispatcher_t *this;
     INIT(this,
         .public = {
             .add_controller = _add_controller,
             .add_filter = _add_filter,
             .run = _run,
             .waitsignal = _waitsignal,
             .destroy = _destroy,
         },
         .sessions = hashtable_create((void*)session_hash,
                                      (void*)session_equals, 4096),
         .controllers = linked_list_create(),
         .filters = linked_list_create(),
         .context_constructor = constructor,
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .param = param,
         .timeout = timeout,
         .last_cleanup = time_monotonic(NULL),
         .debug = debug,
     );
     FCGX_Init();
     if (socket)
     {
         unlink(socket);
         this->fd = FCGX_OpenSocket(socket, 10);
     }
     return &this->public;
 }