strongSwan: md4_hasher.c File Reference
md4_hasher.c File Reference
#include <string.h>
#include "md4_hasher.h"
Classes
struct private_md4_hasher_t
Macros
#define S11 3
#define S12 7
#define S13 11
#define S14 19
#define S21 3
#define S22 5
#define S23 9
#define S24 13
#define S31 3
#define S32 9
#define S33 11
#define S34 15
#define F(x, y, z) (((x) & (y)) | ((~x) & (z)))
#define G(x, y, z) (((x) & (y)) | ((x) & (z)) | ((y) & (z)))
#define H(x, y, z) ((x) ^ (y) ^ (z))
#define ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32-(n))))
#define FF(a, b, c, d, x, s)
#define GG(a, b, c, d, x, s)
#define HH(a, b, c, d, x, s)
#define Encode memcpy
#define Decode memcpy
Typedefs
typedef struct private_md4_hasher_t private_md4_hasher_t
Functions
static void MD4Transform (u_int32_t state[4], u_int8_t block[64])
static void MD4Update (private_md4_hasher_t *this, u_int8_t *input, size_t inputLen)
static void MD4Final (private_md4_hasher_t *this, u_int8_t digest[16])
METHOD (hasher_t, reset, bool, private_md4_hasher_t *this)
METHOD (hasher_t, get_hash, bool, private_md4_hasher_t *this, chunk_t chunk, u_int8_t *buffer)
METHOD (hasher_t, allocate_hash, bool, private_md4_hasher_t *this, chunk_t chunk, chunk_t *hash)
METHOD (hasher_t, get_hash_size, size_t, private_md4_hasher_t *this)
METHOD (hasher_t, destroy, void, private_md4_hasher_t *this)
md4_hasher_t * md4_hasher_create (hash_algorithm_t algo)
Variables
static u_int8_t PADDING [64]
Macro Definition Documentation
#define Decode memcpy
Definition at line 129 of file md4_hasher.c.
Referenced by MD4Transform().
#define Encode memcpy
Definition at line 128 of file md4_hasher.c.
Referenced by MD4Final().
#define F (x, y, z) (((x) & (y)) | ((~x) & (z)))
Definition at line 51 of file md4_hasher.c.
#define FF (a, b, c, d, x, s)
Value:
{ \
    (a) += F ((b), (c), (d)) + (x); \
    (a) = ROTATE_LEFT ((a), (s)); \
  }
Definition at line 63 of file md4_hasher.c.
Referenced by MD4Transform().
#define G (x, y, z) (((x) & (y)) | ((x) & (z)) | ((y) & (z)))
Definition at line 52 of file md4_hasher.c.
Referenced by ec_group_new_brainpool().
#define GG (a, b, c, d, x, s)
Value:
{ \
    (a) += G ((b), (c), (d)) + (x) + (u_int32_t)0x5a827999; \
    (a) = ROTATE_LEFT ((a), (s)); \
  }
Definition at line 67 of file md4_hasher.c.
Referenced by MD4Transform().
#define H (x, y, z) ((x) ^ (y) ^ (z))
Definition at line 53 of file md4_hasher.c.
#define HH (a, b, c, d, x, s)
Value:
{ \
    (a) += H ((b), (c), (d)) + (x) + (u_int32_t)0x6ed9eba1; \
    (a) = ROTATE_LEFT ((a), (s)); \
  }
Definition at line 71 of file md4_hasher.c.
Referenced by MD4Transform().
#define ROTATE_LEFT (x, n) (((x) << (n)) | ((x) >> (32-(n))))
Definition at line 58 of file md4_hasher.c.
#define S11 3
Definition at line 29 of file md4_hasher.c.
Referenced by MD4Transform().
#define S12 7
Definition at line 30 of file md4_hasher.c.
Referenced by MD4Transform().
#define S13 11
Definition at line 31 of file md4_hasher.c.
Referenced by MD4Transform().
#define S14 19
Definition at line 32 of file md4_hasher.c.
Referenced by MD4Transform().
#define S21 3
Definition at line 33 of file md4_hasher.c.
Referenced by MD4Transform().
#define S22 5
Definition at line 34 of file md4_hasher.c.
Referenced by MD4Transform().
#define S23 9
Definition at line 35 of file md4_hasher.c.
Referenced by MD4Transform().
#define S24 13
Definition at line 36 of file md4_hasher.c.
Referenced by MD4Transform().
#define S31 3
Definition at line 37 of file md4_hasher.c.
Referenced by MD4Transform().
#define S32 9
Definition at line 38 of file md4_hasher.c.
Referenced by MD4Transform().
#define S33 11
Definition at line 39 of file md4_hasher.c.
Referenced by MD4Transform().
#define S34 15
Definition at line 40 of file md4_hasher.c.
Referenced by MD4Transform().
Typedef Documentation
typedef struct private_md4_hasher_t private_md4_hasher_t
Definition at line 76 of file md4_hasher.c.
Function Documentation
static void MD4Final (private_md4_hasher_t * this, u_int8_t digest[16]) static
Definition at line 246 of file md4_hasher.c.
References bits, count, Encode, MD4Update(), and PADDING.
Referenced by METHOD().
 {
     u_int8_t bits[8];
     size_t index, padLen;
     /* Save number of bits */
     Encode (bits, this->count, 8);
     /* Pad out to 56 mod 64. */
     index = (size_t)((this->count[0] >> 3) & 0x3f);
     padLen = (index < 56) ? (56 - index) : (120 - index);
     MD4Update (this, PADDING, padLen);
     /* Append length (before padding) */
     MD4Update (this, bits, 8);
     if (digest != NULL)         /* Bill Simpson's padding */
     {
         /* store state in digest */
         Encode (digest, this->state, 16);
     }
 }
static void MD4Transform (u_int32_t state[4], u_int8_t block[64]) static
Definition at line 135 of file md4_hasher.c.
References a, b, c, Decode, FF, GG, HH, S11, S12, S13, S14, S21, S22, S23, S24, S31, S32, S33, and S34.
Referenced by MD4Update().
 {
     u_int32_t a = state[0], b = state[1], c = state[2], d = state[3], x[16];
     Decode(x, block, 64);
   /* Round 1 */
   FF (a, b, c, d, x[ 0], S11); /* 1 */
   FF (d, a, b, c, x[ 1], S12); /* 2 */
   FF (c, d, a, b, x[ 2], S13); /* 3 */
   FF (b, c, d, a, x[ 3], S14); /* 4 */
   FF (a, b, c, d, x[ 4], S11); /* 5 */
   FF (d, a, b, c, x[ 5], S12); /* 6 */
   FF (c, d, a, b, x[ 6], S13); /* 7 */
   FF (b, c, d, a, x[ 7], S14); /* 8 */
   FF (a, b, c, d, x[ 8], S11); /* 9 */
   FF (d, a, b, c, x[ 9], S12); /* 10 */
   FF (c, d, a, b, x[10], S13); /* 11 */
   FF (b, c, d, a, x[11], S14); /* 12 */
   FF (a, b, c, d, x[12], S11); /* 13 */
   FF (d, a, b, c, x[13], S12); /* 14 */
   FF (c, d, a, b, x[14], S13); /* 15 */
   FF (b, c, d, a, x[15], S14); /* 16 */
   /* Round 2 */
   GG (a, b, c, d, x[ 0], S21); /* 17 */
   GG (d, a, b, c, x[ 4], S22); /* 18 */
   GG (c, d, a, b, x[ 8], S23); /* 19 */
   GG (b, c, d, a, x[12], S24); /* 20 */
   GG (a, b, c, d, x[ 1], S21); /* 21 */
   GG (d, a, b, c, x[ 5], S22); /* 22 */
   GG (c, d, a, b, x[ 9], S23); /* 23 */
   GG (b, c, d, a, x[13], S24); /* 24 */
   GG (a, b, c, d, x[ 2], S21); /* 25 */
   GG (d, a, b, c, x[ 6], S22); /* 26 */
   GG (c, d, a, b, x[10], S23); /* 27 */
   GG (b, c, d, a, x[14], S24); /* 28 */
   GG (a, b, c, d, x[ 3], S21); /* 29 */
   GG (d, a, b, c, x[ 7], S22); /* 30 */
   GG (c, d, a, b, x[11], S23); /* 31 */
   GG (b, c, d, a, x[15], S24); /* 32 */
   /* Round 3 */
   HH (a, b, c, d, x[ 0], S31); /* 33 */
   HH (d, a, b, c, x[ 8], S32); /* 34 */
   HH (c, d, a, b, x[ 4], S33); /* 35 */
   HH (b, c, d, a, x[12], S34); /* 36 */
   HH (a, b, c, d, x[ 2], S31); /* 37 */
   HH (d, a, b, c, x[10], S32); /* 38 */
   HH (c, d, a, b, x[ 6], S33); /* 39 */
   HH (b, c, d, a, x[14], S34); /* 40 */
   HH (a, b, c, d, x[ 1], S31); /* 41 */
   HH (d, a, b, c, x[ 9], S32); /* 42 */
   HH (c, d, a, b, x[ 5], S33); /* 43 */
   HH (b, c, d, a, x[13], S34); /* 44 */
   HH (a, b, c, d, x[ 3], S31); /* 45 */
   HH (d, a, b, c, x[11], S32); /* 46 */
   HH (c, d, a, b, x[ 7], S33); /* 47 */
   HH (b, c, d, a, x[15], S34); /* 48 */
   state[0] += a;
   state[1] += b;
   state[2] += c;
   state[3] += d;
 }
static void MD4Update (private_md4_hasher_t * this, u_int8_t * input, size_t inputLen) static
Definition at line 205 of file md4_hasher.c.
References count, MD4Transform(), and memcpy.
Referenced by MD4Final(), and METHOD().
 {
     u_int32_t i;
     size_t index, partLen;
     /* Compute number of bytes mod 64 */
     index = (u_int8_t)((this->count[0] >> 3) & 0x3F);
     /* Update number of bits */
     if ((this->count[0] += (inputLen << 3)) < (inputLen << 3))
     {
         this->count[1]++;
     }
     this->count[1] += (inputLen >> 29);
     partLen = 64 - index;
     /* Transform as many times as possible. */
     if (inputLen >= partLen)
     {
         memcpy(&this->buffer[index], input, partLen);
         MD4Transform (this->state, this->buffer);
         for (i = partLen; i + 63 < inputLen; i += 64)
         {
         MD4Transform (this->state, &input[i]);
         }
         index = 0;
     }
     else
     {
         i = 0;
     }
     /* Buffer remaining input */
     memcpy(&this->buffer[index], &input[i], inputLen-i);
 }
METHOD (hasher_t , reset , bool , private_md4_hasher_t * this)
Definition at line 269 of file md4_hasher.c.
References count, and TRUE.
 {
     this->state[0] = 0x67452301;
     this->state[1] = 0xefcdab89;
     this->state[2] = 0x98badcfe;
     this->state[3] = 0x10325476;
     this->count[0] = 0;
     this->count[1] = 0;
     return TRUE;
 }
METHOD (hasher_t , get_hash , bool , private_md4_hasher_t * this, chunk_t chunk, u_int8_t * buffer)
Definition at line 282 of file md4_hasher.c.
References chunk_t::len, MD4Final(), MD4Update(), chunk_t::ptr, and TRUE.
 {
     MD4Update(this, chunk.ptr, chunk.len);
     if (buffer != NULL)
     {
         MD4Final(this, buffer);
         reset(this);
     }
     return TRUE;
 }
METHOD (hasher_t , allocate_hash , bool , private_md4_hasher_t * this, chunk_t chunk, chunk_t * hash)
Definition at line 294 of file md4_hasher.c.
References HASH_SIZE_MD4, chunk_t::len, malloc(), MD4Final(), MD4Update(), chunk_t::ptr, and TRUE.
 {
     chunk_t allocated_hash;
     MD4Update(this, chunk.ptr, chunk.len);
     if (hash != NULL)
     {
         allocated_hash.ptr = malloc(HASH_SIZE_MD4);
         allocated_hash.len = HASH_SIZE_MD4;
         MD4Final(this, allocated_hash.ptr);
         reset(this);
         *hash = allocated_hash;
     }
     return TRUE;
 }
METHOD (hasher_t , get_hash_size , size_t , private_md4_hasher_t * this)
Definition at line 313 of file md4_hasher.c.
References HASH_SIZE_MD4.
 {
     return HASH_SIZE_MD4;
 }
METHOD (hasher_t , destroy , void , private_md4_hasher_t * this)
Definition at line 319 of file md4_hasher.c.
References free().
 {
     free(this);
 }
Variable Documentation
u_int8_t PADDING[64] static
Initial value:
= {
  0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
}
Definition at line 42 of file md4_hasher.c.
Referenced by MD4Final().