strongSwan: ext_auth_plugin.c File Reference
ext_auth_plugin.c File Reference
#include "ext_auth_plugin.h"
#include "ext_auth_listener.h"
#include <daemon.h>
Classes
struct private_ext_auth_plugin_t
Typedefs
typedef struct
private_ext_auth_plugin_t private_ext_auth_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_ext_auth_plugin_t *this)
static ext_auth_listener_t * create_listener ()
static bool plugin_cb (private_ext_auth_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_ext_auth_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, reload, bool, private_ext_auth_plugin_t *this)
METHOD (plugin_t, destroy, void, private_ext_auth_plugin_t *this)
plugin_t * ext_auth_plugin_create ()
Typedef Documentation
typedef struct private_ext_auth_plugin_t private_ext_auth_plugin_t
Definition at line 30 of file ext_auth_plugin.c.
Function Documentation
static ext_auth_listener_t* create_listener () static
Create a listener instance, NULL on error
Definition at line 57 of file ext_auth_plugin.c.
References DBG1, DBG_CFG, ext_auth_listener_create(), settings_t::get_str, lib, library_t::ns, and library_t::settings.
Referenced by METHOD(), and plugin_cb().
 {
     char *script;
     script = lib->settings->get_str(lib->settings,
                     "%s.plugins.ext-auth.script", NULL, lib->ns);
     if (!script)
     {
         DBG1(DBG_CFG, "no script for ext-auth script defined, disabled");
         return NULL;
     }
     DBG1(DBG_CFG, "using ext-auth script '%s'", script);
     return ext_auth_listener_create(script);
 }
plugin_t* ext_auth_plugin_create ()
Plugin constructor
Definition at line 140 of file ext_auth_plugin.c.
References INIT.
 {
     private_ext_auth_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .reload = _reload,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_ext_auth_plugin_t * this)
Definition at line 48 of file ext_auth_plugin.c.
 {
     return "ext-auth";
 }
METHOD (plugin_t , get_features , int , private_ext_auth_plugin_t * this, plugin_feature_t * features[])
Definition at line 98 of file ext_auth_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "ext_auth"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , reload , bool , private_ext_auth_plugin_t * this)
Definition at line 110 of file ext_auth_plugin.c.
References bus_t::add_listener, daemon_t::bus, charon, create_listener(), ext_auth_listener_t::destroy, ext_auth_listener_t::listener, listener, bus_t::remove_listener, and TRUE.
 {
     ext_auth_listener_t *listener;
     /* reload new listener overlapped */
     listener = create_listener();
     if (listener)
     {
         charon->bus->add_listener(charon->bus, &listener->listener);
     }
     if (this->listener)
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
         this->listener->destroy(this->listener);
     }
     this->listener = listener;
     return TRUE;
 }
METHOD (plugin_t , destroy , void , private_ext_auth_plugin_t * this)
Definition at line 131 of file ext_auth_plugin.c.
References free().
 {
     free(this);
 }
static bool plugin_cb (private_ext_auth_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 75 of file ext_auth_plugin.c.
References bus_t::add_listener, daemon_t::bus, charon, create_listener(), tkm_listener_t::destroy, FALSE, listener, bus_t::remove_listener, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->listener = create_listener();
         if (!this->listener)
         {
             return FALSE;
         }
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         if (this->listener)
         {
             charon->bus->remove_listener(charon->bus, &this->listener->listener);
             this->listener->destroy(this->listener);
         }
     }
     return TRUE;
 }