strongSwan: imv_database_t Struct Reference
imv_database_t Struct Reference
imv_database
#include "imv_database.h"
Public Attributes
imv_session_t *(* add_session)(imv_database_t *this, TNC_ConnectionID conn_id, u_int32_t ar_id_type, chunk_t ar_id_value)
void(* remove_session)(imv_database_t *this, imv_session_t *session)
void(* add_recommendation)(imv_database_t *this, imv_session_t *session, TNC_IMV_Action_Recommendation rec)
bool(* policy_script)(imv_database_t *this, imv_session_t *session, bool start)
bool(* finalize_workitem)(imv_database_t *this, imv_workitem_t *workitem)
database_t *(* get_database)(imv_database_t *this)
void(* destroy)(imv_database_t *this)
Detailed Description
IMV database interface
Definition at line 37 of file imv_database.h.
Member Data Documentation
void(* imv_database_t::add_recommendation)(imv_database_t *this, imv_session_t *session, TNC_IMV_Action_Recommendation rec)
Add final recommendation to a session database entry
Parameters
session Session
rec Final recommendation
Definition at line 64 of file imv_database.h.
Referenced by METHOD().
imv_session_t*(* imv_database_t::add_session)(imv_database_t *this, TNC_ConnectionID conn_id, u_int32_t ar_id_type, chunk_t ar_id_value)
Create or get a session associated with a TNCCS connection
Parameters
conn_id TNCCS Connection ID
ar_id_type Access Requestor identity type
ar_id_value Access Requestor identity value
Returns
Session associated with TNCCS Connection
Definition at line 47 of file imv_database.h.
void(* imv_database_t::destroy)(imv_database_t *this)
Destroys an imv_database_t object
Definition at line 94 of file imv_database.h.
bool(* imv_database_t::finalize_workitem)(imv_database_t *this, imv_workitem_t *workitem)
Finalize a workitem
Parameters
workitem Workitem to be finalized
Definition at line 82 of file imv_database.h.
Referenced by imv_attestation_process(), and METHOD().
database_t*(* imv_database_t::get_database)(imv_database_t *this)
Get database handle
Returns
Database handle
Definition at line 89 of file imv_database.h.
Referenced by imv_os_database_create(), and pts_database_create().
bool(* imv_database_t::policy_script)(imv_database_t *this, imv_session_t *session, bool start)
Announce session start/stop to policy script
Parameters
session Session
start TRUE if session start, FALSE if session stop
Returns
TRUE if command successful, FALSE otherwise
Definition at line 74 of file imv_database.h.
Referenced by METHOD().
void(* imv_database_t::remove_session)(imv_database_t *this, imv_session_t *session)
Remove and delete a session
Parameters
session Session
Definition at line 56 of file imv_database.h.
The documentation for this struct was generated from the following file:
imv_database.h