strongSwan: ipsec_sa_mgr_t Struct Reference
ipsec_sa_mgr_t Struct Reference
ipsec_sa_mgr
#include "ipsec_sa_mgr.h"
Public Attributes
status_t(* get_spi)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
status_t(* add_sa)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, bool initiator, bool encap, bool esn, bool inbound, bool update)
status_t(* update_sa)(ipsec_sa_mgr_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
status_t(* query_sa)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
status_t(* del_sa)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
status_t(* flush_sas)(ipsec_sa_mgr_t *this)
ipsec_sa_t *(* checkout_by_spi)(ipsec_sa_mgr_t *this, u_int32_t spi, host_t *dst)
ipsec_sa_t *(* checkout_by_reqid)(ipsec_sa_mgr_t *this, u_int32_t reqid, bool inbound)
void(* checkin)(ipsec_sa_mgr_t *this, ipsec_sa_t *sa)
void(* destroy)(ipsec_sa_mgr_t *this)
Detailed Description
IPsec SA manager
The first methods are modeled after those in kernel_ipsec_t.
Definition at line 40 of file ipsec_sa_mgr.h.
Member Data Documentation
status_t(* ipsec_sa_mgr_t::add_sa)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, bool initiator, bool encap, bool esn, bool inbound, bool update)
Add a new SA
Parameters
src source address for this SA (gets cloned)
dst destination address for this SA (gets cloned)
spi SPI for this SA
protocol protocol for this SA (only ESP is supported)
reqid reqid for this SA
mark mark for this SA (ignored)
tfc Traffic Flow Confidentiality (not yet supported)
lifetime lifetime for this SA
enc_alg encryption algorithm for this SA
enc_key encryption key for this SA
int_alg integrity protection algorithm
int_key integrity protection key
mode mode for this SA (only tunnel mode is supported)
ipcomp IPcomp transform (not supported, use IPCOMP_NONE)
cpi CPI for IPcomp (ignored)
initiator TRUE if initiator of the exchange creating this SA
encap enable UDP encapsulation (must be TRUE)
esn Extended Sequence Numbers (currently not supported)
inbound TRUE if this is an inbound SA, FALSE otherwise
update TRUE if an SPI has already been allocated for SA
Returns
SUCCESS if operation completed
Definition at line 79 of file ipsec_sa_mgr.h.
Referenced by METHOD().
void(* ipsec_sa_mgr_t::checkin)(ipsec_sa_mgr_t *this, ipsec_sa_t *sa)
Checkin an SA after use.
Parameters
sa checked out SA
Definition at line 188 of file ipsec_sa_mgr.h.
Referenced by process_inbound(), and process_outbound().
ipsec_sa_t*(* ipsec_sa_mgr_t::checkout_by_reqid)(ipsec_sa_mgr_t *this, u_int32_t reqid, bool inbound)
Checkout an installed IPsec SA by its reqid and inbound/outbound flag. Can be used to find the correct SA for an outbound packet.
The matching SA is locked until it is checked in using checkin(). If the matching SA is already checked out, this call blocks until the SA is checked in.
Since other threads may be waiting for a checked out SA, it should be checked in as soon as possible after use.
Parameters
reqid reqid of the SA
inbound TRUE for an inbound SA, FALSE for an outbound SA
Returns
the matching IPsec SA, or NULL if none is found
Definition at line 180 of file ipsec_sa_mgr.h.
Referenced by process_outbound().
ipsec_sa_t*(* ipsec_sa_mgr_t::checkout_by_spi)(ipsec_sa_mgr_t *this, u_int32_t spi, host_t *dst)
Checkout an installed IPsec SA by SPI and destination address Can be used to find the correct SA for an inbound packet.
The matching SA is locked until it is checked in using checkin(). If the matching SA is already checked out, this call blocks until the SA is checked in.
Since other threads may be waiting for the checked out SA, it should be checked in as soon as possible after use.
Parameters
spi SPI (e.g. of an inbound packet)
dst destination address (e.g. of an inbound packet)
Returns
the matching IPsec SA, or NULL if none is found
Definition at line 162 of file ipsec_sa_mgr.h.
Referenced by process_inbound().
status_t(* ipsec_sa_mgr_t::del_sa)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Delete a previously added SA
Parameters
spi SPI of the SA
src source address of the SA
dst destination address of the SA
protocol protocol of the SA
cpi CPI for IPcomp
mark optional mark
Returns
SUCCESS if operation completed
Definition at line 136 of file ipsec_sa_mgr.h.
Referenced by METHOD().
void(* ipsec_sa_mgr_t::destroy)(ipsec_sa_mgr_t *this)
Destroy an ipsec_sa_mgr_t
Definition at line 193 of file ipsec_sa_mgr.h.
status_t(* ipsec_sa_mgr_t::flush_sas)(ipsec_sa_mgr_t *this)
Flush all SAs
Returns
SUCCESS if operation completed
Definition at line 145 of file ipsec_sa_mgr.h.
Referenced by METHOD().
status_t(* ipsec_sa_mgr_t::get_spi)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
Allocate an SPI for an inbound IPsec SA
Parameters
src source address of the SA
dst destination address of the SA
protocol protocol of the SA (only ESP supported)
spi the allocated SPI
Returns
SUCCESS of operation successful
Definition at line 51 of file ipsec_sa_mgr.h.
Referenced by METHOD().
status_t(* ipsec_sa_mgr_t::query_sa)(ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
Query the number of bytes processed by an SA from the SAD.
Parameters
src source address for this SA
dst destination address for this SA
spi SPI allocated by us or remote peer
protocol protocol for this SA (ESP/AH)
mark optional mark for this SA
[out] bytes the number of bytes processed by SA
[out] packets number of packets processed by SA
[out] time last (monotonic) time of SA use
Returns
SUCCESS if operation completed
Definition at line 121 of file ipsec_sa_mgr.h.
Referenced by METHOD().
status_t(* ipsec_sa_mgr_t::update_sa)(ipsec_sa_mgr_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
Update the hosts on an installed SA.
Parameters
spi SPI of the SA
protocol protocol for this SA (ESP/AH)
cpi CPI for IPComp, 0 if no IPComp is used
src current source address
dst current destination address
new_src new source address
new_dst new destination address
encap current use of UDP encapsulation
new_encap new use of UDP encapsulation
mark optional mark for this SA
Returns
SUCCESS if operation completed
Definition at line 102 of file ipsec_sa_mgr.h.
The documentation for this struct was generated from the following file:
ipsec_sa_mgr.h