strongSwan: eap_radius_xauth
eap_radius_xauth
eap_radius
Classes
struct eap_radius_xauth_t
Typedefs
typedef struct eap_radius_xauth_t eap_radius_xauth_t
Functions
eap_radius_xauth_t * eap_radius_xauth_create_server (identification_t *server, identification_t *peer, char *profile)
Detailed Description
Typedef Documentation
typedef struct eap_radius_xauth_t eap_radius_xauth_t
Definition at line 26 of file eap_radius_xauth.h.
Function Documentation
eap_radius_xauth_t* eap_radius_xauth_create_server (identification_t * server, identification_t * peer, char * profile)
Creates the RADIUS XAuth method, acting as server.
Parameters
server ID of the XAuth server
peer ID of the XAuth client
profile configuration string
Returns
xauth_generic_t object
Definition at line 306 of file eap_radius_xauth.c.
References array_create(), client(), identification_t::clone, destroy(), eap_radius_create_client(), INIT, and parse_rounds().
Referenced by METHOD().
 {
     private_eap_radius_xauth_t *this;
     INIT(this,
         .public = {
             .xauth_method = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_identity = _get_identity,
                 .destroy = _destroy,
             },
         },
         .server = server->clone(server),
         .peer = peer->clone(peer),
         .client = eap_radius_create_client(),
         .rounds = array_create(sizeof(xauth_round_t), 0),
     );
     if (!parse_rounds(this, profile))
     {
         destroy(this);
         return NULL;
     }
     if (!this->client)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }