strongSwan: thread_value
thread_value
threading
Classes
struct thread_value_t
Typedefs
typedef struct thread_value_t thread_value_t
Functions
thread_value_t * thread_value_create (thread_cleanup_t destructor)
Detailed Description
Typedef Documentation
typedef struct thread_value_t thread_value_t
Definition at line 26 of file thread_value.h.
Function Documentation
thread_value_t* thread_value_create (thread_cleanup_t cleanup)
Create a new thread-specific value wrapper.
The optional destructor is called whenever a thread terminates, with the assigned value as argument. It is not called if that value is NULL.
Parameters
destructor destructor
Returns
thread-specific value wrapper
Described in header.
Definition at line 77 of file thread_value.c.
References cleanup, DWORD, INIT, and key.
Referenced by arrays_init(), bus_create(), credential_factory_create(), credential_manager_create(), init(), leak_detective_create(), mysql_database_create(), mysql_database_init(), printf_hook_create(), rwlock_create(), sql_logger_create(), sqlite_database_create(), START_TEST(), strerror_init(), threading_init(), and threads_init().
 {
     private_thread_value_t *this;
     INIT(this,
         .public = {
             .set = _set,
             .get = _get,
             .destroy = _destroy,
         },
         .destructor = destructor,
     );
     pthread_key_create(&this->key, destructor);
     return &this->public;
 }