strongSwan: radattr_listener.c File Reference
radattr_listener.c File Reference
#include "radattr_listener.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <daemon.h>
#include <radius_message.h>
Classes
struct private_radattr_listener_t
Macros
#define MAX_ATTR_SIZE 1024
Typedefs
typedef struct
private_radattr_listener_t private_radattr_listener_t
Functions
static void print_radius_attributes (private_radattr_listener_t *this, message_t *message)
static void add_radius_attribute (private_radattr_listener_t *this, ike_sa_t *ike_sa, message_t *message)
METHOD (listener_t, message, bool, private_radattr_listener_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (radattr_listener_t, destroy, void, private_radattr_listener_t *this)
radattr_listener_t * radattr_listener_create ()
Macro Definition Documentation
#define MAX_ATTR_SIZE 1024
Maximum size of an attribute to add
Definition at line 31 of file radattr_listener.c.
Typedef Documentation
typedef struct private_radattr_listener_t private_radattr_listener_t
Definition at line 33 of file radattr_listener.c.
Function Documentation
static void add_radius_attribute (private_radattr_listener_t * this, ike_sa_t * ike_sa, message_t * message) static
Add a RADIUS attribute from a client-ID specific file to an IKE message
Definition at line 103 of file radattr_listener.c.
References message_t::add_notify, AUTH_RULE_EAP_IDENTITY, chunk_map(), chunk_unmap(), data, DBG1, DBG_CFG, dir, FALSE, auth_cfg_t::get, ike_sa_t::get_auth_cfg, message_t::get_message_id, ike_sa_t::get_my_id, id, chunk_t::len, path, chunk_t::ptr, RADIUS_ATTRIBUTE, radius_attribute_type_names, snprintf, strerror, and TRUE.
Referenced by METHOD().
 {
     if (this->dir &&
         (this->mid == -1 || message->get_message_id(message) == this->mid))
     {
         identification_t *id;
         auth_cfg_t *auth;
         char path[PATH_MAX];
         chunk_t *data;
         auth = ike_sa->get_auth_cfg(ike_sa, TRUE);
         id = auth->get(auth, AUTH_RULE_EAP_IDENTITY);
         if (!id)
         {
             id = ike_sa->get_my_id(ike_sa);
         }
         snprintf(path, sizeof(path), "%s/%Y", this->dir, id);
         data = chunk_map(path, FALSE);
         if (data)
         {
             if (data->len >= 2)
             {
                 DBG1(DBG_CFG, "adding RADIUS %N attribute",
                      radius_attribute_type_names, data->ptr[0]);
                 message->add_notify(message, FALSE, RADIUS_ATTRIBUTE, *data);
             }
             chunk_unmap(data);
         }
         else
         {
             DBG1(DBG_CFG, "reading RADIUS attribute '%s' failed: %s",
                  path, strerror(errno));
         }
     }
 }
METHOD (listener_t , message , bool , private_radattr_listener_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 141 of file radattr_listener.c.
References add_radius_attribute(), EXT_STRONGSWAN, message_t::get_exchange_type, message_t::get_payload, IKE_AUTH, PLV2_EAP, print_radius_attributes(), ike_sa_t::supports_extension, and TRUE.
 {
     if (plain && ike_sa->supports_extension(ike_sa, EXT_STRONGSWAN) &&
         message->get_exchange_type(message) == IKE_AUTH &&
         message->get_payload(message, PLV2_EAP))
     {
         if (incoming)
         {
             print_radius_attributes(this, message);
         }
         else
         {
             add_radius_attribute(this, ike_sa, message);
         }
     }
     return TRUE;
 }
METHOD (radattr_listener_t , destroy , void , private_radattr_listener_t * this)
Definition at line 162 of file radattr_listener.c.
References free().
 {
     free(this);
 }
static void print_radius_attributes (private_radattr_listener_t * this, message_t * message) static
Print RADIUS attributes found in IKE message notifies
Definition at line 59 of file radattr_listener.c.
References chunk_printable(), chunk_skip(), message_t::create_payload_enumerator, data, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, notify_payload_t::get_notification_data, notify_payload_t::get_notify_type, payload_t::get_type, chunk_t::len, notify(), PLV2_NOTIFY, chunk_t::ptr, RADIUS_ATTRIBUTE, radius_attribute_type_names, and type.
Referenced by METHOD().
 {
     radius_attribute_type_t type;
     enumerator_t *enumerator;
     notify_payload_t *notify;
     payload_t *payload;
     chunk_t data;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV2_NOTIFY)
         {
             notify = (notify_payload_t*)payload;
             if (notify->get_notify_type(notify) == RADIUS_ATTRIBUTE)
             {
                 data = notify->get_notification_data(notify);
                 if (data.len >= 2)
                 {
                     type = data.ptr[0];
                     data = chunk_skip(data, 2);
                     if (chunk_printable(data, NULL, 0))
                     {
                         DBG1(DBG_IKE, "received RADIUS %N: %.*s",
                              radius_attribute_type_names, type,
                              (int)data.len, data.ptr);
                     }
                     else
                     {
                         DBG1(DBG_IKE, "received RADIUS %N: %#B",
                              radius_attribute_type_names, type, &data);
                     }
                 }
             }
         }
     }
     enumerator->destroy(enumerator);
 }