strongSwan: parser_helper.c File Reference
parser_helper.c File Reference
#include <limits.h>
#include <ctype.h>
#include <stdarg.h>
#include "parser_helper.h"
#include <collections/array.h>
Classes
struct private_parser_helper_t
struct parser_helper_file_t
Typedefs
typedef struct
private_parser_helper_t private_parser_helper_t
typedef struct parser_helper_file_t parser_helper_file_t
Functions
static void parser_helper_file_destroy (parser_helper_file_t *this)
static parser_helper_file_t * current_file (private_parser_helper_t *this)
METHOD (parser_helper_t, file_next, FILE *, private_parser_helper_t *this)
METHOD (parser_helper_t, file_include, void, private_parser_helper_t *this, char *pattern)
METHOD (parser_helper_t, string_init, void, private_parser_helper_t *this)
METHOD (parser_helper_t, string_add, void, private_parser_helper_t *this, char *str)
METHOD (parser_helper_t, string_get, char *, private_parser_helper_t *this)
METHOD (parser_helper_t, destroy, void, private_parser_helper_t *this)
void parser_helper_log (int level, parser_helper_t *ctx, char *fmt,...)
parser_helper_t * parser_helper_create (void *context)
Typedef Documentation
typedef struct parser_helper_file_t parser_helper_file_t
Definition at line 25 of file parser_helper.c.
typedef struct private_parser_helper_t private_parser_helper_t
Definition at line 24 of file parser_helper.c.
Function Documentation
static parser_helper_file_t* current_file (private_parser_helper_t * this) static
Returns the current file, if any.
Definition at line 80 of file parser_helper.c.
References array_get(), ARRAY_TAIL, and parser_helper_file_t::name.
Referenced by parser_helper_log().
 {
     parser_helper_file_t *file;
     array_get(this->files, ARRAY_TAIL, &file);
     if (file->name)
     {
         return file;
     }
     return NULL;
 }
METHOD (parser_helper_t , file_next , FILE * , private_parser_helper_t * this)
Definition at line 92 of file parser_helper.c.
References array_get(), array_insert(), array_remove(), ARRAY_TAIL, enumerator_t::destroy, enumerator_t::enumerate, parser_helper_file_t::file, INIT, parser_helper_file_t::matches, name, parser_helper_file_t::name, next, PARSER_DBG2, parser_helper_file_destroy(), and strdup.
 {
     parser_helper_file_t *file, *next;
     char *name;
     array_get(this->files, ARRAY_TAIL, &file);
     if (!file->matches && file->name)
     {
         array_remove(this->files, ARRAY_TAIL, NULL);
         parser_helper_file_destroy(file);
         /* continue with previous includes, if any */
         array_get(this->files, ARRAY_TAIL, &file);
     }
     if (file->matches)
     {
         while (file->matches->enumerate(file->matches, &name, NULL))
         {
             INIT(next,
                 .name = strdup(name),
                 .file = fopen(name, "r"),
             );
             if (next->file)
             {
                 array_insert(this->files, ARRAY_TAIL, next);
                 return next->file;
             }
             PARSER_DBG2(&this->public, "unable to open '%s'", name);
             parser_helper_file_destroy(next);
         }
         file->matches->destroy(file->matches);
         file->matches = NULL;
     }
     return NULL;
 }
METHOD (parser_helper_t , file_include , void , private_parser_helper_t * this, char * pattern)
Definition at line 129 of file parser_helper.c.
References array_get(), ARRAY_TAIL, dir, DIRECTORY_SEPARATOR, enumerator_create_empty(), enumerator_create_glob(), enumerator_create_single(), free(), parser_helper_file_t::matches, parser_helper_file_t::name, PARSER_DBG1, path_absolute(), path_dirname(), snprintf, and strdup.
 {
     parser_helper_file_t *file;
     char pat[PATH_MAX];
     array_get(this->files, ARRAY_TAIL, &file);
     if (!pattern || !*pattern)
     {
         PARSER_DBG1(&this->public, "no include pattern specified, ignored");
         file->matches = enumerator_create_empty();
         return;
     }
     if (!file->name || path_absolute(pattern))
     {   /* absolute path */
         if (snprintf(pat, sizeof(pat), "%s", pattern) >= sizeof(pat))
         {
             PARSER_DBG1(&this->public, "include pattern too long, ignored");
             file->matches = enumerator_create_empty();
             return;
         }
     }
     else
     {   /* base relative paths to the directory of the current file */
         char *dir = path_dirname(file->name);
         if (snprintf(pat, sizeof(pat), "%s%s%s", dir, DIRECTORY_SEPARATOR,
                      pattern) >= sizeof(pat))
         {
             PARSER_DBG1(&this->public, "include pattern too long, ignored");
             free(dir);
             file->matches = enumerator_create_empty();
             return;
         }
         free(dir);
     }
     file->matches = enumerator_create_glob(pat);
     if (!file->matches)
     {   /* if glob(3) is not available, try to load pattern directly */
         file->matches = enumerator_create_single(strdup(pat), free);
     }
 }
METHOD (parser_helper_t , string_init , void , private_parser_helper_t * this)
Definition at line 173 of file parser_helper.c.
References chunk_free(), and data.
 {
     chunk_t data;
     data = this->writer->extract_buf(this->writer);
     chunk_free(&data);
 }
METHOD (parser_helper_t , string_add , void , private_parser_helper_t * this, char * str)
Definition at line 182 of file parser_helper.c.
References chunk_from_str.
 {
     this->writer->write_data(this->writer, chunk_from_str(str));
 }
METHOD (parser_helper_t , string_get , char * , private_parser_helper_t * this)
Definition at line 188 of file parser_helper.c.
References chunk_from_chars, data, and chunk_t::ptr.
 {
     chunk_t data;
     this->writer->write_data(this->writer, chunk_from_chars('\0'));
     data = this->writer->extract_buf(this->writer);
     return data.ptr;
 }
METHOD (parser_helper_t , destroy , void , private_parser_helper_t * this)
Definition at line 198 of file parser_helper.c.
References array_destroy_function(), free(), and parser_helper_file_destroy().
 {
     array_destroy_function(this->files, (void*)parser_helper_file_destroy, NULL);
     this->writer->destroy(this->writer);
     free(this);
 }
static void parser_helper_file_destroy (parser_helper_file_t * this) static
Destroy the given file data.
Definition at line 66 of file parser_helper.c.
References DESTROY_IF, free(), and name.
Referenced by METHOD().
 {
     if (this->file)
     {
         fclose(this->file);
     }
     free(this->name);
     DESTROY_IF(this->matches);
     free(this);
 }