strongSwan: credential_factory
credential_factory
credentials
Classes
struct credential_factory_t
Typedefs
typedef struct credential_factory_t credential_factory_t
typedef enum credential_type_t credential_type_t
Enumerations
enum credential_type_t { CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, CRED_CERTIFICATE, CRED_CONTAINER }
Functions
credential_factory_t * credential_factory_create ()
Variables
enum_name_t * credential_type_names
Detailed Description
Typedef Documentation
typedef struct credential_factory_t credential_factory_t
Definition at line 24 of file credential_factory.h.
typedef enum credential_type_t credential_type_t
Definition at line 25 of file credential_factory.h.
Enumeration Type Documentation
enum credential_type_t
Kind of credential.
While crypto containers are not really credentials, we still use the credential factory and builders create them.
Enumerator
CRED_PRIVATE_KEY
private key, implemented in private_key_t
CRED_PUBLIC_KEY
public key, implemented in public_key_t
CRED_CERTIFICATE
certificates, implemented in certificate_t
CRED_CONTAINER
crypto container, implemented in container_t
Definition at line 35 of file credential_factory.h.
{
     CRED_PRIVATE_KEY,
     CRED_PUBLIC_KEY,
     CRED_CERTIFICATE,
     CRED_CONTAINER,
 };
Function Documentation
credential_factory_t* credential_factory_create ()
Create a credential_factory instance.
Definition at line 202 of file credential_factory.c.
References INIT, linked_list_create(), rwlock_create(), RWLOCK_TYPE_DEFAULT, and thread_value_create().
Referenced by library_init().
 {
     private_credential_factory_t *this;
     INIT(this,
         .public = {
             .create = _create,
             .create_builder_enumerator = _create_builder_enumerator,
             .add_builder = _add_builder,
             .remove_builder = _remove_builder,
             .destroy = _destroy,
         },
         .constructors = linked_list_create(),
         .recursive = thread_value_create(NULL),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return &this->public;
 }
Variable Documentation
enum_name_t* credential_type_names
enum names for credential_type_t
Referenced by METHOD().