strongSwan: seg_env_t Struct Reference
seg_env_t Struct Reference
seg_env
#include "seg_env.h"
Public Attributes
uint32_t(* get_base_attr_id)(seg_env_t *this)
pa_tnc_attr_t *(* get_base_attr)(seg_env_t *this)
chunk_t(* get_base_attr_info)(seg_env_t *this)
pa_tnc_attr_t *(* first_segment)(seg_env_t *this, size_t max_attr_len)
pa_tnc_attr_t *(* next_segment)(seg_env_t *this, bool *last)
bool(* add_segment)(seg_env_t *this, chunk_t segment, pa_tnc_attr_t **error)
void(* destroy)(seg_env_t *this)
Detailed Description
Interface for a PA-TNC attribute segment envelope object
Definition at line 43 of file seg_env.h.
Member Data Documentation
bool(* seg_env_t::add_segment)(seg_env_t *this, chunk_t segment, pa_tnc_attr_t **error)
Generate the first segment envelope of the base attribute
Parameters
segment Attribute segment to be added
error Error attribute if a parsing error occurred return TRUE if segment was successfully added
Definition at line 89 of file seg_env.h.
Referenced by METHOD(), and START_TEST().
void(* seg_env_t::destroy)(seg_env_t *this)
Destroys a seg_env_t object.
Definition at line 95 of file seg_env.h.
Referenced by METHOD(), and START_TEST().
pa_tnc_attr_t*(* seg_env_t::first_segment)(seg_env_t *this, size_t max_attr_len)
Generate the first segment envelope of the base attribute
Parameters
max_attr_len Maximum size of first attribute segment envelope
Returns
First attribute segment envelope
Definition at line 72 of file seg_env.h.
Referenced by METHOD(), and START_TEST().
pa_tnc_attr_t*(* seg_env_t::get_base_attr)(seg_env_t *this)
Get Base Attribute if it contains processed [incremental] data
Returns
Base Attribute (must be destroyed) or NULL
Definition at line 57 of file seg_env.h.
Referenced by METHOD(), and START_TEST().
uint32_t(* seg_env_t::get_base_attr_id)(seg_env_t *this)
Get Base Attribute ID
Returns
Base Attribute ID
Definition at line 50 of file seg_env.h.
Referenced by METHOD(), and START_TEST().
chunk_t(* seg_env_t::get_base_attr_info)(seg_env_t *this)
Base Attribute Info to be used by PA-TNC error messages
Returns
Message info string
Definition at line 64 of file seg_env.h.
Referenced by METHOD().
pa_tnc_attr_t*(* seg_env_t::next_segment)(seg_env_t *this, bool *last)
Generate the next segment envelope of the base attribute
Parameters
last TRUE if last segment
Returns
Next attribute segment envelope
Definition at line 80 of file seg_env.h.
Referenced by METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
seg_env.h