strongSwan: tnc_tnccs_manager
tnc_tnccs_manager
tnc_tnccs
Functions
tnccs_manager_t * tnc_tnccs_manager_create ()
Detailed Description
Function Documentation
tnccs_manager_t* tnc_tnccs_manager_create ()
Create a TNCCS manager instance.
Definition at line 874 of file tnc_tnccs_manager.c.
References INIT, linked_list_create(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by METHOD().
 {
     private_tnc_tnccs_manager_t *this;
     INIT(this,
             .public = {
                 .add_method = _add_method,
                 .remove_method = _remove_method,
                 .create_instance = _create_instance,
                 .create_connection = _create_connection,
                 .remove_connection = _remove_connection,
                 .request_handshake_retry = _request_handshake_retry,
                 .send_message = _send_message,
                 .provide_recommendation = _provide_recommendation,
                 .get_attribute = _get_attribute,
                 .set_attribute = _set_attribute,
                 .destroy = _destroy,
             },
             .protocols = linked_list_create(),
             .connections = linked_list_create(),
             .protocol_lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
             .connection_lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return &this->public;
 }