strongSwan: cpu_feature
cpu_feature
utils
Enumerations
enum cpu_feature_t {
CPU_FEATURE_MMX = (1 << 0), CPU_FEATURE_SSE = (1 << 1), CPU_FEATURE_SSE2 = (1 << 2), CPU_FEATURE_SSE3 = (1 << 3),
CPU_FEATURE_SSSE3 = (1 << 4), CPU_FEATURE_SSE41 = (1 << 5), CPU_FEATURE_SSE42 = (1 << 6), CPU_FEATURE_AVX = (1 << 7),
CPU_FEATURE_RDRAND = (1 << 8), CPU_FEATURE_AESNI = (1 << 9), CPU_FEATURE_PCLMULQDQ = (1 << 10), CPU_FEATURE_PADLOCK_RNG_AVAILABLE = (1 << 22),
CPU_FEATURE_PADLOCK_RNG_ENABLED = (1 << 23), CPU_FEATURE_PADLOCK_ACE_AVAILABLE = (1 << 24), CPU_FEATURE_PADLOCK_ACE_ENABLED = (1 << 25), CPU_FEATURE_PADLOCK_ACE2_AVAILABLE = (1 << 26),
CPU_FEATURE_PADLOCK_ACE2_ENABLED = (1 << 27), CPU_FEATURE_PADLOCK_PHE_AVAILABLE = (1 << 28), CPU_FEATURE_PADLOCK_PHE_ENABLED = (1 << 29), CPU_FEATURE_PADLOCK_PMM_AVAILABLE = (1 << 30),
CPU_FEATURE_PADLOCK_PMM_ENABLED = (1 << 31)
}
Functions
cpu_feature_t cpu_feature_get_all ()
bool cpu_feature_available (cpu_feature_t feature)
Detailed Description
Enumeration Type Documentation
enum cpu_feature_t
Enumerator
CPU_FEATURE_MMX
x86/x64 extensions
CPU_FEATURE_SSE
CPU_FEATURE_SSE2
CPU_FEATURE_SSE3
CPU_FEATURE_SSSE3
CPU_FEATURE_SSE41
CPU_FEATURE_SSE42
CPU_FEATURE_AVX
CPU_FEATURE_RDRAND
CPU_FEATURE_AESNI
CPU_FEATURE_PCLMULQDQ
CPU_FEATURE_PADLOCK_RNG_AVAILABLE
Via Padlock Security features
CPU_FEATURE_PADLOCK_RNG_ENABLED
CPU_FEATURE_PADLOCK_ACE_AVAILABLE
CPU_FEATURE_PADLOCK_ACE_ENABLED
CPU_FEATURE_PADLOCK_ACE2_AVAILABLE
CPU_FEATURE_PADLOCK_ACE2_ENABLED
CPU_FEATURE_PADLOCK_PHE_AVAILABLE
CPU_FEATURE_PADLOCK_PHE_ENABLED
CPU_FEATURE_PADLOCK_PMM_AVAILABLE
CPU_FEATURE_PADLOCK_PMM_ENABLED
Definition at line 26 of file cpu_feature.h.
              {
     CPU_FEATURE_MMX =                           (1 <<  0),
     CPU_FEATURE_SSE =                           (1 <<  1),
     CPU_FEATURE_SSE2 =                          (1 <<  2),
     CPU_FEATURE_SSE3 =                          (1 <<  3),
     CPU_FEATURE_SSSE3 =                         (1 <<  4),
     CPU_FEATURE_SSE41 =                         (1 <<  5),
     CPU_FEATURE_SSE42 =                         (1 <<  6),
     CPU_FEATURE_AVX =                           (1 <<  7),
     CPU_FEATURE_RDRAND =                        (1 <<  8),
     CPU_FEATURE_AESNI =                         (1 <<  9),
     CPU_FEATURE_PCLMULQDQ =                     (1 << 10),
     CPU_FEATURE_PADLOCK_RNG_AVAILABLE =         (1 << 22),
     CPU_FEATURE_PADLOCK_RNG_ENABLED =           (1 << 23),
     CPU_FEATURE_PADLOCK_ACE_AVAILABLE =         (1 << 24),
     CPU_FEATURE_PADLOCK_ACE_ENABLED =           (1 << 25),
     CPU_FEATURE_PADLOCK_ACE2_AVAILABLE =        (1 << 26),
     CPU_FEATURE_PADLOCK_ACE2_ENABLED =          (1 << 27),
     CPU_FEATURE_PADLOCK_PHE_AVAILABLE =         (1 << 28),
     CPU_FEATURE_PADLOCK_PHE_ENABLED =           (1 << 29),
     CPU_FEATURE_PADLOCK_PMM_AVAILABLE =         (1 << 30),
     CPU_FEATURE_PADLOCK_PMM_ENABLED =           (1 << 31),
 } cpu_feature_t;
Function Documentation
bool cpu_feature_available (cpu_feature_t feature)
Check if a given set of CPU features is available.
See header.
Definition at line 155 of file cpu_feature.c.
References cpu_feature_get_all().
Referenced by METHOD().
 {
     return (cpu_feature_get_all() & feature) == feature;
 }
cpu_feature_t cpu_feature_get_all ()
Get a bitmask for all supported CPU features
See header.
Definition at line 145 of file cpu_feature.c.
Referenced by cpu_feature_available(), and padlock_plugin_create().
 {
     return 0;
 }