strongSwan: pts_ima_event_list.c File Reference
pts_ima_event_list.c File Reference
#include "pts_ima_event_list.h"
#include <utils/debug.h>
#include <crypto/hashers/hasher.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
Classes
struct private_pts_ima_event_list_t
struct event_entry_t
Macros
#define IMA_TYPE_LEN 3
#define IMA_NG_TYPE_LEN 6
#define IMA_TYPE_LEN_MAX 10
#define IMA_ALGO_DIGEST_LEN_MAX IMA_ALGO_LEN_MAX + HASH_SIZE_SHA512
Typedefs
typedef struct
private_pts_ima_event_list_t private_pts_ima_event_list_t
typedef struct event_entry_t event_entry_t
Functions
static void free_event_entry (event_entry_t *this)
METHOD (pts_ima_event_list_t, get_time, time_t, private_pts_ima_event_list_t *this)
METHOD (pts_ima_event_list_t, get_count, int, private_pts_ima_event_list_t *this)
METHOD (pts_ima_event_list_t, get_next, status_t, private_pts_ima_event_list_t *this, chunk_t *measurement, char **algo, char **name)
METHOD (pts_ima_event_list_t, destroy, void, private_pts_ima_event_list_t *this)
pts_ima_event_list_t * pts_ima_event_list_create (char *file)
Macro Definition Documentation
#define IMA_ALGO_DIGEST_LEN_MAX IMA_ALGO_LEN_MAX + HASH_SIZE_SHA512
Definition at line 33 of file pts_ima_event_list.c.
Referenced by pts_ima_event_list_create().
#define IMA_NG_TYPE_LEN 6
Definition at line 31 of file pts_ima_event_list.c.
Referenced by pts_ima_event_list_create().
#define IMA_TYPE_LEN 3
Definition at line 30 of file pts_ima_event_list.c.
Referenced by pts_ima_event_list_create().
#define IMA_TYPE_LEN_MAX 10
Definition at line 32 of file pts_ima_event_list.c.
Referenced by pts_ima_event_list_create().
Typedef Documentation
typedef struct event_entry_t event_entry_t
Definition at line 28 of file pts_ima_event_list.c.
typedef struct private_pts_ima_event_list_t private_pts_ima_event_list_t
Definition at line 27 of file pts_ima_event_list.c.
Function Documentation
static void free_event_entry (event_entry_t * this) static
Free an ima_event_t object
Definition at line 82 of file pts_ima_event_list.c.
References free(), and name.
Referenced by METHOD(), and pts_ima_event_list_create().
 {
     free(this->measurement.ptr);
     free(this->algo);
     free(this->name);
     free(this);
 }
METHOD (pts_ima_event_list_t , get_time , time_t , private_pts_ima_event_list_t * this)
Definition at line 90 of file pts_ima_event_list.c.
 {
     return this->creation_time;
 }
METHOD (pts_ima_event_list_t , get_count , int , private_pts_ima_event_list_t * this)
Definition at line 96 of file pts_ima_event_list.c.
References linked_list_t::get_count, and list.
 {
     return this->list->get_count(this->list);
 }
METHOD (pts_ima_event_list_t , get_next , status_t , private_pts_ima_event_list_t * this, chunk_t * measurement, char ** algo, char ** name)
Definition at line 102 of file pts_ima_event_list.c.
References event_entry_t::algo, free(), list, event_entry_t::measurement, event_entry_t::name, linked_list_t::remove_first, and status.
 {
     event_entry_t *entry;
     status_t status;
     status = this->list->remove_first(this->list, (void**)&entry);
     *measurement = entry->measurement;
     *algo = entry->algo;
     *name = entry->name;
     free(entry);
     return status;
 }
METHOD (pts_ima_event_list_t , destroy , void , private_pts_ima_event_list_t * this)
Definition at line 118 of file pts_ima_event_list.c.
References linked_list_t::destroy_function, free(), free_event_entry(), and list.
 {
     this->list->destroy_function(this->list, (void *)free_event_entry);
     free(this);
 }