strongSwan: printf_hook_vstr
printf_hook_vstr
printf_hook
Macros
#define printf vstr_wrapper_printf
#define fprintf vstr_wrapper_fprintf
#define sprintf vstr_wrapper_sprintf
#define snprintf vstr_wrapper_snprintf
#define asprintf vstr_wrapper_asprintf
#define vprintf vstr_wrapper_vprintf
#define vfprintf vstr_wrapper_vfprintf
#define vsprintf vstr_wrapper_vsprintf
#define vsnprintf vstr_wrapper_vsnprintf
#define vasprintf vstr_wrapper_vasprintf
Functions
int vstr_wrapper_printf (const char *format,...)
int vstr_wrapper_fprintf (FILE *stream, const char *format,...)
int vstr_wrapper_sprintf (char *str, const char *format,...)
int vstr_wrapper_snprintf (char *str, size_t size, const char *format,...)
int vstr_wrapper_asprintf (char **str, const char *format,...)
int vstr_wrapper_vprintf (const char *format, va_list ap)
int vstr_wrapper_vfprintf (FILE *stream, const char *format, va_list ap)
int vstr_wrapper_vsprintf (char *str, const char *format, va_list ap)
int vstr_wrapper_vsnprintf (char *str, size_t size, const char *format, va_list ap)
int vstr_wrapper_vasprintf (char **str, const char *format, va_list ap)
Detailed Description
Macro Definition Documentation
#define asprintf vstr_wrapper_asprintf
Definition at line 75 of file printf_hook_vstr.h.
#define fprintf vstr_wrapper_fprintf
Definition at line 72 of file printf_hook_vstr.h.
#define printf vstr_wrapper_printf
Definition at line 71 of file printf_hook_vstr.h.
#define snprintf vstr_wrapper_snprintf
Definition at line 74 of file printf_hook_vstr.h.
#define sprintf vstr_wrapper_sprintf
Definition at line 73 of file printf_hook_vstr.h.
#define vasprintf vstr_wrapper_vasprintf
Definition at line 81 of file printf_hook_vstr.h.
#define vfprintf vstr_wrapper_vfprintf
Definition at line 78 of file printf_hook_vstr.h.
#define vprintf vstr_wrapper_vprintf
Definition at line 77 of file printf_hook_vstr.h.
#define vsnprintf vstr_wrapper_vsnprintf
Definition at line 80 of file printf_hook_vstr.h.
#define vsprintf vstr_wrapper_vsprintf
Definition at line 79 of file printf_hook_vstr.h.
Function Documentation
int vstr_wrapper_asprintf (char ** str, const char * format, ...)
Definition at line 270 of file printf_hook_vstr.c.
References vstr_wrapper_vasprintf().
 {
     int written;
     va_list args;
     va_start(args, format);
     written = vstr_wrapper_vasprintf(str, format, args);
     va_end(args);
     return written;
 }
int vstr_wrapper_fprintf (FILE * stream, const char * format, ...)
Definition at line 240 of file printf_hook_vstr.c.
References vstr_wrapper_vfprintf().
 {
     int written;
     va_list args;
     va_start(args, format);
     written = vstr_wrapper_vfprintf(stream, format, args);
     va_end(args);
     return written;
 }
int vstr_wrapper_printf (const char * format, ...)
Wrapper functions for printf and alike
Definition at line 230 of file printf_hook_vstr.c.
References vstr_wrapper_vprintf().
 {
     int written;
     va_list args;
     va_start(args, format);
     written = vstr_wrapper_vprintf(format, args);
     va_end(args);
     return written;
 }
int vstr_wrapper_snprintf (char * str, size_t size, const char * format, ...)
Definition at line 260 of file printf_hook_vstr.c.
References vstr_wrapper_vsnprintf().
 {
     int written;
     va_list args;
     va_start(args, format);
     written = vstr_wrapper_vsnprintf(str, size, format, args);
     va_end(args);
     return written;
 }
int vstr_wrapper_sprintf (char * str, const char * format, ...)
Definition at line 250 of file printf_hook_vstr.c.
References vstr_wrapper_vsprintf().
 {
     int written;
     va_list args;
     va_start(args, format);
     written = vstr_wrapper_vsprintf(str, format, args);
     va_end(args);
     return written;
 }
int vstr_wrapper_vasprintf (char ** str, const char * format, va_list ap)
Definition at line 365 of file printf_hook_vstr.c.
References len, malloc(), TRUE, and vstr_wrapper_vsnprintf_internal().
Referenced by vstr_wrapper_asprintf().
 {
     size_t len = 100;
     int written;
     *str = malloc(len);
     while (TRUE)
     {
         va_list ac;
         va_copy(ac, args);
         written = vstr_wrapper_vsnprintf_internal(*str, len, format, ac);
         va_end(ac);
         if (written < len)
         {
             break;
         }
         len = written + 1;
         *str = realloc(*str, len);
     }
     return written;
 }
int vstr_wrapper_vfprintf (FILE * stream, const char * format, va_list ap)
Definition at line 317 of file printf_hook_vstr.c.
References conf, get_vstr_conf(), vfprintf, and vstr_wrapper_vprintf_internal().
Referenced by vstr_wrapper_fprintf().
 {
     Vstr_conf *conf;
     conf = get_vstr_conf();
     if (conf)
     {
         return vstr_wrapper_vprintf_internal(conf, stream, format, args);
     }
     return vfprintf(stream, format, args);
 }
int vstr_wrapper_vprintf (const char * format, va_list ap)
Definition at line 305 of file printf_hook_vstr.c.
References conf, get_vstr_conf(), vprintf, and vstr_wrapper_vprintf_internal().
Referenced by vstr_wrapper_printf().
 {
     Vstr_conf *conf;
     conf = get_vstr_conf();
     if (conf)
     {
         return vstr_wrapper_vprintf_internal(conf, stdout, format, args);
     }
     return vprintf(format, args);
 }
int vstr_wrapper_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 355 of file printf_hook_vstr.c.
References vstr_wrapper_vsnprintf_internal().
Referenced by vstr_wrapper_snprintf().
 {
     if (size > 0)
     {
         return vstr_wrapper_vsnprintf_internal(str, size, format, args);
     }
     return 0;
 }
int vstr_wrapper_vsprintf (char * str, const char * format, va_list ap)
Definition at line 350 of file printf_hook_vstr.c.
References vstr_wrapper_vsnprintf_internal().
Referenced by vstr_wrapper_sprintf().
 {
     return vstr_wrapper_vsnprintf_internal(str, 0, format, args);
 }