strongSwan: keychain_creds
keychain_creds
keychain
Classes
struct keychain_creds_t
Typedefs
typedef struct keychain_creds_t keychain_creds_t
Functions
keychain_creds_t * keychain_creds_create ()
Detailed Description
Typedef Documentation
typedef struct keychain_creds_t keychain_creds_t
Definition at line 24 of file keychain_creds.h.
Function Documentation
keychain_creds_t* keychain_creds_create ()
Create a keychain_creds instance.
See header
Definition at line 185 of file keychain_creds.c.
References credential_manager_t::add_set, callback_job_create_with_prio(), cancel_monitor(), library_t::credmgr, INIT, JOB_PRIO_CRITICAL, lib, load_certs(), monitor_changes(), library_t::processor, processor_t::queue_job, SYSTEM, and SYSTEM_ROOTS.
Referenced by load_creds().
 {
     private_keychain_creds_t *this;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
     );
     this->roots = load_certs(this, SYSTEM_ROOTS);
     this->set = load_certs(this, SYSTEM);
     lib->credmgr->add_set(lib->credmgr, &this->roots->set);
     lib->credmgr->add_set(lib->credmgr, &this->set->set);
     lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create_with_prio((void*)monitor_changes,
                     this, NULL, (void*)cancel_monitor, JOB_PRIO_CRITICAL));
     return &this->public;
 }