strongSwan: tcg_pts_attr_aik.c File Reference
tcg_pts_attr_aik.c File Reference
#include "tcg_pts_attr_aik.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_aik_t
Macros
#define PTS_AIK_SIZE 4
#define PTS_AIK_FLAGS_NONE 0
#define PTS_AIK_FLAGS_NAKED_KEY (1<<7)
Typedefs
typedef struct
private_tcg_pts_attr_aik_t private_tcg_pts_attr_aik_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_aik_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_aik_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_aik_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_aik_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_aik_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_aik_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_aik_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_aik_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_aik_t *this)
METHOD (tcg_pts_attr_aik_t, get_aik, certificate_t *, private_tcg_pts_attr_aik_t *this)
pa_tnc_attr_t * tcg_pts_attr_aik_create (certificate_t *aik)
pa_tnc_attr_t * tcg_pts_attr_aik_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define PTS_AIK_FLAGS_NAKED_KEY (1<<7)
Definition at line 41 of file tcg_pts_attr_aik.c.
Referenced by METHOD().
#define PTS_AIK_FLAGS_NONE 0
Definition at line 40 of file tcg_pts_attr_aik.c.
Referenced by METHOD().
#define PTS_AIK_SIZE 4
Attestation Identity Key see section 3.13 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | Attestation Identity Key (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Attestation Identity Key (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 39 of file tcg_pts_attr_aik.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_aik_t private_tcg_pts_attr_aik_t
Definition at line 24 of file tcg_pts_attr_aik.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_aik_t * this)
Definition at line 83 of file tcg_pts_attr_aik.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_aik_t * this)
Definition at line 89 of file tcg_pts_attr_aik.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_aik_t * this)
Definition at line 95 of file tcg_pts_attr_aik.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_aik_t * this, bool noskip)
Definition at line 101 of file tcg_pts_attr_aik.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_aik_t * this)
Definition at line 107 of file tcg_pts_attr_aik.c.
References bio_writer_create(), CERT_ASN1_DER, CERT_TRUSTED_PUBKEY, chunk_empty, DBG1, DBG_TNC, bio_writer_t::destroy, bio_writer_t::extract_buf, flags, free(), length, chunk_t::ptr, PTS_AIK_FLAGS_NAKED_KEY, PTS_AIK_FLAGS_NONE, PTS_AIK_SIZE, PUBKEY_SPKI_ASN1_DER, value, bio_writer_t::write_data, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     u_int8_t flags = PTS_AIK_FLAGS_NONE;
     cred_encoding_type_t encoding_type = CERT_ASN1_DER;
     chunk_t aik_blob;
     if (this->value.ptr)
     {
         return;
     }
     if (this->aik->get_type(this->aik) == CERT_TRUSTED_PUBKEY)
     {
         flags |= PTS_AIK_FLAGS_NAKED_KEY;
         encoding_type = PUBKEY_SPKI_ASN1_DER;
     }
     if (!this->aik->get_encoding(this->aik, encoding_type, &aik_blob))
     {
         DBG1(DBG_TNC, "encoding of Attestation Identity Key failed");
         aik_blob = chunk_empty;
     }
     writer = bio_writer_create(PTS_AIK_SIZE);
     writer->write_uint8(writer, flags);
     writer->write_data (writer, aik_blob);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
     free(aik_blob.ptr);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_aik_t * this, u_int32_t * offset)
Definition at line 138 of file tcg_pts_attr_aik.c.
References bio_reader_create(), BUILD_BLOB_PEM, BUILD_END, CERT_TRUSTED_PUBKEY, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, flags, lib, NEED_MORE, PTS_AIK_FLAGS_NAKED_KEY, PTS_AIK_SIZE, bio_reader_t::read_data, bio_reader_t::read_uint8, bio_reader_t::remaining, SUCCESS, type, and value.
 {
     bio_reader_t *reader;
     u_int8_t flags;
     certificate_type_t type;
     chunk_t aik_blob;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PTS_AIK_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for Attestation Identity Key");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8(reader, &flags);
     reader->read_data (reader, reader->remaining(reader), &aik_blob);
     type = (flags & PTS_AIK_FLAGS_NAKED_KEY) ? CERT_TRUSTED_PUBKEY : CERT_X509;
     this->aik = lib->creds->create(lib->creds, CRED_CERTIFICATE, type,
                                    BUILD_BLOB_PEM, aik_blob, BUILD_END);
     reader->destroy(reader);
     if (!this->aik)
     {
         DBG1(DBG_TNC, "parsing of Attestation Identity Key failed");
         *offset = 0;
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_aik_t * this, chunk_t segment)
Definition at line 176 of file tcg_pts_attr_aik.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_aik_t * this)
Definition at line 182 of file tcg_pts_attr_aik.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_aik_t * this)
Definition at line 189 of file tcg_pts_attr_aik.c.
References DESTROY_IF, free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         DESTROY_IF(this->aik);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_aik_t , get_aik , certificate_t * , private_tcg_pts_attr_aik_t * this)
Definition at line 200 of file tcg_pts_attr_aik.c.
 {
     return this->aik;
 }