strongSwan: lookip.c File Reference
lookip.c File Reference
#include "lookip_msg.h"
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <getopt.h>
#include <arpa/inet.h>
Functions
static int make_connection ()
static int read_all (int fd, void *buf, size_t len, int flags)
static int write_all (int fd, void *buf, size_t len)
static int send_request (int fd, int type, char *vip)
static int receive (int fd, int block, int loop)
static int interactive (int fd)
static void usage (char *cmd)
int main (int argc, char *argv[])
Function Documentation
static int interactive (int fd) static
Interactive IP lookup shell
Definition at line 196 of file lookip.c.
References LOOKIP_END, LOOKIP_LOOKUP, printf, receive(), res, and send_request().
Referenced by main().
 {
     printf("Enter IP address or 'quit'\n");
     while (1)
     {
         char line[64], *pos;
         int res;
         printf("> ");
         fflush(stdout);
         if (fgets(line, sizeof(line), stdin))
         {
             pos = strchr(line, '\n');
             if (pos)
             {
                 *pos = '\0';
             }
             if (strlen(line) == 0)
             {
                 continue;
             }
             if (strcmp(line, "quit") == 0)
             {
                 return send_request(fd, LOOKIP_END, NULL);
             }
             res = send_request(fd, LOOKIP_LOOKUP, line);
             if (res != 0)
             {
                 return res;
             }
             res = receive(fd, 1, 0);
             if (res != 0)
             {
                 return res;
             }
         }
     }
 }
int main (int argc, char * argv[])
Definition at line 251 of file lookip.c.
References close, end, interactive(), LOOKIP_DUMP, LOOKIP_END, LOOKIP_LOOKUP, LOOKIP_REGISTER_DOWN, LOOKIP_REGISTER_UP, make_connection(), receive(), res, send_request(), and usage().
 {
     int fd, res = 0, end = 0;
     struct option long_opts[] = {
         { "help", no_argument, NULL, 'h' },
         { "dump", no_argument, NULL, 'd' },
         { "lookup", required_argument, NULL, 'l' },
         { "listen-up", no_argument, NULL, 'u' },
         { "listen-down", no_argument, NULL, 'c' },
         { 0,0,0,0 }
     };
     fd = make_connection();
     if (fd == -1)
     {
         return 1;
     }
     if (argc == 1)
     {
         res = interactive(fd);
         close(fd);
         return res;
     }
     while (res == 0)
     {
         switch (getopt_long(argc, argv, "", long_opts, NULL))
         {
             case EOF:
                 end = 1;
                 break;
             case 'h':
                 usage(argv[0]);
                 break;
             case 'd':
                 res = send_request(fd, LOOKIP_DUMP, NULL);
                 break;
             case 'l':
                 res = send_request(fd, LOOKIP_LOOKUP, optarg);
                 break;
             case 'u':
                 res = send_request(fd, LOOKIP_REGISTER_UP, NULL);
                 break;
             case 'c':
                 res = send_request(fd, LOOKIP_REGISTER_DOWN, NULL);
                 break;
             default:
                 usage(argv[0]);
                 res = 1;
                 break;
         }
         if (end)
         {
             break;
         }
         if (res == 0)
         {   /* read all currently available results */
             res = receive(fd, 0, 1);
         }
     }
     if (res == 0)
     {
         /* send close message */
         send_request(fd, LOOKIP_END, NULL);
         /* read until socket gets closed */
         res = receive(fd, 1, 1);
     }
     close(fd);
     return res;
 }
static int make_connection () static
Connect to the daemon, return FD
Definition at line 31 of file lookip.c.
References addr, close, connect, fprintf, len, LOOKIP_SOCKET, socket, and strerror.
Referenced by main().
 {
     union {
         struct sockaddr_un un;
         struct sockaddr_in in;
         struct sockaddr sa;
     } addr;
     int fd, len;
     if (getenv("TCP_PORT"))
     {
         addr.in.sin_family = AF_INET;
         addr.in.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
         addr.in.sin_port = htons(atoi(getenv("TCP_PORT")));
         len = sizeof(addr.in);
     }
     else
     {
         addr.un.sun_family = AF_UNIX;
         strcpy(addr.un.sun_path, LOOKIP_SOCKET);
         len = offsetof(struct sockaddr_un, sun_path) + strlen(addr.un.sun_path);
     }
     fd = socket(addr.sa.sa_family, SOCK_STREAM, 0);
     if (fd < 0)
     {
         fprintf(stderr, "opening socket failed: %s\n", strerror(errno));
         return -1;
     }
     if (connect(fd, &addr.sa, len) < 0)
     {
         fprintf(stderr, "connecting failed: %s\n", strerror(errno));
         close(fd);
         return -1;
     }
     return fd;
 }
static int read_all (int fd, void * buf, size_t len, int flags) static
Definition at line 69 of file lookip.c.
References len, and recv.
Referenced by receive().
 {
     ssize_t ret, done = 0;
     while (done < len)
     {
         ret = recv(fd, buf, len - done, flags);
         if (ret == -1 && errno == EINTR)
         {   /* interrupted, try again */
             continue;
         }
         if (ret == 0)
         {
             return 0;
         }
         if (ret < 0)
         {
             return -1;
         }
         done += ret;
         buf += ret;
     }
     return len;
 }
static int receive (int fd, int block, int loop) static
Receive entries from fd. If block is != 0, the call blocks until closed
Definition at line 139 of file lookip.c.
References EWOULDBLOCK, fprintf, lookip_response_t::id, lookip_response_t::ip, LOOKIP_ENTRY, LOOKIP_NOT_FOUND, LOOKIP_NOTIFY_DOWN, LOOKIP_NOTIFY_UP, MSG_DONTWAIT, name, lookip_response_t::name, printf, read_all(), res, snprintf, strerror, lookip_response_t::type, lookip_response_t::unique_id, and lookip_response_t::vip.
Referenced by interactive(), and main().
 {
     lookip_response_t resp;
     char *label, name[32];
     int res;
     do
     {
         res = read_all(fd, &resp, sizeof(resp), block ? 0 : MSG_DONTWAIT);
         if (res == 0)
         {   /* closed by server */
             return 0;
         }
         if (res != sizeof(resp))
         {
             if (!block && (errno == EAGAIN || errno == EWOULDBLOCK))
             {   /* call would block, but we don't */
                 return 0;
             }
             fprintf(stderr, "reading from socket failed: %s\n", strerror(errno));
             return 1;
         }
         switch (ntohl(resp.type))
         {
             case LOOKIP_ENTRY:
                 label = "lookup:";
                 break;
             case LOOKIP_NOT_FOUND:
                 label = "not found:";
                 break;
             case LOOKIP_NOTIFY_UP:
                 label = "up:";
                 break;
             case LOOKIP_NOTIFY_DOWN:
                 label = "down:";
                 break;
             default:
                 fprintf(stderr, "received invalid message type: %d\n", resp.type);
                 return 1;
         }
         resp.vip[sizeof(resp.vip) - 1] = '\0';
         resp.ip[sizeof(resp.ip) - 1] = '\0';
         resp.id[sizeof(resp.id) - 1] = '\0';
         resp.name[sizeof(resp.name) - 1] = '\0';
         snprintf(name, sizeof(name), "%s[%u]", resp.name, ntohl(resp.unique_id));
         printf("%-12s %16s %16s %20s %s\n",
                label, resp.vip, resp.ip, name, resp.id);
     }
     while (loop);
     return 0;
 }
static int send_request (int fd, int type, char * vip) static
Send a request message
Definition at line 118 of file lookip.c.
References fprintf, req(), snprintf, strerror, lookip_request_t::vip, and write_all().
Referenced by interactive(), and main().
 {
     lookip_request_t req = {
         .type = htonl(type),
     };
     if (vip)
     {
         snprintf(req.vip, sizeof(req.vip), "%s", vip);
     }
     if (write_all(fd, &req, sizeof(req)) != sizeof(req))
     {
         fprintf(stderr, "writing to socket failed: %s\n", strerror(errno));
         return 2;
     }
     return 0;
 }
static void usage (char * cmd) static
Print usage information
Definition at line 240 of file lookip.c.
References fprintf.
Referenced by main().
 {
     fprintf(stderr, "Usage:\n");
     fprintf(stderr, "  %s --help\n", cmd);
     fprintf(stderr, "  %s --dump\n", cmd);
     fprintf(stderr, "  %s --lookup <IP>\n", cmd);
     fprintf(stderr, "  %s --listen-up\n", cmd);
     fprintf(stderr, "  %s --listen-down\n", cmd);
     fprintf(stderr, "Any combination of options is allowed.\n");
 }
static int write_all (int fd, void * buf, size_t len) static
Definition at line 94 of file lookip.c.
References len, and write.
Referenced by send_request().
 {
     ssize_t ret, done = 0;
     while (done < len)
     {
         ret = write(fd, buf, len - done);
         if (ret == -1 && errno == EINTR)
         {   /* interrupted, try again */
             continue;
         }
         if (ret < 0)
         {
             return -1;
         }
         done += ret;
         buf += ret;
     }
     return len;
 }