strongSwan: storage.c File Reference
storage.c File Reference
#include "storage.h"
#include <library.h>
#include <crypto/hashers/hasher.h>
Classes
struct private_storage_t
Typedefs
typedef struct private_storage_t private_storage_t
Functions
METHOD (storage_t, login, int, private_storage_t *this, char *username, char *password)
METHOD (storage_t, create_gateway_enumerator, enumerator_t *, private_storage_t *this, int user)
METHOD (storage_t, destroy, void, private_storage_t *this)
storage_t * storage_create (char *uri)
Typedef Documentation
typedef struct private_storage_t private_storage_t
Definition at line 22 of file storage.c.
Function Documentation
METHOD (storage_t , login , int , private_storage_t * this, char * username, char * password)
Definition at line 40 of file storage.c.
References chunk_alloca, chunk_to_hex(), crypto_factory_t::create_hasher, library_t::crypto, data, db, DB_INT, DB_TEXT, enumerator_t::destroy, hasher_t::destroy, enumerator_t::enumerate, FALSE, free(), hasher_t::get_hash, hasher_t::get_hash_size, hash, HASH_SHA1, hasher, lib, memcpy, chunk_t::ptr, and database_t::query.
 {
     hasher_t *hasher;
     chunk_t hash, data, hex_str;
     size_t username_len, password_len;
     int uid = 0;
     enumerator_t *enumerator;
     /* hash = SHA1( username | password ) */
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (hasher == NULL)
     {
         return 0;
     }
     hash = chunk_alloca(hasher->get_hash_size(hasher));
     username_len = strlen(username);
     password_len = strlen(password);
     data = chunk_alloca(username_len + password_len);
     memcpy(data.ptr, username, username_len);
     memcpy(data.ptr + username_len, password, password_len);
     if (!hasher->get_hash(hasher, data, hash.ptr))
     {
         hasher->destroy(hasher);
         return 0;
     }
     hasher->destroy(hasher);
     hex_str = chunk_to_hex(hash, NULL, FALSE);
     enumerator = this->db->query(this->db,
             "SELECT oid FROM users WHERE username = ? AND password = ?;",
             DB_TEXT, username, DB_TEXT, hex_str.ptr,
             DB_INT);
     if (enumerator)
     {
         enumerator->enumerate(enumerator, &uid);
         enumerator->destroy(enumerator);
     }
     free(hex_str.ptr);
     return uid;
 }
METHOD (storage_t , create_gateway_enumerator , enumerator_t * , private_storage_t * this, int user)
Definition at line 82 of file storage.c.
References db, DB_INT, DB_TEXT, enumerator_create_empty(), and database_t::query.
 {
     enumerator_t *enumerator;
     enumerator = this->db->query(this->db,
             "SELECT gateways.oid AS gid, name, port, address FROM "
             "gateways, user_gateway AS ug ON gid = ug.gateway WHERE ug.user = ?;",
             DB_INT, user,
             DB_INT, DB_TEXT, DB_INT, DB_TEXT);
     if (!enumerator)
     {
         enumerator = enumerator_create_empty();
     }
     return enumerator;
 }
METHOD (storage_t , destroy , void , private_storage_t * this)
Definition at line 99 of file storage.c.
References db, database_t::destroy, and free().
 {
     this->db->destroy(this->db);
     free(this);
 }