strongSwan: asn1
asn1
asn1
Macros
#define ASN1_INVALID_LENGTH 0xffffffff
Enumerations
enum asn1_t {
ASN1_EOC = 0x00, ASN1_BOOLEAN = 0x01, ASN1_INTEGER = 0x02, ASN1_BIT_STRING = 0x03,
ASN1_OCTET_STRING = 0x04, ASN1_NULL = 0x05, ASN1_OID = 0x06, ASN1_ENUMERATED = 0x0A,
ASN1_UTF8STRING = 0x0C, ASN1_NUMERICSTRING = 0x12, ASN1_PRINTABLESTRING = 0x13, ASN1_T61STRING = 0x14,
ASN1_VIDEOTEXSTRING = 0x15, ASN1_IA5STRING = 0x16, ASN1_UTCTIME = 0x17, ASN1_GENERALIZEDTIME = 0x18,
ASN1_GRAPHICSTRING = 0x19, ASN1_VISIBLESTRING = 0x1A, ASN1_GENERALSTRING = 0x1B, ASN1_UNIVERSALSTRING = 0x1C,
ASN1_BMPSTRING = 0x1E, ASN1_CONSTRUCTED = 0x20, ASN1_SEQUENCE = 0x30, ASN1_SET = 0x31,
ASN1_CONTEXT_S_0 = 0x80, ASN1_CONTEXT_S_1 = 0x81, ASN1_CONTEXT_S_2 = 0x82, ASN1_CONTEXT_S_3 = 0x83,
ASN1_CONTEXT_S_4 = 0x84, ASN1_CONTEXT_S_5 = 0x85, ASN1_CONTEXT_S_6 = 0x86, ASN1_CONTEXT_S_7 = 0x87,
ASN1_CONTEXT_S_8 = 0x88, ASN1_CONTEXT_C_0 = 0xA0, ASN1_CONTEXT_C_1 = 0xA1, ASN1_CONTEXT_C_2 = 0xA2,
ASN1_CONTEXT_C_3 = 0xA3, ASN1_CONTEXT_C_4 = 0xA4, ASN1_CONTEXT_C_5 = 0xA5, ASN1_INVALID = 0x100
}
Functions
chunk_t asn1_algorithmIdentifier (int oid)
int asn1_known_oid (chunk_t object)
chunk_t asn1_build_known_oid (int n)
chunk_t asn1_oid_from_string (char *str)
char * asn1_oid_to_string (chunk_t oid)
size_t asn1_length (chunk_t *blob)
int asn1_unwrap (chunk_t *blob, chunk_t *content)
int asn1_parse_algorithmIdentifier (chunk_t blob, int level0, chunk_t *params)
bool asn1_parse_simple_object (chunk_t *object, asn1_t type, u_int level0, const char *name)
u_int64_t asn1_parse_integer_uint64 (chunk_t blob)
void asn1_debug_simple_object (chunk_t object, asn1_t type, bool private)
time_t asn1_to_time (const chunk_t *utctime, asn1_t type)
chunk_t asn1_from_time (const time_t *time, asn1_t type)
time_t asn1_parse_time (chunk_t blob, int level0)
bool is_asn1 (chunk_t blob)
bool asn1_is_printablestring (chunk_t str)
u_char * asn1_build_object (chunk_t *object, asn1_t type, size_t datalen)
chunk_t asn1_simple_object (asn1_t tag, chunk_t content)
chunk_t asn1_bitstring (const char *mode, chunk_t content)
chunk_t asn1_integer (const char *mode, chunk_t content)
chunk_t asn1_wrap (asn1_t type, const char *mode,...)
Variables
const chunk_t ASN1_INTEGER_0
const chunk_t ASN1_INTEGER_1
const chunk_t ASN1_INTEGER_2
Detailed Description
Macro Definition Documentation
#define ASN1_INVALID_LENGTH 0xffffffff
Definition at line 81 of file asn1.h.
Referenced by asn1_length(), asn1_parse_simple_object(), is_asn1(), METHOD(), parse_challengePassword(), and START_TEST().
Enumeration Type Documentation
enum asn1_t
Definition of some primitive ASN1 types
Enumerator
ASN1_EOC
ASN1_BOOLEAN
ASN1_INTEGER
ASN1_BIT_STRING
ASN1_OCTET_STRING
ASN1_NULL
ASN1_OID
ASN1_ENUMERATED
ASN1_UTF8STRING
ASN1_NUMERICSTRING
ASN1_PRINTABLESTRING
ASN1_T61STRING
ASN1_VIDEOTEXSTRING
ASN1_IA5STRING
ASN1_UTCTIME
ASN1_GENERALIZEDTIME
ASN1_GRAPHICSTRING
ASN1_VISIBLESTRING
ASN1_GENERALSTRING
ASN1_UNIVERSALSTRING
ASN1_BMPSTRING
ASN1_CONSTRUCTED
ASN1_SEQUENCE
ASN1_SET
ASN1_CONTEXT_S_0
ASN1_CONTEXT_S_1
ASN1_CONTEXT_S_2
ASN1_CONTEXT_S_3
ASN1_CONTEXT_S_4
ASN1_CONTEXT_S_5
ASN1_CONTEXT_S_6
ASN1_CONTEXT_S_7
ASN1_CONTEXT_S_8
ASN1_CONTEXT_C_0
ASN1_CONTEXT_C_1
ASN1_CONTEXT_C_2
ASN1_CONTEXT_C_3
ASN1_CONTEXT_C_4
ASN1_CONTEXT_C_5
ASN1_INVALID
Definition at line 33 of file asn1.h.
              {
     ASN1_EOC =              0x00,
     ASN1_BOOLEAN =          0x01,
     ASN1_INTEGER =          0x02,
     ASN1_BIT_STRING =       0x03,
     ASN1_OCTET_STRING =     0x04,
     ASN1_NULL =             0x05,
     ASN1_OID =              0x06,
     ASN1_ENUMERATED =       0x0A,
     ASN1_UTF8STRING =       0x0C,
     ASN1_NUMERICSTRING =    0x12,
     ASN1_PRINTABLESTRING =  0x13,
     ASN1_T61STRING =        0x14,
     ASN1_VIDEOTEXSTRING =   0x15,
     ASN1_IA5STRING =        0x16,
     ASN1_UTCTIME =          0x17,
     ASN1_GENERALIZEDTIME =  0x18,
     ASN1_GRAPHICSTRING =    0x19,
     ASN1_VISIBLESTRING =    0x1A,
     ASN1_GENERALSTRING =    0x1B,
     ASN1_UNIVERSALSTRING =  0x1C,
     ASN1_BMPSTRING =        0x1E,
     ASN1_CONSTRUCTED =      0x20,
     ASN1_SEQUENCE =         0x30,
     ASN1_SET =              0x31,
     ASN1_CONTEXT_S_0 =      0x80,
     ASN1_CONTEXT_S_1 =      0x81,
     ASN1_CONTEXT_S_2 =      0x82,
     ASN1_CONTEXT_S_3 =      0x83,
     ASN1_CONTEXT_S_4 =      0x84,
     ASN1_CONTEXT_S_5 =      0x85,
     ASN1_CONTEXT_S_6 =      0x86,
     ASN1_CONTEXT_S_7 =      0x87,
     ASN1_CONTEXT_S_8 =      0x88,
     ASN1_CONTEXT_C_0 =      0xA0,
     ASN1_CONTEXT_C_1 =      0xA1,
     ASN1_CONTEXT_C_2 =      0xA2,
     ASN1_CONTEXT_C_3 =      0xA3,
     ASN1_CONTEXT_C_4 =      0xA4,
     ASN1_CONTEXT_C_5 =      0xA5,
     ASN1_INVALID =          0x100,
 } asn1_t;
Function Documentation
chunk_t asn1_algorithmIdentifier (int oid)
Some ASN.1 analysis functions Build an algorithmIdentifier from a known OID.
Parameters
oid known OID index
Returns
body of the corresponding OID, allocated
Definition at line 38 of file asn1.c.
References asn1_build_known_oid(), ASN1_NULL, ASN1_SEQUENCE, asn1_simple_object(), asn1_wrap(), chunk_empty, OID_ECDSA_WITH_SHA1, OID_ECDSA_WITH_SHA224, OID_ECDSA_WITH_SHA256, OID_ECDSA_WITH_SHA384, and OID_ECDSA_WITH_SHA512.
Referenced by build_ac(), build_attr_cert_info(), build_emsa_pkcs1_signature(), build_optionalSignature(), build_pub_info(), build_Request(), build_signature_auth_data(), generate(), scep_generate_transaction_id(), and START_TEST().
 {
     chunk_t parameters;
     /* some algorithmIdentifiers have a NULL parameters field and some do not */
     switch (oid)
     {
         case OID_ECDSA_WITH_SHA1:
         case OID_ECDSA_WITH_SHA224:
         case OID_ECDSA_WITH_SHA256:
         case OID_ECDSA_WITH_SHA384:
         case OID_ECDSA_WITH_SHA512:
             parameters = chunk_empty;
             break;
         default:
             parameters = asn1_simple_object(ASN1_NULL, chunk_empty);
             break;
     }
     return asn1_wrap(ASN1_SEQUENCE, "mm", asn1_build_known_oid(oid), parameters);
 }
chunk_t asn1_bitstring (const char * mode, chunk_t content)
Build an ASN.1 BITSTRING object
Parameters
mode 'c' for copy or 'm' for move
content content of the BITSTRING
Returns
chunk containing the ASN.1 coded BITSTRING
Build an ASN.1 BIT_STRING object
Definition at line 804 of file asn1.c.
References ASN1_BIT_STRING, asn1_build_object(), free(), chunk_t::len, memcpy, and chunk_t::ptr.
Referenced by bliss_public_key_info_encode(), build_ac(), build_optionalSignature(), build_pub_info(), encode_ecdsa(), generate(), METHOD(), parse_public_key(), scep_generate_transaction_id(), and START_TEST().
 {
     chunk_t object;
     u_char *pos = asn1_build_object(&object, ASN1_BIT_STRING, 1 + content.len);
     *pos++ = 0x00;
     memcpy(pos, content.ptr, content.len);
     if (*mode == 'm')
     {
         free(content.ptr);
     }
     return object;
 }
chunk_t asn1_build_known_oid (int n)
Converts a known OID index to an ASN.1 OID
Parameters
n index into the oid_names[] table
Returns
allocated OID chunk, chunk_empty if index out of range
Definition at line 97 of file asn1.c.
References ASN1_OID, chunk_alloc, chunk_empty, oid_t::level, n, oid_t::octet, OID_MAX, oid_names, and chunk_t::ptr.
Referenced by asn1_algorithmIdentifier(), atodn(), bliss_public_key_info_encode(), build_attribute_type(), build_authorityKeyIdentifier(), build_encoding(), ecparams_lookup(), encode_ecdsa(), generate(), METHOD(), parse_ec_identifier(), parse_public_key(), pkcs7_data_gen(), START_TEST(), x509_build_crlDistributionPoints(), and x509_build_subjectAltNames().
 {
     chunk_t oid;
     int i;
     if (n < 0 || n >= OID_MAX)
     {
         return chunk_empty;
     }
     i = oid_names[n].level + 1;
     oid = chunk_alloc(2 + i);
     oid.ptr[0] = ASN1_OID;
     oid.ptr[1] = i;
     do
     {
         if (oid_names[n].level >= i)
         {
             n--;
             continue;
         }
         oid.ptr[--i + 2] = oid_names[n--].octet;
     }
     while (i > 0);
     return oid;
 }
u_char* asn1_build_object (chunk_t * object, asn1_t type, size_t datalen)
some ASN.1 synthesis functions Build an empty ASN.1 object with tag and length fields already filled in
Parameters
object returned object - memory is allocated by function
type ASN.1 type to be created
datalen size of the body to be created
Returns
points to the first position in the body
build an empty asn.1 object with tag and length fields already filled in
Definition at line 761 of file asn1.c.
References asn1_code_length(), chunk_t::len, length, malloc(), memcpy, chunk_t::ptr, and type.
Referenced by asn1_bitstring(), asn1_integer(), asn1_simple_object(), asn1_wrap(), atodn(), build_attributes(), build_encoding(), and START_TEST().
 {
     u_char length_buf[4];
     chunk_t length = { length_buf, 0 };
     u_char *pos;
     /* code the asn.1 length field */
     asn1_code_length(datalen, &length);
     /* allocate memory for the asn.1 TLV object */
     object->len = 1 + length.len + datalen;
     object->ptr = malloc(object->len);
     /* set position pointer at the start of the object */
     pos = object->ptr;
     /* copy the asn.1 tag field and advance the pointer */
     *pos++ = type;
     /* copy the asn.1 length field and advance the pointer */
     memcpy(pos, length.ptr, length.len);
     pos += length.len;
     return pos;
 }
void asn1_debug_simple_object (chunk_t object, asn1_t type, bool private)
Print the value of an ASN.1 simple object
Parameters
object ASN.1 object to be printed
type asn1_t type
private ASN.1 data is confidential (use debug level 4)
Definition at line 504 of file asn1.c.
References ASN1_GENERALIZEDTIME, ASN1_IA5STRING, asn1_known_oid(), ASN1_OID, asn1_oid_to_string(), ASN1_PRINTABLESTRING, ASN1_T61STRING, asn1_to_time(), ASN1_UTCTIME, ASN1_UTF8STRING, ASN1_VISIBLESTRING, DBG2, DBG3, DBG4, DBG_ASN, free(), len, name, oid_names, OID_UNKNOWN, and TRUE.
Referenced by asn1_parse_simple_object(), and METHOD().
 {
     int oid;
     switch (type)
     {
         case ASN1_OID:
             oid = asn1_known_oid(object);
             if (oid == OID_UNKNOWN)
             {
                 char *oid_str = asn1_oid_to_string(object);
                 if (!oid_str)
                 {
                     break;
                 }
                 DBG2(DBG_ASN, "  %s", oid_str);
                 free(oid_str);
             }
             else
             {
                 DBG2(DBG_ASN, "  '%s'", oid_names[oid].name);
             }
             return;
         case ASN1_UTF8STRING:
         case ASN1_IA5STRING:
         case ASN1_PRINTABLESTRING:
         case ASN1_T61STRING:
         case ASN1_VISIBLESTRING:
             DBG2(DBG_ASN, "  '%.*s'", (int)object.len, object.ptr);
             return;
         case ASN1_UTCTIME:
         case ASN1_GENERALIZEDTIME:
             {
                 time_t time = asn1_to_time(&object, type);
                 DBG2(DBG_ASN, "  '%T'", &time, TRUE);
             }
             return;
         default:
             break;
     }
     if (private)
     {
         DBG4(DBG_ASN, "%B", &object);
     }
     else
     {
         DBG3(DBG_ASN, "%B", &object);
     }
 }
chunk_t asn1_from_time (const time_t * time, asn1_t type)
Converts time_t to an ASN.1 UTCTIME or GENERALIZEDTIME string
Note
The type is automatically changed to GENERALIZEDTIME if needed
Parameters
time time_t in UTC
type ASN1_UTCTIME or ASN1_GENERALIZEDTIME
Returns
body of an ASN.1 code time object
Convert a date into ASN.1 UTCTIME or GENERALIZEDTIME format
Definition at line 470 of file asn1.c.
References ASN1_GENERALIZEDTIME, asn1_simple_object(), BUF_LEN, gmtime_r(), chunk_t::len, offset, chunk_t::ptr, and snprintf.
Referenced by build_attr_cert_validity(), generate(), and START_TEST().
 {
     int offset;
     const char *format;
     char buf[BUF_LEN];
     chunk_t formatted_time;
     struct tm t = {};
     gmtime_r(time, &t);
     /* RFC 5280 says that dates through the year 2049 MUST be encoded as UTCTIME
      * and dates in 2050 or later MUST be encoded as GENERALIZEDTIME. We only
      * enforce the latter to avoid overflows but allow callers to force the
      * encoding to GENERALIZEDTIME */
     type = (t.tm_year >= 150) ? ASN1_GENERALIZEDTIME : type;
     if (type == ASN1_GENERALIZEDTIME)
     {
         format = "%04d%02d%02d%02d%02d%02dZ";
         offset = 1900;
     }
     else /* ASN1_UTCTIME */
     {
         format = "%02d%02d%02d%02d%02d%02dZ";
         offset = (t.tm_year < 100) ? 0 : -100;
     }
     snprintf(buf, BUF_LEN, format, t.tm_year + offset,
              t.tm_mon + 1, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec);
     formatted_time.ptr = buf;
     formatted_time.len = strlen(buf);
     return asn1_simple_object(type, formatted_time);
 }
chunk_t asn1_integer (const char * mode, chunk_t content)
Build an ASN.1 INTEGER object
Parameters
mode 'c' for copy or 'm' for move
content content of the INTEGER
Returns
chunk containing the ASN.1 coded INTEGER
Build an ASN.1 INTEGER object
Definition at line 821 of file asn1.c.
References asn1_build_object(), ASN1_INTEGER, chunk_from_chars, FALSE, free(), chunk_t::len, len, memcpy, and chunk_t::ptr.
Referenced by build_issuerAndSerialNumber(), build_priv(), build_pub(), build_pub_info(), generate(), METHOD(), and START_TEST().
 {
     chunk_t object;
     size_t len;
     u_char *pos;
     bool move;
     if (content.len == 0)
     {   /* make sure 0 is encoded properly */
         content = chunk_from_chars(0x00);
         move = FALSE;
     }
     else
     {
         move = (*mode == 'm');
     }
     /* ASN.1 integers must be positive numbers in two's complement */
     len = content.len + ((*content.ptr & 0x80) ? 1 : 0);
     pos = asn1_build_object(&object, ASN1_INTEGER, len);
     if (len > content.len)
     {
         *pos++ = 0x00;
     }
     memcpy(pos, content.ptr, content.len);
     if (move)
     {
         free(content.ptr);
     }
     return object;
 }
bool asn1_is_printablestring (chunk_t str)
Determines if a character string can be coded as PRINTABLESTRING
Parameters
str character string to be tested
Returns
TRUE if no special characters are contained
Definition at line 709 of file asn1.c.
References FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by atodn(), generate(), and START_TEST().
 {
     const char printablestring_charset[] =
         "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 '()+,-./:=?";
     u_int i;
     for (i = 0; i < str.len; i++)
     {
         if (strchr(printablestring_charset, str.ptr[i]) == NULL)
         {
             return FALSE;
         }
     }
     return TRUE;
 }
int asn1_known_oid (chunk_t object)
Converts an ASN.1 OID into a known OID index
Parameters
object body of an OID
Returns
index into the oid_names[] table or OID_UNKNOWN
Definition at line 62 of file asn1.c.
 {
     int oid = 0;
     while (object.len)
     {
         if (oid_names[oid].octet == *object.ptr)
         {
             if (--object.len == 0 || oid_names[oid].down == 0)
             {
                 return oid;       /* found terminal symbol */
             }
             else
             {
                 object.ptr++; oid++; /* advance to next hex octet */
             }
         }
         else
         {
             if (oid_names[oid].next)
             {
                 oid = oid_names[oid].next;
             }
             else
             {
                 return OID_UNKNOWN;
             }
         }
     }
     return OID_UNKNOWN;
 }
size_t asn1_length (chunk_t * blob)
Returns the length of an ASN.1 object The blob pointer is advanced past the tag length fields
Parameters
blob pointer to an ASN.1 coded blob
Returns
length of ASN.1 object
Definition at line 235 of file asn1.c.
References ASN1_INVALID_LENGTH, DBG2, DBG_ASN, chunk_t::len, len, n, and chunk_t::ptr.
Referenced by asn1_parse_simple_object(), is_asn1(), METHOD(), parse(), parse_challengePassword(), and START_TEST().
 {
     u_char n;
     size_t len;
     if (blob->len < 2)
     {
         DBG2(DBG_ASN, "insufficient number of octets to parse ASN.1 length");
         return ASN1_INVALID_LENGTH;
     }
     /* read length field, skip tag and length */
     n = blob->ptr[1];
     blob->ptr += 2;
     blob->len -= 2;
     if ((n & 0x80) == 0)
     {   /* single length octet */
         if (n > blob->len)
         {
             DBG2(DBG_ASN, "length is larger than remaining blob size");
             return ASN1_INVALID_LENGTH;
         }
         return n;
     }
     /* composite length, determine number of length octets */
     n &= 0x7f;
     if (n == 0 || n > blob->len)
     {
         DBG2(DBG_ASN, "number of length octets invalid");
         return ASN1_INVALID_LENGTH;
     }
     if (n > sizeof(len))
     {
         DBG2(DBG_ASN, "number of length octets is larger than limit of"
              " %d octets", (int)sizeof(len));
         return ASN1_INVALID_LENGTH;
     }
     len = 0;
     while (n-- > 0)
     {
         len = 256*len + *blob->ptr++;
         blob->len--;
     }
     if (len > blob->len)
     {
         DBG2(DBG_ASN, "length is larger than remaining blob size");
         return ASN1_INVALID_LENGTH;
     }
     return len;
 }
chunk_t asn1_oid_from_string (char * str)
Convert human readable OID to ASN.1 DER encoding, without OID header.
Parameters
str OID string (e.g. 1.2.345.67.8)
Returns
allocated ASN.1 encoded OID, chunk_empty on error
Definition at line 147 of file asn1.c.
References bytes_required(), chunk_clone, chunk_create(), enumerator_t::destroy, end, enumerator_t::enumerate, enumerator_create_token(), req(), and val.
Referenced by create_cert_ext(), issue(), main(), parse_ec_identifier(), self(), and START_TEST().
 {
     enumerator_t *enumerator;
     size_t buf_len = 64;
     u_char buf[buf_len];
     char *end;
     int i = 0, pos = 0, req, shift;
     u_int val, first = 0;
     enumerator = enumerator_create_token(str, ".", "");
     while (enumerator->enumerate(enumerator, &str))
     {
         val = strtoul(str, &end, 10);
         req = bytes_required(val);
         if (end == str || pos + req > buf_len)
         {
             pos = 0;
             break;
         }
         switch (i++)
         {
             case 0:
                 first = val;
                 break;
             case 1:
                 buf[pos++] = first * 40 + val;
                 break;
             default:
                 for (shift = (req - 1) * 7; shift; shift -= 7)
                 {
                     buf[pos++] = 0x80 | ((val >> shift) & 0x7F);
                 }
                 buf[pos++] = val & 0x7F;
         }
     }
     enumerator->destroy(enumerator);
     return chunk_clone(chunk_create(buf, pos));
 }
char* asn1_oid_to_string (chunk_t oid)
Convert a DER encoded ASN.1 OID to a human readable string.
Parameters
oid DER encoded OID, without header
Returns
human readable OID string, allocated, NULL on error
Definition at line 190 of file asn1.c.
References chunk_skip(), chunk_t::len, len, chunk_t::ptr, snprintf, strdup, and val.
Referenced by asn1_debug_simple_object(), check_policy(), check_policy_constraints(), print_ac(), print_x509(), START_TEST(), stroke_list_acerts(), and write_ec_identifier().
 {
     size_t len = 64;
     char buf[len], *pos = buf;
     int written;
     u_int val;
     if (!oid.len)
     {
         return NULL;
     }
     val = oid.ptr[0] / 40;
     written = snprintf(buf, len, "%u.%u", val, oid.ptr[0] - val * 40);
     oid = chunk_skip(oid, 1);
     if (written < 0 || written >= len)
     {
         return NULL;
     }
     pos += written;
     len -= written;
     val = 0;
     while (oid.len)
     {
         val = (val << 7) + (u_int)(oid.ptr[0] & 0x7f);
         if (oid.ptr[0] < 128)
         {
             written = snprintf(pos, len, ".%u", val);
             if (written < 0 || written >= len)
             {
                 return NULL;
             }
             pos += written;
             len -= written;
             val = 0;
         }
         oid = chunk_skip(oid, 1);
     }
     return (val == 0) ? strdup(buf) : NULL;
 }
int asn1_parse_algorithmIdentifier (chunk_t blob, int level0, chunk_t * params)
Parses an ASN.1 algorithmIdentifier object
Parameters
blob ASN.1 coded blob
level0 top-most level offset
params returns optional [ASN.1 coded] parameters
Returns
known OID index or OID_UNKNOWN
Definition at line 630 of file asn1.c.
References alg, ALGORITHM_ID_ALG, ALGORITHM_ID_PARAMETERS_OCT, ALGORITHM_ID_PARAMETERS_OID, ALGORITHM_ID_PARAMETERS_SEQ, asn1_known_oid(), asn1_parser_create(), asn1_parser_t::destroy, asn1_parser_t::iterate, OID_UNKNOWN, parser, and asn1_parser_t::set_top_level.
Referenced by bliss_public_key_load(), build_public_key(), parse(), parse_basicOCSPResponse(), parse_certificate(), parse_certificate_request(), parse_digest_info(), parse_pbes2_params(), parse_private_key(), parse_public_key(), parse_signature_auth_data(), parse_singleResponse(), pkcs5_from_algorithmIdentifier(), START_TEST(), and verify_emsa_pkcs1_signature().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int alg = OID_UNKNOWN;
     parser = asn1_parser_create(algorithmIdentifierObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case ALGORITHM_ID_ALG:
                 alg = asn1_known_oid(object);
                 break;
             case ALGORITHM_ID_PARAMETERS_OID:
             case ALGORITHM_ID_PARAMETERS_SEQ:
             case ALGORITHM_ID_PARAMETERS_OCT:
                 if (parameters != NULL)
                 {
                     *parameters = object;
                 }
                 break;
             default:
                 break;
         }
     }
     parser->destroy(parser);
     return alg;
 }
u_int64_t asn1_parse_integer_uint64 (chunk_t blob)
Converts an ASN.1 INTEGER object to an u_int64_t. If the INTEGER is longer than 8 bytes only the 8 LSBs are returned.
Parameters
blob body of an ASN.1 coded integer object
Returns
converted integer
Definition at line 595 of file asn1.c.
References chunk_t::len, chunk_t::ptr, and val.
Referenced by parse_pbes1_params(), parse_pbkdf2_params(), parse_PFX(), and START_TEST().
 {
     u_int64_t val = 0;
     int i;
     for (i = 0; i < blob.len; i++)
     {   /* if it is longer than 8 bytes, we just use the 8 LSBs */
         val <<= 8;
         val |= (u_int64_t)blob.ptr[i];
     }
     return val;
 }
bool asn1_parse_simple_object (chunk_t * object, asn1_t type, u_int level, const char * name)
Parse the top-most level of an ASN.1 object
Parameters
object ASN.1 coded object
type Expected ASN.1 type
level0 top-most level offset
name descriptive name of object
Returns
TRUE if parsing successful
parse an ASN.1 simple type
Definition at line 559 of file asn1.c.
References asn1_debug_simple_object(), ASN1_INVALID_LENGTH, asn1_length(), DBG2, DBG_ASN, FALSE, chunk_t::len, len, chunk_t::ptr, and TRUE.
Referenced by add_certificate(), bliss_public_key_load(), keylen_from_ecparams(), parse(), parse_certificate(), parse_otherName(), parse_pbes2_params(), and START_TEST().
 {
     size_t len;
     /* an ASN.1 object must possess at least a tag and length field */
     if (object->len < 2)
     {
         DBG2(DBG_ASN, "L%d - %s:  ASN.1 object smaller than 2 octets", level,
              name);
         return FALSE;
     }
     if (*object->ptr != type)
     {
         DBG2(DBG_ASN, "L%d - %s: ASN1 tag 0x%02x expected, but is 0x%02x",
              level, name, type, *object->ptr);
         return FALSE;
     }
     len = asn1_length(object);
     if (len == ASN1_INVALID_LENGTH)
     {
         DBG2(DBG_ASN, "L%d - %s:  length of ASN.1 object invalid or too large",
              level, name);
         return FALSE;
     }
     DBG2(DBG_ASN, "L%d - %s:", level, name);
     asn1_debug_simple_object(*object, type, FALSE);
     return TRUE;
 }
time_t asn1_parse_time (chunk_t blob, int level0)
Parse an ASN.1 UTCTIME or GENERALIZEDTIME object
Parameters
blob ASN.1 coded time object
level0 top-most level offset
Returns
time_t in UTC
extracts and converts a UTCTIME or GENERALIZEDTIME object
Definition at line 926 of file asn1.c.
References ASN1_GENERALIZEDTIME, asn1_parser_create(), asn1_to_time(), ASN1_UTCTIME, asn1_parser_t::destroy, asn1_parser_t::iterate, parser, asn1_parser_t::set_top_level, TIME_GENERALIZED, TIME_UTC, and utc_time.
Referenced by parse(), parse_certificate(), and START_TEST().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     time_t utc_time = 0;
     parser= asn1_parser_create(timeObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         if (objectID == TIME_UTC || objectID == TIME_GENERALIZED)
         {
             utc_time = asn1_to_time(&object, (objectID == TIME_UTC)
                                     ? ASN1_UTCTIME : ASN1_GENERALIZEDTIME);
         }
     }
     parser->destroy(parser);
     return utc_time;
 }
chunk_t asn1_simple_object (asn1_t tag, chunk_t content)
Build a simple ASN.1 object
Parameters
tag ASN.1 type to be created
content content of the ASN.1 object
Returns
chunk containing the ASN.1 coded object
Build a simple ASN.1 object
Definition at line 790 of file asn1.c.
References asn1_build_object(), chunk_t::len, memcpy, and chunk_t::ptr.
Referenced by asn1_algorithmIdentifier(), asn1_from_time(), build_attr_cert_info(), build_attributes(), build_authorityKeyIdentifier(), build_directoryName(), build_emsa_pkcs1_signature(), build_holder(), build_nonce(), build_Request(), build_requestorName(), generate(), and START_TEST().
 {
     chunk_t object;
     u_char *pos = asn1_build_object(&object, tag, content.len);
     memcpy(pos, content.ptr, content.len);
     pos += content.len;
     return object;
 }
time_t asn1_to_time (const chunk_t * utctime, asn1_t type)
Converts an ASN.1 UTCTIME or GENERALIZEDTIME string to time_t
On systems where sizeof(time_t) == 4 there will be an overflow for dates
Tue, 19 Jan 2038 03:14:07 UTC (0x7fffffff)
and < Fri, 13 Dec 1901 20:45:52 UTC (0x80000000) in both cases TIME_32_BIT_SIGNED_MAX is returned.
Parameters
utctime body of an ASN.1 coded time object
type ASN1_UTCTIME or ASN1_GENERALIZEDTIME
Returns
time_t in UTC
Converts ASN.1 UTCTIME or GENERALIZEDTIME into calendar time
Definition at line 345 of file asn1.c.
References ASN1_UTCTIME, days, chunk_t::len, chunk_t::ptr, TIME_32_BIT_SIGNED_MAX, and tm_leap_1970.
Referenced by asn1_debug_simple_object(), asn1_parse_time(), main(), parse_basicOCSPResponse(), parse_certificate(), parse_singleResponse(), START_TEST(), and verify().
 {
     int tm_year, tm_mon, tm_day, tm_hour, tm_min, tm_sec;
     int tm_leap_4, tm_leap_100, tm_leap_400, tm_leap;
     int tz_hour, tz_min, tz_offset;
     time_t tm_days, tm_secs;
     u_char *eot = NULL;
     if ((eot = memchr(utctime->ptr, 'Z', utctime->len)) != NULL)
     {
         tz_offset = 0; /* Zulu time with a zero time zone offset */
     }
     else if ((eot = memchr(utctime->ptr, '+', utctime->len)) != NULL)
     {
         if (sscanf(eot+1, "%2d%2d", &tz_hour, &tz_min) != 2)
         {
             return 0; /* error in positive timezone offset format */
         }
         tz_offset = 3600*tz_hour + 60*tz_min;  /* positive time zone offset */
     }
     else if ((eot = memchr(utctime->ptr, '-', utctime->len)) != NULL)
     {
         if (sscanf(eot+1, "%2d%2d", &tz_hour, &tz_min) != 2)
         {
             return 0; /* error in negative timezone offset format */
         }
         tz_offset = -3600*tz_hour - 60*tz_min;  /* negative time zone offset */
     }
     else
     {
         return 0; /* error in time format */
     }
     /* parse ASN.1 time string */
     {
         const char* format = (type == ASN1_UTCTIME)? "%2d%2d%2d%2d%2d":
                                                      "%4d%2d%2d%2d%2d";
         if (sscanf(utctime->ptr, format, &tm_year, &tm_mon, &tm_day,
                                          &tm_hour, &tm_min) != 5)
         {
             return 0; /* error in [yy]yymmddhhmm time format */
         }
     }
     /* is there a seconds field? */
     if ((eot - utctime->ptr) == ((type == ASN1_UTCTIME)?12:14))
     {
         if (sscanf(eot-2, "%2d", &tm_sec) != 1)
         {
             return 0; /* error in ss seconds field format */
         }
     }
     else
     {
         tm_sec = 0;
     }
     /* representation of two-digit years */
     if (type == ASN1_UTCTIME)
     {
         tm_year += (tm_year < 50) ? 2000 : 1900;
     }
     /* prevent obvious 32 bit integer overflows */
     if (sizeof(time_t) == 4 && (tm_year > 2038 || tm_year < 1901))
     {
         return TIME_32_BIT_SIGNED_MAX;
     }
     /* representation of months as 0..11*/
     if (tm_mon < 1 || tm_mon > 12)
     {
         return 0;
     }
     tm_mon--;
     /* representation of days as 0..30 */
     if (tm_day < 1 || tm_day > 31)
     {   /* we don't actually validate the day in relation to tm_year/tm_mon */
         return 0;
     }
     tm_day--;
     if (tm_hour < 0 || tm_hour > 23 ||
         tm_min < 0 || tm_min > 59 ||
         tm_sec < 0 || tm_sec > 60 /* allow leap seconds */)
     {
         return 0;
     }
     /* number of leap years between last year and 1970? */
     tm_leap_4 = (tm_year - 1) / 4;
     tm_leap_100 = tm_leap_4 / 25;
     tm_leap_400 = tm_leap_100 / 4;
     tm_leap = tm_leap_4 - tm_leap_100 + tm_leap_400 - tm_leap_1970;
     /* if date later then February, is the current year a leap year? */
     if (tm_mon > 1 && (tm_year % 4 == 0) &&
         (tm_year % 100 != 0 || tm_year % 400 == 0))
     {
         tm_leap++;
     }
     tm_days = 365 * (tm_year - 1970) + days[tm_mon] + tm_day + tm_leap;
     tm_secs = 60 * (60 * (24 * tm_days + tm_hour) + tm_min) + tm_sec - tz_offset;
     if (sizeof(time_t) == 4)
     {   /* has a 32 bit signed integer overflow occurred? */
         if (tm_year > 1970 && tm_secs < 0)
         {   /* depending on the time zone, the first days in 1970 may result in
              * a negative value, but dates after 1970 never will */
             return TIME_32_BIT_SIGNED_MAX;
         }
         if (tm_year < 1969 && tm_secs > 0)
         {   /* similarly, tm_secs is not positive for dates before 1970, except
              * for the last days in 1969, depending on the time zone */
             return TIME_32_BIT_SIGNED_MAX;
         }
     }
     return tm_secs;
 }
int asn1_unwrap (chunk_t * blob, chunk_t * content)
Unwrap the inner content of an ASN.1 type/length wrapped object.
Parameters
blob blob to parse header from, moved behind parsed content
content inner content
Returns
parsed type, ASN1_INVALID if length parsing failed
Definition at line 295 of file asn1.c.
References ASN1_INVALID, chunk_skip(), chunk_t::len, len, chunk_t::ptr, res, and type.
Referenced by build_public_key(), create_rdn_enumerator(), METHOD(), parse_keyUsage(), START_TEST(), and unwrap_ec_point().
 {
     chunk_t res;
     u_char len;
     int type;
     if (blob->len < 2)
     {
         return ASN1_INVALID;
     }
     type = blob->ptr[0];
     len = blob->ptr[1];
     *blob = chunk_skip(*blob, 2);
     if ((len & 0x80) == 0)
     {   /* single length octet */
         res.len = len;
     }
     else
     {   /* composite length, determine number of length octets */
         len &= 0x7f;
         if (len == 0 || len > blob->len || len > sizeof(res.len))
         {
             return ASN1_INVALID;
         }
         res.len = 0;
         while (len-- > 0)
         {
             res.len = 256 * res.len + blob->ptr[0];
             *blob = chunk_skip(*blob, 1);
         }
     }
     if (res.len > blob->len)
     {
         return ASN1_INVALID;
     }
     res.ptr = blob->ptr;
     *blob = chunk_skip(*blob, res.len);
     /* updating inner not before we are finished allows a caller to pass
      * blob = inner */
     *inner = res;
     return type;
 }
chunk_t asn1_wrap (asn1_t type, const char * mode, ...)
Build an ASN.1 object from a variable number of individual chunks
The mode string specifies the number of chunks, and how to handle each of them with a single character: 'c' for copy (allocate new chunk), 'm' for move (free given chunk) or 's' for sensitive-copy (clear given chunk, then free).
Parameters
type ASN.1 type to be created
mode for each list member: 'c', 'm' or 's'
Returns
chunk containing the ASN.1 coded object
Build an ASN.1 object from a variable number of individual chunks. Depending on the mode, chunks either are moved ('m') or copied ('c').
Definition at line 859 of file asn1.c.
References asn1_build_object(), chunk_clear(), count, free(), chunk_t::len, memcpy, and chunk_t::ptr.
Referenced by asn1_algorithmIdentifier(), atodn(), bliss_public_key_info_encode(), build_ac(), build_acceptableResponses(), build_attr_cert_info(), build_attr_cert_validity(), build_attribute_type(), build_attributes(), build_authorityKeyIdentifier(), build_directoryName(), build_emsa_pkcs1_signature(), build_encoding(), build_extensions(), build_generalName(), build_holder(), build_issuerAndSerialNumber(), build_nonce(), build_OCSPRequest(), build_optionalSignature(), build_priv(), build_pub(), build_pub_info(), build_Request(), build_requestExtensions(), build_requestList(), build_requestorName(), build_tbsRequest(), build_v2_form(), encode_ecdsa(), generate(), main(), METHOD(), parse_ec_identifier(), parse_ecdsa_public_key(), parse_public_key(), pkcs7_data_gen(), scep_build_request(), scep_generate_transaction_id(), START_TEST(), x509_build_crlDistributionPoints(), and x509_build_subjectAltNames().
 {
     chunk_t construct;
     va_list chunks;
     u_char *pos;
     int i;
     int count = strlen(mode);
     /* sum up lengths of individual chunks */
     va_start(chunks, mode);
     construct.len = 0;
     for (i = 0; i < count; i++)
     {
         chunk_t ch = va_arg(chunks, chunk_t);
         construct.len += ch.len;
     }
     va_end(chunks);
     /* allocate needed memory for construct */
     pos = asn1_build_object(&construct, type, construct.len);
     /* copy or move the chunks */
     va_start(chunks, mode);
     for (i = 0; i < count; i++)
     {
         chunk_t ch = va_arg(chunks, chunk_t);
         memcpy(pos, ch.ptr, ch.len);
         pos += ch.len;
         switch (*mode++)
         {
             case 's':
                 chunk_clear(&ch);
                 break;
             case 'm':
                 free(ch.ptr);
                 break;
             default:
                 break;
         }
     }
     va_end(chunks);
     return construct;
 }
bool is_asn1 (chunk_t blob)
Determines if a binary blob is ASN.1 coded
Parameters
blob blob to be tested
Returns
TRUE if blob is ASN.1 coded (SEQUENCE or SET)
Definition at line 666 of file asn1.c.
References ASN1_INVALID_LENGTH, asn1_length(), ASN1_OCTET_STRING, ASN1_SEQUENCE, ASN1_SET, DBG2, DBG_ASN, FALSE, chunk_t::len, len, chunk_t::ptr, and TRUE.
Referenced by identification_create_from_data(), load_from_blob(), and START_TEST().
 {
     u_int len;
     u_char tag;
     if (!blob.len || !blob.ptr)
     {
         return FALSE;
     }
     tag = *blob.ptr;
     if (tag != ASN1_SEQUENCE && tag != ASN1_SET && tag != ASN1_OCTET_STRING)
     {
         DBG2(DBG_ASN, "  file content is not binary ASN.1");
         return FALSE;
     }
     len = asn1_length(&blob);
     if (len == ASN1_INVALID_LENGTH)
     {
         return FALSE;
     }
     /* exact match */
     if (len == blob.len)
     {
         return TRUE;
     }
     /* some websites append a surplus newline character to the blob */
     if (len + 1 == blob.len && *(blob.ptr + len) == '\n')
     {
         return TRUE;
     }
     DBG2(DBG_ASN, "  file size does not match ASN.1 coded length");
     return FALSE;
 }
Variable Documentation
const chunk_t ASN1_INTEGER_0
Some common prefabricated ASN.1 constants
Commonly used ASN1 values.
Definition at line 31 of file asn1.c.
Referenced by build_priv(), and generate().
const chunk_t ASN1_INTEGER_1
Definition at line 32 of file asn1.c.
Referenced by build_attr_cert_info(), and generate().
const chunk_t ASN1_INTEGER_2
Definition at line 33 of file asn1.c.
Referenced by generate().