strongSwan: hashtable
hashtable
collections
Classes
struct hashtable_t
Typedefs
typedef struct hashtable_t hashtable_t
typedef u_int(* hashtable_hash_t)(const void *key)
typedef bool(* hashtable_equals_t)(const void *key, const void *other_key)
Functions
u_int hashtable_hash_ptr (const void *key)
u_int hashtable_hash_str (const void *key)
bool hashtable_equals_ptr (const void *key, const void *other_key)
bool hashtable_equals_str (const void *key, const void *other_key)
hashtable_t * hashtable_create (hashtable_hash_t hash, hashtable_equals_t equals, u_int capacity)
Detailed Description
Typedef Documentation
typedef bool(* hashtable_equals_t)(const void *key, const void *other_key)
Prototype for a function that compares the two keys for equality.
Parameters
key first key (the one we are looking for)
other_key second key
Returns
TRUE if the keys are equal
Definition at line 59 of file hashtable.h.
typedef u_int(* hashtable_hash_t)(const void *key)
Prototype for a function that computes the hash code from the given key.
Parameters
key key to hash
Returns
hash code
Definition at line 34 of file hashtable.h.
typedef struct hashtable_t hashtable_t
Definition at line 26 of file hashtable.h.
Function Documentation
hashtable_t* hashtable_create (hashtable_hash_t hash, hashtable_equals_t equals, u_int capacity)
Creates an empty hash table object.
Parameters
hash hash function
equals equals function
capacity initial capacity
Returns
hashtable_t object.
Definition at line 469 of file hashtable.c.
References create_enumerator(), destroy(), destroy_function(), INIT, and init_hashtable().
Referenced by apply_filter(), CALLBACK(), certexpire_export_create(), child_sa_manager_create(), conf_parser_create(), create_generic(), create_internal(), cred_encoding_create(), dhcp_provider_create(), duplicheck_listener_create(), eap_radius_accounting_create(), eap_radius_forward_create(), eap_radius_provider_create(), eap_simaka_pseudonym_card_create(), eap_simaka_pseudonym_provider_create(), eap_simaka_reauth_card_create(), eap_simaka_reauth_provider_create(), fast_dispatcher_create(), ha_cache_create(), host_resolver_create(), ipsec_sa_mgr_create(), kernel_interface_create(), kernel_libipsec_router_create(), kernel_netlink_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), kernel_wfp_ipsec_create(), library_init(), load_tester_config_create(), lookip_listener_create(), METHOD(), netlink_socket_create(), on_accept(), plugin_loader_create(), print_traces(), printf_hook_create(), register_dh_mapping(), socket_dynamic_socket_create(), START_SETUP(), START_TEST(), stroke_counter_create(), testable_function_register(), threads_init(), tkm_chunk_map_create(), tkm_cred_create(), tls_cache_create(), unity_narrow_create(), vici_attribute_create(), vici_connect(), vici_dispatcher_create(), and whitelist_listener_create().
 {
     private_hashtable_t *this;
     INIT(this,
         .public = {
             .put = _put,
             .get = _get,
             .get_match = _get_match,
             .remove = _remove_,
             .remove_at = (void*)_remove_at,
             .get_count = _get_count,
             .create_enumerator = _create_enumerator,
             .destroy = _destroy,
             .destroy_function = _destroy_function,
         },
         .hash = hash,
         .equals = equals,
     );
     init_hashtable(this, capacity);
     return &this->public;
 }
bool hashtable_equals_ptr (const void * key, const void * other_key)
Hashtable equals function comparing pointers.
Parameters
key key to compare
other_key other key to compare
Returns
TRUE if key == other_key
Definition at line 172 of file hashtable.c.
Referenced by create_internal(), cred_encoding_create(), dhcp_provider_create(), eap_radius_forward_create(), ha_cache_create(), kernel_wfp_ipsec_create(), netlink_socket_create(), printf_hook_create(), threads_init(), and unity_narrow_create().
 {
     return key == other_key;
 }
bool hashtable_equals_str (const void * key, const void * other_key)
Hashtable equals function comparing char* keys.
Parameters
key key to compare
other_key other key to compare
Returns
TRUE if streq(key, other_key)
Definition at line 180 of file hashtable.c.
References streq().
Referenced by apply_filter(), CALLBACK(), conf_parser_create(), METHOD(), testable_function_register(), vici_attribute_create(), vici_connect(), and vici_dispatcher_create().
 {
     return streq(key, other_key);
 }
u_int hashtable_hash_ptr (const void * key)
Hashtable hash function calculation the hash solely based on the key pointer.
Parameters
key key to hash
Returns
hash of key
Definition at line 156 of file hashtable.c.
References chunk_from_thing, and chunk_hash().
Referenced by create_internal(), cred_encoding_create(), dhcp_provider_create(), eap_radius_forward_create(), ha_cache_create(), kernel_wfp_ipsec_create(), netlink_socket_create(), printf_hook_create(), threads_init(), and unity_narrow_create().
 {
     return chunk_hash(chunk_from_thing(key));
 }
u_int hashtable_hash_str (const void * key)
Hashtable hash function calculation the hash for char* keys.
Parameters
key key to hash, a char*
Returns
hash of key
Definition at line 164 of file hashtable.c.
References chunk_from_str, and chunk_hash().
Referenced by apply_filter(), CALLBACK(), conf_parser_create(), METHOD(), testable_function_register(), vici_attribute_create(), vici_connect(), and vici_dispatcher_create().
 {
     return chunk_hash(chunk_from_str((char*)key));
 }