strongSwan: stroke_config
stroke_config
stroke
Classes
struct stroke_config_t
Typedefs
typedef struct stroke_config_t stroke_config_t
Functions
stroke_config_t * stroke_config_create (stroke_ca_t *ca, stroke_cred_t *cred, stroke_attribute_t *attributes)
Detailed Description
Typedef Documentation
typedef struct stroke_config_t stroke_config_t
Definition at line 31 of file stroke_config.h.
Function Documentation
stroke_config_t* stroke_config_create (stroke_ca_t * ca, stroke_cred_t * cred, stroke_attribute_t * attributes)
Create a stroke_config instance.
Definition at line 1542 of file stroke_config.c.
References attributes, INIT, linked_list_create(), mutex_create(), and MUTEX_TYPE_RECURSIVE.
Referenced by stroke_socket_create().
 {
     private_stroke_config_t *this;
     INIT(this,
         .public = {
             .backend = {
                 .create_peer_cfg_enumerator = _create_peer_cfg_enumerator,
                 .create_ike_cfg_enumerator = _create_ike_cfg_enumerator,
                 .get_peer_cfg_by_name = _get_peer_cfg_by_name,
             },
             .add = _add,
             .del = _del,
             .set_user_credentials = _set_user_credentials,
             .destroy = _destroy,
         },
         .list = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_RECURSIVE),
         .ca = ca,
         .cred = cred,
         .attributes = attributes,
     );
     return &this->public;
 }