strongSwan: ike_header_t Struct Reference
ike_header_t Struct Reference
ike_header
#include "ike_header.h"
Public Attributes
payload_t payload_interface
u_int64_t(* get_initiator_spi)(ike_header_t *this)
void(* set_initiator_spi)(ike_header_t *this, u_int64_t initiator_spi)
u_int64_t(* get_responder_spi)(ike_header_t *this)
void(* set_responder_spi)(ike_header_t *this, u_int64_t responder_spi)
u_int8_t(* get_maj_version)(ike_header_t *this)
void(* set_maj_version)(ike_header_t *this, u_int8_t major)
u_int8_t(* get_min_version)(ike_header_t *this)
void(* set_min_version)(ike_header_t *this, u_int8_t minor)
bool(* get_response_flag)(ike_header_t *this)
void(* set_response_flag)(ike_header_t *this, bool response)
bool(* get_version_flag)(ike_header_t *this)
void(* set_version_flag)(ike_header_t *this, bool version)
bool(* get_initiator_flag)(ike_header_t *this)
void(* set_initiator_flag)(ike_header_t *this, bool initiator)
bool(* get_encryption_flag)(ike_header_t *this)
void(* set_encryption_flag)(ike_header_t *this, bool encryption)
bool(* get_commit_flag)(ike_header_t *this)
void(* set_commit_flag)(ike_header_t *this, bool commit)
bool(* get_authonly_flag)(ike_header_t *this)
void(* set_authonly_flag)(ike_header_t *this, bool authonly)
u_int8_t(* get_exchange_type)(ike_header_t *this)
void(* set_exchange_type)(ike_header_t *this, u_int8_t exchange_type)
u_int32_t(* get_message_id)(ike_header_t *this)
void(* set_message_id)(ike_header_t *this, u_int32_t message_id)
void(* destroy)(ike_header_t *this)
Detailed Description
An object of this type represents an IKE header of either IKEv1 or IKEv2.
Definition at line 145 of file ike_header.h.
Member Data Documentation
void(* ike_header_t::destroy)(ike_header_t *this)
Destroys a ike_header_t object.
Definition at line 322 of file ike_header.h.
Referenced by generate_message(), and METHOD().
bool(* ike_header_t::get_authonly_flag)(ike_header_t *this)
Get the authentication only flag.
Returns
authonly flag
Definition at line 282 of file ike_header.h.
bool(* ike_header_t::get_commit_flag)(ike_header_t *this)
Get the commit flag.
Returns
commit flag
Definition at line 268 of file ike_header.h.
bool(* ike_header_t::get_encryption_flag)(ike_header_t *this)
Get the encryption flag.
Returns
encryption flag
Definition at line 254 of file ike_header.h.
Referenced by METHOD().
u_int8_t(* ike_header_t::get_exchange_type)(ike_header_t *this)
Get the exchange type.
Returns
exchange type
Definition at line 296 of file ike_header.h.
Referenced by METHOD().
bool(* ike_header_t::get_initiator_flag)(ike_header_t *this)
Get the initiator flag.
Returns
initiator flag
Definition at line 240 of file ike_header.h.
Referenced by METHOD().
u_int64_t(* ike_header_t::get_initiator_spi)(ike_header_t *this)
Get the initiator spi.
Returns
initiator_spi
Definition at line 156 of file ike_header.h.
Referenced by create_header(), and METHOD().
u_int8_t(* ike_header_t::get_maj_version)(ike_header_t *this)
Get the major version.
Returns
major version
Definition at line 184 of file ike_header.h.
Referenced by METHOD().
u_int32_t(* ike_header_t::get_message_id)(ike_header_t *this)
Get the message id.
Returns
message id
Definition at line 310 of file ike_header.h.
Referenced by METHOD().
u_int8_t(* ike_header_t::get_min_version)(ike_header_t *this)
Get the minor version.
Returns
minor version
Definition at line 198 of file ike_header.h.
Referenced by METHOD().
u_int64_t(* ike_header_t::get_responder_spi)(ike_header_t *this)
Get the responder spi.
Returns
responder_spi
Definition at line 170 of file ike_header.h.
Referenced by create_header(), and METHOD().
bool(* ike_header_t::get_response_flag)(ike_header_t *this)
Get the response flag.
Returns
response flag
Definition at line 212 of file ike_header.h.
Referenced by METHOD().
bool(* ike_header_t::get_version_flag)(ike_header_t *this)
Get "higher version supported"-flag.
Returns
version flag
Definition at line 226 of file ike_header.h.
payload_t ike_header_t::payload_interface
The payload_t interface.
Definition at line 149 of file ike_header.h.
Referenced by create_header(), and METHOD().
void(* ike_header_t::set_authonly_flag)(ike_header_t *this, bool authonly)
Set the authentication only flag.
Parameters
authonly authonly flag
Definition at line 289 of file ike_header.h.
void(* ike_header_t::set_commit_flag)(ike_header_t *this, bool commit)
Set the commit flag.
Parameters
commit commit flag
Definition at line 275 of file ike_header.h.
void(* ike_header_t::set_encryption_flag)(ike_header_t *this, bool encryption)
Set the encryption flag.
Parameters
encryption encryption flag
Definition at line 261 of file ike_header.h.
Referenced by create_header().
void(* ike_header_t::set_exchange_type)(ike_header_t *this, u_int8_t exchange_type)
Set the exchange type.
Parameters
exchange_type exchange type
Definition at line 303 of file ike_header.h.
Referenced by create_header().
void(* ike_header_t::set_initiator_flag)(ike_header_t *this, bool initiator)
Set the initiator flag.
Parameters
initiator initiator flag
Definition at line 247 of file ike_header.h.
Referenced by create_header().
void(* ike_header_t::set_initiator_spi)(ike_header_t *this, u_int64_t initiator_spi)
Set the initiator spi.
Parameters
initiator_spi initiator_spi
Definition at line 163 of file ike_header.h.
Referenced by create_header().
void(* ike_header_t::set_maj_version)(ike_header_t *this, u_int8_t major)
Set the major version.
Parameters
major major version
Definition at line 191 of file ike_header.h.
void(* ike_header_t::set_message_id)(ike_header_t *this, u_int32_t message_id)
Set the message id.
Parameters
initiator_spi message id
Definition at line 317 of file ike_header.h.
Referenced by create_header().
void(* ike_header_t::set_min_version)(ike_header_t *this, u_int8_t minor)
Set the minor version.
Parameters
minor minor version
Definition at line 205 of file ike_header.h.
void(* ike_header_t::set_responder_spi)(ike_header_t *this, u_int64_t responder_spi)
Set the responder spi.
Parameters
responder_spi responder_spi
Definition at line 177 of file ike_header.h.
Referenced by create_header().
void(* ike_header_t::set_response_flag)(ike_header_t *this, bool response)
Set the response flag-
Parameters
response response flag
Definition at line 219 of file ike_header.h.
Referenced by create_header().
void(* ike_header_t::set_version_flag)(ike_header_t *this, bool version)
Set the "higher version supported"-flag.
Parameters
version flag value
Definition at line 233 of file ike_header.h.
Referenced by create_header().
The documentation for this struct was generated from the following file:
ike_header.h