strongSwan: child_sa_manager
child_sa_manager
sa
Classes
struct child_sa_manager_t
Typedefs
typedef struct child_sa_manager_t child_sa_manager_t
Functions
child_sa_manager_t * child_sa_manager_create ()
Detailed Description
Typedef Documentation
typedef struct child_sa_manager_t child_sa_manager_t
Definition at line 27 of file child_sa_manager.h.
Function Documentation
child_sa_manager_t* child_sa_manager_create ()
Create a child_sa_manager instance.
See header
Definition at line 311 of file child_sa_manager.c.
References equals_id(), equals_in(), equals_out(), hash_id(), hash_in(), hash_out(), hashtable_create(), INIT, mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by sa_managers_cb().
 {
     private_child_sa_manager_t *this;
     INIT(this,
         .public = {
             .add = _add,
             .remove = _remove_,
             .checkout = _checkout,
             .checkout_by_id = _checkout_by_id,
             .destroy = _destroy,
         },
         .in = hashtable_create((hashtable_hash_t)hash_in,
                                (hashtable_equals_t)equals_in, 8),
         .out = hashtable_create((hashtable_hash_t)hash_out,
                                (hashtable_equals_t)equals_out, 8),
         .ids = hashtable_create((hashtable_hash_t)hash_id,
                                (hashtable_equals_t)equals_id, 8),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     return &this->public;
 }