strongSwan: encrypted_payload
encrypted_payload
payloads
Classes
struct encrypted_payload_t
Typedefs
typedef struct encrypted_payload_t encrypted_payload_t
Functions
encrypted_payload_t * encrypted_payload_create (payload_type_t type)
encrypted_payload_t * encrypted_payload_create_from_plain (payload_type_t next, chunk_t plain)
Detailed Description
Typedef Documentation
typedef struct encrypted_payload_t encrypted_payload_t
Definition at line 27 of file encrypted_payload.h.
Function Documentation
encrypted_payload_t* encrypted_payload_create (payload_type_t type)
Creates an empty encrypted_payload_t object.
Parameters
type PLV2_ENCRYPTED or PLV1_ENCRYPTED
Returns
encrypted_payload_t object
Definition at line 741 of file encrypted_payload.c.
References INIT, linked_list_create(), PL_NONE, PLV1_ENCRYPTED, and type.
Referenced by encrypted_payload_create_from_plain(), payload_create(), and wrap_payloads().
 {
     private_encrypted_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_length = _get_length,
             .add_payload = _add_payload,
             .remove_payload = _remove_payload,
             .generate_payloads = _generate_payloads,
             .set_transform = _set_transform,
             .encrypt = _encrypt,
             .decrypt = _decrypt,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payloads = linked_list_create(),
         .type = type,
     );
     this->payload_length = get_header_length(this);
     if (type == PLV1_ENCRYPTED)
     {
         this->public.encrypt = _encrypt_v1;
         this->public.decrypt = _decrypt_v1;
     }
     return &this->public;
 }
encrypted_payload_t* encrypted_payload_create_from_plain (payload_type_t next, chunk_t plain)
Creates an encrypted payload with the given plain text data and next payload type.
Parameters
next next payload type
plain plaintext data (gets adopted)
Returns
encrypted_payload_t object
Definition at line 784 of file encrypted_payload.c.
References compute_length(), encrypted_payload_t::decrypt, encrypted_payload_create(), next, and PLV2_ENCRYPTED.
Referenced by METHOD().
 {
     private_encrypted_payload_t *this;
     this = (private_encrypted_payload_t*)encrypted_payload_create(PLV2_ENCRYPTED);
     this->public.decrypt = _decrypt_plain;
     this->next_payload = next;
     this->encrypted = plain;
     compute_length(this);
     return &this->public;
 }