strongSwan: af_alg_ops_t Struct Reference
af_alg_ops_t Struct Reference
af_alg_ops
#include "af_alg_ops.h"
Public Attributes
bool(* hash)(af_alg_ops_t *this, chunk_t data, char *out, size_t outlen)
void(* reset)(af_alg_ops_t *this)
bool(* crypt)(af_alg_ops_t *this, u_int32_t type, chunk_t iv, chunk_t data, char *out)
bool(* set_key)(af_alg_ops_t *this, chunk_t key)
void(* destroy)(af_alg_ops_t *this)
Detailed Description
Helper to run AF_ALG operations.
Definition at line 41 of file af_alg_ops.h.
Member Data Documentation
bool(* af_alg_ops_t::crypt)(af_alg_ops_t *this, u_int32_t type, chunk_t iv, chunk_t data, char *out)
En-/Decrypt a chunk of data.
Parameters
type crypto operation (ALG_OP_DECRYPT/ALG_OP_ENCRYPT)
iv iv to use
data data to encrypt/decrypt
out buffer write processed data to
Returns
TRUE if successful
Definition at line 67 of file af_alg_ops.h.
void(* af_alg_ops_t::destroy)(af_alg_ops_t *this)
Destroy a af_alg_ops_t.
Definition at line 81 of file af_alg_ops.h.
Referenced by af_alg_crypter_probe(), af_alg_hasher_probe(), af_alg_prf_probe(), and af_alg_signer_probe().
bool(* af_alg_ops_t::hash)(af_alg_ops_t *this, chunk_t data, char *out, size_t outlen)
Hash a chunk of data.
Parameters
data data to hash
out buffer to write hash to, NULL for append mode
outlen number of bytes to read into out
Returns
TRUE if successful
Definition at line 51 of file af_alg_ops.h.
void(* af_alg_ops_t::reset)(af_alg_ops_t *this)
Reset hasher state.
Definition at line 56 of file af_alg_ops.h.
bool(* af_alg_ops_t::set_key)(af_alg_ops_t *this, chunk_t key)
Set the key for en-/decryption or HMAC/XCBC operations.
Parameters
key key to set for transform
Returns
TRUE if successful
Definition at line 76 of file af_alg_ops.h.
The documentation for this struct was generated from the following file:
af_alg_ops.h