strongSwan: hmac.c File Reference
hmac.c File Reference
#include "hmac.h"
#include <crypto/mac.h>
#include <crypto/prfs/mac_prf.h>
#include <crypto/signers/mac_signer.h>
Classes
struct private_mac_t
Typedefs
typedef struct private_mac_t private_mac_t
Functions
METHOD (mac_t, get_mac, bool, private_mac_t *this, chunk_t data, u_int8_t *out)
METHOD (mac_t, get_mac_size, size_t, private_mac_t *this)
METHOD (mac_t, set_key, bool, private_mac_t *this, chunk_t key)
METHOD (mac_t, destroy, void, private_mac_t *this)
static mac_t * hmac_create (hash_algorithm_t hash_algorithm)
prf_t * hmac_prf_create (pseudo_random_function_t algo)
signer_t * hmac_signer_create (integrity_algorithm_t algo)
Typedef Documentation
typedef struct private_mac_t private_mac_t
Definition at line 24 of file hmac.c.
Function Documentation
static mac_t* hmac_create (hash_algorithm_t hash_algorithm) static
Definition at line 142 of file hmac.c.
References b, crypto_factory_t::create_hasher, library_t::crypto, free(), HASH_MD5, HASH_SHA1, HASH_SHA256, HASH_SHA384, HASH_SHA512, INIT, lib, and malloc().
Referenced by hmac_prf_create(), and hmac_signer_create().
 {
     private_mac_t *this;
     INIT(this,
         .public = {
             .get_mac = _get_mac,
             .get_mac_size = _get_mac_size,
             .set_key = _set_key,
             .destroy = _destroy,
         },
     );
     /* set b, according to hasher */
     switch (hash_algorithm)
     {
         case HASH_SHA1:
         case HASH_MD5:
         case HASH_SHA256:
             this->b = 64;
             break;
         case HASH_SHA384:
         case HASH_SHA512:
             this->b = 128;
             break;
         default:
             free(this);
             return NULL;
     }
     this->h = lib->crypto->create_hasher(lib->crypto, hash_algorithm);
     if (this->h == NULL)
     {
         free(this);
         return NULL;
     }
     /* build ipad and opad */
     this->opaded_key.ptr = malloc(this->b);
     this->opaded_key.len = this->b;
     this->ipaded_key.ptr = malloc(this->b);
     this->ipaded_key.len = this->b;
     return &this->public;
 }
METHOD (mac_t , get_mac , bool , private_mac_t * this, chunk_t data, u_int8_t * out)
Definition at line 59 of file hmac.c.
References chunk_t::len, and chunk_t::ptr.
 {
     /* H(K XOR opad, H(K XOR ipad, text))
      *
      * if out is NULL, we append text to the inner hash.
      * else, we complete the inner and do the outer.
      *
      */
     u_int8_t buffer[this->h->get_hash_size(this->h)];
     chunk_t inner;
     if (out == NULL)
     {
         /* append data to inner */
         return this->h->get_hash(this->h, data, NULL);
     }
     /* append and do outer hash */
     inner.ptr = buffer;
     inner.len = this->h->get_hash_size(this->h);
     /* complete inner, do outer and reinit for next call */
     return this->h->get_hash(this->h, data, buffer) &&
            this->h->get_hash(this->h, this->opaded_key, NULL) &&
            this->h->get_hash(this->h, inner, out) &&
            this->h->get_hash(this->h, this->ipaded_key, NULL);
 }
METHOD (mac_t , get_mac_size , size_t , private_mac_t * this)
Definition at line 89 of file hmac.c.
 {
     return this->h->get_hash_size(this->h);
 }
METHOD (mac_t , set_key , bool , private_mac_t * this, chunk_t key)
Definition at line 95 of file hmac.c.
References b, FALSE, chunk_t::len, memcpy, memset, and chunk_t::ptr.
 {
     int i;
     u_int8_t buffer[this->b];
     memset(buffer, 0, this->b);
     if (key.len > this->b)
     {
         /* if key is too long, it will be hashed */
         if (!this->h->reset(this->h) ||
             !this->h->get_hash(this->h, key, buffer))
         {
             return FALSE;
         }
     }
     else
     {
         /* if not, just copy it in our pre-padded k */
         memcpy(buffer, key.ptr, key.len);
     }
     /* apply ipad and opad to key */
     for (i = 0; i < this->b; i++)
     {
         this->ipaded_key.ptr[i] = buffer[i] ^ 0x36;
         this->opaded_key.ptr[i] = buffer[i] ^ 0x5C;
     }
     /* begin hashing of inner pad */
     return this->h->reset(this->h) &&
            this->h->get_hash(this->h, this->ipaded_key, NULL);
 }
METHOD (mac_t , destroy , void , private_mac_t * this)
Definition at line 130 of file hmac.c.
References chunk_clear(), and free().
 {
     this->h->destroy(this->h);
     chunk_clear(&this->opaded_key);
     chunk_clear(&this->ipaded_key);
     free(this);
 }