strongSwan: certificate_t Struct Reference
certificate_t Struct Reference
certificate
#include "certificate.h"
Public Attributes
certificate_type_t(* get_type)(certificate_t *this)
identification_t *(* get_subject)(certificate_t *this)
id_match_t(* has_subject)(certificate_t *this, identification_t *subject)
identification_t *(* get_issuer)(certificate_t *this)
id_match_t(* has_issuer)(certificate_t *this, identification_t *issuer)
bool(* issued_by)(certificate_t *this, certificate_t *issuer, signature_scheme_t *scheme)
public_key_t *(* get_public_key)(certificate_t *this)
bool(* get_validity)(certificate_t *this, time_t *when, time_t *not_before, time_t *not_after)
bool(* get_encoding)(certificate_t *this, cred_encoding_type_t type, chunk_t *encoding)
bool(* equals)(certificate_t *this, certificate_t *other)
certificate_t *(* get_ref)(certificate_t *this)
void(* destroy)(certificate_t *this)
Detailed Description
An abstract certificate.
A certificate designs a subject-issuer relationship. It may have an associated public key.
Definition at line 93 of file certificate.h.
Member Data Documentation
void(* certificate_t::destroy)(certificate_t *this)
Destroy a certificate.
Definition at line 194 of file certificate.h.
Referenced by add_cert_internal(), add_device_id(), build_auth_cfg(), build_trustchain(), cache(), cache_queue(), CALLBACK(), check_crl(), check_delta_crl(), destroy_entry_value(), dn(), do_args(), fetch_ocsp(), find_crl(), find_pubkey_in_certs(), get_better_crl(), get_better_ocsp(), get_pretrusted_cert(), keyid(), load_ca_cert(), load_cacerts(), METHOD(), print(), process_certificate(), pub(), read_serial(), try_get_cert(), and verify_trust_chain().
bool(* certificate_t::equals)(certificate_t *this, certificate_t *other)
Check if two certificates are equal.
Parameters
other certificate to compare against this
Returns
TRUE if certificates are equal
Definition at line 182 of file certificate.h.
Referenced by auth_contains_cacert(), build_trustchain(), CALLBACK(), cert_equals(), certificate_equals(), create_unique_cert_list(), entry_equals(), find_public_key(), match_cert(), METHOD(), remove_cert(), verify_ocsp(), and verify_trust_chain().
bool(* certificate_t::get_encoding)(certificate_t *this, cred_encoding_type_t type, chunk_t *encoding)
Get the certificate in an encoded form as a chunk.
Parameters
type type of the encoding, one of CERT_*
encoding encoding of the key, allocated
Returns
TRUE if encoding supported
Definition at line 173 of file certificate.h.
Referenced by acert(), build_cert_chain(), build_cert_payload(), CALLBACK(), cert_payload_create_from_cert(), export(), fetch_ocsp(), generate(), get_cert_hash(), load_pkcs12(), main(), METHOD(), print_pem(), print_pem_cert(), req(), self(), send_certificate(), and show().
identification_t*(* certificate_t::get_issuer)(certificate_t *this)
Get the issuer which signed this certificate.
Returns
issuer identity
Definition at line 125 of file certificate.h.
Referenced by add_attribute_certs(), add_local_certs(), build_issuerAndSerialNumber(), check_crl(), check_policy(), create_unique_cert_list(), find_crl(), find_private(), get_issuer_cert(), imv_attestation_process(), METHOD(), print_cert(), process_ac(), stroke_list_acerts(), stroke_list_certs(), stroke_list_crls(), stroke_list_ocsp(), verify(), verify_crl(), and verify_ocsp().
public_key_t*(* certificate_t::get_public_key)(certificate_t *this)
Get the public key associated to this certificate.
Returns
newly referenced public_key, NULL if none available
Definition at line 153 of file certificate.h.
Referenced by add_certreq(), add_device_id(), add_local_certs(), build_requestList(), cert_enumerate(), cert_filter(), certs_filter(), check_ocsp(), connect_(), create_inner_cdp(), do_args(), encrypt_key(), enumerate(), find_client_id(), find_private(), find_pubkey_in_certs(), get_key_strength(), get_pretrusted_cert(), get_private_by_cert(), has_privkey(), imv_attestation_process(), issue(), keyid(), main(), METHOD(), print_cert(), pub(), sign_crl(), stroke_list_certs(), stroke_list_pgp(), and stroke_list_pubkeys().
certificate_t*(* certificate_t::get_ref)(certificate_t *this)
Get a new reference to the certificate.
Returns
this, with an increased refcount
Definition at line 189 of file certificate.h.
Referenced by add_cert_internal(), add_local_certs(), build_trustchain(), cache(), CALLBACK(), copy_certs(), create_unique_cert_list(), fetch_cert(), find_certificates(), find_crl(), find_smartcard_key(), get_issuer_cert(), load_pkcs12(), main(), merge(), METHOD(), pkcs7_signed_data_gen(), prefer_cert(), process_pkcs7(), tcg_pts_attr_aik_create(), verify_trust_chain(), x509_ac_gen(), and x509_ocsp_request_gen().
identification_t*(* certificate_t::get_subject)(certificate_t *this)
Get the primary subject to which this certificate belongs.
Returns
subject identity
Definition at line 107 of file certificate.h.
Referenced by add_certreq(), add_im_certs(), add_subject_cert(), build_auth_cfg(), build_certs(), build_requestList(), CALLBACK(), check_certificate(), check_name_constraints(), check_policy(), check_policy_constraints(), connect_(), dn(), fetch_cert(), find_certificate(), find_client_id(), find_public_key(), find_smartcard_key(), generate(), get_key_strength(), has_invalid_certs(), has_no_any_policy(), has_no_policy_mapping(), issue(), load_ca_cert(), load_ca_dir(), load_ca_file(), load_cacerts(), load_certs(), load_pkcs12(), load_x509(), load_x509_aa(), log_auth_cfgs(), log_authority_data(), main(), METHOD(), name_constraint_matches(), print_cert(), process_ac(), process_certificate(), process_certreq(), process_crl(), process_pkcs7(), process_x509(), send_certificate(), send_certificate_request(), show(), soap_init(), START_TEST(), stroke_list_acerts(), stroke_list_certs(), stroke_list_pgp(), stroke_list_pubkeys(), verify(), verify_crl(), verify_ocsp(), and verify_trust_chain().
certificate_type_t(* certificate_t::get_type)(certificate_t *this)
Get the type of the certificate.
Returns
certificate type
Definition at line 100 of file certificate.h.
Referenced by add_attribute_certs(), add_certreq(), build_issuerAndSerialNumber(), CALLBACK(), cert_enumerate(), cert_payload_create_from_cert(), certs_filter(), check_certificate(), check_constraints(), check_policy_constraints(), enumerate(), get_issuer_cert(), imv_attestation_process(), METHOD(), print_cert(), process_pkcs7(), x509_ac_gen(), x509_crl_gen(), and x509_ocsp_request_gen().
bool(* certificate_t::get_validity)(certificate_t *this, time_t *when, time_t *not_before, time_t *not_after)
Check the lifetime of the certificate.
Parameters
when check validity at a certain time (NULL for now)
not_before receives certificates start of lifetime
not_after receives certificates end of lifetime
Returns
TRUE if when between not_after and not_before
Definition at line 163 of file certificate.h.
Referenced by add_attribute_certs(), certificate_is_newer(), check_lifetime(), get_better_crl(), get_better_ocsp(), has_invalid_certs(), METHOD(), print_cert(), stroke_list_acerts(), stroke_list_certs(), stroke_list_crls(), stroke_list_ocsp(), stroke_list_pgp(), stroke_list_pubkeys(), verify(), and verify_ocsp().
id_match_t(* certificate_t::has_issuer)(certificate_t *this, identification_t *issuer)
Check if certificate contains an issuer ID.
A certificate may contain additional issuer identifiers, which are not returned by get_issuer (e.g. issuerAltNames)
Parameters
subject issuer identity
Returns
matching value of best match
Definition at line 136 of file certificate.h.
Referenced by cert_enumerate(), check_crl(), create_unique_cert_list(), and find_crl().
id_match_t(* certificate_t::has_subject)(certificate_t *this, identification_t *subject)
Check if certificate contains a subject ID.
A certificate may contain additional subject identifiers, which are not returned by get_subject (e.g. subjectAltNames)
Parameters
subject subject identity
Returns
matching value of best match
Definition at line 118 of file certificate.h.
Referenced by build_auth_cfg(), cert_enumerate(), cert_filter(), certs_filter(), check_certificate(), enumerate(), and METHOD().
bool(* certificate_t::issued_by)(certificate_t *this, certificate_t *issuer, signature_scheme_t *scheme)
Check if this certificate is issued and signed by a specific issuer.
Parameters
issuer issuer's certificate
scheme receives signature scheme used during verification
Returns
TRUE if certificate issued by issuer and trusted
Definition at line 145 of file certificate.h.
Referenced by imv_attestation_process(), and METHOD().
The documentation for this struct was generated from the following file:
certificate.h