strongSwan: attribute_manager_t Struct Reference
attribute_manager_t Struct Reference
attribute_manager
#include "attribute_manager.h"
Public Attributes
host_t *(* acquire_address)(attribute_manager_t *this, linked_list_t *pool, ike_sa_t *ike_sa, host_t *requested)
bool(* release_address)(attribute_manager_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
enumerator_t *(* create_responder_enumerator)(attribute_manager_t *this, linked_list_t *pool, ike_sa_t *ike_sa, linked_list_t *vips)
void(* add_provider)(attribute_manager_t *this, attribute_provider_t *provider)
void(* remove_provider)(attribute_manager_t *this, attribute_provider_t *provider)
attribute_handler_t *(* handle)(attribute_manager_t *this, ike_sa_t *ike_sa, attribute_handler_t *handler, configuration_attribute_type_t type, chunk_t data)
void(* release)(attribute_manager_t *this, attribute_handler_t *handler, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
enumerator_t *(* create_initiator_enumerator)(attribute_manager_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
void(* add_handler)(attribute_manager_t *this, attribute_handler_t *handler)
void(* remove_handler)(attribute_manager_t *this, attribute_handler_t *handler)
void(* destroy)(attribute_manager_t *this)
Detailed Description
The attribute manager hands out attributes or handles them.
The attribute manager manages both, attribute providers and attribute handlers. Attribute providers are responsible to hand out attributes if a connecting peer requests them. Handlers handle such attributes if they are received on the requesting peer.
Definition at line 39 of file attribute_manager.h.
Member Data Documentation
host_t*(* attribute_manager_t::acquire_address)(attribute_manager_t *this, linked_list_t *pool, ike_sa_t *ike_sa, host_t *requested)
Acquire a virtual IP address to assign to a peer.
Parameters
pools list of pool names (char*) to acquire from
ike_sa associated IKE_SA for which an address is requested
requested IP in configuration request
Returns
allocated address, NULL to serve none
Definition at line 49 of file attribute_manager.h.
Referenced by build_reply(), build_set(), and METHOD().
void(* attribute_manager_t::add_handler)(attribute_manager_t *this, attribute_handler_t *handler)
Register an attribute handler to the manager.
Parameters
handler attribute handler to register
Definition at line 132 of file attribute_manager.h.
Referenced by nm_backend_init(), plugin_cb(), and stroke_socket_create().
void(* attribute_manager_t::add_provider)(attribute_manager_t *this, attribute_provider_t *provider)
Register an attribute provider to the manager.
Parameters
provider attribute provider to register
Definition at line 82 of file attribute_manager.h.
Referenced by open_database(), plugin_cb(), register_vici(), and stroke_socket_create().
enumerator_t*(* attribute_manager_t::create_initiator_enumerator)(attribute_manager_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
Create an enumerator over attributes to request from server.
Parameters
ike_sa associated IKE_SA to request attributes for
vip list of virtual IPs (host_t*) going to request
Returns
enumerator (attribute_handler_t, ca_type_t, chunk_t)
Definition at line 124 of file attribute_manager.h.
Referenced by build_request(), and METHOD().
enumerator_t*(* attribute_manager_t::create_responder_enumerator)(attribute_manager_t *this, linked_list_t *pool, ike_sa_t *ike_sa, linked_list_t *vips)
Create an enumerator over attributes to hand out to a peer.
Parameters
pool list of pools names (char*) to query attributes from
ike_sa associated IKE_SA for which attributes are requested
vip list of virtual IPs (host_t*) to assign to peer
Returns
enumerator (configuration_attribute_type_t, chunk_t)
Definition at line 73 of file attribute_manager.h.
Referenced by build_reply(), build_set(), and METHOD().
void(* attribute_manager_t::destroy)(attribute_manager_t *this)
Destroy a attribute_manager instance.
Definition at line 146 of file attribute_manager.h.
attribute_handler_t*(* attribute_manager_t::handle)(attribute_manager_t *this, ike_sa_t *ike_sa, attribute_handler_t *handler, configuration_attribute_type_t type, chunk_t data)
Handle a configuration attribute by passing them to the handlers.
Parameters
ike_sa associated IKE_SA to handle an attribute for
handler handler we requested the attribute for, if any
type type of configuration attribute
data associated attribute data
Returns
handler which handled this attribute, NULL if none
Definition at line 101 of file attribute_manager.h.
Referenced by handle_attribute().
void(* attribute_manager_t::release)(attribute_manager_t *this, attribute_handler_t *handler, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
Release an attribute previously handle()d by a handler.
Parameters
ike_sa associated IKE_SA to release an attribute for
server server from which the attribute was received
type type of attribute to release
data associated attribute data
Definition at line 113 of file attribute_manager.h.
Referenced by METHOD().
bool(* attribute_manager_t::release_address)(attribute_manager_t *this, linked_list_t *pools, host_t *address, ike_sa_t *ike_sa)
Release a previously acquired address.
Parameters
pools list of pool names (char*) to release to
address address to release
ike_sa associated IKE_SA for which an address is released
Returns
TRUE if address released to pool
Definition at line 61 of file attribute_manager.h.
Referenced by build_reply(), and METHOD().
void(* attribute_manager_t::remove_handler)(attribute_manager_t *this, attribute_handler_t *handler)
Unregister an attribute handler from the manager.
Parameters
handler attribute handler to unregister
Definition at line 140 of file attribute_manager.h.
Referenced by METHOD(), nm_backend_deinit(), and plugin_cb().
void(* attribute_manager_t::remove_provider)(attribute_manager_t *this, attribute_provider_t *provider)
Unregister an attribute provider from the manager.
Parameters
provider attribute provider to unregister
Definition at line 89 of file attribute_manager.h.
Referenced by METHOD(), open_database(), plugin_cb(), and register_vici().
The documentation for this struct was generated from the following file:
attribute_manager.h