strongSwan: rekey_child_sa_job
rekey_child_sa_job
jobs
Classes
struct rekey_child_sa_job_t
Typedefs
typedef struct rekey_child_sa_job_t rekey_child_sa_job_t
Functions
rekey_child_sa_job_t * rekey_child_sa_job_create (protocol_id_t protocol, u_int32_t spi, host_t *dst)
Detailed Description
Typedef Documentation
typedef struct rekey_child_sa_job_t rekey_child_sa_job_t
Definition at line 24 of file rekey_child_sa_job.h.
Function Documentation
rekey_child_sa_job_t* rekey_child_sa_job_create (protocol_id_t protocol, u_int32_t spi, host_t * dst)
Creates a job of type REKEY_CHILD_SA.
Parameters
protocol protocol of the CHILD_SA
spi security parameter index of the CHILD_SA
dst SA destination address
Returns
rekey_child_sa_job_t object
Definition at line 88 of file rekey_child_sa_job.c.
References host_t::clone, INIT, and protocol.
Referenced by METHOD(), rekey_child(), and schedule_delayed_rekey().
 {
     private_rekey_child_sa_job_t *this;
     INIT(this,
         .public = {
             .job_interface = {
                 .execute = _execute,
                 .get_priority = _get_priority,
                 .destroy = _destroy,
             },
         },
         .protocol = protocol,
         .spi = spi,
         .dst = dst->clone(dst),
     );
     return &this->public;
 }