strongSwan: aesni_plugin.c File Reference
aesni_plugin.c File Reference
#include "aesni_plugin.h"
#include "aesni_cbc.h"
#include "aesni_ctr.h"
#include "aesni_ccm.h"
#include "aesni_gcm.h"
#include "aesni_xcbc.h"
#include "aesni_cmac.h"
#include <stdio.h>
#include <library.h>
#include <utils/debug.h>
#include <utils/cpu_feature.h>
Classes
struct private_aesni_plugin_t
Typedefs
typedef struct
private_aesni_plugin_t private_aesni_plugin_t
typedef enum cpuid_feature_t cpuid_feature_t
Functions
METHOD (plugin_t, get_name, char *, private_aesni_plugin_t *this)
METHOD (plugin_t, get_features, int, private_aesni_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_aesni_plugin_t *this)
plugin_t * aesni_plugin_create ()
Typedef Documentation
typedef enum cpuid_feature_t cpuid_feature_t
Definition at line 31 of file aesni_plugin.c.
typedef struct private_aesni_plugin_t private_aesni_plugin_t
Definition at line 30 of file aesni_plugin.c.
Function Documentation
plugin_t* aesni_plugin_create ()
Definition at line 109 of file aesni_plugin.c.
References destroy(), INIT, and return_false().
 {
     private_aesni_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .reload = (void*)return_false,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_aesni_plugin_t * this)
Definition at line 44 of file aesni_plugin.c.
 {
     return "aesni";
 }
METHOD (plugin_t , get_features , int , private_aesni_plugin_t * this, plugin_feature_t * features[])
Definition at line 50 of file aesni_plugin.c.
References aesni_cbc_create(), aesni_ccm_create(), aesni_cmac_prf_create(), aesni_cmac_signer_create(), aesni_ctr_create(), aesni_gcm_create(), aesni_xcbc_prf_create(), aesni_xcbc_signer_create(), AUTH_AES_CMAC_96, AUTH_AES_XCBC_96, countof, CPU_FEATURE_AESNI, cpu_feature_available(), CPU_FEATURE_PCLMULQDQ, ENCR_AES_CBC, ENCR_AES_CCM_ICV12, ENCR_AES_CCM_ICV16, ENCR_AES_CCM_ICV8, ENCR_AES_CTR, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, PLUGIN_PROVIDE, PLUGIN_REGISTER, PRF_AES128_CMAC, and PRF_AES128_XCBC.
 {
     static plugin_feature_t f[] = {
         PLUGIN_REGISTER(CRYPTER, aesni_cbc_create),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CBC, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CBC, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CBC, 32),
         PLUGIN_REGISTER(CRYPTER, aesni_ctr_create),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CTR, 16),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CTR, 24),
             PLUGIN_PROVIDE(CRYPTER, ENCR_AES_CTR, 32),
         PLUGIN_REGISTER(AEAD, aesni_ccm_create),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV8,  16),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV12, 16),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV16, 16),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV8,  24),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV12, 24),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV16, 24),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV8,  32),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV12, 32),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_CCM_ICV16, 32),
         PLUGIN_REGISTER(AEAD, aesni_gcm_create),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV8,  16),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV12, 16),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV16, 16),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV8,  24),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV12, 24),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV16, 24),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV8,  32),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV12, 32),
             PLUGIN_PROVIDE(AEAD, ENCR_AES_GCM_ICV16, 32),
         PLUGIN_REGISTER(PRF, aesni_xcbc_prf_create),
             PLUGIN_PROVIDE(PRF, PRF_AES128_XCBC),
         PLUGIN_REGISTER(SIGNER, aesni_xcbc_signer_create),
             PLUGIN_PROVIDE(SIGNER, AUTH_AES_XCBC_96),
         PLUGIN_REGISTER(PRF, aesni_cmac_prf_create),
             PLUGIN_PROVIDE(PRF, PRF_AES128_CMAC),
         PLUGIN_REGISTER(SIGNER, aesni_cmac_signer_create),
             PLUGIN_PROVIDE(SIGNER, AUTH_AES_CMAC_96),
     };
     *features = f;
     if (cpu_feature_available(CPU_FEATURE_AESNI | CPU_FEATURE_PCLMULQDQ))
     {
         return countof(f);
     }
     return 0;
 }
METHOD (plugin_t , destroy , void , private_aesni_plugin_t * this)
Definition at line 100 of file aesni_plugin.c.
References free().
 {
     free(this);
 }