strongSwan: status
status
utils
Typedefs
typedef enum status_t status_t
Enumerations
enum status_t {
SUCCESS, FAILED, OUT_OF_RES, ALREADY_DONE,
NOT_SUPPORTED, INVALID_ARG, NOT_FOUND, PARSE_ERROR,
VERIFY_ERROR, INVALID_STATE, DESTROY_ME, NEED_MORE
}
Functions
status_t return_failed ()
status_t return_success ()
Variables
enum_name_t * status_names
Detailed Description
Typedef Documentation
typedef enum status_t status_t
Definition at line 25 of file status.h.
Enumeration Type Documentation
enum status_t
Return values of function calls.
Enumerator
SUCCESS
Call succeeded
FAILED
Call failed
OUT_OF_RES
Out of resources
ALREADY_DONE
The suggested operation is already done
NOT_SUPPORTED
Not supported
INVALID_ARG
One of the arguments is invalid
NOT_FOUND
Something could not be found
PARSE_ERROR
Error while parsing
VERIFY_ERROR
Error while verifying
INVALID_STATE
Object in invalid state
DESTROY_ME
Destroy object which called method belongs to
NEED_MORE
Another call to the method is required
Definition at line 30 of file status.h.
               {
     SUCCESS,
     FAILED,
     OUT_OF_RES,
     ALREADY_DONE,
     NOT_SUPPORTED,
     INVALID_ARG,
     NOT_FOUND,
     PARSE_ERROR,
     VERIFY_ERROR,
     INVALID_STATE,
     DESTROY_ME,
     NEED_MORE,
 };
Function Documentation
status_t return_failed ()
returns FAILED
Definition at line 37 of file status.c.
References FAILED.
Referenced by load_tester_ipsec_create(), psk_authenticator_create_builder(), psk_authenticator_create_verifier(), pubkey_authenticator_create_builder(), pubkey_authenticator_create_verifier(), and START_TEST().
 {
     return FAILED;
 }
status_t return_success ()
returns SUCCESS
Definition at line 45 of file status.c.
References SUCCESS.
Referenced by delete_failed_sa(), ike_dpd_create(), and START_TEST().
 {
     return SUCCESS;
 }
Variable Documentation
enum_name_t* status_names
enum_names for type status_t.