strongSwan: semaphore_t Struct Reference
semaphore_t Struct Reference
semaphore
#include "semaphore.h"
Public Attributes
void(* wait)(semaphore_t *this)
bool(* timed_wait)(semaphore_t *this, u_int timeout)
bool(* timed_wait_abs)(semaphore_t *this, timeval_t tv)
void(* post)(semaphore_t *this)
void(* destroy)(semaphore_t *this)
Detailed Description
A semaphore is basically an integer whose value is never allowed to be lower than 0. Two operations can be performed on it: increment the value by one, and decrement the value by one. If the value is currently zero, then the decrement operation will blcok until the value becomes greater than zero.
Definition at line 35 of file semaphore.h.
Member Data Documentation
void(* semaphore_t::destroy)(semaphore_t *this)
Destroy a semaphore and free its resources.
Definition at line 75 of file semaphore.h.
Referenced by START_TEST().
void(* semaphore_t::post)(semaphore_t *this)
Increase the value by one. If the value becomes greater than zero, then another thread waiting will be woken up.
Definition at line 70 of file semaphore.h.
Referenced by listener_done(), and semaphore_run().
bool(* semaphore_t::timed_wait)(semaphore_t *this, u_int timeout)
Decrease the value by one, if it is greater than zero. Otherwise the current thread is blocked and it waits until the value increases, or the call times out.
Parameters
timeout timeout im ms
Returns
TRUE if timed out, FALSE otherwise
Definition at line 51 of file semaphore.h.
Referenced by START_TEST(), and wait_for_listener().
bool(* semaphore_t::timed_wait_abs)(semaphore_t *this, timeval_t tv)
Decrease the value by one, if it is greater than zero. Otherwise the current thread is blocked and it waits until the value increases, or the call times out.
The passed timeval should be calculated based on the time_monotonic() function.
Parameters
tv absolute time until timeout
Returns
TRUE if timed out, FALSE otherwise
Definition at line 64 of file semaphore.h.
Referenced by START_TEST().
void(* semaphore_t::wait)(semaphore_t *this)
Decrease the value by one, if it is greater than zero. Otherwise the current thread is blocked and it waits until the value increases.
Definition at line 41 of file semaphore.h.
Referenced by semaphore_cancel_run(), START_TEST(), and wait_for_listener().
The documentation for this struct was generated from the following file:
semaphore.h