strongSwan: vici_logger.c File Reference
vici_logger.c File Reference
#include "vici_logger.h"
#include "vici_builder.h"
#include <daemon.h>
#include <threading/mutex.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_vici_logger_t
Typedefs
typedef struct
private_vici_logger_t private_vici_logger_t
Functions
static job_requeue_t raise_events (private_vici_logger_t *this)
static void queue_messsage (private_vici_logger_t *this, vici_message_t *message)
METHOD (logger_t, log_, void, private_vici_logger_t *this, debug_t group, level_t level, int thread, ike_sa_t *ike_sa, const char *msg)
METHOD (logger_t, get_level, level_t, private_vici_logger_t *this, debug_t group)
static void manage_commands (private_vici_logger_t *this, bool reg)
METHOD (vici_logger_t, destroy, void, private_vici_logger_t *this)
vici_logger_t * vici_logger_create (vici_dispatcher_t *dispatcher)
Typedef Documentation
typedef struct private_vici_logger_t private_vici_logger_t
Definition at line 23 of file vici_logger.c.
Function Documentation
static void manage_commands (private_vici_logger_t * this, bool reg) static
(Un-)register dispatcher functions/events
Definition at line 139 of file vici_logger.c.
Referenced by METHOD(), and vici_logger_create().
 {
     this->dispatcher->manage_event(this->dispatcher, "log", reg);
 }
METHOD (logger_t , log_ , void , private_vici_logger_t * this, debug_t group, level_t level, int thread, ike_sa_t * ike_sa, const char * msg)
Definition at line 94 of file vici_logger.c.
References vici_builder_t::add_kv, debug_names, vici_builder_t::finalize, ike_sa_t::get_name, ike_sa_t::get_unique_id, mutex_t::lock, mutex, queue_messsage(), mutex_t::unlock, and vici_builder_create().
 {
     this->mutex->lock(this->mutex);
     /* avoid recursive invocations by the vici subsystem */
     if (this->recursive++ == 0)
     {
         vici_message_t *message;
         vici_builder_t *builder;
         builder = vici_builder_create();
         builder->add_kv(builder, "group", "%N", debug_names, group);
         builder->add_kv(builder, "level", "%d", level);
         builder->add_kv(builder, "thread", "%d", thread);
         if (ike_sa)
         {
             builder->add_kv(builder, "ikesa-name", "%s",
                             ike_sa->get_name(ike_sa));
             builder->add_kv(builder, "ikesa-uniqueid", "%u",
                             ike_sa->get_unique_id(ike_sa));
         }
         builder->add_kv(builder, "msg", "%s", msg);
         message = builder->finalize(builder);
         if (message)
         {
             queue_messsage(this, message);
         }
     }
     this->recursive--;
     this->mutex->unlock(this->mutex);
 }
METHOD (logger_t , get_level , level_t , private_vici_logger_t * this, debug_t group)
Definition at line 130 of file vici_logger.c.
References LEVEL_CTRL.
 {
     return LEVEL_CTRL;
 }
METHOD (vici_logger_t , destroy , void , private_vici_logger_t * this)
Definition at line 144 of file vici_logger.c.
References mutex_t::destroy, destroy(), FALSE, free(), manage_commands(), mutex, and queue().
 {
     manage_commands(this, FALSE);
     this->queue->destroy_offset(this->queue, offsetof(vici_message_t, destroy));
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void queue_messsage (private_vici_logger_t * this, vici_message_t * message) static
Queue a message for async processing
Definition at line 83 of file vici_logger.c.
References callback_job_create(), lib, library_t::processor, queue(), processor_t::queue_job, and raise_events().
Referenced by METHOD().
 {
     this->queue->insert_last(this->queue, message);
     if (this->queue->get_count(this->queue) == 1)
     {
         lib->processor->queue_job(lib->processor, (job_t*)
                     callback_job_create((callback_job_cb_t)raise_events,
                                         this, NULL, NULL));
     }
 }
static job_requeue_t raise_events (private_vici_logger_t * this) static
Async callback to raise events for queued messages
Definition at line 59 of file vici_logger.c.
References count, JOB_REQUEUE_DIRECT, JOB_REQUEUE_NONE, mutex_t::lock, mutex, queue(), and mutex_t::unlock.
Referenced by queue_messsage().
 {
     vici_message_t *message;
     u_int count;
     this->mutex->lock(this->mutex);
     count = this->queue->get_count(this->queue);
     this->queue->remove_first(this->queue, (void**)&message);
     this->mutex->unlock(this->mutex);
     if (count > 0)
     {
         this->dispatcher->raise_event(this->dispatcher, "log", 0, message);
     }
     if (count > 1)
     {
         return JOB_REQUEUE_DIRECT;
     }
     return JOB_REQUEUE_NONE;
 }