strongSwan: ike_config.c File Reference
ike_config.c File Reference
#include "ike_config.h"
#include <daemon.h>
#include <encoding/payloads/cp_payload.h>
Classes
struct private_ike_config_t
struct entry_t
Typedefs
typedef struct private_ike_config_t private_ike_config_t
Functions
static configuration_attribute_t * build_vip (host_t *vip)
static void handle_attribute (private_ike_config_t *this, configuration_attribute_t *ca)
static void process_attribute (private_ike_config_t *this, configuration_attribute_t *ca)
static void process_payloads (private_ike_config_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_ike_config_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_ike_config_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_ike_config_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_ike_config_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_ike_config_t *this)
METHOD (task_t, migrate, void, private_ike_config_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_ike_config_t *this)
ike_config_t * ike_config_create (ike_sa_t *ike_sa, bool initiator)
Typedef Documentation
typedef struct private_ike_config_t private_ike_config_t
Definition at line 22 of file ike_config.c.
Function Documentation
static configuration_attribute_t* build_vip (host_t * vip) static
build INTERNAL_IPV4/6_ADDRESS attribute from virtual ip
Definition at line 68 of file ike_config.c.
References chunk_alloca, chunk_cata, chunk_empty, configuration_attribute_create_chunk(), host_t::get_address, host_t::get_family, INTERNAL_IP4_ADDRESS, INTERNAL_IP6_ADDRESS, host_t::is_anyaddr, PLV2_CONFIGURATION_ATTRIBUTE, prefix, chunk_t::ptr, and type.
Referenced by METHOD().
 {
     configuration_attribute_type_t type;
     chunk_t chunk, prefix;
     if (vip->get_family(vip) == AF_INET)
     {
         type = INTERNAL_IP4_ADDRESS;
         if (vip->is_anyaddr(vip))
         {
             chunk = chunk_empty;
         }
         else
         {
             chunk = vip->get_address(vip);
         }
     }
     else
     {
         type = INTERNAL_IP6_ADDRESS;
         if (vip->is_anyaddr(vip))
         {
             chunk = chunk_empty;
         }
         else
         {
             prefix = chunk_alloca(1);
             *prefix.ptr = 64;
             chunk = vip->get_address(vip);
             chunk = chunk_cata("cc", chunk, prefix);
         }
     }
     return configuration_attribute_create_chunk(PLV2_CONFIGURATION_ATTRIBUTE,
                                                 type, chunk);
 }
static void handle_attribute (private_ike_config_t * this, configuration_attribute_t * ca) static
Handle a received attribute as initiator
Definition at line 107 of file ike_config.c.
References daemon_t::attributes, charon, enumerator_t::destroy, enumerator_t::enumerate, free(), configuration_attribute_t::get_chunk, configuration_attribute_t::get_type, attribute_manager_t::handle, entry_t::handler, and entry_t::type.
Referenced by process_attribute().
 {
     attribute_handler_t *handler = NULL;
     enumerator_t *enumerator;
     entry_t *entry;
     /* find the handler which requested this attribute */
     enumerator = this->requested->create_enumerator(this->requested);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->type == ca->get_type(ca))
         {
             handler = entry->handler;
             this->requested->remove_at(this->requested, enumerator);
             free(entry);
             break;
         }
     }
     enumerator->destroy(enumerator);
     /* and pass it to the handle function */
     handler = charon->attributes->handle(charon->attributes,
                     this->ike_sa, handler, ca->get_type(ca), ca->get_chunk(ca));
     this->ike_sa->add_configuration_attribute(this->ike_sa,
                             handler, ca->get_type(ca), ca->get_chunk(ca));
 }
METHOD (task_t , build_i , status_t , private_ike_config_t * this, message_t * message)
Definition at line 228 of file ike_config.c.
References cp_payload_t::add_attribute, message_t::add_payload, daemon_t::attributes, build_vip(), CFG_REQUEST, charon, configuration_attribute_create_chunk(), configuration_attribute_type_names, cp, cp_payload_create_type(), linked_list_t::create_enumerator, attribute_manager_t::create_initiator_enumerator, peer_cfg_t::create_virtual_ip_enumerator, data, DBG2, DBG_IKE, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, message_t::get_message_id, entry_t::handler, host, linked_list_t::insert_last, linked_list_create(), malloc_thing, NEED_MORE, PLV2_CONFIGURATION, PLV2_CONFIGURATION_ATTRIBUTE, TRUE, type, and entry_t::type.
 {
     if (message->get_message_id(message) == 1)
     {   /* in first IKE_AUTH only */
         cp_payload_t *cp = NULL;
         enumerator_t *enumerator;
         attribute_handler_t *handler;
         peer_cfg_t *config;
         configuration_attribute_type_t type;
         chunk_t data;
         linked_list_t *vips;
         host_t *host;
         vips = linked_list_create();
         /* reuse virtual IP if we already have one */
         enumerator = this->ike_sa->create_virtual_ip_enumerator(this->ike_sa,
                                                                 TRUE);
         while (enumerator->enumerate(enumerator, &host))
         {
             vips->insert_last(vips, host);
         }
         enumerator->destroy(enumerator);
         if (vips->get_count(vips) == 0)
         {
             config = this->ike_sa->get_peer_cfg(this->ike_sa);
             enumerator = config->create_virtual_ip_enumerator(config);
             while (enumerator->enumerate(enumerator, &host))
             {
                 vips->insert_last(vips, host);
             }
             enumerator->destroy(enumerator);
         }
         if (vips->get_count(vips))
         {
             cp = cp_payload_create_type(PLV2_CONFIGURATION, CFG_REQUEST);
             enumerator = vips->create_enumerator(vips);
             while (enumerator->enumerate(enumerator, &host))
             {
                 cp->add_attribute(cp, build_vip(host));
             }
             enumerator->destroy(enumerator);
         }
         enumerator = charon->attributes->create_initiator_enumerator(
                                         charon->attributes, this->ike_sa, vips);
         while (enumerator->enumerate(enumerator, &handler, &type, &data))
         {
             configuration_attribute_t *ca;
             entry_t *entry;
             /* create configuration attribute */
             DBG2(DBG_IKE, "building %N attribute",
                  configuration_attribute_type_names, type);
             ca = configuration_attribute_create_chunk(PLV2_CONFIGURATION_ATTRIBUTE,
                                                       type, data);
             if (!cp)
             {
                 cp = cp_payload_create_type(PLV2_CONFIGURATION, CFG_REQUEST);
             }
             cp->add_attribute(cp, ca);
             /* save handler along with requested type */
             entry = malloc_thing(entry_t);
             entry->type = type;
             entry->handler = handler;
             this->requested->insert_last(this->requested, entry);
         }
         enumerator->destroy(enumerator);
         vips->destroy(vips);
         if (cp)
         {
             message->add_payload(message, (payload_t*)cp);
         }
     }
     return NEED_MORE;
 }
METHOD (task_t , process_r , status_t , private_ike_config_t * this, message_t * message)
Definition at line 312 of file ike_config.c.
References message_t::get_message_id, NEED_MORE, and process_payloads().
 {
     if (message->get_message_id(message) == 1)
     {   /* in first IKE_AUTH only */
         process_payloads(this, message);
     }
     return NEED_MORE;
 }
METHOD (task_t , build_r , status_t , private_ike_config_t * this, message_t * message)
Definition at line 322 of file ike_config.c.
References attribute_manager_t::acquire_address, cp_payload_t::add_attribute, message_t::add_notify, message_t::add_payload, bus_t::alert, ALERT_VIP_FAILURE, bus_t::assign_vips, daemon_t::attributes, build_vip(), daemon_t::bus, CFG_REPLY, charon, chunk_empty, configuration_attribute_create_chunk(), configuration_attribute_type_names, cp, cp_payload_create_type(), linked_list_t::create_enumerator, peer_cfg_t::create_pool_enumerator, attribute_manager_t::create_responder_enumerator, DBG1, DBG2, DBG_IKE, enumerator_t::destroy, linked_list_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, FAILED_CP_REQUIRED, FALSE, found, linked_list_t::get_count, id, IKE_ESTABLISHED, linked_list_t::insert_last, INTERNAL_ADDRESS_FAILURE, linked_list_create(), linked_list_create_from_enumerator(), NEED_MORE, notify_type_names, PLV2_CONFIGURATION, PLV2_CONFIGURATION_ATTRIBUTE, SUCCESS, TRUE, type, and value.
 {
     if (this->ike_sa->get_state(this->ike_sa) == IKE_ESTABLISHED)
     {   /* in last IKE_AUTH exchange */
         enumerator_t *enumerator;
         configuration_attribute_type_t type;
         chunk_t value;
         cp_payload_t *cp = NULL;
         peer_cfg_t *config;
         identification_t *id;
         linked_list_t *vips, *pools;
         host_t *requested;
         id = this->ike_sa->get_other_eap_id(this->ike_sa);
         config = this->ike_sa->get_peer_cfg(this->ike_sa);
         vips = linked_list_create();
         pools = linked_list_create_from_enumerator(
                                     config->create_pool_enumerator(config));
         this->ike_sa->clear_virtual_ips(this->ike_sa, FALSE);
         enumerator = this->vips->create_enumerator(this->vips);
         while (enumerator->enumerate(enumerator, &requested))
         {
             host_t *found = NULL;
             /* query all pools until we get an address */
             DBG1(DBG_IKE, "peer requested virtual IP %H", requested);
             found = charon->attributes->acquire_address(charon->attributes,
                                                 pools, this->ike_sa, requested);
             if (found)
             {
                 DBG1(DBG_IKE, "assigning virtual IP %H to peer '%Y'", found, id);
                 this->ike_sa->add_virtual_ip(this->ike_sa, FALSE, found);
                 if (!cp)
                 {
                     cp = cp_payload_create_type(PLV2_CONFIGURATION, CFG_REPLY);
                 }
                 cp->add_attribute(cp, build_vip(found));
                 vips->insert_last(vips, found);
             }
             else
             {
                 DBG1(DBG_IKE, "no virtual IP found for %H requested by '%Y'",
                      requested, id);
             }
         }
         enumerator->destroy(enumerator);
         if (this->vips->get_count(this->vips) && !vips->get_count(vips))
         {
             DBG1(DBG_IKE, "no virtual IP found, sending %N",
                  notify_type_names, INTERNAL_ADDRESS_FAILURE);
             charon->bus->alert(charon->bus, ALERT_VIP_FAILURE, this->vips);
             message->add_notify(message, FALSE, INTERNAL_ADDRESS_FAILURE,
                                 chunk_empty);
             vips->destroy_offset(vips, offsetof(host_t, destroy));
             pools->destroy(pools);
             return SUCCESS;
         }
         charon->bus->assign_vips(charon->bus, this->ike_sa, TRUE);
         if (pools->get_count(pools) && !this->vips->get_count(this->vips))
         {
             DBG1(DBG_IKE, "expected a virtual IP request, sending %N",
                  notify_type_names, FAILED_CP_REQUIRED);
             charon->bus->alert(charon->bus, ALERT_VIP_FAILURE, this->vips);
             message->add_notify(message, FALSE, FAILED_CP_REQUIRED, chunk_empty);
             vips->destroy_offset(vips, offsetof(host_t, destroy));
             pools->destroy(pools);
             return SUCCESS;
         }
         /* query registered providers for additional attributes to include */
         enumerator = charon->attributes->create_responder_enumerator(
                                 charon->attributes, pools, this->ike_sa, vips);
         while (enumerator->enumerate(enumerator, &type, &value))
         {
             if (!cp)
             {
                 cp = cp_payload_create_type(PLV2_CONFIGURATION, CFG_REPLY);
             }
             DBG2(DBG_IKE, "building %N attribute",
                  configuration_attribute_type_names, type);
             cp->add_attribute(cp,
                 configuration_attribute_create_chunk(PLV2_CONFIGURATION_ATTRIBUTE,
                                                      type, value));
         }
         enumerator->destroy(enumerator);
         vips->destroy_offset(vips, offsetof(host_t, destroy));
         pools->destroy(pools);
         if (cp)
         {
             message->add_payload(message, (payload_t*)cp);
         }
         return SUCCESS;
     }
     return NEED_MORE;
 }
METHOD (task_t , process_i , status_t , private_ike_config_t * this, message_t * message)
Definition at line 425 of file ike_config.c.
References daemon_t::bus, charon, enumerator_t::destroy, enumerator_t::enumerate, bus_t::handle_vips, host, IKE_ESTABLISHED, host_t::is_anyaddr, NEED_MORE, process_payloads(), SUCCESS, and TRUE.
 {
     if (this->ike_sa->get_state(this->ike_sa) == IKE_ESTABLISHED)
     {   /* in last IKE_AUTH exchange */
         enumerator_t *enumerator;
         host_t *host;
         process_payloads(this, message);
         this->ike_sa->clear_virtual_ips(this->ike_sa, TRUE);
         enumerator = this->vips->create_enumerator(this->vips);
         while (enumerator->enumerate(enumerator, &host))
         {
             if (!host->is_anyaddr(host))
             {
                 this->ike_sa->add_virtual_ip(this->ike_sa, TRUE, host);
             }
         }
         enumerator->destroy(enumerator);
         charon->bus->handle_vips(charon->bus, this->ike_sa, TRUE);
         return SUCCESS;
     }
     return NEED_MORE;
 }
METHOD (task_t , get_type , task_type_t , private_ike_config_t * this)
Definition at line 453 of file ike_config.c.
References TASK_IKE_CONFIG.
 {
     return TASK_IKE_CONFIG;
 }
METHOD (task_t , migrate , void , private_ike_config_t * this, ike_sa_t * ike_sa)
Definition at line 459 of file ike_config.c.
References destroy(), free(), and linked_list_create().
 {
     this->ike_sa = ike_sa;
     this->vips->destroy_offset(this->vips, offsetof(host_t, destroy));
     this->vips = linked_list_create();
     this->requested->destroy_function(this->requested, free);
     this->requested = linked_list_create();
 }
METHOD (task_t , destroy , void , private_ike_config_t * this)
Definition at line 469 of file ike_config.c.
References destroy(), and free().
 {
     this->vips->destroy_offset(this->vips, offsetof(host_t, destroy));
     this->requested->destroy_function(this->requested, free);
     free(this);
 }
static void process_attribute (private_ike_config_t * this, configuration_attribute_t * ca) static
process a single configuration attribute
Definition at line 138 of file ike_config.c.
References addr, EXT_MS_WINDOWS, family, configuration_attribute_t::get_chunk, configuration_attribute_t::get_type, handle_attribute(), host_create_any(), host_create_from_chunk(), initiator, INTERNAL_IP4_ADDRESS, INTERNAL_IP4_SERVER, INTERNAL_IP6_ADDRESS, INTERNAL_IP6_SERVER, ip, and chunk_t::len.
Referenced by process_payloads().
 {
     host_t *ip;
     chunk_t addr;
     int family = AF_INET6;
     switch (ca->get_type(ca))
     {
         case INTERNAL_IP4_ADDRESS:
             family = AF_INET;
             /* fall */
         case INTERNAL_IP6_ADDRESS:
         {
             addr = ca->get_chunk(ca);
             if (addr.len == 0)
             {
                 ip = host_create_any(family);
             }
             else
             {
                 /* skip prefix byte in IPv6 payload*/
                 if (family == AF_INET6)
                 {
                     addr.len--;
                 }
                 ip = host_create_from_chunk(family, addr, 0);
             }
             if (ip)
             {
                 this->vips->insert_last(this->vips, ip);
             }
             break;
         }
         case INTERNAL_IP4_SERVER:
         case INTERNAL_IP6_SERVER:
             /* assume it's a Windows client if we see proprietary attributes */
             this->ike_sa->enable_extension(this->ike_sa, EXT_MS_WINDOWS);
             /* fall */
         default:
         {
             if (this->initiator)
             {
                 handle_attribute(this, ca);
             }
         }
     }
 }
static void process_payloads (private_ike_config_t * this, message_t * message) static
Scan for configuration payloads and attributes
Definition at line 190 of file ike_config.c.
References attributes, CFG_REPLY, CFG_REQUEST, config_type_names, configuration_attribute_type_names, cp, cp_payload_t::create_attribute_enumerator, message_t::create_payload_enumerator, DBG1, DBG2, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, configuration_attribute_t::get_type, cp_payload_t::get_type, payload_t::get_type, PLV2_CONFIGURATION, and process_attribute().
Referenced by METHOD().
 {
     enumerator_t *enumerator, *attributes;
     payload_t *payload;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV2_CONFIGURATION)
         {
             cp_payload_t *cp = (cp_payload_t*)payload;
             configuration_attribute_t *ca;
             switch (cp->get_type(cp))
             {
                 case CFG_REQUEST:
                 case CFG_REPLY:
                 {
                     attributes = cp->create_attribute_enumerator(cp);
                     while (attributes->enumerate(attributes, &ca))
                     {
                         DBG2(DBG_IKE, "processing %N attribute",
                              configuration_attribute_type_names, ca->get_type(ca));
                         process_attribute(this, ca);
                     }
                     attributes->destroy(attributes);
                     break;
                 }
                 default:
                     DBG1(DBG_IKE, "ignoring %N config payload",
                          config_type_names, cp->get_type(cp));
                     break;
             }
         }
     }
     enumerator->destroy(enumerator);
 }