strongSwan: credential_manager_t Struct Reference
credential_manager_t Struct Reference
credential_manager
#include "credential_manager.h"
Public Attributes
enumerator_t *(* create_cert_enumerator)(credential_manager_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
enumerator_t *(* create_shared_enumerator)(credential_manager_t *this, shared_key_type_t type, identification_t *first, identification_t *second)
enumerator_t *(* create_cdp_enumerator)(credential_manager_t *this, certificate_type_t type, identification_t *id)
certificate_t *(* get_cert)(credential_manager_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
shared_key_t *(* get_shared)(credential_manager_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
private_key_t *(* get_private)(credential_manager_t *this, key_type_t type, identification_t *id, auth_cfg_t *auth)
enumerator_t *(* create_trusted_enumerator)(credential_manager_t *this, key_type_t type, identification_t *id, bool online)
enumerator_t *(* create_public_enumerator)(credential_manager_t *this, key_type_t type, identification_t *id, auth_cfg_t *auth)
void(* cache_cert)(credential_manager_t *this, certificate_t *cert)
void(* flush_cache)(credential_manager_t *this, certificate_type_t type)
bool(* issued_by)(credential_manager_t *this, certificate_t *subject, certificate_t *issuer, signature_scheme_t *scheme)
void(* add_set)(credential_manager_t *this, credential_set_t *set)
void(* remove_set)(credential_manager_t *this, credential_set_t *set)
void(* add_local_set)(credential_manager_t *this, credential_set_t *set, bool exclusive)
void(* remove_local_set)(credential_manager_t *this, credential_set_t *set)
void(* add_validator)(credential_manager_t *this, cert_validator_t *vdtr)
void(* remove_validator)(credential_manager_t *this, cert_validator_t *vdtr)
void(* set_hook)(credential_manager_t *this, credential_hook_t hook, void *data)
void(* call_hook)(credential_manager_t *this, credential_hook_type_t type, certificate_t *cert)
void(* destroy)(credential_manager_t *this)
Detailed Description
Manages credentials using credential_sets.
The credential manager is the entry point of the credential framework. It uses so called "sets" to access credentials in a modular fashion. These are implemented through the credential_set_t interface. The manager additionally does trust chain verification and trust status caching. A set may call the managers methods if it needs credentials itself. The manager uses recursive locking.
+-------+        +----------------+
|   A   |        |                |          +------------------+
|   u   | -----> |                | ------>  |  +------------------+
|   t   |        |   credential-  |          |  |  +------------------+
|   h   | -----> |     manager    | ------>  +--|  |   credential-    | => IPC
|   e   |        |                |             +--|       sets       |
|   n   |   +--> |                | ------>        +------------------+
|   t   |   |    |                |                        |
|   i   |   |    |                |                        |
|   c   |   |    +----------------+                        |
|   a   |   |                                              |
|   t   |   +----------------------------------------------+
|   o   |                    may be recursive
|   r   |
+-------+
The credential manager uses rwlocks for performance reasons. Credential sets must be fully thread-safe.
Definition at line 100 of file credential_manager.h.
Member Data Documentation
void(* credential_manager_t::add_local_set)(credential_manager_t *this, credential_set_t *set, bool exclusive)
Register a thread local credential set to the manager.
To add a credential set for the current trustchain verification operation, sets may be added for the calling thread only. This does not require a write lock and is therefore a much cheaper operation. The exclusive option allows to disable all other credential sets until the set is deregistered.
Parameters
set set to register
exclusive TRUE to disable all other sets for this thread
Definition at line 273 of file credential_manager.h.
Referenced by decrypt_with_config(), load_from_file(), load_pin(), METHOD(), pkcs7(), verify_eap(), and verify_ocsp().
void(* credential_manager_t::add_set)(credential_manager_t *this, credential_set_t *set)
Register a credential set to the manager.
Parameters
set set to register
Definition at line 251 of file credential_manager.h.
Referenced by add_callback(), cmd_creds_create(), decrypt(), init(), keychain_cb(), keychain_creds_create(), maemo_service_create(), main(), METHOD(), nm_backend_init(), open_database(), plugin_cb(), register_load_tester(), register_vici(), setup_tunnel(), START_SETUP(), stroke_cred_create(), stroke_socket_create(), tnc_ifmap_soap_create(), token_event_cb(), verify(), and vici_cred_create().
void(* credential_manager_t::add_validator)(credential_manager_t *this, cert_validator_t *vdtr)
Register a certificate validator to the manager.
Parameters
vdtr validator to register
Definition at line 288 of file credential_manager.h.
Referenced by plugin_cb().
void(* credential_manager_t::cache_cert)(credential_manager_t *this, certificate_t *cert)
Cache a certificate by invoking cache_cert() on all registered sets.
Parameters
cert certificate to cache
Definition at line 219 of file credential_manager.h.
Referenced by fetch_cert(), get_better_crl(), and get_better_ocsp().
void(* credential_manager_t::call_hook)(credential_manager_t *this, credential_hook_type_t type, certificate_t *cert)
Call the registered credential hook, if any.
While hooks are usually called by the credential manager itself, some validator plugins might raise hooks as well if they consider certificates invalid.
Parameters
type type of the event
cert associated certificate
Definition at line 316 of file credential_manager.h.
Referenced by METHOD().
enumerator_t*(* credential_manager_t::create_cdp_enumerator)(credential_manager_t *this, certificate_type_t type, identification_t *id)
Create an enumerator over all Certificate Distribution Points.
Parameters
type kind of certificate the point distributes
id identification of the distributed certificate
Returns
enumerator of CDPs as char*
Definition at line 136 of file credential_manager.h.
Referenced by build_cert_payload(), check_ocsp(), and find_crl().
enumerator_t*(* credential_manager_t::create_cert_enumerator)(credential_manager_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
Create an enumerator over all certificates.
Parameters
cert kind of certificate
key kind of key in certificate
id subject this certificate belongs to
trusted TRUE to list trusted certificates only
Returns
enumerator over the certificates
Definition at line 111 of file credential_manager.h.
Referenced by add_attribute_certs(), add_local_certs(), build_certreqs(), CALLBACK(), check_ocsp(), create_unique_cert_list(), find_client_id(), find_crl(), find_private(), find_smartcard_key(), METHOD(), send_certificate_request(), stroke_export(), and verify_ocsp().
enumerator_t*(* credential_manager_t::create_public_enumerator)(credential_manager_t *this, key_type_t type, identification_t *id, auth_cfg_t *auth)
Create an enumerator over trusted public keys.
This method creates an enumerator over trusted public keys to verify a signature created by id. The auth parameter contains additional authentication infos, e.g. peer and intermediate certificates. The resulting enumerator enumerates over public_key_t *, auth_cfg_t *, where the auth config helper contains rules for constraint checks. This function is very similar to create_trusted_enumerator(), but gets public keys directly.
Parameters
type type of the key to get
id owner of the key, signer of the signature
auth authentication infos
Returns
enumerator
Definition at line 211 of file credential_manager.h.
Referenced by find_public_key(), METHOD(), and process_cert_verify().
enumerator_t*(* credential_manager_t::create_shared_enumerator)(credential_manager_t *this, shared_key_type_t type, identification_t *first, identification_t *second)
Create an enumerator over all shared keys.
The enumerator enumerates over: shared_key_t*, id_match_t me, id_match_t other But must accept values for the id_matches.
Parameters
type kind of requested shared key
first first subject between key is shared
second second subject between key is shared
Returns
enumerator over (shared_key_t*,id_match_t,id_match_t)
Definition at line 126 of file credential_manager.h.
Referenced by decrypt(), decrypt_and_unpack(), decrypt_private_key(), login(), METHOD(), pem_to_bin(), reauth(), and verify_mac().
enumerator_t*(* credential_manager_t::create_trusted_enumerator)(credential_manager_t *this, key_type_t type, identification_t *id, bool online)
Create an enumerator over trusted certificates.
This method creates an enumerator over trusted certificates. The auth parameter (if given) receives the trustchain used to validate the certificate. The resulting enumerator enumerates over certificate_t*, auth_cfg_t*. If online is set, revocations are checked online for the whole trustchain.
Parameters
type type of the key we want a certificate for
id subject of the certificate
online whether revocations should be checked online
Returns
enumerator
Definition at line 192 of file credential_manager.h.
Referenced by check_oid(), check_trust(), imv_attestation_process(), METHOD(), verify(), and verify_crl().
void(* credential_manager_t::destroy)(credential_manager_t *this)
Destroy a credential_manager instance.
Definition at line 322 of file credential_manager.h.
void(* credential_manager_t::flush_cache)(credential_manager_t *this, certificate_type_t type)
Flush the certificate cache.
Only the managers local cache is flushed, but not the sets cache filled by the cache_cert() method.
Parameters
type type of certificate to flush, or CERT_ANY
Definition at line 229 of file credential_manager.h.
Referenced by CALLBACK(), destroy(), keychain_cb(), library_deinit(), METHOD(), START_TEARDOWN(), stroke_purge(), test_runner_init(), and token_event_cb().
certificate_t*(* credential_manager_t::get_cert)(credential_manager_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
Get a trusted or untrusted certificate.
Parameters
cert kind of certificate
key kind of key in certificate
id subject this certificate belongs to
trusted TRUE to get a trusted certificate only
Returns
certificate, if found, NULL otherwise
Definition at line 147 of file credential_manager.h.
Referenced by add_local_certs(), build_auth_cfg(), find_certificate(), process_certreq(), tkm_private_key_init(), and try_get_cert().
private_key_t*(* credential_manager_t::get_private)(credential_manager_t *this, key_type_t type, identification_t *id, auth_cfg_t *auth)
Get a private key to create a signature.
The get_private() method gets a secret private key identified by either the keyid itself or an id the key belongs to. The auth parameter contains additional information, such as recipients trusted CA certs. Auth gets filled with subject and CA certificates needed to validate a created signature.
Parameters
type type of the key to get
id identification the key belongs to
auth auth config, including trusted CA certificates
Returns
private_key_t, NULL if none found
Definition at line 174 of file credential_manager.h.
Referenced by add_local_certs(), build_auth(), find_client_id(), find_private(), find_private_key(), get_pubkey_method(), has_privkey(), list_public_key(), METHOD(), rebuild_auth(), select_suite_and_key(), and soap_init().
shared_key_t*(* credential_manager_t::get_shared)(credential_manager_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
Get the best matching shared key for two IDs.
Parameters
type kind of requested shared key
me own identity
other peer identity
Returns
shared_key_t, NULL if none found
Definition at line 158 of file credential_manager.h.
Referenced by eap_aka_3gpp2_get_k(), get_nt_hash(), hash_challenge(), lookup_shared_key(), and METHOD().
bool(* credential_manager_t::issued_by)(credential_manager_t *this, certificate_t *subject, certificate_t *issuer, signature_scheme_t *scheme)
Check if a given subject certificate is issued by an issuer certificate.
This operation does signature verification using the credential manager's cache to speed up the operation.
Parameters
subject subject certificate to check
issuer issuer certificate that potentially has signed subject
scheme receives used signature scheme, if given
Returns
TRUE if issuer signed subject
Definition at line 242 of file credential_manager.h.
Referenced by verify(), verify_crl(), and verify_ocsp().
void(* credential_manager_t::remove_local_set)(credential_manager_t *this, credential_set_t *set)
Unregister a thread local credential set from the manager.
Parameters
set set to unregister
Definition at line 281 of file credential_manager.h.
Referenced by decrypt_with_config(), load_from_file(), load_pin(), METHOD(), pkcs7(), verify_eap(), and verify_ocsp().
void(* credential_manager_t::remove_set)(credential_manager_t *this, credential_set_t *set)
Unregister a credential set from the manager.
Parameters
set set to unregister
Definition at line 258 of file credential_manager.h.
Referenced by cleanup(), decrypt(), exit_scepclient(), handle_certs(), keychain_cb(), METHOD(), nm_backend_deinit(), open_database(), plugin_cb(), register_load_tester(), register_vici(), remove_callback(), START_TEARDOWN(), token_event_cb(), and verify().
void(* credential_manager_t::remove_validator)(credential_manager_t *this, cert_validator_t *vdtr)
Remove a certificate validator from the manager.
Parameters
vdtr validator to unregister
Definition at line 295 of file credential_manager.h.
Referenced by plugin_cb().
void(* credential_manager_t::set_hook)(credential_manager_t *this, credential_hook_t hook, void *data)
Set a hook to call on certain credential validation errors.
Parameters
hook hook to register, NULL to unregister
data data to pass to hook
Definition at line 303 of file credential_manager.h.
Referenced by bus_create(), and METHOD().
The documentation for this struct was generated from the following file:
credential_manager.h