strongSwan: host
host
networking
Classes
struct host_t
Typedefs
typedef enum host_diff_t host_diff_t
typedef struct host_t host_t
Functions
host_t * host_create_from_string (char *string, u_int16_t port)
host_t * host_create_from_string_and_family (char *string, int family, u_int16_t port)
host_t * host_create_from_dns (char *string, int family, u_int16_t port)
host_t * host_create_from_chunk (int family, chunk_t address, u_int16_t port)
host_t * host_create_from_sockaddr (sockaddr_t *sockaddr)
bool host_create_from_range (char *string, host_t **from, host_t **to)
host_t * host_create_from_subnet (char *string, int *bits)
host_t * host_create_netmask (int family, int netbits)
host_t * host_create_any (int family)
int host_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Detailed Description
Typedef Documentation
typedef enum host_diff_t host_diff_t
Definition at line 30 of file host.h.
typedef struct host_t host_t
Definition at line 31 of file host.h.
Function Documentation
host_t* host_create_any (int family)
Create a host without an address, a "any" host.
Parameters
family family of the any host
Returns
host_t, NULL if family not supported
Definition at line 657 of file host.c.
References family, free(), host_create_empty(), memset, and update_sa_len().
Referenced by allocate_addr(), build_peer_cfg(), build_set(), client(), host_create_any_port(), ike_sa_create(), install_shunt_policy(), METHOD(), process_attribute(), pt_tls_receive(), resolve(), START_TEST(), test_create_any(), and uninstall_shunt_policy().
 {
     private_host_t *this = host_create_empty();
     memset(&this->address_max, 0, sizeof(struct sockaddr_storage));
     this->address.sa_family = family;
     switch (family)
     {
         case AF_INET:
         {
             this->socklen = sizeof(struct sockaddr_in);
             update_sa_len(this);
             return &(this->public);
         }
         case AF_INET6:
         {
             this->socklen = sizeof(struct sockaddr_in6);
             update_sa_len(this);
             return &this->public;
         }
         default:
             break;
     }
     free(this);
     return NULL;
 }
host_t* host_create_from_chunk (int family, chunk_t address, u_int16_t port)
Constructor to create a host_t object from an address chunk.
If family is AF_UNSPEC, it is guessed using address.len.
Parameters
family Address family, such as AF_INET or AF_INET6
address address as chunk_t in network order
port port number
Returns
host_t, NULL if family not supported/chunk invalid
Definition at line 477 of file host.c.
References family, host_create_empty(), IPV4_LEN, IPV6_LEN, chunk_t::len, memcpy, chunk_t::ptr, and update_sa_len().
Referenced by build_natd_payload(), check_lease(), del_attr(), get_lease(), get_route(), handle_ack(), handle_offer(), ip_packet_create(), leases(), manage_dns(), manage_route(), METHOD(), offset2host(), parse_notification_data(), print_host(), process_addr(), process_attribute(), process_cfg_attributes(), process_payloads(), process_route(), receive_arp(), receive_casts(), resize(), selector2ts(), START_TEST(), status(), status_attr(), and xfrm2host().
 {
     private_host_t *this;
     switch (family)
     {
         case AF_INET:
             if (address.len < IPV4_LEN)
             {
                 return NULL;
             }
             address.len = IPV4_LEN;
             break;
         case AF_INET6:
             if (address.len < IPV6_LEN)
             {
                 return NULL;
             }
             address.len = IPV6_LEN;
             break;
         case AF_UNSPEC:
             switch (address.len)
             {
                 case IPV4_LEN:
                     family = AF_INET;
                     break;
                 case IPV6_LEN:
                     family = AF_INET6;
                     break;
                 default:
                     return NULL;
             }
             break;
         default:
             return NULL;
     }
     this = host_create_empty();
     this->address.sa_family = family;
     switch (family)
     {
         case AF_INET:
             memcpy(&this->address4.sin_addr.s_addr, address.ptr, address.len);
             this->address4.sin_port = htons(port);
             this->socklen = sizeof(struct sockaddr_in);
             break;
         case AF_INET6:
             memcpy(&this->address6.sin6_addr.s6_addr, address.ptr, address.len);
             this->address6.sin6_port = htons(port);
             this->socklen = sizeof(struct sockaddr_in6);
             break;
     }
     update_sa_len(this);
     return &this->public;
 }
host_t* host_create_from_dns (char * string, int family, u_int16_t port)
Constructor to create a host_t from a DNS name.
Parameters
string hostname to resolve
family family to prefer, 0 for first match
port port number
Returns
host_t, NULL lookup failed
Definition at line 458 of file host.c.
References host_create_from_string_and_family(), library_t::hosts, lib, host_resolver_t::resolve, and set_port().
Referenced by check_connection(), client(), ha_socket_create(), is_local(), main(), match(), resolve(), soap_init(), stream_parse_uri_tcp(), and test_create_from_dns().
 {
     host_t *this;
     this = host_create_from_string_and_family(string, af, port);
     if (!this)
     {
         this = lib->hosts->resolve(lib->hosts, string, af);
     }
     if (this)
     {
         this->set_port(this, port);
     }
     return this;
 }
bool host_create_from_range (char * string, host_t ** from, host_t ** to)
Parse a range definition (1.2.3.0-1.2.3.5), return the two hosts.
The two hosts are not ordered, from is simply the first, to is the second, from is not necessarily smaller.
Parameters
string string to parse
from returns the first address (out)
to returns the second address (out)
Returns
TRUE if parsed successfully, FALSE otherwise
Definition at line 535 of file host.c.
References FALSE, free(), host_create_from_string(), host_create_from_string_and_family(), sep, strndup(), and TRUE.
Referenced by create_pool_range(), make_range(), START_TEST(), and verify_range().
 {
     char *sep, *pos;
     sep = strchr(string, '-');
     if (!sep)
     {
         return FALSE;
     }
     for (pos = sep+1; *pos && *pos == ' '; pos++)
     {
         /* trim spaces before to address*/
     }
     *to = host_create_from_string(pos, 0);
     if (!*to)
     {
         return FALSE;
     }
     for (pos = sep-1; pos > string && *pos == ' '; pos--)
     {
         /* trim spaces behind from address */
     }
     pos = strndup(string, pos - string + 1);
     *from = host_create_from_string_and_family(pos, (*to)->get_family(*to), 0);
     free(pos);
     if (!*from)
     {
         (*to)->destroy(*to);
         return FALSE;
     }
     return TRUE;
 }
host_t* host_create_from_sockaddr (sockaddr_t * sockaddr)
Constructor to create a host_t object from a sockaddr struct
Parameters
sockaddr sockaddr struct which contains family, address and port
Returns
host_t, NULL if family not supported
Definition at line 426 of file host.c.
References free(), host_create_empty(), memcpy, and update_sa_len().
Referenced by get_route(), host_create_from_string_and_family(), init_address_list(), METHOD(), process_addr(), process_expire(), pt_tls_receive(), radius_receive(), receive(), receive_packet(), repopulate_iface(), resolve_hosts(), sadb_address2ts(), setup_interface(), START_TEST(), and update_addrs().
 {
     private_host_t *this = host_create_empty();
     switch (sockaddr->sa_family)
     {
         case AF_INET:
         {
             memcpy(&this->address4, (struct sockaddr_in*)sockaddr,
                    sizeof(struct sockaddr_in));
             this->socklen = sizeof(struct sockaddr_in);
             update_sa_len(this);
             return &this->public;
         }
         case AF_INET6:
         {
             memcpy(&this->address6, (struct sockaddr_in6*)sockaddr,
                    sizeof(struct sockaddr_in6));
             this->socklen = sizeof(struct sockaddr_in6);
             update_sa_len(this);
             return &this->public;
         }
         default:
             break;
     }
     free(this);
     return NULL;
 }
host_t* host_create_from_string (char * string, u_int16_t port)
Constructor to create a host_t object from an address string.
Parameters
string string of an address, such as "152.96.193.130"
port port number
Returns
host_t, NULL if string not an address.
Definition at line 418 of file host.c.
References host_create_from_string_and_family().
Referenced by add_address(), add_addresses(), add_legacy_entry(), add_ts(), add_unity_split_attribute(), assert_acquire(), assert_host(), build_peer_cfg(), CALLBACK(), cancellation_accept(), compile_address_list(), connect_(), create_child_cfg(), create_lease_query(), dhcp_socket_create(), do_args(), get_dns_server(), host_create_from_range(), host_create_from_subnet(), ike_cfg_get_family(), initiate_connection(), join_group(), load_addrs(), load_entries(), load_pools(), load_tester_config_create(), METHOD(), open_socket(), parse_attributes(), query(), run_echo_client(), scep_http_request(), start_echo_server(), START_TEST(), and verify_address().
 {
     return host_create_from_string_and_family(string, AF_UNSPEC, port);
 }
host_t* host_create_from_string_and_family (char * string, int family, u_int16_t port)
Same as host_create_from_string(), but with the option to enforce a family.
Parameters
string string of an address
family address family, or AF_UNSPEC
port port number
Returns
host_t, NULL if string not an address.
Definition at line 349 of file host.c.
References addr, host_create_any_port(), host_create_from_sockaddr(), inet_pton(), memset, and streq().
Referenced by host_create_from_dns(), host_create_from_range(), host_create_from_string(), test_create_from_string_and_family_addr(), and test_create_from_string_and_family_any().
 {
     union {
         struct sockaddr_in v4;
         struct sockaddr_in6 v6;
     } addr;
     if (!string)
     {
         return NULL;
     }
     if (streq(string, "%any"))
     {
         return host_create_any_port(family ? family : AF_INET, port);
     }
     if (family == AF_UNSPEC || family == AF_INET)
     {
         if (streq(string, "%any4") || streq(string, "0.0.0.0"))
         {
             return host_create_any_port(AF_INET, port);
         }
     }
     if (family == AF_UNSPEC || family == AF_INET6)
     {
         if (streq(string, "%any6") || streq(string, "::"))
         {
             return host_create_any_port(AF_INET6, port);
         }
     }
     switch (family)
     {
         case AF_UNSPEC:
             if (strchr(string, '.'))
             {
                 goto af_inet;
             }
             /* FALL */
         case AF_INET6:
             memset(&addr.v6, 0, sizeof(addr.v6));
             if (inet_pton(AF_INET6, string, &addr.v6.sin6_addr) != 1)
             {
                 return NULL;
             }
             addr.v6.sin6_port = htons(port);
             addr.v6.sin6_family = AF_INET6;
             return host_create_from_sockaddr((sockaddr_t*)&addr);
         case AF_INET:
             if (strchr(string, ':'))
             {   /* do not try to convert v6 addresses for v4 family */
                 return NULL;
             }
         af_inet:
             memset(&addr.v4, 0, sizeof(addr.v4));
             if (inet_pton(AF_INET, string, &addr.v4.sin_addr) != 1)
             {
                 return NULL;
             }
             addr.v4.sin_port = htons(port);
             addr.v4.sin_family = AF_INET;
             return host_create_from_sockaddr((sockaddr_t*)&addr);
         default:
             return NULL;
     }
 }
host_t* host_create_from_subnet (char * string, int * bits)
Create a host from a CIDR subnet definition (1.2.3.0/24), return bits.
Parameters
string string to parse
bits gets the number of network bits in CIDR notation
Returns
network start address, NULL on error
Definition at line 571 of file host.c.
References host_t::get_family, host_create_from_string(), net, and string.
Referenced by build_peer_cfg(), CALLBACK(), iface_add_addr(), iface_del_addr(), load_addrs(), START_TEST(), and traffic_selector_create_from_cidr().
 {
     char *pos, buf[64];
     host_t *net;
     pos = strchr(string, '/');
     if (pos)
     {
         if (pos - string >= sizeof(buf))
         {
             return NULL;
         }
         strncpy(buf, string, pos - string);
         buf[pos - string] = '\0';
         *bits = atoi(pos + 1);
         return host_create_from_string(buf, 0);
     }
     net = host_create_from_string(string, 0);
     if (net)
     {
         if (net->get_family(net) == AF_INET)
         {
             *bits = 32;
         }
         else
         {
             *bits = 128;
         }
     }
     return net;
 }
host_t* host_create_netmask (int family, int netbits)
Create a netmask host having the first netbits bits set.
Parameters
family family of the netmask host
netbits number of leading bits set in the host
Returns
netmask host
Definition at line 606 of file host.c.
References bits, bytes, family, host_create_empty(), if(), len, memset, and update_sa_len().
Referenced by add_rt_mask(), append_ts(), START_TEST(), and test_create_netmask().
 {
     private_host_t *this;
     int bits, bytes, len = 0;
     char *target;
     switch (family)
     {
         case AF_INET:
             if (netbits < 0 || netbits > 32)
             {
                 return NULL;
             }
             this = host_create_empty();
             this->socklen = sizeof(struct sockaddr_in);
             target = (char*)&this->address4.sin_addr;
             len = 4;
             break;
         case AF_INET6:
             if (netbits < 0 || netbits > 128)
             {
                 return NULL;
             }
             this = host_create_empty();
             this->socklen = sizeof(struct sockaddr_in6);
             target = (char*)&this->address6.sin6_addr;
             len = 16;
             break;
         default:
             return NULL;
     }
     memset(&this->address_max, 0, sizeof(struct sockaddr_storage));
     this->address.sa_family = family;
     update_sa_len(this);
     bytes = netbits / 8;
     bits = 8 - (netbits & 0x07);
     memset(target, 0xff, bytes);
     if (bytes < len)
     {
         memset(target + bytes, 0x00, len - bytes);
         target[bytes] = (u_int8_t)(0xff << bits);
     }
     return &this->public;
 }
int host_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook function for host_t.
Arguments are: host_t *host Use #-modifier to include port number Use +-modifier to force numeric representation (instead of e.g. any)
Described in header.
Definition at line 104 of file host.c.
References printf_hook_spec_t::hash, inet_ntop(), len, printf_hook_spec_t::minus, printf_hook_spec_t::plus, port, print_in_hook(), snprintf, and printf_hook_spec_t::width.
Referenced by library_init().
 {
     private_host_t *this = *((private_host_t**)(args[0]));
     char buffer[INET6_ADDRSTRLEN + 16];
     if (this == NULL)
     {
         snprintf(buffer, sizeof(buffer), "(null)");
     }
     else if (is_anyaddr(this) && !spec->plus && !spec->hash)
     {
         snprintf(buffer, sizeof(buffer), "%%any%s",
                  this->address.sa_family == AF_INET6 ? "6" : "");
     }
     else
     {
         void *address;
         u_int16_t port;
         int len;
         address = &this->address6.sin6_addr;
         port = this->address6.sin6_port;
         switch (this->address.sa_family)
         {
             case AF_INET:
                 address = &this->address4.sin_addr;
                 port = this->address4.sin_port;
                 /* fall */
             case AF_INET6:
                 if (inet_ntop(this->address.sa_family, address,
                               buffer, sizeof(buffer)) == NULL)
                 {
                     snprintf(buffer, sizeof(buffer),
                              "(address conversion failed)");
                 }
                 else if (spec->hash)
                 {
                     len = strlen(buffer);
                     snprintf(buffer + len, sizeof(buffer) - len,
                              "[%d]", ntohs(port));
                 }
                 break;
             default:
                 snprintf(buffer, sizeof(buffer), "(family not supported)");
                 break;
         }
     }
     if (spec->minus)
     {
         return print_in_hook(data, "%-*s", spec->width, buffer);
     }
     return print_in_hook(data, "%*s", spec->width, buffer);
 }