strongSwan: ha_kernel.c File Reference
ha_kernel.c File Reference
#include "ha_kernel.h"
#include <sys/utsname.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
Classes
struct private_ha_kernel_t
Macros
#define CLUSTERIP_DIR "/proc/net/ipt_CLUSTERIP"
#define jhash_rot(x, k) (((x)<<(k)) | ((x)>>(32-(k))))
Typedefs
typedef u_int32_t u32
typedef u_int8_t u8
typedef struct private_ha_kernel_t private_ha_kernel_t
Enumerations
enum jhash_version_t { JHASH_LOOKUP2, JHASH_LOOKUP3, JHASH_LOOKUP3_1 }
Functions
static jhash_version_t get_jhash_version ()
static u_int32_t jhash (jhash_version_t version, u_int32_t a, u_int32_t b)
static u_int hash2segment (private_ha_kernel_t *this, u_int64_t hash)
static u_int32_t host2int (host_t *host)
METHOD (ha_kernel_t, get_segment, u_int, private_ha_kernel_t *this, host_t *host)
METHOD (ha_kernel_t, get_segment_spi, u_int, private_ha_kernel_t *this, host_t *host, u_int32_t spi)
METHOD (ha_kernel_t, get_segment_int, u_int, private_ha_kernel_t *this, int n)
static void enable_disable (private_ha_kernel_t *this, u_int segment, char *file, bool enable)
static segment_mask_t get_active (private_ha_kernel_t *this, char *file)
METHOD (ha_kernel_t, activate, void, private_ha_kernel_t *this, u_int segment)
METHOD (ha_kernel_t, deactivate, void, private_ha_kernel_t *this, u_int segment)
static void disable_all (private_ha_kernel_t *this)
METHOD (ha_kernel_t, destroy, void, private_ha_kernel_t *this)
ha_kernel_t * ha_kernel_create (u_int count)
Macro Definition Documentation
#define CLUSTERIP_DIR "/proc/net/ipt_CLUSTERIP"
Definition at line 29 of file ha_kernel.c.
Referenced by disable_all(), and METHOD().
#define jhash_rot (x, k) (((x)<<(k)) | ((x)>>(32-(k))))
Rotate 32 bit word x by k bits
Definition at line 113 of file ha_kernel.c.
Referenced by jhash().
Typedef Documentation
typedef struct private_ha_kernel_t private_ha_kernel_t
Definition at line 43 of file ha_kernel.c.
typedef u_int32_t u32
Definition at line 18 of file ha_kernel.c.
typedef u_int8_t u8
Definition at line 19 of file ha_kernel.c.
Enumeration Type Documentation
enum jhash_version_t
Versions of jhash used in the Linux kernel
Enumerator
JHASH_LOOKUP2
JHASH_LOOKUP3
JHASH_LOOKUP3_1
Definition at line 34 of file ha_kernel.c.
              {
     /* old variant, http://burtleburtle.net/bob/c/lookup2.c */
     JHASH_LOOKUP2,
     /* new variant, http://burtleburtle.net/bob/c/lookup3.c, since 2.6.37 */
     JHASH_LOOKUP3,
     /* variant with different init values, since 4.1 */
     JHASH_LOOKUP3_1,
 } jhash_version_t;
Function Documentation
static void disable_all (private_ha_kernel_t * this) static
Disable all not-yet disabled segments on all clusterip addresses
Definition at line 324 of file ha_kernel.c.
References active, library_t::caps, CLUSTERIP_DIR, count, DBG1, DBG_CFG, enumerator_t::destroy, enable_disable(), enumerator_t::enumerate, enumerator_create_directory(), FALSE, get_active(), capabilities_t::get_gid, capabilities_t::get_uid, lib, SEGMENTS_BIT, and strerror.
Referenced by ha_kernel_create().
 {
     enumerator_t *enumerator;
     segment_mask_t active;
     char *file;
     int i;
     enumerator = enumerator_create_directory(CLUSTERIP_DIR);
     if (enumerator)
     {
         while (enumerator->enumerate(enumerator, NULL, &file, NULL))
         {
             if (chown(file, lib->caps->get_uid(lib->caps),
                       lib->caps->get_gid(lib->caps)) != 0)
             {
                 DBG1(DBG_CFG, "changing ClusterIP permissions failed: %s",
                      strerror(errno));
             }
             active = get_active(this, file);
             for (i = 1; i <= this->count; i++)
             {
                 if (active & SEGMENTS_BIT(i))
                 {
                     enable_disable(this, i, file, FALSE);
                 }
             }
         }
         enumerator->destroy(enumerator);
     }
 }
static void enable_disable (private_ha_kernel_t * this, u_int segment, char * file, bool enable) static
Activate/Deactivate a segment for a given clusterip file
Definition at line 219 of file ha_kernel.c.
References close, cmd, DBG1, DBG_CFG, snprintf, strerror, and write.
Referenced by disable_all(), and METHOD().
 {
     char cmd[8];
     int fd;
     snprintf(cmd, sizeof(cmd), "%c%d\n", enable ? '+' : '-', segment);
     fd = open(file, O_WRONLY);
     if (fd == -1)
     {
         DBG1(DBG_CFG, "opening CLUSTERIP file '%s' failed: %s",
              file, strerror(errno));
         return;
     }
     if (write(fd, cmd, strlen(cmd)) == -1)
     {
         DBG1(DBG_CFG, "writing to CLUSTERIP file '%s' failed: %s",
              file, strerror(errno));
     }
     close(fd);
 }
static segment_mask_t get_active (private_ha_kernel_t * this, char * file) static
Get the currenlty active segments in the kernel for a clusterip file
Definition at line 245 of file ha_kernel.c.
References close, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), len, mask, read, segment, SEGMENTS_BIT, and strerror.
Referenced by disable_all().
 {
     char buf[256];
     segment_mask_t mask = 0;
     ssize_t len;
     int fd;
     fd = open(file, O_RDONLY);
     if (fd == -1)
     {
         DBG1(DBG_CFG, "opening CLUSTERIP file '%s' failed: %s",
              file, strerror(errno));
         return 0;
     }
     len = read(fd, buf, sizeof(buf)-1);
     close(fd);
     if (len == -1)
     {
         DBG1(DBG_CFG, "reading from CLUSTERIP file '%s' failed: %s",
              file, strerror(errno));
     }
     else
     {
         enumerator_t *enumerator;
         u_int segment;
         char *token;
         buf[len] = '\0';
         enumerator = enumerator_create_token(buf, ",", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             segment = atoi(token);
             if (segment)
             {
                 mask |= SEGMENTS_BIT(segment);
             }
         }
         enumerator->destroy(enumerator);
     }
     return mask;
 }
static jhash_version_t get_jhash_version () static
Get the jhash version based on the uname().release
Definition at line 69 of file ha_kernel.c.
References a, b, c, DBG1, DBG_CFG, JHASH_LOOKUP2, JHASH_LOOKUP3, and JHASH_LOOKUP3_1.
Referenced by ha_kernel_create().
 {
     struct utsname utsname;
     int a, b, c;
     if (uname(&utsname) == 0)
     {
         switch (sscanf(utsname.release, "%d.%d.%d", &a, &b, &c))
         {
             case 3:
                 if (a == 2 && b == 6)
                 {
                     if (c < 37)
                     {
                         DBG1(DBG_CFG, "detected Linux %d.%d.%d, using old "
                              "jhash", a, b, c);
                         return JHASH_LOOKUP2;
                     }
                     DBG1(DBG_CFG, "detected Linux %d.%d.%d, using new "
                          "jhash", a, b, c);
                     return JHASH_LOOKUP3;
                 }
                 /* FALL */
             case 2:
                 if (a < 4 || (a == 4 && b == 0))
                 {
                     DBG1(DBG_CFG, "detected Linux %d.%d, using new jhash",
                          a, b);
                     return JHASH_LOOKUP3;
                 }
                 DBG1(DBG_CFG, "detected Linux %d.%d, using new jhash with "
                      "updated init values", a, b);
                 return JHASH_LOOKUP3_1;
             default:
                 break;
         }
     }
     DBG1(DBG_CFG, "detecting Linux version failed, using new jhash");
     return JHASH_LOOKUP3;
 }
static u_int hash2segment (private_ha_kernel_t * this, u_int64_t hash) static
Segmentate a calculated hash
Definition at line 165 of file ha_kernel.c.
References count.
Referenced by METHOD().
 {
     return ((hash * this->count) >> 32) + 1;
 }
static u_int32_t host2int (host_t * host) static
Get a host as an integer for hashing
Definition at line 173 of file ha_kernel.c.
References host_t::get_address, host_t::get_family, and chunk_t::ptr.
Referenced by METHOD().
 {
     if (host->get_family(host) == AF_INET)
     {
         return *(u_int32_t*)host->get_address(host).ptr;
     }
     return 0;
 }
static u_int32_t jhash (jhash_version_t version, u_int32_t a, u_int32_t b) static
jhash algorithm of two words, as used in kernel (using 0 as initval)
Definition at line 118 of file ha_kernel.c.
References a, b, c, JHASH_LOOKUP2, JHASH_LOOKUP3, JHASH_LOOKUP3_1, and jhash_rot.
Referenced by METHOD().
 {
     u_int32_t c = 0;
     switch (version)
     {
         case JHASH_LOOKUP2:
             a += 0x9e3779b9;
             b += 0x9e3779b9;
             a -= b; a -= c; a ^= (c >> 13);
             b -= c; b -= a; b ^= (a <<  8);
             c -= a; c -= b; c ^= (b >> 13);
             a -= b; a -= c; a ^= (c >> 12);
             b -= c; b -= a; b ^= (a << 16);
             c -= a; c -= b; c ^= (b >>  5);
             a -= b; a -= c; a ^= (c >>  3);
             b -= c; b -= a; b ^= (a << 10);
             c -= a; c -= b; c ^= (b >> 15);
             break;
         case JHASH_LOOKUP3_1:
             /* changed with 4.1: # of 32-bit words shifted by 2 and c is
              * initialized. we only use the two word variant with SPIs, so it's
              * unlikely that b is 0 in that case */
             c += ((b ? 2 : 1) << 2) + 0xdeadbeef;
             a += ((b ? 2 : 1) << 2);
             b += ((b ? 2 : 1) << 2);
             /* FALL */
         case JHASH_LOOKUP3:
             a += 0xdeadbeef;
             b += 0xdeadbeef;
             c ^= b; c -= jhash_rot(b, 14);
             a ^= c; a -= jhash_rot(c, 11);
             b ^= a; b -= jhash_rot(a, 25);
             c ^= b; c -= jhash_rot(b, 16);
             a ^= c; a -= jhash_rot(c,  4);
             b ^= a; b -= jhash_rot(a, 14);
             c ^= b; c -= jhash_rot(b, 24);
             break;
     }
     return c;
 }
METHOD (ha_kernel_t , get_segment , u_int , private_ha_kernel_t * this, host_t * host)
Definition at line 182 of file ha_kernel.c.
References addr, hash, hash2segment(), host2int(), jhash(), and version.
 {
     unsigned long hash;
     u_int32_t addr;
     addr = host2int(host);
     hash = jhash(this->version, ntohl(addr), 0);
     return hash2segment(this, hash);
 }
METHOD (ha_kernel_t , get_segment_spi , u_int , private_ha_kernel_t * this, host_t * host, u_int32_t spi)
Definition at line 194 of file ha_kernel.c.
References addr, hash, hash2segment(), host2int(), jhash(), and version.
 {
     unsigned long hash;
     u_int32_t addr;
     addr = host2int(host);
     hash = jhash(this->version, ntohl(addr), ntohl(spi));
     return hash2segment(this, hash);
 }
METHOD (ha_kernel_t , get_segment_int , u_int , private_ha_kernel_t * this, int n)
Definition at line 206 of file ha_kernel.c.
References hash, hash2segment(), jhash(), and version.
 {
     unsigned long hash;
     hash = jhash(this->version, ntohl(n), 0);
     return hash2segment(this, hash);
 }
METHOD (ha_kernel_t , activate , void , private_ha_kernel_t * this, u_int segment)
Definition at line 287 of file ha_kernel.c.
References CLUSTERIP_DIR, enumerator_t::destroy, enable_disable(), enumerator_t::enumerate, enumerator_create_directory(), and TRUE.
 {
     enumerator_t *enumerator;
     char *file;
     enumerator = enumerator_create_directory(CLUSTERIP_DIR);
     if (enumerator)
     {
         while (enumerator->enumerate(enumerator, NULL, &file, NULL))
         {
             enable_disable(this, segment, file, TRUE);
         }
         enumerator->destroy(enumerator);
     }
 }
METHOD (ha_kernel_t , deactivate , void , private_ha_kernel_t * this, u_int segment)
Definition at line 304 of file ha_kernel.c.
References CLUSTERIP_DIR, enumerator_t::destroy, enable_disable(), enumerator_t::enumerate, enumerator_create_directory(), and FALSE.
 {
     enumerator_t *enumerator;
     char *file;
     enumerator = enumerator_create_directory(CLUSTERIP_DIR);
     if (enumerator)
     {
         while (enumerator->enumerate(enumerator, NULL, &file, NULL))
         {
             enable_disable(this, segment, file, FALSE);
         }
         enumerator->destroy(enumerator);
     }
 }
METHOD (ha_kernel_t , destroy , void , private_ha_kernel_t * this)
Definition at line 355 of file ha_kernel.c.
References free().
 {
     free(this);
 }