strongSwan: test_identification.c File Reference
test_identification.c File Reference
#include "test_suite.h"
#include <utils/identification.h>
Functions
START_TEST (test_from_encoding)
END_TEST START_TEST (test_from_data)
END_TEST START_TEST (test_from_sockaddr)
START_TEST (test_from_string)
static END_TEST void string_equals (char *a_str, char *b_str)
static void string_equals_id (char *a_str, identification_t *b)
START_TEST (test_printf_hook)
END_TEST START_TEST (test_printf_hook_width)
static END_TEST bool id_equals (identification_t *a, char *b_str)
START_TEST (test_equals)
END_TEST START_TEST (test_equals_any)
END_TEST START_TEST (test_equals_binary)
END_TEST START_TEST (test_equals_fqdn)
END_TEST START_TEST (test_equals_empty)
static END_TEST bool id_matches (identification_t *a, char *b_str, id_match_t expected)
START_TEST (test_matches)
END_TEST START_TEST (test_matches_any)
END_TEST START_TEST (test_matches_binary)
END_TEST START_TEST (test_matches_string)
END_TEST START_TEST (test_matches_empty)
static END_TEST bool id_matches_rev (identification_t *a, char *b_str, id_match_t expected)
START_TEST (test_matches_empty_reverse)
static END_TEST bool id_hash_equals (char *str, char *b_str)
START_TEST (test_hash)
END_TEST START_TEST (test_hash_any)
END_TEST START_TEST (test_hash_dn)
END_TEST START_TEST (test_hash_inc)
END_TEST START_TEST (test_parts)
static END_TEST bool id_contains_wildcards (char *string)
START_TEST (test_contains_wildcards)
END_TEST START_TEST (test_clone)
END_TEST Suite * identification_suite_create ()
Variables
struct {
char * id
id_type_t type
struct {
enum { ENC_CHUNK, ENC_STRING, ENC_SIMPLE }
enum { ... } :: type
union {
chunk_t c
char * s
} data
} result
} string_data []
Function Documentation
static END_TEST bool id_contains_wildcards (char * string) static
Definition at line 857 of file test_identification.c.
References id, and identification_create_from_string().
Referenced by START_TEST().
 {
     identification_t *id;
     bool contains;
     id = identification_create_from_string(string);
     contains = id->contains_wildcards(id);
     id->destroy(id);
     return contains;
 }
static END_TEST bool id_equals (identification_t * a, char * b_str) static
Definition at line 366 of file test_identification.c.
References b, ck_assert_int_eq, identification_t::destroy, equals(), identification_t::equals, and identification_create_from_string().
Referenced by START_TEST().
 {
     identification_t *b;
     bool equals;
     b = identification_create_from_string(b_str);
     equals = a->equals(a, b);
     ck_assert_int_eq(equals, b->equals(b, a));
     b->destroy(b);
     return equals;
 }
static END_TEST bool id_hash_equals (char * str, char * b_str) static
Definition at line 734 of file test_identification.c.
References a, b, identification_t::destroy, FALSE, identification_t::hash, and identification_create_from_string().
Referenced by START_TEST().
 {
     identification_t *a, *b;
     bool success = FALSE;
     a = identification_create_from_string(str);
     b = identification_create_from_string(b_str ?: str);
     success = a->hash(a, 0) == b->hash(b, 0);
     a->destroy(a);
     b->destroy(b);
     return success;
 }
static END_TEST bool id_matches (identification_t * a, char * b_str, id_match_t expected) static
Definition at line 535 of file test_identification.c.
References b, identification_t::destroy, expected, identification_create_from_string(), match(), and identification_t::matches.
Referenced by START_TEST().
 {
     identification_t *b;
     id_match_t match;
     b = identification_create_from_string(b_str);
     match = a->matches(a, b);
     b->destroy(b);
     return match == expected;
 }
static END_TEST bool id_matches_rev (identification_t * a, char * b_str, id_match_t expected) static
Definition at line 676 of file test_identification.c.
References b, identification_t::destroy, expected, identification_create_from_string(), match(), and identification_t::matches.
Referenced by START_TEST().
 {
     identification_t *b;
     id_match_t match;
     b = identification_create_from_string(b_str);
     match = b->matches(b, a);
     b->destroy(b);
     return match == expected;
 }
END_TEST Suite* identification_suite_create ()
Definition at line 901 of file test_identification.c.
References countof, ID_ANY, ID_KEY_ID, s, string_data, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, tcase_add_test, tcase_create, and test_clone().
 {
     Suite *s;
     TCase *tc;
     s = suite_create("identification");
     tc = tcase_create("create");
     tcase_add_test(tc, test_from_encoding);
     tcase_add_test(tc, test_from_data);
     tcase_add_test(tc, test_from_sockaddr);
     tcase_add_loop_test(tc, test_from_string, 0, countof(string_data));
     suite_add_tcase(s, tc);
     tc = tcase_create("printf_hook");
     tcase_add_test(tc, test_printf_hook);
     tcase_add_test(tc, test_printf_hook_width);
     suite_add_tcase(s, tc);
     tc = tcase_create("equals");
     tcase_add_test(tc, test_equals);
     tcase_add_test(tc, test_equals_any);
     tcase_add_test(tc, test_equals_binary);
     tcase_add_test(tc, test_equals_fqdn);
     tcase_add_loop_test(tc, test_equals_empty, ID_ANY, ID_KEY_ID + 1);
     suite_add_tcase(s, tc);
     tc = tcase_create("matches");
     tcase_add_test(tc, test_matches);
     tcase_add_test(tc, test_matches_any);
     tcase_add_test(tc, test_matches_binary);
     tcase_add_test(tc, test_matches_string);
     tcase_add_loop_test(tc, test_matches_empty, ID_ANY, ID_KEY_ID + 1);
     tcase_add_loop_test(tc, test_matches_empty_reverse, ID_ANY, ID_KEY_ID + 1);
     suite_add_tcase(s, tc);
     tc = tcase_create("hash");
     tcase_add_test(tc, test_hash);
     tcase_add_test(tc, test_hash_any);
     tcase_add_test(tc, test_hash_dn);
     tcase_add_test(tc, test_hash_inc);
     suite_add_tcase(s, tc);
     tc = tcase_create("part enumeration");
     tcase_add_test(tc, test_parts);
     suite_add_tcase(s, tc);
     tc = tcase_create("wildcards");
     tcase_add_test(tc, test_contains_wildcards);
     suite_add_tcase(s, tc);
     tc = tcase_create("clone");
     tcase_add_test(tc, test_clone);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_from_encoding)
Definition at line 25 of file test_identification.c.
References a, chunk_equals(), chunk_from_str, ck_assert, identification_t::destroy, encoding, expected, identification_t::get_encoding, identification_t::get_type, ID_ANY, ID_RFC822_ADDR, identification_create_from_encoding(), and chunk_t::ptr.
 {
     identification_t *a;
     chunk_t expected, encoding;
     /* only ID_ANY is handled differently, for all other types the following
      * applies.  should we perhaps test that this is in fact the case? */
     expected = chunk_from_str("moon@strongswan.org");
     a = identification_create_from_encoding(ID_RFC822_ADDR, expected);
     ck_assert(ID_RFC822_ADDR == a->get_type(a));
     encoding = a->get_encoding(a);
     ck_assert(expected.ptr != encoding.ptr);
     ck_assert(chunk_equals(expected, encoding));
     a->destroy(a);
     a = identification_create_from_encoding(ID_ANY, expected);
     ck_assert(ID_ANY == a->get_type(a));
     encoding = a->get_encoding(a);
     ck_assert(encoding.ptr == NULL);
     ck_assert(encoding.len == 0);
     a->destroy(a);
 }
END_TEST START_TEST (test_from_data)
Definition at line 49 of file test_identification.c.
References a, chunk_equals(), chunk_from_chars, chunk_from_str, ck_assert, identification_t::destroy, encoding, expected, identification_t::get_encoding, identification_t::get_type, ID_DER_ASN1_DN, ID_RFC822_ADDR, identification_create_from_data(), and chunk_t::ptr.
 {
     identification_t *a;
     chunk_t expected, encoding;
     /* this uses the DN parser (C=CH) */
     expected = chunk_from_chars(0x30, 0x0d, 0x31, 0x0b, 0x30, 0x09, 0x06,
                                 0x03, 0x55, 0x04, 0x06, 0x13, 0x02, 0x43, 0x48);
     a = identification_create_from_data(expected);
     ck_assert(ID_DER_ASN1_DN == a->get_type(a));
     encoding = a->get_encoding(a);
     ck_assert(expected.ptr != encoding.ptr);
     ck_assert(chunk_equals(expected, encoding));
     a->destroy(a);
     /* everything else is handled by the string parser */
     expected = chunk_from_str("moon@strongswan.org");
     a = identification_create_from_data(expected);
     ck_assert(ID_RFC822_ADDR == a->get_type(a));
     encoding = a->get_encoding(a);
     ck_assert(expected.ptr != encoding.ptr);
     ck_assert(chunk_equals(expected, encoding));
     a->destroy(a);
 }
END_TEST START_TEST (test_from_sockaddr)
Definition at line 75 of file test_identification.c.
References a, chunk_equals(), chunk_from_chars, ck_assert, identification_t::destroy, encoding, expected, identification_t::get_encoding, identification_t::get_type, ID_ANY, ID_IPV4_ADDR, ID_IPV6_ADDR, identification_create_from_sockaddr(), memcpy, and chunk_t::ptr.
 {
     identification_t *a;
     chunk_t expected, encoding;
     struct sockaddr_in in = {
         .sin_family = AF_INET,
     };
     struct sockaddr_in6 in6 = {
         .sin6_family = AF_INET6,
     };
     expected = chunk_from_chars(0xc0, 0xa8, 0x01, 0x01);
     memcpy(&in.sin_addr, expected.ptr, sizeof(in.sin_addr));
     a = identification_create_from_sockaddr((sockaddr_t*)&in);
     ck_assert(ID_IPV4_ADDR == a->get_type(a));
     encoding = a->get_encoding(a);
     ck_assert(chunk_equals(expected, encoding));
     a->destroy(a);
     expected = chunk_from_chars(0xfe, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01);
     memcpy(&in6.sin6_addr, expected.ptr, sizeof(in6.sin6_addr));
     a = identification_create_from_sockaddr((sockaddr_t*)&in6);
     ck_assert(ID_IPV6_ADDR == a->get_type(a));
     encoding = a->get_encoding(a);
     ck_assert(chunk_equals(expected, encoding));
     a->destroy(a);
     in6.sin6_family = AF_UNSPEC;
     a = identification_create_from_sockaddr((sockaddr_t*)&in6);
     ck_assert(ID_ANY == a->get_type(a));
     a->destroy(a);
 }
START_TEST (test_from_string)
Definition at line 189 of file test_identification.c.
References a, chunk_empty, chunk_equals(), chunk_from_str, ck_assert, identification_t::destroy, encoding, expected, fail, fail_unless, identification_t::get_encoding, identification_t::get_type, id, id_type_names, identification_create_from_string(), chunk_t::ptr, result, and string_data.
 {
     identification_t *a;
     chunk_t encoding, expected = chunk_empty;
     char *id;
     id = string_data[_i].id;
     a = identification_create_from_string(id);
     fail_unless(a->get_type(a) == string_data[_i].type,
                 "type of id '%s' is %N, %N expected", id,
                 id_type_names, a->get_type(a),
                 id_type_names, string_data[_i].type);
     encoding = a->get_encoding(a);
     switch (string_data[_i].result.type)
     {
         case ENC_SIMPLE:
             expected = chunk_from_str(string_data[_i].id);
             break;
         case ENC_STRING:
             expected = chunk_from_str(string_data[_i].result.data.s);
             break;
         case ENC_CHUNK:
             expected = string_data[_i].result.data.c;
             break;
         default:
             fail("unexpected result type");
     }
     ck_assert(!id || (char*)encoding.ptr != id);
     if (expected.ptr)
     {
         fail_unless(chunk_equals(encoding, expected),
                     "parsing '%s' failed\nencoding %B\nexpected %B\n",
                     id, &encoding, &expected);
     }
     else
     {
         ck_assert(encoding.ptr == NULL);
         ck_assert(encoding.len == 0);
     }
     a->destroy(a);
 }
START_TEST (test_printf_hook)
Definition at line 258 of file test_identification.c.
References chunk_empty, chunk_from_chars, chunk_from_str, ID_DER_ASN1_DN, ID_DER_ASN1_GN, ID_IPV4_ADDR, ID_IPV6_ADDR, ID_KEY_ID, ID_RFC822_ADDR, identification_create_from_encoding(), string_equals(), and string_equals_id().
 {
     string_equals("(null)", NULL);
     string_equals("%any", "");
     string_equals("%any", "%any");
     string_equals("%any", "*");
     string_equals("192.168.1.1", "192.168.1.1");
     string_equals_id("(invalid ID_IPV4_ADDR)",
                 identification_create_from_encoding(ID_IPV4_ADDR, chunk_empty));
     string_equals("fec0::1", "fec0::1");
     string_equals("fec0::1", "fec0:0:0::1");
     string_equals_id("(invalid ID_IPV6_ADDR)",
                 identification_create_from_encoding(ID_IPV6_ADDR, chunk_empty));
     string_equals_id("(unknown ID type: 255)",
                 identification_create_from_encoding(255, chunk_empty));
     string_equals("moon@strongswan.org", "moon@strongswan.org");
     string_equals("MOON@STRONGSWAN.ORG", "MOON@STRONGSWAN.ORG");
     /* non-printable characters */
     string_equals_id("????@strongswan.org", identification_create_from_encoding(ID_RFC822_ADDR,
             chunk_from_chars(0xfa, 0xfb, 0xfc, 0xfd, 0x40, 0x73, 0x74, 0x72,
                              0x6f, 0x6e, 0x67, 0x73, 0x77, 0x61, 0x6e, 0x2e,
                              0x6f, 0x72, 0x67)));
     /* not a DN => ID_KEY_ID => no normalization */
     string_equals("C=CH, AsdF=asdf", "C=CH, AsdF=asdf");
     string_equals_id("moon@strongswan.org", identification_create_from_encoding(ID_KEY_ID,
             chunk_from_str("moon@strongswan.org")));
     /* non-printable characters */
     string_equals_id("de:ad:be:ef", identification_create_from_encoding(ID_KEY_ID,
             chunk_from_chars(0xde, 0xad, 0xbe, 0xef)));
     /* printable characters */
     string_equals_id("ABCDEFGHIJKLMNOPQRS",
         identification_create_from_encoding(ID_KEY_ID,
             chunk_from_chars(0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48,
                              0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f, 0x50,
                              0x51, 0x52, 0x53)));
     /* ABCDEFGHIJKLMNOPQRST is printable but has the length of a SHA1 hash */
     string_equals_id("41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54",
         identification_create_from_encoding(ID_KEY_ID,
             chunk_from_chars(0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48,
                              0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f, 0x50,
                              0x51, 0x52, 0x53, 0x54)));
     string_equals_id("", identification_create_from_encoding(ID_DER_ASN1_DN, chunk_empty));
     string_equals("C=", "C=");
     string_equals("C=", "C=,");
     string_equals("C=", "C=, ");
     string_equals("C=", "C= , ");
     string_equals("C=, O=strongSwan", "C=, O=strongSwan");
     string_equals("C=CH, O=", "C=CH, O=");
     string_equals("C=CH, O=strongSwan, CN=strongswan.org",
                   "C=CH, O=strongSwan, CN=strongswan.org");
     string_equals("CN=strongswan.org, O=strongSwan, C=CH",
                   "cn=strongswan.org, o=strongSwan, c=CH");
     string_equals("C=CH, O=strongSwan, CN=strongswan.org",
                   "C=CH,O=strongSwan,CN=strongswan.org");
     string_equals("C=CH, O=strongSwan, CN=strongswan.org",
                   "/C=CH/O=strongSwan/CN=strongswan.org");
     string_equals("CN=strongswan.org, O=strongSwan, C=CH",
                   "CN=strongswan.org,O=strongSwan,C=CH");
     string_equals("C=CH, E=moon@strongswan.org, CN=moon",
                   "C=CH, email=moon@strongswan.org, CN=moon");
     string_equals("C=CH, E=moon@strongswan.org, CN=moon",
                   "C=CH, emailAddress=moon@strongswan.org, CN=moon");
     /* C=CH, pseudonym=ANO (pseudonym is currently not recognized) */
     string_equals_id("C=CH, 55:04:41=ANO", identification_create_from_encoding(ID_DER_ASN1_DN,
         chunk_from_chars(0x30, 0x19, 0x31, 0x17, 0x30, 0x09, 0x06, 0x03, 0x55,
                          0x04, 0x06, 0x13, 0x02, 0x43, 0x48, 0x30, 0x0a, 0x06,
                          0x03, 0x55, 0x04, 0x41, 0x13, 0x03, 0x41, 0x4e, 0x4f)));
     /* C=CH, O=strongSwan (but instead of a 2nd OID -0x06- we got NULL -0x05) */
     string_equals_id("C=CH, (invalid ID_DER_ASN1_DN)", identification_create_from_encoding(ID_DER_ASN1_DN,
         chunk_from_chars(0x30, 0x20, 0x31, 0x1e, 0x30, 0x09, 0x06, 0x03, 0x55,
                          0x04, 0x06, 0x13, 0x02, 0x43, 0x48, 0x30, 0x11, 0x05,
                          0x03, 0x55, 0x04, 0x0a, 0x13, 0x0a, 0x73, 0x74, 0x72,
                          0x6f, 0x6e, 0x67, 0x53, 0x77, 0x61, 0x6e)));
     /* moon@strongswan.org as GN */
     string_equals_id("(ASN.1 general name)", identification_create_from_encoding(ID_DER_ASN1_GN,
         chunk_from_chars(0x81, 0x14, 0x6d, 0x6f, 0x6f, 0x6e, 0x40, 0x73, 0x74,
                          0x72, 0x6f, 0x6e, 0x67, 0x73, 0x77, 0x61, 0x6e, 0x2e,
                          0x6f, 0x72, 0x67)));
 }
END_TEST START_TEST (test_printf_hook_width)
Definition at line 346 of file test_identification.c.
References a, ck_assert_str_eq, DESTROY_IF, identification_create_from_string(), and snprintf.
 {
     identification_t *a;
     char buf[128];
     a = identification_create_from_string("moon@strongswan.org");
     snprintf(buf, sizeof(buf), "%25Y", a);
     ck_assert_str_eq("      moon@strongswan.org", buf);
     snprintf(buf, sizeof(buf), "%-*Y", 25, a);
     ck_assert_str_eq("moon@strongswan.org      ", buf);
     snprintf(buf, sizeof(buf), "%5Y", a);
     ck_assert_str_eq("moon@strongswan.org", buf);
     DESTROY_IF(a);
 }
START_TEST (test_equals)
Definition at line 378 of file test_identification.c.
References a, chunk_clone, ck_assert, identification_t::destroy, encoding, free(), identification_t::get_encoding, ID_DER_ASN1_DN, id_equals(), identification_create_from_encoding(), identification_create_from_string(), chunk_t::len, printf, and chunk_t::ptr.
 {
     identification_t *a;
     chunk_t encoding, fuzzed;
     int i;
     /* this test also tests identification_create_from_string with DNs */
     a = identification_create_from_string(
                              "C=CH, E=moon@strongswan.org, CN=moon");
     ck_assert(id_equals(a, "C=CH, E=moon@strongswan.org, CN=moon"));
     ck_assert(id_equals(a, "C==CH , E==moon@strongswan.org , CN==moon"));
     ck_assert(id_equals(a, "  C=CH, E=moon@strongswan.org, CN=moon  "));
     ck_assert(id_equals(a, "C=ch, E=moon@STRONGSWAN.ORG, CN=Moon"));
     ck_assert(id_equals(a, "/C=CH/E=moon@strongswan.org/CN=moon"));
     ck_assert(id_equals(a, " / C=CH / E=moon@strongswan.org / CN=moon"));
     ck_assert(!id_equals(a, "C=CH/E=moon@strongswan.org/CN=moon"));
     ck_assert(!id_equals(a, "C=CH/E=moon@strongswan.org,CN=moon"));
     ck_assert(!id_equals(a, "C=CH E=moon@strongswan.org CN=moon"));
     ck_assert(!id_equals(a, "C=CN, E=moon@strongswan.org, CN=moon"));
     ck_assert(!id_equals(a, "E=moon@strongswan.org, C=CH, CN=moon"));
     ck_assert(!id_equals(a, "E=moon@strongswan.org, C=CH, CN=moon"));
     encoding = chunk_clone(a->get_encoding(a));
     a->destroy(a);
     /* simple fuzzing, increment each byte of encoding */
     for (i = 0; i < encoding.len; i++)
     {
         if (i == 11 || i == 30 || i == 60)
         {   /* skip ASN.1 type fields, as equals() handles them graceful */
             continue;
         }
         fuzzed = chunk_clone(encoding);
         fuzzed.ptr[i]++;
         a = identification_create_from_encoding(ID_DER_ASN1_DN, fuzzed);
         if (id_equals(a, "C=CH, E=moon@strongswan.org, CN=moon"))
         {
             printf("%d %B\n%B\n", i, &fuzzed, &encoding);
         }
         ck_assert(!id_equals(a, "C=CH, E=moon@strongswan.org, CN=moon"));
         a->destroy(a);
         free(fuzzed.ptr);
     }
     /* and decrement each byte of encoding */
     for (i = 0; i < encoding.len; i++)
     {
         if (i == 11 || i == 30 || i == 60)
         {
             continue;
         }
         fuzzed = chunk_clone(encoding);
         fuzzed.ptr[i]--;
         a = identification_create_from_encoding(ID_DER_ASN1_DN, fuzzed);
         ck_assert(!id_equals(a, "C=CH, E=moon@strongswan.org, CN=moon"));
         a->destroy(a);
         free(fuzzed.ptr);
     }
     free(encoding.ptr);
 }
END_TEST START_TEST (test_equals_any)
Definition at line 442 of file test_identification.c.
References a, b, chunk_empty, ck_assert, identification_t::destroy, identification_t::equals, ID_ANY, identification_create_from_encoding(), and identification_create_from_string().
 {
     identification_t *a, *b;
     a = identification_create_from_string("%any");
     b = identification_create_from_encoding(ID_ANY, chunk_empty);
     ck_assert(a->equals(a, b));
     ck_assert(b->equals(b, a));
     b->destroy(b);
     b = identification_create_from_string("C=CH, O=strongSwan, CN=strongswan.org");
     ck_assert(!a->equals(a, b));
     ck_assert(!b->equals(b, a));
     a->destroy(a);
     b->destroy(b);
 }
END_TEST START_TEST (test_equals_binary)
Definition at line 460 of file test_identification.c.
References a, b, chunk_from_str, ck_assert, identification_t::destroy, encoding, identification_t::equals, identification_t::get_type, ID_KEY_ID, identification_create_from_encoding(), and identification_create_from_string().
 {
     identification_t *a, *b;
     chunk_t encoding;
     encoding = chunk_from_str("foobar=");
     /* strings containing = are parsed as KEY_ID if they aren't valid ASN.1 DNs */
     a = identification_create_from_string("foobar=");
     ck_assert(a->get_type(a) == ID_KEY_ID);
     b = identification_create_from_encoding(ID_KEY_ID, encoding);
     ck_assert(a->equals(a, b));
     a->destroy(a);
     b->destroy(b);
 }
END_TEST START_TEST (test_equals_fqdn)
Definition at line 476 of file test_identification.c.
References a, ck_assert, identification_t::destroy, id_equals(), and identification_create_from_string().
 {
     identification_t *a;
     a = identification_create_from_string("ipsec.strongswan.org");
     ck_assert(id_equals(a, "IPSEC.strongswan.org"));
     ck_assert(id_equals(a, "ipsec.strongSwan.org"));
     ck_assert(id_equals(a, "ipsec.strongSwan.ORG"));
     ck_assert(!id_equals(a, "strongswan.org"));
     a->destroy(a);
 }
END_TEST START_TEST (test_equals_empty)
Definition at line 489 of file test_identification.c.
References a, chunk_empty, ck_assert, identification_t::destroy, ID_ANY, ID_DER_ASN1_DN, ID_DER_ASN1_GN, id_equals(), ID_FQDN, ID_IPV4_ADDR, ID_IPV4_ADDR_RANGE, ID_IPV4_ADDR_SUBNET, ID_IPV6_ADDR, ID_IPV6_ADDR_RANGE, ID_IPV6_ADDR_SUBNET, ID_KEY_ID, ID_USER_FQDN, and identification_create_from_encoding().
 {
     identification_t *a;
     a = identification_create_from_encoding(_i, chunk_empty);
     switch (_i)
     {
         case ID_ANY:
             ck_assert(id_equals(a, "%any"));
             break;
         case ID_IPV4_ADDR:
             ck_assert(!id_equals(a, "192.168.1.1"));
             break;
         case ID_FQDN:
             ck_assert(!id_equals(a, "moon.strongswan.org"));
             break;
         case ID_USER_FQDN:
             ck_assert(!id_equals(a, "moon@strongswan.org"));
             break;
         case ID_IPV6_ADDR:
             ck_assert(!id_equals(a, "fec0::1"));
             break;
         case ID_DER_ASN1_DN:
             ck_assert(!id_equals(a, "C=CH, E=moon@strongswan.org, CN=moon"));
             break;
         case ID_KEY_ID:
             ck_assert(!id_equals(a, "@#12345678"));
             break;
         case ID_DER_ASN1_GN:
         case ID_IPV4_ADDR_SUBNET:
         case ID_IPV6_ADDR_SUBNET:
         case ID_IPV4_ADDR_RANGE:
         case ID_IPV6_ADDR_RANGE:
             /* currently not tested */
             break;
     }
     a->destroy(a);
 }
START_TEST (test_matches)
Definition at line 546 of file test_identification.c.
References a, ck_assert, identification_t::destroy, ID_MATCH_ANY, ID_MATCH_NONE, ID_MATCH_ONE_WILDCARD, ID_MATCH_PERFECT, id_matches(), and identification_create_from_string().
 {
     identification_t *a;
     a = identification_create_from_string("C=CH, E=moon@strongswan.org, CN=moon");
     ck_assert(id_matches(a, "C=CH, E=moon@strongswan.org, CN=moon", ID_MATCH_PERFECT));
     ck_assert(id_matches(a, "C=CH, E=*@strongswan.org, CN=moon", ID_MATCH_NONE));
     ck_assert(id_matches(a, "C=CH, E=*, CN=moon", ID_MATCH_ONE_WILDCARD));
     ck_assert(id_matches(a, "C=CH, E=*, CN=*", ID_MATCH_ONE_WILDCARD - 1));
     ck_assert(id_matches(a, "C=*, E=*, CN=*", ID_MATCH_ONE_WILDCARD - 2));
     ck_assert(id_matches(a, "C=*, E=*, CN=*, O=BADInc", ID_MATCH_NONE));
     ck_assert(id_matches(a, "C=*, E=*", ID_MATCH_NONE));
     ck_assert(id_matches(a, "C=*, E=a@b.c, CN=*", ID_MATCH_NONE));
     ck_assert(id_matches(a, "%any", ID_MATCH_ANY));
     a->destroy(a);
 }
END_TEST START_TEST (test_matches_any)
Definition at line 566 of file test_identification.c.
References a, ck_assert, identification_t::destroy, ID_MATCH_ANY, ID_MATCH_NONE, id_matches(), and identification_create_from_string().
 {
     identification_t *a;
     a = identification_create_from_string("%any");
     ck_assert(id_matches(a, "%any", ID_MATCH_ANY));
     ck_assert(id_matches(a, "", ID_MATCH_ANY));
     ck_assert(id_matches(a, "*", ID_MATCH_ANY));
     ck_assert(id_matches(a, "moon@strongswan.org", ID_MATCH_NONE));
     ck_assert(id_matches(a, "vpn.strongswan.org", ID_MATCH_NONE));
     a->destroy(a);
 }
END_TEST START_TEST (test_matches_binary)
Definition at line 581 of file test_identification.c.
References a, ck_assert, identification_t::destroy, identification_t::get_type, ID_KEY_ID, ID_MATCH_ANY, ID_MATCH_NONE, ID_MATCH_PERFECT, id_matches(), and identification_create_from_string().
 {
     identification_t *a;
     /* strings containing = are parsed as KEY_ID if they aren't valid ASN.1 DNs */
     a = identification_create_from_string("foo=bar");
     ck_assert(a->get_type(a) == ID_KEY_ID);
     ck_assert(id_matches(a, "%any", ID_MATCH_ANY));
     ck_assert(id_matches(a, "foo=bar", ID_MATCH_PERFECT));
     ck_assert(id_matches(a, "bar=foo", ID_MATCH_NONE));
     ck_assert(id_matches(a, "*=bar", ID_MATCH_NONE));
     ck_assert(id_matches(a, "foo=*", ID_MATCH_NONE));
     ck_assert(id_matches(a, "foo@bar", ID_MATCH_NONE));
     a->destroy(a);
 }
END_TEST START_TEST (test_matches_string)
Definition at line 598 of file test_identification.c.
References a, ck_assert, identification_t::destroy, ID_MATCH_ANY, ID_MATCH_NONE, ID_MATCH_ONE_WILDCARD, ID_MATCH_PERFECT, id_matches(), and identification_create_from_string().
 {
     identification_t *a;
     a = identification_create_from_string("moon@strongswan.org");
     ck_assert(id_matches(a, "moon@strongswan.org", ID_MATCH_PERFECT));
     ck_assert(id_matches(a, "*@strongswan.org", ID_MATCH_ONE_WILDCARD));
     ck_assert(id_matches(a, "*@*.org", ID_MATCH_NONE));
     ck_assert(id_matches(a, "*@*", ID_MATCH_NONE));
     /* the following two are parsed as ID_FQDN, so no match */
     ck_assert(id_matches(a, "*strongswan.org", ID_MATCH_NONE));
     ck_assert(id_matches(a, "*.org", ID_MATCH_NONE));
     ck_assert(id_matches(a, "moon@*", ID_MATCH_NONE));
     ck_assert(id_matches(a, "**", ID_MATCH_NONE));
     ck_assert(id_matches(a, "*", ID_MATCH_ANY));
     ck_assert(id_matches(a, "%any", ID_MATCH_ANY));
     a->destroy(a);
     a = identification_create_from_string("vpn.strongswan.org");
     ck_assert(id_matches(a, "vpn.strongswan.org", ID_MATCH_PERFECT));
     ck_assert(id_matches(a, "*.strongswan.org", ID_MATCH_ONE_WILDCARD));
     ck_assert(id_matches(a, "*strongswan.org", ID_MATCH_ONE_WILDCARD));
     ck_assert(id_matches(a, "*.org", ID_MATCH_ONE_WILDCARD));
     ck_assert(id_matches(a, "*.strongswan.*", ID_MATCH_NONE));
     ck_assert(id_matches(a, "*vpn.strongswan.org", ID_MATCH_NONE));
     ck_assert(id_matches(a, "vpn.strongswan.*", ID_MATCH_NONE));
     ck_assert(id_matches(a, "**", ID_MATCH_NONE));
     ck_assert(id_matches(a, "*", ID_MATCH_ANY));
     ck_assert(id_matches(a, "%any", ID_MATCH_ANY));
     a->destroy(a);
 }
END_TEST START_TEST (test_matches_empty)
Definition at line 633 of file test_identification.c.
References a, chunk_empty, ck_assert, identification_t::destroy, ID_ANY, ID_DER_ASN1_DN, ID_DER_ASN1_GN, ID_FQDN, ID_IPV4_ADDR, ID_IPV4_ADDR_RANGE, ID_IPV4_ADDR_SUBNET, ID_IPV6_ADDR, ID_IPV6_ADDR_RANGE, ID_IPV6_ADDR_SUBNET, ID_KEY_ID, ID_MATCH_ANY, ID_MATCH_NONE, id_matches(), ID_USER_FQDN, and identification_create_from_encoding().
 {
     identification_t *a;
     a = identification_create_from_encoding(_i, chunk_empty);
     switch (_i)
     {
         case ID_ANY:
             ck_assert(id_matches(a, "%any", ID_MATCH_ANY));
             break;
         case ID_IPV4_ADDR:
             ck_assert(id_matches(a, "192.168.1.1", ID_MATCH_NONE));
             break;
         case ID_FQDN:
             ck_assert(id_matches(a, "moon.strongswan.org", ID_MATCH_NONE));
             break;
         case ID_USER_FQDN:
             ck_assert(id_matches(a, "moon@strongswan.org", ID_MATCH_NONE));
             break;
         case ID_IPV6_ADDR:
             ck_assert(id_matches(a, "fec0::1", ID_MATCH_NONE));
             break;
         case ID_DER_ASN1_DN:
             ck_assert(id_matches(a, "C=CH, E=moon@strongswan.org, CN=moon",
                                  ID_MATCH_NONE));
             break;
         case ID_KEY_ID:
             ck_assert(id_matches(a, "@#12345678", ID_MATCH_NONE));
             break;
         case ID_DER_ASN1_GN:
         case ID_IPV4_ADDR_SUBNET:
         case ID_IPV6_ADDR_SUBNET:
         case ID_IPV4_ADDR_RANGE:
         case ID_IPV6_ADDR_RANGE:
             /* currently not tested */
             break;
     }
     a->destroy(a);
 }
START_TEST (test_matches_empty_reverse)
Definition at line 687 of file test_identification.c.
References a, chunk_empty, ck_assert, identification_t::destroy, ID_ANY, ID_DER_ASN1_DN, ID_DER_ASN1_GN, ID_FQDN, ID_IPV4_ADDR, ID_IPV4_ADDR_RANGE, ID_IPV4_ADDR_SUBNET, ID_IPV6_ADDR, ID_IPV6_ADDR_RANGE, ID_IPV6_ADDR_SUBNET, ID_KEY_ID, ID_MATCH_ANY, ID_MATCH_NONE, id_matches_rev(), ID_USER_FQDN, and identification_create_from_encoding().
 {
     identification_t *a;
     a = identification_create_from_encoding(_i, chunk_empty);
     switch (_i)
     {
         case ID_ANY:
             ck_assert(id_matches_rev(a, "%any", ID_MATCH_ANY));
             break;
         case ID_IPV4_ADDR:
             ck_assert(id_matches_rev(a, "192.168.1.1", ID_MATCH_NONE));
             break;
         case ID_FQDN:
             ck_assert(id_matches_rev(a, "moon.strongswan.org", ID_MATCH_NONE));
             break;
         case ID_USER_FQDN:
             ck_assert(id_matches_rev(a, "moon@strongswan.org", ID_MATCH_NONE));
             break;
         case ID_IPV6_ADDR:
             ck_assert(id_matches_rev(a, "fec0::1", ID_MATCH_NONE));
             break;
         case ID_DER_ASN1_DN:
             ck_assert(id_matches_rev(a, "C=CH, E=moon@strongswan.org, CN=moon",
                                      ID_MATCH_NONE));
             break;
         case ID_KEY_ID:
             ck_assert(id_matches_rev(a, "@#12345678", ID_MATCH_NONE));
             break;
         case ID_DER_ASN1_GN:
         case ID_IPV4_ADDR_SUBNET:
         case ID_IPV6_ADDR_SUBNET:
         case ID_IPV4_ADDR_RANGE:
         case ID_IPV6_ADDR_RANGE:
             /* currently not tested */
             break;
     }
     a->destroy(a);
 }
START_TEST (test_hash)
Definition at line 747 of file test_identification.c.
References ck_assert, and id_hash_equals().
 {
     ck_assert(id_hash_equals("moon@strongswan.org", NULL));
     ck_assert(id_hash_equals("vpn.strongswan.org", NULL));
     ck_assert(id_hash_equals("192.168.1.1", NULL));
     ck_assert(id_hash_equals("C=CH", NULL));
     ck_assert(!id_hash_equals("moon@strongswan.org", "sun@strongswan.org"));
     ck_assert(!id_hash_equals("vpn.strongswan.org", "*.strongswan.org"));
     ck_assert(!id_hash_equals("192.168.1.1", "192.168.1.2"));
     ck_assert(!id_hash_equals("C=CH", "C=DE"));
     ck_assert(!id_hash_equals("fqdn:strongswan.org", "keyid:strongswan.org"));
 }
END_TEST START_TEST (test_hash_any)
Definition at line 762 of file test_identification.c.
References ck_assert, and id_hash_equals().
 {
     ck_assert(id_hash_equals("%any", NULL));
     ck_assert(id_hash_equals("%any", "0.0.0.0"));
     ck_assert(id_hash_equals("%any", "*"));
     ck_assert(id_hash_equals("%any", ""));
     ck_assert(!id_hash_equals("%any", "any"));
 }
END_TEST START_TEST (test_hash_dn)
Definition at line 773 of file test_identification.c.
References a, b, chunk_from_chars, ck_assert, ck_assert_int_eq, identification_t::destroy, identification_t::equals, identification_t::hash, and identification_create_from_data().
 {
     identification_t *a, *b;
     /* same DN (C=CH, O=strongSwan), different RDN type (PRINTABLESTRING vs.
      * UTF8STRING) */
     a = identification_create_from_data(chunk_from_chars(
             0x30, 0x22, 0x31, 0x0b, 0x30, 0x09, 0x06, 0x03,
             0x55, 0x04, 0x06, 0x13, 0x02, 0x43, 0x48, 0x31,
             0x13, 0x30, 0x11, 0x06, 0x03, 0x55, 0x04, 0x0a,
             0x13, 0x0a, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67,
             0x53, 0x77, 0x61, 0x6e));
     b = identification_create_from_data(chunk_from_chars(
             0x30, 0x22, 0x31, 0x0b, 0x30, 0x09, 0x06, 0x03,
             0x55, 0x04, 0x06, 0x0c, 0x02, 0x43, 0x48, 0x31,
             0x13, 0x30, 0x11, 0x06, 0x03, 0x55, 0x04, 0x0a,
             0x0c, 0x0a, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67,
             0x53, 0x77, 0x61, 0x6e));
     ck_assert_int_eq(a->hash(a, 0), b->hash(b, 0));
     ck_assert(a->equals(a, b));
     a->destroy(a);
     b->destroy(b);
 }
END_TEST START_TEST (test_hash_inc)
Definition at line 798 of file test_identification.c.
References a, ck_assert, identification_t::destroy, identification_t::hash, and identification_create_from_string().
 {
     identification_t *a;
     a = identification_create_from_string("vpn.strongswan.org");
     ck_assert(a->hash(a, 0) != a->hash(a, 1));
     a->destroy(a);
     a = identification_create_from_string("C=CH, O=strongSwan");
     ck_assert(a->hash(a, 0) != a->hash(a, 1));
     a->destroy(a);
 }
END_TEST START_TEST (test_parts)
Definition at line 816 of file test_identification.c.
References chunk_create(), chunk_equals(), chunk_from_str, ck_assert, ck_assert_int_eq, data, enumerator_t::destroy, enumerator_t::enumerate, fail, id, ID_PART_RDN_C, ID_PART_RDN_CN, ID_PART_RDN_O, and identification_create_from_string().
 {
     identification_t *id;
     enumerator_t *enumerator;
     id_part_t part;
     chunk_t data;
     int i = 0;
     id = identification_create_from_string("C=CH, O=strongSwan, CN=tester");
     enumerator = id->create_part_enumerator(id);
     while (enumerator->enumerate(enumerator, &part, &data))
     {
         switch (i++)
         {
             case 0:
                 ck_assert(part == ID_PART_RDN_C &&
                           chunk_equals(data, chunk_create("CH", 2)));
                 break;
             case 1:
                 ck_assert(part == ID_PART_RDN_O &&
                           chunk_equals(data, chunk_from_str("strongSwan")));
                 break;
             case 2:
                 ck_assert(part == ID_PART_RDN_CN &&
                           chunk_equals(data, chunk_from_str("tester")));
                 break;
             default:
                 fail("unexpected identification part %d", part);
         }
     }
     ck_assert_int_eq(i, 3);
     enumerator->destroy(enumerator);
     id->destroy(id);
 }
START_TEST (test_contains_wildcards)
Definition at line 868 of file test_identification.c.
References ck_assert, and id_contains_wildcards().
 {
     ck_assert(id_contains_wildcards("%any"));
     ck_assert(id_contains_wildcards("C=*, O=strongSwan, CN=gw"));
     ck_assert(id_contains_wildcards("C=CH, O=strongSwan, CN=*"));
     ck_assert(id_contains_wildcards("*@strongswan.org"));
     ck_assert(id_contains_wildcards("*.strongswan.org"));
     ck_assert(!id_contains_wildcards("C=**, O=a*, CN=*a"));
 }
END_TEST START_TEST (test_clone)
Definition at line 883 of file test_identification.c.
References a, b, chunk_equals(), ck_assert, identification_t::clone, identification_t::destroy, identification_t::get_encoding, identification_create_from_string(), and chunk_t::ptr.
 {
     identification_t *a, *b;
     chunk_t a_enc, b_enc;
     a = identification_create_from_string("moon@strongswan.org");
     a_enc = a->get_encoding(a);
     b = a->clone(a);
     ck_assert(b != NULL);
     ck_assert(a != b);
     b_enc = b->get_encoding(b);
     ck_assert(a_enc.ptr != b_enc.ptr);
     ck_assert(chunk_equals(a_enc, b_enc));
     a->destroy(a);
     b->destroy(b);
 }
static END_TEST void string_equals (char * a_str, char * b_str) static
Definition at line 238 of file test_identification.c.
References b, ck_assert_str_eq, DESTROY_IF, identification_create_from_string(), and snprintf.
Referenced by START_TEST().
 {
     identification_t *b;
     char buf[128];
     b = b_str ? identification_create_from_string(b_str) : NULL;
     snprintf(buf, sizeof(buf), "%Y", b);
     DESTROY_IF(b);
     ck_assert_str_eq(a_str, buf);
 }
static void string_equals_id (char * a_str, identification_t * b) static
Definition at line 249 of file test_identification.c.
References ck_assert_str_eq, DESTROY_IF, and snprintf.
Referenced by START_TEST().
 {
     char buf[128];
     snprintf(buf, sizeof(buf), "%Y", b);
     DESTROY_IF(b);
     ck_assert_str_eq(a_str, buf);
 }
Variable Documentation
chunk_t c
Definition at line 120 of file test_identification.c.
Referenced by add_mod(), assist128(), cancellation_accept(), check_kernel_features(), command_dispatch(), decrypt_ccm128(), decrypt_ccm192(), decrypt_ccm256(), decrypt_ccm_rem(), des_set_key(), do_args(), email_matches(), encrypt_ccm128(), encrypt_ccm192(), encrypt_ccm256(), encrypt_ccm_rem(), encrypt_mppe_key(), fqdn_matches(), get_jhash_version(), icv_header(), initiate(), jhash(), main(), MD4Transform(), MD5Transform(), memwipe_inline(), METHOD(), ring_inv(), rsaep(), run(), SHA1Final(), SHA1Transform(), sha256_transform(), sha512_transform(), socketpair(), START_TEST(), and utils_memrchr().
union { ... } data
Referenced by START_TEST().
char* id
Definition at line 111 of file test_identification.c.
Referenced by id_contains_wildcards(), and START_TEST().
struct { ... } result
Referenced by START_TEST().
char* s
Definition at line 121 of file test_identification.c.
Referenced by identification_suite_create().
END_TEST { ... } string_data[]
Referenced by identification_suite_create(), and START_TEST().
enum { ... } type
Definition at line 112 of file test_identification.c.