strongSwan: radius_message.c File Reference
radius_message.c File Reference
#include "radius_message.h"
#include <utils/debug.h>
#include <bio/bio_reader.h>
#include <crypto/hashers/hasher.h>
Classes
struct rmsg_t
struct rattr_t
struct private_radius_message_t
struct attribute_enumerator_t
struct vendor_enumerator_t
Typedefs
typedef struct
private_radius_message_t private_radius_message_t
typedef struct rmsg_t rmsg_t
typedef struct rattr_t rattr_t
Functions
struct rmsg_t __attribute__ ((packed))
void libradius_init (void)
ENUM_BEGIN (radius_message_code_names, RMC_ACCESS_REQUEST, RMC_ACCOUNTING_RESPONSE,"Access-Request","Access-Accept","Access-Reject","Accounting-Request","Accounting-Response")
ENUM_NEXT (radius_message_code_names, RMC_ACCESS_CHALLENGE, RMC_ACCESS_CHALLENGE, RMC_ACCOUNTING_RESPONSE,"Access-Challenge")
ENUM_NEXT (radius_message_code_names, RMC_DISCONNECT_REQUEST, RMC_COA_NAK, RMC_ACCESS_CHALLENGE,"Disconnect-Request","Disconnect-ACK","Disconnect-NAK","CoA-Request","CoA-ACK","CoA-NAK")
ENUM_END (radius_message_code_names, RMC_COA_NAK)
ENUM_BEGIN (radius_attribute_type_names, RAT_USER_NAME, RAT_MIP6_HOME_LINK_PREFIX,"User-Name","User-Password","CHAP-Password","NAS-IP-Address","NAS-Port","Service-Type","Framed-Protocol","Framed-IP-Address","Framed-IP-Netmask","Framed-Routing","Filter-Id","Framed-MTU","Framed-Compression","Login-IP-Host","Login-Service","Login-TCP-Port","Unassigned","Reply-Message","Callback-Number","Callback-Id","Unassigned","Framed-Route","Framed-IPX-Network","State","Class","Vendor-Specific","Session-Timeout","Idle-Timeout","Termination-Action","Called-Station-Id","Calling-Station-Id","NAS-Identifier","Proxy-State","Login-LAT-Service","Login-LAT-Node","Login-LAT-Group","Framed-AppleTalk-Link","Framed-AppleTalk-Network","Framed-AppleTalk-Zone","Acct-Status-Type","Acct-Delay-Time","Acct-Input-Octets","Acct-Output-Octets","Acct-Session-Id","Acct-Authentic","Acct-Session-Time","Acct-Input-Packets","Acct-Output-Packets","Acct-Terminate-Cause","Acct-Multi-Session-Id","Acct-Link-Count","Acct-Input-Gigawords","Acct-Output-Gigawords","Unassigned","Event-Timestamp","Egress-VLANID","Ingress-Filters","Egress-VLAN-Name","User-Priority-Table","CHAP-Challenge","NAS-Port-Type","Port-Limit","Login-LAT-Port","Tunnel-Type","Tunnel-Medium-Type","Tunnel-Client-Endpoint","Tunnel-Server-Endpoint","Acct-Tunnel-Connection","Tunnel-Password","ARAP-Password","ARAP-Features","ARAP-Zone-Access","ARAP-Security","ARAP-Security-Data","Password-Retry","Prompt","Connect-Info","Configuration-Token","EAP-Message","Message-Authenticator","Tunnel-Private-Group-ID","Tunnel-Assignment-ID","Tunnel-Preference","ARAP-Challenge-Response","Acct-Interim-Interval","Acct-Tunnel-Packets-Lost","NAS-Port-Id","Framed-Pool","CUI","Tunnel-Client-Auth-ID","Tunnel-Server-Auth-ID","NAS-Filter-Rule","Unassigned","Originating-Line-Info","NAS-IPv6-Address","Framed-Interface-Id","Framed-IPv6-Prefix","Login-IPv6-Host","Framed-IPv6-Route","Framed-IPv6-Pool","Error-Cause","EAP-Key-Name","Digest-Response","Digest-Realm","Digest-Nonce","Digest-Response-Auth","Digest-Nextnonce","Digest-Method","Digest-URI","Digest-Qop","Digest-Algorithm","Digest-Entity-Body-Hash","Digest-CNonce","Digest-Nonce-Count","Digest-Username","Digest-Opaque","Digest-Auth-Param","Digest-AKA-Auts","Digest-Domain","Digest-Stale","Digest-HA1","SIP-AOR","Delegated-IPv6-Prefix","MIP6-Feature-Vector","MIP6-Home-Link-Prefix")
ENUM_NEXT (radius_attribute_type_names, RAT_FRAMED_IPV6_ADDRESS, RAT_STATEFUL_IPV6_ADDRESS_POOL, RAT_MIP6_HOME_LINK_PREFIX,"Framed-IPv6-Address","DNS-Server-IPv6-Address","Route-IPv6-Information","Delegated-IPv6-Prefix-Pool","Stateful-IPv6-Address-Pool")
ENUM_END (radius_attribute_type_names, RAT_STATEFUL_IPV6_ADDRESS_POOL)
METHOD (enumerator_t, attribute_enumerate, bool, attribute_enumerator_t *this, int *type, chunk_t *data)
METHOD (radius_message_t, create_enumerator, enumerator_t *, private_radius_message_t *this)
METHOD (enumerator_t, vendor_enumerate, bool, vendor_enumerator_t *this, int *vendor, int *type, chunk_t *data)
METHOD (enumerator_t, vendor_destroy, void, vendor_enumerator_t *this)
METHOD (radius_message_t, create_vendor_enumerator, enumerator_t *, private_radius_message_t *this)
METHOD (radius_message_t, add, void, private_radius_message_t *this, radius_attribute_type_t type, chunk_t data)
METHOD (radius_message_t, crypt, bool, private_radius_message_t *this, chunk_t salt, chunk_t in, chunk_t out, chunk_t secret, hasher_t *hasher)
METHOD (radius_message_t, sign, bool, private_radius_message_t *this, u_int8_t *req_auth, chunk_t secret, hasher_t *hasher, signer_t *signer, rng_t *rng, bool msg_auth)
METHOD (radius_message_t, verify, bool, private_radius_message_t *this, u_int8_t *req_auth, chunk_t secret, hasher_t *hasher, signer_t *signer)
METHOD (radius_message_t, get_code, radius_message_code_t, private_radius_message_t *this)
METHOD (radius_message_t, get_identifier, u_int8_t, private_radius_message_t *this)
METHOD (radius_message_t, set_identifier, void, private_radius_message_t *this, u_int8_t identifier)
METHOD (radius_message_t, get_authenticator, u_int8_t *, private_radius_message_t *this)
METHOD (radius_message_t, get_encoding, chunk_t, private_radius_message_t *this)
METHOD (radius_message_t, destroy, void, private_radius_message_t *this)
static private_radius_message_t * radius_message_create_empty ()
radius_message_t * radius_message_create (radius_message_code_t code)
radius_message_t * radius_message_parse (chunk_t data)
Variables
u_int8_t code
u_int8_t identifier
u_int16_t length
u_int8_t authenticator [HASH_SIZE_MD5]
u_int8_t attributes []
u_int8_t type
u_int8_t value []
struct private_radius_message_t __attribute__
Typedef Documentation
typedef struct private_radius_message_t private_radius_message_t
Definition at line 22 of file radius_message.c.
typedef struct rattr_t rattr_t
Definition at line 24 of file radius_message.c.
typedef struct rmsg_t rmsg_t
Definition at line 23 of file radius_message.c.
Function Documentation
ENUM_BEGIN (radius_message_code_names , RMC_ACCESS_REQUEST , RMC_ACCOUNTING_RESPONSE , "Access-Request" , "Access-Accept" , "Access-Reject" , "Accounting-Request" , "Accounting-Response")
ENUM_BEGIN (radius_attribute_type_names , RAT_USER_NAME , RAT_MIP6_HOME_LINK_PREFIX , "User-Name" , "User-Password" , "CHAP-Password" , "NAS-IP-Address" , "NAS-Port" , "Service-Type" , "Framed-Protocol" , "Framed-IP-Address" , "Framed-IP-Netmask" , "Framed-Routing" , "Filter-Id" , "Framed-MTU" , "Framed-Compression" , "Login-IP-Host" , "Login-Service" , "Login-TCP-Port" , "Unassigned" , "Reply-Message" , "Callback-Number" , "Callback-Id" , "Unassigned" , "Framed-Route" , "Framed-IPX-Network" , "State" , "Class" , "Vendor-Specific" , "Session-Timeout" , "Idle-Timeout" , "Termination-Action" , "Called-Station-Id" , "Calling-Station-Id" , "NAS-Identifier" , "Proxy-State" , "Login-LAT-Service" , "Login-LAT-Node" , "Login-LAT-Group" , "Framed-AppleTalk-Link" , "Framed-AppleTalk-Network" , "Framed-AppleTalk-Zone" , "Acct-Status-Type" , "Acct-Delay-Time" , "Acct-Input-Octets" , "Acct-Output-Octets" , "Acct-Session-Id" , "Acct-Authentic" , "Acct-Session-Time" , "Acct-Input-Packets" , "Acct-Output-Packets" , "Acct-Terminate-Cause" , "Acct-Multi-Session-Id" , "Acct-Link-Count" , "Acct-Input-Gigawords" , "Acct-Output-Gigawords" , "Unassigned" , "Event-Timestamp" , "Egress-VLANID" , "Ingress-Filters" , "Egress-VLAN-Name" , "User-Priority-Table" , "CHAP-Challenge" , "NAS-Port-Type" , "Port-Limit" , "Login-LAT-Port" , "Tunnel-Type" , "Tunnel-Medium-Type" , "Tunnel-Client-Endpoint" , "Tunnel-Server-Endpoint" , "Acct-Tunnel-Connection" , "Tunnel-Password" , "ARAP-Password" , "ARAP-Features" , "ARAP-Zone-Access" , "ARAP-Security" , "ARAP-Security-Data" , "Password-Retry" , "Prompt" , "Connect-Info" , "Configuration-Token" , "EAP-Message" , "Message-Authenticator" , "Tunnel-Private-Group-ID" , "Tunnel-Assignment-ID" , "Tunnel-Preference" , "ARAP-Challenge-Response" , "Acct-Interim-Interval" , "Acct-Tunnel-Packets-Lost" , "NAS-Port-Id" , "Framed-Pool" , "CUI" , "Tunnel-Client-Auth-ID" , "Tunnel-Server-Auth-ID" , "NAS-Filter-Rule" , "Unassigned" , "Originating-Line-Info" , "NAS-IPv6-Address" , "Framed-Interface-Id" , "Framed-IPv6-Prefix" , "Login-IPv6-Host" , "Framed-IPv6-Route" , "Framed-IPv6-Pool" , "Error-Cause" , "EAP-Key-Name" , "Digest-Response" , "Digest-Realm" , "Digest-Nonce" , "Digest-Response-Auth" , "Digest-Nextnonce" , "Digest-Method" , "Digest-URI" , "Digest-Qop" , "Digest-Algorithm" , "Digest-Entity-Body-Hash" , "Digest-CNonce" , "Digest-Nonce-Count" , "Digest-Username" , "Digest-Opaque" , "Digest-Auth-Param" , "Digest-AKA-Auts" , "Digest-Domain" , "Digest-Stale" , "Digest-HA1" , "SIP-AOR" , "Delegated-IPv6-Prefix" , "MIP6-Feature-Vector" , "MIP6-Home-Link-Prefix")
ENUM_END (radius_message_code_names , RMC_COA_NAK)
ENUM_END (radius_attribute_type_names , RAT_STATEFUL_IPV6_ADDRESS_POOL)
ENUM_NEXT (radius_message_code_names , RMC_ACCESS_CHALLENGE , RMC_ACCESS_CHALLENGE , RMC_ACCOUNTING_RESPONSE , "Access-Challenge")
ENUM_NEXT (radius_message_code_names , RMC_DISCONNECT_REQUEST , RMC_COA_NAK , RMC_ACCESS_CHALLENGE , "Disconnect-Request" , "Disconnect-ACK" , "Disconnect-NAK" , "CoA-Request" , "CoA-ACK" , "CoA-NAK")
ENUM_NEXT (radius_attribute_type_names , RAT_FRAMED_IPV6_ADDRESS , RAT_STATEFUL_IPV6_ADDRESS_POOL , RAT_MIP6_HOME_LINK_PREFIX , "Framed-IPv6-Address" , "DNS-Server-IPv6-Address" , "Route-IPv6-Information" , "Delegated-IPv6-Prefix-Pool" , "Stateful-IPv6-Address-Pool")
METHOD (enumerator_t , attribute_enumerate , bool , attribute_enumerator_t * this, int * type, chunk_t * data)
Definition at line 246 of file radius_message.c.
References DBG1, DBG_IKE, FALSE, chunk_t::len, next, chunk_t::ptr, and TRUE.
 {
     if (this->left == 0)
     {
         return FALSE;
     }
     if (this->left < sizeof(rattr_t) ||
         this->left < this->next->length)
     {
         DBG1(DBG_IKE, "RADIUS message truncated");
         return FALSE;
     }
     *type = this->next->type;
     data->ptr = this->next->value;
     data->len = this->next->length - sizeof(rattr_t);
     this->left -= this->next->length;
     this->next = ((void*)this->next) + this->next->length;
     return TRUE;
 }
METHOD (radius_message_t , create_enumerator , enumerator_t * , private_radius_message_t * this)
Definition at line 267 of file radius_message.c.
References destroy(), enumerator_create_empty(), free(), INIT, msg, and attribute_enumerator_t::public.
 {
     attribute_enumerator_t *e;
     if (ntohs(this->msg->length) < sizeof(rmsg_t) + sizeof(rattr_t))
     {
         return enumerator_create_empty();
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_attribute_enumerate,
             .destroy = (void*)free,
         },
         .next = (rattr_t*)this->msg->attributes,
         .left = ntohs(this->msg->length) - sizeof(rmsg_t),
     );
     return &e->public;
 }
METHOD (enumerator_t , vendor_enumerate , bool , vendor_enumerator_t * this, int * vendor, int * type, chunk_t * data)
Definition at line 301 of file radius_message.c.
References bio_reader_create(), FALSE, len, RAT_VENDOR_SPECIFIC, and TRUE.
 {
     chunk_t inner_data;
     int inner_type;
     u_int8_t type8, len;
     while (TRUE)
     {
         if (this->reader)
         {
             if (this->reader->remaining(this->reader) >= 2 &&
                 this->reader->read_uint8(this->reader, &type8) &&
                 this->reader->read_uint8(this->reader, &len) && len >= 2 &&
                 this->reader->read_data(this->reader, len - 2, data))
             {
                 *vendor = this->vendor;
                 *type = type8;
                 return TRUE;
             }
             this->reader->destroy(this->reader);
             this->reader = NULL;
         }
         if (this->inner->enumerate(this->inner, &inner_type, &inner_data))
         {
             if (inner_type == RAT_VENDOR_SPECIFIC)
             {
                 this->reader = bio_reader_create(inner_data);
                 if (!this->reader->read_uint32(this->reader, &this->vendor))
                 {
                     this->reader->destroy(this->reader);
                     this->reader = NULL;
                 }
             }
         }
         else
         {
             return FALSE;
         }
     }
 }
METHOD (enumerator_t , vendor_destroy , void , vendor_enumerator_t * this)
Definition at line 342 of file radius_message.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->reader);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (radius_message_t , create_vendor_enumerator , enumerator_t * , private_radius_message_t * this)
Definition at line 350 of file radius_message.c.
References create_enumerator(), destroy(), INIT, and vendor_enumerator_t::public.
 {
     vendor_enumerator_t *e;
     INIT(e,
         .public = {
             .enumerate = (void*)_vendor_enumerate,
             .destroy = _vendor_destroy,
         },
         .inner = create_enumerator(this),
     );
     return &e->public;
 }
METHOD (radius_message_t , add , void , private_radius_message_t * this, radius_attribute_type_t type, chunk_t data)
Definition at line 366 of file radius_message.c.
References chunk_alloc, HASH_SIZE_MD5, chunk_t::len, rattr_t::length, MAX_RADIUS_ATTRIBUTE_SIZE, memcpy, memset, min, msg, chunk_t::ptr, RAT_USER_PASSWORD, round_up(), rattr_t::type, type, and rattr_t::value.
 {
     rattr_t *attribute;
     if (type == RAT_USER_PASSWORD && !this->password.len)
     {
         /* store a null-padded password */
         this->password = chunk_alloc(round_up(data.len, HASH_SIZE_MD5));
         memset(this->password.ptr + data.len, 0, this->password.len - data.len);
         memcpy(this->password.ptr, data.ptr, data.len);
         return;
     }
     data.len = min(data.len, MAX_RADIUS_ATTRIBUTE_SIZE);
     this->msg = realloc(this->msg,
                         ntohs(this->msg->length) + sizeof(rattr_t) + data.len);
     attribute = ((void*)this->msg) + ntohs(this->msg->length);
     attribute->type = type;
     attribute->length = data.len + sizeof(rattr_t);
     memcpy(attribute->value, data.ptr, data.len);
     this->msg->length = htons(ntohs(this->msg->length) + attribute->length);
 }
METHOD (radius_message_t , crypt , bool , private_radius_message_t * this, chunk_t salt, chunk_t in, chunk_t out, chunk_t secret, hasher_t * hasher)
From RFC2548 (encryption): b(1) = MD5(S + R + A) c(1) = p(1) xor b(1) C = c(1) b(2) = MD5(S + c(1)) c(2) = p(2) xor b(2) C = C + c(2) . . . b(i) = MD5(S + c(i-1)) c(i) = p(i) xor b(i) C = C + c(i)
P/C = Plain/Crypted => in/out S = secret R = authenticator A = salt
Definition at line 390 of file radius_message.c.
References b, chunk_create(), chunk_from_thing, chunk_skip(), FALSE, hasher_t::get_hash, HASH_SIZE_MD5, chunk_t::len, memcpy, memxor(), msg, chunk_t::ptr, and TRUE.
 {
     char b[HASH_SIZE_MD5];
     if (in.len != out.len)
     {
         return FALSE;
     }
     if (in.len % HASH_SIZE_MD5 || in.len < HASH_SIZE_MD5)
     {
         return FALSE;
     }
     if (out.ptr != in.ptr)
     {
         memcpy(out.ptr, in.ptr, in.len);
     }
     /* Preparse seed for first round:
      * b(1) = MD5(S + R + A) */
     if (!hasher->get_hash(hasher, secret, NULL) ||
         !hasher->get_hash(hasher,
                           chunk_from_thing(this->msg->authenticator), NULL) ||
         !hasher->get_hash(hasher, salt, b))
     {
         return FALSE;
     }
     while (in.len)
     {
         /* p(i) = b(i) xor c(1) */
         memxor(out.ptr, b, HASH_SIZE_MD5);
         out = chunk_skip(out, HASH_SIZE_MD5);
         if (out.len)
         {
             /* Prepare seed for next round::
              * b(i) = MD5(S + c(i-1)) */
             if (!hasher->get_hash(hasher, secret, NULL) ||
                 !hasher->get_hash(hasher,
                                   chunk_create(in.ptr, HASH_SIZE_MD5), b))
             {
                 return FALSE;
             }
         }
         in = chunk_skip(in, HASH_SIZE_MD5);
     }
     return TRUE;
 }
METHOD (radius_message_t , sign , bool , private_radius_message_t * this, u_int8_t * req_auth, chunk_t secret, hasher_t * hasher, signer_t * signer, rng_t * rng, bool msg_auth)
Definition at line 451 of file radius_message.c.
References add(), chunk_clear(), chunk_create(), chunk_empty, crypt(), FALSE, rng_t::get_bytes, hasher_t::get_hash, signer_t::get_signature, HASH_SIZE_MD5, memcpy, memset, msg, RAT_MESSAGE_AUTHENTICATOR, RAT_USER_PASSWORD, and TRUE.
 {
     if (rng)
     {
         /* build Request-Authenticator */
         if (!rng->get_bytes(rng, HASH_SIZE_MD5, this->msg->authenticator))
         {
             return FALSE;
         }
     }
     else
     {
         /* prepare build of Response-Authenticator */
         if (req_auth)
         {
             memcpy(this->msg->authenticator, req_auth, HASH_SIZE_MD5);
         }
         else
         {
             memset(this->msg->authenticator, 0, sizeof(this->msg->authenticator));
         }
     }
     if (this->password.len)
     {
         /* encrypt password inline */
         if (!crypt(this, chunk_empty, this->password, this->password,
                    secret, hasher))
         {
             return FALSE;
         }
         add(this, RAT_USER_PASSWORD, this->password);
         chunk_clear(&this->password);
     }
     if (msg_auth)
     {
         char buf[HASH_SIZE_MD5];
         /* build Message-Authenticator attribute, using 16 null bytes */
         memset(buf, 0, sizeof(buf));
         add(this, RAT_MESSAGE_AUTHENTICATOR, chunk_create(buf, sizeof(buf)));
         if (!signer->get_signature(signer,
                 chunk_create((u_char*)this->msg, ntohs(this->msg->length)),
                 ((u_char*)this->msg) + ntohs(this->msg->length) - HASH_SIZE_MD5))
         {
             return FALSE;
         }
     }
     if (!rng)
     {
         chunk_t msg;
         /* build Response-Authenticator */
         msg = chunk_create((u_char*)this->msg, ntohs(this->msg->length));
         if (!hasher->get_hash(hasher, msg, NULL) ||
             !hasher->get_hash(hasher, secret, this->msg->authenticator))
         {
             return FALSE;
         }
     }
     return TRUE;
 }
METHOD (radius_message_t , verify , bool , private_radius_message_t * this, u_int8_t * req_auth, chunk_t secret, hasher_t * hasher, signer_t * signer)
Definition at line 518 of file radius_message.c.
References chunk_create(), create_enumerator(), data, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, hasher_t::get_hash, HASH_SIZE_MD5, chunk_t::len, memcpy, memeq_const(), memset, msg, chunk_t::ptr, RAT_EAP_MESSAGE, RAT_MESSAGE_AUTHENTICATOR, RMC_ACCESS_REQUEST, TRUE, type, and signer_t::verify_signature.
 {
     char buf[HASH_SIZE_MD5], res_auth[HASH_SIZE_MD5];
     enumerator_t *enumerator;
     int type;
     chunk_t data, msg;
     bool has_eap = FALSE, has_auth = FALSE;
     msg = chunk_create((u_char*)this->msg, ntohs(this->msg->length));
     if (this->msg->code != RMC_ACCESS_REQUEST)
     {
         /* replace Response by Request Authenticator for verification */
         memcpy(res_auth, this->msg->authenticator, HASH_SIZE_MD5);
         if (req_auth)
         {
             memcpy(this->msg->authenticator, req_auth, HASH_SIZE_MD5);
         }
         else
         {
             memset(this->msg->authenticator, 0, HASH_SIZE_MD5);
         }
         /* verify Response-Authenticator */
         if (!hasher->get_hash(hasher, msg, NULL) ||
             !hasher->get_hash(hasher, secret, buf) ||
             !memeq_const(buf, res_auth, HASH_SIZE_MD5))
         {
             DBG1(DBG_CFG, "RADIUS Response-Authenticator verification failed");
             return FALSE;
         }
     }
     /* verify Message-Authenticator attribute */
     enumerator = create_enumerator(this);
     while (enumerator->enumerate(enumerator, &type, &data))
     {
         if (type == RAT_MESSAGE_AUTHENTICATOR)
         {
             if (data.len != HASH_SIZE_MD5)
             {
                 DBG1(DBG_CFG, "RADIUS Message-Authenticator invalid length");
                 enumerator->destroy(enumerator);
                 return FALSE;
             }
             memcpy(buf, data.ptr, data.len);
             memset(data.ptr, 0, data.len);
             if (signer->verify_signature(signer, msg,
                                          chunk_create(buf, sizeof(buf))))
             {
                 /* restore Message-Authenticator */
                 memcpy(data.ptr, buf, data.len);
                 has_auth = TRUE;
                 break;
             }
             else
             {
                 DBG1(DBG_CFG, "RADIUS Message-Authenticator verification failed");
                 enumerator->destroy(enumerator);
                 return FALSE;
             }
         }
         else if (type == RAT_EAP_MESSAGE)
         {
             has_eap = TRUE;
         }
     }
     enumerator->destroy(enumerator);
     if (this->msg->code != RMC_ACCESS_REQUEST)
     {
         /* restore Response-Authenticator */
         memcpy(this->msg->authenticator, res_auth, HASH_SIZE_MD5);
     }
     if (has_eap && !has_auth)
     {   /* Message-Authenticator is required if we have an EAP-Message */
         DBG1(DBG_CFG, "RADIUS Message-Authenticator attribute missing");
         return FALSE;
     }
     return TRUE;
 }
METHOD (radius_message_t , get_code , radius_message_code_t , private_radius_message_t * this)
Definition at line 603 of file radius_message.c.
References msg.
 {
     return this->msg->code;
 }
METHOD (radius_message_t , get_identifier , u_int8_t , private_radius_message_t * this)
Definition at line 609 of file radius_message.c.
References msg.
 {
     return this->msg->identifier;
 }
METHOD (radius_message_t , set_identifier , void , private_radius_message_t * this, u_int8_t identifier)
Definition at line 615 of file radius_message.c.
References identifier, and msg.
 {
     this->msg->identifier = identifier;
 }
METHOD (radius_message_t , get_authenticator , u_int8_t * , private_radius_message_t * this)
Definition at line 621 of file radius_message.c.
References msg.
 {
     return this->msg->authenticator;
 }
METHOD (radius_message_t , get_encoding , chunk_t , private_radius_message_t * this)
Definition at line 628 of file radius_message.c.
References chunk_create(), and msg.
 {
     return chunk_create((u_char*)this->msg, ntohs(this->msg->length));
 }
METHOD (radius_message_t , destroy , void , private_radius_message_t * this)
Definition at line 634 of file radius_message.c.
References chunk_clear(), free(), and msg.
 {
     chunk_clear(&this->password);
     free(this->msg);
     free(this);
 }
static private_radius_message_t* radius_message_create_empty () static
Generic constructor
Definition at line 645 of file radius_message.c.
References INIT.
Referenced by radius_message_create(), and radius_message_parse().
 {
     private_radius_message_t *this;
     INIT(this,
         .public = {
             .create_enumerator = _create_enumerator,
             .create_vendor_enumerator = _create_vendor_enumerator,
             .add = _add,
             .get_code = _get_code,
             .get_identifier = _get_identifier,
             .set_identifier = _set_identifier,
             .get_authenticator = _get_authenticator,
             .get_encoding = _get_encoding,
             .sign = _sign,
             .verify = _verify,
             .crypt = _crypt,
             .destroy = _destroy,
         },
     );
     return this;
 }
Variable Documentation
struct private_radius_message_t __attribute__
u_int8_t attributes[]
variable list of packed attributes
Definition at line 112 of file radius_message.c.
Referenced by add_attribute(), add_legacy_entry(), build_ack(), build_encoding(), build_peer_cfg(), compute_length(), destroy(), generate(), get_attr(), get_life_duration(), get_string(), handle_attribute(), load_entries(), METHOD(), METHOD2(), parse_attributes(), process_payloads(), signerinfo_destroy(), and stroke_config_create().
u_int8_t authenticator[HASH_SIZE_MD5]
message authenticator, MD5 hash
Definition at line 110 of file radius_message.c.
Referenced by create_authenticator(), and METHOD().
u_int8_t code
message code, radius_message_code_t
Definition at line 104 of file radius_message.c.
u_int8_t identifier
message identifier
Definition at line 106 of file radius_message.c.
Referenced by METHOD(), and radius_message_create().
u_int8_t length
length of Code, Identifier, Length, Authenticator and Attributes
length of the attriubte, including the Type, Length and Value fields
Definition at line 108 of file radius_message.c.
Referenced by radius_message_create().
u_int8_t type
attribute type, radius_attribute_type_t
Definition at line 104 of file radius_message.c.
Referenced by METHOD().
u_int8_t value[]
variable length attribute value
Definition at line 108 of file radius_message.c.