strongSwan: ike_cfg
ike_cfg
config
Classes
struct ike_cfg_t
Typedefs
typedef enum ike_version_t ike_version_t
typedef enum fragmentation_t fragmentation_t
typedef struct ike_cfg_t ike_cfg_t
Enumerations
enum ike_version_t { IKE_ANY = 0, IKEV1 = 1, IKEV2 = 2 }
enum fragmentation_t {
FRAGMENTATION_NO, FRAGMENTATION_YES, FRAGMENTATION_FORCE, FRAGMENTATION_NO,
FRAGMENTATION_YES, FRAGMENTATION_FORCE
}
Functions
ike_cfg_t * ike_cfg_create (ike_version_t version, bool certreq, bool force_encap, char *me, u_int16_t my_port, char *other, u_int16_t other_port, fragmentation_t fragmentation, u_int8_t dscp)
int ike_cfg_get_family (ike_cfg_t *this, bool local)
Variables
enum_name_t * ike_version_names
Detailed Description
Typedef Documentation
typedef enum fragmentation_t fragmentation_t
Definition at line 27 of file ike_cfg.h.
typedef struct ike_cfg_t ike_cfg_t
Definition at line 28 of file ike_cfg.h.
typedef enum ike_version_t ike_version_t
Definition at line 26 of file ike_cfg.h.
Enumeration Type Documentation
enum fragmentation_t
Proprietary IKEv1 fragmentation
Enumerator
FRAGMENTATION_NO
disable fragmentation
FRAGMENTATION_YES
enable fragmentation if supported by peer
FRAGMENTATION_FORCE
force use of fragmentation (even for the first message)
FRAGMENTATION_NO
FRAGMENTATION_YES
FRAGMENTATION_FORCE
Definition at line 52 of file ike_cfg.h.
                      {
     FRAGMENTATION_NO,
     FRAGMENTATION_YES,
     FRAGMENTATION_FORCE,
 };
enum ike_version_t
IKE version.
Enumerator
IKE_ANY
any version
IKEV1
IKE version 1
IKEV2
IKE version 2
Definition at line 40 of file ike_cfg.h.
                    {
     IKE_ANY = 0,
     IKEV1 = 1,
     IKEV2 = 2,
 };
Function Documentation
ike_cfg_t* ike_cfg_create (ike_version_t version, bool certreq, bool force_encap, char * me, u_int16_t my_port, char * other, u_int16_t other_port, fragmentation_t fragmentation, u_int8_t dscp)
Creates a ike_cfg_t object.
Supplied hosts become owned by ike_cfg, strings get cloned.
me and other are comma separated lists of IP addresses, DNS names, IP ranges or subnets. When initiating, the first non-range/subnet address is used as address. When responding, a match is performed against all items in the list.
Parameters
version IKE major version to use for this config
certreq TRUE to send a certificate request
force_encap enforce UDP encapsulation by faking NATD notify
me address/DNS name of local peer
my_port IKE port to use as source, 500 uses IKEv2 port floating
other address/DNS name of remote peer
other_port IKE port to use as dest, 500 uses IKEv2 port floating
fragmentation use IKEv1 fragmentation
dscp DSCP value to send IKE packets with
Returns
ike_cfg_t object.
Described in header.
Definition at line 563 of file ike_cfg.c.
References force_encap(), INIT, linked_list_create(), parse_addresses(), strdup, and version.
Referenced by assert_family(), build_ike_cfg(), CALLBACK(), connect_(), create_peer_cfg(), generate_config(), initiate_connection(), load_ike_config(), medcli_config_create(), medsrv_config_create(), METHOD(), and setup_tunnel().
 {
     private_ike_cfg_t *this;
     INIT(this,
         .public = {
             .get_version = _get_version,
             .send_certreq = _send_certreq,
             .force_encap = _force_encap_,
             .fragmentation = _fragmentation,
             .resolve_me = _resolve_me,
             .resolve_other = _resolve_other,
             .match_me = _match_me,
             .match_other = _match_other,
             .get_my_addr = _get_my_addr,
             .get_other_addr = _get_other_addr,
             .get_my_port = _get_my_port,
             .get_other_port = _get_other_port,
             .get_dscp = _get_dscp,
             .add_proposal = _add_proposal,
             .get_proposals = _get_proposals,
             .select_proposal = _select_proposal,
             .get_dh_group = _get_dh_group,
             .equals = _equals,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .refcount = 1,
         .version = version,
         .certreq = certreq,
         .force_encap = force_encap,
         .fragmentation = fragmentation,
         .me = strdup(me),
         .my_ranges = linked_list_create(),
         .my_hosts = linked_list_create(),
         .other = strdup(other),
         .other_ranges = linked_list_create(),
         .other_hosts = linked_list_create(),
         .my_port = my_port,
         .other_port = other_port,
         .dscp = dscp,
         .proposals = linked_list_create(),
     );
     parse_addresses(me, this->my_hosts, this->my_ranges);
     parse_addresses(other, this->other_hosts, this->other_ranges);
     return &this->public;
 }
int ike_cfg_get_family (ike_cfg_t * cfg, bool local)
Determine the address family of the local or remtoe address(es). If multiple families are configured AF_UNSPEC is returned. any is ignored (any4|6 are not though).
Parameters
this ike config to check
local TRUE to check local addresses, FALSE for remote
Returns
address family of address(es) if distinct
Described in header.
Definition at line 517 of file ike_cfg.c.
References enumerator_t::destroy, host_t::destroy, DESTROY_IF, enumerator_t::enumerate, family, host_t::get_family, host, host_create_from_string(), str, and streq().
Referenced by assert_family(), and resolve_hosts().
 {
     private_ike_cfg_t *this = (private_ike_cfg_t*)cfg;
     enumerator_t *enumerator;
     host_t *host;
     char *str;
     int family = AF_UNSPEC;
     if (local)
     {
         enumerator = this->my_hosts->create_enumerator(this->my_hosts);
     }
     else
     {
         enumerator = this->other_hosts->create_enumerator(this->other_hosts);
     }
     while (enumerator->enumerate(enumerator, &str))
     {
         if (streq(str, "%any"))
         {   /* ignore %any as its family is undetermined */
             continue;
         }
         host = host_create_from_string(str, 0);
         if (host)
         {
             if (family == AF_UNSPEC)
             {
                 family = host->get_family(host);
             }
             else if (family != host->get_family(host))
             {
                 /* more than one address family defined */
                 family = AF_UNSPEC;
                 host->destroy(host);
                 break;
             }
         }
         DESTROY_IF(host);
     }
     enumerator->destroy(enumerator);
     return family;
 }
Variable Documentation
enum_name_t* ike_version_names
enum strings fro ike_version_t
Referenced by CALLBACK(), log_ike_sa(), and METHOD().