strongSwan: pts_dh_group
pts_dh_group
pts
Typedefs
typedef enum pts_dh_group_t pts_dh_group_t
Enumerations
enum pts_dh_group_t {
PTS_DH_GROUP_NONE = 0, PTS_DH_GROUP_IKE2 = (1<<15), PTS_DH_GROUP_IKE5 = (1<<14), PTS_DH_GROUP_IKE14 = (1<<13),
PTS_DH_GROUP_IKE19 = (1<<12), PTS_DH_GROUP_IKE20 = (1<<11)
}
Functions
bool pts_dh_group_probe (pts_dh_group_t *dh_groups, bool mandatory_dh_groups)
bool pts_dh_group_update (char *dh_group, pts_dh_group_t *dh_groups)
pts_dh_group_t pts_dh_group_select (pts_dh_group_t supported_groups, pts_dh_group_t offered_groups)
diffie_hellman_group_t pts_dh_group_to_ike (pts_dh_group_t dh_group)
Detailed Description
Typedef Documentation
typedef enum pts_dh_group_t pts_dh_group_t
Definition at line 27 of file pts_dh_group.h.
Enumeration Type Documentation
enum pts_dh_group_t
PTS Diffie Hellman Group Values
Enumerator
PTS_DH_GROUP_NONE
No DH Group
PTS_DH_GROUP_IKE2
IKE Group 2
PTS_DH_GROUP_IKE5
IKE Group 5
PTS_DH_GROUP_IKE14
IKE Group 14
PTS_DH_GROUP_IKE19
IKE Group 19
PTS_DH_GROUP_IKE20
IKE Group 20
Definition at line 32 of file pts_dh_group.h.
                     {
     PTS_DH_GROUP_NONE  =                    0,
     PTS_DH_GROUP_IKE2  =                 (1<<15),
     PTS_DH_GROUP_IKE5  =                 (1<<14),
     PTS_DH_GROUP_IKE14 =                 (1<<13),
     PTS_DH_GROUP_IKE19 =                 (1<<12),
     PTS_DH_GROUP_IKE20 =                 (1<<11),
 };
Function Documentation
bool pts_dh_group_probe (pts_dh_group_t * dh_groups, bool mandatory_dh_groups)
Diffie-Hellman Group Values see section 3.8.6 of PTS Protocol: Binding to TNC IF-M Specification
                  1
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ |1|2|3|4|5|R|R|R|R|R|R|R|R|R|R|R| +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ Probe available PTS Diffie-Hellman groups
Parameters
dh_groups returns set of available DH groups
mandatory_dh_groups if TRUE enforce mandatory PTS DH groups
Returns
TRUE if mandatory DH groups are available or at least one optional DH group if mandatory_dh_groups is set to FALSE.
Described in header.
Definition at line 23 of file pts_dh_group.c.
References crypto_factory_t::create_dh_enumerator, library_t::crypto, DBG1, DBG2, DBG_PTS, enumerator_t::destroy, diffie_hellman_group_names, ECP_256_BIT, ECP_384_BIT, enumerator_t::enumerate, FALSE, lib, MODP_1024_BIT, MODP_1536_BIT, MODP_2048_BIT, PTS_DH_GROUP_IKE14, PTS_DH_GROUP_IKE19, PTS_DH_GROUP_IKE2, PTS_DH_GROUP_IKE20, PTS_DH_GROUP_IKE5, PTS_DH_GROUP_NONE, and TRUE.
Referenced by imv_attestation_agent_create(), and TNC_IMC_Initialize().
 {
     enumerator_t *enumerator;
     diffie_hellman_group_t dh_group;
     const char *plugin_name;
     char format1[] = "  %s PTS DH group %N[%s] available";
     char format2[] = "  %s PTS DH group %N not available";
     *dh_groups = PTS_DH_GROUP_NONE;
     enumerator = lib->crypto->create_dh_enumerator(lib->crypto);
     while (enumerator->enumerate(enumerator, &dh_group, &plugin_name))
     {
         if (dh_group == MODP_1024_BIT)
         {
             *dh_groups |= PTS_DH_GROUP_IKE2;
             DBG2(DBG_PTS, format1, "optional ", diffie_hellman_group_names,
                                     dh_group, plugin_name);
         }
         else if (dh_group == MODP_1536_BIT)
         {
             *dh_groups |= PTS_DH_GROUP_IKE5;
             DBG2(DBG_PTS, format1, "optional ", diffie_hellman_group_names,
                                     dh_group, plugin_name);
         }
         else if (dh_group == MODP_2048_BIT)
         {
             *dh_groups |= PTS_DH_GROUP_IKE14;
             DBG2(DBG_PTS, format1, "optional ", diffie_hellman_group_names,
                                     dh_group, plugin_name);
         }
         else if (dh_group == ECP_256_BIT)
         {
             *dh_groups |= PTS_DH_GROUP_IKE19;
             DBG2(DBG_PTS, format1, "mandatory", diffie_hellman_group_names,
                                     dh_group, plugin_name);
         }
         else if (dh_group == ECP_384_BIT)
         {
             *dh_groups |= PTS_DH_GROUP_IKE20;
             DBG2(DBG_PTS, format1, "optional ", diffie_hellman_group_names,
                                     dh_group, plugin_name);
         }
     }
     enumerator->destroy(enumerator);
     if (*dh_groups & PTS_DH_GROUP_IKE19)
     {
         /* mandatory PTS DH group is available */
         return TRUE;
     }
     if (*dh_groups == PTS_DH_GROUP_NONE)
     {
         DBG1(DBG_PTS, "no PTS DH group available");
         return FALSE;
     }
     if (mandatory_dh_groups)
     {
         DBG1(DBG_PTS, format2, "mandatory", diffie_hellman_group_names,
                                             ECP_256_BIT);
         return FALSE;
     }
     /* at least one optional PTS DH group is available */
     return TRUE;
 }
pts_dh_group_t pts_dh_group_select (pts_dh_group_t supported_dh_groups, pts_dh_group_t offered_dh_groups)
Select the strongest supported Diffie-Hellman group among a set of offered DH groups
Parameters
supported_groups set of supported DH groups
offered_groups set of offered DH groups
Returns
selected DH group
Described in header.
Definition at line 133 of file pts_dh_group.c.
References PTS_DH_GROUP_IKE14, PTS_DH_GROUP_IKE19, PTS_DH_GROUP_IKE2, PTS_DH_GROUP_IKE20, PTS_DH_GROUP_IKE5, and PTS_DH_GROUP_NONE.
Referenced by imc_attestation_process().
 {
     if ((supported_dh_groups & PTS_DH_GROUP_IKE20) &&
         (offered_dh_groups   & PTS_DH_GROUP_IKE20))
     {
         return PTS_DH_GROUP_IKE20;
     }
     if ((supported_dh_groups & PTS_DH_GROUP_IKE19) &&
         (offered_dh_groups   & PTS_DH_GROUP_IKE19))
     {
         return PTS_DH_GROUP_IKE19;
     }
     if ((supported_dh_groups & PTS_DH_GROUP_IKE14) &&
         (offered_dh_groups   & PTS_DH_GROUP_IKE14))
     {
         return PTS_DH_GROUP_IKE14;
     }
     if ((supported_dh_groups & PTS_DH_GROUP_IKE5) &&
         (offered_dh_groups   & PTS_DH_GROUP_IKE5))
     {
         return PTS_DH_GROUP_IKE5;
     }
     if ((supported_dh_groups & PTS_DH_GROUP_IKE2) &&
         (offered_dh_groups   & PTS_DH_GROUP_IKE2))
     {
         return PTS_DH_GROUP_IKE2;
     }
     return PTS_DH_GROUP_NONE;
 }
diffie_hellman_group_t pts_dh_group_to_ike (pts_dh_group_t dh_group)
Convert pts_dh_group_t to diffie_hellman_group_t
Parameters
dh_group PTS DH group type
Returns
IKE DH group type
Described in header.
Definition at line 167 of file pts_dh_group.c.
References ECP_256_BIT, ECP_384_BIT, MODP_1024_BIT, MODP_1536_BIT, MODP_2048_BIT, MODP_NONE, PTS_DH_GROUP_IKE14, PTS_DH_GROUP_IKE19, PTS_DH_GROUP_IKE2, PTS_DH_GROUP_IKE20, and PTS_DH_GROUP_IKE5.
Referenced by METHOD().
 {
     switch (dh_group)
     {
         case PTS_DH_GROUP_IKE2:
             return MODP_1024_BIT;
         case PTS_DH_GROUP_IKE5:
             return MODP_1536_BIT;
         case PTS_DH_GROUP_IKE14:
             return MODP_2048_BIT;
         case PTS_DH_GROUP_IKE19:
             return ECP_256_BIT;
         case PTS_DH_GROUP_IKE20:
             return ECP_384_BIT;
         default:
             return MODP_NONE;
     }
 }
bool pts_dh_group_update (char * dh_group, pts_dh_group_t * dh_groups)
Update supported Diffie-Hellman groups according to configuration
modp1024: PTS_DH_GROUP_IKE2 modp1536: PTS_DH_GROUP_IKE2 | PTS_DH_GROUP_IKE5 modp2048: PTS_DH_GROUP_IKE2 | PTS_DH_GROUP_IKE5 | PTS_DH_GROUP_IKE14 ecp256: PTS_DH_GROUP_IKE2 | PTS_DH_GROUP_IKE5 | PTS_DH_GROUP_IKE14 | PTS_DH_GROUP_IKE19 ecp384: PTS_DH_GROUP_IKE2 | PTS_DH_GROUP_IKE5 | PTS_DH_GROUP_IKE14 | PTS_DH_GROUP_IKE19 | PTS_DH_GROUP_IKE20
The PTS-IMC is expected to select the strongest supported group
Parameters
dh_group configured DH group
dh_groups returns set of available DH groups
Described in header.
Definition at line 93 of file pts_dh_group.c.
References DBG1, DBG_PTS, FALSE, PTS_DH_GROUP_IKE14, PTS_DH_GROUP_IKE19, PTS_DH_GROUP_IKE20, PTS_DH_GROUP_IKE5, strcaseeq(), and TRUE.
Referenced by imv_attestation_agent_create().
 {
     if (strcaseeq(dh_group, "ecp384"))
     {
         /* nothing to update, all groups are supported */
         return TRUE;
     }
     if (strcaseeq(dh_group, "ecp256"))
     {
         /* remove DH group 20 */
         *dh_groups &= ~PTS_DH_GROUP_IKE20;
         return TRUE;
     }
     if (strcaseeq(dh_group, "modp2048"))
     {
         /* remove DH groups 19 and 20 */
         *dh_groups &= ~(PTS_DH_GROUP_IKE20 | PTS_DH_GROUP_IKE19);
         return TRUE;
     }
     if (strcaseeq(dh_group, "modp1536"))
     {
         /* remove DH groups 14, 19 and 20 */
         *dh_groups &= ~(PTS_DH_GROUP_IKE20 | PTS_DH_GROUP_IKE19 |
                         PTS_DH_GROUP_IKE14);
         return TRUE;
     }
     if (strcaseeq(dh_group, "modp1024"))
     {
         /* remove DH groups 5, 14, 19 and 20 */
         *dh_groups &= ~(PTS_DH_GROUP_IKE20 | PTS_DH_GROUP_IKE19 |
                         PTS_DH_GROUP_IKE14 | PTS_DH_GROUP_IKE5);
         return TRUE;
     }
     DBG1(DBG_PTS, "unknown DH group '%s' configured", dh_group);
     return FALSE;
 }