strongSwan: pb_remediation_parameters_msg
pb_remediation_parameters_msg
tnccs_20
Classes
struct pb_remediation_parameters_msg_t
Typedefs
typedef enum
pb_tnc_remed_param_type_t pb_tnc_remed_param_type_t
typedef struct
pb_remediation_parameters_msg_t pb_remediation_parameters_msg_t
Enumerations
enum pb_tnc_remed_param_type_t { PB_REMEDIATION_URI = 1, PB_REMEDIATION_STRING = 2 }
Functions
pb_tnc_msg_t * pb_remediation_parameters_msg_create (pen_type_t parameters_type, chunk_t parameters)
pb_tnc_msg_t * pb_remediation_parameters_msg_create_from_uri (chunk_t uri)
pb_tnc_msg_t * pb_remediation_parameters_msg_create_from_string (chunk_t string, chunk_t lang_code)
pb_tnc_msg_t * pb_remediation_parameters_msg_create_from_data (chunk_t data)
Variables
enum_name_t * pb_tnc_remed_param_type_names
Detailed Description
Typedef Documentation
typedef struct pb_remediation_parameters_msg_t pb_remediation_parameters_msg_t
Definition at line 25 of file pb_remediation_parameters_msg.h.
typedef enum pb_tnc_remed_param_type_t pb_tnc_remed_param_type_t
Definition at line 24 of file pb_remediation_parameters_msg.h.
Enumeration Type Documentation
enum pb_tnc_remed_param_type_t
PB-TNC Remediation Parameter Types as defined in section 4.8.1 of RFC 5793
Enumerator
PB_REMEDIATION_URI
PB_REMEDIATION_STRING
Definition at line 34 of file pb_remediation_parameters_msg.h.
{
     PB_REMEDIATION_URI =            1,
     PB_REMEDIATION_STRING =         2,
 };
Function Documentation
pb_tnc_msg_t* pb_remediation_parameters_msg_create (pen_type_t parameters_type, chunk_t parameters)
Create a general PB-Remediation-Parameters message
Parameters
parameters_type Remediation Parameters Type
parameters Remediation Parameters
See header
Definition at line 224 of file pb_remediation_parameters_msg.c.
References chunk_clone, INIT, PB_MSG_REMEDIATION_PARAMETERS, and PEN_IETF.
Referenced by pb_remediation_parameters_msg_create_from_string(), and pb_remediation_parameters_msg_create_from_uri().
 {
     private_pb_remediation_parameters_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .destroy = _destroy,
             },
             .get_parameters_type = _get_parameters_type,
             .get_parameters = _get_parameters,
             .get_uri = _get_parameters,
             .get_string = _get_string,
         },
         .type = { PEN_IETF, PB_MSG_REMEDIATION_PARAMETERS },
         .parameters_type = parameters_type,
         .parameters = chunk_clone(parameters),
     );
     return &this->public.pb_interface;
 }
pb_tnc_msg_t* pb_remediation_parameters_msg_create_from_data (chunk_t data)
Create an unprocessed PB-Remediation-Parameters message from raw data
Parameters
data PB-Remediation-Parameters message data
See header
Definition at line 287 of file pb_remediation_parameters_msg.c.
References chunk_clone, INIT, PB_MSG_REMEDIATION_PARAMETERS, and PEN_IETF.
Referenced by pb_tnc_msg_create_from_data().
 {
     private_pb_remediation_parameters_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .destroy = _destroy,
             },
             .get_parameters_type = _get_parameters_type,
             .get_parameters = _get_parameters,
             .get_uri = _get_parameters,
             .get_string = _get_string,
         },
         .type = { PEN_IETF, PB_MSG_REMEDIATION_PARAMETERS },
         .encoding = chunk_clone(data),
     );
     return &this->public.pb_interface;
 }
pb_tnc_msg_t* pb_remediation_parameters_msg_create_from_string (chunk_t string, chunk_t lang_code)
Create a PB-Remediation-Parameters message of IETF Type Remediation String
Parameters
string Remediation String
lang_code Remediation String Language Code
Described in header.
Definition at line 264 of file pb_remediation_parameters_msg.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::get_buf, chunk_t::len, len, min, msg, pb_remediation_parameters_msg_create(), PB_REMEDIATION_STRING, PEN_IETF, type, bio_writer_t::write_data32, and bio_writer_t::write_data8.
 {
     pb_tnc_msg_t *msg;
     bio_writer_t *writer;
     pen_type_t type = { PEN_IETF, PB_REMEDIATION_STRING };
     /* limit language code to 255 octets */
     lang_code.len = min(255, lang_code.len);
     writer = bio_writer_create(4 + string.len + 1 + lang_code.len);
     writer->write_data32(writer, string);
     writer->write_data8 (writer, lang_code);
     msg = pb_remediation_parameters_msg_create(type, writer->get_buf(writer));
     writer->destroy(writer);
     return msg;
 }
pb_tnc_msg_t* pb_remediation_parameters_msg_create_from_uri (chunk_t uri)
Create a PB-Remediation-Parameters message of IETF Type Remediation URI
Parameters
uri Remediation URI
Described in header.
Definition at line 254 of file pb_remediation_parameters_msg.c.
References pb_remediation_parameters_msg_create(), PB_REMEDIATION_URI, PEN_IETF, and type.
 {
     pen_type_t type = { PEN_IETF, PB_REMEDIATION_URI };
     return pb_remediation_parameters_msg_create(type, uri);
 }
Variable Documentation
enum_name_t* pb_tnc_remed_param_type_names
enum name for pb_tnc_remed_param_type_t.