strongSwan: ita_attr
ita_attr
libimcv
Modules
ita_attr_angel
ita_attr_command
ita_attr_dummy
ita_attr_get_settings
ita_attr_settings
Typedefs
typedef enum ita_attr_t ita_attr_t
Enumerations
enum ita_attr_t {
ITA_ATTR_COMMAND = 1, ITA_ATTR_DUMMY = 2, ITA_ATTR_GET_SETTINGS = 3, ITA_ATTR_SETTINGS = 4,
ITA_ATTR_START_ANGEL = 5, ITA_ATTR_STOP_ANGEL = 6, ITA_ATTR_ECHO = 7, ITA_ATTR_DEVICE_ID = 8
}
Functions
pa_tnc_attr_t * ita_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Variables
enum_name_t * ita_attr_names
Detailed Description
Typedef Documentation
typedef enum ita_attr_t ita_attr_t
Definition at line 28 of file ita_attr.h.
Enumeration Type Documentation
enum ita_attr_t
IETF standard PA-TNC attribute types defined by RFC 5792
Enumerator
ITA_ATTR_COMMAND
ITA_ATTR_DUMMY
ITA_ATTR_GET_SETTINGS
ITA_ATTR_SETTINGS
ITA_ATTR_START_ANGEL
ITA_ATTR_STOP_ANGEL
ITA_ATTR_ECHO
ITA_ATTR_DEVICE_ID
Definition at line 33 of file ita_attr.h.
                 {
     ITA_ATTR_COMMAND =  1,
     ITA_ATTR_DUMMY = 2,
     ITA_ATTR_GET_SETTINGS = 3,
     ITA_ATTR_SETTINGS = 4,
     ITA_ATTR_START_ANGEL = 5,
     ITA_ATTR_STOP_ANGEL = 6,
     ITA_ATTR_ECHO = 7,
     ITA_ATTR_DEVICE_ID = 8
 };
Function Documentation
pa_tnc_attr_t* ita_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Create a ITA PA-TNC attribute from data
Parameters
type attribute type
length attribute length
value attribute value or segment
See header
Definition at line 38 of file ita_attr.c.
References FALSE, generic_attr_string_create_from_data(), ita_attr_angel_create_from_data(), ITA_ATTR_COMMAND, ita_attr_command_create_from_data(), ITA_ATTR_DEVICE_ID, ITA_ATTR_DUMMY, ita_attr_dummy_create_from_data(), ITA_ATTR_GET_SETTINGS, ita_attr_get_settings_create_from_data(), ITA_ATTR_SETTINGS, ita_attr_settings_create_from_data(), ITA_ATTR_START_ANGEL, ITA_ATTR_STOP_ANGEL, PEN_ITA, pen_type_create(), and TRUE.
Referenced by libimcv_init().
 {
     switch (type)
     {
         case ITA_ATTR_COMMAND:
             return ita_attr_command_create_from_data(length, value);
         case ITA_ATTR_DUMMY:
             return ita_attr_dummy_create_from_data(length, value);
         case ITA_ATTR_GET_SETTINGS:
             return ita_attr_get_settings_create_from_data(length, value);
         case ITA_ATTR_SETTINGS:
             return ita_attr_settings_create_from_data(length, value);
         case ITA_ATTR_START_ANGEL:
             return ita_attr_angel_create_from_data(TRUE);
         case ITA_ATTR_STOP_ANGEL:
             return ita_attr_angel_create_from_data(FALSE);
         case ITA_ATTR_DEVICE_ID:
             return generic_attr_string_create_from_data(length, value,
                                     pen_type_create(PEN_ITA, type));
         default:
             return NULL;
     }
 }
Variable Documentation
enum_name_t* ita_attr_names
enum name for ita_attr_t.
Referenced by libimcv_init().