strongSwan: imv_os_info_t Struct Reference
imv_os_info_t Struct Reference
imv_os_info
#include "imv_os_info.h"
Public Attributes
os_type_t(* get_type)(imv_os_info_t *this)
void(* set_name)(imv_os_info_t *this, chunk_t name)
chunk_t(* get_name)(imv_os_info_t *this)
void(* set_version)(imv_os_info_t *this, chunk_t version)
chunk_t(* get_version)(imv_os_info_t *this)
char *(* get_info)(imv_os_info_t *this)
void(* destroy)(imv_os_info_t *this)
Detailed Description
Interface for the IMV Operating System (OS) information module
Definition at line 33 of file imv_os_info.h.
Member Data Documentation
void(* imv_os_info_t::destroy)(imv_os_info_t *this)
Destroys an imv_os_info_t object.
Definition at line 80 of file imv_os_info.h.
char*(* imv_os_info_t::get_info)(imv_os_info_t *this)
Get the OS version or release
Returns
OS name | OS version
Definition at line 75 of file imv_os_info.h.
Referenced by create_session(), and METHOD().
chunk_t(* imv_os_info_t::get_name)(imv_os_info_t *this)
Get the OS product name or distribution
Returns
OS name
Definition at line 54 of file imv_os_info.h.
os_type_t(* imv_os_info_t::get_type)(imv_os_info_t *this)
Get the OS type
Returns
OS type
Definition at line 40 of file imv_os_info.h.
Referenced by METHOD().
chunk_t(* imv_os_info_t::get_version)(imv_os_info_t *this)
Get the OS version or release
Returns
OS version
Definition at line 68 of file imv_os_info.h.
void(* imv_os_info_t::set_name)(imv_os_info_t *this, chunk_t name)
Set the OS product name or distribution
Parameters
name OS name
Definition at line 47 of file imv_os_info.h.
Referenced by receive_msg().
void(* imv_os_info_t::set_version)(imv_os_info_t *this, chunk_t version)
Set the OS version or release
Parameters
version OS version
Definition at line 61 of file imv_os_info.h.
Referenced by receive_msg().
The documentation for this struct was generated from the following file:
imv_os_info.h