strongSwan: stream_manager
stream_manager
streams
Classes
struct stream_manager_t
Typedefs
typedef struct stream_manager_t stream_manager_t
Functions
stream_manager_t * stream_manager_create ()
Detailed Description
Typedef Documentation
typedef struct stream_manager_t stream_manager_t
Definition at line 24 of file stream_manager.h.
Function Documentation
stream_manager_t* stream_manager_create ()
Create a stream_manager instance.
See header
Definition at line 219 of file stream_manager.c.
References INIT, linked_list_create(), rwlock_create(), RWLOCK_TYPE_DEFAULT, stream_create_tcp(), stream_create_unix(), stream_service_create_tcp(), and stream_service_create_unix().
Referenced by library_init().
 {
     private_stream_manager_t *this;
     INIT(this,
         .public = {
             .connect = _connect_,
             .create_service = _create_service,
             .add_stream = _add_stream,
             .remove_stream = _remove_stream,
             .add_service = _add_service,
             .remove_service = _remove_service,
             .destroy = _destroy,
         },
         .streams = linked_list_create(),
         .services = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     add_stream(this, "tcp://", stream_create_tcp);
     add_service(this, "tcp://", stream_service_create_tcp);
 #ifndef WIN32
     add_stream(this, "unix://", stream_create_unix);
     add_service(this, "unix://", stream_service_create_unix);
 #endif
     return &this->public;
 }