strongSwan: starterstroke.h File Reference
starterstroke.h File Reference
#include "confread.h"
Functions
int starter_stroke_add_conn (starter_config_t *cfg, starter_conn_t *conn)
int starter_stroke_del_conn (starter_conn_t *conn)
int starter_stroke_route_conn (starter_conn_t *conn)
int starter_stroke_unroute_conn (starter_conn_t *conn)
int starter_stroke_initiate_conn (starter_conn_t *conn)
int starter_stroke_add_ca (starter_ca_t *ca)
int starter_stroke_del_ca (starter_ca_t *ca)
int starter_stroke_configure (starter_config_t *cfg)
Function Documentation
int starter_stroke_add_ca (starter_ca_t * ca)
Definition at line 319 of file starterstroke.c.
References starter_ca::cacert, stroke_msg_t::cacert, starter_ca::certuribase, stroke_msg_t::certuribase, create_stroke_msg(), starter_ca::crluri, stroke_msg_t::crluri, starter_ca::crluri2, stroke_msg_t::crluri2, msg, starter_ca::name, stroke_msg_t::name, starter_ca::ocspuri, stroke_msg_t::ocspuri, starter_ca::ocspuri2, stroke_msg_t::ocspuri2, push_string, and send_stroke_msg().
Referenced by main().
 {
     stroke_msg_t *msg;
     msg = create_stroke_msg(STR_ADD_CA);
     push_string(&msg, add_ca.name, ca->name);
     push_string(&msg, add_ca.cacert, ca->cacert);
     push_string(&msg, add_ca.crluri, ca->crluri);
     push_string(&msg, add_ca.crluri2, ca->crluri2);
     push_string(&msg, add_ca.ocspuri, ca->ocspuri);
     push_string(&msg, add_ca.ocspuri2, ca->ocspuri2);
     push_string(&msg, add_ca.certuribase, ca->certuribase);
     return send_stroke_msg(msg);
 }
int starter_stroke_add_conn (starter_config_t * cfg, starter_conn_t * conn)
Definition at line 178 of file starterstroke.c.
References starter_conn::aaa_identity, stroke_msg_t::aaa_identity, stroke_msg_t::add_conn, add_end(), starter_conn::aggressive, starter_conn::ah, stroke_msg_t::algorithms, stroke_end_t::auth, stroke_end_t::auth2, starter_conn::authby, starter_conn::close_action, connection_name(), create_stroke_msg(), starter_conn::dpd_action, starter_conn::dpd_delay, starter_conn::dpd_timeout, starter_conn::eap_identity, stroke_msg_t::eap_identity, starter_conn::esp, starter_conn::fragmentation, starter_conn::ike, starter_conn::ikedscp, stroke_msg_t::ikeme, starter_conn::inactivity, starter_conn::install_policy, starter_conn::keyexchange, starter_conn::left, starter_conn::mark_in, starter_conn::mark_out, mark_t::mask, stroke_msg_t::me, starter_conn::me_mediated_by, starter_conn::me_mediation, starter_conn::me_peerid, starter_conn::mode, msg, stroke_msg_t::name, starter_conn::options, stroke_msg_t::other, starter_conn::proxy_mode, push_string, starter_conn::replay_window, starter_conn::reqid, starter_conn::right, starter_conn::sa_ike_life_seconds, starter_conn::sa_ipsec_life_bytes, starter_conn::sa_ipsec_life_packets, starter_conn::sa_ipsec_life_seconds, starter_conn::sa_ipsec_margin_bytes, starter_conn::sa_ipsec_margin_packets, starter_conn::sa_keying_tries, SA_OPTION_COMPRESS, SA_OPTION_DONT_REAUTH, SA_OPTION_DONT_REKEY, SA_OPTION_FORCE_ENCAP, SA_OPTION_MOBIKE, SA_OPTION_MODECFG_PUSH, SA_OPTION_XAUTH_SERVER, starter_conn::sa_rekey_fuzz, starter_conn::sa_rekey_margin, send_stroke_msg(), starter_config::setup, streq(), starter_config::strictcrlpolicy, starter_conn::tfc, starter_config::uniqueids, mark_t::value, starter_conn::xauth_identity, and stroke_msg_t::xauth_identity.
Referenced by main().
 {
     stroke_msg_t *msg;
     msg = create_stroke_msg(STR_ADD_CONN);
     msg->add_conn.version = conn->keyexchange;
     push_string(&msg, add_conn.name, connection_name(conn));
     push_string(&msg, add_conn.eap_identity, conn->eap_identity);
     push_string(&msg, add_conn.aaa_identity, conn->aaa_identity);
     push_string(&msg, add_conn.xauth_identity, conn->xauth_identity);
     msg->add_conn.mode = conn->mode;
     msg->add_conn.proxy_mode = conn->proxy_mode;
     if (!(conn->options & SA_OPTION_DONT_REKEY))
     {
         msg->add_conn.rekey.reauth = !(conn->options & SA_OPTION_DONT_REAUTH);
         msg->add_conn.rekey.ipsec_lifetime = conn->sa_ipsec_life_seconds;
         msg->add_conn.rekey.ike_lifetime = conn->sa_ike_life_seconds;
         msg->add_conn.rekey.margin = conn->sa_rekey_margin;
         msg->add_conn.rekey.life_bytes = conn->sa_ipsec_life_bytes;
         msg->add_conn.rekey.margin_bytes = conn->sa_ipsec_margin_bytes;
         msg->add_conn.rekey.life_packets = conn->sa_ipsec_life_packets;
         msg->add_conn.rekey.margin_packets = conn->sa_ipsec_margin_packets;
         msg->add_conn.rekey.fuzz = conn->sa_rekey_fuzz;
     }
     msg->add_conn.rekey.tries = conn->sa_keying_tries;
     msg->add_conn.mobike = conn->options & SA_OPTION_MOBIKE;
     msg->add_conn.force_encap = conn->options & SA_OPTION_FORCE_ENCAP;
     msg->add_conn.fragmentation = conn->fragmentation;
     msg->add_conn.ikedscp = conn->ikedscp;
     msg->add_conn.ipcomp = conn->options & SA_OPTION_COMPRESS;
     msg->add_conn.install_policy = conn->install_policy;
     msg->add_conn.aggressive = conn->aggressive;
     msg->add_conn.pushmode = conn->options & SA_OPTION_MODECFG_PUSH;
     msg->add_conn.crl_policy = (crl_policy_t)cfg->setup.strictcrlpolicy;
     msg->add_conn.unique = cfg->setup.uniqueids;
     push_string(&msg, add_conn.algorithms.ike, conn->ike);
     push_string(&msg, add_conn.algorithms.esp, conn->esp);
     push_string(&msg, add_conn.algorithms.ah, conn->ah);
     msg->add_conn.dpd.delay = conn->dpd_delay;
     msg->add_conn.dpd.timeout = conn->dpd_timeout;
     msg->add_conn.dpd.action = conn->dpd_action;
     msg->add_conn.close_action = conn->close_action;
     msg->add_conn.inactivity = conn->inactivity;
     msg->add_conn.ikeme.mediation = conn->me_mediation;
     push_string(&msg, add_conn.ikeme.mediated_by, conn->me_mediated_by);
     push_string(&msg, add_conn.ikeme.peerid, conn->me_peerid);
     msg->add_conn.reqid = conn->reqid;
     msg->add_conn.replay_window = conn->replay_window;
     msg->add_conn.mark_in.value = conn->mark_in.value;
     msg->add_conn.mark_in.mask = conn->mark_in.mask;
     msg->add_conn.mark_out.value = conn->mark_out.value;
     msg->add_conn.mark_out.mask = conn->mark_out.mask;
     msg->add_conn.tfc = conn->tfc;
     add_end(&msg, offsetof(stroke_msg_t, add_conn.me), &conn->left);
     add_end(&msg, offsetof(stroke_msg_t, add_conn.other), &conn->right);
     if (!msg->add_conn.me.auth && !msg->add_conn.other.auth &&
          conn->authby)
     {   /* leftauth/rightauth not set, use legacy options */
         if (streq(conn->authby, "rsa")   || streq(conn->authby, "rsasig")   ||
             streq(conn->authby, "ecdsa") || streq(conn->authby, "ecdsasig") ||
             streq(conn->authby, "pubkey"))
         {
             push_string(&msg, add_conn.me.auth, "pubkey");
             push_string(&msg, add_conn.other.auth, "pubkey");
         }
         else if (streq(conn->authby, "secret") || streq(conn->authby, "psk"))
         {
             push_string(&msg, add_conn.me.auth, "psk");
             push_string(&msg, add_conn.other.auth, "psk");
         }
         else if (streq(conn->authby, "xauthrsasig"))
         {
             push_string(&msg, add_conn.me.auth, "pubkey");
             push_string(&msg, add_conn.other.auth, "pubkey");
             if (conn->options & SA_OPTION_XAUTH_SERVER)
             {
                 push_string(&msg, add_conn.other.auth2, "xauth");
             }
             else
             {
                 push_string(&msg, add_conn.me.auth2, "xauth");
             }
         }
         else if (streq(conn->authby, "xauthpsk"))
         {
             push_string(&msg, add_conn.me.auth, "psk");
             push_string(&msg, add_conn.other.auth, "psk");
             if (conn->options & SA_OPTION_XAUTH_SERVER)
             {
                 push_string(&msg, add_conn.other.auth2, "xauth");
             }
             else
             {
                 push_string(&msg, add_conn.me.auth2, "xauth");
             }
         }
     }
     return send_stroke_msg(msg);
 }
int starter_stroke_configure (starter_config_t * cfg)
Definition at line 343 of file starterstroke.c.
References starter_config::cachecrls, stroke_msg_t::config, create_stroke_msg(), msg, send_stroke_msg(), and starter_config::setup.
Referenced by main().
 {
     stroke_msg_t *msg;
     if (cfg->setup.cachecrls)
     {
         msg = create_stroke_msg(STR_CONFIG);
         msg->config.cachecrl = 1;
         return send_stroke_msg(msg);
     }
     return 0;
 }
int starter_stroke_del_ca (starter_ca_t * ca)
Definition at line 334 of file starterstroke.c.
References create_stroke_msg(), msg, starter_ca::name, stroke_msg_t::name, push_string, and send_stroke_msg().
Referenced by main().
 {
     stroke_msg_t *msg;
     msg = create_stroke_msg(STR_DEL_CA);
     push_string(&msg, del_ca.name, ca->name);
     return send_stroke_msg(msg);
 }
int starter_stroke_del_conn (starter_conn_t * conn)
Definition at line 283 of file starterstroke.c.
References connection_name(), create_stroke_msg(), msg, stroke_msg_t::name, push_string, and send_stroke_msg().
Referenced by main().
 {
     stroke_msg_t *msg;
     msg = create_stroke_msg(STR_DEL_CONN);
     push_string(&msg, del_conn.name, connection_name(conn));
     return send_stroke_msg(msg);
 }
int starter_stroke_initiate_conn (starter_conn_t * conn)
Definition at line 310 of file starterstroke.c.
References connection_name(), create_stroke_msg(), initiate(), msg, push_string, and send_stroke_msg().
Referenced by main().
 {
     stroke_msg_t *msg;
     msg = create_stroke_msg(STR_INITIATE);
     push_string(&msg, initiate.name, connection_name(conn));
     return send_stroke_msg(msg);
 }
int starter_stroke_route_conn (starter_conn_t * conn)
Definition at line 292 of file starterstroke.c.
References connection_name(), create_stroke_msg(), msg, stroke_msg_t::name, push_string, and send_stroke_msg().
Referenced by main().
 {
     stroke_msg_t *msg;
     msg = create_stroke_msg(STR_ROUTE);
     push_string(&msg, route.name, connection_name(conn));
     return send_stroke_msg(msg);
 }
int starter_stroke_unroute_conn (starter_conn_t * conn)
Definition at line 301 of file starterstroke.c.
References connection_name(), create_stroke_msg(), msg, stroke_msg_t::name, push_string, and send_stroke_msg().
Referenced by main().
 {
     stroke_msg_t *msg;
     msg = create_stroke_msg(STR_UNROUTE);
     push_string(&msg, route.name, connection_name(conn));
     return send_stroke_msg(msg);
 }