strongSwan: set_proposal_number.c File Reference
set_proposal_number.c File Reference
#include "hook.h"
#include <encoding/payloads/sa_payload.h>
Classes
struct private_set_proposal_number_t
Typedefs
typedef struct
private_set_proposal_number_t private_set_proposal_number_t
Functions
static void copy_proposal_algs (proposal_t *from, proposal_t *to, transform_type_t type)
METHOD (listener_t, message, bool, private_set_proposal_number_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (hook_t, destroy, void, private_set_proposal_number_t *this)
hook_t * set_proposal_number_hook_create (char *name)
Typedef Documentation
typedef struct private_set_proposal_number_t private_set_proposal_number_t
Definition at line 20 of file set_proposal_number.c.
Function Documentation
static void copy_proposal_algs (proposal_t * from, proposal_t * to, transform_type_t type) static
Copy all algs from given type from one proposal to another
Definition at line 56 of file set_proposal_number.c.
References proposal_t::add_algorithm, alg, proposal_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, and key_size.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     u_int16_t alg, key_size;
     enumerator = from->create_enumerator(from, type);
     while (enumerator->enumerate(enumerator, &alg, &key_size))
     {
         to->add_algorithm(to, type, alg, key_size);
     }
     enumerator->destroy(enumerator);
 }
METHOD (listener_t , message , bool , private_set_proposal_number_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 70 of file set_proposal_number.c.
References message_t::add_payload, copy_proposal_algs(), linked_list_t::create_enumerator, message_t::create_payload_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, sa_payload_t::destroy, destroy(), linked_list_t::destroy_offset, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, enumerator_t::enumerate, EXTENDED_SEQUENCE_NUMBERS, from, message_t::get_message_id, proposal_t::get_number, sa_payload_t::get_proposals, proposal_t::get_protocol, message_t::get_request, payload_t::get_type, id, INTEGRITY_ALGORITHM, linked_list_create(), list, PLV2_SECURITY_ASSOCIATION, proposal, proposal_create(), PSEUDO_RANDOM_FUNCTION, linked_list_t::remove_at, message_t::remove_payload_at, req(), sa, sa_payload_create_from_proposals_v2(), to, and TRUE.
 {
     if (!incoming && plain &&
         message->get_request(message) == this->req &&
         message->get_message_id(message) == this->id)
     {
         enumerator_t *enumerator;
         payload_t *payload;
         linked_list_t *list = NULL, *updated;
         sa_payload_t *sa;
         proposal_t *proposal, *new;
         updated = linked_list_create();
         enumerator = message->create_payload_enumerator(message);
         while (enumerator->enumerate(enumerator, &payload))
         {
             if (payload->get_type(payload) == PLV2_SECURITY_ASSOCIATION)
             {
                 sa = (sa_payload_t*)payload;
                 list = sa->get_proposals(sa);
                 message->remove_payload_at(message, enumerator);
                 sa->destroy(sa);
             }
         }
         enumerator->destroy(enumerator);
         if (list)
         {
             enumerator = list->create_enumerator(list);
             while (enumerator->enumerate(enumerator, &proposal))
             {
                 if (proposal->get_number(proposal) == this->from)
                 {
                     DBG1(DBG_CFG, "setting proposal number from %d to %d",
                          this->from, this->to);
                     new = proposal_create(proposal->get_protocol(proposal),
                                           this->to);
                     copy_proposal_algs(proposal, new, ENCRYPTION_ALGORITHM);
                     copy_proposal_algs(proposal, new, INTEGRITY_ALGORITHM);
                     copy_proposal_algs(proposal, new, PSEUDO_RANDOM_FUNCTION);
                     copy_proposal_algs(proposal, new, DIFFIE_HELLMAN_GROUP);
                     copy_proposal_algs(proposal, new, EXTENDED_SEQUENCE_NUMBERS);
                     updated->insert_last(updated, new);
                 }
                 else
                 {
                     list->remove_at(list, enumerator);
                     updated->insert_last(updated, proposal);
                 }
             }
             enumerator->destroy(enumerator);
         }
         sa = sa_payload_create_from_proposals_v2(updated);
         list->destroy_offset(list, offsetof(proposal_t, destroy));
         updated->destroy_offset(updated, offsetof(proposal_t, destroy));
         message->add_payload(message, (payload_t*)sa);
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_set_proposal_number_t * this)
Definition at line 132 of file set_proposal_number.c.
References free().
 {
     free(this);
 }
hook_t* set_proposal_number_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 141 of file set_proposal_number.c.
References conftest, settings_t::get_bool, settings_t::get_int, INIT, conftest_t::test, and TRUE.
 {
     private_set_proposal_number_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .message = _message,
             },
             .destroy = _destroy,
         },
         .req = conftest->test->get_bool(conftest->test,
                                         "hooks.%s.request", TRUE, name),
         .id = conftest->test->get_int(conftest->test,
                                         "hooks.%s.id", 0, name),
         .from = conftest->test->get_int(conftest->test,
                                         "hooks.%s.from", 0, name),
         .to = conftest->test->get_int(conftest->test,
                                         "hooks.%s.to", 1, name),
     );
     return &this->hook;
 }