strongSwan: vici_builder
vici_builder
vici
Classes
struct vici_builder_t
Typedefs
typedef struct vici_builder_t vici_builder_t
Functions
vici_builder_t * vici_builder_create ()
Detailed Description
Typedef Documentation
typedef struct vici_builder_t vici_builder_t
Definition at line 26 of file vici_builder.h.
Function Documentation
vici_builder_t* vici_builder_create ()
Create a vici_builder instance.
See header
Definition at line 260 of file vici_builder.c.
References bio_writer_create(), and INIT.
Referenced by CALLBACK(), create_reply(), log_vici(), METHOD(), raise_policy(), raise_policy_cfg(), send_reply(), START_TEST(), vici_begin(), vici_message_create_from_args(), and vici_message_create_from_enumerator().
 {
     private_vici_builder_t *this;
     INIT(this,
         .public = {
             .add = _add,
             .add_kv = _add_kv,
             .vadd_kv = _vadd_kv,
             .add_li = _add_li,
             .vadd_li = _vadd_li,
             .begin_section = _begin_section,
             .end_section = _end_section,
             .begin_list = _begin_list,
             .end_list = _end_list,
             .finalize = _finalize,
             .destroy = _destroy,
         },
         .writer = bio_writer_create(0),
     );
     return &this->public;
 }