strongSwan: kernel_interface.c File Reference
kernel_interface.c File Reference
#include "kernel_interface.h"
#include <hydra.h>
#include <utils/debug.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include <collections/hashtable.h>
#include <collections/array.h>
Classes
struct kernel_algorithm_t
struct private_kernel_interface_t
struct reqid_entry_t
Typedefs
typedef struct
private_kernel_interface_t private_kernel_interface_t
typedef struct kernel_algorithm_t kernel_algorithm_t
Functions
METHOD (kernel_interface_t, get_features, kernel_feature_t, private_kernel_interface_t *this)
METHOD (kernel_interface_t, get_spi, status_t, private_kernel_interface_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
METHOD (kernel_interface_t, get_cpi, status_t, private_kernel_interface_t *this, host_t *src, host_t *dst, u_int16_t *cpi)
static void reqid_entry_destroy (reqid_entry_t *entry)
static u_int hash_reqid (reqid_entry_t *entry)
static bool equals_reqid (reqid_entry_t *a, reqid_entry_t *b)
static u_int hash_ts_array (array_t *array, u_int hash)
static u_int hash_reqid_by_ts (reqid_entry_t *entry)
static bool ts_array_equals (array_t *a, array_t *b)
static bool equals_reqid_by_ts (reqid_entry_t *a, reqid_entry_t *b)
static array_t * array_from_ts_list (linked_list_t *list)
METHOD (kernel_interface_t, alloc_reqid, status_t, private_kernel_interface_t *this, linked_list_t *local_ts, linked_list_t *remote_ts, mark_t mark_in, mark_t mark_out, u_int32_t *reqid)
METHOD (kernel_interface_t, release_reqid, status_t, private_kernel_interface_t *this, u_int32_t reqid, mark_t mark_in, mark_t mark_out)
METHOD (kernel_interface_t, add_sa, status_t, private_kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t *src_ts, linked_list_t *dst_ts)
METHOD (kernel_interface_t, update_sa, status_t, private_kernel_interface_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
METHOD (kernel_interface_t, query_sa, status_t, private_kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
METHOD (kernel_interface_t, del_sa, status_t, private_kernel_interface_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
METHOD (kernel_interface_t, flush_sas, status_t, private_kernel_interface_t *this)
METHOD (kernel_interface_t, add_policy, status_t, private_kernel_interface_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_interface_t, query_policy, status_t, private_kernel_interface_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, mark_t mark, time_t *use_time)
METHOD (kernel_interface_t, del_policy, status_t, private_kernel_interface_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_interface_t, flush_policies, status_t, private_kernel_interface_t *this)
METHOD (kernel_interface_t, get_source_addr, host_t *, private_kernel_interface_t *this, host_t *dest, host_t *src)
METHOD (kernel_interface_t, get_nexthop, host_t *, private_kernel_interface_t *this, host_t *dest, int prefix, host_t *src)
METHOD (kernel_interface_t, get_interface, bool, private_kernel_interface_t *this, host_t *host, char **name)
METHOD (kernel_interface_t, create_address_enumerator, enumerator_t *, private_kernel_interface_t *this, kernel_address_type_t which)
METHOD (kernel_interface_t, add_ip, status_t, private_kernel_interface_t *this, host_t *virtual_ip, int prefix, char *iface)
METHOD (kernel_interface_t, del_ip, status_t, private_kernel_interface_t *this, host_t *virtual_ip, int prefix, bool wait)
METHOD (kernel_interface_t, add_route, status_t, private_kernel_interface_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
METHOD (kernel_interface_t, del_route, status_t, private_kernel_interface_t *this, chunk_t dst_net, u_int8_t prefixlen, host_t *gateway, host_t *src_ip, char *if_name)
METHOD (kernel_interface_t, bypass_socket, bool, private_kernel_interface_t *this, int fd, int family)
METHOD (kernel_interface_t, enable_udp_decap, bool, private_kernel_interface_t *this, int fd, int family, u_int16_t port)
METHOD (kernel_interface_t, is_interface_usable, bool, private_kernel_interface_t *this, const char *iface)
METHOD (kernel_interface_t, all_interfaces_usable, bool, private_kernel_interface_t *this)
METHOD (kernel_interface_t, get_address_by_ts, status_t, private_kernel_interface_t *this, traffic_selector_t *ts, host_t **ip, bool *vip)
METHOD (kernel_interface_t, add_ipsec_interface, bool, private_kernel_interface_t *this, kernel_ipsec_constructor_t constructor)
METHOD (kernel_interface_t, remove_ipsec_interface, bool, private_kernel_interface_t *this, kernel_ipsec_constructor_t constructor)
METHOD (kernel_interface_t, add_net_interface, bool, private_kernel_interface_t *this, kernel_net_constructor_t constructor)
METHOD (kernel_interface_t, remove_net_interface, bool, private_kernel_interface_t *this, kernel_net_constructor_t constructor)
METHOD (kernel_interface_t, add_listener, void, private_kernel_interface_t *this, kernel_listener_t *listener)
METHOD (kernel_interface_t, remove_listener, void, private_kernel_interface_t *this, kernel_listener_t *listener)
METHOD (kernel_interface_t, acquire, void, private_kernel_interface_t *this, u_int32_t reqid, traffic_selector_t *src_ts, traffic_selector_t *dst_ts)
METHOD (kernel_interface_t, expire, void, private_kernel_interface_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, bool hard)
METHOD (kernel_interface_t, mapping, void, private_kernel_interface_t *this, u_int8_t protocol, u_int32_t spi, host_t *dst, host_t *remote)
METHOD (kernel_interface_t, migrate, void, private_kernel_interface_t *this, u_int32_t reqid, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, host_t *local, host_t *remote)
static bool call_roam (kernel_listener_t *listener, bool *roam)
METHOD (kernel_interface_t, roam, void, private_kernel_interface_t *this, bool address)
METHOD (kernel_interface_t, tun, void, private_kernel_interface_t *this, tun_device_t *tun, bool created)
METHOD (kernel_interface_t, register_algorithm, void, private_kernel_interface_t *this, u_int16_t alg_id, transform_type_t type, u_int16_t kernel_id, char *kernel_name)
METHOD (kernel_interface_t, lookup_algorithm, bool, private_kernel_interface_t *this, u_int16_t alg_id, transform_type_t type, u_int16_t *kernel_id, char **kernel_name)
METHOD (kernel_interface_t, destroy, void, private_kernel_interface_t *this)
kernel_interface_t * kernel_interface_create ()
Typedef Documentation
typedef struct kernel_algorithm_t kernel_algorithm_t
Definition at line 51 of file kernel_interface.c.
typedef struct private_kernel_interface_t private_kernel_interface_t
Definition at line 49 of file kernel_interface.c.
Function Documentation
static array_t* array_from_ts_list (linked_list_t * list) static
Create an array from copied traffic selector list items
Definition at line 310 of file kernel_interface.c.
References array_create(), array_insert(), ARRAY_TAIL, traffic_selector_t::clone, linked_list_t::create_enumerator, enumerator_t::destroy, and enumerator_t::enumerate.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     array_t *array;
     array = array_create(0, 0);
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &ts))
     {
         array_insert(array, ARRAY_TAIL, ts->clone(ts));
     }
     enumerator->destroy(enumerator);
     return array;
 }
static bool call_roam (kernel_listener_t * listener, bool * roam) static
Definition at line 890 of file kernel_interface.c.
References kernel_listener_t::roam.
Referenced by METHOD().
 {
     return listener->roam && !listener->roam(listener, *roam);
 }
static bool equals_reqid (reqid_entry_t * a, reqid_entry_t * b) static
Hashtable equals function for reqid entries using reqid as key
Definition at line 231 of file kernel_interface.c.
References reqid_entry_t::mark_in, reqid_entry_t::mark_out, mark_t::mask, reqid_entry_t::reqid, and mark_t::value.
Referenced by kernel_interface_create().
 {
     return a->reqid == b->reqid &&
            a->mark_in.value == b->mark_in.value &&
            a->mark_in.mask == b->mark_in.mask &&
            a->mark_out.value == b->mark_out.value &&
            a->mark_out.mask == b->mark_out.mask;
 }
static bool equals_reqid_by_ts (reqid_entry_t * a, reqid_entry_t * b) static
Hashtable equals function for reqid entries using traffic selectors as key
Definition at line 297 of file kernel_interface.c.
References reqid_entry_t::local, reqid_entry_t::mark_in, reqid_entry_t::mark_out, mark_t::mask, reqid_entry_t::remote, ts_array_equals(), and mark_t::value.
Referenced by kernel_interface_create().
 {
     return ts_array_equals(a->local, b->local) &&
            ts_array_equals(a->remote, b->remote) &&
            a->mark_in.value == b->mark_in.value &&
            a->mark_in.mask == b->mark_in.mask &&
            a->mark_out.value == b->mark_out.value &&
            a->mark_out.mask == b->mark_out.mask;
 }
static u_int hash_reqid (reqid_entry_t * entry) static
Hashtable hash function for reqid entries using reqid as key
Definition at line 221 of file kernel_interface.c.
References chunk_from_thing, chunk_hash(), chunk_hash_inc(), reqid_entry_t::mark_in, reqid_entry_t::mark_out, and reqid_entry_t::reqid.
Referenced by kernel_interface_create().
 {
     return chunk_hash_inc(chunk_from_thing(entry->reqid),
                 chunk_hash_inc(chunk_from_thing(entry->mark_in),
                     chunk_hash(chunk_from_thing(entry->mark_out))));
 }
static u_int hash_reqid_by_ts (reqid_entry_t * entry) static
Hashtable hash function for reqid entries using traffic selectors as key
Definition at line 261 of file kernel_interface.c.
References chunk_from_thing, chunk_hash(), chunk_hash_inc(), hash_ts_array(), reqid_entry_t::local, reqid_entry_t::mark_in, reqid_entry_t::mark_out, and reqid_entry_t::remote.
Referenced by kernel_interface_create().
 {
     return hash_ts_array(entry->local, hash_ts_array(entry->remote,
             chunk_hash_inc(chunk_from_thing(entry->mark_in),
                 chunk_hash(chunk_from_thing(entry->mark_out)))));
 }
static u_int hash_ts_array (array_t * array, u_int hash) static
Hash an array of traffic selectors
Definition at line 243 of file kernel_interface.c.
References array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, traffic_selector_t::hash, and hash.
Referenced by hash_reqid_by_ts().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     enumerator = array_create_enumerator(array);
     while (enumerator->enumerate(enumerator, &ts))
     {
         hash = ts->hash(ts, hash);
     }
     enumerator->destroy(enumerator);
     return hash;
 }
METHOD (kernel_interface_t , get_features , kernel_feature_t , private_kernel_interface_t * this)
Definition at line 152 of file kernel_interface.c.
References features, ipsec, and net.
 {
     kernel_feature_t features = 0;
     if (this->ipsec && this->ipsec->get_features)
     {
         features |= this->ipsec->get_features(this->ipsec);
     }
     if (this->net && this->net->get_features)
     {
         features |= this->net->get_features(this->net);
     }
     return features;
 }
METHOD (kernel_interface_t , get_spi , status_t , private_kernel_interface_t * this, host_t * src, host_t * dst, u_int8_t protocol, u_int32_t * spi)
Definition at line 168 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->get_spi(this->ipsec, src, dst, protocol, spi);
 }
METHOD (kernel_interface_t , get_cpi , status_t , private_kernel_interface_t * this, host_t * src, host_t * dst, u_int16_t * cpi)
Definition at line 179 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->get_cpi(this->ipsec, src, dst, cpi);
 }
METHOD (kernel_interface_t , alloc_reqid , status_t , private_kernel_interface_t * this, linked_list_t * local_ts, linked_list_t * remote_ts, mark_t mark_in, mark_t mark_out, u_int32_t * reqid)
Definition at line 328 of file kernel_interface.c.
References array_from_ts_list(), INIT, mutex_t::lock, mutex, reqid_entry_t::refs, reqid_entry_t::reqid, reqid_entry_destroy(), status, SUCCESS, and mutex_t::unlock.
 {
     static u_int32_t counter = 0;
     reqid_entry_t *entry = NULL, *tmpl;
     status_t status = SUCCESS;
     INIT(tmpl,
         .local = array_from_ts_list(local_ts),
         .remote = array_from_ts_list(remote_ts),
         .mark_in = mark_in,
         .mark_out = mark_out,
         .reqid = *reqid,
     );
     this->mutex->lock(this->mutex);
     if (tmpl->reqid)
     {
         /* search by reqid if given */
         entry = this->reqids->get(this->reqids, tmpl);
     }
     if (entry)
     {
         /* we don't require a traffic selector match for explicit reqids,
          * as we wan't to reuse a reqid for trap-triggered policies that
          * got narrowed during negotiation. */
         reqid_entry_destroy(tmpl);
     }
     else
     {
         /* search by traffic selectors */
         entry = this->reqids_by_ts->get(this->reqids_by_ts, tmpl);
         if (entry)
         {
             reqid_entry_destroy(tmpl);
         }
         else
         {
             /* none found, create a new entry, allocating a reqid */
             entry = tmpl;
             entry->reqid = ++counter;
             this->reqids_by_ts->put(this->reqids_by_ts, entry, entry);
             this->reqids->put(this->reqids, entry, entry);
         }
         *reqid = entry->reqid;
     }
     entry->refs++;
     this->mutex->unlock(this->mutex);
     return status;
 }
METHOD (kernel_interface_t , release_reqid , status_t , private_kernel_interface_t * this, u_int32_t reqid, mark_t mark_in, mark_t mark_out)
Definition at line 382 of file kernel_interface.c.
References mutex_t::lock, mutex, NOT_FOUND, reqid_entry_t::refs, reqid_entry_t::reqid, reqid_entry_destroy(), SUCCESS, and mutex_t::unlock.
 {
     reqid_entry_t *entry, tmpl = {
         .reqid = reqid,
         .mark_in = mark_in,
         .mark_out = mark_out,
     };
     this->mutex->lock(this->mutex);
     entry = this->reqids->remove(this->reqids, &tmpl);
     if (entry)
     {
         if (--entry->refs == 0)
         {
             entry = this->reqids_by_ts->remove(this->reqids_by_ts, entry);
             if (entry)
             {
                 reqid_entry_destroy(entry);
             }
         }
         else
         {
             this->reqids->put(this->reqids, entry, entry);
         }
     }
     this->mutex->unlock(this->mutex);
     if (entry)
     {
         return SUCCESS;
     }
     return NOT_FOUND;
 }
METHOD (kernel_interface_t , add_sa , status_t , private_kernel_interface_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t * lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t * src_ts, linked_list_t * dst_ts)
Definition at line 418 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->add_sa(this->ipsec, src, dst, spi, protocol, reqid,
                 mark, tfc, lifetime, enc_alg, enc_key, int_alg, int_key, mode,
                 ipcomp, cpi, replay_window, initiator, encap, esn, inbound,
                 update, src_ts, dst_ts);
 }
METHOD (kernel_interface_t , update_sa , status_t , private_kernel_interface_t * this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t * src, host_t * dst, host_t * new_src, host_t * new_dst, bool encap, bool new_encap, mark_t mark)
Definition at line 437 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->update_sa(this->ipsec, spi, protocol, cpi, src, dst,
                                   new_src, new_dst, encap, new_encap, mark);
 }
METHOD (kernel_interface_t , query_sa , status_t , private_kernel_interface_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t * bytes, u_int64_t * packets, time_t * time)
Definition at line 450 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->query_sa(this->ipsec, src, dst, spi, protocol, mark,
                                  bytes, packets, time);
 }
METHOD (kernel_interface_t , del_sa , status_t , private_kernel_interface_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Definition at line 463 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->del_sa(this->ipsec, src, dst, spi, protocol, cpi, mark);
 }
METHOD (kernel_interface_t , flush_sas , status_t , private_kernel_interface_t * this)
Definition at line 474 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->flush_sas(this->ipsec);
 }
METHOD (kernel_interface_t , add_policy , status_t , private_kernel_interface_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 484 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->add_policy(this->ipsec, src, dst, src_ts, dst_ts,
                                    direction, type, sa, mark, priority);
 }
METHOD (kernel_interface_t , query_policy , status_t , private_kernel_interface_t * this, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, mark_t mark, time_t * use_time)
Definition at line 498 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->query_policy(this->ipsec, src_ts, dst_ts,
                                      direction, mark, use_time);
 }
METHOD (kernel_interface_t , del_policy , status_t , private_kernel_interface_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 511 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->del_policy(this->ipsec, src, dst, src_ts, dst_ts,
                                    direction, type, sa, mark, priority);
 }
METHOD (kernel_interface_t , flush_policies , status_t , private_kernel_interface_t * this)
Definition at line 525 of file kernel_interface.c.
References ipsec, and NOT_SUPPORTED.
 {
     if (!this->ipsec)
     {
         return NOT_SUPPORTED;
     }
     return this->ipsec->flush_policies(this->ipsec);
 }
METHOD (kernel_interface_t , get_source_addr , host_t * , private_kernel_interface_t * this, host_t * dest, host_t * src)
Definition at line 535 of file kernel_interface.c.
References net.
 {
     if (!this->net)
     {
         return NULL;
     }
     return this->net->get_source_addr(this->net, dest, src);
 }
METHOD (kernel_interface_t , get_nexthop , host_t * , private_kernel_interface_t * this, host_t * dest, int prefix, host_t * src)
Definition at line 545 of file kernel_interface.c.
References net.
 {
     if (!this->net)
     {
         return NULL;
     }
     return this->net->get_nexthop(this->net, dest, prefix, src);
 }
METHOD (kernel_interface_t , get_interface , bool , private_kernel_interface_t * this, host_t * host, char ** name)
Definition at line 555 of file kernel_interface.c.
References net.
 {
     if (!this->net)
     {
         return NULL;
     }
     return this->net->get_interface(this->net, host, name);
 }
METHOD (kernel_interface_t , create_address_enumerator , enumerator_t * , private_kernel_interface_t * this, kernel_address_type_t which)
Definition at line 565 of file kernel_interface.c.
References enumerator_create_empty(), and net.
 {
     if (!this->net)
     {
         return enumerator_create_empty();
     }
     return this->net->create_address_enumerator(this->net, which);
 }
METHOD (kernel_interface_t , add_ip , status_t , private_kernel_interface_t * this, host_t * virtual_ip, int prefix, char * iface)
Definition at line 575 of file kernel_interface.c.
References net, and NOT_SUPPORTED.
 {
     if (!this->net)
     {
         return NOT_SUPPORTED;
     }
     return this->net->add_ip(this->net, virtual_ip, prefix, iface);
 }
METHOD (kernel_interface_t , del_ip , status_t , private_kernel_interface_t * this, host_t * virtual_ip, int prefix, bool wait)
Definition at line 586 of file kernel_interface.c.
References net, and NOT_SUPPORTED.
 {
     if (!this->net)
     {
         return NOT_SUPPORTED;
     }
     return this->net->del_ip(this->net, virtual_ip, prefix, wait);
 }
METHOD (kernel_interface_t , add_route , status_t , private_kernel_interface_t * this, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, host_t * src_ip, char * if_name)
Definition at line 596 of file kernel_interface.c.
References net, and NOT_SUPPORTED.
 {
     if (!this->net)
     {
         return NOT_SUPPORTED;
     }
     return this->net->add_route(this->net, dst_net, prefixlen, gateway,
                                 src_ip, if_name);
 }
METHOD (kernel_interface_t , del_route , status_t , private_kernel_interface_t * this, chunk_t dst_net, u_int8_t prefixlen, host_t * gateway, host_t * src_ip, char * if_name)
Definition at line 608 of file kernel_interface.c.
References net, and NOT_SUPPORTED.
 {
     if (!this->net)
     {
         return NOT_SUPPORTED;
     }
     return this->net->del_route(this->net, dst_net, prefixlen, gateway,
                                 src_ip, if_name);
 }
METHOD (kernel_interface_t , bypass_socket , bool , private_kernel_interface_t * this, int fd, int family)
Definition at line 620 of file kernel_interface.c.
References FALSE, and ipsec.
 {
     if (!this->ipsec)
     {
         return FALSE;
     }
     return this->ipsec->bypass_socket(this->ipsec, fd, family);
 }
METHOD (kernel_interface_t , enable_udp_decap , bool , private_kernel_interface_t * this, int fd, int family, u_int16_t port)
Definition at line 630 of file kernel_interface.c.
References FALSE, and ipsec.
 {
     if (!this->ipsec)
     {
         return FALSE;
     }
     return this->ipsec->enable_udp_decap(this->ipsec, fd, family, port);
 }
METHOD (kernel_interface_t , is_interface_usable , bool , private_kernel_interface_t * this, const char * iface)
Definition at line 640 of file kernel_interface.c.
References expected, NOT_FOUND, streq(), SUCCESS, and TRUE.
 {
     status_t expected;
     if (!this->ifaces_filter)
     {
         return TRUE;
     }
     expected = this->ifaces_exclude ? NOT_FOUND : SUCCESS;
     return this->ifaces_filter->find_first(this->ifaces_filter, (void*)streq,
                                            NULL, iface) == expected;
 }
METHOD (kernel_interface_t , all_interfaces_usable , bool , private_kernel_interface_t * this)
Definition at line 654 of file kernel_interface.c.
 {
     return this->ifaces_filter == NULL;
 }
METHOD (kernel_interface_t , get_address_by_ts , status_t , private_kernel_interface_t * this, traffic_selector_t * ts, host_t ** ip, bool * vip)
Definition at line 660 of file kernel_interface.c.
References ADDR_TYPE_ALL, ADDR_TYPE_REGULAR, ADDR_TYPE_VIRTUAL, host_t::clone, DBG2, DBG_KNL, enumerator_t::destroy, host_t::destroy, enumerator_t::enumerate, FAILED, FALSE, family, found, traffic_selector_t::get_type, host, host_create_any(), host_create_from_string(), traffic_selector_t::includes, SUCCESS, TRUE, and TS_IPV4_ADDR_RANGE.
 {
     enumerator_t *addrs;
     host_t *host;
     int family;
     bool found = FALSE;
     DBG2(DBG_KNL, "getting a local address in traffic selector %R", ts);
     /* if we have a family which includes localhost, we do not
      * search for an IP, we use the default */
     family = ts->get_type(ts) == TS_IPV4_ADDR_RANGE ? AF_INET : AF_INET6;
     if (family == AF_INET)
     {
         host = host_create_from_string("127.0.0.1", 0);
     }
     else
     {
         host = host_create_from_string("::1", 0);
     }
     if (ts->includes(ts, host))
     {
         *ip = host_create_any(family);
         host->destroy(host);
         DBG2(DBG_KNL, "using host %H", *ip);
         return SUCCESS;
     }
     host->destroy(host);
     /* try virtual IPs only first (on all interfaces) */
     addrs = create_address_enumerator(this,
                                       ADDR_TYPE_ALL ^ ADDR_TYPE_REGULAR);
     while (addrs->enumerate(addrs, (void**)&host))
     {
         if (ts->includes(ts, host))
         {
             found = TRUE;
             *ip = host->clone(host);
             if (vip)
             {
                 *vip = TRUE;
             }
             break;
         }
     }
     addrs->destroy(addrs);
     if (!found)
     {   /* then try the regular addresses (on all interfaces) */
         addrs = create_address_enumerator(this,
                                           ADDR_TYPE_ALL ^ ADDR_TYPE_VIRTUAL);
         while (addrs->enumerate(addrs, (void**)&host))
         {
             if (ts->includes(ts, host))
             {
                 found = TRUE;
                 *ip = host->clone(host);
                 if (vip)
                 {
                     *vip = FALSE;
                 }
                 break;
             }
         }
         addrs->destroy(addrs);
     }
     if (!found)
     {
         DBG2(DBG_KNL, "no local address found in traffic selector %R", ts);
         return FAILED;
     }
     DBG2(DBG_KNL, "using host %H", *ip);
     return SUCCESS;
 }
METHOD (kernel_interface_t , add_ipsec_interface , bool , private_kernel_interface_t * this, kernel_ipsec_constructor_t constructor)
Definition at line 742 of file kernel_interface.c.
References FALSE, and ipsec.
 {
     if (!this->ipsec)
     {
         this->ipsec_constructor = constructor;
         this->ipsec = constructor();
         return this->ipsec != NULL;
     }
     return FALSE;
 }
METHOD (kernel_interface_t , remove_ipsec_interface , bool , private_kernel_interface_t * this, kernel_ipsec_constructor_t constructor)
Definition at line 754 of file kernel_interface.c.
References FALSE, ipsec, and TRUE.
 {
     if (constructor == this->ipsec_constructor && this->ipsec)
     {
         this->ipsec->destroy(this->ipsec);
         this->ipsec = NULL;
         return TRUE;
     }
     return FALSE;
 }
METHOD (kernel_interface_t , add_net_interface , bool , private_kernel_interface_t * this, kernel_net_constructor_t constructor)
Definition at line 766 of file kernel_interface.c.
References FALSE, and net.
 {
     if (!this->net)
     {
         this->net_constructor = constructor;
         this->net = constructor();
         return this->net != NULL;
     }
     return FALSE;
 }
METHOD (kernel_interface_t , remove_net_interface , bool , private_kernel_interface_t * this, kernel_net_constructor_t constructor)
Definition at line 778 of file kernel_interface.c.
References FALSE, net, and TRUE.
 {
     if (constructor == this->net_constructor && this->net)
     {
         this->net->destroy(this->net);
         this->net = NULL;
         return TRUE;
     }
     return FALSE;
 }
METHOD (kernel_interface_t , add_listener , void , private_kernel_interface_t * this, kernel_listener_t * listener)
Definition at line 790 of file kernel_interface.c.
References mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->listeners->insert_last(this->listeners, listener);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , remove_listener , void , private_kernel_interface_t * this, kernel_listener_t * listener)
Definition at line 798 of file kernel_interface.c.
References mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->listeners->remove(this->listeners, listener, NULL);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , acquire , void , private_kernel_interface_t * this, u_int32_t reqid, traffic_selector_t * src_ts, traffic_selector_t * dst_ts)
Definition at line 806 of file kernel_interface.c.
References kernel_listener_t::acquire, enumerator_t::destroy, enumerator_t::enumerate, listener, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     kernel_listener_t *listener;
     enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &listener))
     {
         if (listener->acquire &&
             !listener->acquire(listener, reqid, src_ts, dst_ts))
         {
             this->listeners->remove_at(this->listeners, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , expire , void , private_kernel_interface_t * this, u_int8_t protocol, u_int32_t spi, host_t * dst, bool hard)
Definition at line 826 of file kernel_interface.c.
References enumerator_t::destroy, enumerator_t::enumerate, kernel_listener_t::expire, listener, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     kernel_listener_t *listener;
     enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &listener))
     {
         if (listener->expire &&
             !listener->expire(listener, protocol, spi, dst, hard))
         {
             this->listeners->remove_at(this->listeners, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , mapping , void , private_kernel_interface_t * this, u_int8_t protocol, u_int32_t spi, host_t * dst, host_t * remote)
Definition at line 847 of file kernel_interface.c.
References enumerator_t::destroy, enumerator_t::enumerate, listener, mutex_t::lock, kernel_listener_t::mapping, mutex, and mutex_t::unlock.
 {
     kernel_listener_t *listener;
     enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &listener))
     {
         if (listener->mapping &&
             !listener->mapping(listener, protocol, spi, dst, remote))
         {
             this->listeners->remove_at(this->listeners, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , migrate , void , private_kernel_interface_t * this, u_int32_t reqid, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, host_t * local, host_t * remote)
Definition at line 868 of file kernel_interface.c.
References enumerator_t::destroy, enumerator_t::enumerate, listener, mutex_t::lock, kernel_listener_t::migrate, mutex, and mutex_t::unlock.
 {
     kernel_listener_t *listener;
     enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &listener))
     {
         if (listener->migrate &&
             !listener->migrate(listener, reqid, src_ts, dst_ts, direction,
                                local, remote))
         {
             this->listeners->remove_at(this->listeners, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , roam , void , private_kernel_interface_t * this, bool address)
Definition at line 895 of file kernel_interface.c.
References call_roam(), mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->listeners->remove(this->listeners, &address, (void*)call_roam);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , tun , void , private_kernel_interface_t * this, tun_device_t * tun, bool created)
Definition at line 903 of file kernel_interface.c.
References enumerator_t::destroy, enumerator_t::enumerate, listener, mutex_t::lock, mutex, kernel_listener_t::tun, and mutex_t::unlock.
 {
     kernel_listener_t *listener;
     enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     enumerator = this->listeners->create_enumerator(this->listeners);
     while (enumerator->enumerate(enumerator, &listener))
     {
         if (listener->tun &&
             !listener->tun(listener, tun, created))
         {
             this->listeners->remove_at(this->listeners, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
METHOD (kernel_interface_t , register_algorithm , void , private_kernel_interface_t * this, u_int16_t alg_id, transform_type_t type, u_int16_t kernel_id, char * kernel_name)
Definition at line 922 of file kernel_interface.c.
References algorithm, INIT, name, and strdup.
 {
     kernel_algorithm_t *algorithm;
     INIT(algorithm,
         .type = type,
         .ike = alg_id,
         .kernel = kernel_id,
         .name = strdup(kernel_name),
     );
     this->mutex_algs->lock(this->mutex_algs);
     this->algorithms->insert_first(this->algorithms, algorithm);
     this->mutex_algs->unlock(this->mutex_algs);
 }
METHOD (kernel_interface_t , lookup_algorithm , bool , private_kernel_interface_t * this, u_int16_t alg_id, transform_type_t type, u_int16_t * kernel_id, char ** kernel_name)
Definition at line 940 of file kernel_interface.c.
References algorithm, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, kernel_algorithm_t::ike, kernel_algorithm_t::kernel, kernel_algorithm_t::name, TRUE, and kernel_algorithm_t::type.
 {
     kernel_algorithm_t *algorithm;
     enumerator_t *enumerator;
     bool found = FALSE;
     this->mutex_algs->lock(this->mutex_algs);
     enumerator = this->algorithms->create_enumerator(this->algorithms);
     while (enumerator->enumerate(enumerator, &algorithm))
     {
         if (algorithm->type == type && algorithm->ike == alg_id)
         {
             if (kernel_id)
             {
                 *kernel_id = algorithm->kernel;
             }
             if (kernel_name)
             {
                 *kernel_name = algorithm->name;
             }
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex_algs->unlock(this->mutex_algs);
     return found;
 }
METHOD (kernel_interface_t , destroy , void , private_kernel_interface_t * this)
Definition at line 971 of file kernel_interface.c.
References algorithm, mutex_t::destroy, DESTROY_FUNCTION_IF, DESTROY_IF, free(), ipsec, mutex, kernel_algorithm_t::name, net, and SUCCESS.
 {
     kernel_algorithm_t *algorithm;
     while (this->algorithms->remove_first(this->algorithms,
                                          (void**)&algorithm) == SUCCESS)
     {
         free(algorithm->name);
         free(algorithm);
     }
     this->algorithms->destroy(this->algorithms);
     this->mutex_algs->destroy(this->mutex_algs);
     DESTROY_IF(this->ipsec);
     DESTROY_IF(this->net);
     DESTROY_FUNCTION_IF(this->ifaces_filter, (void*)free);
     this->reqids->destroy(this->reqids);
     this->reqids_by_ts->destroy(this->reqids_by_ts);
     this->listeners->destroy(this->listeners);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void reqid_entry_destroy (reqid_entry_t * entry) static
Destroy a reqid mapping entry
Definition at line 211 of file kernel_interface.c.
References array_destroy_offset(), destroy(), free(), reqid_entry_t::local, and reqid_entry_t::remote.
Referenced by METHOD().
 {
     array_destroy_offset(entry->local, offsetof(traffic_selector_t, destroy));
     array_destroy_offset(entry->remote, offsetof(traffic_selector_t, destroy));
     free(entry);
 }
static bool ts_array_equals (array_t * a, array_t * b) static
Compare two array with traffic selectors for equality
Definition at line 271 of file kernel_interface.c.
References array_count(), array_create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, traffic_selector_t::equals, FALSE, and TRUE.
Referenced by equals_reqid_by_ts().
 {
     traffic_selector_t *tsa, *tsb;
     enumerator_t *ae, *be;
     bool equal = TRUE;
     if (array_count(a) != array_count(b))
     {
         return FALSE;
     }
     ae = array_create_enumerator(a);
     be = array_create_enumerator(b);
     while (equal && ae->enumerate(ae, &tsa) && be->enumerate(be, &tsb))
     {
         equal = tsa->equals(tsa, tsb);
     }
     ae->destroy(ae);
     be->destroy(be);
     return equal;
 }