strongSwan: eap_radius_xauth.c File Reference
eap_radius_xauth.c File Reference
#include "eap_radius_xauth.h"
#include "eap_radius_plugin.h"
#include "eap_radius.h"
#include "eap_radius_forward.h"
#include <daemon.h>
#include <radius_client.h>
#include <collections/array.h>
Classes
struct xauth_round_t
struct private_eap_radius_xauth_t
Typedefs
typedef struct
private_eap_radius_xauth_t private_eap_radius_xauth_t
typedef struct xauth_round_t xauth_round_t
Functions
static bool build_round (private_eap_radius_xauth_t *this, cp_payload_t *cp)
METHOD (xauth_method_t, initiate, status_t, private_eap_radius_xauth_t *this, cp_payload_t **out)
static status_t verify_radius (private_eap_radius_xauth_t *this)
METHOD (xauth_method_t, process, status_t, private_eap_radius_xauth_t *this, cp_payload_t *in, cp_payload_t **out)
METHOD (xauth_method_t, get_identity, identification_t *, private_eap_radius_xauth_t *this)
static bool parse_rounds (private_eap_radius_xauth_t *this, char *profile)
METHOD (xauth_method_t, destroy, void, private_eap_radius_xauth_t *this)
eap_radius_xauth_t * eap_radius_xauth_create_server (identification_t *server, identification_t *peer, char *profile)
Typedef Documentation
typedef struct private_eap_radius_xauth_t private_eap_radius_xauth_t
Definition at line 26 of file eap_radius_xauth.c.
typedef struct xauth_round_t xauth_round_t
Definition at line 27 of file eap_radius_xauth.c.
Function Documentation
static bool build_round (private_eap_radius_xauth_t * this, cp_payload_t * cp) static
Fetch next XAuth round, add attributes to CP payload
Definition at line 83 of file eap_radius_xauth.c.
References cp_payload_t::add_attribute, ARRAY_HEAD, array_remove(), chunk_empty, chunk_from_str, configuration_attribute_create_chunk(), FALSE, PLV1_CONFIGURATION_ATTRIBUTE, TRUE, and XAUTH_MESSAGE.
Referenced by METHOD().
 {
     if (!array_remove(this->rounds, ARRAY_HEAD, &this->round))
     {
         return FALSE;
     }
     cp->add_attribute(cp, configuration_attribute_create_chunk(
                     PLV1_CONFIGURATION_ATTRIBUTE, this->round.type, chunk_empty));
     if (this->round.message && strlen(this->round.message))
     {
         cp->add_attribute(cp, configuration_attribute_create_chunk(
                     PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_MESSAGE,
                     chunk_from_str(this->round.message)));
     }
     return TRUE;
 }
METHOD (xauth_method_t , initiate , status_t , private_eap_radius_xauth_t * this, cp_payload_t ** out)
Definition at line 101 of file eap_radius_xauth.c.
References cp_payload_t::add_attribute, build_round(), CFG_REQUEST, chunk_empty, configuration_attribute_create_chunk(), cp, cp_payload_create_type(), cp_payload_t::destroy, FAILED, NEED_MORE, PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, and XAUTH_USER_NAME.
 {
     cp_payload_t *cp;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REQUEST);
     /* first message always comes with username */
     cp->add_attribute(cp, configuration_attribute_create_chunk(
                 PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_NAME, chunk_empty));
     if (build_round(this, cp))
     {
         *out = cp;
         return NEED_MORE;
     }
     cp->destroy(cp);
     return FAILED;
 }
METHOD (xauth_method_t , process , status_t , private_eap_radius_xauth_t * this, cp_payload_t * in, cp_payload_t ** out)
Definition at line 164 of file eap_radius_xauth.c.
References array_count(), build_round(), CFG_REQUEST, chunk_cat, chunk_empty, configuration_attribute_type_names, cp, cp_payload_create_type(), cp_payload_t::create_attribute_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, cp_payload_t::destroy, enumerator_t::enumerate, FAILED, configuration_attribute_t::get_chunk, configuration_attribute_t::get_type, id, identification_create_from_data(), chunk_t::len, NEED_MORE, PLV1_CONFIGURATION, verify_radius(), and XAUTH_USER_NAME.
 {
     configuration_attribute_t *attr;
     enumerator_t *enumerator;
     identification_t *id;
     cp_payload_t *cp;
     chunk_t user = chunk_empty, pass = chunk_empty;
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &attr))
     {
         if (attr->get_type(attr) == XAUTH_USER_NAME)
         {
             user = attr->get_chunk(attr);
         }
         else if (attr->get_type(attr) == this->round.type)
         {
             pass = attr->get_chunk(attr);
             /* trim password to any null termination. As User-Password
              * uses null padding, we can't have any null in it, and some
              * clients actually send null terminated strings (Android). */
             pass.len = strnlen(pass.ptr, pass.len);
         }
     }
     enumerator->destroy(enumerator);
     if (!pass.ptr)
     {
         DBG1(DBG_IKE, "peer did not respond to our XAuth %N request",
              configuration_attribute_type_names, this->round.type);
         return FAILED;
     }
     this->pass = chunk_cat("mc", this->pass, pass);
     if (user.len)
     {
         id = identification_create_from_data(user);
         if (!id)
         {
             DBG1(DBG_IKE, "failed to parse provided XAuth username");
             return FAILED;
         }
         this->peer->destroy(this->peer);
         this->peer = id;
     }
     if (array_count(this->rounds) == 0)
     {
         return verify_radius(this);
     }
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REQUEST);
     if (build_round(this, cp))
     {
         *out = cp;
         return NEED_MORE;
     }
     cp->destroy(cp);
     return FAILED;
 }
METHOD (xauth_method_t , get_identity , identification_t * , private_eap_radius_xauth_t * this)
Definition at line 224 of file eap_radius_xauth.c.
 {
     return this->peer;
 }
METHOD (xauth_method_t , destroy , void , private_eap_radius_xauth_t * this)
Definition at line 292 of file eap_radius_xauth.c.
References array_destroy(), chunk_clear(), client(), DESTROY_IF, free(), and server.
 {
     DESTROY_IF(this->client);
     chunk_clear(&this->pass);
     array_destroy(this->rounds);
     this->server->destroy(this->server);
     this->peer->destroy(this->peer);
     free(this);
 }
static bool parse_rounds (private_eap_radius_xauth_t * this, char * profile) static
Parse XAuth round configuration
Definition at line 233 of file eap_radius_xauth.c.
References array_count(), array_insert(), ARRAY_TAIL, countof, settings_t::create_key_value_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, lib, xauth_round_t::message, library_t::ns, library_t::settings, str, strcaseeq(), TRUE, xauth_round_t::type, type, XAUTH_ANSWER, XAUTH_NEXT_PIN, XAUTH_PASSCODE, and XAUTH_USER_PASSWORD.
Referenced by eap_radius_xauth_create_server().
 {
     struct {
         char *str;
         configuration_attribute_type_t type;
     } map[] = {
         { "password",       XAUTH_USER_PASSWORD,    },
         { "passcode",       XAUTH_PASSCODE,         },
         { "nextpin",        XAUTH_NEXT_PIN,         },
         { "answer",         XAUTH_ANSWER,           },
     };
     enumerator_t *enumerator;
     char *type, *message;
     xauth_round_t round;
     int i;
     if (!profile || strlen(profile) == 0)
     {
         /* no config, fallback to password */
         round.type = XAUTH_USER_PASSWORD;
         round.message = NULL;
         array_insert(this->rounds, ARRAY_TAIL, &round);
         return TRUE;
     }
     enumerator = lib->settings->create_key_value_enumerator(lib->settings,
                             "%s.plugins.eap-radius.xauth.%s", lib->ns, profile);
     while (enumerator->enumerate(enumerator, &type, &message))
     {
         bool invalid = TRUE;
         for (i = 0; i < countof(map); i++)
         {
             if (strcaseeq(map[i].str, type))
             {
                 round.type = map[i].type;
                 round.message = message;
                 array_insert(this->rounds, ARRAY_TAIL, &round);
                 invalid = FALSE;
                 break;
             }
         }
         if (invalid)
         {
             DBG1(DBG_CFG, "invalid XAuth round type: '%s'", type);
             enumerator->destroy(enumerator);
             return FALSE;
         }
     }
     enumerator->destroy(enumerator);
     if (array_count(this->rounds) == 0)
     {
         DBG1(DBG_CFG, "XAuth configuration profile '%s' invalid", profile);
         return FALSE;
     }
     return TRUE;
 }
static status_t verify_radius (private_eap_radius_xauth_t * this) static
Verify a password using RADIUS User-Name/User-Password attributes
Definition at line 123 of file eap_radius_xauth.c.
References radius_message_t::add, client(), DBG1, DBG_IKE, radius_message_t::destroy, eap_radius_build_attributes(), eap_radius_forward_from_ike(), eap_radius_forward_to_ike(), eap_radius_handle_timeout(), eap_radius_process_attributes(), FAILED, radius_message_t::get_code, radius_message_create(), RAT_USER_NAME, RAT_USER_PASSWORD, request(), response, RMC_ACCESS_ACCEPT, RMC_ACCESS_CHALLENGE, RMC_ACCESS_REJECT, RMC_ACCESS_REQUEST, status, and SUCCESS.
Referenced by METHOD().
 {
     radius_message_t *request, *response;
     status_t status = FAILED;
     request = radius_message_create(RMC_ACCESS_REQUEST);
     request->add(request, RAT_USER_NAME, this->peer->get_encoding(this->peer));
     request->add(request, RAT_USER_PASSWORD, this->pass);
     eap_radius_build_attributes(request);
     eap_radius_forward_from_ike(request);
     response = this->client->request(this->client, request);
     if (response)
     {
         eap_radius_forward_to_ike(response);
         switch (response->get_code(response))
         {
             case RMC_ACCESS_ACCEPT:
                 eap_radius_process_attributes(response);
                 status = SUCCESS;
                 break;
             case RMC_ACCESS_CHALLENGE:
                 DBG1(DBG_IKE, "RADIUS Access-Challenge not supported");
                 /* FALL */
             case RMC_ACCESS_REJECT:
             default:
                 DBG1(DBG_IKE, "RADIUS authentication of '%Y' failed",
                      this->peer);
                 break;
         }
         response->destroy(response);
     }
     else
     {
         eap_radius_handle_timeout(NULL);
     }
     request->destroy(request);
     return status;
 }