strongSwan: eap_sim_file_triplets.c File Reference
eap_sim_file_triplets.c File Reference
#include "eap_sim_file_triplets.h"
#include <stdio.h>
#include <errno.h>
#include <daemon.h>
#include <collections/linked_list.h>
#include <threading/mutex.h>
#include <simaka_manager.h>
Classes
struct private_eap_sim_file_triplets_t
struct triplet_t
struct triplet_enumerator_t
Typedefs
typedef struct
private_eap_sim_file_triplets_t private_eap_sim_file_triplets_t
Functions
static void triplet_destroy (triplet_t *this)
static void enumerator_destroy (triplet_enumerator_t *e)
static bool enumerator_enumerate (triplet_enumerator_t *e, identification_t **imsi, char **rand, char **sres, char **kc)
METHOD (eap_sim_file_triplets_t, create_enumerator, enumerator_t *, private_eap_sim_file_triplets_t *this)
static void parse_token (char *to, char *from, size_t len)
static bool read_triplets (private_eap_sim_file_triplets_t *this, char *path)
METHOD (eap_sim_file_triplets_t, destroy, void, private_eap_sim_file_triplets_t *this)
eap_sim_file_triplets_t * eap_sim_file_triplets_create (char *file)
Typedef Documentation
typedef struct private_eap_sim_file_triplets_t private_eap_sim_file_triplets_t
Definition at line 26 of file eap_sim_file_triplets.c.
Function Documentation
static void enumerator_destroy (triplet_enumerator_t * e) static
destroy a triplet enumerator
Definition at line 85 of file eap_sim_file_triplets.c.
References triplet_enumerator_t::current, enumerator_t::destroy, free(), triplet_enumerator_t::inner, linked_list_t::insert_last, private_eap_sim_file_triplets_t::mutex, linked_list_t::remove_at, triplet_enumerator_t::this, private_eap_sim_file_triplets_t::triplets, and mutex_t::unlock.
Referenced by METHOD().
 {
     if (e->current)
     {
         /* We assume that the current element is used on invocation if destroy.
          * We move that triplet to the end to avoid handout of the same triplet
          * next time. */
         e->this->triplets->remove_at(e->this->triplets, e->inner);
         e->this->triplets->insert_last(e->this->triplets, e->current);
     }
     e->inner->destroy(e->inner);
     e->this->mutex->unlock(e->this->mutex);
     free(e);
 }
static bool enumerator_enumerate (triplet_enumerator_t * e, identification_t ** imsi, char ** rand, char ** sres, char ** kc) static
enumerate through triplets
Definition at line 103 of file eap_sim_file_triplets.c.
References triplet_enumerator_t::current, enumerator_t::enumerate, FALSE, triplet_t::imsi, triplet_enumerator_t::inner, triplet_t::kc, triplet_t::rand, triplet_t::sres, and TRUE.
Referenced by METHOD().
 {
     triplet_t *triplet;
     if (e->inner->enumerate(e->inner, &triplet))
     {
         e->current = triplet;
         *imsi = triplet->imsi;
         *rand = triplet->rand;
         *sres = triplet->sres;
         *kc = triplet->kc;
         return TRUE;
     }
     e->current = NULL;
     return FALSE;
 }
METHOD (eap_sim_file_triplets_t , create_enumerator , enumerator_t * , private_eap_sim_file_triplets_t * this)
Definition at line 121 of file eap_sim_file_triplets.c.
References triplet_enumerator_t::current, enumerator_t::destroy, enumerator_t::enumerate, enumerator_destroy(), enumerator_enumerate(), triplet_enumerator_t::inner, mutex_t::lock, malloc_thing, mutex, triplet_enumerator_t::public, and triplet_enumerator_t::this.
 {
     triplet_enumerator_t *enumerator = malloc_thing(triplet_enumerator_t);
     this->mutex->lock(this->mutex);
     enumerator->public.enumerate = (void*)enumerator_enumerate;
     enumerator->public.destroy = (void*)enumerator_destroy;
     enumerator->inner = this->triplets->create_enumerator(this->triplets);
     enumerator->current = NULL;
     enumerator->this = this;
     return &enumerator->public;
 }
METHOD (eap_sim_file_triplets_t , destroy , void , private_eap_sim_file_triplets_t * this)
Definition at line 233 of file eap_sim_file_triplets.c.
References mutex_t::destroy, free(), mutex, and triplet_destroy().
 {
     this->triplets->destroy_function(this->triplets, (void*)triplet_destroy);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void parse_token (char * to, char * from, size_t len) static
convert to token into the array
Definition at line 139 of file eap_sim_file_triplets.c.
References chunk_create(), chunk_from_hex(), free(), chunk_t::len, memcpy, memset, min, and chunk_t::ptr.
Referenced by read_triplets().
 {
     chunk_t chunk;
     chunk = chunk_create(from, min(strlen(from), len * 2));
     chunk = chunk_from_hex(chunk, NULL);
     memset(to, 0, len);
     memcpy(to + len - chunk.len, chunk.ptr, chunk.len);
     free(chunk.ptr);
 }
static bool read_triplets (private_eap_sim_file_triplets_t * this, char * path) static
Read the triplets from the file
Definition at line 153 of file eap_sim_file_triplets.c.
References DBG1, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), FALSE, identification_create_from_string(), triplet_t::imsi, triplet_t::kc, malloc_thing, memset, parse_token(), path, triplet_t::rand, SIM_KC_LEN, SIM_RAND_LEN, SIM_SRES_LEN, triplet_t::sres, strerror, triplet_destroy(), and TRUE.
Referenced by eap_sim_file_triplets_create().
 {
     char line[512];
     FILE *file;
     int i, nr = 0;
     file = fopen(path, "r");
     if (file == NULL)
     {
         DBG1(DBG_CFG, "opening triplet file %s failed: %s",
              path, strerror(errno));
         return FALSE;
     }
     /* read line by line */
     while (fgets(line, sizeof(line), file))
     {
         triplet_t *triplet;
         enumerator_t *enumerator;
         char *token;
         nr++;
         /* skip comments, empty lines */
         switch (line[0])
         {
             case '\n':
             case '\r':
             case '#':
             case '\0':
                 continue;
             default:
                 break;
         }
         triplet = malloc_thing(triplet_t);
         memset(triplet, 0, sizeof(triplet_t));
         i = 0;
         enumerator = enumerator_create_token(line, ",", " \n\r#");
         while (enumerator->enumerate(enumerator, &token))
         {
             switch (i++)
             {
                 case 0: /* IMSI */
                     triplet->imsi = identification_create_from_string(token);
                     continue;
                 case 1: /* rand */
                     parse_token(triplet->rand, token, SIM_RAND_LEN);
                     continue;
                 case 2: /* sres */
                     parse_token(triplet->sres, token, SIM_SRES_LEN);
                     continue;
                 case 3: /* kc */
                     parse_token(triplet->kc, token, SIM_KC_LEN);
                     continue;
                 default:
                     break;;
             }
             break;
         }
         enumerator->destroy(enumerator);
         if (i < 4)
         {
             DBG1(DBG_CFG, "error in triplet file, line %d", nr);
             triplet_destroy(triplet);
             continue;
         }
         DBG2(DBG_CFG, "triplet: imsi %Y\nrand %b\nsres %b\nkc %b",
              triplet->imsi, triplet->rand, SIM_RAND_LEN,
              triplet->sres, SIM_SRES_LEN, triplet->kc, SIM_KC_LEN);
         this->triplets->insert_last(this->triplets, triplet);
     }
     fclose(file);
     DBG1(DBG_CFG, "read %d triplets from %s",
          this->triplets->get_count(this->triplets), path);
     return TRUE;
 }
static void triplet_destroy (triplet_t * this) static
Destroy a triplet
Definition at line 62 of file eap_sim_file_triplets.c.
References DESTROY_IF, and free().
Referenced by METHOD(), and read_triplets().
 {
     DESTROY_IF(this->imsi);
     free(this);
 }