strongSwan: openssl_rsa_public_key
openssl_rsa_public_key
openssl
Classes
struct openssl_rsa_public_key_t
Typedefs
typedef struct
openssl_rsa_public_key_t openssl_rsa_public_key_t
Functions
openssl_rsa_public_key_t * openssl_rsa_public_key_load (key_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct openssl_rsa_public_key_t openssl_rsa_public_key_t
Definition at line 24 of file openssl_rsa_public_key.h.
Function Documentation
openssl_rsa_public_key_t* openssl_rsa_public_key_load (key_type_t type, va_list args)
Load a RSA public key using OpenSSL.
Accepts a BUILD_BLOB_ASN1_DER argument.
Parameters
type type of the key, must be KEY_RSA
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 368 of file openssl_rsa_public_key.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, chunk_empty, create_empty(), destroy(), KEY_ANY, KEY_RSA, chunk_t::len, n, chunk_t::ptr, rsa, and TRUE.
Referenced by METHOD().
 {
     private_openssl_rsa_public_key_t *this;
     chunk_t blob, n, e;
     n = e = blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_MODULUS:
                 n = va_arg(args, chunk_t);
                 continue;
             case BUILD_RSA_PUB_EXP:
                 e = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     this = create_empty();
     if (blob.ptr)
     {
         switch (type)
         {
             case KEY_ANY:
                 this->rsa = d2i_RSA_PUBKEY(NULL, (const u_char**)&blob.ptr,
                                            blob.len);
                 break;
             case KEY_RSA:
                 this->rsa = d2i_RSAPublicKey(NULL, (const u_char**)&blob.ptr,
                                              blob.len);
                 break;
             default:
                 break;
         }
         if (this->rsa)
         {
             return &this->public;
         }
     }
     else if (n.ptr && e.ptr && type == KEY_RSA)
     {
         this->rsa = RSA_new();
         this->rsa->n = BN_bin2bn((const u_char*)n.ptr, n.len, NULL);
         this->rsa->e = BN_bin2bn((const u_char*)e.ptr, e.len, NULL);
         return &this->public;
     }
     destroy(this);
     return NULL;
 }