strongSwan: cert_payload_t Struct Reference
cert_payload_t Struct Reference
cert_payload
#include "cert_payload.h"
Public Attributes
payload_t payload_interface
certificate_t *(* get_cert)(cert_payload_t *this)
container_t *(* get_container)(cert_payload_t *this)
cert_encoding_t(* get_cert_encoding)(cert_payload_t *this)
chunk_t(* get_hash)(cert_payload_t *this)
char *(* get_url)(cert_payload_t *this)
void(* destroy)(cert_payload_t *this)
Detailed Description
Class representing an IKEv1/IKEv2 CERT payload.
Definition at line 61 of file cert_payload.h.
Member Data Documentation
void(* cert_payload_t::destroy)(cert_payload_t *this)
Destroys the cert_payload object.
Definition at line 110 of file cert_payload.h.
certificate_t*(* cert_payload_t::get_cert)(cert_payload_t *this)
Get the payloads encoded certificate.
Returns
certificate copy
Definition at line 73 of file cert_payload.h.
Referenced by process_ac(), process_crl(), process_x509(), and try_get_cert().
cert_encoding_t(* cert_payload_t::get_cert_encoding)(cert_payload_t *this)
Get the encoding of the certificate.
Returns
encoding
Definition at line 87 of file cert_payload.h.
Referenced by process_certs(), and try_get_cert().
container_t*(* cert_payload_t::get_container)(cert_payload_t *this)
Get the payloads certificate container.
Returns
container copy
Definition at line 80 of file cert_payload.h.
Referenced by process_pkcs7().
chunk_t(* cert_payload_t::get_hash)(cert_payload_t *this)
Get the hash if this is a hash and URL encoded certificate.
This function returns internal data, do not free.
Returns
hash
Definition at line 96 of file cert_payload.h.
Referenced by try_get_cert().
char*(* cert_payload_t::get_url)(cert_payload_t *this)
Get the URL if this is a hash and URL encoded certificate.
This function returns internal data, do not free.
Returns
url
Definition at line 105 of file cert_payload.h.
Referenced by process_x509().
payload_t cert_payload_t::payload_interface
The payload_t interface.
Definition at line 66 of file cert_payload.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
cert_payload.h