strongSwan: rwlock.c File Reference
rwlock.c File Reference
#include <pthread.h>
#include <library.h>
#include <utils/debug.h>
#include "rwlock.h"
#include "rwlock_condvar.h"
#include "thread.h"
#include "condvar.h"
#include "mutex.h"
#include "lock_profiler.h"
Classes
struct private_rwlock_t
struct private_rwlock_condvar_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct private_rwlock_t private_rwlock_t
typedef struct
private_rwlock_condvar_t private_rwlock_condvar_t
Functions
static void initialize_is_reader ()
METHOD (rwlock_t, read_lock, void, private_rwlock_t *this)
METHOD (rwlock_t, write_lock, void, private_rwlock_t *this)
METHOD (rwlock_t, try_write_lock, bool, private_rwlock_t *this)
METHOD (rwlock_t, unlock, void, private_rwlock_t *this)
METHOD (rwlock_t, destroy, void, private_rwlock_t *this)
rwlock_t * rwlock_create (rwlock_type_t type)
METHOD (rwlock_condvar_t, wait_, void, private_rwlock_condvar_t *this, rwlock_t *lock)
METHOD (rwlock_condvar_t, timed_wait_abs, bool, private_rwlock_condvar_t *this, rwlock_t *lock, timeval_t time)
METHOD (rwlock_condvar_t, timed_wait, bool, private_rwlock_condvar_t *this, rwlock_t *lock, u_int timeout)
METHOD (rwlock_condvar_t, signal_, void, private_rwlock_condvar_t *this)
METHOD (rwlock_condvar_t, broadcast, void, private_rwlock_condvar_t *this)
METHOD (rwlock_condvar_t, condvar_destroy, void, private_rwlock_condvar_t *this)
rwlock_condvar_t * rwlock_condvar_create ()
Variables
static pthread_key_t is_reader
static pthread_once_t is_reader_initialized = PTHREAD_ONCE_INIT
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file rwlock.c.
Typedef Documentation
typedef struct private_rwlock_condvar_t private_rwlock_condvar_t
Definition at line 38 of file rwlock.c.
typedef struct private_rwlock_t private_rwlock_t
Definition at line 37 of file rwlock.c.
Function Documentation
static void initialize_is_reader () static
Initialize the read lock counter.
Definition at line 255 of file rwlock.c.
Referenced by rwlock_create().
 {
     pthread_key_create(&is_reader, NULL);
 }
METHOD (rwlock_t , read_lock , void , private_rwlock_t * this)
Definition at line 260 of file rwlock.c.
References FALSE, mutex_t::lock, mutex, profiler_end, profiler_start, thread_cancelability(), and mutex_t::unlock.
 {
     uintptr_t reading;
     bool old;
     reading = (uintptr_t)pthread_getspecific(is_reader);
     profiler_start(&this->profile);
     this->mutex->lock(this->mutex);
     if (!this->writer && reading > 0)
     {
         /* directly allow threads that hold ANY read locks, to avoid a deadlock
          * caused by preferring writers in the loop below */
     }
     else
     {
         old = thread_cancelability(FALSE);
         while (this->writer || this->waiting_writers)
         {
             this->readers->wait(this->readers, this->mutex);
         }
         thread_cancelability(old);
     }
     this->reader_count++;
     profiler_end(&this->profile);
     this->mutex->unlock(this->mutex);
     pthread_setspecific(is_reader, (void*)(reading + 1));
 }
METHOD (rwlock_t , write_lock , void , private_rwlock_t * this)
Definition at line 289 of file rwlock.c.
References FALSE, mutex_t::lock, mutex, profiler_end, profiler_start, thread_cancelability(), TRUE, and mutex_t::unlock.
 {
     bool old;
     profiler_start(&this->profile);
     this->mutex->lock(this->mutex);
     this->waiting_writers++;
     old = thread_cancelability(FALSE);
     while (this->writer || this->reader_count)
     {
         this->writers->wait(this->writers, this->mutex);
     }
     thread_cancelability(old);
     this->waiting_writers--;
     this->writer = TRUE;
     profiler_end(&this->profile);
     this->mutex->unlock(this->mutex);
 }
METHOD (rwlock_t , try_write_lock , bool , private_rwlock_t * this)
Definition at line 309 of file rwlock.c.
References FALSE, mutex_t::lock, mutex, res, TRUE, and mutex_t::unlock.
 {
     bool res = FALSE;
     this->mutex->lock(this->mutex);
     if (!this->writer && !this->reader_count)
     {
         res = this->writer = TRUE;
     }
     this->mutex->unlock(this->mutex);
     return res;
 }
METHOD (rwlock_t , unlock , void , private_rwlock_t * this)
Definition at line 322 of file rwlock.c.
References FALSE, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     if (this->writer)
     {
         this->writer = FALSE;
     }
     else
     {
         uintptr_t reading;
         this->reader_count--;
         reading = (uintptr_t)pthread_getspecific(is_reader);
         pthread_setspecific(is_reader, (void*)(reading - 1));
     }
     if (!this->reader_count)
     {
         if (this->waiting_writers)
         {
             this->writers->signal(this->writers);
         }
         else
         {
             this->readers->broadcast(this->readers);
         }
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (rwlock_t , destroy , void , private_rwlock_t * this)
Definition at line 352 of file rwlock.c.
References mutex_t::destroy, free(), mutex, and profiler_cleanup.
 {
     this->mutex->destroy(this->mutex);
     this->writers->destroy(this->writers);
     this->readers->destroy(this->readers);
     profiler_cleanup(&this->profile);
     free(this);
 }
METHOD (rwlock_condvar_t , wait_ , void , private_rwlock_condvar_t * this, rwlock_t * lock)
Definition at line 399 of file rwlock.c.
References condvar, mutex_t::lock, mutex, thread_cleanup_pop(), thread_cleanup_push(), TRUE, mutex_t::unlock, rwlock_t::unlock, condvar_t::wait, and rwlock_t::write_lock.
 {
     /* at this point we have the write lock locked, to make signals more
      * predictable we try to prevent other threads from signaling by acquiring
      * the mutex while we still hold the write lock (this assumes they will
      * hold the write lock themselves when signaling, which is not mandatory) */
     this->mutex->lock(this->mutex);
     /* unlock the rwlock and wait for a signal */
     lock->unlock(lock);
     /* if the calling thread enabled thread cancelability we want to replicate
      * the behavior of the regular condvar, i.e. the lock will be held again
      * before executing cleanup functions registered by the calling thread */
     thread_cleanup_push((thread_cleanup_t)lock->write_lock, lock);
     thread_cleanup_push((thread_cleanup_t)this->mutex->unlock, this->mutex);
     this->condvar->wait(this->condvar, this->mutex);
     /* we release the mutex to allow other threads into the condvar (might even
      * be required so we can acquire the lock again below) */
     thread_cleanup_pop(TRUE);
     /* finally we reacquire the lock we held previously */
     thread_cleanup_pop(TRUE);
 }
METHOD (rwlock_condvar_t , timed_wait_abs , bool , private_rwlock_condvar_t * this, rwlock_t * lock, timeval_t time)
Definition at line 422 of file rwlock.c.
References condvar, mutex_t::lock, mutex, thread_cleanup_pop(), thread_cleanup_push(), condvar_t::timed_wait_abs, TRUE, mutex_t::unlock, rwlock_t::unlock, and rwlock_t::write_lock.
 {
     bool timed_out;
     /* see wait() above for details on what is going on here */
     this->mutex->lock(this->mutex);
     lock->unlock(lock);
     thread_cleanup_push((thread_cleanup_t)lock->write_lock, lock);
     thread_cleanup_push((thread_cleanup_t)this->mutex->unlock, this->mutex);
     timed_out = this->condvar->timed_wait_abs(this->condvar, this->mutex, time);
     thread_cleanup_pop(TRUE);
     thread_cleanup_pop(TRUE);
     return timed_out;
 }
METHOD (rwlock_condvar_t , timed_wait , bool , private_rwlock_condvar_t * this, rwlock_t * lock, u_int timeout)
Definition at line 438 of file rwlock.c.
References s, time_monotonic(), and timeval_add_ms().
 {
     timeval_t tv;
     u_int s, ms;
     time_monotonic(&tv);
     s = timeout / 1000;
     ms = timeout % 1000;
     tv.tv_sec += s;
     timeval_add_ms(&tv, ms);
     return timed_wait_abs(this, lock, tv);
 }
METHOD (rwlock_condvar_t , signal_ , void , private_rwlock_condvar_t * this)
Definition at line 455 of file rwlock.c.
References condvar, mutex_t::lock, mutex, condvar_t::signal, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->condvar->signal(this->condvar);
     this->mutex->unlock(this->mutex);
 }
METHOD (rwlock_condvar_t , broadcast , void , private_rwlock_condvar_t * this)
Definition at line 463 of file rwlock.c.
References condvar_t::broadcast, condvar, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->condvar->broadcast(this->condvar);
     this->mutex->unlock(this->mutex);
 }
METHOD (rwlock_condvar_t , condvar_destroy , void , private_rwlock_condvar_t * this)
Definition at line 471 of file rwlock.c.
References condvar, mutex_t::destroy, condvar_t::destroy, free(), and mutex.
 {
     this->condvar->destroy(this->condvar);
     this->mutex->destroy(this->mutex);
     free(this);
 }
Variable Documentation
pthread_key_t is_reader static
This implementation of the rwlock_t interface uses mutex_t and condvar_t primitives, if the pthread_rwlock_* group of functions is not available or don't allow recursive locking for readers.
The following constraints are enforced:
Multiple readers can hold the lock at the same time.
Only a single writer can hold the lock at any given time.
A writer must block until all readers have released the lock before obtaining the lock exclusively.
Readers that don't hold any read lock and arrive while a writer is waiting to acquire the lock will block until after the writer has obtained and released the lock. These constraints allow for read sharing, prevent write sharing, prevent read-write sharing and (largely) prevent starvation of writers by a steady stream of incoming readers. Reader starvation is not prevented (this could happen if there are more writers than readers).
The implementation supports recursive locking of the read lock but not of the write lock. Readers must not acquire the lock exclusively at the same time and vice-versa (this is not checked or enforced so behave yourself to prevent deadlocks).
Since writers are preferred a thread currently holding the read lock that tries to acquire the read lock recursively while a writer is waiting would result in a deadlock. In order to avoid having to use a thread-specific value for each rwlock_t (or a list of threads) to keep track if a thread already acquired the read lock we use a single thread-specific value for all rwlock_t objects that keeps track of how many read locks a thread currently holds. Preferring readers that already hold ANY read locks prevents this deadlock while it still largely avoids writer starvation (for locks that can only be acquired while holding another read lock this will obviously not work). Keep track of how many read locks a thread holds.
Definition at line 245 of file rwlock.c.
pthread_once_t is_reader_initialized = PTHREAD_ONCE_INIT static
Only initialize the read lock counter once.
Definition at line 250 of file rwlock.c.