strongSwan: rwlock_condvar_t Struct Reference
rwlock_condvar_t Struct Reference
rwlock_condvar
#include "rwlock_condvar.h"
Public Attributes
void(* wait)(rwlock_condvar_t *this, rwlock_t *lock)
bool(* timed_wait)(rwlock_condvar_t *this, rwlock_t *lock, u_int timeout)
bool(* timed_wait_abs)(rwlock_condvar_t *this, rwlock_t *lock, timeval_t tv)
void(* signal)(rwlock_condvar_t *this)
void(* broadcast)(rwlock_condvar_t *this)
void(* destroy)(rwlock_condvar_t *this)
Detailed Description
A special condvar implementation that can be used in conjunction with rwlock_t (the write lock to be precise).
Note
The implementation does not verify that the current thread actually holds the write lock and not the read lock, so watch out.
Definition at line 35 of file rwlock_condvar.h.
Member Data Documentation
void(* rwlock_condvar_t::broadcast)(rwlock_condvar_t *this)
Wake up all threads in a condvar.
Definition at line 74 of file rwlock_condvar.h.
Referenced by rwlock_condvar_cancel_run(), and START_TEST().
void(* rwlock_condvar_t::destroy)(rwlock_condvar_t *this)
Destroy a condvar and free its resources.
Definition at line 79 of file rwlock_condvar.h.
Referenced by cancellation_rwcond(), and START_TEST().
void(* rwlock_condvar_t::signal)(rwlock_condvar_t *this)
Wake up a single thread in a condvar.
Definition at line 69 of file rwlock_condvar.h.
Referenced by rwlock_condvar_run().
bool(* rwlock_condvar_t::timed_wait)(rwlock_condvar_t *this, rwlock_t *lock, u_int timeout)
Wait on a condvar until it gets signalized, or times out.
Parameters
lock lock to release while waiting (write lock)
timeout timeout im ms
Returns
TRUE if timed out, FALSE otherwise
Definition at line 51 of file rwlock_condvar.h.
Referenced by START_TEST().
bool(* rwlock_condvar_t::timed_wait_abs)(rwlock_condvar_t *this, rwlock_t *lock, timeval_t tv)
Wait on a condvar until it gets signalized, or times out.
The passed timeval should be calculated based on the time_monotonic() function.
Parameters
lock lock to release while waiting (write lock)
tv absolute time until timeout
Returns
TRUE if timed out, FALSE otherwise
Definition at line 63 of file rwlock_condvar.h.
Referenced by START_TEST().
void(* rwlock_condvar_t::wait)(rwlock_condvar_t *this, rwlock_t *lock)
Wait on a condvar until it gets signalized.
Parameters
lock lock to release while waiting (write lock)
Definition at line 42 of file rwlock_condvar.h.
Referenced by cancellation_rwcond(), rwlock_condvar_cancel_run(), rwlock_condvar_run_broad(), and START_TEST().
The documentation for this struct was generated from the following file:
rwlock_condvar.h