strongSwan: x509_ac
x509_ac
x509
Classes
struct x509_ac_t
Typedefs
typedef struct x509_ac_t x509_ac_t
Functions
x509_ac_t * x509_ac_load (certificate_type_t type, va_list args)
x509_ac_t * x509_ac_gen (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct x509_ac_t x509_ac_t
Definition at line 31 of file x509_ac.h.
Function Documentation
x509_ac_t* x509_ac_gen (certificate_type_t type, va_list args)
Generate a X.509 attribute certificate.
Accepted build parts: BUILD_USER_CERT: user certificate BUILD_SIGNER_CERT: signer certificate BUILD_SIGNER_KEY: signer private key BUILD_SERIAL: serial number BUILD_GROUP_ATTR: group attribute, several possible
Parameters
type certificate type, CERT_X509_AC only
args builder_part_t argument list
Returns
X.509 Attribute certificate, NULL on failure
See header.
Definition at line 1116 of file x509_ac.c.
References add_groups_from_list(), build_ac(), BUILD_AC_GROUP_STRINGS, BUILD_CERT, BUILD_END, BUILD_NOT_AFTER_TIME, BUILD_NOT_BEFORE_TIME, BUILD_SERIAL, BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, CERT_X509, chunk_clone, create_empty(), destroy(), private_key_t::get_ref, certificate_t::get_ref, certificate_t::get_type, private_x509_ac_t::holderCert, private_x509_ac_t::notAfter, private_x509_ac_t::notBefore, private_x509_ac_t::public, private_x509_ac_t::serialNumber, private_x509_ac_t::signerCert, private_x509_ac_t::signerKey, and TRUE.
Referenced by METHOD().
 {
     private_x509_ac_t *ac;
     ac = create_empty();
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_NOT_BEFORE_TIME:
                 ac->notBefore = va_arg(args, time_t);
                 continue;
             case BUILD_NOT_AFTER_TIME:
                 ac->notAfter = va_arg(args, time_t);
                 continue;
             case BUILD_SERIAL:
                 ac->serialNumber = chunk_clone(va_arg(args, chunk_t));
                 continue;
             case BUILD_AC_GROUP_STRINGS:
                 add_groups_from_list(ac, va_arg(args, linked_list_t*));
                 continue;
             case BUILD_CERT:
                 ac->holderCert = va_arg(args, certificate_t*);
                 ac->holderCert->get_ref(ac->holderCert);
                 continue;
             case BUILD_SIGNING_CERT:
                 ac->signerCert = va_arg(args, certificate_t*);
                 ac->signerCert->get_ref(ac->signerCert);
                 continue;
             case BUILD_SIGNING_KEY:
                 ac->signerKey = va_arg(args, private_key_t*);
                 ac->signerKey->get_ref(ac->signerKey);
                 continue;
             case BUILD_END:
                 break;
             default:
                 destroy(ac);
                 return NULL;
         }
         break;
     }
     if (ac->signerKey && ac->holderCert && ac->signerCert &&
         ac->holderCert->get_type(ac->holderCert) == CERT_X509 &&
         ac->signerCert->get_type(ac->signerCert) == CERT_X509)
     {
         if (build_ac(ac))
         {
             return &ac->public;
         }
     }
     destroy(ac);
     return NULL;
 }
x509_ac_t* x509_ac_load (certificate_type_t type, va_list args)
Load a X.509 attribute certificate.
Parameters
type certificate type, CERT_X509_AC only
args builder_part_t argument list
Returns
X.509 Attribute certificate, NULL on failure
See header.
Definition at line 1060 of file x509_ac.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_clone, chunk_empty, create_empty(), destroy(), private_x509_ac_t::encoding, parse_certificate(), chunk_t::ptr, private_x509_ac_t::public, and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.ptr)
     {
         private_x509_ac_t *ac = create_empty();
         ac->encoding = chunk_clone(blob);
         if (parse_certificate(ac))
         {
             return &ac->public;
         }
         destroy(ac);
     }
     return NULL;
 }