strongSwan: ntru_private_key
ntru_private_key
ntru
Classes
struct ntru_private_key_t
Typedefs
typedef struct ntru_private_key_t ntru_private_key_t
Functions
ntru_private_key_t * ntru_private_key_create (ntru_drbg_t *drbg, ntru_param_set_t *params)
ntru_private_key_t * ntru_private_key_create_from_data (ntru_drbg_t *drbg, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct ntru_private_key_t ntru_private_key_t
Definition at line 24 of file ntru_private_key.h.
Function Documentation
ntru_private_key_t* ntru_private_key_create (ntru_drbg_t * drbg, ntru_param_set_t * params)
Creates an NTRU encryption public/private key pair using a NIST DRBG
Parameters
drbg Digital Random Bit Generator used for key generation
params NTRU encryption parameter set to be used
Definition at line 644 of file ntru_private_key.c.
References BITS_PER_BYTE, ntru_param_set_t::c_bits, chunk_alloc, chunk_clear(), chunk_free(), DBG2, DBG_LIB, ntru_poly_t::destroy, destroy(), ntru_param_set_t::dF_r, ntru_param_set_t::dg, FALSE, free(), ntru_drbg_t::generate, generate_encoding(), ntru_drbg_t::get_ref, HASH_SHA1, HASH_SHA256, INIT, ntru_param_set_t::is_product_form, chunk_t::len, malloc(), memwipe(), ntru_param_set_t::N, ntru_poly_create_from_seed(), params, chunk_t::ptr, ntru_param_set_t::q, ring_inv(), ntru_poly_t::ring_mult, and ntru_param_set_t::sec_strength_len.
 {
     private_ntru_private_key_t *this;
     size_t t_len;
     uint16_t *t1, *t2, *t = NULL;
     uint16_t mod_q_mask;
     hash_algorithm_t hash_algid;
     ntru_poly_t *g_poly;
     chunk_t seed;
     int i;
     INIT(this,
         .public = {
             .get_id = _get_id,
             .get_public_key = _get_public_key,
             .get_encoding = _get_encoding,
             .decrypt = _decrypt,
             .destroy = _destroy,
         },
         .params = params,
         .pubkey = malloc(params->N * sizeof(uint16_t)),
         .drbg = drbg->get_ref(drbg),
     );
     /* set hash algorithm and seed length based on security strength */
     if (params->sec_strength_len <= 20)
     {
         hash_algid = HASH_SHA1;
     }
     else
     {
         hash_algid = HASH_SHA256;
     }
     seed =chunk_alloc(params->sec_strength_len + 8);
     /* get random seed for generating trinary F as a list of indices */
     if (!drbg->generate(drbg, params->sec_strength_len * BITS_PER_BYTE,
                               seed.len, seed.ptr))
     {
         goto err;
     }
     DBG2(DBG_LIB, "generate polynomial F");
     this->privkey = ntru_poly_create_from_seed(hash_algid, seed, params->c_bits,
                                                params->N, params->q,
                                                params->dF_r, params->dF_r,
                                                params->is_product_form);
     if (!this->privkey)
     {
         goto err;
     }
     /* allocate temporary array t */
     t_len = 3 * params->N * sizeof(uint16_t);
     t = malloc(t_len);
     t1 = t + 2 * params->N;
     /* extend sparse private key polynomial f to N array elements */
     this->privkey->get_array(this->privkey, t1);
     /* set mask for large modulus */
     mod_q_mask = params->q - 1;
     /* form f = 1 + pF */
     for (i = 0; i < params->N; i++)
     {
         t1[i] = (t1[i] * 3) & mod_q_mask;
     }
     t1[0] = (t1[0] + 1) & mod_q_mask;
     /* use the public key array as a temporary buffer */
     t2 = this->pubkey;
     /* find f^-1 in (Z/qZ)[X]/(X^N - 1) */
     if (!ring_inv(t1, params->N, params->q, t, t2))
     {
         goto err;
     }
     /* get random seed for generating trinary g as a list of indices */
     if (!drbg->generate(drbg, params->sec_strength_len * BITS_PER_BYTE,
                               seed.len, seed.ptr))
     {
         goto err;
     }
     DBG2(DBG_LIB, "generate polynomial g");
     g_poly = ntru_poly_create_from_seed(hash_algid, seed, params->c_bits,
                                         params->N, params->q, params->dg + 1,
                                         params->dg, FALSE);
     if (!g_poly)
     {
         goto err;
     }
     /* compute public key polynomial h = p * (f^-1 * g) mod q */
     g_poly->ring_mult(g_poly, t2, t2);
     g_poly->destroy(g_poly);
     for (i = 0; i < params->N; i++)
     {
         this->pubkey[i] = (t2[i] * 3) & mod_q_mask;
     }
     /* cleanup temporary storage */
     chunk_clear(&seed);
     memwipe(t, t_len);
     free(t);
     /* generate private key encoding */
     generate_encoding(this);
     return &this->public;
 err:
     chunk_free(&seed);
     free(t);
     destroy(this);
     return NULL;
 }
ntru_private_key_t* ntru_private_key_create_from_data (ntru_drbg_t * drbg, chunk_t data)
Creates an NTRU encryption private key from encoding
Parameters
drbg Deterministic random bit generator
data Encoded NTRU private key
Definition at line 770 of file ntru_private_key.c.
References chunk_clone, DBG1, DBG_LIB, ntru_param_set_t::dF_r, free(), ntru_drbg_t::get_ref, INIT, ntru_param_set_t::is_product_form, chunk_t::len, malloc(), memwipe(), ntru_param_set_t::N, ntru_param_set_t::N_bits, ntru_octets_2_elements(), NTRU_OID_LEN, ntru_packed_trits_2_indices(), ntru_param_set_get_by_oid(), ntru_poly_create_from_data, NTRU_PRIVKEY_DEFAULT_TAG, NTRU_PRIVKEY_INDICES_TAG, NTRU_PRIVKEY_TRITS_TAG, params, chunk_t::ptr, ntru_param_set_t::q, and ntru_param_set_t::q_bits.
Referenced by START_TEST().
 {
     private_ntru_private_key_t *this;
     size_t header_len, pubkey_packed_len, privkey_packed_len;
     size_t privkey_packed_trits_len, privkey_packed_indices_len;
     uint8_t *privkey_packed, tag;
     uint16_t *indices, dF;
     ntru_param_set_t *params;
     header_len = 2 + NTRU_OID_LEN;
     /* check the NTRU public key header format */
     if (data.len < header_len ||
         !(data.ptr[0] == NTRU_PRIVKEY_DEFAULT_TAG ||
           data.ptr[0] == NTRU_PRIVKEY_TRITS_TAG ||
           data.ptr[0] == NTRU_PRIVKEY_INDICES_TAG) ||
         data.ptr[1] != NTRU_OID_LEN)
     {
         DBG1(DBG_LIB, "loaded NTRU private key with invalid header");
         return NULL;
     }
     tag = data.ptr[0];
     params = ntru_param_set_get_by_oid(data.ptr + 2);
     if (!params)
     {
         DBG1(DBG_LIB, "loaded NTRU private key with unknown OID");
         return NULL;
     }
     pubkey_packed_len = (params->N * params->q_bits + 7) / 8;
     privkey_packed_trits_len = (params->N + 4) / 5;
     /* check packing type for product-form private keys */
     if (params->is_product_form &&  tag == NTRU_PRIVKEY_TRITS_TAG)
     {
         DBG1(DBG_LIB, "a product-form NTRU private key cannot be trits-encoded");
         return NULL;
     }
     /* set packed-key length for packed indices */
     if (params->is_product_form)
     {
         dF = (uint16_t)((params->dF_r & 0xff) +           /* df1 */
                        ((params->dF_r >>  8) & 0xff) +    /* df2 */
                        ((params->dF_r >> 16) & 0xff));    /* df3 */
     }
     else
     {
         dF = (uint16_t)params->dF_r;
     }
     privkey_packed_indices_len = (2 * dF * params->N_bits + 7) / 8;
     /* set private-key packing type if defaulted */
     if (tag == NTRU_PRIVKEY_DEFAULT_TAG)
     {
         if (params->is_product_form ||
             privkey_packed_indices_len <= privkey_packed_trits_len)
         {
             tag = NTRU_PRIVKEY_INDICES_TAG;
         }
         else
         {
             tag = NTRU_PRIVKEY_TRITS_TAG;
         }
     }
     privkey_packed_len = (tag == NTRU_PRIVKEY_TRITS_TAG) ?
                          privkey_packed_trits_len : privkey_packed_indices_len;
     if (data.len < header_len + pubkey_packed_len + privkey_packed_len)
     {
         DBG1(DBG_LIB, "loaded NTRU private key with wrong packed key size");
         return NULL;
     }
     INIT(this,
         .public = {
             .get_id = _get_id,
             .get_public_key = _get_public_key,
             .get_encoding = _get_encoding,
             .decrypt = _decrypt,
             .destroy = _destroy,
         },
         .params = params,
         .pubkey = malloc(params->N * sizeof(uint16_t)),
         .encoding = chunk_clone(data),
         .drbg = drbg->get_ref(drbg),
     );
     /* unpack the encoded public key */
     ntru_octets_2_elements(pubkey_packed_len, data.ptr + header_len,
                            params->q_bits, this->pubkey);
     /* allocate temporary memory for indices */
     indices = malloc(2 * dF * sizeof(uint16_t));
     /* unpack the private key */
     privkey_packed = data.ptr + header_len + pubkey_packed_len;
     if (tag == NTRU_PRIVKEY_TRITS_TAG)
     {
         ntru_packed_trits_2_indices(privkey_packed, params->N,
                                     indices, indices + dF);
     }
     else
     {
         ntru_octets_2_elements(privkey_packed_indices_len, privkey_packed,
                                params->N_bits, indices);
     }
     this->privkey = ntru_poly_create_from_data(indices, params->N, params->q,
                                                params->dF_r, params->dF_r,
                                                params->is_product_form);
     /* cleanup */
     memwipe(indices, 2 * dF * sizeof(uint16_t));
     free(indices);
     return &this->public;
 }