strongSwan: imv_msg_t Struct Reference
imv_msg_t Struct Reference
imv_msg
#include "imv_msg.h"
Public Attributes
TNC_UInt32(* get_src_id)(imv_msg_t *this)
TNC_UInt32(* get_dst_id)(imv_msg_t *this)
void(* set_msg_type)(imv_msg_t *this, pen_type_t msg_type)
pen_type_t(* get_msg_type)(imv_msg_t *this)
TNC_Result(* send)(imv_msg_t *this, bool excl)
TNC_Result(* send_assessment)(imv_msg_t *this)
TNC_Result(* receive)(imv_msg_t *this, imv_msg_t *out_msg, bool *fatal_error)
void(* add_attribute)(imv_msg_t *this, pa_tnc_attr_t *attr)
int(* get_attribute_count)(imv_msg_t *this)
enumerator_t *(* create_attribute_enumerator)(imv_msg_t *this)
chunk_t(* get_encoding)(imv_msg_t *this)
void(* destroy)(imv_msg_t *this)
Detailed Description
Interface for a PA-TNC message handled by an IMV.
Definition at line 34 of file imv_msg.h.
Member Data Documentation
void(* imv_msg_t::add_attribute)(imv_msg_t *this, pa_tnc_attr_t *attr)
Add a PA-TNC attribute to the send queue
Parameters
attr PA-TNC attribute to be added
Definition at line 94 of file imv_msg.h.
Referenced by imv_attestation_build(), imv_attestation_process(), METHOD(), and receive_msg().
enumerator_t*(* imv_msg_t::create_attribute_enumerator)(imv_msg_t *this)
Enumerator over PA-TNC attributes contained in the PA-TNC message
Returns
PA-TNC attribute enumerator
Definition at line 108 of file imv_msg.h.
Referenced by receive_msg().
void(* imv_msg_t::destroy)(imv_msg_t *this)
Destroys a imv_msg_t object.
Definition at line 120 of file imv_msg.h.
Referenced by METHOD(), and receive_msg().
int(* imv_msg_t::get_attribute_count)(imv_msg_t *this)
Get the number of PA-TNC attributes in the send queue
Returns
number of PA-TNC attribute in send queue
Definition at line 101 of file imv_msg.h.
Referenced by METHOD().
TNC_UInt32(* imv_msg_t::get_dst_id)(imv_msg_t *this)
Get destination ID of PA-TNC message
Returns
destination ID
Definition at line 48 of file imv_msg.h.
chunk_t(* imv_msg_t::get_encoding)(imv_msg_t *this)
Get the full encoding of an IMV message.
Returns
message encoding, internal data
Definition at line 115 of file imv_msg.h.
pen_type_t(* imv_msg_t::get_msg_type)(imv_msg_t *this)
Get the type of a PA-TNC message.
Returns
message type
Definition at line 62 of file imv_msg.h.
Referenced by receive_msg().
TNC_UInt32(* imv_msg_t::get_src_id)(imv_msg_t *this)
Get source ID of PA-TNC message
Returns
src ID
Definition at line 41 of file imv_msg.h.
Referenced by receive_msg().
TNC_Result(* imv_msg_t::receive)(imv_msg_t *this, imv_msg_t *out_msg, bool *fatal_error)
Processes a received PA-TNC message
Parameters
out_msg outgoing PA-TN message
fatal_error TRUE if IMC sent a fatal error message
Returns
TNC result code
Definition at line 86 of file imv_msg.h.
Referenced by receive_msg().
TNC_Result(* imv_msg_t::send)(imv_msg_t *this, bool excl)
Sends one or multiple PA-TNC messages
Parameters
excl set the excl message flag if supported
Returns
TNC result code
Definition at line 70 of file imv_msg.h.
Referenced by METHOD(), and receive_msg().
TNC_Result(* imv_msg_t::send_assessment)(imv_msg_t *this)
Send a PA-TNC message containing an IETF Assessment Result attribute
Returns
TNC result code
Definition at line 77 of file imv_msg.h.
Referenced by METHOD(), and receive_msg().
void(* imv_msg_t::set_msg_type)(imv_msg_t *this, pen_type_t msg_type)
Set the type of a PA-TNC message
Parameters
msg_type message type
Definition at line 55 of file imv_msg.h.
Referenced by receive_msg().
The documentation for this struct was generated from the following file:
imv_msg.h