strongSwan: tnc_ifmap_soap.c File Reference
tnc_ifmap_soap.c File Reference
#include "tnc_ifmap_soap.h"
#include "tnc_ifmap_soap_msg.h"
#include <utils/debug.h>
#include <credentials/sets/mem_cred.h>
#include <daemon.h>
#include <tls_socket.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
Classes
struct private_tnc_ifmap_soap_t
Macros
#define IFMAP_NS "http://www.trustedcomputinggroup.org/2010/IFMAP/2"
#define IFMAP_META_NS "http://www.trustedcomputinggroup.org/2010/IFMAP-METADATA/2"
#define IFMAP_URI "https://localhost:8444/imap"
#define IFMAP_NO_FD -1
Typedefs
typedef struct
private_tnc_ifmap_soap_t private_tnc_ifmap_soap_t
Functions
METHOD (tnc_ifmap_soap_t, newSession, bool, private_tnc_ifmap_soap_t *this)
METHOD (tnc_ifmap_soap_t, renewSession, bool, private_tnc_ifmap_soap_t *this)
METHOD (tnc_ifmap_soap_t, purgePublisher, bool, private_tnc_ifmap_soap_t *this)
static xmlNodePtr create_access_request (private_tnc_ifmap_soap_t *this, u_int32_t id)
static xmlNodePtr create_identity (private_tnc_ifmap_soap_t *this, identification_t *id, bool is_user)
static xmlNodePtr create_enforcement_report (private_tnc_ifmap_soap_t *this, xmlChar *action, xmlChar *reason)
static xmlNodePtr create_delete_filter (private_tnc_ifmap_soap_t *this, char *metadata)
static xmlNodePtr create_publish_request (private_tnc_ifmap_soap_t *this)
static xmlNodePtr create_device (private_tnc_ifmap_soap_t *this)
static xmlNodePtr create_ip_address (private_tnc_ifmap_soap_t *this, host_t *host)
static xmlNodePtr create_metadata (private_tnc_ifmap_soap_t *this, xmlChar *metadata)
static xmlNodePtr create_capability (private_tnc_ifmap_soap_t *this, identification_t *name)
METHOD (tnc_ifmap_soap_t, publish_ike_sa, bool, private_tnc_ifmap_soap_t *this, ike_sa_t *ike_sa, bool up)
METHOD (tnc_ifmap_soap_t, publish_device_ip, bool, private_tnc_ifmap_soap_t *this, host_t *host)
METHOD (tnc_ifmap_soap_t, publish_virtual_ips, bool, private_tnc_ifmap_soap_t *this, ike_sa_t *ike_sa, bool assign)
METHOD (tnc_ifmap_soap_t, publish_enforcement_report, bool, private_tnc_ifmap_soap_t *this, host_t *host, char *action, char *reason)
METHOD (tnc_ifmap_soap_t, endSession, bool, private_tnc_ifmap_soap_t *this)
METHOD (tnc_ifmap_soap_t, get_session_id, char *, private_tnc_ifmap_soap_t *this)
METHOD (tnc_ifmap_soap_t, orphaned, bool, private_tnc_ifmap_soap_t *this)
METHOD (tnc_ifmap_soap_t, get_ref, tnc_ifmap_soap_t *, private_tnc_ifmap_soap_t *this)
METHOD (tnc_ifmap_soap_t, destroy, void, private_tnc_ifmap_soap_t *this)
static bool soap_init (private_tnc_ifmap_soap_t *this)
tnc_ifmap_soap_t * tnc_ifmap_soap_create ()
Macro Definition Documentation
#define IFMAP_META_NS "http://www.trustedcomputinggroup.org/2010/IFMAP-METADATA/2"
Definition at line 31 of file tnc_ifmap_soap.c.
Referenced by create_publish_request().
#define IFMAP_NO_FD -1
Definition at line 33 of file tnc_ifmap_soap.c.
Referenced by METHOD(), soap_init(), and tnc_ifmap_soap_create().
#define IFMAP_NS "http://www.trustedcomputinggroup.org/2010/IFMAP/2"
Definition at line 30 of file tnc_ifmap_soap.c.
Referenced by create_publish_request(), and METHOD().
#define IFMAP_URI "https://localhost:8444/imap"
Definition at line 32 of file tnc_ifmap_soap.c.
Referenced by soap_init().
Typedef Documentation
typedef struct private_tnc_ifmap_soap_t private_tnc_ifmap_soap_t
Definition at line 35 of file tnc_ifmap_soap.c.
Function Documentation
static xmlNodePtr create_access_request (private_tnc_ifmap_soap_t * this, u_int32_t id) static
Create an access-request based on device_name and ike_sa_id
Definition at line 188 of file tnc_ifmap_soap.c.
References BUF_LEN, and snprintf.
Referenced by METHOD().
 {
     xmlNodePtr node;
     char buf[BUF_LEN];
     node = xmlNewNode(NULL, "access-request");
     snprintf(buf, BUF_LEN, "%s:%d", this->device_name, id);
     xmlNewProp(node, "name", buf);
     return node;
 }
static xmlNodePtr create_capability (private_tnc_ifmap_soap_t * this, identification_t * name) static
Create capability metadata
Definition at line 387 of file tnc_ifmap_soap.c.
References BUF_LEN, and snprintf.
Referenced by METHOD().
 {
     xmlNodePtr node, node2;
     char buf[BUF_LEN];
     node = xmlNewNode(this->ns_meta, "capability");
     xmlNewProp(node, "ifmap-cardinality", "multiValue");
     node2 = xmlNewNode(NULL, "name");
     xmlAddChild(node, node2);
     snprintf(buf, BUF_LEN, "%Y", name);
     xmlNodeAddContent(node2, buf);
     node2 = xmlNewNode(NULL, "administrative-domain");
     xmlAddChild(node, node2);
     xmlNodeAddContent(node2, "strongswan");
     return node;
 }
static xmlNodePtr create_delete_filter (private_tnc_ifmap_soap_t * this, char * metadata) static
Create delete filter
Definition at line 275 of file tnc_ifmap_soap.c.
References BUF_LEN, and snprintf.
Referenced by METHOD().
 {
     xmlNodePtr node;
     char buf[BUF_LEN];
     node = xmlNewNode(NULL, "delete");
     snprintf(buf, BUF_LEN, "meta:%s[@ifmap-publisher-id='%s']",
              metadata, this->ifmap_publisher_id);
     xmlNewProp(node, "filter", buf);
     return node;
 }
static xmlNodePtr create_device (private_tnc_ifmap_soap_t * this) static
Create a device
Definition at line 309 of file tnc_ifmap_soap.c.
Referenced by METHOD().
 {
     xmlNodePtr node, node2;
     node = xmlNewNode(NULL, "device");
     node2 = xmlNewNode(NULL, "name");
     xmlAddChild(node, node2);
     xmlNodeAddContent(node2, this->device_name);
     return node;
 }
static xmlNodePtr create_enforcement_report (private_tnc_ifmap_soap_t * this, xmlChar * action, xmlChar * reason) static
Create enforcement-report metadata
Definition at line 251 of file tnc_ifmap_soap.c.
Referenced by METHOD().
 {
     xmlNodePtr node, node2, node3;
     node = xmlNewNode(NULL, "metadata");
     node2 = xmlNewNode(this->ns_meta, "enforcement-report");
     xmlAddChild(node, node2);
     xmlNewProp(node2, "ifmap-cardinality", "multiValue");
     node3 = xmlNewNode(NULL, "enforcement-action");
     xmlAddChild(node2, node3);
     xmlNodeAddContent(node3, action);
     node3 = xmlNewNode(NULL, "enforcement-reason");
     xmlAddChild(node2, node3);
     xmlNodeAddContent(node3, reason);
     return node;
 }
static xmlNodePtr create_identity (private_tnc_ifmap_soap_t * this, identification_t * id, bool is_user) static
Create an identity
Definition at line 205 of file tnc_ifmap_soap.c.
References BUF_LEN, identification_t::get_type, ID_DER_ASN1_DN, ID_FQDN, ID_IPV4_ADDR, ID_IPV6_ADDR, ID_KEY_ID, ID_RFC822_ADDR, and snprintf.
Referenced by METHOD().
 {
     xmlNodePtr node;
     char buf[BUF_LEN], *id_type;
     node = xmlNewNode(NULL, "identity");
     snprintf(buf, BUF_LEN, "%Y", id);
     xmlNewProp(node, "name", buf);
     switch (id->get_type(id))
     {
         case ID_IPV4_ADDR:
             id_type = "other";
             xmlNewProp(node, "other-type-definition", "36906:ipv4-address");
             break;
         case ID_FQDN:
             id_type = is_user ? "username" : "dns-name";
             break;
         case ID_RFC822_ADDR:
             id_type = "email-address";
             break;
         case ID_IPV6_ADDR:
             id_type = "other";
             xmlNewProp(node, "other-type-definition", "36906:ipv6-address");
             break;
         case ID_DER_ASN1_DN:
             id_type = "distinguished-name";
             break;
         case ID_KEY_ID:
             id_type = "other";
             xmlNewProp(node, "other-type-definition", "36906:key-id");
             break;
         default:
             id_type = "other";
             xmlNewProp(node, "other-type-definition", "36906:other");
     }
     xmlNewProp(node, "type", id_type);
     return node;
 }
static xmlNodePtr create_ip_address (private_tnc_ifmap_soap_t * this, host_t * host) static
Create an ip-address
Definition at line 324 of file tnc_ifmap_soap.c.
References BUF_LEN, FALSE, host_t::get_address, host_t::get_family, chunk_t::len, len, chunk_t::ptr, snprintf, and TRUE.
Referenced by METHOD().
 {
     xmlNodePtr node;
     char buf[BUF_LEN];
     node = xmlNewNode(NULL, "ip-address");
     if (host->get_family(host) == AF_INET6)
     {
         chunk_t address;
         int len, written, i;
         char *pos;
         bool first = TRUE;
         /* output IPv6 address in canonical IF-MAP 2.0 format */
         address = host->get_address(host);
         pos = buf;
         len = sizeof(buf);
         for (i = 0; i < address.len; i = i + 2)
         {
             written = snprintf(pos, len, "%s%x", first ? "" : ":",
                                256*address.ptr[i] +  address.ptr[i+1]);
             if (written < 0 || written >= len)
             {
                 break;
             }
             pos += written;
             len -= written;
             first = FALSE;
         }
     }
     else
     {
         snprintf(buf, BUF_LEN, "%H", host);
     }
     xmlNewProp(node, "value", buf);
     xmlNewProp(node, "type", host->get_family(host) == AF_INET ? "IPv4" : "IPv6");
     return node;
 }
static xmlNodePtr create_metadata (private_tnc_ifmap_soap_t * this, xmlChar * metadata) static
Create metadata
Definition at line 371 of file tnc_ifmap_soap.c.
Referenced by METHOD().
 {
     xmlNodePtr node, node2;
     node = xmlNewNode(NULL, "metadata");
     node2 = xmlNewNode(this->ns_meta, metadata);
     xmlAddChild(node, node2);
     xmlNewProp(node2, "ifmap-cardinality", "singleValue");
     return node;
 }
static xmlNodePtr create_publish_request (private_tnc_ifmap_soap_t * this) static
Create a publish request
Definition at line 293 of file tnc_ifmap_soap.c.
References IFMAP_META_NS, IFMAP_NS, and request().
Referenced by METHOD().
 {
     xmlNodePtr request;
     request = xmlNewNode(NULL, "publish");
     this->ns = xmlNewNs(request, IFMAP_NS, "ifmap");
     xmlSetNs(request, this->ns);
     this->ns_meta = xmlNewNs(request, IFMAP_META_NS, "meta");
     xmlNewProp(request, "session-id", this->session_id);
     return request;
 }
METHOD (tnc_ifmap_soap_t , newSession , bool , private_tnc_ifmap_soap_t * this)
Definition at line 109 of file tnc_ifmap_soap.c.
References DBG1, DBG_TNC, tnc_ifmap_soap_msg_t::destroy, FALSE, settings_t::get_str, IFMAP_NS, lib, library_t::ns, tnc_ifmap_soap_msg_t::post, request(), result, library_t::settings, strdup, tls, tnc_ifmap_soap_msg_create(), and uri.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request, result;
     /*build newSession request */
     request = xmlNewNode(NULL, "newSession");
     this->ns = xmlNewNs(request, IFMAP_NS, "ifmap");
     xmlSetNs(request, this->ns);
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     if (!soap_msg->post(soap_msg, request, "newSessionResult", &result))
     {
         soap_msg->destroy(soap_msg);
         return FALSE;
     }
     /* get session-id and ifmap-publisher-id properties */
     this->session_id = xmlGetProp(result, "session-id");
     this->ifmap_publisher_id = xmlGetProp(result, "ifmap-publisher-id");
     soap_msg->destroy(soap_msg);
     DBG1(DBG_TNC, "created ifmap session '%s' as publisher '%s'",
                    this->session_id, this->ifmap_publisher_id);
     /* set PEP and PDP device name (defaults to IF-MAP Publisher ID) */
     this->device_name = lib->settings->get_str(lib->settings,
                                         "%s.plugins.tnc-ifmap.device_name",
                                          this->ifmap_publisher_id, lib->ns);
     this->device_name = strdup(this->device_name);
     return this->session_id && this->ifmap_publisher_id;
 }
METHOD (tnc_ifmap_soap_t , renewSession , bool , private_tnc_ifmap_soap_t * this)
Definition at line 144 of file tnc_ifmap_soap.c.
References tnc_ifmap_soap_msg_t::destroy, IFMAP_NS, tnc_ifmap_soap_msg_t::post, request(), tls, tnc_ifmap_soap_msg_create(), and uri.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request;
     bool success;
     /* build renewSession request */
     request = xmlNewNode(NULL, "renewSession");
     this->ns = xmlNewNs(request, IFMAP_NS, "ifmap");
     xmlSetNs(request, this->ns);
     xmlNewProp(request, "session-id", this->session_id);
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     success = soap_msg->post(soap_msg, request, "renewSessionResult", NULL);
     soap_msg->destroy(soap_msg);
     return success;
 }
METHOD (tnc_ifmap_soap_t , purgePublisher , bool , private_tnc_ifmap_soap_t * this)
Definition at line 164 of file tnc_ifmap_soap.c.
References tnc_ifmap_soap_msg_t::destroy, IFMAP_NS, tnc_ifmap_soap_msg_t::post, request(), tls, tnc_ifmap_soap_msg_create(), and uri.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request;
     bool success;
     /* build purgePublisher request */
     request = xmlNewNode(NULL, "purgePublisher");
     this->ns = xmlNewNs(request, IFMAP_NS, "ifmap");
     xmlSetNs(request, this->ns);
     xmlNewProp(request, "session-id", this->session_id);
     xmlNewProp(request, "ifmap-publisher-id", this->ifmap_publisher_id);
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     success = soap_msg->post(soap_msg, request, "purgePublisherReceived", NULL);
     soap_msg->destroy(soap_msg);
     return success;
 }
METHOD (tnc_ifmap_soap_t , publish_ike_sa , bool , private_tnc_ifmap_soap_t * this, ike_sa_t * ike_sa, bool up)
update or delete authenticated-as metadata
update or delete access-request-ip metadata for physical IP address
update or delete authenticated-by metadata
update or delete capability metadata
Definition at line 408 of file tnc_ifmap_soap.c.
References AUTH_RULE_GROUP, create_access_request(), ike_sa_t::create_auth_cfg_enumerator, create_capability(), create_delete_filter(), create_device(), auth_cfg_t::create_enumerator, create_identity(), create_ip_address(), create_metadata(), create_publish_request(), enumerator_t::destroy, tnc_ifmap_soap_msg_t::destroy, enumerator_t::enumerate, identification_t::equals, FALSE, ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, ike_sa_t::get_other_id, ike_sa_t::get_unique_id, group, host, id, tnc_ifmap_soap_msg_t::post, request(), tls, tnc_ifmap_soap_msg_create(), TRUE, type, and uri.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request, node, node2 = NULL;
     enumerator_t *e1, *e2;
     auth_rule_t type;
     identification_t *id, *eap_id, *group;
     host_t *host;
     auth_cfg_t *auth;
     u_int32_t ike_sa_id;
     bool is_user = FALSE, first = TRUE, success;
     /* extract relevant data from IKE_SA*/
     ike_sa_id = ike_sa->get_unique_id(ike_sa);
     host = ike_sa->get_other_host(ike_sa);
     id = ike_sa->get_other_id(ike_sa);
     eap_id = ike_sa->get_other_eap_id(ike_sa);
     /* in the presence of an EAP Identity, treat it as a username */
     if (!id->equals(id, eap_id))
     {
         is_user = TRUE;
         id = eap_id;
     }
     /* build publish request */
     request = create_publish_request(this);
     /* delete any existing enforcement reports */
     if (up)
     {
         node = create_delete_filter(this, "enforcement-report");
         xmlAddChild(request, node);
         xmlAddChild(node, create_ip_address(this, host));
         xmlAddChild(node, create_device(this));
     }
     if (up)
     {
         node = xmlNewNode(NULL, "update");
     }
     else
     {
         node = create_delete_filter(this, "authenticated-as");
     }
     xmlAddChild(request, node);
     /* add access-request, identity and [if up] metadata */
     xmlAddChild(node, create_access_request(this, ike_sa_id));
     xmlAddChild(node, create_identity(this, id, is_user));
     if (up)
     {
         xmlAddChild(node, create_metadata(this, "authenticated-as"));
     }
     if (up)
     {
         node = xmlNewNode(NULL, "update");
     }
     else
     {
         node = create_delete_filter(this, "access-request-ip");
     }
     xmlAddChild(request, node);
     /* add access-request, ip-address and [if up] metadata */
     xmlAddChild(node, create_access_request(this, ike_sa_id));
     xmlAddChild(node, create_ip_address(this, host));
     if (up)
     {
         xmlAddChild(node, create_metadata(this, "access-request-ip"));
     }
     if (up)
     {
         node = xmlNewNode(NULL, "update");
     }
     else
     {
         node = create_delete_filter(this, "authenticated-by");
     }
     xmlAddChild(request, node);
     /* add access-request, device and [if up] metadata */
     xmlAddChild(node, create_access_request(this, ike_sa_id));
     xmlAddChild(node, create_device(this));
     if (up)
     {
         xmlAddChild(node, create_metadata(this, "authenticated-by"));
     }
     e1 = ike_sa->create_auth_cfg_enumerator(ike_sa, FALSE);
     while (e1->enumerate(e1, &auth) && (first || up))
     {
         e2 = auth->create_enumerator(auth);
         while (e2->enumerate(e2, &type, &group))
         {
             /* look for group memberships */
             if (type == AUTH_RULE_GROUP)
             {
                 if (first)
                 {
                     first = FALSE;
                     if (up)
                     {
                         node = xmlNewNode(NULL, "update");
                     }
                     else
                     {
                         node = create_delete_filter(this, "capability");
                     }
                     xmlAddChild(request, node);
                     /* add access-request */
                     xmlAddChild(node, create_access_request(this, ike_sa_id));
                     if (!up)
                     {
                         break;
                     }
                     node2 = xmlNewNode(NULL, "metadata");
                     xmlAddChild(node, node2);
                 }
                 xmlAddChild(node2, create_capability(this, group));
             }
         }
         e2->destroy(e2);
     }
     e1->destroy(e1);
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     success = soap_msg->post(soap_msg, request, "publishReceived", NULL);
     soap_msg->destroy(soap_msg);
     return success;
 }
METHOD (tnc_ifmap_soap_t , publish_device_ip , bool , private_tnc_ifmap_soap_t * this, host_t * host)
Definition at line 558 of file tnc_ifmap_soap.c.
References create_device(), create_ip_address(), create_metadata(), create_publish_request(), tnc_ifmap_soap_msg_t::destroy, tnc_ifmap_soap_msg_t::post, request(), tls, tnc_ifmap_soap_msg_create(), update(), and uri.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request, update;
     bool success;
     /* build publish update request */
     request = create_publish_request(this);
     update = xmlNewNode(NULL, "update");
     xmlAddChild(request, update);
     /* add device, ip-address and metadata */
     xmlAddChild(update, create_device(this));
     xmlAddChild(update, create_ip_address(this, host));
     xmlAddChild(update, create_metadata(this, "device-ip"));
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     success = soap_msg->post(soap_msg, request, "publishReceived", NULL);
     soap_msg->destroy(soap_msg);
     return success;
 }
METHOD (tnc_ifmap_soap_t , publish_virtual_ips , bool , private_tnc_ifmap_soap_t * this, ike_sa_t * ike_sa, bool assign)
update or delete access-request-ip metadata for a virtual IP address
Definition at line 582 of file tnc_ifmap_soap.c.
References create_access_request(), create_delete_filter(), create_ip_address(), create_metadata(), create_publish_request(), ike_sa_t::create_virtual_ip_enumerator, enumerator_t::destroy, tnc_ifmap_soap_msg_t::destroy, enumerator_t::enumerate, FALSE, ike_sa_t::get_unique_id, tnc_ifmap_soap_msg_t::post, request(), tls, tnc_ifmap_soap_msg_create(), uri, and vip.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request, node;
     u_int32_t ike_sa_id;
     enumerator_t *enumerator;
     host_t *vip;
     bool success;
     /* extract relevant data from IKE_SA*/
     ike_sa_id = ike_sa->get_unique_id(ike_sa);
     /* build publish request */
     request = create_publish_request(this);
     enumerator = ike_sa->create_virtual_ip_enumerator(ike_sa, FALSE);
     while (enumerator->enumerate(enumerator, &vip))
     {
         if (assign)
         {
             node = xmlNewNode(NULL, "update");
         }
         else
         {
             node = create_delete_filter(this, "access-request-ip");
         }
         xmlAddChild(request, node);
         /* add access-request, virtual ip-address and [if assign] metadata */
             xmlAddChild(node, create_access_request(this, ike_sa_id));
             xmlAddChild(node, create_ip_address(this, vip));
             if (assign)
         {
             xmlAddChild(node, create_metadata(this, "access-request-ip"));
         }
     }
     enumerator->destroy(enumerator);
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     success = soap_msg->post(soap_msg, request, "publishReceived", NULL);
     soap_msg->destroy(soap_msg);
     return success;
 }
METHOD (tnc_ifmap_soap_t , publish_enforcement_report , bool , private_tnc_ifmap_soap_t * this, host_t * host, char * action, char * reason)
Definition at line 631 of file tnc_ifmap_soap.c.
References create_device(), create_enforcement_report(), create_ip_address(), create_publish_request(), tnc_ifmap_soap_msg_t::destroy, tnc_ifmap_soap_msg_t::post, request(), tls, tnc_ifmap_soap_msg_create(), update(), and uri.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request, update;
     bool success;
     /* build publish update request */
     request = create_publish_request(this);
     update = xmlNewNode(NULL, "update");
     xmlAddChild(request, update);
     /* add ip-address and metadata */
     xmlAddChild(update, create_ip_address(this, host));
     xmlAddChild(update, create_device(this));
     xmlAddChild(update, create_enforcement_report(this, action, reason));
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     success = soap_msg->post(soap_msg, request, "publishReceived", NULL);
     soap_msg->destroy(soap_msg);
     return success;
 }
METHOD (tnc_ifmap_soap_t , endSession , bool , private_tnc_ifmap_soap_t * this)
Definition at line 655 of file tnc_ifmap_soap.c.
References DBG1, DBG_TNC, tnc_ifmap_soap_msg_t::destroy, IFMAP_NS, tnc_ifmap_soap_msg_t::post, request(), tls, tnc_ifmap_soap_msg_create(), and uri.
 {
     tnc_ifmap_soap_msg_t *soap_msg;
     xmlNodePtr request;
     bool success;
     /* build endSession request */
     request = xmlNewNode(NULL, "endSession");
     this->ns = xmlNewNs(request, IFMAP_NS, "ifmap");
     xmlSetNs(request, this->ns);
     xmlNewProp(request, "session-id", this->session_id);
     soap_msg = tnc_ifmap_soap_msg_create(this->uri, this->user_pass, this->tls);
     success = soap_msg->post(soap_msg, request, "endSessionResult", NULL);
     soap_msg->destroy(soap_msg);
     DBG1(DBG_TNC, "ended ifmap session '%s' as publisher '%s'",
                    this->session_id, this->ifmap_publisher_id);
     return success;
 }
METHOD (tnc_ifmap_soap_t , get_session_id , char * , private_tnc_ifmap_soap_t * this)
Definition at line 678 of file tnc_ifmap_soap.c.
 {
     return this->session_id;
 }
METHOD (tnc_ifmap_soap_t , orphaned , bool , private_tnc_ifmap_soap_t * this)
Definition at line 684 of file tnc_ifmap_soap.c.
 {
     return this->ref == 1;
 }
METHOD (tnc_ifmap_soap_t , get_ref , tnc_ifmap_soap_t * , private_tnc_ifmap_soap_t * this)
Definition at line 690 of file tnc_ifmap_soap.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (tnc_ifmap_soap_t , destroy , void , private_tnc_ifmap_soap_t * this)
Definition at line 697 of file tnc_ifmap_soap.c.
References close, library_t::credmgr, creds, mem_cred_t::destroy, DESTROY_IF, free(), host, IFMAP_NO_FD, lib, ref_put(), credential_manager_t::remove_set, and tls.
 {
     if (ref_put(&this->ref))
     {
         if (this->session_id)
         {
             xmlFree(this->session_id);
             xmlFree(this->ifmap_publisher_id);
             free(this->device_name);
         }
         DESTROY_IF(this->tls);
         DESTROY_IF(this->host);
         if (this->fd != IFMAP_NO_FD)
         {
             close(this->fd);
         }
         lib->credmgr->remove_set(lib->credmgr, &this->creds->set);
         this->creds->destroy(this->creds);
         free(this->user_pass.ptr);
         free(this);
     }
 }
static bool soap_init (private_tnc_ifmap_soap_t * this) static
Definition at line 722 of file tnc_ifmap_soap.c.
References auth_cfg_t::add, mem_cred_t::add_cert, mem_cred_t::add_cert_ref, mem_cred_t::add_key, auth_cfg_create(), AUTH_RULE_SUBJECT_CERT, BUILD_END, BUILD_FROM_FILE, cert, CERT_X509, chunk_from_str, chunk_to_base64(), connect, credential_factory_t::create, CRED_CERTIFICATE, CRED_PRIVATE_KEY, library_t::credmgr, creds, library_t::creds, DBG1, DBG_TNC, auth_cfg_t::destroy, FALSE, free(), credential_manager_t::get_private, settings_t::get_str, certificate_t::get_subject, host, host_create_from_dns(), IFMAP_NO_FD, IFMAP_URI, key, KEY_RSA, lib, library_t::ns, port, library_t::settings, socket, strdup, strerror, strncaseeq(), tls, TLS_1_2, tls_socket_create(), TRUE, and uri.
Referenced by tnc_ifmap_soap_create().
 {
     char *server_uri, *server_str, *port_str, *uri_str;
     char *server_cert, *client_cert, *client_key, *user_pass;
     int port;
     auth_cfg_t *auth;
     certificate_t *cert;
     private_key_t *key;
     identification_t *server_id, *client_id = NULL;
     /* getting configuration parameters from strongswan.conf */
     server_uri =  lib->settings->get_str(lib->settings,
                     "%s.plugins.tnc-ifmap.server_uri", IFMAP_URI, lib->ns);
     server_cert = lib->settings->get_str(lib->settings,
                     "%s.plugins.tnc-ifmap.server_cert", NULL, lib->ns);
     client_cert = lib->settings->get_str(lib->settings,
                     "%s.plugins.tnc-ifmap.client_cert", NULL, lib->ns);
     client_key =  lib->settings->get_str(lib->settings,
                     "%s.plugins.tnc-ifmap.client_key", NULL, lib->ns);
     user_pass =   lib->settings->get_str(lib->settings,
                     "%s.plugins.tnc-ifmap.username_password", NULL, lib->ns);
     /* load [self-signed] MAP server certificate */
     if (!server_cert)
     {
         DBG1(DBG_TNC, "MAP server certificate not defined");
         return FALSE;
     }
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_FROM_FILE, server_cert, BUILD_END);
     if (!cert)
     {
         DBG1(DBG_TNC, "loading MAP server certificate from '%s' failed",
                        server_cert);
         return FALSE;
     }
     DBG1(DBG_TNC, "loaded MAP server certificate from '%s'", server_cert);
     server_id = cert->get_subject(cert);
     this->creds->add_cert(this->creds, TRUE, cert);
     /* check availability of client credentials */
     if (!client_cert && !user_pass)
     {
         DBG1(DBG_TNC, "neither MAP client certificate "
                       "nor username:password defined");
         return FALSE;
     }
     if (client_cert)
     {
         /* load MAP client certificate */
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_FROM_FILE, client_cert, BUILD_END);
         if (!cert)
         {
             DBG1(DBG_TNC, "loading MAP client certificate from '%s' failed",
                            client_cert);
             return FALSE;
         }
         DBG1(DBG_TNC, "loaded MAP client certificate from '%s'", client_cert);
         cert = this->creds->add_cert_ref(this->creds, TRUE, cert);
         /* load MAP client private key */
         if (client_key)
         {
             key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                       BUILD_FROM_FILE, client_key, BUILD_END);
             if (!key)
             {
                 DBG1(DBG_TNC, "loading MAP client private key from '%s' failed",
                                client_key);
                 return FALSE;
             }
             DBG1(DBG_TNC, "loaded MAP client RSA private key from '%s'",
                            client_key);
             this->creds->add_key(this->creds, key);
         }
         /* set client ID to certificate distinguished name */
         client_id = cert->get_subject(cert);
         /* check if we have a private key matching the certificate */
         auth = auth_cfg_create();
         auth->add(auth, AUTH_RULE_SUBJECT_CERT, cert);
         key = lib->credmgr->get_private(lib->credmgr, KEY_RSA, client_id, auth);
         auth->destroy(auth);
         if (!key)
         {
             DBG1(DBG_TNC, "no RSA private key matching MAP client certificate");
             return FALSE;
         }
     }
     else
     {
         /* set base64-encoded username:password for HTTP Basic Authentication */
         this->user_pass = chunk_to_base64(chunk_from_str(user_pass), NULL);
     }
     /* remove HTTPS prefix if any */
     if (strlen(server_uri) >= 8 && strncaseeq(server_uri, "https://", 8))
     {
         server_uri += 8;
     }
     this->uri = server_uri;
     /* duplicate server string since we are going to manipulate it */
     server_str = strdup(server_uri);
     /* extract server name and port from server URI */
     port_str = strchr(server_str, ':');
     if (port_str)
     {
         *port_str++ = '\0';
         if (sscanf(port_str, "%d", &port) != 1)
         {
             DBG1(DBG_TNC, "parsing server port %s failed", port_str);
             free(server_str);
             return FALSE;
         }
     }
     else
     {
         /* use default https port */
         port = 443;
         uri_str = strchr(server_str, '/');
         if (uri_str)
         {
             *uri_str = '\0';
         }
     }
     /* open TCP socket and connect to MAP server */
     this->host = host_create_from_dns(server_str, 0, port);
     if (!this->host)
     {
         DBG1(DBG_TNC, "resolving hostname %s failed", server_str);
         free(server_str);
         return FALSE;
     }
     free(server_str);
     this->fd = socket(this->host->get_family(this->host), SOCK_STREAM, 0);
     if (this->fd == IFMAP_NO_FD)
     {
         DBG1(DBG_TNC, "opening socket failed: %s", strerror(errno));
         return FALSE;
     }
     if (connect(this->fd, this->host->get_sockaddr(this->host),
                          *this->host->get_sockaddr_len(this->host)) == -1)
     {
         DBG1(DBG_TNC, "connecting to %#H failed: %s",
                        this->host, strerror(errno));
         return FALSE;
     }
     /* open TLS socket */
     this->tls = tls_socket_create(FALSE, server_id, client_id, this->fd,
                                   NULL, TLS_1_2, FALSE);
     if (!this->tls)
     {
         DBG1(DBG_TNC, "creating TLS socket failed");
         return FALSE;
     }
     return TRUE;
 }