strongSwan: tnccs_batch
tnccs_batch
tnccs_11
Classes
struct tnccs_batch_t
Typedefs
typedef enum tnccs_batch_type_t tnccs_batch_type_t
typedef struct tnccs_batch_t tnccs_batch_t
Functions
tnccs_batch_t * tnccs_batch_create (bool is_server, int batch_id)
tnccs_batch_t * tnccs_batch_create_from_data (bool is_server, int batch_id, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct tnccs_batch_t tnccs_batch_t
Definition at line 25 of file tnccs_batch.h.
typedef enum tnccs_batch_type_t tnccs_batch_type_t
Definition at line 24 of file tnccs_batch.h.
Function Documentation
tnccs_batch_t* tnccs_batch_create (bool is_server, int batch_id)
Create an empty TNCCS 1.x Batch
Parameters
is_server TRUE if server, FALSE if client
batch_id number of the batch to be sent
See header
Definition at line 262 of file tnccs_batch.c.
References DBG2, DBG_TNC, INIT, linked_list_create(), n, SCHEMA_NS, snprintf, TNCCS_NS, and TNCCS_XSD.
Referenced by check_and_build_recommendation(), and METHOD().
 {
     private_tnccs_batch_t *this;
     xmlNodePtr n;
     xmlNsPtr ns_xsi;
     char buf[12];
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .add_msg = _add_msg,
             .build = _build,
             .process = _process,
             .create_msg_enumerator = _create_msg_enumerator,
             .create_error_enumerator = _create_error_enumerator,
             .destroy = _destroy,
         },
         .is_server = is_server,
         .messages = linked_list_create(),
         .errors = linked_list_create(),
         .batch_id = batch_id,
         .doc = xmlNewDoc("1.0"),
     );
     DBG2(DBG_TNC, "creating TNCCS Batch #%d", this->batch_id);
     n = xmlNewNode(NULL, "TNCCS-Batch");
     xmlNewNs(n, TNCCS_NS, NULL);
     ns_xsi = xmlNewNs(n, SCHEMA_NS, "xsi");
     snprintf(buf, sizeof(buf), "%d", batch_id);
     xmlNewProp(n, "BatchId", buf);
     xmlNewProp(n, "Recipient", this->is_server ? "TNCC" : "TNCS");
     xmlNewNsProp(n, ns_xsi, "schemaLocation", TNCCS_NS " " TNCCS_XSD);
     xmlDocSetRootElement(this->doc, n);
     return &this->public;
 }
tnccs_batch_t* tnccs_batch_create_from_data (bool is_server, int batch_id, chunk_t data)
Create an unprocessed TNCCS 1.x Batch from data
Parameters
is_server TRUE if server, FALSE if client
batch_id current Batch ID
data encoded PB-TNC batch
See header
Definition at line 302 of file tnccs_batch.c.
References chunk_clone, INIT, and linked_list_create().
Referenced by METHOD().
 {
     private_tnccs_batch_t *this;
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .add_msg = _add_msg,
             .build = _build,
             .process = _process,
             .create_msg_enumerator = _create_msg_enumerator,
             .create_error_enumerator = _create_error_enumerator,
             .destroy = _destroy,
         },
         .is_server = is_server,
         .batch_id = batch_id,
         .messages = linked_list_create(),
         .errors = linked_list_create(),
         .encoding = chunk_clone(data),
     );
     return &this->public;
 }