strongSwan: ietf_attr_numeric_version
ietf_attr_numeric_version
ietf_attr
Classes
struct ietf_attr_numeric_version_t
Typedefs
typedef struct
ietf_attr_numeric_version_t ietf_attr_numeric_version_t
Functions
pa_tnc_attr_t * ietf_attr_numeric_version_create (u_int32_t major, u_int32_t minor, u_int32_t build, u_int16_t service_pack_major, u_int16_t service_pack_minor)
pa_tnc_attr_t * ietf_attr_numeric_version_create_from_data (size_t length, chunk_t value)
Detailed Description
Typedef Documentation
typedef struct ietf_attr_numeric_version_t ietf_attr_numeric_version_t
Definition at line 24 of file ietf_attr_numeric_version.h.
Function Documentation
pa_tnc_attr_t* ietf_attr_numeric_version_create (u_int32_t major, u_int32_t minor, u_int32_t build, u_int16_t service_pack_major, u_int16_t service_pack_minor)
Creates an ietf_attr_numeric_version_t object
Described in header.
Definition at line 235 of file ietf_attr_numeric_version.c.
References build(), IETF_ATTR_NUMERIC_VERSION, INIT, and PEN_IETF.
Referenced by add_numeric_version().
 {
     private_ietf_attr_numeric_version_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_version = _get_version,
             .get_build = _get_build,
             .get_service_pack = _get_service_pack,
         },
         .type = { PEN_IETF, IETF_ATTR_NUMERIC_VERSION },
         .major_version = major,
         .minor_version = minor,
         .build = build,
         .service_pack_major = service_pack_major,
         .service_pack_minor = service_pack_minor,
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ietf_attr_numeric_version_create_from_data (size_t length, chunk_t data)
Creates an ietf_attr_numeric_version_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 274 of file ietf_attr_numeric_version.c.
References chunk_clone, IETF_ATTR_NUMERIC_VERSION, INIT, length, and PEN_IETF.
Referenced by ietf_attr_create_from_data().
 {
     private_ietf_attr_numeric_version_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_version = _get_version,
             .get_build = _get_build,
             .get_service_pack = _get_service_pack,
         },
         .type = { PEN_IETF, IETF_ATTR_NUMERIC_VERSION },
         .length = length,
         .value = chunk_clone(data),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }