strongSwan: pb_tnc_batch_t Struct Reference
pb_tnc_batch_t Struct Reference
pb_tnc_batch
#include "pb_tnc_batch.h"
Public Attributes
pb_tnc_batch_type_t(* get_type)(pb_tnc_batch_t *this)
chunk_t(* get_encoding)(pb_tnc_batch_t *this)
bool(* add_msg)(pb_tnc_batch_t *this, pb_tnc_msg_t *msg)
void(* build)(pb_tnc_batch_t *this)
status_t(* process_header)(pb_tnc_batch_t *this, bool directionality, bool is_server, bool *from_server)
status_t(* process)(pb_tnc_batch_t *this, pb_tnc_state_machine_t *state_machine)
enumerator_t *(* create_msg_enumerator)(pb_tnc_batch_t *this)
enumerator_t *(* create_error_enumerator)(pb_tnc_batch_t *this)
void(* destroy)(pb_tnc_batch_t *this)
Detailed Description
Interface for all PB-TNC Batch Types.
Definition at line 57 of file pb_tnc_batch.h.
Member Data Documentation
bool(* pb_tnc_batch_t::add_msg)(pb_tnc_batch_t *this, pb_tnc_msg_t *msg)
Add a PB-TNC Message
Parameters
msg PB-TNC message to be addedd
Returns
TRUE if message fit into batch and was added
Definition at line 79 of file pb_tnc_batch.h.
Referenced by METHOD().
void(* pb_tnc_batch_t::build)(pb_tnc_batch_t *this)
Build the PB-TNC Batch
Definition at line 84 of file pb_tnc_batch.h.
Referenced by METHOD().
enumerator_t*(* pb_tnc_batch_t::create_error_enumerator)(pb_tnc_batch_t *this)
Enumerates over all parsing errors
Returns
return error enumerator
Definition at line 118 of file pb_tnc_batch.h.
Referenced by METHOD().
enumerator_t*(* pb_tnc_batch_t::create_msg_enumerator)(pb_tnc_batch_t *this)
Enumerates over all PB-TNC Messages
Returns
return message enumerator
Definition at line 111 of file pb_tnc_batch.h.
Referenced by METHOD().
void(* pb_tnc_batch_t::destroy)(pb_tnc_batch_t *this)
Destroys a pb_tnc_batch_t object.
Definition at line 123 of file pb_tnc_batch.h.
Referenced by METHOD().
chunk_t(* pb_tnc_batch_t::get_encoding)(pb_tnc_batch_t *this)
Get the encoding of the PB-TNC Batch
Returns
encoded PB-TNC batch
Definition at line 71 of file pb_tnc_batch.h.
Referenced by METHOD().
pb_tnc_batch_type_t(* pb_tnc_batch_t::get_type)(pb_tnc_batch_t *this)
Get the PB-TNC Message Type
Returns
PB-TNC batch type
Definition at line 64 of file pb_tnc_batch.h.
Referenced by METHOD().
status_t(* pb_tnc_batch_t::process)(pb_tnc_batch_t *this, pb_tnc_state_machine_t *state_machine)
Process the PB-TNC Batch
Parameters
state_machine PB-TNC state machine
Returns
return processing status
Definition at line 103 of file pb_tnc_batch.h.
Referenced by METHOD().
status_t(* pb_tnc_batch_t::process_header)(pb_tnc_batch_t *this, bool directionality, bool is_server, bool *from_server)
Process the PB-TNC Batch header
Parameters
directionality TRUE if no mutual TNC measurements
is_server TRUE if called by TNC server
from_server TRUE if sent by TNC server
Returns
return processing status
Definition at line 94 of file pb_tnc_batch.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
pb_tnc_batch.h