strongSwan: tcg_pts_attr_req_func_comp_evid
tcg_pts_attr_req_func_comp_evid
tcg_attr
Classes
struct tcg_pts_attr_req_func_comp_evid_t
Typedefs
typedef struct
tcg_pts_attr_req_func_comp_evid_t tcg_pts_attr_req_func_comp_evid_t
Functions
pa_tnc_attr_t * tcg_pts_attr_req_func_comp_evid_create (void)
pa_tnc_attr_t * tcg_pts_attr_req_func_comp_evid_create_from_data (size_t length, chunk_t value)
Detailed Description
Typedef Documentation
typedef struct tcg_pts_attr_req_func_comp_evid_t tcg_pts_attr_req_func_comp_evid_t
Definition at line 25 of file tcg_pts_attr_req_func_comp_evid.h.
Function Documentation
pa_tnc_attr_t* tcg_pts_attr_req_func_comp_evid_create (void)
Creates a tcg_pts_attr_req_func_comp_evid_t object
Described in header.
Definition at line 327 of file tcg_pts_attr_req_func_comp_evid.c.
References INIT, linked_list_create(), PEN_TCG, and TCG_PTS_REQ_FUNC_COMP_EVID.
Referenced by imv_attestation_build().
 {
     private_tcg_pts_attr_req_func_comp_evid_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add_component = _add_component,
             .get_count = _get_count,
             .create_enumerator = _create_enumerator,
         },
         .type = { PEN_TCG, TCG_PTS_REQ_FUNC_COMP_EVID },
         .list = linked_list_create(),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* tcg_pts_attr_req_func_comp_evid_create_from_data (size_t length, chunk_t data)
Creates a tcg_pts_attr_req_func_comp_evid_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 359 of file tcg_pts_attr_req_func_comp_evid.c.
References chunk_clone, INIT, length, linked_list_create(), PEN_TCG, and TCG_PTS_REQ_FUNC_COMP_EVID.
Referenced by tcg_attr_create_from_data().
 {
     private_tcg_pts_attr_req_func_comp_evid_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add_component = _add_component,
             .get_count = _get_count,
             .create_enumerator = _create_enumerator,
         },
         .type = { PEN_TCG, TCG_PTS_REQ_FUNC_COMP_EVID },
         .length = length,
         .list = linked_list_create(),
         .value = chunk_clone(data),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }