strongSwan: imv_test_state
imv_test_state
imv_test
Classes
struct imv_test_state_t
Typedefs
typedef struct imv_test_state_t imv_test_state_t
Functions
imv_state_t * imv_test_state_create (TNC_ConnectionID id)
Detailed Description
Typedef Documentation
typedef struct imv_test_state_t imv_test_state_t
Definition at line 29 of file imv_test_state.h.
Function Documentation
imv_state_t* imv_test_state_create (TNC_ConnectionID connection_id)
Create an imv_test_state_t instance
Parameters
id connection ID
Described in header.
Definition at line 307 of file imv_test_state.c.
References INIT, linked_list_create(), seg_contract_manager_create(), TNC_CONNECTION_STATE_CREATE, TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION, and TNC_IMV_EVALUATION_RESULT_DONT_KNOW.
Referenced by METHOD().
 {
     private_imv_test_state_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_connection_id = _get_connection_id,
                 .has_long = _has_long,
                 .has_excl = _has_excl,
                 .set_flags = _set_flags,
                 .set_max_msg_len = _set_max_msg_len,
                 .get_max_msg_len = _get_max_msg_len,
                 .set_session = _set_session,
                 .get_session = _get_session,
                 .get_contracts = _get_contracts,
                 .change_state = _change_state,
                 .get_recommendation = _get_recommendation,
                 .set_recommendation = _set_recommendation,
                 .update_recommendation = _update_recommendation,
                 .get_reason_string = _get_reason_string,
                 .get_remediation_instructions = _get_remediation_instructions,
                 .destroy = _destroy,
             },
             .add_imc = _add_imc,
             .set_rounds = _set_rounds,
             .another_round = _another_round,
         },
         .state = TNC_CONNECTION_STATE_CREATE,
         .rec = TNC_IMV_ACTION_RECOMMENDATION_NO_RECOMMENDATION,
         .eval = TNC_IMV_EVALUATION_RESULT_DONT_KNOW,
         .connection_id = connection_id,
         .contracts = seg_contract_manager_create(),
         .imcs = linked_list_create(),
     );
     return &this->public.interface;
 }