strongSwan: container_t Struct Reference
container_t Struct Reference
container
#include "container.h"
Public Attributes
container_type_t(* get_type)(container_t *this)
enumerator_t *(* create_signature_enumerator)(container_t *this)
bool(* get_data)(container_t *this, chunk_t *data)
bool(* get_encoding)(container_t *this, chunk_t *encoding)
void(* destroy)(container_t *this)
Detailed Description
Generic interface for cryptographic containers.
Definition at line 59 of file container.h.
Member Data Documentation
enumerator_t*(* container_t::create_signature_enumerator)(container_t *this)
Create an enumerator over trustchains for valid container signatures.
Returns
enumerator over auth_cfg_t*
Definition at line 73 of file container.h.
Referenced by parse_PFX(), scep_parse_response(), and verify().
void(* container_t::destroy)(container_t *this)
Destroy a container_t.
Definition at line 97 of file container.h.
Referenced by decrypt(), encrypt(), load_encrypted_container(), load_pkcs12(), main(), parse_authenticated_safe(), pkcs12(), process_pkcs7(), scep_build_request(), scep_parse_response(), show(), sign(), and verify().
bool(* container_t::get_data)(container_t *this, chunk_t *data)
Get signed/decrypted data wrapped in this container.
This function does not verify any associated signatures, use create_signature_enumerator() to verify them.
Parameters
data allocated data wrapped in this container
Returns
TRUE if data decrypted successfully
Definition at line 84 of file container.h.
Referenced by decrypt(), main(), parse_authenticated_safe(), parse_PFX(), and verify().
bool(* container_t::get_encoding)(container_t *this, chunk_t *encoding)
Get the encoding of the full signed/encrypted container.
Parameters
data allocated container encoding
Returns
TRUE if encodign successful
Definition at line 92 of file container.h.
Referenced by encrypt(), scep_build_request(), and sign().
container_type_t(* container_t::get_type)(container_t *this)
Get the type of the container.
Returns
container type
Definition at line 66 of file container.h.
Referenced by decrypt(), load_encrypted_container(), parse_authenticated_safe(), parse_PFX(), process_pkcs7(), scep_parse_response(), show(), and verify().
The documentation for this struct was generated from the following file:
container.h