strongSwan: winhttp_fetcher
winhttp_fetcher
winhttp
Classes
struct winhttp_fetcher_t
Typedefs
typedef struct winhttp_fetcher_t winhttp_fetcher_t
Functions
winhttp_fetcher_t * winhttp_fetcher_create ()
Detailed Description
Typedef Documentation
typedef struct winhttp_fetcher_t winhttp_fetcher_t
Definition at line 26 of file winhttp_fetcher.h.
Function Documentation
winhttp_fetcher_t* winhttp_fetcher_create ()
Create a winhttp_fetcher instance
Returns
WinHTTP based fetcher
Definition at line 368 of file winhttp_fetcher.c.
References fetcher_default_callback(), free(), INIT, and linked_list_create().
Referenced by METHOD().
 {
     private_winhttp_fetcher_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .fetch = _fetch,
                 .set_option = _set_option,
                 .destroy = _destroy,
             },
         },
         .version = L"HTTP/1.1",
         .cb = fetcher_default_callback,
         .headers = linked_list_create(),
         .session = WinHttpOpen(L"strongSwan WinHTTP fetcher",
                             WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,
                             WINHTTP_NO_PROXY_NAME,
                             WINHTTP_NO_PROXY_BYPASS, 0),
     );
     if (!this->session)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }