strongSwan: medcli_creds.c File Reference
medcli_creds.c File Reference
#include "medcli_creds.h"
#include <daemon.h>
#include <library.h>
#include <collections/enumerator.h>
Classes
struct private_medcli_creds_t
struct private_enumerator_t
struct cert_enumerator_t
Typedefs
typedef struct
private_medcli_creds_t private_medcli_creds_t
Functions
METHOD (enumerator_t, private_enumerator_enumerate, bool, private_enumerator_t *this, private_key_t **key)
METHOD (enumerator_t, private_enumerator_destroy, void, private_enumerator_t *this)
METHOD (credential_set_t, create_private_enumerator, enumerator_t *, private_medcli_creds_t *this, key_type_t type, identification_t *id)
METHOD (enumerator_t, cert_enumerator_enumerate, bool, cert_enumerator_t *this, certificate_t **cert)
METHOD (enumerator_t, cert_enumerator_destroy, void, cert_enumerator_t *this)
METHOD (credential_set_t, create_cert_enumerator, enumerator_t *, private_medcli_creds_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
METHOD (medcli_creds_t, destroy, void, private_medcli_creds_t *this)
medcli_creds_t * medcli_creds_create (database_t *db)
Typedef Documentation
typedef struct private_medcli_creds_t private_medcli_creds_t
Definition at line 22 of file medcli_creds.c.
Function Documentation
METHOD (enumerator_t , private_enumerator_enumerate , bool , private_enumerator_t * this, private_key_t ** key)
Definition at line 52 of file medcli_creds.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, DESTROY_IF, FALSE, KEY_RSA, lib, and TRUE.
 {
     chunk_t chunk;
     DESTROY_IF(this->current);
     while (this->inner->enumerate(this->inner, &chunk))
     {
         this->current = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                            BUILD_BLOB_ASN1_DER, chunk,
                                            BUILD_END);
         if (this->current)
         {
             *key = this->current;
             return TRUE;
         }
     }
     this->current = NULL;
     return FALSE;
 }
METHOD (enumerator_t , private_enumerator_destroy , void , private_enumerator_t * this)
Definition at line 73 of file medcli_creds.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_private_enumerator , enumerator_t * , private_medcli_creds_t * this, key_type_t type, identification_t * id)
Definition at line 81 of file medcli_creds.c.
References db, DB_BLOB, DBG1, DBG_CFG, destroy(), free(), identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, INIT, private_enumerator_t::inner, KEY_ANY, KEY_RSA, key_type_names, private_enumerator_t::public, and database_t::query.
 {
     private_enumerator_t *e;
     if ((type != KEY_RSA && type != KEY_ANY) ||
         id == NULL || id->get_type(id) != ID_KEY_ID)
     {
         DBG1(DBG_CFG, "%N - %Y", key_type_names, type, id);
         return NULL;
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_private_enumerator_enumerate,
             .destroy = _private_enumerator_destroy,
         },
     );
     e->inner = this->db->query(this->db,
                         "SELECT PrivateKey FROM ClientConfig WHERE KeyId = ?",
                         DB_BLOB, id->get_encoding(id),
                         DB_BLOB);
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (enumerator_t , cert_enumerator_enumerate , bool , cert_enumerator_t * this, certificate_t ** cert)
Definition at line 125 of file medcli_creds.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_PUBLIC_KEY, CERT_TRUSTED_PUBKEY, credential_factory_t::create, CRED_CERTIFICATE, CRED_PUBLIC_KEY, library_t::creds, DESTROY_IF, FALSE, KEY_ANY, lib, public, and TRUE.
 {
     public_key_t *public;
     chunk_t chunk;
     DESTROY_IF(this->current);
     while (this->inner->enumerate(this->inner, &chunk))
     {
         public = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_ANY,
                                     BUILD_BLOB_ASN1_DER, chunk,
                                     BUILD_END);
         if (public)
         {
             if (this->type == KEY_ANY || this->type == public->get_type(public))
             {
                 this->current = lib->creds->create(lib->creds,
                                         CRED_CERTIFICATE, CERT_TRUSTED_PUBKEY,
                                         BUILD_PUBLIC_KEY, public, BUILD_END);
                 public->destroy(public);
                 if (this->current)
                 {
                     *cert = this->current;
                     return TRUE;
                 }
             }
             else
             {
                 public->destroy(public);
             }
         }
     }
     this->current = NULL;
     return FALSE;
 }
METHOD (enumerator_t , cert_enumerator_destroy , void , cert_enumerator_t * this)
Definition at line 161 of file medcli_creds.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (credential_set_t , create_cert_enumerator , enumerator_t * , private_medcli_creds_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 169 of file medcli_creds.c.
References CERT_ANY, CERT_TRUSTED_PUBKEY, db, DB_BLOB, destroy(), free(), identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, INIT, cert_enumerator_t::inner, cert_enumerator_t::public, and database_t::query.
 {
     cert_enumerator_t *e;
     if ((cert != CERT_TRUSTED_PUBKEY && cert != CERT_ANY) ||
         id == NULL || id->get_type(id) != ID_KEY_ID)
     {
         return NULL;
     }
     INIT(e,
         .public = {
             .enumerate = (void*)_cert_enumerator_enumerate,
             .destroy = _cert_enumerator_destroy,
         },
         .type = key,
     );
     e->inner = this->db->query(this->db,
             "SELECT PublicKey FROM ClientConfig WHERE KeyId = ? UNION "
             "SELECT PublicKey FROM MediationServerConfig WHERE KeyId = ? UNION "
             "SELECT PublicKey FROM Connection WHERE KeyId = ?",
             DB_BLOB, id->get_encoding(id),
             DB_BLOB, id->get_encoding(id),
             DB_BLOB, id->get_encoding(id),
             DB_BLOB);
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (medcli_creds_t , destroy , void , private_medcli_creds_t * this)
Definition at line 204 of file medcli_creds.c.
References free().
 {
     free(this);
 }