strongSwan: pts_comp_func_name_t Struct Reference
pts_comp_func_name_t Struct Reference
pts_comp_func_name
#include "pts_comp_func_name.h"
Public Attributes
u_int32_t(* get_vendor_id)(pts_comp_func_name_t *this)
u_int32_t(* get_name)(pts_comp_func_name_t *this)
u_int8_t(* get_qualifier)(pts_comp_func_name_t *this)
void(* set_qualifier)(pts_comp_func_name_t *this, u_int8_t qualifier)
bool(* equals)(pts_comp_func_name_t *this, pts_comp_func_name_t *other)
pts_comp_func_name_t *(* clone)(pts_comp_func_name_t *this)
void(* log)(pts_comp_func_name_t *this, char *label)
void(* destroy)(pts_comp_func_name_t *this)
Detailed Description
PTS Component Functional Name object
Definition at line 34 of file pts_comp_func_name.h.
Member Data Documentation
pts_comp_func_name_t*(* pts_comp_func_name_t::clone)(pts_comp_func_name_t *this)
Clone a PTS Component Functional Name
Returns
Cloned PTS Component Functional Name
Definition at line 77 of file pts_comp_func_name.h.
Referenced by extend_pcr(), and METHOD().
void(* pts_comp_func_name_t::destroy)(pts_comp_func_name_t *this)
Destroys a pts_component_t object.
Definition at line 89 of file pts_comp_func_name.h.
Referenced by METHOD().
bool(* pts_comp_func_name_t::equals)(pts_comp_func_name_t *this, pts_comp_func_name_t *other)
Check to PTS Component Functional Names for equality
Parameters
other Other PTS Component Functional Name
Returns
TRUE if equal
Definition at line 70 of file pts_comp_func_name.h.
Referenced by METHOD().
u_int32_t(* pts_comp_func_name_t::get_name)(pts_comp_func_name_t *this)
Get the PTS Component Functional Name
Returns
PTS Component Functional Name
Definition at line 48 of file pts_comp_func_name.h.
Referenced by METHOD(), and print_cfn().
u_int8_t(* pts_comp_func_name_t::get_qualifier)(pts_comp_func_name_t *this)
Get the PTS Component Functional Name Qualifier
Returns
PTS Component Functional Name Qualifier
Definition at line 55 of file pts_comp_func_name.h.
Referenced by imc_attestation_process(), imv_attestation_process(), METHOD(), and print_cfn().
u_int32_t(* pts_comp_func_name_t::get_vendor_id)(pts_comp_func_name_t *this)
Get the PTS Component Functional Name Vendor ID
Returns
PTS Component Functional Name Vendor ID
Definition at line 41 of file pts_comp_func_name.h.
Referenced by METHOD(), and print_cfn().
void(* pts_comp_func_name_t::log)(pts_comp_func_name_t *this, char *label)
Write PTS Component Functional Name information to the standard logfile
Parameters
label Label added to log output
Definition at line 84 of file pts_comp_func_name.h.
Referenced by imc_attestation_process(), imv_attestation_build(), imv_attestation_process(), METHOD(), and pts_comp_evidence_create().
void(* pts_comp_func_name_t::set_qualifier)(pts_comp_func_name_t *this, u_int8_t qualifier)
Set the PTS Component Functional Name Qualifier
Parameters
qualifier PTS Component Functional Name Qualifier to be set
Definition at line 62 of file pts_comp_func_name.h.
Referenced by extend_pcr().
The documentation for this struct was generated from the following file:
pts_comp_func_name.h