strongSwan: aesni_cbc.c File Reference
aesni_cbc.c File Reference
#include "aesni_cbc.h"
#include "aesni_key.h"
Classes
struct private_aesni_cbc_t
Macros
#define CBC_DECRYPT_PARALLELISM 4
Typedefs
typedef struct private_aesni_cbc_t private_aesni_cbc_t
typedef void(* aesni_cbc_fn_t)(aesni_key_t *, u_int, u_char *, u_char *, u_char *)
Functions
static void encrypt_cbc128 (aesni_key_t *key, u_int blocks, u_char *in, u_char *iv, u_char *out)
static void decrypt_cbc128 (aesni_key_t *key, u_int blocks, u_char *in, u_char *iv, u_char *out)
static void encrypt_cbc192 (aesni_key_t *key, u_int blocks, u_char *in, u_char *iv, u_char *out)
static void decrypt_cbc192 (aesni_key_t *key, u_int blocks, u_char *in, u_char *iv, u_char *out)
static void encrypt_cbc256 (aesni_key_t *key, u_int blocks, u_char *in, u_char *iv, u_char *out)
static void decrypt_cbc256 (aesni_key_t *key, u_int blocks, u_char *in, u_char *iv, u_char *out)
static bool crypt (aesni_cbc_fn_t fn, aesni_key_t *key, chunk_t data, chunk_t iv, chunk_t *out)
METHOD (crypter_t, encrypt, bool, private_aesni_cbc_t *this, chunk_t data, chunk_t iv, chunk_t *encrypted)
METHOD (crypter_t, decrypt, bool, private_aesni_cbc_t *this, chunk_t data, chunk_t iv, chunk_t *decrypted)
METHOD (crypter_t, get_block_size, size_t, private_aesni_cbc_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_aesni_cbc_t *this)
METHOD (crypter_t, get_key_size, size_t, private_aesni_cbc_t *this)
METHOD (crypter_t, set_key, bool, private_aesni_cbc_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_aesni_cbc_t *this)
aesni_cbc_t * aesni_cbc_create (encryption_algorithm_t algo, size_t key_size)
Macro Definition Documentation
#define CBC_DECRYPT_PARALLELISM 4
Pipeline parallelism we use for CBC decryption
Definition at line 22 of file aesni_cbc.c.
Referenced by decrypt_cbc128(), decrypt_cbc192(), and decrypt_cbc256().
Typedef Documentation
typedef void(* aesni_cbc_fn_t)(aesni_key_t *, u_int, u_char *, u_char *, u_char *)
CBC en/decryption method type
Definition at line 29 of file aesni_cbc.c.
typedef struct private_aesni_cbc_t private_aesni_cbc_t
Definition at line 24 of file aesni_cbc.c.
Function Documentation
static bool crypt (aesni_cbc_fn_t fn, aesni_key_t * key, chunk_t data, chunk_t iv, chunk_t * out) static
Do inline or allocated de/encryption using key schedule
Definition at line 538 of file aesni_cbc.c.
References AES_BLOCK_SIZE, chunk_alloc, FALSE, fn, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by decrypt_content(), encrypt_content(), and METHOD().
 {
     u_char *buf;
     if (!key || iv.len != AES_BLOCK_SIZE || data.len % AES_BLOCK_SIZE)
     {
         return FALSE;
     }
     if (out)
     {
         *out = chunk_alloc(data.len);
         buf = out->ptr;
     }
     else
     {
         buf = data.ptr;
     }
     fn(key, data.len / AES_BLOCK_SIZE, data.ptr, iv.ptr, buf);
     return TRUE;
 }
static void decrypt_cbc128 (aesni_key_t * key, u_int blocks, u_char * in, u_char * iv, u_char * out) static
AES-128 CBC decryption
Definition at line 105 of file aesni_cbc.c.
References CBC_DECRYPT_PARALLELISM.
Referenced by aesni_cbc_create().
 {
     __m128i *ks, last, *bi, *bo;
     __m128i t1, t2, t3, t4;
     __m128i f1, f2, f3, f4;
     u_int i, pblocks;
     ks = key->schedule;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     pblocks = blocks - (blocks % CBC_DECRYPT_PARALLELISM);
     f1 = _mm_loadu_si128((__m128i*)iv);
     for (i = 0; i < pblocks; i += CBC_DECRYPT_PARALLELISM)
     {
         t1 = _mm_loadu_si128(bi + i + 0);
         t2 = _mm_loadu_si128(bi + i + 1);
         t3 = _mm_loadu_si128(bi + i + 2);
         t4 = _mm_loadu_si128(bi + i + 3);
         f2 = t1;
         f3 = t2;
         f4 = t3;
         last = t4;
         t1 = _mm_xor_si128(t1, ks[0]);
         t2 = _mm_xor_si128(t2, ks[0]);
         t3 = _mm_xor_si128(t3, ks[0]);
         t4 = _mm_xor_si128(t4, ks[0]);
         t1 = _mm_aesdec_si128(t1, ks[1]);
         t2 = _mm_aesdec_si128(t2, ks[1]);
         t3 = _mm_aesdec_si128(t3, ks[1]);
         t4 = _mm_aesdec_si128(t4, ks[1]);
         t1 = _mm_aesdec_si128(t1, ks[2]);
         t2 = _mm_aesdec_si128(t2, ks[2]);
         t3 = _mm_aesdec_si128(t3, ks[2]);
         t4 = _mm_aesdec_si128(t4, ks[2]);
         t1 = _mm_aesdec_si128(t1, ks[3]);
         t2 = _mm_aesdec_si128(t2, ks[3]);
         t3 = _mm_aesdec_si128(t3, ks[3]);
         t4 = _mm_aesdec_si128(t4, ks[3]);
         t1 = _mm_aesdec_si128(t1, ks[4]);
         t2 = _mm_aesdec_si128(t2, ks[4]);
         t3 = _mm_aesdec_si128(t3, ks[4]);
         t4 = _mm_aesdec_si128(t4, ks[4]);
         t1 = _mm_aesdec_si128(t1, ks[5]);
         t2 = _mm_aesdec_si128(t2, ks[5]);
         t3 = _mm_aesdec_si128(t3, ks[5]);
         t4 = _mm_aesdec_si128(t4, ks[5]);
         t1 = _mm_aesdec_si128(t1, ks[6]);
         t2 = _mm_aesdec_si128(t2, ks[6]);
         t3 = _mm_aesdec_si128(t3, ks[6]);
         t4 = _mm_aesdec_si128(t4, ks[6]);
         t1 = _mm_aesdec_si128(t1, ks[7]);
         t2 = _mm_aesdec_si128(t2, ks[7]);
         t3 = _mm_aesdec_si128(t3, ks[7]);
         t4 = _mm_aesdec_si128(t4, ks[7]);
         t1 = _mm_aesdec_si128(t1, ks[8]);
         t2 = _mm_aesdec_si128(t2, ks[8]);
         t3 = _mm_aesdec_si128(t3, ks[8]);
         t4 = _mm_aesdec_si128(t4, ks[8]);
         t1 = _mm_aesdec_si128(t1, ks[9]);
         t2 = _mm_aesdec_si128(t2, ks[9]);
         t3 = _mm_aesdec_si128(t3, ks[9]);
         t4 = _mm_aesdec_si128(t4, ks[9]);
         t1 = _mm_aesdeclast_si128(t1, ks[10]);
         t2 = _mm_aesdeclast_si128(t2, ks[10]);
         t3 = _mm_aesdeclast_si128(t3, ks[10]);
         t4 = _mm_aesdeclast_si128(t4, ks[10]);
         t1 = _mm_xor_si128(t1, f1);
         t2 = _mm_xor_si128(t2, f2);
         t3 = _mm_xor_si128(t3, f3);
         t4 = _mm_xor_si128(t4, f4);
         _mm_storeu_si128(bo + i + 0, t1);
         _mm_storeu_si128(bo + i + 1, t2);
         _mm_storeu_si128(bo + i + 2, t3);
         _mm_storeu_si128(bo + i + 3, t4);
         f1 = last;
     }
     for (i = pblocks; i < blocks; i++)
     {
         last = _mm_loadu_si128(bi + i);
         t1 = _mm_xor_si128(last, ks[0]);
         t1 = _mm_aesdec_si128(t1, ks[1]);
         t1 = _mm_aesdec_si128(t1, ks[2]);
         t1 = _mm_aesdec_si128(t1, ks[3]);
         t1 = _mm_aesdec_si128(t1, ks[4]);
         t1 = _mm_aesdec_si128(t1, ks[5]);
         t1 = _mm_aesdec_si128(t1, ks[6]);
         t1 = _mm_aesdec_si128(t1, ks[7]);
         t1 = _mm_aesdec_si128(t1, ks[8]);
         t1 = _mm_aesdec_si128(t1, ks[9]);
         t1 = _mm_aesdeclast_si128(t1, ks[10]);
         t1 = _mm_xor_si128(t1, f1);
         _mm_storeu_si128(bo + i, t1);
         f1 = last;
     }
 }
static void decrypt_cbc192 (aesni_key_t * key, u_int blocks, u_char * in, u_char * iv, u_char * out) static
AES-192 CBC decryption
Definition at line 251 of file aesni_cbc.c.
References CBC_DECRYPT_PARALLELISM.
Referenced by aesni_cbc_create().
 {
     __m128i *ks, last, *bi, *bo;
     __m128i t1, t2, t3, t4;
     __m128i f1, f2, f3, f4;
     u_int i, pblocks;
     ks = key->schedule;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     pblocks = blocks - (blocks % CBC_DECRYPT_PARALLELISM);
     f1 = _mm_loadu_si128((__m128i*)iv);
     for (i = 0; i < pblocks; i += CBC_DECRYPT_PARALLELISM)
     {
         t1 = _mm_loadu_si128(bi + i + 0);
         t2 = _mm_loadu_si128(bi + i + 1);
         t3 = _mm_loadu_si128(bi + i + 2);
         t4 = _mm_loadu_si128(bi + i + 3);
         f2 = t1;
         f3 = t2;
         f4 = t3;
         last = t4;
         t1 = _mm_xor_si128(t1, ks[0]);
         t2 = _mm_xor_si128(t2, ks[0]);
         t3 = _mm_xor_si128(t3, ks[0]);
         t4 = _mm_xor_si128(t4, ks[0]);
         t1 = _mm_aesdec_si128(t1, ks[1]);
         t2 = _mm_aesdec_si128(t2, ks[1]);
         t3 = _mm_aesdec_si128(t3, ks[1]);
         t4 = _mm_aesdec_si128(t4, ks[1]);
         t1 = _mm_aesdec_si128(t1, ks[2]);
         t2 = _mm_aesdec_si128(t2, ks[2]);
         t3 = _mm_aesdec_si128(t3, ks[2]);
         t4 = _mm_aesdec_si128(t4, ks[2]);
         t1 = _mm_aesdec_si128(t1, ks[3]);
         t2 = _mm_aesdec_si128(t2, ks[3]);
         t3 = _mm_aesdec_si128(t3, ks[3]);
         t4 = _mm_aesdec_si128(t4, ks[3]);
         t1 = _mm_aesdec_si128(t1, ks[4]);
         t2 = _mm_aesdec_si128(t2, ks[4]);
         t3 = _mm_aesdec_si128(t3, ks[4]);
         t4 = _mm_aesdec_si128(t4, ks[4]);
         t1 = _mm_aesdec_si128(t1, ks[5]);
         t2 = _mm_aesdec_si128(t2, ks[5]);
         t3 = _mm_aesdec_si128(t3, ks[5]);
         t4 = _mm_aesdec_si128(t4, ks[5]);
         t1 = _mm_aesdec_si128(t1, ks[6]);
         t2 = _mm_aesdec_si128(t2, ks[6]);
         t3 = _mm_aesdec_si128(t3, ks[6]);
         t4 = _mm_aesdec_si128(t4, ks[6]);
         t1 = _mm_aesdec_si128(t1, ks[7]);
         t2 = _mm_aesdec_si128(t2, ks[7]);
         t3 = _mm_aesdec_si128(t3, ks[7]);
         t4 = _mm_aesdec_si128(t4, ks[7]);
         t1 = _mm_aesdec_si128(t1, ks[8]);
         t2 = _mm_aesdec_si128(t2, ks[8]);
         t3 = _mm_aesdec_si128(t3, ks[8]);
         t4 = _mm_aesdec_si128(t4, ks[8]);
         t1 = _mm_aesdec_si128(t1, ks[9]);
         t2 = _mm_aesdec_si128(t2, ks[9]);
         t3 = _mm_aesdec_si128(t3, ks[9]);
         t4 = _mm_aesdec_si128(t4, ks[9]);
         t1 = _mm_aesdec_si128(t1, ks[10]);
         t2 = _mm_aesdec_si128(t2, ks[10]);
         t3 = _mm_aesdec_si128(t3, ks[10]);
         t4 = _mm_aesdec_si128(t4, ks[10]);
         t1 = _mm_aesdec_si128(t1, ks[11]);
         t2 = _mm_aesdec_si128(t2, ks[11]);
         t3 = _mm_aesdec_si128(t3, ks[11]);
         t4 = _mm_aesdec_si128(t4, ks[11]);
         t1 = _mm_aesdeclast_si128(t1, ks[12]);
         t2 = _mm_aesdeclast_si128(t2, ks[12]);
         t3 = _mm_aesdeclast_si128(t3, ks[12]);
         t4 = _mm_aesdeclast_si128(t4, ks[12]);
         t1 = _mm_xor_si128(t1, f1);
         t2 = _mm_xor_si128(t2, f2);
         t3 = _mm_xor_si128(t3, f3);
         t4 = _mm_xor_si128(t4, f4);
         _mm_storeu_si128(bo + i + 0, t1);
         _mm_storeu_si128(bo + i + 1, t2);
         _mm_storeu_si128(bo + i + 2, t3);
         _mm_storeu_si128(bo + i + 3, t4);
         f1 = last;
     }
     for (i = pblocks; i < blocks; i++)
     {
         last = _mm_loadu_si128(bi + i);
         t1 = _mm_xor_si128(last, ks[0]);
         t1 = _mm_aesdec_si128(t1, ks[1]);
         t1 = _mm_aesdec_si128(t1, ks[2]);
         t1 = _mm_aesdec_si128(t1, ks[3]);
         t1 = _mm_aesdec_si128(t1, ks[4]);
         t1 = _mm_aesdec_si128(t1, ks[5]);
         t1 = _mm_aesdec_si128(t1, ks[6]);
         t1 = _mm_aesdec_si128(t1, ks[7]);
         t1 = _mm_aesdec_si128(t1, ks[8]);
         t1 = _mm_aesdec_si128(t1, ks[9]);
         t1 = _mm_aesdec_si128(t1, ks[10]);
         t1 = _mm_aesdec_si128(t1, ks[11]);
         t1 = _mm_aesdeclast_si128(t1, ks[12]);
         t1 = _mm_xor_si128(t1, f1);
         _mm_storeu_si128(bo + i, t1);
         f1 = last;
     }
 }
static void decrypt_cbc256 (aesni_key_t * key, u_int blocks, u_char * in, u_char * iv, u_char * out) static
AES-256 CBC decryption
Definition at line 409 of file aesni_cbc.c.
References CBC_DECRYPT_PARALLELISM.
Referenced by aesni_cbc_create().
 {
     __m128i *ks, last, *bi, *bo;
     __m128i t1, t2, t3, t4;
     __m128i f1, f2, f3, f4;
     u_int i, pblocks;
     ks = key->schedule;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     pblocks = blocks - (blocks % CBC_DECRYPT_PARALLELISM);
     f1 = _mm_loadu_si128((__m128i*)iv);
     for (i = 0; i < pblocks; i += CBC_DECRYPT_PARALLELISM)
     {
         t1 = _mm_loadu_si128(bi + i + 0);
         t2 = _mm_loadu_si128(bi + i + 1);
         t3 = _mm_loadu_si128(bi + i + 2);
         t4 = _mm_loadu_si128(bi + i + 3);
         f2 = t1;
         f3 = t2;
         f4 = t3;
         last = t4;
         t1 = _mm_xor_si128(t1, ks[0]);
         t2 = _mm_xor_si128(t2, ks[0]);
         t3 = _mm_xor_si128(t3, ks[0]);
         t4 = _mm_xor_si128(t4, ks[0]);
         t1 = _mm_aesdec_si128(t1, ks[1]);
         t2 = _mm_aesdec_si128(t2, ks[1]);
         t3 = _mm_aesdec_si128(t3, ks[1]);
         t4 = _mm_aesdec_si128(t4, ks[1]);
         t1 = _mm_aesdec_si128(t1, ks[2]);
         t2 = _mm_aesdec_si128(t2, ks[2]);
         t3 = _mm_aesdec_si128(t3, ks[2]);
         t4 = _mm_aesdec_si128(t4, ks[2]);
         t1 = _mm_aesdec_si128(t1, ks[3]);
         t2 = _mm_aesdec_si128(t2, ks[3]);
         t3 = _mm_aesdec_si128(t3, ks[3]);
         t4 = _mm_aesdec_si128(t4, ks[3]);
         t1 = _mm_aesdec_si128(t1, ks[4]);
         t2 = _mm_aesdec_si128(t2, ks[4]);
         t3 = _mm_aesdec_si128(t3, ks[4]);
         t4 = _mm_aesdec_si128(t4, ks[4]);
         t1 = _mm_aesdec_si128(t1, ks[5]);
         t2 = _mm_aesdec_si128(t2, ks[5]);
         t3 = _mm_aesdec_si128(t3, ks[5]);
         t4 = _mm_aesdec_si128(t4, ks[5]);
         t1 = _mm_aesdec_si128(t1, ks[6]);
         t2 = _mm_aesdec_si128(t2, ks[6]);
         t3 = _mm_aesdec_si128(t3, ks[6]);
         t4 = _mm_aesdec_si128(t4, ks[6]);
         t1 = _mm_aesdec_si128(t1, ks[7]);
         t2 = _mm_aesdec_si128(t2, ks[7]);
         t3 = _mm_aesdec_si128(t3, ks[7]);
         t4 = _mm_aesdec_si128(t4, ks[7]);
         t1 = _mm_aesdec_si128(t1, ks[8]);
         t2 = _mm_aesdec_si128(t2, ks[8]);
         t3 = _mm_aesdec_si128(t3, ks[8]);
         t4 = _mm_aesdec_si128(t4, ks[8]);
         t1 = _mm_aesdec_si128(t1, ks[9]);
         t2 = _mm_aesdec_si128(t2, ks[9]);
         t3 = _mm_aesdec_si128(t3, ks[9]);
         t4 = _mm_aesdec_si128(t4, ks[9]);
         t1 = _mm_aesdec_si128(t1, ks[10]);
         t2 = _mm_aesdec_si128(t2, ks[10]);
         t3 = _mm_aesdec_si128(t3, ks[10]);
         t4 = _mm_aesdec_si128(t4, ks[10]);
         t1 = _mm_aesdec_si128(t1, ks[11]);
         t2 = _mm_aesdec_si128(t2, ks[11]);
         t3 = _mm_aesdec_si128(t3, ks[11]);
         t4 = _mm_aesdec_si128(t4, ks[11]);
         t1 = _mm_aesdec_si128(t1, ks[12]);
         t2 = _mm_aesdec_si128(t2, ks[12]);
         t3 = _mm_aesdec_si128(t3, ks[12]);
         t4 = _mm_aesdec_si128(t4, ks[12]);
         t1 = _mm_aesdec_si128(t1, ks[13]);
         t2 = _mm_aesdec_si128(t2, ks[13]);
         t3 = _mm_aesdec_si128(t3, ks[13]);
         t4 = _mm_aesdec_si128(t4, ks[13]);
         t1 = _mm_aesdeclast_si128(t1, ks[14]);
         t2 = _mm_aesdeclast_si128(t2, ks[14]);
         t3 = _mm_aesdeclast_si128(t3, ks[14]);
         t4 = _mm_aesdeclast_si128(t4, ks[14]);
         t1 = _mm_xor_si128(t1, f1);
         t2 = _mm_xor_si128(t2, f2);
         t3 = _mm_xor_si128(t3, f3);
         t4 = _mm_xor_si128(t4, f4);
         _mm_storeu_si128(bo + i + 0, t1);
         _mm_storeu_si128(bo + i + 1, t2);
         _mm_storeu_si128(bo + i + 2, t3);
         _mm_storeu_si128(bo + i + 3, t4);
         f1 = last;
     }
     for (i = pblocks; i < blocks; i++)
     {
         last = _mm_loadu_si128(bi + i);
         t1 = _mm_xor_si128(last, ks[0]);
         t1 = _mm_aesdec_si128(t1, ks[1]);
         t1 = _mm_aesdec_si128(t1, ks[2]);
         t1 = _mm_aesdec_si128(t1, ks[3]);
         t1 = _mm_aesdec_si128(t1, ks[4]);
         t1 = _mm_aesdec_si128(t1, ks[5]);
         t1 = _mm_aesdec_si128(t1, ks[6]);
         t1 = _mm_aesdec_si128(t1, ks[7]);
         t1 = _mm_aesdec_si128(t1, ks[8]);
         t1 = _mm_aesdec_si128(t1, ks[9]);
         t1 = _mm_aesdec_si128(t1, ks[10]);
         t1 = _mm_aesdec_si128(t1, ks[11]);
         t1 = _mm_aesdec_si128(t1, ks[12]);
         t1 = _mm_aesdec_si128(t1, ks[13]);
         t1 = _mm_aesdeclast_si128(t1, ks[14]);
         t1 = _mm_xor_si128(t1, f1);
         _mm_storeu_si128(bo + i, t1);
         f1 = last;
     }
 }
static void encrypt_cbc128 (aesni_key_t * key, u_int blocks, u_char * in, u_char * iv, u_char * out) static
AES-128 CBC encryption
Definition at line 70 of file aesni_cbc.c.
Referenced by aesni_cbc_create().
 {
     __m128i *ks, t, fb, *bi, *bo;
     int i;
     ks = key->schedule;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     fb = _mm_loadu_si128((__m128i*)iv);
     for (i = 0; i < blocks; i++)
     {
         t = _mm_loadu_si128(bi + i);
         fb = _mm_xor_si128(t, fb);
         fb = _mm_xor_si128(fb, ks[0]);
         fb = _mm_aesenc_si128(fb, ks[1]);
         fb = _mm_aesenc_si128(fb, ks[2]);
         fb = _mm_aesenc_si128(fb, ks[3]);
         fb = _mm_aesenc_si128(fb, ks[4]);
         fb = _mm_aesenc_si128(fb, ks[5]);
         fb = _mm_aesenc_si128(fb, ks[6]);
         fb = _mm_aesenc_si128(fb, ks[7]);
         fb = _mm_aesenc_si128(fb, ks[8]);
         fb = _mm_aesenc_si128(fb, ks[9]);
         fb = _mm_aesenclast_si128(fb, ks[10]);
         _mm_storeu_si128(bo + i, fb);
     }
 }
static void encrypt_cbc192 (aesni_key_t * key, u_int blocks, u_char * in, u_char * iv, u_char * out) static
AES-192 CBC encryption
Definition at line 214 of file aesni_cbc.c.
Referenced by aesni_cbc_create().
 {
     __m128i *ks, t, fb, *bi, *bo;
     int i;
     ks = key->schedule;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     fb = _mm_loadu_si128((__m128i*)iv);
     for (i = 0; i < blocks; i++)
     {
         t = _mm_loadu_si128(bi + i);
         fb = _mm_xor_si128(t, fb);
         fb = _mm_xor_si128(fb, ks[0]);
         fb = _mm_aesenc_si128(fb, ks[1]);
         fb = _mm_aesenc_si128(fb, ks[2]);
         fb = _mm_aesenc_si128(fb, ks[3]);
         fb = _mm_aesenc_si128(fb, ks[4]);
         fb = _mm_aesenc_si128(fb, ks[5]);
         fb = _mm_aesenc_si128(fb, ks[6]);
         fb = _mm_aesenc_si128(fb, ks[7]);
         fb = _mm_aesenc_si128(fb, ks[8]);
         fb = _mm_aesenc_si128(fb, ks[9]);
         fb = _mm_aesenc_si128(fb, ks[10]);
         fb = _mm_aesenc_si128(fb, ks[11]);
         fb = _mm_aesenclast_si128(fb, ks[12]);
         _mm_storeu_si128(bo + i, fb);
     }
 }
static void encrypt_cbc256 (aesni_key_t * key, u_int blocks, u_char * in, u_char * iv, u_char * out) static
AES-256 CBC encryption
Definition at line 370 of file aesni_cbc.c.
Referenced by aesni_cbc_create().
 {
     __m128i *ks, t, fb, *bi, *bo;
     int i;
     ks = key->schedule;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     fb = _mm_loadu_si128((__m128i*)iv);
     for (i = 0; i < blocks; i++)
     {
         t = _mm_loadu_si128(bi + i);
         fb = _mm_xor_si128(t, fb);
         fb = _mm_xor_si128(fb, ks[0]);
         fb = _mm_aesenc_si128(fb, ks[1]);
         fb = _mm_aesenc_si128(fb, ks[2]);
         fb = _mm_aesenc_si128(fb, ks[3]);
         fb = _mm_aesenc_si128(fb, ks[4]);
         fb = _mm_aesenc_si128(fb, ks[5]);
         fb = _mm_aesenc_si128(fb, ks[6]);
         fb = _mm_aesenc_si128(fb, ks[7]);
         fb = _mm_aesenc_si128(fb, ks[8]);
         fb = _mm_aesenc_si128(fb, ks[9]);
         fb = _mm_aesenc_si128(fb, ks[10]);
         fb = _mm_aesenc_si128(fb, ks[11]);
         fb = _mm_aesenc_si128(fb, ks[12]);
         fb = _mm_aesenc_si128(fb, ks[13]);
         fb = _mm_aesenclast_si128(fb, ks[14]);
         _mm_storeu_si128(bo + i, fb);
     }
 }
METHOD (crypter_t , encrypt , bool , private_aesni_cbc_t * this, chunk_t data, chunk_t iv, chunk_t * encrypted)
Definition at line 560 of file aesni_cbc.c.
References crypt(), and encrypt().
 {
     return crypt(this->encrypt, this->ekey, data, iv, encrypted);
 }
METHOD (crypter_t , decrypt , bool , private_aesni_cbc_t * this, chunk_t data, chunk_t iv, chunk_t * decrypted)
Definition at line 566 of file aesni_cbc.c.
References crypt(), and decrypt.
 {
     return crypt(this->decrypt, this->dkey, data, iv, decrypted);
 }
METHOD (crypter_t , get_block_size , size_t , private_aesni_cbc_t * this)
Definition at line 572 of file aesni_cbc.c.
References AES_BLOCK_SIZE.
 {
     return AES_BLOCK_SIZE;
 }
METHOD (crypter_t , get_iv_size , size_t , private_aesni_cbc_t * this)
Definition at line 578 of file aesni_cbc.c.
References AES_BLOCK_SIZE.
 {
     return AES_BLOCK_SIZE;
 }
METHOD (crypter_t , get_key_size , size_t , private_aesni_cbc_t * this)
Definition at line 584 of file aesni_cbc.c.
References key_size.
 {
     return this->key_size;
 }
METHOD (crypter_t , set_key , bool , private_aesni_cbc_t * this, chunk_t key)
Definition at line 590 of file aesni_cbc.c.
References aesni_key_create(), DESTROY_IF, FALSE, chunk_t::len, and TRUE.
 {
     if (key.len != this->key_size)
     {
         return FALSE;
     }
     DESTROY_IF(this->ekey);
     DESTROY_IF(this->dkey);
     this->ekey = aesni_key_create(TRUE, key);
     this->dkey = aesni_key_create(FALSE, key);
     return this->ekey && this->dkey;
 }
METHOD (crypter_t , destroy , void , private_aesni_cbc_t * this)
Definition at line 607 of file aesni_cbc.c.
References DESTROY_IF, and free_align().
 {
     DESTROY_IF(this->ekey);
     DESTROY_IF(this->dkey);
     free_align(this);
 }