strongSwan: hasher_t Struct Reference
hasher_t Struct Reference
hasher
#include "hasher.h"
Public Attributes
bool(* get_hash)(hasher_t *this, chunk_t data, u_int8_t *hash) __attribute__((warn_unused_result))
bool(* allocate_hash)(hasher_t *this, chunk_t data, chunk_t *hash) __attribute__((warn_unused_result))
size_t(* get_hash_size)(hasher_t *this)
bool(* reset)(hasher_t *this) __attribute__((warn_unused_result))
void(* destroy)(hasher_t *this)
Detailed Description
Generic interface for all hash functions.
Definition at line 76 of file hasher.h.
Member Data Documentation
bool(* hasher_t::allocate_hash)(hasher_t *this, chunk_t data, chunk_t *hash) __attribute__((warn_unused_result))
Hash data and allocate space for the hash.
If the parameter hash is NULL, no result is written back and more data can be appended to already hashed data. If not, the result is written back and the hasher is reset.
Parameters
data chunk with data to hash
hash chunk which will hold allocated hash
Returns
TRUE if hash allocated successfully
Definition at line 106 of file hasher.h.
Referenced by AuthenticatorResponse(), bliss_public_key_fingerprint(), build_cert_payload(), build_emsa_pkcs1_signature(), build_requestList(), build_v3_fingerprint(), ChallengeHash(), fingerprint_ecdsa(), generate(), generate_natd_hash(), get_init_hash(), hash_challenge(), hash_data(), hash_password(), hash_pubkey(), METHOD(), NtPasswordHash(), openssl_ec_fingerprint(), openssl_rsa_fingerprint(), parse_certificate(), parse_public_key(), sign_pkcs1(), verify_emsa_pkcs1_signature(), and verify_pkcs1().
void(* hasher_t::destroy)(hasher_t *this)
Destroys a hasher object.
Definition at line 126 of file hasher.h.
Referenced by AuthenticatorResponse(), bench_hasher(), bliss_public_key_fingerprint(), build_cert_payload(), build_emsa_pkcs1_signature(), build_requestList(), build_v3_fingerprint(), ChallengeHash(), check_boot_aggregate(), derive_key(), ensure_crypto_primitives(), fingerprint_ecdsa(), generate(), GenerateMSK(), hash_challenge(), hash_data(), hash_password(), hash_pubkey(), ima_hash(), main(), METHOD(), NtPasswordHash(), openssl_ec_fingerprint(), openssl_rsa_fingerprint(), parse_certificate(), parse_public_key(), pem_decrypt(), pts_file_meas_create_from_path(), scep_generate_pkcs10_fingerprint(), sign_bliss(), sign_pkcs1(), verify_bliss(), verify_emsa_pkcs1_signature(), and verify_pkcs1().
bool(* hasher_t::get_hash)(hasher_t *this, chunk_t data, u_int8_t *hash) __attribute__((warn_unused_result))
Hash data and write it in the buffer.
If the parameter hash is NULL, no result is written back and more data can be appended to already hashed data. If not, the result is written back and the hasher is reset.
The hash output parameter must hold at least hash_t.get_block_size() bytes.
Parameters
data data to hash
hash pointer where the hash will be written
Returns
TRUE if hash created successfully
Definition at line 92 of file hasher.h.
Referenced by bench_hasher(), check_boot_aggregate(), derive_key(), GenerateMSK(), hash_data(), hash_file(), ima_hash(), main(), METHOD(), mgf1_create(), pbkdf1(), pem_decrypt(), scep_generate_pkcs10_fingerprint(), scep_generate_transaction_id(), sign_bliss(), and verify_bliss().
size_t(* hasher_t::get_hash_size)(hasher_t *this)
Get the size of the resulting hash.
Returns
hash size in bytes
Definition at line 114 of file hasher.h.
Referenced by bench_hasher(), derive_key(), ensure_crypto_primitives(), generate_natd_hash_faked(), METHOD(), mgf1_create(), pbkdf1(), pem_decrypt(), pts_file_meas_create_from_path(), sign_bliss(), verify_bliss(), and verify_emsa_pkcs1_signature().
bool(* hasher_t::reset)(hasher_t *this) __attribute__((warn_unused_result))
Resets the hasher's state.
Returns
TRUE if hasher reset successfully
Definition at line 121 of file hasher.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
hasher.h