strongSwan: simaka_manager.c File Reference
simaka_manager.c File Reference
#include "simaka_manager.h"
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct private_simaka_manager_t
Typedefs
typedef struct
private_simaka_manager_t private_simaka_manager_t
Functions
void libsimaka_init (void)
METHOD (simaka_manager_t, add_card, void, private_simaka_manager_t *this, simaka_card_t *card)
METHOD (simaka_manager_t, remove_card, void, private_simaka_manager_t *this, simaka_card_t *card)
METHOD (simaka_manager_t, card_get_triplet, bool, private_simaka_manager_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
METHOD (simaka_manager_t, card_get_quintuplet, status_t, private_simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int *res_len)
METHOD (simaka_manager_t, card_resync, bool, private_simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
METHOD (simaka_manager_t, card_set_pseudonym, void, private_simaka_manager_t *this, identification_t *id, identification_t *pseudonym)
METHOD (simaka_manager_t, card_get_pseudonym, identification_t *, private_simaka_manager_t *this, identification_t *id)
METHOD (simaka_manager_t, card_set_reauth, void, private_simaka_manager_t *this, identification_t *id, identification_t *next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
METHOD (simaka_manager_t, card_get_reauth, identification_t *, private_simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
METHOD (simaka_manager_t, add_provider, void, private_simaka_manager_t *this, simaka_provider_t *provider)
METHOD (simaka_manager_t, remove_provider, void, private_simaka_manager_t *this, simaka_provider_t *provider)
METHOD (simaka_manager_t, provider_get_triplet, bool, private_simaka_manager_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
METHOD (simaka_manager_t, provider_get_quintuplet, bool, private_simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int *xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
METHOD (simaka_manager_t, provider_resync, bool, private_simaka_manager_t *this, identification_t *id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
METHOD (simaka_manager_t, provider_is_pseudonym, identification_t *, private_simaka_manager_t *this, identification_t *id)
METHOD (simaka_manager_t, provider_gen_pseudonym, identification_t *, private_simaka_manager_t *this, identification_t *id)
METHOD (simaka_manager_t, provider_is_reauth, identification_t *, private_simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1], u_int16_t *counter)
METHOD (simaka_manager_t, provider_gen_reauth, identification_t *, private_simaka_manager_t *this, identification_t *id, char mk[HASH_SIZE_SHA1])
METHOD (simaka_manager_t, add_hooks, void, private_simaka_manager_t *this, simaka_hooks_t *hooks)
METHOD (simaka_manager_t, remove_hooks, void, private_simaka_manager_t *this, simaka_hooks_t *hooks)
METHOD (simaka_manager_t, message_hook, void, private_simaka_manager_t *this, simaka_message_t *message, bool inbound, bool decrypted)
METHOD (simaka_manager_t, key_hook, void, private_simaka_manager_t *this, chunk_t k_encr, chunk_t k_auth)
METHOD (simaka_manager_t, destroy, void, private_simaka_manager_t *this)
simaka_manager_t * simaka_manager_create ()
static bool register_card (char *mgr_name, bool reg, simaka_card_t *card)
static bool register_provider (char *mgr_name, bool reg, simaka_provider_t *provider)
bool simaka_manager_register (plugin_t *plugin, plugin_feature_t *feature, bool reg, void *data)
Typedef Documentation
typedef struct private_simaka_manager_t private_simaka_manager_t
Definition at line 22 of file simaka_manager.c.
Function Documentation
METHOD (simaka_manager_t , add_card , void , private_simaka_manager_t * this, simaka_card_t * card)
Definition at line 63 of file simaka_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->cards->insert_last(this->cards, card);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , remove_card , void , private_simaka_manager_t * this, simaka_card_t * card)
Definition at line 71 of file simaka_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->cards->remove(this->cards, card, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , card_get_triplet , bool , private_simaka_manager_t * this, identification_t * id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
Definition at line 79 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, FALSE, simaka_card_t::get_triplet, lock, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_card_t *card;
     int tried = 0;
     this->lock->read_lock(this->lock);
     enumerator = this->cards->create_enumerator(this->cards);
     while (enumerator->enumerate(enumerator, &card))
     {
         if (card->get_triplet(card, id, rand, sres, kc))
         {
             enumerator->destroy(enumerator);
             this->lock->unlock(this->lock);
             return TRUE;
         }
         tried++;
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     DBG1(DBG_LIB, "tried %d SIM cards, but none has triplets for '%Y'",
          tried, id);
     return FALSE;
 }
METHOD (simaka_manager_t , card_get_quintuplet , status_t , private_simaka_manager_t * this, identification_t * id, char rand[AKA_RAND_LEN], char autn[AKA_AUTN_LEN], char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char res[AKA_RES_MAX], int * res_len)
Definition at line 106 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, FAILED, simaka_card_t::get_quintuplet, INVALID_STATE, lock, NOT_FOUND, NOT_SUPPORTED, res, status, SUCCESS, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_card_t *card;
     status_t status = NOT_FOUND;
     int tried = 0;
     this->lock->read_lock(this->lock);
     enumerator = this->cards->create_enumerator(this->cards);
     while (enumerator->enumerate(enumerator, &card))
     {
         status = card->get_quintuplet(card, id, rand, autn, ck, ik, res, res_len);
         switch (status)
         {   /* try next on error, but not on INVALID_STATE */
             case SUCCESS:
             case INVALID_STATE:
                 enumerator->destroy(enumerator);
                 this->lock->unlock(this->lock);
                 return status;
             case NOT_SUPPORTED:
             case FAILED:
             default:
                 tried++;
                 continue;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     DBG1(DBG_LIB, "tried %d SIM cards, but none has quintuplets for '%Y'",
          tried, id);
     return status;
 }
METHOD (simaka_manager_t , card_resync , bool , private_simaka_manager_t * this, identification_t * id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
Definition at line 142 of file simaka_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, lock, simaka_card_t::resync, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_card_t *card;
     this->lock->read_lock(this->lock);
     enumerator = this->cards->create_enumerator(this->cards);
     while (enumerator->enumerate(enumerator, &card))
     {
         if (card->resync(card, id, rand, auts))
         {
             enumerator->destroy(enumerator);
             this->lock->unlock(this->lock);
             return TRUE;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return FALSE;
 }
METHOD (simaka_manager_t , card_set_pseudonym , void , private_simaka_manager_t * this, identification_t * id, identification_t * pseudonym)
Definition at line 165 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, lock, simaka_card_t::set_pseudonym, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_card_t *card;
     DBG1(DBG_LIB, "storing pseudonym '%Y' for '%Y'", pseudonym, id);
     this->lock->read_lock(this->lock);
     enumerator = this->cards->create_enumerator(this->cards);
     while (enumerator->enumerate(enumerator, &card))
     {
         card->set_pseudonym(card, id, pseudonym);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , card_get_pseudonym , identification_t * , private_simaka_manager_t * this, identification_t * id)
Definition at line 184 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, simaka_card_t::get_pseudonym, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_card_t *card;
     identification_t *pseudonym = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->cards->create_enumerator(this->cards);
     while (enumerator->enumerate(enumerator, &card))
     {
         pseudonym = card->get_pseudonym(card, id);
         if (pseudonym)
         {
             DBG1(DBG_LIB, "using stored pseudonym identity '%Y' "
                  "instead of '%Y'", pseudonym, id);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return pseudonym;
 }
METHOD (simaka_manager_t , card_set_reauth , void , private_simaka_manager_t * this, identification_t * id, identification_t * next, char mk[HASH_SIZE_SHA1], u_int16_t counter)
Definition at line 208 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, lock, simaka_card_t::set_reauth, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_card_t *card;
     DBG1(DBG_LIB, "storing next reauthentication identity '%Y' for '%Y'",
          next, id);
     this->lock->read_lock(this->lock);
     enumerator = this->cards->create_enumerator(this->cards);
     while (enumerator->enumerate(enumerator, &card))
     {
         card->set_reauth(card, id, next, mk, counter);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , card_get_reauth , identification_t * , private_simaka_manager_t * this, identification_t * id, char mk[HASH_SIZE_SHA1], u_int16_t * counter)
Definition at line 228 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, simaka_card_t::get_reauth, lock, reauth(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_card_t *card;
     identification_t *reauth = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->cards->create_enumerator(this->cards);
     while (enumerator->enumerate(enumerator, &card))
     {
         reauth = card->get_reauth(card, id, mk, counter);
         if (reauth)
         {
             DBG1(DBG_LIB, "using stored reauthentication identity '%Y' "
                  "instead of '%Y'", reauth, id);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return reauth;
 }
METHOD (simaka_manager_t , add_provider , void , private_simaka_manager_t * this, simaka_provider_t * provider)
Definition at line 253 of file simaka_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->providers->insert_last(this->providers, provider);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , remove_provider , void , private_simaka_manager_t * this, simaka_provider_t * provider)
Definition at line 261 of file simaka_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->providers->remove(this->providers, provider, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , provider_get_triplet , bool , private_simaka_manager_t * this, identification_t * id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
Definition at line 269 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, FALSE, simaka_provider_t::get_triplet, lock, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_provider_t *provider;
     int tried = 0;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &provider))
     {
         if (provider->get_triplet(provider, id, rand, sres, kc))
         {
             enumerator->destroy(enumerator);
             this->lock->unlock(this->lock);
             return TRUE;
         }
         tried++;
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     DBG1(DBG_LIB, "tried %d SIM providers, but none had a triplet for '%Y'",
          tried, id);
     return FALSE;
 }
METHOD (simaka_manager_t , provider_get_quintuplet , bool , private_simaka_manager_t * this, identification_t * id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int * xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
Definition at line 296 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, FALSE, simaka_provider_t::get_quintuplet, lock, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_provider_t *provider;
     int tried = 0;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &provider))
     {
         if (provider->get_quintuplet(provider, id, rand, xres, xres_len,
                                      ck, ik, autn))
         {
             enumerator->destroy(enumerator);
             this->lock->unlock(this->lock);
             return TRUE;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     DBG1(DBG_LIB, "tried %d SIM providers, but none had a quintuplet for '%Y'",
          tried, id);
     return FALSE;
 }
METHOD (simaka_manager_t , provider_resync , bool , private_simaka_manager_t * this, identification_t * id, char rand[AKA_RAND_LEN], char auts[AKA_AUTS_LEN])
Definition at line 324 of file simaka_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, lock, simaka_provider_t::resync, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_provider_t *provider;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &provider))
     {
         if (provider->resync(provider, id, rand, auts))
         {
             enumerator->destroy(enumerator);
             this->lock->unlock(this->lock);
             return TRUE;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return FALSE;
 }
METHOD (simaka_manager_t , provider_is_pseudonym , identification_t * , private_simaka_manager_t * this, identification_t * id)
Definition at line 347 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, simaka_provider_t::is_pseudonym, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_provider_t *provider;
     identification_t *permanent = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &provider))
     {
         permanent = provider->is_pseudonym(provider, id);
         if (permanent)
         {
             DBG1(DBG_LIB, "received pseudonym identity '%Y' "
                  "mapping to '%Y'", id, permanent);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return permanent;
 }
METHOD (simaka_manager_t , provider_gen_pseudonym , identification_t * , private_simaka_manager_t * this, identification_t * id)
Definition at line 371 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, simaka_provider_t::gen_pseudonym, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_provider_t *provider;
     identification_t *pseudonym = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &provider))
     {
         pseudonym = provider->gen_pseudonym(provider, id);
         if (pseudonym)
         {
             DBG1(DBG_LIB, "proposing new pseudonym '%Y'", pseudonym);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return pseudonym;
 }
METHOD (simaka_manager_t , provider_is_reauth , identification_t * , private_simaka_manager_t * this, identification_t * id, char mk[HASH_SIZE_SHA1], u_int16_t * counter)
Definition at line 394 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, simaka_provider_t::is_reauth, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_provider_t *provider;
     identification_t *permanent = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &provider))
     {
         permanent = provider->is_reauth(provider, id, mk, counter);
         if (permanent)
         {
             DBG1(DBG_LIB, "received reauthentication identity '%Y' "
                  "mapping to '%Y'", id, permanent);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return permanent;
 }
METHOD (simaka_manager_t , provider_gen_reauth , identification_t * , private_simaka_manager_t * this, identification_t * id, char mk[HASH_SIZE_SHA1])
Definition at line 419 of file simaka_manager.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, simaka_provider_t::gen_reauth, lock, reauth(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_provider_t *provider;
     identification_t *reauth = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->providers->create_enumerator(this->providers);
     while (enumerator->enumerate(enumerator, &provider))
     {
         reauth = provider->gen_reauth(provider, id, mk);
         if (reauth)
         {
             DBG1(DBG_LIB, "proposing new reauthentication identity '%Y'", reauth);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return reauth;
 }
METHOD (simaka_manager_t , add_hooks , void , private_simaka_manager_t * this, simaka_hooks_t * hooks)
Definition at line 442 of file simaka_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->hooks->insert_last(this->hooks, hooks);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , remove_hooks , void , private_simaka_manager_t * this, simaka_hooks_t * hooks)
Definition at line 450 of file simaka_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->hooks->remove(this->hooks, hooks, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , message_hook , void , private_simaka_manager_t * this, simaka_message_t * message, bool inbound, bool decrypted)
Definition at line 458 of file simaka_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, hooks, lock, simaka_hooks_t::message, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_hooks_t *hooks;
     this->lock->read_lock(this->lock);
     enumerator = this->hooks->create_enumerator(this->hooks);
     while (enumerator->enumerate(enumerator, &hooks))
     {
         hooks->message(hooks, message, inbound, decrypted);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , key_hook , void , private_simaka_manager_t * this, chunk_t k_encr, chunk_t k_auth)
Definition at line 475 of file simaka_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, hooks, simaka_hooks_t::keys, lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     simaka_hooks_t *hooks;
     this->lock->read_lock(this->lock);
     enumerator = this->hooks->create_enumerator(this->hooks);
     while (enumerator->enumerate(enumerator, &hooks))
     {
         hooks->keys(hooks, k_encr, k_auth);
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (simaka_manager_t , destroy , void , private_simaka_manager_t * this)
Definition at line 491 of file simaka_manager.c.
References spinlock_t::destroy, hashtable_t::destroy, free(), hooks, and lock.
 {
     this->cards->destroy(this->cards);
     this->providers->destroy(this->providers);
     this->hooks->destroy(this->hooks);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool register_card (char * mgr_name, bool reg, simaka_card_t * card) static
(Un-)register a provider to a simaka manager
Definition at line 546 of file simaka_manager.c.
References simaka_manager_t::add_card, FALSE, library_t::get, lib, simaka_manager_t::remove_card, and TRUE.
Referenced by simaka_manager_register().
 {
     simaka_manager_t *mgr;
     if (!card)
     {
         return FALSE;
     }
     mgr = lib->get(lib, mgr_name);
     if (mgr)
     {
         if (reg)
         {
             mgr->add_card(mgr, card);
         }
         else
         {
             mgr->remove_card(mgr, card);
         }
         return TRUE;
     }
     return FALSE;
 }
static bool register_provider (char * mgr_name, bool reg, simaka_provider_t * provider) static
(Un-)register a provider to a simaka manager
Definition at line 573 of file simaka_manager.c.
References simaka_manager_t::add_provider, FALSE, library_t::get, lib, simaka_manager_t::remove_provider, and TRUE.
Referenced by simaka_manager_register().
 {
     simaka_manager_t *mgr;
     if (!provider)
     {
         return FALSE;
     }
     mgr = lib->get(lib, mgr_name);
     if (mgr)
     {
         if (reg)
         {
             mgr->add_provider(mgr, provider);
         }
         else
         {
             mgr->remove_provider(mgr, provider);
         }
         return TRUE;
     }
     return FALSE;
 }