strongSwan: process
process
utils
Classes
struct process_t
Typedefs
typedef struct process_t process_t
Functions
process_t * process_start (char *const argv[], char *const envp[], int *in, int *out, int *err, bool close_all)
process_t * process_start_shell (char *const envp[], int *in, int *out, int *err, char *fmt,...)
Detailed Description
Typedef Documentation
typedef struct process_t process_t
Definition at line 26 of file process.h.
Function Documentation
process_t* process_start (char *const argv[], char *const envp[], int * in, int * out, int * err, bool close_all)
Spawn a child process with redirected I/O.
Forks the current process, optionally redirects stdin/out/err to the current process, and executes the provided program with arguments.
The process to execute is specified as argv[0], followed by the process arguments, followed by NULL. envp[] has a NULL terminated list of arguments to invoke the process with.
If any of in/out/err is given, stdin/out/err from the child process get connected over pipe()s to the caller. If close_all is TRUE, all other open file descriptors get closed, regardless of any CLOEXEC setting.
A caller must close all of the returned file descriptors to avoid file descriptor leaks.
A non-NULL return value does not guarantee that the process has been invoked successfully.
Parameters
argv NULL terminated process arguments, with argv[0] as program
envp NULL terminated list of environment variables
in pipe fd returned for redirecting data to child stdin
out pipe fd returned to redirect child stdout data to
err pipe fd returned to redirect child stderr data to
close_all close all open file descriptors above 2 before execve()
Returns
process, NULL on failure
See header
Definition at line 127 of file process.c.
References close_if(), closefrom(), DBG1, DBG_LIB, INIT, PIPE_READ, PIPE_WRITE, process_destroy(), and strerror.
Referenced by process_start_shell().
 {
     private_process_t *this;
     char *empty[] = { NULL };
     INIT(this,
         .public = {
             .wait = _wait_,
         },
         .in = { -1, -1 },
         .out = { -1, -1 },
         .err = { -1, -1 },
     );
     if (in && pipe(this->in) != 0)
     {
         DBG1(DBG_LIB, "creating stdin pipe failed: %s", strerror(errno));
         process_destroy(this);
         return NULL;
     }
     if (out && pipe(this->out) != 0)
     {
         DBG1(DBG_LIB, "creating stdout pipe failed: %s", strerror(errno));
         process_destroy(this);
         return NULL;
     }
     if (err && pipe(this->err) != 0)
     {
         DBG1(DBG_LIB, "creating stderr pipe failed: %s", strerror(errno));
         process_destroy(this);
         return NULL;
     }
     this->pid = fork();
     switch (this->pid)
     {
         case -1:
             DBG1(DBG_LIB, "forking process failed: %s", strerror(errno));
             process_destroy(this);
             return NULL;
         case 0:
             /* child */
             close_if(&this->in[PIPE_WRITE]);
             close_if(&this->out[PIPE_READ]);
             close_if(&this->err[PIPE_READ]);
             if (this->in[PIPE_READ] != -1)
             {
                 if (dup2(this->in[PIPE_READ], 0) == -1)
                 {
                     raise(SIGKILL);
                 }
             }
             if (this->out[PIPE_WRITE] != -1)
             {
                 if (dup2(this->out[PIPE_WRITE], 1) == -1)
                 {
                     raise(SIGKILL);
                 }
             }
             if (this->err[PIPE_WRITE] != -1)
             {
                 if (dup2(this->err[PIPE_WRITE], 2) == -1)
                 {
                     raise(SIGKILL);
                 }
             }
             if (close_all)
             {
                 closefrom(3);
             }
             if (execve(argv[0], argv, envp ?: empty) == -1)
             {
                 raise(SIGKILL);
             }
             /* not reached */
         default:
             /* parent */
             close_if(&this->in[PIPE_READ]);
             close_if(&this->out[PIPE_WRITE]);
             close_if(&this->err[PIPE_WRITE]);
             if (in)
             {
                 *in = this->in[PIPE_WRITE];
                 this->in[PIPE_WRITE] = -1;
             }
             if (out)
             {
                 *out = this->out[PIPE_READ];
                 this->out[PIPE_READ] = -1;
             }
             if (err)
             {
                 *err = this->err[PIPE_READ];
                 this->err[PIPE_READ] = -1;
             }
             return &this->public;
     }
 }
process_t* process_start_shell (char *const envp[], int * in, int * out, int * err, char * fmt, ...)
Spawn a command in a shell child process.
Same as process_start(), but passes a single command to a shell, such as "sh -c". See process_start() for I/O redirection notes.
Parameters
envp NULL terminated list of environment variables
in pipe fd returned for redirecting data to child stdin
out pipe fd returned to redirect child stdout data to
err pipe fd returned to redirect child stderr data to
fmt printf format string for command
... arguments for fmt
Returns
process, NULL on failure
See header
Definition at line 230 of file process.c.
References argv, free(), len, process(), process_start(), TRUE, and vasprintf().
Referenced by invoke_once(), METHOD(), and START_TEST().
 {
     char *argv[] = {
         "/bin/sh",
         "-c",
         NULL,
         NULL
     };
     process_t *process;
     va_list args;
     int len;
     va_start(args, fmt);
     len = vasprintf(&argv[2], fmt, args);
     va_end(args);
     if (len < 0)
     {
         return NULL;
     }
     process = process_start(argv, envp, in, out, err, TRUE);
     free(argv[2]);
     return process;
 }