strongSwan: eap_simaka_sql_provider.c File Reference
eap_simaka_sql_provider.c File Reference
#include "eap_simaka_sql_provider.h"
#include <time.h>
#include <daemon.h>
Classes
struct private_eap_simaka_sql_provider_t
Typedefs
typedef struct
private_eap_simaka_sql_provider_t private_eap_simaka_sql_provider_t
Functions
METHOD (simaka_provider_t, get_triplet, bool, private_eap_simaka_sql_provider_t *this, identification_t *id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
METHOD (simaka_provider_t, get_quintuplet, bool, private_eap_simaka_sql_provider_t *this, identification_t *id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int *xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
METHOD (eap_simaka_sql_provider_t, destroy, void, private_eap_simaka_sql_provider_t *this)
eap_simaka_sql_provider_t * eap_simaka_sql_provider_create (database_t *db, bool remove_used)
Typedef Documentation
typedef struct private_eap_simaka_sql_provider_t private_eap_simaka_sql_provider_t
Definition at line 22 of file eap_simaka_sql_provider.c.
Function Documentation
METHOD (simaka_provider_t , get_triplet , bool , private_eap_simaka_sql_provider_t * this, identification_t * id, char rand[SIM_RAND_LEN], char sres[SIM_SRES_LEN], char kc[SIM_KC_LEN])
Definition at line 45 of file eap_simaka_sql_provider.c.
References chunk_create(), db, DB_BLOB, DB_TEXT, DB_UINT, enumerator_t::destroy, enumerator_t::enumerate, database_t::execute, FALSE, found, chunk_t::len, memcpy, chunk_t::ptr, database_t::query, query(), snprintf, and TRUE.
 {
     chunk_t rand_chunk, sres_chunk, kc_chunk;
     enumerator_t *query;
     bool found = FALSE;
     char buf[128];
     snprintf(buf, sizeof(buf), "%Y", id);
     query = this->db->query(this->db,
                 "select rand, sres, kc from triplets where id = ? order by used",
                 DB_TEXT, buf, DB_BLOB, DB_BLOB, DB_BLOB);
     if (query)
     {
         if (query->enumerate(query, &rand_chunk, &sres_chunk, &kc_chunk))
         {
             if (rand_chunk.len == SIM_RAND_LEN &&
                 sres_chunk.len == SIM_SRES_LEN &&
                 kc_chunk.len == SIM_KC_LEN)
             {
                 memcpy(rand, rand_chunk.ptr, SIM_RAND_LEN);
                 memcpy(sres, sres_chunk.ptr, SIM_SRES_LEN);
                 memcpy(kc, kc_chunk.ptr, SIM_KC_LEN);
                 found = TRUE;
             }
         }
         query->destroy(query);
     }
     if (found)
     {
         if (this->remove_used)
         {
             this->db->execute(this->db, NULL,
                     "delete from triplets where id = ? and rand = ?",
                     DB_TEXT, buf, DB_BLOB, chunk_create(rand, SIM_RAND_LEN));
         }
         else
         {
             this->db->execute(this->db, NULL,
                     "update triplets set used = ? where id = ? and rand = ?",
                     DB_UINT, time(NULL), DB_TEXT, buf,
                     DB_BLOB, chunk_create(rand, SIM_RAND_LEN));
         }
     }
     return found;
 }
METHOD (simaka_provider_t , get_quintuplet , bool , private_eap_simaka_sql_provider_t * this, identification_t * id, char rand[AKA_RAND_LEN], char xres[AKA_RES_MAX], int * xres_len, char ck[AKA_CK_LEN], char ik[AKA_IK_LEN], char autn[AKA_AUTN_LEN])
Definition at line 93 of file eap_simaka_sql_provider.c.
References chunk_create(), db, DB_BLOB, DB_TEXT, DB_UINT, enumerator_t::destroy, enumerator_t::enumerate, database_t::execute, FALSE, found, chunk_t::len, memcpy, chunk_t::ptr, database_t::query, query(), SIM_RAND_LEN, snprintf, and TRUE.
 {
     chunk_t rand_chunk, xres_chunk, ck_chunk, ik_chunk, autn_chunk;
     enumerator_t *query;
     bool found = FALSE;
     char buf[128];
     snprintf(buf, sizeof(buf), "%Y", id);
     query = this->db->query(this->db, "select rand, res, ck, ik, autn "
                 "from quintuplets where id = ? order by used", DB_TEXT, buf,
                 DB_BLOB, DB_BLOB, DB_BLOB, DB_BLOB, DB_BLOB);
     if (query)
     {
         if (query->enumerate(query, &rand_chunk, &xres_chunk,
                              &ck_chunk, &ik_chunk, &autn_chunk))
         {
             if (rand_chunk.len == AKA_RAND_LEN &&
                 xres_chunk.len <= AKA_RES_MAX &&
                 ck_chunk.len == AKA_CK_LEN &&
                 ik_chunk.len == AKA_IK_LEN &&
                 autn_chunk.len == AKA_AUTN_LEN)
             {
                 memcpy(rand, rand_chunk.ptr, AKA_RAND_LEN);
                 memcpy(xres, xres_chunk.ptr, xres_chunk.len);
                 *xres_len = xres_chunk.len;
                 memcpy(ck, ck_chunk.ptr, AKA_CK_LEN);
                 memcpy(ik, ik_chunk.ptr, AKA_IK_LEN);
                 memcpy(autn, autn_chunk.ptr, AKA_AUTN_LEN);
                 found = TRUE;
             }
         }
         query->destroy(query);
     }
     if (found)
     {
         if (this->remove_used)
         {
             this->db->execute(this->db, NULL,
                     "delete from quintuplets where id = ? and rand = ?",
                     DB_TEXT, buf, DB_BLOB, chunk_create(rand, SIM_RAND_LEN));
         }
         else
         {
             this->db->execute(this->db, NULL,
                     "update quintuplets set used = ? where id = ? and rand = ?",
                     DB_UINT, time(NULL), DB_TEXT, buf,
                     DB_BLOB, chunk_create(rand, AKA_RAND_LEN));
         }
     }
     return found;
 }
METHOD (eap_simaka_sql_provider_t , destroy , void , private_eap_simaka_sql_provider_t * this)
Definition at line 148 of file eap_simaka_sql_provider.c.
References free().
 {
     free(this);
 }