strongSwan: xauth_method_t Struct Reference
xauth_method_t Struct Reference
xauth_method
#include "xauth_method.h"
Public Attributes
status_t(* initiate)(xauth_method_t *this, cp_payload_t **out)
status_t(* process)(xauth_method_t *this, cp_payload_t *in, cp_payload_t **out)
identification_t *(* get_identity)(xauth_method_t *this)
void(* destroy)(xauth_method_t *this)
Detailed Description
Interface of an XAuth method for server and client side.
An XAuth method initiates an XAuth exchange and processes requests and responses. An XAuth method may need multiple exchanges before succeeding. Sending of XAUTH(STATUS) message is done by the framework, not a method.
Definition at line 52 of file xauth_method.h.
Member Data Documentation
void(* xauth_method_t::destroy)(xauth_method_t *this)
Destroys a eap_method_t object.
Definition at line 93 of file xauth_method.h.
Referenced by METHOD().
identification_t*(* xauth_method_t::get_identity)(xauth_method_t *this)
Get the XAuth username received as XAuth initiator.
Returns
used XAuth username, pointer to internal data
Definition at line 88 of file xauth_method.h.
status_t(* xauth_method_t::initiate)(xauth_method_t *this, cp_payload_t **out)
Initiate the XAuth exchange.
initiate() is only useable for server implementations, as clients only reply to server requests. A cp_payload is created in "out" if result is NEED_MORE.
Parameters
out cp_payload to send to the client
Returns
NEED_MORE, if an other exchange is required
FAILED, if unable to create XAuth request payload
Definition at line 66 of file xauth_method.h.
Referenced by METHOD().
status_t(* xauth_method_t::process)(xauth_method_t *this, cp_payload_t *in, cp_payload_t **out)
Process a received XAuth message.
A cp_payload is created in "out" if result is NEED_MORE.
Parameters
in cp_payload response received
out created cp_payload to send
Returns
NEED_MORE, if an other exchange is required
FAILED, if XAuth method failed
SUCCESS, if XAuth method succeeded
Definition at line 80 of file xauth_method.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
xauth_method.h