strongSwan: stroke_plugin.c File Reference
stroke_plugin.c File Reference
#include "stroke_plugin.h"
#include <library.h>
#include "stroke_socket.h"
Classes
struct private_stroke_plugin_t
Typedefs
typedef struct
private_stroke_plugin_t private_stroke_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_stroke_plugin_t *this)
static bool register_stroke (private_stroke_plugin_t *this, plugin_feature_t *feature, bool reg, void *data)
METHOD (plugin_t, get_features, int, private_stroke_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_stroke_plugin_t *this)
plugin_t * stroke_plugin_create ()
Typedef Documentation
typedef struct private_stroke_plugin_t private_stroke_plugin_t
Definition at line 21 of file stroke_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_stroke_plugin_t * this)
Definition at line 39 of file stroke_plugin.c.
 {
     return "stroke";
 }
METHOD (plugin_t , get_features , int , private_stroke_plugin_t * this, plugin_feature_t * features[])
Definition at line 63 of file stroke_plugin.c.
References CERT_ANY, CERT_TRUSTED_PUBKEY, CERT_X509, CERT_X509_AC, CERT_X509_CRL, countof, KEY_BLISS, KEY_DSA, KEY_ECDSA, KEY_RSA, PLUGIN_CALLBACK, PLUGIN_PROVIDE, PLUGIN_SDEPEND, and register_stroke().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)register_stroke, NULL),
             PLUGIN_PROVIDE(CUSTOM, "stroke"),
                 PLUGIN_SDEPEND(PRIVKEY, KEY_RSA),
                 PLUGIN_SDEPEND(PRIVKEY, KEY_ECDSA),
                 PLUGIN_SDEPEND(PRIVKEY, KEY_DSA),
                 PLUGIN_SDEPEND(PRIVKEY, KEY_BLISS),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_ANY),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509_CRL),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509_AC),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_TRUSTED_PUBKEY),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_stroke_plugin_t * this)
Definition at line 83 of file stroke_plugin.c.
References free().
 {
     free(this);
 }
static bool register_stroke (private_stroke_plugin_t * this, plugin_feature_t * feature, bool reg, void * data) static
Register stroke plugin features
Definition at line 48 of file stroke_plugin.c.
References DESTROY_IF, socket, stroke_socket_create(), and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->socket = stroke_socket_create();
         return this->socket != NULL;
     }
     else
     {
         DESTROY_IF(this->socket);
         return TRUE;
     }
 }
plugin_t* stroke_plugin_create ()
Definition at line 92 of file stroke_plugin.c.
References destroy(), INIT, and return_false().
 {
     private_stroke_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .reload = (void*)return_false,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }