strongSwan: ietf_attr_remediation_instr.c File Reference
ietf_attr_remediation_instr.c File Reference
#include "ietf_attr_remediation_instr.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_remediation_instr_t
Macros
#define REMEDIATION_INSTR_MIN_SIZE 8
#define REMEDIATION_INSTR_RESERVED 0x00
Typedefs
typedef struct
private_ietf_attr_remediation_instr_t private_ietf_attr_remediation_instr_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_remediation_instr_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_remediation_instr_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_remediation_instr_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_remediation_instr_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_remediation_instr_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_remediation_instr_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_remediation_instr_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_remediation_instr_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_remediation_instr_t *this)
METHOD (ietf_attr_remediation_instr_t, get_parameters_type, pen_type_t, private_ietf_attr_remediation_instr_t *this)
METHOD (ietf_attr_remediation_instr_t, get_parameters, chunk_t, private_ietf_attr_remediation_instr_t *this)
METHOD (ietf_attr_remediation_instr_t, get_string, chunk_t, private_ietf_attr_remediation_instr_t *this, chunk_t *lang_code)
pa_tnc_attr_t * ietf_attr_remediation_instr_create (pen_type_t parameters_type, chunk_t parameters)
pa_tnc_attr_t * ietf_attr_remediation_instr_create_from_uri (chunk_t uri)
pa_tnc_attr_t * ietf_attr_remediation_instr_create_from_string (chunk_t string, chunk_t lang_code)
pa_tnc_attr_t * ietf_attr_remediation_instr_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define REMEDIATION_INSTR_MIN_SIZE 8
PA-TNC Remediation Instructions type (see section 4.2.10 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Remediation Parameters Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Remediation Parameters Type | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Remediation Parameters (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 39 of file ietf_attr_remediation_instr.c.
Referenced by METHOD().
#define REMEDIATION_INSTR_RESERVED 0x00
Definition at line 40 of file ietf_attr_remediation_instr.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_remediation_instr_t private_ietf_attr_remediation_instr_t
Definition at line 23 of file ietf_attr_remediation_instr.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_remediation_instr_t * this)
Definition at line 122 of file ietf_attr_remediation_instr.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_remediation_instr_t * this)
Definition at line 128 of file ietf_attr_remediation_instr.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_remediation_instr_t * this)
Definition at line 134 of file ietf_attr_remediation_instr.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_remediation_instr_t * this, bool noskip)
Definition at line 140 of file ietf_attr_remediation_instr.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_remediation_instr_t * this)
Definition at line 146 of file ietf_attr_remediation_instr.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, length, REMEDIATION_INSTR_MIN_SIZE, REMEDIATION_INSTR_RESERVED, value, bio_writer_t::write_data, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(REMEDIATION_INSTR_MIN_SIZE);
     writer->write_uint8 (writer, REMEDIATION_INSTR_RESERVED);
     writer->write_uint24(writer, this->parameters_type.vendor_id);
     writer->write_uint32(writer, this->parameters_type.type);
     writer->write_data  (writer, this->parameters);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_remediation_instr_t * this, u_int32_t * offset)
Definition at line 167 of file ietf_attr_remediation_instr.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, end, FAILED, IETF_REMEDIATION_PARAMETERS_STRING, len, NEED_MORE, PEN_IETF, bio_reader_t::read_data, bio_reader_t::read_data32, bio_reader_t::read_data8, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, REMEDIATION_INSTR_MIN_SIZE, reserved, status, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int8_t reserved;
     status_t status = SUCCESS;
     u_char *pos;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < REMEDIATION_INSTR_MIN_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for IETF remediation instructions");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &reserved);
     reader->read_uint24(reader, &this->parameters_type.vendor_id);
     reader->read_uint32(reader, &this->parameters_type.type);
     reader->read_data  (reader, reader->remaining(reader), &this->parameters);
     this->parameters = chunk_clone(this->parameters);
     reader->destroy(reader);
     if (this->parameters_type.vendor_id == PEN_IETF &&
         this->parameters_type.type == IETF_REMEDIATION_PARAMETERS_STRING)
     {
         reader = bio_reader_create(this->parameters);
         status = FAILED;
         *offset = 8;
         if (!reader->read_data32(reader, &this->string))
         {
             DBG1(DBG_TNC, "insufficient data for IETF remediation string");
             goto end;
         }
         *offset += 4;
         pos = memchr(this->string.ptr, '\0', this->string.len);
         if (pos)
         {
             DBG1(DBG_TNC, "nul termination in IETF remediation string");
             *offset += (pos - this->string.ptr);
             goto end;
         }
         *offset += this->string.len;
         if (!reader->read_data8(reader, &this->lang_code))
         {
             DBG1(DBG_TNC, "insufficient data for IETF remediation lang code");
             goto end;
         }
         status = SUCCESS;
 end:
         reader->destroy(reader);
     }
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_remediation_instr_t * this, chunk_t segment)
Definition at line 231 of file ietf_attr_remediation_instr.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_remediation_instr_t * this)
Definition at line 237 of file ietf_attr_remediation_instr.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_remediation_instr_t * this)
Definition at line 244 of file ietf_attr_remediation_instr.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->parameters.ptr);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_remediation_instr_t , get_parameters_type , pen_type_t , private_ietf_attr_remediation_instr_t * this)
Definition at line 255 of file ietf_attr_remediation_instr.c.
 {
     return this->parameters_type;
 }
METHOD (ietf_attr_remediation_instr_t , get_parameters , chunk_t , private_ietf_attr_remediation_instr_t * this)
Definition at line 261 of file ietf_attr_remediation_instr.c.
 {
     return this->parameters;
 }
METHOD (ietf_attr_remediation_instr_t , get_string , chunk_t , private_ietf_attr_remediation_instr_t * this, chunk_t * lang_code)
Definition at line 267 of file ietf_attr_remediation_instr.c.
References string.
 {
     if (lang_code)
     {
         *lang_code = this->lang_code;
     }
     return this->string;
 }