strongSwan: medsrv_config
medsrv_config
medsrv
Classes
struct medsrv_config_t
Typedefs
typedef struct medsrv_config_t medsrv_config_t
Functions
medsrv_config_t * medsrv_config_create (database_t *db)
Detailed Description
Typedef Documentation
typedef struct medsrv_config_t medsrv_config_t
Definition at line 27 of file medsrv_config.h.
Function Documentation
medsrv_config_t* medsrv_config_create (database_t * db)
Create a medsrv_config backend instance.
Parameters
db underlying database
Returns
backend instance
Described in header.
Definition at line 126 of file medsrv_config.c.
References charon, db, FALSE, FRAGMENTATION_NO, socket_manager_t::get_port, settings_t::get_time, ike_cfg_create(), IKEV2, IKEV2_UDP_PORT, INIT, lib, proposal_create_default(), proposal_create_default_aead(), PROTO_IKE, library_t::settings, and daemon_t::socket.
Referenced by open_database().
 {
     private_medsrv_config_t *this;
     INIT(this,
         .public = {
             .backend = {
                 .create_peer_cfg_enumerator = _create_peer_cfg_enumerator,
                 .create_ike_cfg_enumerator = _create_ike_cfg_enumerator,
                 .get_peer_cfg_by_name = _get_peer_cfg_by_name,
             },
             .destroy = _destroy,
         },
         .db = db,
         .rekey = lib->settings->get_time(lib->settings, "medsrv.rekey", 1200),
         .dpd = lib->settings->get_time(lib->settings, "medsrv.dpd", 300),
         .ike = ike_cfg_create(IKEV2, FALSE, FALSE, "0.0.0.0",
                               charon->socket->get_port(charon->socket, FALSE),
                               "0.0.0.0", IKEV2_UDP_PORT,
                               FRAGMENTATION_NO, 0),
     );
     this->ike->add_proposal(this->ike, proposal_create_default(PROTO_IKE));
     this->ike->add_proposal(this->ike, proposal_create_default_aead(PROTO_IKE));
     return &this->public;
 }