strongSwan: format-options.ConfFormatter Class Reference
format-options.ConfFormatter Class Reference
Public Member Functions
def __init__
def format
Private Member Functions
def __print_description
def __print_option
def __print_section
Private Attributes
__indent
__wrapper
__tags
Detailed Description
Formats options to a strongswan.conf snippet
Definition at line 221 of file format-options.py.
Constructor & Destructor Documentation
def format-options.ConfFormatter.__init__ (self)
Definition at line 223 of file format-options.py.
     def __init__(self):
         self.__indent = '    '
         self.__wrapper = TextWrapper(width = 80, replace_whitespace = True,
                                      break_long_words = False, break_on_hyphens = False)
         self.__tags = TagReplacer()
Member Function Documentation
def format-options.ConfFormatter.__print_description (self, opt, indent) private
Definition at line 229 of file format-options.py.
References format-options.ConfFormatter.__indent, format-options.ConfFormatter.format(), len, and print().
Referenced by format-options.ConfFormatter.__print_option(), and format-options.ConfFormatter.__print_section().
     def __print_description(self, opt, indent):
         if len(opt.desc):
             self.__wrapper.initial_indent = '{0}# '.format(self.__indent * indent)
             self.__wrapper.subsequent_indent = self.__wrapper.initial_indent
             print(self.__wrapper.fill(self.__tags.replace(opt.desc[0])))
def format-options.ConfFormatter.__print_option (self, opt, indent, commented) private
Print a single option with description and default value
Definition at line 235 of file format-options.py.
References format-options.ConfFormatter.__indent, format-options.ConfFormatter.__print_description(), format-options.ConfFormatter.format(), and print().
Referenced by format-options.ConfFormatter.__print_section(), and format-options.ConfFormatter.format().
     def __print_option(self, opt, indent, commented):
         """Print a single option with description and default value"""
         comment = "# " if commented or opt.commented else ""
         self.__print_description(opt, indent)
         if opt.default:
             print('{0}{1}{2} = {3}'.format(self.__indent * indent, comment, opt.name, opt.default))
         else:
             print('{0}{1}{2} ='.format(self.__indent * indent, comment, opt.name))
         print('')
def format-options.ConfFormatter.__print_section (self, section, indent, commented) private
Print a section with all options
Definition at line 245 of file format-options.py.
References format-options.ConfFormatter.__indent, format-options.ConfFormatter.__print_description(), format-options.ConfFormatter.__print_option(), format-options.ConfFormatter.__print_section(), format-options.ConfFormatter.format(), and print().
Referenced by format-options.ConfFormatter.__print_section(), and format-options.ConfFormatter.format().
     def __print_section(self, section, indent, commented):
         """Print a section with all options"""
         commented = commented or section.commented
         comment = "# " if commented else ""
         self.__print_description(section, indent)
         print('{0}{1}{2} {{'.format(self.__indent * indent, comment, section.name))
         print('')
         for o in sorted(section.options, key=attrgetter('section')):
             if o.section:
                 self.__print_section(o, indent + 1, commented)
             else:
                 self.__print_option(o, indent + 1, commented)
         print('{0}{1}}}'.format(self.__indent * indent, comment))
         print('')
def format-options.ConfFormatter.format (self, options)
Print a list of options
Definition at line 260 of file format-options.py.
References format-options.ConfFormatter.__print_option(), and format-options.ConfFormatter.__print_section().
Referenced by format-options.ConfFormatter.__print_description(), format-options.ConfFormatter.__print_option(), format-options.ConfFormatter.__print_section(), and format-options.ManFormatter.format().
     def format(self, options):
         """Print a list of options"""
         if not options:
             return
         for option in sorted(options, key=attrgetter('section')):
             if option.section:
                 self.__print_section(option, 0, False)
             else:
                 self.__print_option(option, 0, False)
Member Data Documentation
format-options.ConfFormatter.__indent private
Definition at line 224 of file format-options.py.
Referenced by format-options.ConfFormatter.__print_description(), format-options.ConfFormatter.__print_option(), and format-options.ConfFormatter.__print_section().
format-options.ConfFormatter.__tags private
Definition at line 227 of file format-options.py.
format-options.ConfFormatter.__wrapper private
Definition at line 225 of file format-options.py.
The documentation for this class was generated from the following file:
format-options.py