strongSwan: rwlock_condvar
rwlock_condvar
threading
Classes
struct rwlock_condvar_t
Typedefs
typedef struct rwlock_condvar_t rwlock_condvar_t
Functions
rwlock_condvar_t * rwlock_condvar_create ()
Detailed Description
Typedef Documentation
typedef struct rwlock_condvar_t rwlock_condvar_t
Definition at line 24 of file rwlock_condvar.h.
Function Documentation
rwlock_condvar_t* rwlock_condvar_create ()
Create a condvar instance.
Returns
condvar instance
Definition at line 482 of file rwlock.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, INIT, mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by cancellation_rwcond(), kernel_netlink_net_create(), shunt_manager_create(), START_TEST(), and trap_manager_create().
 {
     private_rwlock_condvar_t *this;
     INIT(this,
         .public = {
             .wait = _wait_,
             .timed_wait = _timed_wait,
             .timed_wait_abs = _timed_wait_abs,
             .signal = _signal_,
             .broadcast = _broadcast,
             .destroy = _condvar_destroy,
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
     );
     return &this->public;
 }