strongSwan: openssl_ec_diffie_hellman
openssl_ec_diffie_hellman
openssl
Classes
struct openssl_ec_diffie_hellman_t
Typedefs
typedef struct
openssl_ec_diffie_hellman_t openssl_ec_diffie_hellman_t
Functions
openssl_ec_diffie_hellman_t * openssl_ec_diffie_hellman_create (diffie_hellman_group_t group)
Detailed Description
Typedef Documentation
typedef struct openssl_ec_diffie_hellman_t openssl_ec_diffie_hellman_t
Definition at line 24 of file openssl_ec_diffie_hellman.h.
Function Documentation
openssl_ec_diffie_hellman_t* openssl_ec_diffie_hellman_create (diffie_hellman_group_t group)
Creates a new openssl_ec_diffie_hellman_t object.
Parameters
group EC Diffie Hellman group number to use
Returns
openssl_ec_diffie_hellman_t object, NULL if not supported
Definition at line 595 of file openssl_ec_diffie_hellman.c.
References destroy(), ec_key_new_brainpool(), ECP_192_BIT, ECP_224_BIT, ECP_224_BP, ECP_256_BIT, ECP_256_BP, ECP_384_BIT, ECP_384_BP, ECP_512_BP, ECP_521_BIT, free(), group, INIT, and key.
Referenced by METHOD().
 {
     private_openssl_ec_diffie_hellman_t *this;
     INIT(this,
         .public = {
             .dh = {
                 .get_shared_secret = _get_shared_secret,
                 .set_other_public_value = _set_other_public_value,
                 .get_my_public_value = _get_my_public_value,
                 .set_private_value = _set_private_value,
                 .get_dh_group = _get_dh_group,
                 .destroy = _destroy,
             },
         },
         .group = group,
     );
     switch (group)
     {
         case ECP_192_BIT:
             this->key = EC_KEY_new_by_curve_name(NID_X9_62_prime192v1);
             break;
         case ECP_224_BIT:
             this->key = EC_KEY_new_by_curve_name(NID_secp224r1);
             break;
         case ECP_256_BIT:
             this->key = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
             break;
         case ECP_384_BIT:
             this->key = EC_KEY_new_by_curve_name(NID_secp384r1);
             break;
         case ECP_521_BIT:
             this->key = EC_KEY_new_by_curve_name(NID_secp521r1);
             break;
         case ECP_224_BP:
         case ECP_256_BP:
         case ECP_384_BP:
         case ECP_512_BP:
             this->key = ec_key_new_brainpool(group);
             break;
         default:
             this->key = NULL;
             break;
     }
     if (!this->key)
     {
         free(this);
         return NULL;
     }
     /* caching the EC group */
     this->ec_group = EC_KEY_get0_group(this->key);
     this->pub_key = EC_POINT_new(this->ec_group);
     if (!this->pub_key)
     {
         destroy(this);
         return NULL;
     }
     /* generate an EC private (public) key */
     if (!EC_KEY_generate_key(this->key))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }