strongSwan: pb_pdp_referral_msg.c File Reference
pb_pdp_referral_msg.c File Reference
#include "pb_pdp_referral_msg.h"
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pb_pdp_referral_msg_t
Macros
#define PDP_REFERRAL_HEADER_SIZE 8
#define PDP_REFERRAL_ID_HEADER_SIZE 4
#define PDP_REFERRAL_RESERVED 0x00
#define PDP_REFERRAL_PROTOCOL 0x00
Typedefs
typedef struct
private_pb_pdp_referral_msg_t private_pb_pdp_referral_msg_t
Functions
ENUM (pb_tnc_pdp_identifier_type_names, PB_PDP_ID_FQDN, PB_PDP_ID_IPV6,"PDP FQDN ID","PDP IPv4 ID","PDP IPv6 ID")
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_pdp_referral_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_pdp_referral_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_pdp_referral_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_pdp_referral_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_pdp_referral_msg_t *this)
METHOD (pb_pdp_referral_msg_t, get_identifier_type, pen_type_t, private_pb_pdp_referral_msg_t *this)
METHOD (pb_pdp_referral_msg_t, get_identifier, chunk_t, private_pb_pdp_referral_msg_t *this)
METHOD (pb_pdp_referral_msg_t, get_fqdn, chunk_t, private_pb_pdp_referral_msg_t *this, u_int8_t *protocol, u_int16_t *port)
pb_tnc_msg_t * pb_pdp_referral_msg_create (pen_type_t identifier_type, chunk_t identifier)
pb_tnc_msg_t * pb_pdp_referral_msg_create_from_fqdn (chunk_t fqdn, u_int16_t port)
pb_tnc_msg_t * pb_pdp_referral_msg_create_from_data (chunk_t data)
Macro Definition Documentation
#define PDP_REFERRAL_HEADER_SIZE 8
PB-PDP-Referral message (see section 3.1.1.1 of TCG TNC PDP Discovery and Validation Specification 1.0
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | PDP Identifier Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PDP Identifier Type | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PDP Identifier (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Section 3.1.1.2.1 FQDN Identifier
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Protocol | Port Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | FQDN (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Section 3.1.1.2.2 IPv4 Identifier
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Protocol | Port Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | IPv4 Address | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Section 3.1.1.2.3 IPv6 Identifier
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | Protocol | Port Number | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | IPv6 Address (octets 1-4) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | IPv6 Address (octets 5-8) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | IPv6 Address (octets 9-12) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | IPv6 Address (octets 13-16) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 82 of file pb_pdp_referral_msg.c.
Referenced by METHOD().
#define PDP_REFERRAL_ID_HEADER_SIZE 4
Definition at line 83 of file pb_pdp_referral_msg.c.
Referenced by METHOD(), and pb_pdp_referral_msg_create_from_fqdn().
#define PDP_REFERRAL_PROTOCOL 0x00
Definition at line 85 of file pb_pdp_referral_msg.c.
Referenced by pb_pdp_referral_msg_create_from_fqdn().
#define PDP_REFERRAL_RESERVED 0x00
Definition at line 84 of file pb_pdp_referral_msg.c.
Referenced by METHOD(), and pb_pdp_referral_msg_create_from_fqdn().
Typedef Documentation
typedef struct private_pb_pdp_referral_msg_t private_pb_pdp_referral_msg_t
Definition at line 28 of file pb_pdp_referral_msg.c.
Function Documentation
ENUM (pb_tnc_pdp_identifier_type_names , PB_PDP_ID_FQDN , PB_PDP_ID_IPV6 , "PDP FQDN ID" , "PDP IPv4 ID" , "PDP IPv6 ID")
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_pdp_referral_msg_t * this)
Definition at line 133 of file pb_pdp_referral_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_pdp_referral_msg_t * this)
Definition at line 139 of file pb_pdp_referral_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_pdp_referral_msg_t * this)
Definition at line 145 of file pb_pdp_referral_msg.c.
References bio_writer_create(), chunk_clone, bio_writer_t::destroy, encoding, bio_writer_t::get_buf, identifier, PDP_REFERRAL_HEADER_SIZE, PDP_REFERRAL_RESERVED, bio_writer_t::write_data, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     writer = bio_writer_create(PDP_REFERRAL_HEADER_SIZE + this->identifier.len);
     writer->write_uint8 (writer, PDP_REFERRAL_RESERVED);
     writer->write_uint24(writer, this->identifier_type.vendor_id);
     writer->write_uint32(writer, this->identifier_type.type);
     writer->write_data  (writer, this->identifier);
     this->encoding = writer->get_buf(writer);
     this->encoding = chunk_clone(this->encoding);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_pdp_referral_msg_t * this, u_int32_t * offset)
Definition at line 165 of file pb_pdp_referral_msg.c.
References bio_reader_create(), chunk_clone, bio_reader_t::destroy, encoding, FAILED, identifier, PB_PDP_ID_FQDN, PDP_REFERRAL_HEADER_SIZE, PDP_REFERRAL_ID_HEADER_SIZE, PEN_TCG, port, protocol, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, and SUCCESS.
 {
     bio_reader_t *reader;
     u_int8_t reserved;
     *offset = 0;
     /* process message */
     reader = bio_reader_create(this->encoding);
     reader->read_uint8 (reader, &reserved);
     reader->read_uint24(reader, &this->identifier_type.vendor_id);
     reader->read_uint32(reader, &this->identifier_type.type);
     reader->read_data  (reader, reader->remaining(reader), &this->identifier);
     this->identifier = chunk_clone(this->identifier);
     reader->destroy(reader);
     if (this->identifier_type.vendor_id == PEN_TCG &&
         this->identifier_type.type == PB_PDP_ID_FQDN)
     {
         reader = bio_reader_create(this->identifier);
         *offset += PDP_REFERRAL_HEADER_SIZE;
         if (this->identifier.len <= PDP_REFERRAL_ID_HEADER_SIZE)
         {
             reader->destroy(reader);
             return FAILED;
         }
         reader->read_uint8 (reader, &reserved);
         reader->read_uint8 (reader, &this->protocol);
         reader->read_uint16(reader, &this->port);
         reader->read_data  (reader, reader->remaining(reader), &this->fqdn);
         this->fqdn = chunk_clone(this->fqdn);
         reader->destroy(reader);
     }
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_pdp_referral_msg_t * this)
Definition at line 204 of file pb_pdp_referral_msg.c.
References encoding, free(), and identifier.
 {
     free(this->encoding.ptr);
     free(this->identifier.ptr);
     free(this->fqdn.ptr);
     free(this);
 }
METHOD (pb_pdp_referral_msg_t , get_identifier_type , pen_type_t , private_pb_pdp_referral_msg_t * this)
Definition at line 213 of file pb_pdp_referral_msg.c.
 {
     return this->identifier_type;
 }
METHOD (pb_pdp_referral_msg_t , get_identifier , chunk_t , private_pb_pdp_referral_msg_t * this)
Definition at line 219 of file pb_pdp_referral_msg.c.
References identifier.
 {
     return this->identifier;
 }
METHOD (pb_pdp_referral_msg_t , get_fqdn , chunk_t , private_pb_pdp_referral_msg_t * this, u_int8_t * protocol, u_int16_t * port)
Definition at line 225 of file pb_pdp_referral_msg.c.
References port, and protocol.
 {
     if (protocol)
     {
         *protocol = this->protocol;
     }
     if (port)
     {
         *port = this->port;
     }
     return this->fqdn;
 }