strongSwan: tls_aead_impl.c File Reference
tls_aead_impl.c File Reference
#include "tls_aead.h"
Classes
struct private_tls_aead_t
Typedefs
typedef struct private_tls_aead_t private_tls_aead_t
Functions
struct __attribute__ ((__packed__))
METHOD (tls_aead_t, encrypt, bool, private_tls_aead_t *this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t *data)
METHOD (tls_aead_t, decrypt, bool, private_tls_aead_t *this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t *data)
METHOD (tls_aead_t, get_mac_key_size, size_t, private_tls_aead_t *this)
METHOD (tls_aead_t, get_encr_key_size, size_t, private_tls_aead_t *this)
METHOD (tls_aead_t, get_iv_size, size_t, private_tls_aead_t *this)
METHOD (tls_aead_t, set_keys, bool, private_tls_aead_t *this, chunk_t mac, chunk_t encr, chunk_t iv)
METHOD (tls_aead_t, destroy, void, private_tls_aead_t *this)
tls_aead_t * tls_aead_create_implicit (integrity_algorithm_t mac, encryption_algorithm_t encr, size_t encr_size)
Variables
sigheader_t
Typedef Documentation
typedef struct private_tls_aead_t private_tls_aead_t
Definition at line 18 of file tls_aead_impl.c.
Function Documentation
METHOD (tls_aead_t , encrypt , bool , private_tls_aead_t * this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t * data)
Definition at line 56 of file tls_aead_impl.c.
References chunk_alloca, chunk_cat, chunk_from_thing, crypter, FALSE, htoun16(), htoun64(), chunk_t::len, memcpy, memset, pad_len(), padding, chunk_t::ptr, sigheader_t, signer, TRUE, and type.
 {
     chunk_t assoc, mac, padding;
     u_int8_t bs, padlen;
     sigheader_t hdr;
     hdr.type = type;
     htoun64(&hdr.seq, seq);
     htoun16(&hdr.version, version);
     htoun16(&hdr.length, data->len);
     assoc = chunk_from_thing(hdr);
     if (!this->signer->get_signature(this->signer, assoc, NULL) ||
         !this->signer->allocate_signature(this->signer, *data, &mac))
     {
         return FALSE;
     }
     bs = this->crypter->get_block_size(this->crypter);
     padlen = pad_len(data->len + mac.len + 1, bs);
     padding = chunk_alloca(padlen);
     memset(padding.ptr, padlen, padding.len);
     *data = chunk_cat("mmcc", *data, mac, padding, chunk_from_thing(padlen));
     /* encrypt inline */
     if (!this->crypter->encrypt(this->crypter, *data, this->iv, NULL))
     {
         return FALSE;
     }
     if (data->len < this->iv.len)
     {
         return FALSE;
     }
     /* next record IV is last ciphertext block of this record */
     memcpy(this->iv.ptr, data->ptr + data->len - this->iv.len, this->iv.len);
     return TRUE;
 }
METHOD (tls_aead_t , decrypt , bool , private_tls_aead_t * this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t * data)
Definition at line 96 of file tls_aead_impl.c.
References chunk_alloca, chunk_from_thing, chunk_skip(), crypter, FALSE, htoun16(), htoun64(), chunk_t::len, len, memcpy, chunk_t::ptr, sigheader_t, signer, TRUE, and type.
 {
     chunk_t assoc, mac, iv;
     u_int8_t bs, padlen;
     sigheader_t hdr;
     size_t i;
     bs = this->crypter->get_block_size(this->crypter);
     if (data->len < bs || data->len < this->iv.len || data->len % bs)
     {
         return FALSE;
     }
     iv = chunk_alloca(this->iv.len);
     memcpy(iv.ptr, this->iv.ptr, this->iv.len);
     memcpy(this->iv.ptr, data->ptr + data->len - this->iv.len, this->iv.len);
     if (!this->crypter->decrypt(this->crypter, *data, iv, NULL))
     {
         return FALSE;
     }
     padlen = data->ptr[data->len - 1];
     if (padlen < data->len)
     {   /* If padding looks valid, remove it */
         for (i = data->len - padlen - 1; i < data->len - 1; i++)
         {
             if (data->ptr[i] != padlen)
             {
                 return FALSE;
             }
         }
         data->len -= padlen + 1;
     }
     bs = this->signer->get_block_size(this->signer);
     if (data->len < bs)
     {
         return FALSE;
     }
     mac = chunk_skip(*data, data->len - bs);
     data->len -= bs;
     hdr.type = type;
     htoun64(&hdr.seq, seq);
     htoun16(&hdr.version, version);
     htoun16(&hdr.length, data->len);
     assoc = chunk_from_thing(hdr);
     if (!this->signer->get_signature(this->signer, assoc, NULL) ||
         !this->signer->verify_signature(this->signer, *data, mac))
     {
         return FALSE;
     }
     return TRUE;
 }
METHOD (tls_aead_t , get_mac_key_size , size_t , private_tls_aead_t * this)
Definition at line 152 of file tls_aead_impl.c.
References signer.
 {
     return this->signer->get_key_size(this->signer);
 }
METHOD (tls_aead_t , get_encr_key_size , size_t , private_tls_aead_t * this)
Definition at line 158 of file tls_aead_impl.c.
References crypter.
 {
     return this->crypter->get_key_size(this->crypter);
 }
METHOD (tls_aead_t , get_iv_size , size_t , private_tls_aead_t * this)
Definition at line 164 of file tls_aead_impl.c.
 {
     return this->iv.len;
 }
METHOD (tls_aead_t , set_keys , bool , private_tls_aead_t * this, chunk_t mac, chunk_t encr, chunk_t iv)
Definition at line 170 of file tls_aead_impl.c.
References crypter, FALSE, chunk_t::len, memcpy, chunk_t::ptr, and signer.
 {
     if (iv.len != this->iv.len)
     {
         return FALSE;
     }
     memcpy(this->iv.ptr, iv.ptr, this->iv.len);
     return this->signer->set_key(this->signer, mac) &&
            this->crypter->set_key(this->crypter, encr);
 }
METHOD (tls_aead_t , destroy , void , private_tls_aead_t * this)
Definition at line 182 of file tls_aead_impl.c.
References chunk_free(), crypter, DESTROY_IF, free(), and signer.
 {
     DESTROY_IF(this->crypter);
     DESTROY_IF(this->signer);
     chunk_free(&this->iv);
     free(this);
 }
Variable Documentation
sigheader_t
Definition at line 54 of file tls_aead_impl.c.
Referenced by METHOD().