strongSwan: ldap_fetcher.c File Reference
ldap_fetcher.c File Reference
#include <ldap.h>
#include <errno.h>
#include <library.h>
#include <utils/debug.h>
#include "ldap_fetcher.h"
Classes
struct private_ldap_fetcher_t
Macros
#define LDAP_DEPRECATED 1
#define DEFAULT_TIMEOUT 10
Typedefs
typedef struct
private_ldap_fetcher_t private_ldap_fetcher_t
Functions
static bool parse (LDAP *ldap, LDAPMessage *result, chunk_t *response)
METHOD (fetcher_t, fetch, status_t, private_ldap_fetcher_t *this, char *url, void *userdata)
METHOD (fetcher_t, set_option, bool, private_ldap_fetcher_t *this, fetcher_option_t option,...)
METHOD (fetcher_t, destroy, void, private_ldap_fetcher_t *this)
ldap_fetcher_t * ldap_fetcher_create ()
Macro Definition Documentation
#define DEFAULT_TIMEOUT 10
Definition at line 29 of file ldap_fetcher.c.
Referenced by ldap_fetcher_create().
#define LDAP_DEPRECATED 1
Definition at line 18 of file ldap_fetcher.c.
Typedef Documentation
typedef struct private_ldap_fetcher_t private_ldap_fetcher_t
Definition at line 31 of file ldap_fetcher.c.
Function Documentation
METHOD (fetcher_t , fetch , status_t , private_ldap_fetcher_t * this, char * url, void * userdata)
Definition at line 103 of file ldap_fetcher.c.
References DBG1, DBG2, DBG_LIB, FAILED, msg, NOT_SUPPORTED, parse(), res, result, status, strerror, strpfx(), and SUCCESS.
 {
     LDAP *ldap;
     LDAPURLDesc *lurl;
     LDAPMessage *msg;
     int res;
     int ldap_version = LDAP_VERSION3;
     struct timeval timeout;
     status_t status = FAILED;
     chunk_t *result = userdata;
     if (!strpfx(url, "ldap"))
     {
         return NOT_SUPPORTED;
     }
     if (ldap_url_parse(url, &lurl) != LDAP_SUCCESS)
     {
         return NOT_SUPPORTED;
     }
     ldap = ldap_init(lurl->lud_host, lurl->lud_port);
     if (ldap == NULL)
     {
         DBG1(DBG_LIB, "LDAP initialization failed: %s", strerror(errno));
         ldap_free_urldesc(lurl);
         return FAILED;
     }
     timeout.tv_sec = this->timeout;
     timeout.tv_usec = 0;
     ldap_set_option(ldap, LDAP_OPT_PROTOCOL_VERSION, &ldap_version);
     ldap_set_option(ldap, LDAP_OPT_NETWORK_TIMEOUT, &timeout);
     DBG2(DBG_LIB, "sending LDAP request to '%s'...", url);
     res = ldap_simple_bind_s(ldap, NULL, NULL);
     if (res == LDAP_SUCCESS)
     {
         res = ldap_search_st(ldap, lurl->lud_dn, lurl->lud_scope,
                              lurl->lud_filter, lurl->lud_attrs,
                              0, &timeout, &msg);
         if (res == LDAP_SUCCESS)
         {
             if (parse(ldap, msg, result))
             {
                 status = SUCCESS;
             }
             ldap_msgfree(msg);
         }
         else
         {
             DBG1(DBG_LIB, "LDAP search failed: %s", ldap_err2string(res));
         }
     }
     else
     {
         DBG1(DBG_LIB, "LDAP bind to '%s' failed: %s", url,
              ldap_err2string(res));
     }
     ldap_unbind_s(ldap);
     ldap_free_urldesc(lurl);
     return status;
 }
METHOD (fetcher_t , set_option , bool , private_ldap_fetcher_t * this, fetcher_option_t option, ...)
Definition at line 170 of file ldap_fetcher.c.
References FALSE, FETCH_TIMEOUT, and TRUE.
 {
     va_list args;
     va_start(args, option);
     switch (option)
     {
         case FETCH_TIMEOUT:
             this->timeout = va_arg(args, u_int);
             break;
         default:
             va_end(args);
             return FALSE;
     }
     va_end(args);
     return TRUE;
 }
METHOD (fetcher_t , destroy , void , private_ldap_fetcher_t * this)
Definition at line 189 of file ldap_fetcher.c.
References free().
 {
     free(this);
 }
static bool parse (LDAP * ldap, LDAPMessage * result, chunk_t * response) static
Parses the result returned by an ldap query
Definition at line 51 of file ldap_fetcher.c.
References chunk_alloc, DBG1, DBG_LIB, FALSE, chunk_t::len, memcpy, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     LDAPMessage *entry = ldap_first_entry(ldap, result);
     bool success = FALSE;
     if (entry)
     {
         BerElement *ber = NULL;
         char *attr;
         attr = ldap_first_attribute(ldap, entry, &ber);
         if (attr)
         {
             struct berval **values = ldap_get_values_len(ldap, entry, attr);
             if (values)
             {
                 if (values[0])
                 {
                     *response = chunk_alloc(values[0]->bv_len);
                     memcpy(response->ptr, values[0]->bv_val, response->len);
                     success = TRUE;
                 }
                 else
                 {
                     DBG1(DBG_LIB, "LDAP response contains no values");
                 }
                 ldap_value_free_len(values);
             }
             else
             {
                 DBG1(DBG_LIB, "getting LDAP values failed: %s",
                      ldap_err2string(ldap_result2error(ldap, entry, 0)));
             }
             ldap_memfree(attr);
         }
         else
         {
             DBG1(DBG_LIB, "finding LDAP attributes failed: %s",
                  ldap_err2string(ldap_result2error(ldap, entry, 0)));
         }
         ber_free(ber, 0);
     }
     else
     {
         DBG1(DBG_LIB, "finding first LDAP entry failed: %s",
              ldap_err2string(ldap_result2error(ldap, entry, 0)));
     }
     return success;
 }