strongSwan: imv_workitem_t Struct Reference
imv_workitem_t Struct Reference
imv_workitem
#include "imv_workitem.h"
Public Attributes
int(* get_id)(imv_workitem_t *this)
imv_workitem_type_t(* get_type)(imv_workitem_t *this)
void(* set_imv_id)(imv_workitem_t *this, TNC_IMVID imv_id)
TNC_IMVID(* get_imv_id)(imv_workitem_t *this)
char *(* get_arg_str)(imv_workitem_t *this)
int(* get_arg_int)(imv_workitem_t *this)
TNC_IMV_Action_Recommendation(* set_result)(imv_workitem_t *this, char *result, TNC_IMV_Evaluation_Result eval)
TNC_IMV_Action_Recommendation(* get_result)(imv_workitem_t *this, char **result)
void(* destroy)(imv_workitem_t *this)
Detailed Description
IMV database interface
Definition at line 56 of file imv_workitem.h.
Member Data Documentation
void(* imv_workitem_t::destroy)(imv_workitem_t *this)
Destroys an imv_workitem_t object
Definition at line 122 of file imv_workitem.h.
Referenced by imv_attestation_process(), and METHOD().
int(* imv_workitem_t::get_arg_int)(imv_workitem_t *this)
Get integer argument
Returns
Argument integer
Definition at line 98 of file imv_workitem.h.
Referenced by imv_attestation_process(), and METHOD().
char*(* imv_workitem_t::get_arg_str)(imv_workitem_t *this)
Get string argument
Returns
Argument string
Definition at line 91 of file imv_workitem.h.
Referenced by METHOD().
int(* imv_workitem_t::get_id)(imv_workitem_t *this)
Get primary workitem key
Returns
Primary workitem key
Definition at line 63 of file imv_workitem.h.
Referenced by imv_attestation_process(), and METHOD().
TNC_IMVID(* imv_workitem_t::get_imv_id)(imv_workitem_t *this)
Get IMV ID
Returns
IMV ID
Definition at line 84 of file imv_workitem.h.
Referenced by METHOD().
TNC_IMV_Action_Recommendation(* imv_workitem_t::get_result)(imv_workitem_t *this, char **result)
Set result string
Parameters
result Result string
Returns
Action Recommendatino
Definition at line 116 of file imv_workitem.h.
Referenced by METHOD().
imv_workitem_type_t(* imv_workitem_t::get_type)(imv_workitem_t *this)
Get workitem type
Returns
Workitem type
Definition at line 70 of file imv_workitem.h.
Referenced by imv_attestation_process(), and METHOD().
void(* imv_workitem_t::set_imv_id)(imv_workitem_t *this, TNC_IMVID imv_id)
Set IMV ID
Parameters
id IMV ID
Definition at line 77 of file imv_workitem.h.
Referenced by METHOD().
TNC_IMV_Action_Recommendation(* imv_workitem_t::set_result)(imv_workitem_t *this, char *result, TNC_IMV_Evaluation_Result eval)
Set result string
Parameters
result Result string
eval Evaluation Result
Returns
Action Recommendation
Definition at line 107 of file imv_workitem.h.
Referenced by imv_attestation_process(), and METHOD().
The documentation for this struct was generated from the following file:
imv_workitem.h