strongSwan: backtrace
backtrace
utils
Classes
struct backtrace_t
Typedefs
typedef struct backtrace_t backtrace_t
Functions
backtrace_t * backtrace_create (int skip)
void backtrace_dump (char *label, FILE *file, bool detailed)
void backtrace_init ()
void backtrace_deinit ()
Detailed Description
Typedef Documentation
typedef struct backtrace_t backtrace_t
Definition at line 24 of file backtrace.h.
Function Documentation
backtrace_t* backtrace_create (int skip)
Create a backtrace of the current stack.
Parameters
skip how many of the innerst frames to skip
Returns
backtrace
See header
Definition at line 822 of file backtrace.c.
References backtrace, countof, get_methods(), malloc(), max, and memcpy.
Referenced by backtrace_dump(), fatal_signal_handler(), HOOK(), segv_handler(), and test_sighandler().
 {
     private_backtrace_t *this;
     void *frames[50];
     int frame_count = 0;
 #ifdef HAVE_LIBUNWIND_H
     frame_count = backtrace_unwind(frames, countof(frames));
 #elif defined(HAVE_BACKTRACE)
     frame_count = backtrace(frames, countof(frames));
 #elif defined(HAVE_DBGHELP)
     frame_count = backtrace_win(frames, countof(frames));
 #elif defined(WIN32)
     frame_count = CaptureStackBackTrace(skip, countof(frames), frames, NULL);
     skip = 0;
 #endif
     frame_count = max(frame_count - skip, 0);
     this = malloc(sizeof(private_backtrace_t) + frame_count * sizeof(void*));
     memcpy(this->frames, frames + skip, frame_count * sizeof(void*));
     this->frame_count = frame_count;
     this->public = get_methods();
     return &this->public;
 }
void backtrace_deinit ()
Deinitialize backtracing framework.
Definition at line 426 of file backtrace.c.
Referenced by library_deinit(), and print_failures().
 {}
void backtrace_dump (char * label, FILE * file, bool detailed)
Create a backtrace, dump it and clean it up.
Parameters
label description to print for this backtrace, or NULL
file FILE to log backtrace to, NULL to dbg() function
detailed TRUE to resolve line/file using addr2line (slow)
See header
Definition at line 851 of file backtrace.c.
References backtrace, backtrace_create(), backtrace_t::destroy, backtrace_t::log, and println().
 {
     backtrace_t *backtrace;
     backtrace = backtrace_create(2);
     if (label)
     {
         println(file, "Debug backtrace: %s", label);
     }
     backtrace->log(backtrace, file, detailed);
     backtrace->destroy(backtrace);
 }
void backtrace_init ()
Initialize backtracing framework.
Definition at line 425 of file backtrace.c.
Referenced by library_init(), and print_failures().
 {}