strongSwan: pen
pen
pen
Classes
struct pen_type_t
Typedefs
typedef enum pen_t pen_t
typedef struct pen_type_t pen_type_t
Enumerations
enum pen_t {
PEN_IETF = 0x000000, PEN_IBM = 0x000002, PEN_MICROSOFT = 0x000137, PEN_REDHAT = 0x000908,
PEN_PWG = 0x000A8B, PEN_ALTIGA = 0x000c04, PEN_OSC = 0x002358, PEN_DEBIAN = 0x002572,
PEN_GOOGLE = 0x002B79, PEN_TCG = 0x005597, PEN_CANONICAL = 0x007132, PEN_FEDORA = 0x0076C1,
PEN_FHH = 0x0080ab, PEN_ITA = 0x00902a, PEN_OPENPTS = 0x00950e, PEN_UNASSIGNED = 0xfffffe,
PEN_RESERVED = 0xffffff
}
Functions
static pen_type_t pen_type_create (pen_t vendor_id, u_int32_t type)
static bool pen_type_equals (pen_type_t a, pen_type_t b)
static bool pen_type_is (pen_type_t pen_type, pen_t vendor_id, u_int32_t type)
Variables
enum_name_t * pen_names
Detailed Description
Typedef Documentation
typedef enum pen_t pen_t
Definition at line 29 of file pen.h.
typedef struct pen_type_t pen_type_t
Definition at line 30 of file pen.h.
Enumeration Type Documentation
enum pen_t
Private enterprise numbers allocated by IANA.
http://www.iana.org/assignments/enterprise-numbers
Enumerator
PEN_IETF
PEN_IBM
PEN_MICROSOFT
PEN_REDHAT
PEN_PWG
PEN_ALTIGA
PEN_OSC
PEN_DEBIAN
PEN_GOOGLE
PEN_TCG
PEN_CANONICAL
PEN_FEDORA
PEN_FHH
PEN_ITA
PEN_OPENPTS
PEN_UNASSIGNED
PEN_RESERVED
Definition at line 37 of file pen.h.
            {
     PEN_IETF =          0x000000,   /*        0 */
     PEN_IBM =           0x000002,   /*        2 */
     PEN_MICROSOFT =     0x000137,   /*      311 */
     PEN_REDHAT =        0x000908,   /*     2312 */
     PEN_PWG =           0x000A8B,   /*     2699 */
     PEN_ALTIGA =        0x000c04,   /*     3076 */
     PEN_OSC =           0x002358,   /*     9048 */
     PEN_DEBIAN =        0x002572,   /*     9586 */
     PEN_GOOGLE =        0x002B79,   /*    11129 */
     PEN_TCG =           0x005597,   /*    21911 */
     PEN_CANONICAL =     0x007132,   /*    28978 */
     PEN_FEDORA =        0x0076C1,   /*    30401 */
     PEN_FHH =           0x0080ab,   /*    32939 */
     PEN_ITA =           0x00902a,   /*    36906 */
     PEN_OPENPTS =       0x00950e,   /*    38158 */
     PEN_UNASSIGNED =    0xfffffe,   /* 16777214 */
     PEN_RESERVED =      0xffffff,   /* 16777215 */
 };
Function Documentation
static pen_type_t pen_type_create (pen_t vendor_id, u_int32_t type) inline static
Create a pen_type_t struct
Parameters
vendor_id vendor ID to create a pen_type_t
type type to create a pen_type_t
Returns
created pen_type_t
Definition at line 72 of file pen.h.
Referenced by add_attrs_natural_lang(), add_certification_state(), add_configuration_state(), add_default_pwd_enabled(), add_device_id(), add_forwarding_enabled(), add_fwd_enabled(), add_machine_type_model(), add_port_filter(), add_pstn_fax_enabled(), add_quadruple(), add_time_source(), add_user_app_enabled(), add_user_app_persist_enabled(), add_vendor_name(), ietf_attr_create_from_data(), imc_attestation_process(), imc_msg_create_from_long_data(), imv_msg_create_from_long_data(), imv_swid_agent_create(), ita_attr_create_from_data(), METHOD(), process_tnc_msg(), pwg_attr_create_from_data(), seg_env_create_from_data(), START_TEST(), swid_error_create(), and TNC_IMC_BeginHandshake().
 {
     pen_type_t pen_type = { vendor_id, type };
     return pen_type;
 }
static bool pen_type_equals (pen_type_t a, pen_type_t b) inline static
Check two pen_type_t for equality.
Parameters
a first pen_type_t to compare
b second pen_type_t to compare
Returns
TRUE if a == b
Definition at line 85 of file pen.h.
References pen_type_t::type, and pen_type_t::vendor_id.
Referenced by METHOD(), and START_TEST().
 {
     return a.vendor_id == b.vendor_id && a.type == b.type;
 }
static bool pen_type_is (pen_type_t pen_type, pen_t vendor_id, u_int32_t type) inline static
Check if a pen_type_t matches vendor and type.
Parameters
pen_type pen_type_t to compare
vendor_id vendor to check in pen_type
type type to check in pen_type
Returns
TRUE if vendor_id and type matches pen_type
Definition at line 98 of file pen.h.
References type, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by START_TEST().
 {
     return pen_type.vendor_id == vendor_id && pen_type.type == type;
 }
Variable Documentation
enum_name_t* pen_names
enum names for pen_t.
Referenced by handle_ietf_message(), handle_message(), imc_attestation_process(), imv_attestation_process(), METHOD(), print_cfn(), process_tnc_msg(), receive_msg(), and TNC_IMC_BeginHandshake().