strongSwan: xauth_pam.c File Reference
xauth_pam.c File Reference
#include "xauth_pam.h"
#include <daemon.h>
#include <library.h>
#include <security/pam_appl.h>
Classes
struct private_xauth_pam_t
Typedefs
typedef struct private_xauth_pam_t private_xauth_pam_t
Functions
METHOD (xauth_method_t, initiate, status_t, private_xauth_pam_t *this, cp_payload_t **out)
static int auth_conv (int num_msg, const struct pam_message **msg, struct pam_response **resp, char *password)
static bool authenticate (char *service, char *user, char *password)
static void attr2string (char *buf, size_t len, chunk_t chunk)
METHOD (xauth_method_t, process, status_t, private_xauth_pam_t *this, cp_payload_t *in, cp_payload_t **out)
METHOD (xauth_method_t, get_identity, identification_t *, private_xauth_pam_t *this)
METHOD (xauth_method_t, destroy, void, private_xauth_pam_t *this)
xauth_pam_t * xauth_pam_create_server (identification_t *server, identification_t *peer, char *profile)
Typedef Documentation
typedef struct private_xauth_pam_t private_xauth_pam_t
Definition at line 23 of file xauth_pam.c.
Function Documentation
static void attr2string (char * buf, size_t len, chunk_t chunk) static
Convert configuration attribute content to a null-terminated string
Definition at line 115 of file xauth_pam.c.
References chunk_clear(), chunk_printable(), chunk_t::len, chunk_t::ptr, and snprintf.
Referenced by METHOD().
 {
     if (chunk.len && chunk.len < len)
     {
         chunk_t sane;
         chunk_printable(chunk, &sane, '?');
         snprintf(buf, len, "%.*s", (int)sane.len, sane.ptr);
         chunk_clear(&sane);
     }
 }
static int auth_conv (int num_msg, const struct pam_message ** msg, struct pam_response ** resp, char * password) static
PAM conv callback function
Definition at line 58 of file xauth_pam.c.
References malloc(), response, and strdup.
Referenced by authenticate().
 {
     struct pam_response *response;
     if (num_msg != 1)
     {
         return PAM_CONV_ERR;
     }
     response = malloc(sizeof(struct pam_response));
     response->resp = strdup(password);
     response->resp_retcode = 0;
     *resp = response;
     return PAM_SUCCESS;
 }
static bool authenticate (char * service, char * user, char * password) static
Authenticate a username/password using PAM
Definition at line 77 of file xauth_pam.c.
References auth_conv(), DBG1, DBG_IKE, and FALSE.
Referenced by METHOD().
 {
     pam_handle_t *pamh = NULL;
     static struct pam_conv conv;
     int ret;
     conv.conv = (void*)auth_conv;
     conv.appdata_ptr = password;
     ret = pam_start(service, user, &conv, &pamh);
     if (ret != PAM_SUCCESS)
     {
         DBG1(DBG_IKE, "XAuth pam_start for '%s' failed: %s",
              user, pam_strerror(pamh, ret));
         return FALSE;
     }
     ret = pam_authenticate(pamh, 0);
     if (ret == PAM_SUCCESS)
     {
         ret = pam_acct_mgmt(pamh, 0);
         if (ret != PAM_SUCCESS)
         {
             DBG1(DBG_IKE, "XAuth pam_acct_mgmt for '%s' failed: %s",
                  user, pam_strerror(pamh, ret));
         }
     }
     else
     {
         DBG1(DBG_IKE, "XAuth pam_authenticate for '%s' failed: %s",
              user, pam_strerror(pamh, ret));
     }
     pam_end(pamh, ret);
     return ret == PAM_SUCCESS;
 }
METHOD (xauth_method_t , initiate , status_t , private_xauth_pam_t * this, cp_payload_t ** out)
Definition at line 41 of file xauth_pam.c.
References cp_payload_t::add_attribute, CFG_REQUEST, chunk_empty, configuration_attribute_create_chunk(), cp, cp_payload_create_type(), NEED_MORE, PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_NAME, and XAUTH_USER_PASSWORD.
 {
     cp_payload_t *cp;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REQUEST);
     cp->add_attribute(cp, configuration_attribute_create_chunk(
                 PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_NAME, chunk_empty));
     cp->add_attribute(cp, configuration_attribute_create_chunk(
                 PLV1_CONFIGURATION_ATTRIBUTE, XAUTH_USER_PASSWORD, chunk_empty));
     *out = cp;
     return NEED_MORE;
 }
METHOD (xauth_method_t , process , status_t , private_xauth_pam_t * this, cp_payload_t * in, cp_payload_t ** out)
Definition at line 127 of file xauth_pam.c.
References attr2string(), authenticate(), cp_payload_t::create_attribute_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FAILED, settings_t::get_bool, configuration_attribute_t::get_chunk, settings_t::get_str, configuration_attribute_t::get_type, identification_create_from_string(), chunk_t::len, lib, library_t::ns, chunk_t::ptr, library_t::settings, SUCCESS, TRUE, XAUTH_USER_NAME, and XAUTH_USER_PASSWORD.
 {
     char *service, user[128] = "", pass[128] = "", *pos;
     configuration_attribute_t *attr;
     enumerator_t *enumerator;
     chunk_t chunk;
     enumerator = in->create_attribute_enumerator(in);
     while (enumerator->enumerate(enumerator, &attr))
     {
         switch (attr->get_type(attr))
         {
             case XAUTH_USER_NAME:
                 chunk = attr->get_chunk(attr);
                 /* trim to username part if email address given */
                 if (lib->settings->get_bool(lib->settings,
                                             "%s.plugins.xauth-pam.trim_email",
                                             TRUE, lib->ns))
                 {
                     pos = memchr(chunk.ptr, '@', chunk.len);
                     if (pos)
                     {
                         chunk.len = (u_char*)pos - chunk.ptr;
                     }
                 }
                 attr2string(user, sizeof(user), chunk);
                 break;
             case XAUTH_USER_PASSWORD:
                 chunk = attr->get_chunk(attr);
                 if (chunk.len && chunk.ptr[chunk.len - 1] == 0)
                 {   /* fix null-terminated passwords (Android etc.) */
                     chunk.len -= 1;
                 }
                 attr2string(pass, sizeof(pass), chunk);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     if (!user[0] || !pass[0])
     {
         DBG1(DBG_IKE, "peer did not respond to our XAuth request");
         return FAILED;
     }
     this->peer->destroy(this->peer);
     this->peer = identification_create_from_string(user);
     /* Look for PAM service, with a legacy fallback for the eap-gtc plugin.
      * Default to "login". */
     service = lib->settings->get_str(lib->settings,
                 "%s.plugins.xauth-pam.pam_service",
                     lib->settings->get_str(lib->settings,
                         "%s.plugins.eap-gtc.pam_service", "login", lib->ns),
                 lib->ns);
     if (authenticate(service, user, pass))
     {
         DBG1(DBG_IKE, "PAM authentication of '%s' successful", user);
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (xauth_method_t , get_identity , identification_t * , private_xauth_pam_t * this)
Definition at line 194 of file xauth_pam.c.
 {
     return this->peer;
 }
METHOD (xauth_method_t , destroy , void , private_xauth_pam_t * this)
Definition at line 200 of file xauth_pam.c.
References free().
 {
     this->peer->destroy(this->peer);
     free(this);
 }