strongSwan: pkcs7_attributes
pkcs7_attributes
pkcs7
Classes
struct pkcs7_attributes_t
Typedefs
typedef struct pkcs7_attributes_t pkcs7_attributes_t
Functions
pkcs7_attributes_t * pkcs7_attributes_create_from_chunk (chunk_t chunk, u_int level)
pkcs7_attributes_t * pkcs7_attributes_create (void)
Detailed Description
Typedef Documentation
typedef struct pkcs7_attributes_t pkcs7_attributes_t
Definition at line 25 of file pkcs7_attributes.h.
Function Documentation
pkcs7_attributes_t* pkcs7_attributes_create (void)
Create an empty PKCS#7 attribute list, aka PKCS#9.
Returns
created pkcs9 attribute list.
Definition at line 187 of file pkcs7_attributes.c.
References INIT, and linked_list_create().
Referenced by pkcs7_attributes_create_from_chunk(), and pkcs7_signed_data_gen().
 {
     private_pkcs7_attributes_t *this;
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .get_attribute = _get_attribute,
             .add_attribute = _add_attribute,
             .destroy = _destroy,
         },
         .attributes = linked_list_create(),
     );
     return &this->public;
 }
pkcs7_attributes_t* pkcs7_attributes_create_from_chunk (chunk_t chunk, u_int level)
Read a PKCS#7 attribute list (aka PKCS#9) from a DER encoded chunk.
Parameters
chunk chunk containing DER encoded data
level ASN.1 parsing start level
Returns
created pkcs9 attribute list, or NULL if invalid.
Definition at line 260 of file pkcs7_attributes.c.
References chunk_clone, destroy(), encoding, parse_attributes(), and pkcs7_attributes_create().
Referenced by parse().
 {
     private_pkcs7_attributes_t *this;
     this = (private_pkcs7_attributes_t*)pkcs7_attributes_create();
     this->encoding = chunk_clone(chunk);
     if (!parse_attributes(chunk, level, this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }