strongSwan: pkcs11_hasher
pkcs11_hasher
pkcs11
Classes
struct pkcs11_hasher_t
Typedefs
typedef struct pkcs11_hasher_t pkcs11_hasher_t
Functions
pkcs11_hasher_t * pkcs11_hasher_create (hash_algorithm_t algo)
Detailed Description
Typedef Documentation
typedef struct pkcs11_hasher_t pkcs11_hasher_t
Definition at line 26 of file pkcs11_hasher.h.
Function Documentation
pkcs11_hasher_t* pkcs11_hasher_create (hash_algorithm_t algo)
Creates a PKCS#11 based hasher.
Parameters
algo hash algorithm
Returns
hasher, NULL if not supported
See header
Definition at line 309 of file pkcs11_hasher.c.
References mutex_t::destroy, find_token(), free(), INIT, lib, mutex, mutex_create(), MUTEX_TYPE_DEFAULT, and size.
Referenced by METHOD().
 {
     private_pkcs11_hasher_t *this;
     INIT(this,
         .public = {
             .hasher = {
                 .get_hash_size = _get_hash_size,
                 .reset = _reset,
                 .get_hash = _get_hash,
                 .allocate_hash = _allocate_hash,
                 .destroy = _destroy,
             },
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     this->lib = find_token(algo, &this->session, &this->mech, &this->size);
     if (!this->lib)
     {
         this->mutex->destroy(this->mutex);
         free(this);
         return NULL;
     }
     return &this->public;
 }