strongSwan: cred_encoding.c File Reference
cred_encoding.c File Reference
#include "cred_encoding.h"
#include <stdint.h>
#include <collections/linked_list.h>
#include <collections/hashtable.h>
#include <threading/rwlock.h>
Classes
struct private_cred_encoding_t
Typedefs
typedef struct
private_cred_encoding_t private_cred_encoding_t
Functions
bool cred_encoding_args (va_list args,...)
METHOD (cred_encoding_t, get_cache, bool, private_cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t *encoding)
static bool encode (private_cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t *encoding,...)
METHOD (cred_encoding_t, cache, void, private_cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t encoding)
METHOD (cred_encoding_t, clear_cache, void, private_cred_encoding_t *this, void *cache)
METHOD (cred_encoding_t, add_encoder, void, private_cred_encoding_t *this, cred_encoder_t encoder)
METHOD (cred_encoding_t, remove_encoder, void, private_cred_encoding_t *this, cred_encoder_t encoder)
METHOD (cred_encoding_t, destroy, void, private_cred_encoding_t *this)
cred_encoding_t * cred_encoding_create ()
Typedef Documentation
typedef struct private_cred_encoding_t private_cred_encoding_t
Definition at line 24 of file cred_encoding.c.
Function Documentation
static bool encode (private_cred_encoding_t * this, cred_encoding_type_t type, void * cache, chunk_t * encoding, ...) static
Implementation of cred_encoding_t.encode
Definition at line 120 of file cred_encoding.c.
References copy(), CRED_ENCODING_MAX, enumerator_t::destroy, encoding, enumerator_t::enumerate, FALSE, free(), lock, malloc_thing, chunk_t::ptr, TRUE, type, and spinlock_t::unlock.
Referenced by cred_encoding_create().
 {
     enumerator_t *enumerator;
     va_list args, copy;
     cred_encoder_t encode;
     bool success = FALSE;
     chunk_t *chunk;
     if (type >= CRED_ENCODING_MAX || (int)type < 0)
     {
         return FALSE;
     }
     this->lock->read_lock(this->lock);
     if (cache)
     {
         chunk = this->cache[type]->get(this->cache[type], cache);
         if (chunk)
         {
             *encoding = *chunk;
             this->lock->unlock(this->lock);
             return TRUE;
         }
     }
     va_start(args, encoding);
     enumerator = this->encoders->create_enumerator(this->encoders);
     while (enumerator->enumerate(enumerator, &encode))
     {
         va_copy(copy, args);
         success = encode(type, encoding, copy);
         va_end(copy);
         if (success)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     va_end(args);
     if (success && cache)
     {
         chunk = malloc_thing(chunk_t);
         *chunk = *encoding;
         this->lock->write_lock(this->lock);
         chunk = this->cache[type]->put(this->cache[type], cache, chunk);
         this->lock->unlock(this->lock);
         if (chunk)
         {
             free(chunk->ptr);
             free(chunk);
         }
     }
     return success;
 }
METHOD (cred_encoding_t , get_cache , bool , private_cred_encoding_t * this, cred_encoding_type_t type, void * cache, chunk_t * encoding)
Definition at line 97 of file cred_encoding.c.
References CRED_ENCODING_MAX, FALSE, lock, type, and spinlock_t::unlock.
 {
     chunk_t *chunk;
     if (type >= CRED_ENCODING_MAX || (int)type < 0)
     {
         return FALSE;
     }
     this->lock->read_lock(this->lock);
     chunk = this->cache[type]->get(this->cache[type], cache);
     if (chunk)
     {
         *encoding = *chunk;
     }
     this->lock->unlock(this->lock);
     return !!chunk;
 }
METHOD (cred_encoding_t , cache , void , private_cred_encoding_t * this, cred_encoding_type_t type, void * cache, chunk_t encoding)
Definition at line 176 of file cred_encoding.c.
References CRED_ENCODING_MAX, encoding, free(), lock, malloc_thing, chunk_t::ptr, type, and spinlock_t::unlock.
 {
     chunk_t *chunk;
     if (type >= CRED_ENCODING_MAX || (int)type < 0)
     {
         return free(encoding.ptr);
     }
     chunk = malloc_thing(chunk_t);
     *chunk = encoding;
     this->lock->write_lock(this->lock);
     chunk = this->cache[type]->put(this->cache[type], cache, chunk);
     this->lock->unlock(this->lock);
     /* free an encoding already associated to the cache */
     if (chunk)
     {
         free(chunk->ptr);
         free(chunk);
     }
 }
METHOD (cred_encoding_t , clear_cache , void , private_cred_encoding_t * this, void * cache)
Definition at line 199 of file cred_encoding.c.
References chunk_free(), CRED_ENCODING_MAX, free(), lock, type, and spinlock_t::unlock.
 {
     cred_encoding_type_t type;
     chunk_t *chunk;
     this->lock->write_lock(this->lock);
     for (type = 0; type < CRED_ENCODING_MAX; type++)
     {
         chunk = this->cache[type]->remove(this->cache[type], cache);
         if (chunk)
         {
             chunk_free(chunk);
             free(chunk);
         }
     }
     this->lock->unlock(this->lock);
 }
METHOD (cred_encoding_t , add_encoder , void , private_cred_encoding_t * this, cred_encoder_t encoder)
Definition at line 218 of file cred_encoding.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->encoders->insert_last(this->encoders, encoder);
     this->lock->unlock(this->lock);
 }
METHOD (cred_encoding_t , remove_encoder , void , private_cred_encoding_t * this, cred_encoder_t encoder)
Definition at line 226 of file cred_encoding.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->encoders->remove(this->encoders, encoder, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (cred_encoding_t , destroy , void , private_cred_encoding_t * this)
Definition at line 234 of file cred_encoding.c.
References cache(), CRED_ENCODING_MAX, spinlock_t::destroy, free(), lock, and type.
 {
     cred_encoding_type_t type;
     for (type = 0; type < CRED_ENCODING_MAX; type++)
     {
         /* We explicitly do not free remaining encodings. All creds should
          * have gone now, and they are responsible for cleaning out their
          * cache entries. Not flushing here allows the leak detective to
          * complain if a credential did not flush cached encodings. */
         this->cache[type]->destroy(this->cache[type]);
     }
     this->encoders->destroy(this->encoders);
     this->lock->destroy(this->lock);
     free(this);
 }