strongSwan: credential_manager.c File Reference
credential_manager.c File Reference
#include "credential_manager.h"
#include <library.h>
#include <utils/debug.h>
#include <threading/thread_value.h>
#include <threading/mutex.h>
#include <threading/rwlock.h>
#include <collections/linked_list.h>
#include <credentials/sets/cert_cache.h>
#include <credentials/sets/auth_cfg_wrapper.h>
#include <credentials/certificates/x509.h>
Classes
struct private_credential_manager_t
struct private_data_t
struct cert_data_t
struct cdp_data_t
struct shared_data_t
struct sets_enumerator_t
struct trusted_enumerator_t
struct public_enumerator_t
Macros
#define MAX_TRUST_PATH_LEN 7
Typedefs
typedef struct
private_credential_manager_t private_credential_manager_t
Functions
METHOD (credential_manager_t, set_hook, void, private_credential_manager_t *this, credential_hook_t hook, void *data)
METHOD (credential_manager_t, call_hook, void, private_credential_manager_t *this, credential_hook_type_t type, certificate_t *cert)
METHOD (enumerator_t, sets_enumerate, bool, sets_enumerator_t *this, credential_set_t **set)
METHOD (enumerator_t, sets_destroy, void, sets_enumerator_t *this)
static enumerator_t * create_sets_enumerator (private_credential_manager_t *this)
static void destroy_cert_data (cert_data_t *data)
static enumerator_t * create_cert (credential_set_t *set, cert_data_t *data)
METHOD (credential_manager_t, create_cert_enumerator, enumerator_t *, private_credential_manager_t *this, certificate_type_t certificate, key_type_t key, identification_t *id, bool trusted)
METHOD (credential_manager_t, get_cert, certificate_t *, private_credential_manager_t *this, certificate_type_t cert, key_type_t key, identification_t *id, bool trusted)
static void destroy_cdp_data (cdp_data_t *data)
static enumerator_t * create_cdp (credential_set_t *set, cdp_data_t *data)
METHOD (credential_manager_t, create_cdp_enumerator, enumerator_t *, private_credential_manager_t *this, certificate_type_t type, identification_t *id)
static void destroy_private_data (private_data_t *data)
static enumerator_t * create_private (credential_set_t *set, private_data_t *data)
static enumerator_t * create_private_enumerator (private_credential_manager_t *this, key_type_t key, identification_t *keyid)
static private_key_t * get_private_by_keyid (private_credential_manager_t *this, key_type_t key, identification_t *keyid)
static void destroy_shared_data (shared_data_t *data)
static enumerator_t * create_shared (credential_set_t *set, shared_data_t *data)
METHOD (credential_manager_t, create_shared_enumerator, enumerator_t *, private_credential_manager_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
METHOD (credential_manager_t, get_shared, shared_key_t *, private_credential_manager_t *this, shared_key_type_t type, identification_t *me, identification_t *other)
METHOD (credential_manager_t, add_local_set, void, private_credential_manager_t *this, credential_set_t *set, bool exclusive)
METHOD (credential_manager_t, remove_local_set, void, private_credential_manager_t *this, credential_set_t *set)
METHOD (credential_manager_t, issued_by, bool, private_credential_manager_t *this, certificate_t *subject, certificate_t *issuer, signature_scheme_t *scheme)
METHOD (credential_manager_t, cache_cert, void, private_credential_manager_t *this, certificate_t *cert)
static void cache_queue (private_credential_manager_t *this)
static bool check_lifetime (private_credential_manager_t *this, certificate_t *cert, char *label, int pathlen, bool trusted, auth_cfg_t *auth)
static bool check_certificate (private_credential_manager_t *this, certificate_t *subject, certificate_t *issuer, bool online, int pathlen, bool trusted, auth_cfg_t *auth)
static certificate_t * get_pretrusted_cert (private_credential_manager_t *this, key_type_t type, identification_t *id)
static certificate_t * get_issuer_cert (private_credential_manager_t *this, certificate_t *subject, bool trusted, signature_scheme_t *scheme)
static void get_key_strength (certificate_t *cert, auth_cfg_t *auth)
static bool verify_trust_chain (private_credential_manager_t *this, certificate_t *subject, auth_cfg_t *result, bool trusted, bool online)
static bool cert_equals (certificate_t *a, certificate_t *b)
METHOD (enumerator_t, trusted_enumerate, bool, trusted_enumerator_t *this, certificate_t **cert, auth_cfg_t **auth)
METHOD (enumerator_t, trusted_destroy, void, trusted_enumerator_t *this)
METHOD (credential_manager_t, create_trusted_enumerator, enumerator_t *, private_credential_manager_t *this, key_type_t type, identification_t *id, bool online)
METHOD (enumerator_t, public_enumerate, bool, public_enumerator_t *this, public_key_t **key, auth_cfg_t **auth)
METHOD (enumerator_t, public_destroy, void, public_enumerator_t *this)
METHOD (credential_manager_t, create_public_enumerator, enumerator_t *, private_credential_manager_t *this, key_type_t type, identification_t *id, auth_cfg_t *auth)
static bool auth_contains_cacert (auth_cfg_t *auth, certificate_t *cert)
static auth_cfg_t * build_trustchain (private_credential_manager_t *this, certificate_t *subject, auth_cfg_t *auth)
static private_key_t * get_private_by_cert (private_credential_manager_t *this, certificate_t *cert, key_type_t type)
static void prefer_cert (auth_cfg_t *auth, certificate_t *cert)
METHOD (credential_manager_t, get_private, private_key_t *, private_credential_manager_t *this, key_type_t type, identification_t *id, auth_cfg_t *auth)
METHOD (credential_manager_t, flush_cache, void, private_credential_manager_t *this, certificate_type_t type)
METHOD (credential_manager_t, add_set, void, private_credential_manager_t *this, credential_set_t *set)
METHOD (credential_manager_t, remove_set, void, private_credential_manager_t *this, credential_set_t *set)
METHOD (credential_manager_t, add_validator, void, private_credential_manager_t *this, cert_validator_t *vdtr)
METHOD (credential_manager_t, remove_validator, void, private_credential_manager_t *this, cert_validator_t *vdtr)
METHOD (credential_manager_t, destroy, void, private_credential_manager_t *this)
credential_manager_t * credential_manager_create ()
Macro Definition Documentation
#define MAX_TRUST_PATH_LEN 7
Maximum length of a certificate trust chain
Definition at line 31 of file credential_manager.c.
Referenced by build_trustchain(), and verify_trust_chain().
Typedef Documentation
typedef struct private_credential_manager_t private_credential_manager_t
Definition at line 33 of file credential_manager.c.
Function Documentation
static bool auth_contains_cacert (auth_cfg_t * auth, certificate_t * cert) static
Check if a helper contains a certificate as trust anchor
Definition at line 1020 of file credential_manager.c.
References AUTH_RULE_CA_CERT, auth_cfg_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, certificate_t::equals, FALSE, found, TRUE, type, and value.
Referenced by build_trustchain().
 {
     enumerator_t *enumerator;
     identification_t *value;
     auth_rule_t type;
     bool found = FALSE;
     enumerator = auth->create_enumerator(auth);
     while (enumerator->enumerate(enumerator, &type, &value))
     {
         if (type == AUTH_RULE_CA_CERT &&
             cert->equals(cert, (certificate_t*)value))
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static auth_cfg_t* build_trustchain (private_credential_manager_t * this, certificate_t * subject, auth_cfg_t * auth) static
build a trustchain from subject up to a trust anchor in trusted
Definition at line 1044 of file credential_manager.c.
References auth_cfg_t::add, auth_cfg_create(), auth_contains_cacert(), AUTH_RULE_CA_CERT, AUTH_RULE_IM_CERT, AUTH_RULE_SUBJECT_CERT, certificate_t::destroy, auth_cfg_t::destroy, certificate_t::equals, FALSE, auth_cfg_t::get, get_issuer_cert(), certificate_t::get_ref, MAX_TRUST_PATH_LEN, and TRUE.
Referenced by METHOD().
 {
     certificate_t *issuer, *current;
     auth_cfg_t *trustchain;
     int pathlen = 0;
     bool has_anchor;
     trustchain = auth_cfg_create();
     has_anchor = auth->get(auth, AUTH_RULE_CA_CERT) != NULL;
     current = subject->get_ref(subject);
     while (TRUE)
     {
         if (auth_contains_cacert(auth, current))
         {
             trustchain->add(trustchain, AUTH_RULE_CA_CERT, current);
             return trustchain;
         }
         if (subject == current)
         {
             trustchain->add(trustchain, AUTH_RULE_SUBJECT_CERT, current);
         }
         else
         {
             if (!has_anchor && issued_by(this, current, current, NULL))
             {   /* If no trust anchor specified, accept any CA */
                 trustchain->add(trustchain, AUTH_RULE_CA_CERT, current);
                 return trustchain;
             }
             trustchain->add(trustchain, AUTH_RULE_IM_CERT, current);
         }
         if (pathlen++ > MAX_TRUST_PATH_LEN)
         {
             break;
         }
         issuer = get_issuer_cert(this, current, FALSE, NULL);
         if (!issuer)
         {
             if (!has_anchor)
             {   /* If no trust anchor specified, accept incomplete chains */
                 return trustchain;
             }
             break;
         }
         if (has_anchor && issuer->equals(issuer, current))
         {
             issuer->destroy(issuer);
             break;
         }
         current = issuer;
     }
     trustchain->destroy(trustchain);
     return NULL;
 }
static void cache_queue (private_credential_manager_t * this) static
Try to cache certificates queued for caching
Definition at line 521 of file credential_manager.c.
References credential_set_t::cache_cert, cert, enumerator_t::destroy, certificate_t::destroy, enumerator_t::enumerate, lock, SUCCESS, and spinlock_t::unlock.
Referenced by METHOD().
 {
     credential_set_t *set;
     certificate_t *cert;
     enumerator_t *enumerator;
     this->queue_mutex->lock(this->queue_mutex);
     if (this->cache_queue->get_count(this->cache_queue) > 0 &&
         this->lock->try_write_lock(this->lock))
     {
         while (this->cache_queue->remove_last(this->cache_queue,
                                               (void**)&cert) == SUCCESS)
         {
             enumerator = this->sets->create_enumerator(this->sets);
             while (enumerator->enumerate(enumerator, &set))
             {
                 set->cache_cert(set, cert);
             }
             enumerator->destroy(enumerator);
             cert->destroy(cert);
         }
         this->lock->unlock(this->lock);
     }
     this->queue_mutex->unlock(this->queue_mutex);
 }
static bool cert_equals (certificate_t * a, certificate_t * b) static
List find match function for certificates
Definition at line 812 of file credential_manager.c.
References certificate_t::equals.
Referenced by METHOD().
 {
     return a->equals(a, b);
 }
static bool check_certificate (private_credential_manager_t * this, certificate_t * subject, certificate_t * issuer, bool online, int pathlen, bool trusted, auth_cfg_t * auth) static
check a certificate for its lifetime
Definition at line 598 of file credential_manager.c.
References check_lifetime(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, TRUE, and cert_validator_t::validate.
Referenced by verify_trust_chain().
 {
     cert_validator_t *validator;
     enumerator_t *enumerator;
     if (!check_lifetime(this, subject, "subject", pathlen, FALSE, auth) ||
         !check_lifetime(this, issuer, "issuer", pathlen + 1, trusted, auth))
     {
         return FALSE;
     }
     enumerator = this->validators->create_enumerator(this->validators);
     while (enumerator->enumerate(enumerator, &validator))
     {
         if (!validator->validate)
         {
             continue;
         }
         if (!validator->validate(validator, subject, issuer,
                                  online, pathlen, trusted, auth))
         {
             enumerator->destroy(enumerator);
             return FALSE;
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 }
static bool check_lifetime (private_credential_manager_t * this, certificate_t * cert, char * label, int pathlen, bool trusted, auth_cfg_t * auth) static
Use validators to check the lifetime of certificates
Definition at line 550 of file credential_manager.c.
References call_hook(), cert_validator_t::check_lifetime, CRED_HOOK_EXPIRED, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FAILED, FALSE, certificate_t::get_validity, NEED_MORE, status, SUCCESS, and TRUE.
Referenced by check_certificate().
 {
     time_t not_before, not_after;
     cert_validator_t *validator;
     enumerator_t *enumerator;
     status_t status = NEED_MORE;
     enumerator = this->validators->create_enumerator(this->validators);
     while (enumerator->enumerate(enumerator, &validator))
     {
         if (!validator->check_lifetime)
         {
             continue;
         }
         status = validator->check_lifetime(validator, cert,
                                            pathlen, trusted, auth);
         if (status != NEED_MORE)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     switch (status)
     {
         case NEED_MORE:
             if (!cert->get_validity(cert, NULL, &not_before, &not_after))
             {
                 DBG1(DBG_CFG, "%s certificate invalid (valid from %T to %T)",
                      label, &not_before, FALSE, &not_after, FALSE);
                 break;
             }
             return TRUE;
         case SUCCESS:
             return TRUE;
         case FAILED:
         default:
             break;
     }
     call_hook(this, CRED_HOOK_EXPIRED, cert);
     return FALSE;
 }
static enumerator_t* create_cdp (credential_set_t * set, cdp_data_t * data) static
enumerator constructor for CDPs
Definition at line 291 of file credential_manager.c.
References credential_set_t::create_cdp_enumerator, cdp_data_t::id, and cdp_data_t::type.
Referenced by METHOD().
 {
     return set->create_cdp_enumerator(set, data->type, data->id);
 }
static enumerator_t* create_cert (credential_set_t * set, cert_data_t * data) static
enumerator constructor for certificates
Definition at line 238 of file credential_manager.c.
References cert_data_t::cert, credential_set_t::create_cert_enumerator, cert_data_t::id, cert_data_t::key, and cert_data_t::trusted.
Referenced by METHOD().
 {
     return set->create_cert_enumerator(set, data->cert, data->key,
                                        data->id, data->trusted);
 }
static enumerator_t* create_private (credential_set_t * set, private_data_t * data) static
enumerator constructor for private keys
Definition at line 325 of file credential_manager.c.
References credential_set_t::create_private_enumerator, private_data_t::keyid, and private_data_t::type.
Referenced by create_private_enumerator().
 {
     return set->create_private_enumerator(set, data->type, data->keyid);
 }
static enumerator_t* create_private_enumerator (private_credential_manager_t * this, key_type_t key, identification_t * keyid) static
Create an enumerator over private keys
Definition at line 333 of file credential_manager.c.
References create_private(), create_sets_enumerator(), data, destroy_private_data(), enumerator_create_nested(), INIT, lock, and type.
Referenced by create_generic(), get_private_by_keyid(), pkcs11_creds_create(), and tkm_cred_create().
 {
     private_data_t *data;
     INIT(data,
         .this = this,
         .type = key,
         .keyid = keyid,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(create_sets_enumerator(this),
                                     (void*)create_private, data,
                                     (void*)destroy_private_data);
 }
static enumerator_t* create_sets_enumerator (private_credential_manager_t * this) static
create an enumerator over both, global and local sets
Definition at line 197 of file credential_manager.c.
References linked_list_t::create_enumerator, destroy(), sets_enumerator_t::exclusive, linked_list_t::get_count, sets_enumerator_t::global, INIT, list, sets_enumerator_t::local, and sets_enumerator_t::public.
Referenced by create_private_enumerator(), and METHOD().
 {
     sets_enumerator_t *enumerator;
     linked_list_t *list;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_sets_enumerate,
             .destroy = _sets_destroy,
         },
     );
     list = this->exclusive_local_sets->get(this->exclusive_local_sets);
     if (list && list->get_count(list))
     {
         enumerator->exclusive = list->create_enumerator(list);
     }
     else
     {
         enumerator->global = this->sets->create_enumerator(this->sets);
         list = this->local_sets->get(this->local_sets);
         if (list)
         {
             enumerator->local = list->create_enumerator(list);
         }
     }
     return &enumerator->public;
 }
static enumerator_t* create_shared (credential_set_t * set, shared_data_t * data) static
enumerator constructor for shared keys
Definition at line 379 of file credential_manager.c.
References credential_set_t::create_shared_enumerator, shared_data_t::me, shared_data_t::other, and shared_data_t::type.
Referenced by METHOD().
 {
     return set->create_shared_enumerator(set, data->type, data->me, data->other);
 }
static void destroy_cdp_data (cdp_data_t * data) static
cleanup function for cdp data
Definition at line 282 of file credential_manager.c.
References free(), private_stroke_ca_t::lock, cdp_data_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static void destroy_cert_data (cert_data_t * data) static
cleanup function for cert data
Definition at line 229 of file credential_manager.c.
References free(), private_nm_creds_t::lock, cert_data_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static void destroy_private_data (private_data_t * data) static
cleanup function for private data
Definition at line 316 of file credential_manager.c.
References free(), private_credential_manager_t::lock, private_data_t::this, and rwlock_t::unlock.
Referenced by create_private_enumerator().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static void destroy_shared_data (shared_data_t * data) static
cleanup function for shared data
Definition at line 370 of file credential_manager.c.
References free(), private_credential_manager_t::lock, shared_data_t::this, and rwlock_t::unlock.
Referenced by METHOD().
 {
     data->this->lock->unlock(data->this->lock);
     free(data);
 }
static certificate_t* get_issuer_cert (private_credential_manager_t * this, certificate_t * subject, bool trusted, signature_scheme_t * scheme) static
Get the issuing certificate of a subject certificate
Definition at line 656 of file credential_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, certificate_t::get_issuer, certificate_t::get_ref, certificate_t::get_type, and KEY_ANY.
Referenced by build_trustchain(), and verify_trust_chain().
 {
     enumerator_t *enumerator;
     certificate_t *issuer = NULL, *candidate;
     enumerator = create_cert_enumerator(this, subject->get_type(subject), KEY_ANY,
                                         subject->get_issuer(subject), trusted);
     while (enumerator->enumerate(enumerator, &candidate))
     {
         if (issued_by(this, subject, candidate, scheme))
         {
             issuer = candidate->get_ref(candidate);
             break;
         }
     }
     enumerator->destroy(enumerator);
     return issuer;
 }
static void get_key_strength (certificate_t * cert, auth_cfg_t * auth) static
Get the strength of certificate, add it to auth
Definition at line 680 of file credential_manager.c.
References auth_cfg_t::add, AUTH_RULE_BLISS_STRENGTH, AUTH_RULE_ECDSA_STRENGTH, AUTH_RULE_RSA_STRENGTH, DBG2, DBG_CFG, public_key_t::destroy, public_key_t::get_keysize, certificate_t::get_public_key, certificate_t::get_subject, public_key_t::get_type, key, KEY_BLISS, KEY_ECDSA, KEY_RSA, key_type_names, and type.
Referenced by verify_trust_chain().
 {
     uintptr_t strength;
     public_key_t *key;
     key_type_t type;
     key = cert->get_public_key(cert);
     if (key)
     {
         type = key->get_type(key);
         strength = key->get_keysize(key);
         DBG2(DBG_CFG, "  certificate \"%Y\" key: %d bit %N",
              cert->get_subject(cert), strength, key_type_names, type);
         switch (type)
         {
             case KEY_RSA:
                 auth->add(auth, AUTH_RULE_RSA_STRENGTH, strength);
                 break;
             case KEY_ECDSA:
                 auth->add(auth, AUTH_RULE_ECDSA_STRENGTH, strength);
                 break;
             case KEY_BLISS:
                 auth->add(auth, AUTH_RULE_BLISS_STRENGTH, strength);
                 break;
             default:
                 break;
         }
         key->destroy(key);
     }
 }
static certificate_t* get_pretrusted_cert (private_credential_manager_t * this, key_type_t type, identification_t * id) static
Get a trusted certificate from a credential set
Definition at line 632 of file credential_manager.c.
References CERT_ANY, certificate_t::destroy, certificate_t::get_public_key, subject, and TRUE.
Referenced by METHOD().
 {
     certificate_t *subject;
     public_key_t *public;
     subject = get_cert(this, CERT_ANY, type, id, TRUE);
     if (!subject)
     {
         return NULL;
     }
     public = subject->get_public_key(subject);
     if (!public)
     {
         subject->destroy(subject);
         return NULL;
     }
     public->destroy(public);
     return subject;
 }
static private_key_t* get_private_by_cert (private_credential_manager_t * this, certificate_t * cert, key_type_t type) static
find a private key of a given certificate
Definition at line 1102 of file credential_manager.c.
References identification_t::destroy, get_private_by_keyid(), certificate_t::get_public_key, ID_KEY_ID, identification_create_from_encoding(), keyid(), KEYID_PUBKEY_SHA1, and public.
Referenced by METHOD().
 {
     private_key_t *private = NULL;
     identification_t *keyid;
     chunk_t chunk;
     public_key_t *public;
     public = cert->get_public_key(cert);
     if (public)
     {
         if (public->get_fingerprint(public, KEYID_PUBKEY_SHA1, &chunk))
         {
             keyid = identification_create_from_encoding(ID_KEY_ID, chunk);
             private = get_private_by_keyid(this, type, keyid);
             keyid->destroy(keyid);
         }
         public->destroy(public);
     }
     return private;
 }
static private_key_t* get_private_by_keyid (private_credential_manager_t * this, key_type_t key, identification_t * keyid) static
Look up a private key by its key identifier
Definition at line 352 of file credential_manager.c.
References create_private_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, found, and private_key_t::get_ref.
Referenced by get_private_by_cert(), and METHOD().
 {
     private_key_t *found = NULL;
     enumerator_t *enumerator;
     enumerator = create_private_enumerator(this, key, keyid);
     if (enumerator->enumerate(enumerator, &found))
     {
         found->get_ref(found);
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (credential_manager_t , set_hook , void , private_credential_manager_t * this, credential_hook_t hook, void * data)
Definition at line 139 of file credential_manager.c.
References data.
 {
     this->hook = hook;
     this->hook_data = data;
 }
METHOD (credential_manager_t , call_hook , void , private_credential_manager_t * this, credential_hook_type_t type, certificate_t * cert)
Definition at line 146 of file credential_manager.c.
 {
     if (this->hook)
     {
         this->hook(this->hook_data, type, cert);
     }
 }
METHOD (enumerator_t , sets_enumerate , bool , sets_enumerator_t * this, credential_set_t ** set)
Definition at line 156 of file credential_manager.c.
References FALSE, and TRUE.
 {
     if (this->exclusive)
     {
         if (this->exclusive->enumerate(this->exclusive, set))
         {   /* only enumerate last added */
             this->exclusive->destroy(this->exclusive);
             this->exclusive = NULL;
             return TRUE;
         }
     }
     if (this->global)
     {
         if (this->global->enumerate(this->global, set))
         {
             return TRUE;
         }
         /* end of global sets, look for local */
         this->global->destroy(this->global);
         this->global = NULL;
     }
     if (this->local)
     {
         return this->local->enumerate(this->local, set);
     }
     return FALSE;
 }
METHOD (enumerator_t , sets_destroy , void , sets_enumerator_t * this)
Definition at line 185 of file credential_manager.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->global);
     DESTROY_IF(this->local);
     DESTROY_IF(this->exclusive);
     free(this);
 }
METHOD (credential_manager_t , create_cert_enumerator , enumerator_t * , private_credential_manager_t * this, certificate_type_t certificate, key_type_t key, identification_t * id, bool trusted)
Definition at line 244 of file credential_manager.c.
References cert_data_t::cert, create_cert(), create_sets_enumerator(), data, destroy_cert_data(), enumerator_create_nested(), id, cert_data_t::id, cert_data_t::key, key, lock, malloc_thing, cert_data_t::this, and cert_data_t::trusted.
 {
     cert_data_t *data = malloc_thing(cert_data_t);
     data->this = this;
     data->cert = certificate;
     data->key = key;
     data->id = id;
     data->trusted = trusted;
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(create_sets_enumerator(this),
                                     (void*)create_cert, data,
                                     (void*)destroy_cert_data);
 }
METHOD (credential_manager_t , get_cert , certificate_t * , private_credential_manager_t * this, certificate_type_t cert, key_type_t key, identification_t * id, bool trusted)
Definition at line 261 of file credential_manager.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, and certificate_t::get_ref.
 {
     certificate_t *current, *found = NULL;
     enumerator_t *enumerator;
     enumerator = create_cert_enumerator(this, cert, key, id, trusted);
     if (enumerator->enumerate(enumerator, &current))
     {
         /* TODO: best match? order by keyid, subject, sualtname */
         found = current->get_ref(current);
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (credential_manager_t , create_cdp_enumerator , enumerator_t * , private_credential_manager_t * this, certificate_type_t type, identification_t * id)
Definition at line 296 of file credential_manager.c.
References create_cdp(), create_sets_enumerator(), data, destroy_cdp_data(), enumerator_create_nested(), INIT, and lock.
 {
     cdp_data_t *data;
     INIT(data,
         .this = this,
         .type = type,
         .id = id,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(create_sets_enumerator(this),
                                     (void*)create_cdp, data,
                                     (void*)destroy_cdp_data);
 }
METHOD (credential_manager_t , create_shared_enumerator , enumerator_t * , private_credential_manager_t * this, shared_key_type_t type, identification_t * me, identification_t * other)
Definition at line 384 of file credential_manager.c.
References create_sets_enumerator(), create_shared(), data, destroy_shared_data(), enumerator_create_nested(), INIT, and lock.
 {
     shared_data_t *data;
     INIT(data,
         .this = this,
         .type = type,
         .me = me,
         .other = other,
     );
     this->lock->read_lock(this->lock);
     return enumerator_create_nested(create_sets_enumerator(this),
                                     (void*)create_shared, data,
                                     (void*)destroy_shared_data);
 }
METHOD (credential_manager_t , get_shared , shared_key_t * , private_credential_manager_t * this, shared_key_type_t type, identification_t * me, identification_t * other)
Definition at line 402 of file credential_manager.c.
References enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, found, shared_key_t::get_ref, ID_MATCH_NONE, and ID_MATCH_PERFECT.
 {
     shared_key_t *current, *found = NULL;
     id_match_t best_me = ID_MATCH_NONE, best_other = ID_MATCH_NONE;
     id_match_t match_me, match_other;
     enumerator_t *enumerator;
     enumerator = create_shared_enumerator(this, type, me, other);
     while (enumerator->enumerate(enumerator, &current, &match_me, &match_other))
     {
         if (match_other > best_other ||
             (match_other == best_other && match_me > best_me))
         {
             DESTROY_IF(found);
             found = current->get_ref(current);
             best_me = match_me;
             best_other = match_other;
         }
         if (best_me == ID_MATCH_PERFECT && best_other == ID_MATCH_PERFECT)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (credential_manager_t , add_local_set , void , private_credential_manager_t * this, credential_set_t * set, bool exclusive)
Definition at line 431 of file credential_manager.c.
References thread_value_t::get, linked_list_t::insert_first, linked_list_t::insert_last, linked_list_create(), and thread_value_t::set.
 {
     linked_list_t *sets;
     thread_value_t *tv;
     if (exclusive)
     {
         tv = this->exclusive_local_sets;
     }
     else
     {
         tv = this->local_sets;
     }
     sets = tv->get(tv);
     if (!sets)
     {
         sets = linked_list_create();
         tv->set(tv, sets);
     }
     if (exclusive)
     {
         sets->insert_first(sets, set);
     }
     else
     {
         sets->insert_last(sets, set);
     }
 }
METHOD (credential_manager_t , remove_local_set , void , private_credential_manager_t * this, credential_set_t * set)
Definition at line 461 of file credential_manager.c.
References linked_list_t::destroy, thread_value_t::get, linked_list_t::get_count, linked_list_t::remove, and thread_value_t::set.
 {
     linked_list_t *sets;
     thread_value_t *tv;
     tv = this->local_sets;
     sets = tv->get(tv);
     if (sets && sets->remove(sets, set, NULL) && sets->get_count(sets) == 0)
     {
         tv->set(tv, NULL);
         sets->destroy(sets);
     }
     tv = this->exclusive_local_sets;
     sets = tv->get(tv);
     if (sets && sets->remove(sets, set, NULL) && sets->get_count(sets) == 0)
     {
         tv->set(tv, NULL);
         sets->destroy(sets);
     }
 }
METHOD (credential_manager_t , issued_by , bool , private_credential_manager_t * this, certificate_t * subject, certificate_t * issuer, signature_scheme_t * scheme)
Definition at line 483 of file credential_manager.c.
References cache(), and certificate_t::issued_by.
 {
     if (this->cache)
     {
         return this->cache->issued_by(this->cache, subject, issuer, scheme);
     }
     return subject->issued_by(subject, issuer, scheme);
 }
METHOD (credential_manager_t , cache_cert , void , private_credential_manager_t * this, certificate_t * cert)
Definition at line 494 of file credential_manager.c.
References credential_set_t::cache_cert, cache_queue(), enumerator_t::destroy, enumerator_t::enumerate, certificate_t::get_ref, lock, and spinlock_t::unlock.
 {
     credential_set_t *set;
     enumerator_t *enumerator;
     if (this->lock->try_write_lock(this->lock))
     {
         enumerator = this->sets->create_enumerator(this->sets);
         while (enumerator->enumerate(enumerator, &set))
         {
             set->cache_cert(set, cert);
         }
         enumerator->destroy(enumerator);
         this->lock->unlock(this->lock);
     }
     else
     {   /* we can't cache now as other threads are active, queue for later */
         this->queue_mutex->lock(this->queue_mutex);
         this->cache_queue->insert_last(this->cache_queue, cert->get_ref(cert));
         this->queue_mutex->unlock(this->queue_mutex);
     }
 }
METHOD (enumerator_t , trusted_enumerate , bool , trusted_enumerator_t * this, certificate_t ** cert, auth_cfg_t ** auth)
Definition at line 841 of file credential_manager.c.
References auth_cfg_t::add, auth_cfg_create(), AUTH_RULE_SUBJECT_CERT, CERT_ANY, cert_equals(), DBG1, DBG_CFG, DESTROY_IF, FALSE, auth_cfg_t::get, get_pretrusted_cert(), certificate_t::get_ref, certificate_t::get_subject, SUCCESS, TRUE, type, and verify_trust_chain().
 {
     certificate_t *current;
     DESTROY_IF(this->auth);
     this->auth = auth_cfg_create();
     if (!this->candidates)
     {
         /* first invocation, build enumerator for next one */
         this->candidates = create_cert_enumerator(this->this, CERT_ANY,
                                                   this->type, this->id, FALSE);
         /* check if we have a trusted certificate for that peer */
         this->pretrusted = get_pretrusted_cert(this->this, this->type, this->id);
         if (this->pretrusted)
         {
             /* if we find a trusted self signed certificate, we just accept it.
              * However, in order to fulfill authorization rules, we try to build
              * the trust chain if it is not self signed */
             if (issued_by(this->this, this->pretrusted, this->pretrusted, NULL) ||
                 verify_trust_chain(this->this, this->pretrusted, this->auth,
                                    TRUE, this->online))
             {
                 DBG1(DBG_CFG, "  using trusted certificate \"%Y\"",
                      this->pretrusted->get_subject(this->pretrusted));
                 *cert = this->pretrusted;
                 if (!this->auth->get(this->auth, AUTH_RULE_SUBJECT_CERT))
                 {   /* add cert to auth info, if not returned by trustchain */
                     this->auth->add(this->auth, AUTH_RULE_SUBJECT_CERT,
                                     this->pretrusted->get_ref(this->pretrusted));
                 }
                 if (auth)
                 {
                     *auth = this->auth;
                 }
                 return TRUE;
             }
         }
     }
     /* try to verify the trust chain for each certificate found */
     while (this->candidates->enumerate(this->candidates, &current))
     {
         if (this->pretrusted &&
             this->pretrusted->equals(this->pretrusted, current))
         {   /* skip pretrusted certificate we already served */
             continue;
         }
         if (this->failed->find_first(this->failed, (void*)cert_equals,
                                      NULL, current) == SUCCESS)
         {   /* check each candidate only once */
             continue;
         }
         DBG1(DBG_CFG, "  using certificate \"%Y\"",
              current->get_subject(current));
         if (verify_trust_chain(this->this, current, this->auth, FALSE,
                                this->online))
         {
             *cert = current;
             if (auth)
             {
                 *auth = this->auth;
             }
             return TRUE;
         }
         this->failed->insert_last(this->failed, current->get_ref(current));
     }
     return FALSE;
 }
METHOD (enumerator_t , trusted_destroy , void , trusted_enumerator_t * this)
Definition at line 913 of file credential_manager.c.
References destroy(), DESTROY_IF, and free().
 {
     DESTROY_IF(this->pretrusted);
     DESTROY_IF(this->auth);
     DESTROY_IF(this->candidates);
     this->failed->destroy_offset(this->failed, offsetof(certificate_t, destroy));
     free(this);
 }
METHOD (credential_manager_t , create_trusted_enumerator , enumerator_t * , private_credential_manager_t * this, key_type_t type, identification_t * id, bool online)
Definition at line 923 of file credential_manager.c.
References destroy(), INIT, linked_list_create(), and trusted_enumerator_t::public.
 {
     trusted_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_trusted_enumerate,
             .destroy = _trusted_destroy,
         },
         .this = this,
         .type = type,
         .id = id,
         .online = online,
         .failed = linked_list_create(),
     );
     return &enumerator->public;
 }
METHOD (enumerator_t , public_enumerate , bool , public_enumerator_t * this, public_key_t ** key, auth_cfg_t ** auth)
Definition at line 959 of file credential_manager.c.
References cert, DESTROY_IF, FALSE, certificate_t::get_public_key, and TRUE.
 {
     certificate_t *cert;
     while (this->inner->enumerate(this->inner, &cert, auth))
     {
         DESTROY_IF(this->current);
         this->current = cert->get_public_key(cert);
         if (this->current)
         {
             *key = this->current;
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (enumerator_t , public_destroy , void , public_enumerator_t * this)
Definition at line 977 of file credential_manager.c.
References cache_queue(), DESTROY_IF, free(), lock, and spinlock_t::unlock.
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     if (this->wrapper)
     {
         remove_local_set(this->this, &this->wrapper->set);
         this->wrapper->destroy(this->wrapper);
     }
     this->this->lock->unlock(this->this->lock);
     /* check for delayed certificate cache queue */
     cache_queue(this->this);
     free(this);
 }
METHOD (credential_manager_t , create_public_enumerator , enumerator_t * , private_credential_manager_t * this, key_type_t type, identification_t * id, auth_cfg_t * auth)
Definition at line 994 of file credential_manager.c.
References auth_cfg_wrapper_create(), destroy(), FALSE, INIT, lock, public_enumerator_t::public, auth_cfg_wrapper_t::set, TRUE, and public_enumerator_t::wrapper.
 {
     public_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_public_enumerate,
             .destroy = _public_destroy,
         },
         .inner = create_trusted_enumerator(this, type, id, TRUE),
         .this = this,
     );
     if (auth)
     {
         enumerator->wrapper = auth_cfg_wrapper_create(auth);
         add_local_set(this, &enumerator->wrapper->set, FALSE);
     }
     this->lock->read_lock(this->lock);
     return &enumerator->public;
 }
METHOD (credential_manager_t , get_private , private_key_t * , private_credential_manager_t * this, key_type_t type, identification_t * id, auth_cfg_t * auth)
Definition at line 1147 of file credential_manager.c.
References auth_cfg_t::add, AUTH_RULE_SUBJECT_CERT, build_trustchain(), cert, CERT_ANY, auth_cfg_t::create_enumerator, enumerator_t::destroy, auth_cfg_t::destroy, enumerator_t::enumerate, FALSE, auth_cfg_t::get, get_private_by_cert(), get_private_by_keyid(), certificate_t::get_ref, identification_t::get_type, ID_KEY_ID, auth_cfg_t::merge, and prefer_cert().
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     private_key_t *private = NULL;
     auth_cfg_t *trustchain;
     auth_rule_t rule;
     /* check if this is a lookup by key ID, and do it if so */
     if (id && id->get_type(id) == ID_KEY_ID)
     {
         private = get_private_by_keyid(this, type, id);
         if (private)
         {
             return private;
         }
     }
     if (auth)
     {
         /* try to find a trustchain with one of the configured subject certs */
         enumerator = auth->create_enumerator(auth);
         while (enumerator->enumerate(enumerator, &rule, &cert))
         {
             if (rule == AUTH_RULE_SUBJECT_CERT)
             {
                 private = get_private_by_cert(this, cert, type);
                 if (private)
                 {
                     trustchain = build_trustchain(this, cert, auth);
                     if (trustchain)
                     {
                         auth->merge(auth, trustchain, FALSE);
                         prefer_cert(auth, cert->get_ref(cert));
                         trustchain->destroy(trustchain);
                         break;
                     }
                     private->destroy(private);
                     private = NULL;
                 }
             }
         }
         enumerator->destroy(enumerator);
         if (private)
         {
             return private;
         }
         /* if none yielded a trustchain, enforce the first configured cert */
         cert = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
         if (cert)
         {
             private = get_private_by_cert(this, cert, type);
             if (private)
             {
                 trustchain = build_trustchain(this, cert, auth);
                 if (trustchain)
                 {
                     auth->merge(auth, trustchain, FALSE);
                     trustchain->destroy(trustchain);
                 }
                 return private;
             }
         }
         /* try to build a trust chain for each certificate found */
         enumerator = create_cert_enumerator(this, CERT_ANY, type, id, FALSE);
         while (enumerator->enumerate(enumerator, &cert))
         {
             private = get_private_by_cert(this, cert, type);
             if (private)
             {
                 trustchain = build_trustchain(this, cert, auth);
                 if (trustchain)
                 {
                     auth->merge(auth, trustchain, FALSE);
                     trustchain->destroy(trustchain);
                     break;
                 }
                 private->destroy(private);
                 private = NULL;
             }
         }
         enumerator->destroy(enumerator);
     }
     /* if no valid trustchain was found, fall back to the first usable cert */
     if (!private)
     {
         enumerator = create_cert_enumerator(this, CERT_ANY, type, id, FALSE);
         while (enumerator->enumerate(enumerator, &cert))
         {
             private = get_private_by_cert(this, cert, type);
             if (private)
             {
                 if (auth)
                 {
                     auth->add(auth, AUTH_RULE_SUBJECT_CERT, cert->get_ref(cert));
                 }
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     return private;
 }
METHOD (credential_manager_t , flush_cache , void , private_credential_manager_t * this, certificate_type_t type)
Definition at line 1256 of file credential_manager.c.
References cache().
 {
     if (this->cache)
     {
         this->cache->flush(this->cache, type);
     }
 }
METHOD (credential_manager_t , add_set , void , private_credential_manager_t * this, credential_set_t * set)
Definition at line 1265 of file credential_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->sets->insert_last(this->sets, set);
     this->lock->unlock(this->lock);
 }
METHOD (credential_manager_t , remove_set , void , private_credential_manager_t * this, credential_set_t * set)
Definition at line 1273 of file credential_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->sets->remove(this->sets, set, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (credential_manager_t , add_validator , void , private_credential_manager_t * this, cert_validator_t * vdtr)
Definition at line 1281 of file credential_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->validators->insert_last(this->validators, vdtr);
     this->lock->unlock(this->lock);
 }
METHOD (credential_manager_t , remove_validator , void , private_credential_manager_t * this, cert_validator_t * vdtr)
Definition at line 1289 of file credential_manager.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->validators->remove(this->validators, vdtr, NULL);
     this->lock->unlock(this->lock);
 }
METHOD (credential_manager_t , destroy , void , private_credential_manager_t * this)
Definition at line 1297 of file credential_manager.c.
References cache(), cache_queue(), spinlock_t::destroy, free(), and lock.
 {
     cache_queue(this);
     this->cache_queue->destroy(this->cache_queue);
     if (this->cache)
     {
         this->sets->remove(this->sets, this->cache, NULL);
         this->cache->destroy(this->cache);
     }
     this->sets->destroy(this->sets);
     this->local_sets->destroy(this->local_sets);
     this->exclusive_local_sets->destroy(this->exclusive_local_sets);
     this->validators->destroy(this->validators);
     this->lock->destroy(this->lock);
     this->queue_mutex->destroy(this->queue_mutex);
     free(this);
 }
static void prefer_cert (auth_cfg_t * auth, certificate_t * cert) static
Move the actually used certificate to front, so it gets returned with get()
Definition at line 1127 of file credential_manager.c.
References auth_cfg_t::add, AUTH_RULE_SUBJECT_CERT, auth_cfg_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, certificate_t::get_ref, and auth_cfg_t::replace.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     auth_rule_t rule;
     certificate_t *current;
     enumerator = auth->create_enumerator(auth);
     while (enumerator->enumerate(enumerator, &rule, &current))
     {
         if (rule == AUTH_RULE_SUBJECT_CERT)
         {
             current->get_ref(current);
             auth->replace(auth, enumerator, AUTH_RULE_SUBJECT_CERT, cert);
             cert = current;
         }
     }
     enumerator->destroy(enumerator);
     auth->add(auth, AUTH_RULE_SUBJECT_CERT, cert);
 }
static bool verify_trust_chain (private_credential_manager_t * this, certificate_t * subject, auth_cfg_t * result, bool trusted, bool online) static
try to verify the trust chain of subject, return TRUE if trusted
Definition at line 714 of file credential_manager.c.
References auth_cfg_t::add, auth_cfg_create(), AUTH_RULE_CA_CERT, AUTH_RULE_IM_CERT, AUTH_RULE_SIGNATURE_SCHEME, AUTH_RULE_SUBJECT_CERT, call_hook(), check_certificate(), CRED_HOOK_EXCEEDED_PATH_LEN, CRED_HOOK_NO_ISSUER, CRED_HOOK_UNTRUSTED_ROOT, DBG1, DBG_CFG, certificate_t::destroy, auth_cfg_t::destroy, certificate_t::equals, FALSE, get_issuer_cert(), get_key_strength(), certificate_t::get_ref, certificate_t::get_subject, MAX_TRUST_PATH_LEN, auth_cfg_t::merge, scheme, and TRUE.
Referenced by METHOD().
 {
     certificate_t *current, *issuer;
     auth_cfg_t *auth;
     signature_scheme_t scheme;
     int pathlen;
     auth = auth_cfg_create();
     get_key_strength(subject, auth);
     current = subject->get_ref(subject);
     auth->add(auth, AUTH_RULE_SUBJECT_CERT, current->get_ref(current));
     for (pathlen = 0; pathlen <= MAX_TRUST_PATH_LEN; pathlen++)
     {
         issuer = get_issuer_cert(this, current, TRUE, &scheme);
         if (issuer)
         {
             /* accept only self-signed CAs as trust anchor */
             if (issued_by(this, issuer, issuer, NULL))
             {
                 auth->add(auth, AUTH_RULE_CA_CERT, issuer->get_ref(issuer));
                 DBG1(DBG_CFG, "  using trusted ca certificate \"%Y\"",
                               issuer->get_subject(issuer));
                 trusted = TRUE;
             }
             else
             {
                 auth->add(auth, AUTH_RULE_IM_CERT, issuer->get_ref(issuer));
                 DBG1(DBG_CFG, "  using trusted intermediate ca certificate "
                      "\"%Y\"", issuer->get_subject(issuer));
             }
             auth->add(auth, AUTH_RULE_SIGNATURE_SCHEME, scheme);
         }
         else
         {
             issuer = get_issuer_cert(this, current, FALSE, &scheme);
             if (issuer)
             {
                 if (current->equals(current, issuer))
                 {
                     DBG1(DBG_CFG, "  self-signed certificate \"%Y\" is not "
                          "trusted", current->get_subject(current));
                     issuer->destroy(issuer);
                     call_hook(this, CRED_HOOK_UNTRUSTED_ROOT, current);
                     break;
                 }
                 auth->add(auth, AUTH_RULE_IM_CERT, issuer->get_ref(issuer));
                 DBG1(DBG_CFG, "  using untrusted intermediate certificate "
                      "\"%Y\"", issuer->get_subject(issuer));
                 auth->add(auth, AUTH_RULE_SIGNATURE_SCHEME, scheme);
             }
             else
             {
                 DBG1(DBG_CFG, "no issuer certificate found for \"%Y\"",
                      current->get_subject(current));
                 call_hook(this, CRED_HOOK_NO_ISSUER, current);
                 break;
             }
         }
         if (!check_certificate(this, current, issuer, online,
                                pathlen, trusted, auth))
         {
             trusted = FALSE;
             issuer->destroy(issuer);
             break;
         }
         if (issuer)
         {
             get_key_strength(issuer, auth);
         }
         current->destroy(current);
         current = issuer;
         if (trusted)
         {
             DBG1(DBG_CFG, "  reached self-signed root ca with a "
                  "path length of %d", pathlen);
             break;
         }
     }
     current->destroy(current);
     if (pathlen > MAX_TRUST_PATH_LEN)
     {
         DBG1(DBG_CFG, "maximum path length of %d exceeded", MAX_TRUST_PATH_LEN);
         call_hook(this, CRED_HOOK_EXCEEDED_PATH_LEN, subject);
     }
     if (trusted)
     {
         result->merge(result, auth, FALSE);
     }
     auth->destroy(auth);
     return trusted;
 }