strongSwan: imc_state_t Struct Reference
imc_state_t Struct Reference
imc_state
#include "imc_state.h"
Public Attributes
TNC_ConnectionID(* get_connection_id)(imc_state_t *this)
bool(* has_long)(imc_state_t *this)
bool(* has_excl)(imc_state_t *this)
void(* set_flags)(imc_state_t *this, bool has_long, bool has_excl)
void(* set_max_msg_len)(imc_state_t *this, u_int32_t max_msg_len)
u_int32_t(* get_max_msg_len)(imc_state_t *this)
seg_contract_manager_t *(* get_contracts)(imc_state_t *this)
void(* change_state)(imc_state_t *this, TNC_ConnectionState new_state)
void(* set_result)(imc_state_t *this, TNC_IMCID id, TNC_IMV_Evaluation_Result result)
bool(* get_result)(imc_state_t *this, TNC_IMCID id, TNC_IMV_Evaluation_Result *result)
void(* destroy)(imc_state_t *this)
Detailed Description
Internal state of an IMC connection instance
Definition at line 38 of file imc_state.h.
Member Data Documentation
void(* imc_state_t::change_state)(imc_state_t *this, TNC_ConnectionState new_state)
Change the connection state
Parameters
new_state new connection state
Definition at line 96 of file imc_state.h.
Referenced by METHOD().
void(* imc_state_t::destroy)(imc_state_t *this)
Destroys an imc_state_t object
Definition at line 120 of file imc_state.h.
Referenced by delete_connection(), and METHOD().
TNC_ConnectionID(* imc_state_t::get_connection_id)(imc_state_t *this)
Get the TNCS connection ID attached to the state
Returns
TNCS connection ID of the state
Definition at line 45 of file imc_state.h.
Referenced by delete_connection(), find_connection(), and METHOD().
seg_contract_manager_t*(* imc_state_t::get_contracts)(imc_state_t *this)
Get attribute segmentation contracts associated with TNCCS Connection
Returns
contracts associated with TNCCS Connection
Definition at line 89 of file imc_state.h.
Referenced by TNC_IMC_BeginHandshake().
u_int32_t(* imc_state_t::get_max_msg_len)(imc_state_t *this)
Get the maximum size of a PA-TNC message for this TNCCS connection
Returns
maximum size of a PA-TNC message
Definition at line 82 of file imc_state.h.
Referenced by TNC_IMC_BeginHandshake().
bool(* imc_state_t::get_result)(imc_state_t *this, TNC_IMCID id, TNC_IMV_Evaluation_Result *result)
Get the Assessment/Evaluation Result
Parameters
id IMC ID
result Assessment/Evaluation Result
Returns
TRUE if result is known
Definition at line 114 of file imc_state.h.
Referenced by receive_message().
bool(* imc_state_t::has_excl)(imc_state_t *this)
Checks if the exclusive delivery is supported for this TNCCS connection
Returns
TRUE if set, FALSE otherwise
Definition at line 59 of file imc_state.h.
bool(* imc_state_t::has_long)(imc_state_t *this)
Checks if long message types are supported for this TNCCS connection
Returns
TRUE if set, FALSE otherwise
Definition at line 52 of file imc_state.h.
Referenced by TNC_IMC_BeginHandshake().
void(* imc_state_t::set_flags)(imc_state_t *this, bool has_long, bool has_excl)
Sets the long message types and exclusive flags for this TNCCS connection
Parameters
has_long TNCCS connection supports long message types
has_excl TNCCS connection supports exclusive delivery
Returns
TRUE if set, FALSE otherwise
Definition at line 68 of file imc_state.h.
Referenced by METHOD().
void(* imc_state_t::set_max_msg_len)(imc_state_t *this, u_int32_t max_msg_len)
Set the maximum size of a PA-TNC message for this TNCCS connection
Parameters
max_msg_len maximum size of a PA-TNC message
Definition at line 75 of file imc_state.h.
Referenced by METHOD().
void(* imc_state_t::set_result)(imc_state_t *this, TNC_IMCID id, TNC_IMV_Evaluation_Result result)
Set the Assessment/Evaluation Result
Parameters
id IMC ID
result Assessment/Evaluation Result
Definition at line 104 of file imc_state.h.
Referenced by TNC_IMC_NotifyConnectionChange().
The documentation for this struct was generated from the following file:
imc_state.h