strongSwan: ipsec_processor.c File Reference
ipsec_processor.c File Reference
#include "ipsec.h"
#include "ipsec_processor.h"
#include <utils/debug.h>
#include <library.h>
#include <threading/rwlock.h>
#include <collections/blocking_queue.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_ipsec_processor_t
Typedefs
typedef struct
private_ipsec_processor_t private_ipsec_processor_t
Functions
static void deliver_inbound (private_ipsec_processor_t *this, esp_packet_t *packet)
static job_requeue_t process_inbound (private_ipsec_processor_t *this)
static void send_outbound (private_ipsec_processor_t *this, esp_packet_t *packet)
static job_requeue_t process_outbound (private_ipsec_processor_t *this)
METHOD (ipsec_processor_t, queue_inbound, void, private_ipsec_processor_t *this, esp_packet_t *packet)
METHOD (ipsec_processor_t, queue_outbound, void, private_ipsec_processor_t *this, ip_packet_t *packet)
METHOD (ipsec_processor_t, register_inbound, void, private_ipsec_processor_t *this, ipsec_inbound_cb_t cb, void *data)
METHOD (ipsec_processor_t, unregister_inbound, void, private_ipsec_processor_t *this, ipsec_inbound_cb_t cb)
METHOD (ipsec_processor_t, register_outbound, void, private_ipsec_processor_t *this, ipsec_outbound_cb_t cb, void *data)
METHOD (ipsec_processor_t, unregister_outbound, void, private_ipsec_processor_t *this, ipsec_outbound_cb_t cb)
METHOD (ipsec_processor_t, destroy, void, private_ipsec_processor_t *this)
ipsec_processor_t * ipsec_processor_create ()
Typedef Documentation
typedef struct private_ipsec_processor_t private_ipsec_processor_t
Definition at line 25 of file ipsec_processor.c.
Function Documentation
static void deliver_inbound (private_ipsec_processor_t * this, esp_packet_t * packet) static
Deliver an inbound IP packet to the registered listener
Definition at line 72 of file ipsec_processor.c.
References DBG2, DBG_ESP, esp_packet_t::destroy, esp_packet_t::extract_payload, lock, and spinlock_t::unlock.
Referenced by process_inbound().
 {
     this->lock->read_lock(this->lock);
     if (this->inbound.cb)
     {
         this->inbound.cb(this->inbound.data, packet->extract_payload(packet));
     }
     else
     {
         DBG2(DBG_ESP, "no inbound callback registered, dropping packet");
     }
     packet->destroy(packet);
     this->lock->unlock(this->lock);
 }
METHOD (ipsec_processor_t , queue_inbound , void , private_ipsec_processor_t * this, esp_packet_t * packet)
Definition at line 236 of file ipsec_processor.c.
 {
     this->inbound_queue->enqueue(this->inbound_queue, packet);
 }
METHOD (ipsec_processor_t , queue_outbound , void , private_ipsec_processor_t * this, ip_packet_t * packet)
Definition at line 242 of file ipsec_processor.c.
 {
     this->outbound_queue->enqueue(this->outbound_queue, packet);
 }
METHOD (ipsec_processor_t , register_inbound , void , private_ipsec_processor_t * this, ipsec_inbound_cb_t cb, void * data)
Definition at line 248 of file ipsec_processor.c.
References cb(), data, lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->inbound.cb = cb;
     this->inbound.data = data;
     this->lock->unlock(this->lock);
 }
METHOD (ipsec_processor_t , unregister_inbound , void , private_ipsec_processor_t * this, ipsec_inbound_cb_t cb)
Definition at line 257 of file ipsec_processor.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     if (this->inbound.cb == cb)
     {
         this->inbound.cb = NULL;
     }
     this->lock->unlock(this->lock);
 }
METHOD (ipsec_processor_t , register_outbound , void , private_ipsec_processor_t * this, ipsec_outbound_cb_t cb, void * data)
Definition at line 268 of file ipsec_processor.c.
References cb(), data, lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     this->outbound.cb = cb;
     this->outbound.data = data;
     this->lock->unlock(this->lock);
 }
METHOD (ipsec_processor_t , unregister_outbound , void , private_ipsec_processor_t * this, ipsec_outbound_cb_t cb)
Definition at line 277 of file ipsec_processor.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->write_lock(this->lock);
     if (this->outbound.cb == cb)
     {
         this->outbound.cb = NULL;
     }
     this->lock->unlock(this->lock);
 }
METHOD (ipsec_processor_t , destroy , void , private_ipsec_processor_t * this)
Definition at line 288 of file ipsec_processor.c.
References spinlock_t::destroy, destroy(), free(), and lock.
 {
     this->inbound_queue->destroy_offset(this->inbound_queue,
                                         offsetof(esp_packet_t, destroy));
     this->outbound_queue->destroy_offset(this->outbound_queue,
                                          offsetof(ip_packet_t, destroy));
     this->lock->destroy(this->lock);
     free(this);
 }
static job_requeue_t process_inbound (private_ipsec_processor_t * this) static
Processes inbound packets
Definition at line 91 of file ipsec_processor.c.
References ipsec_sa_mgr_t::checkin, ipsec_sa_mgr_t::checkout_by_spi, DBG1, DBG2, DBG_ESP, esp_packet_t::decrypt, deliver_inbound(), ipsec_policy_t::destroy, esp_packet_t::destroy, ipsec_policy_mgr_t::find_by_packet, ip_packet_t::get_destination, esp_packet_t::get_destination, ip_packet_t::get_encoding, ipsec_sa_t::get_esp_context, esp_packet_t::get_next_header, esp_packet_t::get_payload, ipsec_sa_t::get_reqid, ip_packet_t::get_source, IPPROTO_IPIP, IPPROTO_IPV6, ipsec, ipsec_sa_t::is_inbound, JOB_REQUEUE_DIRECT, chunk_t::len, esp_packet_t::parse_header, ipsec_t::policies, sa, ipsec_t::sas, SUCCESS, TRUE, and ipsec_sa_t::update_usestats.
Referenced by ipsec_processor_create().
 {
     esp_packet_t *packet;
     ip_packet_t *ip_packet;
     ipsec_sa_t *sa;
     u_int8_t next_header;
     u_int32_t spi, reqid;
     packet = (esp_packet_t*)this->inbound_queue->dequeue(this->inbound_queue);
     if (!packet->parse_header(packet, &spi))
     {
         packet->destroy(packet);
         return JOB_REQUEUE_DIRECT;
     }
     sa = ipsec->sas->checkout_by_spi(ipsec->sas, spi,
                                      packet->get_destination(packet));
     if (!sa)
     {
         DBG2(DBG_ESP, "inbound ESP packet does not belong to an installed SA");
         packet->destroy(packet);
         return JOB_REQUEUE_DIRECT;
     }
     if (!sa->is_inbound(sa))
     {
         DBG1(DBG_ESP, "error: IPsec SA is not inbound");
         packet->destroy(packet);
         ipsec->sas->checkin(ipsec->sas, sa);
         return JOB_REQUEUE_DIRECT;
     }
     if (packet->decrypt(packet, sa->get_esp_context(sa)) != SUCCESS)
     {
         ipsec->sas->checkin(ipsec->sas, sa);
         packet->destroy(packet);
         return JOB_REQUEUE_DIRECT;
     }
     ip_packet = packet->get_payload(packet);
     sa->update_usestats(sa, ip_packet->get_encoding(ip_packet).len);
     reqid = sa->get_reqid(sa);
     ipsec->sas->checkin(ipsec->sas, sa);
     next_header = packet->get_next_header(packet);
     switch (next_header)
     {
         case IPPROTO_IPIP:
         case IPPROTO_IPV6:
         {
             ipsec_policy_t *policy;
             policy = ipsec->policies->find_by_packet(ipsec->policies,
                                                      ip_packet, TRUE, reqid);
             if (policy)
             {
                 deliver_inbound(this, packet);
                 policy->destroy(policy);
                 break;
             }
             DBG1(DBG_ESP, "discarding inbound IP packet %H == %H due to "
                  "policy", ip_packet->get_source(ip_packet),
                  ip_packet->get_destination(ip_packet));
             /* no matching policy found, fall-through */
         }
         case IPPROTO_NONE:
             /* discard dummy packets */
             /* fall-through */
         default:
             packet->destroy(packet);
             break;
     }
     return JOB_REQUEUE_DIRECT;
 }
static job_requeue_t process_outbound (private_ipsec_processor_t * this) static
Processes outbound packets
Definition at line 188 of file ipsec_processor.c.
References ipsec_sa_mgr_t::checkin, ipsec_sa_mgr_t::checkout_by_reqid, host_t::clone, DBG1, DBG2, DBG_ESP, ip_packet_t::destroy, ipsec_policy_t::destroy, esp_packet_t::destroy, dst, esp_packet_t::encrypt, esp_packet_create_from_payload(), FALSE, ipsec_policy_mgr_t::find_by_packet, ipsec_sa_t::get_destination, ip_packet_t::get_destination, ip_packet_t::get_encoding, ipsec_sa_t::get_esp_context, ipsec_policy_t::get_reqid, ipsec_sa_t::get_source, ip_packet_t::get_source, ipsec_sa_t::get_spi, ipsec, JOB_REQUEUE_DIRECT, chunk_t::len, ipsec_t::policies, sa, ipsec_t::sas, send_outbound(), src, SUCCESS, and ipsec_sa_t::update_usestats.
Referenced by ipsec_processor_create().
 {
     ipsec_policy_t *policy;
     esp_packet_t *esp_packet;
     ip_packet_t *packet;
     ipsec_sa_t *sa;
     host_t *src, *dst;
     packet = (ip_packet_t*)this->outbound_queue->dequeue(this->outbound_queue);
     policy = ipsec->policies->find_by_packet(ipsec->policies, packet, FALSE, 0);
     if (!policy)
     {
         DBG2(DBG_ESP, "no matching outbound IPsec policy for %H == %H",
              packet->get_source(packet), packet->get_destination(packet));
         packet->destroy(packet);
         return JOB_REQUEUE_DIRECT;
     }
     sa = ipsec->sas->checkout_by_reqid(ipsec->sas, policy->get_reqid(policy),
                                        FALSE);
     if (!sa)
     {   /* TODO-IPSEC: send an acquire to uppper layer */
         DBG1(DBG_ESP, "could not find an outbound IPsec SA for reqid {%u}, "
              "dropping packet", policy->get_reqid(policy));
         packet->destroy(packet);
         policy->destroy(policy);
         return JOB_REQUEUE_DIRECT;
     }
     src = sa->get_source(sa);
     dst = sa->get_destination(sa);
     esp_packet = esp_packet_create_from_payload(src->clone(src),
                                                 dst->clone(dst), packet);
     if (esp_packet->encrypt(esp_packet, sa->get_esp_context(sa),
                             sa->get_spi(sa)) != SUCCESS)
     {
         ipsec->sas->checkin(ipsec->sas, sa);
         esp_packet->destroy(esp_packet);
         policy->destroy(policy);
         return JOB_REQUEUE_DIRECT;
     }
     sa->update_usestats(sa, packet->get_encoding(packet).len);
     ipsec->sas->checkin(ipsec->sas, sa);
     policy->destroy(policy);
     send_outbound(this, esp_packet);
     return JOB_REQUEUE_DIRECT;
 }
static void send_outbound (private_ipsec_processor_t * this, esp_packet_t * packet) static
Send an ESP packet using the registered outbound callback
Definition at line 169 of file ipsec_processor.c.
References DBG2, DBG_ESP, esp_packet_t::destroy, lock, and spinlock_t::unlock.
Referenced by process_outbound().
 {
     this->lock->read_lock(this->lock);
     if (this->outbound.cb)
     {
         this->outbound.cb(this->outbound.data, packet);
     }
     else
     {
         DBG2(DBG_ESP, "no outbound callback registered, dropping packet");
         packet->destroy(packet);
     }
     this->lock->unlock(this->lock);
 }