strongSwan: libipsec
libipsec
Modules
esp_context
esp_packet
ip_packet
ipsec_event_listener
ipsec_event_relay
ipsec_policy
ipsec_policy_mgr
ipsec_processor
ipsec_sa
ipsec_sa_mgr
Classes
struct ipsec_t
Typedefs
typedef struct ipsec_t ipsec_t
Functions
bool libipsec_init ()
void libipsec_deinit ()
Variables
ipsec_t * ipsec
Detailed Description
Typedef Documentation
typedef struct ipsec_t ipsec_t
Definition at line 35 of file libipsec/ipsec.h.
Function Documentation
void libipsec_deinit ()
Deinitialize libipsec.
Described in header.
Definition at line 43 of file ipsec.c.
References DESTROY_IF, and free().
Referenced by METHOD().
 {
     private_ipsec_t *this = (private_ipsec_t*)ipsec;
     DESTROY_IF(this->public.processor);
     DESTROY_IF(this->public.events);
     DESTROY_IF(this->public.policies);
     DESTROY_IF(this->public.sas);
     free(this);
     ipsec = NULL;
 }
bool libipsec_init ()
Initialize libipsec.
Returns
FALSE if integrity check failed
Described in header.
Definition at line 57 of file ipsec.c.
References integrity_checker_t::check, DBG1, DBG_LIB, FALSE, INIT, library_t::integrity, ipsec_event_relay_create(), ipsec_policy_mgr_create(), ipsec_processor_create(), ipsec_sa_mgr_create(), lib, libipsec_init(), and TRUE.
Referenced by kernel_libipsec_plugin_create(), and libipsec_init().
 {
     private_ipsec_t *this;
     INIT(this);
     ipsec = &this->public;
     if (lib->integrity &&
         !lib->integrity->check(lib->integrity, "libipsec", libipsec_init))
     {
         DBG1(DBG_LIB, "integrity check of libipsec failed");
         return FALSE;
     }
     this->public.sas = ipsec_sa_mgr_create();
     this->public.policies = ipsec_policy_mgr_create();
     this->public.events = ipsec_event_relay_create();
     this->public.processor = ipsec_processor_create();
     return TRUE;
 }
Variable Documentation
ipsec_t* ipsec
The single instance of ipsec_t.
Set between calls to libipsec_init() and libipsec_deinit() calls.
Single instance of ipsec_t.
Definition at line 38 of file ipsec.c.
Referenced by add_policy_internal(), install_sa(), kernel_libipsec_ipsec_create(), kernel_libipsec_router_create(), METHOD(), process_inbound(), process_outbound(), process_plain(), and receiver_esp_cb().