strongSwan: ike_auth_fill.c File Reference
ike_auth_fill.c File Reference
#include "hook.h"
#include <time.h>
#include <netinet/udp.h>
#include <encoding/payloads/cert_payload.h>
#include <encoding/payloads/encrypted_payload.h>
Classes
struct private_ike_auth_fill_t
Macros
#define NON_ESP_MARKER_LEN 4
#define ENCRYPTION_PAYLOAD_HEADER_LENGTH 4
#define CERT_PAYLOAD_HEADER_LENGTH 5
Typedefs
typedef struct
private_ike_auth_fill_t private_ike_auth_fill_t
Functions
static size_t calculate_wire_size (message_t *message, ike_sa_t *ike_sa)
METHOD (listener_t, message, bool, private_ike_auth_fill_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (hook_t, destroy, void, private_ike_auth_fill_t *this)
hook_t * ike_auth_fill_hook_create (char *name)
Macro Definition Documentation
#define CERT_PAYLOAD_HEADER_LENGTH 5
length of fixed cert payload header
Definition at line 57 of file ike_auth_fill.c.
Referenced by METHOD().
#define ENCRYPTION_PAYLOAD_HEADER_LENGTH 4
length of fixed encryption payload header
Definition at line 55 of file ike_auth_fill.c.
Referenced by calculate_wire_size().
#define NON_ESP_MARKER_LEN 4
size of non ESP-Marker
Definition at line 53 of file ike_auth_fill.c.
Referenced by calculate_wire_size().
Typedef Documentation
typedef struct private_ike_auth_fill_t private_ike_auth_fill_t
Definition at line 24 of file ike_auth_fill.c.
Function Documentation
static size_t calculate_wire_size (message_t * message, ike_sa_t * ike_sa) static
Calculate packet size on wire (without ethernet/IP header)
Definition at line 61 of file ike_auth_fill.c.
References aead, message_t::create_payload_enumerator, enumerator_t::destroy, ENCRYPTION_PAYLOAD_HEADER_LENGTH, enumerator_t::enumerate, FALSE, keymat_t::get_aead, aead_t::get_block_size, message_t::get_exchange_type, aead_t::get_icv_size, aead_t::get_iv_size, ike_sa_t::get_keymat, payload_t::get_length, IKE_SA_INIT, NON_ESP_MARKER_LEN, and size.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     size_t size = 0;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         size += payload->get_length(payload);
     }
     enumerator->destroy(enumerator);
     if (message->get_exchange_type(message) != IKE_SA_INIT)
     {
         keymat_t *keymat;
         aead_t *aead;
         size_t  bs;
         keymat = ike_sa->get_keymat(ike_sa);
         aead = keymat->get_aead(keymat, FALSE);
         if (aead)
         {
             bs = aead->get_block_size(aead);
             size += ENCRYPTION_PAYLOAD_HEADER_LENGTH + NON_ESP_MARKER_LEN +
                 aead->get_icv_size(aead) + aead->get_iv_size(aead) +
                 (bs - (size % bs));
         }
     }
     return sizeof(struct udphdr) + IKE_HEADER_LENGTH + size;
 }
hook_t* ike_auth_fill_hook_create (char * name)
Create the IKE_AUTH fill hook
Definition at line 128 of file ike_auth_fill.c.
References conftest, settings_t::get_bool, settings_t::get_int, INIT, conftest_t::test, and TRUE.
 {
     private_ike_auth_fill_t *this;
     INIT(this,
         .hook = {
             .listener = {
                 .message = _message,
             },
             .destroy = _destroy,
         },
         .req = conftest->test->get_bool(conftest->test,
                                         "hooks.%s.request", TRUE, name),
         .id = conftest->test->get_int(conftest->test,
                                         "hooks.%s.id", 1, name),
         .bytes = conftest->test->get_int(conftest->test,
                                         "hooks.%s.bytes", 0, name),
     );
     return &this->hook;
 }
METHOD (listener_t , message , bool , private_ike_auth_fill_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 93 of file ike_auth_fill.c.
References message_t::add_payload, bytes, calculate_wire_size(), cert_payload_create_custom(), CERT_PAYLOAD_HEADER_LENGTH, chunk_alloc, data, DBG1, DBG_CFG, message_t::get_message_id, message_t::get_request, id, chunk_t::len, memset, cert_payload_t::payload_interface, PLV2_CERTIFICATE, chunk_t::ptr, req(), size, and TRUE.
 {
     if (!incoming && plain &&
         message->get_request(message) == this->req &&
         message->get_message_id(message) == this->id)
     {
         cert_payload_t *pld;
         size_t size, diff;
         chunk_t data;
         size = calculate_wire_size(message, ike_sa);
         if (size < this->bytes - CERT_PAYLOAD_HEADER_LENGTH)
         {
             diff = this->bytes - size - CERT_PAYLOAD_HEADER_LENGTH;
             data = chunk_alloc(diff);
             memset(data.ptr, 0x12, data.len);
             pld = cert_payload_create_custom(PLV2_CERTIFICATE, 201, data);
             message->add_payload(message, &pld->payload_interface);
             DBG1(DBG_CFG, "inserting %d dummy bytes certificate payload", diff);
         }
     }
     return TRUE;
 }
METHOD (hook_t , destroy , void , private_ike_auth_fill_t * this)
Definition at line 119 of file ike_auth_fill.c.
References free().
 {
     free(this);
 }