strongSwan: pts_pcr_t Struct Reference
pts_pcr_t Struct Reference
pts_pcr
#include "pts_pcr.h"
Public Attributes
u_int32_t(* get_count)(pts_pcr_t *this)
bool(* select_pcr)(pts_pcr_t *this, u_int32_t pcr)
size_t(* get_selection_size)(pts_pcr_t *this)
enumerator_t *(* create_enumerator)(pts_pcr_t *this)
chunk_t(* get)(pts_pcr_t *this, u_int32_t pcr)
bool(* set)(pts_pcr_t *this, u_int32_t pcr, chunk_t value)
chunk_t(* extend)(pts_pcr_t *this, u_int32_t pcr, chunk_t measurement)
chunk_t(* get_composite)(pts_pcr_t *this)
void(* destroy)(pts_pcr_t *this)
Detailed Description
Class implementing a shadow PCR register set
Definition at line 41 of file pts_pcr.h.
Member Data Documentation
enumerator_t*(* pts_pcr_t::create_enumerator)(pts_pcr_t *this)
Create an enumerator over all selected PCR indexes
Returns
enumerator
Definition at line 70 of file pts_pcr.h.
void(* pts_pcr_t::destroy)(pts_pcr_t *this)
Destroys a pts_pcr_t object.
Definition at line 109 of file pts_pcr.h.
chunk_t(* pts_pcr_t::extend)(pts_pcr_t *this, u_int32_t pcr, chunk_t measurement)
Extend the content of a PCR
Parameters
pcr index of PCR
measurement measurment value to be extended into PCR
Returns
new content of PCR
Definition at line 96 of file pts_pcr.h.
Referenced by extend_pcr(), and METHOD().
chunk_t(* pts_pcr_t::get)(pts_pcr_t *this, u_int32_t pcr)
Get the current content of a PCR
Parameters
pcr index of PCR
Returns
content of PCR
Definition at line 78 of file pts_pcr.h.
Referenced by check_boot_aggregate(), extend_pcr(), and METHOD().
chunk_t(* pts_pcr_t::get_composite)(pts_pcr_t *this)
Create a PCR Composite object over all selected PCRs
Returns
PCR Composite object (must be freed)
Definition at line 103 of file pts_pcr.h.
u_int32_t(* pts_pcr_t::get_count)(pts_pcr_t *this)
Get the number of selected PCRs
Returns
number of selected PCRs
Definition at line 48 of file pts_pcr.h.
size_t(* pts_pcr_t::get_selection_size)(pts_pcr_t *this)
Get the size of the selection field in bytes
Returns
number of bytes written
Definition at line 63 of file pts_pcr.h.
bool(* pts_pcr_t::select_pcr)(pts_pcr_t *this, u_int32_t pcr)
Mark a PCR as selected
Parameters
pcr index of PCR
Returns
TRUE if PCR index exists
Definition at line 56 of file pts_pcr.h.
bool(* pts_pcr_t::set)(pts_pcr_t *this, u_int32_t pcr, chunk_t value)
Set the content of a PCR
Parameters
pcr index of PCR
value new value of PCR
Returns
TRUE if value could be set
Definition at line 87 of file pts_pcr.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
pts_pcr.h