strongSwan: tls_test.c File Reference
tls_test.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <getopt.h>
#include <errno.h>
#include <string.h>
#include <library.h>
#include <utils/debug.h>
#include <tls_socket.h>
#include <networking/host.h>
#include <credentials/sets/mem_cred.h>
Functions
static void usage (FILE *out, char *cmd)
static identification_t * find_client_id ()
static int run_client (host_t *host, identification_t *server, identification_t *client, int times, tls_cache_t *cache)
static int serve (host_t *host, identification_t *server, int times, tls_cache_t *cache)
static bool load_certificate (char *filename)
static bool load_key (char *filename)
static void dbg_tls (debug_t group, level_t level, char *fmt,...)
static void cleanup ()
static void init ()
int main (int argc, char *argv[])
Variables
static mem_cred_t * creds
static level_t tls_level = 1
Function Documentation
static void cleanup (void) static
Cleanup
Definition at line 242 of file tls_test.c.
References library_t::credmgr, mem_cred_t::destroy, lib, library_deinit(), credential_manager_t::remove_set, and mem_cred_t::set.
Referenced by init().
 {
     lib->credmgr->remove_set(lib->credmgr, &creds->set);
     creds->destroy(creds);
     library_deinit();
 }
static void dbg_tls (debug_t group, level_t level, char * fmt, ...) static
Definition at line 226 of file tls_test.c.
References DBG_TLS, fprintf, tls_level, and vfprintf.
Referenced by init().
 {
     if ((group == DBG_TLS && level <= tls_level) || level <= 1)
     {
         va_list args;
         va_start(args, fmt);
         vfprintf(stderr, fmt, args);
         fprintf(stderr, "\n");
         va_end(args);
     }
 }
static identification_t* find_client_id () static
Check, as client, if we have a client certificate with private key
Definition at line 43 of file tls_test.c.
References cert, CERT_X509, client(), identification_t::clone, credential_manager_t::create_cert_enumerator, library_t::credmgr, enumerator_t::destroy, private_key_t::destroy, public_key_t::destroy, enumerator_t::enumerate, FALSE, public_key_t::get_fingerprint, credential_manager_t::get_private, certificate_t::get_public_key, certificate_t::get_subject, public_key_t::get_type, ID_KEY_ID, identification_create_from_encoding(), KEY_ANY, keyid(), KEYID_PUBKEY_SHA1, and lib.
Referenced by main().
 {
     identification_t *client = NULL, *keyid;
     enumerator_t *enumerator;
     certificate_t *cert;
     public_key_t *pubkey;
     private_key_t *privkey;
     chunk_t chunk;
     enumerator = lib->credmgr->create_cert_enumerator(lib->credmgr,
                                             CERT_X509, KEY_ANY, NULL, FALSE);
     while (enumerator->enumerate(enumerator, &cert))
     {
         pubkey = cert->get_public_key(cert);
         if (pubkey)
         {
             if (pubkey->get_fingerprint(pubkey, KEYID_PUBKEY_SHA1, &chunk))
             {
                 keyid = identification_create_from_encoding(ID_KEY_ID, chunk);
                 privkey = lib->credmgr->get_private(lib->credmgr,
                                     pubkey->get_type(pubkey), keyid, NULL);
                 keyid->destroy(keyid);
                 if (privkey)
                 {
                     client = cert->get_subject(cert);
                     client = client->clone(client);
                     privkey->destroy(privkey);
                 }
             }
             pubkey->destroy(pubkey);
         }
         if (client)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return client;
 }
static void init (void) static
Initialize library
Definition at line 252 of file tls_test.c.
References credential_manager_t::add_set, cleanup(), library_t::credmgr, dbg, dbg_tls(), lib, library_init(), plugin_loader_t::load, mem_cred_create(), PLUGINS, library_t::plugins, and mem_cred_t::set.
Referenced by check_and_put_init_hash(), load_suites(), main(), post_test(), and pre_test().
 {
     library_init(NULL, "tls_test");
     dbg = dbg_tls;
     lib->plugins->load(lib->plugins, PLUGINS);
     creds = mem_cred_create();
     lib->credmgr->add_set(lib->credmgr, &creds->set);
     atexit(cleanup);
 }
static bool load_certificate (char * filename) static
Load certificate from file
Definition at line 188 of file tls_test.c.
References mem_cred_t::add_cert, BUILD_END, BUILD_FROM_FILE, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG_TLS, FALSE, lib, and TRUE.
Referenced by main().
 {
     certificate_t *cert;
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_FROM_FILE, filename, BUILD_END);
     if (!cert)
     {
         DBG1(DBG_TLS, "loading certificate from '%s' failed", filename);
         return FALSE;
     }
     creds->add_cert(creds, TRUE, cert);
     return TRUE;
 }
static bool load_key (char * filename) static
Load private key from file
Definition at line 206 of file tls_test.c.
References mem_cred_t::add_key, BUILD_END, BUILD_FROM_FILE, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, DBG1, DBG_TLS, FALSE, key, KEY_RSA, lib, and TRUE.
Referenced by main(), and manage_commands().
 {
     private_key_t *key;
     key = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                               BUILD_FROM_FILE, filename, BUILD_END);
     if (!key)
     {
         DBG1(DBG_TLS, "loading key from '%s' failed", filename);
         return FALSE;
     }
     creds->add_key(creds, key);
     return TRUE;
 }
int main (int argc, char * argv[])
Definition at line 266 of file tls_test.c.
References cache(), client(), DBG1, DBG_TLS, tls_cache_t::destroy, host_t::destroy, identification_t::destroy, DESTROY_IF, FALSE, find_client_id(), host, host_create_from_dns(), identification_create_from_string(), init(), load_certificate(), load_key(), port, res, run_client(), serve(), server, tls_cache_create(), tls_level, TRUE, and usage().
 {
     char *address = NULL;
     bool listen = FALSE;
     int port = 0, times = -1, res;
     identification_t *server, *client;
     tls_cache_t *cache;
     host_t *host;
     init();
     while (TRUE)
     {
         struct option long_opts[] = {
             {"help",        no_argument,            NULL,       'h' },
             {"connect",     required_argument,      NULL,       'c' },
             {"listen",      required_argument,      NULL,       'l' },
             {"port",        required_argument,      NULL,       'p' },
             {"cert",        required_argument,      NULL,       'x' },
             {"key",         required_argument,      NULL,       'k' },
             {"times",       required_argument,      NULL,       't' },
             {"debug",       required_argument,      NULL,       'd' },
             {0,0,0,0 }
         };
         switch (getopt_long(argc, argv, "", long_opts, NULL))
         {
             case EOF:
                 break;
             case 'h':
                 usage(stdout, argv[0]);
                 return 0;
             case 'x':
                 if (!load_certificate(optarg))
                 {
                     return 1;
                 }
                 continue;
             case 'k':
                 if (!load_key(optarg))
                 {
                     return 1;
                 }
                 continue;
             case 'l':
                 listen = TRUE;
                 /* fall */
             case 'c':
                 if (address)
                 {
                     usage(stderr, argv[0]);
                     return 1;
                 }
                 address = optarg;
                 continue;
             case 'p':
                 port = atoi(optarg);
                 continue;
             case 't':
                 times = atoi(optarg);
                 continue;
             case 'd':
                 tls_level = atoi(optarg);
                 continue;
             default:
                 usage(stderr, argv[0]);
                 return 1;
         }
         break;
     }
     if (!port || !address)
     {
         usage(stderr, argv[0]);
         return 1;
     }
     host = host_create_from_dns(address, 0, port);
     if (!host)
     {
         DBG1(DBG_TLS, "resolving hostname %s failed", address);
         return 1;
     }
     server = identification_create_from_string(address);
     cache = tls_cache_create(100, 30);
     if (listen)
     {
         res = serve(host, server, times, cache);
     }
     else
     {
         client = find_client_id();
         res = run_client(host, server, client, times, cache);
         DESTROY_IF(client);
     }
     cache->destroy(cache);
     host->destroy(host);
     server->destroy(server);
     return res;
 }
static int run_client (host_t * host, identification_t * server, identification_t * client, int times, tls_cache_t * cache) static
Client routine
Definition at line 87 of file tls_test.c.
References close, connect, DBG1, DBG_TLS, tls_socket_t::destroy, FALSE, host_t::get_sockaddr, host_t::get_sockaddr_len, res, socket, tls_socket_t::splice, strerror, tls, TLS_1_2, tls_socket_create(), and TRUE.
Referenced by main().
 {
     tls_socket_t *tls;
     int fd, res;
     while (times == -1 || times-- > 0)
     {
         fd = socket(AF_INET, SOCK_STREAM, 0);
         if (fd == -1)
         {
             DBG1(DBG_TLS, "opening socket failed: %s", strerror(errno));
             return 1;
         }
         if (connect(fd, host->get_sockaddr(host),
                     *host->get_sockaddr_len(host)) == -1)
         {
             DBG1(DBG_TLS, "connecting to %#H failed: %s", host, strerror(errno));
             close(fd);
             return 1;
         }
         tls = tls_socket_create(FALSE, server, client, fd, cache, TLS_1_2, TRUE);
         if (!tls)
         {
             close(fd);
             return 1;
         }
         res = tls->splice(tls, 0, 1) ? 0 : 1;
         tls->destroy(tls);
         close(fd);
         if (res)
         {
             break;
         }
     }
     return res;
 }
static int serve (host_t * host, identification_t * server, int times, tls_cache_t * cache) static
Server routine
Definition at line 128 of file tls_test.c.
References accept, bind, close, DBG1, DBG_TLS, tls_socket_t::destroy, host_t::get_sockaddr, host_t::get_sockaddr_len, socket, tls_socket_t::splice, strerror, tls, TLS_1_2, tls_socket_create(), and TRUE.
Referenced by main().
 {
     tls_socket_t *tls;
     int fd, cfd;
     fd = socket(AF_INET, SOCK_STREAM, 0);
     if (fd == -1)
     {
         DBG1(DBG_TLS, "opening socket failed: %s", strerror(errno));
         return 1;
     }
     if (bind(fd, host->get_sockaddr(host),
              *host->get_sockaddr_len(host)) == -1)
     {
         DBG1(DBG_TLS, "binding to %#H failed: %s", host, strerror(errno));
         close(fd);
         return 1;
     }
     if (listen(fd, 1) == -1)
     {
         DBG1(DBG_TLS, "listen to %#H failed: %m", host, strerror(errno));
         close(fd);
         return 1;
     }
     while (times == -1 || times-- > 0)
     {
         cfd = accept(fd, host->get_sockaddr(host), host->get_sockaddr_len(host));
         if (cfd == -1)
         {
             DBG1(DBG_TLS, "accept failed: %s", strerror(errno));
             close(fd);
             return 1;
         }
         DBG1(DBG_TLS, "%#H connected", host);
         tls = tls_socket_create(TRUE, server, NULL, cfd, cache, TLS_1_2, TRUE);
         if (!tls)
         {
             close(fd);
             return 1;
         }
         tls->splice(tls, 0, 1);
         DBG1(DBG_TLS, "%#H disconnected", host);
         tls->destroy(tls);
     }
     close(fd);
     return 0;
 }
static void usage (FILE * out, char * cmd) static
Print usage information
Definition at line 33 of file tls_test.c.
References fprintf.
Referenced by main().
 {
     fprintf(out, "usage:\n");
     fprintf(out, "  %s --connect <address> --port <port> [--key <key] [--cert <file>]+ [--times <n>]\n", cmd);
     fprintf(out, "  %s --listen <address> --port <port> --key <key> [--cert <file>]+ [--times <n>]\n", cmd);
 }
Variable Documentation
mem_cred_t* creds static
In-Memory credential set
Definition at line 183 of file tls_test.c.
level_t tls_level = 1 static
TLS debug level
Definition at line 224 of file tls_test.c.
Referenced by dbg_tls(), and main().