strongSwan: pts_file_meta.c File Reference
pts_file_meta.c File Reference
#include "pts_file_meta.h"
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_pts_file_meta_t
Typedefs
typedef struct
private_pts_file_meta_t private_pts_file_meta_t
Functions
static void free_entry (pts_file_metadata_t *entry)
METHOD (pts_file_meta_t, get_file_count, int, private_pts_file_meta_t *this)
METHOD (pts_file_meta_t, add, void, private_pts_file_meta_t *this, pts_file_metadata_t *metadata)
METHOD (pts_file_meta_t, create_enumerator, enumerator_t *, private_pts_file_meta_t *this)
METHOD (pts_file_meta_t, destroy, void, private_pts_file_meta_t *this)
pts_file_meta_t * pts_file_meta_create ()
Typedef Documentation
typedef struct private_pts_file_meta_t private_pts_file_meta_t
Definition at line 21 of file pts_file_meta.c.
Function Documentation
static void free_entry (pts_file_metadata_t * entry) static
Free an pts_file_metadata_t object
Definition at line 43 of file pts_file_meta.c.
References pts_file_metadata_t::filename, and free().
Referenced by METHOD().
 {
     if (entry)
     {
         free(entry->filename);
         free(entry);
     }
 }
METHOD (pts_file_meta_t , get_file_count , int , private_pts_file_meta_t * this)
Definition at line 52 of file pts_file_meta.c.
References linked_list_t::get_count, and list.
 {
     return this->list->get_count(this->list);
 }
METHOD (pts_file_meta_t , add , void , private_pts_file_meta_t * this, pts_file_metadata_t * metadata)
Definition at line 58 of file pts_file_meta.c.
References linked_list_t::insert_last, and list.
 {
     this->list->insert_last(this->list, metadata);
 }
METHOD (pts_file_meta_t , create_enumerator , enumerator_t * , private_pts_file_meta_t * this)
Definition at line 64 of file pts_file_meta.c.
References linked_list_t::create_enumerator, and list.
 {
     return this->list->create_enumerator(this->list);
 }
METHOD (pts_file_meta_t , destroy , void , private_pts_file_meta_t * this)
Definition at line 70 of file pts_file_meta.c.
References linked_list_t::destroy_function, free(), free_entry(), and list.
 {
     this->list->destroy_function(this->list, (void *)free_entry);
     free(this);
 }