strongSwan: stream
stream
streams
Modules
stream_service_tcp
stream_service_unix
Classes
struct stream_t
Typedefs
typedef struct stream_t stream_t
typedef stream_t *(* stream_constructor_t)(char *uri)
typedef bool(* stream_cb_t)(void *data, stream_t *stream)
Functions
stream_t * stream_create_from_fd (int fd)
Detailed Description
Typedef Documentation
typedef bool(* stream_cb_t)(void *data, stream_t *stream)
Callback function prototype, called when stream is ready.
It is not allowed to destroy the stream nor to call on_read()/on_write/() during the callback.
As select() may return even if a read()/write() would actually block, it is recommended to use the non-blocking calls and handle return values appropriately.
Parameters
data data passed during callback registration
stream associated stream
Returns
FALSE unregisters the invoked callback, TRUE keeps it
Definition at line 50 of file stream.h.
typedef stream_t*(* stream_constructor_t)(char *uri)
Constructor function prototype for stream_t.
Parameters
uri URI to create a stream for
Returns
stream instance, NULL on error
Definition at line 34 of file stream.h.
typedef struct stream_t stream_t
Definition at line 24 of file stream.h.
Function Documentation
stream_t* stream_create_from_fd (int fd)
Create a stream from a file descriptor.
The file descriptor MUST be a socket for non-blocking operation.
Parameters
fd file descriptor to wrap into a stream_t
Returns
stream instance
See header
Definition at line 271 of file stream.c.
References INIT.
Referenced by accept_async(), stream_create_tcp(), and stream_create_unix().
 {
     private_stream_t *this;
     INIT(this,
         .public = {
             .read = _read_,
             .read_all = _read_all,
             .on_read = _on_read,
             .write = _write_,
             .write_all = _write_all,
             .on_write = _on_write,
             .get_file = _get_file,
             .destroy = _destroy,
         },
         .fd = fd,
     );
     return &this->public;
 }