strongSwan: pa_tnc_attr_t Struct Reference
pa_tnc_attr_t Struct Reference
pa_tnc_attr
#include "pa_tnc_attr.h"
Public Attributes
pen_type_t(* get_type)(pa_tnc_attr_t *this)
chunk_t(* get_value)(pa_tnc_attr_t *this)
bool(* get_noskip_flag)(pa_tnc_attr_t *this)
void(* set_noskip_flag)(pa_tnc_attr_t *this, bool noskip)
void(* build)(pa_tnc_attr_t *this)
status_t(* process)(pa_tnc_attr_t *this, uint32_t *offset)
void(* add_segment)(pa_tnc_attr_t *this, chunk_t segment)
pa_tnc_attr_t *(* get_ref)(pa_tnc_attr_t *this)
void(* destroy)(pa_tnc_attr_t *this)
Detailed Description
Interface for an RFC 5792 PA-TNC Posture Attribute.
Definition at line 39 of file pa_tnc_attr.h.
Member Data Documentation
void(* pa_tnc_attr_t::add_segment)(pa_tnc_attr_t *this, chunk_t segment)
Add a data segment to an attribute allowing incremental processing
Parameters
segment data segment to be appended
Definition at line 87 of file pa_tnc_attr.h.
Referenced by START_TEST().
void(* pa_tnc_attr_t::build)(pa_tnc_attr_t *this)
Build value of an PA-TNC attribute from its parameters
Definition at line 72 of file pa_tnc_attr.h.
Referenced by METHOD(), seg_env_create(), and START_TEST().
void(* pa_tnc_attr_t::destroy)(pa_tnc_attr_t *this)
Destroys a pa_tnc_attr_t object.
Definition at line 99 of file pa_tnc_attr.h.
Referenced by add_port_filter(), METHOD(), seg_env_create(), and START_TEST().
bool(* pa_tnc_attr_t::get_noskip_flag)(pa_tnc_attr_t *this)
Get the noskip flag
Returns
TRUE if the noskip flag is set
Definition at line 60 of file pa_tnc_attr.h.
Referenced by METHOD(), and START_TEST().
pa_tnc_attr_t*(* pa_tnc_attr_t::get_ref)(pa_tnc_attr_t *this)
Get a new reference to the PA-TNC attribute
Returns
this, with an increased refcount
Definition at line 94 of file pa_tnc_attr.h.
Referenced by METHOD(), receive_msg(), and START_TEST().
pen_type_t(* pa_tnc_attr_t::get_type)(pa_tnc_attr_t *this)
Get the vendor ID/type of an PA-TNC attribute
Returns
vendor-specific attribute type
Definition at line 46 of file pa_tnc_attr.h.
Referenced by imc_attestation_process(), imv_attestation_process(), METHOD(), receive_message(), receive_msg(), and START_TEST().
chunk_t(* pa_tnc_attr_t::get_value)(pa_tnc_attr_t *this)
Get the value of an PA-TNC attribute
Returns
attribute value
Definition at line 53 of file pa_tnc_attr.h.
Referenced by imc_attestation_process(), METHOD(), receive_msg(), seg_env_create(), and START_TEST().
status_t(* pa_tnc_attr_t::process)(pa_tnc_attr_t *this, uint32_t *offset)
Process the value of an PA-TNC attribute to extract its parameters
Parameters
offset relative error offset within attribute body
Returns
result status
Definition at line 80 of file pa_tnc_attr.h.
Referenced by METHOD(), and START_TEST().
void(* pa_tnc_attr_t::set_noskip_flag)(pa_tnc_attr_t *this, bool noskip)
Set the noskip flag
Parameters
noskip_flag TRUE if the noskip flag is to be set
Definition at line 67 of file pa_tnc_attr.h.
Referenced by add_port_filter(), create_message(), imc_attestation_process(), imv_attestation_build(), METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
pa_tnc_attr.h