strongSwan: ntru_poly_t Struct Reference
ntru_poly_t Struct Reference
ntru_poly
#include "ntru_poly.h"
Public Attributes
size_t(* get_size)(ntru_poly_t *this)
uint16_t *(* get_indices)(ntru_poly_t *this)
void(* get_array)(ntru_poly_t *this, uint16_t *array)
void(* ring_mult)(ntru_poly_t *this, uint16_t *a, uint16_t *c)
void(* destroy)(ntru_poly_t *this)
Detailed Description
Implements a trinary polynomial storing the indices of non-zero coefficients
Definition at line 31 of file ntru_poly.h.
Member Data Documentation
void(* ntru_poly_t::destroy)(ntru_poly_t *this)
Destroy ntru_poly_t object
Definition at line 62 of file ntru_poly.h.
Referenced by METHOD(), ntru_private_key_create(), and START_TEST().
void(* ntru_poly_t::get_array)(ntru_poly_t *this, uint16_t *array)
Parameters
array array containing all N coefficients of the polynomial
Definition at line 48 of file ntru_poly.h.
Referenced by START_TEST().
uint16_t*(* ntru_poly_t::get_indices)(ntru_poly_t *this)
Returns
array containing the indices of the non-zero coefficients
Definition at line 43 of file ntru_poly.h.
Referenced by START_TEST().
size_t(* ntru_poly_t::get_size)(ntru_poly_t *this)
Get the size of the indices array
Returns
number of indices
Definition at line 38 of file ntru_poly.h.
Referenced by START_TEST().
void(* ntru_poly_t::ring_mult)(ntru_poly_t *this, uint16_t *a, uint16_t *c)
Multiply polynomial a with ntru_poly_t object b having sparse coeffients to form result polynomial c = a * b
Parameters
a input polynomial a
b output polynomial c
Definition at line 57 of file ntru_poly.h.
Referenced by METHOD(), ntru_private_key_create(), and START_TEST().
The documentation for this struct was generated from the following file:
ntru_poly.h