strongSwan: attr_plugin.c File Reference
attr_plugin.c File Reference
#include "attr_plugin.h"
#include "attr_provider.h"
#include <daemon.h>
Classes
struct private_attr_plugin_t
Typedefs
typedef struct
private_attr_plugin_t private_attr_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_attr_plugin_t *this)
static bool plugin_cb (private_attr_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_attr_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, reload, bool, private_attr_plugin_t *this)
METHOD (plugin_t, destroy, void, private_attr_plugin_t *this)
plugin_t * attr_plugin_create ()
Typedef Documentation
typedef struct private_attr_plugin_t private_attr_plugin_t
Definition at line 21 of file attr_plugin.c.
Function Documentation
plugin_t* attr_plugin_create ()
Definition at line 92 of file attr_plugin.c.
References attr_provider_create(), and INIT.
 {
     private_attr_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .reload = _reload,
                 .destroy = _destroy,
             },
         },
         .provider = attr_provider_create(),
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_attr_plugin_t * this)
Definition at line 39 of file attr_plugin.c.
 {
     return "attr";
 }
METHOD (plugin_t , get_features , int , private_attr_plugin_t * this, plugin_feature_t * features[])
Definition at line 64 of file attr_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "attr"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , reload , bool , private_attr_plugin_t * this)
Definition at line 75 of file attr_plugin.c.
References TRUE.
 {
     this->provider->reload(this->provider);
     return TRUE;
 }
METHOD (plugin_t , destroy , void , private_attr_plugin_t * this)
Definition at line 82 of file attr_plugin.c.
References free().
 {
     this->provider->destroy(this->provider);
     free(this);
 }
static bool plugin_cb (private_attr_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register provider
Definition at line 48 of file attr_plugin.c.
References attribute_manager_t::add_provider, daemon_t::attributes, charon, attribute_manager_t::remove_provider, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->attributes->add_provider(charon->attributes,
                                          &this->provider->provider);
     }
     else
     {
         charon->attributes->remove_provider(charon->attributes,
                                             &this->provider->provider);
     }
     return TRUE;
 }