strongSwan: pa_tnc_msg.c File Reference
pa_tnc_msg.c File Reference
#include "imcv.h"
#include "pa_tnc_msg.h"
#include "ietf/ietf_attr_pa_tnc_error.h"
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <collections/linked_list.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct private_pa_tnc_msg_t
Macros
#define PA_TNC_RESERVED 0x000000
Typedefs
typedef struct private_pa_tnc_msg_t private_pa_tnc_msg_t
Functions
METHOD (pa_tnc_msg_t, get_encoding, chunk_t, private_pa_tnc_msg_t *this)
METHOD (pa_tnc_msg_t, get_space, size_t, private_pa_tnc_msg_t *this)
METHOD (pa_tnc_msg_t, add_attribute, bool, private_pa_tnc_msg_t *this, pa_tnc_attr_t *attr)
METHOD (pa_tnc_msg_t, build, bool, private_pa_tnc_msg_t *this)
METHOD (pa_tnc_msg_t, process, status_t, private_pa_tnc_msg_t *this)
METHOD (pa_tnc_msg_t, process_ietf_std_errors, bool, private_pa_tnc_msg_t *this, linked_list_t *non_fatal_types)
METHOD (pa_tnc_msg_t, create_attribute_enumerator, enumerator_t *, private_pa_tnc_msg_t *this)
METHOD (pa_tnc_msg_t, create_error_enumerator, enumerator_t *, private_pa_tnc_msg_t *this)
METHOD (pa_tnc_msg_t, destroy, void, private_pa_tnc_msg_t *this)
pa_tnc_msg_t * pa_tnc_msg_create (size_t max_msg_len)
pa_tnc_msg_t * pa_tnc_msg_create_from_data (chunk_t data)
Macro Definition Documentation
#define PA_TNC_RESERVED 0x000000
PA-TNC message header
                 1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Version | Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Message Identifier | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 40 of file pa_tnc_msg.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pa_tnc_msg_t private_pa_tnc_msg_t
Definition at line 26 of file pa_tnc_msg.c.
Function Documentation
METHOD (pa_tnc_msg_t , get_encoding , chunk_t , private_pa_tnc_msg_t * this)
Definition at line 89 of file pa_tnc_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pa_tnc_msg_t , get_space , size_t , private_pa_tnc_msg_t * this)
Definition at line 95 of file pa_tnc_msg.c.
 {
     return this->max_msg_len ? this->max_msg_len - this->msg_len : 0;
 }
METHOD (pa_tnc_msg_t , add_attribute , bool , private_pa_tnc_msg_t * this, pa_tnc_attr_t * attr)
Definition at line 101 of file pa_tnc_msg.c.
References attributes, pa_tnc_attr_t::build, FALSE, pa_tnc_attr_t::get_value, chunk_t::len, PA_TNC_ATTR_HEADER_SIZE, and TRUE.
 {
     chunk_t attr_value;
     size_t attr_len;
     if (!this->from_data)
     {
         attr->build(attr);
         attr_value = attr->get_value(attr);
         attr_len = PA_TNC_ATTR_HEADER_SIZE + attr_value.len;
         if (this->max_msg_len && this->msg_len + attr_len > this->max_msg_len)
         {
             /* attribute just does not fit into this message */
             return FALSE;
         }
         this->msg_len += attr_len;
     }
     this->attributes->insert_last(this->attributes, attr);
     return TRUE;
 }
METHOD (pa_tnc_msg_t , build , bool , private_pa_tnc_msg_t * this)
Definition at line 124 of file pa_tnc_msg.c.
References attributes, bio_writer_create(), crypto_factory_t::create_nonce_gen, library_t::crypto, DBG1, DBG2, DBG3, DBG_TNC, enumerator_t::destroy, nonce_gen_t::destroy, bio_writer_t::destroy, DESTROY_IF, encoding, enumerator_t::enumerate, bio_writer_t::extract_buf, FALSE, flags, free(), pa_tnc_attr_manager_t::get_names, nonce_gen_t::get_nonce, pa_tnc_attr_t::get_noskip_flag, pa_tnc_attr_t::get_type, pa_tnc_attr_t::get_value, identifier, imcv_pa_tnc_attributes, chunk_t::len, lib, PA_TNC_ATTR_FLAG_NONE, PA_TNC_ATTR_FLAG_NOSKIP, PA_TNC_ATTR_HEADER_SIZE, PA_TNC_RESERVED, PA_TNC_VERSION, pen_names, TRUE, type, pen_type_t::type, value, pen_type_t::vendor_id, bio_writer_t::write_data, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     pa_tnc_attr_t *attr;
     enum_name_t *pa_attr_names;
     pen_type_t type;
     uint8_t flags;
     chunk_t value;
     nonce_gen_t *ng;
     /* generate a nonce as a message identifier */
     ng = lib->crypto->create_nonce_gen(lib->crypto);
     if (!ng || !ng->get_nonce(ng, 4, (uint8_t*)&this->identifier))
     {
         DBG1(DBG_TNC, "failed to generate random PA-TNC message identifier");
         DESTROY_IF(ng);
         return FALSE;
     }
     ng->destroy(ng);
     DBG1(DBG_TNC, "creating PA-TNC message with ID 0x%08x", this->identifier);
     /* build message header */
     writer = bio_writer_create(this->msg_len);
     writer->write_uint8 (writer, PA_TNC_VERSION);
     writer->write_uint24(writer, PA_TNC_RESERVED);
     writer->write_uint32(writer, this->identifier);
     /* append encoded value of PA-TNC attributes */
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &attr))
     {
         type  = attr->get_type(attr);
         value = attr->get_value(attr);
         flags = attr->get_noskip_flag(attr) ? PA_TNC_ATTR_FLAG_NOSKIP :
                                               PA_TNC_ATTR_FLAG_NONE;
         pa_attr_names = imcv_pa_tnc_attributes->get_names(imcv_pa_tnc_attributes,
                                                           type.vendor_id);
         if (pa_attr_names)
         {
             DBG2(DBG_TNC, "creating PA-TNC attribute type '%N/%N' "
                           "0x%06x/0x%08x", pen_names, type.vendor_id,
                            pa_attr_names, type.type, type.vendor_id, type.type);
         }
         else
         {
             DBG2(DBG_TNC, "creating PA-TNC attribute type '%N' "
                           "0x%06x/0x%08x", pen_names, type.vendor_id,
                            type.vendor_id, type.type);
         }
         DBG3(DBG_TNC, "%B", &value);
         writer->write_uint8 (writer, flags);
         writer->write_uint24(writer, type.vendor_id);
         writer->write_uint32(writer, type.type);
         writer->write_uint32(writer, PA_TNC_ATTR_HEADER_SIZE + value.len);
         writer->write_data  (writer, value);
     }
     enumerator->destroy(enumerator);
     free(this->encoding.ptr);
     this->encoding = writer->extract_buf(writer);
     writer->destroy(writer);
     return TRUE;
 }
METHOD (pa_tnc_msg_t , process , status_t , private_pa_tnc_msg_t * this)
Definition at line 193 of file pa_tnc_msg.c.
References attributes, bio_reader_create(), pa_tnc_attr_manager_t::create, DBG1, DBG_TNC, pa_tnc_attr_t::destroy, bio_reader_t::destroy, encoding, error_code, FAILED, FALSE, pa_tnc_attr_t::get_type, pa_tnc_attr_t::get_value, identifier, IETF_ATTR_PA_TNC_ERROR, ietf_attr_pa_tnc_error_create(), ietf_attr_pa_tnc_error_create_with_offset(), imcv_pa_tnc_attributes, chunk_t::len, offset, PA_ERROR_INVALID_PARAMETER, PA_ERROR_VERSION_NOT_SUPPORTED, PA_TNC_HEADER_SIZE, PA_TNC_VERSION, PEN_IETF, pen_type_create(), pa_tnc_attr_t::process, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, SUCCESS, pen_type_t::type, pen_type_t::vendor_id, VERIFY_ERROR, and version.
 {
     bio_reader_t *reader;
     pa_tnc_attr_t *attr, *error;
     pen_type_t attr_type;
     chunk_t attr_value;
     uint8_t version;
     uint32_t reserved, offset, attr_offset;
     pen_type_t error_code = { PEN_IETF, PA_ERROR_INVALID_PARAMETER };
     /* process message header */
     if (this->encoding.len < PA_TNC_HEADER_SIZE)
     {
         DBG1(DBG_TNC, "%u bytes insufficient to parse PA-TNC message header",
                        this->encoding.len);
         return FAILED;
     }
     reader = bio_reader_create(this->encoding);
     reader->read_uint8 (reader, &version);
     reader->read_uint24(reader, &reserved);
     reader->read_uint32(reader, &this->identifier);
     DBG1(DBG_TNC, "processing PA-TNC message with ID 0x%08x", this->identifier);
     if (version != PA_TNC_VERSION)
     {
         DBG1(DBG_TNC, "PA-TNC version %u not supported", version);
         error_code = pen_type_create(PEN_IETF, PA_ERROR_VERSION_NOT_SUPPORTED);
         error = ietf_attr_pa_tnc_error_create(error_code, this->encoding);
         goto err;
     }
     /* offset of the first PA-TNC attribute in the PA-TNC message */
     offset = PA_TNC_HEADER_SIZE;
     /* pre-process PA-TNC attributes */
     while (reader->remaining(reader) > 0)
     {
         attr = imcv_pa_tnc_attributes->create(imcv_pa_tnc_attributes,
                             reader, FALSE, &offset, this->encoding, &error);
         if (!attr)
         {
             if (error)
             {
                 goto err;
             }
             else
             {
                 continue;
             }
         }
         attr_value = attr->get_value(attr);
         attr_type  = attr->get_type(attr);
         if (attr->process(attr, &attr_offset) != SUCCESS)
         {
             attr->destroy(attr);
             if (attr_type.vendor_id == PEN_IETF &&
                 attr_type.type == IETF_ATTR_PA_TNC_ERROR)
             {
                 /* suppress error while processing a PA-TNC error attribute */
                 offset += attr_value.len;
                 continue;
             }
             error_code = pen_type_create(PEN_IETF, PA_ERROR_INVALID_PARAMETER);
             error = ietf_attr_pa_tnc_error_create_with_offset(error_code,
                                     this->encoding, offset + attr_offset);
             goto err;
         }
         offset += attr_value.len;
         this->attributes->insert_last(this->attributes, attr);
     }
     reader->destroy(reader);
     return SUCCESS;
 err:
     reader->destroy(reader);
     this->errors->insert_last(this->errors, error);
     return VERIFY_ERROR;
 }
METHOD (pa_tnc_msg_t , process_ietf_std_errors , bool , private_pa_tnc_msg_t * this, linked_list_t * non_fatal_types)
Definition at line 275 of file pa_tnc_msg.c.
References attributes, linked_list_t::create_enumerator, DBG1, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, error_code, FALSE, flags, ietf_attr_pa_tnc_error_t::get_error_code, ietf_attr_pa_tnc_error_t::get_msg_info, pa_tnc_attr_manager_t::get_names, ietf_attr_pa_tnc_error_t::get_offset, pa_tnc_attr_t::get_type, ietf_attr_pa_tnc_error_t::get_unsupported_attr, IETF_ATTR_PA_TNC_ERROR, imcv_pa_tnc_attributes, offset, PA_ERROR_ATTR_TYPE_NOT_SUPPORTED, PA_ERROR_INVALID_PARAMETER, pa_tnc_error_code_names, PEN_IETF, pen_names, pen_type_equals(), chunk_t::ptr, TRUE, type, pen_type_t::type, untoh32(), and pen_type_t::vendor_id.
 {
     enumerator_t *e1, *e2;
     enum_name_t *pa_attr_names;
     pa_tnc_attr_t *attr;
     pen_type_t type, unsupported_type;
     uint8_t flags;
     bool fatal_error = FALSE;
     e1 = this->attributes->create_enumerator(this->attributes);
     while (e1->enumerate(e1, &attr))
     {
         type = attr->get_type(attr);
         if (type.vendor_id == PEN_IETF && type.type == IETF_ATTR_PA_TNC_ERROR)
         {
             ietf_attr_pa_tnc_error_t *error_attr;
             pen_type_t error_code, *non_fatal_type;
             chunk_t msg_info;
             uint32_t offset;
             bool fatal_current_error = TRUE;
             error_attr = (ietf_attr_pa_tnc_error_t*)attr;
             error_code = error_attr->get_error_code(error_attr);
             msg_info = error_attr->get_msg_info(error_attr);
             /* skip errors from non-IETF namespaces */
             if (error_code.vendor_id != PEN_IETF)
             {
                 continue;
             }
             DBG1(DBG_TNC, "received PA-TNC error '%N' concerning message "
                  "0x%08x/0x%08x", pa_tnc_error_code_names, error_code.type,
                  untoh32(msg_info.ptr), untoh32(msg_info.ptr + 4));
             switch (error_code.type)
             {
                 case PA_ERROR_INVALID_PARAMETER:
                     offset = error_attr->get_offset(error_attr);
                     DBG1(DBG_TNC, "  occurred at offset of %u bytes", offset);
                     break;
                 case PA_ERROR_ATTR_TYPE_NOT_SUPPORTED:
                     unsupported_type =
                         error_attr->get_unsupported_attr(error_attr, &flags);
                     pa_attr_names =
                         imcv_pa_tnc_attributes->get_names(imcv_pa_tnc_attributes,
                                                     unsupported_type.vendor_id);
                     if (pa_attr_names)
                     {
                         DBG1(DBG_TNC, "  unsupported attribute type '%N/%N' "
                              "0x%06x/0x%08x, flags 0x%02x",
                              pen_names, unsupported_type.vendor_id,
                              pa_attr_names, unsupported_type.type,
                              unsupported_type.vendor_id, unsupported_type.type,
                              flags);
                     }
                     else
                     {
                         DBG1(DBG_TNC, "  unsupported attribute type '%N' "
                              "0x%06x/0x%08x, flags 0x%02x",
                              pen_names, unsupported_type.vendor_id,
                              unsupported_type.vendor_id, unsupported_type.type,
                              flags);
                     }
                     e2 = non_fatal_types->create_enumerator(non_fatal_types);
                     while (e2->enumerate(e2, &non_fatal_type))
                     {
                         if (pen_type_equals(unsupported_type, *non_fatal_type))
{
                             fatal_current_error = FALSE;
                             break;
                         }
                     }
                     e2->destroy(e2);
                     break;
                 default:
                     break;
             }
             if (fatal_current_error)
             {
                 fatal_error = TRUE;
             }
         }
     }
     e1->destroy(e1);
     return fatal_error;
 }
METHOD (pa_tnc_msg_t , create_attribute_enumerator , enumerator_t * , private_pa_tnc_msg_t * this)
Definition at line 365 of file pa_tnc_msg.c.
References attributes.
 {
     return this->attributes->create_enumerator(this->attributes);
 }
METHOD (pa_tnc_msg_t , create_error_enumerator , enumerator_t * , private_pa_tnc_msg_t * this)
Definition at line 371 of file pa_tnc_msg.c.
 {
     return this->errors->create_enumerator(this->errors);
 }
METHOD (pa_tnc_msg_t , destroy , void , private_pa_tnc_msg_t * this)
Definition at line 377 of file pa_tnc_msg.c.
References attributes, destroy(), encoding, and free().
 {
     this->attributes->destroy_offset(this->attributes,
                                      offsetof(pa_tnc_attr_t, destroy));
     this->errors->destroy_offset(this->errors,
                                      offsetof(pa_tnc_attr_t, destroy));
     free(this->encoding.ptr);
     free(this);
 }