strongSwan: duplicheck_notify.c File Reference
duplicheck_notify.c File Reference
#include "duplicheck_notify.h"
#include "duplicheck_msg.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <errno.h>
#include <daemon.h>
#include <threading/mutex.h>
#include <threading/thread.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_duplicheck_notify_t
Typedefs
typedef struct
private_duplicheck_notify_t private_duplicheck_notify_t
Functions
static bool on_accept (private_duplicheck_notify_t *this, stream_t *stream)
METHOD (duplicheck_notify_t, send_, void, private_duplicheck_notify_t *this, identification_t *id)
METHOD (duplicheck_notify_t, destroy, void, private_duplicheck_notify_t *this)
duplicheck_notify_t * duplicheck_notify_create ()
Variables
struct private_duplicheck_notify_t __attribute__
Typedef Documentation
typedef struct private_duplicheck_notify_t private_duplicheck_notify_t
Definition at line 33 of file duplicheck_notify.c.
Function Documentation
METHOD (duplicheck_notify_t , send_ , void , private_duplicheck_notify_t * this, identification_t * id)
Definition at line 73 of file duplicheck_notify.c.
References DBG1, DBG_CFG, enumerator_t::destroy, stream_t::destroy, enumerator_t::enumerate, len, mutex_t::lock, mutex, snprintf, strerror, mutex_t::unlock, and stream_t::write_all.
 {
     enumerator_t *enumerator;
     stream_t *stream;
     u_int16_t nlen;
     char buf[512];
     int len;
     len = snprintf(buf, sizeof(buf), "%Y", id);
     if (len > 0 && len < sizeof(buf))
     {
         nlen = htons(len);
         this->mutex->lock(this->mutex);
         enumerator = this->connected->create_enumerator(this->connected);
         while (enumerator->enumerate(enumerator, &stream))
         {
             if (!stream->write_all(stream, &nlen, sizeof(nlen)) ||
                 !stream->write_all(stream, buf, len))
             {
                 DBG1(DBG_CFG, "sending duplicheck notify failed: %s",
                      strerror(errno));
                 this->connected->remove_at(this->connected, enumerator);
                 stream->destroy(stream);
             }
         }
         enumerator->destroy(enumerator);
         this->mutex->unlock(this->mutex);
     }
 }
METHOD (duplicheck_notify_t , destroy , void , private_duplicheck_notify_t * this)
Definition at line 105 of file duplicheck_notify.c.
References mutex_t::destroy, destroy(), DESTROY_IF, free(), and mutex.
 {
     DESTROY_IF(this->service);
     this->connected->destroy_offset(this->connected, offsetof(stream_t, destroy));
     this->mutex->destroy(this->mutex);
     free(this);
 }
static bool on_accept (private_duplicheck_notify_t * this, stream_t * stream) static
Accept duplicheck notification connections
Definition at line 64 of file duplicheck_notify.c.
References mutex_t::lock, mutex, TRUE, and mutex_t::unlock.
Referenced by duplicheck_notify_create(), and vici_socket_create().
 {
     this->mutex->lock(this->mutex);
     this->connected->insert_last(this->connected, stream);
     this->mutex->unlock(this->mutex);
     return TRUE;
 }
Variable Documentation
struct private_duplicheck_notify_t __attribute__