strongSwan: hmac_plugin.c File Reference
hmac_plugin.c File Reference
#include "hmac_plugin.h"
#include <library.h>
#include "hmac.h"
Classes
struct private_hmac_plugin_t
Typedefs
typedef struct
private_hmac_plugin_t private_hmac_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_hmac_plugin_t *this)
METHOD (plugin_t, get_features, int, private_hmac_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_hmac_plugin_t *this)
plugin_t * hmac_plugin_create ()
Typedef Documentation
typedef struct private_hmac_plugin_t private_hmac_plugin_t
Definition at line 21 of file hmac_plugin.c.
Function Documentation
plugin_t* hmac_plugin_create ()
Definition at line 92 of file hmac_plugin.c.
References INIT.
 {
     private_hmac_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_hmac_plugin_t * this)
Definition at line 34 of file hmac_plugin.c.
 {
     return "hmac";
 }
METHOD (plugin_t , get_features , int , private_hmac_plugin_t * this, plugin_feature_t * features[])
Definition at line 40 of file hmac_plugin.c.
References AUTH_HMAC_MD5_128, AUTH_HMAC_MD5_96, AUTH_HMAC_SHA1_128, AUTH_HMAC_SHA1_160, AUTH_HMAC_SHA1_96, AUTH_HMAC_SHA2_256_128, AUTH_HMAC_SHA2_256_256, AUTH_HMAC_SHA2_384_192, AUTH_HMAC_SHA2_384_384, AUTH_HMAC_SHA2_512_256, AUTH_HMAC_SHA2_512_512, countof, HASH_MD5, HASH_SHA1, HASH_SHA256, HASH_SHA384, HASH_SHA512, hmac_prf_create(), hmac_signer_create(), PLUGIN_DEPENDS, PLUGIN_PROVIDE, PLUGIN_REGISTER, PRF_HMAC_MD5, PRF_HMAC_SHA1, PRF_HMAC_SHA2_256, PRF_HMAC_SHA2_384, and PRF_HMAC_SHA2_512.
 {
     static plugin_feature_t f[] = {
         PLUGIN_REGISTER(PRF, hmac_prf_create),
             PLUGIN_PROVIDE(PRF, PRF_HMAC_SHA1),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA1),
             PLUGIN_PROVIDE(PRF, PRF_HMAC_MD5),
                 PLUGIN_DEPENDS(HASHER,  HASH_MD5),
             PLUGIN_PROVIDE(PRF, PRF_HMAC_SHA2_256),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA256),
             PLUGIN_PROVIDE(PRF, PRF_HMAC_SHA2_384),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA384),
             PLUGIN_PROVIDE(PRF, PRF_HMAC_SHA2_512),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA512),
         PLUGIN_REGISTER(SIGNER, hmac_signer_create),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA1_96),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA1),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA1_128),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA1),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA1_160),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA1),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_MD5_96),
                 PLUGIN_DEPENDS(HASHER,  HASH_MD5),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_MD5_128),
                 PLUGIN_DEPENDS(HASHER,  HASH_MD5),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA2_256_128),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA256),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA2_256_256),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA256),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA2_384_192),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA384),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA2_384_384),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA384),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA2_512_256),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA512),
             PLUGIN_PROVIDE(SIGNER, AUTH_HMAC_SHA2_512_512),
                 PLUGIN_DEPENDS(HASHER,  HASH_SHA512),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_hmac_plugin_t * this)
Definition at line 83 of file hmac_plugin.c.
References free().
 {
     free(this);
 }