strongSwan: pgp_public_key
pgp_public_key
pgp
Functions
public_key_t * pgp_public_key_load (key_type_t type, va_list args)
private_key_t * pgp_private_key_load (key_type_t type, va_list args)
Detailed Description
Function Documentation
private_key_t* pgp_private_key_load (key_type_t type, va_list args)
Load a generic or RSA private key using PGP decoding.
Parameters
type type of the key, either KEY_ANY or KEY_RSA
args builder_part_t argument list
Returns
builder instance
See header.
Definition at line 248 of file pgp_builder.c.
References blob, BUILD_BLOB_PGP, BUILD_END, chunk_empty, KEY_ANY, KEY_RSA, parse_private_key(), parse_rsa_private_key(), and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_PGP:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     switch (type)
     {
         case KEY_ANY:
             return parse_private_key(blob);
         case KEY_RSA:
             return parse_rsa_private_key(blob);
         default:
             return NULL;
     }
 }
public_key_t* pgp_public_key_load (key_type_t type, va_list args)
Load a generic or an RSA public key using PGP decoding.
Parameters
type type of the key, either KEY_ANY or KEY_RSA
args builder_part_t argument list
Returns
private key, NULL if failed
See header.
Definition at line 216 of file pgp_builder.c.
References blob, BUILD_BLOB_PGP, BUILD_END, chunk_empty, KEY_ANY, KEY_RSA, parse_public_key(), parse_rsa_public_key(), and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_PGP:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     switch (type)
     {
         case KEY_ANY:
             return parse_public_key(blob);
         case KEY_RSA:
             return parse_rsa_public_key(blob);
         default:
             return NULL;
     }
 }