strongSwan: addrblock_plugin.c File Reference
addrblock_plugin.c File Reference
#include "addrblock_plugin.h"
#include <daemon.h>
#include <plugins/plugin_feature.h>
#include "addrblock_validator.h"
#include "addrblock_narrow.h"
Classes
struct private_addrblock_plugin_t
Typedefs
typedef struct
private_addrblock_plugin_t private_addrblock_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_addrblock_plugin_t *this)
static bool plugin_cb (private_addrblock_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_addrblock_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_addrblock_plugin_t *this)
plugin_t * addrblock_plugin_create ()
Typedef Documentation
typedef struct private_addrblock_plugin_t private_addrblock_plugin_t
Definition at line 24 of file addrblock_plugin.c.
Function Documentation
plugin_t* addrblock_plugin_create ()
Definition at line 96 of file addrblock_plugin.c.
References addrblock_narrow_create(), addrblock_validator_create(), and INIT.
 {
     private_addrblock_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .validator = addrblock_validator_create(),
         .narrower = addrblock_narrow_create(),
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_addrblock_plugin_t * this)
Definition at line 47 of file addrblock_plugin.c.
 {
     return "addrblock";
 }
METHOD (plugin_t , get_features , int , private_addrblock_plugin_t * this, plugin_feature_t * features[])
Definition at line 73 of file addrblock_plugin.c.
References CERT_X509, countof, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_PROVIDE, and PLUGIN_SDEPEND.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "addrblock"),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_addrblock_plugin_t * this)
Definition at line 85 of file addrblock_plugin.c.
References free().
 {
     this->narrower->destroy(this->narrower);
     this->validator->destroy(this->validator);
     free(this);
 }
static bool plugin_cb (private_addrblock_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 56 of file addrblock_plugin.c.
References bus_t::add_listener, credential_manager_t::add_validator, daemon_t::bus, charon, library_t::credmgr, lib, bus_t::remove_listener, credential_manager_t::remove_validator, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         lib->credmgr->add_validator(lib->credmgr, &this->validator->validator);
         charon->bus->add_listener(charon->bus, &this->narrower->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->narrower->listener);
         lib->credmgr->remove_validator(lib->credmgr,
                                        &this->validator->validator);
     }
     return TRUE;
 }