strongSwan: kernel_pfroute_net
kernel_pfroute_net
kernel_pfroute
Classes
struct kernel_pfroute_net_t
Typedefs
typedef struct kernel_pfroute_net_t kernel_pfroute_net_t
Functions
kernel_pfroute_net_t * kernel_pfroute_net_create ()
Detailed Description
Typedef Documentation
typedef struct kernel_pfroute_net_t kernel_pfroute_net_t
Definition at line 26 of file kernel_pfroute_net.h.
Function Documentation
kernel_pfroute_net_t* kernel_pfroute_net_create ()
Create a PF_ROUTE kernel net interface instance.
Returns
kernel_pfroute_net_t instance
Definition at line 1828 of file kernel_pfroute_net.c.
References watcher_t::add, addr_map_entry_equals(), addr_map_entry_hash(), condvar_create(), CONDVAR_TYPE_DEFAULT, DBG1, DBG_KNL, destroy(), settings_t::get_bool, settings_t::get_int, hashtable_create(), INIT, init_address_list(), lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, net_change_equals(), net_change_hash(), library_t::ns, receive_events(), route_entry_equals(), route_entry_hash(), rwlock_create(), RWLOCK_TYPE_DEFAULT, library_t::settings, SHUT_RD, shutdown, socket, spinlock_create(), streq(), strerror, SUCCESS, TRUE, library_t::watcher, and WATCHER_READ.
Referenced by METHOD().
 {
     private_kernel_pfroute_net_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_features = _get_features,
                 .get_interface = _get_interface_name,
                 .create_address_enumerator = _create_address_enumerator,
                 .get_source_addr = _get_source_addr,
                 .get_nexthop = _get_nexthop,
                 .add_ip = _add_ip,
                 .del_ip = _del_ip,
                 .add_route = _add_route,
                 .del_route = _del_route,
                 .destroy = _destroy,
             },
         },
         .pid = getpid(),
         .ifaces = linked_list_create(),
         .addrs = hashtable_create(
                                 (hashtable_hash_t)addr_map_entry_hash,
                                 (hashtable_equals_t)addr_map_entry_equals, 16),
         .routes = hashtable_create((hashtable_hash_t)route_entry_hash,
                                    (hashtable_equals_t)route_entry_equals, 16),
         .net_changes = hashtable_create(
                                    (hashtable_hash_t)net_change_hash,
                                    (hashtable_equals_t)net_change_equals, 16),
         .tuns = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .routes_lock = mutex_create(MUTEX_TYPE_DEFAULT),
         .net_changes_lock = mutex_create(MUTEX_TYPE_DEFAULT),
         .roam_lock = spinlock_create(),
         .vip_wait = lib->settings->get_int(lib->settings,
                         "%s.plugins.kernel-pfroute.vip_wait", 1000, lib->ns),
         .install_virtual_ip = lib->settings->get_bool(lib->settings,
                         "%s.install_virtual_ip", TRUE, lib->ns),
     );
     timerclear(&this->last_route_reinstall);
     timerclear(&this->next_roam);
     /* create a PF_ROUTE socket to communicate with the kernel */
     this->socket = socket(PF_ROUTE, SOCK_RAW, AF_UNSPEC);
     if (this->socket == -1)
     {
         DBG1(DBG_KNL, "unable to create PF_ROUTE socket");
         destroy(this);
         return NULL;
     }
     if (streq(lib->ns, "starter"))
     {
         /* starter has no threads, so we do not register for kernel events */
         if (shutdown(this->socket, SHUT_RD) != 0)
         {
             DBG1(DBG_KNL, "closing read end of PF_ROUTE socket failed: %s",
                  strerror(errno));
         }
     }
     else
     {
         lib->watcher->add(lib->watcher, this->socket, WATCHER_READ,
                           (watcher_cb_t)receive_events, this);
     }
     if (init_address_list(this) != SUCCESS)
     {
         DBG1(DBG_KNL, "unable to get interface list");
         destroy(this);
         return NULL;
     }
     return &this->public;
 }