strongSwan: imv_session_t Struct Reference
imv_session_t Struct Reference
imv_session
#include "imv_session.h"
Public Attributes
void(* set_session_id)(imv_session_t *this, int session_id, int pid, int did)
int(* get_session_id)(imv_session_t *this, int *pid, int *did)
TNC_ConnectionID(* get_connection_id)(imv_session_t *this)
time_t(* get_creation_time)(imv_session_t *this)
enumerator_t *(* create_ar_identities_enumerator)(imv_session_t *this)
imv_os_info_t *(* get_os_info)(imv_session_t *this)
void(* set_device_id)(imv_session_t *this, chunk_t device_id)
bool(* get_device_id)(imv_session_t *this, chunk_t *device_id)
void(* set_device_trust)(imv_session_t *this, bool trusted)
bool(* get_device_trust)(imv_session_t *this)
void(* set_policy_started)(imv_session_t *this, bool start)
bool(* get_policy_started)(imv_session_t *this)
void(* insert_workitem)(imv_session_t *this, imv_workitem_t *workitem)
void(* remove_workitem)(imv_session_t *this, enumerator_t *enumerator)
enumerator_t *(* create_workitem_enumerator)(imv_session_t *this)
int(* get_workitem_count)(imv_session_t *this, TNC_IMVID imv_id)
imv_session_t *(* get_ref)(imv_session_t *)
void(* destroy)(imv_session_t *this)
Detailed Description
IMV session interface
Definition at line 38 of file imv_session.h.
Member Data Documentation
enumerator_t*(* imv_session_t::create_ar_identities_enumerator)(imv_session_t *this)
Get list of Access Requestor identities
Returns
List of Access Requestor identities
Definition at line 77 of file imv_session.h.
Referenced by create_session().
enumerator_t*(* imv_session_t::create_workitem_enumerator)(imv_session_t *this)
Create workitem enumerator
Definition at line 148 of file imv_session.h.
Referenced by imv_attestation_process(), and METHOD().
void(* imv_session_t::destroy)(imv_session_t *this)
Destroys an imv_session_t object
Definition at line 166 of file imv_session.h.
TNC_ConnectionID(* imv_session_t::get_connection_id)(imv_session_t *this)
Get TNCCS Connection ID
Returns
TNCCS Connection ID
Definition at line 63 of file imv_session.h.
Referenced by create_session(), and METHOD().
time_t(* imv_session_t::get_creation_time)(imv_session_t *this)
Get session creation time
Returns
Session creation time
Definition at line 70 of file imv_session.h.
Referenced by create_session().
bool(* imv_session_t::get_device_id)(imv_session_t *this, chunk_t *device_id)
Get Device ID
Parameters
device_id Device ID
Returns
TRUE if Device ID has already been set
Definition at line 99 of file imv_session.h.
Referenced by create_session(), imv_attestation_process(), and METHOD().
bool(* imv_session_t::get_device_trust)(imv_session_t *this)
Get device ID trust (needed for TPM-based attestation)
Returns
TRUE if Device ID is trusted
Definition at line 114 of file imv_session.h.
Referenced by imv_attestation_process().
imv_os_info_t*(* imv_session_t::get_os_info)(imv_session_t *this)
Get OS Information
Returns
OS info object
Definition at line 84 of file imv_session.h.
Referenced by create_session(), METHOD(), and receive_msg().
bool(* imv_session_t::get_policy_started)(imv_session_t *this)
Get policy_started status
Returns
TRUE if policy started, FALSE if policy stopped
Definition at line 128 of file imv_session.h.
Referenced by METHOD().
imv_session_t*(* imv_session_t::get_ref)(imv_session_t *)
Get reference to session
Definition at line 161 of file imv_session.h.
Referenced by METHOD().
int(* imv_session_t::get_session_id)(imv_session_t *this, int *pid, int *did)
Get unique session ID
Parameters
pid primary key into products table
did Primary key into devices table
Returns
primary key into sessions table
Definition at line 56 of file imv_session.h.
Referenced by add_workitems(), imv_attestation_process(), and METHOD().
int(* imv_session_t::get_workitem_count)(imv_session_t *this, TNC_IMVID imv_id)
Get number of workitem allocated to a given IMV
Parameters
imv_id IMV ID
Returns
Number of workitems assigned to given IMV
Definition at line 156 of file imv_session.h.
Referenced by METHOD().
void(* imv_session_t::insert_workitem)(imv_session_t *this, imv_workitem_t *workitem)
Insert workitem into list
Parameters
workitem Workitem to be inserted
Definition at line 135 of file imv_session.h.
Referenced by add_workitems().
void(* imv_session_t::remove_workitem)(imv_session_t *this, enumerator_t *enumerator)
Remove workitem from list
Parameters
enumerator Enumerator pointing to workitem to be removed
Definition at line 142 of file imv_session.h.
Referenced by imv_attestation_process(), and METHOD().
void(* imv_session_t::set_device_id)(imv_session_t *this, chunk_t device_id)
Set Device ID
Parameters
device_id Device ID
Definition at line 91 of file imv_session.h.
Referenced by METHOD(), and receive_msg().
void(* imv_session_t::set_device_trust)(imv_session_t *this, bool trusted)
Set trust into Device ID
Parameters
trusted TRUE if Device ID is trusted
Definition at line 106 of file imv_session.h.
Referenced by create_session().
void(* imv_session_t::set_policy_started)(imv_session_t *this, bool start)
Set policy_started status
Parameters
start TRUE if policy started, FALSE if policy stopped
Definition at line 121 of file imv_session.h.
Referenced by METHOD().
void(* imv_session_t::set_session_id)(imv_session_t *this, int session_id, int pid, int did)
Set unique session ID
Parameters
session_id primary key into sessions table
pid primary key into products table
did Primary key into devices table
Definition at line 47 of file imv_session.h.
Referenced by create_session().
The documentation for this struct was generated from the following file:
imv_session.h