strongSwan: scheduler_t Struct Reference
scheduler_t Struct Reference
scheduler
#include "scheduler.h"
Public Attributes
void(* schedule_job)(scheduler_t *this, job_t *job, u_int32_t s)
void(* schedule_job_ms)(scheduler_t *this, job_t *job, u_int32_t ms)
void(* schedule_job_tv)(scheduler_t *this, job_t *job, timeval_t tv)
u_int(* get_job_load)(scheduler_t *this)
void(* flush)(scheduler_t *this)
void(* destroy)(scheduler_t *this)
Detailed Description
The scheduler queues timed events which are then passed to the processor.
The scheduler is implemented as a heap. A heap is a special kind of tree- based data structure that satisfies the following property: if B is a child node of A, then key(A) >= (or <=) key(B). So either the element with the greatest (max-heap) or the smallest (min-heap) key is the root of the heap. We use a min-heap with the key being the absolute unix time at which an event is scheduled. So the root is always the event that will fire next.
An earlier implementation of the scheduler used a sorted linked list to store the events. That had the advantage that removing the next event was extremely fast, also, adding an event scheduled before or after all other events was equally fast (all in O(1)). The problem was, though, that adding an event in-between got slower, as the number of events grew larger (O(n)). For each connection there could be several events: IKE-rekey, NAT-keepalive, retransmissions, expire (half-open), and others. So a gateway that probably has to handle thousands of concurrent connnections has to be able to queue a large number of events as fast as possible. Locking makes this even worse, to provide thread-safety, no events can be processed, while an event is queued, so making the insertion fast is even more important.
That's the advantage of the heap. Adding an element to the heap can be achieved in O(log n) - on the other hand, removing the root node also requires O(log n) operations. Consider 10000 queued events. Inserting a new event in the list implementation required up to 10000 comparisons. In the heap implementation, the worst case is about 13.3 comparisons. That's a drastic improvement.
The implementation itself uses a binary tree mapped to a one-based array to store the elements. This reduces storage overhead and simplifies navigation: the children of the node at position n are at position 2n and 2n+1 (likewise the parent node of the node at position n is at position [n/2]). Thus, navigating up and down the tree is reduced to simple index computations.
Adding an element to the heap works as follows: The heap is always filled from left to right, until a row is full, then the next row is filled. Mapped to an array this gets as simple as putting the new element to the first free position. In a one-based array that position equals the number of elements currently stored in the heap. Then the heap property has to be restored, i.e. the new element has to be "bubbled up" the tree until the parent node's key is smaller or the element got the new root of the tree.
Removing the next event from the heap works similarly. The event itself is the root node and stored at position 1 of the array. After removing it, the root has to be replaced and the heap property has to be restored. This is done by moving the bottom element (last row, rightmost element) to the root and then "seep it down" by swapping it with child nodes until none of the children has a smaller key or it is again a leaf node.
Definition at line 81 of file scheduler.h.
Member Data Documentation
void(* scheduler_t::destroy)(scheduler_t *this)
Destroys a scheduler object.
Definition at line 125 of file scheduler.h.
void(* scheduler_t::flush)(scheduler_t *this)
Remove all scheduled jobs.
Definition at line 120 of file scheduler.h.
Referenced by destroy().
u_int(* scheduler_t::get_job_load)(scheduler_t *this)
Returns number of jobs scheduled.
Returns
number of scheduled jobs
Definition at line 115 of file scheduler.h.
Referenced by CALLBACK(), and METHOD().
void(* scheduler_t::schedule_job)(scheduler_t *this, job_t *job, u_int32_t s)
Adds a event to the queue, using a relative time offset in s.
Parameters
job job to schedule
time relative time to schedule job, in s
Definition at line 89 of file scheduler.h.
Referenced by check_cron(), check_systime(), enforce_replace(), ha_cache_create(), load_action(), METHOD(), plugin_cb(), process_job(), schedule_delayed_rekey(), schedule_expiration(), schedule_expire(), schedule_inactivity_timeout(), schedule_timeout(), start_autobalance(), and tnc_ifmap_listener_create().
void(* scheduler_t::schedule_job_ms)(scheduler_t *this, job_t *job, u_int32_t ms)
Adds a event to the queue, using a relative time offset in ms.
Parameters
job job to schedule
time relative time to schedule job, in ms
Definition at line 97 of file scheduler.h.
Referenced by blink_activity(), fire_roam_event(), handle_child_sa_failure(), METHOD(), process_job(), queue_retransmission(), queue_route_reinstall(), receive_packets(), retransmit_packet(), schedule_checks(), and update_checklist_state().
void(* scheduler_t::schedule_job_tv)(scheduler_t *this, job_t *job, timeval_t tv)
Adds a event to the queue, using an absolut time.
The passed timeval should be calculated based on the time_monotonic() function.
Parameters
job job to schedule
time absolut time to schedule job
Definition at line 108 of file scheduler.h.
Referenced by process_job(), and schedule_interim().
The documentation for this struct was generated from the following file:
scheduler.h