strongSwan: unity_narrow.c File Reference
unity_narrow.c File Reference
#include "unity_narrow.h"
#include <daemon.h>
#include <encoding/payloads/id_payload.h>
#include <collections/hashtable.h>
Classes
struct private_unity_narrow_t
Typedefs
typedef struct
private_unity_narrow_t private_unity_narrow_t
Functions
static void narrow_ts (child_cfg_t *cfg, traffic_selector_t *ts, linked_list_t *list)
static void narrow_initiator (private_unity_narrow_t *this, ike_sa_t *ike_sa, child_cfg_t *cfg, linked_list_t *remote)
static void narrow_pre (linked_list_t *list, char *side)
static void narrow_responder_post (child_cfg_t *child_cfg, linked_list_t *local)
static bool has_split_includes (private_unity_narrow_t *this, ike_sa_t *ike_sa)
METHOD (listener_t, narrow, bool, private_unity_narrow_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, narrow_hook_t type, linked_list_t *local, linked_list_t *remote)
METHOD (listener_t, message, bool, private_unity_narrow_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
METHOD (listener_t, ike_updown, bool, private_unity_narrow_t *this, ike_sa_t *ike_sa, bool up)
METHOD (unity_narrow_t, destroy, void, private_unity_narrow_t *this)
unity_narrow_t * unity_narrow_create (unity_handler_t *handler)
Typedef Documentation
typedef struct private_unity_narrow_t private_unity_narrow_t
Definition at line 25 of file unity_narrow.c.
Function Documentation
static bool has_split_includes (private_unity_narrow_t * this, ike_sa_t * ike_sa) static
Check if any Split-Include attributes are active on this IKE_SA
Definition at line 155 of file unity_narrow.c.
References enumerator_t::destroy, enumerator_t::enumerate, and ike_sa_t::get_id.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     bool has;
     enumerator = this->handler->create_include_enumerator(this->handler,
                                                 ike_sa->get_id(ike_sa));
     has = enumerator->enumerate(enumerator, &ts);
     enumerator->destroy(enumerator);
     return has;
 }
METHOD (listener_t , narrow , bool , private_unity_narrow_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, narrow_hook_t type, linked_list_t * local, linked_list_t * remote)
Definition at line 169 of file unity_narrow.c.
References COND_ORIGINAL_INITIATOR, EXT_CISCO_UNITY, child_sa_t::get_config, ike_sa_t::get_version, ike_sa_t::has_condition, has_split_includes(), IKEV1, narrow_initiator(), NARROW_INITIATOR_POST_AUTH, NARROW_INITIATOR_PRE_AUTH, narrow_pre(), NARROW_RESPONDER, narrow_responder_post(), NARROW_RESPONDER_POST, ike_sa_t::supports_extension, and TRUE.
 {
     if (ike_sa->get_version(ike_sa) == IKEV1 &&
         ike_sa->supports_extension(ike_sa, EXT_CISCO_UNITY))
     {
         /* depending on who initiates a rekeying the hooks will not match the
          * roles in the IKE_SA */
         if (ike_sa->has_condition(ike_sa, COND_ORIGINAL_INITIATOR))
         {
             switch (type)
             {
                 case NARROW_INITIATOR_PRE_AUTH:
                 case NARROW_RESPONDER:
                     if (has_split_includes(this, ike_sa))
                     {
                         narrow_pre(remote, "other");
                     }
                     break;
                 case NARROW_INITIATOR_POST_AUTH:
                 case NARROW_RESPONDER_POST:
                     narrow_initiator(this, ike_sa,
                                      child_sa->get_config(child_sa), remote);
                     break;
                 default:
                     break;
             }
         }
         else
         {
             switch (type)
             {
                 case NARROW_INITIATOR_PRE_AUTH:
                 case NARROW_RESPONDER:
                     if (this->wildcard_ts->get(this->wildcard_ts, ike_sa))
                     {
                         narrow_pre(local, "us");
                     }
                     break;
                 case NARROW_INITIATOR_POST_AUTH:
                 case NARROW_RESPONDER_POST:
                     if (this->wildcard_ts->get(this->wildcard_ts, ike_sa))
                     {
                         narrow_responder_post(child_sa->get_config(child_sa),
                                               local);
                     }
                     break;
                 default:
                     break;
             }
         }
     }
     return TRUE;
 }
METHOD (listener_t , message , bool , private_unity_narrow_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 226 of file unity_narrow.c.
References message_t::create_payload_enumerator, enumerator_t::destroy, traffic_selector_t::destroy, enumerator_t::enumerate, traffic_selector_t::equals, EXT_CISCO_UNITY, FALSE, message_t::get_exchange_type, id_payload_t::get_ts, payload_t::get_type, PLV1_ID, QUICK_MODE, ike_sa_t::supports_extension, traffic_selector_create_from_cidr(), and TRUE.
 {
     traffic_selector_t *tsr = NULL, *wildcard;
     enumerator_t *enumerator;
     id_payload_t *id_payload;
     payload_t *payload;
     bool first = TRUE;
     if (!incoming || !plain ||
         message->get_exchange_type(message) != QUICK_MODE ||
         !ike_sa || !ike_sa->supports_extension(ike_sa, EXT_CISCO_UNITY))
     {
         return TRUE;
     }
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV1_ID)
         {
             if (!first)
             {
                 id_payload = (id_payload_t*)payload;
                 tsr = id_payload->get_ts(id_payload);
                 break;
             }
             first = FALSE;
         }
     }
     enumerator->destroy(enumerator);
     if (!tsr)
     {
         return TRUE;
     }
     wildcard = traffic_selector_create_from_cidr("0.0.0.0/0", 0, 0, 65535);
     if (tsr->equals(tsr, wildcard))
     {
         this->wildcard_ts->put(this->wildcard_ts, ike_sa, ike_sa);
     }
     else
     {
         this->wildcard_ts->remove(this->wildcard_ts, ike_sa);
     }
     wildcard->destroy(wildcard);
     tsr->destroy(tsr);
     return TRUE;
 }
METHOD (listener_t , ike_updown , bool , private_unity_narrow_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 275 of file unity_narrow.c.
References TRUE.
 {
     if (!up)
     {
         this->wildcard_ts->remove(this->wildcard_ts, ike_sa);
     }
     return TRUE;
 }
METHOD (unity_narrow_t , destroy , void , private_unity_narrow_t * this)
Definition at line 285 of file unity_narrow.c.
References free().
 {
     this->wildcard_ts->destroy(this->wildcard_ts);
     free(this);
 }
static void narrow_initiator (private_unity_narrow_t * this, ike_sa_t * ike_sa, child_cfg_t * cfg, linked_list_t * remote) static
Narrow TS as initiator to Unity Split-Include/Local-LAN
Definition at line 71 of file unity_narrow.c.
References configuration_attribute_type_names, DBG1, DBG_CFG, enumerator_t::destroy, traffic_selector_t::destroy, enumerator_t::enumerate, ike_sa_t::get_id, narrow_ts(), orig, linked_list_t::remove_first, SUCCESS, and UNITY_SPLIT_INCLUDE.
Referenced by METHOD().
 {
     traffic_selector_t *current, *orig = NULL;
     enumerator_t *enumerator;
     enumerator = this->handler->create_include_enumerator(this->handler,
                                             ike_sa->get_id(ike_sa));
     while (enumerator->enumerate(enumerator, &current))
     {
         if (orig == NULL)
         {   /* got one, replace original TS */
             if (remote->remove_first(remote, (void**)&orig) != SUCCESS)
             {
                 break;
             }
         }
         narrow_ts(cfg, current, remote);
     }
     enumerator->destroy(enumerator);
     if (orig)
     {
         DBG1(DBG_CFG, "narrowed CHILD_SA to %N %#R",
              configuration_attribute_type_names,
              UNITY_SPLIT_INCLUDE, remote);
         orig->destroy(orig);
     }
     else
     {   /* since we originally changed the traffic selector to 0.0.0.0/0 local
          * narrowing is not applied if no Split-Include attrs are received */
         if (remote->remove_first(remote, (void**)&orig) == SUCCESS)
         {
             narrow_ts(cfg, orig, remote);
             orig->destroy(orig);
         }
     }
 }
static void narrow_pre (linked_list_t * list, char * side) static
As initiator and responder, bump up TS to 0.0.0.0/0 for on-the-wire bits
Definition at line 112 of file unity_narrow.c.
References DBG2, DBG_CFG, traffic_selector_t::destroy, linked_list_t::insert_last, linked_list_t::remove_first, SUCCESS, traffic_selector_create_from_string(), and TS_IPV4_ADDR_RANGE.
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     while (list->remove_first(list, (void**)&ts) == SUCCESS)
     {
         ts->destroy(ts);
     }
     ts = traffic_selector_create_from_string(0, TS_IPV4_ADDR_RANGE,
                                              "0.0.0.0", 0,
                                              "255.255.255.255", 65535);
     if (ts)
     {
         DBG2(DBG_CFG, "changing proposed traffic selectors for %s:", side);
         DBG2(DBG_CFG, " %R", ts);
         list->insert_last(list, ts);
     }
 }
static void narrow_responder_post (child_cfg_t * child_cfg, linked_list_t * local) static
As responder, narrow down TS to configuration for installation
Definition at line 134 of file unity_narrow.c.
References linked_list_t::destroy, traffic_selector_t::destroy, child_cfg_t::get_traffic_selectors, linked_list_t::insert_last, linked_list_t::remove_first, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     linked_list_t *configured;
     while (local->remove_first(local, (void**)&ts) == SUCCESS)
     {
         ts->destroy(ts);
     }
     configured = child_cfg->get_traffic_selectors(child_cfg, TRUE, NULL, NULL);
     while (configured->remove_first(configured, (void**)&ts) == SUCCESS)
     {
         local->insert_last(local, ts);
     }
     configured->destroy(configured);
 }
static void narrow_ts (child_cfg_t * cfg, traffic_selector_t * ts, linked_list_t * list) static
Narrow the given received traffic selector with the child configuration and put them into the given list of TS
Definition at line 52 of file unity_narrow.c.
References linked_list_t::destroy, FALSE, child_cfg_t::get_traffic_selectors, linked_list_t::insert_last, linked_list_create(), linked_list_t::remove_first, and SUCCESS.
Referenced by narrow_initiator().
 {
     linked_list_t *received, *selected;
     received = linked_list_create();
     received->insert_last(received, ts);
     selected = cfg->get_traffic_selectors(cfg, FALSE, received, NULL);
     while (selected->remove_first(selected, (void**)&ts) == SUCCESS)
     {
         list->insert_last(list, ts);
     }
     selected->destroy(selected);
     received->destroy(received);
 }