strongSwan: keymat_t Struct Reference
keymat_t Struct Reference
keymat
#include "keymat.h"
Public Attributes
ike_version_t(* get_version)(keymat_t *this)
diffie_hellman_t *(* create_dh)(keymat_t *this, diffie_hellman_group_t group)
nonce_gen_t *(* create_nonce_gen)(keymat_t *this)
aead_t *(* get_aead)(keymat_t *this, bool in)
void(* destroy)(keymat_t *this)
Detailed Description
Derivation an management of sensitive keying material.
Definition at line 45 of file keymat.h.
Member Data Documentation
diffie_hellman_t*(* keymat_t::create_dh)(keymat_t *this, diffie_hellman_group_t group)
Create a diffie hellman object for key agreement.
The diffie hellman is either for IKE negotiation/rekeying or CHILD_SA rekeying (using PFS). The resulting DH object must be passed to derive_keys or to derive_child_keys and destroyed after use.
Only DH objects allocated through this method are passed to other keymat_t methods, allowing private DH implementations. In some cases (such as retrying with a COOKIE), a DH object allocated from a different keymat_t instance may be passed to other methods.
Parameters
group diffie hellman group
Returns
DH object, NULL if group not supported
Definition at line 69 of file keymat.h.
nonce_gen_t*(* keymat_t::create_nonce_gen)(keymat_t *this)
Create a nonce generator object.
The nonce generator can be used to create nonces needed during IKE/CHILD SA establishment or rekeying.
Returns
nonce generator object
Definition at line 80 of file keymat.h.
void(* keymat_t::destroy)(keymat_t *this)
Destroy a keymat_t.
Definition at line 93 of file keymat.h.
Referenced by build_auth(), rebuild_auth(), and START_TEST().
aead_t*(* keymat_t::get_aead)(keymat_t *this, bool in)
Get a AEAD transform to en-/decrypt and sign/verify IKE messages.
Parameters
in TRUE for inbound (decrypt), FALSE for outbound (encrypt)
Returns
crypter
Definition at line 88 of file keymat.h.
Referenced by calculate_wire_size(), decrypt_and_extract(), decrypt_fragment(), finalize_message(), generate_message(), METHOD(), and START_TEST().
ike_version_t(* keymat_t::get_version)(keymat_t *this)
Get IKE version of this keymat.
Returns
IKEV1 for keymat_v1_t, IKEV2 for keymat_v2_t
Definition at line 52 of file keymat.h.
Referenced by decrypt_and_extract(), generate_message(), METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
keymat.h