strongSwan: imv_manager_t Struct Reference
imv_manager_t Struct Reference
imv_manager
#include "imv_manager.h"
Public Attributes
bool(* add)(imv_manager_t *this, imv_t *imv)
imv_t *(* remove)(imv_manager_t *this, TNC_IMVID id)
bool(* load)(imv_manager_t *this, char *name, char *path)
bool(* load_from_functions)(imv_manager_t *this, char *name, TNC_IMV_InitializePointer initialize, TNC_IMV_NotifyConnectionChangePointer notify_connection_change, TNC_IMV_ReceiveMessagePointer receive_message, TNC_IMV_ReceiveMessageLongPointer receive_message_long, TNC_IMV_SolicitRecommendationPointer solicit_recommendation, TNC_IMV_BatchEndingPointer batch_ending, TNC_IMV_TerminatePointer terminate, TNC_IMV_ProvideBindFunctionPointer provide_bind_function)
bool(* is_registered)(imv_manager_t *this, TNC_IMVID id)
bool(* reserve_id)(imv_manager_t *this, TNC_IMVID id, TNC_UInt32 *new_id)
recommendation_policy_t(* get_recommendation_policy)(imv_manager_t *this)
recommendations_t *(* create_recommendations)(imv_manager_t *this)
void(* notify_connection_change)(imv_manager_t *this, TNC_ConnectionID id, TNC_ConnectionState state)
TNC_Result(* set_message_types)(imv_manager_t *this, TNC_IMVID id, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
TNC_Result(* set_message_types_long)(imv_manager_t *this, TNC_IMVID id, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
void(* solicit_recommendation)(imv_manager_t *this, TNC_ConnectionID id)
void(* receive_message)(imv_manager_t *this, TNC_ConnectionID connection_id, bool excl, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imc_id, TNC_UInt32 dst_imv_id)
void(* batch_ending)(imv_manager_t *this, TNC_ConnectionID id)
void(* destroy)(imv_manager_t *this)
Detailed Description
The IMV manager controls all IMV instances.
Definition at line 34 of file imv_manager.h.
Member Data Documentation
bool(* imv_manager_t::add)(imv_manager_t *this, imv_t *imv)
Add an IMV instance
Parameters
imv IMV instance
Returns
TRUE if initialization successful
Definition at line 42 of file imv_manager.h.
void(* imv_manager_t::batch_ending)(imv_manager_t *this, TNC_ConnectionID id)
Notify all IMVs that all IMC messages received in a batch have been delivered and this is the IMVs last chance to send a message in the batch of IMV messages currently being collected.
Parameters
id connection ID
Definition at line 189 of file imv_manager.h.
Referenced by METHOD().
recommendations_t*(* imv_manager_t::create_recommendations)(imv_manager_t *this)
Create an empty set of IMV recommendations and evaluations
Returns
instance of a recommendations_t list
Definition at line 114 of file imv_manager.h.
Referenced by METHOD().
void(* imv_manager_t::destroy)(imv_manager_t *this)
Destroy an IMV manager and all its controlled instances.
Definition at line 194 of file imv_manager.h.
Referenced by tnc_manager_register().
recommendation_policy_t(* imv_manager_t::get_recommendation_policy)(imv_manager_t *this)
Get the configured recommendation policy
Returns
configured recommendation policy
Definition at line 107 of file imv_manager.h.
Referenced by METHOD().
bool(* imv_manager_t::is_registered)(imv_manager_t *this, TNC_IMVID id)
Check if an IMV with a given ID is registered with the IMV manager
Parameters
id ID of IMV instance
Returns
TRUE if registered
Definition at line 91 of file imv_manager.h.
Referenced by TNC_TNCS_GetAttribute(), TNC_TNCS_ProvideRecommendation(), TNC_TNCS_ReportMessageTypes(), TNC_TNCS_ReportMessageTypesLong(), TNC_TNCS_RequestHandshakeRetry(), TNC_TNCS_SendMessage(), TNC_TNCS_SendMessageLong(), and TNC_TNCS_SetAttribute().
bool(* imv_manager_t::load)(imv_manager_t *this, char *name, char *path)
Load and initialize an IMV as a dynamic library and add it to the list
Parameters
name name of the IMV to be loaded
path path of the IMV dynamic library file
Returns
TRUE if loading succeeded
Definition at line 59 of file imv_manager.h.
Referenced by load_imcvs_from_config().
bool(* imv_manager_t::load_from_functions)(imv_manager_t *this, char *name, TNC_IMV_InitializePointer initialize, TNC_IMV_NotifyConnectionChangePointer notify_connection_change, TNC_IMV_ReceiveMessagePointer receive_message, TNC_IMV_ReceiveMessageLongPointer receive_message_long, TNC_IMV_SolicitRecommendationPointer solicit_recommendation, TNC_IMV_BatchEndingPointer batch_ending, TNC_IMV_TerminatePointer terminate, TNC_IMV_ProvideBindFunctionPointer provide_bind_function)
Load and initialize an IMV from a set of TNC IMC functions.
Parameters
name name of the IMV
initialize TNC_IMV_InitializePointer
notify_connection_change TNC_IMV_NotifyConnectionChangePointer
receive_message TNC_IMV_ReceiveMessagePointer
receive_message_long TNC_IMV_ReceiveMessageLongPointer
solicit_recommendation TNC_IMV_SolicitRecommendationPointer
batch_ending TNC_IMV_BatchEndingPointer
terminate TNC_IMV_TerminatePointer
provide_bind_function TNC_IMV_ProvideBindFunctionPointer
Returns
TRUE if loading succeeded
Definition at line 75 of file imv_manager.h.
void(* imv_manager_t::notify_connection_change)(imv_manager_t *this, TNC_ConnectionID id, TNC_ConnectionState state)
Notify all IMV instances
Parameters
state communicate the state a connection has reached
Definition at line 121 of file imv_manager.h.
Referenced by build_retry_batch(), check_and_build_recommendation(), METHOD(), and tnccs_20_server_create().
void(* imv_manager_t::receive_message)(imv_manager_t *this, TNC_ConnectionID connection_id, bool excl, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imc_id, TNC_UInt32 dst_imv_id)
Delivers a message to interested IMVs.
Parameters
connection_id connection ID
excl exclusive message flag
msg message
msg_len message length
msg_vid message Vendor ID
msg_subtype message subtype
src_imc_id source IMC ID
dst_imv_id destination IMV ID
Definition at line 172 of file imv_manager.h.
Referenced by handle_ietf_message(), and handle_message().
imv_t*(* imv_manager_t::remove)(imv_manager_t *this, TNC_IMVID id)
Remove an IMV instance from the list and return it
Parameters
id ID of IMV instance
Returns
removed IMC instance
Definition at line 50 of file imv_manager.h.
bool(* imv_manager_t::reserve_id)(imv_manager_t *this, TNC_IMVID id, TNC_UInt32 *new_id)
Reserve an additional ID for an IMV
Parameters
id ID of IMV instance
new_id reserved ID assigned to IMV
Returns
TRUE if primary IMV ID was used
Definition at line 100 of file imv_manager.h.
Referenced by TNC_TNCS_ReserveAdditionalIMVID().
TNC_Result(* imv_manager_t::set_message_types)(imv_manager_t *this, TNC_IMVID id, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
Sets the supported message types reported by a given IMV
Parameters
id ID of reporting IMV
supported_types list of messages type supported by IMV
type_count number of supported message types
Returns
TNC result code
Definition at line 133 of file imv_manager.h.
Referenced by TNC_TNCS_ReportMessageTypes().
TNC_Result(* imv_manager_t::set_message_types_long)(imv_manager_t *this, TNC_IMVID id, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
Sets the supported long message types reported by a given IMV
Parameters
id ID of reporting IMV
supported_vids list of vendor IDs supported by IMV
supported_subtypes list of messages type supported by IMV
type_count number of supported message types
Returns
TNC result code
Definition at line 147 of file imv_manager.h.
Referenced by TNC_TNCS_ReportMessageTypesLong().
void(* imv_manager_t::solicit_recommendation)(imv_manager_t *this, TNC_ConnectionID id)
Solicit recommendations from IMVs that have not yet provided one
Parameters
id connection ID
Definition at line 158 of file imv_manager.h.
Referenced by check_and_build_recommendation().
The documentation for this struct was generated from the following file:
imv_manager.h