strongSwan: auth_controller.c File Reference
auth_controller.c File Reference
#include "auth_controller.h"
#include "../manager.h"
#include <library.h>
Classes
struct private_auth_controller_t
Typedefs
typedef struct
private_auth_controller_t private_auth_controller_t
Functions
static void login (private_auth_controller_t *this, fast_request_t *request)
static void check (private_auth_controller_t *this, fast_request_t *request)
static void logout (private_auth_controller_t *this, fast_request_t *request)
METHOD (fast_controller_t, get_name, char *, private_auth_controller_t *this)
METHOD (fast_controller_t, handle, void, private_auth_controller_t *this, fast_request_t *request, char *action, char *p2, char *p3, char *p4, char *p5)
METHOD (fast_controller_t, destroy, void, private_auth_controller_t *this)
fast_controller_t * auth_controller_create (fast_context_t *context, void *param)
Typedef Documentation
typedef struct private_auth_controller_t private_auth_controller_t
Definition at line 22 of file auth_controller.c.
Function Documentation
static void check (private_auth_controller_t * this, fast_request_t * request) static
Definition at line 47 of file auth_controller.c.
References fast_request_t::get_query_data, and fast_request_t::redirect.
Referenced by METHOD().
 {
     char *username, *password;
     username = request->get_query_data(request, "username");
     password = request->get_query_data(request, "password");
     if (username && password &&
         this->manager->login(this->manager, username, password))
     {
         request->redirect(request, "ikesa/list");
     }
     else
     {
         request->redirect(request, "auth/login");
     }
 }
static void login (private_auth_controller_t * this, fast_request_t * request) static
Definition at line 40 of file auth_controller.c.
References fast_request_t::render, and fast_request_t::set.
Referenced by METHOD().
 {
     request->set(request, "action", "check");
     request->set(request, "title", "Login");
     request->render(request, "templates/auth/login.cs");
 }
static void logout (private_auth_controller_t * this, fast_request_t * request) static
Definition at line 64 of file auth_controller.c.
References fast_request_t::redirect.
Referenced by METHOD().
 {
     this->manager->logout(this->manager);
     request->redirect(request, "auth/login");
 }
METHOD (fast_controller_t , get_name , char * , private_auth_controller_t * this)
Definition at line 70 of file auth_controller.c.
 {
     return "auth";
 }
METHOD (fast_controller_t , handle , void , private_auth_controller_t * this, fast_request_t * request, char * action, char * p2, char * p3, char * p4, char * p5)
Definition at line 76 of file auth_controller.c.
References check(), login(), logout(), fast_request_t::redirect, and streq().
 {
     if (action)
     {
         if (streq(action, "login"))
         {
             return login(this, request);
         }
         else if (streq(action, "check"))
         {
             return check(this, request);
         }
         else if (streq(action, "logout"))
         {
             return logout(this, request);
         }
     }
     request->redirect(request, "auth/login");
 }
METHOD (fast_controller_t , destroy , void , private_auth_controller_t * this)
Definition at line 98 of file auth_controller.c.
References free().
 {
     free(this);
 }