strongSwan: vici_attribute
vici_attribute
vici
Classes
struct vici_attribute_t
Typedefs
typedef struct vici_attribute_t vici_attribute_t
Functions
vici_attribute_t * vici_attribute_create (vici_dispatcher_t *dispatcher)
Detailed Description
Typedef Documentation
typedef struct vici_attribute_t vici_attribute_t
Definition at line 28 of file vici_attribute.h.
Function Documentation
vici_attribute_t* vici_attribute_create (vici_dispatcher_t * dispatcher)
Create a vici_attribute instance.
Parameters
dispatcher vici dispatcher context
Returns
vici attribute handler
Definition at line 755 of file vici_attribute.c.
References hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), INIT, manage_commands(), rwlock_create(), RWLOCK_TYPE_DEFAULT, and TRUE.
Referenced by register_vici().
 {
     private_vici_attribute_t *this;
     INIT(this,
         .public = {
             .provider = {
                 .acquire_address = _acquire_address,
                 .release_address = _release_address,
                 .create_attribute_enumerator = _create_attribute_enumerator,
             },
             .destroy = _destroy,
         },
         .dispatcher = dispatcher,
         .pools = hashtable_create(hashtable_hash_str, hashtable_equals_str, 4),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     manage_commands(this, TRUE);
     return &this->public;
 }