strongSwan: ipsec_policy_mgr.c File Reference
ipsec_policy_mgr.c File Reference
#include "ipsec_policy_mgr.h"
#include <utils/debug.h>
#include <threading/rwlock.h>
#include <collections/linked_list.h>
Classes
struct private_ipsec_policy_mgr_t
struct ipsec_policy_entry_t
Macros
#define PRIO_BASE 384
Typedefs
typedef struct
private_ipsec_policy_mgr_t private_ipsec_policy_mgr_t
Functions
static u_int32_t calculate_priority (policy_priority_t policy_priority, traffic_selector_t *src, traffic_selector_t *dst)
static ipsec_policy_entry_t * policy_entry_create (ipsec_policy_t *policy)
static void policy_entry_destroy (ipsec_policy_entry_t *this)
METHOD (ipsec_policy_mgr_t, add_policy, status_t, private_ipsec_policy_mgr_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (ipsec_policy_mgr_t, del_policy, status_t, private_ipsec_policy_mgr_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t policy_priority)
METHOD (ipsec_policy_mgr_t, flush_policies, status_t, private_ipsec_policy_mgr_t *this)
METHOD (ipsec_policy_mgr_t, find_by_packet, ipsec_policy_t *, private_ipsec_policy_mgr_t *this, ip_packet_t *packet, bool inbound, u_int32_t reqid)
METHOD (ipsec_policy_mgr_t, destroy, void, private_ipsec_policy_mgr_t *this)
ipsec_policy_mgr_t * ipsec_policy_mgr_create ()
Macro Definition Documentation
#define PRIO_BASE 384
Base priority for installed policies
Definition at line 25 of file ipsec_policy_mgr.c.
Referenced by calculate_priority().
Typedef Documentation
typedef struct private_ipsec_policy_mgr_t private_ipsec_policy_mgr_t
Definition at line 27 of file ipsec_policy_mgr.c.
Function Documentation
static u_int32_t calculate_priority (policy_priority_t policy_priority, traffic_selector_t * src, traffic_selector_t * dst) static
Calculate the pseudo-priority to sort policies. This is the same algorithm used by the NETLINK kernel interface (i.e. high priority -> low value).
Definition at line 73 of file ipsec_policy_mgr.c.
References host_t::destroy, host_t::get_port, traffic_selector_t::get_protocol, mask, max, net, POLICY_PRIORITY_DEFAULT, POLICY_PRIORITY_FALLBACK, POLICY_PRIORITY_PASS, POLICY_PRIORITY_ROUTED, port, PRIO_BASE, proto, and traffic_selector_t::to_subnet.
Referenced by METHOD(), and policy_entry_create().
 {
     u_int32_t priority = PRIO_BASE;
     u_int16_t port;
     u_int8_t mask, proto;
     host_t *net;
     switch (policy_priority)
     {
         case POLICY_PRIORITY_FALLBACK:
             priority <<= 1;
             /* fall-through */
         case POLICY_PRIORITY_ROUTED:
             priority <<= 1;
             /* fall-through */
         case POLICY_PRIORITY_DEFAULT:
             priority <<= 1;
             /* fall-through */
         case POLICY_PRIORITY_PASS:
             break;
     }
     /* calculate priority based on selector size, small size = high prio */
     src->to_subnet(src, &net, &mask);
     priority -= mask;
     proto = src->get_protocol(src);
     port = net->get_port(net);
     net->destroy(net);
     dst->to_subnet(dst, &net, &mask);
     priority -= mask;
     proto = max(proto, dst->get_protocol(dst));
     port = max(port, net->get_port(net));
     net->destroy(net);
     priority <<= 2; /* make some room for the two flags */
     priority += port ? 0 : 2;
     priority += proto ? 0 : 1;
     return priority;
 }
METHOD (ipsec_policy_mgr_t , add_policy , status_t , private_ipsec_policy_mgr_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 140 of file ipsec_policy_mgr.c.
References DBG2, DBG_ESP, enumerator_t::destroy, enumerator_t::enumerate, ipsec_policy_create(), lock, policy_dir_names, policy_entry_create(), POLICY_FWD, POLICY_IPSEC, ipsec_policy_entry_t::priority, SUCCESS, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     ipsec_policy_entry_t *entry, *current;
     ipsec_policy_t *policy;
     if (type != POLICY_IPSEC || direction == POLICY_FWD)
     {   /* we ignore these policies as we currently have no use for them */
         return SUCCESS;
     }
     DBG2(DBG_ESP, "adding policy %R === %R %N", src_ts, dst_ts,
          policy_dir_names, direction);
     policy = ipsec_policy_create(src, dst, src_ts, dst_ts, direction, type, sa,
                                  mark, priority);
     entry = policy_entry_create(policy);
     this->lock->write_lock(this->lock);
     enumerator = this->policies->create_enumerator(this->policies);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current->priority >= entry->priority)
         {
             break;
         }
     }
     this->policies->insert_before(this->policies, enumerator, entry);
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return SUCCESS;
 }
METHOD (ipsec_policy_mgr_t , del_policy , status_t , private_ipsec_policy_mgr_t * this, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t policy_priority)
Definition at line 177 of file ipsec_policy_mgr.c.
References calculate_priority(), DBG2, DBG_ESP, enumerator_t::destroy, enumerator_t::enumerate, FAILED, found, lock, ipsec_policy_t::match, ipsec_policy_entry_t::policy, policy_dir_names, policy_entry_destroy(), POLICY_FWD, ipsec_policy_entry_t::priority, SUCCESS, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     ipsec_policy_entry_t *current, *found = NULL;
     u_int32_t priority;
     if (direction == POLICY_FWD)
     {   /* we ignore these policies as we currently have no use for them */
         return SUCCESS;
     }
     DBG2(DBG_ESP, "deleting policy %R === %R %N", src_ts, dst_ts,
          policy_dir_names, direction);
     priority = calculate_priority(policy_priority, src_ts, dst_ts);
     this->lock->write_lock(this->lock);
     enumerator = this->policies->create_enumerator(this->policies);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current->priority == priority &&
             current->policy->match(current->policy, src_ts, dst_ts, direction,
                                    reqid, mark, policy_priority))
         {
             this->policies->remove_at(this->policies, enumerator);
             found = current;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (found)
     {
         policy_entry_destroy(found);
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (ipsec_policy_mgr_t , flush_policies , status_t , private_ipsec_policy_mgr_t * this)
Definition at line 218 of file ipsec_policy_mgr.c.
References DBG2, DBG_ESP, lock, policy_entry_destroy(), SUCCESS, and spinlock_t::unlock.
 {
     ipsec_policy_entry_t *entry;
     DBG2(DBG_ESP, "flushing policies");
     this->lock->write_lock(this->lock);
     while (this->policies->remove_last(this->policies,
                                       (void**)&entry) == SUCCESS)
     {
         policy_entry_destroy(entry);
     }
     this->lock->unlock(this->lock);
     return SUCCESS;
 }
METHOD (ipsec_policy_mgr_t , find_by_packet , ipsec_policy_t * , private_ipsec_policy_mgr_t * this, ip_packet_t * packet, bool inbound, u_int32_t reqid)
Definition at line 235 of file ipsec_policy_mgr.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, ipsec_policy_t::get_direction, ipsec_policy_t::get_ref, ipsec_policy_t::get_reqid, lock, ipsec_policy_t::match_packet, ipsec_policy_entry_t::policy, POLICY_IN, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     ipsec_policy_entry_t *current;
     ipsec_policy_t *found = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->policies->create_enumerator(this->policies);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         ipsec_policy_t *policy = current->policy;
         if ((inbound == (policy->get_direction(policy) == POLICY_IN)) &&
              policy->match_packet(policy, packet))
         {
             if (reqid == 0 || reqid == policy->get_reqid(policy))
             {
                 found = policy->get_ref(policy);
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return found;
 }
METHOD (ipsec_policy_mgr_t , destroy , void , private_ipsec_policy_mgr_t * this)
Definition at line 264 of file ipsec_policy_mgr.c.
References spinlock_t::destroy, free(), and lock.
 {
     flush_policies(this);
     this->policies->destroy(this->policies);
     this->lock->destroy(this->lock);
     free(this);
 }
static ipsec_policy_entry_t* policy_entry_create (ipsec_policy_t * policy) static
Create a policy entry
Definition at line 118 of file ipsec_policy_mgr.c.
References calculate_priority(), ipsec_policy_t::get_destination_ts, ipsec_policy_t::get_priority, ipsec_policy_t::get_source_ts, and INIT.
Referenced by METHOD().
 {
     ipsec_policy_entry_t *this;
     INIT(this,
         .policy = policy,
         .priority = calculate_priority(policy->get_priority(policy),
                                        policy->get_source_ts(policy),
                                        policy->get_destination_ts(policy)),
     );
     return this;
 }
static void policy_entry_destroy (ipsec_policy_entry_t * this) static
Destroy a policy entry
Definition at line 134 of file ipsec_policy_mgr.c.
References free().
Referenced by METHOD().
 {
     this->policy->destroy(this->policy);
     free(this);
 }