strongSwan: imc_t Struct Reference
imc_t Struct Reference
imc
#include "imc.h"
Public Attributes
TNC_Result(* initialize)(TNC_IMCID imcID, TNC_Version minVersion, TNC_Version maxVersion, TNC_Version *OutActualVersion)
TNC_Result(* notify_connection_change)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_ConnectionState newState)
TNC_Result(* begin_handshake)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
TNC_Result(* receive_message)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
TNC_Result(* receive_message_long)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 sourceIMVID, TNC_UInt32 destinationIMCID)
TNC_Result(* batch_ending)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
TNC_Result(* terminate)(TNC_IMCID imcID)
TNC_Result(* provide_bind_function)(TNC_IMCID imcID, TNC_TNCC_BindFunctionPointer bindFunction)
void(* set_id)(imc_t *this, TNC_IMCID id)
TNC_IMCID(* get_id)(imc_t *this)
void(* add_id)(imc_t *this, TNC_IMCID id)
bool(* has_id)(imc_t *this, TNC_IMCID id)
char *(* get_name)(imc_t *this)
void(* set_message_types)(imc_t *this, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
void(* set_message_types_long)(imc_t *this, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
bool(* type_supported)(imc_t *this, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
void(* destroy)(imc_t *this)
Detailed Description
Controls a single Integrity Measurement Collector (IMC)
Definition at line 36 of file imc.h.
Member Data Documentation
void(* imc_t::add_id)(imc_t *this, TNC_IMCID id)
Assign an additional ID to an imc_t object.
Parameters
id additional IMC ID to be assigned
Definition at line 178 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::batch_ending)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
The TNC Client calls this function to notify IMCs that all IMV messages received in a batch have been delivered and this is the IMC’s last chance to send a message in the batch of IMC messages currently being collected.
Parameters
imcID IMC ID assigned by TNCC
connectionID network connection ID assigned by TNCC
Returns
TNC result code
Definition at line 133 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::begin_handshake)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
The TNC Client calls this function to indicate that an Integrity Check Handshake is beginning and solicit messages from IMCs for the first batch.
Parameters
imcID IMC ID assigned by TNCC
connectionID network connection ID assigned by TNCC
Returns
TNC result code
Definition at line 75 of file imc.h.
Referenced by METHOD().
void(* imc_t::destroy)(imc_t *this)
Destroys an imc_t object.
Definition at line 227 of file imc.h.
Referenced by METHOD().
TNC_IMCID(* imc_t::get_id)(imc_t *this)
Returns the ID of an imc_t object.
Returns
assigned IMC ID
Definition at line 171 of file imc.h.
Referenced by METHOD().
char*(* imc_t::get_name)(imc_t *this)
Returns the name of an imc_t object.
Returns
name of IMC
Definition at line 192 of file imc.h.
Referenced by METHOD().
bool(* imc_t::has_id)(imc_t *this, TNC_IMCID id)
Checks if the ID is assigned to the imc_t object.
Returns
TRUE if IMC ID is assigned to imc_t object
Definition at line 185 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::initialize)(TNC_IMCID imcID, TNC_Version minVersion, TNC_Version maxVersion, TNC_Version *OutActualVersion)
The TNC Client calls this function to initialize the IMC and agree on the API version number to be used. It also supplies the IMC ID, an IMC identifier that the IMC must use when calling TNC Client callback functions.
Parameters
imcID IMC ID assigned by TNCC
minVersion minimum API version supported by TNCC
maxVersion maximum API version supported by TNCC
OutActualVersion mutually supported API version number
Returns
TNC result code
Definition at line 49 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::notify_connection_change)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_ConnectionState newState)
The TNC Client calls this function to inform the IMC that the state of the network connection identified by connectionID has changed to newState.
Parameters
imcID IMC ID assigned by TNCC
connectionID network connection ID assigned by TNCC
newState new network connection state
Returns
TNC result code
Definition at line 63 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::provide_bind_function)(TNC_IMCID imcID, TNC_TNCC_BindFunctionPointer bindFunction)
IMVs implementing the UNIX/Linux Dynamic Linkage platform binding MUST define this additional function. The TNC Server MUST call the function immediately after calling TNC_IMV_Initialize to provide a pointer to the TNCS bind function. The IMV can then use the TNCS bind function to obtain pointers to any other TNCS functions.
Parameters
imcID IMC ID assigned by TNCC
bindFunction pointer to TNC_TNCC_BindFunction
Returns
TNC result code
Definition at line 156 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::receive_message)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
The TNC Client calls this function to deliver a message to the IMC. The message is contained in the buffer referenced by message and contains the number of octets indicated by messageLength. The type of the message is indicated by messageType.
Parameters
imcID IMC ID assigned by TNCS
connectionID network connection ID assigned by TNCC
message reference to buffer containing message
messageLength number of octets in message
messageType message type of message
Returns
TNC result code
Definition at line 91 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::receive_message_long)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 sourceIMVID, TNC_UInt32 destinationIMCID)
The TNC Client calls this function to deliver a message to the IMC. The message is contained in the buffer referenced by message and contains the number of octets indicated by messageLength. The type of the message is indicated by the message Vendor ID and message subtype.
Parameters
imcID IMC ID assigned by TNCS
connectionID network connection ID assigned by TNCC
messageFlags message flags
message reference to buffer containing message
messageLength number of octets in message
messageVendorID message Vendor ID
messageSubtype message subtype
sourceIMVID source IMV ID
destinationIMCID destination IMC ID
Returns
TNC result code
Definition at line 114 of file imc.h.
Referenced by METHOD().
void(* imc_t::set_id)(imc_t *this, TNC_IMCID id)
Sets the ID of an imc_t object.
Parameters
id IMC ID to be assigned
Definition at line 164 of file imc.h.
Referenced by METHOD().
void(* imc_t::set_message_types)(imc_t *this, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
Sets the supported message types of an imc_t object.
Parameters
supported_types list of messages type supported by IMC
type_count number of supported message types
Definition at line 200 of file imc.h.
Referenced by METHOD().
void(* imc_t::set_message_types_long)(imc_t *this, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
Sets the supported long message types of an imc_t object.
Parameters
supported_vids list of vendor IDs supported by IMC
supported_subtypes list of messages type supported by IMC
type_count number of supported message types
Definition at line 210 of file imc.h.
Referenced by METHOD().
TNC_Result(* imc_t::terminate)(TNC_IMCID imcID)
The TNC Client calls this function to close down the IMC when all work is complete or the IMC reports TNC_RESULT_FATAL.
Parameters
imcID IMC ID assigned by TNCC
Returns
TNC result code
Definition at line 143 of file imc.h.
Referenced by METHOD().
bool(* imc_t::type_supported)(imc_t *this, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
Check if the IMC supports a given message type.
Parameters
msg_vid message vendor ID
msg_subtype message subtype
Returns
TRUE if supported
Definition at line 221 of file imc.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
imc.h