strongSwan: proposal_substructure
proposal_substructure
payloads
Classes
struct proposal_substructure_t
Typedefs
typedef enum encap_t encap_t
typedef struct
proposal_substructure_t proposal_substructure_t
Enumerations
enum encap_t { ENCAP_NONE = 0, ENCAP_UDP, ENCAP_UDP_DRAFT_00_03 }
Functions
proposal_substructure_t * proposal_substructure_create (payload_type_t type)
proposal_substructure_t * proposal_substructure_create_from_proposal_v2 (proposal_t *proposal)
proposal_substructure_t * proposal_substructure_create_from_proposal_v1 (proposal_t *proposal, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp)
proposal_substructure_t * proposal_substructure_create_from_proposals_v1 (linked_list_t *proposals, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp)
proposal_substructure_t * proposal_substructure_create_for_ipcomp_v1 (u_int32_t lifetime, u_int64_t lifebytes, u_int16_t cpi, ipsec_mode_t mode, encap_t udp, u_int8_t proposal_number)
Detailed Description
Typedef Documentation
typedef enum encap_t encap_t
Definition at line 26 of file proposal_substructure.h.
typedef struct proposal_substructure_t proposal_substructure_t
Definition at line 27 of file proposal_substructure.h.
Enumeration Type Documentation
enum encap_t
Encap type for proposal substructure
Enumerator
ENCAP_NONE
ENCAP_UDP
ENCAP_UDP_DRAFT_00_03
Definition at line 40 of file proposal_substructure.h.
              {
     ENCAP_NONE = 0,
     ENCAP_UDP,
     ENCAP_UDP_DRAFT_00_03,
 };
Function Documentation
proposal_substructure_t* proposal_substructure_create (payload_type_t type)
Creates an empty proposal_substructure_t object
Parameters
type PLV2_PROPOSAL_SUBSTRUCTURE or PLV1_PROPOSAL_SUBSTRUCTURE
Returns
proposal_substructure_t object
Definition at line 1217 of file proposal_substructure.c.
References compute_length(), INIT, linked_list_create(), PL_NONE, and type.
Referenced by payload_create(), proposal_substructure_create_for_ipcomp_v1(), proposal_substructure_create_from_proposal_v1(), and proposal_substructure_create_from_proposal_v2().
 {
     private_proposal_substructure_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .set_proposal_number = _set_proposal_number,
             .get_proposal_number = _get_proposal_number,
             .set_protocol_id = _set_protocol_id,
             .get_protocol_id = _get_protocol_id,
             .set_is_last_proposal = _set_is_last_proposal,
             .get_proposals = _get_proposals,
             .create_substructure_enumerator = _create_substructure_enumerator,
             .set_spi = _set_spi,
             .get_spi = _get_spi,
             .get_cpi = _get_cpi,
             .get_lifetime = _get_lifetime,
             .get_lifebytes = _get_lifebytes,
             .get_auth_method = _get_auth_method,
             .get_encap_mode = _get_encap_mode,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .transforms = linked_list_create(),
         .type = type,
     );
     compute_length(this);
     return &this->public;
 }
proposal_substructure_t* proposal_substructure_create_for_ipcomp_v1 (u_int32_t lifetime, u_int64_t lifebytes, u_int16_t cpi, ipsec_mode_t mode, encap_t udp, u_int8_t proposal_number)
Creates an IKEv1 proposal_substructure_t for IPComp with the given proposal_number (e.g. of a ESP proposal to bundle them).
Parameters
lifetime lifetime in seconds
lifebytes lifebytes, in bytes
cpi the CPI to be used
mode IPsec encapsulation mode, TRANSPORT or TUNNEL
udp ENCAP_UDP to use UDP encapsulation
proposal_number the proposal number of the proposal to be linked
Returns
IKEv1 proposal_substructure_t PLV1_PROPOSAL_SUBSTRUCTURE
See header.
Definition at line 1609 of file proposal_substructure.c.
References transform_substructure_t::add_transform_attribute, add_transform_substructure(), chunk_clone, chunk_from_thing, compute_length(), get_ikev1_mode(), IKEV1_IPCOMP_DEFLATE, IKEV1_LIFE_TYPE_KILOBYTES, IKEV1_LIFE_TYPE_SECONDS, PLV1_PROPOSAL_SUBSTRUCTURE, PLV1_TRANSFORM_ATTRIBUTE, PLV1_TRANSFORM_SUBSTRUCTURE, proposal_substructure_create(), PROTO_IPCOMP, TATTR_PH2_ENCAP_MODE, TATTR_PH2_SA_LIFE_DURATION, TATTR_PH2_SA_LIFE_TYPE, transform_attribute_create_value(), and transform_substructure_create_type().
Referenced by sa_payload_create_from_proposals_v1().
 {
     private_proposal_substructure_t *this;
     transform_substructure_t *transform;
     this = (private_proposal_substructure_t*)
                         proposal_substructure_create(PLV1_PROPOSAL_SUBSTRUCTURE);
     /* we currently support DEFLATE only */
     transform = transform_substructure_create_type(PLV1_TRANSFORM_SUBSTRUCTURE,
                                                    1, IKEV1_IPCOMP_DEFLATE);
     transform->add_transform_attribute(transform,
         transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_ENCAP_MODE, get_ikev1_mode(mode, udp)));
     if (lifetime)
     {
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_TYPE, IKEV1_LIFE_TYPE_SECONDS));
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_DURATION, lifetime));
     }
     if (lifebytes)
     {
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_TYPE, IKEV1_LIFE_TYPE_KILOBYTES));
         transform->add_transform_attribute(transform,
             transform_attribute_create_value(PLV1_TRANSFORM_ATTRIBUTE,
                             TATTR_PH2_SA_LIFE_DURATION, lifebytes / 1000));
     }
     add_transform_substructure(this, transform);
     this->spi = chunk_clone(chunk_from_thing(cpi));
     this->spi_size = this->spi.len;
     this->protocol_id = PROTO_IPCOMP;
     this->proposal_number = proposal_number;
     compute_length(this);
     return &this->public;
 }
proposal_substructure_t* proposal_substructure_create_from_proposal_v1 (proposal_t * proposal, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp)
Creates an IKEv1 proposal_substructure_t from a proposal_t.
Parameters
proposal proposal to build a substruct out of it
lifetime lifetime in seconds
lifebytes lifebytes, in bytes
auth authentication method to use, or AUTH_NONE
mode IPsec encapsulation mode, TRANSPORT or TUNNEL
udp ENCAP_UDP to use UDP encapsulation
Returns
proposal_substructure_t object PLV1_PROPOSAL_SUBSTRUCTURE
See header.
Definition at line 1535 of file proposal_substructure.c.
References proposal_t::get_protocol, PLV1_PROPOSAL_SUBSTRUCTURE, proposal_substructure_create(), PROTO_AH, PROTO_ESP, PROTO_IKE, set_data(), set_from_proposal_v1(), and set_from_proposal_v1_ike().
Referenced by proposal_substructure_create_from_proposals_v1().
 {
     private_proposal_substructure_t *this;
     this = (private_proposal_substructure_t*)
                         proposal_substructure_create(PLV1_PROPOSAL_SUBSTRUCTURE);
     switch (proposal->get_protocol(proposal))
     {
         case PROTO_IKE:
             set_from_proposal_v1_ike(this, proposal, lifetime, auth, 1);
             break;
         case PROTO_ESP:
         case PROTO_AH:
             set_from_proposal_v1(this, proposal, lifetime,
                                  lifebytes, mode, udp, 1);
             break;
         default:
             break;
     }
     set_data(this, proposal);
     return &this->public;
 }
proposal_substructure_t* proposal_substructure_create_from_proposal_v2 (proposal_t * proposal)
Creates an IKEv2 proposal_substructure_t from a proposal_t.
Parameters
proposal proposal to build a substruct out of it
Returns
proposal_substructure_t PLV2_PROPOSAL_SUBSTRUCTURE
Definition at line 1519 of file proposal_substructure.c.
References PLV2_SECURITY_ASSOCIATION, proposal_substructure_create(), set_data(), and set_from_proposal_v2().
Referenced by add_proposal_v2().
 {
     private_proposal_substructure_t *this;
     this = (private_proposal_substructure_t*)
                             proposal_substructure_create(PLV2_SECURITY_ASSOCIATION);
     set_from_proposal_v2(this, proposal);
     set_data(this, proposal);
     return &this->public;
 }
proposal_substructure_t* proposal_substructure_create_from_proposals_v1 (linked_list_t * proposals, u_int32_t lifetime, u_int64_t lifebytes, auth_method_t auth, ipsec_mode_t mode, encap_t udp)
Creates an IKEv1 proposal_substructure_t from a list of proposal_t.
Parameters
proposals list of proposal_t to encode in a substructure
lifetime lifetime in seconds
lifebytes lifebytes, in bytes
auth authentication method to use, or AUTH_NONE
mode IPsec encapsulation mode, TRANSPORT or TUNNEL
udp ENCAP_UDP to use UDP encapsulation
Returns
IKEv1 proposal_substructure_t PLV1_PROPOSAL_SUBSTRUCTURE
See header.
Definition at line 1564 of file proposal_substructure.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, proposal_t::get_protocol, proposal, proposal_substructure_create_from_proposal_v1(), PROTO_AH, PROTO_ESP, PROTO_IKE, set_from_proposal_v1(), and set_from_proposal_v1_ike().
Referenced by sa_payload_create_from_proposals_v1().
 {
     private_proposal_substructure_t *this = NULL;
     enumerator_t *enumerator;
     proposal_t *proposal;
     int number = 0;
     enumerator = proposals->create_enumerator(proposals);
     while (enumerator->enumerate(enumerator, &proposal))
     {
         if (!this)
         {
             this = (private_proposal_substructure_t*)
                         proposal_substructure_create_from_proposal_v1(
                                 proposal, lifetime, lifebytes, auth, mode, udp);
             ++number;
         }
         else
         {
             switch (proposal->get_protocol(proposal))
             {
                 case PROTO_IKE:
                     set_from_proposal_v1_ike(this, proposal, lifetime,
                                              auth, ++number);
                     break;
                 case PROTO_ESP:
                 case PROTO_AH:
                     set_from_proposal_v1(this, proposal, lifetime,
                                          lifebytes, mode, udp, ++number);
                     break;
                 default:
                     break;
             }
         }
     }
     enumerator->destroy(enumerator);
     return &this->public;
 }