strongSwan: imv_swid_rest.c File Reference
imv_swid_rest.c File Reference
#include <stdio.h>
#include "imv_swid_rest.h"
Classes
struct private_imv_swid_rest_t
Macros
#define _GNU_SOURCE
#define HTTP_STATUS_CODE_PRECONDITION_FAILED 412
Typedefs
typedef struct
private_imv_swid_rest_t private_imv_swid_rest_t
Functions
METHOD (imv_swid_rest_t, post, status_t, private_imv_swid_rest_t *this, char *command, json_object *jrequest, json_object **jresponse)
METHOD (imv_swid_rest_t, destroy, void, private_imv_swid_rest_t *this)
imv_swid_rest_t * imv_swid_rest_create (char *uri, u_int timeout)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file imv_swid_rest.c.
#define HTTP_STATUS_CODE_PRECONDITION_FAILED 412
Definition at line 45 of file imv_swid_rest.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_imv_swid_rest_t private_imv_swid_rest_t
Definition at line 21 of file imv_swid_rest.c.
Function Documentation
METHOD (imv_swid_rest_t , post , status_t , private_imv_swid_rest_t * this, char * command, json_object * jrequest, json_object ** jresponse)
Definition at line 47 of file imv_swid_rest.c.
References asprintf(), chunk_empty, chunk_from_str, code, data, DBG2, DBG_IMV, FAILED, fetcher_manager_t::fetch, FETCH_END, FETCH_REQUEST_DATA, FETCH_REQUEST_HEADER, FETCH_REQUEST_TYPE, FETCH_RESPONSE_CODE, FETCH_TIMEOUT, library_t::fetcher, free(), HTTP_STATUS_CODE_PRECONDITION_FAILED, chunk_t::len, lib, NEED_MORE, chunk_t::ptr, response, status, SUCCESS, and uri.
 {
     struct json_tokener *tokener;
     chunk_t data, response = chunk_empty;
     status_t status;
     char *uri;
     int code;
     if (asprintf(&uri, "%s%s",this->uri, command) < 0)
     {
         return FAILED;
     }
     data = chunk_from_str((char*)json_object_to_json_string(jrequest));
     status = lib->fetcher->fetch(lib->fetcher, uri, &response,
                 FETCH_TIMEOUT, this->timeout,
                 FETCH_REQUEST_DATA, data,
                 FETCH_REQUEST_TYPE, "application/json; charset=utf-8",
                 FETCH_REQUEST_HEADER, "Accept: application/json",
                 FETCH_REQUEST_HEADER, "Expect:",
                 FETCH_RESPONSE_CODE, &code,
                 FETCH_END);
     free(uri);
     if (status == SUCCESS)
     {
         return  SUCCESS;
     }
     if (code != HTTP_STATUS_CODE_PRECONDITION_FAILED || !response.ptr)
     {
         DBG2(DBG_IMV, "REST http request failed with status code: %d", code);
         return FAILED;
     }
     if (jresponse)
     {
         /* Parse HTTP response into a JSON object */
         tokener = json_tokener_new();
         *jresponse = json_tokener_parse_ex(tokener, response.ptr, response.len);
         json_tokener_free(tokener);
     }
     free(response.ptr);
     return NEED_MORE;
 }
METHOD (imv_swid_rest_t , destroy , void , private_imv_swid_rest_t * this)
Definition at line 96 of file imv_swid_rest.c.
References free(), and uri.
 {
     free(this->uri);
     free(this);
 }