strongSwan: trap_manager.c File Reference
trap_manager.c File Reference
#include "trap_manager.h"
#include <hydra.h>
#include <daemon.h>
#include <threading/mutex.h>
#include <threading/rwlock.h>
#include <threading/rwlock_condvar.h>
#include <collections/linked_list.h>
Classes
struct trap_listener_t
struct private_trap_manager_t
struct entry_t
struct acquire_t
Macros
#define INSTALL_DISABLED ((u_int)~0)
Typedefs
typedef struct
private_trap_manager_t private_trap_manager_t
typedef struct trap_listener_t trap_listener_t
Functions
static void destroy_entry (entry_t *this)
static void destroy_acquire (acquire_t *this)
static bool acquire_by_reqid (acquire_t *this, u_int32_t *reqid)
static bool acquire_by_dst (acquire_t *this, host_t *dst)
METHOD (trap_manager_t, install, u_int32_t, private_trap_manager_t *this, peer_cfg_t *peer, child_cfg_t *child, u_int32_t reqid)
METHOD (trap_manager_t, uninstall, bool, private_trap_manager_t *this, u_int32_t reqid)
static bool trap_filter (rwlock_t *lock, entry_t **entry, peer_cfg_t **peer_cfg, void *none, child_sa_t **child_sa)
METHOD (trap_manager_t, create_enumerator, enumerator_t *, private_trap_manager_t *this)
METHOD (trap_manager_t, find_reqid, u_int32_t, private_trap_manager_t *this, child_cfg_t *child)
METHOD (trap_manager_t, acquire, void, private_trap_manager_t *this, u_int32_t reqid, traffic_selector_t *src, traffic_selector_t *dst)
static void complete (private_trap_manager_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa)
METHOD (listener_t, ike_state_change, bool, trap_listener_t *listener, ike_sa_t *ike_sa, ike_sa_state_t state)
METHOD (listener_t, child_state_change, bool, trap_listener_t *listener, ike_sa_t *ike_sa, child_sa_t *child_sa, child_sa_state_t state)
METHOD (trap_manager_t, flush, void, private_trap_manager_t *this)
METHOD (trap_manager_t, destroy, void, private_trap_manager_t *this)
trap_manager_t * trap_manager_create (void)
Macro Definition Documentation
#define INSTALL_DISABLED ((u_int)~0)
Definition at line 26 of file trap_manager.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_trap_manager_t private_trap_manager_t
Definition at line 28 of file trap_manager.c.
typedef struct trap_listener_t trap_listener_t
Definition at line 29 of file trap_manager.c.
Function Documentation
static bool acquire_by_dst (acquire_t * this, host_t * dst) static
match an acquire entry by destination address
Definition at line 155 of file trap_manager.c.
References host_t::ip_equals.
Referenced by METHOD().
 {
     return this->dst && this->dst->ip_equals(this->dst, dst);
 }
static bool acquire_by_reqid (acquire_t * this, u_int32_t * reqid) static
match an acquire entry by reqid
Definition at line 147 of file trap_manager.c.
Referenced by METHOD().
 {
     return this->reqid == *reqid;
 }
static void complete (private_trap_manager_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa) static
Complete the acquire, if successful or failed
Definition at line 552 of file trap_manager.c.
References acquire(), enumerator_t::destroy, destroy_acquire(), acquire_t::dst, enumerator_t::enumerate, child_sa_t::get_reqid, acquire_t::ike_sa, mutex_t::lock, mutex, acquire_t::reqid, and mutex_t::unlock.
Referenced by METHOD(), and verify().
 {
     enumerator_t *enumerator;
     acquire_t *acquire;
     this->mutex->lock(this->mutex);
     enumerator = this->acquires->create_enumerator(this->acquires);
     while (enumerator->enumerate(enumerator, &acquire))
     {
         if (!acquire->ike_sa || acquire->ike_sa != ike_sa)
         {
             continue;
         }
         if (child_sa)
         {
             if (acquire->dst)
             {
                 /* since every wildcard acquire results in a separate IKE_SA
                  * there is no need to compare the destination address */
             }
             else if (child_sa->get_reqid(child_sa) != acquire->reqid)
             {
                 continue;
             }
         }
         this->acquires->remove_at(this->acquires, enumerator);
         destroy_acquire(acquire);
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
static void destroy_acquire (acquire_t * this) static
destroy a cached acquire entry
Definition at line 138 of file trap_manager.c.
References DESTROY_IF, dst, and free().
Referenced by complete(), and METHOD().
 {
     DESTROY_IF(this->dst);
     free(this);
 }
static void destroy_entry (entry_t * this) static
actually uninstall and destroy an installed entry
Definition at line 127 of file trap_manager.c.
References free(), and name.
Referenced by METHOD().
 {
     this->child_sa->destroy(this->child_sa);
     this->peer_cfg->destroy(this->peer_cfg);
     free(this->name);
     free(this);
 }
METHOD (trap_manager_t , install , u_int32_t , private_trap_manager_t * this, peer_cfg_t * peer, child_cfg_t * child, u_int32_t reqid)
Definition at line 160 of file trap_manager.c.
References child_sa_t::add_policies, entry_t::child_sa, child_sa_create(), condvar, DBG1, DBG_CFG, enumerator_t::destroy, host_t::destroy, destroy(), destroy_entry(), DESTROY_IF, linked_list_t::destroy_offset, enumerator_t::enumerate, FALSE, found, host_t::get_family, linked_list_t::get_first, peer_cfg_t::get_ike_cfg, child_cfg_t::get_mode, ike_cfg_t::get_my_port, child_cfg_t::get_name, child_cfg_t::get_proposals, proposal_t::get_protocol, peer_cfg_t::get_ref, child_sa_t::get_reqid, kernel_interface_t::get_source_addr, child_cfg_t::get_traffic_selectors, host_create_any(), hydra, INIT, INSTALL_DISABLED, host_t::is_anyaddr, hydra_t::kernel_interface, linked_list_create_with_items(), list, lock, me, MODE_TRANSPORT, name, entry_t::name, proposal, proto, PROTO_ESP, ike_cfg_t::resolve_me, ike_cfg_t::resolve_other, child_sa_t::set_mode, host_t::set_port, child_sa_t::set_protocol, condvar_t::signal, status, strdup, streq(), SUCCESS, TRUE, and spinlock_t::unlock.
 {
     entry_t *entry, *found = NULL;
     ike_cfg_t *ike_cfg;
     child_sa_t *child_sa;
     host_t *me, *other;
     linked_list_t *my_ts, *other_ts, *list;
     enumerator_t *enumerator;
     status_t status;
     linked_list_t *proposals;
     proposal_t *proposal;
     protocol_id_t proto = PROTO_ESP;
     bool wildcard = FALSE;
     /* try to resolve addresses */
     ike_cfg = peer->get_ike_cfg(peer);
     other = ike_cfg->resolve_other(ike_cfg, AF_UNSPEC);
     if (other && other->is_anyaddr(other) &&
         child->get_mode(child) == MODE_TRANSPORT)
     {
         /* allow wildcard for Transport Mode SAs */
         me = host_create_any(other->get_family(other));
         wildcard = TRUE;
     }
     else if (!other || other->is_anyaddr(other))
     {
         DESTROY_IF(other);
         DBG1(DBG_CFG, "installing trap failed, remote address unknown");
         return 0;
     }
     else
     {
         me = ike_cfg->resolve_me(ike_cfg, other->get_family(other));
         if (!me || me->is_anyaddr(me))
         {
             DESTROY_IF(me);
             me = hydra->kernel_interface->get_source_addr(
                                         hydra->kernel_interface, other, NULL);
             if (!me)
             {
                 DBG1(DBG_CFG, "installing trap failed, local address unknown");
                 other->destroy(other);
                 return 0;
             }
             me->set_port(me, ike_cfg->get_my_port(ike_cfg));
         }
     }
     this->lock->write_lock(this->lock);
     if (this->installing == INSTALL_DISABLED)
     {   /* flush() has been called */
         this->lock->unlock(this->lock);
         other->destroy(other);
         me->destroy(me);
         return 0;
     }
     enumerator = this->traps->create_enumerator(this->traps);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (streq(entry->name, child->get_name(child)))
         {
             found = entry;
             if (entry->child_sa)
             {   /* replace it with an updated version, if already installed */
                 this->traps->remove_at(this->traps, enumerator);
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (found)
     {
         if (!found->child_sa)
         {
             DBG1(DBG_CFG, "CHILD_SA '%s' is already being routed", found->name);
             this->lock->unlock(this->lock);
             other->destroy(other);
             me->destroy(me);
             return 0;
         }
         /* config might have changed so update everything */
         DBG1(DBG_CFG, "updating already routed CHILD_SA '%s'", found->name);
         reqid = found->child_sa->get_reqid(found->child_sa);
     }
     INIT(entry,
         .name = strdup(child->get_name(child)),
         .peer_cfg = peer->get_ref(peer),
         .wildcard = wildcard,
     );
     this->traps->insert_first(this->traps, entry);
     this->installing++;
     /* don't hold lock while creating CHILD_SA and installing policies */
     this->lock->unlock(this->lock);
     /* create and route CHILD_SA */
     child_sa = child_sa_create(me, other, child, reqid, FALSE, 0, 0);
     list = linked_list_create_with_items(me, NULL);
     my_ts = child->get_traffic_selectors(child, TRUE, NULL, list);
     list->destroy_offset(list, offsetof(host_t, destroy));
     list = linked_list_create_with_items(other, NULL);
     other_ts = child->get_traffic_selectors(child, FALSE, NULL, list);
     list->destroy_offset(list, offsetof(host_t, destroy));
     /* We don't know the finally negotiated protocol (ESP|AH), we install
      * the SA with the protocol of the first proposal */
     proposals = child->get_proposals(child, TRUE);
     if (proposals->get_first(proposals, (void**)&proposal) == SUCCESS)
     {
         proto = proposal->get_protocol(proposal);
     }
     proposals->destroy_offset(proposals, offsetof(proposal_t, destroy));
     child_sa->set_protocol(child_sa, proto);
     child_sa->set_mode(child_sa, child->get_mode(child));
     status = child_sa->add_policies(child_sa, my_ts, other_ts);
     my_ts->destroy_offset(my_ts, offsetof(traffic_selector_t, destroy));
     other_ts->destroy_offset(other_ts, offsetof(traffic_selector_t, destroy));
     if (status != SUCCESS)
     {
         DBG1(DBG_CFG, "installing trap failed");
         this->lock->write_lock(this->lock);
         this->traps->remove(this->traps, entry, NULL);
         this->lock->unlock(this->lock);
         entry->child_sa = child_sa;
         destroy_entry(entry);
         reqid = 0;
     }
     else
     {
         reqid = child_sa->get_reqid(child_sa);
         this->lock->write_lock(this->lock);
         entry->child_sa = child_sa;
         this->lock->unlock(this->lock);
     }
     if (found)
     {
         destroy_entry(found);
     }
     this->lock->write_lock(this->lock);
     /* do this at the end, so entries created temporarily are also destroyed */
     this->installing--;
     this->condvar->signal(this->condvar);
     this->lock->unlock(this->lock);
     return reqid;
 }
METHOD (trap_manager_t , uninstall , bool , private_trap_manager_t * this, u_int32_t reqid)
Definition at line 311 of file trap_manager.c.
References entry_t::child_sa, DBG1, DBG_CFG, enumerator_t::destroy, destroy_entry(), enumerator_t::enumerate, FALSE, found, child_sa_t::get_reqid, lock, TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry, *found = NULL;
     this->lock->write_lock(this->lock);
     enumerator = this->traps->create_enumerator(this->traps);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->child_sa &&
             entry->child_sa->get_reqid(entry->child_sa) == reqid)
         {
             this->traps->remove_at(this->traps, enumerator);
             found = entry;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!found)
     {
         DBG1(DBG_CFG, "trap %d not found to uninstall", reqid);
         return FALSE;
     }
     destroy_entry(found);
     return TRUE;
 }
METHOD (trap_manager_t , create_enumerator , enumerator_t * , private_trap_manager_t * this)
Definition at line 362 of file trap_manager.c.
References enumerator_create_filter(), lock, trap_filter(), and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_filter(this->traps->create_enumerator(this->traps),
                                     (void*)trap_filter, this->lock,
                                     (void*)this->lock->unlock);
 }
METHOD (trap_manager_t , find_reqid , u_int32_t , private_trap_manager_t * this, child_cfg_t * child)
Definition at line 371 of file trap_manager.c.
References entry_t::child_sa, enumerator_t::destroy, enumerator_t::enumerate, child_cfg_t::get_name, child_sa_t::get_reqid, lock, entry_t::name, streq(), and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     u_int32_t reqid = 0;
     this->lock->read_lock(this->lock);
     enumerator = this->traps->create_enumerator(this->traps);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (streq(entry->name, child->get_name(child)))
         {
             if (entry->child_sa)
             {
                 reqid = entry->child_sa->get_reqid(entry->child_sa);
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return reqid;
 }
METHOD (trap_manager_t , acquire , void , private_trap_manager_t * this, u_int32_t reqid, traffic_selector_t * src, traffic_selector_t * dst)
Definition at line 396 of file trap_manager.c.
References acquire(), acquire_by_dst(), acquire_by_reqid(), daemon_t::bus, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout_by_config, ike_sa_manager_t::checkout_new, entry_t::child_sa, DBG1, DBG_CFG, enumerator_t::destroy, host_t::destroy, child_cfg_t::destroy, peer_cfg_t::destroy, destroy_acquire(), DESTROY_ME, enumerator_t::enumerate, FALSE, found, child_sa_t::get_config, ike_sa_t::get_ike_cfg, peer_cfg_t::get_ike_version, ike_cfg_t::get_my_port, ike_cfg_t::get_other_port, ike_sa_t::get_peer_cfg, child_cfg_t::get_ref, peer_cfg_t::get_ref, child_sa_t::get_reqid, ike_sa_t::get_version, host, ignore(), acquire_t::ike_sa, daemon_t::ike_sa_manager, IKEV1, INIT, ike_sa_t::initiate, mutex_t::lock, lock, mask, mutex, entry_t::peer_cfg, port, ike_sa_t::set_my_host, ike_sa_t::set_other_host, ike_sa_t::set_peer_cfg, host_t::set_port, bus_t::set_sa, SUCCESS, traffic_selector_t::to_subnet, TRUE, spinlock_t::unlock, mutex_t::unlock, and entry_t::wildcard.
 {
     enumerator_t *enumerator;
     entry_t *entry, *found = NULL;
     acquire_t *acquire;
     peer_cfg_t *peer;
     child_cfg_t *child;
     ike_sa_t *ike_sa;
     host_t *host;
     bool wildcard, ignore = FALSE;
     this->lock->read_lock(this->lock);
     enumerator = this->traps->create_enumerator(this->traps);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->child_sa &&
             entry->child_sa->get_reqid(entry->child_sa) == reqid)
         {
             found = entry;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         DBG1(DBG_CFG, "trap not found, unable to acquire reqid %d", reqid);
         this->lock->unlock(this->lock);
         return;
     }
     reqid = found->child_sa->get_reqid(found->child_sa);
     wildcard = found->wildcard;
     this->mutex->lock(this->mutex);
     if (wildcard)
     {   /* for wildcard acquires we check that we don't have a pending acquire
          * with the same peer */
         u_int8_t mask;
         dst->to_subnet(dst, &host, &mask);
         if (this->acquires->find_first(this->acquires, (void*)acquire_by_dst,
                                       (void**)&acquire, host) == SUCCESS)
         {
             host->destroy(host);
             ignore = TRUE;
         }
         else
         {
             INIT(acquire,
                 .dst = host,
                 .reqid = reqid,
             );
             this->acquires->insert_last(this->acquires, acquire);
         }
     }
     else
     {
         if (this->acquires->find_first(this->acquires, (void*)acquire_by_reqid,
                                       (void**)&acquire, &reqid) == SUCCESS)
         {
             ignore = TRUE;
         }
         else
         {
             INIT(acquire,
                 .reqid = reqid,
             );
             this->acquires->insert_last(this->acquires, acquire);
         }
     }
     this->mutex->unlock(this->mutex);
     if (ignore)
     {
         DBG1(DBG_CFG, "ignoring acquire, connection attempt pending");
         this->lock->unlock(this->lock);
         return;
     }
     peer = found->peer_cfg->get_ref(found->peer_cfg);
     child = found->child_sa->get_config(found->child_sa);
     child = child->get_ref(child);
     /* don't hold the lock while checking out the IKE_SA */
     this->lock->unlock(this->lock);
     if (wildcard)
     {   /* the peer config would match IKE_SAs with other peers */
         ike_sa = charon->ike_sa_manager->checkout_new(charon->ike_sa_manager,
                                             peer->get_ike_version(peer), TRUE);
         if (ike_sa)
         {
             ike_cfg_t *ike_cfg;
             u_int16_t port;
             u_int8_t mask;
             ike_sa->set_peer_cfg(ike_sa, peer);
             ike_cfg = ike_sa->get_ike_cfg(ike_sa);
             port = ike_cfg->get_other_port(ike_cfg);
             dst->to_subnet(dst, &host, &mask);
             host->set_port(host, port);
             ike_sa->set_other_host(ike_sa, host);
             port = ike_cfg->get_my_port(ike_cfg);
             src->to_subnet(src, &host, &mask);
             host->set_port(host, port);
             ike_sa->set_my_host(ike_sa, host);
             charon->bus->set_sa(charon->bus, ike_sa);
         }
     }
     else
     {
         ike_sa = charon->ike_sa_manager->checkout_by_config(
                                             charon->ike_sa_manager, peer);
     }
     if (ike_sa)
     {
         if (ike_sa->get_peer_cfg(ike_sa) == NULL)
         {
             ike_sa->set_peer_cfg(ike_sa, peer);
         }
         if (this->ignore_acquire_ts || ike_sa->get_version(ike_sa) == IKEV1)
         {   /* in IKEv1, don't prepend the acquiring packet TS, as we only
              * have a single TS that we can establish in a Quick Mode. */
             src = dst = NULL;
         }
         this->mutex->lock(this->mutex);
         acquire->ike_sa = ike_sa;
         this->mutex->unlock(this->mutex);
         if (ike_sa->initiate(ike_sa, child, reqid, src, dst) != DESTROY_ME)
         {
             charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
         }
         else
         {
             charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                         ike_sa);
         }
     }
     else
     {
         this->mutex->lock(this->mutex);
         this->acquires->remove(this->acquires, acquire, NULL);
         this->mutex->unlock(this->mutex);
         destroy_acquire(acquire);
         child->destroy(child);
     }
     peer->destroy(peer);
 }
METHOD (listener_t , ike_state_change , bool , trap_listener_t * listener, ike_sa_t * ike_sa, ike_sa_state_t state)
Definition at line 585 of file trap_manager.c.
References complete(), IKE_DESTROYING, trap_listener_t::traps, and TRUE.
 {
     switch (state)
     {
         case IKE_DESTROYING:
             complete(listener->traps, ike_sa, NULL);
             return TRUE;
         default:
             return TRUE;
     }
 }
METHOD (listener_t , child_state_change , bool , trap_listener_t * listener, ike_sa_t * ike_sa, child_sa_t * child_sa, child_sa_state_t state)
Definition at line 598 of file trap_manager.c.
References CHILD_DESTROYING, CHILD_INSTALLED, complete(), trap_listener_t::traps, and TRUE.
 {
     switch (state)
     {
         case CHILD_INSTALLED:
         case CHILD_DESTROYING:
             complete(listener->traps, ike_sa, child_sa);
             return TRUE;
         default:
             return TRUE;
     }
 }
METHOD (trap_manager_t , flush , void , private_trap_manager_t * this)
Definition at line 613 of file trap_manager.c.
References condvar, destroy_entry(), INSTALL_DISABLED, linked_list_create(), lock, spinlock_t::unlock, and condvar_t::wait.
 {
     this->lock->write_lock(this->lock);
     while (this->installing)
     {
         this->condvar->wait(this->condvar, this->lock);
     }
     this->traps->destroy_function(this->traps, (void*)destroy_entry);
     this->traps = linked_list_create();
     this->installing = INSTALL_DISABLED;
     this->lock->unlock(this->lock);
 }
METHOD (trap_manager_t , destroy , void , private_trap_manager_t * this)
Definition at line 627 of file trap_manager.c.
References daemon_t::bus, charon, condvar, spinlock_t::destroy, mutex_t::destroy, condvar_t::destroy, destroy_acquire(), destroy_entry(), free(), lock, mutex, and bus_t::remove_listener.
 {
     charon->bus->remove_listener(charon->bus, &this->listener.listener);
     this->traps->destroy_function(this->traps, (void*)destroy_entry);
     this->acquires->destroy_function(this->acquires, (void*)destroy_acquire);
     this->condvar->destroy(this->condvar);
     this->mutex->destroy(this->mutex);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool trap_filter (rwlock_t * lock, entry_t ** entry, peer_cfg_t ** peer_cfg, void * none, child_sa_t ** child_sa) static
convert enumerated entries to peer_cfg, child_sa
Definition at line 344 of file trap_manager.c.
References FALSE, and TRUE.
Referenced by METHOD().
 {
     if (!(*entry)->child_sa)
     {   /* skip entries that are currently being installed */
         return FALSE;
     }
     if (peer_cfg)
     {
         *peer_cfg = (*entry)->peer_cfg;
     }
     if (child_sa)
     {
         *child_sa = (*entry)->child_sa;
     }
     return TRUE;
 }