strongSwan: imv_msg.c File Reference
imv_msg.c File Reference
#include "imv_msg.h"
#include "ietf/ietf_attr.h"
#include "ietf/ietf_attr_assess_result.h"
#include "ietf/ietf_attr_remediation_instr.h"
#include "tcg/seg/tcg_seg_attr_max_size.h"
#include "tcg/seg/tcg_seg_attr_seg_env.h"
#include "tcg/seg/tcg_seg_attr_next_seg.h"
#include <tncif_names.h>
#include <tncif_pa_subtypes.h>
#include <pen/pen.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_imv_msg_t
Typedefs
typedef struct private_imv_msg_t private_imv_msg_t
Functions
METHOD (imv_msg_t, get_src_id, TNC_UInt32, private_imv_msg_t *this)
METHOD (imv_msg_t, get_dst_id, TNC_UInt32, private_imv_msg_t *this)
METHOD (imv_msg_t, set_msg_type, void, private_imv_msg_t *this, pen_type_t msg_type)
METHOD (imv_msg_t, get_msg_type, pen_type_t, private_imv_msg_t *this)
METHOD (imv_msg_t, add_attribute, void, private_imv_msg_t *this, pa_tnc_attr_t *attr)
METHOD (imv_msg_t, send_, TNC_Result, private_imv_msg_t *this, bool excl)
METHOD (imv_msg_t, send_assessment, TNC_Result, private_imv_msg_t *this)
METHOD (imv_msg_t, receive, TNC_Result, private_imv_msg_t *this, imv_msg_t *out_msg, bool *fatal_error)
METHOD (imv_msg_t, get_attribute_count, int, private_imv_msg_t *this)
METHOD (imv_msg_t, create_attribute_enumerator, enumerator_t *, private_imv_msg_t *this)
METHOD (imv_msg_t, get_encoding, chunk_t, private_imv_msg_t *this)
METHOD (imv_msg_t, destroy, void, private_imv_msg_t *this)
imv_msg_t * imv_msg_create (imv_agent_t *agent, imv_state_t *state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, pen_type_t msg_type)
imv_msg_t * imv_msg_create_as_reply (imv_msg_t *msg)
imv_msg_t * imv_msg_create_from_data (imv_agent_t *agent, imv_state_t *state, TNC_ConnectionID connection_id, TNC_MessageType msg_type, chunk_t msg)
imv_msg_t * imv_msg_create_from_long_data (imv_agent_t *agent, imv_state_t *state, TNC_ConnectionID connection_id, TNC_UInt32 src_id, TNC_UInt32 dst_id, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, chunk_t msg)
Typedef Documentation
typedef struct private_imv_msg_t private_imv_msg_t
Definition at line 32 of file imv_msg.c.
Function Documentation
METHOD (imv_msg_t , get_src_id , TNC_UInt32 , private_imv_msg_t * this)
Definition at line 86 of file imv_msg.c.
 {
     return this->src_id;
 }
METHOD (imv_msg_t , get_dst_id , TNC_UInt32 , private_imv_msg_t * this)
Definition at line 92 of file imv_msg.c.
 {
     return this->dst_id;
 }
METHOD (imv_msg_t , set_msg_type , void , private_imv_msg_t * this, pen_type_t msg_type)
Definition at line 98 of file imv_msg.c.
References TNC_IMCID_ANY, pen_type_t::type, and pen_type_t::vendor_id.
 {
     if (msg_type.vendor_id != this->msg_type.vendor_id ||
         msg_type.type != this->msg_type.type)
     {
         this->msg_type = msg_type;
         this->dst_id = TNC_IMCID_ANY;
     }
 }
METHOD (imv_msg_t , get_msg_type , pen_type_t , private_imv_msg_t * this)
Definition at line 109 of file imv_msg.c.
 {
     return this->msg_type;
 }
METHOD (imv_msg_t , add_attribute , void , private_imv_msg_t * this, pa_tnc_attr_t * attr)
Definition at line 115 of file imv_msg.c.
 {
     this->attr_list->insert_last(this->attr_list, attr);
 }
METHOD (imv_msg_t , send_ , TNC_Result , private_imv_msg_t * this, bool excl)
Definition at line 121 of file imv_msg.c.
References pa_tnc_msg_t::add_attribute, pa_tnc_msg_t::build, seg_contract_t::check_size, DBG1, DBG3, DBG_IMV, enumerator_t::destroy, pa_tnc_attr_t::destroy, pa_tnc_msg_t::destroy, enumerator_t::enumerate, FALSE, seg_contract_t::first_segment, seg_contract_manager_t::get_contract, pa_tnc_msg_t::get_encoding, pa_tnc_msg_t::get_space, chunk_t::len, msg, PA_TNC_ATTR_HEADER_SIZE, pa_tnc_msg_create(), chunk_t::ptr, result, TCG_SEG_ATTR_SEG_ENV_HEADER, TNC_IMCID_ANY, TNC_MESSAGE_FLAGS_EXCLUSIVE, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, and TRUE.
 {
     pa_tnc_msg_t *pa_tnc_msg;
     pa_tnc_attr_t *attr;
     TNC_UInt32 msg_flags;
     TNC_MessageType msg_type;
     size_t max_msg_len, min_seg_attr_len, space_left;
     bool attr_added, oversize;
     chunk_t msg;
     seg_contract_t *contract;
     seg_contract_manager_t *contracts;
     enumerator_t *enumerator;
     TNC_Result result = TNC_RESULT_SUCCESS;
     /* Get IF-M segmentation contract for this subtype if any */
     contracts = this->state->get_contracts(this->state);
     contract = contracts->get_contract(contracts, this->msg_type,
                                        FALSE, this->dst_id);
     /* Retrieve maximum allowed PA-TNC message size if set */
     max_msg_len = this->state->get_max_msg_len(this->state);
     /* Minimum size needed for Segmentation Envelope Attribute */
     min_seg_attr_len = PA_TNC_ATTR_HEADER_SIZE + TCG_SEG_ATTR_SEG_ENV_HEADER +
                        PA_TNC_ATTR_HEADER_SIZE;
     while (this->attr_list->get_count(this->attr_list))
     {
         pa_tnc_msg = pa_tnc_msg_create(max_msg_len);
         attr_added = FALSE;
         enumerator = this->attr_list->create_enumerator(this->attr_list);
         while (enumerator->enumerate(enumerator, &attr))
         {
             space_left = pa_tnc_msg->get_space(pa_tnc_msg);
             if (contract && contract->check_size(contract, attr, &oversize))
             {
                 if (oversize)
                 {
                     /* TODO handle oversized attributes */
                 }
                 else if (max_msg_len == 0 || space_left >= min_seg_attr_len)
                 {
                     attr = contract->first_segment(contract, attr, space_left);
                 }
                 else
                 {
                     /* segment attribute in next iteration */
                     break;
                 }
             }
             if (pa_tnc_msg->add_attribute(pa_tnc_msg, attr))
             {
                 attr_added = TRUE;
             }
             else
             {
                 if (attr_added)
                 {
                     /* there might be space for attribute in next iteration */
                     break;
                 }
                 else
                 {
                     DBG1(DBG_IMV, "PA-TNC attribute too large to send, deleted");
                     attr->destroy(attr);
                 }
             }
             this->attr_list->remove_at(this->attr_list, enumerator);
         }
         enumerator->destroy(enumerator);
         /* build and send the PA-TNC message via the IF-IMV interface */
         if (!pa_tnc_msg->build(pa_tnc_msg))
         {
             pa_tnc_msg->destroy(pa_tnc_msg);
             return TNC_RESULT_FATAL;
         }
         msg = pa_tnc_msg->get_encoding(pa_tnc_msg);
         DBG3(DBG_IMV, "created PA-TNC message: %B", &msg);
         if (this->state->has_long(this->state) && this->agent->send_message_long)
         {
             excl = excl && this->state->has_excl(this->state) &&
                            this->dst_id != TNC_IMCID_ANY;
             msg_flags = excl ? TNC_MESSAGE_FLAGS_EXCLUSIVE : 0;
             result = this->agent->send_message_long(this->src_id,
                             this->connection_id, msg_flags, msg.ptr, msg.len,
                             this->msg_type.vendor_id, this->msg_type.type,
                             this->dst_id);
         }
         else if (this->agent->send_message)
         {
             msg_type = (this->msg_type.vendor_id << 8) |
                        (this->msg_type.type & 0x000000ff);
             result = this->agent->send_message(this->src_id, this->connection_id,
                                                msg.ptr, msg.len, msg_type);
         }
         pa_tnc_msg->destroy(pa_tnc_msg);
         if (result != TNC_RESULT_SUCCESS)
         {
             break;
         }
     }
     return result;
 }
METHOD (imv_msg_t , send_assessment , TNC_Result , private_imv_msg_t * this)
Definition at line 232 of file imv_msg.c.
References add_attribute(), chunk_create(), chunk_empty, enumerator_t::destroy, pa_tnc_attr_t::destroy, settings_t::get_bool, ietf_attr_assess_result_create(), ietf_attr_remediation_instr_create_from_string(), ietf_attr_remediation_instr_create_from_uri(), len, lib, library_t::ns, library_t::settings, SUCCESS, TNC_IMV_EVALUATION_RESULT_COMPLIANT, TNC_RESULT_SUCCESS, TRUE, and uri.
 {
     TNC_IMV_Action_Recommendation rec;
     TNC_IMV_Evaluation_Result eval;
     pa_tnc_attr_t *attr;
     chunk_t string = chunk_empty;
     char *lang_code = NULL, *uri = NULL;
     enumerator_t *e;
     /* Remove any attributes that have already been constructed */
     while (this->attr_list->remove_last(this->attr_list, (void**)&attr) == SUCCESS)
     {
         attr->destroy(attr);
     }
     /* Send an IETF Assessment Result attribute if enabled */
     if (lib->settings->get_bool(lib->settings, "%s.imcv.assessment_result",
                                 TRUE, lib->ns))
     {
         this->state->get_recommendation(this->state, &rec, &eval);
         attr = ietf_attr_assess_result_create(eval);
         add_attribute(this, attr);
         /* Send IETF Remediation Instructions if available */
         if (eval != TNC_IMV_EVALUATION_RESULT_COMPLIANT)
         {
             e = this->agent->create_language_enumerator(this->agent,
                                     this->state);
             if (this->state->get_remediation_instructions(this->state,
                                     e, &string, &lang_code, &uri))
             {
                 if (string.len && lang_code)
                 {
                     attr = ietf_attr_remediation_instr_create_from_string(string,
                                     chunk_create(lang_code, strlen(lang_code)));
                     add_attribute(this, attr);
                 }
                 if (uri)
                 {
                     attr = ietf_attr_remediation_instr_create_from_uri(
                                     chunk_create(uri, strlen(uri)));
                     add_attribute(this, attr);
                 }
             }
             e->destroy(e);
         }
         /* send PA-TNC message with the excl flag set */
         return send_(this, TRUE);
     }
     return TNC_RESULT_SUCCESS;
 }
METHOD (imv_msg_t , receive , TNC_Result , private_imv_msg_t * this, imv_msg_t * out_msg, bool * fatal_error)
Definition at line 286 of file imv_msg.c.
References imv_msg_t::add_attribute, seg_contract_manager_t::add_contract, seg_contract_t::add_segment, BUF_LEN, seg_contract_t::clone, DBG1, DBG2, DBG3, DBG_IMV, enumerator_t::destroy, enumerator_t::enumerate, FAILED, FALSE, tcg_seg_attr_max_size_t::get_attr_size, tcg_seg_attr_next_seg_t::get_base_attr_id, tcg_seg_attr_seg_env_t::get_base_attr_id, seg_contract_manager_t::get_contract, seg_contract_t::get_info_string, seg_contract_t::get_max_size, pa_tnc_attr_t::get_ref, pa_tnc_attr_t::get_type, max_seg_size, msg, seg_contract_t::next_segment, PA_TNC_ATTR_HEADER_SIZE, PA_TNC_HEADER_SIZE, PEN_TCG, result, seg_contract_create(), SEG_CONTRACT_NO_FRAGMENTATION, seg_contract_t::set_max_size, seg_contract_t::set_responder, SUCCESS, tcg_seg_attr_max_size_create(), tcg_seg_attr_next_seg_create(), TCG_SEG_ATTR_SEG_ENV, TCG_SEG_ATTR_SEG_ENV_HEADER, TCG_SEG_MAX_ATTR_SIZE_REQ, TCG_SEG_MAX_ATTR_SIZE_RESP, TCG_SEG_NEXT_SEG_REQ, TNC_IMCID_ANY, TNC_IMVID_ANY, TNC_RESULT_FATAL, TNC_RESULT_SUCCESS, TRUE, type, pen_type_t::type, pen_type_t::vendor_id, and VERIFY_ERROR.
 {
     TNC_Result result = TNC_RESULT_SUCCESS;
     TNC_UInt32 target_imv_id;
     linked_list_t *non_fatal_types;
     enumerator_t *enumerator;
     pa_tnc_attr_t *attr;
     chunk_t msg;
     if (this->state->has_long(this->state))
     {
         if (this->dst_id != TNC_IMVID_ANY)
         {
             DBG2(DBG_IMV, "IMV %u \"%s\" received message for Connection ID %u "
                           "from IMC %u to IMV %u",
                            this->agent->get_id(this->agent),
                            this->agent->get_name(this->agent),
                            this->connection_id, this->src_id, this->dst_id);
         }
         else
         {
             DBG2(DBG_IMV, "IMV %u \"%s\" received message for Connection ID %u "
                           "from IMC %u", this->agent->get_id(this->agent),
                            this->agent->get_name(this->agent),
                            this->connection_id, this->src_id);
         }
     }
     else
     {
         DBG2(DBG_IMV, "IMV %u \"%s\" received message for Connection ID %u",
                        this->agent->get_id(this->agent),
                        this->agent->get_name(this->agent),
                        this->connection_id);
     }
     msg = this->pa_msg->get_encoding(this->pa_msg);
     DBG3(DBG_IMV, "%B", &msg);
     switch (this->pa_msg->process(this->pa_msg))
     {
         case SUCCESS:
             break;
         case VERIFY_ERROR:
         {
             /* extract and copy by reference all error attributes */
             enumerator = this->pa_msg->create_error_enumerator(this->pa_msg);
             while (enumerator->enumerate(enumerator, &attr))
             {
                 out_msg->add_attribute(out_msg, attr->get_ref(attr));
             }
             enumerator->destroy(enumerator);
         }
         case FAILED:
         default:
             return TNC_RESULT_FATAL;
     }
     /* determine target IMV ID */
     target_imv_id = (this->dst_id != TNC_IMVID_ANY) ?
                      this->dst_id : this->agent->get_id(this->agent);
     /* process IF-M segmentation attributes */
     enumerator = this->pa_msg->create_attribute_enumerator(this->pa_msg);
     while (enumerator->enumerate(enumerator, &attr))
     {
         uint32_t max_attr_size, max_seg_size, my_max_attr_size, my_max_seg_size;
         seg_contract_manager_t *contracts;
         seg_contract_t *contract;
         char buf[BUF_LEN];
         pen_type_t type;
         type = attr->get_type(attr);
         if (type.vendor_id != PEN_TCG)
         {
             continue;
         }
         contracts = this->state->get_contracts(this->state);
         switch (type.type)
         {
             case TCG_SEG_MAX_ATTR_SIZE_REQ:
             {
                 tcg_seg_attr_max_size_t *attr_cast;
                 attr_cast = (tcg_seg_attr_max_size_t*)attr;
                 attr_cast->get_attr_size(attr_cast, &max_attr_size,
                                                     &max_seg_size);
                 contract = contracts->get_contract(contracts, this->msg_type,
                                                    FALSE, this->src_id);
                 if (contract)
                 {
                     contract->set_max_size(contract, max_attr_size,
                                                      max_seg_size);
                 }
                 else
                 {
                     contract = seg_contract_create(this->msg_type, max_attr_size,
                                     max_seg_size, FALSE, this->src_id, FALSE);
                     contract->set_responder(contract, target_imv_id);
                     contracts->add_contract(contracts, contract);
                 }
                 contract->get_info_string(contract, buf, BUF_LEN, TRUE);
                 DBG2(DBG_IMV, "%s", buf);
                 /* Determine maximum PA-TNC attribute segment size */
                 my_max_seg_size = this->state->get_max_msg_len(this->state)
                                     - PA_TNC_HEADER_SIZE
                                     - PA_TNC_ATTR_HEADER_SIZE
                                     - TCG_SEG_ATTR_SEG_ENV_HEADER;
                 /* If segmentation is possible select lower segment size */
                 if (max_seg_size != SEG_CONTRACT_NO_FRAGMENTATION &&
                     max_seg_size > my_max_seg_size)
                 {
                     max_seg_size = my_max_seg_size;
                     contract->set_max_size(contract, max_attr_size,
                                                      max_seg_size);
                     DBG2(DBG_IMV, "  lowered maximum segment size to %u bytes",
                          max_seg_size);
                 }
                 /* Add Maximum Attribute Size Response attribute */
                 attr = tcg_seg_attr_max_size_create(max_attr_size,
                                                     max_seg_size, FALSE);
                 out_msg->add_attribute(out_msg, attr);
                 break;
             }
             case TCG_SEG_MAX_ATTR_SIZE_RESP:
             {
                 tcg_seg_attr_max_size_t *attr_cast;
                 attr_cast = (tcg_seg_attr_max_size_t*)attr;
                 attr_cast->get_attr_size(attr_cast, &max_attr_size,
                                                     &max_seg_size);
                 contract = contracts->get_contract(contracts, this->msg_type,
                                                    TRUE, this->src_id);
                 if (!contract)
                 {
                     contract = contracts->get_contract(contracts, this->msg_type,
                                                    TRUE, TNC_IMCID_ANY);
                     if (contract)
                     {
                         contract = contract->clone(contract);
                         contract->set_responder(contract, this->src_id);
                         contracts->add_contract(contracts, contract);
                     }
                 }
                 if (contract)
                 {
                     contract->get_max_size(contract, &my_max_attr_size,
                                                      &my_max_seg_size);
                     if (my_max_seg_size != SEG_CONTRACT_NO_FRAGMENTATION &&
                         my_max_seg_size > max_seg_size)
                     {
                         my_max_seg_size = max_seg_size;
                         contract->set_max_size(contract, my_max_attr_size,
                                                          my_max_seg_size);
                     }
                     contract->get_info_string(contract, buf, BUF_LEN, FALSE);
                     DBG2(DBG_IMV, "%s", buf);
                 }
                 else
                 {
                     /* TODO no request pending */
                     DBG1(DBG_IMV, "no contract for this PA message type found");
                 }
                 break;
             }
             case TCG_SEG_ATTR_SEG_ENV:
             {
                 tcg_seg_attr_seg_env_t *seg_env_attr;
                 pa_tnc_attr_t *error;
                 uint32_t base_attr_id;
                 bool more;
                 seg_env_attr = (tcg_seg_attr_seg_env_t*)attr;
                 base_attr_id = seg_env_attr->get_base_attr_id(seg_env_attr);
                 contract = contracts->get_contract(contracts, this->msg_type,
                                                    TRUE, this->src_id);
                 if (!contract)
                 {
                     DBG2(DBG_IMV, "no contract for received attribute segment "
                          "with base attribute ID %u", base_attr_id);
                     continue;
                 }
                 attr = contract->add_segment(contract, attr, &error, &more);
                 if (error)
                 {
                     out_msg->add_attribute(out_msg, error);
                 }
                 if (attr)
                 {
                     this->pa_msg->add_attribute(this->pa_msg, attr);
                 }
                 if (more)
                 {
                     /* Send Next Segment Request */
                     attr = tcg_seg_attr_next_seg_create(base_attr_id, FALSE);
                     out_msg->add_attribute(out_msg, attr);
                 }
                 break;
             }
             case TCG_SEG_NEXT_SEG_REQ:
             {
                 tcg_seg_attr_next_seg_t *attr_cast;
                 uint32_t base_attr_id;
                 attr_cast = (tcg_seg_attr_next_seg_t*)attr;
                 base_attr_id = attr_cast->get_base_attr_id(attr_cast);
                 contract = contracts->get_contract(contracts, this->msg_type,
                                                    FALSE, this->src_id);
                 if (!contract)
                 {
                     /* TODO no contract - generate error message */
                     DBG1(DBG_IMV, "no contract for received next segment "
                          "request with base attribute ID %u", base_attr_id);
                     continue;
                 }
                 attr = contract->next_segment(contract, base_attr_id);
                 if (attr)
                 {
                     out_msg->add_attribute(out_msg, attr);
                 }
                 else
                 {
                     /* TODO no more segments - generate error message */
                     DBG1(DBG_IMV, "no more segments found for "
                          "base attribute ID %u", base_attr_id);
                 }
                 break;
             }
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     /* preprocess any received IETF standard error attributes */
     non_fatal_types = this->agent->get_non_fatal_attr_types(this->agent);
     *fatal_error = this->pa_msg->process_ietf_std_errors(this->pa_msg,
                                                          non_fatal_types);
     return result;
 }
METHOD (imv_msg_t , get_attribute_count , int , private_imv_msg_t * this)
Definition at line 535 of file imv_msg.c.
 {
     return this->attr_list->get_count(this->attr_list);
 }
METHOD (imv_msg_t , create_attribute_enumerator , enumerator_t * , private_imv_msg_t * this)
Definition at line 541 of file imv_msg.c.
 {
     return this->pa_msg->create_attribute_enumerator(this->pa_msg);
 }
METHOD (imv_msg_t , get_encoding , chunk_t , private_imv_msg_t * this)
Definition at line 547 of file imv_msg.c.
References chunk_empty.
 {
     if (this->pa_msg)
     {
         return this->pa_msg->get_encoding(this->pa_msg);
     }
     return chunk_empty;
 }
METHOD (imv_msg_t , destroy , void , private_imv_msg_t * this)
Definition at line 557 of file imv_msg.c.
References destroy(), DESTROY_IF, and free().
 {
     this->attr_list->destroy_offset(this->attr_list,
                                     offsetof(pa_tnc_attr_t, destroy));
     DESTROY_IF(this->pa_msg);
     free(this);
 }