strongSwan: tcg_swid_attr_req.c File Reference
tcg_swid_attr_req.c File Reference
#include "tcg_swid_attr_req.h"
#include "swid/swid_tag_id.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
Classes
struct private_tcg_swid_attr_req_t
Macros
#define SWID_REQ_RESERVED_MASK 0xE0
Typedefs
typedef struct
private_tcg_swid_attr_req_t private_tcg_swid_attr_req_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_swid_attr_req_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_swid_attr_req_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_swid_attr_req_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_swid_attr_req_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_swid_attr_req_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_swid_attr_req_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_swid_attr_req_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_swid_attr_req_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_swid_attr_req_t *this)
METHOD (tcg_swid_attr_req_t, get_flags, u_int8_t, private_tcg_swid_attr_req_t *this)
METHOD (tcg_swid_attr_req_t, get_request_id, u_int32_t, private_tcg_swid_attr_req_t *this)
METHOD (tcg_swid_attr_req_t, get_earliest_eid, u_int32_t, private_tcg_swid_attr_req_t *this)
METHOD (tcg_swid_attr_req_t, add_target, void, private_tcg_swid_attr_req_t *this, swid_tag_id_t *tag_id)
METHOD (tcg_swid_attr_req_t, get_targets, swid_inventory_t *, private_tcg_swid_attr_req_t *this)
pa_tnc_attr_t * tcg_swid_attr_req_create (u_int8_t flags, u_int32_t request_id, u_int32_t eid)
pa_tnc_attr_t * tcg_swid_attr_req_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define SWID_REQ_RESERVED_MASK 0xE0
SWID Request see section 4.7 of TCG TNC SWID Message and Attributes for IF-M
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ |R|S|C| Reserved| Tag ID Count | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Request ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Earliest EID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Tag Creator Length | Tag Creator (variable length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Unique Software ID Length |Unique Software ID (var length)| +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 47 of file tcg_swid_attr_req.c.
Referenced by METHOD(), and tcg_swid_attr_req_create().
Typedef Documentation
typedef struct private_tcg_swid_attr_req_t private_tcg_swid_attr_req_t
Definition at line 26 of file tcg_swid_attr_req.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_swid_attr_req_t * this)
Definition at line 106 of file tcg_swid_attr_req.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_swid_attr_req_t * this)
Definition at line 112 of file tcg_swid_attr_req.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_swid_attr_req_t * this)
Definition at line 118 of file tcg_swid_attr_req.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_swid_attr_req_t * this, bool noskip)
Definition at line 124 of file tcg_swid_attr_req.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_swid_attr_req_t * this)
Definition at line 130 of file tcg_swid_attr_req.c.
References bio_writer_create(), enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::extract_buf, flags, swid_tag_id_t::get_tag_creator, swid_tag_id_t::get_unique_sw_id, length, TCG_SWID_REQ_MIN_SIZE, value, bio_writer_t::write_data16, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     chunk_t tag_creator, unique_sw_id;
     swid_tag_id_t *tag_id;
     enumerator_t *enumerator;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(TCG_SWID_REQ_MIN_SIZE);
     writer->write_uint8 (writer, this->flags);
     writer->write_uint24(writer, this->targets->get_count(this->targets));
     writer->write_uint32(writer, this->request_id);
     writer->write_uint32(writer, this->earliest_eid);
     enumerator = this->targets->create_enumerator(this->targets);
     while (enumerator->enumerate(enumerator, &tag_id))
     {
         tag_creator = tag_id->get_tag_creator(tag_id);
         unique_sw_id = tag_id->get_unique_sw_id(tag_id, NULL);
         writer->write_data16(writer, tag_creator);
         writer->write_data16(writer, unique_sw_id);
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_swid_attr_req_t * this, u_int32_t * offset)
Definition at line 164 of file tcg_swid_attr_req.c.
References bio_reader_create(), chunk_empty, DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, flags, chunk_t::len, NEED_MORE, bio_reader_t::read_data16, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, SUCCESS, SWID_REQ_RESERVED_MASK, swid_tag_id_create(), TCG_SWID_REQ_MIN_SIZE, and value.
 {
     bio_reader_t *reader;
     u_int32_t tag_id_count;
     chunk_t tag_creator, unique_sw_id;
     swid_tag_id_t *tag_id;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < TCG_SWID_REQ_MIN_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for SWID Request");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &this->flags);
     reader->read_uint24(reader, &tag_id_count);
     reader->read_uint32(reader, &this->request_id);
     reader->read_uint32(reader, &this->earliest_eid);
     if (this->request_id == 0)
     {
         *offset = 4;
         return FAILED;
     }
     *offset = TCG_SWID_REQ_MIN_SIZE;
     this->flags &= SWID_REQ_RESERVED_MASK;
     while (tag_id_count--)
     {
         if (!reader->read_data16(reader, &tag_creator))
         {
             DBG1(DBG_TNC, "insufficient data for Tag Creator field");
             return FAILED;
         }
         *offset += 2 + tag_creator.len;
         if (!reader->read_data16(reader, &unique_sw_id))
         {
             DBG1(DBG_TNC, "insufficient data for Unique Software ID");
             return FAILED;
         }
         *offset += 2 + unique_sw_id.len;
         tag_id = swid_tag_id_create(tag_creator, unique_sw_id, chunk_empty);
         this->targets->add(this->targets, tag_id);
     }
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_swid_attr_req_t * this, chunk_t segment)
Definition at line 223 of file tcg_swid_attr_req.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_swid_attr_req_t * this)
Definition at line 229 of file tcg_swid_attr_req.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_swid_attr_req_t * this)
Definition at line 236 of file tcg_swid_attr_req.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         this->targets->destroy(this->targets);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (tcg_swid_attr_req_t , get_flags , u_int8_t , private_tcg_swid_attr_req_t * this)
Definition at line 247 of file tcg_swid_attr_req.c.
References flags.
 {
     return this->flags;
 }
METHOD (tcg_swid_attr_req_t , get_request_id , u_int32_t , private_tcg_swid_attr_req_t * this)
Definition at line 253 of file tcg_swid_attr_req.c.
 {
     return this->request_id;
 }
METHOD (tcg_swid_attr_req_t , get_earliest_eid , u_int32_t , private_tcg_swid_attr_req_t * this)
Definition at line 259 of file tcg_swid_attr_req.c.
 {
     return this->earliest_eid;
 }
METHOD (tcg_swid_attr_req_t , add_target , void , private_tcg_swid_attr_req_t * this, swid_tag_id_t * tag_id)
Definition at line 265 of file tcg_swid_attr_req.c.
 {
     this->targets->add(this->targets, tag_id);
 }
METHOD (tcg_swid_attr_req_t , get_targets , swid_inventory_t * , private_tcg_swid_attr_req_t * this)
Definition at line 271 of file tcg_swid_attr_req.c.
 {
     return this->targets;
 }