strongSwan: public_key_t Struct Reference
public_key_t Struct Reference
public_key
#include "public_key.h"
Public Attributes
key_type_t(* get_type)(public_key_t *this)
bool(* verify)(public_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
bool(* encrypt)(public_key_t *this, encryption_scheme_t scheme, chunk_t plain, chunk_t *crypto)
bool(* equals)(public_key_t *this, public_key_t *other)
int(* get_keysize)(public_key_t *this)
bool(* get_fingerprint)(public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
bool(* has_fingerprint)(public_key_t *this, chunk_t fp)
bool(* get_encoding)(public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
public_key_t *(* get_ref)(public_key_t *this)
void(* destroy)(public_key_t *this)
Detailed Description
Abstract interface of a public key.
Definition at line 144 of file public_key.h.
Member Data Documentation
void(* public_key_t::destroy)(public_key_t *this)
Destroy a public_key instance.
Definition at line 228 of file public_key.h.
Referenced by add_device_id(), cert_enumerate(), certs_filter(), create_cert(), create_cert_ext(), create_usercert_enumerator(), do_args(), encrypt_key(), find_client_id(), get_key_strength(), load_agent(), METHOD(), print(), print_cert(), read_key(), sshkey_certificate_load(), START_TEST(), and tkm_private_key_init().
bool(* public_key_t::encrypt)(public_key_t *this, encryption_scheme_t scheme, chunk_t plain, chunk_t *crypto)
Encrypt a chunk of data.
Parameters
scheme encryption scheme to use
plain chunk containing plaintext data
crypto where to allocate encrypted data
Returns
TRUE if data successfully encrypted
Definition at line 172 of file public_key.h.
Referenced by encrypt_key().
bool(* public_key_t::equals)(public_key_t *this, public_key_t *other)
Check if two public keys are equal.
Parameters
other other public key
Returns
TRUE, if equality
Definition at line 181 of file public_key.h.
bool(* public_key_t::get_encoding)(public_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
Get the key in an encoded form as a chunk.
Parameters
type type of the encoding, one of PUBKEY_*
encoding encoding of the key, allocated
Returns
TRUE if encoding supported
Definition at line 215 of file public_key.h.
Referenced by generate(), main(), and scep_generate_transaction_id().
bool(* public_key_t::get_fingerprint)(public_key_t *this, cred_encoding_type_t type, chunk_t *fp)
Get the fingerprint of the key.
Parameters
type type of fingerprint, one of KEYID_*
fp fingerprint, points to internal data
Returns
TRUE if fingerprint type supported
Definition at line 197 of file public_key.h.
Referenced by add_device_id(), do_args(), find_client_id(), generate(), imv_attestation_process(), METHOD(), print_pubkey(), pubkey_cert_create(), and public_key_equals().
int(* public_key_t::get_keysize)(public_key_t *this)
Get the strength of the key in bits.
Returns
strength of the key in bits
Definition at line 188 of file public_key.h.
Referenced by get_key_strength(), main(), print_pubkey(), and test_bad_sigs().
public_key_t*(* public_key_t::get_ref)(public_key_t *this)
Increase the refcount of the key.
Returns
this with an increased refcount
Definition at line 223 of file public_key.h.
Referenced by METHOD(), pubkey_cert_wrap(), START_TEST(), and x509_cert_gen().
key_type_t(* public_key_t::get_type)(public_key_t *this)
Get the key type.
Returns
type of the key
Definition at line 151 of file public_key.h.
Referenced by find_client_id(), get_key_strength(), main(), METHOD(), print_pubkey(), and tkm_private_key_init().
bool(* public_key_t::has_fingerprint)(public_key_t *this, chunk_t fp)
Check if a key has a given fingerprint of any kind.
Parameters
fp fingerprint to check
Returns
TRUE if key has given fingerprint
Definition at line 206 of file public_key.h.
Referenced by METHOD().
bool(* public_key_t::verify)(public_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t signature)
Verifies a signature against a chunk of data.
Parameters
scheme signature scheme to use for verification, may be default
data data to check signature against
signature signature to check
Returns
TRUE if signature matches
Definition at line 161 of file public_key.h.
Referenced by METHOD(), test_bad_sigs(), and test_good_sig().
The documentation for this struct was generated from the following file:
public_key.h