strongSwan: mgf1.c File Reference
mgf1.c File Reference
#include "mgf1.h"
#include "crypto/hashers/hasher.h"
#include "utils/debug.h"
#include "utils/test.h"
Classes
struct private_mgf1_t
Typedefs
typedef struct private_mgf1_t private_mgf1_t
Functions
METHOD (mgf1_t, get_hash_size, size_t, private_mgf1_t *this)
METHOD (mgf1_t, get_mask, bool, private_mgf1_t *this, size_t mask_len, u_char *mask)
METHOD (mgf1_t, allocate_mask, bool, private_mgf1_t *this, size_t mask_len, chunk_t *mask)
METHOD (mgf1_t, destroy, void, private_mgf1_t *this)
mgf1_t * mgf1_create (hash_algorithm_t alg, chunk_t seed, bool hash_seed)
Typedef Documentation
typedef struct private_mgf1_t private_mgf1_t
Definition at line 22 of file mgf1.c.
Function Documentation
METHOD (mgf1_t , get_hash_size , size_t , private_mgf1_t * this)
Definition at line 61 of file mgf1.c.
References hasher.
 {
     return this->hasher->get_hash_size(this->hasher);
 }
METHOD (mgf1_t , get_mask , bool , private_mgf1_t * this, size_t mask_len, u_char * mask)
Definition at line 67 of file mgf1.c.
References FALSE, HASH_SIZE_SHA512, hasher, htoun32(), memcpy, overflow, and TRUE.
 {
     u_char buf[HASH_SIZE_SHA512];
     size_t hash_len;
     hash_len = this->hasher->get_hash_size(this->hasher);
     while (mask_len > 0)
     {
         /* detect overflow, set counter string and increment counter */
         if (this->overflow)
         {
             return FALSE;
         }
         htoun32(this->ctr_str, this->counter++);
         if (this->counter == 0)
         {
             this->overflow = TRUE;
         }
         /* get the next or final mask block from the hash function */
         if (!this->hasher->get_hash(this->hasher, this->state,
                                    (mask_len < hash_len) ? buf : mask))
         {
             return FALSE;
         }
         if (mask_len < hash_len)
         {
             memcpy(mask, buf, mask_len);
             return TRUE;
         }
         mask_len -= hash_len;
         mask += hash_len;
     }
     return TRUE;
 }
METHOD (mgf1_t , allocate_mask , bool , private_mgf1_t * this, size_t mask_len, chunk_t * mask)
Definition at line 105 of file mgf1.c.
References chunk_alloc, chunk_empty, chunk_t::ptr, and TRUE.
 {
     if (mask_len == 0)
     {
         *mask = chunk_empty;
         return TRUE;
     }
     *mask = chunk_alloc(mask_len);
     return get_mask(this, mask_len, mask->ptr);
 }
METHOD (mgf1_t , destroy , void , private_mgf1_t * this)
Definition at line 118 of file mgf1.c.
References chunk_clear(), free(), and hasher.
 {
     this->hasher->destroy(this->hasher);
     chunk_clear(&this->state);
     free(this);
 }