strongSwan: watcher.c File Reference
watcher.c File Reference
#include "watcher.h"
#include <library.h>
#include <threading/thread.h>
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
Classes
struct private_watcher_t
struct entry_t
struct notify_data_t
Typedefs
typedef struct private_watcher_t private_watcher_t
Functions
static void update (private_watcher_t *this)
static void unregister (notify_data_t *data)
static job_requeue_t notify_async (notify_data_t *data)
static void notify_end (notify_data_t *data)
static void notify (private_watcher_t *this, entry_t *entry, watcher_event_t event)
static void activate_all (private_watcher_t *this)
static int find_revents (struct pollfd *pfd, int count, int fd)
static bool entry_ready (entry_t *entry, watcher_event_t event, int revents)
static job_requeue_t watch (private_watcher_t *this)
METHOD (watcher_t, add, void, private_watcher_t *this, int fd, watcher_event_t events, watcher_cb_t cb, void *data)
METHOD (watcher_t, remove_, void, private_watcher_t *this, int fd)
METHOD (watcher_t, get_state, watcher_state_t, private_watcher_t *this)
METHOD (watcher_t, destroy, void, private_watcher_t *this)
static bool create_notify (private_watcher_t *this)
watcher_t * watcher_create ()
Typedef Documentation
typedef struct private_watcher_t private_watcher_t
Definition at line 29 of file watcher.c.
Function Documentation
static void activate_all (private_watcher_t * this) static
Thread cancellation function for watcher thread
Definition at line 220 of file watcher.c.
References condvar_t::broadcast, condvar, enumerator_t::destroy, enumerator_t::enumerate, entry_t::in_callback, mutex_t::lock, mutex, mutex_t::unlock, and WATCHER_STOPPED.
Referenced by watch().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     /* When the watcher thread gets cancelled, we have to reactivate any entry
      * and signal threads in remove() to go on. */
     this->mutex->lock(this->mutex);
     enumerator = this->fds->create_enumerator(this->fds);
     while (enumerator->enumerate(enumerator, &entry))
     {
         entry->in_callback = 0;
     }
     enumerator->destroy(enumerator);
     this->state = WATCHER_STOPPED;
     this->condvar->broadcast(this->condvar);
     this->mutex->unlock(this->mutex);
 }
static bool create_notify (private_watcher_t * this) static
Create a notify pipe with a one-directional pipe
Definition at line 551 of file watcher.c.
References DBG1, DBG_LIB, FALSE, flags, notify(), strerror, and TRUE.
Referenced by watcher_create().
 {
     int flags;
     if (pipe(this->notify) == 0)
     {
         /* use non-blocking I/O on read-end of notify pipe */
         flags = fcntl(this->notify[0], F_GETFL);
         if (flags != -1 &&
             fcntl(this->notify[0], F_SETFL, flags | O_NONBLOCK) != -1)
         {
             return TRUE;
         }
         DBG1(DBG_LIB, "setting watcher notify pipe read-end non-blocking "
              "failed: %s", strerror(errno));
     }
     return FALSE;
 }
static bool entry_ready (entry_t * entry, watcher_event_t event, int revents) static
Check if entry is waiting for a specific event, and if it got signaled
Definition at line 260 of file watcher.c.
References entry_t::events, FALSE, POLLERR, POLLHUP, POLLIN, POLLNVAL, POLLOUT, WATCHER_EXCEPT, WATCHER_READ, and WATCHER_WRITE.
Referenced by watch().
 {
     if (entry->events & event)
     {
         switch (event)
         {
             case WATCHER_READ:
                 return (revents & (POLLIN | POLLHUP | POLLNVAL)) != 0;
             case WATCHER_WRITE:
                 return (revents & (POLLOUT | POLLHUP | POLLNVAL)) != 0;
             case WATCHER_EXCEPT:
                 return (revents & (POLLERR | POLLHUP | POLLNVAL)) != 0;
         }
     }
     return FALSE;
 }
static int find_revents (struct pollfd * pfd, int count, int fd) static
Find flagged revents in a pollfd set by fd
Definition at line 243 of file watcher.c.
References count, and pollfd::revents.
Referenced by watch().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         if (pfd[i].fd == fd)
         {
             return pfd[i].revents;
         }
     }
     return 0;
 }
METHOD (watcher_t , add , void , private_watcher_t * this, int fd, watcher_event_t events, watcher_cb_t cb, void * data)
Definition at line 428 of file watcher.c.
References callback_job_create_with_prio(), INIT, JOB_PRIO_CRITICAL, lib, mutex_t::lock, mutex, library_t::processor, processor_t::queue_job, return_false(), mutex_t::unlock, update(), watch(), WATCHER_QUEUED, and WATCHER_STOPPED.
 {
     entry_t *entry;
     INIT(entry,
         .fd = fd,
         .events = events,
         .cb = cb,
         .data = data,
     );
     this->mutex->lock(this->mutex);
     this->fds->insert_last(this->fds, entry);
     if (this->state == WATCHER_STOPPED)
     {
         this->state = WATCHER_QUEUED;
         lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create_with_prio((void*)watch, this,
                 NULL, (callback_job_cancel_t)return_false, JOB_PRIO_CRITICAL));
     }
     else
     {
         update(this);
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (watcher_t , remove_ , void , private_watcher_t * this, int fd)
Definition at line 457 of file watcher.c.
References condvar, enumerator_t::destroy, enumerator_t::enumerate, FALSE, entry_t::fd, free(), entry_t::in_callback, mutex_t::lock, mutex, TRUE, mutex_t::unlock, update(), condvar_t::wait, and WATCHER_STOPPED.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     this->mutex->lock(this->mutex);
     while (TRUE)
     {
         bool is_in_callback = FALSE;
         enumerator = this->fds->create_enumerator(this->fds);
         while (enumerator->enumerate(enumerator, &entry))
         {
             if (entry->fd == fd)
             {
                 if (this->state != WATCHER_STOPPED && entry->in_callback)
                 {
                     is_in_callback = TRUE;
                     break;
                 }
                 this->fds->remove_at(this->fds, enumerator);
                 free(entry);
             }
         }
         enumerator->destroy(enumerator);
         if (!is_in_callback)
         {
             break;
         }
         this->condvar->wait(this->condvar, this->mutex);
     }
     update(this);
     this->mutex->unlock(this->mutex);
 }
METHOD (watcher_t , get_state , watcher_state_t , private_watcher_t * this)
Definition at line 494 of file watcher.c.
References mutex_t::lock, mutex, and mutex_t::unlock.
 {
     watcher_state_t state;
     this->mutex->lock(this->mutex);
     state = this->state;
     this->mutex->unlock(this->mutex);
     return state;
 }
METHOD (watcher_t , destroy , void , private_watcher_t * this)
Definition at line 506 of file watcher.c.
References close, condvar, mutex_t::destroy, condvar_t::destroy, free(), mutex, and notify().
 {
     this->mutex->destroy(this->mutex);
     this->condvar->destroy(this->condvar);
     this->fds->destroy(this->fds);
     if (this->notify[0] != -1)
     {
         close(this->notify[0]);
     }
     if (this->notify[1] != -1)
     {
         close(this->notify[1]);
     }
     this->jobs->destroy(this->jobs);
     free(this);
 }
static void notify (private_watcher_t * this, entry_t * entry, watcher_event_t event) static
Execute the callback for a registered FD
Definition at line 192 of file watcher.c.
References callback_job_create_with_prio(), entry_t::cb, data, entry_t::data, entry_t::fd, entry_t::in_callback, INIT, JOB_PRIO_CRITICAL, notify_async(), notify_end(), return_false(), and TRUE.
Referenced by add_initial_contact(), build_fds(), build_natd_payload(), create_notify(), duplicheck_listener_create(), duplicheck_plugin_create(), find_child(), find_socket(), get_string(), handle_plain(), has_notify_errors(), ike2queue(), informational_create(), is_connectivity_check(), kernel_libipsec_router_create(), METHOD(), order_payloads(), print_radius_attributes(), process_auth_response(), process_dpd(), process_payloads(), process_request(), send_notify(), socket_dynamic_socket_create(), update(), wait_for_notify(), and watch().
 {
     notify_data_t *data;
     /* get a copy of entry for async job, but with specific event */
     INIT(data,
         .fd = entry->fd,
         .event = event,
         .cb = entry->cb,
         .data = entry->data,
         .keep = TRUE,
         .this = this,
     );
     /* deactivate entry, so we can select() other FDs even if the async
      * processing did not handle the event yet */
     entry->in_callback++;
     this->jobs->insert_last(this->jobs,
                     callback_job_create_with_prio((void*)notify_async, data,
                         (void*)notify_end, (callback_job_cancel_t)return_false,
                         JOB_PRIO_CRITICAL));
 }
static job_requeue_t notify_async (notify_data_t * data) static
Execute callback of registered FD, asynchronous
Definition at line 142 of file watcher.c.
References notify_data_t::cb, notify_data_t::data, notify_data_t::event, FALSE, notify_data_t::fd, JOB_REQUEUE_NONE, notify_data_t::keep, thread_cleanup_pop(), thread_cleanup_push(), and unregister().
Referenced by notify().
 {
     thread_cleanup_push((void*)unregister, data);
     data->keep = data->cb(data->data, data->fd, data->event);
     thread_cleanup_pop(FALSE);
     return JOB_REQUEUE_NONE;
 }
static void notify_end (notify_data_t * data) static
Clean up notification data, reactivate FD
Definition at line 153 of file watcher.c.
References condvar_t::broadcast, condvar, enumerator_t::destroy, enumerator_t::enumerate, notify_data_t::event, entry_t::events, entry_t::fd, notify_data_t::fd, free(), entry_t::in_callback, notify_data_t::keep, mutex_t::lock, mutex, notify_data_t::this, mutex_t::unlock, and update().
Referenced by notify().
 {
     private_watcher_t *this = data->this;
     enumerator_t *enumerator;
     entry_t *entry;
     /* reactivate the disabled entry */
     this->mutex->lock(this->mutex);
     enumerator = this->fds->create_enumerator(this->fds);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->fd == data->fd)
         {
             if (!data->keep)
             {
                 entry->events &= ~data->event;
                 if (!entry->events)
                 {
                     this->fds->remove_at(this->fds, enumerator);
                     free(entry);
                     break;
                 }
             }
             entry->in_callback--;
             break;
         }
     }
     enumerator->destroy(enumerator);
     update(this);
     this->condvar->broadcast(this->condvar);
     this->mutex->unlock(this->mutex);
     free(data);
 }
static void unregister (notify_data_t * data) static
Cleanup function if callback gets cancelled
Definition at line 131 of file watcher.c.
References FALSE, and notify_data_t::keep.
Referenced by notify_async().
 {
     /* if a thread processing a callback gets cancelled, we mark the entry
      * as cancelled, like the callback would return FALSE. This is required
      * to not queue this watcher again if all threads have been gone. */
     data->keep = FALSE;
 }
static void update (private_watcher_t * this) static
Notify watcher thread about changes
Definition at line 114 of file watcher.c.
References DBG1, DBG_JOB, notify(), strerror, TRUE, and write.
Referenced by METHOD(), and notify_end().
 {
     char buf[1] = { 'u' };
     this->pending = TRUE;
     if (this->notify[1] != -1)
     {
         if (write(this->notify[1], buf, sizeof(buf)) == -1)
         {
             DBG1(DBG_JOB, "notifying watcher failed: %s", strerror(errno));
         }
     }
 }
static job_requeue_t watch (private_watcher_t * this) static
Dispatching function
Definition at line 280 of file watcher.c.
References activate_all(), count, DBG1, DBG2, DBG3, DBG_JOB, enumerator_t::destroy, entry_ready(), enumerator_t::enumerate, entry_t::events, pollfd::events, EWOULDBLOCK, processor_t::execute_job, FALSE, entry_t::fd, pollfd::fd, find_revents(), entry_t::in_callback, JOB_REQUEUE_DIRECT, JOB_REQUEUE_NONE, len, lib, mutex_t::lock, mutex, notify(), poll, POLLERR, POLLIN, POLLOUT, library_t::processor, read, res, pollfd::revents, strerror, SUCCESS, thread_cancelability(), thread_cleanup_pop(), thread_cleanup_push(), TRUE, mutex_t::unlock, WATCHER_EXCEPT, WATCHER_QUEUED, WATCHER_READ, WATCHER_RUNNING, WATCHER_STOPPED, and WATCHER_WRITE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     struct pollfd *pfd;
     int count = 0, res;
     bool rebuild = FALSE;
     this->mutex->lock(this->mutex);
     count = this->fds->get_count(this->fds);
     if (count == 0)
     {
         this->state = WATCHER_STOPPED;
         this->mutex->unlock(this->mutex);
         return JOB_REQUEUE_NONE;
     }
     if (this->state == WATCHER_QUEUED)
     {
         this->state = WATCHER_RUNNING;
     }
     pfd = alloca(sizeof(*pfd) * (count + 1));
     pfd[0].fd = this->notify[0];
     pfd[0].events = POLLIN;
     count = 1;
     enumerator = this->fds->create_enumerator(this->fds);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (!entry->in_callback)
         {
             pfd[count].fd = entry->fd;
             pfd[count].events = 0;
             if (entry->events & WATCHER_READ)
             {
                 DBG3(DBG_JOB, "  watching %d for reading", entry->fd);
                 pfd[count].events |= POLLIN;
             }
             if (entry->events & WATCHER_WRITE)
             {
                 DBG3(DBG_JOB, "  watching %d for writing", entry->fd);
                 pfd[count].events |= POLLOUT;
             }
             if (entry->events & WATCHER_EXCEPT)
             {
                 DBG3(DBG_JOB, "  watching %d for exceptions", entry->fd);
                 pfd[count].events |= POLLERR;
             }
             count++;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     while (!rebuild)
     {
         int revents;
         char buf[1];
         bool old;
         ssize_t len;
         job_t *job;
         DBG2(DBG_JOB, "watcher going to poll() %d fds", count);
         thread_cleanup_push((void*)activate_all, this);
         old = thread_cancelability(TRUE);
         res = poll(pfd, count, -1);
         thread_cancelability(old);
         thread_cleanup_pop(FALSE);
         if (res > 0)
         {
             if (pfd[0].revents & POLLIN)
             {
                 while (TRUE)
                 {
                     len = read(this->notify[0], buf, sizeof(buf));
                     if (len == -1)
                     {
                         if (errno != EAGAIN && errno != EWOULDBLOCK)
{
                             DBG1(DBG_JOB, "reading watcher notify failed: %s",
                                  strerror(errno));
                         }
                         break;
                     }
                 }
                 this->pending = FALSE;
                 DBG2(DBG_JOB, "watcher got notification, rebuilding");
                 return JOB_REQUEUE_DIRECT;
             }
             this->mutex->lock(this->mutex);
             enumerator = this->fds->create_enumerator(this->fds);
             while (enumerator->enumerate(enumerator, &entry))
             {
                 if (entry->in_callback)
                 {
                     rebuild = TRUE;
                     break;
                 }
                 revents = find_revents(pfd, count, entry->fd);
                 if (entry_ready(entry, WATCHER_EXCEPT, revents))
                 {
                     DBG2(DBG_JOB, "watched FD %d has exception", entry->fd);
                     notify(this, entry, WATCHER_EXCEPT);
                 }
                 else
                 {
                     if (entry_ready(entry, WATCHER_READ, revents))
                     {
                         DBG2(DBG_JOB, "watched FD %d ready to read", entry->fd);
                         notify(this, entry, WATCHER_READ);
                     }
                     if (entry_ready(entry, WATCHER_WRITE, revents))
                     {
                         DBG2(DBG_JOB, "watched FD %d ready to write", entry->fd);
                         notify(this, entry, WATCHER_WRITE);
                     }
                 }
             }
             enumerator->destroy(enumerator);
             this->mutex->unlock(this->mutex);
             if (this->jobs->get_count(this->jobs))
             {
                 while (this->jobs->remove_first(this->jobs,
                                                 (void**)&job) == SUCCESS)
                 {
                     lib->processor->execute_job(lib->processor, job);
                 }
                 /* we temporarily disable a notified FD, rebuild FDSET */
                 return JOB_REQUEUE_DIRECT;
             }
         }
         else
         {
             if (!this->pending && errno != EINTR)
             {   /* complain only if no pending updates */
                 DBG1(DBG_JOB, "watcher poll() error: %s", strerror(errno));
             }
             return JOB_REQUEUE_DIRECT;
         }
     }
     return JOB_REQUEUE_DIRECT;
 }