strongSwan: forecast_forwarder.c File Reference
forecast_forwarder.c File Reference
#include "forecast_forwarder.h"
#include <errno.h>
#include <unistd.h>
#include <netinet/ip.h>
#include <netinet/udp.h>
#include <linux/socket.h>
#include <netinet/if_ether.h>
#include <linux/if_packet.h>
#include <linux/filter.h>
#include <sys/ioctl.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <hydra.h>
#include <daemon.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_kernel_listener_t
struct private_forecast_forwarder_t
Macros
#define BOOTP_SERVER_PORT 67
#define BOOTP_CLIENT_PORT 68
Typedefs
typedef struct
private_forecast_forwarder_t private_forecast_forwarder_t
typedef struct
private_kernel_listener_t private_kernel_listener_t
Functions
static void send_net (private_forecast_forwarder_t *this, struct sockaddr_ll *addr, void *buf, size_t len)
static void send_peer (private_forecast_forwarder_t *this, u_int32_t dst, void *buf, size_t len, int mark)
static bool is_bootp (void *buf, size_t len)
static bool receive_casts (private_forecast_forwarder_t *this)
static void join_group (private_kernel_listener_t *this, char *group, struct sockaddr *addr)
static void join_groups (private_kernel_listener_t *this, struct sockaddr *addr)
static bool attach_filter (int fd, u_int32_t broadcast)
static int get_ifindex (private_kernel_listener_t *this, char *ifname)
static void setup_interface (private_kernel_listener_t *this)
METHOD (kernel_listener_t, roam, bool, private_kernel_listener_t *this, bool address)
METHOD (forecast_forwarder_t, destroy, void, private_forecast_forwarder_t *this)
forecast_forwarder_t * forecast_forwarder_create (forecast_listener_t *listener)
Macro Definition Documentation
#define BOOTP_CLIENT_PORT 68
Definition at line 36 of file forecast_forwarder.c.
Referenced by is_bootp().
#define BOOTP_SERVER_PORT 67
Definition at line 35 of file forecast_forwarder.c.
Referenced by is_bootp().
Typedef Documentation
typedef struct private_forecast_forwarder_t private_forecast_forwarder_t
Definition at line 38 of file forecast_forwarder.c.
typedef struct private_kernel_listener_t private_kernel_listener_t
Definition at line 39 of file forecast_forwarder.c.
Function Documentation
static bool attach_filter (int fd, u_int32_t broadcast) static
Attach the socket filter to the socket
Definition at line 321 of file forecast_forwarder.c.
References DBG1, DBG_NET, FALSE, setsockopt, strerror, and TRUE.
Referenced by setup_interface().
 {
     struct sock_filter filter_code[] = {
         /* destination address: is ... */
         BPF_STMT(BPF_LD+BPF_W+BPF_ABS, offsetof(struct iphdr, daddr)),
         /* broadcast, as received from the local network */
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, ntohl(broadcast), 4, 0),
         /* broadcast, as Win7 sends them */
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, 0xFFFFFFFF, 3, 0),
         /* any multicast, 224.0.0.0/4 */
         BPF_STMT(BPF_ALU+BPF_AND+BPF_K, 0xF0000000),
         BPF_JUMP(BPF_JMP+BPF_JEQ+BPF_K, 0xE0000000, 1, 0),
         BPF_STMT(BPF_RET+BPF_K, 0),
         BPF_STMT(BPF_LD+BPF_W+BPF_LEN, 0),
         BPF_STMT(BPF_RET+BPF_A, 0),
     };
     struct sock_fprog filter = {
         sizeof(filter_code) / sizeof(struct sock_filter),
         filter_code,
     };
     if (setsockopt(fd, SOL_SOCKET, SO_ATTACH_FILTER,
                    &filter, sizeof(filter)) < 0)
     {
         DBG1(DBG_NET, "installing forecast PACKET socket filter failed: %s",
              strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
static int get_ifindex (private_kernel_listener_t * this, char * ifname) static
Get the interface index of an interface name
Definition at line 355 of file forecast_forwarder.c.
Referenced by setup_interface().
 {
     struct ifreq ifr = {};
     strncpy(ifr.ifr_name, ifname, IFNAMSIZ);
     if (ioctl(this->raw, SIOCGIFINDEX, &ifr) == 0)
     {
         return ifr.ifr_ifindex;
     }
     return 0;
 }
static bool is_bootp (void * buf, size_t len) static
Check if an IP packet is BOOTP/DHCP
Definition at line 132 of file forecast_forwarder.c.
References __attribute__, BOOTP_CLIENT_PORT, BOOTP_SERVER_PORT, FALSE, and TRUE.
Referenced by receive_casts().
 {
     struct __attribute__((__packed__)) {
         struct iphdr ip;
         struct udphdr udp;
     } *pkt = buf;
     if (len > sizeof(*pkt))
     {
         if (ntohs(pkt->udp.source) == BOOTP_CLIENT_PORT &&
             ntohs(pkt->udp.dest) == BOOTP_SERVER_PORT)
         {
             return TRUE;
         }
         if (ntohs(pkt->udp.source) == BOOTP_SERVER_PORT &&
             ntohs(pkt->udp.dest) == BOOTP_CLIENT_PORT)
         {
             return TRUE;
         }
     }
     return FALSE;
 }
static void join_group (private_kernel_listener_t * this, char * group, struct sockaddr * addr) static
Join a multicast group
Definition at line 257 of file forecast_forwarder.c.
References DBG1, DBG2, DBG_NET, EADDRINUSE, host, host_create_from_string(), in, memcpy, memset, setsockopt, and strerror.
Referenced by join_groups().
 {
     struct sockaddr_in *in;
     struct ip_mreqn mreq;
     host_t *host;
     host = host_create_from_string(group, 0);
     if (host)
     {
         memset(&mreq, 0, sizeof(mreq));
         memcpy(&mreq.imr_multiaddr.s_addr, host->get_address(host).ptr, 4);
         if (addr->sa_family == AF_INET)
         {
             in = (struct sockaddr_in*)addr;
             memcpy(&mreq.imr_address, &in->sin_addr.s_addr,
                    sizeof(in->sin_addr.s_addr));
         }
         mreq.imr_ifindex = this->ifindex;
         if (setsockopt(this->raw, IPPROTO_IP, IP_ADD_MEMBERSHIP,
                        &mreq, sizeof(mreq)) == -1)
         {
             if (errno != EADDRINUSE)
             {
                 DBG1(DBG_NET, "forecast multicast join to %s failed: %s",
                      group, strerror(errno));
             }
         }
         else
         {
             DBG2(DBG_NET, "forwarding multicast group %s", group);
         }
         host->destroy(host);
     }
 }
static void join_groups (private_kernel_listener_t * this, struct sockaddr * addr) static
(Re-)Join all multicast groups we want to forward
Definition at line 296 of file forecast_forwarder.c.
References DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), settings_t::get_str, group, groups, join_group(), lib, library_t::ns, and library_t::settings.
Referenced by setup_interface().
 {
     enumerator_t *enumerator;
     char *groups, *group;
     static char *def =
         "224.0.0.1,"        /* host multicast */
         "224.0.0.22,"       /* IGMP */
         "224.0.0.251,"      /* mDNS */
         "224.0.0.252,"      /* LLMNR */
         "239.255.255.250";  /* SSDP/WS-discovery */
     groups = lib->settings->get_str(lib->settings,
                                     "%s.plugins.forecast.groups", def, lib->ns);
     DBG1(DBG_CFG, "joining forecast multicast groups: %s", groups);
     enumerator = enumerator_create_token(groups, ",", " ");
     while (enumerator->enumerate(enumerator, &group))
     {
         join_group(this, group, addr);
     }
     enumerator->destroy(enumerator);
 }
METHOD (kernel_listener_t , roam , bool , private_kernel_listener_t * this, bool address)
Definition at line 409 of file forecast_forwarder.c.
References setup_interface(), and TRUE.
 {
     if (address)
     {
         setup_interface(this);
     }
     return TRUE;
 }
METHOD (forecast_forwarder_t , destroy , void , private_forecast_forwarder_t * this)
Definition at line 419 of file forecast_forwarder.c.
References close, free(), hydra, hydra_t::kernel_interface, lib, watcher_t::remove, kernel_interface_t::remove_listener, and library_t::watcher.
 {
     if (this->kernel.raw != -1)
     {
         close(this->kernel.raw);
     }
     if (this->kernel.pkt != -1)
     {
         lib->watcher->remove(lib->watcher, this->kernel.pkt);
         close(this->kernel.pkt);
     }
     hydra->kernel_interface->remove_listener(hydra->kernel_interface,
                                              &this->kernel.listener);
     free(this);
 }
static bool receive_casts (private_forecast_forwarder_t * this) static
Broadcast/Multicast receiver
Definition at line 158 of file forecast_forwarder.c.
References __attribute__, addr, chunk_from_thing, data, DBG1, DBG2, DBG_NET, enumerator_t::destroy, host_t::destroy, dst, enumerator_t::enumerate, EWOULDBLOCK, FALSE, host_create_from_chunk(), traffic_selector_t::includes, is_bootp(), len, memset, MSG_DONTWAIT, recvfrom, send_net(), send_peer(), src, strerror, TRUE, and type.
Referenced by forecast_forwarder_create().
 {
     struct __attribute__((packed)) {
         struct iphdr hdr;
         char data[2048];
     } buf;
     char *type;
     ssize_t len;
     u_int mark, origin = 0;
     host_t *src, *dst;
     traffic_selector_t *ts;
     enumerator_t *enumerator;
     struct sockaddr_ll addr;
     socklen_t alen = sizeof(addr);
     bool reinject;
     len = recvfrom(this->kernel.pkt, &buf, sizeof(buf), MSG_DONTWAIT,
                    (struct sockaddr*)&addr, &alen);
     if (len < 0)
     {
         if (errno != EAGAIN && errno != EWOULDBLOCK)
         {
             DBG1(DBG_NET, "receiving from forecast socket failed: %s",
                  strerror(errno));
         }
         return TRUE;
     }
     else if (len < sizeof(struct iphdr))
     {
         DBG1(DBG_NET, "received short forecast packet: %zd bytes", len);
         return TRUE;
     }
     if (is_bootp(&buf, len))
     {   /* don't forward DHCP broadcasts */
         return TRUE;
     }
     src = host_create_from_chunk(AF_INET, chunk_from_thing(buf.hdr.saddr), 0);
     dst = host_create_from_chunk(AF_INET, chunk_from_thing(buf.hdr.daddr), 0);
     /* create valid broadcast/multicast MAC to send out */
     if (IN_MULTICAST(ntohl(buf.hdr.daddr)))
     {
         type = "multi";
         ETHER_MAP_IP_MULTICAST(&buf.hdr.daddr, addr.sll_addr);
     }
     else
     {
         type = "broad";
         memset(&addr.sll_addr, 0xFF, sizeof(addr.sll_addr));
     }
     DBG2(DBG_NET, "forecast intercepted packet: %H to %H", src, dst);
     /* find mark of originating tunnel */
     enumerator = this->kernel.fc->create_enumerator(this->kernel.fc, FALSE);
     while (enumerator->enumerate(enumerator, &ts, &mark, &reinject))
     {
         if (ts->includes(ts, src))
         {
             origin = mark;
             break;
         }
     }
     enumerator->destroy(enumerator);
     /* send packet over all tunnels, but not the packets origin */
     enumerator = this->kernel.fc->create_enumerator(this->kernel.fc, FALSE);
     while (enumerator->enumerate(enumerator, &ts, &mark, &reinject))
     {
         if (ts->includes(ts, dst))
         {
             if ((reinject && origin != mark) || origin == 0)
             {
                 DBG2(DBG_NET, "forwarding a %H %scast from %H to peer %R (%u)",
                      dst, type, src, ts, mark);
                 send_peer(this, buf.hdr.daddr, &buf, len, mark);
             }
         }
     }
     enumerator->destroy(enumerator);
     if (origin)
     {
         /* forward broadcast/multicast from client to network */
         DBG2(DBG_NET, "forwarding a %H %scast from peer %H to internal network",
              dst, type, src);
         addr.sll_ifindex = this->kernel.ifindex;
         send_net(this, &addr, &buf, len);
     }
     dst->destroy(dst);
     src->destroy(src);
     return TRUE;
 }
static void send_net (private_forecast_forwarder_t * this, struct sockaddr_ll * addr, void * buf, size_t len) static
Send a broadcast/multicast packet to a network
Definition at line 96 of file forecast_forwarder.c.
References DBG1, DBG_NET, sendto, and strerror.
Referenced by receive_casts().
 {
     if (sendto(this->kernel.pkt, buf, len, 0,
                (struct sockaddr*)addr, sizeof(*addr)) != len)
     {
         DBG1(DBG_NET, "forecast send_net() failed: %s", strerror(errno));
     }
 }
static void send_peer (private_forecast_forwarder_t * this, u_int32_t dst, void * buf, size_t len, int mark) static
Send a broadcast/multicast packet to a peer
Definition at line 109 of file forecast_forwarder.c.
References DBG1, DBG_NET, dst, sendto, setsockopt, and strerror.
Referenced by receive_casts().
 {
     struct sockaddr_in addr = {
         .sin_family = AF_INET,
         .sin_addr.s_addr = dst,
     };
     if (setsockopt(this->kernel.raw, SOL_SOCKET, SO_MARK,
                    &mark, sizeof(mark)) != 0)
     {
         DBG1(DBG_NET, "forecast setting SO_MARK failed: %s", strerror(errno));
     }
     if (sendto(this->kernel.raw, buf, len, 0,
                (struct sockaddr*)&addr, sizeof(addr)) != len)
     {
         DBG1(DBG_NET, "forecast send_peer() failed: %s", strerror(errno));
     }
 }
static void setup_interface (private_kernel_listener_t * this) static
Set up the interface for broad/multicast forwarding
Definition at line 370 of file forecast_forwarder.c.
References attach_filter(), DBG1, DBG_NET, host_t::destroy, get_ifindex(), settings_t::get_str, host, host_create_from_sockaddr(), in, join_groups(), lib, name, library_t::ns, library_t::settings, and streq().
Referenced by forecast_forwarder_create(), and METHOD().
 {
     struct ifaddrs *addrs, *current;
     struct sockaddr_in *in;
     host_t *host;
     char *name;
     name = lib->settings->get_str(lib->settings,
                             "%s.plugins.forecast.interface", NULL, lib->ns);
     if (getifaddrs(&addrs) == 0)
     {
         for (current = addrs; current; current = current->ifa_next)
         {
             if (name && !streq(name, current->ifa_name))
             {
                 continue;
             }
             if (current->ifa_flags & IFF_BROADCAST &&
                 current->ifa_broadaddr &&
                 current->ifa_broadaddr->sa_family == AF_INET)
             {
                 DBG1(DBG_NET, "using forecast interface %s", current->ifa_name);
                 this->ifindex = get_ifindex(this, current->ifa_name);
                 in = (struct sockaddr_in*)current->ifa_broadaddr;
                 attach_filter(this->pkt, in->sin_addr.s_addr);
                 join_groups(this, current->ifa_addr);
                 host = host_create_from_sockaddr(current->ifa_broadaddr);
                 if (host)
                 {
                     this->fc->set_broadcast(this->fc, host);
                     host->destroy(host);
                 }
                 break;
             }
         }
     }
     freeifaddrs(addrs);
 }