strongSwan: ike_cert_post.c File Reference
ike_cert_post.c File Reference
#include "ike_cert_post.h"
#include <daemon.h>
#include <sa/ike_sa.h>
#include <encoding/payloads/cert_payload.h>
#include <encoding/payloads/certreq_payload.h>
#include <encoding/payloads/auth_payload.h>
#include <credentials/certificates/x509.h>
#include <credentials/certificates/ac.h>
Classes
struct private_ike_cert_post_t
Typedefs
typedef struct
private_ike_cert_post_t private_ike_cert_post_t
Functions
static cert_payload_t * build_cert_payload (private_ike_cert_post_t *this, certificate_t *cert)
static bool add_subject_cert (private_ike_cert_post_t *this, auth_cfg_t *auth, message_t *message)
static void add_im_certs (private_ike_cert_post_t *this, auth_cfg_t *auth, message_t *message)
static void add_attribute_certs (private_ike_cert_post_t *this, auth_cfg_t *auth, message_t *message)
static void build_certs (private_ike_cert_post_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_ike_cert_post_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_ike_cert_post_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_ike_cert_post_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_ike_cert_post_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_ike_cert_post_t *this)
METHOD (task_t, migrate, void, private_ike_cert_post_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_ike_cert_post_t *this)
ike_cert_post_t * ike_cert_post_create (ike_sa_t *ike_sa, bool initiator)
Typedef Documentation
typedef struct private_ike_cert_post_t private_ike_cert_post_t
Definition at line 28 of file ike_cert_post.c.
Function Documentation
static void add_attribute_certs (private_ike_cert_post_t * this, auth_cfg_t * auth, message_t * message) static
Add any valid attribute certificates of subject to message
Definition at line 163 of file ike_cert_post.c.
References message_t::add_payload, AUTH_RULE_SUBJECT_CERT, cert, cert_payload_create_from_cert(), CERT_X509, CERT_X509_AC, ac_t::certificate, credential_manager_t::create_cert_enumerator, library_t::credmgr, DBG1, DBG_IKE, identification_t::destroy, identification_t::equals, FALSE, auth_cfg_t::get, ac_t::get_holderIssuer, certificate_t::get_issuer, x509_t::get_serial, certificate_t::get_type, certificate_t::get_validity, id, ID_KEY_ID, identification_create_from_encoding(), KEY_ANY, lib, PLV2_CERTIFICATE, and subject.
Referenced by build_certs().
 {
     certificate_t *subject, *cert;
     subject = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
     if (subject && subject->get_type(subject) == CERT_X509)
     {
         x509_t *x509 = (x509_t*)subject;
         identification_t *id, *serial;
         enumerator_t *enumerator;
         cert_payload_t *payload;
         ac_t *ac;
         /* we look for attribute certs having our serial and holder issuer,
          * which is recommended by RFC 5755 */
         serial = identification_create_from_encoding(ID_KEY_ID,
                                                      x509->get_serial(x509));
         enumerator = lib->credmgr->create_cert_enumerator(lib->credmgr,
                                         CERT_X509_AC, KEY_ANY, serial, FALSE);
         while (enumerator->enumerate(enumerator, &ac))
         {
             cert = &ac->certificate;
             id = ac->get_holderIssuer(ac);
             if (id && id->equals(id, subject->get_issuer(subject)) &&
                 cert->get_validity(cert, NULL, NULL, NULL))
             {
                 payload = cert_payload_create_from_cert(PLV2_CERTIFICATE, cert);
                 if (payload)
                 {
                     DBG1(DBG_IKE, "sending attribute certificate "
                          "issued by \"%Y\"", cert->get_issuer(cert));
                     message->add_payload(message, (payload_t*)payload);
                 }
             }
         }
         enumerator->destroy(enumerator);
         serial->destroy(serial);
     }
 }
static void add_im_certs (private_ike_cert_post_t * this, auth_cfg_t * auth, message_t * message) static
Add intermediate CA certificates to message
Definition at line 135 of file ike_cert_post.c.
References message_t::add_payload, AUTH_RULE_IM_CERT, cert, cert_payload_create_from_cert(), auth_cfg_t::create_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, certificate_t::get_subject, PLV2_CERTIFICATE, and type.
Referenced by build_certs().
 {
     cert_payload_t *payload;
     enumerator_t *enumerator;
     certificate_t *cert;
     auth_rule_t type;
     enumerator = auth->create_enumerator(auth);
     while (enumerator->enumerate(enumerator, &type, &cert))
     {
         if (type == AUTH_RULE_IM_CERT)
         {
             payload = cert_payload_create_from_cert(PLV2_CERTIFICATE, cert);
             if (payload)
             {
                 DBG1(DBG_IKE, "sending issuer cert \"%Y\"",
                      cert->get_subject(cert));
                 message->add_payload(message, (payload_t*)payload);
             }
         }
     }
     enumerator->destroy(enumerator);
 }
static bool add_subject_cert (private_ike_cert_post_t * this, auth_cfg_t * auth, message_t * message) static
Add subject certificate to message
Definition at line 111 of file ike_cert_post.c.
References message_t::add_payload, AUTH_RULE_SUBJECT_CERT, build_cert_payload(), cert, DBG1, DBG_IKE, FALSE, auth_cfg_t::get, certificate_t::get_subject, and TRUE.
Referenced by build_certs().
 {
     cert_payload_t *payload;
     certificate_t *cert;
     cert = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
     if (!cert)
     {
         return FALSE;
     }
     payload = build_cert_payload(this, cert);
     if (!payload)
     {
         return FALSE;
     }
     DBG1(DBG_IKE, "sending end entity cert \"%Y\"", cert->get_subject(cert));
     message->add_payload(message, (payload_t*)payload);
     return TRUE;
 }
static cert_payload_t* build_cert_payload (private_ike_cert_post_t * this, certificate_t * cert) static
Generates the cert payload, if possible with "Hash and URL"
Definition at line 54 of file ike_cert_post.c.
References hasher_t::allocate_hash, CERT_ASN1_DER, cert_payload_create_from_cert(), cert_payload_create_from_hash_and_url(), CERT_X509, chunk_free(), credential_manager_t::create_cdp_enumerator, crypto_factory_t::create_hasher, library_t::credmgr, library_t::crypto, DBG1, DBG_IKE, enumerator_t::destroy, hasher_t::destroy, enumerator_t::enumerate, EXT_HASH_AND_URL, certificate_t::get_encoding, hash, HASH_SHA1, hasher, id, ID_KEY_ID, identification_create_from_encoding(), lib, and PLV2_CERTIFICATE.
Referenced by add_subject_cert().
 {
     hasher_t *hasher;
     identification_t *id;
     chunk_t hash, encoded ;
     enumerator_t *enumerator;
     char *url;
     cert_payload_t *payload = NULL;
     if (!this->ike_sa->supports_extension(this->ike_sa, EXT_HASH_AND_URL))
     {
         return cert_payload_create_from_cert(PLV2_CERTIFICATE, cert);
     }
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher)
     {
         DBG1(DBG_IKE, "unable to use hash-and-url: sha1 not supported");
         return cert_payload_create_from_cert(PLV2_CERTIFICATE, cert);
     }
     if (!cert->get_encoding(cert, CERT_ASN1_DER, &encoded))
     {
         DBG1(DBG_IKE, "encoding certificate for cert payload failed");
         hasher->destroy(hasher);
         return NULL;
     }
     if (!hasher->allocate_hash(hasher, encoded, &hash))
     {
         hasher->destroy(hasher);
         chunk_free(&encoded);
         return cert_payload_create_from_cert(PLV2_CERTIFICATE, cert);
     }
     chunk_free(&encoded);
     hasher->destroy(hasher);
     id = identification_create_from_encoding(ID_KEY_ID, hash);
     enumerator = lib->credmgr->create_cdp_enumerator(lib->credmgr, CERT_X509, id);
     if (enumerator->enumerate(enumerator, &url))
     {
         payload = cert_payload_create_from_hash_and_url(hash, url);
         DBG1(DBG_IKE, "sending hash-and-url \"%s\"", url);
     }
     else
     {
         payload = cert_payload_create_from_cert(PLV2_CERTIFICATE, cert);
     }
     enumerator->destroy(enumerator);
     chunk_free(&hash);
     id->destroy(id);
     return payload;
 }
static void build_certs (private_ike_cert_post_t * this, message_t * message) static
add certificates to message
Definition at line 207 of file ike_cert_post.c.
References add_attribute_certs(), add_im_certs(), add_subject_cert(), AUTH_PSK, CERT_ALWAYS_SEND, CERT_NEVER_SEND, CERT_SEND_IF_ASKED, COND_CERTREQ_SEEN, auth_payload_t::get_auth_method, peer_cfg_t::get_cert_policy, message_t::get_payload, PLV2_AUTH, and TRUE.
Referenced by METHOD().
 {
     peer_cfg_t *peer_cfg;
     auth_payload_t *payload;
     auth_cfg_t *auth;
     payload = (auth_payload_t*)message->get_payload(message, PLV2_AUTH);
     peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
     if (!peer_cfg || !payload || payload->get_auth_method(payload) == AUTH_PSK)
     {   /* no CERT payload for EAP/PSK */
         return;
     }
     switch (peer_cfg->get_cert_policy(peer_cfg))
     {
         case CERT_NEVER_SEND:
             break;
         case CERT_SEND_IF_ASKED:
             if (!this->ike_sa->has_condition(this->ike_sa, COND_CERTREQ_SEEN))
             {
                 break;
             }
             /* FALL */
         case CERT_ALWAYS_SEND:
             auth = this->ike_sa->get_auth_cfg(this->ike_sa, TRUE);
             if (add_subject_cert(this, auth, message))
             {
                 add_im_certs(this, auth, message);
                 add_attribute_certs(this, auth, message);
             }
             break;
     }
 }
METHOD (task_t , build_i , status_t , private_ike_cert_post_t * this, message_t * message)
Definition at line 241 of file ike_cert_post.c.
References build_certs(), and NEED_MORE.
 {
     build_certs(this, message);
     return NEED_MORE;
 }
METHOD (task_t , process_r , status_t , private_ike_cert_post_t * this, message_t * message)
Definition at line 249 of file ike_cert_post.c.
References NEED_MORE.
 {
     return NEED_MORE;
 }
METHOD (task_t , build_r , status_t , private_ike_cert_post_t * this, message_t * message)
Definition at line 255 of file ike_cert_post.c.
References build_certs(), IKE_ESTABLISHED, NEED_MORE, and SUCCESS.
 {
     build_certs(this, message);
     if (this->ike_sa->get_state(this->ike_sa) != IKE_ESTABLISHED)
     {   /* stay alive, we might have additional rounds with certs */
         return NEED_MORE;
     }
     return SUCCESS;
 }
METHOD (task_t , process_i , status_t , private_ike_cert_post_t * this, message_t * message)
Definition at line 267 of file ike_cert_post.c.
References IKE_ESTABLISHED, NEED_MORE, and SUCCESS.
 {
     if (this->ike_sa->get_state(this->ike_sa) != IKE_ESTABLISHED)
     {   /* stay alive, we might have additional rounds with CERTS */
         return NEED_MORE;
     }
     return SUCCESS;
 }
METHOD (task_t , get_type , task_type_t , private_ike_cert_post_t * this)
Definition at line 277 of file ike_cert_post.c.
References TASK_IKE_CERT_POST.
 {
     return TASK_IKE_CERT_POST;
 }
METHOD (task_t , migrate , void , private_ike_cert_post_t * this, ike_sa_t * ike_sa)
Definition at line 283 of file ike_cert_post.c.
 {
     this->ike_sa = ike_sa;
 }
METHOD (task_t , destroy , void , private_ike_cert_post_t * this)
Definition at line 289 of file ike_cert_post.c.
References free().
 {
     free(this);
 }