strongSwan: eap_tls
eap_tls
eap_tls
Classes
struct eap_tls_t
Typedefs
typedef struct eap_tls_t eap_tls_t
Functions
eap_tls_t * eap_tls_create_server (identification_t *server, identification_t *peer)
eap_tls_t * eap_tls_create_peer (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_tls_t eap_tls_t
Definition at line 24 of file eap_tls.h.
Function Documentation
eap_tls_t* eap_tls_create_peer (identification_t * server, identification_t * peer)
Creates the EAP method EAP-TLS acting as peer.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_tls_t object
Definition at line 178 of file eap_tls.c.
References eap_tls_create(), and FALSE.
Referenced by METHOD().
 {
     return eap_tls_create(server, peer, FALSE);
 }
eap_tls_t* eap_tls_create_server (identification_t * server, identification_t * peer)
Creates the EAP method EAP-TLS acting as server.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_tls_t object
Definition at line 172 of file eap_tls.c.
References eap_tls_create(), and TRUE.
Referenced by METHOD().
 {
     return eap_tls_create(server, peer, TRUE);
 }