strongSwan: ip_packet_t Struct Reference
ip_packet_t Struct Reference
ip_packet
#include "ip_packet.h"
Public Attributes
u_int8_t(* get_version)(ip_packet_t *this)
host_t *(* get_source)(ip_packet_t *this)
host_t *(* get_destination)(ip_packet_t *this)
u_int8_t(* get_next_header)(ip_packet_t *this)
chunk_t(* get_encoding)(ip_packet_t *this)
chunk_t(* get_payload)(ip_packet_t *this)
ip_packet_t *(* clone)(ip_packet_t *this)
void(* destroy)(ip_packet_t *this)
Detailed Description
IP packet
Definition at line 33 of file ip_packet.h.
Member Data Documentation
ip_packet_t*(* ip_packet_t::clone)(ip_packet_t *this)
Clone the IP packet
Returns
clone of the packet
Definition at line 82 of file ip_packet.h.
Referenced by METHOD().
void(* ip_packet_t::destroy)(ip_packet_t *this)
Destroy an ip_packet_t
Definition at line 87 of file ip_packet.h.
Referenced by deliver_plain(), and process_outbound().
host_t*(* ip_packet_t::get_destination)(ip_packet_t *this)
Get the destination address of this packet
Returns
destination host
Definition at line 54 of file ip_packet.h.
Referenced by deliver_plain(), METHOD(), process_inbound(), and process_outbound().
chunk_t(* ip_packet_t::get_encoding)(ip_packet_t *this)
Get the complete IP packet (including the header)
Returns
IP packet (internal data)
Definition at line 68 of file ip_packet.h.
Referenced by deliver_plain(), process_inbound(), and process_outbound().
u_int8_t(* ip_packet_t::get_next_header)(ip_packet_t *this)
Get the protocol (IPv4) or next header (IPv6) field of this packet.
Returns
protocol|next header field
Definition at line 61 of file ip_packet.h.
Referenced by METHOD().
chunk_t(* ip_packet_t::get_payload)(ip_packet_t *this)
Get only the payload
Returns
IP payload (internal data)
Definition at line 75 of file ip_packet.h.
host_t*(* ip_packet_t::get_source)(ip_packet_t *this)
Get the source address of this packet
Returns
source host
Definition at line 47 of file ip_packet.h.
Referenced by METHOD(), process_inbound(), and process_outbound().
u_int8_t(* ip_packet_t::get_version)(ip_packet_t *this)
IP version of this packet
Returns
ip version
Definition at line 40 of file ip_packet.h.
Referenced by esp_packet_create_from_payload().
The documentation for this struct was generated from the following file:
ip_packet.h