strongSwan: fast_session
fast_session
libfast
Classes
struct fast_session_t
Typedefs
typedef struct fast_session_t fast_session_t
Functions
fast_session_t * fast_session_create (fast_context_t *context)
Detailed Description
Typedef Documentation
typedef struct fast_session_t fast_session_t
Definition at line 28 of file fast_session.h.
Function Documentation
fast_session_t* fast_session_create (fast_context_t * context)
Create a session new session.
Parameters
context user defined session context instance
Returns
client session, NULL on error
Definition at line 205 of file fast_session.c.
References context, create_sid(), destroy(), INIT, and linked_list_create().
Referenced by load_session().
 {
     private_fast_session_t *this;
     INIT(this,
         .public = {
             .add_controller = _add_controller,
             .add_filter = _add_filter,
             .process = _process,
             .get_sid = _get_sid,
             .destroy = _destroy,
         },
         .controllers = linked_list_create(),
         .filters = linked_list_create(),
         .context = context,
     );
     if (!create_sid(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }