strongSwan: id_payload.c File Reference
id_payload.c File Reference
#include <stddef.h>
#include "id_payload.h"
#include <daemon.h>
#include <encoding/payloads/encodings.h>
Classes
struct private_id_payload_t
Typedefs
typedef struct private_id_payload_t private_id_payload_t
Functions
METHOD (payload_t, verify, status_t, private_id_payload_t *this)
METHOD (payload_t, get_encoding_rules, int, private_id_payload_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_id_payload_t *this)
METHOD (payload_t, get_type, payload_type_t, private_id_payload_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_id_payload_t *this)
METHOD (payload_t, set_next_type, void, private_id_payload_t *this, payload_type_t type)
METHOD (payload_t, get_length, size_t, private_id_payload_t *this)
METHOD (id_payload_t, get_identification, identification_t *, private_id_payload_t *this)
static traffic_selector_t * get_ts_from_range (private_id_payload_t *this, ts_type_t type)
static traffic_selector_t * get_ts_from_subnet (private_id_payload_t *this, ts_type_t type)
static traffic_selector_t * get_ts_from_ip (private_id_payload_t *this, ts_type_t type)
METHOD (id_payload_t, get_ts, traffic_selector_t *, private_id_payload_t *this)
METHOD (id_payload_t, get_encoded, chunk_t, private_id_payload_t *this)
METHOD2 (payload_t, id_payload_t, destroy, void, private_id_payload_t *this)
id_payload_t * id_payload_create (payload_type_t type)
id_payload_t * id_payload_create_from_identification (payload_type_t type, identification_t *id)
id_payload_t * id_payload_create_from_ts (traffic_selector_t *ts)
Variables
static encoding_rule_t encodings_v2 []
static encoding_rule_t encodings_v1 []
Typedef Documentation
typedef struct private_id_payload_t private_id_payload_t
Definition at line 26 of file id_payload.c.
Function Documentation
static traffic_selector_t* get_ts_from_ip (private_id_payload_t * this, ts_type_t type) static
Create a traffic selector from an IP ID
Definition at line 280 of file id_payload.c.
References port, and traffic_selector_create_from_bytes().
Referenced by METHOD().
 {
     return traffic_selector_create_from_bytes(this->protocol_id, type,
                 this->id_data, this->port, this->id_data, this->port ?: 65535);
 }
static traffic_selector_t* get_ts_from_range (private_id_payload_t * this, ts_type_t type) static
Create a traffic selector from an range ID
Definition at line 247 of file id_payload.c.
References chunk_create(), chunk_skip(), and traffic_selector_create_from_bytes().
Referenced by METHOD().
 {
     return traffic_selector_create_from_bytes(this->protocol_id, type,
         chunk_create(this->id_data.ptr, this->id_data.len / 2), this->port,
         chunk_skip(this->id_data, this->id_data.len / 2), this->port ?: 65535);
 }
static traffic_selector_t* get_ts_from_subnet (private_id_payload_t * this, ts_type_t type) static
Create a traffic selector from an subnet ID
Definition at line 258 of file id_payload.c.
References chunk_clone, chunk_create(), chunk_free(), chunk_skip(), chunk_t::len, net, port, chunk_t::ptr, and traffic_selector_create_from_bytes().
Referenced by METHOD().
 {
     traffic_selector_t *ts;
     chunk_t net, netmask;
     int i;
     net = chunk_create(this->id_data.ptr, this->id_data.len / 2);
     netmask = chunk_clone(chunk_skip(this->id_data, this->id_data.len / 2));
     for (i = 0; i < net.len; i++)
     {
         netmask.ptr[i] = (netmask.ptr[i] ^ 0xFF) | net.ptr[i];
     }
     ts = traffic_selector_create_from_bytes(this->protocol_id, type,
                                 net, this->port, netmask, this->port ?: 65535);
     chunk_free(&netmask);
     return ts;
 }
METHOD (payload_t , verify , status_t , private_id_payload_t * this)
Definition at line 163 of file id_payload.c.
References DBG1, DBG_ENC, FAILED, FALSE, ID_IPV4_ADDR, ID_IPV4_ADDR_RANGE, ID_IPV4_ADDR_SUBNET, ID_IPV6_ADDR, ID_IPV6_ADDR_RANGE, ID_IPV6_ADDR_SUBNET, id_type_names, payload_type_short_names, PLV1_NAT_OA, PLV1_NAT_OA_DRAFT_00_03, SUCCESS, and type.
 {
     bool bad_length = FALSE;
     if ((this->type == PLV1_NAT_OA || this->type == PLV1_NAT_OA_DRAFT_00_03) &&
         this->id_type != ID_IPV4_ADDR && this->id_type != ID_IPV6_ADDR)
     {
         DBG1(DBG_ENC, "invalid ID type %N for %N payload", id_type_names,
              this->id_type, payload_type_short_names, this->type);
         return FAILED;
     }
     switch (this->id_type)
     {
         case ID_IPV4_ADDR_RANGE:
         case ID_IPV4_ADDR_SUBNET:
             bad_length = this->id_data.len != 8;
             break;
         case ID_IPV6_ADDR_RANGE:
         case ID_IPV6_ADDR_SUBNET:
             bad_length = this->id_data.len != 32;
             break;
     }
     if (bad_length)
     {
         DBG1(DBG_ENC, "invalid %N length (%d bytes)",
              id_type_names, this->id_type, this->id_data.len);
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (payload_t , get_encoding_rules , int , private_id_payload_t * this, encoding_rule_t ** rules)
Definition at line 195 of file id_payload.c.
References countof, encodings_v1, encodings_v2, PLV1_ID, PLV1_NAT_OA, PLV1_NAT_OA_DRAFT_00_03, and type.
 {
     if (this->type == PLV1_ID ||
         this->type == PLV1_NAT_OA || this->type == PLV1_NAT_OA_DRAFT_00_03)
     {
         *rules = encodings_v1;
         return countof(encodings_v1);
     }
     *rules = encodings_v2;
     return countof(encodings_v2);
 }
METHOD (payload_t , get_header_length , int , private_id_payload_t * this)
Definition at line 208 of file id_payload.c.
 {
     return 8;
 }
METHOD (payload_t , get_type , payload_type_t , private_id_payload_t * this)
Definition at line 214 of file id_payload.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_id_payload_t * this)
Definition at line 220 of file id_payload.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , set_next_type , void , private_id_payload_t * this, payload_type_t type)
Definition at line 226 of file id_payload.c.
References type.
 {
     this->next_payload = type;
 }
METHOD (payload_t , get_length , size_t , private_id_payload_t * this)
Definition at line 232 of file id_payload.c.
 {
     return this->payload_length;
 }
METHOD (id_payload_t , get_identification , identification_t * , private_id_payload_t * this)
Definition at line 238 of file id_payload.c.
References identification_create_from_encoding().
 {
     return identification_create_from_encoding(this->id_type, this->id_data);
 }
METHOD (id_payload_t , get_ts , traffic_selector_t * , private_id_payload_t * this)
Definition at line 287 of file id_payload.c.
References get_ts_from_ip(), get_ts_from_range(), get_ts_from_subnet(), ID_IPV4_ADDR, ID_IPV4_ADDR_RANGE, ID_IPV4_ADDR_SUBNET, ID_IPV6_ADDR, ID_IPV6_ADDR_RANGE, ID_IPV6_ADDR_SUBNET, TS_IPV4_ADDR_RANGE, and TS_IPV6_ADDR_RANGE.
 {
     switch (this->id_type)
     {
         case ID_IPV4_ADDR_SUBNET:
             if (this->id_data.len == 8)
             {
                 return get_ts_from_subnet(this, TS_IPV4_ADDR_RANGE);
             }
             break;
         case ID_IPV6_ADDR_SUBNET:
             if (this->id_data.len == 32)
             {
                 return get_ts_from_subnet(this, TS_IPV6_ADDR_RANGE);
             }
             break;
         case ID_IPV4_ADDR_RANGE:
             if (this->id_data.len == 8)
             {
                 return get_ts_from_range(this, TS_IPV4_ADDR_RANGE);
             }
             break;
         case ID_IPV6_ADDR_RANGE:
             if (this->id_data.len == 32)
             {
                 return get_ts_from_range(this, TS_IPV6_ADDR_RANGE);
             }
             break;
         case ID_IPV4_ADDR:
             if (this->id_data.len == 4)
             {
                 return get_ts_from_ip(this, TS_IPV4_ADDR_RANGE);
             }
             break;
         case ID_IPV6_ADDR:
             if (this->id_data.len == 16)
             {
                 return get_ts_from_ip(this, TS_IPV6_ADDR_RANGE);
             }
             break;
         default:
             break;
     }
     return NULL;
 }
METHOD (id_payload_t , get_encoded , chunk_t , private_id_payload_t * this)
Definition at line 334 of file id_payload.c.
References chunk_cat, chunk_from_thing, and port.
 {
     u_int16_t port = htons(this->port);
     return chunk_cat("cccc", chunk_from_thing(this->id_type),
                      chunk_from_thing(this->protocol_id),
                      chunk_from_thing(port), this->id_data);
 }
METHOD2 (payload_t , id_payload_t , destroy , void , private_id_payload_t * this)
Definition at line 343 of file id_payload.c.
References free().
 {
     free(this->id_data.ptr);
     free(this);
 }
Variable Documentation
encoding_rule_t encodings_v1[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_id_payload_t, next_payload)    },
    { RESERVED_BYTE,    offsetof(private_id_payload_t, reserved_byte[0])},
    { PAYLOAD_LENGTH,   offsetof(private_id_payload_t, payload_length)  },
    { U_INT_8,          offsetof(private_id_payload_t, id_type)         },
    { U_INT_8,          offsetof(private_id_payload_t, protocol_id)     },
    { U_INT_16,         offsetof(private_id_payload_t, port)            },
    { CHUNK_DATA,       offsetof(private_id_payload_t, id_data)         },
}
Encoding rules for an IKEv1 ID payload
Definition at line 134 of file id_payload.c.
Referenced by METHOD().
encoding_rule_t encodings_v2[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_id_payload_t, next_payload)    },
    { FLAG,             offsetof(private_id_payload_t, critical)        },
    { RESERVED_BIT,     offsetof(private_id_payload_t, reserved_bit[0]) },
    { RESERVED_BIT,     offsetof(private_id_payload_t, reserved_bit[1]) },
    { RESERVED_BIT,     offsetof(private_id_payload_t, reserved_bit[2]) },
    { RESERVED_BIT,     offsetof(private_id_payload_t, reserved_bit[3]) },
    { RESERVED_BIT,     offsetof(private_id_payload_t, reserved_bit[4]) },
    { RESERVED_BIT,     offsetof(private_id_payload_t, reserved_bit[5]) },
    { RESERVED_BIT,     offsetof(private_id_payload_t, reserved_bit[6]) },
    { PAYLOAD_LENGTH,   offsetof(private_id_payload_t, payload_length)  },
    { U_INT_8,          offsetof(private_id_payload_t, id_type)         },
    { RESERVED_BYTE,    offsetof(private_id_payload_t, reserved_byte[0])},
    { RESERVED_BYTE,    offsetof(private_id_payload_t, reserved_byte[1])},
    { RESERVED_BYTE,    offsetof(private_id_payload_t, reserved_byte[2])},
    { CHUNK_DATA,       offsetof(private_id_payload_t, id_data)         },
}
Encoding rules for an IKEv2 ID payload
Definition at line 92 of file id_payload.c.
Referenced by METHOD().