strongSwan: eap_simaka_sql_plugin.c File Reference
eap_simaka_sql_plugin.c File Reference
#include "eap_simaka_sql_plugin.h"
#include "eap_simaka_sql_card.h"
#include "eap_simaka_sql_provider.h"
#include <daemon.h>
Classes
struct private_eap_simaka_sql_t
Typedefs
typedef struct
private_eap_simaka_sql_t private_eap_simaka_sql_t
Functions
METHOD (plugin_t, get_name, char *, private_eap_simaka_sql_t *this)
static bool load_db (private_eap_simaka_sql_t *this, plugin_feature_t *feature, bool reg, void *data)
static simaka_card_t * get_card (private_eap_simaka_sql_t *this)
static simaka_provider_t * get_provider (private_eap_simaka_sql_t *this)
METHOD (plugin_t, get_features, int, private_eap_simaka_sql_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_eap_simaka_sql_t *this)
plugin_t * eap_simaka_sql_plugin_create ()
Typedef Documentation
typedef struct private_eap_simaka_sql_t private_eap_simaka_sql_t
Definition at line 22 of file eap_simaka_sql_plugin.c.
Function Documentation
plugin_t* eap_simaka_sql_plugin_create ()
See header
Definition at line 151 of file eap_simaka_sql_plugin.c.
References INIT.
 {
     private_eap_simaka_sql_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
static simaka_card_t* get_card (private_eap_simaka_sql_t * this) static
Callback providing our card to register
Definition at line 101 of file eap_simaka_sql_plugin.c.
Referenced by METHOD().
 {
     return &this->card->card;
 }
static simaka_provider_t* get_provider (private_eap_simaka_sql_t * this) static
Callback providing our provider to register
Definition at line 109 of file eap_simaka_sql_plugin.c.
Referenced by METHOD().
 {
     return &this->provider->provider;
 }
static bool load_db (private_eap_simaka_sql_t * this, plugin_feature_t * feature, bool reg, void * data) static
Load database
Definition at line 59 of file eap_simaka_sql_plugin.c.
References database_factory_t::create, db, library_t::db, DBG1, DBG_CFG, database_t::destroy, eap_simaka_sql_card_create(), eap_simaka_sql_provider_create(), FALSE, settings_t::get_bool, settings_t::get_str, lib, library_t::ns, library_t::settings, TRUE, and uri.
Referenced by METHOD().
 {
     if (reg)
     {
         bool remove_used;
         char *uri;
         uri = lib->settings->get_str(lib->settings,
                                      "%s.plugins.eap-simaka-sql.database", NULL,
                                      lib->ns);
         if (!uri)
         {
             DBG1(DBG_CFG, "eap-simaka-sql database URI missing");
             return FALSE;
         }
         this->db = lib->db->create(lib->db, uri);
         if (!this->db)
         {
             DBG1(DBG_CFG, "opening eap-simaka-sql database failed");
             return FALSE;
         }
         remove_used = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.eap-simaka-sql.remove_used", FALSE,
                                 lib->ns);
         this->provider = eap_simaka_sql_provider_create(this->db, remove_used);
         this->card = eap_simaka_sql_card_create(this->db, remove_used);
         return TRUE;
     }
     this->card->destroy(this->card);
     this->provider->destroy(this->provider);
     this->db->destroy(this->db);
     this->card = NULL;
     this->provider = NULL;
     this->db = NULL;
     return TRUE;
 }
METHOD (plugin_t , get_name , char * , private_eap_simaka_sql_t * this)
Definition at line 50 of file eap_simaka_sql_plugin.c.
 {
     return "eap-simaka-sql";
 }
METHOD (plugin_t , get_features , int , private_eap_simaka_sql_t * this, plugin_feature_t * features[])
Definition at line 114 of file eap_simaka_sql_plugin.c.
References countof, DB_ANY, DB_MYSQL, DB_SQLITE, get_card(), get_provider(), load_db(), PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, PLUGIN_SDEPEND, and simaka_manager_register().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((void*)load_db, NULL),
             PLUGIN_PROVIDE(CUSTOM, "eap-simaka-sql-db"),
                 PLUGIN_DEPENDS(DATABASE, DB_ANY),
                 PLUGIN_SDEPEND(DATABASE, DB_SQLITE),
                 PLUGIN_SDEPEND(DATABASE, DB_MYSQL),
         PLUGIN_CALLBACK(simaka_manager_register, get_card),
             PLUGIN_PROVIDE(CUSTOM, "aka-card"),
                 PLUGIN_DEPENDS(CUSTOM, "aka-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-simaka-sql-db"),
             PLUGIN_PROVIDE(CUSTOM, "sim-card"),
                 PLUGIN_DEPENDS(CUSTOM, "sim-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-simaka-sql-db"),
         PLUGIN_CALLBACK(simaka_manager_register, get_provider),
             PLUGIN_PROVIDE(CUSTOM, "aka-provider"),
                 PLUGIN_DEPENDS(CUSTOM, "aka-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-simaka-sql-db"),
             PLUGIN_PROVIDE(CUSTOM, "sim-provider"),
                 PLUGIN_DEPENDS(CUSTOM, "sim-manager"),
                 PLUGIN_DEPENDS(CUSTOM, "eap-simaka-sql-db"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_eap_simaka_sql_t * this)
Definition at line 142 of file eap_simaka_sql_plugin.c.
References free().
 {
     free(this);
 }