strongSwan: imc_os_info_t Struct Reference
imc_os_info_t Struct Reference
imc_os_info
#include "imc_os_info.h"
Public Attributes
os_type_t(* get_type)(imc_os_info_t *this)
chunk_t(* get_name)(imc_os_info_t *this)
void(* get_numeric_version)(imc_os_info_t *this, u_int32_t *major, u_int32_t *minor)
chunk_t(* get_version)(imc_os_info_t *this)
os_fwd_status_t(* get_fwd_status)(imc_os_info_t *this)
bool(* get_default_pwd_status)(imc_os_info_t *this)
time_t(* get_uptime)(imc_os_info_t *this)
chunk_t(* get_setting)(imc_os_info_t *this, char *name)
enumerator_t *(* create_package_enumerator)(imc_os_info_t *this)
void(* destroy)(imc_os_info_t *this)
Detailed Description
Interface for the IMC Operating System (OS) information module
Definition at line 35 of file imc_os_info.h.
Member Data Documentation
enumerator_t*(* imc_os_info_t::create_package_enumerator)(imc_os_info_t *this)
Enumerates over all installed packages
Returns
return package enumerator
Definition at line 101 of file imc_os_info.h.
Referenced by add_installed_packages().
void(* imc_os_info_t::destroy)(imc_os_info_t *this)
Destroys an imc_os_info_t object.
Definition at line 106 of file imc_os_info.h.
Referenced by TNC_IMC_Terminate().
bool(* imc_os_info_t::get_default_pwd_status)(imc_os_info_t *this)
Get the default password status
Returns
TRUE if enabled, FALSE otherwise
Definition at line 79 of file imc_os_info.h.
Referenced by add_default_pwd_enabled().
os_fwd_status_t(* imc_os_info_t::get_fwd_status)(imc_os_info_t *this)
Get the OS IPv4 forwarding status
Returns
IP forwarding status
Definition at line 72 of file imc_os_info.h.
Referenced by add_forwarding_enabled(), and add_fwd_enabled().
chunk_t(* imc_os_info_t::get_name)(imc_os_info_t *this)
Get the OS product name or distribution
Returns
OS name
Definition at line 49 of file imc_os_info.h.
Referenced by add_product_info().
void(* imc_os_info_t::get_numeric_version)(imc_os_info_t *this, u_int32_t *major, u_int32_t *minor)
Get the numeric OS version or release
Parameters
major OS major version number
minor OS minor version number
Definition at line 57 of file imc_os_info.h.
Referenced by add_numeric_version().
chunk_t(* imc_os_info_t::get_setting)(imc_os_info_t *this, char *name)
Get an OS setting (restricted to /proc, /sys, and /etc)
Parameters
name name of OS setting
Returns
value of OS setting
Definition at line 94 of file imc_os_info.h.
Referenced by add_device_id(), and add_settings().
os_type_t(* imc_os_info_t::get_type)(imc_os_info_t *this)
Get the OS type if it can be determined
Returns
OS type
Definition at line 42 of file imc_os_info.h.
Referenced by add_device_id(), and add_product_info().
time_t(* imc_os_info_t::get_uptime)(imc_os_info_t *this)
Get the OS uptime in seconds
Returns
OS uptime
Definition at line 86 of file imc_os_info.h.
Referenced by add_op_status().
chunk_t(* imc_os_info_t::get_version)(imc_os_info_t *this)
Get the OS version or release
Returns
OS version
Definition at line 65 of file imc_os_info.h.
Referenced by add_string_version().
The documentation for this struct was generated from the following file:
imc_os_info.h