strongSwan: kernel_iph_net.c File Reference
kernel_iph_net.c File Reference
#include <winsock2.h>
#include <ws2ipdef.h>
#include <windows.h>
#include <ntddndis.h>
#include <naptypes.h>
#include <iphlpapi.h>
#include "kernel_iph_net.h"
#include <hydra.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_kernel_iph_net_t
struct iface_t
struct MIB_IPINTERFACE_ROW_FIXUP
struct addr_enumerator_t
Macros
#define _WIN32_WINNT 0x0601
#define ROAM_DELAY 500
Typedefs
typedef struct
private_kernel_iph_net_t private_kernel_iph_net_t
Functions
static void iface_destroy (iface_t *this)
ENUM (if_oper_names, IfOperStatusUp, IfOperStatusLowerLayerDown,"Up","Down","Testing","Unknown","Dormant","NotPresent","LowerLayerDown",)
static job_requeue_t roam_event (private_kernel_iph_net_t *this)
static void fire_roam_event (private_kernel_iph_net_t *this, bool address)
static void update_addrs (private_kernel_iph_net_t *this, iface_t *entry, IP_ADAPTER_ADDRESSES *addr, bool log)
static void add_interface (private_kernel_iph_net_t *this, IP_ADAPTER_ADDRESSES *addr, bool log)
static void remove_interface (private_kernel_iph_net_t *this, NET_IFINDEX index)
static void update_interface (private_kernel_iph_net_t *this, IP_ADAPTER_ADDRESSES *addr)
static void WINAPI change_interface (void *user, PMIB_IPINTERFACE_ROW row_badal, MIB_NOTIFICATION_TYPE type)
static iface_t * address2entry (private_kernel_iph_net_t *this, host_t *ip)
METHOD (kernel_net_t, get_interface_name, bool, private_kernel_iph_net_t *this, host_t *ip, char **name)
METHOD (enumerator_t, addr_enumerate, bool, addr_enumerator_t *this, host_t **host)
METHOD (enumerator_t, addr_destroy, void, addr_enumerator_t *this)
METHOD (kernel_net_t, create_address_enumerator, enumerator_t *, private_kernel_iph_net_t *this, kernel_address_type_t which)
METHOD (kernel_net_t, get_source_addr, host_t *, private_kernel_iph_net_t *this, host_t *dest, host_t *src)
METHOD (kernel_net_t, get_nexthop, host_t *, private_kernel_iph_net_t *this, host_t *dest, int prefix, host_t *src)
METHOD (kernel_net_t, add_ip, status_t, private_kernel_iph_net_t *this, host_t *virtual_ip, int prefix, char *iface_name)
METHOD (kernel_net_t, del_ip, status_t, private_kernel_iph_net_t *this, host_t *virtual_ip, int prefix, bool wait)
static status_t manage_route (private_kernel_iph_net_t *this, bool add, chunk_t dst, u_int8_t prefixlen, host_t *gtw, char *name)
METHOD (kernel_net_t, add_route, status_t, private_kernel_iph_net_t *this, chunk_t dst, u_int8_t prefixlen, host_t *gateway, host_t *src, char *name)
METHOD (kernel_net_t, del_route, status_t, private_kernel_iph_net_t *this, chunk_t dst, u_int8_t prefixlen, host_t *gateway, host_t *src, char *name)
METHOD (kernel_net_t, destroy, void, private_kernel_iph_net_t *this)
kernel_iph_net_t * kernel_iph_net_create ()
Macro Definition Documentation
#define _WIN32_WINNT 0x0601
Definition at line 17 of file kernel_iph_net.c.
#define ROAM_DELAY 500
delay before firing roam events (ms)
Definition at line 34 of file kernel_iph_net.c.
Referenced by fire_roam_event().
Typedef Documentation
typedef struct private_kernel_iph_net_t private_kernel_iph_net_t
Definition at line 36 of file kernel_iph_net.c.
Function Documentation
static void add_interface (private_kernel_iph_net_t * this, IP_ADAPTER_ADDRESSES * addr, bool log) static
Add an interface entry
Definition at line 234 of file kernel_iph_net.c.
References DBG1, DBG_KNL, desc, enumerator_t::destroy, enumerator_t::enumerate, FALSE, iface_t::ifdesc, iface_t::ifindex, iface_t::ifname, INIT, linked_list_create(), mutex_t::lock, mutex, strdup, TRUE, mutex_t::unlock, and update_addrs().
Referenced by change_interface().
 {
     enumerator_t *enumerator;
     iface_t *entry;
     bool exists = FALSE;
     this->mutex->lock(this->mutex);
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->ifindex == addr->IfIndex)
         {
             exists = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     if (!exists)
     {
         char desc[128] = "";
         wcstombs(desc, addr->Description, sizeof(desc));
         INIT(entry,
             .ifindex = addr->IfIndex,
             .ifname = strdup(addr->AdapterName),
             .ifdesc = strdup(desc),
             .iftype = addr->IfType,
             .status = addr->OperStatus,
             .addrs = linked_list_create(),
         );
         if (log)
         {
             DBG1(DBG_KNL, "interface %u '%s' appeared",
                  entry->ifindex, entry->ifdesc);
         }
         this->mutex->lock(this->mutex);
         update_addrs(this, entry, addr, log);
         this->ifaces->insert_last(this->ifaces, entry);
         this->mutex->unlock(this->mutex);
     }
 }
static iface_t* address2entry (private_kernel_iph_net_t * this, host_t * ip) static
Get an iface entry for a local address, does no locking
Definition at line 412 of file kernel_iph_net.c.
References iface_t::addrs, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, host, and host_t::ip_equals.
Referenced by METHOD().
 {
     enumerator_t *ifaces, *addrs;
     iface_t *entry, *found = NULL;
     host_t *host;
     ifaces = this->ifaces->create_enumerator(this->ifaces);
     while (!found && ifaces->enumerate(ifaces, &entry))
     {
         addrs = entry->addrs->create_enumerator(entry->addrs);
         while (!found && addrs->enumerate(addrs, &host))
         {
             if (host->ip_equals(host, ip))
             {
                 found = entry;
             }
         }
         addrs->destroy(addrs);
     }
     ifaces->destroy(ifaces);
     return found;
 }
static void WINAPI change_interface (void * user, PMIB_IPINTERFACE_ROW row_badal, MIB_NOTIFICATION_TYPE type) static
NotifyIpInterfaceChange() callback
Definition at line 358 of file kernel_iph_net.c.
References add_interface(), DBG1, DBG_KNL, FALSE, MIB_IPINTERFACE_ROW_FIXUP::InterfaceIndex, remove_interface(), res, size, TRUE, and update_interface().
Referenced by kernel_iph_net_create().
 {
     private_kernel_iph_net_t *this = user;
     MIB_IPINTERFACE_ROW_FIXUP* row = (MIB_IPINTERFACE_ROW_FIXUP*)row_badal;
     IP_ADAPTER_ADDRESSES addrs[64], *current;
     ULONG res, size = sizeof(addrs);
     if (row && type == MibDeleteInstance)
     {
         remove_interface(this, row->InterfaceIndex);
     }
     else
     {
         res = GetAdaptersAddresses(AF_UNSPEC,
                         GAA_FLAG_SKIP_ANYCAST | GAA_FLAG_SKIP_MULTICAST |
                         GAA_FLAG_SKIP_DNS_SERVER | GAA_FLAG_SKIP_FRIENDLY_NAME,
                         NULL, addrs, &size);
         if (res == NO_ERROR)
         {
             current = addrs;
             while (current)
             {
                 /* row is NULL only on MibInitialNotification */
                 if (!row || row->InterfaceIndex == current->IfIndex)
                 {
                     switch (type)
                     {
                         case MibParameterNotification:
                             update_interface(this, current);
                             break;
                         case MibInitialNotification:
                             add_interface(this, current, FALSE);
                             break;
                         case MibAddInstance:
                             add_interface(this, current, TRUE);
                             break;
                         default:
                             break;
                     }
                 }
                 current = current->Next;
             }
         }
         else
         {
             DBG1(DBG_KNL, "getting IPH adapter addresses failed: 0x%08lx", res);
         }
     }
 }
ENUM (if_oper_names , IfOperStatusUp , IfOperStatusLowerLayerDown , "Up" , "Down" , "Testing" , "Unknown" , "Dormant" , "NotPresent" , "LowerLayerDown")
Enum names for Windows IF_OPER_STATUS
static void fire_roam_event (private_kernel_iph_net_t * this, bool address) static
Fire delayed roam event, caller should hold mutex
Definition at line 140 of file kernel_iph_net.c.
References callback_job_create(), lib, ROAM_DELAY, roam_event(), scheduler_t::schedule_job_ms, library_t::scheduler, time_monotonic(), and timeval_add_ms().
Referenced by remove_interface(), update_addrs(), and update_interface().
 {
     timeval_t now;
     time_monotonic(&now);
     this->roam_address |= address;
     if (timercmp(&now, &this->roam_next, >))
     {
         timeval_add_ms(&now, ROAM_DELAY);
         this->roam_next = now;
         lib->scheduler->schedule_job_ms(lib->scheduler, (job_t*)
                             callback_job_create((callback_job_cb_t)roam_event,
                                                 this, NULL, NULL),
                             ROAM_DELAY);
     }
 }
static void iface_destroy (iface_t * this) static
Clean up an iface_t
Definition at line 100 of file kernel_iph_net.c.
References destroy(), and free().
Referenced by METHOD(), and remove_interface().
 {
     this->addrs->destroy_offset(this->addrs, offsetof(host_t, destroy));
     free(this->ifname);
     free(this->ifdesc);
     free(this);
 }
static status_t manage_route (private_kernel_iph_net_t * this, bool add, chunk_t dst, u_int8_t prefixlen, host_t * gtw, char * name) static
Add or remove a route
Definition at line 619 of file kernel_iph_net.c.
References DBG1, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, FAILED, host_t::get_sockaddr, host_t::get_sockaddr_len, iface_t::ifindex, iface_t::ifname, chunk_t::len, mutex_t::lock, memcpy, mutex, NOT_FOUND, chunk_t::ptr, router, streq(), SUCCESS, and mutex_t::unlock.
Referenced by METHOD().
 {
     MIB_IPFORWARD_ROW2 row = {
         .DestinationPrefix = {
             .PrefixLength = prefixlen,
         },
         .SitePrefixLength = prefixlen,
         .ValidLifetime = INFINITE,
         .PreferredLifetime = INFINITE,
         .Metric = 10,
         .Protocol = MIB_IPPROTO_NETMGMT,
     };
     enumerator_t *enumerator;
     iface_t *entry;
     ULONG ret;
     this->mutex->lock(this->mutex);
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (streq(name, entry->ifname))
         {
             row.InterfaceIndex = entry->ifindex;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     if (!row.InterfaceIndex)
     {
         return NOT_FOUND;
     }
     switch (dst.len)
     {
         case 4:
             row.DestinationPrefix.Prefix.si_family = AF_INET;
             memcpy(&row.DestinationPrefix.Prefix.Ipv4.sin_addr,
                    dst.ptr, dst.len);
             break;
         case 16:
             row.DestinationPrefix.Prefix.si_family = AF_INET6;
             memcpy(&row.DestinationPrefix.Prefix.Ipv6.sin6_addr,
                    dst.ptr, dst.len);
             break;
         default:
             return FAILED;
     }
     if (gtw)
     {
         memcpy(&row.NextHop, gtw->get_sockaddr(gtw),
                *gtw->get_sockaddr_len(gtw));
     }
     if (add)
     {
         ret = CreateIpForwardEntry2(&row);
     }
     else
     {
         ret = DeleteIpForwardEntry2(&row);
     }
     if (ret != NO_ERROR)
     {
         DBG1(DBG_KNL, "%sing route failed: 0x%08lx", add ? "add" : "remov", ret);
         return FAILED;
     }
     if (add)
     {
         ret = EnableRouter(NULL, &this->router);
         if (ret != ERROR_IO_PENDING)
         {
             DBG1(DBG_KNL, "EnableRouter router failed: 0x%08lx", ret);
         }
     }
     else
     {
         ret = UnenableRouter(&this->router, NULL);
         if (ret != NO_ERROR)
         {
             DBG1(DBG_KNL, "UnenableRouter router failed: 0x%08lx", ret);
         }
     }
     return SUCCESS;
 }
METHOD (kernel_net_t , get_interface_name , bool , private_kernel_iph_net_t * this, host_t * ip, char ** name)
Definition at line 436 of file kernel_iph_net.c.
References address2entry(), iface_t::ifname, mutex_t::lock, mutex, strdup, and mutex_t::unlock.
 {
     iface_t *entry;
     this->mutex->lock(this->mutex);
     entry = address2entry(this, ip);
     if (entry && name)
     {
         *name = strdup(entry->ifname);
     }
     this->mutex->unlock(this->mutex);
     return entry != NULL;
 }
METHOD (enumerator_t , addr_enumerate , bool , addr_enumerator_t * this, host_t ** host)
Definition at line 468 of file kernel_iph_net.c.
References ADDR_TYPE_DOWN, ADDR_TYPE_LOOPBACK, iface_t::addrs, linked_list_t::create_enumerator, FALSE, iface_t::iftype, iface_t::status, and TRUE.
 {
     iface_t *entry;
     while (TRUE)
     {
         while (!this->addrs)
         {
             if (!this->ifaces->enumerate(this->ifaces, &entry))
             {
                 return FALSE;
             }
             if (entry->iftype == IF_TYPE_SOFTWARE_LOOPBACK &&
                 !(this->which & ADDR_TYPE_LOOPBACK))
             {
                 continue;
             }
             if (entry->status != IfOperStatusUp &&
                 !(this->which & ADDR_TYPE_DOWN))
             {
                 continue;
             }
             this->addrs = entry->addrs->create_enumerator(entry->addrs);
         }
         if (this->addrs->enumerate(this->addrs, host))
         {
             return TRUE;
         }
         this->addrs->destroy(this->addrs);
         this->addrs = NULL;
     }
 }
METHOD (enumerator_t , addr_destroy , void , addr_enumerator_t * this)
Definition at line 502 of file kernel_iph_net.c.
References DESTROY_IF, free(), mutex, and mutex_t::unlock.
 {
     DESTROY_IF(this->addrs);
     this->ifaces->destroy(this->ifaces);
     this->mutex->unlock(this->mutex);
     free(this);
 }
METHOD (kernel_net_t , create_address_enumerator , enumerator_t * , private_kernel_iph_net_t * this, kernel_address_type_t which)
Definition at line 511 of file kernel_iph_net.c.
References ADDR_TYPE_REGULAR, destroy(), enumerator_create_empty(), INIT, mutex_t::lock, mutex, and addr_enumerator_t::public.
 {
     addr_enumerator_t *enumerator;
     if (!(which & ADDR_TYPE_REGULAR))
     {
         /* we currently have no virtual, but regular IPs only */
         return enumerator_create_empty();
     }
     this->mutex->lock(this->mutex);
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_addr_enumerate,
             .destroy = _addr_destroy,
         },
         .which = which,
         .ifaces = this->ifaces->create_enumerator(this->ifaces),
         .mutex = this->mutex,
     );
     return &enumerator->public;
 }
METHOD (kernel_net_t , get_source_addr , host_t * , private_kernel_iph_net_t * this, host_t * dest, host_t * src)
Definition at line 536 of file kernel_iph_net.c.
References DBG1, DBG2, DBG_KNL, DWORD, host_t::get_sockaddr, host_create_from_sockaddr(), and res.
 {
     MIB_IPFORWARD_ROW2 route;
     SOCKADDR_INET best, *sai_dst, *sai_src = NULL;
     DWORD res, index = 0;
     res = GetBestInterfaceEx(dest->get_sockaddr(dest), &index);
     if (res != NO_ERROR)
     {
         DBG1(DBG_KNL, "getting interface to %H failed: 0x%08x", dest, res);
         return NULL;
     }
     sai_dst = (SOCKADDR_INET*)dest->get_sockaddr(dest);
     if (src)
     {
         sai_src = (SOCKADDR_INET*)src->get_sockaddr(src);
     }
     res = GetBestRoute2(0, index, sai_src, sai_dst, 0, &route, &best);
     if (res != NO_ERROR)
     {
         DBG2(DBG_KNL, "getting src address to %H failed: 0x%08x", dest, res);
         return NULL;
     }
     return host_create_from_sockaddr((struct sockaddr*)&best);
 }
METHOD (kernel_net_t , get_nexthop , host_t * , private_kernel_iph_net_t * this, host_t * dest, int prefix, host_t * src)
Definition at line 564 of file kernel_iph_net.c.
References DBG1, DBG2, DBG_KNL, host_t::destroy, DWORD, host_t::get_sockaddr, host_create_from_sockaddr(), host_t::is_anyaddr, and res.
 {
     MIB_IPFORWARD_ROW2 route;
     SOCKADDR_INET best, *sai_dst, *sai_src = NULL;
     DWORD res, index = 0;
     host_t *nexthop;
     res = GetBestInterfaceEx(dest->get_sockaddr(dest), &index);
     if (res != NO_ERROR)
     {
         DBG1(DBG_KNL, "getting interface to %H failed: 0x%08x", dest, res);
         return NULL;
     }
     sai_dst = (SOCKADDR_INET*)dest->get_sockaddr(dest);
     if (src)
     {
         sai_src = (SOCKADDR_INET*)src->get_sockaddr(src);
     }
     res = GetBestRoute2(0, index, sai_src, sai_dst, 0, &route, &best);
     if (res != NO_ERROR)
     {
         DBG2(DBG_KNL, "getting nexthop to %H failed: 0x%08x", dest, res);
         return NULL;
     }
     nexthop = host_create_from_sockaddr((struct sockaddr*)&route.NextHop);
     if (nexthop)
     {
         if (!nexthop->is_anyaddr(nexthop))
         {
             return nexthop;
         }
         nexthop->destroy(nexthop);
     }
     return NULL;
 }
METHOD (kernel_net_t , add_ip , status_t , private_kernel_iph_net_t * this, host_t * virtual_ip, int prefix, char * iface_name)
Definition at line 602 of file kernel_iph_net.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_net_t , del_ip , status_t , private_kernel_iph_net_t * this, host_t * virtual_ip, int prefix, bool wait)
Definition at line 609 of file kernel_iph_net.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_net_t , add_route , status_t , private_kernel_iph_net_t * this, chunk_t dst, u_int8_t prefixlen, host_t * gateway, host_t * src, char * name)
Definition at line 707 of file kernel_iph_net.c.
References manage_route(), and TRUE.
 {
     return manage_route(this, TRUE, dst, prefixlen, gateway, name);
 }
METHOD (kernel_net_t , del_route , status_t , private_kernel_iph_net_t * this, chunk_t dst, u_int8_t prefixlen, host_t * gateway, host_t * src, char * name)
Definition at line 714 of file kernel_iph_net.c.
References FALSE, and manage_route().
 {
     return manage_route(this, FALSE, dst, prefixlen, gateway, name);
 }
METHOD (kernel_net_t , destroy , void , private_kernel_iph_net_t * this)
Definition at line 721 of file kernel_iph_net.c.
References mutex_t::destroy, free(), iface_destroy(), mutex, and router.
 {
     if (this->changes)
     {
         CancelMibChangeNotify2(this->changes);
     }
     CloseHandle(this->router.hEvent);
     this->mutex->destroy(this->mutex);
     this->ifaces->destroy_function(this->ifaces, (void*)iface_destroy);
     free(this);
 }
static void remove_interface (private_kernel_iph_net_t * this, NET_IFINDEX index) static
Remove an interface entry that is gone
Definition at line 285 of file kernel_iph_net.c.
References DBG1, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, fire_roam_event(), iface_destroy(), iface_t::ifdesc, iface_t::ifindex, mutex_t::lock, mutex, TRUE, and mutex_t::unlock.
Referenced by change_interface().
 {
     enumerator_t *enumerator;
     iface_t *entry;
     this->mutex->lock(this->mutex);
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->ifindex == index)
         {
             this->ifaces->remove_at(this->ifaces, enumerator);
             DBG1(DBG_KNL, "interface %u '%s' disappeared",
                  entry->ifindex, entry->ifdesc);
             iface_destroy(entry);
             fire_roam_event(this, TRUE);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }
static job_requeue_t roam_event (private_kernel_iph_net_t * this) static
Callback function that raises the delayed roam event
Definition at line 124 of file kernel_iph_net.c.
References FALSE, hydra, JOB_REQUEUE_NONE, hydra_t::kernel_interface, mutex_t::lock, mutex, kernel_interface_t::roam, and mutex_t::unlock.
Referenced by fire_roam_event().
 {
     bool address;
     this->mutex->lock(this->mutex);
     address = this->roam_address;
     this->roam_address = FALSE;
     this->mutex->unlock(this->mutex);
     hydra->kernel_interface->roam(hydra->kernel_interface, address);
     return JOB_REQUEUE_NONE;
 }
static void update_addrs (private_kernel_iph_net_t * this, iface_t * entry, IP_ADAPTER_ADDRESSES * addr, bool log) static
Update addresses for an iface entry
Definition at line 160 of file kernel_iph_net.c.
References iface_t::addrs, linked_list_t::create_enumerator, DBG1, DBG_KNL, enumerator_t::destroy, host_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, FALSE, fire_roam_event(), found, host, host_create_from_sockaddr(), if(), iface_t::ifdesc, iface_t::ifindex, linked_list_t::insert_last, host_t::ip_equals, linked_list_create(), list, linked_list_t::remove_at, linked_list_t::remove_first, SUCCESS, and TRUE.
Referenced by add_interface(), and update_interface().
 {
     IP_ADAPTER_UNICAST_ADDRESS *current;
     enumerator_t *enumerator;
     linked_list_t *list;
     host_t *host, *old;
     bool changes = FALSE;
     list = entry->addrs;
     entry->addrs = linked_list_create();
     for (current = addr->FirstUnicastAddress; current; current = current->Next)
     {
         if (current->Address.lpSockaddr->sa_family == AF_INET6)
         {
             struct sockaddr_in6 *sin;
             sin = (struct sockaddr_in6*)current->Address.lpSockaddr;
             if (IN6_IS_ADDR_LINKLOCAL(&sin->sin6_addr))
             {
                 continue;
             }
         }
         host = host_create_from_sockaddr(current->Address.lpSockaddr);
         if (host)
         {
             bool found = FALSE;
             enumerator = list->create_enumerator(list);
             while (enumerator->enumerate(enumerator, &old))
             {
                 if (host->ip_equals(host, old))
                 {
                     list->remove_at(list, enumerator);
                     old->destroy(old);
                     found = TRUE;
                 }
             }
             enumerator->destroy(enumerator);
             entry->addrs->insert_last(entry->addrs, host);
             if (!found && log)
             {
                 DBG1(DBG_KNL, "%H appeared on interface %u '%s'",
                      host, entry->ifindex, entry->ifdesc);
                 changes = TRUE;
             }
         }
     }
     while (list->remove_first(list, (void**)&old) == SUCCESS)
     {
         if (log)
         {
             DBG1(DBG_KNL, "%H disappeared from interface %u '%s'",
                  old, entry->ifindex, entry->ifdesc);
             changes = TRUE;
         }
         old->destroy(old);
     }
     list->destroy(list);
     if (changes)
     {
         fire_roam_event(this, TRUE);
     }
 }
static void update_interface (private_kernel_iph_net_t * this, IP_ADAPTER_ADDRESSES * addr) static
Update an interface entry changed
Definition at line 310 of file kernel_iph_net.c.
References DBG1, DBG_KNL, enumerator_t::destroy, enumerator_t::enumerate, fire_roam_event(), iface_t::ifdesc, iface_t::ifindex, mutex_t::lock, mutex, iface_t::status, TRUE, mutex_t::unlock, and update_addrs().
Referenced by change_interface().
 {
     enumerator_t *enumerator;
     iface_t *entry;
     this->mutex->lock(this->mutex);
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->ifindex == addr->IfIndex)
         {
             if (entry->status != addr->OperStatus)
             {
                 DBG1(DBG_KNL, "interface %u '%s' changed state from %N to %N",
                      entry->ifindex, entry->ifdesc, if_oper_names,
                      entry->status, if_oper_names, addr->OperStatus);
                 entry->status = addr->OperStatus;
                 fire_roam_event(this, TRUE);
             }
             update_addrs(this, entry, addr, TRUE);
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
 }