strongSwan: pwg_attr
pwg_attr
libimcv
Typedefs
typedef enum pwg_attr_t pwg_attr_t
Enumerations
enum pwg_attr_t {
PWG_HCD_ATTRS_NATURAL_LANG = 0x00000001, PWG_HCD_MACHINE_TYPE_MODEL = 0x00000002, PWG_HCD_VENDOR_NAME = 0x00000003, PWG_HCD_VENDOR_SMI_CODE = 0x00000004,
PWG_HCD_DEFAULT_PWD_ENABLED = 0x00000014, PWG_HCD_FIREWALL_SETTING = 0x00000015, PWG_HCD_FORWARDING_ENABLED = 0x00000016, PWG_HCD_PSTN_FAX_ENABLED = 0x00000028,
PWG_HCD_TIME_SOURCE = 0x00000032, PWG_HCD_FIRMWARE_NAME = 0x0000003C, PWG_HCD_FIRMWARE_PATCHES = 0x0000003D, PWG_HCD_FIRMWARE_STRING_VERSION = 0x0000003E,
PWG_HCD_FIRMWARE_VERSION = 0x0000003F, PWG_HCD_RESIDENT_APP_NAME = 0x00000050, PWG_HCD_RESIDENT_APP_PATCHES = 0x00000051, PWG_HCD_RESIDENT_APP_STRING_VERSION = 0x00000052,
PWG_HCD_RESIDENT_APP_VERSION = 0x00000053, PWG_HCD_USER_APP_NAME = 0x00000064, PWG_HCD_USER_APP_PATCHES = 0x00000065, PWG_HCD_USER_APP_STRING_VERSION = 0x00000066,
PWG_HCD_USER_APP_VERSION = 0x00000067, PWG_HCD_USER_APP_ENABLED = 0x00000068, PWG_HCD_USER_APP_PERSIST_ENABLED = 0x00000069, PWG_HCD_CERTIFICATION_STATE = 0x000000C8,
PWG_HCD_CONFIGURATION_STATE = 0x000000C9
}
Functions
pa_tnc_attr_t * pwg_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Variables
enum_name_t * pwg_attr_names
Detailed Description
Typedef Documentation
typedef enum pwg_attr_t pwg_attr_t
Definition at line 27 of file pwg_attr.h.
Enumeration Type Documentation
enum pwg_attr_t
PWG HCD IF-M Attributes (Hardcopy Device Health Assessment TNC Binding)
Enumerator
PWG_HCD_ATTRS_NATURAL_LANG
PWG_HCD_MACHINE_TYPE_MODEL
PWG_HCD_VENDOR_NAME
PWG_HCD_VENDOR_SMI_CODE
PWG_HCD_DEFAULT_PWD_ENABLED
PWG_HCD_FIREWALL_SETTING
PWG_HCD_FORWARDING_ENABLED
PWG_HCD_PSTN_FAX_ENABLED
PWG_HCD_TIME_SOURCE
PWG_HCD_FIRMWARE_NAME
PWG_HCD_FIRMWARE_PATCHES
PWG_HCD_FIRMWARE_STRING_VERSION
PWG_HCD_FIRMWARE_VERSION
PWG_HCD_RESIDENT_APP_NAME
PWG_HCD_RESIDENT_APP_PATCHES
PWG_HCD_RESIDENT_APP_STRING_VERSION
PWG_HCD_RESIDENT_APP_VERSION
PWG_HCD_USER_APP_NAME
PWG_HCD_USER_APP_PATCHES
PWG_HCD_USER_APP_STRING_VERSION
PWG_HCD_USER_APP_VERSION
PWG_HCD_USER_APP_ENABLED
PWG_HCD_USER_APP_PERSIST_ENABLED
PWG_HCD_CERTIFICATION_STATE
PWG_HCD_CONFIGURATION_STATE
Definition at line 32 of file pwg_attr.h.
                 {
     PWG_HCD_ATTRS_NATURAL_LANG =          0x00000001, /*   1 */
     PWG_HCD_MACHINE_TYPE_MODEL =          0x00000002, /*   2 */
     PWG_HCD_VENDOR_NAME =                 0x00000003, /*   3 */
     PWG_HCD_VENDOR_SMI_CODE =             0x00000004, /*   4 */
     PWG_HCD_DEFAULT_PWD_ENABLED =         0x00000014, /*  20 */
     PWG_HCD_FIREWALL_SETTING =            0x00000015, /*  21 */
     PWG_HCD_FORWARDING_ENABLED =          0x00000016, /*  22 */
     PWG_HCD_PSTN_FAX_ENABLED =            0x00000028, /*  40 */
     PWG_HCD_TIME_SOURCE =                 0x00000032, /*  50 ??? */
     PWG_HCD_FIRMWARE_NAME =               0x0000003C, /*  60 */
     PWG_HCD_FIRMWARE_PATCHES =            0x0000003D, /*  61 */
     PWG_HCD_FIRMWARE_STRING_VERSION =     0x0000003E, /*  62 */
     PWG_HCD_FIRMWARE_VERSION =            0x0000003F, /*  63 */
     PWG_HCD_RESIDENT_APP_NAME =           0x00000050, /*  80 */
     PWG_HCD_RESIDENT_APP_PATCHES =        0x00000051, /*  81 */
     PWG_HCD_RESIDENT_APP_STRING_VERSION = 0x00000052, /*  82 */
     PWG_HCD_RESIDENT_APP_VERSION =        0x00000053, /*  83 */
     PWG_HCD_USER_APP_NAME =               0x00000064, /* 100 */
     PWG_HCD_USER_APP_PATCHES =            0x00000065, /* 101 */
     PWG_HCD_USER_APP_STRING_VERSION =     0x00000066, /* 102 */
     PWG_HCD_USER_APP_VERSION =            0x00000067, /* 103 */
     PWG_HCD_USER_APP_ENABLED =            0x00000068, /* 104 */
     PWG_HCD_USER_APP_PERSIST_ENABLED =    0x00000069, /* 105 */
     PWG_HCD_CERTIFICATION_STATE =         0x000000C8, /* 200 */
     PWG_HCD_CONFIGURATION_STATE =         0x000000C9, /* 201 */
 };
Function Documentation
pa_tnc_attr_t* pwg_attr_create_from_data (u_int32_t type, size_t length, chunk_t value)
Create a TCG PA-TNC attribute from data
Parameters
type attribute type
length attribute length
value attribute value or segment
See header
Definition at line 78 of file pwg_attr.c.
References generic_attr_bool_create_from_data(), generic_attr_chunk_create_from_data(), generic_attr_string_create_from_data(), ietf_attr_fwd_enabled_create_from_data(), ietf_attr_port_filter_create_from_data(), PEN_PWG, pen_type_create(), pwg_attr_vendor_smi_code_create_from_data(), PWG_HCD_ATTRS_NATURAL_LANG, PWG_HCD_CERTIFICATION_STATE, PWG_HCD_CONFIGURATION_STATE, PWG_HCD_DEFAULT_PWD_ENABLED, PWG_HCD_FIREWALL_SETTING, PWG_HCD_FIRMWARE_NAME, PWG_HCD_FIRMWARE_PATCHES, PWG_HCD_FIRMWARE_STRING_VERSION, PWG_HCD_FIRMWARE_VERSION, PWG_HCD_FORWARDING_ENABLED, PWG_HCD_MACHINE_TYPE_MODEL, PWG_HCD_PSTN_FAX_ENABLED, PWG_HCD_RESIDENT_APP_NAME, PWG_HCD_RESIDENT_APP_PATCHES, PWG_HCD_RESIDENT_APP_STRING_VERSION, PWG_HCD_RESIDENT_APP_VERSION, PWG_HCD_TIME_SOURCE, PWG_HCD_USER_APP_ENABLED, PWG_HCD_USER_APP_NAME, PWG_HCD_USER_APP_PATCHES, PWG_HCD_USER_APP_PERSIST_ENABLED, PWG_HCD_USER_APP_STRING_VERSION, PWG_HCD_USER_APP_VERSION, PWG_HCD_VENDOR_NAME, and PWG_HCD_VENDOR_SMI_CODE.
Referenced by libimcv_init().
 {
     switch (type)
     {
         case PWG_HCD_DEFAULT_PWD_ENABLED:
         case PWG_HCD_USER_APP_ENABLED:
         case PWG_HCD_USER_APP_PERSIST_ENABLED:
         case PWG_HCD_PSTN_FAX_ENABLED:
             return generic_attr_bool_create_from_data(length, value,
                                     pen_type_create(PEN_PWG, type));
         case PWG_HCD_ATTRS_NATURAL_LANG:
         case PWG_HCD_MACHINE_TYPE_MODEL:
         case PWG_HCD_VENDOR_NAME:
         case PWG_HCD_FIRMWARE_NAME:
         case PWG_HCD_FIRMWARE_PATCHES:
         case PWG_HCD_FIRMWARE_STRING_VERSION:
         case PWG_HCD_TIME_SOURCE:
         case PWG_HCD_USER_APP_NAME:
         case PWG_HCD_USER_APP_PATCHES:
         case PWG_HCD_USER_APP_STRING_VERSION:
         case PWG_HCD_RESIDENT_APP_NAME:
         case PWG_HCD_RESIDENT_APP_PATCHES:
         case PWG_HCD_RESIDENT_APP_STRING_VERSION:
             return generic_attr_string_create_from_data(length, value,
                                     pen_type_create(PEN_PWG, type));
         case PWG_HCD_FIRMWARE_VERSION:
         case PWG_HCD_RESIDENT_APP_VERSION:
         case PWG_HCD_USER_APP_VERSION:
             return generic_attr_chunk_create_from_data(length, value, 16,
                                     pen_type_create(PEN_PWG, type));
         case PWG_HCD_CERTIFICATION_STATE:
         case PWG_HCD_CONFIGURATION_STATE:
             return generic_attr_chunk_create_from_data(length, value, 0,
                                     pen_type_create(PEN_PWG, type));
         case PWG_HCD_VENDOR_SMI_CODE:
             return pwg_attr_vendor_smi_code_create_from_data(length, value);
         case PWG_HCD_FORWARDING_ENABLED:
             return ietf_attr_fwd_enabled_create_from_data(length, value,
                                     pen_type_create(PEN_PWG, type));
         case PWG_HCD_FIREWALL_SETTING:
             return ietf_attr_port_filter_create_from_data(length, value,
                                     pen_type_create(PEN_PWG, type));
         default:
             return NULL;
     }
 }
Variable Documentation
enum_name_t* pwg_attr_names
enum name for pwg_attr_t.
Referenced by add_attrs_natural_lang(), add_certification_state(), add_configuration_state(), add_default_pwd_enabled(), add_forwarding_enabled(), add_machine_type_model(), add_pstn_fax_enabled(), add_quadruple(), add_time_source(), add_user_app_enabled(), add_user_app_persist_enabled(), add_vendor_name(), add_vendor_smi_code(), libimcv_init(), and receive_msg().