strongSwan: ita_attr_dummy
ita_attr_dummy
ita_attr
Classes
struct ita_attr_dummy_t
Typedefs
typedef struct ita_attr_dummy_t ita_attr_dummy_t
Functions
pa_tnc_attr_t * ita_attr_dummy_create (size_t size)
pa_tnc_attr_t * ita_attr_dummy_create_from_data (size_t length, chunk_t value)
Detailed Description
Typedef Documentation
typedef struct ita_attr_dummy_t ita_attr_dummy_t
Definition at line 24 of file ita_attr_dummy.h.
Function Documentation
pa_tnc_attr_t* ita_attr_dummy_create (size_t size)
Creates an ita_attr_dummy_t object with a given size
Parameters
size size of dummy attribute value
Described in header.
Definition at line 145 of file ita_attr_dummy.c.
References INIT, ITA_ATTR_DUMMY, PEN_ITA, and size.
Referenced by create_message(), and START_TEST().
 {
     private_ita_attr_dummy_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_size = _get_size,
         },
         .type = { PEN_ITA, ITA_ATTR_DUMMY },
         .length = size,
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ita_attr_dummy_create_from_data (size_t length, chunk_t data)
Creates an ita_attr_dummy_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 175 of file ita_attr_dummy.c.
References chunk_clone, INIT, ITA_ATTR_DUMMY, length, and PEN_ITA.
Referenced by ita_attr_create_from_data().
 {
     private_ita_attr_dummy_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_size = _get_size,
         },
         .type = { PEN_ITA, ITA_ATTR_DUMMY },
         .length = length,
         .value = chunk_clone(data),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }