strongSwan: eap_aka_3gpp2_provider
eap_aka_3gpp2_provider
eap_aka_3gpp2
Classes
struct eap_aka_3gpp2_provider_t
Typedefs
typedef struct
eap_aka_3gpp2_provider_t eap_aka_3gpp2_provider_t
Functions
eap_aka_3gpp2_provider_t * eap_aka_3gpp2_provider_create (eap_aka_3gpp2_functions_t *f)
Detailed Description
Typedef Documentation
typedef struct eap_aka_3gpp2_provider_t eap_aka_3gpp2_provider_t
Definition at line 28 of file eap_aka_3gpp2_provider.h.
Function Documentation
eap_aka_3gpp2_provider_t* eap_aka_3gpp2_provider_create (eap_aka_3gpp2_functions_t * f)
Create a eap_aka_3gpp2_provider instance.
See header
Definition at line 183 of file eap_aka_3gpp2_provider.c.
References destroy(), eap_aka_3gpp2_get_sqn(), INIT, return_false(), and return_null().
Referenced by register_functions().
 {
     private_eap_aka_3gpp2_provider_t *this;
     INIT(this,
         .public = {
             .provider = {
                 .get_triplet = (void*)return_false,
                 .get_quintuplet = _get_quintuplet,
                 .resync = _resync,
                 .is_pseudonym = (void*)return_null,
                 .gen_pseudonym = (void*)return_null,
                 .is_reauth = (void*)return_null,
                 .gen_reauth = (void*)return_null,
             },
             .destroy = _destroy,
         },
         .f = f,
     );
     /* use an offset to accept clock skew between client/server without resync */
     eap_aka_3gpp2_get_sqn(this->sqn, 180);
     return &this->public;
 }