strongSwan: xauth_pam_plugin.c File Reference
xauth_pam_plugin.c File Reference
#include "xauth_pam_plugin.h"
#include "xauth_pam.h"
#include "xauth_pam_listener.h"
#include <daemon.h>
Classes
struct private_xauth_pam_plugin_t
Macros
#define CAP_AUDIT_WRITE 29
Typedefs
typedef struct
private_xauth_pam_plugin_t private_xauth_pam_plugin_t
Functions
static bool register_listener (private_xauth_pam_plugin_t *this, plugin_feature_t *feature, bool reg, void *data)
METHOD (plugin_t, get_name, char *, private_xauth_pam_plugin_t *this)
METHOD (plugin_t, get_features, int, private_xauth_pam_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_xauth_pam_plugin_t *this)
plugin_t * xauth_pam_plugin_create ()
Macro Definition Documentation
#define CAP_AUDIT_WRITE 29
Definition at line 23 of file xauth_pam_plugin.c.
Referenced by xauth_pam_plugin_create().
Typedef Documentation
typedef struct private_xauth_pam_plugin_t private_xauth_pam_plugin_t
Definition at line 26 of file xauth_pam_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_xauth_pam_plugin_t * this)
Definition at line 66 of file xauth_pam_plugin.c.
 {
     return "xauth-pam";
 }
METHOD (plugin_t , get_features , int , private_xauth_pam_plugin_t * this, plugin_feature_t * features[])
Definition at line 72 of file xauth_pam_plugin.c.
References countof, PLUGIN_CALLBACK, PLUGIN_PROVIDE, register_listener(), xauth_method_register(), xauth_pam_create_server(), and XAUTH_SERVER.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(xauth_method_register, xauth_pam_create_server),
             PLUGIN_PROVIDE(XAUTH_SERVER, "pam"),
         PLUGIN_CALLBACK((plugin_feature_callback_t)register_listener, NULL),
             PLUGIN_PROVIDE(CUSTOM, "pam-session"),
     };
     *features = f;
     if (!this->session)
     {
         return 2;
     }
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_xauth_pam_plugin_t * this)
Definition at line 89 of file xauth_pam_plugin.c.
References tkm_listener_t::destroy, free(), and listener.
 {
     this->listener->destroy(this->listener),
     free(this);
 }
static bool register_listener (private_xauth_pam_plugin_t * this, plugin_feature_t * feature, bool reg, void * data) static
Register XAuth method and listener
Definition at line 52 of file xauth_pam_plugin.c.
References bus_t::add_listener, daemon_t::bus, charon, bus_t::remove_listener, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
     }
     return TRUE;
 }
plugin_t* xauth_pam_plugin_create ()
Definition at line 99 of file xauth_pam_plugin.c.
References CAP_AUDIT_WRITE, library_t::caps, DBG1, DBG_DMN, FALSE, settings_t::get_str, INIT, capabilities_t::keep, lib, library_t::ns, library_t::settings, and xauth_pam_listener_create().
 {
     private_xauth_pam_plugin_t *this;
     /* required for PAM authentication */
     if (!lib->caps->keep(lib->caps, CAP_AUDIT_WRITE))
     {
         DBG1(DBG_DMN, "xauth-pam plugin requires CAP_AUDIT_WRITE capability");
         return NULL;
     }
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .session = lib->settings->get_str(lib->settings,
                         "%s.plugins.xauth-pam.session", FALSE, lib->ns),
         .listener = xauth_pam_listener_create(),
     );
     return &this->public.plugin;
 }