strongSwan: eap_sim_file_provider
eap_sim_file_provider
eap_sim_file
Classes
struct eap_sim_file_provider_t
Typedefs
typedef struct
eap_sim_file_provider_t eap_sim_file_provider_t
Functions
eap_sim_file_provider_t * eap_sim_file_provider_create (eap_sim_file_triplets_t *triplets)
Detailed Description
Typedef Documentation
typedef struct eap_sim_file_provider_t eap_sim_file_provider_t
Definition at line 28 of file eap_sim_file_provider.h.
Function Documentation
eap_sim_file_provider_t* eap_sim_file_provider_create (eap_sim_file_triplets_t * triplets)
Create a eap_sim_file_provider instance.
See header
Definition at line 71 of file eap_sim_file_provider.c.
References INIT, return_false(), and return_null().
Referenced by load_triplets().
 {
     private_eap_sim_file_provider_t *this;
     INIT(this,
         .public = {
             .provider = {
                 .get_triplet = _get_triplet,
                 .get_quintuplet = (void*)return_false,
                 .resync = (void*)return_false,
                 .is_pseudonym = (void*)return_null,
                 .gen_pseudonym = (void*)return_null,
                 .is_reauth = (void*)return_null,
                 .gen_reauth = (void*)return_null,
             },
             .destroy = _destroy,
         },
         .triplets = triplets,
     );
     return &this->public;
 }