strongSwan: configuration_attribute
configuration_attribute
payloads
Classes
struct configuration_attribute_t
Typedefs
typedef struct
configuration_attribute_t configuration_attribute_t
Functions
configuration_attribute_t * configuration_attribute_create (payload_type_t type)
configuration_attribute_t * configuration_attribute_create_chunk (payload_type_t type, configuration_attribute_type_t attr_type, chunk_t chunk)
configuration_attribute_t * configuration_attribute_create_value (configuration_attribute_type_t attr_type, u_int16_t value)
Detailed Description
Typedef Documentation
typedef struct configuration_attribute_t configuration_attribute_t
Definition at line 25 of file configuration_attribute.h.
Function Documentation
configuration_attribute_t* configuration_attribute_create (payload_type_t type)
Creates an empty configuration attribute.
Parameters
type PLV2_CONFIGURATION_ATTRIBUTE or PLV1_CONFIGURATION_ATTRIBUTE
Returns
created configuration attribute
Definition at line 286 of file configuration_attribute.c.
References INIT, and type.
Referenced by configuration_attribute_create_chunk(), configuration_attribute_create_value(), and payload_create().
 {
     private_configuration_attribute_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_chunk = _get_chunk,
             .get_value = _get_value,
             .get_type = _get_cattr_type,
             .destroy = _destroy,
         },
         .type = type
     );
     return &this->public;
 }
configuration_attribute_t* configuration_attribute_create_chunk (payload_type_t type, configuration_attribute_type_t attr_type, chunk_t chunk)
Creates a configuration attribute with type and value.
Parameters
type PLV2_CONFIGURATION_ATTRIBUTE or PLV1_CONFIGURATION_ATTRIBUTE
attr_type type of configuration attribute
chunk attribute value, gets cloned
Returns
created configuration attribute
Definition at line 315 of file configuration_attribute.c.
References chunk_clone, configuration_attribute_create(), chunk_t::len, and value.
Referenced by add_attribute(), build_ack(), build_reply(), build_round(), build_vip(), and METHOD().
 {
     private_configuration_attribute_t *this;
     this = (private_configuration_attribute_t*)
                             configuration_attribute_create(type);
     this->attr_type = ((u_int16_t)attr_type) & 0x7FFF;
     this->value = chunk_clone(chunk);
     this->length_or_value = chunk.len;
     return &this->public;
 }
configuration_attribute_t* configuration_attribute_create_value (configuration_attribute_type_t attr_type, u_int16_t value)
Creates a IKEv1 configuration attribute with 2 bytes value (IKEv1 only).
Parameters
attr_type type of configuration attribute
value attribute value, gets cloned
Returns
created PLV1_CONFIGURATION_ATTRIBUTE configuration attribute
Definition at line 332 of file configuration_attribute.c.
References configuration_attribute_create(), PLV1_CONFIGURATION_ATTRIBUTE, TRUE, and value.
Referenced by METHOD().
 {
     private_configuration_attribute_t *this;
     this = (private_configuration_attribute_t*)
                     configuration_attribute_create(PLV1_CONFIGURATION_ATTRIBUTE);
     this->attr_type = ((u_int16_t)attr_type) & 0x7FFF;
     this->length_or_value = value;
     this->af_flag = TRUE;
     return &this->public;
 }