strongSwan: message_t Struct Reference
message_t Struct Reference
message
#include "message.h"
Public Attributes
void(* set_major_version)(message_t *this, u_int8_t major_version)
u_int8_t(* get_major_version)(message_t *this)
void(* set_minor_version)(message_t *this, u_int8_t minor_version)
u_int8_t(* get_minor_version)(message_t *this)
void(* set_message_id)(message_t *this, u_int32_t message_id)
u_int32_t(* get_message_id)(message_t *this)
u_int64_t(* get_initiator_spi)(message_t *this)
u_int64_t(* get_responder_spi)(message_t *this)
void(* set_ike_sa_id)(message_t *this, ike_sa_id_t *ike_sa_id)
ike_sa_id_t *(* get_ike_sa_id)(message_t *this)
void(* set_exchange_type)(message_t *this, exchange_type_t exchange_type)
exchange_type_t(* get_exchange_type)(message_t *this)
payload_type_t(* get_first_payload_type)(message_t *this)
void(* set_request)(message_t *this, bool request)
bool(* get_request)(message_t *this)
void(* set_version_flag)(message_t *this)
bool(* get_reserved_header_bit)(message_t *this, u_int nr)
void(* set_reserved_header_bit)(message_t *this, u_int nr)
void(* add_payload)(message_t *this, payload_t *payload)
void(* add_notify)(message_t *this, bool flush, notify_type_t type, chunk_t data)
void(* disable_sort)(message_t *this)
status_t(* parse_header)(message_t *this)
status_t(* parse_body)(message_t *this, keymat_t *keymat)
status_t(* generate)(message_t *this, keymat_t *keymat, packet_t **packet)
bool(* is_encoded)(message_t *this)
status_t(* fragment)(message_t *this, keymat_t *keymat, size_t frag_len, enumerator_t **fragments)
bool(* is_fragmented)(message_t *this)
status_t(* add_fragment)(message_t *this, message_t *fragment)
host_t *(* get_source)(message_t *this)
void(* set_source)(message_t *this, host_t *host)
host_t *(* get_destination)(message_t *this)
void(* set_destination)(message_t *this, host_t *host)
enumerator_t *(* create_payload_enumerator)(message_t *this)
void(* remove_payload_at)(message_t *this, enumerator_t *enumerator)
payload_t *(* get_payload)(message_t *this, payload_type_t type)
notify_payload_t *(* get_notify)(message_t *this, notify_type_t type)
packet_t *(* get_packet)(message_t *this)
chunk_t(* get_packet_data)(message_t *this)
enumerator_t *(* get_fragments)(message_t *this)
void(* destroy)(message_t *this)
Detailed Description
This class is used to represent an IKE-Message.
The message handles parsing and generation of payloads via parser_t/generator_t. Encryption is done transparently via the encrypted_payload_t. A set of rules for messages and payloads does check parsed messages.
Definition at line 45 of file message.h.
Member Data Documentation
status_t(* message_t::add_fragment)(message_t *this, message_t *fragment)
Add a fragment to the message if it was created with message_create_defrag().
Once the message is completed it should be processed like any other inbound message.
Parameters
fragment fragment to add
Returns
SUCCESS if message was reassembled
NEED_MORE if not all fragments have yet been received
FAILED if reassembling failed
INVALID_ARG if fragment is invalid for some reason
INVALID_STATE if message was not created using message_create_defrag()
Definition at line 312 of file message.h.
void(* message_t::add_notify)(message_t *this, bool flush, notify_type_t type, chunk_t data)
Build a notify payload and add it to the message.
This is a helper method to create notify messages or add notify payload to messages. The flush parameter specifies if existing payloads should get removed before appending the notify.
Parameters
flush TRUE to remove existing payloads
type type of the notify
data a chunk of data to add to the notify, gets cloned
Definition at line 200 of file message.h.
Referenced by add_auth_lifetime(), add_ipcomp_notify(), add_radius_attribute(), build_address_list(), build_certreqs(), build_cookie(), build_payloads(), METHOD(), process_auth_response(), queue2ike(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), send_supported_hash_algorithms(), and START_TEST().
void(* message_t::add_payload)(message_t *this, payload_t *payload)
Append a payload to the message.
If the payload must be encrypted is not specified here. Encryption of payloads is evaluated via internal rules for the messages and is done before generation. The order of payloads may change, since all payloads to encrypt are added to the encryption payload, which is always the last one.
Parameters
payload payload to append
Definition at line 187 of file message.h.
Referenced by add_attribute_certs(), add_certreq(), add_endpoints_to_message(), add_im_certs(), add_initial_contact(), add_ke(), add_nat_oa_payloads(), add_natd_payloads(), add_nonce(), add_subject_cert(), add_ts(), build(), build_ack(), build_auth(), build_certreqs(), build_certs(), build_payloads(), build_reply(), build_request(), build_set(), create_fragment(), METHOD(), process_auth_response(), rebuild_auth(), send_check(), and send_notify().
enumerator_t*(* message_t::create_payload_enumerator)(message_t *this)
Create an enumerator over all payloads.
Returns
enumerator over payload_t
Definition at line 359 of file message.h.
Referenced by calculate_wire_size(), get_message_data(), get_ts(), has_notify_errors(), ike2queue(), METHOD(), parse_message(), print_radius_attributes(), process(), process_auth_response(), process_certreqs(), process_certs(), process_payloads(), process_request(), rebuild_auth(), set_bit(), set_byte(), and use_certs().
void(* message_t::destroy)(message_t *this)
Destroys a message and all including objects.
Definition at line 410 of file message.h.
Referenced by build_response(), handle_fragment(), METHOD(), process_request(), process_response(), queue_message(), receive_packets(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), and START_TEST().
void(* message_t::disable_sort)(message_t *this)
Disable automatic payload sorting for this message.
Definition at line 206 of file message.h.
Referenced by METHOD().
status_t(* message_t::fragment)(message_t *this, keymat_t *keymat, size_t frag_len, enumerator_t **fragments)
Generates the message split into fragments of the given size (total IP datagram length).
Parameters
keymat keymat to encrypt/sign message(s)
frag_len fragment length (maximum total IP datagram length), 0 for default value depending on address family
fragments receives an enumerator with generated packet_t*, which are owned by the enumerator
Returns
SUCCESS if message could be fragmented
FAILED if fragmentation failed
and the possible return values of generate()
Definition at line 281 of file message.h.
Referenced by METHOD().
status_t(* message_t::generate)(message_t *this, keymat_t *keymat, packet_t **packet)
Generates the UDP packet of specific message.
Payloads which must be encrypted are generated first and added to an encryption payload. This encryption payload will get encrypted and signed via the supplied aead transform (if given). Generation is only done once, multiple calls will just return a copy of the packet.
Parameters
keymat keymat to encrypt/sign message
packet copy of generated packet
Returns
SUCCESS if packet could be generated
INVALID_STATE if exchange type is currently not set
NOT_FOUND if no rules found for message generation
INVALID_STATE if aead not supplied but needed.
Definition at line 258 of file message.h.
Referenced by METHOD(), send_check(), send_notify(), and START_TEST().
host_t*(* message_t::get_destination)(message_t *this)
Gets the destination host informations.
Warning
Returned host_t object is not getting cloned, do not destroy nor modify.
Returns
host_t object representing destination host
Definition at line 342 of file message.h.
Referenced by add_nat_oa_payloads(), add_natd_payloads(), build_response(), drop_ike_sa_init(), merge_fragments(), METHOD(), process_payloads(), send_notify(), and send_notify_response().
exchange_type_t(* message_t::get_exchange_type)(message_t *this)
Gets the exchange type of the message.
Returns
exchange type of the message
Definition at line 133 of file message.h.
Referenced by build_payloads(), build_response(), calculate_wire_size(), get_init_hash(), get_message_id_or_hash(), handle_child_sa_failure(), METHOD(), parse_message(), process_payloads(), process_request(), process_response(), queue_message(), receive_packets(), send_notify(), and send_notify_response().
payload_type_t(* message_t::get_first_payload_type)(message_t *this)
Gets the payload type of the first payload.
Returns
payload type of the first payload
Definition at line 140 of file message.h.
Referenced by get_init_hash(), METHOD(), and parse_message().
enumerator_t*(* message_t::get_fragments)(message_t *this)
Returns internally stored packet_t* objects for each fragment.
Returns
enumerator internal packet_t* objects
Definition at line 405 of file message.h.
ike_sa_id_t*(* message_t::get_ike_sa_id)(message_t *this)
Gets the IKE_SA ID of the message.
The ike_sa_id points to the message internal id, do not modify.
Returns
ike_sa_id of message
Definition at line 119 of file message.h.
Referenced by METHOD(), process_payloads(), receive_packets(), and send_notify().
u_int64_t(* message_t::get_initiator_spi)(message_t *this)
Gets the initiator SPI of the message.
Returns
initiator spi of the message
Definition at line 94 of file message.h.
Referenced by cookie_build(), and get_init_hash().
u_int8_t(* message_t::get_major_version)(message_t *this)
Gets the IKE major version of the message.
Returns
major version of the message
Definition at line 59 of file message.h.
Referenced by drop_ike_sa_init(), get_message_id_or_hash(), message_create_defrag(), METHOD(), and receive_packets().
u_int32_t(* message_t::get_message_id)(message_t *this)
Gets the Message ID of the message.
Returns
message_id type of the message
Definition at line 87 of file message.h.
Referenced by add_radius_attribute(), build_response(), get_message_id_or_hash(), METHOD(), parse_message(), process_request(), send_auth_failed_informational(), and send_notify_response().
u_int8_t(* message_t::get_minor_version)(message_t *this)
Gets the IKE minor version of the message.
Returns
minor version of the message
Definition at line 73 of file message.h.
Referenced by receive_packets().
notify_payload_t*(* message_t::get_notify)(message_t *this, notify_type_t type)
Get the first notify payload of a specific type.
Parameters
type type of notification payload
Returns
notify payload, NULL if no such notify found
Definition at line 384 of file message.h.
Referenced by final_auth(), find_child(), METHOD(), process_dpd(), process_payloads(), and process_response().
packet_t*(* message_t::get_packet)(message_t *this)
Returns a clone of the internally stored packet_t object.
Returns
packet_t object as clone of internal one
Definition at line 391 of file message.h.
Referenced by collect_other_init_data(), METHOD(), and queue_message().
chunk_t(* message_t::get_packet_data)(message_t *this)
Returns a chunk pointing to internal packet_t data.
Returns
packet data.
Definition at line 398 of file message.h.
Referenced by check_cookie(), get_init_hash(), get_message_id_or_hash(), METHOD(), process_init_response(), and START_TEST().
payload_t*(* message_t::get_payload)(message_t *this, payload_type_t type)
Find a payload of a specific type.
Returns the first occurrence.
Parameters
type type of the payload to find
Returns
payload, or NULL if no such payload found
Definition at line 376 of file message.h.
Referenced by build_certreqs(), build_certs(), collect_my_init_data(), collect_other_init_data(), final_auth(), get_ke(), get_nonce(), handle_fragment(), message_create_defrag(), METHOD(), process_auth_request(), process_init_request(), rebuild_auth(), and verify_auth().
bool(* message_t::get_request)(message_t *this)
Gets request flag.
Returns
TRUE if message is a request, FALSE if it is a reply
Definition at line 154 of file message.h.
Referenced by METHOD(), parse_message(), rebuild_auth(), and receive_packets().
bool(* message_t::get_reserved_header_bit)(message_t *this, u_int nr)
Get a reserved bit in the IKE header.
Parameters
nr reserved bit to get in IKE header, 0-4
Returns
TRUE if bit is set
Definition at line 167 of file message.h.
u_int64_t(* message_t::get_responder_spi)(message_t *this)
Gets the responder SPI of the message.
Returns
responder spi of the message
Definition at line 101 of file message.h.
host_t*(* message_t::get_source)(message_t *this)
Gets the source host informations.
Warning
Returned host_t object is not getting cloned, do not destroy nor modify.
Returns
host_t object representing source host
Definition at line 322 of file message.h.
Referenced by add_nat_oa_payloads(), add_natd_payloads(), build_response(), cookie_build(), drop_ike_sa_init(), get_init_hash(), merge_fragments(), METHOD(), process_payloads(), send_notify(), and send_notify_response().
bool(* message_t::is_encoded)(message_t *this)
Check if the message has already been encoded using generate().
Returns
TRUE if message has been encoded
Definition at line 265 of file message.h.
Referenced by get_message_data(), and METHOD().
bool(* message_t::is_fragmented)(message_t *this)
Check if the message has been encoded and fragmented using fragment(), and whether there actually resulted fragments (if not is_encoded() will be TRUE).
The packets of individual fragments can be retrieved with get_fragments().
Returns
TRUE if message has been encoded and fragmented
Definition at line 294 of file message.h.
status_t(* message_t::parse_body)(message_t *this, keymat_t *keymat)
Parses body of message.
The body gets not only parsed, but rather it gets verified. All payloads are verified if they are allowed to exist in the message of this type and if their own structure is ok. If there are encrypted payloads, they get decrypted and verified using the given aead transform (if given).
Parameters
keymat keymat to verify/decrypt message
Returns
SUCCESS if parsing successful
PARSE_ERROR if message parsing failed
VERIFY_ERROR if message verification failed (bad syntax)
FAILED if integrity check failed
INVALID_STATE if aead not supplied, but needed
Definition at line 239 of file message.h.
Referenced by METHOD(), and parse_message().
status_t(* message_t::parse_header)(message_t *this)
Parses header of message.
Begins parsing of a message created via message_create_from_packet(). The parsing context is stored, so a subsequent call to parse_body() will continue the parsing process.
Returns
SUCCESS if header could be parsed
PARSE_ERROR if corrupted/invalid data found
FAILED if consistency check of header failed
Definition at line 220 of file message.h.
Referenced by METHOD(), and receive_packets().
void(* message_t::remove_payload_at)(message_t *this, enumerator_t *enumerator)
Remove the payload at the current enumerator position.
Parameters
enumerator enumerator created by create_payload_enumerator()
Definition at line 366 of file message.h.
Referenced by METHOD(), process_auth_response(), and rebuild_auth().
void(* message_t::set_destination)(message_t *this, host_t *host)
Sets the destination host informations.
Warning
host_t object is not getting cloned and gets destroyed by message_t.destroy or next call of message_t.set_destination.
Parameters
host host_t object representing destination host
Definition at line 352 of file message.h.
Referenced by build_response(), clone_message(), METHOD(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), and START_TEST().
void(* message_t::set_exchange_type)(message_t *this, exchange_type_t exchange_type)
Sets the exchange type of the message.
Parameters
exchange_type exchange_type to set
Definition at line 126 of file message.h.
Referenced by build_i_delete(), build_response(), clone_message(), create_fragment(), METHOD(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), and START_TEST().
void(* message_t::set_ike_sa_id)(message_t *this, ike_sa_id_t *ike_sa_id)
Sets the IKE_SA ID of the message.
ike_sa_id gets cloned.
Parameters
ike_sa_id ike_sa_id to set
Definition at line 110 of file message.h.
Referenced by clone_message(), METHOD(), send_check(), send_notify(), and START_TEST().
void(* message_t::set_major_version)(message_t *this, u_int8_t major_version)
Sets the IKE major version of the message.
Parameters
major_version major version to set
Definition at line 52 of file message.h.
Referenced by METHOD().
void(* message_t::set_message_id)(message_t *this, u_int32_t message_id)
Sets the Message ID of the message.
Parameters
message_id message_id to set
Definition at line 80 of file message.h.
Referenced by build_response(), clone_message(), create_fragment(), METHOD(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), and START_TEST().
void(* message_t::set_minor_version)(message_t *this, u_int8_t minor_version)
Sets the IKE minor version of the message.
Parameters
minor_version minor version to set
Definition at line 66 of file message.h.
Referenced by METHOD().
void(* message_t::set_request)(message_t *this, bool request)
Sets the request flag.
Parameters
request TRUE if message is a request, FALSE if it is a reply
Definition at line 147 of file message.h.
Referenced by build_response(), clone_message(), METHOD(), send_check(), send_notify(), and send_notify_response().
void(* message_t::set_reserved_header_bit)(message_t *this, u_int nr)
Set a reserved bit in the IKE header.
Parameters
nr reserved bit to set in IKE header, 0-4
Definition at line 174 of file message.h.
Referenced by set_bit().
void(* message_t::set_source)(message_t *this, host_t *host)
Sets the source host informations.
Warning
host_t object is not getting cloned and gets destroyed by message_t.destroy or next call of message_t.set_source.
Parameters
host host_t object representing source host
Definition at line 332 of file message.h.
Referenced by build_response(), clone_message(), METHOD(), send_auth_failed_informational(), send_check(), send_notify(), send_notify_response(), and START_TEST().
void(* message_t::set_version_flag)(message_t *this)
Set the version flag in the IKE header.
Definition at line 159 of file message.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
message.h