strongSwan: proposal.c File Reference
proposal.c File Reference
#include <string.h>
#include "proposal.h"
#include <daemon.h>
#include <collections/array.h>
#include <utils/identification.h>
#include <crypto/transform.h>
#include <crypto/prfs/prf.h>
#include <crypto/crypters/crypter.h>
#include <crypto/signers/signer.h>
Classes
struct private_proposal_t
struct entry_t
Typedefs
typedef struct private_proposal_t private_proposal_t
Functions
ENUM (protocol_id_names, PROTO_NONE, PROTO_IPCOMP,"PROTO_NONE","IKE","AH","ESP","IPCOMP",)
METHOD (proposal_t, add_algorithm, void, private_proposal_t *this, transform_type_t type, u_int16_t alg, u_int16_t key_size)
static bool alg_filter (uintptr_t type, entry_t **in, u_int16_t *alg, void **unused, u_int16_t *key_size)
METHOD (proposal_t, create_enumerator, enumerator_t *, private_proposal_t *this, transform_type_t type)
METHOD (proposal_t, get_algorithm, bool, private_proposal_t *this, transform_type_t type, u_int16_t *alg, u_int16_t *key_size)
METHOD (proposal_t, has_dh_group, bool, private_proposal_t *this, diffie_hellman_group_t group)
METHOD (proposal_t, strip_dh, void, private_proposal_t *this, diffie_hellman_group_t keep)
static bool select_algo (private_proposal_t *this, proposal_t *other, proposal_t *selected, transform_type_t type, bool priv)
METHOD (proposal_t, select_proposal, proposal_t *, private_proposal_t *this, proposal_t *other, bool private)
METHOD (proposal_t, get_protocol, protocol_id_t, private_proposal_t *this)
METHOD (proposal_t, set_spi, void, private_proposal_t *this, u_int64_t spi)
METHOD (proposal_t, get_spi, u_int64_t, private_proposal_t *this)
static bool algo_list_equals (private_proposal_t *this, proposal_t *other, transform_type_t type)
METHOD (proposal_t, get_number, u_int, private_proposal_t *this)
METHOD (proposal_t, equals, bool, private_proposal_t *this, proposal_t *other)
METHOD (proposal_t, clone_, proposal_t *, private_proposal_t *this)
static void check_proposal (private_proposal_t *this)
static bool add_string_algo (private_proposal_t *this, const char *alg)
static int print_alg (private_proposal_t *this, printf_hook_data_t *data, u_int kind, void *names, bool *first)
int proposal_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
METHOD (proposal_t, destroy, void, private_proposal_t *this)
proposal_t * proposal_create (protocol_id_t protocol, u_int number)
static bool proposal_add_supported_ike (private_proposal_t *this, bool aead)
proposal_t * proposal_create_default (protocol_id_t protocol)
proposal_t * proposal_create_default_aead (protocol_id_t protocol)
proposal_t * proposal_create_from_string (protocol_id_t protocol, const char *algs)
Variables
struct {
integrity_algorithm_t integ
pseudo_random_function_t prf
} integ_prf_map []
Typedef Documentation
typedef struct private_proposal_t private_proposal_t
Definition at line 38 of file proposal.c.
Function Documentation
static bool add_string_algo (private_proposal_t * this, const char * alg) static
add a algorithm identified by a string to the proposal.
Definition at line 494 of file proposal.c.
References proposal_token_t::algorithm, DBG1, DBG_CFG, FALSE, proposal_keywords_t::get_token, proposal_token_t::keysize, lib, library_t::proposal, TRUE, and proposal_token_t::type.
Referenced by proposal_create_from_string().
 {
     const proposal_token_t *token;
     token = lib->proposal->get_token(lib->proposal, alg);
     if (token == NULL)
     {
         DBG1(DBG_CFG, "algorithm '%s' not recognized", alg);
         return FALSE;
     }
     add_algorithm(this, token->type, token->algorithm, token->keysize);
     return TRUE;
 }
static bool alg_filter (uintptr_t type, entry_t ** in, u_int16_t * alg, void ** unused, u_int16_t * key_size) static
filter function for peer configs
Definition at line 99 of file proposal.c.
References entry_t::alg, FALSE, in, entry_t::key_size, TRUE, and entry_t::type.
Referenced by METHOD().
 {
     entry_t *entry = *in;
     if (entry->type != type)
     {
         return FALSE;
     }
     if (alg)
     {
         *alg = entry->alg;
     }
     if (key_size)
     {
         *key_size = entry->key_size;
     }
     return TRUE;
 }
static bool algo_list_equals (private_proposal_t * this, proposal_t * other, transform_type_t type) static
Check if two proposals have the same algorithms for a given transform type
Definition at line 317 of file proposal.c.
References proposal_t::create_enumerator, create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, equals(), FALSE, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *e1, *e2;
     u_int16_t alg1, alg2, ks1, ks2;
     bool equals = TRUE;
     e1 = create_enumerator(this, type);
     e2 = other->create_enumerator(other, type);
     while (e1->enumerate(e1, &alg1, &ks1))
     {
         if (!e2->enumerate(e2, &alg2, &ks2))
         {
             /* this has more algs */
             equals = FALSE;
             break;
         }
         if (alg1 != alg2 || ks1 != ks2)
         {
             equals = FALSE;
             break;
         }
     }
     if (e2->enumerate(e2, &alg2, &ks2))
     {
         /* other has more algs */
         equals = FALSE;
     }
     e1->destroy(e1);
     e2->destroy(e2);
     return equals;
 }
static void check_proposal (private_proposal_t * this) static
Checks the proposal read from a string.
Definition at line 416 of file proposal.c.
References alg, array_compress(), array_create_enumerator(), array_remove_at(), countof, create_enumerator(), enumerator_t::destroy, ENCRYPTION_ALGORITHM, encryption_algorithm_is_aead(), enumerator_t::enumerate, EXTENDED_SEQUENCE_NUMBERS, FALSE, integ, integ_prf_map, INTEGRITY_ALGORITHM, NO_EXT_SEQ_NUMBERS, prf, PROTO_AH, PROTO_ESP, PROTO_IKE, protocol, PSEUDO_RANDOM_FUNCTION, TRUE, and entry_t::type.
Referenced by proposal_create_from_string().
 {
     enumerator_t *e;
     entry_t *entry;
     u_int16_t alg, ks;
     bool all_aead = TRUE;
     int i;
     if (this->protocol == PROTO_IKE)
     {
         e = create_enumerator(this, PSEUDO_RANDOM_FUNCTION);
         if (!e->enumerate(e, &alg, &ks))
         {
             /* No explicit PRF found. We assume the same algorithm as used
              * for integrity checking */
             e->destroy(e);
             e = create_enumerator(this, INTEGRITY_ALGORITHM);
             while (e->enumerate(e, &alg, &ks))
             {
                 for (i = 0; i < countof(integ_prf_map); i++)
                 {
                     if (alg == integ_prf_map[i].integ)
                     {
                         add_algorithm(this, PSEUDO_RANDOM_FUNCTION,
                                       integ_prf_map[i].prf, 0);
                         break;
                     }
                 }
             }
         }
         e->destroy(e);
     }
     if (this->protocol == PROTO_ESP)
     {
         e = create_enumerator(this, ENCRYPTION_ALGORITHM);
         while (e->enumerate(e, &alg, &ks))
         {
             if (!encryption_algorithm_is_aead(alg))
             {
                 all_aead = FALSE;
                 break;
             }
         }
         e->destroy(e);
         if (all_aead)
         {
             /* if all encryption algorithms in the proposal are AEADs,
              * we MUST NOT propose any integrity algorithms */
             e = array_create_enumerator(this->transforms);
             while (e->enumerate(e, &entry))
             {
                 if (entry->type == INTEGRITY_ALGORITHM)
                 {
                     array_remove_at(this->transforms, e);
                 }
             }
             e->destroy(e);
         }
     }
     if (this->protocol == PROTO_AH || this->protocol == PROTO_ESP)
     {
         e = create_enumerator(this, EXTENDED_SEQUENCE_NUMBERS);
         if (!e->enumerate(e, NULL, NULL))
         {   /* ESN not specified, assume not supported */
             add_algorithm(this, EXTENDED_SEQUENCE_NUMBERS, NO_EXT_SEQ_NUMBERS, 0);
         }
         e->destroy(e);
     }
     array_compress(this->transforms);
 }
ENUM (protocol_id_names , PROTO_NONE , PROTO_IPCOMP , "PROTO_NONE" , "IKE" , "AH" , "ESP" , "IPCOMP")
METHOD (proposal_t , add_algorithm , void , private_proposal_t * this, transform_type_t type, u_int16_t alg, u_int16_t key_size)
Definition at line 83 of file proposal.c.
References alg, array_insert(), ARRAY_TAIL, key_size, type, and entry_t::type.
 {
     entry_t entry = {
         .type = type,
         .alg = alg,
         .key_size = key_size,
     };
     array_insert(this->transforms, ARRAY_TAIL, &entry);
 }
METHOD (proposal_t , create_enumerator , enumerator_t * , private_proposal_t * this, transform_type_t type)
Definition at line 119 of file proposal.c.
References alg_filter(), array_create_enumerator(), and enumerator_create_filter().
 {
     return enumerator_create_filter(
                         array_create_enumerator(this->transforms),
                         (void*)alg_filter, (void*)(uintptr_t)type, NULL);
 }
METHOD (proposal_t , get_algorithm , bool , private_proposal_t * this, transform_type_t type, u_int16_t * alg, u_int16_t * key_size)
Definition at line 127 of file proposal.c.
References create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, and TRUE.
 {
     enumerator_t *enumerator;
     bool found = FALSE;
     enumerator = create_enumerator(this, type);
     if (enumerator->enumerate(enumerator, alg, key_size))
     {
         found = TRUE;
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (proposal_t , has_dh_group , bool , private_proposal_t * this, diffie_hellman_group_t group)
Definition at line 144 of file proposal.c.
References create_enumerator(), enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, enumerator_t::enumerate, FALSE, found, MODP_NONE, and TRUE.
 {
     bool found = FALSE, any = FALSE;
     enumerator_t *enumerator;
     u_int16_t current;
     enumerator = create_enumerator(this, DIFFIE_HELLMAN_GROUP);
     while (enumerator->enumerate(enumerator, &current, NULL))
     {
         any = TRUE;
         if (current == group)
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!any && group == MODP_NONE)
     {
         found = TRUE;
     }
     return found;
 }
METHOD (proposal_t , strip_dh , void , private_proposal_t * this, diffie_hellman_group_t keep)
Definition at line 170 of file proposal.c.
References entry_t::alg, array_create_enumerator(), array_remove_at(), enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, enumerator_t::enumerate, and entry_t::type.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     enumerator = array_create_enumerator(this->transforms);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->type == DIFFIE_HELLMAN_GROUP &&
             entry->alg != keep)
         {
             array_remove_at(this->transforms, enumerator);
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (proposal_t , select_proposal , proposal_t * , private_proposal_t * this, proposal_t * other, bool private)
Definition at line 264 of file proposal.c.
References DBG2, DBG_CFG, proposal_t::destroy, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, EXTENDED_SEQUENCE_NUMBERS, proposal_t::get_number, proposal_t::get_protocol, proposal_t::get_spi, INTEGRITY_ALGORITHM, proposal_create(), protocol, PSEUDO_RANDOM_FUNCTION, select_algo(), and proposal_t::set_spi.
 {
     proposal_t *selected;
     DBG2(DBG_CFG, "selecting proposal:");
     if (this->protocol != other->get_protocol(other))
     {
         DBG2(DBG_CFG, "  protocol mismatch, skipping");
         return NULL;
     }
     selected = proposal_create(this->protocol, other->get_number(other));
     if (!select_algo(this, other, selected, ENCRYPTION_ALGORITHM, private) ||
         !select_algo(this, other, selected, PSEUDO_RANDOM_FUNCTION, private) ||
         !select_algo(this, other, selected, INTEGRITY_ALGORITHM, private) ||
         !select_algo(this, other, selected, DIFFIE_HELLMAN_GROUP, private) ||
         !select_algo(this, other, selected, EXTENDED_SEQUENCE_NUMBERS, private))
     {
         selected->destroy(selected);
         return NULL;
     }
     DBG2(DBG_CFG, "  proposal matches");
     selected->set_spi(selected, other->get_spi(other));
     return selected;
 }
METHOD (proposal_t , get_protocol , protocol_id_t , private_proposal_t * this)
Definition at line 296 of file proposal.c.
References protocol.
 {
     return this->protocol;
 }
METHOD (proposal_t , set_spi , void , private_proposal_t * this, u_int64_t spi)
Definition at line 302 of file proposal.c.
 {
     this->spi = spi;
 }
METHOD (proposal_t , get_spi , u_int64_t , private_proposal_t * this)
Definition at line 308 of file proposal.c.
 {
     return this->spi;
 }
METHOD (proposal_t , get_number , u_int , private_proposal_t * this)
Definition at line 351 of file proposal.c.
 {
     return this->number;
 }
METHOD (proposal_t , equals , bool , private_proposal_t * this, proposal_t * other)
Definition at line 357 of file proposal.c.
References algo_list_equals(), DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, EXTENDED_SEQUENCE_NUMBERS, INTEGRITY_ALGORITHM, PSEUDO_RANDOM_FUNCTION, and TRUE.
 {
     if (&this->public == other)
     {
         return TRUE;
     }
     return (
         algo_list_equals(this, other, ENCRYPTION_ALGORITHM) &&
         algo_list_equals(this, other, INTEGRITY_ALGORITHM) &&
         algo_list_equals(this, other, PSEUDO_RANDOM_FUNCTION) &&
         algo_list_equals(this, other, DIFFIE_HELLMAN_GROUP) &&
         algo_list_equals(this, other, EXTENDED_SEQUENCE_NUMBERS));
 }
METHOD (proposal_t , clone_ , proposal_t * , private_proposal_t * this)
Definition at line 372 of file proposal.c.
References array_create_enumerator(), array_insert(), ARRAY_TAIL, enumerator_t::destroy, enumerator_t::enumerate, private_proposal_t::number, proposal_create(), protocol, private_proposal_t::public, private_proposal_t::spi, and private_proposal_t::transforms.
 {
     private_proposal_t *clone;
     enumerator_t *enumerator;
     entry_t *entry;
     clone = (private_proposal_t*)proposal_create(this->protocol, 0);
     enumerator = array_create_enumerator(this->transforms);
     while (enumerator->enumerate(enumerator, &entry))
     {
         array_insert(clone->transforms, ARRAY_TAIL, entry);
     }
     enumerator->destroy(enumerator);
     clone->spi = this->spi;
     clone->number = this->number;
     return &clone->public;
 }
METHOD (proposal_t , destroy , void , private_proposal_t * this)
Definition at line 591 of file proposal.c.
References array_destroy(), and free().
 {
     array_destroy(this->transforms);
     free(this);
 }
static int print_alg (private_proposal_t * this, printf_hook_data_t * data, u_int kind, void * names, bool * first) static
print all algorithms of a kind to buffer
Definition at line 513 of file proposal.c.
References alg, create_enumerator(), enumerator_t::destroy, enumerator_t::enumerate, FALSE, print_in_hook(), and size.
Referenced by proposal_printf_hook().
 {
     enumerator_t *enumerator;
     size_t written = 0;
     u_int16_t alg, size;
     enumerator = create_enumerator(this, kind);
     while (enumerator->enumerate(enumerator, &alg, &size))
     {
         if (*first)
         {
             written += print_in_hook(data, "%N", names, alg);
             *first = FALSE;
         }
         else
         {
             written += print_in_hook(data, "/%N", names, alg);
         }
         if (size)
         {
             written += print_in_hook(data, "_%u", size);
         }
     }
     enumerator->destroy(enumerator);
     return written;
 }
static bool proposal_add_supported_ike (private_proposal_t * this, bool aead) static
Add supported IKE algorithms to proposal
Definition at line 632 of file proposal.c.
References array_count(), AUTH_AES_CMAC_96, AUTH_AES_XCBC_96, AUTH_HMAC_MD5_96, AUTH_HMAC_SHA1_96, AUTH_HMAC_SHA2_256_128, AUTH_HMAC_SHA2_384_192, AUTH_HMAC_SHA2_512_256, crypto_factory_t::create_aead_enumerator, crypto_factory_t::create_crypter_enumerator, crypto_factory_t::create_dh_enumerator, crypto_factory_t::create_prf_enumerator, crypto_factory_t::create_signer_enumerator, library_t::crypto, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, ECP_192_BIT, ECP_224_BIT, ECP_224_BP, ECP_256_BIT, ECP_256_BP, ECP_384_BIT, ECP_384_BP, ECP_512_BP, ECP_521_BIT, ENCR_3DES, ENCR_AES_CBC, ENCR_AES_CCM_ICV12, ENCR_AES_CCM_ICV16, ENCR_AES_CCM_ICV8, ENCR_AES_CTR, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, ENCR_CAMELLIA_CBC, ENCR_CAMELLIA_CCM_ICV12, ENCR_CAMELLIA_CCM_ICV16, ENCR_CAMELLIA_CCM_ICV8, ENCR_CAMELLIA_CTR, ENCR_DES, ENCRYPTION_ALGORITHM, enumerator_t::enumerate, FALSE, group, integrity, INTEGRITY_ALGORITHM, lib, MODP_1024_160, MODP_1024_BIT, MODP_1536_BIT, MODP_2048_224, MODP_2048_256, MODP_2048_BIT, MODP_3072_BIT, MODP_4096_BIT, MODP_768_BIT, MODP_8192_BIT, MODP_NULL, NTRU_112_BIT, NTRU_128_BIT, NTRU_192_BIT, NTRU_256_BIT, prf, PRF_AES128_CMAC, PRF_AES128_XCBC, PRF_HMAC_MD5, PRF_HMAC_SHA1, PRF_HMAC_SHA2_256, PRF_HMAC_SHA2_384, PRF_HMAC_SHA2_512, PSEUDO_RANDOM_FUNCTION, and TRUE.
Referenced by proposal_create_default(), and proposal_create_default_aead().
 {
     enumerator_t *enumerator;
     encryption_algorithm_t encryption;
     integrity_algorithm_t integrity;
     pseudo_random_function_t prf;
     diffie_hellman_group_t group;
     const char *plugin_name;
     if (aead)
     {
         enumerator = lib->crypto->create_aead_enumerator(lib->crypto);
         while (enumerator->enumerate(enumerator, &encryption, &plugin_name))
         {
             switch (encryption)
             {
                 case ENCR_AES_CCM_ICV8:
                 case ENCR_AES_CCM_ICV12:
                 case ENCR_AES_CCM_ICV16:
                 case ENCR_AES_GCM_ICV8:
                 case ENCR_AES_GCM_ICV12:
                 case ENCR_AES_GCM_ICV16:
                 case ENCR_CAMELLIA_CCM_ICV8:
                 case ENCR_CAMELLIA_CCM_ICV12:
                 case ENCR_CAMELLIA_CCM_ICV16:
                     /* we assume that we support all AES/Camellia sizes */
                     add_algorithm(this, ENCRYPTION_ALGORITHM, encryption, 128);
                     add_algorithm(this, ENCRYPTION_ALGORITHM, encryption, 192);
                     add_algorithm(this, ENCRYPTION_ALGORITHM, encryption, 256);
                     break;
                 default:
                     break;
             }
         }
         enumerator->destroy(enumerator);
         if (!array_count(this->transforms))
         {
             return FALSE;
         }
     }
     else
     {
         enumerator = lib->crypto->create_crypter_enumerator(lib->crypto);
         while (enumerator->enumerate(enumerator, &encryption, &plugin_name))
         {
             switch (encryption)
             {
                 case ENCR_AES_CBC:
                 case ENCR_AES_CTR:
                 case ENCR_CAMELLIA_CBC:
                 case ENCR_CAMELLIA_CTR:
                     /* we assume that we support all AES/Camellia sizes */
                     add_algorithm(this, ENCRYPTION_ALGORITHM, encryption, 128);
                     add_algorithm(this, ENCRYPTION_ALGORITHM, encryption, 192);
                     add_algorithm(this, ENCRYPTION_ALGORITHM, encryption, 256);
                     break;
                 case ENCR_3DES:
                     add_algorithm(this, ENCRYPTION_ALGORITHM, encryption, 0);
                     break;
                 case ENCR_DES:
                     /* no, thanks */
                     break;
                 default:
                     break;
             }
         }
         enumerator->destroy(enumerator);
         if (!array_count(this->transforms))
         {
             return FALSE;
         }
         enumerator = lib->crypto->create_signer_enumerator(lib->crypto);
         while (enumerator->enumerate(enumerator, &integrity, &plugin_name))
         {
             switch (integrity)
             {
                 case AUTH_HMAC_SHA1_96:
                 case AUTH_HMAC_SHA2_256_128:
                 case AUTH_HMAC_SHA2_384_192:
                 case AUTH_HMAC_SHA2_512_256:
                 case AUTH_HMAC_MD5_96:
                 case AUTH_AES_XCBC_96:
                 case AUTH_AES_CMAC_96:
                     add_algorithm(this, INTEGRITY_ALGORITHM, integrity, 0);
                     break;
                 default:
                     break;
             }
         }
         enumerator->destroy(enumerator);
     }
     enumerator = lib->crypto->create_prf_enumerator(lib->crypto);
     while (enumerator->enumerate(enumerator, &prf, &plugin_name))
     {
         switch (prf)
         {
             case PRF_HMAC_SHA1:
             case PRF_HMAC_SHA2_256:
             case PRF_HMAC_SHA2_384:
             case PRF_HMAC_SHA2_512:
             case PRF_HMAC_MD5:
             case PRF_AES128_XCBC:
             case PRF_AES128_CMAC:
                 add_algorithm(this, PSEUDO_RANDOM_FUNCTION, prf, 0);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     enumerator = lib->crypto->create_dh_enumerator(lib->crypto);
     while (enumerator->enumerate(enumerator, &group, &plugin_name))
     {
         switch (group)
         {
             case MODP_NULL:
                 /* only for testing purposes */
                 break;
             case MODP_768_BIT:
                 /* weak */
                 break;
             case MODP_1024_BIT:
             case MODP_1536_BIT:
             case MODP_2048_BIT:
             case MODP_3072_BIT:
             case MODP_4096_BIT:
             case MODP_8192_BIT:
             case ECP_256_BIT:
             case ECP_384_BIT:
             case ECP_521_BIT:
             case MODP_1024_160:
             case MODP_2048_224:
             case MODP_2048_256:
             case ECP_192_BIT:
             case ECP_224_BIT:
             case ECP_224_BP:
             case ECP_256_BP:
             case ECP_384_BP:
             case ECP_512_BP:
             case NTRU_112_BIT:
             case NTRU_128_BIT:
             case NTRU_192_BIT:
             case NTRU_256_BIT:
                 add_algorithm(this, DIFFIE_HELLMAN_GROUP, group, 0);
                 break;
             default:
                 break;
         }
     }
     enumerator->destroy(enumerator);
     return TRUE;
 }
static bool select_algo (private_proposal_t * this, proposal_t * other, proposal_t * selected, transform_type_t type, bool priv) static
Select a matching proposal from this and other, insert into selected.
Definition at line 191 of file proposal.c.
References proposal_t::add_algorithm, proposal_t::create_enumerator, create_enumerator(), DBG1, DBG2, DBG_CFG, enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, ENCRYPTION_ALGORITHM, encryption_algorithm_is_aead(), enumerator_t::enumerate, FALSE, found, proposal_t::get_algorithm, INTEGRITY_ALGORITHM, PROTO_AH, PROTO_ESP, protocol, transform_type_names, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *e1, *e2;
     u_int16_t alg1, alg2, ks1, ks2;
     bool found = FALSE, optional = FALSE;
     if (type == INTEGRITY_ALGORITHM &&
         selected->get_algorithm(selected, ENCRYPTION_ALGORITHM, &alg1, NULL) &&
         encryption_algorithm_is_aead(alg1))
     {
         /* no integrity algorithm required, we have an AEAD */
         return TRUE;
     }
     if (type == DIFFIE_HELLMAN_GROUP)
     {
         optional = this->protocol == PROTO_ESP || this->protocol == PROTO_AH;
     }
     e1 = create_enumerator(this, type);
     e2 = other->create_enumerator(other, type);
     if (!e1->enumerate(e1, NULL, NULL))
     {
         if (!e2->enumerate(e2, &alg2, NULL))
         {
             found = TRUE;
         }
         else if (optional)
         {
             do
             {   /* if the other peer proposes NONE, we accept the proposal */
                 found = !alg2;
             }
             while (!found && e2->enumerate(e2, &alg2, NULL));
         }
     }
     e1->destroy(e1);
     e1 = create_enumerator(this, type);
     /* compare algs, order of algs in "first" is preferred */
     while (!found && e1->enumerate(e1, &alg1, &ks1))
     {
         e2->destroy(e2);
         e2 = other->create_enumerator(other, type);
         while (e2->enumerate(e2, &alg2, &ks2))
         {
             if (alg1 == alg2 && ks1 == ks2)
             {
                 if (!priv && alg1 >= 1024)
                 {
                     /* accept private use algorithms only if requested */
                     DBG1(DBG_CFG, "an algorithm from private space would match, "
                          "but peer implementation is unknown, skipped");
                     continue;
                 }
                 /* ok, we have an algorithm */
                 selected->add_algorithm(selected, type, alg1, ks1);
                 found = TRUE;
                 break;
             }
         }
     }
     /* no match in all comparisons */
     e1->destroy(e1);
     e2->destroy(e2);
     if (!found)
     {
         DBG2(DBG_CFG, "  no acceptable %N found", transform_type_names, type);
     }
     return found;
 }
Variable Documentation
integrity_algorithm_t integ
Definition at line 398 of file proposal.c.
Referenced by check_proposal(), encr2integ(), install_sa(), process_child_add(), process_ike_add(), and verify_mac().
const { ... } integ_prf_map[]
Initial value:
= {
    {AUTH_HMAC_SHA1_96,                 PRF_HMAC_SHA1                   },
    {AUTH_HMAC_SHA1_160,                PRF_HMAC_SHA1                   },
    {AUTH_HMAC_SHA2_256_128,            PRF_HMAC_SHA2_256               },
    {AUTH_HMAC_SHA2_384_192,            PRF_HMAC_SHA2_384               },
    {AUTH_HMAC_SHA2_512_256,            PRF_HMAC_SHA2_512               },
    {AUTH_HMAC_MD5_96,                  PRF_HMAC_MD5                    },
    {AUTH_HMAC_MD5_128,                 PRF_HMAC_MD5                    },
    {AUTH_AES_XCBC_96,                  PRF_AES128_XCBC                 },
    {AUTH_CAMELLIA_XCBC_96,             PRF_CAMELLIA128_XCBC            },
    {AUTH_AES_CMAC_96,                  PRF_AES128_CMAC                 },
}
Map integrity algorithms to the PRF functions using the same algorithm.
Referenced by check_proposal().
pseudo_random_function_t prf
Definition at line 399 of file proposal.c.
Referenced by bench_prf(), check_proposal(), create_aead(), create_ciphers(), derive_master(), eap_aka_3gpp2_functions_create(), ensure_crypto_primitives(), expand_keys(), filter_unsupported_suites(), list_algs(), METHOD(), pbkdf2(), prf_plus_create(), process_ike_add(), proposal_add_supported_ike(), simaka_crypto_create(), and START_TEST().