strongSwan: imv_swid_state_t Struct Reference
imv_swid_state_t Struct Reference
imv_swid_state
#include "imv_swid_state.h"
Public Attributes
imv_state_t interface
void(* set_handshake_state)(imv_swid_state_t *this, imv_swid_handshake_state_t new_state)
imv_swid_handshake_state_t(* get_handshake_state)(imv_swid_state_t *this)
void(* set_request_id)(imv_swid_state_t *this, uint32_t request_id)
uint32_t(* get_request_id)(imv_swid_state_t *this)
void(* set_swid_inventory)(imv_swid_state_t *this, swid_inventory_t *inventory)
json_object *(* get_swid_inventory)(imv_swid_state_t *this)
void(* set_missing)(imv_swid_state_t *this, uint32_t count)
uint32_t(* get_missing)(imv_swid_state_t *this)
void(* set_count)(imv_swid_state_t *this, int tag_id_count, int tag_count)
void(* get_count)(imv_swid_state_t *this, int *tag_id_count, int *tag_count)
Detailed Description
Internal state of an imv_swid_t connection instance
Definition at line 48 of file imv_swid_state.h.
Member Data Documentation
void(* imv_swid_state_t::get_count)(imv_swid_state_t *this, int *tag_id_count, int *tag_count)
Set [or with multiple attributes increment] SWID Tag [ID] counters
Parameters
tag_id_count Number of received SWID Tag IDs
tag_count Number of received SWID Tags
Definition at line 126 of file imv_swid_state.h.
Referenced by METHOD().
imv_swid_handshake_state_t(* imv_swid_state_t::get_handshake_state)(imv_swid_state_t *this)
Get state of the handshake
Returns
the handshake state of IMV
Definition at line 68 of file imv_swid_state.h.
Referenced by METHOD().
uint32_t(* imv_swid_state_t::get_missing)(imv_swid_state_t *this)
Get the number of still missing SWID Tags or Tag IDs
Returns
Number of missing SWID Tags or Tag IDs
Definition at line 110 of file imv_swid_state.h.
Referenced by METHOD().
uint32_t(* imv_swid_state_t::get_request_id)(imv_swid_state_t *this)
Get the SWID request ID
Returns
SWID request ID
Definition at line 82 of file imv_swid_state.h.
Referenced by METHOD(), and receive_msg().
json_object*(* imv_swid_state_t::get_swid_inventory)(imv_swid_state_t *this)
Get the encoding of the complete SWID Tag ID inventory
Returns
SWID Tags ID inventory as a JSON array
Definition at line 96 of file imv_swid_state.h.
Referenced by METHOD().
imv_state_t imv_swid_state_t::interface
imv_state_t interface
Definition at line 53 of file imv_swid_state.h.
void(* imv_swid_state_t::set_count)(imv_swid_state_t *this, int tag_id_count, int tag_count)
Set [or with multiple attributes increment] SWID Tag [ID] counters
Parameters
tag_id_count Number of received SWID Tag IDs
tag_count Number of received SWID Tags
Definition at line 118 of file imv_swid_state.h.
Referenced by receive_msg().
void(* imv_swid_state_t::set_handshake_state)(imv_swid_state_t *this, imv_swid_handshake_state_t new_state)
Set state of the handshake
Parameters
new_state the handshake state of IMV
Definition at line 60 of file imv_swid_state.h.
Referenced by METHOD().
void(* imv_swid_state_t::set_missing)(imv_swid_state_t *this, uint32_t count)
Set the number of still missing SWID Tags or Tag IDs
Parameters
count Number of missing SWID Tags or Tag IDs
Definition at line 103 of file imv_swid_state.h.
Referenced by METHOD(), and receive_msg().
void(* imv_swid_state_t::set_request_id)(imv_swid_state_t *this, uint32_t request_id)
Set the SWID request ID
Parameters
request_id SWID request ID to be set
Definition at line 75 of file imv_swid_state.h.
Referenced by METHOD().
void(* imv_swid_state_t::set_swid_inventory)(imv_swid_state_t *this, swid_inventory_t *inventory)
Set or extend the SWID Tag ID inventory in the state
Parameters
inventory SWID Tags ID inventory to be added
Definition at line 89 of file imv_swid_state.h.
Referenced by receive_msg().
The documentation for this struct was generated from the following file:
imv_swid_state.h