strongSwan: aesni_gcm
aesni_gcm
aesni
Classes
struct aesni_gcm_t
Typedefs
typedef struct aesni_gcm_t aesni_gcm_t
Functions
aesni_gcm_t * aesni_gcm_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Detailed Description
Typedef Documentation
typedef struct aesni_gcm_t aesni_gcm_t
Definition at line 26 of file aesni_gcm.h.
Function Documentation
aesni_gcm_t* aesni_gcm_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Create a aesni_gcm instance.
Parameters
algo encryption algorithm, ENCR_AES_GCM*
key_size AES key size, in bytes
salt_size size of salt value
Returns
AES-GCM AEAD, NULL if not supported
See header
Definition at line 1370 of file aesni_gcm.c.
References decrypt, decrypt_gcm128(), decrypt_gcm192(), decrypt_gcm256(), ENCR_AES_CBC, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, encrypt(), encrypt_gcm128(), encrypt_gcm192(), encrypt_gcm256(), INIT_ALIGN, iv_gen_seq_create(), key_size, and SALT_SIZE.
Referenced by METHOD().
 {
     private_aesni_gcm_t *this;
     size_t icv_size;
     switch (key_size)
     {
         case 0:
             key_size = 16;
             break;
         case 16:
         case 24:
         case 32:
             break;
         default:
             return NULL;
     }
     if (salt_size && salt_size != SALT_SIZE)
     {
         /* currently not supported */
         return NULL;
     }
     switch (algo)
     {
         case ENCR_AES_GCM_ICV8:
             algo = ENCR_AES_CBC;
             icv_size = 8;
             break;
         case ENCR_AES_GCM_ICV12:
             algo = ENCR_AES_CBC;
             icv_size = 12;
             break;
         case ENCR_AES_GCM_ICV16:
             algo = ENCR_AES_CBC;
             icv_size = 16;
             break;
         default:
             return NULL;
     }
     INIT_ALIGN(this, sizeof(__m128i),
         .public = {
             .aead = {
                 .encrypt = _encrypt,
                 .decrypt = _decrypt,
                 .get_block_size = _get_block_size,
                 .get_icv_size = _get_icv_size,
                 .get_iv_size = _get_iv_size,
                 .get_iv_gen = _get_iv_gen,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .key_size = key_size,
         .iv_gen = iv_gen_seq_create(),
         .icv_size = icv_size,
     );
     switch (key_size)
     {
         case 16:
             this->encrypt = encrypt_gcm128;
             this->decrypt = decrypt_gcm128;
             break;
         case 24:
             this->encrypt = encrypt_gcm192;
             this->decrypt = decrypt_gcm192;
             break;
         case 32:
             this->encrypt = encrypt_gcm256;
             this->decrypt = decrypt_gcm256;
             break;
     }
     return &this->public;
 }