strongSwan: error_notify_socket
error_notify_socket
error_notify
Classes
struct error_notify_socket_t
Typedefs
typedef struct
error_notify_socket_t error_notify_socket_t
Functions
error_notify_socket_t * error_notify_socket_create ()
Detailed Description
Typedef Documentation
typedef struct error_notify_socket_t error_notify_socket_t
Definition at line 24 of file error_notify_socket.h.
Function Documentation
error_notify_socket_t* error_notify_socket_create ()
Create a error_notify_socket instance.
See header
Definition at line 128 of file error_notify_socket.c.
References stream_manager_t::create_service, DBG1, DBG_CFG, destroy(), ERROR_NOTIFY_SOCKET, settings_t::get_str, INIT, JOB_PRIO_CRITICAL, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, on_accept(), library_t::settings, library_t::streams, and uri.
Referenced by error_notify_plugin_create().
 {
     private_error_notify_socket_t *this;
     char *uri;
     INIT(this,
         .public = {
             .notify = _notify,
             .has_listeners = _has_listeners,
             .destroy = _destroy,
         },
         .connected = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     uri = lib->settings->get_str(lib->settings,
                 "%s.plugins.error-notify.socket", "unix://" ERROR_NOTIFY_SOCKET,
                 lib->ns);
     this->service = lib->streams->create_service(lib->streams, uri, 10);
     if (!this->service)
     {
         DBG1(DBG_CFG, "creating duplicheck socket failed");
         destroy(this);
         return NULL;
     }
     this->service->on_accept(this->service, (stream_service_cb_t)on_accept,
                              this, JOB_PRIO_CRITICAL, 1);
     return &this->public;
 }