strongSwan: controller_t Struct Reference
controller_t Struct Reference
controller
#include "controller.h"
Public Attributes
enumerator_t *(* create_ike_sa_enumerator)(controller_t *this, bool wait)
status_t(* initiate)(controller_t *this, peer_cfg_t *peer_cfg, child_cfg_t *child_cfg, controller_cb_t callback, void *param, u_int timeout, bool limits)
status_t(* terminate_ike)(controller_t *this, u_int32_t unique_id, controller_cb_t callback, void *param, u_int timeout)
status_t(* terminate_child)(controller_t *this, u_int32_t unique_id, controller_cb_t callback, void *param, u_int timeout)
void(* destroy)(controller_t *this)
Detailed Description
The controller provides a simple interface to run actions.
The controller starts actions by creating jobs. It then tries to evaluate the result of the operation by listening on the bus.
Passing NULL as callback to the managers function calls them asynchronously. If a callback is specified, they are called synchronously. There is a default callback "controller_cb_empty" if you want to call a function synchronously, but don't need a callback.
Definition at line 61 of file controller.h.
Member Data Documentation
enumerator_t*(* controller_t::create_ike_sa_enumerator)(controller_t *this, bool wait)
Create an enumerator for all IKE_SAs.
The enumerator blocks the IKE_SA manager until it gets destroyed. Do not call another interface/manager method while the enumerator is alive.
Parameters
wait TRUE to wait for checked out SAs, FALSE to skip
Returns
enumerator, locks IKE_SA manager until destroyed
Definition at line 72 of file controller.h.
Referenced by CALLBACK(), clear_start_action(), close_child(), close_ike(), disconnect(), find_reqid(), liveness(), METHOD(), rekey_child(), rekey_ike(), reload_metadata(), request_control_terminate(), request_query_ikesa(), status(), and terminate().
void(* controller_t::destroy)(controller_t *this)
Destroy a controller_t instance.
Definition at line 141 of file controller.h.
status_t(* controller_t::initiate)(controller_t *this, peer_cfg_t *peer_cfg, child_cfg_t *child_cfg, controller_cb_t callback, void *param, u_int timeout, bool limits)
Initiate a CHILD_SA, and if required, an IKE_SA.
If a callback is provided the function is synchronous and thus blocks until the IKE_SA is established or failed.
Parameters
peer_cfg peer_cfg to use for IKE_SA setup
child_cfg child_cfg to set up CHILD_SA from
cb logging callback
param parameter to include in each call of cb
timeout timeout in ms to wait for callbacks, 0 to disable
limits whether to check limits regarding IKE_SA initiation
Returns
SUCCESS, if CHILD_SA established
FAILED, if setup failed
NEED_MORE, if callback returned FALSE
OUT_OF_RES if timed out
INVALID_STATE if limits prevented initiation
Definition at line 93 of file controller.h.
Referenced by CALLBACK(), charon_initiate(), do_load_test(), initiate(), initiate_config(), METHOD(), on_accept(), request_control_initiate(), and run_start_action().
status_t(* controller_t::terminate_child)(controller_t *this, u_int32_t unique_id, controller_cb_t callback, void *param, u_int timeout)
Terminate a CHILD_SA.
If a callback is provided the function is synchronous and thus blocks until the CHILD_SA is properly deleted, or the call timed out.
Parameters
unique_id CHILD_SA unique ID to terminate
cb logging callback
param parameter to include in each call of cb
timeout timeout in ms to wait for callbacks, 0 to disable
Returns
SUCCESS, if CHILD_SA terminated
NOT_FOUND, if no such CHILD_SA found
NEED_MORE, if callback returned FALSE
OUT_OF_RES if timed out
Definition at line 134 of file controller.h.
Referenced by CALLBACK(), charon_terminate(), clear_start_action(), close_child(), and request_control_terminate().
status_t(* controller_t::terminate_ike)(controller_t *this, u_int32_t unique_id, controller_cb_t callback, void *param, u_int timeout)
Terminate an IKE_SA and all of its CHILD_SAs.
If a callback is provided the function is synchronous and thus blocks until the IKE_SA is properly deleted, or the call timed out.
Parameters
unique_id unique id of the IKE_SA to terminate.
cb logging callback
param parameter to include in each call of cb
timeout timeout in ms to wait for callbacks, 0 to disable
Returns
SUCCESS, if CHILD_SA terminated
NOT_FOUND, if no such CHILD_SA found
NEED_MORE, if callback returned FALSE
OUT_OF_RES if timed out
Definition at line 114 of file controller.h.
Referenced by CALLBACK(), charon_terminate(), close_ike(), disconnect(), request_control_terminate(), and terminate().
The documentation for this struct was generated from the following file:
controller.h