strongSwan: pkcs7_encrypted_data.c File Reference
pkcs7_encrypted_data.c File Reference
#include "pkcs7_encrypted_data.h"
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <asn1/oid.h>
#include <crypto/pkcs5.h>
#include <utils/debug.h>
Classes
struct private_pkcs7_encrypted_data_t
Macros
#define PKCS7_VERSION 1
#define PKCS7_CONTENT_TYPE 3
#define PKCS7_CONTENT_ENC_ALGORITHM 4
#define PKCS7_ENCRYPTED_CONTENT 5
Typedefs
typedef struct
private_pkcs7_encrypted_data_t private_pkcs7_encrypted_data_t
Functions
static bool decrypt (pkcs5_t *pkcs5, chunk_t data, chunk_t *decrypted)
static bool parse (private_pkcs7_encrypted_data_t *this, chunk_t content)
METHOD (container_t, get_type, container_type_t, private_pkcs7_encrypted_data_t *this)
METHOD (container_t, get_data, bool, private_pkcs7_encrypted_data_t *this, chunk_t *data)
METHOD (container_t, get_encoding, bool, private_pkcs7_encrypted_data_t *this, chunk_t *data)
METHOD (container_t, destroy, void, private_pkcs7_encrypted_data_t *this)
static
private_pkcs7_encrypted_data_t * create_empty ()
pkcs7_t * pkcs7_encrypted_data_load (chunk_t encoding, chunk_t content)
Variables
static const asn1Object_t encryptedDataObjects []
Macro Definition Documentation
#define PKCS7_CONTENT_ENC_ALGORITHM 4
Definition at line 84 of file pkcs7_encrypted_data.c.
Referenced by parse().
#define PKCS7_CONTENT_TYPE 3
Definition at line 83 of file pkcs7_encrypted_data.c.
Referenced by parse().
#define PKCS7_ENCRYPTED_CONTENT 5
Definition at line 85 of file pkcs7_encrypted_data.c.
Referenced by parse().
#define PKCS7_VERSION 1
Definition at line 82 of file pkcs7_encrypted_data.c.
Referenced by parse().
Typedef Documentation
typedef struct private_pkcs7_encrypted_data_t private_pkcs7_encrypted_data_t
Definition at line 24 of file pkcs7_encrypted_data.c.
Function Documentation
static private_pkcs7_encrypted_data_t* create_empty (void) static
Generic constructor
Definition at line 180 of file pkcs7_encrypted_data.c.
References destroy(), enumerator_create_empty(), INIT, and return_false().
Referenced by pkcs7_encrypted_data_load().
 {
     private_pkcs7_encrypted_data_t *this;
     INIT(this,
         .public = {
             .container = {
                 .get_type = _get_type,
                 .create_signature_enumerator = (void*)enumerator_create_empty,
                 .get_data = _get_data,
                 .get_encoding = _get_encoding,
                 .destroy = _destroy,
             },
             .create_cert_enumerator = (void*)enumerator_create_empty,
             .get_attribute = (void*)return_false,
         },
     );
     return this;
 }
static bool decrypt (pkcs5_t * pkcs5, chunk_t data, chunk_t * decrypted) static
Decrypt encrypted-data with available passwords
Definition at line 50 of file pkcs7_encrypted_data.c.
References credential_manager_t::create_shared_enumerator, library_t::credmgr, data, pkcs5_t::decrypt, enumerator_t::destroy, enumerator_t::enumerate, FALSE, shared_key_t::get_key, lib, SHARED_PRIVATE_KEY_PASS, and TRUE.
Referenced by parse().
 {
     enumerator_t *enumerator;
     shared_key_t *shared;
     bool success = FALSE;
     enumerator = lib->credmgr->create_shared_enumerator(lib->credmgr,
                                         SHARED_PRIVATE_KEY_PASS, NULL, NULL);
     while (enumerator->enumerate(enumerator, &shared, NULL, NULL))
     {
         if (pkcs5->decrypt(pkcs5, shared->get_key(shared), data, decrypted))
         {
             success = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return success;
 }
METHOD (container_t , get_type , container_type_t , private_pkcs7_encrypted_data_t * this)
Definition at line 145 of file pkcs7_encrypted_data.c.
References CONTAINER_PKCS7_ENCRYPTED_DATA.
 {
     return CONTAINER_PKCS7_ENCRYPTED_DATA;
 }
METHOD (container_t , get_data , bool , private_pkcs7_encrypted_data_t * this, chunk_t * data)
Definition at line 151 of file pkcs7_encrypted_data.c.
References chunk_clone, FALSE, and TRUE.
 {
     if (this->content.len)
     {
         *data = chunk_clone(this->content);
         return TRUE;
     }
     return FALSE;
 }
METHOD (container_t , get_encoding , bool , private_pkcs7_encrypted_data_t * this, chunk_t * data)
Definition at line 162 of file pkcs7_encrypted_data.c.
References chunk_clone, encoding, and TRUE.
 {
     *data = chunk_clone(this->encoding);
     return TRUE;
 }
METHOD (container_t , destroy , void , private_pkcs7_encrypted_data_t * this)
Definition at line 169 of file pkcs7_encrypted_data.c.
References encoding, and free().
 {
     free(this->content.ptr);
     free(this->encoding.ptr);
     free(this);
 }
static bool parse (private_pkcs7_encrypted_data_t * this, chunk_t content) static
Parse and decrypt encrypted-data
Definition at line 90 of file pkcs7_encrypted_data.c.
References asn1_known_oid(), asn1_parser_create(), chunk_empty, DBG1, DBG2, DBG_LIB, decrypt(), asn1_parser_t::destroy, DESTROY_IF, end, FALSE, asn1_parser_t::get_level, asn1_parser_t::iterate, OID_PKCS7_DATA, parser, pkcs5_from_algorithmIdentifier(), PKCS7_CONTENT_ENC_ALGORITHM, PKCS7_CONTENT_TYPE, PKCS7_ENCRYPTED_CONTENT, PKCS7_VERSION, asn1_parser_t::success, and version.
Referenced by pkcs7_encrypted_data_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID, version;
     bool success = FALSE;
     chunk_t encrypted = chunk_empty;
     pkcs5_t *pkcs5 = NULL;
     parser = asn1_parser_create(encryptedDataObjects, content);
     while (parser->iterate(parser, &objectID, &object))
     {
         int level = parser->get_level(parser);
         switch (objectID)
         {
             case PKCS7_VERSION:
                 version = object.len ? (int)*object.ptr : 0;
                 DBG2(DBG_LIB, "  v%d", version);
                 if (version != 0)
                 {
                     DBG1(DBG_LIB, "encryptedData version is not 0");
                     goto end;
                 }
                 break;
             case PKCS7_CONTENT_TYPE:
                 if (asn1_known_oid(object) != OID_PKCS7_DATA)
                 {
                     DBG1(DBG_LIB, "encrypted content not of type pkcs7 data");
                     goto end;
                 }
                 break;
             case PKCS7_CONTENT_ENC_ALGORITHM:
                 pkcs5 = pkcs5_from_algorithmIdentifier(object, level + 1);
                 if (!pkcs5)
                 {
                     DBG1(DBG_LIB, "failed to detect PKCS#5 scheme");
                     goto end;
                 }
                 break;
             case PKCS7_ENCRYPTED_CONTENT:
                 encrypted = object;
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     success = success && decrypt(pkcs5, encrypted, &this->content);
     DESTROY_IF(pkcs5);
     return success;
 }
Variable Documentation
const asn1Object_t encryptedDataObjects[] static
Initial value:
= {
    { 0, "encryptedData",                   ASN1_SEQUENCE,      ASN1_NONE },
    { 1,   "version",                       ASN1_INTEGER,       ASN1_BODY },
    { 1,   "encryptedContentInfo",          ASN1_SEQUENCE,      ASN1_OBJ  },
    { 2,     "contentType",                 ASN1_OID,           ASN1_BODY },
    { 2,     "contentEncryptionAlgorithm",  ASN1_EOC,           ASN1_RAW  },
    { 2,     "encryptedContent",            ASN1_CONTEXT_S_0,   ASN1_BODY },
    { 0, "exit",                            ASN1_EOC,           ASN1_EXIT }
}
ASN.1 definition of the PKCS#7 encrypted-data type
Definition at line 73 of file pkcs7_encrypted_data.c.