strongSwan: transform_substructure
transform_substructure
payloads
Classes
struct transform_substructure_t
Macros
#define TRANSFORM_TYPE_VALUE 3
Typedefs
typedef struct
transform_substructure_t transform_substructure_t
Functions
transform_substructure_t * transform_substructure_create (payload_type_t type)
transform_substructure_t * transform_substructure_create_type (payload_type_t type, u_int8_t type_or_number, u_int16_t id)
Detailed Description
Macro Definition Documentation
#define TRANSFORM_TYPE_VALUE 3
IKEv1 Value for a transform payload.
Definition at line 40 of file transform_substructure.h.
Referenced by METHOD().
Typedef Documentation
typedef struct transform_substructure_t transform_substructure_t
Definition at line 25 of file transform_substructure.h.
Function Documentation
transform_substructure_t* transform_substructure_create (payload_type_t type)
Creates an empty transform_substructure_t object.
Parameters
type PLV2_TRANSFORM_SUBSTRUCTURE or PLV1_TRANSFORM_SUBSTRUCTURE
Returns
created transform_substructure_t object
Definition at line 271 of file transform_substructure.c.
References INIT, linked_list_create(), PL_NONE, and type.
Referenced by payload_create(), and transform_substructure_create_type().
 {
     private_transform_substructure_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .add_transform_attribute = _add_transform_attribute,
             .set_is_last_transform = _set_is_last_transform,
             .get_transform_type_or_number = _get_transform_type_or_number,
             .get_transform_id = _get_transform_id,
             .create_attribute_enumerator = _create_attribute_enumerator,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .transform_length = get_header_length(this),
         .attributes = linked_list_create(),
         .type = type,
     );
     return &this->public;
 }
transform_substructure_t* transform_substructure_create_type (payload_type_t type, u_int8_t type_or_number, u_int16_t id)
Creates an empty transform_substructure_t object.
Parameters
type PLV2_TRANSFORM_SUBSTRUCTURE or PLV1_TRANSFORM_SUBSTRUCTURE
type_or_number Type (IKEv2) or number (IKEv1) of transform
id transform id specifc for the transform type
Returns
transform_substructure_t object
Definition at line 305 of file transform_substructure.c.
References id, PLV2_TRANSFORM_SUBSTRUCTURE, and transform_substructure_create().
Referenced by proposal_substructure_create_for_ipcomp_v1(), set_from_proposal_v1(), set_from_proposal_v1_ike(), and set_from_proposal_v2().
 {
     private_transform_substructure_t *this;
     this = (private_transform_substructure_t*)transform_substructure_create(type);
     this->transform_ton = type_or_number;
     if (type == PLV2_TRANSFORM_SUBSTRUCTURE)
     {
         this->transform_id_v2 = id;
     }
     else
     {
         this->transform_id_v1 = id;
     }
     return &this->public;
 }