strongSwan: openssl_x509
openssl_x509
openssl
Classes
struct openssl_x509_t
Typedefs
typedef struct openssl_x509_t openssl_x509_t
Functions
openssl_x509_t * openssl_x509_load (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct openssl_x509_t openssl_x509_t
Definition at line 26 of file openssl_x509.h.
Function Documentation
openssl_x509_t* openssl_x509_load (certificate_type_t type, va_list args)
Load a X.509 certificate.
This function takes a BUILD_BLOB_ASN1_DER.
Parameters
type certificate type, CERT_X509 only
args builder_part_t argument list
Returns
X.509 certificate, NULL on failure
Definition at line 1118 of file openssl_x509.c.
References blob, BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_X509_FLAG, chunk_clone, chunk_empty, create_empty(), DBG1, DBG_LIB, destroy(), encoding, flags, parse_certificate(), chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     chunk_t blob = chunk_empty;
     x509_flag_t flags = 0;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_X509_FLAG:
                 flags |= va_arg(args, x509_flag_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.ptr)
     {
         private_openssl_x509_t *this;
         this = create_empty();
         this->encoding = chunk_clone(blob);
         this->flags |= flags;
         if (parse_certificate(this))
         {
             return &this->public;
         }
         DBG1(DBG_LIB, "OpenSSL X.509 parsing failed");
         destroy(this);
     }
     return NULL;
 }