strongSwan: isakmp_cert_post.c File Reference
isakmp_cert_post.c File Reference
#include "isakmp_cert_post.h"
#include <daemon.h>
#include <sa/ike_sa.h>
#include <encoding/payloads/cert_payload.h>
#include <encoding/payloads/certreq_payload.h>
#include <encoding/payloads/auth_payload.h>
#include <encoding/payloads/sa_payload.h>
#include <credentials/certificates/x509.h>
Classes
struct private_isakmp_cert_post_t
Typedefs
typedef struct
private_isakmp_cert_post_t private_isakmp_cert_post_t
Functions
static bool use_certs (private_isakmp_cert_post_t *this, message_t *message)
static void build_certs (private_isakmp_cert_post_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_isakmp_cert_post_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_isakmp_cert_post_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_isakmp_cert_post_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_isakmp_cert_post_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_isakmp_cert_post_t *this)
METHOD (task_t, migrate, void, private_isakmp_cert_post_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_isakmp_cert_post_t *this)
isakmp_cert_post_t * isakmp_cert_post_create (ike_sa_t *ike_sa, bool initiator)
Typedef Documentation
typedef struct private_isakmp_cert_post_t private_isakmp_cert_post_t
Definition at line 27 of file isakmp_cert_post.c.
Function Documentation
static void build_certs (private_isakmp_cert_post_t * this, message_t * message) static
Add certificates to message
Definition at line 101 of file isakmp_cert_post.c.
References message_t::add_payload, AUTH_RULE_IM_CERT, AUTH_RULE_SUBJECT_CERT, cert, CERT_ALWAYS_SEND, CERT_NEVER_SEND, cert_payload_create_from_cert(), CERT_SEND_IF_ASKED, COND_CERTREQ_SEEN, auth_cfg_t::create_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, auth_cfg_t::get, peer_cfg_t::get_cert_policy, certificate_t::get_subject, PLV1_CERTIFICATE, TRUE, and type.
Referenced by METHOD().
 {
     peer_cfg_t *peer_cfg;
     peer_cfg = this->ike_sa->get_peer_cfg(this->ike_sa);
     if (!peer_cfg)
     {
         return;
     }
     switch (peer_cfg->get_cert_policy(peer_cfg))
     {
         case CERT_NEVER_SEND:
             break;
         case CERT_SEND_IF_ASKED:
             if (!this->ike_sa->has_condition(this->ike_sa, COND_CERTREQ_SEEN))
             {
                 break;
             }
             /* FALL */
         case CERT_ALWAYS_SEND:
         {
             cert_payload_t *payload;
             enumerator_t *enumerator;
             certificate_t *cert;
             auth_rule_t type;
             auth_cfg_t *auth;
             auth = this->ike_sa->get_auth_cfg(this->ike_sa, TRUE);
             cert = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
             if (!cert)
             {
                 break;
             }
             payload = cert_payload_create_from_cert(PLV1_CERTIFICATE, cert);
             if (!payload)
             {
                 break;
             }
             DBG1(DBG_IKE, "sending end entity cert \"%Y\"",
                  cert->get_subject(cert));
             message->add_payload(message, (payload_t*)payload);
             enumerator = auth->create_enumerator(auth);
             while (enumerator->enumerate(enumerator, &type, &cert))
             {
                 if (type == AUTH_RULE_IM_CERT)
                 {
                     payload = cert_payload_create_from_cert(PLV1_CERTIFICATE, cert);
                     if (payload)
                     {
                         DBG1(DBG_IKE, "sending issuer cert \"%Y\"",
                              cert->get_subject(cert));
                         message->add_payload(message, (payload_t*)payload);
                     }
                 }
             }
             enumerator->destroy(enumerator);
         }
     }
 }
METHOD (task_t , build_i , status_t , private_isakmp_cert_post_t * this, message_t * message)
Definition at line 163 of file isakmp_cert_post.c.
References AGGRESSIVE, build_certs(), FAILED, message_t::get_exchange_type, ID_PROT, NEED_MORE, and SUCCESS.
 {
     switch (message->get_exchange_type(message))
     {
         case ID_PROT:
             if (this->state == CR_AUTH)
             {
                 build_certs(this, message);
                 return SUCCESS;
             }
             return NEED_MORE;
         case AGGRESSIVE:
             if (this->state == CR_AUTH)
             {
                 build_certs(this, message);
                 return SUCCESS;
             }
             return NEED_MORE;
         default:
             return FAILED;
     }
 }
METHOD (task_t , process_r , status_t , private_isakmp_cert_post_t * this, message_t * message)
Definition at line 187 of file isakmp_cert_post.c.
References AGGRESSIVE, FAILED, message_t::get_exchange_type, ID_PROT, NEED_MORE, SUCCESS, and use_certs().
 {
     switch (message->get_exchange_type(message))
     {
         case ID_PROT:
         {
             switch (this->state)
             {
                 case CR_SA:
                     if (!use_certs(this, message))
                     {
                         return SUCCESS;
                     }
                     return NEED_MORE;
                 case CR_KE:
                     return NEED_MORE;
                 case CR_AUTH:
                     return NEED_MORE;
                 default:
                     return FAILED;
             }
         }
         case AGGRESSIVE:
         {
             switch (this->state)
             {
                 case CR_SA:
                     if (!use_certs(this, message))
                     {
                         return SUCCESS;
                     }
                     return NEED_MORE;
                 case CR_AUTH:
                     return SUCCESS;
                 default:
                     return FAILED;
             }
         }
         default:
             return FAILED;
     }
 }
METHOD (task_t , build_r , status_t , private_isakmp_cert_post_t * this, message_t * message)
Definition at line 231 of file isakmp_cert_post.c.
References AGGRESSIVE, build_certs(), FAILED, message_t::get_exchange_type, ID_PROT, NEED_MORE, and SUCCESS.
 {
     switch (message->get_exchange_type(message))
     {
         case ID_PROT:
             switch (this->state)
             {
                 case CR_SA:
                     this->state = CR_KE;
                     return NEED_MORE;
                 case CR_KE:
                     this->state = CR_AUTH;
                     return NEED_MORE;
                 case CR_AUTH:
                     build_certs(this, message);
                     return SUCCESS;
             }
         case AGGRESSIVE:
             switch (this->state)
             {
                 case CR_SA:
                     build_certs(this, message);
                     this->state = CR_AUTH;
                     return NEED_MORE;
                 case CR_AUTH:
                     return SUCCESS;
                 default:
                     return FAILED;
             }
         default:
             return FAILED;
     }
 }
METHOD (task_t , process_i , status_t , private_isakmp_cert_post_t * this, message_t * message)
Definition at line 266 of file isakmp_cert_post.c.
References AGGRESSIVE, FAILED, message_t::get_exchange_type, ID_PROT, NEED_MORE, SUCCESS, and use_certs().
 {
     switch (message->get_exchange_type(message))
     {
         case ID_PROT:
         {
             switch (this->state)
             {
                 case CR_SA:
                     if (!use_certs(this, message))
                     {
                         return SUCCESS;
                     }
                     this->state = CR_KE;
                     return NEED_MORE;
                 case CR_KE:
                     this->state = CR_AUTH;
                     return NEED_MORE;
                 case CR_AUTH:
                     return SUCCESS;
                 default:
                     return FAILED;
             }
             break;
         }
         case AGGRESSIVE:
         {
             if (this->state == CR_SA)
             {
                 if (!use_certs(this, message))
                 {
                     return SUCCESS;
                 }
                 this->state = CR_AUTH;
                 return NEED_MORE;
             }
             return SUCCESS;
         }
         default:
             return FAILED;
     }
 }
METHOD (task_t , get_type , task_type_t , private_isakmp_cert_post_t * this)
Definition at line 310 of file isakmp_cert_post.c.
References TASK_ISAKMP_CERT_POST.
 {
     return TASK_ISAKMP_CERT_POST;
 }
METHOD (task_t , migrate , void , private_isakmp_cert_post_t * this, ike_sa_t * ike_sa)
Definition at line 316 of file isakmp_cert_post.c.
 {
     this->ike_sa = ike_sa;
     this->state = CR_SA;
 }
METHOD (task_t , destroy , void , private_isakmp_cert_post_t * this)
Definition at line 323 of file isakmp_cert_post.c.
References free().
 {
     free(this);
 }
static bool use_certs (private_isakmp_cert_post_t * this, message_t * message) static
Check if we actually use certificates for authentication
Definition at line 62 of file isakmp_cert_post.c.
References AUTH_ECDSA_256, AUTH_ECDSA_384, AUTH_ECDSA_521, AUTH_HYBRID_INIT_RSA, AUTH_HYBRID_RESP_RSA, AUTH_RSA, AUTH_XAUTH_INIT_RSA, AUTH_XAUTH_RESP_RSA, message_t::create_payload_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, sa_payload_t::get_auth_method, payload_t::get_type, PLV1_SECURITY_ASSOCIATION, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     bool use = FALSE;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV1_SECURITY_ASSOCIATION)
         {
             sa_payload_t *sa_payload = (sa_payload_t*)payload;
             switch (sa_payload->get_auth_method(sa_payload))
             {
                 case AUTH_RSA:
                 case AUTH_ECDSA_256:
                 case AUTH_ECDSA_384:
                 case AUTH_ECDSA_521:
                 case AUTH_XAUTH_INIT_RSA:
                 case AUTH_XAUTH_RESP_RSA:
                 case AUTH_HYBRID_INIT_RSA:
                 case AUTH_HYBRID_RESP_RSA:
                     use = TRUE;
                     break;
                 default:
                     break;
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     return use;
 }