strongSwan: stroke_counter.c File Reference
stroke_counter.c File Reference
#include "stroke_counter.h"
#include <threading/spinlock.h>
#include <collections/hashtable.h>
Classes
struct private_stroke_counter_t
struct entry_t
Typedefs
typedef struct
private_stroke_counter_t private_stroke_counter_t
Functions
ENUM (stroke_counter_type_names, COUNTER_INIT_IKE_SA_REKEY, COUNTER_OUT_INFORMATIONAL_RSP,"ikeInitRekey","ikeRspRekey","ikeChildSaRekey","ikeInInvalid","ikeInInvalidSpi","ikeInInitReq","ikeInInitRsp","ikeOutInitReq","ikeOutInitRsp","ikeInAuthReq","ikeInAuthRsp","ikeOutAuthReq","ikeOutAuthRsp","ikeInCrChildReq","ikeInCrChildRsp","ikeOutCrChildReq","ikeOutCrChildRsp","ikeInInfoReq","ikeInInfoRsp","ikeOutInfoReq","ikeOutInfoRsp",)
static void destroy_entry (entry_t *this)
static u_int hash (char *name)
static bool equals (char *a, char *b)
static char * get_ike_sa_name (ike_sa_t *ike_sa)
static void count_named (private_stroke_counter_t *this, ike_sa_t *ike_sa, stroke_counter_type_t type)
METHOD (listener_t, alert, bool, private_stroke_counter_t *this, ike_sa_t *ike_sa, alert_t alert, va_list args)
METHOD (listener_t, ike_rekey, bool, private_stroke_counter_t *this, ike_sa_t *old, ike_sa_t *new)
METHOD (listener_t, child_rekey, bool, private_stroke_counter_t *this, ike_sa_t *ike_sa, child_sa_t *old, child_sa_t *new)
METHOD (listener_t, message_hook, bool, private_stroke_counter_t *this, ike_sa_t *ike_sa, message_t *message, bool incoming, bool plain)
static void print_counter (FILE *out, stroke_counter_type_t type, u_int64_t counter)
static void print_one (private_stroke_counter_t *this, FILE *out, char *name)
static void print_all (private_stroke_counter_t *this, FILE *out)
static void print_global (private_stroke_counter_t *this, FILE *out)
METHOD (stroke_counter_t, print, void, private_stroke_counter_t *this, FILE *out, char *name)
METHOD (stroke_counter_t, reset, void, private_stroke_counter_t *this, char *name)
METHOD (stroke_counter_t, destroy, void, private_stroke_counter_t *this)
stroke_counter_t * stroke_counter_create ()
Typedef Documentation
typedef struct private_stroke_counter_t private_stroke_counter_t
Definition at line 46 of file stroke_counter.c.
Function Documentation
static void count_named (private_stroke_counter_t * this, ike_sa_t * ike_sa, stroke_counter_type_t type) static
Increase a counter for a named entry
Definition at line 130 of file stroke_counter.c.
References entry_t::counter, get_ike_sa_name(), INIT, name, entry_t::name, strdup, and type.
Referenced by METHOD().
 {
     entry_t *entry;
     char *name;
     name = get_ike_sa_name(ike_sa);
     if (name)
     {
         entry = this->conns->get(this->conns, name);
         if (!entry)
         {
             INIT(entry,
                 .name = strdup(name),
             );
             this->conns->put(this->conns, entry->name, entry);
         }
         entry->counter[type]++;
     }
 }
static void destroy_entry (entry_t * this) static
Destroy named entry
Definition at line 87 of file stroke_counter.c.
References free(), and name.
Referenced by METHOD().
 {
     free(this->name);
     free(this);
 }
ENUM (stroke_counter_type_names , COUNTER_INIT_IKE_SA_REKEY , COUNTER_OUT_INFORMATIONAL_RSP , "ikeInitRekey" , "ikeRspRekey" , "ikeChildSaRekey" , "ikeInInvalid" , "ikeInInvalidSpi" , "ikeInInitReq" , "ikeInInitRsp" , "ikeOutInitReq" , "ikeOutInitRsp" , "ikeInAuthReq" , "ikeInAuthRsp" , "ikeOutAuthReq" , "ikeOutAuthRsp" , "ikeInCrChildReq" , "ikeInCrChildRsp" , "ikeOutCrChildReq" , "ikeOutCrChildRsp" , "ikeInInfoReq" , "ikeInInfoRsp" , "ikeOutInfoReq" , "ikeOutInfoRsp")
static bool equals (char * a, char * b) static
Hashtable equals function
Definition at line 104 of file stroke_counter.c.
References streq().
Referenced by stroke_counter_create().
 {
     return streq(a, b);
 }
static char* get_ike_sa_name (ike_sa_t * ike_sa) static
Get the name of an IKE_SA, but return NULL if it is not known yet
Definition at line 112 of file stroke_counter.c.
References peer_cfg_t::get_name, and ike_sa_t::get_peer_cfg.
Referenced by count_named().
 {
     peer_cfg_t *peer_cfg;
     if (ike_sa)
     {
         peer_cfg = ike_sa->get_peer_cfg(ike_sa);
         if (peer_cfg)
         {
             return peer_cfg->get_name(peer_cfg);
         }
     }
     return NULL;
 }
static u_int hash (char * name) static
Hashtable hash function
Definition at line 96 of file stroke_counter.c.
References chunk_from_str, and chunk_hash().
Referenced by stroke_counter_create().
 {
     return chunk_hash(chunk_from_str(name));
 }
METHOD (listener_t , alert , bool , private_stroke_counter_t * this, ike_sa_t * ike_sa, alert_t alert, va_list args)
Definition at line 151 of file stroke_counter.c.
References ALERT_INVALID_IKE_SPI, ALERT_PARSE_ERROR_BODY, ALERT_PARSE_ERROR_HEADER, count_named(), COUNTER_IN_INVALID, COUNTER_IN_INVALID_IKE_SPI, spinlock_t::lock, lock, TRUE, type, and spinlock_t::unlock.
 {
     stroke_counter_type_t type;
     switch (alert)
     {
         case ALERT_INVALID_IKE_SPI:
             type = COUNTER_IN_INVALID_IKE_SPI;
             break;
         case ALERT_PARSE_ERROR_HEADER:
         case ALERT_PARSE_ERROR_BODY:
             type = COUNTER_IN_INVALID;
             break;
         default:
             return TRUE;
     }
     this->lock->lock(this->lock);
     this->counter[type]++;
     count_named(this, ike_sa, type);
     this->lock->unlock(this->lock);
     return TRUE;
 }
METHOD (listener_t , ike_rekey , bool , private_stroke_counter_t * this, ike_sa_t * old, ike_sa_t * new)
Definition at line 178 of file stroke_counter.c.
References count_named(), COUNTER_INIT_IKE_SA_REKEY, COUNTER_RESP_IKE_SA_REKEY, id, ike_sa_id_t::is_initiator, spinlock_t::lock, lock, TRUE, type, and spinlock_t::unlock.
 {
     stroke_counter_type_t type;
     ike_sa_id_t *id;
     id = new->get_id(new);
     if (id->is_initiator(id))
     {
         type = COUNTER_INIT_IKE_SA_REKEY;
     }
     else
     {
         type = COUNTER_RESP_IKE_SA_REKEY;
     }
     this->lock->lock(this->lock);
     this->counter[type]++;
     count_named(this, old, type);
     this->lock->unlock(this->lock);
     return TRUE;
 }
METHOD (listener_t , child_rekey , bool , private_stroke_counter_t * this, ike_sa_t * ike_sa, child_sa_t * old, child_sa_t * new)
Definition at line 202 of file stroke_counter.c.
References count_named(), COUNTER_CHILD_SA_REKEY, spinlock_t::lock, lock, TRUE, and spinlock_t::unlock.
 {
     this->lock->lock(this->lock);
     this->counter[COUNTER_CHILD_SA_REKEY]++;
     count_named(this, ike_sa, COUNTER_CHILD_SA_REKEY);
     this->lock->unlock(this->lock);
     return TRUE;
 }
METHOD (listener_t , message_hook , bool , private_stroke_counter_t * this, ike_sa_t * ike_sa, message_t * message, bool incoming, bool plain)
Definition at line 214 of file stroke_counter.c.
References count_named(), COUNTER_IN_CREATE_CHILD_SA_REQ, COUNTER_IN_CREATE_CHILD_SA_RSP, COUNTER_IN_IKE_AUTH_REQ, COUNTER_IN_IKE_AUTH_RSP, COUNTER_IN_IKE_SA_INIT_REQ, COUNTER_IN_IKE_SA_INIT_RSP, COUNTER_IN_INFORMATIONAL_REQ, COUNTER_IN_INFORMATIONAL_RSP, COUNTER_OUT_CREATE_CHILD_SA_REQ, COUNTER_OUT_CREATE_CHILD_SA_RSP, COUNTER_OUT_IKE_AUTH_REQ, COUNTER_OUT_IKE_AUTH_RSP, COUNTER_OUT_IKE_SA_INIT_REQ, COUNTER_OUT_IKE_SA_INIT_RES, COUNTER_OUT_INFORMATIONAL_REQ, COUNTER_OUT_INFORMATIONAL_RSP, CREATE_CHILD_SA, message_t::get_exchange_type, message_t::get_request, IKE_AUTH, IKE_SA_INIT, INFORMATIONAL, spinlock_t::lock, lock, request(), TRUE, type, and spinlock_t::unlock.
 {
     stroke_counter_type_t type;
     bool request;
     if ((incoming && !plain) || (!incoming && !plain))
     {   /* handle each message only once */
         return TRUE;
     }
     request = message->get_request(message);
     switch (message->get_exchange_type(message))
     {
         case IKE_SA_INIT:
             if (incoming)
             {
                 type = request ? COUNTER_IN_IKE_SA_INIT_REQ
                                : COUNTER_IN_IKE_SA_INIT_RSP;
             }
             else
             {
                 type = request ? COUNTER_OUT_IKE_SA_INIT_REQ
                                : COUNTER_OUT_IKE_SA_INIT_RES;
             }
             break;
         case IKE_AUTH:
             if (incoming)
             {
                 type = request ? COUNTER_IN_IKE_AUTH_REQ
                                : COUNTER_IN_IKE_AUTH_RSP;
             }
             else
             {
                 type = request ? COUNTER_OUT_IKE_AUTH_REQ
                                : COUNTER_OUT_IKE_AUTH_RSP;
             }
             break;
         case CREATE_CHILD_SA:
             if (incoming)
             {
                 type = request ? COUNTER_IN_CREATE_CHILD_SA_REQ
                                : COUNTER_IN_CREATE_CHILD_SA_RSP;
             }
             else
             {
                 type = request ? COUNTER_OUT_CREATE_CHILD_SA_REQ
                                : COUNTER_OUT_CREATE_CHILD_SA_RSP;
             }
             break;
         case INFORMATIONAL:
             if (incoming)
             {
                 type = request ? COUNTER_IN_INFORMATIONAL_REQ
                                : COUNTER_IN_INFORMATIONAL_RSP;
             }
             else
             {
                 type = request ? COUNTER_OUT_INFORMATIONAL_REQ
                                : COUNTER_OUT_INFORMATIONAL_RSP;
             }
             break;
         default:
             return TRUE;
     }
     this->lock->lock(this->lock);
     this->counter[type]++;
     count_named(this, ike_sa, type);
     this->lock->unlock(this->lock);
     return TRUE;
 }
METHOD (stroke_counter_t , print , void , private_stroke_counter_t * this, FILE * out, char * name)
Definition at line 386 of file stroke_counter.c.
References print_all(), print_global(), print_one(), and streq().
 {
     if (name)
     {
         if (streq(name, "all"))
         {
             return print_all(this, out);
         }
         return print_one(this, out, name);
     }
     return print_global(this, out);
 }
METHOD (stroke_counter_t , reset , void , private_stroke_counter_t * this, char * name)
Definition at line 400 of file stroke_counter.c.
References destroy_entry(), spinlock_t::lock, lock, memset, and spinlock_t::unlock.
 {
     this->lock->lock(this->lock);
     if (name)
     {
         entry_t *entry;
         entry = this->conns->remove(this->conns, name);
         if (entry)
         {
             destroy_entry(entry);
         }
     }
     else
     {
         memset(&this->counter, 0, sizeof(this->counter));
     }
     this->lock->unlock(this->lock);
 }
METHOD (stroke_counter_t , destroy , void , private_stroke_counter_t * this)
Definition at line 421 of file stroke_counter.c.
References spinlock_t::destroy, enumerator_t::destroy, destroy_entry(), enumerator_t::enumerate, free(), lock, and name.
 {
     enumerator_t *enumerator;
     char *name;
     entry_t *entry;
     enumerator = this->conns->create_enumerator(this->conns);
     while (enumerator->enumerate(enumerator, &name, &entry))
     {
         destroy_entry(entry);
     }
     enumerator->destroy(enumerator);
     this->conns->destroy(this->conns);
     this->lock->destroy(this->lock);
     free(this);
 }
static void print_all (private_stroke_counter_t * this, FILE * out) static
Print counters for all connections
Definition at line 335 of file stroke_counter.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, linked_list_t::destroy_function, enumerator_t::enumerate, free(), linked_list_t::insert_last, linked_list_create(), list, spinlock_t::lock, lock, name, print_one(), strdup, and spinlock_t::unlock.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     linked_list_t *list;
     char *name;
     list = linked_list_create();
     this->lock->lock(this->lock);
     enumerator = this->conns->create_enumerator(this->conns);
     while (enumerator->enumerate(enumerator, &name, &entry))
     {
         list->insert_last(list, strdup(name));
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &name))
     {
         print_one(this, out, name);
     }
     enumerator->destroy(enumerator);
     list->destroy_function(list, free);
 }
static void print_counter (FILE * out, stroke_counter_type_t type, u_int64_t counter) static
Print a single counter value to out
Definition at line 292 of file stroke_counter.c.
References fprintf.
Referenced by print_global(), and print_one().
 {
     fprintf(out, "%-18N %12llu\n", stroke_counter_type_names, type, counter);
 }
static void print_global (private_stroke_counter_t * this, FILE * out) static
Print global counters
Definition at line 366 of file stroke_counter.c.
References COUNTER_MAX, countof, fprintf, spinlock_t::lock, lock, print_counter(), and spinlock_t::unlock.
Referenced by METHOD().
 {
     u_int64_t counter[COUNTER_MAX];
     int i;
     this->lock->lock(this->lock);
     for (i = 0; i < countof(this->counter); i++)
     {
         counter[i] = this->counter[i];
     }
     this->lock->unlock(this->lock);
     fprintf(out, "\nList of IKE counters:\n\n");
     for (i = 0; i < countof(this->counter); i++)
     {
         print_counter(out, i, counter[i]);
     }
 }
static void print_one (private_stroke_counter_t * this, FILE * out, char * name) static
Print IKE counters for a specific connection
Definition at line 301 of file stroke_counter.c.
References entry_t::counter, COUNTER_MAX, countof, fprintf, spinlock_t::lock, lock, print_counter(), and spinlock_t::unlock.
Referenced by METHOD(), and print_all().
 {
     u_int64_t counter[COUNTER_MAX];
     entry_t *entry;
     int i;
     this->lock->lock(this->lock);
     entry = this->conns->get(this->conns, name);
     if (entry)
     {
         for (i = 0; i < countof(this->counter); i++)
         {
             counter[i] = entry->counter[i];
         }
     }
     this->lock->unlock(this->lock);
     if (entry)
     {
         fprintf(out, "\nList of IKE counters for '%s':\n\n", name);
         for (i = 0; i < countof(this->counter); i++)
         {
             print_counter(out, i, counter[i]);
         }
     }
     else
     {
         fprintf(out, "No IKE counters found for '%s'\n", name);
     }
 }