strongSwan: gmp_diffie_hellman
gmp_diffie_hellman
gmp
Classes
struct gmp_diffie_hellman_t
Typedefs
typedef struct gmp_diffie_hellman_t gmp_diffie_hellman_t
Functions
gmp_diffie_hellman_t * gmp_diffie_hellman_create (diffie_hellman_group_t group)
gmp_diffie_hellman_t * gmp_diffie_hellman_create_custom (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Detailed Description
Typedef Documentation
typedef struct gmp_diffie_hellman_t gmp_diffie_hellman_t
Definition at line 25 of file gmp_diffie_hellman.h.
Function Documentation
gmp_diffie_hellman_t* gmp_diffie_hellman_create (diffie_hellman_group_t group)
Creates a new gmp_diffie_hellman_t object.
Parameters
group Diffie Hellman group number to use
Returns
gmp_diffie_hellman_t object, NULL if not supported
Definition at line 277 of file gmp_diffie_hellman.c.
References create_generic(), diffie_hellman_get_params(), diffie_hellman_params_t::exp_len, diffie_hellman_params_t::generator, params, and diffie_hellman_params_t::prime.
Referenced by METHOD().
 {
     diffie_hellman_params_t *params;
     params = diffie_hellman_get_params(group);
     if (!params)
     {
         return NULL;
     }
     return create_generic(group, params->exp_len,
                           params->generator, params->prime);
 }
gmp_diffie_hellman_t* gmp_diffie_hellman_create_custom (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Creates a new gmp_diffie_hellman_t object for MODP_CUSTOM.
Parameters
group MODP_CUSTOM
g generator
p prime
Returns
gmp_diffie_hellman_t object, NULL if not supported
Definition at line 291 of file gmp_diffie_hellman.c.
References create_generic(), chunk_t::len, and MODP_CUSTOM.
Referenced by METHOD().
 {
     if (group == MODP_CUSTOM)
     {
         return create_generic(MODP_CUSTOM, p.len, g, p);
     }
     return NULL;
 }