strongSwan: test_hasher.c File Reference
test_hasher.c File Reference
#include "test_suite.h"
#include <crypto/hashers/hasher.h>
#include <crypto/prfs/prf.h>
#include <crypto/signers/signer.h>
#include <asn1/oid.h>
#include <utils/test.h>
Classes
struct hasher_oid_t
struct hasher_sig_scheme_t
struct hasher_prf_t
struct hasher_auth_t
struct hasher_ikev2_t
Functions
START_TEST (test_hasher_from_oid)
END_TEST START_TEST (test_hasher_to_oid)
END_TEST START_TEST (test_hasher_sig_to_oid)
START_TEST (test_hasher_from_sig_scheme)
START_TEST (test_hasher_from_prf)
START_TEST (test_hasher_from_integrity)
END_TEST START_TEST (test_hasher_to_integrity)
START_TEST (test_hasher_for_ikev2)
END_TEST Suite * hasher_suite_create ()
Variables
static hasher_oid_t oids []
static hasher_sig_scheme_t sig_schemes []
static hasher_prf_t prfs []
static hasher_auth_t auths []
static hasher_ikev2_t ikev2 []
Function Documentation
END_TEST Suite* hasher_suite_create ()
Definition at line 235 of file test_hasher.c.
References countof, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("hasher");
     tc = tcase_create("from_oid");
     tcase_add_loop_test(tc, test_hasher_from_oid, 0, 15);
     suite_add_tcase(s, tc);
     tc = tcase_create("to_oid");
     tcase_add_loop_test(tc, test_hasher_to_oid, 0, 12);
     suite_add_tcase(s, tc);
     tc = tcase_create("sig_to_oid");
     tcase_add_loop_test(tc, test_hasher_sig_to_oid, 11, countof(oids));
     suite_add_tcase(s, tc);
     tc = tcase_create("from_sig_scheme");
     tcase_add_loop_test(tc, test_hasher_from_sig_scheme, 0, countof(sig_schemes));
     suite_add_tcase(s, tc);
     tc = tcase_create("from_prf");
     tcase_add_loop_test(tc, test_hasher_from_prf, 0, countof(prfs));
     suite_add_tcase(s, tc);
     tc = tcase_create("from_integrity");
     tcase_add_loop_test(tc, test_hasher_from_integrity, 4, countof(auths));
     suite_add_tcase(s, tc);
     tc = tcase_create("to_integrity");
     tcase_add_loop_test(tc, test_hasher_to_integrity, 0, 17);
     suite_add_tcase(s, tc);
     tc = tcase_create("for_ikev2");
     tcase_add_loop_test(tc, test_hasher_for_ikev2, 0, countof(ikev2));
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_hasher_from_oid)
Definition at line 65 of file test_hasher.c.
References alg, ck_assert, and hasher_algorithm_from_oid().
 {
     ck_assert(hasher_algorithm_from_oid(oids[_i].oid) == oids[_i].alg);
 }
END_TEST START_TEST (test_hasher_to_oid)
Definition at line 71 of file test_hasher.c.
References alg, ck_assert, and hasher_algorithm_to_oid().
 {
     ck_assert(hasher_algorithm_to_oid(oids[_i].alg) == oids[_i].oid);
 }
END_TEST START_TEST (test_hasher_sig_to_oid)
Definition at line 77 of file test_hasher.c.
References alg, ck_assert, hasher_signature_algorithm_to_oid(), and key.
 {
     ck_assert(hasher_signature_algorithm_to_oid(oids[_i].alg,
                                                 oids[_i].key) == oids[_i].oid);
 }
START_TEST (test_hasher_from_sig_scheme)
Definition at line 115 of file test_hasher.c.
References alg, ck_assert, hasher_from_signature_scheme(), and scheme.
 {
     ck_assert(hasher_from_signature_scheme(sig_schemes[_i].scheme) ==
                                            sig_schemes[_i].alg);
 }
START_TEST (test_hasher_from_prf)
Definition at line 144 of file test_hasher.c.
References alg, ck_assert, hasher_algorithm_from_prf(), and prf.
 {
     ck_assert(hasher_algorithm_from_prf(prfs[_i].prf) == prfs[_i].alg);
 }
START_TEST (test_hasher_from_integrity)
Definition at line 184 of file test_hasher.c.
References alg, ck_assert, hasher_algorithm_from_integrity(), and length.
 {
     size_t length;
     length = 0;
     ck_assert(hasher_algorithm_from_integrity(auths[_i].auth, NULL) ==
                                               auths[_i].alg);
     ck_assert(hasher_algorithm_from_integrity(auths[_i].auth, &length) ==
                                               auths[_i].alg);
     ck_assert(length == auths[_i].length);
 }
END_TEST START_TEST (test_hasher_to_integrity)
Definition at line 197 of file test_hasher.c.
References alg, AUTH_UNDEFINED, ck_assert, hasher_algorithm_to_integrity(), and length.
 {
     ck_assert(hasher_algorithm_to_integrity(
                         auths[_i].alg, auths[_i].length) == auths[_i].auth);
     ck_assert(hasher_algorithm_to_integrity(
                         auths[_i].alg, 0) == AUTH_UNDEFINED);
 }
START_TEST (test_hasher_for_ikev2)
Definition at line 229 of file test_hasher.c.
References alg, ck_assert, and hasher_algorithm_for_ikev2().
 {
     ck_assert(hasher_algorithm_for_ikev2(ikev2[_i].alg) == ikev2[_i].ikev2);
 }
Variable Documentation
hasher_auth_t auths[] static
Initial value:
= {
    { AUTH_UNDEFINED, HASH_MD2, 0 },
    { AUTH_UNDEFINED, HASH_MD4, 0 },
    { AUTH_UNDEFINED, HASH_SHA224, 0 },
    { AUTH_UNDEFINED, 9, 0 },
    { AUTH_UNDEFINED, HASH_UNKNOWN, 0 },
    { AUTH_HMAC_MD5_96, HASH_MD5, 12 },
    { AUTH_HMAC_SHA1_96, HASH_SHA1, 12 },
    { AUTH_HMAC_SHA2_256_96, HASH_SHA256, 12 },
    { AUTH_HMAC_MD5_128, HASH_MD5, 16 },
    { AUTH_HMAC_SHA1_128, HASH_SHA1, 16 },
    { AUTH_HMAC_SHA2_256_128, HASH_SHA256, 16 },
    { AUTH_HMAC_SHA1_160, HASH_SHA1, 20 },
    { AUTH_HMAC_SHA2_384_192, HASH_SHA384, 24 },
    { AUTH_HMAC_SHA2_256_256, HASH_SHA256, 32 },
    { AUTH_HMAC_SHA2_512_256, HASH_SHA512, 32 },
    { AUTH_HMAC_SHA2_384_384, HASH_SHA384, 48 },
    { AUTH_HMAC_SHA2_512_512, HASH_SHA512, 64 },
    { AUTH_AES_CMAC_96, HASH_UNKNOWN, 0 },
    { AUTH_AES_128_GMAC, HASH_UNKNOWN, 0 },
    { AUTH_AES_192_GMAC, HASH_UNKNOWN, 0 },
    { AUTH_AES_256_GMAC, HASH_UNKNOWN, 0 },
    { AUTH_AES_XCBC_96, HASH_UNKNOWN, 0 },
    { AUTH_DES_MAC, HASH_UNKNOWN, 0 },
    { AUTH_CAMELLIA_XCBC_96, HASH_UNKNOWN, 0 },
    { 0, HASH_UNKNOWN, 0 }
}
Definition at line 156 of file test_hasher.c.
Referenced by check_oid(), and stroke_export().
hasher_ikev2_t ikev2[] static
Initial value:
= {
    { HASH_SHA1,     TRUE  },
    { HASH_SHA256,   TRUE  },
    { HASH_SHA384,   TRUE  },
    { HASH_SHA512,   TRUE  },
    { HASH_UNKNOWN,  FALSE },
    { HASH_MD2,      FALSE },
    { HASH_MD4,      FALSE },
    { HASH_MD5,      FALSE },
    { HASH_SHA224,   FALSE },
    { HASH_SHA3_224, FALSE },
    { HASH_SHA3_256, FALSE },
    { HASH_SHA3_384, FALSE },
    { HASH_SHA3_512, FALSE },
    { 30,            FALSE }
}
Definition at line 212 of file test_hasher.c.
Referenced by ikev1_from_ikev2().
hasher_oid_t oids[] static
Definition at line 30 of file test_hasher.c.
hasher_prf_t prfs[] static
Initial value:
= {
    { PRF_HMAC_MD5, HASH_MD5 },
    { PRF_HMAC_SHA1, HASH_SHA1 },
    { PRF_FIPS_SHA1_160, HASH_SHA1 },
    { PRF_KEYED_SHA1, HASH_SHA1 },
    { PRF_HMAC_SHA2_256, HASH_SHA256 },
    { PRF_HMAC_SHA2_384, HASH_SHA384 },
    { PRF_HMAC_SHA2_512, HASH_SHA512 },
    { PRF_HMAC_TIGER, HASH_UNKNOWN },
    { PRF_AES128_XCBC, HASH_UNKNOWN },
    { PRF_AES128_CMAC, HASH_UNKNOWN },
    { PRF_FIPS_DES, HASH_UNKNOWN },
    { PRF_CAMELLIA128_XCBC, HASH_UNKNOWN },
    { PRF_UNDEFINED, HASH_UNKNOWN },
    { 0, HASH_UNKNOWN }
}
Definition at line 127 of file test_hasher.c.
Referenced by METHOD().
hasher_sig_scheme_t sig_schemes[] static
Initial value:
= {
    { SIGN_UNKNOWN,               HASH_UNKNOWN  },
    { SIGN_RSA_EMSA_PKCS1_NULL,   HASH_UNKNOWN  },
    { SIGN_RSA_EMSA_PKCS1_MD5,    HASH_MD5      },
    { SIGN_RSA_EMSA_PKCS1_SHA1,   HASH_SHA1     },
    { SIGN_RSA_EMSA_PKCS1_SHA224, HASH_SHA224   },
    { SIGN_RSA_EMSA_PKCS1_SHA256, HASH_SHA256   },
    { SIGN_RSA_EMSA_PKCS1_SHA384, HASH_SHA384   },
    { SIGN_RSA_EMSA_PKCS1_SHA512, HASH_SHA512   },
    { SIGN_ECDSA_WITH_SHA1_DER,   HASH_SHA1     },
    { SIGN_ECDSA_WITH_SHA256_DER, HASH_SHA256   },
    { SIGN_ECDSA_WITH_SHA384_DER, HASH_SHA384   },
    { SIGN_ECDSA_WITH_SHA512_DER, HASH_SHA512   },
    { SIGN_ECDSA_WITH_NULL,       HASH_UNKNOWN  },
    { SIGN_ECDSA_256,             HASH_SHA256   },
    { SIGN_ECDSA_384,             HASH_SHA384   },
    { SIGN_ECDSA_521,             HASH_SHA512   },
    { SIGN_BLISS_WITH_SHA2_256,   HASH_SHA256   },
    { SIGN_BLISS_WITH_SHA2_384,   HASH_SHA384   },
    { SIGN_BLISS_WITH_SHA2_512,   HASH_SHA512   },
    { SIGN_BLISS_WITH_SHA3_256,   HASH_SHA3_256 },
    { SIGN_BLISS_WITH_SHA3_384,   HASH_SHA3_384 },
    { SIGN_BLISS_WITH_SHA3_512,   HASH_SHA3_512 },
    { 30,                         HASH_UNKNOWN  }
}
Definition at line 89 of file test_hasher.c.