strongSwan: imc_agent.c File Reference
imc_agent.c File Reference
#include "imcv.h"
#include "imc_agent.h"
#include <tncif_names.h>
#include <utils/debug.h>
#include <threading/rwlock.h>
Classes
struct private_imc_agent_t
Typedefs
typedef struct private_imc_agent_t private_imc_agent_t
Functions
METHOD (imc_agent_t, bind_functions, TNC_Result, private_imc_agent_t *this, TNC_TNCC_BindFunctionPointer bind_function)
static imc_state_t * find_connection (private_imc_agent_t *this, TNC_ConnectionID id)
static bool delete_connection (private_imc_agent_t *this, TNC_ConnectionID id)
static bool get_bool_attribute (private_imc_agent_t *this, TNC_ConnectionID id, TNC_AttributeID attribute_id)
static char * get_str_attribute (private_imc_agent_t *this, TNC_ConnectionID id, TNC_AttributeID attribute_id)
static u_int32_t get_uint_attribute (private_imc_agent_t *this, TNC_ConnectionID id, TNC_AttributeID attribute_id)
METHOD (imc_agent_t, create_state, TNC_Result, private_imc_agent_t *this, imc_state_t *state)
METHOD (imc_agent_t, delete_state, TNC_Result, private_imc_agent_t *this, TNC_ConnectionID connection_id)
METHOD (imc_agent_t, change_state, TNC_Result, private_imc_agent_t *this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imc_state_t **state_p)
METHOD (imc_agent_t, get_state, bool, private_imc_agent_t *this, TNC_ConnectionID connection_id, imc_state_t **state)
METHOD (imc_agent_t, get_name, const char *, private_imc_agent_t *this)
METHOD (imc_agent_t, get_id, TNC_IMCID, private_imc_agent_t *this)
METHOD (imc_agent_t, reserve_additional_ids, TNC_Result, private_imc_agent_t *this, int count)
METHOD (imc_agent_t, count_additional_ids, int, private_imc_agent_t *this)
METHOD (imc_agent_t, create_id_enumerator, enumerator_t *, private_imc_agent_t *this)
METHOD (imc_agent_t, add_non_fatal_attr_type, void, private_imc_agent_t *this, pen_type_t type)
METHOD (imc_agent_t, get_non_fatal_attr_types, linked_list_t *, private_imc_agent_t *this)
METHOD (imc_agent_t, destroy, void, private_imc_agent_t *this)
imc_agent_t * imc_agent_create (const char *name, pen_type_t *supported_types, u_int32_t type_count, TNC_IMCID id, TNC_Version *actual_version)
Typedef Documentation
typedef struct private_imc_agent_t private_imc_agent_t
Definition at line 24 of file imc_agent.c.
Function Documentation
static bool delete_connection (private_imc_agent_t * this, TNC_ConnectionID id) static
delete a connection state with a given Connection ID
Definition at line 264 of file imc_agent.c.
References enumerator_t::destroy, imc_state_t::destroy, enumerator_t::enumerate, FALSE, found, imc_state_t::get_connection_id, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     imc_state_t *state;
     bool found = FALSE;
     this->connection_lock->write_lock(this->connection_lock);
     enumerator = this->connections->create_enumerator(this->connections);
     while (enumerator->enumerate(enumerator, &state))
     {
         if (id == state->get_connection_id(state))
         {
             found = TRUE;
             state->destroy(state);
             this->connections->remove_at(this->connections, enumerator);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->connection_lock->unlock(this->connection_lock);
     return found;
 }
static imc_state_t* find_connection (private_imc_agent_t * this, TNC_ConnectionID id) static
finds a connection state based on its Connection ID
Definition at line 239 of file imc_agent.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, and imc_state_t::get_connection_id.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     imc_state_t *state, *found = NULL;
     this->connection_lock->read_lock(this->connection_lock);
     enumerator = this->connections->create_enumerator(this->connections);
     while (enumerator->enumerate(enumerator, &state))
     {
         if (id == state->get_connection_id(state))
         {
             found = state;
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->connection_lock->unlock(this->connection_lock);
     return found;
 }
static bool get_bool_attribute (private_imc_agent_t * this, TNC_ConnectionID id, TNC_AttributeID attribute_id) static
Read a boolean attribute
Definition at line 291 of file imc_agent.c.
References len, and TNC_RESULT_SUCCESS.
Referenced by METHOD().
 {
     TNC_UInt32 len;
     char buf[4];
     return this->get_attribute  &&
            this->get_attribute(this->id, id, attribute_id, 4, buf, &len) ==
                                TNC_RESULT_SUCCESS && len == 1 && *buf == 0x01;
 }
static char* get_str_attribute (private_imc_agent_t * this, TNC_ConnectionID id, TNC_AttributeID attribute_id) static
Read a string attribute
Definition at line 305 of file imc_agent.c.
References BUF_LEN, len, strdup, and TNC_RESULT_SUCCESS.
Referenced by METHOD().
 {
     TNC_UInt32 len;
     char buf[BUF_LEN];
     if (this->get_attribute  &&
         this->get_attribute(this->id, id, attribute_id, BUF_LEN, buf, &len) ==
                             TNC_RESULT_SUCCESS && len <= BUF_LEN)
     {
         return strdup(buf);
     }
     return NULL;
  }
static u_int32_t get_uint_attribute (private_imc_agent_t * this, TNC_ConnectionID id, TNC_AttributeID attribute_id) static
Read an UInt32 attribute
Definition at line 323 of file imc_agent.c.
References len, TNC_RESULT_SUCCESS, and untoh32().
Referenced by METHOD().
 {
     TNC_UInt32 len;
     char buf[4];
     if (this->get_attribute  &&
         this->get_attribute(this->id, id, attribute_id, 4, buf, &len) ==
                             TNC_RESULT_SUCCESS && len == 4)
     {
         return untoh32(buf);
     }
     return 0;
  }
METHOD (imc_agent_t , bind_functions , TNC_Result , private_imc_agent_t * this, TNC_TNCC_BindFunctionPointer bind_function)
Definition at line 150 of file imc_agent.c.
References DBG1, DBG_IMC, free(), malloc(), send_message(), TNC_RESULT_INVALID_PARAMETER, TNC_RESULT_SUCCESS, and type.
 {
     if (!bind_function)
     {
         DBG1(DBG_IMC, "TNC client failed to provide bind function");
         return TNC_RESULT_INVALID_PARAMETER;
     }
     if (bind_function(this->id, "TNC_TNCC_ReportMessageTypes",
             (void**)&this->report_message_types) != TNC_RESULT_SUCCESS)
     {
         this->report_message_types = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_ReportMessageTypesLong",
             (void**)&this->report_message_types_long) != TNC_RESULT_SUCCESS)
     {
         this->report_message_types_long = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_RequestHandshakeRetry",
             (void**)&this->public.request_handshake_retry) != TNC_RESULT_SUCCESS)
     {
         this->public.request_handshake_retry = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_SendMessage",
             (void**)&this->public.send_message) != TNC_RESULT_SUCCESS)
     {
         this->public.send_message = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_SendMessageLong",
             (void**)&this->public.send_message_long) != TNC_RESULT_SUCCESS)
     {
         this->public.send_message_long = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_GetAttribute",
             (void**)&this->get_attribute) != TNC_RESULT_SUCCESS)
     {
         this->get_attribute = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_SetAttribute",
             (void**)&this->set_attribute) != TNC_RESULT_SUCCESS)
     {
         this->set_attribute = NULL;
     }
     if (bind_function(this->id, "TNC_TNCC_ReserveAdditionalIMCID",
             (void**)&this->reserve_additional_id) != TNC_RESULT_SUCCESS)
     {
         this->reserve_additional_id = NULL;
     }
     if (this->report_message_types_long)
     {
         TNC_VendorIDList vendor_id_list;
         TNC_MessageSubtypeList subtype_list;
         int i;
         vendor_id_list = malloc(this->type_count * sizeof(TNC_UInt32));
         subtype_list   = malloc(this->type_count * sizeof(TNC_UInt32));
         for (i = 0; i < this->type_count; i++)
         {
             vendor_id_list[i] = this->supported_types[i].vendor_id;
             subtype_list[i]   = this->supported_types[i].type;
         }
         this->report_message_types_long(this->id, vendor_id_list, subtype_list,
                                         this->type_count);
         free(vendor_id_list);
         free(subtype_list);
     }
     else if (this->report_message_types)
     {
         TNC_MessageTypeList type_list;
         int i;
         type_list = malloc(this->type_count * sizeof(TNC_UInt32));
         for (i = 0; i < this->type_count; i++)
         {
             type_list[i] = (this->supported_types[i].vendor_id << 8) |
                            (this->supported_types[i].type & 0xff);
         }
         this->report_message_types(this->id, type_list, this->type_count);
         free(type_list);
     }
     return TNC_RESULT_SUCCESS;
 }
METHOD (imc_agent_t , create_state , TNC_Result , private_imc_agent_t * this, imc_state_t * state)
Definition at line 338 of file imc_agent.c.
References DBG1, DBG2, DBG_IMC, imc_state_t::destroy, FALSE, find_connection(), free(), get_bool_attribute(), imc_state_t::get_connection_id, get_str_attribute(), get_uint_attribute(), name, imc_state_t::set_flags, imc_state_t::set_max_msg_len, TNC_ATTRIBUTEID_HAS_EXCLUSIVE, TNC_ATTRIBUTEID_HAS_LONG_TYPES, TNC_ATTRIBUTEID_HAS_SOH, TNC_ATTRIBUTEID_IFT_PROTOCOL, TNC_ATTRIBUTEID_IFT_VERSION, TNC_ATTRIBUTEID_IFTNCCS_PROTOCOL, TNC_ATTRIBUTEID_IFTNCCS_VERSION, TNC_ATTRIBUTEID_MAX_MESSAGE_SIZE, TNC_RESULT_OTHER, and TNC_RESULT_SUCCESS.
 {
     TNC_ConnectionID conn_id;
     char *tnccs_p = NULL, *tnccs_v = NULL, *t_p = NULL, *t_v = NULL;
     bool has_long = FALSE, has_excl = FALSE, has_soh = FALSE;
     u_int32_t max_msg_len;
     conn_id = state->get_connection_id(state);
     if (find_connection(this, conn_id))
     {
         DBG1(DBG_IMC, "IMC %u \"%s\" already created a state for Connection ID %u",
                        this->id, this->name, conn_id);
         state->destroy(state);
         return TNC_RESULT_OTHER;
     }
     /* Get and display attributes from TNCC via IF-IMC */
     has_long = get_bool_attribute(this, conn_id, TNC_ATTRIBUTEID_HAS_LONG_TYPES);
     has_excl = get_bool_attribute(this, conn_id, TNC_ATTRIBUTEID_HAS_EXCLUSIVE);
     has_soh  = get_bool_attribute(this, conn_id, TNC_ATTRIBUTEID_HAS_SOH);
     tnccs_p = get_str_attribute(this, conn_id, TNC_ATTRIBUTEID_IFTNCCS_PROTOCOL);
     tnccs_v = get_str_attribute(this, conn_id, TNC_ATTRIBUTEID_IFTNCCS_VERSION);
     t_p = get_str_attribute(this, conn_id, TNC_ATTRIBUTEID_IFT_PROTOCOL);
     t_v = get_str_attribute(this, conn_id, TNC_ATTRIBUTEID_IFT_VERSION);
     max_msg_len = get_uint_attribute(this, conn_id, TNC_ATTRIBUTEID_MAX_MESSAGE_SIZE);
     state->set_flags(state, has_long, has_excl);
     state->set_max_msg_len(state, max_msg_len);
     DBG2(DBG_IMC, "IMC %u \"%s\" created a state for %s %s Connection ID %u: "
                   "%slong %sexcl %ssoh", this->id, this->name,
                   tnccs_p ? tnccs_p:"?", tnccs_v ? tnccs_v:"?", conn_id,
                   has_long ? "+":"-", has_excl ? "+":"-", has_soh ? "+":"-");
     DBG2(DBG_IMC, "  over %s %s with maximum PA-TNC message size of %u bytes",
                   t_p ? t_p:"?", t_v ? t_v :"?", max_msg_len);
     free(tnccs_p);
     free(tnccs_v);
     free(t_p);
     free(t_v);
     this->connection_lock->write_lock(this->connection_lock);
     this->connections->insert_last(this->connections, state);
     this->connection_lock->unlock(this->connection_lock);
     return TNC_RESULT_SUCCESS;
 }
METHOD (imc_agent_t , delete_state , TNC_Result , private_imc_agent_t * this, TNC_ConnectionID connection_id)
Definition at line 386 of file imc_agent.c.
References DBG1, DBG2, DBG_IMC, delete_connection(), name, TNC_RESULT_FATAL, and TNC_RESULT_SUCCESS.
 {
     if (!delete_connection(this, connection_id))
     {
         DBG1(DBG_IMC, "IMC %u \"%s\" has no state for Connection ID %u",
                       this->id, this->name, connection_id);
         return TNC_RESULT_FATAL;
     }
     DBG2(DBG_IMC, "IMC %u \"%s\" deleted the state of Connection ID %u",
                   this->id, this->name, connection_id);
     return TNC_RESULT_SUCCESS;
 }
METHOD (imc_agent_t , change_state , TNC_Result , private_imc_agent_t * this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imc_state_t ** state_p)
Definition at line 400 of file imc_agent.c.
References imc_state_t::change_state, DBG1, DBG2, DBG_IMC, find_connection(), name, TNC_CONNECTION_STATE_ACCESS_ALLOWED, TNC_CONNECTION_STATE_ACCESS_ISOLATED, TNC_CONNECTION_STATE_ACCESS_NONE, TNC_CONNECTION_STATE_CREATE, TNC_CONNECTION_STATE_DELETE, TNC_CONNECTION_STATE_HANDSHAKE, TNC_Connection_State_names, TNC_RESULT_FATAL, TNC_RESULT_INVALID_PARAMETER, and TNC_RESULT_SUCCESS.
 {
     imc_state_t *state;
     switch (new_state)
     {
         case TNC_CONNECTION_STATE_HANDSHAKE:
         case TNC_CONNECTION_STATE_ACCESS_ALLOWED:
         case TNC_CONNECTION_STATE_ACCESS_ISOLATED:
         case TNC_CONNECTION_STATE_ACCESS_NONE:
             state = find_connection(this, connection_id);
             if (!state)
             {
                 DBG1(DBG_IMC, "IMC %u \"%s\" has no state for Connection ID %u",
                               this->id, this->name, connection_id);
                 return TNC_RESULT_FATAL;
             }
             state->change_state(state, new_state);
             DBG2(DBG_IMC, "IMC %u \"%s\" changed state of Connection ID %u to '%N'",
                           this->id, this->name, connection_id,
                           TNC_Connection_State_names, new_state);
             if (state_p)
             {
                 *state_p = state;
             }
             break;
         case TNC_CONNECTION_STATE_CREATE:
             DBG1(DBG_IMC, "state '%N' should be handled by create_state()",
                           TNC_Connection_State_names, new_state);
                 return TNC_RESULT_FATAL;
         case TNC_CONNECTION_STATE_DELETE:
             DBG1(DBG_IMC, "state '%N' should be handled by delete_state()",
                           TNC_Connection_State_names, new_state);
                 return TNC_RESULT_FATAL;
         default:
             DBG1(DBG_IMC, "IMC %u \"%s\" was notified of unknown state %u "
                           "for Connection ID %u",
                           this->id, this->name, new_state, connection_id);
             return TNC_RESULT_INVALID_PARAMETER;
     }
     return TNC_RESULT_SUCCESS;
 }
METHOD (imc_agent_t , get_state , bool , private_imc_agent_t * this, TNC_ConnectionID connection_id, imc_state_t ** state)
Definition at line 447 of file imc_agent.c.
References DBG1, DBG_IMC, FALSE, find_connection(), name, and TRUE.
 {
     *state = find_connection(this, connection_id);
     if (!*state)
     {
         DBG1(DBG_IMC, "IMC %u \"%s\" has no state for Connection ID %u",
                       this->id, this->name, connection_id);
         return FALSE;
     }
     return TRUE;
 }
METHOD (imc_agent_t , get_name , const char * , private_imc_agent_t * this)
Definition at line 461 of file imc_agent.c.
References name.
 {
     return  this->name;
 }
METHOD (imc_agent_t , get_id , TNC_IMCID , private_imc_agent_t * this)
Definition at line 467 of file imc_agent.c.
References id.
 {
     return  this->id;
 }
METHOD (imc_agent_t , reserve_additional_ids , TNC_Result , private_imc_agent_t * this, int count)
Definition at line 473 of file imc_agent.c.
References DBG1, DBG2, DBG_IMC, id, name, result, TNC_RESULT_ILLEGAL_OPERATION, and TNC_RESULT_SUCCESS.
 {
     TNC_Result result;
     TNC_UInt32 id;
     void *pointer;
     if (!this->reserve_additional_id)
     {
         DBG1(DBG_IMC, "IMC %u \"%s\" did not detect the capability to reserve "
                       "additional IMC IDs from the TNCC", this->id, this->name);
         return TNC_RESULT_ILLEGAL_OPERATION;
     }
     while (count > 0)
     {
         result = this->reserve_additional_id(this->id, &id);
         if (result != TNC_RESULT_SUCCESS)
         {
             DBG1(DBG_IMC, "IMC %u \"%s\" failed to reserve %d additional IMC IDs",
                           this->id, this->name, count);
             return result;
         }
         count--;
         /* store the scalar value in the pointer */
         pointer = (void*)(uintptr_t)id;
         this->additional_ids->insert_last(this->additional_ids, pointer);
         DBG2(DBG_IMC, "IMC %u \"%s\" reserved additional ID %u",
                       this->id, this->name, id);
     }
     return TNC_RESULT_SUCCESS;
 }
METHOD (imc_agent_t , count_additional_ids , int , private_imc_agent_t * this)
Definition at line 506 of file imc_agent.c.
 {
     return  this->additional_ids->get_count(this->additional_ids);
 }
METHOD (imc_agent_t , create_id_enumerator , enumerator_t * , private_imc_agent_t * this)
Definition at line 512 of file imc_agent.c.
 {
     return this->additional_ids->create_enumerator(this->additional_ids);
 }
METHOD (imc_agent_t , add_non_fatal_attr_type , void , private_imc_agent_t * this, pen_type_t type)
Definition at line 518 of file imc_agent.c.
References malloc_thing, and type.
 {
     pen_type_t *type_p;
     type_p = malloc_thing(pen_type_t);
     *type_p = type;
     this->non_fatal_attr_types->insert_last(this->non_fatal_attr_types, type_p);
 }
METHOD (imc_agent_t , get_non_fatal_attr_types , linked_list_t * , private_imc_agent_t * this)
Definition at line 528 of file imc_agent.c.
 {
     return this->non_fatal_attr_types;
 }
METHOD (imc_agent_t , destroy , void , private_imc_agent_t * this)
Definition at line 534 of file imc_agent.c.
References DBG1, DBG_IMC, free(), libimcv_deinit(), and name.
 {
     DBG1(DBG_IMC, "IMC %u \"%s\" terminated", this->id, this->name);
     this->additional_ids->destroy(this->additional_ids);
     this->non_fatal_attr_types->destroy_function(this->non_fatal_attr_types,
                                                  free);
     this->connections->destroy_function(this->connections, free);
     this->connection_lock->destroy(this->connection_lock);
     free(this);
     /* decrease the reference count or terminate */
     libimcv_deinit();
 }