strongSwan: capabilities.c File Reference
capabilities.c File Reference
#include "capabilities.h"
#include <utils/debug.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <pwd.h>
#include <grp.h>
#include <threading/mutex.h>
Classes
struct private_capabilities_t
Macros
#define EMULATE_R_FUNCS
Typedefs
typedef struct
private_capabilities_t private_capabilities_t
Functions
static bool has_group (gid_t group)
static bool has_capability (private_capabilities_t *this, u_int cap, bool *ignore)
static bool keep_capability (private_capabilities_t *this, u_int cap)
METHOD (capabilities_t, keep, bool, private_capabilities_t *this, u_int cap)
METHOD (capabilities_t, check, bool, private_capabilities_t *this, u_int cap)
METHOD (capabilities_t, get_uid, uid_t, private_capabilities_t *this)
METHOD (capabilities_t, get_gid, gid_t, private_capabilities_t *this)
METHOD (capabilities_t, set_uid, void, private_capabilities_t *this, uid_t uid)
METHOD (capabilities_t, set_gid, void, private_capabilities_t *this, gid_t gid)
METHOD (capabilities_t, resolve_uid, bool, private_capabilities_t *this, char *username)
METHOD (capabilities_t, resolve_gid, bool, private_capabilities_t *this, char *groupname)
static bool init_supplementary_groups (private_capabilities_t *this)
METHOD (capabilities_t, drop, bool, private_capabilities_t *this)
METHOD (capabilities_t, destroy, void, private_capabilities_t *this)
capabilities_t * capabilities_create ()
Macro Definition Documentation
#define EMULATE_R_FUNCS
Definition at line 38 of file capabilities.c.
Typedef Documentation
typedef struct private_capabilities_t private_capabilities_t
Definition at line 42 of file capabilities.c.
Function Documentation
static bool has_capability (private_capabilities_t * this, u_int cap, bool * ignore) static
Verify that the current process has the given capability
Definition at line 128 of file capabilities.c.
References CAP_CHOWN, FALSE, has_group(), ok, TRUE, and val.
Referenced by METHOD().
 {
     if (cap == CAP_CHOWN)
     {   /* if new files/UNIX sockets are created they should be owned by the
          * configured user and group.  This requires a call to chown(2).  But
          * CAP_CHOWN is not always required. */
         if (!this->uid || geteuid() == this->uid)
         {   /* if the owner does not change CAP_CHOWN is not needed */
             if (!this->gid || has_group(this->gid))
             {   /* the same applies if the owner is a member of the group */
                 if (ignore)
                 {   /* we don't have to keep this, if requested */
                     *ignore = TRUE;
                 }
                 return TRUE;
             }
         }
     }
 #ifndef CAPABILITIES
     /* if we can't check the actual capabilities assume only root has it */
     return geteuid() == 0;
 #endif /* !CAPABILITIES */
 #ifdef CAPABILITIES_LIBCAP
     cap_flag_value_t val;
     cap_t caps;
     bool ok;
     caps = cap_get_proc();
     if (!caps)
     {
         return FALSE;
     }
     ok = cap_get_flag(caps, cap, CAP_PERMITTED, &val) == 0 && val == CAP_SET;
     cap_free(caps);
     return ok;
 #endif /* CAPABILITIES_LIBCAP */
 #ifdef CAPABILITIES_NATIVE
     struct __user_cap_header_struct header = {
 #if defined(_LINUX_CAPABILITY_VERSION_3)
         .version = _LINUX_CAPABILITY_VERSION_3,
 #elif defined(_LINUX_CAPABILITY_VERSION_2)
         .version = _LINUX_CAPABILITY_VERSION_2,
 #elif defined(_LINUX_CAPABILITY_VERSION_1)
         .version = _LINUX_CAPABILITY_VERSION_1,
 #else
         .version = _LINUX_CAPABILITY_VERSION,
 #endif
     };
     struct __user_cap_data_struct caps[2];
     int i = 0;
     if (cap >= 32)
     {
         i++;
         cap -= 32;
     }
     return capget(&header, caps) == 0 && caps[i].permitted & (1 << cap);
 #endif /* CAPABILITIES_NATIVE */
 }
static bool has_group (gid_t group) static
Returns TRUE if the current process/user is member of the given group
Definition at line 87 of file capabilities.c.
References DBG1, DBG_LIB, FALSE, found, free(), groups, strerror, and TRUE.
Referenced by has_capability().
 {
     gid_t *groups;
     long ngroups, i;
     bool found = FALSE;
     if (group == getegid())
     {   /* it's unspecified if this is part of the list below or not */
         return TRUE;
     }
     ngroups = sysconf(_SC_NGROUPS_MAX);
     if (ngroups == -1)
     {
         DBG1(DBG_LIB, "getting groups for current process failed: %s",
              strerror(errno));
         return FALSE;
     }
     groups = calloc(ngroups + 1, sizeof(gid_t));
     ngroups = getgroups(ngroups, groups);
     if (ngroups == -1)
     {
         DBG1(DBG_LIB, "getting groups for current process failed: %s",
              strerror(errno));
         free(groups);
         return FALSE;
     }
     for (i = 0; i < ngroups; i++)
     {
         if (group == groups[i])
         {
             found = TRUE;
             break;
         }
     }
     free(groups);
     return found;
 }
static bool init_supplementary_groups (private_capabilities_t * this) static
Initialize supplementary groups for unprivileged user
Definition at line 382 of file capabilities.c.
References free(), mutex_t::lock, mutex, res, TRUE, and mutex_t::unlock.
Referenced by METHOD().
 {
     struct passwd *pwp;
     int res = -1;
 #ifdef HAVE_GETPWUID_R
     struct passwd pwd;
     size_t buflen = 1024;
     char *buf = NULL;
     while (TRUE)
     {
         buf = realloc(buf, buflen);
         if (getpwuid_r(this->uid, &pwd, buf, buflen, &pwp) == ERANGE)
         {
             buflen *= 2;
             continue;
         }
         if (pwp)
         {
             res = initgroups(pwp->pw_name, this->gid);
         }
         break;
     }
     free(buf);
 #else /* HAVE_GETPWUID_R */
     this->mutex->lock(this->mutex);
     pwp = getpwuid(this->uid);
     if (pwp)
     {
         res = initgroups(pwp->pw_name, this->gid);
     }
     this->mutex->unlock(this->mutex);
 #endif /* HAVE_GETPWUID_R */
     return res == 0;
 }
static bool keep_capability (private_capabilities_t * this, u_int cap) static
Keep the given capability if it is held by the current process. Returns FALSE, if this is not the case.
Definition at line 206 of file capabilities.c.
References TRUE.
Referenced by METHOD().
 {
 #ifdef CAPABILITIES_LIBCAP
     cap_set_flag(this->caps, CAP_EFFECTIVE, 1, &cap, CAP_SET);
     cap_set_flag(this->caps, CAP_INHERITABLE, 1, &cap, CAP_SET);
     cap_set_flag(this->caps, CAP_PERMITTED, 1, &cap, CAP_SET);
 #endif /* CAPABILITIES_LIBCAP */
 #ifdef CAPABILITIES_NATIVE
     int i = 0;
     if (cap >= 32)
     {
         i++;
         cap -= 32;
     }
     this->caps[i].effective |= 1 << cap;
     this->caps[i].permitted |= 1 << cap;
     this->caps[i].inheritable |= 1 << cap;
 #endif /* CAPABILITIES_NATIVE */
     return TRUE;
 }
METHOD (capabilities_t , keep , bool , private_capabilities_t * this, u_int cap)
Definition at line 228 of file capabilities.c.
References FALSE, has_capability(), ignore(), keep_capability(), and TRUE.
 {
     bool ignore = FALSE;
     if (!has_capability(this, cap, &ignore))
     {
         return FALSE;
     }
     else if (ignore)
     {   /* don't keep capabilities that are not required */
         return TRUE;
     }
     return keep_capability(this, cap);
 }
METHOD (capabilities_t , check , bool , private_capabilities_t * this, u_int cap)
Definition at line 244 of file capabilities.c.
References has_capability().
 {
     return has_capability(this, cap, NULL);
 }
METHOD (capabilities_t , get_uid , uid_t , private_capabilities_t * this)
Definition at line 250 of file capabilities.c.
 {
 #ifdef WIN32
     return this->uid;
 #else
     return this->uid ?: geteuid();
 #endif
 }
METHOD (capabilities_t , get_gid , gid_t , private_capabilities_t * this)
Definition at line 260 of file capabilities.c.
 {
 #ifdef WIN32
     return this->gid;
 #else
     return this->gid ?: getegid();
 #endif
 }
METHOD (capabilities_t , set_uid , void , private_capabilities_t * this, uid_t uid)
Definition at line 270 of file capabilities.c.
 {
     this->uid = uid;
 }
METHOD (capabilities_t , set_gid , void , private_capabilities_t * this, gid_t gid)
Definition at line 276 of file capabilities.c.
 {
     this->gid = gid;
 }
METHOD (capabilities_t , resolve_uid , bool , private_capabilities_t * this, char * username)
Definition at line 282 of file capabilities.c.
References DBG1, DBG_LIB, FALSE, free(), mutex_t::lock, mutex, strerror, TRUE, and mutex_t::unlock.
 {
 #ifndef WIN32
     struct passwd *pwp;
     int err;
 #ifdef HAVE_GETPWNAM_R
     struct passwd passwd;
     size_t buflen = 1024;
     char *buf = NULL;
     while (TRUE)
     {
         buf = realloc(buf, buflen);
         err = getpwnam_r(username, &passwd, buf, buflen, &pwp);
         if (err == ERANGE)
         {
             buflen *= 2;
             continue;
         }
         if (pwp)
         {
             this->uid = pwp->pw_uid;
         }
         break;
     }
     free(buf);
 #else /* HAVE GETPWNAM_R */
     this->mutex->lock(this->mutex);
     pwp = getpwnam(username);
     if (pwp)
     {
         this->uid = pwp->pw_uid;
     }
     err = errno;
     this->mutex->unlock(this->mutex);
 #endif /* HAVE GETPWNAM_R */
     if (pwp)
     {
         return TRUE;
     }
     DBG1(DBG_LIB, "resolving user '%s' failed: %s", username,
          err ? strerror(err) : "user not found");
 #endif /* !WIN32 */
     return FALSE;
 }
METHOD (capabilities_t , resolve_gid , bool , private_capabilities_t * this, char * groupname)
Definition at line 330 of file capabilities.c.
References DBG1, DBG_LIB, FALSE, free(), group, mutex_t::lock, mutex, strerror, TRUE, and mutex_t::unlock.
 {
 #ifndef WIN32
     struct group *grp;
     int err;
 #ifdef HAVE_GETGRNAM_R
     struct group group;
     size_t buflen = 1024;
     char *buf = NULL;
     while (TRUE)
     {
         buf = realloc(buf, buflen);
         err = getgrnam_r(groupname, &group, buf, buflen, &grp);
         if (err == ERANGE)
         {
             buflen *= 2;
             continue;
         }
         if (grp)
         {
             this->gid = grp->gr_gid;
         }
         break;
     }
     free(buf);
 #else /* HAVE_GETGRNAM_R */
     this->mutex->lock(this->mutex);
     grp = getgrnam(groupname);
     if (grp)
     {
         this->gid = grp->gr_gid;
     }
     err = errno;
     this->mutex->unlock(this->mutex);
 #endif /* HAVE_GETGRNAM_R */
     if (grp)
     {
         return TRUE;
     }
     DBG1(DBG_LIB, "resolving user '%s' failed: %s", groupname,
          err ? strerror(err) : "group not found");
 #endif /* !WIN32 */
     return FALSE;
 }
METHOD (capabilities_t , drop , bool , private_capabilities_t * this)
WIN32
Definition at line 420 of file capabilities.c.
References DBG1, DBG_LIB, FALSE, init_supplementary_groups(), and strerror.
 {
 #ifndef WIN32
 #ifdef HAVE_PRCTL
     prctl(PR_SET_KEEPCAPS, 1, 0, 0, 0);
 #endif
     if (this->uid && !init_supplementary_groups(this))
     {
         DBG1(DBG_LIB, "initializing supplementary groups for %u failed",
              this->uid);
         return FALSE;
     }
     if (this->gid && setgid(this->gid) != 0)
     {
         DBG1(DBG_LIB, "change to unprivileged group %u failed: %s",
              this->gid, strerror(errno));
         return FALSE;
     }
     if (this->uid && setuid(this->uid) != 0)
     {
         DBG1(DBG_LIB, "change to unprivileged user %u failed: %s",
              this->uid, strerror(errno));
         return FALSE;
     }
 #ifdef CAPABILITIES_LIBCAP
     if (cap_set_proc(this->caps) != 0)
     {
         DBG1(DBG_LIB, "dropping capabilities failed: %s", strerror(errno));
         return FALSE;
     }
 #endif /* CAPABILITIES_LIBCAP */
 #ifdef CAPABILITIES_NATIVE
     struct __user_cap_header_struct header = {
 #if defined(_LINUX_CAPABILITY_VERSION_3)
         .version = _LINUX_CAPABILITY_VERSION_3,
 #elif defined(_LINUX_CAPABILITY_VERSION_2)
         .version = _LINUX_CAPABILITY_VERSION_2,
 #elif defined(_LINUX_CAPABILITY_VERSION_1)
         .version = _LINUX_CAPABILITY_VERSION_1,
 #else
         .version = _LINUX_CAPABILITY_VERSION,
 #endif
     };
     if (capset(&header, this->caps) != 0)
     {
         DBG1(DBG_LIB, "dropping capabilities failed: %s", strerror(errno));
         return FALSE;
     }
 #endif /* CAPABILITIES_NATIVE */
 #ifdef CAPABILITIES
     DBG1(DBG_LIB, "dropped capabilities, running as uid %u, gid %u",
          geteuid(), getegid());
 #endif /* CAPABILITIES */
 #endif
     return TRUE;
 }
METHOD (capabilities_t , destroy , void , private_capabilities_t * this)
Definition at line 480 of file capabilities.c.
References mutex_t::destroy, free(), and mutex.
 {
 #ifdef EMULATE_R_FUNCS
     this->mutex->destroy(this->mutex);
 #endif /* EMULATE_R_FUNCS */
 #ifdef CAPABILITIES_LIBCAP
     cap_free(this->caps);
 #endif /* CAPABILITIES_LIBCAP */
     free(this);
 }