strongSwan: x509_pkcs10.c File Reference
x509_pkcs10.c File Reference
#include "x509_pkcs10.h"
#include <library.h>
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <credentials/keys/private_key.h>
#include <collections/linked_list.h>
#include <utils/identification.h>
Classes
struct private_x509_pkcs10_t
Macros
#define PKCS10_EXTN_ID 2
#define PKCS10_EXTN_CRITICAL 3
#define PKCS10_EXTN_VALUE 4
#define PKCS10_CERT_REQUEST_INFO 1
#define PKCS10_VERSION 2
#define PKCS10_SUBJECT 3
#define PKCS10_SUBJECT_PUBLIC_KEY_INFO 4
#define PKCS10_ATTR_TYPE 7
#define PKCS10_ATTR_VALUE 9
#define PKCS10_ALGORITHM 12
#define PKCS10_SIGNATURE 13
Typedefs
typedef struct
private_x509_pkcs10_t private_x509_pkcs10_t
Functions
void x509_parse_generalNames (chunk_t blob, int level0, bool implicit, linked_list_t *list)
chunk_t x509_build_subjectAltNames (linked_list_t *list)
METHOD (certificate_t, get_type, certificate_type_t, private_x509_pkcs10_t *this)
METHOD (certificate_t, get_subject, identification_t *, private_x509_pkcs10_t *this)
METHOD (certificate_t, has_subject, id_match_t, private_x509_pkcs10_t *this, identification_t *subject)
METHOD (certificate_t, issued_by, bool, private_x509_pkcs10_t *this, certificate_t *issuer, signature_scheme_t *schemep)
METHOD (certificate_t, get_public_key, public_key_t *, private_x509_pkcs10_t *this)
METHOD (certificate_t, get_validity, bool, private_x509_pkcs10_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_x509_pkcs10_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, equals, bool, private_x509_pkcs10_t *this, certificate_t *other)
METHOD (certificate_t, get_ref, certificate_t *, private_x509_pkcs10_t *this)
METHOD (pkcs10_t, get_challengePassword, chunk_t, private_x509_pkcs10_t *this)
METHOD (pkcs10_t, create_subjectAltName_enumerator, enumerator_t *, private_x509_pkcs10_t *this)
static bool parse_extension_request (private_x509_pkcs10_t *this, chunk_t blob, int level0)
static bool parse_challengePassword (private_x509_pkcs10_t *this, chunk_t blob, int level)
static bool parse_certificate_request (private_x509_pkcs10_t *this)
METHOD (certificate_t, destroy, void, private_x509_pkcs10_t *this)
static private_x509_pkcs10_t * create_empty (void)
static bool generate (private_x509_pkcs10_t *cert, private_key_t *sign_key, int digest_alg)
x509_pkcs10_t * x509_pkcs10_load (certificate_type_t type, va_list args)
x509_pkcs10_t * x509_pkcs10_gen (certificate_type_t type, va_list args)
Variables
static const asn1Object_t extensionRequestObjects []
static const asn1Object_t certificationRequestObjects []
Macro Definition Documentation
#define PKCS10_ALGORITHM 12
Definition at line 367 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
#define PKCS10_ATTR_TYPE 7
Definition at line 365 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
#define PKCS10_ATTR_VALUE 9
Definition at line 366 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
#define PKCS10_CERT_REQUEST_INFO 1
Definition at line 361 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
#define PKCS10_EXTN_CRITICAL 3
Definition at line 257 of file x509_pkcs10.c.
Referenced by parse_extension_request().
#define PKCS10_EXTN_ID 2
Definition at line 256 of file x509_pkcs10.c.
Referenced by parse_extension_request().
#define PKCS10_EXTN_VALUE 4
Definition at line 258 of file x509_pkcs10.c.
Referenced by parse_extension_request().
#define PKCS10_SIGNATURE 13
Definition at line 368 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
#define PKCS10_SUBJECT 3
Definition at line 363 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
#define PKCS10_SUBJECT_PUBLIC_KEY_INFO 4
Definition at line 364 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
#define PKCS10_VERSION 2
Definition at line 362 of file x509_pkcs10.c.
Referenced by parse_certificate_request().
Typedef Documentation
typedef struct private_x509_pkcs10_t private_x509_pkcs10_t
Definition at line 29 of file x509_pkcs10.c.
Function Documentation
static private_x509_pkcs10_t* create_empty (void) static
create an empty but initialized PKCS#10 certificate request
Definition at line 487 of file x509_pkcs10.c.
References INIT, and linked_list_create().
Referenced by x509_pkcs10_gen(), and x509_pkcs10_load().
 {
     private_x509_pkcs10_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .interface = {
                     .get_type = _get_type,
                     .get_subject = _get_subject,
                     .get_issuer = _get_subject,
                     .has_subject = _has_subject,
                     .has_issuer = _has_subject,
                     .issued_by = _issued_by,
                     .get_public_key = _get_public_key,
                     .get_validity = _get_validity,
                     .get_encoding = _get_encoding,
                     .equals = _equals,
                     .get_ref = _get_ref,
                     .destroy = _destroy,
                 },
                 .get_challengePassword = _get_challengePassword,
                 .create_subjectAltName_enumerator = _create_subjectAltName_enumerator,
             },
         },
         .subjectAltNames = linked_list_create(),
         .ref = 1,
     );
     return this;
 }
static bool generate (private_x509_pkcs10_t * cert, private_key_t * sign_key, int digest_alg) static
Generate and sign a new certificate request
Definition at line 522 of file x509_pkcs10.c.
References private_x509_pkcs10_t::algorithm, asn1_algorithmIdentifier(), asn1_bitstring(), asn1_build_known_oid(), ASN1_CONTEXT_C_0, ASN1_INTEGER_0, asn1_is_printablestring(), ASN1_PRINTABLESTRING, ASN1_SEQUENCE, ASN1_SET, asn1_simple_object(), ASN1_T61STRING, asn1_wrap(), attributes, private_x509_pkcs10_t::certificationRequestInfo, private_x509_pkcs10_t::challengePassword, challengePassword, chunk_empty, private_x509_pkcs10_t::encoding, FALSE, identification_t::get_encoding, public_key_t::get_encoding, private_key_t::get_public_key, private_key_t::get_type, hasher_signature_algorithm_to_oid(), chunk_t::len, OID_CHALLENGE_PASSWORD, OID_EXTENSION_REQUEST, OID_UNKNOWN, chunk_t::ptr, PUBKEY_SPKI_ASN1_DER, private_x509_pkcs10_t::public_key, scheme, private_key_t::sign, private_x509_pkcs10_t::signature, signature_scheme_from_oid(), private_x509_pkcs10_t::subject, subject, private_x509_pkcs10_t::subjectAltNames, subjectAltNames, TRUE, type, and x509_build_subjectAltNames().
Referenced by x509_pkcs10_gen().
 {
     chunk_t key_info, subjectAltNames, attributes;
     chunk_t extensionRequest  = chunk_empty;
     chunk_t challengePassword = chunk_empty;
     signature_scheme_t scheme;
     identification_t *subject;
     subject = cert->subject;
     cert->public_key = sign_key->get_public_key(sign_key);
     /* select signature scheme */
     cert->algorithm = hasher_signature_algorithm_to_oid(digest_alg,
                                     sign_key->get_type(sign_key));
     if (cert->algorithm == OID_UNKNOWN)
     {
         return FALSE;
     }
     scheme = signature_scheme_from_oid(cert->algorithm);
     if (!cert->public_key->get_encoding(cert->public_key,
                                         PUBKEY_SPKI_ASN1_DER, &key_info))
     {
         return FALSE;
     }
     /* encode subjectAltNames */
     subjectAltNames = x509_build_subjectAltNames(cert->subjectAltNames);
     if (subjectAltNames.ptr)
     {
         extensionRequest = asn1_wrap(ASN1_SEQUENCE, "mm",
                     asn1_build_known_oid(OID_EXTENSION_REQUEST),
                     asn1_wrap(ASN1_SET, "m",
                         asn1_wrap(ASN1_SEQUENCE, "m", subjectAltNames)
                     ));
     }
     if (cert->challengePassword.len > 0)
     {
         asn1_t type = asn1_is_printablestring(cert->challengePassword) ?
                                 ASN1_PRINTABLESTRING : ASN1_T61STRING;
         challengePassword = asn1_wrap(ASN1_SEQUENCE, "mm",
                     asn1_build_known_oid(OID_CHALLENGE_PASSWORD),
                     asn1_wrap(ASN1_SET, "m",
                         asn1_simple_object(type, cert->challengePassword)
                     )
             );
     }
     attributes = asn1_wrap(ASN1_CONTEXT_C_0, "mm", extensionRequest,
                                                    challengePassword);
     cert->certificationRequestInfo = asn1_wrap(ASN1_SEQUENCE, "ccmm",
                             ASN1_INTEGER_0,
                             subject->get_encoding(subject),
                             key_info,
                             attributes);
     if (!sign_key->sign(sign_key, scheme, cert->certificationRequestInfo,
                         &cert->signature))
     {
         return FALSE;
     }
     cert->encoding = asn1_wrap(ASN1_SEQUENCE, "cmm",
                                cert->certificationRequestInfo,
                                asn1_algorithmIdentifier(cert->algorithm),
                                asn1_bitstring("c", cert->signature));
     return TRUE;
 }
METHOD (certificate_t , get_type , certificate_type_t , private_x509_pkcs10_t * this)
Definition at line 107 of file x509_pkcs10.c.
References CERT_PKCS10_REQUEST.
 {
     return CERT_PKCS10_REQUEST;
 }
METHOD (certificate_t , get_subject , identification_t * , private_x509_pkcs10_t * this)
Definition at line 113 of file x509_pkcs10.c.
References subject.
 {
     return this->subject;
 }
METHOD (certificate_t , has_subject , id_match_t , private_x509_pkcs10_t * this, identification_t * subject)
Definition at line 119 of file x509_pkcs10.c.
References identification_t::matches.
 {
     return this->subject->matches(this->subject, subject);
 }
METHOD (certificate_t , issued_by , bool , private_x509_pkcs10_t * this, certificate_t * issuer, signature_scheme_t * schemep)
Definition at line 125 of file x509_pkcs10.c.
References algorithm, FALSE, key, public_key, scheme, SIGN_UNKNOWN, signature_scheme_from_oid(), TRUE, valid, and public_key_t::verify.
 {
     public_key_t *key;
     signature_scheme_t scheme;
     bool valid;
     if (&this->public.interface.interface != issuer)
     {
         return FALSE;
     }
     if (this->self_signed)
     {
         return TRUE;
     }
     /* determine signature scheme */
     scheme = signature_scheme_from_oid(this->algorithm);
     if (scheme == SIGN_UNKNOWN)
     {
         return FALSE;
     }
     /* get the public key contained in the certificate request */
     key = this->public_key;
     if (!key)
     {
         return FALSE;
     }
     valid = key->verify(key, scheme, this->certificationRequestInfo,
                         this->signature);
     if (valid && schemep)
     {
         *schemep = scheme;
     }
     return valid;
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_x509_pkcs10_t * this)
Definition at line 164 of file x509_pkcs10.c.
References public_key_t::get_ref, and public_key.
 {
     this->public_key->get_ref(this->public_key);
     return this->public_key;
 }
METHOD (certificate_t , get_validity , bool , private_x509_pkcs10_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 171 of file x509_pkcs10.c.
References TRUE.
 {
     if (not_before)
     {
         *not_before = 0;
     }
     if (not_after)
     {
         *not_after = ~0;
     }
     return TRUE;
 }
METHOD (certificate_t , get_encoding , bool , private_x509_pkcs10_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 186 of file x509_pkcs10.c.
References CERT_ASN1_DER, chunk_clone, CRED_PART_END, CRED_PART_PKCS10_ASN1_DER, cred_encoding_t::encode, library_t::encoding, lib, and TRUE.
 {
     if (type == CERT_ASN1_DER)
     {
         *encoding = chunk_clone(this->encoding);
         return TRUE;
     }
     return lib->encoding->encode(lib->encoding, type, NULL, encoding,
                     CRED_PART_PKCS10_ASN1_DER, this->encoding, CRED_PART_END);
 }
METHOD (certificate_t , equals , bool , private_x509_pkcs10_t * this, certificate_t * other)
Definition at line 198 of file x509_pkcs10.c.
References CERT_ASN1_DER, CERT_PKCS10_REQUEST, chunk_equals(), encoding, equals(), certificate_t::equals, FALSE, free(), certificate_t::get_encoding, certificate_t::get_type, chunk_t::ptr, and TRUE.
 {
     chunk_t encoding;
     bool equal;
     if (this == (private_x509_pkcs10_t*)other)
     {
         return TRUE;
     }
     if (other->get_type(other) != CERT_PKCS10_REQUEST)
     {
         return FALSE;
     }
     if (other->equals == (void*)equals)
     {   /* skip allocation if we have the same implementation */
         return chunk_equals(this->encoding, ((private_x509_pkcs10_t*)other)->encoding);
     }
     if (!other->get_encoding(other, CERT_ASN1_DER, &encoding))
     {
         return FALSE;
     }
     equal = chunk_equals(this->encoding, encoding);
     free(encoding.ptr);
     return equal;
 }
METHOD (certificate_t , get_ref , certificate_t * , private_x509_pkcs10_t * this)
Definition at line 225 of file x509_pkcs10.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.interface.interface;
 }
METHOD (pkcs10_t , get_challengePassword , chunk_t , private_x509_pkcs10_t * this)
Definition at line 232 of file x509_pkcs10.c.
References challengePassword.
 {
     return this->challengePassword;
 }
METHOD (pkcs10_t , create_subjectAltName_enumerator , enumerator_t * , private_x509_pkcs10_t * this)
Definition at line 238 of file x509_pkcs10.c.
References linked_list_t::create_enumerator, and subjectAltNames.
 {
     return this->subjectAltNames->create_enumerator(this->subjectAltNames);
 }
METHOD (certificate_t , destroy , void , private_x509_pkcs10_t * this)
Definition at line 464 of file x509_pkcs10.c.
References challengePassword, chunk_free(), destroy(), DESTROY_IF, linked_list_t::destroy_offset, encoding, free(), public_key, ref_put(), subject, and subjectAltNames.
 {
     if (ref_put(&this->ref))
     {
         this->subjectAltNames->destroy_offset(this->subjectAltNames,
                                     offsetof(identification_t, destroy));
         DESTROY_IF(this->subject);
         DESTROY_IF(this->public_key);
         chunk_free(&this->encoding);
         if (!this->parsed)
         {   /* only parsed certificate requests point these fields to "encoded" */
             chunk_free(&this->certificationRequestInfo);
             chunk_free(&this->challengePassword);
             chunk_free(&this->signature);
         }
         free(this);
     }
 }
static bool parse_certificate_request (private_x509_pkcs10_t * this) static
Parses a PKCS#10 certificate request
Definition at line 373 of file x509_pkcs10.c.
References algorithm, asn1_known_oid(), asn1_parse_algorithmIdentifier(), asn1_parser_create(), BUILD_BLOB_ASN1_DER, BUILD_END, chunk_skip(), credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, DBG1, DBG2, DBG_ASN, DBG_LIB, asn1_parser_t::destroy, encoding, end, FALSE, asn1_parser_t::get_level, ID_DER_ASN1_DN, identification_create_from_encoding(), asn1_parser_t::iterate, KEY_ANY, len, lib, OID_CHALLENGE_PASSWORD, OID_EXTENSION_REQUEST, OID_UNKNOWN, parse_challengePassword(), parse_extension_request(), parser, PKCS10_ALGORITHM, PKCS10_ATTR_TYPE, PKCS10_ATTR_VALUE, PKCS10_CERT_REQUEST_INFO, PKCS10_SIGNATURE, PKCS10_SUBJECT, PKCS10_SUBJECT_PUBLIC_KEY_INFO, PKCS10_VERSION, public_key, subject, asn1_parser_t::success, and TRUE.
Referenced by x509_pkcs10_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int attr_oid = OID_UNKNOWN;
     bool success = FALSE;
     parser = asn1_parser_create(certificationRequestObjects, this->encoding);
     while (parser->iterate(parser, &objectID, &object))
     {
         u_int level = parser->get_level(parser)+1;
         switch (objectID)
         {
             case PKCS10_CERT_REQUEST_INFO:
                 this->certificationRequestInfo = object;
                 break;
             case PKCS10_VERSION:
                 if (object.len > 0 && *object.ptr != 0)
                 {
                     DBG1(DBG_ASN, "PKCS#10 certificate request format is "
                          "not version 1");
                     goto end;
                 }
                 break;
             case PKCS10_SUBJECT:
                 this->subject = identification_create_from_encoding(ID_DER_ASN1_DN, object);
                 DBG2(DBG_ASN, "  '%Y'", this->subject);
                 break;
             case PKCS10_SUBJECT_PUBLIC_KEY_INFO:
                 this->public_key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY,
                         KEY_ANY, BUILD_BLOB_ASN1_DER, object, BUILD_END);
                 if (this->public_key == NULL)
                 {
                     goto end;
                 }
                 break;
             case PKCS10_ATTR_TYPE:
                 attr_oid = asn1_known_oid(object);
                 break;
             case PKCS10_ATTR_VALUE:
                 switch (attr_oid)
                 {
                     case OID_EXTENSION_REQUEST:
                         if (!parse_extension_request(this, object, level))
{
                             goto end;
                         }
                         break;
                     case OID_CHALLENGE_PASSWORD:
                         if (!parse_challengePassword(this, object, level))
{
                             goto end;
                         }
                         break;
                     default:
                         break;
                 }
                 break;
             case PKCS10_ALGORITHM:
                 this->algorithm = asn1_parse_algorithmIdentifier(object, level, NULL);
                 break;
             case PKCS10_SIGNATURE:
                 this->signature = chunk_skip(object, 1);
                 break;
             default:
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     if (success)
     {
         /* check if the certificate request is self-signed */
         if (issued_by(this, &this->public.interface.interface, NULL))
         {
             this->self_signed = TRUE;
         }
         else
         {
             DBG1(DBG_LIB, "certificate request is not self-signed");
             success = FALSE;
         }
     }
     return success;
 }
static bool parse_challengePassword (private_x509_pkcs10_t * this, chunk_t blob, int level) static
Parses a PKCS#10 challenge password
Definition at line 313 of file x509_pkcs10.c.
References ASN1_IA5STRING, ASN1_INVALID_LENGTH, asn1_length(), DBG1, DBG2, DBG4, DBG_ASN, FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by parse_certificate_request().
 {
     char tag;
     if (blob.len < 2)
     {
         DBG1(DBG_ASN, "L%d - challengePassword:  ASN.1 object smaller "
              "than 2 octets", level);
         return FALSE;
     }
     tag = *blob.ptr;
     if (tag < ASN1_UTF8STRING || tag > ASN1_IA5STRING)
     {
         DBG1(DBG_ASN, "L%d - challengePassword:  ASN.1 object is not "
              "a character string", level);
         return FALSE;
     }
     if (asn1_length(&blob) == ASN1_INVALID_LENGTH)
     {
         DBG1(DBG_ASN, "L%d - challengePassword:  ASN.1 object has an "
              "invalid length", level);
         return FALSE;
     }
     DBG2(DBG_ASN, "L%d - challengePassword:", level);
     DBG4(DBG_ASN, "  '%.*s'", (int)blob.len, blob.ptr);
     return TRUE;
 }
static bool parse_extension_request (private_x509_pkcs10_t * this, chunk_t blob, int level0) static
Parses a PKCS#10 extension request
Definition at line 263 of file x509_pkcs10.c.
References asn1_known_oid(), asn1_parser_create(), DBG2, DBG_ASN, asn1_parser_t::destroy, FALSE, asn1_parser_t::get_level, asn1_parser_t::iterate, OID_SUBJECT_ALT_NAME, OID_UNKNOWN, parser, PKCS10_EXTN_CRITICAL, PKCS10_EXTN_ID, PKCS10_EXTN_VALUE, asn1_parser_t::set_top_level, subjectAltNames, asn1_parser_t::success, and x509_parse_generalNames().
Referenced by parse_certificate_request().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int extn_oid = OID_UNKNOWN;
     bool success = FALSE;
     bool critical;
     parser = asn1_parser_create(extensionRequestObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         u_int level = parser->get_level(parser)+1;
         switch (objectID)
         {
             case PKCS10_EXTN_ID:
                 extn_oid = asn1_known_oid(object);
                 break;
             case PKCS10_EXTN_CRITICAL:
                 critical = object.len && *object.ptr;
                 DBG2(DBG_ASN, "  %s", critical ? "TRUE" : "FALSE");
                 break;
             case PKCS10_EXTN_VALUE:
             {
                 switch (extn_oid)
                 {
                     case OID_SUBJECT_ALT_NAME:
                         x509_parse_generalNames(object, level, FALSE,
                                                 this->subjectAltNames);
                         break;
                     default:
                         break;
                 }
                 break;
             }
             default:
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     return success;
 }
chunk_t x509_build_subjectAltNames (linked_list_t * list)
Encode a linked list of subjectAltNames
Definition at line 1927 of file x509_cert.c.
References asn1_build_known_oid(), ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_wrap(), build_generalName(), chunk_cat, chunk_empty, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, id, name, OID_SUBJECT_ALT_NAME, and subjectAltNames.
Referenced by generate().
 {
     chunk_t subjectAltNames = chunk_empty, name;
     enumerator_t *enumerator;
     identification_t *id;
     if (list->get_count(list) == 0)
     {
         return chunk_empty;
     }
     enumerator = list->create_enumerator(list);
     while (enumerator->enumerate(enumerator, &id))
     {
         name = build_generalName(id);
         subjectAltNames = chunk_cat("mm", subjectAltNames, name);
     }
     enumerator->destroy(enumerator);
     return asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_build_known_oid(OID_SUBJECT_ALT_NAME),
                         asn1_wrap(ASN1_OCTET_STRING, "m",
                             asn1_wrap(ASN1_SEQUENCE, "m", subjectAltNames)
                         )
                      );
 }
void x509_parse_generalNames (chunk_t blob, int level0, bool implicit, linked_list_t * list)
Imported from x509_cert.c
Extracts one or several GNs and puts them into a chained list
Definition at line 505 of file x509_cert.c.
References asn1_parser_create(), asn1_parser_t::destroy, FALSE, GENERAL_NAMES_GN, asn1_parser_t::get_level, linked_list_t::insert_last, asn1_parser_t::iterate, parse_generalName(), parser, asn1_parser_t::set_flags, and asn1_parser_t::set_top_level.
Referenced by parse_certificate(), parse_extension_request(), and x509_parse_crlDistributionPoints().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     parser = asn1_parser_create(generalNamesObjects, blob);
     parser->set_top_level(parser, level0);
     parser->set_flags(parser, implicit, FALSE);
     while (parser->iterate(parser, &objectID, &object))
     {
         if (objectID == GENERAL_NAMES_GN)
         {
             identification_t *gn = parse_generalName(object,
                                             parser->get_level(parser)+1);
             if (gn)
             {
                 list->insert_last(list, (void *)gn);
             }
         }
     }
     parser->destroy(parser);
 }
Variable Documentation
const asn1Object_t certificationRequestObjects[] static
Initial value:
= {
    { 0, "certificationRequest",       ASN1_SEQUENCE,    ASN1_OBJ  },
    { 1,   "certificationRequestInfo", ASN1_SEQUENCE,    ASN1_OBJ  },
    { 2,     "version",                ASN1_INTEGER,     ASN1_BODY },
    { 2,     "subject",                ASN1_SEQUENCE,    ASN1_OBJ  },
    { 2,     "subjectPublicKeyInfo",   ASN1_SEQUENCE,    ASN1_RAW  },
    { 2,     "attributes",             ASN1_CONTEXT_C_0, ASN1_LOOP },
    { 3,       "attribute",            ASN1_SEQUENCE,    ASN1_NONE },
    { 4,         "type",               ASN1_OID,         ASN1_BODY },
    { 4,         "values",             ASN1_SET,         ASN1_LOOP },
    { 5,           "value",            ASN1_EOC,         ASN1_RAW  },
    { 4,         "end loop",           ASN1_EOC,         ASN1_END  },
    { 2,     "end loop",               ASN1_EOC,         ASN1_END  },
    { 1,   "signatureAlgorithm",       ASN1_EOC,         ASN1_RAW  },
    { 1,    "signature",               ASN1_BIT_STRING,  ASN1_BODY },
    { 0, "exit",                       ASN1_EOC,         ASN1_EXIT }
}
ASN.1 definition of a PKCS#10 certificate request
Definition at line 344 of file x509_pkcs10.c.
const asn1Object_t extensionRequestObjects[] static
Initial value:
= {
    { 0, "extensions",   ASN1_SEQUENCE,     ASN1_LOOP           },
    { 1,   "extension",   ASN1_SEQUENCE,     ASN1_NONE          },
    { 2,     "extnID",    ASN1_OID,          ASN1_BODY          },
    { 2,     "critical",  ASN1_BOOLEAN,      ASN1_DEF|ASN1_BODY },
    { 2,     "extnValue", ASN1_OCTET_STRING, ASN1_BODY          },
    { 1, "end loop",      ASN1_EOC,          ASN1_END           },
    { 0, "exit",          ASN1_EOC,          ASN1_EXIT          }
}
ASN.1 definition of a PKCS#10 extension request
Definition at line 247 of file x509_pkcs10.c.