strongSwan: test_certnames.c File Reference
test_certnames.c File Reference
#include "test_suite.h"
#include <asn1/asn1.h>
#include <credentials/sets/mem_cred.h>
#include <credentials/certificates/x509.h>
Functions
static certificate_t * create_cert (certificate_t *ca, char *subject, char *san, x509_flag_t flags, identification_t *permitted, identification_t *excluded)
static bool check_trust (identification_t *subject)
START_SETUP (setup)
END_SETUP START_TEARDOWN (teardown)
START_TEST (test_permitted_dn)
START_TEST (test_permitted_san)
START_TEST (test_excluded_dn)
START_TEST (test_excluded_san)
START_TEST (test_permitted_dninh)
START_TEST (test_excluded_dninh)
END_TEST Suite * certnames_suite_create ()
Variables
static char keydata []
static mem_cred_t * creds
struct {
char * constraint
char * subject
bool good
} permitted_dn []
struct {
id_type_t ctype
char * cdata
char * subject
bool good
} permitted_san []
struct {
char * constraint
char * subject
bool good
} excluded_dn []
struct {
id_type_t ctype
char * cdata
char * subject
bool good
} excluded_san []
struct {
char * caconst
char * imconst
char * subject
bool good
} permitted_dninh []
struct {
char * caconst
char * imconst
char * subject
bool good
} excluded_dninh []
Function Documentation
END_TEST Suite* certnames_suite_create ()
Definition at line 360 of file test_certnames.c.
References countof, excluded_dn, excluded_dninh, excluded_san, permitted_dn, permitted_dninh, permitted_san, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_checked_fixture, tcase_add_loop_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("certnames");
     tc = tcase_create("permitted DN name constraints");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_loop_test(tc, test_permitted_dn, 0, countof(permitted_dn));
     suite_add_tcase(s, tc);
     tc = tcase_create("permitted subjectAltName constraints");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_loop_test(tc, test_permitted_san, 0, countof(permitted_san));
     suite_add_tcase(s, tc);
     tc = tcase_create("excluded DN constraints");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_loop_test(tc, test_excluded_dn, 0, countof(excluded_dn));
     suite_add_tcase(s, tc);
     tc = tcase_create("excluded subjectAltName constraints");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_loop_test(tc, test_excluded_san, 0, countof(excluded_san));
     suite_add_tcase(s, tc);
     tc = tcase_create("permitted DN name constraint inherit");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_loop_test(tc, test_permitted_dninh, 0, countof(permitted_dninh));
     suite_add_tcase(s, tc);
     tc = tcase_create("excluded DN name constraint inherit");
     tcase_add_checked_fixture(tc, setup, teardown);
     tcase_add_loop_test(tc, test_excluded_dninh, 0, countof(excluded_dninh));
     suite_add_tcase(s, tc);
     return s;
 }
static bool check_trust (identification_t * subject) static
Check if a certificate with given subject has a valid trustchain
Definition at line 127 of file test_certnames.c.
References cert, credential_manager_t::create_trusted_enumerator, library_t::credmgr, enumerator_t::destroy, enumerator_t::enumerate, FALSE, KEY_ANY, and lib.
Referenced by START_TEST().
 {
     enumerator_t *certs;
     certificate_t *cert;
     bool trusted;
     certs = lib->credmgr->create_trusted_enumerator(lib->credmgr, KEY_ANY,
                                                     subject, FALSE);
     trusted = certs->enumerate(certs, &cert, NULL);
     certs->destroy(certs);
     return trusted;
 }
static certificate_t* create_cert (certificate_t * ca, char * subject, char * san, x509_flag_t flags, identification_t * permitted, identification_t * excluded) static
Issue a certificate with permitted/excluded name constraints
Definition at line 70 of file test_certnames.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_EXCLUDED_NAME_CONSTRAINTS, BUILD_PERMITTED_NAME_CONSTRAINTS, BUILD_PUBLIC_KEY, BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, BUILD_SUBJECT, BUILD_SUBJECT_ALTNAMES, BUILD_X509_FLAG, cert, CERT_X509, chunk_from_thing, ck_assert, credential_factory_t::create, CRED_CERTIFICATE, CRED_PRIVATE_KEY, library_t::creds, private_key_t::destroy, public_key_t::destroy, destroy(), linked_list_t::destroy_offset, private_key_t::get_public_key, id, identification_create_from_string(), linked_list_t::insert_last, KEY_RSA, keydata, lib, and linked_list_create().
Referenced by START_TEST().
 {
     private_key_t *privkey;
     public_key_t *pubkey;
     certificate_t *cert;
     identification_t *id;
     linked_list_t *plist, *elist, *sans;
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
                                  BUILD_BLOB_ASN1_DER, chunk_from_thing(keydata),
                                  BUILD_END);
     ck_assert(privkey);
     pubkey = privkey->get_public_key(privkey);
     ck_assert(pubkey);
     plist = linked_list_create();
     if (permitted)
     {
         plist->insert_last(plist, permitted);
     }
     elist = linked_list_create();
     if (excluded)
     {
         elist->insert_last(elist, excluded);
     }
     sans = linked_list_create();
     if (san)
     {
         id = identification_create_from_string(san);
         sans->insert_last(sans, id);
     }
     id = identification_create_from_string(subject);
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                         BUILD_SIGNING_KEY, privkey,
                         BUILD_PUBLIC_KEY, pubkey,
                         BUILD_SUBJECT, id,
                         BUILD_X509_FLAG, flags,
                         BUILD_SIGNING_CERT, ca,
                         BUILD_SUBJECT_ALTNAMES, sans,
                         BUILD_PERMITTED_NAME_CONSTRAINTS, plist,
                         BUILD_EXCLUDED_NAME_CONSTRAINTS, elist,
                         BUILD_END);
     ck_assert(cert);
     id->destroy(id);
     sans->destroy_offset(sans, offsetof(identification_t, destroy));
     plist->destroy_offset(plist, offsetof(identification_t, destroy));
     elist->destroy_offset(elist, offsetof(identification_t, destroy));
     privkey->destroy(privkey);
     pubkey->destroy(pubkey);
     return cert;
 }
START_SETUP (setup)
Definition at line 143 of file test_certnames.c.
References credential_manager_t::add_set, library_t::credmgr, lib, mem_cred_create(), and mem_cred_t::set.
 {
     creds = mem_cred_create();
     lib->credmgr->add_set(lib->credmgr, &creds->set);
 }
END_SETUP START_TEARDOWN (teardown)
Definition at line 150 of file test_certnames.c.
References CERT_ANY, library_t::credmgr, mem_cred_t::destroy, credential_manager_t::flush_cache, lib, credential_manager_t::remove_set, and mem_cred_t::set.
 {
     lib->credmgr->remove_set(lib->credmgr, &creds->set);
     creds->destroy(creds);
     lib->credmgr->flush_cache(lib->credmgr, CERT_ANY);
 }
START_TEST (test_permitted_dn)
Definition at line 170 of file test_certnames.c.
References mem_cred_t::add_cert, check_trust(), ck_assert, constraint, create_cert(), FALSE, certificate_t::get_subject, good, id, identification_create_from_string(), permitted_dn, subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     identification_t *id;
     id = identification_create_from_string(permitted_dn[_i].constraint);
     ca = create_cert(NULL, "C=CH, O=strongSwan, CN=CA", NULL, X509_CA, id, NULL);
     id = identification_create_from_string(permitted_dn[_i].constraint);
     im = create_cert(ca, "C=CH, O=strongSwan, CN=IM", NULL, X509_CA, id, NULL);
     sj = create_cert(im, permitted_dn[_i].subject, NULL, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_trust(sj->get_subject(sj)) == permitted_dn[_i].good);
 }
START_TEST (test_permitted_san)
Definition at line 212 of file test_certnames.c.
References mem_cred_t::add_cert, cdata, check_trust(), chunk_from_str, ck_assert, create_cert(), ctype, FALSE, certificate_t::get_subject, good, id, identification_create_from_encoding(), permitted_san, subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *sj;
     identification_t *id;
     id = identification_create_from_encoding(permitted_san[_i].ctype,
                                     chunk_from_str(permitted_san[_i].cdata));
     ca = create_cert(NULL, "CN=CA", NULL, X509_CA, id, NULL);
     sj = create_cert(ca, "CN=SJ", permitted_san[_i].subject, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_trust(sj->get_subject(sj)) == permitted_san[_i].good);
 }
START_TEST (test_excluded_dn)
Definition at line 241 of file test_certnames.c.
References mem_cred_t::add_cert, check_trust(), ck_assert, constraint, create_cert(), excluded_dn, FALSE, certificate_t::get_subject, good, id, identification_create_from_string(), subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     identification_t *id;
     id = identification_create_from_string(excluded_dn[_i].constraint);
     ca = create_cert(NULL, "C=CH, O=strongSwan, CN=CA", NULL, X509_CA, NULL, id);
     id = identification_create_from_string(excluded_dn[_i].constraint);
     im = create_cert(ca, "C=CH, O=strongSwan, CN=IM", NULL, X509_CA, NULL, id);
     sj = create_cert(im, excluded_dn[_i].subject, NULL, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_trust(sj->get_subject(sj)) == excluded_dn[_i].good);
 }
START_TEST (test_excluded_san)
Definition at line 283 of file test_certnames.c.
References mem_cred_t::add_cert, cdata, check_trust(), chunk_from_str, ck_assert, create_cert(), ctype, excluded_san, FALSE, certificate_t::get_subject, good, id, identification_create_from_encoding(), subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *sj;
     identification_t *id;
     id = identification_create_from_encoding(excluded_san[_i].ctype,
                                     chunk_from_str(excluded_san[_i].cdata));
     ca = create_cert(NULL, "CN=CA", NULL, X509_CA, NULL, id);
     sj = create_cert(ca, "CN=SJ", excluded_san[_i].subject, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_trust(sj->get_subject(sj)) == excluded_san[_i].good);
 }
START_TEST (test_permitted_dninh)
Definition at line 311 of file test_certnames.c.
References mem_cred_t::add_cert, caconst, check_trust(), ck_assert, create_cert(), FALSE, certificate_t::get_subject, good, id, identification_create_from_string(), imconst, permitted_dninh, subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     identification_t *id;
     id = identification_create_from_string(permitted_dninh[_i].caconst);
     ca = create_cert(NULL, "C=CH, O=strongSwan, CN=CA", NULL, X509_CA, id, NULL);
     id = identification_create_from_string(permitted_dninh[_i].imconst);
     im = create_cert(ca, "C=CH, O=strongSwan, CN=IM", NULL, X509_CA, id, NULL);
     sj = create_cert(im, permitted_dninh[_i].subject, NULL, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_trust(sj->get_subject(sj)) == permitted_dninh[_i].good);
 }
START_TEST (test_excluded_dninh)
Definition at line 341 of file test_certnames.c.
References mem_cred_t::add_cert, caconst, check_trust(), ck_assert, create_cert(), excluded_dninh, FALSE, certificate_t::get_subject, good, id, identification_create_from_string(), imconst, subject, TRUE, and X509_CA.
 {
     certificate_t *ca, *im, *sj;
     identification_t *id;
     id = identification_create_from_string(excluded_dninh[_i].caconst);
     ca = create_cert(NULL, "C=CH, O=strongSwan, CN=CA", NULL, X509_CA, NULL, id);
     id = identification_create_from_string(excluded_dninh[_i].imconst);
     im = create_cert(ca, "C=DE, CN=IM", NULL, X509_CA, NULL, id);
     sj = create_cert(im, excluded_dninh[_i].subject, NULL, 0, NULL, NULL);
     creds->add_cert(creds, TRUE, ca);
     creds->add_cert(creds, FALSE, im);
     creds->add_cert(creds, FALSE, sj);
     ck_assert(check_trust(sj->get_subject(sj)) == excluded_dninh[_i].good);
 }
Variable Documentation
char* caconst
Definition at line 301 of file test_certnames.c.
Referenced by START_TEST().
char* cdata
Definition at line 191 of file test_certnames.c.
Referenced by START_TEST().
char* constraint
Definition at line 159 of file test_certnames.c.
Referenced by check_name_constraints(), name_constraint_inherited(), START_TEST(), and x509_cert_gen().
mem_cred_t* creds static
Definition at line 141 of file test_certnames.c.
id_type_t ctype
Definition at line 190 of file test_certnames.c.
Referenced by START_TEST().
END_TEST { ... } excluded_dn[]
Initial value:
= {
    { "C=CH, O=another", "C=CH, O=strongSwan, CN=tester", TRUE },
    { "C=CH, O=another", "C=CH, O=anot", TRUE },
    { "C=CH, O=another", "C=CH, O=anot, CN=tester", TRUE },
    { "C=CH, O=another", "C=CH, O=another, CN=tester", FALSE },
    { "C=CH, O=another", "C=CH, CN=tester, O=another", TRUE },
}
Referenced by certnames_suite_create(), and START_TEST().
END_TEST { ... } excluded_dninh[]
Initial value:
= {
    { "C=CH, O=strongSwan", "C=CH", "C=DE", TRUE },
    { "C=CH, O=strongSwan", "C=DE", "C=CH", FALSE },
    { "C=CH", "C=CH, O=strongSwan", "C=CH, O=strongSwan, CN=tester", FALSE },
}
Referenced by certnames_suite_create(), and START_TEST().
END_TEST { ... } excluded_san[]
Initial value:
= {
    { ID_FQDN, ".strongswan.org", "test.strongswan.org", FALSE },
    { ID_FQDN, "strongswan.org", "test.strongswan.org", FALSE },
    { ID_FQDN, "a.b.c.strongswan.org", "d.a.b.c.strongswan.org", FALSE },
    { ID_FQDN, "a.b.c.strongswan.org", "a.b.c.d.strongswan.org", TRUE },
    { ID_FQDN, "strongswan.org", "strongswan.org.com", TRUE },
    { ID_FQDN, ".strongswan.org", "strongswan.org", TRUE },
    { ID_FQDN, "strongswan.org", "nostrongswan.org", TRUE },
    { ID_FQDN, "strongswan.org", "swan.org", TRUE },
    { ID_FQDN, "strongswan.org", "swan.org", TRUE },
    { ID_RFC822_ADDR, "tester@strongswan.org", "tester@strongswan.org", FALSE },
    { ID_RFC822_ADDR, "tester@strongswan.org", "atester@strongswan.org", TRUE },
    { ID_RFC822_ADDR, "strongswan.org", "tester@strongswan.org", FALSE },
    { ID_RFC822_ADDR, "strongswan.org", "tester@test.strongswan.org", TRUE },
    { ID_RFC822_ADDR, ".strongswan.org", "tester@test.strongswan.org", FALSE },
    { ID_RFC822_ADDR, ".strongswan.org", "tester@strongswan.org", TRUE },
}
Referenced by certnames_suite_create(), and START_TEST().
bool good
Definition at line 161 of file test_certnames.c.
Referenced by chunk_write(), iface_control(), METHOD(), and START_TEST().
char* imconst
Definition at line 302 of file test_certnames.c.
Referenced by START_TEST().
char keydata[] static
RSA private key, so we don't have to generate one
Definition at line 25 of file test_certnames.c.
Referenced by create_cert(), and main().
END_TEARDOWN { ... } permitted_dn[]
Initial value:
= {
    { "C=CH, O=strongSwan", "C=CH, O=strongSwan, CN=tester", TRUE },
    { "C=CH, O=strongSwan", "C=CH, O=strong", FALSE },
    { "C=CH, O=strongSwan", "C=CH, O=strong, CN=tester", FALSE },
    { "C=CH, O=strongSwan", "C=CH, O=another, CN=tester", FALSE },
    { "C=CH, O=strongSwan", "C=CH, CN=tester, O=strongSwan", FALSE },
}
Referenced by certnames_suite_create(), and START_TEST().
END_TEST { ... } permitted_dninh[]
Initial value:
= {
    { "C=CH", "C=CH, O=strongSwan", "C=CH, O=strongSwan, CN=tester", TRUE },
    { "C=CH", "C=DE, O=strongSwan", "C=CH, O=strongSwan, CN=tester", FALSE },
    { "C=CH, O=strongSwan", "C=CH", "C=CH", FALSE },
}
Referenced by certnames_suite_create(), and START_TEST().
END_TEST { ... } permitted_san[]
Initial value:
= {
    { ID_FQDN, ".strongswan.org", "test.strongswan.org", TRUE },
    { ID_FQDN, "strongswan.org", "test.strongswan.org", TRUE },
    { ID_FQDN, "a.b.c.strongswan.org", "d.a.b.c.strongswan.org", TRUE },
    { ID_FQDN, "a.b.c.strongswan.org", "a.b.c.d.strongswan.org", FALSE },
    { ID_FQDN, "strongswan.org", "strongswan.org.com", FALSE },
    { ID_FQDN, ".strongswan.org", "strongswan.org", FALSE },
    { ID_FQDN, "strongswan.org", "nostrongswan.org", FALSE },
    { ID_FQDN, "strongswan.org", "swan.org", FALSE },
    { ID_FQDN, "strongswan.org", "swan.org", FALSE },
    { ID_RFC822_ADDR, "tester@strongswan.org", "tester@strongswan.org", TRUE },
    { ID_RFC822_ADDR, "tester@strongswan.org", "atester@strongswan.org", FALSE },
    { ID_RFC822_ADDR, "strongswan.org", "tester@strongswan.org", TRUE },
    { ID_RFC822_ADDR, "strongswan.org", "tester@test.strongswan.org", FALSE },
    { ID_RFC822_ADDR, ".strongswan.org", "tester@test.strongswan.org", TRUE },
    { ID_RFC822_ADDR, ".strongswan.org", "tester@strongswan.org", FALSE },
}
Referenced by certnames_suite_create(), and START_TEST().
char* subject
Definition at line 160 of file test_certnames.c.
Referenced by add_attribute_certs(), build_holder(), build_v2_form(), CALLBACK(), check_policy_constraints(), generate(), get_pretrusted_cert(), issue(), list_certs(), log_authority_data(), METHOD(), parse_certificate(), parse_certificate_request(), pem_load(), pubkey_cert_wrap(), self(), sshkey_certificate_load(), START_TEST(), stroke_list_pubkeys(), verify_ocsp(), and x509_ocsp_request_gen().