strongSwan: initiate_mediation_job.c File Reference
initiate_mediation_job.c File Reference
#include "initiate_mediation_job.h"
#include <sa/ike_sa.h>
#include <daemon.h>
Classes
struct private_initiate_mediation_job_t
Typedefs
typedef struct
private_initiate_mediation_job_t private_initiate_mediation_job_t
Functions
METHOD (job_t, destroy, void, private_initiate_mediation_job_t *this)
static bool initiate_callback (private_initiate_mediation_job_t *this, debug_t group, level_t level, ike_sa_t *ike_sa, char *message)
METHOD (job_t, initiate, job_requeue_t, private_initiate_mediation_job_t *this)
METHOD (job_t, reinitiate, job_requeue_t, private_initiate_mediation_job_t *this)
METHOD (job_t, get_priority, job_priority_t, private_initiate_mediation_job_t *this)
static
private_initiate_mediation_job_t * initiate_mediation_job_create_empty ()
initiate_mediation_job_t * initiate_mediation_job_create (ike_sa_id_t *ike_sa_id)
initiate_mediation_job_t * reinitiate_mediation_job_create (ike_sa_id_t *mediation_sa_id, ike_sa_id_t *mediated_sa_id)
Typedef Documentation
typedef struct private_initiate_mediation_job_t private_initiate_mediation_job_t
Definition at line 22 of file initiate_mediation_job.c.
Function Documentation
static bool initiate_callback (private_initiate_mediation_job_t * this, debug_t group, level_t level, ike_sa_t * ike_sa, char * message) static
Callback to handle initiation of mediation connection
Definition at line 55 of file initiate_mediation_job.c.
References ike_sa_id_t::clone, ike_sa_t::get_id, and TRUE.
Referenced by METHOD().
 {
     if (ike_sa && !this->mediation_sa_id)
     {
         this->mediation_sa_id = ike_sa->get_id(ike_sa);
         this->mediation_sa_id = this->mediation_sa_id->clone(this->mediation_sa_id);
     }
     return TRUE;
 }
static private_initiate_mediation_job_t* initiate_mediation_job_create_empty () static
Creates an empty job
Definition at line 228 of file initiate_mediation_job.c.
References INIT.
Referenced by initiate_mediation_job_create(), and reinitiate_mediation_job_create().
 {
     private_initiate_mediation_job_t *this;
     INIT(this,
         .public = {
             .job_interface = {
                 .get_priority = _get_priority,
                 .destroy = _destroy,
             },
         },
     );
     return this;
 }
METHOD (job_t , destroy , void , private_initiate_mediation_job_t * this)
Definition at line 44 of file initiate_mediation_job.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->mediation_sa_id);
     DESTROY_IF(this->mediated_sa_id);
     free(this);
 }
METHOD (job_t , initiate , job_requeue_t , private_initiate_mediation_job_t * this)
Definition at line 67 of file initiate_mediation_job.c.
References AUTH_RULE_IDENTITY, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout, daemon_t::controller, peer_cfg_t::create_auth_cfg_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, peer_cfg_t::destroy, enumerator_t::enumerate, FALSE, auth_cfg_t::get, ike_sa_t::get_peer_cfg, peer_cfg_t::get_ref, daemon_t::ike_sa_manager, controller_t::initiate, initiate_callback(), JOB_REQUEUE_NONE, JOB_RESCHEDULE_MS, SUCCESS, and TRUE.
 {
     ike_sa_t *mediated_sa, *mediation_sa;
     peer_cfg_t *mediated_cfg, *mediation_cfg;
     enumerator_t *enumerator;
     auth_cfg_t *auth_cfg;
     mediated_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager,
                                                    this->mediated_sa_id);
     if (mediated_sa)
     {
         DBG1(DBG_IKE, "initiating mediation connection");
         mediated_cfg = mediated_sa->get_peer_cfg(mediated_sa);
         mediated_cfg->get_ref(mediated_cfg);
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, mediated_sa);
         mediation_cfg = mediated_cfg->get_mediated_by(mediated_cfg);
         mediation_cfg->get_ref(mediation_cfg);
         enumerator = mediation_cfg->create_auth_cfg_enumerator(mediation_cfg,
                                                                TRUE);
         if (!enumerator->enumerate(enumerator, &auth_cfg) ||
             auth_cfg->get(auth_cfg, AUTH_RULE_IDENTITY) == NULL)
         {
             mediated_cfg->destroy(mediated_cfg);
             mediation_cfg->destroy(mediation_cfg);
             enumerator->destroy(enumerator);
             return JOB_REQUEUE_NONE;
         }
         enumerator->destroy(enumerator);
         if (charon->connect_manager->check_and_register(charon->connect_manager,
                 auth_cfg->get(auth_cfg, AUTH_RULE_IDENTITY),
                 mediated_cfg->get_peer_id(mediated_cfg),
                 this->mediated_sa_id))
         {
             mediated_cfg->destroy(mediated_cfg);
             mediation_cfg->destroy(mediation_cfg);
             mediated_sa = charon->ike_sa_manager->checkout(
                                 charon->ike_sa_manager, this->mediated_sa_id);
             if (mediated_sa)
             {
                 DBG1(DBG_IKE, "mediation with the same peer is already in "
                      "progress, queued");
                 charon->ike_sa_manager->checkin(
                                 charon->ike_sa_manager, mediated_sa);
             }
             return JOB_REQUEUE_NONE;
         }
         /* we need an additional reference because initiate consumes one */
         mediation_cfg->get_ref(mediation_cfg);
         if (charon->controller->initiate(charon->controller, mediation_cfg, NULL,
                 (controller_cb_t)initiate_callback, this, 0, FALSE) != SUCCESS)
         {
             mediation_cfg->destroy(mediation_cfg);
             mediated_cfg->destroy(mediated_cfg);
             mediated_sa = charon->ike_sa_manager->checkout(
                                 charon->ike_sa_manager, this->mediated_sa_id);
             if (mediated_sa)
             {
                 DBG1(DBG_IKE, "initiating mediation connection failed");
                 charon->ike_sa_manager->checkin_and_destroy(
                                     charon->ike_sa_manager, mediated_sa);
             }
             return JOB_REQUEUE_NONE;
         }
         mediation_cfg->destroy(mediation_cfg);
         mediation_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager,
                                                         this->mediation_sa_id);
         if (mediation_sa)
         {
             if (mediation_sa->initiate_mediation(mediation_sa,
                                                  mediated_cfg) != SUCCESS)
             {
                 mediated_cfg->destroy(mediated_cfg);
                 charon->ike_sa_manager->checkin_and_destroy(
                                 charon->ike_sa_manager, mediation_sa);
                 mediated_sa = charon->ike_sa_manager->checkout(
                                 charon->ike_sa_manager, this->mediated_sa_id);
                 if (mediated_sa)
                 {
                     DBG1(DBG_IKE, "establishing mediation connection failed");
                     charon->ike_sa_manager->checkin_and_destroy(
                                         charon->ike_sa_manager, mediated_sa);
                 }
                 return JOB_REQUEUE_NONE;
             }
             charon->ike_sa_manager->checkin(charon->ike_sa_manager,
                                             mediation_sa);
         }
         mediated_cfg->destroy(mediated_cfg);
     }
     else
     {   /* newly created IKE_SA is not checked in yet, try again */
         return JOB_RESCHEDULE_MS(100);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (job_t , reinitiate , job_requeue_t , private_initiate_mediation_job_t * this)
Definition at line 171 of file initiate_mediation_job.c.
References charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout, DBG1, DBG_IKE, DBG_JOB, peer_cfg_t::destroy, peer_cfg_t::get_name, ike_sa_t::get_peer_cfg, peer_cfg_t::get_ref, daemon_t::ike_sa_manager, JOB_REQUEUE_NONE, and SUCCESS.
 {
     ike_sa_t *mediated_sa, *mediation_sa;
     peer_cfg_t *mediated_cfg;
     mediated_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager,
                                                    this->mediated_sa_id);
     if (mediated_sa)
     {
         mediated_cfg = mediated_sa->get_peer_cfg(mediated_sa);
         mediated_cfg->get_ref(mediated_cfg);
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, mediated_sa);
         mediation_sa = charon->ike_sa_manager->checkout(charon->ike_sa_manager,
                                                         this->mediation_sa_id);
         if (mediation_sa)
         {
             if (mediation_sa->initiate_mediation(mediation_sa,
                                                  mediated_cfg) != SUCCESS)
             {
                 DBG1(DBG_JOB, "initiating mediated connection '%s' failed",
                      mediated_cfg->get_name(mediated_cfg));
                 mediated_cfg->destroy(mediated_cfg);
                 charon->ike_sa_manager->checkin_and_destroy(
                                         charon->ike_sa_manager,
                                         mediation_sa);
                 mediated_sa = charon->ike_sa_manager->checkout(
                                         charon->ike_sa_manager,
                                         this->mediated_sa_id);
                 if (mediated_sa)
                 {
                     DBG1(DBG_IKE, "establishing mediation connection failed");
                     charon->ike_sa_manager->checkin_and_destroy(
                                         charon->ike_sa_manager,
                                         mediated_sa);
                 }
                 return JOB_REQUEUE_NONE;
             }
             charon->ike_sa_manager->checkin(charon->ike_sa_manager,
                                             mediation_sa);
         }
         mediated_cfg->destroy(mediated_cfg);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (job_t , get_priority , job_priority_t , private_initiate_mediation_job_t * this)
Definition at line 219 of file initiate_mediation_job.c.
References JOB_PRIO_MEDIUM.
 {
     return JOB_PRIO_MEDIUM;
 }