strongSwan: chapoly_aead
chapoly_aead
chapoly
Classes
struct chapoly_aead_t
Typedefs
typedef struct chapoly_aead_t chapoly_aead_t
Functions
chapoly_aead_t * chapoly_aead_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Detailed Description
Typedef Documentation
typedef struct chapoly_aead_t chapoly_aead_t
Definition at line 26 of file chapoly_aead.h.
Function Documentation
chapoly_aead_t* chapoly_aead_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Create a chapoly_aead instance.
Parameters
algo algorithm to implement, ENCR_CHACHA20_POLY1305
key_size key size in bytes, 32
salt_size size of implicit salt length, 0
Returns
AEAD, NULL if not supported
See header
Definition at line 290 of file chapoly_aead.c.
References CHACHA_KEY_SIZE, CHACHA_SALT_SIZE, chapoly_drv_probe(), ENCR_CHACHA20_POLY1305, INIT, and iv_gen_seq_create().
Referenced by METHOD().
 {
     private_chapoly_aead_t *this;
     chapoly_drv_t *drv;
     if (algo != ENCR_CHACHA20_POLY1305)
     {
         return NULL;
     }
     if (key_size && key_size != CHACHA_KEY_SIZE)
     {
         return NULL;
     }
     if (salt_size && salt_size != CHACHA_SALT_SIZE)
     {
         return NULL;
     }
     drv = chapoly_drv_probe();
     if (!drv)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .aead = {
                 .encrypt = _encrypt,
                 .decrypt = _decrypt,
                 .get_block_size = _get_block_size,
                 .get_icv_size = _get_icv_size,
                 .get_iv_size = _get_iv_size,
                 .get_iv_gen = _get_iv_gen,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .iv_gen = iv_gen_seq_create(),
         .drv = drv,
     );
     return &this->public;
 }