strongSwan: tkm_kernel_ipsec.c File Reference
tkm_kernel_ipsec.c File Reference
#include <errno.h>
#include <netinet/udp.h>
#include <linux/xfrm.h>
#include <utils/debug.h>
#include <utils/chunk.h>
#include <tkm/constants.h>
#include <tkm/client.h>
#include "tkm.h"
#include "tkm_utils.h"
#include "tkm_types.h"
#include "tkm_keymat.h"
#include "tkm_kernel_ipsec.h"
Classes
struct private_tkm_kernel_ipsec_t
Macros
#define IP_XFRM_POLICY 17
Typedefs
typedef struct
private_tkm_kernel_ipsec_t private_tkm_kernel_ipsec_t
Functions
METHOD (kernel_ipsec_t, get_spi, status_t, private_tkm_kernel_ipsec_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
METHOD (kernel_ipsec_t, get_cpi, status_t, private_tkm_kernel_ipsec_t *this, host_t *src, host_t *dst, u_int16_t *cpi)
METHOD (kernel_ipsec_t, add_sa, status_t, private_tkm_kernel_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t *src_ts, linked_list_t *dst_ts)
METHOD (kernel_ipsec_t, query_sa, status_t, private_tkm_kernel_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
METHOD (kernel_ipsec_t, del_sa, status_t, private_tkm_kernel_ipsec_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
METHOD (kernel_ipsec_t, update_sa, status_t, private_tkm_kernel_ipsec_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool old_encap, bool new_encap, mark_t mark)
METHOD (kernel_ipsec_t, flush_sas, status_t, private_tkm_kernel_ipsec_t *this)
METHOD (kernel_ipsec_t, add_policy, status_t, private_tkm_kernel_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_ipsec_t, query_policy, status_t, private_tkm_kernel_ipsec_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, mark_t mark, time_t *use_time)
METHOD (kernel_ipsec_t, del_policy, status_t, private_tkm_kernel_ipsec_t *this, host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
METHOD (kernel_ipsec_t, flush_policies, status_t, private_tkm_kernel_ipsec_t *this)
METHOD (kernel_ipsec_t, bypass_socket, bool, private_tkm_kernel_ipsec_t *this, int fd, int family)
METHOD (kernel_ipsec_t, enable_udp_decap, bool, private_tkm_kernel_ipsec_t *this, int fd, int family, u_int16_t port)
METHOD (kernel_ipsec_t, destroy, void, private_tkm_kernel_ipsec_t *this)
tkm_kernel_ipsec_t * tkm_kernel_ipsec_create ()
Macro Definition Documentation
#define IP_XFRM_POLICY 17
From linux/in.h
Definition at line 33 of file tkm_kernel_ipsec.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tkm_kernel_ipsec_t private_tkm_kernel_ipsec_t
Definition at line 36 of file tkm_kernel_ipsec.c.
Function Documentation
METHOD (kernel_ipsec_t , get_spi , status_t , private_tkm_kernel_ipsec_t * this, host_t * src, host_t * dst, u_int8_t protocol, u_int32_t * spi)
Definition at line 55 of file tkm_kernel_ipsec.c.
References crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_KNL, FAILED, lib, result, rng, RNG_WEAK, and SUCCESS.
 {
     bool result;
     if (!this->rng)
     {
         this->rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
         if (!this->rng)
         {
             DBG1(DBG_KNL, "unable to create RNG");
             return FAILED;
         }
     }
     result = this->rng->get_bytes(this->rng, sizeof(u_int32_t),
                                   (u_int8_t *)spi);
     return result ? SUCCESS : FAILED;
 }
METHOD (kernel_ipsec_t , get_cpi , status_t , private_tkm_kernel_ipsec_t * this, host_t * src, host_t * dst, u_int16_t * cpi)
Definition at line 76 of file tkm_kernel_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , add_sa , status_t , private_tkm_kernel_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t * lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, u_int32_t replay_window, bool initiator, bool encap, bool esn, bool inbound, bool update, linked_list_t * src_ts, linked_list_t * dst_ts)
Definition at line 83 of file tkm_kernel_ipsec.c.
References tkm_id_manager_t::acquire_id, chunk_free(), tkm_t::chunk_map, chunk_to_sequence(), DBG1, DBG_KNL, esa_info_t::dh_id, dst, FAILED, tkm_chunk_map_t::get_id, tkm_t::idmgr, tkm_kernel_sad_t::insert, esa_info_t::isa_id, esa_info_t::nonce_i, esa_info_t::nonce_r, chunk_t::ptr, tkm_id_manager_t::release_id, tkm_chunk_map_t::remove, tkm_kernel_sad_t::remove, tkm_t::sad, esa_info_t::spi_r, src, SUCCESS, tkm, TKM_CTX_ESA, and TKM_CTX_NONCE.
 {
     esa_info_t esa;
     esp_spi_type spi_loc, spi_rem;
     host_t *local, *peer;
     chunk_t *nonce_loc, *nonce_rem;
     nc_id_type nonce_loc_id;
     esa_id_type esa_id;
     nonce_type nc_rem;
     if (enc_key.ptr == NULL)
     {
         DBG1(DBG_KNL, "Unable to get ESA information");
         return FAILED;
     }
     esa = *(esa_info_t *)(enc_key.ptr);
     /* only handle the case where we have both distinct ESP spi's available */
     if (esa.spi_r == spi)
     {
         chunk_free(&esa.nonce_i);
         chunk_free(&esa.nonce_r);
         return SUCCESS;
     }
     if (initiator)
     {
         spi_loc = spi;
         spi_rem = esa.spi_r;
         local = dst;
         peer = src;
         nonce_loc = &esa.nonce_i;
         nonce_rem = &esa.nonce_r;
     }
     else
     {
         spi_loc = esa.spi_r;
         spi_rem = spi;
         local = src;
         peer = dst;
         nonce_loc = &esa.nonce_r;
         nonce_rem = &esa.nonce_i;
     }
     esa_id = tkm->idmgr->acquire_id(tkm->idmgr, TKM_CTX_ESA);
     if (!tkm->sad->insert(tkm->sad, esa_id, reqid, local, peer, spi_loc, spi_rem,
                           protocol))
     {
         DBG1(DBG_KNL, "unable to add entry (%llu) to SAD", esa_id);
         goto sad_failure;
     }
     /*
      * creation of first CHILD SA:
      * no nonce and no dh contexts because the ones from the IKE SA are re-used
      */
     nonce_loc_id = tkm->chunk_map->get_id(tkm->chunk_map, nonce_loc);
     if (nonce_loc_id == 0 && esa.dh_id == 0)
     {
         if (ike_esa_create_first(esa_id, esa.isa_id, reqid, 1, spi_loc, spi_rem)
             != TKM_OK)
         {
             DBG1(DBG_KNL, "child SA (%llu, first) creation failed", esa_id);
             goto failure;
         }
     }
     /* creation of child SA without PFS: no dh context */
     else if (nonce_loc_id != 0 && esa.dh_id == 0)
     {
         chunk_to_sequence(nonce_rem, &nc_rem, sizeof(nonce_type));
         if (ike_esa_create_no_pfs(esa_id, esa.isa_id, reqid, 1, nonce_loc_id,
                                   nc_rem, initiator, spi_loc, spi_rem)
             != TKM_OK)
         {
             DBG1(DBG_KNL, "child SA (%llu, no PFS) creation failed", esa_id);
             goto failure;
         }
         tkm->chunk_map->remove(tkm->chunk_map, nonce_loc);
         tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_NONCE, nonce_loc_id);
     }
     /* creation of subsequent child SA with PFS: nonce and dh context are set */
     else
     {
         chunk_to_sequence(nonce_rem, &nc_rem, sizeof(nonce_type));
         if (ike_esa_create(esa_id, esa.isa_id, reqid, 1, esa.dh_id, nonce_loc_id,
                            nc_rem, initiator, spi_loc, spi_rem) != TKM_OK)
         {
             DBG1(DBG_KNL, "child SA (%llu) creation failed", esa_id);
             goto failure;
         }
         tkm->chunk_map->remove(tkm->chunk_map, nonce_loc);
         tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_NONCE, nonce_loc_id);
     }
     if (ike_esa_select(esa_id) != TKM_OK)
     {
         DBG1(DBG_KNL, "error selecting new child SA (%llu)", esa_id);
         if (ike_esa_reset(esa_id) != TKM_OK)
         {
             DBG1(DBG_KNL, "child SA (%llu) deletion failed", esa_id);
         }
         goto failure;
     }
     DBG1(DBG_KNL, "added child SA (esa: %llu, isa: %llu, esp_spi_loc: %x, "
          "esp_spi_rem: %x, role: %s)", esa_id, esa.isa_id, ntohl(spi_loc),
          ntohl(spi_rem), initiator ? "initiator" : "responder");
     chunk_free(&esa.nonce_i);
     chunk_free(&esa.nonce_r);
     return SUCCESS;
 failure:
     tkm->sad->remove(tkm->sad, esa_id);
 sad_failure:
     tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_ESA, esa_id);
     chunk_free(&esa.nonce_i);
     chunk_free(&esa.nonce_r);
     return FAILED;
 }
METHOD (kernel_ipsec_t , query_sa , status_t , private_tkm_kernel_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t * bytes, u_int64_t * packets, time_t * time)
Definition at line 210 of file tkm_kernel_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , del_sa , status_t , private_tkm_kernel_ipsec_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Definition at line 218 of file tkm_kernel_ipsec.c.
References DBG1, DBG_KNL, FAILED, tkm_kernel_sad_t::get_esa_id, tkm_kernel_sad_t::get_other_esa_id, tkm_t::idmgr, tkm_id_manager_t::release_id, tkm_kernel_sad_t::remove, tkm_t::sad, SUCCESS, tkm, and TKM_CTX_ESA.
 {
     esa_id_type esa_id, other_esa_id;
     esa_id = tkm->sad->get_esa_id(tkm->sad, src, dst, spi, protocol);
     if (esa_id)
     {
         other_esa_id = tkm->sad->get_other_esa_id(tkm->sad, esa_id);
         if (other_esa_id)
         {
             DBG1(DBG_KNL, "selecting child SA (esa: %llu)", other_esa_id);
             if (ike_esa_select(other_esa_id) != TKM_OK)
             {
                 DBG1(DBG_KNL, "error selecting other child SA (esa: %llu)",
                         other_esa_id);
             }
         }
         DBG1(DBG_KNL, "deleting child SA (esa: %llu, spi: %x)", esa_id,
              ntohl(spi));
         if (ike_esa_reset(esa_id) != TKM_OK)
         {
             DBG1(DBG_KNL, "child SA (%llu) deletion failed", esa_id);
             return FAILED;
         }
         tkm->sad->remove(tkm->sad, esa_id);
         tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_ESA, esa_id);
     }
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , update_sa , status_t , private_tkm_kernel_ipsec_t * this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t * src, host_t * dst, host_t * new_src, host_t * new_dst, bool old_encap, bool new_encap, mark_t mark)
Definition at line 251 of file tkm_kernel_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , flush_sas , status_t , private_tkm_kernel_ipsec_t * this)
Definition at line 259 of file tkm_kernel_ipsec.c.
References DBG1, DBG_KNL, and SUCCESS.
 {
     DBG1(DBG_KNL, "flushing child SA entries");
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , add_policy , status_t , private_tkm_kernel_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 266 of file tkm_kernel_ipsec.c.
References SUCCESS.
 {
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , query_policy , status_t , private_tkm_kernel_ipsec_t * this, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, mark_t mark, time_t * use_time)
Definition at line 275 of file tkm_kernel_ipsec.c.
References NOT_SUPPORTED.
 {
     return NOT_SUPPORTED;
 }
METHOD (kernel_ipsec_t , del_policy , status_t , private_tkm_kernel_ipsec_t * this, host_t * src, host_t * dst, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t * sa, mark_t mark, policy_priority_t priority)
Definition at line 283 of file tkm_kernel_ipsec.c.
References SUCCESS.
 {
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , flush_policies , status_t , private_tkm_kernel_ipsec_t * this)
Definition at line 292 of file tkm_kernel_ipsec.c.
References SUCCESS.
 {
     return SUCCESS;
 }
METHOD (kernel_ipsec_t , bypass_socket , bool , private_tkm_kernel_ipsec_t * this, int fd, int family)
Definition at line 299 of file tkm_kernel_ipsec.c.
References xfrm_userpolicy_info::action, DBG1, DBG_KNL, xfrm_userpolicy_info::dir, FALSE, family, xfrm_selector::family, IP_XFRM_POLICY, IPV6_XFRM_POLICY, memset, xfrm_userpolicy_info::sel, setsockopt, SOL_IP, SOL_IPV6, strerror, TRUE, XFRM_POLICY_ALLOW, XFRM_POLICY_IN, and XFRM_POLICY_OUT.
 {
     struct xfrm_userpolicy_info policy;
     u_int sol, ipsec_policy;
     switch (family)
     {
         case AF_INET:
             sol = SOL_IP;
             ipsec_policy = IP_XFRM_POLICY;
             break;
         case AF_INET6:
             sol = SOL_IPV6;
             ipsec_policy = IPV6_XFRM_POLICY;
             break;
         default:
             return FALSE;
     }
     memset(&policy, 0, sizeof(policy));
     policy.action = XFRM_POLICY_ALLOW;
     policy.sel.family = family;
     policy.dir = XFRM_POLICY_OUT;
     if (setsockopt(fd, sol, ipsec_policy, &policy, sizeof(policy)) < 0)
     {
         DBG1(DBG_KNL, "unable to set IPSEC_POLICY on socket: %s",
              strerror(errno));
         return FALSE;
     }
     policy.dir = XFRM_POLICY_IN;
     if (setsockopt(fd, sol, ipsec_policy, &policy, sizeof(policy)) < 0)
     {
         DBG1(DBG_KNL, "unable to set IPSEC_POLICY on socket: %s",
              strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
METHOD (kernel_ipsec_t , enable_udp_decap , bool , private_tkm_kernel_ipsec_t * this, int fd, int family, u_int16_t port)
Definition at line 340 of file tkm_kernel_ipsec.c.
References DBG1, DBG_KNL, FALSE, setsockopt, SOL_UDP, strerror, TRUE, type, UDP_ENCAP, and UDP_ENCAP_ESPINUDP.
 {
     int type = UDP_ENCAP_ESPINUDP;
     if (setsockopt(fd, SOL_UDP, UDP_ENCAP, &type, sizeof(type)) < 0)
     {
         DBG1(DBG_KNL, "unable to set UDP_ENCAP: %s", strerror(errno));
         return FALSE;
     }
     return TRUE;
 }
METHOD (kernel_ipsec_t , destroy , void , private_tkm_kernel_ipsec_t * this)
Definition at line 353 of file tkm_kernel_ipsec.c.
References DESTROY_IF, free(), and rng.
 {
     DESTROY_IF(this->rng);
     free(this);
 }