strongSwan: settings.c File Reference
settings.c File Reference
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include <errno.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <ctype.h>
#include "settings.h"
#include "settings_types.h"
#include "collections/array.h"
#include "collections/hashtable.h"
#include "collections/linked_list.h"
#include "threading/rwlock.h"
#include "utils/debug.h"
Classes
struct private_settings_t
struct enumerator_data_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct private_settings_t private_settings_t
Functions
bool settings_parser_parse_file (section_t *root, char *name)
bool settings_parser_parse_string (section_t *root, char *settings)
static bool print_key (char *buf, int len, char *start, char *key, va_list args)
static section_t * find_section_buffered (section_t *section, char *start, char *key, va_list args, char *buf, int len, bool ensure)
static void find_sections_buffered (section_t *section, char *start, char *key, va_list args, char *buf, int len, array_t **sections)
static section_t * ensure_section (private_settings_t *this, section_t *section, const char *key, va_list args)
static array_t * find_sections (private_settings_t *this, section_t *section, char *key, va_list args)
static bool fallback_exists (section_t *section, section_t *fallback)
static void add_fallback_to_section (private_settings_t *this, section_t *section, const char *key, va_list args, section_t *fallback)
static kv_t * find_value_buffered (section_t *section, char *start, char *key, va_list args, char *buf, int len, bool ensure)
static char * find_value (private_settings_t *this, section_t *section, char *key, va_list args)
static void set_value (private_settings_t *this, section_t *section, char *key, va_list args, char *value)
METHOD (settings_t, get_str, char *, private_settings_t *this, char *key, char *def,...)
bool settings_value_as_bool (char *value, bool def)
METHOD (settings_t, get_bool, bool, private_settings_t *this, char *key, bool def,...)
int settings_value_as_int (char *value, int def)
METHOD (settings_t, get_int, int, private_settings_t *this, char *key, int def,...)
u_int64_t settings_value_as_uint64 (char *value, u_int64_t def)
double settings_value_as_double (char *value, double def)
METHOD (settings_t, get_double, double, private_settings_t *this, char *key, double def,...)
u_int32_t settings_value_as_time (char *value, u_int32_t def)
METHOD (settings_t, get_time, u_int32_t, private_settings_t *this, char *key, u_int32_t def,...)
METHOD (settings_t, set_str, void, private_settings_t *this, char *key, char *value,...)
METHOD (settings_t, set_bool, void, private_settings_t *this, char *key, bool value,...)
METHOD (settings_t, set_int, void, private_settings_t *this, char *key, int value,...)
METHOD (settings_t, set_double, void, private_settings_t *this, char *key, double value,...)
METHOD (settings_t, set_time, void, private_settings_t *this, char *key, u_int32_t value,...)
METHOD (settings_t, set_default_str, bool, private_settings_t *this, char *key, char *value,...)
static void enumerator_destroy (enumerator_data_t *this)
static bool section_filter (hashtable_t *seen, section_t **in, char **out)
static enumerator_t * section_enumerator (section_t *section, enumerator_data_t *data)
METHOD (settings_t, create_section_enumerator, enumerator_t *, private_settings_t *this, char *key,...)
static bool kv_filter (hashtable_t *seen, kv_t **in, char **key, void *none, char **value)
static enumerator_t * kv_enumerator (section_t *section, enumerator_data_t *data)
METHOD (settings_t, create_key_value_enumerator, enumerator_t *, private_settings_t *this, char *key,...)
METHOD (settings_t, add_fallback, void, private_settings_t *this, const char *key, const char *fallback,...)
static bool load_internal (private_settings_t *this, section_t *parent, char *pattern, bool merge, bool string)
METHOD (settings_t, load_files, bool, private_settings_t *this, char *pattern, bool merge)
METHOD (settings_t, load_files_section, bool, private_settings_t *this, char *pattern, bool merge, char *key,...)
METHOD (settings_t, load_string, bool, private_settings_t *this, char *settings, bool merge)
METHOD (settings_t, load_string_section, bool, private_settings_t *this, char *settings, bool merge, char *key,...)
METHOD (settings_t, destroy, void, private_settings_t *this)
static private_settings_t * settings_create_base ()
settings_t * settings_create (char *file)
settings_t * settings_create_string (char *settings)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file settings.c.
Typedef Documentation
typedef struct private_settings_t private_settings_t
Definition at line 37 of file settings.c.
Function Documentation
static void add_fallback_to_section (private_settings_t * this, section_t * section, const char * key, va_list args, section_t * fallback) static
Ensure that the section with the given key exists and add the given fallback section (thread-safe).
Definition at line 297 of file settings.c.
References array_create(), array_insert_create(), ARRAY_TAIL, fallback_exists(), section_t::fallbacks, find_section_buffered(), found, lock, snprintf, TRUE, and spinlock_t::unlock.
Referenced by METHOD().
 {
     char buf[128], keybuf[512];
     section_t *found;
     if (snprintf(keybuf, sizeof(keybuf), "%s", key) >= sizeof(keybuf))
     {
         return;
     }
     this->lock->write_lock(this->lock);
     found = find_section_buffered(section, keybuf, keybuf, args, buf,
                                   sizeof(buf), TRUE);
     if (!fallback_exists(found, fallback))
     {
         /* to ensure sections referred to as fallback are not purged, we create
          * the array there too */
         if (!fallback->fallbacks)
         {
             fallback->fallbacks = array_create(0, 0);
         }
         array_insert_create(&found->fallbacks, ARRAY_TAIL, fallback);
     }
     this->lock->unlock(this->lock);
 }
static section_t* ensure_section (private_settings_t * this, section_t * section, const char * key, va_list args) static
Ensure that the section with the given key exists (thread-safe).
Definition at line 229 of file settings.c.
References find_section_buffered(), found, lock, snprintf, TRUE, and spinlock_t::unlock.
Referenced by METHOD().
 {
     char buf[128], keybuf[512];
     section_t *found;
     if (snprintf(keybuf, sizeof(keybuf), "%s", key) >= sizeof(keybuf))
     {
         return NULL;
     }
     /* we might have to change the tree */
     this->lock->write_lock(this->lock);
     found = find_section_buffered(section, keybuf, keybuf, args, buf,
                                   sizeof(buf), TRUE);
     this->lock->unlock(this->lock);
     return found;
 }
static void enumerator_destroy (enumerator_data_t * this) static
Destroy enumerator data
Definition at line 745 of file settings.c.
References array_destroy(), settings_t::destroy, free(), and settings.
Referenced by METHOD().
 {
     this->settings->lock->unlock(this->settings->lock);
     this->seen->destroy(this->seen);
     array_destroy(this->sections);
     free(this);
 }
static bool fallback_exists (section_t * section, section_t * fallback) static
Check if the given fallback section already exists
Definition at line 270 of file settings.c.
References array_count(), array_get(), section_t::fallbacks, FALSE, and TRUE.
Referenced by add_fallback_to_section().
 {
     if (section == fallback)
     {
         return TRUE;
     }
     else if (section->fallbacks)
     {
         section_t *existing;
         int i;
         for (i = 0; i < array_count(section->fallbacks); i++)
         {
             array_get(section->fallbacks, i, &existing);
             if (existing == fallback)
             {
                 return TRUE;
             }
         }
     }
     return FALSE;
 }
static section_t* find_section_buffered (section_t * section, char * start, char * key, va_list args, char * buf, int len, bool ensure) static
Find a section by a given key, using buffered key, reusable buffer. If "ensure" is TRUE, the sections are created if they don't exist.
Definition at line 121 of file settings.c.
References array_bsearch(), found, print_key(), section, section_t::sections, settings_section_add(), settings_section_create(), settings_section_find(), and strdup.
Referenced by add_fallback_to_section(), and ensure_section().
 {
     char *pos;
     section_t *found = NULL;
     if (section == NULL)
     {
         return NULL;
     }
     pos = strchr(key, '.');
     if (pos)
     {
         *pos = '\0';
         pos++;
     }
     if (!print_key(buf, len, start, key, args))
     {
         return NULL;
     }
     if (!strlen(buf))
     {
         found = section;
     }
     else if (array_bsearch(section->sections, buf, settings_section_find,
                            &found) == -1)
     {
         if (ensure)
         {
             found = settings_section_create(strdup(buf));
             settings_section_add(section, found, NULL);
         }
     }
     if (found && pos)
     {
         return find_section_buffered(found, start, pos, args, buf, len, ensure);
     }
     return found;
 }
static array_t* find_sections (private_settings_t * this, section_t * section, char * key, va_list args) static
Find a section by a given key with its fallbacks (not thread-safe!). Sections are returned in depth-first order (array is allocated). NULL is returned if no sections are found.
Definition at line 252 of file settings.c.
References find_sections_buffered(), and snprintf.
Referenced by METHOD().
 {
     char buf[128], keybuf[512];
     array_t *sections = NULL;
     if (snprintf(keybuf, sizeof(keybuf), "%s", key) >= sizeof(keybuf))
     {
         return NULL;
     }
     find_sections_buffered(section, keybuf, keybuf, args, buf,
                            sizeof(buf), &sections);
     return sections;
 }
static void find_sections_buffered (section_t * section, char * start, char * key, va_list args, char * buf, int len, array_t ** sections) static
Find all sections via a given key considering fallbacks, using buffered key, reusable buffer.
Definition at line 166 of file settings.c.
References array_bsearch(), array_count(), array_get(), array_insert_create(), ARRAY_TAIL, section_t::fallbacks, found, print_key(), section, section_t::sections, and settings_section_find().
Referenced by find_sections().
 {
     section_t *found = NULL, *fallback;
     char *pos;
     int i;
     if (!section)
     {
         return;
     }
     pos = strchr(key, '.');
     if (pos)
     {
         *pos = '\0';
     }
     if (!print_key(buf, len, start, key, args))
     {
         return;
     }
     if (pos)
     {   /* restore so we can follow fallbacks */
         *pos = '.';
     }
     if (!strlen(buf))
     {
         found = section;
     }
     else
     {
         array_bsearch(section->sections, buf, settings_section_find, &found);
     }
     if (found)
     {
         if (pos)
         {
             find_sections_buffered(found, start, pos+1, args, buf, len,
                                    sections);
         }
         else
         {
             array_insert_create(sections, ARRAY_TAIL, found);
             for (i = 0; i < array_count(found->fallbacks); i++)
             {
                 array_get(found->fallbacks, i, &fallback);
                 array_insert_create(sections, ARRAY_TAIL, fallback);
             }
         }
     }
     if (section->fallbacks)
     {
         for (i = 0; i < array_count(section->fallbacks); i++)
         {
             array_get(section->fallbacks, i, &fallback);
             find_sections_buffered(fallback, start, key, args, buf, len,
                                    sections);
         }
     }
 }
static char* find_value (private_settings_t * this, section_t * section, char * key, va_list args) static
Find the string value for a key (thread-safe).
Definition at line 411 of file settings.c.
References FALSE, find_value_buffered(), lock, snprintf, spinlock_t::unlock, kv_t::value, and value.
Referenced by METHOD().
 {
     char buf[128], keybuf[512], *value = NULL;
     kv_t *kv;
     if (snprintf(keybuf, sizeof(keybuf), "%s", key) >= sizeof(keybuf))
     {
         return NULL;
     }
     this->lock->read_lock(this->lock);
     kv = find_value_buffered(section, keybuf, keybuf, args, buf, sizeof(buf),
                              FALSE);
     if (kv)
     {
         value = kv->value;
     }
     this->lock->unlock(this->lock);
     return value;
 }
static kv_t* find_value_buffered (section_t * section, char * start, char * key, va_list args, char * buf, int len, bool ensure) static
Find the key/value pair for a key, using buffered key, reusable buffer If "ensure" is TRUE, the sections (and key/value pair) are created if they don't exist. Fallbacks are only considered if "ensure" is FALSE.
Definition at line 330 of file settings.c.
References array_bsearch(), array_count(), array_get(), section_t::fallbacks, found, section_t::kv, print_key(), section, section_t::sections, settings_kv_add(), settings_kv_create(), settings_kv_find(), settings_section_add(), settings_section_create(), settings_section_find(), and strdup.
Referenced by find_value(), and set_value().
 {
     int i;
     char *pos;
     kv_t *kv = NULL;
     section_t *found = NULL;
     if (section == NULL)
     {
         return NULL;
     }
     pos = strchr(key, '.');
     if (pos)
     {
         *pos = '\0';
         if (!print_key(buf, len, start, key, args))
         {
             return NULL;
         }
         /* restore so we can retry for fallbacks */
         *pos = '.';
         if (!strlen(buf))
         {
             found = section;
         }
         else if (array_bsearch(section->sections, buf, settings_section_find,
                                &found) == -1)
         {
             if (ensure)
             {
                 found = settings_section_create(strdup(buf));
                 settings_section_add(section, found, NULL);
             }
         }
         if (found)
         {
             kv = find_value_buffered(found, start, pos+1, args, buf, len,
                                      ensure);
         }
         if (!kv && !ensure && section->fallbacks)
         {
             for (i = 0; !kv && i < array_count(section->fallbacks); i++)
             {
                 array_get(section->fallbacks, i, &found);
                 kv = find_value_buffered(found, start, key, args, buf, len,
                                          ensure);
             }
         }
     }
     else
     {
         if (!print_key(buf, len, start, key, args))
         {
             return NULL;
         }
         if (array_bsearch(section->kv, buf, settings_kv_find, &kv) == -1)
         {
             if (ensure)
             {
                 kv = settings_kv_create(strdup(buf), NULL);
                 settings_kv_add(section, kv, NULL);
             }
             else if (section->fallbacks)
             {
                 for (i = 0; !kv && i < array_count(section->fallbacks); i++)
                 {
                     array_get(section->fallbacks, i, &found);
                     kv = find_value_buffered(found, start, key, args, buf, len,
                                              ensure);
                 }
             }
         }
     }
     return kv;
 }
static enumerator_t* kv_enumerator (section_t * section, enumerator_data_t * data) static
Enumerate key/value pairs of the given section
Definition at line 823 of file settings.c.
References array_create_enumerator(), enumerator_create_filter(), kv_filter(), section_t::kv_order, and enumerator_data_t::seen.
Referenced by METHOD().
 {
     return enumerator_create_filter(array_create_enumerator(section->kv_order),
                     (void*)kv_filter, data->seen, NULL);
 }
static bool kv_filter (hashtable_t * seen, kv_t ** in, char ** key, void * none, char ** value) static
Enumerate key and values, not kv_t entries
Definition at line 807 of file settings.c.
References FALSE, hashtable_t::get, hashtable_t::put, and TRUE.
Referenced by kv_enumerator().
 {
     *key = (*in)->key;
     if (seen->get(seen, *key) || !(*in)->value)
     {
         return FALSE;
     }
     *value = (*in)->value;
     seen->put(seen, *key, *key);
     return TRUE;
 }
static bool load_internal (private_settings_t * this, section_t * parent, char * pattern, bool merge, bool string) static
Load settings from files matching the given file pattern or from a string. All sections and values are added relative to "parent". All files (even included ones) have to be loaded successfully. If merge is FALSE the contents of parent are replaced with the parsed contents, otherwise they are merged together.
Definition at line 878 of file settings.c.
References FALSE, lock, section, settings_parser_parse_file(), settings_parser_parse_string(), settings_section_create(), settings_section_destroy(), settings_section_extend(), TRUE, and spinlock_t::unlock.
Referenced by METHOD().
 {
     section_t *section;
     bool loaded;
     if (pattern == NULL || !pattern[0])
     {   /* TODO: Clear parent if merge is FALSE? */
         return TRUE;
     }
     section = settings_section_create(NULL);
     loaded = string ? settings_parser_parse_string(section, pattern) :
                       settings_parser_parse_file(section, pattern);
     if (!loaded)
     {
         settings_section_destroy(section, NULL);
         return FALSE;
     }
     this->lock->write_lock(this->lock);
     settings_section_extend(parent, section, this->contents, !merge);
     this->lock->unlock(this->lock);
     settings_section_destroy(section, NULL);
     return TRUE;
 }
METHOD (settings_t , get_str , char * , private_settings_t * this, char * key, char * def, ...)
Definition at line 455 of file settings.c.
References find_value(), and value.
 {
     char *value;
     va_list args;
     va_start(args, def);
     value = find_value(this, this->top, key, args);
     va_end(args);
     if (value)
     {
         return value;
     }
     return def;
 }
METHOD (settings_t , get_bool , bool , private_settings_t * this, char * key, bool def, ...)
Definition at line 496 of file settings.c.
References find_value(), settings_value_as_bool(), and value.
 {
     char *value;
     va_list args;
     va_start(args, def);
     value = find_value(this, this->top, key, args);
     va_end(args);
     return settings_value_as_bool(value, def);
 }
METHOD (settings_t , get_int , int , private_settings_t * this, char * key, int def, ...)
Definition at line 528 of file settings.c.
References find_value(), settings_value_as_int(), and value.
 {
     char *value;
     va_list args;
     va_start(args, def);
     value = find_value(this, this->top, key, args);
     va_end(args);
     return settings_value_as_int(value, def);
 }
METHOD (settings_t , get_double , double , private_settings_t * this, char * key, double def, ...)
Definition at line 585 of file settings.c.
References find_value(), settings_value_as_double(), and value.
 {
     char *value;
     va_list args;
     va_start(args, def);
     value = find_value(this, this->top, key, args);
     va_end(args);
     return settings_value_as_double(value, def);
 }
METHOD (settings_t , get_time , u_int32_t , private_settings_t * this, char * key, u_int32_t def, ...)
Definition at line 641 of file settings.c.
References find_value(), settings_value_as_time(), and value.
 {
     char *value;
     va_list args;
     va_start(args, def);
     value = find_value(this, this->top, key, args);
     va_end(args);
     return settings_value_as_time(value, def);
 }
METHOD (settings_t , set_str , void , private_settings_t * this, char * key, char * value, ...)
Definition at line 653 of file settings.c.
References set_value().
 {
     va_list args;
     va_start(args, value);
     set_value(this, this->top, key, args, value);
     va_end(args);
 }
METHOD (settings_t , set_bool , void , private_settings_t * this, char * key, bool value, ...)
Definition at line 662 of file settings.c.
References set_value().
 {
     va_list args;
     va_start(args, value);
     set_value(this, this->top, key, args, value ? "1" : "0");
     va_end(args);
 }
METHOD (settings_t , set_int , void , private_settings_t * this, char * key, int value, ...)
Definition at line 671 of file settings.c.
References set_value(), snprintf, and val.
 {
     char val[16];
     va_list args;
     va_start(args, value);
     if (snprintf(val, sizeof(val), "%d", value) < sizeof(val))
     {
         set_value(this, this->top, key, args, val);
     }
     va_end(args);
 }
METHOD (settings_t , set_double , void , private_settings_t * this, char * key, double value, ...)
Definition at line 684 of file settings.c.
References set_value(), snprintf, and val.
 {
     char val[64];
     va_list args;
     va_start(args, value);
     if (snprintf(val, sizeof(val), "%f", value) < sizeof(val))
     {
         set_value(this, this->top, key, args, val);
     }
     va_end(args);
 }
METHOD (settings_t , set_time , void , private_settings_t * this, char * key, u_int32_t value, ...)
Definition at line 697 of file settings.c.
References set_value(), snprintf, and val.
 {
     char val[16];
     va_list args;
     va_start(args, value);
     if (snprintf(val, sizeof(val), "%u", value) < sizeof(val))
     {
         set_value(this, this->top, key, args, val);
     }
     va_end(args);
 }
METHOD (settings_t , set_default_str , bool , private_settings_t * this, char * key, char * value, ...)
Definition at line 710 of file settings.c.
References FALSE, find_value(), set_value(), and TRUE.
 {
     char *old;
     va_list args;
     va_start(args, value);
     old = find_value(this, this->top, key, args);
     va_end(args);
     if (!old)
     {
         va_start(args, value);
         set_value(this, this->top, key, args, value);
         va_end(args);
         return TRUE;
     }
     return FALSE;
 }
METHOD (settings_t , create_section_enumerator , enumerator_t * , private_settings_t * this, char * key, ...)
Definition at line 778 of file settings.c.
References array_create_enumerator(), data, enumerator_create_empty(), enumerator_create_nested(), enumerator_destroy(), find_sections(), hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), INIT, lock, section_enumerator(), settings, and spinlock_t::unlock.
 {
     enumerator_data_t *data;
     array_t *sections;
     va_list args;
     this->lock->read_lock(this->lock);
     va_start(args, key);
     sections = find_sections(this, this->top, key, args);
     va_end(args);
     if (!sections)
     {
         this->lock->unlock(this->lock);
         return enumerator_create_empty();
     }
     INIT(data,
         .settings = this,
         .sections = sections,
         .seen = hashtable_create(hashtable_hash_str, hashtable_equals_str, 8),
     );
     return enumerator_create_nested(array_create_enumerator(sections),
                     (void*)section_enumerator, data, (void*)enumerator_destroy);
 }
METHOD (settings_t , create_key_value_enumerator , enumerator_t * , private_settings_t * this, char * key, ...)
Definition at line 829 of file settings.c.
References array_create_enumerator(), data, enumerator_create_empty(), enumerator_create_nested(), enumerator_destroy(), find_sections(), hashtable_create(), hashtable_equals_str(), hashtable_hash_str(), INIT, kv_enumerator(), lock, settings, and spinlock_t::unlock.
 {
     enumerator_data_t *data;
     array_t *sections;
     va_list args;
     this->lock->read_lock(this->lock);
     va_start(args, key);
     sections = find_sections(this, this->top, key, args);
     va_end(args);
     if (!sections)
     {
         this->lock->unlock(this->lock);
         return enumerator_create_empty();
     }
     INIT(data,
         .settings = this,
         .sections = sections,
         .seen = hashtable_create(hashtable_hash_str, hashtable_equals_str, 8),
     );
     return enumerator_create_nested(array_create_enumerator(sections),
                     (void*)kv_enumerator, data, (void*)enumerator_destroy);
 }
METHOD (settings_t , add_fallback , void , private_settings_t * this, const char * key, const char * fallback, ...)
Definition at line 855 of file settings.c.
References add_fallback_to_section(), ensure_section(), and section.
 {
     section_t *section;
     va_list args;
     /* find/create the fallback */
     va_start(args, fallback);
     section = ensure_section(this, this->top, fallback, args);
     va_end(args);
     va_start(args, fallback);
     add_fallback_to_section(this, this->top, key, args, section);
     va_end(args);
 }
METHOD (settings_t , load_files , bool , private_settings_t * this, char * pattern, bool merge)
Definition at line 906 of file settings.c.
References FALSE, and load_internal().
 {
     return load_internal(this, this->top, pattern, merge, FALSE);
 }
METHOD (settings_t , load_files_section , bool , private_settings_t * this, char * pattern, bool merge, char * key, ...)
Definition at line 912 of file settings.c.
References ensure_section(), FALSE, load_internal(), and section.
 {
     section_t *section;
     va_list args;
     va_start(args, key);
     section = ensure_section(this, this->top, key, args);
     va_end(args);
     if (!section)
     {
         return FALSE;
     }
     return load_internal(this, section, pattern, merge, FALSE);
 }
METHOD (settings_t , load_string , bool , private_settings_t * this, char * settings, bool merge)
Definition at line 929 of file settings.c.
References load_internal(), and TRUE.
 {
     return load_internal(this, this->top, settings, merge, TRUE);
 }
METHOD (settings_t , load_string_section , bool , private_settings_t * this, char * settings, bool merge, char * key, ...)
Definition at line 935 of file settings.c.
References ensure_section(), FALSE, load_internal(), section, and TRUE.
 {
     section_t *section;
     va_list args;
     va_start(args, key);
     section = ensure_section(this, this->top, key, args);
     va_end(args);
     if (!section)
     {
         return FALSE;
     }
     return load_internal(this, section, settings, merge, TRUE);
 }
METHOD (settings_t , destroy , void , private_settings_t * this)
Definition at line 952 of file settings.c.
References array_destroy_function(), spinlock_t::destroy, free(), lock, and settings_section_destroy().
 {
     settings_section_destroy(this->top, NULL);
     array_destroy_function(this->contents, (void*)free, NULL);
     this->lock->destroy(this->lock);
     free(this);
 }
static bool print_key (char * buf, int len, char * start, char * key, va_list args) static
Print a format key, but consume already processed arguments
Definition at line 77 of file settings.c.
References copy(), DBG1, DBG_CFG, len, res, start, TRUE, and vsnprintf.
Referenced by find_section_buffered(), find_sections_buffered(), and find_value_buffered().
 {
     va_list copy;
     char *pos = start;
     bool res;
     va_copy(copy, args);
     while (TRUE)
     {
         pos = memchr(pos, '%', key - pos);
         if (!pos)
         {
             break;
         }
         pos++;
         switch (*pos)
         {
             case 'd':
                 va_arg(copy, int);
                 break;
             case 's':
                 va_arg(copy, char*);
                 break;
             case 'N':
                 va_arg(copy, enum_name_t*);
                 va_arg(copy, int);
                 break;
             case '%':
                 break;
             default:
                 DBG1(DBG_CFG, "settings with %%%c not supported!", *pos);
                 break;
         }
         pos++;
     }
     res = vsnprintf(buf, len, key, copy) < len;
     va_end(copy);
     return res;
 }
static enumerator_t* section_enumerator (section_t * section, enumerator_data_t * data) static
Enumerate sections of the given section
Definition at line 770 of file settings.c.
References array_create_enumerator(), enumerator_create_filter(), section_filter(), section_t::sections_order, and enumerator_data_t::seen.
Referenced by METHOD().
 {
     return enumerator_create_filter(
             array_create_enumerator(section->sections_order),
                 (void*)section_filter, data->seen, NULL);
 }
static bool section_filter (hashtable_t * seen, section_t ** in, char ** out) static
Enumerate section names, not sections
Definition at line 756 of file settings.c.
References FALSE, hashtable_t::get, hashtable_t::put, and TRUE.
Referenced by section_enumerator().
 {
     *out = (*in)->name;
     if (seen->get(seen, *out))
     {
         return FALSE;
     }
     seen->put(seen, *out, *out);
     return TRUE;
 }
static void set_value (private_settings_t * this, section_t * section, char * key, va_list args, char * value) static
Set a value to a copy of the given string (thread-safe).
Definition at line 435 of file settings.c.
References find_value_buffered(), lock, settings_kv_set(), snprintf, strdupnull(), TRUE, and spinlock_t::unlock.
Referenced by METHOD().
 {
     char buf[128], keybuf[512];
     kv_t *kv;
     if (snprintf(keybuf, sizeof(keybuf), "%s", key) >= sizeof(keybuf))
     {
         return;
     }
     this->lock->write_lock(this->lock);
     kv = find_value_buffered(section, keybuf, keybuf, args, buf, sizeof(buf),
                              TRUE);
     if (kv)
     {
         settings_kv_set(kv, strdupnull(value), this->contents);
     }
     this->lock->unlock(this->lock);
 }
static private_settings_t* settings_create_base () static
Definition at line 961 of file settings.c.
References array_create(), INIT, rwlock_create(), RWLOCK_TYPE_DEFAULT, and settings_section_create().
Referenced by settings_create(), and settings_create_string().
 {
     private_settings_t *this;
     INIT(this,
         .public = {
             .get_str = _get_str,
             .get_int = _get_int,
             .get_double = _get_double,
             .get_time = _get_time,
             .get_bool = _get_bool,
             .set_str = _set_str,
             .set_int = _set_int,
             .set_double = _set_double,
             .set_time = _set_time,
             .set_bool = _set_bool,
             .set_default_str = _set_default_str,
             .create_section_enumerator = _create_section_enumerator,
             .create_key_value_enumerator = _create_key_value_enumerator,
             .add_fallback = _add_fallback,
             .load_files = _load_files,
             .load_files_section = _load_files_section,
             .load_string = _load_string,
             .load_string_section = _load_string_section,
             .destroy = _destroy,
         },
         .top = settings_section_create(NULL),
         .contents = array_create(0, 0),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return this;
 }
bool settings_parser_parse_file (section_t * root, char * name)
Parse functions provided by the generated parser.
Parse the given file and add all sections and key/value pairs to the given section.
Definition at line 1704 of file settings_parser.c.
References array_destroy(), array_insert_create(), ARRAY_TAIL, library_t::conf, DBG1, DBG2, DBG_CFG, parser_helper_t::destroy, FALSE, parser_helper_t::file_include, parser_helper_t::get_lineno, lib, parser_helper_create(), parser_helper_t::scanner, settings_parser_get_lineno(), settings_parser_lex_destroy(), settings_parser_lex_init_extra(), settings_parser_open_next_file(), settings_parser_set_debug(), streq(), yydebug, and yyparse.
Referenced by load_internal().
 {
     parser_helper_t *helper;
     array_t *sections = NULL;
     bool success = FALSE;
     array_insert_create(&sections, ARRAY_TAIL, root);
     helper = parser_helper_create(sections);
     helper->get_lineno = settings_parser_get_lineno;
     if (settings_parser_lex_init_extra(helper, &helper->scanner) != 0)
     {
         helper->destroy(helper);
         array_destroy(sections);
         return FALSE;
     }
     helper->file_include(helper, name);
     if (!settings_parser_open_next_file(helper))
     {
         if (lib->conf && streq(name, lib->conf))
         {
             DBG2(DBG_CFG, "failed to open config file '%s'", name);
         }
         else
         {
             DBG1(DBG_CFG, "failed to open config file '%s'", name);
         }
     }
     else
     {
         if (getenv("DEBUG_SETTINGS_PARSER"))
         {
             yydebug = 1;
             settings_parser_set_debug(1, helper->scanner);
         }
         success = yyparse(helper) == 0;
         if (!success)
         {
             DBG1(DBG_CFG, "invalid config file '%s'", name);
         }
     }
     array_destroy(sections);
     settings_parser_lex_destroy(helper->scanner);
     helper->destroy(helper);
     return success;
 }
bool settings_parser_parse_string (section_t * root, char * settings)
Parse the given string and add all sections and key/value pairs to the given section.
Definition at line 1754 of file settings_parser.c.
References array_destroy(), array_insert_create(), ARRAY_TAIL, DBG1, DBG_CFG, parser_helper_t::destroy, FALSE, parser_helper_t::get_lineno, parser_helper_create(), parser_helper_t::scanner, settings_parser_get_lineno(), settings_parser_lex_destroy(), settings_parser_lex_init_extra(), settings_parser_load_string(), settings_parser_set_debug(), yydebug, and yyparse.
Referenced by load_internal().
 {
     parser_helper_t *helper;
     array_t *sections = NULL;
     bool success = FALSE;
     array_insert_create(&sections, ARRAY_TAIL, root);
     helper = parser_helper_create(sections);
     helper->get_lineno = settings_parser_get_lineno;
     if (settings_parser_lex_init_extra(helper, &helper->scanner) != 0)
     {
         helper->destroy(helper);
         array_destroy(sections);
         return FALSE;
     }
     settings_parser_load_string(helper, settings);
     if (getenv("DEBUG_SETTINGS_PARSER"))
     {
         yydebug = 1;
         settings_parser_set_debug(1, helper->scanner);
     }
     success = yyparse(helper) == 0;
     if (!success)
     {
         DBG1(DBG_CFG, "failed to parse settings '%s'", settings);
     }
     array_destroy(sections);
     settings_parser_lex_destroy(helper->scanner);
     helper->destroy(helper);
     return success;
 }