strongSwan: crl
crl
certificates
Classes
struct crl_t
Typedefs
typedef struct crl_t crl_t
typedef enum crl_reason_t crl_reason_t
Enumerations
enum crl_reason_t {
CRL_REASON_UNSPECIFIED = 0, CRL_REASON_KEY_COMPROMISE = 1, CRL_REASON_CA_COMPROMISE = 2, CRL_REASON_AFFILIATION_CHANGED = 3,
CRL_REASON_SUPERSEDED = 4, CRL_REASON_CESSATION_OF_OPERATON = 5, CRL_REASON_CERTIFICATE_HOLD = 6, CRL_REASON_REMOVE_FROM_CRL = 8
}
Functions
bool crl_is_newer (crl_t *crl, crl_t *other)
Variables
enum_name_t * crl_reason_names
Detailed Description
Typedef Documentation
typedef enum crl_reason_t crl_reason_t
Definition at line 26 of file crl.h.
typedef struct crl_t crl_t
Definition at line 25 of file crl.h.
Enumeration Type Documentation
enum crl_reason_t
RFC 2459 CRL reason codes
Enumerator
CRL_REASON_UNSPECIFIED
CRL_REASON_KEY_COMPROMISE
CRL_REASON_CA_COMPROMISE
CRL_REASON_AFFILIATION_CHANGED
CRL_REASON_SUPERSEDED
CRL_REASON_CESSATION_OF_OPERATON
CRL_REASON_CERTIFICATE_HOLD
CRL_REASON_REMOVE_FROM_CRL
Definition at line 46 of file crl.h.
                   {
     CRL_REASON_UNSPECIFIED              = 0,
     CRL_REASON_KEY_COMPROMISE           = 1,
     CRL_REASON_CA_COMPROMISE            = 2,
     CRL_REASON_AFFILIATION_CHANGED      = 3,
     CRL_REASON_SUPERSEDED               = 4,
     CRL_REASON_CESSATION_OF_OPERATON    = 5,
     CRL_REASON_CERTIFICATE_HOLD         = 6,
     CRL_REASON_REMOVE_FROM_CRL          = 8,
 };
Function Documentation
bool crl_is_newer (crl_t * this, crl_t * other)
Generic check if a given CRL is newer than another.
Parameters
crl CRL
other CRL to compare to
Returns
TRUE if this newer than other
Check if this CRL is newer
Definition at line 36 of file crl.c.
References crl_t::certificate, certificate_is_newer(), chunk_compare(), DBG1, DBG_LIB, crl_t::get_serial, and chunk_t::ptr.
Referenced by get_better_crl(), and METHOD().
 {
     chunk_t this_num, other_num;
     bool newer;
     this_num = this->get_serial(this);
     other_num = other->get_serial(other);
     /* compare crlNumbers if available - otherwise use generic cert compare */
     if (this_num.ptr != NULL && other_num.ptr != NULL)
     {
         newer = chunk_compare(this_num, other_num) > 0;
         DBG1(DBG_LIB, "  crl #%#B is %s - existing crl #%#B %s",
              &this_num, newer ? "newer" : "not newer",
              &other_num, newer ? "replaced" : "retained");
     }
     else
     {
         newer = certificate_is_newer(&this->certificate, &other->certificate);
     }
     return newer;
 }
Variable Documentation
enum_name_t* crl_reason_names
enum names for crl_reason_t
Referenced by get_better_crl(), get_better_ocsp(), parse(), and print_crl().