strongSwan: child_sa_manager_t Struct Reference
child_sa_manager_t Struct Reference
child_sa_manager
#include "child_sa_manager.h"
Public Attributes
void(* add)(child_sa_manager_t *this, child_sa_t *child_sa, ike_sa_t *ike_sa)
void(* remove)(child_sa_manager_t *this, child_sa_t *child_sa)
ike_sa_t *(* checkout)(child_sa_manager_t *this, protocol_id_t protocol, u_int32_t spi, host_t *dst, child_sa_t **child_sa)
ike_sa_t *(* checkout_by_id)(child_sa_manager_t *this, u_int32_t unique_id, child_sa_t **child_sa)
void(* destroy)(child_sa_manager_t *this)
Detailed Description
Handle CHILD_SA to IKE_SA relations
Definition at line 32 of file child_sa_manager.h.
Member Data Documentation
void(* child_sa_manager_t::add)(child_sa_manager_t *this, child_sa_t *child_sa, ike_sa_t *ike_sa)
Register a CHILD_SA/IKE_SA relation.
Parameters
child_sa CHILD_SA to register
ike_sa IKE_SA owning the CHILD_SA
Definition at line 40 of file child_sa_manager.h.
Referenced by METHOD(), and update_children().
ike_sa_t*(* child_sa_manager_t::checkout)(child_sa_manager_t *this, protocol_id_t protocol, u_int32_t spi, host_t *dst, child_sa_t **child_sa)
Find a CHILD_SA and check out the associated IKE_SA by SPI.
On success, the returned IKE_SA must be checked in after use to the IKE_SA manager.
Parameters
protocol IPsec protocol, AH|ESP
spi SPI of CHILD_SA to check out
dst SA destination host related to SPI
child_sa returns CHILD_SA managed by IKE_SA
Returns
IKE_SA, NULL if not found
Definition at line 61 of file child_sa_manager.h.
Referenced by METHOD().
ike_sa_t*(* child_sa_manager_t::checkout_by_id)(child_sa_manager_t *this, u_int32_t unique_id, child_sa_t **child_sa)
Find a CHILD_SA and check out the associated IKE_SA by unique_id.
On success, the returned IKE_SA must be checked in after use to the IKE_SA manager.
Parameters
unique_id unique ID of CHILD_SA to check out
child_sa returns CHILD_SA managed by IKE_SA
Returns
IKE_SA, NULL if not found
Definition at line 75 of file child_sa_manager.h.
Referenced by METHOD().
void(* child_sa_manager_t::destroy)(child_sa_manager_t *this)
Destroy a child_sa_manager_t.
Definition at line 81 of file child_sa_manager.h.
void(* child_sa_manager_t::remove)(child_sa_manager_t *this, child_sa_t *child_sa)
Unregister a CHILD_SA/IKE_SA relation.
Parameters
child_sa CHILD_SA to unregister
Definition at line 47 of file child_sa_manager.h.
Referenced by METHOD(), and update_children().
The documentation for this struct was generated from the following file:
child_sa_manager.h