strongSwan: tls_t Struct Reference
tls_t Struct Reference
tls
#include "tls.h"
Public Attributes
status_t(* process)(tls_t *this, void *buf, size_t buflen)
status_t(* build)(tls_t *this, void *buf, size_t *buflen, size_t *msglen)
bool(* is_server)(tls_t *this)
identification_t *(* get_server_id)(tls_t *this)
void(* set_peer_id)(tls_t *this, identification_t *id)
identification_t *(* get_peer_id)(tls_t *this)
tls_version_t(* get_version)(tls_t *this)
bool(* set_version)(tls_t *this, tls_version_t version)
tls_purpose_t(* get_purpose)(tls_t *this)
bool(* is_complete)(tls_t *this)
chunk_t(* get_eap_msk)(tls_t *this)
auth_cfg_t *(* get_auth)(tls_t *this)
void(* destroy)(tls_t *this)
Detailed Description
A bottom-up driven TLS stack, suitable for EAP implementations.
Definition at line 154 of file tls.h.
Member Data Documentation
status_t(* tls_t::build)(tls_t *this, void *buf, size_t *buflen, size_t *msglen)
Query upper layer for one or more TLS records, build fragments.
The TLS stack automatically fragments the records to the given buffer size. Fragmentation is indicated by the reclen ouput parameter and the return value. For the first fragment of a TLS record, a non-zero record length is returned in reclen. If more fragments follow, NEED_MORE is returned. A return value of ALREADY_DONE indicates that the final fragment has been returned.
Parameters
buf buffer to write TLS record fragments to
buflen size of buffer, receives bytes written
msglen receives size of all TLS fragments
Returns
SUCCESS if TLS negotiation complete
FAILED if TLS handshake failed
INVALID_STATE if more input data required
NEED_MORE if more fragments available
ALREADY_DONE if the last available fragment returned
Definition at line 188 of file tls.h.
Referenced by assess().
void(* tls_t::destroy)(tls_t *this)
Destroy a tls_t.
Definition at line 264 of file tls.h.
Referenced by client(), and METHOD().
auth_cfg_t*(* tls_t::get_auth)(tls_t *this)
Get the authentication details after completing the handshake.
Returns
authentication details, internal data
Definition at line 259 of file tls.h.
chunk_t(* tls_t::get_eap_msk)(tls_t *this)
Get the MSK for EAP-TLS.
Returns
MSK, internal data
Definition at line 252 of file tls.h.
identification_t*(* tls_t::get_peer_id)(tls_t *this)
Return the peer identity.
Returns
peer identity
Definition at line 216 of file tls.h.
Referenced by METHOD().
tls_purpose_t(* tls_t::get_purpose)(tls_t *this)
Get the purpose of this TLS stack instance.
Returns
purpose given during construction
Definition at line 238 of file tls.h.
Referenced by tls_crypto_create().
identification_t*(* tls_t::get_server_id)(tls_t *this)
Return the server identity.
Returns
server identity
Definition at line 202 of file tls.h.
Referenced by METHOD().
tls_version_t(* tls_t::get_version)(tls_t *this)
Get the negotiated TLS/SSL version.
Returns
negotiated TLS version
Definition at line 223 of file tls.h.
bool(* tls_t::is_complete)(tls_t *this)
Check if TLS negotiation completed successfully.
Returns
TRUE if TLS negotiation and authentication complete
Definition at line 245 of file tls.h.
Referenced by assess().
bool(* tls_t::is_server)(tls_t *this)
Check if TLS stack is acting as a server.
Returns
TRUE if server, FALSE if peer
Definition at line 195 of file tls.h.
Referenced by METHOD(), and tls_eap_create().
status_t(* tls_t::process)(tls_t *this, void *buf, size_t buflen)
Process one or more TLS records, pass it to upper layers.
Parameters
buf TLS record data, including headers
buflen number of bytes in buf to process
Returns
SUCCESS if TLS negotiation complete
FAILED if TLS handshake failed
NEED_MORE if more invocations to process/build needed
Definition at line 166 of file tls.h.
Referenced by assess().
void(* tls_t::set_peer_id)(tls_t *this, identification_t *id)
Set the peer identity.
Parameters
id peer identity
Definition at line 209 of file tls.h.
bool(* tls_t::set_version)(tls_t *this, tls_version_t version)
Set the negotiated TLS/SSL version.
Parameters
version negotiated TLS version
Returns
TRUE if version acceptable
Definition at line 231 of file tls.h.
The documentation for this struct was generated from the following file:
tls.h