strongSwan: fips_prf.c File Reference
fips_prf/fips_prf.c File Reference
#include "fips_prf.h"
#include <utils/debug.h>
Classes
struct private_fips_prf_t
Typedefs
typedef struct private_fips_prf_t private_fips_prf_t
Functions
static void add_mod (size_t length, u_int8_t a[], u_int8_t b[], u_int8_t sum[])
static void chunk_mod (size_t length, chunk_t chunk, u_int8_t buffer[])
METHOD (prf_t, get_bytes, bool, private_fips_prf_t *this, chunk_t seed, u_int8_t w[])
METHOD (prf_t, get_block_size, size_t, private_fips_prf_t *this)
METHOD (prf_t, allocate_bytes, bool, private_fips_prf_t *this, chunk_t seed, chunk_t *chunk)
METHOD (prf_t, get_key_size, size_t, private_fips_prf_t *this)
METHOD (prf_t, set_key, bool, private_fips_prf_t *this, chunk_t key)
static bool g_sha1 (private_fips_prf_t *this, chunk_t c, u_int8_t res[])
METHOD (prf_t, destroy, void, private_fips_prf_t *this)
fips_prf_t * fips_prf_create (pseudo_random_function_t algo)
Typedef Documentation
typedef struct private_fips_prf_t private_fips_prf_t
Definition at line 20 of file fips_prf/fips_prf.c.
Function Documentation
static void add_mod (size_t length, u_int8_t a[], u_int8_t b[], u_int8_t sum[]) static
sum = (a + b) mod 2 ^ (length * 8)
Definition at line 55 of file fips_prf/fips_prf.c.
References c.
Referenced by METHOD().
 {
     int i, c = 0;
     for(i = length - 1; i >= 0; i--)
     {
         u_int32_t tmp;
         tmp = a[i] + b[i] + c;
         sum[i] = 0xff & tmp;
         c = tmp >> 8;
     }
 }
static void chunk_mod (size_t length, chunk_t chunk, u_int8_t buffer[]) static
calculate "chunk mod 2^(length*8)" and save it into buffer
Definition at line 72 of file fips_prf/fips_prf.c.
References chunk_t::len, memcpy, memset, and chunk_t::ptr.
Referenced by METHOD().
 {
     if (chunk.len < length)
     {
         /* apply seed as least significant bits, others are zero */
         memset(buffer, 0, length - chunk.len);
         memcpy(buffer + length - chunk.len, chunk.ptr, chunk.len);
     }
     else
     {
         /* use least significant bytes from seed, as we use mod 2^b */
         memcpy(buffer, chunk.ptr + chunk.len - length, length);
     }
 }
static bool g_sha1 (private_fips_prf_t * this, chunk_t c, u_int8_t res[]) static
Implementation of the G() function based on SHA1
Definition at line 178 of file fips_prf/fips_prf.c.
References chunk_empty, FALSE, chunk_t::len, memcpy, memset, chunk_t::ptr, and TRUE.
Referenced by fips_prf_create().
 {
     u_int8_t buf[64];
     if (c.len < sizeof(buf))
     {
         /* pad c with zeros */
         memset(buf, 0, sizeof(buf));
         memcpy(buf, c.ptr, c.len);
         c.ptr = buf;
         c.len = sizeof(buf);
     }
     else
     {
         /* not more than 512 bits can be G()-ed */
         c.len = sizeof(buf);
     }
     /* use the keyed hasher, but use an empty key to use SHA1 IV */
     if (!this->keyed_prf->set_key(this->keyed_prf, chunk_empty) ||
         !this->keyed_prf->get_bytes(this->keyed_prf, c, res))
     {
         return FALSE;
     }
     return TRUE;
 }
METHOD (prf_t , get_bytes , bool , private_fips_prf_t * this, chunk_t seed, u_int8_t w[])
Implementation of prf_t.get_bytes.
Test vector:
key: 0xbd, 0x02, 0x9b, 0xbe, 0x7f, 0x51, 0x96, 0x0b, 0xcf, 0x9e, 0xdb, 0x2b, 0x61, 0xf0, 0x6f, 0x0f, 0xeb, 0x5a, 0x38, 0xb6
seed: 0x00
result: 0x20, 0x70, 0xb3, 0x22, 0x3d, 0xba, 0x37, 0x2f, 0xde, 0x1c, 0x0f, 0xfc, 0x7b, 0x2e, 0x3b, 0x49, 0x8b, 0x26, 0x06, 0x14, 0x3c, 0x6c, 0x18, 0xba, 0xcb, 0x0f, 0x6c, 0x55, 0xba, 0xbb, 0x13, 0x78, 0x8e, 0x20, 0xd7, 0x37, 0xa3, 0x27, 0x51, 0x16
Definition at line 107 of file fips_prf/fips_prf.c.
References add_mod(), b, chunk_create(), chunk_mod(), DBG3, DBG_LIB, FALSE, g, key, memset, and TRUE.
 {
     int i;
     u_int8_t xval[this->b];
     u_int8_t xseed[this->b];
     u_int8_t sum[this->b];
     u_int8_t *xkey = this->key;
     u_int8_t one[this->b];
     if (!w)
     {
         /* append mode is not supported */
         return FALSE;
     }
     memset(one, 0, this->b);
     one[this->b - 1] = 0x01;
     /* 3.1 */
     chunk_mod(this->b, seed, xseed);
     /* 3.2 */
     for (i = 0; i < 2; i++) /* twice */
     {
         /* a. XVAL = (XKEY + XSEED j) mod 2^b */
         add_mod(this->b, xkey, xseed, xval);
         DBG3(DBG_LIB, "XVAL %b", xval, (u_int)this->b);
         /* b. wi = G(t, XVAL ) */
         this->g(this, chunk_create(xval, this->b), &w[i * this->b]);
         DBG3(DBG_LIB, "w[%d] %b", i, &w[i * this->b], (u_int)this->b);
         /* c. XKEY = (1 + XKEY + wi) mod 2b */
         add_mod(this->b, xkey, &w[i * this->b], sum);
         add_mod(this->b, sum, one, xkey);
         DBG3(DBG_LIB, "XKEY %b", xkey, (u_int)this->b);
     }
     /* 3.3 done already, mod q not used */
     return TRUE;
 }
METHOD (prf_t , get_block_size , size_t , private_fips_prf_t * this)
Definition at line 149 of file fips_prf/fips_prf.c.
References b.
 {
     return 2 * this->b;
 }
METHOD (prf_t , allocate_bytes , bool , private_fips_prf_t * this, chunk_t seed, chunk_t * chunk)
Definition at line 154 of file fips_prf/fips_prf.c.
References chunk_alloc, and chunk_t::ptr.
 {
     *chunk = chunk_alloc(get_block_size(this));
     return get_bytes(this, seed, chunk->ptr);
 }
METHOD (prf_t , get_key_size , size_t , private_fips_prf_t * this)
Definition at line 161 of file fips_prf/fips_prf.c.
References b.
 {
     return this->b;
 }
METHOD (prf_t , set_key , bool , private_fips_prf_t * this, chunk_t key)
Definition at line 167 of file fips_prf/fips_prf.c.
References b, chunk_mod(), and TRUE.
 {
     /* save key as "key mod 2^b" */
     chunk_mod(this->b, key, this->key);
     return TRUE;
 }
METHOD (prf_t , destroy , void , private_fips_prf_t * this)
Definition at line 205 of file fips_prf/fips_prf.c.
References free(), and key.
 {
     this->keyed_prf->destroy(this->keyed_prf);
     free(this->key);
     free(this);
 }