strongSwan: process.c File Reference
process.c File Reference
#include "process.h"
#include <library.h>
#include <utils/debug.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
#include <signal.h>
Classes
struct private_process_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct private_process_t private_process_t
Enumerations
enum { PIPE_READ = 0, PIPE_WRITE = 1, PIPE_ENDS }
Functions
static void close_if (int *fd)
static void process_destroy (private_process_t *this)
METHOD (process_t, wait_, bool, private_process_t *this, int *code)
process_t * process_start (char *const argv[], char *const envp[], int *in, int *out, int *err, bool close_all)
process_t * process_start_shell (char *const envp[], int *in, int *out, int *err, char *fmt,...)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file process.c.
Typedef Documentation
typedef struct private_process_t private_process_t
Definition at line 27 of file process.c.
Enumeration Type Documentation
anonymous enum
Ends of a pipe()
Enumerator
PIPE_READ
PIPE_WRITE
PIPE_ENDS
Definition at line 32 of file process.c.
      {
     PIPE_READ = 0,
     PIPE_WRITE = 1,
     PIPE_ENDS,
 };
Function Documentation
static void close_if (int * fd) static
Close a file descriptor if it is not -1
Definition at line 79 of file process.c.
References close.
Referenced by process_destroy(), and process_start().
 {
     if (*fd != -1)
     {
         close(*fd);
         *fd = -1;
     }
 }
METHOD (process_t , wait_ , bool , private_process_t * this, int * code)
Definition at line 102 of file process.c.
References FALSE, process_destroy(), status, and TRUE.
 {
     int status, ret;
     ret = waitpid(this->pid, &status, 0);
     process_destroy(this);
     if (ret == -1)
     {
         return FALSE;
     }
     if (!WIFEXITED(status))
     {
         return FALSE;
     }
     if (code)
     {
         *code = WEXITSTATUS(status);
     }
     return TRUE;
 }
static void process_destroy (private_process_t * this) static
Destroy a process structure, close all pipes
Definition at line 91 of file process.c.
References close_if(), free(), in, out, PIPE_READ, and PIPE_WRITE.
Referenced by METHOD(), and process_start().
 {
     close_if(&this->in[PIPE_READ]);
     close_if(&this->in[PIPE_WRITE]);
     close_if(&this->out[PIPE_READ]);
     close_if(&this->out[PIPE_WRITE]);
     close_if(&this->err[PIPE_READ]);
     close_if(&this->err[PIPE_WRITE]);
     free(this);
 }