strongSwan: transform_substructure.c File Reference
transform_substructure.c File Reference
#include <stddef.h>
#include "transform_substructure.h"
#include <encoding/payloads/transform_attribute.h>
#include <encoding/payloads/encodings.h>
#include <library.h>
#include <collections/linked_list.h>
#include <daemon.h>
Classes
struct private_transform_substructure_t
Typedefs
typedef struct
private_transform_substructure_t private_transform_substructure_t
Functions
METHOD (payload_t, verify, status_t, private_transform_substructure_t *this)
METHOD (payload_t, get_encoding_rules, int, private_transform_substructure_t *this, encoding_rule_t **rules)
METHOD (payload_t, get_header_length, int, private_transform_substructure_t *this)
METHOD (payload_t, get_type, payload_type_t, private_transform_substructure_t *this)
METHOD (payload_t, get_next_type, payload_type_t, private_transform_substructure_t *this)
static void compute_length (private_transform_substructure_t *this)
METHOD (payload_t, get_length, size_t, private_transform_substructure_t *this)
METHOD (transform_substructure_t, add_transform_attribute, void, private_transform_substructure_t *this, transform_attribute_t *attribute)
METHOD (transform_substructure_t, set_is_last_transform, void, private_transform_substructure_t *this, bool is_last)
METHOD (payload_t, set_next_type, void, private_transform_substructure_t *this, payload_type_t type)
METHOD (transform_substructure_t, get_transform_type_or_number, u_int8_t, private_transform_substructure_t *this)
METHOD (transform_substructure_t, get_transform_id, u_int16_t, private_transform_substructure_t *this)
METHOD (transform_substructure_t, create_attribute_enumerator, enumerator_t *, private_transform_substructure_t *this)
METHOD2 (payload_t, transform_substructure_t, destroy, void, private_transform_substructure_t *this)
transform_substructure_t * transform_substructure_create (payload_type_t type)
transform_substructure_t * transform_substructure_create_type (payload_type_t type, u_int8_t type_or_number, u_int16_t id)
Variables
static encoding_rule_t encodings_v2 []
static encoding_rule_t encodings_v1 []
Typedef Documentation
typedef struct private_transform_substructure_t private_transform_substructure_t
Definition at line 28 of file transform_substructure.c.
Function Documentation
static void compute_length (private_transform_substructure_t * this) static
recompute the length of the payload.
Definition at line 200 of file transform_substructure.c.
References attributes, enumerator_t::destroy, enumerator_t::enumerate, and payload_t::get_length.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *attribute;
     this->transform_length = get_header_length(this);
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &attribute))
     {
         this->transform_length += attribute->get_length(attribute);
     }
     enumerator->destroy(enumerator);
 }
METHOD (payload_t , verify , status_t , private_transform_substructure_t * this)
Definition at line 138 of file transform_substructure.c.
References attributes, DBG1, DBG_ENC, enumerator_t::destroy, enumerator_t::enumerate, FAILED, PL_NONE, status, SUCCESS, and payload_t::verify.
 {
     status_t status = SUCCESS;
     enumerator_t *enumerator;
     payload_t *attribute;
     if (this->next_payload != PL_NONE && this->next_payload != 3)
     {
         DBG1(DBG_ENC, "inconsistent next payload");
         return FAILED;
     }
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &attribute))
     {
         status = attribute->verify(attribute);
         if (status != SUCCESS)
         {
             DBG1(DBG_ENC, "TRANSFORM_ATTRIBUTE verification failed");
             break;
         }
     }
     enumerator->destroy(enumerator);
     /* proposal number is checked in SA payload */
     return status;
 }
METHOD (payload_t , get_encoding_rules , int , private_transform_substructure_t * this, encoding_rule_t ** rules)
Definition at line 167 of file transform_substructure.c.
References countof, encodings_v1, encodings_v2, PLV2_TRANSFORM_SUBSTRUCTURE, and type.
 {
     if (this->type == PLV2_TRANSFORM_SUBSTRUCTURE)
     {
         *rules = encodings_v2;
         return countof(encodings_v2);
     }
     *rules = encodings_v1;
     return countof(encodings_v1);
 }
METHOD (payload_t , get_header_length , int , private_transform_substructure_t * this)
Definition at line 179 of file transform_substructure.c.
 {
     return 8;
 }
METHOD (payload_t , get_type , payload_type_t , private_transform_substructure_t * this)
Definition at line 185 of file transform_substructure.c.
References type.
 {
     return this->type;
 }
METHOD (payload_t , get_next_type , payload_type_t , private_transform_substructure_t * this)
Definition at line 191 of file transform_substructure.c.
 {
     return this->next_payload;
 }
METHOD (payload_t , get_length , size_t , private_transform_substructure_t * this)
Definition at line 214 of file transform_substructure.c.
 {
     return this->transform_length;
 }
METHOD (transform_substructure_t , add_transform_attribute , void , private_transform_substructure_t * this, transform_attribute_t * attribute)
Definition at line 220 of file transform_substructure.c.
References attributes, and compute_length().
 {
     this->attributes->insert_last(this->attributes, attribute);
     compute_length(this);
 }
METHOD (transform_substructure_t , set_is_last_transform , void , private_transform_substructure_t * this, bool is_last)
Definition at line 227 of file transform_substructure.c.
References TRANSFORM_TYPE_VALUE.
 {
     this->next_payload = is_last ? 0: TRANSFORM_TYPE_VALUE;
 }
METHOD (payload_t , set_next_type , void , private_transform_substructure_t * this, payload_type_t type)
Definition at line 233 of file transform_substructure.c.
 {
 }
METHOD (transform_substructure_t , get_transform_type_or_number , u_int8_t , private_transform_substructure_t * this)
Definition at line 238 of file transform_substructure.c.
 {
     return this->transform_ton;
 }
METHOD (transform_substructure_t , get_transform_id , u_int16_t , private_transform_substructure_t * this)
Definition at line 244 of file transform_substructure.c.
References PLV2_TRANSFORM_SUBSTRUCTURE, and type.
 {
     if (this->type == PLV2_TRANSFORM_SUBSTRUCTURE)
     {
         return this->transform_id_v2;
     }
     return this->transform_id_v1;
 }
METHOD (transform_substructure_t , create_attribute_enumerator , enumerator_t * , private_transform_substructure_t * this)
Definition at line 254 of file transform_substructure.c.
References attributes.
 {
     return this->attributes->create_enumerator(this->attributes);
 }
METHOD2 (payload_t , transform_substructure_t , destroy , void , private_transform_substructure_t * this)
Definition at line 260 of file transform_substructure.c.
References attributes, destroy(), and free().
 {
     this->attributes->destroy_offset(this->attributes,
                                      offsetof(payload_t, destroy));
     free(this);
 }
Variable Documentation
encoding_rule_t encodings_v1[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_transform_substructure_t, next_payload)    },
    { RESERVED_BYTE,    offsetof(private_transform_substructure_t, reserved[0])     },
    { PAYLOAD_LENGTH,   offsetof(private_transform_substructure_t, transform_length)},
    { U_INT_8,          offsetof(private_transform_substructure_t, transform_ton)},
    { U_INT_8,          offsetof(private_transform_substructure_t, transform_id_v1) },
    { RESERVED_BYTE,    offsetof(private_transform_substructure_t, reserved[1])     },
    { RESERVED_BYTE,    offsetof(private_transform_substructure_t, reserved[2])     },
    { PAYLOAD_LIST + PLV1_TRANSFORM_ATTRIBUTE,
                        offsetof(private_transform_substructure_t, attributes)      }
}
Encoding rules for PLV1_TRANSFORM_SUBSTRUCTURE
Definition at line 105 of file transform_substructure.c.
Referenced by METHOD().
encoding_rule_t encodings_v2[] static
Initial value:
= {
    { U_INT_8,          offsetof(private_transform_substructure_t, next_payload)    },
    { RESERVED_BYTE,    offsetof(private_transform_substructure_t, reserved[0])     },
    { PAYLOAD_LENGTH,   offsetof(private_transform_substructure_t, transform_length)},
    { U_INT_8,          offsetof(private_transform_substructure_t, transform_ton)   },
    { RESERVED_BYTE,    offsetof(private_transform_substructure_t, reserved[1])     },
    { U_INT_16,         offsetof(private_transform_substructure_t, transform_id_v2) },
    { PAYLOAD_LIST + PLV2_TRANSFORM_ATTRIBUTE,
                        offsetof(private_transform_substructure_t, attributes)      }
}
Encoding rules for PLV2_TRANSFORM_SUBSTRUCTURE
Definition at line 84 of file transform_substructure.c.
Referenced by METHOD().