strongSwan: imc_os_info
imc_os_info
imc
Classes
struct imc_os_info_t
Typedefs
typedef struct imc_os_info_t imc_os_info_t
Functions
imc_os_info_t * imc_os_info_create (void)
Detailed Description
Typedef Documentation
typedef struct imc_os_info_t imc_os_info_t
Definition at line 24 of file imc_os_info.h.
Function Documentation
imc_os_info_t* imc_os_info_create (void)
Create an imc_os_info_t object
See header
Definition at line 589 of file imc_os_info.c.
References chunk_clone, DBG1, DBG_IMC, extract_platform_info(), settings_t::get_str, INIT, chunk_t::len, lib, name, library_t::ns, os_type_from_name(), chunk_t::ptr, library_t::settings, type, and version.
Referenced by TNC_IMC_Initialize().
 {
     private_imc_os_info_t *this;
     chunk_t name, version;
     os_type_t type;
     /* As an option OS name and OS version can be configured manually */
     name.ptr = lib->settings->get_str(lib->settings,
                                       "%s.imcv.os_info.name", NULL, lib->ns);
     version.ptr = lib->settings->get_str(lib->settings,
                                       "%s.imcv.os_info.version", NULL, lib->ns);
     if (name.ptr && version.ptr)
     {
         name.len = strlen(name.ptr);
         name = chunk_clone(name);
         version.len = strlen(version.ptr);
         version = chunk_clone(version);
         type = os_type_from_name(name);
     }
     else
     {
         if (!extract_platform_info(&type, &name, &version))
         {
             return NULL;
         }
     }
     DBG1(DBG_IMC, "operating system name is '%.*s'",
                    name.len, name.ptr);
     DBG1(DBG_IMC, "operating system version is '%.*s'",
                    version.len, version.ptr);
     INIT(this,
         .public = {
             .get_type = _get_type,
             .get_name = _get_name,
             .get_numeric_version = _get_numeric_version,
             .get_version = _get_version,
             .get_fwd_status = _get_fwd_status,
             .get_default_pwd_status = _get_default_pwd_status,
             .get_uptime = _get_uptime,
             .get_setting = _get_setting,
             .create_package_enumerator = _create_package_enumerator,
             .destroy = _destroy,
         },
         .type = type,
         .name = name,
         .version = version,
     );
     return &this->public;
 }