strongSwan: rwlock_t Struct Reference
rwlock_t Struct Reference
rwlock
#include "rwlock.h"
Public Attributes
void(* read_lock)(rwlock_t *this)
void(* write_lock)(rwlock_t *this)
bool(* try_write_lock)(rwlock_t *this)
void(* unlock)(rwlock_t *this)
void(* destroy)(rwlock_t *this)
Detailed Description
Read-Write lock wrapper.
Definition at line 39 of file rwlock.h.
Member Data Documentation
void(* rwlock_t::destroy)(rwlock_t *this)
Destroy the read-write lock.
Definition at line 68 of file rwlock.h.
Referenced by cancellation_rwcond(), METHOD(), and START_TEST().
void(* rwlock_t::read_lock)(rwlock_t *this)
Acquire the read lock.
Definition at line 44 of file rwlock.h.
Referenced by cert_enumerate(), eap_radius_create_client(), METHOD(), rwlock_run(), and START_TEST().
bool(* rwlock_t::try_write_lock)(rwlock_t *this)
Try to acquire the write lock.
Never blocks, but returns FALSE if the lock was already occupied.
Returns
TRUE if lock acquired
Definition at line 58 of file rwlock.h.
Referenced by cache(), rwlock_run(), and rwlock_try_run().
void(* rwlock_t::unlock)(rwlock_t *this)
Release any acquired lock.
Definition at line 63 of file rwlock.h.
Referenced by address_enumerator_destroy(), cache(), CALLBACK(), cdp_data_destroy(), cert_data_destroy(), cert_enumerate(), cert_enumerator_destroy(), destroy_cdp_data(), destroy_cert_data(), destroy_private_data(), destroy_shared_data(), eap_radius_create_client(), key_data_destroy(), METHOD(), peer_enum_destroy(), put_connected_peers(), put_half_open(), remove_connected_peers(), remove_half_open(), rwlock_condvar_cancel_run(), rwlock_condvar_run(), rwlock_condvar_run_broad(), rwlock_run(), rwlock_try_run(), shared_data_destroy(), and START_TEST().
void(* rwlock_t::write_lock)(rwlock_t *this)
Acquire the write lock.
Definition at line 49 of file rwlock.h.
Referenced by CALLBACK(), cancellation_rwcond(), METHOD(), put_connected_peers(), put_half_open(), remove_connected_peers(), remove_half_open(), rwlock_condvar_cancel_run(), rwlock_condvar_run(), rwlock_condvar_run_broad(), rwlock_run(), and START_TEST().
The documentation for this struct was generated from the following file:
rwlock.h