strongSwan: medcli_config.c File Reference
medcli_config.c File Reference
#include <string.h>
#include "medcli_config.h"
#include <daemon.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_medcli_config_t
struct peer_enumerator_t
Macros
#define _GNU_SOURCE
Typedefs
typedef struct
private_medcli_config_t private_medcli_config_t
Functions
static traffic_selector_t * ts_from_string (char *str)
METHOD (backend_t, get_peer_cfg_by_name, peer_cfg_t *, private_medcli_config_t *this, char *name)
METHOD (backend_t, create_ike_cfg_enumerator, enumerator_t *, private_medcli_config_t *this, host_t *me, host_t *other)
METHOD (enumerator_t, peer_enumerator_enumerate, bool, peer_enumerator_t *this, peer_cfg_t **cfg)
METHOD (enumerator_t, peer_enumerator_destroy, void, peer_enumerator_t *this)
METHOD (backend_t, create_peer_cfg_enumerator, enumerator_t *, private_medcli_config_t *this, identification_t *me, identification_t *other)
static job_requeue_t initiate_config (peer_cfg_t *peer_cfg)
static void schedule_autoinit (private_medcli_config_t *this)
METHOD (medcli_config_t, destroy, void, private_medcli_config_t *this)
medcli_config_t * medcli_config_create (database_t *db)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file medcli_config.c.
Typedef Documentation
typedef struct private_medcli_config_t private_medcli_config_t
Definition at line 24 of file medcli_config.c.
Function Documentation
static job_requeue_t initiate_config (peer_cfg_t * peer_cfg) static
initiate a peer config
Definition at line 304 of file medcli_config.c.
References charon, daemon_t::controller, peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, child_cfg_t::get_ref, peer_cfg_t::get_ref, controller_t::initiate, and JOB_REQUEUE_NONE.
Referenced by schedule_autoinit().
 {
     enumerator_t *enumerator;
     child_cfg_t *child_cfg = NULL;;
     enumerator = peer_cfg->create_child_cfg_enumerator(peer_cfg);
     enumerator->enumerate(enumerator, &child_cfg);
     if (child_cfg)
     {
         child_cfg->get_ref(child_cfg);
         peer_cfg->get_ref(peer_cfg);
         enumerator->destroy(enumerator);
         charon->controller->initiate(charon->controller,
                                      peer_cfg, child_cfg, NULL, NULL, 0, FALSE);
     }
     else
     {
         enumerator->destroy(enumerator);
     }
     return JOB_REQUEUE_NONE;
 }
METHOD (backend_t , get_peer_cfg_by_name , peer_cfg_t * , private_medcli_config_t * this, char * name)
Definition at line 75 of file medcli_config.c.
References ACTION_NONE, auth_cfg_t::add, peer_cfg_t::add_auth_cfg, peer_cfg_t::add_child_cfg, child_cfg_t::add_proposal, ike_cfg_t::add_proposal, child_cfg_t::add_traffic_selector, auth_cfg_create(), AUTH_CLASS_PUBKEY, AUTH_RULE_AUTH_CLASS, AUTH_RULE_IDENTITY, CERT_NEVER_SEND, charon, child_cfg_create(), db, DB_BLOB, DB_TEXT, enumerator_t::destroy, DESTROY_IF, enumerator_t::enumerate, FALSE, FRAGMENTATION_NO, socket_manager_t::get_port, ID_KEY_ID, identification_create_from_encoding(), ike_cfg_create(), IKEV2, IKEV2_UDP_PORT, lifetime_cfg_t::life, me, MODE_TUNNEL, peer_cfg_create(), proposal_create_default(), proposal_create_default_aead(), PROTO_ESP, PROTO_IKE, database_t::query, daemon_t::socket, lifetime_cfg_t::time, TRUE, ts_from_string(), and UNIQUE_REPLACE.
 {
     enumerator_t *e;
     peer_cfg_t *peer_cfg, *med_cfg;
     auth_cfg_t *auth;
     ike_cfg_t *ike_cfg;
     child_cfg_t *child_cfg;
     chunk_t me, other;
     char *address, *local_net, *remote_net;
     lifetime_cfg_t lifetime = {
         .time = {
             .life = this->rekey * 60 + this->rekey,
             .rekey = this->rekey,
             .jitter = this->rekey
         }
     };
     /* query mediation server config:
      * - build ike_cfg/peer_cfg for mediation connection on-the-fly
      */
     e = this->db->query(this->db,
             "SELECT Address, ClientConfig.KeyId, MediationServerConfig.KeyId "
             "FROM MediationServerConfig JOIN ClientConfig",
             DB_TEXT, DB_BLOB, DB_BLOB);
     if (!e || !e->enumerate(e, &address, &me, &other))
     {
         DESTROY_IF(e);
         return NULL;
     }
     ike_cfg = ike_cfg_create(IKEV2, FALSE, FALSE, "0.0.0.0",
                              charon->socket->get_port(charon->socket, FALSE),
                              address, IKEV2_UDP_PORT, FRAGMENTATION_NO, 0);
     ike_cfg->add_proposal(ike_cfg, proposal_create_default(PROTO_IKE));
     ike_cfg->add_proposal(ike_cfg, proposal_create_default_aead(PROTO_IKE));
     med_cfg = peer_cfg_create(
         "mediation", ike_cfg,
         CERT_NEVER_SEND, UNIQUE_REPLACE,
         1, this->rekey*60, 0,           /* keytries, rekey, reauth */
         this->rekey*5, this->rekey*3,   /* jitter, overtime */
         TRUE, FALSE, TRUE,              /* mobike, aggressive, pull */
         this->dpd, 0,                   /* DPD delay, timeout */
         TRUE, NULL, NULL);              /* mediation, med by, peer id */
     e->destroy(e);
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     auth->add(auth, AUTH_RULE_IDENTITY,
               identification_create_from_encoding(ID_KEY_ID, me));
     med_cfg->add_auth_cfg(med_cfg, auth, TRUE);
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     auth->add(auth, AUTH_RULE_IDENTITY,
               identification_create_from_encoding(ID_KEY_ID, other));
     med_cfg->add_auth_cfg(med_cfg, auth, FALSE);
     /* query mediated config:
      * - use any-any ike_cfg
      * - build peer_cfg on-the-fly using med_cfg
      * - add a child_cfg
      */
     e = this->db->query(this->db,
             "SELECT ClientConfig.KeyId, Connection.KeyId, "
             "Connection.LocalSubnet, Connection.RemoteSubnet "
             "FROM ClientConfig JOIN Connection "
             "WHERE Active AND Alias = ?", DB_TEXT, name,
             DB_BLOB, DB_BLOB, DB_TEXT, DB_TEXT);
     if (!e || !e->enumerate(e, &me, &other, &local_net, &remote_net))
     {
         DESTROY_IF(e);
         return NULL;
     }
     peer_cfg = peer_cfg_create(
         name, this->ike->get_ref(this->ike),
         CERT_NEVER_SEND, UNIQUE_REPLACE,
         1, this->rekey*60, 0,           /* keytries, rekey, reauth */
         this->rekey*5, this->rekey*3,   /* jitter, overtime */
         TRUE, FALSE, TRUE,              /* mobike, aggressive, pull */
         this->dpd, 0,                   /* DPD delay, timeout */
         FALSE, med_cfg,                 /* mediation, med by */
         identification_create_from_encoding(ID_KEY_ID, other));
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     auth->add(auth, AUTH_RULE_IDENTITY,
               identification_create_from_encoding(ID_KEY_ID, me));
     peer_cfg->add_auth_cfg(peer_cfg, auth, TRUE);
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     auth->add(auth, AUTH_RULE_IDENTITY,
               identification_create_from_encoding(ID_KEY_ID, other));
     peer_cfg->add_auth_cfg(peer_cfg, auth, FALSE);
     child_cfg = child_cfg_create(name, &lifetime, NULL, TRUE, MODE_TUNNEL,
                                  ACTION_NONE, ACTION_NONE, ACTION_NONE, FALSE,
                                  0, 0, NULL, NULL, 0);
     child_cfg->add_proposal(child_cfg, proposal_create_default(PROTO_ESP));
     child_cfg->add_proposal(child_cfg, proposal_create_default_aead(PROTO_ESP));
     child_cfg->add_traffic_selector(child_cfg, TRUE, ts_from_string(local_net));
     child_cfg->add_traffic_selector(child_cfg, FALSE, ts_from_string(remote_net));
     peer_cfg->add_child_cfg(peer_cfg, child_cfg);
     e->destroy(e);
     return peer_cfg;
 }
METHOD (backend_t , create_ike_cfg_enumerator , enumerator_t * , private_medcli_config_t * this, host_t * me, host_t * other)
Definition at line 180 of file medcli_config.c.
References enumerator_create_single().
 {
     return enumerator_create_single(this->ike, NULL);
 }
METHOD (enumerator_t , peer_enumerator_enumerate , bool , peer_enumerator_t * this, peer_cfg_t ** cfg)
Definition at line 201 of file medcli_config.c.
References ACTION_NONE, child_cfg_t::add_proposal, child_cfg_t::add_traffic_selector, auth_cfg_create(), AUTH_CLASS_PUBKEY, AUTH_RULE_AUTH_CLASS, AUTH_RULE_IDENTITY, CERT_NEVER_SEND, child_cfg_create(), DESTROY_IF, FALSE, ID_KEY_ID, identification_create_from_encoding(), lifetime_cfg_t::life, me, MODE_TUNNEL, name, peer_cfg_create(), proposal_create_default(), proposal_create_default_aead(), PROTO_ESP, lifetime_cfg_t::time, TRUE, ts_from_string(), and UNIQUE_REPLACE.
 {
     char *name, *local_net, *remote_net;
     chunk_t me, other;
     child_cfg_t *child_cfg;
     auth_cfg_t *auth;
     lifetime_cfg_t lifetime = {
         .time = {
             .life = this->rekey * 60 + this->rekey,
             .rekey = this->rekey,
             .jitter = this->rekey
         }
     };
     DESTROY_IF(this->current);
     if (!this->inner->enumerate(this->inner, &name, &me, &other,
                                 &local_net, &remote_net))
     {
         this->current = NULL;
         return FALSE;
     }
     this->current = peer_cfg_create(
                 name, this->ike->get_ref(this->ike),
                 CERT_NEVER_SEND, UNIQUE_REPLACE,
                 1, this->rekey*60, 0,           /* keytries, rekey, reauth */
                 this->rekey*5, this->rekey*3,   /* jitter, overtime */
                 TRUE, FALSE, TRUE,              /* mobike, aggressive, pull */
                 this->dpd, 0,                   /* DPD delay, timeout */
                 FALSE, NULL, NULL);             /* mediation, med by, peer id */
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     auth->add(auth, AUTH_RULE_IDENTITY,
               identification_create_from_encoding(ID_KEY_ID, me));
     this->current->add_auth_cfg(this->current, auth, TRUE);
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     auth->add(auth, AUTH_RULE_IDENTITY,
               identification_create_from_encoding(ID_KEY_ID, other));
     this->current->add_auth_cfg(this->current, auth, FALSE);
     child_cfg = child_cfg_create(name, &lifetime, NULL, TRUE, MODE_TUNNEL,
                                  ACTION_NONE, ACTION_NONE, ACTION_NONE, FALSE,
                                  0, 0, NULL, NULL, 0);
     child_cfg->add_proposal(child_cfg, proposal_create_default(PROTO_ESP));
     child_cfg->add_proposal(child_cfg, proposal_create_default_aead(PROTO_ESP));
     child_cfg->add_traffic_selector(child_cfg, TRUE, ts_from_string(local_net));
     child_cfg->add_traffic_selector(child_cfg, FALSE, ts_from_string(remote_net));
     this->current->add_child_cfg(this->current, child_cfg);
     *cfg = this->current;
     return TRUE;
 }
METHOD (enumerator_t , peer_enumerator_destroy , void , peer_enumerator_t * this)
Definition at line 255 of file medcli_config.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->current);
     this->inner->destroy(this->inner);
     free(this);
 }
METHOD (backend_t , create_peer_cfg_enumerator , enumerator_t * , private_medcli_config_t * this, identification_t * me, identification_t * other)
Definition at line 263 of file medcli_config.c.
References chunk_empty, db, DB_BLOB, DB_INT, DB_TEXT, destroy(), free(), identification_t::get_encoding, identification_t::get_type, ID_ANY, ID_KEY_ID, INIT, peer_enumerator_t::inner, peer_enumerator_t::public, and database_t::query.
 {
     peer_enumerator_t *e;
     INIT(e,
         .public = {
             .enumerate = (void*)_peer_enumerator_enumerate,
             .destroy = _peer_enumerator_destroy,
         },
         .ike = this->ike,
         .rekey = this->rekey,
         .dpd = this->dpd,
     );
     /* filter on IDs: NULL or ANY or matching KEY_ID */
     e->inner = this->db->query(this->db,
             "SELECT Alias, ClientConfig.KeyId, Connection.KeyId, "
             "Connection.LocalSubnet, Connection.RemoteSubnet "
             "FROM ClientConfig JOIN Connection "
             "WHERE Active AND "
             "(? OR ClientConfig.KeyId = ?) AND (? OR Connection.KeyId = ?)",
             DB_INT, me == NULL || me->get_type(me) == ID_ANY,
             DB_BLOB, me && me->get_type(me) == ID_KEY_ID ?
                 me->get_encoding(me) : chunk_empty,
             DB_INT, other == NULL || other->get_type(other) == ID_ANY,
             DB_BLOB, other && other->get_type(other) == ID_KEY_ID ?
                 other->get_encoding(other) : chunk_empty,
             DB_TEXT, DB_BLOB, DB_BLOB, DB_TEXT, DB_TEXT);
     if (!e->inner)
     {
         free(e);
         return NULL;
     }
     return &e->public;
 }
METHOD (medcli_config_t , destroy , void , private_medcli_config_t * this)
Definition at line 356 of file medcli_config.c.
References free().
 {
     this->ike->destroy(this->ike);
     free(this);
 }
static void schedule_autoinit (private_medcli_config_t * this) static
schedule initiation of all "active" connections
Definition at line 329 of file medcli_config.c.
References callback_job_create(), db, DB_TEXT, enumerator_t::destroy, peer_cfg_t::destroy, enumerator_t::enumerate, initiate_config(), lib, name, library_t::processor, database_t::query, and processor_t::queue_job.
Referenced by medcli_config_create().
 {
     enumerator_t *e;
     char *name;
     e = this->db->query(this->db, "SELECT Alias FROM Connection WHERE Active",
                         DB_TEXT);
     if (e)
     {
         while (e->enumerate(e, &name))
         {
             peer_cfg_t *peer_cfg;
             peer_cfg = get_peer_cfg_by_name(this, name);
             if (peer_cfg)
             {
                 /* schedule asynchronous initiation job */
                 lib->processor->queue_job(lib->processor,
                         (job_t*)callback_job_create(
                                     (callback_job_cb_t)initiate_config,
                                     peer_cfg, (void*)peer_cfg->destroy, NULL));
             }
         }
         e->destroy(e);
     }
 }
static traffic_selector_t* ts_from_string (char * str) static
create a traffic selector from a CIDR notation string
Definition at line 60 of file medcli_config.c.
References traffic_selector_create_dynamic(), and traffic_selector_create_from_cidr().
Referenced by METHOD().
 {
     if (str)
     {
         traffic_selector_t *ts;
         ts = traffic_selector_create_from_cidr(str, 0, 0, 65535);
         if (ts)
         {
             return ts;
         }
     }
     return traffic_selector_create_dynamic(0, 0, 65535);
 }