strongSwan: kernel_libipsec_plugin.c File Reference
kernel_libipsec_plugin.c File Reference
#include "kernel_libipsec_plugin.h"
#include "kernel_libipsec_ipsec.h"
#include "kernel_libipsec_router.h"
#include <daemon.h>
#include <ipsec.h>
#include <networking/tun_device.h>
Classes
struct private_kernel_libipsec_plugin_t
Macros
#define TUN_DEFAULT_MTU 1400
Typedefs
typedef struct
private_kernel_libipsec_plugin_t private_kernel_libipsec_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_kernel_libipsec_plugin_t *this)
static bool create_router (private_kernel_libipsec_plugin_t *this, plugin_feature_t *feature, bool reg, void *arg)
METHOD (plugin_t, get_features, int, private_kernel_libipsec_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_kernel_libipsec_plugin_t *this)
plugin_t * kernel_libipsec_plugin_create ()
Macro Definition Documentation
#define TUN_DEFAULT_MTU 1400
Definition at line 24 of file kernel_libipsec_plugin.c.
Referenced by kernel_libipsec_plugin_create().
Typedef Documentation
typedef struct private_kernel_libipsec_plugin_t private_kernel_libipsec_plugin_t
Definition at line 26 of file kernel_libipsec_plugin.c.
Function Documentation
static bool create_router (private_kernel_libipsec_plugin_t * this, plugin_feature_t * feature, bool reg, void * arg) static
Create the kernel_libipsec_router_t instance
Definition at line 58 of file kernel_libipsec_plugin.c.
References DESTROY_IF, kernel_libipsec_router_create(), router, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {   /* registers as packet handler etc. */
         this->router = kernel_libipsec_router_create();
     }
     else
     {
         DESTROY_IF(this->router);
     }
     return TRUE;
 }
plugin_t* kernel_libipsec_plugin_create ()
Definition at line 101 of file kernel_libipsec_plugin.c.
References CAP_NET_ADMIN, library_t::caps, capabilities_t::check, DBG1, DBG_KNL, DBG_LIB, destroy(), INIT, lib, libipsec_init(), library_t::ns, library_t::set, settings_t::set_str, library_t::settings, TUN_DEFAULT_MTU, and tun_device_create().
 {
     private_kernel_libipsec_plugin_t *this;
     if (!lib->caps->check(lib->caps, CAP_NET_ADMIN))
     {   /* required to create TUN devices */
         DBG1(DBG_KNL, "kernel-libipsec plugin requires CAP_NET_ADMIN "
              "capability");
         return NULL;
     }
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     if (!libipsec_init())
     {
         DBG1(DBG_LIB, "initialization of libipsec failed");
         destroy(this);
         return NULL;
     }
     this->tun = tun_device_create("ipsec%d");
     if (!this->tun)
     {
         DBG1(DBG_KNL, "failed to create TUN device");
         destroy(this);
         return NULL;
     }
     if (!this->tun->set_mtu(this->tun, TUN_DEFAULT_MTU) ||
         !this->tun->up(this->tun))
     {
         DBG1(DBG_KNL, "failed to configure TUN device");
         destroy(this);
         return NULL;
     }
     lib->set(lib, "kernel-libipsec-tun", this->tun);
     /* set TUN device as default to install VIPs */
     lib->settings->set_str(lib->settings, "%s.install_virtual_ip_on",
                            this->tun->get_name(this->tun), lib->ns);
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_kernel_libipsec_plugin_t * this)
Definition at line 49 of file kernel_libipsec_plugin.c.
 {
     return "kernel-libipsec";
 }
METHOD (plugin_t , get_features , int , private_kernel_libipsec_plugin_t * this, plugin_feature_t * features[])
Definition at line 72 of file kernel_libipsec_plugin.c.
References countof, create_router(), kernel_ipsec_register(), kernel_libipsec_ipsec_create(), PLUGIN_CALLBACK, PLUGIN_DEPENDS, and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(kernel_ipsec_register, kernel_libipsec_ipsec_create),
             PLUGIN_PROVIDE(CUSTOM, "kernel-ipsec"),
         PLUGIN_CALLBACK((plugin_feature_callback_t)create_router, NULL),
             PLUGIN_PROVIDE(CUSTOM, "kernel-libipsec-router"),
                 PLUGIN_DEPENDS(CUSTOM, "libcharon-receiver"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_kernel_libipsec_plugin_t * this)
Definition at line 86 of file kernel_libipsec_plugin.c.
References free(), lib, libipsec_deinit(), and library_t::set.
 {
     if (this->tun)
     {
         lib->set(lib, "kernel-libipsec-tun", NULL);
         this->tun->destroy(this->tun);
     }
     libipsec_deinit();
     free(this);
 }