strongSwan: ietf_attr_attr_request.c File Reference
ietf_attr_attr_request.c File Reference
#include "imcv.h"
#include "ietf_attr_attr_request.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_attr_request_t
Macros
#define ATTR_REQUEST_ENTRY_SIZE 8
Typedefs
typedef struct
private_ietf_attr_attr_request_t private_ietf_attr_attr_request_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_attr_request_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_attr_request_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_attr_request_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_attr_request_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_attr_request_t *this)
METHOD (ietf_attr_attr_request_t, add, void, private_ietf_attr_attr_request_t *this, pen_t vendor_id, u_int32_t type)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_attr_request_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_attr_request_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_attr_request_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_attr_request_t *this)
METHOD (ietf_attr_attr_request_t, create_enumerator, enumerator_t *, private_ietf_attr_attr_request_t *this)
pa_tnc_attr_t * ietf_attr_attr_request_create (pen_t vendor_id, u_int32_t type)
pa_tnc_attr_t * ietf_attr_attr_request_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define ATTR_REQUEST_ENTRY_SIZE 8
PA-TNC Attribute Request type (see section 4.2.1 of RFC 5792)
                 1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | PA-TNC Attribute Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PA-TNC Attribute Type | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | PA-TNC Attribute Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PA-TNC Attribute Type | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 44 of file ietf_attr_attr_request.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_attr_request_t private_ietf_attr_attr_request_t
Definition at line 26 of file ietf_attr_attr_request.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_attr_request_t * this)
Definition at line 87 of file ietf_attr_attr_request.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_attr_request_t * this)
Definition at line 93 of file ietf_attr_attr_request.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_attr_request_t * this)
Definition at line 99 of file ietf_attr_attr_request.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_attr_request_t * this, bool noskip)
Definition at line 105 of file ietf_attr_attr_request.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_attr_request_t * this)
Definition at line 111 of file ietf_attr_attr_request.c.
References ATTR_REQUEST_ENTRY_SIZE, bio_writer_create(), linked_list_t::create_enumerator, bio_writer_t::destroy, bio_writer_t::extract_buf, linked_list_t::get_count, length, list, pen_type_t::type, value, pen_type_t::vendor_id, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     pen_type_t *entry;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(ATTR_REQUEST_ENTRY_SIZE *
                                this->list->get_count(this->list));
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         writer->write_uint32(writer, entry->vendor_id);
         writer->write_uint32(writer, entry->type);
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (ietf_attr_attr_request_t , add , void , private_ietf_attr_attr_request_t * this, pen_t vendor_id, u_int32_t type)
Definition at line 138 of file ietf_attr_attr_request.c.
References DBG2, DBG_TNC, pa_tnc_attr_manager_t::get_names, imcv_pa_tnc_attributes, linked_list_t::insert_last, list, malloc_thing, pen_names, type, pen_type_t::type, and pen_type_t::vendor_id.
 {
     enum_name_t *pa_attr_names;
     pen_type_t *entry;
     pa_attr_names = imcv_pa_tnc_attributes->get_names(imcv_pa_tnc_attributes,
                                                           vendor_id);
     if (pa_attr_names)
     {
         DBG2(DBG_TNC, "  0x%06x/0x%08x '%N/%N'", vendor_id, type,
                          pen_names, vendor_id, pa_attr_names, type);
     }
     else
     {
         DBG2(DBG_TNC, "  0x%06x/0x%08x '%N'", vendor_id, type,
                          pen_names, vendor_id);
     }
     entry = malloc_thing(pen_type_t);
     entry->vendor_id = vendor_id;
     entry->type = type;
     this->list->insert_last(this->list, entry);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_attr_request_t * this, u_int32_t * offset)
Definition at line 162 of file ietf_attr_attr_request.c.
References add(), ATTR_REQUEST_ENTRY_SIZE, bio_reader_create(), count, DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, NEED_MORE, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, reserved, SUCCESS, type, and value.
 {
     bio_reader_t *reader;
     pen_t vendor_id;
     u_int32_t type;
     u_int8_t reserved;
     int count;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     count = this->value.len / ATTR_REQUEST_ENTRY_SIZE;
     if (this->value.len != ATTR_REQUEST_ENTRY_SIZE * count)
     {
         DBG1(DBG_TNC, "incorrect attribute length for IETF attribute request");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     while (count--)
     {
         reader->read_uint8 (reader, &reserved);
         reader->read_uint24(reader, &vendor_id);
         reader->read_uint32(reader, &type);
         add(this, vendor_id, type);
     }
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_attr_request_t * this, chunk_t segment)
Definition at line 198 of file ietf_attr_attr_request.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_attr_request_t * this)
Definition at line 204 of file ietf_attr_attr_request.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_attr_request_t * this)
Definition at line 211 of file ietf_attr_attr_request.c.
References linked_list_t::destroy_function, free(), list, ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         this->list->destroy_function(this->list, free);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_attr_request_t , create_enumerator , enumerator_t * , private_ietf_attr_attr_request_t * this)
Definition at line 222 of file ietf_attr_attr_request.c.
References linked_list_t::create_enumerator, and list.
 {
     return this->list->create_enumerator(this->list);
 }