strongSwan: plugin_feature
plugin_feature
plugins
Classes
struct plugin_feature_t
Macros
#define FEATURE(kind, type,...) _PLUGIN_FEATURE_##type(kind, __VA_ARGS__)
#define PLUGIN_REGISTER(type, f,...) _PLUGIN_FEATURE_REGISTER_##type(type, f, ##__VA_ARGS__)
#define PLUGIN_CALLBACK(cb, data) _PLUGIN_FEATURE_CALLBACK(cb, data)
#define PLUGIN_NOOP _PLUGIN_FEATURE_CALLBACK(NULL, NULL)
#define PLUGIN_PROVIDE(type,...) _PLUGIN_FEATURE_##type(PROVIDE, __VA_ARGS__)
#define PLUGIN_DEPENDS(type,...) _PLUGIN_FEATURE_##type(DEPENDS, __VA_ARGS__)
#define PLUGIN_SDEPEND(type,...) _PLUGIN_FEATURE_##type(SDEPEND, __VA_ARGS__)
#define __PLUGIN_FEATURE(kind, type,...) (plugin_feature_t){ FEATURE_##kind, FEATURE_##type, { __VA_ARGS__ }}
#define _PLUGIN_FEATURE_CRYPTER(kind, alg, size) __PLUGIN_FEATURE(kind, CRYPTER, .crypter = { alg, size })
#define _PLUGIN_FEATURE_AEAD(kind, alg, size) __PLUGIN_FEATURE(kind, AEAD, .aead = { alg, size })
#define _PLUGIN_FEATURE_SIGNER(kind, alg) __PLUGIN_FEATURE(kind, SIGNER, .signer = alg)
#define _PLUGIN_FEATURE_HASHER(kind, alg) __PLUGIN_FEATURE(kind, HASHER, .hasher = alg)
#define _PLUGIN_FEATURE_PRF(kind, alg) __PLUGIN_FEATURE(kind, PRF, .prf = alg)
#define _PLUGIN_FEATURE_DH(kind, group) __PLUGIN_FEATURE(kind, DH, .dh_group = group)
#define _PLUGIN_FEATURE_RNG(kind, quality) __PLUGIN_FEATURE(kind, RNG, .rng_quality = quality)
#define _PLUGIN_FEATURE_NONCE_GEN(kind,...) __PLUGIN_FEATURE(kind, NONCE_GEN, .custom = NULL)
#define _PLUGIN_FEATURE_PRIVKEY(kind, type) __PLUGIN_FEATURE(kind, PRIVKEY, .privkey = type)
#define _PLUGIN_FEATURE_PRIVKEY_GEN(kind, type) __PLUGIN_FEATURE(kind, PRIVKEY_GEN, .privkey_gen = type)
#define _PLUGIN_FEATURE_PRIVKEY_SIGN(kind, scheme) __PLUGIN_FEATURE(kind, PRIVKEY_SIGN, .privkey_sign = scheme)
#define _PLUGIN_FEATURE_PRIVKEY_DECRYPT(kind, scheme) __PLUGIN_FEATURE(kind, PRIVKEY_DECRYPT, .privkey_decrypt = scheme)
#define _PLUGIN_FEATURE_PUBKEY(kind, type) __PLUGIN_FEATURE(kind, PUBKEY, .pubkey = type)
#define _PLUGIN_FEATURE_PUBKEY_VERIFY(kind, scheme) __PLUGIN_FEATURE(kind, PUBKEY_VERIFY, .pubkey_verify = scheme)
#define _PLUGIN_FEATURE_PUBKEY_ENCRYPT(kind, scheme) __PLUGIN_FEATURE(kind, PUBKEY_ENCRYPT, .pubkey_encrypt = scheme)
#define _PLUGIN_FEATURE_CERT_DECODE(kind, type) __PLUGIN_FEATURE(kind, CERT_DECODE, .cert = type)
#define _PLUGIN_FEATURE_CERT_ENCODE(kind, type) __PLUGIN_FEATURE(kind, CERT_ENCODE, .cert = type)
#define _PLUGIN_FEATURE_CONTAINER_DECODE(kind, type) __PLUGIN_FEATURE(kind, CONTAINER_DECODE, .container = type)
#define _PLUGIN_FEATURE_CONTAINER_ENCODE(kind, type) __PLUGIN_FEATURE(kind, CONTAINER_ENCODE, .container = type)
#define _PLUGIN_FEATURE_EAP_SERVER(kind, type) _PLUGIN_FEATURE_EAP_SERVER_VENDOR(kind, type, 0)
#define _PLUGIN_FEATURE_EAP_PEER(kind, type) _PLUGIN_FEATURE_EAP_PEER_VENDOR(kind, type, 0)
#define _PLUGIN_FEATURE_EAP_SERVER_VENDOR(kind, type, vendor) __PLUGIN_FEATURE(kind, EAP_SERVER, .eap = { type, vendor })
#define _PLUGIN_FEATURE_EAP_PEER_VENDOR(kind, type, vendor) __PLUGIN_FEATURE(kind, EAP_PEER, .eap = { type, vendor })
#define _PLUGIN_FEATURE_DATABASE(kind, type) __PLUGIN_FEATURE(kind, DATABASE, .database = type)
#define _PLUGIN_FEATURE_FETCHER(kind, type) __PLUGIN_FEATURE(kind, FETCHER, .fetcher = type)
#define _PLUGIN_FEATURE_RESOLVER(kind,...) __PLUGIN_FEATURE(kind, RESOLVER, .custom = NULL)
#define _PLUGIN_FEATURE_CUSTOM(kind, name) __PLUGIN_FEATURE(kind, CUSTOM, .custom = name)
#define _PLUGIN_FEATURE_XAUTH_SERVER(kind, name) __PLUGIN_FEATURE(kind, XAUTH_SERVER, .xauth = name)
#define _PLUGIN_FEATURE_XAUTH_PEER(kind, name) __PLUGIN_FEATURE(kind, XAUTH_PEER, .xauth = name)
#define __PLUGIN_FEATURE_REGISTER(type, _f) (plugin_feature_t){ FEATURE_REGISTER, FEATURE_##type, .arg.reg.f = _f }
#define __PLUGIN_FEATURE_REGISTER_BUILDER(type, _f, _final) (plugin_feature_t){ FEATURE_REGISTER, FEATURE_##type, .arg.reg = {.f = _f, .final = _final, }}
#define _PLUGIN_FEATURE_REGISTER_CRYPTER(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_AEAD(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_SIGNER(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_HASHER(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_PRF(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_DH(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_RNG(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_NONCE_GEN(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_PRIVKEY(type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
#define _PLUGIN_FEATURE_REGISTER_PRIVKEY_GEN(type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
#define _PLUGIN_FEATURE_REGISTER_PUBKEY(type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
#define _PLUGIN_FEATURE_REGISTER_CERT_DECODE(type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
#define _PLUGIN_FEATURE_REGISTER_CERT_ENCODE(type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
#define _PLUGIN_FEATURE_REGISTER_CONTAINER_DECODE(type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
#define _PLUGIN_FEATURE_REGISTER_CONTAINER_ENCODE(type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
#define _PLUGIN_FEATURE_REGISTER_DATABASE(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_FETCHER(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_REGISTER_RESOLVER(type, f) __PLUGIN_FEATURE_REGISTER(type, f)
#define _PLUGIN_FEATURE_CALLBACK(_cb, _data) (plugin_feature_t){ FEATURE_CALLBACK, FEATURE_NONE, .arg.cb = { .f = _cb, .data = _data } }
Typedefs
typedef struct plugin_feature_t plugin_feature_t
typedef bool(* plugin_feature_callback_t)(plugin_t *plugin, plugin_feature_t *feature, bool reg, void *cb_data)
Functions
static void plugin_features_add (plugin_feature_t *features, plugin_feature_t *to_add, int count, int *pos)
u_int32_t plugin_feature_hash (plugin_feature_t *feature)
bool plugin_feature_matches (plugin_feature_t *a, plugin_feature_t *b)
bool plugin_feature_equals (plugin_feature_t *a, plugin_feature_t *b)
char * plugin_feature_get_string (plugin_feature_t *feature)
bool plugin_feature_load (plugin_t *plugin, plugin_feature_t *feature, plugin_feature_t *reg)
bool plugin_feature_unload (plugin_t *plugin, plugin_feature_t *feature, plugin_feature_t *reg)
Variables
enum_name_t * plugin_feature_names
Detailed Description
Macro Definition Documentation
#define __PLUGIN_FEATURE (kind, type, ...) (plugin_feature_t){ FEATURE_##kind, FEATURE_##type, { __VA_ARGS__ }}
Definition at line 275 of file plugin_feature.h.
#define __PLUGIN_FEATURE_REGISTER (type, _f) (plugin_feature_t){ FEATURE_REGISTER, FEATURE_##type, .arg.reg.f = _f }
Definition at line 306 of file plugin_feature.h.
#define __PLUGIN_FEATURE_REGISTER_BUILDER (type, _f, _final) (plugin_feature_t){ FEATURE_REGISTER, FEATURE_##type, .arg.reg = {.f = _f, .final = _final, }}
Definition at line 307 of file plugin_feature.h.
#define _PLUGIN_FEATURE_AEAD (kind, alg, size) __PLUGIN_FEATURE(kind, AEAD, .aead = { alg, size })
Definition at line 277 of file plugin_feature.h.
#define _PLUGIN_FEATURE_CALLBACK (_cb, _data) (plugin_feature_t){ FEATURE_CALLBACK, FEATURE_NONE, .arg.cb = { .f = _cb, .data = _data } }
Definition at line 327 of file plugin_feature.h.
#define _PLUGIN_FEATURE_CERT_DECODE (kind, type) __PLUGIN_FEATURE(kind, CERT_DECODE, .cert = type)
Definition at line 291 of file plugin_feature.h.
#define _PLUGIN_FEATURE_CERT_ENCODE (kind, type) __PLUGIN_FEATURE(kind, CERT_ENCODE, .cert = type)
Definition at line 292 of file plugin_feature.h.
#define _PLUGIN_FEATURE_CONTAINER_DECODE (kind, type) __PLUGIN_FEATURE(kind, CONTAINER_DECODE, .container = type)
Definition at line 293 of file plugin_feature.h.
#define _PLUGIN_FEATURE_CONTAINER_ENCODE (kind, type) __PLUGIN_FEATURE(kind, CONTAINER_ENCODE, .container = type)
Definition at line 294 of file plugin_feature.h.
#define _PLUGIN_FEATURE_CRYPTER (kind, alg, size) __PLUGIN_FEATURE(kind, CRYPTER, .crypter = { alg, size })
Definition at line 276 of file plugin_feature.h.
#define _PLUGIN_FEATURE_CUSTOM (kind, name) __PLUGIN_FEATURE(kind, CUSTOM, .custom = name)
Definition at line 302 of file plugin_feature.h.
#define _PLUGIN_FEATURE_DATABASE (kind, type) __PLUGIN_FEATURE(kind, DATABASE, .database = type)
Definition at line 299 of file plugin_feature.h.
#define _PLUGIN_FEATURE_DH (kind, group) __PLUGIN_FEATURE(kind, DH, .dh_group = group)
Definition at line 281 of file plugin_feature.h.
#define _PLUGIN_FEATURE_EAP_PEER (kind, type) _PLUGIN_FEATURE_EAP_PEER_VENDOR(kind, type, 0)
Definition at line 296 of file plugin_feature.h.
#define _PLUGIN_FEATURE_EAP_PEER_VENDOR (kind, type, vendor) __PLUGIN_FEATURE(kind, EAP_PEER, .eap = { type, vendor })
Definition at line 298 of file plugin_feature.h.
#define _PLUGIN_FEATURE_EAP_SERVER (kind, type) _PLUGIN_FEATURE_EAP_SERVER_VENDOR(kind, type, 0)
Definition at line 295 of file plugin_feature.h.
#define _PLUGIN_FEATURE_EAP_SERVER_VENDOR (kind, type, vendor) __PLUGIN_FEATURE(kind, EAP_SERVER, .eap = { type, vendor })
Definition at line 297 of file plugin_feature.h.
#define _PLUGIN_FEATURE_FETCHER (kind, type) __PLUGIN_FEATURE(kind, FETCHER, .fetcher = type)
Definition at line 300 of file plugin_feature.h.
#define _PLUGIN_FEATURE_HASHER (kind, alg) __PLUGIN_FEATURE(kind, HASHER, .hasher = alg)
Definition at line 279 of file plugin_feature.h.
#define _PLUGIN_FEATURE_NONCE_GEN (kind, ...) __PLUGIN_FEATURE(kind, NONCE_GEN, .custom = NULL)
Definition at line 283 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PRF (kind, alg) __PLUGIN_FEATURE(kind, PRF, .prf = alg)
Definition at line 280 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PRIVKEY (kind, type) __PLUGIN_FEATURE(kind, PRIVKEY, .privkey = type)
Definition at line 284 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PRIVKEY_DECRYPT (kind, scheme) __PLUGIN_FEATURE(kind, PRIVKEY_DECRYPT, .privkey_decrypt = scheme)
Definition at line 287 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PRIVKEY_GEN (kind, type) __PLUGIN_FEATURE(kind, PRIVKEY_GEN, .privkey_gen = type)
Definition at line 285 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PRIVKEY_SIGN (kind, scheme) __PLUGIN_FEATURE(kind, PRIVKEY_SIGN, .privkey_sign = scheme)
Definition at line 286 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PUBKEY (kind, type) __PLUGIN_FEATURE(kind, PUBKEY, .pubkey = type)
Definition at line 288 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PUBKEY_ENCRYPT (kind, scheme) __PLUGIN_FEATURE(kind, PUBKEY_ENCRYPT, .pubkey_encrypt = scheme)
Definition at line 290 of file plugin_feature.h.
#define _PLUGIN_FEATURE_PUBKEY_VERIFY (kind, scheme) __PLUGIN_FEATURE(kind, PUBKEY_VERIFY, .pubkey_verify = scheme)
Definition at line 289 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_AEAD (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 309 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_CERT_DECODE (type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
Definition at line 319 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_CERT_ENCODE (type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
Definition at line 320 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_CONTAINER_DECODE (type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
Definition at line 321 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_CONTAINER_ENCODE (type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
Definition at line 322 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_CRYPTER (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 308 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_DATABASE (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 323 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_DH (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 313 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_FETCHER (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 324 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_HASHER (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 311 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_NONCE_GEN (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 315 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_PRF (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 312 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_PRIVKEY (type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
Definition at line 316 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_PRIVKEY_GEN (type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
Definition at line 317 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_PUBKEY (type, f, final) __PLUGIN_FEATURE_REGISTER_BUILDER(type, f, final)
Definition at line 318 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_RESOLVER (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 325 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_RNG (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 314 of file plugin_feature.h.
#define _PLUGIN_FEATURE_REGISTER_SIGNER (type, f) __PLUGIN_FEATURE_REGISTER(type, f)
Definition at line 310 of file plugin_feature.h.
#define _PLUGIN_FEATURE_RESOLVER (kind, ...) __PLUGIN_FEATURE(kind, RESOLVER, .custom = NULL)
Definition at line 301 of file plugin_feature.h.
#define _PLUGIN_FEATURE_RNG (kind, quality) __PLUGIN_FEATURE(kind, RNG, .rng_quality = quality)
Definition at line 282 of file plugin_feature.h.
#define _PLUGIN_FEATURE_SIGNER (kind, alg) __PLUGIN_FEATURE(kind, SIGNER, .signer = alg)
Definition at line 278 of file plugin_feature.h.
#define _PLUGIN_FEATURE_XAUTH_PEER (kind, name) __PLUGIN_FEATURE(kind, XAUTH_PEER, .xauth = name)
Definition at line 304 of file plugin_feature.h.
#define _PLUGIN_FEATURE_XAUTH_SERVER (kind, name) __PLUGIN_FEATURE(kind, XAUTH_SERVER, .xauth = name)
Definition at line 303 of file plugin_feature.h.
#define FEATURE (kind, type, ...) _PLUGIN_FEATURE_##type(kind, __VA_ARGS__)
Definition at line 227 of file plugin_feature.h.
#define PLUGIN_CALLBACK (cb, data) _PLUGIN_FEATURE_CALLBACK(cb, data)
Define a callback to invoke for registering all upcoming features.
Parameters
cb type specific callback function to register
data data pointer to pass to callback
Definition at line 244 of file plugin_feature.h.
Referenced by main(), METHOD(), nm_backend_register(), and test_runner_init().
#define PLUGIN_DEPENDS (type, ...) _PLUGIN_FEATURE_##type(DEPENDS, __VA_ARGS__)
Define a hard dependency for the previously defined feature.
Parameters
type feature type to provide
... type specific arguments
Definition at line 265 of file plugin_feature.h.
Referenced by add_feature_with_ssl(), init(), main(), METHOD(), and nm_backend_register().
#define PLUGIN_NOOP _PLUGIN_FEATURE_CALLBACK(NULL, NULL)
The upcoming features use neither a callback nor a register function.
Definition at line 249 of file plugin_feature.h.
Referenced by init(), and METHOD().
#define PLUGIN_PROVIDE (type, ...) _PLUGIN_FEATURE_##type(PROVIDE, __VA_ARGS__)
Define a feature the plugin provides.
Parameters
type feature type to provide
... type specific arguments
Definition at line 257 of file plugin_feature.h.
Referenced by af_alg_crypter_probe(), af_alg_hasher_probe(), af_alg_prf_probe(), af_alg_signer_probe(), init(), main(), METHOD(), nm_backend_register(), query_protocols(), register_dh_mapping(), test_bad_sigs(), test_good_sig(), and test_runner_init().
#define PLUGIN_REGISTER (type, f, ...) _PLUGIN_FEATURE_REGISTER_##type(type, f, ##__VA_ARGS__)
Define function to register directly for all upcoming features.
Parameters
type feature type to register
f type specific function to register
... type specific additional arguments
Definition at line 236 of file plugin_feature.h.
Referenced by main(), METHOD(), query_protocols(), register_dh_mapping(), and test_runner_init().
#define PLUGIN_SDEPEND (type, ...) _PLUGIN_FEATURE_##type(SDEPEND, __VA_ARGS__)
Define a soft dependency for the previously defined feature.
Parameters
type feature type to provide
... type specific arguments
Definition at line 273 of file plugin_feature.h.
Referenced by METHOD(), and nm_backend_register().
Typedef Documentation
typedef bool(* plugin_feature_callback_t)(plugin_t *plugin, plugin_feature_t *feature, bool reg, void *cb_data)
Callback function of a plugin to (un-)register a specified feature.
Parameters
plugin plugin instance
feature feature to register
reg TRUE to register, FALSE to unregister
cb_data user data passed with callback function
Returns
TRUE if registered successfully
Definition at line 43 of file plugin_feature.h.
typedef struct plugin_feature_t plugin_feature_t
Definition at line 27 of file plugin_feature.h.
Function Documentation
bool plugin_feature_equals (plugin_feature_t * a, plugin_feature_t * b)
Check if feature a equals feature b.
Parameters
a feature
b feature to compare
Returns
TRUE if a equals b
See header.
Definition at line 209 of file plugin_feature.c.
References plugin_feature_t::arg, plugin_feature_t::database, FALSE, plugin_feature_t::fetcher, plugin_feature_matches(), plugin_feature_t::rng_quality, streq(), and plugin_feature_t::type.
Referenced by loadable_feature_equals(), and registered_feature_equals().
 {
     if (a->type == b->type)
     {
         switch (a->type)
         {
             case FEATURE_NONE:
             case FEATURE_CRYPTER:
             case FEATURE_AEAD:
             case FEATURE_SIGNER:
             case FEATURE_HASHER:
             case FEATURE_PRF:
             case FEATURE_DH:
             case FEATURE_NONCE_GEN:
             case FEATURE_RESOLVER:
             case FEATURE_PRIVKEY:
             case FEATURE_PRIVKEY_GEN:
             case FEATURE_PUBKEY:
             case FEATURE_PRIVKEY_SIGN:
             case FEATURE_PUBKEY_VERIFY:
             case FEATURE_PRIVKEY_DECRYPT:
             case FEATURE_PUBKEY_ENCRYPT:
             case FEATURE_CERT_DECODE:
             case FEATURE_CERT_ENCODE:
             case FEATURE_CONTAINER_DECODE:
             case FEATURE_CONTAINER_ENCODE:
             case FEATURE_EAP_SERVER:
             case FEATURE_EAP_PEER:
             case FEATURE_CUSTOM:
             case FEATURE_XAUTH_SERVER:
             case FEATURE_XAUTH_PEER:
                 return plugin_feature_matches(a, b);
             case FEATURE_RNG:
                 return a->arg.rng_quality == b->arg.rng_quality;
             case FEATURE_DATABASE:
                 return a->arg.database == b->arg.database;
             case FEATURE_FETCHER:
                 if (a->arg.fetcher && b->arg.fetcher)
                 {
                     return streq(a->arg.fetcher, b->arg.fetcher);
                 }
                 return !a->arg.fetcher && !b->arg.fetcher;
         }
     }
     return FALSE;
 }
char* plugin_feature_get_string (plugin_feature_t * feature)
Get a string describing feature.
Parameters
feature feature to describe
Returns
allocated string describing feature
See header.
Definition at line 259 of file plugin_feature.c.
References plugin_feature_t::aead, plugin_feature_t::arg, asprintf(), plugin_feature_t::cert, certificate_type_names, plugin_feature_t::container, container_type_names, plugin_feature_t::crypter, plugin_feature_t::custom, plugin_feature_t::database, db_driver_names, plugin_feature_t::dh_group, diffie_hellman_group_names, plugin_feature_t::eap, eap_type_short_names, encryption_algorithm_names, encryption_scheme_names, plugin_feature_t::fetcher, hash_algorithm_names, plugin_feature_t::hasher, integrity_algorithm_names, key_type_names, plugin_feature_t::kind, plugin_feature_names, plugin_feature_t::prf, plugin_feature_t::privkey, plugin_feature_t::privkey_decrypt, plugin_feature_t::privkey_sign, pseudo_random_function_names, plugin_feature_t::rng_quality, rng_quality_names, signature_scheme_names, plugin_feature_t::signer, str, strdup, eap_vendor_type_t::type, plugin_feature_t::type, eap_vendor_type_t::vendor, and plugin_feature_t::xauth.
Referenced by list_plugins(), load_dependencies(), load_feature(), and load_provided().
 {
     char *str = NULL;
     if (feature->kind == FEATURE_REGISTER)
     {
         return strdup("(register function)");
     }
     switch (feature->type)
     {
         case FEATURE_NONE:
             return strdup("NONE");
         case FEATURE_CRYPTER:
             if (asprintf(&str, "%N:%N-%d", plugin_feature_names, feature->type,
                     encryption_algorithm_names, feature->arg.crypter.alg,
                     feature->arg.crypter.key_size) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_AEAD:
             if (asprintf(&str, "%N:%N-%d", plugin_feature_names, feature->type,
                     encryption_algorithm_names, feature->arg.aead.alg,
                     feature->arg.aead.key_size) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_SIGNER:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     integrity_algorithm_names, feature->arg.signer) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_HASHER:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     hash_algorithm_names, feature->arg.hasher) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_PRF:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     pseudo_random_function_names, feature->arg.prf) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_DH:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     diffie_hellman_group_names, feature->arg.dh_group) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_RNG:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     rng_quality_names, feature->arg.rng_quality) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_NONCE_GEN:
         case FEATURE_RESOLVER:
             if (asprintf(&str, "%N", plugin_feature_names, feature->type) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_PRIVKEY:
         case FEATURE_PRIVKEY_GEN:
         case FEATURE_PUBKEY:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     key_type_names, feature->arg.privkey) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_PRIVKEY_SIGN:
         case FEATURE_PUBKEY_VERIFY:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     signature_scheme_names, feature->arg.privkey_sign) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_PRIVKEY_DECRYPT:
         case FEATURE_PUBKEY_ENCRYPT:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     encryption_scheme_names, feature->arg.privkey_decrypt) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_CERT_DECODE:
         case FEATURE_CERT_ENCODE:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     certificate_type_names, feature->arg.cert) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_CONTAINER_DECODE:
         case FEATURE_CONTAINER_ENCODE:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     container_type_names, feature->arg.container) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_EAP_SERVER:
         case FEATURE_EAP_PEER:
             if (feature->arg.eap.vendor &&
                 asprintf(&str, "%N:%d-%d", plugin_feature_names, feature->type,
                     feature->arg.eap.type, feature->arg.eap.vendor) > 0)
             {
                 return str;
             }
             else if (!feature->arg.eap.vendor &&
                 asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     eap_type_short_names, feature->arg.eap.type) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_DATABASE:
             if (asprintf(&str, "%N:%N", plugin_feature_names, feature->type,
                     db_driver_names, feature->arg.database) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_FETCHER:
             if (asprintf(&str, "%N:%s", plugin_feature_names, feature->type,
                     feature->arg.fetcher) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_CUSTOM:
             if (asprintf(&str, "%N:%s", plugin_feature_names, feature->type,
                     feature->arg.custom) > 0)
             {
                 return str;
             }
             break;
         case FEATURE_XAUTH_SERVER:
         case FEATURE_XAUTH_PEER:
             if (asprintf(&str, "%N:%s", plugin_feature_names, feature->type,
                     feature->arg.xauth) > 0)
             {
                 return str;
             }
             break;
     }
     if (!str)
     {
         str = strdup("(invalid)");
     }
     return str;
 }
u_int32_t plugin_feature_hash (plugin_feature_t * feature)
Calculates a hash value for the given feature.
Since this is intended to be used with the plugin_features_matches function the hash is not really unique for all types of features (e.g. RNGs are all mapped to the same value because they are loosely matched by said function).
Parameters
feature feature to hash
Returns
hash value of the feature
See header.
Definition at line 60 of file plugin_feature.c.
References plugin_feature_t::aead, plugin_feature_t::arg, plugin_feature_t::cert, chunk_create(), chunk_empty, chunk_from_thing, chunk_hash(), chunk_hash_inc(), plugin_feature_t::container, plugin_feature_t::crypter, plugin_feature_t::custom, data, plugin_feature_t::dh_group, plugin_feature_t::eap, plugin_feature_t::hasher, plugin_feature_t::prf, plugin_feature_t::privkey, plugin_feature_t::privkey_decrypt, plugin_feature_t::privkey_gen, plugin_feature_t::privkey_sign, plugin_feature_t::pubkey, plugin_feature_t::pubkey_encrypt, plugin_feature_t::pubkey_verify, plugin_feature_t::signer, plugin_feature_t::type, and plugin_feature_t::xauth.
Referenced by registered_feature_hash().
 {
     chunk_t data = chunk_empty;
     switch (feature->type)
     {
         case FEATURE_NONE:
         case FEATURE_RNG:
         case FEATURE_NONCE_GEN:
         case FEATURE_DATABASE:
         case FEATURE_FETCHER:
         case FEATURE_RESOLVER:
             /* put these special cases in their (type-specific) buckets */
             data = chunk_empty;
             break;
         case FEATURE_CRYPTER:
             data = chunk_from_thing(feature->arg.crypter);
             break;
         case FEATURE_AEAD:
             data = chunk_from_thing(feature->arg.aead);
             break;
         case FEATURE_SIGNER:
             data = chunk_from_thing(feature->arg.signer);
             break;
         case FEATURE_HASHER:
             data = chunk_from_thing(feature->arg.hasher);
             break;
         case FEATURE_PRF:
             data = chunk_from_thing(feature->arg.prf);
             break;
         case FEATURE_DH:
             data = chunk_from_thing(feature->arg.dh_group);
             break;
         case FEATURE_PRIVKEY:
             data = chunk_from_thing(feature->arg.privkey);
             break;
         case FEATURE_PRIVKEY_GEN:
             data = chunk_from_thing(feature->arg.privkey_gen);
             break;
         case FEATURE_PUBKEY:
             data = chunk_from_thing(feature->arg.pubkey);
             break;
         case FEATURE_PRIVKEY_SIGN:
             data = chunk_from_thing(feature->arg.privkey_sign);
             break;
         case FEATURE_PUBKEY_VERIFY:
             data = chunk_from_thing(feature->arg.pubkey_verify);
             break;
         case FEATURE_PRIVKEY_DECRYPT:
             data = chunk_from_thing(feature->arg.privkey_decrypt);
             break;
         case FEATURE_PUBKEY_ENCRYPT:
             data = chunk_from_thing(feature->arg.pubkey_encrypt);
             break;
         case FEATURE_CERT_DECODE:
         case FEATURE_CERT_ENCODE:
             data = chunk_from_thing(feature->arg.cert);
             break;
         case FEATURE_CONTAINER_DECODE:
         case FEATURE_CONTAINER_ENCODE:
             data = chunk_from_thing(feature->arg.container);
             break;
         case FEATURE_EAP_SERVER:
         case FEATURE_EAP_PEER:
             data = chunk_from_thing(feature->arg.eap);
             break;
         case FEATURE_CUSTOM:
             data = chunk_create(feature->arg.custom,
                                 strlen(feature->arg.custom));
             break;
         case FEATURE_XAUTH_SERVER:
         case FEATURE_XAUTH_PEER:
             data = chunk_create(feature->arg.xauth,
                                 strlen(feature->arg.xauth));
             break;
     }
     return chunk_hash_inc(chunk_from_thing(feature->type),
                           chunk_hash(data));
 }
bool plugin_feature_load (plugin_t * plugin, plugin_feature_t * feature, plugin_feature_t * reg)
Load a plugin feature using a REGISTER/CALLBACK feature entry.
Parameters
plugin plugin providing feature
feature feature to load
reg REGISTER/CALLBACK feature entry to use for registration
See header.
Definition at line 425 of file plugin_feature.c.
References crypto_factory_t::add_aead, credential_factory_t::add_builder, crypto_factory_t::add_crypter, database_factory_t::add_database, crypto_factory_t::add_dh, fetcher_manager_t::add_fetcher, crypto_factory_t::add_hasher, crypto_factory_t::add_nonce_gen, crypto_factory_t::add_prf, resolver_manager_t::add_resolver, crypto_factory_t::add_rng, crypto_factory_t::add_signer, plugin_feature_t::aead, plugin_feature_t::arg, plugin_feature_t::cb, plugin_feature_t::cert, plugin_feature_t::container, CRED_CERTIFICATE, CRED_CONTAINER, CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, library_t::creds, plugin_feature_t::crypter, library_t::crypto, library_t::db, plugin_feature_t::dh_group, FALSE, library_t::fetcher, plugin_feature_t::fetcher, plugin_t::get_name, plugin_feature_t::hasher, plugin_feature_t::kind, lib, name, plugin_feature_t::prf, plugin_feature_t::privkey, plugin_feature_t::pubkey, plugin_feature_t::reg, library_t::resolver, plugin_feature_t::rng_quality, plugin_feature_t::signer, TRUE, and plugin_feature_t::type.
Referenced by load_feature().
 {
     char *name;
     if (!reg)
     {   /* noting to do for this feature */
         return TRUE;
     }
     if (reg->kind == FEATURE_CALLBACK)
     {
         if (!reg->arg.cb.f ||
              reg->arg.cb.f(plugin, feature, TRUE, reg->arg.cb.data))
         {
             return TRUE;
         }
         return FALSE;
     }
     name = plugin->get_name(plugin);
     switch (feature->type)
     {
         case FEATURE_CRYPTER:
             lib->crypto->add_crypter(lib->crypto, feature->arg.crypter.alg,
                                 feature->arg.crypter.key_size,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_AEAD:
             lib->crypto->add_aead(lib->crypto, feature->arg.aead.alg,
                                 feature->arg.aead.key_size,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_SIGNER:
             lib->crypto->add_signer(lib->crypto, feature->arg.signer,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_HASHER:
             lib->crypto->add_hasher(lib->crypto, feature->arg.hasher,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_PRF:
             lib->crypto->add_prf(lib->crypto, feature->arg.prf,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_DH:
             lib->crypto->add_dh(lib->crypto, feature->arg.dh_group,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_RNG:
             lib->crypto->add_rng(lib->crypto, feature->arg.rng_quality,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_NONCE_GEN:
             lib->crypto->add_nonce_gen(lib->crypto,
                                 name, reg->arg.reg.f);
             break;
         case FEATURE_PRIVKEY:
         case FEATURE_PRIVKEY_GEN:
             lib->creds->add_builder(lib->creds, CRED_PRIVATE_KEY,
                                 feature->arg.privkey, reg->arg.reg.final,
                                 reg->arg.reg.f);
             break;
         case FEATURE_PUBKEY:
             lib->creds->add_builder(lib->creds, CRED_PUBLIC_KEY,
                                 feature->arg.pubkey, reg->arg.reg.final,
                                 reg->arg.reg.f);
             break;
         case FEATURE_CERT_DECODE:
         case FEATURE_CERT_ENCODE:
             lib->creds->add_builder(lib->creds, CRED_CERTIFICATE,
                                 feature->arg.cert, reg->arg.reg.final,
                                 reg->arg.reg.f);
             break;
         case FEATURE_CONTAINER_DECODE:
         case FEATURE_CONTAINER_ENCODE:
             lib->creds->add_builder(lib->creds, CRED_CONTAINER,
                                 feature->arg.container, reg->arg.reg.final,
                                 reg->arg.reg.f);
             break;
         case FEATURE_DATABASE:
             lib->db->add_database(lib->db, reg->arg.reg.f);
             break;
         case FEATURE_FETCHER:
             lib->fetcher->add_fetcher(lib->fetcher, reg->arg.reg.f,
                                       feature->arg.fetcher);
             break;
         case FEATURE_RESOLVER:
             lib->resolver->add_resolver(lib->resolver, reg->arg.reg.f);
             break;
         default:
             break;
     }
     return TRUE;
 }
bool plugin_feature_matches (plugin_feature_t * a, plugin_feature_t * b)
Check if feature a matches to feature b.
This is no check for equality. For instance, for FEATURE_RNG a matches b if a's strength is at least the strength of b. Or for FEATURE_SQL if a is DB_ANY it will match b if it is of the same type.
Parameters
a feature to check
b feature to match against
Returns
TRUE if a matches b
See header.
Definition at line 143 of file plugin_feature.c.
References plugin_feature_t::aead, plugin_feature_t::arg, plugin_feature_t::cert, plugin_feature_t::container, plugin_feature_t::crypter, plugin_feature_t::custom, plugin_feature_t::database, DB_ANY, plugin_feature_t::dh_group, plugin_feature_t::eap, FALSE, plugin_feature_t::fetcher, plugin_feature_t::hasher, plugin_feature_t::prf, plugin_feature_t::privkey, plugin_feature_t::privkey_decrypt, plugin_feature_t::privkey_sign, plugin_feature_t::rng_quality, plugin_feature_t::signer, streq(), TRUE, eap_vendor_type_t::type, plugin_feature_t::type, eap_vendor_type_t::vendor, and plugin_feature_t::xauth.
Referenced by loadable_feature_matches(), loaded_feature_matches(), METHOD(), and plugin_feature_equals().
 {
     if (a->type == b->type)
     {
         switch (a->type)
         {
             case FEATURE_NONE:
                 return FALSE;
             case FEATURE_CRYPTER:
                 return a->arg.crypter.alg == b->arg.crypter.alg &&
                        a->arg.crypter.key_size == b->arg.crypter.key_size;
             case FEATURE_AEAD:
                 return a->arg.aead.alg == b->arg.aead.alg &&
                        a->arg.aead.key_size == b->arg.aead.key_size;
             case FEATURE_SIGNER:
                 return a->arg.signer == b->arg.signer;
             case FEATURE_HASHER:
                 return a->arg.hasher == b->arg.hasher;
             case FEATURE_PRF:
                 return a->arg.prf == b->arg.prf;
             case FEATURE_DH:
                 return a->arg.dh_group == b->arg.dh_group;
             case FEATURE_RNG:
                 return a->arg.rng_quality <= b->arg.rng_quality;
             case FEATURE_NONCE_GEN:
             case FEATURE_RESOLVER:
                 return TRUE;
             case FEATURE_PRIVKEY:
             case FEATURE_PRIVKEY_GEN:
             case FEATURE_PUBKEY:
                 return a->arg.privkey == b->arg.privkey;
             case FEATURE_PRIVKEY_SIGN:
             case FEATURE_PUBKEY_VERIFY:
                 return a->arg.privkey_sign == b->arg.privkey_sign;
             case FEATURE_PRIVKEY_DECRYPT:
             case FEATURE_PUBKEY_ENCRYPT:
                 return a->arg.privkey_decrypt == b->arg.privkey_decrypt;
             case FEATURE_CERT_DECODE:
             case FEATURE_CERT_ENCODE:
                 return a->arg.cert == b->arg.cert;
             case FEATURE_CONTAINER_DECODE:
             case FEATURE_CONTAINER_ENCODE:
                 return a->arg.container == b->arg.container;
             case FEATURE_EAP_SERVER:
             case FEATURE_EAP_PEER:
                 return a->arg.eap.vendor == b->arg.eap.vendor &&
                        a->arg.eap.type == b->arg.eap.type;
             case FEATURE_DATABASE:
                 return a->arg.database == DB_ANY ||
                        a->arg.database == b->arg.database;
             case FEATURE_FETCHER:
                 return a->arg.fetcher == NULL ||
                        streq(a->arg.fetcher, b->arg.fetcher);
             case FEATURE_CUSTOM:
                 return streq(a->arg.custom, b->arg.custom);
             case FEATURE_XAUTH_SERVER:
             case FEATURE_XAUTH_PEER:
                 return streq(a->arg.xauth, b->arg.xauth);
         }
     }
     return FALSE;
 }
bool plugin_feature_unload (plugin_t * plugin, plugin_feature_t * feature, plugin_feature_t * reg)
Unload a plugin feature using a REGISTER/CALLBACK feature entry.
Parameters
plugin plugin providing feature
feature feature to unload
reg REGISTER/CALLBACK feature entry to use for deregistration
See header.
Definition at line 522 of file plugin_feature.c.
References plugin_feature_t::arg, plugin_feature_t::cb, library_t::creds, library_t::crypto, library_t::db, FALSE, library_t::fetcher, plugin_feature_t::kind, lib, plugin_feature_t::reg, crypto_factory_t::remove_aead, credential_factory_t::remove_builder, crypto_factory_t::remove_crypter, database_factory_t::remove_database, crypto_factory_t::remove_dh, fetcher_manager_t::remove_fetcher, crypto_factory_t::remove_hasher, crypto_factory_t::remove_nonce_gen, crypto_factory_t::remove_prf, resolver_manager_t::remove_resolver, crypto_factory_t::remove_rng, crypto_factory_t::remove_signer, library_t::resolver, TRUE, and plugin_feature_t::type.
Referenced by unload_features().
 {
     if (!reg)
     {   /* noting to do for this feature */
         return TRUE;
     }
     if (reg->kind == FEATURE_CALLBACK)
     {
         if (!reg->arg.cb.f ||
              reg->arg.cb.f(plugin, feature, FALSE, reg->arg.cb.data))
         {
             return TRUE;
         }
         return FALSE;
     }
     switch (feature->type)
     {
         case FEATURE_CRYPTER:
             lib->crypto->remove_crypter(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_AEAD:
             lib->crypto->remove_aead(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_SIGNER:
             lib->crypto->remove_signer(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_HASHER:
             lib->crypto->remove_hasher(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_PRF:
             lib->crypto->remove_prf(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_DH:
             lib->crypto->remove_dh(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_RNG:
             lib->crypto->remove_rng(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_NONCE_GEN:
             lib->crypto->remove_nonce_gen(lib->crypto, reg->arg.reg.f);
             break;
         case FEATURE_PRIVKEY:
         case FEATURE_PRIVKEY_GEN:
             lib->creds->remove_builder(lib->creds, reg->arg.reg.f);
             break;
         case FEATURE_PUBKEY:
             lib->creds->remove_builder(lib->creds, reg->arg.reg.f);
             break;
         case FEATURE_CERT_DECODE:
         case FEATURE_CERT_ENCODE:
             lib->creds->remove_builder(lib->creds, reg->arg.reg.f);
             break;
         case FEATURE_CONTAINER_DECODE:
         case FEATURE_CONTAINER_ENCODE:
             lib->creds->remove_builder(lib->creds, reg->arg.reg.f);
             break;
         case FEATURE_DATABASE:
             lib->db->remove_database(lib->db, reg->arg.reg.f);
             break;
         case FEATURE_FETCHER:
             lib->fetcher->remove_fetcher(lib->fetcher, reg->arg.reg.f);
             break;
         case FEATURE_RESOLVER:
             lib->resolver->remove_resolver(lib->resolver, reg->arg.reg.f);
             break;
         default:
             break;
     }
     return TRUE;
 }
static void plugin_features_add (plugin_feature_t * features, plugin_feature_t * to_add, int count, int * pos) inline static
Add a set of plugin features to the given array, which must have enough space to store the added features.
Parameters
features the array of plugin features to extend
to_add the features to add
count number of features to add
pos current position in the features array, gets advanced
Definition at line 343 of file plugin_feature.h.
References count.
Referenced by METHOD().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         features[(*pos)++] = to_add[i];
     }
 }
Variable Documentation
enum_name_t* plugin_feature_names
Names for plugin_feature_t types.
Referenced by plugin_feature_get_string().