strongSwan: pa_tnc_msg_t Struct Reference
pa_tnc_msg_t Struct Reference
pa_tnc_msg
#include "pa_tnc_msg.h"
Public Attributes
chunk_t(* get_encoding)(pa_tnc_msg_t *this)
size_t(* get_space)(pa_tnc_msg_t *this)
bool(* add_attribute)(pa_tnc_msg_t *this, pa_tnc_attr_t *attr)
bool(* build)(pa_tnc_msg_t *this)
status_t(* process)(pa_tnc_msg_t *this)
bool(* process_ietf_std_errors)(pa_tnc_msg_t *this, linked_list_t *non_fatal_types)
enumerator_t *(* create_attribute_enumerator)(pa_tnc_msg_t *this)
enumerator_t *(* create_error_enumerator)(pa_tnc_msg_t *this)
void(* destroy)(pa_tnc_msg_t *this)
Detailed Description
Interface for the RFC 5792 PA-TNC Posture Attribute protocol.
Definition at line 37 of file pa_tnc_msg.h.
Member Data Documentation
bool(* pa_tnc_msg_t::add_attribute)(pa_tnc_msg_t *this, pa_tnc_attr_t *attr)
Add a PA-TNC attribute
Parameters
attr PA-TNC attribute to be addedd
Returns
TRUE if attribute fit into message and was added
Definition at line 59 of file pa_tnc_msg.h.
Referenced by METHOD().
bool(* pa_tnc_msg_t::build)(pa_tnc_msg_t *this)
Build the PA-TNC message
Returns
TRUE if PA-TNC message was built successfully
Definition at line 66 of file pa_tnc_msg.h.
Referenced by METHOD().
enumerator_t*(* pa_tnc_msg_t::create_attribute_enumerator)(pa_tnc_msg_t *this)
Enumerates over all PA-TNC attributes
Returns
return attribute enumerator
Definition at line 89 of file pa_tnc_msg.h.
enumerator_t*(* pa_tnc_msg_t::create_error_enumerator)(pa_tnc_msg_t *this)
Enumerates over all parsing errors
Returns
return error enumerator
Definition at line 96 of file pa_tnc_msg.h.
void(* pa_tnc_msg_t::destroy)(pa_tnc_msg_t *this)
Destroys a pa_tnc_msg_t object.
Definition at line 101 of file pa_tnc_msg.h.
Referenced by METHOD().
chunk_t(* pa_tnc_msg_t::get_encoding)(pa_tnc_msg_t *this)
Get the encoding of the PA-TNC message
Returns
encoded PA-TNC message
Definition at line 44 of file pa_tnc_msg.h.
Referenced by METHOD().
size_t(* pa_tnc_msg_t::get_space)(pa_tnc_msg_t *this)
Get the remaining space in octets left in the PA-TNC message
Returns
remaining space or 0 if max_msg_len is not set
Definition at line 51 of file pa_tnc_msg.h.
Referenced by METHOD().
status_t(* pa_tnc_msg_t::process)(pa_tnc_msg_t *this)
Process the PA-TNC message
Returns
return processing status
Definition at line 73 of file pa_tnc_msg.h.
bool(* pa_tnc_msg_t::process_ietf_std_errors)(pa_tnc_msg_t *this, linked_list_t *non_fatal_types)
Process all IETF standard error PA-TNC attributes
Parameters
non_fatal_types list of non fatal unsupported attribute types
Returns
TRUE if at least one fatal error processed
Definition at line 81 of file pa_tnc_msg.h.
The documentation for this struct was generated from the following file:
pa_tnc_msg.h