strongSwan: trap_manager
trap_manager
sa
Classes
struct trap_manager_t
Typedefs
typedef struct trap_manager_t trap_manager_t
Functions
trap_manager_t * trap_manager_create ()
Detailed Description
Typedef Documentation
typedef struct trap_manager_t trap_manager_t
Definition at line 28 of file trap_manager.h.
Function Documentation
trap_manager_t* trap_manager_create (void)
Create a trap_manager instance.
See header
Definition at line 642 of file trap_manager.c.
References bus_t::add_listener, daemon_t::bus, charon, FALSE, settings_t::get_bool, INIT, lib, linked_list_create(), mutex_t::lock, mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, rwlock_condvar_create(), rwlock_create(), RWLOCK_TYPE_DEFAULT, and library_t::settings.
Referenced by daemon_create().
 {
     private_trap_manager_t *this;
     INIT(this,
         .public = {
             .install = _install,
             .uninstall = _uninstall,
             .create_enumerator = _create_enumerator,
             .find_reqid = _find_reqid,
             .acquire = _acquire,
             .flush = _flush,
             .destroy = _destroy,
         },
         .listener = {
             .traps = this,
             .listener = {
                 .ike_state_change = _ike_state_change,
                 .child_state_change = _child_state_change,
             },
         },
         .traps = linked_list_create(),
         .acquires = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .condvar = rwlock_condvar_create(),
         .ignore_acquire_ts = lib->settings->get_bool(lib->settings,
                                         "%s.ignore_acquire_ts", FALSE, lib->ns),
     );
     charon->bus->add_listener(charon->bus, &this->listener.listener);
     return &this->public;
 }