strongSwan: scep.h File Reference
scep.h File Reference
#include <credentials/containers/pkcs7.h>
#include <credentials/certificates/certificate.h>
Classes
struct scep_attributes_t
Enumerations
enum scep_op_t { SCEP_PKI_OPERATION, SCEP_GET_CA_CERT }
enum pkiStatus_t { SCEP_SUCCESS, SCEP_FAILURE, SCEP_PENDING, SCEP_UNKNOWN }
enum scep_msg_t {
SCEP_CertRep_MSG, SCEP_PKCSReq_MSG, SCEP_GetCertInitial_MSG, SCEP_GetCert_MSG,
SCEP_GetCRL_MSG, SCEP_Unknown_MSG
}
enum failInfo_t {
SCEP_badAlg_REASON = 0, SCEP_badMessageCheck_REASON = 1, SCEP_badRequest_REASON = 2, SCEP_badTime_REASON = 3,
SCEP_badCertId_REASON = 4, SCEP_unknown_REASON = 5
}
Functions
bool parse_attributes (chunk_t blob, scep_attributes_t *attrs)
void scep_generate_transaction_id (public_key_t *key, chunk_t *transID, chunk_t *serialNumber)
chunk_t scep_generate_pkcs10_fingerprint (chunk_t pkcs10)
chunk_t scep_transId_attribute (chunk_t transaction_id)
chunk_t scep_messageType_attribute (scep_msg_t m)
chunk_t scep_senderNonce_attribute (void)
chunk_t scep_build_request (chunk_t data, chunk_t transID, scep_msg_t msg, certificate_t *enc_cert, encryption_algorithm_t enc_alg, size_t key_size, certificate_t *signer_cert, hash_algorithm_t digest_alg, private_key_t *private_key)
bool scep_http_request (const char *url, chunk_t msg, scep_op_t op, bool http_get_request, u_int timeout, char *src, chunk_t *response)
err_t scep_parse_response (chunk_t response, chunk_t transID, container_t **out, scep_attributes_t *attrs)
Variables
const scep_attributes_t empty_scep_attributes
Enumeration Type Documentation
enum failInfo_t
Enumerator
SCEP_badAlg_REASON
SCEP_badMessageCheck_REASON
SCEP_badRequest_REASON
SCEP_badTime_REASON
SCEP_badCertId_REASON
SCEP_unknown_REASON
Definition at line 48 of file scep.h.
              {
    SCEP_badAlg_REASON =          0,
    SCEP_badMessageCheck_REASON = 1,
    SCEP_badRequest_REASON =      2,
    SCEP_badTime_REASON =         3,
    SCEP_badCertId_REASON =       4,
    SCEP_unknown_REASON =         5
 } failInfo_t;
enum pkiStatus_t
Enumerator
SCEP_SUCCESS
SCEP_FAILURE
SCEP_PENDING
SCEP_UNKNOWN
Definition at line 30 of file scep.h.
              {
    SCEP_SUCCESS,
    SCEP_FAILURE,
    SCEP_PENDING,
    SCEP_UNKNOWN
 } pkiStatus_t;
enum scep_msg_t
Enumerator
SCEP_CertRep_MSG
SCEP_PKCSReq_MSG
SCEP_GetCertInitial_MSG
SCEP_GetCert_MSG
SCEP_GetCRL_MSG
SCEP_Unknown_MSG
Definition at line 38 of file scep.h.
              {
    SCEP_CertRep_MSG,
    SCEP_PKCSReq_MSG,
    SCEP_GetCertInitial_MSG,
    SCEP_GetCert_MSG,
    SCEP_GetCRL_MSG,
    SCEP_Unknown_MSG
 } scep_msg_t;
enum scep_op_t
Enumerator
SCEP_PKI_OPERATION
SCEP_GET_CA_CERT
Definition at line 24 of file scep.h.
              {
     SCEP_PKI_OPERATION,
     SCEP_GET_CA_CERT
 } scep_op_t;
Function Documentation
bool parse_attributes (chunk_t blob, scep_attributes_t * attrs)
chunk_t scep_build_request (chunk_t data, chunk_t transID, scep_msg_t msg, certificate_t * enc_cert, encryption_algorithm_t enc_alg, size_t key_size, certificate_t * signer_cert, hash_algorithm_t digest_alg, private_key_t * private_key)
Builds a pkcs7 enveloped and signed scep request
Definition at line 199 of file scep.c.
References ASN1_OCTET_STRING, ASN1_PRINTABLESTRING, asn1_wrap(), BUILD_BLOB, BUILD_CERT, BUILD_DIGEST_ALG, BUILD_ENCRYPTION_ALG, BUILD_END, BUILD_KEY_SIZE, BUILD_PKCS7_ATTRIBUTE, BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, chunk_create(), chunk_empty, chunk_from_thing, CONTAINER_PKCS7_ENVELOPED_DATA, CONTAINER_PKCS7_SIGNED_DATA, credential_factory_t::create, crypto_factory_t::create_rng, CRED_CONTAINER, library_t::creds, library_t::crypto, rng_t::destroy, container_t::destroy, DESTROY_IF, free(), rng_t::get_bytes, container_t::get_encoding, lib, msgType_values, OID_PKI_MESSAGE_TYPE, OID_PKI_SENDER_NONCE, OID_PKI_TRANS_ID, chunk_t::ptr, request(), rng, and RNG_WEAK.
Referenced by main().
 {
     chunk_t request;
     container_t *container;
     char nonce[16];
     rng_t *rng;
     chunk_t senderNonce, msgType;
     /* generate senderNonce */
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng || !rng->get_bytes(rng, sizeof(nonce), nonce))
     {
         DESTROY_IF(rng);
         return chunk_empty;
     }
     rng->destroy(rng);
     /* encrypt data in enveloped-data PKCS#7 */
     container = lib->creds->create(lib->creds,
                     CRED_CONTAINER, CONTAINER_PKCS7_ENVELOPED_DATA,
                     BUILD_BLOB, data,
                     BUILD_CERT, enc_cert,
                     BUILD_ENCRYPTION_ALG, enc_alg,
                     BUILD_KEY_SIZE, (int)key_size,
                     BUILD_END);
     if (!container)
     {
         return chunk_empty;
     }
     if (!container->get_encoding(container, &request))
     {
         container->destroy(container);
         return chunk_empty;
     }
     container->destroy(container);
     /* sign enveloped-data in a signed-data PKCS#7 */
     senderNonce = asn1_wrap(ASN1_OCTET_STRING, "c", chunk_from_thing(nonce));
     transID = asn1_wrap(ASN1_PRINTABLESTRING, "c", transID);
     msgType = asn1_wrap(ASN1_PRINTABLESTRING, "c",
                         chunk_create((char*)msgType_values[msg],
                                      strlen(msgType_values[msg])));
     container = lib->creds->create(lib->creds,
                     CRED_CONTAINER, CONTAINER_PKCS7_SIGNED_DATA,
                     BUILD_BLOB, request,
                     BUILD_SIGNING_CERT, signer_cert,
                     BUILD_SIGNING_KEY, private_key,
                     BUILD_DIGEST_ALG, digest_alg,
                     BUILD_PKCS7_ATTRIBUTE, OID_PKI_SENDER_NONCE, senderNonce,
                     BUILD_PKCS7_ATTRIBUTE, OID_PKI_TRANS_ID, transID,
                     BUILD_PKCS7_ATTRIBUTE, OID_PKI_MESSAGE_TYPE, msgType,
                     BUILD_END);
     free(request.ptr);
     free(senderNonce.ptr);
     free(transID.ptr);
     free(msgType.ptr);
     if (!container)
     {
         return chunk_empty;
     }
     if (!container->get_encoding(container, &request))
     {
         container->destroy(container);
         return chunk_empty;
     }
     container->destroy(container);
     return request;
 }
chunk_t scep_generate_pkcs10_fingerprint (chunk_t pkcs10)
Generates a unique fingerprint of the pkcs10 request by computing an MD5 hash over it
Definition at line 128 of file scep.c.
References chunk_alloca, chunk_empty, chunk_to_hex(), crypto_factory_t::create_hasher, library_t::crypto, hasher_t::destroy, DESTROY_IF, FALSE, hasher_t::get_hash, HASH_MD5, HASH_SIZE_MD5, hasher, lib, and chunk_t::ptr.
Referenced by main().
 {
     chunk_t digest = chunk_alloca(HASH_SIZE_MD5);
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_MD5);
     if (!hasher || !hasher->get_hash(hasher, pkcs10, digest.ptr))
     {
         DESTROY_IF(hasher);
         return chunk_empty;
     }
     hasher->destroy(hasher);
     return chunk_to_hex(digest, NULL, FALSE);
 }
void scep_generate_transaction_id (public_key_t * key, chunk_t * transID, chunk_t * serialNumber)
Generate a transaction id as the MD5 hash of an public key the transaction id is also used as a unique serial number
Definition at line 148 of file scep.c.
References asn1_algorithmIdentifier(), asn1_bitstring(), ASN1_SEQUENCE, asn1_wrap(), chunk_alloc, chunk_alloca, chunk_empty, chunk_to_hex(), crypto_factory_t::create_hasher, library_t::crypto, DESTROY_IF, free(), public_key_t::get_encoding, hasher_t::get_hash, HASH_MD5, HASH_SIZE_MD5, hasher, chunk_t::len, lib, memcpy, memset, OID_RSA_ENCRYPTION, chunk_t::ptr, PUBKEY_ASN1_DER, and TRUE.
Referenced by main().
 {
     chunk_t digest = chunk_alloca(HASH_SIZE_MD5);
     chunk_t keyEncoding = chunk_empty, keyInfo;
     hasher_t *hasher;
     int zeros = 0, msb_set = 0;
     key->get_encoding(key, PUBKEY_ASN1_DER, &keyEncoding);
     keyInfo = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_algorithmIdentifier(OID_RSA_ENCRYPTION),
                         asn1_bitstring("m", keyEncoding));
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_MD5);
     if (!hasher || !hasher->get_hash(hasher, keyInfo, digest.ptr))
     {
         memset(digest.ptr, 0, digest.len);
     }
     DESTROY_IF(hasher);
     free(keyInfo.ptr);
     /* the serialNumber should be valid ASN1 integer content:
      * remove leading zeros, add one if MSB is set (two's complement) */
     while (zeros < digest.len)
     {
         if (digest.ptr[zeros])
         {
             if (digest.ptr[zeros] & 0x80)
             {
                 msb_set = 1;
             }
             break;
         }
         zeros++;
     }
     *serialNumber = chunk_alloc(digest.len - zeros + msb_set);
     if (msb_set)
     {
         serialNumber->ptr[0] = 0x00;
     }
     memcpy(serialNumber->ptr + msb_set, digest.ptr + zeros,
            digest.len - zeros);
     /* the transaction id is the serial number in hex format */
     *transID = chunk_to_hex(digest, NULL, TRUE);
 }
bool scep_http_request (const char * url, chunk_t msg, scep_op_t op, bool http_get_request, u_int timeout, char * src, chunk_t * response)
Send a SCEP request via HTTP and wait for a response
Definition at line 341 of file scep.c.
References chunk_empty, DBG2, DBG_APP, DESTROY_IF, escape_http_request(), fetcher_manager_t::fetch, FETCH_END, FETCH_HTTP_VERSION_1_0, FETCH_REQUEST_DATA, FETCH_REQUEST_HEADER, FETCH_REQUEST_TYPE, FETCH_SOURCEIP, FETCH_TIMEOUT, library_t::fetcher, free(), host_create_from_string(), chunk_t::len, len, lib, malloc(), chunk_t::ptr, SCEP_PKI_OPERATION, snprintf, status, and SUCCESS.
Referenced by main().
 {
     int len;
     status_t status;
     char *complete_url = NULL;
     host_t *srcip = NULL;
     /* initialize response */
     *response = chunk_empty;
     if (src)
     {
         srcip = host_create_from_string(src, 0);
     }
     DBG2(DBG_APP, "sending scep request to '%s'", url);
     if (op == SCEP_PKI_OPERATION)
     {
         const char operation[] = "PKIOperation";
         if (http_get_request)
         {
             char *escaped_req = escape_http_request(msg);
             /* form complete url */
             len = strlen(url) + 20 + strlen(operation) + strlen(escaped_req) + 1;
             complete_url = malloc(len);
             snprintf(complete_url, len, "%s?operation=%s&message=%s"
                     , url, operation, escaped_req);
             free(escaped_req);
             status = lib->fetcher->fetch(lib->fetcher, complete_url, response,
                                          FETCH_HTTP_VERSION_1_0,
                                          FETCH_TIMEOUT, timeout,
                                          FETCH_REQUEST_HEADER, "Pragma:",
                                          FETCH_REQUEST_HEADER, "Host:",
                                          FETCH_REQUEST_HEADER, "Accept:",
                                          FETCH_SOURCEIP, srcip,
                                          FETCH_END);
         }
         else /* HTTP_POST */
         {
             /* form complete url */
             len = strlen(url) + 11 + strlen(operation) + 1;
             complete_url = malloc(len);
             snprintf(complete_url, len, "%s?operation=%s", url, operation);
             status = lib->fetcher->fetch(lib->fetcher, complete_url, response,
                                          FETCH_HTTP_VERSION_1_0,
                                          FETCH_TIMEOUT, timeout,
                                          FETCH_REQUEST_DATA, msg,
                                          FETCH_REQUEST_TYPE, "",
                                          FETCH_REQUEST_HEADER, "Expect:",
                                          FETCH_SOURCEIP, srcip,
                                          FETCH_END);
         }
     }
     else  /* SCEP_GET_CA_CERT */
     {
         const char operation[] = "GetCACert";
         int i;
         /* escape spaces, TODO: complete URL escape */
         for (i = 0; i < msg.len; i++)
         {
             if (msg.ptr[i] == ' ')
             {
                 msg.ptr[i] = '+';
             }
         }
         /* form complete url */
         len = strlen(url) + 32 + strlen(operation) + msg.len + 1;
         complete_url = malloc(len);
         snprintf(complete_url, len, "%s?operation=%s&message=%.*s",
                  url, operation, (int)msg.len, msg.ptr);
         status = lib->fetcher->fetch(lib->fetcher, complete_url, response,
                                      FETCH_HTTP_VERSION_1_0,
                                      FETCH_TIMEOUT, timeout,
                                      FETCH_SOURCEIP, srcip,
                                      FETCH_END);
     }
     DESTROY_IF(srcip);
     free(complete_url);
     return (status == SUCCESS);
 }
chunk_t scep_messageType_attribute (scep_msg_t m)
err_t scep_parse_response (chunk_t response, chunk_t transID, container_t ** out, scep_attributes_t * attrs)
Definition at line 433 of file scep.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, chunk_equals(), CONTAINER_PKCS7, CONTAINER_PKCS7_SIGNED_DATA, credential_factory_t::create, container_t::create_signature_enumerator, CRED_CONTAINER, library_t::creds, enumerator_t::destroy, container_t::destroy, enumerator_t::enumerate, extract_attributes(), FALSE, container_t::get_type, lib, scep_attributes_t::transID, and TRUE.
Referenced by main().
 {
     enumerator_t *enumerator;
     bool verified = FALSE;
     container_t *container;
     auth_cfg_t *auth;
     container = lib->creds->create(lib->creds, CRED_CONTAINER, CONTAINER_PKCS7,
                                    BUILD_BLOB_ASN1_DER, response, BUILD_END);
     if (!container)
     {
         return "error parsing the scep response";
     }
     if (container->get_type(container) != CONTAINER_PKCS7_SIGNED_DATA)
     {
         container->destroy(container);
         return "scep response is not PKCS#7 signed-data";
     }
     enumerator = container->create_signature_enumerator(container);
     while (enumerator->enumerate(enumerator, &auth))
     {
         verified = TRUE;
         extract_attributes((pkcs7_t*)container, enumerator, attrs);
         if (!chunk_equals(transID, attrs->transID))
         {
             enumerator->destroy(enumerator);
             container->destroy(container);
             return "transaction ID of scep response does not match";
         }
     }
     enumerator->destroy(enumerator);
     if (!verified)
     {
         container->destroy(container);
         return "unable to verify PKCS#7 container";
     }
     *out = container;
     return NULL;
 }
chunk_t scep_senderNonce_attribute (void)
chunk_t scep_transId_attribute (chunk_t transaction_id)
Variable Documentation
const scep_attributes_t empty_scep_attributes
Definition at line 58 of file scep.c.
Referenced by main().