strongSwan: maemo_service
maemo_service
maemo
Classes
struct maemo_service_t
Typedefs
typedef struct maemo_service_t maemo_service_t
Functions
maemo_service_t * maemo_service_create ()
Detailed Description
Typedef Documentation
typedef struct maemo_service_t maemo_service_t
Definition at line 26 of file maemo_service.h.
Function Documentation
maemo_service_t* maemo_service_create ()
Create an instance of maemo_service_t.
Definition at line 476 of file maemo_service.c.
References credential_manager_t::add_set, callback_job_create_with_prio(), cancel(), context, library_t::credmgr, DBG1, DBG_CFG, dbus_req_handler(), destroy(), INIT, JOB_PRIO_CRITICAL, lib, mem_cred_create(), OSSO_CHARON_IFACE, OSSO_CHARON_OBJECT, OSSO_CHARON_SERVICE, library_t::processor, processor_t::queue_job, result, run(), and TRUE.
Referenced by maemo_plugin_create().
 {
     osso_return_t result;
     private_maemo_service_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .ike_updown = _ike_updown,
                 .ike_state_change = _ike_state_change,
                 .child_updown = _child_updown,
                 .ike_rekey = _ike_rekey,
             },
             .destroy = _destroy,
         },
         .creds = mem_cred_create(),
     );
     lib->credmgr->add_set(lib->credmgr, &this->creds->set);
     this->context = osso_initialize(OSSO_CHARON_SERVICE, "0.0.1", TRUE, NULL);
     if (!this->context)
     {
         DBG1(DBG_CFG, "failed to initialize OSSO context");
         destroy(this);
         return NULL;
     }
     result = osso_rpc_set_cb_f(this->context,
                                OSSO_CHARON_SERVICE,
                                OSSO_CHARON_OBJECT,
                                OSSO_CHARON_IFACE,
                                (osso_rpc_cb_f*)dbus_req_handler,
                                this);
     if (result != OSSO_OK)
     {
         DBG1(DBG_CFG, "failed to set D-BUS callback (%d)", result);
         destroy(this);
         return NULL;
     }
     this->loop = NULL;
     if (!g_thread_supported())
     {
         g_thread_init(NULL);
     }
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create_with_prio((callback_job_cb_t)run, this,
                 NULL, (callback_job_cancel_t)cancel, JOB_PRIO_CRITICAL));
     return &this->public;
 }