strongSwan: kernel_ipsec
kernel_ipsec
kernel
Classes
struct kernel_ipsec_t
Typedefs
typedef struct kernel_ipsec_t kernel_ipsec_t
Functions
bool kernel_ipsec_register (plugin_t *plugin, plugin_feature_t *feature, bool reg, void *data)
Detailed Description
Typedef Documentation
typedef struct kernel_ipsec_t kernel_ipsec_t
Definition at line 27 of file kernel_ipsec.h.
Function Documentation
bool kernel_ipsec_register (plugin_t * plugin, plugin_feature_t * feature, bool reg, void * data)
Helper function to (un-)register IPsec kernel interfaces from plugin features.
This function is a plugin_feature_callback_t and can be used with the PLUGIN_CALLBACK macro to register an IPsec kernel interface constructor.
Parameters
plugin plugin registering the kernel interface
feature associated plugin feature
reg TRUE to register, FALSE to unregister
data data passed to callback, an kernel_ipsec_constructor_t
See header
Definition at line 23 of file kernel_ipsec.c.
References kernel_interface_t::add_ipsec_interface, hydra, hydra_t::kernel_interface, and kernel_interface_t::remove_ipsec_interface.
Referenced by main(), METHOD(), and test_runner_init().
 {
     if (reg)
     {
         return hydra->kernel_interface->add_ipsec_interface(
                                             hydra->kernel_interface,
                                             (kernel_ipsec_constructor_t)data);
     }
     else
     {
         return hydra->kernel_interface->remove_ipsec_interface(
                                             hydra->kernel_interface,
                                             (kernel_ipsec_constructor_t)data);
     }
 }