strongSwan: atomics
atomics
utils
Typedefs
typedef u_int refcount_t
Functions
refcount_t ref_get (refcount_t *ref)
bool ref_put (refcount_t *ref)
refcount_t ref_cur (refcount_t *ref)
bool cas_bool (bool *ptr, bool oldval, bool newval)
bool cas_ptr (void **ptr, void *oldval, void *newval)
void atomics_init ()
void atomics_deinit ()
Detailed Description
Typedef Documentation
typedef u_int refcount_t
Special type to count references
Definition at line 28 of file atomics.h.
Function Documentation
void atomics_deinit ()
Clean up atomics utility functions
See header
Definition at line 106 of file atomics.c.
References spinlock_t::destroy.
Referenced by utils_deinit().
 {
 #if !defined(HAVE_GCC_ATOMIC_OPERATIONS) && !defined(HAVE_GCC_SYNC_OPERATIONS)
     ref_lock->destroy(ref_lock);
     cas_lock->destroy(cas_lock);
 #endif
 }
void atomics_init ()
Initialize atomics utility functions
Referenced by utils_init().
bool cas_bool (bool * ptr, bool oldval, bool newval)
Atomically replace value of ptr with newval if it currently equals oldval.
Parameters
ptr pointer to variable
oldval old value of the variable
newval new value set if possible
Returns
TRUE if value equaled oldval and newval was written
bool cas_ptr (void ** ptr, void * oldval, void * newval)
Atomically replace value of ptr with newval if it currently equals oldval.
Parameters
ptr pointer to variable
oldval old value of the variable
newval new value set if possible
Returns
TRUE if value equaled oldval and newval was written
Referenced by METHOD().
refcount_t ref_cur (refcount_t * ref)
Get the current value of the reference counter.
Parameters
ref pointer to ref counter
Returns
current value of ref
Current refcount
Definition at line 58 of file atomics.c.
References spinlock_t::lock, and spinlock_t::unlock.
Referenced by METHOD().
 {
     refcount_t current;
     ref_lock->lock(ref_lock);
     current = *ref;
     ref_lock->unlock(ref_lock);
     return current;
 }
refcount_t ref_get (refcount_t * ref)
Get a new reference.
Increments the reference counter atomically.
Parameters
ref pointer to ref counter
Returns
new value of ref
Increase refcount
Definition at line 31 of file atomics.c.
References spinlock_t::lock, and spinlock_t::unlock.
Referenced by CALLBACK(), child_sa_create(), concurrency(), get_route(), ike_sa_create(), ipsec_sa_create(), libcharon_init(), libhydra_init(), libimcv_init(), library_init(), libtnccs_init(), manage_route(), METHOD(), netlink_msg_loss(), put_half_open(), rwlock_run(), section_dictionary_create(), semaphore_cancel_run(), START_TEST(), wait_for_listener(), and watch().
 {
     refcount_t current;
     ref_lock->lock(ref_lock);
     current = ++(*ref);
     ref_lock->unlock(ref_lock);
     return current;
 }
bool ref_put (refcount_t * ref)
Put back a unused reference.
Decrements the reference counter atomically and says if more references available.
Parameters
ref pointer to ref counter
Returns
TRUE if no more references counted
Decrease refcount
Definition at line 45 of file atomics.c.
References spinlock_t::lock, and spinlock_t::unlock.
Referenced by concurrency(), destroy_service(), detach_exit_run(), detach_run(), finalize_transaction(), ipsec_sa_destroy(), libcharon_deinit(), libhydra_deinit(), libimcv_deinit(), library_deinit(), libtnccs_deinit(), METHOD(), query_destroy(), remove_half_open(), and rwlock_run().
 {
     bool more_refs;
     ref_lock->lock(ref_lock);
     more_refs = --(*ref) > 0;
     ref_lock->unlock(ref_lock);
     return !more_refs;
 }