strongSwan: eap_manager.c File Reference
eap_manager.c File Reference
#include "eap_manager.h"
#include <collections/linked_list.h>
#include <threading/rwlock.h>
Classes
struct eap_entry_t
struct private_eap_manager_t
Typedefs
typedef struct
private_eap_manager_t private_eap_manager_t
typedef struct eap_entry_t eap_entry_t
Functions
METHOD (eap_manager_t, add_method, void, private_eap_manager_t *this, eap_type_t type, u_int32_t vendor, eap_role_t role, eap_constructor_t constructor)
METHOD (eap_manager_t, remove_method, void, private_eap_manager_t *this, eap_constructor_t constructor)
static bool filter_methods (uintptr_t role, eap_entry_t **entry, eap_type_t *type, void *in, u_int32_t *vendor)
METHOD (eap_manager_t, create_enumerator, enumerator_t *, private_eap_manager_t *this, eap_role_t role)
METHOD (eap_manager_t, create_instance, eap_method_t *, private_eap_manager_t *this, eap_type_t type, u_int32_t vendor, eap_role_t role, identification_t *server, identification_t *peer)
METHOD (eap_manager_t, destroy, void, private_eap_manager_t *this)
eap_manager_t * eap_manager_create ()
Typedef Documentation
typedef struct eap_entry_t eap_entry_t
Definition at line 23 of file eap_manager.c.
typedef struct private_eap_manager_t private_eap_manager_t
Definition at line 22 of file eap_manager.c.
Function Documentation
static bool filter_methods (uintptr_t role, eap_entry_t ** entry, eap_type_t * type, void * in, u_int32_t * vendor) static
filter the registered methods
Definition at line 111 of file eap_manager.c.
References EAP_EXPANDED, EAP_EXPERIMENTAL, FALSE, and TRUE.
Referenced by METHOD().
 {
     if ((*entry)->role != (eap_role_t)role)
     {
         return FALSE;
     }
     if ((*entry)->vendor == 0 &&
        ((*entry)->type < 4 || (*entry)->type == EAP_EXPANDED ||
         (*entry)->type > EAP_EXPERIMENTAL))
     {   /* filter invalid types */
         return FALSE;
     }
     if (type)
     {
         *type = (*entry)->type;
     }
     if (vendor)
     {
         *vendor = (*entry)->vendor;
     }
     return TRUE;
 }
METHOD (eap_manager_t , add_method , void , private_eap_manager_t * this, eap_type_t type, u_int32_t vendor, eap_role_t role, eap_constructor_t constructor)
Definition at line 72 of file eap_manager.c.
References eap_entry_t::constructor, lock, malloc_thing, eap_entry_t::role, eap_entry_t::type, type, spinlock_t::unlock, and eap_entry_t::vendor.
 {
     eap_entry_t *entry = malloc_thing(eap_entry_t);
     entry->type = type;
     entry->vendor = vendor;
     entry->role = role;
     entry->constructor = constructor;
     this->lock->write_lock(this->lock);
     this->methods->insert_last(this->methods, entry);
     this->lock->unlock(this->lock);
 }
METHOD (eap_manager_t , remove_method , void , private_eap_manager_t * this, eap_constructor_t constructor)
Definition at line 88 of file eap_manager.c.
References eap_entry_t::constructor, enumerator_t::destroy, enumerator_t::enumerate, free(), lock, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     eap_entry_t *entry;
     this->lock->write_lock(this->lock);
     enumerator = this->methods->create_enumerator(this->methods);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (constructor == entry->constructor)
         {
             this->methods->remove_at(this->methods, enumerator);
             free(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (eap_manager_t , create_enumerator , enumerator_t * , private_eap_manager_t * this, eap_role_t role)
Definition at line 135 of file eap_manager.c.
References enumerator_create_cleaner(), enumerator_create_filter(), filter_methods(), lock, and spinlock_t::unlock.
 {
     this->lock->read_lock(this->lock);
     return enumerator_create_cleaner(
                 enumerator_create_filter(
                     this->methods->create_enumerator(this->methods),
                     (void*)filter_methods, (void*)(uintptr_t)role, NULL),
                 (void*)this->lock->unlock, this->lock);
 }
METHOD (eap_manager_t , create_instance , eap_method_t * , private_eap_manager_t * this, eap_type_t type, u_int32_t vendor, eap_role_t role, identification_t * server, identification_t * peer)
Definition at line 146 of file eap_manager.c.
References eap_entry_t::constructor, enumerator_t::destroy, enumerator_t::enumerate, lock, eap_entry_t::role, eap_entry_t::type, spinlock_t::unlock, and eap_entry_t::vendor.
 {
     enumerator_t *enumerator;
     eap_entry_t *entry;
     eap_method_t *method = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->methods->create_enumerator(this->methods);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (type == entry->type && vendor == entry->vendor &&
             role == entry->role)
         {
             method = entry->constructor(server, peer);
             if (method)
             {
                 break;
             }
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return method;
 }
METHOD (eap_manager_t , destroy , void , private_eap_manager_t * this)
Definition at line 173 of file eap_manager.c.
References spinlock_t::destroy, free(), and lock.
 {
     this->methods->destroy_function(this->methods, free);
     this->lock->destroy(this->lock);
     free(this);
 }