strongSwan: pb_error_msg
pb_error_msg
tnccs_20
Classes
struct pb_error_msg_t
Typedefs
typedef enum pb_tnc_error_code_t pb_tnc_error_code_t
typedef struct pb_error_msg_t pb_error_msg_t
Enumerations
enum pb_tnc_error_code_t {
PB_ERROR_UNEXPECTED_BATCH_TYPE = 0, PB_ERROR_INVALID_PARAMETER = 1, PB_ERROR_LOCAL_ERROR = 2, PB_ERROR_UNSUPPORTED_MANDATORY_MSG = 3,
PB_ERROR_VERSION_NOT_SUPPORTED = 4
}
Functions
pb_tnc_msg_t * pb_error_msg_create (bool fatal, u_int32_t vendor_id, pb_tnc_error_code_t error_code)
pb_tnc_msg_t * pb_error_msg_create_with_offset (bool fatal, u_int32_t vendor_id, pb_tnc_error_code_t error_code, u_int32_t error_offset)
pb_tnc_msg_t * pb_error_msg_create_from_data (chunk_t data)
Variables
enum_name_t * pb_tnc_error_code_names
Detailed Description
Typedef Documentation
typedef struct pb_error_msg_t pb_error_msg_t
Definition at line 25 of file pb_error_msg.h.
typedef enum pb_tnc_error_code_t pb_tnc_error_code_t
Definition at line 24 of file pb_error_msg.h.
Enumeration Type Documentation
enum pb_tnc_error_code_t
PB-TNC Error Codes as defined in section 4.9.1 of RFC 5793
Enumerator
PB_ERROR_UNEXPECTED_BATCH_TYPE
PB_ERROR_INVALID_PARAMETER
PB_ERROR_LOCAL_ERROR
PB_ERROR_UNSUPPORTED_MANDATORY_MSG
PB_ERROR_VERSION_NOT_SUPPORTED
Definition at line 32 of file pb_error_msg.h.
{
     PB_ERROR_UNEXPECTED_BATCH_TYPE =        0,
     PB_ERROR_INVALID_PARAMETER =            1,
     PB_ERROR_LOCAL_ERROR =                  2,
     PB_ERROR_UNSUPPORTED_MANDATORY_MSG =    3,
     PB_ERROR_VERSION_NOT_SUPPORTED =        4
 };
Function Documentation
pb_tnc_msg_t* pb_error_msg_create (bool fatal, u_int32_t vendor_id, pb_tnc_error_code_t error_code)
Create a PB-Error message from parameters
Parameters
fatal fatal flag
vendor_id Error Code Vendor ID
error_code Error Code
See header
Definition at line 252 of file pb_error_msg.c.
References error_code, INIT, PB_MSG_ERROR, and PEN_IETF.
Referenced by METHOD().
 {
     private_pb_error_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_fatal_flag = _get_fatal_flag,
             .get_vendor_id = _get_vendor_id,
             .get_error_code = _get_error_code,
             .get_offset = _get_offset,
             .get_bad_version = _get_bad_version,
             .set_bad_version = _set_bad_version,
         },
         .type = { PEN_IETF, PB_MSG_ERROR },
         .ref = 1,
         .fatal = fatal,
         .vendor_id = vendor_id,
         .error_code = error_code,
     );
     return &this->public.pb_interface;
 }
pb_tnc_msg_t* pb_error_msg_create_from_data (chunk_t data)
Create an unprocessed PB-Error message from raw data
Parameters
data PB-Error message data
See header
Definition at line 324 of file pb_error_msg.c.
References chunk_clone, INIT, PB_MSG_ERROR, and PEN_IETF.
Referenced by pb_tnc_msg_create_from_data().
 {
     private_pb_error_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_fatal_flag = _get_fatal_flag,
             .get_vendor_id = _get_vendor_id,
             .get_error_code = _get_error_code,
             .get_offset = _get_offset,
             .get_bad_version = _get_bad_version,
             .set_bad_version = _set_bad_version,
         },
         .type = { PEN_IETF, PB_MSG_ERROR },
         .ref = 1,
         .encoding = chunk_clone(data),
     );
     return &this->public.pb_interface;
 }
pb_tnc_msg_t* pb_error_msg_create_with_offset (bool fatal, u_int32_t vendor_id, pb_tnc_error_code_t error_code, u_int32_t error_offset)
Create a PB-Error message from parameters with offset field
Parameters
fatal fatal flag
vendor_id Error Code Vendor ID
error_code Error Code
error_offset Error Offset
See header
Definition at line 287 of file pb_error_msg.c.
References error_code, INIT, PB_MSG_ERROR, and PEN_IETF.
Referenced by METHOD(), and process_tnc_msg().
 {
     private_pb_error_msg_t *this;
     INIT(this,
         .public = {
             .pb_interface = {
                 .get_type = _get_type,
                 .get_encoding = _get_encoding,
                 .build = _build,
                 .process = _process,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_fatal_flag = _get_fatal_flag,
             .get_vendor_id = _get_vendor_id,
             .get_error_code = _get_error_code,
             .get_offset = _get_offset,
             .get_bad_version = _get_bad_version,
             .set_bad_version = _set_bad_version,
         },
         .type = { PEN_IETF, PB_MSG_ERROR },
         .ref = 1,
         .fatal = fatal,
         .vendor_id = vendor_id,
         .error_code = error_code,
         .error_offset = error_offset,
     );
     return &this->public.pb_interface;
 }
Variable Documentation
enum_name_t* pb_tnc_error_code_names
enum name for pb_tnc_error_code_t.
Referenced by tnccs_20_handle_ietf_error_msg().