strongSwan: callback_job
callback_job
jobs
Classes
struct callback_job_t
Typedefs
typedef struct callback_job_t callback_job_t
typedef job_requeue_t(* callback_job_cb_t)(void *data)
typedef void(* callback_job_cleanup_t)(void *data)
typedef bool(* callback_job_cancel_t)(void *data)
Functions
callback_job_t * callback_job_create (callback_job_cb_t cb, void *data, callback_job_cleanup_t cleanup, callback_job_cancel_t cancel)
callback_job_t * callback_job_create_with_prio (callback_job_cb_t cb, void *data, callback_job_cleanup_t cleanup, callback_job_cancel_t cancel, job_priority_t prio)
Detailed Description
Typedef Documentation
typedef bool(* callback_job_cancel_t)(void *data)
Cancellation function to use for the callback job.
Optional function to be called when a job has to be canceled.
See job_t.cancel() for details on the return value.
Parameters
data param supplied to job
Returns
TRUE if canceled, FALSE to explicitly cancel the thread
Definition at line 63 of file callback_job.h.
typedef job_requeue_t(* callback_job_cb_t)(void *data)
The callback function to use for the callback job.
This is the function to use as callback for a callback job. It receives a parameter supplied to the callback jobs constructor.
Parameters
data param supplied to job
Returns
requeing policy how to requeue the job
Definition at line 40 of file callback_job.h.
typedef void(* callback_job_cleanup_t)(void *data)
Cleanup function to use for data cleanup.
The callback has an optional user argument which receives data. However, this data may be cleaned up if it is allocated. This is the function to supply to the constructor.
Parameters
data param supplied to job
Definition at line 51 of file callback_job.h.
typedef struct callback_job_t callback_job_t
Definition at line 26 of file callback_job.h.
Function Documentation
callback_job_t* callback_job_create (callback_job_cb_t cb, void * data, callback_job_cleanup_t cleanup, callback_job_cancel_t cancel)
Creates a callback job.
The cleanup function is called when the job gets destroyed to destroy the associated data.
The cancel function is optional and should only be provided if the callback function calls potentially blocking functions and/or always returns JOB_REQUEUE_DIRECT.
Parameters
cb callback to call from the processor
data user data to supply to callback
cleanup destructor for data on destruction, or NULL
cancel function to cancel the job, or NULL
Returns
callback_job_t object
Definition at line 127 of file callback_job.c.
References callback_job_create_with_prio(), and JOB_PRIO_MEDIUM.
Referenced by add_exclude(), CALLBACK(), check_systime(), disconnect(), dispatch(), finish_checks(), fire_roam_event(), ipsec_event_relay_create(), ipsec_processor_create(), kernel_libipsec_router_create(), load_action(), METHOD(), plugin_cb(), queue_messsage(), queue_retransmission(), queue_route_reinstall(), schedule_autoinit(), schedule_checks(), schedule_expiration(), schedule_expire(), start_echo_server(), and update_checklist_state().
 {
     return callback_job_create_with_prio(cb, data, cleanup, cancel,
                                          JOB_PRIO_MEDIUM);
 }
callback_job_t* callback_job_create_with_prio (callback_job_cb_t cb, void * data, callback_job_cleanup_t cleanup, callback_job_cancel_t cancel, job_priority_t prio)
Creates a callback job, with priority.
Same as callback_job_create(), but with different priorities than default.
Parameters
cb callback to call from the processor
data user data to supply to callback
cleanup destructor for data on destruction, or NULL
cancel function to cancel the job, or NULL
prio job priority
Returns
callback_job_t object
Definition at line 95 of file callback_job.c.
References cancel(), cb(), cleanup, data, and INIT.
Referenced by blink_activity(), callback_job_create(), check_cron(), cmd_connection_create(), eap_radius_handle_timeout(), ha_cache_create(), ha_ctl_create(), ha_dispatcher_create(), keychain_creds_create(), maemo_service_create(), METHOD(), nm_backend_init(), notify(), pkcs11_manager_create(), receiver_create(), register_load_tester(), schedule_interim(), scheduler_create(), sender_create(), smp_plugin_create(), start_autobalance(), start_heartbeat(), start_watchdog(), uci_control_create(), and watch().
 {
     private_callback_job_t *this;
     INIT(this,
         .public = {
             .job = {
                 .execute = _execute,
                 .get_priority = _get_priority,
                 .destroy = _destroy,
             },
         },
         .callback = cb,
         .data = data,
         .cleanup = cleanup,
         .cancel = cancel,
         .prio = prio,
     );
     if (cancel)
     {
         this->public.job.cancel = _cancel;
     }
     return &this->public;
 }