strongSwan: vici_socket.c File Reference
vici_socket.c File Reference
#include "vici_socket.h"
#include <threading/mutex.h>
#include <threading/condvar.h>
#include <threading/thread.h>
#include <collections/array.h>
#include <collections/linked_list.h>
#include <processing/jobs/callback_job.h>
#include <errno.h>
#include <string.h>
Classes
struct private_vici_socket_t
struct entry_selector_t
struct msg_buf_t
struct entry_t
Typedefs
typedef struct
private_vici_socket_t private_vici_socket_t
Functions
CALLBACK (destroy_entry, void, entry_t *entry)
static entry_t * find_entry (private_vici_socket_t *this, stream_t *stream, u_int id, bool reader, bool writer)
static entry_t * remove_entry (private_vici_socket_t *this, u_int id)
static void put_entry (private_vici_socket_t *this, entry_t *entry, bool reader, bool writer)
CALLBACK (disconnect_async, job_requeue_t, entry_selector_t *sel)
static void disconnect (private_vici_socket_t *this, u_int id)
static bool do_write (private_vici_socket_t *this, entry_t *entry, stream_t *stream, char *errmsg, size_t errlen)
CALLBACK (on_write, bool, private_vici_socket_t *this, stream_t *stream)
static bool do_read (private_vici_socket_t *this, entry_t *entry, stream_t *stream, char *errmsg, size_t errlen)
CALLBACK (process_queue, job_requeue_t, entry_selector_t *sel)
CALLBACK (on_read, bool, private_vici_socket_t *this, stream_t *stream)
CALLBACK (on_accept, bool, private_vici_socket_t *this, stream_t *stream)
CALLBACK (enable_writer, job_requeue_t, entry_selector_t *sel)
METHOD (vici_socket_t, send_, void, private_vici_socket_t *this, u_int id, chunk_t msg)
METHOD (vici_socket_t, destroy, void, private_vici_socket_t *this)
vici_socket_t * vici_socket_create (char *uri, vici_inbound_cb_t inbound, vici_connect_cb_t connect, vici_disconnect_cb_t disconnect, void *user)
Typedef Documentation
typedef struct private_vici_socket_t private_vici_socket_t
Definition at line 28 of file vici_socket.c.
Function Documentation
CALLBACK (destroy_entry , void , entry_t * entry)
Destroy an connection entry
Definition at line 136 of file vici_socket.c.
References array_destroy(), array_remove(), ARRAY_TAIL, msg_buf_t::buf, chunk_clear(), entry_t::cond, condvar_t::destroy, stream_t::destroy, free(), entry_t::id, entry_t::in, out, entry_t::out, entry_t::queue, entry_t::stream, and entry_t::this.
 {
     msg_buf_t *out;
     chunk_t chunk;
     entry->stream->destroy(entry->stream);
     entry->this->disconnect(entry->this->user, entry->id);
     entry->cond->destroy(entry->cond);
     while (array_remove(entry->out, ARRAY_TAIL, &out))
     {
         chunk_clear(&out->buf);
         free(out);
     }
     array_destroy(entry->out);
     while (array_remove(entry->queue, ARRAY_TAIL, &chunk))
     {
         chunk_clear(&chunk);
     }
     array_destroy(entry->queue);
     chunk_clear(&entry->in.buf);
     free(entry);
 }
CALLBACK (disconnect_async , job_requeue_t , entry_selector_t * sel)
Asynchronous callback to disconnect client
Definition at line 280 of file vici_socket.c.
References destroy_entry(), entry_selector_t::id, JOB_REQUEUE_NONE, remove_entry(), and entry_selector_t::this.
 {
     entry_t *entry;
     entry = remove_entry(sel->this, sel->id);
     if (entry)
     {
         destroy_entry(entry);
     }
     return JOB_REQUEUE_NONE;
 }
CALLBACK (on_write , bool , private_vici_socket_t * this, stream_t * stream)
Send pending messages
Definition at line 376 of file vici_socket.c.
References array_count(), DBG1, DBG_CFG, disconnect(), entry_t::disconnecting, do_write(), FALSE, find_entry(), entry_t::id, entry_t::out, put_entry(), entry_t::this, and TRUE.
 {
     char errmsg[256] = "";
     entry_t *entry;
     bool ret = FALSE;
     entry = find_entry(this, stream, 0, FALSE, TRUE);
     if (entry)
     {
         ret = do_write(this, entry, stream, errmsg, sizeof(errmsg));
         if (ret)
         {
             /* unregister if we have no more messages to send */
             ret = array_count(entry->out) != 0;
         }
         else
         {
             entry->disconnecting = TRUE;
             disconnect(entry->this, entry->id);
         }
         put_entry(this, entry, FALSE, TRUE);
         if (!ret && errmsg[0])
         {
             DBG1(DBG_CFG, errmsg);
         }
     }
     return ret;
 }
CALLBACK (process_queue , job_requeue_t , entry_selector_t * sel)
Callback processing incoming requestes in strict order
Definition at line 479 of file vici_socket.c.
References ARRAY_HEAD, array_remove(), FALSE, find_entry(), found, free(), entry_t::has_processor, id, entry_selector_t::id, entry_t::id, private_vici_socket_t::inbound, JOB_REQUEUE_NONE, chunk_t::ptr, put_entry(), entry_t::queue, entry_selector_t::this, thread_cleanup_pop(), thread_cleanup_push(), TRUE, and private_vici_socket_t::user.
 {
     entry_t *entry;
     chunk_t chunk;
     bool found;
     u_int id;
     while (TRUE)
     {
         entry = find_entry(sel->this, NULL, sel->id, TRUE, FALSE);
         if (!entry)
         {
             break;
         }
         found = array_remove(entry->queue, ARRAY_HEAD, &chunk);
         if (!found)
         {
             entry->has_processor = FALSE;
         }
         id = entry->id;
         put_entry(sel->this, entry, TRUE, FALSE);
         if (!found)
         {
             break;
         }
         thread_cleanup_push(free, chunk.ptr);
         sel->this->inbound(sel->this->user, id, chunk);
         thread_cleanup_pop(TRUE);
     }
     return JOB_REQUEUE_NONE;
 }
CALLBACK (on_read , bool , private_vici_socket_t * this, stream_t * stream)
Process incoming messages
Definition at line 517 of file vici_socket.c.
References array_insert(), ARRAY_TAIL, msg_buf_t::buf, callback_job_create(), chunk_empty, DBG1, DBG_CFG, disconnect(), entry_t::disconnecting, do_read(), msg_buf_t::done, FALSE, find_entry(), free(), entry_t::has_processor, msg_buf_t::hdr, msg_buf_t::hdrlen, entry_t::id, entry_t::in, INIT, chunk_t::len, lib, library_t::processor, put_entry(), entry_t::queue, processor_t::queue_job, and TRUE.
 {
     char errmsg[256] = "";
     entry_selector_t *sel;
     entry_t *entry;
     bool ret = FALSE;
     entry = find_entry(this, stream, 0, TRUE, FALSE);
     if (entry)
     {
         ret = do_read(this, entry, stream, errmsg, sizeof(errmsg));
         if (!ret)
         {
             entry->disconnecting = TRUE;
             disconnect(this, entry->id);
         }
         else if (entry->in.hdrlen == sizeof(entry->in.hdr) &&
                  entry->in.buf.len == entry->in.done)
         {
             array_insert(entry->queue, ARRAY_TAIL, &entry->in.buf);
             entry->in.buf = chunk_empty;
             entry->in.hdrlen = entry->in.done = 0;
             if (!entry->has_processor)
             {
                 INIT(sel,
                     .this = this,
                     .id = entry->id,
                 );
                 lib->processor->queue_job(lib->processor,
                             (job_t*)callback_job_create(process_queue,
                                                         sel, free, NULL));
                 entry->has_processor = TRUE;
             }
         }
         put_entry(this, entry, TRUE, FALSE);
         if (!ret && errmsg[0])
         {
             DBG1(DBG_CFG, errmsg);
         }
     }
     return ret;
 }
CALLBACK (on_accept , bool , private_vici_socket_t * this, stream_t * stream)
Process connection request
Definition at line 567 of file vici_socket.c.
References array_create(), condvar_create(), CONDVAR_TYPE_DEFAULT, connect, FALSE, id, INIT, mutex_t::lock, mutex, stream_t::on_read, on_read(), out, put_entry(), queue(), ref_get(), TRUE, and mutex_t::unlock.
 {
     entry_t *entry;
     u_int id;
     id = ref_get(&this->nextid);
     INIT(entry,
         .this = this,
         .stream = stream,
         .id = id,
         .out = array_create(0, 0),
         .queue = array_create(sizeof(chunk_t), 0),
         .cond = condvar_create(CONDVAR_TYPE_DEFAULT),
         .readers = 1,
     );
     this->mutex->lock(this->mutex);
     this->connections->insert_last(this->connections, entry);
     this->mutex->unlock(this->mutex);
     stream->on_read(stream, on_read, this);
     put_entry(this, entry, TRUE, FALSE);
     this->connect(this->user, id);
     return TRUE;
 }
CALLBACK (enable_writer , job_requeue_t , entry_selector_t * sel)
Async callback to enable writer
Definition at line 601 of file vici_socket.c.
References FALSE, find_entry(), entry_selector_t::id, JOB_REQUEUE_NONE, on_write(), stream_t::on_write, put_entry(), entry_t::stream, entry_selector_t::this, and TRUE.
 {
     entry_t *entry;
     entry = find_entry(sel->this, NULL, sel->id, FALSE, TRUE);
     if (entry)
     {
         entry->stream->on_write(entry->stream, on_write, sel->this);
         put_entry(sel->this, entry, FALSE, TRUE);
     }
     return JOB_REQUEUE_NONE;
 }
static void disconnect (private_vici_socket_t * this, u_int id) static
Disconnect a connected client
Definition at line 296 of file vici_socket.c.
References callback_job_create(), disconnect_async(), free(), INIT, lib, library_t::processor, and processor_t::queue_job.
Referenced by CALLBACK(), and vici_socket_create().
 {
     entry_selector_t *sel;
     INIT(sel,
         .this = this,
         .id = id,
     );
     lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create(disconnect_async, sel, free, NULL));
 }
static bool do_read (private_vici_socket_t * this, entry_t * entry, stream_t * stream, char * errmsg, size_t errlen) static
Read in available header with data, non-blocking cumulating to buffer
Definition at line 411 of file vici_socket.c.
References msg_buf_t::buf, chunk_alloc, msg_buf_t::done, EWOULDBLOCK, FALSE, msg_buf_t::hdr, msg_buf_t::hdrlen, entry_t::in, chunk_t::len, len, msglen, chunk_t::ptr, stream_t::read, snprintf, strerror, TRUE, untoh32(), and VICI_MESSAGE_SIZE_MAX.
Referenced by CALLBACK().
 {
     u_int32_t msglen;
     ssize_t len;
     /* assemble the length header first */
     while (entry->in.hdrlen < sizeof(entry->in.hdr))
     {
         len = stream->read(stream, entry->in.hdr + entry->in.hdrlen,
                            sizeof(entry->in.hdr) - entry->in.hdrlen, FALSE);
         if (len == 0)
         {
             return FALSE;
         }
         if (len < 0)
         {
             if (errno == EWOULDBLOCK)
             {
                 return TRUE;
             }
             snprintf(errmsg, errlen, "vici header read error: %s",
                      strerror(errno));
             return FALSE;
         }
         entry->in.hdrlen += len;
         if (entry->in.hdrlen == sizeof(entry->in.hdr))
         {
             msglen = untoh32(entry->in.hdr);
             if (msglen > VICI_MESSAGE_SIZE_MAX)
             {
                 snprintf(errmsg, errlen, "vici message length %u exceeds %u "
                          "bytes limit, ignored", msglen, VICI_MESSAGE_SIZE_MAX);
                 return FALSE;
             }
             /* header complete, continue with data */
             entry->in.buf = chunk_alloc(msglen);
         }
     }
     /* assemble buffer */
     while (entry->in.buf.len > entry->in.done)
     {
         len = stream->read(stream, entry->in.buf.ptr + entry->in.done,
                            entry->in.buf.len - entry->in.done, FALSE);
         if (len == 0)
         {
             snprintf(errmsg, errlen, "premature vici disconnect");
             return FALSE;
         }
         if (len < 0)
         {
             if (errno == EWOULDBLOCK)
             {
                 return TRUE;
             }
             snprintf(errmsg, errlen, "vici read error: %s", strerror(errno));
             return FALSE;
         }
         entry->in.done += len;
     }
     return TRUE;
 }
static bool do_write (private_vici_socket_t * this, entry_t * entry, stream_t * stream, char * errmsg, size_t errlen) static
Write queued output data
Definition at line 312 of file vici_socket.c.
References array_get(), ARRAY_HEAD, array_remove(), msg_buf_t::buf, chunk_clear(), msg_buf_t::done, EWOULDBLOCK, FALSE, free(), msg_buf_t::hdr, msg_buf_t::hdrlen, chunk_t::len, len, out, entry_t::out, chunk_t::ptr, snprintf, strerror, TRUE, and stream_t::write.
Referenced by CALLBACK().
 {
     msg_buf_t *out;
     ssize_t len;
     while (array_get(entry->out, ARRAY_HEAD, &out))
     {
         /* write header */
         while (out->hdrlen < sizeof(out->hdr))
         {
             len = stream->write(stream, out->hdr + out->hdrlen,
                                 sizeof(out->hdr) - out->hdrlen, FALSE);
             if (len == 0)
             {
                 return FALSE;
             }
             if (len < 0)
             {
                 if (errno == EWOULDBLOCK)
                 {
                     return TRUE;
                 }
                 snprintf(errmsg, errlen, "vici header write error: %s",
                          strerror(errno));
                 return FALSE;
             }
             out->hdrlen += len;
         }
         /* write buffer buffer */
         while (out->buf.len > out->done)
         {
             len = stream->write(stream, out->buf.ptr + out->done,
                                 out->buf.len - out->done, FALSE);
             if (len == 0)
             {
                 snprintf(errmsg, errlen, "premature vici disconnect");
                 return FALSE;
             }
             if (len < 0)
             {
                 if (errno == EWOULDBLOCK)
                 {
                     return TRUE;
                 }
                 snprintf(errmsg, errlen, "vici write error: %s", strerror(errno));
                 return FALSE;
             }
             out->done += len;
         }
         if (array_remove(entry->out, ARRAY_HEAD, &out))
         {
             chunk_clear(&out->buf);
             free(out);
         }
     }
     return TRUE;
 }
static entry_t* find_entry (private_vici_socket_t * this, stream_t * stream, u_int id, bool reader, bool writer) static
Find entry by stream (if given) or id, claim use
Definition at line 164 of file vici_socket.c.
References entry_t::cond, enumerator_t::destroy, entry_t::disconnecting, enumerator_t::enumerate, FALSE, found, entry_t::id, mutex_t::lock, mutex, entry_t::readers, entry_t::stream, TRUE, mutex_t::unlock, condvar_t::wait, and entry_t::writers.
Referenced by CALLBACK(), and METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry, *found = NULL;
     bool candidate = TRUE;
     this->mutex->lock(this->mutex);
     while (candidate && !found)
     {
         candidate = FALSE;
         enumerator = this->connections->create_enumerator(this->connections);
         while (enumerator->enumerate(enumerator, &entry))
         {
             if (stream)
             {
                 if (entry->stream != stream)
                 {
                     continue;
                 }
             }
             else
             {
                 if (entry->id != id)
                 {
                     continue;
                 }
             }
             if (entry->disconnecting)
             {
                 continue;
             }
             candidate = TRUE;
             if ((reader && entry->readers) ||
                 (writer && entry->writers))
             {
                 entry->cond->wait(entry->cond, this->mutex);
                 break;
             }
             if (reader)
             {
                 entry->readers++;
             }
             if (writer)
             {
                 entry->writers++;
             }
             found = entry;
             break;
         }
         enumerator->destroy(enumerator);
     }
     this->mutex->unlock(this->mutex);
     return found;
 }
METHOD (vici_socket_t , send_ , void , private_vici_socket_t * this, u_int id, chunk_t msg)
Definition at line 615 of file vici_socket.c.
References array_count(), array_insert(), ARRAY_TAIL, callback_job_create(), chunk_clear(), DBG1, DBG_CFG, FALSE, find_entry(), free(), msg_buf_t::hdr, htoun32(), entry_t::id, INIT, chunk_t::len, lib, out, entry_t::out, library_t::processor, put_entry(), processor_t::queue_job, TRUE, and VICI_MESSAGE_SIZE_MAX.
 {
     if (msg.len <= VICI_MESSAGE_SIZE_MAX)
     {
         entry_selector_t *sel;
         msg_buf_t *out;
         entry_t *entry;
         entry = find_entry(this, NULL, id, FALSE, TRUE);
         if (entry)
         {
             INIT(out,
                 .buf = msg,
             );
             htoun32(out->hdr, msg.len);
             array_insert(entry->out, ARRAY_TAIL, out);
             if (array_count(entry->out) == 1)
             {   /* asynchronously re-enable on_write callback when we get data */
                 INIT(sel,
                     .this = this,
                     .id = entry->id,
                 );
                 lib->processor->queue_job(lib->processor,
                             (job_t*)callback_job_create(enable_writer,
                                                         sel, free, NULL));
             }
             put_entry(this, entry, FALSE, TRUE);
         }
         else
         {
             DBG1(DBG_CFG, "vici connection %u unknown", id);
             chunk_clear(&msg);
         }
     }
     else
     {
         DBG1(DBG_CFG, "vici message size %zu exceeds maximum size of %u, "
              "discarded", msg.len, VICI_MESSAGE_SIZE_MAX);
         chunk_clear(&msg);
     }
 }
METHOD (vici_socket_t , destroy , void , private_vici_socket_t * this)
Definition at line 659 of file vici_socket.c.
References mutex_t::destroy, destroy_entry(), DESTROY_IF, free(), and mutex.
 {
     DESTROY_IF(this->service);
     this->connections->destroy_function(this->connections, destroy_entry);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void put_entry (private_vici_socket_t * this, entry_t * entry, bool reader, bool writer) static
Release a claimed entry
Definition at line 261 of file vici_socket.c.
References entry_t::cond, mutex_t::lock, mutex, entry_t::readers, condvar_t::signal, mutex_t::unlock, and entry_t::writers.
Referenced by CALLBACK(), and METHOD().
 {
     this->mutex->lock(this->mutex);
     if (reader)
     {
         entry->readers--;
     }
     if (writer)
     {
         entry->writers--;
     }
     entry->cond->signal(entry->cond);
     this->mutex->unlock(this->mutex);
 }
static entry_t* remove_entry (private_vici_socket_t * this, u_int id) static
Remove entry by id, claim use
Definition at line 225 of file vici_socket.c.
References entry_t::cond, enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, entry_t::id, mutex_t::lock, mutex, entry_t::readers, TRUE, mutex_t::unlock, condvar_t::wait, and entry_t::writers.
Referenced by CALLBACK().
 {
     enumerator_t *enumerator;
     entry_t *entry, *found = NULL;
     bool candidate = TRUE;
     this->mutex->lock(this->mutex);
     while (candidate && !found)
     {
         candidate = FALSE;
         enumerator = this->connections->create_enumerator(this->connections);
         while (enumerator->enumerate(enumerator, &entry))
         {
             if (entry->id == id)
             {
                 candidate = TRUE;
                 if (entry->readers || entry->writers)
                 {
                     entry->cond->wait(entry->cond, this->mutex);
                     break;
                 }
                 this->connections->remove_at(this->connections, enumerator);
                 found = entry;
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     this->mutex->unlock(this->mutex);
     return found;
 }