strongSwan: cert_cache
cert_cache
sets
Classes
struct cert_cache_t
Typedefs
typedef struct cert_cache_t cert_cache_t
Functions
cert_cache_t * cert_cache_create ()
Detailed Description
Typedef Documentation
typedef struct cert_cache_t cert_cache_t
Definition at line 26 of file cert_cache.h.
Function Documentation
cert_cache_t* cert_cache_create ()
Create a cert_cache instance.
Definition at line 376 of file cert_cache.c.
References CACHE_SIZE, INIT, nop(), return_null(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by credential_manager_create().
 {
     private_cert_cache_t *this;
     int i;
     INIT(this,
         .public = {
             .set = {
                 .create_cert_enumerator = _create_enumerator,
                 .create_private_enumerator = (void*)return_null,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = (void*)return_null,
                 .cache_cert = (void*)nop,
             },
             .issued_by = _issued_by,
             .flush = _flush,
             .destroy = _destroy,
         },
     );
     for (i = 0; i < CACHE_SIZE; i++)
     {
         this->relations[i].subject = NULL;
         this->relations[i].issuer = NULL;
         this->relations[i].hits = 0;
         this->relations[i].lock = rwlock_create(RWLOCK_TYPE_DEFAULT);
     }
     return &this->public;
 }