strongSwan: bio_reader.c File Reference
bio_reader.c File Reference
#include "bio_reader.h"
#include <utils/debug.h>
Classes
struct private_bio_reader_t
Typedefs
typedef struct private_bio_reader_t private_bio_reader_t
Functions
METHOD (bio_reader_t, remaining, u_int32_t, private_bio_reader_t *this)
METHOD (bio_reader_t, peek, chunk_t, private_bio_reader_t *this)
static chunk_t chunk_skip_end (chunk_t chunk, size_t bytes, bool from_end)
static u_char * get_ptr_end (private_bio_reader_t *this, u_int32_t len, bool from_end)
static bool read_uint8_internal (private_bio_reader_t *this, u_int8_t *res, bool from_end)
static bool read_uint16_internal (private_bio_reader_t *this, u_int16_t *res, bool from_end)
static bool read_uint24_internal (private_bio_reader_t *this, u_int32_t *res, bool from_end)
static bool read_uint32_internal (private_bio_reader_t *this, u_int32_t *res, bool from_end)
static bool read_uint64_internal (private_bio_reader_t *this, u_int64_t *res, bool from_end)
static bool read_data_internal (private_bio_reader_t *this, u_int32_t len, chunk_t *res, bool from_end)
METHOD (bio_reader_t, read_uint8, bool, private_bio_reader_t *this, u_int8_t *res)
METHOD (bio_reader_t, read_uint16, bool, private_bio_reader_t *this, u_int16_t *res)
METHOD (bio_reader_t, read_uint24, bool, private_bio_reader_t *this, u_int32_t *res)
METHOD (bio_reader_t, read_uint32, bool, private_bio_reader_t *this, u_int32_t *res)
METHOD (bio_reader_t, read_uint64, bool, private_bio_reader_t *this, u_int64_t *res)
METHOD (bio_reader_t, read_data, bool, private_bio_reader_t *this, u_int32_t len, chunk_t *res)
METHOD (bio_reader_t, read_uint8_end, bool, private_bio_reader_t *this, u_int8_t *res)
METHOD (bio_reader_t, read_uint16_end, bool, private_bio_reader_t *this, u_int16_t *res)
METHOD (bio_reader_t, read_uint24_end, bool, private_bio_reader_t *this, u_int32_t *res)
METHOD (bio_reader_t, read_uint32_end, bool, private_bio_reader_t *this, u_int32_t *res)
METHOD (bio_reader_t, read_uint64_end, bool, private_bio_reader_t *this, u_int64_t *res)
METHOD (bio_reader_t, read_data_end, bool, private_bio_reader_t *this, u_int32_t len, chunk_t *res)
METHOD (bio_reader_t, read_data8, bool, private_bio_reader_t *this, chunk_t *res)
METHOD (bio_reader_t, read_data16, bool, private_bio_reader_t *this, chunk_t *res)
METHOD (bio_reader_t, read_data24, bool, private_bio_reader_t *this, chunk_t *res)
METHOD (bio_reader_t, read_data32, bool, private_bio_reader_t *this, chunk_t *res)
METHOD (bio_reader_t, destroy, void, private_bio_reader_t *this)
bio_reader_t * bio_reader_create (chunk_t data)
bio_reader_t * bio_reader_create_own (chunk_t data)
Typedef Documentation
typedef struct private_bio_reader_t private_bio_reader_t
Definition at line 23 of file bio_reader.c.
Function Documentation
static chunk_t chunk_skip_end (chunk_t chunk, size_t bytes, bool from_end) inline static
A version of chunk_skip() that supports skipping from the end (i.e. simply reducing the size)
Definition at line 62 of file bio_reader.c.
References bytes, chunk_empty, chunk_t::len, and chunk_t::ptr.
Referenced by read_data_internal(), read_uint16_internal(), read_uint24_internal(), read_uint32_internal(), read_uint64_internal(), and read_uint8_internal().
 {
     if (chunk.len > bytes)
     {
         if (!from_end)
         {
             chunk.ptr += bytes;
         }
         chunk.len -= bytes;
         return chunk;
     }
     return chunk_empty;
 }
static u_char* get_ptr_end (private_bio_reader_t * this, u_int32_t len, bool from_end) inline static
Returns a pointer to the data to read, optionally from the end
Definition at line 79 of file bio_reader.c.
References len.
Referenced by read_data_internal(), read_uint16_internal(), read_uint24_internal(), read_uint32_internal(), read_uint64_internal(), and read_uint8_internal().
 {
     return from_end ? this->buf.ptr + (this->buf.len - len) : this->buf.ptr;
 }
METHOD (bio_reader_t , remaining , u_int32_t , private_bio_reader_t * this)
Definition at line 46 of file bio_reader.c.
 {
     return this->buf.len;
 }
METHOD (bio_reader_t , peek , chunk_t , private_bio_reader_t * this)
Definition at line 52 of file bio_reader.c.
 {
     return this->buf;
 }
METHOD (bio_reader_t , read_uint8 , bool , private_bio_reader_t * this, u_int8_t * res)
Definition at line 187 of file bio_reader.c.
References FALSE, and read_uint8_internal().
 {
     return read_uint8_internal(this, res, FALSE);
 }
METHOD (bio_reader_t , read_uint16 , bool , private_bio_reader_t * this, u_int16_t * res)
Definition at line 193 of file bio_reader.c.
References FALSE, and read_uint16_internal().
 {
     return read_uint16_internal(this, res, FALSE);
 }
METHOD (bio_reader_t , read_uint24 , bool , private_bio_reader_t * this, u_int32_t * res)
Definition at line 199 of file bio_reader.c.
References FALSE, and read_uint24_internal().
 {
     return read_uint24_internal(this, res, FALSE);
 }
METHOD (bio_reader_t , read_uint32 , bool , private_bio_reader_t * this, u_int32_t * res)
Definition at line 205 of file bio_reader.c.
References FALSE, and read_uint32_internal().
 {
     return read_uint32_internal(this, res, FALSE);
 }
METHOD (bio_reader_t , read_uint64 , bool , private_bio_reader_t * this, u_int64_t * res)
Definition at line 211 of file bio_reader.c.
References FALSE, and read_uint64_internal().
 {
     return read_uint64_internal(this, res, FALSE);
 }
METHOD (bio_reader_t , read_data , bool , private_bio_reader_t * this, u_int32_t len, chunk_t * res)
Definition at line 217 of file bio_reader.c.
References FALSE, and read_data_internal().
 {
     return read_data_internal(this, len, res, FALSE);
 }
METHOD (bio_reader_t , read_uint8_end , bool , private_bio_reader_t * this, u_int8_t * res)
Definition at line 223 of file bio_reader.c.
References read_uint8_internal(), and TRUE.
 {
     return read_uint8_internal(this, res, TRUE);
 }
METHOD (bio_reader_t , read_uint16_end , bool , private_bio_reader_t * this, u_int16_t * res)
Definition at line 229 of file bio_reader.c.
References read_uint16_internal(), and TRUE.
 {
     return read_uint16_internal(this, res, TRUE);
 }
METHOD (bio_reader_t , read_uint24_end , bool , private_bio_reader_t * this, u_int32_t * res)
Definition at line 235 of file bio_reader.c.
References read_uint24_internal(), and TRUE.
 {
     return read_uint24_internal(this, res, TRUE);
 }
METHOD (bio_reader_t , read_uint32_end , bool , private_bio_reader_t * this, u_int32_t * res)
Definition at line 241 of file bio_reader.c.
References read_uint32_internal(), and TRUE.
 {
     return read_uint32_internal(this, res, TRUE);
 }
METHOD (bio_reader_t , read_uint64_end , bool , private_bio_reader_t * this, u_int64_t * res)
Definition at line 247 of file bio_reader.c.
References read_uint64_internal(), and TRUE.
 {
     return read_uint64_internal(this, res, TRUE);
 }
METHOD (bio_reader_t , read_data_end , bool , private_bio_reader_t * this, u_int32_t len, chunk_t * res)
Definition at line 253 of file bio_reader.c.
References read_data_internal(), and TRUE.
 {
     return read_data_internal(this, len, res, TRUE);
 }
METHOD (bio_reader_t , read_data8 , bool , private_bio_reader_t * this, chunk_t * res)
Definition at line 259 of file bio_reader.c.
References FALSE, and len.
 {
     u_int8_t len;
     if (!read_uint8(this, &len))
     {
         return FALSE;
     }
     return read_data(this, len, res);
 }
METHOD (bio_reader_t , read_data16 , bool , private_bio_reader_t * this, chunk_t * res)
Definition at line 271 of file bio_reader.c.
References FALSE, and len.
 {
     u_int16_t len;
     if (!read_uint16(this, &len))
     {
         return FALSE;
     }
     return read_data(this, len, res);
 }
METHOD (bio_reader_t , read_data24 , bool , private_bio_reader_t * this, chunk_t * res)
Definition at line 283 of file bio_reader.c.
References FALSE, and len.
 {
     u_int32_t len;
     if (!read_uint24(this, &len))
     {
         return FALSE;
     }
     return read_data(this, len, res);
 }
METHOD (bio_reader_t , read_data32 , bool , private_bio_reader_t * this, chunk_t * res)
Definition at line 295 of file bio_reader.c.
References FALSE, len, and read_uint32().
 {
     u_int32_t len;
     if (!read_uint32(this, &len))
     {
         return FALSE;
     }
     return read_data(this, len, res);
 }
METHOD (bio_reader_t , destroy , void , private_bio_reader_t * this)
Definition at line 307 of file bio_reader.c.
References cleanup, and free().
 {
     free(this->cleanup.ptr);
     free(this);
 }
static bool read_data_internal (private_bio_reader_t * this, u_int32_t len, chunk_t * res, bool from_end) static
Read a chunk of data from the buffer, optionally from the end
Definition at line 173 of file bio_reader.c.
References chunk_create(), chunk_skip_end(), DBG1, DBG_LIB, FALSE, get_ptr_end(), and TRUE.
Referenced by METHOD().
 {
     if (this->buf.len < len)
     {
         DBG1(DBG_LIB, "%d bytes insufficient to parse %d bytes of data",
              this->buf.len, len);
         return FALSE;
     }
     *res = chunk_create(get_ptr_end(this, len, from_end), len);
     this->buf = chunk_skip_end(this->buf, len, from_end);
     return TRUE;
 }
static bool read_uint16_internal (private_bio_reader_t * this, u_int16_t * res, bool from_end) static
Read an u_int16_t from the buffer, optionally from the end
Definition at line 105 of file bio_reader.c.
References chunk_skip_end(), DBG1, DBG_LIB, FALSE, get_ptr_end(), TRUE, and untoh16().
Referenced by METHOD().
 {
     if (this->buf.len < 2)
     {
         DBG1(DBG_LIB, "%d bytes insufficient to parse u_int16 data",
              this->buf.len);
         return FALSE;
     }
     *res = untoh16(get_ptr_end(this, 2, from_end));
     this->buf = chunk_skip_end(this->buf, 2, from_end);
     return TRUE;
 }
static bool read_uint24_internal (private_bio_reader_t * this, u_int32_t * res, bool from_end) static
Read an u_int32_t (only 24-bit) from the buffer, optionally from the end
Definition at line 122 of file bio_reader.c.
References chunk_skip_end(), DBG1, DBG_LIB, FALSE, get_ptr_end(), TRUE, and untoh32().
Referenced by METHOD().
 {
     if (this->buf.len < 3)
     {
         DBG1(DBG_LIB, "%d bytes insufficient to parse u_int24 data",
              this->buf.len);
         return FALSE;
     }
     *res = untoh32(get_ptr_end(this, 3, from_end)) >> 8;
     this->buf = chunk_skip_end(this->buf, 3, from_end);
     return TRUE;
 }
static bool read_uint32_internal (private_bio_reader_t * this, u_int32_t * res, bool from_end) static
Read an u_int32_t from the buffer, optionally from the end
Definition at line 139 of file bio_reader.c.
References chunk_skip_end(), DBG1, DBG_LIB, FALSE, get_ptr_end(), TRUE, and untoh32().
Referenced by METHOD().
 {
     if (this->buf.len < 4)
     {
         DBG1(DBG_LIB, "%d bytes insufficient to parse u_int32 data",
              this->buf.len);
         return FALSE;
     }
     *res = untoh32(get_ptr_end(this, 4, from_end));
     this->buf = chunk_skip_end(this->buf, 4, from_end);
     return TRUE;
 }
static bool read_uint64_internal (private_bio_reader_t * this, u_int64_t * res, bool from_end) static
Read an u_int64_t from the buffer, optionally from the end
Definition at line 156 of file bio_reader.c.
References chunk_skip_end(), DBG1, DBG_LIB, FALSE, get_ptr_end(), TRUE, and untoh64().
Referenced by METHOD().
 {
     if (this->buf.len < 8)
     {
         DBG1(DBG_LIB, "%d bytes insufficient to parse u_int64 data",
              this->buf.len);
         return FALSE;
     }
     *res = untoh64(get_ptr_end(this, 8, from_end));
     this->buf = chunk_skip_end(this->buf, 8, from_end);
     return TRUE;
 }
static bool read_uint8_internal (private_bio_reader_t * this, u_int8_t * res, bool from_end) static
Read an u_int8_t from the buffer, optionally from the end of the buffer
Definition at line 88 of file bio_reader.c.
References chunk_skip_end(), DBG1, DBG_LIB, FALSE, get_ptr_end(), and TRUE.
Referenced by METHOD().
 {
     if (this->buf.len < 1)
     {
         DBG1(DBG_LIB, "%d bytes insufficient to parse u_int8 data",
              this->buf.len);
         return FALSE;
     }
     *res = *get_ptr_end(this, 1, from_end);
     this->buf = chunk_skip_end(this->buf, 1, from_end);
     return TRUE;
 }