strongSwan: keymat_v1.c File Reference
keymat_v1.c File Reference
#include "keymat_v1.h"
#include <daemon.h>
#include <encoding/generator.h>
#include <encoding/payloads/nonce_payload.h>
#include <collections/linked_list.h>
Classes
struct iv_data_t
struct private_keymat_v1_t
struct qm_data_t
struct private_aead_t
Macros
#define MAX_EXCHANGES_DEFAULT 3
Typedefs
typedef struct private_keymat_v1_t private_keymat_v1_t
Functions
static void iv_data_destroy (iv_data_t *this)
static void qm_data_destroy (qm_data_t *this)
METHOD (aead_t, encrypt, bool, private_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encrypted)
METHOD (aead_t, decrypt, bool, private_aead_t *this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t *plain)
METHOD (aead_t, get_block_size, size_t, private_aead_t *this)
METHOD (aead_t, get_icv_size, size_t, private_aead_t *this)
METHOD (aead_t, get_iv_size, size_t, private_aead_t *this)
METHOD (aead_t, get_iv_gen, iv_gen_t *, private_aead_t *this)
METHOD (aead_t, get_key_size, size_t, private_aead_t *this)
METHOD (aead_t, set_key, bool, private_aead_t *this, chunk_t key)
METHOD (aead_t, aead_destroy, void, private_aead_t *this)
static bool expand_skeyid_e (chunk_t skeyid_e, size_t key_size, prf_t *prf, chunk_t *ka)
static aead_t * create_aead (proposal_t *proposal, prf_t *prf, chunk_t skeyid_e)
static u_int16_t auth_to_prf (u_int16_t alg)
static u_int16_t auth_to_hash (u_int16_t alg)
static void adjust_keylen (u_int16_t alg, chunk_t *key)
METHOD (keymat_v1_t, derive_ike_keys, bool, private_keymat_v1_t *this, proposal_t *proposal, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_id_t *id, auth_method_t auth, shared_key_t *shared_key)
METHOD (keymat_v1_t, derive_child_keys, bool, private_keymat_v1_t *this, proposal_t *proposal, diffie_hellman_t *dh, u_int32_t spi_i, u_int32_t spi_r, chunk_t nonce_i, chunk_t nonce_r, chunk_t *encr_i, chunk_t *integ_i, chunk_t *encr_r, chunk_t *integ_r)
METHOD (keymat_v1_t, create_hasher, bool, private_keymat_v1_t *this, proposal_t *proposal)
METHOD (keymat_v1_t, get_hasher, hasher_t *, private_keymat_v1_t *this)
METHOD (keymat_v1_t, get_hash, bool, private_keymat_v1_t *this, bool initiator, chunk_t dh, chunk_t dh_other, ike_sa_id_t *ike_sa_id, chunk_t sa_i, chunk_t id, chunk_t *hash)
static bool get_nonce (message_t *message, chunk_t *n)
static chunk_t get_message_data (message_t *message, generator_t *generator)
static qm_data_t * lookup_quick_mode (private_keymat_v1_t *this, u_int32_t mid)
METHOD (keymat_v1_t, get_hash_phase2, bool, private_keymat_v1_t *this, message_t *message, chunk_t *hash)
static bool generate_iv (private_keymat_v1_t *this, iv_data_t *iv)
static iv_data_t * lookup_iv (private_keymat_v1_t *this, u_int32_t mid)
METHOD (keymat_v1_t, get_iv, bool, private_keymat_v1_t *this, u_int32_t mid, chunk_t *out)
METHOD (keymat_v1_t, update_iv, bool, private_keymat_v1_t *this, u_int32_t mid, chunk_t last_block)
METHOD (keymat_v1_t, confirm_iv, bool, private_keymat_v1_t *this, u_int32_t mid)
METHOD (keymat_t, get_version, ike_version_t, private_keymat_v1_t *this)
METHOD (keymat_t, create_dh, diffie_hellman_t *, private_keymat_v1_t *this, diffie_hellman_group_t group)
METHOD (keymat_t, create_nonce_gen, nonce_gen_t *, private_keymat_v1_t *this)
METHOD (keymat_t, get_aead, aead_t *, private_keymat_v1_t *this, bool in)
METHOD (keymat_t, destroy, void, private_keymat_v1_t *this)
keymat_v1_t * keymat_v1_create (bool initiator)
Variables
static const chunk_t octet_0 = chunk_from_chars(0x00)
static const chunk_t octet_1 = chunk_from_chars(0x01)
static const chunk_t octet_2 = chunk_from_chars(0x02)
Macro Definition Documentation
#define MAX_EXCHANGES_DEFAULT 3
Max. number of IVs/QMs to track.
Definition at line 28 of file keymat_v1.c.
Referenced by keymat_v1_create().
Typedef Documentation
typedef struct private_keymat_v1_t private_keymat_v1_t
Definition at line 23 of file keymat_v1.c.
Function Documentation
static void adjust_keylen (u_int16_t alg, chunk_t * key) static
Adjust the key length for PRF algorithms that expect a fixed key length.
Definition at line 373 of file keymat_v1.c.
References chunk_t::len, min, and PRF_AES128_XCBC.
Referenced by METHOD().
 {
     switch (alg)
     {
         case PRF_AES128_XCBC:
             /* while rfc4434 defines variable keys for AES-XCBC, rfc3664 does
              * not and therefore fixed key semantics apply to XCBC for key
              * derivation. */
             key->len = min(key->len, 16);
             break;
         default:
             /* all other algorithms use variable key length */
             break;
     }
 }
static u_int16_t auth_to_hash (u_int16_t alg) static
Converts integrity algorithm to hash algorithm
Definition at line 351 of file keymat_v1.c.
References AUTH_HMAC_MD5_96, AUTH_HMAC_SHA1_96, AUTH_HMAC_SHA2_256_128, AUTH_HMAC_SHA2_384_192, AUTH_HMAC_SHA2_512_256, HASH_MD5, HASH_SHA1, HASH_SHA256, HASH_SHA384, HASH_SHA512, and HASH_UNKNOWN.
Referenced by METHOD().
 {
     switch (alg)
     {
         case AUTH_HMAC_SHA1_96:
             return HASH_SHA1;
         case AUTH_HMAC_SHA2_256_128:
             return HASH_SHA256;
         case AUTH_HMAC_SHA2_384_192:
             return HASH_SHA384;
         case AUTH_HMAC_SHA2_512_256:
             return HASH_SHA512;
         case AUTH_HMAC_MD5_96:
             return HASH_MD5;
         default:
             return HASH_UNKNOWN;
     }
 }
static u_int16_t auth_to_prf (u_int16_t alg) static
Converts integrity algorithm to PRF algorithm
Definition at line 327 of file keymat_v1.c.
References AUTH_AES_XCBC_96, AUTH_HMAC_MD5_96, AUTH_HMAC_SHA1_96, AUTH_HMAC_SHA2_256_128, AUTH_HMAC_SHA2_384_192, AUTH_HMAC_SHA2_512_256, PRF_AES128_XCBC, PRF_HMAC_MD5, PRF_HMAC_SHA1, PRF_HMAC_SHA2_256, PRF_HMAC_SHA2_384, PRF_HMAC_SHA2_512, and PRF_UNDEFINED.
Referenced by METHOD().
 {
     switch (alg)
     {
         case AUTH_HMAC_SHA1_96:
             return PRF_HMAC_SHA1;
         case AUTH_HMAC_SHA2_256_128:
             return PRF_HMAC_SHA2_256;
         case AUTH_HMAC_SHA2_384_192:
             return PRF_HMAC_SHA2_384;
         case AUTH_HMAC_SHA2_512_256:
             return PRF_HMAC_SHA2_512;
         case AUTH_HMAC_MD5_96:
             return PRF_HMAC_MD5;
         case AUTH_AES_XCBC_96:
             return PRF_AES128_XCBC;
         default:
             return PRF_UNDEFINED;
     }
 }
static aead_t* create_aead (proposal_t * proposal, prf_t * prf, chunk_t skeyid_e) static
Create a simple implementation of the aead_t interface which only encrypts or decrypts data.
Definition at line 272 of file keymat_v1.c.
References aead, alg, chunk_clear(), crypto_factory_t::create_crypter, crypter, library_t::crypto, DBG1, DBG4, DBG_IKE, aead_t::encrypt, ENCRYPTION_ALGORITHM, encryption_algorithm_names, expand_skeyid_e(), proposal_t::get_algorithm, crypter_t::get_key_size, INIT, key_size, lib, prf, crypter_t::set_key, and transform_type_names.
Referenced by METHOD().
 {
     private_aead_t *this;
     u_int16_t alg, key_size;
     crypter_t *crypter;
     chunk_t ka;
     if (!proposal->get_algorithm(proposal, ENCRYPTION_ALGORITHM, &alg,
                                  &key_size))
     {
         DBG1(DBG_IKE, "no %N selected",
              transform_type_names, ENCRYPTION_ALGORITHM);
         return NULL;
     }
     crypter = lib->crypto->create_crypter(lib->crypto, alg, key_size / 8);
     if (!crypter)
     {
         DBG1(DBG_IKE, "%N %N (key size %d) not supported!",
              transform_type_names, ENCRYPTION_ALGORITHM,
              encryption_algorithm_names, alg, key_size);
         return NULL;
     }
     key_size = crypter->get_key_size(crypter);
     if (!expand_skeyid_e(skeyid_e, crypter->get_key_size(crypter), prf, &ka))
     {
         return NULL;
     }
     DBG4(DBG_IKE, "encryption key Ka %B", &ka);
     if (!crypter->set_key(crypter, ka))
     {
         chunk_clear(&ka);
         return NULL;
     }
     chunk_clear(&ka);
     INIT(this,
         .aead = {
             .encrypt = _encrypt,
             .decrypt = _decrypt,
             .get_block_size = _get_block_size,
             .get_icv_size = _get_icv_size,
             .get_iv_size = _get_iv_size,
             .get_iv_gen = _get_iv_gen,
             .get_key_size = _get_key_size,
             .set_key = _set_key,
             .destroy = _aead_destroy,
         },
         .crypter = crypter,
     );
     return &this->aead;
 }
static bool expand_skeyid_e (chunk_t skeyid_e, size_t key_size, prf_t * prf, chunk_t * ka) static
Expand SKEYID_e according to Appendix B in RFC 2409. TODO-IKEv1: verify keys (e.g. for weak keys, see Appendix B)
Definition at line 229 of file keymat_v1.c.
References block_size, chunk_alloc, chunk_clear(), chunk_create(), FALSE, prf_t::get_block_size, prf_t::get_bytes, key_size, chunk_t::len, octet_0, chunk_t::ptr, prf_t::set_key, and TRUE.
Referenced by create_aead().
 {
     size_t block_size;
     chunk_t seed;
     int i;
     if (skeyid_e.len >= key_size)
     {   /* no expansion required, reduce to key_size */
         skeyid_e.len = key_size;
         *ka = skeyid_e;
         return TRUE;
     }
     block_size = prf->get_block_size(prf);
     *ka = chunk_alloc((key_size / block_size + 1) * block_size);
     ka->len = key_size;
     /* Ka = K1 | K2 | ..., K1 = prf(SKEYID_e, 0), K2 = prf(SKEYID_e, K1) ... */
     if (!prf->set_key(prf, skeyid_e))
     {
         chunk_clear(ka);
         chunk_clear(&skeyid_e);
         return FALSE;
     }
     seed = octet_0;
     for (i = 0; i < key_size; i += block_size)
     {
         if (!prf->get_bytes(prf, seed, ka->ptr + i))
         {
             chunk_clear(ka);
             chunk_clear(&skeyid_e);
             return FALSE;
         }
         seed = chunk_create(ka->ptr + i, block_size);
     }
     chunk_clear(&skeyid_e);
     return TRUE;
 }
static bool generate_iv (private_keymat_v1_t * this, iv_data_t * iv) static
Generate an IV
Definition at line 985 of file keymat_v1.c.
References aead, chunk_cata, chunk_empty, chunk_free(), chunk_from_thing, data, DBG4, DBG_IKE, FALSE, aead_t::get_block_size, hasher, iv_data_t::iv, iv_data_t::last_block, chunk_t::len, iv_data_t::mid, net, chunk_t::ptr, and TRUE.
Referenced by lookup_iv(), and METHOD().
 {
     if (iv->mid == 0 || iv->iv.ptr)
     {   /* use last block of previous encrypted message */
         chunk_free(&iv->iv);
         iv->iv = iv->last_block;
         iv->last_block = chunk_empty;
     }
     else
     {
         /* initial phase 2 IV = hash(last_phase1_block | mid) */
         u_int32_t net;;
         chunk_t data;
         net = htonl(iv->mid);
         data = chunk_cata("cc", this->phase1_iv.iv, chunk_from_thing(net));
         if (!this->hasher->allocate_hash(this->hasher, data, &iv->iv))
         {
             return FALSE;
         }
         if (iv->iv.len > this->aead->get_block_size(this->aead))
         {
             iv->iv.len = this->aead->get_block_size(this->aead);
         }
     }
     DBG4(DBG_IKE, "next IV for MID %u %B", iv->mid, &iv->iv);
     return TRUE;
 }
static chunk_t get_message_data (message_t * message, generator_t * generator) static
Generate the message data in order to generate the hashes.
Definition at line 809 of file keymat_v1.c.
References message_t::create_payload_enumerator, enumerator_t::destroy, enumerator_t::enumerate, generator_t::generate_payload, generator_t::get_chunk, payload_t::get_type, message_t::is_encoded, next, PL_NONE, PLV1_HASH, and payload_t::set_next_type.
Referenced by METHOD().
 {
     payload_t *payload, *next;
     enumerator_t *enumerator;
     u_int32_t *lenpos;
     if (message->is_encoded(message))
     {   /* inbound, although the message is generated, we cannot access the
          * cleartext message data, so generate it anyway */
         enumerator = message->create_payload_enumerator(message);
         while (enumerator->enumerate(enumerator, &payload))
         {
             if (payload->get_type(payload) == PLV1_HASH)
             {
                 continue;
             }
             generator->generate_payload(generator, payload);
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         /* outbound, generate the payloads (there is no HASH payload yet) */
         enumerator = message->create_payload_enumerator(message);
         if (enumerator->enumerate(enumerator, &payload))
         {
             while (enumerator->enumerate(enumerator, &next))
             {
                 payload->set_next_type(payload, next->get_type(next));
                 generator->generate_payload(generator, payload);
                 payload = next;
             }
             payload->set_next_type(payload, PL_NONE);
             generator->generate_payload(generator, payload);
         }
         enumerator->destroy(enumerator);
     }
     return generator->get_chunk(generator, &lenpos);
 }
static bool get_nonce (message_t * message, chunk_t * n) static
Get the nonce value found in the given message. Returns FALSE if none is found.
Definition at line 794 of file keymat_v1.c.
References FALSE, nonce_payload_t::get_nonce, message_t::get_payload, PLV1_NONCE, and TRUE.
Referenced by METHOD().
 {
     nonce_payload_t *nonce;
     nonce = (nonce_payload_t*)message->get_payload(message, PLV1_NONCE);
     if (nonce)
     {
         *n = nonce->get_nonce(nonce);
         return TRUE;
     }
     return FALSE;
 }
static void iv_data_destroy (iv_data_t * this) static
Destroy an iv_data_t object.
Definition at line 119 of file keymat_v1.c.
References chunk_free(), and free().
Referenced by lookup_iv(), and METHOD().
 {
     chunk_free(&this->last_block);
     chunk_free(&this->iv);
     free(this);
 }
static iv_data_t* lookup_iv (private_keymat_v1_t * this, u_int32_t mid) static
Try to find an IV for the given message ID, if not found, generate it.
Definition at line 1017 of file keymat_v1.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, generate_iv(), INIT, iv_data_destroy(), iv_data_t::mid, and SUCCESS.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     iv_data_t *iv, *found = NULL;
     if (mid == 0)
     {
         return &this->phase1_iv;
     }
     enumerator = this->ivs->create_enumerator(this->ivs);
     while (enumerator->enumerate(enumerator, &iv))
     {
         if (iv->mid == mid)
         {   /* IV gets moved to the front of the list */
             this->ivs->remove_at(this->ivs, enumerator);
             found = iv;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         INIT(found,
             .mid = mid,
         );
         if (!generate_iv(this, found))
         {
             iv_data_destroy(found);
             return NULL;
         }
     }
     this->ivs->insert_first(this->ivs, found);
     /* remove least recently used IV if maximum reached */
     if (this->ivs->get_count(this->ivs) > this->max_exchanges &&
         this->ivs->remove_last(this->ivs, (void**)&iv) == SUCCESS)
     {
         iv_data_destroy(iv);
     }
     return found;
 }
static qm_data_t* lookup_quick_mode (private_keymat_v1_t * this, u_int32_t mid) static
Try to find data about a Quick Mode with the given message ID, if none is found, state is generated.
Definition at line 853 of file keymat_v1.c.
References enumerator_t::destroy, enumerator_t::enumerate, found, INIT, qm_data_t::mid, qm_data_destroy(), and SUCCESS.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     qm_data_t *qm, *found = NULL;
     enumerator = this->qms->create_enumerator(this->qms);
     while (enumerator->enumerate(enumerator, &qm))
     {
         if (qm->mid == mid)
         {   /* state gets moved to the front of the list */
             this->qms->remove_at(this->qms, enumerator);
             found = qm;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         INIT(found,
             .mid = mid,
         );
     }
     this->qms->insert_first(this->qms, found);
     /* remove least recently used state if maximum reached */
     if (this->qms->get_count(this->qms) > this->max_exchanges &&
         this->qms->remove_last(this->qms, (void**)&qm) == SUCCESS)
     {
         qm_data_destroy(qm);
     }
     return found;
 }
METHOD (aead_t , encrypt , bool , private_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t * encrypted)
Definition at line 166 of file keymat_v1.c.
References crypter.
 {
     return this->crypter->encrypt(this->crypter, plain, iv, encrypted);
 }
METHOD (aead_t , decrypt , bool , private_aead_t * this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t * plain)
Definition at line 173 of file keymat_v1.c.
References crypter.
 {
     return this->crypter->decrypt(this->crypter, encrypted, iv, plain);
 }
METHOD (aead_t , get_block_size , size_t , private_aead_t * this)
Definition at line 180 of file keymat_v1.c.
References crypter.
 {
     return this->crypter->get_block_size(this->crypter);
 }
METHOD (aead_t , get_icv_size , size_t , private_aead_t * this)
Definition at line 186 of file keymat_v1.c.
 {
     return 0;
 }
METHOD (aead_t , get_iv_size , size_t , private_aead_t * this)
Definition at line 192 of file keymat_v1.c.
 {
     /* in order to create the messages properly we return 0 here */
     return 0;
 }
METHOD (aead_t , get_iv_gen , iv_gen_t * , private_aead_t * this)
Definition at line 199 of file keymat_v1.c.
 {
     /* IVs are retrieved via keymat_v1.get_iv() */
     return NULL;
 }
METHOD (aead_t , get_key_size , size_t , private_aead_t * this)
Definition at line 206 of file keymat_v1.c.
References crypter.
 {
     return this->crypter->get_key_size(this->crypter);
 }
METHOD (aead_t , set_key , bool , private_aead_t * this, chunk_t key)
Definition at line 212 of file keymat_v1.c.
References crypter.
 {
     return this->crypter->set_key(this->crypter, key);
 }
METHOD (aead_t , aead_destroy , void , private_aead_t * this)
Definition at line 218 of file keymat_v1.c.
References crypter, and free().
 {
     this->crypter->destroy(this->crypter);
     free(this);
 }
METHOD (keymat_v1_t , derive_ike_keys , bool , private_keymat_v1_t * this, proposal_t * proposal, diffie_hellman_t * dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_id_t * id, auth_method_t auth, shared_key_t * shared_key)
Definition at line 389 of file keymat_v1.c.
References adjust_keylen(), aead, alg, AUTH_ECDSA_256, AUTH_ECDSA_384, AUTH_ECDSA_521, AUTH_HYBRID_INIT_RSA, AUTH_HYBRID_RESP_RSA, AUTH_PSK, AUTH_RSA, auth_to_prf(), AUTH_XAUTH_INIT_PSK, AUTH_XAUTH_INIT_RSA, AUTH_XAUTH_RESP_PSK, AUTH_XAUTH_RESP_RSA, chunk_alloca, chunk_cat, chunk_cata, chunk_clear(), chunk_free(), create_aead(), crypto_factory_t::create_prf, library_t::crypto, data, DBG1, DBG4, DBG_IKE, FALSE, proposal_t::get_algorithm, aead_t::get_block_size, shared_key_t::get_key, diffie_hellman_t::get_my_public_value, diffie_hellman_t::get_shared_secret, hasher, initiator, INTEGRITY_ALGORITHM, lib, prf, PRF_HMAC_SHA2_256, PRF_HMAC_SHA2_384, PRF_HMAC_SHA2_512, PRF_UNDEFINED, PSEUDO_RANDOM_FUNCTION, pseudo_random_function_names, chunk_t::ptr, transform_type_names, and TRUE.
 {
     chunk_t g_xy, g_xi, g_xr, dh_me, spi_i, spi_r, nonces, data, skeyid_e;
     chunk_t skeyid;
     u_int16_t alg;
     spi_i = chunk_alloca(sizeof(u_int64_t));
     spi_r = chunk_alloca(sizeof(u_int64_t));
     if (!proposal->get_algorithm(proposal, PSEUDO_RANDOM_FUNCTION, &alg, NULL))
     {   /* no PRF negotiated, use HMAC version of integrity algorithm instead */
         if (!proposal->get_algorithm(proposal, INTEGRITY_ALGORITHM, &alg, NULL)
             || (alg = auth_to_prf(alg)) == PRF_UNDEFINED)
         {
             DBG1(DBG_IKE, "no %N selected",
                  transform_type_names, PSEUDO_RANDOM_FUNCTION);
             return FALSE;
         }
     }
     this->prf = lib->crypto->create_prf(lib->crypto, alg);
     if (!this->prf)
     {
         DBG1(DBG_IKE, "%N %N not supported!",
              transform_type_names, PSEUDO_RANDOM_FUNCTION,
              pseudo_random_function_names, alg);
         return FALSE;
     }
     if (this->prf->get_block_size(this->prf) <
         this->prf->get_key_size(this->prf))
     {   /* TODO-IKEv1: support PRF output expansion (RFC 2409, Appendix B) */
         DBG1(DBG_IKE, "expansion of %N %N output not supported!",
              transform_type_names, PSEUDO_RANDOM_FUNCTION,
              pseudo_random_function_names, alg);
         return FALSE;
     }
     if (!dh->get_shared_secret(dh, &g_xy))
     {
         return FALSE;
     }
     DBG4(DBG_IKE, "shared Diffie Hellman secret %B", &g_xy);
     *((u_int64_t*)spi_i.ptr) = id->get_initiator_spi(id);
     *((u_int64_t*)spi_r.ptr) = id->get_responder_spi(id);
     nonces = chunk_cata("cc", nonce_i, nonce_r);
     switch (auth)
     {
         case AUTH_PSK:
         case AUTH_XAUTH_INIT_PSK:
         case AUTH_XAUTH_RESP_PSK:
         {   /* SKEYID = prf(pre-shared-key, Ni_b | Nr_b) */
             chunk_t psk;
             if (!shared_key)
             {
                 chunk_clear(&g_xy);
                 return FALSE;
             }
             psk = shared_key->get_key(shared_key);
             adjust_keylen(alg, &psk);
             if (!this->prf->set_key(this->prf, psk) ||
                 !this->prf->allocate_bytes(this->prf, nonces, &skeyid))
             {
                 chunk_clear(&g_xy);
                 return FALSE;
             }
             break;
         }
         case AUTH_RSA:
         case AUTH_ECDSA_256:
         case AUTH_ECDSA_384:
         case AUTH_ECDSA_521:
         case AUTH_XAUTH_INIT_RSA:
         case AUTH_XAUTH_RESP_RSA:
         case AUTH_HYBRID_INIT_RSA:
         case AUTH_HYBRID_RESP_RSA:
         {
             if (!this->prf->set_key(this->prf, nonces) ||
                 !this->prf->allocate_bytes(this->prf, g_xy, &skeyid))
             {
                 chunk_clear(&g_xy);
                 return FALSE;
             }
             break;
         }
         default:
             /* TODO-IKEv1: implement key derivation for other schemes */
             /* authentication class not supported */
             chunk_clear(&g_xy);
             return FALSE;
     }
     adjust_keylen(alg, &skeyid);
     DBG4(DBG_IKE, "SKEYID %B", &skeyid);
     /* SKEYID_d = prf(SKEYID, g^xy | CKY-I | CKY-R | 0) */
     data = chunk_cat("cccc", g_xy, spi_i, spi_r, octet_0);
     if (!this->prf->set_key(this->prf, skeyid) ||
         !this->prf->allocate_bytes(this->prf, data, &this->skeyid_d))
     {
         chunk_clear(&g_xy);
         chunk_clear(&data);
         return FALSE;
     }
     chunk_clear(&data);
     DBG4(DBG_IKE, "SKEYID_d %B", &this->skeyid_d);
     /* SKEYID_a = prf(SKEYID, SKEYID_d | g^xy | CKY-I | CKY-R | 1) */
     data = chunk_cat("ccccc", this->skeyid_d, g_xy, spi_i, spi_r, octet_1);
     if (!this->prf->allocate_bytes(this->prf, data, &this->skeyid_a))
     {
         chunk_clear(&g_xy);
         chunk_clear(&data);
         return FALSE;
     }
     chunk_clear(&data);
     DBG4(DBG_IKE, "SKEYID_a %B", &this->skeyid_a);
     /* SKEYID_e = prf(SKEYID, SKEYID_a | g^xy | CKY-I | CKY-R | 2) */
     data = chunk_cat("ccccc", this->skeyid_a, g_xy, spi_i, spi_r, octet_2);
     if (!this->prf->allocate_bytes(this->prf, data, &skeyid_e))
     {
         chunk_clear(&g_xy);
         chunk_clear(&data);
         return FALSE;
     }
     chunk_clear(&data);
     DBG4(DBG_IKE, "SKEYID_e %B", &skeyid_e);
     chunk_clear(&g_xy);
     switch (auth)
     {
         case AUTH_ECDSA_256:
             alg = PRF_HMAC_SHA2_256;
             break;
         case AUTH_ECDSA_384:
             alg =  PRF_HMAC_SHA2_384;
             break;
         case AUTH_ECDSA_521:
             alg = PRF_HMAC_SHA2_512;
             break;
         default:
             /* use proposal algorithm */
             break;
     }
     this->prf_auth = lib->crypto->create_prf(lib->crypto, alg);
     if (!this->prf_auth)
     {
         DBG1(DBG_IKE, "%N %N not supported!",
              transform_type_names, PSEUDO_RANDOM_FUNCTION,
              pseudo_random_function_names, alg);
         chunk_clear(&skeyid);
         return FALSE;
     }
     if (!this->prf_auth->set_key(this->prf_auth, skeyid))
     {
         chunk_clear(&skeyid);
         return FALSE;
     }
     chunk_clear(&skeyid);
     this->aead = create_aead(proposal, this->prf, skeyid_e);
     if (!this->aead)
     {
         return FALSE;
     }
     if (!this->hasher && !this->public.create_hasher(&this->public, proposal))
     {
         return FALSE;
     }
     if (!dh->get_my_public_value(dh, &dh_me))
     {
         return FALSE;
     }
     g_xi = this->initiator ? dh_me : dh_other;
     g_xr = this->initiator ? dh_other : dh_me;
     /* initial IV = hash(g^xi | g^xr) */
     data = chunk_cata("cc", g_xi, g_xr);
     chunk_free(&dh_me);
     if (!this->hasher->allocate_hash(this->hasher, data, &this->phase1_iv.iv))
     {
         return FALSE;
     }
     if (this->phase1_iv.iv.len > this->aead->get_block_size(this->aead))
     {
         this->phase1_iv.iv.len = this->aead->get_block_size(this->aead);
     }
     DBG4(DBG_IKE, "initial IV %B", &this->phase1_iv.iv);
     return TRUE;
 }
METHOD (keymat_v1_t , derive_child_keys , bool , private_keymat_v1_t * this, proposal_t * proposal, diffie_hellman_t * dh, u_int32_t spi_i, u_int32_t spi_r, chunk_t nonce_i, chunk_t nonce_r, chunk_t * encr_i, chunk_t * integ_i, chunk_t * encr_r, chunk_t * integ_r)
Definition at line 586 of file keymat_v1.c.
References prf_plus_t::allocate_bytes, chunk_cata, chunk_clear(), chunk_empty, chunk_from_thing, DBG1, DBG2, DBG4, DBG_CHD, prf_plus_t::destroy, DESTROY_IF, ENCR_AES_CCM_ICV12, ENCR_AES_CCM_ICV16, ENCR_AES_CCM_ICV8, ENCR_AES_CTR, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, ENCR_CAMELLIA_CCM_ICV12, ENCR_CAMELLIA_CCM_ICV16, ENCR_CAMELLIA_CCM_ICV8, ENCR_NULL, ENCR_NULL_AUTH_AES_GMAC, ENCRYPTION_ALGORITHM, encryption_algorithm_names, FALSE, proposal_t::get_algorithm, proposal_t::get_protocol, diffie_hellman_t::get_shared_secret, INTEGRITY_ALGORITHM, integrity_algorithm_names, keymat_get_keylen_encr(), keymat_get_keylen_integ(), prf, prf_plus_create(), protocol, and TRUE.
 {
     u_int16_t enc_alg, int_alg, enc_size = 0, int_size = 0;
     u_int8_t protocol;
     prf_plus_t *prf_plus;
     chunk_t seed, secret = chunk_empty;
     bool success = FALSE;
     if (proposal->get_algorithm(proposal, ENCRYPTION_ALGORITHM,
                                 &enc_alg, &enc_size))
     {
         DBG2(DBG_CHD, "  using %N for encryption",
              encryption_algorithm_names, enc_alg);
         if (!enc_size)
         {
             enc_size = keymat_get_keylen_encr(enc_alg);
         }
         if (enc_alg != ENCR_NULL && !enc_size)
         {
             DBG1(DBG_CHD, "no keylength defined for %N",
                  encryption_algorithm_names, enc_alg);
             return FALSE;
         }
         /* to bytes */
         enc_size /= 8;
         /* CCM/GCM/CTR/GMAC needs additional bytes */
         switch (enc_alg)
         {
             case ENCR_AES_CCM_ICV8:
             case ENCR_AES_CCM_ICV12:
             case ENCR_AES_CCM_ICV16:
             case ENCR_CAMELLIA_CCM_ICV8:
             case ENCR_CAMELLIA_CCM_ICV12:
             case ENCR_CAMELLIA_CCM_ICV16:
                 enc_size += 3;
                 break;
             case ENCR_AES_GCM_ICV8:
             case ENCR_AES_GCM_ICV12:
             case ENCR_AES_GCM_ICV16:
             case ENCR_AES_CTR:
             case ENCR_NULL_AUTH_AES_GMAC:
                 enc_size += 4;
                 break;
             default:
                 break;
         }
     }
     if (proposal->get_algorithm(proposal, INTEGRITY_ALGORITHM,
                                 &int_alg, &int_size))
     {
         DBG2(DBG_CHD, "  using %N for integrity",
              integrity_algorithm_names, int_alg);
         if (!int_size)
         {
             int_size = keymat_get_keylen_integ(int_alg);
         }
         if (!int_size)
         {
             DBG1(DBG_CHD, "no keylength defined for %N",
                  integrity_algorithm_names, int_alg);
             return FALSE;
         }
         /* to bytes */
         int_size /= 8;
     }
     /* KEYMAT = prf+(SKEYID_d, [ g(qm)^xy | ] protocol | SPI | Ni_b | Nr_b) */
     if (!this->prf->set_key(this->prf, this->skeyid_d))
     {
         return FALSE;
     }
     protocol = proposal->get_protocol(proposal);
     if (dh)
     {
         if (!dh->get_shared_secret(dh, &secret))
         {
             return FALSE;
         }
         DBG4(DBG_CHD, "DH secret %B", &secret);
     }
     *encr_r = *integ_r = *encr_i = *integ_i = chunk_empty;
     seed = chunk_cata("ccccc", secret, chunk_from_thing(protocol),
                       chunk_from_thing(spi_r), nonce_i, nonce_r);
     DBG4(DBG_CHD, "initiator SA seed %B", &seed);
     prf_plus = prf_plus_create(this->prf, FALSE, seed);
     if (!prf_plus ||
         !prf_plus->allocate_bytes(prf_plus, enc_size, encr_i) ||
         !prf_plus->allocate_bytes(prf_plus, int_size, integ_i))
     {
         goto failure;
     }
     seed = chunk_cata("ccccc", secret, chunk_from_thing(protocol),
                       chunk_from_thing(spi_i), nonce_i, nonce_r);
     DBG4(DBG_CHD, "responder SA seed %B", &seed);
     prf_plus->destroy(prf_plus);
     prf_plus = prf_plus_create(this->prf, FALSE, seed);
     if (!prf_plus ||
         !prf_plus->allocate_bytes(prf_plus, enc_size, encr_r) ||
         !prf_plus->allocate_bytes(prf_plus, int_size, integ_r))
     {
         goto failure;
     }
     if (enc_size)
     {
         DBG4(DBG_CHD, "encryption initiator key %B", encr_i);
         DBG4(DBG_CHD, "encryption responder key %B", encr_r);
     }
     if (int_size)
     {
         DBG4(DBG_CHD, "integrity initiator key %B", integ_i);
         DBG4(DBG_CHD, "integrity responder key %B", integ_r);
     }
     success = TRUE;
 failure:
     if (!success)
     {
         chunk_clear(encr_i);
         chunk_clear(integ_i);
         chunk_clear(encr_r);
         chunk_clear(integ_r);
     }
     DESTROY_IF(prf_plus);
     chunk_clear(&secret);
     return success;
 }
METHOD (keymat_v1_t , create_hasher , bool , private_keymat_v1_t * this, proposal_t * proposal)
Definition at line 725 of file keymat_v1.c.
References alg, auth_to_hash(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_IKE, FALSE, proposal_t::get_algorithm, HASH_ALGORITHM, hash_algorithm_names, HASH_UNKNOWN, hasher, INTEGRITY_ALGORITHM, lib, transform_type_names, and TRUE.
 {
     u_int16_t alg;
     if (!proposal->get_algorithm(proposal, INTEGRITY_ALGORITHM, &alg, NULL) ||
         (alg = auth_to_hash(alg)) == HASH_UNKNOWN)
     {
         DBG1(DBG_IKE, "no %N selected", transform_type_names, HASH_ALGORITHM);
         return FALSE;
     }
     this->hasher = lib->crypto->create_hasher(lib->crypto, alg);
     if (!this->hasher)
     {
         DBG1(DBG_IKE, "%N %N not supported!",
              transform_type_names, HASH_ALGORITHM,
              hash_algorithm_names, alg);
         return FALSE;
     }
     return TRUE;
 }
METHOD (keymat_v1_t , get_hasher , hasher_t * , private_keymat_v1_t * this)
Definition at line 746 of file keymat_v1.c.
References hasher.
 {
     return this->hasher;
 }
METHOD (keymat_v1_t , get_hash , bool , private_keymat_v1_t * this, bool initiator, chunk_t dh, chunk_t dh_other, ike_sa_id_t * ike_sa_id, chunk_t sa_i, chunk_t id, chunk_t * hash)
Definition at line 752 of file keymat_v1.c.
References chunk_cat, chunk_from_thing, data, DBG3, DBG_IKE, FALSE, free(), ike_sa_id_t::get_initiator_spi, ike_sa_id_t::get_responder_spi, chunk_t::ptr, and TRUE.
 {
     chunk_t data;
     u_int64_t spi, spi_other;
     /* HASH_I = prf(SKEYID, g^xi | g^xr | CKY-I | CKY-R | SAi_b | IDii_b )
      * HASH_R = prf(SKEYID, g^xr | g^xi | CKY-R | CKY-I | SAi_b | IDir_b )
      */
     if (initiator)
     {
         spi = ike_sa_id->get_initiator_spi(ike_sa_id);
         spi_other = ike_sa_id->get_responder_spi(ike_sa_id);
     }
     else
     {
         spi_other = ike_sa_id->get_initiator_spi(ike_sa_id);
         spi = ike_sa_id->get_responder_spi(ike_sa_id);
     }
     data = chunk_cat("cccccc", dh, dh_other,
                      chunk_from_thing(spi), chunk_from_thing(spi_other),
                      sa_i, id);
     DBG3(DBG_IKE, "HASH_%c data %B", initiator ? 'I' : 'R', &data);
     if (!this->prf_auth->allocate_bytes(this->prf_auth, data, hash))
     {
         free(data.ptr);
         return FALSE;
     }
     DBG3(DBG_IKE, "HASH_%c %B", initiator ? 'I' : 'R', hash);
     free(data.ptr);
     return TRUE;
 }
METHOD (keymat_v1_t , get_hash_phase2 , bool , private_keymat_v1_t * this, message_t * message, chunk_t * hash)
Definition at line 885 of file keymat_v1.c.
References chunk_cata, chunk_empty, chunk_from_thing, data, DBG3, DBG_IKE, generator_t::destroy, FALSE, generator_create_no_dbg(), message_t::get_exchange_type, get_message_data(), message_t::get_message_id, get_nonce(), INFORMATIONAL_V1, lookup_quick_mode(), msg, qm_data_t::n_i, qm_data_t::n_r, name, prf, chunk_t::ptr, qm_data_destroy(), QUICK_MODE, TRANSACTION, and TRUE.
 {
     u_int32_t mid, mid_n;
     chunk_t data = chunk_empty;
     bool add_message = TRUE;
     char *name = "Hash";
     if (!this->prf)
     {   /* no keys derived yet */
         return FALSE;
     }
     mid = message->get_message_id(message);
     mid_n = htonl(mid);
     /* Hashes are simple for most exchanges in Phase 2:
      *   Hash = prf(SKEYID_a, M-ID | Complete message after HASH payload)
      * For Quick Mode there are three hashes:
      *   Hash(1) = same as above
      *   Hash(2) = prf(SKEYID_a, M-ID | Ni_b | Message after HASH payload)
      *   Hash(3) = prf(SKEYID_a, 0 | M-ID | Ni_b | Nr_b)
      * So, for Quick Mode we keep track of the nonce values.
      */
     switch (message->get_exchange_type(message))
     {
         case QUICK_MODE:
         {
             qm_data_t *qm = lookup_quick_mode(this, mid);
             if (!qm->n_i.ptr)
             {   /* Hash(1) = prf(SKEYID_a, M-ID | Message after HASH payload) */
                 name = "Hash(1)";
                 if (!get_nonce(message, &qm->n_i))
                 {
                     return FALSE;
                 }
                 data = chunk_from_thing(mid_n);
             }
             else if (!qm->n_r.ptr)
             {   /* Hash(2) = prf(SKEYID_a, M-ID | Ni_b | Message after HASH) */
                 name = "Hash(2)";
                 if (!get_nonce(message, &qm->n_r))
                 {
                     return FALSE;
                 }
                 data = chunk_cata("cc", chunk_from_thing(mid_n), qm->n_i);
             }
             else
             {   /* Hash(3) = prf(SKEYID_a, 0 | M-ID | Ni_b | Nr_b) */
                 name = "Hash(3)";
                 data = chunk_cata("cccc", octet_0, chunk_from_thing(mid_n),
                                   qm->n_i, qm->n_r);
                 add_message = FALSE;
                 /* we don't need the state anymore */
                 this->qms->remove(this->qms, qm, NULL);
                 qm_data_destroy(qm);
             }
             break;
         }
         case TRANSACTION:
         case INFORMATIONAL_V1:
             /* Hash = prf(SKEYID_a, M-ID | Message after HASH payload) */
             data = chunk_from_thing(mid_n);
             break;
         default:
             return FALSE;
     }
     if (!this->prf->set_key(this->prf, this->skeyid_a))
     {
         return FALSE;
     }
     if (add_message)
     {
         generator_t *generator;
         chunk_t msg;
         generator = generator_create_no_dbg();
         msg = get_message_data(message, generator);
         if (!this->prf->allocate_bytes(this->prf, data, NULL) ||
             !this->prf->allocate_bytes(this->prf, msg, hash))
         {
             generator->destroy(generator);
             return FALSE;
         }
         generator->destroy(generator);
     }
     else
     {
         if (!this->prf->allocate_bytes(this->prf, data, hash))
         {
             return FALSE;
         }
     }
     DBG3(DBG_IKE, "%s %B", name, hash);
     return TRUE;
 }
METHOD (keymat_v1_t , get_iv , bool , private_keymat_v1_t * this, u_int32_t mid, chunk_t * out)
Definition at line 1059 of file keymat_v1.c.
References FALSE, iv_data_t::iv, lookup_iv(), and TRUE.
 {
     iv_data_t *iv;
     iv = lookup_iv(this, mid);
     if (iv)
     {
         *out = iv->iv;
         return TRUE;
     }
     return FALSE;
 }
METHOD (keymat_v1_t , update_iv , bool , private_keymat_v1_t * this, u_int32_t mid, chunk_t last_block)
Definition at line 1073 of file keymat_v1.c.
References chunk_clone, chunk_free(), FALSE, iv_data_t::last_block, lookup_iv(), and TRUE.
 {
     iv_data_t *iv = lookup_iv(this, mid);
     if (iv)
     {   /* update last block */
         chunk_free(&iv->last_block);
         iv->last_block = chunk_clone(last_block);
         return TRUE;
     }
     return FALSE;
 }
METHOD (keymat_v1_t , confirm_iv , bool , private_keymat_v1_t * this, u_int32_t mid)
Definition at line 1086 of file keymat_v1.c.
References FALSE, generate_iv(), and lookup_iv().
 {
     iv_data_t *iv = lookup_iv(this, mid);
     if (iv)
     {
         return generate_iv(this, iv);
     }
     return FALSE;
 }
METHOD (keymat_t , get_version , ike_version_t , private_keymat_v1_t * this)
Definition at line 1097 of file keymat_v1.c.
References IKEV1.
 {
     return IKEV1;
 }
METHOD (keymat_t , create_dh , diffie_hellman_t * , private_keymat_v1_t * this, diffie_hellman_group_t group)
Definition at line 1103 of file keymat_v1.c.
References crypto_factory_t::create_dh, library_t::crypto, and lib.
 {
     return lib->crypto->create_dh(lib->crypto, group);
 }
METHOD (keymat_t , create_nonce_gen , nonce_gen_t * , private_keymat_v1_t * this)
Definition at line 1109 of file keymat_v1.c.
References crypto_factory_t::create_nonce_gen, library_t::crypto, and lib.
 {
     return lib->crypto->create_nonce_gen(lib->crypto);
 }
METHOD (keymat_t , get_aead , aead_t * , private_keymat_v1_t * this, bool in)
Definition at line 1115 of file keymat_v1.c.
References aead.
 {
     return this->aead;
 }
METHOD (keymat_t , destroy , void , private_keymat_v1_t * this)
Definition at line 1121 of file keymat_v1.c.
References aead, chunk_clear(), chunk_free(), DESTROY_IF, free(), hasher, iv_data_destroy(), prf, and qm_data_destroy().
 {
     DESTROY_IF(this->prf);
     DESTROY_IF(this->prf_auth);
     DESTROY_IF(this->aead);
     DESTROY_IF(this->hasher);
     chunk_clear(&this->skeyid_d);
     chunk_clear(&this->skeyid_a);
     chunk_free(&this->phase1_iv.iv);
     chunk_free(&this->phase1_iv.last_block);
     this->ivs->destroy_function(this->ivs, (void*)iv_data_destroy);
     this->qms->destroy_function(this->qms, (void*)qm_data_destroy);
     free(this);
 }
static void qm_data_destroy (qm_data_t * this) static
Destroy a qm_data_t object.
Definition at line 141 of file keymat_v1.c.
References chunk_free(), and free().
Referenced by lookup_quick_mode(), and METHOD().
 {
     chunk_free(&this->n_i);
     chunk_free(&this->n_r);
     free(this);
 }
Variable Documentation
const chunk_t octet_0 = chunk_from_chars(0x00) static
Constants used in key derivation.
Definition at line 151 of file keymat_v1.c.
Referenced by expand_skeyid_e().
const chunk_t octet_1 = chunk_from_chars(0x01) static
Definition at line 152 of file keymat_v1.c.
const chunk_t octet_2 = chunk_from_chars(0x02) static
Definition at line 153 of file keymat_v1.c.