strongSwan: ietf_attr_pa_tnc_error.c File Reference
ietf_attr_pa_tnc_error.c File Reference
#include "ietf_attr_pa_tnc_error.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_pa_tnc_error_t
Macros
#define PA_ERROR_HEADER_SIZE 8
#define PA_ERROR_RESERVED 0x00
#define PA_ERROR_MSG_INFO_SIZE 8
#define PA_ERROR_MSG_INFO_MAX_SIZE 1024
#define PA_ERROR_VERSION_RESERVED 0x0000
#define PA_ERROR_ATTR_INFO_SIZE 8
Typedefs
typedef struct
private_ietf_attr_pa_tnc_error_t private_ietf_attr_pa_tnc_error_t
Functions
ENUM (pa_tnc_error_code_names, PA_ERROR_RESERVED, PA_ERROR_ATTR_TYPE_NOT_SUPPORTED,"Reserved","Invalid Parameter","Version Not Supported","Attribute Type Not Supported")
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_pa_tnc_error_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_pa_tnc_error_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_pa_tnc_error_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_pa_tnc_error_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_pa_tnc_error_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_pa_tnc_error_t *this, uint32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_pa_tnc_error_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_pa_tnc_error_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_pa_tnc_error_t *this)
METHOD (ietf_attr_pa_tnc_error_t, get_error_code, pen_type_t, private_ietf_attr_pa_tnc_error_t *this)
METHOD (ietf_attr_pa_tnc_error_t, get_msg_info, chunk_t, private_ietf_attr_pa_tnc_error_t *this)
METHOD (ietf_attr_pa_tnc_error_t, get_unsupported_attr, pen_type_t, private_ietf_attr_pa_tnc_error_t *this, uint8_t *flags)
METHOD (ietf_attr_pa_tnc_error_t, set_unsupported_attr, void, private_ietf_attr_pa_tnc_error_t *this, uint8_t flags, pen_type_t type)
METHOD (ietf_attr_pa_tnc_error_t, get_offset, uint32_t, private_ietf_attr_pa_tnc_error_t *this)
static
private_ietf_attr_pa_tnc_error_t * create_generic ()
pa_tnc_attr_t * ietf_attr_pa_tnc_error_create (pen_type_t error_code, chunk_t msg_info)
pa_tnc_attr_t * ietf_attr_pa_tnc_error_create_with_offset (pen_type_t error_code, chunk_t msg_info, uint32_t error_offset)
pa_tnc_attr_t * ietf_attr_pa_tnc_error_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define PA_ERROR_ATTR_INFO_SIZE 8
"Attribute Type Not Supported" Error Code
                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Flags | PA-TNC Attribute Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PA-TNC Attribute Type | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 98 of file ietf_attr_pa_tnc_error.c.
Referenced by METHOD().
#define PA_ERROR_HEADER_SIZE 8
PA-TNC Error Attribute Type (see section 4.2.8 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Reserved | PA-TNC Error Code Vendor ID | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | PA-TNC Error Code | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Error Information (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 47 of file ietf_attr_pa_tnc_error.c.
Referenced by METHOD().
#define PA_ERROR_MSG_INFO_MAX_SIZE 1024
Definition at line 63 of file ietf_attr_pa_tnc_error.c.
Referenced by ietf_attr_pa_tnc_error_create().
#define PA_ERROR_MSG_INFO_SIZE 8
All IETF Error Types return the first 8 bytes of the erroneous PA-TNC message
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Version | Copy of Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Message Identifier | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 62 of file ietf_attr_pa_tnc_error.c.
Referenced by ietf_attr_pa_tnc_error_create(), ietf_attr_pa_tnc_error_create_with_offset(), and METHOD().
#define PA_ERROR_RESERVED 0x00
Definition at line 48 of file ietf_attr_pa_tnc_error.c.
Referenced by METHOD().
#define PA_ERROR_VERSION_RESERVED 0x0000
"Invalid Parameter" Error Code 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Offset | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ "Version Not Supported" Error Code
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Max Version | Min Version | Reserved | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 84 of file ietf_attr_pa_tnc_error.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_pa_tnc_error_t private_ietf_attr_pa_tnc_error_t
Definition at line 31 of file ietf_attr_pa_tnc_error.c.
Function Documentation
static private_ietf_attr_pa_tnc_error_t* create_generic () static
Generic constructor
Definition at line 361 of file ietf_attr_pa_tnc_error.c.
References IETF_ATTR_PA_TNC_ERROR, INIT, and PEN_IETF.
Referenced by ietf_attr_pa_tnc_error_create(), ietf_attr_pa_tnc_error_create_from_data(), and ietf_attr_pa_tnc_error_create_with_offset().
 {
     private_ietf_attr_pa_tnc_error_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_error_code = _get_error_code,
             .get_msg_info = _get_msg_info,
             .get_unsupported_attr = _get_unsupported_attr,
             .set_unsupported_attr = _set_unsupported_attr,
             .get_offset = _get_offset,
         },
         .type = { PEN_IETF, IETF_ATTR_PA_TNC_ERROR },
         .ref = 1,
     );
     return this;
 }
ENUM (pa_tnc_error_code_names , PA_ERROR_RESERVED , PA_ERROR_ATTR_TYPE_NOT_SUPPORTED , "Reserved" , "Invalid Parameter" , "Version Not Supported" , "Attribute Type Not Supported")
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 161 of file ietf_attr_pa_tnc_error.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 167 of file ietf_attr_pa_tnc_error.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 173 of file ietf_attr_pa_tnc_error.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_pa_tnc_error_t * this, bool noskip)
Definition at line 179 of file ietf_attr_pa_tnc_error.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 185 of file ietf_attr_pa_tnc_error.c.
References bio_writer_create(), bio_writer_t::destroy, error_code, bio_writer_t::extract_buf, flags, length, PA_ERROR_ATTR_TYPE_NOT_SUPPORTED, PA_ERROR_HEADER_SIZE, PA_ERROR_INVALID_PARAMETER, PA_ERROR_MSG_INFO_SIZE, PA_ERROR_RESERVED, PA_ERROR_VERSION_NOT_SUPPORTED, PA_ERROR_VERSION_RESERVED, PA_TNC_VERSION, PEN_IETF, value, bio_writer_t::write_data, bio_writer_t::write_uint16, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(PA_ERROR_HEADER_SIZE + PA_ERROR_MSG_INFO_SIZE);
     writer->write_uint8 (writer, PA_ERROR_RESERVED);
     writer->write_uint24(writer, this->error_code.vendor_id);
     writer->write_uint32(writer, this->error_code.type);
     writer->write_data  (writer, this->msg_info);
     if (this->error_code.vendor_id == PEN_IETF)
     {
         switch (this->error_code.type)
         {
             case PA_ERROR_INVALID_PARAMETER:
                 writer->write_uint32(writer, this->error_offset);
                 break;
             case PA_ERROR_VERSION_NOT_SUPPORTED:
                 writer->write_uint8 (writer, PA_TNC_VERSION);
                 writer->write_uint8 (writer, PA_TNC_VERSION);
                 writer->write_uint16(writer, PA_ERROR_VERSION_RESERVED);
                 break;
             case PA_ERROR_ATTR_TYPE_NOT_SUPPORTED:
                 writer->write_uint8 (writer, this->flags);
                 writer->write_uint24(writer, this->unsupported_type.vendor_id);
                 writer->write_uint32(writer, this->unsupported_type.type);
                 break;
             default:
                 break;
         }
     }
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_pa_tnc_error_t * this, uint32_t * offset)
Definition at line 226 of file ietf_attr_pa_tnc_error.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, error_code, FAILED, flags, NEED_MORE, PA_ERROR_ATTR_INFO_SIZE, PA_ERROR_ATTR_TYPE_NOT_SUPPORTED, PA_ERROR_HEADER_SIZE, PA_ERROR_INVALID_PARAMETER, PA_ERROR_MSG_INFO_SIZE, PEN_IETF, pen_type_create(), bio_reader_t::read_data, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, SUCCESS, type, and value.
 {
     bio_reader_t *reader;
     uint8_t reserved;
     uint32_t vendor_id, type;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < PA_ERROR_HEADER_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for PA-TNC error header");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint8 (reader, &reserved);
     reader->read_uint24(reader, &this->error_code.vendor_id);
     reader->read_uint32(reader, &this->error_code.type);
     if (this->error_code.vendor_id == PEN_IETF)
     {
         if (!reader->read_data(reader, PA_ERROR_MSG_INFO_SIZE, &this->msg_info))
         {
             reader->destroy(reader);
             DBG1(DBG_TNC, "insufficient data for IETF error information");
             *offset = PA_ERROR_HEADER_SIZE;
             return FAILED;
         }
         this->msg_info = chunk_clone(this->msg_info);
         switch (this->error_code.type)
         {
             case PA_ERROR_INVALID_PARAMETER:
                 if (!reader->read_uint32(reader, &this->error_offset))
                 {
                     reader->destroy(reader);
                     DBG1(DBG_TNC, "insufficient data for error offset field");
                     *offset = PA_ERROR_HEADER_SIZE + PA_ERROR_MSG_INFO_SIZE;
                     return FAILED;
                 }
                 break;
             case PA_ERROR_ATTR_TYPE_NOT_SUPPORTED:
                 if (reader->remaining(reader) < PA_ERROR_ATTR_INFO_SIZE)
                 {
                     reader->destroy(reader);
                     DBG1(DBG_TNC, "insufficient data for unsupported attribute "
                                   "information");
                     *offset = PA_ERROR_HEADER_SIZE + PA_ERROR_MSG_INFO_SIZE;
                     return FAILED;
                 }
                 reader->read_uint8 (reader, &this->flags);
                 reader->read_uint24(reader, &vendor_id);
                 reader->read_uint32(reader, &type);
                 this->unsupported_type = pen_type_create(vendor_id, type);
                 break;
             default:
                 break;
         }
     }
     else
     {
         reader->read_data(reader, reader->remaining(reader), &this->msg_info);
         this->msg_info = chunk_clone(this->msg_info);
     }
     reader->destroy(reader);
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_pa_tnc_error_t * this, chunk_t segment)
Definition at line 299 of file ietf_attr_pa_tnc_error.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 305 of file ietf_attr_pa_tnc_error.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 312 of file ietf_attr_pa_tnc_error.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this->msg_info.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_pa_tnc_error_t , get_error_code , pen_type_t , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 323 of file ietf_attr_pa_tnc_error.c.
References error_code.
 {
     return this->error_code;
 }
METHOD (ietf_attr_pa_tnc_error_t , get_msg_info , chunk_t , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 329 of file ietf_attr_pa_tnc_error.c.
 {
     return this->msg_info;
 }
METHOD (ietf_attr_pa_tnc_error_t , get_unsupported_attr , pen_type_t , private_ietf_attr_pa_tnc_error_t * this, uint8_t * flags)
Definition at line 335 of file ietf_attr_pa_tnc_error.c.
References flags.
 {
     if (flags)
     {
         *flags = this->flags;
     }
     return this->unsupported_type;
 }
METHOD (ietf_attr_pa_tnc_error_t , set_unsupported_attr , void , private_ietf_attr_pa_tnc_error_t * this, uint8_t flags, pen_type_t type)
Definition at line 345 of file ietf_attr_pa_tnc_error.c.
References flags, and type.
 {
     this->flags = flags;
     this->unsupported_type = type;
 }
METHOD (ietf_attr_pa_tnc_error_t , get_offset , uint32_t , private_ietf_attr_pa_tnc_error_t * this)
Definition at line 352 of file ietf_attr_pa_tnc_error.c.
 {
     return this->error_offset;
 }