strongSwan: eap_sim_server
eap_sim_server
eap_sim
Classes
struct eap_sim_server_t
Typedefs
typedef struct eap_sim_server_t eap_sim_server_t
Functions
eap_sim_server_t * eap_sim_server_create (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_sim_server_t eap_sim_server_t
Definition at line 26 of file eap_sim_server.h.
Function Documentation
eap_sim_server_t* eap_sim_server_create (identification_t * server, identification_t * peer)
Creates the EAP method EAP-SIM acting as server.
Parameters
server ID of the EAP server
peer ID of the EAP peer
Returns
eap_sim_t object
Definition at line 606 of file eap_sim_server.c.
References identification_t::clone, EAP_SIM, free(), library_t::get, settings_t::get_bool, identifier, INIT, lib, library_t::ns, random, library_t::settings, simaka_crypto_create(), and TRUE.
Referenced by METHOD().
 {
     private_eap_sim_server_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .destroy = _destroy,
             },
         },
         .crypto = simaka_crypto_create(EAP_SIM),
         .mgr = lib->get(lib, "sim-manager"),
     );
     if (!this->crypto)
     {
         free(this);
         return NULL;
     }
     this->permanent = peer->clone(peer);
     this->use_reauth = this->use_pseudonym = this->use_permanent =
         lib->settings->get_bool(lib->settings,
                                 "%s.plugins.eap-sim.request_identity", TRUE,
                                 lib->ns);
     /* generate a non-zero identifier */
     do {
         this->identifier = random();
     } while (!this->identifier);
     return &this->public;
 }