strongSwan: lexparser
lexparser
utils
Functions
bool eat_whitespace (chunk_t *src)
bool match (const char *pattern, const chunk_t *ch)
bool extract_token (chunk_t *token, const char termination, chunk_t *src)
bool extract_token_str (chunk_t *token, const char *termination, chunk_t *src)
bool fetchline (chunk_t *src, chunk_t *line)
err_t extract_value (chunk_t *value, chunk_t *line)
err_t extract_name_value (chunk_t *name, chunk_t *value, chunk_t *line)
err_t extract_parameter_value (chunk_t *name, chunk_t *value, chunk_t *line)
Detailed Description
Function Documentation
bool eat_whitespace (chunk_t * src)
Eats whitespace
eat whitespace
Definition at line 20 of file lexparser.c.
References chunk_t::len, and chunk_t::ptr.
Referenced by do_netstat(), extract_secret(), extract_value(), get_port_list(), load_from_file(), load_imcvs_from_config(), load_pin(), load_secrets(), METHOD(), pem_to_bin(), and process_header().
 {
     while (src->len > 0 && (*src->ptr == ' ' || *src->ptr == '\t'))
     {
         src->ptr++;  src->len--;
     }
     return  src->len > 0 && *src->ptr != '#';
 }
err_t extract_name_value (chunk_t * name, chunk_t * value, chunk_t * line)
extracts a name: value pair from a text line
err_t extract_parameter_value (chunk_t * name, chunk_t * value, chunk_t * line)
extracts a parameter: value from a text line
extracts a parameter: value pair
Definition at line 152 of file lexparser.c.
References extract_token(), and extract_value().
Referenced by pem_to_bin().
 {
     /* extract name */
     if (!extract_token(name,':', line))
     {
         return "missing ':'";
     }
     /* extract value */
     return extract_value(value, line);
 }
bool extract_token (chunk_t * token, const char termination, chunk_t * src)
Extracts a token ending with the first occurrence of a given termination symbol
extracts a token ending with the first occurrence of a given termination symbol
Definition at line 40 of file lexparser.c.
References chunk_empty, FALSE, chunk_t::len, chunk_t::ptr, and TRUE.
Referenced by do_netstat(), extract_parameter_value(), extract_secret(), extract_value(), fetchline(), get_port_list(), load_imcvs_from_config(), load_secrets(), METHOD(), pem_to_bin(), and process_header().
 {
     u_char *eot = memchr(src->ptr, termination, src->len);
     if (termination == ' ')
     {
         u_char *eot_tab = memchr(src->ptr, '\t', src->len);
         /* check if a tab instead of a space terminates the token */
         eot = ( eot_tab == NULL || (eot && eot < eot_tab) ) ? eot : eot_tab;
     }
     /* initialize empty token */
     *token = chunk_empty;
     if (eot == NULL) /* termination symbol not found */
     {
         return FALSE;
     }
     /* extract token */
     token->ptr = src->ptr;
     token->len = (u_int)(eot - src->ptr);
     /* advance src pointer after termination symbol */
     src->ptr = eot + 1;
     src->len -= (token->len + 1);
     return TRUE;
 }
bool extract_token_str (chunk_t * token, const char * termination, chunk_t * src)
Extracts a token ending with the first occurrence of a given null-terminated string
extracts a token ending with the first occurrence of a given null-terminated string
Definition at line 74 of file lexparser.c.
References chunk_empty, FALSE, chunk_t::len, memstr(), chunk_t::ptr, and TRUE.
Referenced by load_secrets().
 {
     u_char *eot = memstr(src->ptr, termination, src->len);
     size_t l = strlen(termination);
     /* initialize empty token */
     *token = chunk_empty;
     if (eot == NULL) /* termination string not found */
     {
         return FALSE;
     }
     /* extract token */
     token->ptr = src->ptr;
     token->len = (u_int)(eot - src->ptr);
     /* advance src pointer after termination string */
     src->ptr = eot + l;
     src->len -= (token->len + l);
     return TRUE;
 }
err_t extract_value (chunk_t * value, chunk_t * line)
Extracts a value that might be single or double quoted
Definition at line 120 of file lexparser.c.
References chunk_empty, eat_whitespace(), extract_token(), chunk_t::len, and chunk_t::ptr.
Referenced by extract_parameter_value(), load_from_file(), load_pin(), and load_shared().
 {
     char delimiter = ' ';
     if (!eat_whitespace(line))
     {
         *value = chunk_empty;
         return NULL;
     }
     if (*line->ptr == '\'' || *line->ptr == '"')
     {
         delimiter = *line->ptr;
         line->ptr++;  line->len--;
     }
     if (!extract_token(value, delimiter, line))
     {
         if (delimiter == ' ')
         {
             *value = *line;
             line->len = 0;
         }
         else
         {
             return "missing second delimiter";
         }
     }
     return NULL;
 }
bool fetchline (chunk_t * src, chunk_t * line)
Fetches a new text line terminated by \n or \r\n
fetches a new line terminated by
or
Definition at line 101 of file lexparser.c.
References extract_token(), FALSE, chunk_t::len, chunk_t::ptr, src, and TRUE.
Referenced by decode_base64(), load_imcvs_from_config(), load_secrets(), METHOD(), pem_to_bin(), and process_header().
 {
     if (src->len == 0) /* end of src reached */
         return FALSE;
     if (extract_token(line, '\n', src))
     {
         if (line->len > 0 && *(line->ptr + line->len -1) == '\r')
             line->len--;  /* remove optional \r */
     }
     else /*last line ends without newline */
     {
         *line = *src;
         src->ptr += src->len;
         src->len = 0;
     }
     return TRUE;
 }
bool match (const char * pattern, const chunk_t * ch)
Compare null-terminated pattern with chunk
compare string with chunk
Definition at line 32 of file lexparser.c.
References chunk_t::len, and chunk_t::ptr.
 {
     return ch->len == strlen(pattern) && strncmp(pattern, ch->ptr, ch->len) == 0;
 }