strongSwan: processor_t Struct Reference
processor_t Struct Reference
processor
#include "processor.h"
Public Attributes
u_int(* get_total_threads)(processor_t *this)
u_int(* get_idle_threads)(processor_t *this)
u_int(* get_working_threads)(processor_t *this, job_priority_t prio)
u_int(* get_job_load)(processor_t *this, job_priority_t prio)
void(* queue_job)(processor_t *this, job_t *job)
void(* execute_job)(processor_t *this, job_t *job)
void(* set_threads)(processor_t *this, u_int count)
void(* cancel)(processor_t *this)
void(* destroy)(processor_t *processor)
Detailed Description
The processor uses threads to process queued jobs.
Definition at line 38 of file processor.h.
Member Data Documentation
void(* processor_t::cancel)(processor_t *this)
Sets the number of threads to 0 and cancels all blocking jobs, then waits for all threads to be terminated.
Definition at line 106 of file processor.h.
Referenced by cleanup(), destroy(), START_TEST(), test_runner_init(), and vici_deinit().
void(* processor_t::destroy)(processor_t *processor)
Destroy a processor object.
Definition at line 111 of file processor.h.
void(* processor_t::execute_job)(processor_t *this, job_t *job)
Directly execute a job with an idle worker thread.
If no idle thread is available, the job gets executed by the calling thread.
Parameters
job job, gets destroyed
Definition at line 87 of file processor.h.
Referenced by watch().
u_int(* processor_t::get_idle_threads)(processor_t *this)
Get the number of threads currently waiting for work.
Returns
number of idle threads
Definition at line 52 of file processor.h.
Referenced by CALLBACK(), and METHOD().
u_int(* processor_t::get_job_load)(processor_t *this, job_priority_t prio)
Get the number of queued jobs for a specified priority.
Parameters
prio priority class to get job load for
Returns
number of items in queue
Definition at line 68 of file processor.h.
Referenced by CALLBACK(), drop_ike_sa_init(), and METHOD().
u_int(* processor_t::get_total_threads)(processor_t *this)
Get the total number of threads used by the processor.
Returns
size of thread pool
Definition at line 45 of file processor.h.
Referenced by CALLBACK(), METHOD(), and vici_init().
u_int(* processor_t::get_working_threads)(processor_t *this, job_priority_t prio)
Get the number of threads currently working, per priority class.
Parameters
priority to check
Returns
number of threads in priority working
Definition at line 60 of file processor.h.
Referenced by CALLBACK(), and METHOD().
void(* processor_t::queue_job)(processor_t *this, job_t *job)
Adds a job to the queue.
This function is non blocking and adds a job_t to the queue.
Parameters
job job to add to the queue
Definition at line 77 of file processor.h.
Referenced by add_exclude(), CALLBACK(), check_systime(), cmd_connection_create(), delete_all_async(), disconnect(), dispatch(), eap_radius_handle_timeout(), establish_new(), finish_checks(), ha_ctl_create(), ha_dispatcher_create(), handle_fragment(), ipsec_event_relay_create(), ipsec_processor_create(), kernel_libipsec_router_create(), keychain_creds_create(), liveness(), maemo_service_create(), METHOD(), nm_backend_init(), pkcs11_manager_create(), process_disconnect(), process_ike_update(), queue_messsage(), receive_packets(), receiver_create(), register_load_tester(), rekey_child(), rekey_ike(), schedule(), schedule_autoinit(), scheduler_create(), sender_create(), smp_plugin_create(), start_echo_server(), start_heartbeat(), start_watchdog(), uci_control_create(), wait_for_listener(), and watch().
void(* processor_t::set_threads)(processor_t *this, u_int count)
Set the number of threads to use in the processor.
If the number of threads is smaller than number of currently running threads, thread count is decreased. Use 0 to disable the processor.
This call does not block and wait for threads to terminate if the number of threads is reduced. Instead use cancel() for that during shutdown.
Parameters
count number of threads to allocate
Definition at line 100 of file processor.h.
Referenced by destroy(), main(), METHOD(), start_echo_server(), START_TEST(), test_runner_init(), and vici_init().
The documentation for this struct was generated from the following file:
processor.h