strongSwan: stream_service_unix
stream_service_unix
stream
Functions
stream_service_t * stream_service_create_unix (char *uri, int backlog)
stream_service_t * stream_service_create_tcp (char *uri, int backlog)
Detailed Description
Function Documentation
stream_service_t* stream_service_create_tcp (char * uri, int backlog)
Create a service instance for TCP sockets.
Parameters
uri TCP socket specific URI, must start with "tcp://"
backlog size of the backlog queue, as passed to listen()
Returns
stream_service instance, NULL on failure
See header
Definition at line 26 of file stream_service_tcp.c.
References addr, bind, close, DBG1, DBG_NET, len, setsockopt, socket, stream_parse_uri_tcp(), stream_service_create_from_fd(), and strerror.
Referenced by METHOD(), and stream_manager_create().
 {
     union {
         struct sockaddr_in in;
         struct sockaddr_in6 in6;
         struct sockaddr sa;
     } addr;
     int fd, len, on = 1;
     len = stream_parse_uri_tcp(uri, &addr.sa);
     if (len == -1)
     {
         DBG1(DBG_NET, "invalid stream URI: '%s'", uri);
         return NULL;
     }
     fd = socket(addr.sa.sa_family, SOCK_STREAM, 0);
     if (fd < 0)
     {
         DBG1(DBG_NET, "opening socket '%s' failed: %s", uri, strerror(errno));
         return NULL;
     }
     if (setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (void*)&on, sizeof(on)) != 0)
     {
         DBG1(DBG_NET, "SO_REUSADDR on '%s' failed: %s", uri, strerror(errno));
     }
     if (bind(fd, &addr.sa, len) < 0)
     {
         DBG1(DBG_NET, "binding socket '%s' failed: %s", uri, strerror(errno));
         close(fd);
         return NULL;
     }
     if (listen(fd, backlog) < 0)
     {
         DBG1(DBG_NET, "listen on socket '%s' failed: %s", uri, strerror(errno));
         close(fd);
         return NULL;
     }
     return stream_service_create_from_fd(fd);
 }
stream_service_t* stream_service_create_unix (char * uri, int backlog)
Create a service instance for UNIX sockets.
Parameters
uri UNIX socket specific URI, must start with "unix://"
backlog size of the backlog queue, as passed to listen()
Returns
stream_service instance, NULL on failure
See header
Definition at line 28 of file stream_service_unix.c.
References bind, CAP_CHOWN, library_t::caps, capabilities_t::check, close, DBG1, DBG_NET, capabilities_t::get_gid, capabilities_t::get_uid, len, lib, socket, stream_parse_uri_unix(), stream_service_create_from_fd(), and strerror.
Referenced by METHOD(), and stream_manager_create().
 {
     struct sockaddr_un addr;
     mode_t old;
     int fd, len;
     len = stream_parse_uri_unix(uri, &addr);
     if (len == -1)
     {
         DBG1(DBG_NET, "invalid stream URI: '%s'", uri);
         return NULL;
     }
     if (!lib->caps->check(lib->caps, CAP_CHOWN))
     {   /* required to chown(2) service socket */
         DBG1(DBG_NET, "socket '%s' requires CAP_CHOWN capability", uri);
         return NULL;
     }
     fd = socket(AF_UNIX, SOCK_STREAM, 0);
     if (fd == -1)
     {
         DBG1(DBG_NET, "opening socket '%s' failed: %s", uri, strerror(errno));
         return NULL;
     }
     unlink(addr.sun_path);
     old = umask(S_IRWXO);
     if (bind(fd, (struct sockaddr*)&addr, len) < 0)
     {
         DBG1(DBG_NET, "binding socket '%s' failed: %s", uri, strerror(errno));
         close(fd);
         return NULL;
     }
     umask(old);
     if (chown(addr.sun_path, lib->caps->get_uid(lib->caps),
               lib->caps->get_gid(lib->caps)) != 0)
     {
         DBG1(DBG_NET, "changing socket permissions for '%s' failed: %s",
              uri, strerror(errno));
     }
     if (listen(fd, backlog) < 0)
     {
         DBG1(DBG_NET, "listen on socket '%s' failed: %s", uri, strerror(errno));
         unlink(addr.sun_path);
         close(fd);
         return NULL;
     }
     return stream_service_create_from_fd(fd);
 }