strongSwan: pub.c File Reference
pub.c File Reference
#include <errno.h>
#include "pki.h"
#include <credentials/certificates/certificate.h>
#include <credentials/certificates/x509.h>
Functions
static int pub ()
static void __attribute__ ((constructor))
Function Documentation
static void __attribute__ ((constructor)) static
Register the command.
Definition at line 187 of file pub.c.
References command_register(), and pub().
 {
     command_register((command_t) {
         pub, 'p', "pub",
         "extract the public key from a private key/certificate",
         {"[--in file|--keyid hex] [--type rsa|ecdsa|bliss|pub|pkcs10|x509]",
          "[--outform der|pem|dnskey|sshkey]"},
         {
             {"help",    'h', 0, "show usage information"},
             {"in",      'i', 1, "input file, default: stdin"},
             {"keyid",   'x', 1, "keyid on smartcard of private key"},
             {"type",    't', 1, "type of credential, default: rsa"},
             {"outform", 'f', 1, "encoding of extracted public key, default: der"},
         }
     });
 }
static int pub () static
Extract a public key from a private key/certificate
Definition at line 27 of file pub.c.
References BUILD_BLOB, BUILD_END, BUILD_FROM_FILE, BUILD_PKCS11_KEYID, cert, CERT_ASN1_DER, CERT_PKCS10_REQUEST, CERT_X509, chunk_create(), chunk_from_fd(), chunk_from_hex(), command_getopt(), command_usage(), credential_factory_t::create, CRED_CERTIFICATE, CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, library_t::creds, certificate_t::destroy, encoding, fprintf, free(), get_form(), certificate_t::get_public_key, KEY_ANY, KEY_BLISS, KEY_ECDSA, KEY_RSA, keyid(), chunk_t::len, lib, chunk_t::ptr, PUBKEY_SPKI_ASN1_DER, public, set_file_mode(), streq(), strerror, subtype, TRUE, and type.
Referenced by __attribute__(), bench_dh(), ha_diffie_hellman_create(), METHOD(), process_ec_key_exchange(), process_key_exchange_dhe(), process_modp_key_exchange(), and send_key_exchange_dhe().
 {
     cred_encoding_type_t form = PUBKEY_SPKI_ASN1_DER;
     credential_type_t type = CRED_PRIVATE_KEY;
     int subtype = KEY_RSA;
     certificate_t *cert;
     private_key_t *private;
     public_key_t *public;
     chunk_t encoding;
     char *file = NULL, *keyid = NULL;
     void *cred;
     char *arg;
     while (TRUE)
     {
         switch (command_getopt(&arg))
         {
             case 'h':
                 return command_usage(NULL);
             case 't':
                 if (streq(arg, "rsa"))
                 {
                     type = CRED_PRIVATE_KEY;
                     subtype = KEY_RSA;
                 }
                 else if (streq(arg, "ecdsa"))
                 {
                     type = CRED_PRIVATE_KEY;
                     subtype = KEY_ECDSA;
                 }
                 else if (streq(arg, "bliss"))
                 {
                     type = CRED_PRIVATE_KEY;
                     subtype = KEY_BLISS;
                 }
                 else if (streq(arg, "pub"))
                 {
                     type = CRED_PUBLIC_KEY;
                     subtype = KEY_ANY;
                 }
                 else if (streq(arg, "pkcs10"))
                 {
                     type = CRED_CERTIFICATE;
                     subtype = CERT_PKCS10_REQUEST;
                 }
                 else if (streq(arg, "x509"))
                 {
                     type = CRED_CERTIFICATE;
                     subtype = CERT_X509;
                 }
                 else
                 {
                     return command_usage("invalid input type");
                 }
                 continue;
             case 'f':
                 if (!get_form(arg, &form, CRED_PUBLIC_KEY))
                 {
                     return command_usage("invalid output format");
                 }
                 continue;
             case 'i':
                 file = arg;
                 continue;
             case 'x':
                 keyid = arg;
                 continue;
             case EOF:
                 break;
             default:
                 return command_usage("invalid --pub option");
         }
         break;
     }
     if (file)
     {
         cred = lib->creds->create(lib->creds, type, subtype,
                                      BUILD_FROM_FILE, file, BUILD_END);
     }
     else if (keyid)
     {
         chunk_t chunk;
         chunk = chunk_from_hex(chunk_create(keyid, strlen(keyid)), NULL);
         cred = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_ANY,
                                   BUILD_PKCS11_KEYID, chunk, BUILD_END);
         free(chunk.ptr);
     }
     else
     {
         chunk_t chunk;
         set_file_mode(stdin, CERT_ASN1_DER);
         if (!chunk_from_fd(0, &chunk))
         {
             fprintf(stderr, "reading input failed: %s\n", strerror(errno));
             return 1;
         }
         cred = lib->creds->create(lib->creds, type, subtype,
                                   BUILD_BLOB, chunk, BUILD_END);
         free(chunk.ptr);
     }
     if (type == CRED_PRIVATE_KEY)
     {
         private = cred;
         if (!private)
         {
             fprintf(stderr, "parsing private key failed\n");
             return 1;
         }
         public = private->get_public_key(private);
         private->destroy(private);
     }
     else if (type == CRED_PUBLIC_KEY)
     {
         public = cred;
         if (!public)
         {
             fprintf(stderr, "parsing public key failed\n");
             return 1;
         }
     }
     else
     {
         cert = cred;
         if (!cert)
         {
             fprintf(stderr, "parsing certificate failed\n");
             return 1;
         }
         public = cert->get_public_key(cert);
         cert->destroy(cert);
     }
     if (!public)
     {
         fprintf(stderr, "extracting public key failed\n");
         return 1;
     }
     if (!public->get_encoding(public, form, &encoding))
     {
         fprintf(stderr, "public key encoding failed\n");
         public->destroy(public);
         return 1;
     }
     public->destroy(public);
     set_file_mode(stdout, form);
     if (fwrite(encoding.ptr, encoding.len, 1, stdout) != 1)
     {
         fprintf(stderr, "writing public key failed\n");
         free(encoding.ptr);
         return 1;
     }
     free(encoding.ptr);
     return 0;
 }