strongSwan: test_bliss_signature.c File Reference
test_bliss_signature.c File Reference
#include "test_suite.h"
#include <bliss_signature.h>
Functions
START_TEST (test_bliss_signature_fail)
END_TEST Suite * bliss_signature_suite_create ()
Variables
static chunk_t data
Function Documentation
END_TEST Suite* bliss_signature_suite_create ()
Definition at line 129 of file test_bliss_signature.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("bliss_signature");
     tc = tcase_create("signature_fail");
     tcase_add_test(tc, test_bliss_signature_fail);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_bliss_signature_fail)
Definition at line 96 of file test_bliss_signature.c.
References BLISS_B_I, BLISS_B_II, bliss_param_set_get_by_id(), bliss_signature_create(), bliss_signature_create_from_data(), ck_assert, bliss_signature_t::destroy, encoding, bliss_signature_t::get_encoding, bliss_param_set_t::id, chunk_t::len, and chunk_t::ptr.
 {
     bliss_param_set_t set2 = { .id = BLISS_B_II };
     bliss_param_set_t *set;
     bliss_signature_t *signature;
     chunk_t encoding;
     int k;
     signature = bliss_signature_create(&set2);
     ck_assert(signature);
     encoding = signature->get_encoding(signature);
     ck_assert(encoding.len == 0);
     signature->destroy(signature);
     signature  = bliss_signature_create_from_data(&set2, data);
     ck_assert(!signature);
     set = bliss_param_set_get_by_id(BLISS_B_I);
     ck_assert(set);
     for (k = 0; k < data.len - 2; k++)
     {
         chunk_t fragment = { data.ptr, k };
         signature  = bliss_signature_create_from_data(set, fragment);
         ck_assert(!signature);
     }
     signature  = bliss_signature_create_from_data(set, data);
     ck_assert(signature);
     signature->destroy(signature);
 }
Variable Documentation
chunk_t data static
Definition at line 20 of file test_bliss_signature.c.