strongSwan: cert_payload
cert_payload
payloads
Classes
struct cert_payload_t
Typedefs
typedef struct cert_payload_t cert_payload_t
typedef enum cert_encoding_t cert_encoding_t
Enumerations
enum cert_encoding_t {
ENC_PKCS7_WRAPPED_X509 = 1, ENC_PGP = 2, ENC_DNS_SIGNED_KEY = 3, ENC_X509_SIGNATURE = 4,
ENC_KERBEROS_TOKEN = 6, ENC_CRL = 7, ENC_ARL = 8, ENC_SPKI = 9,
ENC_X509_ATTRIBUTE = 10, ENC_RAW_RSA_KEY = 11, ENC_X509_HASH_AND_URL = 12, ENC_X509_HASH_AND_URL_BUNDLE = 13,
ENC_OCSP_CONTENT = 14
}
Functions
cert_payload_t * cert_payload_create (payload_type_t type)
cert_payload_t * cert_payload_create_from_cert (payload_type_t type, certificate_t *cert)
cert_payload_t * cert_payload_create_from_hash_and_url (chunk_t hash, char *url)
cert_payload_t * cert_payload_create_custom (payload_type_t type, cert_encoding_t encoding, chunk_t data)
Variables
enum_name_t * cert_encoding_names
Detailed Description
Typedef Documentation
typedef enum cert_encoding_t cert_encoding_t
Definition at line 27 of file cert_payload.h.
typedef struct cert_payload_t cert_payload_t
Definition at line 26 of file cert_payload.h.
Enumeration Type Documentation
enum cert_encoding_t
Certificate encodings, as in RFC4306
Enumerator
ENC_PKCS7_WRAPPED_X509
ENC_PGP
ENC_DNS_SIGNED_KEY
ENC_X509_SIGNATURE
ENC_KERBEROS_TOKEN
ENC_CRL
ENC_ARL
ENC_SPKI
ENC_X509_ATTRIBUTE
ENC_RAW_RSA_KEY
ENC_X509_HASH_AND_URL
ENC_X509_HASH_AND_URL_BUNDLE
ENC_OCSP_CONTENT
Definition at line 37 of file cert_payload.h.
                      {
     ENC_PKCS7_WRAPPED_X509 =         1,
     ENC_PGP =                        2,
     ENC_DNS_SIGNED_KEY =             3,
     ENC_X509_SIGNATURE =             4,
     ENC_KERBEROS_TOKEN  =            6,
     ENC_CRL =                        7,
     ENC_ARL =                        8,
     ENC_SPKI =                       9,
     ENC_X509_ATTRIBUTE =            10,
     ENC_RAW_RSA_KEY =               11,
     ENC_X509_HASH_AND_URL =         12,
     ENC_X509_HASH_AND_URL_BUNDLE =  13,
     ENC_OCSP_CONTENT =              14,  /* from RFC 4806 */
 };
Function Documentation
cert_payload_t* cert_payload_create (payload_type_t type)
Creates an empty certificate payload.
Parameters
type payload type (for IKEv1 or IKEv2)
Returns
cert_payload_t object
Definition at line 295 of file cert_payload.c.
References INIT, PL_NONE, and type.
Referenced by cert_payload_create_custom(), cert_payload_create_from_cert(), cert_payload_create_from_hash_and_url(), and payload_create().
 {
     private_cert_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_cert = _get_cert,
             .get_container = _get_container,
             .get_cert_encoding = _get_cert_encoding,
             .get_hash = _get_hash,
             .get_url = _get_url,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
         .type = type,
     );
     return &this->public;
 }
cert_payload_t* cert_payload_create_custom (payload_type_t type, cert_encoding_t encoding, chunk_t data)
Creates a custom certificate payload using type and associated data.
Parameters
type payload type (for IKEv1 or IKEv2)
encoding encoding type of certificate
data associated data (gets owned)
Returns
cert_payload_t object
Definition at line 377 of file cert_payload.c.
References cert_payload_create(), data, encoding, and chunk_t::len.
Referenced by METHOD().
 {
     private_cert_payload_t *this;
     this = (private_cert_payload_t*)cert_payload_create(type);
     this->encoding = encoding;
     this->data = data;
     this->payload_length = get_header_length(this) + this->data.len;
     return &this->public;
 }
cert_payload_t* cert_payload_create_from_cert (payload_type_t type, certificate_t * cert)
Creates a certificate payload with an embedded certificate.
Parameters
type payload type (for IKEv1 or IKEv2)
cert certificate to embed
Returns
cert_payload_t object
Definition at line 328 of file cert_payload.c.
References CERT_ASN1_DER, cert_payload_create(), CERT_X509, CERT_X509_AC, certificate_type_names, data, DBG1, DBG_ENC, ENC_X509_ATTRIBUTE, ENC_X509_SIGNATURE, encoding, free(), certificate_t::get_encoding, and certificate_t::get_type.
Referenced by add_attribute_certs(), add_im_certs(), build_cert_payload(), and build_certs().
 {
     private_cert_payload_t *this;
     this = (private_cert_payload_t*)cert_payload_create(type);
     switch (cert->get_type(cert))
     {
         case CERT_X509:
             this->encoding = ENC_X509_SIGNATURE;
             break;
         case CERT_X509_AC:
             this->encoding = ENC_X509_ATTRIBUTE;
             break;
         default:
             DBG1(DBG_ENC, "embedding %N certificate in payload failed",
                  certificate_type_names, cert->get_type(cert));
             free(this);
             return NULL;
     }
     if (!cert->get_encoding(cert, CERT_ASN1_DER, &this->data))
     {
         DBG1(DBG_ENC, "encoding certificate for cert payload failed");
         free(this);
         return NULL;
     }
     this->payload_length = get_header_length(this) + this->data.len;
     return &this->public;
 }
cert_payload_t* cert_payload_create_from_hash_and_url (chunk_t hash, char * url)
Creates an IKEv2 certificate payload with hash and URL encoding.
Parameters
hash hash of the DER encoded certificate (get's cloned)
url URL to the certificate
Returns
cert_payload_t object
Definition at line 362 of file cert_payload.c.
References cert_payload_create(), chunk_cat, chunk_create(), data, ENC_X509_HASH_AND_URL, encoding, and PLV2_CERTIFICATE.
Referenced by build_cert_payload().
 {
     private_cert_payload_t *this;
     this = (private_cert_payload_t*)cert_payload_create(PLV2_CERTIFICATE);
     this->encoding = ENC_X509_HASH_AND_URL;
     this->data = chunk_cat("cc", hash, chunk_create(url, strlen(url)));
     this->payload_length = get_header_length(this) + this->data.len;
     return &this->public;
 }
Variable Documentation
enum_name_t* cert_encoding_names
Enum names for cert_encoding_t
Referenced by process_certs().