strongSwan: thread.c File Reference
thread.c File Reference
#include <pthread.h>
#include <signal.h>
#include <library.h>
#include <utils/debug.h>
#include <threading/thread_value.h>
#include <threading/mutex.h>
#include <collections/linked_list.h>
#include "thread.h"
Classes
struct private_thread_t
struct cleanup_handler_t
Macros
#define _GNU_SOURCE
#define SIG_CANCEL (SIGRTMIN+7)
Typedefs
typedef struct private_thread_t private_thread_t
Functions
static void cancel_signal_handler (int sig)
static void thread_destroy (private_thread_t *this)
METHOD (thread_t, cancel, void, private_thread_t *this)
METHOD (thread_t, kill_, void, private_thread_t *this, int sig)
METHOD (thread_t, detach, void, private_thread_t *this)
METHOD (thread_t, join, void *, private_thread_t *this)
static private_thread_t * thread_create_internal ()
static void thread_cleanup (private_thread_t *this)
static void * thread_main (private_thread_t *this)
thread_t * thread_create (thread_main_t main, void *arg)
thread_t * thread_current ()
u_int thread_current_id ()
void thread_cleanup_push (thread_cleanup_t cleanup, void *arg)
void thread_cleanup_pop (bool execute)
void thread_cleanup_popall ()
bool thread_cancelability (bool enable)
void thread_cancellation_point ()
void thread_exit (void *val)
void threads_init ()
void threads_deinit ()
Variables
static u_int next_id
static mutex_t * id_mutex
static thread_value_t * current_thread
static thread_value_t * dummy1
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 16 of file thread.c.
#define SIG_CANCEL (SIGRTMIN+7)
Definition at line 129 of file thread.c.
Referenced by METHOD(), thread_cancelability(), and threads_init().
Typedef Documentation
typedef struct private_thread_t private_thread_t
Definition at line 42 of file thread.c.
Function Documentation
static void cancel_signal_handler (int sig) static
Definition at line 134 of file thread.c.
Referenced by threads_init().
 {
     pthread_exit(NULL);
 }
METHOD (thread_t , cancel , void , private_thread_t * this)
Definition at line 160 of file thread.c.
References DBG1, DBG_LIB, mutex_t::lock, mutex, SIG_CANCEL, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     if (pthread_equal(this->thread_id, pthread_self()))
     {
         this->mutex->unlock(this->mutex);
         DBG1(DBG_LIB, "!!! CANNOT CANCEL CURRENT THREAD !!!");
         return;
     }
 #ifdef HAVE_PTHREAD_CANCEL
     pthread_cancel(this->thread_id);
 #else
     pthread_kill(this->thread_id, SIG_CANCEL);
 #endif /* HAVE_PTHREAD_CANCEL */
     this->mutex->unlock(this->mutex);
 }
METHOD (thread_t , kill_ , void , private_thread_t * this, int sig)
Definition at line 178 of file thread.c.
References DBG1, DBG_LIB, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     if (pthread_equal(this->thread_id, pthread_self()))
     {
         /* it might actually be possible to send a signal to pthread_self (there
          * is an example in raise(3) describing that), the problem is though,
          * that the thread only returns here after the signal handler has
          * returned, so depending on the signal, the lock might not get
          * unlocked. */
         this->mutex->unlock(this->mutex);
         DBG1(DBG_LIB, "!!! CANNOT SEND SIGNAL TO CURRENT THREAD !!!");
         return;
     }
     pthread_kill(this->thread_id, sig);
     this->mutex->unlock(this->mutex);
 }
METHOD (thread_t , detach , void , private_thread_t * this)
Definition at line 197 of file thread.c.
References mutex_t::lock, mutex, thread_destroy(), and TRUE.
 {
     this->mutex->lock(this->mutex);
     pthread_detach(this->thread_id);
     this->detached_or_joined = TRUE;
     thread_destroy(this);
 }
METHOD (thread_t , join , void * , private_thread_t * this)
Definition at line 206 of file thread.c.
References DBG1, DBG_LIB, mutex_t::lock, mutex, thread_destroy(), TRUE, mutex_t::unlock, and val.
 {
     pthread_t thread_id;
     void *val;
     this->mutex->lock(this->mutex);
     if (pthread_equal(this->thread_id, pthread_self()))
     {
         this->mutex->unlock(this->mutex);
         DBG1(DBG_LIB, "!!! CANNOT JOIN CURRENT THREAD !!!");
         return NULL;
     }
     if (this->detached_or_joined)
     {
         this->mutex->unlock(this->mutex);
         DBG1(DBG_LIB, "!!! CANNOT JOIN DETACHED THREAD !!!");
         return NULL;
     }
     thread_id = this->thread_id;
     this->detached_or_joined = TRUE;
     if (this->terminated)
     {
         /* thread has terminated before the call to join */
         thread_destroy(this);
     }
     else
     {
         /* thread_destroy is called when the thread terminates normally */
         this->mutex->unlock(this->mutex);
     }
     pthread_join(thread_id, &val);
     return val;
 }
static void thread_cleanup (private_thread_t * this) static
Main cleanup function for threads.
Definition at line 266 of file thread.c.
References cleanup_handler_t::arg, cleanup_handler_t::cleanup, free(), mutex_t::lock, mutex, SUCCESS, thread_destroy(), and TRUE.
Referenced by thread_main().
 {
     cleanup_handler_t *handler;
     this->mutex->lock(this->mutex);
     while (this->cleanup_handlers->remove_last(this->cleanup_handlers,
                                                (void**)&handler) == SUCCESS)
     {
         handler->cleanup(handler->arg);
         free(handler);
     }
     this->terminated = TRUE;
     thread_destroy(this);
 }
static private_thread_t* thread_create_internal () static
Create an internal thread object.
Definition at line 245 of file thread.c.
References INIT, linked_list_create(), mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by thread_create(), thread_current(), and threads_init().
 {
     private_thread_t *this;
     INIT(this,
         .public = {
             .cancel = _cancel,
             .kill = _kill_,
             .detach = _detach,
             .join = _join,
         },
         .cleanup_handlers = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     return this;
 }
static void thread_destroy (private_thread_t * this) static
Destroy an internal thread object.
Note
The mutex of this thread object has to be locked, it gets unlocked automatically.
Definition at line 147 of file thread.c.
References mutex_t::destroy, free(), mutex, and mutex_t::unlock.
Referenced by METHOD(), thread_cleanup(), thread_create(), and threads_deinit().
 {
     if (!this->terminated || !this->detached_or_joined)
     {
         this->mutex->unlock(this->mutex);
         return;
     }
     this->cleanup_handlers->destroy(this->cleanup_handlers);
     this->mutex->unlock(this->mutex);
     this->mutex->destroy(this->mutex);
     free(this);
 }
static void* thread_main (private_thread_t * this) static
Main function wrapper for threads.
Definition at line 283 of file thread.c.
References DBG2, DBG_LIB, main(), res, thread_value_t::set, thread_cleanup(), and TRUE.
Referenced by thread_create().
 {
     void *res;
     current_thread->set(current_thread, this);
     pthread_cleanup_push((thread_cleanup_t)thread_cleanup, this);
     /* TODO: this is not 100% portable as pthread_t is an opaque type (i.e.
      * could be of any size, or even a struct) */
 #ifdef HAVE_GETTID
     DBG2(DBG_LIB, "created thread %.2d [%u]",
          this->id, gettid());
 #elif defined(WIN32)
     DBG2(DBG_LIB, "created thread %.2d [%p]",
          this->id, this->thread_id.p);
 #else
     DBG2(DBG_LIB, "created thread %.2d [%lx]",
          this->id, (u_long)this->thread_id);
 #endif
     res = this->main(this->arg);
     pthread_cleanup_pop(TRUE);
     return res;
 }
Variable Documentation
thread_value_t* current_thread static
Store the thread object in a thread-specific value.
Definition at line 121 of file thread.c.
thread_value_t* dummy1 static
A dummy thread value that reserved pthread_key_t value "0". A buggy PKCS#11 library mangles this key, without owning it, so we allocate it for them.
Definition at line 467 of file thread.c.
mutex_t* id_mutex static
Mutex to safely access the next thread ID.
Definition at line 116 of file thread.c.
Referenced by METHOD().
u_int next_id static
Next thread ID.
Definition at line 111 of file thread.c.
Referenced by thread_create(), thread_current(), and threads_init().