strongSwan: ipsec_policy.c File Reference
ipsec_policy.c File Reference
#include "ipsec_policy.h"
#include <utils/debug.h>
Classes
struct private_ipsec_policy_t
Typedefs
typedef struct
private_ipsec_policy_t private_ipsec_policy_t
Functions
METHOD (ipsec_policy_t, match, bool, private_ipsec_policy_t *this, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t priority)
METHOD (ipsec_policy_t, match_packet, bool, private_ipsec_policy_t *this, ip_packet_t *packet)
METHOD (ipsec_policy_t, get_source_ts, traffic_selector_t *, private_ipsec_policy_t *this)
METHOD (ipsec_policy_t, get_destination_ts, traffic_selector_t *, private_ipsec_policy_t *this)
METHOD (ipsec_policy_t, get_reqid, u_int32_t, private_ipsec_policy_t *this)
METHOD (ipsec_policy_t, get_direction, policy_dir_t, private_ipsec_policy_t *this)
METHOD (ipsec_policy_t, get_priority, policy_priority_t, private_ipsec_policy_t *this)
METHOD (ipsec_policy_t, get_type, policy_type_t, private_ipsec_policy_t *this)
METHOD (ipsec_policy_t, get_ref, ipsec_policy_t *, private_ipsec_policy_t *this)
METHOD (ipsec_policy_t, destroy, void, private_ipsec_policy_t *this)
ipsec_policy_t * ipsec_policy_create (host_t *src, host_t *dst, traffic_selector_t *src_ts, traffic_selector_t *dst_ts, policy_dir_t direction, policy_type_t type, ipsec_sa_cfg_t *sa, mark_t mark, policy_priority_t priority)
Typedef Documentation
typedef struct private_ipsec_policy_t private_ipsec_policy_t
Definition at line 22 of file ipsec_policy.c.
Function Documentation
METHOD (ipsec_policy_t , match , bool , private_ipsec_policy_t * this, traffic_selector_t * src_ts, traffic_selector_t * dst_ts, policy_dir_t direction, u_int32_t reqid, mark_t mark, policy_priority_t priority)
Definition at line 91 of file ipsec_policy.c.
References traffic_selector_t::equals, memeq(), and sa.
 {
     return (this->direction == direction &&
             this->priority == priority &&
             this->sa.reqid == reqid &&
             memeq(&this->mark, &mark, sizeof(mark_t)) &&
             this->src_ts->equals(this->src_ts, src_ts) &&
             this->dst_ts->equals(this->dst_ts, dst_ts));
 }
METHOD (ipsec_policy_t , match_packet , bool , private_ipsec_policy_t * this, ip_packet_t * packet)
Definition at line 104 of file ipsec_policy.c.
References dst, ip_packet_t::get_destination, ip_packet_t::get_next_header, ip_packet_t::get_source, proto, protocol, and src.
 {
     u_int8_t proto = packet->get_next_header(packet);
     host_t *src = packet->get_source(packet),
            *dst = packet->get_destination(packet);
     return (!this->protocol || this->protocol == proto) &&
            this->src_ts->includes(this->src_ts, src) &&
            this->dst_ts->includes(this->dst_ts, dst);
 }
METHOD (ipsec_policy_t , get_source_ts , traffic_selector_t * , private_ipsec_policy_t * this)
Definition at line 116 of file ipsec_policy.c.
 {
     return this->src_ts;
 }
METHOD (ipsec_policy_t , get_destination_ts , traffic_selector_t * , private_ipsec_policy_t * this)
Definition at line 122 of file ipsec_policy.c.
 {
     return this->dst_ts;
 }
METHOD (ipsec_policy_t , get_reqid , u_int32_t , private_ipsec_policy_t * this)
Definition at line 128 of file ipsec_policy.c.
References sa.
 {
     return this->sa.reqid;
 }
METHOD (ipsec_policy_t , get_direction , policy_dir_t , private_ipsec_policy_t * this)
Definition at line 134 of file ipsec_policy.c.
 {
     return this->direction;
 }
METHOD (ipsec_policy_t , get_priority , policy_priority_t , private_ipsec_policy_t * this)
Definition at line 140 of file ipsec_policy.c.
 {
     return this->priority;
 }
METHOD (ipsec_policy_t , get_type , policy_type_t , private_ipsec_policy_t * this)
Definition at line 146 of file ipsec_policy.c.
References type.
 {
     return this->type;
 }
METHOD (ipsec_policy_t , get_ref , ipsec_policy_t * , private_ipsec_policy_t * this)
Definition at line 152 of file ipsec_policy.c.
References ref_get().
 {
     ref_get(&this->refcount);
     return &this->public;
 }
METHOD (ipsec_policy_t , destroy , void , private_ipsec_policy_t * this)
Definition at line 159 of file ipsec_policy.c.
References dst, free(), ref_put(), and src.
 {
     if (ref_put(&this->refcount))
     {
         this->src->destroy(this->src);
         this->dst->destroy(this->dst);
         this->src_ts->destroy(this->src_ts);
         this->dst_ts->destroy(this->dst_ts);
         free(this);
     }
 }