strongSwan: credential_manager
credential_manager
credentials
Classes
struct credential_manager_t
Typedefs
typedef struct credential_manager_t credential_manager_t
typedef enum credential_hook_type_t credential_hook_type_t
typedef void(* credential_hook_t)(void *data, credential_hook_type_t type, certificate_t *cert)
Enumerations
enum credential_hook_type_t {
CRED_HOOK_EXPIRED, CRED_HOOK_REVOKED, CRED_HOOK_VALIDATION_FAILED, CRED_HOOK_NO_ISSUER,
CRED_HOOK_UNTRUSTED_ROOT, CRED_HOOK_EXCEEDED_PATH_LEN, CRED_HOOK_POLICY_VIOLATION
}
Functions
credential_manager_t * credential_manager_create ()
Detailed Description
Typedef Documentation
typedef void(* credential_hook_t)(void *data, credential_hook_type_t type, certificate_t *cert)
Hook function to invoke on certificate validation errors.
Parameters
data user data supplied during hook registration
type type of validation error/event
cert associated certificate
Definition at line 64 of file credential_manager.h.
typedef enum credential_hook_type_t credential_hook_type_t
Definition at line 25 of file credential_manager.h.
typedef struct credential_manager_t credential_manager_t
Definition at line 24 of file credential_manager.h.
Enumeration Type Documentation
enum credential_hook_type_t
Type of a credential hook error/event.
Enumerator
CRED_HOOK_EXPIRED
The certificate has expired (or is not yet valid)
CRED_HOOK_REVOKED
The certificate has been revoked
CRED_HOOK_VALIDATION_FAILED
Checking certificate revocation failed. This does not necessarily mean the certificate is rejected, just that revocation checking failed.
CRED_HOOK_NO_ISSUER
No trusted issuer certificate has been found for this certificate
CRED_HOOK_UNTRUSTED_ROOT
Encountered a self-signed (root) certificate, but it is not trusted
CRED_HOOK_EXCEEDED_PATH_LEN
Maximum trust chain length exceeded for certificate
CRED_HOOK_POLICY_VIOLATION
The certificate violates some other kind of policy and gets rejected
Definition at line 39 of file credential_manager.h.
{
     CRED_HOOK_EXPIRED,
     CRED_HOOK_REVOKED,
     CRED_HOOK_VALIDATION_FAILED,
     CRED_HOOK_NO_ISSUER,
     CRED_HOOK_UNTRUSTED_ROOT,
     CRED_HOOK_EXCEEDED_PATH_LEN,
     CRED_HOOK_POLICY_VIOLATION,
 };
Function Documentation
credential_manager_t* credential_manager_create ()
Create a credential_manager instance.
Definition at line 1319 of file credential_manager.c.
References cache(), cert_cache_create(), settings_t::get_bool, INIT, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, rwlock_create(), RWLOCK_TYPE_DEFAULT, library_t::settings, thread_value_create(), and TRUE.
Referenced by imv_attestation_agent_create(), and library_init().
 {
     private_credential_manager_t *this;
     INIT(this,
         .public = {
             .create_cert_enumerator = _create_cert_enumerator,
             .create_shared_enumerator = _create_shared_enumerator,
             .create_cdp_enumerator = _create_cdp_enumerator,
             .get_cert = _get_cert,
             .get_shared = _get_shared,
             .get_private = _get_private,
             .create_trusted_enumerator = _create_trusted_enumerator,
             .create_public_enumerator = _create_public_enumerator,
             .flush_cache = _flush_cache,
             .cache_cert = _cache_cert,
             .issued_by = _issued_by,
             .add_set = _add_set,
             .remove_set = _remove_set,
             .add_local_set = _add_local_set,
             .remove_local_set = _remove_local_set,
             .add_validator = _add_validator,
             .remove_validator = _remove_validator,
             .set_hook = _set_hook,
             .call_hook = _call_hook,
             .destroy = _destroy,
         },
         .sets = linked_list_create(),
         .validators = linked_list_create(),
         .cache_queue = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .queue_mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     this->local_sets = thread_value_create((thread_cleanup_t)this->sets->destroy);
     this->exclusive_local_sets = thread_value_create((thread_cleanup_t)this->sets->destroy);
     if (lib->settings->get_bool(lib->settings, "%s.cert_cache", TRUE, lib->ns))
     {
         this->cache = cert_cache_create();
         this->sets->insert_first(this->sets, this->cache);
     }
     return &this->public;
 }