strongSwan: pkcs12
pkcs12
containers | plugins
Modules
pkcs12_decode
pkcs12_plugin
Classes
struct pkcs12_t
Typedefs
typedef enum pkcs12_key_type_t pkcs12_key_type_t
typedef struct pkcs12_t pkcs12_t
Enumerations
enum pkcs12_key_type_t { PKCS12_KEY_ENCRYPTION = 1, PKCS12_KEY_IV = 2, PKCS12_KEY_MAC = 3 }
Functions
bool pkcs12_derive_key (hash_algorithm_t hash, chunk_t password, chunk_t salt, u_int64_t iterations, pkcs12_key_type_t type, chunk_t key)
Detailed Description
Typedef Documentation
typedef enum pkcs12_key_type_t pkcs12_key_type_t
Definition at line 27 of file pkcs12.h.
typedef struct pkcs12_t pkcs12_t
Definition at line 28 of file pkcs12.h.
Enumeration Type Documentation
enum pkcs12_key_type_t
The types of password based keys used by PKCS#12.
Enumerator
PKCS12_KEY_ENCRYPTION
PKCS12_KEY_IV
PKCS12_KEY_MAC
Definition at line 33 of file pkcs12.h.
{
     PKCS12_KEY_ENCRYPTION = 1,
     PKCS12_KEY_IV = 2,
     PKCS12_KEY_MAC = 3,
 };
Function Documentation
bool pkcs12_derive_key (hash_algorithm_t hash, chunk_t password, chunk_t salt, u_int64_t iterations, pkcs12_key_type_t type, chunk_t key)
Derive the keys used in PKCS#12 for password integrity/privacy mode.
Parameters
hash hash algorithm to use for key derivation
password password (ASCII)
salt salt value
iterations number of iterations
type type of key to derive
key the returned key, must be allocated of desired length
Returns
TRUE on success
Definition at line 151 of file libstrongswan/credentials/containers/pkcs12.c.
References chunk_alloca, chunk_empty, derive_key(), chunk_t::len, memwipe(), and chunk_t::ptr.
Referenced by pkcs12_kdf(), and verify_mac().
 {
     chunk_t unicode = chunk_empty;
     bool success;
     int i;
     if (password.len)
     {   /* convert the password to UTF-16BE (without BOM) with 0 terminator */
         unicode = chunk_alloca(password.len * 2 + 2);
         for (i = 0; i < password.len; i++)
         {
             unicode.ptr[i * 2] = 0;
             unicode.ptr[i * 2 + 1] = password.ptr[i];
         }
         unicode.ptr[i * 2] = 0;
         unicode.ptr[i * 2 + 1] = 0;
     }
     success = derive_key(hash, unicode, salt, iterations, type, key);
     memwipe(unicode.ptr, unicode.len);
     return success;
 }