strongSwan: osx_attr_handler.c File Reference
osx_attr_handler.c File Reference
#include "osx_attr_handler.h"
#include <networking/host.h>
#include <utils/debug.h>
#include <SystemConfiguration/SCDynamicStore.h>
Classes
struct private_osx_attr_handler_t
Typedefs
typedef struct
private_osx_attr_handler_t private_osx_attr_handler_t
Functions
static CFStringRef create_dns_path (SCDynamicStoreRef store)
static CFMutableDictionaryRef get_dictionary (SCDynamicStoreRef store, CFStringRef path)
static CFMutableArrayRef get_array_from_dict (CFDictionaryRef dict, CFStringRef name)
static bool manage_dns (private_osx_attr_handler_t *this, int family, chunk_t data, bool add)
METHOD (attribute_handler_t, handle, bool, private_osx_attr_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (attribute_handler_t, release, void, private_osx_attr_handler_t *this, ike_sa_t *ike_sa, configuration_attribute_type_t type, chunk_t data)
METHOD (enumerator_t, enumerate_dns, bool, enumerator_t *this, configuration_attribute_type_t *type, chunk_t *data)
METHOD (attribute_handler_t, create_attribute_enumerator, enumerator_t *, private_osx_attr_handler_t *this, ike_sa_t *ike_sa, linked_list_t *vips)
METHOD (osx_attr_handler_t, destroy, void, private_osx_attr_handler_t *this)
osx_attr_handler_t * osx_attr_handler_create ()
Typedef Documentation
typedef struct private_osx_attr_handler_t private_osx_attr_handler_t
Definition at line 23 of file osx_attr_handler.c.
Function Documentation
static CFStringRef create_dns_path (SCDynamicStoreRef store) static
Create a path to the DNS configuration of the Primary IPv4 Service
Definition at line 49 of file osx_attr_handler.c.
References DBG1, DBG_CFG, and path.
Referenced by manage_dns().
 {
     CFStringRef service, path = NULL;
     CFDictionaryRef dict;
     /* get primary service */
     dict = SCDynamicStoreCopyValue(store, CFSTR("State:/Network/Global/IPv4"));
     if (dict)
     {
         service = CFDictionaryGetValue(dict, CFSTR("PrimaryService"));
         if (service)
         {
             path = CFStringCreateWithFormat(NULL, NULL,
                                 CFSTR("State:/Network/Service/%@/DNS"), service);
         }
         else
         {
             DBG1(DBG_CFG, "SystemConfiguration PrimaryService not known");
         }
         CFRelease(dict);
     }
     else
     {
         DBG1(DBG_CFG, "getting global IPv4 SystemConfiguration failed");
     }
     return path;
 }
static CFMutableArrayRef get_array_from_dict (CFDictionaryRef dict, CFStringRef name) static
Create a mutable array from dictionary path, a new one if not found
Definition at line 107 of file osx_attr_handler.c.
Referenced by manage_dns().
 {
     CFArrayRef arr;
     arr = CFDictionaryGetValue(dict, name);
     if (arr && CFGetTypeID(arr) == CFArrayGetTypeID())
     {
         return CFArrayCreateMutableCopy(NULL, 0, arr);
     }
     return CFArrayCreateMutable(NULL, 0, &kCFTypeArrayCallBacks);
 }
static CFMutableDictionaryRef get_dictionary (SCDynamicStoreRef store, CFStringRef path) static
Create a mutable dictionary from path, a new one if not found
Definition at line 80 of file osx_attr_handler.c.
Referenced by manage_dns().
 {
     CFDictionaryRef dict;
     CFMutableDictionaryRef mut = NULL;
     dict = SCDynamicStoreCopyValue(store, path);
     if (dict)
     {
         if (CFGetTypeID(dict) == CFDictionaryGetTypeID())
         {
             mut = CFDictionaryCreateMutableCopy(NULL, 0, dict);
         }
         CFRelease(dict);
     }
     if (!mut)
     {
         mut = CFDictionaryCreateMutable(NULL, 0,
                                         &kCFTypeDictionaryKeyCallBacks,
                                         &kCFTypeDictionaryValueCallBacks);
     }
     return mut;
 }
static bool manage_dns (private_osx_attr_handler_t * this, int family, chunk_t data, bool add) static
Add/Remove a DNS server to the configuration
Definition at line 123 of file osx_attr_handler.c.
References create_dns_path(), DBG1, DBG_CFG, host_t::destroy, FALSE, get_array_from_dict(), get_dictionary(), host_create_from_chunk(), path, server, and snprintf.
Referenced by METHOD().
 {
     SCDynamicStoreRef store;
     CFStringRef path, dns;
     CFMutableArrayRef arr;
     CFMutableDictionaryRef dict;
     CFIndex i;
     host_t *server;
     char buf[64];
     bool success = FALSE;
     server = host_create_from_chunk(family, data, 0);
     if (!server)
     {
         return FALSE;
     }
     snprintf(buf, sizeof(buf), "%H", server);
     server->destroy(server);
     store = SCDynamicStoreCreate(NULL, CFSTR("osx-attr"), NULL, NULL);
     path = create_dns_path(store);
     if (path)
     {
         dict = get_dictionary(store, path);
         arr = get_array_from_dict(dict, CFSTR("ServerAddresses"));
         dns = CFStringCreateWithCString(NULL, buf, kCFStringEncodingUTF8);
         if (add)
         {
             if (!this->append && !this->original)
             {   /* backup orignal config, start with empty set */
                 this->original = arr;
                 arr = CFArrayCreateMutable(NULL, 0, &kCFTypeArrayCallBacks);
             }
             DBG1(DBG_CFG, "installing %s as DNS server", buf);
             CFArrayInsertValueAtIndex(arr, 0, dns);
         }
         else
         {
             i = CFArrayGetFirstIndexOfValue(arr,
                                     CFRangeMake(0, CFArrayGetCount(arr)), dns);
             if (i >= 0)
             {
                 DBG1(DBG_CFG, "removing %s from DNS servers (%d)", buf, i);
                 CFArrayRemoveValueAtIndex(arr, i);
             }
             if (!this->append && this->original && CFArrayGetCount(arr) == 0)
             {   /* restore original config */
                 CFRelease(arr);
                 arr = this->original;
                 this->original = NULL;
             }
         }
         CFRelease(dns);
         CFDictionarySetValue(dict, CFSTR("ServerAddresses"), arr);
         CFRelease(arr);
         success = SCDynamicStoreSetValue(store, path, dict);
         CFRelease(dict);
         CFRelease(path);
     }
     CFRelease(store);
     if (!success)
     {
         DBG1(DBG_CFG, "adding DNS server to SystemConfiguration failed");
     }
     return success;
 }
METHOD (attribute_handler_t , handle , bool , private_osx_attr_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 193 of file osx_attr_handler.c.
References FALSE, INTERNAL_IP4_DNS, manage_dns(), and TRUE.
 {
     switch (type)
     {
         case INTERNAL_IP4_DNS:
             return manage_dns(this, AF_INET, data, TRUE);
         default:
             return FALSE;
     }
 }
METHOD (attribute_handler_t , release , void , private_osx_attr_handler_t * this, ike_sa_t * ike_sa, configuration_attribute_type_t type, chunk_t data)
Definition at line 206 of file osx_attr_handler.c.
References FALSE, INTERNAL_IP4_DNS, and manage_dns().
 {
     switch (type)
     {
         case INTERNAL_IP4_DNS:
             manage_dns(this, AF_INET, data, FALSE);
             break;
         default:
             break;
     }
 }
METHOD (enumerator_t , enumerate_dns , bool , enumerator_t * this, configuration_attribute_type_t * type, chunk_t * data)
Definition at line 220 of file osx_attr_handler.c.
References chunk_empty, enumerate(), INTERNAL_IP4_DNS, return_false(), and TRUE.
 {
     *type = INTERNAL_IP4_DNS;
     *data = chunk_empty;
     /* stop enumeration */
     this->enumerate = (void*)return_false;
     return TRUE;
 }
METHOD (attribute_handler_t , create_attribute_enumerator , enumerator_t * , private_osx_attr_handler_t * this, ike_sa_t * ike_sa, linked_list_t * vips)
Definition at line 230 of file osx_attr_handler.c.
References destroy(), enumerate(), free(), and INIT.
 {
     enumerator_t *enumerator;
     INIT(enumerator,
         .enumerate = (void*)_enumerate_dns,
         .destroy = (void*)free,
     );
     return enumerator;
 }
METHOD (osx_attr_handler_t , destroy , void , private_osx_attr_handler_t * this)
Definition at line 243 of file osx_attr_handler.c.
References free().
 {
     free(this);
 }