strongSwan: eap_peap.c File Reference
eap_peap.c File Reference
#include "eap_peap.h"
#include "eap_peap_peer.h"
#include "eap_peap_server.h"
#include <tls_eap.h>
#include <daemon.h>
#include <library.h>
Classes
struct private_eap_peap_t
Macros
#define MAX_MESSAGE_COUNT 32
#define MAX_FRAGMENT_LEN 1024
Typedefs
typedef struct private_eap_peap_t private_eap_peap_t
Functions
METHOD (eap_method_t, initiate, status_t, private_eap_peap_t *this, eap_payload_t **out)
METHOD (eap_method_t, process, status_t, private_eap_peap_t *this, eap_payload_t *in, eap_payload_t **out)
METHOD (eap_method_t, get_type, eap_type_t, private_eap_peap_t *this, u_int32_t *vendor)
METHOD (eap_method_t, get_msk, status_t, private_eap_peap_t *this, chunk_t *msk)
METHOD (eap_method_t, get_identifier, u_int8_t, private_eap_peap_t *this)
METHOD (eap_method_t, set_identifier, void, private_eap_peap_t *this, u_int8_t identifier)
METHOD (eap_method_t, is_mutual, bool, private_eap_peap_t *this)
METHOD (eap_method_t, destroy, void, private_eap_peap_t *this)
static private_eap_peap_t * eap_peap_create_empty (void)
static eap_peap_t * eap_peap_create (private_eap_peap_t *this, identification_t *server, identification_t *peer, bool is_server, tls_application_t *application)
eap_peap_t * eap_peap_create_server (identification_t *server, identification_t *peer)
eap_peap_t * eap_peap_create_peer (identification_t *server, identification_t *peer)
Macro Definition Documentation
#define MAX_FRAGMENT_LEN 1024
Default size of a EAP-PEAP fragment
Definition at line 46 of file eap_peap.c.
Referenced by eap_peap_create().
#define MAX_MESSAGE_COUNT 32
Maximum number of EAP-PEAP messages/fragments allowed
Definition at line 44 of file eap_peap.c.
Referenced by eap_peap_create().
Typedef Documentation
typedef struct private_eap_peap_t private_eap_peap_t
Definition at line 25 of file eap_peap.c.
Function Documentation
static eap_peap_t* eap_peap_create (private_eap_peap_t * this, identification_t * server, identification_t * peer, bool is_server, tls_application_t * application) static
Generic private constructor
Definition at line 148 of file eap_peap.c.
References tls_application_t::destroy, EAP_PEAP, FALSE, free(), settings_t::get_bool, settings_t::get_int, lib, MAX_FRAGMENT_LEN, MAX_MESSAGE_COUNT, library_t::ns, library_t::settings, tls, tls_create(), tls_eap_create(), and TLS_PURPOSE_EAP_PEAP.
Referenced by eap_peap_create_peer(), and eap_peap_create_server().
 {
     size_t frag_size;
     int max_msg_count;
     bool include_length;
     tls_t *tls;
     if (is_server && !lib->settings->get_bool(lib->settings,
                                 "%s.plugins.eap-peap.request_peer_auth", FALSE,
                                 lib->ns))
     {
         peer = NULL;
     }
     frag_size = lib->settings->get_int(lib->settings,
                     "%s.plugins.eap-peap.fragment_size", MAX_FRAGMENT_LEN,
                     lib->ns);
     max_msg_count = lib->settings->get_int(lib->settings,
                     "%s.plugins.eap-peap.max_message_count", MAX_MESSAGE_COUNT,
                     lib->ns);
     include_length = lib->settings->get_bool(lib->settings,
                     "%s.plugins.eap-peap.include_length", FALSE, lib->ns);
     tls = tls_create(is_server, server, peer, TLS_PURPOSE_EAP_PEAP,
                      application, NULL);
     this->tls_eap = tls_eap_create(EAP_PEAP, tls, frag_size, max_msg_count,
                                                   include_length);
     if (!this->tls_eap)
     {
         application->destroy(application);
         free(this);
         return NULL;
     }
     return &this->public;
 }
static private_eap_peap_t* eap_peap_create_empty (void) static
Create an empty private eap_peap_t object
Definition at line 124 of file eap_peap.c.
References INIT.
Referenced by eap_peap_create_peer(), and eap_peap_create_server().
 {
     private_eap_peap_t *this;
     INIT(this,
         .public = {
             .eap_method = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .destroy = _destroy,
             },
         },
     );
     return this;
 }
METHOD (eap_method_t , initiate , status_t , private_eap_peap_t * this, eap_payload_t ** out)
Definition at line 48 of file eap_peap.c.
References data, eap_payload_create_data(), FAILED, free(), NEED_MORE, and chunk_t::ptr.
 {
     chunk_t data;
     if (this->tls_eap->initiate(this->tls_eap, &data) == NEED_MORE)
     {
         *out = eap_payload_create_data(data);
         free(data.ptr);
         return NEED_MORE;
     }
     return FAILED;
 }
METHOD (eap_method_t , process , status_t , private_eap_peap_t * this, eap_payload_t * in, eap_payload_t ** out)
Definition at line 62 of file eap_peap.c.
References data, eap_payload_create_data(), free(), eap_payload_t::get_data, NEED_MORE, chunk_t::ptr, and status.
 {
     status_t status;
     chunk_t data;
     data = in->get_data(in);
     status = this->tls_eap->process(this->tls_eap, data, &data);
     if (status == NEED_MORE)
     {
         *out = eap_payload_create_data(data);
         free(data.ptr);
     }
     return status;
 }
METHOD (eap_method_t , get_type , eap_type_t , private_eap_peap_t * this, u_int32_t * vendor)
Definition at line 78 of file eap_peap.c.
References EAP_PEAP.
 {
     *vendor = 0;
     return EAP_PEAP;
 }
METHOD (eap_method_t , get_msk , status_t , private_eap_peap_t * this, chunk_t * msk)
Definition at line 85 of file eap_peap.c.
References FAILED, chunk_t::len, and SUCCESS.
 {
     *msk = this->tls_eap->get_msk(this->tls_eap);
     if (msk->len)
     {
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (eap_method_t , get_identifier , u_int8_t , private_eap_peap_t * this)
Definition at line 96 of file eap_peap.c.
 {
     return this->tls_eap->get_identifier(this->tls_eap);
 }
METHOD (eap_method_t , set_identifier , void , private_eap_peap_t * this, u_int8_t identifier)
Definition at line 102 of file eap_peap.c.
 {
     this->tls_eap->set_identifier(this->tls_eap, identifier);
 }
METHOD (eap_method_t , is_mutual , bool , private_eap_peap_t * this)
Definition at line 108 of file eap_peap.c.
References TRUE.
 {
     return TRUE;
 }
METHOD (eap_method_t , destroy , void , private_eap_peap_t * this)
Definition at line 114 of file eap_peap.c.
References free().
 {
     this->tls_eap->destroy(this->tls_eap);
     free(this);
 }