strongSwan: pb_language_preference_msg.c File Reference
pb_language_preference_msg.c File Reference
#include "pb_language_preference_msg.h"
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pb_language_preference_msg_t
Macros
#define PB_LANG_PREFIX "Accept-Language: "
#define PB_LANG_PREFIX_LEN strlen(PB_LANG_PREFIX)
Typedefs
typedef struct
private_pb_language_preference_msg_t private_pb_language_preference_msg_t
Functions
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_language_preference_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_language_preference_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_language_preference_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_language_preference_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_language_preference_msg_t *this)
METHOD (pb_language_preference_msg_t, get_language_preference, chunk_t, private_pb_language_preference_msg_t *this)
pb_tnc_msg_t * pb_language_preference_msg_create_from_data (chunk_t data)
pb_tnc_msg_t * pb_language_preference_msg_create (chunk_t language_preference)
Macro Definition Documentation
#define PB_LANG_PREFIX "Accept-Language: "
PB-Language-Preference message (see section 4.10 of RFC 5793)
0 1 2 3 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Language Preference (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 34 of file pb_language_preference_msg.c.
Referenced by METHOD().
#define PB_LANG_PREFIX_LEN strlen(PB_LANG_PREFIX)
Definition at line 35 of file pb_language_preference_msg.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_pb_language_preference_msg_t private_pb_language_preference_msg_t
Definition at line 22 of file pb_language_preference_msg.c.
Function Documentation
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_language_preference_msg_t * this)
Definition at line 63 of file pb_language_preference_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_language_preference_msg_t * this)
Definition at line 69 of file pb_language_preference_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_language_preference_msg_t * this)
Definition at line 75 of file pb_language_preference_msg.c.
References chunk_cat, chunk_create(), encoding, PB_LANG_PREFIX, and PB_LANG_PREFIX_LEN.
 {
     if (this->encoding.ptr)
     {
         return;
     }
     this->encoding = chunk_cat("cc",
                         chunk_create(PB_LANG_PREFIX, PB_LANG_PREFIX_LEN),
                         this->language_preference);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_language_preference_msg_t * this, u_int32_t * offset)
Definition at line 87 of file pb_language_preference_msg.c.
References chunk_clone, chunk_empty, chunk_skip(), DBG1, DBG_TNC, encoding, FAILED, chunk_t::len, memeq(), PB_LANG_PREFIX, PB_LANG_PREFIX_LEN, and SUCCESS.
 {
     chunk_t lang;
     if (this->encoding.len >= PB_LANG_PREFIX_LEN &&
         memeq(this->encoding.ptr, PB_LANG_PREFIX, PB_LANG_PREFIX_LEN))
     {
         lang = chunk_skip(this->encoding, PB_LANG_PREFIX_LEN);
         this->language_preference = lang.len ? chunk_clone(lang) : chunk_empty;
     }
     else
     {
         DBG1(DBG_TNC, "language preference must be preceded by '%s'",
                        PB_LANG_PREFIX);
         *offset = 0;
         return FAILED;
     }
     if (this->language_preference.len &&
         this->language_preference.ptr[this->language_preference.len-1] == '\0')
     {
         DBG1(DBG_TNC, "language preference must not be null terminated");
         *offset = PB_LANG_PREFIX_LEN + this->language_preference.len - 1;
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_language_preference_msg_t * this)
Definition at line 117 of file pb_language_preference_msg.c.
References encoding, and free().
 {
     free(this->encoding.ptr);
     free(this->language_preference.ptr);
     free(this);
 }
METHOD (pb_language_preference_msg_t , get_language_preference , chunk_t , private_pb_language_preference_msg_t * this)
Definition at line 125 of file pb_language_preference_msg.c.
 {
     return this->language_preference;
 }