strongSwan: imc_manager_t Struct Reference
imc_manager_t Struct Reference
imc_manager
#include "imc_manager.h"
Public Attributes
bool(* add)(imc_manager_t *this, imc_t *imc)
imc_t *(* remove)(imc_manager_t *this, TNC_IMCID id)
bool(* load)(imc_manager_t *this, char *name, char *path)
bool(* load_from_functions)(imc_manager_t *this, char *name, TNC_IMC_InitializePointer initialize, TNC_IMC_NotifyConnectionChangePointer notify_connection_change, TNC_IMC_BeginHandshakePointer begin_handshake, TNC_IMC_ReceiveMessagePointer receive_message, TNC_IMC_ReceiveMessageLongPointer receive_message_long, TNC_IMC_BatchEndingPointer batch_ending, TNC_IMC_TerminatePointer terminate, TNC_IMC_ProvideBindFunctionPointer provide_bind_function)
bool(* is_registered)(imc_manager_t *this, TNC_IMCID id)
bool(* reserve_id)(imc_manager_t *this, TNC_IMCID id, TNC_UInt32 *new_id)
char *(* get_preferred_language)(imc_manager_t *this)
void(* notify_connection_change)(imc_manager_t *this, TNC_ConnectionID id, TNC_ConnectionState state)
void(* begin_handshake)(imc_manager_t *this, TNC_ConnectionID id)
TNC_Result(* set_message_types)(imc_manager_t *this, TNC_IMCID id, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
TNC_Result(* set_message_types_long)(imc_manager_t *this, TNC_IMCID id, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
void(* receive_message)(imc_manager_t *this, TNC_ConnectionID connection_id, bool excl, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
void(* batch_ending)(imc_manager_t *this, TNC_ConnectionID id)
void(* destroy)(imc_manager_t *this)
Detailed Description
The IMC manager controls all IMC instances.
Definition at line 33 of file imc_manager.h.
Member Data Documentation
bool(* imc_manager_t::add)(imc_manager_t *this, imc_t *imc)
Add an IMC instance
Parameters
imc IMC instance
Returns
TRUE if initialization successful
Definition at line 41 of file imc_manager.h.
void(* imc_manager_t::batch_ending)(imc_manager_t *this, TNC_ConnectionID id)
Notify all IMCs that all IMV messages received in a batch have been delivered and this is the IMCs last chance to send a message in the batch of IMC messages currently being collected.
Parameters
id connection ID
Definition at line 181 of file imc_manager.h.
Referenced by METHOD().
void(* imc_manager_t::begin_handshake)(imc_manager_t *this, TNC_ConnectionID id)
Begin a handshake between the IMCs and a connection
Parameters
id connection ID
Definition at line 122 of file imc_manager.h.
Referenced by METHOD().
void(* imc_manager_t::destroy)(imc_manager_t *this)
Destroy an IMC manager and all its controlled instances.
Definition at line 186 of file imc_manager.h.
Referenced by tnc_manager_register().
char*(* imc_manager_t::get_preferred_language)(imc_manager_t *this)
Return the preferred language for recommendations
Returns
preferred language string
Definition at line 106 of file imc_manager.h.
Referenced by METHOD().
bool(* imc_manager_t::is_registered)(imc_manager_t *this, TNC_IMCID id)
Check if an IMC with a given ID is registered with the IMC manager
Parameters
id ID of IMC instance
Returns
TRUE if registered
Definition at line 90 of file imc_manager.h.
Referenced by TNC_TNCC_GetAttribute(), TNC_TNCC_ReportMessageTypes(), TNC_TNCC_ReportMessageTypesLong(), TNC_TNCC_RequestHandshakeRetry(), TNC_TNCC_SendMessage(), TNC_TNCC_SendMessageLong(), and TNC_TNCC_SetAttribute().
bool(* imc_manager_t::load)(imc_manager_t *this, char *name, char *path)
Load and initialize an IMC as a dynamic library and add it to the list
Parameters
name name of the IMC to be loaded
path path of the IMC dynamic library file
Returns
TRUE if loading succeeded
Definition at line 58 of file imc_manager.h.
Referenced by load_imcvs_from_config().
bool(* imc_manager_t::load_from_functions)(imc_manager_t *this, char *name, TNC_IMC_InitializePointer initialize, TNC_IMC_NotifyConnectionChangePointer notify_connection_change, TNC_IMC_BeginHandshakePointer begin_handshake, TNC_IMC_ReceiveMessagePointer receive_message, TNC_IMC_ReceiveMessageLongPointer receive_message_long, TNC_IMC_BatchEndingPointer batch_ending, TNC_IMC_TerminatePointer terminate, TNC_IMC_ProvideBindFunctionPointer provide_bind_function)
Load and initialize an IMC from a set of TNC IMC functions.
Parameters
name name of the IMC
initialize TNC_IMC_InitializePointer
notify_connection_change TNC_IMC_NotifyConnectionChangePointer
begin_handshake TNC_IMC_BeginHandshakePointer
receive_message TNC_IMC_ReceiveMessagePointer
receive_message_long TNC_IMC_ReceiveMessageLongPointer
batch_ending TNC_IMC_BatchEndingPointer
terminate TNC_IMC_TerminatePointer
provide_bind_function TNC_IMC_ProvideBindFunctionPointer
Returns
TRUE if loading succeeded
Definition at line 74 of file imc_manager.h.
void(* imc_manager_t::notify_connection_change)(imc_manager_t *this, TNC_ConnectionID id, TNC_ConnectionState state)
Notify all IMC instances
Parameters
state communicate the state a connection has reached
Definition at line 113 of file imc_manager.h.
Referenced by handle_ietf_message(), handle_message(), METHOD(), and tnccs_20_client_create().
void(* imc_manager_t::receive_message)(imc_manager_t *this, TNC_ConnectionID connection_id, bool excl, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
Delivers a message to interested IMCs.
Parameters
connection_id connection ID
excl exclusive message flag
msg message
msg_len message length
msg_vid message Vendor ID
msg_subtype message subtype
src_imv_id source IMV ID
dst_imc_id destination IMC ID
Definition at line 164 of file imc_manager.h.
Referenced by handle_ietf_message(), and handle_message().
imc_t*(* imc_manager_t::remove)(imc_manager_t *this, TNC_IMCID id)
Remove an IMC instance from the list and return it
Parameters
id ID of IMC instance
Returns
removed IMC instance
Definition at line 49 of file imc_manager.h.
bool(* imc_manager_t::reserve_id)(imc_manager_t *this, TNC_IMCID id, TNC_UInt32 *new_id)
Reserve an additional ID for an IMC
Parameters
id ID of IMC instance
new_id reserved ID assigned to IMC
Returns
TRUE if primary IMC ID was used
Definition at line 99 of file imc_manager.h.
Referenced by TNC_TNCC_ReserveAdditionalIMCID().
TNC_Result(* imc_manager_t::set_message_types)(imc_manager_t *this, TNC_IMCID id, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
Sets the supported message types reported by a given IMC
Parameters
id ID of reporting IMC
supported_types list of messages type supported by IMC
type_count number of supported message types
Returns
TNC result code
Definition at line 132 of file imc_manager.h.
Referenced by TNC_TNCC_ReportMessageTypes().
TNC_Result(* imc_manager_t::set_message_types_long)(imc_manager_t *this, TNC_IMCID id, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
Sets the supported long message types reported by a given IMC
Parameters
id ID of reporting IMC
supported_vids list of vendor IDs supported by IMC
supported_subtypes list of messages type supported by IMC
type_count number of supported message types
Returns
TNC result code
Definition at line 146 of file imc_manager.h.
Referenced by TNC_TNCC_ReportMessageTypesLong().
The documentation for this struct was generated from the following file:
imc_manager.h