strongSwan: test_hashtable.c File Reference
test_hashtable.c File Reference
#include "test_suite.h"
#include <collections/hashtable.h>
#include <utils/chunk.h>
Functions
static u_int hash (char *key)
static bool equals (char *key1, char *key2)
START_SETUP (setup_ht)
END_SETUP START_TEARDOWN (teardown_ht)
END_TEARDOWN START_TEST (test_put_get)
static END_TEST u_int hash_match (char *key)
static bool equal_match (char *key1, char *key2)
START_TEST (test_get_match)
static END_TEST void do_remove (char *k1, char *k2, char *k3)
START_TEST (test_remove)
END_TEST START_TEST (test_remove_one_bucket)
END_TEST START_TEST (test_enumerator)
static END_TEST void do_remove_at (char *k1, char *k2, char *k3)
START_TEST (test_remove_at)
END_TEST START_TEST (test_remove_at_one_bucket)
END_TEST Suite * hashtable_suite_create ()
Variables
static hashtable_t * ht
Function Documentation
static END_TEST void do_remove (char * k1, char * k2, char * k3) static
Definition at line 142 of file test_hashtable.c.
References ck_assert, ck_assert_int_eq, hashtable_t::get, hashtable_t::get_count, hashtable_t::put, hashtable_t::remove, streq(), and value.
Referenced by START_TEST().
 {
     char *v1 = "val1", *v2 = "val2", *v3 = "val3", *value;
     ht->put(ht, k1, v1);
     ht->put(ht, k2, v2);
     ht->put(ht, k3, v3);
     value = ht->remove(ht, k2);
     ck_assert_int_eq(ht->get_count(ht), 2);
     ck_assert(streq(ht->get(ht, k1), v1));
     ck_assert(streq(ht->get(ht, k3), v3));
     ck_assert(streq(value, v2));
     ck_assert(ht->get(ht, k2) == NULL);
     value = ht->remove(ht, k2);
     ck_assert_int_eq(ht->get_count(ht), 2);
     ck_assert(value == NULL);
     value = ht->remove(ht, k1);
     value = ht->remove(ht, k3);
     ck_assert_int_eq(ht->get_count(ht), 0);
     ck_assert(ht->get(ht, k1) == NULL);
     ck_assert(ht->get(ht, k2) == NULL);
     ck_assert(ht->get(ht, k3) == NULL);
 }
static END_TEST void do_remove_at (char * k1, char * k2, char * k3) static
Definition at line 247 of file test_hashtable.c.
References ck_assert, ck_assert_int_eq, hashtable_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, hashtable_t::get, hashtable_t::get_count, key, hashtable_t::put, hashtable_t::remove_at, streq(), and value.
Referenced by START_TEST().
 {
     char *v1 = "val1", *v2 = "val2", *v3 = "val3", *value, *key;
     enumerator_t *enumerator;
     ht->put(ht, k1, v1);
     ht->put(ht, k2, v2);
     ht->put(ht, k3, v3);
     enumerator = ht->create_enumerator(ht);
     ht->remove_at(ht, enumerator);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         if (streq(key, k2))
         {
             ht->remove_at(ht, enumerator);
         }
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(ht->get_count(ht), 2);
     ck_assert(ht->get(ht, k1) != NULL);
     ck_assert(ht->get(ht, k3) != NULL);
     ck_assert(ht->get(ht, k2) == NULL);
     ht->put(ht, k2, v2);
     ck_assert_int_eq(ht->get_count(ht), 3);
     ck_assert(ht->get(ht, k1) != NULL);
     ck_assert(ht->get(ht, k2) != NULL);
     ck_assert(ht->get(ht, k3) != NULL);
     enumerator = ht->create_enumerator(ht);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         ht->remove_at(ht, enumerator);
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(ht->get_count(ht), 0);
     ck_assert(ht->get(ht, k1) == NULL);
     ck_assert(ht->get(ht, k2) == NULL);
     ck_assert(ht->get(ht, k3) == NULL);
 }
static bool equal_match (char * key1, char * key2) static
Definition at line 94 of file test_hashtable.c.
References FALSE, and strneq().
Referenced by START_TEST().
 {
     if (!strneq(key1, key2, 4))
     {
         return FALSE;
     }
     /* look for an item with a key < than what we look for */
     return strcmp(key1, key2) >= 0;
 }
static bool equals (char * key1, char * key2) static
Definition at line 30 of file test_hashtable.c.
References streq().
Referenced by START_SETUP(), and START_TEST().
 {
     return streq(key1, key2);
 }
static u_int hash (char * key) static
Definition at line 25 of file test_hashtable.c.
References chunk_from_str, and chunk_hash().
Referenced by START_SETUP().
 {
     return chunk_hash(chunk_from_str(key));
 }
static END_TEST u_int hash_match (char * key) static
Definition at line 89 of file test_hashtable.c.
References chunk_create(), and chunk_hash().
Referenced by START_TEST().
 {
     return chunk_hash(chunk_create(key, 4));
 }
END_TEST Suite* hashtable_suite_create ()
Definition at line 312 of file test_hashtable.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_checked_fixture, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("hashtable");
     tc = tcase_create("put/get");
     tcase_add_checked_fixture(tc, setup_ht, teardown_ht);
     tcase_add_test(tc, test_put_get);
     suite_add_tcase(s, tc);
     tc = tcase_create("get_match");
     tcase_add_test(tc, test_get_match);
     suite_add_tcase(s, tc);
     tc = tcase_create("remove");
     tcase_add_checked_fixture(tc, setup_ht, teardown_ht);
     tcase_add_test(tc, test_remove);
     tcase_add_test(tc, test_remove_one_bucket);
     suite_add_tcase(s, tc);
     tc = tcase_create("enumerator");
     tcase_add_checked_fixture(tc, setup_ht, teardown_ht);
     tcase_add_test(tc, test_enumerator);
     suite_add_tcase(s, tc);
     tc = tcase_create("remove_at");
     tcase_add_checked_fixture(tc, setup_ht, teardown_ht);
     tcase_add_test(tc, test_remove_at);
     tcase_add_test(tc, test_remove_at_one_bucket);
     suite_add_tcase(s, tc);
     return s;
 }
START_SETUP (setup_ht)
Definition at line 41 of file test_hashtable.c.
References ck_assert_int_eq, equals(), hashtable_t::get_count, hash(), and hashtable_create().
 {
     ht = hashtable_create((hashtable_hash_t)hash,
                           (hashtable_equals_t)equals, 0);
     ck_assert_int_eq(ht->get_count(ht), 0);
 }
END_SETUP START_TEARDOWN (teardown_ht)
Definition at line 49 of file test_hashtable.c.
References hashtable_t::destroy.
 {
     ht->destroy(ht);
 }
END_TEARDOWN START_TEST (test_put_get)
Definition at line 59 of file test_hashtable.c.
References ck_assert, ck_assert_int_eq, hashtable_t::get, hashtable_t::get_count, hashtable_t::put, streq(), and value.
 {
     char *k1 = "key1", *k2 = "key2", *k3 = "key3";
     char *v1 = "val1", *v2 = "val2", *v3 = "val3", *value;
     value = ht->put(ht, k1, v1);
     ck_assert_int_eq(ht->get_count(ht), 1);
     ck_assert(streq(ht->get(ht, k1), v1));
     ck_assert(ht->get(ht, k2) == NULL);
     ck_assert(ht->get(ht, k3) == NULL);
     ck_assert(value == NULL);
     ht->put(ht, k2, v2);
     ht->put(ht, k3, v3);
     ck_assert_int_eq(ht->get_count(ht), 3);
     ck_assert(streq(ht->get(ht, k1), v1));
     ck_assert(streq(ht->get(ht, k2), v2));
     ck_assert(streq(ht->get(ht, k3), v3));
     value = ht->put(ht, k2, v1);
     ck_assert_int_eq(ht->get_count(ht), 3);
     ck_assert(streq(value, v2));
     ck_assert(streq(ht->get(ht, k2), v1));
 }
START_TEST (test_get_match)
Definition at line 104 of file test_hashtable.c.
References ck_assert, ck_assert_int_eq, hashtable_t::destroy, equal_match(), equals(), hashtable_t::get, hashtable_t::get_count, hashtable_t::get_match, hash_match(), hashtable_create(), hashtable_t::put, streq(), and value.
 {
     char *k1 = "key1_a", *k2 = "key2", *k3 = "key1_b", *k4 = "key1_c";
     char *v1 = "val1", *v2 = "val2", *v3 = "val3", *value;
     ht = hashtable_create((hashtable_hash_t)hash_match,
                           (hashtable_equals_t)equals, 0);
     ht->put(ht, k1, v1);
     ht->put(ht, k2, v2);
     value = ht->put(ht, k3, v3);
     ck_assert_int_eq(ht->get_count(ht), 3);
     ck_assert(streq(ht->get(ht, k1), v1));
     ck_assert(streq(ht->get(ht, k2), v2));
     ck_assert(streq(ht->get(ht, k3), v3));
     ck_assert(value == NULL);
     value = ht->get_match(ht, k1, (hashtable_equals_t)equal_match);
     ck_assert(value != NULL);
     ck_assert(streq(value, v1));
     value = ht->get_match(ht, k2, (hashtable_equals_t)equal_match);
     ck_assert(value != NULL);
     ck_assert(streq(value, v2));
     value = ht->get_match(ht, k3, (hashtable_equals_t)equal_match);
     ck_assert(value != NULL);
     ck_assert(streq(value, v1));
     value = ht->get_match(ht, k4, (hashtable_equals_t)equal_match);
     ck_assert(value != NULL);
     ck_assert(streq(value, v1));
     ht->destroy(ht);
 }
START_TEST (test_remove)
Definition at line 169 of file test_hashtable.c.
References do_remove().
 {
     char *k1 = "key1", *k2 = "key2", *k3 = "key3";
     do_remove(k1, k2, k3);
 }
END_TEST START_TEST (test_remove_one_bucket)
Definition at line 177 of file test_hashtable.c.
References hashtable_t::destroy, do_remove(), equals(), hash_match(), and hashtable_create().
 {
     char *k1 = "key1_a", *k2 = "key1_b", *k3 = "key1_c";
     ht->destroy(ht);
     /* set a capacity to avoid rehashing, which would change the items' order */
     ht = hashtable_create((hashtable_hash_t)hash_match,
                           (hashtable_equals_t)equals, 8);
     do_remove(k1, k2, k3);
 }
END_TEST START_TEST (test_enumerator)
Definition at line 194 of file test_hashtable.c.
References ck_assert, ck_assert_int_eq, count, hashtable_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, key, hashtable_t::put, hashtable_t::remove, streq(), and value.
 {
     char *k1 = "key1", *k2 = "key2", *k3 = "key3", *key;
     char *v1 = "val1", *v2 = "val2", *v3 = "val3", *value;
     enumerator_t *enumerator;
     int count;
     ht->put(ht, k1, v1);
     ht->put(ht, k2, v2);
     ht->put(ht, k3, v3);
     count = 0;
     enumerator = ht->create_enumerator(ht);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         ck_assert(streq(key, k1) || streq(key, k2) || streq(key, k3));
         ck_assert(streq(value, v1) || streq(value, v2) || streq(value, v3));
         ck_assert(!streq(key, k1) || streq(value, v1));
         ck_assert(!streq(key, k2) || streq(value, v2));
         ck_assert(!streq(key, k3) || streq(value, v3));
         count++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(count, 3);
     count = 0;
     enumerator = ht->create_enumerator(ht);
     while (enumerator->enumerate(enumerator, NULL, NULL))
     {
         count++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(count, 3);
     value = ht->remove(ht, k1);
     value = ht->remove(ht, k2);
     value = ht->remove(ht, k3);
     count = 0;
     enumerator = ht->create_enumerator(ht);
     while (enumerator->enumerate(enumerator, &key, &value))
     {
         count++;
     }
     enumerator->destroy(enumerator);
     ck_assert_int_eq(count, 0);
 }
START_TEST (test_remove_at)
Definition at line 292 of file test_hashtable.c.
References do_remove_at().
 {
     char *k1 = "key1", *k2 = "key2", *k3 = "key3";
     do_remove_at(k1, k2, k3);
 }
END_TEST START_TEST (test_remove_at_one_bucket)
Definition at line 300 of file test_hashtable.c.
References hashtable_t::destroy, do_remove_at(), equals(), hash_match(), and hashtable_create().
 {
     char *k1 = "key1_a", *k2 = "key1_b", *k3 = "key1_c";
     ht->destroy(ht);
     /* set a capacity to avoid rehashing, which would change the items' order */
     ht = hashtable_create((hashtable_hash_t)hash_match,
                           (hashtable_equals_t)equals, 8);
     do_remove_at(k1, k2, k3);
 }
Variable Documentation
hashtable_t* ht static
Definition at line 39 of file test_hashtable.c.