strongSwan: eap_gtc
eap_gtc
eap_gtc
Classes
struct eap_gtc_t
Typedefs
typedef struct eap_gtc_t eap_gtc_t
Functions
eap_gtc_t * eap_gtc_create_server (identification_t *server, identification_t *peer)
eap_gtc_t * eap_gtc_create_peer (identification_t *server, identification_t *peer)
Variables
struct eap_gtc_t __attribute__
Detailed Description
Typedef Documentation
typedef struct eap_gtc_t eap_gtc_t
Definition at line 24 of file eap_gtc.h.
Function Documentation
eap_gtc_t* eap_gtc_create_peer (identification_t * server, identification_t * peer)
Creates the EAP method EAP-GTC acting as peer.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_gtc_t object
Definition at line 274 of file eap_gtc.c.
References eap_gtc_create_generic().
Referenced by METHOD().
 {
     private_eap_gtc_t *this = eap_gtc_create_generic(server, peer);
     this->public.eap_method_interface.initiate = _initiate_peer;
     this->public.eap_method_interface.process = _process_peer;
     return &this->public;
 }
eap_gtc_t* eap_gtc_create_server (identification_t * server, identification_t * peer)
Creates the EAP method EAP-GTC acting as server.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_gtc_t object
Definition at line 256 of file eap_gtc.c.
References eap_gtc_create_generic(), identifier, and random.
Referenced by METHOD().
 {
     private_eap_gtc_t *this = eap_gtc_create_generic(server, peer);
     this->public.eap_method_interface.initiate = _initiate_server;
     this->public.eap_method_interface.process = _process_server;
     /* generate a non-zero identifier */
     do {
         this->identifier = random();
     } while (!this->identifier);
     return &this->public;
 }
Variable Documentation
struct eap_gtc_t __attribute__