strongSwan: tnc_ifmap_listener.c File Reference
tnc_ifmap_listener.c File Reference
#include "tnc_ifmap_listener.h"
#include "tnc_ifmap_soap.h"
#include "tnc_ifmap_renew_session_job.h"
#include <daemon.h>
#include <hydra.h>
#include <utils/debug.h>
Classes
struct private_tnc_ifmap_listener_t
Macros
#define IFMAP_RENEW_SESSION_INTERVAL 150
Typedefs
typedef struct
private_tnc_ifmap_listener_t private_tnc_ifmap_listener_t
Functions
static bool publish_device_ip_addresses (private_tnc_ifmap_listener_t *this)
static bool reload_metadata (private_tnc_ifmap_listener_t *this)
METHOD (listener_t, ike_updown, bool, private_tnc_ifmap_listener_t *this, ike_sa_t *ike_sa, bool up)
METHOD (listener_t, assign_vips, bool, private_tnc_ifmap_listener_t *this, ike_sa_t *ike_sa, bool assign)
METHOD (listener_t, alert, bool, private_tnc_ifmap_listener_t *this, ike_sa_t *ike_sa, alert_t alert, va_list args)
METHOD (tnc_ifmap_listener_t, destroy, void, private_tnc_ifmap_listener_t *this)
tnc_ifmap_listener_t * tnc_ifmap_listener_create (bool reload)
Macro Definition Documentation
#define IFMAP_RENEW_SESSION_INTERVAL 150
Definition at line 24 of file tnc_ifmap_listener.c.
Referenced by tnc_ifmap_listener_create().
Typedef Documentation
typedef struct private_tnc_ifmap_listener_t private_tnc_ifmap_listener_t
Definition at line 26 of file tnc_ifmap_listener.c.
Function Documentation
METHOD (listener_t , ike_updown , bool , private_tnc_ifmap_listener_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 98 of file tnc_ifmap_listener.c.
References ike_sa_t::get_state, IKE_CONNECTING, and TRUE.
 {
     if (ike_sa->get_state(ike_sa) != IKE_CONNECTING)
     {
         this->ifmap->publish_ike_sa(this->ifmap, ike_sa, up);
     }
     return TRUE;
 }
METHOD (listener_t , assign_vips , bool , private_tnc_ifmap_listener_t * this, ike_sa_t * ike_sa, bool assign)
Definition at line 108 of file tnc_ifmap_listener.c.
References TRUE.
 {
     this->ifmap->publish_virtual_ips(this->ifmap, ike_sa, assign);
     return TRUE;
 }
METHOD (listener_t , alert , bool , private_tnc_ifmap_listener_t * this, ike_sa_t * ike_sa, alert_t alert, va_list args)
Definition at line 115 of file tnc_ifmap_listener.c.
References ALERT_PEER_AUTH_FAILED, ike_sa_t::get_other_host, and TRUE.
 {
     if (alert == ALERT_PEER_AUTH_FAILED)
     {
         this->ifmap->publish_enforcement_report(this->ifmap,
                             ike_sa->get_other_host(ike_sa),
                             "block", "authentication failed");
     }
     return TRUE;
 }
METHOD (tnc_ifmap_listener_t , destroy , void , private_tnc_ifmap_listener_t * this)
Definition at line 128 of file tnc_ifmap_listener.c.
References free().
 {
     if (this->ifmap)
     {
         if (this->ifmap->get_session_id(this->ifmap))
         {
             this->ifmap->endSession(this->ifmap);
         }
         this->ifmap->destroy(this->ifmap);
     }
     free(this);
 }
static bool publish_device_ip_addresses (private_tnc_ifmap_listener_t * this) static
Publish PEP device-ip metadata
Definition at line 48 of file tnc_ifmap_listener.c.
References ADDR_TYPE_REGULAR, kernel_interface_t::create_address_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, host, hydra, hydra_t::kernel_interface, and TRUE.
Referenced by tnc_ifmap_listener_create().
 {
     enumerator_t *enumerator;
     host_t *host;
     bool success = TRUE;
     enumerator = hydra->kernel_interface->create_address_enumerator(
                                     hydra->kernel_interface, ADDR_TYPE_REGULAR);
     while (enumerator->enumerate(enumerator, &host))
     {
         if (!this->ifmap->publish_device_ip(this->ifmap, host))
         {
             success = FALSE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return success;
 }
static bool reload_metadata (private_tnc_ifmap_listener_t * this) static
Publish all IKE_SA metadata
Definition at line 72 of file tnc_ifmap_listener.c.
References charon, daemon_t::controller, controller_t::create_ike_sa_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, ike_sa_t::get_state, IKE_ESTABLISHED, and TRUE.
Referenced by tnc_ifmap_listener_create().
 {
     ike_sa_t *ike_sa;
     enumerator_t *enumerator;
     bool success = TRUE;
     enumerator = charon->controller->create_ike_sa_enumerator(
                                                 charon->controller, FALSE);
     while (enumerator->enumerate(enumerator, &ike_sa))
     {
         if (ike_sa->get_state(ike_sa) != IKE_ESTABLISHED)
         {
             continue;
         }
         if (!this->ifmap->publish_ike_sa(this->ifmap, ike_sa, TRUE) ||
             !this->ifmap->publish_virtual_ips(this->ifmap, ike_sa, TRUE))
         {
             success = FALSE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return success;
 }