strongSwan: fetcher
fetcher
fetcher
Classes
struct fetcher_t
Typedefs
typedef struct fetcher_t fetcher_t
typedef enum fetcher_option_t fetcher_option_t
typedef fetcher_t *(* fetcher_constructor_t)()
typedef bool(* fetcher_callback_t)(void *userdata, chunk_t chunk)
Enumerations
enum fetcher_option_t {
FETCH_REQUEST_DATA, FETCH_REQUEST_TYPE, FETCH_REQUEST_HEADER, FETCH_HTTP_VERSION_1_0,
FETCH_TIMEOUT, FETCH_RESPONSE_CODE, FETCH_CALLBACK, FETCH_SOURCEIP,
FETCH_END
}
Functions
bool fetcher_default_callback (void *userdata, chunk_t chunk)
Detailed Description
Typedef Documentation
typedef bool(* fetcher_callback_t)(void *userdata, chunk_t chunk)
Callback function used with FETCH_CALLBACK.
Parameters
userdata userdata passed to fetcher_t.fetch()
chunk chunk with next chunk of data
Returns
TRUE to continue with transfer, FALSE to abort
Definition at line 45 of file fetcher.h.
typedef fetcher_t*(* fetcher_constructor_t)()
Constructor function which creates fetcher instances.
Returns
fetcher instance
Definition at line 36 of file fetcher.h.
typedef enum fetcher_option_t fetcher_option_t
Definition at line 26 of file fetcher.h.
typedef struct fetcher_t fetcher_t
Definition at line 25 of file fetcher.h.
Enumeration Type Documentation
enum fetcher_option_t
Fetching options to use for fetcher_t.fetch() call.
Enumerator
FETCH_REQUEST_DATA
Data to include in fetch request, e.g. on a HTTP post. Additional argument is a chunk_t
FETCH_REQUEST_TYPE
Mime-Type of data included in FETCH_REQUEST_DATA. Additional argument is a char*.
FETCH_REQUEST_HEADER
HTTP header to be sent with with the fetch request. Additional argument is a char*.
FETCH_HTTP_VERSION_1_0
Use HTTP Version 1.0 instead of 1.1. No additional argument is needed.
FETCH_TIMEOUT
Timeout to use for fetch, in seconds. Additional argument is u_int
FETCH_RESPONSE_CODE
Sets a pointer to a variable that receives the request's response code. Additional argument is a u_int*.
FETCH_CALLBACK
Callback to invoke with each chunk of data. Additional argument fetch_callback_t. If this option is not given, the fetcher_default_callback is used, which accumulates the data into an allocated chunk.
FETCH_SOURCEIP
Source IP address to bind for a fetch. Additional argument is a host_t*, which may be NULL.
FETCH_END
end of fetching options
Definition at line 52 of file fetcher.h.
                       {
     FETCH_REQUEST_DATA,
     FETCH_REQUEST_TYPE,
     FETCH_REQUEST_HEADER,
     FETCH_HTTP_VERSION_1_0,
     FETCH_TIMEOUT,
     FETCH_RESPONSE_CODE,
     FETCH_CALLBACK,
     FETCH_SOURCEIP,
     FETCH_END,
 };
Function Documentation
bool fetcher_default_callback (void * userdata, chunk_t chunk)
Default fetcher callback function, accumulates data to a chunk.
Parameters
userdata chunk for allocated data, empty on first invocation
chunk current chunk of data
Returns
FALSE if chunk too large to allocate
See header.
Definition at line 21 of file fetcher.c.
References FALSE, chunk_t::len, memcpy, chunk_t::ptr, and TRUE.
Referenced by curl_fetcher_create(), files_fetcher_create(), METHOD(), read_result(), soup_fetcher_create(), and winhttp_fetcher_create().
 {
     chunk_t *accu = userdata;
     accu->ptr = realloc(accu->ptr, accu->len + chunk.len);
     if (accu->ptr)
     {
         memcpy(&accu->ptr[accu->len], chunk.ptr, chunk.len);
         accu->len += chunk.len;
         return TRUE;
     }
     return FALSE;
 }