strongSwan: ipseckey_t Struct Reference
ipseckey_t Struct Reference
ipseckey
#include "ipseckey.h"
Public Attributes
u_int8_t(* get_precedence)(ipseckey_t *this)
ipseckey_gw_type_t(* get_gateway_type)(ipseckey_t *this)
ipseckey_algorithm_t(* get_algorithm)(ipseckey_t *this)
chunk_t(* get_gateway)(ipseckey_t *this)
chunk_t(* get_public_key)(ipseckey_t *this)
void(* destroy)(ipseckey_t *this)
Detailed Description
An IPSECKEY.
Represents an IPSECKEY as defined in RFC 4025:
 0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | precedence | gateway type | algorithm | gateway | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+----------—+ + ~ gateway ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | / / public key / / / +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-|
Note: RFC 4025 defines that the algorithm field has a length of 7 bits. We use 8 bits instead, because the use of 7 bits is very uncommon in internet protocols and might be an error in RFC 4025 (also the BIND DNS server uses 8 bits for the algorithm field of the IPSECKEY resource records).
Definition at line 81 of file ipseckey.h.
Member Data Documentation
void(* ipseckey_t::destroy)(ipseckey_t *this)
Destroy the IPSECKEY.
Definition at line 138 of file ipseckey.h.
Referenced by METHOD().
ipseckey_algorithm_t(* ipseckey_t::get_algorithm)(ipseckey_t *this)
Get the algorithm.
The "algorithm" determines the format of the public key field of the IPSECKEY.
Returns
algorithm
Definition at line 108 of file ipseckey.h.
Referenced by METHOD().
chunk_t(* ipseckey_t::get_gateway)(ipseckey_t *this)
Get the content of the gateway field as chunk.
The content is in network byte order and its format depends on the gateway type.
The data pointed by the chunk is still owned by the IPSECKEY. Clone it if necessary.
Returns
gateway field as chunk
Definition at line 121 of file ipseckey.h.
ipseckey_gw_type_t(* ipseckey_t::get_gateway_type)(ipseckey_t *this)
Get the type of the gateway.
The "gateway type" determines the format of the gateway field of the IPSECKEY.
Returns
gateway type
Definition at line 98 of file ipseckey.h.
u_int8_t(* ipseckey_t::get_precedence)(ipseckey_t *this)
Get the precedence of the IPSECKEY.
Returns
precedence
Definition at line 88 of file ipseckey.h.
chunk_t(* ipseckey_t::get_public_key)(ipseckey_t *this)
Get the content of the public key field as chunk.
The format of the public key depends on the algorithm type.
The data pointed by the chunk is still owned by the IPSECKEY. Clone it if necessary.
Returns
public key field as chunk
Definition at line 133 of file ipseckey.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
ipseckey.h