strongSwan: generic_attr_chunk
generic_attr_chunk
generic_attr
Classes
struct generic_attr_chunk_t
Typedefs
typedef struct generic_attr_chunk_t generic_attr_chunk_t
Functions
pa_tnc_attr_t * generic_attr_chunk_create (chunk_t string, pen_type_t type)
pa_tnc_attr_t * generic_attr_chunk_create_from_data (size_t length, chunk_t value, size_t size, pen_type_t type)
Detailed Description
Typedef Documentation
typedef struct generic_attr_chunk_t generic_attr_chunk_t
Definition at line 24 of file generic_attr_chunk.h.
Function Documentation
pa_tnc_attr_t* generic_attr_chunk_create (chunk_t value, pen_type_t type)
Creates a generic_attr_chunk_t object
Parameters
string Non-nul terminated string
type Vendor ID / Attribute Type
Described in header.
Definition at line 177 of file generic_attr_chunk.c.
References generic_attr_chunk_create_from_data(), and chunk_t::len.
Referenced by add_certification_state(), add_configuration_state(), and add_quadruple().
 {
     return generic_attr_chunk_create_from_data(value.len, value,
                                                value.len, type);
 }
pa_tnc_attr_t* generic_attr_chunk_create_from_data (size_t length, chunk_t value, size_t size, pen_type_t type)
Creates an generic_attr_chunk_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
size size in bytes if fixed array or 0 if dynamic size
type Vendor ID / Attribute Type
Described in header.
Definition at line 145 of file generic_attr_chunk.c.
References chunk_clone, INIT, length, size, and type.
Referenced by generic_attr_chunk_create(), and pwg_attr_create_from_data().
 {
     private_generic_attr_chunk_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .type = type,
         .length = length,
         .size = size,
         .value = chunk_clone(value),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }