strongSwan: tcg_pts_attr_file_meas.c File Reference
tcg_pts_attr_file_meas.c File Reference
#include "tcg_pts_attr_file_meas.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
Classes
struct private_tcg_pts_attr_file_meas_t
Macros
#define PTS_FILE_MEAS_SIZE 12
Typedefs
typedef struct
private_tcg_pts_attr_file_meas_t private_tcg_pts_attr_file_meas_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_tcg_pts_attr_file_meas_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_tcg_pts_attr_file_meas_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_tcg_pts_attr_file_meas_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_tcg_pts_attr_file_meas_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_tcg_pts_attr_file_meas_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_tcg_pts_attr_file_meas_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_tcg_pts_attr_file_meas_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_tcg_pts_attr_file_meas_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_tcg_pts_attr_file_meas_t *this)
METHOD (tcg_pts_attr_file_meas_t, get_measurements, pts_file_meas_t *, private_tcg_pts_attr_file_meas_t *this)
pa_tnc_attr_t * tcg_pts_attr_file_meas_create (pts_file_meas_t *measurements)
pa_tnc_attr_t * tcg_pts_attr_file_meas_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define PTS_FILE_MEAS_SIZE 12
File Measurement see section 3.19.2 of PTS Protocol: Binding to TNC IF-M Specification
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Number of Files included | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Number of Files included | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Request ID | Measurement Length | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Measurement #1 (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Filename Length | Filename (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Filename (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Measurement #2 (Variable Length) | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Filename Length | Filename (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Filename (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ...........................
Definition at line 55 of file tcg_pts_attr_file_meas.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_tcg_pts_attr_file_meas_t private_tcg_pts_attr_file_meas_t
Definition at line 25 of file tcg_pts_attr_file_meas.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_tcg_pts_attr_file_meas_t * this)
Definition at line 123 of file tcg_pts_attr_file_meas.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_tcg_pts_attr_file_meas_t * this)
Definition at line 129 of file tcg_pts_attr_file_meas.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_tcg_pts_attr_file_meas_t * this)
Definition at line 135 of file tcg_pts_attr_file_meas.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_tcg_pts_attr_file_meas_t * this, bool noskip)
Definition at line 141 of file tcg_pts_attr_file_meas.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_tcg_pts_attr_file_meas_t * this)
Definition at line 147 of file tcg_pts_attr_file_meas.c.
References bio_writer_create(), chunk_create(), count, enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::extract_buf, FALSE, chunk_t::len, length, PTS_FILE_MEAS_SIZE, segment, TRUE, value, bio_writer_t::write_data, bio_writer_t::write_data16, bio_writer_t::write_uint16, and bio_writer_t::write_uint64.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     u_int64_t count;
     u_int16_t request_id;
     char *filename;
     chunk_t measurement;
     bool first = TRUE;
     if (this->value.ptr)
     {
         return;
     }
     count = this->measurements->get_file_count(this->measurements);
     request_id = this->measurements->get_request_id(this->measurements);
     writer = bio_writer_create(PTS_FILE_MEAS_SIZE);
     writer->write_uint64(writer, count);
     writer->write_uint16(writer, request_id);
     enumerator = this->measurements->create_enumerator(this->measurements);
     while (enumerator->enumerate(enumerator, &filename, &measurement))
     {
         if (first)
         {
             writer->write_uint16(writer, measurement.len);
             first = FALSE;
         }
         writer->write_data  (writer, measurement);
         writer->write_data16(writer, chunk_create(filename, strlen(filename)));
     }
     enumerator->destroy(enumerator);
     if (first)
     {
         /* no attached measurements */
         writer->write_uint16(writer, 0);
     }
     this->value = writer->extract_buf(writer);
     this->segment = this->value;
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_tcg_pts_attr_file_meas_t * this, u_int32_t * offset)
Definition at line 194 of file tcg_pts_attr_file_meas.c.
References bio_reader_create(), BUF_LEN, count, DBG1, DBG_TNC, bio_reader_t::destroy, end, FAILED, chunk_t::len, len, length, memcpy, min, NEED_MORE, offset, bio_reader_t::peek, pen_names, PEN_TCG, chunk_t::ptr, pts_file_meas_create(), PTS_FILE_MEAS_SIZE, bio_reader_t::read_data, bio_reader_t::read_data16, bio_reader_t::read_uint16, bio_reader_t::read_uint64, bio_reader_t::remaining, status, SUCCESS, tcg_attr_names, type, and value.
 {
     bio_reader_t *reader;
     chunk_t measurement, filename;
     status_t status = NEED_MORE;
     char buf[BUF_LEN];
     size_t len;
     if (this->offset == 0)
     {
         if (this->length < PTS_FILE_MEAS_SIZE)
         {
             DBG1(DBG_TNC, "insufficient data for %N/%N", pen_names, PEN_TCG,
                            tcg_attr_names, this->type.type);
             *offset = this->offset;
             return FAILED;
         }
         if (this->value.len < PTS_FILE_MEAS_SIZE)
         {
             return NEED_MORE;
         }
         reader = bio_reader_create(this->value);
         reader->read_uint64(reader, &this->count);
         reader->read_uint16(reader, &this->request_id);
         reader->read_uint16(reader, &this->meas_len);
         this->offset = PTS_FILE_MEAS_SIZE;
         this->value = reader->peek(reader);
         reader->destroy(reader);
     }
     this->measurements = pts_file_meas_create(this->request_id);
     reader = bio_reader_create(this->value);
     while (this->count)
     {
         if (!reader->read_data(reader, this->meas_len, &measurement) ||
             !reader->read_data16(reader, &filename))
         {
             goto end;
         }
         this->offset += this->value.len - reader->remaining(reader);
         this->value = reader->peek(reader);
         len = min(filename.len, BUF_LEN-1);
         memcpy(buf, filename.ptr, len);
         buf[len] = '\0';
         this->measurements->add(this->measurements, buf, measurement);
         this->count--;
     }
     status = SUCCESS;
     if (this->length != this->offset)
     {
         DBG1(DBG_TNC, "inconsistent length for %N/%N", pen_names, PEN_TCG,
                        tcg_attr_names, this->type.type);
         *offset = this->offset;
         status = FAILED;
     }
 end:
     reader->destroy(reader);
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_tcg_pts_attr_file_meas_t * this, chunk_t segment)
Definition at line 260 of file tcg_pts_attr_file_meas.c.
References chunk_cat, chunk_free(), and value.
 {
     this->value = chunk_cat("cc", this->value, segment);
     chunk_free(&this->segment);
     this->segment = this->value;
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_tcg_pts_attr_file_meas_t * this)
Definition at line 268 of file tcg_pts_attr_file_meas.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_tcg_pts_attr_file_meas_t * this)
Definition at line 274 of file tcg_pts_attr_file_meas.c.
References DESTROY_IF, free(), chunk_t::ptr, ref_put(), and segment.
 {
     if (ref_put(&this->ref))
     {
         DESTROY_IF(this->measurements);
         free(this->segment.ptr);
         free(this);
     }
 }
METHOD (tcg_pts_attr_file_meas_t , get_measurements , pts_file_meas_t * , private_tcg_pts_attr_file_meas_t * this)
Definition at line 285 of file tcg_pts_attr_file_meas.c.
 {
     return this->measurements;
 }