strongSwan: test_mgf1.c File Reference
test_mgf1.c File Reference
#include "test_suite.h"
#include <tests/utils/test_rng.h>
#include <utils/test.h>
#include <crypto/mgf1/mgf1.h>
#include <crypto/mgf1/mgf1_bitspender.h>
Classes
struct mgf1_test_t
Functions
START_TEST (mgf1_test_mgf1)
END_TEST START_TEST (mgf1_test_bitspender)
END_TEST Suite * mgf1_suite_create (char *name, int n)
Suite * mgf1_sha1_suite_create ()
Suite * mgf1_sha256_suite_create ()
Variables
mgf1_test_t mgf1_tests []
Function Documentation
Suite* mgf1_sha1_suite_create ()
Definition at line 260 of file test_mgf1.c.
References mgf1_suite_create().
 {
     return mgf1_suite_create("mgf1-sha1", 0);
 }
Suite* mgf1_sha256_suite_create ()
Definition at line 265 of file test_mgf1.c.
References mgf1_suite_create().
 {
     return mgf1_suite_create("mgf1-sha256", 1);
 }
END_TEST Suite* mgf1_suite_create (char * name, int n)
Definition at line 242 of file test_mgf1.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, and tcase_create.
Referenced by mgf1_sha1_suite_create(), and mgf1_sha256_suite_create().
 {
     Suite *s;
     TCase *tc;
     s = suite_create(name);
     tc = tcase_create("mgf1");
     tcase_add_loop_test(tc, mgf1_test_mgf1, n, n + 1);
     suite_add_tcase(s, tc);
     tc = tcase_create("bitspender");
     tcase_add_loop_test(tc, mgf1_test_bitspender, n, n + 1);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (mgf1_test_mgf1)
Definition at line 128 of file test_mgf1.c.
References alg, mgf1_t::allocate_mask, chunk_empty, chunk_equals(), chunk_free(), chunk_skip(), ck_assert, mgf1_t::destroy, FALSE, mgf1_t::get_hash_size, mgf1_t::get_mask, mgf1_test_t::hash_size, HASH_UNKNOWN, chunk_t::len, mgf1_test_t::mask, mask, mgf1_create(), mgf1_test_t::ml1, mgf1_test_t::ml2, mgf1_test_t::ml3, chunk_t::ptr, and TRUE.
 {
     mgf1_t *mgf1;
     chunk_t mask, mask1, mask2, mask3;
     mask1 = mgf1_tests[_i].mask;
     mask2 = chunk_skip(mask1, mgf1_tests[_i].ml1);
     mask3 = chunk_skip(mask2, mgf1_tests[_i].ml2);
     mask1.len = mgf1_tests[_i].ml1;
     mask2.len = mgf1_tests[_i].ml2;
     mask3.len = mgf1_tests[_i].ml3;
     mgf1 = mgf1_create(HASH_UNKNOWN, mgf1_tests[_i].seed, TRUE);
     ck_assert(mgf1 == NULL);
     mgf1 = mgf1_create(mgf1_tests[_i].alg, chunk_empty, TRUE);
     ck_assert(mgf1 == NULL);
     /* return mask in allocated chunk */
     mgf1 = mgf1_create(mgf1_tests[_i].alg, mgf1_tests[_i].seed, TRUE);
     ck_assert(mgf1);
     /* check hash size */
     ck_assert(mgf1->get_hash_size(mgf1) == mgf1_tests[_i].hash_size);
     /* get zero number of octets */
     ck_assert(mgf1->allocate_mask(mgf1, 0, &mask));
     ck_assert(mask.len == 0 && mask.ptr == NULL);
     /* get non-zero number of octets */
     ck_assert(mgf1->allocate_mask(mgf1, mgf1_tests[_i].mask.len, &mask));
     ck_assert(chunk_equals(mask, mgf1_tests[_i].mask));
     mgf1->destroy(mgf1);
     /* copy mask to pre-allocated buffer */
     mgf1 = mgf1_create(mgf1_tests[_i].alg, mgf1_tests[_i].seed, TRUE);
     ck_assert(mgf1);
     ck_assert(mgf1->get_mask(mgf1, mgf1_tests[_i].mask.len, mask.ptr));
     ck_assert(chunk_equals(mask, mgf1_tests[_i].mask));
     mgf1->destroy(mgf1);
     /* get mask in batches without hashing the seed */
     mgf1 = mgf1_create(mgf1_tests[_i].alg, mgf1_tests[_i].hashed_seed, FALSE);
     ck_assert(mgf1);
     /* first batch */
     ck_assert(mgf1->get_mask(mgf1, mask1.len, mask.ptr));
     mask.len = mask1.len;
     ck_assert(chunk_equals(mask, mask1));
     /* second batch */
     ck_assert(mgf1->get_mask(mgf1, mask2.len, mask.ptr));
     mask.len = mask2.len;
     ck_assert(chunk_equals(mask, mask2));
     /* third batch */
     ck_assert(mgf1->get_mask(mgf1, mask3.len, mask.ptr));
     mask.len = mask3.len;
     ck_assert(chunk_equals(mask, mask3));
     mgf1->destroy(mgf1);
     chunk_free(&mask);
 }
END_TEST START_TEST (mgf1_test_bitspender)
Definition at line 193 of file test_mgf1.c.
References alg, bits, ck_assert, DBG1, DBG_LIB, mgf1_bitspender_t::destroy, FALSE, mgf1_bitspender_t::get_bits, mgf1_bitspender_t::get_byte, HASH_UNKNOWN, and mgf1_bitspender_create().
 {
     mgf1_bitspender_t *bitspender;
     uint32_t bits;
     uint8_t byte;
     int j;
     bitspender = mgf1_bitspender_create(HASH_UNKNOWN,
                                         mgf1_tests[_i].hashed_seed, FALSE);
     ck_assert(bitspender == NULL);
     bitspender = mgf1_bitspender_create(mgf1_tests[_i].alg,
                                         mgf1_tests[_i].hashed_seed, FALSE);
     ck_assert(bitspender);
     for (j = 0; j < 15; j++)
     {
         ck_assert(bitspender->get_bits(bitspender, j, &bits));
         DBG1(DBG_LIB, "bits[%d] = %u, bits = %u", j, mgf1_tests[_i].bits[j],
                        bits);
         ck_assert(bits == mgf1_tests[_i].bits[j]);
     }
     ck_assert(!bitspender->get_bits(bitspender, 33, &bits));
     for (j = 15; j < 20; j++)
     {
         ck_assert(bitspender->get_byte(bitspender, &byte));
         DBG1(DBG_LIB, "bits[%d] = 0x%02x, byte = 0x%02x", j,
                    mgf1_tests[_i].bits[j], byte);
         ck_assert(byte == mgf1_tests[_i].bits[j]);
     }
     j = 20; /* 23 remaining bits */
     ck_assert(bitspender->get_bits(bitspender, 23, &bits));
     DBG1(DBG_LIB, "bits[%d] = %u, bits = %u", j,
                    mgf1_tests[_i].bits[j], bits);
     ck_assert(bits == mgf1_tests[_i].bits[j]);
     j = 21; /* 32 aligned bits */
     ck_assert(bitspender->get_bits(bitspender, 32, &bits));
     DBG1(DBG_LIB, "bits[%d] = 0x%08x, bits = 0x%08x", j,
                    mgf1_tests[_i].bits[j], bits);
     ck_assert(bits == mgf1_tests[_i].bits[j]);
     bitspender->destroy(bitspender);
 }
Variable Documentation
mgf1_test_t mgf1_tests[]
MGF1 Mask Generation Function Test Vectors
Definition at line 36 of file test_mgf1.c.