strongSwan: tls_server.c File Reference
tls_server.c File Reference
#include "tls_server.h"
#include <time.h>
#include <utils/debug.h>
#include <credentials/certificates/x509.h>
Classes
struct private_tls_server_t
Macros
#define SESSION_ID_SIZE 16
Typedefs
typedef struct private_tls_server_t private_tls_server_t
Enumerations
enum server_state_t {
STATE_INIT, STATE_HELLO_RECEIVED, STATE_HELLO_SENT, STATE_CERT_SENT,
STATE_KEY_EXCHANGE_SENT, STATE_CERTREQ_SENT, STATE_HELLO_DONE, STATE_CERT_RECEIVED,
STATE_KEY_EXCHANGE_RECEIVED, STATE_CERT_VERIFY_RECEIVED, STATE_CIPHERSPEC_CHANGED_IN, STATE_FINISHED_RECEIVED,
STATE_CIPHERSPEC_CHANGED_OUT, STATE_FINISHED_SENT
}
Functions
static bool select_suite_and_key (private_tls_server_t *this, tls_cipher_suite_t *suites, int count)
static status_t process_client_hello (private_tls_server_t *this, bio_reader_t *reader)
static status_t process_certificate (private_tls_server_t *this, bio_reader_t *reader)
static status_t process_key_exchange_encrypted (private_tls_server_t *this, bio_reader_t *reader)
static status_t process_key_exchange_dhe (private_tls_server_t *this, bio_reader_t *reader)
static status_t process_key_exchange (private_tls_server_t *this, bio_reader_t *reader)
static status_t process_cert_verify (private_tls_server_t *this, bio_reader_t *reader)
static status_t process_finished (private_tls_server_t *this, bio_reader_t *reader)
METHOD (tls_handshake_t, process, status_t, private_tls_server_t *this, tls_handshake_type_t type, bio_reader_t *reader)
static status_t send_server_hello (private_tls_server_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_certificate (private_tls_server_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_certificate_request (private_tls_server_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static tls_named_curve_t ec_group_to_curve (private_tls_server_t *this, diffie_hellman_group_t group)
bool peer_supports_curve (private_tls_server_t *this, tls_named_curve_t curve)
static bool find_supported_curve (private_tls_server_t *this, tls_named_curve_t *curve)
static status_t send_server_key_exchange (private_tls_server_t *this, tls_handshake_type_t *type, bio_writer_t *writer, diffie_hellman_group_t group)
static status_t send_hello_done (private_tls_server_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_finished (private_tls_server_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
METHOD (tls_handshake_t, build, status_t, private_tls_server_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
METHOD (tls_handshake_t, cipherspec_changed, bool, private_tls_server_t *this, bool inbound)
METHOD (tls_handshake_t, change_cipherspec, void, private_tls_server_t *this, bool inbound)
METHOD (tls_handshake_t, finished, bool, private_tls_server_t *this)
METHOD (tls_handshake_t, get_peer_id, identification_t *, private_tls_server_t *this)
METHOD (tls_handshake_t, get_server_id, identification_t *, private_tls_server_t *this)
METHOD (tls_handshake_t, get_auth, auth_cfg_t *, private_tls_server_t *this)
METHOD (tls_handshake_t, destroy, void, private_tls_server_t *this)
tls_server_t * tls_server_create (tls_t *tls, tls_crypto_t *crypto, tls_alert_t *alert, identification_t *server, identification_t *peer)
Macro Definition Documentation
#define SESSION_ID_SIZE 16
Size of a session ID
Definition at line 28 of file tls_server.c.
Referenced by process_client_hello().
Typedef Documentation
typedef struct private_tls_server_t private_tls_server_t
Definition at line 23 of file tls_server.c.
Enumeration Type Documentation
enum server_state_t
Enumerator
STATE_INIT
STATE_HELLO_RECEIVED
STATE_HELLO_SENT
STATE_CERT_SENT
STATE_KEY_EXCHANGE_SENT
STATE_CERTREQ_SENT
STATE_HELLO_DONE
STATE_CERT_RECEIVED
STATE_KEY_EXCHANGE_RECEIVED
STATE_CERT_VERIFY_RECEIVED
STATE_CIPHERSPEC_CHANGED_IN
STATE_FINISHED_RECEIVED
STATE_CIPHERSPEC_CHANGED_OUT
STATE_FINISHED_SENT
Definition at line 30 of file tls_server.c.
              {
     STATE_INIT,
     STATE_HELLO_RECEIVED,
     STATE_HELLO_SENT,
     STATE_CERT_SENT,
     STATE_KEY_EXCHANGE_SENT,
     STATE_CERTREQ_SENT,
     STATE_HELLO_DONE,
     STATE_CERT_RECEIVED,
     STATE_KEY_EXCHANGE_RECEIVED,
     STATE_CERT_VERIFY_RECEIVED,
     STATE_CIPHERSPEC_CHANGED_IN,
     STATE_FINISHED_RECEIVED,
     STATE_CIPHERSPEC_CHANGED_OUT,
     STATE_FINISHED_SENT,
 } server_state_t;
Function Documentation
static tls_named_curve_t ec_group_to_curve (private_tls_server_t * this, diffie_hellman_group_t group) static
Get the TLS curve of a given EC DH group
Definition at line 808 of file tls_server.c.
References curve, enumerator_t::destroy, and enumerator_t::enumerate.
Referenced by send_server_key_exchange().
 {
     diffie_hellman_group_t current;
     tls_named_curve_t curve;
     enumerator_t *enumerator;
     enumerator = this->crypto->create_ec_enumerator(this->crypto);
     while (enumerator->enumerate(enumerator, &current, &curve))
     {
         if (current == group)
         {
             enumerator->destroy(enumerator);
             return curve;
         }
     }
     enumerator->destroy(enumerator);
     return 0;
 }
static bool find_supported_curve (private_tls_server_t * this, tls_named_curve_t * curve) static
Try to find a curve supported by both, client and server
Definition at line 856 of file tls_server.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, peer_supports_curve(), and TRUE.
Referenced by send_server_key_exchange().
 {
     tls_named_curve_t current;
     enumerator_t *enumerator;
     enumerator = this->crypto->create_ec_enumerator(this->crypto);
     while (enumerator->enumerate(enumerator, NULL, &current))
     {
         if (peer_supports_curve(this, current))
         {
             *curve = current;
             enumerator->destroy(enumerator);
             return TRUE;
         }
     }
     enumerator->destroy(enumerator);
     return FALSE;
 }
METHOD (tls_handshake_t , process , status_t , private_tls_server_t * this, tls_handshake_type_t type, bio_reader_t * reader)
Definition at line 622 of file tls_server.c.
References DBG1, DBG_TLS, expected, INVALID_STATE, NEED_MORE, process_cert_verify(), process_certificate(), process_client_hello(), process_finished(), process_key_exchange(), STATE_CERT_RECEIVED, STATE_CIPHERSPEC_CHANGED_IN, STATE_HELLO_DONE, STATE_INIT, STATE_KEY_EXCHANGE_RECEIVED, TLS_CERTIFICATE, TLS_CERTIFICATE_VERIFY, TLS_CLIENT_HELLO, TLS_CLIENT_KEY_EXCHANGE, TLS_FATAL, TLS_FINISHED, tls_handshake_type_names, and TLS_UNEXPECTED_MESSAGE.
 {
     tls_handshake_type_t expected;
     switch (this->state)
     {
         case STATE_INIT:
             if (type == TLS_CLIENT_HELLO)
             {
                 return process_client_hello(this, reader);
             }
             expected = TLS_CLIENT_HELLO;
             break;
         case STATE_HELLO_DONE:
             if (type == TLS_CERTIFICATE)
             {
                 return process_certificate(this, reader);
             }
             if (this->peer)
             {
                 expected = TLS_CERTIFICATE;
                 break;
             }
             /* otherwise fall through to next state */
         case STATE_CERT_RECEIVED:
             if (type == TLS_CLIENT_KEY_EXCHANGE)
             {
                 return process_key_exchange(this, reader);
             }
             expected = TLS_CLIENT_KEY_EXCHANGE;
             break;
         case STATE_KEY_EXCHANGE_RECEIVED:
             if (type == TLS_CERTIFICATE_VERIFY)
             {
                 return process_cert_verify(this, reader);
             }
             if (this->peer)
             {
                 expected = TLS_CERTIFICATE_VERIFY;
                 break;
             }
             return INVALID_STATE;
         case STATE_CIPHERSPEC_CHANGED_IN:
             if (type == TLS_FINISHED)
             {
                 return process_finished(this, reader);
             }
             expected = TLS_FINISHED;
             break;
         default:
             DBG1(DBG_TLS, "TLS %N not expected in current state",
                  tls_handshake_type_names, type);
             this->alert->add(this->alert, TLS_FATAL, TLS_UNEXPECTED_MESSAGE);
             return NEED_MORE;
     }
     DBG1(DBG_TLS, "TLS %N expected, but received %N",
          tls_handshake_type_names, expected, tls_handshake_type_names, type);
     this->alert->add(this->alert, TLS_FATAL, TLS_UNEXPECTED_MESSAGE);
     return NEED_MORE;
 }
METHOD (tls_handshake_t , build , status_t , private_tls_server_t * this, tls_handshake_type_t * type, bio_writer_t * writer)
Definition at line 993 of file tls_server.c.
References group, INVALID_STATE, send_certificate(), send_certificate_request(), send_finished(), send_hello_done(), send_server_hello(), send_server_key_exchange(), STATE_CERT_SENT, STATE_CERTREQ_SENT, STATE_CIPHERSPEC_CHANGED_OUT, STATE_FINISHED_SENT, STATE_HELLO_RECEIVED, STATE_HELLO_SENT, and STATE_KEY_EXCHANGE_SENT.
 {
     diffie_hellman_group_t group;
     switch (this->state)
     {
         case STATE_HELLO_RECEIVED:
             return send_server_hello(this, type, writer);
         case STATE_HELLO_SENT:
             return send_certificate(this, type, writer);
         case STATE_CERT_SENT:
             group = this->crypto->get_dh_group(this->crypto);
             if (group)
             {
                 return send_server_key_exchange(this, type, writer, group);
             }
             /* otherwise fall through to next state */
         case STATE_KEY_EXCHANGE_SENT:
             return send_certificate_request(this, type, writer);
         case STATE_CERTREQ_SENT:
             return send_hello_done(this, type, writer);
         case STATE_CIPHERSPEC_CHANGED_OUT:
             return send_finished(this, type, writer);
         case STATE_FINISHED_SENT:
             return INVALID_STATE;
         default:
             return INVALID_STATE;
     }
 }
METHOD (tls_handshake_t , cipherspec_changed , bool , private_tls_server_t * this, bool inbound)
Definition at line 1024 of file tls_server.c.
References FALSE, STATE_CERT_VERIFY_RECEIVED, STATE_FINISHED_RECEIVED, STATE_FINISHED_SENT, STATE_HELLO_SENT, and STATE_KEY_EXCHANGE_RECEIVED.
 {
     if (inbound)
     {
         if (this->resume)
         {
             return this->state == STATE_FINISHED_SENT;
         }
         if (this->peer)
         {
             return this->state == STATE_CERT_VERIFY_RECEIVED;
         }
         return this->state == STATE_KEY_EXCHANGE_RECEIVED;
     }
     else
     {
         if (this->resume)
         {
             return this->state == STATE_HELLO_SENT;
         }
         return this->state == STATE_FINISHED_RECEIVED;
     }
     return FALSE;
 }
METHOD (tls_handshake_t , change_cipherspec , void , private_tls_server_t * this, bool inbound)
Definition at line 1050 of file tls_server.c.
References STATE_CIPHERSPEC_CHANGED_IN, and STATE_CIPHERSPEC_CHANGED_OUT.
 {
     this->crypto->change_cipher(this->crypto, inbound);
     if (inbound)
     {
         this->state = STATE_CIPHERSPEC_CHANGED_IN;
     }
     else
     {
         this->state = STATE_CIPHERSPEC_CHANGED_OUT;
     }
 }
METHOD (tls_handshake_t , finished , bool , private_tls_server_t * this)
Definition at line 1064 of file tls_server.c.
References STATE_FINISHED_RECEIVED, and STATE_FINISHED_SENT.
 {
     if (this->resume)
     {
         return this->state == STATE_FINISHED_RECEIVED;
     }
     return this->state == STATE_FINISHED_SENT;
 }
METHOD (tls_handshake_t , get_peer_id , identification_t * , private_tls_server_t * this)
Definition at line 1074 of file tls_server.c.
 {
     return this->peer;
 }
METHOD (tls_handshake_t , get_server_id , identification_t * , private_tls_server_t * this)
Definition at line 1080 of file tls_server.c.
References server.
 {
     return this->server;
 }
METHOD (tls_handshake_t , get_auth , auth_cfg_t * , private_tls_server_t * this)
Definition at line 1086 of file tls_server.c.
 {
     return this->peer_auth;
 }
METHOD (tls_handshake_t , destroy , void , private_tls_server_t * this)
Definition at line 1092 of file tls_server.c.
References curves, DESTROY_IF, dh, free(), and server.
 {
     DESTROY_IF(this->private);
     DESTROY_IF(this->dh);
     DESTROY_IF(this->peer);
     this->server->destroy(this->server);
     this->peer_auth->destroy(this->peer_auth);
     this->server_auth->destroy(this->server_auth);
     free(this->hashsig.ptr);
     free(this->curves.ptr);
     free(this->session.ptr);
     free(this);
 }
bool peer_supports_curve (private_tls_server_t * this, tls_named_curve_t curve)
Check if the peer supports a given TLS curve
Definition at line 831 of file tls_server.c.
References bio_reader_create(), curves, bio_reader_t::destroy, FALSE, bio_reader_t::read_uint16, bio_reader_t::remaining, and TRUE.
Referenced by find_supported_curve(), and send_server_key_exchange().
 {
     bio_reader_t *reader;
     u_int16_t current;
     if (!this->curves_received)
     {   /* none received, assume yes */
         return TRUE;
     }
     reader = bio_reader_create(this->curves);
     while (reader->remaining(reader) && reader->read_uint16(reader, &current))
     {
         if (current == curve)
         {
             reader->destroy(reader);
             return TRUE;
         }
     }
     reader->destroy(reader);
     return FALSE;
 }
static status_t process_cert_verify (private_tls_server_t * this, bio_reader_t * reader) static
Process Certificate verify
Definition at line 541 of file tls_server.c.
References bio_reader_create(), credential_manager_t::create_public_enumerator, library_t::credmgr, DBG1, DBG_TLS, enumerator_t::destroy, bio_reader_t::destroy, enumerator_t::enumerate, FALSE, KEY_ANY, lib, NEED_MORE, bio_reader_t::peek, sig, STATE_CERT_VERIFY_RECEIVED, STATE_KEY_EXCHANGE_RECEIVED, TLS_CERTIFICATE_UNKNOWN, TLS_CERTIFICATE_VERIFY, and TLS_FATAL.
Referenced by METHOD().
 {
     bool verified = FALSE;
     enumerator_t *enumerator;
     public_key_t *public;
     auth_cfg_t *auth;
     bio_reader_t *sig;
     enumerator = lib->credmgr->create_public_enumerator(lib->credmgr,
                                         KEY_ANY, this->peer, this->peer_auth);
     while (enumerator->enumerate(enumerator, &public, &auth))
     {
         sig = bio_reader_create(reader->peek(reader));
         verified = this->crypto->verify_handshake(this->crypto, public, sig);
         sig->destroy(sig);
         if (verified)
         {
             this->peer_auth->merge(this->peer_auth, auth, FALSE);
             break;
         }
         DBG1(DBG_TLS, "signature verification failed, trying another key");
     }
     enumerator->destroy(enumerator);
     if (!verified)
     {
         DBG1(DBG_TLS, "no trusted certificate found for '%Y' to verify TLS peer",
              this->peer);
         if (!this->peer_auth_optional)
         {   /* client authentication is required */
             this->alert->add(this->alert, TLS_FATAL, TLS_CERTIFICATE_UNKNOWN);
             return NEED_MORE;
         }
         /* reset peer identity, we couldn't authenticate it */
         this->peer->destroy(this->peer);
         this->peer = NULL;
         this->state = STATE_KEY_EXCHANGE_RECEIVED;
     }
     else
     {
         this->state = STATE_CERT_VERIFY_RECEIVED;
     }
     this->crypto->append_handshake(this->crypto,
                                    TLS_CERTIFICATE_VERIFY, reader->peek(reader));
     return NEED_MORE;
 }
static status_t process_certificate (private_tls_server_t * this, bio_reader_t * reader) static
Process certificate
Definition at line 337 of file tls_server.c.
References AUTH_HELPER_IM_CERT, AUTH_HELPER_SUBJECT_CERT, bio_reader_create(), BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, identification_t::clone, credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, data, DBG1, DBG_TLS, bio_reader_t::destroy, FALSE, certificate_t::get_subject, lib, NEED_MORE, bio_reader_t::peek, bio_reader_t::read_data24, bio_reader_t::remaining, STATE_CERT_RECEIVED, TLS_BAD_CERTIFICATE, TLS_CERTIFICATE, TLS_DECODE_ERROR, TLS_FATAL, TLS_WARNING, and TRUE.
Referenced by METHOD().
 {
     certificate_t *cert;
     bio_reader_t *certs;
     chunk_t data;
     bool first = TRUE;
     this->crypto->append_handshake(this->crypto,
                                    TLS_CERTIFICATE, reader->peek(reader));
     if (!reader->read_data24(reader, &data))
     {
         DBG1(DBG_TLS, "certificate message header invalid");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     certs = bio_reader_create(data);
     while (certs->remaining(certs))
     {
         if (!certs->read_data24(certs, &data))
         {
             DBG1(DBG_TLS, "certificate message invalid");
             this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
             certs->destroy(certs);
             return NEED_MORE;
         }
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_BLOB_ASN1_DER, data, BUILD_END);
         if (cert)
         {
             if (first)
             {
                 this->peer_auth->add(this->peer_auth,
                                      AUTH_HELPER_SUBJECT_CERT, cert);
                 DBG1(DBG_TLS, "received TLS peer certificate '%Y'",
                      cert->get_subject(cert));
                 first = FALSE;
                 if (this->peer == NULL)
                 {   /* apply identity to authenticate */
                     this->peer = cert->get_subject(cert);
                     this->peer = this->peer->clone(this->peer);
                     this->peer_auth_optional = TRUE;
                 }
             }
             else
             {
                 DBG1(DBG_TLS, "received TLS intermediate certificate '%Y'",
                      cert->get_subject(cert));
                 this->peer_auth->add(this->peer_auth, AUTH_HELPER_IM_CERT, cert);
             }
         }
         else
         {
             DBG1(DBG_TLS, "parsing TLS certificate failed, skipped");
             this->alert->add(this->alert, TLS_WARNING, TLS_BAD_CERTIFICATE);
         }
     }
     certs->destroy(certs);
     this->state = STATE_CERT_RECEIVED;
     return NEED_MORE;
 }
static status_t process_client_hello (private_tls_server_t * this, bio_reader_t * reader) static
Process client hello message
Definition at line 213 of file tls_server.c.
References rng_t::allocate_bytes, bio_reader_create(), chunk_clone, chunk_empty, chunk_from_thing, count, crypto_factory_t::create_rng, library_t::crypto, curves, DBG1, DBG2, DBG3, DBG_TLS, rng_t::destroy, bio_reader_t::destroy, DESTROY_IF, extension, rng_t::get_bytes, htoun32(), chunk_t::len, lib, memcpy, NEED_MORE, bio_reader_t::peek, chunk_t::ptr, random, bio_reader_t::read_data, bio_reader_t::read_data16, bio_reader_t::read_data8, bio_reader_t::read_uint16, bio_reader_t::remaining, rng, RNG_STRONG, RNG_WEAK, select_suite_and_key(), SESSION_ID_SIZE, STATE_HELLO_RECEIVED, tls, tls_cipher_suite_names, TLS_CLIENT_HELLO, TLS_DECODE_ERROR, TLS_EXT_ELLIPTIC_CURVES, TLS_EXT_SIGNATURE_ALGORITHMS, tls_extension_names, TLS_FATAL, TLS_HANDSHAKE_FAILURE, TLS_INTERNAL_ERROR, TLS_PROTOCOL_VERSION, tls_version_names, TRUE, untoh16(), and version.
Referenced by METHOD().
 {
     u_int16_t version, extension;
     chunk_t random, session, ciphers, compression, ext = chunk_empty;
     bio_reader_t *extensions;
     tls_cipher_suite_t *suites;
     int count, i;
     rng_t *rng;
     this->crypto->append_handshake(this->crypto,
                                    TLS_CLIENT_HELLO, reader->peek(reader));
     if (!reader->read_uint16(reader, &version) ||
         !reader->read_data(reader, sizeof(this->client_random), &random) ||
         !reader->read_data8(reader, &session) ||
         !reader->read_data16(reader, &ciphers) ||
         !reader->read_data8(reader, &compression) ||
         (reader->remaining(reader) && !reader->read_data16(reader, &ext)))
     {
         DBG1(DBG_TLS, "received invalid ClientHello");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     if (ext.len)
     {
         extensions = bio_reader_create(ext);
         while (extensions->remaining(extensions))
         {
             if (!extensions->read_uint16(extensions, &extension) ||
                 !extensions->read_data16(extensions, &ext))
             {
                 DBG1(DBG_TLS, "received invalid ClientHello Extensions");
                 this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
                 extensions->destroy(extensions);
                 return NEED_MORE;
             }
             DBG2(DBG_TLS, "received TLS '%N' extension",
                  tls_extension_names, extension);
             DBG3(DBG_TLS, "%B", &ext);
             switch (extension)
             {
                 case TLS_EXT_SIGNATURE_ALGORITHMS:
                     this->hashsig = chunk_clone(ext);
                     break;
                 case TLS_EXT_ELLIPTIC_CURVES:
                     this->curves_received = TRUE;
                     this->curves = chunk_clone(ext);
                     break;
                 default:
                     break;
             }
         }
         extensions->destroy(extensions);
     }
     memcpy(this->client_random, random.ptr, sizeof(this->client_random));
     htoun32(&this->server_random, time(NULL));
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng ||
         !rng->get_bytes(rng, sizeof(this->server_random) - 4,
                         this->server_random + 4))
     {
         DBG1(DBG_TLS, "failed to generate server random");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         DESTROY_IF(rng);
         return NEED_MORE;
     }
     rng->destroy(rng);
     if (!this->tls->set_version(this->tls, version))
     {
         DBG1(DBG_TLS, "negotiated version %N not supported",
              tls_version_names, version);
         this->alert->add(this->alert, TLS_FATAL, TLS_PROTOCOL_VERSION);
         return NEED_MORE;
     }
     this->client_version = version;
     this->suite = this->crypto->resume_session(this->crypto, session, this->peer,
                                         chunk_from_thing(this->client_random),
                                         chunk_from_thing(this->server_random));
     if (this->suite)
     {
         this->session = chunk_clone(session);
         this->resume = TRUE;
         DBG1(DBG_TLS, "resumed %N using suite %N",
              tls_version_names, this->tls->get_version(this->tls),
              tls_cipher_suite_names, this->suite);
     }
     else
     {
         count = ciphers.len / sizeof(u_int16_t);
         suites = alloca(count * sizeof(tls_cipher_suite_t));
         DBG2(DBG_TLS, "received %d TLS cipher suites:", count);
         for (i = 0; i < count; i++)
         {
             suites[i] = untoh16(&ciphers.ptr[i * sizeof(u_int16_t)]);
             DBG2(DBG_TLS, "  %N", tls_cipher_suite_names, suites[i]);
         }
         if (!select_suite_and_key(this, suites, count))
         {
             this->alert->add(this->alert, TLS_FATAL, TLS_HANDSHAKE_FAILURE);
             return NEED_MORE;
         }
         rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
         if (!rng || !rng->allocate_bytes(rng, SESSION_ID_SIZE, &this->session))
         {
             DBG1(DBG_TLS, "generating TLS session identifier failed, skipped");
         }
         DESTROY_IF(rng);
         DBG1(DBG_TLS, "negotiated %N using suite %N",
              tls_version_names, this->tls->get_version(this->tls),
              tls_cipher_suite_names, this->suite);
     }
     this->state = STATE_HELLO_RECEIVED;
     return NEED_MORE;
 }
static status_t process_finished (private_tls_server_t * this, bio_reader_t * reader) static
Process finished message
Definition at line 592 of file tls_server.c.
References chunk_equals_const(), chunk_from_thing, DBG1, DBG_TLS, NEED_MORE, bio_reader_t::read_data, STATE_FINISHED_RECEIVED, TLS_DECODE_ERROR, TLS_DECRYPT_ERROR, TLS_FATAL, TLS_FINISHED, and TLS_INTERNAL_ERROR.
Referenced by METHOD().
 {
     chunk_t received;
     char buf[12];
     if (!reader->read_data(reader, sizeof(buf), &received))
     {
         DBG1(DBG_TLS, "received client finished too short");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     if (!this->crypto->calculate_finished(this->crypto, "client finished", buf))
     {
         DBG1(DBG_TLS, "calculating client finished failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!chunk_equals_const(received, chunk_from_thing(buf)))
     {
         DBG1(DBG_TLS, "received client finished invalid");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECRYPT_ERROR);
         return NEED_MORE;
     }
     this->crypto->append_handshake(this->crypto, TLS_FINISHED, received);
     this->state = STATE_FINISHED_RECEIVED;
     return NEED_MORE;
 }
static status_t process_key_exchange (private_tls_server_t * this, bio_reader_t * reader) static
Process Client Key Exchange
Definition at line 528 of file tls_server.c.
References dh, process_key_exchange_dhe(), and process_key_exchange_encrypted().
Referenced by METHOD().
 {
     if (this->dh)
     {
         return process_key_exchange_dhe(this, reader);
     }
     return process_key_exchange_encrypted(this, reader);
 }
static status_t process_key_exchange_dhe (private_tls_server_t * this, bio_reader_t * reader) static
Process client key exchange, using DHE exchange
Definition at line 468 of file tls_server.c.
References chunk_clear(), chunk_from_thing, chunk_skip(), DBG1, DBG_TLS, dh, diffie_hellman_group_is_ec(), chunk_t::len, NEED_MORE, bio_reader_t::peek, chunk_t::ptr, pub(), bio_reader_t::read_data16, bio_reader_t::read_data8, STATE_KEY_EXCHANGE_RECEIVED, tls_ansi_point_format_names, TLS_ANSI_UNCOMPRESSED, TLS_CLIENT_KEY_EXCHANGE, TLS_DECODE_ERROR, TLS_FATAL, and TLS_INTERNAL_ERROR.
Referenced by process_key_exchange().
 {
     chunk_t premaster, pub;
     bool ec;
     this->crypto->append_handshake(this->crypto,
                                    TLS_CLIENT_KEY_EXCHANGE, reader->peek(reader));
     ec = diffie_hellman_group_is_ec(this->dh->get_dh_group(this->dh));
     if ((ec && !reader->read_data8(reader, &pub)) ||
         (!ec && (!reader->read_data16(reader, &pub) || pub.len == 0)))
     {
         DBG1(DBG_TLS, "received invalid Client Key Exchange");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     if (ec)
     {
         if (pub.ptr[0] != TLS_ANSI_UNCOMPRESSED)
         {
             DBG1(DBG_TLS, "DH point format '%N' not supported",
                  tls_ansi_point_format_names, pub.ptr[0]);
             this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
             return NEED_MORE;
         }
         pub = chunk_skip(pub, 1);
     }
     if (!this->dh->set_other_public_value(this->dh, pub))
     {
         DBG1(DBG_TLS, "applying DH public value failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!this->dh->get_shared_secret(this->dh, &premaster))
     {
         DBG1(DBG_TLS, "calculating premaster from DH failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!this->crypto->derive_secrets(this->crypto, premaster,
                                       this->session, this->peer,
                                       chunk_from_thing(this->client_random),
                                       chunk_from_thing(this->server_random)))
     {
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         chunk_clear(&premaster);
         return NEED_MORE;
     }
     chunk_clear(&premaster);
     this->state = STATE_KEY_EXCHANGE_RECEIVED;
     return NEED_MORE;
 }
static status_t process_key_exchange_encrypted (private_tls_server_t * this, bio_reader_t * reader) static
Process Client Key Exchange, using premaster encryption
Definition at line 403 of file tls_server.c.
References chunk_clear(), chunk_from_thing, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_TLS, rng_t::destroy, DESTROY_IF, ENCRYPT_RSA_PKCS1, rng_t::get_bytes, htoun16(), chunk_t::len, lib, memcpy, NEED_MORE, bio_reader_t::peek, private, chunk_t::ptr, bio_reader_t::read_data16, rng, RNG_WEAK, STATE_KEY_EXCHANGE_RECEIVED, TLS_CLIENT_KEY_EXCHANGE, TLS_DECODE_ERROR, TLS_FATAL, TLS_INTERNAL_ERROR, and untoh16().
Referenced by process_key_exchange().
 {
     chunk_t encrypted, decrypted;
     char premaster[48];
     rng_t *rng;
     this->crypto->append_handshake(this->crypto,
                                    TLS_CLIENT_KEY_EXCHANGE, reader->peek(reader));
     if (!reader->read_data16(reader, &encrypted))
     {
         DBG1(DBG_TLS, "received invalid Client Key Exchange");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     htoun16(premaster, this->client_version);
     /* pre-randomize premaster for failure cases */
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng || !rng->get_bytes(rng, sizeof(premaster) - 2, premaster + 2))
     {
         DBG1(DBG_TLS, "failed to generate premaster secret");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         DESTROY_IF(rng);
         return NEED_MORE;
     }
     rng->destroy(rng);
     if (this->private &&
         this->private->decrypt(this->private,
                                ENCRYPT_RSA_PKCS1, encrypted, &decrypted))
     {
         if (decrypted.len == sizeof(premaster) &&
             untoh16(decrypted.ptr) == this->client_version)
         {
             memcpy(premaster + 2, decrypted.ptr + 2, sizeof(premaster) - 2);
         }
         else
         {
             DBG1(DBG_TLS, "decrypted premaster has invalid length/version");
         }
         chunk_clear(&decrypted);
     }
     else
     {
         DBG1(DBG_TLS, "decrypting Client Key Exchange failed");
     }
     if (!this->crypto->derive_secrets(this->crypto, chunk_from_thing(premaster),
                                       this->session, this->peer,
                                       chunk_from_thing(this->client_random),
                                       chunk_from_thing(this->server_random)))
     {
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     this->state = STATE_KEY_EXCHANGE_RECEIVED;
     return NEED_MORE;
 }
static bool select_suite_and_key (private_tls_server_t * this, tls_cipher_suite_t * suites, int count) static
Find a cipher suite and a server key
Definition at line 161 of file tls_server.c.
References auth_cfg_create(), library_t::credmgr, DBG1, DBG_TLS, private_key_t::destroy, FALSE, credential_manager_t::get_private, private_key_t::get_type, key, KEY_ANY, KEY_ECDSA, KEY_RSA, lib, server, TRUE, and type.
Referenced by process_client_hello().
 {
     private_key_t *key;
     key_type_t type;
     key = lib->credmgr->get_private(lib->credmgr, KEY_ANY, this->server,
                                     this->server_auth);
     if (!key)
     {
         DBG1(DBG_TLS, "no usable TLS server certificate found for '%Y'",
              this->server);
         return FALSE;
     }
     this->suite = this->crypto->select_cipher_suite(this->crypto,
                                             suites, count, key->get_type(key));
     if (!this->suite)
     {   /* no match for this key, try to find another type */
         if (key->get_type(key) == KEY_ECDSA)
         {
             type = KEY_RSA;
         }
         else
         {
             type = KEY_ECDSA;
         }
         key->destroy(key);
         this->suite = this->crypto->select_cipher_suite(this->crypto,
                                             suites, count, type);
         if (!this->suite)
         {
             DBG1(DBG_TLS, "received cipher suites inacceptable");
             return FALSE;
         }
         this->server_auth->destroy(this->server_auth);
         this->server_auth = auth_cfg_create();
         key = lib->credmgr->get_private(lib->credmgr, type, this->server,
                                         this->server_auth);
         if (!key)
         {
             DBG1(DBG_TLS, "received cipher suites inacceptable");
             return FALSE;
         }
     }
     this->private = key;
     return TRUE;
 }
static status_t send_certificate (private_tls_server_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send Certificate
Definition at line 712 of file tls_server.c.
References AUTH_RULE_IM_CERT, AUTH_RULE_SUBJECT_CERT, bio_writer_create(), cert, CERT_ASN1_DER, data, DBG1, DBG_TLS, enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, free(), bio_writer_t::get_buf, certificate_t::get_encoding, certificate_t::get_subject, NEED_MORE, chunk_t::ptr, STATE_CERT_SENT, TLS_CERTIFICATE, and bio_writer_t::write_data24.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     auth_rule_t rule;
     bio_writer_t *certs;
     chunk_t data;
     /* generate certificate payload */
     certs = bio_writer_create(256);
     cert = this->server_auth->get(this->server_auth, AUTH_RULE_SUBJECT_CERT);
     if (cert)
     {
         if (cert->get_encoding(cert, CERT_ASN1_DER, &data))
         {
             DBG1(DBG_TLS, "sending TLS server certificate '%Y'",
                  cert->get_subject(cert));
             certs->write_data24(certs, data);
             free(data.ptr);
         }
     }
     enumerator = this->server_auth->create_enumerator(this->server_auth);
     while (enumerator->enumerate(enumerator, &rule, &cert))
     {
         if (rule == AUTH_RULE_IM_CERT)
         {
             if (cert->get_encoding(cert, CERT_ASN1_DER, &data))
             {
                 DBG1(DBG_TLS, "sending TLS intermediate certificate '%Y'",
                      cert->get_subject(cert));
                 certs->write_data24(certs, data);
                 free(data.ptr);
             }
         }
     }
     enumerator->destroy(enumerator);
     writer->write_data24(writer, certs->get_buf(certs));
     certs->destroy(certs);
     *type = TLS_CERTIFICATE;
     this->state = STATE_CERT_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_certificate_request (private_tls_server_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send Certificate Request
Definition at line 762 of file tls_server.c.
References bio_writer_create(), cert, CERT_X509, credential_manager_t::create_cert_enumerator, library_t::credmgr, DBG1, DBG_TLS, enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::get_buf, identification_t::get_encoding, x509_t::get_flags, certificate_t::get_subject, id, KEY_RSA, lib, NEED_MORE, STATE_CERTREQ_SENT, tls, TLS_1_2, TLS_CERTIFICATE_REQUEST, TLS_ECDSA_SIGN, TLS_RSA_SIGN, TRUE, bio_writer_t::write_data16, bio_writer_t::write_data8, bio_writer_t::write_uint8, and X509_CA.
Referenced by METHOD().
 {
     bio_writer_t *authorities, *supported;
     enumerator_t *enumerator;
     certificate_t *cert;
     x509_t *x509;
     identification_t *id;
     supported = bio_writer_create(4);
     /* we propose both RSA and ECDSA */
     supported->write_uint8(supported, TLS_RSA_SIGN);
     supported->write_uint8(supported, TLS_ECDSA_SIGN);
     writer->write_data8(writer, supported->get_buf(supported));
     supported->destroy(supported);
     if (this->tls->get_version(this->tls) >= TLS_1_2)
     {
         this->crypto->get_signature_algorithms(this->crypto, writer);
     }
     authorities = bio_writer_create(64);
     enumerator = lib->credmgr->create_cert_enumerator(lib->credmgr,
                                                 CERT_X509, KEY_RSA, NULL, TRUE);
     while (enumerator->enumerate(enumerator, &cert))
     {
         x509 = (x509_t*)cert;
         if (x509->get_flags(x509) & X509_CA)
         {
             id = cert->get_subject(cert);
             DBG1(DBG_TLS, "sending TLS cert request for '%Y'", id);
             authorities->write_data16(authorities, id->get_encoding(id));
         }
     }
     enumerator->destroy(enumerator);
     writer->write_data16(writer, authorities->get_buf(authorities));
     authorities->destroy(authorities);
     *type = TLS_CERTIFICATE_REQUEST;
     this->state = STATE_CERTREQ_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_finished (private_tls_server_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send Finished
Definition at line 972 of file tls_server.c.
References chunk_from_thing, DBG1, DBG_TLS, FAILED, bio_writer_t::get_buf, NEED_MORE, STATE_FINISHED_SENT, TLS_FATAL, TLS_FINISHED, TLS_INTERNAL_ERROR, and bio_writer_t::write_data.
Referenced by METHOD().
 {
     char buf[12];
     if (!this->crypto->calculate_finished(this->crypto, "server finished", buf))
     {
         DBG1(DBG_TLS, "calculating server finished data failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return FAILED;
     }
     writer->write_data(writer, chunk_from_thing(buf));
     *type = TLS_FINISHED;
     this->state = STATE_FINISHED_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_hello_done (private_tls_server_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send Hello Done
Definition at line 960 of file tls_server.c.
References bio_writer_t::get_buf, NEED_MORE, STATE_HELLO_DONE, and TLS_SERVER_HELLO_DONE.
Referenced by METHOD().
 {
     *type = TLS_SERVER_HELLO_DONE;
     this->state = STATE_HELLO_DONE;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_server_hello (private_tls_server_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send ServerHello message
Definition at line 687 of file tls_server.c.
References chunk_from_thing, bio_writer_t::get_buf, NEED_MORE, STATE_HELLO_SENT, tls, TLS_SERVER_HELLO, bio_writer_t::write_data, bio_writer_t::write_data8, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
Referenced by METHOD().
 {
     /* TLS version */
     writer->write_uint16(writer, this->tls->get_version(this->tls));
     writer->write_data(writer, chunk_from_thing(this->server_random));
     /* session identifier if we have one */
     writer->write_data8(writer, this->session);
     /* add selected TLS cipher suite */
     writer->write_uint16(writer, this->suite);
     /* NULL compression only */
     writer->write_uint8(writer, 0);
     *type = TLS_SERVER_HELLO;
     this->state = STATE_HELLO_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_server_key_exchange (private_tls_server_t * this, tls_handshake_type_t * type, bio_writer_t * writer, diffie_hellman_group_t group) static
Send Server key Exchange
Definition at line 879 of file tls_server.c.
References chunk_cat, chunk_from_thing, crypto_factory_t::create_dh, library_t::crypto, curve, DBG1, DBG2, DBG_TLS, dh, diffie_hellman_get_params(), diffie_hellman_group_is_ec(), diffie_hellman_group_names, ec_group_to_curve(), find_supported_curve(), free(), diffie_hellman_params_t::generator, bio_writer_t::get_buf, chunk_t::len, lib, NEED_MORE, params, peer_supports_curve(), diffie_hellman_params_t::prime, chunk_t::ptr, STATE_KEY_EXCHANGE_SENT, TLS_ANSI_UNCOMPRESSED, TLS_ECC_NAMED_CURVE, TLS_FATAL, TLS_HANDSHAKE_FAILURE, TLS_INTERNAL_ERROR, tls_named_curve_names, TLS_SERVER_KEY_EXCHANGE, bio_writer_t::write_data, bio_writer_t::write_data16, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
Referenced by METHOD().
 {
     diffie_hellman_params_t *params = NULL;
     tls_named_curve_t curve;
     chunk_t chunk;
     if (diffie_hellman_group_is_ec(group))
     {
         curve = ec_group_to_curve(this, group);
         if (!curve || (!peer_supports_curve(this, curve) &&
                        !find_supported_curve(this, &curve)))
         {
             DBG1(DBG_TLS, "no EC group supported by client and server");
             this->alert->add(this->alert, TLS_FATAL, TLS_HANDSHAKE_FAILURE);
             return NEED_MORE;
         }
         DBG2(DBG_TLS, "selected ECDH group %N", tls_named_curve_names, curve);
         writer->write_uint8(writer, TLS_ECC_NAMED_CURVE);
         writer->write_uint16(writer, curve);
     }
     else
     {
         params = diffie_hellman_get_params(group);
         if (!params)
         {
             DBG1(DBG_TLS, "no parameters found for DH group %N",
                  diffie_hellman_group_names, group);
             this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
             return NEED_MORE;
         }
         DBG2(DBG_TLS, "selected DH group %N", diffie_hellman_group_names, group);
         writer->write_data16(writer, params->prime);
         writer->write_data16(writer, params->generator);
     }
     this->dh = lib->crypto->create_dh(lib->crypto, group);
     if (!this->dh)
     {
         DBG1(DBG_TLS, "DH group %N not supported",
              diffie_hellman_group_names, group);
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!this->dh->get_my_public_value(this->dh, &chunk))
     {
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (params)
     {
         writer->write_data16(writer, chunk);
     }
     else
     {   /* ECP uses 8bit length header only, but a point format */
         writer->write_uint8(writer, chunk.len + 1);
         writer->write_uint8(writer, TLS_ANSI_UNCOMPRESSED);
         writer->write_data(writer, chunk);
     }
     free(chunk.ptr);
     chunk = chunk_cat("ccc", chunk_from_thing(this->client_random),
                 chunk_from_thing(this->server_random), writer->get_buf(writer));
     if (!this->private || !this->crypto->sign(this->crypto, this->private,
                                               writer, chunk, this->hashsig))
     {
         DBG1(DBG_TLS, "signing DH parameters failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         free(chunk.ptr);
         return NEED_MORE;
     }
     free(chunk.ptr);
     *type = TLS_SERVER_KEY_EXCHANGE;
     this->state = STATE_KEY_EXCHANGE_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }