strongSwan: keychain_creds.c File Reference
keychain_creds.c File Reference
#include "keychain_creds.h"
#include <utils/debug.h>
#include <credentials/sets/mem_cred.h>
#include <processing/jobs/callback_job.h>
#include <Security/Security.h>
Classes
struct private_keychain_creds_t
Macros
#define SYSTEM_ROOTS "/System/Library/Keychains/SystemRootCertificates.keychain"
#define SYSTEM "/Library/Keychains/System.keychain"
Typedefs
typedef struct
private_keychain_creds_t private_keychain_creds_t
Functions
static mem_cred_t * load_certs (private_keychain_creds_t *this, char *path)
static OSStatus keychain_cb (SecKeychainEvent keychainEvent, SecKeychainCallbackInfo *info, private_keychain_creds_t *this)
static job_requeue_t monitor_changes (private_keychain_creds_t *this)
static bool cancel_monitor (private_keychain_creds_t *this)
METHOD (keychain_creds_t, destroy, void, private_keychain_creds_t *this)
keychain_creds_t * keychain_creds_create ()
Macro Definition Documentation
#define SYSTEM "/Library/Keychains/System.keychain"
System keychain
Definition at line 32 of file keychain_creds.c.
Referenced by keychain_cb(), and keychain_creds_create().
#define SYSTEM_ROOTS "/System/Library/Keychains/SystemRootCertificates.keychain"
System Roots keychain
Definition at line 27 of file keychain_creds.c.
Referenced by keychain_creds_create().
Typedef Documentation
typedef struct private_keychain_creds_t private_keychain_creds_t
Definition at line 34 of file keychain_creds.c.
Function Documentation
static bool cancel_monitor (private_keychain_creds_t * this) static
Cancel the monitoring thread in its RunLoop
Definition at line 163 of file keychain_creds.c.
References TRUE.
Referenced by keychain_creds_create().
 {
     if (this->loop)
     {
         CFRunLoopStop(this->loop);
     }
     return TRUE;
 }
static OSStatus keychain_cb (SecKeychainEvent keychainEvent, SecKeychainCallbackInfo * info, private_keychain_creds_t * this) static
Callback function reloading keychain on changes
Definition at line 118 of file keychain_creds.c.
References credential_manager_t::add_set, CERT_X509, library_t::credmgr, DBG1, DBG_CFG, credential_manager_t::flush_cache, lib, load_certs(), credential_manager_t::remove_set, and SYSTEM.
Referenced by monitor_changes().
 {
     mem_cred_t *new;
     DBG1(DBG_CFG, "received keychain event, reloading credentials");
     /* register new before removing old */
     new = load_certs(this, SYSTEM);
     lib->credmgr->add_set(lib->credmgr, &new->set);
     lib->credmgr->remove_set(lib->credmgr, &this->set->set);
     lib->credmgr->flush_cache(lib->credmgr, CERT_X509);
     this->set->destroy(this->set);
     this->set = new;
     return errSecSuccess;
 }
static mem_cred_t* load_certs (private_keychain_creds_t * this, char * path) static
Load a credential sets with certificates from a keychain path
Definition at line 65 of file keychain_creds.c.
References mem_cred_t::add_cert, BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, chunk_create(), credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, data, DBG1, DBG2, DBG_CFG, certificate_t::get_subject, len, lib, mem_cred_create(), search, status, and TRUE.
Referenced by keychain_cb(), and keychain_creds_create().
 {
     SecKeychainRef keychain;
     SecKeychainSearchRef search;
     SecKeychainItemRef item;
     mem_cred_t *set;
     OSStatus status;
     int loaded = 0;
     set = mem_cred_create();
     DBG2(DBG_CFG, "loading certificates from %s:", path);
     status = SecKeychainOpen(path, &keychain);
     if (status == errSecSuccess)
     {
         status = SecKeychainSearchCreateFromAttributes(keychain,
                                     kSecCertificateItemClass, NULL, &search);
         if (status == errSecSuccess)
         {
             while (SecKeychainSearchCopyNext(search, &item) == errSecSuccess)
             {
                 certificate_t *cert;
                 UInt32 len;
                 void *data;
                 if (SecKeychainItemCopyAttributesAndData(item, NULL, NULL, NULL,
                                                 &len, &data) == errSecSuccess)
                 {
                     cert = lib->creds->create(lib->creds,
                                 CRED_CERTIFICATE, CERT_X509,
                                 BUILD_BLOB_ASN1_DER, chunk_create(data, len),
                                 BUILD_END);
                     if (cert)
                     {
                         DBG2(DBG_CFG, "  loaded '%Y'", cert->get_subject(cert));
                         set->add_cert(set, TRUE, cert);
                         loaded++;
                     }
                     SecKeychainItemFreeAttributesAndData(NULL, data);
                 }
                 CFRelease(item);
             }
             CFRelease(search);
         }
         CFRelease(keychain);
     }
     DBG1(DBG_CFG, "loaded %d certificates from %s", loaded, path);
     return set;
 }
METHOD (keychain_creds_t , destroy , void , private_keychain_creds_t * this)
Definition at line 172 of file keychain_creds.c.
References library_t::credmgr, free(), lib, and credential_manager_t::remove_set.
 {
     lib->credmgr->remove_set(lib->credmgr, &this->set->set);
     lib->credmgr->remove_set(lib->credmgr, &this->roots->set);
     this->set->destroy(this->set);
     this->roots->destroy(this->roots);
     free(this);
 }
static job_requeue_t monitor_changes (private_keychain_creds_t * this) static
Wait for changes in the keychain and handle them
Definition at line 142 of file keychain_creds.c.
References JOB_REQUEUE_NONE, and keychain_cb().
Referenced by keychain_creds_create().
 {
     if (SecKeychainAddCallback((SecKeychainCallback)keychain_cb,
                         kSecAddEventMask | kSecDeleteEventMask |
                         kSecUpdateEventMask | kSecTrustSettingsChangedEventMask,
                         this) == errSecSuccess)
     {
         this->loop = CFRunLoopGetCurrent();
         /* does not return until cancelled */
         CFRunLoopRun();
         this->loop = NULL;
         SecKeychainRemoveCallback((SecKeychainCallback)keychain_cb);
     }
     return JOB_REQUEUE_NONE;
 }