strongSwan: tkm.c File Reference
tkm.c File Reference
#include <daemon.h>
#include <tkm/client.h>
#include <tkm/constants.h>
#include "tkm.h"
Classes
struct private_tkm_t
Macros
#define IKE_SOCKET "/tmp/tkm.rpc.ike"
#define EES_SOCKET "/tmp/tkm.rpc.ees"
Typedefs
typedef struct private_tkm_t private_tkm_t
Functions
result_type ees_server_init (const char *const address)
void ees_server_finalize (void)
void ehandler_init (void)
bool tkm_init ()
void tkm_deinit ()
Variables
tkm_t * tkm = NULL
Macro Definition Documentation
#define EES_SOCKET "/tmp/tkm.rpc.ees"
Definition at line 25 of file tkm.c.
Referenced by tkm_init().
#define IKE_SOCKET "/tmp/tkm.rpc.ike"
Definition at line 24 of file tkm.c.
Referenced by tkm_init().
Typedef Documentation
typedef struct private_tkm_t private_tkm_t
Definition at line 27 of file tkm.c.
Function Documentation
void ees_server_finalize (void)
Referenced by tkm_deinit(), and tkm_init().
result_type ees_server_init (const char *const address)
Referenced by tkm_init().
void ehandler_init (void)
Referenced by tkm_init().