strongSwan: file_logger
file_logger
listeners
Classes
struct file_logger_t
Typedefs
typedef struct file_logger_t file_logger_t
Functions
file_logger_t * file_logger_create (char *filename)
Detailed Description
Typedef Documentation
typedef struct file_logger_t file_logger_t
Definition at line 27 of file file_logger.h.
Function Documentation
file_logger_t* file_logger_create (char * filename)
Constructor to create a file_logger_t object.
The logger has to be opened via file_logger_t.open() before anything is logged.
Parameters
filename name of the log file (stderr and stdout are handled specially), cloned
Returns
file_logger_t object
Definition at line 276 of file file_logger.c.
References DBG_ANY, INIT, LEVEL_SILENT, mutex_t::lock, mutex_create(), MUTEX_TYPE_DEFAULT, rwlock_create(), RWLOCK_TYPE_DEFAULT, set_level, and strdup.
Referenced by get_logger_entry(), load_loggers(), and main().
 {
     private_file_logger_t *this;
     INIT(this,
         .public = {
             .logger = {
                 .log = _log_,
                 .get_level = _get_level,
             },
             .set_level = _set_level,
             .set_options = _set_options,
             .open = _open_,
             .destroy = _destroy,
         },
         .filename = strdup(filename),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     set_level(this, DBG_ANY, LEVEL_SILENT);
     return &this->public;
 }