strongSwan: revocation_plugin.c File Reference
revocation_plugin.c File Reference
#include "revocation_plugin.h"
#include <library.h>
#include "revocation_validator.h"
Classes
struct private_revocation_plugin_t
Typedefs
typedef struct
private_revocation_plugin_t private_revocation_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_revocation_plugin_t *this)
static bool plugin_cb (private_revocation_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_revocation_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_revocation_plugin_t *this)
plugin_t * revocation_plugin_create ()
Typedef Documentation
typedef struct private_revocation_plugin_t private_revocation_plugin_t
Definition at line 21 of file revocation_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_revocation_plugin_t * this)
Definition at line 39 of file revocation_plugin.c.
 {
     return "revocation";
 }
METHOD (plugin_t , get_features , int , private_revocation_plugin_t * this, plugin_feature_t * features[])
Definition at line 63 of file revocation_plugin.c.
References CERT_X509, CERT_X509_CRL, CERT_X509_OCSP_REQUEST, CERT_X509_OCSP_RESPONSE, countof, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_PROVIDE, and PLUGIN_SDEPEND.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "revocation"),
                 PLUGIN_SDEPEND(CERT_ENCODE, CERT_X509_OCSP_REQUEST),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509_OCSP_RESPONSE),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509_CRL),
                 PLUGIN_SDEPEND(CERT_DECODE, CERT_X509),
                 PLUGIN_SDEPEND(FETCHER, NULL),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_revocation_plugin_t * this)
Definition at line 79 of file revocation_plugin.c.
References free().
 {
     this->validator->destroy(this->validator);
     free(this);
 }
static bool plugin_cb (private_revocation_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register validator
Definition at line 48 of file revocation_plugin.c.
References credential_manager_t::add_validator, library_t::credmgr, lib, credential_manager_t::remove_validator, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         lib->credmgr->add_validator(lib->credmgr, &this->validator->validator);
     }
     else
     {
         lib->credmgr->remove_validator(lib->credmgr,
                                        &this->validator->validator);
     }
     return TRUE;
 }
plugin_t* revocation_plugin_create ()
Definition at line 89 of file revocation_plugin.c.
References INIT, and revocation_validator_create().
 {
     private_revocation_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .validator = revocation_validator_create(),
     );
     return &this->public.plugin;
 }