strongSwan: cmd_creds
cmd_creds
cmd
Classes
struct cmd_creds_t
Typedefs
typedef struct cmd_creds_t cmd_creds_t
Functions
cmd_creds_t * cmd_creds_create ()
Detailed Description
Typedef Documentation
typedef struct cmd_creds_t cmd_creds_t
Definition at line 28 of file cmd_creds.h.
Function Documentation
cmd_creds_t* cmd_creds_create ()
Create a cmd_creds instance.
See header
Definition at line 279 of file cmd_creds.c.
References credential_manager_t::add_set, callback_cred_create_shared(), callback_shared(), cb(), library_t::credmgr, INIT, lib, mem_cred_create(), and SHARED_ANY.
Referenced by main().
 {
     private_cmd_creds_t *this;
     INIT(this,
         .public = {
             .handle = _handle,
             .destroy = _destroy,
         },
         .creds = mem_cred_create(),
         .prompted = SHARED_ANY,
     );
     this->cb = callback_cred_create_shared((void*)callback_shared, this);
     lib->credmgr->add_set(lib->credmgr, &this->creds->set);
     lib->credmgr->add_set(lib->credmgr, &this->cb->set);
     return &this->public;
 }