strongSwan: auth_cfg
auth_cfg
credentials
Classes
struct auth_cfg_t
Typedefs
typedef struct auth_cfg_t auth_cfg_t
typedef enum auth_rule_t auth_rule_t
typedef enum auth_class_t auth_class_t
Enumerations
enum auth_class_t {
AUTH_CLASS_ANY = 0, AUTH_CLASS_PUBKEY = 1, AUTH_CLASS_PSK = 2, AUTH_CLASS_EAP = 3,
AUTH_CLASS_XAUTH = 4
}
enum auth_rule_t {
AUTH_RULE_IDENTITY, AUTH_RULE_IDENTITY_LOOSE, AUTH_RULE_AUTH_CLASS, AUTH_RULE_AAA_IDENTITY,
AUTH_RULE_EAP_IDENTITY, AUTH_RULE_EAP_TYPE, AUTH_RULE_EAP_VENDOR, AUTH_RULE_XAUTH_BACKEND,
AUTH_RULE_XAUTH_IDENTITY, AUTH_RULE_CA_CERT, AUTH_RULE_IM_CERT, AUTH_RULE_SUBJECT_CERT,
AUTH_RULE_CRL_VALIDATION, AUTH_RULE_OCSP_VALIDATION, AUTH_RULE_GROUP, AUTH_RULE_RSA_STRENGTH,
AUTH_RULE_ECDSA_STRENGTH, AUTH_RULE_BLISS_STRENGTH, AUTH_RULE_SIGNATURE_SCHEME, AUTH_RULE_CERT_POLICY,
AUTH_HELPER_IM_CERT, AUTH_HELPER_SUBJECT_CERT, AUTH_HELPER_IM_HASH_URL, AUTH_HELPER_SUBJECT_HASH_URL,
AUTH_HELPER_REVOCATION_CERT, AUTH_HELPER_AC_CERT, AUTH_RULE_MAX
}
Functions
auth_cfg_t * auth_cfg_create ()
Variables
enum_name_t * auth_class_names
enum_name_t * auth_rule_names
Detailed Description
Typedef Documentation
typedef struct auth_cfg_t auth_cfg_t
Definition at line 27 of file auth_cfg.h.
typedef enum auth_class_t auth_class_t
Definition at line 29 of file auth_cfg.h.
typedef enum auth_rule_t auth_rule_t
Definition at line 28 of file auth_cfg.h.
Enumeration Type Documentation
enum auth_class_t
Class of authentication to use. This is different to auth_method_t in that it does not specify a method, but a class of acceptable methods. The found certificate finally dictates which method is used.
Enumerator
AUTH_CLASS_ANY
any class acceptable
AUTH_CLASS_PUBKEY
authentication using public keys (RSA, ECDSA)
AUTH_CLASS_PSK
authentication using a pre-shared secrets
AUTH_CLASS_EAP
authentication using EAP
AUTH_CLASS_XAUTH
authentication using IKEv1 XAUTH
Definition at line 36 of file auth_cfg.h.
                   {
     AUTH_CLASS_ANY = 0,
     AUTH_CLASS_PUBKEY = 1,
     AUTH_CLASS_PSK = 2,
     AUTH_CLASS_EAP = 3,
     AUTH_CLASS_XAUTH = 4,
 };
enum auth_rule_t
Authentication config to use during authentication process.
Each authentication config contains a set of rules. These rule-sets are used in two ways:
For configs specifying local authentication behavior, the rules define which authentication method in which way.
For configs specifying remote peer authentication, the rules define constraints the peer has to fulfill.
Additionally to the rules, there is a set of helper items. These are used to transport credentials during the authentication process.
Enumerator
AUTH_RULE_IDENTITY
identity to use for IKEv2 authentication exchange, identification_t*
AUTH_RULE_IDENTITY_LOOSE
if TRUE don't send IDr as initiator, but verify the identity after receiving IDr (but also verify it against subjectAltNames), bool
AUTH_RULE_AUTH_CLASS
authentication class, auth_class_t
AUTH_RULE_AAA_IDENTITY
AAA-backend identity for EAP methods supporting it, identification_t*
AUTH_RULE_EAP_IDENTITY
EAP identity to use within EAP-Identity exchange, identification_t*
AUTH_RULE_EAP_TYPE
EAP type to propose for peer authentication, eap_type_t
AUTH_RULE_EAP_VENDOR
EAP vendor for vendor specific type, u_int32_t
AUTH_RULE_XAUTH_BACKEND
XAUTH backend name to use, char*
AUTH_RULE_XAUTH_IDENTITY
XAuth identity to use or require, identification_t*
AUTH_RULE_CA_CERT
certificate authority, certificate_t*
AUTH_RULE_IM_CERT
intermediate certificate in trustchain, certificate_t*
AUTH_RULE_SUBJECT_CERT
subject certificate, certificate_t*
AUTH_RULE_CRL_VALIDATION
result of a CRL validation, cert_validation_t
AUTH_RULE_OCSP_VALIDATION
result of a OCSP validation, cert_validation_t
AUTH_RULE_GROUP
subject is member of a group, identification_t* The group membership constraint is fulfilled if the subject is member of one group defined in the constraints.
AUTH_RULE_RSA_STRENGTH
required RSA public key strength, u_int in bits
AUTH_RULE_ECDSA_STRENGTH
required ECDSA public key strength, u_int in bits
AUTH_RULE_BLISS_STRENGTH
required BLISS public key strength, u_int in bits
AUTH_RULE_SIGNATURE_SCHEME
required signature scheme, signature_scheme_t
AUTH_RULE_CERT_POLICY
certificatePolicy constraint, numerical OID as char*
AUTH_HELPER_IM_CERT
intermediate certificate, certificate_t*
AUTH_HELPER_SUBJECT_CERT
subject certificate, certificate_t*
AUTH_HELPER_IM_HASH_URL
Hash and URL of a intermediate certificate, char*
AUTH_HELPER_SUBJECT_HASH_URL
Hash and URL of a end-entity certificate, char*
AUTH_HELPER_REVOCATION_CERT
revocation certificate (CRL, OCSP), certificate_t*
AUTH_HELPER_AC_CERT
attribute certificate for authorization decisions, certificate_t
AUTH_RULE_MAX
helper to determine the number of elements in this enum
Definition at line 67 of file auth_cfg.h.
                  {
     AUTH_RULE_IDENTITY,
     AUTH_RULE_IDENTITY_LOOSE,
     AUTH_RULE_AUTH_CLASS,
     AUTH_RULE_AAA_IDENTITY,
     AUTH_RULE_EAP_IDENTITY,
     AUTH_RULE_EAP_TYPE,
     AUTH_RULE_EAP_VENDOR,
     AUTH_RULE_XAUTH_BACKEND,
     AUTH_RULE_XAUTH_IDENTITY,
     AUTH_RULE_CA_CERT,
     AUTH_RULE_IM_CERT,
     AUTH_RULE_SUBJECT_CERT,
     AUTH_RULE_CRL_VALIDATION,
     AUTH_RULE_OCSP_VALIDATION,
     AUTH_RULE_GROUP,
     AUTH_RULE_RSA_STRENGTH,
     AUTH_RULE_ECDSA_STRENGTH,
     AUTH_RULE_BLISS_STRENGTH,
     AUTH_RULE_SIGNATURE_SCHEME,
     AUTH_RULE_CERT_POLICY,
     AUTH_HELPER_IM_CERT,
     AUTH_HELPER_SUBJECT_CERT,
     AUTH_HELPER_IM_HASH_URL,
     AUTH_HELPER_SUBJECT_HASH_URL,
     AUTH_HELPER_REVOCATION_CERT,
     AUTH_HELPER_AC_CERT,
     AUTH_RULE_MAX,
 };
Function Documentation
auth_cfg_t* auth_cfg_create ()
Create a authentication config.
Definition at line 1112 of file auth_cfg.c.
References add(), array_create(), bool, create_enumerator(), equals(), INIT, merge(), replace(), and type.
Referenced by add_auth_cfg(), apply_auth_cfg(), build_auth(), build_auth_cfg(), build_peer_cfg(), build_trustchain(), CALLBACK(), connect_(), eap_mschapv2_create_generic(), generate_auth_cfg(), ike_sa_create(), initiate_connection(), load_peer_config(), METHOD(), process_ike_update(), save_auth_cfg(), select_suite_and_key(), setup_tunnel(), soap_init(), tls_peer_create(), tls_server_create(), and verify_trust_chain().
 {
     private_auth_cfg_t *this;
     INIT(this,
         .public = {
             .add = (void(*)(auth_cfg_t*, auth_rule_t type, ...))add,
             .get = _get,
             .create_enumerator = _create_enumerator,
             .replace = (void(*)(auth_cfg_t*,enumerator_t*,auth_rule_t,...))replace,
             .complies = _complies,
             .merge = (void(*)(auth_cfg_t*,auth_cfg_t*,bool))merge,
             .purge = _purge,
             .equals = (bool(*)(auth_cfg_t*,auth_cfg_t*))equals,
             .clone = _clone_,
             .destroy = _destroy,
         },
         .entries = array_create(sizeof(entry_t), 0),
     );
     return &this->public;
 }
Variable Documentation
enum_name_t* auth_class_names
enum strings for auth_class_t
Referenced by build_auth(), build_auth_cfgs(), log_auth(), log_auth_cfgs(), log_ike_sa(), METHOD(), and verify_auth().
enum_name_t* auth_rule_names
enum name for auth_rule_t.
Referenced by METHOD().