strongSwan: strerror.c File Reference
strerror.c File Reference
#include <stdlib.h>
#include <string.h>
#include <library.h>
#include <threading/thread_value.h>
#include <threading/spinlock.h>
#include "strerror.h"
Macros
#define STRERROR_BUF_LEN 256
Functions
static char * get_strerror_buf ()
const char * strerror_safe (int errnum)
static void free_no_ld (void *buf)
void strerror_init ()
void strerror_deinit ()
Variables
static thread_value_t * strerror_buf
static spinlock_t * strerror_lock
Macro Definition Documentation
#define STRERROR_BUF_LEN 256
The size of the thread-specific error buffer
Definition at line 28 of file strerror.c.
Referenced by get_strerror_buf(), and strerror_safe().
Function Documentation
static void free_no_ld (void * buf) static
free() with disabled leak detective
Definition at line 111 of file strerror.c.
References FALSE, free(), library_t::leak_detective, lib, and leak_detective_t::set_state.
Referenced by strerror_init().
 {
     bool old = FALSE;
     if (lib->leak_detective)
     {
         old = lib->leak_detective->set_state(lib->leak_detective, FALSE);
     }
     free(buf);
     if (lib->leak_detective)
     {
         lib->leak_detective->set_state(lib->leak_detective, old);
     }
 }
static char* get_strerror_buf () inline static
Retrieve the error buffer assigned to the current thread (or create it)
Definition at line 45 of file strerror.c.
References FALSE, thread_value_t::get, library_t::leak_detective, lib, malloc(), thread_value_t::set, leak_detective_t::set_state, and STRERROR_BUF_LEN.
Referenced by strerror_safe().
 {
     char *buf;
     bool old = FALSE;
     if (!strerror_buf)
     {
         return NULL;
     }
     buf = strerror_buf->get(strerror_buf);
     if (!buf)
     {
         if (lib->leak_detective)
         {
             old = lib->leak_detective->set_state(lib->leak_detective, FALSE);
         }
         buf = malloc(STRERROR_BUF_LEN);
         strerror_buf->set(strerror_buf, buf);
         if (lib->leak_detective)
         {
             lib->leak_detective->set_state(lib->leak_detective, old);
         }
     }
     return buf;
 }
Variable Documentation
thread_value_t* strerror_buf static
Thread specific strerror buffer, as char*
Definition at line 33 of file strerror.c.
spinlock_t* strerror_lock static
Lock to access strerror() safely
Definition at line 39 of file strerror.c.