strongSwan: tnccs_20_client.c File Reference
tnccs_20_client.c File Reference
#include "tnccs_20_client.h"
#include "messages/pb_tnc_msg.h"
#include "messages/ietf/pb_pa_msg.h"
#include "messages/ietf/pb_error_msg.h"
#include "messages/ietf/pb_assessment_result_msg.h"
#include "messages/ietf/pb_access_recommendation_msg.h"
#include "messages/ietf/pb_remediation_parameters_msg.h"
#include "messages/ietf/pb_reason_string_msg.h"
#include "messages/ietf/pb_language_preference_msg.h"
#include "messages/ita/pb_mutual_capability_msg.h"
#include "messages/ita/pb_noskip_test_msg.h"
#include "messages/tcg/pb_pdp_referral_msg.h"
#include "state_machine/pb_tnc_state_machine.h"
#include <tncif_names.h>
#include <tncif_pa_subtypes.h>
#include <tnc/tnc.h>
#include <tnc/tnccs/tnccs_manager.h>
#include <tnc/imc/imc_manager.h>
#include <threading/mutex.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <pen/pen.h>
Classes
struct private_tnccs_20_client_t
Typedefs
typedef struct
private_tnccs_20_client_t private_tnccs_20_client_t
Functions
void tnccs_20_handle_ietf_error_msg (pb_tnc_msg_t *msg, bool *fatal_error)
bool tnccs_20_handle_ita_mutual_capability_msg (pb_tnc_msg_t *msg)
static void change_batch_type (private_tnccs_20_client_t *this, pb_tnc_batch_type_t batch_type)
static void handle_ietf_message (private_tnccs_20_client_t *this, pb_tnc_msg_t *msg)
static void handle_tcg_message (private_tnccs_20_client_t *this, pb_tnc_msg_t *msg)
static void handle_ita_message (private_tnccs_20_client_t *this, pb_tnc_msg_t *msg)
static void handle_message (private_tnccs_20_client_t *this, pb_tnc_msg_t *msg)
static void build_retry_batch (private_tnccs_20_client_t *this)
METHOD (tnccs_20_handler_t, process, status_t, private_tnccs_20_client_t *this, pb_tnc_batch_t *batch)
METHOD (tnccs_20_handler_t, build, status_t, private_tnccs_20_client_t *this, void *buf, size_t *buflen, size_t *msglen)
METHOD (tnccs_20_handler_t, begin_handshake, void, private_tnccs_20_client_t *this, bool mutual)
METHOD (tnccs_20_handler_t, get_send_flag, bool, private_tnccs_20_client_t *this)
METHOD (tnccs_20_handler_t, get_mutual, bool, private_tnccs_20_client_t *this)
METHOD (tnccs_20_handler_t, get_state, pb_tnc_state_t, private_tnccs_20_client_t *this)
METHOD (tnccs_20_handler_t, add_msg, void, private_tnccs_20_client_t *this, pb_tnc_msg_t *msg)
METHOD (tnccs_20_handler_t, handle_errors, void, private_tnccs_20_client_t *this, pb_tnc_batch_t *batch, bool fatal_header_error)
METHOD (tnccs_20_handler_t, destroy, void, private_tnccs_20_client_t *this)
METHOD (tnccs_20_client_t, get_pdp_server, chunk_t, private_tnccs_20_client_t *this, u_int16_t *port)
tnccs_20_handler_t * tnccs_20_client_create (tnccs_t *tnccs, tnccs_send_message_t send_msg, size_t max_batch_len, size_t max_msg_len)
Typedef Documentation
typedef struct private_tnccs_20_client_t private_tnccs_20_client_t
Definition at line 42 of file tnccs_20_client.c.
Function Documentation
static void build_retry_batch (private_tnccs_20_client_t * this) static
Build a CRETRY batch
Definition at line 447 of file tnccs_20_client.c.
References change_batch_type(), and PB_BATCH_CRETRY.
Referenced by METHOD().
 {
     if (this->batch_type == PB_BATCH_CRETRY)
     {
         /* retry batch has already been selected */
         return;
     }
     change_batch_type(this, PB_BATCH_CRETRY);
 }
static void change_batch_type (private_tnccs_20_client_t * this, pb_tnc_batch_type_t batch_type) static
If the batch type changes then delete all accumulated PB-TNC messages
Definition at line 203 of file tnccs_20_client.c.
References DBG1, DBG_TNC, pb_tnc_msg_t::destroy, msg, PB_BATCH_NONE, pb_tnc_batch_type_names, and SUCCESS.
Referenced by build_retry_batch(), and METHOD().
 {
     pb_tnc_msg_t *msg;
     if (batch_type != this->batch_type)
     {
         if (this->batch_type != PB_BATCH_NONE)
         {
             DBG1(DBG_TNC, "cancelling PB-TNC %N batch",
                  pb_tnc_batch_type_names, this->batch_type);
             while (this->messages->remove_last(this->messages,
                                               (void**)&msg) == SUCCESS)
             {
                 msg->destroy(msg);
             }
         }
         this->batch_type = batch_type;
     }
 }
static void handle_ietf_message (private_tnccs_20_client_t * this, pb_tnc_msg_t * msg) static
Handle a single PB-TNC IETF standard message according to its type
Definition at line 228 of file tnccs_20_client.c.
References DBG1, DBG2, DBG_TNC, FALSE, pb_access_recommendation_msg_t::get_access_recommendation, pb_assessment_result_msg_t::get_assessment_result, pb_pa_msg_t::get_body, pb_pa_msg_t::get_collector_id, pb_pa_msg_t::get_exclusive_flag, pb_reason_string_msg_t::get_language_code, get_pa_subtype_names(), pb_remediation_parameters_msg_t::get_parameters, pb_remediation_parameters_msg_t::get_parameters_type, pb_reason_string_msg_t::get_reason_string, pb_remediation_parameters_msg_t::get_string, pb_pa_msg_t::get_subtype, pb_tnc_msg_t::get_type, pb_pa_msg_t::get_validator_id, tnc_t::imcs, chunk_t::len, imc_manager_t::notify_connection_change, pb_access_recommendation_code_names, PB_MSG_ACCESS_RECOMMENDATION, PB_MSG_ASSESSMENT_RESULT, PB_MSG_ERROR, PB_MSG_EXPERIMENTAL, PB_MSG_PA, PB_MSG_REASON_STRING, PB_MSG_REMEDIATION_PARAMETERS, PB_REC_ACCESS_ALLOWED, PB_REC_ACCESS_DENIED, PB_REC_QUARANTINED, PB_REMEDIATION_STRING, PB_REMEDIATION_URI, PEN_IETF, pen_names, chunk_t::ptr, imc_manager_t::receive_message, result, send_msg(), string, tnc, TNC_CONNECTION_STATE_ACCESS_ALLOWED, TNC_CONNECTION_STATE_ACCESS_ISOLATED, TNC_CONNECTION_STATE_ACCESS_NONE, TNC_IMV_Evaluation_Result_names, tnccs_20_handle_ietf_error_msg(), TRUE, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by handle_message().
 {
     pen_type_t msg_type = msg->get_type(msg);
     switch (msg_type.type)
     {
         case PB_MSG_EXPERIMENTAL:
             /* nothing to do */
             break;
         case PB_MSG_PA:
         {
             pb_pa_msg_t *pa_msg;
             pen_type_t msg_subtype;
             u_int16_t imc_id, imv_id;
             chunk_t msg_body;
             bool excl;
             enum_name_t *pa_subtype_names;
             pa_msg = (pb_pa_msg_t*)msg;
             msg_subtype = pa_msg->get_subtype(pa_msg);
             msg_body = pa_msg->get_body(pa_msg);
             imc_id = pa_msg->get_collector_id(pa_msg);
             imv_id = pa_msg->get_validator_id(pa_msg);
             excl = pa_msg->get_exclusive_flag(pa_msg);
             pa_subtype_names = get_pa_subtype_names(msg_subtype.vendor_id);
             if (pa_subtype_names)
             {
                 DBG2(DBG_TNC, "handling PB-PA message type '%N/%N' 0x%06x/0x%08x",
                      pen_names, msg_subtype.vendor_id, pa_subtype_names,
                      msg_subtype.type, msg_subtype.vendor_id, msg_subtype.type);
             }
             else
             {
                 DBG2(DBG_TNC, "handling PB-PA message type '%N' 0x%06x/0x%08x",
                      pen_names, msg_subtype.vendor_id, msg_subtype.vendor_id,
                      msg_subtype.type);
             }
             this->send_msg = TRUE;
             tnc->imcs->receive_message(tnc->imcs, this->connection_id,
                                        excl, msg_body.ptr, msg_body.len,
                                        msg_subtype.vendor_id,
                                        msg_subtype.type, imv_id, imc_id);
             this->send_msg = FALSE;
             break;
         }
         case PB_MSG_ASSESSMENT_RESULT:
         {
             pb_assessment_result_msg_t *assess_msg;
             u_int32_t result;
             assess_msg = (pb_assessment_result_msg_t*)msg;
             result = assess_msg->get_assessment_result(assess_msg);
             DBG1(DBG_TNC, "PB-TNC assessment result is '%N'",
                  TNC_IMV_Evaluation_Result_names, result);
             break;
         }
         case PB_MSG_ACCESS_RECOMMENDATION:
         {
             pb_access_recommendation_msg_t *rec_msg;
             pb_access_recommendation_code_t rec;
             TNC_ConnectionState state = TNC_CONNECTION_STATE_ACCESS_NONE;
             rec_msg = (pb_access_recommendation_msg_t*)msg;
             rec = rec_msg->get_access_recommendation(rec_msg);
             DBG1(DBG_TNC, "PB-TNC access recommendation is '%N'",
                            pb_access_recommendation_code_names, rec);
             switch (rec)
             {
                 case PB_REC_ACCESS_ALLOWED:
                     state = TNC_CONNECTION_STATE_ACCESS_ALLOWED;
                     break;
                 case PB_REC_ACCESS_DENIED:
                     state = TNC_CONNECTION_STATE_ACCESS_NONE;
                     break;
                 case PB_REC_QUARANTINED:
                     state = TNC_CONNECTION_STATE_ACCESS_ISOLATED;
             }
             tnc->imcs->notify_connection_change(tnc->imcs, this->connection_id,
                                                 state);
             break;
         }
         case PB_MSG_REMEDIATION_PARAMETERS:
         {
             pb_remediation_parameters_msg_t *rem_msg;
             pen_type_t parameters_type;
             chunk_t parameters, string, lang_code;
             rem_msg = (pb_remediation_parameters_msg_t*)msg;
             parameters_type = rem_msg->get_parameters_type(rem_msg);
             parameters = rem_msg->get_parameters(rem_msg);
             if (parameters_type.vendor_id == PEN_IETF)
             {
                 switch (parameters_type.type)
                 {
                     case PB_REMEDIATION_URI:
                         DBG1(DBG_TNC, "remediation uri: %.*s",
                                        parameters.len, parameters.ptr);
                         break;
                     case PB_REMEDIATION_STRING:
                         string = rem_msg->get_string(rem_msg, &lang_code);
                         DBG1(DBG_TNC, "remediation string: [%.*s]\n%.*s",
                                        lang_code.len, lang_code.ptr,
                                        string.len, string.ptr);
                         break;
                     default:
                         DBG1(DBG_TNC, "remediation parameters: %B", &parameters);
                 }
             }
             else
             {
                 DBG1(DBG_TNC, "remediation parameters: %B", &parameters);
             }
             break;
         }
         case PB_MSG_ERROR:
             tnccs_20_handle_ietf_error_msg(msg, &this->fatal_error);
             break;
         case PB_MSG_REASON_STRING:
         {
             pb_reason_string_msg_t *reason_msg;
             chunk_t reason_string, language_code;
             reason_msg = (pb_reason_string_msg_t*)msg;
             reason_string = reason_msg->get_reason_string(reason_msg);
             language_code = reason_msg->get_language_code(reason_msg);
             DBG1(DBG_TNC, "reason string is '%.*s' [%.*s]",
                  (int)reason_string.len, reason_string.ptr,
                  (int)language_code.len, language_code.ptr);
             break;
         }
         default:
             break;
     }
 }
static void handle_ita_message (private_tnccs_20_client_t * this, pb_tnc_msg_t * msg) static
Handle a single PB-TNC ITA standard message according to its type
Definition at line 407 of file tnccs_20_client.c.
References pb_tnc_msg_t::get_type, PB_ITA_MSG_MUTUAL_CAPABILITY, tnccs_20_handle_ita_mutual_capability_msg(), and pen_type_t::type.
Referenced by handle_message().
 {
     pen_type_t msg_type = msg->get_type(msg);
     switch (msg_type.type)
     {
         case PB_ITA_MSG_MUTUAL_CAPABILITY:
             this->mutual = tnccs_20_handle_ita_mutual_capability_msg(msg);
             break;
         default:
             break;
     }
 }
static void handle_message (private_tnccs_20_client_t * this, pb_tnc_msg_t * msg) static
Handle a single PB-TNC message according to its type
Definition at line 424 of file tnccs_20_client.c.
References pb_tnc_msg_t::get_type, handle_ietf_message(), handle_ita_message(), handle_tcg_message(), PEN_IETF, PEN_ITA, PEN_TCG, and pen_type_t::vendor_id.
Referenced by METHOD().
 {
     pen_type_t msg_type = msg->get_type(msg);
     switch (msg_type.vendor_id)
     {
         case PEN_IETF:
             handle_ietf_message(this, msg);
             break;
         case PEN_TCG:
             handle_tcg_message(this, msg);
             break;
         case PEN_ITA:
             handle_ita_message(this, msg);
             break;
         default:
             break;
     }
 }
static void handle_tcg_message (private_tnccs_20_client_t * this, pb_tnc_msg_t * msg) static
Handle a single PB-TNC TCG standard message according to its type
Definition at line 368 of file tnccs_20_client.c.
References chunk_clone, DBG1, DBG_TNC, pb_pdp_referral_msg_t::get_fqdn, pb_pdp_referral_msg_t::get_identifier_type, pb_tnc_msg_t::get_type, PB_PDP_ID_FQDN, PB_TCG_MSG_PDP_REFERRAL, PEN_TCG, pen_type_t::type, and pen_type_t::vendor_id.
Referenced by handle_message().
 {
     pen_type_t msg_type = msg->get_type(msg);
     switch (msg_type.type)
     {
         case PB_TCG_MSG_PDP_REFERRAL:
         {
             pb_pdp_referral_msg_t *pdp_msg;
             pen_type_t pdp_id_type;
             u_int8_t pdp_protocol;
             pdp_msg = (pb_pdp_referral_msg_t*)msg;
             pdp_id_type = pdp_msg->get_identifier_type(pdp_msg);
             if (pdp_id_type.vendor_id == PEN_TCG &&
                 pdp_id_type.type == PB_PDP_ID_FQDN)
             {
                 this->pdp_server = chunk_clone(pdp_msg->get_fqdn(pdp_msg,
                                          &pdp_protocol, &this->pdp_port));
                 if (pdp_protocol != 0)
                 {
                     DBG1(DBG_TNC, "unsupported PDP transport protocol");
                     break;
                 }
                 DBG1(DBG_TNC, "PDP server '%.*s' is listening on port %u",
                                this->pdp_server.len, this->pdp_server.ptr,
                                this->pdp_port);
             }
             break;
         }
         default:
             break;
     }
 }
METHOD (tnccs_20_handler_t , process , status_t , private_tnccs_20_client_t * this, pb_tnc_batch_t * batch)
Definition at line 457 of file tnccs_20_client.c.
References imc_manager_t::batch_ending, imc_manager_t::begin_handshake, pb_tnc_batch_t::create_msg_enumerator, DBG1, DBG_TNC, enumerator_t::destroy, enumerator_t::enumerate, FAILED, FALSE, pb_tnc_batch_t::get_type, handle_message(), tnc_t::imcs, msg, NEED_MORE, imc_manager_t::notify_connection_change, PB_BATCH_CLOSE, PB_BATCH_SRETRY, pb_tnc_batch_type_names, pb_tnc_batch_t::process, send_msg(), status, SUCCESS, tnc, TNC_CONNECTION_STATE_HANDSHAKE, TRUE, and VERIFY_ERROR.
 {
     pb_tnc_batch_type_t batch_type;
     status_t status;
     batch_type = batch->get_type(batch);
     DBG1(DBG_TNC, "processing PB-TNC %N batch for Connection ID %d",
          pb_tnc_batch_type_names, batch_type, this->connection_id);
     status = batch->process(batch, this->state_machine);
     if (status != FAILED)
     {
         enumerator_t *enumerator;
         pb_tnc_msg_t *msg;
         bool empty = TRUE;
         if (batch_type == PB_BATCH_SRETRY)
         {
             /* Restart the measurements */
             tnc->imcs->notify_connection_change(tnc->imcs,
                         this->connection_id, TNC_CONNECTION_STATE_HANDSHAKE);
             this->send_msg = TRUE;
             tnc->imcs->begin_handshake(tnc->imcs, this->connection_id);
             this->send_msg = FALSE;
         }
         enumerator = batch->create_msg_enumerator(batch);
         while (enumerator->enumerate(enumerator, &msg))
         {
             handle_message(this, msg);
             empty = FALSE;
         }
         enumerator->destroy(enumerator);
         /* received a CLOSE batch from PB-TNC server */
         if (batch_type == PB_BATCH_CLOSE)
         {
             return empty ? SUCCESS : FAILED;
         }
         this->send_msg = TRUE;
         tnc->imcs->batch_ending(tnc->imcs, this->connection_id);
         this->send_msg = FALSE;
     }
     switch (status)
     {
         case FAILED:
             this->fatal_error = TRUE;
             status = VERIFY_ERROR;
             break;
         case VERIFY_ERROR:
             break;
         case SUCCESS:
         default:
             status = NEED_MORE;
             break;
     }
     return status;
 }
METHOD (tnccs_20_handler_t , build , status_t , private_tnccs_20_client_t * this, void * buf, size_t * buflen, size_t * msglen)
In the DECIDED state and if no CRETRY is under way, a PB-TNC client replies with an empty CLOSE batch.
Definition at line 522 of file tnccs_20_client.c.
References pb_tnc_batch_t::add_msg, ALREADY_DONE, batch(), pb_tnc_batch_t::build, build_retry_batch(), change_batch_type(), data, DBG1, DBG2, DBG3, DBG_TNC, enumerator_t::destroy, pb_tnc_batch_t::destroy, enumerator_t::enumerate, FAILED, FALSE, pb_tnc_batch_t::get_encoding, INVALID_STATE, chunk_t::len, mutex_t::lock, memcpy, min, msg, mutex, PB_BATCH_CDATA, PB_BATCH_CLOSE, PB_BATCH_NONE, PB_STATE_CLIENT_WORKING, PB_STATE_DECIDED, PB_STATE_END, PB_STATE_INIT, pb_tnc_batch_create(), pb_tnc_batch_type_names, chunk_t::ptr, status, and mutex_t::unlock.
 {
     status_t status;
     pb_tnc_state_t state;
     state = this->state_machine->get_state(this->state_machine);
     if (this->fatal_error && state == PB_STATE_END)
     {
         DBG1(DBG_TNC, "a fatal PB-TNC error occurred, terminating connection");
         return FAILED;
     }
     /* Do not allow any asynchronous IMCs to add additional messages */
     this->mutex->lock(this->mutex);
     if (this->request_handshake_retry)
     {
         if (state != PB_STATE_INIT)
         {
             build_retry_batch(this);
         }
         /* Reset the flag for the next handshake retry request */
         this->request_handshake_retry = FALSE;
     }
     if (this->batch_type == PB_BATCH_NONE)
     {
         switch (state)
         {
             case PB_STATE_CLIENT_WORKING:
                 DBG2(DBG_TNC, "no client data to send, "
                               "sending empty PB-TNC CDATA batch");
                 this->batch_type = PB_BATCH_CDATA;
                 break;
             case PB_STATE_DECIDED:
                 this->batch_type = PB_BATCH_CLOSE;
                 break;
             default:
                 break;
         }
     }
     if (this->batch_type != PB_BATCH_NONE)
     {
         pb_tnc_batch_t *batch;
         pb_tnc_msg_t *msg;
         chunk_t data;
         int msg_count;
         enumerator_t *enumerator;
         if (this->state_machine->send_batch(this->state_machine, this->batch_type))
         {
             batch = pb_tnc_batch_create(FALSE, this->batch_type,
                                         min(this->max_batch_len, *buflen));
             enumerator = this->messages->create_enumerator(this->messages);
             while (enumerator->enumerate(enumerator, &msg))
             {
                 if (batch->add_msg(batch, msg))
                 {
                     this->messages->remove_at(this->messages, enumerator);
                 }
                 else
                 {
                     break;
                 }
             }
             enumerator->destroy(enumerator);
             batch->build(batch);
             data = batch->get_encoding(batch);
             DBG1(DBG_TNC, "sending PB-TNC %N batch (%d bytes) for Connection ID %u",
                            pb_tnc_batch_type_names, this->batch_type, data.len,
                            this->connection_id);
             DBG3(DBG_TNC, "%B", &data);
             *buflen = data.len;
             *msglen = 0;
             memcpy(buf, data.ptr, *buflen);
             batch->destroy(batch);
             msg_count = this->messages->get_count(this->messages);
             if (msg_count)
             {
                 DBG2(DBG_TNC, "queued %d PB-TNC message%s for next %N batch",
                      msg_count, (msg_count == 1) ? "" : "s",
                      pb_tnc_batch_type_names, this->batch_type);
             }
             else
             {
                 this->batch_type = PB_BATCH_NONE;
             }
             status = ALREADY_DONE;
         }
         else
         {
             change_batch_type(this, PB_BATCH_NONE);
             status = INVALID_STATE;
         }
     }
     else
     {
         DBG1(DBG_TNC, "no PB-TNC batch to send");
         status = INVALID_STATE;
     }
     this->mutex->unlock(this->mutex);
     return status;
 }
METHOD (tnccs_20_handler_t , begin_handshake , void , private_tnccs_20_client_t * this, bool mutual)
Definition at line 640 of file tnccs_20_client.c.
References imc_manager_t::begin_handshake, chunk_create(), DBG2, DBG_TNC, FALSE, settings_t::get_bool, imc_manager_t::get_preferred_language, tnc_t::imcs, lib, mutex_t::lock, msg, mutex, imc_manager_t::notify_connection_change, library_t::ns, pb_language_preference_msg_create(), pb_mutual_capability_msg_create(), PB_MUTUAL_HALF_DUPLEX, pb_noskip_test_msg_create(), pb_tnc_mutual_protocol_type_names, send_msg(), library_t::settings, tnc, TNC_CONNECTION_STATE_HANDSHAKE, TRUE, and mutex_t::unlock.
 {
     pb_tnc_msg_t *msg;
     char *pref_lang;
     tnc->imcs->notify_connection_change(tnc->imcs, this->connection_id,
                                         TNC_CONNECTION_STATE_HANDSHAKE);
     /* Announce PB-TNC Mutual Capability if activated */
     this->sent_mutual_capability = mutual;
     if (!mutual && lib->settings->get_bool(lib->settings,
                 "%s.plugins.tnccs-20.mutual", FALSE, lib->ns))
     {
         pb_tnc_mutual_protocol_type_t protocols;
         protocols = PB_MUTUAL_HALF_DUPLEX;
         DBG2(DBG_TNC, "proposing PB-TNC mutual %N protocol",
              pb_tnc_mutual_protocol_type_names, PB_MUTUAL_HALF_DUPLEX);
         msg = pb_mutual_capability_msg_create(protocols);
         this->mutex->lock(this->mutex);
         this->messages->insert_last(this->messages, msg);
         this->mutex->unlock(this->mutex);
         this->sent_mutual_capability = TRUE;
     }
     /* Create PB-TNC Language Preference message */
     pref_lang = tnc->imcs->get_preferred_language(tnc->imcs);
     msg = pb_language_preference_msg_create(chunk_create(pref_lang,
                                                 strlen(pref_lang)));
     this->mutex->lock(this->mutex);
     this->messages->insert_last(this->messages, msg);
     this->mutex->unlock(this->mutex);
     this->send_msg = TRUE;
     tnc->imcs->begin_handshake(tnc->imcs, this->connection_id);
     this->send_msg = FALSE;
     /* Send a PB-Noskip-Test message for testing purposes */
     if (lib->settings->get_bool(lib->settings,
                 "%s.plugins.tnccs-20.tests.pb_tnc_noskip", FALSE, lib->ns))
     {
         msg = pb_noskip_test_msg_create();
         this->mutex->lock(this->mutex);
         this->messages->insert_last(this->messages, msg);
         this->mutex->unlock(this->mutex);
     }
 }
METHOD (tnccs_20_handler_t , get_send_flag , bool , private_tnccs_20_client_t * this)
Definition at line 690 of file tnccs_20_client.c.
References send_msg().
 {
     return this->send_msg;
 }
METHOD (tnccs_20_handler_t , get_mutual , bool , private_tnccs_20_client_t * this)
Definition at line 696 of file tnccs_20_client.c.
 {
     return this->mutual;
 }
METHOD (tnccs_20_handler_t , get_state , pb_tnc_state_t , private_tnccs_20_client_t * this)
Definition at line 702 of file tnccs_20_client.c.
 {
     return this->state_machine->get_state(this->state_machine);
 }
METHOD (tnccs_20_handler_t , add_msg , void , private_tnccs_20_client_t * this, pb_tnc_msg_t * msg)
Definition at line 708 of file tnccs_20_client.c.
References pb_tnc_msg_t::destroy, mutex_t::lock, mutex, PB_BATCH_CDATA, PB_BATCH_NONE, and mutex_t::unlock.
 {
     /* adding PA message to CDATA batch only */
     this->mutex->lock(this->mutex);
     if (this->batch_type == PB_BATCH_NONE)
     {
         this->batch_type = PB_BATCH_CDATA;
     }
     if (this->batch_type == PB_BATCH_CDATA)
     {
         this->messages->insert_last(this->messages, msg);
     }
     else
     {
         msg->destroy(msg);
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (tnccs_20_handler_t , handle_errors , void , private_tnccs_20_client_t * this, pb_tnc_batch_t * batch, bool fatal_header_error)
Definition at line 728 of file tnccs_20_client.c.
References change_batch_type(), pb_tnc_batch_t::create_error_enumerator, enumerator_t::destroy, enumerator_t::enumerate, pb_tnc_msg_t::get_ref, mutex_t::lock, msg, mutex, PB_BATCH_CLOSE, and mutex_t::unlock.
 {
     pb_tnc_msg_t *msg;
     enumerator_t *enumerator;
     if (fatal_header_error || this->fatal_error)
     {
         this->mutex->lock(this->mutex);
         change_batch_type(this, PB_BATCH_CLOSE);
         this->mutex->unlock(this->mutex);
     }
     enumerator = batch->create_error_enumerator(batch);
     while (enumerator->enumerate(enumerator, &msg))
     {
         this->mutex->lock(this->mutex);
         this->messages->insert_last(this->messages, msg->get_ref(msg));
         this->mutex->unlock(this->mutex);
     }
     enumerator->destroy(enumerator);
 }
METHOD (tnccs_20_handler_t , destroy , void , private_tnccs_20_client_t * this)
Definition at line 752 of file tnccs_20_client.c.
References mutex_t::destroy, destroy(), FALSE, free(), mutex, tnccs_manager_t::remove_connection, tnc, and tnc_t::tnccs.
 {
     if (this->connection_id)
     {
         tnc->tnccs->remove_connection(tnc->tnccs, this->connection_id, FALSE);
     }
     this->state_machine->destroy(this->state_machine);
     this->mutex->destroy(this->mutex);
     this->messages->destroy_offset(this->messages,
                                    offsetof(pb_tnc_msg_t, destroy));
     free(this->pdp_server.ptr);
     free(this);
 }
METHOD (tnccs_20_client_t , get_pdp_server , chunk_t , private_tnccs_20_client_t * this, u_int16_t * port)
Definition at line 767 of file tnccs_20_client.c.
 {
     *port = this->pdp_port;
     return this->pdp_server;
 }
void tnccs_20_handle_ietf_error_msg (pb_tnc_msg_t * msg, bool * fatal_error)
The following two functions are shared with the tnccs_20_server class
Definition at line 124 of file tnccs_20_client.c.
References DBG1, DBG_TNC, error_code, pb_error_msg_t::get_bad_version, pb_error_msg_t::get_error_code, pb_error_msg_t::get_fatal_flag, pb_error_msg_t::get_offset, pb_error_msg_t::get_vendor_id, PB_ERROR_INVALID_PARAMETER, PB_ERROR_LOCAL_ERROR, PB_ERROR_UNEXPECTED_BATCH_TYPE, PB_ERROR_UNSUPPORTED_MANDATORY_MSG, PB_ERROR_VERSION_NOT_SUPPORTED, pb_tnc_error_code_names, PEN_IETF, and TRUE.
Referenced by handle_ietf_message().
 {
     pb_error_msg_t *err_msg;
     u_int32_t vendor_id;
     u_int16_t error_code;
     bool fatal;
     err_msg = (pb_error_msg_t*)msg;
     fatal = err_msg->get_fatal_flag(err_msg);
     vendor_id = err_msg->get_vendor_id(err_msg);
     error_code = err_msg->get_error_code(err_msg);
     if (fatal)
     {
         *fatal_error = TRUE;
     }
     if (vendor_id == PEN_IETF)
     {
         switch (error_code)
         {
             case PB_ERROR_INVALID_PARAMETER:
             case PB_ERROR_UNSUPPORTED_MANDATORY_MSG:
                 DBG1(DBG_TNC, "received %s PB-TNC error '%N' (offset %u bytes)",
                               fatal ? "fatal" : "non-fatal",
                               pb_tnc_error_code_names, error_code,
                               err_msg->get_offset(err_msg));
                 break;
             case PB_ERROR_VERSION_NOT_SUPPORTED:
                 DBG1(DBG_TNC, "received %s PB-TNC error '%N' "
                               "caused by bad version 0x%02x",
                               fatal ? "fatal" : "non-fatal",
                               pb_tnc_error_code_names, error_code,
                               err_msg->get_bad_version(err_msg));
                 break;
             case PB_ERROR_UNEXPECTED_BATCH_TYPE:
             case PB_ERROR_LOCAL_ERROR:
             default:
                 DBG1(DBG_TNC, "received %s PB-TNC error '%N'",
                               fatal ? "fatal" : "non-fatal",
                               pb_tnc_error_code_names, error_code);
                 break;
         }
     }
     else
     {
         DBG1(DBG_TNC, "received %s PB-TNC error (%u) with Vendor ID 0x%06x",
                       fatal ? "fatal" : "non-fatal", error_code, vendor_id);
     }
 }
bool tnccs_20_handle_ita_mutual_capability_msg (pb_tnc_msg_t * msg)
Definition at line 175 of file tnccs_20_client.c.
References DBG1, DBG_TNC, FALSE, settings_t::get_bool, pb_mutual_capability_msg_t::get_protocols, lib, library_t::ns, PB_MUTUAL_HALF_DUPLEX, pb_tnc_mutual_protocol_type_names, library_t::settings, and TRUE.
Referenced by handle_ita_message().
 {
     pb_mutual_capability_msg_t *mutual_msg;
     uint32_t protocols;
     if (!lib->settings->get_bool(lib->settings,
                 "%s.plugins.tnccs-20.mutual", FALSE, lib->ns))
     {
         /* PB-TNC mutual capability disabled, ignore message */
         return FALSE;
     }
     mutual_msg = (pb_mutual_capability_msg_t*)msg;
     protocols = mutual_msg->get_protocols(mutual_msg);
     if (protocols & PB_MUTUAL_HALF_DUPLEX)
     {
         DBG1(DBG_TNC, "activating mutual PB-TNC %N protocol",
              pb_tnc_mutual_protocol_type_names, PB_MUTUAL_HALF_DUPLEX);
         return TRUE;
     }
     return FALSE;
 }