strongSwan: swid_tag
swid_tag
swid
Classes
struct swid_tag_t
Typedefs
typedef struct swid_tag_t swid_tag_t
Functions
swid_tag_t * swid_tag_create (chunk_t encoding, chunk_t instance_id)
Detailed Description
Typedef Documentation
typedef struct swid_tag_t swid_tag_t
Definition at line 26 of file swid_tag.h.
Function Documentation
swid_tag_t* swid_tag_create (chunk_t encoding, chunk_t instance_id)
Creates a swid_tag_t object
Parameters
encoding XML encoding of SWID tag
instance_id Tag Identifier Instance ID or empty chunk
See header
Definition at line 80 of file swid_tag.c.
References chunk_clone, INIT, and chunk_t::len.
Referenced by collect_tags(), METHOD(), and read_swid_tags().
 {
     private_swid_tag_t *this;
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .get_instance_id = _get_instance_id,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .encoding = chunk_clone(encoding),
         .ref = 1,
     );
     if (instance_id.len > 0)
     {
         this->instance_id = chunk_clone(instance_id);
     }
     return &this->public;
 }