strongSwan: esp_packet
esp_packet
libipsec
Classes
struct esp_packet_t
Typedefs
typedef struct esp_packet_t esp_packet_t
Functions
esp_packet_t * esp_packet_create_from_packet (packet_t *packet)
esp_packet_t * esp_packet_create_from_payload (host_t *src, host_t *dst, ip_packet_t *payload)
Detailed Description
Typedef Documentation
typedef struct esp_packet_t esp_packet_t
Definition at line 33 of file esp_packet.h.
Function Documentation
esp_packet_t* esp_packet_create_from_packet (packet_t * packet)
Create an ESP packet out of data from the wire.
Parameters
packet the packet data as received, gets owned
Returns
esp_packet_t instance
Described in header.
Definition at line 439 of file esp_packet.c.
References esp_packet_create_internal().
Referenced by receiver_esp_cb().
 {
     private_esp_packet_t *this;
     this = esp_packet_create_internal(packet);
     return &this->public;
 }
esp_packet_t* esp_packet_create_from_payload (host_t * src, host_t * dst, ip_packet_t * payload)
Create an ESP packet from a plaintext payload
Parameters
src source address
dst destination address
payload plaintext payload, gets owned
Returns
esp_packet_t instance
Described in header.
Definition at line 451 of file esp_packet.c.
References chunk_empty, esp_packet_create_internal(), ip_packet_t::get_version, IPPROTO_IPIP, IPPROTO_IPV6, and packet_create_from_data().
Referenced by process_outbound(), and START_TEST().
 {
     private_esp_packet_t *this;
     packet_t *packet;
     packet = packet_create_from_data(src, dst, chunk_empty);
     this = esp_packet_create_internal(packet);
     this->payload = payload;
     if (payload)
     {
         this->next_header = payload->get_version(payload) == 4 ? IPPROTO_IPIP
                                                                : IPPROTO_IPV6;
     }
     else
     {
         this->next_header = IPPROTO_NONE;
     }
     return &this->public;
 }