strongSwan: kernel_pfkey_ipsec
kernel_pfkey_ipsec
kernel_pfkey
Classes
struct kernel_pfkey_ipsec_t
Typedefs
typedef struct kernel_pfkey_ipsec_t kernel_pfkey_ipsec_t
Functions
kernel_pfkey_ipsec_t * kernel_pfkey_ipsec_create ()
Variables
struct kernel_pfkey_ipsec_t __attribute__
Detailed Description
Typedef Documentation
typedef struct kernel_pfkey_ipsec_t kernel_pfkey_ipsec_t
Definition at line 26 of file kernel_pfkey_ipsec.h.
Function Documentation
kernel_pfkey_ipsec_t* kernel_pfkey_ipsec_create ()
Create a PF_KEY kernel ipsec interface instance.
Returns
kernel_pfkey_ipsec_t instance
Definition at line 3015 of file kernel_pfkey_ipsec.c.
References watcher_t::add, DBG1, DBG_KNL, destroy(), FALSE, settings_t::get_bool, settings_t::get_int, hashtable_create(), INIT, ipsec_sa_equals(), ipsec_sa_hash(), lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, PF_KEY_V2, receive_events(), register_pfkey_socket(), SADB_SATYPE_AH, SADB_SATYPE_ESP, setsockopt, library_t::settings, socket, streq(), strerror, SUCCESS, TRUE, library_t::watcher, and WATCHER_READ.
Referenced by METHOD().
 {
     private_kernel_pfkey_ipsec_t *this;
     bool register_for_events = TRUE;
     int rcv_buffer;
     INIT(this,
         .public = {
             .interface = {
                 .get_spi = _get_spi,
                 .get_cpi = _get_cpi,
                 .add_sa  = _add_sa,
                 .update_sa = _update_sa,
                 .query_sa = _query_sa,
                 .del_sa = _del_sa,
                 .flush_sas = _flush_sas,
                 .add_policy = _add_policy,
                 .query_policy = _query_policy,
                 .del_policy = _del_policy,
                 .flush_policies = _flush_policies,
                 .bypass_socket = _bypass_socket,
                 .enable_udp_decap = _enable_udp_decap,
                 .destroy = _destroy,
             },
         },
         .policies = linked_list_create(),
         .excludes = linked_list_create(),
         .sas = hashtable_create((hashtable_hash_t)ipsec_sa_hash,
                                 (hashtable_equals_t)ipsec_sa_equals, 32),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .mutex_pfkey = mutex_create(MUTEX_TYPE_DEFAULT),
         .install_routes = lib->settings->get_bool(lib->settings,
                                                   "%s.install_routes", TRUE,
                                                   lib->ns),
     );
     if (streq(lib->ns, "starter"))
     {   /* starter has no threads, so we do not register for kernel events */
         register_for_events = FALSE;
     }
     /* create a PF_KEY socket to communicate with the kernel */
     this->socket = socket(PF_KEY, SOCK_RAW, PF_KEY_V2);
     if (this->socket <= 0)
     {
         DBG1(DBG_KNL, "unable to create PF_KEY socket");
         destroy(this);
         return NULL;
     }
     if (register_for_events)
     {
         /* create a PF_KEY socket for ACQUIRE & EXPIRE */
         this->socket_events = socket(PF_KEY, SOCK_RAW, PF_KEY_V2);
         if (this->socket_events <= 0)
         {
             DBG1(DBG_KNL, "unable to create PF_KEY event socket");
             destroy(this);
             return NULL;
         }
         rcv_buffer = lib->settings->get_int(lib->settings,
                     "%s.plugins.kernel-pfkey.events_buffer_size", 0, lib->ns);
         if (rcv_buffer > 0)
         {
             if (setsockopt(this->socket_events, SOL_SOCKET, SO_RCVBUF,
                            &rcv_buffer, sizeof(rcv_buffer)) == -1)
             {
                 DBG1(DBG_KNL, "unable to set receive buffer size on PF_KEY "
                      "event socket: %s", strerror(errno));
             }
         }
         /* register the event socket */
         if (register_pfkey_socket(this, SADB_SATYPE_ESP) != SUCCESS ||
             register_pfkey_socket(this, SADB_SATYPE_AH) != SUCCESS)
         {
             DBG1(DBG_KNL, "unable to register PF_KEY event socket");
             destroy(this);
             return NULL;
         }
         lib->watcher->add(lib->watcher, this->socket_events, WATCHER_READ,
                           (watcher_cb_t)receive_events, this);
     }
     return &this->public;
 }
Variable Documentation
struct kernel_pfkey_ipsec_t __attribute__