strongSwan: bridge.c File Reference
bridge.c File Reference
#include <sys/types.h>
#include <netinet/in.h>
#include <libbridge.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
#include "bridge.h"
Classes
struct private_bridge_t
Typedefs
typedef struct private_bridge_t private_bridge_t
Functions
bool iface_control (char *name, bool up)
METHOD (bridge_t, get_name, char *, private_bridge_t *this)
METHOD (bridge_t, create_iface_enumerator, enumerator_t *, private_bridge_t *this)
METHOD (bridge_t, disconnect_iface, bool, private_bridge_t *this, iface_t *iface)
METHOD (bridge_t, connect_iface, bool, private_bridge_t *this, iface_t *iface)
METHOD (bridge_t, destroy, void, private_bridge_t *this)
bridge_t * bridge_create (char *name)
Variables
static int instances = 0
Typedef Documentation
typedef struct private_bridge_t private_bridge_t
Definition at line 25 of file bridge.c.
Function Documentation
bridge_t* bridge_create (char * name)
create the bridge instance
Definition at line 142 of file bridge.c.
References DBG1, DBG_LIB, free(), iface_control(), INIT, instances, linked_list_create(), strdup, and TRUE.
Referenced by METHOD().
 {
     private_bridge_t *this;
     if (instances == 0)
     {
         if (br_init() != 0)
         {
             DBG1(DBG_LIB, "libbridge initialization failed: %m");
             return NULL;
         }
     }
     INIT(this,
         .public = {
             .get_name = _get_name,
             .create_iface_enumerator = _create_iface_enumerator,
             .disconnect_iface = _disconnect_iface,
             .connect_iface = _connect_iface,
             .destroy = _destroy,
         }
     );
     if (br_add_bridge(name) != 0)
     {
         DBG1(DBG_LIB, "creating bridge '%s' failed: %m", name);
         free(this);
         return NULL;
     }
     if (!iface_control(name, TRUE))
     {
         DBG1(DBG_LIB, "bringing bridge '%s' up failed: %m", name);
     }
     this->name = strdup(name);
     this->ifaces = linked_list_create();
     instances++;
     return &this->public;
 }
bool iface_control (char * name, bool up)
defined in iface.c
bring an interface up or down (host side)
Definition at line 53 of file iface.c.
References close, FALSE, good, memset, s, socket, and TRUE.
Referenced by bridge_create(), destroy_tap(), iface_create(), and METHOD().
 {
     int s;
     bool good = FALSE;
     struct ifreq ifr;
     memset(&ifr, 0, sizeof(struct ifreq));
     strncpy(ifr.ifr_name, name, sizeof(ifr.ifr_name));
     s = socket(AF_INET, SOCK_DGRAM, 0);
     if (!s)
     {
         return FALSE;
     }
     if (ioctl(s, SIOCGIFFLAGS, &ifr) == 0)
     {
         if (up)
         {
             ifr.ifr_flags |= IFF_UP;
         }
         else
         {
             ifr.ifr_flags &= ~IFF_UP;
         }
         if (ioctl(s, SIOCSIFFLAGS, &ifr) == 0)
         {
             good = TRUE;
         }
     }
     close(s);
     return good;
 }
METHOD (bridge_t , get_name , char * , private_bridge_t * this)
Definition at line 41 of file bridge.c.
References name.
 {
     return this->name;
 }
METHOD (bridge_t , create_iface_enumerator , enumerator_t * , private_bridge_t * this)
Definition at line 47 of file bridge.c.
 {
     return this->ifaces->create_enumerator(this->ifaces);
 }
METHOD (bridge_t , disconnect_iface , bool , private_bridge_t * this, iface_t * iface)
Definition at line 53 of file bridge.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, FALSE, iface_t::get_hostif, good, name, iface_t::set_bridge, and TRUE.
 {
     enumerator_t *enumerator;
     iface_t *current = NULL;
     bool good = FALSE;
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current == iface)
         {
             if (br_del_interface(this->name, iface->get_hostif(iface)) != 0)
             {
                 DBG1(DBG_LIB, "removing iface '%s' from bridge '%s' in kernel"
                      " failed: %m", iface->get_hostif(iface), this->name);
             }
             else
             {
                 iface->set_bridge(iface, NULL);
                 this->ifaces->remove_at(this->ifaces, enumerator);
                 good = TRUE;
             }
             break;
         }
     }
     if (iface != current)
     {
         DBG1(DBG_LIB, "iface '%s' not found on bridge '%s'",
              iface->get_hostif(iface), this->name);
     }
     enumerator->destroy(enumerator);
     return good;
 }
METHOD (bridge_t , connect_iface , bool , private_bridge_t * this, iface_t * iface)
Definition at line 88 of file bridge.c.
References DBG1, DBG_LIB, FALSE, iface_t::get_hostif, name, iface_t::set_bridge, and TRUE.
 {
     if (br_add_interface(this->name, iface->get_hostif(iface)) != 0)
     {
         DBG1(DBG_LIB, "adding iface '%s' to bridge '%s' failed: %m",
              iface->get_hostif(iface), this->name);
         return FALSE;
     }
     iface->set_bridge(iface, &this->public);
     this->ifaces->insert_last(this->ifaces, iface);
     return TRUE;
 }
METHOD (bridge_t , destroy , void , private_bridge_t * this)
Definition at line 107 of file bridge.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, FALSE, free(), iface_t::get_hostif, iface_control(), instances, name, and iface_t::set_bridge.
 {
     enumerator_t *enumerator;
     iface_t *iface;
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, (void**)&iface))
     {
         if (br_del_interface(this->name, iface->get_hostif(iface)) != 0)
         {
             DBG1(DBG_LIB, "disconnecting iface '%s' failed: %m",
                  iface->get_hostif(iface));
         }
         iface->set_bridge(iface, NULL);
     }
     enumerator->destroy(enumerator);
     this->ifaces->destroy(this->ifaces);
     iface_control(this->name, FALSE);
     if (br_del_bridge(this->name) != 0)
     {
         DBG1(DBG_LIB, "deleting bridge '%s' from kernel failed: %m",
              this->name);
     }
     free(this->name);
     free(this);
     if (--instances == 0)
     {
         br_shutdown();
     }
 }
Variable Documentation
int instances = 0 static
instance counter to (de-)initialize libbridge
Definition at line 105 of file bridge.c.
Referenced by bridge_create(), and METHOD().