strongSwan: ike_sa_manager.c File Reference
ike_sa_manager.c File Reference
#include <string.h>
#include "ike_sa_manager.h"
#include <daemon.h>
#include <sa/ike_sa_id.h>
#include <bus/bus.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
#include <threading/rwlock.h>
#include <collections/linked_list.h>
#include <crypto/hashers/hasher.h>
#include <processing/jobs/delete_ike_sa_job.h>
Classes
struct entry_t
struct half_open_t
struct connected_peers_t
struct init_hash_t
struct segment_t
struct shareable_segment_t
struct table_item_t
struct private_ike_sa_manager_t
struct private_enumerator_t
Macros
#define DEFAULT_HASHTABLE_SIZE 1
#define MAX_HASHTABLE_SIZE (1 << 30)
#define DEFAULT_SEGMENT_COUNT 1
Typedefs
typedef struct entry_t entry_t
typedef struct half_open_t half_open_t
typedef struct connected_peers_t connected_peers_t
typedef struct init_hash_t init_hash_t
typedef struct segment_t segment_t
typedef struct shareable_segment_t shareable_segment_t
typedef struct table_item_t table_item_t
typedef struct
private_ike_sa_manager_t private_ike_sa_manager_t
typedef struct private_enumerator_t private_enumerator_t
Functions
static status_t entry_destroy (entry_t *this)
static entry_t * entry_create ()
static bool entry_match_by_id (entry_t *entry, ike_sa_id_t *id)
static bool entry_match_by_sa (entry_t *entry, ike_sa_t *ike_sa)
static u_int ike_sa_id_hash (ike_sa_id_t *ike_sa_id)
static void half_open_destroy (half_open_t *this)
static void connected_peers_destroy (connected_peers_t *this)
static bool connected_peers_match (connected_peers_t *connected_peers, identification_t *my_id, identification_t *other_id, int family)
static void lock_single_segment (private_ike_sa_manager_t *this, u_int index)
static void unlock_single_segment (private_ike_sa_manager_t *this, u_int index)
static void lock_all_segments (private_ike_sa_manager_t *this)
static void unlock_all_segments (private_ike_sa_manager_t *this)
METHOD (enumerator_t, enumerate, bool, private_enumerator_t *this, entry_t **entry, u_int *segment)
METHOD (enumerator_t, enumerator_destroy, void, private_enumerator_t *this)
static enumerator_t * create_table_enumerator (private_ike_sa_manager_t *this)
static u_int put_entry (private_ike_sa_manager_t *this, entry_t *entry)
static void remove_entry (private_ike_sa_manager_t *this, entry_t *entry)
static void remove_entry_at (private_enumerator_t *this)
static status_t get_entry_by_match_function (private_ike_sa_manager_t *this, ike_sa_id_t *ike_sa_id, entry_t **entry, u_int *segment, linked_list_match_t match, void *param)
static status_t get_entry_by_id (private_ike_sa_manager_t *this, ike_sa_id_t *ike_sa_id, entry_t **entry, u_int *segment)
static status_t get_entry_by_sa (private_ike_sa_manager_t *this, ike_sa_id_t *ike_sa_id, ike_sa_t *ike_sa, entry_t **entry, u_int *segment)
static bool wait_for_entry (private_ike_sa_manager_t *this, entry_t *entry, u_int segment)
static void put_half_open (private_ike_sa_manager_t *this, entry_t *entry)
static void remove_half_open (private_ike_sa_manager_t *this, entry_t *entry)
static void put_connected_peers (private_ike_sa_manager_t *this, entry_t *entry)
static void remove_connected_peers (private_ike_sa_manager_t *this, entry_t *entry)
static u_int64_t get_spi (private_ike_sa_manager_t *this)
static bool get_init_hash (hasher_t *hasher, message_t *message, chunk_t *hash)
static status_t check_and_put_init_hash (private_ike_sa_manager_t *this, chunk_t init_hash, u_int64_t *our_spi)
static void remove_init_hash (private_ike_sa_manager_t *this, chunk_t init_hash)
METHOD (ike_sa_manager_t, checkout, ike_sa_t *, private_ike_sa_manager_t *this, ike_sa_id_t *ike_sa_id)
METHOD (ike_sa_manager_t, checkout_new, ike_sa_t *, private_ike_sa_manager_t *this, ike_version_t version, bool initiator)
static u_int32_t get_message_id_or_hash (message_t *message)
METHOD (ike_sa_manager_t, checkout_by_message, ike_sa_t *, private_ike_sa_manager_t *this, message_t *message)
METHOD (ike_sa_manager_t, checkout_by_config, ike_sa_t *, private_ike_sa_manager_t *this, peer_cfg_t *peer_cfg)
METHOD (ike_sa_manager_t, checkout_by_id, ike_sa_t *, private_ike_sa_manager_t *this, u_int32_t id)
METHOD (ike_sa_manager_t, checkout_by_name, ike_sa_t *, private_ike_sa_manager_t *this, char *name, bool child)
static bool enumerator_filter_wait (private_ike_sa_manager_t *this, entry_t **in, ike_sa_t **out, u_int *segment)
static bool enumerator_filter_skip (private_ike_sa_manager_t *this, entry_t **in, ike_sa_t **out, u_int *segment)
static void reset_sa (void *data)
METHOD (ike_sa_manager_t, create_enumerator, enumerator_t *, private_ike_sa_manager_t *this, bool wait)
METHOD (ike_sa_manager_t, checkin, void, private_ike_sa_manager_t *this, ike_sa_t *ike_sa)
METHOD (ike_sa_manager_t, checkin_and_destroy, void, private_ike_sa_manager_t *this, ike_sa_t *ike_sa)
static void id_enumerator_cleanup (linked_list_t *ids)
METHOD (ike_sa_manager_t, create_id_enumerator, enumerator_t *, private_ike_sa_manager_t *this, identification_t *me, identification_t *other, int family)
static void adopt_children_and_vips (ike_sa_t *old, ike_sa_t *new)
static status_t enforce_replace (private_ike_sa_manager_t *this, ike_sa_t *duplicate, ike_sa_t *new, identification_t *other, host_t *host)
METHOD (ike_sa_manager_t, check_uniqueness, bool, private_ike_sa_manager_t *this, ike_sa_t *ike_sa, bool force_replace)
METHOD (ike_sa_manager_t, has_contact, bool, private_ike_sa_manager_t *this, identification_t *me, identification_t *other, int family)
METHOD (ike_sa_manager_t, get_count, u_int, private_ike_sa_manager_t *this)
METHOD (ike_sa_manager_t, get_half_open_count, u_int, private_ike_sa_manager_t *this, host_t *ip, bool responder_only)
METHOD (ike_sa_manager_t, set_spi_cb, void, private_ike_sa_manager_t *this, spi_cb_t callback, void *data)
METHOD (ike_sa_manager_t, flush, void, private_ike_sa_manager_t *this)
METHOD (ike_sa_manager_t, destroy, void, private_ike_sa_manager_t *this)
static u_int get_nearest_powerof2 (u_int n)
ike_sa_manager_t * ike_sa_manager_create ()
Macro Definition Documentation
#define DEFAULT_HASHTABLE_SIZE 1
Definition at line 34 of file ike_sa_manager.c.
Referenced by ike_sa_manager_create().
#define DEFAULT_SEGMENT_COUNT 1
Definition at line 40 of file ike_sa_manager.c.
Referenced by ike_sa_manager_create().
#define MAX_HASHTABLE_SIZE (1 << 30)
Definition at line 37 of file ike_sa_manager.c.
Referenced by ike_sa_manager_create().
Typedef Documentation
typedef struct connected_peers_t connected_peers_t
Definition at line 223 of file ike_sa_manager.c.
typedef struct entry_t entry_t
Definition at line 42 of file ike_sa_manager.c.
typedef struct half_open_t half_open_t
Definition at line 198 of file ike_sa_manager.c.
typedef struct init_hash_t init_hash_t
Definition at line 259 of file ike_sa_manager.c.
typedef struct private_enumerator_t private_enumerator_t
Definition at line 468 of file ike_sa_manager.c.
typedef struct private_ike_sa_manager_t private_ike_sa_manager_t
Definition at line 310 of file ike_sa_manager.c.
typedef struct segment_t segment_t
Definition at line 269 of file ike_sa_manager.c.
typedef struct shareable_segment_t shareable_segment_t
Definition at line 282 of file ike_sa_manager.c.
typedef struct table_item_t table_item_t
Definition at line 296 of file ike_sa_manager.c.
Function Documentation
static void adopt_children_and_vips (ike_sa_t * old, ike_sa_t * new) static
Move all CHILD_SAs and virtual IPs from old to new
Definition at line 1810 of file ike_sa_manager.c.
References bus_t::assign_vips, daemon_t::bus, charon, bus_t::children_migrate, ike_sa_t::clear_virtual_ips, ike_sa_t::create_child_sa_enumerator, ike_sa_t::create_virtual_ip_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, ike_sa_t::remove_child_sa, bus_t::set_sa, TRUE, and vip.
Referenced by enforce_replace().
 {
     enumerator_t *enumerator;
     child_sa_t *child_sa;
     host_t *vip;
     int chcount = 0, vipcount = 0;
     charon->bus->children_migrate(charon->bus, new->get_id(new),
                                   new->get_unique_id(new));
     enumerator = old->create_child_sa_enumerator(old);
     while (enumerator->enumerate(enumerator, &child_sa))
     {
         old->remove_child_sa(old, enumerator);
         new->add_child_sa(new, child_sa);
         chcount++;
     }
     enumerator->destroy(enumerator);
     enumerator = old->create_virtual_ip_enumerator(old, FALSE);
     while (enumerator->enumerate(enumerator, &vip))
     {
         new->add_virtual_ip(new, FALSE, vip);
         vipcount++;
     }
     enumerator->destroy(enumerator);
     /* this does not release the addresses, which is good, but it does trigger
      * an assign_vips(FALSE) event... */
     old->clear_virtual_ips(old, FALSE);
     /* ...trigger the analogous event on the new SA */
     charon->bus->set_sa(charon->bus, new);
     charon->bus->assign_vips(charon->bus, new, TRUE);
     charon->bus->children_migrate(charon->bus, NULL, 0);
     charon->bus->set_sa(charon->bus, old);
     if (chcount || vipcount)
     {
         DBG1(DBG_IKE, "detected reauth of existing IKE_SA, adopting %d "
              "children and %d virtual IPs", chcount, vipcount);
     }
 }
static status_t check_and_put_init_hash (private_ike_sa_manager_t * this, chunk_t init_hash, u_int64_t * our_spi) static
Check if we already have created an IKE_SA based on the initial IKE message with the given hash. If not the hash is stored, the hash data is not(!) cloned.
Also, the local SPI is returned. In case of a retransmit this is already stored together with the hash, otherwise it is newly allocated and should be used to create the IKE_SA.
Returns
ALREADY_DONE if the message with the given hash has been seen before NOT_FOUND if the message hash was not found FAILED if the SPI allocation failed
Definition at line 1050 of file ike_sa_manager.c.
References ALREADY_DONE, chunk_equals(), chunk_hash(), FAILED, get_spi(), init_hash_t::hash, hash, INIT, init(), chunk_t::len, mutex_t::lock, mutex, next, table_item_t::next, NOT_FOUND, init_hash_t::our_spi, chunk_t::ptr, segment, mutex_t::unlock, value, and table_item_t::value.
Referenced by METHOD().
 {
     table_item_t *item;
     u_int row, segment;
     mutex_t *mutex;
     init_hash_t *init;
     u_int64_t spi;
     row = chunk_hash(init_hash) & this->table_mask;
     segment = row & this->segment_mask;
     mutex = this->init_hashes_segments[segment].mutex;
     mutex->lock(mutex);
     item = this->init_hashes_table[row];
     while (item)
     {
         init_hash_t *current = item->value;
         if (chunk_equals(init_hash, current->hash))
         {
             *our_spi = current->our_spi;
             mutex->unlock(mutex);
             return ALREADY_DONE;
         }
         item = item->next;
     }
     spi = get_spi(this);
     if (!spi)
     {
         return FAILED;
     }
     INIT(init,
         .hash = {
             .len = init_hash.len,
             .ptr = init_hash.ptr,
         },
         .our_spi = spi,
     );
     INIT(item,
         .value = init,
         .next = this->init_hashes_table[row],
     );
     this->init_hashes_table[row] = item;
     *our_spi = init->our_spi;
     mutex->unlock(mutex);
     return NOT_FOUND;
 }
static void connected_peers_destroy (connected_peers_t * this) static
Definition at line 239 of file ike_sa_manager.c.
References free().
Referenced by remove_connected_peers().
 {
     this->my_id->destroy(this->my_id);
     this->other_id->destroy(this->other_id);
     this->sas->destroy(this->sas);
     free(this);
 }
static bool connected_peers_match (connected_peers_t * connected_peers, identification_t * my_id, identification_t * other_id, int family) inline static
Function that matches connected_peers_t objects by the given ids.
Definition at line 250 of file ike_sa_manager.c.
References identification_t::equals, connected_peers_t::family, connected_peers_t::my_id, and connected_peers_t::other_id.
Referenced by METHOD(), put_connected_peers(), and remove_connected_peers().
 {
     return my_id->equals(my_id, connected_peers->my_id) &&
            other_id->equals(other_id, connected_peers->other_id) &&
            (!family || family == connected_peers->family);
 }
static enumerator_t* create_table_enumerator (private_ike_sa_manager_t * this) static
Creates an enumerator to enumerate the entries in the hash table.
Definition at line 565 of file ike_sa_manager.c.
References destroy(), private_enumerator_t::enumerator, and INIT.
Referenced by METHOD().
 {
     private_enumerator_t *enumerator;
     INIT(enumerator,
         .enumerator = {
             .enumerate = (void*)_enumerate,
             .destroy = _enumerator_destroy,
         },
         .manager = this,
     );
     return &enumerator->enumerator;
 }
static status_t enforce_replace (private_ike_sa_manager_t * this, ike_sa_t * duplicate, ike_sa_t * new, identification_t * other, host_t * host) static
Delete an existing IKE_SA due to a unique replace policy
Definition at line 1854 of file ike_sa_manager.c.
References adopt_children_and_vips(), bus_t::alert, ALERT_UNIQUE_REPLACE, daemon_t::bus, charon, COND_INIT_CONTACT_SEEN, DBG1, DBG_IKE, ike_sa_t::delete, delete_ike_sa_job_create(), host_t::equals, ike_sa_t::get_id, ike_sa_t::get_other_host, IKEV1, lib, scheduler_t::schedule_job, library_t::scheduler, SUCCESS, and TRUE.
Referenced by METHOD().
 {
     charon->bus->alert(charon->bus, ALERT_UNIQUE_REPLACE);
     if (host->equals(host, duplicate->get_other_host(duplicate)))
     {
         /* looks like a reauthentication attempt */
         if (!new->has_condition(new, COND_INIT_CONTACT_SEEN) &&
             new->get_version(new) == IKEV1)
         {
             /* IKEv1 implicitly takes over children, IKEv2 recreates them
              * explicitly. */
             adopt_children_and_vips(duplicate, new);
         }
         /* For IKEv1 we have to delay the delete for the old IKE_SA. Some
          * peers need to complete the new SA first, otherwise the quick modes
          * might get lost. For IKEv2 we do the same, as we want overlapping
          * CHILD_SAs to keep connectivity up. */
         lib->scheduler->schedule_job(lib->scheduler, (job_t*)
             delete_ike_sa_job_create(duplicate->get_id(duplicate), TRUE), 10);
         return SUCCESS;
     }
     DBG1(DBG_IKE, "deleting duplicate IKE_SA for peer '%Y' due to "
          "uniqueness policy", other);
     return duplicate->delete(duplicate);
 }
static entry_t* entry_create () static
Creates a new entry for the ike_sa_t list.
Definition at line 137 of file ike_sa_manager.c.
References condvar, condvar_create(), CONDVAR_TYPE_DEFAULT, and INIT.
Referenced by METHOD().
 {
     entry_t *this;
     INIT(this,
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .processing = -1,
     );
     return this;
 }
static status_t entry_destroy (entry_t * this) static
Implementation of entry_t.destroy.
Definition at line 120 of file ike_sa_manager.c.
References chunk_free(), condvar, condvar_t::destroy, DESTROY_IF, free(), and SUCCESS.
Referenced by METHOD().
 {
     /* also destroy IKE SA */
     this->ike_sa->destroy(this->ike_sa);
     this->ike_sa_id->destroy(this->ike_sa_id);
     chunk_free(&this->init_hash);
     DESTROY_IF(this->other);
     DESTROY_IF(this->my_id);
     DESTROY_IF(this->other_id);
     this->condvar->destroy(this->condvar);
     free(this);
     return SUCCESS;
 }
static bool entry_match_by_id (entry_t * entry, ike_sa_id_t * id) static
Function that matches entry_t objects by ike_sa_id_t.
Definition at line 152 of file ike_sa_manager.c.
References ike_sa_id_t::equals, FALSE, ike_sa_id_t::get_ike_version, ike_sa_id_t::get_initiator_spi, ike_sa_id_t::get_responder_spi, entry_t::ike_sa_id, IKEV1_MAJOR_VERSION, ike_sa_id_t::is_initiator, and TRUE.
Referenced by get_entry_by_id().
 {
     if (id->equals(id, entry->ike_sa_id))
     {
         return TRUE;
     }
     if ((id->get_responder_spi(id) == 0 ||
          entry->ike_sa_id->get_responder_spi(entry->ike_sa_id) == 0) &&
         (id->get_ike_version(id) == IKEV1_MAJOR_VERSION ||
          id->is_initiator(id) == entry->ike_sa_id->is_initiator(entry->ike_sa_id)) &&
         id->get_initiator_spi(id) == entry->ike_sa_id->get_initiator_spi(entry->ike_sa_id))
     {
         /* this is TRUE for IKE_SAs that we initiated but have not yet received a response */
         return TRUE;
     }
     return FALSE;
 }
static bool entry_match_by_sa (entry_t * entry, ike_sa_t * ike_sa) static
Function that matches entry_t objects by ike_sa_t pointers.
Definition at line 173 of file ike_sa_manager.c.
References entry_t::ike_sa.
Referenced by get_entry_by_sa().
 {
     return entry->ike_sa == ike_sa;
 }
static bool enumerator_filter_skip (private_ike_sa_manager_t * this, entry_t ** in, ike_sa_t ** out, u_int * segment) static
enumerator filter function, skipping variant
Definition at line 1542 of file ike_sa_manager.c.
References daemon_t::bus, charon, FALSE, bus_t::set_sa, and TRUE.
Referenced by METHOD().
 {
     if (!(*in)->driveout_new_threads &&
         !(*in)->driveout_waiting_threads &&
         !(*in)->checked_out)
     {
         *out = (*in)->ike_sa;
         charon->bus->set_sa(charon->bus, *out);
         return TRUE;
     }
     return FALSE;
 }
static bool enumerator_filter_wait (private_ike_sa_manager_t * this, entry_t ** in, ike_sa_t ** out, u_int * segment) static
enumerator filter function, waiting variant
Definition at line 1527 of file ike_sa_manager.c.
References daemon_t::bus, charon, FALSE, bus_t::set_sa, TRUE, and wait_for_entry().
Referenced by METHOD().
 {
     if (wait_for_entry(this, *in, *segment))
     {
         *out = (*in)->ike_sa;
         charon->bus->set_sa(charon->bus, *out);
         return TRUE;
     }
     return FALSE;
 }
static status_t get_entry_by_id (private_ike_sa_manager_t * this, ike_sa_id_t * ike_sa_id, entry_t ** entry, u_int * segment) static
Find an entry by ike_sa_id_t. Note: On SUCCESS, the caller has to unlock the segment.
Definition at line 700 of file ike_sa_manager.c.
References entry_match_by_id(), and get_entry_by_match_function().
Referenced by METHOD().
 {
     return get_entry_by_match_function(this, ike_sa_id, entry, segment,
                 (linked_list_match_t)entry_match_by_id, ike_sa_id);
 }
static status_t get_entry_by_match_function (private_ike_sa_manager_t * this, ike_sa_id_t * ike_sa_id, entry_t ** entry, u_int * segment, linked_list_match_t match, void * param) static
Find an entry using the provided match function to compare the entries for equality.
Definition at line 669 of file ike_sa_manager.c.
References ike_sa_id_hash(), lock_single_segment(), match(), table_item_t::next, NOT_FOUND, SUCCESS, unlock_single_segment(), and table_item_t::value.
Referenced by get_entry_by_id(), and get_entry_by_sa().
 {
     table_item_t *item;
     u_int row, seg;
     row = ike_sa_id_hash(ike_sa_id) & this->table_mask;
     seg = row & this->segment_mask;
     lock_single_segment(this, seg);
     item = this->ike_sa_table[row];
     while (item)
     {
         if (match(item->value, param))
         {
             *entry = item->value;
             *segment = seg;
             /* the locked segment has to be unlocked by the caller */
             return SUCCESS;
         }
         item = item->next;
     }
     unlock_single_segment(this, seg);
     return NOT_FOUND;
 }
static status_t get_entry_by_sa (private_ike_sa_manager_t * this, ike_sa_id_t * ike_sa_id, ike_sa_t * ike_sa, entry_t ** entry, u_int * segment) static
Find an entry by IKE_SA pointer. Note: On SUCCESS, the caller has to unlock the segment.
Definition at line 711 of file ike_sa_manager.c.
References entry_match_by_sa(), and get_entry_by_match_function().
Referenced by METHOD().
 {
     return get_entry_by_match_function(this, ike_sa_id, entry, segment,
                 (linked_list_match_t)entry_match_by_sa, ike_sa);
 }
static bool get_init_hash (hasher_t * hasher, message_t * message, chunk_t * hash) static
Calculate the hash of the initial IKE message. Memory for the hash is allocated on success.
Returns
TRUE on success
Definition at line 1002 of file ike_sa_manager.c.
References hasher_t::allocate_hash, chunk_from_thing, FALSE, host_t::get_address, message_t::get_exchange_type, message_t::get_first_payload_type, message_t::get_initiator_spi, message_t::get_packet_data, host_t::get_port, message_t::get_source, hash, ID_PROT, PLV1_FRAGMENT, port, and src.
Referenced by METHOD().
 {
     host_t *src;
     if (message->get_first_payload_type(message) == PLV1_FRAGMENT)
     {   /* only hash the source IP, port and SPI for fragmented init messages */
         u_int16_t port;
         u_int64_t spi;
         src = message->get_source(message);
         if (!hasher->allocate_hash(hasher, src->get_address(src), NULL))
         {
             return FALSE;
         }
         port = src->get_port(src);
         if (!hasher->allocate_hash(hasher, chunk_from_thing(port), NULL))
         {
             return FALSE;
         }
         spi = message->get_initiator_spi(message);
         return hasher->allocate_hash(hasher, chunk_from_thing(spi), hash);
     }
     if (message->get_exchange_type(message) == ID_PROT)
     {   /* include the source for Main Mode as the hash will be the same if
          * SPIs are reused by two initiators that use the same proposal */
         src = message->get_source(message);
         if (!hasher->allocate_hash(hasher, src->get_address(src), NULL))
         {
             return FALSE;
         }
     }
     return hasher->allocate_hash(hasher, message->get_packet_data(message), hash);
 }
static u_int32_t get_message_id_or_hash (message_t * message) static
Get the message ID or message hash to detect early retransmissions
Definition at line 1201 of file ike_sa_manager.c.
References chunk_hash(), message_t::get_exchange_type, message_t::get_major_version, message_t::get_message_id, message_t::get_packet_data, IKEV1_MAJOR_VERSION, and QUICK_MODE.
Referenced by METHOD().
 {
     if (message->get_major_version(message) == IKEV1_MAJOR_VERSION)
     {
         /* Use a hash for IKEv1 Phase 1, where we don't have a MID, and Quick
          * Mode, where all three messages use the same message ID */
         if (message->get_message_id(message) == 0 ||
             message->get_exchange_type(message) == QUICK_MODE)
         {
             return chunk_hash(message->get_packet_data(message));
         }
     }
     return message->get_message_id(message);
 }
static u_int get_nearest_powerof2 (u_int n) static
This function returns the next-highest power of two for the given number. The algorithm works by setting all bits on the right-hand side of the most significant 1 to 1 and then increments the whole number so it rolls over to the nearest power of two. Note: returns 0 for n == 0
Definition at line 2186 of file ike_sa_manager.c.
References n.
Referenced by ike_sa_manager_create().
 {
     u_int i;
     --n;
     for (i = 1; i < sizeof(u_int) * 8; i <<= 1)
     {
         n |= n >> i;
     }
     return ++n;
 }
static u_int64_t get_spi (private_ike_sa_manager_t * this) static
Get a random SPI for new IKE_SAs
Definition at line 978 of file ike_sa_manager.c.
References rng.
Referenced by check_and_put_init_hash(), and METHOD().
 {
     u_int64_t spi;
     this->spi_lock->read_lock(this->spi_lock);
     if (this->spi_cb.cb)
     {
         spi = this->spi_cb.cb(this->spi_cb.data);
     }
     else if (!this->rng ||
              !this->rng->get_bytes(this->rng, sizeof(spi), (u_int8_t*)&spi))
     {
         spi = 0;
     }
     this->spi_lock->unlock(this->spi_lock);
     return spi;
 }
static void half_open_destroy (half_open_t * this) static
Destroys a half_open_t object.
Definition at line 217 of file ike_sa_manager.c.
References chunk_free(), and free().
Referenced by remove_half_open().
 {
     chunk_free(&this->other);
     free(this);
 }
static void id_enumerator_cleanup (linked_list_t * ids) static
Cleanup function for create_id_enumerator
Definition at line 1764 of file ike_sa_manager.c.
References destroy(), and linked_list_t::destroy_offset.
Referenced by METHOD().
 {
     ids->destroy_offset(ids, offsetof(ike_sa_id_t, destroy));
 }
static u_int ike_sa_id_hash (ike_sa_id_t * ike_sa_id) static
Hash function for ike_sa_id_t objects.
Definition at line 181 of file ike_sa_manager.c.
References ike_sa_id_t::get_ike_version, ike_sa_id_t::get_initiator_spi, ike_sa_id_t::get_responder_spi, IKEV1_MAJOR_VERSION, and ike_sa_id_t::is_initiator.
Referenced by get_entry_by_match_function(), put_entry(), and remove_entry().
 {
     /* IKEv2 does not mandate random SPIs (RFC 5996, 2.6), they just have to be
      * locally unique, so we use our randomly allocated SPI whether we are
      * initiator or responder to ensure a good distribution.  The latter is not
      * possible for IKEv1 as we don't know whether we are original initiator or
      * not (based on the IKE header).  But as RFC 2408, section 2.5.3 proposes
      * SPIs (Cookies) to be allocated near random (we allocate them randomly
      * anyway) it seems safe to always use the initiator SPI. */
     if (ike_sa_id->get_ike_version(ike_sa_id) == IKEV1_MAJOR_VERSION ||
         ike_sa_id->is_initiator(ike_sa_id))
     {
         return ike_sa_id->get_initiator_spi(ike_sa_id);
     }
     return ike_sa_id->get_responder_spi(ike_sa_id);
 }
static void lock_all_segments (private_ike_sa_manager_t * this) static
Lock all segments
Definition at line 445 of file ike_sa_manager.c.
References mutex.
Referenced by METHOD().
 {
     u_int i;
     for (i = 0; i < this->segment_count; i++)
     {
         this->segments[i].mutex->lock(this->segments[i].mutex);
     }
 }
static void lock_single_segment (private_ike_sa_manager_t * this, u_int index) inline static
Acquire a lock to access the segment of the table row with the given index. It also works with the segment index directly.
Definition at line 424 of file ike_sa_manager.c.
References mutex_t::lock, and lock.
Referenced by get_entry_by_match_function(), METHOD(), and put_entry().
 {
     mutex_t *lock = this->segments[index & this->segment_mask].mutex;
     lock->lock(lock);
 }
METHOD (enumerator_t , enumerate , bool , private_enumerator_t * this, entry_t ** entry, u_int * segment)
Definition at line 511 of file ike_sa_manager.c.
References entry_t::condvar, FALSE, lock_single_segment(), segment, condvar_t::signal, TRUE, unlock_single_segment(), and entry_t::value.
 {
     if (this->entry)
     {
         this->entry->condvar->signal(this->entry->condvar);
         this->entry = NULL;
     }
     while (this->segment < this->manager->segment_count)
     {
         while (this->row < this->manager->table_size)
         {
             this->prev = this->current;
             if (this->current)
             {
                 this->current = this->current->next;
             }
             else
             {
                 lock_single_segment(this->manager, this->segment);
                 this->current = this->manager->ike_sa_table[this->row];
             }
             if (this->current)
             {
                 *entry = this->entry = this->current->value;
                 *segment = this->segment;
                 return TRUE;
             }
             unlock_single_segment(this->manager, this->segment);
             this->row += this->manager->segment_count;
         }
         this->segment++;
         this->row = this->segment;
     }
     return FALSE;
 }
METHOD (enumerator_t , enumerator_destroy , void , private_enumerator_t * this)
Definition at line 548 of file ike_sa_manager.c.
References free(), segment, and unlock_single_segment().
 {
     if (this->entry)
     {
         this->entry->condvar->signal(this->entry->condvar);
     }
     if (this->current)
     {
         unlock_single_segment(this->manager, this->segment);
     }
     free(this);
 }
METHOD (ike_sa_manager_t , checkout , ike_sa_t * , private_ike_sa_manager_t * this, ike_sa_id_t * ike_sa_id)
Definition at line 1138 of file ike_sa_manager.c.
References daemon_t::bus, charon, entry_t::checked_out, DBG2, DBG_MGR, get_entry_by_id(), ike_sa_t::get_name, ike_sa_t::get_unique_id, entry_t::ike_sa, segment, bus_t::set_sa, SUCCESS, TRUE, unlock_single_segment(), and wait_for_entry().
 {
     ike_sa_t *ike_sa = NULL;
     entry_t *entry;
     u_int segment;
     DBG2(DBG_MGR, "checkout IKE_SA");
     if (get_entry_by_id(this, ike_sa_id, &entry, &segment) == SUCCESS)
     {
         if (wait_for_entry(this, entry, segment))
         {
             entry->checked_out = TRUE;
             ike_sa = entry->ike_sa;
             DBG2(DBG_MGR, "IKE_SA %s[%u] successfully checked out",
                     ike_sa->get_name(ike_sa), ike_sa->get_unique_id(ike_sa));
         }
         unlock_single_segment(this, segment);
     }
     charon->bus->set_sa(charon->bus, ike_sa);
     return ike_sa;
 }
METHOD (ike_sa_manager_t , checkout_new , ike_sa_t * , private_ike_sa_manager_t * this, ike_version_t version, bool initiator)
Definition at line 1162 of file ike_sa_manager.c.
References DBG1, DBG2, DBG_MGR, ike_sa_id_t::destroy, FALSE, ike_sa_t::get_name, get_spi(), ike_sa_t::get_unique_id, ike_sa_create(), ike_sa_id_create(), ike_version, IKEV1, IKEV1_MAJOR_VERSION, IKEV2_MAJOR_VERSION, and TRUE.
 {
     ike_sa_id_t *ike_sa_id;
     ike_sa_t *ike_sa;
     u_int8_t ike_version;
     u_int64_t spi;
     ike_version = version == IKEV1 ? IKEV1_MAJOR_VERSION : IKEV2_MAJOR_VERSION;
     spi = get_spi(this);
     if (!spi)
     {
         DBG1(DBG_MGR, "failed to allocate SPI for new IKE_SA");
         return NULL;
     }
     if (initiator)
     {
         ike_sa_id = ike_sa_id_create(ike_version, spi, 0, TRUE);
     }
     else
     {
         ike_sa_id = ike_sa_id_create(ike_version, 0, spi, FALSE);
     }
     ike_sa = ike_sa_create(ike_sa_id, initiator, version);
     ike_sa_id->destroy(ike_sa_id);
     if (ike_sa)
     {
         DBG2(DBG_MGR, "created IKE_SA %s[%u]", ike_sa->get_name(ike_sa),
              ike_sa->get_unique_id(ike_sa));
     }
     return ike_sa;
 }
METHOD (ike_sa_manager_t , checkout_by_message , ike_sa_t * , private_ike_sa_manager_t * this, message_t * message)
Definition at line 1216 of file ike_sa_manager.c.
References AGGRESSIVE, bus_t::alert, ALERT_INVALID_IKE_SPI, ALREADY_DONE, daemon_t::bus, charon, check_and_put_init_hash(), entry_t::checked_out, chunk_free(), ike_sa_id_t::clone, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG2, DBG_MGR, hasher_t::destroy, DESTROY_IF, entry_create(), exchange_type_names, FAILED, FALSE, get_entry_by_id(), message_t::get_exchange_type, message_t::get_first_payload_type, ike_sa_t::get_id, message_t::get_ike_sa_id, get_init_hash(), message_t::get_major_version, message_t::get_message_id, get_message_id_or_hash(), ike_sa_t::get_name, message_t::get_request, ike_sa_id_t::get_responder_spi, ike_sa_t::get_unique_id, hash, HASH_SHA1, hasher, id, ID_PROT, entry_t::ike_sa, ike_sa_create(), entry_t::ike_sa_id, IKE_SA_INIT, ike_version, IKEV1, IKEV2, IKEV2_MAJOR_VERSION, entry_t::init_hash, ike_sa_id_t::is_initiator, lib, NOT_FOUND, PLV1_FRAGMENT, PLV2_FRAGMENT, entry_t::processing, put_entry(), remove_init_hash(), segment, ike_sa_id_t::set_responder_spi, bus_t::set_sa, SUCCESS, ike_sa_id_t::switch_initiator, TRUE, unlock_single_segment(), and wait_for_entry().
 {
     u_int segment;
     entry_t *entry;
     ike_sa_t *ike_sa = NULL;
     ike_sa_id_t *id;
     ike_version_t ike_version;
     bool is_init = FALSE;
     id = message->get_ike_sa_id(message);
     /* clone the IKE_SA ID so we can modify the initiator flag */
     id = id->clone(id);
     id->switch_initiator(id);
     DBG2(DBG_MGR, "checkout IKE_SA by message");
     if (id->get_responder_spi(id) == 0 &&
         message->get_message_id(message) == 0)
     {
         if (message->get_major_version(message) == IKEV2_MAJOR_VERSION)
         {
             if (message->get_exchange_type(message) == IKE_SA_INIT &&
                 message->get_request(message))
             {
                 ike_version = IKEV2;
                 is_init = TRUE;
             }
         }
         else
         {
             if (message->get_exchange_type(message) == ID_PROT ||
                 message->get_exchange_type(message) == AGGRESSIVE)
             {
                 ike_version = IKEV1;
                 is_init = TRUE;
                 if (id->is_initiator(id))
                 {   /* not set in IKEv1, switch back before applying to new SA */
                     id->switch_initiator(id);
                 }
             }
         }
     }
     if (is_init)
     {
         hasher_t *hasher;
         u_int64_t our_spi;
         chunk_t hash;
         hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
         if (!hasher || !get_init_hash(hasher, message, &hash))
         {
             DBG1(DBG_MGR, "ignoring message, failed to hash message");
             DESTROY_IF(hasher);
             id->destroy(id);
             return NULL;
         }
         hasher->destroy(hasher);
         /* ensure this is not a retransmit of an already handled init message */
         switch (check_and_put_init_hash(this, hash, &our_spi))
         {
             case NOT_FOUND:
             {   /* we've not seen this packet yet, create a new IKE_SA */
                 if (!this->ikesa_limit ||
                     this->public.get_count(&this->public) < this->ikesa_limit)
                 {
                     id->set_responder_spi(id, our_spi);
                     ike_sa = ike_sa_create(id, FALSE, ike_version);
                     if (ike_sa)
                     {
                         entry = entry_create();
                         entry->ike_sa = ike_sa;
                         entry->ike_sa_id = id;
                         segment = put_entry(this, entry);
                         entry->checked_out = TRUE;
                         unlock_single_segment(this, segment);
                         entry->processing = get_message_id_or_hash(message);
                         entry->init_hash = hash;
                         DBG2(DBG_MGR, "created IKE_SA %s[%u]",
                              ike_sa->get_name(ike_sa),
                              ike_sa->get_unique_id(ike_sa));
                         charon->bus->set_sa(charon->bus, ike_sa);
                         return ike_sa;
                     }
                     else
                     {
                         DBG1(DBG_MGR, "creating IKE_SA failed, ignoring message");
                     }
                 }
                 else
                 {
                     DBG1(DBG_MGR, "ignoring %N, hitting IKE_SA limit (%u)",
                          exchange_type_names, message->get_exchange_type(message),
                          this->ikesa_limit);
                 }
                 remove_init_hash(this, hash);
                 chunk_free(&hash);
                 id->destroy(id);
                 return NULL;
             }
             case FAILED:
             {   /* we failed to allocate an SPI */
                 chunk_free(&hash);
                 id->destroy(id);
                 DBG1(DBG_MGR, "ignoring message, failed to allocate SPI");
                 return NULL;
             }
             case ALREADY_DONE:
             default:
                 break;
         }
         /* it looks like we already handled this init message to some degree */
         id->set_responder_spi(id, our_spi);
         chunk_free(&hash);
     }
     if (get_entry_by_id(this, id, &entry, &segment) == SUCCESS)
     {
         /* only check out if we are not already processing it. */
         if (entry->processing == get_message_id_or_hash(message))
         {
             DBG1(DBG_MGR, "ignoring request with ID %u, already processing",
                  entry->processing);
         }
         else if (wait_for_entry(this, entry, segment))
         {
             ike_sa_id_t *ike_id;
             ike_id = entry->ike_sa->get_id(entry->ike_sa);
             entry->checked_out = TRUE;
             if (message->get_first_payload_type(message) != PLV1_FRAGMENT &&
                 message->get_first_payload_type(message) != PLV2_FRAGMENT)
             {   /* TODO-FRAG: this fails if there are unencrypted payloads */
                 entry->processing = get_message_id_or_hash(message);
             }
             if (ike_id->get_responder_spi(ike_id) == 0)
             {
                 ike_id->set_responder_spi(ike_id, id->get_responder_spi(id));
             }
             ike_sa = entry->ike_sa;
             DBG2(DBG_MGR, "IKE_SA %s[%u] successfully checked out",
                     ike_sa->get_name(ike_sa), ike_sa->get_unique_id(ike_sa));
         }
         unlock_single_segment(this, segment);
     }
     else
     {
         charon->bus->alert(charon->bus, ALERT_INVALID_IKE_SPI, message);
     }
     id->destroy(id);
     charon->bus->set_sa(charon->bus, ike_sa);
     return ike_sa;
 }
METHOD (ike_sa_manager_t , checkout_by_config , ike_sa_t * , private_ike_sa_manager_t * this, peer_cfg_t * peer_cfg)
Definition at line 1376 of file ike_sa_manager.c.
References daemon_t::bus, charon, entry_t::checked_out, entry_t::condvar, create_table_enumerator(), DBG2, DBG_MGR, enumerator_t::destroy, enumerator_t::enumerate, ike_cfg_t::equals, peer_cfg_t::equals, peer_cfg_t::get_ike_cfg, peer_cfg_t::get_ike_version, peer_cfg_t::get_name, ike_sa_t::get_peer_cfg, ike_sa_t::get_state, ike_sa_t::get_unique_id, IKE_DELETING, entry_t::ike_sa, segment, bus_t::set_sa, condvar_t::signal, TRUE, and wait_for_entry().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     ike_sa_t *ike_sa = NULL;
     peer_cfg_t *current_peer;
     ike_cfg_t *current_ike;
     u_int segment;
     DBG2(DBG_MGR, "checkout IKE_SA by config");
     if (!this->reuse_ikesa)
     {   /* IKE_SA reuse disable by config */
         ike_sa = checkout_new(this, peer_cfg->get_ike_version(peer_cfg), TRUE);
         charon->bus->set_sa(charon->bus, ike_sa);
         return ike_sa;
     }
     enumerator = create_table_enumerator(this);
     while (enumerator->enumerate(enumerator, &entry, &segment))
     {
         if (!wait_for_entry(this, entry, segment))
         {
             continue;
         }
         if (entry->ike_sa->get_state(entry->ike_sa) == IKE_DELETING)
         {   /* skip IKE_SAs which are not usable, wake other waiting threads */
             entry->condvar->signal(entry->condvar);
             continue;
         }
         current_peer = entry->ike_sa->get_peer_cfg(entry->ike_sa);
         if (current_peer && current_peer->equals(current_peer, peer_cfg))
         {
             current_ike = current_peer->get_ike_cfg(current_peer);
             if (current_ike->equals(current_ike, peer_cfg->get_ike_cfg(peer_cfg)))
             {
                 entry->checked_out = TRUE;
                 ike_sa = entry->ike_sa;
                 DBG2(DBG_MGR, "found existing IKE_SA %u with a '%s' config",
                         ike_sa->get_unique_id(ike_sa),
                         current_peer->get_name(current_peer));
                 break;
             }
         }
         /* other threads might be waiting for this entry */
         entry->condvar->signal(entry->condvar);
     }
     enumerator->destroy(enumerator);
     if (!ike_sa)
     {   /* no IKE_SA using such a config, hand out a new */
         ike_sa = checkout_new(this, peer_cfg->get_ike_version(peer_cfg), TRUE);
     }
     charon->bus->set_sa(charon->bus, ike_sa);
     return ike_sa;
 }
METHOD (ike_sa_manager_t , checkout_by_id , ike_sa_t * , private_ike_sa_manager_t * this, u_int32_t id)
Definition at line 1435 of file ike_sa_manager.c.
References daemon_t::bus, charon, entry_t::checked_out, entry_t::condvar, create_table_enumerator(), DBG2, DBG_MGR, enumerator_t::destroy, enumerator_t::enumerate, ike_sa_t::get_name, ike_sa_t::get_unique_id, id, entry_t::ike_sa, segment, bus_t::set_sa, condvar_t::signal, TRUE, and wait_for_entry().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     ike_sa_t *ike_sa = NULL;
     u_int segment;
     DBG2(DBG_MGR, "checkout IKE_SA by ID %u", id);
     enumerator = create_table_enumerator(this);
     while (enumerator->enumerate(enumerator, &entry, &segment))
     {
         if (wait_for_entry(this, entry, segment))
         {
             if (entry->ike_sa->get_unique_id(entry->ike_sa) == id)
             {
                 ike_sa = entry->ike_sa;
                 entry->checked_out = TRUE;
                 break;
             }
             /* other threads might be waiting for this entry */
             entry->condvar->signal(entry->condvar);
         }
     }
     enumerator->destroy(enumerator);
     if (ike_sa)
     {
         DBG2(DBG_MGR, "IKE_SA %s[%u] successfully checked out",
              ike_sa->get_name(ike_sa), ike_sa->get_unique_id(ike_sa));
     }
     charon->bus->set_sa(charon->bus, ike_sa);
     return ike_sa;
 }
METHOD (ike_sa_manager_t , checkout_by_name , ike_sa_t * , private_ike_sa_manager_t * this, char * name, bool child)
Definition at line 1471 of file ike_sa_manager.c.
References daemon_t::bus, charon, entry_t::checked_out, entry_t::condvar, ike_sa_t::create_child_sa_enumerator, create_table_enumerator(), DBG2, DBG_MGR, enumerator_t::destroy, enumerator_t::enumerate, child_sa_t::get_name, ike_sa_t::get_name, ike_sa_t::get_unique_id, entry_t::ike_sa, name, segment, bus_t::set_sa, condvar_t::signal, streq(), TRUE, and wait_for_entry().
 {
     enumerator_t *enumerator, *children;
     entry_t *entry;
     ike_sa_t *ike_sa = NULL;
     child_sa_t *child_sa;
     u_int segment;
     enumerator = create_table_enumerator(this);
     while (enumerator->enumerate(enumerator, &entry, &segment))
     {
         if (wait_for_entry(this, entry, segment))
         {
             /* look for a child with such a policy name ... */
             if (child)
             {
                 children = entry->ike_sa->create_child_sa_enumerator(entry->ike_sa);
                 while (children->enumerate(children, (void**)&child_sa))
                 {
                     if (streq(child_sa->get_name(child_sa), name))
                     {
                         ike_sa = entry->ike_sa;
                         break;
                     }
                 }
                 children->destroy(children);
             }
             else /* ... or for a IKE_SA with such a connection name */
             {
                 if (streq(entry->ike_sa->get_name(entry->ike_sa), name))
                 {
                     ike_sa = entry->ike_sa;
                 }
             }
             /* got one, return */
             if (ike_sa)
             {
                 entry->checked_out = TRUE;
                 DBG2(DBG_MGR, "IKE_SA %s[%u] successfully checked out",
                         ike_sa->get_name(ike_sa), ike_sa->get_unique_id(ike_sa));
                 break;
             }
             /* other threads might be waiting for this entry */
             entry->condvar->signal(entry->condvar);
         }
     }
     enumerator->destroy(enumerator);
     charon->bus->set_sa(charon->bus, ike_sa);
     return ike_sa;
 }
METHOD (ike_sa_manager_t , create_enumerator , enumerator_t * , private_ike_sa_manager_t * this, bool wait)
Definition at line 1564 of file ike_sa_manager.c.
References create_table_enumerator(), enumerator_create_filter(), enumerator_filter_skip(), enumerator_filter_wait(), and reset_sa().
 {
     return enumerator_create_filter(create_table_enumerator(this),
             wait ? (void*)enumerator_filter_wait : (void*)enumerator_filter_skip,
             this, reset_sa);
 }
METHOD (ike_sa_manager_t , checkin , void , private_ike_sa_manager_t * this, ike_sa_t * ike_sa)
Definition at line 1572 of file ike_sa_manager.c.
References daemon_t::bus, charon, entry_t::checked_out, host_t::clone, ike_sa_id_t::clone, identification_t::clone, COND_INIT_CONTACT_SEEN, entry_t::condvar, DBG2, DBG_MGR, DESTROY_IF, entry_create(), FALSE, get_entry_by_sa(), ike_sa_t::get_id, ike_sa_t::get_my_id, ike_sa_t::get_name, ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, ike_sa_t::get_state, ike_sa_t::get_unique_id, ike_sa_t::get_version, entry_t::half_open, ike_sa_t::has_condition, IKE_CONNECTING, IKE_ESTABLISHED, IKE_PASSIVE, entry_t::ike_sa, entry_t::ike_sa_id, IKEV1, host_t::ip_equals, lock_single_segment(), entry_t::my_id, entry_t::other, entry_t::other_id, entry_t::processing, put_connected_peers(), put_entry(), put_half_open(), remove_half_open(), ike_sa_id_t::replace_values, segment, ike_sa_t::set_condition, bus_t::set_sa, condvar_t::signal, SUCCESS, TRUE, and unlock_single_segment().
 {
     /* to check the SA back in, we look for the pointer of the ike_sa
      * in all entries.
      * The lookup is done by initiator SPI, so even if the SPI has changed (e.g.
      * on reception of a IKE_SA_INIT response) the lookup will work but
      * updating of the SPI MAY be necessary...
      */
     entry_t *entry;
     ike_sa_id_t *ike_sa_id;
     host_t *other;
     identification_t *my_id, *other_id;
     u_int segment;
     ike_sa_id = ike_sa->get_id(ike_sa);
     my_id = ike_sa->get_my_id(ike_sa);
     other_id = ike_sa->get_other_eap_id(ike_sa);
     other = ike_sa->get_other_host(ike_sa);
     DBG2(DBG_MGR, "checkin IKE_SA %s[%u]", ike_sa->get_name(ike_sa),
             ike_sa->get_unique_id(ike_sa));
     /* look for the entry */
     if (get_entry_by_sa(this, ike_sa_id, ike_sa, &entry, &segment) == SUCCESS)
     {
         /* ike_sa_id must be updated */
         entry->ike_sa_id->replace_values(entry->ike_sa_id, ike_sa->get_id(ike_sa));
         /* signal waiting threads */
         entry->checked_out = FALSE;
         entry->processing = -1;
         /* check if this SA is half-open */
         if (entry->half_open && ike_sa->get_state(ike_sa) != IKE_CONNECTING)
         {
             /* not half open anymore */
             entry->half_open = FALSE;
             remove_half_open(this, entry);
         }
         else if (entry->half_open && !other->ip_equals(other, entry->other))
         {
             /* the other host's IP has changed, we must update the hash table */
             remove_half_open(this, entry);
             DESTROY_IF(entry->other);
             entry->other = other->clone(other);
             put_half_open(this, entry);
         }
         else if (!entry->half_open &&
                  ike_sa->get_state(ike_sa) == IKE_CONNECTING)
         {
             /* this is a new half-open SA */
             entry->half_open = TRUE;
             entry->other = other->clone(other);
             put_half_open(this, entry);
         }
         DBG2(DBG_MGR, "check-in of IKE_SA successful.");
         entry->condvar->signal(entry->condvar);
     }
     else
     {
         entry = entry_create();
         entry->ike_sa_id = ike_sa_id->clone(ike_sa_id);
         entry->ike_sa = ike_sa;
         if (ike_sa->get_state(ike_sa) == IKE_CONNECTING)
         {
             entry->half_open = TRUE;
             entry->other = other->clone(other);
             put_half_open(this, entry);
         }
         segment = put_entry(this, entry);
     }
     /* apply identities for duplicate test */
     if ((ike_sa->get_state(ike_sa) == IKE_ESTABLISHED ||
          ike_sa->get_state(ike_sa) == IKE_PASSIVE) &&
         entry->my_id == NULL && entry->other_id == NULL)
     {
         if (ike_sa->get_version(ike_sa) == IKEV1)
         {
             /* If authenticated and received INITIAL_CONTACT,
              * delete any existing IKE_SAs with that peer. */
             if (ike_sa->has_condition(ike_sa, COND_INIT_CONTACT_SEEN))
             {
                 /* We can't hold the segment locked while checking the
                  * uniqueness as this could lead to deadlocks.  We mark the
                  * entry as checked out while we release the lock so no other
                  * thread can acquire it.  Since it is not yet in the list of
                  * connected peers that will not cause a deadlock as no other
                  * caller of check_unqiueness() will try to check out this SA */
                 entry->checked_out = TRUE;
                 unlock_single_segment(this, segment);
                 this->public.check_uniqueness(&this->public, ike_sa, TRUE);
                 ike_sa->set_condition(ike_sa, COND_INIT_CONTACT_SEEN, FALSE);
                 /* The entry could have been modified in the mean time, e.g.
                  * because another SA was added/removed next to it or another
                  * thread is waiting, but it should still exist, so there is no
                  * need for a lookup via get_entry_by... */
                 lock_single_segment(this, segment);
                 entry->checked_out = FALSE;
                 /* We already signaled waiting threads above, we have to do that
                  * again after checking the SA out and back in again. */
                 entry->condvar->signal(entry->condvar);
             }
         }
         entry->my_id = my_id->clone(my_id);
         entry->other_id = other_id->clone(other_id);
         if (!entry->other)
         {
             entry->other = other->clone(other);
         }
         put_connected_peers(this, entry);
     }
     unlock_single_segment(this, segment);
     charon->bus->set_sa(charon->bus, NULL);
 }
METHOD (ike_sa_manager_t , checkin_and_destroy , void , private_ike_sa_manager_t * this, ike_sa_t * ike_sa)
Definition at line 1692 of file ike_sa_manager.c.
References condvar_t::broadcast, daemon_t::bus, charon, entry_t::checked_out, entry_t::condvar, DBG1, DBG2, DBG_MGR, ike_sa_t::destroy, entry_t::driveout_new_threads, entry_t::driveout_waiting_threads, entry_destroy(), FALSE, get_entry_by_sa(), ike_sa_t::get_id, ike_sa_t::get_name, ike_sa_t::get_unique_id, entry_t::half_open, entry_t::init_hash, entry_t::my_id, entry_t::other_id, chunk_t::ptr, remove_connected_peers(), remove_entry(), remove_half_open(), remove_init_hash(), segment, bus_t::set_sa, SUCCESS, TRUE, unlock_single_segment(), condvar_t::wait, and entry_t::waiting_threads.
 {
     /* deletion is a bit complex, we must ensure that no thread is waiting for
      * this SA.
      * We take this SA from the table, and start signaling while threads
      * are in the condvar.
      */
     entry_t *entry;
     ike_sa_id_t *ike_sa_id;
     u_int segment;
     ike_sa_id = ike_sa->get_id(ike_sa);
     DBG2(DBG_MGR, "checkin and destroy IKE_SA %s[%u]", ike_sa->get_name(ike_sa),
             ike_sa->get_unique_id(ike_sa));
     if (get_entry_by_sa(this, ike_sa_id, ike_sa, &entry, &segment) == SUCCESS)
     {
         if (entry->driveout_waiting_threads && entry->driveout_new_threads)
         {   /* it looks like flush() has been called and the SA is being deleted
              * anyway, just check it in */
             DBG2(DBG_MGR, "ignored check-in and destroy of IKE_SA during shutdown");
             entry->checked_out = FALSE;
             entry->condvar->broadcast(entry->condvar);
             unlock_single_segment(this, segment);
             return;
         }
         /* drive out waiting threads, as we are in hurry */
         entry->driveout_waiting_threads = TRUE;
         /* mark it, so no new threads can get this entry */
         entry->driveout_new_threads = TRUE;
         /* wait until all workers have done their work */
         while (entry->waiting_threads)
         {
             /* wake up all */
             entry->condvar->broadcast(entry->condvar);
             /* they will wake us again when their work is done */
             entry->condvar->wait(entry->condvar, this->segments[segment].mutex);
         }
         remove_entry(this, entry);
         unlock_single_segment(this, segment);
         if (entry->half_open)
         {
             remove_half_open(this, entry);
         }
         if (entry->my_id && entry->other_id)
         {
             remove_connected_peers(this, entry);
         }
         if (entry->init_hash.ptr)
         {
             remove_init_hash(this, entry->init_hash);
         }
         entry_destroy(entry);
         DBG2(DBG_MGR, "check-in and destroy of IKE_SA successful");
     }
     else
     {
         DBG1(DBG_MGR, "tried to check-in and delete nonexisting IKE_SA");
         ike_sa->destroy(ike_sa);
     }
     charon->bus->set_sa(charon->bus, NULL);
 }
METHOD (ike_sa_manager_t , create_id_enumerator , enumerator_t * , private_ike_sa_manager_t * this, identification_t * me, identification_t * other, int family)
Definition at line 1769 of file ike_sa_manager.c.
References chunk_hash(), chunk_hash_inc(), linked_list_t::clone_offset, connected_peers_match(), linked_list_t::create_enumerator, enumerator_create_cleaner(), enumerator_create_empty(), identification_t::get_encoding, id_enumerator_cleanup(), lock, table_item_t::next, rwlock_t::read_lock, connected_peers_t::sas, segment, rwlock_t::unlock, and table_item_t::value.
 {
     table_item_t *item;
     u_int row, segment;
     rwlock_t *lock;
     linked_list_t *ids = NULL;
     row = chunk_hash_inc(other->get_encoding(other),
                          chunk_hash(me->get_encoding(me))) & this->table_mask;
     segment = row & this->segment_mask;
     lock = this->connected_peers_segments[segment].lock;
     lock->read_lock(lock);
     item = this->connected_peers_table[row];
     while (item)
     {
         connected_peers_t *current = item->value;
         if (connected_peers_match(current, me, other, family))
         {
             ids = current->sas->clone_offset(current->sas,
                                              offsetof(ike_sa_id_t, clone));
             break;
         }
         item = item->next;
     }
     lock->unlock(lock);
     if (!ids)
     {
         return enumerator_create_empty();
     }
     return enumerator_create_cleaner(ids->create_enumerator(ids),
                                      (void*)id_enumerator_cleanup, ids);
 }
METHOD (ike_sa_manager_t , check_uniqueness , bool , private_ike_sa_manager_t * this, ike_sa_t * ike_sa, bool force_replace)
Definition at line 1883 of file ike_sa_manager.c.
References daemon_t::bus, cancel(), charon, DBG1, DBG_IKE, enumerator_t::destroy, DESTROY_ME, enforce_replace(), enumerator_t::enumerate, host_t::equals, peer_cfg_t::equals, FALSE, host_t::get_family, ike_sa_t::get_my_id, ike_sa_t::get_other_eap_id, ike_sa_t::get_other_host, ike_sa_t::get_peer_cfg, ike_sa_t::get_state, peer_cfg_t::get_unique_policy, IKE_ESTABLISHED, IKE_REKEYING, bus_t::ike_updown, me, bus_t::set_sa, status, SUCCESS, TRUE, UNIQUE_KEEP, UNIQUE_NEVER, UNIQUE_NO, and UNIQUE_REPLACE.
 {
     bool cancel = FALSE;
     peer_cfg_t *peer_cfg;
     unique_policy_t policy;
     enumerator_t *enumerator;
     ike_sa_id_t *id = NULL;
     identification_t *me, *other;
     host_t *other_host;
     peer_cfg = ike_sa->get_peer_cfg(ike_sa);
     policy = peer_cfg->get_unique_policy(peer_cfg);
     if (policy == UNIQUE_NEVER || (policy == UNIQUE_NO && !force_replace))
     {
         return FALSE;
     }
     me = ike_sa->get_my_id(ike_sa);
     other = ike_sa->get_other_eap_id(ike_sa);
     other_host = ike_sa->get_other_host(ike_sa);
     enumerator = create_id_enumerator(this, me, other,
                                       other_host->get_family(other_host));
     while (enumerator->enumerate(enumerator, &id))
     {
         status_t status = SUCCESS;
         ike_sa_t *duplicate;
         duplicate = checkout(this, id);
         if (!duplicate)
         {
             continue;
         }
         if (force_replace)
         {
             DBG1(DBG_IKE, "destroying duplicate IKE_SA for peer '%Y', "
                  "received INITIAL_CONTACT", other);
             charon->bus->ike_updown(charon->bus, duplicate, FALSE);
             checkin_and_destroy(this, duplicate);
             continue;
         }
         peer_cfg = duplicate->get_peer_cfg(duplicate);
         if (peer_cfg && peer_cfg->equals(peer_cfg, ike_sa->get_peer_cfg(ike_sa)))
         {
             switch (duplicate->get_state(duplicate))
             {
                 case IKE_ESTABLISHED:
                 case IKE_REKEYING:
                     switch (policy)
                     {
                         case UNIQUE_REPLACE:
                             status = enforce_replace(this, duplicate, ike_sa,
                                                      other, other_host);
                             break;
                         case UNIQUE_KEEP:
                             /* potential reauthentication? */
                             if (!other_host->equals(other_host,
                                         duplicate->get_other_host(duplicate)))
{
                                 cancel = TRUE;
                                 /* we keep the first IKE_SA and delete all
                                  * other duplicates that might exist */
                                 policy = UNIQUE_REPLACE;
                             }
                             break;
                         default:
                             break;
                     }
                     break;
                 default:
                     break;
             }
         }
         if (status == DESTROY_ME)
         {
             checkin_and_destroy(this, duplicate);
         }
         else
         {
             checkin(this, duplicate);
         }
     }
     enumerator->destroy(enumerator);
     /* reset thread's current IKE_SA after checkin */
     charon->bus->set_sa(charon->bus, ike_sa);
     return cancel;
 }
METHOD (ike_sa_manager_t , has_contact , bool , private_ike_sa_manager_t * this, identification_t * me, identification_t * other, int family)
Definition at line 1971 of file ike_sa_manager.c.
References chunk_hash(), chunk_hash_inc(), connected_peers_match(), FALSE, found, identification_t::get_encoding, lock, table_item_t::next, rwlock_t::read_lock, segment, TRUE, rwlock_t::unlock, and table_item_t::value.
 {
     table_item_t *item;
     u_int row, segment;
     rwlock_t *lock;
     bool found = FALSE;
     row = chunk_hash_inc(other->get_encoding(other),
                          chunk_hash(me->get_encoding(me))) & this->table_mask;
     segment = row & this->segment_mask;
     lock = this->connected_peers_segments[segment].lock;
     lock->read_lock(lock);
     item = this->connected_peers_table[row];
     while (item)
     {
         if (connected_peers_match(item->value, me, other, family))
         {
             found = TRUE;
             break;
         }
         item = item->next;
     }
     lock->unlock(lock);
     return found;
 }
METHOD (ike_sa_manager_t , get_count , u_int , private_ike_sa_manager_t * this)
Definition at line 2000 of file ike_sa_manager.c.
References count, mutex_t::lock, mutex, segment, and mutex_t::unlock.
 {
     u_int segment, count = 0;
     mutex_t *mutex;
     for (segment = 0; segment < this->segment_count; segment++)
     {
         mutex = this->segments[segment & this->segment_mask].mutex;
         mutex->lock(mutex);
         count += this->segments[segment].count;
         mutex->unlock(mutex);
     }
     return count;
 }
METHOD (ike_sa_manager_t , get_half_open_count , u_int , private_ike_sa_manager_t * this, host_t * ip, bool responder_only)
Definition at line 2016 of file ike_sa_manager.c.
References addr, chunk_equals(), chunk_hash(), count, half_open_t::count, half_open_t::count_responder, host_t::get_address, lock, table_item_t::next, half_open_t::other, rwlock_t::read_lock, ref_cur(), segment, rwlock_t::unlock, and table_item_t::value.
 {
     table_item_t *item;
     u_int row, segment;
     rwlock_t *lock;
     chunk_t addr;
     u_int count = 0;
     if (ip)
     {
         addr = ip->get_address(ip);
         row = chunk_hash(addr) & this->table_mask;
         segment = row & this->segment_mask;
         lock = this->half_open_segments[segment].lock;
         lock->read_lock(lock);
         item = this->half_open_table[row];
         while (item)
         {
             half_open_t *half_open = item->value;
             if (chunk_equals(addr, half_open->other))
             {
                 count = responder_only ? half_open->count_responder
                                        : half_open->count;
                 break;
             }
             item = item->next;
         }
         lock->unlock(lock);
     }
     else
     {
         count = responder_only ? (u_int)ref_cur(&this->half_open_count_responder)
                                : (u_int)ref_cur(&this->half_open_count);
     }
     return count;
 }
METHOD (ike_sa_manager_t , set_spi_cb , void , private_ike_sa_manager_t * this, spi_cb_t callback, void * data)
Definition at line 2055 of file ike_sa_manager.c.
References callback, and data.
 {
     this->spi_lock->write_lock(this->spi_lock);
     this->spi_cb.cb = callback;
     this->spi_cb.data = data;
     this->spi_lock->unlock(this->spi_lock);
 }
METHOD (ike_sa_manager_t , flush , void , private_ike_sa_manager_t * this)
Definition at line 2064 of file ike_sa_manager.c.
References condvar_t::broadcast, daemon_t::bus, charon, entry_t::checked_out, entry_t::condvar, create_table_enumerator(), DBG2, DBG_MGR, ike_sa_t::delete, enumerator_t::destroy, entry_t::driveout_new_threads, entry_t::driveout_waiting_threads, entry_destroy(), enumerator_t::enumerate, FALSE, ike_sa_t::get_state, ike_sa_t::get_version, entry_t::half_open, IKE_DELETING, IKE_ESTABLISHED, IKE_REKEYING, entry_t::ike_sa, bus_t::ike_updown, IKEV2, entry_t::init_hash, lock_all_segments(), entry_t::my_id, entry_t::other_id, chunk_t::ptr, remove_connected_peers(), remove_entry_at(), remove_half_open(), remove_init_hash(), rng, segment, bus_t::set_sa, TRUE, unlock_all_segments(), condvar_t::wait, and entry_t::waiting_threads.
 {
     /* destroy all list entries */
     enumerator_t *enumerator;
     entry_t *entry;
     u_int segment;
     lock_all_segments(this);
     DBG2(DBG_MGR, "going to destroy IKE_SA manager and all managed IKE_SA's");
     /* Step 1: drive out all waiting threads  */
     DBG2(DBG_MGR, "set driveout flags for all stored IKE_SA's");
     enumerator = create_table_enumerator(this);
     while (enumerator->enumerate(enumerator, &entry, &segment))
     {
         /* do not accept new threads, drive out waiting threads */
         entry->driveout_new_threads = TRUE;
         entry->driveout_waiting_threads = TRUE;
     }
     enumerator->destroy(enumerator);
     DBG2(DBG_MGR, "wait for all threads to leave IKE_SA's");
     /* Step 2: wait until all are gone */
     enumerator = create_table_enumerator(this);
     while (enumerator->enumerate(enumerator, &entry, &segment))
     {
         while (entry->waiting_threads || entry->checked_out)
         {
             /* wake up all */
             entry->condvar->broadcast(entry->condvar);
             /* go sleeping until they are gone */
             entry->condvar->wait(entry->condvar, this->segments[segment].mutex);
         }
     }
     enumerator->destroy(enumerator);
     DBG2(DBG_MGR, "delete all IKE_SA's");
     /* Step 3: initiate deletion of all IKE_SAs */
     enumerator = create_table_enumerator(this);
     while (enumerator->enumerate(enumerator, &entry, &segment))
     {
         charon->bus->set_sa(charon->bus, entry->ike_sa);
         if (entry->ike_sa->get_version(entry->ike_sa) == IKEV2)
         {   /* as the delete never gets processed, fire down events */
             switch (entry->ike_sa->get_state(entry->ike_sa))
             {
                 case IKE_ESTABLISHED:
                 case IKE_REKEYING:
                 case IKE_DELETING:
                     charon->bus->ike_updown(charon->bus, entry->ike_sa, FALSE);
                     break;
                 default:
                     break;
             }
         }
         entry->ike_sa->delete(entry->ike_sa);
     }
     enumerator->destroy(enumerator);
     DBG2(DBG_MGR, "destroy all entries");
     /* Step 4: destroy all entries */
     enumerator = create_table_enumerator(this);
     while (enumerator->enumerate(enumerator, &entry, &segment))
     {
         charon->bus->set_sa(charon->bus, entry->ike_sa);
         if (entry->half_open)
         {
             remove_half_open(this, entry);
         }
         if (entry->my_id && entry->other_id)
         {
             remove_connected_peers(this, entry);
         }
         if (entry->init_hash.ptr)
         {
             remove_init_hash(this, entry->init_hash);
         }
         remove_entry_at((private_enumerator_t*)enumerator);
         entry_destroy(entry);
     }
     enumerator->destroy(enumerator);
     charon->bus->set_sa(charon->bus, NULL);
     unlock_all_segments(this);
     this->spi_lock->write_lock(this->spi_lock);
     this->rng->destroy(this->rng);
     this->rng = NULL;
     this->spi_cb.cb = NULL;
     this->spi_cb.data = NULL;
     this->spi_lock->unlock(this->spi_lock);
 }
METHOD (ike_sa_manager_t , destroy , void , private_ike_sa_manager_t * this)
Definition at line 2154 of file ike_sa_manager.c.
References free(), lock, and mutex.
 {
     u_int i;
     /* these are already cleared in flush() above */
     free(this->ike_sa_table);
     free(this->half_open_table);
     free(this->connected_peers_table);
     free(this->init_hashes_table);
     for (i = 0; i < this->segment_count; i++)
     {
         this->segments[i].mutex->destroy(this->segments[i].mutex);
         this->half_open_segments[i].lock->destroy(this->half_open_segments[i].lock);
         this->connected_peers_segments[i].lock->destroy(this->connected_peers_segments[i].lock);
         this->init_hashes_segments[i].mutex->destroy(this->init_hashes_segments[i].mutex);
     }
     free(this->segments);
     free(this->half_open_segments);
     free(this->connected_peers_segments);
     free(this->init_hashes_segments);
     this->spi_lock->destroy(this->spi_lock);
     free(this);
 }
static void put_connected_peers (private_ike_sa_manager_t * this, entry_t * entry) static
Put an SA between two peers into the hash table.
Definition at line 855 of file ike_sa_manager.c.
References chunk_hash(), chunk_hash_inc(), ike_sa_id_t::clone, identification_t::clone, connected_peers_match(), ike_sa_id_t::equals, family, linked_list_t::find_first, identification_t::get_encoding, host_t::get_family, entry_t::ike_sa_id, INIT, linked_list_t::insert_last, linked_list_create(), lock, entry_t::my_id, next, table_item_t::next, entry_t::other, entry_t::other_id, connected_peers_t::sas, segment, SUCCESS, rwlock_t::unlock, value, table_item_t::value, and rwlock_t::write_lock.
Referenced by METHOD().
 {
     table_item_t *item;
     u_int row, segment;
     rwlock_t *lock;
     connected_peers_t *connected_peers;
     chunk_t my_id, other_id;
     int family;
     my_id = entry->my_id->get_encoding(entry->my_id);
     other_id = entry->other_id->get_encoding(entry->other_id);
     family = entry->other->get_family(entry->other);
     row = chunk_hash_inc(other_id, chunk_hash(my_id)) & this->table_mask;
     segment = row & this->segment_mask;
     lock = this->connected_peers_segments[segment].lock;
     lock->write_lock(lock);
     item = this->connected_peers_table[row];
     while (item)
     {
         connected_peers = item->value;
         if (connected_peers_match(connected_peers, entry->my_id,
                                   entry->other_id, family))
         {
             if (connected_peers->sas->find_first(connected_peers->sas,
                     (linked_list_match_t)entry->ike_sa_id->equals,
                     NULL, entry->ike_sa_id) == SUCCESS)
             {
                 lock->unlock(lock);
                 return;
             }
             break;
         }
         item = item->next;
     }
     if (!item)
     {
         INIT(connected_peers,
             .my_id = entry->my_id->clone(entry->my_id),
             .other_id = entry->other_id->clone(entry->other_id),
             .family = family,
             .sas = linked_list_create(),
         );
         INIT(item,
             .value = connected_peers,
             .next = this->connected_peers_table[row],
         );
         this->connected_peers_table[row] = item;
     }
     connected_peers->sas->insert_last(connected_peers->sas,
                                       entry->ike_sa_id->clone(entry->ike_sa_id));
     this->connected_peers_segments[segment].count++;
     lock->unlock(lock);
 }
static u_int put_entry (private_ike_sa_manager_t * this, entry_t * entry) static
Put an entry into the hash table. Note: The caller has to unlock the returned segment.
Definition at line 583 of file ike_sa_manager.c.
References entry_t::ike_sa_id, ike_sa_id_hash(), INIT, lock_single_segment(), table_item_t::next, segment, and value.
Referenced by METHOD().
 {
     table_item_t *current, *item;
     u_int row, segment;
     INIT(item,
         .value = entry,
     );
     row = ike_sa_id_hash(entry->ike_sa_id) & this->table_mask;
     segment = row & this->segment_mask;
     lock_single_segment(this, segment);
     current = this->ike_sa_table[row];
     if (current)
     {   /* insert at the front of current bucket */
         item->next = current;
     }
     this->ike_sa_table[row] = item;
     this->segments[segment].count++;
     return segment;
 }
static void put_half_open (private_ike_sa_manager_t * this, entry_t * entry) static
Put a half-open SA into the hash table.
Definition at line 751 of file ike_sa_manager.c.
References addr, chunk_clone, chunk_equals(), chunk_hash(), half_open_t::count, half_open_t::count_responder, host_t::get_address, entry_t::ike_sa_id, INIT, ike_sa_id_t::is_initiator, lock, next, table_item_t::next, entry_t::other, half_open_t::other, ref_get(), segment, rwlock_t::unlock, value, table_item_t::value, and rwlock_t::write_lock.
Referenced by METHOD().
 {
     table_item_t *item;
     u_int row, segment;
     rwlock_t *lock;
     ike_sa_id_t *ike_id;
     half_open_t *half_open;
     chunk_t addr;
     ike_id = entry->ike_sa_id;
     addr = entry->other->get_address(entry->other);
     row = chunk_hash(addr) & this->table_mask;
     segment = row & this->segment_mask;
     lock = this->half_open_segments[segment].lock;
     lock->write_lock(lock);
     item = this->half_open_table[row];
     while (item)
     {
         half_open = item->value;
         if (chunk_equals(addr, half_open->other))
         {
             break;
         }
         item = item->next;
     }
     if (!item)
     {
         INIT(half_open,
             .other = chunk_clone(addr),
         );
         INIT(item,
             .value = half_open,
             .next = this->half_open_table[row],
         );
         this->half_open_table[row] = item;
     }
     half_open->count++;
     ref_get(&this->half_open_count);
     if (!ike_id->is_initiator(ike_id))
     {
         half_open->count_responder++;
         ref_get(&this->half_open_count_responder);
     }
     this->half_open_segments[segment].count++;
     lock->unlock(lock);
 }
static void remove_connected_peers (private_ike_sa_manager_t * this, entry_t * entry) static
Remove an SA between two peers from the hash table.
Definition at line 914 of file ike_sa_manager.c.
References chunk_hash(), chunk_hash_inc(), connected_peers_destroy(), connected_peers_match(), linked_list_t::create_enumerator, enumerator_t::destroy, ike_sa_id_t::destroy, enumerator_t::enumerate, ike_sa_id_t::equals, family, free(), linked_list_t::get_count, identification_t::get_encoding, host_t::get_family, entry_t::ike_sa_id, lock, entry_t::my_id, table_item_t::next, entry_t::other, entry_t::other_id, linked_list_t::remove_at, connected_peers_t::sas, segment, rwlock_t::unlock, table_item_t::value, and rwlock_t::write_lock.
Referenced by METHOD().
 {
     table_item_t *item, *prev = NULL;
     u_int row, segment;
     rwlock_t *lock;
     chunk_t my_id, other_id;
     int family;
     my_id = entry->my_id->get_encoding(entry->my_id);
     other_id = entry->other_id->get_encoding(entry->other_id);
     family = entry->other->get_family(entry->other);
     row = chunk_hash_inc(other_id, chunk_hash(my_id)) & this->table_mask;
     segment = row & this->segment_mask;
     lock = this->connected_peers_segments[segment].lock;
     lock->write_lock(lock);
     item = this->connected_peers_table[row];
     while (item)
     {
         connected_peers_t *current = item->value;
         if (connected_peers_match(current, entry->my_id, entry->other_id,
                                   family))
         {
             enumerator_t *enumerator;
             ike_sa_id_t *ike_sa_id;
             enumerator = current->sas->create_enumerator(current->sas);
             while (enumerator->enumerate(enumerator, &ike_sa_id))
             {
                 if (ike_sa_id->equals(ike_sa_id, entry->ike_sa_id))
                 {
                     current->sas->remove_at(current->sas, enumerator);
                     ike_sa_id->destroy(ike_sa_id);
                     this->connected_peers_segments[segment].count--;
                     break;
                 }
             }
             enumerator->destroy(enumerator);
             if (current->sas->get_count(current->sas) == 0)
             {
                 if (prev)
                 {
                     prev->next = item->next;
                 }
                 else
                 {
                     this->connected_peers_table[row] = item->next;
                 }
                 connected_peers_destroy(current);
                 free(item);
             }
             break;
         }
         prev = item;
         item = item->next;
     }
     lock->unlock(lock);
 }
static void remove_entry (private_ike_sa_manager_t * this, entry_t * entry) static
Remove an entry from the hash table. Note: The caller MUST have a lock on the segment of this entry.
Definition at line 610 of file ike_sa_manager.c.
References free(), entry_t::ike_sa_id, ike_sa_id_hash(), table_item_t::next, segment, and table_item_t::value.
Referenced by METHOD().
 {
     table_item_t *item, *prev = NULL;
     u_int row, segment;
     row = ike_sa_id_hash(entry->ike_sa_id) & this->table_mask;
     segment = row & this->segment_mask;
     item = this->ike_sa_table[row];
     while (item)
     {
         if (item->value == entry)
         {
             if (prev)
             {
                 prev->next = item->next;
             }
             else
             {
                 this->ike_sa_table[row] = item->next;
             }
             this->segments[segment].count--;
             free(item);
             break;
         }
         prev = item;
         item = item->next;
     }
 }
static void remove_entry_at (private_enumerator_t * this) static
Remove the entry at the current enumerator position.
Definition at line 642 of file ike_sa_manager.c.
References free(), table_item_t::next, segment, and unlock_single_segment().
Referenced by METHOD().
 {
     this->entry = NULL;
     if (this->current)
     {
         table_item_t *current = this->current;
         this->manager->segments[this->segment].count--;
         this->current = this->prev;
         if (this->prev)
         {
             this->prev->next = current->next;
         }
         else
         {
             this->manager->ike_sa_table[this->row] = current->next;
             unlock_single_segment(this->manager, this->segment);
         }
         free(current);
     }
 }
static void remove_half_open (private_ike_sa_manager_t * this, entry_t * entry) static
Remove a half-open SA from the hash table.
Definition at line 803 of file ike_sa_manager.c.
References addr, chunk_equals(), chunk_hash(), half_open_t::count, half_open_t::count_responder, free(), host_t::get_address, half_open_destroy(), ignore_result, entry_t::ike_sa_id, ike_sa_id_t::is_initiator, lock, table_item_t::next, entry_t::other, half_open_t::other, ref_put(), segment, rwlock_t::unlock, table_item_t::value, and rwlock_t::write_lock.
Referenced by METHOD().
 {
     table_item_t *item, *prev = NULL;
     u_int row, segment;
     rwlock_t *lock;
     ike_sa_id_t *ike_id;
     chunk_t addr;
     ike_id = entry->ike_sa_id;
     addr = entry->other->get_address(entry->other);
     row = chunk_hash(addr) & this->table_mask;
     segment = row & this->segment_mask;
     lock = this->half_open_segments[segment].lock;
     lock->write_lock(lock);
     item = this->half_open_table[row];
     while (item)
     {
         half_open_t *half_open = item->value;
         if (chunk_equals(addr, half_open->other))
         {
             if (!ike_id->is_initiator(ike_id))
             {
                 half_open->count_responder--;
                 ignore_result(ref_put(&this->half_open_count_responder));
             }
             ignore_result(ref_put(&this->half_open_count));
             if (--half_open->count == 0)
             {
                 if (prev)
                 {
                     prev->next = item->next;
                 }
                 else
                 {
                     this->half_open_table[row] = item->next;
                 }
                 half_open_destroy(half_open);
                 free(item);
             }
             this->half_open_segments[segment].count--;
             break;
         }
         prev = item;
         item = item->next;
     }
     lock->unlock(lock);
 }
static void remove_init_hash (private_ike_sa_manager_t * this, chunk_t init_hash) static
Remove the hash of an initial IKE message from the cache.
Definition at line 1103 of file ike_sa_manager.c.
References chunk_equals(), chunk_hash(), free(), init_hash_t::hash, mutex_t::lock, mutex, table_item_t::next, segment, mutex_t::unlock, and table_item_t::value.
Referenced by METHOD().
 {
     table_item_t *item, *prev = NULL;
     u_int row, segment;
     mutex_t *mutex;
     row = chunk_hash(init_hash) & this->table_mask;
     segment = row & this->segment_mask;
     mutex = this->init_hashes_segments[segment].mutex;
     mutex->lock(mutex);
     item = this->init_hashes_table[row];
     while (item)
     {
         init_hash_t *current = item->value;
         if (chunk_equals(init_hash, current->hash))
         {
             if (prev)
             {
                 prev->next = item->next;
             }
             else
             {
                 this->init_hashes_table[row] = item->next;
             }
             free(current);
             free(item);
             break;
         }
         prev = item;
         item = item->next;
     }
     mutex->unlock(mutex);
 }
static void reset_sa (void * data) static
Reset threads SA after enumeration
Definition at line 1559 of file ike_sa_manager.c.
References daemon_t::bus, charon, and bus_t::set_sa.
Referenced by METHOD().
 {
     charon->bus->set_sa(charon->bus, NULL);
 }
static void unlock_all_segments (private_ike_sa_manager_t * this) static
Unlock all segments
Definition at line 458 of file ike_sa_manager.c.
References mutex.
Referenced by METHOD().
 {
     u_int i;
     for (i = 0; i < this->segment_count; i++)
     {
         this->segments[i].mutex->unlock(this->segments[i].mutex);
     }
 }
static void unlock_single_segment (private_ike_sa_manager_t * this, u_int index) inline static
Release the lock required to access the segment of the table row with the given index. It also works with the segment index directly.
Definition at line 435 of file ike_sa_manager.c.
References lock, and mutex_t::unlock.
Referenced by get_entry_by_match_function(), METHOD(), and remove_entry_at().
 {
     mutex_t *lock = this->segments[index & this->segment_mask].mutex;
     lock->unlock(lock);
 }
static bool wait_for_entry (private_ike_sa_manager_t * this, entry_t * entry, u_int segment) static
Wait until no other thread is using an IKE_SA, return FALSE if entry not acquirable.
Definition at line 722 of file ike_sa_manager.c.
References entry_t::checked_out, entry_t::condvar, entry_t::driveout_new_threads, entry_t::driveout_waiting_threads, FALSE, condvar_t::signal, TRUE, condvar_t::wait, and entry_t::waiting_threads.
Referenced by enumerator_filter_wait(), and METHOD().
 {
     if (entry->driveout_new_threads)
     {
         /* we are not allowed to get this */
         return FALSE;
     }
     while (entry->checked_out && !entry->driveout_waiting_threads)
     {
         /* so wait until we can get it for us.
          * we register us as waiting. */
         entry->waiting_threads++;
         entry->condvar->wait(entry->condvar, this->segments[segment].mutex);
         entry->waiting_threads--;
     }
     /* hm, a deletion request forbids us to get this SA, get next one */
     if (entry->driveout_waiting_threads)
     {
         /* we must signal here, others may be waiting on it, too */
         entry->condvar->signal(entry->condvar);
         return FALSE;
     }
     return TRUE;
 }