strongSwan: mgf1_bitspender
mgf1_bitspender
mgf1
Classes
struct mgf1_bitspender_t
Typedefs
typedef struct mgf1_bitspender_t mgf1_bitspender_t
Functions
mgf1_bitspender_t * mgf1_bitspender_create (hash_algorithm_t alg, chunk_t seed, bool hash_seed)
Detailed Description
Typedef Documentation
typedef struct mgf1_bitspender_t mgf1_bitspender_t
Definition at line 27 of file mgf1_bitspender.h.
Function Documentation
mgf1_bitspender_t* mgf1_bitspender_create (hash_algorithm_t alg, chunk_t seed, bool hash_seed)
Create a mgf1_bitspender_t object
Parameters
alg Hash algorithm to be used with MGF1
seed Seed used to initialize MGF1
hash_seed Hash seed before using it as a seed for MFG1
See header.
Definition at line 183 of file mgf1_bitspender.c.
References DBG2, DBG_LIB, mgf1_t::get_hash_size, hash_algorithm_short_names, INIT, chunk_t::len, and mgf1_create().
Referenced by bliss_sampler_create(), bliss_utils_generate_c(), create_vector_from_seed(), ntru_poly_create_from_seed(), ntru_trits_create(), and START_TEST().
 {
     private_mgf1_bitspender_t *this;
     mgf1_t *mgf1;
     mgf1 = mgf1_create(alg, seed, hash_seed);
     if (!mgf1)
     {
         return NULL;
     }
     DBG2(DBG_LIB, "mgf1 based on %N is seeded with %u octets",
                    hash_algorithm_short_names, alg, seed.len);
     INIT(this,
         .public = {
             .get_bits = _get_bits,
             .get_byte = _get_byte,
             .destroy = _destroy,
         },
         .mgf1 = mgf1,
         .hash_len = mgf1->get_hash_size(mgf1),
     );
     return &this->public;
 }