strongSwan: tls_peer.c File Reference
tls_peer.c File Reference
#include "tls_peer.h"
#include <utils/debug.h>
#include <credentials/certificates/x509.h>
#include <time.h>
Classes
struct private_tls_peer_t
Typedefs
typedef struct private_tls_peer_t private_tls_peer_t
Enumerations
enum peer_state_t {
STATE_INIT, STATE_HELLO_SENT, STATE_HELLO_RECEIVED, STATE_HELLO_DONE,
STATE_CERT_SENT, STATE_CERT_RECEIVED, STATE_KEY_EXCHANGE_RECEIVED, STATE_CERTREQ_RECEIVED,
STATE_KEY_EXCHANGE_SENT, STATE_VERIFY_SENT, STATE_CIPHERSPEC_CHANGED_OUT, STATE_FINISHED_SENT,
STATE_CIPHERSPEC_CHANGED_IN, STATE_FINISHED_RECEIVED
}
Functions
static status_t process_server_hello (private_tls_peer_t *this, bio_reader_t *reader)
static bool check_certificate (private_tls_peer_t *this, certificate_t *cert)
static status_t process_certificate (private_tls_peer_t *this, bio_reader_t *reader)
static public_key_t * find_public_key (private_tls_peer_t *this)
static status_t process_modp_key_exchange (private_tls_peer_t *this, bio_reader_t *reader)
static diffie_hellman_group_t curve_to_ec_group (private_tls_peer_t *this, tls_named_curve_t curve)
static status_t process_ec_key_exchange (private_tls_peer_t *this, bio_reader_t *reader)
static status_t process_key_exchange (private_tls_peer_t *this, bio_reader_t *reader)
static status_t process_certreq (private_tls_peer_t *this, bio_reader_t *reader)
static status_t process_hello_done (private_tls_peer_t *this, bio_reader_t *reader)
static status_t process_finished (private_tls_peer_t *this, bio_reader_t *reader)
METHOD (tls_handshake_t, process, status_t, private_tls_peer_t *this, tls_handshake_type_t type, bio_reader_t *reader)
static status_t send_client_hello (private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static private_key_t * find_private_key (private_tls_peer_t *this)
static status_t send_certificate (private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_key_exchange_encrypt (private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_key_exchange_dhe (private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_key_exchange (private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_certificate_verify (private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
static status_t send_finished (private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
METHOD (tls_handshake_t, build, status_t, private_tls_peer_t *this, tls_handshake_type_t *type, bio_writer_t *writer)
METHOD (tls_handshake_t, cipherspec_changed, bool, private_tls_peer_t *this, bool inbound)
METHOD (tls_handshake_t, change_cipherspec, void, private_tls_peer_t *this, bool inbound)
METHOD (tls_handshake_t, finished, bool, private_tls_peer_t *this)
METHOD (tls_handshake_t, get_peer_id, identification_t *, private_tls_peer_t *this)
METHOD (tls_handshake_t, get_server_id, identification_t *, private_tls_peer_t *this)
METHOD (tls_handshake_t, get_auth, auth_cfg_t *, private_tls_peer_t *this)
METHOD (tls_handshake_t, destroy, void, private_tls_peer_t *this)
tls_peer_t * tls_peer_create (tls_t *tls, tls_crypto_t *crypto, tls_alert_t *alert, identification_t *peer, identification_t *server)
Typedef Documentation
typedef struct private_tls_peer_t private_tls_peer_t
Definition at line 23 of file tls_peer.c.
Enumeration Type Documentation
enum peer_state_t
Enumerator
STATE_INIT
STATE_HELLO_SENT
STATE_HELLO_RECEIVED
STATE_HELLO_DONE
STATE_CERT_SENT
STATE_CERT_RECEIVED
STATE_KEY_EXCHANGE_RECEIVED
STATE_CERTREQ_RECEIVED
STATE_KEY_EXCHANGE_SENT
STATE_VERIFY_SENT
STATE_CIPHERSPEC_CHANGED_OUT
STATE_FINISHED_SENT
STATE_CIPHERSPEC_CHANGED_IN
STATE_FINISHED_RECEIVED
Definition at line 25 of file tls_peer.c.
              {
     STATE_INIT,
     STATE_HELLO_SENT,
     STATE_HELLO_RECEIVED,
     STATE_HELLO_DONE,
     STATE_CERT_SENT,
     STATE_CERT_RECEIVED,
     STATE_KEY_EXCHANGE_RECEIVED,
     STATE_CERTREQ_RECEIVED,
     STATE_KEY_EXCHANGE_SENT,
     STATE_VERIFY_SENT,
     STATE_CIPHERSPEC_CHANGED_OUT,
     STATE_FINISHED_SENT,
     STATE_CIPHERSPEC_CHANGED_IN,
     STATE_FINISHED_RECEIVED,
 } peer_state_t;
Function Documentation
static bool check_certificate (private_tls_peer_t * this, certificate_t * cert) static
Check if a server certificate is acceptable for the given server identity
Definition at line 208 of file tls_peer.c.
References CERT_X509, x509_t::create_subjectAltName_enumerator, DBG1, DBG_TLS, enumerator_t::destroy, enumerator_t::enumerate, FALSE, certificate_t::get_subject, certificate_t::get_type, certificate_t::has_subject, id, identification_t::matches, server, and TRUE.
Referenced by process_certificate().
 {
     identification_t *id;
     if (cert->has_subject(cert, this->server))
     {
         return TRUE;
     }
     id = cert->get_subject(cert);
     if (id->matches(id, this->server))
     {
         return TRUE;
     }
     if (cert->get_type(cert) == CERT_X509)
     {
         x509_t *x509 = (x509_t*)cert;
         enumerator_t *enumerator;
         enumerator = x509->create_subjectAltName_enumerator(x509);
         while (enumerator->enumerate(enumerator, &id))
         {
             if (id->matches(id, this->server))
             {
                 enumerator->destroy(enumerator);
                 return TRUE;
             }
         }
         enumerator->destroy(enumerator);
     }
     DBG1(DBG_TLS, "server certificate does not match to '%Y'", this->server);
     return FALSE;
 }
static diffie_hellman_group_t curve_to_ec_group (private_tls_peer_t * this, tls_named_curve_t curve) static
Get the EC group for a TLS named curve
Definition at line 408 of file tls_peer.c.
References enumerator_t::destroy, enumerator_t::enumerate, and group.
Referenced by process_ec_key_exchange().
 {
     diffie_hellman_group_t group;
     tls_named_curve_t current;
     enumerator_t *enumerator;
     enumerator = this->crypto->create_ec_enumerator(this->crypto);
     while (enumerator->enumerate(enumerator, &group, &current))
     {
         if (current == curve)
         {
             enumerator->destroy(enumerator);
             return group;
         }
     }
     enumerator->destroy(enumerator);
     return 0;
 }
static private_key_t* find_private_key (private_tls_peer_t * this) static
Find a private key suitable to sign Certificate Verify
Definition at line 830 of file tls_peer.c.
References bio_reader_create(), cert, library_t::credmgr, bio_reader_t::destroy, credential_manager_t::get_private, key, KEY_ECDSA, KEY_RSA, lib, bio_reader_t::read_uint8, bio_reader_t::remaining, TLS_ECDSA_SIGN, TLS_RSA_SIGN, and type.
Referenced by send_certificate().
 {
     private_key_t *key = NULL;
     bio_reader_t *reader;
     key_type_t type;
     u_int8_t cert;
     if (!this->peer)
     {
         return NULL;
     }
     reader = bio_reader_create(this->cert_types);
     while (reader->remaining(reader) && reader->read_uint8(reader, &cert))
     {
         switch (cert)
         {
             case TLS_RSA_SIGN:
                 type = KEY_RSA;
                 break;
             case TLS_ECDSA_SIGN:
                 type = KEY_ECDSA;
                 break;
             default:
                 continue;
         }
         key = lib->credmgr->get_private(lib->credmgr, type,
                                         this->peer, this->peer_auth);
         if (key)
         {
             break;
         }
     }
     reader->destroy(reader);
     return key;
 }
static public_key_t* find_public_key (private_tls_peer_t * this) static
Find a trusted public key to encrypt/verify key exchange data
Definition at line 312 of file tls_peer.c.
References AUTH_HELPER_SUBJECT_CERT, AUTH_RULE_SUBJECT_CERT, cert, credential_manager_t::create_public_enumerator, library_t::credmgr, enumerator_t::destroy, enumerator_t::enumerate, certificate_t::equals, FALSE, found, auth_cfg_t::get, certificate_t::get_subject, KEY_ANY, and lib.
Referenced by process_ec_key_exchange(), process_modp_key_exchange(), and send_key_exchange_encrypt().
 {
     public_key_t *public = NULL, *current;
     certificate_t *cert, *found;
     enumerator_t *enumerator;
     auth_cfg_t *auth;
     cert = this->server_auth->get(this->server_auth, AUTH_HELPER_SUBJECT_CERT);
     if (cert)
     {
         enumerator = lib->credmgr->create_public_enumerator(lib->credmgr,
                         KEY_ANY, cert->get_subject(cert), this->server_auth);
         while (enumerator->enumerate(enumerator, &current, &auth))
         {
             found = auth->get(auth, AUTH_RULE_SUBJECT_CERT);
             if (found && cert->equals(cert, found))
             {
                 public = current->get_ref(current);
                 this->server_auth->merge(this->server_auth, auth, FALSE);
                 break;
             }
         }
         enumerator->destroy(enumerator);
     }
     return public;
 }
METHOD (tls_handshake_t , process , status_t , private_tls_peer_t * this, tls_handshake_type_t type, bio_reader_t * reader)
Definition at line 663 of file tls_peer.c.
References DBG1, DBG_TLS, DESTROY_IF, expected, NEED_MORE, process_certificate(), process_certreq(), process_finished(), process_hello_done(), process_key_exchange(), process_server_hello(), STATE_CERT_RECEIVED, STATE_CERTREQ_RECEIVED, STATE_CIPHERSPEC_CHANGED_IN, STATE_HELLO_RECEIVED, STATE_HELLO_SENT, STATE_KEY_EXCHANGE_RECEIVED, TLS_CERTIFICATE, TLS_CERTIFICATE_REQUEST, TLS_FATAL, TLS_FINISHED, tls_handshake_type_names, TLS_SERVER_HELLO, TLS_SERVER_HELLO_DONE, TLS_SERVER_KEY_EXCHANGE, and TLS_UNEXPECTED_MESSAGE.
 {
     tls_handshake_type_t expected;
     switch (this->state)
     {
         case STATE_HELLO_SENT:
             if (type == TLS_SERVER_HELLO)
             {
                 return process_server_hello(this, reader);
             }
             expected = TLS_SERVER_HELLO;
             break;
         case STATE_HELLO_RECEIVED:
             if (type == TLS_CERTIFICATE)
             {
                 return process_certificate(this, reader);
             }
             expected = TLS_CERTIFICATE;
             break;
         case STATE_CERT_RECEIVED:
             if (type == TLS_SERVER_KEY_EXCHANGE)
             {
                 return process_key_exchange(this, reader);
             }
             /* fall through since TLS_SERVER_KEY_EXCHANGE is optional */
         case STATE_KEY_EXCHANGE_RECEIVED:
             if (type == TLS_CERTIFICATE_REQUEST)
             {
                 return process_certreq(this, reader);
             }
             /* no cert request, server does not want to authenticate us */
             DESTROY_IF(this->peer);
             this->peer = NULL;
             /* fall through since TLS_CERTIFICATE_REQUEST is optional */
         case STATE_CERTREQ_RECEIVED:
             if (type == TLS_SERVER_HELLO_DONE)
             {
                 return process_hello_done(this, reader);
             }
             expected = TLS_SERVER_HELLO_DONE;
             break;
         case STATE_CIPHERSPEC_CHANGED_IN:
             if (type == TLS_FINISHED)
             {
                 return process_finished(this, reader);
             }
             expected = TLS_FINISHED;
             break;
         default:
             DBG1(DBG_TLS, "TLS %N not expected in current state",
                  tls_handshake_type_names, type);
             this->alert->add(this->alert, TLS_FATAL, TLS_UNEXPECTED_MESSAGE);
             return NEED_MORE;
     }
     DBG1(DBG_TLS, "TLS %N expected, but received %N",
          tls_handshake_type_names, expected, tls_handshake_type_names, type);
     this->alert->add(this->alert, TLS_FATAL, TLS_UNEXPECTED_MESSAGE);
     return NEED_MORE;
 }
METHOD (tls_handshake_t , build , status_t , private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer)
Definition at line 1090 of file tls_peer.c.
References INVALID_STATE, send_certificate(), send_certificate_verify(), send_client_hello(), send_finished(), send_key_exchange(), STATE_CERT_SENT, STATE_CIPHERSPEC_CHANGED_OUT, STATE_HELLO_DONE, STATE_INIT, and STATE_KEY_EXCHANGE_SENT.
 {
     switch (this->state)
     {
         case STATE_INIT:
             return send_client_hello(this, type, writer);
         case STATE_HELLO_DONE:
             if (this->peer)
             {
                 return send_certificate(this, type, writer);
             }
             /* otherwise fall through to next state */
         case STATE_CERT_SENT:
             return send_key_exchange(this, type, writer);
         case STATE_KEY_EXCHANGE_SENT:
             if (this->peer)
             {
                 return send_certificate_verify(this, type, writer);
             }
             else
             {
                 return INVALID_STATE;
             }
         case STATE_CIPHERSPEC_CHANGED_OUT:
             return send_finished(this, type, writer);
         default:
             return INVALID_STATE;
     }
 }
METHOD (tls_handshake_t , cipherspec_changed , bool , private_tls_peer_t * this, bool inbound)
Definition at line 1121 of file tls_peer.c.
References STATE_FINISHED_RECEIVED, STATE_FINISHED_SENT, STATE_HELLO_RECEIVED, STATE_KEY_EXCHANGE_SENT, and STATE_VERIFY_SENT.
 {
     if (inbound)
     {
         if (this->resume)
         {
             return this->state == STATE_HELLO_RECEIVED;
         }
         return this->state == STATE_FINISHED_SENT;
     }
     else
     {
         if (this->resume)
         {
             return this->state == STATE_FINISHED_RECEIVED;
         }
         if (this->peer)
         {
             return this->state == STATE_VERIFY_SENT;
         }
         return this->state == STATE_KEY_EXCHANGE_SENT;
     }
 }
METHOD (tls_handshake_t , change_cipherspec , void , private_tls_peer_t * this, bool inbound)
Definition at line 1146 of file tls_peer.c.
References STATE_CIPHERSPEC_CHANGED_IN, and STATE_CIPHERSPEC_CHANGED_OUT.
 {
     this->crypto->change_cipher(this->crypto, inbound);
     if (inbound)
     {
         this->state = STATE_CIPHERSPEC_CHANGED_IN;
     }
     else
     {
         this->state = STATE_CIPHERSPEC_CHANGED_OUT;
     }
 }
METHOD (tls_handshake_t , finished , bool , private_tls_peer_t * this)
Definition at line 1160 of file tls_peer.c.
References STATE_FINISHED_RECEIVED, and STATE_FINISHED_SENT.
 {
     if (this->resume)
     {
         return this->state == STATE_FINISHED_SENT;
     }
     return this->state == STATE_FINISHED_RECEIVED;
 }
METHOD (tls_handshake_t , get_peer_id , identification_t * , private_tls_peer_t * this)
Definition at line 1170 of file tls_peer.c.
 {
     return this->peer;
 }
METHOD (tls_handshake_t , get_server_id , identification_t * , private_tls_peer_t * this)
Definition at line 1176 of file tls_peer.c.
References server.
 {
     return this->server;
 }
METHOD (tls_handshake_t , get_auth , auth_cfg_t * , private_tls_peer_t * this)
Definition at line 1182 of file tls_peer.c.
 {
     return this->server_auth;
 }
METHOD (tls_handshake_t , destroy , void , private_tls_peer_t * this)
Definition at line 1188 of file tls_peer.c.
References DESTROY_IF, dh, free(), and server.
 {
     DESTROY_IF(this->private);
     DESTROY_IF(this->dh);
     DESTROY_IF(this->peer);
     this->server->destroy(this->server);
     this->peer_auth->destroy(this->peer_auth);
     this->server_auth->destroy(this->server_auth);
     free(this->hashsig.ptr);
     free(this->cert_types.ptr);
     free(this->session.ptr);
     free(this);
 }
static status_t process_certificate (private_tls_peer_t * this, bio_reader_t * reader) static
Process a Certificate message
Definition at line 244 of file tls_peer.c.
References AUTH_HELPER_IM_CERT, AUTH_HELPER_SUBJECT_CERT, bio_reader_create(), BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, check_certificate(), credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, data, DBG1, DBG_TLS, bio_reader_t::destroy, certificate_t::destroy, FALSE, certificate_t::get_subject, lib, NEED_MORE, bio_reader_t::peek, bio_reader_t::read_data24, bio_reader_t::remaining, STATE_CERT_RECEIVED, TLS_ACCESS_DENIED, TLS_BAD_CERTIFICATE, TLS_CERTIFICATE, TLS_DECODE_ERROR, TLS_FATAL, TLS_WARNING, and TRUE.
Referenced by METHOD().
 {
     certificate_t *cert;
     bio_reader_t *certs;
     chunk_t data;
     bool first = TRUE;
     this->crypto->append_handshake(this->crypto,
                                    TLS_CERTIFICATE, reader->peek(reader));
     if (!reader->read_data24(reader, &data))
     {
         DBG1(DBG_TLS, "certificate message header invalid");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     certs = bio_reader_create(data);
     while (certs->remaining(certs))
     {
         if (!certs->read_data24(certs, &data))
         {
             DBG1(DBG_TLS, "certificate message invalid");
             this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
             certs->destroy(certs);
             return NEED_MORE;
         }
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_BLOB_ASN1_DER, data, BUILD_END);
         if (cert)
         {
             if (first)
             {
                 if (!check_certificate(this, cert))
                 {
                     cert->destroy(cert);
                     certs->destroy(certs);
                     this->alert->add(this->alert, TLS_FATAL, TLS_ACCESS_DENIED);
                     return NEED_MORE;
                 }
                 this->server_auth->add(this->server_auth,
                                        AUTH_HELPER_SUBJECT_CERT, cert);
                 DBG1(DBG_TLS, "received TLS server certificate '%Y'",
                      cert->get_subject(cert));
                 first = FALSE;
             }
             else
             {
                 DBG1(DBG_TLS, "received TLS intermediate certificate '%Y'",
                      cert->get_subject(cert));
                 this->server_auth->add(this->server_auth,
                                        AUTH_HELPER_IM_CERT, cert);
             }
         }
         else
         {
             DBG1(DBG_TLS, "parsing TLS certificate failed, skipped");
             this->alert->add(this->alert, TLS_WARNING, TLS_BAD_CERTIFICATE);
         }
     }
     certs->destroy(certs);
     this->state = STATE_CERT_RECEIVED;
     return NEED_MORE;
 }
static status_t process_certreq (private_tls_peer_t * this, bio_reader_t * reader) static
Process a Certificate Request message
Definition at line 549 of file tls_peer.c.
References AUTH_RULE_CA_CERT, bio_reader_create(), cert, CERT_X509, chunk_clone, library_t::credmgr, data, DBG1, DBG_TLS, bio_reader_t::destroy, credential_manager_t::get_cert, id, ID_DER_ASN1_DN, identification_create_from_encoding(), KEY_ANY, lib, NEED_MORE, bio_reader_t::peek, bio_reader_t::read_data16, bio_reader_t::read_data8, bio_reader_t::remaining, STATE_CERTREQ_RECEIVED, tls, TLS_1_2, TLS_CERTIFICATE_REQUEST, TLS_DECODE_ERROR, TLS_FATAL, and TRUE.
Referenced by METHOD().
 {
     chunk_t types, hashsig, data;
     bio_reader_t *authorities;
     identification_t *id;
     certificate_t *cert;
     if (!this->peer)
     {
         DBG1(DBG_TLS, "server requested a certificate, but client "
              "authentication disabled");
     }
     this->crypto->append_handshake(this->crypto,
                                 TLS_CERTIFICATE_REQUEST, reader->peek(reader));
     if (!reader->read_data8(reader, &types))
     {
         DBG1(DBG_TLS, "certreq message header invalid");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     this->cert_types = chunk_clone(types);
     if (this->tls->get_version(this->tls) >= TLS_1_2)
     {
         if (!reader->read_data16(reader, &hashsig))
         {
             DBG1(DBG_TLS, "certreq message invalid");
             this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
             return NEED_MORE;
         }
         this->hashsig = chunk_clone(hashsig);
     }
     if (!reader->read_data16(reader, &data))
     {
         DBG1(DBG_TLS, "certreq message invalid");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     authorities = bio_reader_create(data);
     while (authorities->remaining(authorities))
     {
         if (!authorities->read_data16(authorities, &data))
         {
             DBG1(DBG_TLS, "certreq message invalid");
             this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
             authorities->destroy(authorities);
             return NEED_MORE;
         }
         if (this->peer)
         {
             id = identification_create_from_encoding(ID_DER_ASN1_DN, data);
             cert = lib->credmgr->get_cert(lib->credmgr,
                                           CERT_X509, KEY_ANY, id, TRUE);
             if (cert)
             {
                 DBG1(DBG_TLS, "received TLS cert request for '%Y", id);
                 this->peer_auth->add(this->peer_auth, AUTH_RULE_CA_CERT, cert);
             }
             else
             {
                 DBG1(DBG_TLS, "received TLS cert request for unknown CA '%Y'", id);
             }
             id->destroy(id);
         }
     }
     authorities->destroy(authorities);
     this->state = STATE_CERTREQ_RECEIVED;
     return NEED_MORE;
 }
static status_t process_ec_key_exchange (private_tls_peer_t * this, bio_reader_t * reader) static
Process a Key Exchange message using EC Diffie Hellman
Definition at line 431 of file tls_peer.c.
References chunk_cat, chunk_from_thing, chunk_skip(), crypto_factory_t::create_dh, library_t::crypto, curve, curve_to_ec_group(), DBG1, DBG_TLS, dh, diffie_hellman_group_names, find_public_key(), free(), group, chunk_t::len, lib, NEED_MORE, bio_reader_t::peek, chunk_t::ptr, pub(), bio_reader_t::read_data8, bio_reader_t::read_uint16, bio_reader_t::read_uint8, server, STATE_KEY_EXCHANGE_RECEIVED, tls_ansi_point_format_names, TLS_ANSI_UNCOMPRESSED, TLS_BAD_CERTIFICATE, TLS_CERTIFICATE_UNKNOWN, TLS_DECODE_ERROR, tls_ecc_curve_type_names, TLS_ECC_NAMED_CURVE, TLS_FATAL, TLS_HANDSHAKE_FAILURE, TLS_INTERNAL_ERROR, tls_named_curve_names, and type.
Referenced by process_key_exchange().
 {
     diffie_hellman_group_t group;
     public_key_t *public;
     u_int8_t type;
     u_int16_t curve;
     chunk_t pub, chunk;
     chunk = reader->peek(reader);
     if (!reader->read_uint8(reader, &type))
     {
         DBG1(DBG_TLS, "received invalid Server Key Exchange");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     if (type != TLS_ECC_NAMED_CURVE)
     {
         DBG1(DBG_TLS, "ECDH curve type %N not supported",
              tls_ecc_curve_type_names, type);
         this->alert->add(this->alert, TLS_FATAL, TLS_HANDSHAKE_FAILURE);
         return NEED_MORE;
     }
     if (!reader->read_uint16(reader, &curve) ||
         !reader->read_data8(reader, &pub) || pub.len == 0)
     {
         DBG1(DBG_TLS, "received invalid Server Key Exchange");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     group = curve_to_ec_group(this, curve);
     if (!group)
     {
         DBG1(DBG_TLS, "ECDH curve %N not supported",
              tls_named_curve_names, curve);
         this->alert->add(this->alert, TLS_FATAL, TLS_HANDSHAKE_FAILURE);
         return NEED_MORE;
     }
     public = find_public_key(this);
     if (!public)
     {
         DBG1(DBG_TLS, "no TLS public key found for server '%Y'", this->server);
         this->alert->add(this->alert, TLS_FATAL, TLS_CERTIFICATE_UNKNOWN);
         return NEED_MORE;
     }
     chunk.len = 4 + pub.len;
     chunk = chunk_cat("ccc", chunk_from_thing(this->client_random),
                       chunk_from_thing(this->server_random), chunk);
     if (!this->crypto->verify(this->crypto, public, reader, chunk))
     {
         public->destroy(public);
         free(chunk.ptr);
         DBG1(DBG_TLS, "verifying DH parameters failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_BAD_CERTIFICATE);
         return NEED_MORE;
     }
     public->destroy(public);
     free(chunk.ptr);
     this->dh = lib->crypto->create_dh(lib->crypto, group);
     if (!this->dh)
     {
         DBG1(DBG_TLS, "DH group %N not supported",
              diffie_hellman_group_names, group);
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (pub.ptr[0] != TLS_ANSI_UNCOMPRESSED)
     {
         DBG1(DBG_TLS, "DH point format '%N' not supported",
              tls_ansi_point_format_names, pub.ptr[0]);
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!this->dh->set_other_public_value(this->dh, chunk_skip(pub, 1)))
     {
         DBG1(DBG_TLS, "applying DH public value failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     this->state = STATE_KEY_EXCHANGE_RECEIVED;
     return NEED_MORE;
 }
static status_t process_finished (private_tls_peer_t * this, bio_reader_t * reader) static
Process finished message
Definition at line 634 of file tls_peer.c.
References chunk_equals_const(), chunk_from_thing, DBG1, DBG_TLS, NEED_MORE, bio_reader_t::read_data, STATE_FINISHED_RECEIVED, TLS_DECODE_ERROR, TLS_DECRYPT_ERROR, TLS_FATAL, TLS_FINISHED, and TLS_INTERNAL_ERROR.
Referenced by METHOD().
 {
     chunk_t received;
     char buf[12];
     if (!reader->read_data(reader, sizeof(buf), &received))
     {
         DBG1(DBG_TLS, "received server finished too short");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     if (!this->crypto->calculate_finished(this->crypto, "server finished", buf))
     {
         DBG1(DBG_TLS, "calculating server finished failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!chunk_equals_const(received, chunk_from_thing(buf)))
     {
         DBG1(DBG_TLS, "received server finished invalid");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECRYPT_ERROR);
         return NEED_MORE;
     }
     this->state = STATE_FINISHED_RECEIVED;
     this->crypto->append_handshake(this->crypto, TLS_FINISHED, received);
     return NEED_MORE;
 }
static status_t process_hello_done (private_tls_peer_t * this, bio_reader_t * reader) static
Process Hello Done message
Definition at line 622 of file tls_peer.c.
References NEED_MORE, bio_reader_t::peek, STATE_HELLO_DONE, and TLS_SERVER_HELLO_DONE.
Referenced by METHOD().
 {
     this->crypto->append_handshake(this->crypto,
                                    TLS_SERVER_HELLO_DONE, reader->peek(reader));
     this->state = STATE_HELLO_DONE;
     return NEED_MORE;
 }
static status_t process_key_exchange (private_tls_peer_t * this, bio_reader_t * reader) static
Process a Server Key Exchange
Definition at line 523 of file tls_peer.c.
References DBG1, DBG_TLS, diffie_hellman_group_is_ec(), group, MODP_NONE, NEED_MORE, bio_reader_t::peek, process_ec_key_exchange(), process_modp_key_exchange(), TLS_FATAL, TLS_HANDSHAKE_FAILURE, and TLS_SERVER_KEY_EXCHANGE.
Referenced by METHOD().
 {
     diffie_hellman_group_t group;
     this->crypto->append_handshake(this->crypto,
                                 TLS_SERVER_KEY_EXCHANGE, reader->peek(reader));
     group = this->crypto->get_dh_group(this->crypto);
     if (group == MODP_NONE)
     {
         DBG1(DBG_TLS, "received Server Key Exchange, but not required "
              "for current suite");
         this->alert->add(this->alert, TLS_FATAL, TLS_HANDSHAKE_FAILURE);
         return NEED_MORE;
     }
     if (diffie_hellman_group_is_ec(group))
     {
         return process_ec_key_exchange(this, reader);
     }
     return process_modp_key_exchange(this, reader);
 }
static status_t process_modp_key_exchange (private_tls_peer_t * this, bio_reader_t * reader) static
Process a Key Exchange message using MODP Diffie Hellman
Definition at line 342 of file tls_peer.c.
References chunk_cat, chunk_from_thing, crypto_factory_t::create_dh, library_t::crypto, DBG1, DBG_TLS, dh, find_public_key(), free(), chunk_t::len, lib, MODP_CUSTOM, NEED_MORE, bio_reader_t::peek, chunk_t::ptr, pub(), bio_reader_t::read_data16, server, STATE_KEY_EXCHANGE_RECEIVED, TLS_BAD_CERTIFICATE, TLS_CERTIFICATE_UNKNOWN, TLS_DECODE_ERROR, TLS_FATAL, and TLS_INTERNAL_ERROR.
Referenced by process_key_exchange().
 {
     chunk_t prime, generator, pub, chunk;
     public_key_t *public;
     chunk = reader->peek(reader);
     if (!reader->read_data16(reader, &prime) ||
         !reader->read_data16(reader, &generator) ||
         !reader->read_data16(reader, &pub))
     {
         DBG1(DBG_TLS, "received invalid Server Key Exchange");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     /* reject (export) DH groups using primes smaller than 1024 bit */
     if (prime.len < 1024 / 8)
     {
         DBG1(DBG_TLS, "short DH prime received (%zu bytes)", prime.len);
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     public = find_public_key(this);
     if (!public)
     {
         DBG1(DBG_TLS, "no TLS public key found for server '%Y'", this->server);
         this->alert->add(this->alert, TLS_FATAL, TLS_CERTIFICATE_UNKNOWN);
         return NEED_MORE;
     }
     chunk.len = 2 + prime.len + 2 + generator.len + 2 + pub.len;
     chunk = chunk_cat("ccc", chunk_from_thing(this->client_random),
                       chunk_from_thing(this->server_random), chunk);
     if (!this->crypto->verify(this->crypto, public, reader, chunk))
     {
         public->destroy(public);
         free(chunk.ptr);
         DBG1(DBG_TLS, "verifying DH parameters failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_BAD_CERTIFICATE);
         return NEED_MORE;
     }
     public->destroy(public);
     free(chunk.ptr);
     this->dh = lib->crypto->create_dh(lib->crypto, MODP_CUSTOM,
                                       generator, prime);
     if (!this->dh)
     {
         DBG1(DBG_TLS, "custom DH parameters not supported");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!this->dh->set_other_public_value(this->dh, pub))
     {
         DBG1(DBG_TLS, "applying DH public value failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     this->state = STATE_KEY_EXCHANGE_RECEIVED;
     return NEED_MORE;
 }
static status_t process_server_hello (private_tls_peer_t * this, bio_reader_t * reader) static
Process a server hello message
Definition at line 141 of file tls_peer.c.
References chunk_clone, chunk_empty, chunk_equals(), chunk_from_thing, DBG1, DBG_TLS, free(), KEY_ANY, memcpy, NEED_MORE, bio_reader_t::peek, chunk_t::ptr, random, bio_reader_t::read_data, bio_reader_t::read_data16, bio_reader_t::read_data8, bio_reader_t::read_uint16, bio_reader_t::read_uint8, bio_reader_t::remaining, server, STATE_HELLO_RECEIVED, tls, tls_cipher_suite_names, TLS_DECODE_ERROR, TLS_FATAL, TLS_HANDSHAKE_FAILURE, TLS_PROTOCOL_VERSION, TLS_SERVER_HELLO, tls_version_names, TRUE, and version.
Referenced by METHOD().
 {
     u_int8_t compression;
     u_int16_t version, cipher;
     chunk_t random, session, ext = chunk_empty;
     tls_cipher_suite_t suite = 0;
     this->crypto->append_handshake(this->crypto,
                                    TLS_SERVER_HELLO, reader->peek(reader));
     if (!reader->read_uint16(reader, &version) ||
         !reader->read_data(reader, sizeof(this->server_random), &random) ||
         !reader->read_data8(reader, &session) ||
         !reader->read_uint16(reader, &cipher) ||
         !reader->read_uint8(reader, &compression) ||
         (reader->remaining(reader) && !reader->read_data16(reader, &ext)))
     {
         DBG1(DBG_TLS, "received invalid ServerHello");
         this->alert->add(this->alert, TLS_FATAL, TLS_DECODE_ERROR);
         return NEED_MORE;
     }
     memcpy(this->server_random, random.ptr, sizeof(this->server_random));
     if (!this->tls->set_version(this->tls, version))
     {
         DBG1(DBG_TLS, "negotiated version %N not supported",
              tls_version_names, version);
         this->alert->add(this->alert, TLS_FATAL, TLS_PROTOCOL_VERSION);
         return NEED_MORE;
     }
     if (chunk_equals(this->session, session))
     {
         suite = this->crypto->resume_session(this->crypto, session, this->server,
                                         chunk_from_thing(this->client_random),
                                         chunk_from_thing(this->server_random));
         if (suite)
         {
             DBG1(DBG_TLS, "resumed %N using suite %N",
                  tls_version_names, version, tls_cipher_suite_names, suite);
             this->resume = TRUE;
         }
     }
     if (!suite)
     {
         suite = cipher;
         if (!this->crypto->select_cipher_suite(this->crypto, &suite, 1, KEY_ANY))
         {
             DBG1(DBG_TLS, "received TLS cipher suite %N inacceptable",
                  tls_cipher_suite_names, suite);
             this->alert->add(this->alert, TLS_FATAL, TLS_HANDSHAKE_FAILURE);
             return NEED_MORE;
         }
         DBG1(DBG_TLS, "negotiated %N using suite %N",
              tls_version_names, version, tls_cipher_suite_names, suite);
         free(this->session.ptr);
         this->session = chunk_clone(session);
     }
     this->state = STATE_HELLO_RECEIVED;
     return NEED_MORE;
 }
static status_t send_certificate (private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send Certificate
Definition at line 869 of file tls_peer.c.
References AUTH_RULE_IM_CERT, AUTH_RULE_SUBJECT_CERT, bio_writer_create(), cert, CERT_ASN1_DER, data, DBG1, DBG_TLS, enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, find_private_key(), free(), bio_writer_t::get_buf, certificate_t::get_encoding, certificate_t::get_subject, NEED_MORE, chunk_t::ptr, STATE_CERT_SENT, TLS_CERTIFICATE, and bio_writer_t::write_data24.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     auth_rule_t rule;
     bio_writer_t *certs;
     chunk_t data;
     this->private = find_private_key(this);
     if (!this->private)
     {
         DBG1(DBG_TLS, "no TLS peer certificate found for '%Y', "
              "skipping client authentication", this->peer);
         this->peer->destroy(this->peer);
         this->peer = NULL;
     }
     /* generate certificate payload */
     certs = bio_writer_create(256);
     if (this->peer)
     {
         cert = this->peer_auth->get(this->peer_auth, AUTH_RULE_SUBJECT_CERT);
         if (cert)
         {
             if (cert->get_encoding(cert, CERT_ASN1_DER, &data))
             {
                 DBG1(DBG_TLS, "sending TLS peer certificate '%Y'",
                      cert->get_subject(cert));
                 certs->write_data24(certs, data);
                 free(data.ptr);
             }
         }
         enumerator = this->peer_auth->create_enumerator(this->peer_auth);
         while (enumerator->enumerate(enumerator, &rule, &cert))
         {
             if (rule == AUTH_RULE_IM_CERT)
             {
                 if (cert->get_encoding(cert, CERT_ASN1_DER, &data))
                 {
                     DBG1(DBG_TLS, "sending TLS intermediate certificate '%Y'",
                          cert->get_subject(cert));
                     certs->write_data24(certs, data);
                     free(data.ptr);
                 }
             }
         }
         enumerator->destroy(enumerator);
     }
     writer->write_data24(writer, certs->get_buf(certs));
     certs->destroy(certs);
     *type = TLS_CERTIFICATE;
     this->state = STATE_CERT_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_certificate_verify (private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send certificate verify
Definition at line 1049 of file tls_peer.c.
References DBG1, DBG_TLS, bio_writer_t::get_buf, NEED_MORE, STATE_VERIFY_SENT, TLS_CERTIFICATE_VERIFY, TLS_FATAL, and TLS_INTERNAL_ERROR.
Referenced by METHOD().
 {
     if (!this->private ||
         !this->crypto->sign_handshake(this->crypto, this->private,
                                       writer, this->hashsig))
     {
         DBG1(DBG_TLS, "creating TLS Certificate Verify signature failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     *type = TLS_CERTIFICATE_VERIFY;
     this->state = STATE_VERIFY_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_client_hello (private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send a client hello
Definition at line 728 of file tls_peer.c.
References bio_writer_create(), chunk_from_thing, count, crypto_factory_t::create_rng, library_t::crypto, curve, curves, DBG1, DBG2, DBG_TLS, enumerator_t::destroy, rng_t::destroy, bio_writer_t::destroy, DESTROY_IF, enumerator_t::enumerate, bio_writer_t::get_buf, rng_t::get_bytes, htoun32(), ID_FQDN, lib, NEED_MORE, rng, RNG_WEAK, server, STATE_HELLO_SENT, tls, TLS_CLIENT_HELLO, TLS_EC_POINT_UNCOMPRESSED, TLS_EXT_EC_POINT_FORMATS, TLS_EXT_ELLIPTIC_CURVES, TLS_EXT_SERVER_NAME, TLS_EXT_SIGNATURE_ALGORITHMS, TLS_FATAL, TLS_INTERNAL_ERROR, TLS_NAME_TYPE_HOST_NAME, version, bio_writer_t::wrap16, bio_writer_t::write_data, bio_writer_t::write_data16, bio_writer_t::write_data8, bio_writer_t::write_uint16, and bio_writer_t::write_uint8.
Referenced by METHOD().
 {
     tls_cipher_suite_t *suites;
     bio_writer_t *extensions, *curves = NULL;
     tls_version_t version;
     tls_named_curve_t curve;
     enumerator_t *enumerator;
     int count, i;
     rng_t *rng;
     htoun32(&this->client_random, time(NULL));
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng ||
         !rng->get_bytes(rng, sizeof(this->client_random) - 4,
                         this->client_random + 4))
     {
         DBG1(DBG_TLS, "failed to generate client random");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         DESTROY_IF(rng);
         return NEED_MORE;
     }
     rng->destroy(rng);
     /* TLS version */
     version = this->tls->get_version(this->tls);
     this->hello_version = version;
     writer->write_uint16(writer, version);
     writer->write_data(writer, chunk_from_thing(this->client_random));
     /* session identifier */
     this->session = this->crypto->get_session(this->crypto, this->server);
     writer->write_data8(writer, this->session);
     /* add TLS cipher suites */
     count = this->crypto->get_cipher_suites(this->crypto, &suites);
     writer->write_uint16(writer, count * 2);
     for (i = 0; i < count; i++)
     {
         writer->write_uint16(writer, suites[i]);
     }
     /* NULL compression only */
     writer->write_uint8(writer, 1);
     writer->write_uint8(writer, 0);
     extensions = bio_writer_create(32);
     extensions->write_uint16(extensions, TLS_EXT_SIGNATURE_ALGORITHMS);
     this->crypto->get_signature_algorithms(this->crypto, extensions);
     /* add supported Elliptic Curves, if any */
     enumerator = this->crypto->create_ec_enumerator(this->crypto);
     while (enumerator->enumerate(enumerator, NULL, &curve))
     {
         if (!curves)
         {
             extensions->write_uint16(extensions, TLS_EXT_ELLIPTIC_CURVES);
             curves = bio_writer_create(16);
         }
         curves->write_uint16(curves, curve);
     }
     enumerator->destroy(enumerator);
     if (curves)
     {
         curves->wrap16(curves);
         extensions->write_data16(extensions, curves->get_buf(curves));
         curves->destroy(curves);
         /* if we support curves, add point format extension */
         extensions->write_uint16(extensions, TLS_EXT_EC_POINT_FORMATS);
         extensions->write_uint16(extensions, 2);
         extensions->write_uint8(extensions, 1);
         extensions->write_uint8(extensions, TLS_EC_POINT_UNCOMPRESSED);
     }
     if (this->server->get_type(this->server) == ID_FQDN)
     {
         bio_writer_t *names;
         DBG2(DBG_TLS, "sending Server Name Indication for '%Y'", this->server);
         names = bio_writer_create(8);
         names->write_uint8(names, TLS_NAME_TYPE_HOST_NAME);
         names->write_data16(names, this->server->get_encoding(this->server));
         names->wrap16(names);
         extensions->write_uint16(extensions, TLS_EXT_SERVER_NAME);
         extensions->write_data16(extensions, names->get_buf(names));
         names->destroy(names);
     }
     writer->write_data16(writer, extensions->get_buf(extensions));
     extensions->destroy(extensions);
     *type = TLS_CLIENT_HELLO;
     this->state = STATE_HELLO_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_finished (private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send Finished
Definition at line 1070 of file tls_peer.c.
References chunk_from_thing, DBG1, DBG_TLS, bio_writer_t::get_buf, NEED_MORE, STATE_FINISHED_SENT, TLS_FATAL, TLS_FINISHED, TLS_INTERNAL_ERROR, and bio_writer_t::write_data.
Referenced by METHOD().
 {
     char buf[12];
     if (!this->crypto->calculate_finished(this->crypto, "client finished", buf))
     {
         DBG1(DBG_TLS, "calculating client finished data failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     writer->write_data(writer, chunk_from_thing(buf));
     *type = TLS_FINISHED;
     this->state = STATE_FINISHED_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_key_exchange (private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send client key exchange, depending on suite
Definition at line 1036 of file tls_peer.c.
References dh, send_key_exchange_dhe(), and send_key_exchange_encrypt().
Referenced by METHOD().
 {
     if (this->dh)
     {
         return send_key_exchange_dhe(this, type, writer);
     }
     return send_key_exchange_encrypt(this, type, writer);
 }
static status_t send_key_exchange_dhe (private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send client key exchange, using DHE exchange
Definition at line 988 of file tls_peer.c.
References chunk_clear(), chunk_from_thing, DBG1, DBG_TLS, dh, free(), bio_writer_t::get_buf, chunk_t::len, MODP_CUSTOM, NEED_MORE, chunk_t::ptr, pub(), STATE_KEY_EXCHANGE_SENT, TLS_ANSI_UNCOMPRESSED, TLS_CLIENT_KEY_EXCHANGE, TLS_FATAL, TLS_INTERNAL_ERROR, bio_writer_t::write_data, bio_writer_t::write_data16, and bio_writer_t::write_uint8.
Referenced by send_key_exchange().
 {
     chunk_t premaster, pub;
     if (!this->dh->get_shared_secret(this->dh, &premaster))
     {
         DBG1(DBG_TLS, "calculating premaster from DH failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (!this->crypto->derive_secrets(this->crypto, premaster,
                                       this->session, this->server,
                                       chunk_from_thing(this->client_random),
                                       chunk_from_thing(this->server_random)))
     {
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         chunk_clear(&premaster);
         return NEED_MORE;
     }
     chunk_clear(&premaster);
     if (!this->dh->get_my_public_value(this->dh, &pub))
     {
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     if (this->dh->get_dh_group(this->dh) == MODP_CUSTOM)
     {
         writer->write_data16(writer, pub);
     }
     else
     {   /* ECP uses 8bit length header only, but a point format */
         writer->write_uint8(writer, pub.len + 1);
         writer->write_uint8(writer, TLS_ANSI_UNCOMPRESSED);
         writer->write_data(writer, pub);
     }
     free(pub.ptr);
     *type = TLS_CLIENT_KEY_EXCHANGE;
     this->state = STATE_KEY_EXCHANGE_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }
static status_t send_key_exchange_encrypt (private_tls_peer_t * this, tls_handshake_type_t * type, bio_writer_t * writer) static
Send client key exchange, using premaster encryption
Definition at line 931 of file tls_peer.c.
References chunk_from_thing, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_TLS, rng_t::destroy, DESTROY_IF, ENCRYPT_RSA_PKCS1, find_public_key(), free(), bio_writer_t::get_buf, rng_t::get_bytes, htoun16(), lib, NEED_MORE, chunk_t::ptr, public, rng, RNG_STRONG, server, STATE_KEY_EXCHANGE_SENT, TLS_BAD_CERTIFICATE, TLS_CERTIFICATE_UNKNOWN, TLS_CLIENT_KEY_EXCHANGE, TLS_FATAL, TLS_INTERNAL_ERROR, and bio_writer_t::write_data16.
Referenced by send_key_exchange().
 {
     public_key_t *public;
     rng_t *rng;
     char premaster[48];
     chunk_t encrypted;
     rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
     if (!rng || !rng->get_bytes(rng, sizeof(premaster) - 2, premaster + 2))
     {
         DBG1(DBG_TLS, "failed to generate TLS premaster secret");
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         DESTROY_IF(rng);
         return NEED_MORE;
     }
     rng->destroy(rng);
     htoun16(premaster, this->hello_version);
     if (!this->crypto->derive_secrets(this->crypto, chunk_from_thing(premaster),
                                       this->session, this->server,
                                       chunk_from_thing(this->client_random),
                                       chunk_from_thing(this->server_random)))
     {
         this->alert->add(this->alert, TLS_FATAL, TLS_INTERNAL_ERROR);
         return NEED_MORE;
     }
     public = find_public_key(this);
     if (!public)
     {
         DBG1(DBG_TLS, "no TLS public key found for server '%Y'", this->server);
         this->alert->add(this->alert, TLS_FATAL, TLS_CERTIFICATE_UNKNOWN);
         return NEED_MORE;
     }
     if (!public->encrypt(public, ENCRYPT_RSA_PKCS1,
                          chunk_from_thing(premaster), &encrypted))
     {
         public->destroy(public);
         DBG1(DBG_TLS, "encrypting TLS premaster secret failed");
         this->alert->add(this->alert, TLS_FATAL, TLS_BAD_CERTIFICATE);
         return NEED_MORE;
     }
     public->destroy(public);
     writer->write_data16(writer, encrypted);
     free(encrypted.ptr);
     *type = TLS_CLIENT_KEY_EXCHANGE;
     this->state = STATE_KEY_EXCHANGE_SENT;
     this->crypto->append_handshake(this->crypto, *type, writer->get_buf(writer));
     return NEED_MORE;
 }