strongSwan: leak_detective.c File Reference
leak_detective.c File Reference
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <locale.h>
#include <time.h>
#include <errno.h>
#include "leak_detective.h"
#include <library.h>
#include <utils/utils.h>
#include <utils/debug.h>
#include <utils/backtrace.h>
#include <collections/hashtable.h>
#include <threading/thread_value.h>
#include <threading/spinlock.h>
Classes
struct private_leak_detective_t
struct memory_header_t
struct memory_tail_t
Macros
#define _GNU_SOURCE
#define MEMORY_HEADER_MAGIC 0x7ac0be11
#define MEMORY_TAIL_MAGIC 0xcafebabe
#define MEMORY_FREE_PATTERN 0xFF
#define MEMORY_ALLOC_PATTERN 0xEE
#define HOOK(ret, name,...) ret name(__VA_ARGS__)
Typedefs
typedef struct
private_leak_detective_t private_leak_detective_t
typedef struct memory_header_t memory_header_t
typedef struct memory_tail_t memory_tail_t
Functions
struct memory_header_t __attribute__ ((__packed__))
static void enable_leak_detective ()
static void disable_leak_detective ()
static bool enable_thread (bool enable)
static void add_hdr (memory_header_t *hdr)
static void remove_hdr (memory_header_t *hdr)
static bool has_hdr (memory_header_t *hdr)
static void * malloc_for_dlsym (size_t size)
static void * get_malloc_fn (char *name)
static void * real_malloc (size_t size)
static void real_free (void *ptr)
static void * real_realloc (void *ptr, size_t size)
static bool register_hooks ()
static void init_static_allocations ()
static u_int hash (backtrace_t *key)
static bool equals (backtrace_t *a, backtrace_t *b)
static int print_traces (private_leak_detective_t *this, leak_detective_report_cb_t cb, void *user, int thresh, int thresh_count, bool detailed, int *whitelisted, size_t *sum)
METHOD (leak_detective_t, report, void, private_leak_detective_t *this, bool detailed)
METHOD (leak_detective_t, set_report_cb, void, private_leak_detective_t *this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void *user)
METHOD (leak_detective_t, leaks, int, private_leak_detective_t *this)
METHOD (leak_detective_t, set_state, bool, private_leak_detective_t *this, bool enable)
METHOD (leak_detective_t, usage, void, private_leak_detective_t *this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void *user)
HOOK (void *, malloc, size_t bytes)
HOOK (void *, calloc, size_t nmemb, size_t size)
HOOK (void *, valloc, size_t size)
HOOK (void, free, void *ptr)
HOOK (void *, realloc, void *old, size_t bytes)
METHOD (leak_detective_t, destroy, void, private_leak_detective_t *this)
leak_detective_t * leak_detective_create ()
Variables
memory_header_t * previous
memory_header_t * next
backtrace_t * backtrace
u_int32_t padding [sizeof(void *)==sizeof(u_int32_t)?3:0]
u_int32_t bytes
u_int32_t magic
static memory_header_t first_header
static spinlock_t * lock
static bool enabled = FALSE
static thread_value_t * thread_disabled
char * whitelist []
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file leak_detective.c.
#define HOOK (ret, name, ...) ret name(__VA_ARGS__)
Hook definition: plain function overloading existing malloc calls
Definition at line 476 of file leak_detective.c.
#define MEMORY_ALLOC_PATTERN 0xEE
Pattern which is filled in newly allocated memory
Definition at line 95 of file leak_detective.c.
Referenced by HOOK().
#define MEMORY_FREE_PATTERN 0xFF
Pattern which is filled in memory before freeing it
Definition at line 90 of file leak_detective.c.
Referenced by HOOK().
#define MEMORY_HEADER_MAGIC 0x7ac0be11
Magic value which helps to detect memory corruption. Yummy!
Definition at line 80 of file leak_detective.c.
Referenced by HOOK().
#define MEMORY_TAIL_MAGIC 0xcafebabe
Magic written to tail of allocation
Definition at line 85 of file leak_detective.c.
Referenced by HOOK().
Typedef Documentation
typedef struct memory_header_t memory_header_t
Definition at line 97 of file leak_detective.c.
typedef struct memory_tail_t memory_tail_t
Definition at line 98 of file leak_detective.c.
typedef struct private_leak_detective_t private_leak_detective_t
Definition at line 49 of file leak_detective.c.
Function Documentation
static void add_hdr (memory_header_t * hdr) static
Add a header to the beginning of the list
Definition at line 205 of file leak_detective.c.
References first_header, spinlock_t::lock, memory_header_t::next, memory_header_t::previous, and spinlock_t::unlock.
Referenced by HOOK().
 {
     lock->lock(lock);
     hdr->next = first_header.next;
     if (hdr->next)
     {
         hdr->next->previous = hdr;
     }
     hdr->previous = &first_header;
     first_header.next = hdr;
     lock->unlock(lock);
 }
static void disable_leak_detective () static
Uninstalls the malloc hooks, disables leak detection
Definition at line 183 of file leak_detective.c.
References FALSE.
Referenced by METHOD().
 {
     enabled = FALSE;
 }
static void enable_leak_detective () static
Installs the malloc hooks, enables leak detection
Definition at line 175 of file leak_detective.c.
References TRUE.
Referenced by leak_detective_create().
 {
     enabled = TRUE;
 }
static bool enable_thread (bool enable) static
Enable/Disable leak detective for the current thread
Returns
Previous value
Definition at line 193 of file leak_detective.c.
References thread_value_t::get, thread_value_t::set, and TRUE.
Referenced by get_malloc_fn(), HOOK(), METHOD(), and print_traces().
 {
     bool before;
     before = thread_disabled->get(thread_disabled) == NULL;
     thread_disabled->set(thread_disabled, enable ? NULL : (void*)TRUE);
     return before;
 }
static bool equals (backtrace_t * a, backtrace_t * b) static
Hashtable equals function
Definition at line 621 of file leak_detective.c.
References backtrace_t::equals.
Referenced by print_traces().
 {
     return a->equals(a, b);
 }
static void* get_malloc_fn (char * name) static
Lookup a malloc function, while disabling wrappers
Definition at line 404 of file leak_detective.c.
References dlsym(), enable_thread(), FALSE, fn, and RTLD_NEXT.
Referenced by real_free(), real_malloc(), and real_realloc().
 {
     bool before = FALSE;
     void *fn;
     if (enabled)
     {
         before = enable_thread(FALSE);
     }
     fn = dlsym(RTLD_NEXT, name);
     if (enabled)
     {
         enable_thread(before);
     }
     return fn;
 }
static bool has_hdr (memory_header_t * hdr) static
Check if a header is in the list
Definition at line 235 of file leak_detective.c.
References FALSE, found, spinlock_t::lock, memory_header_t::next, TRUE, and spinlock_t::unlock.
Referenced by HOOK().
 {
     memory_header_t *current;
     bool found = FALSE;
     lock->lock(lock);
     for (current = &first_header; current != NULL; current = current->next)
     {
         if (current == hdr)
         {
             found = TRUE;
             break;
         }
     }
     lock->unlock(lock);
     return found;
 }
static u_int hash (backtrace_t * key) static
Hashtable hash function
Definition at line 602 of file leak_detective.c.
References addr, chunk_from_thing, chunk_hash_inc(), backtrace_t::create_frame_enumerator, enumerator_t::destroy, and enumerator_t::enumerate.
Referenced by print_traces().
 {
     enumerator_t *enumerator;
     void *addr;
     u_int hash = 0;
     enumerator = key->create_frame_enumerator(key);
     while (enumerator->enumerate(enumerator, &addr))
     {
         hash = chunk_hash_inc(chunk_from_thing(addr), hash);
     }
     enumerator->destroy(enumerator);
     return hash;
 }
HOOK (void * , malloc , size_t bytes)
Wrapped malloc() function
Definition at line 775 of file leak_detective.c.
References add_hdr(), memory_header_t::backtrace, backtrace_create(), bytes, memory_header_t::bytes, enable_thread(), FALSE, thread_value_t::get, memory_header_t::magic, memory_tail_t::magic, MEMORY_ALLOC_PATTERN, MEMORY_HEADER_MAGIC, MEMORY_TAIL_MAGIC, memset, and real_malloc().
 {
     memory_header_t *hdr;
     memory_tail_t *tail;
     bool before;
     if (!enabled || thread_disabled->get(thread_disabled))
     {
         return real_malloc(bytes);
     }
     hdr = real_malloc(sizeof(memory_header_t) + bytes + sizeof(memory_tail_t));
     tail = ((void*)hdr) + bytes + sizeof(memory_header_t);
     /* set to something which causes crashes */
     memset(hdr, MEMORY_ALLOC_PATTERN,
            sizeof(memory_header_t) + bytes + sizeof(memory_tail_t));
     before = enable_thread(FALSE);
     hdr->backtrace = backtrace_create(2);
     enable_thread(before);
     hdr->magic = MEMORY_HEADER_MAGIC;
     hdr->bytes = bytes;
     tail->magic = MEMORY_TAIL_MAGIC;
     add_hdr(hdr);
     return hdr + 1;
 }
HOOK (void * , calloc , size_t nmemb, size_t size)
Wrapped calloc() function
Definition at line 808 of file leak_detective.c.
References malloc(), and memset.
 {
     void *ptr;
     size *= nmemb;
     ptr = malloc(size);
     memset(ptr, 0, size);
     return ptr;
 }
HOOK (void * , valloc , size_t size)
Wrapped valloc(), TODO: currently not supported
Definition at line 822 of file leak_detective.c.
References DBG1, and DBG_LIB.
 {
     DBG1(DBG_LIB, "valloc() used, but leak-detective hook missing");
     return NULL;
 }
HOOK (void , free , void * ptr)
Wrapped free() function
Definition at line 831 of file leak_detective.c.
References backtrace, memory_header_t::backtrace, backtrace_create(), memory_header_t::bytes, backtrace_t::destroy, enable_thread(), FALSE, fprintf, thread_value_t::get, has_hdr(), backtrace_t::log, memory_header_t::magic, MEMORY_FREE_PATTERN, MEMORY_HEADER_MAGIC, MEMORY_TAIL_MAGIC, memset, real_free(), remove_hdr(), and TRUE.
 {
     memory_header_t *hdr;
     memory_tail_t *tail;
     backtrace_t *backtrace;
     bool before;
     if (!enabled || thread_disabled->get(thread_disabled))
     {
         real_free(ptr);
         return;
     }
     /* allow freeing of NULL */
     if (ptr == NULL)
     {
         return;
     }
     hdr = ptr - sizeof(memory_header_t);
     tail = ptr + hdr->bytes;
     before = enable_thread(FALSE);
     if (hdr->magic != MEMORY_HEADER_MAGIC ||
         tail->magic != MEMORY_TAIL_MAGIC)
     {
         if (has_hdr(hdr))
         {
             /* memory was allocated by our hooks but is corrupted */
             fprintf(stderr, "freeing corrupted memory (%p): "
                     "header magic 0x%x, tail magic 0x%x:\n",
                     ptr, hdr->magic, tail->magic);
         }
         else
         {
             /* memory was not allocated by our hooks */
             fprintf(stderr, "freeing invalid memory (%p)\n", ptr);
         }
         backtrace = backtrace_create(2);
         backtrace->log(backtrace, stderr, TRUE);
         backtrace->destroy(backtrace);
     }
     else
     {
         remove_hdr(hdr);
         hdr->backtrace->destroy(hdr->backtrace);
         /* clear MAGIC, set mem to something remarkable */
         memset(hdr, MEMORY_FREE_PATTERN,
                sizeof(memory_header_t) + hdr->bytes + sizeof(memory_tail_t));
         real_free(hdr);
     }
     enable_thread(before);
 }
HOOK (void * , realloc , void * old, size_t bytes)
Wrapped realloc() function
Definition at line 889 of file leak_detective.c.
References add_hdr(), backtrace, memory_header_t::backtrace, backtrace_create(), bytes, memory_header_t::bytes, backtrace_t::destroy, enable_thread(), FALSE, fprintf, free(), thread_value_t::get, backtrace_t::log, memory_header_t::magic, malloc(), MEMORY_ALLOC_PATTERN, MEMORY_HEADER_MAGIC, MEMORY_TAIL_MAGIC, memset, real_realloc(), remove_hdr(), and TRUE.
 {
     memory_header_t *hdr;
     memory_tail_t *tail;
     backtrace_t *backtrace;
     bool before;
     if (!enabled || thread_disabled->get(thread_disabled))
     {
         return real_realloc(old, bytes);
     }
     /* allow reallocation of NULL */
     if (old == NULL)
     {
         return malloc(bytes);
     }
     /* handle zero size as a free() */
     if (bytes == 0)
     {
         free(old);
         return NULL;
     }
     hdr = old - sizeof(memory_header_t);
     tail = old + hdr->bytes;
     remove_hdr(hdr);
     if (hdr->magic != MEMORY_HEADER_MAGIC ||
         tail->magic != MEMORY_TAIL_MAGIC)
     {
         fprintf(stderr, "reallocating invalid memory (%p):\n"
                 "header magic 0x%x:\n", old, hdr->magic);
         backtrace = backtrace_create(2);
         backtrace->log(backtrace, stderr, TRUE);
         backtrace->destroy(backtrace);
     }
     else
     {
         /* clear tail magic, allocate, set tail magic */
         memset(&tail->magic, MEMORY_ALLOC_PATTERN, sizeof(tail->magic));
     }
     hdr = real_realloc(hdr,
                        sizeof(memory_header_t) + bytes + sizeof(memory_tail_t));
     tail = ((void*)hdr) + bytes + sizeof(memory_header_t);
     tail->magic = MEMORY_TAIL_MAGIC;
     /* update statistics */
     hdr->bytes = bytes;
     before = enable_thread(FALSE);
     hdr->backtrace->destroy(hdr->backtrace);
     hdr->backtrace = backtrace_create(2);
     enable_thread(before);
     add_hdr(hdr);
     return hdr + 1;
 }
static void init_static_allocations () static
Some functions are hard to whitelist, as they don't use a symbol directly. Use some static initialization to suppress them on leak reports
Definition at line 589 of file leak_detective.c.
References gmtime_r(), and localtime_r().
Referenced by leak_detective_create().
 {
     struct tm tm;
     time_t t = 0;
     tzset();
     gmtime_r(&t, &tm);
     localtime_r(&t, &tm);
 }
static void* malloc_for_dlsym (size_t size) static
dlsym() might do a malloc(), but we can't do one before we get the malloc() function pointer. Use this minimalistic malloc implementation instead.
Definition at line 383 of file leak_detective.c.
References size.
Referenced by real_malloc().
 {
     static char buf[1024] = {};
     static size_t used = 0;
     char *ptr;
     /* roundup to a multiple of 32 */
     size = (size - 1) / 32 * 32 + 32;
     if (used + size > sizeof(buf))
     {
         return NULL;
     }
     ptr = buf + used;
     used += size;
     return ptr;
 }
METHOD (leak_detective_t , report , void , private_leak_detective_t * this, bool detailed)
Definition at line 709 of file leak_detective.c.
References library_t::leak_detective, lib, and print_traces().
 {
     if (lib->leak_detective)
     {
         int leaks, whitelisted = 0;
         size_t sum = 0;
         leaks = print_traces(this, this->report_cb, this->report_data,
                              0, 0, detailed, &whitelisted, &sum);
         if (this->report_scb)
         {
             this->report_scb(this->report_data, leaks, sum, whitelisted);
         }
     }
 }
METHOD (leak_detective_t , set_report_cb , void , private_leak_detective_t * this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void * user)
Definition at line 726 of file leak_detective.c.
References cb().
 {
     this->report_cb = cb;
     this->report_scb = scb;
     this->report_data = user;
 }
METHOD (leak_detective_t , leaks , int , private_leak_detective_t * this)
Definition at line 735 of file leak_detective.c.
References FALSE, and print_traces().
 {
     int whitelisted = 0;
     return print_traces(this, NULL, NULL, 0, 0, FALSE, &whitelisted, NULL);
 }
METHOD (leak_detective_t , set_state , bool , private_leak_detective_t * this, bool enable)
Definition at line 743 of file leak_detective.c.
References enable_thread().
 {
     return enable_thread(enable);
 }
METHOD (leak_detective_t , usage , void , private_leak_detective_t * this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void * user)
Definition at line 749 of file leak_detective.c.
References settings_t::get_bool, settings_t::get_int, lib, library_t::ns, print_traces(), library_t::settings, and TRUE.
 {
     bool detailed;
     int thresh, thresh_count, leaks, whitelisted = 0;
     size_t sum = 0;
     thresh = lib->settings->get_int(lib->settings,
                         "%s.leak_detective.usage_threshold", 10240, lib->ns);
     thresh_count = lib->settings->get_int(lib->settings,
                         "%s.leak_detective.usage_threshold_count", 0, lib->ns);
     detailed = lib->settings->get_bool(lib->settings,
                         "%s.leak_detective.detailed", TRUE, lib->ns);
     leaks = print_traces(this, cb, user, thresh, thresh_count,
                          detailed, &whitelisted, &sum);
     if (scb)
     {
         scb(user, leaks, sum, whitelisted);
     }
 }
METHOD (leak_detective_t , destroy , void , private_leak_detective_t * this)
Definition at line 949 of file leak_detective.c.
References spinlock_t::destroy, thread_value_t::destroy, disable_leak_detective(), free(), and memory_header_t::next.
 {
     disable_leak_detective();
     lock->destroy(lock);
     thread_disabled->destroy(thread_disabled);
     free(this);
     first_header.next = NULL;
 }
static int print_traces (private_leak_detective_t * this, leak_detective_report_cb_t cb, void * user, int thresh, int thresh_count, bool detailed, int * whitelisted, size_t * sum) static
Summarize and print backtraces
associated backtrace
total size of all allocations
number of allocations
Definition at line 629 of file leak_detective.c.
References backtrace, memory_header_t::backtrace, bytes, memory_header_t::bytes, cb(), backtrace_t::clone, backtrace_t::contains_function, count, countof, hashtable_t::create_enumerator, enumerator_t::destroy, hashtable_t::destroy, enable_thread(), enumerator_t::enumerate, equals(), FALSE, free(), hashtable_t::get, hash(), hashtable_create(), INIT, spinlock_t::lock, memory_header_t::next, hashtable_t::put, and spinlock_t::unlock.
Referenced by METHOD().
 {
     int leaks = 0;
     memory_header_t *hdr;
     enumerator_t *enumerator;
     hashtable_t *entries;
     struct {
         backtrace_t *backtrace;
         size_t bytes;
         u_int count;
     } *entry;
     bool before;
     before = enable_thread(FALSE);
     entries = hashtable_create((hashtable_hash_t)hash,
                                (hashtable_equals_t)equals, 1024);
     lock->lock(lock);
     for (hdr = first_header.next; hdr != NULL; hdr = hdr->next)
     {
         if (whitelisted &&
             hdr->backtrace->contains_function(hdr->backtrace,
                                               whitelist, countof(whitelist)))
         {
             (*whitelisted)++;
             continue;
         }
         entry = entries->get(entries, hdr->backtrace);
         if (entry)
         {
             entry->bytes += hdr->bytes;
             entry->count++;
         }
         else
         {
             INIT(entry,
                 .backtrace = hdr->backtrace->clone(hdr->backtrace),
                 .bytes = hdr->bytes,
                 .count = 1,
             );
             entries->put(entries, entry->backtrace, entry);
         }
         if (sum)
         {
             *sum += hdr->bytes;
         }
         leaks++;
     }
     lock->unlock(lock);
     enumerator = entries->create_enumerator(entries);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         if (cb)
         {
             if (!thresh || entry->bytes >= thresh)
             {
                 if (!thresh_count || entry->count >= thresh_count)
                 {
                     cb(user, entry->count, entry->bytes, entry->backtrace,
                        detailed);
                 }
             }
         }
         entry->backtrace->destroy(entry->backtrace);
         free(entry);
     }
     enumerator->destroy(enumerator);
     entries->destroy(entries);
     enable_thread(before);
     return leaks;
 }
static void real_free (void * ptr) static
Call original free()
Definition at line 448 of file leak_detective.c.
References fn, and get_malloc_fn().
Referenced by HOOK(), and register_hooks().
 {
     static void (*fn)(void *ptr);
     if (!fn)
     {
         fn = get_malloc_fn("free");
     }
     return fn(ptr);
 }
static void* real_malloc (size_t size) static
Call original malloc()
Definition at line 424 of file leak_detective.c.
References fn, get_malloc_fn(), malloc_for_dlsym(), and size.
Referenced by HOOK(), and register_hooks().
 {
     static void* (*fn)(size_t size);
     static int recursive = 0;
     if (!fn)
     {
         /* checking recursiveness should actually be thread-specific. But as
          * it is very likely that the first allocation is done before we go
          * multi-threaded, we keep it simple. */
         if (recursive)
         {
             return malloc_for_dlsym(size);
         }
         recursive++;
         fn = get_malloc_fn("malloc");
         recursive--;
     }
     return fn(size);
 }
static void* real_realloc (void * ptr, size_t size) static
Call original realloc()
Definition at line 462 of file leak_detective.c.
References fn, get_malloc_fn(), and size.
Referenced by HOOK(), and register_hooks().
 {
     static void* (*fn)(void *ptr, size_t size);
     if (!fn)
     {
         fn = get_malloc_fn("realloc");
     }
     return fn(ptr, size);
 }
static bool register_hooks () static
Hook initialization when not using hooks, resolve functions.
Definition at line 481 of file leak_detective.c.
References real_free(), real_malloc(), real_realloc(), and TRUE.
Referenced by leak_detective_create().
 {
     void *buf = real_malloc(8);
     buf = real_realloc(buf, 16);
     real_free(buf);
     return TRUE;
 }
static void remove_hdr (memory_header_t * hdr) static
Remove a header from the list
Definition at line 221 of file leak_detective.c.
References spinlock_t::lock, memory_header_t::next, memory_header_t::previous, and spinlock_t::unlock.
Referenced by HOOK().
 {
     lock->lock(lock);
     if (hdr->next)
     {
         hdr->next->previous = hdr->previous;
     }
     hdr->previous->next = hdr->next;
     lock->unlock(lock);
 }
Variable Documentation
backtrace_t* backtrace
backtrace taken during (re-)allocation
Definition at line 115 of file leak_detective.c.
Referenced by backtrace_create(), backtrace_dump(), fatal_signal_handler(), HOOK(), print_traces(), and segv_handler().
u_int32_t bytes
Number of bytes following after the header
Definition at line 125 of file leak_detective.c.
Referenced by bench_prf(), calc_range(), chunk_skip(), chunk_skip_end(), HOOK(), host_create_netmask(), list_child(), mem_printf_hook(), METHOD(), parse_bytes(), pgp_read_mpi(), print_traces(), vici.protocol.Message::serialize(), and update_usebytes().
bool enabled = FALSE static
Is leak detection currently enabled?
Definition at line 165 of file leak_detective.c.
Referenced by METHOD(), and plugin_cb().
memory_header_t first_header static
Initial value:
= {
    .magic = MEMORY_HEADER_MAGIC,
}
first mem header is just a dummy to chain the others on it...
Definition at line 153 of file leak_detective.c.
Referenced by add_hdr().
spinlock_t* lock static
Spinlock to access header linked list
Definition at line 160 of file leak_detective.c.
Referenced by add_cert_internal(), add_entry(), add_fallback_to_section(), build_fds(), cache_queue(), CALLBACK(), cancellation_rwcond(), check_timeouts(), cowfs_create(), cowfs_readdir(), create_enumerator(), create_function(), create_private_enumerator(), create_trusted_cert_enumerator(), create_usercert_enumerator(), deliver_inbound(), deliver_plain(), encode(), ensure_section(), find_socket(), find_token(), find_value(), get_any_socket(), get_interface_index(), get_rd(), get_route(), get_wr(), handle_events(), handle_plain(), init_address_list(), initiator_destroy(), journal_register(), kernel_libipsec_router_create(), load_internal(), lock_single_segment(), merge_config(), METHOD(), parse_token(), print_all(), print_global(), print_one(), process_addr(), process_link(), process_route(), put_connected_peers(), put_half_open(), remove_connected_peers(), remove_entry(), remove_half_open(), scan_fds(), send_outbound(), set_value(), and unlock_single_segment().
u_int32_t magic
magic bytes to detect bad free or heap underflow, MEMORY_HEADER_MAGIC
Magic bytes to detect heap overflow, MEMORY_TAIL_MAGIC
Definition at line 130 of file leak_detective.c.
Referenced by __attribute__(), check_memwipe(), and START_TEST().
memory_header_t* next
Pointer to next entry in linked list
Definition at line 110 of file leak_detective.c.
Referenced by format-options.Parser::__add_option(), format-options.Parser::__get_option(), aikgen_dbg(), asn1_known_oid(), attest_dbg(), build_peer_cfg(), CALLBACK(), check_and_put_init_hash(), dbg_pt_tls(), destroy_internal(), encrypted_payload_create_from_plain(), endecode_enumerate(), find_value(), generate(), generate_message(), get_auth_cfg(), get_message_data(), imcv_dbg(), METHOD(), pacman_dbg(), put_connected_peers(), put_half_open(), reauthenticate(), rehash(), remove_element(), scepclient_dbg(), and starter_dbg().
u_int32_t padding[sizeof(void *)==sizeof(u_int32_t)?3:0]
Padding to make sizeof(memory_header_t) == 32
Definition at line 120 of file leak_detective.c.
Referenced by add_unity_split_attribute(), append_ts(), decrypt_content(), encrypt_content(), generate(), mem_printf_hook(), METHOD(), pem_decrypt(), remove_padding(), and verify_padding().
memory_header_t* previous
Pointer to previous entry in linked list
Definition at line 105 of file leak_detective.c.
Referenced by decrypt_payloads(), and remove_element().
thread_value_t* thread_disabled static
Is leak detection disabled for the current thread?
Definition at line 170 of file leak_detective.c.
char* whitelist[]
Leak report white list
List of functions using static allocation buffers or should be suppressed otherwise on leak report.
Definition at line 497 of file leak_detective.c.