strongSwan: seg_env.c File Reference
seg_env.c File Reference
#include "seg_env.h"
#include "imcv.h"
#include "pa_tnc/pa_tnc_msg.h"
#include "ietf/ietf_attr_pa_tnc_error.h"
#include "tcg/seg/tcg_seg_attr_seg_env.h"
#include <utils/debug.h>
#include <bio/bio_reader.h>
#include <bio/bio_writer.h>
Classes
struct private_seg_env_t
Macros
#define BASE_ATTR_ID_PREFIX 0xFF
Typedefs
typedef struct private_seg_env_t private_seg_env_t
Functions
METHOD (seg_env_t, get_base_attr_id, uint32_t, private_seg_env_t *this)
METHOD (seg_env_t, get_base_attr, pa_tnc_attr_t *, private_seg_env_t *this)
METHOD (seg_env_t, get_base_attr_info, chunk_t, private_seg_env_t *this)
METHOD (seg_env_t, first_segment, pa_tnc_attr_t *, private_seg_env_t *this, size_t max_attr_len)
METHOD (seg_env_t, next_segment, pa_tnc_attr_t *, private_seg_env_t *this, bool *last)
METHOD (seg_env_t, add_segment, bool, private_seg_env_t *this, chunk_t segment, pa_tnc_attr_t **error)
METHOD (seg_env_t, destroy, void, private_seg_env_t *this)
seg_env_t * seg_env_create (uint32_t base_attr_id, pa_tnc_attr_t *base_attr, uint32_t max_seg_size)
seg_env_t * seg_env_create_from_data (uint32_t base_attr_id, chunk_t data, uint32_t max_seg_size, pa_tnc_attr_t **error)
Macro Definition Documentation
#define BASE_ATTR_ID_PREFIX 0xFF
Definition at line 27 of file seg_env.c.
Typedef Documentation
typedef struct private_seg_env_t private_seg_env_t
Definition at line 29 of file seg_env.c.
Function Documentation
METHOD (seg_env_t , get_base_attr_id , uint32_t , private_seg_env_t * this)
Definition at line 73 of file seg_env.c.
 {
     return this->base_attr_id;
 }
METHOD (seg_env_t , get_base_attr , pa_tnc_attr_t * , private_seg_env_t * this)
Definition at line 79 of file seg_env.c.
References base_attr.
 {
     return this->need_more ? NULL : this->base_attr->get_ref(this->base_attr);
 }
METHOD (seg_env_t , get_base_attr_info , chunk_t , private_seg_env_t * this)
Definition at line 85 of file seg_env.c.
References chunk_create().
 {
     return chunk_create(this->base_attr_info, 8);
 }
METHOD (seg_env_t , first_segment , pa_tnc_attr_t * , private_seg_env_t * this, size_t max_attr_len)
Definition at line 91 of file seg_env.c.
References base_attr, bio_writer_create(), chunk_free(), chunk_skip(), data, DBG2, DBG_TNC, bio_writer_t::destroy, bio_writer_t::extract_buf, flags, chunk_t::len, max_seg_size, min, PA_TNC_ATTR_FLAG_NONE, PA_TNC_ATTR_FLAG_NOSKIP, PA_TNC_ATTR_HEADER_SIZE, SEG_ENV_FLAG_MORE, SEG_ENV_FLAG_START, tcg_seg_attr_seg_env_create(), TCG_SEG_ATTR_SEG_ENV_HEADER, type, pen_type_t::type, value, pen_type_t::vendor_id, bio_writer_t::write_data, bio_writer_t::write_uint24, bio_writer_t::write_uint32, and bio_writer_t::write_uint8.
 {
     pa_tnc_attr_t *seg_env_attr;
     bio_writer_t *writer;
     pen_type_t type;
     chunk_t segment_data, value;
     size_t seg_size;
     uint8_t flags, seg_env_flags;
     /* compute size of first segment */
     seg_size = max_attr_len ? min(this->max_seg_size,
                                   max_attr_len - PA_TNC_ATTR_HEADER_SIZE
                                                - TCG_SEG_ATTR_SEG_ENV_HEADER)
                             : this->max_seg_size;
     /* get components of base attribute header and data */
     flags = this->base_attr->get_noskip_flag(this->base_attr) ?
                 PA_TNC_ATTR_FLAG_NOSKIP : PA_TNC_ATTR_FLAG_NONE;
     type = this->base_attr->get_type(this->base_attr);
     /* attribute data going into the first segment */
     segment_data = this->data;
     segment_data.len = seg_size - PA_TNC_ATTR_HEADER_SIZE;
     /* build encoding of the base attribute header and first segment data */
     writer = bio_writer_create(this->max_seg_size);
     writer->write_uint8 (writer, flags);
     writer->write_uint24(writer, type.vendor_id);
     writer->write_uint32(writer, type.type);
     writer->write_uint32(writer, PA_TNC_ATTR_HEADER_SIZE + this->data.len);
     writer->write_data  (writer, segment_data);
     value = writer->extract_buf(writer);
     writer->destroy(writer);
     this->data = chunk_skip(this->data, segment_data.len);
     DBG2(DBG_TNC, "creating first segment for base attribute ID %d (%d bytes)",
          this->base_attr_id, seg_size);
     seg_env_flags = SEG_ENV_FLAG_START | SEG_ENV_FLAG_MORE;
     seg_env_attr = tcg_seg_attr_seg_env_create(value, seg_env_flags,
                                                this->base_attr_id);
     chunk_free(&value);
     return seg_env_attr;
 }
METHOD (seg_env_t , next_segment , pa_tnc_attr_t * , private_seg_env_t * this, bool * last)
Definition at line 138 of file seg_env.c.
References chunk_skip(), data, DBG2, DBG_TNC, chunk_t::len, max_seg_size, min, SEG_ENV_FLAG_MORE, SEG_ENV_FLAG_NONE, and tcg_seg_attr_seg_env_create().
 {
     pa_tnc_attr_t *seg_env_attr;
     chunk_t segment_data;
     uint8_t seg_env_flags;
     bool is_last_segment;
     if (this->data.len == 0)
     {
         /* no more attribute data to segment available */
         return NULL;
     }
     /* attribute data going into the next segment */
     segment_data = this->data;
     segment_data.len = min(this->max_seg_size, this->data.len);
     this->data = chunk_skip(this->data, segment_data.len);
     is_last_segment = (this->data.len == 0);
     if (last)
     {
         *last = is_last_segment;
     }
     DBG2(DBG_TNC, "creating %s segment for base attribute ID %d (%d bytes)",
                    is_last_segment ? "last" : "next", this->base_attr_id,
                    segment_data.len);
     seg_env_flags = is_last_segment ? SEG_ENV_FLAG_NONE : SEG_ENV_FLAG_MORE;
     seg_env_attr = tcg_seg_attr_seg_env_create(segment_data, seg_env_flags,
                                                this->base_attr_id);
     return seg_env_attr;
 }
METHOD (seg_env_t , add_segment , bool , private_seg_env_t * this, chunk_t segment, pa_tnc_attr_t ** error)
Definition at line 173 of file seg_env.c.
References base_attr, error_code, FALSE, IETF_ATTR_PA_TNC_ERROR, ietf_attr_pa_tnc_error_create_with_offset(), NEED_MORE, PA_ERROR_INVALID_PARAMETER, PA_TNC_ATTR_HEADER_SIZE, PEN_IETF, pen_type_create(), status, SUCCESS, TRUE, type, pen_type_t::type, and pen_type_t::vendor_id.
 {
     pen_type_t type, error_code;
     uint32_t attr_offset;
     chunk_t msg_info;
     status_t status;
     this->base_attr->add_segment(this->base_attr, segment);
     status = this->base_attr->process(this->base_attr, &attr_offset);
     if (status != SUCCESS && status != NEED_MORE)
     {
         type = this->base_attr->get_type(this->base_attr);
         if (type.vendor_id == PEN_IETF && type.type == IETF_ATTR_PA_TNC_ERROR)
         {
             /* error while processing a PA-TNC error attribute - abort */
             return FALSE;
         }
         error_code = pen_type_create(PEN_IETF, PA_ERROR_INVALID_PARAMETER);
         msg_info = get_base_attr_info(this);
         *error = ietf_attr_pa_tnc_error_create_with_offset(error_code,
                     msg_info, PA_TNC_ATTR_HEADER_SIZE + attr_offset);
         return FALSE;
     }
     this->need_more = (status == NEED_MORE);
     return TRUE;
 }
METHOD (seg_env_t , destroy , void , private_seg_env_t * this)
Definition at line 203 of file seg_env.c.
References base_attr, DESTROY_IF, and free().
 {
     DESTROY_IF(this->base_attr);
     free(this);
 }