strongSwan: endpoint_notify
endpoint_notify
payloads
Classes
struct endpoint_notify_t
Macros
#define ME_PRIO_HOST 255
#define ME_PRIO_PEER 128
#define ME_PRIO_SERVER 64
#define ME_PRIO_RELAY 0
Typedefs
typedef enum me_endpoint_family_t me_endpoint_family_t
typedef enum me_endpoint_type_t me_endpoint_type_t
typedef struct endpoint_notify_t endpoint_notify_t
Enumerations
enum me_endpoint_family_t { NO_FAMILY = 0, IPv4 = 1, IPv6 = 2, MAX_FAMILY = 3 }
enum me_endpoint_type_t {
NO_TYPE = 0, HOST = 1, PEER_REFLEXIVE = 2, SERVER_REFLEXIVE = 3,
RELAYED = 4, MAX_TYPE = 5
}
Functions
endpoint_notify_t * endpoint_notify_create_from_host (me_endpoint_type_t type, host_t *host, host_t *base)
endpoint_notify_t * endpoint_notify_create_from_payload (notify_payload_t *notify)
Variables
enum_name_t * me_endpoint_type_names
Detailed Description
Macro Definition Documentation
#define ME_PRIO_HOST 255
Definition at line 24 of file endpoint_notify.h.
Referenced by endpoint_notify_create_from_host().
#define ME_PRIO_PEER 128
Definition at line 25 of file endpoint_notify.h.
Referenced by endpoint_notify_create_from_host().
#define ME_PRIO_RELAY 0
Definition at line 27 of file endpoint_notify.h.
Referenced by endpoint_notify_create_from_host().
#define ME_PRIO_SERVER 64
Definition at line 26 of file endpoint_notify.h.
Referenced by endpoint_notify_create_from_host().
Typedef Documentation
typedef struct endpoint_notify_t endpoint_notify_t
Definition at line 31 of file endpoint_notify.h.
typedef enum me_endpoint_family_t me_endpoint_family_t
Definition at line 29 of file endpoint_notify.h.
typedef enum me_endpoint_type_t me_endpoint_type_t
Definition at line 30 of file endpoint_notify.h.
Enumeration Type Documentation
enum me_endpoint_family_t
ME endpoint families.
Enumerator
NO_FAMILY
IPv4
IPv6
MAX_FAMILY
Definition at line 38 of file endpoint_notify.h.
{
     NO_FAMILY = 0,
     IPv4 = 1,
     IPv6 = 2,
     MAX_FAMILY = 3
 };
enum me_endpoint_type_t
ME endpoint types.
Enumerator
NO_TYPE
HOST
PEER_REFLEXIVE
SERVER_REFLEXIVE
RELAYED
MAX_TYPE
Definition at line 53 of file endpoint_notify.h.
{
     NO_TYPE = 0,
     HOST = 1,
     PEER_REFLEXIVE = 2,
     SERVER_REFLEXIVE = 3,
     RELAYED = 4,
     MAX_TYPE = 5
 };
Function Documentation
endpoint_notify_t* endpoint_notify_create_from_host (me_endpoint_type_t type, host_t * host, host_t * base)
Creates an endpoint_notify_t object from a host.
Parameters
type the endpoint type
host host to base the notify on (gets cloned)
base base of the endpoint, applies only to reflexive endpoints (gets cloned)
Returns
created endpoint_notify_t object
Described in header
Definition at line 336 of file endpoint_notify.c.
References host_t::clone, endpoint_notify_create(), family, host_t::get_family, HOST, IPv4, IPv6, ME_PRIO_HOST, ME_PRIO_PEER, ME_PRIO_RELAY, ME_PRIO_SERVER, PEER_REFLEXIVE, RELAYED, SERVER_REFLEXIVE, and type.
Referenced by gather_and_add_endpoints(), METHOD(), process_request(), process_response(), and sender().
 {
     private_endpoint_notify_t *this = endpoint_notify_create();
     this->type = type;
     switch(type)
     {
         case HOST:
             this->priority = pow(2, 16) * ME_PRIO_HOST;
             break;
         case PEER_REFLEXIVE:
             this->priority = pow(2, 16) * ME_PRIO_PEER;
             break;
         case SERVER_REFLEXIVE:
             this->priority = pow(2, 16) * ME_PRIO_SERVER;
             break;
         case RELAYED:
         default:
             this->priority = pow(2, 16) * ME_PRIO_RELAY;
             break;
     }
     /* FIXME: if there is more than one ip address we should vary this priority */
     this->priority += 65535;
     if (!host)
     {
         return &this->public;
     }
     switch(host->get_family(host))
     {
         case AF_INET:
             this->family = IPv4;
             break;
         case AF_INET6:
             this->family = IPv6;
             break;
         default:
             /* unsupported family type, we do not set the host
              * (family is set to NO_FAMILY) */
             return &this->public;
     }
     this->endpoint = host->clone(host);
     if (base)
     {
         this->base = base->clone(base);
     }
     return &this->public;
 }
endpoint_notify_t* endpoint_notify_create_from_payload (notify_payload_t * notify)
Creates an endpoint_notify_t object from a notify payload.
Parameters
notify the notify payload
Returns
- created endpoint_notify_t object
NULL if invalid payload
Described in header
Definition at line 394 of file endpoint_notify.c.
References data, destroy(), endpoint_notify_create(), notify_payload_t::get_notification_data, notify_payload_t::get_notify_type, ME_ENDPOINT, parse_notification_data(), and SUCCESS.
Referenced by process_payloads().
 {
     private_endpoint_notify_t *this;
     chunk_t data;
     if (notify->get_notify_type(notify) != ME_ENDPOINT)
     {
         return NULL;
     }
     this = endpoint_notify_create();
     data = notify->get_notification_data(notify);
     if (parse_notification_data(this, data) != SUCCESS)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
Variable Documentation
enum_name_t* me_endpoint_type_names
enum name for me_endpoint_type_t.
Referenced by process_payloads().