strongSwan: stroke_ca
stroke_ca
stroke
Classes
struct stroke_ca_t
Typedefs
typedef struct stroke_ca_t stroke_ca_t
Functions
stroke_ca_t * stroke_ca_create ()
Detailed Description
Typedef Documentation
typedef struct stroke_ca_t stroke_ca_t
Definition at line 28 of file stroke_ca.h.
Function Documentation
stroke_ca_t* stroke_ca_create ()
Create a stroke_ca instance.
Definition at line 716 of file stroke_ca.c.
References add(), del(), destroy(), INIT, linked_list_create(), list, nop(), return_null(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by stroke_socket_create().
 {
     private_stroke_ca_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_private_enumerator = (void*)return_null,
                 .create_cert_enumerator = _create_cert_enumerator,
                 .create_shared_enumerator = (void*)return_null,
                 .create_cdp_enumerator = _create_cdp_enumerator,
                 .cache_cert = (void*)nop,
             },
             .add = _add,
             .del = _del,
             .list = _list,
             .get_cert_ref = _get_cert_ref,
             .reload_certs = _reload_certs,
             .replace_certs = _replace_certs,
             .check_for_hash_and_url = _check_for_hash_and_url,
             .destroy = _destroy,
         },
         .sections = linked_list_create(),
         .certs = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return &this->public;
 }