strongSwan: eap_peap_server.c File Reference
eap_peap_server.c File Reference
#include "eap_peap_server.h"
#include "eap_peap_avp.h"
#include <utils/debug.h>
#include <daemon.h>
Classes
struct private_eap_peap_server_t
Typedefs
typedef struct
private_eap_peap_server_t private_eap_peap_server_t
Functions
static status_t start_phase2_auth (private_eap_peap_server_t *this)
static status_t start_phase2_tnc (private_eap_peap_server_t *this)
METHOD (tls_application_t, process, status_t, private_eap_peap_server_t *this, bio_reader_t *reader)
METHOD (tls_application_t, build, status_t, private_eap_peap_server_t *this, bio_writer_t *writer)
METHOD (tls_application_t, destroy, void, private_eap_peap_server_t *this)
eap_peap_server_t * eap_peap_server_create (identification_t *server, identification_t *peer, eap_method_t *eap_method)
Typedef Documentation
typedef struct private_eap_peap_server_t private_eap_peap_server_t
Definition at line 22 of file eap_peap_server.c.
Function Documentation
METHOD (tls_application_t , process , status_t , private_eap_peap_server_t * this, bio_reader_t * reader)
Definition at line 161 of file eap_peap_server.c.
References charon, chunk_empty, chunk_free(), code, eap_manager_t::create_instance, data, DBG1, DBG3, DBG_IKE, eap_payload_t::destroy, daemon_t::eap, eap_code_names, eap_code_short_names, EAP_FAILURE, EAP_IDENTITY, EAP_NAK, eap_payload_create_code(), eap_payload_create_data(), EAP_PEAP, EAP_REQUEST, EAP_RESPONSE, EAP_SERVER, EAP_SUCCESS, eap_type_names, eap_type_short_names, FAILED, FALSE, settings_t::get_bool, eap_payload_t::get_code, eap_payload_t::get_type, identification_create_from_data(), in, lib, NEED_MORE, library_t::ns, out, library_t::settings, start_phase2_auth(), start_phase2_tnc(), status, SUCCESS, type, and payload_t::verify.
 {
     chunk_t data = chunk_empty;
     status_t status;
     payload_t *payload;
     eap_payload_t *in;
     eap_code_t code;
     eap_type_t type = EAP_NAK, received_type;
     u_int32_t vendor, received_vendor;
     status = this->avp->process(this->avp, reader, &data,
                             this->ph1_method->get_identifier(this->ph1_method));
     switch (status)
     {
         case SUCCESS:
             break;
         case NEED_MORE:
             return NEED_MORE;
         case FAILED:
         default:
             return FAILED;
     }
     in = eap_payload_create_data(data);
     DBG3(DBG_IKE, "%B", &data);
     chunk_free(&data);
     payload = (payload_t*)in;
     if (payload->verify(payload) != SUCCESS)
     {
         in->destroy(in);
         return FAILED;
     }
     code = in->get_code(in);
     if (code == EAP_REQUEST || code == EAP_RESPONSE)
     {
         received_type = in->get_type(in, &received_vendor);
         DBG1(DBG_IKE, "received tunneled EAP-PEAP AVP [EAP/%N/%N]",
                                 eap_code_short_names, code,
                                 eap_type_short_names, received_type);
         if (code != EAP_RESPONSE)
         {
             DBG1(DBG_IKE, "%N expected", eap_code_names, EAP_RESPONSE);
             in->destroy(in);
             return FAILED;
         }
     }
     else
     {
         DBG1(DBG_IKE, "received tunneled EAP-PEAP AVP [EAP/%N]",
                                 eap_code_short_names, code);
         /* if EAP_SUCCESS check if to continue phase2 with EAP-TNC */
         return (this->phase2_result == EAP_SUCCESS && code == EAP_SUCCESS) ?
                start_phase2_tnc(this) : FAILED;
     }
     if (this->ph2_method)
     {
         type = this->ph2_method->get_type(this->ph2_method, &vendor);
         if (type != received_type || vendor != received_vendor)
         {
             if (received_vendor == 0 && received_type == EAP_NAK)
             {
                 DBG1(DBG_IKE, "peer does not support %N", eap_type_names, type);
             }
             else
             {
                 DBG1(DBG_IKE, "received invalid EAP response");
             }
             in->destroy(in);
             return FAILED;
         }
     }
     if (!received_vendor && received_type == EAP_IDENTITY)
     {
         chunk_t eap_id;
         if (this->ph2_method == NULL)
         {
             /* Received an EAP Identity response without a matching request */
             this->ph2_method = charon->eap->create_instance(charon->eap,
                                              EAP_IDENTITY, 0, EAP_SERVER,
                                              this->server, this->peer);
             if (this->ph2_method == NULL)
             {
                 DBG1(DBG_IKE, "%N method not available",
                                eap_type_names, EAP_IDENTITY);
                 return FAILED;
             }
         }
         if (this->ph2_method->process(this->ph2_method, in, &this->out) != SUCCESS)
         {
             DBG1(DBG_IKE, "%N method failed", eap_type_names, EAP_IDENTITY);
             return FAILED;
         }
         if (this->ph2_method->get_msk(this->ph2_method, &eap_id) == SUCCESS)
         {
             this->peer->destroy(this->peer);
             this->peer = identification_create_from_data(eap_id);
             DBG1(DBG_IKE, "received EAP identity '%Y'", this->peer);
         }
         in->destroy(in);
         this->ph2_method->destroy(this->ph2_method);
         this->ph2_method = NULL;
         /* Start Phase 2 of EAP-PEAP authentication */
         if (lib->settings->get_bool(lib->settings,
                     "%s.plugins.eap-peap.request_peer_auth", FALSE, lib->ns))
         {
             return start_phase2_tnc(this);
         }
         else
         {
             return start_phase2_auth(this);
         }
     }
     if (this->ph2_method == 0)
     {
         DBG1(DBG_IKE, "no %N phase2 method installed", eap_type_names, EAP_PEAP);
         in->destroy(in);
         return FAILED;
     }
     status = this->ph2_method->process(this->ph2_method, in, &this->out);
     in->destroy(in);
     switch (status)
     {
         case SUCCESS:
             DBG1(DBG_IKE, "%N phase2 authentication of '%Y' with %N successful",
                             eap_type_names, EAP_PEAP, this->peer,
                             eap_type_names, type);
             this->ph2_method->destroy(this->ph2_method);
             this->ph2_method = NULL;
             /* EAP-PEAP requires the sending of an inner EAP_SUCCESS message */
             this->phase2_result = EAP_SUCCESS;
             this->out = eap_payload_create_code(this->phase2_result, 1 +
                             this->ph1_method->get_identifier(this->ph1_method));
             return NEED_MORE;
         case NEED_MORE:
             break;
         case FAILED:
         default:
             if (vendor)
             {
                 DBG1(DBG_IKE, "vendor specific EAP method %d-%d failed",
                                type, vendor);
             }
             else
             {
                 DBG1(DBG_IKE, "%N method failed", eap_type_names, type);
             }
             /* EAP-PEAP requires the sending of an inner EAP_FAILURE message */
             this->phase2_result = EAP_FAILURE;
             this->out = eap_payload_create_code(this->phase2_result, 1 +
                             this->ph1_method->get_identifier(this->ph1_method));
             return NEED_MORE;
     }
     return status;
 }
METHOD (tls_application_t , build , status_t , private_eap_peap_server_t * this, bio_writer_t * writer)
Definition at line 333 of file eap_peap_server.c.
References charon, code, eap_manager_t::create_instance, data, DBG1, DBG3, DBG_IKE, daemon_t::eap, eap_code_short_names, EAP_IDENTITY, EAP_REQUEST, EAP_RESPONSE, EAP_SERVER, eap_type_names, eap_type_short_names, FAILED, FALSE, INVALID_STATE, out, TRUE, and type.
 {
     chunk_t data;
     eap_code_t code;
     eap_type_t type;
     u_int32_t vendor;
     if (this->ph2_method == NULL && this->start_phase2 && this->start_phase2_id)
     {
         /*
          * Start Phase 2 with an EAP Identity request either piggybacked right
          * onto the TLS Finished payload or delayed after the reception of an
          * empty EAP Acknowledge message.
          */
         this->ph2_method = charon->eap->create_instance(charon->eap, EAP_IDENTITY,
                                  0, EAP_SERVER, this->server, this->peer);
         if (this->ph2_method == NULL)
         {
             DBG1(DBG_IKE, "%N method not available",
                  eap_type_names, EAP_IDENTITY);
             return FAILED;
         }
         /* synchronize EAP message identifiers of inner protocol with outer */
         this->ph2_method->set_identifier(this->ph2_method,
                     this->ph1_method->get_identifier(this->ph1_method));
         this->ph2_method->initiate(this->ph2_method, &this->out);
         this->start_phase2 = FALSE;
     }
     this->start_phase2_id = TRUE;
     if (this->out)
     {
         code = this->out->get_code(this->out);
         type = this->out->get_type(this->out, &vendor);
         if (code == EAP_REQUEST || code == EAP_RESPONSE)
         {
             DBG1(DBG_IKE, "sending tunneled EAP-PEAP AVP [EAP/%N/%N]",
                  eap_code_short_names, code, eap_type_short_names, type);
         }
         else
         {
             DBG1(DBG_IKE, "sending tunneled EAP-PEAP AVP [EAP/%N]",
                  eap_code_short_names, code);
         }
         /* get the raw EAP message data */
         data = this->out->get_data(this->out);
         DBG3(DBG_IKE, "%B", &data);
         this->avp->build(this->avp, writer, data);
         this->out->destroy(this->out);
         this->out = NULL;
     }
     return INVALID_STATE;
 }
METHOD (tls_application_t , destroy , void , private_eap_peap_server_t * this)
Definition at line 393 of file eap_peap_server.c.
References DESTROY_IF, free(), out, and server.
 {
     this->server->destroy(this->server);
     this->peer->destroy(this->peer);
     DESTROY_IF(this->ph2_method);
     DESTROY_IF(this->out);
     this->avp->destroy(this->avp);
     free(this);
 }
static status_t start_phase2_auth (private_eap_peap_server_t * this) static
Start EAP client authentication protocol
Definition at line 88 of file eap_peap_server.c.
References charon, eap_manager_t::create_instance, DBG1, DBG_IKE, daemon_t::eap, EAP_SERVER, eap_type_from_string(), eap_type_names, FAILED, settings_t::get_str, lib, NEED_MORE, library_t::ns, library_t::settings, and type.
Referenced by METHOD().
 {
     char *eap_type_str;
     eap_type_t type;
     eap_type_str = lib->settings->get_str(lib->settings,
                             "%s.plugins.eap-peap.phase2_method", "mschapv2",
                             lib->ns);
     type = eap_type_from_string(eap_type_str);
     if (type == 0)
     {
         DBG1(DBG_IKE, "unrecognized phase2 method \"%s\"", eap_type_str);
         return FAILED;
     }
     DBG1(DBG_IKE, "phase2 method %N selected", eap_type_names, type);
         this->ph2_method = charon->eap->create_instance(charon->eap, type, 0,
                                 EAP_SERVER, this->server, this->peer);
     if (this->ph2_method == NULL)
     {
         DBG1(DBG_IKE, "%N method not available", eap_type_names, type);
         return FAILED;
     }
     /* synchronize EAP message identifiers of inner protocol with outer */
     this->ph2_method->set_identifier(this->ph2_method,
                         this->ph1_method->get_identifier(this->ph1_method) + 1);
     if (this->ph2_method->initiate(this->ph2_method, &this->out) == NEED_MORE)
     {
         return NEED_MORE;
     }
     else
     {
         DBG1(DBG_IKE, "%N method failed", eap_type_names, type);
             return FAILED;
     }
 }
static status_t start_phase2_tnc (private_eap_peap_server_t * this) static
If configured, start EAP-TNC protocol
Definition at line 129 of file eap_peap_server.c.
References charon, eap_manager_t::create_instance, DBG1, DBG_IKE, daemon_t::eap, EAP_SERVER, EAP_TNC, eap_type_names, FAILED, FALSE, settings_t::get_bool, lib, NEED_MORE, library_t::ns, library_t::settings, and SUCCESS.
Referenced by METHOD().
 {
     if (this->start_phase2_tnc && lib->settings->get_bool(lib->settings,
                         "%s.plugins.eap-peap.phase2_tnc", FALSE, lib->ns))
     {
         DBG1(DBG_IKE, "phase2 method %N selected", eap_type_names, EAP_TNC);
         this->ph2_method = charon->eap->create_instance(charon->eap, EAP_TNC,
                                     0, EAP_SERVER, this->server, this->peer);
         if (this->ph2_method == NULL)
         {
             DBG1(DBG_IKE, "%N method not available", eap_type_names, EAP_TNC);
             return FAILED;
         }
         this->start_phase2_tnc = FALSE;
         /* synchronize EAP message identifiers of inner protocol with outer */
         this->ph2_method->set_identifier(this->ph2_method,
                         this->ph1_method->get_identifier(this->ph1_method) + 1);
         if (this->ph2_method->initiate(this->ph2_method, &this->out) == NEED_MORE)
         {
             return NEED_MORE;
         }
         else
         {
             DBG1(DBG_IKE, "%N method failed", eap_type_names, EAP_TNC);
             return FAILED;
         }
     }
     return SUCCESS;
 }