strongSwan: tnc_imc
tnc_imc
tnc_imc
Functions
imc_t * tnc_imc_create (char *name, char *filename)
imc_t * tnc_imc_create_from_functions (char *name, TNC_IMC_InitializePointer initialize, TNC_IMC_NotifyConnectionChangePointer notify_connection_change, TNC_IMC_BeginHandshakePointer begin_handshake, TNC_IMC_ReceiveMessagePointer receive_message, TNC_IMC_ReceiveMessageLongPointer receive_message_long, TNC_IMC_BatchEndingPointer batch_ending, TNC_IMC_TerminatePointer terminate, TNC_IMC_ProvideBindFunctionPointer provide_bind_function)
Detailed Description
Function Documentation
imc_t* tnc_imc_create (char * name, char * path)
Create an Integrity Measurement Collector loaded from a library.
Parameters
name name of the IMC
filename path to the dynamic IMC library
Returns
instance of the imc_t interface
See header
Definition at line 349 of file tnc_imc.c.
References DBG1, DBG_TNC, destroy(), dlerror(), dlopen(), dlsym(), FALSE, settings_t::get_bool, handle, initialize(), lib, library_t::ns, RTLD_LAZY, RTLD_NOW, library_t::settings, and tnc_imc_create_empty().
Referenced by METHOD().
 {
     private_tnc_imc_t *this;
     int flag = RTLD_LAZY;
     this = tnc_imc_create_empty(name);
     if (lib->settings->get_bool(lib->settings, "%s.dlopen_use_rtld_now",
                                 lib->ns, FALSE))
     {
         flag = RTLD_NOW;
     }
     this->handle = dlopen(path, flag);
     if (!this->handle)
     {
         DBG1(DBG_TNC, "IMC \"%s\" failed to load: %s", name, dlerror());
         destroy(this);
         return NULL;
     }
     this->public.initialize = dlsym(this->handle, "TNC_IMC_Initialize");
     if (!this->public.initialize)
     {
         DBG1(DBG_TNC, "could not resolve TNC_IMC_Initialize in %s: %s\n",
                        path, dlerror());
         destroy(this);
         return NULL;
     }
     this->public.notify_connection_change =
                          dlsym(this->handle, "TNC_IMC_NotifyConnectionChange");
     this->public.begin_handshake = dlsym(this->handle, "TNC_IMC_BeginHandshake");
     if (!this->public.begin_handshake)
     {
         DBG1(DBG_TNC, "could not resolve TNC_IMC_BeginHandshake in %s: %s\n",
                        path, dlerror());
         destroy(this);
         return NULL;
     }
     this->public.receive_message =
                         dlsym(this->handle, "TNC_IMC_ReceiveMessage");
     this->public.receive_message_long =
                         dlsym(this->handle, "TNC_IMC_ReceiveMessageLong");
     this->public.batch_ending =
                         dlsym(this->handle, "TNC_IMC_BatchEnding");
     this->public.terminate =
                         dlsym(this->handle, "TNC_IMC_Terminate");
     this->public.provide_bind_function =
                         dlsym(this->handle, "TNC_IMC_ProvideBindFunction");
     if (!this->public.provide_bind_function)
     {
         DBG1(DBG_TNC, "could not resolve TNC_IMC_ProvideBindFunction in %s: %s\n",
                       path, dlerror());
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
imc_t* tnc_imc_create_from_functions (char * name, TNC_IMC_InitializePointer initialize, TNC_IMC_NotifyConnectionChangePointer notify_connection_change, TNC_IMC_BeginHandshakePointer begin_handshake, TNC_IMC_ReceiveMessagePointer receive_message, TNC_IMC_ReceiveMessageLongPointer receive_message_long, TNC_IMC_BatchEndingPointer batch_ending, TNC_IMC_TerminatePointer terminate, TNC_IMC_ProvideBindFunctionPointer provide_bind_function)
Create an Integrity Measurement Collector from a set of IMC functions.
Parameters
name name of the IMC
initialize TNC_IMC_InitializePointer
notify_connection_change TNC_IMC_NotifyConnectionChangePointer
begin_handshake TNC_IMC_BeginHandshakePointer
receive_message TNC_IMC_ReceiveMessagePointer
receive_message_long TNC_IMC_ReceiveMessageLongPointer
batch_ending TNC_IMC_BatchEndingPointer
terminate TNC_IMC_TerminatePointer
provide_bind_function TNC_IMC_ProvideBindFunctionPointer
Returns
instance of the imc_t interface
See header
Definition at line 411 of file tnc_imc.c.
References initialize(), receive_message(), terminate(), and tnc_imc_create_empty().
Referenced by METHOD().
 {
     private_tnc_imc_t *this;
     this = tnc_imc_create_empty(name);
     this->public.initialize = initialize;
     this->public.notify_connection_change = notify_connection_change;
     this->public.begin_handshake = begin_handshake;
     this->public.receive_message = receive_message;
     this->public.receive_message_long = receive_message_long;
     this->public.batch_ending = batch_ending;
     this->public.terminate = terminate;
     this->public.provide_bind_function = provide_bind_function;
     return &this->public;
 }