strongSwan: openssl_diffie_hellman
openssl_diffie_hellman
openssl
Classes
struct openssl_diffie_hellman_t
Typedefs
typedef struct
openssl_diffie_hellman_t openssl_diffie_hellman_t
Functions
openssl_diffie_hellman_t * openssl_diffie_hellman_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Detailed Description
Typedef Documentation
typedef struct openssl_diffie_hellman_t openssl_diffie_hellman_t
Definition at line 24 of file openssl_diffie_hellman.h.
Function Documentation
openssl_diffie_hellman_t* openssl_diffie_hellman_create (diffie_hellman_group_t group, chunk_t g, chunk_t p)
Creates a new openssl_diffie_hellman_t object.
Parameters
group Diffie Hellman group number to use
g custom generator, if MODP_CUSTOM
p custom prime, if MODP_CUSTOM
Returns
openssl_diffie_hellman_t object, NULL if not supported
Definition at line 165 of file openssl_diffie_hellman.c.
References chunk_empty, DBG2, DBG_LIB, destroy(), dh, FALSE, free(), group, INIT, chunk_t::len, MODP_CUSTOM, chunk_t::ptr, set_modulus(), and SUCCESS.
Referenced by METHOD().
 {
     private_openssl_diffie_hellman_t *this;
     INIT(this,
         .public = {
             .dh = {
                 .get_shared_secret = _get_shared_secret,
                 .set_other_public_value = _set_other_public_value,
                 .get_my_public_value = _get_my_public_value,
                 .set_private_value = _set_private_value,
                 .get_dh_group = _get_dh_group,
                 .destroy = _destroy,
             },
         },
     );
     this->dh = DH_new();
     if (!this->dh)
     {
         free(this);
         return NULL;
     }
     this->group = group;
     this->computed = FALSE;
     this->pub_key = BN_new();
     this->shared_secret = chunk_empty;
     if (group == MODP_CUSTOM)
     {
         this->dh->p = BN_bin2bn(p.ptr, p.len, NULL);
         this->dh->g = BN_bin2bn(g.ptr, g.len, NULL);
     }
     else
     {
         /* find a modulus according to group */
         if (set_modulus(this) != SUCCESS)
         {
             destroy(this);
             return NULL;
         }
     }
     /* generate my public and private values */
     if (!DH_generate_key(this->dh))
     {
         destroy(this);
         return NULL;
     }
     DBG2(DBG_LIB, "size of DH secret exponent: %d bits",
          BN_num_bits(this->dh->priv_key));
     return &this->public;
 }