strongSwan: rc2_crypter.c File Reference
rc2_crypter.c File Reference
#include "rc2_crypter.h"
Classes
struct private_rc2_crypter_t
Macros
#define RC2_BLOCK_SIZE 8
#define ROL16(x, k) ({ u_int16_t _x = (x); (_x << (k)) | (_x >> (16 - (k))); })
#define ROR16(x, k) ({ u_int16_t _x = (x); (_x >> (k)) | (_x << (16 - (k))); })
#define GET16(x) ({ u_char *_x = (x); (u_int16_t)_x[0] | ((u_int16_t)_x[1] << 8); })
#define PUT16(x, v) ({ u_char *_x = (x); u_int16_t _v = (v); _x[0] = _v, _x[1] = _v >> 8; })
Typedefs
typedef struct
private_rc2_crypter_t private_rc2_crypter_t
Functions
static void encrypt_block (private_rc2_crypter_t *this, u_char R[])
static void decrypt_block (private_rc2_crypter_t *this, u_char R[])
METHOD (crypter_t, decrypt, bool, private_rc2_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *decrypted)
METHOD (crypter_t, encrypt, bool, private_rc2_crypter_t *this, chunk_t data, chunk_t iv, chunk_t *encrypted)
METHOD (crypter_t, get_block_size, size_t, private_rc2_crypter_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_rc2_crypter_t *this)
METHOD (crypter_t, get_key_size, size_t, private_rc2_crypter_t *this)
METHOD (crypter_t, set_key, bool, private_rc2_crypter_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_rc2_crypter_t *this)
rc2_crypter_t * rc2_crypter_create (encryption_algorithm_t algo, size_t key_size)
Variables
static const u_char PITABLE [256]
Macro Definition Documentation
#define GET16 (x) ({ u_char *_x = (x); (u_int16_t)_x[0] | ((u_int16_t)_x[1] << 8); })
Definition at line 25 of file rc2_crypter.c.
Referenced by decrypt_block(), encrypt_block(), and METHOD().
#define PUT16 (x, v) ({ u_char *_x = (x); u_int16_t _v = (v); _x[0] = _v, _x[1] = _v >> 8; })
Definition at line 26 of file rc2_crypter.c.
Referenced by decrypt_block(), and encrypt_block().
#define RC2_BLOCK_SIZE 8
Definition at line 20 of file rc2_crypter.c.
Referenced by METHOD().
#define ROL16 (x, k) ({ u_int16_t _x = (x); (_x << (k)) | (_x >> (16 - (k))); })
Definition at line 22 of file rc2_crypter.c.
Referenced by encrypt_block().
#define ROR16 (x, k) ({ u_int16_t _x = (x); (_x >> (k)) | (_x << (16 - (k))); })
Definition at line 23 of file rc2_crypter.c.
Referenced by decrypt_block().
Typedef Documentation
typedef struct private_rc2_crypter_t private_rc2_crypter_t
Definition at line 18 of file rc2_crypter.c.
Function Documentation
static void decrypt_block (private_rc2_crypter_t * this, u_char R[]) static
Decrypt a single block of data.
Definition at line 140 of file rc2_crypter.c.
References GET16, PUT16, R0, R1, R2, R3, ROR16, and TRUE.
Referenced by METHOD().
 {
     register u_int16_t R0, R1, R2, R3, *Kj;
     int rounds = 3, mix = 5;
     R0 = GET16(R);
     R1 = GET16(R + 2);
     R2 = GET16(R + 4);
     R3 = GET16(R + 6);
     Kj = &this->K[63];
     /* 5 r-mix, r-mash, 6 r-mix, r-mash, 5 r-mix */
     while (TRUE)
     {
         /* r-mix */
         R3 = ROR16(R3, 5);
         R3 = R3 - *(Kj--) - (R2 & R1) - (~R2 & R0);
         R2 = ROR16(R2, 3);
         R2 = R2 - *(Kj--) - (R1 & R0) - (~R1 & R3);
         R1 = ROR16(R1, 2);
         R1 = R1 - *(Kj--) - (R0 & R3) - (~R0 & R2);
         R0 = ROR16(R0, 1);
         R0 = R0 - *(Kj--) - (R3 & R2) - (~R3 & R1);
         if (--mix == 0)
         {
             if (--rounds == 0)
             {
                 break;
             }
             mix = (rounds == 2) ? 6 : 5;
             /* r-mash */
             R3 -= this->K[R2 & 63];
             R2 -= this->K[R1 & 63];
             R1 -= this->K[R0 & 63];
             R0 -= this->K[R3 & 63];
         }
     }
     PUT16(R, R0);
     PUT16(R + 2, R1);
     PUT16(R + 4, R2);
     PUT16(R + 6, R3);
 }
static void encrypt_block (private_rc2_crypter_t * this, u_char R[]) static
Encrypt a single block of data
Definition at line 96 of file rc2_crypter.c.
References GET16, PUT16, R0, R1, R2, R3, ROL16, and TRUE.
Referenced by METHOD().
 {
     register u_int16_t R0, R1, R2, R3, *Kj;
     int rounds = 3, mix = 5;
     R0 = GET16(R);
     R1 = GET16(R + 2);
     R2 = GET16(R + 4);
     R3 = GET16(R + 6);
     Kj = &this->K[0];
     /* 5 mix, mash, 6 mix, mash, 5 mix */
     while (TRUE)
     {
         /* mix */
         R0 = ROL16(R0 + *(Kj++) + (R3 & R2) + (~R3 & R1), 1);
         R1 = ROL16(R1 + *(Kj++) + (R0 & R3) + (~R0 & R2), 2);
         R2 = ROL16(R2 + *(Kj++) + (R1 & R0) + (~R1 & R3), 3);
         R3 = ROL16(R3 + *(Kj++) + (R2 & R1) + (~R2 & R0), 5);
         if (--mix == 0)
         {
             if (--rounds == 0)
             {
                 break;
             }
             mix = (rounds == 2) ? 6 : 5;
             /* mash */
             R0 += this->K[R3 & 63];
             R1 += this->K[R0 & 63];
             R2 += this->K[R1 & 63];
             R3 += this->K[R2 & 63];
         }
     }
     PUT16(R, R0);
     PUT16(R + 2, R1);
     PUT16(R + 4, R2);
     PUT16(R + 6, R3);
 }
METHOD (crypter_t , decrypt , bool , private_rc2_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * decrypted)
Definition at line 185 of file rc2_crypter.c.
References chunk_alloc, decrypt_block(), FALSE, in, chunk_t::len, memcpy, memxor(), out, chunk_t::ptr, RC2_BLOCK_SIZE, and TRUE.
 {
     u_int8_t *in, *out, *prev;
     if (data.len % RC2_BLOCK_SIZE || iv.len != RC2_BLOCK_SIZE)
     {
         return FALSE;
     }
     in = data.ptr + data.len - RC2_BLOCK_SIZE;
     out = data.ptr;
     if (decrypted)
     {
         *decrypted = chunk_alloc(data.len);
         out = decrypted->ptr;
     }
     out += data.len - RC2_BLOCK_SIZE;
     prev = in;
     for (; in >= data.ptr; in -= RC2_BLOCK_SIZE, out -= RC2_BLOCK_SIZE)
     {
         if (decrypted)
         {
             memcpy(out, in, RC2_BLOCK_SIZE);
         }
         decrypt_block(this, out);
         prev -= RC2_BLOCK_SIZE;
         if (prev < data.ptr)
         {
             prev = iv.ptr;
         }
         memxor(out, prev, RC2_BLOCK_SIZE);
     }
     return TRUE;
 }
METHOD (crypter_t , encrypt , bool , private_rc2_crypter_t * this, chunk_t data, chunk_t iv, chunk_t * encrypted)
Definition at line 222 of file rc2_crypter.c.
References chunk_alloc, encrypt_block(), end, FALSE, in, chunk_t::len, memcpy, memxor(), out, chunk_t::ptr, RC2_BLOCK_SIZE, and TRUE.
 {
     u_int8_t *in, *out, *end, *prev;
     if (data.len % RC2_BLOCK_SIZE || iv.len != RC2_BLOCK_SIZE)
     {
         return FALSE;
     }
     in = data.ptr;
     end = data.ptr + data.len;
     out = data.ptr;
     if (encrypted)
     {
         *encrypted = chunk_alloc(data.len);
         out = encrypted->ptr;
     }
     prev = iv.ptr;
     for (; in < end; in += RC2_BLOCK_SIZE, out += RC2_BLOCK_SIZE)
     {
         if (encrypted)
         {
             memcpy(out, in, RC2_BLOCK_SIZE);
         }
         memxor(out, prev, RC2_BLOCK_SIZE);
         encrypt_block(this, out);
         prev = out;
     }
     return TRUE;
 }
METHOD (crypter_t , get_block_size , size_t , private_rc2_crypter_t * this)
Definition at line 255 of file rc2_crypter.c.
References RC2_BLOCK_SIZE.
 {
     return RC2_BLOCK_SIZE;
 }
METHOD (crypter_t , get_iv_size , size_t , private_rc2_crypter_t * this)
Definition at line 261 of file rc2_crypter.c.
References RC2_BLOCK_SIZE.
 {
     return RC2_BLOCK_SIZE;
 }
METHOD (crypter_t , get_key_size , size_t , private_rc2_crypter_t * this)
Definition at line 267 of file rc2_crypter.c.
 {
     return this->T;
 }
METHOD (crypter_t , set_key , bool , private_rc2_crypter_t * this, chunk_t key)
Definition at line 273 of file rc2_crypter.c.
References FALSE, GET16, chunk_t::len, memwipe(), PITABLE, chunk_t::ptr, and TRUE.
 {
     u_int8_t L[128], T8, TM, idx;
     int i;
     if (key.len != this->T)
     {
         return FALSE;
     }
     for (i = 0; i < key.len; i++)
     {
         L[i] = key.ptr[i];
     }
     for (; i < 128; i++)
     {
         idx = L[i-1] + L[i-key.len];
         L[i] = PITABLE[idx];
     }
     T8 = (this->T1 + 7) / 8;
     TM = ~(0xff << (8 - (8*T8 - this->T1)));
     L[128-T8] = PITABLE[L[128-T8] & TM];
     for (i = 127-T8; i >= 0; i--)
     {
         idx = L[i+1] ^ L[i+T8];
         L[i] = PITABLE[idx];
     }
     for (i = 0; i < 64; i++)
     {
         this->K[i] = GET16(&L[i << 1]);
     }
     memwipe(L, sizeof(L));
     return TRUE;
 }
METHOD (crypter_t , destroy , void , private_rc2_crypter_t * this)
Definition at line 308 of file rc2_crypter.c.
References free(), and memwipe().
 {
     memwipe(this->K, sizeof(this->K));
     free(this);
 }
Variable Documentation
const u_char PITABLE[256] static
PITABLE
Definition at line 57 of file rc2_crypter.c.
Referenced by METHOD().