strongSwan: thread_value.c File Reference
windows/thread_value.c File Reference
#include "thread.h"
#include <threading/thread_value.h>
Classes
struct private_thread_value_t
struct entry_t
Typedefs
typedef struct
private_thread_value_t private_thread_value_t
Functions
void thread_tls_cleanup (void *value)
METHOD (thread_value_t, tls_set, void, private_thread_value_t *this, void *val)
METHOD (thread_value_t, tls_get, void *, private_thread_value_t *this)
METHOD (thread_value_t, tls_destroy, void, private_thread_value_t *this)
METHOD (thread_value_t, tls_set_index, void, private_thread_value_t *this, void *val)
METHOD (thread_value_t, tls_get_index, void *, private_thread_value_t *this)
METHOD (thread_value_t, tls_destroy_index, void, private_thread_value_t *this)
thread_value_t * thread_value_create (thread_cleanup_t cleanup)
Typedef Documentation
typedef struct private_thread_value_t private_thread_value_t
Definition at line 21 of file windows/thread_value.c.
Function Documentation
METHOD (thread_value_t , tls_set , void , private_thread_value_t * this, void * val)
Definition at line 71 of file windows/thread_value.c.
References cleanup, free(), INIT, thread_tls_put(), thread_tls_remove(), and value.
 {
     entry_t *entry;
     if (val)
     {
         INIT(entry,
             .cleanup = this->cleanup,
             .value = val,
         );
         free(thread_tls_put(this, entry));
     }
     else
     {
         free(thread_tls_remove(this));
     }
 }
METHOD (thread_value_t , tls_get , void * , private_thread_value_t * this)
Definition at line 91 of file windows/thread_value.c.
References thread_tls_get(), and entry_t::value.
 {
     entry_t *entry;
     entry = thread_tls_get(this);
     if (entry)
     {
         return entry->value;
     }
     return NULL;
 }
METHOD (thread_value_t , tls_destroy , void , private_thread_value_t * this)
Definition at line 104 of file windows/thread_value.c.
References free(), thread_tls_cleanup(), and thread_tls_remove().
 {
     entry_t *entry;
     entry = thread_tls_remove(this);
     if (entry)
     {
         thread_tls_cleanup(entry);
     }
     free(this);
 }
METHOD (thread_value_t , tls_set_index , void , private_thread_value_t * this, void * val)
Definition at line 117 of file windows/thread_value.c.
 {
     TlsSetValue(this->index, val);
 }
METHOD (thread_value_t , tls_get_index , void * , private_thread_value_t * this)
Definition at line 123 of file windows/thread_value.c.
 {
     return TlsGetValue(this->index);
 }
METHOD (thread_value_t , tls_destroy_index , void , private_thread_value_t * this)
Definition at line 129 of file windows/thread_value.c.
References free().
 {
     TlsFree(this->index);
     free(this);
 }