strongSwan: test_bliss_sampler.c File Reference
test_bliss_sampler.c File Reference
#include "test_suite.h"
#include <bliss_sampler.h>
Functions
START_TEST (test_bliss_sampler_gaussian)
END_TEST Suite * bliss_sampler_suite_create ()
Variables
static u_int key_size [] = { 1, 3, 4}
Function Documentation
END_TEST Suite* bliss_sampler_suite_create ()
Definition at line 84 of file test_bliss_sampler.c.
References countof, key_size, s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, tcase_create, and tcase_set_timeout.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("bliss_sampler");
     tc = tcase_create("sampler_gaussian");
     tcase_set_timeout(tc, 10);
     tcase_add_loop_test(tc, test_bliss_sampler_gaussian, 0, countof(key_size));
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_bliss_sampler_gaussian)
Definition at line 22 of file test_bliss_sampler.c.
References alg, bliss_param_set_get_by_id(), bliss_sampler_create(), chunk_alloc, ck_assert, count, DBG1, DBG_LIB, bliss_sampler_t::destroy, free(), bliss_sampler_t::gaussian, HASH_SHA256, key_size, memset, chunk_t::ptr, and sign().
 {
     bliss_sampler_t *sampler;
     bliss_param_set_t *set;
     int i, k, count;
     uint32_t hist[8], sign[3];
     int32_t z;
     hash_algorithm_t alg;
     size_t seed_len;
     chunk_t seed;
     set = bliss_param_set_get_by_id(key_size[_i]);
     alg = HASH_SHA256;
     seed_len = 32;
     count = 10000000;
     seed = chunk_alloc(seed_len);
     memset(seed.ptr, 0xcc, seed_len);
     for (k = 0; k < 3; k++)
     {
         sign[k] = 0;
     }
     for (k = 0; k < 8; k++)
     {
         hist[k] = 0;
     }
     sampler = bliss_sampler_create(alg, seed, set);
     for (i = 0; i < count; i++)
     {
         ck_assert(sampler->gaussian(sampler, &z));
         if (z == 0)
         {
             sign[1]++;
             hist[0]++;
         }
         else if (z > 0)
         {
             sign[2]++;
             hist[z/256]++;
         }
         else
         {
             sign[0]++;
             hist[(-z)/256]++;
         }
     }
     sampler->destroy(sampler);
     free(seed.ptr);
     DBG1(DBG_LIB, "histogram");
     for (k = 0; k < 8; k++)
     {
         DBG1(DBG_LIB, "%d %7d", k, hist[k]);
     }
     DBG1(DBG_LIB, "- %7d", sign[0]);
     DBG1(DBG_LIB, "0 %7d", sign[1]);
     DBG1(DBG_LIB, "+ %7d", sign[2]);
 }
Variable Documentation
u_int key_size[] = { 1, 3, 4} static
Definition at line 20 of file test_bliss_sampler.c.
Referenced by bliss_sampler_suite_create(), and START_TEST().