strongSwan: tls_aead_null.c File Reference
tls_aead_null.c File Reference
#include "tls_aead.h"
Classes
struct private_tls_aead_t
Typedefs
typedef struct private_tls_aead_t private_tls_aead_t
Functions
struct __attribute__ ((__packed__))
METHOD (tls_aead_t, encrypt, bool, private_tls_aead_t *this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t *data)
METHOD (tls_aead_t, decrypt, bool, private_tls_aead_t *this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t *data)
METHOD (tls_aead_t, get_mac_key_size, size_t, private_tls_aead_t *this)
METHOD (tls_aead_t, get_encr_key_size, size_t, private_tls_aead_t *this)
METHOD (tls_aead_t, get_iv_size, size_t, private_tls_aead_t *this)
METHOD (tls_aead_t, set_keys, bool, private_tls_aead_t *this, chunk_t mac, chunk_t encr, chunk_t iv)
METHOD (tls_aead_t, destroy, void, private_tls_aead_t *this)
tls_aead_t * tls_aead_create_null (integrity_algorithm_t alg)
Variables
sigheader_t
Typedef Documentation
typedef struct private_tls_aead_t private_tls_aead_t
Definition at line 18 of file tls_aead_null.c.
Function Documentation
METHOD (tls_aead_t , encrypt , bool , private_tls_aead_t * this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t * data)
Definition at line 46 of file tls_aead_null.c.
References chunk_cat, chunk_from_thing, FALSE, htoun16(), htoun64(), chunk_t::len, sigheader_t, signer, TRUE, and type.
 {
     chunk_t assoc, mac;
     sigheader_t hdr;
     hdr.type = type;
     htoun64(&hdr.seq, seq);
     htoun16(&hdr.version, version);
     htoun16(&hdr.length, data->len);
     assoc = chunk_from_thing(hdr);
     if (!this->signer->get_signature(this->signer, assoc, NULL) ||
         !this->signer->allocate_signature(this->signer, *data, &mac))
     {
         return FALSE;
     }
     *data = chunk_cat("mm", *data, mac);
     return TRUE;
 }
METHOD (tls_aead_t , decrypt , bool , private_tls_aead_t * this, tls_version_t version, tls_content_type_t type, u_int64_t seq, chunk_t * data)
Definition at line 68 of file tls_aead_null.c.
References chunk_from_thing, chunk_skip(), FALSE, htoun16(), htoun64(), chunk_t::len, sigheader_t, signer, TRUE, and type.
 {
     chunk_t assoc, mac;
     sigheader_t hdr;
     mac.len = this->signer->get_block_size(this->signer);
     if (data->len < mac.len)
     {
         return FALSE;
     }
     mac = chunk_skip(*data, data->len - mac.len);
     data->len -= mac.len;
     hdr.type = type;
     htoun64(&hdr.seq, seq);
     htoun16(&hdr.version, version);
     htoun16(&hdr.length, data->len);
     assoc = chunk_from_thing(hdr);
     if (!this->signer->get_signature(this->signer, assoc, NULL) ||
         !this->signer->verify_signature(this->signer, *data, mac))
     {
         return FALSE;
     }
     return TRUE;
 }
METHOD (tls_aead_t , get_mac_key_size , size_t , private_tls_aead_t * this)
Definition at line 97 of file tls_aead_null.c.
References signer.
 {
     return this->signer->get_key_size(this->signer);
 }
METHOD (tls_aead_t , get_encr_key_size , size_t , private_tls_aead_t * this)
Definition at line 103 of file tls_aead_null.c.
 {
     return 0;
 }
METHOD (tls_aead_t , get_iv_size , size_t , private_tls_aead_t * this)
Definition at line 109 of file tls_aead_null.c.
 {
     return 0;
 }
METHOD (tls_aead_t , set_keys , bool , private_tls_aead_t * this, chunk_t mac, chunk_t encr, chunk_t iv)
Definition at line 115 of file tls_aead_null.c.
References FALSE, chunk_t::len, and signer.
 {
     if (iv.len || encr.len)
     {
         return FALSE;
     }
     return this->signer->set_key(this->signer, mac);
 }
METHOD (tls_aead_t , destroy , void , private_tls_aead_t * this)
Definition at line 125 of file tls_aead_null.c.
References free(), and signer.
 {
     this->signer->destroy(this->signer);
     free(this);
 }
Variable Documentation
sigheader_t
Definition at line 44 of file tls_aead_null.c.
Referenced by METHOD().