strongSwan: bliss_bitpacker
bliss_bitpacker
bliss
Classes
struct bliss_bitpacker_t
Typedefs
typedef struct bliss_bitpacker_t bliss_bitpacker_t
Functions
bliss_bitpacker_t * bliss_bitpacker_create (uint16_t max_bits)
bliss_bitpacker_t * bliss_bitpacker_create_from_data (chunk_t data)
Detailed Description
Typedef Documentation
typedef struct bliss_bitpacker_t bliss_bitpacker_t
Definition at line 26 of file bliss_bitpacker.h.
Function Documentation
bliss_bitpacker_t* bliss_bitpacker_create (uint16_t max_bits)
Create a bliss_bitpacker_t object for writing
Parameters
max_bits Total number of bits to be stored
See header.
Definition at line 162 of file bliss_bitpacker.c.
References chunk_alloc, INIT, and round_up().
Referenced by bliss_public_key_encode(), METHOD(), and START_TEST().
 {
     private_bliss_bitpacker_t *this;
     INIT(this,
         .public = {
             .get_bits = _get_bits,
             .write_bits = _write_bits,
             .read_bits = _read_bits,
             .extract_buf = _extract_buf,
             .destroy = _destroy,
         },
         .bits_left = 32,
         .buf = chunk_alloc(round_up(max_bits, 32)/8),
     );
     this->pos = this->buf;
     return &this->public;
 }
bliss_bitpacker_t* bliss_bitpacker_create_from_data (chunk_t data)
Create a bliss_bitpacker_t object for reading
Parameters
data Packed array of bits
See header.
Definition at line 186 of file bliss_bitpacker.c.
References chunk_alloc, INIT, chunk_t::len, memcpy, memset, chunk_t::ptr, and round_up().
Referenced by bliss_private_key_load(), bliss_public_key_from_asn1(), bliss_signature_create_from_data(), and START_TEST().
 {
     private_bliss_bitpacker_t *this;
     INIT(this,
         .public = {
             .get_bits = _get_bits,
             .write_bits = _write_bits,
             .read_bits = _read_bits,
             .extract_buf = _extract_buf,
             .destroy = _destroy,
         },
         .bits = 8 * data.len,
         .buf = chunk_alloc(round_up(data.len, 4)),
     );
     memset(this->buf.ptr + this->buf.len - 4, 0x00, 4);
     memcpy(this->buf.ptr, data.ptr, data.len);
     this->pos = this->buf;
     return &this->public;
 }