strongSwan: sasl_mechanism
sasl_mechanism
sasl
Classes
struct sasl_mechanism_t
Typedefs
typedef struct sasl_mechanism_t sasl_mechanism_t
typedef sasl_mechanism_t *(* sasl_mechanism_constructor_t)(char *name, identification_t *client)
Functions
sasl_mechanism_t * sasl_mechanism_create (char *name, identification_t *client)
enumerator_t * sasl_mechanism_create_enumerator (bool server)
Detailed Description
Typedef Documentation
typedef sasl_mechanism_t*(* sasl_mechanism_constructor_t)(char *name, identification_t *client)
Constructor function for SASL mechansims.
Parameters
name name of the requested SASL mechanism
client client identity, NULL to act as server
Returns
SASL mechanism, NULL on failure
Definition at line 38 of file sasl_mechanism.h.
typedef struct sasl_mechanism_t sasl_mechanism_t
Definition at line 27 of file sasl_mechanism.h.
Function Documentation
sasl_mechanism_t* sasl_mechanism_create (char * name, identification_t * client)
Create a sasl_mechanism instance.
Parameters
name name of SASL mechanism to create
client client identity, NULL to act as server
Returns
SASL mechanism instance, NULL if not found
See header.
Definition at line 35 of file sasl_mechanism.c.
References countof, mechs, and streq().
Referenced by read_sasl_mech_selection(), and select_and_do_sasl().
 {
     int i;
     for (i = 0; i < countof(mechs); i++)
     {
         if (streq(mechs[i].name, name) && mechs[i].server == (client == NULL))
         {
             return mechs[i].create(name, client);
         }
     }
     return NULL;
 }
enumerator_t* sasl_mechanism_create_enumerator (bool server)
Create an enumerator over supported SASL mechanism names.
Parameters
server TRUE for server instance, FALSE for client
Returns
enumerator over char*
See header.
Definition at line 80 of file sasl_mechanism.c.
References destroy(), free(), INIT, mech_enumerator_t::public, and server.
Referenced by send_sasl_mechs().
 {
     mech_enumerator_t *enumerator;
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_mech_enumerate,
             .destroy = (void*)free,
         },
         .server = server,
     );
     return &enumerator->public;
 }