strongSwan: tnc_imc.c File Reference
tnc_imc.c File Reference
#include "tnc_imc.h"
#include <dlfcn.h>
#include <tncif_pa_subtypes.h>
#include <utils/debug.h>
#include <library.h>
#include <collections/linked_list.h>
#include <threading/mutex.h>
Classes
struct private_tnc_imc_t
Typedefs
typedef struct private_tnc_imc_t private_tnc_imc_t
Functions
METHOD (imc_t, set_id, void, private_tnc_imc_t *this, TNC_IMCID id)
METHOD (imc_t, get_id, TNC_IMCID, private_tnc_imc_t *this)
METHOD (imc_t, add_id, void, private_tnc_imc_t *this, TNC_IMCID id)
METHOD (imc_t, has_id, bool, private_tnc_imc_t *this, TNC_IMCID id)
METHOD (imc_t, get_name, char *, private_tnc_imc_t *this)
METHOD (imc_t, set_message_types, void, private_tnc_imc_t *this, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
METHOD (imc_t, set_message_types_long, void, private_tnc_imc_t *this, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
METHOD (imc_t, type_supported, bool, private_tnc_imc_t *this, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
METHOD (imc_t, destroy, void, private_tnc_imc_t *this)
static private_tnc_imc_t * tnc_imc_create_empty (char *name)
imc_t * tnc_imc_create (char *name, char *path)
imc_t * tnc_imc_create_from_functions (char *name, TNC_IMC_InitializePointer initialize, TNC_IMC_NotifyConnectionChangePointer notify_connection_change, TNC_IMC_BeginHandshakePointer begin_handshake, TNC_IMC_ReceiveMessagePointer receive_message, TNC_IMC_ReceiveMessageLongPointer receive_message_long, TNC_IMC_BatchEndingPointer batch_ending, TNC_IMC_TerminatePointer terminate, TNC_IMC_ProvideBindFunctionPointer provide_bind_function)
Typedef Documentation
typedef struct private_tnc_imc_t private_tnc_imc_t
Definition at line 29 of file tnc_imc.c.
Function Documentation
METHOD (imc_t , set_id , void , private_tnc_imc_t * this, TNC_IMCID id)
Definition at line 82 of file tnc_imc.c.
References id.
 {
     this->id = id;
 }
METHOD (imc_t , get_id , TNC_IMCID , private_tnc_imc_t * this)
Definition at line 88 of file tnc_imc.c.
References id.
 {
     return this->id;
 }
METHOD (imc_t , add_id , void , private_tnc_imc_t * this, TNC_IMCID id)
Definition at line 94 of file tnc_imc.c.
References id.
 {
     void *pointer;
     /* store the scalar value in the pointer */
     pointer = (void*)(uintptr_t)id;
     this->additional_ids->insert_last(this->additional_ids, pointer);
 }
METHOD (imc_t , has_id , bool , private_tnc_imc_t * this, TNC_IMCID id)
Definition at line 104 of file tnc_imc.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, found, and TRUE.
 {
     enumerator_t *enumerator;
     TNC_IMCID additional_id;
     void *pointer;
     bool found = FALSE;
     /* check primary IMC ID */
     if (id == this->id)
     {
         return TRUE;
     }
     /* return if there are no additional IMC IDs */
     if (this->additional_ids->get_count(this->additional_ids) == 0)
     {
         return FALSE;
     }
     /* check additional IMC IDs */
     enumerator = this->additional_ids->create_enumerator(this->additional_ids);
     while (enumerator->enumerate(enumerator, &pointer))
     {
         /* interpret pointer as scalar value */
         additional_id = (uintptr_t)pointer;
         if (id == additional_id)
         {
             found = TRUE;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
METHOD (imc_t , get_name , char * , private_tnc_imc_t * this)
Definition at line 142 of file tnc_imc.c.
References name.
 {
     return this->name;
 }
METHOD (imc_t , set_message_types , void , private_tnc_imc_t * this, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
Definition at line 148 of file tnc_imc.c.
References BUF_LEN, DBG2, DBG_TNC, free(), get_pa_subtype_names(), len, mutex_t::lock, malloc(), mutex, pen_names, size, snprintf, subtype, TNC_SUBTYPE_ANY, TNC_VENDORID_ANY, and mutex_t::unlock.
 {
     char buf[BUF_LEN];
     char *pos = buf;
     int len = sizeof(buf);
     int i, written;
     size_t size;
     TNC_VendorID vid;
     TNC_MessageSubtype subtype;
     enum_name_t *pa_subtype_names;
     /* lock the imc_t instance */
     this->mutex->lock(this->mutex);
     /* Free existing VendorID and MessageSubtype lists */
     free(this->supported_vids);
     this->supported_vids = NULL;
     free(this->supported_subtypes);
     this->supported_subtypes = NULL;
     /* Store the new MessageType list */
     this->type_count = type_count;
     if (type_count && supported_types)
     {
         size = type_count * sizeof(TNC_VendorID);
         this->supported_vids = malloc(size);
         size = type_count * sizeof(TNC_MessageSubtype);
         this->supported_subtypes = malloc(size);
         for (i = 0; i < type_count; i++)
         {
             vid = (supported_types[i] >> 8) & TNC_VENDORID_ANY;
             subtype = supported_types[i] & TNC_SUBTYPE_ANY;
             pa_subtype_names = get_pa_subtype_names(vid);
             if (pa_subtype_names)
             {
                 written = snprintf(pos, len," '%N/%N' 0x%06x/0x%02x",
                                    pen_names, vid, pa_subtype_names, subtype,
                                    vid, subtype);
             }
             else
             {
                 written = snprintf(pos, len," '%N' 0x%06x/0x%02x",
                                    pen_names, vid, vid, subtype);
             }
             if (written >= len)
             {
                 break;
             }
             pos += written;
             len -= written;
             this->supported_vids[i] = vid;
             this->supported_subtypes[i] = subtype;
         }
     }
     *pos = '\0';
     DBG2(DBG_TNC, "IMC %u supports %u message type%s:%s",
                   this->id, type_count, (type_count == 1) ? "":"s", buf);
     /* unlock the imc_t instance */
     this->mutex->unlock(this->mutex);
 }
METHOD (imc_t , set_message_types_long , void , private_tnc_imc_t * this, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
Definition at line 215 of file tnc_imc.c.
References BUF_LEN, DBG2, DBG_TNC, free(), get_pa_subtype_names(), len, mutex_t::lock, malloc(), memcpy, mutex, pen_names, size, snprintf, subtype, and mutex_t::unlock.
 {
     char buf[BUF_LEN];
     char *pos = buf;
     int len = sizeof(buf);
     int i, written;
     size_t size;
     TNC_VendorID vid;
     TNC_MessageSubtype subtype;
     enum_name_t *pa_subtype_names;
     /* lock the imc_t instance */
     this->mutex->lock(this->mutex);
     /* Free existing VendorID and MessageSubtype lists */
     free(this->supported_vids);
     this->supported_vids = NULL;
     free(this->supported_subtypes);
     this->supported_subtypes = NULL;
     /* Store the new MessageType list */
     this->type_count = type_count;
     if (type_count && supported_vids && supported_subtypes)
     {
         size = type_count * sizeof(TNC_VendorID);
         this->supported_vids = malloc(size);
         memcpy(this->supported_vids, supported_vids, size);
         size = type_count * sizeof(TNC_MessageSubtype);
         this->supported_subtypes = malloc(size);
         memcpy(this->supported_subtypes, supported_subtypes, size);
         for (i = 0; i < type_count; i++)
         {
             vid = supported_vids[i];
             subtype = supported_subtypes[i];
             pa_subtype_names = get_pa_subtype_names(vid);
             if (pa_subtype_names)
             {
                 written = snprintf(pos, len," '%N/%N' 0x%06x/0x%08x",
                                    pen_names, vid, pa_subtype_names, subtype,
                                    vid, subtype);
             }
             else
             {
                 written = snprintf(pos, len," '%N' 0x%06x/0x%08x",
                                    pen_names, vid, vid, subtype);
             }
             if (written >= len)
             {
                 break;
             }
             pos += written;
             len -= written;
         }
     }
     *pos = '\0';
     DBG2(DBG_TNC, "IMC %u supports %u message type%s:%s",
                   this->id, type_count, (type_count == 1) ? "":"s", buf);
     /* unlock the imc_t instance */
     this->mutex->unlock(this->mutex);
 }
METHOD (imc_t , type_supported , bool , private_tnc_imc_t * this, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype)
Definition at line 281 of file tnc_imc.c.
References FALSE, subtype, TNC_SUBTYPE_ANY, TNC_VENDORID_ANY, and TRUE.
 {
     TNC_VendorID vid;
     TNC_MessageSubtype subtype;
     int i;
     for (i = 0; i < this->type_count; i++)
     {
         vid = this->supported_vids[i];
         subtype = this->supported_subtypes[i];
         if ((vid == TNC_VENDORID_ANY && subtype == TNC_SUBTYPE_ANY) ||
             (vid == msg_vid && (subtype == TNC_SUBTYPE_ANY ||
              subtype == msg_subtype)))
         {
             return TRUE;
         }
     }
     return FALSE;
 }
METHOD (imc_t , destroy , void , private_tnc_imc_t * this)
Definition at line 303 of file tnc_imc.c.
References mutex_t::destroy, dlclose(), free(), settings_t::get_bool, handle, lib, mutex, name, library_t::ns, library_t::settings, and TRUE.
 {
     if (this->handle && lib->settings->get_bool(lib->settings,
         "%s.plugins.tnc-imc.dlclose", TRUE, lib->ns))
     {
         dlclose(this->handle);
     }
     this->mutex->destroy(this->mutex);
     this->additional_ids->destroy(this->additional_ids);
     free(this->supported_vids);
     free(this->supported_subtypes);
     free(this->name);
     free(this);
 }
static private_tnc_imc_t* tnc_imc_create_empty (char * name) static
Generic constructor
Definition at line 322 of file tnc_imc.c.
References INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, and strdup.
Referenced by tnc_imc_create(), and tnc_imc_create_from_functions().
 {
     private_tnc_imc_t *this;
     INIT(this,
         .public = {
             .set_id = _set_id,
             .get_id = _get_id,
             .add_id = _add_id,
             .has_id = _has_id,
             .get_name = _get_name,
             .set_message_types = _set_message_types,
             .set_message_types_long = _set_message_types_long,
             .type_supported = _type_supported,
             .destroy = _destroy,
         },
         .name = strdup(name),
         .additional_ids = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     return this;
 }