strongSwan: fast_smtp.c File Reference
fast_smtp.c File Reference
#include "fast_smtp.h"
#include <unistd.h>
#include <errno.h>
#include <utils/debug.h>
Classes
struct private_fast_smtp_t
Typedefs
typedef struct private_fast_smtp_t private_fast_smtp_t
Functions
static int read_response (private_fast_smtp_t *this)
static int write_cmd (private_fast_smtp_t *this, char *fmt,...)
METHOD (fast_smtp_t, send_mail, bool, private_fast_smtp_t *this, char *from, char *to, char *subject, char *fmt,...)
METHOD (fast_smtp_t, destroy, void, private_fast_smtp_t *this)
fast_smtp_t * fast_smtp_create ()
Typedef Documentation
typedef struct private_fast_smtp_t private_fast_smtp_t
Definition at line 23 of file fast_smtp.c.
Function Documentation
METHOD (fast_smtp_t , send_mail , bool , private_fast_smtp_t * this, char * from, char * to, char * subject, char * fmt, ...)
Definition at line 92 of file fast_smtp.c.
References DBG1, DBG_LIB, FALSE, fprintf, read_response(), vfprintf, and write_cmd().
 {
     va_list args;
     if (write_cmd(this, "MAIL FROM:<%s>", from) != 250)
     {
         DBG1(DBG_LIB, "SMTP MAIL FROM failed");
         return FALSE;
     }
     if (write_cmd(this, "RCPT TO:<%s>", to) != 250)
     {
         DBG1(DBG_LIB, "SMTP RCPT TO failed");
         return FALSE;
     }
     if (write_cmd(this, "DATA") != 354)
     {
         DBG1(DBG_LIB, "SMTP DATA failed");
         return FALSE;
     }
     fprintf(this->f, "From: %s\n", from);
     fprintf(this->f, "To: %s\n", to);
     fprintf(this->f, "Subject: %s\n", subject);
     fprintf(this->f, "\n");
     va_start(args, fmt);
     vfprintf(this->f, fmt, args);
     va_end(args);
     fprintf(this->f, "\n.\n");
     return read_response(this) == 250;
 }
METHOD (fast_smtp_t , destroy , void , private_fast_smtp_t * this)
Definition at line 125 of file fast_smtp.c.
References free(), and write_cmd().
 {
     write_cmd(this, "QUIT");
     fclose(this->f);
     free(this);
 }
static int read_response (private_fast_smtp_t * this) static
Read the response code from an SMTP server
Definition at line 44 of file fast_smtp.c.
References end, res, and TRUE.
Referenced by fast_smtp_create(), METHOD(), and write_cmd().
 {
     char buf[256], *end;
     int res = 0;
     while (TRUE)
     {
         if (!fgets(buf, sizeof(buf), this->f))
         {
             return 0;
         }
         res = strtol(buf, &end, 10);
         switch (*end)
         {
             case '-':
                 continue;
             case ' ':
             case '\0':
             case '\n':
                 break;
             default:
                 return 0;
         }
         break;
     }
     return res;
 }
static int write_cmd (private_fast_smtp_t * this, char * fmt, ...) static
write a SMTP command to the server, read response code
Definition at line 75 of file fast_smtp.c.
References DBG1, DBG_LIB, fprintf, read_response(), and vsnprintf.
Referenced by fast_smtp_create(), and METHOD().
 {
     char buf[256];
     va_list args;
     va_start(args, fmt);
     vsnprintf(buf, sizeof(buf), fmt, args);
     va_end(args);
     if (fprintf(this->f, "%s\n", buf) < 1)
     {
         DBG1(DBG_LIB, "sending SMTP command failed");
         return 0;
     }
     return read_response(this);
 }