strongSwan: tnccs_11_plugin.c File Reference
tnccs_11_plugin.c File Reference
#include "tnccs_11_plugin.h"
#include "tnccs_11.h"
#include <tnc/tnccs/tnccs_manager.h>
Functions
METHOD (plugin_t, get_name, char *, tnccs_11_plugin_t *this)
METHOD (plugin_t, get_features, int, tnccs_11_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, tnccs_11_plugin_t *this)
plugin_t * tnccs_11_plugin_create ()
Function Documentation
METHOD (plugin_t , get_name , char * , tnccs_11_plugin_t * this)
Definition at line 21 of file tnccs_11_plugin.c.
 {
     return "tnccs-11";
 }
METHOD (plugin_t , get_features , int , tnccs_11_plugin_t * this, plugin_feature_t * features[])
Definition at line 27 of file tnccs_11_plugin.c.
References countof, PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, tnccs_11_create(), and tnccs_method_register().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(tnccs_method_register, tnccs_11_create),
             PLUGIN_PROVIDE(CUSTOM, "tnccs-1.1"),
                 PLUGIN_DEPENDS(CUSTOM, "tnccs-manager"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , tnccs_11_plugin_t * this)
Definition at line 39 of file tnccs_11_plugin.c.
References free().
 {
     free(this);
 }
plugin_t* tnccs_11_plugin_create ()
Definition at line 48 of file tnccs_11_plugin.c.
References INIT, and plugin.
 {
     tnccs_11_plugin_t *this;
     INIT(this,
         .plugin = {
             .get_name = _get_name,
             .get_features = _get_features,
             .destroy = _destroy,
         },
     );
     return &this->plugin;
 }