strongSwan: ita_attr_command
ita_attr_command
ita_attr
Classes
struct ita_attr_command_t
Typedefs
typedef struct ita_attr_command_t ita_attr_command_t
Functions
pa_tnc_attr_t * ita_attr_command_create (char *command)
pa_tnc_attr_t * ita_attr_command_create_from_data (size_t length, chunk_t value)
Detailed Description
Typedef Documentation
typedef struct ita_attr_command_t ita_attr_command_t
Definition at line 24 of file ita_attr_command.h.
Function Documentation
pa_tnc_attr_t* ita_attr_command_create (char * command)
Creates an ita_attr_command_t object from a command string
Parameters
command ITA command string
Described in header.
Definition at line 150 of file ita_attr_command.c.
References INIT, ITA_ATTR_COMMAND, PEN_ITA, and strdup.
Referenced by create_message(), receive_msg(), and START_TEST().
 {
     private_ita_attr_command_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_command = _get_command,
         },
         .type = { PEN_ITA, ITA_ATTR_COMMAND },
         .command = strdup(command),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ita_attr_command_create_from_data (size_t length, chunk_t data)
Creates an ita_attr_command_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 180 of file ita_attr_command.c.
References chunk_clone, INIT, ITA_ATTR_COMMAND, length, and PEN_ITA.
Referenced by ita_attr_create_from_data().
 {
     private_ita_attr_command_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_command = _get_command,
         },
         .type = {PEN_ITA, ITA_ATTR_COMMAND },
         .length = length,
         .value = chunk_clone(data),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }