strongSwan: pgp_encoder.c File Reference
pgp_encoder.c File Reference
#include "pgp_encoder.h"
#include <utils/debug.h>
Functions
static bool build_v3_fingerprint (chunk_t *encoding, va_list args)
bool pgp_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Function Documentation
static bool build_v3_fingerprint (chunk_t * encoding, va_list args) static
Build a PGPv3 fingerprint
Definition at line 23 of file pgp_encoder.c.
References hasher_t::allocate_hash, chunk_skip(), crypto_factory_t::create_hasher, cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, FALSE, HASH_MD5, hasher, chunk_t::len, lib, n, chunk_t::ptr, and TRUE.
Referenced by pgp_encoder_encode().
 {
     hasher_t *hasher;
     chunk_t n, e;
     if (cred_encoding_args(args, CRED_PART_RSA_MODULUS, &n,
                            CRED_PART_RSA_PUB_EXP, &e, CRED_PART_END))
     {
         hasher = lib->crypto->create_hasher(lib->crypto, HASH_MD5);
         if (!hasher)
         {
             DBG1(DBG_LIB, "MD5 hash algorithm not supported, PGP"
                  " fingerprinting failed");
             return FALSE;
         }
         /* remove leading zero bytes before hashing modulus and exponent */
         while (n.len > 0 && n.ptr[0] == 0x00)
         {
             n = chunk_skip(n, 1);
         }
         while (e.len > 0 && e.ptr[0] == 0x00)
         {
             e = chunk_skip(e, 1);
         }
         if (!hasher->allocate_hash(hasher, n, NULL) ||
             !hasher->allocate_hash(hasher, e, encoding))
         {
             hasher->destroy(hasher);
             return FALSE;
         }
         hasher->destroy(hasher);
         return TRUE;
     }
     return FALSE;
 }