strongSwan: controller
controller
control
Classes
struct controller_t
Typedefs
typedef bool(* controller_cb_t)(void *param, debug_t group, level_t level, ike_sa_t *ike_sa, const char *message)
typedef struct controller_t controller_t
Functions
bool controller_cb_empty (void *param, debug_t group, level_t level, ike_sa_t *ike_sa, const char *message)
controller_t * controller_create ()
Detailed Description
Typedef Documentation
typedef bool(* controller_cb_t)(void *param, debug_t group, level_t level, ike_sa_t *ike_sa, const char *message)
Callback to log things triggered by controller.
Parameters
param parameter supplied when controller method was called
group debugging group
level verbosity level
ike_sa associated IKE_SA, if any
message log message
Returns
FALSE to return from called controller method
Definition at line 36 of file controller.h.
typedef struct controller_t controller_t
Definition at line 48 of file controller.h.
Function Documentation
bool controller_cb_empty (void * param, debug_t group, level_t level, ike_sa_t * ike_sa, const char * message)
Empty callback function for controller_t methods.
If you want to do a synchronous call, but don't need a callback, pass this function to the controller methods.
See header
Definition at line 686 of file controller.c.
References TRUE.
Referenced by disconnect(), initiate(), METHOD(), and terminate().
 {
     return TRUE;
 }
controller_t* controller_create ()
Creates a controller instance.
Returns
controller_t object
Definition at line 701 of file controller.c.
References INIT.
Referenced by daemon_create().
 {
     private_controller_t *this;
     INIT(this,
         .public = {
             .create_ike_sa_enumerator = _create_ike_sa_enumerator,
             .initiate = _initiate,
             .terminate_ike = _terminate_ike,
             .terminate_child = _terminate_child,
             .destroy = _destroy,
         },
     );
     return &this->public;
 }