strongSwan: delete_payload
delete_payload
payloads
Classes
struct delete_payload_t
Typedefs
typedef struct delete_payload_t delete_payload_t
Functions
delete_payload_t * delete_payload_create (payload_type_t type, protocol_id_t protocol_id)
Detailed Description
Typedef Documentation
typedef struct delete_payload_t delete_payload_t
Definition at line 26 of file delete_payload.h.
Function Documentation
delete_payload_t* delete_payload_create (payload_type_t type, protocol_id_t protocol_id)
Creates an empty delete_payload_t object.
Parameters
type PLV2_DELETE or PLV1_DELETE
protocol_id protocol, such as AH|ESP
Returns
delete_payload_t object
Definition at line 349 of file delete_payload.c.
References IKEV1_DOI_IPSEC, INIT, PL_NONE, PLV1_DELETE, PROTO_IKE, and type.
Referenced by build_payloads(), METHOD(), and payload_create().
 {
     private_delete_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_payload_type,
                 .destroy = _destroy,
             },
             .get_protocol_id = _get_protocol_id,
             .add_spi = _add_spi,
             .set_ike_spi = _set_ike_spi,
             .get_ike_spi = _get_ike_spi,
             .create_spi_enumerator = _create_spi_enumerator,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .protocol_id = protocol_id,
         .doi = IKEV1_DOI_IPSEC,
         .type = type,
     );
     this->payload_length = get_header_length(this);
     if (protocol_id == PROTO_IKE)
     {
         if (type == PLV1_DELETE)
         {
             this->spi_size = 16;
         }
     }
     else
     {
         this->spi_size = 4;
     }
     return &this->public;
 }