strongSwan: tkm_diffie_hellman.c File Reference
tkm_diffie_hellman.c File Reference
#include <tkm/client.h>
#include <tkm/constants.h>
#include "tkm.h"
#include "tkm_utils.h"
#include "tkm_diffie_hellman.h"
#include <daemon.h>
#include <collections/hashtable.h>
Classes
struct private_tkm_diffie_hellman_t
Typedefs
typedef struct
private_tkm_diffie_hellman_t private_tkm_diffie_hellman_t
Functions
METHOD (diffie_hellman_t, get_my_public_value, bool, private_tkm_diffie_hellman_t *this, chunk_t *value)
METHOD (diffie_hellman_t, get_shared_secret, bool, private_tkm_diffie_hellman_t *this, chunk_t *secret)
METHOD (diffie_hellman_t, set_other_public_value, bool, private_tkm_diffie_hellman_t *this, chunk_t value)
METHOD (diffie_hellman_t, get_dh_group, diffie_hellman_group_t, private_tkm_diffie_hellman_t *this)
METHOD (diffie_hellman_t, destroy, void, private_tkm_diffie_hellman_t *this)
METHOD (tkm_diffie_hellman_t, get_id, dh_id_type, private_tkm_diffie_hellman_t *this)
static u_int hash (void *key)
static bool equals (void *key, void *other_key)
int register_dh_mapping ()
void destroy_dh_mapping ()
tkm_diffie_hellman_t * tkm_diffie_hellman_create (diffie_hellman_group_t group)
Variables
static hashtable_t * group_map = NULL
Typedef Documentation
typedef struct private_tkm_diffie_hellman_t private_tkm_diffie_hellman_t
Definition at line 27 of file tkm_diffie_hellman.c.
Function Documentation
static bool equals (void * key, void * other_key) static
Definition at line 113 of file tkm_diffie_hellman.c.
Referenced by register_dh_mapping().
 {
     return *(diffie_hellman_group_t*)key == *(diffie_hellman_group_t*)other_key;
 }
static u_int hash (void * key) static
Definition at line 107 of file tkm_diffie_hellman.c.
References chunk_from_thing, and chunk_hash().
Referenced by register_dh_mapping().
 {
     diffie_hellman_group_t k = *(diffie_hellman_group_t*)key;
     return chunk_hash(chunk_from_thing(k));
 }
METHOD (diffie_hellman_t , get_my_public_value , bool , private_tkm_diffie_hellman_t * this, chunk_t * value)
Definition at line 58 of file tkm_diffie_hellman.c.
References sequence_to_chunk(), and TRUE.
 {
     sequence_to_chunk(this->pubvalue.data, this->pubvalue.size, value);
     return TRUE;
 }
METHOD (diffie_hellman_t , get_shared_secret , bool , private_tkm_diffie_hellman_t * this, chunk_t * secret)
Definition at line 65 of file tkm_diffie_hellman.c.
References chunk_empty, and TRUE.
 {
     *secret = chunk_empty;
     return TRUE;
 }
METHOD (diffie_hellman_t , set_other_public_value , bool , private_tkm_diffie_hellman_t * this, chunk_t value)
Definition at line 73 of file tkm_diffie_hellman.c.
References chunk_t::len, memcpy, and chunk_t::ptr.
 {
     dh_pubvalue_type othervalue;
     othervalue.size = value.len;
     memcpy(&othervalue.data, value.ptr, value.len);
     return ike_dh_generate_key(this->context_id, othervalue) == TKM_OK;
 }
METHOD (diffie_hellman_t , get_dh_group , diffie_hellman_group_t , private_tkm_diffie_hellman_t * this)
Definition at line 83 of file tkm_diffie_hellman.c.
References group.
 {
     return this->group;
 }
METHOD (diffie_hellman_t , destroy , void , private_tkm_diffie_hellman_t * this)
Definition at line 89 of file tkm_diffie_hellman.c.
References DBG1, DBG_LIB, free(), tkm_t::idmgr, tkm_id_manager_t::release_id, tkm, and TKM_CTX_DH.
 {
     if (ike_dh_reset(this->context_id) != TKM_OK)
     {
         DBG1(DBG_LIB, "failed to reset DH context %d", this->context_id);
     }
     tkm->idmgr->release_id(tkm->idmgr, TKM_CTX_DH, this->context_id);
     free(this);
 }
METHOD (tkm_diffie_hellman_t , get_id , dh_id_type , private_tkm_diffie_hellman_t * this)
Definition at line 101 of file tkm_diffie_hellman.c.
 {
     return this->context_id;
 }
Variable Documentation
hashtable_t* group_map = NULL static
Definition at line 29 of file tkm_diffie_hellman.c.