strongSwan: pkcs11_creds
pkcs11_creds
pkcs11
Classes
struct pkcs11_creds_t
Typedefs
typedef struct pkcs11_creds_t pkcs11_creds_t
Functions
pkcs11_creds_t * pkcs11_creds_create (pkcs11_library_t *p11, CK_SLOT_ID slot)
certificate_t * pkcs11_creds_load (certificate_type_t type, va_list args)
Detailed Description
Typedef Documentation
typedef struct pkcs11_creds_t pkcs11_creds_t
Definition at line 24 of file pkcs11_creds.h.
Function Documentation
pkcs11_creds_t* pkcs11_creds_create (pkcs11_library_t * p11, CK_SLOT_ID slot)
Create a pkcs11_creds instance.
Parameters
p11 loaded PKCS#11 library
slot slot of the token we hand out credentials
See header
Definition at line 230 of file pkcs11_creds.c.
References create_private_enumerator(), destroy(), enumerator_create_empty(), INIT, linked_list_create(), load_certificates(), and nop().
Referenced by token_event_cb().
 {
     private_pkcs11_creds_t *this;
     INIT(this,
         .public = {
             .set = {
                 .create_shared_enumerator = (void*)enumerator_create_empty,
                 .create_private_enumerator = (void*)enumerator_create_empty,
                 .create_cert_enumerator = _create_cert_enumerator,
                 .create_cdp_enumerator  = (void*)enumerator_create_empty,
                 .cache_cert = (void*)nop,
             },
             .get_library = _get_library,
             .get_slot = _get_slot,
             .destroy = _destroy,
         },
         .lib = p11,
         .slot = slot,
         .trusted = linked_list_create(),
         .untrusted = linked_list_create(),
     );
     if (!load_certificates(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
certificate_t* pkcs11_creds_load (certificate_type_t type, va_list args)
Load a specific certificate from a token.
Requires a BUILD_PKCS11_KEYID argument, and optionally BUILD_PKCS11_MODULE and/or BUILD_PKCS11_SLOT.
Parameters
type certificate type, must be CERT_X509
args variable argument list, containing BUILD_PKCS11_KEYID.
Returns
loaded certificate, or NULL on failure
See header.
Definition at line 265 of file pkcs11_creds.c.
References BUILD_BLOB_ASN1_DER, BUILD_END, BUILD_PKCS11_KEYID, BUILD_PKCS11_MODULE, BUILD_PKCS11_SLOT, ck_function_list::C_CloseSession, ck_function_list::C_OpenSession, cert, CERT_X509, chunk_clone, chunk_create(), chunk_empty, ck_rv_names, CKA_CERTIFICATE_TYPE, CKA_CLASS, CKA_ID, CKA_VALUE, CKC_X_509, CKF_SERIAL_SESSION, CKO_CERTIFICATE, CKR_OK, countof, credential_factory_t::create, pkcs11_library_t::create_object_enumerator, pkcs11_manager_t::create_token_enumerator, CRED_CERTIFICATE, library_t::creds, data, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, pkcs11_library_t::f, free(), library_t::get, pkcs11_library_t::get_name, keyid(), chunk_t::len, lib, chunk_t::ptr, streq(), TRUE, and type.
Referenced by handle_certs().
 {
     chunk_t keyid = chunk_empty, data = chunk_empty;
     enumerator_t *enumerator, *certs;
     pkcs11_manager_t *manager;
     pkcs11_library_t *p11;
     certificate_t *cert = NULL;
     CK_SLOT_ID current, slot = -1;
     char *module = NULL;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_PKCS11_KEYID:
                 keyid = va_arg(args, chunk_t);
                 continue;
             case BUILD_PKCS11_SLOT:
                 slot = va_arg(args, int);
                 continue;
             case BUILD_PKCS11_MODULE:
                 module = va_arg(args, char*);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (!keyid.len)
     {
         return NULL;
     }
     manager = lib->get(lib, "pkcs11-manager");
     if (!manager)
     {
         return NULL;
     }
     enumerator = manager->create_token_enumerator(manager);
     while (enumerator->enumerate(enumerator, &p11, &current))
     {
         CK_OBJECT_CLASS class = CKO_CERTIFICATE;
         CK_CERTIFICATE_TYPE type = CKC_X_509;
         CK_ATTRIBUTE tmpl[] = {
             {CKA_CLASS, &class, sizeof(class)},
             {CKA_CERTIFICATE_TYPE, &type, sizeof(type)},
             {CKA_ID, keyid.ptr, keyid.len},
         };
         CK_ATTRIBUTE attr[] = {
             {CKA_VALUE, NULL, 0},
         };
         CK_OBJECT_HANDLE object;
         CK_SESSION_HANDLE session;
         CK_RV rv;
         if (slot != -1 && slot != current)
         {
             continue;
         }
         if (module && !streq(module, p11->get_name(p11)))
         {
             continue;
         }
         rv = p11->f->C_OpenSession(current, CKF_SERIAL_SESSION, NULL, NULL,
                                    &session);
         if (rv != CKR_OK)
         {
             DBG1(DBG_CFG, "opening PKCS#11 session failed: %N", ck_rv_names, rv);
             continue;
         }
         certs = p11->create_object_enumerator(p11, session,
                                     tmpl, countof(tmpl), attr, countof(attr));
         if (certs->enumerate(certs, &object))
         {
             data = chunk_clone(chunk_create(attr[0].pValue, attr[0].ulValueLen));
         }
         certs->destroy(certs);
         p11->f->C_CloseSession(session);
         if (data.ptr)
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (data.ptr)
     {
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_BLOB_ASN1_DER, data, BUILD_END);
         free(data.ptr);
         if (!cert)
         {
             DBG1(DBG_CFG, "parsing PKCS#11 certificate %#B failed", &keyid);
         }
     }
     else
     {
         DBG1(DBG_CFG, "PKCS#11 certificate %#B not found", &keyid);
     }
     return cert;
 }