strongSwan: ietf_attr_attr_request
ietf_attr_attr_request
ietf_attr
Classes
struct ietf_attr_attr_request_t
Typedefs
typedef struct
ietf_attr_attr_request_t ietf_attr_attr_request_t
Functions
pa_tnc_attr_t * ietf_attr_attr_request_create (pen_t vendor_id, u_int32_t type)
pa_tnc_attr_t * ietf_attr_attr_request_create_from_data (size_t length, chunk_t value)
Detailed Description
Typedef Documentation
typedef struct ietf_attr_attr_request_t ietf_attr_attr_request_t
Definition at line 24 of file ietf_attr_attr_request.h.
Function Documentation
pa_tnc_attr_t* ietf_attr_attr_request_create (pen_t vendor_id, u_int32_t type)
Creates an ietf_attr_attr_request_t object
Described in header.
Definition at line 231 of file ietf_attr_attr_request.c.
References add(), IETF_ATTR_ATTRIBUTE_REQUEST, INIT, linked_list_create(), PEN_IETF, and PEN_RESERVED.
Referenced by build_attr_request(), and METHOD().
 {
     private_ietf_attr_attr_request_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add = _add,
             .create_enumerator = _create_enumerator,
         },
         .type = { PEN_IETF, IETF_ATTR_ATTRIBUTE_REQUEST },
         .list = linked_list_create(),
         .ref = 1,
     );
     if (vendor_id != PEN_RESERVED)
     {
         add(this, vendor_id, type);
     }
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ietf_attr_attr_request_create_from_data (size_t length, chunk_t data)
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 267 of file ietf_attr_attr_request.c.
References chunk_clone, IETF_ATTR_ATTRIBUTE_REQUEST, INIT, length, linked_list_create(), and PEN_IETF.
Referenced by ietf_attr_create_from_data().
 {
     private_ietf_attr_attr_request_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .add = _add,
             .create_enumerator = _create_enumerator,
         },
         .type = { PEN_IETF, IETF_ATTR_ATTRIBUTE_REQUEST },
         .length = length,
         .value = chunk_clone(data),
         .list = linked_list_create(),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }