strongSwan: ha_ctl
ha_ctl
ha
Classes
struct ha_ctl_t
Typedefs
typedef struct ha_ctl_t ha_ctl_t
Functions
ha_ctl_t * ha_ctl_create (ha_segments_t *segments, ha_cache_t *cache)
Detailed Description
Typedef Documentation
typedef struct ha_ctl_t ha_ctl_t
Definition at line 27 of file ha_ctl.h.
Function Documentation
ha_ctl_t* ha_ctl_create (ha_segments_t * segments, ha_cache_t * cache)
Create a ha_ctl instance.
Parameters
segments segments to control
cache message cache for resynchronization
Returns
HA control interface
See header
Definition at line 159 of file ha_ctl.c.
References cache(), callback_job_create_with_prio(), change_fifo_permissions(), DBG1, DBG_CFG, dispatch_fifo(), HA_FIFO, INIT, JOB_PRIO_CRITICAL, lib, library_t::processor, processor_t::queue_job, recreate_fifo(), return_false(), and strerror.
Referenced by initialize_plugin().
 {
     private_ha_ctl_t *this;
     struct stat sb;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
         .segments = segments,
         .cache = cache,
     );
     if (stat(HA_FIFO, &sb) == 0)
     {
         if (!S_ISFIFO(sb.st_mode))
         {
             DBG1(DBG_CFG, "%s is not a FIFO, recreate it", HA_FIFO);
             recreate_fifo();
         }
         else if (access(HA_FIFO, R_OK|W_OK) != 0)
         {
             DBG1(DBG_CFG, "accessing HA FIFO %s denied, recreate it", HA_FIFO);
             recreate_fifo();
         }
         else
         {
             change_fifo_permissions();
         }
     }
     else if (errno == ENOENT)
     {
         recreate_fifo();
     }
     else
     {
         DBG1(DBG_CFG, "accessing HA FIFO %s failed: %s", HA_FIFO,
              strerror(errno));
     }
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create_with_prio((callback_job_cb_t)dispatch_fifo,
             this, NULL, (callback_job_cancel_t)return_false, JOB_PRIO_CRITICAL));
     return &this->public;
 }