strongSwan: imc_agent_t Struct Reference
imc_agent_t Struct Reference
imc_agent
#include "imc_agent.h"
Public Attributes
TNC_Result(* request_handshake_retry)(TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_RetryReason reason)
TNC_Result(* send_message)(TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
TNC_Result(* send_message_long)(TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 dst_imv_id)
TNC_Result(* bind_functions)(imc_agent_t *this, TNC_TNCC_BindFunctionPointer bind_function)
TNC_Result(* create_state)(imc_agent_t *this, imc_state_t *state)
TNC_Result(* delete_state)(imc_agent_t *this, TNC_ConnectionID connection_id)
TNC_Result(* change_state)(imc_agent_t *this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imc_state_t **state_p)
bool(* get_state)(imc_agent_t *this, TNC_ConnectionID connection_id, imc_state_t **state)
const char *(* get_name)(imc_agent_t *this)
TNC_IMCID(* get_id)(imc_agent_t *this)
TNC_Result(* reserve_additional_ids)(imc_agent_t *this, int count)
int(* count_additional_ids)(imc_agent_t *this)
enumerator_t *(* create_id_enumerator)(imc_agent_t *this)
void(* add_non_fatal_attr_type)(imc_agent_t *this, pen_type_t type)
linked_list_t *(* get_non_fatal_attr_types)(imc_agent_t *this)
void(* destroy)(imc_agent_t *this)
Detailed Description
Core functions of an Integrity Measurement Verifier (IMC)
Definition at line 39 of file imc_agent.h.
Member Data Documentation
void(* imc_agent_t::add_non_fatal_attr_type)(imc_agent_t *this, pen_type_t type)
Add an item to the list of non-fatal unsupported PA-TNC attribute types
Definition at line 177 of file imc_agent.h.
TNC_Result(* imc_agent_t::bind_functions)(imc_agent_t *this, TNC_TNCC_BindFunctionPointer bind_function)
Bind TNCC functions
Parameters
bind_function function offered by the TNCC
Returns
TNC result code
Definition at line 97 of file imc_agent.h.
Referenced by TNC_IMC_ProvideBindFunction().
TNC_Result(* imc_agent_t::change_state)(imc_agent_t *this, TNC_ConnectionID connection_id, TNC_ConnectionState new_state, imc_state_t **state_p)
Change the current state of a TNCCS connection
Parameters
connection_id network connection ID assigned by TNCS
new_state new state of TNCCS connection
state_p internal IMC state instance [optional argument]
Returns
TNC result code
Definition at line 125 of file imc_agent.h.
Referenced by TNC_IMC_NotifyConnectionChange().
int(* imc_agent_t::count_additional_ids)(imc_agent_t *this)
Return the number of additional IMC IDs assigned by the TNCC
Returns
number of additional IMC IDs
Definition at line 167 of file imc_agent.h.
Referenced by TNC_IMC_BeginHandshake(), and TNC_IMC_NotifyConnectionChange().
enumerator_t*(* imc_agent_t::create_id_enumerator)(imc_agent_t *this)
Create an enumerator for the additional IMC IDs
Definition at line 172 of file imc_agent.h.
Referenced by TNC_IMC_BeginHandshake(), and TNC_IMC_NotifyConnectionChange().
TNC_Result(* imc_agent_t::create_state)(imc_agent_t *this, imc_state_t *state)
Create the IMC state for a TNCCS connection instance
Parameters
state internal IMC state instance
Returns
TNC result code
Definition at line 106 of file imc_agent.h.
Referenced by TNC_IMC_NotifyConnectionChange().
TNC_Result(* imc_agent_t::delete_state)(imc_agent_t *this, TNC_ConnectionID connection_id)
Delete the IMC state for a TNCCS connection instance
Parameters
connection_id network connection ID assigned by TNCS
Returns
TNC result code
Definition at line 114 of file imc_agent.h.
Referenced by TNC_IMC_NotifyConnectionChange().
void(* imc_agent_t::destroy)(imc_agent_t *this)
Destroys an imc_agent_t object
Definition at line 187 of file imc_agent.h.
Referenced by TNC_IMC_Initialize(), and TNC_IMC_Terminate().
TNC_IMCID(* imc_agent_t::get_id)(imc_agent_t *this)
Get base IMC ID
return base IMC ID
Definition at line 152 of file imc_agent.h.
Referenced by imc_msg_create_as_reply(), and imc_msg_create_from_data().
const char*(* imc_agent_t::get_name)(imc_agent_t *this)
Get IMC name
return IMC name
Definition at line 145 of file imc_agent.h.
linked_list_t*(* imc_agent_t::get_non_fatal_attr_types)(imc_agent_t *this)
Get a list of non-fatal unsupported PA-TNC attribute types
Definition at line 182 of file imc_agent.h.
bool(* imc_agent_t::get_state)(imc_agent_t *this, TNC_ConnectionID connection_id, imc_state_t **state)
Get the IMC state for a TNCCS connection instance
Parameters
connection_id network connection ID assigned by TNCS
state internal IMC state instance
Returns
TRUE if the state was found
Definition at line 137 of file imc_agent.h.
Referenced by TNC_IMC_BeginHandshake(), TNC_IMC_ReceiveMessage(), and TNC_IMC_ReceiveMessageLong().
TNC_Result(* imc_agent_t::request_handshake_retry)(TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_RetryReason reason)
Ask a TNCC to retry an Integrity Check Handshake
Parameters
imc_id IMC ID assigned by TNCC
connection_id network connection ID assigned by TNCC
reason IMC retry reason
Returns
TNC result code
Definition at line 49 of file imc_agent.h.
Referenced by TNC_IMC_NotifyConnectionChange().
TNC_Result(* imc_agent_t::reserve_additional_ids)(imc_agent_t *this, int count)
Reserve additional IMC IDs from TNCC
Parameters
count number of additional IMC IDs to be assigned
Returns
TNC result code
Definition at line 160 of file imc_agent.h.
Referenced by TNC_IMC_NotifyConnectionChange().
TNC_Result(* imc_agent_t::send_message)(TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
Call when an IMC-IMC message is to be sent
Parameters
imc_id IMC ID assigned by TNCC
connection_id network connection ID assigned by TNCC
msg message to send
msg_len message length in bytes
msg_type message type
Returns
TNC result code
Definition at line 63 of file imc_agent.h.
TNC_Result(* imc_agent_t::send_message_long)(TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 dst_imv_id)
Call when an IMC-IMC message is to be sent with long message types
Parameters
imc_id IMC ID assigned by TNCC
connection_id network connection ID assigned by TNCC
msg_flags message flags
msg message to send
msg_len message length in bytes
msg_vid message vendor ID
msg_subtype message subtype
dst_imc_id destination IMV ID
Returns
TNC result code
Definition at line 82 of file imc_agent.h.
The documentation for this struct was generated from the following file:
imc_agent.h