strongSwan: ike_sa_id_t Struct Reference
ike_sa_id_t Struct Reference
ike_sa_id
#include "ike_sa_id.h"
Public Attributes
u_int8_t(* get_ike_version)(ike_sa_id_t *this)
void(* set_responder_spi)(ike_sa_id_t *this, u_int64_t responder_spi)
void(* set_initiator_spi)(ike_sa_id_t *this, u_int64_t initiator_spi)
u_int64_t(* get_initiator_spi)(ike_sa_id_t *this)
u_int64_t(* get_responder_spi)(ike_sa_id_t *this)
bool(* equals)(ike_sa_id_t *this, ike_sa_id_t *other)
void(* replace_values)(ike_sa_id_t *this, ike_sa_id_t *other)
bool(* is_initiator)(ike_sa_id_t *this)
bool(* switch_initiator)(ike_sa_id_t *this)
ike_sa_id_t *(* clone)(ike_sa_id_t *this)
void(* destroy)(ike_sa_id_t *this)
Detailed Description
An object of type ike_sa_id_t is used to identify an IKE_SA.
An IKE_SA is identified by its initiator and responder SPIs. Additionally, it contains the major IKE version of the IKE_SA and, for IKEv2, the role of the daemon (original initiator or responder).
Definition at line 37 of file ike_sa_id.h.
Member Data Documentation
ike_sa_id_t*(* ike_sa_id_t::clone)(ike_sa_id_t *this)
Clones a given ike_sa_id_t object.
Returns
cloned ike_sa_id_t object
Definition at line 117 of file ike_sa_id.h.
Referenced by add_matching_ike_sas(), delete_ike_sa_job_create(), dpd_timeout_job_create(), get_or_create_entry(), ike_sa_create(), initiate_callback(), initiate_mediation_job_create(), initiate_tasks_job_create(), METHOD(), peer_create(), put(), put_connected_peers(), reinitiate_mediation_job_create(), rekey_ike_sa_job_create(), rekey_segment(), retransmit_job_create(), retry_initiate_job_create(), send_dpd_job_create(), and send_keepalive_job_create().
void(* ike_sa_id_t::destroy)(ike_sa_id_t *this)
Destroys an ike_sa_id_t object.
Definition at line 122 of file ike_sa_id.h.
Referenced by child_entry_destroy(), linked_list_create(), METHOD(), remove_connected_peers(), remove_specific(), send_check(), and START_TEST().
bool(* ike_sa_id_t::equals)(ike_sa_id_t *this, ike_sa_id_t *other)
Check if two ike_sa_id_t objects are equal.
Two ike_sa_id_t objects are equal if version and both SPI values match. The role is not compared.
Parameters
other ike_sa_id_t object to check if equal
Returns
TRUE if given ike_sa_id_t are equal, FALSE otherwise
Definition at line 86 of file ike_sa_id.h.
Referenced by entry_match_by_id(), equals(), include_filter(), METHOD(), put_connected_peers(), remove_connected_peers(), and remove_specific().
u_int8_t(* ike_sa_id_t::get_ike_version)(ike_sa_id_t *this)
Get the major IKE version of this IKE_SA.
Returns
IKE version
Definition at line 44 of file ike_sa_id.h.
Referenced by entry_match_by_id(), and ike_sa_id_hash().
u_int64_t(* ike_sa_id_t::get_initiator_spi)(ike_sa_id_t *this)
Get the initiator SPI.
Returns
SPI of the initiator
Definition at line 67 of file ike_sa_id.h.
Referenced by add_initial_contact(), build_payloads(), entry_match_by_id(), generate_natd_hash(), ike_sa_id_hash(), list_ike(), METHOD(), and send_notify().
u_int64_t(* ike_sa_id_t::get_responder_spi)(ike_sa_id_t *this)
Get the responder SPI.
Returns
SPI of the responder
Definition at line 74 of file ike_sa_id.h.
Referenced by add_initial_contact(), build_payloads(), entry_match_by_id(), generate_natd_hash(), hash(), ike_sa_id_hash(), list_ike(), METHOD(), receive_packets(), and send_notify().
bool(* ike_sa_id_t::is_initiator)(ike_sa_id_t *this)
Get the initiator flag.
Returns
TRUE if we are the original initiator
Definition at line 103 of file ike_sa_id.h.
Referenced by entry_match_by_id(), ike_sa_id_hash(), list_ike(), METHOD(), process_ike_add(), put_half_open(), receive_packets(), remove_half_open(), and request_query_ikesa().
void(* ike_sa_id_t::replace_values)(ike_sa_id_t *this, ike_sa_id_t *other)
Replace all values of a given ike_sa_id_t object with values from another ike_sa_id_t object.
After calling this function, both objects are equal.
Parameters
other ike_sa_id_t object from which values will be taken
Definition at line 96 of file ike_sa_id.h.
Referenced by METHOD().
void(* ike_sa_id_t::set_initiator_spi)(ike_sa_id_t *this, u_int64_t initiator_spi)
Set the SPI of the initiator.
Parameters
initiator_spi SPI to set
Definition at line 60 of file ike_sa_id.h.
Referenced by METHOD().
void(* ike_sa_id_t::set_responder_spi)(ike_sa_id_t *this, u_int64_t responder_spi)
Set the SPI of the responder.
This function is called when a request or reply of a IKE_SA_INIT is received.
Parameters
responder_spi SPI of responder to set
Definition at line 53 of file ike_sa_id.h.
Referenced by METHOD().
bool(* ike_sa_id_t::switch_initiator)(ike_sa_id_t *this)
Switch the original initiator flag.
Returns
new value if initiator flag.
Definition at line 110 of file ike_sa_id.h.
Referenced by METHOD(), and send_notify().
The documentation for this struct was generated from the following file:
ike_sa_id.h