strongSwan: eap_tnc_plugin.c File Reference
eap_tnc_plugin.c File Reference
#include "eap_tnc_plugin.h"
#include "eap_tnc.h"
#include <daemon.h>
Functions
METHOD (plugin_t, get_name, char *, eap_tnc_plugin_t *this)
METHOD (plugin_t, get_features, int, eap_tnc_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, eap_tnc_plugin_t *this)
plugin_t * eap_tnc_plugin_create ()
Function Documentation
plugin_t* eap_tnc_plugin_create ()
Definition at line 61 of file eap_tnc_plugin.c.
References INIT, and plugin.
 {
     eap_tnc_plugin_t *this;
     INIT(this,
         .plugin = {
             .get_name = _get_name,
             .get_features = _get_features,
             .destroy = _destroy,
         },
     );
     return &this->plugin;
 }
METHOD (plugin_t , get_name , char * , eap_tnc_plugin_t * this)
Definition at line 21 of file eap_tnc_plugin.c.
 {
     return "eap-tnc";
 }
METHOD (plugin_t , get_features , int , eap_tnc_plugin_t * this, plugin_feature_t * features[])
Definition at line 27 of file eap_tnc_plugin.c.
References countof, eap_method_register(), EAP_PEER, EAP_PT_EAP, EAP_SERVER, EAP_TNC, eap_tnc_create_peer(), eap_tnc_create_server(), eap_tnc_pt_create_peer(), eap_tnc_pt_create_server(), EAP_TTLS, PLUGIN_CALLBACK, PLUGIN_DEPENDS, and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(eap_method_register, eap_tnc_create_server),
             PLUGIN_PROVIDE(EAP_SERVER, EAP_TNC),
                 PLUGIN_DEPENDS(EAP_SERVER, EAP_TTLS),
                 PLUGIN_DEPENDS(CUSTOM, "tnccs-manager"),
         PLUGIN_CALLBACK(eap_method_register, eap_tnc_create_peer),
             PLUGIN_PROVIDE(EAP_PEER, EAP_TNC),
                 PLUGIN_DEPENDS(EAP_PEER, EAP_TTLS),
                 PLUGIN_DEPENDS(CUSTOM, "tnccs-manager"),
         PLUGIN_CALLBACK(eap_method_register, eap_tnc_pt_create_server),
             PLUGIN_PROVIDE(EAP_SERVER, EAP_PT_EAP),
                 PLUGIN_DEPENDS(EAP_SERVER, EAP_TTLS),
                 PLUGIN_DEPENDS(CUSTOM, "tnccs-manager"),
         PLUGIN_CALLBACK(eap_method_register, eap_tnc_pt_create_peer),
             PLUGIN_PROVIDE(EAP_PEER, EAP_PT_EAP),
                 PLUGIN_DEPENDS(EAP_PEER, EAP_TTLS),
                 PLUGIN_DEPENDS(CUSTOM, "tnccs-manager"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , eap_tnc_plugin_t * this)
Definition at line 52 of file eap_tnc_plugin.c.
References free().
 {
     free(this);
 }