strongSwan: aead_t Struct Reference
aead_t Struct Reference
aead
#include "aead.h"
Public Attributes
bool(* encrypt)(aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encrypted) __attribute__((warn_unused_result))
bool(* decrypt)(aead_t *this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t *plain)
size_t(* get_block_size)(aead_t *this)
size_t(* get_icv_size)(aead_t *this)
size_t(* get_iv_size)(aead_t *this)
iv_gen_t *(* get_iv_gen)(aead_t *this)
size_t(* get_key_size)(aead_t *this)
bool(* set_key)(aead_t *this, chunk_t key) __attribute__((warn_unused_result))
void(* destroy)(aead_t *this)
Detailed Description
Authenticated encryption / authentication decryption interface.
Definition at line 37 of file aead.h.
Member Data Documentation
bool(* aead_t::decrypt)(aead_t *this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t *plain)
Decrypt and verify data, verify associated data.
The IV must have a length of get_iv_size(). If plain is NULL, the decryption is done inline. The decrypted data is returned in the encrypted chunk, the last get_icv_size() bytes contain the verified ICV.
Parameters
encrypted data to decrypt and verify
assoc associated data to verify
iv initialization vector
plain allocated result, if successful
Returns
TRUE if MAC verification successful
Definition at line 71 of file aead.h.
Referenced by bench_aead(), burn_aead(), CALLBACK(), decrypt_content(), do_test_gcm(), and METHOD().
void(* aead_t::destroy)(aead_t *this)
Destroy an aead_t.
Definition at line 130 of file aead.h.
Referenced by attack_aeads(), bench_aead(), burn_aead(), do_test_gcm(), METHOD(), and START_TEST().
bool(* aead_t::encrypt)(aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encrypted) __attribute__((warn_unused_result))
Encrypt and sign data, sign associated data.
The plain data must be a multiple of get_block_size(), the IV must have a length of get_iv_size(). If encrypted is NULL, the encryption is done inline. The buffer must have space for additional get_icv_size() data, the ICV value is appended silently to the plain chunk.
Parameters
plain data to encrypt and sign
assoc associated data to sign
iv initialization vector
encrypted allocated encryption result
Returns
TRUE if successfully encrypted
Definition at line 54 of file aead.h.
Referenced by attack_aeads(), bench_aead(), burn_aead(), create_aead(), do_test_gcm(), encrypt_content(), and METHOD().
size_t(* aead_t::get_block_size)(aead_t *this)
Get the block size for encryption.
Returns
block size in bytes
Definition at line 79 of file aead.h.
Referenced by burn_aead(), calculate_wire_size(), compute_overhead(), decrypt_and_extract(), decrypt_content(), decrypt_fragment(), encrypt_content(), finalize_message(), generate_iv(), METHOD(), START_TEST(), and tls_aead_create_aead().
size_t(* aead_t::get_icv_size)(aead_t *this)
Get the integrity check value size of the algorithm.
Returns
ICV size in bytes
Definition at line 86 of file aead.h.
Referenced by attack_aeads(), bench_aead(), burn_aead(), calculate_wire_size(), compute_overhead(), decrypt_content(), encrypt_content(), and METHOD().
iv_gen_t*(* aead_t::get_iv_gen)(aead_t *this)
Get the IV generator implementation
Returns
IV generator
Definition at line 100 of file aead.h.
Referenced by encrypt_content(), METHOD(), and START_TEST().
size_t(* aead_t::get_iv_size)(aead_t *this)
Get the size of the initialization vector.
Returns
IV size in bytes
Definition at line 93 of file aead.h.
Referenced by attack_aeads(), bench_aead(), burn_aead(), calculate_wire_size(), CALLBACK(), compute_overhead(), decrypt_content(), do_test_gcm(), encrypt_content(), and METHOD().
size_t(* aead_t::get_key_size)(aead_t *this)
Get the size of the key material (for encryption and authentication).
This includes any additional bytes requires for the implicit nonce part. For AEADs based on traditional ciphers, the length is for both the integrity and the encryption key in total.
Returns
key size in bytes
Definition at line 111 of file aead.h.
Referenced by attack_aeads(), bench_aead(), burn_aead(), derive_ike_aead(), do_test_gcm(), METHOD(), and START_TEST().
bool(* aead_t::set_key)(aead_t *this, chunk_t key) __attribute__((warn_unused_result))
Set the key for encryption and authentication.
If the AEAD uses an implicit nonce, the last part of the key shall be the implicit nonce. For AEADs based on traditional ciphers, the key shall include both integrity and encryption keys, concatenated in that order.
Parameters
key encryption and authentication key
Returns
TRUE if key set successfully
Definition at line 124 of file aead.h.
Referenced by attack_aeads(), bench_aead(), burn_aead(), create_aead(), derive_ike_aead(), do_test_gcm(), METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
aead.h