strongSwan: array
array
collections
Typedefs
typedef struct array_t array_t
typedef enum array_idx_t array_idx_t
typedef void(* array_callback_t)(void *data, int idx, void *user)
Enumerations
enum array_idx_t { ARRAY_HEAD = 0, ARRAY_TAIL = -1 }
Functions
array_t * array_create (u_int esize, u_int8_t reserve)
int array_count (array_t *array)
void array_compress (array_t *array)
enumerator_t * array_create_enumerator (array_t *array)
void array_remove_at (array_t *array, enumerator_t *enumerator)
void array_insert (array_t *array, int idx, void *data)
void array_insert_create (array_t **array, int idx, void *ptr)
void array_insert_enumerator (array_t *array, int idx, enumerator_t *enumerator)
bool array_get (array_t *array, int idx, void *data)
bool array_remove (array_t *array, int idx, void *data)
void array_sort (array_t *array, int(*cmp)(const void *, const void *, void *), void *user)
int array_bsearch (array_t *array, const void *key, int(*cmp)(const void *, const void *), void *data)
void array_invoke (array_t *array, array_callback_t cb, void *user)
void array_invoke_offset (array_t *array, size_t offset)
void array_destroy (array_t *array)
void array_destroy_function (array_t *array, array_callback_t cb, void *user)
void array_destroy_offset (array_t *array, size_t offset)
void arrays_init ()
void arrays_deinit ()
Detailed Description
Typedef Documentation
typedef void(* array_callback_t)(void *data, int idx, void *user)
Callback function invoked for each array element.
Data is a pointer to the array element. If this is a pointer based array, (esize is zero), data is the pointer itself.
Parameters
data pointer to array data, or the pointer itself
idx array index
user user data passed with callback
Definition at line 58 of file array.h.
typedef enum array_idx_t array_idx_t
Definition at line 38 of file array.h.
typedef struct array_t array_t
Variable sized array with fixed size elements.
An array is a primitive object with associated functions to avoid the overhead of an object with methods. It is efficient in memory usage, but less efficient than a linked list in manipulating elements.
Definition at line 36 of file array.h.
Enumeration Type Documentation
enum array_idx_t
Special array index values for insert/remove.
Enumerator
ARRAY_HEAD
ARRAY_TAIL
Definition at line 43 of file array.h.
                  {
     ARRAY_HEAD = 0,
     ARRAY_TAIL = -1,
 };
Function Documentation
int array_bsearch (array_t * array, const void * key, int(*)(const void *, const void *) cmp, void * data)
Binary search of a sorted array.
The array should be sorted in ascending order according to the given comparison function.
The comparison function must return an integer less than, equal to, or greater than zero if the first argument (the key) is considered to be respectively less than, equal to, or greater than the second.
If there are multiple elements that match the key it is not specified which element is returned.
The comparison function receives the key object and a pointer to an array element (esize != 0) or an actual pointer (esize = 0).
Parameters
array array to search, or NULL
key key to search for
cmp comparison function
data data to copy element to, or NULL
Returns
index of the element if found, -1 if not
Definition at line 460 of file array.c.
References array_t::count, data, array_t::data, get_size(), array_t::head, key, memcpy, search_elements(), and start.
Referenced by add_section(), cleanup_sas(), find_section_buffered(), find_sections_buffered(), find_value_buffered(), METHOD(), modular_pluginlist(), section_purge(), send_interim(), settings_kv_add(), settings_section_extend(), START_TEST(), and update_sa().
 {
     int idx = -1;
     if (array)
     {
         bsearch_data_t data = {
             .array = array,
             .key = key,
             .cmp = cmp,
         };
         void *start, *item;
         start = array->data + get_size(array, array->head);
         item = bsearch(&data, start, array->count, get_size(array, 1),
                        search_elements);
         if (item)
         {
             if (out)
             {
                 memcpy(out, item, get_size(array, 1));
             }
             idx = (item - start) / get_size(array, 1);
         }
     }
     return idx;
 }
void array_compress (array_t * array)
Compress an array, remove unused head/tail space.
Parameters
array array to compress, or NULL
Definition at line 185 of file array.c.
References array_t::count, array_t::data, get_size(), array_t::head, memmove, and array_t::tail.
Referenced by array_remove(), build_response(), check_proposal(), generate_message(), merge(), METHOD(), process_response(), and START_TEST().
 {
     if (array)
     {
         u_int32_t tail;
         tail = array->tail;
         if (array->head)
         {
             memmove(array->data, array->data + get_size(array, array->head),
                     get_size(array, array->count + array->tail));
             tail += array->head;
             array->head = 0;
         }
         if (tail)
         {
             array->data = realloc(array->data, get_size(array, array->count));
             array->tail = 0;
         }
     }
 }
int array_count (array_t * array)
Get the number of elements currently in the array.
Returns
number of elements
Definition at line 176 of file array.c.
References array_t::count.
Referenced by add_fragment(), array_get(), array_insert(), array_remove(), CALLBACK(), clear_start_action(), fallback_exists(), find_sections_buffered(), find_value_buffered(), get_reassigned(), is_contained_in(), merge_fragments(), METHOD(), parse_rounds(), print_section(), process_request(), proposal_add_supported_ike(), resolve_also_single(), run_case(), run_suite(), section_purge(), select_signature_schemes(), send_packets(), sign_signature_auth(), START_TEST(), test_runner_run(), thread_cleanup_popall(), and ts_array_equals().
 {
     if (array)
     {
         return array->count;
     }
     return 0;
 }
array_t* array_create (u_int esize, u_int8_t reserve)
Create a array instance.
Elements get tight packed to each other. If any alignment is required, pass appropriate padding to each element. The reserved space does not affect array_count(), but just preallocates buffer space.
Parameters
esize element size for this array, use 0 for a pointer array
reserve number of items to allocate space for
Returns
array instance
Definition at line 161 of file array.c.
References array_t::data, get_size(), INIT, malloc(), and array_t::tail.
Referenced by add_entry(), add_fallback_to_section(), array_from_ts_list(), array_insert_create(), auth_cfg_create(), CALLBACK(), child_sa_create(), cleanup_sas(), collect_stats(), conf_parser_create(), create_internal(), eap_radius_xauth_create_server(), entry_create(), hash_algorithm_set_create(), ike_sa_create(), kernel_netlink_ipsec_create(), kernel_wfp_ipsec_create(), load_suites(), METHOD(), modular_pluginlist(), parser_helper_create(), proposal_create(), resolve_also(), resolve_also_single(), run_case(), select_signature_schemes(), send_once(), settings_create_base(), START_TEST(), task_manager_v2_create(), test_case_create(), and test_suite_create().
 {
     array_t *array;
     INIT(array,
         .esize = esize,
         .tail = reserve,
     );
     if (array->tail)
     {
         array->data = malloc(get_size(array, array->tail));
     }
     return array;
 }
enumerator_t* array_create_enumerator (array_t * array)
Create an enumerator over an array.
The enumerater enumerates directly over the array element (pass a pointer to element types), unless the array is pointer based. If zero is passed as element size during construction, the enumerator enumerates over the dereferenced pointer values.
Parameters
array array to create enumerator for, or NULL
Returns
enumerator, over elements or pointers
Definition at line 242 of file array.c.
References destroy(), enumerator_create_empty(), free(), INIT, and array_enumerator_t::public.
Referenced by activate_task(), apply_filter(), auth_cfg_equals(), build_response(), call_fixture(), CALLBACK(), check_proposal(), cleanup_policies(), cleanup_sas(), create_inner_local(), create_inner_remote(), get_existing(), get_use_time(), handle_collisions(), has_queued(), hash_ts_array(), install_sas(), install_sps(), kv_enumerator(), manage_out(), manage_routes(), METHOD(), migrate_child_tasks(), modular_pluginlist(), process_request(), process_response(), resolve_also_single(), run_case(), run_suite(), section_enumerator(), send_interim(), send_packets(), send_stop(), settings_section_extend(), sign_signature_auth(), START_TEST(), test_runner_run(), trigger_mbb_reauth(), ts_array_equals(), and unregister_event().
 {
     array_enumerator_t *enumerator;
     if (!array)
     {
         return enumerator_create_empty();
     }
     INIT(enumerator,
         .public = {
             .enumerate = (void*)_enumerate,
             .destroy = (void*)free,
         },
         .array = array,
     );
     return &enumerator->public;
 }
void array_destroy (array_t * array)
Destroy an array.
Parameters
array array to destroy, or NULL
Definition at line 532 of file array.c.
References array_t::data, and free().
Referenced by array_destroy_function(), array_destroy_offset(), CALLBACK(), clear_start_action(), destroy(), destroy_suite(), entry_destroy(), enumerator_destroy(), METHOD(), modular_pluginlist(), resolve_also(), resolve_also_single(), run_case(), section_destroy(), section_purge(), send_notify(), settings_parser_parse_file(), settings_parser_parse_string(), settings_section_destroy(), settings_section_extend(), sign_signature_auth(), START_TEST(), and unload_suites().
 {
     if (array)
     {
         free(array->data);
         free(array);
     }
 }
void array_destroy_function (array_t * array, array_callback_t cb, void * user)
Destroy an array, call a function to clean up all elements.
Parameters
array array to destroy, or NULL
cb callback function to free element data
user user data to pass to callback
Definition at line 541 of file array.c.
References array_destroy(), and array_invoke().
Referenced by cleanup_sas(), destroy_entry(), entry_destroy(), METHOD(), modular_pluginlist(), pool_destroy(), reset_defrag(), section_destroy(), section_purge(), send_interim(), and settings_section_destroy().
 {
     array_invoke(array, cb, user);
     array_destroy(array);
 }
void array_destroy_offset (array_t * array, size_t offset)
Destroy an array, call element method defined with offset.
Parameters
array array to destroy, or NULL
offset offset of element method, use offsetof()
Definition at line 547 of file array.c.
References array_destroy(), and array_invoke_offset().
Referenced by clear_fragments(), entry_destroy(), METHOD(), and reqid_entry_destroy().
 {
     array_invoke_offset(array, offset);
     array_destroy(array);
 }
bool array_get (array_t * array, int idx, void * data)
Get an element from the array.
If data is given, the element is copied to that position.
Parameters
array array to get element from, or NULL
idx index of the item to get
data data to copy element to, or NULL
Returns
TRUE if idx valid and item returned
Definition at line 332 of file array.c.
References array_count(), array_t::data, FALSE, get_size(), array_t::head, memcpy, and TRUE.
Referenced by add_fragment(), add_section(), add_setting(), array_remove(), current_file(), do_write(), fallback_exists(), find_sections_buffered(), find_value_buffered(), is_contained_in(), merge_fragments(), METHOD(), print_section(), resolve_also_single(), retransmit_packet(), section_purge(), select_signature_schemes(), send_packets(), and START_TEST().
 {
     if (!array)
     {
         return FALSE;
     }
     if (idx >= 0 && idx >= array_count(array))
     {
         return FALSE;
     }
     if (idx < 0)
     {
         if (array_count(array) == 0)
         {
             return FALSE;
         }
         idx = array_count(array) - 1;
     }
     if (data)
     {
         memcpy(data, array->data + get_size(array, array->head + idx),
                get_size(array, 1));
     }
     return TRUE;
 }
void array_insert (array_t * array, int idx, void * data)
Insert an element to an array.
If the array is pointer based (esize = 0), the pointer itself is appended. Otherwise the element gets copied from the pointer. The idx must be either within array_count() or one above to append the item. Passing -1 has the same effect as passing array_count(), i.e. appends the item. It is always valid to pass idx 0 to prepend the item.
Parameters
array array to append element to
idx index to insert item at
data pointer to array element to copy
Definition at line 291 of file array.c.
References array_count(), array_t::data, array_t::esize, get_size(), array_t::head, insert_head(), insert_tail(), memcpy, and array_t::tail.
Referenced by activate_task(), add(), add_entry(), add_fragment(), add_port_bypass(), array_from_ts_list(), array_insert_create(), array_insert_enumerator(), CALLBACK(), cleanup_sas(), collect_failure_info(), collect_stats(), get_existing(), get_new(), get_reassigned(), load_suites(), merge(), METHOD(), migrate_child_tasks(), modular_pluginlist(), parse_rounds(), parser_helper_create(), process_request(), push_section(), queue(), register_event(), report_leaks(), resolve_also_single(), select_signature_schemes(), settings_kv_destroy(), settings_kv_set(), settings_section_extend(), START_TEST(), test_case_add_checked_fixture(), test_case_add_test_name(), test_suite_add_case(), and thread_cleanup_push().
 {
     if (idx < 0 || idx <= array_count(array))
     {
         void *pos;
         if (idx < 0)
         {
             idx = array_count(array);
         }
         if (array->head && !array->tail)
         {
             insert_head(array, idx);
         }
         else if (array->tail && !array->head)
         {
             insert_tail(array, idx);
         }
         else if (idx > array_count(array) / 2)
         {
             insert_tail(array, idx);
         }
         else
         {
             insert_head(array, idx);
         }
         pos = array->data + get_size(array, array->head + idx);
         if (array->esize)
         {
             memcpy(pos, data, get_size(array, 1));
         }
         else
         {
             /* pointer based array, copy pointer value */
             *(void**)pos = data;
         }
     }
 }
void array_insert_create (array_t ** array, int idx, void * ptr)
Create an pointer based array if it does not exist, insert pointer.
This is a convenience function for insert a pointer and implicitly create a pointer based array if array is NULL. Array is set the the newly created array, if any.
Parameters
array pointer to array reference, potentially NULL
idx index to insert item at
ptr pointer to append
Definition at line 271 of file array.c.
References array_create(), and array_insert().
Referenced by add_fallback_to_section(), add_section(), CALLBACK(), clear_start_action(), find_sections_buffered(), generate_message(), METHOD(), resolve_also_single(), settings_kv_add(), settings_parser_parse_file(), settings_parser_parse_string(), settings_section_extend(), and update_sa().
 {
     if (*array == NULL)
     {
         *array = array_create(0, 0);
     }
     array_insert(*array, idx, ptr);
 }
void array_insert_enumerator (array_t * array, int idx, enumerator_t * enumerator)
Insert all items from an enumerator to an array.
Parameters
array array to add items to
idx index to insert each item with
enumerator enumerator over void*, gets destroyed
Definition at line 280 of file array.c.
References array_insert(), enumerator_t::destroy, and enumerator_t::enumerate.
 {
     void *ptr;
     while (enumerator->enumerate(enumerator, &ptr))
     {
         array_insert(array, idx, ptr);
     }
     enumerator->destroy(enumerator);
 }
void array_invoke (array_t * array, array_callback_t cb, void * user)
Invoke a callback for all array members.
Parameters
array array to traverse, or NULL
cb callback function to invoke each element with
user user data to pass to callback
Definition at line 490 of file array.c.
References cb(), count, array_t::data, array_t::esize, get_size(), and array_t::head.
Referenced by array_destroy_function(), and START_TEST().
 {
     if (array)
     {
         void *obj;
         int i;
         for (i = array->head; i < array->count + array->head; i++)
         {
             obj = array->data + get_size(array, i);
             if (!array->esize)
             {
                 /* dereference if we store store pointers */
                 obj = *(void**)obj;
             }
             cb(obj, i - array->head, user);
         }
     }
 }
void array_invoke_offset (array_t * array, size_t offset)
Invoke a method of each element defined with offset.
Parameters
array array to traverse, or NULL
offset offset of element method, use offsetof()
Definition at line 510 of file array.c.
References count, data, array_t::data, array_t::esize, get_size(), and array_t::head.
Referenced by array_destroy_offset(), and START_TEST().
 {
     if (array)
     {
         void (*method)(void *data);
         void *obj;
         int i;
         for (i = array->head; i < array->count + array->head; i++)
         {
             obj = array->data + get_size(array, i);
             if (!array->esize)
             {
                 /* dereference if we store store pointers */
                 obj = *(void**)obj;
             }
             method = *(void**)(obj + offset);
             method(obj);
         }
     }
 }
bool array_remove (array_t * array, int idx, void * data)
Remove an element from the array.
If data is given, the element is copied to that position.
Parameters
array array to remove element from, or NULL
idx index of the item to remove
data data to copy element to, or NULL
Returns
TRUE if idx existed and item removed
Definition at line 358 of file array.c.
References array_compress(), array_count(), array_get(), ARRAY_MAX_UNUSED, FALSE, array_t::head, remove_head(), remove_tail(), array_t::tail, and TRUE.
Referenced by array_remove_at(), build_round(), CALLBACK(), clear_packets(), clear_start_action(), destroy_suite(), do_write(), docleanup(), flush_auth_cfgs(), get_reassigned(), merge(), METHOD(), pop_section(), print_failures(), resolve_also_single(), section_purge(), send_once(), settings_section_extend(), START_TEST(), thread_cleanup_pop(), thread_cleanup_popall(), and unload_suites().
 {
     if (!array_get(array, idx, data))
     {
         return FALSE;
     }
     if (idx < 0)
     {
         idx = array_count(array) - 1;
     }
     if (idx > array_count(array) / 2)
     {
         remove_tail(array, idx);
     }
     else
     {
         remove_head(array, idx);
     }
     if (array->head + array->tail > ARRAY_MAX_UNUSED)
     {
         array_compress(array);
     }
     return TRUE;
 }
void array_remove_at (array_t * array, enumerator_t * enumerator)
Remove an element at enumerator position.
Warning
For value based arrays don't use the pointer returned by enumerate() anymore after calling this function. For performance reasons that pointer will point to internal data structures that get modified when this function is called.
Parameters
array array to remove element in
enumerator enumerator position, from array_create_enumerator()
Definition at line 261 of file array.c.
References array_remove(), and array_enumerator_t::idx.
Referenced by activate_task(), apply_filter(), build_response(), CALLBACK(), check_proposal(), cleanup_sas(), get_existing(), METHOD(), migrate_child_tasks(), process_request(), process_response(), resolve_also_single(), send_interim(), settings_section_extend(), START_TEST(), trigger_mbb_reauth(), and unregister_event().
 {
     array_enumerator_t *enumerator = (array_enumerator_t*)public;
     if (enumerator->idx)
     {
         array_remove(array, --enumerator->idx, NULL);
     }
 }
void array_sort (array_t * array, int(*)(const void *, const void *, void *) cmp, void * user)
Sort the array.
The comparison function must return an integer less than, equal to, or greater than zero if the first argument is considered to be respectively less than, equal to, or greater than the second. If two elements compare as equal, their order in the sorted array is undefined.
The comparison function receives pointers to the array elements (esize != 0) or the actual pointers (esize = 0). The third argument is the user data supplied to this function.
Parameters
array array to sort, or NULL
cmp comparison function
user user data to pass to comparison function
Definition at line 413 of file array.c.
References compare_elements(), array_t::count, data, array_t::data, get_size(), array_t::head, thread_value_t::set, and start.
Referenced by add_section(), cleanup_sas(), collect_stats(), METHOD(), modular_pluginlist(), settings_kv_add(), settings_section_extend(), START_TEST(), and update_sa().
 {
     if (array)
     {
         sort_data_t data = {
             .array = array,
             .cmp = cmp,
             .arg = user,
         };
         void *start;
         start = array->data + get_size(array, array->head);
 #ifdef HAVE_QSORT_R_GNU
         qsort_r(start, array->count, get_size(array, 1), compare_elements,
                 &data);
 #elif defined(HAVE_QSORT_R_BSD)
         qsort_r(start, array->count, get_size(array, 1), &data,
                 compare_elements);
 #else /* !HAVE_QSORT_R */
         sort_data->set(sort_data, &data);
         qsort(start, array->count, get_size(array, 1), compare_elements);
 #endif
     }
 }
void arrays_deinit ()
Destroys the thread local value if required.
Definition at line 560 of file array.c.
References thread_value_t::destroy.
Referenced by library_deinit().
 {
 #ifndef HAVE_QSORT_R
     sort_data->destroy(sort_data);
 #endif
 }
void arrays_init ()
Required on some platforms to initialize thread local value to implement array_sort().
Definition at line 553 of file array.c.
References thread_value_create().
Referenced by library_init().
 {
 #ifndef HAVE_QSORT_R
     sort_data =  thread_value_create(NULL);
 #endif
 }