strongSwan: sha1_prf.c File Reference
sha1_prf.c File Reference
#include "sha1_prf.h"
#include "sha1_hasher.h"
#include <library.h>
Classes
struct private_sha1_hasher_t
struct private_sha1_prf_t
Typedefs
typedef struct private_sha1_prf_t private_sha1_prf_t
typedef struct
private_sha1_hasher_t private_sha1_hasher_t
Functions
void SHA1Update (private_sha1_hasher_t *this, u_int8_t *data, u_int32_t len)
METHOD (prf_t, get_bytes, bool, private_sha1_prf_t *this, chunk_t seed, u_int8_t *bytes)
METHOD (prf_t, get_block_size, size_t, private_sha1_prf_t *this)
METHOD (prf_t, allocate_bytes, bool, private_sha1_prf_t *this, chunk_t seed, chunk_t *chunk)
METHOD (prf_t, get_key_size, size_t, private_sha1_prf_t *this)
METHOD (prf_t, set_key, bool, private_sha1_prf_t *this, chunk_t key)
METHOD (prf_t, destroy, void, private_sha1_prf_t *this)
sha1_prf_t * sha1_prf_create (pseudo_random_function_t algo)
Typedef Documentation
typedef struct private_sha1_hasher_t private_sha1_hasher_t
Definition at line 22 of file sha1_prf.c.
typedef struct private_sha1_prf_t private_sha1_prf_t
Definition at line 21 of file sha1_prf.c.
Function Documentation
METHOD (prf_t , get_bytes , bool , private_sha1_prf_t * this, chunk_t seed, u_int8_t * bytes)
Definition at line 62 of file sha1_prf.c.
References hash, hasher, chunk_t::len, chunk_t::ptr, SHA1Update(), and TRUE.
 {
     u_int32_t *hash = (u_int32_t*)bytes;
     SHA1Update(this->hasher, seed.ptr, seed.len);
     hash[0] = htonl(this->hasher->state[0]);
     hash[1] = htonl(this->hasher->state[1]);
     hash[2] = htonl(this->hasher->state[2]);
     hash[3] = htonl(this->hasher->state[3]);
     hash[4] = htonl(this->hasher->state[4]);
     return TRUE;
 }
METHOD (prf_t , get_block_size , size_t , private_sha1_prf_t * this)
Definition at line 78 of file sha1_prf.c.
References HASH_SIZE_SHA1.
 {
     return HASH_SIZE_SHA1;
 }
METHOD (prf_t , allocate_bytes , bool , private_sha1_prf_t * this, chunk_t seed, chunk_t * chunk)
Definition at line 84 of file sha1_prf.c.
References chunk_alloc, HASH_SIZE_SHA1, and chunk_t::ptr.
 {
     *chunk = chunk_alloc(HASH_SIZE_SHA1);
     return get_bytes(this, seed, chunk->ptr);
 }
METHOD (prf_t , get_key_size , size_t , private_sha1_prf_t * this)
Definition at line 91 of file sha1_prf.c.
References hasher.
 {
     return sizeof(this->hasher->state);
 }
METHOD (prf_t , set_key , bool , private_sha1_prf_t * this, chunk_t key)
Definition at line 97 of file sha1_prf.c.
References FALSE, hasher, if(), chunk_t::len, min, chunk_t::ptr, and TRUE.
 {
     int i, rounds;
     u_int32_t *iv = (u_int32_t*)key.ptr;
     if (!this->hasher->public.hasher_interface.reset(
                                         &this->hasher->public.hasher_interface))
     {
         return FALSE;
     }
     rounds = min(key.len/sizeof(u_int32_t), sizeof(this->hasher->state));
     for (i = 0; i < rounds; i++)
     {
         this->hasher->state[i] ^= htonl(iv[i]);
     }
     return TRUE;
 }
METHOD (prf_t , destroy , void , private_sha1_prf_t * this)
Definition at line 116 of file sha1_prf.c.
References free(), and hasher.
 {
     this->hasher->public.hasher_interface.destroy(&this->hasher->public.hasher_interface);
     free(this);
 }
void SHA1Update (private_sha1_hasher_t * this, u_int8_t * data, u_int32_t len)
From sha1_hasher.c
Run your data through this. Also used in sha1_prf.
Definition at line 121 of file sha1_hasher.c.
References count, len, memcpy, and SHA1Transform().
Referenced by METHOD(), and SHA1Final().
 {
     u_int32_t i;
     u_int32_t j;
     j = this->count[0];
     if ((this->count[0] += len << 3) < j)
     {
         this->count[1]++;
     }
     this->count[1] += (len>>29);
     j = (j >> 3) & 63;
     if ((j + len) > 63)
     {
         memcpy(&this->buffer[j], data, (i = 64-j));
         SHA1Transform(this->state, this->buffer);
         for ( ; i + 63 < len; i += 64)
         {
             SHA1Transform(this->state, &data[i]);
         }
         j = 0;
     }
     else
     {
         i = 0;
     }
     memcpy(&this->buffer[j], &data[i], len - i);
 }