strongSwan: imc_test_state
imc_test_state
imc_test
Classes
struct imc_test_state_t
Typedefs
typedef struct imc_test_state_t imc_test_state_t
Functions
imc_state_t * imc_test_state_create (TNC_ConnectionID id, char *command, int dummy_size, bool retry)
Detailed Description
Typedef Documentation
typedef struct imc_test_state_t imc_test_state_t
Definition at line 30 of file imc_test_state.h.
Function Documentation
imc_state_t* imc_test_state_create (TNC_ConnectionID connection_id, char * command, int dummy_size, bool retry)
Create an imc_test_state_t instance
Parameters
id connection ID
command command to send to IMV
dummy_size size of the dummy attribute to send (only if > 0)
retry TRUE if a handshake retry should be done
Described in header.
Definition at line 262 of file imc_test_state.c.
References INIT, linked_list_create(), seg_contract_manager_create(), strdup, TNC_CONNECTION_STATE_CREATE, and TRUE.
Referenced by TNC_IMC_NotifyConnectionChange().
 {
     private_imc_test_state_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_connection_id = _get_connection_id,
                 .has_long = _has_long,
                 .has_excl = _has_excl,
                 .set_flags = _set_flags,
                 .set_max_msg_len = _set_max_msg_len,
                 .get_max_msg_len = _get_max_msg_len,
                 .get_contracts = _get_contracts,
                 .change_state = _change_state,
                 .set_result = _set_result,
                 .get_result = _get_result,
                 .destroy = _destroy,
             },
             .get_command = _get_command,
             .set_command = _set_command,
             .get_dummy_size = _get_dummy_size,
             .is_first_handshake = _is_first_handshake,
             .do_handshake_retry = _do_handshake_retry,
         },
         .state = TNC_CONNECTION_STATE_CREATE,
         .results = linked_list_create(),
         .connection_id = connection_id,
         .contracts = seg_contract_manager_create(),
         .command = strdup(command),
         .dummy_size = dummy_size,
         .first_handshake = TRUE,
         .handshake_retry = retry,
     );
     return &this->public.interface;
 }