strongSwan: ike_cfg.c File Reference
ike_cfg.c File Reference
#include <string.h>
#include "ike_cfg.h"
#include <daemon.h>
Classes
struct private_ike_cfg_t
Macros
#define _GNU_SOURCE /* for stdndup() */
Typedefs
typedef struct private_ike_cfg_t private_ike_cfg_t
Functions
ENUM (ike_version_names, IKE_ANY, IKEV2,"IKEv1/2","IKEv1","IKEv2",)
METHOD (ike_cfg_t, get_version, ike_version_t, private_ike_cfg_t *this)
METHOD (ike_cfg_t, send_certreq, bool, private_ike_cfg_t *this)
METHOD (ike_cfg_t, force_encap_, bool, private_ike_cfg_t *this)
METHOD (ike_cfg_t, fragmentation, fragmentation_t, private_ike_cfg_t *this)
static host_t * resolve (linked_list_t *hosts, int family, u_int16_t port)
METHOD (ike_cfg_t, resolve_me, host_t *, private_ike_cfg_t *this, int family)
METHOD (ike_cfg_t, resolve_other, host_t *, private_ike_cfg_t *this, int family)
static u_int match (linked_list_t *hosts, linked_list_t *ranges, host_t *cand)
METHOD (ike_cfg_t, match_me, u_int, private_ike_cfg_t *this, host_t *host)
METHOD (ike_cfg_t, match_other, u_int, private_ike_cfg_t *this, host_t *host)
METHOD (ike_cfg_t, get_my_addr, char *, private_ike_cfg_t *this)
METHOD (ike_cfg_t, get_other_addr, char *, private_ike_cfg_t *this)
METHOD (ike_cfg_t, get_my_port, u_int16_t, private_ike_cfg_t *this)
METHOD (ike_cfg_t, get_other_port, u_int16_t, private_ike_cfg_t *this)
METHOD (ike_cfg_t, get_dscp, u_int8_t, private_ike_cfg_t *this)
METHOD (ike_cfg_t, add_proposal, void, private_ike_cfg_t *this, proposal_t *proposal)
METHOD (ike_cfg_t, get_proposals, linked_list_t *, private_ike_cfg_t *this)
METHOD (ike_cfg_t, select_proposal, proposal_t *, private_ike_cfg_t *this, linked_list_t *proposals, bool private)
METHOD (ike_cfg_t, get_dh_group, diffie_hellman_group_t, private_ike_cfg_t *this)
METHOD (ike_cfg_t, equals, bool, private_ike_cfg_t *this, ike_cfg_t *other_public)
METHOD (ike_cfg_t, get_ref, ike_cfg_t *, private_ike_cfg_t *this)
METHOD (ike_cfg_t, destroy, void, private_ike_cfg_t *this)
static traffic_selector_t * make_subnet (char *str)
static traffic_selector_t * make_range (char *str)
static void parse_addresses (char *str, linked_list_t *hosts, linked_list_t *ranges)
int ike_cfg_get_family (ike_cfg_t *cfg, bool local)
ike_cfg_t * ike_cfg_create (ike_version_t version, bool certreq, bool force_encap, char *me, u_int16_t my_port, char *other, u_int16_t other_port, fragmentation_t fragmentation, u_int8_t dscp)
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 18 of file ike_cfg.c.
Typedef Documentation
typedef struct private_ike_cfg_t private_ike_cfg_t
Definition at line 31 of file ike_cfg.c.
Function Documentation
ENUM (ike_version_names , IKE_ANY , IKEV2 , "IKEv1/2" , "IKEv1" , "IKEv2")
static traffic_selector_t* make_range (char * str) static
Try to parse a string as an IP range
Definition at line 459 of file ike_cfg.c.
References host_t::destroy, from, host_t::get_address, host_t::get_family, host_create_from_range(), to, traffic_selector_create_from_bytes(), TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
Referenced by parse_addresses().
 {
     traffic_selector_t *ts;
     ts_type_t type;
     host_t *from, *to;
     if (!host_create_from_range(str, &from, &to))
     {
         return NULL;
     }
     if (to->get_family(to) == AF_INET)
     {
         type = TS_IPV4_ADDR_RANGE;
     }
     else
     {
         type = TS_IPV6_ADDR_RANGE;
     }
     ts = traffic_selector_create_from_bytes(0, type,
                                             from->get_address(from), 0,
                                             to->get_address(to), 0);
     from->destroy(from);
     to->destroy(to);
     return ts;
 }
static traffic_selector_t* make_subnet (char * str) static
Try to parse a string as subnet
Definition at line 444 of file ike_cfg.c.
References traffic_selector_create_from_cidr().
Referenced by parse_addresses().
 {
     char *pos;
     pos = strchr(str, '/');
     if (!pos)
     {
         return NULL;
     }
     return traffic_selector_create_from_cidr(str, 0, 0, 0);
 }
static u_int match (linked_list_t * hosts, linked_list_t * ranges, host_t * cand) static
Common function for match_me/other
Definition at line 189 of file ike_cfg.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, host_t::destroy, enumerator_t::enumerate, host_t::get_family, host, host_create_from_dns(), traffic_selector_t::includes, host_t::ip_equals, host_t::is_anyaddr, mask, max, str, and traffic_selector_t::to_subnet.
Referenced by assign_arg(), collect_tags(), common_prefix(), dn_matches(), do_netstat(), get_entry_by_match_function(), get_ike_match(), get_peer_match(), get_ts_match(), has_owner(), id_matches(), id_matches_rev(), imv_lang_string_select_lang(), load_imcvs_from_config(), load_secrets(), METHOD(), pem_to_bin(), process_header(), and translate().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     char *str;
     host_t *host;
     u_int8_t mask;
     u_int quality = 0;
     /* try single hosts first */
     enumerator = hosts->create_enumerator(hosts);
     while (enumerator->enumerate(enumerator, &str))
     {
         host = host_create_from_dns(str, cand->get_family(cand), 0);
         if (host)
         {
             if (host->ip_equals(host, cand))
             {
                 quality = max(quality, 128 + 1);
             }
             if (host->is_anyaddr(host))
             {
                 quality = max(quality, 1);
             }
             host->destroy(host);
         }
     }
     enumerator->destroy(enumerator);
     /* then ranges/subnets */
     enumerator = ranges->create_enumerator(ranges);
     while (enumerator->enumerate(enumerator, &ts))
     {
         if (ts->includes(ts, cand))
         {
             if (ts->to_subnet(ts, &host, &mask))
             {
                 quality = max(quality, mask + 1);
                 host->destroy(host);
             }
             else
             {
                 quality = max(quality, 1);
             }
         }
     }
     enumerator->destroy(enumerator);
     return quality;
 }
METHOD (ike_cfg_t , get_version , ike_version_t , private_ike_cfg_t * this)
Definition at line 119 of file ike_cfg.c.
References version.
 {
     return this->version;
 }
METHOD (ike_cfg_t , send_certreq , bool , private_ike_cfg_t * this)
Definition at line 125 of file ike_cfg.c.
 {
     return this->certreq;
 }
METHOD (ike_cfg_t , force_encap_ , bool , private_ike_cfg_t * this)
Definition at line 131 of file ike_cfg.c.
References force_encap().
 {
     return this->force_encap;
 }
METHOD (ike_cfg_t , fragmentation , fragmentation_t , private_ike_cfg_t * this)
Definition at line 137 of file ike_cfg.c.
 {
     return this->fragmentation;
 }
METHOD (ike_cfg_t , resolve_me , host_t * , private_ike_cfg_t * this, int family)
Definition at line 174 of file ike_cfg.c.
References resolve().
 {
     return resolve(this->my_hosts, family, this->my_port);
 }
METHOD (ike_cfg_t , resolve_other , host_t * , private_ike_cfg_t * this, int family)
Definition at line 180 of file ike_cfg.c.
References resolve().
 {
     return resolve(this->other_hosts, family, this->other_port);
 }
METHOD (ike_cfg_t , match_me , u_int , private_ike_cfg_t * this, host_t * host)
Definition at line 240 of file ike_cfg.c.
References match().
 {
     return match(this->my_hosts, this->my_ranges, host);
 }
METHOD (ike_cfg_t , match_other , u_int , private_ike_cfg_t * this, host_t * host)
Definition at line 246 of file ike_cfg.c.
References match().
 {
     return match(this->other_hosts, this->other_ranges, host);
 }
METHOD (ike_cfg_t , get_my_addr , char * , private_ike_cfg_t * this)
Definition at line 252 of file ike_cfg.c.
References me.
 {
     return this->me;
 }
METHOD (ike_cfg_t , get_other_addr , char * , private_ike_cfg_t * this)
Definition at line 258 of file ike_cfg.c.
 {
     return this->other;
 }
METHOD (ike_cfg_t , get_my_port , u_int16_t , private_ike_cfg_t * this)
Definition at line 264 of file ike_cfg.c.
 {
     return this->my_port;
 }
METHOD (ike_cfg_t , get_other_port , u_int16_t , private_ike_cfg_t * this)
Definition at line 270 of file ike_cfg.c.
 {
     return this->other_port;
 }
METHOD (ike_cfg_t , get_dscp , u_int8_t , private_ike_cfg_t * this)
Definition at line 276 of file ike_cfg.c.
 {
     return this->dscp;
 }
METHOD (ike_cfg_t , add_proposal , void , private_ike_cfg_t * this, proposal_t * proposal)
Definition at line 282 of file ike_cfg.c.
 {
     if (proposal)
     {
         this->proposals->insert_last(this->proposals, proposal);
     }
 }
METHOD (ike_cfg_t , get_proposals , linked_list_t * , private_ike_cfg_t * this)
Definition at line 291 of file ike_cfg.c.
References proposal_t::clone, linked_list_t::create_enumerator, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, and linked_list_create().
 {
     enumerator_t *enumerator;
     proposal_t *current;
     linked_list_t *proposals;
     proposals = linked_list_create();
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, &current))
     {
         current = current->clone(current);
         proposals->insert_last(proposals, current);
     }
     enumerator->destroy(enumerator);
     DBG2(DBG_CFG, "configured proposals: %#P", proposals);
     return proposals;
 }
METHOD (ike_cfg_t , select_proposal , proposal_t * , private_ike_cfg_t * this, linked_list_t * proposals, bool private)
Definition at line 312 of file ike_cfg.c.
References linked_list_t::create_enumerator, DBG1, DBG2, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, linked_list_t::reset_enumerator, and proposal_t::select.
 {
     enumerator_t *stored_enum, *supplied_enum;
     proposal_t *stored, *supplied, *selected;
     stored_enum = this->proposals->create_enumerator(this->proposals);
     supplied_enum = proposals->create_enumerator(proposals);
     /* compare all stored proposals with all supplied. Stored ones are preferred.*/
     while (stored_enum->enumerate(stored_enum, (void**)&stored))
     {
         proposals->reset_enumerator(proposals, supplied_enum);
         while (supplied_enum->enumerate(supplied_enum, (void**)&supplied))
         {
             selected = stored->select(stored, supplied, private);
             if (selected)
             {
                 /* they match, return */
                 stored_enum->destroy(stored_enum);
                 supplied_enum->destroy(supplied_enum);
                 DBG2(DBG_CFG, "received proposals: %#P", proposals);
                 DBG2(DBG_CFG, "configured proposals: %#P", this->proposals);
                 DBG2(DBG_CFG, "selected proposal: %P", selected);
                 return selected;
             }
         }
     }
     /* no proposal match :-(, will result in a NO_PROPOSAL_CHOSEN... */
     stored_enum->destroy(stored_enum);
     supplied_enum->destroy(supplied_enum);
     DBG1(DBG_CFG, "received proposals: %#P", proposals);
     DBG1(DBG_CFG, "configured proposals: %#P", this->proposals);
     return NULL;
 }
METHOD (ike_cfg_t , get_dh_group , diffie_hellman_group_t , private_ike_cfg_t * this)
Definition at line 351 of file ike_cfg.c.
References enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, enumerator_t::enumerate, proposal_t::get_algorithm, MODP_NONE, and proposal.
 {
     enumerator_t *enumerator;
     proposal_t *proposal;
     u_int16_t dh_group = MODP_NONE;
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, &proposal))
     {
         if (proposal->get_algorithm(proposal, DIFFIE_HELLMAN_GROUP, &dh_group, NULL))
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return dh_group;
 }
METHOD (ike_cfg_t , equals , bool , private_ike_cfg_t * this, ike_cfg_t * other_public)
Definition at line 370 of file ike_cfg.c.
References private_ike_cfg_t::certreq, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, equals(), proposal_t::equals, ike_cfg_t::equals, FALSE, private_ike_cfg_t::force_encap, private_ike_cfg_t::fragmentation, linked_list_t::get_count, private_ike_cfg_t::me, me, private_ike_cfg_t::my_port, private_ike_cfg_t::other, private_ike_cfg_t::other_port, private_ike_cfg_t::proposals, private_ike_cfg_t::public, streq(), TRUE, private_ike_cfg_t::version, and version.
 {
     private_ike_cfg_t *other = (private_ike_cfg_t*)other_public;
     enumerator_t *e1, *e2;
     proposal_t *p1, *p2;
     bool eq = TRUE;
     if (this == other)
     {
         return TRUE;
     }
     if (this->public.equals != other->public.equals)
     {
         return FALSE;
     }
     if (this->proposals->get_count(this->proposals) !=
         other->proposals->get_count(other->proposals))
     {
         return FALSE;
     }
     e1 = this->proposals->create_enumerator(this->proposals);
     e2 = other->proposals->create_enumerator(other->proposals);
     while (e1->enumerate(e1, &p1) && e2->enumerate(e2, &p2))
     {
         if (!p1->equals(p1, p2))
         {
             eq = FALSE;
             break;
         }
     }
     e1->destroy(e1);
     e2->destroy(e2);
     return (eq &&
         this->version == other->version &&
         this->certreq == other->certreq &&
         this->force_encap == other->force_encap &&
         this->fragmentation == other->fragmentation &&
         streq(this->me, other->me) &&
         streq(this->other, other->other) &&
         this->my_port == other->my_port &&
         this->other_port == other->other_port);
 }
METHOD (ike_cfg_t , get_ref , ike_cfg_t * , private_ike_cfg_t * this)
Definition at line 415 of file ike_cfg.c.
References ref_get().
 {
     ref_get(&this->refcount);
     return &this->public;
 }
METHOD (ike_cfg_t , destroy , void , private_ike_cfg_t * this)
Definition at line 422 of file ike_cfg.c.
References destroy(), free(), me, and ref_put().
 {
     if (ref_put(&this->refcount))
     {
         this->proposals->destroy_offset(this->proposals,
                                         offsetof(proposal_t, destroy));
         free(this->me);
         free(this->other);
         this->my_hosts->destroy_function(this->my_hosts, free);
         this->other_hosts->destroy_function(this->other_hosts, free);
         this->my_ranges->destroy_offset(this->my_ranges,
                                         offsetof(traffic_selector_t, destroy));
         this->other_ranges->destroy_offset(this->other_ranges,
                                         offsetof(traffic_selector_t, destroy));
         free(this);
     }
 }
static void parse_addresses (char * str, linked_list_t * hosts, linked_list_t * ranges) static
Parse address string into lists of single hosts and ranges/subnets
Definition at line 488 of file ike_cfg.c.
References enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), linked_list_t::insert_last, make_range(), make_subnet(), and strdup.
Referenced by ike_cfg_create().
 {
     enumerator_t *enumerator;
     traffic_selector_t *ts;
     enumerator = enumerator_create_token(str, ",", " ");
     while (enumerator->enumerate(enumerator, &str))
     {
         ts = make_subnet(str);
         if (ts)
         {
             ranges->insert_last(ranges, ts);
             continue;
         }
         ts = make_range(str);
         if (ts)
         {
             ranges->insert_last(ranges, ts);
             continue;
         }
         hosts->insert_last(hosts, strdup(str));
     }
     enumerator->destroy(enumerator);
 }
static host_t* resolve (linked_list_t * hosts, int family, u_int16_t port) static
Common function for resolve_me/other
Definition at line 146 of file ike_cfg.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, FALSE, host, host_create_any(), host_create_from_dns(), host_t::set_port, str, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     host_t *host = NULL;
     bool tried = FALSE;
     char *str;
     enumerator = hosts->create_enumerator(hosts);
     while (enumerator->enumerate(enumerator, &str))
     {
         host = host_create_from_dns(str, family, port);
         if (host)
         {
             break;
         }
         tried = TRUE;
     }
     enumerator->destroy(enumerator);
     if (!host && !tried)
     {
         /* we have no single host configured, return %any */
         host = host_create_any(family ?: AF_INET);
         host->set_port(host, port);
     }
     return host;
 }