strongSwan: eap_simaka_pseudonym_plugin.c File Reference
eap_simaka_pseudonym_plugin.c File Reference
#include "eap_simaka_pseudonym_plugin.h"
#include "eap_simaka_pseudonym_card.h"
#include "eap_simaka_pseudonym_provider.h"
#include <daemon.h>
Classes
struct private_eap_simaka_pseudonym_t
Typedefs
typedef struct
private_eap_simaka_pseudonym_t private_eap_simaka_pseudonym_t
Functions
METHOD (plugin_t, get_name, char *, private_eap_simaka_pseudonym_t *this)
static simaka_card_t * get_card (private_eap_simaka_pseudonym_t *this)
static simaka_provider_t * get_provider (private_eap_simaka_pseudonym_t *this)
METHOD (plugin_t, get_features, int, private_eap_simaka_pseudonym_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_eap_simaka_pseudonym_t *this)
plugin_t * eap_simaka_pseudonym_plugin_create ()
Typedef Documentation
typedef struct private_eap_simaka_pseudonym_t private_eap_simaka_pseudonym_t
Definition at line 22 of file eap_simaka_pseudonym_plugin.c.
Function Documentation
plugin_t* eap_simaka_pseudonym_plugin_create ()
See header
Definition at line 111 of file eap_simaka_pseudonym_plugin.c.
References INIT.
 {
     private_eap_simaka_pseudonym_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
static simaka_card_t* get_card (private_eap_simaka_pseudonym_t * this) static
Callback providing our card to register
Definition at line 54 of file eap_simaka_pseudonym_plugin.c.
References eap_simaka_pseudonym_card_create().
Referenced by METHOD().
 {
     if (!this->card)
     {
         this->card = eap_simaka_pseudonym_card_create();
     }
     return &this->card->card;
 }
static simaka_provider_t* get_provider (private_eap_simaka_pseudonym_t * this) static
Callback providing our provider to register
Definition at line 66 of file eap_simaka_pseudonym_plugin.c.
References eap_simaka_pseudonym_provider_create().
Referenced by METHOD().
 {
     if (!this->provider)
     {
         this->provider = eap_simaka_pseudonym_provider_create();
         if (!this->provider)
         {
             return NULL;
         }
     }
     return &this->provider->provider;
 }
METHOD (plugin_t , get_name , char * , private_eap_simaka_pseudonym_t * this)
Definition at line 45 of file eap_simaka_pseudonym_plugin.c.
 {
     return "eap-simaka-pseudonym";
 }
METHOD (plugin_t , get_features , int , private_eap_simaka_pseudonym_t * this, plugin_feature_t * features[])
Definition at line 79 of file eap_simaka_pseudonym_plugin.c.
References countof, get_card(), get_provider(), PLUGIN_CALLBACK, PLUGIN_DEPENDS, PLUGIN_PROVIDE, RNG_WEAK, and simaka_manager_register().
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK(simaka_manager_register, get_card),
             PLUGIN_PROVIDE(CUSTOM, "aka-card"),
                 PLUGIN_DEPENDS(CUSTOM, "aka-manager"),
             PLUGIN_PROVIDE(CUSTOM, "sim-card"),
                 PLUGIN_DEPENDS(CUSTOM, "sim-manager"),
         PLUGIN_CALLBACK(simaka_manager_register, get_provider),
             PLUGIN_PROVIDE(CUSTOM, "aka-provider"),
                 PLUGIN_DEPENDS(CUSTOM, "aka-manager"),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
             PLUGIN_PROVIDE(CUSTOM, "sim-provider"),
                 PLUGIN_DEPENDS(CUSTOM, "sim-manager"),
                 PLUGIN_DEPENDS(RNG, RNG_WEAK),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_eap_simaka_pseudonym_t * this)
Definition at line 100 of file eap_simaka_pseudonym_plugin.c.
References DESTROY_IF, and free().
 {
     DESTROY_IF(this->card);
     DESTROY_IF(this->provider);
     free(this);
 }