strongSwan: traffic_selector
traffic_selector
selectors
Classes
struct traffic_selector_t
Typedefs
typedef enum ts_type_t ts_type_t
typedef struct traffic_selector_t traffic_selector_t
Enumerations
enum ts_type_t { TS_IPV4_ADDR_RANGE = 7, TS_IPV6_ADDR_RANGE = 8 }
Functions
static u_int8_t traffic_selector_icmp_type (u_int16_t port)
static u_int8_t traffic_selector_icmp_code (u_int16_t port)
int traffic_selector_cmp (traffic_selector_t *a, traffic_selector_t *b, void *opts)
traffic_selector_t * traffic_selector_create_from_string (u_int8_t protocol, ts_type_t type, char *from_addr, u_int16_t from_port, char *to_addr, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_from_cidr (char *string, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_from_bytes (u_int8_t protocol, ts_type_t type, chunk_t from_address, u_int16_t from_port, chunk_t to_address, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_from_rfc3779_format (ts_type_t type, chunk_t from_addr, chunk_t to_addr)
traffic_selector_t * traffic_selector_create_from_subnet (host_t *net, u_int8_t netbits, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
traffic_selector_t * traffic_selector_create_dynamic (u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
int traffic_selector_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Variables
enum_name_t * ts_type_name
Detailed Description
Typedef Documentation
typedef struct traffic_selector_t traffic_selector_t
Definition at line 27 of file traffic_selector.h.
typedef enum ts_type_t ts_type_t
Definition at line 26 of file traffic_selector.h.
Enumeration Type Documentation
enum ts_type_t
Traffic selector types.
Enumerator
TS_IPV4_ADDR_RANGE
A range of IPv4 addresses, represented by two four (4) octet values. The first value is the beginning IPv4 address (inclusive) and the second value is the ending IPv4 address (inclusive). All addresses falling between the two specified addresses are considered to be within the list.
TS_IPV6_ADDR_RANGE
A range of IPv6 addresses, represented by two sixteen (16) octet values. The first value is the beginning IPv6 address (inclusive) and the second value is the ending IPv6 address (inclusive). All addresses falling between the two specified addresses are considered to be within the list.
Definition at line 35 of file traffic_selector.h.
                {
     TS_IPV4_ADDR_RANGE = 7,
     TS_IPV6_ADDR_RANGE = 8
 };
Function Documentation
int traffic_selector_cmp (traffic_selector_t * a, traffic_selector_t * b, void * opts)
Compare two traffic selectors, usable as sort function
Parameters
a first selector to compare
b second selector to compare
opts optional sort options, currently unused
Returns
> 0 if a > b, 0 if a == b, < 0 if a < b
Definition at line 715 of file traffic_selector.c.
References a, b, compare_int(), private_traffic_selector_t::from4, private_traffic_selector_t::from6, private_traffic_selector_t::from_port, private_traffic_selector_t::protocol, res, private_traffic_selector_t::to4, private_traffic_selector_t::to6, private_traffic_selector_t::to_port, TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and private_traffic_selector_t::type.
Referenced by METHOD(), and START_TEST().
 {
     private_traffic_selector_t *a, *b;
     int res;
     a = (private_traffic_selector_t*)a_pub;
     b = (private_traffic_selector_t*)b_pub;
     /* IPv4 before IPv6 */
     res = compare_int(a->type, b->type);
     if (res)
     {
         return res;
     }
     switch (a->type)
     {
         case TS_IPV4_ADDR_RANGE:
             /* lower starting subnets first */
             res = memcmp(a->from4, b->from4, sizeof(a->from4));
             if (res)
             {
                 return res;
             }
             /* larger subnets first */
             res = memcmp(b->to4, a->to4, sizeof(a->to4));
             if (res)
             {
                 return res;
             }
             break;
         case TS_IPV6_ADDR_RANGE:
             res = memcmp(a->from6, b->from6, sizeof(a->from6));
             if (res)
             {
                 return res;
             }
             res = memcmp(b->to6, a->to6, sizeof(a->to6));
             if (res)
             {
                 return res;
             }
             break;
         default:
             return 1;
     }
     /* lower protocols first */
     res = compare_int(a->protocol, b->protocol);
     if (res)
     {
         return res;
     }
     /* lower starting ports first */
     res = compare_int(a->from_port, b->from_port);
     if (res)
     {
         return res;
     }
     /* larger port ranges first */
     return compare_int(b->to_port, a->to_port);
 }
traffic_selector_t* traffic_selector_create_dynamic (u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
Create a traffic selector for host-to-host cases.
For host2host or virtual IP setups, the traffic selectors gets created at runtime using the external/virtual IP. Using this constructor, a call to set_address() sets this traffic selector to the supplied host.
If protocol is ICMP or ICMPv6 the ports are interpreted as follows: If they are less than 256 the value is assumed to be a message type, if they are greater or equal to 256 they are assumed to be type and code as defined for traffic_selector_t.
Parameters
protocol upper layer protocl to allow
from_port start of allowed port range
to_port end of range
Returns
traffic_selector_t object
NULL if type not supported
Definition at line 947 of file traffic_selector.c.
References dynamic, memset, traffic_selector_create(), TRUE, and TS_IPV4_ADDR_RANGE.
Referenced by add_ts(), build_traffic_selector(), CALLBACK(), cmd_connection_create(), connect_(), create_ts(), initiate_connection(), load_child_config(), METHOD(), setup_tunnel(), START_TEST(), and ts_from_string().
 {
     private_traffic_selector_t *this = traffic_selector_create(
                             protocol, TS_IPV4_ADDR_RANGE, from_port, to_port);
     memset(this->from6, 0, sizeof(this->from6));
     memset(this->to6, 0xFF, sizeof(this->to6));
     this->netbits = 0;
     this->dynamic = TRUE;
     return &this->public;
 }
traffic_selector_t* traffic_selector_create_from_bytes (u_int8_t protocol, ts_type_t type, chunk_t from_address, u_int16_t from_port, chunk_t to_address, u_int16_t to_port)
Create a new traffic selector using data read from the net.
There exists a mix of network and host order in the params. But the parser gives us this data in this format, so we don't have to convert twice.
If protocol is ICMP or ICMPv6 the ports are interpreted as follows: If they are less than 256 the value is assumed to be a message type, if they are greater or equal to 256 they are assumed to be type and code as defined for traffic_selector_t.
Parameters
protocol protocol for this ts, such as TCP or UDP
type type of following addresses, such as TS_IPV4_ADDR_RANGE
from_address start of address range, network order
from_port port number, host order
to_address end of address range, network order
to_port port number, host order
Returns
traffic_selector_t object
Definition at line 780 of file traffic_selector.c.
References calc_netbits(), free(), chunk_t::len, memcpy, chunk_t::ptr, traffic_selector_create(), TS_IPV4_ADDR_RANGE, and TS_IPV6_ADDR_RANGE.
Referenced by addr2ts(), build_traffic_selector(), create_ts(), get_ts_from_ip(), get_ts_from_range(), get_ts_from_subnet(), make_range(), METHOD(), and START_TEST().
 {
     private_traffic_selector_t *this = traffic_selector_create(protocol, type,
                                                             from_port, to_port);
     switch (type)
     {
         case TS_IPV4_ADDR_RANGE:
             if (from.len != 4 || to.len != 4)
             {
                 free(this);
                 return NULL;
             }
             memcpy(this->from4, from.ptr, from.len);
             memcpy(this->to4, to.ptr, to.len);
             break;
         case TS_IPV6_ADDR_RANGE:
             if (from.len != 16 || to.len != 16)
             {
                 free(this);
                 return NULL;
             }
             memcpy(this->from6, from.ptr, from.len);
             memcpy(this->to6, to.ptr, to.len);
             break;
         default:
             free(this);
             return NULL;
     }
     calc_netbits(this);
     return (&this->public);
 }
traffic_selector_t* traffic_selector_create_from_cidr (char * string, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
Create a traffic selector from a CIDR string.
If protocol is ICMP or ICMPv6 the ports are interpreted as follows: If they are less than 256 the value is assumed to be a message type, if they are greater or equal to 256 they are assumed to be type and code as defined for traffic_selector_t.
Parameters
string CIDR string, such as 10.1.0.0/16
protocol protocol for this ts, such as TCP or UDP
from_port start of allowed port range
to_port end of port range
Returns
traffic selector, NULL if string invalid
Definition at line 928 of file traffic_selector.c.
References bits, host_create_from_subnet(), net, and traffic_selector_create_from_subnet().
Referenced by add_ts(), CALLBACK(), create_ts(), install_route(), load_child_config(), make_subnet(), METHOD(), START_TEST(), and ts_from_string().
 {
     host_t *net;
     int bits;
     net = host_create_from_subnet(string, &bits);
     if (net)
     {
         return traffic_selector_create_from_subnet(net, bits, protocol,
                                                    from_port, to_port);
     }
     return NULL;
 }
traffic_selector_t* traffic_selector_create_from_rfc3779_format (ts_type_t type, chunk_t from_addr, chunk_t to_addr)
Create a new traffic selector using the RFC 3779 ASN.1 min/max address format
Parameters
type type of following addresses, such as TS_IPV4_ADDR_RANGE
from_addr start of address range in RFC 3779 ASN.1 BIT STRING format
to_addr end of address range in RFC 3779 ASN.1 BIT STRING format
Returns
traffic_selector_t object
Definition at line 819 of file traffic_selector.c.
References calc_netbits(), free(), chunk_t::len, len, mask, memcpy, memset, chunk_t::ptr, traffic_selector_create(), TS_IPV4_ADDR_RANGE, and TS_IPV6_ADDR_RANGE.
Referenced by parse_ipAddrBlocks(), and START_TEST().
 {
     size_t len;
     private_traffic_selector_t *this = traffic_selector_create(0, type, 0, 65535);
     switch (type)
     {
         case TS_IPV4_ADDR_RANGE:
             len = 4;
             break;
         case TS_IPV6_ADDR_RANGE:
             len = 16;
             break;
         default:
             free(this);
             return NULL;
     }
     memset(this->from, 0x00, len);
     memset(this->to  , 0xff, len);
     if (from.len > 1)
     {
         memcpy(this->from, from.ptr+1, from.len-1);
     }
     if (to.len > 1)
     {
         u_int8_t mask = to.ptr[0] ? (1 << to.ptr[0]) - 1 : 0;
         memcpy(this->to, to.ptr+1, to.len-1);
         this->to[to.len-2] |= mask;
     }
     calc_netbits(this);
     return (&this->public);
 }
traffic_selector_t* traffic_selector_create_from_string (u_int8_t protocol, ts_type_t type, char * from_addr, u_int16_t from_port, char * to_addr, u_int16_t to_port)
Create a new traffic selector using human readable params.
If protocol is ICMP or ICMPv6 the ports are interpreted as follows: If they are less than 256 the value is assumed to be a message type, if they are greater or equal to 256 they are assumed to be type and code as defined for traffic_selector_t.
Parameters
protocol protocol for this ts, such as TCP or UDP
type type of following addresses, such as TS_IPV4_ADDR_RANGE
from_addr start of address range as string
from_port port number in host order
to_addr end of address range as string
to_port port number in host order
Returns
traffic_selector_t object
NULL if invalid address strings/protocol
Definition at line 892 of file traffic_selector.c.
References calc_netbits(), family, free(), from, inet_pton(), to, traffic_selector_create(), TS_IPV4_ADDR_RANGE, and TS_IPV6_ADDR_RANGE.
Referenced by connect_(), create_child_cfg(), initiate_connection(), narrow_pre(), and START_TEST().
 {
     private_traffic_selector_t *this;
     int family;
     switch (type)
     {
         case TS_IPV4_ADDR_RANGE:
             family = AF_INET;
             break;
         case TS_IPV6_ADDR_RANGE:
             family = AF_INET6;
             break;
         default:
             return NULL;
     }
     this = traffic_selector_create(protocol, type, from_port, to_port);
     if (inet_pton(family, from_addr, this->from) != 1 ||
         inet_pton(family, to_addr, this->to) != 1)
     {
         free(this);
         return NULL;
     }
     calc_netbits(this);
     return &this->public;
 }
traffic_selector_t* traffic_selector_create_from_subnet (host_t * net, u_int8_t netbits, u_int8_t protocol, u_int16_t from_port, u_int16_t to_port)
Create a new traffic selector defining a whole subnet.
In most cases, definition of a traffic selector for full subnets is sufficient. This constructor creates a traffic selector for all protocols, all ports and the address range specified by the subnet. Additionally, a protocol and ports may be specified.
If protocol is ICMP or ICMPv6 the ports are interpreted as follows: If they are less than 256 the value is assumed to be a message type, if they are greater or equal to 256 they are assumed to be type and code as defined for traffic_selector_t.
Parameters
net subnet to use
netbits size of the subnet, as used in e.g. 192.168.0.0/24 notation
protocol protocol for this ts, such as TCP or UDP
from_port start of allowed port range
to_port end of port range
Returns
traffic_selector_t object
NULL if address family of net not supported
Definition at line 858 of file traffic_selector.c.
References calc_range(), host_t::destroy, free(), from, host_t::get_address, host_t::get_family, chunk_t::len, memcpy, min, chunk_t::ptr, traffic_selector_create(), TS_IPV4_ADDR_RANGE, TS_IPV6_ADDR_RANGE, and type.
Referenced by add_exclude_async(), add_ts(), get_ts(), install_ipip_ale(), sadb_address2ts(), selector2ts(), START_TEST(), and traffic_selector_create_from_cidr().
 {
     private_traffic_selector_t *this;
     chunk_t from;
     this = traffic_selector_create(protocol, 0, from_port, to_port);
     switch (net->get_family(net))
     {
         case AF_INET:
             this->type = TS_IPV4_ADDR_RANGE;
             break;
         case AF_INET6:
             this->type = TS_IPV6_ADDR_RANGE;
             break;
         default:
             net->destroy(net);
             free(this);
             return NULL;
     }
     from = net->get_address(net);
     memcpy(this->from, from.ptr, from.len);
     netbits = min(netbits, this->type == TS_IPV4_ADDR_RANGE ? 32 : 128);
     calc_range(this, netbits);
     net->destroy(net);
     return &this->public;
 }
static u_int8_t traffic_selector_icmp_code (u_int16_t port) inline static
Extract the ICMP/ICMPv6 message code from a port in host order
Parameters
port port number in host order
Returns
ICMP/ICMPv6 message code
Definition at line 254 of file traffic_selector.h.
Referenced by create_policy_entry(), get_port(), print_icmp(), START_TEST(), ts2condition(), and ts2selector().
 {
     return port & 0xff;
 }
static u_int8_t traffic_selector_icmp_type (u_int16_t port) inline static
Extract the ICMP/ICMPv6 message type from a port in host order
Parameters
port port number in host order
Returns
ICMP/ICMPv6 message type
Definition at line 243 of file traffic_selector.h.
Referenced by create_policy_entry(), get_port(), print_icmp(), START_TEST(), ts2condition(), and ts2selector().
 {
     return port >> 8;
 }
int traffic_selector_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook function for traffic_selector_t.
Arguments are: traffic_selector_t ts With the #-specifier, arguments are: linked_list_t *list containing traffic_selector_t
Described in header.
Definition at line 214 of file traffic_selector.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, dynamic, enumerator_t::enumerate, from, from_port, printf_hook_spec_t::hash, inet_ntop(), is_any(), is_opaque(), list, memeq(), memset, NON_SUBNET_ADDRESS_RANGE, print_icmp(), print_in_hook(), proto, protocol, sep, to, to_port, TS_IPV4_ADDR_RANGE, and type.
Referenced by library_init().
 {
     private_traffic_selector_t *this = *((private_traffic_selector_t**)(args[0]));
     linked_list_t *list = *((linked_list_t**)(args[0]));
     enumerator_t *enumerator;
     char from_str[INET6_ADDRSTRLEN] = "";
     char to_str[INET6_ADDRSTRLEN] = "";
     char *serv_proto = NULL, *sep = "";
     bool has_proto, has_ports;
     size_t written = 0;
     u_int32_t from[4], to[4];
     if (this == NULL)
     {
         return print_in_hook(data, "(null)");
     }
     if (spec->hash)
     {
         enumerator = list->create_enumerator(list);
         while (enumerator->enumerate(enumerator, (void**)&this))
         {
             written += print_in_hook(data, "%s%R", sep, this);
             sep = " ";
         }
         enumerator->destroy(enumerator);
         return written;
     }
     memset(from, 0, sizeof(from));
     memset(to, 0xFF, sizeof(to));
     if (this->dynamic &&
         memeq(this->from, from, this->type == TS_IPV4_ADDR_RANGE ? 4 : 16) &&
         memeq(this->to, to, this->type == TS_IPV4_ADDR_RANGE ? 4 : 16))
     {
         written += print_in_hook(data, "dynamic");
     }
     else
     {
         if (this->type == TS_IPV4_ADDR_RANGE)
         {
             inet_ntop(AF_INET, &this->from4, from_str, sizeof(from_str));
         }
         else
         {
             inet_ntop(AF_INET6, &this->from6, from_str, sizeof(from_str));
         }
         if (this->netbits == NON_SUBNET_ADDRESS_RANGE)
         {
             if (this->type == TS_IPV4_ADDR_RANGE)
             {
                 inet_ntop(AF_INET, &this->to4, to_str, sizeof(to_str));
             }
             else
             {
                 inet_ntop(AF_INET6, &this->to6, to_str, sizeof(to_str));
             }
             written += print_in_hook(data, "%s..%s", from_str, to_str);
         }
         else
         {
             written += print_in_hook(data, "%s/%d", from_str, this->netbits);
         }
     }
     /* check if we have protocol and/or port selectors */
     has_proto = this->protocol != 0;
     has_ports = !is_any(this);
     if (!has_proto && !has_ports)
     {
         return written;
     }
     written += print_in_hook(data, "[");
     /* build protocol string */
     if (has_proto)
     {
         struct protoent *proto = getprotobynumber(this->protocol);
         if (proto)
         {
             written += print_in_hook(data, "%s", proto->p_name);
             serv_proto = proto->p_name;
         }
         else
         {
             written += print_in_hook(data, "%d", this->protocol);
         }
     }
     if (has_proto && has_ports)
     {
         written += print_in_hook(data, "/");
     }
     /* build port string */
     if (has_ports)
     {
         if (this->from_port == this->to_port)
         {
             struct servent *serv;
             if (this->protocol == IPPROTO_ICMP ||
                 this->protocol == IPPROTO_ICMPV6)
             {
                 written += print_icmp(data, this->from_port);
             }
             else
             {
                 serv = getservbyport(htons(this->from_port), serv_proto);
                 if (serv)
                 {
                     written += print_in_hook(data, "%s", serv->s_name);
                 }
                 else
                 {
                     written += print_in_hook(data, "%d", this->from_port);
                 }
             }
         }
         else if (is_opaque(this))
         {
             written += print_in_hook(data, "OPAQUE");
         }
         else if (this->protocol == IPPROTO_ICMP ||
                  this->protocol == IPPROTO_ICMPV6)
         {
             written += print_icmp(data, this->from_port);
             written += print_in_hook(data, "-");
             written += print_icmp(data, this->to_port);
         }
         else
         {
             written += print_in_hook(data, "%d-%d",
                                      this->from_port, this->to_port);
         }
     }
     written += print_in_hook(data, "]");
     return written;
 }
Variable Documentation
enum_name_t* ts_type_name
enum names for ts_type_t
Referenced by METHOD(), and parse_ipAddrBlocks().