strongSwan: tls_crypto.c File Reference
tls_crypto.c File Reference
#include "tls_crypto.h"
#include <utils/debug.h>
#include <plugins/plugin_feature.h>
Classes
struct private_tls_crypto_t
struct suite_algs_t
Typedefs
typedef struct private_tls_crypto_t private_tls_crypto_t
Functions
ENUM_BEGIN (tls_cipher_suite_names, TLS_NULL_WITH_NULL_NULL, TLS_DH_anon_WITH_3DES_EDE_CBC_SHA,"TLS_NULL_WITH_NULL_NULL","TLS_RSA_WITH_NULL_MD5","TLS_RSA_WITH_NULL_SHA","TLS_RSA_EXPORT_WITH_RC4_40_MD5","TLS_RSA_WITH_RC4_128_MD5","TLS_RSA_WITH_RC4_128_SHA","TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5","TLS_RSA_WITH_IDEA_CBC_SHA","TLS_RSA_EXPORT_WITH_DES40_CBC_SHA","TLS_RSA_WITH_DES_CBC_SHA","TLS_RSA_WITH_3DES_EDE_CBC_SHA","TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA","TLS_DH_DSS_WITH_DES_CBC_SHA","TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA","TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA","TLS_DH_RSA_WITH_DES_CBC_SHA","TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA","TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA","TLS_DHE_DSS_WITH_DES_CBC_SHA","TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA","TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA","TLS_DHE_RSA_WITH_DES_CBC_SHA","TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA","TLS_DH_anon_EXPORT_WITH_RC4_40_MD5","TLS_DH_anon_WITH_RC4_128_MD5","TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA","TLS_DH_anon_WITH_DES_CBC_SHA","TLS_DH_anon_WITH_3DES_EDE_CBC_SHA")
ENUM_NEXT (tls_cipher_suite_names, TLS_KRB5_WITH_DES_CBC_SHA, TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA, TLS_DH_anon_WITH_3DES_EDE_CBC_SHA,"TLS_KRB5_WITH_DES_CBC_SHA","TLS_KRB5_WITH_3DES_EDE_CBC_SHA","TLS_KRB5_WITH_RC4_128_SHA","TLS_KRB5_WITH_IDEA_CBC_SHA","TLS_KRB5_WITH_DES_CBC_MD5","TLS_KRB5_WITH_3DES_EDE_CBC_MD5","TLS_KRB5_WITH_RC4_128_MD5","TLS_KRB5_WITH_IDEA_CBC_MD5","TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA","TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA","TLS_KRB5_EXPORT_WITH_RC4_40_SHA","TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5","TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5","TLS_KRB5_EXPORT_WITH_RC4_40_MD5","TLS_PSK_WITH_NULL_SHA","TLS_DHE_PSK_WITH_NULL_SHA","TLS_RSA_PSK_WITH_NULL_SHA","TLS_RSA_WITH_AES_128_CBC_SHA","TLS_DH_DSS_WITH_AES_128_CBC_SHA","TLS_DH_RSA_WITH_AES_128_CBC_SHA","TLS_DHE_DSS_WITH_AES_128_CBC_SHA","TLS_DHE_RSA_WITH_AES_128_CBC_SHA","TLS_DH_anon_WITH_AES_128_CBC_SHA","TLS_RSA_WITH_AES_256_CBC_SHA","TLS_DH_DSS_WITH_AES_256_CBC_SHA","TLS_DH_RSA_WITH_AES_256_CBC_SHA","TLS_DHE_DSS_WITH_AES_256_CBC_SHA","TLS_DHE_RSA_WITH_AES_256_CBC_SHA","TLS_DH_anon_WITH_AES_256_CBC_SHA","TLS_RSA_WITH_NULL_SHA256","TLS_RSA_WITH_AES_128_CBC_SHA256","TLS_RSA_WITH_AES_256_CBC_SHA256","TLS_DH_DSS_WITH_AES_128_CBC_SHA256","TLS_DH_RSA_WITH_AES_128_CBC_SHA256","TLS_DHE_DSS_WITH_AES_128_CBC_SHA256","TLS_RSA_WITH_CAMELLIA_128_CBC_SHA","TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA","TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA","TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA","TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA","TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA")
ENUM_NEXT (tls_cipher_suite_names, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DH_anon_WITH_AES_256_CBC_SHA256, TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA,"TLS_DHE_RSA_WITH_AES_128_CBC_SHA256","TLS_DH_DSS_WITH_AES_256_CBC_SHA256","TLS_DH_RSA_WITH_AES_256_CBC_SHA256","TLS_DHE_DSS_WITH_AES_256_CBC_SHA256","TLS_DHE_RSA_WITH_AES_256_CBC_SHA256","TLS_DH_anon_WITH_AES_128_CBC_SHA256","TLS_DH_anon_WITH_AES_256_CBC_SHA256")
ENUM_NEXT (tls_cipher_suite_names, TLS_RSA_WITH_CAMELLIA_256_CBC_SHA, TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256, TLS_DH_anon_WITH_AES_256_CBC_SHA256,"TLS_RSA_WITH_CAMELLIA_256_CBC_SHA","TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA","TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA","TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA","TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA","TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA","TLS_PSK_WITH_RC4_128_SHA","TLS_PSK_WITH_3DES_EDE_CBC_SHA","TLS_PSK_WITH_AES_128_CBC_SHA","TLS_PSK_WITH_AES_256_CBC_SHA","TLS_DHE_PSK_WITH_RC4_128_SHA","TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA","TLS_DHE_PSK_WITH_AES_128_CBC_SHA","TLS_DHE_PSK_WITH_AES_256_CBC_SHA","TLS_RSA_PSK_WITH_RC4_128_SHA","TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA","TLS_RSA_PSK_WITH_AES_128_CBC_SHA","TLS_RSA_PSK_WITH_AES_256_CBC_SHA","TLS_RSA_WITH_SEED_CBC_SHA","TLS_DH_DSS_WITH_SEED_CBC_SHA","TLS_DH_RSA_WITH_SEED_CBC_SHA","TLS_DHE_DSS_WITH_SEED_CBC_SHA","TLS_DHE_RSA_WITH_SEED_CBC_SHA","TLS_DH_anon_WITH_SEED_CBC_SHA","TLS_RSA_WITH_AES_128_GCM_SHA256","TLS_RSA_WITH_AES_256_GCM_SHA384","TLS_DHE_RSA_WITH_AES_128_GCM_SHA256","TLS_DHE_RSA_WITH_AES_256_GCM_SHA384","TLS_DH_RSA_WITH_AES_128_GCM_SHA256","TLS_DH_RSA_WITH_AES_256_GCM_SHA384","TLS_DHE_DSS_WITH_AES_128_GCM_SHA256","TLS_DHE_DSS_WITH_AES_256_GCM_SHA384","TLS_DH_DSS_WITH_AES_128_GCM_SHA256","TLS_DH_DSS_WITH_AES_256_GCM_SHA384","TLS_DH_anon_WITH_AES_128_GCM_SHA256","TLS_DH_anon_WITH_AES_256_GCM_SHA384","TLS_PSK_WITH_AES_128_GCM_SHA256","TLS_PSK_WITH_AES_256_GCM_SHA384","TLS_DHE_PSK_WITH_AES_128_GCM_SHA256","TLS_DHE_PSK_WITH_AES_256_GCM_SHA384","TLS_RSA_PSK_WITH_AES_128_GCM_SHA256","TLS_RSA_PSK_WITH_AES_256_GCM_SHA384","TLS_PSK_WITH_AES_128_CBC_SHA256","TLS_PSK_WITH_AES_256_CBC_SHA384","TLS_PSK_WITH_NULL_SHA256","TLS_PSK_WITH_NULL_SHA384","TLS_DHE_PSK_WITH_AES_128_CBC_SHA256","TLS_DHE_PSK_WITH_AES_256_CBC_SHA384","TLS_DHE_PSK_WITH_NULL_SHA256","TLS_DHE_PSK_WITH_NULL_SHA384","TLS_RSA_PSK_WITH_AES_128_CBC_SHA256","TLS_RSA_PSK_WITH_AES_256_CBC_SHA384","TLS_RSA_PSK_WITH_NULL_SHA256","TLS_RSA_PSK_WITH_NULL_SHA384","TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256","TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256","TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256","TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256","TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256","TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256","TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256","TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256","TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256","TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256","TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256","TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256")
ENUM_NEXT (tls_cipher_suite_names, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256,"TLS_EMPTY_RENEGOTIATION_INFO_SCSV")
ENUM_NEXT (tls_cipher_suite_names, TLS_ECDH_ECDSA_WITH_NULL_SHA, TLS_ECDHE_PSK_WITH_NULL_SHA384, TLS_EMPTY_RENEGOTIATION_INFO_SCSV,"TLS_ECDH_ECDSA_WITH_NULL_SHA","TLS_ECDH_ECDSA_WITH_RC4_128_SHA","TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA","TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA","TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA","TLS_ECDHE_ECDSA_WITH_NULL_SHA","TLS_ECDHE_ECDSA_WITH_RC4_128_SHA","TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA","TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA","TLS_ECDH_RSA_WITH_NULL_SHA","TLS_ECDH_RSA_WITH_RC4_128_SHA","TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA","TLS_ECDH_RSA_WITH_AES_128_CBC_SHA","TLS_ECDH_RSA_WITH_AES_256_CBC_SHA","TLS_ECDHE_RSA_WITH_NULL_SHA","TLS_ECDHE_RSA_WITH_RC4_128_SHA","TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA","TLS_ECDH_anon_WITH_NULL_SHA","TLS_ECDH_anon_WITH_RC4_128_SHA","TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA","TLS_ECDH_anon_WITH_AES_128_CBC_SHA","TLS_ECDH_anon_WITH_AES_256_CBC_SHA","TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA","TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA","TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA","TLS_SRP_SHA_WITH_AES_128_CBC_SHA","TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA","TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA","TLS_SRP_SHA_WITH_AES_256_CBC_SHA","TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA","TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA","TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256","TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384","TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256","TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256","TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384","TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256","TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384","TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_PSK_WITH_RC4_128_SHA","TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA","TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA","TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA","TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256","TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384","TLS_ECDHE_PSK_WITH_NULL_SHA","TLS_ECDHE_PSK_WITH_NULL_SHA256","TLS_ECDHE_PSK_WITH_NULL_SHA384")
ENUM_END (tls_cipher_suite_names, TLS_ECDHE_PSK_WITH_NULL_SHA384)
ENUM (tls_hash_algorithm_names, TLS_HASH_NONE, TLS_HASH_SHA512,"NONE","MD5","SHA1","SHA224","SHA256","SHA384","SHA512",)
ENUM (tls_signature_algorithm_names, TLS_SIG_RSA, TLS_SIG_ECDSA,"RSA","DSA","ECDSA",)
ENUM_BEGIN (tls_client_certificate_type_names, TLS_RSA_SIGN, TLS_DSS_EPHEMERAL_DH,"RSA_SIGN","DSA_SIGN","RSA_FIXED_DH","DSS_FIXED_DH","RSA_EPHEMERAL_DH","DSS_EPHEMERAL_DH")
ENUM_NEXT (tls_client_certificate_type_names, TLS_FORTEZZA_DMS, TLS_FORTEZZA_DMS, TLS_DSS_EPHEMERAL_DH,"FORTEZZA_DMS")
ENUM_NEXT (tls_client_certificate_type_names, TLS_ECDSA_SIGN, TLS_ECDSA_FIXED_ECDH, TLS_FORTEZZA_DMS,"ECDSA_SIGN","RSA_FIXED_ECDH","ECDSA_FIXED_ECDH")
ENUM_END (tls_client_certificate_type_names, TLS_ECDSA_FIXED_ECDH)
ENUM (tls_ecc_curve_type_names, TLS_ECC_EXPLICIT_PRIME, TLS_ECC_NAMED_CURVE,"EXPLICIT_PRIME","EXPLICIT_CHAR2","NAMED_CURVE",)
ENUM (tls_named_curve_names, TLS_SECT163K1, TLS_SECP521R1,"SECT163K1","SECT163R1","SECT163R2","SECT193R1","SECT193R2","SECT233K1","SECT233R1","SECT239K1","SECT283K1","SECT283R1","SECT409K1","SECT409R1","SECT571K1","SECT571R1","SECP160K1","SECP160R1","SECP160R2","SECP192K1","SECP192R1","SECP224K1","SECP224R1","SECP256K1","SECP256R1","SECP384R1","SECP521R1",)
ENUM (tls_ansi_point_format_names, TLS_ANSI_COMPRESSED, TLS_ANSI_HYBRID_Y,"compressed","compressed y","uncompressed","uncompressed y","hybrid","hybrid y",)
ENUM (tls_ec_point_format_names, TLS_EC_POINT_UNCOMPRESSED, TLS_EC_POINT_ANSIX962_COMPRESSED_CHAR2,"uncompressed","ansiX962 compressed prime","ansiX962 compressed char2",)
static suite_algs_t * find_suite (tls_cipher_suite_t suite)
static void filter_suite (suite_algs_t suites[], int *count, int offset, enumerator_t *(*create_enumerator)(crypto_factory_t *))
static void filter_null_suites (suite_algs_t suites[], int *count)
static void filter_key_suites (private_tls_crypto_t *this, suite_algs_t suites[], int *count, key_type_t key)
static void filter_key_exchange_config_suites (private_tls_crypto_t *this, suite_algs_t suites[], int *count)
static void filter_cipher_config_suites (private_tls_crypto_t *this, suite_algs_t suites[], int *count)
static void filter_mac_config_suites (private_tls_crypto_t *this, suite_algs_t suites[], int *count)
static void filter_specific_config_suites (private_tls_crypto_t *this, suite_algs_t suites[], int *count)
static void filter_unsupported_suites (suite_algs_t suites[], int *count)
static void build_cipher_suite_list (private_tls_crypto_t *this, bool require_encryption)
METHOD (tls_crypto_t, get_cipher_suites, int, private_tls_crypto_t *this, tls_cipher_suite_t **suites)
static bool create_null (private_tls_crypto_t *this, suite_algs_t *algs)
static bool create_traditional (private_tls_crypto_t *this, suite_algs_t *algs)
static bool create_aead (private_tls_crypto_t *this, suite_algs_t *algs)
static void destroy_aeads (private_tls_crypto_t *this)
static bool create_ciphers (private_tls_crypto_t *this, suite_algs_t *algs)
METHOD (tls_crypto_t, select_cipher_suite, tls_cipher_suite_t, private_tls_crypto_t *this, tls_cipher_suite_t *suites, int count, key_type_t key)
METHOD (tls_crypto_t, get_dh_group, diffie_hellman_group_t, private_tls_crypto_t *this)
METHOD (tls_crypto_t, get_signature_algorithms, void, private_tls_crypto_t *this, bio_writer_t *writer)
static signature_scheme_t hashsig_to_scheme (key_type_t type, tls_hash_algorithm_t hash, tls_signature_algorithm_t sig)
static bool group_filter (void *null, diffie_hellman_group_t *in, diffie_hellman_group_t *out, void *dummy1, tls_named_curve_t *curve)
METHOD (tls_crypto_t, create_ec_enumerator, enumerator_t *, private_tls_crypto_t *this)
METHOD (tls_crypto_t, set_protection, void, private_tls_crypto_t *this, tls_protection_t *protection)
METHOD (tls_crypto_t, append_handshake, void, private_tls_crypto_t *this, tls_handshake_type_t type, chunk_t data)
static bool hash_data (private_tls_crypto_t *this, chunk_t data, chunk_t *hash)
METHOD (tls_crypto_t, sign, bool, private_tls_crypto_t *this, private_key_t *key, bio_writer_t *writer, chunk_t data, chunk_t hashsig)
METHOD (tls_crypto_t, verify, bool, private_tls_crypto_t *this, public_key_t *key, bio_reader_t *reader, chunk_t data)
METHOD (tls_crypto_t, sign_handshake, bool, private_tls_crypto_t *this, private_key_t *key, bio_writer_t *writer, chunk_t hashsig)
METHOD (tls_crypto_t, verify_handshake, bool, private_tls_crypto_t *this, public_key_t *key, bio_reader_t *reader)
METHOD (tls_crypto_t, calculate_finished, bool, private_tls_crypto_t *this, char *label, char out[12])
static bool derive_master (private_tls_crypto_t *this, chunk_t premaster, chunk_t session, identification_t *id, chunk_t client_random, chunk_t server_random)
static bool expand_keys (private_tls_crypto_t *this, chunk_t client_random, chunk_t server_random)
METHOD (tls_crypto_t, derive_secrets, bool, private_tls_crypto_t *this, chunk_t premaster, chunk_t session, identification_t *id, chunk_t client_random, chunk_t server_random)
METHOD (tls_crypto_t, resume_session, tls_cipher_suite_t, private_tls_crypto_t *this, chunk_t session, identification_t *id, chunk_t client_random, chunk_t server_random)
METHOD (tls_crypto_t, get_session, chunk_t, private_tls_crypto_t *this, identification_t *server)
METHOD (tls_crypto_t, change_cipher, void, private_tls_crypto_t *this, bool inbound)
METHOD (tls_crypto_t, get_eap_msk, chunk_t, private_tls_crypto_t *this)
METHOD (tls_crypto_t, destroy, void, private_tls_crypto_t *this)
tls_crypto_t * tls_crypto_create (tls_t *tls, tls_cache_t *cache)
int tls_crypto_get_supported_suites (bool null, tls_cipher_suite_t **out)
Variables
static suite_algs_t suite_algs []
struct {
tls_signature_algorithm_t sig
tls_hash_algorithm_t hash
signature_scheme_t scheme
} schemes []
struct {
diffie_hellman_group_t group
tls_named_curve_t curve
} curves []
Typedef Documentation
typedef struct private_tls_crypto_t private_tls_crypto_t
Definition at line 326 of file tls_crypto.c.
Function Documentation
static void build_cipher_suite_list (private_tls_crypto_t * this, bool require_encryption) static
Initialize the cipher suite list
Definition at line 998 of file tls_crypto.c.
References count, countof, DBG2, DBG_TLS, ecdsa, filter_cipher_config_suites(), filter_key_exchange_config_suites(), filter_key_suites(), filter_mac_config_suites(), filter_null_suites(), filter_specific_config_suites(), filter_unsupported_suites(), free(), KEY_ECDSA, KEY_RSA, malloc(), rsa, suite_algs_t::suite, and tls_cipher_suite_names.
Referenced by tls_crypto_create().
 {
     suite_algs_t suites[countof(suite_algs)];
     int count = countof(suite_algs), i;
     /* copy all suites */
     for (i = 0; i < count; i++)
     {
         suites[i] = suite_algs[i];
     }
     if (require_encryption)
     {
         filter_null_suites(suites, &count);
     }
     if (!this->rsa)
     {
         filter_key_suites(this, suites, &count, KEY_RSA);
     }
     if (!this->ecdsa)
     {
         filter_key_suites(this, suites, &count, KEY_ECDSA);
     }
     filter_unsupported_suites(suites, &count);
     /* filter suites with strongswan.conf options */
     filter_key_exchange_config_suites(this, suites, &count);
     filter_cipher_config_suites(this, suites, &count);
     filter_mac_config_suites(this, suites, &count);
     filter_specific_config_suites(this, suites, &count);
     free(this->suites);
     this->suite_count = count;
     this->suites = malloc(sizeof(tls_cipher_suite_t) * count);
     DBG2(DBG_TLS, "%d supported TLS cipher suites:", count);
     for (i = 0; i < count; i++)
     {
         DBG2(DBG_TLS, "  %N", tls_cipher_suite_names, suites[i].suite);
         this->suites[i] = suites[i].suite;
     }
 }
static bool create_aead (private_tls_crypto_t * this, suite_algs_t * algs) static
Create AEAD transforms
Definition at line 1098 of file tls_crypto.c.
References DBG1, DBG_TLS, suite_algs_t::encr, suite_algs_t::encr_size, encryption_algorithm_names, FALSE, tls_aead_create_aead(), and TRUE.
Referenced by create_ciphers().
 {
     this->aead_in = tls_aead_create_aead(algs->encr, algs->encr_size);
     this->aead_out = tls_aead_create_aead(algs->encr, algs->encr_size);
     if (!this->aead_in || !this->aead_out)
     {
         DBG1(DBG_TLS, "selected TLS transforms %N-%u not supported",
              encryption_algorithm_names, algs->encr, algs->encr_size * 8);
         return FALSE;
     }
     return TRUE;
 }
static bool create_ciphers (private_tls_crypto_t * this, suite_algs_t * algs) static
Create crypto primitives
Definition at line 1124 of file tls_crypto.c.
References create_aead(), create_null(), create_traditional(), DBG1, DBG_TLS, destroy_aeads(), DESTROY_IF, suite_algs_t::encr, ENCR_NULL, encryption_algorithm_is_aead(), FALSE, prf, suite_algs_t::prf, tls, TLS_1_2, tls_prf_create_10(), tls_prf_create_12(), and TRUE.
Referenced by METHOD().
 {
     destroy_aeads(this);
     DESTROY_IF(this->prf);
     if (this->tls->get_version(this->tls) < TLS_1_2)
     {
         this->prf = tls_prf_create_10();
     }
     else
     {
         this->prf = tls_prf_create_12(algs->prf);
     }
     if (!this->prf)
     {
         DBG1(DBG_TLS, "selected TLS PRF not supported");
         return FALSE;
     }
     if (algs->encr == ENCR_NULL)
     {
         if (create_null(this, algs))
         {
             return TRUE;
         }
     }
     else if (encryption_algorithm_is_aead(algs->encr))
     {
         if (create_aead(this, algs))
         {
             return TRUE;
         }
     }
     else
     {
         if (create_traditional(this, algs))
         {
             return TRUE;
         }
     }
     destroy_aeads(this);
     return FALSE;
 }
static bool create_null (private_tls_crypto_t * this, suite_algs_t * algs) static
Create NULL encryption transforms
Definition at line 1053 of file tls_crypto.c.
References DBG1, DBG_TLS, FALSE, integrity_algorithm_names, suite_algs_t::mac, tls_aead_create_null(), and TRUE.
Referenced by create_ciphers().
 {
     this->aead_in = tls_aead_create_null(algs->mac);
     this->aead_out = tls_aead_create_null(algs->mac);
     if (!this->aead_in || !this->aead_out)
     {
         DBG1(DBG_TLS, "selected TLS MAC %N not supported",
              integrity_algorithm_names, algs->mac);
         return FALSE;
     }
     return TRUE;
 }
static bool create_traditional (private_tls_crypto_t * this, suite_algs_t * algs) static
Create traditional transforms
Definition at line 1069 of file tls_crypto.c.
References DBG1, DBG_TLS, suite_algs_t::encr, suite_algs_t::encr_size, encryption_algorithm_names, FALSE, integrity_algorithm_names, suite_algs_t::mac, tls, TLS_1_1, tls_aead_create_explicit(), tls_aead_create_implicit(), and TRUE.
Referenced by create_ciphers().
 {
     if (this->tls->get_version(this->tls) < TLS_1_1)
     {
         this->aead_in = tls_aead_create_implicit(algs->mac,
                                 algs->encr, algs->encr_size);
         this->aead_out = tls_aead_create_implicit(algs->mac,
                                 algs->encr, algs->encr_size);
     }
     else
     {
         this->aead_in = tls_aead_create_explicit(algs->mac,
                                 algs->encr, algs->encr_size);
         this->aead_out = tls_aead_create_explicit(algs->mac,
                                 algs->encr, algs->encr_size);
     }
     if (!this->aead_in || !this->aead_out)
     {
         DBG1(DBG_TLS, "selected TLS transforms %N-%u-%N not supported",
              encryption_algorithm_names, algs->encr, algs->encr_size * 8,
              integrity_algorithm_names, algs->mac);
         return FALSE;
     }
     return TRUE;
 }
static bool derive_master (private_tls_crypto_t * this, chunk_t premaster, chunk_t session, identification_t * id, chunk_t client_random, chunk_t server_random) static
Derive master secret from premaster, optionally save session
Definition at line 1592 of file tls_crypto.c.
References cache(), chunk_cata, chunk_from_thing, FALSE, chunk_t::len, memwipe(), prf, and TRUE.
Referenced by METHOD().
 {
     char master[48];
     chunk_t seed;
     /* derive master secret */
     seed = chunk_cata("cc", client_random, server_random);
     if (!this->prf->set_key(this->prf, premaster) ||
         !this->prf->get_bytes(this->prf, "master secret", seed,
                               sizeof(master), master) ||
         !this->prf->set_key(this->prf, chunk_from_thing(master)))
     {
         return FALSE;
     }
     if (this->cache && session.len)
     {
         this->cache->create(this->cache, session, id, chunk_from_thing(master),
                             this->suite);
     }
     memwipe(master, sizeof(master));
     return TRUE;
 }
static void destroy_aeads (private_tls_crypto_t * this) static
Clean up and unset AEAD transforms
Definition at line 1114 of file tls_crypto.c.
References DESTROY_IF.
Referenced by create_ciphers(), and METHOD().
 {
     DESTROY_IF(this->aead_in);
     DESTROY_IF(this->aead_out);
     this->aead_in = this->aead_out = NULL;
 }
ENUM (tls_hash_algorithm_names , TLS_HASH_NONE , TLS_HASH_SHA512 , "NONE" , "MD5" , "SHA1" , "SHA224" , "SHA256" , "SHA384" , "SHA512")
ENUM (tls_signature_algorithm_names , TLS_SIG_RSA , TLS_SIG_ECDSA , "RSA" , "DSA" , "ECDSA")
ENUM (tls_ecc_curve_type_names , TLS_ECC_EXPLICIT_PRIME , TLS_ECC_NAMED_CURVE , "EXPLICIT_PRIME" , "EXPLICIT_CHAR2" , "NAMED_CURVE")
ENUM (tls_named_curve_names , TLS_SECT163K1 , TLS_SECP521R1 , "SECT163K1" , "SECT163R1" , "SECT163R2" , "SECT193R1" , "SECT193R2" , "SECT233K1" , "SECT233R1" , "SECT239K1" , "SECT283K1" , "SECT283R1" , "SECT409K1" , "SECT409R1" , "SECT571K1" , "SECT571R1" , "SECP160K1" , "SECP160R1" , "SECP160R2" , "SECP192K1" , "SECP192R1" , "SECP224K1" , "SECP224R1" , "SECP256K1" , "SECP256R1" , "SECP384R1" , "SECP521R1")
ENUM (tls_ansi_point_format_names , TLS_ANSI_COMPRESSED , TLS_ANSI_HYBRID_Y , "compressed" , "compressed y" , "uncompressed" , "uncompressed y" , "hybrid" , "hybrid y")
ENUM (tls_ec_point_format_names , TLS_EC_POINT_UNCOMPRESSED , TLS_EC_POINT_ANSIX962_COMPRESSED_CHAR2 , "uncompressed" , "ansiX962 compressed prime" , "ansiX962 compressed char2")
ENUM_BEGIN (tls_cipher_suite_names , TLS_NULL_WITH_NULL_NULL , TLS_DH_anon_WITH_3DES_EDE_CBC_SHA , "TLS_NULL_WITH_NULL_NULL" , "TLS_RSA_WITH_NULL_MD5" , "TLS_RSA_WITH_NULL_SHA" , "TLS_RSA_EXPORT_WITH_RC4_40_MD5" , "TLS_RSA_WITH_RC4_128_MD5" , "TLS_RSA_WITH_RC4_128_SHA" , "TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5" , "TLS_RSA_WITH_IDEA_CBC_SHA" , "TLS_RSA_EXPORT_WITH_DES40_CBC_SHA" , "TLS_RSA_WITH_DES_CBC_SHA" , "TLS_RSA_WITH_3DES_EDE_CBC_SHA" , "TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA" , "TLS_DH_DSS_WITH_DES_CBC_SHA" , "TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA" , "TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA" , "TLS_DH_RSA_WITH_DES_CBC_SHA" , "TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA" , "TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA" , "TLS_DHE_DSS_WITH_DES_CBC_SHA" , "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA" , "TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA" , "TLS_DHE_RSA_WITH_DES_CBC_SHA" , "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA" , "TLS_DH_anon_EXPORT_WITH_RC4_40_MD5" , "TLS_DH_anon_WITH_RC4_128_MD5" , "TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA" , "TLS_DH_anon_WITH_DES_CBC_SHA" , "TLS_DH_anon_WITH_3DES_EDE_CBC_SHA")
ENUM_BEGIN (tls_client_certificate_type_names , TLS_RSA_SIGN , TLS_DSS_EPHEMERAL_DH , "RSA_SIGN" , "DSA_SIGN" , "RSA_FIXED_DH" , "DSS_FIXED_DH" , "RSA_EPHEMERAL_DH" , "DSS_EPHEMERAL_DH")
ENUM_END (tls_cipher_suite_names , TLS_ECDHE_PSK_WITH_NULL_SHA384)
ENUM_END (tls_client_certificate_type_names , TLS_ECDSA_FIXED_ECDH)
ENUM_NEXT (tls_cipher_suite_names , TLS_KRB5_WITH_DES_CBC_SHA , TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA , TLS_DH_anon_WITH_3DES_EDE_CBC_SHA , "TLS_KRB5_WITH_DES_CBC_SHA" , "TLS_KRB5_WITH_3DES_EDE_CBC_SHA" , "TLS_KRB5_WITH_RC4_128_SHA" , "TLS_KRB5_WITH_IDEA_CBC_SHA" , "TLS_KRB5_WITH_DES_CBC_MD5" , "TLS_KRB5_WITH_3DES_EDE_CBC_MD5" , "TLS_KRB5_WITH_RC4_128_MD5" , "TLS_KRB5_WITH_IDEA_CBC_MD5" , "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA" , "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA" , "TLS_KRB5_EXPORT_WITH_RC4_40_SHA" , "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5" , "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5" , "TLS_KRB5_EXPORT_WITH_RC4_40_MD5" , "TLS_PSK_WITH_NULL_SHA" , "TLS_DHE_PSK_WITH_NULL_SHA" , "TLS_RSA_PSK_WITH_NULL_SHA" , "TLS_RSA_WITH_AES_128_CBC_SHA" , "TLS_DH_DSS_WITH_AES_128_CBC_SHA" , "TLS_DH_RSA_WITH_AES_128_CBC_SHA" , "TLS_DHE_DSS_WITH_AES_128_CBC_SHA" , "TLS_DHE_RSA_WITH_AES_128_CBC_SHA" , "TLS_DH_anon_WITH_AES_128_CBC_SHA" , "TLS_RSA_WITH_AES_256_CBC_SHA" , "TLS_DH_DSS_WITH_AES_256_CBC_SHA" , "TLS_DH_RSA_WITH_AES_256_CBC_SHA" , "TLS_DHE_DSS_WITH_AES_256_CBC_SHA" , "TLS_DHE_RSA_WITH_AES_256_CBC_SHA" , "TLS_DH_anon_WITH_AES_256_CBC_SHA" , "TLS_RSA_WITH_NULL_SHA256" , "TLS_RSA_WITH_AES_128_CBC_SHA256" , "TLS_RSA_WITH_AES_256_CBC_SHA256" , "TLS_DH_DSS_WITH_AES_128_CBC_SHA256" , "TLS_DH_RSA_WITH_AES_128_CBC_SHA256" , "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256" , "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA" , "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA" , "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA" , "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA" , "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA" , "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA")
ENUM_NEXT (tls_cipher_suite_names , TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 , TLS_DH_anon_WITH_AES_256_CBC_SHA256 , TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA , "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256" , "TLS_DH_DSS_WITH_AES_256_CBC_SHA256" , "TLS_DH_RSA_WITH_AES_256_CBC_SHA256" , "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256" , "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256" , "TLS_DH_anon_WITH_AES_128_CBC_SHA256" , "TLS_DH_anon_WITH_AES_256_CBC_SHA256")
ENUM_NEXT (tls_cipher_suite_names , TLS_RSA_WITH_CAMELLIA_256_CBC_SHA , TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 , TLS_DH_anon_WITH_AES_256_CBC_SHA256 , "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA" , "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA" , "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA" , "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA" , "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA" , "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA" , "TLS_PSK_WITH_RC4_128_SHA" , "TLS_PSK_WITH_3DES_EDE_CBC_SHA" , "TLS_PSK_WITH_AES_128_CBC_SHA" , "TLS_PSK_WITH_AES_256_CBC_SHA" , "TLS_DHE_PSK_WITH_RC4_128_SHA" , "TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA" , "TLS_DHE_PSK_WITH_AES_128_CBC_SHA" , "TLS_DHE_PSK_WITH_AES_256_CBC_SHA" , "TLS_RSA_PSK_WITH_RC4_128_SHA" , "TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA" , "TLS_RSA_PSK_WITH_AES_128_CBC_SHA" , "TLS_RSA_PSK_WITH_AES_256_CBC_SHA" , "TLS_RSA_WITH_SEED_CBC_SHA" , "TLS_DH_DSS_WITH_SEED_CBC_SHA" , "TLS_DH_RSA_WITH_SEED_CBC_SHA" , "TLS_DHE_DSS_WITH_SEED_CBC_SHA" , "TLS_DHE_RSA_WITH_SEED_CBC_SHA" , "TLS_DH_anon_WITH_SEED_CBC_SHA" , "TLS_RSA_WITH_AES_128_GCM_SHA256" , "TLS_RSA_WITH_AES_256_GCM_SHA384" , "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256" , "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384" , "TLS_DH_RSA_WITH_AES_128_GCM_SHA256" , "TLS_DH_RSA_WITH_AES_256_GCM_SHA384" , "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256" , "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384" , "TLS_DH_DSS_WITH_AES_128_GCM_SHA256" , "TLS_DH_DSS_WITH_AES_256_GCM_SHA384" , "TLS_DH_anon_WITH_AES_128_GCM_SHA256" , "TLS_DH_anon_WITH_AES_256_GCM_SHA384" , "TLS_PSK_WITH_AES_128_GCM_SHA256" , "TLS_PSK_WITH_AES_256_GCM_SHA384" , "TLS_DHE_PSK_WITH_AES_128_GCM_SHA256" , "TLS_DHE_PSK_WITH_AES_256_GCM_SHA384" , "TLS_RSA_PSK_WITH_AES_128_GCM_SHA256" , "TLS_RSA_PSK_WITH_AES_256_GCM_SHA384" , "TLS_PSK_WITH_AES_128_CBC_SHA256" , "TLS_PSK_WITH_AES_256_CBC_SHA384" , "TLS_PSK_WITH_NULL_SHA256" , "TLS_PSK_WITH_NULL_SHA384" , "TLS_DHE_PSK_WITH_AES_128_CBC_SHA256" , "TLS_DHE_PSK_WITH_AES_256_CBC_SHA384" , "TLS_DHE_PSK_WITH_NULL_SHA256" , "TLS_DHE_PSK_WITH_NULL_SHA384" , "TLS_RSA_PSK_WITH_AES_128_CBC_SHA256" , "TLS_RSA_PSK_WITH_AES_256_CBC_SHA384" , "TLS_RSA_PSK_WITH_NULL_SHA256" , "TLS_RSA_PSK_WITH_NULL_SHA384" , "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256" , "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256" , "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256" , "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256" , "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256" , "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256" , "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256" , "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256" , "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256" , "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256" , "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256" , "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256")
ENUM_NEXT (tls_cipher_suite_names , TLS_EMPTY_RENEGOTIATION_INFO_SCSV , TLS_EMPTY_RENEGOTIATION_INFO_SCSV , TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 , "TLS_EMPTY_RENEGOTIATION_INFO_SCSV")
ENUM_NEXT (tls_cipher_suite_names , TLS_ECDH_ECDSA_WITH_NULL_SHA , TLS_ECDHE_PSK_WITH_NULL_SHA384 , TLS_EMPTY_RENEGOTIATION_INFO_SCSV , "TLS_ECDH_ECDSA_WITH_NULL_SHA" , "TLS_ECDH_ECDSA_WITH_RC4_128_SHA" , "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA" , "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA" , "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA" , "TLS_ECDHE_ECDSA_WITH_NULL_SHA" , "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA" , "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA" , "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA" , "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA" , "TLS_ECDH_RSA_WITH_NULL_SHA" , "TLS_ECDH_RSA_WITH_RC4_128_SHA" , "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA" , "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA" , "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA" , "TLS_ECDHE_RSA_WITH_NULL_SHA" , "TLS_ECDHE_RSA_WITH_RC4_128_SHA" , "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA" , "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA" , "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA" , "TLS_ECDH_anon_WITH_NULL_SHA" , "TLS_ECDH_anon_WITH_RC4_128_SHA" , "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA" , "TLS_ECDH_anon_WITH_AES_128_CBC_SHA" , "TLS_ECDH_anon_WITH_AES_256_CBC_SHA" , "TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA" , "TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA" , "TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA" , "TLS_SRP_SHA_WITH_AES_128_CBC_SHA" , "TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA" , "TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA" , "TLS_SRP_SHA_WITH_AES_256_CBC_SHA" , "TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA" , "TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA" , "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256" , "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384" , "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256" , "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384" , "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256" , "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384" , "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256" , "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384" , "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256" , "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384" , "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256" , "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384" , "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" , "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" , "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256" , "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384" , "TLS_ECDHE_PSK_WITH_RC4_128_SHA" , "TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA" , "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA" , "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA" , "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256" , "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384" , "TLS_ECDHE_PSK_WITH_NULL_SHA" , "TLS_ECDHE_PSK_WITH_NULL_SHA256" , "TLS_ECDHE_PSK_WITH_NULL_SHA384")
ENUM_NEXT (tls_client_certificate_type_names , TLS_FORTEZZA_DMS , TLS_FORTEZZA_DMS , TLS_DSS_EPHEMERAL_DH , "FORTEZZA_DMS")
ENUM_NEXT (tls_client_certificate_type_names , TLS_ECDSA_SIGN , TLS_ECDSA_FIXED_ECDH , TLS_FORTEZZA_DMS , "ECDSA_SIGN" , "RSA_FIXED_ECDH" , "ECDSA_FIXED_ECDH")
static bool expand_keys (private_tls_crypto_t * this, chunk_t client_random, chunk_t server_random) static
Expand key material from master secret
Definition at line 1622 of file tls_crypto.c.
References chunk_alloc, chunk_alloca, chunk_cata, chunk_create(), chunk_skip(), FALSE, ivlen, chunk_t::len, prf, chunk_t::ptr, tls, and TRUE.
Referenced by METHOD().
 {
     chunk_t seed, block;
     chunk_t cw_mac, cw, cw_iv;
     chunk_t sw_mac, sw, sw_iv;
     int mklen, eklen, ivlen;
     if (!this->aead_in || !this->aead_out)
     {
         return FALSE;
     }
     /* derive key block for key expansion */
     mklen = this->aead_in->get_mac_key_size(this->aead_in);
     eklen = this->aead_in->get_encr_key_size(this->aead_in);
     ivlen = this->aead_in->get_iv_size(this->aead_in);
     seed = chunk_cata("cc", server_random, client_random);
     block = chunk_alloca((mklen + eklen + ivlen) * 2);
     if (!this->prf->get_bytes(this->prf, "key expansion", seed,
                               block.len, block.ptr))
     {
         return FALSE;
     }
     /* client/server write signer keys */
     cw_mac = chunk_create(block.ptr, mklen);
     block = chunk_skip(block, mklen);
     sw_mac = chunk_create(block.ptr, mklen);
     block = chunk_skip(block, mklen);
     /* client/server write encryption keys */
     cw = chunk_create(block.ptr, eklen);
     block = chunk_skip(block, eklen);
     sw = chunk_create(block.ptr, eklen);
     block = chunk_skip(block, eklen);
     /* client/server write IV; TLS 1.0 implicit IVs or AEAD salt, if any */
     cw_iv = chunk_create(block.ptr, ivlen);
     block = chunk_skip(block, ivlen);
     sw_iv = chunk_create(block.ptr, ivlen);
     block = chunk_skip(block, ivlen);
     if (this->tls->is_server(this->tls))
     {
         if (!this->aead_in->set_keys(this->aead_in, cw_mac, cw, cw_iv) ||
             !this->aead_out->set_keys(this->aead_out, sw_mac, sw, sw_iv))
         {
             return FALSE;
         }
     }
     else
     {
         if (!this->aead_out->set_keys(this->aead_out, cw_mac, cw, cw_iv) ||
             !this->aead_in->set_keys(this->aead_in, sw_mac, sw, sw_iv))
         {
             return FALSE;
         }
     }
     /* EAP-MSK */
     if (this->msk_label)
     {
         seed = chunk_cata("cc", client_random, server_random);
         this->msk = chunk_alloc(64);
         if (!this->prf->get_bytes(this->prf, this->msk_label, seed,
                                   this->msk.len, this->msk.ptr))
         {
             return FALSE;
         }
     }
     return TRUE;
 }
static void filter_cipher_config_suites (private_tls_crypto_t * this, suite_algs_t suites[], int * count) static
Filter suites by cipher user config
Definition at line 816 of file tls_crypto.c.
References count, enumerator_t::destroy, suite_algs_t::encr, ENCR_3DES, ENCR_AES_CBC, ENCR_AES_GCM_ICV16, ENCR_CAMELLIA_CBC, ENCR_NULL, suite_algs_t::encr_size, enumerator_t::enumerate, enumerator_create_token(), settings_t::get_str, lib, library_t::ns, library_t::settings, and strcaseeq().
Referenced by build_cipher_suite_list().
 {
     enumerator_t *enumerator;
     int i, remaining = 0;
     char *token, *config;
     config = lib->settings->get_str(lib->settings, "%s.tls.cipher", NULL,
                                     lib->ns);
     if (config)
     {
         for (i = 0; i < *count; i++)
         {
             enumerator = enumerator_create_token(config, ",", " ");
             while (enumerator->enumerate(enumerator, &token))
             {
                 if (strcaseeq(token, "aes128") &&
                     suites[i].encr == ENCR_AES_CBC &&
                     suites[i].encr_size == 16)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "aes256") &&
                     suites[i].encr == ENCR_AES_CBC &&
                     suites[i].encr_size == 32)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "aes128gcm") &&
                     suites[i].encr == ENCR_AES_GCM_ICV16 &&
                     suites[i].encr_size == 16)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "aes256gcm") &&
                     suites[i].encr == ENCR_AES_GCM_ICV16 &&
                     suites[i].encr_size == 32)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "camellia128") &&
                     suites[i].encr == ENCR_CAMELLIA_CBC &&
                     suites[i].encr_size == 16)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "camellia256") &&
                     suites[i].encr == ENCR_CAMELLIA_CBC &&
                     suites[i].encr_size == 32)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "3des") &&
                     suites[i].encr == ENCR_3DES)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "null") &&
                     suites[i].encr == ENCR_NULL)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
             }
             enumerator->destroy(enumerator);
         }
         *count = remaining;
     }
 }
static void filter_key_exchange_config_suites (private_tls_crypto_t * this, suite_algs_t suites[], int * count) static
Filter suites by key exchange user config
Definition at line 761 of file tls_crypto.c.
References count, enumerator_t::destroy, dh, suite_algs_t::dh, diffie_hellman_group_is_ec(), enumerator_t::enumerate, enumerator_create_token(), settings_t::get_str, suite_algs_t::key, KEY_ECDSA, KEY_RSA, lib, MODP_NONE, library_t::ns, library_t::settings, and strcaseeq().
Referenced by build_cipher_suite_list().
 {
     enumerator_t *enumerator;
     int i, remaining = 0;
     char *token, *config;
     config = lib->settings->get_str(lib->settings, "%s.tls.key_exchange", NULL,
                                     lib->ns);
     if (config)
     {
         for (i = 0; i < *count; i++)
         {
             enumerator = enumerator_create_token(config, ",", " ");
             while (enumerator->enumerate(enumerator, &token))
             {
                 if (strcaseeq(token, "ecdhe-ecdsa") &&
                     diffie_hellman_group_is_ec(suites[i].dh) &&
                     suites[i].key == KEY_ECDSA)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "ecdhe-rsa") &&
                     diffie_hellman_group_is_ec(suites[i].dh) &&
                     suites[i].key == KEY_RSA)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "dhe-rsa") &&
                     !diffie_hellman_group_is_ec(suites[i].dh) &&
                     suites[i].dh != MODP_NONE &&
                     suites[i].key == KEY_RSA)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "rsa") &&
                     suites[i].dh == MODP_NONE &&
                     suites[i].key == KEY_RSA)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
             }
             enumerator->destroy(enumerator);
         }
         *count = remaining;
     }
 }
static void filter_key_suites (private_tls_crypto_t * this, suite_algs_t suites[], int * count, key_type_t key) static
Purge suites using a given key type
Definition at line 741 of file tls_crypto.c.
References count, DBG2, DBG_TLS, and key_type_names.
Referenced by build_cipher_suite_list().
 {
     int i, remaining = 0;
     DBG2(DBG_TLS, "disabling %N suites, no backend found", key_type_names, key);
     for (i = 0; i < *count; i++)
     {
         if (suites[i].key != key)
         {
             suites[remaining] = suites[i];
             remaining++;
         }
     }
     *count = remaining;
 }
static void filter_mac_config_suites (private_tls_crypto_t * this, suite_algs_t suites[], int * count) static
Filter suites by mac user config
Definition at line 896 of file tls_crypto.c.
References AUTH_HMAC_MD5_128, AUTH_HMAC_SHA1_160, AUTH_HMAC_SHA2_256_256, AUTH_HMAC_SHA2_384_384, count, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), settings_t::get_str, lib, suite_algs_t::mac, library_t::ns, library_t::settings, and strcaseeq().
Referenced by build_cipher_suite_list().
 {
     enumerator_t *enumerator;
     int i, remaining = 0;
     char *token, *config;
     config = lib->settings->get_str(lib->settings, "%s.tls.mac", NULL,
                                     lib->ns);
     if (config)
     {
         for (i = 0; i < *count; i++)
         {
             enumerator = enumerator_create_token(config, ",", " ");
             while (enumerator->enumerate(enumerator, &token))
             {
                 if (strcaseeq(token, "md5") &&
                     suites[i].mac == AUTH_HMAC_MD5_128)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "sha1") &&
                     suites[i].mac == AUTH_HMAC_SHA1_160)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "sha256") &&
                     suites[i].mac == AUTH_HMAC_SHA2_256_256)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
                 if (strcaseeq(token, "sha384") &&
                     suites[i].mac == AUTH_HMAC_SHA2_384_384)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
             }
             enumerator->destroy(enumerator);
         }
         *count = remaining;
     }
 }
static void filter_null_suites (suite_algs_t suites[], int * count) static
Purge NULL encryption cipher suites from list
Definition at line 723 of file tls_crypto.c.
References count, and ENCR_NULL.
Referenced by build_cipher_suite_list(), and tls_crypto_get_supported_suites().
 {
     int i, remaining = 0;
     for (i = 0; i < *count; i++)
     {
         if (suites[i].encr != ENCR_NULL)
         {
             suites[remaining] = suites[i];
             remaining++;
         }
     }
     *count = remaining;
 }
static void filter_specific_config_suites (private_tls_crypto_t * this, suite_algs_t suites[], int * count) static
Filter for specific suites specified in strongswan.conf
Definition at line 946 of file tls_crypto.c.
References count, enumerator_t::destroy, enum_from_name, enumerator_t::enumerate, enumerator_create_token(), settings_t::get_str, lib, library_t::ns, library_t::settings, suite_algs_t::suite, and tls_cipher_suite_names.
Referenced by build_cipher_suite_list().
 {
     enumerator_t *enumerator;
     int i, remaining = 0, suite;
     char *token, *config;
     config = lib->settings->get_str(lib->settings, "%s.tls.suites", NULL,
                                     lib->ns);
     if (config)
     {
         for (i = 0; i < *count; i++)
         {
             enumerator = enumerator_create_token(config, ",", " ");
             while (enumerator->enumerate(enumerator, &token))
             {
                 if (enum_from_name(tls_cipher_suite_names, token, &suite) &&
                     suite == suites[i].suite)
                 {
                     suites[remaining++] = suites[i];
                     break;
                 }
             }
             enumerator->destroy(enumerator);
         }
         *count = remaining;
     }
 }
static void filter_suite (suite_algs_t suites[], int * count, int offset, enumerator_t *(*)(crypto_factory_t *) create_enumerator) static
Filter a suite list using a transform enumerator
Definition at line 651 of file tls_crypto.c.
References AUTH_UNDEFINED, count, crypto_factory_t::create_aead_enumerator, crypto_factory_t::create_crypter_enumerator, create_enumerator(), library_t::crypto, enumerator_t::destroy, dh, suite_algs_t::dh, suite_algs_t::encr, ENCR_NULL, encryption_algorithm_is_aead(), enumerator_t::enumerate, suite_algs_t::hash, lib, suite_algs_t::mac, memset, MODP_NONE, offset, and suite_algs_t::prf.
Referenced by filter_unsupported_suites().
 {
     const char *plugin_name;
     suite_algs_t current;
     int *current_alg, i, remaining = 0;
     enumerator_t *enumerator;
     memset(&current, 0, sizeof(current));
     current_alg = (int*)((char*)&current + offset);
     for (i = 0; i < *count; i++)
     {
         if (create_enumerator == lib->crypto->create_crypter_enumerator &&
             encryption_algorithm_is_aead(suites[i].encr))
         {   /* filtering crypters, but current suite uses an AEAD, apply */
             suites[remaining] = suites[i];
             remaining++;
             continue;
         }
         if (create_enumerator == lib->crypto->create_aead_enumerator &&
             !encryption_algorithm_is_aead(suites[i].encr))
         {   /* filtering AEADs, but current suite doesn't use one, apply */
             suites[remaining] = suites[i];
             remaining++;
             continue;
         }
         enumerator = create_enumerator(lib->crypto);
         while (enumerator->enumerate(enumerator, current_alg, &plugin_name))
         {
             if (current.encr && current.encr != suites[i].encr)
             {
                 if (suites[i].encr != ENCR_NULL)
                 {   /* skip, ENCR does not match nor is NULL */
                     continue;
                 }
             }
             if (current.mac && current.mac != suites[i].mac)
             {
                 if (suites[i].mac != AUTH_UNDEFINED)
                 {   /* skip, MAC does not match nor is it undefined */
                     continue;
                 }
             }
             if (current.prf && current.prf != suites[i].prf)
             {   /* skip, PRF does not match */
                 continue;
             }
             if (current.hash && current.hash != suites[i].hash)
             {   /* skip, hash does not match */
                 continue;
             }
             if (current.dh && current.dh != suites[i].dh)
             {
                 if (suites[i].dh != MODP_NONE)
                 {   /* skip DH group, does not match nor NONE */
                     continue;
                 }
             }
             /* suite supported, apply */
             suites[remaining] = suites[i];
             remaining++;
             break;
         }
         enumerator->destroy(enumerator);
     }
     *count = remaining;
 }
static void filter_unsupported_suites (suite_algs_t suites[], int * count) static
Filter out unsupported suites on given suite array
Definition at line 978 of file tls_crypto.c.
References crypto_factory_t::create_aead_enumerator, crypto_factory_t::create_crypter_enumerator, crypto_factory_t::create_dh_enumerator, crypto_factory_t::create_hasher_enumerator, crypto_factory_t::create_prf_enumerator, crypto_factory_t::create_signer_enumerator, library_t::crypto, dh, filter_suite(), hash, lib, and prf.
Referenced by build_cipher_suite_list(), and tls_crypto_get_supported_suites().
 {
     /* filter suite list by each algorithm */
     filter_suite(suites, count, offsetof(suite_algs_t, encr),
                  lib->crypto->create_crypter_enumerator);
     filter_suite(suites, count, offsetof(suite_algs_t, encr),
                  lib->crypto->create_aead_enumerator);
     filter_suite(suites, count, offsetof(suite_algs_t, mac),
                  lib->crypto->create_signer_enumerator);
     filter_suite(suites, count, offsetof(suite_algs_t, prf),
                  lib->crypto->create_prf_enumerator);
     filter_suite(suites, count, offsetof(suite_algs_t, hash),
                  lib->crypto->create_hasher_enumerator);
     filter_suite(suites, count, offsetof(suite_algs_t, dh),
                  lib->crypto->create_dh_enumerator);
 }
static suite_algs_t* find_suite (tls_cipher_suite_t suite) static
Look up algorithms by a suite
Definition at line 634 of file tls_crypto.c.
References countof.
Referenced by hash_data(), and METHOD().
 {
     int i;
     for (i = 0; i < countof(suite_algs); i++)
     {
         if (suite_algs[i].suite == suite)
         {
             return &suite_algs[i];
         }
     }
     return NULL;
 }
static bool group_filter (void * null, diffie_hellman_group_t * in, diffie_hellman_group_t * out, void * dummy1, tls_named_curve_t * curve) static
Filter EC groups, add TLS curve
Definition at line 1302 of file tls_crypto.c.
References countof, curves, FALSE, group, and TRUE.
Referenced by METHOD().
 {
     int i;
     for (i = 0; i < countof(curves); i++)
     {
         if (curves[i].group == *in)
         {
             if (out)
             {
                 *out = curves[i].group;
             }
             if (curve)
             {
                 *curve = curves[i].curve;
             }
             return TRUE;
         }
     }
     return FALSE;
 }
static bool hash_data (private_tls_crypto_t * this, chunk_t data, chunk_t * hash) static
Create a hash using the suites HASH algorithm
Definition at line 1354 of file tls_crypto.c.
References alg, hasher_t::allocate_hash, chunk_clone, chunk_from_thing, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_TLS, hasher_t::destroy, DESTROY_IF, FALSE, find_suite(), hasher_t::get_hash, suite_algs_t::hash, hash_algorithm_names, HASH_MD5, HASH_SHA1, HASH_SIZE_MD5, HASH_SIZE_SHA1, hasher, lib, sha1(), tls, TLS_1_2, and TRUE.
Referenced by METHOD().
 {
     if (this->tls->get_version(this->tls) >= TLS_1_2)
     {
         hasher_t *hasher;
         suite_algs_t *alg;
         alg = find_suite(this->suite);
         if (!alg)
         {
             return FALSE;
         }
         hasher = lib->crypto->create_hasher(lib->crypto, alg->hash);
         if (!hasher || !hasher->allocate_hash(hasher, data, hash))
         {
             DBG1(DBG_TLS, "%N not supported", hash_algorithm_names, alg->hash);
             DESTROY_IF(hasher);
             return FALSE;
         }
         hasher->destroy(hasher);
     }
     else
     {
         hasher_t *md5, *sha1;
         char buf[HASH_SIZE_MD5 + HASH_SIZE_SHA1];
         md5 = lib->crypto->create_hasher(lib->crypto, HASH_MD5);
         if (!md5 || !md5->get_hash(md5, data, buf))
         {
             DBG1(DBG_TLS, "%N not supported", hash_algorithm_names, HASH_MD5);
             DESTROY_IF(md5);
             return FALSE;
         }
         md5->destroy(md5);
         sha1 = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
         if (!sha1 || !sha1->get_hash(sha1, data, buf + HASH_SIZE_MD5))
         {
             DBG1(DBG_TLS, "%N not supported", hash_algorithm_names, HASH_SHA1);
             DESTROY_IF(sha1);
             return FALSE;
         }
         sha1->destroy(sha1);
         *hash = chunk_clone(chunk_from_thing(buf));
     }
     return TRUE;
 }
static signature_scheme_t hashsig_to_scheme (key_type_t type, tls_hash_algorithm_t hash, tls_signature_algorithm_t sig) static
Get the signature scheme from a TLS 1.2 hash/sig algorithm pair
Definition at line 1265 of file tls_crypto.c.
References countof, KEY_ECDSA, KEY_RSA, schemes, SIGN_UNKNOWN, TLS_SIG_ECDSA, and TLS_SIG_RSA.
Referenced by METHOD().
 {
     int i;
     if ((sig == TLS_SIG_RSA && type == KEY_RSA) ||
         (sig == TLS_SIG_ECDSA && type == KEY_ECDSA))
     {
         for (i = 0; i < countof(schemes); i++)
         {
             if (schemes[i].sig == sig && schemes[i].hash == hash)
             {
                 return schemes[i].scheme;
             }
         }
     }
     return SIGN_UNKNOWN;
 }
METHOD (tls_crypto_t , get_cipher_suites , int , private_tls_crypto_t * this, tls_cipher_suite_t ** suites)
Definition at line 1043 of file tls_crypto.c.
 {
     *suites = this->suites;
     return this->suite_count;
 }
METHOD (tls_crypto_t , select_cipher_suite , tls_cipher_suite_t , private_tls_crypto_t * this, tls_cipher_suite_t * suites, int count, key_type_t key)
Definition at line 1166 of file tls_crypto.c.
References algs, count, create_ciphers(), find_suite(), suite_algs_t::key, and KEY_ANY.
 {
     suite_algs_t *algs;
     int i, j;
     for (i = 0; i < this->suite_count; i++)
     {
         for (j = 0; j < count; j++)
         {
             if (this->suites[i] == suites[j])
             {
                 algs = find_suite(this->suites[i]);
                 if (algs)
                 {
                     if (key == KEY_ANY || key == algs->key)
                     {
                         if (create_ciphers(this, algs))
{
                             this->suite = this->suites[i];
                             return this->suite;
                         }
                     }
                 }
             }
         }
     }
     return 0;
 }
METHOD (tls_crypto_t , get_dh_group , diffie_hellman_group_t , private_tls_crypto_t * this)
Definition at line 1197 of file tls_crypto.c.
References algs, suite_algs_t::dh, find_suite(), and MODP_NONE.
 {
     suite_algs_t *algs;
     algs = find_suite(this->suite);
     if (algs)
     {
         return algs->dh;
     }
     return MODP_NONE;
 }
METHOD (tls_crypto_t , get_signature_algorithms , void , private_tls_crypto_t * this, bio_writer_t * writer)
Definition at line 1230 of file tls_crypto.c.
References bio_writer_create(), countof, bio_writer_t::destroy, ecdsa, bio_writer_t::get_buf, plugin_loader_t::has_feature, hash, lib, PLUGIN_PROVIDE, library_t::plugins, rsa, scheme, schemes, sig, TLS_SIG_ECDSA, TLS_SIG_RSA, bio_writer_t::wrap16, bio_writer_t::write_data16, and bio_writer_t::write_uint8.
 {
     bio_writer_t *supported;
     int i;
     supported = bio_writer_create(32);
     for (i = 0; i < countof(schemes); i++)
     {
         if (schemes[i].sig == TLS_SIG_RSA && !this->rsa)
         {
             continue;
         }
         if (schemes[i].sig == TLS_SIG_ECDSA && !this->ecdsa)
         {
             continue;
         }
         if (!lib->plugins->has_feature(lib->plugins,
                         PLUGIN_PROVIDE(PUBKEY_VERIFY, schemes[i].scheme)))
         {
             continue;
         }
         supported->write_uint8(supported, schemes[i].hash);
         supported->write_uint8(supported, schemes[i].sig);
     }
     supported->wrap16(supported);
     writer->write_data16(writer, supported->get_buf(supported));
     supported->destroy(supported);
 }
METHOD (tls_crypto_t , create_ec_enumerator , enumerator_t * , private_tls_crypto_t * this)
Definition at line 1326 of file tls_crypto.c.
References crypto_factory_t::create_dh_enumerator, library_t::crypto, enumerator_create_filter(), group_filter(), and lib.
 {
     return enumerator_create_filter(
                     lib->crypto->create_dh_enumerator(lib->crypto),
                     (void*)group_filter, NULL, NULL);
 }
METHOD (tls_crypto_t , set_protection , void , private_tls_crypto_t * this, tls_protection_t * protection)
Definition at line 1334 of file tls_crypto.c.
 {
     this->protection = protection;
 }
METHOD (tls_crypto_t , append_handshake , void , private_tls_crypto_t * this, tls_handshake_type_t type, chunk_t data)
Definition at line 1340 of file tls_crypto.c.
References chunk_cat, chunk_from_thing, and chunk_t::len.
 {
     u_int32_t header;
     /* reconstruct handshake header */
     header = htonl(data.len | (type << 24));
     this->handshake = chunk_cat("mcc", this->handshake,
                                 chunk_from_thing(header), data);
 }
METHOD (tls_crypto_t , sign , bool , private_tls_crypto_t * this, private_key_t * key, bio_writer_t * writer, chunk_t data, chunk_t hashsig)
Definition at line 1402 of file tls_crypto.c.
References alg, bio_reader_create(), chunk_from_chars, DBG1, DBG2, DBG_TLS, bio_reader_t::destroy, FALSE, free(), private_key_t::get_type, hash, hash_data(), hashsig_to_scheme(), KEY_ECDSA, KEY_RSA, chunk_t::len, chunk_t::ptr, bio_reader_t::read_uint8, bio_reader_t::remaining, scheme, sig, private_key_t::sign, SIGN_ECDSA_WITH_SHA1_DER, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_UNKNOWN, tls, TLS_1_2, tls_hash_algorithm_names, TLS_HASH_SHA1, TLS_SIG_ECDSA, TLS_SIG_RSA, tls_signature_algorithm_names, TRUE, bio_writer_t::write_data16, and bio_writer_t::write_uint8.
 {
     if (this->tls->get_version(this->tls) >= TLS_1_2)
     {
         signature_scheme_t scheme;
         bio_reader_t *reader;
         u_int8_t hash, alg;
         chunk_t sig;
         bool done = FALSE;
         if (!hashsig.len)
         {   /* fallback if none given */
             hashsig = chunk_from_chars(
                 TLS_HASH_SHA1, TLS_SIG_RSA, TLS_HASH_SHA1, TLS_SIG_ECDSA);
         }
         reader = bio_reader_create(hashsig);
         while (reader->remaining(reader) >= 2)
         {
             if (reader->read_uint8(reader, &hash) &&
                 reader->read_uint8(reader, &alg))
             {
                 scheme = hashsig_to_scheme(key->get_type(key), hash, alg);
                 if (scheme != SIGN_UNKNOWN &&
                     key->sign(key, scheme, data, &sig))
                 {
                     done = TRUE;
                     break;
                 }
             }
         }
         reader->destroy(reader);
         if (!done)
         {
             DBG1(DBG_TLS, "none of the proposed hash/sig algorithms supported");
             return FALSE;
         }
         DBG2(DBG_TLS, "created signature with %N/%N",
              tls_hash_algorithm_names, hash, tls_signature_algorithm_names, alg);
         writer->write_uint8(writer, hash);
         writer->write_uint8(writer, alg);
         writer->write_data16(writer, sig);
         free(sig.ptr);
     }
     else
     {
         chunk_t sig, hash;
         bool done;
         switch (key->get_type(key))
         {
             case KEY_RSA:
                 if (!hash_data(this, data, &hash))
                 {
                     return FALSE;
                 }
                 done = key->sign(key, SIGN_RSA_EMSA_PKCS1_NULL, hash, &sig);
                 free(hash.ptr);
                 if (!done)
                 {
                     return FALSE;
                 }
                 DBG2(DBG_TLS, "created signature with MD5+SHA1/RSA");
                 break;
             case KEY_ECDSA:
                 if (!key->sign(key, SIGN_ECDSA_WITH_SHA1_DER, data, &sig))
                 {
                     return FALSE;
                 }
                 DBG2(DBG_TLS, "created signature with SHA1/ECDSA");
                 break;
             default:
                 return FALSE;
         }
         writer->write_data16(writer, sig);
         free(sig.ptr);
     }
     return TRUE;
 }
METHOD (tls_crypto_t , verify , bool , private_tls_crypto_t * this, public_key_t * key, bio_reader_t * reader, chunk_t data)
Definition at line 1483 of file tls_crypto.c.
References alg, DBG1, DBG2, DBG_TLS, FALSE, free(), public_key_t::get_type, hash, hash_data(), hashsig_to_scheme(), KEY_ECDSA, KEY_RSA, chunk_t::ptr, bio_reader_t::read_data16, bio_reader_t::read_uint8, scheme, sig, SIGN_ECDSA_WITH_SHA1_DER, SIGN_RSA_EMSA_PKCS1_NULL, SIGN_UNKNOWN, tls, TLS_1_2, tls_hash_algorithm_names, tls_signature_algorithm_names, TRUE, and public_key_t::verify.
 {
     if (this->tls->get_version(this->tls) >= TLS_1_2)
     {
         signature_scheme_t scheme = SIGN_UNKNOWN;
         u_int8_t hash, alg;
         chunk_t sig;
         if (!reader->read_uint8(reader, &hash) ||
             !reader->read_uint8(reader, &alg) ||
             !reader->read_data16(reader, &sig))
         {
             DBG1(DBG_TLS, "received invalid signature");
             return FALSE;
         }
         scheme = hashsig_to_scheme(key->get_type(key), hash, alg);
         if (scheme == SIGN_UNKNOWN)
         {
             DBG1(DBG_TLS, "signature algorithms %N/%N not supported",
                  tls_hash_algorithm_names, hash,
                  tls_signature_algorithm_names, alg);
             return FALSE;
         }
         if (!key->verify(key, scheme, data, sig))
         {
             return FALSE;
         }
         DBG2(DBG_TLS, "verified signature with %N/%N",
              tls_hash_algorithm_names, hash, tls_signature_algorithm_names, alg);
     }
     else
     {
         chunk_t sig, hash;
         bool done;
         if (!reader->read_data16(reader, &sig))
         {
             DBG1(DBG_TLS, "received invalid signature");
             return FALSE;
         }
         switch (key->get_type(key))
         {
             case KEY_RSA:
                 if (!hash_data(this, data, &hash))
                 {
                     return FALSE;
                 }
                 done = key->verify(key, SIGN_RSA_EMSA_PKCS1_NULL, hash, sig);
                 free(hash.ptr);
                 if (!done)
                 {
                     return FALSE;
                 }
                 DBG2(DBG_TLS, "verified signature data with MD5+SHA1/RSA");
                 break;
             case KEY_ECDSA:
                 if (!key->verify(key, SIGN_ECDSA_WITH_SHA1_DER, data, sig))
                 {
                     return FALSE;
                 }
                 DBG2(DBG_TLS, "verified signature with SHA1/ECDSA");
                 break;
             default:
                 return FALSE;
         }
     }
     return TRUE;
 }
METHOD (tls_crypto_t , sign_handshake , bool , private_tls_crypto_t * this, private_key_t * key, bio_writer_t * writer, chunk_t hashsig)
Definition at line 1554 of file tls_crypto.c.
References sign().
 {
     return sign(this, key, writer, this->handshake, hashsig);
 }
METHOD (tls_crypto_t , verify_handshake , bool , private_tls_crypto_t * this, public_key_t * key, bio_reader_t * reader)
Definition at line 1561 of file tls_crypto.c.
References verify().
 {
     return verify(this, key, reader, this->handshake);
 }
METHOD (tls_crypto_t , calculate_finished , bool , private_tls_crypto_t * this, char * label, char out[12])
Definition at line 1567 of file tls_crypto.c.
References FALSE, free(), hash_data(), prf, chunk_t::ptr, and TRUE.
 {
     chunk_t seed;
     if (!this->prf)
     {
         return FALSE;
     }
     if (!hash_data(this, this->handshake, &seed))
     {
         return FALSE;
     }
     if (!this->prf->get_bytes(this->prf, label, seed, 12, out))
     {
         free(seed.ptr);
         return FALSE;
     }
     free(seed.ptr);
     return TRUE;
 }
METHOD (tls_crypto_t , derive_secrets , bool , private_tls_crypto_t * this, chunk_t premaster, chunk_t session, identification_t * id, chunk_t client_random, chunk_t server_random)
Definition at line 1696 of file tls_crypto.c.
References derive_master(), and expand_keys().
 {
     return derive_master(this, premaster, session, id,
                          client_random, server_random) &&
            expand_keys(this, client_random, server_random);
 }
METHOD (tls_crypto_t , resume_session , tls_cipher_suite_t , private_tls_crypto_t * this, chunk_t session, identification_t * id, chunk_t client_random, chunk_t server_random)
Definition at line 1705 of file tls_crypto.c.
References cache(), chunk_clear(), expand_keys(), KEY_ANY, chunk_t::len, and prf.
 {
     chunk_t master;
     if (this->cache && session.len)
     {
         this->suite = this->cache->lookup(this->cache, session, id, &master);
         if (this->suite)
         {
             this->suite = select_cipher_suite(this, &this->suite, 1, KEY_ANY);
             if (this->suite)
             {
                 if (!this->prf->set_key(this->prf, master) ||
                     !expand_keys(this, client_random, server_random))
                 {
                     this->suite = 0;
                 }
             }
             chunk_clear(&master);
         }
         return this->suite;
     }
     return 0;
 }
METHOD (tls_crypto_t , get_session , chunk_t , private_tls_crypto_t * this, identification_t * server)
Definition at line 1732 of file tls_crypto.c.
References cache(), and chunk_empty.
 {
     if (this->cache)
     {
         return this->cache->check(this->cache, server);
     }
     return chunk_empty;
 }
METHOD (tls_crypto_t , change_cipher , void , private_tls_crypto_t * this, bool inbound)
Definition at line 1742 of file tls_crypto.c.
References FALSE, and TRUE.
 {
     if (this->protection)
     {
         if (inbound)
         {
             this->protection->set_cipher(this->protection, TRUE, this->aead_in);
         }
         else
         {
             this->protection->set_cipher(this->protection, FALSE, this->aead_out);
         }
     }
 }
METHOD (tls_crypto_t , get_eap_msk , chunk_t , private_tls_crypto_t * this)
Definition at line 1758 of file tls_crypto.c.
 {
     return this->msk;
 }
METHOD (tls_crypto_t , destroy , void , private_tls_crypto_t * this)
Definition at line 1764 of file tls_crypto.c.
References destroy_aeads(), DESTROY_IF, free(), and prf.
 {
     destroy_aeads(this);
     free(this->handshake.ptr);
     free(this->msk.ptr);
     DESTROY_IF(this->prf);
     free(this->suites);
     free(this);
 }
Variable Documentation
tls_named_curve_t curve
Definition at line 1290 of file tls_crypto.c.
Referenced by ec_group_to_curve(), ec_key_new_brainpool(), process_ec_key_exchange(), send_client_hello(), send_server_key_exchange(), and write_ec_identifier().
struct { ... } curves[]
Initial value:
= {
    { ECP_256_BIT, TLS_SECP256R1},
    { ECP_384_BIT, TLS_SECP384R1},
    { ECP_521_BIT, TLS_SECP521R1},
    { ECP_224_BIT, TLS_SECP224R1},
    { ECP_192_BIT, TLS_SECP192R1},
}
Mapping groups to TLS named curves
Referenced by group_filter(), METHOD(), peer_supports_curve(), process_client_hello(), and send_client_hello().
diffie_hellman_group_t group
Definition at line 1289 of file tls_crypto.c.
Referenced by group_filter().
tls_hash_algorithm_t hash
Definition at line 1215 of file tls_crypto.c.
Referenced by add(), bench_hasher(), build_cert_payload(), build_curve_signature(), build_der_signature(), build_emsa_pkcs1_signature(), build_natd_payload(), check_and_put_init_hash(), cookie_build(), coupling_validator_create(), create_inner_cdp_hashandurl(), filter_unsupported_suites(), generate_message(), get_init_hash(), get_internal(), guest_hash(), guest_hash_create(), hash_password(), hash_ts_array(), hybrid_authenticator_create(), insert_file_hash(), list_algs(), login(), main(), METHOD(), METHOD2(), parse_PFX(), pbkdf1(), pem_decrypt(), pkcs11_signature_scheme_to_mech(), process_payloads(), pts_file_meas_create_from_path(), send_supported_hash_algorithms(), sha1(), sign_pkcs1(), try_get_cert(), verify_curve_signature(), verify_der_signature(), verify_emsa_pkcs1_signature(), and verify_pkcs1().
signature_scheme_t scheme
Definition at line 1216 of file tls_crypto.c.
Referenced by METHOD().
struct { ... } schemes[]
Initial value:
= {
    { TLS_SIG_ECDSA,    TLS_HASH_SHA256,    SIGN_ECDSA_WITH_SHA256_DER  },
    { TLS_SIG_ECDSA,    TLS_HASH_SHA384,    SIGN_ECDSA_WITH_SHA384_DER  },
    { TLS_SIG_ECDSA,    TLS_HASH_SHA512,    SIGN_ECDSA_WITH_SHA512_DER  },
    { TLS_SIG_ECDSA,    TLS_HASH_SHA1,      SIGN_ECDSA_WITH_SHA1_DER    },
    { TLS_SIG_RSA,      TLS_HASH_SHA256,    SIGN_RSA_EMSA_PKCS1_SHA256  },
    { TLS_SIG_RSA,      TLS_HASH_SHA384,    SIGN_RSA_EMSA_PKCS1_SHA384  },
    { TLS_SIG_RSA,      TLS_HASH_SHA512,    SIGN_RSA_EMSA_PKCS1_SHA512  },
    { TLS_SIG_RSA,      TLS_HASH_SHA224,    SIGN_RSA_EMSA_PKCS1_SHA224  },
    { TLS_SIG_RSA,      TLS_HASH_SHA1,      SIGN_RSA_EMSA_PKCS1_SHA1    },
    { TLS_SIG_RSA,      TLS_HASH_MD5,       SIGN_RSA_EMSA_PKCS1_MD5     },
}
Map signature schemes to TLS key types and hashes, ordered by preference
Referenced by hashsig_to_scheme(), and METHOD().
tls_signature_algorithm_t sig
Definition at line 1214 of file tls_crypto.c.
Referenced by build_der_signature(), build_signature(), burn_signer(), hybrid_authenticator_create(), main(), METHOD(), process_cert_verify(), run(), sign_bliss(), sigwaitinfo(), test_good_sig(), verify_bliss(), verify_pkcs1(), verify_raw(), and verify_signature().
suite_algs_t suite_algs[] static
Mapping suites to a set of algorithms
Definition at line 423 of file tls_crypto.c.