strongSwan: led_plugin.c File Reference
led_plugin.c File Reference
#include "led_plugin.h"
#include "led_listener.h"
#include <daemon.h>
Classes
struct private_led_plugin_t
Typedefs
typedef struct private_led_plugin_t private_led_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_led_plugin_t *this)
static bool plugin_cb (private_led_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_led_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_led_plugin_t *this)
plugin_t * led_plugin_create ()
Typedef Documentation
typedef struct private_led_plugin_t private_led_plugin_t
Definition at line 22 of file led_plugin.c.
Function Documentation
plugin_t* led_plugin_create ()
Plugin constructor
Definition at line 84 of file led_plugin.c.
References INIT, and led_listener_create().
 {
     private_led_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
         .listener = led_listener_create(),
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_led_plugin_t * this)
Definition at line 40 of file led_plugin.c.
 {
     return "led";
 }
METHOD (plugin_t , get_features , int , private_led_plugin_t * this, plugin_feature_t * features[])
Definition at line 63 of file led_plugin.c.
References countof, PLUGIN_CALLBACK, plugin_cb(), and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "led"),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_led_plugin_t * this)
Definition at line 74 of file led_plugin.c.
References tkm_listener_t::destroy, free(), and listener.
 {
     this->listener->destroy(this->listener);
     free(this);
 }
static bool plugin_cb (private_led_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 49 of file led_plugin.c.
References bus_t::add_listener, daemon_t::bus, charon, bus_t::remove_listener, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
     }
     return TRUE;
 }