strongSwan: pkcs1_builder.c File Reference
pkcs1_builder.c File Reference
#include "pkcs1_builder.h"
#include <utils/debug.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <credentials/keys/private_key.h>
Macros
#define PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM 1
#define PKINFO_SUBJECT_PUBLIC_KEY 2
#define PUB_KEY_RSA_PUBLIC_KEY 0
#define PUB_KEY_MODULUS 1
#define PUB_KEY_EXPONENT 2
#define PRIV_KEY_VERSION 1
#define PRIV_KEY_MODULUS 2
#define PRIV_KEY_PUB_EXP 3
#define PRIV_KEY_PRIV_EXP 4
#define PRIV_KEY_PRIME1 5
#define PRIV_KEY_PRIME2 6
#define PRIV_KEY_EXP1 7
#define PRIV_KEY_EXP2 8
#define PRIV_KEY_COEFF 9
Functions
static public_key_t * parse_public_key (chunk_t blob)
static public_key_t * parse_rsa_public_key (chunk_t blob)
static private_key_t * parse_rsa_private_key (chunk_t blob)
public_key_t * pkcs1_public_key_load (key_type_t type, va_list args)
private_key_t * pkcs1_private_key_load (key_type_t type, va_list args)
Variables
static const asn1Object_t pkinfoObjects []
static const asn1Object_t pubkeyObjects []
static const asn1Object_t privkeyObjects []
Macro Definition Documentation
#define PKINFO_SUBJECT_PUBLIC_KEY 2
Definition at line 36 of file pkcs1_builder.c.
Referenced by parse_public_key().
#define PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM 1
Definition at line 35 of file pkcs1_builder.c.
Referenced by parse_public_key().
#define PRIV_KEY_COEFF 9
Definition at line 184 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_EXP1 7
Definition at line 182 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_EXP2 8
Definition at line 183 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_MODULUS 2
Definition at line 177 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_PRIME1 5
Definition at line 180 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_PRIME2 6
Definition at line 181 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_PRIV_EXP 4
Definition at line 179 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_PUB_EXP 3
Definition at line 178 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PRIV_KEY_VERSION 1
Definition at line 176 of file pkcs1_builder.c.
Referenced by parse_rsa_private_key().
#define PUB_KEY_EXPONENT 2
Definition at line 115 of file pkcs1_builder.c.
Referenced by parse_rsa_public_key().
#define PUB_KEY_MODULUS 1
Definition at line 114 of file pkcs1_builder.c.
Referenced by parse_rsa_public_key().
#define PUB_KEY_RSA_PUBLIC_KEY 0
Definition at line 113 of file pkcs1_builder.c.
Function Documentation
static public_key_t* parse_public_key (chunk_t blob) static
Load a generic public key from an ASN.1 encoded blob
Definition at line 41 of file pkcs1_builder.c.
References asn1_parse_algorithmIdentifier(), asn1_parser_create(), BUILD_BLOB_ASN1_DER, BUILD_END, chunk_skip(), credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, DBG2, DBG_ASN, asn1_parser_t::destroy, end, asn1_parser_t::get_level, asn1_parser_t::iterate, key, KEY_ANY, KEY_BLISS, KEY_ECDSA, KEY_RSA, len, lib, OID_BLISS_PUBLICKEY, OID_EC_PUBLICKEY, OID_RSA_ENCRYPTION, OID_RSAES_OAEP, parser, PKINFO_SUBJECT_PUBLIC_KEY, PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM, and type.
Referenced by pkcs1_public_key_load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     public_key_t *key = NULL;
     key_type_t type = KEY_ANY;
     parser = asn1_parser_create(pkinfoObjects, blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case PKINFO_SUBJECT_PUBLIC_KEY_ALGORITHM:
             {
                 int oid = asn1_parse_algorithmIdentifier(object,
                                         parser->get_level(parser)+1, NULL);
                 if (oid == OID_RSA_ENCRYPTION || oid == OID_RSAES_OAEP)
                 {
                     type = KEY_RSA;
                 }
                 else if (oid == OID_EC_PUBLICKEY)
                 {
                     /* Need the whole subjectPublicKeyInfo for EC public keys */
                     key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY,
                                 KEY_ECDSA, BUILD_BLOB_ASN1_DER, blob, BUILD_END);
                     goto end;
                 }
                 else if (oid == OID_BLISS_PUBLICKEY)
                 {
                     /* Need the whole subjectPublicKeyInfo for BLISS public keys */
                     key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY,
                                 KEY_BLISS, BUILD_BLOB_ASN1_DER, blob, BUILD_END);
                     goto end;
                 }
                 else
                 {
                     /* key type not supported */
                     goto end;
                 }
                 break;
             }
             case PKINFO_SUBJECT_PUBLIC_KEY:
                 if (object.len > 0 && *object.ptr == 0x00)
                 {
                     /* skip initial bit string octet defining 0 unused bits */
                     object = chunk_skip(object, 1);
                 }
                 DBG2(DBG_ASN, "-- > --");
                 key = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, type,
                                          BUILD_BLOB_ASN1_DER, object, BUILD_END);
                 DBG2(DBG_ASN, "-- < --");
                 break;
         }
     }
 end:
     parser->destroy(parser);
     return key;
 }
static private_key_t* parse_rsa_private_key (chunk_t blob) static
Load a RSA private key from a ASN1 encoded blob.
Definition at line 189 of file pkcs1_builder.c.
References asn1_parser_create(), BUILD_END, BUILD_RSA_COEFF, BUILD_RSA_EXP1, BUILD_RSA_EXP2, BUILD_RSA_MODULUS, BUILD_RSA_PRIME1, BUILD_RSA_PRIME2, BUILD_RSA_PRIV_EXP, BUILD_RSA_PUB_EXP, credential_factory_t::create, CRED_PRIVATE_KEY, library_t::creds, DBG1, DBG_ASN, asn1_parser_t::destroy, end, FALSE, asn1_parser_t::iterate, KEY_RSA, len, lib, n, parser, PRIV_KEY_COEFF, PRIV_KEY_EXP1, PRIV_KEY_EXP2, PRIV_KEY_MODULUS, PRIV_KEY_PRIME1, PRIV_KEY_PRIME2, PRIV_KEY_PRIV_EXP, PRIV_KEY_PUB_EXP, PRIV_KEY_VERSION, q, asn1_parser_t::set_flags, asn1_parser_t::success, and TRUE.
Referenced by pkcs1_private_key_load().
 {
     chunk_t n, e, d, p, q, exp1, exp2, coeff;
     asn1_parser_t *parser;
     chunk_t object;
     int objectID ;
     bool success = FALSE;
     parser = asn1_parser_create(privkeyObjects, blob);
     parser->set_flags(parser, FALSE, TRUE);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case PRIV_KEY_VERSION:
                 if (object.len > 0 && *object.ptr != 0)
                 {
                     DBG1(DBG_ASN, "PKCS#1 private key format is not version 1");
                     goto end;
                 }
                 break;
             case PRIV_KEY_MODULUS:
                 n = object;
                 break;
             case PRIV_KEY_PUB_EXP:
                 e = object;
                 break;
             case PRIV_KEY_PRIV_EXP:
                 d = object;
                 break;
             case PRIV_KEY_PRIME1:
                 p = object;
                 break;
             case PRIV_KEY_PRIME2:
                 q = object;
                 break;
             case PRIV_KEY_EXP1:
                 exp1 = object;
                 break;
             case PRIV_KEY_EXP2:
                 exp2 = object;
                 break;
             case PRIV_KEY_COEFF:
                 coeff = object;
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     if (!success)
     {
         return NULL;
     }
     return lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_RSA,
             BUILD_RSA_MODULUS, n, BUILD_RSA_PUB_EXP, e, BUILD_RSA_PRIV_EXP, d,
             BUILD_RSA_PRIME1, p,  BUILD_RSA_PRIME2, q, BUILD_RSA_EXP1, exp1,
             BUILD_RSA_EXP2, exp2, BUILD_RSA_COEFF, coeff, BUILD_END);
 }
static public_key_t* parse_rsa_public_key (chunk_t blob) static
Load a RSA public key from an ASN.1 encoded blob.
Definition at line 120 of file pkcs1_builder.c.
References asn1_parser_create(), BUILD_END, BUILD_RSA_MODULUS, BUILD_RSA_PUB_EXP, credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, asn1_parser_t::destroy, FALSE, asn1_parser_t::iterate, KEY_RSA, lib, n, parser, PUB_KEY_EXPONENT, PUB_KEY_MODULUS, and asn1_parser_t::success.
Referenced by pkcs1_public_key_load().
 {
     chunk_t n, e;
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool success = FALSE;
     parser = asn1_parser_create(pubkeyObjects, blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case PUB_KEY_MODULUS:
                 n = object;
                 break;
             case PUB_KEY_EXPONENT:
                 e = object;
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     if (!success)
     {
         return NULL;
     }
     return lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_RSA,
                         BUILD_RSA_MODULUS, n, BUILD_RSA_PUB_EXP, e, BUILD_END);
 }
Variable Documentation
const asn1Object_t pkinfoObjects[] static
Initial value:
= {
    { 0, "subjectPublicKeyInfo",ASN1_SEQUENCE,      ASN1_NONE   },
    { 1,   "algorithm",         ASN1_EOC,           ASN1_RAW    },
    { 1,   "subjectPublicKey",  ASN1_BIT_STRING,    ASN1_BODY   },
    { 0, "exit",                ASN1_EOC,           ASN1_EXIT   }
}
ASN.1 definition of a subjectPublicKeyInfo structure
Definition at line 29 of file pkcs1_builder.c.
const asn1Object_t privkeyObjects[] static
Initial value:
= {
    { 0, "RSAPrivateKey",       ASN1_SEQUENCE,     ASN1_NONE },
    { 1,   "version",           ASN1_INTEGER,      ASN1_BODY },
    { 1,   "modulus",           ASN1_INTEGER,      ASN1_BODY },
    { 1,   "publicExponent",    ASN1_INTEGER,      ASN1_BODY },
    { 1,   "privateExponent",   ASN1_INTEGER,      ASN1_BODY },
    { 1,   "prime1",            ASN1_INTEGER,      ASN1_BODY },
    { 1,   "prime2",            ASN1_INTEGER,      ASN1_BODY },
    { 1,   "exponent1",         ASN1_INTEGER,      ASN1_BODY },
    { 1,   "exponent2",         ASN1_INTEGER,      ASN1_BODY },
    { 1,   "coefficient",       ASN1_INTEGER,      ASN1_BODY },
    { 1,   "otherPrimeInfos",   ASN1_SEQUENCE,     ASN1_OPT |
                                                   ASN1_LOOP },
    { 2,     "otherPrimeInfo",  ASN1_SEQUENCE,     ASN1_NONE },
    { 3,       "prime",         ASN1_INTEGER,      ASN1_BODY },
    { 3,       "exponent",      ASN1_INTEGER,      ASN1_BODY },
    { 3,       "coefficient",   ASN1_INTEGER,      ASN1_BODY },
    { 1,   "end opt or loop",   ASN1_EOC,          ASN1_END  },
    { 0, "exit",                ASN1_EOC,          ASN1_EXIT }
}
ASN.1 definition of a PKCS#1 RSA private key
Definition at line 156 of file pkcs1_builder.c.
const asn1Object_t pubkeyObjects[] static
Initial value:
= {
    { 0, "RSAPublicKey",        ASN1_SEQUENCE,  ASN1_OBJ  },
    { 1,   "modulus",           ASN1_INTEGER,   ASN1_BODY },
    { 1,   "publicExponent",    ASN1_INTEGER,   ASN1_BODY },
    { 0, "exit",                ASN1_EOC,       ASN1_EXIT }
}
ASN.1 definition of RSApublicKey
Definition at line 107 of file pkcs1_builder.c.