strongSwan: ha_dispatcher
ha_dispatcher
ha
Classes
struct ha_dispatcher_t
Typedefs
typedef struct ha_dispatcher_t ha_dispatcher_t
Functions
ha_dispatcher_t * ha_dispatcher_create (ha_socket_t *socket, ha_segments_t *segments, ha_cache_t *cache, ha_kernel_t *kernel, ha_attribute_t *attr)
Detailed Description
Typedef Documentation
typedef struct ha_dispatcher_t ha_dispatcher_t
Definition at line 30 of file ha_dispatcher.h.
Function Documentation
ha_dispatcher_t* ha_dispatcher_create (ha_socket_t * socket, ha_segments_t * segments, ha_cache_t * cache, ha_kernel_t * kernel, ha_attribute_t * attr)
Create a ha_dispatcher instance pulling from socket.
Parameters
socket socket to pull messages from
segments segments to control based on received messages
cache message cache to use for resynchronization
kernel kernel helper
attr HA enabled pool
Returns
dispatcher object
See header
Definition at line 1069 of file ha_dispatcher.c.
References cache(), callback_job_create_with_prio(), dispatch(), INIT, JOB_PRIO_CRITICAL, lib, library_t::processor, processor_t::queue_job, return_false(), and socket.
Referenced by initialize_plugin().
 {
     private_ha_dispatcher_t *this;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
         .socket = socket,
         .segments = segments,
         .cache = cache,
         .kernel = kernel,
         .attr = attr,
     );
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create_with_prio((callback_job_cb_t)dispatch, this,
                 NULL, (callback_job_cancel_t)return_false, JOB_PRIO_CRITICAL));
     return &this->public;
 }