strongSwan: medcli_plugin.c File Reference
medcli_plugin.c File Reference
#include "medcli_plugin.h"
#include "medcli_creds.h"
#include "medcli_config.h"
#include "medcli_listener.h"
#include <daemon.h>
Classes
struct private_medcli_plugin_t
Typedefs
typedef struct
private_medcli_plugin_t private_medcli_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_medcli_plugin_t *this)
static bool open_database (private_medcli_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_medcli_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_medcli_plugin_t *this)
plugin_t * medcli_plugin_create ()
Typedef Documentation
typedef struct private_medcli_plugin_t private_medcli_plugin_t
Definition at line 25 of file medcli_plugin.c.
Function Documentation
plugin_t* medcli_plugin_create ()
Definition at line 131 of file medcli_plugin.c.
References INIT.
 {
     private_medcli_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_medcli_plugin_t * this)
Definition at line 58 of file medcli_plugin.c.
 {
     return "medcli";
 }
METHOD (plugin_t , get_features , int , private_medcli_plugin_t * this, plugin_feature_t * features[])
Definition at line 110 of file medcli_plugin.c.
References countof, DB_ANY, open_database(), PLUGIN_CALLBACK, PLUGIN_DEPENDS, and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)open_database, NULL),
             PLUGIN_PROVIDE(CUSTOM, "medcli"),
                 PLUGIN_DEPENDS(DATABASE, DB_ANY),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_medcli_plugin_t * this)
Definition at line 122 of file medcli_plugin.c.
References free().
 {
     free(this);
 }
static bool open_database (private_medcli_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Connect to database
Definition at line 67 of file medcli_plugin.c.
References backend_manager_t::add_backend, bus_t::add_listener, credential_manager_t::add_set, daemon_t::backends, daemon_t::bus, charon, database_factory_t::create, library_t::credmgr, creds, db, library_t::db, DBG1, DBG_CFG, tkm_listener_t::destroy, mem_cred_t::destroy, database_t::destroy, FALSE, settings_t::get_str, lib, listener, medcli_config_create(), medcli_creds_create(), medcli_listener_create(), backend_manager_t::remove_backend, bus_t::remove_listener, credential_manager_t::remove_set, library_t::settings, TRUE, and uri.
Referenced by METHOD().
 {
     if (reg)
     {
         char *uri;
         uri = lib->settings->get_str(lib->settings,
                                      "medcli.database", NULL);
         if (!uri)
         {
             DBG1(DBG_CFG, "mediation client database URI not defined, skipped");
             return FALSE;
         }
         this->db = lib->db->create(lib->db, uri);
         if (this->db == NULL)
         {
             DBG1(DBG_CFG, "opening mediation client database failed");
             return FALSE;
         }
         this->creds = medcli_creds_create(this->db);
         this->config = medcli_config_create(this->db);
         this->listener = medcli_listener_create(this->db);
         lib->credmgr->add_set(lib->credmgr, &this->creds->set);
         charon->backends->add_backend(charon->backends, &this->config->backend);
         charon->bus->add_listener(charon->bus, &this->listener->listener);
     }
     else
     {
         charon->bus->remove_listener(charon->bus, &this->listener->listener);
         charon->backends->remove_backend(charon->backends, &this->config->backend);
         lib->credmgr->remove_set(lib->credmgr, &this->creds->set);
         this->listener->destroy(this->listener);
         this->config->destroy(this->config);
         this->creds->destroy(this->creds);
         this->db->destroy(this->db);
     }
     return TRUE;
 }