strongSwan: control_controller.c File Reference
control_controller.c File Reference
#include "control_controller.h"
#include "../manager.h"
#include "../gateway.h"
#include <xml.h>
#include <library.h>
Classes
struct private_control_controller_t
Typedefs
typedef struct
private_control_controller_t private_control_controller_t
Functions
static void handle_result (private_control_controller_t *this, fast_request_t *r, enumerator_t *e)
static void initiate (private_control_controller_t *this, fast_request_t *r, bool ike, char *config)
static void terminate (private_control_controller_t *this, fast_request_t *r, bool ike, u_int32_t id)
METHOD (fast_controller_t, get_name, char *, private_control_controller_t *this)
METHOD (fast_controller_t, handle, void, private_control_controller_t *this, fast_request_t *request, char *action, char *str, char *p3, char *p4, char *p5)
METHOD (fast_controller_t, destroy, void, private_control_controller_t *this)
fast_controller_t * control_controller_create (fast_context_t *context, void *param)
Typedef Documentation
typedef struct private_control_controller_t private_control_controller_t
Definition at line 25 of file control_controller.c.
Function Documentation
static void handle_result (private_control_controller_t * this, fast_request_t * r, enumerator_t * e) static
handle the result of a control operation
Definition at line 46 of file control_controller.c.
References xml_t::children, enumerator_t::destroy, enumerator_t::enumerate, name, fast_request_t::render, fast_request_t::set, fast_request_t::setf, streq(), and value.
Referenced by initiate(), and terminate().
 {
     enumerator_t *e1;
     xml_t *xml;
     char *name, *value;
     int num = 0;
     if (e)
     {
         while (e->enumerate(e, &xml, &name, &value))
         {
             if (streq(name, "status"))
             {
                 if (value && atoi(value) == 0)
                 {
                     r->set(r, "result", "Operation executed successfully:");
                 }
                 else
                 {
                     r->set(r, "result", "Operation failed:");
                 }
             }
             else if (streq(name, "log"))
             {
                 e1 = xml->children(xml);
                 while (e1->enumerate(e1, &xml, &name, &value))
                 {
                     if (streq(name, "item"))
                     {
                         r->setf(r, "log.%d=%s", ++num, value);
                     }
                 }
                 e1->destroy(e1);
             }
         }
         e->destroy(e);
         r->render(r, "templates/control/result.cs");
     }
     else
     {
         r->set(r, "title", "Error");
         r->set(r, "error", "controlling the gateway failed");
         r->render(r, "templates/error.cs");
     }
 }
static void initiate (private_control_controller_t * this, fast_request_t * r, bool ike, char * config) static
initiate an IKE or CHILD SA
Definition at line 96 of file control_controller.c.
References handle_result(), gateway_t::initiate, and fast_request_t::setf.
Referenced by METHOD().
 {
     gateway_t *gateway;
     enumerator_t *e;
     r->setf(r, "title=Establishing %s SA %s", ike ? "IKE" : "CHILD", config);
     gateway = this->manager->select_gateway(this->manager, 0);
     e = gateway->initiate(gateway, ike, config);
     handle_result(this, r, e);
 }
METHOD (fast_controller_t , get_name , char * , private_control_controller_t * this)
Definition at line 123 of file control_controller.c.
 {
     return "control";
 }
METHOD (fast_controller_t , handle , void , private_control_controller_t * this, fast_request_t * request, char * action, char * str, char * p3, char * p4, char * p5)
Definition at line 129 of file control_controller.c.
References FALSE, id, initiate(), fast_request_t::redirect, streq(), terminate(), and TRUE.
 {
     if (!this->manager->logged_in(this->manager))
     {
         return request->redirect(request, "auth/login");
     }
     if (this->manager->select_gateway(this->manager, 0) == NULL)
     {
         return request->redirect(request, "gateway/list");
     }
     if (action)
     {
         u_int32_t id;
         if (streq(action, "terminateike"))
         {
             if (str && (id = atoi(str)))
             {
                 return terminate(this, request, TRUE, id);
             }
         }
         if (streq(action, "terminatechild"))
         {
             if (str && (id = atoi(str)))
             {
                 return terminate(this, request, FALSE, id);
             }
         }
         if (streq(action, "initiateike"))
         {
             if (str)
             {
                 return initiate(this, request, TRUE, str);
             }
         }
         if (streq(action, "initiatechild"))
         {
             if (str)
             {
                 return initiate(this, request, FALSE, str);
             }
         }
     }
     return request->redirect(request, "ikesa/list");
 }
METHOD (fast_controller_t , destroy , void , private_control_controller_t * this)
Definition at line 177 of file control_controller.c.
References free().
 {
     free(this);
 }
static void terminate (private_control_controller_t * this, fast_request_t * r, bool ike, u_int32_t id) static
terminate an IKE or CHILD SA
Definition at line 111 of file control_controller.c.
References handle_result(), fast_request_t::setf, and gateway_t::terminate.
Referenced by METHOD().
 {
     gateway_t *gateway;
     enumerator_t *e;
     r->setf(r, "title=Terminate %s SA %d", ike ? "IKE" : "CHILD", id);
     gateway = this->manager->select_gateway(this->manager, 0);
     e = gateway->terminate(gateway, ike, id);
     handle_result(this, r, e);
 }