strongSwan: encrypted_payload_t Struct Reference
encrypted_payload_t Struct Reference
encrypted_payload
#include "encrypted_payload.h"
Public Attributes
payload_t payload_interface
size_t(* get_length)(encrypted_payload_t *this)
void(* add_payload)(encrypted_payload_t *this, payload_t *payload)
payload_t *(* remove_payload)(encrypted_payload_t *this)
void(* generate_payloads)(encrypted_payload_t *this, generator_t *generator)
void(* set_transform)(encrypted_payload_t *this, aead_t *aead)
status_t(* encrypt)(encrypted_payload_t *this, u_int64_t mid, chunk_t assoc)
status_t(* decrypt)(encrypted_payload_t *this, chunk_t assoc)
void(* destroy)(encrypted_payload_t *this)
Detailed Description
The encrypted payload as described in RFC section 3.14.
Definition at line 37 of file encrypted_payload.h.
Member Data Documentation
void(* encrypted_payload_t::add_payload)(encrypted_payload_t *this, payload_t *payload)
Adds a payload to this encryption payload.
Parameters
payload payload_t object to add
Definition at line 56 of file encrypted_payload.h.
Referenced by wrap_payloads().
status_t(* encrypted_payload_t::decrypt)(encrypted_payload_t *this, chunk_t assoc)
Decrypt, verify and parse contained payloads.
Parameters
assoc associated data
Returns
SUCCESS if parsing successful
PARSE_ERROR if sub-payload parsing failed
VERIFY_ERROR if sub-payload verification failed
FAILED if integrity check failed
INVALID_STATE if aead not supplied, but needed
Definition at line 105 of file encrypted_payload.h.
Referenced by decrypt_and_extract(), decrypt_fragment(), and encrypted_payload_create_from_plain().
void(* encrypted_payload_t::destroy)(encrypted_payload_t *this)
Destroys an encrypted_payload_t object.
Definition at line 110 of file encrypted_payload.h.
Referenced by decrypt_payloads(), finalize_message(), and METHOD().
status_t(* encrypted_payload_t::encrypt)(encrypted_payload_t *this, u_int64_t mid, chunk_t assoc)
Generate, encrypt and sign contained payloads.
Parameters
mid message ID
assoc associated data
Returns
SUCCESS if encryption successful
FAILED if encryption failed
INVALID_STATE if aead not supplied, but needed
Definition at line 91 of file encrypted_payload.h.
Referenced by finalize_message().
void(* encrypted_payload_t::generate_payloads)(encrypted_payload_t *this, generator_t *generator)
Uses the given generator to generate the contained payloads.
Parameters
generator generator used to generate the contained payloads
Definition at line 71 of file encrypted_payload.h.
Referenced by METHOD().
size_t(* encrypted_payload_t::get_length)(encrypted_payload_t *this)
Get the payload length.
Returns
(expected) payload length
Definition at line 49 of file encrypted_payload.h.
Referenced by decrypt_and_extract(), decrypt_fragment(), finalize_message(), and METHOD().
payload_t encrypted_payload_t::payload_interface
Implements payload_t interface.
Definition at line 42 of file encrypted_payload.h.
Referenced by finalize_message(), METHOD(), and parse_payloads().
payload_t*(* encrypted_payload_t::remove_payload)(encrypted_payload_t *this)
Remove the first payload in the list
Parameters
payload removed payload
Returns
payload, NULL if none left
Definition at line 64 of file encrypted_payload.h.
Referenced by decrypt_and_extract().
void(* encrypted_payload_t::set_transform)(encrypted_payload_t *this, aead_t *aead)
Set the AEAD transform to use.
Parameters
aead aead transform to use
Definition at line 79 of file encrypted_payload.h.
Referenced by decrypt_and_extract(), and decrypt_fragment().
The documentation for this struct was generated from the following file:
encrypted_payload.h