strongSwan: ietf_attr_installed_packages_t Struct Reference
ietf_attr_installed_packages_t Struct Reference
ietf_attr_installed_packages
#include "ietf_attr_installed_packages.h"
Public Attributes
pa_tnc_attr_t pa_tnc_attribute
void(* add)(ietf_attr_installed_packages_t *this, chunk_t name, chunk_t version)
enumerator_t *(* create_enumerator)(ietf_attr_installed_packages_t *this)
uint16_t(* get_count)(ietf_attr_installed_packages_t *this)
void(* clear_packages)(ietf_attr_installed_packages_t *this)
Detailed Description
Class implementing the IETF PA-TNC Installed Packages attribute.
Definition at line 35 of file ietf_attr_installed_packages.h.
Member Data Documentation
void(* ietf_attr_installed_packages_t::add)(ietf_attr_installed_packages_t *this, chunk_t name, chunk_t version)
Add a package entry
Parameters
name package name
version package version number
Definition at line 48 of file ietf_attr_installed_packages.h.
Referenced by add_installed_packages().
void(* ietf_attr_installed_packages_t::clear_packages)(ietf_attr_installed_packages_t *this)
Remove all Installed Packages from list
Definition at line 69 of file ietf_attr_installed_packages.h.
Referenced by receive_msg().
enumerator_t*(* ietf_attr_installed_packages_t::create_enumerator)(ietf_attr_installed_packages_t *this)
Enumerates over all packages Format: chunk_t name, chunk_t version
Returns
enumerator
Definition at line 57 of file ietf_attr_installed_packages.h.
Referenced by receive_msg().
uint16_t(* ietf_attr_installed_packages_t::get_count)(ietf_attr_installed_packages_t *this)
Number of Installed Packages still missing
Returns
Number of missing installed packages
Definition at line 64 of file ietf_attr_installed_packages.h.
Referenced by receive_msg().
pa_tnc_attr_t ietf_attr_installed_packages_t::pa_tnc_attribute
Public PA-TNC attribute interface
Definition at line 40 of file ietf_attr_installed_packages.h.
The documentation for this struct was generated from the following file:
ietf_attr_installed_packages.h