strongSwan: load_tester_ipsec
load_tester_ipsec
load_tester
Classes
struct load_tester_ipsec_t
Typedefs
typedef struct load_tester_ipsec_t load_tester_ipsec_t
Functions
load_tester_ipsec_t * load_tester_ipsec_create ()
Detailed Description
Typedef Documentation
typedef struct load_tester_ipsec_t load_tester_ipsec_t
Definition at line 26 of file load_tester_ipsec.h.
Function Documentation
load_tester_ipsec_t* load_tester_ipsec_create ()
Create a faked kernel ipsec interface instance.
Returns
kernel_load_tester_ipsec_t instance
Definition at line 123 of file load_tester_ipsec.c.
References INIT, return_failed(), and return_true().
Referenced by load_tester_plugin_create(), and METHOD().
 {
     private_load_tester_ipsec_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .get_spi = _get_spi,
                 .get_cpi = _get_cpi,
                 .add_sa = _add_sa,
                 .update_sa = _update_sa,
                 .query_sa = _query_sa,
                 .del_sa = _del_sa,
                 .flush_sas = (void*)return_failed,
                 .add_policy = _add_policy,
                 .query_policy = _query_policy,
                 .del_policy = _del_policy,
                 .flush_policies = (void*)return_failed,
                 .bypass_socket = (void*)return_true,
                 .enable_udp_decap = (void*)return_true,
                 .destroy = _destroy,
             },
         },
         .spi = 0,
     );
     return &this->public;
 }