strongSwan: blocking_queue.c File Reference
blocking_queue.c File Reference
#include "blocking_queue.h"
#include <threading/mutex.h>
#include <threading/thread.h>
#include <threading/condvar.h>
#include <collections/linked_list.h>
Classes
struct private_blocking_queue_t
Typedefs
typedef struct
private_blocking_queue_t private_blocking_queue_t
Functions
METHOD (blocking_queue_t, enqueue, void, private_blocking_queue_t *this, void *item)
METHOD (blocking_queue_t, dequeue, void *, private_blocking_queue_t *this)
METHOD (blocking_queue_t, destroy, void, private_blocking_queue_t *this)
METHOD (blocking_queue_t, destroy_offset, void, private_blocking_queue_t *this, size_t offset)
METHOD (blocking_queue_t, destroy_function, void, private_blocking_queue_t *this, void(*fn)(void *))
blocking_queue_t * blocking_queue_create ()
Typedef Documentation
typedef struct private_blocking_queue_t private_blocking_queue_t
Definition at line 25 of file blocking_queue.c.
Function Documentation
METHOD (blocking_queue_t , enqueue , void , private_blocking_queue_t * this, void * item)
Definition at line 54 of file blocking_queue.c.
References condvar, linked_list_t::insert_first, list, mutex_t::lock, mutex, condvar_t::signal, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     this->list->insert_first(this->list, item);
     this->condvar->signal(this->condvar);
     this->mutex->unlock(this->mutex);
 }
METHOD (blocking_queue_t , dequeue , void * , private_blocking_queue_t * this)
Definition at line 63 of file blocking_queue.c.
References condvar, list, mutex_t::lock, mutex, linked_list_t::remove_last, SUCCESS, thread_cancelability(), thread_cancellation_point(), thread_cleanup_pop(), thread_cleanup_push(), TRUE, mutex_t::unlock, and condvar_t::wait.
 {
     bool oldstate;
     void *item;
     this->mutex->lock(this->mutex);
     thread_cleanup_push((thread_cleanup_t)this->mutex->unlock, this->mutex);
     /* ensure that a canceled thread does not dequeue any items */
     thread_cancellation_point();
     while (this->list->remove_last(this->list, &item) != SUCCESS)
     {
         oldstate = thread_cancelability(TRUE);
         this->condvar->wait(this->condvar, this->mutex);
         thread_cancelability(oldstate);
     }
     thread_cleanup_pop(TRUE);
     return item;
 }
METHOD (blocking_queue_t , destroy , void , private_blocking_queue_t * this)
Definition at line 84 of file blocking_queue.c.
References condvar, mutex_t::destroy, condvar_t::destroy, linked_list_t::destroy, free(), list, and mutex.
 {
     this->list->destroy(this->list);
     this->condvar->destroy(this->condvar);
     this->mutex->destroy(this->mutex);
     free(this);
 }
METHOD (blocking_queue_t , destroy_offset , void , private_blocking_queue_t * this, size_t offset)
Definition at line 93 of file blocking_queue.c.
References destroy(), linked_list_t::invoke_offset, and list.
 {
     this->list->invoke_offset(this->list, offset);
     destroy(this);
 }
METHOD (blocking_queue_t , destroy_function , void , private_blocking_queue_t * this, void(*)(void *) fn)
Definition at line 100 of file blocking_queue.c.
References destroy(), fn, linked_list_t::invoke_function, and list.
 {
     this->list->invoke_function(this->list, (linked_list_invoke_t)fn);
     destroy(this);
 }