strongSwan: tncifimc
tncifimc
libtncif
Macros
#define TNC_IMC_API
#define TNC_IFIMC_VERSION_1 1
#define TNC_RETRY_REASON_IMC_REMEDIATION_COMPLETE 0
#define TNC_RETRY_REASON_IMC_SERIOUS_EVENT 1
#define TNC_RETRY_REASON_IMC_INFORMATIONAL_EVENT 2
#define TNC_RETRY_REASON_IMC_PERIODIC 3
#define TNC_ATTRIBUTEID_SOHR ((TNC_AttributeID) 0x00559708)
#define TNC_ATTRIBUTEID_SSOHR ((TNC_AttributeID) 0x00559709)
#define TNC_ATTRIBUTEID_PRIMARY_IMC_ID ((TNC_AttributeID) 0x00559711)
Typedefs
typedef TNC_UInt32 TNC_IMCID
typedef TNC_Result(* TNC_IMC_InitializePointer)(TNC_IMCID imcID, TNC_Version minVersion, TNC_Version maxVersion, TNC_Version *pOutActualVersion)
typedef TNC_Result(* TNC_IMC_NotifyConnectionChangePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_ConnectionState newState)
typedef TNC_Result(* TNC_IMC_BeginHandshakePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
typedef TNC_Result(* TNC_IMC_ReceiveMessagePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
typedef TNC_Result(* TNC_IMC_ReceiveMessageSOHPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohrReportEntry, TNC_UInt32 sohrRELength, TNC_MessageType systemHealthID)
typedef TNC_Result(* TNC_IMC_ReceiveMessageLongPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 sourceIMVID, TNC_UInt32 destinationIMCID)
typedef TNC_Result(* TNC_IMC_BatchEndingPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
typedef TNC_Result(* TNC_IMC_TerminatePointer)(TNC_IMCID imcID)
typedef TNC_Result(* TNC_TNCC_ReportMessageTypesPointer)(TNC_IMCID imcID, TNC_MessageTypeList supportedTypes, TNC_UInt32 typeCount)
typedef TNC_Result(* TNC_TNCC_ReportMessageTypesLongPointer)(TNC_IMCID imcID, TNC_VendorIDList supportedVendorIDs, TNC_MessageSubtypeList supportedSubtypes, TNC_UInt32 typeCount)
typedef TNC_Result(* TNC_TNCC_SendMessagePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
typedef TNC_Result(* TNC_TNCC_SendMessageSOHPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohReportEntry, TNC_UInt32 sohRELength)
typedef TNC_Result(* TNC_TNCC_SendMessageLongPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 destinationIMVID)
typedef TNC_Result(* TNC_TNCC_RequestHandshakeRetryPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_RetryReason reason)
typedef TNC_Result(* TNC_TNCC_GetAttributePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_AttributeID attributeID, TNC_UInt32 bufferLength, TNC_BufferReference buffer, TNC_UInt32 *pOutValueLength)
typedef TNC_Result(* TNC_TNCC_SetAttributePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_AttributeID attributeID, TNC_UInt32 bufferLength, TNC_BufferReference buffer)
typedef TNC_Result(* TNC_TNCC_ReserveAdditionalIMCIDPointer)(TNC_IMCID imcID, TNC_UInt32 *pOutIMCID)
typedef TNC_Result(* TNC_TNCC_BindFunctionPointer)(TNC_IMCID imcID, char *functionName, void **pOutfunctionPointer)
typedef TNC_Result(* TNC_IMC_ProvideBindFunctionPointer)(TNC_IMCID imcID, TNC_TNCC_BindFunctionPointer bindFunction)
Functions
TNC_IMC_API TNC_Result TNC_IMC_Initialize (TNC_IMCID imcID, TNC_Version minVersion, TNC_Version maxVersion, TNC_Version *pOutActualVersion)
TNC_IMC_API TNC_Result TNC_IMC_NotifyConnectionChange (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_ConnectionState newState)
TNC_IMC_API TNC_Result TNC_IMC_BeginHandshake (TNC_IMCID imcID, TNC_ConnectionID connectionID)
TNC_IMC_API TNC_Result TNC_IMC_ReceiveMessage (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference messageBuffer, TNC_UInt32 messageLength, TNC_MessageType messageType)
TNC_IMC_API TNC_Result TNC_IMC_ReceiveMessageSOH (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohrReportEntry, TNC_UInt32 sohrRELength, TNC_MessageType systemHealthID)
TNC_IMC_API TNC_Result TNC_IMC_ReceiveMessageLong (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 sourceIMVID, TNC_UInt32 destinationIMCID)
TNC_IMC_API TNC_Result TNC_IMC_BatchEnding (TNC_IMCID imcID, TNC_ConnectionID connectionID)
TNC_IMC_API TNC_Result TNC_IMC_Terminate (TNC_IMCID imcID)
TNC_IMC_API TNC_Result TNC_IMC_ProvideBindFunction (TNC_IMCID imcID, TNC_TNCC_BindFunctionPointer bindFunction)
TNC_Result TNC_TNCC_ReportMessageTypes (TNC_IMCID imcID, TNC_MessageTypeList supportedTypes, TNC_UInt32 typeCount)
TNC_Result TNC_TNCC_ReportMessageTypesLong (TNC_IMCID imcID, TNC_VendorIDList supportedVendorIDs, TNC_MessageSubtypeList supportedSubtypes, TNC_UInt32 typeCount)
TNC_Result TNC_TNCC_SendMessage (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
TNC_Result TNC_TNCC_SendMessageSOH (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohReportEntry, TNC_UInt32 sohRELength)
TNC_Result TNC_TNCC_SendMessageLong (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 destinationIMVID)
TNC_Result TNC_TNCC_RequestHandshakeRetry (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_RetryReason reason)
TNC_Result TNC_TNCC_GetAttribute (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_AttributeID attributeID, TNC_UInt32 bufferLength, TNC_BufferReference buffer, TNC_UInt32 *pOutValueLength)
TNC_Result TNC_TNCC_SetAttribute (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_AttributeID attributeID, TNC_UInt32 bufferLength, TNC_BufferReference buffer)
TNC_Result TNC_TNCS_ReserveAdditionalIMCID (TNC_IMCID imcID, TNC_UInt32 *pOutIMCID)
TNC_Result TNC_TNCC_BindFunction (TNC_IMCID imcID, char *functionName, void **pOutfunctionPointer)
Detailed Description
Macro Definition Documentation
#define TNC_ATTRIBUTEID_PRIMARY_IMC_ID ((TNC_AttributeID) 0x00559711)
Definition at line 188 of file tncifimc.h.
Referenced by METHOD().
#define TNC_ATTRIBUTEID_SOHR ((TNC_AttributeID) 0x00559708)
Definition at line 186 of file tncifimc.h.
Referenced by METHOD().
#define TNC_ATTRIBUTEID_SSOHR ((TNC_AttributeID) 0x00559709)
Definition at line 187 of file tncifimc.h.
Referenced by METHOD().
#define TNC_IFIMC_VERSION_1 1
Definition at line 170 of file tncifimc.h.
Referenced by imc_agent_create(), METHOD(), and TNC_IMC_Initialize().
#define TNC_IMC_API
Definition at line 63 of file tncifimc.h.
#define TNC_RETRY_REASON_IMC_INFORMATIONAL_EVENT 2
Definition at line 176 of file tncifimc.h.
#define TNC_RETRY_REASON_IMC_PERIODIC 3
Definition at line 177 of file tncifimc.h.
#define TNC_RETRY_REASON_IMC_REMEDIATION_COMPLETE 0
Definition at line 174 of file tncifimc.h.
Referenced by TNC_IMC_NotifyConnectionChange().
#define TNC_RETRY_REASON_IMC_SERIOUS_EVENT 1
Definition at line 175 of file tncifimc.h.
Typedef Documentation
typedef TNC_Result(* TNC_IMC_BatchEndingPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
Definition at line 106 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_BeginHandshakePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID)
Definition at line 81 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_InitializePointer)(TNC_IMCID imcID, TNC_Version minVersion, TNC_Version maxVersion, TNC_Version *pOutActualVersion)
Definition at line 72 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_NotifyConnectionChangePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_ConnectionState newState)
Definition at line 77 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_ProvideBindFunctionPointer)(TNC_IMCID imcID, TNC_TNCC_BindFunctionPointer bindFunction)
Definition at line 164 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_ReceiveMessageLongPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 sourceIMVID, TNC_UInt32 destinationIMCID)
Definition at line 96 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_ReceiveMessagePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
Definition at line 84 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_ReceiveMessageSOHPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohrReportEntry, TNC_UInt32 sohrRELength, TNC_MessageType systemHealthID)
Definition at line 90 of file tncifimc.h.
typedef TNC_Result(* TNC_IMC_TerminatePointer)(TNC_IMCID imcID)
Definition at line 109 of file tncifimc.h.
typedef TNC_UInt32 TNC_IMCID
Definition at line 68 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_BindFunctionPointer)(TNC_IMCID imcID, char *functionName, void **pOutfunctionPointer)
Definition at line 160 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_GetAttributePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_AttributeID attributeID, TNC_UInt32 bufferLength, TNC_BufferReference buffer, TNC_UInt32 *pOutValueLength)
Definition at line 144 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_ReportMessageTypesLongPointer)(TNC_IMCID imcID, TNC_VendorIDList supportedVendorIDs, TNC_MessageSubtypeList supportedSubtypes, TNC_UInt32 typeCount)
Definition at line 115 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_ReportMessageTypesPointer)(TNC_IMCID imcID, TNC_MessageTypeList supportedTypes, TNC_UInt32 typeCount)
Definition at line 111 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_RequestHandshakeRetryPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_RetryReason reason)
Definition at line 140 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_ReserveAdditionalIMCIDPointer)(TNC_IMCID imcID, TNC_UInt32 *pOutIMCID)
Definition at line 157 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_SendMessageLongPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_UInt32 messageFlags, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_VendorID messageVendorID, TNC_MessageSubtype messageSubtype, TNC_UInt32 destinationIMVID)
Definition at line 131 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_SendMessagePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference message, TNC_UInt32 messageLength, TNC_MessageType messageType)
Definition at line 120 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_SendMessageSOHPointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohReportEntry, TNC_UInt32 sohRELength)
Definition at line 126 of file tncifimc.h.
typedef TNC_Result(* TNC_TNCC_SetAttributePointer)(TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_AttributeID attributeID, TNC_UInt32 bufferLength, TNC_BufferReference buffer)
Definition at line 151 of file tncifimc.h.
Function Documentation
TNC_IMC_API TNC_Result TNC_IMC_BatchEnding (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
see section 3.8.7 of TCG TNC IF-IMC Specification 1.3
Definition at line 296 of file imc_attestation.c.
References DBG1, DBG_IMC, imc_name, TNC_RESULT_NOT_INITIALIZED, and TNC_RESULT_SUCCESS.
 {
     if (!imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has not been initialized", imc_name);
         return TNC_RESULT_NOT_INITIALIZED;
     }
     return TNC_RESULT_SUCCESS;
 }
TNC_IMC_API TNC_Result TNC_IMC_BeginHandshake (TNC_IMCID imc_id, TNC_ConnectionID connection_id)
see section 3.8.3 of TCG TNC IF-IMC Specification 1.3
Definition at line 141 of file imc_attestation.c.
References imc_msg_t::add_attribute, add_attrs_natural_lang(), seg_contract_manager_t::add_contract, add_default_pwd_enabled(), add_device_id(), add_forwarding_enabled(), add_fwd_enabled(), add_machine_type_model(), add_numeric_version(), add_op_status(), add_port_filter(), add_product_info(), add_pstn_fax_enabled(), add_quadruple(), add_string_version(), add_time_source(), add_user_app_enabled(), add_user_app_persist_enabled(), add_vendor_name(), add_vendor_smi_code(), BUF_LEN, imc_agent_t::count_additional_ids, countof, imc_agent_t::create_id_enumerator, create_message(), settings_t::create_section_enumerator, DBG1, DBG2, DBG_IMC, enumerator_t::destroy, imc_msg_t::destroy, enumerator_t::enumerate, FALSE, settings_t::get_bool, imc_state_t::get_contracts, seg_contract_t::get_info_string, imc_state_t::get_max_msg_len, imc_agent_t::get_state, imc_state_t::has_long, imc_msg_create(), imc_name, lib, max_seg_size, library_t::ns, PA_SUBTYPE_PWG_HCD_SYSTEM, PA_SUBTYPE_PWG_HCD_UNKNOWN, pa_subtype_pwg_names, PA_TNC_ATTR_HEADER_SIZE, PA_TNC_HEADER_SIZE, pen_names, PEN_PWG, pen_type_create(), result, section, seg_contract_create(), imc_msg_t::send, library_t::settings, streq(), section_subtype_t::subtype, subtype, SWID_MAX_ATTR_SIZE, tcg_seg_attr_max_size_create(), TCG_SEG_ATTR_SEG_ENV_HEADER, TNC_IMVID_ANY, TNC_RESULT_FATAL, TNC_RESULT_NOT_INITIALIZED, TNC_RESULT_SUCCESS, and TRUE.
 {
     if (!imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has not been initialized", imc_name);
         return TNC_RESULT_NOT_INITIALIZED;
     }
     return TNC_RESULT_SUCCESS;
 }
TNC_IMC_API TNC_Result TNC_IMC_Initialize (TNC_IMCID imc_id, TNC_Version min_version, TNC_Version max_version, TNC_Version * actual_version)
see section 3.8.1 of TCG TNC IF-IMC Specification 1.3
Definition at line 61 of file imc_attestation.c.
References countof, DBG1, DBG_IMC, imc_agent_t::destroy, settings_t::get_bool, imc_agent_create(), imc_name, imc_os_info_create(), lib, library_t::ns, pts_dh_group_probe(), pts_meas_algo_probe(), library_t::settings, supported_algorithms, supported_dh_groups, TNC_IFIMC_VERSION_1, TNC_RESULT_ALREADY_INITIALIZED, TNC_RESULT_FATAL, TNC_RESULT_NO_COMMON_VERSION, TNC_RESULT_SUCCESS, and TRUE.
 {
     bool mandatory_dh_groups;
     if (imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has already been initialized", imc_name);
         return TNC_RESULT_ALREADY_INITIALIZED;
     }
     imc_attestation = imc_agent_create(imc_name, msg_types, countof(msg_types),
                                        imc_id, actual_version);
     if (!imc_attestation)
     {
         return TNC_RESULT_FATAL;
     }
     mandatory_dh_groups = lib->settings->get_bool(lib->settings,
             "%s.plugins.imc-attestation.mandatory_dh_groups", TRUE, lib->ns);
     if (!pts_meas_algo_probe(&supported_algorithms) ||
         !pts_dh_group_probe(&supported_dh_groups, mandatory_dh_groups))
     {
         imc_attestation->destroy(imc_attestation);
         imc_attestation = NULL;
         return TNC_RESULT_FATAL;
     }
     if (min_version > TNC_IFIMC_VERSION_1 || max_version < TNC_IFIMC_VERSION_1)
     {
         DBG1(DBG_IMC, "no common IF-IMC version");
         return TNC_RESULT_NO_COMMON_VERSION;
     }
     return TNC_RESULT_SUCCESS;
 }
TNC_IMC_API TNC_Result TNC_IMC_NotifyConnectionChange (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_ConnectionState new_state)
see section 3.8.2 of TCG TNC IF-IMC Specification 1.3
Definition at line 102 of file imc_attestation.c.
References imc_agent_t::change_state, command, imc_agent_t::count_additional_ids, imc_agent_t::create_id_enumerator, imc_agent_t::create_state, DBG1, DBG_IMC, imc_agent_t::delete_state, enumerator_t::destroy, imc_test_state_t::do_handshake_retry, enumerator_t::enumerate, FALSE, settings_t::get_bool, imc_test_state_t::get_command, settings_t::get_int, settings_t::get_str, imc_attestation_state_create(), imc_hcd_state_create(), imc_name, imc_os_state_create(), imc_scanner_state_create(), imc_swid_state_create(), imc_test_state_create(), imc_test_state_t::is_first_handshake, lib, library_t::ns, imc_agent_t::request_handshake_retry, imc_agent_t::reserve_additional_ids, result, imc_test_state_t::set_command, imc_state_t::set_result, library_t::settings, TNC_CONNECTION_STATE_ACCESS_ISOLATED, TNC_CONNECTION_STATE_ACCESS_NONE, TNC_CONNECTION_STATE_CREATE, TNC_CONNECTION_STATE_DELETE, TNC_CONNECTION_STATE_HANDSHAKE, TNC_IMV_EVALUATION_RESULT_DONT_KNOW, TNC_RESULT_FATAL, TNC_RESULT_NOT_INITIALIZED, TNC_RESULT_SUCCESS, and TNC_RETRY_REASON_IMC_REMEDIATION_COMPLETE.
 {
     imc_state_t *state;
     if (!imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has not been initialized", imc_name);
         return TNC_RESULT_NOT_INITIALIZED;
     }
     switch (new_state)
     {
         case TNC_CONNECTION_STATE_CREATE:
             state = imc_attestation_state_create(connection_id);
             return imc_attestation->create_state(imc_attestation, state);
         case TNC_CONNECTION_STATE_HANDSHAKE:
             if (imc_attestation->change_state(imc_attestation, connection_id,
                 new_state, &state) != TNC_RESULT_SUCCESS)
             {
                 return TNC_RESULT_FATAL;
             }
             state->set_result(state, imc_id,
                               TNC_IMV_EVALUATION_RESULT_DONT_KNOW);
             return TNC_RESULT_SUCCESS;
         case TNC_CONNECTION_STATE_DELETE:
             return imc_attestation->delete_state(imc_attestation, connection_id);
         case TNC_CONNECTION_STATE_ACCESS_ISOLATED:
         case TNC_CONNECTION_STATE_ACCESS_NONE:
         default:
             return imc_attestation->change_state(imc_attestation, connection_id,
                                                   new_state, NULL);
     }
 }
TNC_IMC_API TNC_Result TNC_IMC_ProvideBindFunction (TNC_IMCID imc_id, TNC_TNCC_BindFunctionPointer bind_function)
see section 4.2.8.1 of TCG TNC IF-IMC Specification 1.3
Definition at line 326 of file imc_attestation.c.
References imc_agent_t::bind_functions, DBG1, DBG_IMC, imc_name, and TNC_RESULT_NOT_INITIALIZED.
 {
     if (!imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has not been initialized", imc_name);
         return TNC_RESULT_NOT_INITIALIZED;
     }
     return imc_attestation->bind_functions(imc_attestation, bind_function);
 }
TNC_IMC_API TNC_Result TNC_IMC_ReceiveMessage (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
see section 3.8.4 of TCG TNC IF-IMC Specification 1.3
Definition at line 230 of file imc_attestation.c.
References chunk_create(), DBG1, DBG_IMC, imc_msg_t::destroy, imc_agent_t::get_state, imc_msg_create_from_data(), imc_name, receive_message(), result, TNC_RESULT_FATAL, and TNC_RESULT_NOT_INITIALIZED.
 {
     imc_state_t *state;
     imc_msg_t *in_msg;
     TNC_Result result;
     if (!imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has not been initialized", imc_name);
         return TNC_RESULT_NOT_INITIALIZED;
     }
     if (!imc_attestation->get_state(imc_attestation, connection_id, &state))
     {
         return TNC_RESULT_FATAL;
     }
     in_msg = imc_msg_create_from_data(imc_attestation, state, connection_id,
                                       msg_type, chunk_create(msg, msg_len));
     result = receive_message(state, in_msg);
     in_msg->destroy(in_msg);
     return result;
 }
TNC_IMC_API TNC_Result TNC_IMC_ReceiveMessageLong (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 src_imv_id, TNC_UInt32 dst_imc_id)
see section 3.8.6 of TCG TNC IF-IMV Specification 1.3
Definition at line 261 of file imc_attestation.c.
References chunk_create(), DBG1, DBG_IMC, imc_msg_t::destroy, imc_agent_t::get_state, imc_msg_create_from_long_data(), imc_name, receive_message(), result, TNC_RESULT_FATAL, and TNC_RESULT_NOT_INITIALIZED.
 {
     imc_state_t *state;
     imc_msg_t *in_msg;
     TNC_Result result;
     if (!imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has not been initialized", imc_name);
         return TNC_RESULT_NOT_INITIALIZED;
     }
     if (!imc_attestation->get_state(imc_attestation, connection_id, &state))
     {
         return TNC_RESULT_FATAL;
     }
     in_msg = imc_msg_create_from_long_data(imc_attestation, state, connection_id,
                                 src_imv_id, dst_imc_id, msg_vid, msg_subtype,
                                 chunk_create(msg, msg_len));
     result =receive_message(state, in_msg);
     in_msg->destroy(in_msg);
     return result;
 }
TNC_IMC_API TNC_Result TNC_IMC_ReceiveMessageSOH (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohrReportEntry, TNC_UInt32 sohrRELength, TNC_MessageType systemHealthID)
TNC_IMC_API TNC_Result TNC_IMC_Terminate (TNC_IMCID imc_id)
see section 3.8.8 of TCG TNC IF-IMC Specification 1.3
Definition at line 310 of file imc_attestation.c.
References DBG1, DBG_IMC, imc_os_info_t::destroy, imc_agent_t::destroy, imc_name, TNC_RESULT_NOT_INITIALIZED, and TNC_RESULT_SUCCESS.
 {
     if (!imc_attestation)
     {
         DBG1(DBG_IMC, "IMC \"%s\" has not been initialized", imc_name);
         return TNC_RESULT_NOT_INITIALIZED;
     }
     imc_attestation->destroy(imc_attestation);
     imc_attestation = NULL;
     return TNC_RESULT_SUCCESS;
 }
TNC_Result TNC_TNCC_BindFunction (TNC_IMCID id, char * function_name, void ** function_pointer)
Called by the IMC when it needs a function pointer
Definition at line 181 of file tnc_imc_bind_function.c.
References streq(), TNC_RESULT_INVALID_PARAMETER, TNC_RESULT_SUCCESS, TNC_TNCC_GetAttribute(), TNC_TNCC_ReportMessageTypes(), TNC_TNCC_ReportMessageTypesLong(), TNC_TNCC_RequestHandshakeRetry(), TNC_TNCC_ReserveAdditionalIMCID(), TNC_TNCC_SendMessage(), TNC_TNCC_SendMessageLong(), and TNC_TNCC_SetAttribute().
Referenced by METHOD().
 {
     if (streq(function_name, "TNC_TNCC_ReportMessageTypes"))
     {
         *function_pointer = (void*)TNC_TNCC_ReportMessageTypes;
     }
     else if (streq(function_name, "TNC_TNCC_ReportMessageTypesLong"))
     {
         *function_pointer = (void*)TNC_TNCC_ReportMessageTypesLong;
     }
     else if (streq(function_name, "TNC_TNCC_RequestHandshakeRetry"))
     {
         *function_pointer = (void*)TNC_TNCC_RequestHandshakeRetry;
     }
     else if (streq(function_name, "TNC_TNCC_SendMessage"))
     {
         *function_pointer = (void*)TNC_TNCC_SendMessage;
     }
     else if (streq(function_name, "TNC_TNCC_SendMessageLong"))
     {
         *function_pointer = (void*)TNC_TNCC_SendMessageLong;
     }
     else if (streq(function_name, "TNC_TNCC_GetAttribute"))
     {
         *function_pointer = (void*)TNC_TNCC_GetAttribute;
     }
     else if (streq(function_name, "TNC_TNCC_SetAttribute"))
     {
         *function_pointer = (void*)TNC_TNCC_SetAttribute;
     }
     else if (streq(function_name, "TNC_TNCC_ReserveAdditionalIMCID"))
     {
         *function_pointer = (void*)TNC_TNCC_ReserveAdditionalIMCID;
     }
     else
     {
         return TNC_RESULT_INVALID_PARAMETER;
     }
     return TNC_RESULT_SUCCESS;
 }
TNC_Result TNC_TNCC_GetAttribute (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_AttributeID attribute_id, TNC_UInt32 buffer_len, TNC_BufferReference buffer, TNC_UInt32 * out_value_len)
Called by the IMC to get the value of an attribute associated with a connection or with the TNCC as a whole.
Definition at line 127 of file tnc_imc_bind_function.c.
References DBG1, DBG_TNC, tnccs_manager_t::get_attribute, tnc_t::imcs, imc_manager_t::is_registered, tnc, TNC_RESULT_INVALID_PARAMETER, tnc_t::tnccs, and TRUE.
Referenced by TNC_TNCC_BindFunction().
 {
     if (!tnc->imcs->is_registered(tnc->imcs, imc_id))
     {
         DBG1(DBG_TNC, "ignoring GetAttribute() from unregistered IMC %u",
                        imc_id);
         return TNC_RESULT_INVALID_PARAMETER;
     }
     return tnc->tnccs->get_attribute(tnc->tnccs, TRUE, imc_id, connection_id,
                             attribute_id, buffer_len, buffer, out_value_len);
 }
TNC_Result TNC_TNCC_ReportMessageTypes (TNC_IMCID imc_id, TNC_MessageTypeList supported_types, TNC_UInt32 type_count)
Called by the IMC to inform a TNCC about the set of message types the IMC is able to receive
Definition at line 26 of file tnc_imc_bind_function.c.
References DBG1, DBG_TNC, tnc_t::imcs, imc_manager_t::is_registered, imc_manager_t::set_message_types, tnc, and TNC_RESULT_INVALID_PARAMETER.
Referenced by TNC_TNCC_BindFunction().
 {
     if (!tnc->imcs->is_registered(tnc->imcs, imc_id))
     {
         DBG1(DBG_TNC, "ignoring ReportMessageTypes() from unregistered IMC %u",
                        imc_id);
         return TNC_RESULT_INVALID_PARAMETER;
     }
     return tnc->imcs->set_message_types(tnc->imcs, imc_id, supported_types,
                                         type_count);
 }
TNC_Result TNC_TNCC_ReportMessageTypesLong (TNC_IMCID imc_id, TNC_VendorIDList supported_vids, TNC_MessageSubtypeList supported_subtypes, TNC_UInt32 type_count)
Called by the IMC to inform a TNCC about the set of message types the IMC is able to receive. This function supports long message types.
Definition at line 44 of file tnc_imc_bind_function.c.
References DBG1, DBG_TNC, tnc_t::imcs, imc_manager_t::is_registered, imc_manager_t::set_message_types_long, tnc, and TNC_RESULT_INVALID_PARAMETER.
Referenced by TNC_TNCC_BindFunction().
 {
     if (!tnc->imcs->is_registered(tnc->imcs, imc_id))
     {
         DBG1(DBG_TNC, "ignoring ReportMessageTypesLong() from unregistered IMC %u",
                        imc_id);
         return TNC_RESULT_INVALID_PARAMETER;
     }
     return tnc->imcs->set_message_types_long(tnc->imcs, imc_id, supported_vids,
                                              supported_subtypes, type_count);
 }
TNC_Result TNC_TNCC_RequestHandshakeRetry (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_RetryReason reason)
Called by the IMC to ask a TNCC to retry an Integrity Check Handshake
Definition at line 62 of file tnc_imc_bind_function.c.
References DBG1, DBG_TNC, tnc_t::imcs, imc_manager_t::is_registered, tnccs_manager_t::request_handshake_retry, tnc, TNC_RESULT_INVALID_PARAMETER, tnc_t::tnccs, and TRUE.
Referenced by TNC_TNCC_BindFunction().
 {
     if (!tnc->imcs->is_registered(tnc->imcs, imc_id))
     {
         DBG1(DBG_TNC, "ignoring RequestHandshakeRetry() from unregistered IMC %u",
                        imc_id);
         return TNC_RESULT_INVALID_PARAMETER;
     }
     return tnc->tnccs->request_handshake_retry(tnc->tnccs, TRUE, imc_id,
                                                connection_id, reason);
 }
TNC_Result TNC_TNCC_SendMessage (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_MessageType msg_type)
Called by the IMC when an IMC-IMV message is to be sent
Definition at line 79 of file tnc_imc_bind_function.c.
References DBG1, DBG_TNC, tnc_t::imcs, imc_manager_t::is_registered, tnccs_manager_t::send_message, tnc, TNC_IMVID_ANY, TNC_RESULT_INVALID_PARAMETER, TNC_SUBTYPE_ANY, TNC_VENDORID_ANY, and tnc_t::tnccs.
Referenced by TNC_TNCC_BindFunction().
 {
     TNC_VendorID msg_vid;
     TNC_MessageSubtype msg_subtype;
     if (!tnc->imcs->is_registered(tnc->imcs, imc_id))
     {
         DBG1(DBG_TNC, "ignoring SendMessage() from unregistered IMC %u",
                        imc_id);
         return TNC_RESULT_INVALID_PARAMETER;
     }
     msg_vid = (msg_type >> 8) & TNC_VENDORID_ANY;
     msg_subtype = msg_type & TNC_SUBTYPE_ANY;
     return tnc->tnccs->send_message(tnc->tnccs, imc_id, TNC_IMVID_ANY,
                         connection_id, 0, msg, msg_len, msg_vid, msg_subtype);
 }
TNC_Result TNC_TNCC_SendMessageLong (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_UInt32 msg_flags, TNC_BufferReference msg, TNC_UInt32 msg_len, TNC_VendorID msg_vid, TNC_MessageSubtype msg_subtype, TNC_UInt32 imv_id)
Called by the IMC when an IMC-IMV message is to be sent over IF-TNCCS 2.0
Definition at line 104 of file tnc_imc_bind_function.c.
References DBG1, DBG_TNC, tnc_t::imcs, imc_manager_t::is_registered, tnccs_manager_t::send_message, tnc, TNC_RESULT_INVALID_PARAMETER, and tnc_t::tnccs.
Referenced by TNC_TNCC_BindFunction().
 {
     if (!tnc->imcs->is_registered(tnc->imcs, imc_id))
     {
         DBG1(DBG_TNC, "ignoring SendMessage() from unregistered IMC %u",
                        imc_id);
         return TNC_RESULT_INVALID_PARAMETER;
     }
     return tnc->tnccs->send_message(tnc->tnccs, imc_id, imv_id, connection_id,
                                 msg_flags, msg, msg_len, msg_vid, msg_subtype);
 }
TNC_Result TNC_TNCC_SendMessageSOH (TNC_IMCID imcID, TNC_ConnectionID connectionID, TNC_BufferReference sohReportEntry, TNC_UInt32 sohRELength)
TNC_Result TNC_TNCC_SetAttribute (TNC_IMCID imc_id, TNC_ConnectionID connection_id, TNC_AttributeID attribute_id, TNC_UInt32 buffer_len, TNC_BufferReference buffer)
Called by the IMC to set the value of an attribute associated with a connection or with the TNCC as a whole.
Definition at line 148 of file tnc_imc_bind_function.c.
References DBG1, DBG_TNC, tnc_t::imcs, imc_manager_t::is_registered, tnccs_manager_t::set_attribute, tnc, TNC_RESULT_INVALID_PARAMETER, tnc_t::tnccs, and TRUE.
Referenced by TNC_TNCC_BindFunction().
 {
     if (!tnc->imcs->is_registered(tnc->imcs, imc_id))
     {
         DBG1(DBG_TNC, "ignoring SetAttribute() from unregistered IMC %u",
                        imc_id);
         return TNC_RESULT_INVALID_PARAMETER;
     }
     return tnc->tnccs->set_attribute(tnc->tnccs, TRUE, imc_id, connection_id,
                                      attribute_id, buffer_len, buffer);
 }
TNC_Result TNC_TNCS_ReserveAdditionalIMCID (TNC_IMCID imcID, TNC_UInt32 * pOutIMCID)