strongSwan: isakmp_natd.c File Reference
isakmp_natd.c File Reference
#include "isakmp_natd.h"
#include <string.h>
#include <hydra.h>
#include <daemon.h>
#include <sa/ikev1/keymat_v1.h>
#include <config/peer_cfg.h>
#include <crypto/hashers/hasher.h>
#include <encoding/payloads/hash_payload.h>
Classes
struct private_isakmp_natd_t
Typedefs
typedef struct
private_isakmp_natd_t private_isakmp_natd_t
Functions
static bool force_encap (ike_cfg_t *ike_cfg)
static payload_type_t get_nat_d_payload_type (ike_sa_t *ike_sa)
static chunk_t generate_natd_hash (private_isakmp_natd_t *this, ike_sa_id_t *ike_sa_id, host_t *host)
static chunk_t generate_natd_hash_faked (private_isakmp_natd_t *this)
static hash_payload_t * build_natd_payload (private_isakmp_natd_t *this, bool src, host_t *host)
static void add_natd_payloads (private_isakmp_natd_t *this, message_t *message)
static void process_payloads (private_isakmp_natd_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_isakmp_natd_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_isakmp_natd_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_isakmp_natd_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_isakmp_natd_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_isakmp_natd_t *this)
METHOD (task_t, migrate, void, private_isakmp_natd_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_isakmp_natd_t *this)
isakmp_natd_t * isakmp_natd_create (ike_sa_t *ike_sa, bool initiator)
Typedef Documentation
typedef struct private_isakmp_natd_t private_isakmp_natd_t
Definition at line 51 of file isakmp_natd.c.
Function Documentation
static void add_natd_payloads (private_isakmp_natd_t * this, message_t * message) static
Add NAT-D payloads to the message.
Definition at line 222 of file isakmp_natd.c.
References message_t::add_payload, build_natd_payload(), FALSE, message_t::get_destination, message_t::get_source, host, and TRUE.
Referenced by METHOD().
 {
     hash_payload_t *payload;
     host_t *host;
     /* destination has to be added first */
     host = message->get_destination(message);
     payload = build_natd_payload(this, FALSE, host);
     if (payload)
     {
         message->add_payload(message, (payload_t*)payload);
     }
     /* source is added second, compared with IKEv2 we always know the source,
      * as these payloads are added in the second Phase 1 exchange or the
      * response to the first */
     host = message->get_source(message);
     payload = build_natd_payload(this, TRUE, host);
     if (payload)
     {
         message->add_payload(message, (payload_t*)payload);
     }
 }
static hash_payload_t* build_natd_payload (private_isakmp_natd_t * this, bool src, host_t * host) static
Build a NAT-D payload.
Definition at line 192 of file isakmp_natd.c.
References chunk_free(), force_encap(), generate_natd_hash(), generate_natd_hash_faked(), get_nat_d_payload_type(), hash, hash_payload_create(), chunk_t::len, and hash_payload_t::set_hash.
Referenced by add_natd_payloads().
 {
     hash_payload_t *payload;
     ike_cfg_t *config;
     chunk_t hash;
     config = this->ike_sa->get_ike_cfg(this->ike_sa);
     if (src && force_encap(config))
     {
         hash = generate_natd_hash_faked(this);
     }
     else
     {
         ike_sa_id_t *ike_sa_id = this->ike_sa->get_id(this->ike_sa);
         hash = generate_natd_hash(this, ike_sa_id, host);
     }
     if (!hash.len)
     {
         return NULL;
     }
     payload = hash_payload_create(get_nat_d_payload_type(this->ike_sa));
     payload->set_hash(payload, hash);
     chunk_free(&hash);
     return payload;
 }
static bool force_encap (ike_cfg_t * ike_cfg) static
Check if UDP encapsulation has to be forced either by config or required by the kernel interface
Definition at line 103 of file isakmp_natd.c.
References ike_cfg_t::force_encap, kernel_interface_t::get_features, hydra, hydra_t::kernel_interface, KERNEL_REQUIRE_UDP_ENCAPSULATION, and TRUE.
Referenced by build_ike_cfg(), build_natd_payload(), ike_cfg_create(), METHOD(), and process_payloads().
 {
     if (!ike_cfg->force_encap(ike_cfg))
     {
         return hydra->kernel_interface->get_features(hydra->kernel_interface) &
                     KERNEL_REQUIRE_UDP_ENCAPSULATION;
     }
     return TRUE;
 }
static chunk_t generate_natd_hash (private_isakmp_natd_t * this, ike_sa_id_t * ike_sa_id, host_t * host) static
Build NAT detection hash for a host.
Definition at line 128 of file isakmp_natd.c.
References hasher_t::allocate_hash, chunk_cata, chunk_empty, chunk_from_thing, DBG1, DBG3, DBG_IKE, host_t::get_address, ike_sa_id_t::get_initiator_spi, host_t::get_port, ike_sa_id_t::get_responder_spi, hasher, and port.
Referenced by build_natd_payload(), and process_payloads().
 {
     hasher_t *hasher;
     chunk_t natd_chunk, natd_hash;
     u_int64_t spi_i, spi_r;
     u_int16_t port;
     hasher = this->keymat->get_hasher(this->keymat);
     if (!hasher)
     {
         DBG1(DBG_IKE, "no hasher available to build NAT-D payload");
         return chunk_empty;
     }
     spi_i = ike_sa_id->get_initiator_spi(ike_sa_id);
     spi_r = ike_sa_id->get_responder_spi(ike_sa_id);
     port = htons(host->get_port(host));
     /*  natd_hash = HASH(CKY-I | CKY-R | IP | Port) */
     natd_chunk = chunk_cata("cccc", chunk_from_thing(spi_i),
                             chunk_from_thing(spi_r), host->get_address(host),
                             chunk_from_thing(port));
     if (!hasher->allocate_hash(hasher, natd_chunk, &natd_hash))
     {
         DBG1(DBG_IKE, "creating NAT-D payload hash failed");
         return chunk_empty;
     }
     DBG3(DBG_IKE, "natd_chunk %B", &natd_chunk);
     DBG3(DBG_IKE, "natd_hash %B", &natd_hash);
     return natd_hash;
 }
static chunk_t generate_natd_hash_faked (private_isakmp_natd_t * this) static
Build a faked NAT-D payload to enforce UDP encapsulation.
Definition at line 165 of file isakmp_natd.c.
References rng_t::allocate_bytes, chunk_empty, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_IKE, rng_t::destroy, DESTROY_IF, hasher_t::get_hash_size, hasher, lib, rng, and RNG_WEAK.
Referenced by build_natd_payload().
 {
     hasher_t *hasher;
     chunk_t chunk;
     rng_t *rng;
     hasher = this->keymat->get_hasher(this->keymat);
     if (!hasher)
     {
         DBG1(DBG_IKE, "no hasher available to build NAT-D payload");
         return chunk_empty;
     }
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng ||
         !rng->allocate_bytes(rng, hasher->get_hash_size(hasher), &chunk))
     {
         DBG1(DBG_IKE, "unable to get random bytes for NAT-D fake");
         DESTROY_IF(rng);
         return chunk_empty;
     }
     rng->destroy(rng);
     return chunk;
 }
static payload_type_t get_nat_d_payload_type (ike_sa_t * ike_sa) static
Get NAT-D payload type (RFC 3947 or RFC 3947 drafts).
Definition at line 116 of file isakmp_natd.c.
References EXT_NATT_DRAFT_02_03, PLV1_NAT_D, PLV1_NAT_D_DRAFT_00_03, and ike_sa_t::supports_extension.
Referenced by build_natd_payload().
 {
     if (ike_sa->supports_extension(ike_sa, EXT_NATT_DRAFT_02_03))
     {
         return PLV1_NAT_D_DRAFT_00_03;
     }
     return PLV1_NAT_D;
 }
METHOD (task_t , build_i , status_t , private_isakmp_natd_t * this, message_t * message)
Definition at line 321 of file isakmp_natd.c.
References add_natd_payloads(), AGGRESSIVE, message_t::get_exchange_type, message_t::get_payload, ID_PROT, NEED_MORE, PLV1_SECURITY_ASSOCIATION, result, and SUCCESS.
 {
     status_t result = NEED_MORE;
     switch (message->get_exchange_type(message))
     {
         case AGGRESSIVE:
         {   /* add NAT-D payloads to the second request, already processed
              * those by the responder contained in the first response */
             result = SUCCESS;
             /* fall */
         }
         case ID_PROT:
         {   /* add NAT-D payloads to the second request, need to process
              * those by the responder contained in the second response */
             if (message->get_payload(message, PLV1_SECURITY_ASSOCIATION))
             {   /* wait for the second exchange */
                 return NEED_MORE;
             }
             add_natd_payloads(this, message);
             return result;
         }
         default:
             break;
     }
     return SUCCESS;
 }
METHOD (task_t , process_i , status_t , private_isakmp_natd_t * this, message_t * message)
Definition at line 350 of file isakmp_natd.c.
References AGGRESSIVE, COND_NAT_ANY, EXT_NATT, message_t::get_exchange_type, message_t::get_payload, ID_PROT, NEED_MORE, PLV1_SECURITY_ASSOCIATION, process_payloads(), result, and SUCCESS.
 {
     status_t result = NEED_MORE;
     if (!this->ike_sa->supports_extension(this->ike_sa, EXT_NATT))
     {   /* we didn't receive VIDs inidcating support for NAT-T */
         return SUCCESS;
     }
     switch (message->get_exchange_type(message))
     {
         case ID_PROT:
         {   /* process NAT-D payloads in the second response, added them in the
              * second request already, so we're done afterwards */
             if (message->get_payload(message, PLV1_SECURITY_ASSOCIATION))
             {   /* wait for the second exchange */
                 return NEED_MORE;
             }
             result = SUCCESS;
             /* fall */
         }
         case AGGRESSIVE:
         {   /* process NAT-D payloads in the first response, add them in the
              * following second request */
             process_payloads(this, message);
             if (this->ike_sa->has_condition(this->ike_sa, COND_NAT_ANY))
             {
                 this->ike_sa->float_ports(this->ike_sa);
             }
             return result;
         }
         default:
             break;
     }
     return SUCCESS;
 }
METHOD (task_t , process_r , status_t , private_isakmp_natd_t * this, message_t * message)
Definition at line 389 of file isakmp_natd.c.
References AGGRESSIVE, EXT_NATT, message_t::get_exchange_type, message_t::get_payload, ID_PROT, NEED_MORE, PLV1_SECURITY_ASSOCIATION, process_payloads(), result, and SUCCESS.
 {
     status_t result = NEED_MORE;
     if (!this->ike_sa->supports_extension(this->ike_sa, EXT_NATT))
     {   /* we didn't receive VIDs indicating NAT-T support */
         return SUCCESS;
     }
     switch (message->get_exchange_type(message))
     {
         case AGGRESSIVE:
         {   /* process NAT-D payloads in the second request, already added ours
              * in the first response */
             result = SUCCESS;
             /* fall */
         }
         case ID_PROT:
         {   /* process NAT-D payloads in the second request, need to add ours
              * to the second response */
             if (message->get_payload(message, PLV1_SECURITY_ASSOCIATION))
             {   /* wait for the second exchange */
                 return NEED_MORE;
             }
             process_payloads(this, message);
             return result;
         }
         default:
             break;
     }
     return SUCCESS;
 }
METHOD (task_t , build_r , status_t , private_isakmp_natd_t * this, message_t * message)
Definition at line 423 of file isakmp_natd.c.
References add_natd_payloads(), AGGRESSIVE, message_t::get_exchange_type, message_t::get_payload, ID_PROT, NEED_MORE, PLV1_SECURITY_ASSOCIATION, and SUCCESS.
 {
     switch (message->get_exchange_type(message))
     {
         case ID_PROT:
         {   /* add NAT-D payloads to second response, already processed those
              * contained in the second request */
             if (message->get_payload(message, PLV1_SECURITY_ASSOCIATION))
             {   /* wait for the second exchange */
                 return NEED_MORE;
             }
             add_natd_payloads(this, message);
             return SUCCESS;
         }
         case AGGRESSIVE:
         {   /* add NAT-D payloads to the first response, process those contained
              * in the following second request */
             add_natd_payloads(this, message);
             return NEED_MORE;
         }
         default:
             break;
     }
     return SUCCESS;
 }
METHOD (task_t , get_type , task_type_t , private_isakmp_natd_t * this)
Definition at line 450 of file isakmp_natd.c.
References TASK_ISAKMP_NATD.
 {
     return TASK_ISAKMP_NATD;
 }
METHOD (task_t , migrate , void , private_isakmp_natd_t * this, ike_sa_t * ike_sa)
Definition at line 456 of file isakmp_natd.c.
References FALSE, and ike_sa_t::get_keymat.
 {
     this->ike_sa = ike_sa;
     this->keymat = (keymat_v1_t*)ike_sa->get_keymat(ike_sa);
     this->src_seen = FALSE;
     this->dst_seen = FALSE;
     this->src_matched = FALSE;
     this->dst_matched = FALSE;
 }
METHOD (task_t , destroy , void , private_isakmp_natd_t * this)
Definition at line 467 of file isakmp_natd.c.
References free().
 {
     free(this);
 }
static void process_payloads (private_isakmp_natd_t * this, message_t * message) static
Read NAT-D payloads from message and evaluate them.
Definition at line 249 of file isakmp_natd.c.
References chunk_equals(), chunk_free(), COND_NAT_FAKE, COND_NAT_HERE, COND_NAT_THERE, message_t::create_payload_enumerator, DBG3, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, force_encap(), generate_natd_hash(), message_t::get_destination, hash_payload_t::get_hash, message_t::get_ike_sa_id, message_t::get_source, payload_t::get_type, hash, me, PLV1_NAT_D, PLV1_NAT_D_DRAFT_00_03, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     payload_t *payload;
     hash_payload_t *hash_payload;
     chunk_t hash, src_hash, dst_hash;
     ike_sa_id_t *ike_sa_id;
     host_t *me, *other;
     ike_cfg_t *config;
     /* precompute hashes for incoming NAT-D comparison */
     ike_sa_id = message->get_ike_sa_id(message);
     me = message->get_destination(message);
     other = message->get_source(message);
     dst_hash = generate_natd_hash(this, ike_sa_id, me);
     src_hash = generate_natd_hash(this, ike_sa_id, other);
     DBG3(DBG_IKE, "precalculated src_hash %B", &src_hash);
     DBG3(DBG_IKE, "precalculated dst_hash %B", &dst_hash);
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) != PLV1_NAT_D &&
             payload->get_type(payload) != PLV1_NAT_D_DRAFT_00_03)
         {
             continue;
         }
         hash_payload = (hash_payload_t*)payload;
         if (!this->dst_seen)
         {   /* the first NAT-D payload contains the destination hash */
             this->dst_seen = TRUE;
             hash = hash_payload->get_hash(hash_payload);
             DBG3(DBG_IKE, "received dst_hash %B", &hash);
             if (chunk_equals(hash, dst_hash))
             {
                 this->dst_matched = TRUE;
             }
             continue;
         }
         /* the other NAT-D payloads contain source hashes */
         this->src_seen = TRUE;
         if (!this->src_matched)
         {
             hash = hash_payload->get_hash(hash_payload);
             DBG3(DBG_IKE, "received src_hash %B", &hash);
             if (chunk_equals(hash, src_hash))
             {
                 this->src_matched = TRUE;
             }
         }
     }
     enumerator->destroy(enumerator);
     chunk_free(&src_hash);
     chunk_free(&dst_hash);
     if (this->src_seen && this->dst_seen)
     {
         this->ike_sa->set_condition(this->ike_sa, COND_NAT_HERE,
                                     !this->dst_matched);
         this->ike_sa->set_condition(this->ike_sa, COND_NAT_THERE,
                                     !this->src_matched);
         config = this->ike_sa->get_ike_cfg(this->ike_sa);
         if (this->dst_matched && this->src_matched &&
             force_encap(config))
         {
             this->ike_sa->set_condition(this->ike_sa, COND_NAT_FAKE, TRUE);
         }
     }
 }