strongSwan: ipsec_policy_mgr
ipsec_policy_mgr
libipsec
Classes
struct ipsec_policy_mgr_t
Typedefs
typedef struct ipsec_policy_mgr_t ipsec_policy_mgr_t
Functions
ipsec_policy_mgr_t * ipsec_policy_mgr_create ()
Detailed Description
Typedef Documentation
typedef struct ipsec_policy_mgr_t ipsec_policy_mgr_t
Definition at line 35 of file ipsec_policy_mgr.h.
Function Documentation
ipsec_policy_mgr_t* ipsec_policy_mgr_create ()
Create an ipsec_policy_mgr instance
Returns
ipsec_policy_mgr
Described in header.
Definition at line 276 of file ipsec_policy_mgr.c.
References INIT, linked_list_create(), rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by libipsec_init().
 {
     private_ipsec_policy_mgr_t *this;
     INIT(this,
         .public = {
             .add_policy = _add_policy,
             .del_policy = _del_policy,
             .flush_policies = _flush_policies,
             .find_by_packet = _find_by_packet,
             .destroy = _destroy,
         },
         .policies = linked_list_create(),
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
     );
     return &this->public;
 }