strongSwan: informational
informational
tasks
Classes
struct informational_t
Typedefs
typedef struct informational_t informational_t
Functions
informational_t * informational_create (ike_sa_t *ike_sa, notify_payload_t *notify)
Detailed Description
Typedef Documentation
typedef struct informational_t informational_t
Definition at line 24 of file informational.h.
Function Documentation
informational_t* informational_create (ike_sa_t * ike_sa, notify_payload_t * notify)
Create a new informational task.
Parameters
ike_sa IKE_SA this task works for
notify notify to send as initiator, NULL if responder
Returns
task to handle by the task_manager
Definition at line 225 of file informational.c.
References INIT, and notify().
Referenced by process_request(), and send_notify().
 {
     private_informational_t *this;
     INIT(this,
         .public = {
             .task = {
                 .get_type = _get_type,
                 .migrate = _migrate,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .notify = notify,
     );
     if (notify)
     {
         this->public.task.build = _build_i;
         this->public.task.process = _process_i;
     }
     else
     {
         this->public.task.build = _build_r;
         this->public.task.process = _process_r;
     }
     return &this->public;
 }