strongSwan: keymat_v1_t Struct Reference
keymat_v1_t Struct Reference
keymat_v1
#include "keymat_v1.h"
Public Attributes
keymat_t keymat
bool(* derive_ike_keys)(keymat_v1_t *this, proposal_t *proposal, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_id_t *id, auth_method_t auth, shared_key_t *shared_key)
bool(* derive_child_keys)(keymat_v1_t *this, proposal_t *proposal, diffie_hellman_t *dh, u_int32_t spi_i, u_int32_t spi_r, chunk_t nonce_i, chunk_t nonce_r, chunk_t *encr_i, chunk_t *integ_i, chunk_t *encr_r, chunk_t *integ_r)
bool(* create_hasher)(keymat_v1_t *this, proposal_t *proposal)
hasher_t *(* get_hasher)(keymat_v1_t *this)
bool(* get_hash)(keymat_v1_t *this, bool initiator, chunk_t dh, chunk_t dh_other, ike_sa_id_t *ike_sa_id, chunk_t sa_i, chunk_t id, chunk_t *hash)
bool(* get_hash_phase2)(keymat_v1_t *this, message_t *message, chunk_t *hash)
bool(* get_iv)(keymat_v1_t *this, u_int32_t mid, chunk_t *iv)
bool(* update_iv)(keymat_v1_t *this, u_int32_t mid, chunk_t last_block)
bool(* confirm_iv)(keymat_v1_t *this, u_int32_t mid)
Detailed Description
Derivation and management of sensitive keying material, IKEv1 variant.
Definition at line 32 of file keymat_v1.h.
Member Data Documentation
bool(* keymat_v1_t::confirm_iv)(keymat_v1_t *this, u_int32_t mid)
Confirms the updated IV for the given message ID.
To actually make the new IV available via get_iv this method has to be called after update_iv.
Parameters
mid message ID
Returns
TRUE if IV confirmed successfully
Definition at line 155 of file keymat_v1.h.
Referenced by finalize_message(), METHOD(), and process_ike_iv().
bool(* keymat_v1_t::create_hasher)(keymat_v1_t *this, proposal_t *proposal)
Create the negotiated hasher.
Parameters
proposal selected algorithms
Returns
TRUE, if creation was successful
Definition at line 86 of file keymat_v1.h.
Referenced by process_ike_add().
bool(* keymat_v1_t::derive_child_keys)(keymat_v1_t *this, proposal_t *proposal, diffie_hellman_t *dh, u_int32_t spi_i, u_int32_t spi_r, chunk_t nonce_i, chunk_t nonce_r, chunk_t *encr_i, chunk_t *integ_i, chunk_t *encr_r, chunk_t *integ_r)
Derive keys for the CHILD_SA.
Parameters
proposal selected algorithms
dh diffie hellman key, NULL if none used
spi_i SPI chosen by initiatior
spi_r SPI chosen by responder
nonce_i quick mode initiator nonce
nonce_r quick mode responder nonce
encr_i allocated initiators encryption key
integ_i allocated initiators integrity key
encr_r allocated responders encryption key
integ_r allocated responders integrity key
Definition at line 74 of file keymat_v1.h.
Referenced by process_child_add().
bool(* keymat_v1_t::derive_ike_keys)(keymat_v1_t *this, proposal_t *proposal, diffie_hellman_t *dh, chunk_t dh_other, chunk_t nonce_i, chunk_t nonce_r, ike_sa_id_t *id, auth_method_t auth, shared_key_t *shared_key)
Derive keys for the IKE_SA.
These keys are not handed out, but are used by the associated signers, crypters and authentication functions.
Parameters
proposal selected algorithms
dh diffie hellman key allocated by create_dh()
dh_other public DH value from other peer
nonce_i initiators nonce value
nonce_r responders nonce value
id IKE_SA identifier
auth authentication method
shared_key PSK in case of AUTH_CLASS_PSK, NULL otherwise
Returns
TRUE on success
Definition at line 55 of file keymat_v1.h.
Referenced by process_ike_add().
bool(* keymat_v1_t::get_hash)(keymat_v1_t *this, bool initiator, chunk_t dh, chunk_t dh_other, ike_sa_id_t *ike_sa_id, chunk_t sa_i, chunk_t id, chunk_t *hash)
Get HASH data for authentication.
Parameters
initiatior TRUE to create HASH_I, FALSE for HASH_R
dh public DH value of peer to create HASH for
dh_other others public DH value
ike_sa_id IKE_SA identifier
sa_i encoded SA payload of initiator
id encoded IDii payload for HASH_I (IDir for HASH_R)
hash chunk receiving allocated HASH data
Returns
TRUE if hash allocated successfully
Definition at line 107 of file keymat_v1.h.
Referenced by METHOD().
bool(* keymat_v1_t::get_hash_phase2)(keymat_v1_t *this, message_t *message, chunk_t *hash)
Get HASH data for integrity/authentication in Phase 2 exchanges.
Parameters
message message to generate the HASH data for
hash chunk receiving allocated hash data
Returns
TRUE if hash allocated successfully
Definition at line 118 of file keymat_v1.h.
Referenced by generate_message(), and METHOD().
hasher_t*(* keymat_v1_t::get_hasher)(keymat_v1_t *this)
Get the negotiated hasher.
Returns
allocated hasher or NULL
Definition at line 93 of file keymat_v1.h.
bool(* keymat_v1_t::get_iv)(keymat_v1_t *this, u_int32_t mid, chunk_t *iv)
Returns the IV for a message with the given message ID.
The return chunk contains internal data and is valid until the next get_iv/udpate_iv/confirm_iv call.
Parameters
mid message ID
iv chunk receiving IV, internal data
Returns
TRUE if IV allocated successfully
Definition at line 130 of file keymat_v1.h.
Referenced by decrypt_and_extract(), finalize_message(), and METHOD().
keymat_t keymat_v1_t::keymat
Implements keymat_t.
Definition at line 37 of file keymat_v1.h.
Referenced by keymat_create().
bool(* keymat_v1_t::update_iv)(keymat_v1_t *this, u_int32_t mid, chunk_t last_block)
Updates the IV for the next message with the given message ID.
A call of confirm_iv() is required in order to actually make the IV available. This is needed for the inbound case where we store the last block of the encrypted message but want to update the IV only after verification of the decrypted message.
Parameters
mid message ID
last_block last block of encrypted message (gets cloned)
Returns
TRUE if IV updated successfully
Definition at line 144 of file keymat_v1.h.
Referenced by decrypt_and_extract(), finalize_message(), and process_ike_iv().
The documentation for this struct was generated from the following file:
keymat_v1.h