strongSwan: watcher_t Struct Reference
watcher_t Struct Reference
watcher
#include "watcher.h"
Public Attributes
void(* add)(watcher_t *this, int fd, watcher_event_t events, watcher_cb_t cb, void *data)
void(* remove)(watcher_t *this, int fd)
watcher_state_t(* get_state)(watcher_t *this)
void(* destroy)(watcher_t *this)
Detailed Description
Watch multiple file descriptors using select().
Definition at line 75 of file watcher.h.
Member Data Documentation
void(* watcher_t::add)(watcher_t *this, int fd, watcher_event_t events, watcher_cb_t cb, void *data)
Start watching a new file descriptor.
Multiple callbacks can be registered for the same file descriptor, and all of them get notified. Such callbacks are executed concurrently.
Parameters
fd file descriptor to start watching
events ORed set of events to watch
cb callback function to invoke on events
data data to pass to cb()
Definition at line 88 of file watcher.h.
Referenced by add_watcher(), destroy_async_data(), dhcp_socket_create(), eap_radius_dae_create(), farp_spoofer_create(), forecast_forwarder_create(), kernel_netlink_ipsec_create(), kernel_netlink_net_create(), kernel_pfkey_ipsec_create(), kernel_pfroute_net_create(), METHOD(), netlink_socket_create(), pt_tls_receive(), START_TEST(), and tnc_pdp_create().
void(* watcher_t::destroy)(watcher_t *this)
Destroy a watcher_t.
Definition at line 111 of file watcher.h.
watcher_state_t(* watcher_t::get_state)(watcher_t *this)
Get the current watcher state
Returns
currently active watcher state
Definition at line 106 of file watcher.h.
Referenced by send_once().
void(* watcher_t::remove)(watcher_t *this, int fd)
Stop watching a previously registered file descriptor.
This call blocks until any active callback for this FD returns. All callbacks registered for that FD get unregistered.
Parameters
fd file descriptor to stop watching
Definition at line 99 of file watcher.h.
Referenced by METHOD(), and START_TEST().
The documentation for this struct was generated from the following file:
watcher.h