strongSwan: test_ike_cfg.c File Reference
test_ike_cfg.c File Reference
#include "test_suite.h"
#include <config/ike_cfg.h>
Functions
static void assert_family (int expected, char *addr, bool local)
START_TEST (test_get_address_family_empty)
END_TEST START_TEST (test_get_address_family_addr)
END_TEST START_TEST (test_get_address_family_multi)
END_TEST START_TEST (test_get_address_family_any)
END_TEST START_TEST (test_get_address_family_other)
END_TEST Suite * ike_cfg_suite_create ()
Function Documentation
static void assert_family (int expected, char * addr, bool local) static
Definition at line 20 of file test_ike_cfg.c.
References ck_assert_msg, ike_cfg_t::destroy, FALSE, family, FRAGMENTATION_NO, ike_cfg_create(), ike_cfg_get_family(), and IKEV2.
Referenced by START_TEST().
 {
     ike_cfg_t *cfg;
     int family;
     cfg = ike_cfg_create(IKEV2, FALSE, FALSE, local ? addr : "%any", 500,
                          local ? "%any" : addr, 500, FRAGMENTATION_NO, 0);
     family = ike_cfg_get_family(cfg, local);
     ck_assert_msg(expected == family, "expected family %d != %d (addr: '%s')",
                   expected, family, addr);
     cfg->destroy(cfg);
 }
END_TEST Suite* ike_cfg_suite_create ()
Definition at line 102 of file test_ike_cfg.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_loop_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("ike_cfg");
     tc = tcase_create("ike_cfg_get_address_family");
     tcase_add_loop_test(tc, test_get_address_family_empty, 0, 2);
     tcase_add_loop_test(tc, test_get_address_family_addr, 0, 2);
     tcase_add_loop_test(tc, test_get_address_family_multi, 0, 2);
     tcase_add_loop_test(tc, test_get_address_family_any, 0, 2);
     tcase_add_loop_test(tc, test_get_address_family_other, 0, 2);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_get_address_family_empty)
Definition at line 33 of file test_ike_cfg.c.
References assert_family().
 {
     assert_family(AF_UNSPEC, "", _i);
 }
END_TEST START_TEST (test_get_address_family_addr)
Definition at line 39 of file test_ike_cfg.c.
References assert_family().
 {
     assert_family(AF_INET, "192.168.1.1", _i);
     assert_family(AF_INET6, "fec::1", _i);
 }
END_TEST START_TEST (test_get_address_family_multi)
Definition at line 46 of file test_ike_cfg.c.
References assert_family().
 {
     assert_family(AF_INET, "192.168.1.1,192.168.2.2", _i);
     assert_family(AF_INET6, "fec::1,fec::2", _i);
     assert_family(AF_UNSPEC, "192.168.1.1,fec::1", _i);
     assert_family(AF_UNSPEC, "fec::1,192.168.1.1", _i);
 }
END_TEST START_TEST (test_get_address_family_any)
Definition at line 56 of file test_ike_cfg.c.
References assert_family().
 {
     assert_family(AF_UNSPEC, "%any", _i);
     assert_family(AF_INET, "%any4", _i);
     assert_family(AF_INET, "0.0.0.0", _i);
     assert_family(AF_INET6, "%any6", _i);
     assert_family(AF_INET6, "::", _i);
     assert_family(AF_INET, "192.168.1.1,%any", _i);
     assert_family(AF_INET, "192.168.1.1,%any4", _i);
     assert_family(AF_UNSPEC, "192.168.1.1,%any6", _i);
     assert_family(AF_INET6, "fec::1,%any", _i);
     assert_family(AF_UNSPEC, "fec::1,%any4", _i);
     assert_family(AF_INET6, "fec::1,%any6", _i);
 }
END_TEST START_TEST (test_get_address_family_other)
Definition at line 76 of file test_ike_cfg.c.
References assert_family().
 {
     assert_family(AF_INET, "192.168.1.0", _i);
     assert_family(AF_UNSPEC, "192.168.1.0/24", _i);
     assert_family(AF_UNSPEC, "192.168.1.0-192.168.1.10", _i);
     assert_family(AF_INET, "192.168.1.0/24,192.168.2.1", _i);
     assert_family(AF_INET, "192.168.1.0-192.168.1.10,192.168.2.1", _i);
     assert_family(AF_INET6, "192.168.1.0/24,fec::1", _i);
     assert_family(AF_INET6, "192.168.1.0-192.168.1.10,fec::1", _i);
     assert_family(AF_INET6, "fec::", _i);
     assert_family(AF_UNSPEC, "fec::/64", _i);
     assert_family(AF_UNSPEC, "fec::1-fec::10", _i);
     assert_family(AF_INET6, "fec::/64,fed::1", _i);
     assert_family(AF_INET6, "fec::1-fec::10,fec::1", _i);
     assert_family(AF_INET, "fec::/64,192.168.1.1", _i);
     assert_family(AF_INET, "fec::1-fec::10,192.168.1.1", _i);
     assert_family(AF_UNSPEC, "strongswan.org", _i);
     assert_family(AF_INET, "192.168.1.0,strongswan.org", _i);
     assert_family(AF_INET6, "fec::1,strongswan.org", _i);
 }