strongSwan: enum
enum
utils
Classes
struct enum_name_t
Macros
#define ENUM_FLAG_MAGIC ((enum_name_t*)~(uintptr_t)0)
#define ENUM_BEGIN(name, first, last,...) static enum_name_t name##last = {first, last, NULL, { __VA_ARGS__ }}
#define ENUM_NEXT(name, first, last, prev,...) static enum_name_t name##last = {first, last, &name##prev, { __VA_ARGS__ }}
#define ENUM_END(name, prev) enum_name_t *name = &name##prev;
#define ENUM(name, first, last,...) ENUM_BEGIN(name, first, last, __VA_ARGS__); ENUM_END(name, last)
#define ENUM_FLAGS(name, first, last,...)
#define enum_from_name(e, name, valp)
Typedefs
typedef struct enum_name_t enum_name_t
Functions
char * enum_to_name (enum_name_t *e, int val)
bool enum_from_name_as_int (enum_name_t *e, const char *name, int *val)
char * enum_flags_to_string (enum_name_t *e, u_int val, char *buf, size_t len)
int enum_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Detailed Description
Macro Definition Documentation
#define ENUM (name, first, last, ...) ENUM_BEGIN(name, first, last, __VA_ARGS__); ENUM_END(name, last)
Define a enum name with only one range.
This is a convenience macro to use when a enum_name list contains only one range, and is equal as defining ENUM_BEGIN followed by ENUM_END.
Parameters
name name of the enum_name list
first enum value of the first enum string
last enum value of the last enum string
... a list of strings
Definition at line 112 of file enum.h.
#define ENUM_BEGIN (name, first, last, ...) static enum_name_t name##last = {first, last, NULL, { __VA_ARGS__ }}
Begin a new enum_name list.
Parameters
name name of the enum_name list
first enum value of the first enum string
last enum value of the last enum string
... a list of strings
Definition at line 80 of file enum.h.
#define ENUM_END (name, prev) enum_name_t *name = &name##prev;
Complete enum name list started with ENUM_BEGIN.
Parameters
name name of the enum_name list
prev enum value of the "last" defined in ENUM_BEGIN/previous ENUM_NEXT
Definition at line 99 of file enum.h.
#define ENUM_FLAG_MAGIC ((enum_name_t*)~(uintptr_t)0)
Magic enum_name_t pointer indicating this is an enum name for flags
Definition at line 32 of file enum.h.
Referenced by enum_flags_to_string(), and enum_printf_hook().
#define ENUM_FLAGS (name, first, last, ...)
Value:
static enum_name_t name##last = {first, last, ENUM_FLAG_MAGIC, { __VA_ARGS__ }}; \
    ENUM_END(name, last)
Define a enum name with only one range for flags.
Using an enum list for flags would be overkill. Hence we use a single range with all values in range. The next pointer is abused to mark that the enum name is for flags only. Use NULL if a particular flag is not meant to be printed.
Parameters
name name of the enum_name list
first enum value of the first enum string
last enum value of the last enum string
... a list of strings
Definition at line 127 of file enum.h.
#define enum_from_name (e, name, valp)
Value:
({ \
    int _val; \
    int _found = enum_from_name_as_int(e, name, &_val); \
    if (_found) \
    { \
        *(valp) = _val; \
    } \
    _found; })
Convert a enum string back to its enum value.
Parameters
e enum names for this enum value
name name to get enum value for
valp variable sized pointer receiving value
Returns
TRUE if enum name found, FALSE otherwise
Definition at line 148 of file enum.h.
Referenced by acert(), CALLBACK(), coupling_validator_create(), filter_specific_config_suites(), issue(), load_proposals(), load_tester_creds_create(), main(), METHOD(), parse_selector(), req(), self(), set_profile(), sign_crl(), START_TEST(), stroke_loglevel(), tnc_imv_manager_create(), tnccs_error_msg_create_from_node(), and tnccs_msg_create_from_node().
#define ENUM_NEXT (name, first, last, prev, ...) static enum_name_t name##last = {first, last, &name##prev, { __VA_ARGS__ }}
Continue a enum name list startetd with ENUM_BEGIN.
Parameters
name name of the enum_name list
first enum value of the first enum string
last enum value of the last enum string
prev enum value of the "last" defined in ENUM_BEGIN/previous ENUM_NEXT
... a list of strings
Definition at line 91 of file enum.h.
Typedef Documentation
typedef struct enum_name_t enum_name_t
Definition at line 27 of file enum.h.
Function Documentation
char* enum_flags_to_string (enum_name_t * e, u_int val, char * buf, size_t len)
Convert a enum value containing flags to its string representation.
Parameters
e enum names for this enum value suitable for flags
val enum value to get string for
buf buffer to write flag string to
len buffer size
Returns
buf, NULL if buffer too small
Described in header.
Definition at line 84 of file enum.c.
References ENUM_FLAG_MAGIC, find_flag_pos(), enum_name_t::first, enum_name_t::last, name, enum_name_t::names, enum_name_t::next, snprintf, and val.
Referenced by enum_printf_hook(), and START_TEST().
 {
     char *pos = buf, *delim = "";
     int i, wr;
     if (e->next != ENUM_FLAG_MAGIC)
     {
         if (snprintf(buf, len, "(%d)", (int)val) >= len)
         {
             return NULL;
         }
         return buf;
     }
     if (snprintf(buf, len, "(unset)") >= len)
     {
         return NULL;
     }
     for (i = 0; val; i++)
     {
         u_int flag = 1 << i;
         if (val & flag)
         {
             char *name = NULL, hex[32];
             if (flag >= (u_int)e->first && flag <= (u_int)e->last)
             {
                 name = e->names[find_flag_pos(e->first, i)];
             }
             else
             {
                 snprintf(hex, sizeof(hex), "(0x%X)", flag);
                 name = hex;
             }
             if (name)
             {
                 wr = snprintf(pos, len, "%s%s", delim, name);
                 if (wr >= len)
                 {
                     return NULL;
                 }
                 len -= wr;
                 pos += wr;
                 delim = " | ";
             }
             val &= ~flag;
         }
     }
     return buf;
 }
bool enum_from_name_as_int (enum_name_t * e, const char * name, int * val)
Convert a enum string back to its enum value, integer pointer variant.
This variant takes integer pointer only, use enum_from_name() to pass enum type pointers for the result.
Parameters
e enum names for this enum value
name name to get enum value for
val integer pointer receiving value
Returns
TRUE if enum name found, FALSE otherwise
See header.
Definition at line 47 of file enum.c.
References count, FALSE, enum_name_t::first, enum_name_t::last, enum_name_t::names, enum_name_t::next, strcaseeq(), and TRUE.
 {
     do
     {
         int i, count = e->last - e->first + 1;
         for (i = 0; i < count; i++)
         {
             if (name && strcaseeq(name, e->names[i]))
             {
                 *val = e->first + i;
                 return TRUE;
             }
         }
     }
     while ((e = e->next));
     return FALSE;
 }
int enum_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook function for enum_names_t.
Arguments are: enum_names_t *names, int value
See header.
Definition at line 140 of file enum.c.
References ENUM_FLAG_MAGIC, enum_flags_to_string(), enum_to_name(), printf_hook_spec_t::minus, name, enum_name_t::next, print_in_hook(), snprintf, val, and printf_hook_spec_t::width.
Referenced by library_init().
 {
     enum_name_t *ed = *((enum_name_t**)(args[0]));
     int val = *((int*)(args[1]));
     char *name, buf[512];
     if (ed && ed->next == ENUM_FLAG_MAGIC)
     {
         name = enum_flags_to_string(ed, val, buf, sizeof(buf));
         if (name == NULL)
         {
             snprintf(buf, sizeof(buf), "(0x%X)", val);
             name = buf;
         }
     }
     else
     {
         name = enum_to_name(ed, val);
         if (name == NULL)
         {
             snprintf(buf, sizeof(buf), "(%d)", val);
             name = buf;
         }
     }
     if (spec->minus)
     {
         return print_in_hook(data, "%-*s", spec->width, name);
     }
     return print_in_hook(data, "%*s", spec->width, name);
 }
char* enum_to_name (enum_name_t * e, int val)
Convert a enum value to its string representation.
Parameters
e enum names for this enum value
val enum value to get string for
Returns
string for enum, NULL if not found
See header.
Definition at line 27 of file enum.c.
References enum_name_t::first, enum_name_t::names, and enum_name_t::next.
Referenced by CALLBACK(), enum_printf_hook(), extract_platform_info(), hmac_create(), METHOD(), openssl_hasher_create(), os_type_from_name(), START_TEST(), tnccs_error_msg_create(), tnccs_preferred_language_msg_create(), tnccs_reason_strings_msg_create(), tnccs_recommendation_msg_create(), and tty_escape_get().
 {
     if (!e)
     {
         return NULL;
     }
     do
     {
         if (val >= e->first && val <= e->last)
         {
             return e->names[val - e->first];
         }
     }
     while ((e = e->next));
     return NULL;
 }