strongSwan: medcli_listener.c File Reference
medcli_listener.c File Reference
#include "medcli_listener.h"
#include <daemon.h>
#include <library.h>
Classes
struct private_medcli_listener_t
Typedefs
typedef struct
private_medcli_listener_t private_medcli_listener_t
typedef enum mediated_state_t mediated_state_t
Enumerations
enum mediated_state_t { STATE_DOWN = 1, STATE_CONNECTING = 2, STATE_UP = 3 }
Functions
static void set_state (private_medcli_listener_t *this, char *alias, mediated_state_t state)
METHOD (listener_t, ike_state_change, bool, private_medcli_listener_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
METHOD (listener_t, child_state_change, bool, private_medcli_listener_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, child_sa_state_t state)
METHOD (medcli_listener_t, destroy, void, private_medcli_listener_t *this)
medcli_listener_t * medcli_listener_create (database_t *db)
Typedef Documentation
typedef enum mediated_state_t mediated_state_t
Definition at line 22 of file medcli_listener.c.
typedef struct private_medcli_listener_t private_medcli_listener_t
Definition at line 21 of file medcli_listener.c.
Enumeration Type Documentation
enum mediated_state_t
state of a mediated connection
Enumerator
STATE_DOWN
STATE_CONNECTING
STATE_UP
Definition at line 27 of file medcli_listener.c.
                       {
     STATE_DOWN = 1,
     STATE_CONNECTING = 2,
     STATE_UP = 3,
 };
Function Documentation
METHOD (listener_t , ike_state_change , bool , private_medcli_listener_t * this, ike_sa_t * ike_sa, ike_sa_state_t state)
Definition at line 60 of file medcli_listener.c.
References ike_sa_t::get_name, IKE_CONNECTING, IKE_DESTROYING, set_state(), STATE_CONNECTING, STATE_DOWN, and TRUE.
 {
     if (ike_sa)
     {
         switch (state)
         {
             case IKE_CONNECTING:
                 set_state(this, ike_sa->get_name(ike_sa), STATE_CONNECTING);
                 break;
             case IKE_DESTROYING:
                 set_state(this, ike_sa->get_name(ike_sa), STATE_DOWN);
             default:
                 break;
         }
     }
     return TRUE;
 }
METHOD (listener_t , child_state_change , bool , private_medcli_listener_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, child_sa_state_t state)
Definition at line 79 of file medcli_listener.c.
References CHILD_DESTROYING, CHILD_INSTALLED, child_sa_t::get_name, set_state(), STATE_DOWN, STATE_UP, and TRUE.
 {
     if (ike_sa && child_sa)
     {
         switch (state)
         {
             case CHILD_INSTALLED:
                 set_state(this, child_sa->get_name(child_sa), STATE_UP);
                 break;
             case CHILD_DESTROYING:
                 set_state(this, child_sa->get_name(child_sa), STATE_DOWN);
                 break;
             default:
                 break;
         }
     }
     return TRUE;
 }
METHOD (medcli_listener_t , destroy , void , private_medcli_listener_t * this)
Definition at line 100 of file medcli_listener.c.
References db, DB_UINT, database_t::execute, free(), and STATE_DOWN.
 {
     this->db->execute(this->db, NULL, "UPDATE Connection SET Status = ?",
                       DB_UINT, STATE_DOWN);
     free(this);
 }
static void set_state (private_medcli_listener_t * this, char * alias, mediated_state_t state) static
Update connection status in the database
Definition at line 52 of file medcli_listener.c.
References db, DB_TEXT, DB_UINT, and database_t::execute.
Referenced by METHOD().
 {
     this->db->execute(this->db, NULL,
                       "UPDATE Connection SET Status = ? WHERE Alias = ?",
                       DB_UINT, state, DB_TEXT, alias);
 }