strongSwan: imv_os_state_t Struct Reference
imv_os_state_t Struct Reference
imv_os_state
#include "imv_os_state.h"
Public Attributes
imv_state_t interface
void(* set_handshake_state)(imv_os_state_t *this, imv_os_handshake_state_t new_state)
imv_os_handshake_state_t(* get_handshake_state)(imv_os_state_t *this)
void(* set_count)(imv_os_state_t *this, int count, int count_update, int count_blacklist, int count_ok)
void(* get_count)(imv_os_state_t *this, int *count, int *count_update, int *count_blacklist, int *count_ok)
void(* set_os_settings)(imv_os_state_t *this, u_int settings)
u_int(* get_os_settings)(imv_os_state_t *this)
void(* set_missing)(imv_os_state_t *this, uint16_t missing)
uint16_t(* get_missing)(imv_os_state_t *this)
void(* add_bad_package)(imv_os_state_t *this, char *package, os_package_state_t package_state)
Detailed Description
Internal state of an imv_os_t connection instance
Definition at line 58 of file imv_os_state.h.
Member Data Documentation
void(* imv_os_state_t::add_bad_package)(imv_os_state_t *this, char *package, os_package_state_t package_state)
Store a bad package that has to be updated or removed
Parameters
package Name of software package
package_state Security state of software package
Definition at line 136 of file imv_os_state.h.
Referenced by METHOD().
void(* imv_os_state_t::get_count)(imv_os_state_t *this, int *count, int *count_update, int *count_blacklist, int *count_ok)
Set [or with multiple attributes increment] package counters
Parameters
count Number of processed packages
count_update Number of not updated packages
count_blacklist Number of blacklisted packages
count_ok Number of whitelisted packages
Definition at line 99 of file imv_os_state.h.
Referenced by METHOD().
imv_os_handshake_state_t(* imv_os_state_t::get_handshake_state)(imv_os_state_t *this)
Get state of the handshake
Returns
the handshake state of IMV
Definition at line 78 of file imv_os_state.h.
Referenced by METHOD().
uint16_t(* imv_os_state_t::get_missing)(imv_os_state_t *this)
Get number of installed packages still missing
Returns
Number of missing installed packages
Definition at line 128 of file imv_os_state.h.
Referenced by METHOD().
u_int(* imv_os_state_t::get_os_settings)(imv_os_state_t *this)
Get OS settings
Returns
OS settings
Definition at line 114 of file imv_os_state.h.
Referenced by METHOD().
imv_state_t imv_os_state_t::interface
imv_state_t interface
Definition at line 63 of file imv_os_state.h.
Referenced by METHOD().
void(* imv_os_state_t::set_count)(imv_os_state_t *this, int count, int count_update, int count_blacklist, int count_ok)
Set [or with multiple attributes increment] package counters
Parameters
count Number of processed packages
count_update Number of not updated packages
count_blacklist Number of blacklisted packages
count_ok Number of whitelisted packages
Definition at line 88 of file imv_os_state.h.
Referenced by METHOD().
void(* imv_os_state_t::set_handshake_state)(imv_os_state_t *this, imv_os_handshake_state_t new_state)
Set state of the handshake
Parameters
new_state the handshake state of IMV
Definition at line 70 of file imv_os_state.h.
Referenced by METHOD(), and receive_msg().
void(* imv_os_state_t::set_missing)(imv_os_state_t *this, uint16_t missing)
Set number of installed packages still missing
Parameters
missing Number of missing installed packages
Definition at line 121 of file imv_os_state.h.
Referenced by receive_msg().
void(* imv_os_state_t::set_os_settings)(imv_os_state_t *this, u_int settings)
Set OS settings
Parameters
settings OS settings
Definition at line 107 of file imv_os_state.h.
Referenced by receive_msg().
The documentation for this struct was generated from the following file:
imv_os_state.h