strongSwan: tnc_ifmap_soap
tnc_ifmap_soap
tnc_ifmap
Classes
struct tnc_ifmap_soap_t
Typedefs
typedef struct tnc_ifmap_soap_t tnc_ifmap_soap_t
Functions
tnc_ifmap_soap_t * tnc_ifmap_soap_create ()
Detailed Description
Typedef Documentation
typedef struct tnc_ifmap_soap_t tnc_ifmap_soap_t
Definition at line 28 of file tnc_ifmap_soap.h.
Function Documentation
tnc_ifmap_soap_t* tnc_ifmap_soap_create ()
Create a tnc_ifmap_soap instance.
See header
Definition at line 893 of file tnc_ifmap_soap.c.
References credential_manager_t::add_set, library_t::credmgr, destroy(), IFMAP_NO_FD, INIT, lib, mem_cred_create(), and soap_init().
Referenced by tnc_ifmap_listener_create().
 {
     private_tnc_ifmap_soap_t *this;
     INIT(this,
         .public = {
             .newSession = _newSession,
             .renewSession = _renewSession,
             .purgePublisher = _purgePublisher,
             .publish_ike_sa = _publish_ike_sa,
             .publish_device_ip = _publish_device_ip,
             .publish_virtual_ips = _publish_virtual_ips,
             .publish_enforcement_report = _publish_enforcement_report,
             .endSession = _endSession,
             .get_session_id = _get_session_id,
             .orphaned = _orphaned,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .fd = IFMAP_NO_FD,
         .creds = mem_cred_create(),
         .ref = 1,
     );
     lib->credmgr->add_set(lib->credmgr, &this->creds->set);
     if (!soap_init(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }