strongSwan: unknown_payload
unknown_payload
payloads
Classes
struct unknown_payload_t
Typedefs
typedef struct unknown_payload_t unknown_payload_t
Functions
unknown_payload_t * unknown_payload_create (payload_type_t type)
unknown_payload_t * unknown_payload_create_data (payload_type_t type, bool critical, chunk_t data)
Detailed Description
Typedef Documentation
typedef struct unknown_payload_t unknown_payload_t
Definition at line 26 of file unknown_payload.h.
Function Documentation
unknown_payload_t* unknown_payload_create (payload_type_t type)
Creates an empty unknown_payload_t.
Parameters
type of the payload
Returns
unknown_payload_t object
Definition at line 174 of file unknown_payload.c.
References INIT, PL_NONE, and type.
Referenced by METHOD(), payload_create(), and unknown_payload_create_data().
 {
     private_unknown_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_payload_type,
                 .destroy = _destroy,
             },
             .is_critical = _is_critical,
             .get_type = _get_type,
             .get_data = _get_data,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .payload_length = get_header_length(this),
         .type = type,
     );
     return &this->public;
 }
unknown_payload_t* unknown_payload_create_data (payload_type_t type, bool critical, chunk_t data)
Create an unknown payload with data.
Parameters
type type of payload to create
critical TRUE to set critical bit
data data to set for this payload, gets owned by payload
Returns
payload object
Definition at line 207 of file unknown_payload.c.
References data, chunk_t::len, and unknown_payload_create().
Referenced by METHOD().
 {
     private_unknown_payload_t *this;
     this = (private_unknown_payload_t*)unknown_payload_create(type);
     this->data = data;
     this->critical = critical;
     this->payload_length = get_header_length(this) + data.len;
     return &this->public;
 }