strongSwan: prf_t Struct Reference
prf_t Struct Reference
prf
#include "prf.h"
Public Attributes
bool(* get_bytes)(prf_t *this, chunk_t seed, u_int8_t *buffer) __attribute__((warn_unused_result))
bool(* allocate_bytes)(prf_t *this, chunk_t seed, chunk_t *chunk) __attribute__((warn_unused_result))
size_t(* get_block_size)(prf_t *this)
size_t(* get_key_size)(prf_t *this)
bool(* set_key)(prf_t *this, chunk_t key) __attribute__((warn_unused_result))
void(* destroy)(prf_t *this)
Detailed Description
Generic interface for pseudo-random-functions.
Definition at line 73 of file prf.h.
Member Data Documentation
bool(* prf_t::allocate_bytes)(prf_t *this, chunk_t seed, chunk_t *chunk) __attribute__((warn_unused_result))
Generates pseudo random bytes and allocate space for them.
Parameters
seed a chunk containing the seed for the next bytes
chunk chunk which will hold generated bytes
Returns
TRUE if bytes allocated and generated successfully
Definition at line 92 of file prf.h.
Referenced by METHOD().
void(* prf_t::destroy)(prf_t *this)
Destroys a prf object.
Definition at line 124 of file prf.h.
Referenced by bench_prf(), and METHOD().
size_t(* prf_t::get_block_size)(prf_t *this)
Get the block size of this prf_t object.
Returns
block size in bytes
Definition at line 100 of file prf.h.
Referenced by bench_prf(), expand_skeyid_e(), METHOD(), pbkdf2(), pbkdf2_f(), and prf_plus_create().
bool(* prf_t::get_bytes)(prf_t *this, chunk_t seed, u_int8_t *buffer) __attribute__((warn_unused_result))
Generates pseudo random bytes and writes them in the buffer.
Parameters
seed a chunk containing the seed for the next bytes
buffer pointer where the generated bytes will be written
Returns
TRUE if bytes generated successfully
Definition at line 82 of file prf.h.
Referenced by bench_prf(), expand_skeyid_e(), METHOD(), p_hash(), pbkdf2_f(), prf_plus_create(), and step3().
size_t(* prf_t::get_key_size)(prf_t *this)
Get the key size of this prf_t object.
This is a suggestion only, all implemented PRFs accept variable key length.
Returns
key size in bytes
Definition at line 110 of file prf.h.
bool(* prf_t::set_key)(prf_t *this, chunk_t key) __attribute__((warn_unused_result))
Set the key for this prf_t object.
Parameters
key key to set
Returns
TRUE if key set successfully
Definition at line 118 of file prf.h.
Referenced by bench_prf(), expand_skeyid_e(), METHOD(), pbkdf2(), and step3().
The documentation for this struct was generated from the following file:
prf.h