strongSwan: pts_ima_bios_list
pts_ima_bios_list
pts
Classes
struct pts_ima_bios_list_t
Typedefs
typedef struct pts_ima_bios_list_t pts_ima_bios_list_t
Functions
pts_ima_bios_list_t * pts_ima_bios_list_create (char *file)
Detailed Description
Typedef Documentation
typedef struct pts_ima_bios_list_t pts_ima_bios_list_t
Definition at line 28 of file pts_ima_bios_list.h.
Function Documentation
pts_ima_bios_list_t* pts_ima_bios_list_create (char * file)
Create a PTS IMA BIOS measurement object
Parameters
file Pathname pointing to the BIOS measurements
See header
Definition at line 192 of file pts_ima_bios_list.c.
References chunk_alloc, chunk_create(), close, DBG1, DBG2, DBG3, DBG_PTS, destroy(), EV_ACTION, EV_EFI_ACTION, event, FALSE, free_bios_entry(), linked_list_t::get_count, HASH_SIZE_SHA1, INIT, linked_list_t::insert_last, linked_list_create(), list, malloc_thing, bios_entry_t::measurement, bios_entry_t::pcr, chunk_t::ptr, read, res, strerror, and TRUE.
Referenced by METHOD().
 {
     private_pts_ima_bios_list_t *this;
     uint32_t pcr, event_type, event_len, seek_len;
     uint32_t buf_len = 2048;
     uint8_t event_buf[buf_len];
     chunk_t event;
     bios_entry_t *entry;
     struct stat st;
     ssize_t res;
     int fd;
     fd = open(file, O_RDONLY);
     if (fd == -1)
     {
         DBG1(DBG_PTS, "opening '%s' failed: %s", file, strerror(errno));
         return NULL;
     }
     if (fstat(fd, &st) == -1)
     {
         DBG1(DBG_PTS, "getting statistics of '%s' failed: %s", file,
              strerror(errno));
         close(fd);
         return FALSE;
     }
     INIT(this,
         .public = {
             .get_time = _get_time,
             .get_count = _get_count,
             .get_next = _get_next,
             .destroy = _destroy,
         },
         .creation_time = st.st_ctime,
         .list = linked_list_create(),
     );
     DBG2(DBG_PTS, "PCR Event Type  (Size)");
     while (TRUE)
     {
         res = read(fd, &pcr, 4);
         if (res == 0)
         {
             DBG2(DBG_PTS, "loaded bios measurements '%s' (%d entries)",
                  file, this->list->get_count(this->list));
             close(fd);
             return &this->public;
         }
         entry = malloc_thing(bios_entry_t);
         entry->pcr = pcr;
         entry->measurement = chunk_alloc(HASH_SIZE_SHA1);
         if (res != 4)
         {
             break;
         }
         if (read(fd, &event_type, 4) != 4)
         {
             break;
         }
         if (read(fd, entry->measurement.ptr, HASH_SIZE_SHA1) != HASH_SIZE_SHA1)
         {
             break;
         }
         if (read(fd, &event_len, 4) != 4)
         {
             break;
         }
         DBG2(DBG_PTS, "%2u  %N  (%u bytes)", pcr, event_type_names, event_type,
                                              event_len);
         seek_len = (event_len > buf_len) ? event_len - buf_len : 0;
         event_len -= seek_len;
         if (read(fd, event_buf, event_len) != event_len)
         {
             break;
         }
         event = chunk_create(event_buf, event_len);
         DBG3(DBG_PTS,"%B", &event);
         if (event_type == EV_ACTION || event_type == EV_EFI_ACTION)
         {
             DBG2(DBG_PTS, "     '%.*s'", event_len, event_buf);
         }
         if (seek_len > 0 && lseek(fd, seek_len, SEEK_CUR) == -1)
         {
                 break;
         }
         this->list->insert_last(this->list, entry);
     }
     DBG1(DBG_PTS, "loading bios measurements '%s' failed: %s", file,
          strerror(errno));
     free_bios_entry(entry);
     close(fd);
     destroy(this);
     return NULL;
 }