strongSwan: job_t Struct Reference
job_t Struct Reference
job
#include "job.h"
Public Attributes
job_status_t status
job_requeue_t(* execute)(job_t *this)
bool(* cancel)(job_t *this)
job_priority_t(* get_priority)(job_t *this)
void(* destroy)(job_t *this)
Detailed Description
Job interface as it is stored in the job queue.
Definition at line 119 of file job.h.
Member Data Documentation
bool(* job_t::cancel)(job_t *this)
Cancel a job.
Implementing this method is optional. It allows potentially blocking jobs to be canceled during shutdown.
If no special action is to be taken simply return FALSE then the thread executing the job will be canceled. If TRUE is returned the job is expected to return from execute() itself (i.e. the thread won't be canceled explicitly and can still be joined later). Jobs that return FALSE have to make sure they provide the appropriate cancellation points.
Note
Regular jobs that do not block MUST NOT implement this method.
This method could be called even before execute() has been called.
Returns
FALSE to cancel the thread, TRUE if canceled otherwise
Definition at line 155 of file job.h.
Referenced by METHOD(), and process_job().
void(* job_t::destroy)(job_t *this)
Destroy a job.
Is called after a job is executed or got canceled. It is also called for queued jobs that were never executed.
Use the status of a job to decide what to do during destruction.
Definition at line 172 of file job.h.
Referenced by METHOD(), process_job(), and restart().
job_requeue_t(* job_t::execute)(job_t *this)
Execute a job.
The processing facility executes a job using this method. Jobs are one-shot, they are destroyed after execution (depending on the return value here), so don't use a job once it has been queued.
Returns
policy how to requeue the job
Definition at line 135 of file job.h.
Referenced by METHOD(), and process_job().
job_priority_t(* job_t::get_priority)(job_t *this)
Get the priority of a job.
Returns
job priority
Definition at line 162 of file job.h.
Referenced by METHOD().
job_status_t job_t::status
Status of this job, is modified exclusively by the processor/scheduler
Definition at line 124 of file job.h.
Referenced by METHOD(), process_job(), and restart().
The documentation for this struct was generated from the following file:
job.h