strongSwan: whitelist_listener
whitelist_listener
whitelist
Classes
struct whitelist_listener_t
Typedefs
typedef struct whitelist_listener_t whitelist_listener_t
Functions
whitelist_listener_t * whitelist_listener_create ()
Detailed Description
Typedef Documentation
typedef struct whitelist_listener_t whitelist_listener_t
Definition at line 26 of file whitelist_listener.h.
Function Documentation
whitelist_listener_t* whitelist_listener_create ()
Create a whitelist_listener instance.
See header
Definition at line 189 of file whitelist_listener.c.
References equals(), FALSE, settings_t::get_bool, hash(), hashtable_create(), INIT, lib, library_t::ns, rwlock_create(), RWLOCK_TYPE_DEFAULT, and library_t::settings.
Referenced by whitelist_plugin_create().
 {
     private_whitelist_listener_t *this;
     INIT(this,
         .public = {
             .listener = {
                 .authorize = _authorize,
             },
             .add = _add,
             .remove = _remove_,
             .create_enumerator = _create_enumerator,
             .flush = _flush,
             .set_active = _set_active,
             .destroy = _destroy,
         },
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .ids = hashtable_create((hashtable_hash_t)hash,
                                 (hashtable_equals_t)equals, 32),
         .enabled = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.whitelist.enable", FALSE, lib->ns),
     );
     return &this->public;
 }