strongSwan: config.c File Reference
config.c File Reference
#include "config.h"
#include <daemon.h>
#include <conftest.h>
Classes
struct private_config_t
Typedefs
typedef struct private_config_t private_config_t
Functions
static bool ike_filter (void *data, peer_cfg_t **in, ike_cfg_t **out)
METHOD (backend_t, create_ike_cfg_enumerator, enumerator_t *, private_config_t *this, host_t *me, host_t *other)
METHOD (backend_t, create_peer_cfg_enumerator, enumerator_t *, private_config_t *this, identification_t *me, identification_t *other)
METHOD (backend_t, get_peer_cfg_by_name, peer_cfg_t *, private_config_t *this, char *name)
static ike_cfg_t * load_ike_config (private_config_t *this, settings_t *settings, char *config)
static child_cfg_t * load_child_config (private_config_t *this, settings_t *settings, char *config, char *child)
static peer_cfg_t * load_peer_config (private_config_t *this, settings_t *settings, char *config)
METHOD (config_t, load, void, private_config_t *this, settings_t *settings)
METHOD (config_t, destroy, void, private_config_t *this)
config_t * config_create ()
Typedef Documentation
typedef struct private_config_t private_config_t
Definition at line 21 of file config.c.
Function Documentation
static bool ike_filter (void * data, peer_cfg_t ** in, ike_cfg_t ** out) static
filter function for ike configs
Definition at line 42 of file config.c.
References TRUE.
Referenced by METHOD().
 {
     *out = (*in)->get_ike_cfg(*in);
     return TRUE;
 }
static child_cfg_t* load_child_config (private_config_t * this, settings_t * settings, char * config, char * child) static
Load CHILD config for given section names
Definition at line 139 of file config.c.
References ACTION_NONE, child_cfg_t::add_proposal, child_cfg_t::add_traffic_selector, child_cfg_create(), DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), FALSE, settings_t::get_bool, settings_t::get_int, settings_t::get_str, MODE_TRANSPORT, MODE_TUNNEL, proposal, proposal_create_default(), proposal_create_default_aead(), proposal_create_from_string(), PROTO_ESP, traffic_selector_create_dynamic(), traffic_selector_create_from_cidr(), and TRUE.
Referenced by load_peer_config().
 {
     child_cfg_t *child_cfg;
     lifetime_cfg_t lifetime = {};
     enumerator_t *enumerator;
     proposal_t *proposal;
     traffic_selector_t *ts;
     ipsec_mode_t mode = MODE_TUNNEL;
     char *token;
     u_int32_t tfc;
     if (settings->get_bool(settings, "configs.%s.%s.transport",
                            FALSE, config, child))
     {
         mode = MODE_TRANSPORT;
     }
     tfc = settings->get_int(settings, "configs.%s.%s.tfc_padding",
                             0, config, child);
     child_cfg = child_cfg_create(child, &lifetime, NULL, FALSE, mode,
                                  ACTION_NONE, ACTION_NONE, ACTION_NONE,
                                  FALSE, 0, 0, NULL, NULL, tfc);
     token = settings->get_str(settings, "configs.%s.%s.proposal",
                               NULL, config, child);
     if (token)
     {
         enumerator = enumerator_create_token(token, ",", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             proposal = proposal_create_from_string(PROTO_ESP, token);
             if (proposal)
             {
                 child_cfg->add_proposal(child_cfg, proposal);
             }
             else
             {
                 DBG1(DBG_CFG, "parsing proposal '%s' failed, skipped", token);
             }
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         child_cfg->add_proposal(child_cfg, proposal_create_default(PROTO_ESP));
         child_cfg->add_proposal(child_cfg,
                                 proposal_create_default_aead(PROTO_ESP));
     }
     token = settings->get_str(settings, "configs.%s.%s.lts", NULL, config, child);
     if (token)
     {
         enumerator = enumerator_create_token(token, ",", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             ts = traffic_selector_create_from_cidr(token, 0, 0, 65535);
             if (ts)
             {
                 child_cfg->add_traffic_selector(child_cfg, TRUE, ts);
             }
             else
             {
                 DBG1(DBG_CFG, "invalid local ts: %s, skipped", token);
             }
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         ts = traffic_selector_create_dynamic(0, 0, 65535);
         child_cfg->add_traffic_selector(child_cfg, TRUE, ts);
     }
     token = settings->get_str(settings, "configs.%s.%s.rts", NULL, config, child);
     if (token)
     {
         enumerator = enumerator_create_token(token, ",", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             ts = traffic_selector_create_from_cidr(token, 0, 0, 65535);
             if (ts)
             {
                 child_cfg->add_traffic_selector(child_cfg, FALSE, ts);
             }
             else
             {
                 DBG1(DBG_CFG, "invalid remote ts: %s, skipped", token);
             }
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         ts = traffic_selector_create_dynamic(0, 0, 65535);
         child_cfg->add_traffic_selector(child_cfg, FALSE, ts);
     }
     return child_cfg;
 }
static ike_cfg_t* load_ike_config (private_config_t * this, settings_t * settings, char * config) static
Load IKE config for a given section name
Definition at line 96 of file config.c.
References ike_cfg_t::add_proposal, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), FALSE, FRAGMENTATION_NO, settings_t::get_bool, settings_t::get_int, settings_t::get_str, ike_cfg_create(), IKEV2, proposal, proposal_create_default(), proposal_create_default_aead(), proposal_create_from_string(), PROTO_IKE, and TRUE.
Referenced by load_peer_config().
 {
     enumerator_t *enumerator;
     ike_cfg_t *ike_cfg;
     proposal_t *proposal;
     char *token;
     ike_cfg = ike_cfg_create(IKEV2, TRUE,
         settings->get_bool(settings, "configs.%s.fake_nat", FALSE, config),
         settings->get_str(settings, "configs.%s.lhost", "%any", config),
         settings->get_int(settings, "configs.%s.lport", 500, config),
         settings->get_str(settings, "configs.%s.rhost", "%any", config),
         settings->get_int(settings, "configs.%s.rport", 500, config),
         FRAGMENTATION_NO, 0);
     token = settings->get_str(settings, "configs.%s.proposal", NULL, config);
     if (token)
     {
         enumerator = enumerator_create_token(token, ",", " ");
         while (enumerator->enumerate(enumerator, &token))
         {
             proposal = proposal_create_from_string(PROTO_IKE, token);
             if (proposal)
             {
                 ike_cfg->add_proposal(ike_cfg, proposal);
             }
             else
             {
                 DBG1(DBG_CFG, "parsing proposal '%s' failed, skipped", token);
             }
         }
         enumerator->destroy(enumerator);
     }
     else
     {
         ike_cfg->add_proposal(ike_cfg, proposal_create_default(PROTO_IKE));
         ike_cfg->add_proposal(ike_cfg, proposal_create_default_aead(PROTO_IKE));
     }
     return ike_cfg;
 }
static peer_cfg_t* load_peer_config (private_config_t * this, settings_t * settings, char * config) static
Load peer config for a given section name
Definition at line 241 of file config.c.
References auth_cfg_t::add, peer_cfg_t::add_auth_cfg, peer_cfg_t::add_child_cfg, peer_cfg_t::add_pool, auth_cfg_create(), AUTH_CLASS_PUBKEY, AUTH_RULE_AUTH_CLASS, AUTH_RULE_CERT_POLICY, AUTH_RULE_ECDSA_STRENGTH, AUTH_RULE_IDENTITY, AUTH_RULE_RSA_STRENGTH, CERT_ALWAYS_SEND, settings_t::create_section_enumerator, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, FALSE, settings_t::get_int, settings_t::get_str, identification_create_from_string(), load_child_config(), load_ike_config(), peer_cfg_create(), strdup, TRUE, and UNIQUE_NO.
Referenced by METHOD().
 {
     ike_cfg_t *ike_cfg;
     peer_cfg_t *peer_cfg;
     auth_cfg_t *auth;
     child_cfg_t *child_cfg;
     enumerator_t *enumerator;
     identification_t *lid, *rid;
     char *child, *policy, *pool;
     uintptr_t strength;
     ike_cfg = load_ike_config(this, settings, config);
     peer_cfg = peer_cfg_create(config, ike_cfg, CERT_ALWAYS_SEND,
                                UNIQUE_NO, 1, 0, 0, 0, 0, FALSE, FALSE, TRUE,
                                0, 0, FALSE, NULL, NULL);
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     lid = identification_create_from_string(
                 settings->get_str(settings, "configs.%s.lid", "%any", config));
     auth->add(auth, AUTH_RULE_IDENTITY, lid);
     peer_cfg->add_auth_cfg(peer_cfg, auth, TRUE);
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     rid = identification_create_from_string(
                 settings->get_str(settings, "configs.%s.rid", "%any", config));
     strength = settings->get_int(settings, "configs.%s.rsa_strength", 0, config);
     if (strength)
     {
         auth->add(auth, AUTH_RULE_RSA_STRENGTH, strength);
     }
     strength = settings->get_int(settings, "configs.%s.ecdsa_strength", 0, config);
     if (strength)
     {
         auth->add(auth, AUTH_RULE_ECDSA_STRENGTH, strength);
     }
     policy = settings->get_str(settings, "configs.%s.cert_policy", NULL, config);
     if (policy)
     {
         auth->add(auth, AUTH_RULE_CERT_POLICY, strdup(policy));
     }
     auth->add(auth, AUTH_RULE_IDENTITY, rid);
     peer_cfg->add_auth_cfg(peer_cfg, auth, FALSE);
     pool = settings->get_str(settings, "configs.%s.named_pool", NULL, config);
     if (pool)
     {
         peer_cfg->add_pool(peer_cfg, pool);
     }
     DBG1(DBG_CFG, "loaded config %s: %Y - %Y", config, lid, rid);
     enumerator = settings->create_section_enumerator(settings,
                                                      "configs.%s", config);
     while (enumerator->enumerate(enumerator, &child))
     {
         child_cfg = load_child_config(this, settings, config, child);
         peer_cfg->add_child_cfg(peer_cfg, child_cfg);
     }
     enumerator->destroy(enumerator);
     return peer_cfg;
 }
METHOD (backend_t , create_ike_cfg_enumerator , enumerator_t * , private_config_t * this, host_t * me, host_t * other)
Definition at line 48 of file config.c.
References enumerator_create_filter(), and ike_filter().
 {
     return enumerator_create_filter(
                             this->configs->create_enumerator(this->configs),
                             (void*)ike_filter, NULL, NULL);
 }
METHOD (backend_t , create_peer_cfg_enumerator , enumerator_t * , private_config_t * this, identification_t * me, identification_t * other)
Definition at line 57 of file config.c.
 {
     return this->configs->create_enumerator(this->configs);
 }
METHOD (backend_t , get_peer_cfg_by_name , peer_cfg_t * , private_config_t * this, char * name)
Definition at line 63 of file config.c.
References peer_cfg_t::create_child_cfg_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, child_cfg_t::get_name, peer_cfg_t::get_ref, name, and streq().
 {
     enumerator_t *e1, *e2;
     peer_cfg_t *current, *found = NULL;
     child_cfg_t *child;
     e1 = this->configs->create_enumerator(this->configs);
     while (e1->enumerate(e1, &current))
     {
         e2 = current->create_child_cfg_enumerator(current);
         while (e2->enumerate(e2, &child))
         {
             if (streq(child->get_name(child), name))
             {
                 found = current;
                 found->get_ref(found);
                 break;
             }
         }
         e2->destroy(e2);
         if (found)
         {
             break;
         }
     }
     e1->destroy(e1);
     return found;
 }
METHOD (config_t , load , void , private_config_t * this, settings_t * settings)
Definition at line 305 of file config.c.
References settings_t::create_section_enumerator, enumerator_t::destroy, enumerator_t::enumerate, and load_peer_config().
 {
     enumerator_t *enumerator;
     char *config;
     enumerator = settings->create_section_enumerator(settings, "configs");
     while (enumerator->enumerate(enumerator, &config))
     {
         this->configs->insert_last(this->configs,
                                 load_peer_config(this, settings, config));
     }
     enumerator->destroy(enumerator);
 }
METHOD (config_t , destroy , void , private_config_t * this)
Definition at line 320 of file config.c.
References destroy(), and free().
 {
     this->configs->destroy_offset(this->configs, offsetof(peer_cfg_t, destroy));
     free(this);
 }