strongSwan: tnc_pdp_plugin.c File Reference
tnc_pdp_plugin.c File Reference
#include "tnc_pdp_plugin.h"
#include "tnc_pdp.h"
#include <daemon.h>
Classes
struct private_tnc_pdp_plugin_t
Typedefs
typedef struct
private_tnc_pdp_plugin_t private_tnc_pdp_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_tnc_pdp_plugin_t *this)
static bool plugin_cb (private_tnc_pdp_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_tnc_pdp_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_tnc_pdp_plugin_t *this)
plugin_t * tnc_pdp_plugin_create ()
Typedef Documentation
typedef struct private_tnc_pdp_plugin_t private_tnc_pdp_plugin_t
Definition at line 21 of file tnc_pdp_plugin.c.
Function Documentation
METHOD (plugin_t , get_name , char * , private_tnc_pdp_plugin_t * this)
Definition at line 40 of file tnc_pdp_plugin.c.
 {
     return "tnc-pdp";
 }
METHOD (plugin_t , get_features , int , private_tnc_pdp_plugin_t * this, plugin_feature_t * features[])
Definition at line 67 of file tnc_pdp_plugin.c.
References AUTH_HMAC_MD5_128, countof, HASH_MD5, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_DEPENDS, and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "tnc-pdp"),
                 PLUGIN_DEPENDS(CUSTOM, "imv-manager"),
                 PLUGIN_DEPENDS(HASHER, HASH_MD5),
                 PLUGIN_DEPENDS(SIGNER, AUTH_HMAC_MD5_128),
                 PLUGIN_DEPENDS(NONCE_GEN),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_tnc_pdp_plugin_t * this)
Definition at line 82 of file tnc_pdp_plugin.c.
References free().
 {
     free(this);
 }
static bool plugin_cb (private_tnc_pdp_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Register listener
Definition at line 49 of file tnc_pdp_plugin.c.
References DESTROY_IF, FALSE, tnc_pdp_create(), and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         this->pdp = tnc_pdp_create();
         if (!this->pdp)
         {
             return FALSE;
         }
     }
     else
     {
         DESTROY_IF(this->pdp);
     }
     return TRUE;
 }
plugin_t* tnc_pdp_plugin_create ()
Definition at line 91 of file tnc_pdp_plugin.c.
References INIT.
 {
     private_tnc_pdp_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }