strongSwan: kernel_sad_tests.c File Reference
kernel_sad_tests.c File Reference
#include <tests/test_suite.h>
#include "tkm_kernel_sad.h"
Functions
START_TEST (test_sad_creation)
END_TEST START_TEST (test_insert)
END_TEST START_TEST (test_insert_duplicate)
END_TEST START_TEST (test_get_esa_id)
END_TEST START_TEST (test_get_esa_id_nonexistent)
END_TEST START_TEST (test_get_other_esa_id)
END_TEST START_TEST (test_get_other_esa_id_nonexistent)
END_TEST START_TEST (test_get_dst_host)
END_TEST START_TEST (test_get_dst_host_nonexistent)
END_TEST START_TEST (test_remove)
END_TEST START_TEST (test_remove_nonexistent)
END_TEST Suite * make_kernel_sad_tests ()
Function Documentation
END_TEST Suite* make_kernel_sad_tests ()
Definition at line 164 of file kernel_sad_tests.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("kernel SAD tests");
     tc = tcase_create("creation");
     tcase_add_test(tc, test_sad_creation);
     suite_add_tcase(s, tc);
     tc = tcase_create("insert");
     tcase_add_test(tc, test_insert);
     tcase_add_test(tc, test_insert_duplicate);
     suite_add_tcase(s, tc);
     tc = tcase_create("get_esa_id");
     tcase_add_test(tc, test_get_esa_id);
     tcase_add_test(tc, test_get_esa_id_nonexistent);
     suite_add_tcase(s, tc);
     tc = tcase_create("get_other_esa_id");
     tcase_add_test(tc, test_get_other_esa_id);
     tcase_add_test(tc, test_get_other_esa_id_nonexistent);
     suite_add_tcase(s, tc);
     tc = tcase_create("get_dst_host");
     tcase_add_test(tc, test_get_dst_host);
     tcase_add_test(tc, test_get_dst_host_nonexistent);
     suite_add_tcase(s, tc);
     tc = tcase_create("remove");
     tcase_add_test(tc, test_remove);
     tcase_add_test(tc, test_remove_nonexistent);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_sad_creation)
Definition at line 21 of file kernel_sad_tests.c.
References tkm_kernel_sad_t::destroy, fail_if, and tkm_kernel_sad_create().
 {
     tkm_kernel_sad_t *sad = NULL;
     sad = tkm_kernel_sad_create();
     fail_if(!sad, "Error creating tkm kernel SAD");
     sad->destroy(sad);
 }
END_TEST START_TEST (test_insert)
Definition at line 32 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, fail_unless, host_create_from_string(), tkm_kernel_sad_t::insert, and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->insert(sad, 1, 2, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_insert_duplicate)
Definition at line 45 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, fail_if, fail_unless, host_create_from_string(), tkm_kernel_sad_t::insert, and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->insert(sad, 1, 2, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     fail_if(sad->insert(sad, 1, 2, addr, addr, 27, 42, 50),
             "Expected error inserting duplicate entry");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_get_esa_id)
Definition at line 60 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, fail_unless, tkm_kernel_sad_t::get_esa_id, host_create_from_string(), tkm_kernel_sad_t::insert, and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->insert(sad, 23, 54, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     fail_unless(sad->get_esa_id(sad, addr, addr, 42, 50) == 23,
                 "Error getting esa id");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_get_esa_id_nonexistent)
Definition at line 73 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, fail_unless, tkm_kernel_sad_t::get_esa_id, host_create_from_string(), and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->get_esa_id(sad, addr, addr, 42, 50) == 0,
                 "Got esa id for nonexistent SAD entry");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_get_other_esa_id)
Definition at line 84 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, fail_unless, tkm_kernel_sad_t::get_other_esa_id, host_create_from_string(), tkm_kernel_sad_t::insert, and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->insert(sad, 23, 54, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     fail_unless(sad->insert(sad, 24, 54, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     fail_unless(sad->get_other_esa_id(sad, 23) == 24,
                 "Error getting other esa id");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_get_other_esa_id_nonexistent)
Definition at line 99 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, fail_unless, tkm_kernel_sad_t::get_other_esa_id, host_create_from_string(), tkm_kernel_sad_t::insert, and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->get_other_esa_id(sad, 1) == 0,
                 "Got other esa id for nonexistent SAD entry");
     fail_unless(sad->insert(sad, 23, 54, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     fail_unless(sad->get_other_esa_id(sad, 23) == 0,
                 "Got own esa id");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_get_dst_host)
Definition at line 115 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, dst, host_t::equals, fail_unless, tkm_kernel_sad_t::get_dst_host, host_create_from_string(), tkm_kernel_sad_t::insert, and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->insert(sad, 23, 54, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     host_t *dst = sad->get_dst_host(sad, 54, 42, 50);
     fail_unless(addr->equals(addr, dst), "Error getting dst host");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_get_dst_host_nonexistent)
Definition at line 129 of file kernel_sad_tests.c.
References tkm_kernel_sad_t::destroy, fail_unless, tkm_kernel_sad_t::get_dst_host, and tkm_kernel_sad_create().
 {
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->get_dst_host(sad, 1, 12, 50) == NULL,
                 "Got dst for nonexistent SAD entry");
     sad->destroy(sad);
 }
END_TEST START_TEST (test_remove)
Definition at line 138 of file kernel_sad_tests.c.
References addr, tkm_kernel_sad_t::destroy, host_t::destroy, fail_unless, tkm_kernel_sad_t::get_esa_id, host_create_from_string(), tkm_kernel_sad_t::insert, tkm_kernel_sad_t::remove, and tkm_kernel_sad_create().
 {
     host_t *addr = host_create_from_string("127.0.0.1", 1024);
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_unless(sad->insert(sad, 23, 54, addr, addr, 27, 42, 50),
                 "Error inserting SAD entry");
     fail_unless(sad->get_esa_id(sad, addr, addr, 42, 50) == 23,
                 "Error getting esa id");
     fail_unless(sad->remove(sad, 23),
                 "Error removing SAD entry");
     fail_unless(sad->get_esa_id(sad, addr, addr, 42, 50) == 0,
                 "Got esa id for removed SAD entry");
     sad->destroy(sad);
     addr->destroy(addr);
 }
END_TEST START_TEST (test_remove_nonexistent)
Definition at line 155 of file kernel_sad_tests.c.
References tkm_kernel_sad_t::destroy, fail_if, tkm_kernel_sad_t::remove, and tkm_kernel_sad_create().
 {
     tkm_kernel_sad_t *sad = tkm_kernel_sad_create();
     fail_if(sad->remove(sad, 1),
             "Expected error removing nonexistent SAD entry");
     sad->destroy(sad);
 }