strongSwan: ke_payload
ke_payload
payloads
Classes
struct ke_payload_t
Typedefs
typedef struct ke_payload_t ke_payload_t
Functions
ke_payload_t * ke_payload_create (payload_type_t type)
ke_payload_t * ke_payload_create_from_diffie_hellman (payload_type_t type, diffie_hellman_t *dh)
Detailed Description
Typedef Documentation
typedef struct ke_payload_t ke_payload_t
Definition at line 25 of file ke_payload.h.
Function Documentation
ke_payload_t* ke_payload_create (payload_type_t type)
Creates an empty ke_payload_t object.
Parameters
type PLV2_KEY_EXCHANGE or PLV1_KEY_EXCHANGE
Returns
ke_payload_t object
Definition at line 216 of file ke_payload.c.
References INIT, MODP_NONE, PL_NONE, and type.
Referenced by ke_payload_create_from_diffie_hellman(), and payload_create().
 {
     private_ke_payload_t *this;
     INIT(this,
         .public = {
             .payload_interface = {
                 .verify = _verify,
                 .get_encoding_rules = _get_encoding_rules,
                 .get_header_length = _get_header_length,
                 .get_length = _get_length,
                 .get_next_type = _get_next_type,
                 .set_next_type = _set_next_type,
                 .get_type = _get_type,
                 .destroy = _destroy,
             },
             .get_key_exchange_data = _get_key_exchange_data,
             .get_dh_group_number = _get_dh_group_number,
             .destroy = _destroy,
         },
         .next_payload = PL_NONE,
         .dh_group_number = MODP_NONE,
         .type = type,
     );
     this->payload_length = get_header_length(this);
     return &this->public;
 }
ke_payload_t* ke_payload_create_from_diffie_hellman (payload_type_t type, diffie_hellman_t * dh)
Creates a ke_payload_t from a diffie_hellman_t.
Parameters
type PLV2_KEY_EXCHANGE or PLV1_KEY_EXCHANGE
dh diffie hellman object containing group and key
Returns
ke_payload_t object, NULL on error
Definition at line 247 of file ke_payload.c.
References diffie_hellman_t::get_dh_group, diffie_hellman_t::get_my_public_value, ke_payload_create(), and value.
Referenced by add_ke(), build_payloads(), and METHOD().
 {
     private_ke_payload_t *this;
     chunk_t value;
     if (!dh->get_my_public_value(dh, &value))
     {
         return NULL;
     }
     this = (private_ke_payload_t*)ke_payload_create(type);
     this->key_exchange_data = value;
     this->dh_group_number = dh->get_dh_group(dh);
     this->payload_length += this->key_exchange_data.len;
     return &this->public;
 }