strongSwan: tnccs_error_msg
tnccs_error_msg
tnccs_11
Classes
struct tnccs_error_msg_t
Typedefs
typedef enum tnccs_error_type_t tnccs_error_type_t
typedef struct tnccs_error_msg_t tnccs_error_msg_t
Enumerations
enum tnccs_error_type_t {
TNCCS_ERROR_BATCH_TOO_LONG, TNCCS_ERROR_MALFORMED_BATCH, TNCCS_ERROR_INVALID_BATCH_ID, TNCCS_ERROR_INVALID_RECIPIENT_TYPE,
TNCCS_ERROR_INTERNAL_ERROR, TNCCS_ERROR_OTHER
}
Functions
tnccs_msg_t * tnccs_error_msg_create_from_node (xmlNodePtr node)
tnccs_msg_t * tnccs_error_msg_create (tnccs_error_type_t type, char *msg)
Variables
enum_name_t * tnccs_error_type_names
Detailed Description
Typedef Documentation
typedef struct tnccs_error_msg_t tnccs_error_msg_t
Definition at line 25 of file tnccs_error_msg.h.
typedef enum tnccs_error_type_t tnccs_error_type_t
Definition at line 24 of file tnccs_error_msg.h.
Enumeration Type Documentation
enum tnccs_error_type_t
TNCCS error types as defined in section 8.1.4 of TCG TNC IF-TNCCS v1.2
Enumerator
TNCCS_ERROR_BATCH_TOO_LONG
TNCCS_ERROR_MALFORMED_BATCH
TNCCS_ERROR_INVALID_BATCH_ID
TNCCS_ERROR_INVALID_RECIPIENT_TYPE
TNCCS_ERROR_INTERNAL_ERROR
TNCCS_ERROR_OTHER
Definition at line 32 of file tnccs_error_msg.h.
{
     TNCCS_ERROR_BATCH_TOO_LONG,
     TNCCS_ERROR_MALFORMED_BATCH,
     TNCCS_ERROR_INVALID_BATCH_ID,
     TNCCS_ERROR_INVALID_RECIPIENT_TYPE,
     TNCCS_ERROR_INTERNAL_ERROR,
     TNCCS_ERROR_OTHER
 };
Function Documentation
tnccs_msg_t* tnccs_error_msg_create (tnccs_error_type_t type, char * msg)
Create a TNCCS-Error message from parameters
Parameters
type TNCCS error type
msg arbitrary error message
See header
Definition at line 152 of file tnccs_error_msg.c.
References DBG1, DBG_TNC, enum_to_name(), INIT, n, strdup, tnccs_error_type_names, TNCCS_MSG_ERROR, tnccs_msg_type_names, and type.
Referenced by METHOD(), tnccs_msg_create_from_node(), tnccs_reason_strings_msg_create_from_node(), and tnccs_recommendation_msg_create_from_node().
 {
     private_tnccs_error_msg_t *this;
     xmlNodePtr n, n2;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_message = _get_message,
         },
         .type = TNCCS_MSG_ERROR,
         .ref = 1,
         .node =  xmlNewNode(NULL, "TNCC-TNCS-Message"),
         .error_type = type,
         .error_msg  = strdup(msg),
     );
     DBG1(DBG_TNC, "%s", msg);
     n = xmlNewNode(NULL, "Type");
     xmlNodeSetContent(n, "00000002");
     xmlAddChild(this->node, n);
     n = xmlNewNode(NULL, "XML");
     xmlAddChild(this->node, n);
     n2 = xmlNewNode(NULL, enum_to_name(tnccs_msg_type_names, this->type));
     xmlNewProp(n2, "type", enum_to_name(tnccs_error_type_names, type));
     xmlNodeSetContent(n2, msg);
     xmlAddChild(n, n2);
     return &this->public.tnccs_msg_interface;
 }
tnccs_msg_t* tnccs_error_msg_create_from_node (xmlNodePtr node)
Create a TNCCS-Error message from XML-encoded message node
Parameters
node XML-encoded message node
See header
Definition at line 107 of file tnccs_error_msg.c.
References enum_from_name, INIT, strdup, TNCCS_ERROR_OTHER, tnccs_error_type_names, and TNCCS_MSG_ERROR.
Referenced by tnccs_msg_create_from_node().
 {
     private_tnccs_error_msg_t *this;
     xmlChar *error_type_name, *error_msg;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_message = _get_message,
         },
         .type = TNCCS_MSG_ERROR,
         .ref = 1,
         .node = node,
         .error_type = TNCCS_ERROR_OTHER,
     );
     error_type_name = xmlGetProp(node, "type");
     if (error_type_name)
     {
         if (!enum_from_name(tnccs_error_type_names, error_type_name,
                             &this->error_type))
         {
             this->error_type = TNCCS_ERROR_OTHER;
         }
         xmlFree(error_type_name);
     }
     error_msg = xmlNodeGetContent(node);
     if (error_msg)
     {
         this->error_msg = strdup(error_msg);
         xmlFree(error_msg);
     }
     return &this->public.tnccs_msg_interface;
 }
Variable Documentation
enum_name_t* tnccs_error_type_names
enum name for tnccs_error_type_t.
Referenced by handle_message(), tnccs_error_msg_create(), and tnccs_error_msg_create_from_node().