strongSwan: guest.c File Reference
guest.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/uio.h>
#include <unistd.h>
#include <stdio.h>
#include <fcntl.h>
#include <signal.h>
#include <dirent.h>
#include <termios.h>
#include <stdarg.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
#include "dumm.h"
#include "guest.h"
#include "mconsole.h"
#include "cowfs.h"
Classes
struct private_guest_t
struct exec_str_t
Macros
#define _GNU_SOURCE
#define PERME (S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH)
#define PERM (S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH)
#define MASTER_DIR "master"
#define DIFF_DIR "diff"
#define UNION_DIR "union"
#define ARGS_FILE "args"
#define PID_FILE "pid"
#define KERNEL_FILE "linux"
#define LOG_FILE "boot.log"
#define NOTIFY_FILE "notify"
#define PTYS 0
Typedefs
typedef struct private_guest_t private_guest_t
Functions
ENUM (guest_state_names, GUEST_STOPPED, GUEST_STOPPING,"STOPPED","STARTING","RUNNING","PAUSED","STOPPING",)
METHOD (guest_t, get_name, char *, private_guest_t *this)
METHOD (guest_t, create_iface, iface_t *, private_guest_t *this, char *name)
METHOD (guest_t, destroy_iface, void, private_guest_t *this, iface_t *iface)
METHOD (guest_t, create_iface_enumerator, enumerator_t *, private_guest_t *this)
METHOD (guest_t, get_state, guest_state_t, private_guest_t *this)
METHOD (guest_t, get_pid, pid_t, private_guest_t *this)
static char * write_arg (char **pos, size_t *left, char *format,...)
METHOD (guest_t, stop, void, private_guest_t *this, idle_function_t idle)
void savepid (private_guest_t *this)
METHOD (guest_t, start, bool, private_guest_t *this, invoke_function_t invoke, void *data, idle_function_t idle)
METHOD (guest_t, add_overlay, bool, private_guest_t *this, char *path)
METHOD (guest_t, del_overlay, bool, private_guest_t *this, char *path)
METHOD (guest_t, pop_overlay, bool, private_guest_t *this)
static int vexec (private_guest_t *this, void(*cb)(void *, char *, size_t), void *data, char *cmd, va_list args)
METHOD (guest_t, exec, int, private_guest_t *this, void(*cb)(void *, char *, size_t), void *data, char *cmd,...)
static void exec_str_cb (exec_str_t *data, char *buf, size_t len)
METHOD (guest_t, exec_str, int, private_guest_t *this, void(*cb)(void *, char *), bool lines, void *data, char *cmd,...)
METHOD (guest_t, sigchild, void, private_guest_t *this)
static bool umount_unionfs (private_guest_t *this)
static bool mount_unionfs (private_guest_t *this)
char * loadargs (private_guest_t *this)
bool saveargs (private_guest_t *this, char *args)
METHOD (guest_t, destroy, void, private_guest_t *this)
static private_guest_t * guest_create_generic (char *parent, char *name, bool create)
static bool make_symlink (private_guest_t *this, char *old, char *new)
guest_t * guest_create (char *parent, char *name, char *kernel, char *master, char *args)
guest_t * guest_load (char *parent, char *name)
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file guest.c.
#define ARGS_FILE "args"
Definition at line 45 of file guest.c.
Referenced by loadargs(), and saveargs().
#define DIFF_DIR "diff"
Definition at line 43 of file guest.c.
Referenced by guest_create(), and mount_unionfs().
#define KERNEL_FILE "linux"
Definition at line 47 of file guest.c.
Referenced by guest_create(), and METHOD().
#define LOG_FILE "boot.log"
Definition at line 48 of file guest.c.
#define MASTER_DIR "master"
Definition at line 42 of file guest.c.
Referenced by guest_create(), and mount_unionfs().
#define NOTIFY_FILE "notify"
Definition at line 49 of file guest.c.
Referenced by METHOD().
#define PERM (S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH)
Definition at line 40 of file guest.c.
Referenced by loadargs(), saveargs(), and savepid().
#define PERME (S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH)
Definition at line 39 of file guest.c.
Referenced by guest_create(), guest_create_generic(), and METHOD().
#define PID_FILE "pid"
Definition at line 46 of file guest.c.
Referenced by METHOD(), and savepid().
#define PTYS 0
Definition at line 50 of file guest.c.
#define UNION_DIR "union"
Definition at line 44 of file guest.c.
Referenced by guest_create(), METHOD(), and mount_unionfs().
Typedef Documentation
typedef struct private_guest_t private_guest_t
Definition at line 52 of file guest.c.
Function Documentation
ENUM (guest_state_names , GUEST_STOPPED , GUEST_STOPPING , "STOPPED" , "STARTING" , "RUNNING" , "PAUSED" , "STOPPING")
static void exec_str_cb (exec_str_t * data, char * buf, size_t len) static
callback that combines chunks to a string. if a callback is given, the string is split at newlines and the callback is called for each line.
Definition at line 359 of file guest.c.
References exec_str_t::buf, exec_str_t::cb, chunk_alloc, exec_str_t::data, chunk_t::len, len, memcpy, memmove, and chunk_t::ptr.
Referenced by METHOD().
 {
     if (!data->buf.ptr)
     {
         data->buf = chunk_alloc(len + 1);
         memcpy(data->buf.ptr, buf, len);
         data->buf.ptr[len] = '\0';
     }
     else
     {
         size_t newlen = strlen(data->buf.ptr) + len + 1;
         if (newlen > data->buf.len)
         {
             data->buf.ptr = realloc(data->buf.ptr, newlen);
             data->buf.len = newlen;
         }
         strncat(data->buf.ptr, buf, len);
     }
     if (data->cb)
     {
         char *nl;
         while ((nl = strchr(data->buf.ptr, '\n')) != NULL)
         {
             *nl++ = '\0';
             data->cb(data->data, data->buf.ptr);
             memmove(data->buf.ptr, nl, strlen(nl) + 1);
         }
     }
 }
guest_t* guest_create (char * parent, char * name, char * kernel, char * master, char * args)
create the guest instance, including required dirs and mounts
Definition at line 618 of file guest.c.
References DBG1, DBG_LIB, destroy(), DIFF_DIR, dir, guest_create_generic(), KERNEL_FILE, make_symlink(), MASTER_DIR, mount_unionfs(), PERME, saveargs(), TRUE, and UNION_DIR.
Referenced by METHOD().
 {
     private_guest_t *this = guest_create_generic(parent, name, TRUE);
     if (this == NULL)
     {
         return NULL;
     }
     if (!make_symlink(this, master, MASTER_DIR) ||
         !make_symlink(this, kernel, KERNEL_FILE))
     {
         DBG1(DBG_LIB, "creating master/kernel symlink failed: %m");
         destroy(this);
         return NULL;
     }
     if (mkdirat(this->dir, UNION_DIR, PERME) != 0 ||
         mkdirat(this->dir, DIFF_DIR, PERME) != 0)
     {
         DBG1(DBG_LIB, "unable to create directories for '%s': %m", name);
         destroy(this);
         return NULL;
     }
     this->args = args;
     if (args && !saveargs(this, args))
     {
         destroy(this);
         return NULL;
     }
     if (!mount_unionfs(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
static private_guest_t* guest_create_generic (char * parent, char * name, bool create) static
generic guest constructor
Definition at line 531 of file guest.c.
References asprintf(), DBG1, DBG_LIB, dir, free(), GUEST_STOPPED, INIT, linked_list_create(), PERME, and strdup.
Referenced by guest_create(), and guest_load().
 {
     char cwd[PATH_MAX];
     private_guest_t *this;
     INIT(this,
         .public = {
             .get_name = _get_name,
             .get_pid = _get_pid,
             .get_state = _get_state,
             .create_iface = _create_iface,
             .destroy_iface = _destroy_iface,
             .create_iface_enumerator = _create_iface_enumerator,
             .start = _start,
             .stop = _stop,
             .add_overlay = _add_overlay,
             .del_overlay = _del_overlay,
             .pop_overlay = _pop_overlay,
             .exec = _exec,
             .exec_str = _exec_str,
             .sigchild = _sigchild,
             .destroy = _destroy,
         }
     );
     if (*parent == '/' || getcwd(cwd, sizeof(cwd)) == NULL)
     {
         if (asprintf(&this->dirname, "%s/%s", parent, name) < 0)
         {
             this->dirname = NULL;
         }
     }
     else
     {
         if (asprintf(&this->dirname, "%s/%s/%s", cwd, parent, name) < 0)
         {
             this->dirname = NULL;
         }
     }
     if (this->dirname == NULL)
     {
         free(this);
         return NULL;
     }
     if (create)
     {
         mkdir(this->dirname, PERME);
     }
     this->dir = open(this->dirname, O_DIRECTORY, PERME);
     if (this->dir < 0)
     {
         DBG1(DBG_LIB, "opening guest directory '%s' failed: %m", this->dirname);
         free(this->dirname);
         free(this);
         return NULL;
     }
     this->state = GUEST_STOPPED;
     this->ifaces = linked_list_create();
     this->name = strdup(name);
     return this;
 }
guest_t* guest_load (char * parent, char * name)
load an already created guest
Definition at line 663 of file guest.c.
References destroy(), FALSE, guest_create_generic(), loadargs(), and mount_unionfs().
Referenced by load_guests().
 {
     private_guest_t *this = guest_create_generic(parent, name, FALSE);
     if (this == NULL)
     {
         return NULL;
     }
     this->args = loadargs(this);
     if (!mount_unionfs(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
char* loadargs (private_guest_t * this)
load args configuration from file
Definition at line 474 of file guest.c.
References ARGS_FILE, dir, PERM, and strdup.
Referenced by guest_load().
 {
     FILE *file;
     char buf[512], *args = NULL;
     file = fdopen(openat(this->dir, ARGS_FILE, O_RDONLY, PERM), "r");
     if (file)
     {
         if (fgets(buf, sizeof(buf), file))
         {
             args = strdup(buf);
         }
         fclose(file);
     }
     return args;
 }
static bool make_symlink (private_guest_t * this, char * old, char * new) static
create a symlink to old called new in our working dir
Definition at line 598 of file guest.c.
References dir, and snprintf.
Referenced by guest_create().
 {
     char cwd[PATH_MAX];
     char buf[PATH_MAX];
     if (*old == '/' || getcwd(cwd, sizeof(cwd)) == NULL)
     {
         snprintf(buf, sizeof(buf), "%s", old);
     }
     else
     {
         snprintf(buf, sizeof(buf), "%s/%s", cwd, old);
     }
     return symlinkat(buf, this->dir, new) == 0;
 }
METHOD (guest_t , get_name , char * , private_guest_t * this)
Definition at line 85 of file guest.c.
References name.
 {
     return this->name;
 }
METHOD (guest_t , create_iface , iface_t * , private_guest_t * this, char * name)
Definition at line 91 of file guest.c.
References DBG1, DBG_LIB, enumerator_t::destroy, enumerator_t::enumerate, iface_t::get_guestif, GUEST_RUNNING, iface_create(), and streq().
 {
     enumerator_t *enumerator;
     iface_t *iface;
     if (this->state != GUEST_RUNNING)
     {
         DBG1(DBG_LIB, "guest '%s' not running, unable to add interface",
              this->name);
         return NULL;
     }
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, (void**)&iface))
     {
         if (streq(name, iface->get_guestif(iface)))
         {
             DBG1(DBG_LIB, "guest '%s' already has an interface '%s'",
                  this->name, name);
             enumerator->destroy(enumerator);
             return NULL;
         }
     }
     enumerator->destroy(enumerator);
     iface = iface_create(name, &this->public, this->mconsole);
     if (iface)
     {
         this->ifaces->insert_last(this->ifaces, iface);
     }
     return iface;
 }
METHOD (guest_t , destroy_iface , void , private_guest_t * this, iface_t * iface)
Definition at line 125 of file guest.c.
References enumerator_t::destroy, iface_t::destroy, and enumerator_t::enumerate.
 {
     enumerator_t *enumerator;
     iface_t *current;
     enumerator = this->ifaces->create_enumerator(this->ifaces);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current == iface)
         {
             this->ifaces->remove_at(this->ifaces, enumerator);
             current->destroy(current);
             break;
         }
     }
     enumerator->destroy(enumerator);
 }
METHOD (guest_t , create_iface_enumerator , enumerator_t * , private_guest_t * this)
Definition at line 144 of file guest.c.
 {
     return this->ifaces->create_enumerator(this->ifaces);
 }
METHOD (guest_t , get_state , guest_state_t , private_guest_t * this)
Definition at line 150 of file guest.c.
 {
     return this->state;
 }
METHOD (guest_t , get_pid , pid_t , private_guest_t * this)
Definition at line 156 of file guest.c.
 {
     return this->pid;
 }
METHOD (guest_t , stop , void , private_guest_t * this, idle_function_t idle)
Definition at line 184 of file guest.c.
References destroy(), dir, GUEST_STOPPED, GUEST_STOPPING, idle(), linked_list_create(), PID_FILE, and usleep().
 {
     if (this->state != GUEST_STOPPED)
     {
         this->state = GUEST_STOPPING;
         this->ifaces->destroy_offset(this->ifaces, offsetof(iface_t, destroy));
         this->ifaces = linked_list_create();
         kill(this->pid, SIGINT);
         while (this->state != GUEST_STOPPED)
         {
             if (idle)
             {
                 idle();
             }
             else
             {
                 usleep(50000);
             }
         }
         unlinkat(this->dir, PID_FILE, 0);
         this->pid = 0;
     }
 }
METHOD (guest_t , start , bool , private_guest_t * this, invoke_function_t invoke, void * data, idle_function_t idle)
Definition at line 225 of file guest.c.
References DBG1, DBG_LIB, FALSE, GUEST_RUNNING, GUEST_STARTING, guest_state_names, GUEST_STOPPED, invoke(), KERNEL_FILE, mconsole_create(), memset, name, notify(), NOTIFY_FILE, savepid(), TRUE, UNION_DIR, and write_arg().
 {
     char buf[2048];
     char *notify;
     char *pos = buf;
     char *args[32];
     int i = 0;
     size_t left = sizeof(buf);
     memset(args, 0, sizeof(args));
     if (this->state != GUEST_STOPPED)
     {
         DBG1(DBG_LIB, "unable to start guest in state %N", guest_state_names,
              this->state);
         return FALSE;
     }
     this->state = GUEST_STARTING;
     notify = write_arg(&pos, &left, "%s/%s", this->dirname, NOTIFY_FILE);
     args[i++] = write_arg(&pos, &left, "nice");
     args[i++] = write_arg(&pos, &left, "%s/%s", this->dirname, KERNEL_FILE);
     args[i++] = write_arg(&pos, &left, "root=/dev/root");
     args[i++] = write_arg(&pos, &left, "rootfstype=hostfs");
     args[i++] = write_arg(&pos, &left, "rootflags=%s/%s", this->dirname, UNION_DIR);
     args[i++] = write_arg(&pos, &left, "uml_dir=%s", this->dirname);
     args[i++] = write_arg(&pos, &left, "umid=%s", this->name);
     args[i++] = write_arg(&pos, &left, "mconsole=notify:%s", notify);
     args[i++] = write_arg(&pos, &left, "con=null");
     if (this->args)
     {
         args[i++] = this->args;
     }
     this->pid = invoke(data, &this->public, args, i);
     if (!this->pid)
     {
         this->state = GUEST_STOPPED;
         return FALSE;
     }
     savepid(this);
     /* open mconsole */
     this->mconsole = mconsole_create(notify, idle);
     if (this->mconsole == NULL)
     {
         DBG1(DBG_LIB, "opening mconsole at '%s' failed, stopping guest", buf);
         stop(this, NULL);
         return FALSE;
     }
     this->state = GUEST_RUNNING;
     return TRUE;
 }
METHOD (guest_t , add_overlay , bool , private_guest_t * this, char * path)
Definition at line 283 of file guest.c.
References DBG1, DBG_LIB, FALSE, mkdir_p(), name, and PERME.
 {
     if (path == NULL)
     {
         return FALSE;
     }
     if (access(path, F_OK) != 0)
     {
         if (!mkdir_p(path, PERME))
         {
             DBG1(DBG_LIB, "creating overlay for guest '%s' failed: %m",
                  this->name);
             return FALSE;
         }
     }
     return this->cowfs->add_overlay(this->cowfs, path);
 }
METHOD (guest_t , del_overlay , bool , private_guest_t * this, char * path)
Definition at line 304 of file guest.c.
 {
     return this->cowfs->del_overlay(this->cowfs, path);
 }
METHOD (guest_t , pop_overlay , bool , private_guest_t * this)
Definition at line 310 of file guest.c.
 {
     return this->cowfs->pop_overlay(this->cowfs);
 }
METHOD (guest_t , exec , int , private_guest_t * this, void(*)(void *, char *, size_t) cb, void * data, char * cmd, ...)
Definition at line 337 of file guest.c.
References cb(), res, and vexec().
 {
     int res;
     va_list args;
     va_start(args, cmd);
     res = vexec(this, cb, data, cmd, args);
     va_end(args);
     return res;
 }
METHOD (guest_t , exec_str , int , private_guest_t * this, void(*)(void *, char *) cb, bool lines, void * data, char * cmd, ...)
Definition at line 390 of file guest.c.
References exec_str_t::buf, cb(), exec_str_t::cb, chunk_empty, chunk_free(), data, exec_str_t::data, exec_str_cb(), chunk_t::ptr, res, and vexec().
 {
     int res;
     va_list args;
     va_start(args, cmd);
     if (cb)
     {
         exec_str_t exec = { chunk_empty, NULL, NULL };
         if (lines)
         {
             exec.cb = cb;
             exec.data = data;
         }
         res = vexec(this, (void(*)(void*,char*,size_t))exec_str_cb, &exec, cmd, args);
         if (exec.buf.ptr)
         {
             if (!lines || strlen(exec.buf.ptr) > 0)
             {
                 /* return the complete string or the remaining stuff in the
                  * buffer (i.e. when there was no newline at the end) */
                 cb(data, exec.buf.ptr);
             }
             chunk_free(&exec.buf);
         }
     }
     else
     {
         res = vexec(this, NULL, NULL, cmd, args);
     }
     va_end(args);
     return res;
 }
METHOD (guest_t , sigchild , void , private_guest_t * this)
Definition at line 425 of file guest.c.
References DESTROY_IF, and GUEST_STOPPED.
 {
     DESTROY_IF(this->mconsole);
     this->mconsole = NULL;
     this->state = GUEST_STOPPED;
 }
METHOD (guest_t , destroy , void , private_guest_t * this)
Definition at line 512 of file guest.c.
References close, dir, free(), name, and umount_unionfs().
 {
     stop(this, NULL);
     umount_unionfs(this);
     if (this->dir > 0)
     {
         close(this->dir);
     }
     this->ifaces->destroy(this->ifaces);
     free(this->dirname);
     free(this->args);
     free(this->name);
     free(this);
 }
static bool mount_unionfs (private_guest_t * this) static
mount the union filesystem
Definition at line 450 of file guest.c.
References cowfs_create(), DIFF_DIR, FALSE, MASTER_DIR, snprintf, TRUE, and UNION_DIR.
Referenced by guest_create(), and guest_load().
 {
     char master[PATH_MAX];
     char diff[PATH_MAX];
     char mount[PATH_MAX];
     if (this->cowfs == NULL)
     {
         snprintf(master, sizeof(master), "%s/%s", this->dirname, MASTER_DIR);
         snprintf(diff, sizeof(diff), "%s/%s", this->dirname, DIFF_DIR);
         snprintf(mount, sizeof(mount), "%s/%s", this->dirname, UNION_DIR);
         this->cowfs = cowfs_create(master, diff, mount);
         if (this->cowfs)
         {
             return TRUE;
         }
     }
     return FALSE;
 }
bool saveargs (private_guest_t * this, char * args)
save args configuration to file
Definition at line 494 of file guest.c.
References ARGS_FILE, dir, FALSE, fprintf, PERM, and TRUE.
Referenced by guest_create().
 {
     FILE *file;
     bool retval = FALSE;
     file = fdopen(openat(this->dir, ARGS_FILE, O_RDWR | O_CREAT | O_TRUNC,
                          PERM), "w");
     if (file)
     {
         if (fprintf(file, "%s", args) > 0)
         {
             retval = TRUE;
         }
         fclose(file);
     }
     return retval;
 }
void savepid (private_guest_t * this)
save pid in file
Definition at line 212 of file guest.c.
References dir, fprintf, PERM, and PID_FILE.
Referenced by METHOD().
 {
     FILE *file;
     file = fdopen(openat(this->dir, PID_FILE, O_RDWR | O_CREAT | O_TRUNC,
                          PERM), "w");
     if (file)
     {
         fprintf(file, "%d", this->pid);
         fclose(file);
     }
 }
static bool umount_unionfs (private_guest_t * this) static
umount the union filesystem
Definition at line 436 of file guest.c.
References FALSE, and TRUE.
Referenced by METHOD().
 {
     if (this->cowfs)
     {
         this->cowfs->destroy(this->cowfs);
         this->cowfs = NULL;
         return TRUE;
     }
     return FALSE;
 }
static int vexec (private_guest_t * this, void(*)(void *, char *, size_t) cb, void * data, char * cmd, va_list args) static
Variadic version of the exec function
Definition at line 319 of file guest.c.
References cb(), len, and vsnprintf.
Referenced by METHOD().
 {
     char buf[1024];
     size_t len;
     if (this->mconsole)
     {
         len = vsnprintf(buf, sizeof(buf), cmd, args);
         if (len > 0 && len < sizeof(buf))
         {
             return this->mconsole->exec(this->mconsole, cb, data, buf);
         }
     }
     return -1;
 }
static char* write_arg (char ** pos, size_t * left, char * format, ...) static
write format string to a buffer, and advance buffer position
Definition at line 165 of file guest.c.
References len, res, and vsnprintf.
Referenced by METHOD().
 {
     size_t len;
     char *res = NULL;
     va_list args;
     va_start(args, format);
     len = vsnprintf(*pos, *left, format, args);
     va_end(args);
     if (len < *left)
     {
         res = *pos;
         len++;
         *pos += len + 1;
         *left -= len + 1;
     }
     return res;
 }