strongSwan: imc_imv_msg.c File Reference
imc_imv_msg.c File Reference
#include "imc_imv_msg.h"
#include <tnc/tnccs/tnccs.h>
#include <utils/lexparser.h>
#include <utils/debug.h>
Classes
struct private_imc_imv_msg_t
Macros
#define BYTES_PER_LINE 57
Typedefs
typedef struct
private_imc_imv_msg_t private_imc_imv_msg_t
Functions
static chunk_t encode_base64 (chunk_t data)
static chunk_t decode_base64 (chunk_t data)
METHOD (tnccs_msg_t, get_type, tnccs_msg_type_t, private_imc_imv_msg_t *this)
METHOD (tnccs_msg_t, get_node, xmlNodePtr, private_imc_imv_msg_t *this)
METHOD (tnccs_msg_t, destroy, void, private_imc_imv_msg_t *this)
METHOD (imc_imv_msg_t, get_msg_type, TNC_MessageType, private_imc_imv_msg_t *this)
METHOD (imc_imv_msg_t, get_msg_body, chunk_t, private_imc_imv_msg_t *this)
tnccs_msg_t * imc_imv_msg_create_from_node (xmlNodePtr node, linked_list_t *errors)
tnccs_msg_t * imc_imv_msg_create (TNC_MessageType msg_type, chunk_t msg_body)
Macro Definition Documentation
#define BYTES_PER_LINE 57
Definition at line 25 of file imc_imv_msg.c.
Referenced by encode_base64().
Typedef Documentation
typedef struct private_imc_imv_msg_t private_imc_imv_msg_t
Definition at line 23 of file imc_imv_msg.c.
Function Documentation
static chunk_t decode_base64 (chunk_t data) static
Decodes message data from multiple base64-encoded lines
Definition at line 104 of file imc_imv_msg.c.
References chunk_alloc, chunk_from_base64(), fetchline(), chunk_t::len, and chunk_t::ptr.
Referenced by imc_imv_msg_create_from_node().
 {
     chunk_t decoding, data_line, b64_line;
     u_char *pos;
     /* compute and allocate maximum size of decoded message data */
     decoding = chunk_alloc(3 * ((data.len + 3) / 4));
     pos = decoding.ptr;
     decoding.len = 0;
     while (fetchline(&data, &b64_line))
     {
         data_line = chunk_from_base64(b64_line, pos);
         pos += data_line.len;
         decoding.len += data_line.len;
     }
     return decoding;
 }
static chunk_t encode_base64 (chunk_t data) static
Encodes message data into multiple base64-encoded lines
Definition at line 62 of file imc_imv_msg.c.
References BYTES_PER_LINE, chunk_alloc, chunk_create(), chunk_to_base64(), encoding, chunk_t::len, min, and chunk_t::ptr.
Referenced by imc_imv_msg_create().
 {
     chunk_t encoding;
     u_char *pos;
     size_t b64_chars, b64_lines;
     /* handle empty message data object */
     if (data.len == 0)
     {
         encoding = chunk_alloc(1);
         *encoding.ptr = '\0';
         return encoding;
     }
     /* compute and allocate maximum size of base64 object */
     b64_chars = 4 * ((data.len + 2) / 3);
     b64_lines = (data.len + BYTES_PER_LINE - 1) / BYTES_PER_LINE;
     encoding = chunk_alloc(b64_chars + b64_lines);
     pos = encoding.ptr;
     /* encode lines */
     while (b64_lines--)
     {
         chunk_t data_line, b64_line;
         data_line = chunk_create(data.ptr, min(data.len, BYTES_PER_LINE));
         data.ptr += data_line.len;
         data.len -= data_line.len;
         b64_line = chunk_to_base64(data_line, pos);
         pos += b64_line.len;
         *pos = '\n';
         pos++;
     }
     /* terminate last line with NULL character instead of newline */
     *(pos-1) = '\0';
     return encoding;
 }
METHOD (tnccs_msg_t , get_type , tnccs_msg_type_t , private_imc_imv_msg_t * this)
Definition at line 124 of file imc_imv_msg.c.
References type.
 {
     return this->type;
 }
METHOD (tnccs_msg_t , get_node , xmlNodePtr , private_imc_imv_msg_t * this)
Definition at line 130 of file imc_imv_msg.c.
 {
     return this->node;
 }
METHOD (tnccs_msg_t , destroy , void , private_imc_imv_msg_t * this)
Definition at line 136 of file imc_imv_msg.c.
References free().
 {
     free(this->msg_body.ptr);
     free(this);
 }
METHOD (imc_imv_msg_t , get_msg_type , TNC_MessageType , private_imc_imv_msg_t * this)
Definition at line 143 of file imc_imv_msg.c.
 {
     return this->msg_type;
 }
METHOD (imc_imv_msg_t , get_msg_body , chunk_t , private_imc_imv_msg_t * this)
Definition at line 149 of file imc_imv_msg.c.
 {
     return this->msg_body;
 }