strongSwan: mode_config.c File Reference
mode_config.c File Reference
#include "mode_config.h"
#include <daemon.h>
#include <encoding/payloads/cp_payload.h>
Classes
struct private_mode_config_t
struct entry_t
Typedefs
typedef struct
private_mode_config_t private_mode_config_t
Functions
static configuration_attribute_t * build_vip (host_t *vip)
static void handle_attribute (private_mode_config_t *this, configuration_attribute_t *ca)
static void process_attribute (private_mode_config_t *this, configuration_attribute_t *ca)
static bool accept_push (private_mode_config_t *this)
static void process_payloads (private_mode_config_t *this, message_t *message)
static void add_attribute (private_mode_config_t *this, cp_payload_t *cp, configuration_attribute_type_t type, chunk_t data, attribute_handler_t *handler)
static status_t build_request (private_mode_config_t *this, message_t *message)
static status_t build_set (private_mode_config_t *this, message_t *message)
METHOD (task_t, build_i, status_t, private_mode_config_t *this, message_t *message)
static void install_vips (private_mode_config_t *this)
METHOD (task_t, process_r, status_t, private_mode_config_t *this, message_t *message)
static host_t * assign_migrated_vip (linked_list_t *migrated, host_t *requested)
static status_t build_reply (private_mode_config_t *this, message_t *message)
static status_t build_ack (private_mode_config_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_mode_config_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_mode_config_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_mode_config_t *this)
METHOD (task_t, migrate, void, private_mode_config_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_mode_config_t *this)
mode_config_t * mode_config_create (ike_sa_t *ike_sa, bool initiator, bool pull)
Typedef Documentation
typedef struct private_mode_config_t private_mode_config_t
Definition at line 21 of file mode_config.c.
Function Documentation
static bool accept_push (private_mode_config_t * this) static
Check if config allows push mode when acting as task responder
Definition at line 194 of file mode_config.c.
References peer_cfg_t::create_virtual_ip_enumerator, enumerator_t::destroy, enumerator_t::enumerate, host, peer_cfg_t::use_pull_mode, and vip.
Referenced by process_payloads().
 {
     enumerator_t *enumerator;
     peer_cfg_t *config;
     bool vip;
     host_t *host;
     config = this->ike_sa->get_peer_cfg(this->ike_sa);
     enumerator = config->create_virtual_ip_enumerator(config);
     vip = enumerator->enumerate(enumerator, &host);
     enumerator->destroy(enumerator);
     return vip && !config->use_pull_mode(config);
 }
static void add_attribute (private_mode_config_t * this, cp_payload_t * cp, configuration_attribute_type_t type, chunk_t data, attribute_handler_t * handler) static
Add an attribute to a configuration payload, and store it in task
Definition at line 264 of file mode_config.c.
References cp_payload_t::add_attribute, attributes, configuration_attribute_create_chunk(), INIT, and PLV1_CONFIGURATION_ATTRIBUTE.
Referenced by build_request(), build_set(), METHOD(), and parse_attributes().
 {
     entry_t *entry;
     cp->add_attribute(cp,
             configuration_attribute_create_chunk(PLV1_CONFIGURATION_ATTRIBUTE,
                                                  type, data));
     INIT(entry,
         .type = type,
         .handler = handler,
     );
     this->attributes->insert_last(this->attributes, entry);
 }
static host_t* assign_migrated_vip (linked_list_t * migrated, host_t * requested) static
Assign a migrated virtual IP
Definition at line 477 of file mode_config.c.
References linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, host_t::get_family, host_t::is_anyaddr, linked_list_t::remove_at, and vip.
Referenced by build_reply().
 {
     enumerator_t *enumerator;
     host_t *found = NULL, *vip;
     enumerator = migrated->create_enumerator(migrated);
     while (enumerator->enumerate(enumerator, &vip))
     {
         if (vip->ip_equals(vip, requested) ||
            (requested->is_anyaddr(requested) &&
             requested->get_family(requested) == vip->get_family(vip)))
         {
             migrated->remove_at(migrated, enumerator);
             found = vip;
             break;
         }
     }
     enumerator->destroy(enumerator);
     return found;
 }
static status_t build_ack (private_mode_config_t * this, message_t * message) static
Build CFG_ACK for a received CFG_SET
Definition at line 586 of file mode_config.c.
References cp_payload_t::add_attribute, message_t::add_payload, attributes, CFG_ACK, chunk_empty, configuration_attribute_create_chunk(), cp, cp_payload_create_type(), enumerator_t::destroy, enumerator_t::enumerate, host_t::get_family, host, identifier, INTERNAL_IP4_ADDRESS, INTERNAL_IP6_ADDRESS, PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, cp_payload_t::set_identifier, SUCCESS, type, and entry_t::type.
Referenced by METHOD().
 {
     cp_payload_t *cp;
     enumerator_t *enumerator;
     host_t *host;
     configuration_attribute_type_t type;
     entry_t *entry;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_ACK);
     /* return empty attributes for installed IPs */
     enumerator = this->vips->create_enumerator(this->vips);
     while (enumerator->enumerate(enumerator, &host))
     {
         type = INTERNAL_IP6_ADDRESS;
         if (host->get_family(host) == AF_INET6)
         {
             type = INTERNAL_IP6_ADDRESS;
         }
         else
         {
             type = INTERNAL_IP4_ADDRESS;
         }
         cp->add_attribute(cp, configuration_attribute_create_chunk(
                                 PLV1_CONFIGURATION_ATTRIBUTE, type, chunk_empty));
     }
     enumerator->destroy(enumerator);
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &entry))
     {
         cp->add_attribute(cp,
             configuration_attribute_create_chunk(PLV1_CONFIGURATION_ATTRIBUTE,
                                                  entry->type, chunk_empty));
     }
     enumerator->destroy(enumerator);
     cp->set_identifier(cp, this->identifier);
     message->add_payload(message, (payload_t*)cp);
     return SUCCESS;
 }
static status_t build_reply (private_mode_config_t * this, message_t * message) static
Build CFG_REPLY message after receiving CFG_REQUEST
Definition at line 501 of file mode_config.c.
References attribute_manager_t::acquire_address, cp_payload_t::add_attribute, message_t::add_payload, assign_migrated_vip(), bus_t::assign_vips, daemon_t::attributes, build_vip(), daemon_t::bus, CFG_REPLY, charon, linked_list_t::clone_offset, configuration_attribute_create_chunk(), cp, cp_payload_create_type(), peer_cfg_t::create_pool_enumerator, attribute_manager_t::create_responder_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, linked_list_t::destroy, destroy(), enumerator_t::enumerate, FALSE, found, id, identifier, linked_list_create(), linked_list_create_from_enumerator(), PLV1_CONFIGURATION, PLV1_CONFIGURATION_ATTRIBUTE, attribute_manager_t::release_address, cp_payload_t::set_identifier, SUCCESS, TRUE, type, and value.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     configuration_attribute_type_t type;
     chunk_t value;
     cp_payload_t *cp;
     peer_cfg_t *config;
     identification_t *id;
     linked_list_t *vips, *pools, *migrated;
     host_t *requested, *found;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REPLY);
     id = this->ike_sa->get_other_eap_id(this->ike_sa);
     config = this->ike_sa->get_peer_cfg(this->ike_sa);
     pools = linked_list_create_from_enumerator(
                                     config->create_pool_enumerator(config));
     /* if we migrated virtual IPs during reauthentication, reassign them */
     vips = linked_list_create_from_enumerator(
                         this->ike_sa->create_virtual_ip_enumerator(this->ike_sa,
                                                                    FALSE));
     migrated = vips->clone_offset(vips, offsetof(host_t, clone));
     vips->destroy(vips);
     this->ike_sa->clear_virtual_ips(this->ike_sa, FALSE);
     vips = linked_list_create();
     enumerator = this->vips->create_enumerator(this->vips);
     while (enumerator->enumerate(enumerator, &requested))
     {
         DBG1(DBG_IKE, "peer requested virtual IP %H", requested);
         found = assign_migrated_vip(migrated, requested);
         if (!found)
         {
             found = charon->attributes->acquire_address(charon->attributes,
                                             pools, this->ike_sa, requested);
         }
         if (found)
         {
             DBG1(DBG_IKE, "assigning virtual IP %H to peer '%Y'", found, id);
             this->ike_sa->add_virtual_ip(this->ike_sa, FALSE, found);
             cp->add_attribute(cp, build_vip(found));
             vips->insert_last(vips, found);
         }
         else
         {
             DBG1(DBG_IKE, "no virtual IP found for %H requested by '%Y'",
                  requested, id);
         }
     }
     enumerator->destroy(enumerator);
     charon->bus->assign_vips(charon->bus, this->ike_sa, TRUE);
     /* query registered providers for additional attributes to include */
     enumerator = charon->attributes->create_responder_enumerator(
                                 charon->attributes, pools, this->ike_sa, vips);
     while (enumerator->enumerate(enumerator, &type, &value))
     {
         cp->add_attribute(cp,
             configuration_attribute_create_chunk(PLV1_CONFIGURATION_ATTRIBUTE,
                                                  type, value));
     }
     enumerator->destroy(enumerator);
     /* if a client did not re-request all adresses, release them */
     enumerator = migrated->create_enumerator(migrated);
     while (enumerator->enumerate(enumerator, &found))
     {
         charon->attributes->release_address(charon->attributes,
                                             pools, found, this->ike_sa);
     }
     enumerator->destroy(enumerator);
     migrated->destroy_offset(migrated, offsetof(host_t, destroy));
     vips->destroy_offset(vips, offsetof(host_t, destroy));
     pools->destroy(pools);
     cp->set_identifier(cp, this->identifier);
     message->add_payload(message, (payload_t*)cp);
     return SUCCESS;
 }
static status_t build_request (private_mode_config_t * this, message_t * message) static
Build a CFG_REQUEST as initiator
Definition at line 283 of file mode_config.c.
References cp_payload_t::add_attribute, add_attribute(), message_t::add_payload, daemon_t::attributes, build_vip(), CFG_REQUEST, charon, cp, cp_payload_create_type(), linked_list_t::create_enumerator, attribute_manager_t::create_initiator_enumerator, peer_cfg_t::create_virtual_ip_enumerator, data, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::get_count, host, linked_list_t::insert_last, linked_list_create(), NEED_MORE, PLV1_CONFIGURATION, TRUE, and type.
Referenced by METHOD().
 {
     cp_payload_t *cp;
     enumerator_t *enumerator;
     attribute_handler_t *handler;
     peer_cfg_t *config;
     configuration_attribute_type_t type;
     chunk_t data;
     linked_list_t *vips;
     host_t *host;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_REQUEST);
     vips = linked_list_create();
     /* reuse virtual IP if we already have one */
     enumerator = this->ike_sa->create_virtual_ip_enumerator(this->ike_sa, TRUE);
     while (enumerator->enumerate(enumerator, &host))
     {
         vips->insert_last(vips, host);
     }
     enumerator->destroy(enumerator);
     if (vips->get_count(vips) == 0)
     {
         config = this->ike_sa->get_peer_cfg(this->ike_sa);
         enumerator = config->create_virtual_ip_enumerator(config);
         while (enumerator->enumerate(enumerator, &host))
         {
             vips->insert_last(vips, host);
         }
         enumerator->destroy(enumerator);
     }
     if (vips->get_count(vips))
     {
         enumerator = vips->create_enumerator(vips);
         while (enumerator->enumerate(enumerator, &host))
         {
             cp->add_attribute(cp, build_vip(host));
         }
         enumerator->destroy(enumerator);
     }
     enumerator = charon->attributes->create_initiator_enumerator(
                                         charon->attributes, this->ike_sa, vips);
     while (enumerator->enumerate(enumerator, &handler, &type, &data))
     {
         add_attribute(this, cp, type, data, handler);
     }
     enumerator->destroy(enumerator);
     vips->destroy(vips);
     message->add_payload(message, (payload_t*)cp);
     return NEED_MORE;
 }
static status_t build_set (private_mode_config_t * this, message_t * message) static
Build a CFG_SET as initiator
Definition at line 345 of file mode_config.c.
References attribute_manager_t::acquire_address, cp_payload_t::add_attribute, add_attribute(), message_t::add_payload, bus_t::assign_vips, daemon_t::attributes, build_vip(), daemon_t::bus, CFG_SET, charon, linked_list_t::clone_offset, cp, cp_payload_create_type(), peer_cfg_t::create_pool_enumerator, attribute_manager_t::create_responder_enumerator, DBG1, DBG_IKE, enumerator_t::destroy, host_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, FALSE, found, host_create_any(), id, linked_list_create_from_enumerator(), linked_list_create_with_items(), name, PLV1_CONFIGURATION, SUCCESS, TRUE, type, and value.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     configuration_attribute_type_t type;
     chunk_t value;
     cp_payload_t *cp;
     peer_cfg_t *config;
     identification_t *id;
     linked_list_t *pools, *migrated, *vips;
     host_t *any4, *any6, *found;
     char *name;
     cp = cp_payload_create_type(PLV1_CONFIGURATION, CFG_SET);
     id = this->ike_sa->get_other_eap_id(this->ike_sa);
     config = this->ike_sa->get_peer_cfg(this->ike_sa);
     /* if we migrated virtual IPs during reauthentication, reassign them */
     migrated = linked_list_create_from_enumerator(
                         this->ike_sa->create_virtual_ip_enumerator(this->ike_sa,
                                                                    FALSE));
     vips = migrated->clone_offset(migrated, offsetof(host_t, clone));
     migrated->destroy(migrated);
     this->ike_sa->clear_virtual_ips(this->ike_sa, FALSE);
     /* in push mode, we ask each configured pool for an address */
     if (!vips->get_count(vips))
     {
         any4 = host_create_any(AF_INET);
         any6 = host_create_any(AF_INET6);
         enumerator = config->create_pool_enumerator(config);
         while (enumerator->enumerate(enumerator, &name))
         {
             pools = linked_list_create_with_items(name, NULL);
             /* try IPv4, then IPv6 */
             found = charon->attributes->acquire_address(charon->attributes,
                                                     pools, this->ike_sa, any4);
             if (!found)
             {
                 found = charon->attributes->acquire_address(charon->attributes,
                                                     pools, this->ike_sa, any6);
             }
             pools->destroy(pools);
             if (found)
             {
                 vips->insert_last(vips, found);
             }
         }
         enumerator->destroy(enumerator);
         any4->destroy(any4);
         any6->destroy(any6);
     }
     enumerator = vips->create_enumerator(vips);
     while (enumerator->enumerate(enumerator, &found))
     {
         DBG1(DBG_IKE, "assigning virtual IP %H to peer '%Y'", found, id);
         this->ike_sa->add_virtual_ip(this->ike_sa, FALSE, found);
         cp->add_attribute(cp, build_vip(found));
         this->vips->insert_last(this->vips, found);
         vips->remove_at(vips, enumerator);
     }
     enumerator->destroy(enumerator);
     vips->destroy(vips);
     charon->bus->assign_vips(charon->bus, this->ike_sa, TRUE);
     /* query registered providers for additional attributes to include */
     pools = linked_list_create_from_enumerator(
                                     config->create_pool_enumerator(config));
     enumerator = charon->attributes->create_responder_enumerator(
                         charon->attributes, pools, this->ike_sa, this->vips);
     while (enumerator->enumerate(enumerator, &type, &value))
     {
         add_attribute(this, cp, type, value, NULL);
     }
     enumerator->destroy(enumerator);
     pools->destroy(pools);
     message->add_payload(message, (payload_t*)cp);
     return SUCCESS;
 }
static configuration_attribute_t* build_vip (host_t * vip) static
build INTERNAL_IPV4/6_ADDRESS attribute from virtual ip
Definition at line 77 of file mode_config.c.
References chunk_alloca, chunk_cata, chunk_empty, configuration_attribute_create_chunk(), host_t::get_address, host_t::get_family, INTERNAL_IP4_ADDRESS, INTERNAL_IP6_ADDRESS, host_t::is_anyaddr, PLV1_CONFIGURATION_ATTRIBUTE, prefix, chunk_t::ptr, and type.
Referenced by build_reply(), build_request(), and build_set().
 {
     configuration_attribute_type_t type;
     chunk_t chunk, prefix;
     if (vip->get_family(vip) == AF_INET)
     {
         type = INTERNAL_IP4_ADDRESS;
         if (vip->is_anyaddr(vip))
         {
             chunk = chunk_empty;
         }
         else
         {
             chunk = vip->get_address(vip);
         }
     }
     else
     {
         type = INTERNAL_IP6_ADDRESS;
         if (vip->is_anyaddr(vip))
         {
             chunk = chunk_empty;
         }
         else
         {
             prefix = chunk_alloca(1);
             *prefix.ptr = 64;
             chunk = vip->get_address(vip);
             chunk = chunk_cata("cc", chunk, prefix);
         }
     }
     return configuration_attribute_create_chunk(PLV1_CONFIGURATION_ATTRIBUTE,
                                                 type, chunk);
 }
static void handle_attribute (private_mode_config_t * this, configuration_attribute_t * ca) static
Handle a received attribute as initiator
Definition at line 116 of file mode_config.c.
References attributes, daemon_t::attributes, charon, enumerator_t::destroy, enumerator_t::enumerate, free(), configuration_attribute_t::get_chunk, configuration_attribute_t::get_type, attribute_manager_t::handle, entry_t::handler, and entry_t::type.
Referenced by process_attribute().
 {
     attribute_handler_t *handler = NULL;
     enumerator_t *enumerator;
     entry_t *entry;
     /* find the handler which requested this attribute */
     enumerator = this->attributes->create_enumerator(this->attributes);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->type == ca->get_type(ca))
         {
             handler = entry->handler;
             this->attributes->remove_at(this->attributes, enumerator);
             free(entry);
             break;
         }
     }
     enumerator->destroy(enumerator);
     /* and pass it to the handle function */
     handler = charon->attributes->handle(charon->attributes,
                     this->ike_sa, handler, ca->get_type(ca), ca->get_chunk(ca));
     this->ike_sa->add_configuration_attribute(this->ike_sa,
                             handler, ca->get_type(ca), ca->get_chunk(ca));
 }
static void install_vips (private_mode_config_t * this) static
Store received virtual IPs to the IKE_SA, install them
Definition at line 442 of file mode_config.c.
References daemon_t::bus, charon, enumerator_t::destroy, enumerator_t::enumerate, bus_t::handle_vips, host, host_t::is_anyaddr, and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     host_t *host;
     this->ike_sa->clear_virtual_ips(this->ike_sa, TRUE);
     enumerator = this->vips->create_enumerator(this->vips);
     while (enumerator->enumerate(enumerator, &host))
     {
         if (!host->is_anyaddr(host))
         {
             this->ike_sa->add_virtual_ip(this->ike_sa, TRUE, host);
         }
     }
     enumerator->destroy(enumerator);
     charon->bus->handle_vips(charon->bus, this->ike_sa, TRUE);
 }
METHOD (task_t , build_i , status_t , private_mode_config_t * this, message_t * message)
Definition at line 429 of file mode_config.c.
References build_request(), and build_set().
 {
     if (this->pull)
     {
         return build_request(this, message);
     }
     return build_set(this, message);
 }
METHOD (task_t , process_r , status_t , private_mode_config_t * this, message_t * message)
Definition at line 462 of file mode_config.c.
References install_vips(), NEED_MORE, and process_payloads().
 {
     process_payloads(this, message);
     if (!this->pull)
     {
         install_vips(this);
     }
     return NEED_MORE;
 }
METHOD (task_t , build_r , status_t , private_mode_config_t * this, message_t * message)
Definition at line 630 of file mode_config.c.
References build_ack(), and build_reply().
 {
     if (this->pull)
     {
         return build_reply(this, message);
     }
     return build_ack(this, message);
 }
METHOD (task_t , process_i , status_t , private_mode_config_t * this, message_t * message)
Definition at line 640 of file mode_config.c.
References install_vips(), process_payloads(), and SUCCESS.
 {
     process_payloads(this, message);
     if (this->pull)
     {
         install_vips(this);
     }
     return SUCCESS;
 }
METHOD (task_t , get_type , task_type_t , private_mode_config_t * this)
Definition at line 652 of file mode_config.c.
References TASK_MODE_CONFIG.
 {
     return TASK_MODE_CONFIG;
 }
METHOD (task_t , migrate , void , private_mode_config_t * this, ike_sa_t * ike_sa)
Definition at line 658 of file mode_config.c.
References attributes, destroy(), free(), and linked_list_create().
 {
     this->ike_sa = ike_sa;
     this->vips->destroy_offset(this->vips, offsetof(host_t, destroy));
     this->vips = linked_list_create();
     this->attributes->destroy_function(this->attributes, free);
     this->attributes = linked_list_create();
 }
METHOD (task_t , destroy , void , private_mode_config_t * this)
Definition at line 668 of file mode_config.c.
References attributes, destroy(), and free().
 {
     this->vips->destroy_offset(this->vips, offsetof(host_t, destroy));
     this->attributes->destroy_function(this->attributes, free);
     free(this);
 }
static void process_attribute (private_mode_config_t * this, configuration_attribute_t * ca) static
process a single configuration attribute
Definition at line 147 of file mode_config.c.
References addr, family, configuration_attribute_t::get_chunk, configuration_attribute_t::get_type, handle_attribute(), host_create_any(), host_create_from_chunk(), initiator, INTERNAL_IP4_ADDRESS, INTERNAL_IP6_ADDRESS, ip, and chunk_t::len.
Referenced by process_payloads().
 {
     host_t *ip;
     chunk_t addr;
     int family = AF_INET6;
     switch (ca->get_type(ca))
     {
         case INTERNAL_IP4_ADDRESS:
             family = AF_INET;
             /* fall */
         case INTERNAL_IP6_ADDRESS:
         {
             addr = ca->get_chunk(ca);
             if (addr.len == 0)
             {
                 ip = host_create_any(family);
             }
             else
             {
                 /* skip prefix byte in IPv6 payload*/
                 if (family == AF_INET6)
                 {
                     addr.len--;
                 }
                 ip = host_create_from_chunk(family, addr, 0);
             }
             if (ip)
             {
                 this->vips->insert_last(this->vips, ip);
             }
             break;
         }
         default:
         {
             if (this->initiator == this->pull)
             {
                 handle_attribute(this, ca);
             }
         }
     }
 }
static void process_payloads (private_mode_config_t * this, message_t * message) static
Scan for configuration payloads and attributes
Definition at line 212 of file mode_config.c.
References accept_push(), attributes, CFG_ACK, CFG_REPLY, CFG_REQUEST, CFG_SET, config_type_names, configuration_attribute_type_names, cp, cp_payload_t::create_attribute_enumerator, message_t::create_payload_enumerator, DBG1, DBG2, DBG_IKE, enumerator_t::destroy, enumerator_t::enumerate, FALSE, cp_payload_t::get_identifier, configuration_attribute_t::get_type, cp_payload_t::get_type, payload_t::get_type, identifier, initiator, PLV1_CONFIGURATION, and process_attribute().
Referenced by METHOD().
 {
     enumerator_t *enumerator, *attributes;
     payload_t *payload;
     enumerator = message->create_payload_enumerator(message);
     while (enumerator->enumerate(enumerator, &payload))
     {
         if (payload->get_type(payload) == PLV1_CONFIGURATION)
         {
             cp_payload_t *cp = (cp_payload_t*)payload;
             configuration_attribute_t *ca;
             switch (cp->get_type(cp))
             {
                 case CFG_SET:
                     /* when acting as a responder, we detect the mode using
                      * the type of configuration payload. But we should double
                      * check the peer is allowed to use push mode on us. */
                     if (!this->initiator && accept_push(this))
                     {
                         this->pull = FALSE;
                     }
                     /* FALL */
                 case CFG_REQUEST:
                     this->identifier = cp->get_identifier(cp);
                     /* FALL */
                 case CFG_REPLY:
                     attributes = cp->create_attribute_enumerator(cp);
                     while (attributes->enumerate(attributes, &ca))
                     {
                         DBG2(DBG_IKE, "processing %N attribute",
                              configuration_attribute_type_names, ca->get_type(ca));
                         process_attribute(this, ca);
                     }
                     attributes->destroy(attributes);
                     break;
                 case CFG_ACK:
                     break;
                 default:
                     DBG1(DBG_IKE, "ignoring %N config payload",
                          config_type_names, cp->get_type(cp));
                     break;
             }
         }
     }
     enumerator->destroy(enumerator);
 }