strongSwan: tnccs_reason_strings_msg
tnccs_reason_strings_msg
tnccs_11
Classes
struct tnccs_reason_strings_msg_t
Typedefs
typedef struct
tnccs_reason_strings_msg_t tnccs_reason_strings_msg_t
Functions
tnccs_msg_t * tnccs_reason_strings_msg_create_from_node (xmlNodePtr node, linked_list_t *errors)
tnccs_msg_t * tnccs_reason_strings_msg_create (chunk_t reason, chunk_t language)
Detailed Description
Typedef Documentation
typedef struct tnccs_reason_strings_msg_t tnccs_reason_strings_msg_t
Definition at line 24 of file tnccs_reason_strings_msg.h.
Function Documentation
tnccs_msg_t* tnccs_reason_strings_msg_create (chunk_t reason, chunk_t language)
Create a TNCCS-ReasonStrings message from parameters
Parameters
reason reason string
language reason language
See header
Definition at line 153 of file tnccs_reason_strings_msg.c.
References chunk_create_clone(), enum_to_name(), INIT, chunk_t::len, malloc(), n, chunk_t::ptr, TNCCS_MSG_REASON_STRINGS, tnccs_msg_type_names, and type.
Referenced by check_and_build_recommendation().
 {
     private_tnccs_reason_strings_msg_t *this;
     xmlNodePtr n, n2, n3;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .destroy = _destroy,
             },
             .get_reason = _get_reason,
         },
         .type = TNCCS_MSG_REASON_STRINGS,
         .node =  xmlNewNode(NULL, "TNCC-TNCS-Message"),
         .reason = chunk_create_clone(malloc(reason.len + 1), reason),
         .language = chunk_create_clone(malloc(language.len + 1), language),
     );
     /* add NULL termination for XML string representation */
     this->reason.ptr[this->reason.len] = '\0';
     this->language.ptr[this->language.len] = '\0';
     /* add the message type number in hex */
     n = xmlNewNode(NULL, "Type");
     xmlNodeSetContent(n, "00000004");
     xmlAddChild(this->node, n);
     n = xmlNewNode(NULL, "XML");
     xmlAddChild(this->node, n);
     n2 = xmlNewNode(NULL, enum_to_name(tnccs_msg_type_names, this->type));
     /* could add multiple reasons here, if we had them */
     n3 = xmlNewNode(NULL, "ReasonString");
     xmlNewProp(n3, "xml:lang", this->language.ptr);
     xmlNodeSetContent(n3, this->reason.ptr);
     xmlAddChild(n2, n3);
     xmlAddChild(n, n2);
     return &this->public.tnccs_msg_interface;
 }
tnccs_msg_t* tnccs_reason_strings_msg_create_from_node (xmlNodePtr node, linked_list_t * errors)
Create a TNCCS-ReasonStrings message from XML-encoded message node
Parameters
node XML-encoded message node
errors linked list of TNCCS error messages
See header
Definition at line 85 of file tnccs_reason_strings_msg.c.
References chunk_clone, chunk_from_str, destroy(), INIT, linked_list_t::insert_last, msg, strdup, TNCCS_ERROR_MALFORMED_BATCH, tnccs_error_msg_create(), and TNCCS_MSG_REASON_STRINGS.
Referenced by tnccs_msg_create_from_node().
 {
     private_tnccs_reason_strings_msg_t *this;
     char *error_msg, *lang_string, *reason_string;
     tnccs_error_type_t error_type = TNCCS_ERROR_MALFORMED_BATCH;
     tnccs_msg_t *msg;
     xmlNodePtr child;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .destroy = _destroy,
             },
             .get_reason = _get_reason,
         },
         .type = TNCCS_MSG_REASON_STRINGS,
         .node = node,
     );
     if (xmlStrcmp(node->name, "TNCCS-ReasonStrings"))
     {
         error_msg = "TNCCS-ReasonStrings tag expected";
         goto fatal;
     }
     child = node->xmlChildrenNode;
     while (child)
     {
         if (xmlIsBlankNode(child))
         {
             child = child->next;
             continue;
         }
         if (xmlStrcmp(child->name, "ReasonString"))
         {
             error_msg = "ReasonString tag expected";
             goto fatal;
         }
         break;
     }
     lang_string = xmlGetProp(child, "lang");
     if (!lang_string)
     {
         lang_string = strdup("");
     }
     this->language = chunk_clone(chunk_from_str(lang_string));
     xmlFree(lang_string);
     reason_string = xmlNodeGetContent(child);
     this->reason = chunk_clone(chunk_from_str(reason_string));
     xmlFree(reason_string);
     return &this->public.tnccs_msg_interface;
 fatal:
     msg = tnccs_error_msg_create(error_type, error_msg);
     errors->insert_last(errors, msg);
     destroy(this);
     return NULL;
 }