strongSwan: imc_imv_msg
imc_imv_msg
tnccs_11
Classes
struct imc_imv_msg_t
Typedefs
typedef struct imc_imv_msg_t imc_imv_msg_t
Functions
tnccs_msg_t * imc_imv_msg_create_from_node (xmlNodePtr node, linked_list_t *errors)
tnccs_msg_t * imc_imv_msg_create (TNC_MessageType msg_type, chunk_t msg_body)
Detailed Description
Typedef Documentation
typedef struct imc_imv_msg_t imc_imv_msg_t
Definition at line 24 of file imc_imv_msg.h.
Function Documentation
tnccs_msg_t* imc_imv_msg_create (TNC_MessageType msg_type, chunk_t msg_body)
Create an IMC-IMV message from parameters
Parameters
msg_type IMC-IMV message type
msg_body IMC-IMV message body
See header
Definition at line 206 of file imc_imv_msg.c.
References chunk_clone, encode_base64(), free(), IMC_IMV_MSG, INIT, n, chunk_t::ptr, and snprintf.
Referenced by METHOD().
 {
     private_imc_imv_msg_t *this;
     chunk_t b64_body;
     char buf[10];       /* big enough for hex-encoded message type */
     xmlNodePtr n;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .destroy = _destroy,
             },
             .get_msg_type = _get_msg_type,
             .get_msg_body = _get_msg_body,
         },
         .type = IMC_IMV_MSG,
         .node = xmlNewNode(NULL, "IMC-IMV-Message"),
         .msg_type = msg_type,
         .msg_body = chunk_clone(msg_body),
     );
     /* add the message type number in hex */
     n = xmlNewNode(NULL, "Type");
     snprintf(buf, 10, "%08x", this->msg_type);
     xmlNodeSetContent(n, buf);
     xmlAddChild(this->node, n);
     /* encode the message as a Base64 node */
     n = xmlNewNode(NULL, "Base64");
     b64_body = encode_base64(this->msg_body);
     xmlNodeSetContent(n, b64_body.ptr);
     xmlAddChild(this->node, n);
     free(b64_body.ptr);
     return &this->public.tnccs_msg_interface;
 }
tnccs_msg_t* imc_imv_msg_create_from_node (xmlNodePtr node, linked_list_t * errors)
Create an IMC-IMV message from XML-encoded message node
Parameters
node XML-encoded message node
errors linked list of TNCCS error messages
See header
Definition at line 158 of file imc_imv_msg.c.
References chunk_create(), decode_base64(), IMC_IMV_MSG, INIT, and streq().
Referenced by tnccs_msg_create_from_node().
 {
     private_imc_imv_msg_t *this;
     xmlNsPtr ns;
     xmlNodePtr cur;
     xmlChar *content;
     chunk_t b64_body;
     INIT(this,
         .public = {
             .tnccs_msg_interface = {
                 .get_type = _get_type,
                 .get_node = _get_node,
                 .destroy = _destroy,
             },
             .get_msg_type = _get_msg_type,
             .get_msg_body = _get_msg_body,
         },
         .type = IMC_IMV_MSG,
         .node = node,
     );
     ns =  node->ns;
     cur = node->xmlChildrenNode;
     while (cur)
     {
         if (streq(cur->name, "Type") && cur->ns == ns)
         {
             content = xmlNodeGetContent(cur);
             this->msg_type = strtoul(content, NULL, 16);
             xmlFree(content);
         }
         else if (streq(cur->name, "Base64") && cur->ns == ns)
         {
             content = xmlNodeGetContent(cur);
             b64_body = chunk_create(content, strlen(content));
             this->msg_body = decode_base64(b64_body);
             xmlFree(content);
         }
         cur = cur->next;
     }
     return &this->public.tnccs_msg_interface;
 }