strongSwan: confread.h File Reference
confread.h File Reference
#include <kernel/kernel_ipsec.h>
Classes
struct starter_end
struct starter_conn
struct starter_ca
struct starter_config
Typedefs
typedef struct starter_end starter_end_t
typedef struct starter_conn starter_conn_t
typedef struct starter_ca starter_ca_t
typedef struct starter_config starter_config_t
Enumerations
enum startup_t { STARTUP_NO, STARTUP_ADD, STARTUP_ROUTE, STARTUP_START }
enum starter_state_t {
STATE_IGNORE, STATE_TO_ADD, STATE_ADDED, STATE_REPLACED,
STATE_INVALID
}
enum keyexchange_t { KEY_EXCHANGE_IKE = 0, KEY_EXCHANGE_IKEV1 = 1, KEY_EXCHANGE_IKEV2 = 2 }
enum strict_t { STRICT_NO, STRICT_YES, STRICT_IFURI }
enum certpolicy_t {
CERT_ALWAYS_SEND, CERT_SEND_IF_ASKED, CERT_NEVER_SEND, CERT_YES_SEND,
CERT_NO_SEND
}
enum dpd_action_t {
DPD_ACTION_NONE, DPD_ACTION_CLEAR, DPD_ACTION_HOLD, DPD_ACTION_RESTART,
DPD_ACTION_UNKNOW
}
enum fragmentation_t {
FRAGMENTATION_NO, FRAGMENTATION_YES, FRAGMENTATION_FORCE, FRAGMENTATION_NO,
FRAGMENTATION_YES, FRAGMENTATION_FORCE
}
enum sa_option_t {
SA_OPTION_COMPRESS = 1 << 1, SA_OPTION_DONT_REKEY = 1 << 2, SA_OPTION_DONT_REAUTH = 1 << 3, SA_OPTION_MODECFG_PUSH = 1 << 4,
SA_OPTION_XAUTH_SERVER = 1 << 5, SA_OPTION_MOBIKE = 1 << 6, SA_OPTION_FORCE_ENCAP = 1 << 7
}
Functions
starter_config_t * confread_load (const char *file)
void confread_free (starter_config_t *cfg)
Typedef Documentation
typedef struct starter_ca starter_ca_t
Definition at line 173 of file confread.h.
typedef struct starter_config starter_config_t
Definition at line 192 of file confread.h.
typedef struct starter_conn starter_conn_t
Definition at line 116 of file confread.h.
typedef struct starter_end starter_end_t
Definition at line 85 of file confread.h.
Enumeration Type Documentation
enum certpolicy_t
Enumerator
CERT_ALWAYS_SEND
CERT_SEND_IF_ASKED
CERT_NEVER_SEND
CERT_YES_SEND
CERT_NO_SEND
Definition at line 49 of file confread.h.
              {
         CERT_ALWAYS_SEND,
         CERT_SEND_IF_ASKED,
         CERT_NEVER_SEND,
         CERT_YES_SEND,      /* synonym for CERT_ALWAYS_SEND */
         CERT_NO_SEND,       /* synonym for CERT_NEVER_SEND */
 } certpolicy_t;
enum dpd_action_t
Enumerator
DPD_ACTION_NONE
DPD_ACTION_CLEAR
DPD_ACTION_HOLD
DPD_ACTION_RESTART
DPD_ACTION_UNKNOW
Definition at line 57 of file confread.h.
              {
         DPD_ACTION_NONE,
         DPD_ACTION_CLEAR,
         DPD_ACTION_HOLD,
         DPD_ACTION_RESTART,
         DPD_ACTION_UNKNOW,
 } dpd_action_t;
enum fragmentation_t
Enumerator
FRAGMENTATION_NO
disable fragmentation
FRAGMENTATION_YES
enable fragmentation if supported by peer
FRAGMENTATION_FORCE
force use of fragmentation (even for the first message)
FRAGMENTATION_NO
FRAGMENTATION_YES
FRAGMENTATION_FORCE
Definition at line 65 of file confread.h.
              {
         /* same as in ike_cfg.h */
         FRAGMENTATION_NO,
         FRAGMENTATION_YES,
         FRAGMENTATION_FORCE,
 } fragmentation_t;
enum keyexchange_t
Enumerator
KEY_EXCHANGE_IKE
KEY_EXCHANGE_IKEV1
KEY_EXCHANGE_IKEV2
Definition at line 36 of file confread.h.
              {
         /* shared with ike_version_t */
         KEY_EXCHANGE_IKE = 0,
         KEY_EXCHANGE_IKEV1 = 1,
         KEY_EXCHANGE_IKEV2 = 2,
 } keyexchange_t;
enum sa_option_t
Enumerator
SA_OPTION_COMPRESS
SA_OPTION_DONT_REKEY
SA_OPTION_DONT_REAUTH
SA_OPTION_MODECFG_PUSH
SA_OPTION_XAUTH_SERVER
SA_OPTION_MOBIKE
SA_OPTION_FORCE_ENCAP
Definition at line 72 of file confread.h.
              {
         /* IPsec options */
         SA_OPTION_COMPRESS      = 1 << 1, /* use IPComp */
         /* IKE and other other options */
         SA_OPTION_DONT_REKEY    = 1 << 2, /* don't rekey state either Phase */
         SA_OPTION_DONT_REAUTH   = 1 << 3, /* don't reauthenticate on rekeying, IKEv2 only */
         SA_OPTION_MODECFG_PUSH  = 1 << 4, /* is modecfg pushed by server? */
         SA_OPTION_XAUTH_SERVER  = 1 << 5, /* are we an XAUTH server? */
         SA_OPTION_MOBIKE        = 1 << 6, /* enable MOBIKE for IKEv2  */
         SA_OPTION_FORCE_ENCAP   = 1 << 7, /* force UDP encapsulation */
 } sa_option_t;
enum starter_state_t
Enumerator
STATE_IGNORE
STATE_TO_ADD
STATE_ADDED
STATE_REPLACED
STATE_INVALID
Definition at line 28 of file confread.h.
              {
         STATE_IGNORE,
         STATE_TO_ADD,
         STATE_ADDED,
         STATE_REPLACED,
         STATE_INVALID
 } starter_state_t;
enum startup_t
Enumerator
STARTUP_NO
STARTUP_ADD
STARTUP_ROUTE
STARTUP_START
Definition at line 21 of file confread.h.
              {
         STARTUP_NO,
         STARTUP_ADD,
         STARTUP_ROUTE,
         STARTUP_START
 } startup_t;
enum strict_t
Enumerator
STRICT_NO
STRICT_YES
STRICT_IFURI
Definition at line 43 of file confread.h.
              {
         STRICT_NO,
         STRICT_YES,
         STRICT_IFURI,
 } strict_t;
Function Documentation
void confread_free (starter_config_t * cfg)
Definition at line 659 of file confread.c.
References starter_config::ca_first, confread_free_ca(), confread_free_conn(), conn, starter_config::conn_first, free(), free_args(), KW_SETUP_FIRST, KW_SETUP_LAST, starter_conn::next, and starter_ca::next.
Referenced by main().
 {
     starter_conn_t *conn = cfg->conn_first;
     starter_ca_t   *ca   = cfg->ca_first;
     free_args(KW_SETUP_FIRST, KW_SETUP_LAST, (char *)cfg);
     while (conn != NULL)
     {
         starter_conn_t *conn_aux = conn;
         conn = conn->next;
         confread_free_conn(conn_aux);
     }
     while (ca != NULL)
     {
         starter_ca_t *ca_aux = ca;
         ca = ca->next;
         confread_free_ca(ca_aux);
     }
     free(cfg);
 }
starter_config_t* confread_load (const char * file)
Definition at line 688 of file confread.c.
References starter_config::ca_first, starter_config::ca_last, CONF_PARSER_CA, CONF_PARSER_CONN, conf_parser_create(), confread_free_ca(), confread_free_conn(), conn, conn_defaults(), starter_config::conn_first, starter_config::conn_last, DBG1, DBG_APP, enumerator_t::destroy, conf_parser_t::destroy, enumerator_t::enumerate, starter_config::err, conf_parser_t::get_sections, INIT, load_ca(), load_conn(), load_setup(), name, starter_conn::next, starter_ca::next, starter_config::non_fatal_err, conf_parser_t::parse, parser, starter_conn::startup, starter_ca::startup, STARTUP_NO, starter_conn::state, starter_ca::state, STATE_TO_ADD, strdup, TRUE, and starter_config::uniqueids.
Referenced by main().
 {
     conf_parser_t *parser;
     starter_config_t *cfg = NULL;
     enumerator_t *enumerator;
     u_int total_err;
     char *name;
     parser = conf_parser_create(file);
     if (!parser->parse(parser))
     {
         parser->destroy(parser);
         return NULL;
     }
     INIT(cfg,
         .setup = {
             .uniqueids = TRUE,
         }
     );
     /* load config setup section */
     load_setup(cfg, parser);
     /* load ca sections */
     enumerator = parser->get_sections(parser, CONF_PARSER_CA);
     while (enumerator->enumerate(enumerator, &name))
     {
         u_int previous_err = cfg->err;
         starter_ca_t *ca;
         INIT(ca,
             .name = strdup(name),
         );
         load_ca(ca, cfg, parser);
         if (cfg->err > previous_err)
         {
             total_err = cfg->err - previous_err;
             DBG1(DBG_APP, "# ignored ca '%s' due to %d parsing error%s", name,
                  total_err, (total_err > 1) ? "s" : "");
             confread_free_ca(ca);
             cfg->non_fatal_err += cfg->err - previous_err;
             cfg->err = previous_err;
         }
         else
         {
             if (cfg->ca_last)
             {
                 cfg->ca_last->next = ca;
             }
             cfg->ca_last = ca;
             if (!cfg->ca_first)
             {
                 cfg->ca_first = ca;
             }
             if (ca->startup != STARTUP_NO)
             {
                 ca->state = STATE_TO_ADD;
             }
         }
     }
     enumerator->destroy(enumerator);
     /* load conn sections */
     enumerator = parser->get_sections(parser, CONF_PARSER_CONN);
     while (enumerator->enumerate(enumerator, &name))
     {
         u_int previous_err = cfg->err;
         starter_conn_t *conn;
         INIT(conn,
             .name = strdup(name),
         );
         conn_defaults(conn);
         load_conn(conn, cfg, parser);
         if (cfg->err > previous_err)
         {
             total_err = cfg->err - previous_err;
             DBG1(DBG_APP, "# ignored conn '%s' due to %d parsing error%s", name,
                  total_err, (total_err > 1) ? "s" : "");
             confread_free_conn(conn);
             cfg->non_fatal_err += cfg->err - previous_err;
             cfg->err = previous_err;
         }
         else
         {
             if (cfg->conn_last)
             {
                 cfg->conn_last->next = conn;
             }
             cfg->conn_last = conn;
             if (!cfg->conn_first)
             {
                 cfg->conn_first = conn;
             }
             if (conn->startup != STARTUP_NO)
             {
                 conn->state = STATE_TO_ADD;
             }
         }
     }
     enumerator->destroy(enumerator);
     parser->destroy(parser);
     total_err = cfg->err + cfg->non_fatal_err;
     if (total_err > 0)
     {
         DBG1(DBG_APP, "### %d parsing error%s (%d fatal) ###",
              total_err, (total_err > 1)?"s":"", cfg->err);
     }
     return cfg;
 }