strongSwan: tls_eap
tls_eap
libtls
Classes
struct tls_eap_t
Typedefs
typedef struct tls_eap_t tls_eap_t
Functions
tls_eap_t * tls_eap_create (eap_type_t type, tls_t *tls, size_t frag_size, int max_msg_count, bool include_length)
Detailed Description
Typedef Documentation
typedef struct tls_eap_t tls_eap_t
Definition at line 24 of file tls_eap.h.
Function Documentation
tls_eap_t* tls_eap_create (eap_type_t type, tls_t * tls, size_t frag_size, int max_msg_count, bool include_length)
Create a tls_eap instance.
Parameters
type EAP type, EAP-TLS or EAP-TTLS
tls TLS implementation
frag_size maximum size of a TLS fragment we send
max_msg_count maximum number of processed messages
include_length if TRUE include length in non-fragmented packets
See header
Definition at line 445 of file tls_eap.c.
References EAP_PEAP, EAP_PEAP_SUPPORTED_VERSION, EAP_PT_EAP, EAP_PT_EAP_SUPPORTED_VERSION, EAP_TNC, EAP_TNC_SUPPORTED_VERSION, EAP_TTLS, EAP_TTLS_SUPPORTED_VERSION, identifier, INIT, tls_t::is_server, random, and type.
Referenced by eap_peap_create(), eap_tls_create(), eap_tnc_create(), and eap_ttls_create().
 {
     private_tls_eap_t *this;
     if (!tls)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .initiate = _initiate,
             .process = _process,
             .get_msk = _get_msk,
             .get_identifier = _get_identifier,
             .set_identifier = _set_identifier,
             .get_auth = _get_auth,
             .destroy = _destroy,
         },
         .type = type,
         .is_server = tls->is_server(tls),
         .first_fragment = (type != EAP_TNC && type != EAP_PT_EAP),
         .frag_size = frag_size,
         .max_msg_count = max_msg_count,
         .include_length = include_length,
         .tls = tls,
     );
     switch (type)
     {
         case EAP_TTLS:
             this->supported_version = EAP_TTLS_SUPPORTED_VERSION;
             break;
         case EAP_TNC:
             this->supported_version = EAP_TNC_SUPPORTED_VERSION;
             break;
         case EAP_PEAP:
             this->supported_version = EAP_PEAP_SUPPORTED_VERSION;
             break;
         case EAP_PT_EAP:
             this->supported_version = EAP_PT_EAP_SUPPORTED_VERSION;
             break;
         default:
             break;
     }
     if (this->is_server)
     {
         do
         {   /* start with non-zero random identifier */
             this->identifier = random();
         }
         while (!this->identifier);
     }
     return &this->public;
 }