strongSwan: x509_ocsp_request.c File Reference
x509_ocsp_request.c File Reference
#include "x509_ocsp_request.h"
#include <library.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <utils/identification.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
#include <credentials/certificates/x509.h>
#include <credentials/keys/private_key.h>
Classes
struct private_x509_ocsp_request_t
Macros
#define NONCE_LEN 16
Typedefs
typedef struct
private_x509_ocsp_request_t private_x509_ocsp_request_t
Functions
static chunk_t build_requestorName (private_x509_ocsp_request_t *this)
static chunk_t build_Request (private_x509_ocsp_request_t *this, chunk_t issuerNameHash, chunk_t issuerKeyHash, chunk_t serialNumber)
static chunk_t build_requestList (private_x509_ocsp_request_t *this)
static chunk_t build_nonce (private_x509_ocsp_request_t *this)
static chunk_t build_acceptableResponses (private_x509_ocsp_request_t *this)
static chunk_t build_requestExtensions (private_x509_ocsp_request_t *this)
static chunk_t build_tbsRequest (private_x509_ocsp_request_t *this)
static chunk_t build_optionalSignature (private_x509_ocsp_request_t *this, chunk_t tbsRequest)
static chunk_t build_OCSPRequest (private_x509_ocsp_request_t *this)
METHOD (certificate_t, get_type, certificate_type_t, private_x509_ocsp_request_t *this)
METHOD (certificate_t, get_subject, identification_t *, private_x509_ocsp_request_t *this)
METHOD (certificate_t, get_issuer, identification_t *, private_x509_ocsp_request_t *this)
METHOD (certificate_t, has_subject, id_match_t, private_x509_ocsp_request_t *this, identification_t *subject)
METHOD (certificate_t, has_issuer, id_match_t, private_x509_ocsp_request_t *this, identification_t *issuer)
METHOD (certificate_t, issued_by, bool, private_x509_ocsp_request_t *this, certificate_t *issuer, signature_scheme_t *scheme)
METHOD (certificate_t, get_public_key, public_key_t *, private_x509_ocsp_request_t *this)
METHOD (certificate_t, get_validity, bool, private_x509_ocsp_request_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_x509_ocsp_request_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, equals, bool, private_x509_ocsp_request_t *this, certificate_t *other)
METHOD (certificate_t, get_ref, certificate_t *, private_x509_ocsp_request_t *this)
METHOD (certificate_t, destroy, void, private_x509_ocsp_request_t *this)
static
private_x509_ocsp_request_t * create_empty ()
x509_ocsp_request_t * x509_ocsp_request_gen (certificate_type_t type, va_list args)
Variables
static const chunk_t ASN1_nonce_oid
static const chunk_t ASN1_response_oid
static const chunk_t ASN1_response_content
Macro Definition Documentation
#define NONCE_LEN 16
Definition at line 29 of file x509_ocsp_request.c.
Referenced by build_nonce().
Typedef Documentation
typedef struct private_x509_ocsp_request_t private_x509_ocsp_request_t
Definition at line 31 of file x509_ocsp_request.c.
Function Documentation
static chunk_t build_acceptableResponses (private_x509_ocsp_request_t * this) static
build acceptableResponses extension
Definition at line 218 of file x509_ocsp_request.c.
References ASN1_SEQUENCE, and asn1_wrap().
Referenced by build_requestExtensions().
 {
     return asn1_wrap(ASN1_SEQUENCE, "cc",
                 ASN1_response_oid,
                 ASN1_response_content);
 }
static chunk_t build_nonce (private_x509_ocsp_request_t * this) static
build nonce extension
Definition at line 199 of file x509_ocsp_request.c.
References rng_t::allocate_bytes, ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_simple_object(), asn1_wrap(), chunk_empty, crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG_LIB, rng_t::destroy, DESTROY_IF, lib, NONCE_LEN, rng, and RNG_WEAK.
Referenced by build_requestExtensions().
 {
     rng_t *rng;
     rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
     if (!rng || !rng->allocate_bytes(rng, NONCE_LEN, &this->nonce))
     {
         DBG1(DBG_LIB, "creating OCSP request nonce failed, no RNG found");
         DESTROY_IF(rng);
         return chunk_empty;
     }
     rng->destroy(rng);
     return asn1_wrap(ASN1_SEQUENCE, "cm", ASN1_nonce_oid,
                 asn1_simple_object(ASN1_OCTET_STRING, this->nonce));
 }
static chunk_t build_OCSPRequest (private_x509_ocsp_request_t * this) static
Build the OCSPRequest data
Definition at line 300 of file x509_ocsp_request.c.
References ASN1_SEQUENCE, asn1_wrap(), build_optionalSignature(), build_tbsRequest(), chunk_empty, and key.
Referenced by x509_ocsp_request_gen().
 {
     chunk_t tbsRequest, optionalSignature = chunk_empty;
     tbsRequest = build_tbsRequest(this);
     if (this->key)
     {
         optionalSignature = build_optionalSignature(this, tbsRequest);
     }
     return asn1_wrap(ASN1_SEQUENCE, "mm", tbsRequest, optionalSignature);
 }
static chunk_t build_optionalSignature (private_x509_ocsp_request_t * this, chunk_t tbsRequest) static
Build the optionalSignature
Definition at line 250 of file x509_ocsp_request.c.
References asn1_algorithmIdentifier(), asn1_bitstring(), ASN1_CONTEXT_C_0, ASN1_SEQUENCE, asn1_wrap(), cert, CERT_ASN1_DER, chunk_empty, DBG1, DBG_LIB, encoding, key, KEY_BLISS, KEY_ECDSA, KEY_RSA, key_type_names, OID_BLISS_WITH_SHA2_512, OID_ECDSA_WITH_SHA1, OID_SHA1_WITH_RSA, scheme, SIGN_BLISS_WITH_SHA2_512, SIGN_ECDSA_WITH_SHA1_DER, and SIGN_RSA_EMSA_PKCS1_SHA1.
Referenced by build_OCSPRequest().
 {
     int oid;
     signature_scheme_t scheme;
     chunk_t certs = chunk_empty, signature, encoding;
     switch (this->key->get_type(this->key))
     {
         /* TODO: use a generic mapping function */
         case KEY_RSA:
             oid = OID_SHA1_WITH_RSA;
             scheme = SIGN_RSA_EMSA_PKCS1_SHA1;
             break;
         case KEY_ECDSA:
             oid = OID_ECDSA_WITH_SHA1;
             scheme = SIGN_ECDSA_WITH_SHA1_DER;
             break;
         case KEY_BLISS:
             oid = OID_BLISS_WITH_SHA2_512;
             scheme = SIGN_BLISS_WITH_SHA2_512;
             break;
         default:
             DBG1(DBG_LIB, "unable to sign OCSP request, %N signature not "
                  "supported", key_type_names, this->key->get_type(this->key));
             return chunk_empty;
     }
     if (!this->key->sign(this->key, scheme, tbsRequest, &signature))
     {
         DBG1(DBG_LIB, "creating OCSP signature failed, skipped");
         return chunk_empty;
     }
     if (this->cert &&
         this->cert->get_encoding(this->cert, CERT_ASN1_DER, &encoding))
     {
         certs = asn1_wrap(ASN1_CONTEXT_C_0, "m",
                     asn1_wrap(ASN1_SEQUENCE, "m", encoding));
     }
     return asn1_wrap(ASN1_CONTEXT_C_0, "m",
                 asn1_wrap(ASN1_SEQUENCE, "cmm",
                     asn1_algorithmIdentifier(oid),
                     asn1_bitstring("m", signature),
                     certs));
 }
static chunk_t build_Request (private_x509_ocsp_request_t * this, chunk_t issuerNameHash, chunk_t issuerKeyHash, chunk_t serialNumber) static
build Request, not using singleRequestExtensions
Definition at line 125 of file x509_ocsp_request.c.
References asn1_algorithmIdentifier(), ASN1_INTEGER, ASN1_OCTET_STRING, ASN1_SEQUENCE, asn1_simple_object(), asn1_wrap(), and OID_SHA1.
Referenced by build_requestList().
 {
     return asn1_wrap(ASN1_SEQUENCE, "m",
                 asn1_wrap(ASN1_SEQUENCE, "mmmm",
                     asn1_algorithmIdentifier(OID_SHA1),
                     asn1_simple_object(ASN1_OCTET_STRING, issuerNameHash),
                     asn1_simple_object(ASN1_OCTET_STRING, issuerKeyHash),
                     asn1_simple_object(ASN1_INTEGER, serialNumber)));
 }
static chunk_t build_requestExtensions (private_x509_ocsp_request_t * this) static
build requestExtensions
Definition at line 228 of file x509_ocsp_request.c.
References ASN1_CONTEXT_C_2, ASN1_SEQUENCE, asn1_wrap(), build_acceptableResponses(), and build_nonce().
Referenced by build_tbsRequest().
 {
     return asn1_wrap(ASN1_CONTEXT_C_2, "m",
                 asn1_wrap(ASN1_SEQUENCE, "mm",
                     build_nonce(this),
                     build_acceptableResponses(this)));
 }
static chunk_t build_requestList (private_x509_ocsp_request_t * this) static
build requestList
Definition at line 140 of file x509_ocsp_request.c.
References hasher_t::allocate_hash, ASN1_SEQUENCE, asn1_wrap(), build_Request(), cert, chunk_cat, chunk_empty, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, enumerator_t::destroy, hasher_t::destroy, enumerator_t::enumerate, identification_t::get_encoding, certificate_t::get_public_key, x509_t::get_serial, certificate_t::get_subject, HASH_SHA1, hasher, KEYID_PUBKEY_SHA1, lib, list, public, request(), and serialNumber.
Referenced by build_tbsRequest().
 {
     chunk_t issuerNameHash, issuerKeyHash;
     identification_t *issuer;
     x509_t *x509;
     certificate_t *cert;
     chunk_t list = chunk_empty;
     public_key_t *public;
     cert = (certificate_t*)this->ca;
     public = cert->get_public_key(cert);
     if (public)
     {
         hasher_t *hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
         if (hasher)
         {
             if (public->get_fingerprint(public, KEYID_PUBKEY_SHA1,
                                         &issuerKeyHash))
             {
                 enumerator_t *enumerator;
                 issuer = cert->get_subject(cert);
                 if (hasher->allocate_hash(hasher, issuer->get_encoding(issuer),
                                           &issuerNameHash))
                 {
                     enumerator = this->candidates->create_enumerator(
                                                             this->candidates);
                     while (enumerator->enumerate(enumerator, &x509))
                     {
                         chunk_t request, serialNumber;
                         serialNumber = x509->get_serial(x509);
                         request = build_Request(this, issuerNameHash,
                                                 issuerKeyHash, serialNumber);
                         list = chunk_cat("mm", list, request);
                     }
                     enumerator->destroy(enumerator);
                     chunk_free(&issuerNameHash);
                 }
                 hasher->destroy(hasher);
             }
         }
         else
         {
             DBG1(DBG_LIB, "creating OCSP request failed, SHA1 not supported");
         }
         public->destroy(public);
     }
     else
     {
         DBG1(DBG_LIB, "creating OCSP request failed, CA certificate has "
              "no public key");
     }
     return asn1_wrap(ASN1_SEQUENCE, "m", list);
 }
static chunk_t build_requestorName (private_x509_ocsp_request_t * this) static
build requestorName
Definition at line 105 of file x509_ocsp_request.c.
References ASN1_CONTEXT_C_1, ASN1_CONTEXT_C_4, asn1_simple_object(), asn1_wrap(), cert, and chunk_empty.
Referenced by build_tbsRequest().
 {
     if (this->requestor || this->cert)
     {   /* use requestor name, fallback to his cert subject */
         if (!this->requestor)
         {
             this->requestor = this->cert->get_subject(this->cert);
             this->requestor = this->requestor->clone(this->requestor);
         }
         return asn1_wrap(ASN1_CONTEXT_C_1, "m",
                     asn1_simple_object(ASN1_CONTEXT_C_4,
                         this->requestor->get_encoding(this->requestor)));
     }
     return chunk_empty;
 }
static chunk_t build_tbsRequest (private_x509_ocsp_request_t * this) static
build tbsRequest
Definition at line 239 of file x509_ocsp_request.c.
References ASN1_SEQUENCE, asn1_wrap(), build_requestExtensions(), build_requestList(), and build_requestorName().
Referenced by build_OCSPRequest().
 {
     return asn1_wrap(ASN1_SEQUENCE, "mmm",
                 build_requestorName(this),
                 build_requestList(this),
                 build_requestExtensions(this));
 }
static private_x509_ocsp_request_t* create_empty (void) static
create an empty but initialized OCSP request
Definition at line 469 of file x509_ocsp_request.c.
References INIT, and linked_list_create().
Referenced by x509_ocsp_request_gen().
 {
     private_x509_ocsp_request_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .interface = {
                     .get_type = _get_type,
                     .get_subject = _get_subject,
                     .get_issuer = _get_issuer,
                     .has_subject = _has_subject,
                     .has_issuer = _has_issuer,
                     .issued_by = _issued_by,
                     .get_public_key = _get_public_key,
                     .get_validity = _get_validity,
                     .get_encoding = _get_encoding,
                     .equals = _equals,
                     .get_ref = _get_ref,
                     .destroy = _destroy,
                 },
             },
         },
         .candidates = linked_list_create(),
         .ref = 1,
     );
     return this;
 }
METHOD (certificate_t , get_type , certificate_type_t , private_x509_ocsp_request_t * this)
Definition at line 313 of file x509_ocsp_request.c.
References CERT_X509_OCSP_REQUEST.
 {
     return CERT_X509_OCSP_REQUEST;
 }
METHOD (certificate_t , get_subject , identification_t * , private_x509_ocsp_request_t * this)
Definition at line 319 of file x509_ocsp_request.c.
References cert, and certificate_t::get_subject.
 {
     certificate_t *ca = (certificate_t*)this->ca;
     if (this->requestor)
     {
         return this->requestor;
     }
     if (this->cert)
     {
         return this->cert->get_subject(this->cert);
     }
     return ca->get_subject(ca);
 }
METHOD (certificate_t , get_issuer , identification_t * , private_x509_ocsp_request_t * this)
Definition at line 335 of file x509_ocsp_request.c.
References certificate_t::get_subject.
 {
     certificate_t *ca = (certificate_t*)this->ca;
     return ca->get_subject(ca);
 }
METHOD (certificate_t , has_subject , id_match_t , private_x509_ocsp_request_t * this, identification_t * subject)
Definition at line 343 of file x509_ocsp_request.c.
References enumerator_t::destroy, enumerator_t::enumerate, certificate_t::has_subject, ID_MATCH_NONE, and match().
 {
     certificate_t *current;
     enumerator_t *enumerator;
     id_match_t match, best = ID_MATCH_NONE;
     enumerator = this->candidates->create_enumerator(this->candidates);
     while (enumerator->enumerate(enumerator, &current))
     {
         match = current->has_subject(current, subject);
         if (match > best)
         {
             best = match;
         }
     }
     enumerator->destroy(enumerator);
     return best;
 }
METHOD (certificate_t , has_issuer , id_match_t , private_x509_ocsp_request_t * this, identification_t * issuer)
Definition at line 363 of file x509_ocsp_request.c.
References certificate_t::has_subject.
 {
     certificate_t *ca = (certificate_t*)this->ca;
     return ca->has_subject(ca, issuer);
 }
METHOD (certificate_t , issued_by , bool , private_x509_ocsp_request_t * this, certificate_t * issuer, signature_scheme_t * scheme)
Definition at line 372 of file x509_ocsp_request.c.
References DBG1, DBG_LIB, and FALSE.
 {
     DBG1(DBG_LIB, "OCSP request validation not implemented!");
     return FALSE;
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_x509_ocsp_request_t * this)
Definition at line 380 of file x509_ocsp_request.c.
 {
     return NULL;
 }
METHOD (certificate_t , get_validity , bool , private_x509_ocsp_request_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 386 of file x509_ocsp_request.c.
References cert, and certificate_t::get_validity.
 {
     certificate_t *cert;
     if (this->cert)
     {
         cert = this->cert;
     }
     else
     {
         cert = (certificate_t*)this->ca;
     }
     return cert->get_validity(cert, when, not_before, not_after);
 }
METHOD (certificate_t , get_encoding , bool , private_x509_ocsp_request_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 403 of file x509_ocsp_request.c.
References CERT_ASN1_DER, chunk_clone, CRED_PART_END, CRED_PART_X509_OCSP_REQ_ASN1_DER, cred_encoding_t::encode, library_t::encoding, lib, and TRUE.
 {
     if (type == CERT_ASN1_DER)
     {
         *encoding = chunk_clone(this->encoding);
         return TRUE;
     }
     return lib->encoding->encode(lib->encoding, type, NULL, encoding,
                 CRED_PART_X509_OCSP_REQ_ASN1_DER, this->encoding, CRED_PART_END);
 }
METHOD (certificate_t , equals , bool , private_x509_ocsp_request_t * this, certificate_t * other)
Definition at line 416 of file x509_ocsp_request.c.
References CERT_ASN1_DER, CERT_X509_OCSP_REQUEST, chunk_equals(), encoding, equals(), certificate_t::equals, FALSE, free(), certificate_t::get_encoding, certificate_t::get_type, chunk_t::ptr, and TRUE.
 {
     chunk_t encoding;
     bool equal;
     if (this == (private_x509_ocsp_request_t*)other)
     {
         return TRUE;
     }
     if (other->get_type(other) != CERT_X509_OCSP_REQUEST)
     {
         return FALSE;
     }
     if (other->equals == (void*)equals)
     {   /* skip allocation if we have the same implementation */
         return chunk_equals(this->encoding, ((private_x509_ocsp_request_t*)other)->encoding);
     }
     if (!other->get_encoding(other, CERT_ASN1_DER, &encoding))
     {
         return FALSE;
     }
     equal = chunk_equals(this->encoding, encoding);
     free(encoding.ptr);
     return equal;
 }
METHOD (certificate_t , get_ref , certificate_t * , private_x509_ocsp_request_t * this)
Definition at line 443 of file x509_ocsp_request.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.interface.interface;
 }
METHOD (certificate_t , destroy , void , private_x509_ocsp_request_t * this)
Definition at line 450 of file x509_ocsp_request.c.
References cert, chunk_free(), destroy(), DESTROY_IF, encoding, free(), key, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         DESTROY_IF((certificate_t*)this->ca);
         DESTROY_IF(this->requestor);
         DESTROY_IF(this->cert);
         DESTROY_IF(this->key);
         this->candidates->destroy_offset(this->candidates, offsetof(certificate_t, destroy));
         chunk_free(&this->nonce);
         chunk_free(&this->encoding);
         free(this);
     }
 }
Variable Documentation
const chunk_t ASN1_nonce_oid static
Initial value:
= chunk_from_chars(
    0x06, 0x09,
          0x2B, 0x06,
                0x01, 0x05, 0x05, 0x07, 0x30, 0x01, 0x02
)
Definition at line 84 of file x509_ocsp_request.c.
const chunk_t ASN1_response_content static
Initial value:
= chunk_from_chars(
    0x04, 0x0D,
          0x30, 0x0B,
                0x06, 0x09,
                0x2B, 0x06,
                0x01, 0x05, 0x05, 0x07, 0x30, 0x01, 0x01
)
Definition at line 94 of file x509_ocsp_request.c.
const chunk_t ASN1_response_oid static
Initial value:
= chunk_from_chars(
    0x06, 0x09,
          0x2B, 0x06,
                0x01, 0x05, 0x05, 0x07, 0x30, 0x01, 0x04
)
Definition at line 89 of file x509_ocsp_request.c.