strongSwan: tnc_pdp_connections.c File Reference
tnc_pdp_connections.c File Reference
#include "tnc_pdp_connections.h"
#include <collections/linked_list.h>
#include <utils/debug.h>
#include <threading/rwlock.h>
#include <processing/jobs/callback_job.h>
#include <daemon.h>
Classes
struct private_tnc_pdp_connections_t
struct entry_t
Macros
#define DEFAULT_TIMEOUT 30
Typedefs
typedef struct
private_tnc_pdp_connections_t private_tnc_pdp_connections_t
typedef struct entry_t entry_t
Functions
static void free_entry (entry_t *this)
static bool equals_entry (entry_t *this, chunk_t nas_id, chunk_t user_name)
static void dbg_nas_user (chunk_t nas_id, chunk_t user_name, bool not, char *op)
static job_requeue_t check_timeouts (private_tnc_pdp_connections_t *this)
METHOD (tnc_pdp_connections_t, add, void, private_tnc_pdp_connections_t *this, chunk_t nas_id, chunk_t user_name, identification_t *peer, eap_method_t *method)
METHOD (tnc_pdp_connections_t, remove_, void, private_tnc_pdp_connections_t *this, chunk_t nas_id, chunk_t user_name)
METHOD (tnc_pdp_connections_t, get_state, eap_method_t *, private_tnc_pdp_connections_t *this, chunk_t nas_id, chunk_t user_name, ike_sa_t **ike_sa)
METHOD (tnc_pdp_connections_t, unlock, void, private_tnc_pdp_connections_t *this)
METHOD (tnc_pdp_connections_t, destroy, void, private_tnc_pdp_connections_t *this)
tnc_pdp_connections_t * tnc_pdp_connections_create (void)
Macro Definition Documentation
#define DEFAULT_TIMEOUT 30
Default PDP connection timeout, in s
Definition at line 28 of file tnc_pdp_connections.c.
Referenced by tnc_pdp_connections_create().
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 31 of file tnc_pdp_connections.c.
typedef struct private_tnc_pdp_connections_t private_tnc_pdp_connections_t
Definition at line 30 of file tnc_pdp_connections.c.
Function Documentation
static job_requeue_t check_timeouts (private_tnc_pdp_connections_t * this) static
Check if any connection has timed out
Definition at line 135 of file tnc_pdp_connections.c.
References linked_list_t::create_enumerator, entry_t::created, DBG1, DBG_CFG, enumerator_t::destroy, enumerator_t::enumerate, free_entry(), JOB_REQUEUE_NONE, list, lock, linked_list_t::remove_at, time_monotonic(), and spinlock_t::unlock.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     entry_t *entry;
     time_t now;
     now = time_monotonic(NULL);
     this->lock->write_lock(this->lock);
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->created + this->timeout <= now)
         {
             DBG1(DBG_CFG, "RADIUS connection timed out after %d seconds",
                  this->timeout);
             this->list->remove_at(this->list, enumerator);
             free_entry(entry);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return JOB_REQUEUE_NONE;
 }
static void dbg_nas_user (chunk_t nas_id, chunk_t user_name, bool not, char * op) static
Find a matching data entry
Definition at line 116 of file tnc_pdp_connections.c.
References DBG1, DBG_CFG, chunk_t::len, and chunk_t::ptr.
Referenced by METHOD().
 {
     if (nas_id.len)
     {
         DBG1(DBG_CFG, "%s RADIUS connection for user '%.*s' NAS '%.*s'",
                        not ? "could not find" : op, (int)user_name.len,
                        user_name.ptr, (int)nas_id.len, nas_id.ptr);
     }
     else
     {
         DBG1(DBG_CFG, "%s RADIUS connection for user '%.*s'",
                        not ? "could not find" : op, (int)user_name.len,
                        user_name.ptr);
     }
 }
static bool equals_entry (entry_t * this, chunk_t nas_id, chunk_t user_name) static
Find a matching data entry
Definition at line 105 of file tnc_pdp_connections.c.
References chunk_equals(), and chunk_t::ptr.
Referenced by METHOD().
 {
     bool no_nas_id = !this->nas_id.ptr && !nas_id.ptr;
     return (chunk_equals(this->nas_id, nas_id) || no_nas_id) &&
             chunk_equals(this->user_name, user_name);
 }
static void free_entry (entry_t * this) static
Free the memory allocated to a data entry
Definition at line 93 of file tnc_pdp_connections.c.
References free().
Referenced by check_timeouts(), and METHOD().
 {
     this->method->destroy(this->method);
     this->ike_sa->destroy(this->ike_sa);
     free(this->nas_id.ptr);
     free(this->user_name.ptr);
     free(this);
 }
METHOD (tnc_pdp_connections_t , add , void , private_tnc_pdp_connections_t * this, chunk_t nas_id, chunk_t user_name, identification_t * peer, eap_method_t * method)
Definition at line 161 of file tnc_pdp_connections.c.
References callback_job_create(), check_timeouts(), chunk_clone, linked_list_t::create_enumerator, entry_t::created, DBG1, DBG_CFG, dbg_nas_user(), enumerator_t::destroy, ike_sa_id_t::destroy, eap_method_t::destroy, ike_sa_t::destroy, enumerator_t::enumerate, equals_entry(), FALSE, found, entry_t::ike_sa, ike_sa_create(), ike_sa_id_create(), IKEV2, IKEV2_MAJOR_VERSION, INIT, linked_list_t::insert_last, lib, list, lock, entry_t::method, return_false(), scheduler_t::schedule_job_ms, library_t::scheduler, ike_sa_t::set_other_id, time_monotonic(), TRUE, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     ike_sa_id_t *ike_sa_id;
     ike_sa_t *ike_sa;
     bool found = FALSE;
     ike_sa_id = ike_sa_id_create(IKEV2_MAJOR_VERSION, 0, 0, FALSE);
     ike_sa = ike_sa_create(ike_sa_id, FALSE, IKEV2);
     ike_sa_id->destroy(ike_sa_id);
     ike_sa->set_other_id(ike_sa, peer);
     this->lock->read_lock(this->lock);
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (equals_entry(entry, nas_id, user_name))
         {
             found = TRUE;
             entry->method->destroy(entry->method);
             entry->ike_sa->destroy(entry->ike_sa);
             DBG1(DBG_CFG, "removed stale RADIUS connection");
             entry->method = method;
             entry->ike_sa = ike_sa;
             entry->created = time_monotonic(NULL);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     if (!found)
     {
         INIT(entry,
             .nas_id = chunk_clone(nas_id),
             .user_name = chunk_clone(user_name),
             .method = method,
             .ike_sa = ike_sa,
             .created = time_monotonic(NULL),
         );
         this->lock->write_lock(this->lock);
         this->list->insert_last(this->list, entry);
         this->lock->unlock(this->lock);
     }
     /* schedule timeout checking */
     lib->scheduler->schedule_job_ms(lib->scheduler,
                 (job_t*)callback_job_create((callback_job_cb_t)check_timeouts,
                     this, NULL, (callback_job_cancel_t)return_false),
                 this->timeout * 1000);
     dbg_nas_user(nas_id, user_name, FALSE, "created");
 }
METHOD (tnc_pdp_connections_t , remove_ , void , private_tnc_pdp_connections_t * this, chunk_t nas_id, chunk_t user_name)
Definition at line 218 of file tnc_pdp_connections.c.
References linked_list_t::create_enumerator, dbg_nas_user(), enumerator_t::destroy, enumerator_t::enumerate, equals_entry(), FALSE, free_entry(), list, lock, linked_list_t::remove_at, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     this->lock->write_lock(this->lock);
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (equals_entry(entry, nas_id, user_name))
         {
             free_entry(entry);
             this->list->remove_at(this->list, enumerator);
             dbg_nas_user(nas_id, user_name, FALSE, "removed");
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
 }
METHOD (tnc_pdp_connections_t , get_state , eap_method_t * , private_tnc_pdp_connections_t * this, chunk_t nas_id, chunk_t user_name, ike_sa_t ** ike_sa)
Definition at line 240 of file tnc_pdp_connections.c.
References linked_list_t::create_enumerator, dbg_nas_user(), enumerator_t::destroy, enumerator_t::enumerate, equals_entry(), found, entry_t::ike_sa, list, lock, entry_t::method, and spinlock_t::unlock.
 {
     enumerator_t *enumerator;
     entry_t *entry;
     eap_method_t *found = NULL;
     this->lock->read_lock(this->lock);
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (equals_entry(entry, nas_id, user_name))
         {
             found = entry->method;
             *ike_sa = entry->ike_sa;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         this->lock->unlock(this->lock);
     }
     dbg_nas_user(nas_id, user_name, !found, "found");
     return found;
 }
METHOD (tnc_pdp_connections_t , unlock , void , private_tnc_pdp_connections_t * this)
Definition at line 269 of file tnc_pdp_connections.c.
References lock, and spinlock_t::unlock.
 {
     this->lock->unlock(this->lock);
 }
METHOD (tnc_pdp_connections_t , destroy , void , private_tnc_pdp_connections_t * this)
Definition at line 275 of file tnc_pdp_connections.c.
References spinlock_t::destroy, linked_list_t::destroy_function, free(), free_entry(), list, and lock.
 {
     this->lock->destroy(this->lock);
     this->list->destroy_function(this->list, (void*)free_entry);
     free(this);
 }