strongSwan: linked_list_t Struct Reference
linked_list_t Struct Reference
linked_list
#include "linked_list.h"
Public Attributes
int(* get_count)(linked_list_t *this)
enumerator_t *(* create_enumerator)(linked_list_t *this)
void(* reset_enumerator)(linked_list_t *this, enumerator_t *enumerator)
void(* insert_first)(linked_list_t *this, void *item)
status_t(* remove_first)(linked_list_t *this, void **item)
void(* insert_before)(linked_list_t *this, enumerator_t *enumerator, void *item)
void(* remove_at)(linked_list_t *this, enumerator_t *enumerator)
int(* remove)(linked_list_t *this, void *item, bool(*compare)(void *, void *))
status_t(* get_first)(linked_list_t *this, void **item)
void(* insert_last)(linked_list_t *this, void *item)
status_t(* remove_last)(linked_list_t *this, void **item)
status_t(* get_last)(linked_list_t *this, void **item)
status_t(* find_first)(linked_list_t *this, linked_list_match_t match, void **item,...)
void(* invoke_offset)(linked_list_t *this, size_t offset,...)
void(* invoke_function)(linked_list_t *this, linked_list_invoke_t function,...)
linked_list_t *(* clone_offset)(linked_list_t *this, size_t offset)
void(* destroy)(linked_list_t *this)
void(* destroy_offset)(linked_list_t *this, size_t offset)
void(* destroy_function)(linked_list_t *this, void(*)(void *))
Detailed Description
Class implementing a double linked list.
General purpose linked list. This list is not synchronized.
Definition at line 54 of file linked_list.h.
Member Data Documentation
linked_list_t*(* linked_list_t::clone_offset)(linked_list_t *this, size_t offset)
Clones a list and its objects using the objects' clone method.
Parameters
offset offset ot the objects clone function
Returns
cloned list
Definition at line 218 of file linked_list.h.
Referenced by build_reply(), build_set(), check_list_create(), mediation_job_create(), METHOD(), select_and_install(), and START_TEST().
enumerator_t*(* linked_list_t::create_enumerator)(linked_list_t *this)
Create an enumerator over the list.
Note
The enumerator's position is invalid before the first call to enumerate().
Returns
enumerator over list items
Definition at line 71 of file linked_list.h.
Referenced by add_cdps(), add_endpoints_to_message(), add_entry(), add_groups_from_list(), address2entry(), array_from_ts_list(), assign_migrated_vip(), auth_cfg_equal(), build_pairs(), build_payloads(), build_request(), CALLBACK(), check_constraints(), check_policy_constraints(), check_timeouts(), child_exited(), copy_certs(), create_enumerator(), create_iface_enumerator(), create_inner(), create_inner_cdp(), create_inner_cdp_hashandurl(), create_sets_enumerator(), create_unique_cert_list(), eap_radius_create_client(), find_addr(), generate(), get_interface_address(), get_page(), get_proposals(), get_proxy_addr(), get_route(), get_transport_nat_ts(), get_triggered_pair(), get_ts_match(), has_host_family(), has_no_any_policy(), has_no_policy_mapping(), has_owner(), has_policy_chain(), have_vips_from_pool(), identity_attribute(), init_address_list(), initiate_mediated(), insert_pair_by_priority(), install_shunt_policy(), is_attribute_selected(), is_policy_valid(), list_uris(), load_features(), load_registered(), log_authority_data(), log_peer_data(), match(), METHOD(), migrate_child_tasks(), order_payloads(), parse_directoryName(), print_all(), print_checklist(), process_addr(), process_coa(), process_disconnect(), proposal_printf_hook(), proposal_substructure_create_from_proposals_v1(), prune_pairs(), quit(), raise_policy_cfg(), register_logger(), register_peer(), rekey_children(), remove_addr(), remove_connected_peers(), remove_from_list(), remove_specific(), resolve(), sa_payload_create_from_proposals_v2(), shared_entry_equals(), sign_crl(), start_all_guests(), START_TEST(), stroke_list_acerts(), stroke_list_certs(), stroke_list_crls(), stroke_list_ocsp(), stroke_list_pgp(), stroke_list_pubkeys(), tnc_imv_recommendations_create(), traffic_selector_printf_hook(), ts_list_is_host(), ts_payload_create_from_traffic_selectors(), uninstall_shunt_policy(), unregister_features(), unregister_logger(), unregister_peer(), update_addrs(), update_checklist_state(), verify_key_values(), verify_sections(), write_networks(), x509_build_crlDistributionPoints(), x509_build_subjectAltNames(), x509_cert_gen(), x509_crl_gen(), and x509_pkcs10_gen().
void(* linked_list_t::destroy)(linked_list_t *this)
Destroys a linked_list object.
Definition at line 223 of file linked_list.h.
Referenced by acert(), add_exclude(), add_include(), bridge_each(), bridge_each_iface(), build_reply(), build_request(), build_set(), CALLBACK(), check_policy_constraints(), cleanup(), create_cert_ext(), create_enumerator(), delete_child(), entry_destroy(), find_certificates(), get_proxy_addr(), get_ts_if_nat_transport(), guest_each_iface(), handle_preferred_eap_types(), iface_each_addr(), install(), install_shunt_policy(), issue(), list_plugins(), load_authorities_cfg(), load_conns_cfg(), load_pools_cfg(), log_child_sa(), log_children(), METHOD(), narrow_responder_post(), narrow_ts(), order_payloads(), parse_directoryName(), peer_enum_filter_destroy(), plugin_entry_destroy(), policy_entry_destroy(), rekey_segment(), remove_exclude(), remove_include(), sa_payload_create_from_proposal_v1(), select_and_install(), select_child_cfg(), select_ts(), self(), START_TEARDOWN(), START_TEST(), status(), uninstall_shunt_policy(), unregister_feature(), update_addrs(), update_children(), verify_key_values(), verify_sections(), wrap_payloads(), write_childend(), and x509_parse_crlDistributionPoints().
void(* linked_list_t::destroy_function)(linked_list_t *this, void(*)(void *))
Destroys a list and its contents using a a cleanup function.
If a linked list and its contents should get destroyed using a specific cleanup function, use destroy_function. This is useful when the list contains malloc()-ed blocks which should get freed, e.g.: list->destroy_function(list, free);
Parameters
function function to call on each object
Definition at line 247 of file linked_list.h.
Referenced by get_route(), handle_event(), issue(), main(), METHOD(), print_all(), rekey_children(), remove_queue(), self(), sign_crl(), vendor_entry_destroy(), and vici_free_res().
void(* linked_list_t::destroy_offset)(linked_list_t *this, size_t offset)
Destroys a list and its objects using the destructor.
If a linked list and the contained objects should be destroyed, use destroy_offset. The supplied offset specifies the destructor to call on each object. The offset may be calculated using the offsetof macro, e.g.: list->destroy_offset(list, offsetof(object_t, destroy));
Parameters
offset offset of the objects destructor
Definition at line 235 of file linked_list.h.
Referenced by add_local_certs(), build_payloads(), CALLBACK(), create_cert(), destroy_address_list(), entry_destroy(), exit_scepclient(), free_child_data(), free_peer_data(), get_proxy_addr(), get_ts_match(), id_enumerator_cleanup(), install(), install_shunt_policy(), issue(), list(), load_shared(), METHOD(), narrow_ts(), process_auth_request(), process_child_add(), process_coa(), process_disconnect(), process_payloads(), raise_alerts(), raise_policy_cfg(), req(), select_and_install(), select_ts(), self(), shared_entry_destroy(), uninstall_shunt_policy(), and verify_list().
status_t(* linked_list_t::find_first)(linked_list_t *this, linked_list_match_t match, void **item,...)
Find the first matching element in the list.
The first object passed to the match function is the current list item, followed by the user supplied data. If the supplied function returns TRUE this function returns SUCCESS, and the current object is returned in the third parameter, otherwise, the next item is checked.
If match is NULL, *item and the current object are compared.
Warning
Only use pointers as user supplied data.
Parameters
match comparison function to call on each object, or NULL
item the list item, if found
... user data to supply to match function (limited to 5 arguments)
Returns
SUCCESS if found, NOT_FOUND otherwise
Definition at line 183 of file linked_list.h.
Referenced by add_policy_internal(), endpoints_contain(), get_best_valid_pair(), get_logger_entry(), get_pair_by_hosts(), get_pair_by_id(), list_plugins(), loadable_feature_equals(), loadable_feature_matches(), loaded_feature_matches(), METHOD(), purge_plugins(), put_connected_peers(), sender(), START_TEST(), and unique_check().
int(* linked_list_t::get_count)(linked_list_t *this)
Gets the count of items in the list.
Returns
number of items in list
Definition at line 61 of file linked_list.h.
Referenced by add_cdps(), auth_cfg_equal(), build_request(), CALLBACK(), create_sets_enumerator(), generate(), get_dynamic_hosts(), get_ts_if_nat_transport(), get_ts_match(), identity_attribute(), install(), log_peer_data(), METHOD(), process_coa(), process_disconnect(), process_request(), pts_ima_bios_list_create(), pts_ima_event_list_create(), put_or_destroy_entry(), remove_connected_peers(), remove_if_empty(), sa_payload_create_from_proposals_v1(), select_and_install(), send_packets(), shared_entry_equals(), START_SETUP(), START_TEST(), test_clone(), unregister_feature(), unregister_peer(), verify_key_values(), verify_sections(), x509_build_crlDistributionPoints(), and x509_build_subjectAltNames().
status_t(* linked_list_t::get_first)(linked_list_t *this, void **item)
Returns the value of the first list item without removing it.
Parameters
item returned value of first item
Returns
SUCCESS, NOT_FOUND if list is empty
Definition at line 140 of file linked_list.h.
Referenced by get_route(), METHOD(), process_acquire(), select_ts(), START_SETUP(), START_TEST(), unregister_feature(), and unregister_logger().
status_t(* linked_list_t::get_last)(linked_list_t *this, void **item)
Returns the value of the last list item without removing it.
Parameters
item returned value of last item
Returns
SUCCESS, NOT_FOUND if list is empty
Definition at line 163 of file linked_list.h.
Referenced by START_SETUP(), and START_TEST().
void(* linked_list_t::insert_before)(linked_list_t *this, enumerator_t *enumerator, void *item)
Inserts a new item before the item the enumerator currently points to.
If this method is called before starting the enumeration the item is inserted first. If it is called after all items have been enumerated the item is inserted last. This is helpful when inserting items into a sorted list.
Note
The position of the enumerator is not changed.
Parameters
enumerator enumerator with position
item item value to insert in list
Definition at line 108 of file linked_list.h.
Referenced by add_entry(), create_unique_cert_list(), get_route(), insert_pair_by_priority(), METHOD(), register_logger(), and START_TEST().
void(* linked_list_t::insert_first)(linked_list_t *this, void *item)
Inserts a new item at the beginning of the list.
Parameters
item item value to insert in list
Definition at line 85 of file linked_list.h.
Referenced by check_policy_constraints(), METHOD(), order_payloads(), and START_TEST().
void(* linked_list_t::insert_last)(linked_list_t *this, void *item)
Inserts a new item at the end of the list.
Parameters
item value to insert into list
Definition at line 147 of file linked_list.h.
Referenced by acert(), add_addr(), add_attr(), add_cdps(), add_local_certs(), add_matching_ike_sas(), add_revoked(), add_ts(), bridge_each(), bridge_each_iface(), build_request(), CALLBACK(), check_policy_constraints(), collect_tags(), compile_address_list(), copy_certs(), create_cert(), create_cert_ext(), create_page(), enumerator_destroy(), find_certificates(), get_dynamic_hosts(), get_identity_attribute(), get_port_list(), get_transport_nat_ts(), guest_each_iface(), handle_preferred_eap_types(), iface_each_addr(), ike2queue(), init_address_list(), insert_sorted(), issue(), linked_list_create_from_enumerator(), linked_list_create_with_items(), list(), load_hooks(), load_loggers(), load_proposals(), load_shared(), main(), METHOD(), migrate_child_tasks(), narrow_pre(), narrow_responder_post(), narrow_ts(), parse_addresses(), parse_generalNames_ext(), parse_list(), parse_proposal(), parse_selector(), parse_subnets(), print_all(), process_addr(), process_child_add(), process_request(), process_response(), pts_ima_bios_list_create(), pts_ima_event_list_create(), put(), put_connected_peers(), queue_triggered_check(), radius2queue(), read_revoked(), read_swid_tag_ids(), read_swid_tags(), register_features(), register_peer(), rekey_children(), rekey_segment(), repopulate_iface(), req(), sa_payload_create_from_proposal_v1(), sa_payload_create_from_proposals_v1(), self(), sign_crl(), START_TEST(), tnccs_msg_create_from_node(), tnccs_reason_strings_msg_create_from_node(), tnccs_recommendation_msg_create_from_node(), unbound_response_create_frm_libub_response(), unique_check(), update_addrs(), update_children(), vici_parse_name(), vici_parse_value_str(), wrap_payloads(), x509_cert_gen(), x509_crl_gen(), x509_ocsp_request_gen(), x509_parse_generalNames(), and x509_pkcs10_gen().
void(* linked_list_t::invoke_function)(linked_list_t *this, linked_list_invoke_t function,...)
Invoke a function on all of the contained objects.
Warning
Only use pointers as user supplied data.
Parameters
function offset of the method to invoke on objects
... user data to supply to called function (limited to 5 arguments)
Definition at line 210 of file linked_list.h.
Referenced by METHOD(), policy_entry_destroy(), process_link(), and START_TEST().
void(* linked_list_t::invoke_offset)(linked_list_t *this, size_t offset,...)
Invoke a method on all of the contained objects.
If a linked list contains objects with function pointers, invoke() can call a method on each of the objects. The method is specified by an offset of the function pointer, which can be evalutated at compile time using the offsetof macro, e.g.: list->invoke(list, offsetof(object_t, method));
Warning
Only use pointers as user supplied data.
Parameters
offset offset of the method to invoke on objects
... user data to supply to called function (limited to 5 arguments)
Definition at line 200 of file linked_list.h.
Referenced by METHOD(), and START_TEST().
int(* linked_list_t::remove)(linked_list_t *this, void *item, bool(*compare)(void *, void *))
Remove items from the list matching the given item.
If a compare function is given, it is called for each item, with the first parameter being the current list item and the second parameter being the supplied item. Return TRUE from the compare function to remove the item, return FALSE to keep it in the list.
If compare is NULL, comparison is done by pointers.
Parameters
item item to remove/pass to comparator
compare compare function, or NULL
Returns
number of removed items
Definition at line 132 of file linked_list.h.
Referenced by delete_guest(), get_logger_entry(), METHOD(), process_addr(), remove_addr(), START_TEST(), unload_features(), unregister_feature(), and unregister_logger().
void(* linked_list_t::remove_at)(linked_list_t *this, enumerator_t *enumerator)
Remove an item from the list where the enumerator points to.
Parameters
enumerator enumerator with position
Definition at line 116 of file linked_list.h.
Referenced by assign_migrated_vip(), CALLBACK(), check_timeouts(), copy_certs(), enumerator_destroy(), get_proposals(), get_triggered_pair(), METHOD(), migrate_child_tasks(), order_payloads(), process_addr(), prune_pairs(), remove_addr(), remove_connected_peers(), remove_from_list(), remove_specific(), START_TEST(), unregister_features(), unregister_logger(), unregister_peer(), update_addrs(), verify_key_values(), and verify_sections().
status_t(* linked_list_t::remove_first)(linked_list_t *this, void **item)
Removes the first item in the list and returns its value.
Parameters
item returned value of first item, or NULL
Returns
SUCCESS, or NOT_FOUND if list is empty
Definition at line 93 of file linked_list.h.
Referenced by add_exclude(), add_include(), bridge_each(), bridge_each_iface(), CALLBACK(), find_certificates(), guest_each_iface(), iface_each_addr(), insert_sorted(), list(), load_authorities_cfg(), load_conns_cfg(), load_pools_cfg(), METHOD(), narrow_initiator(), narrow_pre(), narrow_responder_post(), narrow_ts(), process_auth_request(), remove_attr(), remove_exclude(), remove_first(), remove_include(), select_method(), send_packets(), START_TEST(), test_clone(), update_addrs(), and wrap_payloads().
status_t(* linked_list_t::remove_last)(linked_list_t *this, void **item)
Removes the last item in the list and returns its value.
Parameters
item returned value of last item, or NULL
Returns
SUCCESS, NOT_FOUND if list is empty
Definition at line 155 of file linked_list.h.
Referenced by add_cdps(), cleanup(), flush_ts_list(), handle_preferred_eap_types(), METHOD(), order_payloads(), peer_enum_filter_destroy(), queue2ike(), queue2radius(), rekey_segment(), repopulate_iface(), and START_TEST().
void(* linked_list_t::reset_enumerator)(linked_list_t *this, enumerator_t *enumerator)
Resets the enumerator's current position to the beginning of the list.
Parameters
enumerator enumerator to reset
Definition at line 78 of file linked_list.h.
Referenced by METHOD(), prune_pairs(), and START_TEST().
The documentation for this struct was generated from the following file:
linked_list.h