strongSwan: chapoly_aead.c File Reference
chapoly_aead.c File Reference
#include "chapoly_aead.h"
#include "chapoly_drv.h"
#include <crypto/iv/iv_gen_seq.h>
Classes
struct private_chapoly_aead_t
Macros
#define P_MAX 247877906880
Typedefs
typedef struct
private_chapoly_aead_t private_chapoly_aead_t
Functions
static bool poly_update_padded (private_chapoly_aead_t *this, u_char *in, size_t len)
static bool poly_head (private_chapoly_aead_t *this, u_char *assoc, size_t len)
static bool poly_tail (private_chapoly_aead_t *this, size_t alen, size_t clen)
static bool do_encrypt (private_chapoly_aead_t *this, size_t len, u_char *data, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
static bool do_decrypt (private_chapoly_aead_t *this, size_t len, u_char *data, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
METHOD (aead_t, encrypt, bool, private_chapoly_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encr)
METHOD (aead_t, decrypt, bool, private_chapoly_aead_t *this, chunk_t encr, chunk_t assoc, chunk_t iv, chunk_t *plain)
METHOD (aead_t, get_block_size, size_t, private_chapoly_aead_t *this)
METHOD (aead_t, get_icv_size, size_t, private_chapoly_aead_t *this)
METHOD (aead_t, get_iv_size, size_t, private_chapoly_aead_t *this)
METHOD (aead_t, get_iv_gen, iv_gen_t *, private_chapoly_aead_t *this)
METHOD (aead_t, get_key_size, size_t, private_chapoly_aead_t *this)
METHOD (aead_t, set_key, bool, private_chapoly_aead_t *this, chunk_t key)
METHOD (aead_t, destroy, void, private_chapoly_aead_t *this)
chapoly_aead_t * chapoly_aead_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Macro Definition Documentation
#define P_MAX 247877906880
Definition at line 22 of file chapoly_aead.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_chapoly_aead_t private_chapoly_aead_t
Definition at line 24 of file chapoly_aead.c.
Function Documentation
static bool do_decrypt (private_chapoly_aead_t * this, size_t len, u_char * data, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
Perform ChaCha20 decryption inline and generate an ICV tag
Definition at line 145 of file chapoly_aead.c.
References CHACHA_BLOCK_SIZE, FALSE, memxor(), POLY_BLOCK_SIZE, poly_head(), poly_tail(), and poly_update_padded().
Referenced by METHOD().
 {
     u_int blocks, rem, prem;
     if (!this->drv->init(this->drv, iv) ||
         !poly_head(this, assoc, alen))
     {
         return FALSE;
     }
     blocks = len / CHACHA_BLOCK_SIZE;
     if (!this->drv->decrypt(this->drv, data, blocks))
     {
         return FALSE;
     }
     rem = len % CHACHA_BLOCK_SIZE;
     if (rem)
     {
         u_char stream[CHACHA_BLOCK_SIZE];
         data += blocks * CHACHA_BLOCK_SIZE;
         blocks = rem / POLY_BLOCK_SIZE;
         if (!this->drv->poly(this->drv, data, blocks))
         {
             return FALSE;
         }
         prem = rem % POLY_BLOCK_SIZE;
         if (prem)
         {
             poly_update_padded(this, data + blocks * POLY_BLOCK_SIZE, prem);
         }
         if (!this->drv->chacha(this->drv, stream))
         {
             return FALSE;
         }
         memxor(data, stream, rem);
     }
     return poly_tail(this, alen, len) &&
            this->drv->finish(this->drv, icv);
 }
static bool do_encrypt (private_chapoly_aead_t * this, size_t len, u_char * data, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
Perform ChaCha20 encryption inline and generate an ICV tag
Definition at line 100 of file chapoly_aead.c.
References CHACHA_BLOCK_SIZE, FALSE, memxor(), POLY_BLOCK_SIZE, poly_head(), poly_tail(), and poly_update_padded().
Referenced by METHOD().
 {
     u_int blocks, rem, prem;
     if (!this->drv->init(this->drv, iv) ||
         !poly_head(this, assoc, alen))
     {
         return FALSE;
     }
     blocks = len / CHACHA_BLOCK_SIZE;
     if (!this->drv->encrypt(this->drv, data, blocks))
     {
         return FALSE;
     }
     rem = len % CHACHA_BLOCK_SIZE;
     if (rem)
     {
         u_char stream[CHACHA_BLOCK_SIZE];
         data += blocks * CHACHA_BLOCK_SIZE;
         if (!this->drv->chacha(this->drv, stream))
         {
             return FALSE;
         }
         memxor(data, stream, rem);
         blocks = rem / POLY_BLOCK_SIZE;
         if (!this->drv->poly(this->drv, data, blocks))
         {
             return FALSE;
         }
         prem = rem % POLY_BLOCK_SIZE;
         if (prem)
         {
             poly_update_padded(this, data + blocks * POLY_BLOCK_SIZE, prem);
         }
     }
     return poly_tail(this, alen, len) &&
            this->drv->finish(this->drv, icv);
 }
METHOD (aead_t , encrypt , bool , private_chapoly_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t * encr)
Definition at line 187 of file chapoly_aead.c.
References CHACHA_IV_SIZE, chunk_alloc, do_encrypt(), FALSE, chunk_t::len, memcpy, out, P_MAX, POLY_ICV_SIZE, chunk_t::ptr, and TRUE.
 {
     u_char *out;
     if (sizeof(plain.len) > sizeof(u_int32_t) && plain.len > P_MAX)
     {
         return FALSE;
     }
     if (iv.len != CHACHA_IV_SIZE)
     {
         return FALSE;
     }
     out = plain.ptr;
     if (encr)
     {
         *encr = chunk_alloc(plain.len + POLY_ICV_SIZE);
         out = encr->ptr;
         memcpy(out, plain.ptr, plain.len);
     }
     do_encrypt(this, plain.len, out, iv.ptr, assoc.len, assoc.ptr,
                out + plain.len);
     return TRUE;
 }
METHOD (aead_t , decrypt , bool , private_chapoly_aead_t * this, chunk_t encr, chunk_t assoc, chunk_t iv, chunk_t * plain)
Definition at line 213 of file chapoly_aead.c.
References CHACHA_IV_SIZE, chunk_alloc, do_decrypt(), FALSE, chunk_t::len, memcpy, memeq_const(), out, P_MAX, POLY_ICV_SIZE, and chunk_t::ptr.
 {
     u_char *out, icv[POLY_ICV_SIZE];
     if (iv.len != CHACHA_IV_SIZE || encr.len < POLY_ICV_SIZE)
     {
         return FALSE;
     }
     encr.len -= POLY_ICV_SIZE;
     if (sizeof(encr.len) > sizeof(u_int32_t) && encr.len > P_MAX)
     {
         return FALSE;
     }
     out = encr.ptr;
     if (plain)
     {
         *plain = chunk_alloc(encr.len);
         out = plain->ptr;
         memcpy(out, encr.ptr, encr.len);
     }
     do_decrypt(this, encr.len, out, iv.ptr, assoc.len, assoc.ptr, icv);
     return memeq_const(icv, encr.ptr + encr.len, POLY_ICV_SIZE);
 }
METHOD (aead_t , get_block_size , size_t , private_chapoly_aead_t * this)
Definition at line 238 of file chapoly_aead.c.
 {
     return 1;
 }
METHOD (aead_t , get_icv_size , size_t , private_chapoly_aead_t * this)
Definition at line 244 of file chapoly_aead.c.
References POLY_ICV_SIZE.
 {
     return POLY_ICV_SIZE;
 }
METHOD (aead_t , get_iv_size , size_t , private_chapoly_aead_t * this)
Definition at line 250 of file chapoly_aead.c.
References CHACHA_IV_SIZE.
 {
     return CHACHA_IV_SIZE;
 }
METHOD (aead_t , get_iv_gen , iv_gen_t * , private_chapoly_aead_t * this)
Definition at line 256 of file chapoly_aead.c.
 {
     return this->iv_gen;
 }
METHOD (aead_t , get_key_size , size_t , private_chapoly_aead_t * this)
Definition at line 262 of file chapoly_aead.c.
References CHACHA_KEY_SIZE, and CHACHA_SALT_SIZE.
 {
     return CHACHA_KEY_SIZE + CHACHA_SALT_SIZE;
 }
METHOD (aead_t , set_key , bool , private_chapoly_aead_t * this, chunk_t key)
Definition at line 268 of file chapoly_aead.c.
References CHACHA_KEY_SIZE, CHACHA_SALT_SIZE, FALSE, chunk_t::len, and chunk_t::ptr.
 {
     if (key.len != CHACHA_KEY_SIZE + CHACHA_SALT_SIZE)
     {
         return FALSE;
     }
     return this->drv->set_key(this->drv, "expand 32-byte k",
                               key.ptr, key.ptr + CHACHA_KEY_SIZE);
 }
METHOD (aead_t , destroy , void , private_chapoly_aead_t * this)
Definition at line 279 of file chapoly_aead.c.
References free().
 {
     this->drv->destroy(this->drv);
     this->iv_gen->destroy(this->iv_gen);
     free(this);
 }
static bool poly_head (private_chapoly_aead_t * this, u_char * assoc, size_t len) static
Include associated data with padding to ICV
Definition at line 64 of file chapoly_aead.c.
References FALSE, POLY_BLOCK_SIZE, poly_update_padded(), and TRUE.
Referenced by do_decrypt(), and do_encrypt().
 {
     u_int blocks, rem;
     blocks = len / POLY_BLOCK_SIZE;
     rem = len % POLY_BLOCK_SIZE;
     if (!this->drv->poly(this->drv, assoc, blocks))
     {
         return FALSE;
     }
     if (rem)
     {
         return poly_update_padded(this, assoc + blocks * POLY_BLOCK_SIZE, rem);
     }
     return TRUE;
 }
static bool poly_tail (private_chapoly_aead_t * this, size_t alen, size_t clen) static
Include length fields to ICV
Definition at line 84 of file chapoly_aead.c.
References b.
Referenced by do_decrypt(), and do_encrypt().
 {
     struct {
         u_int64_t alen;
         u_int64_t clen;
     } b;
     b.alen = htole64(alen);
     b.clen = htole64(clen);
     return this->drv->poly(this->drv, (u_char*)&b, 1);
 }
static bool poly_update_padded (private_chapoly_aead_t * this, u_char * in, size_t len) static
Include a partial block to ICV by padding it with zero bytes
Definition at line 50 of file chapoly_aead.c.
References b, memcpy, memset, and POLY_BLOCK_SIZE.
Referenced by do_decrypt(), do_encrypt(), and poly_head().
 {
     u_char b[POLY_BLOCK_SIZE];
     memset(b, 0, sizeof(b));
     memcpy(b, in, len);
     return this->drv->poly(this->drv, b, 1);
 }