strongSwan: mac_signer
mac_signer
crypto
Typedefs
typedef struct mac_signer_t mac_signer_t
Functions
signer_t * mac_signer_create (mac_t *mac, size_t len)
Detailed Description
Typedef Documentation
typedef struct mac_signer_t mac_signer_t
Definition at line 24 of file mac_signer.h.
Function Documentation
signer_t* mac_signer_create (mac_t * mac, size_t len)
Creates an implementation of the signer_t interface using the provided mac_t implementation and truncation length.
Note
len will be set to mac_t.get_mac_size() if it is greater than that.
Parameters
mac mac_t implementation
len length of resulting signature
Returns
mac_signer_t
Definition at line 119 of file mac_signer.c.
References mac_t::get_mac_size, INIT, and min.
Referenced by aesni_cmac_signer_create(), aesni_xcbc_signer_create(), cmac_signer_create(), hmac_signer_create(), openssl_hmac_signer_create(), and xcbc_signer_create().
 {
     private_signer_t *this;
     INIT(this,
         .public = {
             .get_signature = _get_signature,
             .allocate_signature = _allocate_signature,
             .verify_signature = _verify_signature,
             .get_block_size = _get_block_size,
             .get_key_size = _get_key_size,
             .set_key = _set_key,
             .destroy = _destroy,
         },
         .truncation = min(len, mac->get_mac_size(mac)),
         .mac = mac,
     );
     return &this->public;
 }