strongSwan: seg_contract
seg_contract
seg
Classes
struct seg_contract_t
Macros
#define SEG_CONTRACT_MAX_SIZE_VALUE 0xffffffff
#define SEG_CONTRACT_NO_FRAGMENTATION SEG_CONTRACT_MAX_SIZE_VALUE
Typedefs
typedef struct seg_contract_t seg_contract_t
Functions
seg_contract_t * seg_contract_create (pen_type_t msg_type, uint32_t max_attr_size, uint32_t max_seg_size, bool is_issuer, TNC_UInt32 issuer_id, bool is_imc)
Detailed Description
Macro Definition Documentation
#define SEG_CONTRACT_MAX_SIZE_VALUE 0xffffffff
Definition at line 33 of file seg_contract.h.
Referenced by METHOD(), seg_contract_create(), and START_TEST().
#define SEG_CONTRACT_NO_FRAGMENTATION SEG_CONTRACT_MAX_SIZE_VALUE
Definition at line 34 of file seg_contract.h.
Referenced by METHOD().
Typedef Documentation
typedef struct seg_contract_t seg_contract_t
Definition at line 24 of file seg_contract.h.
Function Documentation
seg_contract_t* seg_contract_create (pen_type_t msg_type, uint32_t max_attr_size, uint32_t max_seg_size, bool is_issuer, TNC_UInt32 issuer_id, bool is_imc)
Create a PA-TNC attribute segmentation contract
Parameters
msg_type PA-TNC message type
max_attr_size Maximum PA-TNC attribute size in octets
max_seg_size Maximum PA-TNC attribute segment size in octets
is_issuer TRUE if issuer of the contract
issuer_id IMC or IMV ID of issuer
is_imc TRUE if IMC, FALSE if IMV
See header
Definition at line 439 of file seg_contract.c.
References INIT, linked_list_create(), max_seg_size, SEG_CONTRACT_MAX_SIZE_VALUE, TNC_IMCID_ANY, and TNC_IMVID_ANY.
Referenced by METHOD(), START_TEST(), and TNC_IMC_BeginHandshake().
 {
     private_seg_contract_t *this;
     INIT(this,
         .public = {
             .get_msg_type = _get_msg_type,
             .set_max_size = _set_max_size,
             .get_max_size = _get_max_size,
             .check_size = _check_size,
             .first_segment = _first_segment,
             .next_segment = _next_segment,
             .add_segment = _add_segment,
             .is_issuer = _is_issuer,
             .is_null = _is_null,
             .set_responder = _set_responder,
             .get_responder = _get_responder,
             .get_issuer = _get_issuer,
             .clone = _clone_,
             .get_info_string = _get_info_string,
             .destroy = _destroy,
         },
         .msg_type = msg_type,
         .max_attr_size = max_attr_size,
         .max_seg_size = max_seg_size,
         .seg_envs = linked_list_create(),
         .is_issuer = is_issuer,
         .issuer_id = issuer_id,
         .responder_id = is_imc ? TNC_IMVID_ANY : TNC_IMCID_ANY,
         .is_imc = is_imc,
         .is_null = max_attr_size == SEG_CONTRACT_MAX_SIZE_VALUE &&
                    max_seg_size  == SEG_CONTRACT_MAX_SIZE_VALUE,
     );
     return &this->public;
 }