strongSwan: scheduler.c File Reference
scheduler.c File Reference
#include <stdlib.h>
#include "scheduler.h"
#include <utils/debug.h>
#include <processing/processor.h>
#include <processing/jobs/callback_job.h>
#include <threading/thread.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
Classes
struct event_t
struct private_scheduler_t
Macros
#define HEAP_SIZE_DEFAULT 64
Typedefs
typedef struct event_t event_t
typedef struct private_scheduler_t private_scheduler_t
Functions
static void event_destroy (event_t *event)
static int timeval_cmp (timeval_t *a, timeval_t *b)
static event_t * peek_event (private_scheduler_t *this)
static event_t * remove_event (private_scheduler_t *this)
static job_requeue_t schedule (private_scheduler_t *this)
METHOD (scheduler_t, get_job_load, u_int, private_scheduler_t *this)
METHOD (scheduler_t, schedule_job_tv, void, private_scheduler_t *this, job_t *job, timeval_t tv)
METHOD (scheduler_t, schedule_job, void, private_scheduler_t *this, job_t *job, u_int32_t s)
METHOD (scheduler_t, schedule_job_ms, void, private_scheduler_t *this, job_t *job, u_int32_t ms)
METHOD (scheduler_t, flush, void, private_scheduler_t *this)
METHOD (scheduler_t, destroy, void, private_scheduler_t *this)
scheduler_t * scheduler_create ()
Macro Definition Documentation
#define HEAP_SIZE_DEFAULT 64
Definition at line 30 of file scheduler.c.
Referenced by scheduler_create().
Typedef Documentation
typedef struct event_t event_t
Definition at line 32 of file scheduler.c.
typedef struct private_scheduler_t private_scheduler_t
Definition at line 58 of file scheduler.c.
Function Documentation
static void event_destroy (event_t * event) static
destroy an event and its job
Definition at line 52 of file scheduler.c.
References free(), and event_t::job.
Referenced by METHOD().
 {
     event->job->destroy(event->job);
     free(event);
 }
METHOD (scheduler_t , get_job_load , u_int , private_scheduler_t * this)
Definition at line 230 of file scheduler.c.
References count, mutex_t::lock, mutex, and mutex_t::unlock.
 {
     int count;
     this->mutex->lock(this->mutex);
     count = this->event_count;
     this->mutex->unlock(this->mutex);
     return count;
 }
METHOD (scheduler_t , schedule_job_tv , void , private_scheduler_t * this, job_t * job, timeval_t tv)
Definition at line 240 of file scheduler.c.
References condvar, event, JOB_STATUS_QUEUED, mutex_t::lock, malloc_thing, mutex, condvar_t::signal, job_t::status, event_t::time, timeval_cmp(), and mutex_t::unlock.
 {
     event_t *event;
     u_int position;
     event = malloc_thing(event_t);
     event->job = job;
     event->job->status = JOB_STATUS_QUEUED;
     event->time = tv;
     this->mutex->lock(this->mutex);
     this->event_count++;
     if (this->event_count > this->heap_size)
     {
         /* double the size of the heap */
         this->heap_size <<= 1;
         this->heap = (event_t**)realloc(this->heap,
                                     (this->heap_size + 1) * sizeof(event_t*));
     }
     /* "put" the event to the bottom */
     position = this->event_count;
     /* then bubble it up */
     while (position > 1 && timeval_cmp(&this->heap[position >> 1]->time,
                                        &event->time) > 0)
     {
         /* parent has to be fired after the new event, move up */
         this->heap[position] = this->heap[position >> 1];
         position >>= 1;
     }
     this->heap[position] = event;
     this->condvar->signal(this->condvar);
     this->mutex->unlock(this->mutex);
 }
METHOD (scheduler_t , schedule_job , void , private_scheduler_t * this, job_t * job, u_int32_t s)
Definition at line 278 of file scheduler.c.
References s, and time_monotonic().
 {
     timeval_t tv;
     time_monotonic(&tv);
     tv.tv_sec += s;
     schedule_job_tv(this, job, tv);
 }
METHOD (scheduler_t , schedule_job_ms , void , private_scheduler_t * this, job_t * job, u_int32_t ms)
Definition at line 289 of file scheduler.c.
References add(), time_monotonic(), and timeradd().
 {
     timeval_t tv, add;
     time_monotonic(&tv);
     add.tv_sec = ms / 1000;
     add.tv_usec = (ms % 1000) * 1000;
     timeradd(&tv, &add, &tv);
     schedule_job_tv(this, job, tv);
 }
METHOD (scheduler_t , flush , void , private_scheduler_t * this)
Definition at line 303 of file scheduler.c.
References condvar, event, event_destroy(), mutex_t::lock, mutex, remove_event(), condvar_t::signal, and mutex_t::unlock.
 {
     event_t *event;
     this->mutex->lock(this->mutex);
     while ((event = remove_event(this)) != NULL)
     {
         event_destroy(event);
     }
     this->condvar->signal(this->condvar);
     this->mutex->unlock(this->mutex);
 }
METHOD (scheduler_t , destroy , void , private_scheduler_t * this)
Definition at line 317 of file scheduler.c.
References condvar, mutex_t::destroy, condvar_t::destroy, free(), and mutex.
 {
     flush(this);
     this->condvar->destroy(this->condvar);
     this->mutex->destroy(this->mutex);
     free(this->heap);
     free(this);
 }
static event_t* peek_event (private_scheduler_t * this) static
Returns the top event without removing it. Returns NULL if the heap is empty.
Definition at line 123 of file scheduler.c.
Referenced by schedule().
 {
     return this->event_count > 0 ? this->heap[1] : NULL;
 }
static event_t* remove_event (private_scheduler_t * this) static
Removes the top event from the heap and returns it. Returns NULL if the heap is empty.
Definition at line 132 of file scheduler.c.
References event, event_t::time, and timeval_cmp().
Referenced by METHOD(), and schedule().
 {
     event_t *event, *top;
     if (!this->event_count)
     {
         return NULL;
     }
     /* store the value to return */
     event = this->heap[1];
     /* move the bottom event to the top */
     top = this->heap[1] = this->heap[this->event_count];
     if (--this->event_count > 1)
     {
         /* seep down the top event */
         u_int position = 1;
         while ((position << 1) <= this->event_count)
         {
             u_int child = position << 1;
             if ((child + 1) <= this->event_count &&
                 timeval_cmp(&this->heap[child + 1]->time,
                             &this->heap[child]->time) < 0)
             {
                 /* the "right" child is smaller */
                 child++;
             }
             if (timeval_cmp(&top->time, &this->heap[child]->time) <= 0)
             {
                 /* the top event fires before the smaller of the two children,
                  * stop */
                 break;
             }
             /* swap with the smaller child */
             this->heap[position] = this->heap[child];
             position = child;
         }
         this->heap[position] = top;
     }
     return event;
 }
static job_requeue_t schedule (private_scheduler_t * this) static
Get events from the queue and pass it to the processor
Definition at line 180 of file scheduler.c.
References condvar, DBG2, DBG_JOB, event, FALSE, free(), event_t::job, JOB_REQUEUE_DIRECT, lib, mutex_t::lock, mutex, peek_event(), library_t::processor, processor_t::queue_job, remove_event(), thread_cancelability(), thread_cleanup_pop(), thread_cleanup_push(), event_t::time, time_monotonic(), condvar_t::timed_wait_abs, timersub(), timeval_cmp(), TRUE, mutex_t::unlock, and condvar_t::wait.
Referenced by METHOD(), reverse_key(), and scheduler_create().
 {
     timeval_t now;
     event_t *event;
     bool timed = FALSE, oldstate;
     this->mutex->lock(this->mutex);
     time_monotonic(&now);
     if ((event = peek_event(this)) != NULL)
     {
         if (timeval_cmp(&now, &event->time) >= 0)
         {
             remove_event(this);
             this->mutex->unlock(this->mutex);
             DBG2(DBG_JOB, "got event, queuing job for execution");
             lib->processor->queue_job(lib->processor, event->job);
             free(event);
             return JOB_REQUEUE_DIRECT;
         }
         timersub(&event->time, &now, &now);
         if (now.tv_sec)
         {
             DBG2(DBG_JOB, "next event in %ds %dms, waiting",
                  now.tv_sec, now.tv_usec/1000);
         }
         else
         {
             DBG2(DBG_JOB, "next event in %dms, waiting", now.tv_usec/1000);
         }
         timed = TRUE;
     }
     thread_cleanup_push((thread_cleanup_t)this->mutex->unlock, this->mutex);
     oldstate = thread_cancelability(TRUE);
     if (timed)
     {
         this->condvar->timed_wait_abs(this->condvar, this->mutex, event->time);
     }
     else
     {
         DBG2(DBG_JOB, "no events, waiting");
         this->condvar->wait(this->condvar, this->mutex);
     }
     thread_cancelability(oldstate);
     thread_cleanup_pop(TRUE);
     return JOB_REQUEUE_DIRECT;
 }
static int timeval_cmp (timeval_t * a, timeval_t * b) static
Comparse two timevals, return >0 if a > b, <0 if a < b and =0 if equal
Definition at line 99 of file scheduler.c.
Referenced by METHOD(), remove_event(), and schedule().
 {
     if (a->tv_sec > b->tv_sec)
     {
         return 1;
     }
     if (a->tv_sec < b->tv_sec)
     {
         return -1;
     }
     if (a->tv_usec > b->tv_usec)
     {
         return 1;
     }
     if (a->tv_usec < b->tv_usec)
     {
         return -1;
     }
     return 0;
 }