strongSwan: dnscert
dnscert
dnscert
Classes
struct dnscert_t
Typedefs
typedef struct dnscert_t dnscert_t
typedef enum dnscert_algorithm_t dnscert_algorithm_t
typedef enum dnscert_type_t dnscert_type_t
Enumerations
enum dnscert_type_t {
DNSCERT_TYPE_RESERVED = 0, DNSCERT_TYPE_PKIX = 1, DNSCERT_TYPE_SKPI = 2, DNSCERT_TYPE_PGP = 3,
DNSCERT_TYPE_IPKIX = 4, DNSCERT_TYPE_ISKPI = 5, DNSCERT_TYPE_IPGP = 6, DNSCERT_TYPE_ACPKIX = 7,
DNSCERT_TYPE_IACKPIX = 8
}
enum dnscert_algorithm_t {
DNSCERT_ALGORITHM_UNDEFINED = 0, DNSCERT_ALGORITHM_RSAMD5 = 1, DNSCERT_ALGORITHM_DH = 2, DNSCERT_ALGORITHM_DSASHA = 3,
DNSCERT_ALGORITHM_RSRVD4 = 4, DNSCERT_ALGORITHM_RSASHA = 5, DNSCERT_ALGORITHM_DSANSEC3 = 6, DNSCERT_ALGORITHM_RSANSEC3 = 7,
DNSCERT_ALGORITHM_RSASHA256 = 8, DNSCERT_ALGORITHM_RSRVD9 = 9, DNSCERT_ALGORITHM_RSASHA512 = 10
}
Functions
dnscert_t * dnscert_create_frm_rr (rr_t *rr)
Detailed Description
Typedef Documentation
typedef enum dnscert_algorithm_t dnscert_algorithm_t
Definition at line 32 of file dnscert.h.
typedef struct dnscert_t dnscert_t
Definition at line 31 of file dnscert.h.
typedef enum dnscert_type_t dnscert_type_t
Definition at line 33 of file dnscert.h.
Enumeration Type Documentation
enum dnscert_algorithm_t
DNSCERT algorithms as defined in http://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml#dns-sec-alg-numbers-1
Enumerator
DNSCERT_ALGORITHM_UNDEFINED
No defined
DNSCERT_ALGORITHM_RSAMD5
RSA/MD5
DNSCERT_ALGORITHM_DH
Diffie-Hellman
DNSCERT_ALGORITHM_DSASHA
DSA/SHA1
DNSCERT_ALGORITHM_RSRVD4
Reserved
DNSCERT_ALGORITHM_RSASHA
RSA/SHA1
DNSCERT_ALGORITHM_DSANSEC3
DSA/NSEC3/SHA
DNSCERT_ALGORITHM_RSANSEC3
RSA/NSEC3/SHA
DNSCERT_ALGORITHM_RSASHA256
RSA/SHA256
DNSCERT_ALGORITHM_RSRVD9
Reserved
DNSCERT_ALGORITHM_RSASHA512
RSA/SHA512
Definition at line 64 of file dnscert.h.
{
     DNSCERT_ALGORITHM_UNDEFINED = 0,
     DNSCERT_ALGORITHM_RSAMD5 = 1,
     DNSCERT_ALGORITHM_DH = 2,
     DNSCERT_ALGORITHM_DSASHA = 3,
     DNSCERT_ALGORITHM_RSRVD4 = 4,
     DNSCERT_ALGORITHM_RSASHA = 5,
     DNSCERT_ALGORITHM_DSANSEC3 = 6,
     DNSCERT_ALGORITHM_RSANSEC3 = 7,
     DNSCERT_ALGORITHM_RSASHA256 = 8,
     DNSCERT_ALGORITHM_RSRVD9 = 9,
     DNSCERT_ALGORITHM_RSASHA512 = 10,
 };
enum dnscert_type_t
DNS CERT types as defined in RFC 4398.
Enumerator
DNSCERT_TYPE_RESERVED
Reserved value
DNSCERT_TYPE_PKIX
An x509 PKIX certificate
DNSCERT_TYPE_SKPI
A SKPI certificate
DNSCERT_TYPE_PGP
A PGP certificate
DNSCERT_TYPE_IPKIX
An x509 PKIX cert URL
DNSCERT_TYPE_ISKPI
A SKPI cert URL
DNSCERT_TYPE_IPGP
A PGP cert fingerprint and URL
DNSCERT_TYPE_ACPKIX
An attribute Certificate
DNSCERT_TYPE_IACKPIX
An attribute cert URL
Definition at line 40 of file dnscert.h.
                     {
     DNSCERT_TYPE_RESERVED = 0,
     DNSCERT_TYPE_PKIX = 1,
     DNSCERT_TYPE_SKPI = 2,
     DNSCERT_TYPE_PGP = 3,
     DNSCERT_TYPE_IPKIX = 4,
     DNSCERT_TYPE_ISKPI = 5,
     DNSCERT_TYPE_IPGP = 6,
     DNSCERT_TYPE_ACPKIX = 7,
     DNSCERT_TYPE_IACKPIX = 8
 };
Function Documentation
dnscert_t* dnscert_create_frm_rr (rr_t * rr)
Create a dnscert instance out of a resource record.
Parameters
rr resource record which contains a DNSCERT
Returns
dnscert, NULL on failure
Parse the content (RDATA field) of the RR First - type/tag/algo fields and then cert body
Definition at line 93 of file dnscert.c.
References algorithm, bio_reader_create(), chunk_clone, DBG1, DBG_CFG, bio_reader_t::destroy, free(), rr_t::get_rdata, rr_t::get_type, INIT, bio_reader_t::read_data, bio_reader_t::read_uint16, bio_reader_t::read_uint8, bio_reader_t::remaining, and RR_TYPE_CERT.
Referenced by METHOD().
 {
     private_dnscert_t *this;
     bio_reader_t *reader = NULL;
     INIT(this,
             .public = {
                 .get_cert_type = _get_cert_type,
                 .get_key_tag  = _get_key_tag,
                 .get_algorithm = _get_algorithm,
                 .get_certificate = _get_certificate,
                 .destroy = _destroy,
             },
     );
     if (rr->get_type(rr) != RR_TYPE_CERT)
     {
         DBG1(DBG_CFG, "unable to create a dnscert out of an RR "
                       "whose type is not CERT");
         free(this);
         return NULL;
     }
     reader = bio_reader_create(rr->get_rdata(rr));
     if (!reader->read_uint16(reader, &this->cert_type) ||
         !reader->read_uint16(reader, &this->key_tag) ||
         !reader->read_uint8(reader, &this->algorithm) )
     {
         DBG1(DBG_CFG, "CERT RR has a wrong format");
         reader->destroy(reader);
         free(this);
         return NULL;
     }
     if (!reader->read_data(reader, reader->remaining(reader),
                            &this->certificate))
     {
         DBG1(DBG_CFG, "failed to read DNS certificate field");
         reader->destroy(reader);
         free(this);
         return NULL;
     }
     this->certificate = chunk_clone(this->certificate);
     reader->destroy(reader);
     return &this->public;
 }