strongSwan: authenticator_t Struct Reference
authenticator_t Struct Reference
authenticator
#include "authenticator.h"
Public Attributes
status_t(* process)(authenticator_t *this, message_t *message)
status_t(* build)(authenticator_t *this, message_t *message)
bool(* is_mutual)(authenticator_t *this)
void(* destroy)(authenticator_t *this)
Detailed Description
Authenticator interface implemented by the various authenticators.
An authenticator implementation handles AUTH and EAP payloads. Received messages are passed to the process() method, to send authentication data the message is passed to the build() method.
Definition at line 135 of file authenticator.h.
Member Data Documentation
status_t(* authenticator_t::build)(authenticator_t *this, message_t *message)
Attach authentication data to an outgoing message.
Parameters
message message to add authentication data to
Returns
SUCCESS if authentication successful
FAILED if authentication failed
NEED_MORE if another exchange required
Definition at line 157 of file authenticator.h.
Referenced by METHOD().
void(* authenticator_t::destroy)(authenticator_t *this)
Destroy authenticator instance.
Definition at line 172 of file authenticator.h.
Referenced by METHOD().
bool(* authenticator_t::is_mutual)(authenticator_t *this)
Check if the authenticator is capable of mutual authentication.
Some authenticator authenticate both peers, e.g. EAP. To support mutual authentication with only a single authenticator (EAP-only authentication), it must be mutual. This method is invoked in ike_auth to check if the given authenticator is capable of doing so.
Definition at line 167 of file authenticator.h.
status_t(* authenticator_t::process)(authenticator_t *this, message_t *message)
Process an incoming message using the authenticator.
Parameters
message message containing authentication payloads
Returns
SUCCESS if authentication successful
FAILED if authentication failed
NEED_MORE if another exchange required
Definition at line 146 of file authenticator.h.
Referenced by METHOD().
The documentation for this struct was generated from the following file:
authenticator.h