strongSwan: cmd_creds.c File Reference
cmd_creds.c File Reference
#include "cmd_creds.h"
#include <unistd.h>
#include <utils/debug.h>
#include <credentials/sets/mem_cred.h>
#include <credentials/containers/pkcs12.h>
#include <credentials/sets/callback_cred.h>
Classes
struct private_cmd_creds_t
Typedefs
typedef struct private_cmd_creds_t private_cmd_creds_t
Functions
static shared_key_t * callback_shared (private_cmd_creds_t *this, shared_key_type_t type, identification_t *me, identification_t *other, id_match_t *match_me, id_match_t *match_other)
static void load_cert (private_cmd_creds_t *this, char *path)
static void load_key (private_cmd_creds_t *this, key_type_t type, char *path)
static void load_agent (private_cmd_creds_t *this)
static void load_pkcs12 (private_cmd_creds_t *this, char *path)
METHOD (cmd_creds_t, handle, bool, private_cmd_creds_t *this, cmd_option_type_t opt, char *arg)
METHOD (cmd_creds_t, destroy, void, private_cmd_creds_t *this)
cmd_creds_t * cmd_creds_create ()
Typedef Documentation
typedef struct private_cmd_creds_t private_cmd_creds_t
Definition at line 28 of file cmd_creds.c.
Function Documentation
static shared_key_t* callback_shared (private_cmd_creds_t * this, shared_key_type_t type, identification_t * me, identification_t * other, id_match_t * match_me, id_match_t * match_other) static
Callback function to prompt for secret
Definition at line 69 of file cmd_creds.c.
References mem_cred_t::add_shared, chunk_clone, chunk_from_str, creds, shared_key_t::get_ref, getpass(), ID_MATCH_PERFECT, prompted, SHARED_EAP, SHARED_IKE, shared_key_create(), SHARED_PIN, SHARED_PRIVATE_KEY_PASS, and type.
Referenced by cmd_creds_create().
 {
     shared_key_t *shared;
     char *label, *pwd = NULL;
     if (type == this->prompted)
     {
         return NULL;
     }
     switch (type)
     {
         case SHARED_EAP:
             label = "EAP password: ";
             break;
         case SHARED_IKE:
             label = "Preshared Key: ";
             break;
         case SHARED_PRIVATE_KEY_PASS:
             label = "Password: ";
             break;
         case SHARED_PIN:
             label = "PIN: ";
             break;
         default:
             return NULL;
     }
 #ifdef HAVE_GETPASS
     pwd = getpass(label);
 #endif
     if (!pwd || strlen(pwd) == 0)
     {
         return NULL;
     }
     this->prompted = type;
     if (match_me)
     {
         *match_me = ID_MATCH_PERFECT;
     }
     if (match_other)
     {
         *match_other = ID_MATCH_PERFECT;
     }
     shared = shared_key_create(type, chunk_clone(chunk_from_str(pwd)));
     /* cache password in case it is required more than once */
     this->creds->add_shared(this->creds, shared, NULL);
     return shared->get_ref(shared);
 }
static void load_agent (private_cmd_creds_t * this) static
Load a private and public key via ssh-agent
Definition at line 158 of file cmd_creds.c.
References mem_cred_t::add_cert, mem_cred_t::add_key, BUILD_AGENT_SOCKET, BUILD_END, BUILD_PUBLIC_KEY, BUILD_SUBJECT, cert, CERT_TRUSTED_PUBKEY, credential_factory_t::create, CRED_CERTIFICATE, CRED_PRIVATE_KEY, creds, library_t::creds, DBG1, DBG_CFG, private_key_t::destroy, public_key_t::destroy, private_key_t::get_public_key, id, identification_create_from_string(), identity, KEY_ANY, lib, and TRUE.
Referenced by METHOD().
 {
     private_key_t *privkey;
     public_key_t *pubkey;
     identification_t *id;
     certificate_t *cert;
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, KEY_ANY,
                                  BUILD_AGENT_SOCKET, this->agent, BUILD_END);
     if (!privkey)
     {
         DBG1(DBG_CFG, "failed to load private key from ssh-agent");
         exit(1);
     }
     pubkey = privkey->get_public_key(privkey);
     if (!pubkey)
     {
         DBG1(DBG_CFG, "failed to load public key from ssh-agent");
         privkey->destroy(privkey);
         exit(1);
     }
     id = identification_create_from_string(this->identity);
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                               CERT_TRUSTED_PUBKEY, BUILD_PUBLIC_KEY, pubkey,
                               BUILD_SUBJECT, id, BUILD_END);
     pubkey->destroy(pubkey);
     id->destroy(id);
     if (!cert)
     {
         DBG1(DBG_CFG, "failed to create certificate for ssh-agent public key");
         privkey->destroy(privkey);
         exit(1);
     }
     this->creds->add_cert(this->creds, TRUE, cert);
     this->creds->add_key(this->creds, privkey);
 }
static void load_cert (private_cmd_creds_t * this, char * path) static
Load a trusted certificate from path
Definition at line 123 of file cmd_creds.c.
References mem_cred_t::add_cert, BUILD_END, BUILD_FROM_FILE, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, creds, library_t::creds, DBG1, DBG_CFG, lib, and TRUE.
Referenced by manage_commands(), and METHOD().
 {
     certificate_t *cert;
     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                               BUILD_FROM_FILE, path, BUILD_END);
     if (!cert)
     {
         DBG1(DBG_CFG, "loading certificate from '%s' failed", path);
         exit(1);
     }
     this->creds->add_cert(this->creds, TRUE, cert);
 }
static void load_key (private_cmd_creds_t * this, key_type_t type, char * path) static
Load a private key of given kind from path
Definition at line 140 of file cmd_creds.c.
References mem_cred_t::add_key, BUILD_END, BUILD_FROM_FILE, credential_factory_t::create, CRED_PRIVATE_KEY, creds, library_t::creds, DBG1, DBG_CFG, key_type_names, and lib.
Referenced by METHOD().
 {
     private_key_t *privkey;
     privkey = lib->creds->create(lib->creds, CRED_PRIVATE_KEY, type,
                                  BUILD_FROM_FILE, path, BUILD_END);
     if (!privkey)
     {
         DBG1(DBG_CFG, "loading %N private key from '%s' failed",
              key_type_names, type, path);
         exit(1);
     }
     this->creds->add_key(this->creds, privkey);
 }
static void load_pkcs12 (private_cmd_creds_t * this, char * path) static
Load a PKCS#12 file from path
Definition at line 198 of file cmd_creds.c.
References mem_cred_t::add_cert, mem_cred_t::add_key, BUILD_END, BUILD_FROM_FILE, cert, CONTAINER_PKCS12, credential_factory_t::create, pkcs12_t::create_cert_enumerator, pkcs12_t::create_key_enumerator, CRED_CONTAINER, creds, library_t::creds, DBG1, DBG_CFG, enumerator_t::destroy, container_t::destroy, enumerator_t::enumerate, private_key_t::get_ref, certificate_t::get_ref, key, lib, pkcs12(), and TRUE.
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     certificate_t *cert;
     private_key_t *key;
     container_t *container;
     pkcs12_t *pkcs12;
     container = lib->creds->create(lib->creds, CRED_CONTAINER, CONTAINER_PKCS12,
                                    BUILD_FROM_FILE, path, BUILD_END);
     if (!container)
     {
         DBG1(DBG_CFG, "loading PKCS#12 file '%s' failed", path);
         exit(1);
     }
     pkcs12 = (pkcs12_t*)container;
     enumerator = pkcs12->create_cert_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &cert))
     {
         this->creds->add_cert(this->creds, TRUE, cert->get_ref(cert));
     }
     enumerator->destroy(enumerator);
     enumerator = pkcs12->create_key_enumerator(pkcs12);
     while (enumerator->enumerate(enumerator, &key))
     {
         this->creds->add_key(this->creds, key->get_ref(key));
     }
     enumerator->destroy(enumerator);
     container->destroy(container);
 }
METHOD (cmd_creds_t , handle , bool , private_cmd_creds_t * this, cmd_option_type_t opt, char * arg)
Definition at line 229 of file cmd_creds.c.
References CMD_OPT_AGENT, CMD_OPT_CERT, CMD_OPT_IDENTITY, CMD_OPT_PKCS12, CMD_OPT_RSA, DBG1, DBG_CFG, FALSE, identity, KEY_RSA, load_agent(), load_cert(), load_key(), load_pkcs12(), and TRUE.
 {
     switch (opt)
     {
         case CMD_OPT_CERT:
             load_cert(this, arg);
             break;
         case CMD_OPT_RSA:
             load_key(this, KEY_RSA, arg);
             break;
         case CMD_OPT_PKCS12:
             load_pkcs12(this, arg);
             break;
         case CMD_OPT_IDENTITY:
             this->identity = arg;
             break;
         case CMD_OPT_AGENT:
             this->agent = arg ?: getenv("SSH_AUTH_SOCK");
             if (!this->agent)
             {
                 DBG1(DBG_CFG, "no ssh-agent socket defined");
                 exit(1);
             }
             break;
         default:
             return FALSE;
     }
     if (this->agent && this->identity)
     {
         load_agent(this);
         /* only do this once */
         this->agent = NULL;
     }
     return TRUE;
 }
METHOD (cmd_creds_t , destroy , void , private_cmd_creds_t * this)
Definition at line 266 of file cmd_creds.c.
References cb(), library_t::credmgr, creds, mem_cred_t::destroy, free(), lib, and credential_manager_t::remove_set.
 {
     lib->credmgr->remove_set(lib->credmgr, &this->creds->set);
     lib->credmgr->remove_set(lib->credmgr, &this->cb->set);
     this->creds->destroy(this->creds);
     this->cb->destroy(this->cb);
     free(this);
 }