strongSwan: kernel_interface
kernel_interface
kernel
Classes
struct kernel_interface_t
Typedefs
typedef struct kernel_interface_t kernel_interface_t
typedef enum kernel_feature_t kernel_feature_t
typedef kernel_ipsec_t *(* kernel_ipsec_constructor_t)(void)
typedef kernel_net_t *(* kernel_net_constructor_t)(void)
Enumerations
enum kernel_feature_t { KERNEL_ESP_V3_TFC = (1<<0), KERNEL_REQUIRE_EXCLUDE_ROUTE = (1<<1), KERNEL_REQUIRE_UDP_ENCAPSULATION = (1<<2), KERNEL_NO_POLICY_UPDATES = (1<<3) }
Functions
kernel_interface_t * kernel_interface_create (void)
Detailed Description
Typedef Documentation
typedef enum kernel_feature_t kernel_feature_t
Definition at line 50 of file kernel_interface.h.
typedef struct kernel_interface_t kernel_interface_t
Definition at line 49 of file kernel_interface.h.
typedef kernel_ipsec_t*(* kernel_ipsec_constructor_t)(void)
Constructor function for ipsec kernel interface
Definition at line 79 of file kernel_interface.h.
typedef kernel_net_t*(* kernel_net_constructor_t)(void)
Constructor function for network kernel interface
Definition at line 84 of file kernel_interface.h.
Enumeration Type Documentation
enum kernel_feature_t
Bitfield of optional features a kernel backend supports.
This feature-set is for both, kernel_ipsec_t and kernel_net_t. Each backend returns a subset of these features.
Enumerator
KERNEL_ESP_V3_TFC
IPsec can process ESPv3 (RFC 4303) TFC padded packets
KERNEL_REQUIRE_EXCLUDE_ROUTE
Networking requires an "exclude" route for IKE/ESP packets
KERNEL_REQUIRE_UDP_ENCAPSULATION
IPsec implementation requires UDP encapsulation of ESP packets
KERNEL_NO_POLICY_UPDATES
IPsec backend does not require a policy reinstall on SA updates
Definition at line 65 of file kernel_interface.h.
                       {
     KERNEL_ESP_V3_TFC = (1<<0),
     KERNEL_REQUIRE_EXCLUDE_ROUTE = (1<<1),
     KERNEL_REQUIRE_UDP_ENCAPSULATION = (1<<2),
     KERNEL_NO_POLICY_UPDATES = (1<<3),
 };
Function Documentation
kernel_interface_t* kernel_interface_create (void)
Creates an object of type kernel_interface_t.
Definition at line 997 of file kernel_interface.c.
References enumerator_t::destroy, enumerator_t::enumerate, enumerator_create_token(), equals_reqid(), equals_reqid_by_ts(), settings_t::get_str, hash_reqid(), hash_reqid_by_ts(), hashtable_create(), INIT, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, library_t::settings, strdup, and TRUE.
Referenced by libhydra_init().
 {
     private_kernel_interface_t *this;
     char *ifaces;
     INIT(this,
         .public = {
             .get_features = _get_features,
             .get_spi = _get_spi,
             .get_cpi = _get_cpi,
             .alloc_reqid = _alloc_reqid,
             .release_reqid = _release_reqid,
             .add_sa = _add_sa,
             .update_sa = _update_sa,
             .query_sa = _query_sa,
             .del_sa = _del_sa,
             .flush_sas = _flush_sas,
             .add_policy = _add_policy,
             .query_policy = _query_policy,
             .del_policy = _del_policy,
             .flush_policies = _flush_policies,
             .get_source_addr = _get_source_addr,
             .get_nexthop = _get_nexthop,
             .get_interface = _get_interface,
             .create_address_enumerator = _create_address_enumerator,
             .add_ip = _add_ip,
             .del_ip = _del_ip,
             .add_route = _add_route,
             .del_route = _del_route,
             .bypass_socket = _bypass_socket,
             .enable_udp_decap = _enable_udp_decap,
             .is_interface_usable = _is_interface_usable,
             .all_interfaces_usable = _all_interfaces_usable,
             .get_address_by_ts = _get_address_by_ts,
             .add_ipsec_interface = _add_ipsec_interface,
             .remove_ipsec_interface = _remove_ipsec_interface,
             .add_net_interface = _add_net_interface,
             .remove_net_interface = _remove_net_interface,
             .add_listener = _add_listener,
             .remove_listener = _remove_listener,
             .register_algorithm = _register_algorithm,
             .lookup_algorithm = _lookup_algorithm,
             .acquire = _acquire,
             .expire = _expire,
             .mapping = _mapping,
             .migrate = _migrate,
             .roam = _roam,
             .tun = _tun,
             .destroy = _destroy,
         },
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .listeners = linked_list_create(),
         .mutex_algs = mutex_create(MUTEX_TYPE_DEFAULT),
         .algorithms = linked_list_create(),
         .reqids = hashtable_create((hashtable_hash_t)hash_reqid,
                                    (hashtable_equals_t)equals_reqid, 8),
         .reqids_by_ts = hashtable_create((hashtable_hash_t)hash_reqid_by_ts,
                                    (hashtable_equals_t)equals_reqid_by_ts, 8),
     );
     ifaces = lib->settings->get_str(lib->settings,
                                     "%s.interfaces_use", NULL, lib->ns);
     if (!ifaces)
     {
         this->ifaces_exclude = TRUE;
         ifaces = lib->settings->get_str(lib->settings,
                                     "%s.interfaces_ignore", NULL, lib->ns);
     }
     if (ifaces)
     {
         enumerator_t *enumerator;
         char *iface;
         enumerator = enumerator_create_token(ifaces, ",", " ");
         while (enumerator->enumerate(enumerator, &iface))
         {
             if (!this->ifaces_filter)
             {
                 this->ifaces_filter = linked_list_create();
             }
             this->ifaces_filter->insert_last(this->ifaces_filter,
                                              strdup(iface));
         }
         enumerator->destroy(enumerator);
     }
     return &this->public;
 }