strongSwan: pts_ima_event_list
pts_ima_event_list
pts
Classes
struct pts_ima_event_list_t
Macros
#define IMA_PCR 10
#define IMA_ALGO_LEN_MIN 5
#define IMA_ALGO_LEN_MAX 8
Typedefs
typedef struct pts_ima_event_list_t pts_ima_event_list_t
Functions
pts_ima_event_list_t * pts_ima_event_list_create (char *file)
Detailed Description
Macro Definition Documentation
#define IMA_ALGO_LEN_MAX 8
Definition at line 32 of file pts_ima_event_list.h.
Referenced by METHOD(), parse_validation_uri(), and pts_ima_event_list_create().
#define IMA_ALGO_LEN_MIN 5
Definition at line 31 of file pts_ima_event_list.h.
Referenced by pts_ima_event_list_create().
#define IMA_PCR 10
Definition at line 30 of file pts_ima_event_list.h.
Referenced by METHOD(), and pts_ima_event_list_create().
Typedef Documentation
typedef struct pts_ima_event_list_t pts_ima_event_list_t
Definition at line 28 of file pts_ima_event_list.h.
Function Documentation
pts_ima_event_list_t* pts_ima_event_list_create (char * file)
Create a PTS IMA runtime file measurement object
Parameters
file Pathname pointing to the IMA runtme measurements
See header
Definition at line 128 of file pts_ima_event_list.c.
References event_entry_t::algo, chunk_alloc, close, DBG1, DBG2, DBG_PTS, destroy(), FALSE, free_event_entry(), linked_list_t::get_count, HASH_SIZE_SHA1, IMA_ALGO_DIGEST_LEN_MAX, IMA_ALGO_LEN_MAX, IMA_ALGO_LEN_MIN, IMA_NG_TYPE_LEN, IMA_PCR, IMA_TYPE_LEN, IMA_TYPE_LEN_MAX, INIT, linked_list_t::insert_last, linked_list_create(), list, malloc(), malloc_thing, event_entry_t::measurement, memcpy, memeq(), event_entry_t::name, chunk_t::ptr, read, res, strerror, TRUE, type, and UINT32_MAX.
Referenced by METHOD().
 {
     private_pts_ima_event_list_t *this;
     event_entry_t *entry;
     uint32_t pcr, type_len, name_len, eventdata_len, algo_digest_len, algo_len;
     char type[IMA_TYPE_LEN_MAX];
     char algo_digest[IMA_ALGO_DIGEST_LEN_MAX];
     char *pos, *error = "";
     struct stat st;
     ssize_t res;
     bool ima_ng;
     int fd;
     fd = open(file, O_RDONLY);
     if (fd == -1)
     {
         DBG1(DBG_PTS, "opening '%s' failed: %s", file, strerror(errno));
         return NULL;
     }
     if (fstat(fd, &st) == -1)
     {
         DBG1(DBG_PTS, "getting statistics of '%s' failed: %s", file,
              strerror(errno));
         close(fd);
         return NULL;
     }
     INIT(this,
         .public = {
             .get_time = _get_time,
             .get_count = _get_count,
             .get_next = _get_next,
             .destroy = _destroy,
         },
         .creation_time = st.st_ctime,
         .list = linked_list_create(),
     );
     while (TRUE)
     {
         /* read 32 bit PCR number in host order */
         res = read(fd, &pcr, 4);
         /* exit if no more measurement data is available */
         if (res == 0)
         {
             DBG2(DBG_PTS, "loaded ima measurements '%s' (%d entries)",
                  file, this->list->get_count(this->list));
             close(fd);
             return &this->public;
         }
         /* create and initialize new IMA entry */
         entry = malloc_thing(event_entry_t);
         entry->measurement = chunk_alloc(HASH_SIZE_SHA1);
         entry->algo = NULL;
         entry->name = NULL;
         if (res != 4 || pcr != IMA_PCR)
         {
             error = "invalid IMA PCR field";
             break;
         }
         /* read 20 byte SHA-1 measurement digest */
         if (read(fd, entry->measurement.ptr, HASH_SIZE_SHA1) != HASH_SIZE_SHA1)
         {
             error = "invalid SHA-1 digest field";
             break;
         }
         /* read 32 bit length of IMA type string in host order */
         if (read(fd, &type_len, 4) != 4 || type_len > IMA_TYPE_LEN_MAX)
         {
             error = "invalid IMA type field length";
             break;
         }
         /* read and interpret IMA type string */
         if (read(fd, type, type_len) != type_len)
         {
             error = "invalid IMA type field";
             break;
         }
         if (type_len == IMA_NG_TYPE_LEN &&
             memeq(type, "ima-ng", IMA_NG_TYPE_LEN))
         {
             ima_ng = TRUE;
         }
         else if (type_len == IMA_TYPE_LEN &&
                  memeq(type, "ima", IMA_TYPE_LEN))
         {
             ima_ng = FALSE;
         }
         else
         {
             error = "unknown IMA type";
             break;
         }
         if (ima_ng)
         {
             /* read the 32 bit length of the event data in host order */
             if (read(fd, &eventdata_len, 4) != 4 || eventdata_len < 4)
             {
                 error = "invalid event data field length";
                 break;
             }
             /* read the 32 bit length of the algo_digest string in host order */
             if (read(fd, &algo_digest_len, 4) != 4 ||
                 algo_digest_len > IMA_ALGO_DIGEST_LEN_MAX ||
                 eventdata_len < 4 + algo_digest_len + 4)
             {
                 error = "invalid digest_with_algo field length";
                 break;
             }
             /* read the IMA algo_digest string */
             if (read(fd, algo_digest, algo_digest_len) != algo_digest_len)
             {
                 error = "invalid digest_with_algo field";
                 break;
             }
             /* extract the hash algorithm name */
             pos = memchr(algo_digest, '\0', algo_digest_len);
             if (!pos)
             {
                 error = "no algo field";
                 break;
             }
             algo_len = pos - algo_digest + 1;
             if (algo_len > IMA_ALGO_LEN_MAX ||
                 algo_len < IMA_ALGO_LEN_MIN || *(pos - 1) != ':')
             {
                 error = "invalid algo field";
                 break;
             }
             /* copy and store the hash algorithm name */
             entry->algo = malloc(algo_len);
             memcpy(entry->algo, algo_digest, algo_len);
             /* read the 32 bit length of the event name in host order */
             if (read(fd, &name_len, 4) != 4 ||
                 eventdata_len != 4 + algo_digest_len + 4 + name_len)
             {
                 error = "invalid filename field length";
                 break;
             }
             /* allocate memory for the file name */
             entry->name = malloc(name_len);
             /* read file name */
             if (read(fd, entry->name, name_len) != name_len)
             {
                 error = "invalid filename field";
                 break;
             }
         }
         else
         {
             /* skip SHA-1 digest of the file content */
             if (lseek(fd, HASH_SIZE_SHA1, SEEK_CUR) == -1)
             {
                 break;
             }
             /* read the 32 bit length of the file name in host order */
             if (read(fd, &name_len, 4) != 4 || name_len == UINT32_MAX)
             {
                 error = "invalid filename field length";
                 break;
             }
             /* allocate memory for the file name */
             entry->name = malloc(name_len + 1);
             /* read file name */
             if (read(fd, entry->name, name_len) != name_len)
             {
                 error = "invalid eventname field";
                 break;
             }
             /* terminate the file name with a nul character */
             entry->name[name_len] = '\0';
         }
         this->list->insert_last(this->list, entry);
     }
     DBG1(DBG_PTS, "loading ima measurements '%s' failed: %s", file, error);
     free_event_entry(entry);
     close(fd);
     destroy(this);
     return NULL;
 }