strongSwan: tests.c File Reference
libhydra/plugins/kernel_netlink/tests.c File Reference
#include <test_runner.h>
#include <hydra.h>
#include "tests.h"
Macros
#define TEST_SUITE(x) test_suite_t* x();
#define TEST_SUITE(x) { .suite = x, },
Functions
static bool test_runner_init (bool init)
int main (int argc, char *argv[])
Variables
static test_configuration_t tests []
Macro Definition Documentation
#define TEST_SUITE (x) test_suite_t* x();
Definition at line 21 of file libhydra/plugins/kernel_netlink/tests.c.
#define TEST_SUITE (x) { .suite = x, },
Definition at line 21 of file libhydra/plugins/kernel_netlink/tests.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 46 of file libhydra/plugins/kernel_netlink/tests.c.
References test_runner_init(), and test_runner_run().
 {
     return test_runner_run("kernel-netlink", tests, test_runner_init);
 }
static bool test_runner_init (bool init) static
Definition at line 32 of file libhydra/plugins/kernel_netlink/tests.c.
References processor_t::cancel, lib, library_t::processor, processor_t::set_threads, and TRUE.
Referenced by main().
 {
     if (init)
     {
         lib->processor->set_threads(lib->processor, 8);
     }
     else
     {
         lib->processor->set_threads(lib->processor, 0);
         lib->processor->cancel(lib->processor);
     }
     return TRUE;
 }
Variable Documentation
test_configuration_t tests[] static
Initial value:
= {
#define TEST_SUITE(x)
    { .suite = NULL, }
}
Definition at line 25 of file libhydra/plugins/kernel_netlink/tests.c.