strongSwan: xauth_eap
xauth_eap
xauth_eap
Classes
struct xauth_eap_t
Typedefs
typedef struct xauth_eap_t xauth_eap_t
Functions
xauth_eap_t * xauth_eap_create_server (identification_t *server, identification_t *peer, char *profile)
Detailed Description
Typedef Documentation
typedef struct xauth_eap_t xauth_eap_t
Definition at line 24 of file xauth_eap.h.
Function Documentation
xauth_eap_t* xauth_eap_create_server (identification_t * server, identification_t * peer, char * profile)
Creates the XAuth method using EAP, acting as server.
Parameters
server ID of the XAuth server
peer ID of the XAuth client
profile configuration string
Returns
xauth_eap_t object
Definition at line 268 of file xauth_eap.c.
References callback_cred_create_shared(), identification_t::clone, INIT, and shared_cb().
Referenced by METHOD().
 {
     private_xauth_eap_t *this;
     INIT(this,
         .public = {
             .xauth_method = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_identity = _get_identity,
                 .destroy = _destroy,
             },
         },
         .server = server->clone(server),
         .peer = peer->clone(peer),
     );
     this->cred = callback_cred_create_shared((void*)shared_cb, this);
     return &this->public;
 }