strongSwan: mgf1
mgf1
crypto
Modules
mgf1_bitspender
Classes
struct mgf1_t
Typedefs
typedef struct mgf1_t mgf1_t
Functions
mgf1_t * mgf1_create (hash_algorithm_t alg, chunk_t seed, bool hash_seed)
Detailed Description
Typedef Documentation
typedef struct mgf1_t mgf1_t
Definition at line 24 of file mgf1.h.
Function Documentation
mgf1_t* mgf1_create (hash_algorithm_t alg, chunk_t seed, bool hash_seed)
Create an MGF1 object
Parameters
alg hash algorithm to be used by MGF1
seed seed used by MGF1 to generate mask from
hash_seed hash seed before using it as a seed for MGF1
Definition at line 129 of file mgf1.c.
References chunk_alloc, crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, destroy(), hasher_t::get_hash, hasher_t::get_hash_size, hash_algorithm_names, hasher, INIT, chunk_t::len, lib, memcpy, and chunk_t::ptr.
Referenced by mgf1_bitspender_create(), and START_TEST().
 {
     private_mgf1_t *this;
     hasher_t *hasher;
     size_t state_len;
     if (seed.len == 0)
     {
         DBG1(DBG_LIB, "empty seed for MGF1");
         return NULL;
     }
     hasher = lib->crypto->create_hasher(lib->crypto, alg);
     if (!hasher)
     {
         DBG1(DBG_LIB, "failed to create %N hasher for MGF1",
              hash_algorithm_names, alg);
         return NULL;
     }
     state_len = (hash_seed ? hasher->get_hash_size(hasher) : seed.len) + 4;
     INIT(this,
         .public = {
             .get_hash_size = _get_hash_size,
             .allocate_mask = _allocate_mask,
             .get_mask = _get_mask,
             .destroy = _destroy,
         },
         .hasher = hasher,
         .state = chunk_alloc(state_len),
     );
     /* determine position of the 4 octet counter string */
     this->ctr_str = this->state.ptr + state_len - 4;
     if (hash_seed)
     {
         if (!hasher->get_hash(hasher, seed, this->state.ptr))
         {
             DBG1(DBG_LIB, "failed to hash seed for MGF1");
             destroy(this);
             return NULL;
         }
     }
     else
     {
         memcpy(this->state.ptr, seed.ptr, seed.len);
     }
     return &this->public;
 }