strongSwan: dumm.c File Reference
ext/dumm.c File Reference
#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <library.h>
#include <dumm.h>
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <ruby.h>
Macros
#define RUBY_DONT_SUBST
Functions
static pid_t invoke (void *null, guest_t *guest, char *args[], int argc)
static void sigchld_handler (int signal, siginfo_t *info, void *ptr)
static VALUE dumm_add_overlay (VALUE class, VALUE dir)
static VALUE dumm_del_overlay (VALUE class, VALUE dir)
static VALUE dumm_pop_overlay (VALUE class)
static void dumm_init ()
static VALUE guest_hash_create (VALUE class)
static VALUE guest_hash (VALUE class)
static VALUE guest_find (VALUE class, VALUE key)
static VALUE guest_get (VALUE class, VALUE key)
static VALUE guest_each (int argc, VALUE *argv, VALUE class)
static VALUE guest_new (VALUE class, VALUE name, VALUE kernel, VALUE master, VALUE args)
static VALUE guest_to_s (VALUE self)
static VALUE guest_start (VALUE self)
static VALUE guest_stop (VALUE self)
static VALUE guest_running (VALUE self)
static void exec_cb (void *data, char *buf)
static VALUE guest_exec (VALUE self, VALUE cmd)
static VALUE guest_mconsole (VALUE self, VALUE cmd)
static VALUE guest_add_iface (VALUE self, VALUE name)
static VALUE guest_find_iface (VALUE self, VALUE key)
static VALUE guest_get_iface (VALUE self, VALUE key)
static VALUE guest_each_iface (int argc, VALUE *argv, VALUE self)
static VALUE guest_delete (VALUE self)
static VALUE guest_add_overlay (VALUE self, VALUE dir)
static VALUE guest_del_overlay (VALUE self, VALUE dir)
static VALUE guest_pop_overlay (VALUE self)
static void guest_init ()
static VALUE bridge_find (VALUE class, VALUE key)
static VALUE bridge_get (VALUE class, VALUE key)
static VALUE bridge_each (int argc, VALUE *argv, VALUE class)
static VALUE bridge_new (VALUE class, VALUE name)
static VALUE bridge_to_s (VALUE self)
static VALUE bridge_each_iface (int argc, VALUE *argv, VALUE self)
static VALUE bridge_delete (VALUE self)
static void bridge_init ()
static VALUE iface_to_s (VALUE self)
static VALUE iface_connect (VALUE self, VALUE vbridge)
static VALUE iface_disconnect (VALUE self)
static VALUE iface_add_addr (VALUE self, VALUE name)
static VALUE iface_each_addr (int argc, VALUE *argv, VALUE self)
static VALUE iface_del_addr (VALUE self, VALUE vaddr)
static VALUE iface_delete (VALUE self)
static void iface_init ()
static VALUE template_load (VALUE class, VALUE dir)
static VALUE template_unload (VALUE class)
static VALUE template_each (int argc, VALUE *argv, VALUE class)
static void template_init ()
void Final_dumm ()
void Init_dumm ()
Variables
static dumm_t * dumm
static VALUE rbm_dumm
static VALUE rbc_guest
static VALUE rbc_bridge
static VALUE rbc_iface
static VALUE rbc_template
Macro Definition Documentation
#define RUBY_DONT_SUBST
Definition at line 34 of file ext/dumm.c.
Function Documentation
static VALUE bridge_delete (VALUE self) static
Definition at line 536 of file ext/dumm.c.
References dumm_t::delete_bridge.
Referenced by bridge_init().
 {
     bridge_t *bridge;
     Data_Get_Struct(self, bridge_t, bridge);
     dumm->delete_bridge(dumm, bridge);
     return Qnil;
 }
static VALUE bridge_each (int argc, VALUE * argv, VALUE class) static
Definition at line 463 of file ext/dumm.c.
References dumm_t::create_bridge_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, linked_list_create(), list, linked_list_t::remove_first, and SUCCESS.
Referenced by bridge_init().
 {
     enumerator_t *enumerator;
     linked_list_t *list;
     bridge_t *bridge;
     if (!rb_block_given_p())
     {
         rb_raise(rb_eArgError, "must be called with a block");
     }
     list = linked_list_create();
     enumerator = dumm->create_bridge_enumerator(dumm);
     while (enumerator->enumerate(enumerator, &bridge))
     {
         list->insert_last(list, bridge);
     }
     enumerator->destroy(enumerator);
     while (list->remove_first(list, (void**)&bridge) == SUCCESS)
     {
         rb_yield(Data_Wrap_Struct(class, NULL, NULL, bridge));
     }
     list->destroy(list);
     return class;
 }
static VALUE bridge_each_iface (int argc, VALUE * argv, VALUE self) static
Definition at line 509 of file ext/dumm.c.
References bridge_t::create_iface_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, linked_list_create(), list, rbc_iface, linked_list_t::remove_first, and SUCCESS.
Referenced by bridge_init().
 {
     enumerator_t *enumerator;
     linked_list_t *list;
     bridge_t *bridge;
     iface_t *iface;
     if (!rb_block_given_p())
     {
         rb_raise(rb_eArgError, "must be called with a block");
     }
     Data_Get_Struct(self, bridge_t, bridge);
     list = linked_list_create();
     enumerator = bridge->create_iface_enumerator(bridge);
     while (enumerator->enumerate(enumerator, &iface))
     {
         list->insert_last(list, iface);
     }
     enumerator->destroy(enumerator);
     while (list->remove_first(list, (void**)&iface) == SUCCESS)
     {
         rb_yield(Data_Wrap_Struct(rbc_iface, NULL, NULL, iface));
     }
     list->destroy(list);
     return self;
 }
static VALUE bridge_find (VALUE class, VALUE key) static
Bridge binding
Definition at line 427 of file ext/dumm.c.
References dumm_t::create_bridge_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, bridge_t::get_name, and streq().
Referenced by bridge_get(), and bridge_init().
 {
     enumerator_t *enumerator;
     bridge_t *bridge, *found = NULL;
     if (TYPE(key) == T_SYMBOL)
     {
         key = rb_convert_type(key, T_STRING, "String", "to_s");
     }
     enumerator = dumm->create_bridge_enumerator(dumm);
     while (enumerator->enumerate(enumerator, &bridge))
     {
         if (streq(bridge->get_name(bridge), StringValuePtr(key)))
         {
             found = bridge;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         return Qnil;
     }
     return Data_Wrap_Struct(class, NULL, NULL, found);
 }
static VALUE bridge_get (VALUE class, VALUE key) static
Definition at line 453 of file ext/dumm.c.
References bridge_find().
Referenced by bridge_init().
 {
     VALUE bridge = bridge_find(class, key);
     if (NIL_P(bridge))
     {
         rb_raise(rb_eRuntimeError, "bridge not found");
     }
     return bridge;
 }
static void bridge_init () static
Definition at line 545 of file ext/dumm.c.
References bridge_delete(), bridge_each(), bridge_each_iface(), bridge_find(), bridge_get(), bridge_new(), bridge_to_s(), rbc_bridge, and rbm_dumm.
Referenced by Init_dumm().
 {
     rbc_bridge = rb_define_class_under(rbm_dumm , "Bridge", rb_cObject);
     rb_include_module(rb_class_of(rbc_bridge), rb_mEnumerable);
     rb_include_module(rbc_bridge, rb_mEnumerable);
     rb_define_singleton_method(rbc_bridge, "[]", bridge_get, 1);
     rb_define_singleton_method(rbc_bridge, "each", bridge_each, -1);
     rb_define_singleton_method(rbc_bridge, "new", bridge_new, 1);
     rb_define_singleton_method(rbc_bridge, "include?", bridge_find, 1);
     rb_define_singleton_method(rbc_bridge, "bridge?", bridge_find, 1);
     rb_define_method(rbc_bridge, "to_s", bridge_to_s, 0);
     rb_define_method(rbc_bridge, "each", bridge_each_iface, -1);
     rb_define_method(rbc_bridge, "delete", bridge_delete, 0);
 }
static VALUE bridge_new (VALUE class, VALUE name) static
Definition at line 488 of file ext/dumm.c.
References dumm_t::create_bridge.
Referenced by bridge_init().
 {
     bridge_t *bridge;
     bridge = dumm->create_bridge(dumm, StringValuePtr(name));
     if (!bridge)
     {
         rb_raise(rb_eRuntimeError, "creating bridge failed");
     }
     return Data_Wrap_Struct(class, NULL, NULL, bridge);
 }
static VALUE bridge_to_s (VALUE self) static
Definition at line 501 of file ext/dumm.c.
References bridge_t::get_name.
Referenced by bridge_init().
 {
     bridge_t *bridge;
     Data_Get_Struct(self, bridge_t, bridge);
     return rb_str_new2(bridge->get_name(bridge));
 }
static VALUE dumm_add_overlay (VALUE class, VALUE dir) static
Global Dumm bindings
Definition at line 96 of file ext/dumm.c.
References dumm_t::add_overlay.
Referenced by dumm_init().
 {
     if (!dumm->add_overlay(dumm, StringValuePtr(dir)))
     {
         rb_raise(rb_eRuntimeError, "loading overlay failed");
     }
     return class;
 }
static VALUE dumm_del_overlay (VALUE class, VALUE dir) static
Definition at line 105 of file ext/dumm.c.
References dumm_t::del_overlay.
Referenced by dumm_init().
 {
     return dumm->del_overlay(dumm, StringValuePtr(dir)) ? Qtrue : Qfalse;
 }
static void dumm_init () static
Definition at line 115 of file ext/dumm.c.
References dumm_add_overlay(), dumm_del_overlay(), dumm_pop_overlay(), and rbm_dumm.
Referenced by Init_dumm().
 {
     rbm_dumm = rb_define_module("Dumm");
     rb_define_module_function(rbm_dumm, "add_overlay", dumm_add_overlay, 1);
     rb_define_module_function(rbm_dumm, "del_overlay", dumm_del_overlay, 1);
     rb_define_module_function(rbm_dumm, "pop_overlay", dumm_pop_overlay, 0);
 }
static VALUE dumm_pop_overlay (VALUE class) static
Definition at line 110 of file ext/dumm.c.
References dumm_t::pop_overlay.
Referenced by dumm_init().
 {
     return dumm->pop_overlay(dumm) ? Qtrue : Qfalse;
 }
static void exec_cb (void * data, char * buf) static
Definition at line 238 of file ext/dumm.c.
Referenced by guest_exec(), and guest_mconsole().
 {
     rb_yield(rb_str_new2(buf));
 }
void Final_dumm ()
extension finalization
Definition at line 755 of file ext/dumm.c.
References dumm_t::destroy, and library_deinit().
Referenced by Init_dumm().
 {
     struct sigaction action;
     dumm->destroy(dumm);
     sigemptyset(&action.sa_mask);
     action.sa_handler = SIG_DFL;
     action.sa_flags = 0;
     sigaction(SIGCHLD, &action, NULL);
     library_deinit();
 }
static VALUE guest_add_iface (VALUE self, VALUE name) static
Definition at line 273 of file ext/dumm.c.
References guest_t::create_iface, and rbc_iface.
Referenced by guest_init().
 {
     guest_t *guest;
     iface_t *iface;
     Data_Get_Struct(self, guest_t, guest);
     iface = guest->create_iface(guest, StringValuePtr(name));
     if (!iface)
     {
         rb_raise(rb_eRuntimeError, "adding interface failed");
     }
     return Data_Wrap_Struct(rbc_iface, NULL, NULL, iface);
 }
static VALUE guest_add_overlay (VALUE self, VALUE dir) static
Definition at line 365 of file ext/dumm.c.
References guest_t::add_overlay.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     if (!guest->add_overlay(guest, StringValuePtr(dir)))
     {
         rb_raise(rb_eRuntimeError, "loading overlay failed");
     }
     return self;
 }
static VALUE guest_del_overlay (VALUE self, VALUE dir) static
Definition at line 377 of file ext/dumm.c.
References guest_t::del_overlay.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     return guest->del_overlay(guest, StringValuePtr(dir)) ? Qtrue : Qfalse;
 }
static VALUE guest_delete (VALUE self) static
Definition at line 352 of file ext/dumm.c.
References dumm_t::delete_guest, and guest_t::get_pid.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     if (guest->get_pid(guest))
     {
         rb_raise(rb_eRuntimeError, "guest is running");
     }
     dumm->delete_guest(dumm, guest);
     return Qnil;
 }
static VALUE guest_each (int argc, VALUE * argv, VALUE class) static
Definition at line 172 of file ext/dumm.c.
References guest_hash().
Referenced by guest_init().
 {
     if (!rb_block_given_p())
     {
         rb_raise(rb_eArgError, "must be called with a block");
     }
     rb_block_call(guest_hash(class), rb_intern("each_value"), 0, 0,
                   rb_yield, 0);
     return class;
 }
static VALUE guest_each_iface (int argc, VALUE * argv, VALUE self) static
Definition at line 325 of file ext/dumm.c.
References guest_t::create_iface_enumerator, enumerator_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, linked_list_create(), list, rbc_iface, linked_list_t::remove_first, and SUCCESS.
Referenced by guest_init().
 {
     enumerator_t *enumerator;
     linked_list_t *list;
     guest_t *guest;
     iface_t *iface;
     if (!rb_block_given_p())
     {
         rb_raise(rb_eArgError, "must be called with a block");
     }
     Data_Get_Struct(self, guest_t, guest);
     list = linked_list_create();
     enumerator = guest->create_iface_enumerator(guest);
     while (enumerator->enumerate(enumerator, &iface))
     {
         list->insert_last(list, iface);
     }
     enumerator->destroy(enumerator);
     while (list->remove_first(list, (void**)&iface) == SUCCESS)
     {
         rb_yield(Data_Wrap_Struct(rbc_iface, NULL, NULL, iface));
     }
     list->destroy(list);
     return self;
 }
static VALUE guest_exec (VALUE self, VALUE cmd) static
Definition at line 243 of file ext/dumm.c.
References exec_cb(), guest_t::exec_str, and TRUE.
Referenced by guest_init().
 {
     guest_t *guest;
     bool block;
     int ret;
     block = rb_block_given_p();
     Data_Get_Struct(self, guest_t, guest);
     ret = guest->exec_str(guest, block ? (void*)exec_cb : NULL, TRUE, NULL,
                           "exec %s", StringValuePtr(cmd));
     rb_iv_set(self, "@execstatus", INT2NUM(ret));
     return self;
 }
static VALUE guest_find (VALUE class, VALUE key) static
Definition at line 158 of file ext/dumm.c.
References guest_hash().
Referenced by guest_get(), and guest_init().
 {
     if (TYPE(key) != T_STRING)
     {
         key = rb_convert_type(key, T_STRING, "String", "to_s");
     }
     return rb_hash_aref(guest_hash(class), key);
 }
static VALUE guest_find_iface (VALUE self, VALUE key) static
Definition at line 287 of file ext/dumm.c.
References guest_t::create_iface_enumerator, enumerator_t::destroy, enumerator_t::enumerate, found, iface_t::get_guestif, rbc_iface, and streq().
Referenced by guest_get_iface(), and guest_init().
 {
     enumerator_t *enumerator;
     iface_t *iface, *found = NULL;
     guest_t *guest;
     if (TYPE(key) == T_SYMBOL)
     {
         key = rb_convert_type(key, T_STRING, "String", "to_s");
     }
     Data_Get_Struct(self, guest_t, guest);
     enumerator = guest->create_iface_enumerator(guest);
     while (enumerator->enumerate(enumerator, &iface))
     {
         if (streq(iface->get_guestif(iface), StringValuePtr(key)))
         {
             found = iface;
             break;
         }
     }
     enumerator->destroy(enumerator);
     if (!found)
     {
         return Qnil;
     }
     return Data_Wrap_Struct(rbc_iface, NULL, NULL, iface);
 }
static VALUE guest_get (VALUE class, VALUE key) static
Definition at line 167 of file ext/dumm.c.
References guest_find().
Referenced by guest_init().
 {
     return guest_find(class, key);
 }
static VALUE guest_get_iface (VALUE self, VALUE key) static
Definition at line 315 of file ext/dumm.c.
References guest_find_iface().
Referenced by guest_init().
 {
     VALUE iface = guest_find_iface(self, key);
     if (NIL_P(iface))
     {
         rb_raise(rb_eRuntimeError, "interface not found");
     }
     return iface;
 }
static VALUE guest_hash (VALUE class) static
Definition at line 142 of file ext/dumm.c.
References guest_hash_create(), and hash.
Referenced by guest_each(), guest_find(), and guest_new().
 {
     ID id = rb_intern("@@guests");
     if (!rb_cvar_defined(class, id))
     {
         VALUE hash = guest_hash_create(class);
 #ifdef RB_CVAR_SET_4_ARGS
         rb_cvar_set(class, id, hash, 0);
 #else
         rb_cvar_set(class, id, hash);
 #endif
         return hash;
     }
     return rb_cvar_get(class, id);
 }
static VALUE guest_hash_create (VALUE class) static
Guest bindings
Definition at line 127 of file ext/dumm.c.
References dumm_t::create_guest_enumerator, enumerator_t::destroy, enumerator_t::enumerate, guest_t::get_name, and hash.
Referenced by guest_hash().
 {
     enumerator_t *enumerator;
     guest_t *guest;
     VALUE hash = rb_hash_new();
     enumerator = dumm->create_guest_enumerator(dumm);
     while (enumerator->enumerate(enumerator, &guest))
     {
         rb_hash_aset(hash, rb_str_new2(guest->get_name(guest)),
                      Data_Wrap_Struct(class, NULL, NULL, guest));
     }
     enumerator->destroy(enumerator);
     return hash;
 }
static void guest_init () static
Definition at line 393 of file ext/dumm.c.
References guest_add_iface(), guest_add_overlay(), guest_del_overlay(), guest_delete(), guest_each(), guest_each_iface(), guest_exec(), guest_find(), guest_find_iface(), guest_get(), guest_get_iface(), guest_mconsole(), guest_new(), guest_pop_overlay(), guest_running(), guest_start(), guest_stop(), guest_to_s(), rbc_guest, and rbm_dumm.
Referenced by Init_dumm().
 {
     rbc_guest = rb_define_class_under(rbm_dumm , "Guest", rb_cObject);
     rb_include_module(rb_class_of(rbc_guest), rb_mEnumerable);
     rb_include_module(rbc_guest, rb_mEnumerable);
     rb_define_singleton_method(rbc_guest, "[]", guest_get, 1);
     rb_define_singleton_method(rbc_guest, "each", guest_each, -1);
     rb_define_singleton_method(rbc_guest, "new", guest_new, 4);
     rb_define_singleton_method(rbc_guest, "include?", guest_find, 1);
     rb_define_singleton_method(rbc_guest, "guest?", guest_find, 1);
     rb_define_method(rbc_guest, "to_s", guest_to_s, 0);
     rb_define_method(rbc_guest, "start", guest_start, 0);
     rb_define_method(rbc_guest, "stop", guest_stop, 0);
     rb_define_method(rbc_guest, "running?", guest_running, 0);
     rb_define_method(rbc_guest, "exec", guest_exec, 1);
     rb_define_method(rbc_guest, "mconsole", guest_mconsole, 1);
     rb_define_method(rbc_guest, "add", guest_add_iface, 1);
     rb_define_method(rbc_guest, "[]", guest_get_iface, 1);
     rb_define_method(rbc_guest, "each", guest_each_iface, -1);
     rb_define_method(rbc_guest, "include?", guest_find_iface, 1);
     rb_define_method(rbc_guest, "iface?", guest_find_iface, 1);
     rb_define_method(rbc_guest, "delete", guest_delete, 0);
     rb_define_method(rbc_guest, "add_overlay", guest_add_overlay, 1);
     rb_define_method(rbc_guest, "del_overlay", guest_del_overlay, 1);
     rb_define_method(rbc_guest, "pop_overlay", guest_pop_overlay, 0);
     rb_define_attr(rbc_guest, "execstatus", 1, 0);
 }
static VALUE guest_mconsole (VALUE self, VALUE cmd) static
Definition at line 257 of file ext/dumm.c.
References exec_cb(), guest_t::exec_str, and TRUE.
Referenced by guest_init().
 {
     guest_t *guest;
     bool block;
     int ret;
     block = rb_block_given_p();
     Data_Get_Struct(self, guest_t, guest);
     if ((ret = guest->exec_str(guest, block ? (void*)exec_cb : NULL, TRUE, NULL,
                     "%s", StringValuePtr(cmd))) != 0)
     {
         rb_raise(rb_eRuntimeError, "executing command failed (%d)", ret);
     }
     return self;
 }
static VALUE guest_new (VALUE class, VALUE name, VALUE kernel, VALUE master, VALUE args) static
Definition at line 183 of file ext/dumm.c.
References dumm_t::create_guest, and guest_hash().
Referenced by guest_init().
 {
     VALUE self;
     guest_t *guest;
     guest = dumm->create_guest(dumm, StringValuePtr(name),
                                StringValuePtr(kernel), StringValuePtr(master),
                                StringValuePtr(args));
     if (!guest)
     {
         rb_raise(rb_eRuntimeError, "creating guest failed");
     }
     self = Data_Wrap_Struct(class, NULL, NULL, guest);
     rb_hash_aset(guest_hash(class), name, self);
     return self;
 }
static VALUE guest_pop_overlay (VALUE self) static
Definition at line 385 of file ext/dumm.c.
References guest_t::pop_overlay.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     return guest->pop_overlay(guest) ? Qtrue : Qfalse;
 }
static VALUE guest_running (VALUE self) static
Definition at line 230 of file ext/dumm.c.
References guest_t::get_pid.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     return guest->get_pid(guest) ? Qtrue : Qfalse;
 }
static VALUE guest_start (VALUE self) static
Definition at line 208 of file ext/dumm.c.
References invoke(), and guest_t::start.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     if (!guest->start(guest, invoke, NULL, NULL))
     {
         rb_raise(rb_eRuntimeError, "starting guest failed");
     }
     return self;
 }
static VALUE guest_stop (VALUE self) static
Definition at line 221 of file ext/dumm.c.
References guest_t::stop.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     guest->stop(guest, NULL);
     return self;
 }
static VALUE guest_to_s (VALUE self) static
Definition at line 200 of file ext/dumm.c.
References guest_t::get_name.
Referenced by guest_init().
 {
     guest_t *guest;
     Data_Get_Struct(self, guest_t, guest);
     return rb_str_new2(guest->get_name(guest));
 }
static VALUE iface_add_addr (VALUE self, VALUE name) static
Definition at line 601 of file ext/dumm.c.
References iface_t::add_address, addr, bits, iface_t::delete_address, host_t::destroy, and host_create_from_subnet().
Referenced by iface_init().
 {
     iface_t *iface;
     host_t *addr;
     int bits;
     addr = host_create_from_subnet(StringValuePtr(name), &bits);
     if (!addr)
     {
         rb_raise(rb_eArgError, "invalid IP address");
     }
     Data_Get_Struct(self, iface_t, iface);
     if (!iface->add_address(iface, addr, bits))
     {
         addr->destroy(addr);
         rb_raise(rb_eRuntimeError, "adding address failed");
     }
     if (rb_block_given_p()) {
         rb_yield(self);
         iface->delete_address(iface, addr, bits);
     }
     addr->destroy(addr);
     return self;
 }
static VALUE iface_connect (VALUE self, VALUE vbridge) static
Definition at line 573 of file ext/dumm.c.
References bridge_t::connect_iface.
Referenced by iface_init().
 {
     iface_t *iface;
     bridge_t *bridge;
     Data_Get_Struct(self, iface_t, iface);
     Data_Get_Struct(vbridge, bridge_t, bridge);
     if (!bridge->connect_iface(bridge, iface))
     {
         rb_raise(rb_eRuntimeError, "connecting iface failed");
     }
     return self;
 }
static VALUE iface_del_addr (VALUE self, VALUE vaddr) static
Definition at line 656 of file ext/dumm.c.
References iface_t::add_address, addr, bits, iface_t::delete_address, host_t::destroy, and host_create_from_subnet().
Referenced by iface_init().
 {
     iface_t *iface;
     host_t *addr;
     int bits;
     addr = host_create_from_subnet(StringValuePtr(vaddr), &bits);
     if (!addr)
     {
         rb_raise(rb_eArgError, "invalid IP address");
     }
     Data_Get_Struct(self, iface_t, iface);
     if (!iface->delete_address(iface, addr, bits))
     {
         addr->destroy(addr);
         rb_raise(rb_eRuntimeError, "address not found");
     }
     if (rb_block_given_p()) {
         rb_yield(self);
         iface->add_address(iface, addr, bits);
     }
     addr->destroy(addr);
     return self;
 }
static VALUE iface_delete (VALUE self) static
Definition at line 681 of file ext/dumm.c.
References guest_t::destroy_iface, and iface_t::get_guest.
Referenced by iface_init().
 {
     guest_t *guest;
     iface_t *iface;
     Data_Get_Struct(self, iface_t, iface);
     guest = iface->get_guest(iface);
     guest->destroy_iface(guest, iface);
     return Qnil;
 }
static VALUE iface_disconnect (VALUE self) static
Definition at line 587 of file ext/dumm.c.
References bridge_t::disconnect_iface, and iface_t::get_bridge.
Referenced by iface_init().
 {
     iface_t *iface;
     bridge_t *bridge;
     Data_Get_Struct(self, iface_t, iface);
     bridge = iface->get_bridge(iface);
     if (!bridge || !bridge->disconnect_iface(bridge, iface))
     {
         rb_raise(rb_eRuntimeError, "disconnecting iface failed");
     }
     return self;
 }
static VALUE iface_each_addr (int argc, VALUE * argv, VALUE self) static
Definition at line 626 of file ext/dumm.c.
References addr, host_t::clone, iface_t::create_address_enumerator, enumerator_t::destroy, host_t::destroy, linked_list_t::destroy, enumerator_t::enumerate, linked_list_t::insert_last, linked_list_create(), list, linked_list_t::remove_first, snprintf, and SUCCESS.
Referenced by iface_init().
 {
     enumerator_t *enumerator;
     linked_list_t *list;
     iface_t *iface;
     host_t *addr;
     char buf[64], *fmt = "%H";
     if (!rb_block_given_p())
     {
         rb_raise(rb_eArgError, "must be called with a block");
     }
     list = linked_list_create();
     Data_Get_Struct(self, iface_t, iface);
     enumerator = iface->create_address_enumerator(iface);
     while (enumerator->enumerate(enumerator, &addr))
     {
         list->insert_last(list, addr->clone(addr));
     }
     enumerator->destroy(enumerator);
     while (list->remove_first(list, (void**)&addr) == SUCCESS)
     {
         snprintf(buf, sizeof(buf), fmt, addr);
         addr->destroy(addr);
         rb_yield(rb_str_new2(buf));
     }
     list->destroy(list);
     return self;
 }
static void iface_init () static
Definition at line 692 of file ext/dumm.c.
References iface_add_addr(), iface_connect(), iface_del_addr(), iface_delete(), iface_disconnect(), iface_each_addr(), iface_to_s(), rbc_iface, and rbm_dumm.
Referenced by Init_dumm().
 {
     rbc_iface = rb_define_class_under(rbm_dumm , "Iface", rb_cObject);
     rb_include_module(rbc_iface, rb_mEnumerable);
     rb_define_method(rbc_iface, "to_s", iface_to_s, 0);
     rb_define_method(rbc_iface, "connect", iface_connect, 1);
     rb_define_method(rbc_iface, "disconnect", iface_disconnect, 0);
     rb_define_method(rbc_iface, "add", iface_add_addr, 1);
     rb_define_method(rbc_iface, "del", iface_del_addr, 1);
     rb_define_method(rbc_iface, "each", iface_each_addr, -1);
     rb_define_method(rbc_iface, "delete", iface_delete, 0);
 }
static VALUE iface_to_s (VALUE self) static
Iface wrapper
Definition at line 565 of file ext/dumm.c.
References iface_t::get_hostif.
Referenced by iface_init().
 {
     iface_t *iface;
     Data_Get_Struct(self, iface_t, iface);
     return rb_str_new2(iface->get_hostif(iface));
 }
void Init_dumm ()
extension initialization
Definition at line 772 of file ext/dumm.c.
References bridge_init(), dumm_create(), dumm_init(), Final_dumm(), guest_init(), iface_init(), library_init(), setenv(), sigchld_handler(), and template_init().
 {
     struct sigaction action;
     /* there are too many to report, rubyruby... */
     setenv("LEAK_DETECTIVE_DISABLE", "1", 1);
     library_init(NULL, "dumm");
     dumm = dumm_create(NULL);
     dumm_init();
     guest_init();
     bridge_init();
     iface_init();
     template_init();
     sigemptyset(&action.sa_mask);
     action.sa_sigaction = sigchld_handler;
     action.sa_flags = SA_SIGINFO;
     sigaction(SIGCHLD, &action, NULL);
     rb_set_end_proc(Final_dumm, 0);
 }
static pid_t invoke (void * null, guest_t * guest, char * args[], int argc) static
Guest invocation callback
Definition at line 50 of file ext/dumm.c.
Referenced by guest_start(), and METHOD().
 {
     pid_t pid;
     pid = fork();
     switch (pid)
     {
         case 0: /* child */
             /* create a new process group in order to prevent signals (e.g.
              * SIGINT) sent to the parent from terminating the child */
             setpgid(0, 0);
             dup2(open("/dev/null", 0), 1);
             dup2(open("/dev/null", 0), 2);
             execvp(args[0], args);
             /* FALL */
         case -1:
             return 0;
         default:
             return pid;
     }
 }
static void sigchld_handler (int signal, siginfo_t * info, void * ptr) static
SIGCHLD signal handler
Definition at line 75 of file ext/dumm.c.
References dumm_t::create_guest_enumerator, enumerator_t::destroy, enumerator_t::enumerate, guest_t::get_pid, and guest_t::sigchild.
Referenced by Init_dumm().
 {
     enumerator_t *enumerator;
     guest_t *guest;
     enumerator = dumm->create_guest_enumerator(dumm);
     while (enumerator->enumerate(enumerator, &guest))
     {
         if (guest->get_pid(guest) == info->si_pid)
         {
             guest->sigchild(guest);
             break;
         }
     }
     enumerator->destroy(enumerator);
 }
static VALUE template_each (int argc, VALUE * argv, VALUE class) static
Definition at line 724 of file ext/dumm.c.
References dumm_t::create_template_enumerator, enumerator_t::destroy, and enumerator_t::enumerate.
Referenced by template_init().
 {
     enumerator_t *enumerator;
     char *template;
     if (!rb_block_given_p())
     {
         rb_raise(rb_eArgError, "must be called with a block");
     }
     enumerator = dumm->create_template_enumerator(dumm);
     while (enumerator->enumerate(enumerator, &template))
     {
         rb_yield(rb_str_new2(template));
     }
     enumerator->destroy(enumerator);
     return class;
 }
static void template_init () static
Definition at line 742 of file ext/dumm.c.
References rbc_template, rbm_dumm, template_each(), template_load(), and template_unload().
Referenced by Init_dumm().
 {
     rbc_template = rb_define_class_under(rbm_dumm , "Template", rb_cObject);
     rb_include_module(rb_class_of(rbc_template), rb_mEnumerable);
     rb_define_singleton_method(rbc_template, "load", template_load, 1);
     rb_define_singleton_method(rbc_template, "unload", template_unload, 0);
     rb_define_singleton_method(rbc_template, "each", template_each, -1);
 }
static VALUE template_load (VALUE class, VALUE dir) static
Definition at line 706 of file ext/dumm.c.
References dumm_t::load_template.
Referenced by template_init().
 {
     if (!dumm->load_template(dumm, StringValuePtr(dir)))
     {
         rb_raise(rb_eRuntimeError, "loading template failed");
     }
     return class;
 }
static VALUE template_unload (VALUE class) static
Definition at line 715 of file ext/dumm.c.
References dumm_t::load_template.
Referenced by template_init().
 {
     if (!dumm->load_template(dumm, NULL))
     {
         rb_raise(rb_eRuntimeError, "unloading template failed");
     }
     return class;
 }
Variable Documentation
dumm_t* dumm static
Definition at line 39 of file ext/dumm.c.
VALUE rbc_bridge static
Definition at line 43 of file ext/dumm.c.
Referenced by bridge_init().
VALUE rbc_guest static
Definition at line 42 of file ext/dumm.c.
Referenced by guest_init().
VALUE rbc_iface static
Definition at line 44 of file ext/dumm.c.
Referenced by bridge_each_iface(), guest_add_iface(), guest_each_iface(), guest_find_iface(), and iface_init().
VALUE rbc_template static
Definition at line 45 of file ext/dumm.c.
Referenced by template_init().
VALUE rbm_dumm static
Definition at line 41 of file ext/dumm.c.
Referenced by bridge_init(), dumm_init(), guest_init(), iface_init(), and template_init().