strongSwan: bliss_public_key
bliss_public_key
bliss
Classes
struct bliss_public_key_t
Typedefs
typedef struct bliss_public_key_t bliss_public_key_t
Functions
bliss_public_key_t * bliss_public_key_load (key_type_t type, va_list args)
bool bliss_public_key_from_asn1 (chunk_t object, bliss_param_set_t *set, uint32_t **pubkey)
chunk_t bliss_public_key_encode (uint32_t *pubkey, bliss_param_set_t *set)
chunk_t bliss_public_key_info_encode (int oid, uint32_t *pubkey, bliss_param_set_t *set)
bool bliss_public_key_fingerprint (int oid, uint32_t *pubkey, bliss_param_set_t *set, cred_encoding_type_t type, chunk_t *fp)
Detailed Description
Typedef Documentation
typedef struct bliss_public_key_t bliss_public_key_t
Definition at line 30 of file bliss_public_key.h.
Function Documentation
chunk_t bliss_public_key_encode (uint32_t * pubkey, bliss_param_set_t * set)
Encode a raw BLISS subjectPublicKey in ASN.1 DER format
Parameters
pubkey coefficients of public key vector
set BLISS parameter set for the public key vector
Returns
ASN.1 encoded subjectPublicKey
See header.
Definition at line 441 of file bliss_public_key.c.
References bliss_bitpacker_create(), bliss_bitpacker_t::destroy, encoding, bliss_bitpacker_t::extract_buf, bliss_param_set_t::n, bliss_param_set_t::q_bits, and bliss_bitpacker_t::write_bits.
Referenced by bliss_public_key_fingerprint(), bliss_public_key_info_encode(), and METHOD().
 {
     bliss_bitpacker_t *packer;
     chunk_t encoding;
     int i;
     packer = bliss_bitpacker_create(set->n * set->q_bits);
     for (i = 0; i < set->n; i++)
     {
         packer->write_bits(packer, pubkey[i], set->q_bits);
     }
     encoding = packer->extract_buf(packer);
     packer->destroy(packer);
     return encoding;
 }
bool bliss_public_key_fingerprint (int oid, uint32_t * pubkey, bliss_param_set_t * set, cred_encoding_type_t type, chunk_t * fp)
Generate a BLISS public key fingerprint
Parameters
oid BLISS public key type OID
pubkey coefficients of public key vector
set BLISS parameter set for the public key vector
type type of fingerprint to be generated
fp generated fingerprint (must be freed by caller)
Returns
TRUE if generation was successful
See header.
Definition at line 481 of file bliss_public_key.c.
References hasher_t::allocate_hash, bliss_public_key_encode(), bliss_public_key_info_encode(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, free(), HASH_SHA1, hasher, key, KEYID_PUBKEY_INFO_SHA1, KEYID_PUBKEY_SHA1, lib, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     hasher_t *hasher;
     chunk_t key;
     switch (type)
     {
         case KEYID_PUBKEY_SHA1:
             key = bliss_public_key_encode(pubkey, set);
             break;
         case KEYID_PUBKEY_INFO_SHA1:
             key = bliss_public_key_info_encode(oid, pubkey, set);
             break;
         default:
             return FALSE;
     }
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher || !hasher->allocate_hash(hasher, key, fp))
     {
         DBG1(DBG_LIB, "SHA1 hash algorithm not supported, fingerprinting failed");
         DESTROY_IF(hasher);
         free(key.ptr);
         return FALSE;
     }
     hasher->destroy(hasher);
     free(key.ptr);
     return TRUE;
 }
bool bliss_public_key_from_asn1 (chunk_t object, bliss_param_set_t * set, uint32_t ** pubkey)
Parse an ASN.1 BIT STRING into an array of public key coefficients
Parameters
object packed subjectPublicKey
set BLISS parameter set for public key vector
pubkey coefficients of public key vector
Returns
TRUE if parsing successful
See header.
Definition at line 402 of file bliss_public_key.c.
References bliss_bitpacker_create_from_data(), chunk_skip(), bliss_bitpacker_t::destroy, FALSE, len, malloc(), bliss_param_set_t::n, bliss_param_set_t::q, bliss_param_set_t::q_bits, bliss_bitpacker_t::read_bits, and TRUE.
Referenced by bliss_private_key_load(), and bliss_public_key_load().
 {
     bliss_bitpacker_t *packer;
     uint32_t coefficient;
     uint16_t needed_bits;
     int i;
     /* skip initial bit string octet defining unused bits */
     object = chunk_skip(object, 1);
     needed_bits = set->n * set->q_bits;
     if (8 * object.len < needed_bits)
     {
         return FALSE;
     }
     *pubkey = malloc(set->n * sizeof(uint32_t));
     packer = bliss_bitpacker_create_from_data(object);
     for (i = 0; i < set->n; i++)
     {
         packer->read_bits(packer, &coefficient, set->q_bits);
         if (coefficient >= set->q)
         {
             packer->destroy(packer);
             return FALSE;
         }
         (*pubkey)[i] = coefficient;
     }
     packer->destroy(packer);
     return TRUE;
 }
chunk_t bliss_public_key_info_encode (int oid, uint32_t * pubkey, bliss_param_set_t * set)
Encode a BLISS subjectPublicKeyInfo record in ASN.1 DER format
Parameters
oid BLISS public key type OID
pubkey coefficients of public key vector
set BLISS parameter set for the public key vector
Returns
ASN.1 encoded subjectPublicKeyInfo record
See header.
Definition at line 462 of file bliss_public_key.c.
References asn1_bitstring(), asn1_build_known_oid(), ASN1_SEQUENCE, asn1_wrap(), bliss_public_key_encode(), encoding, and OID_BLISS_PUBLICKEY.
Referenced by bliss_public_key_fingerprint(), and METHOD().
 {
     chunk_t encoding, pubkey_encoding;
     pubkey_encoding = bliss_public_key_encode(pubkey, set);
     encoding = asn1_wrap(ASN1_SEQUENCE, "mm",
                     asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_build_known_oid(OID_BLISS_PUBLICKEY),
                         asn1_build_known_oid(oid)),
                     asn1_bitstring("m", pubkey_encoding));
     return encoding;
 }
bliss_public_key_t* bliss_public_key_load (key_type_t type, va_list args)
Load a BLISS public key.
Accepts BUILD_BLISS_* components.
Parameters
type type of the key, must be KEY_BLISS
args builder_part_t argument list
Returns
loaded key, NULL on failure
See header.
Definition at line 301 of file bliss_public_key.c.
References asn1_known_oid(), ASN1_OID, asn1_parse_algorithmIdentifier(), asn1_parse_simple_object(), asn1_parser_create(), bliss_param_set_get_by_oid(), bliss_public_key_from_asn1(), BLISS_SUBJECT_PUBLIC_KEY, BLISS_SUBJECT_PUBLIC_KEY_ALGORITHM, blob, BUILD_BLOB_ASN1_DER, BUILD_END, chunk_empty, host_t::destroy, destroy(), end, FALSE, INIT, chunk_t::len, OID_BLISS_PUBLICKEY, OID_UNKNOWN, parser, public_key_equals(), public_key_has_fingerprint(), and TRUE.
Referenced by METHOD().
 {
     private_bliss_public_key_t *this;
     chunk_t blob = chunk_empty, object, param;
     asn1_parser_t *parser;
     bool success = FALSE;
     int objectID, oid;
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_BLOB_ASN1_DER:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_END:
                 break;
             default:
                 return NULL;
         }
         break;
     }
     if (blob.len == 0)
     {
         return NULL;
     }
     INIT(this,
         .public = {
             .key = {
                 .get_type = _get_type,
                 .verify = _verify,
                 .encrypt = _encrypt_,
                 .equals = public_key_equals,
                 .get_keysize = _get_keysize,
                 .get_fingerprint = _get_fingerprint,
                 .has_fingerprint = public_key_has_fingerprint,
                 .get_encoding = _get_encoding,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
         },
         .ref = 1,
     );
     parser = asn1_parser_create(pubkeyObjects, blob);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case BLISS_SUBJECT_PUBLIC_KEY_ALGORITHM:
             {
                 oid = asn1_parse_algorithmIdentifier(object,
                                 parser->get_level(parser)+1, &param);
                 if (oid != OID_BLISS_PUBLICKEY)
                 {
                     goto end;
                 }
                 if (!asn1_parse_simple_object(&param, ASN1_OID,
                                 parser->get_level(parser)+3, "blissKeyType"))
                 {
                     goto end;
                 }
                 oid = asn1_known_oid(param);
                 if (oid == OID_UNKNOWN)
                 {
                     goto end;
                 }
                 this->set = bliss_param_set_get_by_oid(oid);
                 if (this->set == NULL)
                 {
                     goto end;
                 }
                 break;
             }
             case BLISS_SUBJECT_PUBLIC_KEY:
                 if (!bliss_public_key_from_asn1(object, this->set, &this->A))
                 {
                     goto end;
                 }
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     if (!success)
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }