strongSwan: uci_control
uci_control
uci
Classes
struct uci_control_t
Typedefs
typedef struct uci_control_t uci_control_t
Functions
uci_control_t * uci_control_create ()
Detailed Description
Typedef Documentation
typedef struct uci_control_t uci_control_t
Definition at line 24 of file uci_control.h.
Function Documentation
uci_control_t* uci_control_create ()
Create a UCI based configuration backend.
Described in header.
Definition at line 277 of file uci_control.c.
References callback_job_create_with_prio(), DBG1, DBG_CFG, FIFO_FILE, INIT, JOB_PRIO_CRITICAL, lib, library_t::processor, processor_t::queue_job, receive(), return_false(), and strerror.
Referenced by uci_plugin_create().
 {
     private_uci_control_t *this;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
     );
     unlink(FIFO_FILE);
     if (mkfifo(FIFO_FILE, S_IRUSR|S_IWUSR) != 0)
     {
         DBG1(DBG_CFG, "creating UCI control fifo '%s' failed: %s",
              FIFO_FILE, strerror(errno));
     }
     else
     {
         lib->processor->queue_job(lib->processor,
             (job_t*)callback_job_create_with_prio((callback_job_cb_t)receive,
                             this, NULL, (callback_job_cancel_t)return_false,
                             JOB_PRIO_CRITICAL));
     }
     return &this->public;
 }