strongSwan: tnccs_msg
tnccs_msg
tnccs_11
Classes
struct tnccs_msg_t
Typedefs
typedef enum tnccs_msg_type_t tnccs_msg_type_t
typedef struct tnccs_msg_t tnccs_msg_t
Enumerations
enum tnccs_msg_type_t {
IMC_IMV_MSG = 0, TNCCS_MSG_RECOMMENDATION = 1, TNCCS_MSG_ERROR = 2, TNCCS_MSG_PREFERRED_LANGUAGE = 3,
TNCCS_MSG_REASON_STRINGS = 4, TNCCS_MSG_TNCS_CONTACT_INFO = 5, TNCCS_MSG_ROOF = 5
}
Functions
tnccs_msg_t * tnccs_msg_create_from_node (xmlNodePtr node, linked_list_t *errors)
Variables
enum_name_t * tnccs_msg_type_names
Detailed Description
Typedef Documentation
typedef struct tnccs_msg_t tnccs_msg_t
Definition at line 25 of file tnccs_msg.h.
typedef enum tnccs_msg_type_t tnccs_msg_type_t
Definition at line 24 of file tnccs_msg.h.
Enumeration Type Documentation
enum tnccs_msg_type_t
TNCC-TNCS messages as defined in section 2.8.5 of TCG TNC IF-TNCCS v1.2
Enumerator
IMC_IMV_MSG
TNCCS_MSG_RECOMMENDATION
TNCCS_MSG_ERROR
TNCCS_MSG_PREFERRED_LANGUAGE
TNCCS_MSG_REASON_STRINGS
TNCCS_MSG_TNCS_CONTACT_INFO
TNCCS_MSG_ROOF
Definition at line 34 of file tnccs_msg.h.
                       {
     IMC_IMV_MSG =                       0,
     TNCCS_MSG_RECOMMENDATION =          1,
     TNCCS_MSG_ERROR =                   2,
     TNCCS_MSG_PREFERRED_LANGUAGE =      3,
     TNCCS_MSG_REASON_STRINGS =          4,
     TNCCS_MSG_TNCS_CONTACT_INFO =       5,
     TNCCS_MSG_ROOF =                    5
 };
Function Documentation
tnccs_msg_t* tnccs_msg_create_from_node (xmlNodePtr node, linked_list_t * errors)
Create a pre-processed TNCCS message
Useful for the parser which wants a generic constructor for all tnccs_msg_t types.
Parameters
node TNCCS message node
errors linked list of TNCCS error messages
See header
Definition at line 39 of file tnccs_msg.c.
References BUF_LEN, DBG1, DBG2, DBG_TNC, enum_from_name, FALSE, found, IMC_IMV_MSG, imc_imv_msg_create_from_node(), linked_list_t::insert_last, msg, snprintf, streq(), TNCCS_ERROR_MALFORMED_BATCH, tnccs_error_msg_create(), tnccs_error_msg_create_from_node(), TNCCS_MSG_ERROR, TNCCS_MSG_PREFERRED_LANGUAGE, TNCCS_MSG_REASON_STRINGS, TNCCS_MSG_RECOMMENDATION, TNCCS_MSG_ROOF, TNCCS_MSG_TNCS_CONTACT_INFO, tnccs_msg_type_names, tnccs_preferred_language_msg_create_from_node(), tnccs_reason_strings_msg_create_from_node(), tnccs_recommendation_msg_create_from_node(), tnccs_tncs_contact_info_msg_create_from_node(), TRUE, and type.
Referenced by METHOD().
 {
     char *error_msg, buf[BUF_LEN];
     tnccs_error_type_t error_type = TNCCS_ERROR_MALFORMED_BATCH;
     tnccs_msg_t *msg;
     tnccs_msg_type_t type = IMC_IMV_MSG, nametype;
     if (streq((char*)node->name, "IMC-IMV-Message"))
     {
         DBG2(DBG_TNC, "processing %N message", tnccs_msg_type_names, type);
         return imc_imv_msg_create_from_node(node, errors);
     }
     else if (streq((char*)node->name, "TNCC-TNCS-Message"))
     {
         bool found = FALSE;
         xmlNsPtr ns = node->ns;
         xmlNodePtr cur = node->xmlChildrenNode;
         xmlNodePtr xml_msg_node = NULL;
         while (cur)
         {
             if (streq(cur->name, "Type") && cur->ns == ns)
             {
                 xmlChar *content = xmlNodeGetContent(cur);
                 type = strtol(content, NULL, 16);
                 xmlFree(content);
                 found = TRUE;
             }
             else if (streq(cur->name, "XML") && cur->ns == ns)
             {
                 xml_msg_node = cur->xmlChildrenNode;
             }
             cur = cur->next;
         }
         if (!found)
         {
             error_msg = "Type is missing in TNCC-TNCS-Message";
             goto fatal;
         }
         if (!xml_msg_node)
         {
             error_msg = "XML node is missing in TNCC-TNCS-Message";
             goto fatal;
         }
         cur = xml_msg_node;
         /* skip empty and blank nodes */
         while (cur && xmlIsBlankNode(cur))
         {
             cur = cur->next;
         }
         if (!cur)
         {
             error_msg = "XML node is empty";
             goto fatal;
         }
         /* check if TNCCS message type and node name agree */
         if (type >= TNCCS_MSG_RECOMMENDATION && type <= TNCCS_MSG_ROOF)
         {
             DBG2(DBG_TNC, "processing %N message", tnccs_msg_type_names, type);
             if (cur->ns != ns)
             {
                 error_msg = "node is not in the TNCCS message namespace";
                 goto fatal;
             }
             if (!enum_from_name(tnccs_msg_type_names, cur->name, &nametype) ||
                 type != nametype)
             {
                 error_msg = buf;
                 snprintf(buf, BUF_LEN, "expected '%N' node but was '%s'",
                          tnccs_msg_type_names, type, (char*)cur->name);
                 goto fatal;
             }
         }
         switch (type)
         {
             case TNCCS_MSG_RECOMMENDATION:
                 return tnccs_recommendation_msg_create_from_node(cur, errors);
             case TNCCS_MSG_ERROR:
                 return tnccs_error_msg_create_from_node(cur);
             case TNCCS_MSG_PREFERRED_LANGUAGE:
                 return tnccs_preferred_language_msg_create_from_node(cur, errors);
             case TNCCS_MSG_REASON_STRINGS:
                 return tnccs_reason_strings_msg_create_from_node(cur, errors);
             case TNCCS_MSG_TNCS_CONTACT_INFO:
                 return tnccs_tncs_contact_info_msg_create_from_node(cur, errors);
             default:
                 DBG1(DBG_TNC, "ignoring TNCC-TNCS-Message with type %d", type);
                 return NULL;
         }
     }
     DBG1(DBG_TNC, "ignoring unknown message node '%s'", (char*)node->name);
     return NULL;
 fatal:
     msg = tnccs_error_msg_create(error_type, error_msg);
     errors->insert_last(errors, msg);
     return NULL;
 }
Variable Documentation
enum_name_t* tnccs_msg_type_names
enum name for tnccs_msg_type_t.
Referenced by METHOD(), tnccs_error_msg_create(), tnccs_msg_create_from_node(), tnccs_preferred_language_msg_create(), tnccs_reason_strings_msg_create(), and tnccs_recommendation_msg_create().