strongSwan: fast_smtp
fast_smtp
libfast
Classes
struct fast_smtp_t
Typedefs
typedef struct fast_smtp_t fast_smtp_t
Functions
fast_smtp_t * fast_smtp_create ()
Detailed Description
Typedef Documentation
typedef struct fast_smtp_t fast_smtp_t
Definition at line 24 of file fast_smtp.h.
Function Documentation
fast_smtp_t* fast_smtp_create ()
Create a smtp instance.
See header
Definition at line 136 of file fast_smtp.c.
References close, connect, DBG1, DBG_LIB, free(), INIT, read_response(), s, socket, strerror, and write_cmd().
 {
     private_fast_smtp_t *this;
     struct sockaddr_in addr = {
         .sin_family = AF_INET,
         .sin_port = htons(25),
         .sin_addr = {
             .s_addr = htonl(INADDR_LOOPBACK),
         },
     };
     int s;
     INIT(this,
         .public = {
             .send_mail = _send_mail,
             .destroy = _destroy,
         },
     );
     s = socket(AF_INET, SOCK_STREAM, 0);
     if (s < 0)
     {
         DBG1(DBG_LIB, "opening SMTP socket failed: %s", strerror(errno));
         free(this);
         return NULL;
     }
     if (connect(s, (struct sockaddr*)&addr, sizeof(addr)) < 0)
     {
         DBG1(DBG_LIB, "connecting to SMTP server failed: %s", strerror(errno));
         close(s);
         free(this);
         return NULL;
     }
     this->f = fdopen(s, "a+");
     if (!this->f)
     {
         DBG1(DBG_LIB, "opening stream to SMTP server failed: %s",
              strerror(errno));
         close(s);
         free(this);
         return NULL;
     }
     if (read_response(this) != 220 ||
         write_cmd(this, "EHLO localhost") != 250)
     {
         DBG1(DBG_LIB, "SMTP EHLO failed");
         fclose(this->f);
         free(this);
         return NULL;
     }
     return &this->public;
 }