strongSwan: ietf_attr_fwd_enabled.c File Reference
ietf_attr_fwd_enabled.c File Reference
#include "ietf_attr_fwd_enabled.h"
#include <pa_tnc/pa_tnc_msg.h>
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_ietf_attr_fwd_enabled_t
Macros
#define FORWARDING_ENABLED_SIZE 4
Typedefs
typedef struct
private_ietf_attr_fwd_enabled_t private_ietf_attr_fwd_enabled_t
Functions
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ietf_attr_fwd_enabled_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ietf_attr_fwd_enabled_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ietf_attr_fwd_enabled_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ietf_attr_fwd_enabled_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ietf_attr_fwd_enabled_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ietf_attr_fwd_enabled_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ietf_attr_fwd_enabled_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ietf_attr_fwd_enabled_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ietf_attr_fwd_enabled_t *this)
METHOD (ietf_attr_fwd_enabled_t, get_status, os_fwd_status_t, private_ietf_attr_fwd_enabled_t *this)
pa_tnc_attr_t * ietf_attr_fwd_enabled_create (os_fwd_status_t fwd_status, pen_type_t type)
pa_tnc_attr_t * ietf_attr_fwd_enabled_create_from_data (size_t length, chunk_t data, pen_type_t type)
Macro Definition Documentation
#define FORWARDING_ENABLED_SIZE 4
PA-TNC Forwarding Enabled type (see section 4.2.11 of RFC 5792)
                  1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Forwarding Enabled | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 35 of file ietf_attr_fwd_enabled.c.
Referenced by METHOD().
Typedef Documentation
typedef struct private_ietf_attr_fwd_enabled_t private_ietf_attr_fwd_enabled_t
Definition at line 23 of file ietf_attr_fwd_enabled.c.
Function Documentation
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ietf_attr_fwd_enabled_t * this)
Definition at line 78 of file ietf_attr_fwd_enabled.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ietf_attr_fwd_enabled_t * this)
Definition at line 84 of file ietf_attr_fwd_enabled.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ietf_attr_fwd_enabled_t * this)
Definition at line 90 of file ietf_attr_fwd_enabled.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ietf_attr_fwd_enabled_t * this, bool noskip)
Definition at line 96 of file ietf_attr_fwd_enabled.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ietf_attr_fwd_enabled_t * this)
Definition at line 102 of file ietf_attr_fwd_enabled.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::extract_buf, FORWARDING_ENABLED_SIZE, length, value, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(FORWARDING_ENABLED_SIZE);
     writer->write_uint32(writer, this->fwd_status);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ietf_attr_fwd_enabled_t * this, u_int32_t * offset)
Definition at line 119 of file ietf_attr_fwd_enabled.c.
References bio_reader_create(), DBG1, DBG_TNC, bio_reader_t::destroy, FAILED, FORWARDING_ENABLED_SIZE, NEED_MORE, OS_FWD_UNKNOWN, bio_reader_t::read_uint32, SUCCESS, and value.
 {
     bio_reader_t *reader;
     u_int32_t fwd_status;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len != FORWARDING_ENABLED_SIZE)
     {
         DBG1(DBG_TNC, "incorrect size for IETF forwarding enabled attribute");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint32(reader, &fwd_status);
     reader->destroy(reader);
     if (fwd_status > OS_FWD_UNKNOWN)
     {
         DBG1(DBG_TNC, "IETF forwarding enabled field has unknown value %u",
                        fwd_status);
         return FAILED;
     }
     this->fwd_status = fwd_status;
     return SUCCESS;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ietf_attr_fwd_enabled_t * this, chunk_t segment)
Definition at line 151 of file ietf_attr_fwd_enabled.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ietf_attr_fwd_enabled_t * this)
Definition at line 157 of file ietf_attr_fwd_enabled.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ietf_attr_fwd_enabled_t * this)
Definition at line 164 of file ietf_attr_fwd_enabled.c.
References free(), ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ietf_attr_fwd_enabled_t , get_status , os_fwd_status_t , private_ietf_attr_fwd_enabled_t * this)
Definition at line 174 of file ietf_attr_fwd_enabled.c.
 {
     return this->fwd_status;
 }