strongSwan: time
time
utils
Macros
#define UNDEFINED_TIME 0
#define TIME_32_BIT_SIGNED_MAX 0x7fffffff
Typedefs
typedef struct timeval timeval_t
typedef struct timespec timespec_t
Functions
time_t time_monotonic (timeval_t *tv)
static void timeval_add_ms (timeval_t *tv, u_int ms)
int time_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
int time_delta_printf_hook (printf_hook_data_t *data, printf_hook_spec_t *spec, const void *const *args)
Detailed Description
Macro Definition Documentation
#define TIME_32_BIT_SIGNED_MAX 0x7fffffff
Maximum time since epoch causing wrap-around on Jan 19 03:14:07 UTC 2038
Definition at line 33 of file time.h.
Referenced by asn1_to_time(), METHOD(), and stroke_list_pgp().
#define UNDEFINED_TIME 0
time_t not defined
Definition at line 28 of file time.h.
Referenced by add_op_status(), load(), measurement_time_to_utc(), METHOD(), parse_singleResponse(), pubkey_cert_wrap(), stroke_list_pubkeys(), time_printf_hook(), and verify().
Typedef Documentation
typedef struct timespec timespec_t
Handle struct timespec like an own type.
Definition at line 43 of file time.h.
typedef struct timeval timeval_t
Handle struct timeval like an own type.
Definition at line 38 of file time.h.
Function Documentation
int time_delta_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook for time_t deltas.
Arguments are: time_t* begin, time_t* end
Described in header.
Definition at line 118 of file time.c.
References print_in_hook(), and PRIu64.
Referenced by library_init().
 {
     char* unit = "second";
     time_t *arg1 = *((time_t**)(args[0]));
     time_t *arg2 = *((time_t**)(args[1]));
     u_int64_t delta = llabs(*arg1 - *arg2);
     if (delta > 2 * 60 * 60 * 24)
     {
         delta /= 60 * 60 * 24;
         unit = "day";
     }
     else if (delta > 2 * 60 * 60)
     {
         delta /= 60 * 60;
         unit = "hour";
     }
     else if (delta > 2 * 60)
     {
         delta /= 60;
         unit = "minute";
     }
     return print_in_hook(data, "%" PRIu64 " %s%s", delta, unit,
                          (delta == 1) ? "" : "s");
 }
time_t time_monotonic (timeval_t * tv)
Get a timestamp from a monotonic time source.
While the time()/gettimeofday() functions are affected by leap seconds and system time changes, this function returns ever increasing monotonic time stamps.
Parameters
tv timeval struct receiving monotonic timestamps, or NULL
Returns
monotonic timestamp in seconds
Return monotonic time
Definition at line 31 of file time.c.
References s.
Referenced by add_auth_lifetime(), CALLBACK(), check_timeouts(), child_sa_create(), cookie_verify(), dispatch(), dpd_timeout_job_create(), drop_ike_sa_init(), fast_dispatcher_create(), fire_roam_event(), get_or_create_entry(), ike_sa_create(), log_child_sa(), log_ike_sa(), main(), METHOD(), process_dpd(), process_request(), queue_route_reinstall(), receiver_create(), schedule(), send_interim(), send_stop(), session_entry_create(), START_TEST(), stroke_list_create(), and vici_query_create().
 {
 #ifdef WIN32
     ULONGLONG ms;
     time_t s;
     ms = GetTickCount64();
     s = ms / 1000;
     if (tv)
     {
         tv->tv_sec = s;
         tv->tv_usec = (ms - (s * 1000)) * 1000;
     }
     return s;
 #else /* !WIN32 */
 #if defined(HAVE_CLOCK_GETTIME) && \
     (defined(HAVE_CONDATTR_CLOCK_MONOTONIC) || \
      defined(HAVE_PTHREAD_COND_TIMEDWAIT_MONOTONIC))
     /* as we use time_monotonic() for condvar operations, we use the
      * monotonic time source only if it is also supported by pthread. */
     timespec_t ts;
     if (clock_gettime(CLOCK_MONOTONIC, &ts) == 0)
     {
         if (tv)
         {
             tv->tv_sec = ts.tv_sec;
             tv->tv_usec = ts.tv_nsec / 1000;
         }
         return ts.tv_sec;
     }
 #endif /* HAVE_CLOCK_GETTIME && (...) */
     /* Fallback to non-monotonic timestamps:
      * On MAC OS X, creating monotonic timestamps is rather difficult. We
      * could use mach_absolute_time() and catch sleep/wakeup notifications.
      * We stick to the simpler (non-monotonic) gettimeofday() for now.
      * But keep in mind: we need the same time source here as in condvar! */
     if (!tv)
     {
         return time(NULL);
     }
     if (gettimeofday(tv, NULL) != 0)
     {   /* should actually never fail if passed pointers are valid */
         return -1;
     }
     return tv->tv_sec;
 #endif /* !WIN32 */
 }
int time_printf_hook (printf_hook_data_t * data, printf_hook_spec_t * spec, const void *const * args)
printf hook for time_t.
Arguments are: time_t* time, bool utc
Described in header.
Definition at line 83 of file time.c.
References gmtime_r(), localtime_r(), print_in_hook(), UNDEFINED_TIME, and utc.
Referenced by library_init().
 {
     static const char* months[] = {
         "Jan", "Feb", "Mar", "Apr", "May", "Jun",
         "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
     };
     time_t *time = *((time_t**)(args[0]));
     bool utc = *((int*)(args[1]));
     struct tm t, *ret = NULL;
     if (*time != UNDEFINED_TIME)
     {
         if (utc)
         {
             ret = gmtime_r(time, &t);
         }
         else
         {
             ret = localtime_r(time, &t);
         }
     }
     if (ret == NULL)
     {
         return print_in_hook(data, "--- -- --:--:--%s----",
                              utc ? " UTC " : " ");
     }
     return print_in_hook(data, "%s %02d %02d:%02d:%02d%s%04d",
                          months[t.tm_mon], t.tm_mday, t.tm_hour, t.tm_min,
                          t.tm_sec, utc ? " UTC " : " ", t.tm_year + 1900);
 }
static void timeval_add_ms (timeval_t * tv, u_int ms) inline static
Add the given number of milliseconds to the given timeval struct
Parameters
tv timeval struct to modify
ms number of milliseconds
Definition at line 63 of file time.h.
Referenced by fire_roam_event(), METHOD(), queue_route_reinstall(), read_msg(), and START_TEST().
 {
     tv->tv_usec += ms * 1000;
     while (tv->tv_usec >= 1000000 /* 1s */)
     {
         tv->tv_usec -= 1000000;
         tv->tv_sec++;
     }
 }