strongSwan: array.c File Reference
array.c File Reference
#include <stdlib.h>
#include "array.h"
#include <threading/thread_value.h>
Classes
struct array_t
struct array_enumerator_t
struct sort_data_t
struct bsearch_data_t
Macros
#define _GNU_SOURCE /* for qsort_r() */
#define ARRAY_MAX_UNUSED 32
Functions
static size_t get_size (array_t *array, u_int32_t num)
static void make_tail_room (array_t *array, u_int8_t room)
static void make_head_room (array_t *array, u_int8_t room)
static void insert_tail (array_t *array, int idx)
static void insert_head (array_t *array, int idx)
static void remove_tail (array_t *array, int idx)
static void remove_head (array_t *array, int idx)
array_t * array_create (u_int esize, u_int8_t reserve)
int array_count (array_t *array)
void array_compress (array_t *array)
METHOD (enumerator_t, enumerate, bool, array_enumerator_t *this, void **out)
enumerator_t * array_create_enumerator (array_t *array)
void array_remove_at (array_t *array, enumerator_t *public)
void array_insert_create (array_t **array, int idx, void *ptr)
void array_insert_enumerator (array_t *array, int idx, enumerator_t *enumerator)
void array_insert (array_t *array, int idx, void *data)
bool array_get (array_t *array, int idx, void *data)
bool array_remove (array_t *array, int idx, void *data)
static int compare_elements (const void *a, const void *b)
void array_sort (array_t *array, int(*cmp)(const void *, const void *, void *), void *user)
static int search_elements (const void *a, const void *b)
int array_bsearch (array_t *array, const void *key, int(*cmp)(const void *, const void *), void *out)
void array_invoke (array_t *array, array_callback_t cb, void *user)
void array_invoke_offset (array_t *array, size_t offset)
void array_destroy (array_t *array)
void array_destroy_function (array_t *array, array_callback_t cb, void *user)
void array_destroy_offset (array_t *array, size_t offset)
void arrays_init ()
void arrays_deinit ()
Variables
static thread_value_t * sort_data
Macro Definition Documentation
#define _GNU_SOURCE /* for qsort_r() */
Definition at line 19 of file array.c.
#define ARRAY_MAX_UNUSED 32
maximum number of unused head/tail elements before cleanup
Definition at line 62 of file array.c.
Referenced by array_remove().
Function Documentation
static int compare_elements (const void * a, const void * b) static
Definition at line 397 of file array.c.
References sort_data_t::arg, sort_data_t::array, sort_data_t::cmp, data, array_t::esize, and thread_value_t::get.
Referenced by array_sort().
 {
 #ifdef HAVE_QSORT_R
     sort_data_t *data = (sort_data_t*)arg;
 #else
     sort_data_t *data = sort_data->get(sort_data);
 #endif
     if (data->array->esize)
     {
         return data->cmp(a, b, data->arg);
     }
     return data->cmp(*(void**)a, *(void**)b, data->arg);
 }
static size_t get_size (array_t * array, u_int32_t num) static
Get the actual size of a number of elements
Definition at line 67 of file array.c.
References array_t::esize.
Referenced by array_bsearch(), array_compress(), array_create(), array_get(), array_insert(), array_invoke(), array_invoke_offset(), array_sort(), insert_head(), insert_tail(), make_head_room(), make_tail_room(), METHOD(), remove_head(), and remove_tail().
 {
     if (array->esize)
     {
         return array->esize * num;
     }
     return sizeof(void*) * num;
 }
static void insert_head (array_t * array, int idx) static
Make space for an item at index using head room
Definition at line 124 of file array.c.
References array_t::count, array_t::data, get_size(), array_t::head, make_head_room(), and memmove.
Referenced by array_insert().
 {
     make_head_room(array, 1);
     /* move down all elements before idx by one */
     memmove(array->data + get_size(array, array->head - 1),
             array->data + get_size(array, array->head),
             get_size(array, idx));
     array->head--;
     array->count++;
 }
static void insert_tail (array_t * array, int idx) static
Make space for an item at index using tail room
Definition at line 109 of file array.c.
References array_t::count, array_t::data, get_size(), array_t::head, make_tail_room(), memmove, and array_t::tail.
Referenced by array_insert().
 {
     make_tail_room(array, 1);
     /* move up all elements after idx by one */
     memmove(array->data + get_size(array, array->head + idx + 1),
             array->data + get_size(array, array->head + idx),
             get_size(array, array->count - idx));
     array->tail--;
     array->count++;
 }
static void make_head_room (array_t * array, u_int8_t room) static
Increase allocated but unused head room to at least "room"
Definition at line 92 of file array.c.
References array_t::count, array_t::data, get_size(), array_t::head, increase(), memmove, and array_t::tail.
Referenced by insert_head().
 {
     if (array->head < room)
     {
         u_int8_t increase = room - array->head;
         array->data = realloc(array->data,
                         get_size(array, array->count + array->tail + room));
         memmove(array->data + get_size(array, increase), array->data,
                 get_size(array, array->count + array->tail + array->head));
         array->head = room;
     }
 }
static void make_tail_room (array_t * array, u_int8_t room) static
Increase allocated but unused tail room to at least "room"
Definition at line 79 of file array.c.
References array_t::count, array_t::data, get_size(), array_t::head, and array_t::tail.
Referenced by insert_tail().
 {
     if (array->tail < room)
     {
         array->data = realloc(array->data,
                         get_size(array, array->count + array->head + room));
         array->tail = room;
     }
 }
METHOD (enumerator_t , enumerate , bool , array_enumerator_t * this, void ** out)
Definition at line 216 of file array.c.
References FALSE, get_size(), and TRUE.
 {
     void *pos;
     if (this->idx >= this->array->count)
     {
         return FALSE;
     }
     pos = this->array->data +
           get_size(this->array, this->idx + this->array->head);
     if (this->array->esize)
     {
         /* for element based arrays we return a pointer to the element */
         *out = pos;
     }
     else
     {
         /* for pointer based arrays we return the pointer directly */
         *out = *(void**)pos;
     }
     this->idx++;
     return TRUE;
 }
static void remove_head (array_t * array, int idx) static
Remove an item, increase head
Definition at line 152 of file array.c.
References array_t::count, array_t::data, get_size(), array_t::head, and memmove.
Referenced by array_remove().
 {
     /* move all items before idx one up */
     memmove(array->data + get_size(array, array->head + 1),
             array->data + get_size(array, array->head), get_size(array, idx));
     array->count--;
     array->head++;
 }
static void remove_tail (array_t * array, int idx) static
Remove an item, increase tail
Definition at line 139 of file array.c.
References array_t::count, array_t::data, get_size(), array_t::head, memmove, and array_t::tail.
Referenced by array_remove().
 {
     /* move all items after idx one down */
     memmove(array->data + get_size(array, idx + array->head),
             array->data + get_size(array, idx + array->head + 1),
             get_size(array, array->count - 1 - idx));
     array->count--;
     array->tail++;
 }
static int search_elements (const void * a, const void * b) static
Definition at line 449 of file array.c.
References bsearch_data_t::array, bsearch_data_t::cmp, data, array_t::esize, and bsearch_data_t::key.
Referenced by array_bsearch().
 {
     bsearch_data_t *data = (bsearch_data_t*)a;
     if (data->array->esize)
     {
         return data->cmp(data->key, b);
     }
     return data->cmp(data->key, *(void**)b);
 }
Variable Documentation
thread_value_t* sort_data static
Definition at line 58 of file array.c.