strongSwan: shared_key.c File Reference
shared_key.c File Reference
#include "shared_key.h"
Classes
struct private_shared_key_t
Typedefs
typedef struct private_shared_key_t private_shared_key_t
Functions
ENUM (shared_key_type_names, SHARED_ANY, SHARED_PIN,"ANY","IKE","EAP","PRIVATE_KEY_PASS","PIN",)
METHOD (shared_key_t, get_type, shared_key_type_t, private_shared_key_t *this)
METHOD (shared_key_t, get_key, chunk_t, private_shared_key_t *this)
METHOD (shared_key_t, get_ref, shared_key_t *, private_shared_key_t *this)
METHOD (shared_key_t, destroy, void, private_shared_key_t *this)
shared_key_t * shared_key_create (shared_key_type_t type, chunk_t key)
Typedef Documentation
typedef struct private_shared_key_t private_shared_key_t
Definition at line 26 of file shared_key.c.
Function Documentation
ENUM (shared_key_type_names , SHARED_ANY , SHARED_PIN , "ANY" , "IKE" , "EAP" , "PRIVATE_KEY_PASS" , "PIN")
METHOD (shared_key_t , get_type , shared_key_type_t , private_shared_key_t * this)
Definition at line 54 of file shared_key.c.
References type.
 {
     return this->type;
 }
METHOD (shared_key_t , get_key , chunk_t , private_shared_key_t * this)
Definition at line 60 of file shared_key.c.
References key.
 {
     return this->key;
 }
METHOD (shared_key_t , get_ref , shared_key_t * , private_shared_key_t * this)
Definition at line 66 of file shared_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public;
 }
METHOD (shared_key_t , destroy , void , private_shared_key_t * this)
Definition at line 73 of file shared_key.c.
References free(), key, and ref_put().
 {
     if (ref_put(&this->ref))
     {
         free(this->key.ptr);
         free(this);
     }
 }