strongSwan: ipsec_sa_t Struct Reference
ipsec_sa_t Struct Reference
ipsec_sa
#include "ipsec_sa.h"
Public Attributes
host_t * src
host_t * dst
mark_t mark
ipsec_sa_cfg_t cfg
refcount_t refcount
host_t *(* get_source)(ipsec_sa_t *this)
host_t *(* get_destination)(ipsec_sa_t *this)
void(* set_source)(ipsec_sa_t *this, host_t *addr)
void(* set_destination)(ipsec_sa_t *this, host_t *addr)
u_int32_t(* get_spi)(ipsec_sa_t *this)
u_int32_t(* get_reqid)(ipsec_sa_t *this)
u_int8_t(* get_protocol)(ipsec_sa_t *this)
bool(* is_inbound)(ipsec_sa_t *this)
lifetime_cfg_t *(* get_lifetime)(ipsec_sa_t *this)
esp_context_t *(* get_esp_context)(ipsec_sa_t *this)
void(* get_usestats)(ipsec_sa_t *this, u_int64_t *bytes, u_int64_t *packets, time_t *time)
void(* update_usestats)(ipsec_sa_t *this, u_int32_t bytes)
void(* expire)(ipsec_sa_t *this, bool hard)
bool(* match_by_spi_dst)(ipsec_sa_t *this, u_int32_t spi, host_t *dst)
bool(* match_by_spi_src_dst)(ipsec_sa_t *this, u_int32_t spi, host_t *src, host_t *dst)
bool(* match_by_reqid)(ipsec_sa_t *this, u_int32_t reqid, bool inbound)
void(* destroy)(ipsec_sa_t *this)
Detailed Description
IPsec SA assigned to a policy.
IPsec Security Association (SA)
Definition at line 381 of file kernel_netlink_ipsec.c.
Member Data Documentation
ipsec_sa_cfg_t ipsec_sa_t::cfg
Description of this SA
Definition at line 392 of file kernel_netlink_ipsec.c.
Referenced by add_policy_internal(), ipsec_sa_equals(), ipsec_sa_hash(), and process_acquire().
void(* ipsec_sa_t::destroy)(ipsec_sa_t *this)
Destroy an ipsec_sa_t
Definition at line 175 of file ipsec_sa.h.
Referenced by destroy_entry(), and METHOD().
host_t * ipsec_sa_t::dst
Destination address of this SA
Definition at line 386 of file kernel_netlink_ipsec.c.
Referenced by add_policy_internal(), install_route(), ipsec_sa_create(), ipsec_sa_destroy(), ipsec_sa_equals(), and ipsec_sa_hash().
void(* ipsec_sa_t::expire)(ipsec_sa_t *this, bool hard)
Expire this SA, soft or hard.
A soft expire triggers a rekey, a hard expire blocks the SA and triggers a delete for the SA.
Parameters
hard TRUE for hard, FALSE for soft
Definition at line 137 of file ipsec_sa.h.
Referenced by sa_expired().
host_t*(* ipsec_sa_t::get_destination)(ipsec_sa_t *this)
Get the destination address for this SA
Returns
destination address of this SA
Definition at line 52 of file ipsec_sa.h.
Referenced by process_outbound().
esp_context_t*(* ipsec_sa_t::get_esp_context)(ipsec_sa_t *this)
Get the ESP context for this SA
Returns
ESP context of this SA
Definition at line 110 of file ipsec_sa.h.
Referenced by process_inbound(), and process_outbound().
lifetime_cfg_t*(* ipsec_sa_t::get_lifetime)(ipsec_sa_t *this)
Get the lifetime information for this SA Note that this information is always relative to the time when the SA was installed (i.e. it is not adjusted over time)
Returns
lifetime of this SA
Definition at line 103 of file ipsec_sa.h.
Referenced by schedule_expiration().
u_int8_t(* ipsec_sa_t::get_protocol)(ipsec_sa_t *this)
Get the protocol (e.g. IPPROTO_ESP) of this SA
Returns
protocol of this SA
Definition at line 87 of file ipsec_sa.h.
u_int32_t(* ipsec_sa_t::get_reqid)(ipsec_sa_t *this)
Get the reqid of this SA
Returns
reqid of this SA
Definition at line 80 of file ipsec_sa.h.
Referenced by process_inbound().
host_t*(* ipsec_sa_t::get_source)(ipsec_sa_t *this)
Get the source address for this SA
Returns
source address of this SA
Definition at line 45 of file ipsec_sa.h.
Referenced by process_outbound().
u_int32_t(* ipsec_sa_t::get_spi)(ipsec_sa_t *this)
Get the SPI for this SA
Returns
SPI of this SA
Definition at line 73 of file ipsec_sa.h.
Referenced by match_entry_by_spi_inbound(), and process_outbound().
void(* ipsec_sa_t::get_usestats)(ipsec_sa_t *this, u_int64_t *bytes, u_int64_t *packets, time_t *time)
Get usage statistics for this SA.
Parameters
bytes receives number of processed bytes, or NULL
packets receives number of processed packets, or NULL
time receives last use time of this SA, or NULL
Definition at line 119 of file ipsec_sa.h.
Referenced by METHOD().
bool(* ipsec_sa_t::is_inbound)(ipsec_sa_t *this)
Returns whether this SA is inbound or outbound
Returns
TRUE if inbound, FALSE if outbound
Definition at line 94 of file ipsec_sa.h.
Referenced by match_entry_by_spi_inbound(), METHOD(), and process_inbound().
mark_t ipsec_sa_t::mark
Optional mark
Definition at line 389 of file kernel_netlink_ipsec.c.
Referenced by add_policy_internal(), ipsec_sa_equals(), and ipsec_sa_hash().
bool(* ipsec_sa_t::match_by_reqid)(ipsec_sa_t *this, u_int32_t reqid, bool inbound)
Check if this SA matches all given parameters
Only matches if the SA has not yet expired.
Parameters
reqid reqid
inbound TRUE for inbound SA, FALSE for outbound
Returns
TRUE if this SA matches all parameters, FALSE otherwise
Definition at line 170 of file ipsec_sa.h.
Referenced by match_entry_by_reqid_inbound().
bool(* ipsec_sa_t::match_by_spi_dst)(ipsec_sa_t *this, u_int32_t spi, host_t *dst)
Check if this SA matches all given parameters
Only matches if the SA has not yet expired.
Parameters
spi SPI
dst destination address
Returns
TRUE if this SA matches all parameters, FALSE otherwise
Definition at line 148 of file ipsec_sa.h.
Referenced by match_entry_by_spi_dst().
bool(* ipsec_sa_t::match_by_spi_src_dst)(ipsec_sa_t *this, u_int32_t spi, host_t *src, host_t *dst)
Check if this SA matches all given parameters
Parameters
spi SPI
src source address
dst destination address
Returns
TRUE if this SA matches all parameters, FALSE otherwise
Definition at line 158 of file ipsec_sa.h.
Referenced by match_entry_by_spi_src_dst().
refcount_t ipsec_sa_t::refcount
Reference count for this SA
Definition at line 395 of file kernel_netlink_ipsec.c.
Referenced by ipsec_sa_create(), and ipsec_sa_destroy().
void(* ipsec_sa_t::set_destination)(ipsec_sa_t *this, host_t *addr)
Set the destination address for this SA
Parameters
addr destination address of this SA (gets cloned)
Definition at line 66 of file ipsec_sa.h.
Referenced by METHOD().
void(* ipsec_sa_t::set_source)(ipsec_sa_t *this, host_t *addr)
Set the source address for this SA
Parameters
addr source address of this SA (gets cloned)
Definition at line 59 of file ipsec_sa.h.
Referenced by METHOD().
host_t * ipsec_sa_t::src
Source address of this SA
Definition at line 383 of file kernel_netlink_ipsec.c.
Referenced by add_policy_internal(), install_route(), ipsec_sa_create(), ipsec_sa_destroy(), ipsec_sa_equals(), ipsec_sa_hash(), and METHOD().
void(* ipsec_sa_t::update_usestats)(ipsec_sa_t *this, u_int32_t bytes)
Record en/decryption of a packet to update usage statistics.
Parameters
bytes length of packet processed
Definition at line 127 of file ipsec_sa.h.
Referenced by process_inbound(), and process_outbound().
The documentation for this struct was generated from the following files:
kernel_netlink_ipsec.c
kernel_pfkey_ipsec.c
ipsec_sa.h