strongSwan: pkcs7_signed_data
pkcs7_signed_data
pkcs7
Functions
pkcs7_t * pkcs7_signed_data_load (chunk_t encoding, chunk_t content)
pkcs7_t * pkcs7_signed_data_gen (container_type_t type, va_list args)
Detailed Description
Function Documentation
pkcs7_t* pkcs7_signed_data_gen (container_type_t type, va_list args)
Generate a PKCS#7 signed-data container.
Parameters
type container type, must be CONTAINER_PKCS7_SIGNED_DATA
args builder_t arguments to use.
See header.
Definition at line 615 of file pkcs7_signed_data.c.
References pkcs7_attributes_t::add_attribute, mem_cred_t::add_cert, alg, blob, BUILD_BLOB, BUILD_DIGEST_ALG, BUILD_END, BUILD_PKCS7_ATTRIBUTE, BUILD_SIGNING_CERT, BUILD_SIGNING_KEY, cert, chunk_clone, chunk_empty, CONTAINER_PKCS7_DATA, credential_factory_t::create, create_empty(), CRED_CONTAINER, creds, library_t::creds, pkcs7_attributes_t::destroy, destroy(), FALSE, generate(), certificate_t::get_ref, HASH_SHA1, key, chunk_t::len, lib, pkcs7_attributes_create(), TRUE, and value.
Referenced by METHOD().
 {
     private_pkcs7_signed_data_t *this;
     chunk_t blob = chunk_empty;
     hash_algorithm_t alg = HASH_SHA1;
     private_key_t *key = NULL;
     certificate_t *cert = NULL;
     pkcs7_attributes_t *pkcs9;
     chunk_t value;
     int oid;
     pkcs9 = pkcs7_attributes_create();
     while (TRUE)
     {
         switch (va_arg(args, builder_part_t))
         {
             case BUILD_SIGNING_KEY:
                 key = va_arg(args, private_key_t*);
                 continue;
             case BUILD_SIGNING_CERT:
                 cert = va_arg(args, certificate_t*);
                 continue;
             case BUILD_DIGEST_ALG:
                 alg = va_arg(args, int);
                 continue;
             case BUILD_BLOB:
                 blob = va_arg(args, chunk_t);
                 continue;
             case BUILD_PKCS7_ATTRIBUTE:
                 oid = va_arg(args, int);
                 value = va_arg(args, chunk_t);
                 pkcs9->add_attribute(pkcs9, oid, chunk_clone(value));
                 continue;
             case BUILD_END:
                 break;
             default:
                 pkcs9->destroy(pkcs9);
                 return NULL;
         }
         break;
     }
     if (blob.len && key && cert)
     {
         this = create_empty();
         this->creds->add_cert(this->creds, FALSE, cert->get_ref(cert));
         this->content = lib->creds->create(lib->creds,
                                            CRED_CONTAINER, CONTAINER_PKCS7_DATA,
                                            BUILD_BLOB, blob, BUILD_END);
         if (this->content && generate(this, key, cert, alg, pkcs9))
         {
             return &this->public;
         }
         pkcs9->destroy(pkcs9);
         destroy(this);
     }
     else
     {
         pkcs9->destroy(pkcs9);
     }
     return NULL;
 }
pkcs7_t* pkcs7_signed_data_load (chunk_t encoding, chunk_t content)
Parse a PKCS#7 signed-data container.
Parameters
encoding full contentInfo encoding
content DER encoded content from contentInfo
Returns
CONTAINER_PKCS7_SIGNED_DATA container, NULL on failure
See header.
Definition at line 484 of file pkcs7_signed_data.c.
References chunk_clone, create_empty(), destroy(), and parse().
Referenced by parse_contentInfo().
 {
     private_pkcs7_signed_data_t *this = create_empty();
     this->encoding = chunk_clone(encoding);
     if (!parse(this, content))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }