strongSwan: parser_helper
parser_helper
utils
Classes
struct parser_helper_t
Macros
#define PARSER_DBG1(...) {}
#define PARSER_DBG2(...) {}
#define PARSER_DBG3(...) {}
Typedefs
typedef struct parser_helper_t parser_helper_t
Functions
void parser_helper_log (int level, parser_helper_t *ctx, char *fmt,...)
parser_helper_t * parser_helper_create (void *context)
Detailed Description
Macro Definition Documentation
#define PARSER_DBG1 (...) {}
Definition at line 144 of file parser_helper.h.
Referenced by conf_parser_error(), METHOD(), settings_parser_error(), while(), and yyparse().
#define PARSER_DBG2 (...) {}
Definition at line 147 of file parser_helper.h.
Referenced by METHOD().
#define PARSER_DBG3 (...) {}
Definition at line 150 of file parser_helper.h.
Typedef Documentation
typedef struct parser_helper_t parser_helper_t
Definition at line 28 of file parser_helper.h.
Function Documentation
parser_helper_t* parser_helper_create (void * context)
Create a parser helper object
Parameters
context user defined parser context
Returns
parser helper
Described in header
Definition at line 236 of file parser_helper.c.
References array_create(), array_insert(), ARRAY_TAIL, bio_writer_create(), context, INIT, and name.
Referenced by conf_parser_parse_file(), settings_parser_parse_file(), and settings_parser_parse_string().
 {
     private_parser_helper_t *this;
     parser_helper_file_t *sentinel;
     INIT(this,
         .public = {
             .context = context,
             .file_include = _file_include,
             .file_next = _file_next,
             .string_init = _string_init,
             .string_add = _string_add,
             .string_get = _string_get,
             .destroy = _destroy,
         },
         .files = array_create(0, 0),
         .writer = bio_writer_create(0),
     );
     INIT(sentinel,
         .name = NULL,
     );
     array_insert(this->files, ARRAY_TAIL, sentinel);
     return &this->public;
 }
void parser_helper_log (int level, parser_helper_t * ctx, char * fmt, ...)
Log the given message either as error or warning
Parameters
level log level
ctx current parser context
fmt error message format
... additional arguments
Described in header
Definition at line 209 of file parser_helper.c.
References current_file(), dbg, DBG_CFG, parser_helper_t::get_lineno, msg, parser_helper_file_t::name, parser_helper_t::scanner, and vsnprintf.
 {
     private_parser_helper_t *this = (private_parser_helper_t*)ctx;
     parser_helper_file_t *file;
     char msg[8192];
     va_list args;
     int line;
     va_start(args, fmt);
     vsnprintf(msg, sizeof(msg), fmt, args);
     va_end(args);
     file = current_file(this);
     line = ctx->get_lineno ? ctx->get_lineno(ctx->scanner) : 0;
     if (file)
     {
         dbg(DBG_CFG, level, "%s:%d: %s", file->name, line, msg);
     }
     else
     {
         dbg(DBG_CFG, level, "%s", msg);
     }
 }