strongSwan: unity_handler
unity_handler
unity
Classes
struct unity_handler_t
Typedefs
typedef struct unity_handler_t unity_handler_t
Functions
unity_handler_t * unity_handler_create ()
Detailed Description
Typedef Documentation
typedef struct unity_handler_t unity_handler_t
Definition at line 27 of file unity_handler.h.
Function Documentation
unity_handler_t* unity_handler_create ()
Create a unity_handler instance.
See header
Definition at line 458 of file unity_handler.c.
References INIT, linked_list_create(), mutex_create(), and MUTEX_TYPE_DEFAULT.
Referenced by unity_plugin_create().
 {
     private_unity_handler_t *this;
     INIT(this,
         .public = {
             .handler = {
                 .handle = _handle,
                 .release = _release,
                 .create_attribute_enumerator = _create_attribute_enumerator,
             },
             .create_include_enumerator = _create_include_enumerator,
             .destroy = _destroy,
         },
         .include = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
     );
     return &this->public;
 }