strongSwan: pts
pts
libimcv
Modules
pts_ita_comp_func_name
pts_comp_evidence
pts_comp_func_name
pts_component
pts_component_manager
pts_tcg_comp_func_name
pts_creds
pts_database
pts_dh_group
pts_error
pts_file_meas
pts_file_meta
pts_file_type
pts_ima_bios_list
pts_ima_event_list
pts_meas_algo
pts_pcr
pts_proto_caps
pts_req_func_comp_evid
pts_rsimple_evid_final
Classes
struct pts_t
Macros
#define SOLIDUS_UTF 0x2F
#define REVERSE_SOLIDUS_UTF 0x5C
#define PCR_BIOS 0
#define PCR_PLATFORM_EXT 1
#define PCR_MOTHERBOARD 1
#define PCR_OPTION_ROMS 2
#define PCR_IPL 4
#define PCR_TBOOT_POLICY 17
#define PCR_TBOOT_MLE 18
#define PCR_TGRUB_MBR_STAGE1 4
#define PCR_TGRUB_STAGE2_PART1 8
#define PCR_TGRUB_STAGE2_PART2 9
#define PCR_TGRUB_CMD_LINE_ARGS 12
#define PCR_TGRUB_CHECKFILE 13
#define PCR_TGRUB_LOADED_FILES 14
#define PCR_DEBUG 16
#define ASSESSMENT_SECRET_LEN 20
#define TPM_QUOTE_INFO_LEN 48
#define TRUSTED_HASH_ALGO PTS_MEAS_ALGO_SHA1
Typedefs
typedef struct pts_t pts_t
Functions
pts_t * pts_create (bool is_imc)
Detailed Description
Macro Definition Documentation
#define ASSESSMENT_SECRET_LEN 20
Length of the generated nonce used for calculation of shared secret
Definition at line 71 of file pts.h.
#define PCR_BIOS 0
PCR indices used for measurements of various functional components
Definition at line 50 of file pts.h.
#define PCR_DEBUG 16
Definition at line 66 of file pts.h.
Referenced by METHOD().
#define PCR_IPL 4
Definition at line 54 of file pts.h.
#define PCR_MOTHERBOARD 1
Definition at line 52 of file pts.h.
#define PCR_OPTION_ROMS 2
Definition at line 53 of file pts.h.
#define PCR_PLATFORM_EXT 1
Definition at line 51 of file pts.h.
#define PCR_TBOOT_MLE 18
Definition at line 57 of file pts.h.
Referenced by METHOD().
#define PCR_TBOOT_POLICY 17
Definition at line 56 of file pts.h.
Referenced by METHOD().
#define PCR_TGRUB_CHECKFILE 13
Definition at line 63 of file pts.h.
#define PCR_TGRUB_CMD_LINE_ARGS 12
Definition at line 62 of file pts.h.
#define PCR_TGRUB_LOADED_FILES 14
Definition at line 64 of file pts.h.
#define PCR_TGRUB_MBR_STAGE1 4
Definition at line 59 of file pts.h.
#define PCR_TGRUB_STAGE2_PART1 8
Definition at line 60 of file pts.h.
#define PCR_TGRUB_STAGE2_PART2 9
Definition at line 61 of file pts.h.
#define REVERSE_SOLIDUS_UTF 0x5C
Definition at line 45 of file pts.h.
Referenced by imc_attestation_process().
#define SOLIDUS_UTF 0x2F
UTF-8 encoding of the character used to delimiter the filename
Definition at line 44 of file pts.h.
Referenced by imc_attestation_process(), and METHOD().
#define TPM_QUOTE_INFO_LEN 48
Length of the TPM_QUOTE_INFO structure, TPM Spec 1.2
Definition at line 76 of file pts.h.
Referenced by METHOD().
#define TRUSTED_HASH_ALGO PTS_MEAS_ALGO_SHA1
Hashing algorithm used by tboot and trustedGRUB
Definition at line 81 of file pts.h.
Typedef Documentation
typedef struct pts_t pts_t
Definition at line 25 of file pts.h.
Function Documentation
pts_t* pts_create (bool is_imc)
Creates an pts_t object
Parameters
is_imc TRUE if running on an IMC
See header
Definition at line 1142 of file pts.c.
References DBG1, DBG_PTS, has_tpm(), INIT, load_aik(), load_aik_blob(), PTS_MEAS_ALGO_SHA256, pts_pcr_create(), PTS_PROTO_CAPS_D, PTS_PROTO_CAPS_T, PTS_PROTO_CAPS_V, and TRUE.
Referenced by imc_attestation_state_create(), and imv_attestation_state_create().
 {
     private_pts_t *this;
     pts_pcr_t *pcrs;
     pcrs = pts_pcr_create();
     if (!pcrs)
     {
         DBG1(DBG_PTS, "shadow PCR set could not be created");
         return NULL;
     }
     INIT(this,
         .public = {
             .get_proto_caps = _get_proto_caps,
             .set_proto_caps = _set_proto_caps,
             .get_meas_algorithm = _get_meas_algorithm,
             .set_meas_algorithm = _set_meas_algorithm,
             .get_dh_hash_algorithm = _get_dh_hash_algorithm,
             .set_dh_hash_algorithm = _set_dh_hash_algorithm,
             .create_dh_nonce = _create_dh_nonce,
             .get_my_public_value = _get_my_public_value,
             .set_peer_public_value = _set_peer_public_value,
             .calculate_secret = _calculate_secret,
             .get_platform_id = _get_platform_id,
             .set_platform_id = _set_platform_id,
             .get_tpm_version_info = _get_tpm_version_info,
             .set_tpm_version_info = _set_tpm_version_info,
             .get_aik = _get_aik,
             .set_aik = _set_aik,
             .get_aik_id = _get_aik_id,
             .is_path_valid = _is_path_valid,
             .get_metadata = _get_metadata,
             .read_pcr = _read_pcr,
             .extend_pcr = _extend_pcr,
             .quote_tpm = _quote_tpm,
             .get_pcrs = _get_pcrs,
             .get_quote_info = _get_quote_info,
             .verify_quote_signature  = _verify_quote_signature,
             .destroy = _destroy,
         },
         .is_imc = is_imc,
         .proto_caps = PTS_PROTO_CAPS_V,
         .algorithm = PTS_MEAS_ALGO_SHA256,
         .dh_hash_algorithm = PTS_MEAS_ALGO_SHA256,
         .pcrs = pcrs,
     );
     if (is_imc)
     {
         if (has_tpm(this))
         {
             this->has_tpm = TRUE;
             this->proto_caps |= PTS_PROTO_CAPS_T | PTS_PROTO_CAPS_D;
             load_aik(this);
             load_aik_blob(this);
         }
     }
     else
     {
         this->proto_caps |= PTS_PROTO_CAPS_T | PTS_PROTO_CAPS_D;
     }
     return &this->public;
 }