strongSwan: prf_plus_t Struct Reference
prf_plus_t Struct Reference
prf_plus
#include "prf_plus.h"
Public Attributes
bool(* get_bytes)(prf_plus_t *this, size_t length, u_int8_t *buffer) __attribute__((warn_unused_result))
bool(* allocate_bytes)(prf_plus_t *this, size_t length, chunk_t *chunk) __attribute__((warn_unused_result))
void(* destroy)(prf_plus_t *this)
Detailed Description
Implementation of the prf+ function used in IKEv1/IKEv2 keymat extension.
Definition at line 32 of file prf_plus.h.
Member Data Documentation
bool(* prf_plus_t::allocate_bytes)(prf_plus_t *this, size_t length, chunk_t *chunk) __attribute__((warn_unused_result))
Allocate pseudo random bytes.
Parameters
length number of bytes to get
chunk chunk which will hold generated bytes
Returns
TRUE if bytes allocated successfully
Definition at line 51 of file prf_plus.h.
Referenced by derive_ike_aead(), derive_ike_traditional(), and METHOD().
void(* prf_plus_t::destroy)(prf_plus_t *this)
Destroys a prf_plus_t object.
Definition at line 57 of file prf_plus.h.
Referenced by METHOD().
bool(* prf_plus_t::get_bytes)(prf_plus_t *this, size_t length, u_int8_t *buffer) __attribute__((warn_unused_result))
Get pseudo random bytes.
Parameters
length number of bytes to get
buffer pointer where the generated bytes will be written
Returns
TRUE if bytes generated successfully
Definition at line 41 of file prf_plus.h.
The documentation for this struct was generated from the following file:
prf_plus.h