strongSwan: format-options Namespace Reference
format-options Namespace Reference
Classes
class ConfigOption
class Parser
class TagReplacer
class GroffTagReplacer
class ConfFormatter
class ManFormatter
Variables
tuple options
string help = "output format: conf, man [default: %default]"
string default = "do not sort sections alphabetically"
tuple parser = Parser(opts.sort)
tuple root = parser.get_option(opts.root)
tuple formatter = ConfFormatter()
Variable Documentation
string format-options.default = "do not sort sections alphabetically"
Definition at line 317 of file format-options.py.
tuple format-options.formatter = ConfFormatter()
Definition at line 339 of file format-options.py.
string format-options.help = "output format: conf, man [default: %default]"
Definition at line 312 of file format-options.py.
format-options.options
Initial value:
 = OptionParser(usage = "Usage: %prog [options] file1 file2\n\n"
                        "If no filenames are provided the input is read from stdin.")
Definition at line 309 of file format-options.py.
Referenced by receive_dhcp(), and starter_cmp_conn().
tuple format-options.parser = Parser(opts.sort)
Definition at line 321 of file format-options.py.
tuple format-options.root = parser.get_option(opts.root)
Definition at line 334 of file format-options.py.
Referenced by main(), METHOD(), and xml_create().