strongSwan: kernel_libipsec_router.c File Reference
kernel_libipsec_router.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include "kernel_libipsec_router.h"
#include <daemon.h>
#include <hydra.h>
#include <ipsec.h>
#include <collections/hashtable.h>
#include <networking/tun_device.h>
#include <threading/rwlock.h>
#include <threading/thread.h>
#include <processing/jobs/callback_job.h>
Classes
struct tun_entry_t
struct private_kernel_libipsec_router_t
Typedefs
typedef struct
private_kernel_libipsec_router_t private_kernel_libipsec_router_t
Functions
static u_int tun_entry_hash (tun_entry_t *entry)
static bool tun_entry_equals (tun_entry_t *a, tun_entry_t *b)
static void send_esp (void *data, esp_packet_t *packet)
static void receiver_esp_cb (void *data, packet_t *packet)
static void deliver_plain (private_kernel_libipsec_router_t *this, ip_packet_t *packet)
static void process_plain (tun_device_t *tun)
static int find_revents (struct pollfd *pfd, int count, int fd)
static job_requeue_t handle_plain (private_kernel_libipsec_router_t *this)
METHOD (kernel_listener_t, tun, bool, private_kernel_libipsec_router_t *this, tun_device_t *tun, bool created)
METHOD (kernel_libipsec_router_t, get_tun_name, char *, private_kernel_libipsec_router_t *this, host_t *vip)
METHOD (kernel_libipsec_router_t, destroy, void, private_kernel_libipsec_router_t *this)
static bool set_nonblock (int socket)
kernel_libipsec_router_t * kernel_libipsec_router_create ()
Variables
kernel_libipsec_router_t * router
Typedef Documentation
typedef struct private_kernel_libipsec_router_t private_kernel_libipsec_router_t
Definition at line 30 of file kernel_libipsec_router.c.
Function Documentation
static void deliver_plain (private_kernel_libipsec_router_t * this, ip_packet_t * packet) static
Inbound callback
Definition at line 117 of file kernel_libipsec_router.c.
References ip_packet_t::destroy, ip_packet_t::get_destination, ip_packet_t::get_encoding, lock, lookup, tun_entry_t::tun, spinlock_t::unlock, and tun_device_t::write_packet.
Referenced by kernel_libipsec_router_create(), and METHOD().
 {
     tun_device_t *tun;
     tun_entry_t *entry, lookup = {
         .addr = packet->get_destination(packet),
     };
     this->lock->read_lock(this->lock);
     entry = this->tuns->get(this->tuns, &lookup);
     tun = entry ? entry->tun : this->tun.tun;
     tun->write_packet(tun, packet->get_encoding(packet));
     this->lock->unlock(this->lock);
     packet->destroy(packet);
 }
static int find_revents (struct pollfd * pfd, int count, int fd) static
Find flagged revents in a pollfd set by fd
Definition at line 159 of file kernel_libipsec_router.c.
References count, and pollfd::revents.
Referenced by handle_plain().
 {
     int i;
     for (i = 0; i < count; i++)
     {
         if (pfd[i].fd == fd)
         {
             return pfd[i].revents;
         }
     }
     return 0;
 }
static job_requeue_t handle_plain (private_kernel_libipsec_router_t * this) static
Job handling outbound plaintext packets
Definition at line 176 of file kernel_libipsec_router.c.
References count, enumerator_t::destroy, enumerator_t::enumerate, pollfd::events, tun_entry_t::fd, pollfd::fd, find_revents(), JOB_REQUEUE_DIRECT, JOB_REQUEUE_FAIR, lock, notify(), poll, POLLIN, process_plain(), read, pollfd::revents, thread_cancelability(), TRUE, tun_entry_t::tun, and spinlock_t::unlock.
Referenced by kernel_libipsec_router_create().
 {
     enumerator_t *enumerator;
     tun_entry_t *entry;
     bool oldstate;
     int count = 0;
     char buf[1];
     struct pollfd *pfd;
     this->lock->read_lock(this->lock);
     pfd = alloca(sizeof(*pfd) * (this->tuns->get_count(this->tuns) + 2));
     pfd[count].fd = this->notify[0];
     pfd[count].events = POLLIN;
     count++;
     pfd[count].fd = this->tun.fd;
     pfd[count].events = POLLIN;
     count++;
     enumerator = this->tuns->create_enumerator(this->tuns);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         pfd[count].fd = entry->fd;
         pfd[count].events = POLLIN;
         count++;
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     oldstate = thread_cancelability(TRUE);
     if (poll(pfd, count, -1) <= 0)
     {
         thread_cancelability(oldstate);
         return JOB_REQUEUE_FAIR;
     }
     thread_cancelability(oldstate);
     if (pfd[0].revents & POLLIN)
     {
         /* list of TUN devices changed, read notification data, rebuild FDs */
         while (read(this->notify[0], &buf, sizeof(buf)) == sizeof(buf))
         {
             /* nop */
         }
         return JOB_REQUEUE_DIRECT;
     }
     if (pfd[1].revents & POLLIN)
     {
         process_plain(this->tun.tun);
     }
     this->lock->read_lock(this->lock);
     enumerator = this->tuns->create_enumerator(this->tuns);
     while (enumerator->enumerate(enumerator, NULL, &entry))
     {
         if (find_revents(pfd, count, entry->fd) & POLLIN)
         {
             process_plain(entry->tun);
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return JOB_REQUEUE_DIRECT;
 }
METHOD (kernel_listener_t , tun , bool , private_kernel_libipsec_router_t * this, tun_device_t * tun, bool created)
Definition at line 243 of file kernel_libipsec_router.c.
References tun_entry_t::addr, addr, free(), tun_device_t::get_address, tun_device_t::get_fd, ignore_result, INIT, lock, lookup, notify(), TRUE, spinlock_t::unlock, and write.
 {
     tun_entry_t *entry, lookup;
     char buf[] = {0x01};
     this->lock->write_lock(this->lock);
     if (created)
     {
         INIT(entry,
             .addr = tun->get_address(tun, NULL),
             .fd = tun->get_fd(tun),
             .tun = tun,
         );
         this->tuns->put(this->tuns, entry, entry);
     }
     else
     {
         lookup.addr = tun->get_address(tun, NULL);
         entry = this->tuns->remove(this->tuns, &lookup);
         free(entry);
     }
     /* notify handler thread to recreate FD set */
     ignore_result(write(this->notify[1], buf, sizeof(buf)));
     this->lock->unlock(this->lock);
     return TRUE;
 }
METHOD (kernel_libipsec_router_t , get_tun_name , char * , private_kernel_libipsec_router_t * this, host_t * vip)
Definition at line 271 of file kernel_libipsec_router.c.
References tun_device_t::get_name, lock, lookup, name, strdup, tun_entry_t::tun, spinlock_t::unlock, and vip.
 {
     tun_entry_t *entry, lookup = {
         .addr = vip,
     };
     tun_device_t *tun;
     char *name;
     if (!vip)
     {
         return strdup(this->tun.tun->get_name(this->tun.tun));
     }
     this->lock->read_lock(this->lock);
     entry = this->tuns->get(this->tuns, &lookup);
     tun = entry ? entry->tun : this->tun.tun;
     name = strdup(tun->get_name(tun));
     this->lock->unlock(this->lock);
     return name;
 }
METHOD (kernel_libipsec_router_t , destroy , void , private_kernel_libipsec_router_t * this)
Definition at line 292 of file kernel_libipsec_router.c.
References charon, close, receiver_t::del_esp_cb, deliver_plain(), spinlock_t::destroy, free(), hydra, ipsec, hydra_t::kernel_interface, lock, notify(), ipsec_t::processor, daemon_t::receiver, receiver_esp_cb(), kernel_interface_t::remove_listener, send_esp(), ipsec_processor_t::unregister_inbound, and ipsec_processor_t::unregister_outbound.
 {
     charon->receiver->del_esp_cb(charon->receiver,
                                 (receiver_esp_cb_t)receiver_esp_cb);
     ipsec->processor->unregister_outbound(ipsec->processor,
                                          (ipsec_outbound_cb_t)send_esp);
     ipsec->processor->unregister_inbound(ipsec->processor,
                                          (ipsec_inbound_cb_t)deliver_plain);
     hydra->kernel_interface->remove_listener(hydra->kernel_interface,
                                              &this->public.listener);
     this->lock->destroy(this->lock);
     this->tuns->destroy(this->tuns);
     close(this->notify[0]);
     close(this->notify[1]);
     router = NULL;
     free(this);
 }
static void process_plain (tun_device_t * tun) static
Read and process outbound plaintext packet for the given TUN device
Definition at line 136 of file kernel_libipsec_router.c.
References DBG1, DBG_KNL, ip_packet_create(), ipsec, ipsec_t::processor, ipsec_processor_t::queue_outbound, and tun_device_t::read_packet.
Referenced by handle_plain().
 {
     chunk_t raw;
     if (tun->read_packet(tun, &raw))
     {
         ip_packet_t *packet;
         packet = ip_packet_create(raw);
         if (packet)
         {
             ipsec->processor->queue_outbound(ipsec->processor, packet);
         }
         else
         {
             DBG1(DBG_KNL, "invalid IP packet read from TUN device");
         }
     }
 }
static void receiver_esp_cb (void * data, packet_t * packet) static
Receiver callback
Definition at line 108 of file kernel_libipsec_router.c.
References esp_packet_create_from_packet(), ipsec, ipsec_t::processor, and ipsec_processor_t::queue_inbound.
Referenced by kernel_libipsec_router_create(), and METHOD().
 {
     ipsec->processor->queue_inbound(ipsec->processor,
                                     esp_packet_create_from_packet(packet));
 }
static void send_esp (void * data, esp_packet_t * packet) static
Outbound callback
Definition at line 100 of file kernel_libipsec_router.c.
References charon, sender_t::send_no_marker, and daemon_t::sender.
Referenced by kernel_libipsec_router_create(), and METHOD().
 {
     charon->sender->send_no_marker(charon->sender, (packet_t*)packet);
 }
static bool set_nonblock (int socket) static
Set O_NONBLOCK on the given socket.
Definition at line 314 of file kernel_libipsec_router.c.
References flags.
Referenced by kernel_libipsec_router_create().
 {
     int flags = fcntl(socket, F_GETFL);
     return flags != -1 && fcntl(socket, F_SETFL, flags | O_NONBLOCK) != -1;
 }
static bool tun_entry_equals (tun_entry_t * a, tun_entry_t * b) static
Comparison function for TUN device map
Definition at line 92 of file kernel_libipsec_router.c.
References tun_entry_t::addr, and host_t::ip_equals.
Referenced by kernel_libipsec_router_create().
 {
     return a->addr->ip_equals(a->addr, b->addr);
 }
static u_int tun_entry_hash (tun_entry_t * entry) static
Hash function for TUN device map
Definition at line 84 of file kernel_libipsec_router.c.
References tun_entry_t::addr, chunk_hash(), and host_t::get_address.
Referenced by kernel_libipsec_router_create().
 {
     return chunk_hash(entry->addr->get_address(entry->addr));
 }