strongSwan: socket_win_socket
socket_win_socket
socket_win
Classes
struct socket_win_socket_t
Typedefs
typedef struct socket_win_socket_t socket_win_socket_t
Functions
socket_win_socket_t * socket_win_socket_create ()
Detailed Description
Typedef Documentation
typedef struct socket_win_socket_t socket_win_socket_t
Definition at line 24 of file socket_win_socket.h.
Function Documentation
socket_win_socket_t* socket_win_socket_create ()
Create a socket_win_socket instance.
Definition at line 435 of file socket_win_socket.c.
References CHARON_NATT_PORT, CHARON_UDP_PORT, DBG1, DBG_NET, destroy(), DWORD, settings_t::get_int, INIT, len, lib, library_t::ns, open_socket(), PACKET_MAX_DEFAULT, library_t::settings, SOCKET_COUNT, WSARecvMsgGUID, and WSASendMsgGUID.
Referenced by METHOD().
 {
     private_socket_win_socket_t *this;
     DWORD len;
     int i;
     INIT(this,
         .public = {
             .socket = {
                 .send = _sender,
                 .receive = _receiver,
                 .get_port = _get_port,
                 .supported_families = _supported_families,
                 .destroy = _destroy,
             },
         },
         .ports = {
             lib->settings->get_int(lib->settings,
                             "%s.port", CHARON_UDP_PORT, lib->ns),
             lib->settings->get_int(lib->settings,
                             "%s.port_nat_t", CHARON_NATT_PORT, lib->ns),
         },
         .max_packet = lib->settings->get_int(lib->settings,
                             "%s.max_packet", PACKET_MAX_DEFAULT, lib->ns),
     );
     for (i = 0; i < SOCKET_COUNT; i++)
     {
         this->socks[i] = open_socket(this, i);
         this->events[i] = WSACreateEvent();
     }
     for (i = 0; i < SOCKET_COUNT; i++)
     {
         if (this->events[i] == WSA_INVALID_EVENT ||
             this->socks[i] == INVALID_SOCKET)
         {
             DBG1(DBG_NET, "creating socket failed: %d", WSAGetLastError());
             destroy(this);
             return NULL;
         }
         if (WSAEventSelect(this->socks[i], this->events[i],
                            FD_READ) == SOCKET_ERROR)
         {
             DBG1(DBG_NET, "WSAEventSelect() failed: %d", WSAGetLastError());
             destroy(this);
             return NULL;
         }
     }
     if (WSAIoctl(this->socks[0], SIO_GET_EXTENSION_FUNCTION_POINTER,
             &WSASendMsgGUID, sizeof(WSASendMsgGUID), &this->WSASendMsg,
             sizeof(this->WSASendMsg), &len, NULL, NULL) != 0 ||
         WSAIoctl(this->socks[0], SIO_GET_EXTENSION_FUNCTION_POINTER,
             &WSARecvMsgGUID, sizeof(WSARecvMsgGUID), &this->WSARecvMsg,
             sizeof(this->WSARecvMsg), &len, NULL, NULL) != 0)
     {
         DBG1(DBG_NET, "send/recvmsg() lookup failed: %d", WSAGetLastError());
         destroy(this);
         return NULL;
     }
     return &this->public;
 }