strongSwan: libimcv
libimcv
Modules
ietf_attr
generic_attr
imc
imv
pa_tnc
plugins
seg
ita_attr
os_info
attest_db
pts
pwg_attr
tcg_attr
swid
Functions
bool libimcv_init (bool is_imv)
void libimcv_deinit (void)
Variables
pa_tnc_attr_manager_t * imcv_pa_tnc_attributes
imv_database_t * imcv_db
imv_session_manager_t * imcv_sessions
pts_component_manager_t * imcv_pts_components
Detailed Description
Function Documentation
void libimcv_deinit (void)
Deinitialize libimcv.
Described in header.
Definition at line 232 of file imcv.c.
References DBG1, DBG_LIB, pts_component_manager_t::destroy, DESTROY_IF, libimcv_ref, library_deinit(), libstrongswan_ref, PEN_IETF, PEN_ITA, PEN_PWG, PEN_TCG, ref_put(), pa_tnc_attr_manager_t::remove_vendor, and pts_component_manager_t::remove_vendor.
Referenced by cleanup(), METHOD(), and START_TEST().
 {
     if (ref_put(&libimcv_ref))
     {
         imcv_pts_components->remove_vendor(imcv_pts_components, PEN_TCG);
         imcv_pts_components->remove_vendor(imcv_pts_components, PEN_ITA);
         imcv_pts_components->destroy(imcv_pts_components);
         imcv_pa_tnc_attributes->remove_vendor(imcv_pa_tnc_attributes, PEN_IETF);
         imcv_pa_tnc_attributes->remove_vendor(imcv_pa_tnc_attributes, PEN_ITA);
         imcv_pa_tnc_attributes->remove_vendor(imcv_pa_tnc_attributes, PEN_PWG);
         imcv_pa_tnc_attributes->remove_vendor(imcv_pa_tnc_attributes, PEN_TCG);
         DESTROY_IF(imcv_pa_tnc_attributes);
         imcv_pa_tnc_attributes = NULL;
         DESTROY_IF(imcv_db);
         DESTROY_IF(imcv_sessions);
         DBG1(DBG_LIB, "libimcv terminated");
     }
     if (ref_put(&libstrongswan_ref))
     {
         library_deinit();
     }
 }
bool libimcv_init (bool is_imv)
Initialize libimcv.
Parameters
is_imv TRUE if called by IMV, FALSE if by IMC
Returns
FALSE if initialization failed
Described in header.
Definition at line 129 of file imcv.c.
References pts_component_manager_t::add_component, settings_t::add_fallback, pa_tnc_attr_manager_t::add_vendor, pts_component_manager_t::add_vendor, dbg, DBG1, DBG_LIB, FALSE, settings_t::get_int, settings_t::get_str, ietf_attr_create_from_data(), ietf_attr_names, imcv_dbg(), IMCV_DEBUG_LEVEL, imcv_debug_level, IMCV_DEFAULT_POLICY_SCRIPT, imcv_stderr_quiet, imv_database_create(), imv_session_manager_create(), ita_attr_create_from_data(), ita_attr_names, lib, libimcv_ref, library_deinit(), library_init(), libstrongswan_ref, plugin_loader_t::load, library_t::ns, pa_tnc_attr_manager_create(), PEN_IETF, PEN_ITA, PEN_PWG, PEN_TCG, library_t::plugins, pts_component_manager_create(), PTS_ITA_COMP_FUNC_NAME_IMA, PTS_ITA_COMP_FUNC_NAME_TBOOT, PTS_ITA_COMP_FUNC_NAME_TGRUB, pts_ita_comp_func_names, pts_ita_comp_ima_create(), pts_ita_comp_tboot_create(), pts_ita_comp_tgrub_create(), pts_ita_qualifier_flag_names, pts_ita_qualifier_type_names, PTS_ITA_QUALIFIER_TYPE_SIZE, pts_tcg_comp_func_names, pts_tcg_qualifier_flag_names, pts_tcg_qualifier_type_names, PTS_TCG_QUALIFIER_TYPE_SIZE, pwg_attr_create_from_data(), pwg_attr_names, ref_get(), library_t::settings, tcg_attr_create_from_data(), tcg_attr_names, TRUE, and uri.
Referenced by imc_agent_create(), imv_agent_create(), main(), and START_TEST().
 {
     /* initialize libstrongswan library only once */
     if (lib)
     {
         /* did main program initialize libstrongswan? */
         if (libstrongswan_ref == 0)
         {
             ref_get(&libstrongswan_ref);
         }
     }
     else
     {
         /* we are the first to initialize libstrongswan */
         if (!library_init(NULL, "libimcv"))
         {
             return FALSE;
         }
         /* set the debug level and stderr output */
         imcv_debug_level =  lib->settings->get_int(lib->settings,
                                     "libimcv.debug_level", IMCV_DEBUG_LEVEL);
         imcv_stderr_quiet = lib->settings->get_int(lib->settings,
                                     "libimcv.stderr_quiet", FALSE);
         /* activate the imcv debugging hook */
         dbg = imcv_dbg;
 #ifdef HAVE_SYSLOG
         openlog("imcv", 0, LOG_DAEMON);
 #endif
         if (!lib->plugins->load(lib->plugins,
                 lib->settings->get_str(lib->settings, "libimcv.load",
                     "random nonce gmp pubkey x509")))
         {
             library_deinit();
             return FALSE;
         }
     }
     ref_get(&libstrongswan_ref);
     lib->settings->add_fallback(lib->settings, "%s.imcv", "libimcv", lib->ns);
     lib->settings->add_fallback(lib->settings, "%s.plugins", "libimcv.plugins",
                                 lib->ns);
     if (libimcv_ref == 0)
     {
         char *uri, *script;
         /* initialize the PA-TNC attribute manager */
         imcv_pa_tnc_attributes = pa_tnc_attr_manager_create();
         imcv_pa_tnc_attributes->add_vendor(imcv_pa_tnc_attributes, PEN_IETF,
                             ietf_attr_create_from_data, ietf_attr_names);
         imcv_pa_tnc_attributes->add_vendor(imcv_pa_tnc_attributes, PEN_ITA,
                             ita_attr_create_from_data, ita_attr_names);
         imcv_pa_tnc_attributes->add_vendor(imcv_pa_tnc_attributes, PEN_PWG,
                             pwg_attr_create_from_data, pwg_attr_names);
         imcv_pa_tnc_attributes->add_vendor(imcv_pa_tnc_attributes, PEN_TCG,
                             tcg_attr_create_from_data, tcg_attr_names);
         imcv_pts_components = pts_component_manager_create();
         imcv_pts_components->add_vendor(imcv_pts_components, PEN_TCG,
                     pts_tcg_comp_func_names, PTS_TCG_QUALIFIER_TYPE_SIZE,
                     pts_tcg_qualifier_flag_names, pts_tcg_qualifier_type_names);
         imcv_pts_components->add_vendor(imcv_pts_components, PEN_ITA,
                     pts_ita_comp_func_names, PTS_ITA_QUALIFIER_TYPE_SIZE,
                     pts_ita_qualifier_flag_names, pts_ita_qualifier_type_names);
         imcv_pts_components->add_component(imcv_pts_components, PEN_ITA,
                                       PTS_ITA_COMP_FUNC_NAME_TGRUB,
                                       pts_ita_comp_tgrub_create);
         imcv_pts_components->add_component(imcv_pts_components, PEN_ITA,
                                       PTS_ITA_COMP_FUNC_NAME_TBOOT,
                                       pts_ita_comp_tboot_create);
         imcv_pts_components->add_component(imcv_pts_components, PEN_ITA,
                                       PTS_ITA_COMP_FUNC_NAME_IMA,
                                       pts_ita_comp_ima_create);
         if (is_imv)
         {
             /* instantiate global IMV session manager */
             imcv_sessions = imv_session_manager_create();
             /* instantiate and attach global IMV database if URI is valid */
             uri = lib->settings->get_str(lib->settings,
                         "%s.imcv.database", NULL, lib->ns);
             script = lib->settings->get_str(lib->settings,
                         "%s.imcv.policy_script", IMCV_DEFAULT_POLICY_SCRIPT,
                         lib->ns);
             if (uri)
             {
                 imcv_db = imv_database_create(uri, script);
             }
         }
         DBG1(DBG_LIB, "libimcv initialized");
     }
     ref_get(&libimcv_ref);
     return TRUE;
 }
Variable Documentation
imv_database_t* imcv_db
Global IMV database object
Global IMV database
Definition at line 58 of file imcv.c.
Referenced by imv_attestation_agent_create(), imv_attestation_process(), imv_os_agent_create(), and METHOD().
pa_tnc_attr_manager_t* imcv_pa_tnc_attributes
PA-TNC attribute manager
Definition at line 48 of file imcv.c.
Referenced by METHOD(), and seg_env_create_from_data().
pts_component_manager_t* imcv_pts_components
PTS Functional Component manager
Definition at line 63 of file imcv.c.
Referenced by METHOD(), and print_cfn().
imv_session_manager_t* imcv_sessions
Global IMV session manager
Global list of IMV sessions
Definition at line 53 of file imcv.c.
Referenced by delete_connection(), and METHOD().