strongSwan: ipsec_sa_mgr.c File Reference
ipsec_sa_mgr.c File Reference
#include "ipsec.h"
#include "ipsec_sa_mgr.h"
#include <utils/debug.h>
#include <library.h>
#include <processing/jobs/callback_job.h>
#include <threading/condvar.h>
#include <threading/mutex.h>
#include <collections/hashtable.h>
#include <collections/linked_list.h>
Classes
struct private_ipsec_sa_mgr_t
struct ipsec_sa_entry_t
struct ipsec_sa_expired_t
Typedefs
typedef struct
private_ipsec_sa_mgr_t private_ipsec_sa_mgr_t
Functions
static bool spi_equals (u_int32_t *spi, u_int32_t *other_spi)
static u_int spi_hash (u_int32_t *spi)
static ipsec_sa_entry_t * create_entry (ipsec_sa_t *sa)
static void destroy_entry (ipsec_sa_entry_t *entry)
static bool wait_remove_entry (private_ipsec_sa_mgr_t *this, ipsec_sa_entry_t *entry)
static bool wait_for_entry (private_ipsec_sa_mgr_t *this, ipsec_sa_entry_t *entry)
static void flush_entries (private_ipsec_sa_mgr_t *this)
static bool match_entry_by_ptr (ipsec_sa_entry_t *item, ipsec_sa_entry_t *entry)
static bool match_entry_by_sa_ptr (ipsec_sa_entry_t *item, ipsec_sa_t *sa)
static bool match_entry_by_spi_inbound (ipsec_sa_entry_t *item, u_int32_t *spi, bool *inbound)
static bool match_entry_by_spi_src_dst (ipsec_sa_entry_t *item, u_int32_t *spi, host_t *src, host_t *dst)
static bool match_entry_by_reqid_inbound (ipsec_sa_entry_t *item, u_int32_t *reqid, bool *inbound)
static bool match_entry_by_spi_dst (ipsec_sa_entry_t *item, u_int32_t *spi, host_t *dst)
static bool remove_entry (private_ipsec_sa_mgr_t *this, ipsec_sa_entry_t *entry)
static job_requeue_t sa_expired (ipsec_sa_expired_t *expired)
static void schedule_expiration (private_ipsec_sa_mgr_t *this, ipsec_sa_entry_t *entry)
static void flush_allocated_spis (private_ipsec_sa_mgr_t *this)
static bool allocate_spi (private_ipsec_sa_mgr_t *this, u_int32_t spi)
METHOD (ipsec_sa_mgr_t, get_spi, status_t, private_ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t *spi)
METHOD (ipsec_sa_mgr_t, add_sa, status_t, private_ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, bool initiator, bool encap, bool esn, bool inbound, bool update)
METHOD (ipsec_sa_mgr_t, update_sa, status_t, private_ipsec_sa_mgr_t *this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t *src, host_t *dst, host_t *new_src, host_t *new_dst, bool encap, bool new_encap, mark_t mark)
METHOD (ipsec_sa_mgr_t, query_sa, status_t, private_ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t *bytes, u_int64_t *packets, time_t *time)
METHOD (ipsec_sa_mgr_t, del_sa, status_t, private_ipsec_sa_mgr_t *this, host_t *src, host_t *dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
METHOD (ipsec_sa_mgr_t, checkout_by_reqid, ipsec_sa_t *, private_ipsec_sa_mgr_t *this, u_int32_t reqid, bool inbound)
METHOD (ipsec_sa_mgr_t, checkout_by_spi, ipsec_sa_t *, private_ipsec_sa_mgr_t *this, u_int32_t spi, host_t *dst)
METHOD (ipsec_sa_mgr_t, checkin, void, private_ipsec_sa_mgr_t *this, ipsec_sa_t *sa)
METHOD (ipsec_sa_mgr_t, flush_sas, status_t, private_ipsec_sa_mgr_t *this)
METHOD (ipsec_sa_mgr_t, destroy, void, private_ipsec_sa_mgr_t *this)
ipsec_sa_mgr_t * ipsec_sa_mgr_create ()
Typedef Documentation
typedef struct private_ipsec_sa_mgr_t private_ipsec_sa_mgr_t
Definition at line 29 of file ipsec_sa_mgr.c.
Function Documentation
static bool allocate_spi (private_ipsec_sa_mgr_t * this, u_int32_t spi) static
Pre-allocate an SPI for an inbound SA
Definition at line 381 of file ipsec_sa_mgr.c.
References FALSE, malloc_thing, match_entry_by_spi_inbound(), SUCCESS, and TRUE.
Referenced by METHOD().
 {
     u_int32_t *spi_alloc;
     if (this->allocated_spis->get(this->allocated_spis, &spi) ||
         this->sas->find_first(this->sas, (void*)match_entry_by_spi_inbound,
                               NULL, &spi, TRUE) == SUCCESS)
     {
         return FALSE;
     }
     spi_alloc = malloc_thing(u_int32_t);
     *spi_alloc = spi;
     this->allocated_spis->put(this->allocated_spis, spi_alloc, spi_alloc);
     return TRUE;
 }
static ipsec_sa_entry_t* create_entry (ipsec_sa_t * sa) static
Create an SA entry
Definition at line 132 of file ipsec_sa_mgr.c.
References condvar, condvar_create(), CONDVAR_TYPE_DEFAULT, and INIT.
Referenced by METHOD().
 {
     ipsec_sa_entry_t *this;
     INIT(this,
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .sa = sa,
     );
     return this;
 }
static void destroy_entry (ipsec_sa_entry_t * entry) static
Destroy an SA entry
Definition at line 146 of file ipsec_sa_mgr.c.
References ipsec_sa_entry_t::condvar, condvar_t::destroy, ipsec_sa_t::destroy, free(), and ipsec_sa_entry_t::sa.
Referenced by flush_entries(), METHOD(), and sa_expired().
 {
     entry->condvar->destroy(entry->condvar);
     entry->sa->destroy(entry->sa);
     free(entry);
 }
static void flush_allocated_spis (private_ipsec_sa_mgr_t * this) static
Remove all allocated SPIs
Definition at line 362 of file ipsec_sa_mgr.c.
References DBG2, DBG_ESP, enumerator_t::destroy, enumerator_t::enumerate, and free().
Referenced by METHOD().
 {
     enumerator_t *enumerator;
     u_int32_t *current;
     DBG2(DBG_ESP, "flushing allocated SPIs");
     enumerator = this->allocated_spis->create_enumerator(this->allocated_spis);
     while (enumerator->enumerate(enumerator, NULL, (void**)&current))
     {
         this->allocated_spis->remove_at(this->allocated_spis, enumerator);
         DBG2(DBG_ESP, "  removed allocated SPI %.8x", ntohl(*current));
         free(current);
     }
     enumerator->destroy(enumerator);
 }
static void flush_entries (private_ipsec_sa_mgr_t * this) static
Flushes all entries Must be called with this->mutex held.
Definition at line 208 of file ipsec_sa_mgr.c.
References DBG2, DBG_ESP, enumerator_t::destroy, destroy_entry(), enumerator_t::enumerate, and wait_remove_entry().
Referenced by METHOD().
 {
     ipsec_sa_entry_t *current;
     enumerator_t *enumerator;
     DBG2(DBG_ESP, "flushing SAD");
     enumerator = this->sas->create_enumerator(this->sas);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (wait_remove_entry(this, current))
         {
             this->sas->remove_at(this->sas, enumerator);
             destroy_entry(current);
         }
     }
     enumerator->destroy(enumerator);
 }
static bool match_entry_by_ptr (ipsec_sa_entry_t * item, ipsec_sa_entry_t * entry) static
Definition at line 230 of file ipsec_sa_mgr.c.
Referenced by sa_expired().
 {
     return item == entry;
 }
static bool match_entry_by_reqid_inbound (ipsec_sa_entry_t * item, u_int32_t * reqid, bool * inbound) static
Definition at line 253 of file ipsec_sa_mgr.c.
References ipsec_sa_t::match_by_reqid, and ipsec_sa_entry_t::sa.
Referenced by METHOD().
 {
     return item->sa->match_by_reqid(item->sa, *reqid, *inbound);
 }
static bool match_entry_by_sa_ptr (ipsec_sa_entry_t * item, ipsec_sa_t * sa) static
Definition at line 235 of file ipsec_sa_mgr.c.
References ipsec_sa_entry_t::sa, and sa.
Referenced by METHOD().
 {
     return item->sa == sa;
 }
static bool match_entry_by_spi_dst (ipsec_sa_entry_t * item, u_int32_t * spi, host_t * dst) static
Definition at line 259 of file ipsec_sa_mgr.c.
References ipsec_sa_t::match_by_spi_dst, and ipsec_sa_entry_t::sa.
Referenced by METHOD().
 {
     return item->sa->match_by_spi_dst(item->sa, *spi, dst);
 }
static bool match_entry_by_spi_inbound (ipsec_sa_entry_t * item, u_int32_t * spi, bool * inbound) static
Definition at line 240 of file ipsec_sa_mgr.c.
References ipsec_sa_t::get_spi, ipsec_sa_t::is_inbound, and ipsec_sa_entry_t::sa.
Referenced by allocate_spi().
 {
     return item->sa->get_spi(item->sa) == *spi &&
            item->sa->is_inbound(item->sa) == *inbound;
 }
static bool match_entry_by_spi_src_dst (ipsec_sa_entry_t * item, u_int32_t * spi, host_t * src, host_t * dst) static
Definition at line 247 of file ipsec_sa_mgr.c.
References ipsec_sa_t::match_by_spi_src_dst, and ipsec_sa_entry_t::sa.
Referenced by METHOD().
 {
     return item->sa->match_by_spi_src_dst(item->sa, *spi, src, dst);
 }
METHOD (ipsec_sa_mgr_t , get_spi , status_t , private_ipsec_sa_mgr_t * this, host_t * src, host_t * dst, u_int8_t protocol, u_int32_t * spi)
Definition at line 397 of file ipsec_sa_mgr.c.
References allocate_spi(), crypto_factory_t::create_rng, library_t::crypto, DBG1, DBG2, DBG_ESP, FAILED, lib, mutex_t::lock, mutex, rng, RNG_WEAK, SUCCESS, and mutex_t::unlock.
 {
     u_int32_t spi_new;
     this->mutex->lock(this->mutex);
     if (!this->rng)
     {
         this->rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK);
         if (!this->rng)
         {
             this->mutex->unlock(this->mutex);
             DBG1(DBG_ESP, "failed to create RNG for SPI generation");
             return FAILED;
         }
     }
     do
     {
         if (!this->rng->get_bytes(this->rng, sizeof(spi_new),
                                  (u_int8_t*)&spi_new))
         {
             this->mutex->unlock(this->mutex);
             DBG1(DBG_ESP, "failed to allocate SPI");
             return FAILED;
         }
         /* make sure the SPI is valid (not in range 0-255) */
         spi_new |= 0x00000100;
         spi_new = htonl(spi_new);
     }
     while (!allocate_spi(this, spi_new));
     this->mutex->unlock(this->mutex);
     *spi = spi_new;
     DBG2(DBG_ESP, "allocated SPI %.8x", ntohl(*spi));
     return SUCCESS;
 }
METHOD (ipsec_sa_mgr_t , add_sa , status_t , private_ipsec_sa_mgr_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t * lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, bool initiator, bool encap, bool esn, bool inbound, bool update)
Definition at line 437 of file ipsec_sa_mgr.c.
References create_entry(), DBG1, DBG2, DBG_ESP, ipsec_sa_t::destroy, encryption_algorithm_names, FAILED, free(), integrity_algorithm_names, ipsec_sa_create(), chunk_t::len, mutex_t::lock, match_entry_by_spi_src_dst(), mutex, schedule_expiration(), SUCCESS, and mutex_t::unlock.
 {
     ipsec_sa_entry_t *entry;
     ipsec_sa_t *sa_new;
     DBG2(DBG_ESP, "adding SAD entry with SPI %.8x and reqid {%u}",
          ntohl(spi), reqid);
     DBG2(DBG_ESP, "  using encryption algorithm %N with key size %d",
          encryption_algorithm_names, enc_alg, enc_key.len * 8);
     DBG2(DBG_ESP, "  using integrity algorithm %N with key size %d",
          integrity_algorithm_names, int_alg, int_key.len * 8);
     sa_new = ipsec_sa_create(spi, src, dst, protocol, reqid, mark, tfc,
                              lifetime, enc_alg, enc_key, int_alg, int_key, mode,
                              ipcomp, cpi, encap, esn, inbound);
     if (!sa_new)
     {
         DBG1(DBG_ESP, "failed to create SAD entry");
         return FAILED;
     }
     this->mutex->lock(this->mutex);
     if (update)
     {   /* remove any pre-allocated SPIs */
         u_int32_t *spi_alloc;
         spi_alloc = this->allocated_spis->remove(this->allocated_spis, &spi);
         free(spi_alloc);
     }
     if (this->sas->find_first(this->sas, (void*)match_entry_by_spi_src_dst,
                               NULL, &spi, src, dst) == SUCCESS)
     {
         this->mutex->unlock(this->mutex);
         DBG1(DBG_ESP, "failed to install SAD entry: already installed");
         sa_new->destroy(sa_new);
         return FAILED;
     }
     entry = create_entry(sa_new);
     schedule_expiration(this, entry);
     this->sas->insert_first(this->sas, entry);
     this->mutex->unlock(this->mutex);
     return SUCCESS;
 }
METHOD (ipsec_sa_mgr_t , update_sa , status_t , private_ipsec_sa_mgr_t * this, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, host_t * src, host_t * dst, host_t * new_src, host_t * new_dst, bool encap, bool new_encap, mark_t mark)
Definition at line 491 of file ipsec_sa_mgr.c.
References ipsec_sa_entry_t::condvar, DBG1, DBG2, DBG_ESP, FAILED, FALSE, mutex_t::lock, ipsec_sa_entry_t::locked, match_entry_by_spi_src_dst(), mutex, NOT_SUPPORTED, ipsec_sa_entry_t::sa, ipsec_sa_t::set_destination, ipsec_sa_t::set_source, condvar_t::signal, SUCCESS, mutex_t::unlock, and wait_for_entry().
 {
     ipsec_sa_entry_t *entry = NULL;
     DBG2(DBG_ESP, "updating SAD entry with SPI %.8x from %#H..%#H to %#H..%#H",
          ntohl(spi), src, dst, new_src, new_dst);
     if (!new_encap)
     {
         DBG1(DBG_ESP, "failed to update SAD entry: can't deactivate UDP "
              "encapsulation");
         return NOT_SUPPORTED;
     }
     this->mutex->lock(this->mutex);
     if (this->sas->find_first(this->sas, (void*)match_entry_by_spi_src_dst,
                              (void**)&entry, &spi, src, dst) == SUCCESS &&
         wait_for_entry(this, entry))
     {
         entry->sa->set_source(entry->sa, new_src);
         entry->sa->set_destination(entry->sa, new_dst);
         /* checkin the entry */
         entry->locked = FALSE;
         entry->condvar->signal(entry->condvar);
     }
     this->mutex->unlock(this->mutex);
     if (!entry)
     {
         DBG1(DBG_ESP, "failed to update SAD entry: not found");
         return FAILED;
     }
     return SUCCESS;
 }
METHOD (ipsec_sa_mgr_t , query_sa , status_t , private_ipsec_sa_mgr_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, mark_t mark, u_int64_t * bytes, u_int64_t * packets, time_t * time)
Definition at line 529 of file ipsec_sa_mgr.c.
References ipsec_sa_entry_t::condvar, FALSE, ipsec_sa_t::get_usestats, mutex_t::lock, ipsec_sa_entry_t::locked, match_entry_by_spi_src_dst(), mutex, NOT_FOUND, ipsec_sa_entry_t::sa, condvar_t::signal, SUCCESS, mutex_t::unlock, and wait_for_entry().
 {
     ipsec_sa_entry_t *entry = NULL;
     this->mutex->lock(this->mutex);
     if (this->sas->find_first(this->sas, (void*)match_entry_by_spi_src_dst,
                              (void**)&entry, &spi, src, dst) == SUCCESS &&
         wait_for_entry(this, entry))
     {
         entry->sa->get_usestats(entry->sa, bytes, packets, time);
         /* checkin the entry */
         entry->locked = FALSE;
         entry->condvar->signal(entry->condvar);
     }
     this->mutex->unlock(this->mutex);
     return entry ? SUCCESS : NOT_FOUND;
 }
METHOD (ipsec_sa_mgr_t , del_sa , status_t , private_ipsec_sa_mgr_t * this, host_t * src, host_t * dst, u_int32_t spi, u_int8_t protocol, u_int16_t cpi, mark_t mark)
Definition at line 551 of file ipsec_sa_mgr.c.
References DBG2, DBG_ESP, enumerator_t::destroy, destroy_entry(), enumerator_t::enumerate, FAILED, found, ipsec_sa_t::is_inbound, mutex_t::lock, match_entry_by_spi_src_dst(), mutex, ipsec_sa_entry_t::sa, SUCCESS, mutex_t::unlock, and wait_remove_entry().
 {
     ipsec_sa_entry_t *current, *found = NULL;
     enumerator_t *enumerator;
     this->mutex->lock(this->mutex);
     enumerator = this->sas->create_enumerator(this->sas);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (match_entry_by_spi_src_dst(current, &spi, src, dst))
         {
             if (wait_remove_entry(this, current))
             {
                 this->sas->remove_at(this->sas, enumerator);
                 found = current;
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->mutex->unlock(this->mutex);
     if (found)
     {
         DBG2(DBG_ESP, "deleted %sbound SAD entry with SPI %.8x",
              found->sa->is_inbound(found->sa) ? "in" : "out", ntohl(spi));
         destroy_entry(found);
         return SUCCESS;
     }
     return FAILED;
 }
METHOD (ipsec_sa_mgr_t , checkout_by_reqid , ipsec_sa_t * , private_ipsec_sa_mgr_t * this, u_int32_t reqid, bool inbound)
Definition at line 585 of file ipsec_sa_mgr.c.
References mutex_t::lock, match_entry_by_reqid_inbound(), mutex, ipsec_sa_entry_t::sa, sa, SUCCESS, mutex_t::unlock, and wait_for_entry().
 {
     ipsec_sa_entry_t *entry;
     ipsec_sa_t *sa = NULL;
     this->mutex->lock(this->mutex);
     if (this->sas->find_first(this->sas, (void*)match_entry_by_reqid_inbound,
                              (void**)&entry, &reqid, &inbound) == SUCCESS &&
         wait_for_entry(this, entry))
     {
         sa = entry->sa;
     }
     this->mutex->unlock(this->mutex);
     return sa;
 }
METHOD (ipsec_sa_mgr_t , checkout_by_spi , ipsec_sa_t * , private_ipsec_sa_mgr_t * this, u_int32_t spi, host_t * dst)
Definition at line 602 of file ipsec_sa_mgr.c.
References mutex_t::lock, match_entry_by_spi_dst(), mutex, ipsec_sa_entry_t::sa, sa, SUCCESS, mutex_t::unlock, and wait_for_entry().
 {
     ipsec_sa_entry_t *entry;
     ipsec_sa_t *sa = NULL;
     this->mutex->lock(this->mutex);
     if (this->sas->find_first(this->sas, (void*)match_entry_by_spi_dst,
                              (void**)&entry, &spi, dst) == SUCCESS &&
         wait_for_entry(this, entry))
     {
         sa = entry->sa;
     }
     this->mutex->unlock(this->mutex);
     return sa;
 }
METHOD (ipsec_sa_mgr_t , checkin , void , private_ipsec_sa_mgr_t * this, ipsec_sa_t * sa)
Definition at line 619 of file ipsec_sa_mgr.c.
References ipsec_sa_entry_t::condvar, FALSE, mutex_t::lock, ipsec_sa_entry_t::locked, match_entry_by_sa_ptr(), mutex, condvar_t::signal, SUCCESS, and mutex_t::unlock.
 {
     ipsec_sa_entry_t *entry;
     this->mutex->lock(this->mutex);
     if (this->sas->find_first(this->sas, (void*)match_entry_by_sa_ptr,
                              (void**)&entry, sa) == SUCCESS)
     {
         if (entry->locked)
         {
             entry->locked = FALSE;
             entry->condvar->signal(entry->condvar);
         }
     }
     this->mutex->unlock(this->mutex);
 }
METHOD (ipsec_sa_mgr_t , flush_sas , status_t , private_ipsec_sa_mgr_t * this)
Definition at line 637 of file ipsec_sa_mgr.c.
References flush_entries(), mutex_t::lock, mutex, SUCCESS, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     flush_entries(this);
     this->mutex->unlock(this->mutex);
     return SUCCESS;
 }
METHOD (ipsec_sa_mgr_t , destroy , void , private_ipsec_sa_mgr_t * this)
Definition at line 646 of file ipsec_sa_mgr.c.
References mutex_t::destroy, DESTROY_IF, flush_allocated_spis(), flush_entries(), free(), mutex_t::lock, mutex, rng, and mutex_t::unlock.
 {
     this->mutex->lock(this->mutex);
     flush_entries(this);
     flush_allocated_spis(this);
     this->mutex->unlock(this->mutex);
     this->allocated_spis->destroy(this->allocated_spis);
     this->sas->destroy(this->sas);
     this->mutex->destroy(this->mutex);
     DESTROY_IF(this->rng);
     free(this);
 }
static bool remove_entry (private_ipsec_sa_mgr_t * this, ipsec_sa_entry_t * entry) static
Remove an entry
Definition at line 268 of file ipsec_sa_mgr.c.
References enumerator_t::destroy, enumerator_t::enumerate, FALSE, TRUE, and wait_remove_entry().
Referenced by sa_expired().
 {
     ipsec_sa_entry_t *current;
     enumerator_t *enumerator;
     bool removed = FALSE;
     enumerator = this->sas->create_enumerator(this->sas);
     while (enumerator->enumerate(enumerator, (void**)&current))
     {
         if (current == entry)
         {
             if (wait_remove_entry(this, current))
             {
                 this->sas->remove_at(this->sas, enumerator);
                 removed = TRUE;
             }
             break;
         }
     }
     enumerator->destroy(enumerator);
     return removed;
 }
static job_requeue_t sa_expired (ipsec_sa_expired_t * expired) static
Callback for expiration events
Definition at line 294 of file ipsec_sa_mgr.c.
References destroy_entry(), ipsec_sa_expired_t::entry, ipsec_sa_t::expire, ipsec_sa_expired_t::hard_offset, JOB_REQUEUE_NONE, JOB_RESCHEDULE, mutex_t::lock, ipsec_sa_expired_t::manager, match_entry_by_ptr(), mutex, remove_entry(), ipsec_sa_entry_t::sa, SUCCESS, and mutex_t::unlock.
Referenced by schedule_expiration().
 {
     private_ipsec_sa_mgr_t *this = expired->manager;
     this->mutex->lock(this->mutex);
     if (this->sas->find_first(this->sas, (void*)match_entry_by_ptr,
                               NULL, expired->entry) == SUCCESS)
     {
         u_int32_t hard_offset;
         hard_offset = expired->hard_offset;
         expired->entry->sa->expire(expired->entry->sa, hard_offset == 0);
         if (hard_offset)
         {   /* soft limit reached, schedule hard expire */
             expired->hard_offset = 0;
             this->mutex->unlock(this->mutex);
             return JOB_RESCHEDULE(hard_offset);
         }
         /* hard limit reached */
         if (remove_entry(this, expired->entry))
         {
             destroy_entry(expired->entry);
         }
     }
     this->mutex->unlock(this->mutex);
     return JOB_REQUEUE_NONE;
 }
static void schedule_expiration (private_ipsec_sa_mgr_t * this, ipsec_sa_entry_t * entry) static
Schedule a job to handle IPsec SA expiration
Definition at line 325 of file ipsec_sa_mgr.c.
References callback_job_create(), free(), ipsec_sa_t::get_lifetime, ipsec_sa_expired_t::hard_offset, INIT, lib, lifetime_cfg_t::life, lifetime_cfg_t::rekey, ipsec_sa_entry_t::sa, sa_expired(), scheduler_t::schedule_job, library_t::scheduler, and lifetime_cfg_t::time.
Referenced by METHOD().
 {
     lifetime_cfg_t *lifetime = entry->sa->get_lifetime(entry->sa);
     ipsec_sa_expired_t *expired;
     callback_job_t *job;
     u_int32_t timeout;
     if (!lifetime->time.life)
     {   /* no expiration at all */
         return;
     }
     INIT(expired,
         .manager = this,
         .entry = entry,
     );
     /* schedule a rekey first, a hard timeout will be scheduled then, if any */
     expired->hard_offset = lifetime->time.life - lifetime->time.rekey;
     timeout = lifetime->time.rekey;
     if (lifetime->time.life <= lifetime->time.rekey ||
         lifetime->time.rekey == 0)
     {   /* no rekey, schedule hard timeout */
         expired->hard_offset = 0;
         timeout = lifetime->time.life;
     }
     job = callback_job_create((callback_job_cb_t)sa_expired, expired,
                               (callback_job_cleanup_t)free, NULL);
     lib->scheduler->schedule_job(lib->scheduler, (job_t*)job, timeout);
 }
static bool spi_equals (u_int32_t * spi, u_int32_t * other_spi) static
Definition at line 119 of file ipsec_sa_mgr.c.
Referenced by ipsec_sa_mgr_create().
 {
     return *spi == *other_spi;
 }
static u_int spi_hash (u_int32_t * spi) static
Definition at line 124 of file ipsec_sa_mgr.c.
References chunk_from_thing, and chunk_hash().
Referenced by ipsec_sa_mgr_create().
 {
     return chunk_hash(chunk_from_thing(*spi));
 }
static bool wait_for_entry (private_ipsec_sa_mgr_t * this, ipsec_sa_entry_t * entry) static
Waits until an is available and then locks it. Must only be called with this->mutex held
Definition at line 185 of file ipsec_sa_mgr.c.
References ipsec_sa_entry_t::awaits_deletion, ipsec_sa_entry_t::condvar, FALSE, ipsec_sa_entry_t::locked, condvar_t::signal, TRUE, condvar_t::wait, and ipsec_sa_entry_t::waiting_threads.
Referenced by METHOD().
 {
     while (entry->locked && !entry->awaits_deletion)
     {
         entry->waiting_threads++;
         entry->condvar->wait(entry->condvar, this->mutex);
         entry->waiting_threads--;
     }
     if (entry->awaits_deletion)
     {
         /* others may still be waiting, */
         entry->condvar->signal(entry->condvar);
         return FALSE;
     }
     entry->locked = TRUE;
     return TRUE;
 }
static bool wait_remove_entry (private_ipsec_sa_mgr_t * this, ipsec_sa_entry_t * entry) static
Makes sure an entry is safe to remove Must be called with this->mutex held.
Returns
TRUE if entry can be removed, FALSE if entry is already being removed by another thread
Definition at line 160 of file ipsec_sa_mgr.c.
References ipsec_sa_entry_t::awaits_deletion, condvar_t::broadcast, ipsec_sa_entry_t::condvar, FALSE, ipsec_sa_entry_t::locked, TRUE, condvar_t::wait, and ipsec_sa_entry_t::waiting_threads.
Referenced by flush_entries(), METHOD(), and remove_entry().
 {
     if (entry->awaits_deletion)
     {
         /* this will be deleted by another thread already */
         return FALSE;
     }
     entry->awaits_deletion = TRUE;
     while (entry->locked)
     {
         entry->condvar->wait(entry->condvar, this->mutex);
     }
     while (entry->waiting_threads > 0)
     {
         entry->condvar->broadcast(entry->condvar);
         entry->condvar->wait(entry->condvar, this->mutex);
     }
     return TRUE;
 }