strongSwan: pb_remediation_parameters_msg.c File Reference
pb_remediation_parameters_msg.c File Reference
#include "pb_remediation_parameters_msg.h"
#include <bio/bio_writer.h>
#include <bio/bio_reader.h>
#include <utils/debug.h>
Classes
struct private_pb_remediation_parameters_msg_t
Typedefs
typedef struct
private_pb_remediation_parameters_msg_t private_pb_remediation_parameters_msg_t
Functions
ENUM (pb_tnc_remed_param_type_names, PB_REMEDIATION_URI, PB_REMEDIATION_STRING,"Remediation-URI","Remediation-String")
METHOD (pb_tnc_msg_t, get_type, pen_type_t, private_pb_remediation_parameters_msg_t *this)
METHOD (pb_tnc_msg_t, get_encoding, chunk_t, private_pb_remediation_parameters_msg_t *this)
METHOD (pb_tnc_msg_t, build, void, private_pb_remediation_parameters_msg_t *this)
METHOD (pb_tnc_msg_t, process, status_t, private_pb_remediation_parameters_msg_t *this, u_int32_t *offset)
METHOD (pb_tnc_msg_t, destroy, void, private_pb_remediation_parameters_msg_t *this)
METHOD (pb_remediation_parameters_msg_t, get_parameters_type, pen_type_t, private_pb_remediation_parameters_msg_t *this)
METHOD (pb_remediation_parameters_msg_t, get_parameters, chunk_t, private_pb_remediation_parameters_msg_t *this)
METHOD (pb_remediation_parameters_msg_t, get_string, chunk_t, private_pb_remediation_parameters_msg_t *this, chunk_t *lang_code)
pb_tnc_msg_t * pb_remediation_parameters_msg_create (pen_type_t parameters_type, chunk_t parameters)
pb_tnc_msg_t * pb_remediation_parameters_msg_create_from_uri (chunk_t uri)
pb_tnc_msg_t * pb_remediation_parameters_msg_create_from_string (chunk_t string, chunk_t lang_code)
pb_tnc_msg_t * pb_remediation_parameters_msg_create_from_data (chunk_t data)
Typedef Documentation
typedef struct private_pb_remediation_parameters_msg_t private_pb_remediation_parameters_msg_t
Definition at line 27 of file pb_remediation_parameters_msg.c.
Function Documentation
ENUM (pb_tnc_remed_param_type_names , PB_REMEDIATION_URI , PB_REMEDIATION_STRING , "Remediation-URI" , "Remediation-String")
METHOD (pb_tnc_msg_t , get_type , pen_type_t , private_pb_remediation_parameters_msg_t * this)
Definition at line 94 of file pb_remediation_parameters_msg.c.
References type.
 {
     return this->type;
 }
METHOD (pb_tnc_msg_t , get_encoding , chunk_t , private_pb_remediation_parameters_msg_t * this)
Definition at line 100 of file pb_remediation_parameters_msg.c.
References encoding.
 {
     return this->encoding;
 }
METHOD (pb_tnc_msg_t , build , void , private_pb_remediation_parameters_msg_t * this)
Definition at line 106 of file pb_remediation_parameters_msg.c.
References bio_writer_create(), chunk_clone, bio_writer_t::destroy, encoding, bio_writer_t::get_buf, bio_writer_t::write_data, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     if (this->encoding.ptr)
     {
         return;
     }
     writer = bio_writer_create(64);
     writer->write_uint32(writer, this->parameters_type.vendor_id);
     writer->write_uint32(writer, this->parameters_type.type);
     writer->write_data  (writer, this->parameters);
     this->encoding = writer->get_buf(writer);
     this->encoding = chunk_clone(this->encoding);
     writer->destroy(writer);
 }
METHOD (pb_tnc_msg_t , process , status_t , private_pb_remediation_parameters_msg_t * this, u_int32_t * offset)
Definition at line 125 of file pb_remediation_parameters_msg.c.
References bio_reader_create(), chunk_clone, DBG1, DBG_TNC, bio_reader_t::destroy, encoding, end, FAILED, len, PB_REMEDIATION_STRING, PEN_IETF, bio_reader_t::read_data, bio_reader_t::read_data32, bio_reader_t::read_data8, bio_reader_t::read_uint24, bio_reader_t::read_uint32, bio_reader_t::read_uint8, bio_reader_t::remaining, reserved, status, and SUCCESS.
 {
     bio_reader_t *reader;
     u_int8_t reserved;
     status_t status = SUCCESS;
     u_char *pos;
     *offset = 0;
     /* process message */
     reader = bio_reader_create(this->encoding);
     reader->read_uint8 (reader, &reserved);
     reader->read_uint24(reader, &this->parameters_type.vendor_id);
     reader->read_uint32(reader, &this->parameters_type.type);
     reader->read_data  (reader, reader->remaining(reader), &this->parameters);
     this->parameters = chunk_clone(this->parameters);
     reader->destroy(reader);
     if (this->parameters_type.vendor_id == PEN_IETF &&
         this->parameters_type.type == PB_REMEDIATION_STRING)
     {
         reader = bio_reader_create(this->parameters);
         status = FAILED;
         *offset = 8;
         if (!reader->read_data32(reader, &this->string))
         {
             DBG1(DBG_TNC, "insufficient data for remediation string");
             goto end;
         };
         *offset += 4;
         pos = memchr(this->string.ptr, '\0', this->string.len);
         if (pos)
         {
             DBG1(DBG_TNC, "nul termination in remediation string");
             *offset += (pos - this->string.ptr);
             goto end;
         }
         *offset += this->string.len;
         if (!reader->read_data8(reader, &this->lang_code))
         {
             DBG1(DBG_TNC, "insufficient data for remediation string lang code");
             goto end;
         };
         *offset += 1;
         pos = memchr(this->lang_code.ptr, '\0', this->lang_code.len);
         if (pos)
         {
             DBG1(DBG_TNC, "nul termination in remediation string lang code");
             *offset += (pos - this->lang_code.ptr);
             goto end;
         }
         status = SUCCESS;
 end:
         reader->destroy(reader);
     }
     return status;
 }
METHOD (pb_tnc_msg_t , destroy , void , private_pb_remediation_parameters_msg_t * this)
Definition at line 191 of file pb_remediation_parameters_msg.c.
References encoding, and free().
 {
     free(this->encoding.ptr);
     free(this->parameters.ptr);
     free(this);
 }
METHOD (pb_remediation_parameters_msg_t , get_parameters_type , pen_type_t , private_pb_remediation_parameters_msg_t * this)
Definition at line 199 of file pb_remediation_parameters_msg.c.
 {
     return this->parameters_type;
 }
METHOD (pb_remediation_parameters_msg_t , get_parameters , chunk_t , private_pb_remediation_parameters_msg_t * this)
Definition at line 205 of file pb_remediation_parameters_msg.c.
 {
     return this->parameters;
 }
METHOD (pb_remediation_parameters_msg_t , get_string , chunk_t , private_pb_remediation_parameters_msg_t * this, chunk_t * lang_code)
Definition at line 211 of file pb_remediation_parameters_msg.c.
References string.
 {
     if (lang_code)
     {
         *lang_code = this->lang_code;
     }
     return this->string;
 }