strongSwan: watcher
watcher
processor
Classes
struct watcher_t
Typedefs
typedef struct watcher_t watcher_t
typedef enum watcher_event_t watcher_event_t
typedef enum watcher_state_t watcher_state_t
typedef bool(* watcher_cb_t)(void *data, int fd, watcher_event_t event)
Enumerations
enum watcher_event_t { WATCHER_READ = (1<<0), WATCHER_WRITE = (1<<1), WATCHER_EXCEPT = (1<<2) }
enum watcher_state_t { WATCHER_STOPPED = 0, WATCHER_QUEUED, WATCHER_RUNNING }
Functions
watcher_t * watcher_create ()
Detailed Description
Typedef Documentation
typedef bool(* watcher_cb_t)(void *data, int fd, watcher_event_t event)
Callback function to register for file descriptor events.
The callback is executed asynchronously using a thread from the pool. Monitoring of fd is temporarily suspended to avoid additional events while it is processed asynchronously. To allow concurrent events, one can quickly process it (using a read/write) and return from the callback. This will re-enable the event, while the data read can be processed in another asynchronous job.
On Linux, even if select() marks an FD as "ready", a subsequent read/write can block. It is therefore highly recommended to use non-blocking I/O and handle EAGAIN/EWOULDBLOCK gracefully.
Parameters
data user data passed during registration
fd file descriptor the event occurred on
event type of event
Returns
TRUE to keep watching event, FALSE to unregister fd for event
Definition at line 49 of file watcher.h.
typedef enum watcher_event_t watcher_event_t
Definition at line 25 of file watcher.h.
typedef enum watcher_state_t watcher_state_t
Definition at line 26 of file watcher.h.
typedef struct watcher_t watcher_t
Definition at line 24 of file watcher.h.
Enumeration Type Documentation
enum watcher_event_t
What events to watch for a file descriptor.
Enumerator
WATCHER_READ
WATCHER_WRITE
WATCHER_EXCEPT
Definition at line 54 of file watcher.h.
                      {
     WATCHER_READ = (1<<0),
     WATCHER_WRITE = (1<<1),
     WATCHER_EXCEPT = (1<<2),
 };
enum watcher_state_t
State the watcher currently is in
Enumerator
WATCHER_STOPPED
no watcher thread running or queued
WATCHER_QUEUED
a job has been queued for watching, but not yet started
WATCHER_RUNNING
a watcher thread is active, dispatching socket events
Definition at line 63 of file watcher.h.
                      {
     WATCHER_STOPPED = 0,
     WATCHER_QUEUED,
     WATCHER_RUNNING,
 };
Function Documentation
watcher_t* watcher_create ()
Create a watcher instance.
Returns
watcher
See header
Definition at line 575 of file watcher.c.
References condvar_create(), CONDVAR_TYPE_DEFAULT, create_notify(), DBG1, DBG_LIB, INIT, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, strerror, and WATCHER_STOPPED.
Referenced by library_init().
 {
     private_watcher_t *this;
     INIT(this,
         .public = {
             .add = _add,
             .remove = _remove_,
             .get_state = _get_state,
             .destroy = _destroy,
         },
         .fds = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .condvar = condvar_create(CONDVAR_TYPE_DEFAULT),
         .jobs = linked_list_create(),
         .notify = {-1, -1},
         .state = WATCHER_STOPPED,
     );
     if (!create_notify(this))
     {
         DBG1(DBG_LIB, "creating watcher notify pipe failed: %s",
              strerror(errno));
     }
     return &this->public;
 }