strongSwan: af_alg_crypter
af_alg_crypter
af_alg
Classes
struct af_alg_crypter_t
Macros
#define AF_ALG_CRYPTER 25
Typedefs
typedef struct af_alg_crypter_t af_alg_crypter_t
Functions
af_alg_crypter_t * af_alg_crypter_create (encryption_algorithm_t algo, size_t key_size)
void af_alg_crypter_probe (plugin_feature_t *features, int *pos)
Detailed Description
Macro Definition Documentation
#define AF_ALG_CRYPTER 25
Number of crypters
Definition at line 30 of file af_alg_crypter.h.
Referenced by METHOD().
Typedef Documentation
typedef struct af_alg_crypter_t af_alg_crypter_t
Definition at line 24 of file af_alg_crypter.h.
Function Documentation
af_alg_crypter_t* af_alg_crypter_create (encryption_algorithm_t algo, size_t key_size)
Constructor to create af_alg_crypter_t.
Parameters
algo algorithm to implement
key_size key size in bytes
Returns
af_alg_crypter_t, NULL if not supported
Definition at line 190 of file af_alg_crypter.c.
References af_alg_ops_create(), block_size, free(), INIT, iv_size, keymat_size, lookup_alg(), and name.
Referenced by METHOD().
 {
     private_af_alg_crypter_t *this;
     size_t block_size, keymat_size, iv_size;
     char *name;
     block_size = lookup_alg(algo, &name, key_size, &keymat_size, &iv_size);
     if (!block_size)
     {   /* not supported by kernel */
         return NULL;
     }
     INIT(this,
         .public = {
             .crypter = {
                 .encrypt = _encrypt,
                 .decrypt = _decrypt,
                 .get_block_size = _get_block_size,
                 .get_iv_size = _get_iv_size,
                 .get_key_size = _get_key_size,
                 .set_key = _set_key,
                 .destroy = _destroy,
             },
         },
         .block_size = block_size,
         .keymat_size = keymat_size,
         .iv_size = iv_size,
         .ops = af_alg_ops_create("skcipher", name),
     );
     if (!this->ops)
     {
         free(this);
         return NULL;
     }
     return &this->public;
 }
void af_alg_crypter_probe (plugin_feature_t * features, int * pos)
Probe algorithms and return plugin features.
Parameters
features plugin features to create
pos current position in features
See header.
Definition at line 95 of file af_alg_crypter.c.
References af_alg_ops_create(), algs, countof, af_alg_ops_t::destroy, key_size, name, and PLUGIN_PROVIDE.
Referenced by METHOD().
 {
     af_alg_ops_t *ops;
     int i;
     for (i = 0; i < countof(algs); i++)
     {
         ops = af_alg_ops_create("skcipher", algs[i].name);
         if (ops)
         {
             ops->destroy(ops);
             features[(*pos)++] = PLUGIN_PROVIDE(CRYPTER,
                                                 algs[i].id, algs[i].key_size);
         }
     }
 }