strongSwan: agent_private_key.c File Reference
agent_private_key.c File Reference
#include "agent_private_key.h"
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <arpa/inet.h>
#include <errno.h>
#include <library.h>
#include <utils/chunk.h>
#include <utils/debug.h>
Classes
struct private_agent_private_key_t
Macros
#define UNIX_PATH_MAX 108
Typedefs
typedef struct
private_agent_private_key_t private_agent_private_key_t
typedef enum agent_msg_type_t agent_msg_type_t
Enumerations
enum agent_msg_type_t {
SSH_AGENT_FAILURE = 5, SSH_AGENT_SUCCESS = 6, SSH_AGENT_ID_REQUEST = 11, SSH_AGENT_ID_RESPONSE = 12,
SSH_AGENT_SIGN_REQUEST = 13, SSH_AGENT_SIGN_RESPONSE = 14
}
Functions
static u_char read_byte (chunk_t *blob)
static u_int32_t read_uint32 (chunk_t *blob)
static chunk_t read_string (chunk_t *blob)
static int open_connection (char *path)
static bool read_key (private_agent_private_key_t *this, public_key_t *pubkey)
static bool scheme_supported (private_agent_private_key_t *this, signature_scheme_t scheme)
METHOD (private_key_t, sign, bool, private_agent_private_key_t *this, signature_scheme_t scheme, chunk_t data, chunk_t *signature)
METHOD (private_key_t, get_type, key_type_t, private_agent_private_key_t *this)
METHOD (private_key_t, decrypt, bool, private_agent_private_key_t *this, encryption_scheme_t scheme, chunk_t crypto, chunk_t *plain)
METHOD (private_key_t, get_keysize, int, private_agent_private_key_t *this)
METHOD (private_key_t, get_public_key, public_key_t *, private_agent_private_key_t *this)
METHOD (private_key_t, get_encoding, bool, private_agent_private_key_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (private_key_t, get_fingerprint, bool, private_agent_private_key_t *this, cred_encoding_type_t type, chunk_t *fp)
METHOD (private_key_t, get_ref, private_key_t *, private_agent_private_key_t *this)
METHOD (private_key_t, destroy, void, private_agent_private_key_t *this)
agent_private_key_t * agent_private_key_open (key_type_t type, va_list args)
Macro Definition Documentation
#define UNIX_PATH_MAX 108
Definition at line 31 of file agent_private_key.c.
Referenced by open_connection().
Typedef Documentation
typedef enum agent_msg_type_t agent_msg_type_t
Definition at line 35 of file agent_private_key.c.
typedef struct private_agent_private_key_t private_agent_private_key_t
Definition at line 34 of file agent_private_key.c.
Enumeration Type Documentation
enum agent_msg_type_t
Message types for ssh-agent protocol
Enumerator
SSH_AGENT_FAILURE
SSH_AGENT_SUCCESS
SSH_AGENT_ID_REQUEST
SSH_AGENT_ID_RESPONSE
SSH_AGENT_SIGN_REQUEST
SSH_AGENT_SIGN_RESPONSE
Definition at line 75 of file agent_private_key.c.
                       {
     SSH_AGENT_FAILURE = 5,
     SSH_AGENT_SUCCESS = 6,
     SSH_AGENT_ID_REQUEST = 11,
     SSH_AGENT_ID_RESPONSE = 12,
     SSH_AGENT_SIGN_REQUEST = 13,
     SSH_AGENT_SIGN_RESPONSE = 14,
 };
Function Documentation
METHOD (private_key_t , sign , bool , private_agent_private_key_t * this, signature_scheme_t scheme, chunk_t data, chunk_t * signature)
Definition at line 235 of file agent_private_key.c.
References blob, chunk_cat, chunk_clone, chunk_create(), chunk_equals(), chunk_from_str, DBG1, DBG_LIB, FALSE, flags, key, chunk_t::len, len, chunk_t::ptr, r, read, read_byte(), read_string(), read_uint32(), s, scheme_supported(), signature_scheme_names, socket, SSH_AGENT_SIGN_REQUEST, SSH_AGENT_SIGN_RESPONSE, TRUE, and write.
 {
     u_int32_t len, flags;
     char buf[2048];
     chunk_t blob;
     if (!scheme_supported(this, scheme))
     {
         DBG1(DBG_LIB, "signature scheme %N not supported by ssh-agent",
              signature_scheme_names, scheme);
         return FALSE;
     }
     len = htonl(1 + sizeof(u_int32_t) * 3 + this->key.len + data.len);
     buf[0] = SSH_AGENT_SIGN_REQUEST;
     if (write(this->socket, &len, sizeof(len)) != sizeof(len) ||
         write(this->socket, &buf, 1) != 1)
     {
         DBG1(DBG_LIB, "writing to ssh-agent failed");
         return FALSE;
     }
     len = htonl(this->key.len);
     if (write(this->socket, &len, sizeof(len)) != sizeof(len) ||
         write(this->socket, this->key.ptr, this->key.len) != this->key.len)
     {
         DBG1(DBG_LIB, "writing to ssh-agent failed");
         return FALSE;
     }
     len = htonl(data.len);
     if (write(this->socket, &len, sizeof(len)) != sizeof(len) ||
         write(this->socket, data.ptr, data.len) != data.len)
     {
         DBG1(DBG_LIB, "writing to ssh-agent failed");
         return FALSE;
     }
     flags = htonl(0);
     if (write(this->socket, &flags, sizeof(flags)) != sizeof(flags))
     {
         DBG1(DBG_LIB, "writing to ssh-agent failed");
         return FALSE;
     }
     blob = chunk_create(buf, sizeof(buf));
     blob.len = read(this->socket, blob.ptr, blob.len);
     if (blob.len < sizeof(u_int32_t) + sizeof(u_char) ||
         read_uint32(&blob) != blob.len ||
         read_byte(&blob) != SSH_AGENT_SIGN_RESPONSE)
     {
         DBG1(DBG_LIB, "received invalid ssh-agent signature response");
         return FALSE;
     }
     /* parse length */
     blob = read_string(&blob);
     /* check sig type */
     if (chunk_equals(read_string(&blob), chunk_from_str("ssh-rsa")))
     {   /* for RSA the signature has no special encoding */
         blob = read_string(&blob);
         if (blob.len)
         {
             *signature = chunk_clone(blob);
             return TRUE;
         }
     }
     else
     {   /* anything else is treated as ECSDA for now */
         blob = read_string(&blob);
         if (blob.len)
         {
             chunk_t r, s;
             r = read_string(&blob);
             s = read_string(&blob);
             if (r.len && s.len)
             {
                 *signature = chunk_cat("cc", r, s);
                 return TRUE;
             }
         }
     }
     DBG1(DBG_LIB, "received invalid ssh-agent signature response");
     return FALSE;
 }
METHOD (private_key_t , get_type , key_type_t , private_agent_private_key_t * this)
Definition at line 323 of file agent_private_key.c.
 {
     return this->pubkey->get_type(this->pubkey);
 }
METHOD (private_key_t , decrypt , bool , private_agent_private_key_t * this, encryption_scheme_t scheme, chunk_t crypto, chunk_t * plain)
Definition at line 329 of file agent_private_key.c.
References DBG1, DBG_LIB, and FALSE.
 {
     DBG1(DBG_LIB, "private key decryption not supported by ssh-agent");
     return FALSE;
 }
METHOD (private_key_t , get_keysize , int , private_agent_private_key_t * this)
Definition at line 337 of file agent_private_key.c.
 {
     return this->pubkey->get_keysize(this->pubkey);
 }
METHOD (private_key_t , get_public_key , public_key_t * , private_agent_private_key_t * this)
Definition at line 343 of file agent_private_key.c.
 {
     return this->pubkey->get_ref(this->pubkey);
 }
METHOD (private_key_t , get_encoding , bool , private_agent_private_key_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 349 of file agent_private_key.c.
References FALSE.
 {
     return FALSE;
 }
METHOD (private_key_t , get_fingerprint , bool , private_agent_private_key_t * this, cred_encoding_type_t type, chunk_t * fp)
Definition at line 356 of file agent_private_key.c.
 {
     return this->pubkey->get_fingerprint(this->pubkey, type, fp);
 }
METHOD (private_key_t , get_ref , private_key_t * , private_agent_private_key_t * this)
Definition at line 362 of file agent_private_key.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.key;
 }
METHOD (private_key_t , destroy , void , private_agent_private_key_t * this)
Definition at line 369 of file agent_private_key.c.
References chunk_free(), close, DESTROY_IF, free(), key, ref_put(), and socket.
 {
     if (ref_put(&this->ref))
     {
         close(this->socket);
         chunk_free(&this->key);
         DESTROY_IF(this->pubkey);
         free(this);
     }
 }
static int open_connection (char * path) static
open socket connection to the ssh-agent
Definition at line 137 of file agent_private_key.c.
References close, connect, DBG1, DBG_LIB, s, socket, strerror, and UNIX_PATH_MAX.
Referenced by agent_private_key_open().
 {
     struct sockaddr_un addr;
     int s;
     s = socket(AF_UNIX, SOCK_STREAM, 0);
     if (s == -1)
     {
         DBG1(DBG_LIB, "opening ssh-agent socket %s failed: %s:", path,
              strerror(errno));
         return -1;
     }
     addr.sun_family = AF_UNIX;
     addr.sun_path[UNIX_PATH_MAX - 1] = '\0';
     strncpy(addr.sun_path, path, UNIX_PATH_MAX - 1);
     if (connect(s, (struct sockaddr*)&addr, SUN_LEN(&addr)) != 0)
     {
         DBG1(DBG_LIB, "connecting to ssh-agent socket failed: %s",
              strerror(errno));
         close(s);
         return -1;
     }
     return s;
 }
static u_char read_byte (chunk_t * blob) static
read a byte from a blob
Definition at line 87 of file agent_private_key.c.
References chunk_skip(), chunk_t::len, chunk_t::ptr, and val.
Referenced by METHOD(), and read_key().
 {
     u_char val;
     if (blob->len < sizeof(u_char))
     {
         return 0;
     }
     val = *(blob->ptr);
     *blob = chunk_skip(*blob, sizeof(u_char));
     return val;
 }
static bool read_key (private_agent_private_key_t * this, public_key_t * pubkey) static
Get the first usable key from the agent
Definition at line 167 of file agent_private_key.c.
References blob, BUILD_BLOB_SSHKEY, BUILD_END, chunk_clone, chunk_create(), credential_factory_t::create, CRED_PUBLIC_KEY, library_t::creds, DBG1, DBG_LIB, public_key_t::destroy, FALSE, key, KEY_ANY, chunk_t::len, len, lib, private_key_belongs_to(), chunk_t::ptr, read, read_byte(), read_string(), read_uint32(), socket, SSH_AGENT_ID_REQUEST, SSH_AGENT_ID_RESPONSE, TRUE, and write.
Referenced by agent_private_key_open().
 {
     int len;
     char buf[2048];
     chunk_t blob, key;
     len = htonl(1);
     buf[0] = SSH_AGENT_ID_REQUEST;
     if (write(this->socket, &len, sizeof(len)) != sizeof(len) ||
         write(this->socket, &buf, 1) != 1)
     {
         DBG1(DBG_LIB, "writing to ssh-agent failed");
         return FALSE;
     }
     blob = chunk_create(buf, sizeof(buf));
     blob.len = read(this->socket, blob.ptr, blob.len);
     if (blob.len < sizeof(u_int32_t) + sizeof(u_char) ||
         read_uint32(&blob) != blob.len ||
         read_byte(&blob) != SSH_AGENT_ID_RESPONSE)
     {
         DBG1(DBG_LIB, "received invalid ssh-agent identity response");
         return FALSE;
     }
     read_uint32(&blob);
     while (blob.len)
     {
         key = read_string(&blob);
         if (!key.len)
         {
             break;
         }
         this->pubkey = lib->creds->create(lib->creds, CRED_PUBLIC_KEY, KEY_ANY,
                                           BUILD_BLOB_SSHKEY, key, BUILD_END);
         if (!this->pubkey)
         {
             continue;
         }
         if (pubkey && !private_key_belongs_to(&this->public.key, pubkey))
         {
             this->pubkey->destroy(this->pubkey);
             this->pubkey = NULL;
             continue;
         }
         this->key = chunk_clone(key);
         return TRUE;
     }
     return FALSE;
 }
static chunk_t read_string (chunk_t * blob) static
read a ssh-agent "string" length/value from a blob
Definition at line 119 of file agent_private_key.c.
References chunk_create(), chunk_empty, chunk_skip(), chunk_t::len, len, chunk_t::ptr, read_uint32(), and str.
Referenced by METHOD(), and read_key().
 {
     int len;
     chunk_t str;
     len = read_uint32(blob);
     if (len > blob->len)
     {
         return chunk_empty;
     }
     str = chunk_create(blob->ptr, len);
     *blob = chunk_skip(*blob, + len);
     return str;
 }
static u_int32_t read_uint32 (chunk_t * blob) static
read a u_int32_t from a blob
Definition at line 103 of file agent_private_key.c.
References chunk_skip(), chunk_t::len, chunk_t::ptr, and val.
Referenced by METHOD(), read_key(), and read_string().
 {
     u_int32_t val;
     if (blob->len < sizeof(u_int32_t))
     {
         return 0;
     }
     val = ntohl(*(u_int32_t*)blob->ptr);
     *blob = chunk_skip(*blob, sizeof(u_int32_t));
     return val;
 }
static bool scheme_supported (private_agent_private_key_t * this, signature_scheme_t scheme) static
Definition at line 219 of file agent_private_key.c.
References FALSE, KEY_ECDSA, KEY_RSA, SIGN_ECDSA_256, SIGN_ECDSA_384, SIGN_ECDSA_521, and SIGN_RSA_EMSA_PKCS1_SHA1.
Referenced by METHOD().
 {
     switch (this->pubkey->get_type(this->pubkey))
     {
         case KEY_RSA:
             return scheme == SIGN_RSA_EMSA_PKCS1_SHA1;
         case KEY_ECDSA:
             return scheme == SIGN_ECDSA_256 ||
                    scheme == SIGN_ECDSA_384 ||
                    scheme == SIGN_ECDSA_521;
         default:
             return FALSE;
     }
 }