strongSwan: ita_attr_settings.c File Reference
ita_attr_settings.c File Reference
#include <string.h>
#include "ita_attr.h"
#include "ita_attr_settings.h"
#include <bio/bio_reader.h>
#include <bio/bio_writer.h>
#include <collections/linked_list.h>
#include <pen/pen.h>
#include <utils/debug.h>
Classes
struct entry_t
struct private_ita_attr_settings_t
Macros
#define _GNU_SOURCE /* for stdndup() */
#define ITA_SETTINGS_MIN_SIZE 4
Typedefs
typedef struct
private_ita_attr_settings_t private_ita_attr_settings_t
typedef struct entry_t entry_t
Functions
static void free_entry (entry_t *this)
METHOD (pa_tnc_attr_t, get_type, pen_type_t, private_ita_attr_settings_t *this)
METHOD (pa_tnc_attr_t, get_value, chunk_t, private_ita_attr_settings_t *this)
METHOD (pa_tnc_attr_t, get_noskip_flag, bool, private_ita_attr_settings_t *this)
METHOD (pa_tnc_attr_t, set_noskip_flag, void, private_ita_attr_settings_t *this, bool noskip)
METHOD (pa_tnc_attr_t, build, void, private_ita_attr_settings_t *this)
METHOD (pa_tnc_attr_t, process, status_t, private_ita_attr_settings_t *this, u_int32_t *offset)
METHOD (pa_tnc_attr_t, add_segment, void, private_ita_attr_settings_t *this, chunk_t segment)
METHOD (pa_tnc_attr_t, get_ref, pa_tnc_attr_t *, private_ita_attr_settings_t *this)
METHOD (pa_tnc_attr_t, destroy, void, private_ita_attr_settings_t *this)
METHOD (ita_attr_settings_t, add, void, private_ita_attr_settings_t *this, char *name, chunk_t value)
static bool entry_filter (void *null, entry_t **entry, char **name, void *i2, chunk_t *value)
METHOD (ita_attr_settings_t, create_enumerator, enumerator_t *, private_ita_attr_settings_t *this)
pa_tnc_attr_t * ita_attr_settings_create (void)
pa_tnc_attr_t * ita_attr_settings_create_from_data (size_t length, chunk_t data)
Macro Definition Documentation
#define _GNU_SOURCE /* for stdndup() */
Definition at line 16 of file ita_attr_settings.c.
#define ITA_SETTINGS_MIN_SIZE 4
ITA Settings
               1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Settings Count | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Name Length | Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Value Length | Value (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Value (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Name Length | Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Name (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | Value Length | Value (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ~ Value (Variable Length) ~ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ ...........................
Definition at line 76 of file ita_attr_settings.c.
Referenced by METHOD().
Typedef Documentation
typedef struct entry_t entry_t
Definition at line 29 of file ita_attr_settings.c.
typedef struct private_ita_attr_settings_t private_ita_attr_settings_t
Definition at line 28 of file ita_attr_settings.c.
Function Documentation
static bool entry_filter (void * null, entry_t ** entry, char ** name, void * i2, chunk_t * value) static
Enumerate name/value pairs
Definition at line 268 of file ita_attr_settings.c.
References TRUE.
Referenced by METHOD().
 {
     *name = (*entry)->name;
     *value = (*entry)->value;
     return TRUE;
 }
static void free_entry (entry_t * this) static
Free an entry_t object
Definition at line 42 of file ita_attr_settings.c.
References free(), name, and value.
Referenced by METHOD().
 {
     free(this->name);
     free(this->value.ptr);
     free(this);
 }
METHOD (pa_tnc_attr_t , get_type , pen_type_t , private_ita_attr_settings_t * this)
Definition at line 119 of file ita_attr_settings.c.
References type.
 {
     return this->type;
 }
METHOD (pa_tnc_attr_t , get_value , chunk_t , private_ita_attr_settings_t * this)
Definition at line 125 of file ita_attr_settings.c.
References value.
 {
     return this->value;
 }
METHOD (pa_tnc_attr_t , get_noskip_flag , bool , private_ita_attr_settings_t * this)
Definition at line 131 of file ita_attr_settings.c.
 {
     return this->noskip_flag;
 }
METHOD (pa_tnc_attr_t , set_noskip_flag , void , private_ita_attr_settings_t * this, bool noskip)
Definition at line 137 of file ita_attr_settings.c.
 {
     this->noskip_flag = noskip;
 }
METHOD (pa_tnc_attr_t , build , void , private_ita_attr_settings_t * this)
Definition at line 143 of file ita_attr_settings.c.
References bio_writer_create(), chunk_create(), linked_list_t::create_enumerator, enumerator_t::destroy, bio_writer_t::destroy, enumerator_t::enumerate, bio_writer_t::extract_buf, linked_list_t::get_count, ITA_SETTINGS_MIN_SIZE, length, list, entry_t::name, entry_t::value, value, bio_writer_t::write_data16, and bio_writer_t::write_uint32.
 {
     bio_writer_t *writer;
     enumerator_t *enumerator;
     entry_t *entry;
     if (this->value.ptr)
     {
         return;
     }
     writer = bio_writer_create(ITA_SETTINGS_MIN_SIZE);
     writer->write_uint32(writer, this->list->get_count(this->list));
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         writer->write_data16(writer, chunk_create(entry->name,
                                                   strlen(entry->name)));
         writer->write_data16(writer, entry->value);
     }
     enumerator->destroy(enumerator);
     this->value = writer->extract_buf(writer);
     this->length = this->value.len;
     writer->destroy(writer);
 }
METHOD (pa_tnc_attr_t , process , status_t , private_ita_attr_settings_t * this, u_int32_t * offset)
Definition at line 171 of file ita_attr_settings.c.
References bio_reader_create(), chunk_clone, count, DBG1, DBG_TNC, bio_reader_t::destroy, end, FAILED, linked_list_t::insert_last, ITA_SETTINGS_MIN_SIZE, chunk_t::len, list, malloc_thing, name, entry_t::name, NEED_MORE, chunk_t::ptr, bio_reader_t::read_data16, bio_reader_t::read_uint32, status, strndup(), SUCCESS, entry_t::value, and value.
 {
     bio_reader_t *reader;
     u_int32_t count;
     chunk_t name, value;
     entry_t *entry;
     status_t status = FAILED;
     *offset = 0;
     if (this->value.len < this->length)
     {
         return NEED_MORE;
     }
     if (this->value.len < ITA_SETTINGS_MIN_SIZE)
     {
         DBG1(DBG_TNC, "insufficient data for ITA Settings attribute");
         return FAILED;
     }
     reader = bio_reader_create(this->value);
     reader->read_uint32(reader, &count);
     *offset = ITA_SETTINGS_MIN_SIZE;
     while (count--)
     {
         if (!reader->read_data16(reader, &name))
         {
             DBG1(DBG_TNC, "insufficient data for setting name");
             goto end;
         }
         *offset += 2 + name.len;
         if (!reader->read_data16(reader, &value))
         {
             DBG1(DBG_TNC, "insufficient data for setting value");
             goto end;
         }
         *offset += 2 + value.len;
         /* remove a terminating newline character */
         if (value.len && value.ptr[value.len - 1] == '\n')
         {
             value.len--;
         }
         entry = malloc_thing(entry_t);
         entry->name = strndup(name.ptr, name.len);
         entry->value = chunk_clone(value);
         this->list->insert_last(this->list, entry);
     }
     status = SUCCESS;
 end:
     reader->destroy(reader);
     return status;
 }
METHOD (pa_tnc_attr_t , add_segment , void , private_ita_attr_settings_t * this, chunk_t segment)
Definition at line 230 of file ita_attr_settings.c.
References chunk_cat, and value.
 {
     this->value = chunk_cat("mc", this->value, segment);
 }
METHOD (pa_tnc_attr_t , get_ref , pa_tnc_attr_t * , private_ita_attr_settings_t * this)
Definition at line 236 of file ita_attr_settings.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.pa_tnc_attribute;
 }
METHOD (pa_tnc_attr_t , destroy , void , private_ita_attr_settings_t * this)
Definition at line 243 of file ita_attr_settings.c.
References linked_list_t::destroy_function, free(), free_entry(), list, ref_put(), and value.
 {
     if (ref_put(&this->ref))
     {
         this->list->destroy_function(this->list, (void*)free_entry);
         free(this->value.ptr);
         free(this);
     }
 }
METHOD (ita_attr_settings_t , add , void , private_ita_attr_settings_t * this, char * name, chunk_t value)
Definition at line 254 of file ita_attr_settings.c.
References chunk_clone, linked_list_t::insert_last, list, malloc_thing, entry_t::name, strdup, and entry_t::value.
 {
     entry_t *entry;
     entry = malloc_thing(entry_t);
     entry->name = strdup(name);
     entry->value = chunk_clone(value);
     this->list->insert_last(this->list, entry);
 }
METHOD (ita_attr_settings_t , create_enumerator , enumerator_t * , private_ita_attr_settings_t * this)
Definition at line 276 of file ita_attr_settings.c.
References linked_list_t::create_enumerator, entry_filter(), enumerator_create_filter(), and list.
 {
     return enumerator_create_filter(this->list->create_enumerator(this->list),
                                    (void*)entry_filter, NULL, NULL);
 }