strongSwan: child_cfg.c File Reference
child_cfg.c File Reference
#include "child_cfg.h"
#include <stdint.h>
#include <daemon.h>
Classes
struct private_child_cfg_t
Macros
#define DEFAULT_REPLAY_WINDOW 32
#define APPLY_JITTER(l) l.rekey = apply_jitter(l.rekey, l.jitter)
Typedefs
typedef struct private_child_cfg_t private_child_cfg_t
Functions
ENUM (action_names, ACTION_NONE, ACTION_RESTART,"clear","hold","restart",)
METHOD (child_cfg_t, get_name, char *, private_child_cfg_t *this)
METHOD (child_cfg_t, add_proposal, void, private_child_cfg_t *this, proposal_t *proposal)
static bool match_proposal (proposal_t *item, proposal_t *proposal)
METHOD (child_cfg_t, get_proposals, linked_list_t *, private_child_cfg_t *this, bool strip_dh)
METHOD (child_cfg_t, select_proposal, proposal_t *, private_child_cfg_t *this, linked_list_t *proposals, bool strip_dh, bool private)
METHOD (child_cfg_t, add_traffic_selector, void, private_child_cfg_t *this, bool local, traffic_selector_t *ts)
METHOD (child_cfg_t, get_traffic_selectors, linked_list_t *, private_child_cfg_t *this, bool local, linked_list_t *supplied, linked_list_t *hosts)
METHOD (child_cfg_t, get_updown, char *, private_child_cfg_t *this)
METHOD (child_cfg_t, get_hostaccess, bool, private_child_cfg_t *this)
static u_int64_t apply_jitter (u_int64_t rekey, u_int64_t jitter)
METHOD (child_cfg_t, get_lifetime, lifetime_cfg_t *, private_child_cfg_t *this)
METHOD (child_cfg_t, get_mode, ipsec_mode_t, private_child_cfg_t *this)
METHOD (child_cfg_t, get_start_action, action_t, private_child_cfg_t *this)
METHOD (child_cfg_t, get_dpd_action, action_t, private_child_cfg_t *this)
METHOD (child_cfg_t, get_close_action, action_t, private_child_cfg_t *this)
METHOD (child_cfg_t, get_dh_group, diffie_hellman_group_t, private_child_cfg_t *this)
METHOD (child_cfg_t, use_ipcomp, bool, private_child_cfg_t *this)
METHOD (child_cfg_t, get_inactivity, u_int32_t, private_child_cfg_t *this)
METHOD (child_cfg_t, get_reqid, u_int32_t, private_child_cfg_t *this)
METHOD (child_cfg_t, get_mark, mark_t, private_child_cfg_t *this, bool inbound)
METHOD (child_cfg_t, get_tfc, u_int32_t, private_child_cfg_t *this)
METHOD (child_cfg_t, get_replay_window, u_int32_t, private_child_cfg_t *this)
METHOD (child_cfg_t, set_replay_window, void, private_child_cfg_t *this, u_int32_t replay_window)
METHOD (child_cfg_t, set_mipv6_options, void, private_child_cfg_t *this, bool proxy_mode, bool install_policy)
METHOD (child_cfg_t, use_proxy_mode, bool, private_child_cfg_t *this)
METHOD (child_cfg_t, install_policy, bool, private_child_cfg_t *this)
METHOD (child_cfg_t, get_ref, child_cfg_t *, private_child_cfg_t *this)
METHOD (child_cfg_t, destroy, void, private_child_cfg_t *this)
child_cfg_t * child_cfg_create (char *name, lifetime_cfg_t *lifetime, char *updown, bool hostaccess, ipsec_mode_t mode, action_t start_action, action_t dpd_action, action_t close_action, bool ipcomp, u_int32_t inactivity, u_int32_t reqid, mark_t *mark_in, mark_t *mark_out, u_int32_t tfc)
Macro Definition Documentation
#define APPLY_JITTER (l) l.rekey = apply_jitter(l.rekey, l.jitter)
Definition at line 417 of file child_cfg.c.
Referenced by METHOD().
#define DEFAULT_REPLAY_WINDOW 32
Default replay window size, if not set using charon.replay_window
Definition at line 31 of file child_cfg.c.
Referenced by child_cfg_create().
Typedef Documentation
typedef struct private_child_cfg_t private_child_cfg_t
Definition at line 33 of file child_cfg.c.
Function Documentation
static u_int64_t apply_jitter (u_int64_t rekey, u_int64_t jitter) static
Applies jitter to the rekey value. Returns the new rekey value. Note: The distribution of random values is not perfect, but it should get the job done.
Definition at line 408 of file child_cfg.c.
References random.
 {
     if (jitter == 0)
     {
         return rekey;
     }
     jitter = (jitter == UINT64_MAX) ? jitter : jitter + 1;
     return rekey - jitter * (random() / (RAND_MAX + 1.0));
 }
ENUM (action_names , ACTION_NONE , ACTION_RESTART , "clear" , "hold" , "restart")
static bool match_proposal (proposal_t * item, proposal_t * proposal) static
Definition at line 166 of file child_cfg.c.
References proposal_t::equals.
Referenced by METHOD().
 {
     return item->equals(item, proposal);
 }
METHOD (child_cfg_t , get_name , char * , private_child_cfg_t * this)
Definition at line 151 of file child_cfg.c.
References name.
 {
     return this->name;
 }
METHOD (child_cfg_t , add_proposal , void , private_child_cfg_t * this, proposal_t * proposal)
Definition at line 157 of file child_cfg.c.
 {
     if (proposal)
     {
         this->proposals->insert_last(this->proposals, proposal);
     }
 }
METHOD (child_cfg_t , get_proposals , linked_list_t * , private_child_cfg_t * this, bool strip_dh)
Definition at line 171 of file child_cfg.c.
References proposal_t::clone, linked_list_t::create_enumerator, DBG2, DBG_CFG, enumerator_t::destroy, proposal_t::destroy, enumerator_t::enumerate, linked_list_t::find_first, linked_list_t::insert_last, linked_list_create(), match_proposal(), MODP_NONE, proposal_t::strip_dh, and SUCCESS.
 {
     enumerator_t *enumerator;
     proposal_t *current;
     linked_list_t *proposals = linked_list_create();
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, &current))
     {
         current = current->clone(current);
         if (strip_dh)
         {
             current->strip_dh(current, MODP_NONE);
         }
         if (proposals->find_first(proposals, (linked_list_match_t)match_proposal,
                                   NULL, current) == SUCCESS)
         {
             current->destroy(current);
             continue;
         }
         proposals->insert_last(proposals, current);
     }
     enumerator->destroy(enumerator);
     DBG2(DBG_CFG, "configured proposals: %#P", proposals);
     return proposals;
 }
METHOD (child_cfg_t , select_proposal , proposal_t * , private_child_cfg_t * this, linked_list_t * proposals, bool strip_dh, bool private)
Definition at line 201 of file child_cfg.c.
References proposal_t::clone, linked_list_t::create_enumerator, DBG1, DBG2, DBG_CFG, enumerator_t::destroy, proposal_t::destroy, enumerator_t::enumerate, MODP_NONE, proposal_t::select, and proposal_t::strip_dh.
 {
     enumerator_t *stored_enum, *supplied_enum;
     proposal_t *stored, *supplied, *selected = NULL;
     stored_enum = this->proposals->create_enumerator(this->proposals);
     supplied_enum = proposals->create_enumerator(proposals);
     /* compare all stored proposals with all supplied. Stored ones are preferred. */
     while (stored_enum->enumerate(stored_enum, &stored))
     {
         stored = stored->clone(stored);
         while (supplied_enum->enumerate(supplied_enum, &supplied))
         {
             if (strip_dh)
             {
                 stored->strip_dh(stored, MODP_NONE);
             }
             selected = stored->select(stored, supplied, private);
             if (selected)
             {
                 DBG2(DBG_CFG, "received proposals: %#P", proposals);
                 DBG2(DBG_CFG, "configured proposals: %#P", this->proposals);
                 DBG2(DBG_CFG, "selected proposal: %P", selected);
                 break;
             }
         }
         stored->destroy(stored);
         if (selected)
         {
             break;
         }
         supplied_enum->destroy(supplied_enum);
         supplied_enum = proposals->create_enumerator(proposals);
     }
     stored_enum->destroy(stored_enum);
     supplied_enum->destroy(supplied_enum);
     if (selected == NULL)
     {
         DBG1(DBG_CFG, "received proposals: %#P", proposals);
         DBG1(DBG_CFG, "configured proposals: %#P", this->proposals);
     }
     return selected;
 }
METHOD (child_cfg_t , add_traffic_selector , void , private_child_cfg_t * this, bool local, traffic_selector_t * ts)
Definition at line 248 of file child_cfg.c.
 {
     if (local)
     {
         this->my_ts->insert_last(this->my_ts, ts);
     }
     else
     {
         this->other_ts->insert_last(this->other_ts, ts);
     }
 }
METHOD (child_cfg_t , get_traffic_selectors , linked_list_t * , private_child_cfg_t * this, bool local, linked_list_t * supplied, linked_list_t * hosts)
Definition at line 261 of file child_cfg.c.
References bus_t::alert, ALERT_TS_NARROWED, daemon_t::bus, charon, traffic_selector_t::clone, linked_list_t::create_enumerator, DBG2, DBG_CFG, enumerator_t::destroy, linked_list_t::destroy, traffic_selector_t::destroy, destroy(), linked_list_t::destroy_offset, enumerator_t::enumerate, traffic_selector_t::equals, linked_list_t::get_count, traffic_selector_t::get_subset, host, linked_list_t::insert_last, traffic_selector_t::is_contained_in, traffic_selector_t::is_dynamic, linked_list_create(), linked_list_t::remove_at, linked_list_t::remove_first, linked_list_t::reset_enumerator, result, traffic_selector_t::set_address, and SUCCESS.
 {
     enumerator_t *e1, *e2;
     traffic_selector_t *ts1, *ts2, *selected;
     linked_list_t *result, *derived;
     host_t *host;
     result = linked_list_create();
     derived = linked_list_create();
     if (local)
     {
         e1 = this->my_ts->create_enumerator(this->my_ts);
     }
     else
     {
         e1 = this->other_ts->create_enumerator(this->other_ts);
     }
     /* In a first step, replace "dynamic" TS with the host list */
     while (e1->enumerate(e1, &ts1))
     {
         if (hosts && hosts->get_count(hosts) &&
             ts1->is_dynamic(ts1))
         {
             e2 = hosts->create_enumerator(hosts);
             while (e2->enumerate(e2, &host))
             {
                 ts2 = ts1->clone(ts1);
                 ts2->set_address(ts2, host);
                 derived->insert_last(derived, ts2);
             }
             e2->destroy(e2);
         }
         else
         {
             derived->insert_last(derived, ts1->clone(ts1));
         }
     }
     e1->destroy(e1);
     DBG2(DBG_CFG, "%s traffic selectors for %s:",
          supplied ? "selecting" : "proposing", local ? "us" : "other");
     if (supplied == NULL)
     {
         while (derived->remove_first(derived, (void**)&ts1) == SUCCESS)
         {
             DBG2(DBG_CFG, " %R", ts1);
             result->insert_last(result, ts1);
         }
         derived->destroy(derived);
     }
     else
     {
         e1 = derived->create_enumerator(derived);
         e2 = supplied->create_enumerator(supplied);
         /* enumerate all configured/derived selectors */
         while (e1->enumerate(e1, &ts1))
         {
             /* enumerate all supplied traffic selectors */
             while (e2->enumerate(e2, &ts2))
             {
                 selected = ts1->get_subset(ts1, ts2);
                 if (selected)
                 {
                     DBG2(DBG_CFG, " config: %R, received: %R => match: %R",
                          ts1, ts2, selected);
                     result->insert_last(result, selected);
                 }
                 else
                 {
                     DBG2(DBG_CFG, " config: %R, received: %R => no match",
                          ts1, ts2);
                 }
             }
             supplied->reset_enumerator(supplied, e2);
         }
         e1->destroy(e1);
         e2->destroy(e2);
         /* check if we/peer did any narrowing, raise alert */
         e1 = derived->create_enumerator(derived);
         e2 = result->create_enumerator(result);
         while (e1->enumerate(e1, &ts1))
         {
             if (!e2->enumerate(e2, &ts2) || !ts1->equals(ts1, ts2))
             {
                 charon->bus->alert(charon->bus, ALERT_TS_NARROWED,
                                    local, result, this);
                 break;
             }
         }
         e1->destroy(e1);
         e2->destroy(e2);
         derived->destroy_offset(derived, offsetof(traffic_selector_t, destroy));
     }
     /* remove any redundant traffic selectors in the list */
     e1 = result->create_enumerator(result);
     e2 = result->create_enumerator(result);
     while (e1->enumerate(e1, &ts1))
     {
         while (e2->enumerate(e2, &ts2))
         {
             if (ts1 != ts2)
             {
                 if (ts2->is_contained_in(ts2, ts1))
                 {
                     result->remove_at(result, e2);
                     ts2->destroy(ts2);
                     result->reset_enumerator(result, e1);
                     break;
                 }
                 if (ts1->is_contained_in(ts1, ts2))
                 {
                     result->remove_at(result, e1);
                     ts1->destroy(ts1);
                     break;
                 }
             }
         }
         result->reset_enumerator(result, e2);
     }
     e1->destroy(e1);
     e2->destroy(e2);
     return result;
 }
METHOD (child_cfg_t , get_updown , char * , private_child_cfg_t * this)
Definition at line 391 of file child_cfg.c.
 {
     return this->updown;
 }
METHOD (child_cfg_t , get_hostaccess , bool , private_child_cfg_t * this)
Definition at line 397 of file child_cfg.c.
 {
     return this->hostaccess;
 }
METHOD (child_cfg_t , get_lifetime , lifetime_cfg_t * , private_child_cfg_t * this)
Definition at line 419 of file child_cfg.c.
References APPLY_JITTER, lifetime_cfg_t::bytes, malloc_thing, memcpy, lifetime_cfg_t::packets, and lifetime_cfg_t::time.
 {
     lifetime_cfg_t *lft = malloc_thing(lifetime_cfg_t);
     memcpy(lft, &this->lifetime, sizeof(lifetime_cfg_t));
     APPLY_JITTER(lft->time);
     APPLY_JITTER(lft->bytes);
     APPLY_JITTER(lft->packets);
     return lft;
 }
METHOD (child_cfg_t , get_mode , ipsec_mode_t , private_child_cfg_t * this)
Definition at line 430 of file child_cfg.c.
 {
     return this->mode;
 }
METHOD (child_cfg_t , get_start_action , action_t , private_child_cfg_t * this)
Definition at line 436 of file child_cfg.c.
 {
     return this->start_action;
 }
METHOD (child_cfg_t , get_dpd_action , action_t , private_child_cfg_t * this)
Definition at line 442 of file child_cfg.c.
 {
     return this->dpd_action;
 }
METHOD (child_cfg_t , get_close_action , action_t , private_child_cfg_t * this)
Definition at line 448 of file child_cfg.c.
 {
     return this->close_action;
 }
METHOD (child_cfg_t , get_dh_group , diffie_hellman_group_t , private_child_cfg_t * this)
Definition at line 454 of file child_cfg.c.
References enumerator_t::destroy, DIFFIE_HELLMAN_GROUP, enumerator_t::enumerate, proposal_t::get_algorithm, MODP_NONE, and proposal.
 {
     enumerator_t *enumerator;
     proposal_t *proposal;
     u_int16_t dh_group = MODP_NONE;
     enumerator = this->proposals->create_enumerator(this->proposals);
     while (enumerator->enumerate(enumerator, &proposal))
     {
         if (proposal->get_algorithm(proposal, DIFFIE_HELLMAN_GROUP, &dh_group, NULL))
         {
             break;
         }
     }
     enumerator->destroy(enumerator);
     return dh_group;
 }
METHOD (child_cfg_t , use_ipcomp , bool , private_child_cfg_t * this)
Definition at line 473 of file child_cfg.c.
 {
     return this->use_ipcomp;
 }
METHOD (child_cfg_t , get_inactivity , u_int32_t , private_child_cfg_t * this)
Definition at line 479 of file child_cfg.c.
 {
     return this->inactivity;
 }
METHOD (child_cfg_t , get_reqid , u_int32_t , private_child_cfg_t * this)
Definition at line 485 of file child_cfg.c.
 {
     return this->reqid;
 }
METHOD (child_cfg_t , get_mark , mark_t , private_child_cfg_t * this, bool inbound)
Definition at line 491 of file child_cfg.c.
 {
     return inbound ? this->mark_in : this->mark_out;
 }
METHOD (child_cfg_t , get_tfc , u_int32_t , private_child_cfg_t * this)
Definition at line 497 of file child_cfg.c.
 {
     return this->tfc;
 }
METHOD (child_cfg_t , get_replay_window , u_int32_t , private_child_cfg_t * this)
Definition at line 503 of file child_cfg.c.
 {
     return this->replay_window;
 }
METHOD (child_cfg_t , set_replay_window , void , private_child_cfg_t * this, u_int32_t replay_window)
Definition at line 509 of file child_cfg.c.
 {
     this->replay_window = replay_window;
 }
METHOD (child_cfg_t , set_mipv6_options , void , private_child_cfg_t * this, bool proxy_mode, bool install_policy)
Definition at line 515 of file child_cfg.c.
 {
     this->proxy_mode = proxy_mode;
     this->install_policy = install_policy;
 }
METHOD (child_cfg_t , use_proxy_mode , bool , private_child_cfg_t * this)
Definition at line 522 of file child_cfg.c.
 {
     return this->proxy_mode;
 }
METHOD (child_cfg_t , install_policy , bool , private_child_cfg_t * this)
Definition at line 528 of file child_cfg.c.
 {
     return this->install_policy;
 }
METHOD (child_cfg_t , get_ref , child_cfg_t * , private_child_cfg_t * this)
Definition at line 534 of file child_cfg.c.
References ref_get().
 {
     ref_get(&this->refcount);
     return &this->public;
 }
METHOD (child_cfg_t , destroy , void , private_child_cfg_t * this)
Definition at line 541 of file child_cfg.c.
References destroy(), free(), name, and ref_put().
 {
     if (ref_put(&this->refcount))
     {
         this->proposals->destroy_offset(this->proposals, offsetof(proposal_t, destroy));
         this->my_ts->destroy_offset(this->my_ts, offsetof(traffic_selector_t, destroy));
         this->other_ts->destroy_offset(this->other_ts, offsetof(traffic_selector_t, destroy));
         if (this->updown)
         {
             free(this->updown);
         }
         free(this->name);
         free(this);
     }
 }