strongSwan: medsrv_config.c File Reference
medsrv_config.c File Reference
#include <string.h>
#include "medsrv_config.h"
#include <daemon.h>
Classes
struct private_medsrv_config_t
Typedefs
typedef struct
private_medsrv_config_t private_medsrv_config_t
Functions
METHOD (backend_t, get_peer_cfg_by_name, peer_cfg_t *, private_medsrv_config_t *this, char *name)
METHOD (backend_t, create_ike_cfg_enumerator, enumerator_t *, private_medsrv_config_t *this, host_t *me, host_t *other)
METHOD (backend_t, create_peer_cfg_enumerator, enumerator_t *, private_medsrv_config_t *this, identification_t *me, identification_t *other)
METHOD (medsrv_config_t, destroy, void, private_medsrv_config_t *this)
medsrv_config_t * medsrv_config_create (database_t *db)
Typedef Documentation
typedef struct private_medsrv_config_t private_medsrv_config_t
Definition at line 22 of file medsrv_config.c.
Function Documentation
METHOD (backend_t , get_peer_cfg_by_name , peer_cfg_t * , private_medsrv_config_t * this, char * name)
Definition at line 55 of file medsrv_config.c.
 {
     return NULL;
 }
METHOD (backend_t , create_ike_cfg_enumerator , enumerator_t * , private_medsrv_config_t * this, host_t * me, host_t * other)
Definition at line 61 of file medsrv_config.c.
References enumerator_create_single().
 {
     return enumerator_create_single(this->ike, NULL);
 }
METHOD (backend_t , create_peer_cfg_enumerator , enumerator_t * , private_medsrv_config_t * this, identification_t * me, identification_t * other)
Definition at line 67 of file medsrv_config.c.
References auth_cfg_t::add, peer_cfg_t::add_auth_cfg, auth_cfg_create(), AUTH_CLASS_PUBKEY, AUTH_RULE_AUTH_CLASS, AUTH_RULE_IDENTITY, CERT_NEVER_SEND, identification_t::clone, db, DB_BLOB, DB_TEXT, enumerator_t::destroy, peer_cfg_t::destroy, enumerator_t::enumerate, enumerator_create_single(), FALSE, identification_t::get_encoding, identification_t::get_type, ID_KEY_ID, name, peer_cfg_create(), database_t::query, TRUE, and UNIQUE_REPLACE.
 {
     enumerator_t *e;
     if (!me || !other || other->get_type(other) != ID_KEY_ID)
     {
         return NULL;
     }
     e = this->db->query(this->db,
             "SELECT CONCAT(peer.alias, CONCAT('@', user.login)) FROM "
             "peer JOIN user ON peer.user = user.id "
             "WHERE peer.keyid = ?", DB_BLOB, other->get_encoding(other),
             DB_TEXT);
     if (e)
     {
         peer_cfg_t *peer_cfg;
         auth_cfg_t *auth;
         char *name;
         if (e->enumerate(e, &name))
         {
             peer_cfg = peer_cfg_create(
                 name, this->ike->get_ref(this->ike),
                 CERT_NEVER_SEND, UNIQUE_REPLACE,
                 1, this->rekey*60, 0,           /* keytries, rekey, reauth */
                 this->rekey*5, this->rekey*3,   /* jitter, overtime */
                 TRUE, FALSE, TRUE,              /* mobike, aggressive, pull */
                 this->dpd, 0,                   /* DPD delay, timeout */
                 TRUE, NULL, NULL);              /* mediation, med by, peer id */
             e->destroy(e);
             auth = auth_cfg_create();
             auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
             auth->add(auth, AUTH_RULE_IDENTITY, me->clone(me));
             peer_cfg->add_auth_cfg(peer_cfg, auth, TRUE);
             auth = auth_cfg_create();
             auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
             auth->add(auth, AUTH_RULE_IDENTITY, other->clone(other));
             peer_cfg->add_auth_cfg(peer_cfg, auth, FALSE);
             return enumerator_create_single(peer_cfg, (void*)peer_cfg->destroy);
         }
         e->destroy(e);
     }
     return NULL;
 }
METHOD (medsrv_config_t , destroy , void , private_medsrv_config_t * this)
Definition at line 116 of file medsrv_config.c.
References free().
 {
     this->ike->destroy(this->ike);
     free(this);
 }