strongSwan: blowfish.h File Reference
blowfish.h File Reference
#include <sys/types.h>
Classes
struct bf_key_st
Macros
#define BF_ENCRYPT 1
#define BF_DECRYPT 0
#define BF_LONG u_int32_t
#define BF_ROUNDS 16
#define BF_BLOCK 8
Typedefs
typedef struct bf_key_st BF_KEY
Functions
void BF_set_key (BF_KEY *key, int len, const unsigned char *data)
void BF_encrypt (BF_LONG *data, const BF_KEY *key)
void BF_decrypt (BF_LONG *data, const BF_KEY *key)
void BF_ecb_encrypt (const unsigned char *in, unsigned char *out, const BF_KEY *key, int enc)
void BF_cbc_encrypt (const unsigned char *in, unsigned char *out, long length, const BF_KEY *schedule, unsigned char *ivec, int enc)
void BF_cfb64_encrypt (const unsigned char *in, unsigned char *out, long length, const BF_KEY *schedule, unsigned char *ivec, int *num, int enc)
void BF_ofb64_encrypt (const unsigned char *in, unsigned char *out, long length, const BF_KEY *schedule, unsigned char *ivec, int *num)
const char * BF_options (void)
Macro Definition Documentation
#define BF_BLOCK 8
Definition at line 105 of file blowfish.h.
#define BF_DECRYPT 0
Definition at line 71 of file blowfish.h.
#define BF_ENCRYPT 1
Definition at line 70 of file blowfish.h.
#define BF_LONG u_int32_t
Definition at line 101 of file blowfish.h.
Referenced by BF_cbc_encrypt(), BF_decrypt(), BF_encrypt(), and BF_set_key().
#define BF_ROUNDS 16
Definition at line 104 of file blowfish.h.
Referenced by BF_decrypt(), BF_encrypt(), and BF_set_key().
Typedef Documentation
typedef struct bf_key_st BF_KEY
Function Documentation
void BF_cbc_encrypt (const unsigned char * in, unsigned char * out, long length, const BF_KEY * schedule, unsigned char * ivec, int enc)
Definition at line 224 of file bf_enc.c.
References BF_decrypt(), BF_encrypt(), BF_LONG, l2n, l2nn, length, n2l, and n2ln.
Referenced by METHOD().
 {
     BF_LONG tin0,tin1;
     BF_LONG tout0,tout1,xor0,xor1;
     long l=length;
     BF_LONG tin[2];
     if (encrypt)
     {
         n2l(ivec,tout0);
         n2l(ivec,tout1);
         ivec-=8;
         for (l-=8; l>=0; l-=8)
         {
             n2l(in,tin0);
             n2l(in,tin1);
             tin0^=tout0;
             tin1^=tout1;
             tin[0]=tin0;
             tin[1]=tin1;
             BF_encrypt(tin,schedule);
             tout0=tin[0];
             tout1=tin[1];
             l2n(tout0,out);
             l2n(tout1,out);
         }
         if (l != -8)
         {
             n2ln(in,tin0,tin1,l+8);
             tin0^=tout0;
             tin1^=tout1;
             tin[0]=tin0;
             tin[1]=tin1;
             BF_encrypt(tin,schedule);
             tout0=tin[0];
             tout1=tin[1];
             l2n(tout0,out);
             l2n(tout1,out);
         }
         l2n(tout0,ivec);
         l2n(tout1,ivec);
     }
     else
     {
         n2l(ivec,xor0);
         n2l(ivec,xor1);
         ivec-=8;
         for (l-=8; l>=0; l-=8)
         {
             n2l(in,tin0);
             n2l(in,tin1);
             tin[0]=tin0;
             tin[1]=tin1;
             BF_decrypt(tin,schedule);
             tout0=tin[0]^xor0;
             tout1=tin[1]^xor1;
             l2n(tout0,out);
             l2n(tout1,out);
             xor0=tin0;
             xor1=tin1;
         }
         if (l != -8)
         {
             n2l(in,tin0);
             n2l(in,tin1);
             tin[0]=tin0;
             tin[1]=tin1;
             BF_decrypt(tin,schedule);
             tout0=tin[0]^xor0;
             tout1=tin[1]^xor1;
             l2nn(tout0,tout1,out,l+8);
             xor0=tin0;
             xor1=tin1;
         }
         l2n(xor0,ivec);
         l2n(xor1,ivec);
     }
     tin0=tin1=tout0=tout1=xor0=xor1=0;
     tin[0]=tin[1]=0;
 }
void BF_cfb64_encrypt (const unsigned char * in, unsigned char * out, long length, const BF_KEY * schedule, unsigned char * ivec, int * num, int enc)
void BF_decrypt (BF_LONG * data, const BF_KEY * key)
Definition at line 149 of file bf_enc.c.
References BF_ENC, BF_LONG, BF_ROUNDS, bf_key_st::P, r, bf_key_st::S, and s.
Referenced by BF_cbc_encrypt().
 {
 #ifndef BF_PTR2
     const BF_LONG *p,*s;
     BF_LONG l,r;
     p=key->P;
     s= &(key->S[0]);
     l=data[0];
     r=data[1];
     l^=p[BF_ROUNDS+1];
 #if BF_ROUNDS == 20
     BF_ENC(r,l,s,p[20]);
     BF_ENC(l,r,s,p[19]);
     BF_ENC(r,l,s,p[18]);
     BF_ENC(l,r,s,p[17]);
 #endif
     BF_ENC(r,l,s,p[16]);
     BF_ENC(l,r,s,p[15]);
     BF_ENC(r,l,s,p[14]);
     BF_ENC(l,r,s,p[13]);
     BF_ENC(r,l,s,p[12]);
     BF_ENC(l,r,s,p[11]);
     BF_ENC(r,l,s,p[10]);
     BF_ENC(l,r,s,p[ 9]);
     BF_ENC(r,l,s,p[ 8]);
     BF_ENC(l,r,s,p[ 7]);
     BF_ENC(r,l,s,p[ 6]);
     BF_ENC(l,r,s,p[ 5]);
     BF_ENC(r,l,s,p[ 4]);
     BF_ENC(l,r,s,p[ 3]);
     BF_ENC(r,l,s,p[ 2]);
     BF_ENC(l,r,s,p[ 1]);
     r^=p[0];
     data[1]=l&0xffffffffL;
     data[0]=r&0xffffffffL;
 #else
     BF_LONG l,r,t,*k;
     l=data[0];
     r=data[1];
     k=(BF_LONG *)key;
     l^=k[BF_ROUNDS+1];
 #if BF_ROUNDS == 20
     BF_ENC(r,l,k,20);
     BF_ENC(l,r,k,19);
     BF_ENC(r,l,k,18);
     BF_ENC(l,r,k,17);
 #endif
     BF_ENC(r,l,k,16);
     BF_ENC(l,r,k,15);
     BF_ENC(r,l,k,14);
     BF_ENC(l,r,k,13);
     BF_ENC(r,l,k,12);
     BF_ENC(l,r,k,11);
     BF_ENC(r,l,k,10);
     BF_ENC(l,r,k, 9);
     BF_ENC(r,l,k, 8);
     BF_ENC(l,r,k, 7);
     BF_ENC(r,l,k, 6);
     BF_ENC(l,r,k, 5);
     BF_ENC(r,l,k, 4);
     BF_ENC(l,r,k, 3);
     BF_ENC(r,l,k, 2);
     BF_ENC(l,r,k, 1);
     r^=k[0];
     data[1]=l&0xffffffffL;
     data[0]=r&0xffffffffL;
 #endif
 }
void BF_ecb_encrypt (const unsigned char * in, unsigned char * out, const BF_KEY * key, int enc)
void BF_encrypt (BF_LONG * data, const BF_KEY * key)
Definition at line 72 of file bf_enc.c.
References BF_ENC, BF_LONG, BF_ROUNDS, bf_key_st::P, r, bf_key_st::S, and s.
Referenced by BF_cbc_encrypt(), and BF_set_key().
 {
 #ifndef BF_PTR2
     const BF_LONG *p,*s;
     BF_LONG l,r;
     p=key->P;
     s= &(key->S[0]);
     l=data[0];
     r=data[1];
     l^=p[0];
     BF_ENC(r,l,s,p[ 1]);
     BF_ENC(l,r,s,p[ 2]);
     BF_ENC(r,l,s,p[ 3]);
     BF_ENC(l,r,s,p[ 4]);
     BF_ENC(r,l,s,p[ 5]);
     BF_ENC(l,r,s,p[ 6]);
     BF_ENC(r,l,s,p[ 7]);
     BF_ENC(l,r,s,p[ 8]);
     BF_ENC(r,l,s,p[ 9]);
     BF_ENC(l,r,s,p[10]);
     BF_ENC(r,l,s,p[11]);
     BF_ENC(l,r,s,p[12]);
     BF_ENC(r,l,s,p[13]);
     BF_ENC(l,r,s,p[14]);
     BF_ENC(r,l,s,p[15]);
     BF_ENC(l,r,s,p[16]);
 #if BF_ROUNDS == 20
     BF_ENC(r,l,s,p[17]);
     BF_ENC(l,r,s,p[18]);
     BF_ENC(r,l,s,p[19]);
     BF_ENC(l,r,s,p[20]);
 #endif
     r^=p[BF_ROUNDS+1];
     data[1]=l&0xffffffffL;
     data[0]=r&0xffffffffL;
 #else
     BF_LONG l,r,t,*k;
     l=data[0];
     r=data[1];
     k=(BF_LONG*)key;
     l^=k[0];
     BF_ENC(r,l,k, 1);
     BF_ENC(l,r,k, 2);
     BF_ENC(r,l,k, 3);
     BF_ENC(l,r,k, 4);
     BF_ENC(r,l,k, 5);
     BF_ENC(l,r,k, 6);
     BF_ENC(r,l,k, 7);
     BF_ENC(l,r,k, 8);
     BF_ENC(r,l,k, 9);
     BF_ENC(l,r,k,10);
     BF_ENC(r,l,k,11);
     BF_ENC(l,r,k,12);
     BF_ENC(r,l,k,13);
     BF_ENC(l,r,k,14);
     BF_ENC(r,l,k,15);
     BF_ENC(l,r,k,16);
 #if BF_ROUNDS == 20
     BF_ENC(r,l,k,17);
     BF_ENC(l,r,k,18);
     BF_ENC(r,l,k,19);
     BF_ENC(l,r,k,20);
 #endif
     r^=k[BF_ROUNDS+1];
     data[1]=l&0xffffffffL;
     data[0]=r&0xffffffffL;
 #endif
 }
void BF_ofb64_encrypt (const unsigned char * in, unsigned char * out, long length, const BF_KEY * schedule, unsigned char * ivec, int * num)
const char* BF_options (void)
void BF_set_key (BF_KEY * key, int len, const unsigned char * data)
Definition at line 71 of file bf_skey.c.
References BF_encrypt(), bf_init, BF_LONG, BF_ROUNDS, data, end, in, len, memcpy, bf_key_st::P, and bf_key_st::S.
Referenced by METHOD().
     {
     int i;
     BF_LONG *p,ri,in[2];
     const unsigned char *d,*end;
     memcpy((char *)key,(const char *)&bf_init,sizeof(BF_KEY));
     p=key->P;
     if (len > ((BF_ROUNDS+2)*4)) len=(BF_ROUNDS+2)*4;
     d=data;
     end= &(data[len]);
     for (i=0; i<(BF_ROUNDS+2); i++)
         {
         ri= *(d++);
         if (d >= end) d=data;
         ri<<=8;
         ri|= *(d++);
         if (d >= end) d=data;
         ri<<=8;
         ri|= *(d++);
         if (d >= end) d=data;
         ri<<=8;
         ri|= *(d++);
         if (d >= end) d=data;
         p[i]^=ri;
         }
     in[0]=0L;
     in[1]=0L;
     for (i=0; i<(BF_ROUNDS+2); i+=2)
         {
         BF_encrypt(in,key);
         p[i  ]=in[0];
         p[i+1]=in[1];
         }
     p=key->S;
     for (i=0; i<4*256; i+=2)
         {
         BF_encrypt(in,key);
         p[i  ]=in[0];
         p[i+1]=in[1];
         }
     }