strongSwan: pkcs1_encoder.c File Reference
pkcs1_encoder.c File Reference
#include "pkcs1_encoder.h"
#include <utils/debug.h>
#include <asn1/asn1.h>
#include <asn1/oid.h>
Functions
static bool build_pub (chunk_t *encoding, va_list args)
static bool build_pub_info (chunk_t *encoding, va_list args)
static bool build_pub_modulus (chunk_t *encoding, va_list args)
static bool build_priv (chunk_t *encoding, va_list args)
static bool hash_pubkey (chunk_t pubkey, chunk_t *hash)
static bool build_info_sha1 (chunk_t *encoding, va_list args)
static bool build_sha1 (chunk_t *encoding, va_list args)
bool pkcs1_encoder_encode (cred_encoding_type_t type, chunk_t *encoding, va_list args)
Function Documentation
static bool build_info_sha1 (chunk_t * encoding, va_list args) static
build the fingerprint of the subjectPublicKeyInfo object
Definition at line 134 of file pkcs1_encoder.c.
References build_pub_info(), FALSE, and hash_pubkey().
Referenced by pkcs1_encoder_encode().
 {
     chunk_t pubkey;
     if (build_pub_info(&pubkey, args))
     {
         return hash_pubkey(pubkey, encoding);
     }
     return FALSE;
 }
static bool build_priv (chunk_t * encoding, va_list args) static
Encode a private key in PKCS#1/ASN.1 DER
Definition at line 85 of file pkcs1_encoder.c.
References asn1_integer(), ASN1_INTEGER_0, ASN1_SEQUENCE, asn1_wrap(), cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_COEFF, CRED_PART_RSA_EXP1, CRED_PART_RSA_EXP2, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PRIME1, CRED_PART_RSA_PRIME2, CRED_PART_RSA_PRIV_EXP, CRED_PART_RSA_PUB_EXP, FALSE, n, q, and TRUE.
Referenced by pkcs1_encoder_encode().
 {
     chunk_t n, e, d, p, q, exp1, exp2, coeff;
     if (cred_encoding_args(args, CRED_PART_RSA_MODULUS, &n,
                     CRED_PART_RSA_PUB_EXP, &e, CRED_PART_RSA_PRIV_EXP, &d,
                     CRED_PART_RSA_PRIME1, &p, CRED_PART_RSA_PRIME2, &q,
                     CRED_PART_RSA_EXP1, &exp1, CRED_PART_RSA_EXP2, &exp2,
                     CRED_PART_RSA_COEFF, &coeff, CRED_PART_END))
     {
         *encoding = asn1_wrap(ASN1_SEQUENCE, "cmmssssss",
                         ASN1_INTEGER_0,
                         asn1_integer("c", n),
                         asn1_integer("c", e),
                         asn1_integer("c", d),
                         asn1_integer("c", p),
                         asn1_integer("c", q),
                         asn1_integer("c", exp1),
                         asn1_integer("c", exp2),
                         asn1_integer("c", coeff));
         return TRUE;
     }
     return FALSE;
 }
static bool build_pub (chunk_t * encoding, va_list args) static
Encode a public key in PKCS#1/ASN.1 DER
Definition at line 25 of file pkcs1_encoder.c.
References asn1_integer(), ASN1_SEQUENCE, asn1_wrap(), cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, FALSE, n, and TRUE.
Referenced by build_sha1(), and pkcs1_encoder_encode().
 {
     chunk_t n, e;
     if (cred_encoding_args(args, CRED_PART_RSA_MODULUS, &n,
                            CRED_PART_RSA_PUB_EXP, &e, CRED_PART_END))
     {
         *encoding = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_integer("c", n),
                         asn1_integer("c", e));
         return TRUE;
     }
     return FALSE;
 }
static bool build_pub_info (chunk_t * encoding, va_list args) static
Encode a public key in PKCS#1/ASN.1 DER, contained in subjectPublicKeyInfo
Definition at line 43 of file pkcs1_encoder.c.
References asn1_algorithmIdentifier(), asn1_bitstring(), asn1_integer(), ASN1_SEQUENCE, asn1_wrap(), cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_MODULUS, CRED_PART_RSA_PUB_EXP, FALSE, n, OID_RSA_ENCRYPTION, and TRUE.
Referenced by build_info_sha1(), and pkcs1_encoder_encode().
 {
     chunk_t n, e;
     if (cred_encoding_args(args, CRED_PART_RSA_MODULUS, &n,
                            CRED_PART_RSA_PUB_EXP, &e, CRED_PART_END))
     {
         *encoding = asn1_wrap(ASN1_SEQUENCE, "mm",
                         asn1_algorithmIdentifier(OID_RSA_ENCRYPTION),
                         asn1_bitstring("m",
                             asn1_wrap(ASN1_SEQUENCE, "mm",
                                 asn1_integer("c", n),
                                 asn1_integer("c", e))));
         return TRUE;
     }
     return FALSE;
 }
static bool build_pub_modulus (chunk_t * encoding, va_list args) static
Encode the RSA modulus of a public key only
Definition at line 64 of file pkcs1_encoder.c.
References chunk_clone, cred_encoding_args(), CRED_PART_END, CRED_PART_RSA_MODULUS, FALSE, chunk_t::len, n, chunk_t::ptr, and TRUE.
Referenced by pkcs1_encoder_encode().
 {
     chunk_t n;
     if (cred_encoding_args(args, CRED_PART_RSA_MODULUS, &n, CRED_PART_END))
     {
         /* remove preceding zero bytes */
         while (n.len > 0 && *n.ptr == 0x00)
         {
             n.ptr++;
             n.len--;
         }
         *encoding = chunk_clone(n);
         return TRUE;
     }
     return FALSE;
 }
static bool build_sha1 (chunk_t * encoding, va_list args) static
build the fingerprint of the subjectPublicKey object
Definition at line 148 of file pkcs1_encoder.c.
References build_pub(), FALSE, and hash_pubkey().
Referenced by pkcs1_encoder_encode().
 {
     chunk_t pubkey;
     if (build_pub(&pubkey, args))
     {
         return hash_pubkey(pubkey, encoding);
     }
     return FALSE;
 }
static bool hash_pubkey (chunk_t pubkey, chunk_t * hash) static
Build the SHA1 hash of pubkey(info) ASN.1 data
Definition at line 113 of file pkcs1_encoder.c.
References hasher_t::allocate_hash, chunk_free(), crypto_factory_t::create_hasher, library_t::crypto, DBG1, DBG_LIB, hasher_t::destroy, DESTROY_IF, FALSE, HASH_SHA1, hasher, lib, and TRUE.
Referenced by build_info_sha1(), and build_sha1().
 {
     hasher_t *hasher;
     hasher = lib->crypto->create_hasher(lib->crypto, HASH_SHA1);
     if (!hasher || !hasher->allocate_hash(hasher, pubkey, hash))
     {
         DESTROY_IF(hasher);
         chunk_free(&pubkey);
         DBG1(DBG_LIB, "SHA1 hash algorithm not supported, "
              "fingerprinting failed");
         return FALSE;
     }
     hasher->destroy(hasher);
     chunk_free(&pubkey);
     return TRUE;
 }