strongSwan: swid_tag_id
swid_tag_id
swid
Classes
struct swid_tag_id_t
Typedefs
typedef struct swid_tag_id_t swid_tag_id_t
Functions
swid_tag_id_t * swid_tag_id_create (chunk_t tag_creator, chunk_t unique_sw_id, chunk_t instance_id)
Detailed Description
Typedef Documentation
typedef struct swid_tag_id_t swid_tag_id_t
Definition at line 26 of file swid_tag_id.h.
Function Documentation
swid_tag_id_t* swid_tag_id_create (chunk_t tag_creator, chunk_t unique_sw_id, chunk_t instance_id)
Creates a swid_tag_id_t object
Parameters
tag_creator Tag Creator
unique_sw_id Unique Software ID
instance_id Tag Identifier Instance ID or empty chunk
See header
Definition at line 90 of file swid_tag_id.c.
References chunk_clone, INIT, and chunk_t::len.
Referenced by collect_tags(), METHOD(), and read_swid_tag_ids().
 {
     private_swid_tag_id_t *this;
     INIT(this,
         .public = {
             .get_tag_creator = _get_tag_creator,
             .get_unique_sw_id = _get_unique_sw_id,
             .get_ref = _get_ref,
             .destroy = _destroy,
         },
         .tag_creator = chunk_clone(tag_creator),
         .unique_sw_id = chunk_clone(unique_sw_id),
         .ref = 1,
     );
     if (instance_id.len > 0)
     {
         this->instance_id = chunk_clone(instance_id);
     }
     return &this->public;
 }