strongSwan: thread_value_t Struct Reference
thread_value_t Struct Reference
thread_value
#include "thread_value.h"
Public Attributes
void(* set)(thread_value_t *this, void *val)
void *(* get)(thread_value_t *this)
void(* destroy)(thread_value_t *this)
Detailed Description
Wrapper for thread-specific values.
Definition at line 31 of file thread_value.h.
Member Data Documentation
void(* thread_value_t::destroy)(thread_value_t *this)
Destroys this thread specific value wrapper. There is no check for non-NULL values which are currently assigned to the calling thread, no destructor is called.
Definition at line 52 of file thread_value.h.
Referenced by arrays_deinit(), destroy(), METHOD(), mysql_database_deinit(), START_TEST(), strerror_deinit(), threading_cleanup(), and threads_deinit().
void*(* thread_value_t::get)(thread_value_t *this)
Get a thread-specific value.
Returns
the value specific to the current thread
Definition at line 45 of file thread_value.h.
Referenced by compare_elements(), enable_thread(), get_strerror_buf(), get_vstr_conf(), getenv_cb(), HOOK(), iterenv_cb(), METHOD(), read_cb(), thread_current(), thread_initialize(), write_cb(), and writef_cb().
void(* thread_value_t::set)(thread_value_t *this, void *val)
Set a thread-specific value.
Parameters
val thread specific value
Definition at line 38 of file thread_value.h.
Referenced by array_sort(), enable_thread(), fast_request_create(), get_strerror_buf(), get_vstr_conf(), id_function(), METHOD(), thread_current(), thread_initialize(), thread_main(), threads_init(), tls_cleanup_run(), and tls_run().
The documentation for this struct was generated from the following file:
thread_value.h