strongSwan: xauth_manager_t Struct Reference
xauth_manager_t Struct Reference
xauth_manager
#include "xauth_manager.h"
Public Attributes
void(* add_method)(xauth_manager_t *this, char *name, xauth_role_t role, xauth_constructor_t constructor)
void(* remove_method)(xauth_manager_t *this, xauth_constructor_t constructor)
xauth_method_t *(* create_instance)(xauth_manager_t *this, char *name, xauth_role_t role, identification_t *server, identification_t *peer)
void(* destroy)(xauth_manager_t *this)
Detailed Description
The XAuth manager manages all XAuth implementations and creates instances.
A plugin registers it's implemented XAuth method at the manager by providing type and a contructor function. The manager then instanciates xauth_method_t instances through the provided constructor to handle XAuth authentication.
Definition at line 36 of file xauth_manager.h.
Member Data Documentation
void(* xauth_manager_t::add_method)(xauth_manager_t *this, char *name, xauth_role_t role, xauth_constructor_t constructor)
Register a XAuth method implementation.
Parameters
name backend name to register
role XAUTH_SERVER or XAUTH_PEER
constructor constructor function, returns an xauth_method_t
Definition at line 45 of file xauth_manager.h.
Referenced by xauth_method_register().
xauth_method_t*(* xauth_manager_t::create_instance)(xauth_manager_t *this, char *name, xauth_role_t role, identification_t *server, identification_t *peer)
Create a new XAuth method instance.
The name may contain an option string, separated by a colon. This option string gets passed to the XAuth constructor to specify the behavior of the XAuth method.
Parameters
name backend name, with optional config string
role XAUTH_SERVER or XAUTH_PEER
server identity of the server
peer identity of the peer (client)
Returns
XAUTH method instance, NULL if no constructor found
Definition at line 68 of file xauth_manager.h.
Referenced by load_method(), and METHOD().
void(* xauth_manager_t::destroy)(xauth_manager_t *this)
Destroy a eap_manager instance.
Definition at line 75 of file xauth_manager.h.
void(* xauth_manager_t::remove_method)(xauth_manager_t *this, xauth_constructor_t constructor)
Unregister a XAuth method implementation using it's constructor.
Parameters
constructor constructor function, as added in add_method
Definition at line 53 of file xauth_manager.h.
Referenced by xauth_method_register().
The documentation for this struct was generated from the following file:
xauth_manager.h