strongSwan: ietf_attr_remediation_instr
ietf_attr_remediation_instr
ietf_attr
Classes
struct ietf_attr_remediation_instr_t
Typedefs
typedef struct
ietf_attr_remediation_instr_t ietf_attr_remediation_instr_t
typedef enum
ietf_remediation_parameters_t ietf_remediation_parameters_t
Enumerations
enum ietf_remediation_parameters_t { IETF_REMEDIATION_PARAMETERS_URI = 1, IETF_REMEDIATION_PARAMETERS_STRING = 2 }
Functions
pa_tnc_attr_t * ietf_attr_remediation_instr_create (pen_type_t parameters_type, chunk_t parameters)
pa_tnc_attr_t * ietf_attr_remediation_instr_create_from_uri (chunk_t uri)
pa_tnc_attr_t * ietf_attr_remediation_instr_create_from_string (chunk_t string, chunk_t lang_code)
pa_tnc_attr_t * ietf_attr_remediation_instr_create_from_data (size_t length, chunk_t value)
Detailed Description
Typedef Documentation
typedef struct ietf_attr_remediation_instr_t ietf_attr_remediation_instr_t
Definition at line 24 of file ietf_attr_remediation_instr.h.
typedef enum ietf_remediation_parameters_t ietf_remediation_parameters_t
Definition at line 25 of file ietf_attr_remediation_instr.h.
Enumeration Type Documentation
enum ietf_remediation_parameters_t
Enumerator
IETF_REMEDIATION_PARAMETERS_URI
IETF_REMEDIATION_PARAMETERS_STRING
Definition at line 30 of file ietf_attr_remediation_instr.h.
{
     IETF_REMEDIATION_PARAMETERS_URI =    1,
     IETF_REMEDIATION_PARAMETERS_STRING = 2
 };
Function Documentation
pa_tnc_attr_t* ietf_attr_remediation_instr_create (pen_type_t parameters_type, chunk_t parameters)
Creates a general ietf_attr_remediation_instr_t object
Parameters
parameters_type Remediation Parameters Type
parameters Remediation Parameters
Described in header.
Definition at line 280 of file ietf_attr_remediation_instr.c.
References chunk_clone, IETF_ATTR_REMEDIATION_INSTRUCTIONS, INIT, and PEN_IETF.
Referenced by ietf_attr_remediation_instr_create_from_string(), and ietf_attr_remediation_instr_create_from_uri().
 {
     private_ietf_attr_remediation_instr_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_parameters_type = _get_parameters_type,
             .get_parameters = _get_parameters,
             .get_uri = _get_parameters,
             .get_string = _get_string,
         },
         .type = { PEN_IETF, IETF_ATTR_REMEDIATION_INSTRUCTIONS },
         .parameters_type = parameters_type,
         .parameters = chunk_clone(parameters),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ietf_attr_remediation_instr_create_from_data (size_t length, chunk_t data)
Creates an ietf_attr_remediation_instr_t object from received data
Parameters
length Total length of attribute value
value Unparsed attribute value (might be a segment)
Described in header.
Definition at line 348 of file ietf_attr_remediation_instr.c.
References chunk_clone, IETF_ATTR_REMEDIATION_INSTRUCTIONS, INIT, length, and PEN_IETF.
Referenced by ietf_attr_create_from_data().
 {
     private_ietf_attr_remediation_instr_t *this;
     INIT(this,
         .public = {
             .pa_tnc_attribute = {
                 .get_type = _get_type,
                 .get_value = _get_value,
                 .get_noskip_flag = _get_noskip_flag,
                 .set_noskip_flag = _set_noskip_flag,
                 .build = _build,
                 .process = _process,
                 .add_segment = _add_segment,
                 .get_ref = _get_ref,
                 .destroy = _destroy,
             },
             .get_parameters_type = _get_parameters_type,
             .get_parameters = _get_parameters,
             .get_uri = _get_parameters,
             .get_string = _get_string,
         },
         .type = { PEN_IETF, IETF_ATTR_REMEDIATION_INSTRUCTIONS },
         .length = length,
         .value = chunk_clone(data),
         .ref = 1,
     );
     return &this->public.pa_tnc_attribute;
 }
pa_tnc_attr_t* ietf_attr_remediation_instr_create_from_string (chunk_t string, chunk_t lang_code)
Creates an ietf_attr_remediation_instr_t object of Remediation String Type
Parameters
string Remediation String
lang_code Remediation String Language Code
Described in header.
Definition at line 325 of file ietf_attr_remediation_instr.c.
References bio_writer_create(), bio_writer_t::destroy, bio_writer_t::get_buf, ietf_attr_remediation_instr_create(), IETF_REMEDIATION_PARAMETERS_STRING, chunk_t::len, len, min, PEN_IETF, type, bio_writer_t::write_data32, and bio_writer_t::write_data8.
Referenced by METHOD().
 {
     pa_tnc_attr_t *attr;
     bio_writer_t *writer;
     pen_type_t type = { PEN_IETF, IETF_REMEDIATION_PARAMETERS_STRING };
     /* limit language code to 255 octets */
     lang_code.len = min(255, lang_code.len);
     writer = bio_writer_create(4 + string.len + 1 + lang_code.len);
     writer->write_data32(writer, string);
     writer->write_data8 (writer, lang_code);
     attr = ietf_attr_remediation_instr_create(type, writer->get_buf(writer));
     writer->destroy(writer);
     return attr;
 }
pa_tnc_attr_t* ietf_attr_remediation_instr_create_from_uri (chunk_t uri)
Creates an ietf_attr_remediation_instr_t object of Remediation URI Type
Parameters
uri Remediation URI
Described in header.
Definition at line 315 of file ietf_attr_remediation_instr.c.
References ietf_attr_remediation_instr_create(), IETF_REMEDIATION_PARAMETERS_URI, PEN_IETF, and type.
Referenced by METHOD().
 {
     pen_type_t type = { PEN_IETF, IETF_REMEDIATION_PARAMETERS_URI };
     return ietf_attr_remediation_instr_create(type, uri);
 }