strongSwan: x509_ocsp_response.c File Reference
x509_ocsp_response.c File Reference
#include "x509_ocsp_response.h"
#include <time.h>
#include <asn1/oid.h>
#include <asn1/asn1.h>
#include <asn1/asn1_parser.h>
#include <utils/identification.h>
#include <collections/linked_list.h>
#include <utils/debug.h>
#include <library.h>
#include <credentials/certificates/x509.h>
#include <credentials/certificates/crl.h>
Classes
struct private_x509_ocsp_response_t
struct single_response_t
Macros
#define OCSP_DEFAULT_LIFETIME 30
#define OCSP_BASIC_RESPONSE_VERSION 1
#define SINGLE_RESPONSE_ALGORITHM 2
#define SINGLE_RESPONSE_ISSUER_NAME_HASH 3
#define SINGLE_RESPONSE_ISSUER_KEY_HASH 4
#define SINGLE_RESPONSE_SERIAL_NUMBER 5
#define SINGLE_RESPONSE_CERT_STATUS_GOOD 6
#define SINGLE_RESPONSE_CERT_STATUS_REVOKED 8
#define SINGLE_RESPONSE_CERT_STATUS_REVOCATION_TIME 9
#define SINGLE_RESPONSE_CERT_STATUS_CRL_REASON 11
#define SINGLE_RESPONSE_CERT_STATUS_UNKNOWN 14
#define SINGLE_RESPONSE_THIS_UPDATE 16
#define SINGLE_RESPONSE_NEXT_UPDATE 18
#define SINGLE_RESPONSE_EXT_ID 23
#define SINGLE_RESPONSE_CRITICAL 24
#define SINGLE_RESPONSE_EXT_VALUE 25
#define RESPONSES_SINGLE_RESPONSE 1
#define BASIC_RESPONSE_TBS_DATA 1
#define BASIC_RESPONSE_VERSION 3
#define BASIC_RESPONSE_ID_BY_NAME 5
#define BASIC_RESPONSE_ID_BY_KEY 8
#define BASIC_RESPONSE_PRODUCED_AT 10
#define BASIC_RESPONSE_RESPONSES 11
#define BASIC_RESPONSE_EXT_ID 15
#define BASIC_RESPONSE_CRITICAL 16
#define BASIC_RESPONSE_EXT_VALUE 17
#define BASIC_RESPONSE_ALGORITHM 20
#define BASIC_RESPONSE_SIGNATURE 21
#define BASIC_RESPONSE_CERTIFICATE 24
#define OCSP_RESPONSE_STATUS 1
#define OCSP_RESPONSE_TYPE 4
#define OCSP_RESPONSE 5
Typedefs
typedef struct
private_x509_ocsp_response_t private_x509_ocsp_response_t
Functions
METHOD (ocsp_response_t, get_status, cert_validation_t, private_x509_ocsp_response_t *this, x509_t *subject, x509_t *issuer, time_t *revocation_time, crl_reason_t *revocation_reason, time_t *this_update, time_t *next_update)
METHOD (ocsp_response_t, create_cert_enumerator, enumerator_t *, private_x509_ocsp_response_t *this)
static bool parse_singleResponse (private_x509_ocsp_response_t *this, chunk_t blob, int level0)
static bool parse_responses (private_x509_ocsp_response_t *this, chunk_t blob, int level0)
static bool parse_basicOCSPResponse (private_x509_ocsp_response_t *this, chunk_t blob, int level0)
static bool parse_OCSPResponse (private_x509_ocsp_response_t *this)
METHOD (certificate_t, get_type, certificate_type_t, private_x509_ocsp_response_t *this)
METHOD (certificate_t, get_issuer, identification_t *, private_x509_ocsp_response_t *this)
METHOD (certificate_t, has_issuer, id_match_t, private_x509_ocsp_response_t *this, identification_t *issuer)
METHOD (certificate_t, issued_by, bool, private_x509_ocsp_response_t *this, certificate_t *issuer, signature_scheme_t *schemep)
METHOD (certificate_t, get_public_key, public_key_t *, private_x509_ocsp_response_t *this)
METHOD (certificate_t, get_validity, bool, private_x509_ocsp_response_t *this, time_t *when, time_t *not_before, time_t *not_after)
METHOD (certificate_t, get_encoding, bool, private_x509_ocsp_response_t *this, cred_encoding_type_t type, chunk_t *encoding)
METHOD (certificate_t, equals, bool, private_x509_ocsp_response_t *this, certificate_t *other)
METHOD (certificate_t, get_ref, certificate_t *, private_x509_ocsp_response_t *this)
METHOD (certificate_t, destroy, void, private_x509_ocsp_response_t *this)
static x509_ocsp_response_t * load (chunk_t blob)
x509_ocsp_response_t * x509_ocsp_response_load (certificate_type_t type, va_list args)
Variables
static const asn1Object_t singleResponseObjects []
static const asn1Object_t responsesObjects []
static const asn1Object_t basicResponseObjects []
static const asn1Object_t ocspResponseObjects []
Macro Definition Documentation
#define BASIC_RESPONSE_ALGORITHM 20
Definition at line 463 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_CERTIFICATE 24
Definition at line 465 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_CRITICAL 16
Definition at line 461 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_EXT_ID 15
Definition at line 460 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_EXT_VALUE 17
Definition at line 462 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_ID_BY_KEY 8
Definition at line 457 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_ID_BY_NAME 5
Definition at line 456 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_PRODUCED_AT 10
Definition at line 458 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_RESPONSES 11
Definition at line 459 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_SIGNATURE 21
Definition at line 464 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_TBS_DATA 1
Definition at line 454 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define BASIC_RESPONSE_VERSION 3
Definition at line 455 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define OCSP_BASIC_RESPONSE_VERSION 1
Definition at line 135 of file x509_ocsp_response.c.
Referenced by parse_basicOCSPResponse().
#define OCSP_DEFAULT_LIFETIME 30
Copyright (C) 2008-2009 Martin Willi Copyright (C) 2007-2014 Andreas Steffen Hochschule fuer Technik Rapperswil Copyright (C) 2003 Christoph Gysin, Simon Zwahlen
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. See http://www.fsf.org/copyleft/gpl.txt.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. how long do we use an OCSP response without a nextUpdate
Definition at line 36 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define OCSP_RESPONSE 5
Definition at line 586 of file x509_ocsp_response.c.
Referenced by parse_OCSPResponse().
#define OCSP_RESPONSE_STATUS 1
Definition at line 584 of file x509_ocsp_response.c.
Referenced by parse_OCSPResponse().
#define OCSP_RESPONSE_TYPE 4
Definition at line 585 of file x509_ocsp_response.c.
Referenced by parse_OCSPResponse().
#define RESPONSES_SINGLE_RESPONSE 1
Definition at line 381 of file x509_ocsp_response.c.
Referenced by parse_responses().
#define SINGLE_RESPONSE_ALGORITHM 2
Definition at line 265 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_CERT_STATUS_CRL_REASON 11
Definition at line 272 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_CERT_STATUS_GOOD 6
Definition at line 269 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_CERT_STATUS_REVOCATION_TIME 9
Definition at line 271 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_CERT_STATUS_REVOKED 8
Definition at line 270 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_CERT_STATUS_UNKNOWN 14
Definition at line 273 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_CRITICAL 24
Definition at line 277 of file x509_ocsp_response.c.
#define SINGLE_RESPONSE_EXT_ID 23
Definition at line 276 of file x509_ocsp_response.c.
#define SINGLE_RESPONSE_EXT_VALUE 25
Definition at line 278 of file x509_ocsp_response.c.
#define SINGLE_RESPONSE_ISSUER_KEY_HASH 4
Definition at line 267 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_ISSUER_NAME_HASH 3
Definition at line 266 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_NEXT_UPDATE 18
Definition at line 275 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_SERIAL_NUMBER 5
Definition at line 268 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
#define SINGLE_RESPONSE_THIS_UPDATE 16
Definition at line 274 of file x509_ocsp_response.c.
Referenced by parse_singleResponse().
Typedef Documentation
typedef struct private_x509_ocsp_response_t private_x509_ocsp_response_t
Definition at line 43 of file x509_ocsp_response.c.
Function Documentation
static x509_ocsp_response_t* load (chunk_t blob) static
load an OCSP response
Definition at line 808 of file x509_ocsp_response.c.
References chunk_clone, destroy(), INIT, linked_list_create(), OID_UNKNOWN, parse_OCSPResponse(), and UNDEFINED_TIME.
Referenced by METHOD(), and x509_ocsp_response_load().
 {
     private_x509_ocsp_response_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .certificate = {
                     .get_type = _get_type,
                     .get_subject = _get_issuer,
                     .get_issuer = _get_issuer,
                     .has_subject = _has_issuer,
                     .has_issuer = _has_issuer,
                     .issued_by = _issued_by,
                     .get_public_key = _get_public_key,
                     .get_validity = _get_validity,
                     .get_encoding = _get_encoding,
                     .equals = _equals,
                     .get_ref = _get_ref,
                     .destroy = _destroy,
                 },
                 .get_status = _get_status,
                 .create_cert_enumerator = _create_cert_enumerator,
             },
         },
         .ref = 1,
         .encoding = chunk_clone(blob),
         .producedAt = UNDEFINED_TIME,
         .usableUntil = UNDEFINED_TIME,
         .responses = linked_list_create(),
         .signatureAlgorithm = OID_UNKNOWN,
         .certs = linked_list_create(),
     );
     if (!parse_OCSPResponse(this))
     {
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
METHOD (ocsp_response_t , get_status , cert_validation_t , private_x509_ocsp_response_t * this, x509_t * subject, x509_t * issuer, time_t * revocation_time, crl_reason_t * revocation_reason, time_t * this_update, time_t * next_update)
Definition at line 137 of file x509_ocsp_response.c.
References hasher_t::allocate_hash, chunk_equals(), crypto_factory_t::create_hasher, library_t::crypto, enumerator_t::destroy, hasher_t::destroy, DESTROY_IF, enumerator_t::enumerate, fingerprint, free(), identification_t::get_encoding, certificate_t::get_public_key, x509_t::get_serial, certificate_t::get_subject, hash, single_response_t::hashAlgorithm, hasher, hasher_algorithm_from_oid(), id, x509_t::interface, single_response_t::issuerKeyHash, single_response_t::issuerNameHash, KEYID_PUBKEY_SHA1, lib, single_response_t::nextUpdate, OID_SHA1, chunk_t::ptr, public, response, single_response_t::revocationReason, single_response_t::revocationTime, single_response_t::serialNumber, status, single_response_t::status, single_response_t::thisUpdate, type, and VALIDATION_FAILED.
 {
     enumerator_t *enumerator;
     single_response_t *response;
     cert_validation_t status = VALIDATION_FAILED;
     certificate_t *issuercert = &issuer->interface;
     enumerator = this->responses->create_enumerator(this->responses);
     while (enumerator->enumerate(enumerator, &response))
     {
         hasher_t *hasher;
         identification_t *id;
         cred_encoding_type_t type;
         chunk_t hash, fingerprint;
         /* check serial first, is cheaper */
         if (!chunk_equals(subject->get_serial(subject), response->serialNumber))
         {
             continue;
         }
         /* check issuerKeyHash if available */
         if (response->issuerKeyHash.ptr)
         {
             public_key_t *public;
             public = issuercert->get_public_key(issuercert);
             if (!public)
             {
                 continue;
             }
             switch (response->hashAlgorithm)
             {
                 case OID_SHA1:
                     type = KEYID_PUBKEY_SHA1;
                     break;
                 default:
                     public->destroy(public);
                     continue;
             }
             if (!public->get_fingerprint(public, type, &fingerprint) ||
                 !chunk_equals(response->issuerKeyHash, fingerprint))
             {
                 public->destroy(public);
                 continue;
             }
             public->destroy(public);
         }
         /* check issuerNameHash, if available */
         else if (response->issuerNameHash.ptr)
         {
             id = issuercert->get_subject(issuercert);
             hasher = lib->crypto->create_hasher(lib->crypto,
                             hasher_algorithm_from_oid(response->hashAlgorithm));
             if (!hasher ||
                 !hasher->allocate_hash(hasher, id->get_encoding(id), &hash))
             {
                 DESTROY_IF(hasher);
                 continue;
             }
             hasher->destroy(hasher);
             if (!chunk_equals(hash, response->issuerNameHash))
             {
                 free(hash.ptr);
                 continue;
             }
             free(hash.ptr);
         }
         else
         {
             continue;
         }
         /* got a match */
         status = response->status;
         *revocation_time = response->revocationTime;
         *revocation_reason = response->revocationReason;
         *this_update = response->thisUpdate;
         *next_update = response->nextUpdate;
         break;
     }
     enumerator->destroy(enumerator);
     return status;
 }
METHOD (ocsp_response_t , create_cert_enumerator , enumerator_t * , private_x509_ocsp_response_t * this)
Definition at line 224 of file x509_ocsp_response.c.
 {
     return this->certs->create_enumerator(this->certs);
 }
METHOD (certificate_t , get_type , certificate_type_t , private_x509_ocsp_response_t * this)
Definition at line 643 of file x509_ocsp_response.c.
References CERT_X509_OCSP_RESPONSE.
 {
     return CERT_X509_OCSP_RESPONSE;
 }
METHOD (certificate_t , get_issuer , identification_t * , private_x509_ocsp_response_t * this)
Definition at line 649 of file x509_ocsp_response.c.
 {
     return this->responderId;
 }
METHOD (certificate_t , has_issuer , id_match_t , private_x509_ocsp_response_t * this, identification_t * issuer)
Definition at line 655 of file x509_ocsp_response.c.
 {
     return this->responderId->matches(this->responderId, issuer);
 }
METHOD (certificate_t , issued_by , bool , private_x509_ocsp_response_t * this, certificate_t * issuer, signature_scheme_t * schemep)
Definition at line 661 of file x509_ocsp_response.c.
References CERT_X509, chunk_equals(), public_key_t::destroy, DESTROY_IF, FALSE, fingerprint, public_key_t::get_fingerprint, x509_t::get_flags, certificate_t::get_public_key, certificate_t::get_subject, certificate_t::get_type, ID_KEY_ID, key, KEYID_PUBKEY_SHA1, scheme, SIGN_UNKNOWN, signature_scheme_from_oid(), valid, public_key_t::verify, X509_CA, and X509_OCSP_SIGNER.
 {
     public_key_t *key;
     signature_scheme_t scheme;
     bool valid;
     x509_t *x509 = (x509_t*)issuer;
     if (issuer->get_type(issuer) != CERT_X509)
     {
         return FALSE;
     }
     if (this->responderId->get_type(this->responderId) == ID_KEY_ID)
     {
         chunk_t fingerprint;
         key = issuer->get_public_key(issuer);
         if (!key ||
             !key->get_fingerprint(key, KEYID_PUBKEY_SHA1, &fingerprint) ||
             !chunk_equals(fingerprint,
                           this->responderId->get_encoding(this->responderId)))
         {
             DESTROY_IF(key);
             return FALSE;
         }
         key->destroy(key);
     }
     else
     {
         if (!this->responderId->equals(this->responderId,
                                        issuer->get_subject(issuer)))
         {
             return FALSE;
         }
     }
     if (!(x509->get_flags(x509) & X509_OCSP_SIGNER) &&
         !(x509->get_flags(x509) & X509_CA))
     {
         return FALSE;
     }
     /* get the public key of the issuer */
     key = issuer->get_public_key(issuer);
     /* determine signature scheme */
     scheme = signature_scheme_from_oid(this->signatureAlgorithm);
     if (scheme == SIGN_UNKNOWN || key == NULL)
     {
         return FALSE;
     }
     valid = key->verify(key, scheme, this->tbsResponseData, this->signature);
     key->destroy(key);
     if (valid && schemep)
     {
         *schemep = scheme;
     }
     return valid;
 }
METHOD (certificate_t , get_public_key , public_key_t * , private_x509_ocsp_response_t * this)
Definition at line 722 of file x509_ocsp_response.c.
 {
     return NULL;
 }
METHOD (certificate_t , get_validity , bool , private_x509_ocsp_response_t * this, time_t * when, time_t * not_before, time_t * not_after)
Definition at line 728 of file x509_ocsp_response.c.
 {
     time_t t = when ? *when : time(NULL);
     if (not_before)
     {
         *not_before = this->producedAt;
     }
     if (not_after)
     {
         *not_after = this->usableUntil;
     }
     return (t < this->usableUntil);
 }
METHOD (certificate_t , get_encoding , bool , private_x509_ocsp_response_t * this, cred_encoding_type_t type, chunk_t * encoding)
Definition at line 745 of file x509_ocsp_response.c.
References CERT_ASN1_DER, chunk_clone, CRED_PART_END, CRED_PART_X509_OCSP_RES_ASN1_DER, cred_encoding_t::encode, library_t::encoding, lib, and TRUE.
 {
     if (type == CERT_ASN1_DER)
     {
         *encoding = chunk_clone(this->encoding);
         return TRUE;
     }
     return lib->encoding->encode(lib->encoding, type, NULL, encoding,
                 CRED_PART_X509_OCSP_RES_ASN1_DER, this->encoding, CRED_PART_END);
 }
METHOD (certificate_t , equals , bool , private_x509_ocsp_response_t * this, certificate_t * other)
Definition at line 758 of file x509_ocsp_response.c.
References CERT_ASN1_DER, CERT_X509_OCSP_RESPONSE, chunk_equals(), encoding, equals(), certificate_t::equals, FALSE, free(), certificate_t::get_encoding, certificate_t::get_type, chunk_t::ptr, and TRUE.
 {
     chunk_t encoding;
     bool equal;
     if (this == (private_x509_ocsp_response_t*)other)
     {
         return TRUE;
     }
     if (other->get_type(other) != CERT_X509_OCSP_RESPONSE)
     {
         return FALSE;
     }
     if (other->equals == (void*)equals)
     {   /* skip allocation if we have the same implementation */
         return chunk_equals(this->encoding, ((private_x509_ocsp_response_t*)other)->encoding);
     }
     if (!other->get_encoding(other, CERT_ASN1_DER, &encoding))
     {
         return FALSE;
     }
     equal = chunk_equals(this->encoding, encoding);
     free(encoding.ptr);
     return equal;
 }
METHOD (certificate_t , get_ref , certificate_t * , private_x509_ocsp_response_t * this)
Definition at line 785 of file x509_ocsp_response.c.
References ref_get().
 {
     ref_get(&this->ref);
     return &this->public.interface.certificate;
 }
METHOD (certificate_t , destroy , void , private_x509_ocsp_response_t * this)
Definition at line 792 of file x509_ocsp_response.c.
References destroy(), DESTROY_IF, encoding, free(), and ref_put().
 {
     if (ref_put(&this->ref))
     {
         this->certs->destroy_offset(this->certs, offsetof(certificate_t, destroy));
         this->responses->destroy_function(this->responses, free);
         DESTROY_IF(this->responderId);
         free(this->encoding.ptr);
         free(this);
     }
 }
static bool parse_basicOCSPResponse (private_x509_ocsp_response_t * this, chunk_t blob, int level0) static
Parse a basicOCSPResponse
Definition at line 470 of file x509_ocsp_response.c.
References ASN1_GENERALIZEDTIME, asn1_known_oid(), asn1_parse_algorithmIdentifier(), asn1_parser_create(), asn1_to_time(), BASIC_RESPONSE_ALGORITHM, BASIC_RESPONSE_CERTIFICATE, BASIC_RESPONSE_CRITICAL, BASIC_RESPONSE_EXT_ID, BASIC_RESPONSE_EXT_VALUE, BASIC_RESPONSE_ID_BY_KEY, BASIC_RESPONSE_ID_BY_NAME, BASIC_RESPONSE_PRODUCED_AT, BASIC_RESPONSE_RESPONSES, BASIC_RESPONSE_SIGNATURE, BASIC_RESPONSE_TBS_DATA, BASIC_RESPONSE_VERSION, BUILD_BLOB_ASN1_DER, BUILD_END, cert, CERT_X509, chunk_empty, chunk_skip(), credential_factory_t::create, CRED_CERTIFICATE, library_t::creds, DBG1, DBG2, DBG_ASN, asn1_parser_t::destroy, end, FALSE, asn1_parser_t::get_level, ID_ANY, ID_DER_ASN1_DN, ID_KEY_ID, identification_create_from_encoding(), asn1_parser_t::iterate, lib, OCSP_BASIC_RESPONSE_VERSION, OID_NONCE, OID_UNKNOWN, parse_responses(), parser, asn1_parser_t::set_top_level, asn1_parser_t::success, and version.
Referenced by parse_OCSPResponse().
 {
     asn1_parser_t *parser;
     chunk_t object;
     chunk_t responses = chunk_empty;
     int objectID;
     int extn_oid = OID_UNKNOWN;
     u_int responses_level = level0;
     certificate_t *cert;
     bool success = FALSE;
     bool critical;
     parser = asn1_parser_create(basicResponseObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case BASIC_RESPONSE_TBS_DATA:
                 this->tbsResponseData = object;
                 break;
             case BASIC_RESPONSE_VERSION:
             {
                 u_int version = (object.len)? (1 + (u_int)*object.ptr) : 1;
                 if (version != OCSP_BASIC_RESPONSE_VERSION)
                 {
                     DBG1(DBG_ASN, "  ocsp ResponseData version %d not "
                          "supported", version);
                     goto end;
                 }
                 break;
             }
             case BASIC_RESPONSE_ID_BY_NAME:
                 this->responderId = identification_create_from_encoding(
                                                     ID_DER_ASN1_DN, object);
                 DBG2(DBG_ASN, "  '%Y'", this->responderId);
                 break;
             case BASIC_RESPONSE_ID_BY_KEY:
                 this->responderId = identification_create_from_encoding(
                                                     ID_KEY_ID, object);
                 DBG2(DBG_ASN, "  '%Y'", this->responderId);
                 break;
             case BASIC_RESPONSE_PRODUCED_AT:
                 this->producedAt = asn1_to_time(&object, ASN1_GENERALIZEDTIME);
                 break;
             case BASIC_RESPONSE_RESPONSES:
                 responses = object;
                 responses_level = parser->get_level(parser)+1;
                 break;
             case BASIC_RESPONSE_EXT_ID:
                 extn_oid = asn1_known_oid(object);
                 break;
             case BASIC_RESPONSE_CRITICAL:
                 critical = object.len && *object.ptr;
                 DBG2(DBG_ASN, "  %s", critical ? "TRUE" : "FALSE");
                 break;
             case BASIC_RESPONSE_EXT_VALUE:
                 if (extn_oid == OID_NONCE)
                 {
                     this->nonce = object;
                 }
                 break;
             case BASIC_RESPONSE_ALGORITHM:
                 this->signatureAlgorithm = asn1_parse_algorithmIdentifier(object,
                                                 parser->get_level(parser)+1, NULL);
                 break;
             case BASIC_RESPONSE_SIGNATURE:
                 this->signature = chunk_skip(object, 1);
                 break;
             case BASIC_RESPONSE_CERTIFICATE:
             {
                 cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,CERT_X509,
                                           BUILD_BLOB_ASN1_DER, object,
                                           BUILD_END);
                 if (cert)
                 {
                     this->certs->insert_last(this->certs, cert);
                 }
                 break;
             }
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     if (success)
     {
         if (!this->responderId)
         {
             this->responderId = identification_create_from_encoding(ID_ANY,
                                     chunk_empty);
         }
         success = parse_responses(this, responses, responses_level);
     }
     return success;
 }
static bool parse_OCSPResponse (private_x509_ocsp_response_t * this) static
Parse OCSPResponse object
Definition at line 591 of file x509_ocsp_response.c.
References asn1_known_oid(), asn1_parser_create(), DBG1, DBG_LIB, asn1_parser_t::destroy, encoding, end, FALSE, asn1_parser_t::get_level, asn1_parser_t::iterate, OCSP_RESPONSE, OCSP_RESPONSE_STATUS, OCSP_RESPONSE_TYPE, ocsp_status_names, OCSP_SUCCESSFUL, OID_BASIC, OID_UNKNOWN, parse_basicOCSPResponse(), parser, status, and asn1_parser_t::success.
Referenced by load().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     int responseType = OID_UNKNOWN;
     bool success = FALSE;
     ocsp_status_t status;
     parser = asn1_parser_create(ocspResponseObjects, this->encoding);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case OCSP_RESPONSE_STATUS:
                 status = (ocsp_status_t)*object.ptr;
                 switch (status)
                 {
                     case OCSP_SUCCESSFUL:
                         break;
                     default:
                         DBG1(DBG_LIB, "  ocsp response status: %N",
                              ocsp_status_names, status);
                         goto end;
                 }
                 break;
             case OCSP_RESPONSE_TYPE:
                 responseType = asn1_known_oid(object);
                 break;
             case OCSP_RESPONSE:
                 switch (responseType)
                 {
                     case OID_BASIC:
                         success = parse_basicOCSPResponse(this, object,
                                                 parser->get_level(parser)+1);
                         break;
                     default:
                         DBG1(DBG_LIB, "  ocsp response type %#B not supported",
                              &object);
                         goto end;
                 }
                 break;
         }
     }
     success &= parser->success(parser);
 end:
     parser->destroy(parser);
     return success;
 }
static bool parse_responses (private_x509_ocsp_response_t * this, chunk_t blob, int level0) static
Parse all responses
Definition at line 386 of file x509_ocsp_response.c.
References asn1_parser_create(), asn1_parser_t::destroy, end, FALSE, asn1_parser_t::get_level, asn1_parser_t::iterate, parse_singleResponse(), parser, RESPONSES_SINGLE_RESPONSE, asn1_parser_t::set_top_level, and asn1_parser_t::success.
Referenced by parse_basicOCSPResponse().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool success = FALSE;
     parser = asn1_parser_create(responsesObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case RESPONSES_SINGLE_RESPONSE:
                 if (!parse_singleResponse(this, object,
                                           parser->get_level(parser)+1))
                 {
                     goto end;
                 }
                 break;
             default:
                 break;
         }
     }
     success = parser->success(parser);
 end:
     parser->destroy(parser);
     return success;
 }
static bool parse_singleResponse (private_x509_ocsp_response_t * this, chunk_t blob, int level0) static
Parse a single OCSP response
Definition at line 283 of file x509_ocsp_response.c.
References ASN1_GENERALIZEDTIME, asn1_parse_algorithmIdentifier(), asn1_parser_create(), asn1_to_time(), chunk_empty, CRL_REASON_UNSPECIFIED, asn1_parser_t::destroy, FALSE, free(), asn1_parser_t::get_level, single_response_t::hashAlgorithm, single_response_t::issuerKeyHash, single_response_t::issuerNameHash, asn1_parser_t::iterate, len, malloc_thing, single_response_t::nextUpdate, OCSP_DEFAULT_LIFETIME, OID_UNKNOWN, parser, response, single_response_t::revocationReason, single_response_t::revocationTime, single_response_t::serialNumber, asn1_parser_t::set_top_level, SINGLE_RESPONSE_ALGORITHM, SINGLE_RESPONSE_CERT_STATUS_CRL_REASON, SINGLE_RESPONSE_CERT_STATUS_GOOD, SINGLE_RESPONSE_CERT_STATUS_REVOCATION_TIME, SINGLE_RESPONSE_CERT_STATUS_REVOKED, SINGLE_RESPONSE_CERT_STATUS_UNKNOWN, SINGLE_RESPONSE_ISSUER_KEY_HASH, SINGLE_RESPONSE_ISSUER_NAME_HASH, SINGLE_RESPONSE_NEXT_UPDATE, SINGLE_RESPONSE_SERIAL_NUMBER, SINGLE_RESPONSE_THIS_UPDATE, single_response_t::status, asn1_parser_t::success, single_response_t::thisUpdate, UNDEFINED_TIME, VALIDATION_FAILED, VALIDATION_GOOD, and VALIDATION_REVOKED.
Referenced by parse_responses().
 {
     asn1_parser_t *parser;
     chunk_t object;
     int objectID;
     bool success = FALSE;
     single_response_t *response;
     response = malloc_thing(single_response_t);
     response->hashAlgorithm = OID_UNKNOWN;
     response->issuerNameHash = chunk_empty;
     response->issuerKeyHash = chunk_empty;
     response->serialNumber = chunk_empty;
     response->status = VALIDATION_FAILED;
     response->revocationTime = 0;
     response->revocationReason = CRL_REASON_UNSPECIFIED;
     response->thisUpdate = UNDEFINED_TIME;
     /* if nextUpdate is missing, we give it a short lifetime */
     response->nextUpdate = this->producedAt + OCSP_DEFAULT_LIFETIME;
     parser = asn1_parser_create(singleResponseObjects, blob);
     parser->set_top_level(parser, level0);
     while (parser->iterate(parser, &objectID, &object))
     {
         switch (objectID)
         {
             case SINGLE_RESPONSE_ALGORITHM:
                 response->hashAlgorithm = asn1_parse_algorithmIdentifier(object,
                                             parser->get_level(parser)+1, NULL);
                 break;
             case SINGLE_RESPONSE_ISSUER_NAME_HASH:
                 response->issuerNameHash = object;
                 break;
             case SINGLE_RESPONSE_ISSUER_KEY_HASH:
                 response->issuerKeyHash = object;
                 break;
             case SINGLE_RESPONSE_SERIAL_NUMBER:
                 response->serialNumber = object;
                 break;
             case SINGLE_RESPONSE_CERT_STATUS_GOOD:
                 response->status = VALIDATION_GOOD;
                 break;
             case SINGLE_RESPONSE_CERT_STATUS_REVOKED:
                 response->status = VALIDATION_REVOKED;
                 break;
             case SINGLE_RESPONSE_CERT_STATUS_REVOCATION_TIME:
                 response->revocationTime = asn1_to_time(&object, ASN1_GENERALIZEDTIME);
                 break;
             case SINGLE_RESPONSE_CERT_STATUS_CRL_REASON:
                 if (object.len == 1)
                 {
                     response->revocationReason = *object.ptr;
                 }
                 break;
             case SINGLE_RESPONSE_CERT_STATUS_UNKNOWN:
                 response->status = VALIDATION_FAILED;
                 break;
             case SINGLE_RESPONSE_THIS_UPDATE:
                 response->thisUpdate = asn1_to_time(&object, ASN1_GENERALIZEDTIME);
                 break;
             case SINGLE_RESPONSE_NEXT_UPDATE:
                 response->nextUpdate = asn1_to_time(&object, ASN1_GENERALIZEDTIME);
                 if (response->nextUpdate > this->usableUntil)
                 {
                     this->usableUntil = response->nextUpdate;
                 }
                 break;
         }
     }
     success = parser->success(parser);
     parser->destroy(parser);
     if (success)
     {
         if (this->usableUntil == UNDEFINED_TIME)
         {
             this->usableUntil = this->producedAt + OCSP_DEFAULT_LIFETIME;
         }
         this->responses->insert_last(this->responses, response);
     }
     else
     {
         free(response);
     }
     return success;
 }
Variable Documentation
const asn1Object_t basicResponseObjects[] static
ASN.1 definition of basicResponse
Definition at line 422 of file x509_ocsp_response.c.
const asn1Object_t ocspResponseObjects[] static
Initial value:
= {
    { 0, "OCSPResponse",            ASN1_SEQUENCE,      ASN1_NONE },
    { 1,   "responseStatus",        ASN1_ENUMERATED,    ASN1_BODY },
    { 1,   "responseBytesContext",  ASN1_CONTEXT_C_0,   ASN1_OPT  },
    { 2,     "responseBytes",       ASN1_SEQUENCE,      ASN1_NONE },
    { 3,       "responseType",      ASN1_OID,           ASN1_BODY },
    { 3,       "response",          ASN1_OCTET_STRING,  ASN1_BODY },
    { 1,   "end opt",               ASN1_EOC,           ASN1_END  },
    { 0, "exit",                    ASN1_EOC,           ASN1_EXIT }
}
ASN.1 definition of ocspResponse
Definition at line 574 of file x509_ocsp_response.c.
const asn1Object_t responsesObjects[] static
Initial value:
= {
    { 0, "responses",           ASN1_SEQUENCE,  ASN1_LOOP },
    { 1,   "singleResponse",    ASN1_EOC,       ASN1_RAW  },
    { 0, "end loop",            ASN1_EOC,       ASN1_END  },
    { 0, "exit",                ASN1_EOC,       ASN1_EXIT }
}
ASN.1 definition of responses
Definition at line 375 of file x509_ocsp_response.c.
const asn1Object_t singleResponseObjects[] static
ASN.1 definition of singleResponse
Definition at line 233 of file x509_ocsp_response.c.