strongSwan: socket_dynamic_socket
socket_dynamic_socket
socket_dynamic
Classes
struct socket_dynamic_socket_t
Typedefs
typedef struct
socket_dynamic_socket_t socket_dynamic_socket_t
Functions
socket_dynamic_socket_t * socket_dynamic_socket_create ()
Detailed Description
Typedef Documentation
typedef struct socket_dynamic_socket_t socket_dynamic_socket_t
Definition at line 24 of file socket_dynamic_socket.h.
Function Documentation
socket_dynamic_socket_t* socket_dynamic_socket_create ()
Create a socket_dynamic_socket instance.
Definition at line 682 of file socket_dynamic_socket.c.
References DBG1, DBG_NET, equals(), free(), settings_t::get_int, hash(), hashtable_create(), INIT, lib, notify(), library_t::ns, PACKET_MAX_DEFAULT, rwlock_create(), RWLOCK_TYPE_DEFAULT, and library_t::settings.
Referenced by METHOD().
 {
     private_socket_dynamic_socket_t *this;
     INIT(this,
         .public = {
             .socket = {
                 .send = _sender,
                 .receive = _receiver,
                 .get_port = _get_port,
                 .supported_families = _supported_families,
                 .destroy = _destroy,
             },
         },
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .max_packet = lib->settings->get_int(lib->settings,
                                 "%s.max_packet", PACKET_MAX_DEFAULT, lib->ns),
     );
     if (pipe(this->notify) != 0)
     {
         DBG1(DBG_NET, "creating notify pipe for dynamic socket failed");
         free(this);
         return NULL;
     }
     this->sockets = hashtable_create((void*)hash, (void*)equals, 8);
     return &this->public;
 }