strongSwan: test_pen.c File Reference
test_pen.c File Reference
#include "test_suite.h"
#include <pen/pen.h>
Functions
START_TEST (test_pen_type_create)
END_TEST START_TEST (test_pen_type_equals)
END_TEST START_TEST (test_pen_type_is)
END_TEST Suite * pen_suite_create ()
Function Documentation
END_TEST Suite* pen_suite_create ()
Definition at line 67 of file test_pen.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("pen");
     tc = tcase_create("create");
     tcase_add_test(tc, test_pen_type_create);
     suite_add_tcase(s, tc);
     tc = tcase_create("equals");
     tcase_add_test(tc, test_pen_type_equals);
     suite_add_tcase(s, tc);
     tc = tcase_create("is");
     tcase_add_test(tc, test_pen_type_is);
     suite_add_tcase(s, tc);
     return s;
 }
START_TEST (test_pen_type_create)
Definition at line 25 of file test_pen.c.
References ck_assert, PEN_ITA, pen_type_create(), pen_type_t::type, and pen_type_t::vendor_id.
 {
     pen_type_t ita_1 = pen_type_create(PEN_ITA, 100);
     ck_assert(ita_1.vendor_id == PEN_ITA);
     ck_assert(ita_1.type == 100);
 }
END_TEST START_TEST (test_pen_type_equals)
Definition at line 38 of file test_pen.c.
References ck_assert, PEN_FHH, PEN_ITA, pen_type_create(), and pen_type_equals().
 {
     pen_type_t ita_1 = pen_type_create(PEN_ITA, 100);
     pen_type_t ita_2 = pen_type_create(PEN_ITA, 200);
     pen_type_t fhh_1 = pen_type_create(PEN_FHH, 100);
     pen_type_t fhh_2 = pen_type_create(PEN_FHH, 200);
     ck_assert( pen_type_equals(ita_1, ita_1));
     ck_assert(!pen_type_equals(ita_1, ita_2));
     ck_assert(!pen_type_equals(ita_1, fhh_1));
     ck_assert(!pen_type_equals(ita_1, fhh_2));
 }
END_TEST START_TEST (test_pen_type_is)
Definition at line 56 of file test_pen.c.
References ck_assert, PEN_FHH, PEN_ITA, pen_type_create(), and pen_type_is().
 {
     pen_type_t ita_1 = pen_type_create(PEN_ITA, 100);
     ck_assert( pen_type_is(ita_1, PEN_ITA, 100));
     ck_assert(!pen_type_is(ita_1, PEN_ITA, 200));
     ck_assert(!pen_type_is(ita_1, PEN_FHH, 100));
     ck_assert(!pen_type_is(ita_1, PEN_FHH, 200));
 }