strongSwan: ipseckey_plugin.c File Reference
ipseckey_plugin.c File Reference
#include "ipseckey_plugin.h"
#include <daemon.h>
#include "ipseckey_cred.h"
Classes
struct private_ipseckey_plugin_t
Typedefs
typedef struct
private_ipseckey_plugin_t private_ipseckey_plugin_t
Functions
METHOD (plugin_t, get_name, char *, private_ipseckey_plugin_t *this)
METHOD (plugin_t, reload, bool, private_ipseckey_plugin_t *this)
static bool plugin_cb (private_ipseckey_plugin_t *this, plugin_feature_t *feature, bool reg, void *cb_data)
METHOD (plugin_t, get_features, int, private_ipseckey_plugin_t *this, plugin_feature_t *features[])
METHOD (plugin_t, destroy, void, private_ipseckey_plugin_t *this)
plugin_t * ipseckey_plugin_create ()
Typedef Documentation
typedef struct private_ipseckey_plugin_t private_ipseckey_plugin_t
Definition at line 22 of file ipseckey_plugin.c.
Function Documentation
plugin_t* ipseckey_plugin_create ()
Definition at line 128 of file ipseckey_plugin.c.
References INIT.
 {
     private_ipseckey_plugin_t *this;
     INIT(this,
         .public = {
             .plugin = {
                 .get_name = _get_name,
                 .get_features = _get_features,
                 .reload = _reload,
                 .destroy = _destroy,
             },
         },
     );
     return &this->public.plugin;
 }
METHOD (plugin_t , get_name , char * , private_ipseckey_plugin_t * this)
Definition at line 46 of file ipseckey_plugin.c.
 {
     return "ipseckey";
 }
METHOD (plugin_t , reload , bool , private_ipseckey_plugin_t * this)
Definition at line 52 of file ipseckey_plugin.c.
References credential_manager_t::add_set, library_t::credmgr, DBG1, DBG_CFG, enabled, FALSE, settings_t::get_bool, lib, library_t::ns, credential_manager_t::remove_set, library_t::settings, and TRUE.
 {
     bool enabled = lib->settings->get_bool(lib->settings,
                                 "%s.plugins.ipseckey.enable", FALSE, lib->ns);
     if (enabled != this->enabled)
     {
         if (enabled)
         {
             lib->credmgr->add_set(lib->credmgr, &this->cred->set);
         }
         else
         {
             lib->credmgr->remove_set(lib->credmgr, &this->cred->set);
         }
         this->enabled = enabled;
     }
     DBG1(DBG_CFG, "ipseckey plugin is %sabled", this->enabled ? "en" : "dis");
     return TRUE;
 }
METHOD (plugin_t , get_features , int , private_ipseckey_plugin_t * this, plugin_feature_t * features[])
Definition at line 105 of file ipseckey_plugin.c.
References CERT_TRUSTED_PUBKEY, countof, KEY_RSA, PLUGIN_CALLBACK, plugin_cb(), PLUGIN_DEPENDS, and PLUGIN_PROVIDE.
 {
     static plugin_feature_t f[] = {
         PLUGIN_CALLBACK((plugin_feature_callback_t)plugin_cb, NULL),
             PLUGIN_PROVIDE(CUSTOM, "ipseckey"),
                 PLUGIN_DEPENDS(RESOLVER),
                 PLUGIN_DEPENDS(PUBKEY, KEY_RSA),
                 PLUGIN_DEPENDS(CERT_ENCODE, CERT_TRUSTED_PUBKEY),
     };
     *features = f;
     return countof(f);
 }
METHOD (plugin_t , destroy , void , private_ipseckey_plugin_t * this)
Definition at line 119 of file ipseckey_plugin.c.
References free().
 {
     free(this);
 }
static bool plugin_cb (private_ipseckey_plugin_t * this, plugin_feature_t * feature, bool reg, void * cb_data) static
Create resolver and register credential set
Definition at line 77 of file ipseckey_plugin.c.
References resolver_manager_t::create, library_t::credmgr, DBG1, DBG_CFG, enabled, FALSE, ipseckey_cred_create(), lib, credential_manager_t::remove_set, res, library_t::resolver, and TRUE.
Referenced by METHOD().
 {
     if (reg)
     {
         resolver_t *res;
         res = lib->resolver->create(lib->resolver);
         if (!res)
         {
             DBG1(DBG_CFG, "failed to create a DNS resolver instance");
             return FALSE;
         }
         this->cred = ipseckey_cred_create(res);
         reload(this);
     }
     else
     {
         if (this->enabled)
         {
             lib->credmgr->remove_set(lib->credmgr, &this->cred->set);
         }
         this->cred->destroy(this->cred);
     }
     return TRUE;
 }