strongSwan: sender
sender
network
Classes
struct sender_t
Typedefs
typedef struct sender_t sender_t
Functions
sender_t * sender_create (void)
Detailed Description
Typedef Documentation
typedef struct sender_t sender_t
Definition at line 26 of file sender.h.
Function Documentation
sender_t* sender_create (void)
Create the sender thread.
The thread will start to work, getting packets from its queue and sends them out.
Returns
created sender object
Definition at line 191 of file sender.c.
References callback_job_create_with_prio(), condvar_create(), CONDVAR_TYPE_DEFAULT, settings_t::get_bool, settings_t::get_int, INIT, JOB_PRIO_CRITICAL, lib, linked_list_create(), mutex_create(), MUTEX_TYPE_DEFAULT, library_t::ns, library_t::processor, processor_t::queue_job, return_false(), send_packets(), library_t::settings, and TRUE.
Referenced by sender_receiver_cb().
 {
     private_sender_t *this;
     INIT(this,
         .public = {
             .send = _send_,
             .send_no_marker = _send_no_marker,
             .flush = _flush,
             .destroy = _destroy,
         },
         .list = linked_list_create(),
         .mutex = mutex_create(MUTEX_TYPE_DEFAULT),
         .got = condvar_create(CONDVAR_TYPE_DEFAULT),
         .sent = condvar_create(CONDVAR_TYPE_DEFAULT),
         .send_delay = lib->settings->get_int(lib->settings,
                                     "%s.send_delay", 0, lib->ns),
         .send_delay_type = lib->settings->get_int(lib->settings,
                                     "%s.send_delay_type", 0, lib->ns),
         .send_delay_request = lib->settings->get_bool(lib->settings,
                                     "%s.send_delay_request", TRUE, lib->ns),
         .send_delay_response = lib->settings->get_bool(lib->settings,
                                     "%s.send_delay_response", TRUE, lib->ns),
     );
     lib->processor->queue_job(lib->processor,
         (job_t*)callback_job_create_with_prio((callback_job_cb_t)send_packets,
             this, NULL, (callback_job_cancel_t)return_false, JOB_PRIO_CRITICAL));
     return &this->public;
 }