strongSwan: eap_ttls
eap_ttls
eap_ttls
Classes
struct eap_ttls_t
Typedefs
typedef struct eap_ttls_t eap_ttls_t
Functions
eap_ttls_t * eap_ttls_create_server (identification_t *server, identification_t *peer)
eap_ttls_t * eap_ttls_create_peer (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_ttls_t eap_ttls_t
Definition at line 24 of file eap_ttls.h.
Function Documentation
eap_ttls_t* eap_ttls_create_peer (identification_t * server, identification_t * peer)
Creates the EAP method EAP-TTLS acting as peer.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_ttls_t object
Definition at line 189 of file eap_ttls.c.
References eap_ttls_create(), eap_ttls_peer_create(), and FALSE.
Referenced by METHOD().
 {
     return eap_ttls_create(server, peer, FALSE,
                            &eap_ttls_peer_create(server, peer)->application);
 }
eap_ttls_t* eap_ttls_create_server (identification_t * server, identification_t * peer)
Creates the EAP method EAP-TTLS acting as server.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_ttls_t object
Definition at line 182 of file eap_ttls.c.
References eap_ttls_create(), eap_ttls_server_create(), and TRUE.
Referenced by METHOD().
 {
     return eap_ttls_create(server, peer, TRUE,
                            &eap_ttls_server_create(server, peer)->application);
 }