strongSwan: tls_cache.c File Reference
tls_cache.c File Reference
#include "tls_cache.h"
#include <utils/debug.h>
#include <collections/linked_list.h>
#include <collections/hashtable.h>
#include <threading/rwlock.h>
Classes
struct private_tls_cache_t
struct entry_t
Typedefs
typedef struct private_tls_cache_t private_tls_cache_t
Functions
static void entry_destroy (entry_t *entry)
static u_int hash (chunk_t *key)
static bool equals (chunk_t *a, chunk_t *b)
METHOD (tls_cache_t, create_, void, private_tls_cache_t *this, chunk_t session, identification_t *id, chunk_t master, tls_cipher_suite_t suite)
METHOD (tls_cache_t, lookup, tls_cipher_suite_t, private_tls_cache_t *this, chunk_t session, identification_t *id, chunk_t *master)
METHOD (tls_cache_t, check, chunk_t, private_tls_cache_t *this, identification_t *id)
METHOD (tls_cache_t, destroy, void, private_tls_cache_t *this)
tls_cache_t * tls_cache_create (u_int max_sessions, u_int max_age)
Typedef Documentation
typedef struct private_tls_cache_t private_tls_cache_t
Definition at line 23 of file tls_cache.c.
Function Documentation
static void entry_destroy (entry_t * entry) static
Destroy an entry
Definition at line 80 of file tls_cache.c.
References chunk_clear(), DESTROY_IF, free(), entry_t::id, entry_t::master, and entry_t::session.
Referenced by METHOD().
 {
     chunk_clear(&entry->session);
     chunk_clear(&entry->master);
     DESTROY_IF(entry->id);
     free(entry);
 }
static bool equals (chunk_t * a, chunk_t * b) static
Hashtable equals function
Definition at line 99 of file tls_cache.c.
References chunk_equals().
Referenced by tls_cache_create().
 {
     return chunk_equals(*a, *b);
 }
static u_int hash (chunk_t * key) static
Hashtable hash function
Definition at line 91 of file tls_cache.c.
References chunk_hash().
Referenced by tls_cache_create().
 {
     return chunk_hash(*key);
 }
METHOD (tls_cache_t , create_ , void , private_tls_cache_t * this, chunk_t session, identification_t * id, chunk_t master, tls_cipher_suite_t suite)
Definition at line 104 of file tls_cache.c.
References chunk_clone, identification_t::clone, DBG2, DBG_TLS, entry_destroy(), linked_list_t::get_count, INIT, linked_list_t::insert_first, list, lock, linked_list_t::remove_last, entry_t::session, SUCCESS, time_monotonic(), and spinlock_t::unlock.
 {
     entry_t *entry;
     INIT(entry,
         .session = chunk_clone(session),
         .master = chunk_clone(master),
         .suite = suite,
         .id = id ? id->clone(id) : NULL,
         .t = time_monotonic(NULL),
     );
     this->lock->write_lock(this->lock);
     this->list->insert_first(this->list, entry);
     this->table->put(this->table, &entry->session, entry);
     if (this->list->get_count(this->list) > this->max_sessions &&
         this->list->remove_last(this->list, (void**)&entry) == SUCCESS)
     {
         DBG2(DBG_TLS, "session limit of %u reached, deleting %#B",
              this->max_sessions, &entry->session);
         this->table->remove(this->table, &entry->session);
         entry_destroy(entry);
     }
     this->lock->unlock(this->lock);
     DBG2(DBG_TLS, "created TLS session %#B, %d sessions",
          &session, this->list->get_count(this->list));
 }
METHOD (tls_cache_t , lookup , tls_cipher_suite_t , private_tls_cache_t * this, chunk_t session, identification_t * id, chunk_t * master)
Definition at line 135 of file tls_cache.c.
References chunk_clone, DBG2, DBG_TLS, identification_t::equals, entry_t::id, lock, entry_t::master, entry_t::suite, entry_t::t, time_monotonic(), and spinlock_t::unlock.
 {
     tls_cipher_suite_t suite = 0;
     entry_t *entry;
     time_t now;
     u_int age;
     now = time_monotonic(NULL);
     this->lock->write_lock(this->lock);
     entry = this->table->get(this->table, &session);
     if (entry)
     {
         age = now - entry->t;
         if (age <= this->max_age)
         {
             if (!id || !entry->id || id->equals(id, entry->id))
             {
                 *master = chunk_clone(entry->master);
                 suite = entry->suite;
             }
         }
         else
         {
             DBG2(DBG_TLS, "TLS session %#B expired: %u seconds", &session, age);
         }
     }
     this->lock->unlock(this->lock);
     if (suite)
     {
         DBG2(DBG_TLS, "resuming TLS session %#B, age %u seconds", &session, age);
     }
     return suite;
 }
METHOD (tls_cache_t , check , chunk_t , private_tls_cache_t * this, identification_t * id)
Definition at line 173 of file tls_cache.c.
References chunk_clone, chunk_empty, linked_list_t::create_enumerator, enumerator_t::destroy, enumerator_t::enumerate, identification_t::equals, entry_t::id, list, lock, entry_t::session, entry_t::t, time_monotonic(), and spinlock_t::unlock.
 {
     chunk_t session = chunk_empty;
     enumerator_t *enumerator;
     entry_t *entry;
     time_t now;
     now = time_monotonic(NULL);
     this->lock->read_lock(this->lock);
     enumerator = this->list->create_enumerator(this->list);
     while (enumerator->enumerate(enumerator, &entry))
     {
         if (entry->t + this->max_age >= now &&
             entry->id && id->equals(id, entry->id))
         {
             session = chunk_clone(entry->session);
             break;
         }
     }
     enumerator->destroy(enumerator);
     this->lock->unlock(this->lock);
     return session;
 }
METHOD (tls_cache_t , destroy , void , private_tls_cache_t * this)
Definition at line 199 of file tls_cache.c.
References spinlock_t::destroy, linked_list_t::destroy, entry_destroy(), free(), list, lock, linked_list_t::remove_last, and SUCCESS.
 {
     entry_t *entry;
     while (this->list->remove_last(this->list, (void**)&entry) == SUCCESS)
     {
         entry_destroy(entry);
     }
     this->list->destroy(this->list);
     this->table->destroy(this->table);
     this->lock->destroy(this->lock);
     free(this);
 }