strongSwan: ike_sa
ike_sa
sa
Classes
struct ike_sa_t
Macros
#define HALF_OPEN_IKE_SA_TIMEOUT 30
#define KEEPALIVE_INTERVAL 20
#define RETRY_INTERVAL 30
#define RETRY_JITTER 20
Typedefs
typedef enum ike_extension_t ike_extension_t
typedef enum ike_condition_t ike_condition_t
typedef enum ike_sa_state_t ike_sa_state_t
typedef enum statistic_t statistic_t
typedef struct ike_sa_t ike_sa_t
Enumerations
enum ike_extension_t {
EXT_NATT = (1<<0), EXT_MOBIKE = (1<<1), EXT_HASH_AND_URL = (1<<2), EXT_MULTIPLE_AUTH = (1<<3),
EXT_STRONGSWAN = (1<<4), EXT_EAP_ONLY_AUTHENTICATION = (1<<5), EXT_MS_WINDOWS = (1<<6), EXT_XAUTH = (1<<7),
EXT_DPD = (1<<8), EXT_CISCO_UNITY = (1<<9), EXT_NATT_DRAFT_02_03 = (1<<10), EXT_IKE_FRAGMENTATION = (1<<11),
EXT_SIGNATURE_AUTH = (1<<12)
}
enum ike_condition_t {
COND_NAT_ANY = (1<<0), COND_NAT_HERE = (1<<1), COND_NAT_THERE = (1<<2), COND_NAT_FAKE = (1<<3),
COND_EAP_AUTHENTICATED = (1<<4), COND_CERTREQ_SEEN = (1<<5), COND_ORIGINAL_INITIATOR = (1<<6), COND_STALE = (1<<7),
COND_INIT_CONTACT_SEEN = (1<<8), COND_XAUTH_AUTHENTICATED = (1<<9), COND_REAUTHENTICATING = (1<<10)
}
enum statistic_t {
STAT_ESTABLISHED = 0, STAT_REKEY, STAT_REAUTH, STAT_DELETE,
STAT_INBOUND, STAT_OUTBOUND, STAT_MAX
}
enum ike_sa_state_t {
IKE_CREATED, IKE_CONNECTING, IKE_ESTABLISHED, IKE_PASSIVE,
IKE_REKEYING, IKE_DELETING, IKE_DESTROYING
}
Functions
ike_sa_t * ike_sa_create (ike_sa_id_t *ike_sa_id, bool initiator, ike_version_t version)
Variables
enum_name_t * ike_sa_state_names
Detailed Description
Macro Definition Documentation
#define HALF_OPEN_IKE_SA_TIMEOUT 30
Timeout in seconds after that a half open IKE_SA gets deleted.
Definition at line 51 of file ike_sa.h.
Referenced by METHOD(), and schedule_timeout().
#define KEEPALIVE_INTERVAL 20
Interval to send keepalives when NATed, in seconds.
Definition at line 56 of file ike_sa.h.
Referenced by ike_sa_create().
#define RETRY_INTERVAL 30
After which time rekeying should be retried if it failed, in seconds.
Definition at line 61 of file ike_sa.h.
Referenced by get_retry_delay(), METHOD(), and schedule_delayed_rekey().
#define RETRY_JITTER 20
Jitter to subtract from RETRY_INTERVAL to randomize rekey retry.
Definition at line 66 of file ike_sa.h.
Referenced by get_retry_delay(), METHOD(), and schedule_delayed_rekey().
Typedef Documentation
typedef enum ike_condition_t ike_condition_t
Definition at line 28 of file ike_sa.h.
typedef enum ike_extension_t ike_extension_t
Definition at line 27 of file ike_sa.h.
typedef enum ike_sa_state_t ike_sa_state_t
Definition at line 29 of file ike_sa.h.
typedef struct ike_sa_t ike_sa_t
Definition at line 31 of file ike_sa.h.
typedef enum statistic_t statistic_t
Definition at line 30 of file ike_sa.h.
Enumeration Type Documentation
enum ike_condition_t
Conditions of an IKE_SA, change during its lifetime
Enumerator
COND_NAT_ANY
Connection is natted (or faked) somewhere
COND_NAT_HERE
we are behind NAT
COND_NAT_THERE
other is behind NAT
COND_NAT_FAKE
Faking NAT to enforce UDP encapsulation
COND_EAP_AUTHENTICATED
peer has been authenticated using EAP at least once
COND_CERTREQ_SEEN
received a certificate request from the peer
COND_ORIGINAL_INITIATOR
Local peer is the "original" IKE initiator. Unaffected from rekeying.
COND_STALE
IKE_SA is stale, the peer is currently unreachable (MOBIKE)
COND_INIT_CONTACT_SEEN
Initial contact received
COND_XAUTH_AUTHENTICATED
Peer has been authenticated using XAuth
COND_REAUTHENTICATING
This IKE_SA is currently being reauthenticated
Definition at line 144 of file ike_sa.h.
                      {
     COND_NAT_ANY = (1<<0),
     COND_NAT_HERE = (1<<1),
     COND_NAT_THERE = (1<<2),
     COND_NAT_FAKE = (1<<3),
     COND_EAP_AUTHENTICATED = (1<<4),
     COND_CERTREQ_SEEN = (1<<5),
     COND_ORIGINAL_INITIATOR = (1<<6),
     COND_STALE = (1<<7),
     COND_INIT_CONTACT_SEEN = (1<<8),
     COND_XAUTH_AUTHENTICATED = (1<<9),
     COND_REAUTHENTICATING = (1<<10),
 };
enum ike_extension_t
Extensions (or optional features) the peer supports
Enumerator
EXT_NATT
peer supports NAT traversal as specified in RFC4306 or RFC3947 including some RFC3947 drafts
EXT_MOBIKE
peer supports MOBIKE (RFC4555)
EXT_HASH_AND_URL
peer supports HTTP cert lookups as specified in RFC4306
EXT_MULTIPLE_AUTH
peer supports multiple authentication exchanges, RFC4739
EXT_STRONGSWAN
peer uses strongSwan, accept private use extensions
EXT_EAP_ONLY_AUTHENTICATION
peer supports EAP-only authentication, draft-eronen-ipsec-ikev2-eap-auth
EXT_MS_WINDOWS
peer is probably a Windows RAS client
EXT_XAUTH
peer supports XAuth authentication, draft-ietf-ipsec-isakmp-xauth-06
EXT_DPD
peer supports DPD detection, RFC 3706 (or IKEv2)
EXT_CISCO_UNITY
peer supports Cisco Unity configuration attributes
EXT_NATT_DRAFT_02_03
peer supports NAT traversal as specified in draft-ietf-ipsec-nat-t-ike-02 .. -03
EXT_IKE_FRAGMENTATION
peer supports proprietary IKEv1 or standardized IKEv2 fragmentation
EXT_SIGNATURE_AUTH
Signature Authentication, RFC 7427
Definition at line 71 of file ike_sa.h.
                      {
     EXT_NATT = (1<<0),
     EXT_MOBIKE = (1<<1),
     EXT_HASH_AND_URL = (1<<2),
     EXT_MULTIPLE_AUTH = (1<<3),
     EXT_STRONGSWAN = (1<<4),
     EXT_EAP_ONLY_AUTHENTICATION = (1<<5),
     EXT_MS_WINDOWS = (1<<6),
     EXT_XAUTH = (1<<7),
     EXT_DPD = (1<<8),
     EXT_CISCO_UNITY = (1<<9),
     EXT_NATT_DRAFT_02_03 = (1<<10),
     EXT_IKE_FRAGMENTATION = (1<<11),
     EXT_SIGNATURE_AUTH = (1<<12),
 };
enum ike_sa_state_t
State of an IKE_SA.
An IKE_SA passes various states in its lifetime. A newly created SA is in the state CREATED.
              +----------------+
                 SA_CREATED
              +----------------+
 on initiate()--->       <----- on IKE_SA_INIT received
                      V
              +----------------+
               SA_CONNECTING
              +----------------+
                         <----- on IKE_AUTH successfully completed
                      V
              +----------------+
               SA_ESTABLISHED -------------------------+ <-- on rekeying
              +----------------+
                                                        V
 on delete()--->         <----- on IKE_SA        +-------------+
                                delete request    SA_REKEYING
                                received         +-------------+
                      V
              +----------------+
                SA_DELETING   <------------------------+ <-- after rekeying
              +----------------+
                         <----- after delete() acknowledged
                     \V/
                      X
                     / \
Enumerator
IKE_CREATED
IKE_SA just got created, but is not initiating nor responding yet.
IKE_CONNECTING
IKE_SA gets initiated actively or passively
IKE_ESTABLISHED
IKE_SA is fully established
IKE_PASSIVE
IKE_SA is managed externally and does not process messages
IKE_REKEYING
IKE_SA rekeying in progress
IKE_DELETING
IKE_SA is in progress of deletion
IKE_DESTROYING
IKE_SA object gets destroyed
Definition at line 259 of file ike_sa.h.
                     {
     IKE_CREATED,
     IKE_CONNECTING,
     IKE_ESTABLISHED,
     IKE_PASSIVE,
     IKE_REKEYING,
     IKE_DELETING,
     IKE_DESTROYING,
 };
enum statistic_t
Timing information and statistics to query from an SA
Enumerator
STAT_ESTABLISHED
Timestamp of SA establishement
STAT_REKEY
Timestamp of scheduled rekeying
STAT_REAUTH
Timestamp of scheduled reauthentication
STAT_DELETE
Timestamp of scheduled delete
STAT_INBOUND
Timestamp of last inbound IKE packet
STAT_OUTBOUND
Timestamp of last outbound IKE packet
STAT_MAX
Definition at line 205 of file ike_sa.h.
                  {
     STAT_ESTABLISHED = 0,
     STAT_REKEY,
     STAT_REAUTH,
     STAT_DELETE,
     STAT_INBOUND,
     STAT_OUTBOUND,
     STAT_MAX
 };
Function Documentation
ike_sa_t* ike_sa_create (ike_sa_id_t * ike_sa_id, bool initiator, ike_version_t version)
Creates an ike_sa_t object with a specific ID and IKE version.
Parameters
ike_sa_id ike_sa_id_t to associate with new IKE_SA/ISAKMP_SA
initiator TRUE to create this IKE_SA as initiator
version IKE version of this SA
Returns
ike_sa_t object
Definition at line 2469 of file ike_sa.c.
References array_create(), auth_cfg_create(), charon, chunk_empty, ike_sa_id_t::clone, DBG1, DBG_IKE, destroy(), EXT_DPD, FALSE, settings_t::get_bool, settings_t::get_int, socket_manager_t::get_port, settings_t::get_time, host_create_any(), ID_ANY, identification_create_from_encoding(), IKE_ANY, IKE_CREATED, IKEV1, IKEV2, INIT, KEEPALIVE_INTERVAL, keymat_create(), lib, library_t::ns, ref_get(), library_t::settings, daemon_t::socket, STAT_INBOUND, STAT_OUTBOUND, task_manager_create(), time_monotonic(), unique_id, and version.
Referenced by METHOD(), and process_ike_add().
 {
     private_ike_sa_t *this;
     static refcount_t unique_id = 0;
     if (version == IKE_ANY)
     {   /* prefer IKEv2 if protocol not specified */
 #ifdef USE_IKEV2
         version = IKEV2;
 #else
         version = IKEV1;
 #endif
     }
     INIT(this,
         .public = {
             .get_version = _get_version,
             .get_state = _get_state,
             .set_state = _set_state,
             .get_name = _get_name,
             .get_statistic = _get_statistic,
             .set_statistic = _set_statistic,
             .process_message = _process_message,
             .initiate = _initiate,
             .retry_initiate = _retry_initiate,
             .get_ike_cfg = _get_ike_cfg,
             .set_ike_cfg = _set_ike_cfg,
             .get_peer_cfg = _get_peer_cfg,
             .set_peer_cfg = _set_peer_cfg,
             .get_auth_cfg = _get_auth_cfg,
             .create_auth_cfg_enumerator = _create_auth_cfg_enumerator,
             .add_auth_cfg = _add_auth_cfg,
             .get_proposal = _get_proposal,
             .set_proposal = _set_proposal,
             .get_id = _get_id,
             .get_my_host = _get_my_host,
             .set_my_host = _set_my_host,
             .get_other_host = _get_other_host,
             .set_other_host = _set_other_host,
             .set_message_id = _set_message_id,
             .float_ports = _float_ports,
             .update_hosts = _update_hosts,
             .get_my_id = _get_my_id,
             .set_my_id = _set_my_id,
             .get_other_id = _get_other_id,
             .set_other_id = _set_other_id,
             .get_other_eap_id = _get_other_eap_id,
             .enable_extension = _enable_extension,
             .supports_extension = _supports_extension,
             .set_condition = _set_condition,
             .has_condition = _has_condition,
             .set_pending_updates = _set_pending_updates,
             .get_pending_updates = _get_pending_updates,
             .create_peer_address_enumerator = _create_peer_address_enumerator,
             .add_peer_address = _add_peer_address,
             .clear_peer_addresses = _clear_peer_addresses,
             .has_mapping_changed = _has_mapping_changed,
             .retransmit = _retransmit,
             .delete = _delete_,
             .destroy = _destroy,
             .send_dpd = _send_dpd,
             .send_keepalive = _send_keepalive,
             .get_keymat = _get_keymat,
             .add_child_sa = _add_child_sa,
             .get_child_sa = _get_child_sa,
             .get_child_count = _get_child_count,
             .create_child_sa_enumerator = _create_child_sa_enumerator,
             .remove_child_sa = _remove_child_sa,
             .rekey_child_sa = _rekey_child_sa,
             .delete_child_sa = _delete_child_sa,
             .destroy_child_sa = _destroy_child_sa,
             .rekey = _rekey,
             .reauth = _reauth,
             .reestablish = _reestablish,
             .set_auth_lifetime = _set_auth_lifetime,
             .roam = _roam,
             .inherit_pre = _inherit_pre,
             .inherit_post = _inherit_post,
             .generate_message = _generate_message,
             .generate_message_fragmented = _generate_message_fragmented,
             .reset = _reset,
             .get_unique_id = _get_unique_id,
             .add_virtual_ip = _add_virtual_ip,
             .clear_virtual_ips = _clear_virtual_ips,
             .create_virtual_ip_enumerator = _create_virtual_ip_enumerator,
             .add_configuration_attribute = _add_configuration_attribute,
             .create_attribute_enumerator = _create_attribute_enumerator,
             .set_kmaddress = _set_kmaddress,
             .create_task_enumerator = _create_task_enumerator,
             .flush_queue = _flush_queue,
             .queue_task = _queue_task,
 #ifdef ME
             .act_as_mediation_server = _act_as_mediation_server,
             .get_server_reflexive_host = _get_server_reflexive_host,
             .set_server_reflexive_host = _set_server_reflexive_host,
             .get_connect_id = _get_connect_id,
             .initiate_mediation = _initiate_mediation,
             .initiate_mediated = _initiate_mediated,
             .relay = _relay,
             .callback = _callback,
             .respond = _respond,
 #endif /* ME */
         },
         .ike_sa_id = ike_sa_id->clone(ike_sa_id),
         .version = version,
         .my_host = host_create_any(AF_INET),
         .other_host = host_create_any(AF_INET),
         .my_id = identification_create_from_encoding(ID_ANY, chunk_empty),
         .other_id = identification_create_from_encoding(ID_ANY, chunk_empty),
         .keymat = keymat_create(version, initiator),
         .state = IKE_CREATED,
         .stats[STAT_INBOUND] = time_monotonic(NULL),
         .stats[STAT_OUTBOUND] = time_monotonic(NULL),
         .my_auth = auth_cfg_create(),
         .other_auth = auth_cfg_create(),
         .my_auths = array_create(0, 0),
         .other_auths = array_create(0, 0),
         .attributes = array_create(sizeof(attribute_entry_t), 0),
         .unique_id = ref_get(&unique_id),
         .keepalive_interval = lib->settings->get_time(lib->settings,
                                 "%s.keep_alive", KEEPALIVE_INTERVAL, lib->ns),
         .retry_initiate_interval = lib->settings->get_time(lib->settings,
                                 "%s.retry_initiate_interval", 0, lib->ns),
         .flush_auth_cfg = lib->settings->get_bool(lib->settings,
                                 "%s.flush_auth_cfg", FALSE, lib->ns),
         .fragment_size = lib->settings->get_int(lib->settings,
                                 "%s.fragment_size", 0, lib->ns),
     );
     if (version == IKEV2)
     {   /* always supported with IKEv2 */
         enable_extension(this, EXT_DPD);
     }
     this->task_manager = task_manager_create(&this->public);
     this->my_host->set_port(this->my_host,
                             charon->socket->get_port(charon->socket, FALSE));
     if (!this->task_manager || !this->keymat)
     {
         DBG1(DBG_IKE, "IKE version %d not supported", this->version);
         destroy(this);
         return NULL;
     }
     return &this->public;
 }
Variable Documentation
enum_name_t* ike_sa_state_names
enum names for ike_sa_state_t.
Referenced by get_retry_delay(), list_ike(), log_ike_sa(), and METHOD().