strongSwan: maemo_service.c File Reference
maemo_service.c File Reference
#include <glib.h>
#include <libosso.h>
#include <sys/stat.h>
#include "maemo_service.h"
#include <daemon.h>
#include <credentials/sets/mem_cred.h>
#include <processing/jobs/callback_job.h>
Classes
struct private_maemo_service_t
Macros
#define OSSO_STATUS_NAME "status"
#define OSSO_STATUS_SERVICE "org.strongswan."OSSO_STATUS_NAME
#define OSSO_STATUS_OBJECT "/org/strongswan/"OSSO_STATUS_NAME
#define OSSO_STATUS_IFACE "org.strongswan."OSSO_STATUS_NAME
#define OSSO_CHARON_NAME "charon"
#define OSSO_CHARON_SERVICE "org.strongswan."OSSO_CHARON_NAME
#define OSSO_CHARON_OBJECT "/org/strongswan/"OSSO_CHARON_NAME
#define OSSO_CHARON_IFACE "org.strongswan."OSSO_CHARON_NAME
#define MAEMO_COMMON_CA_DIR "/etc/certs/common-ca"
#define MAEMO_USER_CA_DIR "/home/user/.maemosec-certs/wifi-ca"
Typedefs
typedef struct
private_maemo_service_t private_maemo_service_t
Enumerations
enum vpn_status_t {
VPN_STATUS_DISCONNECTED, VPN_STATUS_CONNECTING, VPN_STATUS_CONNECTED, VPN_STATUS_AUTH_FAILED,
VPN_STATUS_CONNECTION_FAILED
}
Functions
static gint change_status (private_maemo_service_t *this, int status)
METHOD (listener_t, ike_updown, bool, private_maemo_service_t *this, ike_sa_t *ike_sa, bool up)
METHOD (listener_t, ike_state_change, bool, private_maemo_service_t *this, ike_sa_t *ike_sa, ike_sa_state_t state)
METHOD (listener_t, child_updown, bool, private_maemo_service_t *this, ike_sa_t *ike_sa, child_sa_t *child_sa, bool up)
METHOD (listener_t, ike_rekey, bool, private_maemo_service_t *this, ike_sa_t *old, ike_sa_t *new)
static void load_ca_dir (private_maemo_service_t *this, char *dir)
static void disconnect (private_maemo_service_t *this)
static gboolean initiate_connection (private_maemo_service_t *this, GArray *arguments)
static gint dbus_req_handler (const gchar *interface, const gchar *method, GArray *arguments, private_maemo_service_t *this, osso_rpc_t *retval)
static job_requeue_t run (private_maemo_service_t *this)
static bool cancel (private_maemo_service_t *this)
METHOD (maemo_service_t, destroy, void, private_maemo_service_t *this)
maemo_service_t * maemo_service_create ()
Macro Definition Documentation
#define MAEMO_COMMON_CA_DIR "/etc/certs/common-ca"
Definition at line 36 of file maemo_service.c.
Referenced by initiate_connection().
#define MAEMO_USER_CA_DIR "/home/user/.maemosec-certs/wifi-ca"
Definition at line 37 of file maemo_service.c.
Referenced by initiate_connection().
#define OSSO_CHARON_IFACE "org.strongswan."OSSO_CHARON_NAME
Definition at line 34 of file maemo_service.c.
Referenced by maemo_service_create(), and METHOD().
#define OSSO_CHARON_NAME "charon"
Definition at line 31 of file maemo_service.c.
#define OSSO_CHARON_OBJECT "/org/strongswan/"OSSO_CHARON_NAME
Definition at line 33 of file maemo_service.c.
Referenced by maemo_service_create(), and METHOD().
#define OSSO_CHARON_SERVICE "org.strongswan."OSSO_CHARON_NAME
Definition at line 32 of file maemo_service.c.
Referenced by maemo_service_create(), and METHOD().
#define OSSO_STATUS_IFACE "org.strongswan."OSSO_STATUS_NAME
Definition at line 29 of file maemo_service.c.
Referenced by change_status().
#define OSSO_STATUS_NAME "status"
Definition at line 26 of file maemo_service.c.
#define OSSO_STATUS_OBJECT "/org/strongswan/"OSSO_STATUS_NAME
Definition at line 28 of file maemo_service.c.
Referenced by change_status().
#define OSSO_STATUS_SERVICE "org.strongswan."OSSO_STATUS_NAME
Definition at line 27 of file maemo_service.c.
Referenced by change_status().
Typedef Documentation
typedef struct private_maemo_service_t private_maemo_service_t
Definition at line 49 of file maemo_service.c.
Enumeration Type Documentation
enum vpn_status_t
Enumerator
VPN_STATUS_DISCONNECTED
VPN_STATUS_CONNECTING
VPN_STATUS_CONNECTED
VPN_STATUS_AUTH_FAILED
VPN_STATUS_CONNECTION_FAILED
Definition at line 41 of file maemo_service.c.
              {
     VPN_STATUS_DISCONNECTED,
     VPN_STATUS_CONNECTING,
     VPN_STATUS_CONNECTED,
     VPN_STATUS_AUTH_FAILED,
     VPN_STATUS_CONNECTION_FAILED,
 } vpn_status_t;
Function Documentation
static bool cancel (private_maemo_service_t * this) static
Cancel the GLib Main Event Loop
Definition at line 440 of file maemo_service.c.
References TRUE.
Referenced by maemo_service_create().
 {
     if (this->loop)
     {
         if (g_main_loop_is_running(this->loop))
         {
             g_main_loop_quit(this->loop);
         }
         g_main_loop_unref(this->loop);
     }
     return TRUE;
 }
static gint change_status (private_maemo_service_t * this, int status) static
Definition at line 93 of file maemo_service.c.
References context, OSSO_STATUS_IFACE, OSSO_STATUS_OBJECT, OSSO_STATUS_SERVICE, res, and status.
Referenced by METHOD().
 {
     osso_rpc_t retval;
     gint res;
     this->status = status;
     res = osso_rpc_run (this->context, OSSO_STATUS_SERVICE, OSSO_STATUS_OBJECT,
                         OSSO_STATUS_IFACE, "StatusChanged", &retval,
                         DBUS_TYPE_INT32, status,
                         DBUS_TYPE_INVALID);
     return res;
 }
static gint dbus_req_handler (const gchar * interface, const gchar * method, GArray * arguments, private_maemo_service_t * this, osso_rpc_t * retval) static
Callback for libosso dbus wrapper
Definition at line 403 of file maemo_service.c.
References disconnect(), initiate_connection(), and streq().
Referenced by maemo_service_create(), and METHOD().
 {
     if (streq(method, "Start"))
     {   /* void start (void), dummy function to start charon as root */
         return OSSO_OK;
     }
     else if (streq(method, "Connect"))
     {   /* bool connect (name, host, cert, user, pass) */
         retval->value.b = initiate_connection(this, arguments);
         retval->type = DBUS_TYPE_BOOLEAN;
     }
     else if (streq(method, "Disconnect"))
     {   /* void disconnect (void) */
         disconnect(this);
     }
     else
     {
         return OSSO_ERROR;
     }
     return OSSO_OK;
 }
static void disconnect (private_maemo_service_t * this) static
Definition at line 200 of file maemo_service.c.
References daemon_t::bus, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkout_by_name, daemon_t::controller, FALSE, ike_sa_t::get_unique_id, id, daemon_t::ike_sa_manager, bus_t::remove_listener, status, controller_t::terminate_ike, and VPN_STATUS_DISCONNECTED.
Referenced by dbus_req_handler(), and initiate_connection().
 {
     ike_sa_t *ike_sa;
     u_int id;
     if (!this->current)
     {
         return;
     }
     /* avoid status updates, as this is called from the Glib main loop */
     charon->bus->remove_listener(charon->bus, &this->public.listener);
     ike_sa = charon->ike_sa_manager->checkout_by_name(charon->ike_sa_manager,
                                                       this->current, FALSE);
     if (ike_sa)
     {
         id = ike_sa->get_unique_id(ike_sa);
         charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
         charon->controller->terminate_ike(charon->controller, id,
                                           NULL, NULL, 0);
     }
     this->current = (g_free(this->current), NULL);
     this->status = VPN_STATUS_DISCONNECTED;
 }
static gboolean initiate_connection (private_maemo_service_t * this, GArray * arguments) static
Definition at line 226 of file maemo_service.c.
References ACTION_NONE, auth_cfg_t::add, peer_cfg_t::add_auth_cfg, mem_cred_t::add_cert, peer_cfg_t::add_child_cfg, bus_t::add_listener, child_cfg_t::add_proposal, ike_cfg_t::add_proposal, mem_cred_t::add_shared, child_cfg_t::add_traffic_selector, peer_cfg_t::add_virtual_ip, auth_cfg_create(), AUTH_CLASS_EAP, AUTH_CLASS_PUBKEY, AUTH_RULE_AUTH_CLASS, AUTH_RULE_IDENTITY, BUILD_END, BUILD_FROM_FILE, daemon_t::bus, cacert, cert, CERT_SEND_IF_ASKED, CERT_X509, charon, ike_sa_manager_t::checkin, ike_sa_manager_t::checkin_and_destroy, ike_sa_manager_t::checkout_by_config, child_cfg_create(), chunk_clone, chunk_create(), mem_cred_t::clear, credential_factory_t::create, CRED_CERTIFICATE, creds, library_t::creds, DBG1, DBG_CFG, peer_cfg_t::destroy, disconnect(), FALSE, FRAGMENTATION_NO, ike_sa_t::get_peer_cfg, socket_manager_t::get_port, child_cfg_t::get_ref, host_create_from_string(), identification_create_from_string(), ike_cfg_create(), daemon_t::ike_sa_manager, IKEV2, IKEV2_UDP_PORT, ike_sa_t::initiate, lib, lifetime_cfg_t::life, load_ca_dir(), MAEMO_COMMON_CA_DIR, MAEMO_USER_CA_DIR, MODE_TUNNEL, peer_cfg_create(), proposal_create_default(), proposal_create_default_aead(), PROTO_ESP, PROTO_IKE, bus_t::remove_listener, ike_sa_t::set_peer_cfg, SHARED_EAP, shared_key_create(), daemon_t::socket, status, streq(), SUCCESS, lifetime_cfg_t::time, traffic_selector_create_dynamic(), traffic_selector_create_from_string(), TRUE, TS_IPV4_ADDR_RANGE, UNIQUE_REPLACE, VPN_STATUS_CONNECTED, VPN_STATUS_CONNECTING, and VPN_STATUS_CONNECTION_FAILED.
Referenced by dbus_req_handler().
 {
     gint i;
     gchar *hostname = NULL, *cacert = NULL, *username = NULL, *password = NULL;
     identification_t *gateway = NULL, *user = NULL;
     ike_sa_t *ike_sa;
     ike_cfg_t *ike_cfg;
     peer_cfg_t *peer_cfg;
     child_cfg_t *child_cfg;
     traffic_selector_t *ts;
     auth_cfg_t *auth;
     certificate_t *cert;
     lifetime_cfg_t lifetime = {
         .time = {
             .life = 10800, /* 3h */
             .rekey = 10200, /* 2h50min */
             .jitter = 300 /* 5min */
         }
     };
     if (this->status == VPN_STATUS_CONNECTED ||
         this->status == VPN_STATUS_CONNECTING)
     {
         DBG1(DBG_CFG, "currently connected to '%s', disconnecting first",
              this->current);
         disconnect (this);
     }
     if (arguments->len != 5)
     {
         DBG1(DBG_CFG, "wrong number of arguments: %d", arguments->len);
         return FALSE;
     }
     for (i = 0; i < arguments->len; i++)
     {
         osso_rpc_t *arg = &g_array_index(arguments, osso_rpc_t, i);
         if (arg->type != DBUS_TYPE_STRING)
         {
             DBG1(DBG_CFG, "invalid argument [%d]: %d", i, arg->type);
             return FALSE;
         }
         switch (i)
         {
             case 0: /* name */
                 this->current = (g_free(this->current), NULL);
                 this->current = g_strdup(arg->value.s);
                 break;
             case 1: /* hostname */
                 hostname = arg->value.s;
                 break;
             case 2: /* CA certificate path */
                 cacert = arg->value.s;
                 break;
             case 3: /* username */
                 username = arg->value.s;
                 break;
             case 4: /* password */
                 password = arg->value.s;
                 break;
         }
     }
     DBG1(DBG_CFG, "received initiate for connection '%s'", this->current);
     this->creds->clear(this->creds);
     if (cacert && !streq(cacert, ""))
     {
         cert = lib->creds->create(lib->creds, CRED_CERTIFICATE, CERT_X509,
                                   BUILD_FROM_FILE, cacert, BUILD_END);
         if (cert)
         {
             this->creds->add_cert(this->creds, TRUE, cert);
         }
         else
         {
             DBG1(DBG_CFG, "failed to load CA certificate");
         }
         /* if this is a server cert we could use the cert subject as id */
     }
     else
     {
         load_ca_dir(this, MAEMO_COMMON_CA_DIR);
         load_ca_dir(this, MAEMO_USER_CA_DIR);
     }
     gateway = identification_create_from_string(hostname);
     DBG1(DBG_CFG, "using CA certificate, gateway identitiy '%Y'", gateway);
     {
         shared_key_t *shared_key;
         chunk_t secret = chunk_create(password, strlen(password));
         user = identification_create_from_string(username);
         shared_key = shared_key_create(SHARED_EAP, chunk_clone(secret));
         this->creds->add_shared(this->creds, shared_key, user->clone(user),
                                 NULL);
     }
     ike_cfg = ike_cfg_create(IKEV2, TRUE, FALSE, "0.0.0.0",
                              charon->socket->get_port(charon->socket, FALSE),
                              hostname, IKEV2_UDP_PORT, FRAGMENTATION_NO, 0);
     ike_cfg->add_proposal(ike_cfg, proposal_create_default(PROTO_IKE));
     ike_cfg->add_proposal(ike_cfg, proposal_create_default_aead(PROTO_IKE));
     peer_cfg = peer_cfg_create(this->current, ike_cfg,
                                CERT_SEND_IF_ASKED,
                                UNIQUE_REPLACE, 1, /* keyingtries */
                                36000, 0, /* rekey 10h, reauth none */
                                600, 600, /* jitter, over 10min */
                                TRUE, FALSE, TRUE, /* mobike, aggressive, pull */
                                0, 0, /* DPD delay, timeout */
                                FALSE, NULL, NULL); /* mediation */
     peer_cfg->add_virtual_ip(peer_cfg,  host_create_from_string("0.0.0.0", 0));
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_EAP);
     auth->add(auth, AUTH_RULE_IDENTITY, user);
     peer_cfg->add_auth_cfg(peer_cfg, auth, TRUE);
     auth = auth_cfg_create();
     auth->add(auth, AUTH_RULE_AUTH_CLASS, AUTH_CLASS_PUBKEY);
     auth->add(auth, AUTH_RULE_IDENTITY, gateway);
     peer_cfg->add_auth_cfg(peer_cfg, auth, FALSE);
     child_cfg = child_cfg_create(this->current, &lifetime, NULL /* updown */,
                                  TRUE, MODE_TUNNEL, ACTION_NONE, ACTION_NONE,
                                  ACTION_NONE, FALSE, 0, 0, NULL, NULL, 0);
     child_cfg->add_proposal(child_cfg, proposal_create_default(PROTO_ESP));
     child_cfg->add_proposal(child_cfg, proposal_create_default_aead(PROTO_ESP));
     ts = traffic_selector_create_dynamic(0, 0, 65535);
     child_cfg->add_traffic_selector(child_cfg, TRUE, ts);
     ts = traffic_selector_create_from_string(0, TS_IPV4_ADDR_RANGE, "0.0.0.0",
                                              0, "255.255.255.255", 65535);
     child_cfg->add_traffic_selector(child_cfg, FALSE, ts);
     peer_cfg->add_child_cfg(peer_cfg, child_cfg);
     /* get us an IKE_SA */
     ike_sa = charon->ike_sa_manager->checkout_by_config(charon->ike_sa_manager,
                                                         peer_cfg);
     if (!ike_sa)
     {
         peer_cfg->destroy(peer_cfg);
         this->status = VPN_STATUS_CONNECTION_FAILED;
         return FALSE;
     }
     if (!ike_sa->get_peer_cfg(ike_sa))
     {
         ike_sa->set_peer_cfg(ike_sa, peer_cfg);
     }
     peer_cfg->destroy(peer_cfg);
     /* store the IKE_SA, so we can track its progress */
     this->ike_sa = ike_sa;
     this->status = VPN_STATUS_CONNECTING;
     this->public.listener.ike_updown = _ike_updown;
     this->public.listener.ike_state_change = _ike_state_change;
     charon->bus->add_listener(charon->bus, &this->public.listener);
     /* get an additional reference because initiate consumes one */
     child_cfg->get_ref(child_cfg);
     if (ike_sa->initiate(ike_sa, child_cfg, 0, NULL, NULL) != SUCCESS)
     {
         DBG1(DBG_CFG, "failed to initiate tunnel");
         charon->bus->remove_listener(charon->bus, &this->public.listener);
         charon->ike_sa_manager->checkin_and_destroy(charon->ike_sa_manager,
                                                     ike_sa);
         this->status = VPN_STATUS_CONNECTION_FAILED;
         return FALSE;
     }
     charon->ike_sa_manager->checkin(charon->ike_sa_manager, ike_sa);
     return TRUE;
 }
static void load_ca_dir (private_maemo_service_t * this, char * dir) static
load all CA certificates in the given directory
Definition at line 165 of file maemo_service.c.
References mem_cred_t::add_cert, BUILD_END, BUILD_FROM_FILE, cert, CERT_X509, credential_factory_t::create, CRED_CERTIFICATE, creds, library_t::creds, DBG1, DBG2, DBG_CFG, enumerator_create_directory(), certificate_t::get_subject, lib, rel(), and TRUE.
Referenced by initiate_connection(), and METHOD().
 {
     enumerator_t *enumerator;
     char *rel, *abs;
     struct stat st;
     enumerator = enumerator_create_directory(dir);
     if (enumerator)
     {
         while (enumerator->enumerate(enumerator, &rel, &abs, &st))
         {
             if (rel[0] != '.')
             {
                 if (S_ISREG(st.st_mode))
                 {
                     certificate_t *cert;
                     cert = lib->creds->create(lib->creds, CRED_CERTIFICATE,
                                               CERT_X509, BUILD_FROM_FILE, abs,
                                               BUILD_END);
                     if (!cert)
                     {
                         DBG1(DBG_CFG, "loading CA certificate '%s' failed",
                              abs);
                         continue;
                     }
                     DBG2(DBG_CFG, "loaded CA certificate '%Y'",
                          cert->get_subject(cert));
                     this->creds->add_cert(this->creds, TRUE, cert);
                 }
             }
         }
         enumerator->destroy(enumerator);
     }
 }
METHOD (listener_t , ike_updown , bool , private_maemo_service_t * this, ike_sa_t * ike_sa, bool up)
Definition at line 105 of file maemo_service.c.
References change_status(), FALSE, TRUE, and VPN_STATUS_AUTH_FAILED.
 {
     /* this callback is only registered during initiation, so if the IKE_SA
      * goes down we assume an authentication error */
     if (this->ike_sa == ike_sa && !up)
     {
         change_status(this, VPN_STATUS_AUTH_FAILED);
         return FALSE;
     }
     return TRUE;
 }
METHOD (listener_t , ike_state_change , bool , private_maemo_service_t * this, ike_sa_t * ike_sa, ike_sa_state_t state)
Definition at line 118 of file maemo_service.c.
References change_status(), FALSE, IKE_DESTROYING, TRUE, and VPN_STATUS_CONNECTION_FAILED.
 {
     /* this call back is only registered during initiation */
     if (this->ike_sa == ike_sa && state == IKE_DESTROYING)
     {
         change_status(this, VPN_STATUS_CONNECTION_FAILED);
         return FALSE;
     }
     return TRUE;
 }
METHOD (listener_t , child_updown , bool , private_maemo_service_t * this, ike_sa_t * ike_sa, child_sa_t * child_sa, bool up)
Definition at line 130 of file maemo_service.c.
References change_status(), FALSE, TRUE, VPN_STATUS_CONNECTED, and VPN_STATUS_CONNECTION_FAILED.
 {
     if (this->ike_sa == ike_sa)
     {
         if (up)
         {
             /* disable hooks registered to catch initiation failures */
             this->public.listener.ike_updown = NULL;
             this->public.listener.ike_state_change = NULL;
             change_status(this, VPN_STATUS_CONNECTED);
         }
         else
         {
             change_status(this, VPN_STATUS_CONNECTION_FAILED);
             return FALSE;
         }
     }
     return TRUE;
 }
METHOD (listener_t , ike_rekey , bool , private_maemo_service_t * this, ike_sa_t * old, ike_sa_t * new)
Definition at line 152 of file maemo_service.c.
References TRUE.
 {
     if (this->ike_sa == old)
     {
         this->ike_sa = new;
     }
     return TRUE;
 }
METHOD (maemo_service_t , destroy , void , private_maemo_service_t * this)
Definition at line 453 of file maemo_service.c.
References daemon_t::bus, charon, context, library_t::credmgr, creds, dbus_req_handler(), mem_cred_t::destroy, free(), lib, OSSO_CHARON_IFACE, OSSO_CHARON_OBJECT, OSSO_CHARON_SERVICE, bus_t::remove_listener, and credential_manager_t::remove_set.
 {
     if (this->context)
     {
         osso_rpc_unset_cb_f(this->context,
                             OSSO_CHARON_SERVICE,
                             OSSO_CHARON_OBJECT,
                             OSSO_CHARON_IFACE,
                             (osso_rpc_cb_f*)dbus_req_handler,
                             this);
         osso_deinitialize(this->context);
     }
     charon->bus->remove_listener(charon->bus, &this->public.listener);
     lib->credmgr->remove_set(lib->credmgr, &this->creds->set);
     this->creds->destroy(this->creds);
     this->current = (g_free(this->current), NULL);
     free(this);
 }
static job_requeue_t run (private_maemo_service_t * this) static
Main loop to handle D-BUS messages.
Definition at line 430 of file maemo_service.c.
References FALSE, and JOB_REQUEUE_NONE.
Referenced by maemo_service_create().
 {
     this->loop = g_main_loop_new(NULL, FALSE);
     g_main_loop_run(this->loop);
     return JOB_REQUEUE_NONE;
 }