strongSwan: imv_attestation_agent
imv_attestation_agent
imv_attestation
Functions
imv_agent_if_t * imv_attestation_agent_create (const char *name, TNC_IMVID id, TNC_Version *actual_version)
Detailed Description
Function Documentation
imv_agent_if_t* imv_attestation_agent_create (const char * name, TNC_IMVID id, TNC_Version * actual_version)
Creates a Attestation IMV agent
Parameters
name Name of the IMV
id ID of the IMV
actual_version TNC IF-IMV version
Described in header.
Definition at line 871 of file imv_attestation_agent.c.
References countof, credential_manager_create(), destroy(), settings_t::get_bool, settings_t::get_str, imcv_db, imv_agent_create, INIT, lib, library_t::ns, pts_creds_create(), pts_database_create(), PTS_DH_GROUP_NONE, pts_dh_group_probe(), pts_dh_group_update(), PTS_MEAS_ALGO_NONE, pts_meas_algo_probe(), pts_meas_algo_update(), library_t::settings, supported_algorithms, supported_dh_groups, and TRUE.
 {
     private_imv_attestation_agent_t *this;
     imv_agent_t *agent;
     char *hash_alg, *dh_group, *cadir;
     bool mandatory_dh_groups;
     agent = imv_agent_create(name, msg_types, countof(msg_types), id,
                              actual_version);
     if (!agent)
     {
         return NULL;
     }
     hash_alg = lib->settings->get_str(lib->settings,
                 "%s.plugins.imv-attestation.hash_algorithm", "sha256", lib->ns);
     dh_group = lib->settings->get_str(lib->settings,
                 "%s.plugins.imv-attestation.dh_group", "ecp256", lib->ns);
     mandatory_dh_groups = lib->settings->get_bool(lib->settings,
                 "%s.plugins.imv-attestation.mandatory_dh_groups", TRUE, lib->ns);
     cadir = lib->settings->get_str(lib->settings,
                 "%s.plugins.imv-attestation.cadir", NULL, lib->ns);
     INIT(this,
         .public = {
             .bind_functions = _bind_functions,
             .notify_connection_change = _notify_connection_change,
             .receive_message = _receive_message,
             .receive_message_long = _receive_message_long,
             .batch_ending = _batch_ending,
             .solicit_recommendation = _solicit_recommendation,
             .destroy = _destroy,
         },
         .agent = agent,
         .supported_algorithms = PTS_MEAS_ALGO_NONE,
         .supported_dh_groups = PTS_DH_GROUP_NONE,
         .pts_credmgr = credential_manager_create(),
         .pts_creds = pts_creds_create(cadir),
         .pts_db = pts_database_create(imcv_db),
     );
     if (!pts_meas_algo_probe(&this->supported_algorithms) ||
         !pts_dh_group_probe(&this->supported_dh_groups, mandatory_dh_groups) ||
         !pts_meas_algo_update(hash_alg, &this->supported_algorithms) ||
         !pts_dh_group_update(dh_group, &this->supported_dh_groups))
     {
         destroy(this);
         return NULL;
     }
     if (this->pts_creds)
     {
         this->pts_credmgr->add_set(this->pts_credmgr,
                                    this->pts_creds->get_set(this->pts_creds));
     }
     return &this->public;
 }