strongSwan: dhcp_transaction_t Struct Reference
dhcp_transaction_t Struct Reference
dhcp_transaction
#include "dhcp_transaction.h"
Public Attributes
u_int32_t(* get_id)(dhcp_transaction_t *this)
identification_t *(* get_identity)(dhcp_transaction_t *this)
void(* set_address)(dhcp_transaction_t *this, host_t *address)
host_t *(* get_address)(dhcp_transaction_t *this)
void(* set_server)(dhcp_transaction_t *this, host_t *server)
host_t *(* get_server)(dhcp_transaction_t *this)
void(* add_attribute)(dhcp_transaction_t *this, configuration_attribute_type_t type, chunk_t data)
enumerator_t *(* create_attribute_enumerator)(dhcp_transaction_t *this)
void(* destroy)(dhcp_transaction_t *this)
Detailed Description
DHCP transaction class.
Definition at line 33 of file dhcp_transaction.h.
Member Data Documentation
void(* dhcp_transaction_t::add_attribute)(dhcp_transaction_t *this, configuration_attribute_type_t type, chunk_t data)
An an additional attribute to serve to peer.
Parameters
type type of attribute
data attribute data
Definition at line 83 of file dhcp_transaction.h.
Referenced by handle_offer().
enumerator_t*(* dhcp_transaction_t::create_attribute_enumerator)(dhcp_transaction_t *this)
Create an enumerator over added attributes.
Returns
enumerator over (configuration_attribute_t, chunk_t)
Definition at line 91 of file dhcp_transaction.h.
Referenced by METHOD().
void(* dhcp_transaction_t::destroy)(dhcp_transaction_t *this)
Destroy a dhcp_transaction_t.
Definition at line 96 of file dhcp_transaction.h.
Referenced by METHOD().
host_t*(* dhcp_transaction_t::get_address)(dhcp_transaction_t *this)
Get the DHCP address received using this transaction.
Returns
received DHCP address
Definition at line 61 of file dhcp_transaction.h.
Referenced by hash_transaction(), METHOD(), and request().
u_int32_t(* dhcp_transaction_t::get_id)(dhcp_transaction_t *this)
Get the DCHP transaction ID.
Returns
DHCP transaction identifier
Definition at line 40 of file dhcp_transaction.h.
Referenced by handle_ack(), handle_offer(), and prepare_dhcp().
identification_t*(* dhcp_transaction_t::get_identity)(dhcp_transaction_t *this)
Get the peer identity this transaction is used for.
Returns
peer Identity
Definition at line 47 of file dhcp_transaction.h.
Referenced by hash_transaction(), and prepare_dhcp().
host_t*(* dhcp_transaction_t::get_server)(dhcp_transaction_t *this)
Get the DHCP server address.
Returns
DHCP server address
Definition at line 75 of file dhcp_transaction.h.
Referenced by METHOD(), request(), and send_dhcp().
void(* dhcp_transaction_t::set_address)(dhcp_transaction_t *this, host_t *address)
Set the DHCP address received using this transaction.
Parameters
host received DHCP address
Definition at line 54 of file dhcp_transaction.h.
Referenced by handle_offer().
void(* dhcp_transaction_t::set_server)(dhcp_transaction_t *this, host_t *server)
Set the DCHP server address discovered.
Parameters
server DHCP server address
Definition at line 68 of file dhcp_transaction.h.
Referenced by handle_offer().
The documentation for this struct was generated from the following file:
dhcp_transaction.h