strongSwan: iv
iv
crypto
Classes
struct iv_gen_t
Typedefs
typedef struct iv_gen_t iv_gen_t
Functions
iv_gen_t * iv_gen_create_for_alg (encryption_algorithm_t alg)
iv_gen_t * iv_gen_null_create ()
iv_gen_t * iv_gen_rand_create ()
iv_gen_t * iv_gen_seq_create ()
Detailed Description
Typedef Documentation
typedef struct iv_gen_t iv_gen_t
Definition at line 24 of file iv_gen.h.
Function Documentation
iv_gen_t* iv_gen_create_for_alg (encryption_algorithm_t alg)
Select an IV generator for a given encryption algorithm.
Parameters
alg encryption algorithm
Returns
IV generator
See header.
Definition at line 27 of file iv_gen.c.
References ENCR_3DES, ENCR_3IDEA, ENCR_AES_CBC, ENCR_AES_CCM_ICV12, ENCR_AES_CCM_ICV16, ENCR_AES_CCM_ICV8, ENCR_AES_CTR, ENCR_AES_GCM_ICV12, ENCR_AES_GCM_ICV16, ENCR_AES_GCM_ICV8, ENCR_BLOWFISH, ENCR_CAMELLIA_CBC, ENCR_CAMELLIA_CCM_ICV12, ENCR_CAMELLIA_CCM_ICV16, ENCR_CAMELLIA_CCM_ICV8, ENCR_CAMELLIA_CTR, ENCR_CAST, ENCR_CHACHA20_POLY1305, ENCR_DES, ENCR_DES_ECB, ENCR_DES_IV32, ENCR_DES_IV64, ENCR_IDEA, ENCR_NULL, ENCR_NULL_AUTH_AES_GMAC, ENCR_RC2_CBC, ENCR_RC5, ENCR_SERPENT_CBC, ENCR_TWOFISH_CBC, ENCR_UNDEFINED, iv_gen_null_create(), iv_gen_rand_create(), and iv_gen_seq_create().
Referenced by aead_create_from_keys(), create_traditional(), and derive_ike_traditional().
 {
     switch (alg)
     {
         case ENCR_DES:
         case ENCR_3DES:
         case ENCR_RC5:
         case ENCR_IDEA:
         case ENCR_CAST:
         case ENCR_BLOWFISH:
         case ENCR_3IDEA:
         case ENCR_AES_CBC:
         case ENCR_CAMELLIA_CBC:
         case ENCR_SERPENT_CBC:
         case ENCR_TWOFISH_CBC:
         case ENCR_RC2_CBC:
             return iv_gen_rand_create();
         case ENCR_AES_CTR:
         case ENCR_AES_CCM_ICV8:
         case ENCR_AES_CCM_ICV12:
         case ENCR_AES_CCM_ICV16:
         case ENCR_AES_GCM_ICV8:
         case ENCR_AES_GCM_ICV12:
         case ENCR_AES_GCM_ICV16:
         case ENCR_CAMELLIA_CTR:
         case ENCR_CAMELLIA_CCM_ICV8:
         case ENCR_CAMELLIA_CCM_ICV12:
         case ENCR_CAMELLIA_CCM_ICV16:
         case ENCR_CHACHA20_POLY1305:
         case ENCR_NULL_AUTH_AES_GMAC:
             return iv_gen_seq_create();
         case ENCR_NULL:
             return iv_gen_null_create();
         case ENCR_UNDEFINED:
         case ENCR_DES_ECB:
         case ENCR_DES_IV32:
         case ENCR_DES_IV64:
             break;
     }
     return NULL;
 }
iv_gen_t* iv_gen_null_create ()
Create an IV generator that does not actually generate an IV.
Returns
IV generator
Definition at line 50 of file iv_gen_null.c.
References INIT.
Referenced by iv_gen_create_for_alg().
 {
     private_iv_gen_t *this;
     INIT(this,
         .public = {
             .get_iv = _get_iv,
             .allocate_iv = _allocate_iv,
             .destroy = _destroy,
         },
     );
     return &this->public;
 }
iv_gen_t* iv_gen_rand_create ()
Create an IV generator that generates random IVs.
Returns
IV generator
Definition at line 65 of file iv_gen_rand.c.
References crypto_factory_t::create_rng, library_t::crypto, INIT, lib, and RNG_WEAK.
Referenced by iv_gen_create_for_alg(), and tls_aead_create_explicit().
 {
     private_iv_gen_t *this;
     INIT(this,
         .public = {
             .get_iv = _get_iv,
             .allocate_iv = _allocate_iv,
             .destroy = _destroy,
         },
         .rng = lib->crypto->create_rng(lib->crypto, RNG_WEAK),
     );
     return &this->public;
 }
iv_gen_t* iv_gen_seq_create ()
Create an IV generator that generates sequential IVs (counter).
The passed external IV must be larger than the one passed to any previous call.
Returns
IV generator
Definition at line 116 of file iv_gen_seq.c.
References crypto_factory_t::create_rng, library_t::crypto, free(), INIT, lib, malloc(), rng, RNG_STRONG, salt, and SEQ_IV_INIT_STATE.
Referenced by aesni_ccm_create(), aesni_gcm_create(), ccm_aead_create(), chapoly_aead_create(), gcm_aead_create(), iv_gen_create_for_alg(), and START_TEST().
 {
     private_iv_gen_t *this;
     rng_t *rng;
     INIT(this,
         .public = {
             .get_iv = _get_iv,
             .allocate_iv = _allocate_iv,
             .destroy = _destroy,
         },
         .prevl = SEQ_IV_INIT_STATE,
         .prevh = SEQ_IV_INIT_STATE,
     );
     rng = lib->crypto->create_rng(lib->crypto, RNG_STRONG);
     if (rng)
     {
         this->salt = malloc(sizeof(u_int64_t));
         if (!rng->get_bytes(rng, sizeof(u_int64_t), this->salt))
         {
             free(this->salt);
             this->salt = NULL;
         }
         rng->destroy(rng);
     }
     return &this->public;
 }