strongSwan: semaphore.c File Reference
semaphore.c File Reference
#include <library.h>
#include <threading/thread.h>
#include <threading/condvar.h>
#include "semaphore.h"
Classes
struct private_semaphore_t
Typedefs
typedef struct private_semaphore_t private_semaphore_t
Functions
METHOD (semaphore_t, wait_, void, private_semaphore_t *this)
METHOD (semaphore_t, timed_wait_abs, bool, private_semaphore_t *this, timeval_t tv)
METHOD (semaphore_t, timed_wait, bool, private_semaphore_t *this, u_int timeout)
METHOD (semaphore_t, post, void, private_semaphore_t *this)
METHOD (semaphore_t, destroy, void, private_semaphore_t *this)
semaphore_t * semaphore_create (u_int value)
Typedef Documentation
typedef struct private_semaphore_t private_semaphore_t
Definition at line 35 of file semaphore.c.
Function Documentation
METHOD (semaphore_t , wait_ , void , private_semaphore_t * this)
Definition at line 70 of file semaphore.c.
References count, mutex_t::lock, mutex, thread_cleanup_pop(), thread_cleanup_push(), TRUE, and mutex_t::unlock.
 {
 #ifdef HAVE_SEM_TIMEDWAIT
     sem_wait(&this->sem);
 #else /* !HAVE_SEM_TIMEDWAIT */
     this->mutex->lock(this->mutex);
     thread_cleanup_push((void*)this->mutex->unlock, this->mutex);
     while (this->count == 0)
     {
         this->cond->wait(this->cond, this->mutex);
     }
     this->count--;
     thread_cleanup_pop(TRUE);
 #endif /* HAVE_SEM_TIMEDWAIT */
 }
METHOD (semaphore_t , timed_wait_abs , bool , private_semaphore_t * this, timeval_t tv)
Definition at line 87 of file semaphore.c.
References count, FALSE, mutex_t::lock, mutex, thread_cleanup_pop(), thread_cleanup_push(), TRUE, and mutex_t::unlock.
 {
 #ifdef HAVE_SEM_TIMEDWAIT
     timespec_t ts;
     ts.tv_sec = tv.tv_sec;
     ts.tv_nsec = tv.tv_usec * 1000;
     /* there are errors other than ETIMEDOUT possible, but we consider them
      * all as timeout */
     return sem_timedwait(&this->sem, &ts) == -1;
 #else /* !HAVE_SEM_TIMEDWAIT */
     this->mutex->lock(this->mutex);
     thread_cleanup_push((void*)this->mutex->unlock, this->mutex);
     while (this->count == 0)
     {
         if (this->cond->timed_wait_abs(this->cond, this->mutex, tv))
         {
             thread_cleanup_pop(TRUE);
             return TRUE;
         }
     }
     this->count--;
     thread_cleanup_pop(TRUE);
     return FALSE;
 #endif /* HAVE_SEM_TIMEDWAIT */
 }
METHOD (semaphore_t , timed_wait , bool , private_semaphore_t * this, u_int timeout)
Definition at line 116 of file semaphore.c.
References add(), time_monotonic(), and timeradd().
 {
     timeval_t tv, add;
     add.tv_sec = timeout / 1000;
     add.tv_usec = (timeout % 1000) * 1000;
     time_monotonic(&tv);
     timeradd(&tv, &add, &tv);
     return timed_wait_abs(this, tv);
 }
METHOD (semaphore_t , post , void , private_semaphore_t * this)
Definition at line 130 of file semaphore.c.
References count, mutex_t::lock, mutex, and mutex_t::unlock.
 {
 #ifdef HAVE_SEM_TIMEDWAIT
     sem_post(&this->sem);
 #else /* !HAVE_SEM_TIMEDWAIT */
     this->mutex->lock(this->mutex);
     this->count++;
     this->mutex->unlock(this->mutex);
     this->cond->signal(this->cond);
 #endif /* HAVE_SEM_TIMEDWAIT */
 }
METHOD (semaphore_t , destroy , void , private_semaphore_t * this)
Definition at line 143 of file semaphore.c.
References mutex_t::destroy, free(), and mutex.
 {
 #ifdef HAVE_SEM_TIMEDWAIT
     sem_destroy(&this->sem);
 #else /* !HAVE_SEM_TIMEDWAIT */
     this->cond->destroy(this->cond);
     this->mutex->destroy(this->mutex);
 #endif /* HAVE_SEM_TIMEDWAIT */
     free(this);
 }