strongSwan: forecast_forwarder
forecast_forwarder
forecast
Classes
struct forecast_forwarder_t
Typedefs
typedef struct forecast_forwarder_t forecast_forwarder_t
Functions
forecast_forwarder_t * forecast_forwarder_create (forecast_listener_t *listener)
Detailed Description
Typedef Documentation
typedef struct forecast_forwarder_t forecast_forwarder_t
Definition at line 26 of file forecast_forwarder.h.
Function Documentation
forecast_forwarder_t* forecast_forwarder_create (forecast_listener_t * listener)
Create a forecast_forwarder instance.
Parameters
listener listener to check for addresses to forward to
Returns
forwarder instance
See header
Definition at line 439 of file forecast_forwarder.c.
References watcher_t::add, kernel_interface_t::add_listener, DBG1, DBG_NET, destroy(), hydra, INIT, hydra_t::kernel_interface, lib, listener, receive_casts(), setsockopt, setup_interface(), socket, strerror, library_t::watcher, and WATCHER_READ.
Referenced by register_forecast().
 {
     private_forecast_forwarder_t *this;
     int on = 1;
     INIT(this,
         .public = {
             .destroy = _destroy,
         },
         .kernel = {
             .listener = {
                 .roam = _roam,
             },
             .raw = -1,
             .pkt = -1,
             .fc = listener,
         },
     );
     this->kernel.pkt = socket(AF_PACKET, SOCK_DGRAM, htons(ETH_P_IP));
     if (this->kernel.pkt == -1)
     {
         DBG1(DBG_NET, "opening PACKET socket failed: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     this->kernel.raw = socket(AF_INET, SOCK_RAW, IPPROTO_UDP);
     if (this->kernel.raw == -1)
     {
         DBG1(DBG_NET, "opening RAW socket failed: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     if (setsockopt(this->kernel.raw, IPPROTO_IP, IP_HDRINCL,
                    &on, sizeof(on)) == -1)
     {
         DBG1(DBG_NET, "forecast socket HDRINCL failed: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     if (setsockopt(this->kernel.raw, SOL_SOCKET, SO_BROADCAST,
                    &on, sizeof(on)) == -1)
     {
         DBG1(DBG_NET, "forecast socket BROADCAST failed: %s", strerror(errno));
         destroy(this);
         return NULL;
     }
     setup_interface(&this->kernel);
     hydra->kernel_interface->add_listener(hydra->kernel_interface,
                                           &this->kernel.listener);
     lib->watcher->add(lib->watcher, this->kernel.pkt, WATCHER_READ,
                       (watcher_cb_t)receive_casts, this);
     return &this->public;
 }