strongSwan: aesni_ccm.c File Reference
aesni_ccm.c File Reference
#include "aesni_ccm.h"
#include "aesni_key.h"
#include <crypto/iv/iv_gen_seq.h>
#include <tmmintrin.h>
Classes
struct private_aesni_ccm_t
Macros
#define SALT_SIZE 3
#define IV_SIZE 8
#define NONCE_SIZE (SALT_SIZE + IV_SIZE) /* 11 */
#define Q_SIZE (AES_BLOCK_SIZE - NONCE_SIZE - 1) /* 4 */
Typedefs
typedef struct private_aesni_ccm_t private_aesni_ccm_t
typedef void(* aesni_ccm_fn_t)(private_aesni_ccm_t *, size_t, u_char *, u_char *, u_char *, size_t, u_char *, u_char *)
Functions
struct __attribute__ ((packed))
static void build_b0 (private_aesni_ccm_t *this, size_t len, size_t alen, u_char *iv, void *out)
static void build_ctr (private_aesni_ccm_t *this, u_int32_t i, u_char *iv, void *out)
static __m128i icv_header (private_aesni_ccm_t *this, size_t len, u_char *iv, u_int16_t alen, u_char *assoc)
static void crypt_icv (private_aesni_ccm_t *this, u_char *iv, __m128i c, u_char *icv)
static __m128i increment_be (__m128i x)
static __m128i encrypt_ccm_rem (aesni_key_t *key, u_int rem, __m128i state, void *in, void *out, __m128i c)
static __m128i decrypt_ccm_rem (aesni_key_t *key, u_int rem, __m128i state, void *in, void *out, __m128i c)
static void encrypt_ccm128 (private_aesni_ccm_t *this, size_t len, u_char *in, u_char *out, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
static void decrypt_ccm128 (private_aesni_ccm_t *this, size_t len, u_char *in, u_char *out, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
static void encrypt_ccm192 (private_aesni_ccm_t *this, size_t len, u_char *in, u_char *out, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
static void decrypt_ccm192 (private_aesni_ccm_t *this, size_t len, u_char *in, u_char *out, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
static void encrypt_ccm256 (private_aesni_ccm_t *this, size_t len, u_char *in, u_char *out, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
static void decrypt_ccm256 (private_aesni_ccm_t *this, size_t len, u_char *in, u_char *out, u_char *iv, size_t alen, u_char *assoc, u_char *icv)
METHOD (aead_t, encrypt, bool, private_aesni_ccm_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encr)
METHOD (aead_t, decrypt, bool, private_aesni_ccm_t *this, chunk_t encr, chunk_t assoc, chunk_t iv, chunk_t *plain)
METHOD (aead_t, get_block_size, size_t, private_aesni_ccm_t *this)
METHOD (aead_t, get_icv_size, size_t, private_aesni_ccm_t *this)
METHOD (aead_t, get_iv_size, size_t, private_aesni_ccm_t *this)
METHOD (aead_t, get_iv_gen, iv_gen_t *, private_aesni_ccm_t *this)
METHOD (aead_t, get_key_size, size_t, private_aesni_ccm_t *this)
METHOD (aead_t, set_key, bool, private_aesni_ccm_t *this, chunk_t key)
METHOD (aead_t, destroy, void, private_aesni_ccm_t *this)
aesni_ccm_t * aesni_ccm_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Variables
b0_t
ctr_t
Macro Definition Documentation
#define IV_SIZE 8
Definition at line 24 of file aesni_ccm.c.
Referenced by __attribute__(), build_b0(), build_ctr(), and METHOD().
#define NONCE_SIZE (SALT_SIZE + IV_SIZE) /* 11 */
Definition at line 25 of file aesni_ccm.c.
#define Q_SIZE (AES_BLOCK_SIZE - NONCE_SIZE - 1) /* 4 */
Definition at line 26 of file aesni_ccm.c.
Referenced by __attribute__(), build_b0(), and build_ctr().
#define SALT_SIZE 3
Definition at line 23 of file aesni_ccm.c.
Referenced by __attribute__(), aesni_ccm_create(), build_b0(), build_ctr(), and METHOD().
Typedef Documentation
typedef void(* aesni_ccm_fn_t)(private_aesni_ccm_t *, size_t, u_char *, u_char *, u_char *, size_t, u_char *, u_char *)
CCM en/decryption method type
Definition at line 33 of file aesni_ccm.c.
typedef struct private_aesni_ccm_t private_aesni_ccm_t
Definition at line 28 of file aesni_ccm.c.
Function Documentation
static void build_b0 (private_aesni_ccm_t * this, size_t len, size_t alen, u_char * iv, void * out) static
Build the first block B0
Definition at line 126 of file aesni_ccm.c.
References b0_t, htoun32(), IV_SIZE, memcpy, out, Q_SIZE, and SALT_SIZE.
Referenced by icv_header().
 {
     b0_t *block = out;
     block->flags.reserved = 0;
     block->flags.assoc = alen ? 1 : 0;
     block->flags.t_len = (this->icv_size - 2) / 2;
     block->flags.q_len = Q_SIZE - 1;
     memcpy(block->nonce.salt, this->salt, SALT_SIZE);
     memcpy(block->nonce.iv, iv, IV_SIZE);
     htoun32(block->q, len);
 }
static void build_ctr (private_aesni_ccm_t * this, u_int32_t i, u_char * iv, void * out) static
Build a counter block for counter i
Definition at line 143 of file aesni_ccm.c.
References ctr_t, htoun32(), IV_SIZE, memcpy, out, Q_SIZE, and SALT_SIZE.
Referenced by crypt_icv(), decrypt_ccm128(), decrypt_ccm192(), decrypt_ccm256(), encrypt_ccm128(), encrypt_ccm192(), and encrypt_ccm256().
 {
     ctr_t *ctr = out;
     ctr->flags.reserved = 0;
     ctr->flags.zero = 0;
     ctr->flags.q_len = Q_SIZE - 1;
     memcpy(ctr->nonce.salt, this->salt, SALT_SIZE);
     memcpy(ctr->nonce.iv, iv, IV_SIZE);
     htoun32(ctr->i, i);
 }
static void crypt_icv (private_aesni_ccm_t * this, u_char * iv, __m128i c, u_char * icv) static
En-/Decrypt the ICV, trim and store it
Definition at line 218 of file aesni_ccm.c.
References b, build_ctr(), key, and memcpy.
Referenced by decrypt_ccm128(), decrypt_ccm192(), decrypt_ccm256(), encrypt_ccm128(), encrypt_ccm192(), and encrypt_ccm256().
 {
     __m128i *ks, b, t;
     u_int round;
     ks = this->key->schedule;
     build_ctr(this, 0, iv, &b);
     t = _mm_loadu_si128(&b);
     t = _mm_xor_si128(t, ks[0]);
     for (round = 1; round < this->key->rounds; round++)
     {
         t = _mm_aesenc_si128(t, ks[round]);
     }
     t = _mm_aesenclast_si128(t, ks[this->key->rounds]);
     t = _mm_xor_si128(t, c);
     _mm_storeu_si128(&b, t);
     memcpy(icv, &b, this->icv_size);
 }
static void decrypt_ccm128 (private_aesni_ccm_t * this, size_t len, u_char * in, u_char * out, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
AES-128 CCM decryption/ICV generation
Definition at line 394 of file aesni_ccm.c.
References AES_BLOCK_SIZE, b, build_ctr(), c, crypt_icv(), decrypt_ccm_rem(), icv_header(), increment_be(), and key.
Referenced by aesni_ccm_create().
 {
     __m128i *ks, d, t, c, b, state, *bi, *bo;
     u_int blocks, rem, i;
     c = icv_header(this, len, iv, alen, assoc);
     build_ctr(this, 1, iv, &b);
     state = _mm_load_si128(&b);
     blocks = len / AES_BLOCK_SIZE;
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < blocks; i++)
     {
         d = _mm_loadu_si128(bi + i);
         t = _mm_xor_si128(state, ks[0]);
         t = _mm_aesenc_si128(t, ks[1]);
         t = _mm_aesenc_si128(t, ks[2]);
         t = _mm_aesenc_si128(t, ks[3]);
         t = _mm_aesenc_si128(t, ks[4]);
         t = _mm_aesenc_si128(t, ks[5]);
         t = _mm_aesenc_si128(t, ks[6]);
         t = _mm_aesenc_si128(t, ks[7]);
         t = _mm_aesenc_si128(t, ks[8]);
         t = _mm_aesenc_si128(t, ks[9]);
         t = _mm_aesenclast_si128(t, ks[10]);
         t = _mm_xor_si128(t, d);
         _mm_storeu_si128(bo + i, t);
         c = _mm_xor_si128(t, c);
         c = _mm_xor_si128(c, ks[0]);
         c = _mm_aesenc_si128(c, ks[1]);
         c = _mm_aesenc_si128(c, ks[2]);
         c = _mm_aesenc_si128(c, ks[3]);
         c = _mm_aesenc_si128(c, ks[4]);
         c = _mm_aesenc_si128(c, ks[5]);
         c = _mm_aesenc_si128(c, ks[6]);
         c = _mm_aesenc_si128(c, ks[7]);
         c = _mm_aesenc_si128(c, ks[8]);
         c = _mm_aesenc_si128(c, ks[9]);
         c = _mm_aesenclast_si128(c, ks[10]);
         state = increment_be(state);
     }
     if (rem)
     {
         c = decrypt_ccm_rem(this->key, rem, state, bi + blocks, bo + blocks, c);
     }
     crypt_icv(this, iv, c, icv);
 }
static void decrypt_ccm192 (private_aesni_ccm_t * this, size_t len, u_char * in, u_char * out, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
AES-192 CCM decryption/ICV generation
Definition at line 526 of file aesni_ccm.c.
References AES_BLOCK_SIZE, b, build_ctr(), c, crypt_icv(), decrypt_ccm_rem(), icv_header(), increment_be(), and key.
Referenced by aesni_ccm_create().
 {
     __m128i *ks, d, t, c, b, state, *bi, *bo;
     u_int blocks, rem, i;
     c = icv_header(this, len, iv, alen, assoc);
     build_ctr(this, 1, iv, &b);
     state = _mm_load_si128(&b);
     blocks = len / AES_BLOCK_SIZE;
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < blocks; i++)
     {
         d = _mm_loadu_si128(bi + i);
         t = _mm_xor_si128(state, ks[0]);
         t = _mm_aesenc_si128(t, ks[1]);
         t = _mm_aesenc_si128(t, ks[2]);
         t = _mm_aesenc_si128(t, ks[3]);
         t = _mm_aesenc_si128(t, ks[4]);
         t = _mm_aesenc_si128(t, ks[5]);
         t = _mm_aesenc_si128(t, ks[6]);
         t = _mm_aesenc_si128(t, ks[7]);
         t = _mm_aesenc_si128(t, ks[8]);
         t = _mm_aesenc_si128(t, ks[9]);
         t = _mm_aesenc_si128(t, ks[10]);
         t = _mm_aesenc_si128(t, ks[11]);
         t = _mm_aesenclast_si128(t, ks[12]);
         t = _mm_xor_si128(t, d);
         _mm_storeu_si128(bo + i, t);
         c = _mm_xor_si128(t, c);
         c = _mm_xor_si128(c, ks[0]);
         c = _mm_aesenc_si128(c, ks[1]);
         c = _mm_aesenc_si128(c, ks[2]);
         c = _mm_aesenc_si128(c, ks[3]);
         c = _mm_aesenc_si128(c, ks[4]);
         c = _mm_aesenc_si128(c, ks[5]);
         c = _mm_aesenc_si128(c, ks[6]);
         c = _mm_aesenc_si128(c, ks[7]);
         c = _mm_aesenc_si128(c, ks[8]);
         c = _mm_aesenc_si128(c, ks[9]);
         c = _mm_aesenc_si128(c, ks[10]);
         c = _mm_aesenc_si128(c, ks[11]);
         c = _mm_aesenclast_si128(c, ks[12]);
         state = increment_be(state);
     }
     if (rem)
     {
         c = decrypt_ccm_rem(this->key, rem, state, bi + blocks, bo + blocks, c);
     }
     crypt_icv(this, iv, c, icv);
 }
static void decrypt_ccm256 (private_aesni_ccm_t * this, size_t len, u_char * in, u_char * out, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
AES-256 CCM decryption/ICV generation
Definition at line 666 of file aesni_ccm.c.
References AES_BLOCK_SIZE, b, build_ctr(), c, crypt_icv(), decrypt_ccm_rem(), icv_header(), increment_be(), and key.
Referenced by aesni_ccm_create().
 {
     __m128i *ks, d, t, c, b, state, *bi, *bo;
     u_int blocks, rem, i;
     c = icv_header(this, len, iv, alen, assoc);
     build_ctr(this, 1, iv, &b);
     state = _mm_load_si128(&b);
     blocks = len / AES_BLOCK_SIZE;
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < blocks; i++)
     {
         d = _mm_loadu_si128(bi + i);
         t = _mm_xor_si128(state, ks[0]);
         t = _mm_aesenc_si128(t, ks[1]);
         t = _mm_aesenc_si128(t, ks[2]);
         t = _mm_aesenc_si128(t, ks[3]);
         t = _mm_aesenc_si128(t, ks[4]);
         t = _mm_aesenc_si128(t, ks[5]);
         t = _mm_aesenc_si128(t, ks[6]);
         t = _mm_aesenc_si128(t, ks[7]);
         t = _mm_aesenc_si128(t, ks[8]);
         t = _mm_aesenc_si128(t, ks[9]);
         t = _mm_aesenc_si128(t, ks[10]);
         t = _mm_aesenc_si128(t, ks[11]);
         t = _mm_aesenc_si128(t, ks[12]);
         t = _mm_aesenc_si128(t, ks[13]);
         t = _mm_aesenclast_si128(t, ks[14]);
         t = _mm_xor_si128(t, d);
         _mm_storeu_si128(bo + i, t);
         c = _mm_xor_si128(t, c);
         c = _mm_xor_si128(c, ks[0]);
         c = _mm_aesenc_si128(c, ks[1]);
         c = _mm_aesenc_si128(c, ks[2]);
         c = _mm_aesenc_si128(c, ks[3]);
         c = _mm_aesenc_si128(c, ks[4]);
         c = _mm_aesenc_si128(c, ks[5]);
         c = _mm_aesenc_si128(c, ks[6]);
         c = _mm_aesenc_si128(c, ks[7]);
         c = _mm_aesenc_si128(c, ks[8]);
         c = _mm_aesenc_si128(c, ks[9]);
         c = _mm_aesenc_si128(c, ks[10]);
         c = _mm_aesenc_si128(c, ks[11]);
         c = _mm_aesenc_si128(c, ks[12]);
         c = _mm_aesenc_si128(c, ks[13]);
         c = _mm_aesenclast_si128(c, ks[14]);
         state = increment_be(state);
     }
     if (rem)
     {
         c = decrypt_ccm_rem(this->key, rem, state, bi + blocks, bo + blocks, c);
     }
     crypt_icv(this, iv, c, icv);
 }
static __m128i decrypt_ccm_rem (aesni_key_t * key, u_int rem, __m128i state, void * in, void * out, __m128i c) static
Decrypt a remaining incomplete block
Definition at line 293 of file aesni_ccm.c.
References b, c, memcpy, memset, and aesni_key_t::rounds.
Referenced by decrypt_ccm128(), decrypt_ccm192(), and decrypt_ccm256().
 {
     __m128i *ks, t, b, d;
     u_int round;
     ks = key->schedule;
     memset(&b, 0, sizeof(b));
     memcpy(&b, in, rem);
     d = _mm_loadu_si128(&b);
     t = _mm_xor_si128(state, ks[0]);
     for (round = 1; round < key->rounds; round++)
     {
         t = _mm_aesenc_si128(t, ks[round]);
     }
     t = _mm_aesenclast_si128(t, ks[key->rounds]);
     t = _mm_xor_si128(t, d);
     _mm_storeu_si128(&b, t);
     memset((u_char*)&b + rem, 0, sizeof(b) - rem);
     t = _mm_loadu_si128(&b);
     c = _mm_xor_si128(t, c);
     c = _mm_xor_si128(c, ks[0]);
     for (round = 1; round < key->rounds; round++)
     {
         c = _mm_aesenc_si128(c, ks[round]);
     }
     c = _mm_aesenclast_si128(c, ks[key->rounds]);
     memcpy(out, &b, rem);
     return c;
 }
static void encrypt_ccm128 (private_aesni_ccm_t * this, size_t len, u_char * in, u_char * out, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
AES-128 CCM encryption/ICV generation
Definition at line 331 of file aesni_ccm.c.
References AES_BLOCK_SIZE, b, build_ctr(), c, crypt_icv(), encrypt_ccm_rem(), icv_header(), increment_be(), and key.
Referenced by aesni_ccm_create().
 {
     __m128i *ks, d, t, c, b, state, *bi, *bo;
     u_int blocks, rem, i;
     c = icv_header(this, len, iv, alen, assoc);
     build_ctr(this, 1, iv, &b);
     state = _mm_load_si128(&b);
     blocks = len / AES_BLOCK_SIZE;
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < blocks; i++)
     {
         d = _mm_loadu_si128(bi + i);
         c = _mm_xor_si128(d, c);
         c = _mm_xor_si128(c, ks[0]);
         t = _mm_xor_si128(state, ks[0]);
         c = _mm_aesenc_si128(c, ks[1]);
         t = _mm_aesenc_si128(t, ks[1]);
         c = _mm_aesenc_si128(c, ks[2]);
         t = _mm_aesenc_si128(t, ks[2]);
         c = _mm_aesenc_si128(c, ks[3]);
         t = _mm_aesenc_si128(t, ks[3]);
         c = _mm_aesenc_si128(c, ks[4]);
         t = _mm_aesenc_si128(t, ks[4]);
         c = _mm_aesenc_si128(c, ks[5]);
         t = _mm_aesenc_si128(t, ks[5]);
         c = _mm_aesenc_si128(c, ks[6]);
         t = _mm_aesenc_si128(t, ks[6]);
         c = _mm_aesenc_si128(c, ks[7]);
         t = _mm_aesenc_si128(t, ks[7]);
         c = _mm_aesenc_si128(c, ks[8]);
         t = _mm_aesenc_si128(t, ks[8]);
         c = _mm_aesenc_si128(c, ks[9]);
         t = _mm_aesenc_si128(t, ks[9]);
         c = _mm_aesenclast_si128(c, ks[10]);
         t = _mm_aesenclast_si128(t, ks[10]);
         t = _mm_xor_si128(t, d);
         _mm_storeu_si128(bo + i, t);
         state = increment_be(state);
     }
     if (rem)
     {
         c = encrypt_ccm_rem(this->key, rem, state, bi + blocks, bo + blocks, c);
     }
     crypt_icv(this, iv, c, icv);
 }
static void encrypt_ccm192 (private_aesni_ccm_t * this, size_t len, u_char * in, u_char * out, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
AES-192 CCM encryption/ICV generation
Definition at line 459 of file aesni_ccm.c.
References AES_BLOCK_SIZE, b, build_ctr(), c, crypt_icv(), encrypt_ccm_rem(), icv_header(), increment_be(), and key.
Referenced by aesni_ccm_create().
 {
     __m128i *ks, d, t, c, b, state, *bi, *bo;
     u_int blocks, rem, i;
     c = icv_header(this, len, iv, alen, assoc);
     build_ctr(this, 1, iv, &b);
     state = _mm_load_si128(&b);
     blocks = len / AES_BLOCK_SIZE;
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < blocks; i++)
     {
         d = _mm_loadu_si128(bi + i);
         c = _mm_xor_si128(d, c);
         c = _mm_xor_si128(c, ks[0]);
         t = _mm_xor_si128(state, ks[0]);
         c = _mm_aesenc_si128(c, ks[1]);
         t = _mm_aesenc_si128(t, ks[1]);
         c = _mm_aesenc_si128(c, ks[2]);
         t = _mm_aesenc_si128(t, ks[2]);
         c = _mm_aesenc_si128(c, ks[3]);
         t = _mm_aesenc_si128(t, ks[3]);
         c = _mm_aesenc_si128(c, ks[4]);
         t = _mm_aesenc_si128(t, ks[4]);
         c = _mm_aesenc_si128(c, ks[5]);
         t = _mm_aesenc_si128(t, ks[5]);
         c = _mm_aesenc_si128(c, ks[6]);
         t = _mm_aesenc_si128(t, ks[6]);
         c = _mm_aesenc_si128(c, ks[7]);
         t = _mm_aesenc_si128(t, ks[7]);
         c = _mm_aesenc_si128(c, ks[8]);
         t = _mm_aesenc_si128(t, ks[8]);
         c = _mm_aesenc_si128(c, ks[9]);
         t = _mm_aesenc_si128(t, ks[9]);
         c = _mm_aesenc_si128(c, ks[10]);
         t = _mm_aesenc_si128(t, ks[10]);
         c = _mm_aesenc_si128(c, ks[11]);
         t = _mm_aesenc_si128(t, ks[11]);
         c = _mm_aesenclast_si128(c, ks[12]);
         t = _mm_aesenclast_si128(t, ks[12]);
         t = _mm_xor_si128(t, d);
         _mm_storeu_si128(bo + i, t);
         state = increment_be(state);
     }
     if (rem)
     {
         c = encrypt_ccm_rem(this->key, rem, state, bi + blocks, bo + blocks, c);
     }
     crypt_icv(this, iv, c, icv);
 }
static void encrypt_ccm256 (private_aesni_ccm_t * this, size_t len, u_char * in, u_char * out, u_char * iv, size_t alen, u_char * assoc, u_char * icv) static
AES-256 CCM encryption/ICV generation
Definition at line 595 of file aesni_ccm.c.
References AES_BLOCK_SIZE, b, build_ctr(), c, crypt_icv(), encrypt_ccm_rem(), icv_header(), increment_be(), and key.
Referenced by aesni_ccm_create().
 {
     __m128i *ks, d, t, c, b, state, *bi, *bo;
     u_int blocks, rem, i;
     c = icv_header(this, len, iv, alen, assoc);
     build_ctr(this, 1, iv, &b);
     state = _mm_load_si128(&b);
     blocks = len / AES_BLOCK_SIZE;
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < blocks; i++)
     {
         d = _mm_loadu_si128(bi + i);
         c = _mm_xor_si128(d, c);
         c = _mm_xor_si128(c, ks[0]);
         t = _mm_xor_si128(state, ks[0]);
         c = _mm_aesenc_si128(c, ks[1]);
         t = _mm_aesenc_si128(t, ks[1]);
         c = _mm_aesenc_si128(c, ks[2]);
         t = _mm_aesenc_si128(t, ks[2]);
         c = _mm_aesenc_si128(c, ks[3]);
         t = _mm_aesenc_si128(t, ks[3]);
         c = _mm_aesenc_si128(c, ks[4]);
         t = _mm_aesenc_si128(t, ks[4]);
         c = _mm_aesenc_si128(c, ks[5]);
         t = _mm_aesenc_si128(t, ks[5]);
         c = _mm_aesenc_si128(c, ks[6]);
         t = _mm_aesenc_si128(t, ks[6]);
         c = _mm_aesenc_si128(c, ks[7]);
         t = _mm_aesenc_si128(t, ks[7]);
         c = _mm_aesenc_si128(c, ks[8]);
         t = _mm_aesenc_si128(t, ks[8]);
         c = _mm_aesenc_si128(c, ks[9]);
         t = _mm_aesenc_si128(t, ks[9]);
         c = _mm_aesenc_si128(c, ks[10]);
         t = _mm_aesenc_si128(t, ks[10]);
         c = _mm_aesenc_si128(c, ks[11]);
         t = _mm_aesenc_si128(t, ks[11]);
         c = _mm_aesenc_si128(c, ks[12]);
         t = _mm_aesenc_si128(t, ks[12]);
         c = _mm_aesenc_si128(c, ks[13]);
         t = _mm_aesenc_si128(t, ks[13]);
         c = _mm_aesenclast_si128(c, ks[14]);
         t = _mm_aesenclast_si128(t, ks[14]);
         t = _mm_xor_si128(t, d);
         _mm_storeu_si128(bo + i, t);
         state = increment_be(state);
     }
     if (rem)
     {
         c = encrypt_ccm_rem(this->key, rem, state, bi + blocks, bo + blocks, c);
     }
     crypt_icv(this, iv, c, icv);
 }
static __m128i encrypt_ccm_rem (aesni_key_t * key, u_int rem, __m128i state, void * in, void * out, __m128i c) static
Encrypt a remaining incomplete block
Definition at line 260 of file aesni_ccm.c.
References b, c, memcpy, memset, and aesni_key_t::rounds.
Referenced by encrypt_ccm128(), encrypt_ccm192(), and encrypt_ccm256().
 {
     __m128i *ks, t, b, d;
     u_int round;
     ks = key->schedule;
     memset(&b, 0, sizeof(b));
     memcpy(&b, in, rem);
     d = _mm_loadu_si128(&b);
     c = _mm_xor_si128(d, c);
     c = _mm_xor_si128(c, ks[0]);
     t = _mm_xor_si128(state, ks[0]);
     for (round = 1; round < key->rounds; round++)
     {
         c = _mm_aesenc_si128(c, ks[round]);
         t = _mm_aesenc_si128(t, ks[round]);
     }
     c = _mm_aesenclast_si128(c, ks[key->rounds]);
     t = _mm_aesenclast_si128(t, ks[key->rounds]);
     t = _mm_xor_si128(t, d);
     _mm_storeu_si128(&b, t);
     memcpy(out, &b, rem);
     return c;
 }
static __m128i icv_header (private_aesni_ccm_t * this, size_t len, u_char * iv, u_int16_t alen, u_char * assoc) static
Calculate the ICV for the b0 and associated data
Definition at line 159 of file aesni_ccm.c.
References AES_BLOCK_SIZE, b, build_b0(), c, htoun16(), key, memcpy, memset, and min.
Referenced by decrypt_ccm128(), decrypt_ccm192(), decrypt_ccm256(), encrypt_ccm128(), encrypt_ccm192(), and encrypt_ccm256().
 {
     __m128i *ks, b, t, c;
     u_int i, round, blocks, rem;
     ks = this->key->schedule;
     build_b0(this, len, alen, iv, &b);
     c = _mm_loadu_si128(&b);
     c = _mm_xor_si128(c, ks[0]);
     for (round = 1; round < this->key->rounds; round++)
     {
         c = _mm_aesenc_si128(c, ks[round]);
     }
     c = _mm_aesenclast_si128(c, ks[this->key->rounds]);
     if (alen)
     {
         blocks = (alen + sizeof(alen)) / AES_BLOCK_SIZE;
         rem = (alen + sizeof(alen)) % AES_BLOCK_SIZE;
         if (rem)
         {
             blocks++;
         }
         for (i = 0; i < blocks; i++)
         {
             if (i == 0)
             {   /* first block */
                 memset(&b, 0, sizeof(b));
                 htoun16(&b, alen);
                 memcpy(((u_char*)&b) + sizeof(alen), assoc,
                        min(alen, sizeof(b) - sizeof(alen)));
                 t = _mm_loadu_si128(&b);
             }
             else if (i == blocks - 1 && rem)
             {   /* last block with padding */
                 memset(&b, 0, sizeof(b));
                 memcpy(&b, ((__m128i*)(assoc - sizeof(alen))) + i, rem);
                 t = _mm_loadu_si128(&b);
             }
             else
             {   /* full block */
                 t = _mm_loadu_si128(((__m128i*)(assoc - sizeof(alen))) + i);
             }
             c = _mm_xor_si128(t, c);
             c = _mm_xor_si128(c, ks[0]);
             for (round = 1; round < this->key->rounds; round++)
             {
                 c = _mm_aesenc_si128(c, ks[round]);
             }
             c = _mm_aesenclast_si128(c, ks[this->key->rounds]);
         }
     }
     return c;
 }
static __m128i increment_be (__m128i x) inline static
Do big-endian increment on x
Definition at line 244 of file aesni_ccm.c.
Referenced by decrypt_ccm128(), decrypt_ccm192(), decrypt_ccm256(), encrypt_ccm128(), encrypt_ccm192(), and encrypt_ccm256().
 {
     __m128i swap;
     swap = _mm_set_epi8(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
     x = _mm_shuffle_epi8(x, swap);
     x = _mm_add_epi64(x, _mm_set_epi32(0, 0, 0, 1));
     x = _mm_shuffle_epi8(x, swap);
     return x;
 }
METHOD (aead_t , encrypt , bool , private_aesni_ccm_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t * encr)
Definition at line 736 of file aesni_ccm.c.
References chunk_alloc, encrypt(), FALSE, IV_SIZE, key, chunk_t::len, out, chunk_t::ptr, and TRUE.
 {
     u_char *out;
     if (!this->key || iv.len != IV_SIZE)
     {
         return FALSE;
     }
     out = plain.ptr;
     if (encr)
     {
         *encr = chunk_alloc(plain.len + this->icv_size);
         out = encr->ptr;
     }
     this->encrypt(this, plain.len, plain.ptr, out, iv.ptr,
                   assoc.len, assoc.ptr, out + plain.len);
     return TRUE;
 }
METHOD (aead_t , decrypt , bool , private_aesni_ccm_t * this, chunk_t encr, chunk_t assoc, chunk_t iv, chunk_t * plain)
Definition at line 757 of file aesni_ccm.c.
References chunk_alloc, decrypt, FALSE, IV_SIZE, key, chunk_t::len, memeq_const(), out, and chunk_t::ptr.
 {
     u_char *out, icv[this->icv_size];
     if (!this->key || iv.len != IV_SIZE || encr.len < this->icv_size)
     {
         return FALSE;
     }
     encr.len -= this->icv_size;
     out = encr.ptr;
     if (plain)
     {
         *plain = chunk_alloc(encr.len);
         out = plain->ptr;
     }
     this->decrypt(this, encr.len, encr.ptr, out, iv.ptr,
                   assoc.len, assoc.ptr, icv);
     return memeq_const(icv, encr.ptr + encr.len, this->icv_size);
 }
METHOD (aead_t , get_block_size , size_t , private_aesni_ccm_t * this)
Definition at line 780 of file aesni_ccm.c.
 {
     return 1;
 }
METHOD (aead_t , get_icv_size , size_t , private_aesni_ccm_t * this)
Definition at line 786 of file aesni_ccm.c.
 {
     return this->icv_size;
 }
METHOD (aead_t , get_iv_size , size_t , private_aesni_ccm_t * this)
Definition at line 792 of file aesni_ccm.c.
References IV_SIZE.
 {
     return IV_SIZE;
 }
METHOD (aead_t , get_iv_gen , iv_gen_t * , private_aesni_ccm_t * this)
Definition at line 798 of file aesni_ccm.c.
 {
     return this->iv_gen;
 }
METHOD (aead_t , get_key_size , size_t , private_aesni_ccm_t * this)
Definition at line 804 of file aesni_ccm.c.
References key_size, and SALT_SIZE.
 {
     return this->key_size + SALT_SIZE;
 }
METHOD (aead_t , set_key , bool , private_aesni_ccm_t * this, chunk_t key)
Definition at line 810 of file aesni_ccm.c.
References aesni_key_create(), DESTROY_IF, FALSE, chunk_t::len, memcpy, chunk_t::ptr, salt, SALT_SIZE, and TRUE.
 {
     if (key.len != this->key_size + SALT_SIZE)
     {
         return FALSE;
     }
     memcpy(this->salt, key.ptr + key.len - SALT_SIZE, SALT_SIZE);
     key.len -= SALT_SIZE;
     DESTROY_IF(this->key);
     this->key = aesni_key_create(TRUE, key);
     return TRUE;
 }
METHOD (aead_t , destroy , void , private_aesni_ccm_t * this)
Definition at line 826 of file aesni_ccm.c.
References DESTROY_IF, free_align(), and key.
 {
     DESTROY_IF(this->key);
     this->iv_gen->destroy(this->iv_gen);
     free_align(this);
 }
Variable Documentation
b0_t
Definition at line 102 of file aesni_ccm.c.
Referenced by build_b0().
ctr_t
Definition at line 121 of file aesni_ccm.c.
Referenced by build_ctr().