strongSwan: files_fetcher.c File Reference
files_fetcher.c File Reference
#include <errno.h>
#include <library.h>
#include <utils/debug.h>
#include "files_fetcher.h"
Classes
struct private_files_fetcher_t
Typedefs
typedef struct
private_files_fetcher_t private_files_fetcher_t
Functions
METHOD (fetcher_t, fetch, status_t, private_files_fetcher_t *this, char *uri, void *userdata)
METHOD (fetcher_t, set_option, bool, private_files_fetcher_t *this, fetcher_option_t option,...)
METHOD (fetcher_t, destroy, void, private_files_fetcher_t *this)
files_fetcher_t * files_fetcher_create ()
Typedef Documentation
typedef struct private_files_fetcher_t private_files_fetcher_t
Definition at line 23 of file files_fetcher.c.
Function Documentation
METHOD (fetcher_t , fetch , status_t , private_files_fetcher_t * this, char * uri, void * userdata)
Definition at line 41 of file files_fetcher.c.
References cb(), chunk_empty, chunk_map(), chunk_unmap(), data, DBG1, DBG_LIB, FAILED, FALSE, fetcher_default_callback(), NOT_SUPPORTED, status, strerror, strpfx(), and SUCCESS.
 {
     chunk_t *data;
     status_t status = FAILED;
     if (this->cb == fetcher_default_callback)
     {
         *(chunk_t*)userdata = chunk_empty;
     }
     if (!strpfx(uri, "file://"))
     {
         return NOT_SUPPORTED;
     }
     uri = uri + strlen("file://");
     data = chunk_map(uri, FALSE);
     if (!data)
     {
         DBG1(DBG_LIB, "  opening '%s' failed: %s", uri, strerror(errno));
         return FAILED;
     }
     if (this->cb(userdata, *data))
     {
         status = SUCCESS;
     }
     chunk_unmap(data);
     return status;
 }
METHOD (fetcher_t , set_option , bool , private_files_fetcher_t * this, fetcher_option_t option, ...)
Definition at line 70 of file files_fetcher.c.
References cb(), FALSE, FETCH_CALLBACK, and TRUE.
 {
     bool supported = TRUE;
     va_list args;
     va_start(args, option);
     switch (option)
     {
         case FETCH_CALLBACK:
         {
             this->cb = va_arg(args, fetcher_callback_t);
             break;
         }
         default:
             supported = FALSE;
             break;
     }
     va_end(args);
     return supported;
 }
METHOD (fetcher_t , destroy , void , private_files_fetcher_t * this)
Definition at line 92 of file files_fetcher.c.
References free().
 {
     free(this);
 }