strongSwan: tnc_identities
tnc_identities
libtncif
Classes
struct tncif_identity_t
Macros
#define TNCIF_IDENTITY_MIN_SIZE 28
Typedefs
typedef struct tncif_identity_t tncif_identity_t
Functions
tncif_identity_t * tncif_identity_create_empty (void)
tncif_identity_t * tncif_identity_create (pen_type_t identity_type, chunk_t identity_value, pen_type_t subject_type, pen_type_t auth_type)
Detailed Description
Macro Definition Documentation
#define TNCIF_IDENTITY_MIN_SIZE 28
Definition at line 35 of file tncif_identity.h.
Referenced by identity_attribute(), and METHOD().
Typedef Documentation
typedef struct tncif_identity_t tncif_identity_t
Definition at line 37 of file tncif_identity.h.
Function Documentation
tncif_identity_t* tncif_identity_create (pen_type_t identity_type, chunk_t identity_value, pen_type_t subject_type, pen_type_t auth_type)
Create an TNC Identity object from its components
Parameters
identity_type TNC Identity Type
identity_value TNC Identity Value (not cloned by constructor)
subject_type TNC Subject Type
auth_type TNC Authentication Type
See header
Definition at line 190 of file tncif_identity.c.
References tncif_identity_create_empty().
Referenced by METHOD().
 {
     private_tncif_identity_t *this;
     this = (private_tncif_identity_t*)tncif_identity_create_empty();
     this->identity_type = identity_type;
     this->identity_value = identity_value;
     this->subject_type = subject_type;
     this->auth_type = auth_type;
     return &this->public;
 }
tncif_identity_t* tncif_identity_create_empty (void)
Create an empty TNC Identity object
See header
Definition at line 168 of file tncif_identity.c.
References INIT.
Referenced by get_identity_attribute(), and tncif_identity_create().
 {
     private_tncif_identity_t *this;
     INIT(this,
         .public = {
             .get_identity_type = _get_identity_type,
             .get_identity_value = _get_identity_value,
             .get_subject_type = _get_subject_type,
             .get_auth_type = _get_auth_type,
             .build = _build,
             .process = _process,
             .destroy = _destroy,
         },
     );
     return &this->public;
 }