strongSwan: bliss_signature
bliss_signature
bliss
Classes
struct bliss_signature_t
Typedefs
typedef struct bliss_signature_t bliss_signature_t
Functions
bliss_signature_t * bliss_signature_create (bliss_param_set_t *set)
bliss_signature_t * bliss_signature_create_from_data (bliss_param_set_t *set, chunk_t encoding)
Detailed Description
Typedef Documentation
typedef struct bliss_signature_t bliss_signature_t
Definition at line 24 of file bliss_signature.h.
Function Documentation
bliss_signature_t* bliss_signature_create (bliss_param_set_t * set)
Create a BLISS signature object.
Parameters
set BLISS parameter set
See header.
Definition at line 137 of file bliss_signature.c.
References INIT, malloc(), and bliss_param_set_t::n.
Referenced by sign_bliss(), and START_TEST().
 {
     private_bliss_signature_t *this;
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .get_parameters = _get_parameters,
             .destroy = _destroy,
         },
         .set = set,
         .z1  = malloc(set->n * sizeof(int32_t)),
         .z2d = malloc(set->n * sizeof(int16_t)),
         .c_indices = malloc(set->n * sizeof(uint16_t)),
     );
     return &this->public;
 }
bliss_signature_t* bliss_signature_create_from_data (bliss_param_set_t * set, chunk_t encoding)
Create a BLISS signature object from encoding.
Parameters
set BLISS parameter set
encoding binary signature encoding
See header.
Definition at line 159 of file bliss_signature.c.
References bliss_bitpacker_create_from_data(), bliss_huffman_code_get_by_id(), bliss_huffman_coder_create(), bliss_param_set_id_names, code, DBG1, DBG_LIB, bliss_huffman_coder_t::decode, bliss_huffman_coder_t::destroy, destroy(), bliss_param_set_t::id, INIT, bliss_param_set_t::kappa, chunk_t::len, malloc(), bliss_param_set_t::n, bliss_param_set_t::n_bits, and value.
Referenced by START_TEST(), and verify_bliss().
 {
     private_bliss_signature_t *this;
     bliss_bitpacker_t *packer;
     bliss_huffman_coder_t *coder;
     bliss_huffman_code_t *code;
     uint32_t z1_sign, z1_low, value;
     int32_t z1;
     int16_t z2;
     int i;
     /* Get Huffman code for this BLISS parameter set */
     code = bliss_huffman_code_get_by_id(set->id);
     if (!code)
     {
         DBG1(DBG_LIB, "no Huffman code found for parameter set %N",
              bliss_param_set_id_names, set->id);
         return NULL;
     }
     if (encoding.len == 0)
     {
         DBG1(DBG_LIB, "zero length BLISS signature");
         return NULL;
     }
     INIT(this,
         .public = {
             .get_encoding = _get_encoding,
             .get_parameters = _get_parameters,
             .destroy = _destroy,
         },
         .set = set,
         .z1  = malloc(set->n * sizeof(int32_t)),
         .z2d = malloc(set->n * sizeof(int16_t)),
         .c_indices = malloc(set->n * sizeof(uint16_t)),
     );
     packer = bliss_bitpacker_create_from_data(encoding);
     coder = bliss_huffman_coder_create(code, packer);
     for (i = 0; i < set->n; i++)
     {
         if (!packer->read_bits(packer, &z1_sign, 1) ||
             !packer->read_bits(packer, &z1_low, 8) ||
             !coder->decode(coder, &z1, &z2))
         {
             DBG1(DBG_LIB, "truncated BLISS signature encoding of z1/z2");
             coder->destroy(coder);
             packer->destroy(packer);
             destroy(this);
             return NULL;
         }
         z1 = (z1 << 8) + z1_low;
         this->z1[i] = z1_sign ? -z1 : z1;
         this->z2d[i] = z2;
     }
     coder->destroy(coder);
     for (i = 0; i < set->kappa; i++)
     {
         if (!packer->read_bits(packer, &value, set->n_bits))
         {
             DBG1(DBG_LIB, "truncated BLISS signature encoding of c_indices");
             packer->destroy(packer);
             destroy(this);
             return NULL;
         }
         this->c_indices[i] = value;
     }
     packer->destroy(packer);
     return &this->public;
 }