strongSwan: crypto_factory_t Struct Reference
crypto_factory_t Struct Reference
crypto_factory
#include "crypto_factory.h"
Public Attributes
crypter_t *(* create_crypter)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size)
aead_t *(* create_aead)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, size_t salt_size)
signer_t *(* create_signer)(crypto_factory_t *this, integrity_algorithm_t algo)
hasher_t *(* create_hasher)(crypto_factory_t *this, hash_algorithm_t algo)
prf_t *(* create_prf)(crypto_factory_t *this, pseudo_random_function_t algo)
rng_t *(* create_rng)(crypto_factory_t *this, rng_quality_t quality)
nonce_gen_t *(* create_nonce_gen)(crypto_factory_t *this)
diffie_hellman_t *(* create_dh)(crypto_factory_t *this, diffie_hellman_group_t group,...)
bool(* add_crypter)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, const char *plugin_name, crypter_constructor_t create)
void(* remove_crypter)(crypto_factory_t *this, crypter_constructor_t create)
void(* remove_aead)(crypto_factory_t *this, aead_constructor_t create)
bool(* add_aead)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, const char *plugin_name, aead_constructor_t create)
bool(* add_signer)(crypto_factory_t *this, integrity_algorithm_t algo, const char *plugin_name, signer_constructor_t create)
void(* remove_signer)(crypto_factory_t *this, signer_constructor_t create)
bool(* add_hasher)(crypto_factory_t *this, hash_algorithm_t algo, const char *plugin_name, hasher_constructor_t create)
void(* remove_hasher)(crypto_factory_t *this, hasher_constructor_t create)
bool(* add_prf)(crypto_factory_t *this, pseudo_random_function_t algo, const char *plugin_name, prf_constructor_t create)
void(* remove_prf)(crypto_factory_t *this, prf_constructor_t create)
bool(* add_rng)(crypto_factory_t *this, rng_quality_t quality, const char *plugin_name, rng_constructor_t create)
void(* remove_rng)(crypto_factory_t *this, rng_constructor_t create)
bool(* add_nonce_gen)(crypto_factory_t *this, const char *plugin_name, nonce_gen_constructor_t create)
void(* remove_nonce_gen)(crypto_factory_t *this, nonce_gen_constructor_t create)
bool(* add_dh)(crypto_factory_t *this, diffie_hellman_group_t group, const char *plugin_name, dh_constructor_t create)
void(* remove_dh)(crypto_factory_t *this, dh_constructor_t create)
enumerator_t *(* create_crypter_enumerator)(crypto_factory_t *this)
enumerator_t *(* create_aead_enumerator)(crypto_factory_t *this)
enumerator_t *(* create_signer_enumerator)(crypto_factory_t *this)
enumerator_t *(* create_hasher_enumerator)(crypto_factory_t *this)
enumerator_t *(* create_prf_enumerator)(crypto_factory_t *this)
enumerator_t *(* create_dh_enumerator)(crypto_factory_t *this)
enumerator_t *(* create_rng_enumerator)(crypto_factory_t *this)
enumerator_t *(* create_nonce_gen_enumerator)(crypto_factory_t *this)
void(* add_test_vector)(crypto_factory_t *this, transform_type_t type, void *vector)
enumerator_t *(* create_verify_enumerator)(crypto_factory_t *this, transform_type_t type)
void(* destroy)(crypto_factory_t *this)
Detailed Description
Handles crypto modules and creates instances.
Definition at line 86 of file crypto_factory.h.
Member Data Documentation
bool(* crypto_factory_t::add_aead)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, const char *plugin_name, aead_constructor_t create)
Register a aead constructor.
Parameters
algo algorithm to constructor
key size key size to peform benchmarking for
plugin_name plugin that registered this algorithm
create constructor function for that algorithm
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 197 of file crypto_factory.h.
Referenced by plugin_feature_load().
bool(* crypto_factory_t::add_crypter)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, const char *plugin_name, crypter_constructor_t create)
Register a crypter constructor.
Parameters
algo algorithm to constructor
key size key size to peform benchmarking for
plugin_name plugin that registered this algorithm
create constructor function for that algorithm
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 170 of file crypto_factory.h.
Referenced by plugin_feature_load().
bool(* crypto_factory_t::add_dh)(crypto_factory_t *this, diffie_hellman_group_t group, const char *plugin_name, dh_constructor_t create)
Register a diffie hellman constructor.
Parameters
group dh group to constructor
plugin_name plugin that registered this algorithm
create constructor function for that algorithm
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 299 of file crypto_factory.h.
Referenced by plugin_feature_load(), and START_TEST().
bool(* crypto_factory_t::add_hasher)(crypto_factory_t *this, hash_algorithm_t algo, const char *plugin_name, hasher_constructor_t create)
Register a hasher constructor.
Parameters
algo algorithm to constructor
plugin_name plugin that registered this algorithm
create constructor function for that algorithm
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 227 of file crypto_factory.h.
Referenced by plugin_feature_load().
bool(* crypto_factory_t::add_nonce_gen)(crypto_factory_t *this, const char *plugin_name, nonce_gen_constructor_t create)
Register a nonce generator.
Parameters
plugin_name plugin that registered this algorithm
create constructor function for that nonce generator
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 280 of file crypto_factory.h.
Referenced by plugin_feature_load().
bool(* crypto_factory_t::add_prf)(crypto_factory_t *this, pseudo_random_function_t algo, const char *plugin_name, prf_constructor_t create)
Register a prf constructor.
Parameters
algo algorithm to constructor
plugin_name plugin that registered this algorithm
create constructor function for that algorithm
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 245 of file crypto_factory.h.
Referenced by plugin_feature_load().
bool(* crypto_factory_t::add_rng)(crypto_factory_t *this, rng_quality_t quality, const char *plugin_name, rng_constructor_t create)
Register a source of randomness.
Parameters
quality quality of randomness this RNG serves
plugin_name plugin that registered this algorithm
create constructor function for such a quality
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 263 of file crypto_factory.h.
Referenced by plugin_feature_load(), and START_TEST().
bool(* crypto_factory_t::add_signer)(crypto_factory_t *this, integrity_algorithm_t algo, const char *plugin_name, signer_constructor_t create)
Register a signer constructor.
Parameters
algo algorithm to constructor
plugin_name plugin that registered this algorithm
create constructor function for that algorithm
Returns
TRUE if registered, FALSE if test vector failed
Definition at line 209 of file crypto_factory.h.
Referenced by plugin_feature_load().
void(* crypto_factory_t::add_test_vector)(crypto_factory_t *this, transform_type_t type, void *vector)
Add a test vector to the crypto factory.
Parameters
type type of the test vector
vector pointer to a test vector, defined in crypto_tester.h
Definition at line 371 of file crypto_factory.h.
Referenced by test_vectors_plugin_create().
aead_t*(* crypto_factory_t::create_aead)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Create a aead instance.
Parameters
algo encryption algorithm
key_size length of the key in bytes
salt_size size of salt, implicit part of the nonce
Returns
aead_t instance, NULL if not supported
Definition at line 106 of file crypto_factory.h.
Referenced by attack_aeads(), burn_aead(), create_aead(), derive_ike_aead(), do_test_gcm(), START_TEST(), and tls_aead_create_aead().
enumerator_t*(* crypto_factory_t::create_aead_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered aead algorithms.
Returns
enumerator over encryption_algorithm_t, plugin
Definition at line 321 of file crypto_factory.h.
Referenced by filter_suite(), filter_unsupported_suites(), list_algs(), and proposal_add_supported_ike().
crypter_t*(* crypto_factory_t::create_crypter)(crypto_factory_t *this, encryption_algorithm_t algo, size_t key_size)
Create a crypter instance.
Parameters
algo encryption algorithm
key_size length of the key in bytes
Returns
crypter_t instance, NULL if not supported
Definition at line 95 of file crypto_factory.h.
Referenced by aead_create_from_keys(), burn_crypter(), ccm_aead_create(), ChallengeResponse(), cmac_create(), create_aead(), create_traditional(), ctr_ipsec_crypter_create(), decrypt(), derive_ike_traditional(), do_test_cbc(), do_test_mct(), ensure_crypto_primitives(), gcm_aead_create(), generate(), pem_decrypt(), rdrand_mixed(), simaka_crypto_create(), tls_aead_create_explicit(), tls_aead_create_implicit(), and xcbc_create().
enumerator_t*(* crypto_factory_t::create_crypter_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered crypter algorithms.
Returns
enumerator over encryption_algorithm_t, plugin
Definition at line 314 of file crypto_factory.h.
Referenced by filter_suite(), filter_unsupported_suites(), list_algs(), and proposal_add_supported_ike().
diffie_hellman_t*(* crypto_factory_t::create_dh)(crypto_factory_t *this, diffie_hellman_group_t group,...)
Create a diffie hellman instance.
Additional arguments are passed to the DH constructor.
Parameters
group diffie hellman group
Returns
diffie_hellman_t instance, NULL if not supported
Definition at line 158 of file crypto_factory.h.
Referenced by METHOD(), process_ec_key_exchange(), process_modp_key_exchange(), run_test(), send_server_key_exchange(), START_TEST(), and verify_dh().
enumerator_t*(* crypto_factory_t::create_dh_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered diffie hellman groups.
Returns
enumerator over diffie_hellman_group_t, plugin
Definition at line 349 of file crypto_factory.h.
Referenced by filter_unsupported_suites(), list_algs(), METHOD(), proposal_add_supported_ike(), pts_dh_group_probe(), and START_TEST().
hasher_t*(* crypto_factory_t::create_hasher)(crypto_factory_t *this, hash_algorithm_t algo)
Create a hasher instance.
Parameters
algo hash algorithm
Returns
hasher_t instance, NULL if not supported
Definition at line 125 of file crypto_factory.h.
Referenced by AuthenticatorResponse(), bliss_public_key_fingerprint(), build_cert_payload(), build_emsa_pkcs1_signature(), build_requestList(), build_v3_fingerprint(), ChallengeHash(), check_boot_aggregate(), connect_manager_create(), coupling_validator_create(), derive_key(), eap_radius_dae_create(), ensure_crypto_primitives(), fingerprint_ecdsa(), generate(), GenerateMSK(), hash_challenge(), hash_data(), hash_password(), hash_pubkey(), hmac_create(), ike_natd_create(), ima_hash(), main(), METHOD(), mgf1_create(), NtPasswordHash(), openssl_ec_fingerprint(), openssl_rsa_fingerprint(), parse_certificate(), parse_public_key(), pem_decrypt(), pts_file_meas_create_from_path(), pts_pcr_create(), radius_socket_create(), receiver_create(), scep_generate_pkcs10_fingerprint(), scep_generate_transaction_id(), sign_bliss(), sign_pkcs1(), simaka_crypto_create(), tnc_pdp_create(), verify_bliss(), verify_emsa_pkcs1_signature(), and verify_pkcs1().
enumerator_t*(* crypto_factory_t::create_hasher_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered hasher algorithms.
Returns
enumerator over hash_algorithm_t, plugin
Definition at line 335 of file crypto_factory.h.
Referenced by filter_unsupported_suites(), list_algs(), pts_meas_algo_probe(), and send_supported_hash_algorithms().
nonce_gen_t*(* crypto_factory_t::create_nonce_gen)(crypto_factory_t *this)
Create a nonce generator instance.
Returns
nonce_gen_t instance, NULL if not supported
Definition at line 148 of file crypto_factory.h.
Referenced by imc_swid_state_create(), METHOD(), and tnc_pdp_create().
enumerator_t*(* crypto_factory_t::create_nonce_gen_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered nonce generators.
Returns
enumerator over plugin
Definition at line 363 of file crypto_factory.h.
Referenced by list_algs().
prf_t*(* crypto_factory_t::create_prf)(crypto_factory_t *this, pseudo_random_function_t algo)
Create a pseudo random function instance.
Parameters
algo PRF algorithm to use
Returns
prf_t instance, NULL if not supported
Definition at line 133 of file crypto_factory.h.
Referenced by eap_aka_3gpp2_functions_create(), ensure_crypto_primitives(), fips_prf_create(), METHOD(), simaka_crypto_create(), tls_prf_create_10(), and tls_prf_create_12().
enumerator_t*(* crypto_factory_t::create_prf_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered PRFs.
Returns
enumerator over pseudo_random_function_t, plugin
Definition at line 342 of file crypto_factory.h.
Referenced by filter_unsupported_suites(), list_algs(), and proposal_add_supported_ike().
rng_t*(* crypto_factory_t::create_rng)(crypto_factory_t *this, rng_quality_t quality)
Create a source of randomness.
Parameters
quality required randomness quality
Returns
rng_t instance, NULL if no RNG with such a quality
Definition at line 141 of file crypto_factory.h.
Referenced by acert(), bliss_private_key_gen(), build_cookie(), build_nonce(), compute_prime(), create_generic(), create_sid(), dhcp_socket_create(), do_test_gcm(), eap_simaka_pseudonym_provider_create(), eap_simaka_reauth_provider_create(), encrypt_content(), generate_guid(), generate_natd_hash_faked(), get_random(), gmp_rsa_private_key_gen(), ike_sa_manager_create(), init_spi(), issue(), iv_gen_rand_create(), iv_gen_seq_create(), METHOD(), nonce_nonceg_create(), ntru_ke_create(), process_client_hello(), process_key_exchange_encrypted(), process_peer_challenge(), process_server_retry(), radius_socket_create(), receiver_create(), scep_build_request(), seed_rng(), self(), send_client_hello(), send_key_exchange_encrypt(), sign_bliss(), simaka_crypto_create(), START_TEST(), task_manager_v1_create(), tkm_spi_generator_register(), and verify_rng().
enumerator_t*(* crypto_factory_t::create_rng_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered random generators.
Returns
enumerator over rng_quality_t, plugin
Definition at line 356 of file crypto_factory.h.
Referenced by list_algs().
signer_t*(* crypto_factory_t::create_signer)(crypto_factory_t *this, integrity_algorithm_t algo)
Create a symmetric signer instance.
Parameters
algo MAC algorithm to use
Returns
signer_t instance, NULL if not supported
Definition at line 116 of file crypto_factory.h.
Referenced by aead_create_from_keys(), attack_signers(), burn_signer(), create_traditional(), derive_ike_traditional(), eap_radius_dae_create(), ntru_drbg_create(), radius_socket_create(), simaka_crypto_create(), tls_aead_create_explicit(), tls_aead_create_implicit(), tls_aead_create_null(), tnc_pdp_create(), and verify_mac().
enumerator_t*(* crypto_factory_t::create_signer_enumerator)(crypto_factory_t *this)
Create an enumerator over all registered signer algorithms.
Returns
enumerator over integrity_algorithm_t, plugin
Definition at line 328 of file crypto_factory.h.
Referenced by filter_unsupported_suites(), list_algs(), and proposal_add_supported_ike().
enumerator_t*(* crypto_factory_t::create_verify_enumerator)(crypto_factory_t *this, transform_type_t type)
Create an enumerator verifying transforms using known test vectors.
The resulting enumerator enumerates over an u_int with the type specific transform identifier, the plugin name providing the transform, and a boolean value indicating success/failure for the given transform.
Parameters
type transform type to test
Returns
enumerator over (u_int, char*, bool)
Definition at line 384 of file crypto_factory.h.
Referenced by START_TEST().
void(* crypto_factory_t::destroy)(crypto_factory_t *this)
Destroy a crypto_factory instance.
Definition at line 390 of file crypto_factory.h.
Referenced by START_TEST().
void(* crypto_factory_t::remove_aead)(crypto_factory_t *this, aead_constructor_t create)
Unregister a aead constructor.
Parameters
create constructor function to unregister
Definition at line 186 of file crypto_factory.h.
Referenced by plugin_feature_unload().
void(* crypto_factory_t::remove_crypter)(crypto_factory_t *this, crypter_constructor_t create)
Unregister a crypter constructor.
Parameters
create constructor function to unregister
Definition at line 179 of file crypto_factory.h.
Referenced by plugin_feature_unload().
void(* crypto_factory_t::remove_dh)(crypto_factory_t *this, dh_constructor_t create)
Unregister a diffie hellman constructor.
Parameters
create constructor function to unregister
Definition at line 307 of file crypto_factory.h.
Referenced by plugin_feature_unload(), and START_TEST().
void(* crypto_factory_t::remove_hasher)(crypto_factory_t *this, hasher_constructor_t create)
Unregister a hasher constructor.
Parameters
create constructor function to unregister
Definition at line 235 of file crypto_factory.h.
Referenced by plugin_feature_unload().
void(* crypto_factory_t::remove_nonce_gen)(crypto_factory_t *this, nonce_gen_constructor_t create)
Unregister a nonce generator.
Parameters
create constructor function to unregister
Definition at line 288 of file crypto_factory.h.
Referenced by plugin_feature_unload().
void(* crypto_factory_t::remove_prf)(crypto_factory_t *this, prf_constructor_t create)
Unregister a prf constructor.
Parameters
create constructor function to unregister
Definition at line 253 of file crypto_factory.h.
Referenced by plugin_feature_unload().
void(* crypto_factory_t::remove_rng)(crypto_factory_t *this, rng_constructor_t create)
Unregister a source of randomness.
Parameters
create constructor function to unregister
Definition at line 271 of file crypto_factory.h.
Referenced by plugin_feature_unload(), and START_TEST().
void(* crypto_factory_t::remove_signer)(crypto_factory_t *this, signer_constructor_t create)
Unregister a signer constructor.
Parameters
create constructor function to unregister
Definition at line 217 of file crypto_factory.h.
Referenced by plugin_feature_unload().
The documentation for this struct was generated from the following file:
crypto_factory.h