strongSwan: eap_aka_server
eap_aka_server
eap_aka
Classes
struct eap_aka_server_t
Typedefs
typedef struct eap_aka_server_t eap_aka_server_t
Functions
eap_aka_server_t * eap_aka_server_create (identification_t *server, identification_t *peer)
Detailed Description
Typedef Documentation
typedef struct eap_aka_server_t eap_aka_server_t
Definition at line 24 of file eap_aka_server.h.
Function Documentation
eap_aka_server_t* eap_aka_server_create (identification_t * server, identification_t * peer)
Creates the server implementation of the EAP method EAP-AKA.
Parameters
server ID of the EAP server
peer ID of the EAP client
Returns
eap_aka_server_t object
Definition at line 693 of file eap_aka_server.c.
References identification_t::clone, EAP_AKA, free(), library_t::get, settings_t::get_bool, identifier, INIT, lib, library_t::ns, random, library_t::settings, simaka_crypto_create(), and TRUE.
Referenced by METHOD().
 {
     private_eap_aka_server_t *this;
     INIT(this,
         .public = {
             .interface = {
                 .initiate = _initiate,
                 .process = _process,
                 .get_type = _get_type,
                 .is_mutual = _is_mutual,
                 .get_msk = _get_msk,
                 .get_identifier = _get_identifier,
                 .set_identifier = _set_identifier,
                 .destroy = _destroy,
             },
         },
         .crypto = simaka_crypto_create(EAP_AKA),
         .mgr = lib->get(lib, "aka-manager"),
     );
     if (!this->crypto)
     {
         free(this);
         return NULL;
     }
     this->permanent = peer->clone(peer);
     this->use_reauth = this->use_pseudonym = this->use_permanent =
         lib->settings->get_bool(lib->settings,
                         "%s.plugins.eap-aka.request_identity", TRUE, lib->ns);
     /* generate a non-zero identifier */
     do {
         this->identifier = random();
     } while (!this->identifier);
     return &this->public;
 }