strongSwan: pubkey_authenticator
pubkey_authenticator
authenticators
Classes
struct pubkey_authenticator_t
Typedefs
typedef struct
pubkey_authenticator_t pubkey_authenticator_t
Functions
pubkey_authenticator_t * pubkey_authenticator_create_builder (ike_sa_t *ike_sa, chunk_t received_nonce, chunk_t sent_init, char reserved[3])
pubkey_authenticator_t * pubkey_authenticator_create_verifier (ike_sa_t *ike_sa, chunk_t sent_nonce, chunk_t received_init, char reserved[3])
Detailed Description
Typedef Documentation
typedef struct pubkey_authenticator_t pubkey_authenticator_t
Definition at line 25 of file pubkey_authenticator.h.
Function Documentation
pubkey_authenticator_t* pubkey_authenticator_create_builder (ike_sa_t * ike_sa, chunk_t received_nonce, chunk_t sent_init, char reserved[3])
Create an authenticator to build public key signatures.
Parameters
ike_sa associated ike_sa
received_nonce nonce received in IKE_SA_INIT
sent_init sent IKE_SA_INIT message data
reserved reserved bytes of ID payload
Returns
public key authenticator
Definition at line 455 of file pubkey_authenticator.c.
References INIT, memcpy, return_failed(), and return_false().
 {
     private_pubkey_authenticator_t *this;
     INIT(this,
         .public = {
             .authenticator = {
                 .build = _build,
                 .process = (void*)return_failed,
                 .is_mutual = (void*)return_false,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .ike_sa_init = sent_init,
         .nonce = received_nonce,
     );
     memcpy(this->reserved, reserved, sizeof(this->reserved));
     return &this->public;
 }
pubkey_authenticator_t* pubkey_authenticator_create_verifier (ike_sa_t * ike_sa, chunk_t sent_nonce, chunk_t received_init, char reserved[3])
Create an authenticator to verify public key signatures.
Parameters
ike_sa associated ike_sa
sent_nonce nonce sent in IKE_SA_INIT
received_init received IKE_SA_INIT message data
reserved reserved bytes of ID payload
Returns
public key authenticator
Definition at line 482 of file pubkey_authenticator.c.
References settings_t::get_bool, INIT, lib, memcpy, library_t::ns, process(), return_failed(), return_false(), library_t::settings, and TRUE.
 {
     private_pubkey_authenticator_t *this;
     INIT(this,
         .public = {
             .authenticator = {
                 .build = (void*)return_failed,
                 .process = _process,
                 .is_mutual = (void*)return_false,
                 .destroy = _destroy,
             },
         },
         .ike_sa = ike_sa,
         .ike_sa_init = received_init,
         .nonce = sent_nonce,
         .store_signature_scheme = lib->settings->get_bool(lib->settings,
                     "%s.signature_authentication_constraints", TRUE, lib->ns),
     );
     memcpy(this->reserved, reserved, sizeof(this->reserved));
     return &this->public;
 }