strongSwan: test_test_rng.c File Reference
test_test_rng.c File Reference
#include "test_suite.h"
#include <tests/utils/test_rng.h>
#include <utils/test.h>
Functions
START_TEST (test_test_rng)
END_TEST Suite * test_rng_suite_create ()
Function Documentation
START_TEST (test_test_rng)
Definition at line 21 of file test_test_rng.c.
References rng_t::allocate_bytes, chunk_cat, chunk_equals(), chunk_free(), chunk_from_chars, ck_assert, rng_t::destroy, rng_t::get_bytes, in, chunk_t::len, memeq(), out, chunk_t::ptr, and test_rng_create().
 {
     rng_t *entropy;
     chunk_t in, in1, in2, out;
     in1 = chunk_from_chars(0x01, 0x02, 0x03, 0x04, 0x05, 0x06);
     in2 = chunk_from_chars(0x07, 0x08);
     in = chunk_cat("cc", in1, in2);
     entropy = test_rng_create(in);
     ck_assert(entropy->allocate_bytes(entropy, 6, &out));
     ck_assert(chunk_equals(in1, out));
     ck_assert(entropy->get_bytes(entropy, 2, out.ptr));
     ck_assert(memeq(in2.ptr, out.ptr, in2.len));
     ck_assert(!entropy->get_bytes(entropy, 4, out.ptr));
     chunk_free(&out);
     ck_assert(!entropy->allocate_bytes(entropy, 4, &out));
     entropy->destroy(entropy);
     chunk_free(&in);
 }
END_TEST Suite* test_rng_suite_create ()
Definition at line 44 of file test_test_rng.c.
References s, Suite, suite_add_tcase, suite_create, TCase, tcase_add_test, and tcase_create.
 {
     Suite *s;
     TCase *tc;
     s = suite_create("test_rng");
     tc = tcase_create("test_rng");
     tcase_add_test(tc, test_test_rng);
     suite_add_tcase(s, tc);
     return s;
 }