strongSwan: quick_delete.c File Reference
quick_delete.c File Reference
#include "quick_delete.h"
#include <daemon.h>
#include <encoding/payloads/delete_payload.h>
Classes
struct private_quick_delete_t
Typedefs
typedef struct
private_quick_delete_t private_quick_delete_t
Functions
static bool delete_child (private_quick_delete_t *this, protocol_id_t protocol, u_int32_t spi, bool remote_close)
METHOD (task_t, build_i, status_t, private_quick_delete_t *this, message_t *message)
METHOD (task_t, process_i, status_t, private_quick_delete_t *this, message_t *message)
METHOD (task_t, process_r, status_t, private_quick_delete_t *this, message_t *message)
METHOD (task_t, build_r, status_t, private_quick_delete_t *this, message_t *message)
METHOD (task_t, get_type, task_type_t, private_quick_delete_t *this)
METHOD (task_t, migrate, void, private_quick_delete_t *this, ike_sa_t *ike_sa)
METHOD (task_t, destroy, void, private_quick_delete_t *this)
quick_delete_t * quick_delete_create (ike_sa_t *ike_sa, protocol_id_t protocol, u_int32_t spi, bool force, bool expired)
Typedef Documentation
typedef struct private_quick_delete_t private_quick_delete_t
Definition at line 42 of file quick_delete.c.
Function Documentation
static bool delete_child (private_quick_delete_t * this, protocol_id_t protocol, u_int32_t spi, bool remote_close) static
Delete the specified CHILD_SA, if found
Definition at line 88 of file quick_delete.c.
References ACTION_RESTART, ACTION_ROUTE, daemon_t::bus, charon, CHILD_DELETING, CHILD_REKEYED, bus_t::child_updown, child_sa_t::create_ts_enumerator, DBG0, DBG_IKE, linked_list_t::destroy, child_cfg_t::destroy, FALSE, child_sa_t::get_close_action, child_sa_t::get_config, child_sa_t::get_name, child_cfg_t::get_ref, child_sa_t::get_reqid, child_sa_t::get_spi, child_sa_t::get_state, child_sa_t::get_unique_id, child_sa_t::get_usestats, trap_manager_t::install, linked_list_create_from_enumerator(), child_sa_t::set_state, daemon_t::traps, and TRUE.
Referenced by METHOD().
 {
     u_int64_t bytes_in, bytes_out;
     child_sa_t *child_sa;
     linked_list_t *my_ts, *other_ts;
     child_cfg_t *child_cfg;
     bool rekeyed;
     child_sa = this->ike_sa->get_child_sa(this->ike_sa, protocol, spi, TRUE);
     if (!child_sa)
     {   /* fallback and check for outbound SA */
         child_sa = this->ike_sa->get_child_sa(this->ike_sa, protocol, spi, FALSE);
         if (!child_sa)
         {
             return FALSE;
         }
         this->spi = spi = child_sa->get_spi(child_sa, TRUE);
     }
     rekeyed = child_sa->get_state(child_sa) == CHILD_REKEYED;
     child_sa->set_state(child_sa, CHILD_DELETING);
     my_ts = linked_list_create_from_enumerator(
                             child_sa->create_ts_enumerator(child_sa, TRUE));
     other_ts = linked_list_create_from_enumerator(
                             child_sa->create_ts_enumerator(child_sa, FALSE));
     if (this->expired)
     {
         DBG0(DBG_IKE, "closing expired CHILD_SA %s{%d} "
              "with SPIs %.8x_i %.8x_o and TS %#R === %#R",
              child_sa->get_name(child_sa), child_sa->get_unique_id(child_sa),
              ntohl(child_sa->get_spi(child_sa, TRUE)),
              ntohl(child_sa->get_spi(child_sa, FALSE)), my_ts, other_ts);
     }
     else
     {
         child_sa->get_usestats(child_sa, TRUE, NULL, &bytes_in, NULL);
         child_sa->get_usestats(child_sa, FALSE, NULL, &bytes_out, NULL);
         DBG0(DBG_IKE, "closing CHILD_SA %s{%d} with SPIs "
              "%.8x_i (%llu bytes) %.8x_o (%llu bytes) and TS %#R === %#R",
              child_sa->get_name(child_sa), child_sa->get_unique_id(child_sa),
              ntohl(child_sa->get_spi(child_sa, TRUE)), bytes_in,
              ntohl(child_sa->get_spi(child_sa, FALSE)), bytes_out,
              my_ts, other_ts);
     }
     my_ts->destroy(my_ts);
     other_ts->destroy(other_ts);
     if (!rekeyed)
     {
         charon->bus->child_updown(charon->bus, child_sa, FALSE);
         if (remote_close)
         {
             child_cfg = child_sa->get_config(child_sa);
             child_cfg->get_ref(child_cfg);
             switch (child_sa->get_close_action(child_sa))
             {
                 case ACTION_RESTART:
                     child_cfg->get_ref(child_cfg);
                     this->ike_sa->initiate(this->ike_sa, child_cfg,
                                     child_sa->get_reqid(child_sa), NULL, NULL);
                     break;
                 case ACTION_ROUTE:
                     charon->traps->install(charon->traps,
                                     this->ike_sa->get_peer_cfg(this->ike_sa),
                                     child_cfg, child_sa->get_reqid(child_sa));
                     break;
                 default:
                     break;
             }
             child_cfg->destroy(child_cfg);
         }
     }
     this->ike_sa->destroy_child_sa(this->ike_sa, protocol, spi);
     return TRUE;
 }
METHOD (task_t , build_i , status_t , private_quick_delete_t * this, message_t * message)
Definition at line 170 of file quick_delete.c.
References message_t::add_payload, delete_payload_t::add_spi, ALREADY_DONE, DBG1, DBG_IKE, delete_child(), delete_payload_create(), FALSE, delete_payload_t::payload_interface, PLV1_DELETE, protocol, protocol_id_names, SUCCESS, and TASK_QUEUE_ACTIVE.
 {
     if (delete_child(this, this->protocol, this->spi, FALSE) || this->force)
     {
         delete_payload_t *delete_payload;
         DBG1(DBG_IKE, "sending DELETE for %N CHILD_SA with SPI %.8x",
              protocol_id_names, this->protocol, ntohl(this->spi));
         delete_payload = delete_payload_create(PLV1_DELETE, this->protocol);
         delete_payload->add_spi(delete_payload, this->spi);
         message->add_payload(message, &delete_payload->payload_interface);
         return SUCCESS;
     }
     this->ike_sa->flush_queue(this->ike_sa, TASK_QUEUE_ACTIVE);
     return ALREADY_DONE;
 }
METHOD (task_t , process_i , status_t , private_quick_delete_t * this, message_t * message)
Definition at line 190 of file quick_delete.c.
References FAILED.
 {
     return FAILED;
 }
METHOD (task_t , process_r , status_t , private_quick_delete_t * this, message_t * message)
Definition at line 196 of file quick_delete.c.
References message_t::create_payload_enumerator, delete_payload_t::create_spi_enumerator, DBG1, DBG_IKE, delete_child(), enumerator_t::destroy, enumerator_t::enumerate, delete_payload_t::get_protocol_id, payload_t::get_type, PLV1_DELETE, PROTO_AH, PROTO_ESP, protocol, protocol_id_names, SUCCESS, and TRUE.
 {
     enumerator_t *payloads, *spis;
     payload_t *payload;
     delete_payload_t *delete_payload;
     protocol_id_t protocol;
     u_int32_t spi;
     payloads = message->create_payload_enumerator(message);
     while (payloads->enumerate(payloads, &payload))
     {
         if (payload->get_type(payload) == PLV1_DELETE)
         {
             delete_payload = (delete_payload_t*)payload;
             protocol = delete_payload->get_protocol_id(delete_payload);
             if (protocol != PROTO_ESP && protocol != PROTO_AH)
             {
                 continue;
             }
             spis = delete_payload->create_spi_enumerator(delete_payload);
             while (spis->enumerate(spis, &spi))
             {
                 DBG1(DBG_IKE, "received DELETE for %N CHILD_SA with SPI %.8x",
                      protocol_id_names, protocol, ntohl(spi));
                 if (!delete_child(this, protocol, spi, TRUE))
                 {
                     DBG1(DBG_IKE, "CHILD_SA not found, ignored");
                     continue;
                 }
             }
             spis->destroy(spis);
         }
     }
     payloads->destroy(payloads);
     return SUCCESS;
 }
METHOD (task_t , build_r , status_t , private_quick_delete_t * this, message_t * message)
Definition at line 235 of file quick_delete.c.
References FAILED.
 {
     return FAILED;
 }
METHOD (task_t , get_type , task_type_t , private_quick_delete_t * this)
Definition at line 241 of file quick_delete.c.
References TASK_QUICK_DELETE.
 {
     return TASK_QUICK_DELETE;
 }
METHOD (task_t , migrate , void , private_quick_delete_t * this, ike_sa_t * ike_sa)
Definition at line 247 of file quick_delete.c.
 {
     this->ike_sa = ike_sa;
 }
METHOD (task_t , destroy , void , private_quick_delete_t * this)
Definition at line 253 of file quick_delete.c.
References free().
 {
     free(this);
 }