strongSwan: aesni_ctr.c File Reference
aesni_ctr.c File Reference
#include "aesni_ctr.h"
#include "aesni_key.h"
#include <tmmintrin.h>
Classes
struct private_aesni_ctr_t
Macros
#define CTR_CRYPT_PARALLELISM 4
Typedefs
typedef struct private_aesni_ctr_t private_aesni_ctr_t
typedef void(* aesni_ctr_fn_t)(private_aesni_ctr_t *, size_t, u_char *, u_char *)
Functions
static __m128i increment_be (__m128i x)
static void encrypt_ctr128 (private_aesni_ctr_t *this, size_t len, u_char *in, u_char *out)
static void encrypt_ctr192 (private_aesni_ctr_t *this, size_t len, u_char *in, u_char *out)
static void encrypt_ctr256 (private_aesni_ctr_t *this, size_t len, u_char *in, u_char *out)
METHOD (crypter_t, crypt, bool, private_aesni_ctr_t *this, chunk_t in, chunk_t iv, chunk_t *out)
METHOD (crypter_t, get_block_size, size_t, private_aesni_ctr_t *this)
METHOD (crypter_t, get_iv_size, size_t, private_aesni_ctr_t *this)
METHOD (crypter_t, get_key_size, size_t, private_aesni_ctr_t *this)
METHOD (crypter_t, set_key, bool, private_aesni_ctr_t *this, chunk_t key)
METHOD (crypter_t, destroy, void, private_aesni_ctr_t *this)
aesni_ctr_t * aesni_ctr_create (encryption_algorithm_t algo, size_t key_size)
Macro Definition Documentation
#define CTR_CRYPT_PARALLELISM 4
Pipeline parallelism we use for CTR en/decryption
Definition at line 24 of file aesni_ctr.c.
Referenced by encrypt_ctr128(), encrypt_ctr192(), and encrypt_ctr256().
Typedef Documentation
typedef void(* aesni_ctr_fn_t)(private_aesni_ctr_t *, size_t, u_char *, u_char *)
CTR en/decryption method type
Definition at line 31 of file aesni_ctr.c.
typedef struct private_aesni_ctr_t private_aesni_ctr_t
Definition at line 26 of file aesni_ctr.c.
Function Documentation
static void encrypt_ctr128 (private_aesni_ctr_t * this, size_t len, u_char * in, u_char * out) static
AES-128 CTR encryption
Definition at line 87 of file aesni_ctr.c.
References AES_BLOCK_SIZE, b, CTR_CRYPT_PARALLELISM, increment_be(), private_aesni_ctr_t::key, memcpy, and memset.
Referenced by aesni_ctr_create().
 {
     __m128i t1, t2, t3, t4;
     __m128i d1, d2, d3, d4;
     __m128i *ks, state, b, *bi, *bo;
     u_int i, blocks, pblocks, rem;
     state = _mm_load_si128((__m128i*)&this->state);
     blocks = len / AES_BLOCK_SIZE;
     pblocks = blocks - (blocks % CTR_CRYPT_PARALLELISM);
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < pblocks; i += CTR_CRYPT_PARALLELISM)
     {
         d1 = _mm_loadu_si128(bi + i + 0);
         d2 = _mm_loadu_si128(bi + i + 1);
         d3 = _mm_loadu_si128(bi + i + 2);
         d4 = _mm_loadu_si128(bi + i + 3);
         t1 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t2 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t3 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t4 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t2 = _mm_aesenc_si128(t2, ks[1]);
         t3 = _mm_aesenc_si128(t3, ks[1]);
         t4 = _mm_aesenc_si128(t4, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t2 = _mm_aesenc_si128(t2, ks[2]);
         t3 = _mm_aesenc_si128(t3, ks[2]);
         t4 = _mm_aesenc_si128(t4, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t2 = _mm_aesenc_si128(t2, ks[3]);
         t3 = _mm_aesenc_si128(t3, ks[3]);
         t4 = _mm_aesenc_si128(t4, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t2 = _mm_aesenc_si128(t2, ks[4]);
         t3 = _mm_aesenc_si128(t3, ks[4]);
         t4 = _mm_aesenc_si128(t4, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t2 = _mm_aesenc_si128(t2, ks[5]);
         t3 = _mm_aesenc_si128(t3, ks[5]);
         t4 = _mm_aesenc_si128(t4, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t2 = _mm_aesenc_si128(t2, ks[6]);
         t3 = _mm_aesenc_si128(t3, ks[6]);
         t4 = _mm_aesenc_si128(t4, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t2 = _mm_aesenc_si128(t2, ks[7]);
         t3 = _mm_aesenc_si128(t3, ks[7]);
         t4 = _mm_aesenc_si128(t4, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t2 = _mm_aesenc_si128(t2, ks[8]);
         t3 = _mm_aesenc_si128(t3, ks[8]);
         t4 = _mm_aesenc_si128(t4, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t2 = _mm_aesenc_si128(t2, ks[9]);
         t3 = _mm_aesenc_si128(t3, ks[9]);
         t4 = _mm_aesenc_si128(t4, ks[9]);
         t1 = _mm_aesenclast_si128(t1, ks[10]);
         t2 = _mm_aesenclast_si128(t2, ks[10]);
         t3 = _mm_aesenclast_si128(t3, ks[10]);
         t4 = _mm_aesenclast_si128(t4, ks[10]);
         t1 = _mm_xor_si128(t1, d1);
         t2 = _mm_xor_si128(t2, d2);
         t3 = _mm_xor_si128(t3, d3);
         t4 = _mm_xor_si128(t4, d4);
         _mm_storeu_si128(bo + i + 0, t1);
         _mm_storeu_si128(bo + i + 1, t2);
         _mm_storeu_si128(bo + i + 2, t3);
         _mm_storeu_si128(bo + i + 3, t4);
     }
     for (i = pblocks; i < blocks; i++)
     {
         d1 = _mm_loadu_si128(bi + i);
         t1 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t1 = _mm_aesenclast_si128(t1, ks[10]);
         t1 = _mm_xor_si128(t1, d1);
         _mm_storeu_si128(bo + i, t1);
     }
     if (rem)
     {
         memset(&b, 0, sizeof(b));
         memcpy(&b, bi + blocks, rem);
         d1 = _mm_loadu_si128(&b);
         t1 = _mm_xor_si128(state, ks[0]);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t1 = _mm_aesenclast_si128(t1, ks[10]);
         t1 = _mm_xor_si128(t1, d1);
         _mm_storeu_si128(&b, t1);
         memcpy(bo + blocks, &b, rem);
     }
 }
static void encrypt_ctr192 (private_aesni_ctr_t * this, size_t len, u_char * in, u_char * out) static
AES-192 CTR encryption
Definition at line 222 of file aesni_ctr.c.
References AES_BLOCK_SIZE, b, CTR_CRYPT_PARALLELISM, increment_be(), private_aesni_ctr_t::key, memcpy, and memset.
Referenced by aesni_ctr_create().
 {
     __m128i t1, t2, t3, t4;
     __m128i d1, d2, d3, d4;
     __m128i *ks, state, b, *bi, *bo;
     u_int i, blocks, pblocks, rem;
     state = _mm_load_si128((__m128i*)&this->state);
     blocks = len / AES_BLOCK_SIZE;
     pblocks = blocks - (blocks % CTR_CRYPT_PARALLELISM);
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < pblocks; i += CTR_CRYPT_PARALLELISM)
     {
         d1 = _mm_loadu_si128(bi + i + 0);
         d2 = _mm_loadu_si128(bi + i + 1);
         d3 = _mm_loadu_si128(bi + i + 2);
         d4 = _mm_loadu_si128(bi + i + 3);
         t1 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t2 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t3 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t4 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t2 = _mm_aesenc_si128(t2, ks[1]);
         t3 = _mm_aesenc_si128(t3, ks[1]);
         t4 = _mm_aesenc_si128(t4, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t2 = _mm_aesenc_si128(t2, ks[2]);
         t3 = _mm_aesenc_si128(t3, ks[2]);
         t4 = _mm_aesenc_si128(t4, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t2 = _mm_aesenc_si128(t2, ks[3]);
         t3 = _mm_aesenc_si128(t3, ks[3]);
         t4 = _mm_aesenc_si128(t4, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t2 = _mm_aesenc_si128(t2, ks[4]);
         t3 = _mm_aesenc_si128(t3, ks[4]);
         t4 = _mm_aesenc_si128(t4, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t2 = _mm_aesenc_si128(t2, ks[5]);
         t3 = _mm_aesenc_si128(t3, ks[5]);
         t4 = _mm_aesenc_si128(t4, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t2 = _mm_aesenc_si128(t2, ks[6]);
         t3 = _mm_aesenc_si128(t3, ks[6]);
         t4 = _mm_aesenc_si128(t4, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t2 = _mm_aesenc_si128(t2, ks[7]);
         t3 = _mm_aesenc_si128(t3, ks[7]);
         t4 = _mm_aesenc_si128(t4, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t2 = _mm_aesenc_si128(t2, ks[8]);
         t3 = _mm_aesenc_si128(t3, ks[8]);
         t4 = _mm_aesenc_si128(t4, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t2 = _mm_aesenc_si128(t2, ks[9]);
         t3 = _mm_aesenc_si128(t3, ks[9]);
         t4 = _mm_aesenc_si128(t4, ks[9]);
         t1 = _mm_aesenc_si128(t1, ks[10]);
         t2 = _mm_aesenc_si128(t2, ks[10]);
         t3 = _mm_aesenc_si128(t3, ks[10]);
         t4 = _mm_aesenc_si128(t4, ks[10]);
         t1 = _mm_aesenc_si128(t1, ks[11]);
         t2 = _mm_aesenc_si128(t2, ks[11]);
         t3 = _mm_aesenc_si128(t3, ks[11]);
         t4 = _mm_aesenc_si128(t4, ks[11]);
         t1 = _mm_aesenclast_si128(t1, ks[12]);
         t2 = _mm_aesenclast_si128(t2, ks[12]);
         t3 = _mm_aesenclast_si128(t3, ks[12]);
         t4 = _mm_aesenclast_si128(t4, ks[12]);
         t1 = _mm_xor_si128(t1, d1);
         t2 = _mm_xor_si128(t2, d2);
         t3 = _mm_xor_si128(t3, d3);
         t4 = _mm_xor_si128(t4, d4);
         _mm_storeu_si128(bo + i + 0, t1);
         _mm_storeu_si128(bo + i + 1, t2);
         _mm_storeu_si128(bo + i + 2, t3);
         _mm_storeu_si128(bo + i + 3, t4);
     }
     for (i = pblocks; i < blocks; i++)
     {
         d1 = _mm_loadu_si128(bi + i);
         t1 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t1 = _mm_aesenc_si128(t1, ks[10]);
         t1 = _mm_aesenc_si128(t1, ks[11]);
         t1 = _mm_aesenclast_si128(t1, ks[12]);
         t1 = _mm_xor_si128(t1, d1);
         _mm_storeu_si128(bo + i, t1);
     }
     if (rem)
     {
         memset(&b, 0, sizeof(b));
         memcpy(&b, bi + blocks, rem);
         d1 = _mm_loadu_si128(&b);
         t1 = _mm_xor_si128(state, ks[0]);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t1 = _mm_aesenc_si128(t1, ks[10]);
         t1 = _mm_aesenc_si128(t1, ks[11]);
         t1 = _mm_aesenclast_si128(t1, ks[12]);
         t1 = _mm_xor_si128(t1, d1);
         _mm_storeu_si128(&b, t1);
         memcpy(bo + blocks, &b, rem);
     }
 }
static void encrypt_ctr256 (private_aesni_ctr_t * this, size_t len, u_char * in, u_char * out) static
AES-256 CTR encryption
Definition at line 369 of file aesni_ctr.c.
References AES_BLOCK_SIZE, b, CTR_CRYPT_PARALLELISM, increment_be(), private_aesni_ctr_t::key, memcpy, and memset.
Referenced by aesni_ctr_create().
 {
     __m128i t1, t2, t3, t4;
     __m128i d1, d2, d3, d4;
     __m128i *ks, state, b, *bi, *bo;
     u_int i, blocks, pblocks, rem;
     state = _mm_load_si128((__m128i*)&this->state);
     blocks = len / AES_BLOCK_SIZE;
     pblocks = blocks - (blocks % CTR_CRYPT_PARALLELISM);
     rem = len % AES_BLOCK_SIZE;
     bi = (__m128i*)in;
     bo = (__m128i*)out;
     ks = this->key->schedule;
     for (i = 0; i < pblocks; i += CTR_CRYPT_PARALLELISM)
     {
         d1 = _mm_loadu_si128(bi + i + 0);
         d2 = _mm_loadu_si128(bi + i + 1);
         d3 = _mm_loadu_si128(bi + i + 2);
         d4 = _mm_loadu_si128(bi + i + 3);
         t1 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t2 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t3 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t4 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t2 = _mm_aesenc_si128(t2, ks[1]);
         t3 = _mm_aesenc_si128(t3, ks[1]);
         t4 = _mm_aesenc_si128(t4, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t2 = _mm_aesenc_si128(t2, ks[2]);
         t3 = _mm_aesenc_si128(t3, ks[2]);
         t4 = _mm_aesenc_si128(t4, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t2 = _mm_aesenc_si128(t2, ks[3]);
         t3 = _mm_aesenc_si128(t3, ks[3]);
         t4 = _mm_aesenc_si128(t4, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t2 = _mm_aesenc_si128(t2, ks[4]);
         t3 = _mm_aesenc_si128(t3, ks[4]);
         t4 = _mm_aesenc_si128(t4, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t2 = _mm_aesenc_si128(t2, ks[5]);
         t3 = _mm_aesenc_si128(t3, ks[5]);
         t4 = _mm_aesenc_si128(t4, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t2 = _mm_aesenc_si128(t2, ks[6]);
         t3 = _mm_aesenc_si128(t3, ks[6]);
         t4 = _mm_aesenc_si128(t4, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t2 = _mm_aesenc_si128(t2, ks[7]);
         t3 = _mm_aesenc_si128(t3, ks[7]);
         t4 = _mm_aesenc_si128(t4, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t2 = _mm_aesenc_si128(t2, ks[8]);
         t3 = _mm_aesenc_si128(t3, ks[8]);
         t4 = _mm_aesenc_si128(t4, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t2 = _mm_aesenc_si128(t2, ks[9]);
         t3 = _mm_aesenc_si128(t3, ks[9]);
         t4 = _mm_aesenc_si128(t4, ks[9]);
         t1 = _mm_aesenc_si128(t1, ks[10]);
         t2 = _mm_aesenc_si128(t2, ks[10]);
         t3 = _mm_aesenc_si128(t3, ks[10]);
         t4 = _mm_aesenc_si128(t4, ks[10]);
         t1 = _mm_aesenc_si128(t1, ks[11]);
         t2 = _mm_aesenc_si128(t2, ks[11]);
         t3 = _mm_aesenc_si128(t3, ks[11]);
         t4 = _mm_aesenc_si128(t4, ks[11]);
         t1 = _mm_aesenc_si128(t1, ks[12]);
         t2 = _mm_aesenc_si128(t2, ks[12]);
         t3 = _mm_aesenc_si128(t3, ks[12]);
         t4 = _mm_aesenc_si128(t4, ks[12]);
         t1 = _mm_aesenc_si128(t1, ks[13]);
         t2 = _mm_aesenc_si128(t2, ks[13]);
         t3 = _mm_aesenc_si128(t3, ks[13]);
         t4 = _mm_aesenc_si128(t4, ks[13]);
         t1 = _mm_aesenclast_si128(t1, ks[14]);
         t2 = _mm_aesenclast_si128(t2, ks[14]);
         t3 = _mm_aesenclast_si128(t3, ks[14]);
         t4 = _mm_aesenclast_si128(t4, ks[14]);
         t1 = _mm_xor_si128(t1, d1);
         t2 = _mm_xor_si128(t2, d2);
         t3 = _mm_xor_si128(t3, d3);
         t4 = _mm_xor_si128(t4, d4);
         _mm_storeu_si128(bo + i + 0, t1);
         _mm_storeu_si128(bo + i + 1, t2);
         _mm_storeu_si128(bo + i + 2, t3);
         _mm_storeu_si128(bo + i + 3, t4);
     }
     for (i = pblocks; i < blocks; i++)
     {
         d1 = _mm_loadu_si128(bi + i);
         t1 = _mm_xor_si128(state, ks[0]);
         state = increment_be(state);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t1 = _mm_aesenc_si128(t1, ks[10]);
         t1 = _mm_aesenc_si128(t1, ks[11]);
         t1 = _mm_aesenc_si128(t1, ks[12]);
         t1 = _mm_aesenc_si128(t1, ks[13]);
         t1 = _mm_aesenclast_si128(t1, ks[14]);
         t1 = _mm_xor_si128(t1, d1);
         _mm_storeu_si128(bo + i, t1);
     }
     if (rem)
     {
         memset(&b, 0, sizeof(b));
         memcpy(&b, bi + blocks, rem);
         d1 = _mm_loadu_si128(&b);
         t1 = _mm_xor_si128(state, ks[0]);
         t1 = _mm_aesenc_si128(t1, ks[1]);
         t1 = _mm_aesenc_si128(t1, ks[2]);
         t1 = _mm_aesenc_si128(t1, ks[3]);
         t1 = _mm_aesenc_si128(t1, ks[4]);
         t1 = _mm_aesenc_si128(t1, ks[5]);
         t1 = _mm_aesenc_si128(t1, ks[6]);
         t1 = _mm_aesenc_si128(t1, ks[7]);
         t1 = _mm_aesenc_si128(t1, ks[8]);
         t1 = _mm_aesenc_si128(t1, ks[9]);
         t1 = _mm_aesenc_si128(t1, ks[10]);
         t1 = _mm_aesenc_si128(t1, ks[11]);
         t1 = _mm_aesenc_si128(t1, ks[12]);
         t1 = _mm_aesenc_si128(t1, ks[13]);
         t1 = _mm_aesenclast_si128(t1, ks[14]);
         t1 = _mm_xor_si128(t1, d1);
         _mm_storeu_si128(&b, t1);
         memcpy(bo + blocks, &b, rem);
     }
 }
static __m128i increment_be (__m128i x) inline static
Do big-endian increment on x
Definition at line 71 of file aesni_ctr.c.
Referenced by encrypt_ctr128(), encrypt_ctr192(), and encrypt_ctr256().
 {
     __m128i swap;
     swap = _mm_setr_epi8(15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0);
     x = _mm_shuffle_epi8(x, swap);
     x = _mm_add_epi64(x, _mm_set_epi32(0, 0, 0, 1));
     x = _mm_shuffle_epi8(x, swap);
     return x;
 }
METHOD (crypter_t , crypt , bool , private_aesni_ctr_t * this, chunk_t in, chunk_t iv, chunk_t * out)
Definition at line 525 of file aesni_ctr.c.
References chunk_alloc, private_aesni_ctr_t::crypt, FALSE, private_aesni_ctr_t::key, chunk_t::len, memcpy, chunk_t::ptr, and TRUE.
 {
     u_char *buf;
     if (!this->key || iv.len != sizeof(this->state.iv))
     {
         return FALSE;
     }
     memcpy(this->state.iv, iv.ptr, sizeof(this->state.iv));
     this->state.counter = htonl(1);
     buf = in.ptr;
     if (out)
     {
         *out = chunk_alloc(in.len);
         buf = out->ptr;
     }
     this->crypt(this, in.len, in.ptr, buf);
     return TRUE;
 }
METHOD (crypter_t , get_block_size , size_t , private_aesni_ctr_t * this)
Definition at line 547 of file aesni_ctr.c.
 {
     return 1;
 }
METHOD (crypter_t , get_iv_size , size_t , private_aesni_ctr_t * this)
Definition at line 553 of file aesni_ctr.c.
 {
     return sizeof(this->state.iv);
 }
METHOD (crypter_t , get_key_size , size_t , private_aesni_ctr_t * this)
Definition at line 559 of file aesni_ctr.c.
References private_aesni_ctr_t::key_size.
 {
     return this->key_size + sizeof(this->state.nonce);
 }
METHOD (crypter_t , set_key , bool , private_aesni_ctr_t * this, chunk_t key)
Definition at line 565 of file aesni_ctr.c.
References aesni_key_create(), DESTROY_IF, FALSE, private_aesni_ctr_t::key, chunk_t::len, memcpy, chunk_t::ptr, and TRUE.
 {
     if (key.len != get_key_size(this))
     {
         return FALSE;
     }
     memcpy(this->state.nonce, key.ptr + key.len - sizeof(this->state.nonce),
            sizeof(this->state.nonce));
     key.len -= sizeof(this->state.nonce);
     DESTROY_IF(this->key);
     this->key = aesni_key_create(TRUE, key);
     return this->key;
 }
METHOD (crypter_t , destroy , void , private_aesni_ctr_t * this)
Definition at line 583 of file aesni_ctr.c.
References DESTROY_IF, free_align(), and private_aesni_ctr_t::key.
 {
     DESTROY_IF(this->key);
     free_align(this);
 }