strongSwan: chunk map
chunk map
tkm
Classes
struct tkm_chunk_map_t
Typedefs
typedef struct tkm_chunk_map_t tkm_chunk_map_t
Functions
tkm_chunk_map_t * tkm_chunk_map_create ()
Detailed Description
Typedef Documentation
typedef struct tkm_chunk_map_t tkm_chunk_map_t
Definition at line 28 of file tkm_chunk_map.h.
Function Documentation
tkm_chunk_map_t* tkm_chunk_map_create ()
Create a tkm chunk map instance.
Definition at line 154 of file tkm_chunk_map.c.
References chunk_equals_ptr(), hash(), hashtable_create(), INIT, rwlock_create(), and RWLOCK_TYPE_DEFAULT.
Referenced by START_TEST(), and tkm_init().
 {
     private_tkm_chunk_map_t *this;
     INIT(this,
         .public = {
             .insert = _insert,
             .get_id = _get_id,
             .remove = _remove_,
             .destroy = _destroy,
         },
         .lock = rwlock_create(RWLOCK_TYPE_DEFAULT),
         .mappings = hashtable_create((hashtable_hash_t)hash,
                                      (hashtable_equals_t)chunk_equals_ptr, 32),
     );
     return &this->public;
 }