strongSwan: cred_encoding_t Struct Reference
cred_encoding_t Struct Reference
cred_encoding
#include "cred_encoding.h"
Public Attributes
bool(* encode)(cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t *encoding,...)
void(* clear_cache)(cred_encoding_t *this, void *cache)
bool(* get_cache)(cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t *encoding)
void(* cache)(cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t encoding)
void(* add_encoder)(cred_encoding_t *this, cred_encoder_t encoder)
void(* remove_encoder)(cred_encoding_t *this, cred_encoder_t encoder)
void(* destroy)(cred_encoding_t *this)
Detailed Description
Credential encoding and fingerprinting facility.
Definition at line 158 of file cred_encoding.h.
Member Data Documentation
void(* cred_encoding_t::add_encoder)(cred_encoding_t *this, cred_encoder_t encoder)
Register a credential encoder function.
Parameters
encoder credential encoder function to add
Definition at line 214 of file cred_encoding.h.
Referenced by dnskey_plugin_create(), main(), pem_plugin_create(), pgp_plugin_create(), pkcs1_plugin_create(), and sshkey_plugin_create().
void(* cred_encoding_t::cache)(cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t encoding)
Cache a credential encoding created externally.
After calling cache(), the passed encoding is owned by the cred encoding facility.
Parameters
type format of the credential encoding
cache key to use for caching, as given to encode()
encoding encoding to cache, gets owned by this
Definition at line 206 of file cred_encoding.h.
Referenced by fingerprint_ecdsa(), METHOD(), openssl_ec_fingerprint(), and openssl_rsa_fingerprint().
void(* cred_encoding_t::clear_cache)(cred_encoding_t *this, void *cache)
Clear all cached encodings of a given cache key.
Parameters
cache key used in encode() for caching
Definition at line 183 of file cred_encoding.h.
Referenced by METHOD().
void(* cred_encoding_t::destroy)(cred_encoding_t *this)
Destroy a cred_encoding_t.
Definition at line 226 of file cred_encoding.h.
bool(* cred_encoding_t::encode)(cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t *encoding,...)
Encode a credential in a format using several parts, optional caching.
The variable argument list takes cred_encoding_part_t, followed by part specific arguments, terminated by CRED_PART_END. If a cache key is given, the returned encoding points to internal data: do not free or modify. If no cache key is given, the encoding is allocated and must be freed by the caller.
Parameters
type format the credential should be encoded to
cache key to use for caching, NULL to not cache
encoding encoding result, allocated if caching disabled
... list of (cred_encoding_part_t, data)
Returns
TRUE if encoding successful
Definition at line 175 of file cred_encoding.h.
Referenced by encode_ecdsa(), encode_rsa(), main(), METHOD(), openssl_rsa_fingerprint(), and pem_encoder_encode().
bool(* cred_encoding_t::get_cache)(cred_encoding_t *this, cred_encoding_type_t type, void *cache, chunk_t *encoding)
Check for a cached encoding.
Parameters
type format of the credential encoding
cache key to use for caching, as given to encode()
encoding encoding result, internal data
Returns
TRUE if cache entry found
Definition at line 193 of file cred_encoding.h.
Referenced by METHOD(), openssl_ec_fingerprint(), and openssl_rsa_fingerprint().
void(* cred_encoding_t::remove_encoder)(cred_encoding_t *this, cred_encoder_t encoder)
Unregister a previously registered credential encoder function.
Parameters
encoder credential encoder function to remove
Definition at line 221 of file cred_encoding.h.
Referenced by main(), and METHOD().
The documentation for this struct was generated from the following file:
cred_encoding.h