strongSwan: leak_detective_t Struct Reference
leak_detective_t Struct Reference
leak_detective
#include "leak_detective.h"
Public Attributes
void(* report)(leak_detective_t *this, bool detailed)
void(* set_report_cb)(leak_detective_t *this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void *user)
void(* usage)(leak_detective_t *this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void *user)
int(* leaks)(leak_detective_t *this)
bool(* set_state)(leak_detective_t *this, bool enabled)
void(* destroy)(leak_detective_t *this)
Detailed Description
Leak detective finds leaks and invalid frees using malloc hooks.
Todo:
Build an API for leak detective, allowing leak enumeration, statistics and dynamic whitelisting.
Definition at line 58 of file leak_detective.h.
Member Data Documentation
void(* leak_detective_t::destroy)(leak_detective_t *this)
Destroy a leak_detective instance.
Definition at line 105 of file leak_detective.h.
Referenced by library_deinit().
int(* leak_detective_t::leaks)(leak_detective_t *this)
Number of detected leaks.
Returns
number of leaks
Definition at line 92 of file leak_detective.h.
void(* leak_detective_t::report)(leak_detective_t *this, bool detailed)
Report leaks to the registered callback functions.
Parameters
detailed TRUE to resolve line/filename of leaks (slow)
Definition at line 65 of file leak_detective.h.
Referenced by library_deinit().
void(* leak_detective_t::set_report_cb)(leak_detective_t *this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void *user)
Set callback functions invoked when report() is called.
Parameters
cb callback invoked for each detected leak
scb summary callback invoked at end of report
user user data to supply to callbacks
Definition at line 74 of file leak_detective.h.
Referenced by post_test(), and pre_test().
bool(* leak_detective_t::set_state)(leak_detective_t *this, bool enabled)
Enable/disable leak detective hooks for the current thread.
Parameters
TRUE to enable, FALSE to disable
Returns
state active before calling set_state
Definition at line 100 of file leak_detective.h.
Referenced by free_no_ld(), get_strerror_buf(), load_suites(), set_leak_detective(), test_sighandler(), and testable_function_register().
void(* leak_detective_t::usage)(leak_detective_t *this, leak_detective_report_cb_t cb, leak_detective_summary_cb_t scb, void *user)
Report current memory usage using callback functions.
Parameters
cb callback invoked for each allocation
scb summary callback invoked at end of usage report
user user data to supply to callbacks
Definition at line 84 of file leak_detective.h.
Referenced by CALLBACK(), and stroke_memusage().
The documentation for this struct was generated from the following file:
leak_detective.h