strongSwan: ipsec_sa.c File Reference
ipsec_sa.c File Reference
#include "ipsec.h"
#include "ipsec_sa.h"
#include <library.h>
#include <utils/debug.h>
Classes
struct private_ipsec_sa_t
Typedefs
typedef struct private_ipsec_sa_t private_ipsec_sa_t
Functions
METHOD (ipsec_sa_t, get_source, host_t *, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, get_destination, host_t *, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, set_source, void, private_ipsec_sa_t *this, host_t *addr)
METHOD (ipsec_sa_t, set_destination, void, private_ipsec_sa_t *this, host_t *addr)
METHOD (ipsec_sa_t, get_spi, u_int32_t, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, get_reqid, u_int32_t, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, get_protocol, u_int8_t, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, get_lifetime, lifetime_cfg_t *, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, is_inbound, bool, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, get_esp_context, esp_context_t *, private_ipsec_sa_t *this)
METHOD (ipsec_sa_t, get_usestats, void, private_ipsec_sa_t *this, u_int64_t *bytes, u_int64_t *packets, time_t *time)
METHOD (ipsec_sa_t, expire, void, private_ipsec_sa_t *this, bool hard)
METHOD (ipsec_sa_t, update_usestats, void, private_ipsec_sa_t *this, u_int32_t bytes)
METHOD (ipsec_sa_t, match_by_spi_dst, bool, private_ipsec_sa_t *this, u_int32_t spi, host_t *dst)
METHOD (ipsec_sa_t, match_by_spi_src_dst, bool, private_ipsec_sa_t *this, u_int32_t spi, host_t *src, host_t *dst)
METHOD (ipsec_sa_t, match_by_reqid, bool, private_ipsec_sa_t *this, u_int32_t reqid, bool inbound)
METHOD (ipsec_sa_t, destroy, void, private_ipsec_sa_t *this)
ipsec_sa_t * ipsec_sa_create (u_int32_t spi, host_t *src, host_t *dst, u_int8_t protocol, u_int32_t reqid, mark_t mark, u_int32_t tfc, lifetime_cfg_t *lifetime, u_int16_t enc_alg, chunk_t enc_key, u_int16_t int_alg, chunk_t int_key, ipsec_mode_t mode, u_int16_t ipcomp, u_int16_t cpi, bool encap, bool esn, bool inbound)
Typedef Documentation
typedef struct private_ipsec_sa_t private_ipsec_sa_t
Definition at line 24 of file ipsec_sa.c.
Function Documentation
METHOD (ipsec_sa_t , get_source , host_t * , private_ipsec_sa_t * this)
Definition at line 109 of file ipsec_sa.c.
References src.
 {
     return this->src;
 }
METHOD (ipsec_sa_t , get_destination , host_t * , private_ipsec_sa_t * this)
Definition at line 115 of file ipsec_sa.c.
References dst.
 {
     return this->dst;
 }
METHOD (ipsec_sa_t , set_source , void , private_ipsec_sa_t * this, host_t * addr)
Definition at line 121 of file ipsec_sa.c.
References host_t::clone, and src.
 {
     this->src->destroy(this->src);
     this->src = addr->clone(addr);
 }
METHOD (ipsec_sa_t , set_destination , void , private_ipsec_sa_t * this, host_t * addr)
Definition at line 128 of file ipsec_sa.c.
References host_t::clone, and dst.
 {
     this->dst->destroy(this->dst);
     this->dst = addr->clone(addr);
 }
METHOD (ipsec_sa_t , get_spi , u_int32_t , private_ipsec_sa_t * this)
Definition at line 135 of file ipsec_sa.c.
 {
     return this->spi;
 }
METHOD (ipsec_sa_t , get_reqid , u_int32_t , private_ipsec_sa_t * this)
Definition at line 141 of file ipsec_sa.c.
 {
     return this->reqid;
 }
METHOD (ipsec_sa_t , get_protocol , u_int8_t , private_ipsec_sa_t * this)
Definition at line 147 of file ipsec_sa.c.
References protocol.
 {
     return this->protocol;
 }
METHOD (ipsec_sa_t , get_lifetime , lifetime_cfg_t * , private_ipsec_sa_t * this)
Definition at line 153 of file ipsec_sa.c.
 {
     return &this->lifetime;
 }
METHOD (ipsec_sa_t , is_inbound , bool , private_ipsec_sa_t * this)
Definition at line 159 of file ipsec_sa.c.
 {
     return this->inbound;
 }
METHOD (ipsec_sa_t , get_esp_context , esp_context_t * , private_ipsec_sa_t * this)
Definition at line 165 of file ipsec_sa.c.
 {
     return this->esp_context;
 }
METHOD (ipsec_sa_t , get_usestats , void , private_ipsec_sa_t * this, u_int64_t * bytes, u_int64_t * packets, time_t * time)
Definition at line 171 of file ipsec_sa.c.
 {
     if (bytes)
     {
         *bytes = this->use.bytes;
     }
     if (packets)
     {
         *packets = this->use.packets;
     }
     if (time)
     {
         *time = this->use.time;
     }
 }
METHOD (ipsec_sa_t , expire , void , private_ipsec_sa_t * this, bool hard)
Definition at line 189 of file ipsec_sa.c.
References ipsec_t::events, ipsec_event_relay_t::expire, FALSE, ipsec, and TRUE.
 {
     if (hard)
     {
         if (!this->hard_expired)
         {
             this->hard_expired = TRUE;
             ipsec->events->expire(ipsec->events, this->protocol, this->spi,
                                   this->dst, TRUE);
         }
     }
     else
     {
         if (!this->hard_expired && !this->soft_expired)
         {
             this->soft_expired = TRUE;
             ipsec->events->expire(ipsec->events, this->protocol, this->spi,
                                   this->dst, FALSE);
         }
     }
 }
METHOD (ipsec_sa_t , update_usestats , void , private_ipsec_sa_t * this, u_int32_t bytes)
Definition at line 212 of file ipsec_sa.c.
References bytes, expire(), FALSE, time_monotonic(), and TRUE.
 {
     this->use.time = time_monotonic(NULL);
     this->use.packets++;
     this->use.bytes += bytes;
     if (this->lifetime.packets.life &&
         this->use.packets >= this->lifetime.packets.life)
     {
         return expire(this, TRUE);
     }
     if (this->lifetime.bytes.life &&
         this->use.bytes >= this->lifetime.bytes.life)
     {
         return expire(this, TRUE);
     }
     if (this->lifetime.packets.rekey &&
         this->use.packets >= this->lifetime.packets.rekey)
     {
         return expire(this, FALSE);
     }
     if (this->lifetime.bytes.rekey &&
         this->use.bytes >= this->lifetime.bytes.rekey)
     {
         return expire(this, FALSE);
     }
 }
METHOD (ipsec_sa_t , match_by_spi_dst , bool , private_ipsec_sa_t * this, u_int32_t spi, host_t * dst)
Definition at line 241 of file ipsec_sa.c.
References host_t::ip_equals.
 {
     return this->spi == spi && this->dst->ip_equals(this->dst, dst) &&
            !this->hard_expired;
 }
METHOD (ipsec_sa_t , match_by_spi_src_dst , bool , private_ipsec_sa_t * this, u_int32_t spi, host_t * src, host_t * dst)
Definition at line 248 of file ipsec_sa.c.
References host_t::ip_equals.
 {
     return this->spi == spi && this->src->ip_equals(this->src, src) &&
            this->dst->ip_equals(this->dst, dst);
 }
METHOD (ipsec_sa_t , match_by_reqid , bool , private_ipsec_sa_t * this, u_int32_t reqid, bool inbound)
Definition at line 255 of file ipsec_sa.c.
 {
     return this->reqid == reqid && this->inbound == inbound &&
            !this->hard_expired;
 }
METHOD (ipsec_sa_t , destroy , void , private_ipsec_sa_t * this)
Definition at line 262 of file ipsec_sa.c.
References DESTROY_IF, dst, free(), and src.
 {
     this->src->destroy(this->src);
     this->dst->destroy(this->dst);
     DESTROY_IF(this->esp_context);
     free(this);
 }