strongSwan: ccm_aead.c File Reference
ccm_aead.c File Reference
#include "ccm_aead.h"
#include <crypto/iv/iv_gen_seq.h>
Classes
struct private_ccm_aead_t
Macros
#define BLOCK_SIZE 16
#define SALT_SIZE 3
#define IV_SIZE 8
#define NONCE_SIZE (SALT_SIZE + IV_SIZE) /* 11 */
#define Q_SIZE (BLOCK_SIZE - NONCE_SIZE - 1) /* 4 */
Typedefs
typedef struct private_ccm_aead_t private_ccm_aead_t
Functions
struct __attribute__ ((packed))
static void build_b0 (private_ccm_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, char *out)
static void build_ctr (private_ccm_aead_t *this, u_int32_t i, chunk_t iv, char *out)
static bool crypt_data (private_ccm_aead_t *this, chunk_t iv, chunk_t in, chunk_t out)
static bool crypt_icv (private_ccm_aead_t *this, chunk_t iv, char *icv)
static bool create_icv (private_ccm_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, char *icv)
static bool verify_icv (private_ccm_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, char *icv)
METHOD (aead_t, encrypt, bool, private_ccm_aead_t *this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t *encrypted)
METHOD (aead_t, decrypt, bool, private_ccm_aead_t *this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t *plain)
METHOD (aead_t, get_block_size, size_t, private_ccm_aead_t *this)
METHOD (aead_t, get_icv_size, size_t, private_ccm_aead_t *this)
METHOD (aead_t, get_iv_size, size_t, private_ccm_aead_t *this)
METHOD (aead_t, get_iv_gen, iv_gen_t *, private_ccm_aead_t *this)
METHOD (aead_t, get_key_size, size_t, private_ccm_aead_t *this)
METHOD (aead_t, set_key, bool, private_ccm_aead_t *this, chunk_t key)
METHOD (aead_t, destroy, void, private_ccm_aead_t *this)
ccm_aead_t * ccm_aead_create (encryption_algorithm_t algo, size_t key_size, size_t salt_size)
Variables
b0_t
ctr_t
Macro Definition Documentation
#define BLOCK_SIZE 16
Definition at line 20 of file ccm_aead.c.
Referenced by create_icv(), crypt_data(), and crypt_icv().
#define IV_SIZE 8
Definition at line 22 of file ccm_aead.c.
Referenced by __attribute__(), build_b0(), build_ctr(), and METHOD().
#define NONCE_SIZE (SALT_SIZE + IV_SIZE) /* 11 */
Definition at line 23 of file ccm_aead.c.
#define Q_SIZE (BLOCK_SIZE - NONCE_SIZE - 1) /* 4 */
Definition at line 24 of file ccm_aead.c.
Referenced by __attribute__(), build_b0(), and build_ctr().
#define SALT_SIZE 3
Definition at line 21 of file ccm_aead.c.
Referenced by __attribute__(), build_b0(), build_ctr(), ccm_aead_create(), and METHOD().
Typedef Documentation
typedef struct private_ccm_aead_t private_ccm_aead_t
Definition at line 26 of file ccm_aead.c.
Function Documentation
static void build_b0 (private_ccm_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, char * out) static
Build the first block B0
Definition at line 103 of file ccm_aead.c.
References b0_t, htoun32(), IV_SIZE, chunk_t::len, memcpy, chunk_t::ptr, Q_SIZE, and SALT_SIZE.
Referenced by create_icv().
 {
     b0_t *block = (b0_t*)out;
     block->flags.reserved = 0;
     block->flags.assoc = assoc.len ? 1 : 0;
     block->flags.t_len = (this->icv_size - 2) / 2;
     block->flags.q_len = Q_SIZE - 1;
     memcpy(block->nonce.salt, this->salt, SALT_SIZE);
     memcpy(block->nonce.iv, iv.ptr, IV_SIZE);
     htoun32(block->q, plain.len);
 }
static void build_ctr (private_ccm_aead_t * this, u_int32_t i, chunk_t iv, char * out) static
Build a counter block for counter i
Definition at line 120 of file ccm_aead.c.
References ctr_t, htoun32(), IV_SIZE, memcpy, chunk_t::ptr, Q_SIZE, and SALT_SIZE.
Referenced by crypt_data(), and crypt_icv().
 {
     ctr_t *ctr = (ctr_t*)out;
     ctr->flags.reserved = 0;
     ctr->flags.zero = 0;
     ctr->flags.q_len = Q_SIZE - 1;
     memcpy(ctr->nonce.salt, this->salt, SALT_SIZE);
     memcpy(ctr->nonce.iv, iv.ptr, IV_SIZE);
     htoun32(ctr->i, i);
 }
static bool create_icv (private_ccm_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, char * icv) static
Create the ICV
Definition at line 190 of file ccm_aead.c.
References BLOCK_SIZE, build_b0(), chunk_alloc, chunk_from_thing, crypt_icv(), crypter, FALSE, free(), htoun16(), chunk_t::len, len, memcpy, memset, chunk_t::ptr, and r.
Referenced by METHOD(), and verify_icv().
 {
     char zero[BLOCK_SIZE];
     chunk_t chunk;
     char *pos;
     int r, len;
     memset(zero, 0, BLOCK_SIZE);
     /* calculate number of blocks, including b0 */
     r = 1;
     if (assoc.len)
     {   /* assoc gets a 2 byte length header, gets padded to BLOCK_SIZE */
         r += (2 + assoc.len + BLOCK_SIZE - 1) / BLOCK_SIZE;
     }
     /* plain text gets padded to BLOCK_SIZE */
     r += (plain.len + BLOCK_SIZE - 1) / BLOCK_SIZE;
     /* concatenate data to a new chunk */
     chunk = chunk_alloc(r * BLOCK_SIZE);
     /* write control block */
     build_b0(this, plain, assoc, iv, chunk.ptr);
     pos = chunk.ptr + BLOCK_SIZE;
     /* append associated data, with length header */
     if (assoc.len)
     {
         /* currently we support two byte headers only (up to 2^16-2^8 bytes) */
         htoun16(pos, assoc.len);
         memcpy(pos + 2, assoc.ptr, assoc.len);
         pos += 2 + assoc.len;
         /* padding */
         len = (BLOCK_SIZE - ((2 + assoc.len) % BLOCK_SIZE)) % BLOCK_SIZE;
         memset(pos, 0, len);
         pos += len;
     }
     /* write plain data */
     memcpy(pos, plain.ptr, plain.len);
     pos += plain.len;
     /* padding */
     len = (BLOCK_SIZE - (plain.len % BLOCK_SIZE)) % BLOCK_SIZE;
     memset(pos, 0, len);
     /* encrypt inline with CBC, zero IV */
     if (!this->crypter->encrypt(this->crypter, chunk,
                                 chunk_from_thing(zero), NULL))
     {
         free(chunk.ptr);
         return FALSE;
     }
     /* copy last icv_size bytes as ICV to output */
     memcpy(icv, chunk.ptr + chunk.len - BLOCK_SIZE, this->icv_size);
     free(chunk.ptr);
     /* encrypt the ICV value */
     return crypt_icv(this, iv, icv);
 }
static bool crypt_data (private_ccm_aead_t * this, chunk_t iv, chunk_t in, chunk_t out) static
En-/Decrypt data
Definition at line 136 of file ccm_aead.c.
References BLOCK_SIZE, build_ctr(), chunk_from_thing, chunk_increment(), chunk_skip(), crypter, FALSE, chunk_t::len, memcpy, memset, memxor(), min, chunk_t::ptr, and TRUE.
Referenced by METHOD().
 {
     char ctr[BLOCK_SIZE];
     char zero[BLOCK_SIZE];
     char block[BLOCK_SIZE];
     build_ctr(this, 1, iv, ctr);
     memset(zero, 0, BLOCK_SIZE);
     while (in.len > 0)
     {
         memcpy(block, ctr, BLOCK_SIZE);
         if (!this->crypter->encrypt(this->crypter, chunk_from_thing(block),
                                     chunk_from_thing(zero), NULL))
         {
             return FALSE;
         }
         chunk_increment(chunk_from_thing(ctr));
         if (in.ptr != out.ptr)
         {
             memcpy(out.ptr, in.ptr, min(in.len, BLOCK_SIZE));
         }
         memxor(out.ptr, block, min(in.len, BLOCK_SIZE));
         in = chunk_skip(in, BLOCK_SIZE);
         out = chunk_skip(out, BLOCK_SIZE);
     }
     return TRUE;
 }
static bool crypt_icv (private_ccm_aead_t * this, chunk_t iv, char * icv) static
En-/Decrypt the ICV
Definition at line 170 of file ccm_aead.c.
References BLOCK_SIZE, build_ctr(), chunk_from_thing, crypter, FALSE, memset, memxor(), and TRUE.
Referenced by create_icv().
 {
     char ctr[BLOCK_SIZE];
     char zero[BLOCK_SIZE];
     build_ctr(this, 0, iv, ctr);
     memset(zero, 0, BLOCK_SIZE);
     if (!this->crypter->encrypt(this->crypter, chunk_from_thing(ctr),
                                 chunk_from_thing(zero), NULL))
     {
         return FALSE;
     }
     memxor(icv, ctr, this->icv_size);
     return TRUE;
 }
METHOD (aead_t , encrypt , bool , private_ccm_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, chunk_t * encrypted)
Definition at line 262 of file ccm_aead.c.
References chunk_alloc, create_icv(), crypt_data(), chunk_t::len, and chunk_t::ptr.
 {
     if (encrypted)
     {
         *encrypted = chunk_alloc(plain.len + this->icv_size);
         return create_icv(this, plain, assoc, iv, encrypted->ptr + plain.len) &&
                crypt_data(this, iv, plain, *encrypted);
     }
     return create_icv(this, plain, assoc, iv, plain.ptr + plain.len) &&
            crypt_data(this, iv, plain, plain);
 }
METHOD (aead_t , decrypt , bool , private_ccm_aead_t * this, chunk_t encrypted, chunk_t assoc, chunk_t iv, chunk_t * plain)
Definition at line 276 of file ccm_aead.c.
References chunk_alloc, crypt_data(), FALSE, chunk_t::len, chunk_t::ptr, and verify_icv().
 {
     if (encrypted.len < this->icv_size)
     {
         return FALSE;
     }
     encrypted.len -= this->icv_size;
     if (plain)
     {
         *plain = chunk_alloc(encrypted.len);
         return crypt_data(this, iv, encrypted, *plain) &&
                verify_icv(this, *plain, assoc, iv,
                           encrypted.ptr + encrypted.len);
     }
     return crypt_data(this, iv, encrypted, encrypted) &&
            verify_icv(this, encrypted, assoc, iv,
                       encrypted.ptr + encrypted.len);
 }
METHOD (aead_t , get_block_size , size_t , private_ccm_aead_t * this)
Definition at line 297 of file ccm_aead.c.
 {
     return 1;
 }
METHOD (aead_t , get_icv_size , size_t , private_ccm_aead_t * this)
Definition at line 303 of file ccm_aead.c.
 {
     return this->icv_size;
 }
METHOD (aead_t , get_iv_size , size_t , private_ccm_aead_t * this)
Definition at line 309 of file ccm_aead.c.
References IV_SIZE.
 {
     return IV_SIZE;
 }
METHOD (aead_t , get_iv_gen , iv_gen_t * , private_ccm_aead_t * this)
Definition at line 315 of file ccm_aead.c.
 {
     return this->iv_gen;
 }
METHOD (aead_t , get_key_size , size_t , private_ccm_aead_t * this)
Definition at line 321 of file ccm_aead.c.
References crypter, and SALT_SIZE.
 {
     return this->crypter->get_key_size(this->crypter) + SALT_SIZE;
 }
METHOD (aead_t , set_key , bool , private_ccm_aead_t * this, chunk_t key)
Definition at line 327 of file ccm_aead.c.
References crypter, chunk_t::len, memcpy, chunk_t::ptr, salt, and SALT_SIZE.
 {
     memcpy(this->salt, key.ptr + key.len - SALT_SIZE, SALT_SIZE);
     key.len -= SALT_SIZE;
     return this->crypter->set_key(this->crypter, key);
 }
METHOD (aead_t , destroy , void , private_ccm_aead_t * this)
Definition at line 335 of file ccm_aead.c.
References crypter, and free().
 {
     this->crypter->destroy(this->crypter);
     this->iv_gen->destroy(this->iv_gen);
     free(this);
 }
static bool verify_icv (private_ccm_aead_t * this, chunk_t plain, chunk_t assoc, chunk_t iv, char * icv) static
Verify the ICV
Definition at line 253 of file ccm_aead.c.
References create_icv(), and memeq_const().
Referenced by METHOD().
 {
     char buf[this->icv_size];
     return create_icv(this, plain, assoc, iv, buf) &&
            memeq_const(buf, icv, this->icv_size);
 }
Variable Documentation
b0_t
Definition at line 79 of file ccm_aead.c.
Referenced by build_b0().
ctr_t
Definition at line 98 of file ccm_aead.c.
Referenced by build_ctr().