strongSwan: rr_set_t Struct Reference
rr_set_t Struct Reference
rr_set
#include "rr_set.h"
Public Attributes
enumerator_t *(* create_rr_enumerator)(rr_set_t *this)
enumerator_t *(* create_rrsig_enumerator)(rr_set_t *this)
void(* destroy)(rr_set_t *this)
Detailed Description
A set of DNS Resource Records.
Represents a RRset as defined in RFC 2181. This RRset consists of a set of Resource Records with the same label, class and type but different data.
The DNSSEC signature Resource Records (RRSIGs) which sign the RRs of this set are also part of an object of this type.
Definition at line 39 of file rr_set.h.
Member Data Documentation
enumerator_t*(* rr_set_t::create_rr_enumerator)(rr_set_t *this)
Create an enumerator over all Resource Records of this RRset.
Note
The enumerator's position is invalid before the first call to enumerate().
Returns
enumerator over Resource Records
Definition at line 49 of file rr_set.h.
Referenced by main(), and METHOD().
enumerator_t*(* rr_set_t::create_rrsig_enumerator)(rr_set_t *this)
Create an enumerator over all RRSIGs of this RRset
Note
The enumerator's position is invalid before the first call to enumerate().
Returns
enumerator over RRSIG Resource Records, NULL if there are no RRSIGs for this RRset
Definition at line 60 of file rr_set.h.
Referenced by main(), and METHOD().
void(* rr_set_t::destroy)(rr_set_t *this)
Destroy this RRset with all its Resource Records.
Definition at line 65 of file rr_set.h.
The documentation for this struct was generated from the following file:
rr_set.h